### ISSUE TITLE
Protolathe Infinite Build Time

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#10113]
I don't know what causes the fucking thing but I came back to research and anytime somethign was made in protolathe it would never get made and the research console would get frozen.

Around 11:30 am est 6/23/2015 Sybil

**Comment by xxalpha** [comment]
What were you building exactly?

**Comment by Iamgoofball** [comment]
What were you building, what was the upgrade level, etc etc.

**Comment by Invisty** [comment]
I got this once while trying to build the base-tier scanning modules. None of the other items I tried to build were triggering this problem.

Rebuilding the protolathe did not fix it.
Rebuilding the RnD console fixed it.
