### ISSUE TITLE
New explosion code leaves some old explosives feeling underwhelming

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/tgstation#10118]
The new explosion code (and increased bomb cap) lets us have more realistic and entertaining explosions.
While toxins can reach the new cap with zero effort, other explosives (syndie bomb/payload/bluespace beaker nades etc) are now comparatively weaker.

For example trying to damage shit on the other side of a r-wall (like tcomms or genetics) with a syndie bomb is now far far harder, since the wall aborbs a lot of the damage.

So while I think it's fine for example, that water/potassium nades stay as they are, a few other things mainly the syndie bomb, ought to be looked at since they've effectively been nerfed pretty hard.

**Comment by Iamgoofball** [comment]
Black Powder scaling could probably be adjusted.

**Comment by Lumipharon** [comment]
Just be careful to not make gibbing to easy. Blackpowder gib darts on shotguns while hilarios as fuck, were pretty awful to be on the recieving end of.

https://tgstation13.org/phpBB/viewtopic.php?f=33&t=3589&p=88959&hilit=explosion#p88959 has some pictures that highlight this issue.
Syndie bombs on the otherside of the tcomm APC wall is so weak that the apc has a reasonable chance of being undamaged.

**Comment by WJohn** [comment]
Just raise the value of syndie bombs, then?

**Comment by Jalleo** [comment]
Maybe we need to make a scaling system so the explosions themselves can scale to the set bombcap.

**Comment by phil235** [comment]
Is this still an issue?

**Comment by Lumipharon** [comment]
Yes. That recent pr simply made them harder to detect (which kind of defeats the purpose of them/checking the wires before use), but they're still really weak whenup against r-walls and shit.

**Comment by phil235** [comment]
I'm declaring this fixed, the whole issue with syndibomb not being able to blow up telecomms from above was because of a bug in explosion that was fixed in #11061.

**Comment by nullbear** [comment]
This should only affect chemical explosives right now. If syndie bombs are having this issue, it is due to the damage refactoring.

**Comment by nullbear** [comment]
Or some other bug. Whoops didn't read Phil comment
