### ISSUE TITLE
Progress bar bugs

### ISSUE THREAD

**Issue by freerealestate** [tgstation/tgstation#10128]
If you strip someone prone, the bar is rotated 90 degrees, but isn't above their head.

If you strip multiple items, multiple bars appear layered on top of one another, and each moves to the top of the pile each time the bar updates. I don't think there'd be an easy fix for this given the lack of screen space available on a tile (though maybe they could stack upwards, onto other tiles?), but I thought it was worth mentioning anyway.

Deconstructing broken turrets with a crowbar doesn't show a progress bar (probably a request, not a bug)

**Comment by WJohn** [comment]
@Iamgoofball 

Maybe he can find a way to stack progress bars in a sort of queue if you do multiple things on one object, with the first action being continuously shifted up and the newest being at the bottom.

**Comment by Jordie0608** [comment]
Repairing windows with welding tools doesn't complete.

**Comment by Iamgoofball** [comment]
I'm not really certain about what to do for the prone bug.

@WJohn Maybe. I'll check it out.

Broken turrets not using a progbar means it's not using do_after() and is probably using old outdated code.

@Jordie0608 The bar or the act of repairing?

**Comment by MrStonedOne** [comment]
@Iamgoofball the bar never shows, and the repair never happens.

**Comment by phil235** [comment]
>Repairing windows with welding tools doesn't complete.

Will be fixed by #10168

**Comment by Anonus** [comment]
They also get color from the object you're trying to do stuff to, so pipes and all get colored progress bars.

**Comment by MrStonedOne** [comment]
Thats a byond limitation.

in order to show the progress bar to only you, it adds it as a hud icon to that object, this is a internal byond system. Sadly it copies the color of the object
