### ISSUE TITLE
current explosive implants don't set off syndibombs in your backpack

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/tgstation#10161]
If you have the bomb core of a syndibomb in your backpack and use an explosive implant to explode yourself, the bomb in your backpack won't explode. Instead, the small explosion from the implant occurs and you gib.

Edit: May or may not have been fixed by the new microbomb implants. Time to test.

**Comment by MoreRobustThanYou** [comment]
this should be fixed by #31516

**Comment by lzimann** [comment]
Should be fixed by #31516
