### ISSUE TITLE
Floating animation not just broke it broke completely

### ISSUE THREAD

**Issue by Razharas** [tgstation/tgstation#10190]
I have no idea what happened but only coming back to the gravity fixed it

![image](http://i.imgur.com/kUOXE65.gif)

**Comment by Razharas** [comment]
@MrPerson

**Comment by Razharas** [comment]
Sick moonwalking by the way

**Comment by MrPerson** [comment]
Feature?

**Comment by WJohn** [comment]
Zero G moonwalking :+1:

**Comment by Razharas** [comment]
@phil235

**Comment by phil235** [comment]
No idea what could cause that.

**Comment by optimumtact** [comment]
old higgs bugson

**Comment by phil235** [comment]
Happened right now to someone on Basil. Still no idea what causes it exactly but it's apparently clientside only. The player looked fine to me while he reported being stuck in a direction while moving in space. The bug started when he got in space, and stopped when he came back on non-space tile. Player was CE with CE hardsuit and traitor. Singulo was loose.

**Comment by PraiseRatvar** [comment]
@optimumtact did somebody say old higgs bugson. just close this
