### ISSUE TITLE
Supply request console cannot print crate access restriction properly.

### ISSUE THREAD

**Issue by kyrahabattoir** [tgstation/tgstation#10225]
they just print: "ACCESS RESTRICTION: $Err$ Unknown Error."

**Comment by bgobandit** [comment]
I cannot reproduce this, when I try it prints the access text normally

**Comment by Core0verload** [comment]
Looks like it was already fixed in one of the cargo refactors.

**Comment by bgobandit** [comment]
why is this still open then

**Comment by ShizCalev** [comment]
@lzimann can be closed
