### ISSUE TITLE
Transform sting + Impersonation objective = Tears

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/tgstation#10236]
1) Have to impersonate John Jackson, the HoP
2) Another changeling uses a transform sting on the HoP, changes him into Jack Johnson
3) Be SOL because the target DNA is destroyed

**Comment by Xhuis** [comment]
daily reminder that changeling objectives need an overhaul

**Comment by Kromgar** [comment]
Changeling objectives are objectively shit.

**Comment by Anonus** [comment]
Changeling objectives would be good if they had the tools to actually do them, but if they did they'd be the strongest antag, bar none.

**Comment by Miauw62** [comment]
changeling is objectively shit

**Comment by CPTANT** [comment]
tranformation sting is bullshit when used for ANY purpose. You can also instantly and undetectable give every crewmember an SE full of disabilities

**Comment by Ikarrus** [comment]
As the person who made transform sting work on living mobs in the first place, I agree, it's bullshit, and I regret making it that way.

**Comment by Dorsisdwarf** [comment]
Transform sting should automatically channel the targets DNA to the hivemind, to avoid fucking lings over irreperably
