### ISSUE TITLE
Smokable transfer rate is lower than the metaboliation rate of most chemicals

### ISSUE THREAD

**Issue by apuh3** [tgstation/tgstation#10245]
What it says on the tin.  Firstly, it means you'll only get the effects of your chemicals every few ticks, which can be jarring, especially if one of the chems is a stimulant. Secondly, it means you'll never overdose on anything, including niccotine, crank, meth, ephedrine, etc. from cigarettes.

**Comment by Marflowerose** [comment]
It's not that it's jarring, it's that the chems don't really do anything, at least meth doesn't. It gives the shakes and all but no added speed at all.

**Comment by Invisty** [comment]
I believe this affects the Syndie cigarettes from the uplink too. I purchased a pack the other day (as I'd never tried them and needed to heal myself) and... they do sweet fuck all.
