### ISSUE TITLE
Cyborg leg missing from exosuit fabricator menu.

### ISSUE THREAD

**Issue by Invisty** [tgstation/tgstation#10242]
**Problem Description:** After syncing an exosuit fabricator and clicking "build all" for a cyborg, I don't get a complete set of cyborg parts. Checking the cyborg menu shows that one of the legs (I think it's the right leg) is missing. 

**What did you expect to happen:** I should be able to build a full set of cyborg parts.

**What happened instead:** The cyborg construction menu is missing a leg!

**Why is this bad/What are the consequences:** No cyborgs, yo. 

**Steps to reproduce the problem:** Start game, sync console, sync fabricator, hit "build all" on the cyborg menu, don't get all the parts. 

**Server:** Sybil.

This bug might be inconsistent. I'll give it another poke when I'm home from ~~procrastinating~~ work.

**Comment by RemieRichards** [comment]
THIS WAS SUPPOSED TO BE FIXED.
I THOUGHT WE STOPPED USING REFERENCES IN FABRICATORS!?!

**Comment by Anonus** [comment]
THE LEG HAS LEFT THE BUILDING

**Comment by MrPerson** [comment]
I guess you could say it

Legged it

**Comment by RemieRichards** [comment]
@MrPerson DID YOU ACTUALLY JUST.

**Comment by MrPerson** [comment]
I just felt the knee'd to share

**Comment by RemieRichards** [comment]
@MrPerson OMG STOP

**Comment by Invisty** [comment]
Guys this is a serious issue that is really *crippling* cyborgs please take it seriously.

**Comment by RemieRichards** [comment]
>crippling

YOU PEOPLE.

**Comment by Ricotez** [comment]
are legs really missing

are you sure you didnt

<i>fabricate</i> it

**Comment by PKPenguin321** [comment]
this bug is gamebreaking, i'm sure cyborg players wont stand for this

**Comment by Ricotez** [comment]
someone should probably <i>step</i> in, this discussion has <i>run</i> its course

**Comment by Dorsisdwarf** [comment]
On a more serious discussion, it might be important to confirm this issue!

It's a (rare) traitor tactic to delete something innocous, like a cyborg leg or flash from the R&D server, as they cannot be re-researched and therefore permanently cripple R&D.

It's important when making an issue to be certain you have a leg to stand on.

**Comment by Strathcona** [comment]
Wait, you can't re-research basic items? Isn't that a bug? That permanently amputates R&D options when sabotaged. We should give them some sort of crutch to fix that if it happens.

**Comment by duncathan** [comment]
This is hilarious. I'm falling over laughing.

**Comment by phil235** [comment]
>Steps to reproduce the problem: Start game, sync console, sync fabricator, hit "build all" on the cyborg menu, don't get all the parts. 

Cannot Reproduce

**Comment by Dorsisdwarf** [comment]
Applying not a bug for now, unless we can somehow prove that this unreproduceable bug was not, in fact, a traitor or AI deleting the leg from the records

**Comment by optimumtact** [comment]
old with no repro
