### ISSUE TITLE
New AI law inconsistencies

### ISSUE THREAD

**Issue by GunHog** [tgstation/tgstation#10263]
When building a new AI, you can apply law boards directly to the core. Since AIs built without having a board applied become Asimov, the general expectation is that the unfinished core has Asimov laws as well (it is in fact null).

If someone uses a freeform board on an AI core (such as "All lizards are human"), that AI will have only that law, not Asimov plus that law. Furthermore, applying a purge board clears the laws set with other boards, but if an AI is a built with cleared laws, it will become Asimov, when the user is attempting to crate a purged AI.

My recommendation: Have unfinished AI cores start with the same laws (accounting for server config as well) a new AI would. That is what most players expect; it should be consistent and possible to create a purged AI or modified default version of the laws, just as if you were modifying an active AI via an upload console.

**Comment by freerealestate** [comment]
I had no idea this was a thing

**Comment by optimumtact** [comment]
did somebody die to this

please say somebody died to this

**Comment by GunHog** [comment]
I did not die to this, the AI I built was put into a Gygax, so it could not cause as much damage as a core-only AI. I gave an AI a "Lizards are human" freeform law, and wound up with an AI having ONLY that law. It, too, was a bro and allowed a proper reset.

**Comment by optimumtact** [comment]
dang it

**Comment by optimumtact** [comment]
@xxalpha claims this is impossible in current code

**Comment by GunHog** [comment]
@xxalpha's claim is false:

In fact, it is **different** now. 
![screenshot 2016-05-24 17 57 45](https://cloud.githubusercontent.com/assets/4955510/15522587/210e7b68-21d9-11e6-9802-a6bfcbd4e9dc.png)

![screenshot 2016-05-24 17 57 48](https://cloud.githubusercontent.com/assets/4955510/15522589/24f7a1c8-21d9-11e6-8c4d-1df2ea89750d.png)

Secondary AI attempt, I applied a corporate board, then a freeform to an AI, which worked.
![image](https://cloud.githubusercontent.com/assets/4955510/15522665/ad56120c-21d9-11e6-8664-ce1994eeb2c7.png)

I believe the issue is that you must apply a core law board before uploading a non-core freeform.
