### ISSUE TITLE
Resonant shriek bypasses earmuffs

### ISSUE THREAD

**Issue by CPTANT** [tgstation/tgstation#10294]
The changeling resonant shriek ability is unaffected by earmuffs, which is odd since resonant shriek is supposed to work by emitting a very high pitched sound. Earmuffs blocking sound should block the effect.

**Comment by Supermichael777** [comment]
shakes the earmuffs/your skull. shows how often earmuffs get used. note that it does this because it needs to take down sec to be useful so it bypasses the check for ear protect used by flashbangs present on bowman headsets and earmuffs. this is intentional.

**Comment by Nitrousoxide** [comment]
Maybe split ear protect into two vars one for bowman headsets and one for earmuffs.  You're giving up a lot to wear earmuffs (being cut off from all sound at all) versus the bowman headsets which have no downsides.
