### ISSUE TITLE
Implants are inconvenient to use 

### ISSUE THREAD

**Issue by SconesC** [tgstation/tgstation#10319]
Minor ease of use complaint, sort of annoying there is no hotkey option and I have to click a big 'ol UI button on my screen

**Comment by Rinoka** [comment]
Could be improved by making it so that the 1-2-3-4-5-etc keys we have for stuff like Cyborg modules could be used with the UI buttons. I don't know the UI button code, though, so it might not be so easily done.

**Comment by SconesC** [comment]
1-5 already bound to intents

**Comment by Rinoka** [comment]
Orite.

Shift+#?

**Comment by SconesC** [comment]
C V Z all unbound

**Comment by WJohn** [comment]
Shift+1-0 would be nice for action buttons, actually.

**Comment by Rinoka** [comment]
I think that idea's good; 1-0 for the big UI buttons, and shiftlock the intent swaps so that people don't switch accidentally. (I eagerly await people accidentally macrobombing because they hit 4 without hitting shift.)

**Comment by SconesC** [comment]
intents are more important than the ui buttons

make ui shift#

**Comment by Rinoka** [comment]
Leaving it up to whoever PRs it; both are validly interesting.

Personally, there's benefits to locking intent changes behind shift and downsides, but however it's done it'll be somethin' people will use, so hey.

**Comment by Dorsisdwarf** [comment]
It baffles me that buttons are considered "inconvenient to use" by anyone who ever tried to use adrenals when you had to *wink

**Comment by SconesC** [comment]
At least BYOND supports macros for text input, so you could bind a key to "t *wink enter" on your numpad
