### ISSUE TITLE
Brains cannot speak with deadchat despite being considered dead

### ISSUE THREAD

**Issue by Chocobro** [tgstation/tgstation#10332]
they are also completely unable to ghost.
extra info: i was a monkey's brain. i was NOT in an MMI.

**Comment by PKPenguin321** [comment]
i thought they were able to ghost? if they're not that's a pretty big issue
and yeah, iirc they can hear but cannot speak to deadchat

**Comment by Lumipharon** [comment]
just move, and you ghost.

**Comment by duncathan** [comment]
Still a bug that they can't speak on dead chat without ghosting.

**Comment by Chocobro** [comment]
yeah, I was able to hear deadchat at the time.
