### ISSUE TITLE
Borg cultist buggy thing

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/tgstation#10369]
Borging a cultist will deconvert the cultist but if you are ever deconstructed or blown and the brain is placed in your old body, you are no longer a cultist but still have the communicate verb with a cultist tab.  A rare case but a bug none the less.

**Comment by Lumipharon** [comment]
Why did we make borging people de-antag them? It makes no logical sense and removes FUN, like antags trying to do their thing within the bounds of their laws etc.

**Comment by Miauw62** [comment]
So people actually borg antags instead of spacing them.
Op 4-jul.-2015 10:08 schreef "Lumipharon" <notifications@github.com>:

**Comment by Lumipharon** [comment]
But they borged antags before the change, and they still kill them outright after the change.

**Comment by Miauw62** [comment]
afaik you were never considered an antag after you were borged.

**Comment by RemieRichards** [comment]
we have procs (that I wrote) that fully cull antagonist status from a mind datum, but we don't actually use them on borgs as it was voted against.

what we do have is an OOC line of text added to the characters notes that tells them their objectives are automatically failed.

**Comment by PKPenguin321** [comment]
i thought we made it so borging fully removes cult and rev status since there were bugs that let you see who was rev and cultist even though you were borged?

**Comment by Lumipharon** [comment]
that was done for non cult constructs, even though by the time it was merged, the problem was already fixed, so the could be said for borging.

**Comment by Niknakflak** [comment]
When I tested it in game, it actually deculted me, completely.  I just had the tab still.

**Comment by ChangelingRain** [comment]
fix'd
