### ISSUE TITLE
No way of knowing overdose threshold

### ISSUE THREAD

**Issue by freerealestate** [tgstation/tgstation#10385]
I injected a dude with kelotane in a sleeper, thinking I was helping him, but he actually ended up nearly dying over an overdose. There should be some sort of indication in the sleeper when a dose is reaching excessive amounts.

**Comment by WJohn** [comment]
I think there was a PR up at one point that gave really detailed information on this sort of stuff for either chem masters or health analyzers, but I think that either didn't get merged or was specifically censored to keep you in the dark for whatever reason.

**Comment by freerealestate** [comment]
Well that's stupid, because people learn the 30u+ in an overdose meta anyway. It just means a few players have to die/nearly die over overdoses needlessly first.

**Comment by xxalpha** [comment]
Overdose is retarded.

**Comment by Tokiko1** [comment]
Similar thing also happens with the genetics machines, where the "rejuvenators" are actually disguised epinephrine and can kill the occupant.

**Comment by Iamgoofball** [comment]
1. I'll add a way to tell thresholds on sleepers.
2. The Chem-Master can show all info about chemicals including overdose and addiction thresholds by clicking either the name of the chemical or the analyze button on it when it's in a chem master, can't remember which one it is. Either way you can tell thresholds with that in game.
3. I'll check out the genetics machine, I thought I switched it to inaprov.

**Comment by Kelenius** [comment]
Sleepers shouldn't overdose you in the first place.

**Comment by Iamgoofball** [comment]
@Kelenius You only need to hit the button once. Don't hit it 50 times.

**Comment by Dorsisdwarf** [comment]
Maybe Kel means that there's a 20u cap on all sleeper reagants to stop you from filling people up?

Also you need to hit the button twice for fully effective healing with most meds

**Comment by Iamgoofball** [comment]
20u inject cap is a good idea.

**Comment by freerealestate** [comment]
An inject cap just limits what traitors can do with sleepers. A warning
about the overdose threshold for each chem on the UI would be better.

**Comment by Iamgoofball** [comment]
That works too.

**Comment by Kelenius** [comment]
"Let's make a system that prevents people from poisoning other people with sleepers, and tune numbers so they can poison people but not too much".

I get that it's NT but geez. They really shouldn't be able to inject people if a fresh injection would overdose.

**Comment by freerealestate** [comment]
I agree, it doesn't make sense to warn people about the potential for
overdose but allow them to do it anyway.

A solution might be to add the dose cap, but also make it so you can emag
or hack sleepers to remove it.

**Comment by CyberbossJHCB** [comment]
Wasn't this fixed? You can't inject more than 20u anymore
