### ISSUE TITLE
Alien hunter leaping shifts a tile to the left upon smashing into something.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#10428]
![](http://i.imgur.com/xPksHDQ.png)

I jumped straight up in this scenario, and shifted a tile to the left upon smashing into the wall for a split second, then back to the appropriate tile.

**Comment by phil235** [comment]
Probably the pixel shift not being updated quickly enough.

**Comment by phil235** [comment]
Actually I think it might be due to throw code.

**Comment by WJohn** [comment]
This is back, except now it's to the bottom left instead. Happened after the most recent xeno changes in #19720

**Comment by Repukan** [comment]
Ausops tested this today, can be closed, doesn't happen anymore.

@Cyberboss

**Comment by CPTANT** [comment]
@Dorsisdwarf fixed.
