### ISSUE TITLE
Mind-swapping with a loyalty implanted person as a rev keeps your rev status while still showing you as being implanted.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#10431]
Basically what the title says.
May become an issue with datum antags interacting with each other in the future.
@Incoming5643

**Comment by Incoming5643** [comment]
Living on the edge.

Will have to handle this in antag datums

**Comment by palpatine213** [comment]
Yeah. antag datums are going to uncover a ton of weird hidden bugs due to things interacting that were never meant to interact.

**Comment by Supermichael777** [comment]
this will require *POLICY DISCUSSIONS* on how such edge cases should be resolved. also what kind of anemic excuse for a wizard supports any government but a magic based oligarchy/theocracy.

**Comment by Dorsisdwarf** [comment]
[edge case]
