### ISSUE TITLE
Borg Power Drain is not Flat

### ISSUE THREAD

**Issue by Nitrousoxide** [tgstation/tgstation#10469]
As a sec borg I charged to full and with no modules on let my power drain for one minute.  I lost ~50-60 power units.

I put three modules in but didn't activate them and waited the same minute.  I lost 500-600 power units.

A ten fold increase in the power drain does not seem right.  It seemed to be draining at about the same rate on a per second basis, but every 6 seconds about 100 power units would get sapped from the cell.

Date Tested: Yesterday

**Comment by Miauw62** [comment]
what modules were these?

also module power drain was supposedly removed, @Cheridan

**Comment by Nitrousoxide** [comment]
I had a taser, a stun baton, and cuffs on.

The stun baton was turned off, but tried it on and saw the same results.

**Comment by Nitrousoxide** [comment]
Just did some more testing and with just the disabler on (and it fully charged having just been made into a borg with no shots fired) I was getting the same battery drain.  I tried the stun baton by itself and didn't see any unusual batter drain, and the same with the cuffs.  So it may be just the disabler causing the huge drain on the secborg.

**Comment by Jalleo** [comment]
This is the offending code. https://github.com/tgstation/-tg-station/blob/cf6eca2d472b6e8c2ca80b7ba9f18678a8068173/code/modules/projectiles/guns/energy/special.dm#L237

I believe by what I am seeing is that while charge is less than recharge time ( all the time ) it processes to take the power required to fill the object but it dosent check if its charged.
This means the disabler module was a even bigger drain before @Cheridan changed it.
I think a simple check to see if it is charged will do.
Nitpick
Maybe even having it taken off the process list once charged until the cyborg uses it or gets emp'd will also help save a small amount of processing time.

**Comment by ChangelingRain** [comment]
this is also fixed
