### ISSUE TITLE
Crew monitor stays active even once you step away from the computer

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#10471]
Yea, mixed feelings on this change already... but it's definitely past the "broken" mark when I can run around the station with near-omniscience.

**Comment by freerealestate** [comment]
It's NanoUI, so it should stop updating when you move away from it. The eye in the top corner should change to red to indicate it's no longer updating.

However, you can run around with a portable crew monitor in your pocket and it will continue to update despite you being logically unable to see it. I like that though, so I shouldn't have mentioned it because I don't want it fixed.

**Comment by PKPenguin321** [comment]
>I like that though, so I shouldn't have mentioned it because I don't want it fixed.

you for real nigga

**Comment by freerealestate** [comment]
Are you just going to enter every issue I comment on now and find fault with what I've written? Maybe I should change my username to try to throw you off the scent.

For real though, nigga, I care more about balance than what suits me in the short-term.

**Comment by Miauw62** [comment]
its not nanoui

**Comment by MrStonedOne** [comment]
its nanoui 2.0

**Comment by Robustin** [comment]
If an issue bothers me enough to get me to drag my ass here and post about it, you can be 99% sure that I'm not wrong about it. You can disagree about the subjective stuff, but I did not hallucinate my crew monitor map staying updated as I roamed the station (without any portable crew monitor).

**Comment by neersighted** [comment]
@nullquery

**Comment by nullquery** [comment]
/datum/crewmonitor/proc/hiIsValidClient governs the validity of the client watching the computer and needs to return 1 in order for the map to remain updated. If that doesn't happen, the eye goes "red" and the map should NOT be updated.

I tested this exact case when I first built the system, so I'm wondering if I missed something or if there's a change that causes this.

**Comment by nullquery** [comment]
Just checked. There haven't been any modifications to the crew monitoring computer that would cause this problem.

Note that one feature of the system is that the AI can use it freely regardless of their proximity to a crew monitoring computer, so maybe this check is passing for humans as well. I'll look into it when I get a chance.

**Comment by nullquery** [comment]
Hold up -- just noticed that this post was made on the 6th of July. @Robustin Has this ever been reproduced after this time, or has this only occurred this one time?

**Comment by nullquery** [comment]
It looks like the bug can occur if you have a portable crew monitor somewhere in your inventory. Even if you use the stationary computer moving away detects that you have a portable version and automatically switch to it.

If you're a robot then the interface remains available so long as the crew monitoring computer remains in view (through walls is allowed).

**Comment by optimumtact** [comment]
old with no repro
