### ISSUE TITLE
Can see items through flashbang blind overlay and crit fog overlay

### ISSUE THREAD

**Issue by duncathan** [tgstation/tgstation#10511]
![Image of issue](http://puu.sh/iTPUP/29f2de134c.jpg)
Happened a couple of rounds ago on Sybil, after the shuttle arrived. No idea why it happened.

**Comment by phil235** [comment]
Were you wearing special glasses? Did you see what else was on the tile with those visible items?

**Comment by duncathan** [comment]
I was wearing engineering scanners in tray mode. All I could see on the tile was the items.

**Comment by Dorsisdwarf** [comment]
This is due to items being exploded/burned out of a backpack not resetting their HUD layer

**Comment by phil235** [comment]
Does this still happen?

**Comment by optimumtact** [comment]
doubt it
