### ISSUE TITLE
It's possible to weld into the syndicate shuttle from outside

### ISSUE THREAD

**Issue by apuh3** [tgstation/tgstation#10520]
It was made self-locking and impossible to enter from outside so we wouldn't need the overbearing "avoid the syndie shuttle if you're a crewmember" policy to keep people from looting the shuttle and spacing the nuke.  Now it's trivial to do again.
The walls should probably be made irremovable some way or another.

**Comment by freerealestate** [comment]
add
turrets

**Comment by bgobandit** [comment]
probably due to shuttle changes

**Comment by duncathan** [comment]
More likely due to unsim removal, I'd think.

**Comment by Lumipharon** [comment]
This should really be high priority to be honest.
Turrets don't do shit whenthere are blind spots and you can just juke past them anyway. The nuke getting spaced every 2nd nuke op round is terrible as shit.

**Comment by KorPhaeron** [comment]
Shuttle is covered in guns now
