### ISSUE TITLE
Powered Objects just decide if they want work or not in areas that aren't the station's Zlevel.

### ISSUE THREAD

**Issue by Summoners** [tgstation/tgstation#10530]
Seems like someone broke area and power definitions as objects just randomly decide if they want to stay on or break in that area forever. 

Some examples of this hard to explain issue that I've personally seen:

Derelicts Gravity Generator: It turns on at roundstart while the server is loading and then shuts off minutes later and can never be brought back online, I've tested this couple times and sometimes it can be brought back online but otherwise it stays down forever.

Machines on Mining Station/Asteroid: Hard to explain but even with an active APC machines will decide if they want to listen to it. After a power failure on the mining station all machines (even airlocks) stopped working even at 100% power and the APC being on, the only machine that was still functioning was the snack machine for some odd reason. 

This issue occurred on Basil but I've been told the mining issue happened on Sibyl too.

(side note: please fix quick, I can't make new spacestations due to gravity generators activating at 100% and shutting itself off. It kills everyone with radiation. :rotating_light: )

**Comment by ChangelingRain** [comment]
this probably doesn't exist if it does we'll reopen this
