### ISSUE TITLE
tinted fulltile windows can only be attacked/interacted with from certain angles

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/tgstation#10544]
Attempting to attack/knock on/unsecure a tinted fulltile window will fail unless you are standing in a certain location. Seems to be related to the dir of the window. For example, most tinted windows on metastation have a dir value of 5, which only lets you interact with them by standing directly north, northeast or east of the tile.

**Comment by francinum** [comment]
It's because the damn things are single-side, and they aren't even reinforced.

**Comment by Dorsisdwarf** [comment]
[bug]
[sprites] (They have the wrong sprite for being single-sided)

**Comment by Robustin** [comment]
Couldn't replicate
