### ISSUE TITLE
Spiders try to wrap objects they cant wrap

### ISSUE THREAD

**Issue by theOperand** [tgstation/tgstation#10579]
Seems like spiders really like going to the east, or trying to wrap unwrappable objs?
![2015-07-12 22_06_16-bagil_ mime hut phi](https://cloud.githubusercontent.com/assets/3975713/8639690/67291b8a-28e2-11e5-94af-c4e8da2fd67f.png)

I possessed the camera console and found that the spiders followed it, so they seem to try and continously get to objs they cant wrap.

**Comment by Dorsisdwarf** [comment]
I'm pretty sure spiders can detect people through walls, so they're probbably trying futilely to path to someone in tool storage

**Comment by CorruptComputer** [comment]
Spiders breaking walls when?

**Comment by Miauw62** [comment]
Nah, they followed the mining camera console when I possessed it, so it's
either that or they're pathing to ghosts
Op 13-jul.-2015 08:09 schreef "Dorsisdwarf" <notifications@github.com>:

**Comment by Bawhoppen** [comment]
this fixed?

**Comment by ChangelingRain** [comment]
I fixed this hey
