### ISSUE TITLE
RPED ghost items

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#10636]
This occured in a bluespace RPED. There's some ghost objects beneath the others, though you can't click on them or have their names highlighted, right clicking WILL show their names there.

![](http://i.imgur.com/1tR0Hjz.png)

**Comment by phil235** [comment]
The items's loc was changed w/o calling the right procs probably.

**Comment by xxalpha** [comment]
@iamgoofball Fix your loc juggling

**Comment by Iamgoofball** [comment]
spoooky

BSRPED is calling all the same procs that RPEDs call so this has to already have existed

**Comment by GunHog** [comment]
This is indeed a bug with the current RPED. I do not know what causes it, and had not a clue to fix it when I was testing my buff to the RPED.

**Comment by WJohn** [comment]
I haven't seen this bug in literal years. Will re-open if it's seen again.
