### ISSUE TITLE
Toggling Lab Coat Open is not available on right click.

### ISSUE THREAD

**Issue by Nitrousoxide** [tgstation/tgstation#10647]
Toggling your suit sensors is available on a right click.  However, the only way to open and close your lab coat buttons is via alt-click on the lab coat.

This is clearly a class A bug that needs to be fixed asap.

Version of the game: as of 7/15/15

**Comment by Anonus** [comment]
Not a bug, a feature. Read; someone removed the object verb, because they hated object verbs so much that they just had to remove one you might need.

**Comment by Incoming5643** [comment]
Alt clicking on some clothing leads to alternate styles, but not everything has alternate styles.
 
In some cases this functionality is explained in the description, other times it isn't.

Additionally some clothing can also be swapped to its alt style with attackself

In a few (usually very old) alt style items you can only attackself to swap to the alt style, alt clicking won't do it. 

Some others, like clown masks, have multiple alt styles that work on a drop down.

---

So it's a highly unstandardized mess really

**Comment by bustygoku** [comment]
This needs to be all standardized to alt-click since it's only done pretty much once per round so it doesn't necessitate an object verb or an action key. All clothing alt styles and buttons and minor aesthetics should be alt click because it's less annoying and clutter-y

**Comment by WJohn** [comment]
alt-clicking is so terribly underused though. I wish it and drag+drop were used a lot more frequently.
