### ISSUE TITLE
You can empty containers from inside lockers

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#10673]
Get in locker, drag backpack/other storage on the tile outside. 
Stuff is now outside without locker opening.

**Comment by phil235** [comment]
A missing Adjacent check probably (or maybe it checks the mob's turf instead of its real loc).

**Comment by phil235** [comment]
Apparently this is an issue with the Adjacent proc itself. A backpack on a turf, with a neighbouring closet that contains a mob, calls Adjacent(ClosetedMob) and it returns TRUE.

**Comment by Robustin** [comment]
I cannot reproduce this using the method stated in the OP.

**Comment by AnturK** [comment]
Forgot to close this one after redoing adjacent.
