### ISSUE TITLE
Mixing chamber in toxins never open [BUG]

### ISSUE THREAD

**Issue by falafox** [tgstation/tgstation#10676]
The interior airlock never opens, it keeps pressurizing forever

**Comment by falafox** [comment]
Basically, toxins dosen't work

**Comment by duncathan** [comment]
aaaaaaaa
steps to reproduce please

**Comment by phil235** [comment]
It's an old bug, might be a duplicate. To reproduce you have to open the exterior door then cycle to interior, I think.

**Comment by duncathan** [comment]
>It's an old bug

oh thank god it's not my fault again

**Comment by xxalpha** [comment]
I am almost sure the bug is that the vents in toxins chambers aren't connected to anything at all.

**Comment by Supermichael777** [comment]
well the original mapping problem was that you couldn't connect the vent to distro or it would backflow HOT DEATH into the pipe and you couldn't cycle to waste while repressurizing with air so you ended up stuck with crappy storage that goes nowhere. actually now that multitools are starting to gain programing use a whole button linking mechanism might not be a bad idea if you could activate pumps using it.

**Comment by xxalpha** [comment]
What about using one of those maintenance air tanks to repressurize the chamber?

**Comment by MrStonedOne** [comment]
Just add a scrubber and hook that up to waste

**Comment by phil235** [comment]
How about simply remove the vent altogether like in the turbine (incinerator) room?

**Comment by xxalpha** [comment]
The point is repressurization after you vent the chamber, without any way to do that you don't want to be opening a vaccuum chamber.

Also I am not sure what the scrubber would accomplish.

**Comment by phil235** [comment]
You don't have any reason to go inside the chamber itself. Plus you can always use an air canister to manually refill the chamber.

**Comment by Dorsisdwarf** [comment]
You have to enter the chamber every single time you change the pump settings.

**Comment by ExcessiveUseOfCobblestone** [comment]
I've gotten inside the test chamber tank before recently (Jan2018), at least on meta.

It just takes forever and you will be in near crit.

**Comment by ShizCalev** [comment]
fixed this.
