### ISSUE TITLE
Embedding items ignores armor

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#10728]
Get some throwing stars. Each does 30 brute+bleeding if they hit, with 10 of that coming from them embedding in you, which ignores armor; 5 stars will crit a deathsquad member.

**Comment by Lumipharon** [comment]
B-But DS are godmodeplsnerf.

That aside, a bomb sending a metal rod flying through an armored vest to me atleast, seems plausible.

**Comment by SconesC** [comment]
its the best way to kill nukememes right now

**Comment by WJohn** [comment]
Don't rods launched from a pneumatic cannon embed themselves in people? If so you could easily get a shot off and have a bunch get stuck in someone.

Alternatively, throw spears at em and force them to hunker down while they pull it out and heal up from the insane damage output that is embedded items.

**Comment by duncathan** [comment]
are you telling me that a pneumatic cannon is the best defense against a deathsquad

**Comment by WJohn** [comment]
If the rods embed, possibly yeah.

**Comment by stapler2025** [comment]
well you (at least used to be able to) launch rods out of a disposal down a hallway/into a chair/into a person and they would embed, so seems plausible

**Comment by Incoming5643** [comment]
rods from cannon only embed if you use the highest setting, which also knocks the firer down.

That said a cannon full of throwing stars...

But yeah the balance of throwing stars is that if someone dies with one lodged in them you can't get it out short of surgery. They're almost one use only.

**Comment by Cebasiz** [comment]
spears and rods are really nasty. i've seen nukeops teams lose to them because one or two ops will go down from bleeding due to a thrown spear. it's almost like spears are useful these days; who would have thought?
