### ISSUE TITLE
Abandoned teleporter tiles are bork

### ISSUE THREAD

**Issue by Midaychi** [tgstation/tgstation#10748]
What I did: Teleported to abandoned teleporter

What I expected: Ability to walk around or at least do anything besides float there helplessly

What happens: The tiles there don't register, and turning them into tiles/building a grille/whatever doesn't register/update your ability to move. A normal mob can just throw and null grav around, but something like a drone gets stuck 4 ever.

I've noticed something similar on the exposed space tile outside the eastern door on the north eastern solar part of the derelict.

**Comment by AlexanderUlanH** [comment]
Isn't that because the abandoned teleporter doesn't have a gravity generator?

**Comment by Kromgar** [comment]
It has no gravity boi

**Comment by Midaychi** [comment]
Yes but being near tables and grilles and stuff should let you move in null grav.
Constructing them on the abandoned teleporter does nothing and does not allow movement.

**Comment by MrStonedOne** [comment]
@AlexanderUlanH @Kromgar If you aren't gonna read the PR don't comment.

>What happens: The tiles there don't register, and turning them into tiles/***building a grille/whatever doesn't register***/update ***your ability to move***.

Either you don't know enough about the game to be commenting on issue reports or you didn't read the pr and shouldn't have commented. 

Either way all you did was make yourselves look like jackasses

**Comment by Repukan** [comment]
@ChangelingRain This is fixed, making a grille now allows you to move.

**Comment by CPTANT** [comment]
@Dorsisdwarf  fixed
