### ISSUE TITLE
Mechs and plastic flaps

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#10741]
I've just seen a mech walk through plastic flaps
Wtf.
Humans can't fit
Why should a huge mech fit?

**Comment by phil235** [comment]
Codewise, it fits for the same reason that a window, grille or cabinet fits in.

**Comment by Dorsisdwarf** [comment]
I think this falls under consistency issue, not bug. 

Also more things should be able to go through plastic flaps, like drones and borgs

**Comment by Supermichael777** [comment]
humans just don't get these weird plastic things!

**Comment by Dorsisdwarf** [comment]
Mechs can go through plastic flaps because they're big enough to push the flaps aside, I guess.
