### ISSUE TITLE
Issue with firelock construction

### ISSUE THREAD

**Issue by phil235** [tgstation/tgstation#10750]
You can build a firelock on top of another one.

You cannot build a reinforced firelock from scratch, you need a reinforced assembly from an existing firelock.

@Xhuis

**Comment by GunHog** [comment]
Why not just refuse to merge it until he met your concerns?

**Comment by phil235** [comment]
It's really minor stuff and I didn't want that big PR to get conflicted.

**Comment by Xhuis** [comment]
I'm sorry I haven't had time to work on this. I'll fix this in a few days once I do, or someone else can make a PR for it.
