### ISSUE TITLE
Action buttons are very slow to update.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#10774]
This can cause problems for wizards, especially with charged spells like lightning bolt, where he can accidentally queue up multiple lightning bolts without being able to fire them. It also generally feels really clunky for it to update that slowly when the rest of the UI has been made so much faster.

Also I'd like to point out that the progress bar can get wonky with this @Iamgoofball

**Comment by AnturK** [comment]
Right now action buttons are only updated on each life call, i suppose that could be moved to some faster controller

**Comment by Iamgoofball** [comment]
idk what to do about this

**Comment by WJohn** [comment]
To elaborate further, lightning bolt's progress bar does not cancel out when you fire early, and if you make the recharge speed on the spell fast enough (3 seconds) it can easily be spammed faster than the progress bar can finish, resulting in some weirdness with another bar immediately (and maybe inaccurately) appearing right after the last.

**Comment by AnturK** [comment]
The minimum cooldown was supposed to be equal to maxium charging time, i just messed that up. I'll see what i can do about the progress bar

**Comment by WJohn** [comment]
Also while you're at it, could you look into the progress bars that appear when attempting to devour someone as a xeno? It creates a bar that finishes quickly, and THEN shows a much longer duration bar. You might also want to see if this happens when trying to eat a monkey when you're obese.

**Comment by Iamgoofball** [comment]
@WJohn i didn't even know magic used progress bars, I thought they were on the ancient manual timing system

i can look into the xeno shit tho
