### ISSUE TITLE
Irrelevant piece of crate code

### ISSUE THREAD

**Issue by Jalleo** [tgstation/tgstation#10831]
This is no longer used and must of been back when food required to be cold to stay fresh

https://github.com/tgstation/-tg-station/blob/master/code/game/objects/structures/crates_lockers/crates.dm#L66

**Comment by freerealestate** [comment]
I always wondered why we had freezer crates, a fridge and a kitchen coldroom. Always thought it was fluff.

**Comment by callanrocks** [comment]
That was a cool feature bring it back. More accidental chef poisonings.

**Comment by Iamgoofball** [comment]
@sawu coded food caring about temperatures, and having to keep foods at certain temperatures

eg. no letting food sit around in the Danger Zone(this is what it's actually called, not memeing it up here) else it's bad 4 u
