### ISSUE TITLE
Random and picked wizard names can run afoul of the name character limit . . .

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#10884]
Which isn't actually enforced for player names, thus just making it an annoyance for wizards who want to name themselves "Lord of the Twelve Suns, Greatest of His Line" or whatever the fuck they're coming up with.

**Comment by Anonus** [comment]
As an example, a wizard was named, presumably via random name, "Archchancellor the Seethi" which is 25 characters with spaces, while a player was named "Mortimer Q. Stumblebuttons" which is 26 with spaces, definitely not random, and has more characters than the wizard's name.

**Comment by Iamgoofball** [comment]
Let's increase the Name Character Limit then.

**Comment by JustinBNewton** [comment]
I think its a issue with the wizard name setting itself, not the name character limit applied to all names.

**Comment by PKPenguin321** [comment]
>Let's increase the Name Character Limit then.

**One day while Andy was masturbating, Woody got wood. He could no longer help himse** says, "Penis"

**Comment by Iamgoofball** [comment]
I don't see a problem with that.

**Comment by PKPenguin321** [comment]
me neither honestly

**Comment by Firecage** [comment]
To be fair PK, people would already get bwoinked for having retarded names. So using that as an example is kinda silly.
