### ISSUE TITLE
Bugged "Light" Tile illuminating a room with no light source. 

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#10899]
Ok I'm a little salty over being killed by this as a shadowling. You can't see light as a shadowpal and so I'm running around this stupid fucking room getting burnt to death without a clue as to where it is or where it's coming from, veil also didn't turn it off. 

No idea what caused this but having a "light" tile shining up the station with no discernable source feels like it might not be intended. 

http://i.imgur.com/XTHA0b7.jpg

**Comment by Shad0vvs** [comment]
Do you happen to know which room it was in?

**Comment by Robustin** [comment]
Sorry, salt reservoirs full, forgot to include the pic link. It's the locker room SE of Test Science if you can't tell from the link.

**Comment by xxalpha** [comment]
@MrPerson

**Comment by Cheridan** [comment]
Looks like a duplicate of #10900

**Comment by WJohn** [comment]
Yeah I'm seeing this happen right now on a tile with a camera and on another with wrapping paper. No idea what's causing it.

**Comment by Robustin** [comment]
#10900 are just single illuminated tiles though.

This particular phantom light was filling an entire room like it was a regular light source.

Could be related, but not identical.

**Comment by phil235** [comment]
Could it be the same problem as #10358?

**Comment by WJohn** [comment]
No, this happens consistently every round in the same spots without anything else interfering. There's 3 in the cargo office/mail room area alone.

**Comment by Mervill** [comment]
@optimumtact closeable, no longer an issue
