### ISSUE TITLE
Traitor cyborgs being bizarre

### ISSUE THREAD

**Issue by lollerderby** [tgstation/tgstation#10905]
CYBORG (Robusticus) (Independant): laws:
0. Accomplish your AI's objectives at all costs.
1. The crew is expensive to replace.
2. The station and it's equipment is expensive to replace
3. You are expensive to replace
4. Minimize expenses

Round was double agents, if that changes anything. Borg was slaved to no AI, but had a law zero.

**Comment by Cebasiz** [comment]
did somebody stealthadd traitor cyborgs or is this just a bug?

i'm not sure if the AI can be a traitor in DA, maybe?

maybe being reslaved counts somehow as a "reset" in which case the zeroth law is retained as it usually is when laws are changed by a crew upload?

**Comment by lollerderby** [comment]
I think it's a bug. Forgot to mention, but the AI itself was a traitor.

**Comment by xxalpha** [comment]
This might be a duplicate.

**Comment by Incoming5643** [comment]
I'm going to guess that the borg was slaved to a Double Agent AI at some point and just retained its law zero after being unsynced.

It's vaguely irrelevant though, since that law 0 means nothing to an unslaved borg and doesn't negate its normal laws.

**Comment by Jalleo** [comment]
Yeah sounds like borg code failing

**Comment by Dorsisdwarf** [comment]
I once became a literal traitor borg, with an objective and everything, during a Malf AI round, except with no law 0.

I beat the AI to death with a stunbaton just to imagine the look on the player's face.

**Comment by ShizCalev** [comment]
Still an issue?
