### ISSUE TITLE
Field generators bug out horribly if they are hit by an emitter beam before they are secured

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/tgstation#10907]
See title of this issue. Once this happen, stuff gets weird. Attempting to secure them in this odd state will give you the "Turn it off first." message. If you wait until they turn off, attempting to weld them will give you a confusing message about how you are now starting to cut them loose, even though they are not anchored in the first place. They will still connect to other field generators and create a field, which will fail after a second or so, shutting down all other connected field generators in the process too, regardless of their charge.

**Comment by AnturK** [comment]
Can't reproduce. Emmiter code was probably changed since this was reported

**Comment by WJohn** [comment]
![](http://i.imgur.com/OUOMC0M.png)

Something to this extent happened, I'm not sure how.

**Comment by bgobandit** [comment]
Cannot reproduce though people have reported field gens being fucky

**Comment by actioninja** [comment]
inactive issue with multiple cannot reproduce, not useful.
