### ISSUE TITLE
Timing glitches with flick()

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/tgstation#10917]
flick() used to basically act as a sleep for the duration of the animation.

This doesn't seem to be the case anymore, leading to weird animation glitches like with our cinematics and false wall animations.

**Comment by WJohn** [comment]
Yeah I've noticed this has been around for ages. I wonder if airlocks which originally flickered when closing a couple years ago had the same problem?

**Comment by RemieRichards** [comment]
```flick()``` is a byond built in proc, meaning it's not our fault.
Are you sure you didn't mean ```flick_overlay()```? that one IS custom and I recently changed it from a ```sleep()``` to a ```spawn()``` (so that the flick'd image could be modified during the animation)

**Comment by MrStonedOne** [comment]
@tgstation/issue-managers @tgstation/commit-access closable (this was a byond bug that was fixed)
