### ISSUE TITLE
Dragging yourself into cryo doesn't turn it on like closing it on yourself does

### ISSUE THREAD

**Issue by freerealestate** [tgstation/tgstation#10968]
Not sure if you're meant to be able to self-cryo or not. Either way, one method is inconsistent with the other.

**Comment by Tokiko1** [comment]
When fixing, consider the fact that braindamage from unupgraded cloners stops you from using the interface, stopping you from cryoing yourself without assistance.

**Comment by Cheridan** [comment]
cant cryo yourself anymore
