### ISSUE TITLE
Ling Issues: Stamina damage persists through death, Regen chems capped at 37, default regen is abyssmal 

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#10980]
1) With the shorter regen its possible to notice this, if you get stamina slamjammed by security and go into stasis, you will still maintain stamina damage and can continue to take stamina damage while dead. Its completely possible to "regenerate" and be stunned on the ground still. 

2) When you "die" as a ling, you regen chems while dead, until you hit 37 (with engorged glands at least) and then it caps. That seems odd, but not too buggy. What is buggy is regenerating with a full 75 chems and the moment you pop back up youre down to 37. 

3) This is the non-bug issue but I'll throw it in here. Default ling regen is abominable. 40 seconds to generate 10 chems. To whip out my armblade I need 80 seconds, to cancel a stun I need 2 minutes. Considering lings MUST use their abilities in conjunction (Armblade + EMP,  or Adrenal+Fleshmend), you're looking at nearly 4 minutes of standing around twiddling your thumbs just to use two abilities.

Engorged hardly feels strong itself. 75 chems with 10 chems every 20 seconds means that you'll still need 2-3 minutes just to recover chems from a single sting combo, and many abilties still dampen/drain that regen rate. Make engorged glands the new default ling chem/regen rate, and either buff engorged or remove it and let lings actually have 10 genomes to freely spend instead of 8 + mandatory engorged glands.

**Comment by RemieRichards** [comment]
1) That's deffo a bug.
2) it's 37 because it's half your max, 75/2 = 37.5, without engorged glands it caps at 25 (50/2)
3) I should have buffed chem rates when I buffed them with death-recharging and voice samples.

**Comment by Robustin** [comment]
I suspected part of 37 was intentional due to the 50% cap thing, but having the regen burn off close to 40 chems for no reason is really lame given how long it takes to generate even that much. 

Some people are always going to have a terrible view of how much power lings should have. They didn't get removed as a game mode because they were effective antagonists. They got removed because Ling had become "LSD and Spiders: The Mode". I can't fathom anyone arguing that ling's current default chem and chem regeneration numbers are acceptable, you have to spend 2 points just to make your chem generation bearable and even then I think its still a bit too small and slow (if you have to pay 2 genomes for it, you should be at 100 chems w/10 chem every 15 seconds, and the current engorged chem stats would be the new default). In its current state, if your fight as a ling goes on for more than 20 seconds chances are you're just a hard-to-permakill assistant by that point. I find myself spending way too often just staring at my chem meter and waiting around. 

It just feels silly to have an antag where you'd favor a stunprod assistant to a changeling in a fight, chasing a ling into maint should be a huge risk if you're alone, not just a free kill for the first person to bring a stun weapon to a fight against an antag that with no stuns. EMP not even fully discharging lasers is another huge blow to ling as well, you can burn through most of your chems cancelling a taser stun, EMP'ing to try and drain their weapons, only to realize that an EMP'd taser + laser still have enough energy to kill you at range. 

Anyway there's my ling rant.

**Comment by Miauw62** [comment]
pls keep hands off of ling im reworking ling and already have conflicts.

ling is awful and no minor changes are going to de-awful ling in its current state.

**Comment by RemieRichards** [comment]
@Miauw62 
>"reworking"

You added quick change ling clothes, that's not that game changing :P

**Comment by Robustin** [comment]
Ling was made awful not just by changes to ling, but a hundred other minor changes to everything else.

It's absolutely possible to make ling robust again with enough minor changes. Give lings 200 chem and 1 chem per second and they'd still probably get wasted, but in the right hands you'd have some real terrors.

**Comment by Miauw62** [comment]
so ninety percent of ling rounds would still be lame but in the other rounds a ling would murderbone everybody?

also rr im going to do other stuffs too, clothes is just the first thing

**Comment by Robustin** [comment]
Miauw62 thats the kind of shit logic that got us here in the first place, please stop.

The playerbase isn't a dichotomy of utterly useless monkeys and people who can murder the entire crew with an armblade is they JUST had a few more chems. 

Just don't pretend that's a real argument.

**Comment by Razharas** [comment]
SO what the fuck is with lings?
THey are off rotatiohn because presumably they are horrendous

**Comment by Jalleo** [comment]
They have it seems and Miauw locked RR out when they were going to do things with it.

**Comment by Razharas** [comment]
Well miauw is no longer with us its time to do shit to lings

**Comment by Jalleo** [comment]
Best if you create a milestone and collate all the ling bugs to help get it done this freeze.

**Comment by Miauw62** [comment]
Wait how did I lock remie out?

**Comment by kevinz000** [comment]
No longer an issue
https://github.com/tgstation/tgstation/blob/4105ca9ea6df5aef2b3dd7fb52988f93aae29428/code/modules/mob/living/living.dm#L357
