### ISSUE TITLE
Lootcrate spawners and maint spawners conflict?

### ISSUE THREAD

**Issue by Midaychi** [tgstation/tgstation#10986]
I recently changed the z4 map to have maint spawners, but I left the crate spawners completely alone. For some reason, though, crates no longer spawn at their spots? Either I super goofed, or the code conflicts somehow when going to spawn the stuff.

**Comment by Midaychi** [comment]
Edit: the one on the dj station works fine. Idk.

**Comment by WJohn** [comment]
Weird, not sure what could've caused this. Maps are bizzare and nebulous things at best, so I'm sorry to say you'll need to put the PR up again.

**Comment by Penguaro** [comment]
@lzimann @Midaychi 
From reviewing the code and testing, this isn't a Map Issue nor is it a bug. There is only a 20% chance for the crate spawner to leave the crate. Putting 30 on a map with and without Maint Spawners yielded crates. Changing it to a 99% chance of drop also yielding results on other z-levels.

I recommend closing this issue.

**Comment by Penguaro** [comment]
@KorPhaeron Since you looked at the other one... maybe look at this? (-;
