### ISSUE TITLE
Inventories and mechs

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#10993]
@phil235 This is kind of a discussion. You can't use your inventory in a mech. Does anyone really know why? It seems like a super outdated and useless feature, probably to prevent ~powergaming~ or something

Here's the check when you try to use your inventory:

```
    if (istype(usr.loc,/obj/mecha)) // stops inventory actions in a mech
        return 1
```

This checks every time you click any inventory or storage slot on your screen, lol, I dunno, might be relevant since phil is doing mecha updates

**Comment by Incoming5643** [comment]
probably an old shitty check to try and limit people from dropping items while in mechs (since those items are then stuck in the mech).

**Comment by RemieRichards** [comment]
at my instruction @xxalpha fixed dropping items in places that say you can't drop them there (the issue was the proc that governed if it was ok to drop an item wasn't even called) so this is just a left over bandaid fix at this point.

**Comment by Jalleo** [comment]
I do remember before this temp fix was done you were effectively drilling your own backpack toolbelt if you wanted to get a welder out when in the ripley.

**Comment by bustygoku** [comment]
What about when you unequip jumpsuits inside of mechs? Wouldn't stuff get dumped inside of them?

**Comment by Jalleo** [comment]
Could use something similar to cryo.

**Comment by Incoming5643** [comment]
It would probably just be easier to recode mechs to dump everything in their contents out when the driver ejects except for the modules.

**Comment by Jalleo** [comment]
Thats what cryo and the genetics scanners do.

**Comment by bustygoku** [comment]
You'll have to exclude their guns and their cells and stuff then because mechs have a lot of contents that aren't just people

**Comment by ChangelingRain** [comment]
Yeah this isn't a bug it's to handle you trying to drop stuff in various arcane ways
