### ISSUE TITLE
ED's Not accepting Setting changes

### ISSUE THREAD

**Issue by Maehir** [tgstation/tgstation#10995]
Problem Description: Ed's Revert any setting changes when i try to make them

What did you expect to happen: The ed's to keep the settings

What happened instead: Settings reverted on window refresh

Why is this bad/What are the consequences: Ed's will arrest unknowns even when the cec team don't want them to

Steps to reproduce the problem: Unlock Ed and attempt to change settings. Arrest unknown specifically

Server: Bagil

Revision: Server revision compiled on: 2015-08-02
9e4522698e4f81e17a150cbdc213cf91e3a0e14a

**Comment by Firecage** [comment]
I actually had the same problem last round with Beepsky, but for the patroll setting. I turned patroll on. And each time the moment he gives the message that he will start patrolling, he auto turns the patroll setting off.

**Comment by Shadowlight213** [comment]
I haven't seen this issue come up when using eds. It's likely this was fixed.

**Comment by ShizCalev** [comment]
@lzimann No longer an issue. This can be closed.
