### ISSUE TITLE
hulk cannot escape straight jacket

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#11006]
seems weird that they can literally punch through solid steel but cloth is beyond them.

**Comment by WJohn** [comment]
In the same vein, they cannot escape handcuffs any faster. Their strength must really only come when they want to punch things, not stretch or flex their muscles.

**Comment by PKPenguin321** [comment]
I thought hulks could break handcuffs in about five or so seconds? If that doesn't happen anymore, that's a bug.

**Comment by Robustin** [comment]
They can still fastbreak cuffs, just did yesterday.

**Comment by Incoming5643** [comment]
That said, we need a more object oriented way for hulk status to work, as it stands right now hulk checks pollute the codebase.

**Comment by PKPenguin321** [comment]
i doubt this is still a bug, since this was probably before you could resist out of straight jackets at all. this looks like a feature request btw

**Comment by phil235** [comment]
yep, fixed.
