### ISSUE TITLE
Xenos don't have a white screen telling them how close they are to death.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#11011]
When you're in critical as a xeno, you don't get that faded white screen of death telling you how close you are to dying. Given that xenos don't actually take oxygen damage until they're at -50 HP, this can be kind of annoying on whether to give up and ghost or wait it out.

**Comment by SconesC** [comment]
>xenos don't actually take oxygen damage until they're at -50 HP

Can we just change this

**Comment by WJohn** [comment]
This was fixed a while ago, not sure when.
