### ISSUE TITLE
Universal recorder not working too properly. 

### ISSUE THREAD

**Issue by idontwannasignup** [tgstation/tgstation#11091]
https://gyazo.com/1b475cfb2276805a24db68a5b5e861d0

This garbage was happening during my time as a service borg. 

I think the cause was the universal recorder solely, but I could be wrong.

**Comment by WJohn** [comment]
Yeah recorder has become all kinds of broken as of late, I'm not sure if anyone wants to try and fix it.

**Comment by Miauw62** [comment]
i thought i fixed this reeee

**Comment by Repukan** [comment]
@ChangelingRain I believe this is fixed, I have tested and used URs as a vet from the ruin before successfully.

**Comment by Repukan** [comment]
![desdsd](https://user-images.githubusercontent.com/19575516/28679077-16a63cea-72c0-11e7-978d-8b925a78d1db.PNG)
@lzimann 
@Cyberboss 
@ChangelingRain 
This can be closed

**Comment by idontwannasignup** [comment]
after like years
