### ISSUE TITLE
Animated mobs not friendly to wizard apprentices

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/tgstation#11137]
Animated mobs are not friendly to the wizard's apprentice.
They need their faction lists to contain the ref of the apprentice too.

**Comment by Delimusca** [comment]
or inversely, add the wizard to his apprentice's factions, which would also work i think.

**Comment by Supermichael777** [comment]
apprentices don't currently get added to the wizards faction(this may be wrong but i didn't see it in the code) they just get the protect objective.
my suggestion is to add apprentices to the wizards faction and give the animated statue the faction list in its notes (or a button that lets them pull that list like borgs can see laws). and change its objective to:
"You are an animate statue. You cannot move when monitored, but are nearly invincible and deadly when unobserved! Do not harm [firer.name], your creator or their other servants"

**Comment by xxalpha** [comment]
Wouldn't the apprentices belonging to the wizard's faction work, because that makes more sense.

**Comment by KorPhaeron** [comment]
The animated mobs aren't friendly to the wizard either, unless he's holding the staff. I don't think this is actually a bug.

**Comment by KorPhaeron** [comment]
Not a bug, animated mobs are only friendly to the staff holder
