### ISSUE TITLE
You can't change what camera network a console accesses

### ISSUE THREAD

**Issue by SconesC** [tgstation/tgstation#11147]
Kind of weird considering you can make custom ones I'm pretty sure

**Comment by WJohn** [comment]
You can't change the accesses of almost all boards in the game. Frankly I think it shouldn't be that difficult to apply a multitool to a circuit board to rewrite its access like you would with a door circuit, but what do I know?

**Comment by xxalpha** [comment]
You can when constructing. If you could change this after construction it would be a major balance issue.

**Comment by WJohn** [comment]
The whole damn camera system needs to be reworked, frankly.
