### ISSUE TITLE
Shuttles, piping, and wires are super fucky.

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#11183]
It seems very likely that the following issues are all caused by the same thing, so for the convenience of people who feel inclined to fix this I'm making an issue to collate them all under one, easily closeable roof.

Bluespace Electricity: #9903 

Disposals Teleporters: #11171 

ITT: Now that you can build on shuttles, confusing things happen when you have a pipenet/wirenet leading onto them, such as teleportation or wireless power.

**Comment by duncathan** [comment]
If this applies to pipes then that means we can hook the derelict up to station distro directly
Absolutely incredible

**Comment by francinum** [comment]
@duncathan This does NOT apply to atmos pipes last time I checked.

**Comment by Dorsisdwarf** [comment]
#11474 is an instance of this.

**Comment by RemieRichards** [comment]
#11474 isn't always reporducable.
Myself and I think it was @Miauw62 witnessed somebody attempt to build a disposal network connecting the station and the emergency shuttle, only for it to not work when used.

**Comment by Miauw62** [comment]
Yeah, this bug is a bit finnicky. I saw somebody trying to do it on the lower airlock of the shuttle on box but on testing, it didnt work.

**Comment by duncathan** [comment]
Reproduced with pipes.

**Comment by PKPenguin321** [comment]
It's been ages. Is this still an issue?

**Comment by francinum** [comment]
Very much so.
