### ISSUE TITLE
Secrets > Power all SMES breaks MC?

### ISSUE THREAD

**Issue by Saegrimr** [tgstation/tgstation#11180]
Depowered the station using admin secrets button "Make all areas unpowered"

Used button "Power all SMES" a couple minutes later. MC died.

Used button "Make all areas powered" and it didn't seem to fix it immediately, after about 5 minutes of people fumbling around in a broken MC limbo-land with killer tomatoes chasing them, it sorted itself out and lighting started working.

┐('～`；)┌

**Comment by phil235** [comment]
I can't reproduce any anomaly. All I'm seeing is that the "Make all areas unpowered/powered" are really lag intensive, so I think the bug was just caused by too much lag...

**Comment by Saegrimr** [comment]
Well this is also like 8 months old now so any number of updates could have fixed/unfixed/refixed/fucked it up.
