### ISSUE TITLE
Shadowling Veil doesn't turn off camera lights

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#11198]
Also it doesn't have enough range to disable light tubes that are in 'damage-you' range, which is stupid.

**Comment by PKPenguin321** [comment]
why doesn't it just have range that covers the whole screen

**Comment by Miauw62** [comment]
it should really just make shadowlings emit NEGATIVE LIGHT

**Comment by Xhuis** [comment]
i can buff the veil range, but camera lights are only active when the AI is watching through the camera anyway

**Comment by Anonus** [comment]
It can instantly refresh the light by moving out of range and back into range, meaning veil is useless.
