### ISSUE TITLE
Sacrifice rune doesn't make the victim into the shade

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#11200]
I'm assuming this has to do with the recent change to shades that made it so it'd ask ghosts if they wanted to be a shade if the sac'd person ragequit. As of right now, it'll asks ghosts as soon as it happens, 9/10 times ending with the victim being left in deadchat to bitch while some random ghost gets to fill their spot.

The shard on sac was added to keep players in the round so this seems pretty unintentional.

**Comment by optimumtact** [comment]
I seem to remember this being an intentional change, but I can't source it

**Comment by ChangelingRain** [comment]
This doesn't happen anymore
