### ISSUE TITLE
Cloner takes a ridiculously long time, doesn't seem to finish

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#11213]
What it says on the tin - I found myself still in crit long after I should've been out of the machine at full health. If it was the lack of oxygen, then why would that affect someone inside a sealed tube full of hyperoxygenated flesh-healing goo?

**Comment by WJohn** [comment]
The cloner is supposed to take 3 or so minutes if not upgraded, and it's also supposed to drop you out at 40 HP (60 clone damage remaining) if not upgraded. Upgrading it makes it happen both faster and with fewer defects.

**Comment by Cebasiz** [comment]
i don't think the tube insulates you from atmospheric conditions.. so if you were in an airless environment that's my bet. how i assume it works is it "regenerates" you by slowly ticking up your health until it's at cap. the airless environment might be killing you just as fast and thus it never finishes.

**Comment by WJohn** [comment]
Frankly it probably should protect you from at least lacking atmospheres outside (although low/high temperature should probably hurt you).

**Comment by AnonymousNow** [comment]
Like WJohn said - those are the regular timings, but something went seriously wrong earlier.

I feel the atmospheric thing may be an oversight.

**Comment by ojacobson** [comment]
There are definitely boogs with cloning recovery. If you get kicked out of the cloning tube at the wrong time, you'll be stuck in crit until you `*succumb` or `ghost` out ([or someone comes and rescues you](https://tgstation13.org/wiki/Beyond_the_impossible)), neither dying nor recovering.

**Comment by Miauw62** [comment]
cloning tube injects you with 60u of salbutamol as long as you're under 30u of the stuff, so when you come out you could probably have 90u of it in your body, which would prevent you from dying of oxyloss, which is actually completely intended.

**Comment by Marflowerose** [comment]
It's possible something halted the cloning progress. Someone/thing could've turned Genetics APC off and then back on and there's always possibilty of running out of power though you probably would've noticed that. 
Ejecting someone from cloning prematurely is relatively common thing to do. Usually it's to Speedclone (clone for a bit, turn equipment APC off and on to eject clone and toss said clone to Cryo, add new corpse for cloning rince and repeat.). Sometimes hostile individual cancels the cloning in order to kill you.

**Comment by Firecage** [comment]
Actually, I experienced something similar about 3 or 4 days ago while I was cloning people, and it wasn't just one person, it was for each of them. The cloning progress got to 70%, then stopped...and it wouldn't continue nor eject people. They just stayed in stasis there until either they were ejected or power was shut off

**Comment by AnonymousNow** [comment]
>70%
A familiar number, in this instance.

Looks like I reproduced a bug someone else found, then.

**Comment by Shadowlight213** [comment]
This happened recently on the hand of God testing server.
