### ISSUE TITLE
Turrets don't respect invisibility

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#11246]
Thus, if you're a revenant, turrets will try to shoot you even if you're super invisible.

**Comment by Aloraydrel** [comment]
#unfuckrevenantsshitup

**Comment by Chocobro** [comment]
related #9594

**Comment by drmies** [comment]
maybe their targeting is heat-sensitive?

**Comment by KorPhaeron** [comment]
This is a feature, a holdover from when cloakers were a thing and silicons could see through it.

**Comment by KorPhaeron** [comment]
@tkdrg 

Feature, please close

**Comment by tkdrg** [comment]
well I mean it IS a feature but it's a feature request and tagged as such, i think its fine to keep those in the tracker?

**Comment by duncathan** [comment]
Tbh I think it's more accurate to say that this WAS a feature
