### ISSUE TITLE
Tank Computers in Atmospherics are misleading/inefficent

### ISSUE THREAD

**Issue by SconesC** [tgstation/tgstation#11253]
Referencing the computers that give you information about the mix tank/gas holding tanks. The rooms.

I'm fairly certain the temperature readout is only giving it you from one tile and not taking into account the other tiles which could have a much different temperature. Having multiple readouts (Individual tile, median value of all 9 tiles in the tank, highest temp and lowest temp points) would be really nice as an alternative.

**Comment by Marflowerose** [comment]
Doesn't the Fastmos basically make that sort of useless since all the tiles would have pretty much identical temperature and pressure unless someone breaks the window?

**Comment by SconesC** [comment]
They get kind of weird in the mix tank

**Comment by MrStonedOne** [comment]
ya, the mix tank can have wildly different temps because of gas coming in, and gas going out..

**Comment by SconesC** [comment]
It really get crazy annoying if something ignites in there

**Comment by optimumtact** [comment]
feedback forum , not really a bug, just crappy ui
