### ISSUE TITLE
Cyborg photo system

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/tgstation#11276]
As a cyborg, the "view images" button always returns with "No Images saved", rather than the drop down of your pictures, no matter how many photos you have saved.
Printing works normally and gives you a list of the photos you took however.

Unsure if the same issue comes with the AI.

**Comment by GunHog** [comment]
The photos are not lost, but are uploaded to the borg's AI. Linked borgs do not seem to have access to their AI's picture list, hence this bug.

**Comment by Dorsisdwarf** [comment]
Tested and confirmed fucking dead
