### ISSUE TITLE
Lightning bolt bounces off simple animals, but does not hurt them.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#11283]
What it says on the tin.

**Comment by Bawhoppen** [comment]
I believe this was changed, you should test it again

**Comment by Jalleo** [comment]
@optimumtact was this fixed with the work @MrStonedOne did?

**Comment by optimumtact** [comment]
Why would I know

**Comment by Repukan** [comment]
![dsdseds](https://user-images.githubusercontent.com/19575516/28679657-eaa4e464-72c1-11e7-9cce-369c96fb1cc8.PNG)

It hurts them now, this can be closed

@lzimann 
@Cyberboss 
@ChangelingRain
