### ISSUE TITLE
Ninja losing its abilities.

### ISSUE THREAD

**Issue by IvanIssaccs** [tgstation/tgstation#11289]
Just played a round as a space ninja, came across a bug where as the round went on I found my powers not working. 
From the beginning of the round ninja stealth would not activate.
I was able to use the abilities EMP, Energy net and jaunt several times however these became non functional while fully charged.
Also noted activating the abilities reduced suit energy by the appropriate amount however did not function in game.

**Comment by WJohn** [comment]
Ninja stealth not working is a known bug, otherwise yeah ninja is bugged in a bunch of ways.
