### ISSUE TITLE
Talking in pipes/disposal tubes is weird/broken

### ISSUE THREAD

**Issue by theOperand** [tgstation/tgstation#11296]
When crawling through pipes, you are sometimes able to talk, sometimes not. This appears to have to do with if the pipe is under a floor or not.

A cyborg stuck in disposals cannot use his radio, but can use binary chat.

It's just weird and broken.

**Comment by Jalleo** [comment]
Same happens if you are put within someone.

**Comment by PKPenguin321** [comment]
pretty sure this is a dupe

**Comment by phil235** [comment]
Cannot reproduce. Was likely same issue as #10005.
