### ISSUE TITLE
Cyborg stuck in unconsciousness.

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/tgstation#11292]
1. Get flashbanged to go into borg unconsciousness.
2. Get hit by a blob type that lights you on fire.
3. You are now stuck in borg unconsciousness until someone puts the little fire sprites on you out with a fire extinguisher.

Don't know if you guys can replicate but that's what happened to me.

**Comment by WJohn** [comment]
I can't even confirm this because #11294 is in the way of testing it.
