### ISSUE TITLE
Shuttles are always fully lit

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#11304]
They should use actual lights so that shadowlings can go on the shuttle or pods and not get cucked hard.

**Comment by RemieRichards** [comment]
this was mainly due to the old lighting system, SDAL (well, it was based on the byond SDAL library, I think we just called it "DAL") and shuttles wouldn't work with DAL because they weren't real floor tiles.
they might work with @MrPerson's new lighting however.

**Comment by Anonus** [comment]
And shuttle floors are subtypes of normal floors now, as well.

**Comment by Chnkr** [comment]
Just port baylighting, it's faster than DAL.

**Comment by RemieRichards** [comment]
@Chnkr why would we port Baylighting? our lighting is better than Bay's.
(For the record, NOBODY uses DAL anymore)
