### ISSUE TITLE
Creating an AI core with no brain creates a clientless AI core.

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#11328]
![](http://puu.sh/jKNRq/f9dedde9de.png)

**Comment by WJohn** [comment]
I thought this was intentional, creating a core without a brain just makes an empty core that you can upload an AI in an intelicard to.

Unless it's changed so it creates a braindead AI taking up that slot, in that case yeah that's broken.

**Comment by GunHog** [comment]
Creating a core without a brain should create an empty, inactive core for you to load an AI from a card.

**Comment by Shadowlight213** [comment]
Spawning an Ai mob from spawn panel also makes an inactive core.

**Comment by xxalpha** [comment]
Can't reproduce, probably some runtime that was fixed was causing this.

**Comment by optimumtact** [comment]
old with no repro
