### ISSUE TITLE
Putting a brain into a cake sends the ghost to nullspace

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#11326]
Had an ahelp where someone had a chef put their brain into a cake
Chef then cut the cake, and the brain fell out.
Brain was then made into braincake.

After the brain was put into the cake, the player's ghost got sent to nullspace or something when they used re-enter corpse.

**Comment by Dorsisdwarf** [comment]
This needs reproducing. @Shadowlight213 would you mind having a go?

**Comment by phil235** [comment]
Can't reproduce, whether the player stays in the brain or ghosts before the brain cake is created and tries to reenter corpse.
The only tiny issue is if the player is in the brain when it's consumed to make the cake, the player is ghosted and their ghost moved to arrival shuttle(spawn point).

**Comment by optimumtact** [comment]
old with no repro
