### ISSUE TITLE
/obj/effect/decal/cleanable/blood/drip doesn't qdel.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#11369]
This happens if there is still a variable that points to that Object. in order to soft delete properly, the Object's destroy proc needs to clear up all references that point to it.

Failed qdel log:
http://privatepaste.com/edc18b668d

**Comment by nicbn** [comment]
404 link

**Comment by vuonojenmustaturska** [comment]
seems to have been fixed by #33083
