### ISSUE TITLE
/obj/effect/explosion doesn't qdel.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#11371]
This happens if there is still a variable that points to that Object. in order to soft delete properly, the Object's destroy proc needs to clear up all references that point to it.

Failed qdel log:
http://privatepaste.com/edc18b668d

**Comment by Core0verload** [comment]
Propably related to "TTV bomb doesn't qdel" issue that you forgot to create.

**Comment by MrStonedOne** [comment]
I have a list of things not qdeling 100 items long...

This is just a taste.

**Comment by Jalleo** [comment]
Are you just passing the worst offendors at the moment?
You really should give all of them.

**Comment by WJohn** [comment]
But then we'll be just under 900 issues! WE CAN'T HAVE THAT.

**Comment by Cyberboss** [comment]
Not an issue anymore, @lzimann
