### ISSUE TITLE
You cannot make existing station areas into a shuttle

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#11399]
Basically, I've followed the guide for making a shuttle, and while it will work for new shuttles out in space, attempting to use it to move a room on the station will result in only the mobile port moving, leaving the occupants and turfs behind.
Returning back to that area will kill everyone in it instantly.

**Comment by Aranclanos** [comment]
what guide?

**Comment by Shadowlight213** [comment]
The one made by @NikNakFlak 
https://tgstation13.org/phpBB/viewtopic.php?f=11&t=3174

**Comment by Cyberboss** [comment]
Closed by the dock rewrite
