### ISSUE TITLE
Thermiting the shuttle walls turn them into burnt out normal walls

### ISSUE THREAD

**Issue by Jalleo** [tgstation/tgstation#11391]
What it says on the tin

**Comment by freerealestate** [comment]
Was going to report this for floors

![](https://u.pomf.is/tbttam.png)

**Comment by Jalleo** [comment]
@Bawhoppen Was this fixed when you did the shuttle walls overhaul?

**Comment by Bawhoppen** [comment]
yes, I had actually broke it further but then Joan fixed it
