### ISSUE TITLE
Swapping out human icons dmis in-game can bug out.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#11408]
If you replace a human's sprite, say with a horror form changeling sprite I made "icon = /icon(human.dmi)" var, and then set that player's species to anything else, even a human again, it will place that skin as an overlay on top, regardless of whether you did or didn't name the replacement sprite in your .dmi the same as their skin color (if you didn't just leave it blank).

The result is this:
![](http://i.imgur.com/3vrWvlu.png)

You can get around this by setting the species as something not normally available, such as a zombie (which for some reason goes invisible???)

**Comment by RemieRichards** [comment]
Side effect of humans correctly using ```update_color()```

**Comment by Core0verload** [comment]
That's because update_icon doesn't respect mob's icon var.

**Comment by Incoming5643** [comment]
is it really a bug if people are doing things that were never really supported to begin with.

**Comment by PKPenguin321** [comment]
yeah this isn't *really* a bug in the conventional sense

**Comment by WJohn** [comment]
But it is intentional. And now this IS a bug.

We gave clothing sprites things like left & right inhands, as well as worn sprites. You can swap out all those DMIs now. They were added with the express purpose of letting admins swap out clothing sprites, and for the longest time you could do it with humans too.

**Comment by RemieRichards** [comment]
this isn't supported officially, unlike with clothing/held items where I specifically added it.
It's also not possible at all anymore, as with dismemberment human ```icon_state``` is wiped every icon update, just incase.
