### ISSUE TITLE
Bug with cleaning items you used to be wearing

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#11407]
What happened: I was mime, I came into the possession of a bar of soap and some armor.

I try to clean the armor, You need to take that armor off before cleaning it! I take the armor off. Same message. 

So I tested it with tools in a toolbelt I was wearing. Same shit happened. You need to take that screwdriver off before cleaning it! (That alone is fucking odd.) Take out the screwdriver, same message.

**Comment by phil235** [comment]
intended

**Comment by bgobandit** [comment]
how is it intended to be unable to clean articles of clothing even AFTER you remove them because "you have to take that off first :^) :^) :^)

**Comment by phil235** [comment]
relevant code: https://github.com/tgstation/-tg-station/blob/b7ca1106541e7cbba80ecf156a253b2537252278/code/game/objects/items/weapons/clown_items.dm#L48

**Comment by RemieRichards** [comment]
if you were holding it in your hands, thats also in your "screen" so the check works, however that check is ancient shitcode and should be modernised.

Actual fix:
Move shower blood cleaning out of showers, and into carbon ```clean_blood()```, and then remove this check from soap altogether, carn might not have been able to fix the overlay issues, but we already have.
