### ISSUE TITLE
Cheap lighter burns through atmos hardsuit

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#11419]
Wearing full atmos hardsuit gear (which is supposed to have pretty much immunity to heat) and fiddling with cheap lighters can cause burns.

Edit. Probably also applies to black gloves and other supposedly heat resistant handgear.

**Comment by xxalpha** [comment]
Exosuits are not gloves, why would they protect your hands?

**Comment by Marflowerose** [comment]
Probably with same logic that wearing atmos hardsuit protects your entire body from walking through the fire and flames

**Comment by WJohn** [comment]
Furthermore, wearing actual black gloves, the fire resistant ones, still doesn't protect you from this.

**Comment by Xhuis** [comment]
can we please just remove cheap lighter burning
it's pointless, snowflakey, and dumb
