### ISSUE TITLE
Antag preferences showing in traitor panel as different settings from what the player has them set to.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#11423]
This has happened a couple times, where I have gotten ahelps from players who say they have an antag turned off, but their traitor panel shows it as enabled in prefs. Same thing can happen the other way around where it shows as disabled in the traitor panel, but enabled for them.
I've checked their preferences, and the flags match up with what the player sees as the settings.
This seems to cause them to get a certain antag that they have disabled, or never get an antag they have enabled possibly.

**Comment by nicbn** [comment]
Is this still an issue?
