### ISSUE TITLE
Steal an AI objective doesn't actually check for a living, roundstart AI

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#11444]
I mean, you could MAKE one, but this is kind of silly.

**Comment by xxalpha** [comment]
I am almost sure that it does.

**Comment by Anonus** [comment]
It does not, as a traitor just recently got the objective without the round having an AI.

**Comment by xxalpha** [comment]
Oh. I thought you meant it doesn't check if you have an AI at round end.

**Comment by Fayrik** [comment]
It's a feature. Otherwise you physically can't complete the objective in that scenario.

**Comment by Shadowlight213** [comment]
@Fayrik
He doesn't mean checking on round end. The steal an AI objective doesn't check to see if there is an AI on the station before assigning it. Upon escape, it still will check to see if you have an AI. Unless you build one, you cannot complete it.

**Comment by Alek2ander** [comment]
>Upon escape, it still will check to see if you have an AI.

No. It won't. See #4725.

**Comment by Shadowlight213** [comment]
Ah. Ok. I didn't know that an empty intellicard worked

**Comment by Dorsisdwarf** [comment]
Closed because due to #4725 , this bug is a non-issue. Ping me if it's fixed and I'll reopen

**Comment by Razharas** [comment]
@tkdrg asked to
