### ISSUE TITLE
Golem rune created in space -In ghostchat [golem runes have no jump-to-link]

### ISSUE THREAD

**Issue by Jalleo** [tgstation/tgstation#11445]
what it says on the tin nobody can then find it if it was created.
I saw that message in the ghostchat

**Comment by Dorsisdwarf** [comment]
All the platings on the outside of the station are "space", so its a lot to look for

**Comment by Jalleo** [comment]
Ya cant jump to the rune though

**Comment by Jalleo** [comment]
What i mean is ya cant jump to any golem rune sorry for misworded reply.

**Comment by Jordie0608** [comment]
Easy fix, replace area with jump-to-coord href.

**Comment by KorPhaeron** [comment]
@tkdrg you fixed this with ghost buttons

**Comment by Jalleo** [comment]
KorPhaeron not completly i think they still need specific jump to. For when multiple runes are created at different places at the same time.

**Comment by tkdrg** [comment]
the buttons appear for up to 5 runes
it's true that it's still an issue if over 5 runes are made within 1 minute but eeeh
