### ISSUE TITLE
Swapping forms after changing bodies with last resort kicks you out of the body

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#11462]
Pretty much use last resort and lay eggs in some random body. Then after you resurrect in that body try transforming and watch as you are ghosted out of the body

**Comment by Firecage** [comment]
This is basically what happened to me the round before Alo reported this. I informed the admins what happened to me, and Ausops said that Alo already knew of the bug and was going to make an issue report about it, which implies it hasn't only happened to me I guess.

**Comment by AnturK** [comment]
This is the same bug as monkey transform eating items etc. wear_suit runtime and such.

**Comment by Dorsisdwarf** [comment]
Tested, happens exactly as described.

**Comment by jughu** [comment]
can be closed swap bodies donr exist anymore

**Comment by jughu** [comment]
@anturk i think this can be closed i didnt see it happen recently not even with xenolings
