### ISSUE TITLE
Cure all diseases currently in existence doesnt actually cure every disease

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#11499]
Good luck with incurable GBS :^)

**Comment by phil235** [comment]
Can't seem to reproduce with viruses from the virus crates or random ones from the Disease Outbreak Event.

**Comment by optimumtact** [comment]
old with no repro

**Comment by bgobandit** [comment]
this might still be a thing. maybe it's custom diseases it doesn't cure?

**Comment by optimumtact** [comment]
I'm not going to reopen and old bug because you think it might be still a thing

either prove it and make a new issue or stop worrying about it
