### ISSUE TITLE
Latejoin heads of staff don't have to be killed during revolution

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#11532]
See #4846 which was never reverted.
This is thus a bug.

**Comment by Supermichael777** [comment]
warning that fixing this will cause late-join head-revs which scares me and may harm the mode.

**Comment by Supermichael777** [comment]
@Cheridan i THIIINK this may have been resolved

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/bc50c7757045598a3b5a0e5cd47ad3bf150506ca/code/game/gamemodes/revolution/revolution.dm#L186

Was rewritten some point since then, so likely fixed.
