### ISSUE TITLE
Honked up floor in the chapel [Box]

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#11537]
What happened: See image

Why this is bad: HONK!

Other details: Obviously this is just plating. There was a bomb that went off south-ish of here. I don't know anything else besides what I saw.

Image:
![learn to embed images](http://i.imgur.com/tsUEx14.png)

**Comment by WJohn** [comment]
It might be trying to make damaged carpets, still? I'm going to test this in a second.

**Comment by Jalleo** [comment]
It could be due to acid or other stuff. So many things act incorrect.
