### ISSUE TITLE
AI status screen will sometimes go blank rather than bluescreen when killed

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#11543]
Not sure if this happens when they ghost or when they die.
I know the screen is supposed to go blank on braindead and bluescreen on death.

**Comment by GunHog** [comment]
Happens when the AI ghosts, which is forced when the AI tries to move its eye. This is caused by PR 5641.

**Comment by Shadowlight213** [comment]
Hmm. I guess it could be fixed by using the same thing that the soul has departed message for humans has.

**Comment by GunHog** [comment]
That message is for when mobs lose their ckey (ghosted player gets another role in the round or such) and cannot ever return. Yes, instead of having the AI's screens go black when it ghosts, have it do so if the AI player abandon its body forever.

**Comment by Shadowlight213** [comment]
The AI screen going black is for when the AI goes braindead I think. An easier change would probably be to just have the bluescreen override the black one from ghosting

**Comment by phil235** [comment]
Can't reproduce, I think because ghosting as AI no longer changes your sprite.
Can't reproduce by dying and then ghosting, or by dying and then disconnecting, or by disconnecting and then dying.

**Comment by GunHog** [comment]
You probably fixed it in another refactor, maybe?

**Comment by Shadowlight213** [comment]
@Phil235 the status screens, not the AI core sprite itself, right?

**Comment by GunHog** [comment]
Oh, that is right. Make sure you are checking the _AI status screens_ found on the walls of your chamber, not the core itself.

**Comment by phil235** [comment]
Welp, I guess it's time to test again.. :monkey_face:
