### ISSUE TITLE
AI hologram bugs out when AI dies while using it

### ISSUE THREAD

**Issue by Jalleo** [tgstation/tgstation#11552]
AI using hologram
AI dies while using it
AI hologram sprite where it is shown from bugs out saying its still active when AI cant use it

**Comment by phil235** [comment]
I don't understand what you mean.

 I don't see any bug when testing killing an AI that is currently using a hologram.

**Comment by Jalleo** [comment]
The holopad thinks it is still on when it isnt

**Comment by Cyberboss** [comment]
Tested, fixed here: https://github.com/tgstation/tgstation/blame/8dab2c9c34d49513ee67d45c750169c740a40462/code/game/machinery/hologram.dm#L177

@lzimann
