### ISSUE TITLE
Drone hats do not correctly flip with the drone.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#11554]
When you flip as a drone, your hat makes a circle all on its own, flying away from you completely before re-aligning with your head.

The easiest solution to this would be to prevent them from flipping, but that's booooriiiing.

**Comment by WJohn** [comment]
I should also mention that this should totally be a feature because it's ADORABLE.

**Comment by bgobandit** [comment]
drones confirmed for nope.avi

**Comment by duncathan** [comment]
Omg webm pls

**Comment by optimumtact** [comment]
ascended bug to feature, just leave it alone I'd say

**Comment by Actionb** [comment]
This needs to stay. Flipping is a drone's best tool to express its infinite rage over meatbags destroying everything.

**Comment by JJRcop** [comment]
hahahahaha, it's probably because I lowered the hat sprite so it would fit on the drone's head as hats were made for humans

**Comment by ChangelingRain** [comment]
Unfixable without drone-specific hat sprites
