### ISSUE TITLE
you can no longer easaly split stacks

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#11561]
old behavior: clicking a stack with another stack of the same type would pull a single item to your primary hand stack.

new behavior: it combines the whole stack

this fucks up splitting stacks to give people(or especially greedy machines) a specific amount.

**Comment by kingofkosmos** [comment]
One solution would be to have all machines ask for the amount, like some do already.

**Comment by Lumipharon** [comment]
Yeah it's actually really annoying now, if you want to give someone some of a stack but not all of it, you can't.

**Comment by Supermichael777** [comment]
this is @MrPerson change
