### ISSUE TITLE
A bunch of stuff has no icons in the right click dropdown menu

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#11574]
It used to be that right clicking had a little preview icon pop up. For humans at least, this isnt the case anymore, and it just shows up blank.

**Comment by Core0verload** [comment]
BYOND Bug.

**Comment by WJohn** [comment]
Same thing with walls, windows, and a ton of other stuff. I'd say almost 50% of the things in drop down menus don't show up.

**Comment by RemieRichards** [comment]
Not fixable without a custom right click dropdown, which can't be implemented without losing verbs at present as the logic byond uses for verbs isn't fully replicable in DM itself.

Granted, verbs suck ass so lets remove them.
