### ISSUE TITLE
Drones do not have a check alerts button

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#11598]
Drones get messages if station alarms go off, but unlike borgs and Ais, they do not have a button to check what alerts are currently active, nor do they have a verb to check it. This is an issue because if a drone didn't see the alarm first go off, they have no idea that there is an issue in that area.

**Comment by WJohn** [comment]
I thought they had that button in their verbs? An actual action button or something similar on their huds like the AI has would be nice, though.

**Comment by Shadowlight213** [comment]
They dont have it in their verbs either

**Comment by WJohn** [comment]
Huh. I swear they used to have it... That's a bug then.
