### ISSUE TITLE
bloody footprints sometimes apere for no reson

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#11654]
see above.
realy weird
some kind of invisible mess maybe?

**Comment by WJohn** [comment]
Yeah I've noticed there were tons of footprints despite there not being any blood puddles or oil patches for them to originate from.

**Comment by Supermichael777** [comment]
this was round start.

**Comment by RemieRichards** [comment]
You store blood on your shoes, it starts at 0, obviously, walking over a pool of blood simple puts the blood on your shoes (taking it from the pool also).
you only produce bloody footprints with bloody shoes.

**Comment by WJohn** [comment]
It's actually not only just that, but I think people are really unhappy with how you actually get more blood on your shoes by walking on footprints. It does nothing but distort the original crime scene and spreads footprints friggin' eeeeverywhere.

Also you can't make footprints when barefooted.

**Comment by Dorsisdwarf** [comment]
Suggestion for bloodprints:
1) Reduce the amount of blood in blooddrops below the limit for walking on
2) Increase the amount of blood used up in each step
3) Make footprints have no blood of their own, so the trails don't get so messed up
4) make the footprints on the sprite a little smaller
5) Make footprints get bloody with bare feet

**Comment by WJohn** [comment]
Heck, remove the ability to make footprints from blood drops at all, those are EVERYWHERE.

**Comment by RemieRichards** [comment]
Just clearing this up here because I've said it in other places.

I have plans to tweak all this stuff, just not right away, I'm giving time to get proper feedback (like this) instead of what was initially "Hmm lots of blood!" "gaaaaaay" "blood for blood god" "memes"

**Comment by phil235** [comment]
Does this still happen?

**Comment by phil235** [comment]
walking on blood drops no longer create footprints, so I'm guessing this is fixed.
