### ISSUE TITLE
Teamling objectives are really buggy

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#11664]
1) Sometimes each ling will be told that their team has to impersonate a different department, this instantly ruins team cohesion and makes greentext virtually impossible (one ling is told the team has to impersonate medbay, the next is told the team has to impersonate science...)

2) Lings will be given the "replace heads" objective but each ling has differences in their "list" of heads of staff so that nobody has consistent objectives.

**Comment by Durkel** [comment]
To add to this I've also seen a team of lings succeed, but only one of the lings get greentext for the replace heads objective.

**Comment by CPTANT** [comment]
dupe and can be closed since taemling doesn't exist anymore.

**Comment by Robustin** [comment]
I'm closing this because Teamling is ded, its a shame because it was literally never functional and people would shit on it because the lings would just murderbone since they had impossible objectives.

**Comment by RemieRichards** [comment]
@Robustin not strictly true but whatever.
