### ISSUE TITLE
Paper BBCode mission critical problem

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/tgstation#11714]
So with bbcode for writing on paper (which is pretty awful I might add), does not have the [tab] function, or the ability to show more then one space (ie: word     word)
Unless there is other wizardry about, this makes formatting pretty awful.

Edit: Tried to show the gap I wanted between word and word, but github has the same retarded thing. Why?

**Comment by Jordie0608** [comment]
/obj/item/weapon/paper/proc/parsepencode() would just need a check to add some $nbsp
