### ISSUE TITLE
Lings don't get notes from husking anymore?

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/tgstation#11759]
Didn't lings used to get their victims notes if they husked them?
Now all you get are the last few things they said (usually HELP, X LING, FUCK!!).

I've husked 2 traitors and not gotten their notes.

**Comment by RemieRichards** [comment]
```target.mind.show_memory(src, 0) //I can read your mind, kekeke. Output all their notes.```
You're SHOWN them, but not given them, which has always been the case

**Comment by Lumipharon** [comment]
hm, well I husked atleast 2 confirmed traitors (as per end round report) and didn't see their notes at all.

**Comment by RemieRichards** [comment]
Nothing's changed to have caused this to not work.
Certainly not recent speech, since recent speech happens AFTER not output, meaning if it was broken, you'd still see note output.

**Comment by WJohn** [comment]
![](http://i.imgur.com/7JZJkj6.png)

I just tested this, you don't get any notes after absorbing someone. I made myself that person and added the note "test test test" but I didn't get it after absorbing them.

**Comment by Marflowerose** [comment]
What's the reasoning for getting tator notes? I thought syndies implanted crewmembers and the implant would brainwash/activate the agent kinda like in Naked Gun.

**Comment by Dorsisdwarf** [comment]
Because you're stealing their mind when you steal their brain as a ling.

**Comment by Marflowerose** [comment]
But aren't the brains still intact? Don't get me wrong, the system would be nice if it was consistent. Perhaps have separate brain notes for all properly sucked corpses that would give snippets to the life of the person.

**Comment by Miauw62** [comment]
yeah, objectives are updated automatically and to that purpose are not stored in notes, but just dynamically displayed every time you open your notes window.

**Comment by Lumipharon** [comment]
The idea is that shit like 'your uplink code/nuke code is X' would be given to the ling. But that is no longer the case.

**Comment by Miauw62** [comment]
it might never have been the case in the first place.

**Comment by Lumipharon** [comment]
I honestly can't say for sure, since you rarely get to husk a traitor - I only brought it up now because I know for certain that 2 guys I husked were traitors.

What Remie said suggests it's supposed to though.

**Comment by Miauw62** [comment]
yeah, its definitely supposed to, but whoever made it in the first place
could have easily overlooked the fact that traitor stuff doesnt really
count as notes

**Comment by Dorsisdwarf** [comment]
RR says that **no** notes are showing for lings

**Comment by Cyberboss** [comment]
Closable
