### ISSUE TITLE
Admin ghosting out of a jaunting in progress wizard causes the wizard to be invisible and immovable 

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#11755]
What it says in the title. only way to reappear is to rejaunt.

**Comment by Incoming5643** [comment]
Ow the edge. Sounds like a runtime.

**Comment by Aloraydrel** [comment]
I would guess it happens if you actually ghost as well

**Comment by Jordie0608** [comment]
What happens if you aghost back in?

**Comment by Aloraydrel** [comment]
you are just invisible and stuck on the tile you were suppose to reappear from jaunting

**Comment by optimumtact** [comment]
This was refactored and thunder11 could not repro either
