### ISSUE TITLE
Mid-round joining traitors can get objectives to kill people who are on centcom

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#11761]
For admins/coders who are testing with random humans

**Comment by WJohn** [comment]
It really should only pick people who are on the crew roster, or are from round start.

**Comment by Dorsisdwarf** [comment]
Roundstart assasination targets only is a config, IIRC (Yogstation used to have it, I'm sure)

We don't use it because everyone (EVERYONE) signed up 1 second after roundstart to avoid being a target

**Comment by phil235** [comment]
Still happening.
