### ISSUE TITLE
Kill choke has a progress bar.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#11764]
What it says on the tin. When you reinforce your neck grab and have it actively choking them, it will make a progress bar that will appear again and again.

**Comment by Iamgoofball** [comment]
it should have a prog bar

but it shouldn't flash in and out of existance

**Comment by WJohn** [comment]
To clarify, the progress bar completes in a few seconds, then starts again rather than flashing constantly.

**Comment by Core0verload** [comment]
#11760 adds a var that disables progress bar to do_mob and do_after.

**Comment by Iamgoofball** [comment]
@WJohn That's probably just bad logic in terms of the choke code.

@Core0verload That's literally useless, we already have that var. Just don't set a target and a progbar won't show up.

**Comment by optimumtact** [comment]
except you might want target logic and no progbar
