### ISSUE TITLE
crew monitor window

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/tgstation#11774]
![first](https://cloud.githubusercontent.com/assets/701959/9840568/bda7ad50-5a6a-11e5-96fb-20aa1853ba5f.jpg)
![extended](https://cloud.githubusercontent.com/assets/701959/9840569/bddb2450-5a6a-11e5-8e33-03c5a690eae9.jpg)

First image is how the window opens, the details are missing, if I manually increase the size of the window, they appear but the 'not available' strings overlap with the lower line

**Comment by vuonojenmustaturska** [comment]
Removed in #35431
