### ISSUE TITLE
Examine false walls have a different mini icon than normal walls

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#11813]
Title.

**Comment by Dorsisdwarf** [comment]
@Aranclanos

**Comment by Aranclanos** [comment]
mini icon?

**Comment by RemieRichards** [comment]
@Aranclanos I assume they mean ```\icon[wall]``` which they almost certainly spotted in examining.

**Comment by Bawhoppen** [comment]
For an example this icon at the right:
![ss 2015-09-16 at 04 45 52](https://cloud.githubusercontent.com/assets/6510293/9919434/7401fb7c-5c92-11e5-8885-6a03c40b1448.png)

**Comment by RemieRichards** [comment]
that's a ```"\icon[THING]"``` text macro, and it's in examining.
let's call that 2 points to me :3

**Comment by Alek2ander** [comment]
Well if you examine a false wall you should realise it's false. Because you examined it. This ain't a perception check.

**Comment by Bawhoppen** [comment]
Well if you want to use that logic make it a piece of text like: "This wall appears shaky" or something.

**Comment by MrStonedOne** [comment]
Could somebody please show a picture of normal wall and false wall so we can actually see the issue.

**Comment by Bawhoppen** [comment]
![ss 2015-09-17 at 04 06 51](https://cloud.githubusercontent.com/assets/6510293/9945965/257c274c-5d56-11e5-86aa-ec51cbcca8e8.png)

**Comment by swankcookie** [comment]
This seems like a non-issue. Alternatively, lets give the player a 1/20 chance of seeing the altered icon.  d&d13.

**Comment by Aranclanos** [comment]
don't shitpost please
