### ISSUE TITLE
Syndieborg and Multiverse clone (and maybe others) should have their own pref toggle

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#11841]
Many times when I don't want to be a borg when I have nukeops enabled yet I observed.

**Comment by Jalleo** [comment]
That could use the pop up request to check if ya want in really

**Comment by RemieRichards** [comment]
Literally not possible at the moment, since we've used all 0-15 bits of the bitflag.
My Hand of God PR expands that to allow for (functionally) infinite antag preferences.
Which means things like a pref for:
* First cultist on station
* Revhead
* Nukeop Head

etc, just more general control over which role you get during rounds.

**Comment by Jalleo** [comment]
Could you move that into a seperate PR to get that neat administration maintainibility change through please

**Comment by Jalleo** [comment]
Anyhow i do believe this issue report is talking about people who dont want to join the round but get joined in without warning or choice due to how code works.

**Comment by Bawhoppen** [comment]
Yea, if you're observing as a ghost you just get dropped in as a syndieborg, and then I have syndies enabled but maybe I don't want to ever be a borg, Should be seperate.

**Comment by Dorsisdwarf** [comment]
Left open because these ones particularly really should use popup "DO YOU WANT TO BE THE SYNDIEBORG" (although probbably a toggle for Clone)

**Comment by Bawhoppen** [comment]
still an issue for multiverse clone oranges

**Comment by optimumtact** [comment]
This is a feature request

**Comment by Bawhoppen** [comment]
its still a problem

**Comment by optimumtact** [comment]
then make a forum thread about it

this tracker is concerned with bugs only and this trend will continue

**Comment by Bawhoppen** [comment]
oranges you know full well its for non-bugs too

**Comment by optimumtact** [comment]
no
