### ISSUE TITLE
Bruise packs and patches work in weird ways on augs

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#11854]
What happened: I was fully auged. People tried to heal me.

Bruise packs:

You begin applying the bruise pack on yourself...
You apply the bruise pack on yourself.
Medicine won't work on a robotic limb!

Patches:

Anna Avery forces Fortune Ray to apply Synthflesh (15u) patch.
You feel your burns healing and your flesh knitting together! 
(Pretty sure this actually did heal me)

**Comment by Dorsisdwarf** [comment]
I bet this is because patches are pills.

**Comment by Miauw62** [comment]
duplicate, probably
