### ISSUE TITLE
Syndicate bombs and the emergancy shuttle timer don't tick at similar rates

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#11881]
A bomb that was set for 60 seconds when the shuttle was 80 seconds out(1:20) from centcom still hadn't gone off by the time the round restarted, which is really really odd.

**Comment by Incoming5643** [comment]
The emergency shuttle keeps time by a different method than most things in the game. It's why if the game is extremely laggy getting to the shuttle before it leaves can be a real trial, because it moves in something closer to real time than "byond time"

**Comment by WJohn** [comment]
Hell a lot of things don't tick at similar rates. The escape shuttle, nukes, and various other countdowns all seem to tick at different rates.
