### ISSUE TITLE
Shoes don't lose the blood overlay once blood runs out

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#11895]
I'm pretty sure they're supposed to?

**Comment by Dorsisdwarf** [comment]
No. The blood is considered "dried", IIRC

**Comment by PKPenguin321** [comment]
well if it's intended then why can it be fixed by taking your shoes off and back on

**Comment by Dorsisdwarf** [comment]
@RemieRichards  

Do you know why this might be happening?

**Comment by freerealestate** [comment]
You also can't clean the blood overlay with spray, like you can with the others
