### ISSUE TITLE
Feature? Bug? Locking Lockers from the Inside

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#11909]
Currently you can lock/unlock perosnal lockers from the inside--not sure if this is an intended feature or a bug.

**Comment by Lumipharon** [comment]
You've been able to lock/unlock lockers from the inside for as long as I can remember.

However funnily enough I found just the other day I WASN'T able to do so, and was going to write a bug report on that. Dunno.

**Comment by Jordie0608** [comment]
Way back in #8936 we decided this was a bug where I'm pretty sure it was fixed, but it would seem something's brought it back.

**Comment by Alek2ander** [comment]
You can't lock/unlock normal lockers from the inside, but you can lock/unlock personal closets. If this is removed locker mime will be sad.

**Comment by Fox-McCloud** [comment]
Ok, to clarify, yes, this only applies to personal lockers--it doesn't work on regular lockers.

**Comment by PKPenguin321** [comment]
i say we just readd being able to lock/unlock from the inside of all lockers
