### ISSUE TITLE
Attempting to use canisters while on vehicles

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#11915]
If you try to use a canister with a tank inside or whatever while on a vehicle none of the buttons work.

**Comment by Aloraydrel** [comment]
Doesnt riding a vehicle count as being buckled?

**Comment by Bawhoppen** [comment]
Yea I think so, but you should be able to access it.

**Comment by Marflowerose** [comment]
Interacting world when in a vehicle is pretty dumb as a whole. Manually opening airlocks and having to hold the key come up right away.

**Comment by phil235** [comment]
Probably need to remove the buckled check in the canister's Topic proc (and others if relevant).

**Comment by Cheridan** [comment]
firecage tested this and says its no longer an issue
