### ISSUE TITLE
Can suicide with guns who's pins don't match up with your allowed use

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#11936]
Title. Syndie gun is a prime example

**Comment by Lumipharon** [comment]
also related (and pretty sure already reported) you can suicide with PINLESS guns, and clowns can shoot themselves in the foot with pinless/wrong pin guns (hilarious with the ion rifle since it actually does the aoe emp.

**Comment by Marflowerose** [comment]
I think the real bug would be that it gives the wrong message when commiting suicide with a weapon you aren't allowed to use. You should be able to commit suicide with all weapons regardless of pins/charge, it should just give the Pretend version of suicide.

**Comment by freerealestate** [comment]
the idea of a pretend suicide actually killing the character is pretty stupid, why not just have them bludgeon themselves to death with it?

**Comment by Marflowerose** [comment]
Most of the suicides are "stupid", which is why they're also hilarious. Stop trying to remove fun.

**Comment by freerealestate** [comment]
Just trying to make the "fun" logically consistent

**Comment by Dorsisdwarf** [comment]
"Jimmy Rustle starts scribbling all over himself with the pen! It looks like he's trying to commit sudoku!|"

**Comment by freerealestate** [comment]
i guess
