### ISSUE TITLE
Shadowling Veil not turning off lights properly

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#11952]
Two shadowlings died to a light they couldn't veil, probably implanted, but ALSO a firefighter helmet that wouldn't turn off.

**Comment by whodaloo** [comment]
if this is from the round i'm thinking of, it was a torch on the jacket that killed them

**Comment by Anonus** [comment]
The firefighter helmet also didn't turn off, so something's probably broke.

**Comment by Xhuis** [comment]
Hard hats do turn off. Their sprites don't update, though.
