### ISSUE TITLE
Photos in sec records are sabotage proof

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#11986]
Basically, the photo provides a 100% certain way to see what someone's starting job is.
The only way to change the picture is by uploading a camera photo, which is really obvious as it shows as a standard picture instead of the round start preview photos.

**Comment by SconesC** [comment]
And?

**Comment by PKPenguin321** [comment]
honestly if somebody actually somehow manages to solve a crime using these, they deserved it
i've never heard of them being used before

**Comment by optimumtact** [comment]
this isn't even the most pressing issue, which is if you set someone to arrest that status will follow them around on the sechud through basically any type of identity change until someone causes the arrest record to be recalculated.

**Comment by Shadowlight213** [comment]
@SconesC rank can be changed on the sec records, people trying to infiltrate can get loyalty implants and everything. Perfect disguise, until someone looks at their photo and sees that they are an assistant.

**Comment by SconesC** [comment]
Owned, then.

Non-issue and promotes use of the otherwise borderline useless record system.

**Comment by optimumtact** [comment]
get out of town scones

**Comment by tuypo1** [comment]
I agree its a good thing

**Comment by astralenigma** [comment]
They can claim the HoP gave them the access all the pictures prove is that they were that job before being promoted.
I kinda of agree there should be some standard background to be used in the photos probably near the HoP's and Sec's office to upgrade the records.
