### ISSUE TITLE
Sleeping carp move apparently doesn't work with the grab item in hand for the next step?

### ISSUE THREAD

**Issue by Ausops** [tgstation/tgstation#12011]
HELP: RainofSpades/(Ziggs Pippbottom): Seems to just be Stomach Knee Grab Harm.
PM: RainofSpades/(Ziggs Pippbottom)->Ausops/(Anna Avery): I'll try switching hands, maybe it's the "Grab" item.
PM: RainofSpades/(Ziggs Pippbottom)->Ausops/(Anna Avery): It sure is.

Reproduced in a later round. The message the victim gets is also fugged.

<span class'userdanger'>Ziggs Pippbottom winds you with a knee in the stomach!

Also doesn't seem to stun, despite the description suggesting it does.

**Comment by Xhuis** [comment]
It does stun. The grab is intended, but the item is not. There's no way to fix this other than changing the combo.

**Comment by ChangelingRain** [comment]
grab item is dead
