### ISSUE TITLE
Changeling Shriek will blind/disorient you in space

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#12022]
But being in space, no sound is played, meaning its either

A) A bug that it works in space or

B) Should be some kind of feedback for the victim so they can tell whats going on, even in space.

**Comment by RemieRichards** [comment]
Haha, I think this one is technically on me.
I added our version of sound dampening with atmospheres, and at a low enough value, sounds don't always play (however for us in space it does play it, just super quietly)
the proc for Shriek doesn't care if the sound effect played, it never needed to in the past.

While logical "sound in space" sounds silly, none of our atmospheric effects can ever bring a sound low enough to not play (space drops it *FAIRLY* low, but you can still hear airlocks and stuff) so technically it's not -really- an issue. but blacklisting it with ```isinspace()``` is easy.

**Comment by PKPenguin321** [comment]
by this logic flashbangs shouldn't be as effective in space too

**Comment by Marflowerose** [comment]
The shriek uses localized spherical bluespace to tickle the target cells in quantum level.
