### ISSUE TITLE
Rev round end report doubles names

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#12034]
http://i.imgur.com/IlQTHNJ.png

Happens to just a single name on the last every rev round.

**Comment by freerealestate** [comment]
will happen to multiple names too

>The heads of staff were:
Allen Westry was Devon Knight the Chief Medical Officer and had their body destroyed
Amnestik was Ethan Milne the Captain and died
Laz0r was Johnathan Rock the Research Director and died
Laz0r was Johnathan Rock the Research Director and died
PutinRootin was Max Rockatansky the Head of Personnel and died
PutinRootin was Max Rockatansky the Head of Personnel and died
Helgraf was Helgraf Dragonhammer the Head of Security and died
Amnestik was Ethan Milne the Captain and died

bug's been around for years as well

**Comment by Incoming5643** [comment]
As I've mentioned before this seems (at least for the most part at least) because the corpses of staffs of heads are counted independently of their clones. Your shift start job is tied to your body for some bizarre reason.

**Comment by freerealestate** [comment]
I thought that might've been the reason too, but in that round I died and was cloned and only got counted once in the end of round report (pretty sure my body wasn't destroyed either)

**Comment by bgobandit** [comment]
apparently this didn't get fixed

**Comment by bgobandit** [comment]
yo @KorPhaeron or others,  has anyone seen this since my fix
