### ISSUE TITLE
The chameleon stamp does not properly deny cargo manifests

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#12052]
What happened: I was a cargo traitor who happened to have a cham stamp handy. We got a crate with an incorrect destination, so I changed the stamp to DENIED and stamped it -- the X showed up on the sprite and everything. When I sent it back, the points didn't get refunded ("+0: Station approved package 3139 despite error: Destination station incorrect. Be more vigilant.")

How to reproduce: Get an erroneous manifest and a chameleon stamp and test for yourself.

Why this is bad: I WANT MY POINTS DAMMIT, also the cham stamp does so few things that it's a shame it can't even do some of them right

**Comment by Shadowlight213** [comment]
Sounds like something has a snowflake check
