### ISSUE TITLE
Stickyban runtime errors caused by putting number/IP/IPrange

### ISSUE THREAD

**Issue by NullNeska** [tgstation/tgstation#12068]
Any admin with access to the stickyban panel can cause the panel to stop displaying properly by inserting a number, IP or IP range. something about a bad index.

runtime error: bad index
proc name: stickyban gethtml (/datum/admins/proc/stickyban_gethtml)
  source file: stickyban.dm,130
  usr: FlavoredCactus (/mob/new_player)
  src: /datum/admins (/datum/admins)
  call stack:
/datum/admins (/datum/admins): stickyban gethtml(null, null)
/datum/admins (/datum/admins): stickyban show()
FlavoredCactus (/client): Sticky Ban Panel()

**Comment by dragomagol** [comment]
![image](https://github.com/tgstation/tgstation/assets/66640614/56c6f559-0e80-4abd-8619-4871897dfc27)
