### ISSUE TITLE
Being asleep (due to sleepypen?) still allows you to talk

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#12114]
I can't go into much detail yet but

A ling took me into surgery and:

You feel a tiny prick!
.. You can almost hear someone talking ...
... You can almost hear someone talking ...
[The 'someone talking' messages stop here but my screen looked unconscious still]
Fortune Ray snores.
[I can talk now even though the screen shows I am unconscious and I am still snoring. I'm mid-strangulation, no proboscis appeared though] 
Fortune Ray says,  "HELP"

Why this is bad: Incredibly cheap and stupid for the person trying to kill

**Comment by PKPenguin321** [comment]
if this applies to all forms of chem induced sleep then high priority tag

**Comment by Xhuis** [comment]
Unable to reproduce on my local server - due to a parapen, anyway.

**Comment by tkdrg** [comment]
It would be interesting to confirm if this is still happening, considering this hasn't ever been reproduced and the related code has been significantly changed.

**Comment by PKPenguin321** [comment]
this was caused by the morphine bug that made you fall in and out of sleep really quickly i believe

**Comment by phil235** [comment]
@PKPenguin321 That morphine bug was very recent, this issue is from october.

**Comment by optimumtact** [comment]
old with no repro
