### ISSUE TITLE
WIZARD LIGHTNING BOLT BREAKS ADMIN MIDIS

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#12118]
The sound for lightning bolt spell stops all sounds for nearby mobs, causing admin midis to stop playing
Priority Critical, FUCK tags needed

**Comment by Bawhoppen** [comment]
FEATURE

**Comment by freerealestate** [comment]
^

**Comment by Shadowlight213** [comment]
@Cuboos

**Comment by Cuboos** [comment]
fuck if i know

**Comment by Shadowlight213** [comment]
You added the sound thing. Might have been the way you had it play.

**Comment by Cuboos** [comment]
Well, there's something in there that stops the charge up sound if you cast before it's finished. It's a bit wonky but i never tested it out while playing midis. I don't know any other way to do it though.

**Comment by RemieRichards** [comment]
Admin sound channel is now the 1023rd out of 1024 possible channels likely to be picked.
there would have to be 1022 other sounds playing at the exact same moment for the admin one to be overriden.

this is "fixed", though I say it'd make sense to move the implicit random channel to our own code to purposefully protect sound channels.
