### ISSUE TITLE
There is no way to view the entire game map without having to go to the forums

### ISSUE THREAD

**Issue by TheRealGLH** [tgstation/tgstation#12124]
Unless you're talking about Box or Meta, though. Those actually have a page on the wiki.
My suggestion is to show the player a link to the full map at roundstart/ whenever someone latejoins. That way nobody can complain over common radio/ OOC about how they can't find escape or other critical places.

**Comment by Dorsisdwarf** [comment]
Technically you can bust into medbay and use the suit sensors console.

But yes, someone needs to sprite maps for the new maps

**Comment by Jalleo** [comment]
This is not a issue for github more a issue for individual mappers and the wiki maintainers.

**Comment by duncathan** [comment]
We have a system set up that generates a minimap at roundstart. Why don't we make that a feature of the PDA or something?

**Comment by Jalleo** [comment]
That could be done sure but for servers without that feature will have the issue still.

**Comment by duncathan** [comment]
???
It's built into our codebase. It's what the crew monitoring console uses.
