### ISSUE TITLE
Rotated inner shuttle diagonal walls look like shit

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#12130]
This probably isn't fixable without some snowflake code but hey, here's a bug.
![I deleted this puush at some point but all you need to do to replicate it is move a shuttle on a map that rotates it](http://puu.sh/pgOPn/d8d5a65fbe.png)

**Comment by duncathan** [comment]
Diagonal walls are already snowflake

**Comment by xxalpha** [comment]
There's no code, those are just regular sprites.

**Comment by tuypo1** [comment]
the problem looks to be that the floor next to them does not match up

**Comment by KorPhaeron** [comment]
I think this got fixed by smooth walls right?

**Comment by ChangelingRain** [comment]
This didn't get fixed by smooth walls, no.

**Comment by xxalpha** [comment]
It did if you used smooth walls.

**Comment by ChangelingRain** [comment]
Using smoothwalls makes the problem worse, see #18097

**Comment by xxalpha** [comment]
Someone broke that then, ask mso.
