### ISSUE TITLE
White Ship can kill (ramming) remotely (EDIT: Shuttle hitboxes are squared?)

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#12168]
Just had an instance where, floating through space, I saw the White Ship's outer hull on the very edge of my vision, then started floating in the other direction, and was dead.

According to NikNakFlak, I had 700 brute, which is consistent with being rammed by a teleporting white ship. What isn't consistent is that the ramming didn't occur. It appeared ahead of me, oh yes, but I was barely close enough to see it, let alone be rammed by it. 

Yet another glitch-caused death to add onto the conga line of buggy premature game enders which I have endured over the last couple of months. So, what could have caused this one?

**Comment by PKPenguin321** [comment]
being shuttleslammed moves you to the edge of a shuttle, since space all looks the same it may have moved you to the edge of the shuttle and you didn't notice, making it look like it didn't hit you when it did

**Comment by Anonus** [comment]
Yeah no, shuttles hit and destroy anything in the box they move to even if the shuttle turfs don't actually even touch that spot.
I had to move the white ship's docking port up a tile on my map because otherwise it'd break some windows and expose arrivals to space.

**Comment by Jalleo** [comment]
You were almost certainly at the white ship but probably due to lag did not see it that way

**Comment by AnonymousNow** [comment]
I'm a miner's canary for lag on /tg/station, and if it happened then then it was the first instance I'd encountered in that round.

My bet is what Anonus is saying.

**Comment by Anonus** [comment]
You can confirm what I'm saying by looking at arrivals in this image https://www.dropbox.com/s/zo0b4oomyakvmv2/Dreamstation02.png?dl=0 
See where the two windows near the white ship are missing? Yeah, it destroyed those.

**Comment by AnonymousNow** [comment]
That's also consistent with the bit of the ship that I saw.
