### ISSUE TITLE
All plasteel type floors are broken

### ISSUE THREAD

**Issue by Razharas** [tgstation/tgstation#12179]
When you try to change the simulated floor to the plasteel type floor plasteel type floor will retain the icon state of the old simulated floor every time

https://github.com/tgstation/-tg-station/blob/master/code/game/turfs/simulated/floor.dm#L116

https://github.com/tgstation/-tg-station/blob/master/code/game/turfs/simulated/floor/plasteel_floor.dm#L11

This is why cult floors arent being shown, all simulated->plasteel type floor conversions will retain the icon of the old floor

**Comment by phil235** [comment]
related to #10180

**Comment by Mervill** [comment]
@optimumtact closeable, looks fixed and this is from 2015
