### ISSUE TITLE
Camera network chunks do not properly update on shuttle turfs.

### ISSUE THREAD

**Issue by GunHog** [tgstation/tgstation#12170]
If the AI is on or looking at any kind of shuttle, camera chunks may update improperly, or not at all. Example:
![screenshot 2015-10-04 21 33 50](https://cloud.githubusercontent.com/assets/4955510/10272079/ba05b1f8-6adf-11e5-9367-e53195c770ad.png)

On a round in which the CE moved me to the White Ship, I was entirely blind, despite my core having a camera embedded. 

This is generally also an issue sometimes when the AI is being moved and some chunks may not update properly.

**Comment by PKPenguin321** [comment]
pretty sure this also happens with abductor's advanced cameras

**Comment by Giacom** [comment]
I'm guessing the portable cameras are not updating correctly. It's a weird issue, especially if the turf is using tags as they usually give a lot of undefined behaviour. I would first check the map to see if tags are being used.

**Comment by Shad0vvs** [comment]
You cannot see your borgs on the shuttle either and they also have cameras.
