### ISSUE TITLE
Datum/Del() Non-existent 

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#12176]
There is no Datum/Del() defined....as a result, it won't show up in the profiler, and lots of things that are directly deleted aren't tracked, either--could be potentially useful for finding more things to GC if this existed.

**Comment by MrPerson** [comment]
I woulda sworn I had datum/Del() to null tags.

**Comment by duncathan** [comment]
@MrPerson that's covered in `datum/Destroy()`

**Comment by MrPerson** [comment]
Yeah I meant Destroy(). Major typo.

**Comment by MrStonedOne** [comment]
This can not be resolved because defining any Del() proc outside of special types like world/client slows down **all** deletions, soft deletes and hard deletes alike.

**Comment by Cyberboss** [comment]
We could have it defined in the DEBUG revision?

**Comment by MrStonedOne** [comment]
you mean testing? debug is on all the time since that's required for runtimes to print anything useful.

**Comment by Fox-McCloud** [comment]
Trust me, you don't *want* `/datum/Del()` defined; it'll make literally every single deletion (soft or otherwise) dramatically more expensive; even those that don't even pass through the GC!

**Comment by RemieRichards** [comment]
@Fox-McCloud Aww, lag at work didn't let me make fun of what you originally wrote, sadface.

**Comment by Fox-McCloud** [comment]
Yeahh, I didn't realize MSO had already said what I effectively said--went back and re-reviewed it, was like "ohhh derp" and corrected my post.
