### ISSUE TITLE
Revenants should change zlevels

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#12203]
Right now they just hit the edge of the map and don't go to the next zlevel

**Comment by Anonus** [comment]
This is an incorporeal_move issue which shouldn't surprise anyone who knows how it works

**Comment by Rinoka** [comment]
so the issue linked there suggests handling got handed off to @Armhulen so is this issue fixed? idk if your spookymurdergoast rework got fully launched but worth asking i suppose

**Comment by ShizCalev** [comment]
@rinoka Don't think he did anything with it, no.

**Comment by kriskog** [comment]
Revenants can currently leave z-level, so some-one/-thing fixed it.
