### ISSUE TITLE
Ore box contents spontaneously disappearing

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#12200]
**Happened on:** Sybil, 10/6/15, apx. 9:15 PM
I was bringing home a box full of ore from the mining station. I shoved it through a disposal chute to get it home faster. I then brought it with me back to the station, and when I went to empty it I discovered that it was completely empty. I have no idea how this could have happened.

**Comment by Zilenan91** [comment]
Could it be possible that a mining mob or gibtonite explosion broke part of the disposal chain leading to the main station, causing all the ore to spew out onto the floor?

**Comment by Xhuis** [comment]
@Zilenan91 When I had the ore box filled, I used a mining jetpack to fly through space to the station. The only bumpy ride the box took was through a disposal chute.

**Comment by coiax** [comment]
I feel like this is just never going to be fixed with the information we have available. Also, we don't even have the mining asteroid anymore.

**Comment by vuonojenmustaturska** [comment]
@KorPhaeron
