### ISSUE TITLE
Orion Trail Double Changeling Homocide

### ISSUE THREAD

**Issue by Aredal** [tgstation/tgstation#12215]
If you click twice fast enough in the changeling risk/kill option choosing the kill option it will kill two crewmembers.

**Comment by WJohn** [comment]
@RemieRichards

**Comment by astralenigma** [comment]
Well the system works like webpages loading so he loaded the same page twice.
Any fixes will conflict with this update. #12145

**Comment by MrStonedOne** [comment]
Ya, the system needs to do more sanity checking.

You can generally load the action webpages manually to get it to let you do things.

**Comment by SuperNovaa41** [comment]
This has been fixed due to a couple reworks
