### ISSUE TITLE
Bombs can be triggered after you've removed the trigger

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#12237]
I removed the signaller on a bomb, it got signalled, and THEN it blew up even though the signaller was already off of it when it got signalled.

**Comment by Dorsisdwarf** [comment]
@Anonus any luck reproducing this?

**Comment by phil235** [comment]
What kind of bomb are we talking about? I can't reproduce with a TTV bomb

**Comment by tkdrg** [comment]
@Anonus do you have any more information on this bug?

**Comment by Anonus** [comment]
It might be that bombs take a second or so to mix and explode but what I said is basically what happened, I found a bomb, removed the signaller, heard it beep, and then exploded.

**Comment by tkdrg** [comment]
Additional info that I squeezed from Anonus on irc:
* It really was a TTV bomb.
* He really heard/saw the beep AFTER removing it.

**Comment by Jalleo** [comment]
I think this is a byond issue by both things already being set to process within the same tick or so before byond could realize the signaler was already out of the bomb.

**Comment by phil235** [comment]
@Jalleo The code looks straightforward to me. I guess I'll try reproducing the bug again.
Isn't there a short delay when the two tanks contents are mixed though? It could explain seeing the beep message before the explosion occurs.

**Comment by Jalleo** [comment]
The message from visible message could of been recieved by Anonus too late as well meaning it was activated before removal which would also explain this.

**Comment by Cyberboss** [comment]
Closable methinks

**Comment by Cyberboss** [comment]
@lzimann
