### ISSUE TITLE
No Atom/Destroy()

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#12245]
Simply put, there's no Atom/Destroy(), when there really should be.

For example, any atom can have reagents in it, but yet qdel()ing of reagents is handled on the atom/movable level. While I know of no turf that has reagents in it, it's still best to handle getting rid of something on the level it's defined at....likewise, it means you could push invisibility = 101 up another level so it applied to more than just atom/movable.

**Comment by MrPerson** [comment]
Turfs can't be gc'd. Dunno about areas. Only real sensible option would be to call Destroy() in turf/Del() I guess.

**Comment by Fox-McCloud** [comment]
@MrPerson 

I'm aware of that, it's more the fact that reagents are defined on the atom level, so qdel'ing/nulling out references to them should also be on the atom level, as well.

I also believe that Turf/Del() was converted into Turf/Destroy() (that said, it returns a HARD_DELNOW hint).
