### ISSUE TITLE
Things that are still del()'d

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#12274]
@duncathan 

Here's a few things that are still `del`'d; not all of them should necessarily be `qdel`'d, but it's something to look at:
- some fake attacker images in hallucinations
- a lot of clients in the admin modules/topics
- inactivity
- SQL2 related things
- Client/New

I'm sure there's others.

**Comment by Iamgoofball** [comment]
@MrPerson can't we qdel images now?

**Comment by Iamgoofball** [comment]
oh and clients can't be qdel'd, causes problems apparently

**Comment by Fox-McCloud** [comment]
They can't be, but right now, there's still a Client/Del()---if `qdel` gets passed a non-datum (clients, for instance), it sees that and says "ahh, not a datum; can't be put in the GC queue; let's just call `del` on it) and it ends up calling `del` anyway.

Also, @Iamgoofball images are technically a child of datum, so yes, I think they can be GC'd.

Of this list, the biggest concern of actually calling qdel on something here would be in SQL2--as a delete function int here is for(var/datum/d) qdel(d). I realize that the GC can handle GC'ing datums, but in this instance, it comes across as a bit dangerous to qdel here.

**Comment by MrPerson** [comment]
Spending any time sanity checking the SQL stuff is a complete waste of time. Don't even bother.
