### ISSUE TITLE
Boxes prevent borg energy loss from movement

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#12278]
:8ball:
lets you sneak past energy consumption

**Comment by Bawhoppen** [comment]
Boxes were the best addition

**Comment by Incoming5643** [comment]
Theoretically a borg riding a secway/janicart would have the same problem

**Comment by Firecage** [comment]
...I don't think so, the borg would still be literally moving. Like how humans slips on stuff when riding a secway/janicart

**Comment by ChangelingRain** [comment]
borgs don't LOSE power from moving
