### ISSUE TITLE
Lings can come back from suicide

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#12289]
Suicide is supposed to show that you don't want to play anymore, and that your body is fair game for gibbing. Lings shouldn't be able to come back from it.

**Comment by PKPenguin321** [comment]
iirc they can revive from it but when they do they take constant oxyloss damage (similar to how suicide used to not kill you instantly and if you survived via dexalin plus you would take constant oxy damage)
unless that was changed

**Comment by Aliannera** [comment]
Someone in deadchat asked me to test this fairly recently just to find out, and I came back from a suicide as ling without taking constant oxy damage. Could be a feature or strategy, but yea might be best to change so you can't regen as a suicided ling.

**Comment by pudl** [comment]
STOP KILLING LING META

**Comment by XDTM** [comment]
Feature or bug? I personally would say it's a feature.

**Comment by Robustin** [comment]
I vote feature people would fucking open an issue thread if they committed suicide as a ling and couldn't revive since lings can come back from anything short of gibbing/cremation so it wouldn't make sense to deny revives because you bit your tongue off with PASSION.

**Comment by Bawhoppen** [comment]
The way I see it, suicide is supposed to be an OOC indicator that the body is out of the round for good and shouldn't be able to get back into the round in any way.
I realize they can be resurrected in various ways as is, but personally I think we should have it so you can always be revived as a suicide making it no different than a normal death, or never be able to under any circumstances, not our current "only if the cloner is upgraded" shit
