### ISSUE TITLE
Server Config Code Config

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#12293]
Not really a bug, but a bit of a feature request and a bit of a consistency issue.

@MrStonedOne mentioned having the same configs/game options that are running on the live server being the same configs/game options that's on the codebase.

Would just like to request this be done--it allows for more accurate testing, mob movement behavior, explosion size benchmarking vs performance, etc It also gives downstreams somewhat of an idea of the actual settings to get the full "TG Experience" so to speak.

**Comment by MrStonedOne** [comment]
Alright, So first, i'll need to go thru the config to import all the settings we don't have. (when a net config is made, If the default works, the actual setting almost never gets imported to the file.)

**Comment by Fox-McCloud** [comment]
@MrStonedOne 

Any status update on this, per chance?

**Comment by Dorsisdwarf** [comment]
@MrStonedOne 

Closing in a week if no progress update
