### ISSUE TITLE
Known issues with away missions/any dungeon like content

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#12325]
Dont want to clog up issue reports with a ton of these, this list is mostly for myself if away missions ever seriously get reworked or lavaworld (never happening) happens.

You can use medibots to infinitely heal out of crit, as mobs will ignore them

You can use viruses in a similar manner

You can abuse infinite heal powers like fleshmend

You can sneak past everything with a camo projector or box

You can use wormhole jaunter, strange object, or disposals create to bypass walls/obstacles

**Comment by Anonus** [comment]
box sneaking is a feature

**Comment by Anonus** [comment]
Also making maps that are literally fighting pits is awful and balancing them is impossible and a stupid idea to try, though an actual dungeon might be cool if it wasn't full of monsters.

**Comment by Shadowlight213** [comment]
Box sneaking is totally a feature. Not removing that.
Various teleport stuff can be given a check for away missions like I'm pretty sure the hand tele has.
Same thing can be done for medbots, or mobs can have that var set that makes them attack people in crit.
Disposals stuff I don't know how to fix. I can try disabling the RPD on away missions, but that seems hacky.

**Comment by Miauw62** [comment]
remove all away missions except WJs missions on account of they suck.

**Comment by Shadowlight213** [comment]
@anonus
It seems that dungeon exploration away missions are out of the question unless they become closed source, so any away missions with a reward at the end will have to become fighting pits.

**Comment by duncathan** [comment]
@Shadowlight213 or we could use procedural generation, like rougelikes do.

**Comment by Shadowlight213** [comment]
@duncathan Maybe. Not sure if remie's generator would be able to accomplish that

**Comment by Miauw62** [comment]
or we could make more away missions like WJ's
