### ISSUE TITLE
Package-wrapping a large cardboard box displays the wrapped locker sprite

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#12335]
What happened: see title
How to reproduce: see title
Why this is bad: THE LAW OF CONSERVATION OF MASS

**Comment by Incoming5643** [comment]
Will fix.

**Comment by Miauw62** [comment]
>conservation of mass

doesn't apply here, no mass is being converted, just volume.

**Comment by freerealestate** [comment]
would this be a game over
