### ISSUE TITLE
Most of the vv menus don't have a cancel option

### ISSUE THREAD

**Issue by MrPerson** [tgstation/tgstation#12332]
Many of the menus involved in vv will give a list of options without a cancel button. The only way to cancel is to quit and rejoin. Most of them are "as anything in list" when they should be "as null|anything in list".

Just off the top of my head, the list entry addition menu and reference selection menus both suffer from this, but I'm sure pretty much all of them do.

**Comment by xxalpha** [comment]
Also ckey input is a huge textbox that won't register the Enter key as 'OK' and it grinds my gears.

**Comment by Firecage** [comment]
MrPerson. Would you perhaps make a list of the ones you can spot?

**Comment by MrPerson** [comment]
Probably not, I never do much vv edits, especially not ones that involve lists or references, which are the worst offenders.

**Comment by bgobandit** [comment]
FIX THIS SHIT
