### ISSUE TITLE
Map rotation allows you select jobs that are unavaible on some maps

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/tgstation#12428]
How to reproduce: 
1. Pick a job in preferences that is not avaible on some maps like ministation or birdstation. A good example is CMO which is unavaible on both. You can only do this on a map that does not remove jobs.
2. Wait until the map changes to one where the picked job is unavaible.
3. When you open setup you get an error message.
4. Probably some worse stuff happening when you ready up but is untested yet.

**Comment by Incoming5643** [comment]
I'm going to guess you can't select map specific jobs like Lieutenant on ministation either

**Comment by MrStonedOne** [comment]
This isn't exactly a map rotation issue

You can have this issue if the server's map is changed for any reason, as changing a map doesn't wipe preferences (nor should it)

Remember, basil used to be on ministation, and before that meta, so i best this issue happened to some people then as well.

**Comment by TrustyGun** [comment]
You can have separate job configuration files for each map, it would be annoying to reset your configurations every time the map  changes, but there will be no issues

**Comment by MrStonedOne** [comment]
Na, that isn't a proper fix, A proper fix would be for the map makers to get together and figure out a way to convert standard jobs for maps that don't have them to other jobs.

**Comment by Incoming5643** [comment]
Job code has a section where you can be disqualified for a roll without it impacting your other job chances, this is the section that keeps people marked for traitor out of sec rolls and lizards out of command. We could just add a check to make sure a spawn point for that job exists on the map before it's given to them.

That said we don't have a bug report of CMOs ending up in nullspace, so the code must already be doing something.

**Comment by MrStonedOne** [comment]
Ya, it already is, but this relates more for the screen to choose job prefs

**Comment by kriskog** [comment]
Since we no longer have maps with unavailable jobs, I am closing this.
