### ISSUE TITLE
runtime error: wrong type of value for list

### ISSUE THREAD

**Issue by caelaislinn** [tgstation/tgstation#12439]
The following runtime has occured 6 time(s).
runtime error: wrong type of value for list
proc name: updateSeeStaticMobs (/mob/living/simple_animal/drone/proc/updateSeeStaticMobs)
  source file: visuals_icons.dm,163
  usr: (src)
  src: Drone (548) (/mob/living/simple_animal/drone)

https://tgstation13.org/parsed-logs/sybil/runtimes/runtime-2015-10-16-condensed.txt

For this one, I'd say someone might need to go through all the mobs and find out which one is putting bad values into their var/staticOverlays

Could be quick, could take a while. I might have a look later if I get time but not now.

**Comment by MrStonedOne** [comment]
>For this one, I'd say someone might need to go through all the mobs and find out which one is putting bad values into their var/staticOverlays

Ya, This error is basically when somebody tries to stuff a non-image into client images.

**Comment by caelaislinn** [comment]
It's happening with drones specifically though, so that might be a good place to start.

**Comment by vuonojenmustaturska** [comment]
@KorPhaeron I can't find any references to this runtime in the logs, which doesn't surprise me given that there have been two years since it was reported.
