### ISSUE TITLE
Swarmers can't deconstruct turrets

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#12462]
I tried to deconstruct a turret on the AI sat the other day, and it did one of two things, it either : 

A. deconstructed only the cover, but not the turret itself, which shouldn't happen afaik
or
B. Deconstructed the entire turret but it failed to deconstruct, still giving me the metal

I've also had this bug happen a very long time ago and never reported it, I just kept deconning the turrets in the AI upload and they never died, but kept giving me more and more metal. The turrets even looked destroyed but when the AI noticed me it turned the turrets on and even the ones I deconned killed me.

**Comment by PKPenguin321** [comment]
iirc, turrets are supposed to be blacklisted from the things you can eat

**Comment by Dorsisdwarf** [comment]
Portaturrets can't be eaten by swarmers.

**Comment by Jordie0608** [comment]
While not deconning turrets is intentional, what's described by the issue is a bug.

**Comment by Dorsisdwarf** [comment]
No longer happens, they have an explicit refusal to decon message now.
