### ISSUE TITLE
It's not always possible to actually open safes

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#12474]
Server: Basil

Revision: 2015-10-18
8ae5b8bcc778e98219c3c6309ee1b315ebcc00f3 

Problem Description: After turning the dial positive and then negative, hitting the first two numbers in the safe, turning the dial positive again will not give you the third number ever. Done using a stethoscope on BirdBoatStation but I seem to remember having the same problem on Box.

What did you expect to happen: Eventually run into the third number and be allowed to open the safe

What happened instead: No third number arose.

Why is this bad/What are the consequences: It is impossible to access anything stored in a safe.

Steps to reproduce the problem: Attempt to open a safe following these instructions: https://tgstation13.org/wiki/Hacking#Safe

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): N/A

**Comment by Iamgoofball** [comment]
you need to buy a drill for $2.49 to open the safe, sorry

**Comment by Tokiko1** [comment]
It is usually possible, but I am sure that the code does not check if the positions are actually solveable so sometimes you will get an impossible lock. I did see people opening safes today though so it is very likely possible.

**Comment by newfren** [comment]
Just tried again and could not open the safe on birdboat - it had different numbers than the first attempt on birdboat but still the third number didn't come up.

**Comment by ShizCalev** [comment]
Okay, so after some extensive testing on my part, they do seem to be functioning correctly. The first tumbler that has to be set is tumbler #2. From there, you have to move in the opposite direction to set tumbler #1. 

The context of the clues provided is -EXTREMELY- important, as they are giving you direct feedback to what it happening. 

You -will- hear clinking while trying to find the position for tumbler #1, as tumbler #2 remains set during this time. I assume people hear that and think that they have set the next tumbler and start on a third, **which is incorrect as there is no third number to find.**
