### ISSUE TITLE
Mousedropping vs. grabbing then clicking people into stuff?

### ISSUE THREAD

**Issue by kingofkosmos** [tgstation/tgstation#12481]
I'm 100% sure I'm not the only one who's panicked and lost a ling due to panicking because I didn't realize I need to GRAB then CLICK the ling into the gibber, instead of just mousedropping it in there. **This kind of inconsistency is bad and confusing as fuck.**

**Grabbing + clicking:**
- Gibber
- Meat spike
- Washing machine (corgi)
- Transit tubes
- DNA Scanner

**Mousedropping (preferred method):**
- Trash bin
- Morgue tray
- Bodybags
- Disposal unit/bin
- Closet
- Photocopier

**Both:**
- ~~Disposal unit/bin~~ (fixed in #14869)
- ~~Closet~~ (fixed in #14873)
- Suit storage unit
- ~~Photocopier~~ (fixed in #14868)
- ~~Bins~~ (fixed in #14919)

EDIT: List updated.

**Comment by freerealestate** [comment]
You used to be able to drag and drop people into disposals, but it got changed. If I remember correctly it was because they didn't want borgs doing it due to their lack of arms.
