### ISSUE TITLE
EVA cam (and possibly other motion cams) alert is broken

### ISSUE THREAD

**Issue by TheRealGLH** [tgstation/tgstation#12486]
"--- Motion alarm detected in EVA Storage! (A HREF=?src=[mob_150];switchcamera=[icon-camera (NORTH)]EVA Motion Sensor)"
This was on Dreamstation, so it may be map specific.

**Comment by Anonus** [comment]
The camera is copied from box, so if it happens on dream it'll happen on box, too.
Might be related to #12433 and #12435

**Comment by Penguaro** [comment]
Recommend Closing as Map has been removed.

**Comment by Penguaro** [comment]
@TheRealGLH @ChangelingRain @Dorsisdwarf Testing on the most current revision of Box, the motion cam and link for the alarm seem to be functioning. Dreamstation is also no longer used. Close this?
