### ISSUE TITLE
Ripley suddenly denying access to everyone

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#12489]
This happened on Sybil, at 3:41 PM EST, on October 18, 2015.

I was a shaft miner and had just acquired a Ripley for mining. I got in with no issues, turned the lights on, started using the internal airtank for air, and brought it to Cargo. I jumped out next to the autolathe and printed an industrial welding tool for repairs and tried to get back in, only to discover that I was suddenly locked out. Neither me, the detective, or the cargo technician nearby could get into the mech, and I was frustrated enough to suicide. I have no idea how this could have happened.

A raw log from Dream Seeker can be found here: https://dl.dropboxusercontent.com/u/116194515/log%202015-10-18%20%283%2043%20pm%29.htm

**Comment by phil235** [comment]
You weren't able to enter the mech specifically because you didn't have the required access apparently. Either someone changed the access requirements while you were in the mech, or they were changed while you were climbing into the mech for the first time.

**Comment by Dorsisdwarf** [comment]
Not sure whether it's a bug from Phil's explanation

**Comment by optimumtact** [comment]
Thunder11 couldn't reproduce either, and I doubt this was a bug
