### ISSUE TITLE
Cargo consoles have a snowflakey interaction

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#12534]
You can't actually open the interface unless you're physically wearing an ID unlike other consoles that require access, where you can still open it even if you can't use the functions.

You should need to log in, or just require the ID access to actually authorize the orders.

 (emag also does not remove the lock and it probably should)

**Comment by Lumipharon** [comment]
All the consoles are different - it's really annoying.

Cargo requires the ID in hand (and emag doesn't break the ID lock as mentioned)
Sec records and hop console require you to insert the ID to login
Comm console (and I think med records) only requires clicking with an ID (and the comm console atleast can have it's ID lock broken)

**Comment by Bawhoppen** [comment]
Robotics is accessable now universally (it used to not be) but you might need the ID on you or in a hand to actually queue stuff, but I don't remember.

**Comment by Lumipharon** [comment]
I mean the robotics lockdown console thing, not the exofab.

**Comment by Bawhoppen** [comment]
Yea. We really do need some level of consistency for all the consoles.
