### ISSUE TITLE
facehugger protection is illogical and inconsitent

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#12574]
the cardborg hat protects you but the atmos fire-helmet dosen't.
what is life?

**Comment by Bawhoppen** [comment]
IMO nearly all helmets should block huggers

**Comment by WJohn** [comment]
Yeah, I think it should probably be revised a bit, and it should definitely knock off your helmet if it successfully facehugs you.

**Comment by Dorsisdwarf** [comment]
IMO there should be two levels of facehugger protect, one which is the current (they bounce off it), and the other which they rip off the protective item and destroy it, but are killed (So one facehugger can't be yolothrown to get you, but running into DA HIVE will still cause you to discover how babby is form)

**Comment by Steelpoint** [comment]
ACM has a system where helmets will block one facehugging attempt but it'll destroy the helmet.

**Comment by neersighted** [comment]
Bump?

**Comment by Dorsisdwarf** [comment]
If you want to ask a coder to fix something in particular, @neersighted , you're better off picking an unlucky soul on the bus and nagging them mercilessly.

**Comment by Bawhoppen** [comment]
i recommend anturk

**Comment by WJohn** [comment]
I would like to point out that welding helmets only protect you while they're facing down. If the visor is lifted up, it will not. This is fine and all, but it's inconsistent with how RIOT helmets work. They protect you regardless of whether the visor is up or down.

**Comment by PKPenguin321** [comment]
i think it's weird with riot helmets because for them the visor is completely cosmetic so it doesnt matter at all

**Comment by Davdichan** [comment]
Anything that covers the face should provide protection. To include gas mask and hailers. CM system is cancer with infinite huggers able to destroy limited supply helmets

**Comment by WJohn** [comment]
I don't think ANY mask should provide protection, they're just too common and easy to get, even if it doesn't include breath masks or mouth-only sec hailers, you still have full gas masks, clown/mime mask, full-face sec hailers, welding masks and so on that you can mass print. It'd promote shitty idiot assistants running in to try and melee the queen while still getting killed, if anything this'd probably buff xenos with free idiot hosts.

**Comment by Davdichan** [comment]
Welding helmets provide hugger protection and can be printed from autolathes at round start, so it being a recreatable item isn't much of an excuse for open faced hats and helmets provide hugger protection but full face covering masks do not.

Lets not forget that Facehuggers ARE an infinitely produceable stun item that a queen can endlessly shit out more so long as she can find a clear tile.

Facehuggers shouldn't be the go to method for xeno combat anyways. xenos have (multiple) stuns and ludicrous physical stats for sustained combat, if the crew is aware of xenos they should rightly be able to defend themselves from LOLHUG'd combat of a xeno tossing a hugger.

It's more canon friendly anyways for xenos to have to disarm and capture combatants and drag them back to the nest for infestation, giving other crew a fraction of a chance to save people being captured.

**Comment by WJohn** [comment]
Well, aside from welding helmets screwing over your vision immensely, as a tradeoff for being mass produce-able.

Now whether facehuggers should be throwable or not is a very different question. We *could* rework some of their mechanics to be less like landmines (as they currently hug anything in a 3x3 area without protection), but this again could just promote idiot assistants who think that's a license to run in the nest and fight xenos, where they'll just become hosts.

I think it's better for people to not want to get close to xenos at all, because that at least means they'll *try* to do ranged attacks, which is how you're supposed to fight them anyway.

**Comment by WJohn** [comment]
Also would like to point out: Flipping riot masks up does not even allow you to eat food at all. Isn't that the original point? I think it's more that something is broken rather than an oversight.

**Comment by PKPenguin321** [comment]
It is cosmetic
