### ISSUE TITLE
Slimes can't attack Kudzu

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#12581]
i ded plz nerf

**Comment by bgobandit** [comment]
why would slimes attack kudzu? it's plant, not animal

**Comment by Zilenan91** [comment]
If they're stuck behind kudzu because they accidentally left the vents due to them obscuring all the lights

**Comment by Dorsisdwarf** [comment]
Not sure if bug send help

**Comment by Tokiko1** [comment]
But humans need to find a cutting weapon to attack kudzu too.

**Comment by Marflowerose** [comment]
It's generally weird that kudzu would even block slimes, considering they're kinda gelatinous.

**Comment by Supermichael777** [comment]
slimes that eat a kudz seed should totaly gain the ability to shoot spikes.
also you cant make food out of (kudz)[https://en.wikipedia.org/wiki/Kuzuko]

**Comment by Jordie0608** [comment]
@Tokiko1 Yeah but on the other hand, slime can't go and pick up a knife.

**Comment by ChangelingRain** [comment]
shit phil fixed by accident
