### ISSUE TITLE
Flashes go off when activated in containers

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#12591]
What happened: I was on the bridge, some asshole with TK decided to flash me, I grabbed the flash and put it in my backpack. Asshole continued to flash me with the same flash -- I know it was the same one because the sprite flipped and everything.

I think it speaks for itself why this is bad.

**Comment by phil235** [comment]
Did he remove the flash from the bag or just used the flash while it was inside your backpack?

**Comment by bgobandit** [comment]
The flash didn't leave my backpack as far as I know.

**Comment by xxalpha** [comment]
How is this bad? It's TK.

**Comment by Anonus** [comment]
you can beat someone to death using an item they're holding via TK

**Comment by RemieRichards** [comment]
@Anonus that's fine, because it's just "Stop hitting yourself, Stop hitting yourself, Stop hitting yourself".
Inside of a container however... das bad.

**Comment by xxalpha** [comment]
Flashes just should flash you when inside things, that is the bug. Cyborg flashes will go off if you EMP them, even if the cyborgs have the flashes stored. And they do flash people around.

**Comment by PKPenguin321** [comment]
this is fine, it's how TK is supposed to work
it's like putting a rabid squirrel in your backpack. do you really expect it to stop attacking you just because you put it in a backpack?

**Comment by bgobandit** [comment]
I expect not to see it
