### ISSUE TITLE
Resetting a hacked drone with the maintenance drone sprite breaks the sprite

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#12595]
@Xhuis

**Comment by Xhuis** [comment]
Weird, this didn't happen in testing. Will look into it.

**Comment by RemieRichards** [comment]
@Xhuis that should be your name on github, instead of "The Half-Finished"
"This didn't happen in testing"

**Comment by Xhuis** [comment]
@RemieRichards Done, thanks for the suggestion
