### ISSUE TITLE
Events (at least wizard ones) aren't respecting occurrence limits.

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#12636]
Saw a round of summon events where mass mindswap managed to proc 3 times, but it's never supposed to happen more than once.

**Comment by Saegrimr** [comment]
Wizard in question used summon events multiple times, not sure if that has any effect.

**Comment by Incoming5643** [comment]
it shouldn't, summon events is a binary on/off thing, taking it more than once makes it proc more often, not gain more instances of the system

**Comment by Profakos** [comment]
This rarely happens with events whose weight is set to 0. Probably lacking a few continues in the loop that select the next event.

**Comment by Supermichael777** [comment]
memealicious. also absolutely terrible

**Comment by Bawhoppen** [comment]
Is this still an issue?
