### ISSUE TITLE
Gravity generator is supposed to be bomb proof in code but isnt.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#12657]
according to the code, the gravity generator is supposed to switch to its broken state if it gets bombed and not delete. However, I've seen the gravity generator get bombed and the whole thing just disappear, which shouldn't be happening.
It's extremely annoying as the gravity generator can be repaired if it becomes broken, but if it gets completely destroyed, it cannot be rebuilt.

**Comment by xxalpha** [comment]
Get bombed with what? I can't reproduce this.

**Comment by Shadowlight213** [comment]
@xxalpha I've seen it vanish when in the dev range of bombs, which it's shielded against.

**Comment by Cyberboss** [comment]
No longer happens, @lzimann
