### ISSUE TITLE
Annihilate spell doesn't log persistently

### ISSUE THREAD

**Issue by lollerderby** [tgstation/tgstation#12692]
Might be an issue with all spells actually, I was too lazy to test, but although you can check spells cast in VV during the round they don't actually seem to show up in server logs anywhere. Should probably do that.

**Comment by Incoming5643** [comment]
Annihilate? Do you mean Disintegrate? If you mean disintegrate the attack of the touch item should log before the victim explodes.

**Comment by lollerderby** [comment]
I mean the ascendant shadowling spell annihilate, although it could be an issue with other spells I haven't checked.

**Comment by ChangelingRain** [comment]
bye shadowling
