### ISSUE TITLE
Latejoin tators can get an objective to assassinate simple mobs (maybe zombies in specific only)

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#12690]
Marflow was Olorin McKellen the Virologist and had their body destroyed
Objective #1: Assassinate zombie, the Animal. Success!
Objective #2: Escape on the shuttle or an escape pod alive and without being in custody. Fail.
The traitor has failed!

**Comment by Bawhoppen** [comment]
It may or may not have been player controlled, but likely not.

**Comment by Supermichael777** [comment]
anything with a mind i think

**Comment by Incoming5643** [comment]
I wouldn't necessarily call this a bug, but I could see how getting an objective to kill something with a name shared by 40 other mobs could be frustrating

**Comment by KorPhaeron** [comment]
for(var/datum/mind/possible_target in ticker.minds)
		if(possible_target != owner && ishuman(possible_target.current) && (possible_target.current.stat != 2) && is_unique_objective(possible_target))
			possible_targets += possible_target

It shouldn't be picking simple animals

**Comment by Supermichael777** [comment]
it might be because the zombie has a human mob inside so it slips by?

**Comment by RemieRichards** [comment]
It picked the person.
THEN
the person becomes a zombie
suddenly ```possible_target.current``` isn't a human anymore, but it's too late, the check already succeeded when they WERE a human
THEN
the game calls update_explanation_text() on the objective, and that's it.

**Comment by Bawhoppen** [comment]
While the specific details I am unsure of in this case, I am almost certain that it was a non-sentient gold slime mob.

**Comment by RemieRichards** [comment]
Can't have been, it needs to have been a sentient one.
Non sentient ones never have minds, and thus can't be picked, and also, aren't human, so can't be picked.

The ONLY way they can be picked is if it was a human who was made the objective target because they were human, only to THEN be turned into a zombie, at which point the target is already set and you end up with a semi-weird objective.
