### ISSUE TITLE
Minor grammar shit with revenant end of round report

### ISSUE THREAD

**Issue by freerealestate** [tgstation/tgstation#12753]
Player was_ the revenant and survived as revenant
Objective #1: Absorb 241 points of essence from humans. Fail.
Objective #2: Attempt to make your presence unknown to the crew. Success!
The antagonist has failed!
1. Extra space between was and the
2. Revenant should probably be capitalised if other antag roles receive capitalisation, not sure if they do just that job titles do
3. Should probably refer to the revenant as "a revenant" not "the revenant" or just "revenant" in case it's not the only revenant and because revenant isn't a proper noun
4. Should say "The revenant" rather than "The antagonist" in the success/failure text, like the other antag reports

**Comment by Carbonhell** [comment]
If it can be of any help, i fixed that on my server by giving revenants names just like shadowling's ones, and we haven't got any more complaints about it
https://github.com/HippieStationCode/HippieStation13/blob/a061042c56667c57c5bc30620ca054536bd03578/code/modules/mob/living/simple_animal/revenant/revenant.dm
