### ISSUE TITLE
Explosions can proc on a mob twice

### ISSUE THREAD

**Issue by GunHog** [tgstation/tgstation#12758]
Problem Description: What is the problem?
<b> Explosions can sometimes proc on the same mob twice </b>?
What did you expect to happen: Why do you think this is a bug?
<b> Explosions should only call ex_act() on each mob once. </b>
What happened instead: How is what happened different from what you expected?
<b>When I was caught in an explosion wearing bomb armor, I expected to leave behind a corpse. I was gibbed instead.</b>
Why is this bad/What are the consequences: Why do you think this is an important issue?
<b>It completely nullifies the point of EOD equipment.</b>
Steps to reproduce the problem: The most important section. Review everything you did leading up to causing the issue.

<b>I was a Thrall, as RD, wearing the Prototype hardsuit, dragging a Syndicate bomb to space in an attempt to protect my masters in Science. It was planted in Sci maint, I heard it beeping and proceeded to try and move it. I succeeded in getting it to space, but I was unable to escape. It exploded next to me.</b>

Server: Which server were you playing on? <b>Sybil, Metastation</b>

Revision: What revision was the server running? Type 'show-server-revision' ingame to find out.
6fa7caee8e2197ff56ff99f05c78e999b52db9d2

On to how I think this happens: I tested it a few times, with mixed results. I added some debug outputs to world, and discovered that ex_act(1) was being called on me twice, and one time ex_act(2). Here is the related human ex_act() code:

```
/mob/living/carbon/human/ex_act(severity, ex_target)

var/b_loss = null
var/f_loss = null
switch (severity)
    if (1)
        b_loss += 500
        if (prob(getarmor(null, "bomb")))
            shred_clothing(1,150)
            var/atom/target = get_edge_target_turf(src, get_dir(src, get_step_away(src, src)))
            throw_at(target, 200, 4)
        else
            gib()
            return
```

From this, I believe the cause to be the mob being thrown in the first ex_act(1), and when the mob reaches a tile not yet affected by the explosion, the explosion's loop catches the mob again, proccing another ex_act().

**Comment by PKPenguin321** [comment]
wow, that's whack

**Comment by KorPhaeron** [comment]
Could you do it like Repulse does and make a list of all the objects to throw them simultaneously after the bomb stuff is done?

**Comment by RemieRichards** [comment]
This isn't a bug.
Think about it, if you were knocked to a place an explosion was going to hit you, you WILL be hit again.

**Comment by Dorsisdwarf** [comment]
*embarrass*

**Comment by optimumtact** [comment]
well it's not physically possible in our world, but I guess it could make sense in the ss13 one.

**Comment by SouDescolado** [comment]
Maybe put the knockback to happen after the explosion loop? Maybe even move the player with the explosion loop.
