### ISSUE TITLE
breathing from an empty internals tank with oxy virus causes you to still breathe in surrounding gas.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#12770]
Guy has the virus that made it so he didn't need to breathe.

He had internals on with the release value set to 0.

Walked in n20 gas.

Went to sleep.

**Comment by Anonus** [comment]
The "no breathe" virus doesn't even do that but that's not related to the issue, really.

**Comment by octareenroon91** [comment]
I imagine there's some conflation between 0 release pressure and valve off.
Shortest change would be forcing a minimum pressure of 1 or 0.1 kPa
