### ISSUE TITLE
You can click the resist button to unbuckle out of a chair while dead.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#12775]
What it says on the tin. Clicking on the action button or the chair won't unbuckle you, but clicking the resist button or typing in resist will.

**Comment by PKPenguin321** [comment]
maybe something to do with this [area of the code](https://github.com/tgstation/-tg-station/blob/e3e6fc13a919ed50a1777471f44deaf04340be7e/code/_onclick/hud/screen_objects.dm#L184)?
