### ISSUE TITLE
Broken flash shows up as a cleaver on Alt+Click

### ISSUE THREAD

**Issue by CosmicScientist** [tgstation/tgstation#12782]
Server revision compiled on: 2015-10-30
58c828ccfefca24f3d1a4a5571527924ff8d90d6 

A broken flash on the floor, when viewed through alt+click shows up with the bloody butcher's cleaver sprite:
![flash_bug](https://cloud.githubusercontent.com/assets/11809482/10865740/dc33a9d6-800d-11e5-9f3e-88b0ead297d9.png)

This might happen to regular flashes, I don't know.

**Comment by MrStonedOne** [comment]
alt click lets byond handle object displaying.

Either that flash really had that icon. or this is a byond bug.

**Comment by Jordie0608** [comment]
Tried, couldn't reproduce.

**Comment by CosmicScientist** [comment]
Hm, alright, I'll try to replicate it myself.

The only other thing off the top of my head was that this was thrown into the disposals system after or around the same time as an actual, bloodied butcher's cleaver.

**Comment by Bawhoppen** [comment]
I've seen similar bugs countless times, don't quite remember what they all were.

**Comment by Dorsisdwarf** [comment]
Looks like it might be related to the VV icon bugs

**Comment by optimumtact** [comment]
old with no repro
