### ISSUE TITLE
Potential weirdness with slime splitting

### ISSUE THREAD

**Issue by imtakingabreakdontatme** [tgstation/tgstation#12797]
So last round I saw a slime person loading up on food to split. However I was a gangster, and he was loyalty implanted, so I tazed and incinerated him.

My question is, if he had split, and I had then converted his clone, could he swap back into his body with the loyalty implant and run around as a gangster camouflaged against sec huds?

@Incoming5643

**Comment by Incoming5643** [comment]
Antag status is mind attached and implants are body attached, so it might be possible to have a rev/gang slime person exist in a a loyalty implanted body if the implants don't "refresh" the mind during a mindswap. The same problem would exist with the mindswap spell and the mass mindswap summon event if so.

My gut feeling is that implant code isn't that great, and that there's probably no protection against this sort of thing. I'll look into it.

**Comment by ShizCalev** [comment]
Still an issue?

**Comment by AnturK** [comment]
If you mean does mindswap and other unusal mind transfers do anything with implants, no. If you mean original issue, no you wouldn't be able to convert them because at that point the second body is mindless.
