### ISSUE TITLE
Teamling objectives are still fucked

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#12808]
I keep posting about this, with all the complaints about Teamling one of its core problems is you've got 8 lings with 8 different objectives that pretty much involve the lings needing to kill absolutely everyone while having objectives that rarely overlap (I need us to replace the engineering team + I need us to replace the medbay staff + I need us to replace science...).

This probably isn't a difficult fix for a bug that's crippling a mode. How long would a bug that gave half the cult "ESCAPE WITH 10 ACOLYTES" and the other half "SUMMON NAR SIE" be tolerated?

**Comment by Incoming5643** [comment]
Honestly I'm not usually a guy who screams remove shit but team ling objectives seem patently not worth having.

**Comment by Robustin** [comment]
Its silly to argue for its removal when a functioning version of Teamling has never existed.

Since its introduction Teamling has been:

1) Given the ling team objectives to kill pretty much everyone on the station
2) Made greentext virtually impossible (and what do we do when team greentext is impossible? Mindlessly murder everyone in sight!!!)
3) Had no teamplay rules or policy

Do you think Nukeops would be popular if each operative had a requirement to murder a different department and the operatives could murder each other if it gave them an advantage?

**Comment by Incoming5643** [comment]
that's why I want it removed. 

1. Ling was never envisioned as a team antagonist mode
2. The objective hasn't been successful as rebranding it as one and 
3. I can think of no way to change the objective that would make it actually fun/possible to do

**Comment by Dorsisdwarf** [comment]
Teamling should be it's own damn gamemode, like DA is to Traitor

**Comment by Robustin** [comment]
How to fix the objectives themselves:

1) Toss the "assume department X identity" objectives. They were a novel idea but ultimately every team antag has an objective associated with ENDING THE ROUND because it works better that way. The only other exception is "Escape with X acolytes" as Cult, but even then that's semi-associated with ending the round since the usual strategy is to go loud and try to wipe out loyalists rather than just have a bunch of covert cult napping on the shuttle. 

2) Make the new objectives associated with ending the round, perhaps that means finally adopting horror form or Husking a certain number of crew. One idea I just had would be to have a set of assassination objectives and once X time or X objectives have been killed, the remaining targets are identified in an automatic centcom message... giving the crew a purpose and creating a more nuanced conflict.

**Comment by Metacide** [comment]
Binning teamling entirely sounds easier, it's an awful mess.

**Comment by KorPhaeron** [comment]
@Dorsisdwarf 

Changeling is awful I dunno how making three modes out of it (ling, traitorling, team ling) will make it any better

**Comment by jughu** [comment]
can be closed since it doesnt exist anymore?

**Comment by CPTANT** [comment]
Close this as ling team objectives were removed ages ago.
