### ISSUE TITLE
All simple animals move too fast now

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#12816]
Guessing this was caused by #12726 

All simple animals move way too fast now. Parasites are going at the movespeed cap, so are wraiths. I'm guessing all of their slowdowns are off by 1 now (unless they all move at max and its just fucked, I have not tested that much yet)

**Comment by Zilenan91** [comment]
clearly this is a conspiracy by Kor so that he can "nerf" the parasites down to "sane" levels /s

**Comment by KorPhaeron** [comment]
@MrPerson

**Comment by tkdrg** [comment]
is this even still an issue

**Comment by KorPhaeron** [comment]
I mean I kinda avoided the issue by just changing the config to compensate, but the default is still all wrong. It's bugged but easy to sweep under the rug.

**Comment by Mervill** [comment]
what about now?

**Comment by KorPhaeron** [comment]
It was never fixed, I just edited the config to slow them down to compensate so there is no real pressure or incentive to fix the bug

**Comment by jughu** [comment]
Time to add a hedgehog mob and make it 2 fast

**Comment by optimumtact** [comment]
priority high lol

**Comment by kevinz000** [comment]
kek

**Comment by Militaires** [comment]
not an issue anymore close

**Comment by kevinz000** [comment]
you're a fucking issue

**Comment by kevinz000** [comment]
i'll close you

**Comment by Militaires** [comment]
@kevinz000 if im an issue then you're paradise's codebase
