### ISSUE TITLE
Cannot hack secure briefcases

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#12884]
Secure briefcases appear to be unable to be hacked via multiool.
![](http://puu.sh/lbWZk/e6fc709bc5.png)

**Comment by francinum** [comment]
Cannot Reproduce.

![](http://puu.sh/lc7UA/481800a9b8.png)

**Comment by francinum** [comment]
They may be referring to the Lockbox.

**Comment by Dorsisdwarf** [comment]
I can confirm they were talking about the secure, codelocked briefcase
I have previously had this bug, which led to having to ask the admins to give me the codes to access the nuke disk inside

**Comment by Firecage** [comment]
Never experienced this bug before.

**Comment by Supermichael777** [comment]
>needing a code to unlock a code locked briefcase being a bug.

Honestly you should need the damn thing open to reset it.

**Comment by francinum** [comment]
@Supermichael777 Making it like that makes the captains safe impenetrable.

**Comment by optimumtact** [comment]
old with no repro
