### ISSUE TITLE
Slime Management Console doesn't check for density when teleporting.

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#12901]
Just saw a round where xenobio defended themselves from invaders by teleporting slimes into the walls at the edges of the room and letting them move into maint.

**Comment by bgobandit** [comment]
hahahahaha that's amazing

**Comment by KorPhaeron** [comment]
Shame I missed it. Feature

**Comment by XDTM** [comment]
If it's a feature then this can be closed, i guess.

**Comment by bgobandit** [comment]
is this a feature or not a feature

**Comment by XDTM** [comment]
@KorPhaeron feature or not
