### ISSUE TITLE
It's possible to get inside the slime computer console.

### ISSUE THREAD

**Issue by tkdrg** [tgstation/tgstation#12953]
No idea how to reproduce. Happened on sybil, some guy ahelped it, said he just clicked it and it happened. His loc was the slime console.

@KorPhaeron

**Comment by PKPenguin321** [comment]
hahaha what

**Comment by KorPhaeron** [comment]
I came back from aghosting or tabbing out or something once and found myself inside the machine. I have no clue how that happens

**Comment by lzimann** [comment]
We never got an info on how this was happening, and I'm pretty sure it's no longer happening(at least haven't seen anyone complaining about for quite some time).
