### ISSUE TITLE
Plasmaman plasma tanks don't fit anywhere but the belt

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#13001]
Relatedly, plasmamen don't get belt slot items.

**Comment by SweaterKittens** [comment]
This isn't a bug. They fit on the back and hardsuit slots, much like large oxygen tanks. However, I'll talk to as334 about having them spawn in-hand so that Engi/Atmos/Robo Plasmamen can get their roundstart belt, and others can get their roundstart PDA.
