### ISSUE TITLE
You cannot cast spells as a ghost anymore

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#13006]
Not sure when this was changed, but before you could cast spells as a ghost if the spell had stat allowed set to 1. Now all the spells get removed while you are a ghost.

**Comment by newfren** [comment]
Out of curiosity, which spells had this stat?

**Comment by Shadowlight213** [comment]
@newfren any spell really. There's a var called stat_allowed that lets it be cast when dead or crit.

**Comment by Thunder12345** [comment]
Spell still visible as a verb while ghosted, but not useable

**Comment by AnturK** [comment]
Can't reproduce. Adding spells through vv and setting stat_allowed works. You might have to set human_req and clothes_req for non-robeless spells to show up but that's not a bug.

**Comment by phil235** [comment]
Is this reproduced or not? Need some instructions on how to reproduce.

**Comment by lordpidey** [comment]
@Cyberboss Being unable t cast as a ghost seems to be intentional.  You can still cast as a corpse.

**Comment by vuonojenmustaturska** [comment]
@KorPhaeron
