### ISSUE TITLE
Can't sac enemy cultists in HoG

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#13033]
Tells you not to sac your friends

**Comment by KorPhaeron** [comment]
@remierichards

**Comment by RemieRichards** [comment]
I dont think that's what this is.
it uses a ```locate()``` to find L, so if you stand on the altar with them it finds you instead.
I'll sort it to be a proper loop, but until then just dont stand on the altar.

**Comment by ChangelingRain** [comment]
hog is gone
