### ISSUE TITLE
Blood drops from a dying body drip in a repeating cycle.

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#13049]
Server: Sybil

Revision: What revision was the server running? 2dd49e518e41924c09fc23ef248b07615447f6ae 

Problem Description: So I was bleeding out and I alt-clicked my corpse and noticed that the drips of blood under me built up from 1 to 2 to 3 like you'd expect, but then after that the floor cleaned itself and started dripping more blood over and over.

What did you expect to happen: I expected the drips to either just stop at 3 or continue onto some higher number and then stop.

What happened instead: Blood just kept cycling through the 4 states.

Why is this bad/What are the consequences: I don't really think this is an important issue but it's just a bit odd.

Steps to reproduce the problem: Crit someone so they bleed, alt click the tile they're under as they bleed out.

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): On Metastation, in maint, after getting beaten by a holoparasite. Probably irrelevant.

**Comment by phil235** [comment]
Intended afaik, the drips merge into a blood stain once you get enough on the same tile. If there's already a blood stain on the tile then the drips are merged into it since we don't stack multiple blood stains on a tile.

**Comment by CosmicScientist** [comment]
@phil235 I think they mean that the last blood stain is removed if it was at its biggest size and is replaced by the smallest blood drip rather than new drips merging into the old stain.

**Comment by newfren** [comment]
No actually there was also a blood stain on the tile that didn't move at all, Just thought the blood drops cycling was weird - makes sense if it's just turning into more blood stain.

**Comment by CosmicScientist** [comment]
Oh okay, my mistake then.

**Comment by phil235** [comment]
Maybe we can try to not create a drip if we detect a blood pool on the tile (just like other blood stains do)
