### ISSUE TITLE
cloner problem

### ISSUE THREAD

**Issue by Gookamungus** [tgstation/tgstation#13079]
possible bug when the power is cut when a pseudo-human is being made in the pod. the console says that the person is still cloning but the pod seems empty after power is restored, possibly preventing another cloning?

**Comment by newfren** [comment]
This doesn't prevent another cloning and is entirely cosmetic - cutting power is how people speed clone, by cutting power as soon as someone starts processing then starting someone else cloning as a friend drags the now in crit person to cryo to heal up the rest of the way.
