### ISSUE TITLE
Crew monitoring console map doesn't work on Asteroid Station

### ISSUE THREAD

**Issue by tkdrg** [tgstation/tgstation#13091]
The coordinates show up fine, but the small squares in the map are in the wrong place. Possibly related with large Z-levels, I didn't investigate very thoroughly.

**Comment by WJohn** [comment]
Scratch that, it's completely broken right now. It's showing birdboat while we're on box, and isn't showing anybody's sensors either.

**Comment by tkdrg** [comment]
The issue with showing different maps can be a cache miss if you're playing on two servers at the same time. If you aren't, though, it's a bug.
@neersighted would know better

**Comment by lzimann** [comment]
Asteroid station is no more.
