### ISSUE TITLE
The number of maps is becoming a maintainabilty issue

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#13132]
> change a single item path
> have to update a dozen maps or more
> merge conflicts forever

Really sad we lost the simple animal bots to this.

We either need to cut it down to focus on a couple core maps or have some kind of priority merging for PRs that touch several maps.

**Comment by tkdrg** [comment]
@KorPhaeron there is a third option. N3X15 over at /vg/ has developed a tool that can automatically repath any maps. If @MrStonedOne was willing to implement that in his bot, then this issue could be neatly solved by just including a repath.txt within the PR, much like we do with changelogs currently.

**Comment by GunHog** [comment]
That is glorious! Port it at once!

**Comment by duncathan** [comment]
Pull the other maps from Travis IMO; make it the mapper's responsibility to update the map

**Comment by MrStonedOne** [comment]
How about we stop treating paths as mutable.

Next time you want to change a path, turn the old path into a spawner for the new path

**Comment by Dorsisdwarf** [comment]
Codebloat I guess MSO

**Comment by duncathan** [comment]
Ah yes, of course, what a great idea. 
I'm sure it absolutely would've been a good idea to make EVERY atmos machinery path into a spawner for the new one when I last repathed them. I'm sure the mappers all would've LOVED how much more difficult I'd have made changing the plumbing.

**Comment by Jordie0608** [comment]
Modifying paths is really easy with notepad++ and doesn't cause merge issues on it's own.

**Comment by Jalleo** [comment]
Could create a simple .bat to work out the path changes and change

**Comment by Strathcona** [comment]
Path swaps aren't very hard to work out. It's the merge conflicts more than anything that's a problem. Also finding whatever the heck the path was supposed to be changed to. Can we get a sticky in the coding forum with changed paths so we can reference that?

**Comment by optimumtact** [comment]
proved to be fine in practice
