### ISSUE TITLE
Advanced Xenobio Camera is Borked

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#13155]
Simply put, it's fairly easy to break the console. I don't have the exact steps to reproduce it, but I attempted to switch camera networks and quit---the icons for the console still stayed up, and any further attempts to interact with the console only generated "this console is already in use!"

There was no way to close the console fully, nor be able to use the console again.

Pretty major, as it impacts player UI and part of how xenobio operates.

**Comment by GunHog** [comment]
Did you screw the screen out, and then back in?

**Comment by Shadowlight213** [comment]
@gunhog I don't think you can deconstruct the console. At least it didn't work when I tried it.

**Comment by bgobandit** [comment]
new shit

"just saying it so you can help others: the console is incapable of manipulating slimes which are currently above monkeys or dead monkeys: I believe its likely related to being unable to grasp dead monkeys, the console likely using some form of the grasp code "
