### ISSUE TITLE
RCD not deconstructing some RCD-created walls.

### ISSUE THREAD

**Issue by Invisty** [tgstation/tgstation#13194]
Ran into this problem last night, I might have to look into it further.

1. Another player makes some RCD walls.
2. I attempt to remove them with my own RCD.
3. It does not respond to clicking on the wall.

Some of the walls, however, could be deconstructed. I checked the RCD material capacity, it was full.

I would expect some sort of in-game error message or progress bar appear when I click on the wall.

**Comment by phil235** [comment]
Cannot reproduce. what kind of RCD did you use? Where was that specific wall exactly? Was there something else on the wall's tile?

**Comment by Invisty** [comment]
I'll experiment some more, see if I can work out what's causing it.

**Comment by Dorsisdwarf** [comment]
@Invisty Any luck? Are you sure the RCD had sufficient matter to decon the wall?

**Comment by optimumtact** [comment]
old with no repro
