### ISSUE TITLE
Stunprods/batons have one less charge than they should

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#13209]
When the charge of your prod is equal or higher to the charge required to stun (IE, a prod needs 2500 units of power to stun and the cell has between 2500 and 5000 units of power left), the next time you stun somebody with it, it will not stun. Instead, it will eat a charge and turn itself off as though it were out of power, and not stun the target.

**Comment by PKPenguin321** [comment]
This line is probably relevant: https://github.com/tgstation/-tg-station/blob/89b6e5d0961a005a587e2f9d987d0c93c96031b0/code/game/objects/items/weapons/stunbaton.dm#L39

**Comment by phil235** [comment]
The bug appeared because I moved the charge deduction in baton_stun() to happen before the actual stun. https://github.com/tgstation/-tg-station/commit/0efb30434a8491d381002f713076f2edf586eb9a#diff-94cf9c598d9000693cd54ff7275f86b5R140

**Comment by PKPenguin321** [comment]
@phil235 it's very nearly been a month, do you want somebody else to take over

**Comment by phil235** [comment]
oh boy, sorry, I had forgotten about it.

**Comment by PKPenguin321** [comment]
what the fuck this bug is too hard phil fix it

**Comment by PKPenguin321** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by Jalleo** [comment]
@phil235 we now got a dupe bug report.
