### ISSUE TITLE
PANDEMIC (machine) can reveal the existence of viro crates

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#13234]
(Sun Head): Hey you can tell if someone orders a virus crate from pandemic if you find toxic filter. It has no name if a crate hasnt been ordered and it has the name Liver Enhancer if one has. Dont know if this is a known bug.

Not sure if this is even worth fixing honestly

**Comment by newfren** [comment]
that's still the wrong format for the PanD.E.M.I.C Kor jesus christ

**Comment by Dorsisdwarf** [comment]
Clearly to solve this, have 1 virus crate start on centcomm roundstart

**Comment by tkdrg** [comment]
A couple easy options:
* Have all the crate diseases be unknown.
* Have all the single symptom diseases start named regardless of crates.

**Comment by Cyberboss** [comment]
Toxic filter don't exist, closable

**Comment by XDTM** [comment]
It does, and it calls it Liver Enhancement regardless of whether a crate has been ordered or not. I think the guy that found this simply removed the sneezing symptom triggering the disease naming.

**Comment by XDTM** [comment]
So, double closable.
