### ISSUE TITLE
Toggling off midround antagonist doesn't seem to work for some midround antags

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#13249]
Such as syndicate borgs, as I got shoved into one of those even with midround antag off.
May need more testing.

**Comment by tkdrg** [comment]
syndieborgs aren't really a midround antag per se, they're a picked ghost antag, "midround antag" usually refers to stuff like revhead scaling or latejoin traitor

**Comment by Anonus** [comment]
They're picked randomly from ghosts midround and they're antags, so they're a midround antag.

**Comment by Xhuis** [comment]
The midround antagonist preference is used for traitors, changelings, etc. from mulligan after some modes end. Syndicate cyborgs were coded before the midround preference was added. This is not a bug.

**Comment by Rinoka** [comment]
doesn't that mean it's a consistency issue, then?

**Comment by Jalleo** [comment]
This issue is non relevant we have the pop ups saying if you want to be this or not now. @Cyberboss
