### ISSUE TITLE
xenobio camera does not function if you are buckeled to chair

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#13255]
Herp derp. makes bumping someone away form the camera easy

**Comment by tkdrg** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
@tkdrg 

@AnturK is the person who could fix this if anyone, he made the advanced consoles

**Comment by tkdrg** [comment]
but you made the xeno thing

**Comment by AnturK** [comment]
That's because relay move things needs actual movement and buckling prevents that. I'll try moving it above the checks later.

**Comment by KorPhaeron** [comment]
@tkdrg 

Barely

**Comment by XDTM** [comment]
Tested, does not prevent movement or actions. Feel free to close.
