### ISSUE TITLE
Lizard Tail renders on the wrong layer/Contains erroneous pixels

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#13286]
![](http://i.imgur.com/dIzweRT.png)

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by RemieRichards** [comment]
That's not the dixel.

**Comment by LanCartwright** [comment]
FIX THIS.

**Comment by RemieRichards** [comment]
On closer inspection, I believe this to not be a bug.

Female uniform cuts 1 pixel out of the groin
+
Lizard Tail is naturally visible from the front (1 pixel)
=
2 pixels showing on the front.

it's due to female uniforms expecting a human body shape, without mutant parts.

**Comment by YotaXP** [comment]
So why is this still open?

**Comment by RemieRichards** [comment]
This is an issue tracker, not a bug tracker, an oversight is still an issue.

**Comment by PKPenguin321** [comment]
dixel 2.0

**Comment by YotaXP** [comment]
Then the issue should be renamed to "female jumpsuits shouldn't ride so high up the crotch".

**Comment by PKPenguin321** [comment]
we may as well just add a kinksuit where the crotch is exposed, because this bug keeps popping up every few weeks anyways :V

**Comment by bgobandit** [comment]
dongerinos

**Comment by duncathan** [comment]
I never thought I'd see the day

**Comment by duncathan** [comment]
Also dear lord
There's TWO dixels on the ligger
Salts-The-Wounds canon

**Comment by Zilenan91** [comment]
Something similar happens on naked male lizards. If you set one up in the character viewer, it looks like they have a penis. I'll update with a screenshot in a bit

**Comment by WJohn** [comment]
That's not a penis, that's the back of their tail, zile. That's completely intended.

**Comment by Bluespace** [comment]
It does look like a tiny lizard dick tho.

**Comment by newfren** [comment]
tiny lizard dicks are intended

**Comment by WJohn** [comment]
This is fixed, I believe.
