### ISSUE TITLE
You can't hear while dead/in your body

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#13306]
Makes it very annoying to wait for cloning or defibbing when you can't hear anything.

**Comment by WJohn** [comment]
Been like this for years, don't know if it's intended or not.

**Comment by newfren** [comment]
I'm pretty sure this happens when you would be deaf from an explosion or a viro disease.

It's the same reason you can still hear the comms channels for whatever you've got in your headset but none of the others while you're in your body, I'd imagine.

**Comment by Jalleo** [comment]
Think this is a dupe

**Comment by Dorsisdwarf** [comment]
Dupe not found

**Comment by Potato-Masher** [comment]
I think this can be closed, last I was on you could hear while in your body.

**Comment by Rinoka** [comment]
agreed

**Comment by PKPenguin321** [comment]
Still occurs if you die while deaf, IE from an explosion. I think the ear damage never wears off because it stops processing when you die

**Comment by Rinoka** [comment]
should probably just dip an unstuck-like command into ghosts for this, if they stop processing like that. might be more convenient than having the risk of an unexpected method fucking up ghost hearing and having it be difficult to fix because of dropped processing
