### ISSUE TITLE
Large grenades aren't handling slime core reactions right

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#13387]
the gimmick with large grenades is that you can put pretty much reagent container in them instead of just beakers. This includes slime cores. With liberal use of plasma beakers and slime cores, you could make exotic grenades that do cool stuff like summon mobs.

Except that stopped working at some point.

I think slime cores with a wind up (" The solution begins to bubble.") are being removed before they can actually release their payload. Though the message "The used slime extract's power is consumed in the reaction." IS shown. 

For example a gold core grenade should summon mobs, but doesn't (unless they're hiding in the grenade).

**Comment by Lumipharon** [comment]
Someone please bring back the old bluespace slime + plasma reaction. Tele nades were the shit.

**Comment by Incoming5643** [comment]
yeah I noticed that too, tried to make one and watched the crystal plop out of the grenade. I couldn't have been sadder about it.
