### ISSUE TITLE
Plasma men bugs

### ISSUE THREAD

**Issue by ATBarza** [tgstation/tgstation#13396]
-Tanks start at release pressure 101, and spawn without internals on

-If you wear the atmos hardsuit and stay on fire for a while you don't get damaged, but when you put your regular helmet afterwards you take burn damage even when you're not on fire

-Going into crit as plasman and then coming out of it, you're stuck with the No O2 sign on your HUD and can't get rid of it

-If your character is set to plasma man and you get chosen for deathsquad, you spawn as a deathsquad plasman and die soon after

**Comment by as334** [comment]
I was told that deathsquad were humans only, I'm not sure about the No 02 sign thing, but i'll look into it. As for the atmos hardsuit stuff, that's because those things have full fire resist, but I think it still raises your temperature? I dunno, I'll take a look at that in a bit.

**Comment by actioninja** [comment]
According to some recent plasmaman players these issues no longer happen.
