### ISSUE TITLE
Instrument BPM (unrelated to #9248)

### ISSUE THREAD

**Issue by TheWiznard** [tgstation/tgstation#13417]
12/3/15
Maybe I just don't understand but for some reason the instrument tuning on each server is different.

on basil you open the piano and I put in one of my midi's (not actual midi, using the converter in the code and copypasta into instrument) and the bpm is locked into increments on like 
600,300,200,150,120,100,85,75,66,60,54,50,46,42,40,37,35,33,31,30 - actually it goes down from 30 to 1 but the lower it goes the longer you have to click to get it  to go down, at like 2 I had to click for like 2 minutes for it to go to 1 
![image](https://cloud.githubusercontent.com/assets/9158683/11563173/2248cb92-9998-11e5-9f16-e269030e754c.png)

on sybil you open the piano and put in a song and it's locked to really bizarre tempos like 909,454,303,227,181,151,129,113,101,90,82 
edit: also 82 was the lowest I could go on sybil bpm wise

On basil songs actually sound like a song instead of a jumbled pile of shit like they do on sybil. I dunno what's going on so I thought I'd make an issue about it.

**Comment by tkdrg** [comment]
This is because the resolution of the tempo timer is related to fps, and basil runs at a slower fps than sybil.

**Comment by MrStonedOne** [comment]
It would seem that this is a bug.

A bug in the bpm selection system.
