### ISSUE TITLE
Highlander mode doesn't check if the person is in a 'safe' area before changing their equipment

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#13410]
I know its a meme admin button but as far as I'm aware all the other force-apparel events (at least wizard ones) has a check to make sure people that are in space aren't immediately fucked by the fact their hardsuit stuff just turned into a pair of kawaii cat ears and a horse mask.

**Comment by Bawhoppen** [comment]
>highlander 

>living
