### ISSUE TITLE
Plasmamen can be Nuke Ops

### ISSUE THREAD

**Issue by Lumbermancer** [tgstation/tgstation#13424]
But they don't get helmet, suit or plasma tank making them explode instantly.

**Comment by tkdrg** [comment]
@as334

**Comment by WJohn** [comment]
I really wish plasmamen would be safe as long as they had a space/biosuit on or something similar. Those things are meant to be airtight, aren't they?

**Comment by Incoming5643** [comment]
Nuke ops don't spawn in their spacesuits all the same, so it'd still be an issue

**Comment by Zilenan91** [comment]
I mean, if we can figure out a way to make it so plasmamen have syndicate-themed plasmaman jumpsuits, I'd absolutely love to see one go ham in the new elite hardsuit we just added.

**Comment by as334** [comment]
I swear to god it worked when I tested it, alright i'll add it to the list.

**Comment by PKPenguin321** [comment]
whitelist nuke ops to humans for the ez fix

**Comment by as334** [comment]
That's actually harder than you'd think. But i think it should be good if i set stuff up to call the pre_equip_job() before putting on the antag equipment

**Comment by Zilenan91** [comment]
Can't you blacklist species with dangerous_existence from Nuke Ops/wizard?

**Comment by as334** [comment]
I did that, but apparently that doesn't work.

**Comment by KorPhaeron** [comment]
This got fixed
