### ISSUE TITLE
You can type in words from verbs separated by spaces to get some sort of incomplete command.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#13431]
![](http://i.imgur.com/XxljE7P.png)
This happens if you type in up, but it also works with top, to, and so on.

**Comment by MrStonedOne** [comment]
byond issue

feature

working as intended (mostly)

What happens is typing any unique word of a verb will work to trigger that verb...

up is triggering the pick up verb.

This is intended functionality.

What isn't, is that that box had the partial verb name as it's title, not the full verb name...

**Comment by WJohn** [comment]
I'm not experiencing this anymore. May be fixed by now with newer byond versions.
