### ISSUE TITLE
Plasmamen can have their DNA modified by the genetics DNA machine, but they will not be affected by the radiation.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#13451]
Kind of a consistency issue as being rad immune should make it so radiation cannot modify your DNA. Also it means that geneticist plasmamen can easily be used as test subjects and never have to worry about stopping to heal or decrease rads.

**Comment by tkdrg** [comment]
@as334

**Comment by as334** [comment]
Hmm, on one hand making it so they can't have disabilities OR superpowers is sorta shit, on the other hand that's really strong for finding genetics shit. I'll ask Sweaterkittens.

**Comment by tkdrg** [comment]
@as334 11 days

**Comment by Shadowlight213** [comment]
@As334 I talked to sweaterkittens. They said to make them unable to get their dna modified at all. No powers or disabilities.
