### ISSUE TITLE
Space vines really should work off a health system

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#13454]
Right now, they get deleted only if the object used to attack them is sharp or an active welding tool, which is pretty unintuitive especially given that some non-sharp objects used to have a chance to kill them, like wirecutters.

**Comment by Zilenan91** [comment]
Wait, killing them is RnG? Then what the fuck are the hardened vines

**Comment by Anonus** [comment]
MORE, SHITTIER RNG
