### ISSUE TITLE
Plasmamen accumulated radiation levels do not decrease over time.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#13450]
Using SE injectors or the DNA console will accumulate radiation, but plasmamen will not be harmed by it, nor suffer any ill effects. Which is obviously intended as they are rad immune. However, the accumulated radiation will never decrease allowing it to reach hundreds of thousands easily.

**Comment by tkdrg** [comment]
@as334

**Comment by as334** [comment]
Is this really a bug? They ignore rads as a whole, so of course it doesn't get metabolized. I don't really see any issue here, unless having the rads that high cause some weird behavior.(Also how the hell is this balance?)

**Comment by Shadowlight213** [comment]
@as334 It can display weird for stuff like the genetics console showing 1000000% rads.
