### ISSUE TITLE
Hand of god cultists don't lose the red/blue god faction when deconverted

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#13468]
I'm not sure if that faction is checked for anything, but it's notable.

**Comment by tkdrg** [comment]
i think only the friendly fire thing from the defense pylons use it, but that's also broken so

**Comment by KorPhaeron** [comment]
@tkdrg 

Someone fixed this

**Comment by Anonus** [comment]
[There IS a line to remove the factions, but that line doesn't work.](https://github.com/tgstation/-tg-station/blob/master/code/game/gamemodes/handofgod/_handofgod.dm#L228)
I don't know WHY it doesn't work, but yeah it doesn't for some reason.
![???????????](http://puu.sh/m2vvy/9e7825a01a.png)

**Comment by duncathan** [comment]
... Is that an associative list?

**Comment by ChangelingRain** [comment]
hog is gone
