### ISSUE TITLE
Plasmamen leak plasma from their internals

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#13461]
Was watching a plasmaman in genetics be put into the scanner. After about 30 seconds I noticed that the tile had the plasma overlay. Afterwards, whenever the plasmaman would stop for a few seconds, they would dump some plasma into the tile.

**Comment by tkdrg** [comment]
@as334

**Comment by Knigga** [comment]
they probably had their internals still set to 101 kPa

**Comment by as334** [comment]
what? Maybe their tank reached the leaking point, but the fact they can get air from the tank into the atmosphere at all makes no sense.

**Comment by Knigga** [comment]
The same thing happens when you use anesthetic in the surgery room. After a while the whole room starts giggling, and that's set to 101 too

**Comment by as334** [comment]
Clearly beyond the scope of plasmamemes then. But i'll take a look into it.

**Comment by Jalleo** [comment]
This is caused by this proc apparently. It would need a rewrite potentially including lungs to manage how this should be done https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/carbon/life.dm#L46

**Comment by kingoftheautism** [comment]
Three years has passed

Maybe somebody will like, ever try to fix that?
