### ISSUE TITLE
There is no indication that the emergency space-suit safe on the pods is unlocked

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#13465]
Normally unlocked safes have a different sprite or description or SOMETHING. The safe looks the same, clicking does nothing, you have to know to drag it to you.

@KorPhaeron

**Comment by KorPhaeron** [comment]
I can't think of a non shitty way to change this. 

>in world loop to find them on alert change

Bad

>process to update icon based on alert level

Bad

>global list of them so alert change can loop through it

Still sounds dumb.

**Comment by duncathan** [comment]
That last one sounds okay. Are safes children of anything that already has a global list?

**Comment by KorPhaeron** [comment]
They're storage items like backpacks,  so I doubt it
