### ISSUE TITLE
Proposal: Make Brain Damage trigger the Unintelligable mutation

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#13497]
You know the mutation Unintelligable that makes whatever you say absolute gibberish?

If we make Brain Damage trigger that mutation, it can be an actual concern, and we can remove the meme stuff from life.dm.

This will improve maintainability of life.dm by a small amount because for fucks sake it does a switch and then picks between 4 lists all defined in the proc itself instead of as globals.

It's a win/win situation. Except for oranges, he might be sad.

I'd do this myself but I'm busy with the Tesla engine project.

**Comment by optimumtact** [comment]
:-1: don't remove harmless fun

**Comment by Iamgoofball** [comment]
It's "harmless fun" that's also shitcode.

**Comment by PKPenguin321** [comment]
>It's "harmless fun" that's also shitcode.

you know what other PR got merged because of this line of thought?
https://github.com/tgstation/-tg-station/pull/8449
never forget

**Comment by Iamgoofball** [comment]
Yeah, that can be readded nowadays as a spell or action button or some shit with the spevies datums.

**Comment by optimumtact** [comment]
make brain damage give you a retardation mutation that makes you spew those messages, use the AI ion law pick from file code to have a file full of memes

shitcode solved as was my plan when aran closed my PR

**Comment by Iamgoofball** [comment]
I guess that'd work. I'll see if I can find anyone willing to do it.

**Comment by optimumtact** [comment]
I will do it

**Comment by Niknakflak** [comment]
Oranges doesn't want this removed because he likes making dumb PRs

**Comment by optimumtact** [comment]
all of these flavours and you choose to be :cry: over some harmless memes?

**Comment by Dorsisdwarf** [comment]
Idee forum.

**Comment by duncathan** [comment]
@Dorsisdwarf
This is a maintainability issue.

**Comment by KorPhaeron** [comment]
goof if you're gonna do it then do it

**Comment by optimumtact** [comment]
I already refactored this a bit
