### ISSUE TITLE
Ghost spawners dont check for any sort of jobban when selecting ghosts.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#13517]
@KorPhaeron What the fuck man.

**Comment by KorPhaeron** [comment]
I didnt code this

**Comment by Shadowlight213** [comment]
@KorPhaeron 
https://github.com/tgstation/-tg-station/pull/12848

>didn't code this.

**Comment by KorPhaeron** [comment]
The wizard thing is not the same kind of object

**Comment by KorPhaeron** [comment]
I can add jobbans to these but they currently exist nowhere ingame

**Comment by Shadowlight213** [comment]
Well technically when they do they won't have jobbans for them. So you'll need to add them at some point in time.

**Comment by tkdrg** [comment]
@AnturK i think

**Comment by Shadowlight213** [comment]
@tkdrg The wizard one is completely different from the one I'm mentioning.

**Comment by Shadowlight213** [comment]
Fixed I think
