### ISSUE TITLE
It's possible for academy wizards to escape the Wizard academy away mission.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#13518]
Be academy wizard
Staff of change other wizard into a borg
Order borg to go mediborg
Have it remove your implant
Use gateway to go to station and go on a murderspree

**Comment by Shadowlight213** [comment]
@anturke

**Comment by Shadowlight213** [comment]
@AnturK

**Comment by Incoming5643** [comment]
I'd just like to point out that there's no staff of change on the away mission, just a wand of change. Meaning there's a very finite chance to manage to turn someone willing to cooperate with you into a borg.

**Comment by coiax** [comment]
Also, we don't have away missions anymore. Do we need this issue still open?

**Comment by Shadowlight213** [comment]
probably not
