### ISSUE TITLE
growing.dmi has hit its icon_state limit

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#13602]
Opening growing.dmi in dreammaker stops halfway through mimana trees. As far as I can tell the two plants added after mimana's, steel-caps and glowcaps, cannot be read in dreammaker at all. Even trying to export the images as a png will not properly display them.

However they WILL still appear properly in the game itself, there's just no easy way to edit them.

The file should be split up into more .dmi's. Growing states for the new plants can be recovered from the growing.dmi's that were included with their pull requests.

**Comment by PKPenguin321** [comment]
splitting it into growing_default.dmi, growing_mutations.dmi might help

or you could do growing_fruits.dmi, growing_vegetables.dmi, growing_mushrooms.dmi, growing_medicinal.dmi, growing_other.dmi if you wanna get precise

**Comment by WJohn** [comment]
Feels kind of nuts to me that we can't have more than 512 sprites in a file. Oh well, that's byond for you.

**Comment by RemieRichards** [comment]
@WJohn false, we can have move than 512 sprites in a file, Byond just won't open the file in IT'S own editor.

**Comment by Core0verload** [comment]
Partially fixed in #15944 - I changed plant icon generation so it would reuse growth/death icons for similar plants, kicking the icons amount way back under the 512 states mark. It's now somewhere around 200 states, and BYOND can add new ones.
