### ISSUE TITLE
People who died to superchilled air couldn't move as ghosts

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#13633]
Multiple people adminhelped that they couldn't move as ghosts after dying to super chilled air.

They could still move around by doubleclicking turfs.

Fuck if I know why

**Comment by optimumtact** [comment]
Temperature affects move delay calculation, so unless the mob move_delay var is unset on ghosting they'll have a massive negative value that will never reach line 150 in mob movement
https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/mob_movement.dm#L150


The mob movement procs could use a max/min sanity check as well
https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/carbon/human/species.dm#L833

This proc could use maximum/minimum slow downs as well to help prevent this sort of thing.

**Comment by Jalleo** [comment]
Ghosts should be affected by thos they have their own movement code unless there is something i dont know.

**Comment by optimumtact** [comment]
the move_delay var on the client will remain set during the ghosting and because it's so high (thanks the to rediculous temperatures) it will never reach line 150 in the client move proc and get reset.

**Comment by MrStonedOne** [comment]
Move this: https://github.com/tgstation/tgstation/blob/master/code/modules/mob/mob_movement.dm#L99

down two if checks.

**Comment by vuonojenmustaturska** [comment]
@KorPhaeron is this still an issue?

**Comment by KorPhaeron** [comment]
Technically yes, but it is unlikely we will ever trigger this bug again
