### ISSUE TITLE
Resisting out of cryo is imposible

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#13646]
because it knocks you out
this can result in a traped forever moment.

**Comment by tkdrg** [comment]
to add, i've seen this happen a few times, and two of those times were when when cryo was hot (not low enough to heal) since you can only resist out when fully healed
one other time it was cold enough but he was at 97 HP and couldn't heal any further, i suspect a rounding error somewhere

**Comment by Incoming5643** [comment]
Anything that does persistent damage, like blood loss, can defeat a cryo and lead to someone getting stuck in there.

Cryos should probably just check to see if a healing attempt has flatlined or allow resisting after some long period of time.

**Comment by WJohn** [comment]
Cryo should frankly just regenerate your blood, because this is kind of awful.

**Comment by Incoming5643** [comment]
Don't quote me on this but if you put O- blood in the beaker it WOULD regenerate your blood.

Also due to shitty cryo mechanics you could give someone a TON of blood even if there were only like 10 units in the cryo beaker.

**Comment by WJohn** [comment]
Then perhaps players simply need to get good? I dunno.

Neat, though.

**Comment by Qbopper** [comment]
@KorPhaeron unless I'm mistaken the changes to cryo make this irrelevant, the cell automatically opens once you reach full health and dumps you out

**Comment by Cyberboss** [comment]
@optimumtact Is this even a bug? Seems like a design issue

**Comment by Qbopper** [comment]
The issue was "you're trapped forever" because it knocked you out and wouldn't open without help, but this isn't a problem anymore
