### ISSUE TITLE
defib ex_act can leave the paddles outside

### ISSUE THREAD

**Issue by tkdrg** [tgstation/tgstation#13654]
Don't know the exact steps to reproduce but this happened on Sybil1 after a syndicate bomb by the bridge in metastation, the NODROP paddles were left in the floor. dunno if the doctor had them out or not, but he probably did

**Comment by swankcookie** [comment]
This might just be a case of misrepresented sprites. Were the paddles under the doctor?  Were they on the same tile as the defib?

**Comment by tkdrg** [comment]
the doctor got gibbed

**Comment by tkdrg** [comment]
i forgot i had this pic
![2015-12-14-151131_1366x768_scrot](https://cloud.githubusercontent.com/assets/6563111/11804920/606aefac-a2e6-11e5-909c-a079ab07a6c6.png)

**Comment by swankcookie** [comment]
Oh fuck that is weird. I'll do some testing later today to find what actually causes this, if no one else get to it.

**Comment by Metacide** [comment]
If it's any help, a few days ago on Sibyl there were some defib paddles in the hands of a corpse I saw. I couldn't remove them, they were "stuck" in their left hand. Not sure how they died, though.

**Comment by ShizCalev** [comment]
Possibly fixed by #28189

**Comment by ShizCalev** [comment]
Looks to be fixed.
