### ISSUE TITLE
Cyborgs are unable to use ladders.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#13670]
As a result, they can't get out of the caves away mission.

**Comment by Anonus** [comment]
A lot of things can't use ladders, and even mechs can't get out of the caves mission because bump teleporters don't work on mechs for some reason????

**Comment by Cebasiz** [comment]
you can actually use the ladders, you just need to click them with a module.

medical cyborgs cannot climb ladders, until they try with a surgical saw.

**Comment by KorPhaeron** [comment]
Borgs dont have hands how can they climb ladders

**Comment by Shapsy** [comment]
Secret jetpacks, they just never got to use them before because there was always a ceiling

**Comment by Firecage** [comment]
@KorPhaeron To be perfectly fair. Borgs can pull objects and people despite lacking hands...And they can open lockers and crates despite lacking hands.

**Comment by Anonmare** [comment]
NECROMANCY

**Comment by Supermichael777** [comment]
shitty impercise Clamps
