### ISSUE TITLE
Container emptying lacks sanity for adjacency

### ISSUE THREAD

**Issue by tkdrg** [tgstation/tgstation#13725]
```
if you drag a container to empty onto a tile while in the cardboard box solid snake box thingie and continue walking it will empty on the tile you initiated it even if you walk to try and break the dump sequence
```

**Comment by xxalpha** [comment]
why did you write this in code format

**Comment by tkdrg** [comment]
coz i copypaste it from ahelp

**Comment by WJohn** [comment]
So I imagine this means some short range item teleportation? Try emptying the contents somewhere, move while in the solid snake box during the process, have the items be dumped where you are?

Sorry, it wasn't very clear with how you wrote it.

**Comment by Jalleo** [comment]
This is due to how closets transfer their contents out I believe.

**Comment by tkdrg** [comment]
WJohnston that's exactly right. Probably just needs an Adjacent() check somewhere.

**Comment by Mervill** [comment]
@optimumtact no longer an issue
