### ISSUE TITLE
Syndie hardsuit problems.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#13731]
1. Elite syndie hardsuits can be removed by outside forces, it's straight up lying according to the uplink description "When the built in helmet is deployed your identity will be protected, even in death, as the suit cannot be removed by outside forces."
2. The elite hardsuit costs as much as a regular hardsuit, 8 TC. Why???
3. We have both a shielded hardsuit AND an elite hardsuit, but the shielded hardsuit is strictly better because it can protect you from tasers. The shielded hardsuits' shield should be moved into the elite hardsuit to make it a real considerable upgrade.
4. The shielded hardsuit does not block melee at all, even though with stunbatons it says it does (and the shield still breaks after 3 hits). It will also prevent the stun baton's melee damage up until that point, but you're still stunned so who cares. It will also not protect you from things like energy swords at all, the shield won't even acknowledge it and the hit will go right through.

**Comment by Dorsisdwarf** [comment]
WHEN did nuke ops get shielded hardsuits?

They were supposed to be a badmin item!

**Comment by KorPhaeron** [comment]
>The elite hardsuit costs as much as a regular hardsuit, 8 TC. Why???

The blood red hardsuit is in the uplink for the benefit of traitors, as nuke ops get them for free.

https://github.com/tgstation/-tg-station/pull/8639 Incoming forgot to restrict them from nuke.

>shielded hardsuit is strictly better

It also costs more than 3 times as much, so yes I would hope its better

>Wrong uplink section

My bad

>Doesn't block melee at all

It does, but stun batons ignore shields/armour as they always have since the dawn of time. The afterattack code does not give a single shit if you actually hit them or not.

> It will also not protect you from things like energy swords at all, the shield won't even acknowledge it and the hit will go right through.

Because e-swords are NOSHIELD, this is intended

**Comment by WJohn** [comment]
Shouldn't we merge the elite hardsuit and the shielded hardsuit? It seems weird you'd have a hardsuit that has better general protection, but another one which protects you from getting stunned. Why not just merge both properties if you're going to have to spend 30 TC on it?

**Comment by KorPhaeron** [comment]
I don't like the black hardsuit sprites mostly

**Comment by Repukan** [comment]
@Cyberboss I think Kor explained it well, not an issue, can be closed I guess?
