### ISSUE TITLE
Orbiting nothingness and other abstract concepts.

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#13745]
Not a big deal but interesting: If you doubleclick on the blank space outside the map, it reports "Now orbiting ." You don't actually start orbiting however.

**Comment by Incoming5643** [comment]
Ghosts can attempt to orbit ghost UI buttons

"Now orbiting Orbit."

**Comment by Cebasiz** [comment]
requesting not a bug tag

**Comment by Mervill** [comment]
@optimumtact closeable, not a bug.

**Comment by Incoming5643** [comment]
(this is still a bug)

**Comment by karlnp** [comment]
Don't make us tap the label.

**Comment by optimumtact** [comment]
This is a bug, it shouldn't be registering clicks on random items like that.
