### ISSUE TITLE
Simple Mobs have no regards for self-preservation. 

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#13755]
Recent additions of such /FUN/ things like lava turfs make it all-apparent that simple mobs simply do not give a shit about the fact they've just walked into a giant pit of death, usually making them a null threat around any environmental hazards.

Maybe some sort of variable that can be set so mobs will see certain turfs as 'dense' so they'll pathfind around it instead of deciding the path straight through a giant lava lake is the best method to getting to their target?

**Comment by WJohn** [comment]
Simple animals are dumb, you know.

**Comment by MMMiracles** [comment]
Its kinda silly when the mob that represents an operative will run head-first through lava to get to where it needs to go, though.

Unless theres some unspoken commentary that about the syndicate in that regard.

**Comment by Iamgoofball** [comment]
we should really upgrade SNPC ai with more modules and make syndicate mobs SNPCs

**Comment by Iamgoofball** [comment]
although we should also teach any AI pathing to avoid lava

**Comment by KorPhaeron** [comment]
Same issue with space

**Comment by Incoming5643** [comment]
Spiders in particular are great at breaking windows that lead to space, then asphyxiating to death. Dummies.

**Comment by Firecage** [comment]
Goof, well, fuck SNPC until they are fixed. Why would you want to add more modules and stuff to something which is broken and 100% unused due to being hilariously broken.
