### ISSUE TITLE
Reattach tail surgery can delete tails

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#13767]
Basically, I first used the severe tail surgery to remove a lizardmans tail. Then when I re-attached it with the reattachment surgery....nothing. The tail was deleted.

**Comment by tkdrg** [comment]
@bgobandit

**Comment by Xhuis** [comment]
No great loss tbh.

**Comment by duncathan** [comment]
Feature

**Comment by bgobandit** [comment]
gonna need more details m8
