### ISSUE TITLE
New orbit() occasionally fall behind fast moving targets

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#13784]
loving the new orbit, but on people/item moving at the speed cap occasionally can move a tile before the ghost's loc can catch up. The ghost WILL catch up, but it just makes the movement stutter a bit for the ghost. If there's a way to compare the ghost's loc to the targets loc a bit more often without raising other costs, that'd probably be for the best.

**Comment by RemieRichards** [comment]
could lower the 0.6 sleep to 0.3 I suppose.

**Comment by MrStonedOne** [comment]
I will note, that if a ghost orbits an orbiting ghost, there is this lag...

But i've been able to orbit a thrown object and not see any lag...

Are you sure that isn't what you were seeing @Incoming5643

**Comment by RemieRichards** [comment]
so this "lag" (please can we not use the term lag here, it worries me, can we use "follow delay") only occurs with orbiting something that is orbiting? that's a REALLY odd case.

**Comment by duncathan** [comment]
Well definitionally it is lag but yeah lag has a different connotation to what's intended here

**Comment by MrStonedOne** [comment]
oh wait, no it happens normally too, but it's not always noticeable...

I think it's partly a side effect of the new fps.

Before the move cap was 11 tiles a second, now it's 16 tiles a second.

**Comment by RemieRichards** [comment]
leave lag for performance, use "delay" for non-performance related lag PLEASE.
my poor sanity.

@MrStonedOne so it's your fault? (this might still be fixed by lowering the 0.6 delay, which was actually only required for old animate, new animate *shouldn't* need it, or it can atleast use a lower delay)

**Comment by MrStonedOne** [comment]
it would seem like, blame mso tag pls.

and ya, because this is now purely client side handled, even the looping part, we can lower that delay.

Maybe have it be a multiple of world.tick_lag, say world.tick_lag * 3

**Comment by MrStonedOne** [comment]
Actually, hmmmmmm

I'm not sure anymore, sleep is 0.6, but 0.6 is still lower than world.tick_lag, even on the higher fps

**Comment by Incoming5643** [comment]
The orbiting is client sided but the ghost keeping loc with the target atom isn't.

**Comment by MrStonedOne** [comment]
I don't think this is actually resolvable since we already sleep for less then world.tick_lag.

**Comment by MrStonedOne** [comment]
incoming i know, what i meant is that because we moved the generation of the orbit to be 100% client side by only generating the transforms once, and only sending the animate() once, the orbit loop is doing less, so we could lower that sleep.

**Comment by RemieRichards** [comment]
MSO showed me this on Sibyl.
the delay is smooth, and doesn't actually look that bad.

**Comment by MrStonedOne** [comment]
@optimumtact this can be closed, fixed in #20632

**Comment by ChangelingRain** [comment]
Uh, it's definitely not fixed even with that.

**Comment by Incoming5643** [comment]
Often this occurs when you're orbiting another observer who is themselves orbiting something, it creates a daisy chain effect.
