### ISSUE TITLE
The DM files often have duplicated or unhelpful names

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#13832]
Guns folder is the worst example, where there is energy.dm for energy guns as well as energy.dm for projectiles as well as energy.dm for casings. There is also fourth energy dm elsewhere in the code. Same shit for projectile.dm.

I request that someone

A) Tell me how to change a dm files name without ruining the file history

B) Make it a code standard that you name your file something helpful/not duplicated (for example, larva_powers, slime_powers, handofgod_powers instead of multiple powers.dm, or the dozen life.dm and death.dm files we have)

**Comment by ike709** [comment]
You've just pointed out the number one reason why I don't ever attempt to code anything anymore.

**Comment by Jordie0608** [comment]
Well I see the issue here, but so what?

**Comment by duncathan** [comment]
@Firecage
Ayy bb I got a job for you

**Comment by MrStonedOne** [comment]
kor, use git mv to rename the files. preserves history.
