### ISSUE TITLE
Bluespace capsules break shuttles

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#13842]
Since they create a new area, the shuttle will have a big capsule house shaped hole in it when it moves

I guess you could argue FEATURE since you're making a fucking house in the shuttle but its kind of wonky and unbalanced.

**Comment by WJohn** [comment]
Maybe it should only replace specific area types? Like asteroid and space and whatever, otherwise it should use the area it's on.

**Comment by KazeEspada** [comment]
Its a feature to sabotage shuttles. But I put a check in so that you don't fuck your own shuttle.

**Comment by phil235** [comment]
This is still happening...

**Comment by tkdrg** [comment]
With the escape shuttle? Weird. @KorPhaeron

**Comment by KorPhaeron** [comment]
@tkdrg

I will look at it when I am next home (not sure exactly when)

**Comment by coiax** [comment]
@KorPhaeron this was fixed when they refused to deploy on shuttles

**Comment by Mervill** [comment]
@WJohn closeable, bluespace capsules now refuse to deploy on shuttles
