### ISSUE TITLE
Wizard round fails to mulligan but doesn't end upon wizard's death.

### ISSUE THREAD

**Issue by phil235** [tgstation/tgstation#13924]
Happened on Sybil just now.
Wizard died at the 23min mark, admin log stated "Convert_roundtype failed due to too many dead people. Limit is 70% living crew", and yet the round continued with no further admin log message about mulligan. Pretty sure this shouldn't happen with wizard as it has round_ends_with_antag_death = 1. I was the only admin observing so I doubt someone changed mulligan options to continue the round.

In the end the round ended properly by shuttle call.

Wizard used a necrostone, scrying orb, fireball spell, staffs of death, chaos and healing (among other things).

**Comment by Incoming5643** [comment]
A mulligan bug? I thought the nightmare was over.

**Comment by Incoming5643** [comment]
Some questions anyway:

Are you sure this was wizard mode? A wizard spawned into extended would provoke this sort of thing, but wouldn't natively end the round on death.

Did anyone else become an antag at the EXACT MOMENT the wizard died?

**Comment by phil235** [comment]
@Incoming5643 
The wizard had two skeleton legionnaires and a xeno (skeleton transformed with staff of chaos) with him and all four got gibbed by a TTV bomb at the same time. I don't know if he used the staff of chaos on someone else though.

**Comment by LatD** [comment]
The exact spells were necro stone, magic missile, wand belt, staff of healing and scrying orb if that is needed for anything.

**Comment by Jalleo** [comment]
We need stats of how many live people there was and etc etc. We should have that info logged when mulligan fails to make sure tbh.

**Comment by Dorsisdwarf** [comment]
I think this issue's been made irrelevant by changes to mulligan in the last 4 years
