### ISSUE TITLE
arrests can be set from examine if opened before ID being removed

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#13934]
OOC: M00nm4nhere: Officers can still set people to arrest without their ID as long as they examined someone prior to being mugged
OOC:  Bawhoppennn: make an issue report for it 
OOC: M00nm4nhere: lol no forums are for fags
OOC:  Bawhoppennn: just do it even if there is probably one already, the maintainers will check for dupes
OOC: Saegrimr: Github, not the forums.
OOC:  Bawhoppennn: >forums
OOC: M00nm4nhere: oh, that's even worse

:laughing:

**Comment by PKPenguin321** [comment]
fuckin moonman talking shit

**Comment by swankcookie** [comment]
"no thanks, I'd rather just bitch about it"

**Comment by duncathan** [comment]
Lol what a loser
Thanks baw

**Comment by Bawhoppen** [comment]
no worries I am nothing if not an ethical man

**Comment by ShizCalev** [comment]
this is fixed.
