### ISSUE TITLE
EMPs can lock up processing

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#13968]
Simply put, because of sleeps:

https://github.com/tgstation/-tg-station/blob/da0ba3659f3f83bfbc6c0e28c378a0728caa2cc6/code/game/machinery/doors/door.dm#L140

this calls open() on doors, which have a sleep: https://github.com/tgstation/-tg-station/blob/da0ba3659f3f83bfbc6c0e28c378a0728caa2cc6/code/game/machinery/doors/door.dm#L185

it's only a total sleep of 1 second, but that's still one second of delayed processing---this could be particularly problematic during mass EMP events like the singularity, telsa release, etc.

I believe adding a spawn(0) then having open() would solve this problem; generally lots of spawning isn't a good thing (as evidence by the "fix" to lopsided explosions), but in this case, I believe it's applicable.

**Comment by MrStonedOne** [comment]
No spawns need, this is NOT a bug.

#13479 made it so that sleeping in the MC is allowed now, Spawns have a lot of overhead, set waitfor = 0 does not.

**Comment by optimumtact** [comment]
this will delay the process of the thing causing the emp's will it not? so it's still an issue in that sense

**Comment by Fox-McCloud** [comment]
@optimumtact 

Correct; anything that called emp_act() on things directly (There's...a surprisingly lot of this) and emp grenades would not finish doing their thing for a while under a few circumstances.

For example, back when turret's had a sleep(rand(60,600) in them, an EMP grenade would go off and keep on repeatedly going off (and the grenade wouldn't delete either) until that finished. 

While this would be *very* small of a delay with doors (even more so when you consider that it's only a probaiblity for EMPs to open doors), it's still going to be problematic in some cases.

**Comment by MrStonedOne** [comment]
Add set waitfor = 0 to the base of emp_act()

**Comment by optimumtact** [comment]
hmm, I wonder, does that work if the ..() call is after the code being run?

**Comment by MrStonedOne** [comment]
it works even if ..() is never ran.

It applies to the proc and all child procs, its a proc meta value, not a code, so it's compile time.

**Comment by optimumtact** [comment]
neat

**Comment by MrStonedOne** [comment]
I was gonna do a run thru and set waitfor ALL the things that have the no sleep issue, (fire_act being a big one)

**Comment by Fox-McCloud** [comment]
I can't seem to dig up *any* documentation on waitfor---what is it, exactly?

**Comment by MrStonedOne** [comment]
kek, there is none.

basically, it means that if a proc or child proc sleeps, the waitfor = 0 proc will return ., then act as if it was spawn()ed from that point on.

its like spawn()ing the entire proc, but with less overhead, and it even ensures processing order when used on a proc called in a loop (spawn doesn't always do this)

**Comment by MrStonedOne** [comment]
It used to be that set waitfor = 0 was the default, sleeping would return, always. 

if you wanted to get current behavior (sleeping held up the entire stack) you did set waitfor = 1

in byond 225 they changed this, and added spawn(), saying it would replace most cases of waitfor.

http://web.archive.org/web/20060722121013/http://developer.byond.com/docs/notes/225.html

**Comment by MrStonedOne** [comment]
Certain internal byond procs, like Enter(), Exit(), New(), Del(), Move() etc use this same thing to make it `return .` if you sleep

**Comment by MrStonedOne** [comment]
to explain how it works with nested calls (because how this works is what makes or breaks it's viability)

````python
/mob/proc
  proc1()
    world << "proc1-1"
    proc2()
    world << "proc1-2"
  proc2()
    set waitfor = 0
    world << "proc2-1"
    proc3()
    world << "proc2-2"
  proc3()
    world << "proc3-1"
    sleep(10)
    world << "proc3-2"
````

the output will be

proc1-1
proc2-1
proc3-1
proc1-2

*10 seconds pass*

proc3-2
proc2-2

**Comment by Fox-McCloud** [comment]
Alright; that was a concern of mine that I had as in door/proc/close() it sleeps for 5 deciseconds, does a little thing, then sleeps for 5 more deciseconds and does more stuff.

So with set waitfor = 1 set on the base emp_act(), you're saying that if it proc'd on a door successfully, it would call close() on that door, then: https://github.com/tgstation/-tg-station/blob/da0ba3659f3f83bfbc6c0e28c378a0728caa2cc6/code/game/machinery/doors/door.dm#L209

when it encountered the first sleep(5), it would spawn off the density, then encounter the second sleep(5) and spawn off the icon updates, operating status and the likes---only with less overhead than actual spawn(0)?

**Comment by MrStonedOne** [comment]
More like once it encounters the first sleep, it spawns off emp_act() in what ever called it. and returns to processing *that* proc.

Notice how after 3-1, the next call is 1-2 and not 2-2 or 3-2.

so if emp_act was called by the singulo in a loop, it would go back to the singulo's loop, and call emp_act on the next thing.

**Comment by MrStonedOne** [comment]
re: your edit:

I'll take a look at it and tell you if that will cause any issues with returns after work

**Comment by rev-benji** [comment]
Is this why the tesla is still kinda laggy?

**Comment by securitycopper** [comment]
Based on how EMPS work, why do the doors open in the first place?  The opening of the door and shocking may be more for effect rather then realistic. I don't remember, is sleep(#) in ms or seconds?

**Comment by duncathan** [comment]
knowing byond it's probably ds

**Comment by Fox-McCloud** [comment]
sleep is in deciseconds, as @duncathan stated. 

This is even worse, on Bay, where doors are technically a part of machine processing.
