### ISSUE TITLE
Orbiting (AI eye)

### ISSUE THREAD

**Issue by Zalewyr** [tgstation/tgstation#13967]
One orbiting the AI eye, it removed the HUD for orbiting, returning to corpse, etc. even when orbiting ceased.

**Comment by Bawhoppen** [comment]
orbiting AI is the scrub way though tbh
you orbit the AI core and then observe the AI eye

**Comment by bgobandit** [comment]
@WJohn (or anyone else) this appears to be fixed, or at least I cannot reproduce it

**Comment by XDTM** [comment]
cannot reproduce
