### ISSUE TITLE
Turrets icons

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#13976]
With porta turrets, if you change the weapon path from /obj/item/weapon/gun/energy/gun/turret to /obj/item/weapon/gun/energy/gun You can get it to toggle between disabler and laser functions. However, if you then mess with the turret controls, set it to lethal, then back to disable, the turrets will continue to look as though they are on kill mode (yellow/orange colors).

**Comment by KazeEspada** [comment]
Is this a bug about var-editing?

**Comment by WJohn** [comment]
It happened while var editing in the map maker, yes.

Also, turret icons are invisible in the map maker because they are using outdated icon states. At least this doesn't affect things in game.
