### ISSUE TITLE
Hardsuit continues to appear in your hand long after it has left your possesion.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/tgstation#14033]
If you go into crit while wearing the atmospheric hardsuit, you will always know when the hardsuit is picked up because its icon will appear in your hand any time someone picks it up. This continues for the rest of game, beyond even dieing.

**Comment by tkdrg** [comment]
I had this with a sec hardsuit earlier today as well, didn't realize that it was a bug, though I was just hallucinating.

**Comment by Mervill** [comment]
@optimumtact no longer an issue
