### ISSUE TITLE
Issues with ore redemption machine and losing power

### ISSUE THREAD

**Issue by tkdrg** [tgstation/tgstation#14086]
You sometimes cannot deconstruct the ore redemption machine if the power is offline. Power sink in this case, and reproduced by turning the APC off manually, but when I tried setting stat to 2 manually in the thunderdome, it worked fine. Dunno what's up here. The screwdriver just didn't give any message. Furthermore, if it loses power with the panel unscrewed, it gets the "unpowered" sprite but with the panel closed. Not sure of the actual status of the panel however.

Thanks a lot to Polyp on Sybil for reporting and testing this.

**Comment by bgobandit** [comment]
related https://github.com/tgstation/-tg-station/issues/12525

the sprite is my fault
