### ISSUE TITLE
Click + Dragging from a container to a tray doesn't update the tray's appearance.

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#14176]
Steps to reproduce: Get a bunch of tools in a toolbox. Drag all the tools onto a tray. Tray stays with the same icon. Take a tool off the tray and all the tools magically appear on the icon.

Fairly minor but annoying!

**Comment by KazeEspada** [comment]
Kitchen trays are trash that need to be removed.

**Comment by newfren** [comment]
No don't remove them they're like 8 free toolbelts the chef starts with.

**Comment by lzimann** [comment]
apparently already fixed according to @Firecage

**Comment by Firecage** [comment]
Indeed. tested it, and the items from a storage container correctly appeared on the tray. It may already have been fixed in the almost 2 years since issue was made.
