### ISSUE TITLE
The Wizard Defender can throw simple mob wizards through the gateway

### ISSUE THREAD

**Issue by tkdrg** [tgstation/tgstation#14202]
@AnturK fix please

**Comment by LanCartwright** [comment]
my fault

**Comment by Zilenan91** [comment]
Please keep this this is hilarious

**Comment by LanCartwright** [comment]
those wizard NPCs shoot fireballs

there's a good 10+ wizards.

yeah lets just say thats a bad idea

**Comment by Zilenan91** [comment]
They end up teleporting into maint most of the time, and the people they kill ARE on station so it's very likely they'll get popped into medbay after the mobs die.

**Comment by LanCartwright** [comment]
They're very, very accurate with the fireball and MM which I've noticed.

None the less, I think this should be fixed. The academy is one away mission I refuse to complete.

**Comment by ChangelingRain** [comment]
let's just pretend away missions are gone

**Comment by kevinz000** [comment]
Ill fix this later.
