### ISSUE TITLE
Mjollnir can turn to shreds

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/tgstation#14214]

**Comment by KorPhaeron** [comment]
Like you got bombed or you dropped it in lava or what?

**Comment by LanCartwright** [comment]
landmine

Should be a bug because you can't welderbomb wizards and wolol their robes, you shouldn't be able to use the equivalent of a welderbomb on a hammer and wolol it away.

**Comment by KorPhaeron** [comment]
Well I don't really feel like adding a BOMBPROOF flag to items, but that'd be required if you wanted this to work

**Comment by LanCartwright** [comment]
Someone added unacidable to all the wizard stuff, so why not bombproof?

**Comment by KorPhaeron** [comment]
I mean a bombproof/shredproof flag doesn't exist and I don't want to create one for just one item

**Comment by LanCartwright** [comment]
Well, you wouldn't have to do so for one item. A good majority of items should be covered under this tag, too.
