### ISSUE TITLE
Field generators sometimes don't form a field

### ISSUE THREAD

**Issue by tkdrg** [tgstation/tgstation#14255]
One of the fields connecting two gens is simply missing. I have the complete singulo logs of the person who set it up, so that might help with reproducing. Proccalling start_fields() on one of the affected gens fixed it. My guess is that the connection from the southeast field didn't force an update between the middle left and top left field gens for some reason. Also note that the code in question is extremely low quality and chock full of extraneous sleep()s and spawn()s.

Singulo setup logs:

```
17:58:02 [0x200555a] (109,65,1) || Field Generator activated by *snip*.
17:58:04 [0x200555b] (114,65,1) || Field Generator activated by *snip*.
17:58:06 [0x200555c] (117,65,1) || Field Generator activated by *snip*.
17:58:10 [0x200555f] (122,65,1) || Emitter turned on by *snip*
17:58:11 [0x200555f] (122,65,1) || Emitter regained power and turned on
17:58:15 [0x20052c2] (117,60,1) || Field Generator activated by *snip*.
17:58:18 [0x2005197] (117,57,1) || Field Generator activated by *snip*.
17:58:20 [0x200519a] (122,57,1) || Emitter turned on by *snip*
17:58:21 [0x200519a] (122,57,1) || Emitter regained power and turned on
17:58:32 [0x200555b] (114,65,1) || Field Generator ran out of power and deactivated
17:58:36 [0x200555a] (109,65,1) || Field Generator ran out of power and deactivated
17:58:37 [0x2005196] (112,57,1) || Field Generator activated by *snip*.
17:58:39 [0x2005195] (109,57,1) || Field Generator activated by *snip*.
17:58:41 [0x200518b] (104,57,1) || Emitter turned on by *snip*
17:58:42 [0x200518b] (104,57,1) || Emitter regained power and turned on
17:58:47 [0x20053e1] (109,62,1) || Field Generator activated by *snip*.
17:58:49 [0x2005550] (104,65,1) || Emitter turned on by *snip*
17:58:51 [0x2005550] (104,65,1) || Emitter regained power and turned on
17:58:51 [0x200555a] (109,65,1) || Field Generator activated by *snip*.
17:58:53 [0x200555b] (114,65,1) || Field Generator activated by *snip*.
```

**Comment by phil235** [comment]
Maybe some dense object was blocking the way right as the field was supposed to start? Like the tesla coils, which start unanchored. All it would take is a clumsy engineer pushing the coil between two field generators.

**Comment by tkdrg** [comment]
I didn't get to watch him set it up, so I can't be sure since that isn't logged.

**Comment by Jalleo** [comment]
@tkdrg add some logging for failure of field generator setup so we can properly investigate next time this occurs.
Until then we should put a need reproducing tag

**Comment by bgobandit** [comment]
this is still happening

**Comment by Bawhoppen** [comment]
Still happening.
