### ISSUE TITLE
Spider bites don't respect shields/blocking

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#14299]
Poison is always injected even when blocked by shields/swords.

**Comment by phil235** [comment]
Relevant code: https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/simple_animal/hostile/giant_spider.dm#L11

**Comment by Thunder12345** [comment]
Not sure how to fix, but the problem is it injects the poison without checking if the attack was blocked. This affects any sort of special addon to just damage from an attack, like carp stamina damage.
