### ISSUE TITLE
Cultists are listed multiple times in the end round report

### ISSUE THREAD

**Issue by imtakingabreakdontatme** [tgstation/tgstation#14290]
Whoisthere was Shade of Patrick Rowley the Shade and had their body destroyed
Whoisthere was Juggernaut (800) the Juggernaut and survived
Pikminpicker was Shade of Meloni Mayse the Shade and had their body destroyed
Pikminpicker was Juggernaut (94) the Juggernaut and survived

Basically if you soulstone a cultist it doubles them, and if you then make them a construct it lists them a third time.

**Comment by tkdrg** [comment]
Yes, that's because each body is a different cultist code-wise, and the report lists all cultists. This is an oooold bug but I think it is datum antags material @Incoming5643

**Comment by ChangelingRain** [comment]
the construct multiplying is fixed because for some reason they had multiple minds???
but any other multiple-mind things will still cause this, ie; dying, then becoming a shade via popup
however it's not really fixable in a practical manner SO

**Comment by ShizCalev** [comment]
still an issue?
