### ISSUE TITLE
Simple animals runtime

### ISSUE THREAD

**Issue by xxalpha** [tgstation/tgstation#14300]
Attacking a cockroach or a mouse causes a runtime. Seems like it is trying to log after the simple animal is killed and deleted, doesn't happen with Poly because it isn't deleted when killed.

`runtime error: Cannot read null.x
proc name: add logs (/proc/add_logs)
  source file: mobs.dm,131
  usr: Emma Burkett (/mob/living/carbon/human)
  src: null
  usr.loc: the plating (115,69,1) (/turf/simulated/floor/plating)
  call stack:
add logs(Emma Burkett (/mob/living/carbon/human), null, "attacked", "wrench", "(INTENT: HELP) (DAMTYPE: BRUTE...")
the wrench (/obj/item/weapon/wrench): attack(null, Emma Burkett (/mob/living/carbon/human), null)`

**Comment by tkdrg** [comment]
@KorPhaeron

**Comment by AnturK** [comment]
I got a generic fix for this in #14201

**Comment by Iamgoofball** [comment]
#14300

**Comment by Mervill** [comment]
@optimumtact closeable, fixed by https://github.com/tgstation/tgstation/pull/14793 (see https://github.com/tgstation/tgstation/pull/14201#issuecomment-174248638)

**Comment by xxalpha** [comment]
What, how, @optimumtact my PR didn't fix this.
