### ISSUE TITLE
You can get two refs to the same atmos tank nozzle in both your hands by spam clicking

### ISSUE THREAD

**Issue by tkdrg** [tgstation/tgstation#14317]
Some guy spamclicked his action button on sybil and got two refs to the same nozzle on both hands. Then he reintroduced one of them into the tank and could even drop it, but he couldn't put the other one back inside. My VV proved that it was the same obj, just referenced twice.

**Comment by KorPhaeron** [comment]
Could not reproduce this

**Comment by duncathan** [comment]
I watched it happen

**Comment by duncathan** [comment]
It may have been facilitated by the immense lag at the time

**Comment by KorPhaeron** [comment]
Yeah I saw it happen as well, couldnt get it to happen under normal circumstances though

**Comment by kevinz000** [comment]
I /was/ pretty sure this was fixed, but I saw it happen a week ago, wtf?

**Comment by bgobandit** [comment]
this seems related to the click dupe bug

**Comment by ShizCalev** [comment]
#26980 might have fixed this.

**Comment by AnturK** [comment]
Can't really say for sure this is the same problem because tank/nozzle code is pretty bad so might be something else.

**Comment by ShizCalev** [comment]
Will close in a week if nobody reports it still happening.
