### ISSUE TITLE
Reinforcing the detective's revolver doesn't have a progress bar

### ISSUE THREAD

**Issue by lzimann** [tgstation/tgstation#14318]
Just a small consistancy issue I guess, when you start reinforcing the detective's gun, with a screwdriver to fire .357 rounds, it doesn't have a progress bar, even though it takes a while to do.

**Comment by KorPhaeron** [comment]
Tested this. It has a bar if you reinforce it on the ground, but not if you reinforce it while holding it

**Comment by optimumtact** [comment]
None of the inhand stuff has progress bars I imagine

**Comment by swankcookie** [comment]
^ I believe this is true

**Comment by KorPhaeron** [comment]
@iamgoofball

**Comment by Iamgoofball** [comment]
@MrStonedOne rewrote it all, bug him

**Comment by lzimann** [comment]
They actually DO have progress bar but it's below the swap hands/equip button.

**Comment by Mervill** [comment]
@optimumtact closeable, no longer an issue
