### ISSUE TITLE
Runtime with antag huds when autocloning a gibbed antag

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#14312]
runtime error: Cannot read null.type
proc name: leave hud (/datum/atom_hud/antag/proc/leave_hud)
  source file: antag_hud.dm,15
  usr: null
  src: /datum/atom_hud/antag (/datum/atom_hud/antag)
  call stack:
/datum/atom_hud/antag (/datum/atom_hud/antag): leave hud(null)
Cy Pershing (/datum/mind): leave all huds()
Cy Pershing (/datum/mind): transfer to(Sheri Zaun (/mob/living/carbon/human))
the cloning pod (/obj/machinery/clonepod): growclone("shadowlight213", "Cy Pershing"

leave_hud uses the "current" var in the mind, which references the body it is attached to. If the body is gibbed, the var is null.

**Comment by KorPhaeron** [comment]
Didnt you fix this?

**Comment by Shadowlight213** [comment]
@KorPhaeron nope. This involves Hud code which I did not touch as I didn't quite understand it.

**Comment by SpaceManiac** [comment]
@Cyberboss Cannot reproduce. Cursory examination of the code looks like it doesn't check mind.current anymore.
