### ISSUE TITLE
Stat tracking is completely unmaintainable 

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#14326]
Still hosted by erro, nobody is quite sure how it works, can't add new stuff to it, Cheridan still has to manually update it.

Stat tracking is the only thing that injects the barr minimum of objectivety and rationality into balance shouting matches, it really needs to be overhauled badly.

**Comment by MrStonedOne** [comment]
the data we still have, we just have no way to actually use it.

I've given example copies of that database out, but its not EASY to actually do it.

Each stat that it actually displays is about 30 to 90 actual lines of parsing/math code.

**Comment by tedward1337** [comment]
What is this even referencing too

**Comment by tkdrg** [comment]
http://ss13.eu/tgdb/tg/latest_stats.html

**Comment by Iamgoofball** [comment]
Erro is still active and helping maintain this, hell, I added tracking for like 50 different things a few months back and he got it all implemented.

**Comment by Dorsisdwarf** [comment]
If Error is still maintaining it, and goofball knows how it works well enough to add tings to it.... then is it really brokeN?

**Comment by tkdrg** [comment]
Goof didn't do shit db wise, erro did
the issue here is we're relying on erro as our single point of failure for this, which as history has proven isn't really the best idea

**Comment by Iamgoofball** [comment]
@tkdrg I can do the codeside changes to make things track in the DB, however.
