### ISSUE TITLE
Solo Blob mulligan failed

### ISSUE THREAD

**Issue by yackemflam** [tgstation/tgstation#14338]
I was a solo blob. After my cores death the game failed to mulligan.

**Comment by swankcookie** [comment]
How'd your core get destroyed?  Anything unusual? What server?

**Comment by Incoming5643** [comment]
Did you confirm with any admins on station that they didn't override the mulligan?
Were there any other antagonists in the round end report?
Was the shuttle already at/near the station when you were killed?

**Comment by yackemflam** [comment]
Admins admitted that the mulligan failed.
No other antags.
Shuttle was not called/docked because it was too early in the round.
