### ISSUE TITLE
Weird white bar: ui bug

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#14344]
uhhh
played a round latejoin sec nothing to unusual for a mid gang round(by which i mean holed up in the armory untill i ded became a ghost then a drone then a ghost) next round  became ai and was greeted with this which lasted the whole round and into the next when I re-logged removing it.
![blue-square on white bar extending right over the bottom of the verb window](http://i.imgur.com/DbrKDYS.png?1)
if its not clear that white rectangle with the blue square extends to the right to the edge of the window.
I have no idea what caused it but re-logging fixed it
server was Sybille around 11:00 on the second of January
bug persisted across rounds. thankfully it didn't take up area i needed to AI

**Comment by neersighted** [comment]
@YotaXP saw this before, we're pretty sure it is a tooltip bug

**Comment by YotaXP** [comment]
When I saw it, it was in the top-left corner of the map.  Inset a little.

**Comment by Supermichael777** [comment]
-\_('w')_/-
