### ISSUE TITLE
Multiverse ID Card deletes your PDA if it's in your ID slot.

### ISSUE THREAD

**Issue by MightyRadcon** [tgstation/tgstation#14365]
Start of the round, I put my ID in my PDA, then my PDA in my ID slot.

When the multiverse shenanigans started, my PDA was deleted and the multiverse card was put in its place.

**Comment by Jalleo** [comment]
Can you explain in a bit more detail please

**Comment by LatD** [comment]
If I understood correctly, the multiverse ID card always appears and replaces the normal ID card when multiverse begins. But if the original ID is inside PDA, the entire PDA disappears.

**Comment by MightyRadcon** [comment]
That is correct. If you place your ID in your PDA, then place your PDA in the ID slot, when the multiverse begins, the multiverse ID card will effectively "overwrite" the PDA, making it disappear.

**Comment by KorPhaeron** [comment]
Multiverse is gone
