### ISSUE TITLE
The academy queries ghosts every thirty seconds until a defender is chosen. If the defender dies or ghosts, it does it again and again and again and again.

### ISSUE THREAD

**Issue by Arquebusier** [tgstation/tgstation#14376]
![](http://puu.sh/mj8Z1/180874268f.png)

**Comment by RemieRichards** [comment]
[goofjectives intensifies]

**Comment by Zilenan91** [comment]
Wow that's a lot of fucking dead wizards. I don't think this is a bug at all because the wiz academy mission spawns another wiz teacher every time one dies, so a lot of them can get dunked on over the course of a long round.

**Comment by Arquebusier** [comment]
Even if you just ghost out (or aghost) it instantly spawns one.

Also when the academy is depressured, there's constant BE DEFENDER?!?! spam

**Comment by optimumtact** [comment]
well it's not really a bug

**Comment by KorPhaeron** [comment]
Could you put a real title for your issue?

**Comment by ChangelingRain** [comment]
how about we not away missions ever

**Comment by XDTM** [comment]
does this even matter anymore

**Comment by KorPhaeron** [comment]
Many of our issues dont matter but its still technically an issue

**Comment by Rinoka** [comment]
this isn't even really an issue in that it's a bug or consistency issue, it's the code working in an expected way with undesirable results

the easiest way to get rid of this would be to simply remove the code that allows for constant refilling of a role in the away mission

i'm pretty sure this is also old enough that the mentioned issue (spam) is solved by updates to the general interface -- i think now you could disable pings for the round and avoid being spammed with requests.

not even mentioning away missions are disabled and unsupported, replaced with spawnable ruins and shit

**Comment by Rinoka** [comment]
@KorPhaeron
