### ISSUE TITLE
Turret bugs (wtf)

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#14381]
When acided via xenos, turrets sometimes only have their cover destroyed, and sometimes the entire thing is destroyed, only to magically zap into existence perfectly fine a few seconds later.

There's also some weirdness with the tesla where I think the tesla zaps the turrets and they dissapear completely (?) only to reappear a few seconds later or sometimes not reappearing at all.

**Comment by RemieRichards** [comment]
Don't melt the cover, p.sure it rebuilds itself.
If you melt the turret itself it actually dies, iirc.

**Comment by Zilenan91** [comment]
I can't not melt the cover, when I melt the turret it either melts the entire thing and the entire thing dissapears only to reappear seconds later (like literally gone) or only the cover dissapears and I can punch it.

**Comment by optimumtact** [comment]
there are spawns that could cause a race condition where you destroy the cover and then the turret repops it, dunno if you could easily replicate it though

**Comment by WJohn** [comment]
Is this relevant anymore after the phil damage rework?

**Comment by kevinz000** [comment]
@lzimann no longer relevant as turret covers aren't a thing anymore as a separate object.

**Comment by RemieRichards** [comment]
@kevinz000 Please don't spread misinformation.
https://github.com/tgstation/tgstation/blob/master/code/game/machinery/porta_turret/portable_turret_cover.dm

**Comment by kevinz000** [comment]
Nevermind, my mistake, sorry, but it doesn't break anymore.

**Comment by kevinz000** [comment]
just tested in tdome, xeno acid and tesla bolts break them properly now.
