### ISSUE TITLE
Assistants spawning at non-assistant start landmarks.

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#14425]
For instance, spawning in the toxins room (not a mapping error, only a scientist spawn is there).

I don't really know how to reproduce this but it happened.

**Comment by KorPhaeron** [comment]
I have seen this happen on mini station

**Comment by swankcookie** [comment]
I believe this explains #14373 as well

**Comment by GunHog** [comment]
Filthy greyshirts invading sacred departments.

**Comment by lzimann** [comment]
Probably due to lack of assistant spawners(for example ministation high pop) and just throwing them somewhere else

**Comment by swankcookie** [comment]
Can someone confirm this? I can remap some extra spawners, but i would like to be sure this is the issue first.
