### ISSUE TITLE
Sepia Timestop Behaves Improperly

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#14434]
Maybe this intentional, but it doesn't seem like it.

When you use the sepia slime core timestop reaction, it immediately stops all things properly, but the icon for it doesn't render as it should---additionally, after time resumes, it plays the timstop sound and stops time _again_.

I'm guessing this is because in effect/timestop/New() automatically calls Timestop() after checking for immunities---and the slime extract has the timestop effect created, then the timestop proc is manually called.

**Comment by KorPhaeron** [comment]
Doesn't render as it should?

**Comment by Fox-McCloud** [comment]
The timestop effect generates a clock that flickers/has a watery appearance; this doesn't appear.

**Comment by XDTM** [comment]
Tested, works properly right now
