### ISSUE TITLE
Helmetlights and slings

### ISSUE THREAD

**Issue by apuh3** [tgstation/tgstation#14457]
Helmetlights (seclites stuck on sec helmets) have some god awful snowflake code for being activated and deactivated where instead of having luminosity, they increase the turf's or the user's luminosity, meaning there's some unexpected behavior.  For example, they bypass all the redundant light deactivation code in shadowling veil and effectively turn back on whenever they're moved (IE removed from a victim)

**Comment by swankcookie** [comment]
maybe, when combined, the helmet should just switch to a prepared hardhat version.

**Comment by bgobandit** [comment]
we don't even have slings anymore
