### ISSUE TITLE
Too many implementations of flashlights

### ISSUE THREAD

**Issue by apuh3** [tgstation/tgstation#14458]
We have several separate implementations for flashlights in several different things that can be used as flashlights, including PDA's, flashlights themselves, firefighter helmets/hardhats, hardsuit helmets, and sec helmets.  Those all have some weird quirks and sometimes result in minor bugs, like having to de-activate and re-activate your PDA because something's just turned all your lights off, to bugs that would be minor but kill shadowlings.

It would be more maintainable, and would probably fix and/or prevent bugs, if the code for items which act as lights when worn were standardized.

**Comment by swankcookie** [comment]
While I agree, and think this is very important, I think that worn light-emitters, and handheld  light-emitters should be kept seperate.

**Comment by xxalpha** [comment]
The only difference between those two kinds of objects is that handheld can't be equipped to a clothing slot.

**Comment by lordpidey** [comment]
@cyberboss with the lighting revamp, this isn't as much of an issue.
