### ISSUE TITLE
Traitor objectives can be given to clients that are in the lobby

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#14469]
This happened to me a _long_ time ago and I only just remembered it and realized I should report it, so my memory's probably a bit fuzzy, but basically:
1. Hit "Ready" in the lobby the exact same tick the game starts/the button changes to "Join Game"
2. You will not join the game, but remain in the lobby
3. Roll traitor (maybe other antag types too, but I wouldn't know, I just know it works for traitors). Your objectives/the traitor fluff text WILL be given to you despite being in the lobby. Maybe the codewords too, but I don't remember.
4. Be able to latejoin as any role (including loyalty implanted ones) and retain antag status

You also do not spawn with an uplink, which led me to have to adminhelp for one.

If I had to guess how this bug happened, I'd say that it's probably caused by Byond's interface lagging behind and allowing me to hit Ready after the game started but before antag roles are handed out, putting me in the pool of people that have a chance at rolling antag but not actually putting me in the game.

Since this was so long ago, it _may_ have already been fixed unintentionally, but there isn't much of a way to be sure aside from testing. Local testing is probably harder since it's a direct connection and therefore there'd be less lag on the Ready button, and live testing is tricky because you won't always roll antag.

**Comment by MMMiracles** [comment]
This has happened to me before, only with cult. I was able to join as HoS afterwards and proceeded to confuse all the other roundstart cultists.

**Comment by ShizCalev** [comment]
Still an issue? Will close in a week without further report.

**Comment by Cyberboss** [comment]
There's zero chance this can happen with antag datums, right @AnturK ?
