### ISSUE TITLE
Bluespace Translocation can teleport stuff to space

### ISSUE THREAD

**Issue by callanrocks** [tgstation/tgstation#14474]
Happened on Meta, teleported most of medical to old tcomms sat, including a few people.

**Comment by bgobandit** [comment]
feature

**Comment by WJohn** [comment]
Pretty sure it's supposed to be confined to the station areas, but I could be wrong.

**Comment by coiax** [comment]
As coded, it picks a random teleport beacon, and dumps everything there. Some teleport beacons are in space.

**Comment by bgobandit** [comment]
my "feature" wasn't a meme, how is this a bug, it makes perfect sense

**Comment by XDTM** [comment]
feature
