### ISSUE TITLE
Cargo Bug?

### ISSUE THREAD

**Issue by Aredal** [tgstation/tgstation#14483]
What happened:
1-Find emag
2-Order swat gear crate and syndie gear crate
3-Cargo tech sends the crates back beucase no reason
4-Come back
5-Order one more null crate for 90 points, it does not take away the points from the console.
Order a second one for the shuttle, says not enough points but still points are stuck at that value and increasing slightly from 13-something to 16-something later 
6-Nothing comes on the shuttle
7-Cry as your Swatgonia dreams fade away

**Comment by Mervill** [comment]
Cannot Reproduce -- Outdated / Not Enough Info

The null crate isn't even 90 points, it's 1400, and I'm not seeing a syndicate crate in the (emag'd) cargo list.

**Comment by calzilla1** [comment]
@lzimann seems pretty outdated, think you should close it

**Comment by lzimann** [comment]
I'll reopen if anyone actually reproduces this/find if this is actually an issue currently.
