### ISSUE TITLE
The PR announcement system is very vulnerable to being spammed

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#14508]
Since github bans are apparently awful to apply, we were at the mercy of someone just spam opening/closing his PR until we kicked the bots and disabled the announcements serverside. Needs flood detection or something.

@MrStonedOne

**Comment by PKPenguin321** [comment]
oranges what have you done

**Comment by tkdrg** [comment]
Just give admins a button to disable it

**Comment by Jordie0608** [comment]
There already is one

**Comment by tkdrg** [comment]
>the config controller can be varedited to turn it off

Didn't work when I tried it.

**Comment by Zilenan91** [comment]
This was all part of Oranges master plan to increase security on the server

**Comment by PKPenguin321** [comment]
it's oranges

**Comment by SouDescolado** [comment]
Could it be changed to just appear there as it gets tagged?

**Comment by Dorsisdwarf** [comment]
Wouldn't the easiest way to fix this be have a simple counter every time the same person opens/closes a PR, and ignore the message if they've open/closed more than, say, 4 times in the last minute?

**Comment by Giacom** [comment]
If the data was transferred in a text2list format (arg1=value1&arg2=value2) then you could key the username of the author and limit their PRs to 3 a round.

**Comment by SouDescolado** [comment]
Could it go to a temp list that would only appear at round start/round end?

**Comment by coiax** [comment]
Is this still a problem?

**Comment by kevinz000** [comment]
yes it is @coiax  since goof is here.

**Comment by coiax** [comment]
This is why we have repo bans.

**Comment by KorPhaeron** [comment]
@coiax 

We've had issues with people using throwaway accounts to do it until we had to turn the announcer off

**Comment by coiax** [comment]
Should make it so the announcements serverside and bots can be disabled from IRC.
