### ISSUE TITLE
Turf sprite bug on snow away mission

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#14511]
![Yay](http://puu.sh/mnHx6/7347a51775.jpg)

**Comment by swankcookie** [comment]
@MMMiracles

**Comment by swankcookie** [comment]
Has this been dealt with? @MMMiracles

**Comment by MMMiracles** [comment]
all signs lead to 'no' 

probably won't bother fixing due to lack of interest and /tg/ decommissioning away missions

**Comment by swankcookie** [comment]
good idea. kinda crazy how issues like this probably represent over half of the current ones in the issue list. just sitting there, never to be looked at again...
