### ISSUE TITLE
Singularity works inconsistently on asteroid station mining turfs

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#14536]
If the singularity goes to the asteroid, it does not eat the asteroid floor, but it does eat the walls. The curious part about it eating the walls is that it leaves the outlines of the walls behind, and the asteroid walls left do not smooth out like walls should.

**Comment by tkdrg** [comment]
The former is intended I believe, but the latter is a bug. @xxalpha

**Comment by Zilenan91** [comment]
It works, or worked correctly on the actual asteroid zlevel turfs, but for some reason doesn't on asteroid station mining turfs.

**Comment by tkdrg** [comment]
Huh, I could swear that I've seen this happen on box mining as well.

**Comment by Zilenan91** [comment]
Yeah on box mining it doesn't pull the asteroid flooring turfs but it does delete them when it goes over them. It doesn't delete them or pull them when it goes over the asteroid station mining asteroid.

**Comment by tkdrg** [comment]
I meant the sprite issue.

**Comment by Mervill** [comment]
@optimumtact closeable, rip asteroid station
