### ISSUE TITLE
End round antag report has the objective change to the current name and title for assasination objectives.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#14532]
Objective #1: Assassinate Robot Noise, the Cyborg. Success!
This was formerly the Hop. Not sure if this is for all borging, as he got autoborged so maybe that messed something up.

**Comment by tkdrg** [comment]
@Shadowlight213 was this before or after the goofjectives revert

**Comment by Shadowlight213** [comment]
@tkdrg supposedly after. I asked in coderbus and was told goofjectives were reverted.

**Comment by tkdrg** [comment]
they were reverted around the time this happened and I'm not sure if the servers updated. It would have been nice if we knew the show-server-revision from when that happened

**Comment by duncathan** [comment]
There's a reason we have the template

**Comment by tkdrg** [comment]
Well we could pull it from the runtime logs if we knew the exact round this happened. Or just wait for someone else to report it

**Comment by duncathan** [comment]
@tkdrg we might be able to figure out the round by searching attack logs for the day for "Robot Noise"

**Comment by ShizCalev** [comment]
This is due to borging calling fully_replace_character_name, which updates tator memories iirc.
