### ISSUE TITLE
ATV's bypass exile implants...

### ISSUE THREAD

**Issue by apuh3** [tgstation/tgstation#14540]
...allowing snowdin operatives free passage to the station.  Simply drive the ATV through the gateway; it will go through without you.  Then, drive it in any direction.  It will move, and pull you along with it.

**Comment by ChangelingRain** [comment]
You can already defeat exile implants with two sheets of metal formed into a locker so this isn't a ton different, besides not needing two people.

**Comment by AlexanderUlanH** [comment]
I thought we fixed the lockers

**Comment by Cheridan** [comment]
i'm closing away mission issues

**Comment by Cheridan** [comment]
muh downstreams i guess
