### ISSUE TITLE
Tesla doesn't respect space torus

### ISSUE THREAD

**Issue by JJRcop** [tgstation/tgstation#14550]
# EXTREMELY *SHOCKING* DISCOVERY
The tesla will warp to a space tile, but not trigger the space transition, so it stays on the zlevel it was created on forever. 

This could be fixed by moving it instead of loc setting if the location is beyond the transition number stuff

**Comment by Zilenan91** [comment]
I think it's a feature that it stays on the zlevel tbh.

**Comment by tkdrg** [comment]
yeah this was known ever since the first revision but goof never managed to fix it

**Comment by Cheridan** [comment]
its intended for the ball to stay on zlevel

**Comment by Iamgoofball** [comment]
it's intentional because otherwise the tesla fucks off into space

plus it shouldn't ennd up at space anymore since it moves towards what it zaps
