### ISSUE TITLE
Being in an MMI counts as surviving

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#14564]
doesnt make much sense

**Comment by swankcookie** [comment]
Whose to say what is and isn't surviving?
Can we get a "Philosophical quandary" tag, please?

**Comment by lzimann** [comment]
Well the MMI technically makes your brain work, isnt this kinda intended...? You are alive, no body, but alive...

**Comment by Bawhoppen** [comment]
yes but balance wise it makes no sense

**Comment by PKPenguin321** [comment]
especially since you can't really "kill" an MMI without removing the brain, which requires robotics access

**Comment by francinum** [comment]
@PKPenguin321 Wasn't that changed a while ago to where anyone can just upend the thing?

**Comment by PKPenguin321** [comment]
dunno, was it?

**Comment by TrustyGun** [comment]
yes, anyone can take the brain out of the MMI

**Comment by octareenroon91** [comment]
You end up a living/carbon/brain inside an MMI. Probably need to talk about what 'escape alive' really should mean.

**Comment by octareenroon91** [comment]
At present, "stay alive until the end" should fail if you are an MMI. Remember, the objective is defined for AIs, too.

https://github.com/tgstation/-tg-station/blob/master/code/game/gamemodes/objective.dm#L297
```
	if(isbrain(owner.current))
		return 0
```


https://github.com/tgstation/-tg-station/blob/master/code/game/gamemodes/objective.dm#L362
```
	if(!owner.current || owner.current.stat == DEAD || isbrain(owner.current))
		return 0		//Brains no longer win survive objectives. --NEO
```

**Comment by Jalleo** [comment]
That is not the code it checks its a different code for antags at round end that it checks to see if they won. Lemme find it.

**Comment by Jalleo** [comment]
Only way i can see is its checking mmi or mind incorrectly.

**Comment by swindly** [comment]
I think this was fixed.
![Untitled](https://user-images.githubusercontent.com/22402048/70950152-aaeb1c80-2057-11ea-8ab2-64c908473136.png)
