### ISSUE TITLE
Antag AI failure to virally dominate mech

### ISSUE THREAD

**Issue by MightyRadcon** [tgstation/tgstation#14579]
I was an AI on box station. I virally dominated a mech that was breaking into the core. When I got into it, I could not control anything. I could open the menus and reload & select weapons, but I could not move, turn, shoot, or anything else.
- I was originally not an antag, but was admin-assigned antag with 130 points to destroy the station.
- I hacked 30 points from APCs after activating the doomsday device.
- I received three law changes over the course of the round.
- The mech I virally dominated was a piloted durand.
- I believe it might have been locked down, but I would think that viral domination overrules that, since it transfers the AI's entire consciousness into it.
- Defense mode on the durand was OFF. I confirmed this by turning it on after I realized I could not move.

**Comment by GunHog** [comment]
What about *Maintenance Mode*? Did you get any messages at all when you tried to move? If the mech's interface was unlocked, the angry pilot could have switched it on. Mech domination does not override maint mode.

**Comment by MightyRadcon** [comment]
No messages at all. Can you explain maint mode a little more? I might be able to narrow it down.

**Comment by GunHog** [comment]
ID and DNA locks do not matter, I just tested that myself. There is nothing that halts an AI taking over a mech, even another Malf AI (They are overwritten during the takeover, having nowhere to go).

**Comment by ShizCalev** [comment]
Still an issue? Will close in a week without further report.
