### ISSUE TITLE
MULEbots

### ISSUE THREAD

**Issue by rancereya** [tgstation/tgstation#14583]
I've noticed that every time I've played cargo that the mulebots sometimes stop responding entirely and their ui interface window proceeds to never close/stay closed.

I've been able to see other peoples interactions with the bots from the other side of the station too.

**Comment by SouDescolado** [comment]
Maybe related to #14424?

**Comment by WJohn** [comment]
Is this still the case? The fix was just merged 3 days ago. Needs some testing.

**Comment by rancereya** [comment]
It was still the case this morning when it kept popping up while someone
else manipulated the MULE.
Also the wire menu came up while it was being hacked as well.

**Comment by Shadowlight213** [comment]
I've seen similar happen with pretty much every bot as AI.
