### ISSUE TITLE
search function in security records console nonfunctional

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/tgstation#14598]
for the AI, anyway. has happened to me several rounds in a row. on entering a name and hitting enter, no search is performed and no sound feedback is given either.

**Comment by Lumbermancer** [comment]
For everyone. That's how it been for at least few months now. I was meant to report the bug but never came around to it. And now I want and I see it has been reported 4 days ago, and has not yet been fixed.

Thank god you can ctrl+f in the window.

**Comment by CPTANT** [comment]
Would be nice if this got fixed. Its annoying the shit out of me every time I use a security records console.

**Comment by Lumbermancer** [comment]
Still broken yo.

**Comment by Lumbermancer** [comment]
Still broken.

**Comment by Lumbermancer** [comment]
STILL BROKEN

**Comment by PKPenguin321** [comment]
1. List records
2. Ctrl+F

**Comment by Lumbermancer** [comment]
oh you don't say? Exactly how I said in second post here?

**Comment by PKPenguin321** [comment]
why are you complaining so hard then fam i mean a lot of things are still broken but you don't see people shitting up those issue reports

**Comment by Lumbermancer** [comment]
Because it's been broken for a very long time and doesn't seem like something that would be hard to fix.

My immersions.

**Comment by TechnoAlchemisto** [comment]
bro we are -broken-
