### ISSUE TITLE
Ninja Star embedding causing icon fuck up

### ISSUE THREAD

**Issue by tedward1337** [tgstation/tgstation#14600]
Getting embedding with a ninja star changes the characters hair style/face. Nothing game breaking, but my immersions. Can be fixed by taking said embedded object out of you.

**Comment by RemieRichards** [comment]
Hahaha what.

**Comment by tedward1337** [comment]
Not sure if its like this with all embedding. The ninja star in question was from an actual space ninja as well.

**Comment by Dorsisdwarf** [comment]
Sounds like an edge case with preferences?

**Comment by Incoming5643** [comment]
as far as I know embeded objects don't actually show up on your character model, so I don't know why it'd even update the body, let allow the hair.

**Comment by lzimann** [comment]
Thunder11 couldn't reproduce it.
