### ISSUE TITLE
you can forcibly break open abandoned crates

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/tgstation#14601]
NO FUN FUCK THE POLICE.

Check my codebase for the fix since we did this a while ago.

https://github.com/Zaers/-tg-station

**Comment by newfren** [comment]
Is the issue here that abandoned crates function consistently with locked crates.

I don't see the problem.

**Comment by Supermichael777** [comment]
agreable now that abandoned crates actually work because apparently in their code 0=null(fix made 0=z which is bad BUT FUNCTIONAL).
But consider that it typically requires a limited resource (gibonite) to bypass its a non issue. Stop stomping on emergent game-play etc.

**Comment by Durkel** [comment]
If you're going to fix the crates at least give us back artifact rooms.

**Comment by bengin-polyp** [comment]
i don't even understand how abandoned crates are supposed to work, i didn't see anything in the wiki on them. I thought gibbonite was how you opened them.

**Comment by newfren** [comment]
They have a mastermind game based off of numbers that you can only do if you have a multitool.

Enter 1234 then pulse with a multitool and you'll see how they work.

**Comment by Shadowlight213** [comment]
You don't even need gibtonite to open them. Just get a Ripley and drill the crate. Bam. Instant open.
I make a fix pr making the crate delete its contents on Destroy() but it was rejected.

**Comment by lzimann** [comment]
The crate can no longer be cheesed so I guess this can be closed.
