### ISSUE TITLE
Various Synth disguise issues.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#14617]
I ran a round a few days ago where I made everyone a synth, and I discovered a few issues with them.
- ~~Synths have no examine icon. Lizards and himans have that little naked person icon in their examine text, but synths just have a whitespace. This makes it easy to tell if someone is a synth.~~
- Cloning a synth will cause it to lose its disguise and come out as a bare machine. Said disguise is lost completely and cannot be remade with synthflesh or anything as the fake species data isn't transferred to the new body.
- Setting species with any way other than the admin VV set species dropdown menu will cause the disguise to fail to build, creating either a barebones machine skeleton, or a poorly overlayed default human. This makes it really annoying to mass turn people into synths, as you cannot use the set everyone's species button like you can with all other races.

@RemieRichards

**Comment by Zilenan91** [comment]
We don't have examine icons anymore, and the 2nd one is probably a bug/missing feature.

**Comment by Shadowlight213** [comment]
Huh. someone else reported that to me. Didn't realize that examine icons are gone.

**Comment by Jordie0608** [comment]
Did you try using SQDL2 to mass call set species?

**Comment by Shadowlight213** [comment]
Sqdl2 doesn't work, as the admin set species is actually not a proc, but part of the href switch statement for the drop-down menu.

**Comment by Jordie0608** [comment]
Yes, but the href calls a proc
https://github.com/tgstation/-tg-station/blob/master/code/datums/datumvars.dm#L855

**Comment by Shadowlight213** [comment]
Yes, but unless you also call admin_set_species with their old dna as an argument, the disguise will not build.
You can't do that with sqdl2.
Calling setspecies by itself will cause them to not generate a disguise and have a buggy appearance.

**Comment by RemieRichards** [comment]
Can just have it fall back to a human disguise if things fail, and maybe an ```on_cloned()``` proc for species datums

**Comment by Dorsisdwarf** [comment]
I'll be honest, synths should fail cloning completely. You can't clone beepsky, after all.

**Comment by bengin-polyp** [comment]
>You can't clone beepsky, after all.

What if, and stay with me on this one, but what if you COULD clone beepsky. After all beepsky is the hero security needs.

In all seriousness I really like the idea of having to use synthflesh patches to reconstruct your appearance after cloning as a synth.
