### ISSUE TITLE
People can use machine/computer frames to block lasers like they used to with girders.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#14623]
What it says on the tin. Girders got changed to have a "girderpasschance" var that makes it possible for lasers to sometimes slip through. People now instead use machine and computer frames since they both do exactly the same thing but without that chance, albeit are a tiny bit more costly.

This can be used to fight the AI or go through the emitter maze in exactly the same way people used to.

**Comment by Supermichael777** [comment]
people will always find a way. just make shots pass over machines 100% of the time if unanchored.

**Comment by WJohn** [comment]
Should frankly be the case with girders too, then. I mean, you don't see grilles blocking them and girders still look full of holes.

**Comment by xxalpha** [comment]
Is there a need to have the computers block projectiles?
