### ISSUE TITLE
Lube/water on bright tiles like med/sci

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#14628]
lube/water on bright tiles like the ones in Medbay and Science are NEARLY invisible and cause a slight discoloration. Meanwhile on regular tile they are very noticable with a "shining" look

**Comment by WJohn** [comment]
Not entirely sure how to resolve this. Medbay tiles are extremely bright, very close to maximum white. Meanwhile, the wet floor tile overlay is yet more white as an alpha. You basically have the problem of white on white, which is borderline invisible. Not sure how you'd pull off giving the shine itself some sort of outline and still have it look good, though.

**Comment by kevinz000** [comment]
Playability > looks :^)

**Comment by Dorsisdwarf** [comment]
These were invisible completely for actual years.

Besides, I find the idea that the "medsci clean" style actually makes medsci *more* dangerous funny
