### ISSUE TITLE
Xenobio console lets you see through walls

### ISSUE THREAD

**Issue by lzimann** [tgstation/tgstation#14626]
Even if there's no camera in the area, it lets you see.
Edit: Appears to actually have static when there is no camera(for some reason it wasn't working when I created the bug report).

**Comment by WJohn** [comment]
Xenobio consoles are really just ayy lmao camera consoles that don't let you move past the xenobio area. As a result, they inherit the properties of being able to see perfectly fine through walls.

**Comment by phil235** [comment]
There's more to this bug. The first time that you connect to the xenobio console, your Eye sees static in areas not covered by cameras. But if you disconnect and reconnect to the console, the static will be gone.

**Comment by lzimann** [comment]
Oh, so that's how it works, I didn't exactly realize how to remove static, it just removed by itself sometime after. That's my main thing with this report, that the static just goes away.

**Comment by Dorsisdwarf** [comment]
See Phil's report
