### ISSUE TITLE
Lights that aren't broken don't work until taken out/put back in.

### ISSUE THREAD

**Issue by Ausops** [tgstation/tgstation#14621]
> expect light from light tube
> no light from light tube
> take out light tube
> put light tube back in
> light tube now gives light

???

**Comment by WJohn** [comment]
I've seen this happen before, but I don't remember the circumstances that cause it. Might have to do with forced darkness like shadowlings, but I could be completely wrong.

**Comment by Zilenan91** [comment]
It happens with slings and I think revenant defile. Also with advanced darkness wizard event.

**Comment by Supermichael777** [comment]
lighting is terrible.

**Comment by ChangelingRain** [comment]
As a note, it *shouldn't* happen with revenant defile, because that uses the light's flicker proc.

**Comment by Ausops** [comment]
it's totally roundstart stuff, independent of sling I think. Lights will just start bugged out until they get taken out/put back in.

**Comment by Niknakflak** [comment]
It also does this whenever admins spawn a fully built light.  It wont light up until tube is taken out abd inserted again.

**Comment by tkdrg** [comment]
flicker() used to be broken but i fixed it at some point I think, dunno if it is broken again

**Comment by Razharas** [comment]
Anything blicking sight moving to and away from the turf of light source breaks that light source until it is turned off and on again
Usually this happen with mechs

**Comment by Razharas** [comment]
Yes i know because i ded it a few times

**Comment by CPTANT** [comment]
This happens frequently and has been for ages.

It is one of the bugs I constantly encounter and it is getting annoying.
