### ISSUE TITLE
Naming condiment bottles is a useless feature

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#14631]
You can name these things out of the CondiMaster Neo, but the second anything gets inside of them the name dissapears and they become just a regular old condiment bottle, with you being unable to label them without a hand labeler.

**Comment by Zilenan91** [comment]
bump I'd really like this fixed

**Comment by xxalpha** [comment]
>bump

**Comment by Zilenan91** [comment]
I dunno man it was like 2:00 AM

**Comment by octareenroon91** [comment]
>condiment bottle sprite has a label

will a pen not work?

**Comment by Zilenan91** [comment]
I've tried, it doesn't. You can actually name them when you dispense them from a Condimaster but once any units of liquid get inside of it it just gets the label "condiment bottle."
