### ISSUE TITLE
Mutation toxin does not work on lizards.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#14643]
What it says on the tin. This may be the case for other species, but it works fine for humans.

**Comment by Zilenan91** [comment]
Lizards also aren't changed to different species when there are viruses out that force-change people into someone else.

Ex : A virus is turning everyone into Geist Dangerous, lizards will be immune. Sometimes they will not be immune and instead just assume his name instead of his appearance.

**Comment by octareenroon91** [comment]
At least one mutation toxin does that by design. This is a code/balance issue.

I'm not sure if the DNA retrovirus carries species or just UI/UE

**Comment by XDTM** [comment]
No longer an issue.
