### ISSUE TITLE
Grabbing is really screwy.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#14665]
Grabbing someone and moving will have them move in parallel to you. Grabbing multiple people will have you start to move multiple tiles at once (though thankfully not through walls). I wonder how big a chain you can make?

Basically: You can grab multiple people and have them grab people and MOVE IN FORMATION??

**Comment by Cebasiz** [comment]
>unintended formation system

feature

**Comment by PKPenguin321** [comment]
You can already do this with pulling and rolling chairs. This doesn't seem like an issue at all.
