### ISSUE TITLE
Reactive tele armor and magic

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#14688]
If you have telearmor and you dodge a magical bolt it still does its effects to you but you teleport away .. like if you get deathbolted your CORPSE teleports
Oh and telebatons bypasses it!
and handcuffs but it's probably a feature!

**Comment by Cebasiz** [comment]
>mekhi wants to buff telearmor

this is a good meme

**Comment by kevinz000** [comment]
its not a buff its fixing a bug 
:^)
either make magic penetrate or MAKE IT WORK I hate having my deathbolted body in the middle of nowhere not able to be found

**Comment by Zilenan91** [comment]
Telearmor shouldn't even block magic tbh

**Comment by KazeEspada** [comment]
Armor does not apply to ranged touch attacks. TG should know this.

**Comment by Lumipharon** [comment]
does meme armour still do the thing where it can trigger off any hit, not just shit hittin your chest?
