### ISSUE TITLE
Syndicate comms give two messages instead of one

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#14687]
So if someone types "Hi botanist here"
it'd be
"Hi botanist here"
"Hi botanist here"

**Comment by KorPhaeron** [comment]
I believe this happens because of the tcomms equipment on snowdin

**Comment by Zilenan91** [comment]
So it only happens when the Snowdin mission loads?

**Comment by Lumipharon** [comment]
You could just remove the snowdin synie comms thing then, since the nuke opbase one applies to all z-levels/already works for traitors with syndie keys?

**Comment by KorPhaeron** [comment]
@MMMiracles

**Comment by Cheridan** [comment]
top quality bug. away missions are dead so i'll close this
