### ISSUE TITLE
SMG magazine appears to still have bullets in it even when empty.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#14717]
What it says on the tin, we have separate sprites where there is no bullet visible at the top to indicate it is empty, but they're apparently not being used.

![](http://i.imgur.com/rMWen9z.png)

**Comment by PKPenguin321** [comment]
https://github.com/tgstation/-tg-station/issues/14315

>They're just unused, but so are like a trillion other sprites. This is a complete non-issue.

*taps foot angrily*
