### ISSUE TITLE
Rusted walls have no icons when being deconstructed.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#14746]
They turn black as soon as you click on them with wirecutters. Should probably just use the normal deconstruction icons because screw making custom ones for that shit.

**Comment by RemieRichards** [comment]
Rust should just be an overlay damn it.

**Comment by KazeEspada** [comment]
But how will mappers use them?

**Comment by Zilenan91** [comment]
I thought you were just supposed to weld down rusted walls like normal walls.

**Comment by RemieRichards** [comment]
@KazeEspada they'd still have the icon state for when on the map, but it'd be set to normal in New() and the rust overlay applied then.

**Comment by Dorsisdwarf** [comment]
@Zilenan91 there are also rusted rwalls
