### ISSUE TITLE
you can walk into a shocked grille under a shutter

### ISSUE THREAD

**Issue by hornygranny** [tgstation/tgstation#14757]
i dunno if this is that fixable

**Comment by octareenroon91** [comment]
I'd imagine so: fulltile glass keeps you from being shocked on a grille underneath it.

**Comment by tkdrg** [comment]
Does this just use straight bumped or is it some snowflake proc

**Comment by Dorsisdwarf** [comment]
think this is dupe

**Comment by Cheridan** [comment]
yeah guess its a dupe
