### ISSUE TITLE
Emagged defibs can bypass shield hardsuits

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#14788]
seeing how it blocks everything before the shield goes down, this seems like an issue.

its also funny because I only saw this happen because of one particular person who uses it a lot.

**Comment by WJohn** [comment]
Might be intentional, as energy swords go through as well.

**Comment by GunHog** [comment]
E-swords go through because of penetration mechanics, I believe.

**Comment by MMMiracles** [comment]
I don't see the correlation between defibs and energy swords.

It stops batons so I can't really see how a defib bypasses it.

**Comment by tkdrg** [comment]
emagged defibs use some snowflake attack code
I'd wager shit like screwdriver eye attack does it too

**Comment by Zilenan91** [comment]
Electricity from other stuff also goes through shields, as do spear attacks.

**Comment by MMMiracles** [comment]
How does that still work if batons are blocked??

If one touch-based electrical stun doesn't bypass it, why would another?

**Comment by Zilenan91** [comment]
Batons are physical I guess, I dunno.

**Comment by Cyberboss** [comment]
@coiax Was this fixed when you changed heart attacks?

**Comment by coiax** [comment]
Defibs do different things depending on your intent. I don't know.

**Comment by jughu** [comment]
@anturk defibs are now blocked by hardsuits eveni used this a week earlier and i couldnt place it on a hardsuit
