### ISSUE TITLE
Massive amounts of blue/bluespace tomatoes in one tile can lag the server to shit via slips

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#14827]
And if you think that will never happen in a round:

ADMIN LOG: Bgobandit/(Leo Pfeifer) has deleted all (570) instances of /obj/item/weapon/reagent_containers/food/snacks/grown/tomato/blue/bluespace. 

fucking daisy

**Comment by Lumipharon** [comment]
Botany can mass produce things better than any other department or job in the game, bar none.

**Comment by newfren** [comment]
I once had all my trays upgraded to tier 4 parts and was getting like 80 plants from one harvest.

**Comment by Firecage** [comment]
@bgobandit Wouldn't bananas also basically cause this?

@Dorsisdwarf Also, I think this needs a Balance tag instead of a Bug tag, that seems more related.

**Comment by Cyberboss** [comment]
Slips don't lag anymore, this is closable @lzimann
