### ISSUE TITLE
BRPED rnd machines while they're making something/printing a circuit.

### ISSUE THREAD

**Issue by Ausops** [tgstation/tgstation#14842]
It might lock the console up.

**Comment by WJohn** [comment]
We've been wrestling with this bug for years and years. It keeps coming back god damn.

**Comment by xxalpha** [comment]
Isn't the RPED recent? And BRPED even more recent? Sounds like oversights during the implementation of these.

**Comment by WJohn** [comment]
Well specifically the fact that R&D machines lock up. That kind of bug has come and gone so many times.
