### ISSUE TITLE
Player beepsky's permastun people with one stun baton hit

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#14865]
They cannot get up on their own.

**Comment by lzimann** [comment]
I believe this only happens with xenobiology golems

**Comment by Cheridan** [comment]
the law

**Comment by phil235** [comment]
Looking at secbot's stun_attack() proc, I don't see you could end up stuck permanently stunned. The proc uses the standard Stun() and Weaken() procs.

https://github.com/tgstation/tgstation/blob/53773c3bbfca372562b0c84db5f042bbb546e121/code/modules/mob/living/simple_animal/bot/secbot.dm#L211

Someone should try to reproduce the bug.

**Comment by PKPenguin321** [comment]
i got stunned by a beepsky just the other day and got up normally, i really dont think this is still a bug

**Comment by lzimann** [comment]
Yea, i think this got fixed somewhere
