### ISSUE TITLE
Bloodcrawling bugs 

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#14863]
1. If you drag A CONTAINER ON YOU to an area on the ground while bloodcrawling it will dump out the contents.. ONLY YOU CANT STOP IT BY MOVING IT WORKS EVEN IF YOU MOVE AWAY
2.  I have a taser in it and it is no longer rechargable after that happens. Also, don't know if it's related, but my flashlights stop emitting lights too.

**Comment by xxalpha** [comment]
Just to clarify, removing a taser from a container while bloodcrawling will make that taser invalid for recharging?

**Comment by Dorsisdwarf** [comment]
Please retitle the issue to be more relevant

**Comment by WJohn** [comment]
Confirmed on the first case, the second is probably just another instance of #10516. It's possible the taser was caught in an explosion at some point.

**Comment by kevinz000** [comment]
Nope, I never got blown up and the taser worked perfectly before I bloodcrawled, then it works but can't be recharged
