### ISSUE TITLE
Wizards can choose to be Military Synths

### ISSUE THREAD

**Issue by drynwyn** [tgstation/tgstation#14883]
Wizards can use the Magic Mirror to become Military Synths, which gives them punchstun and a high armor value. This should probably be changed.

**Comment by Zilenan91** [comment]
It really should, military synths are a bit too powerful for wizards to be able to be.

**Comment by xxalpha** [comment]
feedback forum

**Comment by Zilenan91** [comment]
The place that no coders will ever read

**Comment by ChangelingRain** [comment]
I have a solution already. #14773

**Comment by WJohn** [comment]
I mean they can also choose to be plant people, which heal in light but take double burn damage, or skeletons which have space and cold immunity, or slime people which take half heat/fire/laser damage but doubled cold damage.

**Comment by drynwyn** [comment]
Both of those are less potent then armor and stunpunches imo

**Comment by WJohn** [comment]
I don't know about you but taking the gem suit (which is extremely heavily armored) plus slime makes you both immune to the slime downsides and have over 50% damage immunity to lasers.

**Comment by Shapsy** [comment]
What about the lesser badmin mirror? Wasn't that specifically made to prevent issues with players chosing OP races?

**Comment by ChangelingRain** [comment]
The lesser mirror was made to let people choose face/hair/etc for stuff like centcom events without having to deal with edgy shadowling centcom officials.

**Comment by Zilenan91** [comment]
The Snowdin mission uses it, lets you be a human or a lizard.

**Comment by TheNightingale** [comment]
Let them keep normal synths, then, so they can do the "silicon rights and a staff of change" gimmick.
