### ISSUE TITLE
You can make two flamethrowers from one tool

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#14892]
![image](https://cloud.githubusercontent.com/assets/12382984/12550230/3834d716-c35a-11e5-9ba6-c98167662996.png)
If you're click it quick enough you can make two throwers from one tool with two rods. Not too gamebreaking but eh, I like my headpats.

**Comment by WJohn** [comment]
Why are flamethrowers still partially constructed in your hands rather than all done with table crafting? Someone needs to move it to that.

**Comment by Lumipharon** [comment]
Because tablecrafting is a piece of fucking shit and everyone avoids it whenever possible?

**Comment by octareenroon91** [comment]
Neat.  Sounds like this is a qdel thing. I wonder if someone could double tablecraft...

**Comment by Razharas** [comment]
Tablecrafting doesnt allow such things to happen and is much easier to code though
Usual crafting is the devil

**Comment by PKPenguin321** [comment]
usual crafting is intuitive as fuck while 99% of new players wouldn't consider dragging a table to themselves

**Comment by Razharas** [comment]
Thats a problem on interface not the system as such
New players wouldnt consider applying rods to wirecuffs to make wires rods, then adding a wirecutter and then a powercell to make a prod, so in terms of intuitivity there isnt much difference

**Comment by Lumipharon** [comment]
the fact that literally no on uses tablecrafting when there is a non table crafting alterative is proof enough that it's unpopular and shit. Doesn't matter if it's easier code or whatever.

**Comment by Firecage** [comment]
@Razharas As everyone else said, Table crafting is unpopular. If there is an alternative to using it, people WILL use that. It is way more fun and immersive to actually construct things yourself from its parts.

Anyway, doesn't really have anything to do with this specific issue.
