### ISSUE TITLE
Sound procs are being replaced by New() calls, breaking everything (CLEANBOT, corgis, etc)

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#14893]
!!!SEE COMMENTS FOR RELEVANT INFO!!!

1) A global narrate shows up for players spontaneously, often after announcements (NOTE FROM THE FUTURE: because they play sounds). Here is what it looks like (the first announcement is from a silicon who happened to get named Cleanbot after this nonsense started):

Cleanbot Announces:
I am in your head now. Cleanbot.

What players see immediately after: (cleanbot minicon) Cleanbot

2) Over 6000 cleanbots spawn in nullspace. Server crashes, either on its own or due to the efforts of admins trying to del-all 6000 cleanbots. rip

![img](http://puu.sh/mJdeG/90da67856b.png)

from runtime logs the Cleanbot (/mob/living/simple_animal/bot/cleanbot): New(null, null, null, null, null) 

(/mob/living/simple_animal/bot/cleanbot): New('sound/ambience/title1.ogg', null, null, null, null)  -- relatedly all in-game sounds stopped working for everyone around now, admin did disable playing sounds at around the same time though

**Comment by lzimann** [comment]
Apparently it's showing up to all announcements

**Comment by AnturK** [comment]
Hum what.

**Comment by Miauw62** [comment]
﻿ｗｅ  ａｒｅ  ｌｅｇｉｏｎ

**Comment by bgobandit** [comment]
Antur
alright 
all "sound" types got replaced by "mob/living/simple_animal/bot/cleanbot" 
literally 
wtf byond

**Comment by RemieRichards** [comment]
The icon and name output is due to the corrupted statement being ```world << sound()``` originally, and ```<<```ing an object displays it's icon and name.

**Comment by AnturK** [comment]
```
Undefined variable /mob/living/simple_animal/bot/cleanbot/var/wait
proc name: playsound local (/atom/proc/playsound_local)
  source file: sound.dm,27
  usr: (src)
  src: Maline Trell (/mob/living/carbon/human)
  src.loc: the floor (90,146,1) (/turf/simulated/floor/plasteel)
  call stack:
Maline Trell (/mob/living/carbon/human): playsound local(the floor (90,147,1) (/turf/simulated/floor/plasteel), 'sound/items/Screwdriver.ogg', 50, 1, 42685, null, 1)
Maline Trell (/mob/living/carbon/human): playsound local(the floor (90,147,1) (/turf/simulated/floor/plasteel), 'sound/items/Screwdriver.ogg', 50, 1, 42685, null, 1)
playsound(the floor (90,147,1) (/turf/simulated/floor/plasteel), 'sound/items/Screwdriver.ogg', 50, 1, null, null, 1)
the security camera (/obj/machinery/camera): attackby(the screwdriver (/obj/item/weapon/screwdriver), Maline Trell (/mob/living/carbon/human), "icon-x=7;icon-y=27;left=1;scre...")
Maline Trell (/mob/living/carbon/human): ClickOn(the security camera (/obj/machinery/camera), "icon-x=7;icon-y=27;left=1;scre...")
the security camera (/obj/machinery/camera): Click(the floor (90,147,1) (/turf/simulated/floor/plasteel), "mapwindow.map", "icon-x=7;icon-y=27;left=1;scre...")
```

Where relevant code is :
```
/atom/proc/playsound_local(turf/turf_source, soundin, vol as num, vary, frequency, falloff, surround = 1)
	soundin = get_sfx(soundin)

	var/sound/S = sound(soundin)
	S.wait = 0 //No queue
	S.channel = 0 //Any channel
	S.volume = vol
```

And many more similar instances where mob/living/simple_animal/bot/cleanbot() was used instead of sound() call

**Comment by tkdrg** [comment]
Not our bug. Report it upstream to lummox I guess. I'll close this in a few if no further information surfaces.

**Comment by 9600bauds** [comment]
This is just fucking magical

**Comment by drynwyn** [comment]
Power Word Cleanbot

**Comment by bgobandit** [comment]
happened twice on bagil, with corgis instead of cleanbots

**Comment by Saegrimr** [comment]
Bonus is that the corgis are actually fucking in nullspace, creating corgi puppies which announce themselves who eventually grow into normal corgis who also then fuck and make more puppies.

**Comment by optimumtact** [comment]
Why has no-one reported this upstream yet?

**Comment by RemieRichards** [comment]
@optimumtact if you mean to Byond, I did, AGES ago, Lummox agrees it's something internal mixing itself up but doesn't know anymore and doesn't know where to start.

**Comment by optimumtact** [comment]
Suprisingly this was found and fixed for 511

**Comment by Cyberboss** [comment]
We're running 511 right? So close it? Also can we remove the cleanbot_bug calls?

**Comment by Cyberboss** [comment]
Bump. See my above comment

**Comment by lzimann** [comment]
We should wait for 511 stable before closing imo.

**Comment by optimumtact** [comment]
That was what I was waiting for, although apparently at this rate we will be waiting forever.
