### ISSUE TITLE
Teleporting to Artifact Rooms has always been broken

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#14910]
Currently, they don't show up in the teleport menu at all.

Before, there would usually be around 5 artifact room teleporters in the teleport menu, where some of them would teleport to the same exact artifact room, just in a different tile.

**Comment by tkdrg** [comment]
I'm pretty sure this is intended in order to prevent meta

**Comment by Zilenan91** [comment]
It used to work perfectly though, what pr was it removed?

**Comment by Jordie0608** [comment]
They probably just use the same area

**Comment by KorPhaeron** [comment]
They make a new area, but createroom doesnt call the proc that updates the teleport list
