### ISSUE TITLE
Can't see attack messages through walls as a ghost

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#14913]
really annoying

**Comment by phil235** [comment]
That's visible_message() code. The same thing happens to mobs with thermal vision.

**Comment by SuperNovaa41** [comment]
Still an issue

**Comment by SuperNovaa41** [comment]
![2021-12-29_01:12:38_%](https://user-images.githubusercontent.com/16159590/147632580-ac9aeee9-9e4a-4e39-a0e8-2f20b96d259b.png)

**Comment by tralezab** [comment]
for future reference this was closed for being a feature- ghosts getting every message that even whomever they're orbiting is not seeing would lead to overly spammy chatboxes
