### ISSUE TITLE
Sydrone Health issues

### ISSUE THREAD

**Issue by imtakingabreakdontatme** [tgstation/tgstation#14923]
So syndrones supposedly start with 30 health, and a maxHealth of 120, with a comment explaining that consuming other drones will make them stronger.

They have 120 health when they spawn though

**Comment by neersighted** [comment]
Not sure this is a bug; pretty sure someone along the line gave up on the eating drones mechanic.

**Comment by PKPenguin321** [comment]
yeah its probably just a garbage comment

**Comment by Zilenan91** [comment]
They can eat dead drones, as can regular drones. They can reactivate them as well as salvage for parts, and consume for healing.

**Comment by PKPenguin321** [comment]
yes zile we know but that is not the topic of the issue

**Comment by KorPhaeron** [comment]
/mob/living/simple_animal/drone/syndrone/Login()
	..()
	src << "<span class='notice'>You can kill and eat other drones to increase your health!</span>" //Inform the evil lil guy

**Comment by KorPhaeron** [comment]
health = 30
	maxHealth = 120 //If you murder other drones and cannibalize them you can get much stronger

**Comment by KorPhaeron** [comment]
Something is not working as intended

**Comment by PKPenguin321** [comment]
if syndrones are a child of normal drones there might be some weirdness in drone/new() or something idk

**Comment by RemieRichards** [comment]
Somebody along the line decided that instead of fixing a bug with the "start with lower health, eat to gain more" mechanic they'd instead REMOVE IT.

Said person is on my naughty list as it's made Syndrones far more powerful than originally intended.

**Comment by RandomMarine** [comment]
The real joke is that even if it worked the syndrones can just screwdrive themselves.
