### ISSUE TITLE
Welding fuel tanks explode oddly when hit by a KA blast

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#14936]
When you hit a welding fuel tank with a welder or shoot them with a laser they explode in a piddly little explosion just around the welding tank.

However when you shoot a welding fuel tank with a kinetic accelerator it makes a much larger explosion that blows a hole into the station's floor.

Accordings to K Peculiar it is not logged, whereas the other welding fuel tank explosions are.

@KorPhaeron I assume.

**Comment by MrStonedOne** [comment]
welding tanks have different explosion ranges for different triggers for some god awful reason.

**Comment by CPTANT** [comment]
According to the referenced PR this was fixed.
