### ISSUE TITLE
Medbay doors are no longer synced.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#14941]
When pushing the medbay door button, one door will open after the other, rather than simultaneously.

![](http://i.imgur.com/9EOnnt5.png)

Both doors started closed, I'm not sure why it's getting queued.

**Comment by neersighted** [comment]
Honestly I'd just like to port doublewide medbay airlocks from bay.

**Comment by Zilenan91** [comment]
Don't we have those? I'm p sure that Snowdin uses them for its armory.

**Comment by tkdrg** [comment]
Yeah we have those, but we don't use it because of a reason I think

**Comment by phil235** [comment]
There's a sleep() fucking things in the airlock's open() probably. Something similar happens when clicking the airlock with an item that has an afterattack(), you click, the door opens, and only after the door is completely opened then the afterattack() code is called.
