### ISSUE TITLE
Suicide_act() with a tank is buggy as shit with NODROPS(and even worse with nozzles and defibs)

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/tgstation#14959]
So Suicide_act() with a tank makes you unequip all your items and throw them everywhere as your body is suddenly destroyed from the pressure.

Except NODROPS hate unEquiping so they often end up stuck in the hands of the now dead person.

To make matters worse, nozzle based things such as sprayers(botany, atmos, and janitor) as well as defibs all fall apart when the body explodes since it doesn't correctly allow the parts to come back together.

**Comment by lzimann** [comment]
Oh yea, it happens with hardsuits aswell. If you have your helmet on it will drop a hardsuit helmet(which should be inside the hardsuit). Forgot to report this a while ago.

**Comment by tkdrg** [comment]
i could swear we had some generic proc to unequip errything, used in dust() or some shit
maybe just generalize dust() for this

**Comment by optimumtact** [comment]
There should be a hard drop proc that deletes no drop items

**Comment by lzimann** [comment]
No longer an issue since it won't force NODROP items on the ground.
