### ISSUE TITLE
Being-on-fire can be resisted without gravity.

### ISSUE THREAD

**Issue by ChemicalRascal** [tgstation/tgstation#15033]
Being alight (ergo, on fire) can be resisted while in a zero-gravity situation. Ergo, one can stop, drop, and roll, in an environment where one is actually physically incapable of stopping and dropping.

I'm not sure how removing the ability to resist fire in zero gravity would affect balance, but figured I'd raise a bug report anyways to at least promote a discussion on the topic. As niche as it is.

**Comment by kevinz000** [comment]
Id say this would be a feature as otherwise if you don't have an extingusher and you get set on fire its ggnore.

**Comment by xxalpha** [comment]
I say correct the inconsistency. Saboteurs could plan to take down gravity before starting fires.

**Comment by Shapsy** [comment]
Fires that are impossible to put out without an extinguisher sounds _incredibly_ unfun

**Comment by xxalpha** [comment]
Sounds incredibly how it was before the resist.

**Comment by neersighted** [comment]
Some different fluff text if there is no gravity would be an easy fix.

**Comment by tkdrg** [comment]
I'm pretty sure this is a dupe

**Comment by ChemicalRascal** [comment]
If it is, the existing report didn't show up on my searches.

**Comment by swankcookie** [comment]
While this doesn't seem terribly important, I agree with @xxalpha that this could add somestrategy to saboteurs. I could see a Atmos-savvy MalfAI using this incredibly towards there advantage in the event of a plasma flood

**Comment by Cheridan** [comment]
Sounds like it'd be terribly frustrating and would mostly occur in cases where things are already going horribly (plasmafire + no gravity). 

Just imagine you're patting yourself out instead, whatever.
