### ISSUE TITLE
Buildmode generator, Asteroid/Hollow/Random/Monster option

### ISSUE THREAD

**Issue by Ausops** [tgstation/tgstation#15035]
Buildmode generator with the asteroid/random hollow/monster option bugged out. It would spawn asteroids with random walls/floors inside but it wouldn't spawn monsters.

For whatever it's worth it was a bit laggy and I was turning buildmode on and off constantly.

**Comment by AnturK** [comment]
Can't reproduce, might have just been bad luck since they're not guaranteed to actually spawn monsters.

**Comment by Dorsisdwarf** [comment]
Closing in 1 week/ next time I see this if not reproduced
