### ISSUE TITLE
You can tablecraft a chainsaw with the holodeck saw

### ISSUE THREAD

**Issue by tkdrg** [tgstation/tgstation#15046]

**Comment by PKPenguin321** [comment]
Inherent problem with tablecrafting, see my issue about applying invalid cells to prods with tablecrafting. It lacks blacklist checks for certain children objects.

**Comment by tkdrg** [comment]
the holodeck one isn't even a different object, it's just a normal saw with some varedits

**Comment by PKPenguin321** [comment]
Then the only way to fix this without tweaking tablecrafting is making a "brother" object of saws that's just holosaws with lots of copy paste, which is really bad and ugly

**Comment by tkdrg** [comment]
Or we could just tweak tablecrafting

**Comment by PKPenguin321** [comment]
have fun with that

**Comment by xxalpha** [comment]
Or we could just abandon.

**Comment by rev-benji** [comment]
yeah tablecrafting is pretty bad but theres some stuff you can't do without it, like I don't think you can remove pins without using tablecrafting. 

at least change it back to dragging table to yourself so I don't accidentally open the window when im tabling mekhi

**Comment by octareenroon91** [comment]
Tablecraft needs to check, what, the ABSTRACT flag?
