### ISSUE TITLE
you can buckle with full hands but not unbuckle

### ISSUE THREAD

**Issue by hornygranny** [tgstation/tgstation#15053]

**Comment by KorPhaeron** [comment]
Hit the chair button newfriend

**Comment by Firecage** [comment]
He means unbuckle other people.

**Comment by Mervill** [comment]
Confirmed: Someone can buckle you to a chair while holding things in both hands, but cannot unbuckle you

**Comment by kriskog** [comment]
Emergent gameplay. Drop what you are holding to unbuckle someone.
