### ISSUE TITLE
Tesla doesn't shock simple mobs

### ISSUE THREAD

**Issue by Shapsy** [tgstation/tgstation#15050]
Saw a tesla loose on a blob round and it didn't shock any of the blob zombies running around right next to it, I'm not 100% sure but I think I should tag @Iamgoofball for this

**Comment by Iamgoofball** [comment]
simple_animals have no electrocute_act() handling so they can't get hit by the tesla

i'll fix it probably with my farm animal shit

**Comment by PKPenguin321** [comment]
Unintentional fixes hell yeah
