### ISSUE TITLE
Cryo layer goes under windows

### ISSUE THREAD

**Issue by tkdrg** [tgstation/tgstation#15051]
Cryo is 2.1, windows 2.9; This can look weird if cryo is directly under a window.

**Comment by neersighted** [comment]
Note: The fix is not messing with cryo. Windows are the problem here, they're much too high.

**Comment by WJohn** [comment]
This also means that cryo tubes are underneath people; you can walk above their top half.

**Comment by neersighted** [comment]
Maybe shorten the sprite. Cryo always looked out of place.

**Comment by ChangelingRain** [comment]
this is not an easy fix, also it will never be easy until we have planes

**Comment by CyberbossJHCB** [comment]
#21112 How's that working out for ya?

**Comment by ChangelingRain** [comment]
it turns out the answer is "planes may not be a good choice send help"

**Comment by MrPerson** [comment]
Planes don't let you do anything layers don't already let you do on this front

**Comment by WJohn** [comment]
Not so much a map issue, unless the rule of thumb is "don't put cryo tubes directly under windows or anything other than walls".

**Comment by PKPenguin321** [comment]
I think widows could do with having their layer lowered
