### ISSUE TITLE
Snowdin indestructible walls have incorrect base turf

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#15084]
Meaning you can poke holes to space by deleting the walls (with a singularity, for example)

**Comment by KorPhaeron** [comment]
I will fix this after my splashscreen pr is merged I do not want to conflict with myself

**Comment by duncathan** [comment]
>the indestructible thing causes issues when you destroy it

**Comment by xxalpha** [comment]
What is destroying these?

**Comment by Zilenan91** [comment]
A singularity. BoHs spawn on the away mission.

**Comment by Lumipharon** [comment]
>build a PA on the away mission to rip a hole through the mission to cheese it

10/10

**Comment by Cheridan** [comment]
away missions are ded
