### ISSUE TITLE
AI camera goes to start zone after moving

### ISSUE THREAD

**Issue by lzimann** [tgstation/tgstation#15095]
Whenever you spawn as AI, when you move your camera you go to the start zone(if you are roundstart AI).
I tested by transforming myself into an AI and it moved the camera to the thunderdome,where I first spawned a human body and then transformed myself into an AI(it moved to the AI core).

**Comment by GunHog** [comment]
Confirming this issue. Happened to me during Greytide-Highlander when I asked to be the AI. A badmin spawned me on the arrival shuttle, then AI'ed me. When I moved my eye from my core, it snapped back to the arrival shuttle.

**Comment by CPTANT** [comment]
yeah this seems to be happening every time I play AI now.

**Comment by Dorsisdwarf** [comment]
happened to me once yesterday

**Comment by Shadowlight213** [comment]
@Dorsisdwarf doesn't seem to happen anymore
