### ISSUE TITLE
Bug with lich death

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#15150]
When lich dies, round ends, no matter exists his phylactery or not.
/obj/effect/proc_holder/spell/targeted/lichdom/New()
This code, as i have tested is never executed.

```
    if(initial(ticker.mode.round_ends_with_antag_death))
        existence_stops_round_end = 1
        ticker.mode.round_ends_with_antag_death = 0
    ..()
```

It was checked by adding this code:
`world << "<B>The current game mode is - Wizard!</B>"`
 after this line:
`ticker.mode.round_ends_with_antag_death = 0`

**Comment by Dorsisdwarf** [comment]
I've not seen this happen myself. Is this a downstream server?

**Comment by lzimann** [comment]
It's for mulligan, if an admin set the round to end after antag death, it won't check if the wizard has the lich spell and his phylactery is active or not.

**Comment by tkdrg** [comment]
@Incoming5643 for datum antags

**Comment by HunterMaksim** [comment]
I tested it on local server.
I haven't set the round to end after antag death.

**Comment by ShizCalev** [comment]
Still an issue? This was all refactored a while ago. Will close in a week if no further reports.
