### ISSUE TITLE
Flashes don't affect the blob.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#15178]
Flashes don't affect the blob, only flashbangs specifically affect it. Meaning making flash powder grenades in chemistry is completely useless.

**Comment by Firecage** [comment]
Well, Flashbangs aren't actually just a bright flash of light...

**Comment by Buggy123** [comment]
True, but you could make a grenade that looks identical to a flashbang, acts exactly like a flashbang, but doesn't affect blobs whatsoever. Making it require both sonic powder and flash powder, I.E. both a flash and a bang, would be fine but as is its very inconsistent.

**Comment by PKPenguin321** [comment]
We need to generalize flashbang code into a proc, it's really snowflake at the moment

**Comment by Buggy123** [comment]
We can just turn it into a chem grenade with sonic powder and flash powder, most grenades are like that.

**Comment by Firecage** [comment]
Well, scratch the flash powder part. The only useful part should be sonic powder, since that is what effects blobs.

**Comment by Buggy123** [comment]
Wait, the sound part of a flashbang is what hurts blobs?

The organism which is explictly vulnerable to concentrated light (lasers), and heat, isn't affected by a extremely bright flash but is affected by a loud bang?

**Comment by PKPenguin321** [comment]
see https://github.com/tgstation/-tg-station/blob/master/code/game/objects/items/weapons/grenades/flashbang.dm#L15

just move this to the bang() proc
