### ISSUE TITLE
Zombie species and simple mob issues.

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#15194]
So right now if you create a simple mob zombie, upon killing their target they will also become a zombie (nice!) also if they die, they will be resurrected in a few minutes. 
BUT if you turn a player into a zombie (via Set Species in VV) they don't have the ability to transmit the "disease" nor will they resurrect, they simply LOOK like a zombie.

Is there anyway to change this?

Also it be nice if both zombie types couldn't speak plain human, is it possible to either create a new language that allows them to talk among themselves and to only come out as  Mumbles or "BRAIIINNNS" or something similar. Right now its pretty immersion breaking when a zombie can scream "Get back here you fgt" etc etc... (yes Ive seen it happen)

**Comment by Incoming5643** [comment]
There are many different kinds of zombies in the codebase.

In terms of newest to oldest:

There are simple animal zombies, that raise human corpses as simple animal zombies.
There are blob zombies, that pick up human corpses and grow stronger
There are the zombie race, which are pretty durable, talk funny, and have no infection potential.

These are all completely seperate concepts with absolutely no overlap beyond the fact that they're all "zombies"

**Comment by KorPhaeron** [comment]
I think the confusion comes from the fact that when you kill a xenobio zombie, it drops the human corpse back off, but with their race edited to zombie, so it appears as if you had just killed a real human/you can strip and interact with them normally.
