### ISSUE TITLE
Lockboxes drop their contents on the ground in Destroy()

### ISSUE THREAD

**Issue by neersighted** [tgstation/tgstation#15235]
This means that if you send back a crate full of loyalty implant lockboxes on the cargo shuttle, and then call it back, the implants will be dumped on the ground.

The shuttle deletes the the contents of crates, and all atoms on the shuttle. Because the lockboxes are qdel'd inside the loop, the loop does not catch them and they survive.

**Comment by tkdrg** [comment]
@KazeEspada

**Comment by KazeEspada** [comment]
This is intended in most circumstances, just not this one.

**Comment by KorPhaeron** [comment]
Some thing happens if you incinerate a lockbox in the crematorium.

**Comment by Mervill** [comment]
```
<Mervill> Does [15235] imply that lockboxes should dust their contents when destroyed?
<Miauw> Mervill: i think it implies that the mentioned cases should make sure theres nothing on the shuttle/in the incinerator
<Mervill> ooooh yeah ok that makes sense
```

**Comment by Mervill** [comment]
@optimumtact closeable, no longer an issue
