### ISSUE TITLE
Blobbernauts white out forever if enough flashbangs go off near them, but it happens minutes later

### ISSUE THREAD

**Issue by Cheimon** [tgstation/tgstation#15246]
Server: Sybil

Revision: 2016-02-06

Problem Description: Playing as blobbernaut, I witnessed some flashbangs going off (a box or two).  Flashbangs normally give you a full white screen for a few seconds.  I experienced intermittent white-outs for several minutes, and then went permanently blind (full white forever), despite moving away from the flashbangs shortly after the first one went off.

What did you expect to happen: I expected flashbangs to only white out my screen for a few seconds, then to get my sight back after I moved away.  

What happened instead: Flashbangs whited out my screen several times subsequently while not near them, then I lost my sight for the rest of the round (I played for about 20 minutes blind to be sure).  It was as though each flashbang was being applied individually in a row.

Why is this bad/What are the consequences: Flashbangs ought only to blind when they go off near you. For blobbernauts to be blind forever is a huge drain on the resources of a blob, especially if they can't even see their way towards the crew to die.  They are forced to ghost out, which isn't fun for anyone.

Steps to reproduce the problem: Play as a blobbernaut in a blob round.  Have someone throw a couple of boxes worth of flashbangs at the blob.  See a few explode, then run away to where they can't explode near you, and wait to go blind.  

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Blob gamemode, was blobbernaut, chemical lexorin I think?  I have nothing to really say here.

**Comment by ShizCalev** [comment]
Seems to have been fixed.
