### ISSUE TITLE
Taking bleed damage despite having no brute damage

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#15295]
I was fighting a cultist in space and managed kill him. I had a hivelord core implanted and used two brute patches to heal off the brute damage, but I continued to bleed out as I ran away and died in space.How is this even possible? How was I still bleeding?

**Comment by neersighted** [comment]
You can have bloodloss but no brute. Blood loss deals constant oxy damage until the blood is replaced.

**Comment by PKPenguin321** [comment]
He's saying he was still bleeding, not that he was taking the adverse affects of bloodloss

Are you sure you didn't have anything embedded in you?

**Comment by Shapsy** [comment]
Don't cults have special weapons that cause bloodloss?

**Comment by phil235** [comment]
@YakumoChen Were you bleeding (dripping blood on the floor)? Or simply taking oxy damage from low blood level?

**Comment by WJohn** [comment]
Embedded items can cause you to bleed even if the impaled limb has less than 30 brute damage.

I'm not sure about surgery, I know that it causes a fair bit of blood loss when screwed up, but I don't know what happens if you don't cauterize it after finishing it or leaving it half finished.

**Comment by RemieRichards** [comment]
As was said, not a bug, Brute can cause bleeding but is not at all required for it.
