### ISSUE TITLE
pAIs getting booted to the lobby

### ISSUE THREAD

**Issue by ATBarza** [tgstation/tgstation#15302]
Just had this happen to me. Was a pAI on the shuttle when the singularity ate me and my holder, lost connection instantly. When I reconnected the round was still in progress and I was kicked to the lobby and able to rejoin.

**Comment by PKPenguin321** [comment]
I'll try testing this tomorrow, I'm guessing it happens because pAI mobs are never meant to be deleted beyond the special "pAI Suicide" verb

**Comment by tkdrg** [comment]
probably the mob getting qdel()'d instead of ghotize()'d

**Comment by Dorsisdwarf** [comment]
Unable to reproduce, old issue closed
