### ISSUE TITLE
Ai's can't access some air alarms / apc's

### ISSUE THREAD

**Issue by CPTANT** [tgstation/tgstation#15333]
This has happened to be several times, certain air alarms just do nothing, despite having vision on them. You click on them but you don't get an interface popup and can't do anything with the alarm/apc

It seems to effect a small percentage of air alarms every round I play and it shifts which ones they are. They stay broken for the rest of the round.

**Comment by neersighted** [comment]
Probably a bug with the cameranet. If you could ping me or request an admin pings me (ahelp) when this happens I could diagnose the issue.

**Comment by KazeEspada** [comment]
Its related to the UIs thinking they are open when they arent.
Happens to players too, but players can reach the close distance.

Well, AIs never reach close distance.

**Comment by neersighted** [comment]
I don't think so. UIs disappearing is a problem thats mostly solved, as with default settings the UI can never leave the screen. Like I said, I can easily tell the cause if I'm called next time it happens.

**Comment by KazeEspada** [comment]
No no no. The UIs aren't leaving the screen, they are literally not displayed at all. Something to do with hitting the X button and it not probably removing the UI from active UIs.

**Comment by neersighted** [comment]
I've never experienced or been able to reproduce that behavior. Like I said, seeing this one time for myself will show what the issue is; I am very sure it is not that. It is likely pixel turf and camera weirdness.

**Comment by Cyberboss** [comment]
Closable

**Comment by Cyberboss** [comment]
@lzimann
