### ISSUE TITLE
Poly poly says span classes when repeating stuff heard from a recorder.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#15351]
`[Engineering] Poly squawks, "[00:02] <span class='game say'><span class='name'> Sergio Portabella</span> <span class='message'>exclaims, "<span class=''>One day while Andy was masturbating, Woody got wood. He could no longer help himself! He watched as Andy stroked his juicy kawaii cock. He approached Andy which startled him and make him pee everywhere on the floor and on Woody too. Being drenched in his urine made him harder than ever!</span>"</span><"`

@Incoming5643

**Comment by lordpidey** [comment]
Did poly hear the recorder over the radio, or in person?

**Comment by Supermichael777** [comment]
recorders are trash after they started picking up radio noise tbh

**Comment by tkdrg** [comment]
@Incoming5643 since he's apparently the parrot coder now

**Comment by Incoming5643** [comment]
Parrot coder != Gatekeeper of saycode

but I'll see what I can do

**Comment by lordpidey** [comment]
Whoa!  Was this fixed?  why was this closed.

**Comment by Shadowlight213** [comment]
Recorders were removed afaik
