### ISSUE TITLE
AI's *deathgasp shows a borgs death message.

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#15359]
When you deathgasp as a AI it will show
"(x) shudders violently for a moment, then becomes motionless, its eyes slowly darkening."
When the actual death message for the AI is
"(x) sparks and its screen flickers, its systems slowly coming to a halt."

**Comment by PKPenguin321** [comment]
relevant lines: https://github.com/tgstation/-tg-station/blob/94a138c2ad52da324728418e9b8fcbdb1f2b7576/code/modules/mob/living/silicon/robot/emote.dm#L102

**Comment by Cyberboss** [comment]
Pretty sure this doesn't happen anymore
