### ISSUE TITLE
Air tanks at 1013 pressure does not drop.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#15357]
I'm not sure if it actually does get used up, but it doesn't update in the UI on the status tab.

**Comment by neersighted** [comment]
Air tanks or jetpacks? Just to be clear.

**Comment by WJohn** [comment]
Both, and actually it almost definitely seems to be replenishing itself. Checked in status tab, examine, using analyzer, and air contents. If you use it up rapidly like by flying around in space, pressure will drop and then replenish back up to 1013.

**Comment by neersighted** [comment]
After live testing with @Wjohn it looks like this only applies to tanks used for internals. Jetpacks work as expected when not used as internals.

**Comment by neersighted** [comment]
@phil235 life refactor?

**Comment by Actionb** [comment]
Just to pitch in: I have seen that happen with tanks used for jetpacks.
Used an orange tank in pocket for internals (which didn't deplete either).
Had a big blue o2 tank on the exoslot for jetty packy stuff.
Played around with this for a bit, but couldn't really figure out what triggers it.

I haven't tested this with CO2 jetpacks, but I do remember people flying around apparently forever with these things. Afaik they should only last for ~1.5 orbits around the station.

**Comment by phil235** [comment]
Can't reproduce. I take an emergency oxygen tank, fill it to 1013 kPa at an oxygen canister, put on a mask and place the tank in my pocket, turn on my internals, the pressure drops as expected on the tank interface, on the analyzer results and on the status tab.
