### ISSUE TITLE
Duplication bugs

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#15369]
Sometimes when putting together a cyborg exoskeleton quickly (might happen with other items built by attacking with an item?), parts will not be used but will still be added to the frame. I was able to do this multiple times.

Embedded items will sometimes duplicate when they embed. The original item will be inside the person while the duplicate drops where it would of landed normally if it didn't embed. I somehow managed this with an energy sword, and was able to deconstruct both of them for research.

honkhonk

**Comment by MrStonedOne** [comment]
alright, I'll need you to admin help this while a coder is on, mainly so we can figure out if its real duplication or fake duplication, where it's the same instance of an item, just in two places.

**Comment by duncathan** [comment]
if a coder isn't on when you ahelp, ask the admins to ping a maintainer or neersighted in #coderbus so that we can debug as soon as it happens.
