### ISSUE TITLE
Pooling has Negative Performance

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#15377]
This may not be for every single pooled thing, but it wouldn't shock me if it was.

Here's a snapshot of breaking lights--keep in mind the pool was pre-filled before this test began, so as to stack things in pooling's favor:

http://www.hastebin.com/ufoceneyew.mel

Here's the same test, only two changes: the place-in-pool hint was removed for the spark effects and `PoolOrNew`  was axed for a plain old `new`: http://hastebin.com/afateyaruq.mel

so say the least, pooling is _significantly_ more expensive than non-pooling; not only in the creation of the actual object, but also in its destruction.

It strongly appears that, even with improvements to `ResetVars`, pooling still generates a net loss in performance over non-pooling.

**Comment by duncathan** [comment]
have we considered pooling the pools?

**Comment by MrStonedOne** [comment]
Lets delay deciding on this until lummox does his datum var storage improvements. as that could swing this in any direction, (and more to the point, the direction could change on different processors)
