### ISSUE TITLE
Being revved no longer stuns

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#15373]
Still mutes though

**Comment by PKPenguin321** [comment]
iirc only gang conversions stun, this is not a bug and intentional

**Comment by Zilenan91** [comment]
Rev conversion used to hold you in place for a bit after you got flashed so people knew it wasn't just someone randomly flashing other people.

**Comment by phil235** [comment]
It does stun you in the code, but not for long https://github.com/tgstation/-tg-station/blob/0d1f90ff542077c1e3dd0e64c7e7416d3c6fc347/code/modules/assembly/flash.dm#L91

**Comment by phil235** [comment]
@Zilenan91 Were you a hulk when you got converted?

**Comment by Zilenan91** [comment]
Nope, just a lizard

**Comment by phil235** [comment]
Can't reproduce

**Comment by Zilenan91** [comment]
I was smoking at the time but nicotine isn't strong enough to make me be able to move half a second after being revved

**Comment by phil235** [comment]
Actually even without nicotine being able to move again half a second after being flashed can easily happen. All it takes is a bad timing where life() is called right after we're stunned. Maybe we can make the stun a Stun(2) or 3 if we want new revs to be garranted to be stunned for at least one life cycle.

**Comment by Zilenan91** [comment]
A stun(2) would be the best I think.
