### ISSUE TITLE
You can emote on crit

### ISSUE THREAD

**Issue by tkdrg** [tgstation/tgstation#15399]
Tested with pressing the t hotkey and typing *cough. Not sure if intended.

**Comment by bgobandit** [comment]
think of the ERP this enables

**Comment by ChangelingRain** [comment]
I think this is a feature, given that you gasp while in crit and that's an emote(unless crit does something special and I'm pretty sure it doesn't)

**Comment by PKPenguin321** [comment]
Also to let you *deathgasp in crit

**Comment by duncathan** [comment]
Does this mean you can flip while in crit

**Comment by Shadowlight213** [comment]
@duncathan Tested it. You cannot.

**Comment by duncathan** [comment]
laaaaaaame

**Comment by alexkar598** [comment]
is this a bug or a feature it seems more like a feature

**Comment by BeeSting12** [comment]
You can flip in critical.

**Comment by XDTM** [comment]
After the emote rework i'm pretty sure that you're restricted to a few emotes while in crit, like gasp and deathgasp.
