### ISSUE TITLE
Conveyor Issues

### ISSUE THREAD

**Issue by Zerrien** [tgstation/tgstation#15426]
While working on #15425 I discovered a few other issues that I didn't have time to tackle, so I'm going to list them here until they are completed (by me, by others.)

- [ ] Placing a conveyor doesn't add it to the same-id conveyor_switch's conveyors list
- [ ] There should be a way to override the direction per conveyor
- [ ] Associating a conveyor-item with a conveyor_switch-item is awkward and sometimes doesn't work
- [ ] No way to repair placed conveyors
- [ ] Directional markings on the sprite to indicate which way the conveyor will push

- Being able to override the direction per conveyor (instead of per network) allows for more interesting conveyor designs.
- Would like to be able to place a conveyor-item on a conveyor_switch-machinery to make id association simpler. Multitool functionality?
- Welder + broken conveyor-machinery = repaired?

**Comment by neersighted** [comment]
Multitool would be a good way to pair them. Conveyors should really be faster, and bi-directional switches would also be nice.
