### ISSUE TITLE
Swarmers can deconstruct soil into metal

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#15463]
Probably because soil is the same path as hydro trays aka machines

**Comment by bgobandit** [comment]
how is this not a bug

it's fucking soil

do you see any magically materializing metal in a patch of soil

**Comment by WJohn** [comment]
Consistency issue tag should be renamed to "consistency/sanity" so it can cover things like this. Because really it's just an oversight.

Or maybe we need an oversight tag.

**Comment by tkdrg** [comment]
how about the Minor issue tag that I made and nobody uses

**Comment by WJohn** [comment]
OK.

**Comment by duncathan** [comment]
The soil is very rich in iron

**Comment by PKPenguin321** [comment]
>The soil is very rich in iron

Finally, somebody else who understands science
