### ISSUE TITLE
RCDs can be spammed to quickly produce grilles/windows for resource duplication/massive stacks

### ISSUE THREAD

**Issue by tkdrg** [tgstation/tgstation#15473]
(F) DEAD: _REDACTED_ says, "make grilles>cut>put rods in autolathe>make more cartridges."
(F) DEAD: _REDACTED_ says, "can duplicate glass just by making windows."

**Comment by Shadowlight213** [comment]
Sounds like a simple cost balance issue.
I'm assuming this is just for the ammo cartridges for the autolathe and that manually deconstructing a wall or window and putting the glass and metal directly into the rcd doesn't give more charge than is used to make it?
