### ISSUE TITLE
You can examine and point at light

### ISSUE THREAD

**Issue by TrustyGun** [tgstation/tgstation#15494]
![untitled](https://cloud.githubusercontent.com/assets/7079721/13026992/25ea3870-d20b-11e5-864e-059571f6cfc5.png)

I was a ghost

**Comment by WJohn** [comment]
Oh, so this bug's back again.

**Comment by neersighted** [comment]
This has always been here according to @MrStonedOne, or at least is always there for admins.

**Comment by TrustyGun** [comment]
This was on basil though, and I am not an admin

**Comment by MrStonedOne** [comment]
Its ghosts with darkness enabled who can, humans can not.

Its intended so that admin ghosts can debug lighting if needed.

**Comment by Mervill** [comment]
@optimumtact closeable
