### ISSUE TITLE
Valentine cards spawn on every human mob, alive or dead

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#15509]
This leads to situations like away missions littered with corpses now also giving every spawned corpse their own valentine card.

I don't know if this makes the missions more morbid or not.

**Comment by KorPhaeron** [comment]
>Hide body in locker
>card spawns on it

I'm crying

**Comment by bgobandit** [comment]
how would one fix this memery

**Comment by RemieRichards** [comment]
@bgobandit don't, this is great.

**Comment by drynwyn** [comment]
Feature.

**Comment by Shapsy** [comment]
The dead will not be forgotten

**Comment by Shadowlight213** [comment]
Spawns on AIs too.

**Comment by lzimann** [comment]
AI deserves some love aswell
