### ISSUE TITLE
Communications Console is glitchy

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#15526]
Communications Console keeps constantly updating, immediately switching from any other window, making it nearly impossible to type with a Communication Console window open.

Appears to be most common when interfacing with one as an AI.

**Comment by tkdrg** [comment]
@neersighted you know what to do

**Comment by neersighted** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa @tkdrg pls

**Comment by Shadowlight213** [comment]
This bug is super old. Has something to do with the console updating

**Comment by actioninja** [comment]
Still a problem.
