### ISSUE TITLE
Some things are weird colours sometimes

### ISSUE THREAD

**Issue by freerealestate** [tgstation/tgstation#15529]
Running latest version of BYOND
GFX card drivers up to date (NVIDIA)
Windies 10

I haven't tried turning it off and on again because I don't want to lose my shit
plenty of rams though, cp units, dick space, etc

edit: let me get you a J-peg so you can see its not hallucinatory

![](https://u.pomf.is/xrxnka.png)
![](https://u.pomf.is/bxwemp.png)

This only started happening in the past couple of days or so

**Comment by octareenroon91** [comment]
It looks like something has gone wrong in the alpha channels. It's not the hard-edged software/hardware rendering problem that's come up before either.

**Comment by xxalpha** [comment]
looks perfectly normal to me

**Comment by freerealestate** [comment]
when'd you last see an optician?

**Comment by neersighted** [comment]
It's 510.1325... I believe a BYOND bug is open (or should be opened).

**Comment by MrPerson** [comment]
This is what the game looks like in software mode. Turn on hardware mode.
