### ISSUE TITLE
Hotkey mode still doesn't stay the same when you switch mobs

### ISSUE THREAD

**Issue by lzimann** [tgstation/tgstation#15556]
Althought the annoying issue of looking like it did is out, it still doesn't keep the preference when you enter a new mob.

**Comment by MrStonedOne** [comment]
There is now a game preference to mostly alleviate the issue.

I'll fix it fully when i go over the ui and look at redoing some things

**Comment by lzimann** [comment]
The problem is that I change a lot the modes, so having as preference doesn't quite solve my issue
