### ISSUE TITLE
Robots can Take Oxy Damage

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#15557]
While I realize it's intentional that AI's can take oxygen damage, this seems odd that robots can, especially since they have no means of recovering oxygen damage, and there's really no particular points they need to take O2 damage (lexorin jelly is the only thing I can think of that does O2 to them).

**Comment by Jordie0608** [comment]
When they suicide robots take ~200 oxyloss so they can't just be repaired and revived.

**Comment by WJohn** [comment]
I think the bug here is that perhaps lexorin blobs can deal O2 damage to borgs and they can't ever get it fixed? This needs some testing.

**Comment by Cyberboss** [comment]
@Fox-McCloud @Xhuis I believe this was fixed, no?

**Comment by Xhuis** [comment]
yup
