### ISSUE TITLE
Borg hacked stunprod ignores Telearmor

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#15551]
Just in case ayy stun ignoring armor and getting me spaced on Zlevel 2 wasn't enough, now this.

**Comment by neersighted** [comment]
i ded

**Comment by GunHog** [comment]
Does it block a **normal** stunbaton?

**Comment by YakumoChen** [comment]
yes

**Comment by PKPenguin321** [comment]
remove telearmor when? too many bugs from it :^)

**Comment by Anonmare** [comment]
>Wearing telearmour has no downsides except a small chance to TP to space

Teleport armour being vulnerable to emags and EMPs when?

**Comment by GunHog** [comment]
It is not just teleport armor, but _shield type reactions._ Think nuke op shielded hardsuits, riot shields, etc. EMPs will disable the teleport armor, btw.

**Comment by kevinz000** [comment]
wew lads i'm not the one whinin about telearmor anymore

**Comment by KorPhaeron** [comment]
Pretty sure this got fixed
