### ISSUE TITLE
Efficiency disposals conveyor belt facing the wrong way

### ISSUE THREAD

**Issue by ATDoop** [tgstation/tgstation#15570]
![se2k6py](https://cloud.githubusercontent.com/assets/1959416/13082054/0ed1cef2-d49d-11e5-983e-48d9edd9e455.png)

On the far right.

**Comment by ATDoop** [comment]
Actually I just noticed it's the same on Box, too.

**Comment by WJohn** [comment]
That's probably not my fault then? Something may have gone wonky with conveyer belts. I don't recall anyone touching those lately, though.

**Comment by tkdrg** [comment]
@Zerrien changed their directions recently
