### ISSUE TITLE
Cult shades pop-up can be spammed.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#15583]
If you click on a corpse with a soulstone over and over, it will keep spamming deadchat with the noisy pop ups which is super annoying.

Please put a 10 second delay between uses because people for some reason think that being more annoying and spamming this is going to get them more responses.

**Comment by tkdrg** [comment]
i was pretty sure i fixed this, oh well, someone fix it please

**Comment by WJohn** [comment]
Also give us a "never for this round" option like all of these pop ups ought to have.

**Comment by WJohn** [comment]
Really, all pop ups need major consistency work done for them because there's so many of them which may be a popup, or are a text message in the chat, or are an action button on the screen. Needs consistency everywhere all around.

**Comment by Dorsisdwarf** [comment]
Just noticed that this was effectively fixed by 44197
