### ISSUE TITLE
Gangsters do not show up on admins' antag HUD

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#15626]

**Comment by Shapsy** [comment]
I think this is because they all have the same icon colors (but even then, just knowing if someone is a gangster or not, even if you don't know what gang they're in would be incredibly useful)

**Comment by tkdrg** [comment]
i was too lazy to add them because gang huds are awful code

**Comment by duncathan** [comment]
That's debatable tk and you know it

**Comment by tkdrg** [comment]
what's debatable, gang huds being awful or this being a feature request
if it's the latter then it's requesting a feature because gangster lacking huds was intended and documented

**Comment by bgobandit** [comment]
Speaking as an admin, I really don't care how bad the gang HUD code is when it's med-to-high-pop, someone has a dominator up, there's mass chaos and attacking, and I can't tell who's in what gang if any. It makes investigating anything basically impossible.

**Comment by duncathan** [comment]
Gang HUDs being awful
It's inconsistent sure but it's also modular unlike the rest
But w/e is pointless discussion

**Comment by Shadowlight213** [comment]
Yeah, admins really need gang huds. Having multiple teams in a conversion gamemode is pretty much impossible to track normally.
