### ISSUE TITLE
Heavy armor doesn't have damage resistance

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#15649]
/obj/item/clothing/suit/armor/heavy does not have any actual armor, because it doesn't list damage resistances, /obj/item/clothing/suit/armor doesn't list any, and /obj/item/clothing/suit doesn't list any.

It doesn't have any armor values, and it's subtypes don't either, so it's useless.

**Comment by PKPenguin321** [comment]
i'd fix this right now if i knew what armor values i could input without starting a whole balance debate

**Comment by Zilenan91** [comment]
Make it death squad levels so Emitter Maze gets removed

Because currently none of the emitters or turrets fire.

**Comment by WJohn** [comment]
These aren't used anywhere to my knowledge. MAYBE they're on the thunderdome but that's about it.

**Comment by Zilenan91** [comment]
There's one on the Emitter Maze away mission in the loot room.

**Comment by PKPenguin321** [comment]
we should just close this if they're no longer used since emitter maze got removed
