### ISSUE TITLE
Randomly turned into a monkey mid round.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#15658]
Let me preface this that I've communicated with a admin (shaps) when this happened and we can't come to conclusion as to what caused this.

I was recently autocloned, I had contracted two viruses, one needing salt to cure, the other spaceallin. I cured the spaceallin one,and then picked up a unlocked traitors pda. Soon after I drink some salt to cure the other one. 5-9 seconds afterwards I turned into a monkey with no warning. Neither virus advanced past stage 1/5.

What I can absolutely tell you:
There was no monkey virus present on the station.
I did not inject myself with a dna injector.
Admin fuckery was not involved.

Time of this incident was around 12:30 2/21/16 if you wish to check the logs.

**Comment by Zilenan91** [comment]
Could be that bug with DNA saboteur. It causes monkeying.
