### ISSUE TITLE
Engineering APC wasn't outputting power on Meta

### ISSUE THREAD

**Issue by Cuboos** [tgstation/tgstation#15660]
So i was the CE on meta trying to set up the engine. I was doing Tesla and moved the Emitters around to better fit the Tesla configuration. I wired everything right but for some reason the wires remained powered. I double checked everything, they were wired up correctly, there were no gaps or knots. But for some reason the APC was now powering the wires and the emitters did not activate.

**Comment by Jalleo** [comment]
Um the APC dosent power wires its vice versa. SMES cells give power from below them.
Aka terminals draw power that connect to apc or smes and smes outputs from a knot wire below it.

Did you disconnect the smes cell?

**Comment by Cuboos** [comment]
Yeah, and i replaced it with a fresh powercell.

**Comment by Jalleo** [comment]
Then this issue can be closed if there is no power in the future output from smes cells its solar panel time to then fix main power.

**Comment by MrStonedOne** [comment]
@tgstation/commit-access
