### ISSUE TITLE
Camera obscura shows spawn points

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#15672]
HELP: [redacted](?) (PP) (VV) (SM) (FLW) (TP) (REJT): bug alert: camera(?|F) obscura shows spawn points. it shows the Xs

**Comment by RemieRichards** [comment]
~spooky~

**Comment by Zilenan91** [comment]
Probably fine to keep around

**Comment by phil235** [comment]
Pretty sure you can see the god's mob/camera/god in hand of god, or blob camera.
See https://github.com/tgstation/-tg-station/blob/041461b21831cdfff88252d919c34d83189425a5/code/modules/paperwork/photography.dm#L188
probably need to check that atom movables wih invisibility superior to 60 (ghosts) doesn't get caught.

**Comment by Crushtoe** [comment]
It IS the chaplain's camera. Only makes sense you can see the hand of god.
