### ISSUE TITLE
Initialized Minimap subsystem within 75 seconds!

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/tgstation#15675]
### What is the problem?

See Title.
### Why is it a problem, or what should have happened?

The old Minimap subsystem didn't take 75 seconds
(and I actually had to edit the code to get it down to 75 seconds (counter 128 -> counter 64))
### How can the problem be reproduced?

Lower counters speed it up, but its still high.
Could atleast add an option to not generate minimaps.
### What revision did the problem happen on? (Helpful, but not required)

Latest master 22/02/2016

**Comment by tkdrg** [comment]
@neersighted @MrStonedOne

**Comment by MrStonedOne** [comment]
Lowering the counter makes it take longer

**Comment by RemieRichards** [comment]
@MrStonedOne
I had to lower it to 64 for it to actually finish.
Maybe it is faster with a higher counter, but it never actually finishes for me on anything higher than 64 counter.

**Comment by MrStonedOne** [comment]
Also its only once until the map changes, if you are doing lots of map changes its best to just disable that I guess

**Comment by MrStonedOne** [comment]
It never finishing is odd... Hmmm

**Comment by RemieRichards** [comment]
@MrStonedOne all it means is whenever there has been a map change my master takes fucking AGES to actually let me test my changes with anything other than -32fps.

**Comment by xxalpha** [comment]
The minimap also doesn't generate properly on the server when the map is changed.

**Comment by actioninja** [comment]
We don't even have minimaps anymore: https://github.com/tgstation/tgstation/pull/39459
