### ISSUE TITLE
teleprods are inconsistent with recent stunprod changes

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#15682]
See https://github.com/tgstation/-tg-station/blob/master/code/game/objects/items/weapons/teleprod.dm

Stunprods were recently changed to use igniters instead of wirecutters. Teleprods still refer to clamping a bluespace crystal into wirecutters, and the sprites are less consistent now (although this is much lower priority).

I intend to fix this at some point by making two variants of stunprods, one with wirecutters and one with igniters. For now I'm just gonna make this issue report to get the word out there.

**Comment by Buggy123** [comment]
Why did we even change it to igniters?

**Comment by PKPenguin321** [comment]
I still don't know tbh

**Comment by CosmicScientist** [comment]
#14905
Because igniters?

**Comment by xxalpha** [comment]
what the fuck is a teleprod

**Comment by CosmicScientist** [comment]
@xxalpha [teleprod.dm](https://github.com/tgstation/-tg-station/blob/master/code/game/objects/items/weapons/teleprod.dm)

**Comment by Supermichael777** [comment]
it was changed to prevent every greyshirt from having an invisible melee stun into having a select few greyshirts have an invisible melee stun.

**Comment by newfren** [comment]
>Invisible

Have you not ever seen someone holding a stunprod or are you just lying.

**Comment by Dorsisdwarf** [comment]
Maybe he means the fact that they go in backpacks.
