### ISSUE TITLE
Nukeops Nuke Station, Crew Major Victory

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#15693]
On Asteroid, blew the nuke, 2 nukeop survivors, crew major victory.

**Comment by MMMiracles** [comment]
asteroid station is so bad that blowing it up is actually a win for the crew.

**Comment by KorPhaeron** [comment]
Maybe because we left the disk behind and the 2 survivors were reinforcement ops rather than roundstart syndies.

So as far as the game was concerned the whole op team died and left the disk behind.

**Comment by PKPenguin321** [comment]
If the disk is left behind, the ops lose
Not a bug

**Comment by Aloraydrel** [comment]
I think its a minor victory for syndi if they all die when the station blows up

**Comment by Dorsisdwarf** [comment]
@PKPenguin321 

Disk left behind is the minor *syndie* victory.

**Comment by YakumoChen** [comment]
> I think its a minor victory for syndi if they all die when the station blows up
It's actually a no-win if all the ops die to the nuke. "Total Annihilation"

**Comment by vuonojenmustaturska** [comment]
I'm going to assume there is no issue here
