### ISSUE TITLE
Field Generator Icon Updates are Terribly Expensive

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#15704]
### What is the problem?

Field Generator `update_icons` is very expensive: http://pastebin.com/hg0wyk0Y
### Why is it a problem, or what should have happened?

It's a noteworthy cost for just updating a shitty little icon
### How can the problem be reproduced?

Run the server for a round with the profiler on, sort by proc cost, then scream

**Comment by RemieRichards** [comment]
This isn't true.
Its not expensive.

The issue is that its called EVERY PROCESS() TICK.
now THAT is expensive.

**Comment by xxalpha** [comment]
Yeah this shouldn't be done in the process().

**Comment by vuonojenmustaturska** [comment]
@KorPhaeron process() has not called update_icon() here after #15795
