### ISSUE TITLE
TGUI sometimes displays extra symbols.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/tgstation#15719]
### What is the problem?

TGUI has extra symbols
### Why is it a problem, or what should have happened?

Minor visual issue
### How can the problem be reproduced?

Start round, open TGUI
### What revision did the problem happen on? (Helpful, but not required)

2/23/2016, but Ive seen it since January.
![tguibug2](https://cloud.githubusercontent.com/assets/3869450/13276870/db09c310-da80-11e5-923c-075998456f38.png)

**Comment by tkdrg** [comment]
Looks like an issue with svg fonts?
@neersighted

**Comment by neersighted** [comment]
Not SVG fonts; unable to reproduce. Its both the font fallback and the real font loading for some reason. This is probably an upstream issue in the WebFontObserver...

**Comment by KazeEspada** [comment]
Only happens on the first ui of the round.

**Comment by optimumtact** [comment]
this happens to me if I open a UI immediately after spawn.

**Comment by Aranclanos** [comment]
locally or in the server?

**Comment by optimumtact** [comment]
on the server, I reproduced it about 10 minutes ago while testing tgui's for lag

**Comment by PraiseRatvar** [comment]
@optimumtact does it still happen if not then SMASH THAT CLOSE BUTTON

**Comment by vuonojenmustaturska** [comment]
@optimumtact i've never seen this and no-one i've asked has seen this, so if there's something here other than "two years ago we had this bug", reopen
