### ISSUE TITLE
floor tiles always have 20C temperature?

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/tgstation#15726]
### What is the problem?

if you build a bunch of floor tiles through space, they do not take on the temperature of space
### Why is it a problem, or what should have happened?

i built a megaconstruction of heat exchanger networks, but since the pipes were built on floors they remained 20C even when crossing 100 tiles through open space
### How can the problem be reproduced?

built floor in space, put heat exchanger pipes through it, observe 0 temperature drop
### What revision did the problem happen on? (Helpful, but not required)

latest

anyway just a small consistency issue that's a little weird.

**Comment by duncathan** [comment]
as a workaround, you don't need to place floor tiles to build pipes in space. you can place them directly.
anyway, i'll take a look at what might be causing this. my guess is construction not activating the turf or something similar.

**Comment by Cebasiz** [comment]
i ended up just routing a few tiles of it through a few tiles of walkway (the ones you build from rods) and it worked out. i reported more as a formality than a "BIG PROBLEM FIX IMMEDIATELY" thing.

**Comment by AnturK** [comment]
Can't reproduce.

**Comment by CPTANT** [comment]
might this have happened while atmos was disabled?

**Comment by duncathan** [comment]
making a floor tile should still maintain the temperature of the turf it's probably a problem in changeturf or something

**Comment by Robustin** [comment]
This is still a problem, and a pretty big one at that

**Comment by duncathan** [comment]
reassign me tbh

**Comment by Cyberboss** [comment]
Ya have to be maintainer

**Comment by duncathan** [comment]
it's breath. this 18 month old bug was caused because you breathed on something you shouldn't have. nice going, numbnuts.

(workin on a fix asap)
