### ISSUE TITLE
Beach away mission broken

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#15748]
There's holes to space along the shoreline where the shore turfs are supposed to be
You also can't actually exit the away mission as the gateway is blocked by an invisible wall.
Supposedly there's a ghost spawner for the bartender, but he just spawns catatonic.

@MMMiracles

**Comment by ChangelingRain** [comment]
away missions aren't real la la la

**Comment by kevinz000** [comment]
I'll fix this later yell at me if I don't same for the other one.

**Comment by ShizCalev** [comment]
@kevinz000 yelling

**Comment by PraiseRatvar** [comment]
@kevinz000 YELLING MORE

but away missions aren't real so idk???

**Comment by DoctoreMad** [comment]
WHy is this still open

**Comment by Cyberboss** [comment]
Can't have multiple milestones TT
