### ISSUE TITLE
Can't teleport to Zlevel 2 beacons now

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#15751]
### What is the problem?

Usually if I place a beacon on the shuttle I can still teleport to it even if I'm left behind or thrown out the shuttle for whatever reason. Now it seems I can't.
### Why is it a problem, or what should have happened?

Teleporting onto the escape shuttle is a good last resort for people who miss the bus out, or even a pod. It makes a good way to narrowly complete objectives or just survive if you're unlucky or slow.
### How can the problem be reproduced?

Just put a beacon on the shuttle and try to set tele to it after it leaves.
### What revision did the problem happen on? (Helpful, but not required)

Not sure but it was probably recent, like within last week or two.

**Comment by duncathan** [comment]
fucking z2 checks

**Comment by ChangelingRain** [comment]
reasons shuttle transit areas should be on a different zlevel++

**Comment by TheWiznard** [comment]
maybe related, but if you build a separate teleporter on the shuttle and link it with another one on station while both are in gate mode it works fine
