### ISSUE TITLE
Trays can display sprite with food on them when they are empty

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#15776]
### What is the problem?

See title
### Why is it a problem, or what should have happened?

The empty sprite should be displayed
### How can the problem be reproduced?

Not sure, perhaps has to do with custom foods? The item in question was a burger.

**Comment by LanCartwright** [comment]
how it was produced:
put cooked buns on tray on table
attempt to add meat to bun

![image](https://cloud.githubusercontent.com/assets/13142400/13369075/cbb519f4-dce8-11e5-959e-b978f3194366.png)
![image](https://cloud.githubusercontent.com/assets/13142400/13369077/cff0fa9c-dce8-11e5-8672-3297b16fd8d4.png)

**Comment by kriskog** [comment]
I haven't been able to reproduce this, so lets assume its fixed.
