### ISSUE TITLE
Grab then harm is a hard combo to pull off

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#15777]
Due to how grabing works. seeing as this is sleeping carps bread and butter it needs to be changed

**Comment by duncathan** [comment]
Click, cycle intent hotkey, click
Why is it difficult? I'm probably missing something obvious

**Comment by TheNightingale** [comment]
Grabbing uses the hand you're using to punch them with, so you have to swap hands too.
With hotkey mode: click target, X (swap hands), 4 (intent), click again.
Without hotkey mode: click target, click 'swap hands', the target resists and kills you.

**Comment by xxalpha** [comment]
The real bug is the system that tries this shit with ss13's clunky controls.

**Comment by lzimann** [comment]
No longer an issue with the grab/pull refactor.

**Comment by ChangelingRain** [comment]
>phil just fixes issues accidentally
