### ISSUE TITLE
Invisible C4

### ISSUE THREAD

**Issue by Saegrimr** [tgstation/tgstation#15785]
### What is the problem?
C4 goes invisible when you place it on a space_heater

### How can the problem be reproduced?
Turn space heater on
Place C4 on space heater (With long timer for suspicion clearing long con)
Turn space heater off
C4 disappears

Probably works on other objects that change their sprite, can't think of any though.

**Comment by phil235** [comment]
the space heater's "on" overlay hides the c4.

**Comment by Incoming5643** [comment]
Anytime anything updates its overlays the C4 overlay is removed as a "rogue" overlay.

This is a bug as old as C4 itself, and there's probably a report for it somewhere in the oldest open issue reports

**Comment by Razharas** [comment]
All overlays are handled in overlays.cut() overlays += X kind of way
I told again and again and again that this is a bad practice and that we should store overlays instead of rebuilding overlay lists all the times of all objects
