### ISSUE TITLE
air injector item and consistency issues

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/tgstation#15789]
### What is the problem?

air injectors can't be built; to work around this you can connect pipes to them, however there does not seem to be a way to activate them and no gas is injected through them, causing me a ton of problems with my painstakingly constructed burn chamber.
### Why is it a problem, or what should have happened?

i should be able to build the things with my RPD or metal as an engiborg, and they should function when connecting with standard piping
### How can the problem be reproduced?

connect straight pipes to the air injector with arbitrary pressure; observe nothing happening

note: i connected the mix loop all the way from atmos to the misc testing lab's burn chamber to see if i could get some ridiculously high temperature. while building up my H/E loop so i could use it to heat canisters i realized air injectors were not possible to build which seems a little weird. to get around this i simply connected my pipe of infinite plasma at 4000 KPA to the air injector but nothing happened.

i was pretty miffed because the whole thing took the whole round RIP my dream ;_;

anyway these should be standard atmos equipment and they should be buildable and work; as is they are kind of snowflake and lack consistency. durandan said they are admin spawn only and i'm not sure why.

**Comment by KazeEspada** [comment]
Air injectors have to be linked to an atmos control computer to be activated.

**Comment by Cebasiz** [comment]
it seems weird that there isn't something so simple as 

>connect to pipe

>output to tile

i mean, you can use vents but it's generally a pain in the dick and you're SOL if there is no power or no air alarm.

can we get this thing added to the RPD? and changed so it's simpler to use?

**Comment by duncathan** [comment]
Oh we can sure add it the rpd; we'd just have to uncomment one line
Making it usable is another question
