### ISSUE TITLE
Space suit crates notify admins when they aren't supposed to

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#15808]
### What is the problem?

See title
### Why is it a problem, or what should have happened?

The dangerous var in packs.dm is supposed to not notify admins when set to FALSE (which is default) but for some reason space suit crates do; I looked into the code and I have no idea why this is happening
### How can the problem be reproduced?

Order a space suit crate, be admin, get notification

**Comment by tkdrg** [comment]
@neersighted
