### ISSUE TITLE
Atom instantiation in "in world" loops

### ISSUE THREAD

**Issue by Menshin** [tgstation/tgstation#15818]
@AnturK More a reminder than anything else.

Atom instantiation in a `for var in world` loop is dangerous and should be avoided, since the `world` node is not duplicated in the loop and updated for each instanciation (i.e during the loop, shifting the looping `var`).

`World` consist of three parts :
- first come `mobs` (addresses  `0x3.....`)
- then are `objs` (addresses `0x2.....`)
- finally are `turfs` (addresses `0x1.....`)

So :
-  anything created by a `mob` proc _should_ be safe.
- `objs` and `turfs`  created by an `obj` proc _should_ be safe
- `turfs` created by a `turf` proc _should_ be safe
- any other instantiation mess with the `in world` loop

This is currently happening in the code, during `objs` initialisation for `/landmarks/corpsespawners`, leading to intermittent runtimes at server startup.

**Edit** : this also means that an atom cannot spawn an atom _of the same type_ in a `for var in world` or it will forever loop.

**Comment by RemieRichards** [comment]
not a PR perse, but technically PRs are issues so butts.

**Comment by optimumtact** [comment]
is it safe if your loop is like the following:

    for var/type/path/B in world:
        B.creatething()

or would it ideally need to be

    for var/type/path/B in uniquelist
        b.CreateThing()

**Comment by Menshin** [comment]
>for var/type/path/B in **world**
B.creatething()

is unsafe, the type pathing not preventing the ```world``` structure from being updated.

>for var/type/path/B in **uniquelist**
    b.CreateThing()

_is_ safe, since Byond seems to make a copy of the list before the loop is started (which it doesn't do for ```world```).

**Comment by optimumtact** [comment]
Err this isn't a bug and should go in the coding forum really
