### ISSUE TITLE
Cyborgs without powercells can still control doors

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#15831]
self explanatory

**Comment by Cebasiz** [comment]
they can also still talk, which is also probably a bug(?)

**Comment by phil235** [comment]
That's because airlock window doesn't use tgui or nanoui.

**Comment by Aloraydrel** [comment]
also binary as well

**Comment by Buggy123** [comment]
Why don't we just make batterylessness cause cyborgs to 'sleep'?

**Comment by YakumoChen** [comment]
Honestly this isn't a big problem, it's already a huge hassle to get people to pay attention to you when your cell is out and it really, REALLY sucks when someone removes your cell 4noraisin / gets killed while changing cells / a billion other things

**Comment by YakumoChen** [comment]
Unless I'm wrong and this is about door gui and not door-bumping to open.

**Comment by Dorsisdwarf** [comment]
the GUI access could not be reduced and by now powerless borgs being able to scuttle away is a feature
