### ISSUE TITLE
remove mutants REMOVE MUTANTS AI objective doesn't work?

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#15833]
### What is the problem?

I was a traitor AI with the "No mutant humanoids on escape shuttle" objective. I was about 99% sure there were only humans on the shuttle, as I didn't see anyone with an obvious name that suggested otherwise. I failed the objective anyway
### Why is it a problem, or what should have happened?

muh greentext, really hard as AI to determine who is ''mutant'' (especially since hardsuits and such hide obvious mutant traits like lizard tails) to do the objective without just hijacking the shuttle with nobody onboard so there can't be mutants anyway. I was trying to avoid that and managed to survive to round end after spacing the only player I could reasonably be sure was not human (the ligger clown) but for some reason I couldn't trigger greentext anyway and admins wouldn't delay long enough to figure out.
### How can the problem be reproduced?

Not sure, but I think the objective needs some serious testing with various traitor items and maybe genetics or viro? I was blind on the shuttle due to a different bug but I couldn't see any non-humans on the shuttle after I ghosted roundend.
### What revision did the problem happen on? (Helpful, but not required)

IMO something like a Race HUD (or a HUD to differentiate biological humans from nonhumans) might help solve this issue, maybe make it a Malf Module (since it'd likely be a problem on standard asimov, but maybe not), but if the objective is buggy anyway it might not help.

**Comment by Iamgoofball** [comment]
You forgot the revision.

**Comment by lordpidey** [comment]
@cyberboss I believe this objective was removed, so it's irrelevant.
