### ISSUE TITLE
New Meta: Monkey Then Hitspam

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#15848]
### What is the problem?

During transition from monkey to human, people can hitspam like pre Wooden Barricade-Fix
### Why is it a problem, or what should have happened?

You should not be able to hitspam.
### How can the problem be reproduced?

monkey someone then hit them during their transition
### What revision did the problem happen on? (Helpful, but not required)

The one currently running on sybil [2/29/16]

**Comment by bgobandit** [comment]
@ExcessiveUseOfCobblestone this appears to be fixed
