### ISSUE TITLE
Carded AIs can suicide to prevent the "Steal functional AI" objective from being fulfilled

### ISSUE THREAD

**Issue by tkdrg** [tgstation/tgstation#15845]
This could probably be fixed by making it accept suicided/braindead/catatonic AIs as greentext (as long as it happened post-carding).

**Comment by Lumipharon** [comment]
policy free week aside, it's against policy to do this.

**Comment by Iamgoofball** [comment]
@tkdrg 
with assassinate/protect/maroon objectives the game just gives you greentext for suicides

might as well follow suit and make it greentext if the AI suicides

**Comment by Anonmare** [comment]
AI shouldn't suicide if it's under Asmiov (Yeah I know it's policy-free week but Law 3). If it suicides, you can put it in an integrity restorer which can restore an AI regardless of whether there's a player in it or not.

**Comment by Dorsisdwarf** [comment]
Yeah, any AI that does this should be ahelped then banned

**Comment by Cyberboss** [comment]
@lzimann
