### ISSUE TITLE
Janicart/secway are slower than usual.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#15863]
This could possibly be intended but it would seem odd considering you're losing a hand slot to drive them. They're slower than normal running speed and make it rather useless to pilot.

**Comment by YakumoChen** [comment]
not a bug, go harass Xenobio for red slime cores

**Comment by Durkel** [comment]
Cool ad hominem bro. But the janicart is currently slower than walking, which wasn't the case even after the red slime core pr was merged. Something happened to their movespeed.

**Comment by YakumoChen** [comment]
Pretty sure this is the case though, I adminPM'd about this problem once and got reply that they were intentionally slowed down.

**Comment by Mervill** [comment]
@optimumtact closeable - no longer an issue
