### ISSUE TITLE
ayyductors can use a megaphone to speak

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#15865]
### What is the problem?
grey ayylien race can speak using a megaphone
### Why is it a problem, or what should have happened?
Aliens only use hivemind to speak and cannot actually speak words so this basically bypasses it
### How can the problem be reproduced?
Use a megaphone as a ayylien

**Comment by AdamElTablawy** [comment]
mimes can do this too

**Comment by Buggy123** [comment]
The megaphone is so loud it amplifies what you say before it even leaves your brain.

**Comment by ShadowDeath6** [comment]
It's not actually talking, I think deaf people can hear megaphones too.  It's some weird item action.
