### ISSUE TITLE
Assteroid station holodeck doesn't work

### ISSUE THREAD

**Issue by matillo** [tgstation/tgstation#15860]
### What is the problem?

Holodeck computer does nothing when activated.
### What revision did the problem happen on? (Helpful, but not required)

I'm not sure the asteroid station has ever had a working holodeck, it's a pretty rarely played map though maybe it never met the requirements when someone modded it in.

**Comment by PKPenguin321** [comment]
might be a dupe?

**Comment by optimumtact** [comment]
ass is gone walkabout

**Comment by optimumtact** [comment]
thanks @Shadowlight213

**Comment by Mervill** [comment]
@optimumtact closeable, rip asteroid station.
