### ISSUE TITLE
pAI radio configuration screen blank

### ISSUE THREAD

**Issue by matillo** [tgstation/tgstation#15861]
### What is the problem?

There is no radio interface for pAI anymore
### Why is it a problem, or what should have happened?

I assume I should have a radio configuration interface.
### How can the problem be reproduced?

The pAI software interface has a 'Radio Configuration' page which should not be empty.

**Comment by GunHog** [comment]
@neersighted Likely a result of the TGUI conversion. Perhaps the entire interface could be made TGUI!

**Comment by neersighted** [comment]
Easy enough fix, just need to call interact() on the internal radio... However, the more elegant approach would be converting the entire UI. I'll see what I can do as soon as I finish polls.

**Comment by kriskog** [comment]
This has been fixed
