### ISSUE TITLE
Dead Mob's suicide status doesn't appear upon examination if debrained

### ISSUE THREAD

**Issue by phil235** [tgstation/tgstation#15868]
### What is the problem?
Examining a dead debrained human doesn't show whether the human commited suicide or not

### Why is it a problem, or what should have happened?
You can't tell whether you should try to help this dead human back to life or not.

### How can the problem be reproduced?
Commit suicide with a telescopic baton. Then examine the corpse.

### What revision did the problem happen on? (Helpful, but not required)
current.

**Comment by lordpidey** [comment]
Can you put a good brain in a suicide corpse, and bring the body back to life?  If so, I'm not seeing the major problem here, as brainless corpses are shown on examine.

**Comment by phil235** [comment]
@lordpidey I'll need to test that.

**Comment by YakumoChen** [comment]
the soul is in the brain, not the body, so if you take the brain out you're just left with a soulless corpse, regardless of how the brain died.

**Comment by lordpidey** [comment]
Let's close this.  Suicide is tied to a mind, not to a body.
