### ISSUE TITLE
Monkey Ventcrawling Broken

### ISSUE THREAD

**Issue by Whalen207** [tgstation/tgstation#15877]
### What is the problem?
Monkeys cannot ventcrawl after removing clothing.

### Why is it a problem, or what should have happened?
Monkeys should be able to (to my knowledge) ventcrawl if they are nude. (Honestly you should let them ventcrawl as long as they're not wearing a backpack, but that's like... my opinion, man.)

### How can the problem be reproduced?
1. Get turned into a monkey using a monkey SE injector, clean.
2. Attempt to ventcrawl. Should work fine.
3. Wear full clothing and a backpack for a little while. Enjoy slipping people.
4. If you are not robusted by now, attempt to ventcrawl. You should not be able to, given you are wearing stuff.
5. Remove all articles of clothing. Attempt to ventcrawl. You cannot because of a bug.

### What revision did the problem happen on? (Helpful, but not required)
Whatever Sybil's running at 6:10PM CST March 1st 2016

**Comment by phil235** [comment]
Can't reproduce.

**Comment by optimumtact** [comment]
old cannot reproduce
