### ISSUE TITLE
Reconstructing SMES is bugged

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#15874]
### What is the problem?

It was lowpop and I was RD Acting Captain. No engineers (though someone did the tesla shortly before I worked on my idea) so I got the idea to reconstruct SMES with research's fully charged protolathe Super cells. Turns out it worked! 
### Why is it a problem, or what should have happened?

The SMES weren't sending out power... So then the tesla got loose, because the emitters got no power.
### How can the problem be reproduced?

Decon and rebuild the SMES without moving the frames.

**Comment by tkdrg** [comment]
@Razharas

**Comment by ShadowDeath6** [comment]
Constructed SMES start with 0 power upon consctruction, it's been that way for as long as I remember because it would be kind of OP if you just spam fully charged SMES everywhere and power sinks are overloaded in like 5 seconds.

**Comment by YakumoChen** [comment]
No, they keep the cell charge. If you build them with fresh cells, they start at full power. The problem was that they weren't putting power in the wires even upon construction. The power net had zero watts.

**Comment by KazeEspada** [comment]
Maybe the cells failed? Protolathe puts out unreliable parts.

**Comment by YakumoChen** [comment]
I tested it later with an RPED and they were fully charged and cranking out power fine. Also all four of them were failing all at once, that's literally 16 cells that would have to fail.

**Comment by phil235** [comment]
Still happening.

**Comment by Jordie0608** [comment]
\<Frozenguy5> close this
\<Frozenguy5> i tested it just now
\<Frozenguy5> it works
