### ISSUE TITLE
Brainslug bursting ejecting a brain somehow deletes the changeling

### ISSUE THREAD

**Issue by Incomptinence** [tgstation/tgstation#15883]
### What is the problem?

While working xenobiology I was waiting on my sentient headslug to burst from a corpse and when he did the monkey was there for a second then vanished. My xeno maid pointed out the brain from the organs dropping from the corpse and so I just picked it up. Could have been a debrained body I dunno was an unknown from genetics off cuts but since it dropped a brain I don't think so.
### Why is it a problem, or what should have happened?

A changeling monkey should have come out and continued to exist or at least died on the spot it deleting itself was pretty immersion breaking or at least that is what it looked like, if it gibbed twice that's more confusing. I have had brainslugs successfully emerge as changelings so I think it comes down to the brain. Found no other past reports of it so I guess it is tied to the new organs dropping during gibing change.
### How can the problem be reproduced?

Infect bodies with brainslug eggs until a brain pops out you might want to edit the process to happen more quickly it is a 5 minute wait or so. I was on the shuttle if that matters.
### What revision did the problem happen on? (Helpful, but not required)

It was on the 29th of February or so give or take gmt +10 not sure as to the exact revision saw this format and decided to go back to playing at the time.

**Comment by phil235** [comment]
The changeling isn't deleted, it's moved into null space.

**Comment by phil235** [comment]
Can't reproduce.

**Comment by Incoming5643** [comment]
It's because the client goes to the brain, it basically steals away the ling to be's mind before it can be incorporated in the monkey ling.

but it only happens if the brain RNG survives.

**Comment by phil235** [comment]
@Incoming5643 It still doesn't explain why the monkey would be deleted after a second.

**Comment by Incomptinence** [comment]
I would advise using admin tools to test it since it involves a round of work including random chance on what slimes you get in a timely fashion, random spawns, random organ drops and a considerable wait.

Maybe it was a debrained corpse? I dunno was a pretty messed up unknown.

**Comment by AlexanderUlanH** [comment]
I reproduced it with a catatonic corpse and an adminspawned human. The resulting monkey didn't get deleted, but went to nullspace.

**Comment by phil235** [comment]
@AlexanderUlanH Did you make sure that it wasn't simply a lack of perspective update? Because it's also a bug that happened when I tried to reproduce this issue and that I mistakenly thought was null space. (Check the mob's loc in VV)

**Comment by AlexanderUlanH** [comment]
You're right, that was it.

**Comment by Incomptinence** [comment]
So you've reproduced it then? Golly I don't see how I could have properly reported this considering it basically required admin tools to even comprehend.

**Comment by phil235** [comment]
No, it's not reproduced. There's an additional unrelated bug that I and Alexander mistook for your bug.

**Comment by ShizCalev** [comment]
Will close in a week without another repo.
