### ISSUE TITLE
The Listening Post floor safe is broken

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#15894]
Cracked it, got the three codes, tried to open it, said it was still locked. I've seen other people be unable to hack it as well.

**Comment by Zilenan91** [comment]
Might not be a bug but stay tuned, gonna try testing it soon (tm)

**Comment by WJohn** [comment]
Not a map issue, it seems. Could possibly be related to #12474?

**Comment by PKPenguin321** [comment]
Yep, a dupe

**Comment by Mervill** [comment]
@optimumtact duplicate of #12474
