### ISSUE TITLE
martial art data not stored in mind

### ISSUE THREAD

**Issue by hornygranny** [tgstation/tgstation#15918]
### What is the problem?

Learned martial arts (sleeping carp) stored as a variable in the body
### Why is it a problem, or what should have happened?

If you die and are cloned, you do not retain your martial art
### How can the problem be reproduced?

Kill and clone someone who has used a martial art scroll
### What revision did the problem happen on? (Helpful, but not required)

9d66dad13f54c5198d43d712c604f16bf80e93ac

**Comment by Zilenan91** [comment]
Isn't a lot of martial arts just reflex? So if you get a new body wouldn't that reflex dissapear?

**Comment by hornygranny** [comment]
in terms of balance this makes a carp scroll a horrible investment for 17TC
in terms of fluff, muscle memory is a brain function so assuming our clones are perfect copies no

**Comment by Zilenan91** [comment]
They aren't perfect copies tho, they have massive genetic deformation unless the cloner is upgraded.

**Comment by PKPenguin321** [comment]
>muh fluff

ignore zileposters


this issue also means that if you kill a traitor with martial arts and put a loyal crewmember's brain into his corpse, they get martial arts

**Comment by KazeEspada** [comment]
store martial arts in both

**Comment by Supermichael777** [comment]
not how it works kaze.
