### ISSUE TITLE
MAP MERGER IS FUCKING BROKEN

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#15922]
### What is the problem?
IT DOES NOT MERGE IN EITHER DMM OR TGM MODE
### Why is it a problem, or what should have happened?
LOL SORRY CAN'T MERGE YOUR PR AUTOMATICALLY :^))))))))))))))))))))))))))))))))))
### How can the problem be reproduced?
1. try to merge a map
2. watch as the diffs are fucked and unmergable no matter what
3. cry
4. try to release stress on www.pornhub.com
5. cry again

### What revision did the problem happen on? (Helpful, but not required)
the current shit and it wasnt on  the server

**Comment by Iamgoofball** [comment]
@xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha @xxalpha

**Comment by Iamgoofball** [comment]
OH ALSO THE JAVA ONE THROWS ERRORS AND CLOSES

**Comment by optimumtact** [comment]
![this woman has lost her composure](http://static2.gamespot.com/uploads/scale_medium/1551/15517698/2905318-3919709597-13840.jpg)

**Comment by 9600bauds** [comment]
Stop celtposting

**Comment by Buggy123** [comment]
I told you, but nooooo, no one listened.

**Comment by xxalpha** [comment]
I can't do anything with this report.

**Comment by xxalpha** [comment]
It works for me.

**Comment by Iamgoofball** [comment]
idk man it keeps doing 50 bazillion line changes even if I tgm to dmm or tgm to tgm box

**Comment by xxalpha** [comment]
That's intended.

**Comment by Iamgoofball** [comment]
obviously it isn't because BOX IS ALREADY TGM, AND THEN TRYING TO MAP MERGE WITH TGM BAT DOESNT FUCKING WORK

**Comment by xxalpha** [comment]
This is a non issue.

**Comment by Iamgoofball** [comment]
ur mom is a non issue L O L

**Comment by xxalpha** [comment]
Thanks.

**Comment by Steelpoint** [comment]
Is this still a issue?

**Comment by optimumtact** [comment]
no
