### ISSUE TITLE
Collectible hat crate contains all collectible hats.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/tgstation#15956]
### What is the problem?
I received too many hats, so I denied the crate. Apparently there was nothing wrong so it deduced the crates cost from the points sending cargo balls deep into the red.

### Why is it a problem, or what should have happened?
Really fucks with the who papers please minigame that cargo has that already punishes super hard for fucking up.

It is only supposed to deliver three hats.

### How can the problem be reproduced?
Order a collectible hat crate.

### What revision did the problem happen on? (Helpful, but not required)
https://github.com/tgstation/-tg-station/commit/2b41e7da264089dffddd2c609fcccc05a9190730

Either caused by goofballs stock exchange or neersighted's rewrite.

**Comment by YakumoChen** [comment]
>too many hats

why not just give them to the crew or something?

**Comment by octareenroon91** [comment]
The hat supply doesn't match the manifest. Kaze got screwed for cargo points over an erroneously-rejected hats order.

There's no live code to actually randomize the contents in a `/datum/supply_pack/misc/randomised`
https://github.com/tgstation/-tg-station/blob/master/code/modules/cargo/packs.dm#L1203
