### ISSUE TITLE
Whibyl IRC bot triggers its own PR lookup

### ISSUE THREAD

**Issue by Chocobro** [tgstation/tgstation#15959]
`[12:57] (TheGhostOfWhibyl2) [-tg-station] Impisi opened pull request #15958: Improvised Shell Rework Attempt 2 (master...ImprovisedShellCharges) https://github.com/tgstation/-tg-station/pull/15958
[12:57] (TheGhostOfWhibyl2) https://github.com/tgstation/-tg-station/pull/15958 - 'Improvised Shell Rework Attempt 2' by Impisi`

@MrStonedOne

**Comment by Impisi** [comment]
THE SUMMONING

**Comment by MrStonedOne** [comment]
mloc runs that bot

**Comment by Chocobro** [comment]
this was fixed
