### ISSUE TITLE
Sniper rifle rounds PHASE through turrets.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#15967]
### What is the problem?

Firing a sniper rifle at a turret will have the bullet phase right through.
### Why is it a problem, or what should have happened?

You don't seem to deal any damage, I emptied two magazines into one and, despite there being sparks once or twice, it didn't die. Turrets die in two shots from a revolver, which are weaker than sniper rifle rounds.
### How can the problem be reproduced?

Spawn a turret (ai) and a sniper rifle, empty a few clips and be unable to kill it.
### What revision did the problem happen on? (Helpful, but not required)

Server revision compiled on: 2016-03-07

**Comment by RemieRichards** [comment]
you are aware there's 3-4 different ammo types for snipers right?
Which one did you fire.

**Comment by WJohn** [comment]
I used the default.

Also scratch that, it did ONE damage when it phased through.

**Comment by Zilenan91** [comment]
Turrets are really fucking weird in general. I've acided them before as a xeno, making them dissapear, only to zap back into existence moments later.

**Comment by phil235** [comment]
turret or turret_cover?

**Comment by Zilenan91** [comment]
The ENTIRE turret, it completely dissapeared then reappeared a few seconds alter.

**Comment by WJohn** [comment]
Turrets have been buggy, broken, unintuitive pieces of shit in every iteration since the dawn of time.

**Comment by kevinz000** [comment]
@lzimann definitely works properly now.
