### ISSUE TITLE
Bug: Delayed reaction to burn damage

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#15965]
### What is the problem?

Delayed reaction to burn damage. I get shot by a guy with a laser gun, in the chest and head. My health heartbeat does not change, but I show damage to the head and chest. I limp over to medbay storage and apply ointment, first to my chest, which fails because I am chest augmented, and then to my head. Once the ointment is applied, I drop into crit, which I assume is the game "realising" that I should be in crit.
### Why is it a problem, or what should have happened?

My health should have updated as I was lasered, dropping into crit appropriately, rather than "catching up" and realising as I apply ointment.
### How can the problem be reproduced?

I had xray implant, breathing tube, mining hardsuit, chest augmentation, no chemicals in my system that I was aware of.
### What revision did the problem happen on? (Helpful, but not required)

Server revision compiled on: 2016-03-07
2b41e7da264089dffddd2c609fcccc05a9190730

**Comment by duncathan** [comment]
Isn't burn damage DoT? Maybe I'm mistaken

**Comment by coiax** [comment]
It was from a laser gun. Pretty sure those aren't DoT.

**Comment by phil235** [comment]
Probably a runtime. Did you get shot once or multiple times?

**Comment by coiax** [comment]
Multiple  times.

**Comment by coiax** [comment]
This was a weird edge case, and without it happening again, I doubt we'll be able to find out what it was. Probably some sort of bug or delay in damage.
