### ISSUE TITLE
Fire blob ignores flameproof hardsuit

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/tgstation#15971]
[Everyone]: # (Please fill in your information on the line AFTER the header.)

### What is the problem?
Fire blob ignores flameproof hardsuit. Both blob attacks, and the spore smoke, but the blobbernaut attacks do not penetrate.

### Why is it a problem, or what should have happened?
I die from blob I should smash easily due to having the ultimate counter, the atmos rig.

### How can the problem be reproduced?
Make flame blob. Put on atmos rig. Setup internals and gloves. Watch the blob burn your skin through the suit when it attacks you.

### What revision did the problem happen on? (Helpful, but not required)
[If you're including this]: # (Type find-server-revision ingame to find it. "Current" isn't helpful.)

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by Zilenan91** [comment]
If atmos rigs were immune to this blob it would be hella unbalanced. It's why chemblobs happened in the first place, because Miners shat all over blobs with their melee resistance.

**Comment by phil235** [comment]
if I remember correctly, hardsuits give you a 50 % resistance to blob's chemical attack. Not being able to completely block the attack is intended.

**Comment by WJohn** [comment]
I'd prefer it if it were actually possible to counter the blob's attacks so it was actually forced to change chemicals. Right now they're functionally almost all the same, with a few aesthetic differences, you don't actually need to change chems unless you get one of the few really bad ones.

**Comment by ChangelingRain** [comment]
Yeah this isn't a bug and I can't really easily fix it without a lot of shit checks.

As an aside, I think all the blob types should at least be able to kill somebody without having to swap chemicals, because it feels *awful* to play things with no offensive power at all.

**Comment by ChangelingRain** [comment]
Also I should note that chemistry can cuck half of the blob types with a few chemicals
