### ISSUE TITLE
When carded as AI if the person holding you is gibbed by a cult god game crashes and you can respawn into the game as a new role

### ISSUE THREAD

**Issue by icecreamcohn** [tgstation/tgstation#15974]

**Comment by phil235** [comment]
Can't reproduce, need more details. was the person holding the aicard a human? Was the card in his hand or his backpack?

**Comment by phil235** [comment]
Can't reproduce, need more details.

**Comment by PraiseRatvar** [comment]
@Dorsisdwarf add needs test tag

**Comment by ShizCalev** [comment]
This was fixed.
