### ISSUE TITLE
Chameleon Gasmasks don't block identity.

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#15970]
### What is the problem?

Chameleon gas masks don't block identification.
### Why is it a problem, or what should have happened?

Chameleon gasmasks should block identification.
### How can the problem be reproduced?

Put on a chameleon gaskmask, remove ID.

**Comment by Iamgoofball** [comment]
Odd.

It works if you have an ID on or a replacement ID, because I've had a cigar chameleon mask on with a fake ID and passed for the person before.

**Comment by francinum** [comment]
Yeah, but without an ID it just shows your face.

**Comment by XDTM** [comment]
Tested, they do block identity
