### ISSUE TITLE
/obj/effect/forcefield/cult has no hit delay.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#15975]
You can spam hitting it super fast.

**Comment by ChangelingRain** [comment]
So does the normal forcefield, then.
Not that it matters, because it's indestructible.

**Comment by Shadowlight213** [comment]
@changelingrain
It does matter because you can spam the attack message.

**Comment by optimumtact** [comment]
Does anyone else see the message or are you just spamming yourself?

**Comment by Shadowlight213** [comment]
@optimumtact It's a visible message, so everyone around you sees it. I was observing when I first saw this happen.

**Comment by Shadowlight213** [comment]
@phil235 eta on that attackby pr? This is still an issue.

**Comment by phil235** [comment]
@Shadowlight213 I've tried to find the time and motivation to finish it, but I'm not sure anymore whether I'll  actually finish the PR to be honest. @optimumtact You should probably reopen your PR #15995 and have it merged now, sorry about the delay.

**Comment by phil235** [comment]
Already fixed actually.
