### ISSUE TITLE
Plasmamen in Fire-immune hardsuits are on fire forever

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#15985]
### What is the problem?

Plasmamen can put on an atmos or CE hardsuit and will indefinitely stay on fire, it can't be extinguished. This has no effect on their health because the suit is fireproof,
### Why is it a problem, or what should have happened?

Lets plasmamen grief by setting everyone they touch on fire without any consequence.
### How can the problem be reproduced?

plasmemes

**Comment by TheNightingale** [comment]
I'm pretty sure you can do this with some welding fluid and a lighter anyway. Maybe people running around setting fire to things is a problem with the players?

**Comment by PKPenguin321** [comment]
>I'm pretty sure you can do this with some welding fluid and a lighter anyway

You'd run out of firestacks eventually, plasmamen get infinite firestacks though

**Comment by KazeEspada** [comment]
You never run out of firestack unless someone douses you.

**Comment by PKPenguin321** [comment]
or until you bump enough people, whereas with this you can just run through halls forever

**Comment by YakumoChen** [comment]
No, I tried putting the guy I saw out, he just relit immediately.

**Comment by octareenroon91** [comment]
maybe just use suit permeability_constants instead of istype bollocks?

**Comment by Tacolizard** [comment]
this should be closed

**Comment by octareenroon91** [comment]
yeah weird
