### ISSUE TITLE
Magic Mirror Synths Beepboop instead of Saying

### ISSUE THREAD

**Issue by Boredone** [tgstation/tgstation#15986]
### What is the problem?
Synths made via magic mirror do not inherit saymod, and maybe other things

### Why is it a problem, or what should have happened?
It means a synth wizard is rather easy to detect as non-human if they don't yell all the time, instead of requiring damage/lasering/whacking/etc first to knock off some synthflesh.

### How can the problem be reproduced?
Go to wizard den, use magic mirror to become a synth/military synth, talk and beepboop instead of say or whatever.

**Comment by TheNightingale** [comment]
Isn't that the point? It's the downside to being a cool robot.
