### ISSUE TITLE
Sawn off Riot shotgun sprite

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/tgstation#16049]
### What is the problem?
Sawn off uses non-sawn off.
### Why is it a problem, or what should have happened?
Sprite should have updated to sawn off.
### How can the problem be reproduced?
Hold riot shotgun.
saw off with circular saw
### What revision did the problem happen on? (Helpful, but not required)
Yesterday gang round before 00:00 GMT.

![image](https://cloud.githubusercontent.com/assets/13142400/13714374/19e6d8fa-e7c6-11e5-8ff4-a6acd7577173.png)

**Comment by Boredone** [comment]
Copy of #15799 but this one seems more detailed maybe?

**Comment by Zilenan91** [comment]
Same bug as the one that effects double-barreled shotguns.

**Comment by LanCartwright** [comment]
Sounds like it. Damn, this will probably delay the idea I had for the mosin sawn off (obrez).

**Comment by Shapsy** [comment]
What, @zilenan91 I literally posted in that issue "Yeah is that the one about sawing them off because it happens with the riot shotguns too" and you said it wasn't
