### ISSUE TITLE
Plasmaman Wizards start off on fire

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#16094]
[Everyone]: # (Please fill in your information on the line AFTER the header.)

### What is the problem?
Wizards of players who have race set to plasmaman start as a plasmaman
### Why is it a problem, or what should have happened?
They start on fire and die
### How can the problem be reproduced?
Set race to plasmaman, get wizard, die
### What revision did the problem happen on? (Helpful, but not required)
[If you're including this]: # (Type find-server-revision ingame to find it. "Current" isn't helpful.)

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by Incoming5643** [comment]
The true hardmode persists between rounds

**Comment by AdamElTablawy** [comment]
feature
