### ISSUE TITLE
PAI's in mules have trouble after teleporting.

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/tgstation#16090]
### What is the problem?

A PAI in a mule had trouble moving after teleporting to the AI sat, after he came though he was set to off, I set him back to on and he still couldn't move.
### Why is it a problem, or what should have happened?

PAI wishes to move.
### How can the problem be reproduced?

Try teleporting to the AI sat as a PAI in a mule via the station teleporter and see if you can move.

**Comment by AnturK** [comment]
Can't reproduce.
