### ISSUE TITLE
Scrubbers can't be set to scrub certain gasses. 

### ISSUE THREAD

**Issue by Saegrimr** [tgstation/tgstation#16098]
[Everyone]: # (Please fill in your information on the line AFTER the header.)

### What is the problem?
Scrubbers only filter CO2, N2O and Plasma

### Why is it a problem, or what should have happened?
Can't scrub O2 for plasmameme safe regions, or nefarious traitor usages to choke people. Or Nitrogen.

### How can the problem be reproduced?
This is default behavior. Would like more functionality.

**Comment by duncathan** [comment]
Pretty easy to do this now with listmos. It's been on my to-do list for a while.

**Comment by Aloraydrel** [comment]
Please make this a dream come true

**Comment by lordpidey** [comment]
Do you think the scrubbers should be able to do this by default, or should it require hacking/emagging?

**Comment by Buggy123** [comment]
By default, definitely. You can already depressurize a room with air-alarm-scrubbers so this would only allow you to remove oxygen without completely depressurizing the room, not that big of a difference.

**Comment by lordpidey** [comment]
Buggy123,  What about this situation:
If you can put plasma in the distro, if you could filter just the nitrogen out of the air, that would create a fairly potent burnmix.

**Comment by Anonmare** [comment]
I seem to recall being able to scrub O2 in the past.
Would be nice for quietly rendering rooms uninhabitable.

**Comment by kyrahabattoir** [comment]
wouldn't plasmamen be fine in pure nitrogen too? would be prettier.

**Comment by duncathan** [comment]
They'd need internals

**Comment by neersighted** [comment]
This is very easy, I'll add it to the alarm/UI in a bit.
