### ISSUE TITLE
Crowbaring up flooring removes lube/lava on it.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#16102]
### Why is it a problem, or what should have happened?

Crowbaring up flooring removes lube/lava on it.
### How can the problem be reproduced?

Spray lube,Crowbar floor, ?????,gg.
### What revision did the problem happen on? (Helpful, but not required)

39e356c55cf6223162814135ba54512af7481cac

This is has been in for awhile, but after watching someone just crowbar lubed tiles and ignore it all completely I thought I'd report it. You can do this for the floor is lava event as well, effectively neutering it.

**Comment by AdamElTablawy** [comment]
Was this not intentional?

I mean, lube goes on the top of the floor tile. Then you remove the floor tile, why does lube transcend dimensions and seep through metal to the plating?

**Comment by Durkel** [comment]
Well for one you're picking up a tile that has liquid on it, unless it's magical the liquid is going to run off the sides of it. Secondly, Have you ever stuck a crowbar in lava and pulled up the floor underneath it?

**Comment by AdamElTablawy** [comment]
the lava is obviously a bug.

Lube? I dunno, it wouldn't coat the tile, just get 1-2 drops of lube

**Comment by lzimann** [comment]
F E A T U R E

**Comment by Durkel** [comment]
People crow barring up lube is becoming much more prominent, Just saying.

**Comment by bgobandit** [comment]
this also is the case for freon
