### ISSUE TITLE
Heat absorbtion issue with engine floors.

### ISSUE THREAD

**Issue by kyrahabattoir** [tgstation/tgstation#16126]
### What is the problem?

The TEG Combustion chamber can barely hold heat.
### Why is it a problem, or what should have happened?

The hot co2 produced by plasma combustion should stay hot longer than a couple minutes
### How can the problem be reproduced?

On ministation, prepare a burn mix and light it on fire and notice the rapid temperature drop as soon as the fire is out.
### What revision did the problem happen on? (Helpful, but not required)

Tested on commit: 5fb22a9116330c1dd4c064cab9b34c921002511c

Tested some of it with Dunc, it appears that engine floor heat capapcity is almost infinite so any temperature increase on engine floors is essentially rounded away, leeching the temperature from the hot gas rapidly despite it's low thermal conductivity.

**Comment by duncathan** [comment]
Solution: find a heat capacity for engine floors which allows it to change temperature but prevents melting

**Comment by kyrahabattoir** [comment]
All turfs have two properties:
Heat capacitance -> How much heat they can absorb.
Thermal conduction -> How well they conduct heat.

Currently, engine floors have a very low thermal conduction (we are talking better than rockwool) and a near infinite heat capacity. As a result, even with their very low thermal conduction, they trap a massive amount of heat. However the resulting temperature increase is so minuscule that it is rounded down to zero.

Result: They suck heat away without actually heating up.

**Comment by Buggy123** [comment]
I set up a PR that changes reinforced floors to have a conduction of 0, all other floors are normal. Since they're only used in a few select areas, this'll make all burn rooms heatproof and make it easy to produce perfectly insulate rooms, without messing up the rest of the station.
