### ISSUE TITLE
Prone people don't show up in the right-click menu

### ISSUE THREAD

**Issue by freerealestate** [tgstation/tgstation#16159]
### What is the problem?

Prone people don't show up in the right-click menu
### Why is it a problem, or what should have happened?

It means you need to examine them with shift+click
### How can the problem be reproduced?
1. Rest
2. Right-click self
### What revision did the problem happen on? (Helpful, but not required)

314afedfef3bc267d7c18fb896e7023d7fd4c926

**Comment by hornygranny** [comment]
does not reproduce for me

**Comment by freerealestate** [comment]
![](http://i.imgur.com/K1FZeiU.png)

**Comment by MrStonedOne** [comment]
byond version including both major and minor number, there is a change that could be at play.

**Comment by freerealestate** [comment]
What about it?

**Comment by Mervill** [comment]
@optimumtact closeable - Not an issue in the 511 beta, and I imagine we'd be hearing about it if this was still an issue
