### ISSUE TITLE
Carp Scroll Exception

### ISSUE THREAD

**Issue by IvanIssaccs** [tgstation/tgstation#16185]
### What is the problem?

Probably more oversight that bug. You can still use flamethrowers with the carp scroll. 
### Why is it a problem, or what should have happened?

Seems a flamethrower is still a ranged weapon, so should not be viable to use with carp scroll?
### How can the problem be reproduced?

Using carp scroll and flamethrower.
### What revision did the problem happen on?

Current?

**Comment by PKPenguin321** [comment]
Not an issue imo

**Comment by xxalpha** [comment]
Fire punch
