### ISSUE TITLE
Plasmamen start with human internals box

### ISSUE THREAD

**Issue by LordJike** [tgstation/tgstation#16183]
### What is the problem?

Plasmamen start with internal boxes mean't for humans
### Why is it a problem, or what should have happened?

It's pretty self-evident, might be better to have a spare plasma tank and maybe also a spare suit (could double as a counter for retrovirus)
### How can the problem be reproduced?

By playing plasmaman, pretty much.
### What revision did the problem happen on? (Helpful, but not required)

Ever since plasmamen were implemented, I don't think I need to specify the build.

**Comment by kyrahabattoir** [comment]
Nanotrasen's typical lack of care for it's crew imho.
