### ISSUE TITLE
can't order books with SBN code

### ISSUE THREAD

**Issue by Grazyn** [tgstation/tgstation#16180]
### What is the problem?

Type book code in the library computer
### Why is it a problem, or what should have happened?

nothing happens

**Comment by Iamgoofball** [comment]
@liamlime

**Comment by balohmatevz** [comment]
@Iamgoofball ?

**Comment by optimumtact** [comment]
I'm not sure why you're tagging them

**Comment by bgobandit** [comment]
ok I have looked at this shit for literally hours and I cannot tell where it is going wrong. except that the printing code IS getting called, because the "Printer unavailable" error message (for when you do it too quickly) appears as normal. it's just that the book never spawns.

@MrStonedOne
