### ISSUE TITLE
Borgs cannot finish the 5 metal sheets part of the scooter.

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/tgstation#16193]
[Everyone]: # (Please fill in your information on the line AFTER the header.)

### What is the problem?
The borg can make the scooter frame but not finish the scooter.
### Why is it a problem, or what should have happened?
Expected to finish the frame and not get a "You need at least five metal sheets to make proper wheels!" error (i had well more than 5 metal)
### How can the problem be reproduced?
Be engineering borg, make scooter frame, attempt to finish scooter.

**Comment by GunHog** [comment]
Did you test this as human as well?

**Comment by Shad0vvs** [comment]
Phoebe did it right after me after i deconned some things to get her the metal and completed the scooter.

**Comment by PKPenguin321** [comment]
Possibly similar to https://github.com/tgstation/-tg-station/issues/15621 ?
I imagine borg metal sheets use a different path than regular metal sheets

**Comment by phil235** [comment]
Most likely https://github.com/tgstation/-tg-station/blob/5fb22a9116330c1dd4c064cab9b34c921002511c/code/modules/vehicles/scooter.dm#L84
borg metal sheet has an amount of 0 and uses its cell power if I remember correctly. GetAmount() or something must be used instead.

Also
