### ISSUE TITLE
Manually built turrets don't seem to work

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#16234]
### What is the problem?

I've been building turrets in the armoury as warden for extra protection, but nothing seems to cause them to activate, even with all the settings to 'on' (weapon auth, no ID, nonhuman)
### Why is it a problem, or what should have happened?

Turrets are supposed to work, most of the time.
### How can the problem be reproduced?

build turrets.

**Comment by optimumtact** [comment]
I'll try to have a look at this sometime this week

**Comment by Anonmare** [comment]
Isn't turret code an absolute mess?

**Comment by optimumtact** [comment]
Well it's not the worst I've ever seen

**Comment by XDTM** [comment]
@AnturK, was this resolved in #22052?

**Comment by AnturK** [comment]
Yes
