### ISSUE TITLE
Cat sprites do not update upon death

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#16248]
### What is the problem?

see title

### Why is it a problem, or what should have happened?

dead sprite should display (this is a note for me to fix it)

### How can the problem be reproduced?

kill a cat if you are a MONSTER

**Comment by Niknakflak** [comment]
>bgobandit reporting a bug they will probably fix themselves because it's cat related

**Comment by bgobandit** [comment]
:cat:

**Comment by Cheridan** [comment]
even in death i still nya~~

**Comment by YotaXP** [comment]
Thank god issue templates are gone. (sorta)

**Comment by Xhuis** [comment]
Unreproducable

**Comment by KorPhaeron** [comment]
Can't reproduce
