### ISSUE TITLE
Lavaland ruins can spawn inside the bridge to the necropolis gate.

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#16246]
http://i.imgur.com/hb7SGQJ.png

This one spawned such that you can't actually get to the gate at all.

@KorPhaeron

**Comment by Supermichael777** [comment]
@KorPhaeron

**Comment by KazeEspada** [comment]
Kor, make the bridge an area so its also ash proof.

**Comment by PKPenguin321** [comment]
![embed](http://i.imgur.com/hb7SGQJ.png)

**Comment by KorPhaeron** [comment]
It's a beta

@KazeEspada 

Good idea
