### ISSUE TITLE
Hostile creatures can spawn in the lavaland gulag

### ISSUE THREAD

**Issue by TheRealGLH** [tgstation/tgstation#16251]
The gulag is already a pretty harsh sentence, but it's not a bad idea to at least make sure the prisoners don't just die there.

**Comment by KorPhaeron** [comment]
Cant fix this until the freeze is up unfortunatley

**Comment by bgobandit** [comment]
feature

**Comment by Cheridan** [comment]
shouldn't be happening anymore
