### ISSUE TITLE
cloning does not work with altered crit/death config

### ISSUE THREAD

**Issue by hornygranny** [tgstation/tgstation#16297]
Setting death at 0 and crit at 50 will cause people to instantly die when they begin cloning

**Comment by PKPenguin321** [comment]
need to tweak this line to base itself on the config: https://github.com/tgstation/-tg-station/blob/d31bc85106ea9ed86e741021f54ece62383d6744/code/game/machinery/cloning.dm#L214

**Comment by KorPhaeron** [comment]
@PKPenguin321 

Actually not the correct line. Needed line 176
