### ISSUE TITLE
Left-handed police baton sprites are bugged

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#16309]
They jut behind the body rather than in front of it.

**Comment by ShadowDeath6** [comment]
https://github.com/tgstation/-tg-station/issues/14844
Doubleposted

**Comment by Zilenan91** [comment]
No, this got half-fixed, the right-handed sprites are fine, but the left-handed ones are still broken.

**Comment by Cheridan** [comment]
i swear these backwards batons have been fixed 3 separate times already.
