### ISSUE TITLE
Queen Alien sprite too fucking big

### ISSUE THREAD

**Issue by tedward1337** [tgstation/tgstation#16335]
Seriously
You cant click the tile above you, this sprite is 
2
fucking
B I G

**Comment by KazeEspada** [comment]
Dupe

**Comment by tedward1337** [comment]
Dupe of what? Theres no other issue report for this

**Comment by PKPenguin321** [comment]
It was closed as unresolvable iirc

**Comment by tedward1337** [comment]
>unreasonable
Just make the sprite smaller
or use the old one??

**Comment by PKPenguin321** [comment]
Blame wj's megasprite fetish

**Comment by Zilenan91** [comment]
Also the new Xeno Queen sprite looks a lot worse than the old one

**Comment by Lumipharon** [comment]
I suggested just using the old sprite/making a new non HUGE sprite, but then they closed it because functionality and practicality over appearance is apparently not an option.

**Comment by Jordie0608** [comment]
The previous report for reference; #13094
As was said, it isn't litrerally unresolvable

**Comment by tedward1337** [comment]
Just
Make this shit smaller god damn

**Comment by WJohn** [comment]
I'd still rather we make it so the queen can only be clicked on in the tile they're on, with the rest of it being unclickable. This'd probably need some pretty silly layered sprite stuff, but I can't help much with that.

The alternative of respriting the queen to be smaller is noooooooope. Good luck spending another 20+ hours on that shit!

**Comment by PKPenguin321** [comment]
Well I mean queens only took 1 tile for literal years before the giga meme sprite was added so I don't see why we couldn't just go back to that

If somebody could find a way to make queens see themselves as the small sprite that'd be optimal

**Comment by tedward1337** [comment]
Let's just go back to the old sprite. There was nothing wrong with it tbh

**Comment by ChangelingRain** [comment]
Making it only clickable on the tile it's on is actually super easy, honestly, you just need a reference object with its sprite that follows it around(you can't use an overlay because overlays refuse to respect mouse_opacity which is bull) which you could probably do with buckling.

**Comment by Lumipharon** [comment]
Functionality > fancy sprite

Bring back the normal sized sprite.
