### ISSUE TITLE
AI cannot use Shipping Price Computers or Stock Exchange Computers

### ISSUE THREAD

**Issue by alphaaBeta** [tgstation/tgstation#16331]
While it can access the interface, it cannot buy or sell anything. It's annoying to yell at crewmembers to buy something for you and then loose points when they don't sell it in time.

**Comment by KazeEspada** [comment]
Feature, AIs shouldnt be touching cargo comps

**Comment by TheRealGLH** [comment]
@KazeEspada 
Why not? They used to be able to do it before the cargo overhaul.

**Comment by GunHog** [comment]
Because Goof hates the AI. He himself stated something about not interfering in "Human affairs" despite this being a fun minigame that the AI can do. It really is a shame.

**Comment by Iamgoofball** [comment]
this is INTENTIONAL

# I N T E N T I O N A L
