### ISSUE TITLE
Blob spores have perfect space move while attacking

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/tgstation#16382]
No matter how much I zigged and zagged through space and gravity less hallways with my jetpack, their AI could keep on my tail

**Comment by Zilenan91** [comment]
Probably for balance because otherwise spores would just float away and space would be unfightable for a blob

**Comment by KazeEspada** [comment]
Space is unfightable for the blob. That's the point. Hence the meme:

"Blobs cannot into space."

**Comment by Xhuis** [comment]
This is not an issue. According to the following code:
```
/mob/living/simple_animal/hostile/blob/Process_Spacemove(movement_dir = 0)
	for(var/obj/effect/blob/B in range(1, src))
		return 1
	return ..()
```
Blob spores can move in space as long as there are blob tiles nearby. Otherwise, they can't and drift helplessly.

**Comment by KazeEspada** [comment]
No, they were changing direction in space nowhere near a blob.

**Comment by Xhuis** [comment]
That's bizarre and shouldn't happen.
