### ISSUE TITLE
Placing floor tiles on asteroid plating has strange interactions

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#16391]
Using generic plasteel tiles.
1. Place a tile. It will be invisible/look like the default asteroid turf with no variants
2. Pry up the tile you just placed. The asteroid will now look like metal plating.

**Comment by coiax** [comment]
Plasteel can make floor tiles?

**Comment by KazeEspada** [comment]
Nope, metal tiles are called plasteel tiles in the code for legacy reasons.

**Comment by ChangelingRain** [comment]
FLOOR CODE
