### ISSUE TITLE
Machine upgrading is horrendously implemented

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#16392]
1. It scales terribly. The efficiency gains are x2 x3 x4
2. It's very easy to get the parts roundstart. The round I was just observing the scientist got t4 parts at 10 minutes in. I'm guessing this is not unusual.
3. They don't cost anything. A single sheet of diamond is 2k units. A T4 part costs 20 diamond.

There is 0 point to having upgrades if they come that early with no outside help, and impossible to balance around with such numbers.

**Comment by xxalpha** [comment]
Things shouldn't have costs that low when mineral sheets are worth 2000.

**Comment by PKPenguin321** [comment]
^
Also you could lower the scaling to 1x, 1.25x, 1.5x, 1.75x, and 2x

**Comment by MrStonedOne** [comment]
You generally want to do diminishing returns when you do efficiency scaling.

1x, 1.75x, 2.25x, and 2.5x

**Comment by Iamgoofball** [comment]
Don't forget the actual mechanic of upgrading the machine with the RPED is clunky as fuck

I added the BSRPED to remove this problem and honestly I'm considering making BSRPED the default

**Comment by Dawgas** [comment]
I think we're looking at this problem from the wrong angle - R&D, as a mechanic, is clearly poorly implemented/shit

Maybe there could be some other method of obtaining upgrades? The problem with that though would be that somebody would've come up with a good idea by now for that already.

We could try making cargo more important? But then again, with how people are purely anti-fun around here, nobody would enjoy people doing things that aren't bringing a round to a quick and immediate end.

**Comment by PKPenguin321** [comment]
>kor excluded his own feedback forum issue from the non issue purge

**Comment by KorPhaeron** [comment]
abuse

**Comment by optimumtact** [comment]
Priority High lol
