### ISSUE TITLE
Bees need a reagent blackist.

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#16414]
because everyone on the station having a heart attack is only funny twice.  Sugest banning admin and traitor exclusive things like intropedrol that come in 30u bottles for a reason. and morphine because morphine spam sucks

**Comment by Zilenan91** [comment]
I tried to get botanists to inject their bees with neurotoxin but they wouldn't do it

I mean I'd have gotten banned since neither of us were antags but it would've been so fucking worth it

**Comment by Core0verload** [comment]
No, they don't need a reagent blacklist.

**Comment by killerx09** [comment]
Agreed with Core0verload, no.

**Comment by AdamElTablawy** [comment]
Okay but what if clf3 bees and blackpowder bees

...Gibbing stings?

**Comment by killerx09** [comment]
CLF3 kills too fast for enough blackpowder to be injected, so you'd have lots of tiny explosions going off while he burns.

**Comment by AdamElTablawy** [comment]
Nitroglycerin bees.

**Comment by Iamgoofball** [comment]
fuck off

**Comment by Lumipharon** [comment]
stay mad bee haters.

Also an epi pen THAT EVERY PLAYERS STARTS WITH hard counters that shit yo.

**Comment by Supermichael777** [comment]
it does show that no one gets poisoned with it enough to know the cure. Also i didnt die because i grabed a hardsuit the moment i saw bees.

**Comment by nullbear** [comment]
We had nanomachine bees a few rounds ago.

Everyone on the station became a borg.

**Comment by Iamgoofball** [comment]
i dont see the problem here
