### ISSUE TITLE
Ghosts other than yourself disappear when you toggle darksight.

### ISSUE THREAD

**Issue by ATDoop** [tgstation/tgstation#16447]
It was a wizard round, and I died pretty fast and started orbiting the wizard. The problem is, only my ghost appeared. Even if I orbited other ghosts, I couldn't see them. Ghost vision was on, so that wasn't the issue. EDIT: IT'S TOGGLE DARKNESS IGNORE WHAT I SAID BEFORE

![](http://i.imgur.com/SUa9pdf.png)

**Comment by Zilenan91** [comment]
yeah I noticed this. Ghosts just aren't visible

**Comment by TheRealGLH** [comment]
Did you toggle darkness?
I've noticed that turning off darkness also makes ghosts invisible.

**Comment by TrustyGun** [comment]
Yeah, I noticed that in the round we're playing. Toggle Darkness makes ghosts invisible.

**Comment by ATDoop** [comment]
Yep. It's toggle darkness!

**Comment by xxalpha** [comment]
Wasn't this fixed @MrStonedOne ?

**Comment by Shadowlight213** [comment]
This was fixed ages ago. Did you have ghost vision on?

**Comment by phil235** [comment]
We use a workaround to allow ghosts to see others ghosts when toggle darkness is on. It uses ghost images. Somehow this broke. It might be related to the recent change to ghost hair?

**Comment by Zilenan91** [comment]
Yeah ghost directional sprites are also broken

**Comment by phil235** [comment]
I managed to reproduce the bug, but after changing my ghost display settings, the bug seems to have disappeared no matter which setting I have selected.
