### ISSUE TITLE
Bluespace capsules inside escape shuttle.

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/tgstation#16461]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))
Bluespace capsules triggered when a shuttle is launching creates this bug. 
It leaves the bluespace capsule square that is made(the little room) on the "hyperspace" z level when the shuttle docks, and leaves a big hole where the capsule was on the shuttle when the shuttle docks.

**Comment by coiax** [comment]
It's probably something to do with how bluespace capsules define their insides as part of a specific area so they allow protection from ash storms. Could just disable their use in the shuttle, or the shuttle turf things?

**Comment by coiax** [comment]
@KorPhaeron @ChangelingRain was this fixed?
