### ISSUE TITLE
Wearing boxing gloves fails to give you sleeping carp powers

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#16479]
1) Wear boxing gloves
2) Use carp scroll
3) You get the carp tab but can still shoot guns/be shot/lack any carp martial arts moves

**Comment by Incoming5643** [comment]
Because the boxing gloves give their own martial art datum

**Comment by PKPenguin321** [comment]
could be kinda hackily fixed by giving boxing gloves the same drawbacks as sleeping carp ("Your boxing gloves are too puffy to get your finger on the gun trigger!")

**Comment by Lumipharon** [comment]
how the fuck DO you fire a gun with boxing gloves on?

**Comment by TrustyGun** [comment]
the same way you type with boxing gloves on

**Comment by optimumtact** [comment]
martial arts datums are highly fragile in the way they are applied

**Comment by bgobandit** [comment]
Fixed, probably in https://github.com/tgstation/tgstation/pull/27324 @AnturK @Robustin

**Comment by PraiseRatvar** [comment]
@Really-Good-Soda-Flavor 

Has this been fixed? If so, tag Dorsisdwarf or a maintainer to close this (or ask someone on coderbus)

**Comment by Robustin** [comment]
Seems to be fixed, I could block projectiles with gloves on now and most of the SC moves appear to work.
