### ISSUE TITLE
Firing at contact point on someone's head may miss.

### ISSUE THREAD

**Issue by Steelpoint** [tgstation/tgstation#16474]
I was doing a offline test and during that I aimed a 'Energy Gun' at a Human's mouth to execute them, after the ten second pause my character fired the gun. Only to hit the target in the left arm, dealing far less damage than otherwise.

While amusing, I find it annoying that there is even a chance to miss a contact shot with someone, which is impossible considering the amount of time it takes to prepare the shot.

**Comment by GunHog** [comment]
Were you testing it using Mekhi's character profile?

**Comment by ATDoop** [comment]
nanotrasen security training at work

**Comment by Alek2ander** [comment]
Only imperial stormtroopers are this precise

**Comment by Dorsisdwarf** [comment]
Unable to reproduce 2019.07.11
