### ISSUE TITLE
Bowls are lost when grinding or composting foods made with a bowl

### ISSUE THREAD

**Issue by erwgd** [tgstation/tgstation#16519]
Soups and salads tend to require a bowl. When you eat these completely the bowl is returned to the world as 'trash'. This is important as this lets you make more soups and salads without forever losing bowls.
However, when you put the food in a reagent grinder and grind it, you will not get the bowl back. 
To reproduce this:
1. Tablecraft a soup or salad; wish soup is easiest to make, needing only a bowl and 20u water.
2. Put the wish soup in an All-in-One Grinder and grind it.
3. You lost a bowl.

To solve this, perhaps:
- When grinding food, for each food item that leaves a bowl as trash, spawn a bowl.
- When grinding food, for each food item that is a soup or a salad, spawn a bowl.

Additionally, when composting a food made using a bowl you don't get a bowl back.

**Comment by MMMiracles** [comment]
maybe you shouldn't be putting a bowl in a grinder?

**Comment by octareenroon91** [comment]
That is a lame excuse.

How hard would it be to drop the empty bowl immediately and make it impossible to eject bowl-bound snacks?

**Comment by phil235** [comment]
>How hard would it be to drop the empty bowl immediately 

easy

>How hard would it be to drop the empty bowl immediately 

HACCKKKYYYYYY

**Comment by octareenroon91** [comment]
Is immersion worth hackiness?
