### ISSUE TITLE
Cat mens job ristrictions arnt taken into acount when they atempt to latejoin when considering slots

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#16554]
Meaning they are told assistant is not available even though no eligible job exists

**Comment by Shadowlight213** [comment]
Does the same apply to lizards/plasmamen?

**Comment by Supermichael777** [comment]
no because cat men use a different snowflake system.

**Comment by Supermichael777** [comment]
now that catbeast is forced out this is irrelavent
