### ISSUE TITLE
Vomit Doesn't Contain Viruses and Blood Viruses Contents Do Nothing

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#16553]
Vomit contains a virus list of what viruses are contained in the vomit--that said, there's never a time where viruses are added to the vomit.

On a similar thread, viruses _are_ added to blood and gibs---but this doesn't really mean anything. touching blood decals, crossing them, or rolling around in them doesn't appear to actually do anything, therefore making the point of viruses stored in the blood a bit...pointless.

Vomit has a similar problem; interacting with vomit doesn't transfer any viruses it has to you in any way, shape, or form.

**Comment by Incoming5643** [comment]
it used to infect through blood splaters, but the intense resource use of every drip of blood checking for all those means of interaction all the time eventually got the mechanic removed.

**Comment by octareenroon91** [comment]
Can you give me a PR for that? We seem to have resources for days now.

**Comment by XDTM** [comment]
Currently intentional due to every instance of viruses processing. I'm thinking of readding it with Crossed and similar procs in the future.

**Comment by Fox-McCloud** [comment]
oops, I forgot to put "fixes" in my one PR; there's no such thing as blood/vomit containing viruses anymore; only mobs.
