### ISSUE TITLE
Holodeck cats can mate

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#16574]
How to reproduce:
- Set the holodeck to Pet Playground
- Bring Runtime to the pet playground
- Watch as Runtime happily fucks the holographic cats, producing real life kittens
- Optional: Set the holodeck to something other than Pet Playground and watch the kittens remain, take them around the station, they're real

**Comment by bgobandit** [comment]
a related bug: you can use a collar on holodeck pets, but predictably, if you take the pet out of the holodeck, the collar is gone forever, you don't get it back

**Comment by TehZombehz** [comment]
If you sex in the holodeck, you sex in real life!

**Comment by HankMoodyExperience** [comment]
its a feature

**Comment by bgobandit** [comment]
tested, no more mating
