### ISSUE TITLE
The stock market can rise to fucking ridiculous amounts

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#16598]
19:35 | The Wolf Of Clown Planet bought 2 stocks for 14280.7 credits in Fig Gadgets.
19:47 | The Wolf Of Clown Planet sold 2 stocks for 1.31584e+008 credits from Fig Gadgets.

**Comment by Zilenan91** [comment]
I think this is a feature more than anything

**Comment by stapler2025** [comment]
feature

**Comment by Nyvrem** [comment]
Yes it's very fun when you got a borrow in a company that's about to go bankrupt but instead of going bankrupt suddenly the stocks become a thousand times worth more and you're suddely millions in debt simply because of a bug.

It essentially ruins the entirity of the "borrowing stocks" functionality because it happening once can sink you so deep into debt nothing matters anymore.

**Comment by Jalleo** [comment]
Well I think this means we need bankruptcy options.

**Comment by Iamgoofball** [comment]
until someone saves a snapshot of when this happens I can't debug it

**Comment by Nyvrem** [comment]
![bugged stocks](https://cloud.githubusercontent.com/assets/10331933/15048430/c8a52a6a-12e9-11e6-9827-9507b9c05c6f.png)

**Comment by Nyvrem** [comment]
![stock bug](https://cloud.githubusercontent.com/assets/10331933/15048887/c08c4212-12eb-11e6-98ed-9c641597600c.png)
Later that round.

**Comment by Iamgoofball** [comment]
jesus

**Comment by Iamgoofball** [comment]
:+1:

**Comment by Nyvrem** [comment]
It happens often enough to make using the stocks system not enjoyable.

**Comment by Iamgoofball** [comment]
i'll add some quick debug shit

**Comment by Iamgoofball** [comment]
also by snapshot I meant like a server save file shit so we can revisit it any time

**Comment by Nyvrem** [comment]
Then other coders misinformed me.

**Comment by optimumtact** [comment]
lets be honest with ourselves nobody is gonna fix this.

**Comment by Kromgar** [comment]
RIP stock market

**Comment by evsey9** [comment]
feature

**Comment by Nyvrem** [comment]
It's really great when you're shorting and this brings you into a negative billion with no way to predict it happening.

**Comment by Iamgoofball** [comment]
It's really great when they STILL HAVEN'T MERGED MY FIX

**Comment by nullbear** [comment]
That fix has been open for like a week geez
