### ISSUE TITLE
Switching bodies bugs poll creation

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#16614]
1. Start creating poll

2.Be a couple options in

3.Random event triggers, pulling my body for a revenant (why doesn't this have a prompt?). This cuts the poll process short and creates the half finished poll

**Comment by Jordie0608** [comment]
Polls only get auto-deleted if they're created without any options and in this instance you were 3 options. Off the top of my head I can't think of a way to fix this that'd be entirely foolproof (byondproof?) but specifying an intended number of options and deleting if that amount isn't reached could work.

**Comment by KorPhaeron** [comment]
We should probably kill the things that switch your body without a prompt either way

**Comment by xxalpha** [comment]
Make them prompt if you're an admin.

**Comment by MrStonedOne** [comment]
How about escalating prompts? Start at chatbox, then ghost hud icon, then question, then if its important enough, pull a random person

**Comment by Dorsisdwarf** [comment]
But admins becoming space ninjas in the middle of interrogating the HOS about killing the clown and trying to decide between handing off their investigation and being a ninja or giving some other schmuck they KNOW will be awful ninja is a time-honored tradition.
