### ISSUE TITLE
Cargo consoles do not work on ministation map

### ISSUE THREAD

**Issue by Shadowizard** [tgstation/tgstation#16612]
Playing on ministation map with most current update. Opening cargo consoles reveals nothing except a yellow bar at the top which says "loading". Stared at this for ten minutes before declaring cargo to be dead. Please fix, as lack of starting resources on ministation can only be supplemented by cargo, making it essential.

**Comment by merklaw** [comment]
This happens on other maps as well.

This issue annoyed me enough that I didn't stop looking until I found a solution. [Here](http://i.imgur.com/vyBO1iW.png) is the in-game error that pops up when you try to open a supply request console or supply console. I have Internet Explorer 11 installed. I noticed an [additional error](http://i.imgur.com/ghyvpfD.png) in Dream Daemon which is found in the file "code\__HELPERS\510.dm" on line 196.

It seems to be a bug in the helper for running 510 code on older versions of BYOND.

Workaround: Compile with BYOND 510. It will restore functionality to the supply consoles.

**Comment by Shadowizard** [comment]
Thanks! Although I am running my server using (What I believe to be) the most current version of BYOND, I will double check and re-compile.

**Comment by Shadowizard** [comment]
Re-compiled. Now I get this error popping out at me. [http://s62i.imgup.net/Error120ba.jpg](url) When I hit "Yes" it gives me this [http://y78i.imgup.net/error2c638.jpg](url). Clicking "Yes" again gives me the other error and it continues. When I hit "No" it gives me the same error. I cannot exit out of the console, short of closing the game. Am I doing something wrong, or is the code at fault? In order to ensure I was using the newset version of Dream Builder, I navigated to it via the BYOND console, which is up to date. Database is not enabled. I'm not sure how much info is needed, so I'll let you ask for more if need be.

**Comment by merklaw** [comment]
I got the same error until I compiled with BYOND 510. You can see what version you have by going to Help -> About BYOND in Dream Daemon or the BYOND client. If you're using BYOND 509, you have to go to their [website](http://www.byond.com/download/) and download the BYOND 510 beta.

**Comment by Shadowizard** [comment]
Oh... I shoul listen better. :P

**Comment by Chocobro** [comment]
[SarkinL] anyways, issue 16612 can be closed as its not relevant anymore
