### ISSUE TITLE
Lavaland xeno nest has outdated turf paths

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#16685]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))
As in /simulated and such.
[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by duncathan** [comment]
what file is it

**Comment by ChangelingRain** [comment]
lavaland_surface_xeno_nest.dmm
