### ISSUE TITLE
Destroying a block of dense turfs (walls, mineral, etc) results in vaucuum being spawned

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#16684]
Notably it will always be in the corner of where the turfs used to be. Can be tested by exploding gibtonite or using a hyper KA on lavaland.

http://imgur.com/rcREowL

You can see how all the ores get sucked into the corner by said vacuum.

I'm guessing this is some bug with assume_air trying to pull from turfs around it in the midst of an explosion/being surrounded only by walls.

**Comment by KorPhaeron** [comment]
@MrStonedOne @duncathan 

Since you guys are the ones that would be able to fix it

**Comment by RandomMarine** [comment]
I recently blew four gibtonites in one chain reaction and it made a massive portion of lavaland dish out pressure damage. I feel this needs higher priority.

**Comment by duncathan** [comment]
this is a stupidly complicated bug to fix

**Comment by TechnoAlchemisto** [comment]
please god mining is horrible sometimes with this

**Comment by duncathan** [comment]
I'm still trying to figure out a decent way to fix this

**Comment by Firecage** [comment]
@KorPhaeron Possibly related to this issue #17806
