### ISSUE TITLE
Ripley Drills don't work on Rock.

### ISSUE THREAD

**Issue by Brimcon** [tgstation/tgstation#16691]
Clicking on a Rock tile in a Ripley armed with a Mining Drill does nothing. The text is displayed, the bar shows and fills normally but nothing happens afterwards.

**Comment by optimumtact** [comment]
Thunder11 Tested and couldn't reproduce

**Comment by Brimcon** [comment]
Was a long time ago, was fixed nearly immediately AFAIK. Didn't realize this was still open after all this time.
