### ISSUE TITLE
Vomit never gains reagents

### ISSUE THREAD

**Issue by octareenroon91** [tgstation/tgstation#16693]
`carbon/proc/vomit()` never puts any reagents into the vomit decal, but flypeople need to get their nutrition from nutriment-rich vomit pools.

**Comment by bgobandit** [comment]
see also https://github.com/tgstation/-tg-station/issues/16553

**Comment by Man-Shroom-** [comment]
ARISE FROM YOUR GRAVE FOR I AM THE NECROMANCER

**Comment by Iamgoofball** [comment]
i have to add a vomit reagent with goonmed, will fix

**Comment by Iamgoofball** [comment]
this is a feature btw not a bug

**Comment by Cheridan** [comment]
no its not a feature you idiot
