### ISSUE TITLE
TGui client-side speed concerns.

### ISSUE THREAD

**Issue by PJB3005** [tgstation/tgstation#16702]
TGui looks great, is powerful, and nice to work with. Issue is very complicated interfaces can become really slow, taking upwards of 5+ seconds to open (yes this is dependant on system specs, but it's still a LOT), where similar NanoUI interfaces would be less than half a second at worst. (yes I'm on Windows 10)

Well it turns out that TGui has really poor scalability.

For this reason I'm opening an issue to discuss improving TGui performance / workarounds, because this'll definitely be a showstopper for more complicated / large interfaces (anybody want to tackle R&D console, perhaps?).

Yes I get it due to how Ractive works it's more expensive up front, but faster while the interface is open. However seeing that on the computer I tested this on CPU usage on Dream Seeker increased by a whopping **15%** with **1** complicated TGui interface ([this WIP one I'm making for a different codebase](https://camo.githubusercontent.com/7d8cbc62cdc7e7a845c4562385e54d5b3b764f59/687474703a2f2f692e696d6775722e636f6d2f525131565967792e706e67)), combined by the fact that 5+ second UI opening times is just not acceptable.

**Comment by optimumtact** [comment]
what are your hardware stats?

**Comment by PJB3005** [comment]
Not much, but either way there are people worse computers and those will have even worse performance.

**Comment by duncathan** [comment]
Is there a difference with No Frills?

**Comment by PJB3005** [comment]
Sorry for forgetting about this, but with No frills there's not much difference, sadly.

**Comment by nullquery** [comment]
I've noticed that tgui seems to prefer sending data to the client every processing tick, which seems redundant if there are no updates to send. Ideally updates should only be sent when things have actually changed, i.e., force the developer to call a proc to mark a particular object as requiring an update. Or is this already the case (I've seen an "autoupdate" flag but no means to force an update on the next tick)?

I may see some issues in the near future as I'll have at least 1 tgui element visible at all times per player. I'll update this issue with any performance tweaks I've had to do on my end.

**Comment by PJB3005** [comment]
Auto updating is one issue, but that still doesn't do much about the humongous opening time of UIs. 

Honestly I'm feeling that ractive is just hopelessly slow, even in modern browsers.

**Comment by nullquery** [comment]
This is one of the reasons I kept my html_interface module minimalistic and process the HTML on the server-side.

IE is notorious for being bad with DOM manipulation. I've had a case where requesting the offsetLeft of an element took 300-400ms in IE and 0-2ms in Chrome.

The only way to avoid that problem would be to render the HTML first and do any scripting on top of that, I think.

**Comment by PJB3005** [comment]
Sadly the issue with that is that the HTML interface module is that it's a pain to work with.

I've made a couple interfaces with it on /vg/, the TEG, MSGS, RCD / RPD framework and I modified the power monitor to have better code and a fancy graph. The module did allow me to utilize things like `<input>` though, which is great. 

Although there is area for improvements to be made, I don't feel like doing them because you still need a fundamental understanding of html and Javascript to do anything with it, while a system like nano or tgui is an incredibly comfortable work flow. This isn't a problem for me personally, but for a lot of coders who don't want to learn a whole new language it is.

Another issue is that building the html on the server is quite slow so it's our of the question.

**Comment by optimumtact** [comment]
a lot of the points PJB made in his vg ui thread are salient.

tgui's backend is very strong, the frontend is where it's a letdown.

Possibly we could go back to nanoui's templating engine for the frontend, bolted on to the tgui backend.

**Comment by optimumtact** [comment]
Also if you ask me the real advantage of ractive or other templating engines is the third party plugins enabling things like graphs etc with just a few lines of code

**Comment by PJB3005** [comment]
I actually have a lot if complaints about the tgui backend too, namely the fact that it still needs you to copy paste the boilerplate `ui_interact` and such, not to mention some other systems are still messy (looking at status systems)

The thing about ractive is that

**Comment by PJB3005** [comment]
Fuck you GitHub I didn't hit comment just yet.

Anyways, the problem is that Ractive needs to do complex parsing on the template provided and the passed data to be able to preserve the unmodified DOM, which has the benefit of letting things like input tags work correctly, because they don't lose their contents every update. This comes with a huge cost and byond/IE... Just can't handle it. 

DoT on the other hand literally generates a function that works in the same way as old interfaces in the DM code does. This is about as fast as you're gonna get with building the HTML for the interface. This does come with the side effect that any input tags in the interfaces and other interactive elements like charts are LOST.

This is actually what makes it even possible to implement elements like charts and IDEs into ractive, where with DoT it's gonna require some trickery.

Paradise did manage to implement animations and such with DoT which is great. I have no idea how the systems works however so...

So we just need to figure out a way to get the volatile elements like input tags, charts, etc... To work in DoT and we're golden.

**Comment by optimumtact** [comment]
yeah ui interact is pretty strange, especially when you consider most of them are just a clone of the one from the documentation.

**Comment by optimumtact** [comment]
tgui was a mistake but this isn't a bug as such
