### ISSUE TITLE
Mining shelter pod storage issue

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#16722]
HELP: redacted (?) (PP) (VV) (SM) (FLW) (TP) (REJT): Shelter pod storage only shows minerals as 1 unit but when retrieved is more

**Comment by ChangelingRain** [comment]
this is a smartfridge issue

**Comment by praisenarsie** [comment]
@vuonojenmustaturska since you touched smartfridges recently, anything to say about issue?

**Comment by ShizCalev** [comment]
Will close in a week without repo.
