### ISSUE TITLE
Ghost roles can be traitor targets.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/tgstation#16736]
Vault Creature is a ghost role on lavaland, and as you can see, it was an assasination target.
![](http://i.imgur.com/tBnF7JL.png)

**Comment by coiax** [comment]
You're sure that it's not just adjusting when the target player controls a new mob? Or is this an issue with midround assigned antags?

**Comment by octareenroon91** [comment]
Fuck, either one needs fixing. Hijack is probably more convenient.

**Comment by Dorsisdwarf** [comment]
I got Kill Free Golem, which was a pain!
