### ISSUE TITLE
Plasmamen Issues

### ISSUE THREAD

**Issue by HenryBlackie** [tgstation/tgstation#16753]
When a plasmaman is choking you get the standard choking notification in the top right saying that you require oxygen and advising you to use the one in your backpack.

Plasmamen start with an oxygen tank in their back pack. Not really an issue, just not really needed.

**Comment by erwgd** [comment]
The O2 notification (instead of the toxin notification) appears if a plasmaman is suffocating as a result of being in crit. It stays there forever even if the plasmaman wakes up and returns to breathing.
