### ISSUE TITLE
The nuke disk still is not respawning

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#16756]
@ChangelingRain

**Comment by ChangelingRain** [comment]
I need more information than this, what's the situation/location of the disc?

**Comment by KazeEspada** [comment]
I saw it. Nuke got dat disc, then got filled full of lasers. One boom later, nuke disc.

**Comment by KazeEspada** [comment]
Nuke op*

**Comment by coiax** [comment]
So a nuke op had the disk in his inventory, died, setting off their suicide bomb (which destroys items in the nuke op's inventory and equipment apart from what they are carrying in hand), but the disc dropped where they had died, instead of doing the correct thing and respawning somewhere else?

**Comment by ChangelingRain** [comment]
That sounds like container drop code and thus not my fault.

**Comment by KorPhaeron** [comment]
Was working before you changed it so that ghosts could keep orbiting though (I think it was that PR?)

**Comment by optimumtact** [comment]
This is definitely fixed otherwisepplayers would be screaming at us
