### ISSUE TITLE
Tools in toolbelt survive gibbing

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#16772]
For some reason, when various things happen that should delete all equipment on a person, like using certain admin commands, being hit directly by the tesla, or just gibbed randomly, the contents of the toolbelt will drop on the floor. This shouldn't happen.

**Comment by KorPhaeron** [comment]
@KazeEspada 

Please fix this it's been months

**Comment by KazeEspada** [comment]
This is the first time its been an issue. I need to think of the best way to do this.

**Comment by coiax** [comment]
#17027 was a PR to attempt to fix this.

We need to identify when we want items to drop their contents and when we don't want them to.

From talking to @RemieRichards and @ChangelingRain and @KorPhaeron and others, I sense this is a design decision that you guys should probably discuss and hash out?

**Comment by kevinz000** [comment]
@lzimann tested in bagil thunderdome, ex_act(1) and gib() both won't make toolbelts worn in belt slot drop tools.
