### ISSUE TITLE
Smoke blocks turret fire

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#16798]
Just what the station needed: New ways to cheese turrets that were already worthless.

Why is turret AI so bad? Apparently all you need to do is block line of sight now to make it turn off.

**Comment by GunHog** [comment]
Makes it impossible to make feasible xray turrets.

**Comment by Zilenan91** [comment]
intended, feedback forum

**Comment by Lumipharon** [comment]
xray turrets are fine because there are still plenty of objects that block gunfire but not LOS.
Being able to make an xray turret behind walls and watch it just murder everyone would be pretty gay yo.
