### ISSUE TITLE
Issues with drones created with a Drone Shell Dispenser

### ISSUE THREAD

**Issue by TrustyGun** [tgstation/tgstation#16804]
**1.** Upon a ghost entering one, or reconnecting after disconnecting as a drone
 the game asks you where to spawn a movable UI object. **FIXED**
![untitled](https://cloud.githubusercontent.com/assets/7079721/14422672/f5a89e0e-ffa5-11e5-8e79-dc930776a0f0.png)
**2.** There is no static overlay on living objects.
![untitled](https://cloud.githubusercontent.com/assets/7079721/14422708/1f58eeb6-ffa6-11e5-9af1-867f9800a3c9.png)

**Comment by Aloraydrel** [comment]
Same menu pops up for toggle darkness

**Comment by coiax** [comment]
I don't think this is happening anymore, is it?

**Comment by TrustyGun** [comment]
Not anymore. For issue 2 it may be the same issue as #17057

**Comment by coiax** [comment]
Don't think so, snowflake drones are admin spawn only.

**Comment by coiax** [comment]
@oranges @Cheridan this isn't happening anymore

**Comment by Cyberboss** [comment]
Close it nerds

**Comment by coiax** [comment]
someone close this, @lzimann
