### ISSUE TITLE
Fire in Disposal Chute is Inextinguishable by Water

### ISSUE THREAD

**Issue by AssassinT90** [tgstation/tgstation#16803]
- Start a plasma fire on a disposal chute.
- Watch as people try to extinguish the fire.
- Laugh as the disposal chute's tile is not extinguished and keeps feeding the fire with heat.

Of course, if you manage to lower the temperature enough to stop the combustion via atmos meddling, you manage to extinguish the fire. The problem is that a standard fire extinguisher's water jet can't get to a disposal chute's tile.

**Comment by octareenroon91** [comment]
Hurray for `density = 1`

Could make fire extinguishers shoot a little nitrogen reagent with water.

**Comment by phil235** [comment]
Probably modify /obj/effect/particle_effect/water's CanPass() to be able to pass through dense machines.

**Comment by timothymtorres** [comment]
Is this even a bug anymore?  I would assume that if it was there would be more duplicate bug reports since the plasma fires would never fully extinguish.

**Comment by timothymtorres** [comment]
Found the PR that fixed it #57004
