### ISSUE TITLE
Humans unable to spawn as captain

### ISSUE THREAD

**Issue by octareenroon91** [tgstation/tgstation#16821]
Suppose a new player connects to a server for the first time, creates their character, and joins.

If the server config allows joining only as strict humans, players may find themselves **unable to join as heads.**

```
#JOIN_WITH_MUTANT_RACE
#JOIN_WITH_MUTANT_HUMANS
```

I traced the bug to roughly this line -- 
https://github.com/tgstation/-tg-station/blob/master/code/modules/client/preferences.dm#L489

The condition for not letting someone join as a job checks against their pref race, _which may well be disabled in the server config,_ rather than the effective race that they _will spawn as._

So we need to put a fix into either
1. `preferences.dm` , making that if() line that much longer
2. `code/modules/mob/living/carbon/human/species_types.dm`, where the qualification/disqualification gets thrown out if the player _will inevitably spawn as human._

I favor updating `/datum/species/proc/qualifies_for_rank()` to return the fluff reason for rejection (NON-HUMAN/MUTANT)

I really want to turn qualifies_for_rank inside out, so it returns 0 if the rank IS allowed, but I don't have a good name for the proc . Advantage: return `null` when the species qualifies for rank, and `"MUTANT"` or `"NON-HUMAN"` as appropriate directly from the species proc.

**Comment by coiax** [comment]
`rank_disqualifications()`

What about that?

**Comment by octareenroon91** [comment]
I'll incorporate suggestions from the PR soon.

**Comment by SpaceManiac** [comment]
@Cyberboss Cannot reproduce, whatever recently added the "Backup Human Name" option I think also fixed this.
