### ISSUE TITLE
Bot interfaces will open for anyone who interacted with it previously when the bot's status is changed.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#16847]
The interface will just popup for them regardless of their current position relative to the bot.

**Comment by Bawhoppen** [comment]
does this have any correlation to https://github.com/tgstation/-tg-station/issues/13815

**Comment by optimumtact** [comment]
@Shadowlight213 any specific bot or just any bot?

**Comment by GunHog** [comment]
It is any bot, I have gotten this often as AI for bots which I have modified at the same time as a another player. I have not determined why, but it might be how the Topic() handles "close" hrefs and calls update for every user interacting with the bot in its user list. You end up being in the user list still, even if your interface is not open.

**Comment by Shadowlight213** [comment]
Yeah. It may have to do with silicon interaction, as I've gotten this as a drone, ai, and admin ai interact the most.

**Comment by optimumtact** [comment]
@GunHog yeah casting my eyes over that code I suspect there’s a number of ways to close the interfaces without disconnecting the user from the list
