### ISSUE TITLE
Ghosts showing up as both simple sprites and full sprites

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#16842]
![meme](http://puu.sh/ogcNY/abbc93b4b6.jpg)
I had see others set to see the default sprites and i was seeing both ghost types overlayed.
Toggling darkness seemed to fix it.
@Ricotez

**Comment by Durkel** [comment]
Sounds like a case of 2spook

**Comment by Ricotez** [comment]
weird, I thought I covered all cases when I tested this but apparently I missed a configuration

fix asap
