### ISSUE TITLE
RPD's can't place disposal pipes under normal walls.

### ISSUE THREAD

**Issue by CPTANT** [tgstation/tgstation#16855]
PR #14809 claimed to fix RPD's placing pipes under indestructible walls, however it made RPD's not be able to place disposal pipes under ANY wall. Something not stated as goal in the PR.

This makes building disposal networks a pain.

**Comment by Dorsisdwarf** [comment]
@tkdrg

**Comment by duncathan** [comment]
in its first iteration that PR wouldn't allow ANY rpd use (even regular pipes) on ANY turf with ANYTHING dense on it
that PR was awful tbqh

**Comment by lordpidey** [comment]
@cyberboss Wasn't this feature removed because it's too powerful, causing an RPD to be an easy all access?

**Comment by Dorsisdwarf** [comment]
The PR removing it did not state that as a reason anywhere, no.

**Comment by RemieRichards** [comment]
This is not a bug, the OP's premise is wrong, 
#14809 Is not about fixing it going under indestructible walls, it's about all walls.
And we've decided we don't want cheap RPD-under-walls-to-break-in tactics to make a comeback.

**Comment by CPTANT** [comment]
My premise wasn't wrong, you just changed your mind about it.
