### ISSUE TITLE
Cardborg alternate appearance can sometimes remain after removing the suit/helmet.

### ISSUE THREAD

**Issue by phil235** [tgstation/tgstation#16860]
It happened to one person just this round. Reconnecting fixed the issue, but the player couldn't reproduce the bug again. I also couldn't reproduce the bug, but after a while, I got back to my mob with silicon appearance in the thunderdome, removed the helmet and it worked just once for me... 

@RemieRichards

**Comment by RemieRichards** [comment]
very odd.

**Comment by Dorsisdwarf** [comment]
I encountered this when I used the "Reconnect" button while wearing the suit, while an active admin, live on bagil
