### ISSUE TITLE
Using a teleprod in hand without a power cell creates a new igniter

### ISSUE THREAD

**Issue by Shapsy** [tgstation/tgstation#16888]
Take a teleprod with a bluespace crystal attached but no power cell, use it in hand to remove the crystal, it creates a free igniter at your feet while keeping the one attached to the prod itself.

**Comment by PKPenguin321** [comment]
>somebody used teleprods

**Comment by GunHog** [comment]
Do not be silly, I use them as RD sometimes when the miners literally leave them on the floor. They are excellent for removing intruders! (Terrible if you are an antag, because the target can wind up out of your reach)

**Comment by PKPenguin321** [comment]
Okay so I figured this out. To make teleprods able to use both real and artificial crystals without transforming artificial to real upon removing it, I made it add the crystal to the prods contents, then drop the contents on the floor when the crystal is removed. Raz's teleprod change must use a system that adds igniters to contents, as well.  I have a few possible fixes in mind, I'll see about it later today.
