### ISSUE TITLE
DNA spread virus is broken

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#16898]
It just instantly cures itself.
@xhuis

**Comment by Xhuis** [comment]
Bizarre. Not sure why this is happening.

**Comment by LanCartwright** [comment]
if(!affected_mob.dna)
		cure()
	if(affected_mob.dna.species.specflags & NOTRANSSTING) //Only species that can be spread by transformation sting can be spread by the retrovirus
		cure()

**Comment by Xhuis** [comment]
Unable to reproduce this on latest build.

**Comment by phil235** [comment]
>if(<b>affected_mob.dna.species.specflags & NOTRANSSTING</b>) //Only species that can be spread by 
Another example of people mistaking specflags for a bitflag, it's a list... The error has been changed already, probably by me.
