### ISSUE TITLE
Projectiles are suddenly very slow

### ISSUE THREAD

**Issue by CPTANT** [tgstation/tgstation#16893]
Played a couple of rounds yesterday and it seems something bugged up projectile speeds. I could outrun my own disabler shots and lasers.

Sometimes they suddenly seemed to do speed up.

**Comment by xxalpha** [comment]
@iamgoofball put this shit on the fast process.

**Comment by MrStonedOne** [comment]
Projectiles use while .. sleep() (technically they use throw, but throw uses that), I changed it so that they would sleep for longer but move more each tick if the server was lagged out, and this might be part of why.

**Comment by MrStonedOne** [comment]
Also they used to calculate their speed stuff oddly that in some tick_lag rates would cause them to be faster, I had to fix that bug to make that change.

This was done in the initial TICK_CHECK pr.

**Comment by KorPhaeron** [comment]
Dupe
