### ISSUE TITLE
smoke effects break lighting

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#16927]
Smoke effects (well tear gas atleast) will break lighting and cause the infamous darkness despite there being light fixtures online

If you want to reproduce this definitely throw a teargas into metastation's armory and close the door, but I'm sure this can probably be easily reproduced elsewhere

**Comment by MrPerson** [comment]
I fixed this issue ages ago. Who broke it wtf

**Comment by Bawhoppen** [comment]
lighting is literally completely broken, it break so often

**Comment by phil235** [comment]
Probably the same issue as mech walking on a turf with a light tube making the turf dark.

**Comment by coiax** [comment]
Is this bug still present?

**Comment by phil235** [comment]
I can't reproduce it. Did someone fix it?

**Comment by phil235** [comment]
Still present.
