### ISSUE TITLE
Editing ICON var with gifs crashes server

### ISSUE THREAD

**Issue by Saegrimr** [tgstation/tgstation#16932]
Used to you could change an object or mob's ICON state to a local .gif that would be uploaded. Hence buttsky randomly in the round when I get bored or whatever.

Now it just crashes the server. 

RIP Officer Buttsky

**Comment by Dorsisdwarf** [comment]
Those two tags are incompatible, @RemieRichards

**Comment by RemieRichards** [comment]
Not true at all @Dorsisdwarf

**Comment by Dorsisdwarf** [comment]
If the issue is with BYOND, it means that there's a problem with BYOND that means we cant fix it.

If it's Not A Bug, then it doesn't need fixing in the first place. I guess "All our code is run on BYOND" would merit the tags :/

**Comment by duncathan** [comment]
it can be an intended feature of byond which causes the issue

**Comment by Dorsisdwarf** [comment]
I guess that makes sense

**Comment by MrStonedOne** [comment]
@tgstation/commit-access http://www.byond.com/forum/?post=2082593 fixed
