### ISSUE TITLE
[Box] Point Checking Console is gone from labor camp

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/tgstation#16936]
I added a small console to conveniently check how many points you needed to fill your quota.

Someone adminhelped about how points worked and we discovered the console was missing since lavaland was put in.

Labor camp remains confusing for new players to use.

**Comment by Penguaro** [comment]
@Ikarrus I'm looking into this. Right now I only see points consoles on the actual labor console. Do you roughly remember where the console was on the asteroid or when you added it so I have a general place to look?

**Comment by BeeSting12** [comment]
Is this even a boxstation specific issue? I would think it's edited on the mining zlevel, correct me if I'm wrong.

**Comment by Ikarrus** [comment]
@Penguaro It was in the general prisoner area. It was green and looked just like the claim console

@BeeSting12 this issue was created before they were separated into different files

**Comment by Penguaro** [comment]
@Ikarrus So I've investigated this and am working on a solution. One problem is that it's not just the console missing. Points are only tabulated upon sheets being added to the stacker and then claimed. Right now the console for claiming labor points also has Shuttle launch coded to it so adding a stacker and point claim console wouldn't work exactly and just the point checker would always show zero. Another problem I'm still working out is how to get the ore that was processed since there doesn't seem to be a way to reclaim it.

**Comment by Profakos** [comment]
@Penguaro 
I reported the inability to reclaim sheets in #26399, so I might close that issue if it can be incorporated into this one.  But I would like to add that placing a regular stacker console on the map, aimed at the stacker would overwrite the stacker's CONSOLE var.... which is not used for anything actually so it might as well be removed.

**Comment by Penguaro** [comment]
@Profakos What you added here is a good idea. I'll try that with my solution. Leave your issue open as it is a different problem than this. If my fix can resolve both, I'll note both. It's good they reference each other.

**Comment by PraiseRatvar** [comment]
@ShizCalev since you are the only one i see mapping

Has this been fixed? If so, tag Dorsisdwarf or a maintainer to close this (or ask someone on coderbus)

**Comment by ShizCalev** [comment]
I'm not familiar with the point redemption system, so I haven't looked into this myself.

**Comment by Penguaro** [comment]
The console was not added but there's a deeper problem in how the system functions. Just adding the console doesn't really resolve the overall issue.

**Comment by BeeSting12** [comment]
I believe this issue is no longer a problem since lavaland is the same for all maps and I've never seen any problems doing points on any map, including box.
