### ISSUE TITLE
Ghost of Poly able to attack phased slaughter demons

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#16941]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))
Be a slaughter demon. Kill Poly. Have Ghost of Poly spawn. Attack the Ghost of Poly (which does no damage). The Ghost is now pissed and starts attacking you, and will continue if you don't run away until you die.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by PKPenguin321** [comment]
ghost of poly should not be able to deal damage

**Comment by coiax** [comment]
I was on commit bf4778dba5c20b626d6273bed8daa8fcc3f15355 I will check in the morning if this also happens in master.

**Comment by PKPenguin321** [comment]
no it can do damage but i'm just saying it shouldnt

**Comment by ChangelingRain** [comment]
I can't call this a bug, because it's hilarious.

**Comment by octareenroon91** [comment]
I also like this as-is.

**Comment by coiax** [comment]
So is the "bug" here attracting GoP aggro, or it being able to harm things? Because we could turn this into a feature, where GoP attacks anything in the phased plane, like revenants, blood demons and ethereal wizards.

**Comment by KazeEspada** [comment]
This reminds when poly soloed 10 spiders.

**Comment by Incoming5643** [comment]
Ghost of poly can do damage but can't be killed outside of gibs. A player controlled ghost of poly could theoretically solo the station. But then I fully intended that.

The actual bug is that whatever poly is using as an adjacency check isn't quite right, this means he'd probably also be able to attack people hiding in lockers without destroying the locker first.
