### ISSUE TITLE
Rev scaling is busted

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#16951]
Only one revhead with 3-4 heads of staff and security multiple rounds in a row

**Comment by PKPenguin321** [comment]
really? i was revhead today and there was a second one, with only i think 4 or 5 heads

**Comment by Zilenan91** [comment]
Happened tonight around 10:00 PM pacific

**Comment by LatD** [comment]
heads.len - ((8 - sec.len) / 3) is the function which determines the number of headrevs. So for example with 3 heads and 3 security there wil only be one headrev. Same thing with 2 heads and 6 security or 4 heads and 0 security. This might need some tuning.

**Comment by Zilenan91** [comment]
Good lord

**Comment by Incoming5643** [comment]
Historically it's worked well, I don't see the problem. The absolute scaling numbers can be found in #12724

If your getting dunked as a solo head in a low sec environment you might need a bit more self-preservation. Hang back and let the converts do the work, don't risk your ass needlessly. Most single revhead losses are of the "the revhead died even though there were a ton of living revs" variety.

**Comment by xxalpha** [comment]
git gud son

**Comment by Zilenan91** [comment]
There was like 4 or 5 sec officers and three heads of staff versus one revhead how is this not a broken system, that's far too much sec for one guy to convert enough to deal with.

**Comment by Incoming5643** [comment]
gain competence, offspring

**Comment by xxalpha** [comment]
god damn it i almost spit my coffee

**Comment by Incoming5643** [comment]
This is not a bug

**Comment by xxalpha** [comment]
Yea this is a whine.

**Comment by PKPenguin321** [comment]
Somebody close this

**Comment by ChangelingRain** [comment]
Not a bug itself, though scaling might need tweaking.
