### ISSUE TITLE
Xeno queens cannot damage space vines

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#16968]
- Queens cannot damage space vines

THE ONLY BUG THAT MATTERS.

**Comment by Jalleo** [comment]
This is a critical consistency issue for glass tables!

**Comment by WJohn** [comment]
I see no problem with being able to open and close washing machines, it doesn't require deft hands. Harvesting botany trays is harmless. The only real bug here is being unable to hit space vines.
