### ISSUE TITLE
Meat Hook goes nuts if it hits a borg 1 tile away from the firer

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#16981]
Tested on a mediborg sitting adjacent to the firer. It somehow hits the borg dozens of times. Have not been able to replicate with humans at any range.

Maybe something to do with the spawn() that was used to get the beam working

**Comment by Firecage** [comment]
The meat hook also appears to randomly runtime when hitting any mob. Either it runtimes or it doesn't. And strangely, most of the times I directly click on the borg when its a few tiles away, it correctly hits them once, but if I aim behind the borg, it spams it.

**Comment by jughu** [comment]
When i outrun the hook it gaurantees this affect on humans

**Comment by alphaaBeta** [comment]
It happens with stands, too.
Also, server crashed just after someone has used it on borg. Might have something to do with it.

**Comment by vuonojenmustaturska** [comment]
fixed in #20267
