### ISSUE TITLE
Old Away Mission checks work improperly with the new number of Z levels

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#16990]
Checks for counting as dead for objectives, teleporters not working, etc, all used if(Z > 7) or whatever.

This means that these properties apply to the random seeded space levels that were just added.

**Comment by Incoming5643** [comment]
M A G I C  N U M B E R S

**Comment by xxalpha** [comment]
use maxz

**Comment by SpaceManiac** [comment]
@Cyberboss I'm sure away missions are still barely functional, but the `z > 7` magic number has been eliminated.
