### ISSUE TITLE
Bluespace turfs aren't making movement faster

### ISSUE THREAD

**Issue by LatD** [tgstation/tgstation#16996]
This was still working a while ago. Bluespace turfs have `slowdown = -1` but nothing is changing.

The turf is at https://github.com/tgstation/-tg-station/blob/e3d5a240a9f4626689583a4cb16e2e536bd48552/code/modules/research/xenobiology/xenobiology.dm#L596
but the problem is probably somewhere else since this turf hasn't been changed at all.

**Comment by xxalpha** [comment]
@duncathan maybe knows what is wrong

**Comment by Core0verload** [comment]
I don't see what could be wrong with that. Will test.

**Comment by Core0verload** [comment]
NOT CONFIRMED, in my test both positive slowdown tiles and negative slowdown tiles were working as intended.

**Comment by LatD** [comment]
That's weird. I saw this on a long round on metastation in which I placed lots of bluespace tiles and movement was exactly the same for me and others on them and on normal tiles. Could lag somehow affect this then? I forgot to check if there were any PRs test merged.

**Comment by coiax** [comment]
@LatD you still experiencing this issue?

**Comment by LatD** [comment]
I haven't tested it since. Probably could get it tested on thunderdome on some round today.

**Comment by LatD** [comment]
Tested now on Thunderdome, bug is still happening. There's no change in movement speed when comparing bluespace tiles and normal floor tiles.

**Comment by Firecage** [comment]
Same issue on my side. Even tried making normal floors to slowdown 100 and -100 respectively via Var Editing....still normal movemement speed.
