### ISSUE TITLE
Shits deleting itself for no raisin

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#17004]
#1 Roundstart RD:
- Try to put ID in-hand at roundstart
- Roundstart lagspike ends, ID has disapeared, its not in my PDA, box, paper holder, folder, disposal, etc. 
#2 Reinforcement Operative:
- Pick up operative hardsuit from suit storage
- Cant switch between combat/travel mode
- Can't even pick up suit off my body
- Finally get it off
- Holding it in-hand and on my body at the same time
- Throw it
- Disappears from body AND hand at the same time
- Go to station
- NEW COP the station
- Flee into space, can't toggle mode, AGAIN
- Board station and put my suit in hand, once again sprite is in-hand AND on-body simultaneously
- Try to put suit on table
- Suit disappears from body AND table, but ceases to exist 
- LOL ded

**Comment by PKPenguin321** [comment]
1st one sounds like a runtime or something, second one is the SSU desync bug which is already reported

**Comment by Robustin** [comment]
Well for what its worth someone else had the hardsuit toggling issue but was too lazy to register and report it here.

**Comment by PKPenguin321** [comment]
hardsuit toggling issue is a symptom of SSU desync

**Comment by xxalpha** [comment]
What even is this round start lag?

**Comment by optimumtact** [comment]
Caught that ID bug

This was midround join as well, so whatever the lag is, it's not server start / game round start lag, tis' something to do with us intialising.

Some shots
http://puu.sh/ossyA/7844752900.png - ID in my inhands, but actually in my PDA

Switch hands and alt click to drag out pda
http://puu.sh/ossyX/9b6589dcd3.png - now I have two inhands but the pda is out once

**Comment by Robustin** [comment]
I was reviewing my old issues and saw this. The reason for this specific incident was resolved a while ago but I've still (recently) had large objects occasionally disappear when trying to move bags off my back and the like.

I wish I could find a way to reproduce it.

**Comment by PraiseRatvar** [comment]
@Dorsisdwarf close dead issue or give need repro/test tag
