### ISSUE TITLE
New Admin dection multitool es borked

### ISSUE THREAD

**Issue by tedward1337** [tgstation/tgstation#17005]
After observing it as an admin, I clicked deadmin, only to see it still marked me as an admin. Pls fix

**Comment by PKPenguin321** [comment]
wew

**Comment by optimumtact** [comment]
You're still an admin with an adminholder even in the deadmin state iirc

**Comment by kevinz000** [comment]
It's an adminspawn item anyhows but if you REALLY REALLY want it gone I could try (if someone tells me the stealthmin var or whatever)
But I don't even think that's necessary because it's adminspawn

**Comment by kevinz000** [comment]
also, im gonna have to fix the part where it breaks if you pick it up.
Gah, how'd that happen ;_;

**Comment by PKPenguin321** [comment]
i think this was fixed wasnt it?

**Comment by vuonojenmustaturska** [comment]
@KorPhaeron unless it was actually fixed before, #25325 fixed it
