### ISSUE TITLE
Sawing off a shotgun still blasts you if its on your back

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#17051]
I'm not sure if sawing off a shotty not blasting you anymore is a bug, but if you hold it in your hands it doesn't but if you're wearing it, it does

**Comment by coiax** [comment]
I thought the intended behaviour was: A shotgun is supposed to blast you when sawn if it's loaded.

If so, this sounds like a bug where it's not triggered if held in hand, but correctly when worn on back?

**Comment by Bawhoppen** [comment]
yes it could be that
I guessed perhaps someone removed the ability for them to blast you in the face and they forgot to make it so it didn't if its on your back or something but it could be the other way around

**Comment by phil235** [comment]
Can't reproduce, the shotgun always goes off, whether it's in your hand, back or on the floor.

**Comment by Bawhoppen** [comment]
maybe someone stealth fixed it, cause I used to be able to reproduce it every round
