### ISSUE TITLE
Megaphones appear to penetrate language barriers

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#17104]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

Xenomorphs can understand humans using a megaphone.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by Poojawa** [comment]
It is the American way.

If you speak loud enough and slow enough, they'll eventually understand you, right?

**Comment by phil235** [comment]
Long story short, megaphone code is shit.

**Comment by PKPenguin321** [comment]
I think people with no tongues can speak via megaphone too

**Comment by coiax** [comment]
Megaphones work by literally just generating an "audible message" that looks like them speaking, but doesn't go through any of the speech procs apart from a can_speak().

So it shouldn't have fly buzzing or lizard lisping or Pierre honking or anything. It's likely it'll need to be rewritten to use say, possibly with some additional spans

**Comment by PKPenguin321** [comment]
i have no idea how saycode actually works but couldn't you just make it so like when you speak into the megaphone is calls for the user to Say() or whatever then adds an extra span that makes the text larger

**Comment by Iamgoofball** [comment]
this is the power of the teamster voice
