### ISSUE TITLE
Fuel tanks occasionally do WAY too much damage

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#17112]
I've deal with a couple ahelps where someone shot a welding tank from 5-7 tiles away and were crit (from full health) by it.

Couldn't reproduce it and the logs for that kind of stuff are really spotty, so I just wrote it off.

Was testing the mech missile launcher, comparing it to Fuel Tank explosions. 

Set off the fuel tank with a missile at ~4 tiles away in a 550hp Seraph and the Seraph instantly exploded. I've been able to reproduce it occasionally using missiles on fuel tanks.

Edit: Been having difficulty reproducing it but I'm convinced it has something to do with spotty explosion code where some confluence of factors results in stuff getting hit much harder than it should. I was able to observe a similar effect on a minibomb that was able to 1-shot a Seraph from 4 tiles away despite prior and subsequent tests showing it doing only 60 damage from 1-tile away.

**Comment by KazeEspada** [comment]
So to reproduce shoot a missile at a fuel tank?

**Comment by Robustin** [comment]
Correct, doesn't seem to happen every time, but most of the time you'll get this effect. 

Didn't test clothes.

Fire damage doesn't happen because I think all damage caps at 700. 

Haven't tested

**Comment by xxalpha** [comment]
It's the projected objects that get embedded.

**Comment by Robustin** [comment]
There's no embedding, not on the bodies, and the mech gives messages when the Seraph is hit by stuff anyway.

Plus its a welderbomb + missile on an empty floor, only one tile and maybe a rod should get thrown.
