### ISSUE TITLE
Circuit Imprinter Efficiency Upgrade Does Nothing

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#17139]
Simply put, the efficiency upgrade for the circuit imprinter's reagents do nothing; if you upgrade it, the acid cost is always the same and never goes down.

@KorPhaeron

**Comment by IvanIssaccs** [comment]
The same is true of the protolathe.

**Comment by LatD** [comment]
The efficiency upgrades were removed by Kor. Circuit imprinter has been bugged since though. It actually reduces the amount of acid it uses but the text always says 20 now.

**Comment by KorPhaeron** [comment]
I keep forgetting to fix this, sorry. I think I might have actually finished it at one point but forgot to pr it
