### ISSUE TITLE
Flashlight+belt lighting bug

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#17155]
HELP: OneSevenOne/(Allen Guess) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): I found a weird bug.  If you turn a flashlight on then put it in your toolbelt, the light will stay where you were standing, instead of following you.

**Comment by optimumtact** [comment]
Worth attempting to reproduce because it may have just been lag stopping the lighting ticker from firing every tick

**Comment by Aloraydrel** [comment]
this has been reported ages ago. it works with any container with a flashlight

**Comment by WJohn** [comment]
Just tested this, it's definitely still around.
