### ISSUE TITLE
Central Command Reports can be read by any race/language

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#17197]
Any race or language can "read" or "hear" Central Command Reports. For example xenomophs can hear a report that would normally make sense that only humans can understand.
This can make use of the reports very limited as there isnt another easy way to direct/GM the crew as a whole and ONLY the crew.

Steps:
- create command report
- be xenomorph/dog/drone/monkey
- see the command report un-garbled and plane as the day.

**Comment by PKPenguin321** [comment]
I am fine with this

**Comment by peoplearestrange** [comment]
Yeah it kinda means that if you say "Crew get to arrivals! Theres some extra guns there!" you suddenly find all the xenomorphs are already waiting there... etc etc

**Comment by Dorsisdwarf** [comment]
TBF, the xenoes followed the line of ERTs back before the announcement was even made
