### ISSUE TITLE
Toggling Darkness as an observer once again toggles ghost vision with it

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#17190]
As an observer hitting "Toggle Darkness" in the Ghost verb tab, removes all other ghosts. Even with ghost vision toggled on.

Steps:
-Be Ghost
-Hit "Toggle Darkness"
-Watch as other ghosts disappear
-Try toggling ghost vision to no effect.
- Just like the old days

**Comment by Sligneris** [comment]
I couldn't reproduce it with Toggle Darkness alone, but I did experience it this way after jumping to a different Z-level
