### ISSUE TITLE
Lavaland ruin tiles are bugged

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#17222]
http://i.imgur.com/jys0YMP.png?1

**Comment by xxalpha** [comment]
That's not lavaland, that's a template. It's the furry hospital.

**Comment by KorPhaeron** [comment]
This is the result of the maploader changes. When ruins intersect with a cave tunnel or lava river, it creates these weird tiles

@duncathan @YotaXP

**Comment by ChangelingRain** [comment]
I fixed this specific instance of the issue; rivers no longer cause it(tunnels do)

**Comment by nullbear** [comment]
A lot of tiles become HONK! tiles when crowbarring them then attempting to replace them. Maybe this is related?
