### ISSUE TITLE
Heating a turf with a heater will only heat this turf and not spread the heat.

### ISSUE THREAD

**Issue by phil235** [tgstation/tgstation#17255]
Basically the turf is not excited and doesn't update the air so the temperature isn't equalized with the nearby turf until the starting turf gets excited by something.

**Comment by Jalleo** [comment]
@duncathan

**Comment by Shadowlight213** [comment]
@MrStonedOne

**Comment by MrStonedOne** [comment]
I'm refactoring some things with atmos for the freeze, i'll see if i can't figure this out.

The turf gets activated but goes immediately to sleep. so something in process_cell isn't properly taking temperature into account.

**Comment by Iatots** [comment]
@MrStonedOne anything?
