### ISSUE TITLE
Head of Security's Armored Greatcoat shows bare skin instead of jumpsuit underneath

### ISSUE THREAD

**Issue by Man-Shroom-** [tgstation/tgstation#17258]
If you put on the armored greatcoat and face south/towards the computer screen/TOWARDS YOU THE PLAYER, you can see that there is a small area in the body sprite where the jumpsuit under the greatcoat is meant to peek out, but the layers or some shit w/e do not work right and you can see right to the skin.
![2](https://cloud.githubusercontent.com/assets/6549019/14931639/ff24d620-0e3a-11e6-8d56-acacb678f5f7.png)

![1](https://cloud.githubusercontent.com/assets/6549019/14931628/e9ed6448-0e3a-11e6-8498-e3c9e644c360.png)

The area just below my neck is the offending VIOLATOR

**Comment by phil235** [comment]
some flag problem

**Comment by Man-Shroom-** [comment]
wow now that I look at these screenshots it's a really tiny bug i dunno why it bothered me so much
