### ISSUE TITLE
Mech walikng on the turfs with lights in them breaks the lightning

### ISSUE THREAD

**Issue by Core0verload** [tgstation/tgstation#17271]
1. Have a stompy mech.
2. Walk it to the tile with wall-mounted light
3. See the light darken.
4. Walk away.
5. Light is still dark.

Looks like opaque moveable objects annoy the fuck out of our lightning system.

**Comment by phil235** [comment]
Duplicate of #16927

**Comment by phil235** [comment]
Probably not the same issue after all, since I can't reproduce the smoke bug, but the mech bug is still there.
