### ISSUE TITLE
Pop maxcap

### ISSUE THREAD

**Issue by yackemflam** [tgstation/tgstation#17335]
![image](https://cloud.githubusercontent.com/assets/16517871/14953143/a79c6bca-10a1-11e6-851b-0f1406060e6f.png)

Could not join, only observe

**Comment by Jalleo** [comment]
Not a bug i believe it is a config @Mrstonedone

**Comment by Incoming5643** [comment]
You only get this message when you manage to open job selection before a living pop cap is reached but don't choose until after. Otherwise you'd get a more descriptive explanation about the cap.

**Comment by optimumtact** [comment]
I thought our caps were soft only.

**Comment by Incoming5643** [comment]
It's a living player cap, which is usually pretty soft because while 90 connections isn't that hard to do it's much harder to keep all those players alive and playing.

It's gotten far easier to hit lately because of the glut of ghost roles.

U N I N T E N D E D  C O N S E Q U E N C E S

**Comment by kevinz000** [comment]
@lzimann not an issue it's a config thing

**Comment by MrStonedOne** [comment]
Don't believe his lies, the bug is in how undescriptive the error message is
