### ISSUE TITLE
Lava staff can instakill

### ISSUE THREAD

**Issue by AlexanderUlanH** [tgstation/tgstation#17347]
In one case, lava took me from full health to dead the moment the staff was used on me.
Possibly related maybe: It was a cult round, I was a geneticist with hulk and cold-resist, I had a heal virus.
I'm not really sure how this would be reproduced, but it happens.

**Comment by KazeEspada** [comment]
Lava is just really fucking deadly.

**Comment by Zilenan91** [comment]
How do you get a a lava staff?

**Comment by Incoming5643** [comment]
It can also burn away any blob tile except the core, and keep it burned away. It can also select a tile even if it's behind dense spaces.

@Zilenan91 you kill a drake and get lucky

**Comment by AlexanderUlanH** [comment]
@KazeEspada No, this is a bug. I was hit by a lava staff and went from +100 to -100 in one tick. I'm not complaining that there are too many firestacks or there is too much fire damage per tick.
Same thing happened to @Robustin

**Comment by KorPhaeron** [comment]
I think it was just really laggy towards the end of that round, because were not able to reproduce it in the thunderdome next round

**Comment by Robustin** [comment]
I had something similar happen. When we tested it in Thunderdome it appeared to be related to the nature of lag and ticks. ~10 tests and 9 of the results were normal but got hit with one that left me in flashing red health despite moving almost instantly, was in crit before I could even finish the first roll. 

Either way the staff could use balancing.

**Comment by KorPhaeron** [comment]
Can't reproduce
