### ISSUE TITLE
Disease stealth not calculating properly

### ISSUE THREAD

**Issue by Hamfam77** [tgstation/tgstation#17357]
According to the wiki (https://tgstation13.org/wiki/Infections), if a virus has a stealth level of 3 or higher, it will be invisible to the PANDEMIC machine, so anything with stealth 2 or below IS visible. This is not the case however, because mixing Eternal Youth (Stealth 3, invisible to PANDEMIC) with Headache (Stealth -1, bringing the virus total to Stealth 2) does not make the newly created pathogen visible on the machine, when a Stealth 2 virus should be able to be seen on the PANDEMIC.

**Comment by XDTM** [comment]
I might be wrong, but i think the code defaults all stats to 1 and then applies the modifiers

**Comment by Cyberboss** [comment]
Closable after that big viro refactor

**Comment by XDTM** [comment]
Can confirm, this was no longer an issue already after i lowered the default to 0

**Comment by Cyberboss** [comment]
@lzimann
