### ISSUE TITLE
Grief Ghost health doesnt update in the status menu.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/tgstation#17369]
No matter how much damage I took, my health always showed 100% in the status menu and Revenants lack a health HuD icon.

**Comment by Aloraydrel** [comment]
Essence is your health unless you are talking about essence not going down

**Comment by Zilenan91** [comment]
Yeah essence = health, your health can't actually go down below 100% because your essence is your health

**Comment by ChangelingRain** [comment]
health is inherited from the simple animal stat panel, nothing that can be done about this unless you make them use health as essence, but that's not so easy

**Comment by KazeEspada** [comment]
Oh. Alright, that's unintuitive.
