### ISSUE TITLE
Space can be dark for some reason

### ISSUE THREAD

**Issue by Razharas** [tgstation/tgstation#17384]
![image](http://i.imgur.com/j6PDPay.png)

Dark turfs are space, when i come closer they become light again
When i go away they become dark again

**Comment by TrustyGun** [comment]
area issue?

**Comment by LatD** [comment]
I've had similar issues before too. Some weeks ago I noticed them again and flew around them as a ghost and then my dreamseeker crashed so it's possible this is a Byond 510 issue if it's related.

**Comment by Jordie0608** [comment]
Possibly related to #8282
