### ISSUE TITLE
The mime's spell action buttons always appear greyed out

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#17388]
Making it very confusing to know what's on cooldown

**Comment by phil235** [comment]
Can't reproduce.

**Comment by PKPenguin321** [comment]
Latejoin as mime. Action buttons in top left are red as if they're on cool down.

**Comment by phil235** [comment]
Only happens for latejoin mimes. I think this is not a bug specific to mime spell, but probably happens to any latejoin mob with spells.
