### ISSUE TITLE
Revenants can interact with any machines that have right-click verbs

### ISSUE THREAD

**Issue by harmonyn** [tgstation/tgstation#17409]
Cross-reporting from Paradise: https://github.com/ParadiseSS13/Paradise/issues/3357

We have fewer right-click verbs than they do, but ones that still exist:
- The gibber
- Chem grinders
- Food/slime processors

I probably missed a lot.

**Comment by coiax** [comment]
Washing machines?

**Comment by PKPenguin321** [comment]
washing machines use alt click now

**Comment by kriskog** [comment]
Still a thing. We dont have many right click verbs anymore, but seems they still arent griff ghost proof.

**Comment by dragomagol** [comment]
This appears to apply to regular ghosts as well

**Comment by ArcaneDefence** [comment]
Doesn't work for ordinary ghosts now, still works for revenants.
