### ISSUE TITLE
Dominators can't be heard through walls.

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#17412]
Last round I had trouble finding a dominator hidden inside one of the AI core walls because I couldn't hear it until I took the wall down, after I had to go get mesons to figure out exactly where it was at.

This is a problem because it takes forever to find doms hidden in walls now unless I pack mesons everywhere and just makes it easy to hide it in an obscure wall and guard 

I think this is a bug related to the recent buff to syndie bombs allowing them to be less audible.

**Comment by LatD** [comment]
If it was planted through space originally and there was no air inside the hidden tile it makes no sound right? That's another possible reason for it if it isn't related to that bomb sound.
