### ISSUE TITLE
Art canvases that are drawn on are in some cases invisible to others

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#17427]
not as in the drawing is invisible, as in 100% invisible. usually to people who were not observing it being drawn on.

**Comment by Incoming5643** [comment]
might have something to do with resource caching with fcopy_rsc

**Comment by WJohn** [comment]
Can confirm, this is extremely common. I'd say almost 50% of people can't see your art.

**Comment by RemieRichards** [comment]
this is Byond's fault, could try forcing a new asset to be sent every 10 or so pixels I guess.

**Comment by SpaceManiac** [comment]
Duplicate of #24241
