### ISSUE TITLE
AI can see cult runes

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#17426]
https://github.com/tgstation/-tg-station/blob/35bfb9abb6d3e7952d14a1781c9ffc3a68d2df00/code/modules/mob/living/silicon/ai/login.dm
AI is supposed to just see blood splatters, but it can see runes.

**Comment by GunHog** [comment]
Oh god. That code uses "in world". You have done a very good thing, pointing out this travesty. No doubt the massive cult changes failed to account for this.

**Comment by ChangelingRain** [comment]
This code only happens when the AI logs in............

**Comment by Cyberboss** [comment]
@lzimann #22577 was reverted, reopen this
