### ISSUE TITLE
The Stimulants symptom in virology causes oxyloss and mutes (Goonchem)

### ISSUE THREAD

**Issue by XDTM** [tgstation/tgstation#17457]
Ephedrine does strange things with breath loss:

From the ephedrine section of the code

>M.losebreath = max(5, M.losebreath-1)
 
seems to set a minimum breath loss of 5 which in return means it's impossible to speak

**Comment by Iamgoofball** [comment]
will fix

**Comment by Dorsisdwarf** [comment]
The inescapable milestone

**Comment by Iamgoofball** [comment]
this is actually a GOOFMED bug FYI

**Comment by Cheridan** [comment]
goonmed got closed
