### ISSUE TITLE
Issue with lavaland template ruin spawning

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#17450]
On commit d11809196a871bc6b572f681cfe558291af750ec

I'm seeing this patterning on loaded ruins occasionally, where I think the tunnel would naturally go through. Occasionally I also see the HONK debug tiles.

![image](https://cloud.githubusercontent.com/assets/609465/15092796/e744dd52-146b-11e6-8cab-45a7863ede11.png)

EDIT: For those who don't know the golem ship, it's supposed to be all purple and not have any ordinary station tiles.

**Comment by KorPhaeron** [comment]
@YotaXP did something weird to ruins with the TGM maploader change, causing them to all spawn freezing. @duncathan fixed this, but the fix/change he did to changeturf left this weird tile thing behind.

The real culprit is of course is that floor code is scary and just edited icons

**Comment by Dorsisdwarf** [comment]
I think this is something to do with caves.

**Comment by coiax** [comment]
I think this may be related to #17222

**Comment by ChangelingRain** [comment]
This is tunnels and caused by tunnels being genned before ruins are spawned
And or it's caused by ruins using standard station plasteel flooring(which is why it turns grey)

**Comment by WJohn** [comment]
Definitely caused by tunnels. This is also still around.

**Comment by Dennok** [comment]
Now ruins have protection from random placing another ruins on it.
So this is outdated.

**Comment by kriskog** [comment]
Yeah, never seen in game so its likely fixed.
