### ISSUE TITLE
Medical huds apparently show your pref character, not the one you are playing as

### ISSUE THREAD

**Issue by imtakingabreakdontatme** [tgstation/tgstation#17487]
Guy on lavaland was playing as a veterinarian or something, so he had a random name/face.

He used the med HUD "show front/side picture" function and got a picture of his normal character.

Reply PM from-BlessedHeretic/(Kylie Rahl): View me with med huds and hit front photo or side photo. It shows my start up character, not this(?|F) RNG made one that i'm using

**Comment by nfreader** [comment]
I wasn't able to reproduce this. It looks like medhud functionality was changed since this was reported and the error case outlined here is no longer possible.
