### ISSUE TITLE
Ninja energy katana can no longer emag things

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#17504]

**Comment by kilkun** [comment]
To add onto this, disconnecting makes the spiderOS tab blank, not displaying any information. Deinit and reinit your suit doesn't fix it.

Yet more issues for ninja :/

**Comment by Bawhoppen** [comment]
It works on harm intent, has to do with phil's thing I guess

**Comment by phil235** [comment]
no, it doesn't work even on harm intent.

**Comment by Bawhoppen** [comment]
I just used it last round as a ninja

**Comment by phil235** [comment]
mm, well I guess it only works if you're a ninja...

**Comment by kevinz000** [comment]
@lzimann works now, even as nonninja.
