### ISSUE TITLE
Circuit Imprinter doesn't need 20 acid when upgraded but uses it anyway

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#17539]
On Tier 3 parts I can put only 5 acid in the Imprinter and it still gives me a board. If there's more then 5 acid in the imprinter however, it will still use up to 20 units.

This is probably the case for the protolathe as well, but would need testing and a calculator.

I don't know why acid usage was nerfed in the first place, Chem Dispensers exist, but getting more acid is annoying and only having two chances for my PACMAN board to work before I have to get acid to make a Dispenser is annoying.

**Comment by LatD** [comment]
I think this is the same as #17139
