### ISSUE TITLE
Crafted Turrets don't do shit to humans

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#17540]
Despite having like 5 settings for targeting crewmembers, none of them will aggro the turret. They appear to still target animals just fine though.

**Comment by Anonmare** [comment]
Can confirm, turrets I built in Thunderdome don't attack me last I checked. 
Except laser tag turrets when I'm wearing the opposite coloured armour.

**Comment by optimumtact** [comment]
Pretty sure I busted this
