### ISSUE TITLE
No minimap for crew monitor on metastation

### ISSUE THREAD

**Issue by Bobylein** [tgstation/tgstation#17547]
The crew monitor on metastation shows no minimap while it does on boxstation, seems odd.

Is it because the Minimap generation is turned off?

**Comment by peoplearestrange** [comment]
I've noticed this as well, was meant to report it but forgot. Im sure its a recent bug.

**Comment by Shadowlight213** [comment]
Yeah, it's because of minimap generation being off. Not a bug.
The generated minimap is cached on the server, so the box minimap shows simply because it was the last one generated before switching generation off, and is still cached.

**Comment by peoplearestrange** [comment]
Is it off for a reason? or can we turn it back on?

**Comment by Dorsisdwarf** [comment]
Lag I think

**Comment by Bobylein** [comment]
Hm but on my local server its deactivated too and I still have a minimap on box

**Comment by Shadowlight213** [comment]
Oh!. Now I remember.
It's not cached on the server, it's cached on your client I think. I remember people saying that they were seeing the wrong map when they had both servers open with different maps running.

**Comment by Bobylein** [comment]
@Shadowlight213 okay that makes sense albeit it sucks

**Comment by peoplearestrange** [comment]
Can't we use byond's new background download feature for caching the map locally? should avoid lag and will actually be useable.

**Comment by Vakulum** [comment]
would be nice. Its hard to find the right place and locate injured people if you dont have the right station on the crew monitors. More of a guesing game then...

**Comment by ShizCalev** [comment]
It's fixed. This can be closed.

**Comment by ShizCalev** [comment]
@Cyberboss

**Comment by Dorsisdwarf** [comment]
Reported as resolved.
