### ISSUE TITLE
Beheaded changeling issues

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#17554]
- Changelings being alive without a head is a giveaway that they're changelings.
- Changelings without heads can still speak and as if they had a tongue
- Changelings without heads still take toxic damage from a toxic atmosphere

**Comment by LatD** [comment]
First and third one seem okay like that.

**Comment by Incoming5643** [comment]
The changeling antag test confirmed: Decapitate the entire crew.

**Comment by Jalleo** [comment]
Welp @phil235

**Comment by PKPenguin321** [comment]
These are all non issues except *maybe* the talking one

**Comment by phil235** [comment]
All intended.

**Comment by Bawhoppen** [comment]
1st and 3rd are fine, we can fix the 2nd by changing it to be like 'X gurgles "Meme" instead of says

**Comment by coiax** [comment]
@phil235 is it intended that their death sleep->full revive doesn't grow back limbs? I've seen changelings die repeatedly looking for a body to husk so they can reroll abilities to take fleshmend.

**Comment by phil235** [comment]
@coiax It was intended, but if people think it's too much trouble for lings, I can move the limb regeneration to stasis.

**Comment by coiax** [comment]
Don't move it, just add it additionally to stasis, given it's supposed to be a full "stand up and walk away" ability.

**Comment by Shadowlight213** [comment]
Nah, leave stasis not regenerating your head. Headless lings rising from the grave to fuck your shit up is hilarious.

**Comment by PKPenguin321** [comment]
^

**Comment by phil235** [comment]
2nd thing was already fixed. I'll make stasis regenerate limbs except the head.

**Comment by coiax** [comment]
Except headless lings still breathe and are unable to wear breathmasks. I admit it's an appealing visual image though. Tbh, I think we need to split fleshmend and limb regeneration.
