### ISSUE TITLE
pAI radios work on z-level 2

### ISSUE THREAD

**Issue by kilkun** [tgstation/tgstation#17559]

**Comment by Jalleo** [comment]
They are station bounced radios inside of them i believe.
Aka please explain what the actual issue is.

**Comment by kilkun** [comment]
intercomms don't work, why should pai radios

**Comment by Dorsisdwarf** [comment]
Do intercomms really not work on Z2?

When are you ever on Z2 in a position to check?

**Comment by LatD** [comment]
Escape pods have intercomms but I can't remember if they work properly or not

**Comment by Dorsisdwarf** [comment]
pretty sure this isnt a thing. correct if wrong
