### ISSUE TITLE
Sprayed lube doesn't go away

### ISSUE THREAD

**Issue by lzimann** [tgstation/tgstation#17552]
Whenever you spray lube, 5 units or 10, it never disappears, instead, it stays lubed forever. I've tested with water and it went away after a while.

**Comment by PKPenguin321** [comment]
Sheeeeeeit
Who did this? @nullbear ?

Very high priority

**Comment by nullbear** [comment]
https://github.com/tgstation/-tg-station/pull/17333 fixes it, which has been open for like, a week.
.

**Comment by lzimann** [comment]
This was fixed already.
