### ISSUE TITLE
Drones cannot pick up packs of cards

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#17560]
?

**Comment by phil235** [comment]
clickdrag doesn't work?

**Comment by coiax** [comment]
It didn't for me.

**Comment by phil235** [comment]
it's probably also happening with paper bins.

**Comment by coiax** [comment]
No, paper bins are fine.

**Comment by phil235** [comment]
https://github.com/tgstation/-tg-station/blob/c6cad13d0ed7ca7b8fb074c6e4d7b7ed88bd8a9a/code/game/objects/items/toys.dm#L767

**Comment by coiax** [comment]
Also, the card code is weird, there's the /obj/item/toy/deck and there's /obj/item/weapon/deck, and I can't work out why. We can take out the ishuman check easily, look at what paperbins do. In fact, this MouseDrop to pickup code is so common I'm thinking of just unifying it at a proc at /obj/item if I can

**Comment by bgobandit** [comment]
we have two versions of card code for some godawful reason; the toy version is what we use

**Comment by jughu** [comment]
Why cant we pick up cards witgh the first click and inhand to shuffle and use other hand to grab a card inhand and alt-click if its on a ground/table to grab a card is it so hard?
