### ISSUE TITLE
Hand labelers can't label pill bottles

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#17588]
Mostly because it's trying to put the labeler in the bottle and not label it

**Comment by Lumipharon** [comment]
This used to work at some point.

**Comment by phil235** [comment]
and can't wrap it with package wrap.

>This used to work at some point.

Yes, but it was working due to a bug. When you labelled the pill bottle you'd get "the labeller doesn't fit inside the pill bottle", because the code is trying to store it inside.
