### ISSUE TITLE
Disinfecting with suit storage units allows 'teleportation' of things.

### ISSUE THREAD

**Issue by Crushtoe** [tgstation/tgstation#17631]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

Put hard suit in a suit storage unit, run disinfect. It will spit out the equipment. Put it on. Open suit storage unit, it says the suit is still inside. Click it, the suit suddenly teleports off of you and onto the space.

You could use this to trick security into putting on disinfected suits and then teleport their suits off them once they're in space.

**Comment by PKPenguin321** [comment]
Desync
