### ISSUE TITLE
Spray cans completely insane now

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#17663]
What did this?

50 units of ethanol + 10 units of fuel for a single spray to the face?

Hardsuits+Masks don't even completely stop an application (4-6 units still go through)?

What?

**Comment by Dorsisdwarf** [comment]
Are you sure? i cant find a PR about this

**Comment by jughu** [comment]
Yeah it is altough hardsuit/mask/sunglasses still stops the stun but doesnt stop the chems coming onto you is-a-lizard sprayed me with 2 cans last round and i got 1000 ethanol inside me causing me to fall in sleep and die

**Comment by jughu** [comment]
Altough the idea is like a little ethenol on you face when wearing protection about 5 units and 10 without i mean its Paint on your face made by chems at all

**Comment by Shapsy** [comment]
Maybe it was the alcohol change that made getting drunk way more lethal and it already had the ethanol feature from its inception, but spray cans are awful right now. Getting sprayed in the face a few times is guaranteed death even with like 10 minutes of intensive care in medbay

**Comment by KorPhaeron** [comment]
It's definitely happening

**Comment by PKPenguin321** [comment]
spraycans apply ethanol ??? why

**Comment by optimumtact** [comment]
Who tagged this not a bug eh ? :grin:

**Comment by kevinz000** [comment]
I already said this, to th eguy who added it, and apparently I got ignored?

**Comment by kevinz000** [comment]
Also I got 30 fucking units of ethonal from a rev as a head of staff once and it killed me minutes later because drunk wears off slowly.

**Comment by optimumtact** [comment]
rekt

**Comment by coiax** [comment]
Turns out the volume multiplier was set to x10, rather than x1. Learned a valuable lesson today.
