### ISSUE TITLE
Beepsky can cuff armless people

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#17709]
LEMME SHOW YOU A REAL LIMBLESS HANDCUFFS BUG RIGHT HERE

**Comment by RandomMarine** [comment]
YOU CANNOT ESCAPE THE LAW

**Comment by Shapsy** [comment]
Beepsky doesn't give a fuck about reasonable force, he just cuffs your hand to your neck

**Comment by LatD** [comment]
What should Beepsky even do to armless people? Ignore them completely? Keep stunning them forever?

**Comment by Dorsisdwarf** [comment]
Legcuff them.

**Comment by TrustyGun** [comment]
but what if they have no legs?

**Comment by Bawhoppen** [comment]
auto-switches to detain mode

**Comment by Dorsisdwarf** [comment]
One-armed legless/ nolimbed people should just be stunned once, then Beepsky mocks them and prints them a parking ticket

**Comment by Bawhoppen** [comment]
add harmbaton mode to beepsky actually

**Comment by Man-Shroom-** [comment]
parking ticket idea is funny, especially if beepsky treats the limbless person like a car that's in the wrong area

**Comment by Armhulen** [comment]
Treat em like a mulebot, give a ticket and drag to cargo
