### ISSUE TITLE
pAI related bugs

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#17721]
- pAI EMP death doesn't update face
- pAI EMP communications silence keeps ticking while in bot, but does not affect bot
- Bots cannot beep or boop
- pAIs lose their binary voice when talking normally in a bot

**Comment by kriskog** [comment]
Mostly fixed apart from the emote thing (bot "issue") and the comms silence thing. Its a bit of a minor outer edge case, and I'm not so sure it doesn't make sense if someone puts you in a bot after you have been emp'd.
