### ISSUE TITLE
Light tiles are buggy as fuck

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/tgstation#17725]
Just a couple of problems I've run into

**1)** Mapped/Admin spawned floor tiles do not have functionality of manually built floor tiles.  You can place them down or spawn them and they will spawn lit.  If you click spam them, they will turn off forever and never turn back on, ever.  It's not even a single click that will turn off, It's literally only click spam that works.  They don't even have the pulse icon either, it's just the plain on icon that they are stuck too.

**2)** The mapped/admin spawned light tiles do work however if you crowbar them, and disassemble them into their wired tile without the metal.  If you add the metal again, it will act as if it was manually built and function as normal

**3)** Floor tile functionality is inconsistent.  Sometimes when you click on a manually built floor tile, it will start flickering and other times when you click on it, it will change colors. It doesn't cycle modes via the clicks, it simply picks a functionality based on tiles around it or some other retarded thing.  It's literally awful.

**Problems this causes**
Mapping these in a map is awful because while you can edit the icon state to what you want, someone will eventually come along and turn off one the tiles via a misclick or just because it's there, and then it's permanently fucked with it's broken Icon.  This put the brakes on a map I was making.

**Comment by Niknakflak** [comment]
Another problem that I've seen is that when light tiles get damaged, they either turn off, or simply get destroyed.  This isn't so much of a problem but there are broken floor tile sprites that exist and either they aren't being used correctly in which case, that needs fixing, or they aren't being used at all, in which case the icons could probably be removed

**Comment by xxalpha** [comment]
Stop referring to the light floors are floor tiles!

**Comment by Jalleo** [comment]
Is this light tiles or floor tiles in general?

**Comment by Niknakflak** [comment]
whoops, floor tiles = light tiles, This whole issue is about light tiles

**Comment by Cyberboss** [comment]
@lzimann Fixed with vg lights
