### ISSUE TITLE
Cant load shuttles.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#17730]
Map was dreamstation.
Shuttle import landmark not found. Aborting.
The loaded template didn't have a mobile docking port! The template has been deleted.

This was for every shuttle...
@coiax 

Priority high

**Comment by coiax** [comment]
Does dreamstation have a different Z2?

Letting a shuttle be deleted if it can't import shuttles at all is a bug though, hopefully new shuttle UI will fix that by running some checks beforehand.

**Comment by ChangelingRain** [comment]
No maps have different Z2s at all.

**Comment by coiax** [comment]
Probably due to shuttle template bugs, this can be closed.
