### ISSUE TITLE
The Hand labeler

### ISSUE THREAD

**Issue by DarkRiper** [tgstation/tgstation#17743]
[Note]: # so I was playing today and a huge shuttle full of corgies docked to the station, filled with adorible corgies! so I picked a hand labeler and started giving them names, but after I named like 5 guys each time I added one more name the name of another corgi dissapeared. this made me really sad. and I hope this will be fixed.

I dont know if this matters but I was wearing a full toolbelt a Duffleback my PDA, a black jumpsuit and a full xenosuit.

**Comment by Supermichael777** [comment]
Odd, mob renaming should be permenent. You were probably loosing corgis in piles of multiple dogs.

**Comment by Jalleo** [comment]
Was it a emergency shuttle or a normal shuttle?

**Comment by DarkRiper** [comment]
it was a centcomm shuttle but that was irrelivent, admins just sent a shuttle from centcomm full of corgies, but I started tagging corgies at the bar

**Comment by DarkRiper** [comment]
@Supermichael777 each member of the crew had their own cogies and where dragging them behind them their names also vanished. ((the names of the corgies offcourse))

**Comment by AnturK** [comment]
Corgi's reset their name to real name on attackby because of the clothing namechanges. Not sure this is really an issue because the intended way to give names to pets is the collars not handlabeler.
