### ISSUE TITLE
Box armory is missing its medkit again

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#17747]

**Comment by Eaglendia** [comment]
inb4 "not a bug"

**Comment by Aloraydrel** [comment]
A meme of the ages

**Comment by GunHog** [comment]
What is it with the armory and that medkit? Seriously. @Steelpoint

**Comment by Steelpoint** [comment]
Someone hates it.

I don't know, I haven't touched the map in months. I'm sure if I went through all the merged PR's recently I could find whoever removed the medkit.

**Comment by KorPhaeron** [comment]
We already know which PR it got removed in
