### ISSUE TITLE
Borgs apparently count against escape alone

### ISSUE THREAD

**Issue by Eaglendia** [tgstation/tgstation#17745]
A traitor from a recent late-night round redtexted his hijack objective when he was alone aboard the shuttle with a squad of emagged borgs.

I'm not sure whether escape alone still exists or was completely reworked into the new "escape with no loyalists aboard", but borgs counting against at least the former was supposedly fixed ages ago by  #11652

**Comment by RemieRichards** [comment]
> when he was alone aboard the shuttle with a squad of emagged borgs.
> he was alone ... with a squad of emagged borgs
> alone
> with a squad
> alone

**Comment by Eaglendia** [comment]
His objective was to escape on board the shuttle with no Nanotrasen-loyal crew, which he _definitely_ did. The only entities on the escape shuttle were him, three hacked engineering cyborgs, and, come to think of it, a non-traitor's corpse.

So either borgs have since been reworked to count against escape alone again (when they haven't at times in the past), cyborgs (hacked or otherwise) count as Nanotrasen-loyal crew members, or dead people count as living Nanotrasen-loyal crew members.

**Comment by Supermichael777** [comment]
ditch the corpses no evedence man

**Comment by Jalleo** [comment]
It may of been a person in crit if not something else failed.

**Comment by ChangelingRain** [comment]
I'm guessing so, but did this nerd check all the lockers, sleepers, crates, and, if this was meta or one of the other different-shuttled maps, suit storage units?

**Comment by YakumoChen** [comment]
still needs fixed.
