### ISSUE TITLE
Ghetto surgery tools not performing intended function.

### ISSUE THREAD

**Issue by demonfiren** [tgstation/tgstation#17768]
Performed ghetto surgery according to wiki (organ manipulation, legion heart.)

Using red crowbars as hemostats doesn't work, furthermore, neither matches, lighters, or welders can be used to cancel surgery despite being valid as cauteries in normal surgical steps.

**Comment by xxalpha** [comment]
Likely not a bug, just outdated wiki.

**Comment by PKPenguin321** [comment]
Crowbars are only hemostats for steps that require prying (removing organs), NOT clamping bleeders, and the cautery thing is likely just not implemented. Not a bug, consistency issue at best.

**Comment by demonfiren** [comment]
Well, after the crowbar failed I did pinch the guy with wirecutters, which seemed like the only other candidate, and it did brute instead of fixing shit.

It's an issue chiefly for ashmemes, they get a table but no tools (especially no saw), and trying to fix shit as one of them when ghetto surgery is half broken is ew.

**Comment by phil235** [comment]
wirecutters for clamp bleeder step work fine. The crowbar thing is due to wiki being outdated.
Not being able to stop a surgery with ghetto cautery items is a bug though.

**Comment by bgobandit** [comment]
can this be closed
