### ISSUE TITLE
Firearm executions are subject to normal attack targeting

### ISSUE THREAD

**Issue by Eaglendia** [tgstation/tgstation#17788]
Picture this: you're executing a gang boss, you're aiming your gun at his head for like 20 fucking seconds and that part from Imogen Heap's "Hide and Seek" is already queued up and playing (or at least it is in your head), and when you pull the trigger it somehow hits him in the arm because of regular attack RNG and between armor and limb damage cap he doesn't even fall into crit

And then he laughs at you for a while and it's just embarrassing

**Comment by Supermichael777** [comment]
whip out your baton and go to town

**Comment by PKPenguin321** [comment]
This is some stormtrooper aim level shit

**Comment by Jalleo** [comment]
@KorPhaeron this has to be a feature.

**Comment by Steelpoint** [comment]
I noted it in this bug report a while back: https://github.com/tgstation/-tg-station/issues/16474

**Comment by phil235** [comment]
yeah, this is a duplicate
