### ISSUE TITLE
Bear traps act like pseudo handcuffs

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#17786]
Beartraps can not be taken off if you're strapped in a chair, and prevent you from using your hands.
As in, can't draw weapons, can't do shit except for move around with WASD which doesnt' make sense because it's LEGCUFFS and not HANDCUFFS.

**Comment by Eaglendia** [comment]
New meta

**Comment by Dorsisdwarf** [comment]
What why do beartraps disable your hand who did this.

**Comment by phil235** [comment]
Can't reproduce

**Comment by kevinz000** [comment]
What do you mean cannot reproduce?
Don't know about you but whenever I get hit with any traps or snares on Sybil I'm unable to take anything out of my backpack or whatnot...

**Comment by phil235** [comment]
>Beartraps can not be taken off if you're strapped in a chair

Intended, resisting makes you unbuckle first, then resist again to remove the beartrap. Or, have another person remove the trap when you're buckled)

>and prevent you from using your hands.

Nope, can't reproduce this on sybil.

@kevinz000 Did you update your BYOND version to the newest beta version? The one that causes issues with attacks and progress bars.

**Comment by kevinz000** [comment]
.. havn't updated in a while. whatever then.
