### ISSUE TITLE
Martial arts attacks don't log

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#17809]
They don't appear in the attack log at all.

Tested with both krav maga and wrestling belt

@Iamgoofball @PKPenguin321

**Comment by PKPenguin321** [comment]
Oh god what
Uhh

**Comment by PKPenguin321** [comment]
I'm gonna pin this on goof since all I did was steal his code and make it use action buttons, I'll see if I can maybe fix it when I get home
