### ISSUE TITLE
Using a beaker on a janitoral cart consumes the beaker.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#17800]
Had a big beaker of space lube I was going to prank the janitor with, when I used the beaker on his little pull cart it transferred 10u and the beaker vanished.

**Comment by bgobandit** [comment]
I cannot reproduce this.

**Comment by Durkel** [comment]
Here's some additional details then.

It was on meta.
I was a clown gang head with clumsy.
It's the janitors pull cart, not the pussy wagon.
It was the large 100u beaker.

**Comment by bgobandit** [comment]
Still can't reproduce this

**Comment by lordpidey** [comment]
The beaker might be being put inside of the trash bag?

**Comment by Durkel** [comment]
That could be what happened, I'm not sure if it was fully loaded or not, I'll close this then if that checks out.

**Comment by Bawhoppen** [comment]
I'd think it is almost certainly the trashbag thing, been buggy since phil's attackby thing

**Comment by Jalleo** [comment]
@phil235

**Comment by phil235** [comment]
not my fault

**Comment by swankcookie** [comment]
so this should be closed. misclick is not an issue

**Comment by lordpidey** [comment]
It's not exactly a misclick.

Take the janitorial cart, put a bag on it.
Then pickup a beaker with water in it, and click on the janitorial cart.
The beaker will transfer liquid to the cart, and THEN be put inside of the trash bag.

**Comment by swankcookie** [comment]
oh, i misunderstood. thanks

**Comment by optimumtact** [comment]
Unreproducible
