### ISSUE TITLE
Many progress bars do not appear anymore, and those that do are slow to update.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#17803]
Originally, almost everything that had a timer on it, such as putting windows into their frames or deconstructing walls, had timers. These don't have them anymore, and for the few remaining instances where they do appear, they are extremely slow to update. They often jump random, large chunks of the bar, rather than being smooth like it used to be.

**Comment by Eaglendia** [comment]
I feel like at least part of this might be because of how shitty the server has been recently

**Comment by Durkel** [comment]
#17659

Been having the same problem and they said it was a byond problem even though I was running the same version they were. Dunno man

**Comment by xxalpha** [comment]
check tick?

**Comment by Razharas** [comment]
Its lag

**Comment by Jalleo** [comment]
@MrStonedOne

**Comment by RemieRichards** [comment]
Lag / Get off of version 510.1332

**Comment by LatD** [comment]
I've had it for some weeks now too and I was and still am on 510.1341 so something broke or it's just lag

**Comment by RemieRichards** [comment]
it appeared atleast twice (the initial bug, a fix, and then a regression) around 510.1339/1340/1341/1342

**Comment by Jalleo** [comment]
Is the 1345 version fixed from this issue?
