### ISSUE TITLE
O- blood fucking poisions people

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#17812]
NOT EVEN O- BLOOD IS SAFE FROM BUGGY BLOOD TYPES

**Comment by phil235** [comment]
likely related to #17422

**Comment by optimumtact** [comment]
I don't understand the bug report?

Are you saying just having o- blood starts to kill you?

**Comment by anconfuzedrock** [comment]
no matter what your goddamn blood type blood acts like your blood type is the wrong one and pumps you with toxin

**Comment by Bobylein** [comment]
Oh that explains why people keep dying if I try to rescue them with blood transfer

**Comment by Bobylein** [comment]
what the hell... sometimes I can reproduce it, sometimes not. I am confused.

Made several tests now and sometimes the same blood type poisons me and sometimes it doesn't, even had different results with the same blood type after a server restart.

**Comment by phil235** [comment]
The issue is likely a discrepancy between the blood type referenced in your dna (the one that the health analyzer shows) and the type of the actual blood reagent that's inside you.
