### ISSUE TITLE
Ghost images runtime

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#17817]
runtime:
wrong type of value for list
proc name: updateghostimages (/mob/dead/observer/proc/updateghostimages)
  source file: observer.dm,488
  usr: (src)
  src: Urist Mcspaceman (/mob/dead/observer)
  src.loc: the wall (197,89,1) (/turf/closed/wall)
  call stack:
Urist Mcspaceman (/mob/dead/observer): updateghostimages()
Urist Mcspaceman (/mob/dead/observer): updateghostsight()
Urist Mcspaceman (/mob/dead/observer): Toggle Darkness()

**Comment by Shadowlight213** [comment]
@Ricotez this is your code runtiming

**Comment by Ricotez** [comment]
was this running on a private server?

**Comment by Shadowlight213** [comment]
@Ricotez this is running live on the servers.
I think the runtime I pulled was from basil.

This also causes ghosts to be invisible with darkness turned off unless you set the see other ghosts to default or white sprites.
