### ISSUE TITLE
Space makes stuff TOO cold

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#17814]
A tiny breach to space will make whole sections of the station instantly sub-zero temperatures apparently. Does weird shit like make items get pulled to seemingly random spots due to space wind, and the insane drop in pressure from the temperature going down makes the area crush people to death extremely quickly.

From what I can tell it was caused by https://github.com/tgstation/-tg-station/pull/17727 and while it is a feature I sincerely doubt it was meant to be *this* strong.

**Comment by Bawhoppen** [comment]
you know this almost makes sense and is a good balance thing but hugbox memes so

**Comment by MMMiracles** [comment]
ZAS-lite

**Comment by PKPenguin321** [comment]
@Bawhoppen there is a difference between dangerstation and "smash-one-window-and-literally-everbody-dies station"

**Comment by Razharas** [comment]
In local tests it actually was taking quite a while to take down temperature to real cold levels so i sped up it a bit by artificially making termal conduction coefficient of space 100% instead of usual 40%

**Comment by Razharas** [comment]
Tested on live servers, 6x6 room with one broken window gets to dangerous levels of pressure after 3 minutes, dangerous levels of cold after 4
I think its rather slow if anything

**Comment by PKPenguin321** [comment]
needs more testing really because as far as i can tell it's really inconsistent, hard to be certain with atmos though since air is invisible

**Comment by RandomMarine** [comment]
Atmos goggles when?

**Comment by Poojawa** [comment]
Add a testing/debug sprite to nitrogen/oxygen, in the same manner as plasma/N2O is. Then you can see how atmosia functions easier I'd imagine.

**Comment by Metacide** [comment]
Seems pretty crazy how fast the station freezes now, with a few tiles of breach or even just the one. Spacewind also seems to go in random directions all over the place which really messes things up, and combines with freeze-walkspeed and pressure damage to cause a whole lot of rapid deaths.

If we're going to have this sort of rapidly-lethal atmos breach gameplay we need properly reactive firelocks too - without them everywhere starts to depressurise and freeze incredibly quickly.

**Comment by Durkel** [comment]
Can we get a high priority on this? It's making the game unplayable from one small crack in station. I've seen a space dust put hole in arrivals by where the white ship docks, furthest point possible. In five minutes the entire hallway was -193c and just stepping off the arrival shuttle would kill you before you reached the bridge.

**Comment by Razharas** [comment]
Ok ill fix it

**Comment by Steelpoint** [comment]
I like this but I think as noted above the station's fire alarms need to respond to rapidly dropping tempretures and shut as well, to counter hull breaches so 50% of the station doesn't vent out after several minutes.

**Comment by optimumtact** [comment]
@Steelpoint sounds like a good idea for post freeze
