### ISSUE TITLE
Client crashes on attacking objects with items

### ISSUE THREAD

**Issue by Razharas** [tgstation/tgstation#17821]
1 - the attack overlay stays on top of the object for longer than it should(visually)
2 - after each attack you get a chance of the client crash
3 - the faster you mush the mouse button the more likely is client to crash(doubleclick issue?)

**Comment by Razharas** [comment]
@phil235

**Comment by phil235** [comment]
Can't reproduce.

**Comment by optimumtact** [comment]
Hmm I wonder, @phil235 and @Razharas what version are you byond clients right now?

**Comment by phil235** [comment]
I'm on 510.1336, not the most recent one that makes progress bars buggy.

**Comment by Razharas** [comment]
Im on the latest beta

**Comment by MrStonedOne** [comment]
this would have been fixed with the add_overlay rewrite.
