### ISSUE TITLE
Unstable mutation toxin can turn people into golems

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#17831]
https://github.com/tgstation/-tg-station/blob/b95cf44123961282e0df7a5fed30802b5311e248/code/modules/reagents/chemistry/reagents/other_reagents.dm#L362

Golems are hard coded as unable to be able to change species with unstable mutation toxin, but are valid species to transform into. Bug or intentional?

**Comment by LatD** [comment]
The golem block was removed when species blacklist was added. I've changed many golems to other species in xenobio. But I thought turning into golems was blocked. Do all the new golem species have the blacklisted var on?

**Comment by anconfuzedrock** [comment]
wait what? I swear after turning myself into a golem I drank unstable mutation toxin in liquid form and that worked

**Comment by coiax** [comment]
@KorPhaeron Pick the intended behaviour plox

1 - Golems can be turned into other races via unstable mutation toxin.
2 - Golems cannot be turned into other races via unstable mutation toxin, but are a valid gravity-well style target, rendering further attempts pointless.
3 - Golems cannot be turned into anything, and nothing can be turned into golems.

Pick one plz.

**Comment by LatD** [comment]
That's missing the one we've had until that free golem change broke it: golems can get changed to other species but nothing can be turned into a golem. And before this we had that option 3.

**Comment by KorPhaeron** [comment]
Whatever you wanna do
