### ISSUE TITLE
Humans with lizard heads have a human length nose and can grow hair

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#17836]
CRITICAL ERROR

**Comment by xxalpha** [comment]
Who's been race mixing?

**Comment by optimumtact** [comment]
That's hilarious

**Comment by nicbn** [comment]
Fix the nose only and we will have Cuca as a playable race
![image](https://user-images.githubusercontent.com/20824501/48973667-ba9e5a00-f02b-11e8-8f7f-52e89c20ad06.png)
