### ISSUE TITLE
The floor is lava event turns space turfs into lava

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#17841]

**Comment by KorPhaeron** [comment]
Here is what is required to fix this:

Redo all station areas as

/area/station

Preferably divided into things like

/area/station/hallway

/area/station/department

/area/station/maint

And then update every map.

**Comment by bgobandit** [comment]
well you have fun with that

**Comment by KorPhaeron** [comment]
Yeah exactly

**Comment by LatD** [comment]
Can't you just make it affect floor/plating types on z1? Without using areas

**Comment by KorPhaeron** [comment]
It's significantly laggier to change the icon on every floor on the Z level than to just change an areas icon
