### ISSUE TITLE
you can regrow a persons limbs by monkeying them and turning them back into a human

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#17854]

**Comment by anconfuzedrock** [comment]
what this is a bug

**Comment by phil235** [comment]
the solution to this bug is a feature.

**Comment by PKPenguin321** [comment]
yep, i mentioned this in the dismemberment PR. until we have dismemberment for all carbons and not just the /human subtype this is pretty much resolvable.

**Comment by Cheridan** [comment]
Also they totally did this in the Animorphs books so I'm calling this a feature

**Comment by Jazaen** [comment]
Not. A. Bug.
Getting people into genetics scanner when you tell them you are going to monkey them is hard enough. Besides, there is so e small ammount of radiation, or something.

**Comment by ChangelingRain** [comment]
This is a feeeeeature
