### ISSUE TITLE
Lube and Water slips never disappear

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#17884]
This has been an issue for weeks, I though the slip PR was going to fix it but I still saw it on display today.

Eternal slips are not fun.

**Comment by Cheridan** [comment]
#17874 already fixed :skull:

**Comment by Durkel** [comment]
>been happening for over a week.
>dies to it.
>makes a issue report now.

WEW

**Comment by Robustin** [comment]
@Durkel 

I made a report before but I was told that a pending PR would fix it. Said PR was merged, nothing was fixed, so I made a new one.

**Comment by Boredone** [comment]
Server needs to update before the fix actually takes effect Robustin. And the fix was merged around the same time as the Spray can changes, which has a changelog you can check to see if we are that updated.

**Comment by ChangelingRain** [comment]
This is already fixed, yeah.
