### ISSUE TITLE
BZ gas can't be detected by analyzers.

### ISSUE THREAD

**Issue by lzimann** [tgstation/tgstation#17880]
They also can't be filtered by gas filters.
The same thing applies to the agent B gas(althought it's impossible to get without admin intervention, so not a big deal).

**Comment by bgobandit** [comment]
are you sure, becaues this worked for me in testing

**Comment by Iamgoofball** [comment]
gas filters manually check for gases to remove, you have to add it

**Comment by lzimann** [comment]
The analyzer item, but I assume it goes for all of them?

**Comment by bgobandit** [comment]
not necessarily, they all have different code

**Comment by lzimann** [comment]
well they do detect, just doesn't show up if bz concentration is 0%, closing this
