### ISSUE TITLE
(Human) eyes cannot be removed using surgery: organ manipulation.

### ISSUE THREAD

**Issue by ChemicalRascal** [tgstation/tgstation#17883]
Which is a shame. Eyes are delicious.

Ideally, removing eyes could leave someone not-quite-permanently blind (not to mention remove all their eye-based implants). Probably a very conditional sort of feature, but hey, we have tongues now.

**Comment by ChemicalRascal** [comment]
_Eye_deas forum, you mean.

And yeah, will do.

**Comment by PKPenguin321** [comment]
For what it's worth though this is a neat idea that I'm surprised we don't have already

**Comment by xxalpha** [comment]
Instead of slapping a feature request tag, just close issues like this.

**Comment by Dorsisdwarf** [comment]
Slain most cruelly
