### ISSUE TITLE
Removing simulated turfs killed our startup

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation#17892]
Before that pr was merged startup time was pretty manageable.
After: it's much worse, although not noticeable on the prod servers as they're pretty high spec.
#16026

**Comment by RemieRichards** [comment]
This sparked by SAVAGE comments by Lummox about our start up performance:
http://www.byond.com/forum/?post=2086980&page=2#comment19776775

**Comment by optimumtact** [comment]
@tgstation/commit-access

**Comment by KorPhaeron** [comment]
If you're suggesting we go back, which poor bastard is gonna change everything again?

**Comment by bgobandit** [comment]
The same one who fixes https://github.com/tgstation/tgstation/issues/17841

**Comment by optimumtact** [comment]
I'm not suggesting we go back, I'm suggesting we find out why

**Comment by optimumtact** [comment]
unscientific timings on my vm for time from startup to the warning about active turfs

pre 0m55

post : 2m49s

**Comment by MrStonedOne** [comment]
This is from space turfs changing how they init lighting. (ie, starlight) I'll look at a way to make them only do this if its near a normal turf, in the mean time, we could disable starlight by default

**Comment by optimumtact** [comment]
I think it's just a bunch more stuff in simulated turf new that is now being called on all unsimulated turfs

**Comment by optimumtact** [comment]
much better
