### ISSUE TITLE
ChemMasters 3000 can't be used in boxstation

### ISSUE THREAD

**Issue by Archie700** [tgstation/tgstation#17902]
When I used the ChemMaster 3000 after the TGUI upgrade in Box, the message "The requested interface (chem_master) was not found. Does it exist?" was returned. As far as I know, MetaStation ChemMasters were working normally.

**Comment by Dorsisdwarf** [comment]
This doesn't seem physically possible that it would be different on box and meta (Unless you mean Sybil and Basil, they're often on different update schedules)

**Comment by phil235** [comment]
@Bobylein

**Comment by Bobylein** [comment]
Uhhhmmmmmm looking into it

**Comment by Bobylein** [comment]
Can't reproduce, works fine for me and others on Sybil metastation

**Comment by coiax** [comment]
I have been seeing occasional similar problems with shuttle manipulator TGUIs reporting that the interface file is missing for me, but other people can use it fine. It might be a cache issue or something, maybe when the server updates or test merges?

**Comment by Archie700** [comment]
Worked fine when I tested it again in box, but yeah it may have been a cache issue

**Comment by optimumtact** [comment]
Unreproducible
