### ISSUE TITLE
People can emote in crit

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#17905]
> Duke Hayka flaps his wings.
> Duke Hayka flaps his wings.

**Comment by MMMiracles** [comment]
It's the only way to get medbay to actually notice you dying in the lobby as they keep stepping over your dying body clueless.

**Comment by coiax** [comment]
People can shift-click to examine, it's not difficult. But this is still a bug, helpful as it is.

**Comment by TheRealGLH** [comment]
If a doctor wasn't smart enough to wear a medical HUD to be able to pinpoint whoever needs their attention the most, I wouldn't trust them with healing me in the first place.

**Comment by XDTM** [comment]
Should *deathgasp be usable in crit?

**Comment by GunHog** [comment]
Yes, that is one way to let yourself die, as well as triggering your explosive implants.(by dying)

**Comment by coiax** [comment]
I've always just death whispered. Also explosive implants should be triggerable even in crit. I'll see what I can do about that.

**Comment by Cheridan** [comment]
duplicate of #15399
