### ISSUE TITLE
Dismembering a head with the god hand causes the brain to be unenterable

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#17907]
On Sybil, a Plasmaman's head got cut off the dead body, and the player was unable to reenter their body (which should be their brain). The brain from Examine "appeared totally lifeless".

EDIT: Reproduced on e4755a8d4b4da35cf11d357d2276721dfca46053

1 - Spawn human mob occupied by player
2 - Attack human mob's head with Chaplain's "God Hand" (null rod variant)
3 - Keep attacking, head will dismember post death
4 - Brain will drop, will be lifeless, player will be unable to enter brain
@phil235

**Comment by Crushtoe** [comment]
I'll have to test with various null rod types and see if it affects more than just the hand.

**Comment by PKPenguin321** [comment]
Are we sure this isn't a plasmaman issue

**Comment by coiax** [comment]
The test was with a plain human.

**Comment by phil235** [comment]
Does the same issue occur with brain removal surgery?

**Comment by KorPhaeron** [comment]
@phil235 

Was my fault, fixed it
