### ISSUE TITLE
ADD A COOLDOWN TO THE COOKIE MAKERS AHHHHHHRHGHHHHHH

### ISSUE THREAD

**Issue by Cheridan** [tgstation/tgstation#17918]
http://i.imgur.com/fDMUBdF.png

**Comment by Shadowlight213** [comment]
No. Add auto clicker to cookie gen. MORE COOKIES

**Comment by coiax** [comment]
Just add a high energy cost.

**Comment by Cebasiz** [comment]
they're pretty tasty cookies, i'd say 300 energy ez

**Comment by swankcookie** [comment]
honestly we're gonna have to rename to chocolate station soon.
