### ISSUE TITLE
abductor ufos have black outline on outside

### ISSUE THREAD

**Issue by Cheridan** [tgstation/tgstation#17919]
http://i.imgur.com/LdrPimA.png

it looks really bad when observing

**Comment by ChangelingRain** [comment]
It looks great for the abductors and people they abduct, though.

**Comment by ChangelingRain** [comment]
Pick your poison; looking shit for ghosts, who we don't give a shit about, or looking bad for abductors and the people they abduct, who we maybe care about.

**Comment by Cheridan** [comment]
at least make it not so ugly and immersion breaking, maybe like make the surrounding space tiles all black as well and put some walls around those, so they're all in a little black box

**Comment by Durkel** [comment]
Is this just the ufos or all the alien alloy walls? Keep in mind we can make those on station now.

**Comment by KorPhaeron** [comment]
I have a zany plan involving objects that look like space pixel shifted over the turfs so only people on the outside see them but it probably isnt worth the time

**Comment by Steelpoint** [comment]
This doesn't affect in game people at all and is a positive thing.

This only literally affects coders and ghosts.

**Comment by swankcookie** [comment]
@KorPhaeron this should just be closed for the reasons stated above.

**Comment by XDTM** [comment]
closable?
