### ISSUE TITLE
dual wielding chainsaws

### ISSUE THREAD

**Issue by dhostak** [tgstation/tgstation#17924]
Possible to dual wield chainsaws by having someone throw them and having the other person catching them.  This doesn't take the extra arm slot so you have a free hand and can repeat the process.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by PKPenguin321** [comment]
We should make it so if you try to catch an item with 15 brute or higher that has sharpness your arm just comes off

**Comment by callanrocks** [comment]
This isn't much of an adva...

Flukes dual wielding eswords.

**Comment by PKPenguin321** [comment]
^ when you throw a dual esword it closes iirc
