### ISSUE TITLE
the round does not auto-end when all players are dead

### ISSUE THREAD

**Issue by hornygranny** [tgstation/tgstation#17928]

**Comment by lordpidey** [comment]
I have a hunch this might be a server config issue.

**Comment by GunHog** [comment]
I remember this being a feature a long time ago. Perhaps it was removed for causing problems with testers?

**Comment by PKPenguin321** [comment]
This is an ancient feature that I think was either removed or made into a config that's off by default.

**Comment by KorPhaeron** [comment]
Gun Hog has it right
