### ISSUE TITLE
Colorful reagent grenades colour DARKNESS

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#17937]
Excessive use of colorful_reagent generates tiles of just solid colour.

These are darkness tiles, you can toggle  their appearance on and off with Toggle Darkness.

With darkness on.
![image](https://cloud.githubusercontent.com/assets/609465/15742582/c195d786-28b7-11e6-8e7a-a43d071cd0a4.png)

Darkness turned off.
![image](https://cloud.githubusercontent.com/assets/609465/15742591/ce7b1c5e-28b7-11e6-8d38-46a24f72020d.png)

**Comment by lordpidey** [comment]
[http://img.ifcdn.com/images/5b10b85d79fecc48b87d6c1a05e84b2adfecbd6cbdf2dc062c60803bcafac214_1.jpg]Advanced darkness!(url)

**Comment by Iamgoofball** [comment]
why would we ever fix this

its a feature i swear
