### ISSUE TITLE
Issue: Legion Soul not correctly healing sicknesses.

### ISSUE THREAD

**Issue by Repukan** [tgstation/tgstation#17931]
![shit](https://cloud.githubusercontent.com/assets/19575516/15548126/ed8706ec-2274-11e6-9b32-fd354185c572.PNG)

Got infected with a disease. Tried to heal it using a legion soul that had been preserved with stabilizers. Still the disease persisted.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by coiax** [comment]
Do you know when this bug was not present? It'll be helpful in tracking down the cause. Even a rough timespan would be good.

**Comment by Repukan** [comment]
No idea if it ever happened before. I know it gets rid of bleeding though, but i think that's just a brute damage by-product.

**Comment by coiax** [comment]
Legion souls are just subclassed hivelord cores, which perform a revive(full_heal = TRUE, admin_heal = FALSE). An admin_heal removes diseases, handcuffs, regenerates limbs and missing organs. I'm not sure if hivelord cores ever cured diseases. I will investigate.

**Comment by coiax** [comment]
If anyone can remember a time where they did cure diseases, then it's a bug.

**Comment by Repukan** [comment]
It was stated like so in the wiki, hence the report. Then again, maybe it was just bad wording on that part.

**Comment by PKPenguin321** [comment]
I know they cured diseases back before lavaland, as I was mining with no suit (healing viruses were keeping me alive), ate a hivelord core, and quickly froze to death.

**Comment by LatD** [comment]
Checking the history of https://github.com/tgstation/tgstation/blob/a599ad0f196045c5ed58bacab21fc88ba76ea2e4/code/modules/mob/living/living.dm
It used to have 
```
for(var/datum/disease/D in viruses)
	D.cure(0)
```
but it got removed in a commit around February 5th, the commit isn't showing up on history.

**Comment by Repukan** [comment]
Ah, So i guess it isn't a bug then?

**Comment by optimumtact** [comment]
Nominally tagging as bug until someone finds commit that removes and there is an explanation

**Comment by LatD** [comment]
Found it. It got removed at https://github.com/tgstation/tgstation/commit/81ce777ec26eaa42a4b6aa101124bf4658f256ed#diff-df7fe1c87ccd86bb2878257cd89bc8f5

@phil235 is/was there any reason not to have revive (or the new procs replacing it) cure viruses?

**Comment by phil235** [comment]
Maybe I thought some of the code that called revive(full_heal=1) shouldn't cure viruses. But after reviewing all current calls of revive, I can't  seem to find any potential issue. So you can change it back, I guess. The relevant code is here.
