### ISSUE TITLE
There is no way to clone decapitated victims without very, very complex detail

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#17942]
If you get your head cut off you can either get borged, AI'd , otherwise MMI'd, or you can get brain transplanted, because if I understand this right you can't put heads back on corpses so no cloning

**Comment by TechnoAlchemisto** [comment]
Not really a *bug*. Asking to be able to reattach heads is a feature request my dude.

**Comment by XDTM** [comment]
Also there is the cyborg head option

**Comment by GunHog** [comment]
Should just be able to clone using the head. The brain is the critical organ here.

**Comment by PKPenguin321** [comment]
You can add a prosthetic cyborg head, drop the brain in, and clone

**Comment by optimumtact** [comment]
Some things should be hard.
