### ISSUE TITLE
Shuttle not arriving to station

### ISSUE THREAD

**Issue by alphaaBeta** [tgstation/tgstation#17956]
Happening on MetaStation, Bagil 

Server revision compiled on: 2016-05-26
0925d1bb2911b64af0a38205e7e182c0e3c983c1

`ADMIN LOG: dock(): shuttle MetaStation emergency shuttle cannot dock at MetaStation emergency evac bay, error: width_too_large`
is being spammed constantly

**Comment by coiax** [comment]
*gargling noises*
