### ISSUE TITLE
nuke can set station to code green

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#17964]
1. Have station alert level on any level other than green
2. Insert disk/code into nuke
3. Turn safeties off and back on
4. The alert level is forced to green

**Comment by PKPenguin321** [comment]
Oh and also if you mash the nuke buttons a bunch and turn it off and back on the station can get stuck on delta despite the nuke being deactivated

**Comment by xxalpha** [comment]
tgui nuke when

**Comment by Shadowlight213** [comment]
Odd. Doesn't the alert level drop to red from delta if the nuke is disarmed?
I'm guessing the safeties are calling the alert level lowering regardless of if the nuke is armed or not.
