### ISSUE TITLE
The Legion of the Necropolis Door can get on the station if it enters a hand teleporter portal

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#17960]
![image](https://cloud.githubusercontent.com/assets/6778786/15591843/80cb9050-236d-11e6-81e8-726014630c16.png)

![image](https://cloud.githubusercontent.com/assets/6778786/15591878/a9c2dc70-236d-11e6-9906-8ff7a5f74d2a.png)

I  knocked on the door and teleported away using the handtele because I wanted to see the Big Boss man it appears he followed

But uh... totally new best way for antags to kill the station amirite

**Comment by Durkel** [comment]
Feature.

**Comment by Zilenan91** [comment]
100% a feature

**Comment by Anonmare** [comment]
Undoubtedly a feature.

**Comment by Zilenan91** [comment]
fakj you

**Comment by xxalpha** [comment]
Isn't this the whole point of portals? It'd be weird if it didn't work like this.

**Comment by Jalleo** [comment]
@KorPhaeron

**Comment by drynwyn** [comment]
Working as intended
