### ISSUE TITLE
Create antagonist buttons can turn ash walkers into antags

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#17971]
Which is an issue if that antag is, like, gangboss

**Comment by Anonmare** [comment]
Ash gang OP pls nerf

**Comment by coiax** [comment]
One of the issues here is that some antags require equipment to do anything. Traitor code gives up if it can't find a radio or PDA to issue you TC, despite the fact that a hidden uplink can literally be any object. Same with gang and their gang tools.

**Comment by Cebasiz** [comment]
lava ssssserpentsssss rule
