### ISSUE TITLE
New grabdrag ruins everything, feature pushed through despite freeze

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#17989]
**C O D E R   D I S P A R I T Y**

Borg dragging is so hard right now, not to mention the opposite: dragging cyborgs. When you ctrl-click it just fucks up and ungrabs a half second later. Got one round against an emagged borg ruined when I couldn't drag it, and another AI round where I was malf was hellish for borgs because they had a shit ton of trouble dragging people to the borging machine.

**Comment by Dorsisdwarf** [comment]
Yeah, borgs couldnt be grabbed, so that probbably messed up the current system.

**Comment by phil235** [comment]
Can't reproduce. Give me more info...

**Comment by phil235** [comment]
Found the actual bug by testing different scenarios.
