### ISSUE TITLE
program freeze using electrical maint. power monitor

### ISSUE THREAD

**Issue by pajeetpooloo** [tgstation/tgstation#17986]
The byond client freezes up every time I try to use the power monitor in electrical maint. This happens despite restarting byond and relogging. No other obvious signs or symptoms show.

**Comment by LatD** [comment]
Which Byond version do you have?

**Comment by GunHog** [comment]
You should also state your Internet Explorer version and Operating System. It could be related to TGUI.

**Comment by pajeetpooloo** [comment]
BYOND 510.1344
Windows 7 64bit
All Internet Explorer files completely removed from the system (using no frills TGUI) 

Haven't had any prior problems with monitor, pda, and other machine interfaces in other locations.

**Comment by RemieRichards** [comment]
>All Internet Explorer files completely removed from the system

Not true, IE6 is like, hardcoded into Windows, so you have atleast the backend of IE6.
if you download an updated version of IE (IE11 for example) the UIs will work better for you.

**Comment by Iamgoofball** [comment]
1. why did you remove all of IE

2. why did you remove all of IE

3. reinstall IE

**Comment by LatD** [comment]
Does the power monitor have any unique code that would be causing this then? If there's some easy way of avoiding this then it could be done. But reinstalling new IE probably fixes this particular case.

**Comment by Jalleo** [comment]
Its probably due to how byond requires IE for tgui to even work properly and tgui is designed on newer versions of IE i believe.

**Comment by ShizCalev** [comment]
Will close in a week without repo.
