### ISSUE TITLE
Pulling a person as they get infected by a blob spore makes the zombie but leaves the corpse

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#18012]
It probably manually moves the corpse instead of forcemove, woop.

**Comment by PKPenguin321** [comment]
@phil235 this seems really similar to https://github.com/tgstation/tgstation/issues/17993

**Comment by MMMiracles** [comment]
https://github.com/tgstation/tgstation/blob/2cfb2d8eedb39e36c3b6db9456fb32ba57fbb5ee/code/modules/mob/living/simple_animal/hostile/zombie.dm#L132

is the offending section, so probably would want to chuck that in if he sees this

**Comment by Incoming5643** [comment]
That's not blob zombie code, that's simple animal zombie code. They are not the same thing mechanic wise.

**Comment by MMMiracles** [comment]
I grabbed the wrong one, didn't notice seeing how zombies and blob zombies use almost the same thing
