### ISSUE TITLE
Crafting menu now annoying to use.

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#18025]
Each items part is now overly large and the crafting menu now feels overly clunky to and annoying to use. And a few times when I tried to go to the foods subsection, the crafting menu just decided to stop working and crashed.

**Comment by callanrocks** [comment]
Remove menu, return righteous tablecrafting.

**Comment by Iamgoofball** [comment]
# FEATURE REQUEST CLOSE THIS

@Cheridan @RemieRichards @KorPhaeron @Razharas @ChangelingRain @duncathan @phil235

**Comment by Firecage** [comment]
My god @Iamgoofball Will you fuck off? Since this is a valid issue and not a feature request.

**Comment by Iamgoofball** [comment]
the crashing is the only problem which has not been reported for awhile

**Comment by Firecage** [comment]
@Iamgoofball >Not reported in awhile.

Well, people still do complain about it crashing for them, and it does for me aswell. So yes, its still a VERY active and gamebreaking problem.

**Comment by Iamgoofball** [comment]
good thing I made a fix #19325
