### ISSUE TITLE
goofball's wrestling belt has fucky grabs

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#18020]
I'm guessing this was caused by phil's grab/pull rewrite. When you PUT SOMEBODY IN A CINCH with the slimjim wrestling belt or whatever the fuck it's called, you put them in a permastun which as far as I could tell you were not able to break out of.

**Comment by Iamgoofball** [comment]
it's a 5sec stun

i'll lower it to 3 seconds, it's so you have time to actually use a cinch move on them

the real bug is that the cinch kept disabling itself annd I had to keep re-applying it

**Comment by PKPenguin321** [comment]
jesus christ you get stuns off of grabs that can instantly stun and convert into a move that causes a small explosion on you with this belt, yet people complained about the weaken(1) on krav maga???
what the fuck

**Comment by MMMiracles** [comment]
WRASSLIN'

**Comment by Iamgoofball** [comment]
@PKPenguin321 buff krav maga 2k16

**Comment by PKPenguin321** [comment]
welp this techincally isnt a bug just a balance meme soooo
