### ISSUE TITLE
Newscaster spams common radio whenever an announcement is made.

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#18034]
![newscaster spam](https://cloud.githubusercontent.com/assets/8237862/15633227/3108ee64-2575-11e6-84ec-94478debf2d3.jpg)

**Comment by phil235** [comment]
Which map was it? Can't reproduce on Box. It was most likely intercoms and station-bounced radios relaying the message.

**Comment by Cebasiz** [comment]
i'm pretty sure this was round specific. it only occurred that time and was probably just intercom / whatever looping.

**Comment by GunHog** [comment]
If it happened on only one round, then it could have been some troll!

**Comment by Hatfish** [comment]
Odd, I swear someone said it had been happening for a few rounds before.  Ah well.
