### ISSUE TITLE
Using the gibber with a empty container puts a gib inside the container

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#18035]
So put someone inside a gibber with some storage container on the left and it will place a gib inside of it.

![nicememe](https://cloud.githubusercontent.com/assets/13092039/15633367/57630e1a-2579-11e6-850a-48584bf7174b.png)

**Comment by GunHog** [comment]
That is...kind of awesome!

**Comment by PKPenguin321** [comment]
haha what
