### ISSUE TITLE
Lizard faces are broken again.

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#18031]
![muh special snowflakes](https://cloud.githubusercontent.com/assets/8237862/15633112/38ad0904-2573-11e6-9077-10c5075b7487.jpg)
![tgstation bagil english 100 free lag capitalist bomb xix 2016-05-29 075755](https://cloud.githubusercontent.com/assets/8237862/15633113/39a069d2-2573-11e6-80de-52c64f43b217.png)

**Comment by phil235** [comment]
I blame #17059 obviously.

**Comment by bgobandit** [comment]
Lizard tails are also broken, they only show up from the north facing view

**Comment by phil235** [comment]
think the whole is just due to lizard mutant bodyparts using the layer number in their icon name, since the wing stuff added a layer, the numbers no longer match. So tbh the real issue comes from the lizard parts icon name, it's not shadowlight's fault.

**Comment by bgobandit** [comment]
@ChangelingRain

**Comment by PKPenguin321** [comment]
yo that's a really creepy lizard

**Comment by Incoming5643** [comment]
They shouldn't have needed to add another layer to begin with. This is specifically what BODY_BEHIND_LAYER, BODY_ADJ_LAYER, and FRONT_MUTATIONS_LAYER are for
