### ISSUE TITLE
Spirit board bugs

### ISSUE THREAD

**Issue by LatD** [tgstation/tgstation#18040]
- Users can't see the letters written on the spirit board if there's no lighting at all. This was broken by some lighting changes last year.
- Sometimes spirit board works when there's only one human next to it and ghosts can write with it
- Most letters come 2 or even 3 times when written by ghosts. This happens often but not always.
- If you open the letter window, you can't close it. There's no cancel button.

**Comment by coiax** [comment]
> Most letters come 2 or even 3 times when written by ghosts. This happens often but not always.

The spooooooooky interference
