### ISSUE TITLE
Gibtonite explosion does not actually destroy gibtonite

### ISSUE THREAD

**Issue by JustAnotherUserGH** [tgstation/tgstation#18044]
Whilst mining on Lavaland - standard Box round on Sybil, nothing special - with the standard Kinetic Accellerator, I shot a piece of gibtonite, intent on using it to clear a bunch of space in short order. While the explosion still went off fine, the tile of rock wall the gibtonite was in - as well as the flashing gibtonite itself - persisted, and became indestrucible - no amount of KA blasts or attempts to stop it's reaction with a mining scanner worked. Tested it another couple times to the same result. Attached is a screencap of me standing next to one of these broken pieces.
![gibtonitebugimage](https://cloud.githubusercontent.com/assets/19363814/15636544/52829222-25fa-11e6-9133-d254ca781b1c.png)

**Comment by ChangelingRain** [comment]
@MrStonedOne #17970
