### ISSUE TITLE
Anything that's not harddefined to go into the grinder but still has reagents can't go in the grinder

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#18050]
Anything that contain reagents give a "cannot be refined into a reagent" message when attempting to add it to a grinder unless it's on a hard defined list.

Didn't used to be the case.

Extends to things like pills

**Comment by TechnoAlchemisto** [comment]
Probably similar to the issue with grinders not accepting things like plasma, uranium, etc.
