### ISSUE TITLE
Lavaland Crashed Prisoner ship: No flashlights/ In general Enviormental issues with lavaland spawns

### ISSUE THREAD

**Issue by vulpineryth** [tgstation/tgstation#18055]
There is no way to get a Flash light for the prisoner ship spawn in Lavaland, making it next to impossible to actually navigate the land without stepping into lava. Suggested fix: add Seclights near the sleepers.

Also in general Air in these spawns often easly leak out without any proper internal Enviormental systems like in the larger ruins areas, and one time a fucking Goliath was able to get into a Seed shuttle spawn

**Comment by Bawhoppen** [comment]
uh the dead officers have seclites, theres mining lanterns, and theres also a light emitter

**Comment by coiax** [comment]
If you don't want the air to leak out, don't open the door. Also, mob spawning in ruins has been greatly reduced by mobs being deleted when the ruin is placed.

**Comment by Jalleo** [comment]
@KorPhaeron

**Comment by optimumtact** [comment]
Please file these on the ideas of feedback forums
