### ISSUE TITLE
Singularity can apparently expand from stage 1 to stage 2 when next to field

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18062]
This means that it can eat part of the field.
![image](https://cloud.githubusercontent.com/assets/609465/15659032/026aa8e8-26bc-11e6-9b7c-ea88d386c358.png)

**Comment by Man-Shroom-** [comment]
Immediately after this screenshot was taken, the singularity expanded AGAIN into a 3x3 shape and bit out a chunk of the field and escaped

**Comment by RemieRichards** [comment]
@Iamgoofball 

The ```Beam()``` effect must be different to the old containment effect (which was a MACHINE hilariously) so the vars are different, thus it's no longer immune to the effect of the sing.

**Comment by hornygranny** [comment]
it's not a beam yet, on the live revision it's still machinery

**Comment by hornygranny** [comment]
https://github.com/tgstation/tgstation/blob/master/code/modules/power/singularity/singularity.dm#L151
this is intended for some reason. normally will not happen as the singularity will hit stage 2 before it moves around
