### ISSUE TITLE
Shuttle roadkill damage can hit more than once

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18061]
When a shuttle arrives, it gibs all nonhumans and deals damage to humans. I made a visible message happen for this, but that's just highlighted that if you're in the middle of an arriving shuttle, you will almost certainly die from the repeated damage instances because it's 120 damage per step.

Is this intended? Or should it be capped at one instance maximum.

**Comment by Dorsisdwarf** [comment]
You SHOULD die, but yeah this doesnt seem intentional

**Comment by PKPenguin321** [comment]
it should just gib you again i dont know why we removed that
