### ISSUE TITLE
syndicate bomb disarming bug

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#18064]
If you cut the syndicate bomb wire that triggers it, you have about a tick of time to cut the defusal wire, which means that you can get the bomb explosion message yet prevent the bomb from exploding.

Maybe not a bug, but it definitely seems like one.

**Comment by LatD** [comment]
That's probably caused by the timer. Cutting one of the two activate wires sets the timer to 0 so the explosion itself comes a tick later when the bomb checks that time is 0.

**Comment by Firecage** [comment]
This must have been fixed already. I tested it on my local repo before trying to make a fix, and it worked perfectly. It detonated instantly with no time to cut other wires.

And apparently someone already fixed this issue according to IRC.
