### ISSUE TITLE
Krokodil addicts aren't appearance zombified

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18074]
Instead they're only zombified if they already are??

**Comment by KorPhaeron** [comment]
It's okay you still get fix credit even if you don't make an issue report before fixing

**Comment by coiax** [comment]
I'm really just too lazy to think of a good branch name. Also, don't give me fix credit for this, this is literally a bug I made.

**Comment by KorPhaeron** [comment]
You're fixing way more stuff than you're making features anyway so
