### ISSUE TITLE
improvised shotgun recipes is broken

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#18080]
Both table and UI crafting variants broke. You can't apply the pipe to the modular receiver, so I'm guessing it's a problem with pipes?

**Comment by LatD** [comment]
I think the shotgun was moved from shotgun.dm to revolver.dm to be a revolver subtype. This happened a day or two ago so this might have caused it.

**Comment by phil235** [comment]
yeah I moved it into another file, but why would it cause an issue?

**Comment by Thunder12345** [comment]
Can't reproduce it myself either

**Comment by PKPenguin321** [comment]
Odd. How are you able to do it? Tablecrafting, slapcrafting, both?

**Comment by Thunder12345** [comment]
Tablecrafting, didn't try slap

**Comment by PKPenguin321** [comment]
I guess if this hasn't been reproduced I'll close it. I have no idea why it wasn't working, though...
