### ISSUE TITLE
Wabbajack shuttle doesnt rotate very well

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#18097]
![shuttle](http://puu.sh/pbeKl/de9c981e56.jpg)
This was on metastation
@coiax

**Comment by coiax** [comment]
This  can't be solved until @xxalpha solves the mystery of why it can't be opened in the map editor.

**Comment by xxalpha** [comment]
Have you tried ticking the map and compiling it?

**Comment by ChangelingRain** [comment]
Technically incorrect; it could be solved, as it's a code-side rather than a map-side problem.
