### ISSUE TITLE
Lava tiles around Ash Walker nest not properly visible to the living

### ISSUE THREAD

**Issue by JustAnotherUserGH** [tgstation/tgstation#18091]
Pretty clear cut; spawn as Ash Walker, grab some lights, walk out expecting lights to follow me, step into a tile of pure blackness that lights me on fire immediately. Same thing happened to a couple other Walkers. Turns out the nest was right on the coast of a lava lake - which, by the way, also made it impossible to safely exit. If I had to guess, the invisible lava is probably an issue with the basic shape of the ruin placement or something. It was near round-end so I spawned in again to get it properly in caps. Was all visible as a ghost though.
![1](https://cloud.githubusercontent.com/assets/19363814/15663592/89560e14-26f4-11e6-8809-b062ec8d010c.png)
![2](https://cloud.githubusercontent.com/assets/19363814/15663576/638e3698-26f4-11e6-99cd-4da92f722dcf.png)

**Comment by xxalpha** [comment]
So that blackness is supposed to be lava?

**Comment by KorPhaeron** [comment]
Yes

**Comment by ChangelingRain** [comment]
I FIXED THIS I'M PRETTY SURE IT WAS KOR'S FAULT ALL ALONG
