### ISSUE TITLE
Invisible floor tiles on box.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#18104]
There are several invisible floor tiles obscuring the wires near the particle accelerator and one tile right above the incinerator in maintenance. You can use a crowbar to pry them up and get a floor tile, but they're invisible before that. There could potentially be more but these are the ones I've noticed so far.

**Comment by phil235** [comment]
@xxalpha related to your map edits?

**Comment by xxalpha** [comment]
Probably.

**Comment by xxalpha** [comment]
Actually, it's certainly my edit's fault, but in my defense oranges merged it before it was ready.
