### ISSUE TITLE
The nar'sie rune can be scribed in space

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18102]
Make a floating room in space, pressurise it, put a tp rune inside.

Scribe summon nar'sie rune, crew is told the location is Space. Crew does not find your secret cult box, Narnar ascends.

Bug or feature?

**Comment by KorPhaeron** [comment]
It should check valid station areas instead of Z level (reuse the dominator checks)

**Comment by xxalpha** [comment]
No, don't limit it to station areas.

**Comment by Anonmare** [comment]
@KorPhaeron As someone who's done this before, it's pretty easy to nab the station blueprints and make the cult box an area.

**Comment by coiax** [comment]
It's possible to check if an area is an original station area though, and not one made via blueprints

**Comment by TechnoAlchemisto** [comment]
I don't think this is so much of a bug as a balance issue

**Comment by ChangelingRain** [comment]
If you want, you can also literally scribe the rune on a space tile.

**Comment by pudl** [comment]
This is awesome and should not be removed

**Comment by Iamgoofball** [comment]
bug, you cant stop the summoning if we build a box in space and summon there
