### ISSUE TITLE
Revolution rounds can happen without heads of staff in round start.

### ISSUE THREAD

**Issue by lzimann** [tgstation/tgstation#18106]
So, a round in Sybil started, it was revolution, but then this happened:

> ADMIN LOG: The roundtype (revolution) has no antagonists, continuous round has been defaulted to on and midround_antag has been defaulted to off.

![viva](https://cloud.githubusercontent.com/assets/6282424/15681703/ac9c89f2-2730-11e6-923c-4943efd80e81.png)

No heads but still a rev.

**Comment by Incoming5643** [comment]
Roundstart code is supposed to assure that at least one head exists in every round, but occasionally it derps out for whatever reason (maybe it picked the solo head rev).

It's weird the round reported there were no antags, maybe that one was added by a badmin later to try and fix this? I'd say it was a latejoin rev head, but those are only ever made from normal revs, which couldn't have existed first in this situation.

But really the issues here was more that there were enough people to play revolution and no one had a head set even to low.

**Comment by Shadowlight213** [comment]
@incoming5643 I'm wondering if this is a byproduct of the antag roll before job change.
The game might have rolled and assigned the head rev before it assigned people to jobs and made any heads. Head check might be too late to bail out on the mode 

Also, heads getting priority assignment was removed, so having a head role set to low, wouldn't auto make you a head if you had another role set to high.

**Comment by Shadowlight213** [comment]
@incoming5643 actually, looking at rev code it doesn't check for heads as a requirement at all.
The earliest head check is post setup where it checks to see if it should make more than one head rev.
The actual elegibility for rev only checks if it can make a head rev.

**Comment by Incoming5643** [comment]
Well there was a reason that priority roll existed and this is it.

**Comment by CrazyClown12** [comment]
This happened to me the other day. No heads of staff were present so the round just ended near instantly.
