### ISSUE TITLE
The doomsday device is disabled when the AI core is destroyed, even if an AI APC copy exists

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18105]
Old malf, the timer would still tick down. New malf, the doomsday device is stopped. Intentional?

**Comment by LatD** [comment]
I remember some talk in deadchat soon after new malf that this was intentional. Something about "if the AI has to leave its core, it gave up".

**Comment by KorPhaeron** [comment]
LORE: The bomb is located in the AI core

GAMEPLAY: If you abandon your core you don't get your bonus win of wiping out the station
