### ISSUE TITLE
Catsplosion is still happening, call a fucking exorcist.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#18117]
REEEEEEEEEEEEEEEEEEE

http://imgur.com/OIMpbw9

Sibyl.
8:38 pm est.
1f712be59de38e45d27115fa7cf9dd949fbbe0ef
No tests active.

**Comment by Iamgoofball** [comment]
how did runtime survive all those rounds

**Comment by optimumtact** [comment]
probably during the low pop times

**Comment by Incoming5643** [comment]
Like I said that last pull didn't solve the problem, it just masked it.

**Comment by GunHog** [comment]
Do. Not. Fix.

**Comment by Shapsy** [comment]
Just remove cat mating or something just please actually fix it

**Comment by Cebasiz** [comment]
the code is trying to tell us something

it's like those guys that survive hanging several times

you just have to bow to the cosmic will, man.

**Comment by Shadowlight213** [comment]
The actual problem here is that runtime saves any grown cats and deploys them next round.
They then will mate with said cat, and save all the kittens, plus that cat, at round end.

**Comment by lzimann** [comment]
seriously, we should just remove this already

**Comment by Iamgoofball** [comment]
look, all you have to do is

1. kill runtime

**Comment by kevinz000** [comment]
@lzimann havn't seen this in a long time.

**Comment by Iamgoofball** [comment]
Yeah we removed runtime persistence

**Comment by optimumtact** [comment]
No we didn't, It just got nerfed heavily
