### ISSUE TITLE
Fix shuttle docks

### ISSUE THREAD

**Issue by pudl** [tgstation/tgstation#18128]
At the moment shuttles are required to occupy a perfectly rectangular area. Nothing can intrude upon this. Consequently oblong shuttles with say indented entrances have been changed to fit this rule. For example the asteroid shuttle had its airlocks pulled out into a weird hallway thing thats pretty awful looking. Would it be possible for shuttle docks to only search for tiles that have a shuttle area on them so we can again make weird shuttles that wont have the entrances taken with them?

Tag this as feature request

**Comment by WJohn** [comment]
I thought you could use areas specifically so they did not have to be rectangular, and give them some leeway into where and how they can dock?

**Comment by pudl** [comment]
Shuttles dont have to be rectangular they have to occupy a rectangular space

**Comment by WJohn** [comment]
Right, well that's not a problem as long as you use areas, because then the rectangular space can safely overlap anywhere around the station. The areas let you do some precision ship docking without chunks of the station suddenly disappearing. Or did the modular shuttle change make it so you can't do that anymore?

**Comment by pudl** [comment]
I guess you cant do it anymore because shuttle docks will take anything in their space with them shuttle area or not

**Comment by coiax** [comment]
None of what you are saying is true. And the asteroid shuttle hasn't been changed.

**Comment by ChangelingRain** [comment]
However, anything in the rectangular area the shuttle moves to will be hit by it, even if the shuttle doesn't touch it; this is very easy to observe with box's huge-ass white ship.

**Comment by pudl** [comment]
@coiax Yes it has. The airlocks have been extended out 2 tiles to make it fit the rectangular area

**Comment by KorPhaeron** [comment]
We shouldn't really have feature requests open I should probably close them all
