### ISSUE TITLE
Invoking Inath-Neq doesn't work properly

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#18135]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)
Affected targets keep the blue color permanently, but the invoker doesn't turn blue

**Comment by Iamgoofball** [comment]
???????????????????????????????????????????????

**Comment by KorPhaeron** [comment]
what goof said

**Comment by SkowronX** [comment]
clock cult

**Comment by Xhuis** [comment]
https://www.youtube.com/watch?v=68ugkg9RePc

**Comment by ChangelingRain** [comment]
The people in range included one anima fragment and two humans including the person invoking it, if that helps.
