### ISSUE TITLE
kinetic accelerators have less range diagonally

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#18133]
thanks pixel projectiles

**Comment by swankcookie** [comment]
how fucking far are you trying to shoot from?

**Comment by TechnoAlchemisto** [comment]
KA's have piss range anyhow

**Comment by kevinz000** [comment]
literally an edge case.

**Comment by kevinz000** [comment]
@lzimann this bug applies to all projectiles, not specifically kas.

**Comment by optimumtact** [comment]
Is this still a thing @kevinz000 ?
