### ISSUE TITLE
Slipocalypse Grenade didnt work on Shuttle

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#18152]
So I ran out to the center of the shuttle activated my slipocalypse grenade and everyone was able to run around perfectly fine. I instantly got murdered I dont have a screenshot sorry

**Comment by coiax** [comment]
So did the grenade fail to deploy?

**Comment by Thunder12345** [comment]
Couldn't reproduce this

**Comment by Kromgar** [comment]
I saw a flash when i activated the grenade and I saw the clusters launch around the shuttle

**Comment by KorPhaeron** [comment]
I saw the clusters, but only a couple of soaps

**Comment by Thunder12345** [comment]
I saw the clusters and a huge pile of soap
