### ISSUE TITLE
Drone Shell Dispenser bug

### ISSUE THREAD

**Issue by Midaychi** [tgstation/tgstation#18155]
Bug: Drone dispenser cannot be deconstructed or have its material ejected, so If you fill the drone shell dispenser with metal without putting any glass in, not only will the drone dispenser be unable to have any glass put in, but the material in there can't be removed and you can't deconstruct the machine to get it out.

What was expected: To be able to at least eject material.

What actually happened: Pile of junk.

Version affected: 7942972ed0bf8a9310ac955f27ffe9d714e6f97e

**Comment by lzimann** [comment]
I'll see if I can add a tgui to them, so you can remove the materials properly.

**Comment by Mervill** [comment]
It should be easy to prevent overfilling of one type of material .... *should*

**Comment by XDTM** [comment]
crowbar removal was added after this issue, by the way, it should have been closed

**Comment by lzimann** [comment]
Fixed on #20805
