### ISSUE TITLE
permafrost has some serious issues

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#18169]
last night, a new coder came into the IRC to ask about where chameleon helmet code is

i ask him why because muh code babby and he replies "I'm not gonna tell you until you tell me where the code is because you'll steal my merge token"

the problem with the permafrost is that it encourages secretive coding and paranoia about other coders when it comes to fixes

now, most of us dont do this and we're being good sports about it

but that's because most of us either 1. haven't realized this yet, or 2. aren't coding anything atm

however, new coders are going to, as demonstrated by this new coder, see this as "i cant let other coders know what I'm doing, or i lose a merge token"

this is bad on so many levels because now new coders aren't going to be working together, they're gonna be working against us all because they know they get a merge token for fixing a bug, and letting others know about this bug might result in them losing that token

there's also another aspect that hasn't been contested yet, but another aspect of "merge tokens" is that the very name and concept implies you'll get your PR merged in the end if you have a token
this hasnt happened yet but I forsee it happening soon

ps. if you're skipping to the end and just planning to say "goofball u just dont like it because u have to fix bugs skrub git gud", please stop being a dipshit and R E A D

**Comment by Razharas** [comment]
People with such attitude arent going to get very far anyway so not an issue

**Comment by Iamgoofball** [comment]
@Razharas yeah they are, because the system encourages them over the average coder?

i have no more incentive to report bugs until after the fact because now I can fix it and then file a bug report right before hitting the open PR button

or I could not report the bug until I have a feature ready

dont you fuckers see whats going to happen

how am I the only one able to look past the current day and see "this will happen if we go down this path", fuck

**Comment by Cheridan** [comment]
Nobody's going to be sniping bugs away from people like this, so this person's paranoia is absurd and unfounded.
