### ISSUE TITLE
Non-servants can use the clockwork proselytizer

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#18163]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)
@Xhuis

**Comment by Anonmare** [comment]
Is this a bug though? I mean, if you're an Elder God would you disapprove of non-believers unwittingly spread your influence?

**Comment by Xhuis** [comment]
It makes sense for it to be usable by everyone, but gameplay-wise it's bad.
