### ISSUE TITLE
AI Sat on Metastation is not getting any power.

### ISSUE THREAD

**Issue by alphaaBeta** [tgstation/tgstation#18164]
Wire in engineering foyer, connecting the satellite with the main power grid is absent.
[](url)
![](http://puu.sh/pdZ9y/15b55de0c1.png)

**Comment by KorPhaeron** [comment]
@Metacide

**Comment by Metacide** [comment]
AI satellite has its own independent SMES cells which should power everything for hours and hours, also has a backup PACMAN generator. 

The wire pictured is incomplete but allows you to hook up the station to the satellite to repower it or allow you to power sink it at the same time as the station, but you needn't bother if nothing goes wrong.
