### ISSUE TITLE
The equipping of gangster items causes message spam in low slot circumstances

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18176]
> You are unable to equip that!
> You are unable to equip that!
> You are unable to equip that!

To replicate.
1) Start server
2) Equip Butler costume, or anything else that doesn't have a backpack.
3) Via Antag Panel, become gangster head, equip equipment.

**Comment by Firecage** [comment]
Not just an issue related to gangster items, and not just via the antag panel. Though yes, it is an edge case. Rarely I have experienced this with other, random, items aswell while playing the game.

**Comment by bgobandit** [comment]
can this be closed because gang is kill @optimumtact
