### ISSUE TITLE
Lavaland ruin lighting bug

### ISSUE THREAD

**Issue by Cheridan** [tgstation/tgstation#18188]
http://i.imgur.com/YylHZlI.png

The dark area directly south of the shuttle is actually lava. It's not generating light for some reason

**Comment by Cheridan** [comment]
http://i.imgur.com/d13vGSn.png

Better image, you can see how the lighting is messed up in the box around where the ruin was loaded

**Comment by xxalpha** [comment]
This is a duplicate.
