### ISSUE TITLE
Emagged barbot beer deals damage

### ISSUE THREAD

**Issue by GeneralGoose** [tgstation/tgstation#18213]
https://github.com/tgstation/tgstation/blob/79bffc4f64a5f08e70d7aa1a3ec132a70bca47fd/code/modules/reagents/chemistry/reagents/toxin_reagents.dm#L284
Looks like it's supposed to be just a sedative, but it inherits toxpwr = 1.5 from original Toxin and therefore deals toxin damage.

**Comment by Dorsisdwarf** [comment]
this is not a bug. The description is wrong, barbots get a deadly poison when emagged, as known by most servicebot players (Notice its on_mob_life, where after 50 cycles it suddenly starts doing huge damage?)
