### ISSUE TITLE
Loading tablecraft recipes for food makes my client stop responding

### ISSUE THREAD

**Issue by Deputi** [tgstation/tgstation#18212]
While the food recipes are loading, my client stops responding until it's done loading. This takes around 30 seconds and it happens every time I close and reopen the window. As a chef, I have to open the recipe window every time I want to make food or check a recipe, so having it freeze my client every time makes chef pretty much unplayable. This didn't happen with the previous version of tablecrafting.
![pls no](https://cloud.githubusercontent.com/assets/4474395/15779205/eed8fd02-2968-11e6-8927-39b455a75a69.png)

**Comment by LatD** [comment]
Do you have newest version of Byond and newest IE? Probably related to #17986

**Comment by Deputi** [comment]
I have IE 11 and byond 510.1345

**Comment by xxalpha** [comment]
add the tgui tag @Dorsisdwarf on both issues

**Comment by Incoming5643** [comment]
tgui takes forever to load on older machines and the crafting window is huge. I'm not shocked this is happening.

**Comment by Incoming5643** [comment]
Does the tgui menu for crafting (especially the food category) make your client crash?
Consistently, yes: 4
Occasionally, but it usually just lags like a bastard: 3
It takes a while to load but I survive: 1
It's a pretty short load I don't get what people are on about: 8
Cleanbot: 5
Did not vote: 47

**Comment by coalescentwinter** [comment]
Same happens with me: not a crash but a particularly long wait of "Not responding". Happens every time I go to the food category, and even worse when I finish crafting a recipe. (so far tried with Enchiladas, Apple Cake and many others, so it's not a specific recipe).
Windows 10 user, with the default IE11. Byond updated to the latest version (510.1347)

**Comment by Firecage** [comment]
Same issue here. Makes my client stop responding and sometimes it crashes.

**Comment by PJB3005** [comment]
I told you.

#16702

Good thing @neersighted neglected my concerns and then fell of the face of the planet.

**Comment by actioninja** [comment]
doesn't use the same UI system anymore
