### ISSUE TITLE
Lighting is still extremely buggy.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#18229]
![](http://i.imgur.com/0bRz3z3.png)

I'm not quite sure how or why these things happen, but I don't think anyone interacted with these tiles. Happened on metastation, likely on all other maps.

**Comment by Bawhoppen** [comment]
this issue gonna get closed our lighting system is perfect

**Comment by WJohn** [comment]
So to expand on this: Closed lockers seem to be a source of this bug. When you open the locker, everything's fine again, but as soon as it's closed the lighting bugs out on that tile. You can also drag the locker out of it (leaving the lighting still bugged), and open/close the locker on a new tile to bug out the lighting there, too.

**Comment by phil235** [comment]
is there a light source inside the locker?

**Comment by WJohn** [comment]
No, at roundstart lockers don't do this. You have to open them and close them for the lighting to bug out on that tile.

**Comment by phil235** [comment]
Oh, maybe the light object is getting shoved inside the locker when you close it?
