### ISSUE TITLE
The clockwork slab really needs a better interface

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#18253]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)
It's multiple chained input menus right now and that's godawful, it should be something similar to the syndicate uplink but in clockcult style.

**Comment by coiax** [comment]
I can make one in TGUI, but I'll need someone better at css and shit to make the "theme" like we have for NT and Syndicate stuff.

**Comment by ChangelingRain** [comment]
I can provide color choices but I don't know shit about tgui or css.

**Comment by Durkel** [comment]
I know everyone is crazy about tgui but I'm like to mention that for larger lists of items it's really fucking slow. I'm not sure how much clockwork cult has to work with, but trying to make food on a tgui crafting menu is a absolute pain in the balls. 10 seconds to open the menu to craft a salad is bad, and I can't imagine trying to spend that time trying to get something I need under pressure.

**Comment by ChangelingRain** [comment]
Clockwork cult doesn't have nearly that many things, thank god. Even if it did take 10 seconds that'd still be better than the chained input menus though

**Comment by Imagebard** [comment]
SUMMONING THE ELDRITCH GODS ON A _RE-PURPOSED CHAT MENU_
_CRUOX CRUO_
