### ISSUE TITLE
The AI has camera vision of half the escape shuttle while in flight

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18277]
Which is vertically aligned with the title screen, which the AI can also see. Maybe this is that weird thing about the AI seeing the sides of the map sometimes?

**Comment by YakumoChen** [comment]
This has always been a problem and there are a lot of spots where the AI is just permanently blind around the station, such as where the White Ship docks.

**Comment by coiax** [comment]
Well no, the AI gets no vision because shuttles have no cameras. Possibly because they move and that makes the cameras unhappy. Obviously when we move shuttles to not be magically powered and lit we can also put in some cameras, because why not

**Comment by Anonmare** [comment]
This has been an issue for a long while, I think it started happening when we removed AI core sight.

I remember when Cyborgs could put up cameras the white ship could accept camera vision but they stopped working as soon as it moved.

**Comment by Jalleo** [comment]
It is a issue with the shuttle moving it was known before and after the rework from Carn
