### ISSUE TITLE
AI unable to use binary chat

### ISSUE THREAD

**Issue by kpeculier** [tgstation/tgstation#18270]
AI's can't use binary chat. Cyborgs still can.

**Comment by phil235** [comment]
I think this was fixed by #18269 which got merged an hour ago, we'll see after the next server update.

**Comment by coiax** [comment]
wasn't present in latest round played

**Comment by Cebasiz** [comment]
AI senpai called me useless because i didn't hear anything they said after i was turned on.

kind of a pain when you're rogue and need to coordinate something.

**Comment by coiax** [comment]
maybe there's some weird runtime occuring in the initial parts of silicon communication?

**Comment by Cebasiz** [comment]
IT'S STILL HAPPENING REEE

**Comment by coiax** [comment]
Fixed by #18281, pretty sure.

**Comment by lzimann** [comment]
This got fixed already.
