### ISSUE TITLE
Judicial Visor can create 2 flames at the same time

### ISSUE THREAD

**Issue by Lexorion** [tgstation/tgstation#18274]
Alt-clicking it spawns a flame which you can use to smite the nonfaithful,using the flame on the floor triggers a cooldown and prevents you from spawning more flames for a bit. 

Issue: Somehow it's possible to spawn two flames (one in each hand) before you use them. This allows you to stun/damage people twice.
This could be a feature but the text in the guide states "Judicial Visor: Forms a visor that, when worn, will grant the ability to form **a flame** in your hand"

**Comment by ChangelingRain** [comment]
I actually fixed this in #18292
