### ISSUE TITLE
Major Graphic Bugs

### ISSUE THREAD

**Issue by Vakulum** [tgstation/tgstation#18287]
Playing on Basil.
On Sunday 5.06 in the evening european time with the new byond Beta. 

Many sprites seem to be broken somehow. 
All Computer and Firedoor buttons always look unpowered. Tables are invisible and all reinforced glass looks just like a grinder without glass. 
Also all closed lockers look like open empty lockers withou a door.  
![unbenannt](https://cloud.githubusercontent.com/assets/19765811/15808305/e2750a70-2b74-11e6-8e3e-7ac85f8acb2e.jpg)

**Comment by PKPenguin321** [comment]
update byond

**Comment by Vakulum** [comment]
just updatet to the new beta. Is there already a newer version?

**Comment by PKPenguin321** [comment]
i dont know dude go check for yourself

**Comment by Dorsisdwarf** [comment]
check the main BYOND window that comes up when you open the program, and look for a red button marked UPDATE
