### ISSUE TITLE
Medical Robot PAI

### ISSUE THREAD

**Issue by Vakulum** [tgstation/tgstation#18289]
I played  round as PAi inserted into a medical robot. Sadly I did not have a Medhud and could not see who to heal.....
maybe in the tranformation process it should be included. 
(Downloading it as a PAI and then inserting did not work either)

**Comment by LatD** [comment]
issue already exists #17127

**Comment by Vakulum** [comment]
sorry tghen. Just delete this one please

**Comment by PKPenguin321** [comment]
you are able to close it yourself

**Comment by Dorsisdwarf** [comment]
or the issue-demon could identify a weak and abandoned victim
