### ISSUE TITLE
Can Wield Double E-swords as hulk

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#18293]
Fairly simple and straightforward---you can wield a double-bladed energy sword as hulk, to do this, simply equip the energy sword, wield it, then have someone else inject you with hulk.

**Comment by PKPenguin321** [comment]
seems fair considering how difficult it would be to do in the first place

**Comment by Fox-McCloud** [comment]
Not especially difficult. Two traitors working together could easily pull this off---metabuddies are definitely a thing---not to mention corning someone and threatening them to do something or you'll kill them.

Uncommon? Yes, especially difficult? No.

**Comment by Zilenan91** [comment]
Yeah I think this should be fixed since it makes you immune to ranged damage which is literally the only thing that can stop a hulk

**Comment by PKPenguin321** [comment]
How would you even fix this honestly

**Comment by Fox-McCloud** [comment]
check for the hulk mutation in the `attack` proc and make it fail if you have it.

**Comment by PKPenguin321** [comment]
clever

**Comment by RandomMarine** [comment]
I thought hulk prevented reflecting projectiles with dual eswords, but still allowed it to be used as a weapon.

**Comment by PKPenguin321** [comment]
nope
