### ISSUE TITLE
Xenos are immune to tesla shocks.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#18304]
What it says on the tin. While they take massive damage for directly hitting a shocked grille, being hit by the tesla effect that comes off of it from proximity does no damage to them whatsoever. I imagine the tesla ball doesn't affect them either.

**Comment by coiax** [comment]
I have been killed by the tesla as a xeno queen before. So this must be recent.

**Comment by coiax** [comment]
Unless this has to do with my change about species that are electricity immune are immune to the tesla? But that literally affects golems only.

**Comment by Cebasiz** [comment]
they're immune to door shocks too btw, not sure if that should be a thing

**Comment by Cebasiz** [comment]
^ they didn't used to be

**Comment by Iamgoofball** [comment]
yeah someone fucked the electrocute act for them
