### ISSUE TITLE
Toggling Darkness bugs premium ghost sprites

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/tgstation#18301]
1. Be a ghost
2. Find someone who has a premium ghost sprite like the Ian sprite
3. See that they have the Ian sprite and then toggle darkness
4. The sprite is not a default boring one (not even the goon ones)
5. Toggle the button back and forth and watch it change sprites back and forth

Why is this a problem?
Premium ghost sprites are only seen now when people have darkness on, which most ghosts don't.  It is a reduction of their well payed for snowflake.  Priority: Super mega critical

**Comment by MrStonedOne** [comment]
I can fix this easily
