### ISSUE TITLE
Non-crew still count against Hijack Objective.

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#18302]
I just redtexted a round where I subverted AI and made a borg army, and had the chaplain possessed axe, and still failed the objective. All the borgs were emagged. Not sure what caused the issue as I still escaped with no crew on the shuttle, I had a brain in my bag too, that might have counted

**Comment by coiax** [comment]
Well, maybe you can just consider yourself to have won. You know, because you clearly did.

**Comment by Jordie0608** [comment]
Dupe #17745
