### ISSUE TITLE
Changeling fake death bugs out if you readapt after using the regenerate ability but before you get the verb

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#18308]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)
![](http://puu.sh/piPCU/fb1c3859e8.png)
The guy's status_flags still had the FAKEDEATH flag and he never got the revival power.

**Comment by Cruix** [comment]
Are you certain that he readapted before getting the revive verb?

**Comment by ChangelingRain** [comment]
Given that he didn't have it, yes.

**Comment by Cruix** [comment]
I just tested this, and if you respec before you get the verb, you still get the verb after the normal time. If you respec after you have the verb, the verb is removed, and you are stuck fake-dead.
