### ISSUE TITLE
Changeling decapitation plus lava capable of destroying brain

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18314]
1) Cut off changeling's head
2) Throw head into lava
3) Head burns, leaving brain
4) Brain burns
5) Dead changeling, even though they can't normally be killed via decapitation

**Comment by phil235** [comment]
Did you actually reproduce this? The brain inside the decapitated head is a decoy, not the real changeling's brain.

**Comment by TechnoAlchemisto** [comment]
I feel like throwing a changeling into lava should kill them

**Comment by coiax** [comment]
The body became soul departed.

**Comment by xxalpha** [comment]
How is this a bug?

**Comment by Dorsisdwarf** [comment]
Because changelings can live without their head.

**Comment by Jalleo** [comment]
This is a bug because the mind is set to be in the brain object. Solution set it to the changelings heart instead.

**Comment by coiax** [comment]
The brain is actually a mob, sort of, because of reasons, which the mind is moved to when it is separated from the body. Could probably mark this under "brainmob shittery"

**Comment by phil235** [comment]
Can't reproduce. Like I said, the brain inside the head is a decoy, there is no brain mob inside it, lava burning the head and brain does nothing to the ling.

**Comment by xxalpha** [comment]
When you spawn a brain mob doesn't it spawn a brain organ and put the mob in the organ?

**Comment by phil235** [comment]
@xxalpha It does, but here we're spawning a brain organ, not a brain mob.

**Comment by optimumtact** [comment]
Unreproducible
