### ISSUE TITLE
Headslug bursters have black screen

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18316]
When burst from a person after a changeling egg (laid by a headslug) hatches, you have a black window, and cannot see, and have to restart.

1) Lay egg in corpse as headslug
2) Die
3) Hatch, you will have a black screen

**Comment by XDTM** [comment]
It is fixed upon transforming as well, without restarting

**Comment by XDTM** [comment]
This issue was fixed somewhere, although i can't find where. Anyway, in testing there was no screen on either legit changeling last resort or xenobio-potion headcrabbing.
