### ISSUE TITLE
White ship loses ambient shuttle lighting on lavaland

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18311]
It's dark suddenly. Why?

**Comment by KorPhaeron** [comment]
Infected by the grimdark

**Comment by Bawhoppen** [comment]
will be fixed soon when I finish dynamic shuttles

**Comment by Jalleo** [comment]
Bump @Bawhoppen

**Comment by Bawhoppen** [comment]
well the PR to add the materials I wanted for it just got merged so its going to happen soon enough

**Comment by coiax** [comment]
Probably no longer a thing with new dynamic lighting.
