### ISSUE TITLE
Fleshmend doesn't regrow organs

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#18341]
I make the assumption that it is suppose to since if your organs spill out you will constantly die of oxygen loss even when regenerating.

**Comment by coiax** [comment]
Fleshmend specifically only regrows external limbs (if missing), and oxy, brute and fire damage. This isn't a bug where it's supposed to happen and doesn't, it's just a design flaw.

I'd suggest making a new organ and limb regeneration power that grows back the limbs and organs.

**Comment by ShadowDeath6** [comment]
Maybe have anatomic panacea or whatever it's called do it

**Comment by drynwyn** [comment]
I feel like regrowing organs is appropriate to fleshmend rather than anatomic panacea. Lings are pretty weak as is; they don't need to be nerfed by splitting up their most potent ability (unless we also cut the the cost of fleshmend to reflect it's reduced usefulness.)

**Comment by AdamElTablawy** [comment]
>lings

>weak

**Comment by drynwyn** [comment]
They're potent in 1v1 combat but lose in any other scenario.

**Comment by Core0verload** [comment]
Not a bug, and ling stasis regenerates internal organs.

**Comment by kevinz000** [comment]
@lzimann new power called regenerate does this now so it's not an issue
