### ISSUE TITLE
Being pulled into Xeno body should have a pop-up?

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#18344]
Most ghost roles have a pop-up for being called back into the game. Xenomorphs do not and pull any random ghost into existence. This includes admins and can be pretty annoying when your in the middle of an ahelp etc.

Of course I realise I could turn off ghost roles or xeno roles in my preferences, but consistency would be nicer.

**Comment by coiax** [comment]
Yeah, this is on my todo list. The problem is, we either spam a popup every time a xeno larva is about to hatch, or we have some sort of toggle, which probably involves a hud option for the ghost

**Comment by peoplearestrange** [comment]
Why is it closed? Its not been denied or added yet?

Also I was goona say, could it work similar to the pAI setup? With a "never for this round" option?

**Comment by PKPenguin321** [comment]
Feature request purge
