### ISSUE TITLE
Blackscreen when "dying" as a possessed object

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18346]
1) Possess a supermatter shard.
2) Make a huge explosion that destroys the shard.
3) You are now dead, in deadchat with the name "supermatter shard", but you cannot see, even if you teleport or orbit other things. A client reconnect solves this.

Possibly related to #18316 ?

**Comment by Incoming5643** [comment]
it's nullspace

**Comment by PKPenguin321** [comment]
This is not an uncommon issue with possession. Item possession is pretty much a debug function

**Comment by lzimann** [comment]
Possession is kinda weird, probably has no checks if the item still exists.
