### ISSUE TITLE
The wizard teleport location list is backwards

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18347]
I know ti's generated surprisingly early in the server's lifetime, but it's still weird.

**Comment by Man-Shroom-** [comment]
If you're talking about the teleport scroll list, and how Xenobiology and Vault appear near the top, this is actually intended.

It used to be alphabetical but wizards would frequently teleport to Aft Solars and die because it was the first in the list.

So now it's reverse alphabetical.

**Comment by coiax** [comment]
Sounds like those wizards need to GET GUD.

**Comment by PKPenguin321** [comment]
Sounds like this not-bug needs to GET CLOSED
