### ISSUE TITLE
Wrapping Cupboards can create empty packages

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#18343]
Dragging a cupboard behind you, wrapping it, then continuing to drag it will leave the wrapping behind and create an empty wrapping "shell".

Steps to recreate:

- Ctrl+click locker (you MUST be doing this before you wrap)
- Wrap the locker using packagewrap
- Move a few tiles (you will still be dragging the locker as the command hasn't be cancelled)
- Locker will move with you but wrapping will stay in place.

Its also worth noting that if you Crtl+click AFTER the locker is wrapped then you will drag the wrapped locker correctly.
Alt click also doesn't show that the two items are separate as expected, UNTIL you move them apart.

Ive also noticed the "hug" sound being played when grabbing the locker, but I only noticed it briefly. I'll try to recreate and will make a separate report if I can do so.

**Comment by PKPenguin321** [comment]
@phil235 ahhhh
