### ISSUE TITLE
Asteroid Station does not compile due to outdated var edits

### ISSUE THREAD

**Issue by xxalpha** [tgstation/tgstation#18358]
Many floors in Asteroid station map are have edited variables which no longer exist, namely gas variables (nitrogen, oxygen, etc.).

There are also undefined types. All of this can be verified by compiling it and DM will throw many errors.

**Comment by coiax** [comment]
Can anyone open Asteroid station and save it, in DM, without crashing?

**Comment by lordpidey** [comment]
Ass Roid Station was removed, close this?

**Comment by Jordie0608** [comment]
I'm pretty sure I fixed this anyway.
