### ISSUE TITLE
four-way manifolds are broken

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/tgstation#18354]
they don't fill with gas when connected to any type of pump; they are a brick wall to any atmos setup which means that anything past the four-way manifold will not fill no matter what is attached to it.

regular manifolds work fine.

**Comment by Cebasiz** [comment]
or now they work fine what

needs testing though, they weren't working 15 minutes ago at all but worked fine when replaced with 3 way manifolds. bizarre.

**Comment by lzimann** [comment]
Huh, never had a problem with them

**Comment by Cebasiz** [comment]
this was as of this morning; the TEG wasn't working probably because of this issue and about an hour after that i was using four-ways to hook up to piping (N/S) and connectors (E/W) and the gas halted at the first 4way it hit, and would not go any further (either to the connectors or through the other 4 ways and onwards through the pipes) confirmed by admins.

then later it started working again who knows why. could be indicative of a problem with atmos processing generally and not just the manifolds.

**Comment by lordpidey** [comment]
I can confirm this bug also happens sometimes.  I can reproduce it semi-reliably by just connecting 4 tanks to 4 connectors, each connected to the same 4way.

It seems to have SOMETHING to do with the order in which the parts are wrenched in.

**Comment by Jalleo** [comment]
@duncathan @as334 any idea what could be causing this?

**Comment by Cyberboss** [comment]
@duncathan

**Comment by kevinz000** [comment]
@duncathan 
Huh these work fine when I use em? WTF?

**Comment by duncathan** [comment]
I have no idea if or why this happens. I've never been able to reproduce. I'm hoping that my pipenet refactor will take care of existing bugs like these.

**Comment by DaedalusGame** [comment]
This still happens on my localhost server which is reasonably updated, with regular manifolds and 4ways. regular manifolds appear to connect to only the node in the direction they're facing in. 4ways, i think only connect south. have not tested on a live tg server.
