### ISSUE TITLE
Can't have multiple HUDs on at once as a pAI

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#18362]
While the HUD functionality was being reworked to allow for multiple HUDs, it is still not possible for pAIs.

![pai hud](https://cloud.githubusercontent.com/assets/12747768/15876214/59f3a5c8-2d0c-11e6-9cdd-5c43f73e39e1.png)

Once you switch the second HUD, the other one shuts off automatically regardless of its actual setting.

**Comment by GunHog** [comment]
This was intended, as HUDs once conflicted. I really should fix this for all the silicon HUDs, but I will start with pAI.

**Comment by Cebasiz** [comment]
gunhog can you make pAIs good

that would be neat

**Comment by GunHog** [comment]
If there are simple improvements I can make to pAI, let me know! I should add a Diagnostic HUD for one thing, but I do not have any merge tokens to spare.
