### ISSUE TITLE
HUD button overlay bug

### ISSUE THREAD

**Issue by dhostak** [tgstation/tgstation#18365]
-I haven't figured out how to replicate this-
A strange blueish purplish box inside a larger white rectangular box was on my screen.  Couldn't get rid of it for a while, asked in OOC and nobody knew what it was.  Essentially just a strip that I could click things on if they were under it.  Couldn't get rid of it with restarting my computer, but just now was able to get rid of it when I was the warden and had the krav maga gloves.  Could be the gloves or could just be the button overlay thats bugged.
If it matters it was leg sweep's description that happened to remove it/cause it not sure.

**Comment by TechnoAlchemisto** [comment]
a screenshot would probably help

**Comment by dhostak** [comment]
I'll see if I can replicate it and get a screenshot, but it was a box just like the textbox when you hover over a HUD button in the top left.  It was the same color as what the text box would normally be but since there were no words it was small, and the white bit was how big it would be if you hovered over the leg sweep ability
...I'll see if I can get that screenshot

**Comment by dhostak** [comment]
Well I made a private client and played around with it a whole lot and could not replicate it. Iunno

**Comment by dhostak** [comment]
![hud](https://cloud.githubusercontent.com/assets/15916150/16048812/05415872-321b-11e6-9cc1-0406129f07d0.png)
Here it is again, this time the button was to attach to a monkey as a slime.
STILL not sure how to reproduce but its happened to me 3 times now.

**Comment by RemieRichards** [comment]
Looks a lot like how tooltips were when I was first porting those from Wirewraith (and I did it wrong at first obvi), no Idea why it'd break JUST for you though, and this late (like, it's atleast 5-6 MONTHS since I added tooltips)

Do tooltips actually work for you?

**Comment by dhostak** [comment]
yes

**Comment by Kromgar** [comment]
I get these fucking things all the time.

**Comment by ShizCalev** [comment]
I've seen it from time to time.

**Comment by factoryman942** [comment]
Got this once too, but with a much wider white box. iirc reconnecting didn't remove, but killing dream seeker did
