### ISSUE TITLE
Closed closet looks like an O2 canister.

### ISSUE THREAD

**Issue by Yiu113** [tgstation/tgstation#18363]
If a closed closet it right-clicked, it has the icon of an O2 canister, instead of a closet, as expected. Thsi does not occur with open closets.

![screenshot 2](https://cloud.githubusercontent.com/assets/16039993/15879217/1cc15ec8-2cf0-11e6-9291-fc249b614dbb.png)

**Comment by ChangelingRain** [comment]
This is byond being a piece of shit basically.

**Comment by LatD** [comment]
Most likely related to  #17643, we can't do anything to fix it.
