### ISSUE TITLE
Strange lava bug with weapons.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#18373]
I think this is going to be incredibly rare and difficult to reproduce but here's what happened.

There was a lava river going through a crashed prisoner shuttle that I was navigating on a boat, I went over a flaming corpse that was on the lava, and then I was shot six times and put into crit. There was no one alive near by.

My guess is that the m1911 that should have spawned on the corpse was melted by the lava, and when I went over where it was, the bullets were for some reason stored, then activated and all fired at once into my squishy ass.

**Comment by PKPenguin321** [comment]
Feature

**Comment by xxalpha** [comment]
This lava sure has many strange properties.

**Comment by KorPhaeron** [comment]
If you del a casing, it leaves a bullet.

If a mob bumps a bullet, the bullet hits them.

We ran into this issue when someone tried to mass delete all the spent casings in CTF, making all the bullets of the unspent casings left like free floating landmines that ruined the rest of the mmtch.

**Comment by PKPenguin321** [comment]
so basically if the bullet is hit with a qdel, qdel its contents as well?

**Comment by KorPhaeron** [comment]
I think mekhi fixed this
