### ISSUE TITLE
New Gamemode Idea: Inter-stationary battle

### ISSUE THREAD

**Issue by Groxic** [tgstation/tgstation#18381]
Two stations, possibly Nanotrasen and Syndicate respectively, are poised in a battle. Each round starts with the stations' respective crewmembers arriving in locations on the station. The station would be commandeered by around 2 Commanders, Generals, etc. (Heads of Staff) that would determine strategy and tactics for this battle as well as making sure things don't fall apart and directing internal station work. Roles for sub-command crew members could be communal, so there would be all access for everyone, or individualized roles, like on our current stations, which would require more work to set up.
Each station would have its own map or maybe stay together on one large z-level. Warriors from each station can attack the opponent at any time via hardsuits, shuttles, etc, however it is advised(rule-wise) that they abide by the command orders.
The battle(round) would end when either all members of an opposing faction(station) are slaughtered or when the integrity of a station is reduced to a certain, very low percentage.

**Comment by xxalpha** [comment]
I am not sure why you thought this was the place to share this when we have a whole forum available.

https://www.tgstation13.org/phpBB/viewforum.php?f=9

**Comment by Groxic** [comment]
I'm sorry.
