### ISSUE TITLE
Metastation xenobiology kill chamber is broken.

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#18382]
Using the xenobiology kill chamber on metastation does literally nothing, as it isn't cold enough to kill any slimes.

**Comment by xxalpha** [comment]
Have you tried cooling it down?

**Comment by Magikarpet** [comment]
Metastation is the chamber without the freezer, the one with no gasses inside to make it freezing cold. You don't have a freezer to do that, and without breaking into the chamber there is no way to cool it down.

**Comment by xxalpha** [comment]
Since when was it broken?

**Comment by Xhuis** [comment]
Just looked in the mapfile and confirmed this, I'll fix it in my upcoming PR

**Comment by Magikarpet** [comment]
I have no idea, but it used to work without any coolers. Something with atmos changing might've broken it?

**Comment by Xhuis** [comment]
Nah, it seems like the floors were standard bluegrid instead of the killroom floors that Box has. Box's floors in that room started with supercooled nitrogen, but Meta is just normal floors if I'm not mistaken.
