### ISSUE TITLE
Boxstation has things appearing and disappearing randomly

### ISSUE THREAD

**Issue by gameMotif** [tgstation/tgstation#18406]
This is engineering. There's a shutter labeled "Brig Shutter".
![image](https://cloud.githubusercontent.com/assets/19834766/15924032/c5d92b02-2df5-11e6-94e9-ef0f1beaf925.png)
Just sort of randomly happened for no apparent reason, admin told me to hit report issue. I hope this isn't a duplicate issue. Happened in round that is current according to time of posting, so, the one that ended at about 4 AM CST.

**Comment by WJohn** [comment]
I've noticed this happen on dreamstation once, a bunch of catwalks on one of the solars were just gone.

**Comment by Jordie0608** [comment]
Missing catwalks are already reported in #17315, the shutter is likely unrelated to that however.

**Comment by lzimann** [comment]
Most likely caused by a map merge error and no one bothered to fix. I'll fix stuff in box station I guess.

**Comment by MrStonedOne** [comment]
Also, confirm you are using the stable version of 510, and not the beta version

**Comment by swankcookie** [comment]
These were all confirmed to be round start, non-player disappearances?

**Comment by xxalpha** [comment]
The catwalk bug is known and debugged, but nobody has bothered to fix it yet.

I am currently investigating the misplaced blast door.

**Comment by xxalpha** [comment]
Okay, so I have been looking for the box station's map file edit history and...

The blast door has been there since before November 21st, 2014. That's as back as github let me go and it was in there under a different key:

"cpc" = (/obj/structure/cable{d2 = 8; icon_state = "0-8"},/obj/structure/grille,/obj/machinery/door/poddoor/preopen{id = "Secure Gate"; name = "brig shutters"},/obj/structure/window/reinforced/fulltile,/turf/simulated/floor/plating,/area/engine/engineering)

**Comment by MrStonedOne** [comment]
It's suppose yo be there, its not suppose to be closed (while the other
ones are open)

That door is controlled by the button in the ce's office

The name might be off (as well as the layer)

**Comment by xxalpha** [comment]
That's wrong MSO, it is the only blast door in that row of windows and besides being labeled Secure Gate, it also has the id of 'brig shutters' which means it is not controlled by the CE button, as none of the CE buttons have that id.

**Comment by xxalpha** [comment]
A git log showed me the last commit and it belongs to this PR:

https://github.com/tgstation/tgstation/pull/5914

**Comment by gameMotif** [comment]
Confirming I was using the stable version, as recommended by admins at the time. Admins also saw this, as per recommendation that I report it. Also I tried to remove catwalks manually with welders and it breaks the wire when I do, so that's no dice.

**Comment by WJohn** [comment]
This is not limited just to the station z level, either. Ruins can have this happen to them, too. Seems to mainly happen to catwalks.

![](http://i.imgur.com/oNStD5h.png)

**Comment by Jalleo** [comment]
So the brig shutter just needs to be removed via a map edit? This is a easy fix...

**Comment by Cyberboss** [comment]
@lzimann The shutter was removed
