### ISSUE TITLE
AI vox is unlogged

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#18403]
It can be found in href logs probably, but it presents a problem when there are multiple ais.

**Comment by optimumtact** [comment]
What do you mean by logged, what they said?

**Comment by Aloraydrel** [comment]
probably which AI is using vox to tell if one is spamming when they have multiple AI's

**Comment by kevinz000** [comment]
log_game("[key_name(src)] made a vocal announcement with the following message: [message].")

**Comment by ChangelingRain** [comment]
It turns out it is logged, gee
