### ISSUE TITLE
Bots and cyborg can ride on top of Mekhi (or Mekhi and cyborg can ride on top of beekspy)

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#18404]
Server: Sybil

Revision: 2016-06-09

Problem Description: Mekhi and a cyborg can ride on top of Beepsky (or them can ride on top of Mekhi)

What did you expect to happen: You can't ride policebots IRL

What happened instead: I thought it wouldn't happen

Why is this bad/What are the consequences: Mekhi can stun everyone if someone emags beepsky

Steps to reproduce the problem: I just saw it
Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Its op pls nerf

**Comment by Zilenan91** [comment]
How do they get on top of beepsky in the first place? Make sure it's not admins messing around.

**Comment by KorPhaeron** [comment]
Admins
