### ISSUE TITLE
you can move at full speed with 1 or no legs if you get damaged to slowdown health and get healed

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#18415]
or something i don't know

**Comment by phil235** [comment]
https://github.com/tgstation/tgstation/blob/23e8c808f5625a1f6d8fcbe17f539af8af779557/code/modules/mob/living/carbon/human/species.dm#L948

specflags is treated as if it's a bitflag...It's not. It's a list..... We really need to rename it.
