### ISSUE TITLE
hand tele is broken and portals never fade

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#18426]
Could we stop with the huge amount of science bugs and general science awfulness? Playing RD is getting to be more of a hassle then fun right now. 

Hand tele portals never fade, and because they need to fade to recharge the hand tele, you can only use it three times.

**Comment by xxalpha** [comment]
How about you fix some bugs you little shit?

**Comment by TechnoAlchemisto** [comment]
This is probably caused by Nullbear's noteleport PR.

**Comment by Core0verload** [comment]
Simple solution: revert Nullbear's noteleport PR. It was shitty anyway.
