### ISSUE TITLE
You can't heal damage through var viewer anymore

### ISSUE THREAD

**Issue by xxalpha** [tgstation/tgstation#18436]
It doesn't heal the damage.

**Comment by PKPenguin321** [comment]
You input negative damage

**Comment by xxalpha** [comment]
It doesn't do anything.

**Comment by phil235** [comment]
it must be something super recent, healing with inputing a negative damage value in VV works fine on my branch which is less than 3 days old.

**Comment by xxalpha** [comment]
I may or may have not had god mode on.
