### ISSUE TITLE
Chemicals can't be injected into kudzu seeds.

### ISSUE THREAD

**Issue by drynwyn** [tgstation/tgstation#18447]
There's a big chunk of code for kudzu seeds governing their interaction with chemicals. However, you can't inject any chemicals into kudzu seeds, so it doesn't actually do anything.

**Comment by Firecage** [comment]
Unless I am mistaken. While making a solution to fix this, I noticed(and the commented text helped explain it), that you don't directly inject the seeds with this. If I understand this right, first you plant the seeds into the Hydrotray and then inject the hydrotray with those chemicles.

**Comment by KorPhaeron** [comment]
@bobdobbington 

?

**Comment by XDTM** [comment]
Kudzu's chemical code is for when they're planted in a tray. Not a bug.
