### ISSUE TITLE
Jetpack never changes direction

### ISSUE THREAD

**Issue by julian94** [tgstation/tgstation#18448]
It happened with the co2 jetpack from eva. I've had this problem before with the engineer jetpack but it got fixed, before someone stole those jetpacks.

**Comment by julian94** [comment]
It happened with the co2 jetpack from eva. I've had this problem before with the engineer jetpack but it got fixed, before someone stole those jetpacks.

**Comment by phil235** [comment]
Can you be more specific? Do you mean you can't change direction while in space and wearing a jetpack that is turned on and has gas?

**Comment by julian94** [comment]
Yes exactly that.

**Comment by Bawhoppen** [comment]
What type of gas did it have in it? As unintuitive as it sounds, certain types of gas do not work in it, such as plasma.

**Comment by julian94** [comment]
As I said in the op: CO2.

**Comment by Bawhoppen** [comment]
did you fill it to max? maybe somehow some other gas got involved

**Comment by xxalpha** [comment]
That doesn't matter.

**Comment by Bawhoppen** [comment]
I'm talking about gas type and yes that does matter
