### ISSUE TITLE
turrets don't work without a turret control computer

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/tgstation#18443]
i'm not sure if those are even buildable, but at least it's deceptive; once the turrets are unlocked an AI can control it's target discrimination IFF and power state, however the turrets don't fire even if set to shoot at everything and the power is on. which is at least a little weird.

probably should put a note in the turret controls somewhere that says they won't fire without a control, or just make them default to a ready state without one.

**Comment by kevinz000** [comment]
if i recall correctly turrets in AI areas that are there roundstart are the same thing as constructable portaturrets, but they have special targetting that shoots anything that's not a drone or a silicon. Normal turrets work properly but can't be set to this special mode.

**Comment by Cebasiz** [comment]
the round that prompted this report was a rogue AI round where i had a custom objective to hijack the shuttle to create a robot-topia. i bolted off escape and had my engiborg and my accomplice detective construct 4+ turrets there, but while they were set to on and neutralize all non-security non-command personnel they didn't turn on at all, even with the least discriminatory targeting setup.

my guess is that if they aren't linked to a turret control they default to the green setting, either that or their targeting is really fucked up because there were people swarming them with fire extinguishers and they weren't doing anything.
