### ISSUE TITLE
refill mode on air alarms overpressurizes rooms

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/tgstation#18450]
it should only go up to whatever the alarm is set to i think, which is usually 101, however for whatever reason it keeps filling the room, sometimes to dangerous pressures of 170+

**Comment by coiax** [comment]
This isn't a bug, refill sets the target external pressure of vents to x3 air pressure (303kpa).

**Comment by MrStonedOne** [comment]
It;s designed to help refill the room quickly, its not designed to be automatic. Normal mode refills rooms up to normal pressure. Refill forces air out at a much higher rate but doesn't automatically turn it back down, its designed to be a trade off, babysit vs slow.
