### ISSUE TITLE
xenobio slime batteries do not recharge engiborgs' metal/glass synth, only the battery

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/tgstation#18452]
making them moderately useless for long engineering tasks as the RCDs' energy use is very high and the only real way to construct large amounts of walls is to use the metal sheets you have, which don't recharge.

niggling consistency issue i'd guess

**Comment by phil235** [comment]
duplicate

**Comment by phil235** [comment]
woops, wrong issue number....

**Comment by Core0verload** [comment]
Battery replacement never recharges materials. Not a bug.

**Comment by optimumtact** [comment]
Definitely not a bug, materials only recharge in the chargers.
