### ISSUE TITLE
queue_smooth is slow as fuck

### ISSUE THREAD

**Issue by Core0verload** [tgstation/tgstation#18467]
Try breaking any mining wall - you'll see that nearby walls are updated with a noticeable, immersion-breaking delay.

Old smoothing systems had no queue_smooth and smoothed instantly, why current one needs smoothing queue?

**Comment by xxalpha** [comment]
Because smoothing is a visual effect and it shouldn't take priority over important processes.

I will double the frequency of the SS firing just for you luv.
