### ISSUE TITLE
Invincible bugged ash drake.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#18464]
Tonight I was fighting a drake for over 20 minutes, I eventually retreat, put on a medical hud and see that it was reduced in health and yet taking no further damage.After  continued fighting I decided to give up and let it just kill me, except when it came into melee range it stopped attacking all togther. It also wasn't swooping or fire balling either. I was then able to take my domesticated drake aboard the station, where it was still invincible and would not attack.

Some details I do know.
It killed and gibbed a miner earlier into the round.
A clockwork drone tried to convert, but was disrupted before it could finish.
It was swooping and fireballing normally during the fight, but then suddenly stopped.

2545bcd492b2ebee74537808d794e10728a908a8

Ausops was online and can confirm that drake was taking zero damage.

**Comment by KorPhaeron** [comment]
It failed to properly clear the swooping var for some reason, preventing it from attacking or being attacked

**Comment by ChangelingRain** [comment]
Sounds like it runtimed
