### ISSUE TITLE
overdosing on spraytan turns you completely white

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#18479]
![master race](http://puu.sh/ppeL2/eead16e632.png)
it's supposed to make you orange iirc

**Comment by phil235** [comment]
Because the orangeness is a full body overlay in human.dmi, whereas humans now use human_bodyparts.dmi or something, where we assemble each limb icon into a full body.
So to fix this you need to refactor the orange overlay to work with dismemberment.
