### ISSUE TITLE
Being abducted removes your gang HUD

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#18471]
Being abducted by aliens removes your ability to see fellow gangsters if you're a gang member, and I can only assume it also removes your own gang icon, since I was targeted by members of my own gang shortly after.

**Comment by lordpidey** [comment]
Can you figure out if your fellow gangsters saw no hud on you, or if they saw the abductee hud?

**Comment by Sligneris** [comment]
I'm not sure how the code works here, but I think the gang HUD is like an implant, right? Where I'm given a gang icon, and can see other people's gang icons?

Well, being abducted and processed removed that, even though I still had my antag status.

**Comment by lordpidey** [comment]
Here's how antag huds work.

You have -ONE- antag icon.
You have a list of antag huds you belong to.
You have a list of antag huds you can see.

If you see someone who belongs to an antag hud you can see, you can see their ONE icon above their head.

**Comment by Sligneris** [comment]
Alright.

From my experience, I was not able to see any icon on myself or anyone else - being processed by abductors removed my gang hud from the list of the huds I can see, and from the list I belong to.

I was not able to check if I had any antag icon from the technical standpoint - I know I wasn't able to see it, and that others didn't see it either, as they immediately turned hostile.
