### ISSUE TITLE
Autoprocess cloning pod starts cloning people even when unpowered

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18470]
They are then immediately ejected due to power loss and die. Again.

**Comment by LatD** [comment]
This has been happening for some months now. Autoprocess has some weird functions like it doesn't even update the text on the console when it starts to clone or when the clone finishes so you can't see who's getting cloned.

**Comment by coiax** [comment]
Oh I thought it was my fault. Phew.
