### ISSUE TITLE
Dismemberment heals the mob

### ISSUE THREAD

**Issue by Man-Shroom-** [tgstation/tgstation#18474]
When you cut off someone's leg or arm the damage of the leg or arm is removed and thus the mob is healed.

Case in point, the other day I was in maint and a changeling critted me with his armblade. However, while I was in crit my arm was chopped off which healed me enough that I was no longer in crit, which allowed me to stand up and beat the ling to death and strangle him. 

tl;dr I kil pls nerf

**Comment by Incoming5643** [comment]
Could convert brute damage to stamina damage if the limb is removed.

**Comment by ChangelingRain** [comment]
I expected this to be a problem and wow it is what a surprise

**Comment by LatD** [comment]
The missing limb should show as max damage until the wound is fixed with a cautery/welding tool or even through a proper surgery. The whole amputation surgery feels so meaningless when you can just beat the limbs off.

**Comment by KorPhaeron** [comment]
>which allowed me to stand up and beat the ling to death and strangle him.

This sounds cool though

**Comment by Man-Shroom-** [comment]
I mean it was impressive for me to beat up a ling one handed but it was mostly because he assumed that I MYSELF was a ling since I appeared to regenerate, and he didn't attack me out of a sense of ling comradery.

**Comment by PKPenguin321** [comment]
The damage is actually transferred to your chest when a limb is removed, just not *all* of it. 

I like this feature a lot because one time I was bleeding out on an admin away mission from my leg and in a brilliant move I self-amputated it to continue living. The ghosts that were watching loved it.

**Comment by RemieRichards** [comment]
>I like this feature a lot because one time I was bleeding out on an admin away mission from my leg and in a brilliant move I self-amputated it to continue living. The ghosts that were watching loved it.

This stays.

**Comment by MMMiracles** [comment]
I mean if you didn't have the ability to bandage the already-bleeding limb, wouldn't cutting it off entirely just worsen the bleeding, considering you'd have to cut a major artery to completely detach?

I mean that would literally worsen the bleeding to the point of hypovolemic shock pretty quickly.

Then again space is apparently cold and bruisepacks instantly heal all external/internal trauma so why the fuck am I bringing realism into this.

**Comment by Jalleo** [comment]
Best solution make a huge bleeding issue.

**Comment by PKPenguin321** [comment]
best solution is to leave it in because it's fun

**Comment by MMMiracles** [comment]
"oh im bleeding and i can't actually bandage the wound, BETTER JUST CUT THE ENTIRE THING OF AND MAKE AN EVEN BIGGER WOUND TO BLEED OUT OF."

**Comment by ike709** [comment]
Amputation is the best medicine.

**Comment by LatD** [comment]
Amputation should be an option but it should then be done as a surgery and the wound should be closed properly, not just beating the limb with a glass shard

**Comment by PKPenguin321** [comment]
mmmiracles to be fair i did amputate it with an energy sword, you could argue that that would cauterize the wound ¯\\\_(ツ)_/¯
