### ISSUE TITLE
Hand teleporters

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#18490]
Hand teleporters are bugged.
1. Using them puts a portal next to you that you have to walk through or throw people through instead of making a portal on you and teleporting you. Buff/nerf by itself
2. These portals will never disappear, and the hand teleporter, after making 3 portals, will always be on cooldown. These portals will never go away so will be a teleport point forever, and the hand tele will be effectively useless except for steal objective/R&D after that.

**Comment by TechnoAlchemisto** [comment]
dupe of #18426

**Comment by kevinz000** [comment]
honk nvm then
