### ISSUE TITLE
Permanently unconscious after cloning process

### ISSUE THREAD

**Issue by Actionb** [tgstation/tgstation#18491]
rev e6536c61c1dbc198420c543b36df30f7704b4aeb 

Get cloned, stuffed into cryo until healed, never awake from my slumber. Even Reed Glover couldn't figure out what was wrong with me. According to admins there was nothing wrong with my body (no morphine in my blood). 
Maybe of importance: I was a geneticist with some powers. My clone had hulk and the invisibilty power.

**Comment by Jalleo** [comment]
Has this occured again at all?

**Comment by Shadowlight213** [comment]
This was due to hulk. If you had hulk and were knocked out, the paralysis counter would never decrease making you sleep forever.
The bug has since been fixed, this an be closed @optimumtact

**Comment by PKPenguin321** [comment]
I have a report similar to this and it sounds like the same issue, I'll close it
