### ISSUE TITLE
Some shuttle templates are leaking air

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18506]
Leaking: emergency_birdboat, emergency_asteroid

Not leaking: emergency_box, emergency_bar

The ones leaking are those that use /turf/open/floor/plating/airless underneath their windows.

**Comment by Jalleo** [comment]
Does that mean windows on airless tiles dont block air or is this shuttle specific. @duncathan

**Comment by coiax** [comment]
I'm not sure if it's airless plating's fault or not yet, but git bisect tells me this bug was introduced in b3b60b187bbf503f3d9e09e66b843b939f4b455d. @RemieRichards
