### ISSUE TITLE
It is impossible to remove facehuggers from corgis

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#18518]
Cross-reporting https://github.com/ParadiseSS13/Paradise/issues/2802. This also is the case for real facehuggers, which obviously is a much more serious issue.

Also, when a corgi is actually facehugged, the facehugger overlay stays on even when a dead facehugger drops off the corgi

**Comment by karlnp** [comment]
#22200 only fixed attaching to things. Didn't occur to me to look into detaching them.

**Comment by Cyberboss** [comment]
WHY CAN CORGIS EVEN BE HUGGED REEE

**Comment by Fox-McCloud** [comment]
@Cyberboss 

Try looking at the sprite; it's even *worse*.
