### ISSUE TITLE
Resin smoothing gets funky with shuttle rotation.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#18519]
![](http://i.imgur.com/DUD3wyC.png)

I don't really know what to say.

**Comment by ChangelingRain** [comment]
shuttle rotation is butts part two act two

**Comment by coiax** [comment]
Can't we just queue new smoothing with onShuttleRotation

**Comment by ChangelingRain** [comment]
Yes but it turns out that is not the issue, once again.
It's, guess what, the automatic object turning. For an object that has no directions.

**Comment by xxalpha** [comment]
Changing dirs doesn't do anything on sprites that have only one direction.
