### ISSUE TITLE
The new wizard spell effect tiles can blow into space

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18510]
@xxalpha

**Comment by xxalpha** [comment]
Intended, read the PR next time.

**Comment by coiax** [comment]
It's counter intuitive.

**Comment by xxalpha** [comment]
No, it's i ded pls nerf.

**Comment by Zilenan91** [comment]
Aren't every other RnG movement spells not allowed to go into space

**Comment by coiax** [comment]
The tiles literally move like objects in the space wind.

**Comment by PKPenguin321** [comment]
Oh I thought you meant they warped stuff into space

They probably just need to be anchored

**Comment by PKPenguin321** [comment]
oranges no i think this is an actual bug, the report is just shitty. the magic enchanted tiles shouldn't be moving

i mean unless they are supposed to be moving but i honestly don't think that could possibly be intended

**Comment by xxalpha** [comment]
Ah I understand the problem now, next time just say the things moved. :confused:
