### ISSUE TITLE
Jelly People sprites clip over the top of shirts, when sideways

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#18523]
Jellypeople
jelly clips very slightly over the top of shirts by one pixel when sideways on the shoulders:

<details><summary>side views</summary>
<img src="https://user-images.githubusercontent.com/85910816/198699438-554e121e-94f3-4d78-99d9-6c16b1036d6c.png">
<img src="https://user-images.githubusercontent.com/85910816/198699834-6ed0f92f-75eb-4d31-a8ea-bb8731a407b9.png">
</details>
<details><summary>front + back</summary>
<img src="https://user-images.githubusercontent.com/85910816/198699861-318a74d4-b361-4e4d-8662-fdcc1090c87b.png">
<img src="https://user-images.githubusercontent.com/85910816/198699854-b779d12d-f7c6-445e-a0ed-7b918bde5b35.png">
</details>

**Comment by phil235** [comment]
Yeah, that's my bad for the most part. Turns out editing a hundred sprites leads to sloppy work.

**Comment by Incoming5643** [comment]
No worries, I just wanted to document what specifically seemed off.

**Comment by Incoming5643** [comment]
I think we could solve the slime/jelly people transparency issues by making their sprites fully opaque, then just applying an alpha to the whole dismemberment layer at some later point in the process.

It might look slightly worse for jellypeople, but that's not really a big issue.

**Comment by PKPenguin321** [comment]
>Lizards
No problems :ok_hand:

as if

**Comment by Incoming5643** [comment]
Ｎ ｏ  Ｐ ｒ ｏ ｂ ｌ ｅ ｍ ｓ :ok_hand:

**Comment by Bawhoppen** [comment]
:snake:

**Comment by timothymtorres** [comment]
This seems to be related to https://github.com/tgstation/tgstation/issues/20603

Both of these caused from PR https://github.com/tgstation/tgstation/pull/17419

**Comment by timothymtorres** [comment]
@Kapu1178 was this fixed by your Kapulimbs PR by chance?

**Comment by Mooshimi** [comment]
Just ran through this list, only one left over is this where jelly clips very slightly over the top of shirts by one pixel when sideways on the shoulders: 
<details><summary>side views</summary>
<img src="https://user-images.githubusercontent.com/85910816/198699438-554e121e-94f3-4d78-99d9-6c16b1036d6c.png">
<img src="https://user-images.githubusercontent.com/85910816/198699834-6ed0f92f-75eb-4d31-a8ea-bb8731a407b9.png">
</details>
<details><summary>front + back</summary>
<img src="https://user-images.githubusercontent.com/85910816/198699861-318a74d4-b361-4e4d-8662-fdcc1090c87b.png">
<img src="https://user-images.githubusercontent.com/85910816/198699854-b779d12d-f7c6-445e-a0ed-7b918bde5b35.png">
</details>

**Comment by JohnFulpWillard** [comment]
![image](https://user-images.githubusercontent.com/53777086/224141838-5c8fbaf7-1c2a-4546-b07e-4100f8bc76c0.png)
![image](https://user-images.githubusercontent.com/53777086/224141874-ede04871-7892-4136-8dc3-faf14b564d67.png)

I don't see it anymore
