### ISSUE TITLE
Slime People (and the problems with being legion)

### ISSUE THREAD

**Issue by SpessInquisitor** [tgstation/tgstation#18525]
Right, as I am wont to do, I advanced enough in slime research to get green slimes, and then I became a slime person. I ate enough food for long enough that I was able to split off and make two of myself (so that neither of us would be virgins). However, I noticed a pretty weird bug involving switching between the duplicate and the original body. If either dies, you are dead for good. Forever. The other body (or bodies) go catatonic and cannot be transferred to, which you think would be part of the draw of becoming a slime person. Becoming a slime person should be the opportunity for the player to have a small group of themselves, either to spread around workloads or use as disposable bodies for dangerous experiments. Having the player not be able to switch to any available slime bodies they made after one of the dies kinda ruins the fun of being a slime person.

**Comment by Incoming5643** [comment]
This is the intended mechanic, you need to predict when you're about to get attacked and get the heck out of there. If you could just do it whenever being a slimeperson would be stronger than being a lich.

Which people complain about being too powerful in the hands of WIZARDS.

**Comment by PKPenguin321** [comment]
this is like the 40th time this has been reported. not an issue, close this
