### ISSUE TITLE
Lings transforming into plasmamen burn to death before they can transform again after resurrection.

### ISSUE THREAD

**Issue by callanrocks** [tgstation/tgstation#18535]
Pretty simple one, the time before being able to transform after resurrection means that you get set on fire and cannot survive long enough to actually turn into someone else. Lesser Form/headslug is pretty much the only way out of a death loop.

**Comment by coiax** [comment]
I think changeling's internal "genome damage" should be visible to the ling.

**Comment by Razharas** [comment]
Make ling plasmamen be able to set or unset themselves from fire

**Comment by Aloraydrel** [comment]
genome damage is a mistake

**Comment by XDTM** [comment]
Genome damage was removed. Close at will.
