### ISSUE TITLE
pAIs in simple bots don't have robotic font while stating.

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#18536]
While simple bot speech is perfectly robotic while declaring and querying, it doesn't work so well with stating.

![6b17fc72e9f005973618c12076470a1c](https://cloud.githubusercontent.com/assets/12747768/16006893/ab7f4f7a-316f-11e6-99b0-5916b5770f02.png)

Speaking with a dot at the end makes the bots sound like a human.

**Comment by GunHog** [comment]
Easy fix, I can look into this if no one beats me to it.
