### ISSUE TITLE
The pylons on the wizard ship convert the cult floors into cult floors

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18539]
At the start of the round, the wizard ship's tiles have the distinctive red flash as their floors are converted (again?). Might be a type path issue. Also probably because features were added to previously cosmetic objects (forge/magma engine, pylon, archives).

**Comment by ChangelingRain** [comment]
The floors on the wizard ship are likely not actual cult floors, then.

**Comment by Incoming5643** [comment]
It's kinda a cool effect though

**Comment by GunHog** [comment]
I would not consider this a bug, because it looks like the shuttle is repairing itself!

**Comment by Bawhoppen** [comment]
I always took this as a feature because it looks sweet as hell

**Comment by lzimann** [comment]
it looks pretty cool, unless it's causing lag/another issue, we should keep it tbh
