### ISSUE TITLE
brain transplants are bugged

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#18533]
1. Humanize monkey
2. Transplant brain with ckey into humanized monkey
3. Try to clone
4. Realize that the brain with ckey's ckey has been moved to the brain you took OUT of the humanized monkey
5. bugged forever unless admins help you

**Comment by Core0verload** [comment]
Can't confirm. Did you just misplaced the brains?

**Comment by phil235** [comment]
>Realize that the brain with <b>ckey's ckey</b> has been

wat
