### ISSUE TITLE
Weird behavior with lings and swapping into things.

### ISSUE THREAD

**Issue by callanrocks** [tgstation/tgstation#18538]
Was memeing around as a ling and we discovered some weird shit.
- Swapping into a headless/debrained corpse will break resurrecting, it will say you have been resurrected but you will still be dead. Your body goes catatonic.
- Swapping into a corpse with someone else in it will not put them into your living body, but you can resurrect. They will stay catatonic when you swap back to your body. If their blood was put into a cloning pod before you swap in they can be pod cloned from the looks of it too.

**Comment by XDTM** [comment]
Swapping was removed. Close at will.
