### ISSUE TITLE
Torso renders invisibly under some circumstances.

### ISSUE THREAD

**Issue by lordpidey** [tgstation/tgstation#18559]
I noticed a corpse with transparent torso/head.  The legs/arms were still visible.  Other players could also see the transparency.

![image](https://cloud.githubusercontent.com/assets/8701326/16031932/23fc4872-31cf-11e6-8d83-efec85ab0309.png)

I adminhelped, if anything seemed out of the ordinary, and they didn't see anything unusual, but they did let me know the following:
icon_render_key = "plasmaman-coloured-fff-male-chest-robotic-head-robotic-l_arm-robotic-r_arm-robotic-r_leg-robotic-l_leg-robotic-husk" 

*---------*
This is Unknown!
He has   an oxygen tank on his back.
He has   a breath mask on his face.
He has   an engineering radio headset on his ears.
He is limp and unresponsive; there are no signs of life...
He has severe burns!
*---------*

This occured on Sybil, at about 1:25am EST 6/14/16
Server revision compiled on: 2016-06-14
3a005b3ca70d843fbffc0d4658b658812ed9f761

**Comment by phil235** [comment]
both chest and head...

**Comment by phil235** [comment]
Robotic augmentation of chest and head seem to have some icon issue.
