### ISSUE TITLE
Set Round End Sound Broke

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#18552]
Due to changes to the byond proc `fcopy_rsc()` set round end sound no longer properly loads sounds to other clients.

I know there's some nonsense about a sound stream now or something. I'll probably eventually get to this if no one else does.

Might have been why #17869 didn't work right

**Comment by MrStonedOne** [comment]
the proper way to do these sounds would be set it's paused state to 1, send it to the clients in world/Reboot before the sleep, then update it to set pause to 0 and send that to the clients. This way they have the sound file loaded and ready by the time round end happens
