### ISSUE TITLE
wrong color for acid

### ISSUE THREAD

**Issue by kilkun** [tgstation/tgstation#18554]
[Note]: # sulfuric acid is green and not orange

**Comment by coiax** [comment]
Sulfuric acid (alternative spelling sulphuric acid) is a highly corrosive strong mineral acid with the molecular formula H2SO4 and molecular weight 98.079 g/mol. It is a pungent-ethereal, colorless to slightly yellow viscous liquid that is soluble in water at all concentrations.[6] Sometimes, it is dyed dark brown during production to alert people to its hazards.[7] The historical name of this acid is oil of vitriol.[8]

**Comment by bgobandit** [comment]
close this meme issue, not a bug

**Comment by coiax** [comment]
Also, I think acid /is/ green now.

**Comment by kilkun** [comment]
not a meme, yes its a bug

**Comment by XDTM** [comment]
not a bug
