### ISSUE TITLE
Skeleton corpses in lavaland ruins are bugged.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#18560]
![](http://i.imgur.com/wpl6Dp5.png)

These rainbow colored corpses USED to be skeletons. Now they're rainbow colored corpses.

**Comment by coiax** [comment]
WJohn, I think that might be due to admin memes changing all human species to slimepeople.

**Comment by Dorsisdwarf** [comment]
Tagged admin

**Comment by WJohn** [comment]
Seems that may have been the case. I haven't seen it happen since. Will reopen if I see it happen and it's not admins who did it.
