### ISSUE TITLE
Airtank suicide models don't update

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#18561]
instead you are just bald

![ss 2016-06-14 at 06 49 49](https://cloud.githubusercontent.com/assets/13092039/16040254/849ffec6-31fc-11e6-99ee-12b39a72eec6.png)

**Comment by Aloraydrel** [comment]
Same goes for adding brute damage via var editing

**Comment by phil235** [comment]
The bug is actually about the damage overlay never appearing in any case at all. will fix since it's technically my fault.
