### ISSUE TITLE
[metastation] AI APC runs out of power in a few minutes

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/tgstation#18574]
must have somehow come unhooked from the SMES; the equipment power fails in five minutes or so and the whole APCs drains shortly after.

**Comment by Actionb** [comment]
Afaik: the problem is the Core SMES, it starts out set to 'charge' and thus will try to recharge itself (same power circuit) - leaving very little power (if any at all) for the APC.

**Comment by Metacide** [comment]
Not sure when this changed but will try to fix it soon - in the meantime yeah, turn off SMES charging input and it's fine.

**Comment by Cebasiz** [comment]
also @metacide there's something wrong with the xenobio APC too. i'm not sure if it's the same problem but it depowers very early.
