### ISSUE TITLE
Debraining/Beheading bugs podcloning.

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#18571]
So recently in a round we tried to pod clone CJ AJ(a player), and it appears that once either the head is removed, or the brain is removed from the head, you are unable to pod clone said person anymore. The seed packet instead rejects the blood.

It also appears that beheading/debraining the corpse after injecting the blood into the packet also won't cause the person to get pod cloned.

Step 1. Get a cloneable body.
Step 2. Cut off said bodies head(or possibly also cut out the brain from the head)
Step 3. Try to inject the blood into the seed packet.

I am pretty sure this has to do with beheading though, and not debraining. Since I have never before experienced debraining breaking podcloning, and limbs being removable is new.

**Comment by phil235** [comment]
Relevant code: https://github.com/tgstation/tgstation/blob/99620ffe76ba40289efbe91837e6d5bbe264319d/code/modules/hydroponics/grown/replicapod.dm#L30

**Comment by vuonojenmustaturska** [comment]
@DaxDupont says this has been fixed a long while ago
