### ISSUE TITLE
Medbots allegedly injecting players in lockers

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#18572]
Allegedly, a player was injected by a hacked medbot while in a locker and died.

info to come maybe

Player was in a locker, medbot ran up to him in the locker and injected him through the locker with poison

**Comment by PKPenguin321** [comment]
i think i've seen this happen with a non-hacked medibot and a player inside a sleeper

**Comment by GunHog** [comment]
This could plausibly happen if A: The bot detected the player and came after him before hiding in the locker, or B: The bot is directly adjacent to the player when searching for a target.

**Comment by PKPenguin321** [comment]
i was reliably able to reproduce this on a test server by spawning a medibot, stabbing myself a couple times, and jumping into a locker. can confirm this happens

**Comment by KorPhaeron** [comment]
Has happened to me

**Comment by phil235** [comment]
It happens because the Adjacent() proc currently considers an object to be adjacent to a mob even if the mob is inside a container (as long as the object is next to the container itself of course). I've mentionned this already in another issue.

**Comment by kevinz000** [comment]
It's injecting people past windoors too.

**Comment by Shadowlight213** [comment]
Windoor thing happened today. Medbot didn't have access to the windoor but still was able to inject someone on the other side.

**Comment by jughu** [comment]
Fun fact if the  medibot is in a crate/locker it can innect you too

**Comment by MoreRobustThanYou** [comment]
Fixed by #31648
