### ISSUE TITLE
Wet floors still broken

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#18577]
The wetness dissipates way too fast, 
originally caused by @nullbear

**Comment by optimumtact** [comment]
This isn't a bug, it's intended by the balance change

If you don't like it you need to modify the settings and make a pr

**Comment by Bawhoppen** [comment]
yes but the change itself was reverted an this part was erroneously left in

**Comment by optimumtact** [comment]
no as far as I am aware the change was not reverted.

**Comment by Bawhoppen** [comment]
you reverted it yourself manually, I remember seeing it in the coderbus, (because it was broken)

**Comment by optimumtact** [comment]
no, i fixed a bug with it, I certainly don't recall reverting wet floors
