### ISSUE TITLE
Silver ID crad multiplying

### ISSUE THREAD

**Issue by Vakulum** [tgstation/tgstation#18591]
When a silver ID card is inserted into an id console (tried at the one at arrivals) it stays in the hand but there is also a second one apperaing in the console. 
After changes the one can be removed and you have suddenly 2...

**Comment by F-OS** [comment]
cannot reproduce.

**Comment by Vakulum** [comment]
on basil

**Comment by F-OS** [comment]
i tried it on a standard test server on my computer, the id card did not multiply.

**Comment by phil235** [comment]
The card isn't multiplied, it's simply "inserted" in the machine without removing it from your hand.
We need more info to reproduce the bug though.

**Comment by Vakulum** [comment]
I played on Basil. 
I got the HoPs Box of spares silver Ids. I had a normal Id with all access on it. 
Went to the computer at arrivals and inserted the silver ID and then my id to make more all access ids. 
When I removed the new made silver ID from the console there was one lying on the console not changed and under it the changed one with all access. (never put in any name, just set to captain) .
Tried 2 times and in both cases had 1 captain id and a second one unchanged.

**Comment by Mervill** [comment]
Cannot Reproduce

Local Server (Boxstation)
- Be the Captain
- Grab the box of silver ids from the cap's locker
- Proceed to the HoP id console, insert silver id followed by captains id (note: not the spare!)
- Give the silver card all access
- Eject the silver card
- No duplicate card appears
- Newly minted card works fine

Also tried with the console in the Boxstation security checkpoint
Also tried with the CE's department console

**Comment by Mervill** [comment]
@optimumtact @AnturK closeable
