### ISSUE TITLE
Peacekeeper cyborgs Ratvar conversion yellow eye shows through headlamp

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18599]
Ratvar Cyborgs are supposed to be able to hide their yellow eye by turning up their headlamp to lvl 2 or higher, this doesn't work for PK cyborgs.

**Comment by RemieRichards** [comment]
Didn't know about that ~completely stupid "feature"~ so obviously I didn't implement it for the sprites.

**Comment by coiax** [comment]
It's akin to thralls wearing masks to cover up their THRALL TIGHTNESS
