### ISSUE TITLE
Beheading someone wearing explorer's hood drop his explorer's hood...

### ISSUE THREAD

**Issue by alphaaBeta** [tgstation/tgstation#18601]
...and it's undroppable when picked up.

**Comment by Dorsisdwarf** [comment]
Clariftying:

Dismemberment causes nodrop items to drop.

**Comment by alphaaBeta** [comment]
It doesn't happen with other nodrop items

**Comment by alphaaBeta** [comment]
At least not with other hardsuits

**Comment by coiax** [comment]
That's likely because those items qdel themselves on drop.

**Comment by coiax** [comment]
Actually, I'm wrong, looks like hoods are coded WEIRD

**Comment by phil235** [comment]
Relevant code: https://github.com/tgstation/tgstation/blob/50807d454b0bdc8e7f699b88280c8dbdc6878e39/code/modules/surgery/bodyparts/dismemberment.dm#L206
