### ISSUE TITLE
That's a proto-kinetic accelerator.

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#18610]
![too long](http://puu.sh/pufw6/7dd6b616e7.png)

**Comment by PKPenguin321** [comment]
![reeee](http://puu.sh/pugcZ/a7fc0a131b.png)

**Comment by Jordie0608** [comment]
#lorebus

**Comment by Davdichan** [comment]
Proposed new examine text:

"Do not point boomy end at face"

**Comment by Aloraydrel** [comment]
this is canon

**Comment by Cheridan** [comment]
Its a feature

**Comment by Davdichan** [comment]
Kinetic accelerator should now come with user manual, certficicate of authenticity and autobiography of inventor
