### ISSUE TITLE
Hand teleporters not teleporting you instantly

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#18617]
Wasn't it made intentionally that hand teleporters drop the portal ONTOP of you so it instantly teleported you so you can't use it to toss corpses through or whatever?
Well that's not working
Thanks noteleport.

**Comment by TechnoAlchemisto** [comment]
i ded please fix

**Comment by phil235** [comment]
Caused by https://github.com/tgstation/tgstation/pull/18534 , see my comment there.

**Comment by Bawhoppen** [comment]
hand teles were supposed to make a portal next to you, and you instantly go through

**Comment by Core0verload** [comment]
Intentional change. Instant teleport made hand tele useless for everything but powergaming. Now it's at least is useful for transportation.

**Comment by Bawhoppen** [comment]
no, they're supposed to teleport instantly so you can get out of positions where you're stuck (like in a wall surrounded by other walls), plus them being instant makes you able to abuse them less easily

**Comment by Core0verload** [comment]
If you are stuck in walls, you can just click a portal with empty hand or any other item.

**Comment by kevinz000** [comment]
Coreoverload you realize yuo can tell someone to liedown /stun them /push the mover to teleport if it's instant and it's spawning right ontop of you right? Because it teleports every mob in its tile so if you're on the same tile as someone before that noteleport crap it works as transportation.

**Comment by PKPenguin321** [comment]
Pbbt

**Comment by TechnoAlchemisto** [comment]
it not instantly teleporting you is a actually a good thing now that i've been dealing with it for awhile

**Comment by nullbear** [comment]
@kevinz000 thoughts on adjusting portal-checking stuff to 'prefer' non-wall turfs, but have a chance to ignore the preference, and remove a limb if you end up in a wall? (would be like 1% of the time, and only likely to happen if you're in an area with lots of walls + using the 'unsafe' teleportation method)
