### ISSUE TITLE
People can take comical amounts of tox damage from plasma gas for some reason

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#18650]
Saw someone step into plasma gas for about two seconds and they ended up taking 167 tox damage.

**Comment by MrStonedOne** [comment]
atmos processing doesn't handle applying to people, thats mob life().

so for some reason mob life() ran too quickly.

I'll have to see it in action to know whats going on.

**Comment by Repukan** [comment]
@ChangelingRain Isn't this fixed with Fox's rework from plasma reagent to toxin when inhaling toxin now?

**Comment by ChangelingRain** [comment]
I don't know if it is or not.

**Comment by PraiseRatvar** [comment]
@Fox-McCloud

**Comment by Fox-McCloud** [comment]
Yeah, this should be extremely consistent now, this shouldn't be an issue anymore.
