### ISSUE TITLE
lavaland ruins overlapping

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#18663]
![ss 2016-06-17 at 04 42 52](https://cloud.githubusercontent.com/assets/6510293/16146874/f761bd8c-3445-11e6-9f09-41751314aafb.png)

**Comment by coiax** [comment]
This shouldn't happen if the away mission areas are set up correctly. I will check.

**Comment by coiax** [comment]
It's the cult ruin not using areas correctly, I will fix.

**Comment by Bawhoppen** [comment]
coiax you got tons of mergetokens already spread the wealth

**Comment by coiax** [comment]
Apparently I don't because oranges is tagging my PRs with "Feature without Fix", so apparently I don't have enough. Faced with the choice between meaningless accounting and more fixes, I'll just submit more fixes until he gives in.

**Comment by Jordie0608** [comment]
That tag just means you haven't linked a fix in your PR description
