### ISSUE TITLE
Various snpc bugs

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#18678]
All of these occurred last night.
Snpcs were staying in crit and not dying from oxy loss or other damage. (There was one that got grenade spammed by another snpc and fell into crit, stayed in crit for at least 15 minutes, then got attacked by a emagged cleanbot, then finally I var edited 200 brute to them and they still were in crit) however a different snpc got lasered and died correctly.

Traitor Psycho snpcs can spam grenades while in crit (they just drop the primed grenade)

Traitor brute (assasinate) snpcs can target lavaland simple mobs (one had their target be a goldgrub)

Snpcs can have their body sprites go invisible.

**Comment by kilkun** [comment]
>Traitor brute (assasinate) snpcs can target lavaland simple mobs (one had their target be a goldgrub)

Objective 1: Assassinate Bubblegum, the creature

**Comment by Shadowlight213** [comment]
@kilkun they don't get objectives in the traditional sense. The traitor objective is basically just a var that points to the target mob that tells them to go kill that guy.

**Comment by kilkun** [comment]
I figured, I was just being cute.
