### ISSUE TITLE
Air tank suicide does not leave a highly brute damage corpse

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18671]
Instead the corpse is just dead, and not all red and blooded meat like we are used to from air tank suicides.

Something to do with brute overlays perhaps?

**Comment by bgobandit** [comment]
I cannot reproduce this

**Comment by JJRcop** [comment]
fresh build, HEAD at https://github.com/tgstation/tgstation/commit/966af6e967be9e4dd49d9080ff6fee5984f7b19e, unable to reproduce

**Comment by PKPenguin321** [comment]
This was part of damage overlays being broken by I think maybe dismemberment? Either way it was fixed ages ago

**Comment by Cheridan** [comment]
k, pk says it was fixed
