### ISSUE TITLE
You can hit yourself with items you've thrown if moving in the same direction as them

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#18670]
Send help I cucked myself and it wasn't fun

**Comment by anconfuzedrock** [comment]
i feel you man

**Comment by Actionb** [comment]
Pretty sure I have seen somebody run into their own shotgun pellets. 
Let's just forget about somebody outrunning laser beams for a minute, maybe Einstein was wrong after all.

**Comment by xxalpha** [comment]
Hitscan throw when

**Comment by timkoster1** [comment]
Were you running at extreme speeds? ( meth, stimulants etc)

**Comment by ChangelingRain** [comment]
Nope, just standard speed. It might have actually been slower, I was wearing the shielded cult armor.

**Comment by PKPenguin321** [comment]
Probably lag

**Comment by timkoster1** [comment]
It's possible to make it hitscan, does this happen alot?

**Comment by MrStonedOne** [comment]
throwing uses check_tick, this isn't perfect but it works.

One of my todo lists is to make throwing use its own subsystem

**Comment by bgobandit** [comment]
feature

**Comment by Qbopper** [comment]
@KorPhaeron should this be closed?

**Comment by KorPhaeron** [comment]
It still happens as far as I know

**Comment by MrStonedOne** [comment]
it might still happen, i mitigated it somewhat. this can't be effectively fixed because movement happens outside of the bounds of "ticks" while throwing has to happen within a tick

**Comment by Qbopper** [comment]
I think the only way this couldn't happen is if throws instantly connected or something and that's dumb so this may never be fixed

**Comment by PKPenguin321** [comment]
This definitely still happens

**Comment by ChangelingRain** [comment]
Why not just track the thrower and not hit the thrower? Is there, like, a really good reason not to do that?

**Comment by MrStonedOne** [comment]
seems hacky

**Comment by KorPhaeron** [comment]
It is what we do for projectiles, and the thrower is already tracked

**Comment by Qbopper** [comment]
like MSO said, probably too hacky for most people's tastes
