### ISSUE TITLE
Reanimated Skeletons in Lavaland are fucking invisible

### ISSUE THREAD

**Issue by Imagebard** [tgstation/tgstation#18683]
![000](https://cloud.githubusercontent.com/assets/7571238/16161781/ccd8ff66-34a5-11e6-83d4-de9004aac250.png)

HATE HATE HATE

**Comment by KorPhaeron** [comment]
How

**Comment by Imagebard** [comment]
I'm pretty sure about everything broke
The floors on some areas are using the default "no sprite" icon.

![0000](https://cloud.githubusercontent.com/assets/7571238/16162620/e928e7d0-34aa-11e6-8db6-cabfe08d4195.png)

**Comment by MMMiracles** [comment]
bone magic

**Comment by phil235** [comment]
Just change their icon file to the one used by every other animal, probably animal.dmi or something. And add a skeleton sprite in there.

**Comment by Kromgar** [comment]
If you rip up any floor tile and then place it down you get the honk floors
