### ISSUE TITLE
Testmerged PRs are only visible when using the Show-Server-Revision verb...

### ISSUE THREAD

**Issue by TheRealGLH** [tgstation/tgstation#18684]
... which is really counter-intuitive, because it either requires you to follow changes happening on Git/ the forums, or for you to use the verb every time you joined. It would probably make more sense to automatically show it in the lobby joining.

**Comment by Jordie0608** [comment]
I don't think #22581 really fixed this, it doesn't help a player to know about test merges unless they try to report a bug with the PR they don't know about.

**Comment by JJRcop** [comment]
should be added to MOTD
