### ISSUE TITLE
Winter wonderland at some point got bugged

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18717]
![image](https://cloud.githubusercontent.com/assets/609465/16172452/bc2f689e-3581-11e6-9da5-d88c22f5b531.png)

**Comment by coiax** [comment]
@xxalpha

**Comment by xxalpha** [comment]
wasn't me

**Comment by Cheridan** [comment]
oh god thats creepy

**Comment by coiax** [comment]
It's the most maaaaagical time of the yearrr
