### ISSUE TITLE
Slime core reactions that create reagents do so in proportion to amount injected

### ISSUE THREAD

**Issue by XDTM** [tgstation/tgstation#18725]
The black slime reaction, for example, should give one unit of mutation toxin, but if you inject 5 u of plasma, it results in 5u of mutation toxin, and THEN the slime core becomes used. Possibly intended behaviour, though.

**Comment by Incoming5643** [comment]
Always thought it was intended, but not sure. You'd have to ask @KorPhaeron

**Comment by KorPhaeron** [comment]
I honestly don't remember

**Comment by Zilenan91** [comment]
Does it matter if it was?

**Comment by optimumtact** [comment]
Declaring this an ascended feature for now

**Comment by Jordie0608** [comment]
This is not intended.
