### ISSUE TITLE
The "legion has been summoned!" icon breaks the screen

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#18733]
Because the icon used for this alert is the gateway, and because the gateway is longer than the edge of the normally 15x15 screen, it actually adds black tile lanes on the right side to fit it, temporarily making the screen 17x15

**Comment by KorPhaeron** [comment]
@Xhuis

**Comment by Xhuis** [comment]
If there's an icon, I don't remember making it, only adding a ghost alert. If I did screw it up, I'm sorry.
