### ISSUE TITLE
Bowman headsets are disappearing when you drop them

### ISSUE THREAD

**Issue by lzimann** [tgstation/tgstation#18748]
This is only happening with bowman.
- Pick up a bowman headset
- Drop it
- It disappears
edit: it also happens when you unequip them

**Comment by ChangelingRain** [comment]
@coiax

**Comment by dhostak** [comment]
EVERYTHING BROKE FUCK

**Comment by coiax** [comment]
WHY IS THIS MY FAULT

**Comment by ChangelingRain** [comment]
It's your fault because DROPDEL has the same flag number as EARBANGPROTECT
