### ISSUE TITLE
Dreamstation HoP locker has wrong access level.

### ISSUE THREAD

**Issue by TechnoAlchemisto** [tgstation/tgstation#18753]
The required access is 3 (armory)

Needs to be 57.

Easy fix come get your merge tokens

**Comment by dhostak** [comment]
![fffffffffffffffff](https://cloud.githubusercontent.com/assets/15916150/16186489/6b16b2ea-3690-11e6-84b2-b1191782b9f6.png)
map value looks fine
unless i'm doin it wrong

**Comment by TechnoAlchemisto** [comment]
Bizarre, earlier today I checked it and it was on 3 after a guy adminhelped not being able to open it.

**Comment by ChangelingRain** [comment]
Can't reproduce, I've got no idea why this'd happen.
