### ISSUE TITLE
welding tanks don't refuel welders

### ISSUE THREAD

**Issue by dhostak** [tgstation/tgstation#18751]
Yeah I don't even
this recent update broke things

**Comment by dhostak** [comment]
![fsadf](https://cloud.githubusercontent.com/assets/15916150/16183706/af48b03c-367a-11e6-8bf3-03c14f9b784c.png)
You know a lot of weird things are happening with this latest update.

**Comment by dhostak** [comment]
![sfasfdfffff](https://cloud.githubusercontent.com/assets/15916150/16183718/c98e16f8-367a-11e6-8db5-73e97810552a.png)
A lot of weird things are happening this last update

**Comment by phil235** [comment]
https://github.com/tgstation/tgstation/pull/18649/files#diff-85dfa6847a4fdcbf04be9765c75773a8R127

**Comment by PKPenguin321** [comment]
a fix for this by @Xhuis just got speedmerged i believe

**Comment by Xhuis** [comment]
Yeah, you can close this
