### ISSUE TITLE
Detective's Office area is wrong on Box Station

### ISSUE THREAD

**Issue by Aliannera** [tgstation/tgstation#18750]
Using the Ghost -> Teleport -> Detective's Office will sometimes put you in the new office, sometimes in the old office on Box Station.

**Comment by KorPhaeron** [comment]
I think the old office is powered by the new office's APC as well

**Comment by pudl** [comment]
The old detective's office uses an area called "Old Detective's Office", as well as an apc named "Old Detective's Office", so it's not a map issue.

**Comment by xxalpha** [comment]
It has to be, these teleports are area based.
