### ISSUE TITLE
Wormhole event can teleport you onto catwalks in space, but cannot be spawned on catwalks.

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#18756]
This means you can be teleported onto Solars, but cannot leave Solars due to the fact the portals only spawn on the solar panels and are thus impossible to move into.

This is obviously lethal with no escape unless you happen to have access to the airlocks.

**Comment by coiax** [comment]
This isn't a bug per se. Wormholes will only spawn on /open/floor turfs, and the teleport from the portal will put you adjacent to another wormhole. Since catwalks aren't /open/floor, but structures, you'll end up next to the solar panels.

**Comment by coiax** [comment]
https://github.com/tgstation/tgstation/blob/cf8bd9044dfce9c3d45ae946bc8446aa3253247a/code/modules/events/wormholes.dm

**Comment by JJRcop** [comment]
Did you know you can click wormholes to teleport through them?

**Comment by coiax** [comment]
I'd call this not a bug, but a feature

**Comment by XDTM** [comment]
feature i think

**Comment by ShizCalev** [comment]
Intentional

**Comment by JJRcop** [comment]
All portals can be clicked on if you are next to them to assist in using them if they are on a dense turf or object https://github.com/tgstation/tgstation/blob/b6741caf7d9518b8ea2207fe3a5feb8d5d9ba7b0/code/game/objects/effects/portals.dm#L57-L61
