### ISSUE TITLE
ORM puts minerals in a wall

### ISSUE THREAD

**Issue by dhostak** [tgstation/tgstation#18752]
I dunno why they moved it
![fsadf](https://cloud.githubusercontent.com/assets/15916150/16183626/ba3970a4-3679-11e6-9ead-3f8e4bd643d0.png)

**Comment by xxalpha** [comment]
@pudl

**Comment by pudl** [comment]
I didn't know the mineral thing only went down, I'll fix this asap.

**Comment by Jordie0608** [comment]
It doesn't, you can set its `output_dir`
