### ISSUE TITLE
Docking shuttles defeat lord singulo

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#18763]
If a singularity is in the shadow of a docking shuttle, it's deleted.

This is so not canon

**Comment by ChangelingRain** [comment]
Probably happens to nar-sie/ratvar too

**Comment by xxalpha** [comment]
If a shuttle lands in a singularity it should be deleted instead of the singularity.

**Comment by Zilenan91** [comment]
It's always been this way

Shuttle > black hole

**Comment by Incoming5643** [comment]
I'm pretty sure it used to just push it to the back of the shuttle, which would then be summarily destroyed

**Comment by optimumtact** [comment]
I like the idea of a shuttle rending the dark lord in twain

**Comment by Man-Shroom-** [comment]
not canon

**Comment by optimumtact** [comment]
YOU DON'T SAY WHAT ISN'T CANON
