### ISSUE TITLE
Medical holodeck floor is busted

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18783]
![image](https://cloud.githubusercontent.com/assets/609465/16209893/11bc7d32-3731-11e6-8a8f-ea8f3bfaace1.png)

**Comment by pudl** [comment]
It just looks like that in DM, it works fine in game

**Comment by TheRealGLH** [comment]
That's an ingame screenshot, as evidenced by the ghost and locker sprites. I also just tested it by going to Sybil and teleporting there and it's still like that.
