### ISSUE TITLE
Mice that die lose their custom name, if any

### ISSUE THREAD

**Issue by TheRealGLH** [tgstation/tgstation#18786]
Didn't test it with other simple animals.
I was a mouse from the sleeper in the pet hospital ruin, named Stallman Jr. After I died my name reverted to simply 'mouse' and even being resurrected with a Lazarus injector didn't change it back.

**Comment by Bawhoppen** [comment]
thats cause they turn into an item when they die

**Comment by optimumtact** [comment]
Consistency issue but technically intended due to how they turn into a trash item on death

**Comment by PKPenguin321** [comment]
should be easy. on mouse death, set the name of the item it creates to the mob name, unless mob name = initial.mob name, in which case set it to "dead mouse" like usual

**Comment by SnipeDragon** [comment]
Fixed in #18836
