### ISSUE TITLE
Ruins and creatures are spawning too close to mining

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#18791]
![image](https://cloud.githubusercontent.com/assets/6778786/16214199/0121898e-3724-11e6-897e-68c25eff65a5.png)

Had multiple times goliaths and ruins spawn way too close to mining to the point when you land they tear down all the walls when you arrive during the starting ash storm

**Comment by KorPhaeron** [comment]
I think this is a dupe but either way I will fix it Soon(TM)

**Comment by EMT321** [comment]
Old mining had something of an exclusion zone, where monsters only spawned on one (larger) side of the asteroid. It might make sense to replicate that in some minor way, so there's no longer colossi spawning on top of mining.
