### ISSUE TITLE
Flashlight implanted in chest no longer works

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#18799]
Before you could use it as a hands-free light source taking up no slots. Now it's broke.

Though this is probably the first time anyone's tried it in months.

**Comment by xxalpha** [comment]
Now it's fixed*.

**Comment by francinum** [comment]
Close this, it's a fixed bug.

**Comment by xxalpha** [comment]
This isn't a bug @dorsisdwarf
