### ISSUE TITLE
Confirmation window for ambrosia gaia can be spammed.

### ISSUE THREAD

**Issue by Ausops** [tgstation/tgstation#18803]
> spread gaia in tray
> expect popup window to only come up once/expect the confirmation message after saying I'm sure to only display once
> click multiple times on tray
> opens up multiple windows
> makes the confirmation message that you planted the gaia in the tray come up multiple times

**Comment by vuonojenmustaturska** [comment]
I've never seen this window, it was probably removed in 2016
