### ISSUE TITLE
Umbra memory draining disables AIs

### ISSUE THREAD

**Issue by Jazaen** [tgstation/tgstation#18812]
After Umbra drains memories from an AI, it can't access doors in any way or use APCs and some other TgUI things. It can still use some other equipment though (turret control, for example). 
I think this may be tied with how AIs react to stuns, from things like mindswap.

**Comment by kilkun** [comment]
Just another reason to revert Umbras. 

#FREEGRIFFGHOSTS2016

**Comment by swankcookie** [comment]
i say leave this in. It's like the "intelligence" was stolen by the umbra

**Comment by AdamElTablawy** [comment]
>leave in permanently disabling an AI for a cheap ghost

**Comment by Jazaen** [comment]
Permamently disabling AI itself is bad, and it's even worse when, for once, it really is virtually uncounterable. They can do that from a spot where no turret can reach them, and you would need to cover entirety of the AI core with salt (good luck finding spessman to do that, when many of them won't respond when you have a CHANGELING in core, much less a griff ghost that *might* appear). Also, nothing stops Umbras from going there the moment they spawn, making either moving core (rated somewhere between "Nukeops and traitor metagame" and "Bad sport") or spraying salt in advance (again, metagame, plus try to find someone to do it) only ways to protect yourself. If this were wizard, that can teleport and EMP, sure, because those are main antags and made to be hard to detect. Or nukeops dropping bomb outside. But Umbras are a random side-antag that can with no trouble make someones life much, much more irritating (especially since you can't act as a doorknob, and half of station forgets about your existence)

**Comment by swankcookie** [comment]
Yeah, it wasn't a smart suggestion. you're right.

**Comment by optimumtact** [comment]
greifghosts got turned back into revenants.
