### ISSUE TITLE
Using thoughtsteal on a holoparasite will freeze you in place...

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#18822]
...But will do nothing to the holoparasite.  I assume this will also happen if you try to thoughtsteal a guardian, holocarp, or any other similar creature.

**Comment by swankcookie** [comment]
The problem is that "if !user.mind" was supposed to prevent thoughtstealing of non sentient playercreatures. The problem is that Holos do have user.mind, but don't have the capacity to be stunned.

**Comment by swankcookie** [comment]
@Hatfish the stun is just the regular length for thoughtsteal, right? Your not stuck there forever or anything?

**Comment by TheColdTurtle** [comment]
the fuck is thoughtsteal, is that supposed to work like heavens door?

**Comment by swankcookie** [comment]
It's basically a stun + Vitae-steal combo with some fluff attached.

**Comment by Hatfish** [comment]
@swankcookie Not sure if I was stuck forever or not because I died shortly after the bug, but since there was no progress bar to indicate when the thoughtsteal stun would end I'm assuming it was forever.

**Comment by swankcookie** [comment]
@Hatfish ended up not mattering, see my PR ^
