### ISSUE TITLE
Ruins can spawn ontop of the bridge to the necropolis and if the blocks near the bridge are destroyed it creates a hole into space

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#18825]
![image](https://cloud.githubusercontent.com/assets/6778786/16252134/aa943df6-37f9-11e6-8d63-cfd9161761da.png)

Uh and apparently you can destroy the blocks to create a hole into space

**Comment by ChangelingRain** [comment]
Indestructible turfs getting replaced and destroyed causes problems what a shocker

**Comment by Kromgar** [comment]
They didnt get replaced. The dude bombed them and they got destroyed

**Comment by Kromgar** [comment]
Either way ruins shouldnt spawn on top of the bridge

**Comment by xxalpha** [comment]
This is a duplicate of https://github.com/tgstation/tgstation/issues/16246

**Comment by Dorsisdwarf** [comment]
dooplicat i guess
