### ISSUE TITLE
If DreamMaker encounters a multiple of 10 errors, it passes Travis

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18849]
See: https://travis-ci.org/tgstation/tgstation/jobs/139579493

**Comment by Miauw62** [comment]
:mime:

**Comment by RemieRichards** [comment]
@optimumtact you fixed this, supposedly.

**Comment by optimumtact** [comment]
I apparently forgot to update the linux build path :tada:

**Comment by swankcookie** [comment]
fucking gold.
