### ISSUE TITLE
core stabilizer improperly named in the mining vendor.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#18843]
It's listed as a hive lord stabilizer which are no longer around (normally).

 easy fix.

**Comment by Durkel** [comment]
I'm getting mixed messages here.

**Comment by francinum** [comment]
Hivelords are still there
However it's on lavaland.
so yes it's both a bug and not a bug at the same time.

**Comment by swankcookie** [comment]
I'm going to make a child of the core stabilizer specifically for Lavaland

**Comment by swankcookie** [comment]
wait, doesnt it just show up as "stabilizing serum" anyway?

**Comment by Core0verload** [comment]
It's name is "stabilizing serum", desc: "Inject certain types of monster organs with this stabilizer to preserve their healing powers indefinitely." No mention of hivelords whatever.

**Comment by swankcookie** [comment]
Agreed. I'm not sure how Durkel realistically saw this.
Close this.

**Comment by Durkel** [comment]
There ya go, it helps if you actually take a look at it in game instead of glancing at the code and jumping to a conclusion.

**Comment by swankcookie** [comment]
You literally said nothing about the mining vendor. Please be more descriptive in your issue reports.
