### ISSUE TITLE
floor tile bug

### ISSUE THREAD

**Issue by dhostak** [tgstation/tgstation#18846]
seems that roundstart oil piles and any footprints created from them will bug a -metal- floor tile that, when crowbared up and put back will irreversably become some strange HONK tile.
Not sure if this was intended but I think its some error.
Other tiles (i tested it with gold floor tiles) seem to work fine, however.  So it seems the problem is metal floor tiles.

**Comment by xxalpha** [comment]
By metal do you mean the regular gray station floor tiles?

**Comment by dhostak** [comment]
![stupidtiles](https://cloud.githubusercontent.com/assets/15916150/16280118/bbd02668-3883-11e6-8c05-c683a5bc95e9.png)
yeah, both special and the generic 4 grey tile ones, forgot to attach the picture

**Comment by swankcookie** [comment]
@dhostak Just fyi, the honk tile is the error tile on our codebase. it means that the right tile couldnt be realized.

**Comment by swankcookie** [comment]
I'll take a look

**Comment by Kromgar** [comment]
Shits broke its every single tile in the game that does this if you replace the tile with a normal metal tile

**Comment by Kromgar** [comment]
![image](https://cloud.githubusercontent.com/assets/6778786/16313689/5e343cf4-3948-11e6-9960-4fe5cd2bd88c.png)

Hell even the ruins get this shit

**Comment by swankcookie** [comment]
wow @Jordie0608 I think this needs a pri tag

**Comment by xxalpha** [comment]
This is not a map issue, just floor code.
