### ISSUE TITLE
Wrapped lockers are impossible to get out of

### ISSUE THREAD

**Issue by Loneguyfly** [tgstation/tgstation#18854]
If you wrap up a locker in paper wrapping, it's impossible for the person inside to get out.

Even if the message comes up and says you are 'pushing on it,' or whatever.

**Comment by dhostak** [comment]
feature

**Comment by swankcookie** [comment]
Do you mean closets in general, or lockers specifically?

**Comment by Loneguyfly** [comment]
I'm not sure about closets, but I know you can't get out of lockers when you're wrapped up.

**Comment by lzimann** [comment]
this bug is around for quite a while, maybe just a wrong check/action after the timer.

**Comment by phil235** [comment]
https://github.com/tgstation/tgstation/pull/15899/files#diff-16b06991fd66aa46893553142fb5d185R163
https://github.com/tgstation/tgstation/pull/15899/files#diff-713b75ebddc1de70bbebc50b809f6347R56

I think this is both of these.
