### ISSUE TITLE
Medical Hologram made by pen lights not visible.

### ISSUE THREAD

**Issue by BananaSenor** [tgstation/tgstation#18869]
If you click on a mob while you have a pen light in your hands, it used to create a sound and a medical hologram. For a while now, the graphical part is missing, I only hear the sound but do not see the sprite.

That thing was quite useful to get the attention of half-dead people walking away from my healing hands.

**Comment by swankcookie** [comment]
Honestly I think someone got rid of the sprite. I can't locate it anywhere.

**Comment by BananaSenor** [comment]
It should still be around, though. The new "shuttle coming, yo" effect is using the same sprite, I think (https://github.com/tgstation/tgstation/blob/4872623507234a13771afbf85c9cbb7d7d935da2/code/modules/shuttle/ripple.dm)

**Comment by swankcookie** [comment]
yeah, i saw that as well. I'm going to try to spawn it in manually on a testing server,l but i couldn't find it. one downside of byond sprite storage is a really limited search function.

**Comment by swankcookie** [comment]
turns out the issue was that the penlight being activated on someone didnt actually call the effect, just the sound

**Comment by BananaSenor** [comment]
Thanks for the fix!
