### ISSUE TITLE
Mining Hardsuit is not fire immune like Explorer's Suit

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#18870]
I assume this is a bug. If its a design decision then why the fuck does the explorers suit have fire immunity and not a hardsuit designed for mining?

PS: Please make the Mining Hardsuit ashstorm proof

**Comment by jughu** [comment]
Because miner suits never got updated when lavaland arrivered

**Comment by swankcookie** [comment]
Fixing

**Comment by Boredone** [comment]
Minor, but explorer suits are not IMMUNE, they are RESISTANT. As resistant as an emergency Fire Suit.

**Comment by swankcookie** [comment]
yeah they have MAX_TEMP_PROTECT
