### ISSUE TITLE
You can't remove a straightjacket if you're cuffed

### ISSUE THREAD

**Issue by Shapsy** [tgstation/tgstation#18878]
Get straightjacketed and cuffed, try to remove the jacket, wait 5 minutes, it says you remove it but you don't. Even if it's decided that not being able to get out when jacketed and cuffed is intended, the text saying you can get out after 5 minutes and saying you succeed in doing so when you don't should be changed

**Comment by ChangelingRain** [comment]
I don't think you can remove them at all actually.

**Comment by Kromgar** [comment]
You can't remove straight jackets

**Comment by hornygranny** [comment]
not a bug but remove straihgtjackets

**Comment by xxalpha** [comment]
You can free yourself from straightjackets.

**Comment by InsaneHyena** [comment]
You couldn't remove straightjackets for some time, but you can now.

**Comment by Shapsy** [comment]
It got changed to be removable after 5 minutes #14706

**Comment by ChangelingRain** [comment]
You can't remove them even if you wait the full five minutes, no.

**Comment by ExcessiveUseOfCobblestone** [comment]
just tested this, you still cannot remove jackets with or without cuffs.

**Comment by ShizCalev** [comment]
This was fixed.
