### ISSUE TITLE
Bunker1 Camera Network can be seen by the AI

### ISSUE THREAD

**Issue by TheWiznard** [tgstation/tgstation#18873]
current basil revision 6/23/16
I believe this is some kind of random ruin but the AI can see it in the list of camera networks it can jump to. it was called "Bunker1" and I used the 'jump to network' verb

![ss 2016-06-23 at 07 47 05](https://cloud.githubusercontent.com/assets/9158683/16324996/630cf6d0-397f-11e6-906d-15dcdc654db6.jpg)

**Comment by Kromgar** [comment]
That doesn't even look like lavaland the fuck is this?

**Comment by WJohn** [comment]
That's weird. It's not on the "SS13" camera network. Will look into it.
