### ISSUE TITLE
flying over a glass table breaks it and stuns you

### ISSUE THREAD

**Issue by hornygranny** [tgstation/tgstation#18880]

**Comment by drynwyn** [comment]
What do you mean by "flying"? Space Carp/Holoparasite movement? Being thrown over it?

**Comment by hornygranny** [comment]
@drynwyn angel wings

**Comment by Saegrimr** [comment]
Monkeys too, watched a monkey dart down a hallway and over a glass table and stun itself. Probably more intended than actual flying.

**Comment by Shadowlight213** [comment]
This was known in original testing and deemed a feature at the time. Mainly because I found it a hilarious sort of hard counter.

**Comment by Shadowlight213** [comment]
@Dorsisdwarf @RemieRichards this was "fixed"
