### ISSUE TITLE
Restore Ghost Character verb doesn't restore name

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#18886]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by coiax** [comment]
Do you mean that it doesn't actually rename the ghostmob's name?

**Comment by ChangelingRain** [comment]
Yes.

**Comment by coiax** [comment]
That's intentional because some admins didn't want the names of the ghosts or minds changed so they could work out who was who.

Restore ghost character actually sets a "deadchat name" var, as well as altering the ghost cosmetic appearence.

**Comment by ChangelingRain** [comment]
oh so it basically does nothing, then

**Comment by coiax** [comment]
Yep. But it means you can talk in deadchat with your normal name and have normal hair. But cosmetically that's enough for most people

**Comment by PKPenguin321** [comment]
so wait does that mean this isnt a bug

and also doesnt that mean this should be closed

**Comment by Jordie0608** [comment]
Yes and Yes
