### ISSUE TITLE
Floor code needs to be refactored

### ISSUE THREAD

**Issue by xxalpha** [tgstation/tgstation#18888]
The recent refactoring of map files to use different floor types is causing predictable bugs and a new refactoring of floor code is necessary to fix things once and for all.

**Comment by MrStonedOne** [comment]
gonna need more details

what bugs

what recent refactoring

**Comment by xxalpha** [comment]
Floors being different types instead of all being the same type with different icon states.

**Comment by MrStonedOne** [comment]
what bugs does that cause?

**Comment by MrStonedOne** [comment]
(you're gonna have to explain this in a way that a coder who has never touched flooring code understands)

**Comment by Jalleo** [comment]
This will meab we need to make certain things like warning stripe floors and painted floors (mulebot crate loading area in cargo makeable somehow.

**Comment by ninjanomnom** [comment]
This issue is too old and means nothing at this point.

**Comment by xxalpha** [comment]
That...is not true.
