### ISSUE TITLE
Devil Ascension is bugged

### ISSUE THREAD

**Issue by Yoshmaster** [tgstation/tgstation#18893]
[Note]: # I ascended into a greater demon as devil. I was unable to move, and I was slowly suffocating until I was in crit. I whispered and succumbed, and I was unable to return to my body. Before I ascended, I was missing an arm.

**Comment by lordpidey** [comment]
Did you resurrect afterwards?
Were you somehow incapacitated during ascension?

**Comment by Yoshmaster** [comment]
I didn't get the resurrection notification, but a minute or so later I noticed that I was back in my body. I think an admin did that, probably. I wasn't incapacitated, until I ascended.

**Comment by lordpidey** [comment]
Okay, it sounds like somehow your original body got nullspaced AND the mind transfer to the new body failed.  I'll look into it, but I'm not optimistic that I can find it.

**Comment by kriskog** [comment]
Very old issue, rarely used out of rotation mode, limited reproduction possibilities. Closing.
