### ISSUE TITLE
Emergency Medical Bay Holodeck not loading on Metastation.

### ISSUE THREAD

**Issue by Aliannera** [tgstation/tgstation#18892]
Not sure if this also is affecting other stations, but it won't load on Meta. None of the tables and equipment appear and the floor stays the same as whatever prior holodeck was there.

Also when I tried to use Admin AI to change it the server froze for a good few minutes but eventually came back.

**Comment by Jalleo** [comment]
@Metacide

**Comment by Metacide** [comment]
Weird, was working fine quite recently and not sure what could have changed.
