### ISSUE TITLE
Unable to open C4s wire panel / attach anything to it

### ISSUE THREAD

**Issue by Lexorion** [tgstation/tgstation#18898]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

I was unable to open the c4s wire pannel so I could add stuff like remote signaler or voice analyzers to it. I'm not entirely sure if this is a bug or a nerf to the c4+syndibomb core combo (sorry if I missed that).
How to reproduce: Buy c4 and use tools on it,nothing will happen

**Comment by TechnoAlchemisto** [comment]
This was caused by the repathing of c4 to a grenade path, I attempted to readd the old path to the uplinks but it was denied due to it being a work around instead of a fix.

**Comment by lzimann** [comment]
Not a bug, intended. You need to attach an assembly(this part might be a bug though)

**Comment by Dorsisdwarf** [comment]
I think

**Comment by Lexorion** [comment]
Using an assembly (e.g. signaler + signaler) on the c4 worked,it'd still be nicer to be able to open the wire pannel.
