### ISSUE TITLE
AI interface (and entire UI) disappear during the round

### ISSUE THREAD

**Issue by Daundra** [tgstation/tgstation#18906]
I was playing as an AI recently, and I cannot offer nothing more than a "this issue exists" because I don't seem to know what was causing it.

Image related.
![dreamseeker_2016-06-24_23-31-34](https://cloud.githubusercontent.com/assets/5360736/16354518/88119fd6-3a64-11e6-9d3a-4a0743f5a6a5.png)

I apologize I cannot offer more than that, but reconnecting does not appear to fix the issue.

Commands in the AI command tabs and such work just fine, so does radio chat and other things like that. The only problem is my UI is completely inoperable, interface and all, making it near impossible to play for the rest of the round.

**Comment by SnipeDragon** [comment]
What were you doing when this happened?  Was anything abnormal going on before this happened to you?

**Comment by GunHog** [comment]
Did you try the "Cancel Camera View" or "Return To Core" verbs? Did you lose power at any time during the round? Did you try to view any cameras on the list? Chances are, your AI Eye got moved to nullspace or such. These are all guesses, of course.

**Comment by Daundra** [comment]
I attempted to use the cancel camera view verb to fix it, it didn't do anything. Neither did return to core verb. I can't recall what exactly happened when my camera bugged out, but I do know I was messing with several of the commands during the round, if that has any bearing on the cause.

If it matters, no, my power did not go out any time during the round.

**Comment by PKPenguin321** [comment]
is this still a thing

**Comment by ShizCalev** [comment]
Will close in a week without another repo.
