### ISSUE TITLE
Brain damage machine use prevention is frustrating/feels buggy.

### ISSUE THREAD

**Issue by Cheridan** [tgstation/tgstation#18901]
Large amounts of brain damage prevents you from using machinery, with a % of failure based on amount of damage.

However, it's not implemented very well. For example:

- Cloner pods are machinery, so if you're retarded you can't even open/close the pod door. It's just a door? Not exactly complex equipment.
- Try to use a station announcement thing as a head. If you manage to get the window up, you can type a message into the announcement box. If you fail your roll, it'll give you the "You momentarily forget how to use X!" message... and it won't save your message, you'll have to retype the whole thing.

I mean this feature isn't even funny, at least the slurring and stupid phrases are visible to others and they can laugh at your expense.

I'd make a PR myself to take this aspect out but I don't want to get memed at for changing /tg/ culture or whatever.
Could readd some other negative effect for retardation? I don't really know what though.

**Comment by yackemflam** [comment]
If you`re dumb enough to bash your head on a door. You`re dumb enough to stare at shit and drool.

**Comment by coiax** [comment]
We can probably implement a brain damage proc for each machine that has % chances of scrubbing the input and what not. For example, hitting the wrong button with the chemistry dispenser; calling the shuttle instead of making an announcement, erasing clone templates instead of scanning, printing the wrong thing at protolathe/autolathe, wrong settings for PA, SMES, solars; microwave on too long, wrong items ordered at cargo, duplicating a package when you try to remove it from the cart, etc. etc.

**Comment by Metacide** [comment]
It seems that on chemistry dispensers for example there is a roll every tick to see if brain damage prevents you from being able to use the UI. Even with tiny amounts it seems to be about 70% chance you get locked out and all the buttons go grey. Problem is it takes a tick to go grey>blue, during which you can't use any of the UI buttons, and by that time the next tick roll has decided you can't use it after all and the UI buttons fade to grey again.

Anyone who has tried to make mannitol for even small amounts of their own brain damage has probably experienced how poorly implemented this is.

**Comment by Jalleo** [comment]
How about instead as a temp fix it increases the time it takes to complete the action?

**Comment by Razharas** [comment]
I think we need a more complex retardness system
Make people with brain damage have their recieved html corrupted so they see gibberish and broken layouts
Very immersive
