### ISSUE TITLE
Colossi movement ai breaks when facing tables between it and its target

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#18905]

**Comment by Kromgar** [comment]
![image](https://cloud.githubusercontent.com/assets/6778786/16354544/1da6b78e-3a65-11e6-9a6a-344d2cdd2ea4.png)


Also colossi can not break botany pods

**Comment by MMMiracles** [comment]
i mean i would of waited a bit longer before posting this for reasons

**Comment by Kromgar** [comment]
Oh shit ill jsut delete this
