### ISSUE TITLE
Opening a canister with bad gases makes an adminmessage even when it's just filling a tank

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18909]
Opening a canister of plasma or BZ should only make messages when it's opened to the air?

**Comment by lzimann** [comment]
probably my fault, i'll look into it

**Comment by lzimann** [comment]
Uhh this is not happening or at least I could not reproduce it.

**Comment by coiax** [comment]
Hmm maybe I misunderstood. Maybe it was only when plasma cannisters were wrenched into a network, which would count.
