### ISSUE TITLE
Colossi movement ai breaks when facing tables between it and its target

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#18911]
![image](https://cloud.githubusercontent.com/assets/6778786/16354499/1caf16e2-3a64-11e6-9f82-4934325aadc4.png)

Didnt save a snapshot in time but.

Target was there it was a protective holoparasite. It just stood there shooting needles instead of running to it's target. Once the holoparasite moved south and the straight line avoided the tables it followed the holoparasite

![image](https://cloud.githubusercontent.com/assets/6778786/16354544/1da6b78e-3a65-11e6-9a6a-344d2cdd2ea4.png)

Also colossi can not break botany pods or doors. It got stuck here for like... 3 minutes

**Comment by ChangelingRain** [comment]
~simple animal pathing is a byond proc~

**Comment by Kromgar** [comment]
Well shit like this should somehow be fixed otherwise it can be abused to easy kill colossi or shit like that.


Colossi should probably be able to shatter doors though
