### ISSUE TITLE
Bug Report: Holodeck - Emergency Medical isn't working.

### ISSUE THREAD

**Issue by thehellslayer** [tgstation/tgstation#18918]
[Note]: Having issues getting Holo-Deck Emergency Medical to work. The button just doesn't work. AHelped it, and was told to post here.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by Zilenan91** [comment]
It seems like the holodeck breaks every other week.

**Comment by Kromgar** [comment]
>It seems like the holodeck breaks every other week.

What do you think this is Star Trek?
