### ISSUE TITLE
Inhand items do not fall into chasms with you

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#18920]
![image](https://cloud.githubusercontent.com/assets/6778786/16359232/88dc111c-3afa-11e6-996c-0d66d24e36cb.png)

Chasms how do they work?

**Comment by Kromgar** [comment]
This is present on lavaland too

**Comment by kevinz000** [comment]
more like the item is teleported to the ground below you instead of qdelled or dropped
