### ISSUE TITLE
Toolset arm uses wrong surgery

### ISSUE THREAD

**Issue by InsaneHyena** [tgstation/tgstation#18939]
In order to install a toolset arm onto your subject, you need to use organ manipulation surgery instead of much more logical augmentation surgery. Also, if your toolset arm fails to activate, it displays a message

> Your the integrated toolset implant fails to activate!

"The" shouldn't be there. Literally unplayable.

**Comment by Aliannera** [comment]
Augmentation is done for replacing limbs with cyborg part versions, while organ manipulation is used for implants like the toolset. I'm no coder but this was probably the easiest way to do it, even if it's odd having tools appear out of your flesh.

However grammer errors reeeeeeeeee

**Comment by GunHog** [comment]
Probably should use [name] instead of [src]. Organ manipulation surgery is the correct surgery for implants. Augmentation is just for the metal plating.

**Comment by InsaneHyena** [comment]
An obvious solution - make toolset arm an augmentation that also gives you the implant.

**Comment by GunHog** [comment]
There is no need!

**Comment by PKPenguin321** [comment]
yeah no augments are only for making the arm robotic. not a bug

**Comment by optimumtact** [comment]
Not a bug
