### ISSUE TITLE
Cardborg Disguise bug

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#18941]
Upon wearing the full cardborg disguise and then going into a locker, removing parts of the disguise while inside the locker and then opening it will cause you to still be stuck looking like a cyborg, changing clothing or reentering the locker will not remove the disguise.

edit: this only applies to the client, other people see it as normal

**Comment by jughu** [comment]
Once a borg ALWAYS A BORG

**Comment by optimumtact** [comment]
Known issue to do with how the alternate diguises are applied
