### ISSUE TITLE
Newly created shuttles don't move

### ISSUE THREAD

**Issue by Isratosh** [tgstation/tgstation#18955]
Setting the id, width/height, and dwidth/dheight properly will allow the shuttle console to recognize destinations. Upon first attempting a move the distortion effect will appear but only shortly, and the shuttle will not move from its position. The effect appears in the correct spot with the correct shape, but it only appears the first time a move is attempted and after that, nothing will happen. This is only possible/re-creatable with admin permissions and variable editing.

**Comment by coiax** [comment]
Right, so all shuttles currently need a transit docking port, I'm working on making transit space dynamically assigned so this isn't needed anymore.

**Comment by MrStonedOne** [comment]
Just make it so that if it doesn't have a transit docking port, it skips that step.

**Comment by coiax** [comment]
Fixed by dynamic transit space. This can be closed.

**Comment by coiax** [comment]
@optimumtact close this plz
