### ISSUE TITLE
UUURH UGYYS VR 0RIOBPLKKLS MY FOOPD

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#18959]
http://puu.sh/mo8Rp/a4a888a6c9.png

THSIOIS ISI WEORTBNGNN 

FIOXOEI XOIY [D;

**Comment by Iamgoofball** [comment]
DSDUAFHGGQEFTYW FMWNT GISOOOD?

**Comment by optimumtact** [comment]
This isn't a bug

**Comment by Iamgoofball** [comment]
# YYESII YI ISZI
