### ISSUE TITLE
A skeleton can jam a human arm into a socket and regains a skeleton arm

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18968]
1) The skeleton is missing an arm.
2) The skeleton applies a human arm to their socket.
3) The skeleton regains an arm, but it's a skeleton arm.

@Incoming5643

**Comment by Incoming5643** [comment]
works for other races, something special about skeletons. Maybe it's because it's not colored.

Also that @ didn't actually alert me for some reason

**Comment by jughu** [comment]
The skeleton rips the flesh off

**Comment by GeneralGoose** [comment]
you can't corrupt pure skeletons with your filthy flesh
