### ISSUE TITLE
Traitor AI was not given complete "yandere" objectives

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#18966]
https://github.com/tgstation/tgstation/blob/dfc6df579a10c8f17da4a3b56fae34ef3f74c3d8/code/game/gamemodes/traitor/traitor.dm#L109

One possible set of objectives is to protect and strand a target. I saw a round where the AI had to protect the CMO, but where the strand objective was, was "Free Objective" or missing or something. Is this objective set generating correctly?

**Comment by Cebasiz** [comment]
i've never had this objective. in hundreds of rounds of traitor ai i've gotten protect once, and my second objective was "nothing"

**Comment by coiax** [comment]
Yes, that's exactly what I'm talking about.

**Comment by lordpidey** [comment]
Another issue I noticed is on  https://github.com/tgstation/tgstation/blob/master/code/game/gamemodes/objective.dm#L190
Wouldn't this mean if the target is gibbed (and thus qdel-ed), the objective autosucceeds?
