### ISSUE TITLE
tgm meme: there's no readme

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#18978]
How do you convert to tgm?
How do you keep things in tgm?
Why should you keep things in tgm?
What are the benefits of tgm?

All these questions and more, are answered nowhere.

**Comment by RemieRichards** [comment]
1. You don't, Map Merge does it for you (or you can run the exe or py file using command line args)
2. You don't, Map Merge does it for you
3+4. tgm is a better format for git, with tgm git will try to merge the file for longer than two nanoseconds before giving up, to actually cause a conflict on a tgm map the two (or more) PRs have to touch the EXACT SAME LINE in the tgm map, which means touching the exact same variable, where as with the normal dmms just touching the same tile caused issues. it's also a bit more human readable, but that's just a side effect.

None of this is mentioned anywhere as it doesn't need to be, those who want to know about tgm should be more than capable of working it out from the source (the py file) which explains the whole "git friendly format" anyway, and also mappers shouldn't care what goes on under the hud, they shouldn't need to worry about that, just run the appropriate tools and have the work done for them.

**Comment by Incoming5643** [comment]
but mapmerge doesn't have a readme anymore either
