### ISSUE TITLE
laughter demon ex_act

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#18979]
1. Be laughter demon (honk)
2. Eat a ton of people
3. Die to explosion (My case was immovable rod, it would do this for sure)
4. Watch as limbs fly out of you and then after that lag you die
5. Everyone is revived... without their limbs and most likely dead from an immovable rod calling ex_act on them
6. Deadchat erupts in salt, pepper, laughter, and all kinds of crazy

EDIT: 7. Admins realize that LIMBS HAVE ALSO TELEPORTED ALL OVER THE PLACE

**Comment by bobdobbington** [comment]
>obvious feature

**Comment by optimumtact** [comment]
hard to say, I don't think it's a bug that objects pass ex_act onto their contents.

**Comment by coiax** [comment]
This is all kinds of weird. Probably should override ex_act() even more not to call super so it doesn't do the contents of the demon.

In fact, should probably just leave the magical rez part in the demon's Destroy()
