### ISSUE TITLE
portable seed extractor apparently screws with yield vars for plants

### ISSUE THREAD

**Issue by Ausops** [tgstation/tgstation#18990]
>PM: xxxxx: Harvests were normal until I picked up the portable seed extractor.

Somebody complained about all seeds yielding one plant. Upon further testing by that person, they reported seeds only did that when picked up by the portable seed extractor.

**Comment by bobdobbington** [comment]
Are you sure this isn't backwards? The portable seed extractor PRODUCES one seed per plant, while the nonportable one produces 1-5 seeds. That's intended behavior. It should not mess with yield, potency, or production.

**Comment by bgobandit** [comment]
yeah the exact code is: 

while(t_amount < t_max)
				var/obj/item/seeds/t_prod = F.seed.Copy()
				t_prod.loc = seedloc
				t_amount++

where t_max is just the counter sent, which is 1. so 1 seed will be produced, but it should have all the same stats
