### ISSUE TITLE
wastes another get

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#19000]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by Man-Shroom-** [comment]
damn baw you a savage ass nigga

**Comment by Man-Shroom-** [comment]
doing that won't announce it to coderbus or OOC (i think) since this is an issue and not a PR

**Comment by PKPenguin321** [comment]
Bawhoppen you shitter

**Comment by Bawhoppen** [comment]
@Man-Shroom- i know

**Comment by Bawhoppen** [comment]
@PKPenguin321 if you were mad at me for this wasted get, you should be livid about #50000
