### ISSUE TITLE
Poly managed to bust VV with a dodgy phrase

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#19011]
Someone taught poly this phrase:

`Ruel*/*;>gerh**&igned<%u *; St**o */*neer `

And in the VV window it rendered as:

`Ruel*/*;>gerh**&igned`

At which point the window terminated without printing any more vars.

Removing that phrase from the list fixed VV, but still.

**Comment by MrStonedOne** [comment]
Use \` code blocks or \\ to bypass the markup

**Comment by coiax** [comment]
Poly most likely overheard it over tcomms during a processor overload.

**Comment by MrStonedOne** [comment]
@coiax that doesn't matter

Nothing you can put in a variable should be able to break VV

Something isn't escaping html output properly.

**Comment by Menshin** [comment]
> Ruel*/*;>gerh*&igned  ___<___  %u *; St**o */*neer

Opening tag without a corresponding ```>``` ?
