### ISSUE TITLE
Fake Nuke (Honk) buckles the entire crew to invisible beds

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#19031]
Is this intended? FOR WHAT PURPOSE?

**Comment by ChangelingRain** [comment]
All nuke animations do this, because reasons.

**Comment by xxalpha** [comment]
If it unbuckles people after it finishes playing then there is no bug.

**Comment by Zilenan91** [comment]
Is that really how hacky nukes are

**Comment by Cebasiz** [comment]
when's someone going to recode the nuke just literally destroying the station as a 1000/10000/100000 bomb would or something anyway?

**Comment by Alek2ander** [comment]
It doesn't just buckle the crew to invisible beds...
It buckles every crew member to the _same_ invisible bed.

**Comment by Dorsisdwarf** [comment]
Why

WHY

The server can handle 255,255,255 bombs now, why cant we just drop a 100/200/255

**Comment by xxalpha** [comment]
No it can't.

**Comment by Saegrimr** [comment]
Or you know, set weakened state to like 50?

**Comment by Jordie0608** [comment]
That could be affected by reagents mobs have in them, changing the time they're down.

**Comment by ChangelingRain** [comment]
why does it even need to buckle anyway, why can't you just move around

**Comment by xxalpha** [comment]
Because it's supposed to be the end of the round.

**Comment by optimumtact** [comment]
nukes need fixing

**Comment by Robustin** [comment]
This is no longer an issue with the changes to nukes
