### ISSUE TITLE
Chef cant grind slimes for jar of slime jelly anymore

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#19033]
I was a chef and grinded a slime and got a extract instead of a jar of jelly

**Comment by TechnoAlchemisto** [comment]
Only purple slimes generate slime jelly, and that's when their cores are injected with sugar.

**Comment by jughu** [comment]
BUT J-JARS

**Comment by jughu** [comment]
You used to be able to grind them for a jar with slime jelly despite what slime it was

**Comment by bgobandit** [comment]
not a bug, the grinder and the slime processor are exactly the same machine iirc
