### ISSUE TITLE
Puzzle1 Reflectors don't work.

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#19038]
You're unable to complete the puzzle of the ruin Puzzle1 because the laser doesn't obey reflectors, blame pixelprojectiles.

**Comment by Bawhoppen** [comment]
The vote was held whether we should abandon reflectors in favor of pixel projectiles, and clearly it passed. Reflectors aren't even supposed to be used in the game anymore anyways

**Comment by MrStonedOne** [comment]
You can make them work, you just have to not be lazy

**Comment by Bawhoppen** [comment]
I wanted them to work dynamically not just add 90 degrees like you suggested

**Comment by francinum** [comment]
So much for abandoning reflectors.

**Comment by Cyberboss** [comment]
@kevinz000 fixed this I believe
