### ISSUE TITLE
box AI core turrets can't hit anything in front of the AI core.

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#19044]
they told me the new projectiles didn't change their path!

**Comment by InsaneHyena** [comment]
Isn't it intended?

**Comment by YakumoChen** [comment]
No, anywhere above the AI core isn't targetable. The turrets are supposed to be able to hit any space that isn't glassed off.

**Comment by Bawhoppen** [comment]
it made it so the paths were accurate diagonally now as opposed to the old arbitrary dumb paths

see:
![80ee27c6-9391-11e5-9d55-08f0c926475a](https://cloud.githubusercontent.com/assets/6510293/16713078/8ebbcea2-4661-11e6-87b3-66e9b930b942.png)

**Comment by WJohn** [comment]
This is due to pixel projectiles. Yes. Before that, I checked to make sure they could hit you, and they did some friggin' bizzare ass curving around the glass panels that the AI is protected by in order to hit you, so it used to work fine.

I'll have to reorganize the turrets.
