### ISSUE TITLE
Lavaland prison sleeper ruin spawned in a lake full of lava, also bugged lighting so you can't see where are you walking.

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#19042]
The lavaland prisoner sleeper ruin spawned so that the only exit was covered by lava, and was unable to be seen, resulting in blind running, and almost zero chances of getting out. Also it was spawned in a way that you HAD to use the lavaboat to get out, and you still had to cross lava to get to it, and needed to either guess where it is or ghost and disable darkness.
TL:DR; Prison ruin spawned so you couldn't get out, also bugged lighting.

**Comment by Bawhoppen** [comment]
dupe of https://github.com/tgstation/tgstation/issues/17450

**Comment by evsey9** [comment]
Oh, sorry then, Bob just told me to post me an issue and i did so.

**Comment by Bawhoppen** [comment]
yes thats fine when in doubt post an issue report but you can go ahead and close this one

**Comment by evsey9** [comment]
Alright, thanks.
