### ISSUE TITLE
Scythes don't work on kudzu

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#19058]
Neither do welders. I'm talking unmutated, plain old green kudzu. Why is a hatchet and a flamer the only counter for a potentially round ending weed? Also bluespace vines growing into windows aren't killable unless you break the window.

**Comment by xxalpha** [comment]
The entire reason for scythes existing is kudzu so this is pretty bad.

**Comment by Davdichan** [comment]
Better question: Why doesn't the Janitor start out with a Scythe in his closet?

**Comment by xxalpha** [comment]
Because that's dumb.
