### ISSUE TITLE
Overdosing on antitoxin still drains blood from slimemen instead of adding to it

### ISSUE THREAD

**Issue by XDTM** [tgstation/tgstation#19054]
Because for some reason taking tox damage as a slimeperson removes 5 times the damage from blood volume, while healing only gives 1 each; and overdosing on antitox therefore removes (2_5) and adds (4_1), despite you actually healing from damage.

**Comment by Incoming5643** [comment]
That's actually exactly why the inequality is there, to stop people from abusing OD mechanics that logically shouldn't work. Ya done tried to play me but got played yourself.

**Comment by Jalleo** [comment]
@Dorsisdwarf what ^ said.
