### ISSUE TITLE
Malf AIs hacking APCs get stuck if the APC they are in the process of hacking is destroyed

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#19063]
...such as being eaten by a singularity. The APC will never register as being completely hacked, so the malf AI will not be ever able to hack a new one. 

Reported by a player, needs testing/reproducing, also imma put feature requests here:

(F) DEAD: Loves-The-Lizards says, "An ability to be able to stop hacking an APC would be nice though"
(F) DEAD: Loves-The-Lizards says, "and even better, knowing which APC i'm actually hacking, I lose track"

**Comment by coiax** [comment]
It's likely that the "finish hacking" is a timer attached to the APC, that would get cancelled if the APC is destroyed. We can probably split the "hack APC" and the "AI can hack a new APC" timers into two seperate ones.
