### ISSUE TITLE
Mechs create some bizzare "mech radio" when destroyed by lava.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#19067]
![](http://i.imgur.com/FlJy0y9.png)

When I walked these mechs through fire and allowed them to burn (I didn't exit them) they were destroyed after a short little while. They then also created some sort of radio item that looks like a ripley mech. I could pick it up and throw it around.

**Comment by RemieRichards** [comment]
it's their internal radio, and it looks like the Mecha because we used to have Radio icons in chat.

**Comment by Core0verload** [comment]
Caused by old bug when items destroyed by fire always dropped their contents.

**Comment by lzimann** [comment]
I think dropping the contents is an intended mechanic for when items burn(lava or normal plasma fires)

**Comment by Core0verload** [comment]
Yes, it was "intended" by some shithead who didn't knew that some objects can store technical items in contents.

**Comment by ChangelingRain** [comment]
No longer happens; mechs take damage properly
