### ISSUE TITLE
Welcome to reality: You cannot build intercom and mirror assembly

### ISSUE THREAD

**Issue by Bill-Luxe** [tgstation/tgstation#19069]
Why? I dont know ¯\_(ツ)_/¯.

Also, why THIS shit cannot be deconstructed?

**Comment by Core0verload** [comment]
also light buttons, request consoles, status screens, signs...

not a bug

**Comment by RemieRichards** [comment]
fun fact: intercoms are just normal radios that you can't pick up.
Because logic.

**Comment by Jalleo** [comment]
This is a dupe old issue might of been closed cant confirm.

**Comment by Bill-Luxe** [comment]
Ok.
