### ISSUE TITLE
Changelings can use mind transfer to give people permament changeling powers

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#19087]
1) Be a changeling.
2) Grow arm blade, aug vision, body armor, etc.
3) Mind swap into someone else.

They now have those abilities, items, organs without being a changeling. With proper transformations, they don't even lose their identity. A friendly changeling can do this to give people armblades, a bad changeling can use mindswap to permamently give someone real and irremovable changeling powers.

**Comment by Cebasiz** [comment]
does this really need fixing?

**Comment by Core0verload** [comment]
Feature.

**Comment by Anonmare** [comment]
Feature. Changelings armblades/armour/Thermal vision are all physical changes made to a body and I'm pretty sure you can remove about 50% of them with surgery if you really cared enough I think. (The changeling vision is an implant in the eyes and the armblade is just a NO_DROP object.) 

Don't think there's a way to remove the organic spacesuit or armour though. Maybe it could be removable with specialised surgery?

**Comment by improvedname** [comment]
Doesnt exist anymore swap forms is removed
