### ISSUE TITLE
Wearing mesons doesn't protect from supermatter shard hallucinations

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#19082]

**Comment by Dorsisdwarf** [comment]
Is it meant to? I hadnt heard this was a thing

**Comment by coiax** [comment]
The code seems to imply it.

**Comment by coiax** [comment]
https://github.com/tgstation/tgstation/blob/36fb46981c6e82e9b888e925a948679e5d760dd8/code/modules/power/supermatter/supermatter.dm#L199

**Comment by Shadowlight213** [comment]
It does protect you.
I tested it, and I can't seem to reproduce this issue.

**Comment by Firecage** [comment]
Ditto here.

**Comment by Firecage** [comment]
@optimumtact Seems to be a dud issue now.
