### ISSUE TITLE
"Spawn removal" can result in a fuck-ton of maintainability problems

### ISSUE THREAD

**Issue by Core0verload** [tgstation/tgstation#19099]
Mindlessly removing every single "spawn" call would make finding usage of any function impossible. Then someone will rename/remove/change some of "spawn" functions, resulting in silent, hidden, hard-to-track bugs.

@coiax

**Comment by coiax** [comment]
I don't understand any of these points. "finding usage"? "renaming?" Addtimer not finding a function makes runtimes, hardly a silent bug.

**Comment by optimumtact** [comment]
This isn't a bug and is probably better suited to a discussion in irc or the forum.
