### ISSUE TITLE
Admin ghosts can empty people's pockets

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#19114]

**Comment by Aloraydrel** [comment]
if you have nothing to hide you have nothing to fear!

**Comment by Shapsy** [comment]
Is it too much to ask to let admin ghosts strip people with no restrictions, like how they can interact with APC's and stuff

**Comment by Shapsy** [comment]
Also they can enable/disable internals as well

**Comment by ChangelingRain** [comment]
It'd be neat but it probably shouldn't be on by default

**Comment by lzimann** [comment]
Just put it all behind the admin AI interaction(and maybe change the name to fit better). Also, admins can interact with PDAs with no restriction aswell.

**Comment by Anonmare** [comment]
It was a feature!

**Comment by Aloraydrel** [comment]
STUPID BELATED RABBIT

**Comment by Poojawa** [comment]
Oh, since mine was closed I'll update that Admin ghosts can also pilfer from filled rechargers, even change the settings kill/disable and drop them.

**Comment by Anonmare** [comment]
Still a feature
