### ISSUE TITLE
Hotel Staff don't have access

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#19128]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

As title says. I'll do some testing later on it, but I couldn't leave the Hotel Security Checkpoint door. I couldn't test the others because I couldn't leave, obviously.

Edit: It's a whole lot worse. Staff don't even have access, nobody does.
[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by MMMiracles** [comment]
t'was cleary a clever ruse, publishing half-done features to rake in all those sweet mergetokens from the bug reports shortly after.

seriously though i did an oops when assigning access to the cards time for quickfix.
