### ISSUE TITLE
Pickaxes are spawning inside the walls of the necropolis bridge.

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#19127]
![the black pearl 2016-07-04 154025](https://cloud.githubusercontent.com/assets/8237862/16568904/daf6f084-41fd-11e6-9f10-7adab6d65300.png)

**Comment by Zilenan91** [comment]
Are you sure this wasn't admins because this is really bizarre

**Comment by Imagebard** [comment]
Uh, I thought it was intentional.
This seems to be happening consistently.

**Comment by Hatfish** [comment]
Nope, it definitely wasn't admins because I saw it on both Sybil and Basil after a bit of serverhopping.

**Comment by coiax** [comment]
Caused by a map merger bug, this was fixed in #19122
