### ISSUE TITLE
Explosions on a moving shuttle create regular space and not transit space

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#19135]
1) Have shuttle in motion.
2) Explosion.
3) Space is created, not transit space.

Likely a bug caused by my recent shuttle changes, I will investigate how to fix.

**Comment by KorPhaeron** [comment]
Did this fuck up landing on planets as well?

**Comment by Jalleo** [comment]
This might be easily fixable with one or two things i think.

**Comment by coiax** [comment]
Fixed by #19171
