### ISSUE TITLE
Space Hotel Spawning ID's set wrong

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#19136]
The ID's the Hotel Space staff and security start with have there access setup wrong.

The VV "Access - /list" is set up like this currently (for the security):
200 = NULL
201 = NULL
203 = NULL

when it should be:
1 = 200
2 = 201
3 = 203 
etc

**Comment by Boredone** [comment]
Probobly related to #19128 though this seems to point out the exact problem.
