### ISSUE TITLE
tgui

### ISSUE THREAD

**Issue by kilkun** [tgstation/tgstation#19131]
[Note]: # when opening a tgui menu it opens fine the first time. after it gets closed it doesn't open again.

normal html menus like the disposal chute and the pda work fine.

kill tgui.

**Comment by lzimann** [comment]
I've noticed it happening a few times, some tguis not opening again, having to delete the obj to make it work again

**Comment by coiax** [comment]
I have also noticed this recently, I think it's a recently introduced bug.
