### ISSUE TITLE
For some reason you still bleed if gauze is used 

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#19148]
He has severe bruising!
He is bandaged with something.
He is bleeding!

**Comment by Xhuis** [comment]
Could've been shot up with heparin. It makes you bleed crazily even when bandaged.

**Comment by anconfuzedrock** [comment]
definitely not

**Comment by dhostak** [comment]
Gauze doesn't fix bleeding all the time, not sure it was intended to be bleeding through the bandage or not but I've seen this a lot.

**Comment by Firecage** [comment]
As a side note, I never used to see this, the Gauze always stopped bleeding. Then suddenly it stopped working properly during the same week we got dismemberment. So maybe it somehow has an effect on the gauze's bleeding stopping?
