### ISSUE TITLE
Certain floor tiles go black in an explosion.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#19147]
It appears to be affecting damaged warning tiles, which metastation has a ton of.
![](http://i.imgur.com/7ElzFIq.png)

**Comment by ChangelingRain** [comment]
I think it's all warning tiles, I keep seeing it then forgetting to report it

**Comment by xxalpha** [comment]
I think it was reported already?

**Comment by coiax** [comment]
@MrStonedOne Did you fix this?

**Comment by MrStonedOne** [comment]
No, its because warning.dmi has no damaged1-5 states we could either import them, or override the break proc to change the icon

**Comment by ChangelingRain** [comment]
the damage really should be an overlay tbh, it'd be easier to maintain

**Comment by MrStonedOne** [comment]
[18715] added this bug.

**Comment by xxalpha** [comment]
This is why floor code needs to be changed. ALL floor icons are in a single dmi and I forgot to copy the damage icons over to the new dmi.

Overlays sounds like the best solution.

**Comment by Cyberboss** [comment]
Literally just happened on sybil
