### ISSUE TITLE
shunting removes the doomsday timer

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#19140]
There's a host of bad issues with Doomsday that still need fixed. There's no way to reduce the timer, shunting disables it. 

Also the AI still has the fireproofing power, which is still a newbie trap (hint: it does nothing). I accidentally bought it recently thinking it was the turret upgrade.

**Reported already, but the turret placement on box is still shit and it can't hit anything north of the glass surrounding the AI core, thanks to new projectiles.**

Also Shunting puts you in a new mob named SHODAN, for some reason.

**Comment by Dorsisdwarf** [comment]
1) Atomic issues. Don't make issue reports like "1: clown is gay 2: detectives baton sucks"

2) Shunting cancels the doomsday timer. Thats the tradeoff. It's not malf mode anymore

**Comment by Imagebard** [comment]
I'm just going to be told to go to the design forum but before I am,

>Thats the tradeoff. It's not malf mode anymore

**Wat**

**Comment by Zilenan91** [comment]
It's so that one antagonist in a round full of antagonists doesn't blow the whole thing up and instantly end the round for everyone else. It was fine in malf since that was malf, that's all there was, but not in Traitors.

**Comment by ChangelingRain** [comment]
this is intended plus one unrelated issue make atomic issues etc
