### ISSUE TITLE
Water Grenades do not make floors Slippery

### ISSUE THREAD

**Issue by Boredone** [tgstation/tgstation#19157]
This is kinda minor, but still a bit of a problem.
Tested with a normal grenade full of just water in both beakers.
Admitedly haven't tested smoke and such, but I doubt that would work.

**Comment by RandomMarine** [comment]
When not using a special reaction like smoke, chem grenades splash the reagent evenly on everything in range. And you need a minimum 10u splash of water to wet a tile.

This isn't a bug, you just need to use more water. A LOT of water.

**Comment by RandomMarine** [comment]
Aaand here's the reason.
https://github.com/tgstation/tgstation/blob/master/code/modules/reagents/chem_splash.dm#L65
Turns out everything in a chemsplash is halved for some... arbitrary reason. Balance concern? Does anyone even use basic chemsplashes for anything other than space cleaner?
