### ISSUE TITLE
shuttles take years to go anywhere now

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#19159]
I'm misusing the issue tracker but this is pretty obnoxious for miners

**Comment by Jalleo** [comment]
@coiax

**Comment by coiax** [comment]
Ooof, oranges ignoring the design lead

**Comment by coiax** [comment]
Mining shuttle has a 10 second ignition timer, 15 second transit time.

**Comment by KorPhaeron** [comment]
@coiax 

Where is the ignition timer set?
