### ISSUE TITLE
Fireplace Feedback/Issue

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/tgstation#19184]
The main notable issue right now is that when you place your four logs into the fireplace, and light up the fireplace.  When it moves down the stages, and you add more logs to it, you always add four, so even if its a stage 3 fire, you will still add 4 logs to update it back to a stage 4 fire when in reality, it would seem like it should only take 1 log and so on, meaning that if you want to be conservative with your fuel, you gotta wait til your fire dies down or else its wasting fuel and it doesn't really make sense.

Fireplaces also seem to be always luminous for some reason, like the sprite is always light even if its completely dark around it, its likely a byond issue or something because it reminds me of the issue where you sometimes see a sprite in perfect light even though its completely dark.

My own opinion here but fires burn wayyyyy too fast but it's difficult to judge because of the different stages and buggy log feeding right now.

Random tidbit to-do: Make it so clicking on a lit fireplace with nothing in hands warms you up slightly like drinking coffee does, making fireplaces (if you have one) an emergency warmer.  (Will this need a cooldown to not be spammed?)  (This is also /vg/ functionality, their fireplaces already do this.

@coiax

**Comment by Niknakflak** [comment]
Another request I've gotten from a few players and some admins is that they want to fireplace to function like a microwave and cook things.  I have no idea how anyone would do that nor do I know how to do it myself.  I always intended these to just be neat cozy things :3  The feedback is here anyway regardless.

**Comment by MrStonedOne** [comment]
)

**Comment by SuperNovaa41** [comment]
This is a really tiny thing, also should probably be tested. If I haven't gotten back to this, if anyone sees this please test it :)
