### ISSUE TITLE
Zombies can receive stamina damage and be killed by toxins damage.

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#19199]
They can also be conventionally stunned with a stun baton or taser.  Needless to say, zombies should probably not be affected by any of these.

**Comment by Incoming5643** [comment]
Zombies have reverse toxin damage, they can't be killed with poison, but can be killed with healing. It's a RPG shout out.

**Comment by Hatfish** [comment]
IIRC zombies are meant to be a round-ender like xenos used to be, and stunning a zombie is too easy considering just how slow they are.

**Comment by Dorsisdwarf** [comment]
Zombies shouldnt be able to be stunned, they're simple mobs. Is this referring to the round in which niknak tried to make zombies during a traitor round but just set someones species to zombie instead?

**Comment by coiax** [comment]
@Dorsisdwarf We don't have simple mob zombies anymore, they've been replaced by a human subspecies with auto equip NODROP | ABSTRACT "zombie claws" in both hands.

**Comment by coiax** [comment]
Anyway, this isn't a bug, this is a design issue. Ever since zombies were turned humanoid, they became vulnerable to stuns and stamina.

**Comment by optimumtact** [comment]
They're gettable through so many means that they cannot be an "overpowered round ender" any more

I'm closing this as intended.
