### ISSUE TITLE
tele-gulag reclaimer thingy is bugged to fuck

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#19202]
I suck at explaining fuck
if you try to use the gulag reclaimer thing, you need to insert your id, right? if you don't insert the id then it shows you the list of people's stuff that can be retrieved, but the button is greyed out because the id isn't in.
if you put the id in, the list of people's stuff dissapears, as if nobody was teleported into the gulag. it is 100% impossible to get your stuff out from my experience.

**Comment by TechnoAlchemisto** [comment]
@lzimann

**Comment by jughu** [comment]
What would happen if you use the nuke disk

**Comment by lzimann** [comment]
Yea I'm aware of this bug but I still didn't figure out why it is happening.
