### ISSUE TITLE
You can block poeple with meatspikes

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#19212]
https://www.youtube.com/watch?v=VR6qUM70RRA&feature=youtu.be

**Comment by coiax** [comment]
Meatspikes are super buggy. If you decon one while someone's stuck on it, they just keep hanging there

**Comment by PKPenguin321** [comment]
![1](https://images-na.ssl-images-amazon.com/images/I/51S%2BpPtReeL._SY344_BO1,204,203,200_.jpg)
