### ISSUE TITLE
Cardborg camouflage not working on module-less borgs

### ISSUE THREAD

**Issue by BananaSenor** [tgstation/tgstation#19221]
While I had no module selected, I could see the human in full cardborg suit as human. As soon as I selected my module, he was a "borg".

**Comment by Firecage** [comment]
@AnturK I can't seem to reproduce this. I was a module-less borg, and the cardborg disguise worked.

**Comment by Buggy123** [comment]
Couldn't be reproduced, no further reports, we should probably close this.
