### ISSUE TITLE
Legion is somehow becoming one pixel large

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/tgstation#19226]
Somehow, the big Legion boss is shrinking to sizes much smaller than it should be, but even worse, its getting so small that you have like 2000 healthed one pixel legions murdering things that are untouchable.  CODE RED

**Comment by N3X15** [comment]
Literally special snowflakes

**Comment by kilog** [comment]
more like code DEAD heh

**Comment by Crushtoe** [comment]
I'd love to see a picture of this.

**Comment by Xhuis** [comment]
I tried to rework Legion's mechanics but _noooo_, this is what you get.

**Comment by ChangelingRain** [comment]
I FIXED THIS
