### ISSUE TITLE
Disarm does not work properly

### ISSUE THREAD

**Issue by alphaaBeta** [tgstation/tgstation#19231]
You can't disarm someone out of an item that is being held in left hand. Except for pushing them.

To reprdoduce: Have one human hold an item in left hand, try to disarm them. You can even have them hold items in both hands to see it doesn't work. 

It also doesn't work when using krav maga gloves.

**Comment by GrayRachnid** [comment]
I'm pretty sure that when someone holds something in a hand but switches his "active" have to another hand, the only way to remove it from their hand then is to stun them or push them down. As long as the item is not in their "Active" hand then you cannot "disarm" it.

**Comment by Bawhoppen** [comment]
feature

**Comment by alphaaBeta** [comment]
Yeah, it appears that's the case.
