### ISSUE TITLE
Map tagging

### ISSUE THREAD

**Issue by nullquery** [tgstation/tgstation#19239]
There are currently a few "fixed" z-levels used in the game for various purposes. For instance, a lot of the code assumes that z-level 1 is the station.

I'd like to get rid of the z-levels altogether and place a small "tag" landmark on the map to point to areas.

The locate() proc would have to be deprecated in favor of a proc that accepts a tag instead of a z-level.

The benefit of this approach is that it would be possible to have multiple smaller maps contained in a single z-level, and to allow maps to be loaded independently of the z-level they ultimately appear on. It would also permit developers to "replace" maps by modifying the tag.

I need this change for my own project, but I'd like to maintain compatibility with /tg/station for as long as possible. Hence opening up discussion on how this would be implemented in a 'standard' way that everyone can live with.

---

The current approach I have in mind:
1. Add a "tag" object which can be added to the start sector of a map (the lower bound x/y). This would contain the tag as well as the map size (the upper bound x/y).
2. Expose the maps as a map object in the code. This map object would contain a proc to locate a turf within its bounds.
3. Use the preprocessor to ban the use of locate() throughout the project, replacing it with an '#error' that warns developers to use the new syntax.
4. Refactor every instance where locate() is used to use the new system.

---

One drawback that springs to mind is that administrators might want to use varedit to modify an object's x/y/z variables directly. I don't think this occurs that much for this to be a factor, however it does beg the question who else would rely on x/y/z being predictable?

**Comment by xxalpha** [comment]
:-1:

**Comment by Iamgoofball** [comment]
:-1:

**Comment by Penguaro** [comment]
@Dorsisdwarf @nullquery This is more of a feature request and not really a bug or map issue. Unless you can identify something specific that is causing an issue, I recommend closing this.

**Comment by duncathan** [comment]
NQ is dead and it only really mattered to him

**Comment by Penguaro** [comment]
@duncathan As in not really involved anymore or like deceased dead? )-8

**Comment by duncathan** [comment]
The former but we can't really rule out the latter either
