### ISSUE TITLE
Damp rag issues

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#19245]
Damp rags can be used to clean off clothing items and your hands, except for the jumpsuit. With the exception of your hands, cleaning off your clothing does not show a progress bar.

**Comment by WJohn** [comment]
Another thing to note: Gloves cleaned in this manner will not actually show themselves to be cleaned on your mob (they are clean in your inventory) until you've taken them off and put them on again.

**Comment by ShizCalev** [comment]
Cleaning jumpsuits was fixed (probably by the component addition.) Progress bar thing is still an issue though. Seems it's getting hidden behind the rest of the icons in that area.

**Comment by ShizCalev** [comment]
![image](https://user-images.githubusercontent.com/6209658/35080540-4062f05a-fbdc-11e7-9e31-4edf72071a42.png)
![image](https://user-images.githubusercontent.com/6209658/35080547-45cc1774-fbdc-11e7-9631-3184b5882b95.png)

**Comment by nemvar** [comment]
This has been fixed.
