### ISSUE TITLE
dismemberment targeting issues

### ISSUE THREAD

**Issue by hornygranny** [tgstation/tgstation#19259]
Currently if you have are targeting a limb on the doll that your target does not have, you will get the "attempted to attack" message and not do anything (I believe it still plays the hitsound too). This is very much counterintuitive and clumsy. Attacks on missing limbs should probably auto-target the chest.

**Comment by hornygranny** [comment]
for obvious reasons this is bad for the user experience, as if you happened to have a limb targeted for healing and end up in a fight you might cut off a limb without realizing and then lose

**Comment by dhostak** [comment]
I don't think this was a bug as it seems intentional with the 'attempts to attack' but I agree with the fix, I once dunked a traitor because of this.  He hit me about 10 times with an esword and couldn't figure it out that my arm was already off

**Comment by hornygranny** [comment]
i think the current behavior was done to avoid runtimes, but it sucks
