### ISSUE TITLE
Cult constructs can't use cult telepathy

### ISSUE THREAD

**Issue by InsaneHyena** [tgstation/tgstation#19251]
Pls fix.

**Comment by ChangelingRain** [comment]
If it's harvesters, not a bug.

**Comment by InsaneHyena** [comment]
No, I'm referring to actual constructs.

**Comment by ChangelingRain** [comment]
In that case I need more info; how was the construct made, were you added to the construct by an admin, were you actually a cultist

**Comment by InsaneHyena** [comment]
I got a "Do you want to be a shade" prompt, clicked yes, was inserted into a shell. While I could hear cult telepathy, I couldn't use it (no action button) as a shade or as a construct.

**Comment by ChangelingRain** [comment]
Were you a cultist before dying and becoming a shade?

**Comment by InsaneHyena** [comment]
No, I was just a ghost, wasn't an antag that round.

**Comment by Buggy123** [comment]
Has gone a year without further reports/reproducing, can probably close.
