### ISSUE TITLE
macrobomb not triggering from explosion

### ISSUE THREAD

**Issue by dhostak** [tgstation/tgstation#19262]
As a war op I downed the captain who had a maxcap inserted into him with a health analyzer, when he died I was in the tile next to him (dragging) and when I died my macrobomb did not trigger, at the end screen it also said I had 'died' instead of 'and had their body destroyed'
![proof](https://cloud.githubusercontent.com/assets/15916150/16717179/77e9ad3c-46d6-11e6-82ad-0ae26c5754e9.png)

**Comment by TechnoAlchemisto** [comment]
macrobomb has a timer, so if you gib it won't detonate.

**Comment by ChangelingRain** [comment]
It also won't detonate unless you deathgasp, and if gibbed you will not deathgasp.

**Comment by Zilenan91** [comment]
Can't you also activate it manually and avoid the deathgasp trigger

**Comment by lzimann** [comment]
the action button is only active if you are concious(so if you are critted/sleeping, if i'm not mistaken even stunned it wont let you activate by it)

**Comment by ChangelingRain** [comment]
Using the *deathgasp emote is possible at basically any time, even unconscious, just as a note.

**Comment by lzimann** [comment]
Yes, which makes the action button not being active at all the times really stupid

**Comment by octareenroon91** [comment]
What the hell happened here?

If you gib, you'd have "body destroyed", right? Or is that only if you don't even have a brain left?

**Comment by Dorsisdwarf** [comment]
Old issue, unable to reproduce.
