### ISSUE TITLE
Flyperson mime/clown not healing

### ISSUE THREAD

**Issue by Waismuth** [tgstation/tgstation#19263]
Eating a banana as flyperson clown, or drinking nothing as flyperson mime doesn’t heal you. Eating the banana or eating the banana-induced vomit doesn’t heal the flyperson clowns, the same for nothing and mimes.

**Comment by TechnoAlchemisto** [comment]
that's because fly people don't process what they eat, they just straight throw it up. Ingested shit is pretty much worthless.

**Comment by octareenroon91** [comment]
Smoking it is gross but seems to work.

Flypeople can't keep consumables down, which bananajuice and nothing are.
