### ISSUE TITLE
Space torus code doesn't work right and isn't needed, but is too nice to destroy

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#19276]
Ever since randomized space, having convoluted space torus z transitions hasn't really been needed. Since everything out there is random, their relative order to each other is irrelevant. That alone wouldn't warrant its removal.

The problem is the space torus is absolutely rife with self looping z levels, by my count EVERY z level self loops either north/south or east/west. Consequently the geometry of space is always either 9x1 or 1x9. Either you're self looping or your looping through everything. There is absolutely no reason we couldn't just use the 9 cross linked z leves in a 3x3 grid formation and be done with it and remove all self loops.

It's just that the current code [space_transition.dm] just cannot properly do that. Attempting to expand the grid to a 3x3 square leads to a formation where the z levels form a zigzag diagonally jointed mess. There doesn't seem to be any proper way to do this and it'd be too much of a shame to just scrap it entirely.

A note on ministation z5: Ministation is the only station not using lavaland, and that's important because with lavaland there's a proper 9 cross linked z levels, but without it there's 10. HOWEVER there's no mining shuttle at all on ministation, and in fact their z5 is self linking, meaning it's a dead zone where nothing can ever enter or leave. This means you don't need to give special consideration to it.

Tried to do this myself but not great at reading the code so whatever :cow2:

**Comment by LanCartwright** [comment]
My math here reads that I can map out zlevel ruins to a 20-30% accuracy average across the board. Are you sure space transitions are awful?

Because I'm still the king of space.

**Comment by ShizCalev** [comment]
Still an issue?

**Comment by SpaceManiac** [comment]
>Consequently the geometry of space is always either 9x1 or 1x9

This particular bug stopped being an issue at some point, I've never observed it. The various z-level update PRs of a few months back (#34090, #35339) have - I believe - handled the rest.
