### ISSUE TITLE
Shuttle docking deletes ai camera eye mob and possibly prevents it from respawning until undocked

### ISSUE THREAD

**Issue by TheWiznard** [tgstation/tgstation#19279]
Server revision compiled on: 2016-07-11
8493c7ac9018e0ed93f9682349f4ac7747d97e95 

I was the AI and I had the center of my screen (which is where the ai eye mob is) over one of the mining shuttle ripples before it docked at the station. When it docked my screen went black and I was forced back into my core vision.

When the mining shuttle first docked and it blanked out my screen, it looked just like the screenshot in #18906 , but it quickly returned to my core view like when you're not looking through the cameras. 

Nothing I did could fix it, re-logging, cancel camera view, view core ; When the mining shuttle left again though I got this message "Error: Eyeobj not found, creating a new one..." or something very similar to that and then my vision returned and I could move again. 

@Niknakflak said something about it deleting my camera eye mob

**Comment by MrStonedOne** [comment]
@coiax what did you do!

Seriously, everytime somebody touches shuttles they remove this exemption thinking "what's this do, i'll just remove it!"

**Comment by ChangelingRain** [comment]
uh, my pr didn't cause that?
I'm pretty sure whoever added the isliving() caused it, because that pr wouldn't

**Comment by ChangelingRain** [comment]
Oh look, I found the line that caused it!
https://github.com/tgstation/tgstation/pull/17436/files#diff-8d50796c8e2b4ec669f94278cf488abdL555
