### ISSUE TITLE
Can't see c4s attached to medals(or any accessory)

### ISSUE THREAD

**Issue by lzimann** [tgstation/tgstation#19270]

**Comment by MMMiracles** [comment]
emergent gameplay

**Comment by lzimann** [comment]
my only problem is that there's absolutely no way to see the c4

**Comment by Jalleo** [comment]
@dorsisdwarf oh god this is bad.

**Comment by PKPenguin321** [comment]
feature

**Comment by ike709** [comment]
inb4 the captain starts giving out loads of medals

**Comment by TechnoAlchemisto** [comment]
this is fucking sick keep this in

**Comment by AnturK** [comment]
Don't accept medals from strangers kids.

**Comment by rintezukas** [comment]
holy fuck i love this

**Comment by Jordie0608** [comment]
This isn't really fixed.

**Comment by lzimann** [comment]
updated title to be more accurate to the real issue

**Comment by octareenroon91** [comment]
c4 overlay is plain missing on any atom as of revision 98be1a3eab23dbd3ce13c9ebc8e49736192d45a8

Updating...
