### ISSUE TITLE
If you have an eye of god and pick up another one it gets stuck to your hand

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#19307]
![image](https://cloud.githubusercontent.com/assets/6778786/16825773/7d14c83e-4945-11e6-9a87-0ec4c8bbea9e.png)

I thought i'd be able to combine them

You should be able to combine them so both of your eyes flash or you get some unique power or some shit because the amazing nodrop power kinda sucks ass

**Comment by TechnoAlchemisto** [comment]
I honestly never considered that people would ever find two
