### ISSUE TITLE
Riot Helmet sprite doesn't work with facial hair

### ISSUE THREAD

**Issue by Lumbermancer** [tgstation/tgstation#19313]
http://i.imgur.com/o1zixGZ.png

Helmet face cover closed. All is fine.

http://i.imgur.com/lWuBcSY.png

Helmet face cover open. WHAT'S WRONG WITH YOUUR FAAAACEEE!

**Comment by WJohn** [comment]
I think it's actually hiding a mask on the closed cover. Easy fix.

**Comment by Lumbermancer** [comment]
It wasn't fixed.

**Comment by Lumbermancer** [comment]
It's almost 1 year anniversary.

**Comment by optimumtact** [comment]
don't tag me please

**Comment by PraiseRatvar** [comment]
@KorPhaeron you attempted to fix this, dont give up so easy

**Comment by kingofkosmos** [comment]
Cannot reproduce.

**Comment by kingofkosmos** [comment]
Cannot reproduce. The visor covers the mask fine, tried it with internals mask, bandana and a balaclava.
