### ISSUE TITLE
paper cutter glitch

### ISSUE THREAD

**Issue by rintezukas** [tgstation/tgstation#19314]
used a piece of paper on the paper cutter (found in the security office in the hotel) and it turned into a single sheet of paper labelled "paper cutter". clicking it again sliced this paper into two slips which i could do nothing with, and did not return the paper cutter to its normal state

**Comment by DorfGuy1** [comment]
Can confirm,
this actually happens, and it warps through the table, if you pick it up, then it slices the paper

**Comment by jughu** [comment]
Paper is mysterious
