### ISSUE TITLE
Doomsday device doesn't work

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#19327]
There is no longer any timer/announcements of the countdown

**Comment by MrStonedOne** [comment]
@coiax

**Comment by coiax** [comment]
I don't think this is a bug anymore, surely

**Comment by KorPhaeron** [comment]
I saw similar happen recently, timer just stopped announcing for the last 3 minutes

**Comment by coiax** [comment]
Is this still happening?

**Comment by TehZombehz** [comment]
Saw this again recently. It won't show up on the status screen and won't announce every 30 seconds like it's supposed to.
