### ISSUE TITLE
autocapitalization

### ISSUE THREAD

**Issue by rintezukas** [tgstation/tgstation#19320]
not actually a glitch, but a minor inconsistency: text is autocapitalized to enforce grammar or something, but individual "i"s, which are always capitalized when you're typing in, like. formal grammar, are not, which means you have the worst of both worlds: you're forced to look like you're typing formally, but it looks weird and bad if you're not actually doing it

**Comment by WJohn** [comment]
Dots are also not applied at the end of your text, and it can be pretty confusing when emoting as sometimes there's a dot, sometimes there isn't?

It should also autocapitalize the "i" in /me, too.

**Comment by PKPenguin321** [comment]
This is a feature request

**Comment by optimumtact** [comment]
You're right
