### ISSUE TITLE
Shuttle rotation is basically just super broken now

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#19324]
![sybil procreatory fortress omega 2016-07-14 205204](https://cloud.githubusercontent.com/assets/3886584/16860313/fad6c410-4a04-11e6-8ec0-9bd550dded09.png)
yeah uh I think @coiax broke this but he's gone, this is what happens to the white ship on dreamstation as long as it's not docked at the station

**Comment by Jalleo** [comment]
It may only be a visual issue.

**Comment by MrStonedOne** [comment]
if its anything, its https://github.com/tgstation/tgstation/pull/18974

nothing else has touched shuttles recently enough.

**Comment by Bawhoppen** [comment]
its cause I haven't fixed the map paths yet
