### ISSUE TITLE
Using titanium on a displaced girder doesn't make a false wall, and deletes the Titanium.

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#19336]
Basically I tried to make a false wall on the emergency shuttle, but when I used the Titanium sheets on the displaced girder, it told me it made a false wall, but it didn't do anything, and instead just deleted the Titanium.

**Comment by Bawhoppen** [comment]
will be fixed shortly

**Comment by Jalleo** [comment]
@Bawhoppen

**Comment by Bawhoppen** [comment]
PR is up
forgot to say that it fixed this
