### ISSUE TITLE
Dumping plants onto a seed extractor with a plant bag does not turn plants into seeds

### ISSUE THREAD

**Issue by ma44** [tgstation/tgstation#19356]
If you put plants onto a seed extractor one by one, it turns into seeds.
How come dumping plants on a seed extractor doesn't turn all the plants to seeds?
This would also be a quality of life feature, as it makes turning plants into seeds for exporting so much more easier.

**Comment by GrayRachnid** [comment]
The portable seed extractor can mass extract plants on a 1:1 ratio.
While the seed extractor has a % to increase the amount of seed packs that spawn.
Making it so you can use a plant bag to mass extract seeds will probably make the portable extractor even more useless that it already is(I bet you nobody even knows it can extract).

**Comment by Bawhoppen** [comment]
its called portable extractor ofc people know you can

**Comment by optimumtact** [comment]
Not a bug?
