### ISSUE TITLE
Issue with Ligger Tail Attachment surgery.

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#19350]
So, I cut off a liggers tail, and then stuck it to a humans butt. Unfortunately, the tail at first appeared fully invisible. After I had him wag it, the tail did....show up, kinda....But it looked VERY off, and the tail sprite was also giving issues, like if he faced north, it was fully invisible behind his jumpsuit.

**Comment by Hatfish** [comment]
This happens to lizards as well, only the tail is always invisible.
