### ISSUE TITLE
Photo camera is not photographing lots of stuff

### ISSUE THREAD

**Issue by BananaSenor** [tgstation/tgstation#19383]
The photo camera is not photographing lots of important stuff. Dead Ians, consoles and machines and more. Quite sad if you finally manage to catch the Clown with Ian in dorms, just for it to not show on the image.

**Comment by optimumtact** [comment]
Known and probably not ever going to be fixed, since the flatIcon proc is huge and terrifying for most people to look at.

**Comment by francinum** [comment]
Cameracode is a horrorbeast.

**Comment by Detective-Google** [comment]
![image](https://user-images.githubusercontent.com/48196179/64509112-a8349a80-d2a4-11e9-8cc1-0008438bffea.png)
pictured, a machine, one dead ian, seems to work fine
