### ISSUE TITLE
Some nerd used the lavaland ruin area for space ruins and it ruined the names

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#19384]
Golem ship is now named Space Bar, ash lizard nest is derelict outpost, etc

@MMMiracles

**Comment by MMMiracles** [comment]
The last branch I pushed have none of these issues, don't bring me into these shenanigans.

**Comment by KorPhaeron** [comment]
@Bawhoppen 

This is all your fault

**Comment by Mervill** [comment]
@optimumtact no longer an issue, closeable

**Comment by KorPhaeron** [comment]
This is still a thing for some lava ruins, but Phil fixed space

**Comment by Mervill** [comment]
which? I'll fixit
