### ISSUE TITLE
Gulag is cruel and unusual

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#19385]
Gulag mine is awful, and sec doesn't even really care.

First off, 100 points of work is easily 5 minutes of digging. All that can be found on gulag is iron, which is worth basically nothing point wise. There's no valuable ore so miners will laugh at you from across the lava river while you sit in Gulag endlessly toiling.

Now, the average security officer won't give you 100 points if you're going to gulag. Expect probably 500 because security hates you. That's 20 minutes of work, minimum. You can expect to get this for simple assault or whatever because space law. Even brig doesn't hold you for more then 10 minutes, over a major crime.

Oh, did I mention lava? Lavaland is dangerous now and there's a fair chance something will kill you while you dig for iron, with inferior mining tools, no bag, etc etc.

**Comment by ike709** [comment]
can't do the time don't do the crime

**Comment by MMMiracles** [comment]
Sand and metal. 

If you didn't want to be forced labor then don't piss off security enough to throw you into the gulag.

**Comment by YakumoChen** [comment]
Sand is worth even less.

Any punishment over 10 minutes for a non-perma crime is utterly ridiculous. Gulag should at least have better minerals to use.

**Comment by optimumtact** [comment]
Not a bug, take it to the feedback or ideas forums
