### ISSUE TITLE
End-round Report not showing players key's

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#19396]
I waited until I was sure it wasn't just a once-off Edge-case.

It appears that if someone's body is completely destroyed(I am unsure if it requires the destruction of their brain aswell), the End-round report will show their name, job, traitor type, etc. BUT, it doesn't show their keyname. I have seen this happen with Crematoriums aswell, but its most visible when the body destruction occurs due to a bomb.

![end-round bug](https://cloud.githubusercontent.com/assets/4686269/16955622/a3a4296a-4dd5-11e6-929b-d46ec0ffe9b2.png)

Note how the HoS, HoP, and Loves the scientist, lacks a keyname. They all died due to a bomb.

**Comment by Saegrimr** [comment]
Pretty sure this happens if they then join into a new mob like a drone or lavaland role before the round ends.
