### ISSUE TITLE
Chameleon Suit default naming

### ISSUE THREAD

**Issue by yodaman888** [tgstation/tgstation#19392]
The names of the default chameleon backpack and headset should be named Backpack and Station Headset instead of chameleon backpack and headset respectively they look the EXACT same as those items and it would fix the inconsistency of the rest of the items default names not giving themselves away.

**Comment by Iamgoofball** [comment]
stop leaving them on the defaults

**Comment by yodaman888** [comment]
Then at least make it consistent across all the items instead of two that are like that for no reason.
