### ISSUE TITLE
Ling tries to revive while being cremated, gets kicked to lobby

### ISSUE THREAD

**Issue by Thunder12345** [tgstation/tgstation#19393]
Not sure exactly of the circumstances since this was reported by a player, but basically they seem to have tried to revive as a ling, been cremated before they could finish reviving, and when it did finish, immediately kicked to the lobby.

**Comment by xxalpha** [comment]
Where is the reviving processed because it should have been interrupted when the body was deleted.

**Comment by lzimann** [comment]
Perhaps an issue with the body being deleted and not deleting properly? It happened a few days ago, a ling with full ling armor bugged and wasn't deleted properly(body still there but not interactable).
