### ISSUE TITLE
HoS Multiphase gun now fires half the rounds at twice the cost.

### ISSUE THREAD

**Issue by ChayseRamsay** [tgstation/tgstation#19397]
I'm not aware if this is entirely a bug, but now the HoS laser is completely underpowered and almost completely useless. May need patching.

**Comment by Davdichan** [comment]
Snowflake gun that didn't need to exist in the first place. Not really sure how this broke though.

**Comment by Jalleo** [comment]
@Iamgoofball possibly otherwise we need to check its history.

**Comment by Iamgoofball** [comment]
its always my fault isnt it

guncrafting isnt testmerged right now

**Comment by ChayseRamsay** [comment]
Remind me to be careful with PRs on my own fork so stuff doesn't change here.

**Comment by Jalleo** [comment]
@Iamgoofball sorry wasnt aware of that i was just stating the last person i am seeing touching the code i didnt know its not test merged.

**Comment by Cyberboss** [comment]
Is it literally supposed to be an egun with a stun mode? Cause that's all it is right now is an egun with a stun mode

**Comment by PKPenguin321** [comment]
:salt:

also remember when all eguns had stun mode
