### ISSUE TITLE
rainbow jumpsuit has a missing rolled-down icon

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#19404]
1. Get a rainbow jumpsuit
2. Alt-click it to adjust it (roll it down)
3. Get this: ![SUIT](http://puu.sh/q7NKA/403db2048c.png)

**Comment by PKPenguin321** [comment]
I don't think that PR actually fixed this?

**Comment by Mervill** [comment]
Can you roll down the jumpsuit at all? It shouldn't let you after this pr

**Comment by Mervill** [comment]
Yeah I get
```
You cannot wear this suit any differently!
```
On the latest build. This is the correct behavior since the rainbow jumpsuit does not have a casual sprite. If you think the rainbow jumpsuit should have a casual sprite, that's a whole other thing
