### ISSUE TITLE
Dismemberment doesn't respect GODMODE flag

### ISSUE THREAD

**Issue by TheSadFox** [tgstation/tgstation#19419]
Shapeshift into something, in my case it was ED.

Fire fireball into a wall/suffer from an explosion strong enough to cause dismemberment. Lose limbs in your human form while being in the shapeshift one. Bonus points if you had an item in hand, and the limb loss (hand that held the item or both legs) will make the item dissapear.

**Comment by Incoming5643** [comment]
This is because the godmode flag is not respected by dismemberment.

If you could change the title to "Dismemberment doesn't respect GODMODE flag", as that's the underlying issue

**Comment by SeikoTheSeal** [comment]
Done.
