### ISSUE TITLE
issue report for sniper rifles

### ISSUE THREAD

**Issue by Shadowhunter215** [tgstation/tgstation#19412]
lets get started with what's wrong with the sniper rifles available to the syndicate, first off, the penetrator rounds either don't do what they are meant to and they do not pierce through all the walls like they should be doing, or something just goes wrong with the targeting on it when used in combination with thermal glasses.
    Second there is a MAJOR problem with its basic functionality as a sniper rifle, which is that it does not have ANYWHERE near the range that a sniper rifle should have where as it currently give you about 14 tiles of range, a sniper rifle should have at least 30 tiles of range (if you ask me).
   My last attempted use of the sniper rifle with penetrator rounds and thermal glasses went about as you can expect with something that did not work as intended, when I was able to get my eyes on a scientist working R&D through the walls with thermals, I fired several penetrator rounds, but to no avail, I made sure that my mouse was directly on the target, but no damage was done when fired, the rounds were designed to be able to pierce all reinforced walls until a certain range, but several other targets after him had the same result, no damage, no knockdowns, and no bleeding, nothing

**Comment by optimumtact** [comment]
the issue with the penetrator working is likely a bug, but the range concerns are something to be discussed in the feedback forum, as the range is a balance issue

**Comment by kriskog** [comment]
Can't reproduce, people die fine though eight rwalls. Probably fixed.

**Comment by sponic** [comment]
Fu@k ss13
