### ISSUE TITLE
You can defrib yourself with no heart, and function fine.

### ISSUE THREAD

**Issue by Darkgenerallord** [tgstation/tgstation#19439]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)
 If you remove your heart and then get defribbed, it stops you from having a heart attack and it never restarts. So basically, you can live forever without a heart. This isn't really a problem per se, but it is a thing.

**Comment by Core0verload** [comment]
Defib is supposed to fail on heartless humans. Definitely a bug.

**Comment by Darkgenerallord** [comment]
It fails after you die, but it definitely works while alive.

**Comment by Iamgoofball** [comment]
I got an idea on a fix
