### ISSUE TITLE
Plasmamen have an emergency oxygen tank in their backpack box

### ISSUE THREAD

**Issue by Man-Shroom-** [tgstation/tgstation#19433]
In the little internals box that all plasmamen start with, there is a breath mask, an epipen, and an oxygen tank.

Please note that plasmamen explode when exposed to oxygen.

WARNING: FEATURE REQUEST

**Comment by Jalleo** [comment]
That would require possibly a lot of work probably not much.

**Comment by Dorsisdwarf** [comment]
Dupe of #16183
