### ISSUE TITLE
Over 100% health

### ISSUE THREAD

**Issue by lordpidey** [tgstation/tgstation#19442]
So, I was dicking around with cyro mixtures on a braindead, and Eventually, he came across as 105% healthy.  Both medical scanners and sleepers show him as 105%.
![screenshot 2016-07-23 07 19 31](https://cloud.githubusercontent.com/assets/8701326/17077669/2f23e534-50a6-11e6-8be5-b28a1cc24444.png)

**Comment by jughu** [comment]
The extra 5%

**Comment by RemieRichards** [comment]
You've <i>improved</i> him!

**Comment by Thunder12345** [comment]
Should've beaten him up a little and healed to see if the increased health was permenant

**Comment by Core0verload** [comment]
Some alcohol drink gives temporary +5 to max HP, this may be related.

**Comment by lordpidey** [comment]
That might have been it.  The cyro mix I threw him in was like 2 pages long.
