### ISSUE TITLE
Slimepersons Swapping Bodies in a Mech Prevents Usage of Mech Controls

### ISSUE THREAD

**Issue by ekuhta** [tgstation/tgstation#19459]
If a slimeperson swaps between two bodies while one body is in a mech, the body in a mech will lose the ability to use the mech buttons (switch equipment, toggle airtank, view stats, eject, etc), while the body outside the mech will keep the targeting crosshair if the mech had a weapon. This effectively traps the body in a mech to be in the mech until it is destroyed, as the eject button no longer functions.

Steps to Replicate:
1. Enter a mech as a slime person. A fully equipped Durand was used during the initial discovery of this bug.
2. Split into two bodies. This will result in one inside the mech, and one outside the mech
3. Swap control between the bodies
4. The body in the mech will no longer have access to the above mentioned functions.

**Comment by Core0verload** [comment]
You can always use resist to eject.

**Comment by Detective-Google** [comment]
Tested, works as intended.
