### ISSUE TITLE
Jumpboots have no sprite.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#19488]
Alright, tested it again, the sprite it just missing totally.

**Comment by xxalpha** [comment]
I don't think this is a sprite problem, blood is overlays. Likely something in the code is wrong.

**Comment by Durkel** [comment]
I'll fiddle with it again once I get the chance, but I had jump boots on with no sprite for sure.

**Comment by MMMiracles** [comment]
The item and icon states are set so I can't exactly see why they'd be missing an on-character sprite.

**Comment by Durkel** [comment]
@MMMiracles The sprites isn't showing in game, tested it again, just nothing there.
