### ISSUE TITLE
Tendril chasms are broken/delayed

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#19500]
All tiles don't appear at once.

I assume this is because when a new tile spawns, and stuff is there, it has to wait for the animation to finish before spawning the next tile

@Xhuis

**Comment by GunHog** [comment]
The expansion effect is not intended? It looked amazing, I think you should keep it, or refactor it to be an intended effect!

**Comment by KorPhaeron** [comment]
Having one random tile appear, then 3 seconds later having another 9 tiles all appear at once doesn't look very good, especially since it's not synced with the sound effect anymore

**Comment by Kromgar** [comment]
Definitely sync it better but keep it as it is now

**Comment by Firecage** [comment]
@KorPhaeron It does sound interesting though if the chasm spreads from a centre point outwards, but I get what you mean, it isn't working as intended and it is a bug.

**Comment by Xhuis** [comment]
Why are you pinging me about this? I don't think I've edited their mechanics.

**Comment by KorPhaeron** [comment]
You added the animation, didn't you?

**Comment by KorPhaeron** [comment]
Or was that coiax

**Comment by Xhuis** [comment]
Probably coiax. I didn't make any animations.

**Comment by Xhuis** [comment]
IT WAS ME AAAAAAAAAAAAAAAAAAAAA
