### ISSUE TITLE
GPS coord names in ruins  are extremely weird

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#19508]
![image](https://cloud.githubusercontent.com/assets/6778786/17144072/902bd11e-5323-11e6-86a2-e747f01b7c86.png)
I've seen ones near the mining outpost labeled as "Necropolis Bridge" one time there was a necropolis bridge in Z8

The gluttony ruins are named space bar if you  can't tell

**Comment by KorPhaeron** [comment]
Whoever mapped the space bar used the exact same area as the ruins, but var edited, so it renamed everything.

Same deal with bridge. People too lazy to add 2 new lines defining their own area in the code have mucked up everything but I have no idea which map "derelict outpost" refers to and I'm putting off looking through 40 map files to figure out which one it is.

**Comment by Shadowlight213** [comment]
I'll do it when I start work on my second ruin fix pass I guess.

**Comment by Penguaro** [comment]
@KorPhaeron @Shadowlight213 @Kromgar 
This particular issue was resolved by the removal of the Space Bar. I'm working on a PR that goes over all the other ruins. I'm about half done with all the lavaland ruins and the space ruins are next. You can probably close this or I'll reference it for close in a few days when I submit my PR.

**Comment by ShizCalev** [comment]
@Penguaro Did you do that PR yet? Still see a couple areas that need to be cleaned up, won't bother if yours is still pending though

**Comment by Penguaro** [comment]
I didn't. I've been blasted with overtime at work and haven't had the chance. Go for it.
