### ISSUE TITLE
Do Not Seem Able to Export Bluespace Crystals and Plastitanium

### ISSUE THREAD

**Issue by Boredone** [tgstation/tgstation#19503]
So, was checking the exports cause why not, and found I can't seem to find either of these in the export files.
I have not actually tried this, but seems a bit strange. Probably minor honestly, but eh.

**Comment by Jalleo** [comment]
@bawhoppen @iamgoofball.

**Comment by Iamgoofball** [comment]
@Core0verload

**Comment by Core0verload** [comment]
I don't know who the fuck added bluespacecrystalfuckery and plastitanium, but they forgot to add export datums. Not my fault.

**Comment by Boredone** [comment]
Eh, actually its BOTH kinds of telecrystals, didn't see either in there.

**Comment by Bawhoppen** [comment]
I thought I added both titanium and plastitanium as exports but apparently only the former

**Comment by Firecage** [comment]
Strangely enough, you can export Plastitanium, but for a ridiculous amount.

**Comment by XDTM** [comment]
That's because it defaults to 5 credits per sheet, same value for iron and glass.
