### ISSUE TITLE
stickmen with guns do not have firing pins in the gun

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#19516]
thats all really

**Comment by YakumoChen** [comment]
well they were around before firing pins so it makes sense?

**Comment by anconfuzedrock** [comment]
wait what stickmen with guns were not around before firing pins what the fuck is wrong with you

**Comment by YakumoChen** [comment]
I'm thinking of something different, whoops

**Comment by Mervill** [comment]
Since you can't pick up a `/pistol/stickman` anyway, do we need to care?
