### ISSUE TITLE
there is no lizard blood in the surgery freezer on boxstation

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#19519]
thats all thanks

**Comment by PKPenguin321** [comment]
lizard blood?

**Comment by jughu** [comment]
Blood Type:L for ligger
Just get iron nerds what do you think this is
A five star resort for lizards?

**Comment by PKPenguin321** [comment]
since when did lizards have snowflake blood?

**Comment by anconfuzedrock** [comment]
since a blood refactor thingy or something and for the love of fuck the blood used to be there and iron takes like 15 seconds per 1% of blood you nerd

**Comment by YakumoChen** [comment]
Boo hoo. Playing a ligger is hard. That's how it should be.

**Comment by xxalpha** [comment]
It's disadvantage for flavor.

**Comment by lordpidey** [comment]
I'm against this lizard blood.  Lizards are supposed to be as mechanically close to humans as possible.  I also wish they could hulk, but that's another issue.

**Comment by Hatfish** [comment]
Why did lizards need a special snowflake blood type again?

**Comment by jughu** [comment]
BECUASE HUMANS ARE SUPERIOR!!!

**Comment by bgobandit** [comment]
this should be closed

**Comment by anconfuzedrock** [comment]
guess so.
