### ISSUE TITLE
blob random event gives no prompt and pulls ghosts

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#19527]
I was literally seconds from being revived and suddenly I'm a blob, kind of salty since the station was here and I can't even do anything

**Comment by Robustitron** [comment]
Had the same issue with syndieborgs. I was pulled into one as an afk ghost by nuclear ops, when I came back I was shot dead by frustrated ops, who then lost their own nuke in space.

**Comment by ChangelingRain** [comment]
I fixed this at some point rip issue
