### ISSUE TITLE
You can still succeed the escape alive objective handcuffed and in shuttle brig

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#19530]
Yellodeath was Desmond Collins the Shaft Miner and survived (used 20 TC)      
Objective #1: Prevent Moves-Boxes-Quickly, the Quartermaster, from escaping alive. Success!
Objective #2: Escape on the shuttle or an escape pod alive and without being in custody. Success!
The traitor was successful!
OOC: Yellodeath: ayyyy green text while handcuffed in sec shuttle

**Comment by ChangelingRain** [comment]
@Bawhoppen

**Comment by Bawhoppen** [comment]
I thought this might happen but when I looked at the old brig floor it didn't actually have any code associated with it, must be a gamemode code thing

**Comment by MrStonedOne** [comment]
ya, the code is done by checking the icon state i think. or the type
