### ISSUE TITLE
Spawned stickmen using the paper mache robe do not attack ANYONE

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#19542]
I spawned stickmen with the paper mache robe thingy and they didn't attack ANYONE I mean the source of the robe was not the boss so maybe its a different version but they just sat there and waved their arms (which was still funny)

**Comment by KingPhilipIII** [comment]
That's because they have the same faction as the crew. Cobby spawned one in for me at one point as a trade and after some testing came to the conclusion they are for fighting carp/necropolis creatures.

**Comment by Mervill** [comment]
Ok I just tested this and @KingPhilipIII is essentially correct, they attack `/hostile` mobs and nothing else.

So: Is this a bug? Should they attack anyone but the summoner?

**Comment by Mervill** [comment]
@AnturK closeable. This item is working as intended, it just crap (a different issue)
