### ISSUE TITLE
Artificer buildings are not ash storm proof

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#19547]
![image](https://cloud.githubusercontent.com/assets/6778786/17199896/858aa6a0-544e-11e6-9623-07dfde24786f.png)

**Comment by Jalleo** [comment]
@korphaeron.

**Comment by jughu** [comment]
THEY ARE but you need blueprints to set the area so it removes the ash storm in the area

**Comment by jughu** [comment]
Not a bug but intended uuuuse

**Comment by Cruix** [comment]
You just forgot to put a roof on your building.

**Comment by KorPhaeron** [comment]
Gotta use blueprints to finish the room yeah

**Comment by Kromgar** [comment]
How does that even make sense.

We have to steal the blueprints to make cult bases?

**Comment by jughu** [comment]
Gotta do effort for a base

**Comment by optimumtact** [comment]
take it to feedback forum
