### ISSUE TITLE
Welderfuel cant melt darkness

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#19559]
Welders didnt light up in the darkness when on for some reason

**Comment by GunHog** [comment]
I do not believe this to be a bug, as there does not seem to be any code related to emitting light. The only light related var relates to flash protection when welding. The request is logical and should be implemented, though.

**Comment by TechnoAlchemisto** [comment]
If I remember this I'll make it happen

**Comment by PKPenguin321** [comment]
Feature request close please

**Comment by GunHog** [comment]
Why would you be against such a feature, PKP?

**Comment by PKPenguin321** [comment]
I'm not but it's a feature request that doesn't belong in the issues section

**Comment by TechnoAlchemisto** [comment]
#19614
