### ISSUE TITLE
Keanu Hair Style missing; Can't get the bradberry look

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#19550]
[Note]: The character preferences hairstyle picker is missing the keanu hairstyle, which i have used to get the perfect 'Ethan Bradberry' look for my character. 

[Admins]: i am not an admin.

![image](https://cloud.githubusercontent.com/assets/7098330/17206073/d8e21ef0-5462-11e6-85d1-eaef2d6718bd.png)

**Comment by Iamgoofball** [comment]
what the fuck is that font size

**Comment by Tacolizard** [comment]
ok i'd appreciate it if you weren't so rude but listen buckaroo, I have a high DPI monitor so my default font size is tiny, fucker, thanks!

**Comment by francinum** [comment]
But still that's massively overkill.

**Comment by PKPenguin321** [comment]
Is this a feature request

**Comment by TechnoAlchemisto** [comment]
no keanu is a hair style that definitely existed

**Comment by Iamgoofball** [comment]
Yeah, I added it with all those hairstyles way back when. Someone git blame the file

**Comment by bgobandit** [comment]
keanu hair is still in there, close this
