### ISSUE TITLE
contents may have shifted during flight

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#19562]
![ss 2016-07-28 at 05 38 15](https://cloud.githubusercontent.com/assets/6510293/17231874/25adf59c-54ea-11e6-8028-cc7ea36a615f.png)

the tools are like moved over something to do with atmos prolly

**Comment by Bawhoppen** [comment]
This appears to have happened on very specific circumstances, as on a fresh round it didn't happen.

**Comment by Bawhoppen** [comment]
ah found out the cause

**Comment by Jordie0608** [comment]
Was it that someone moved them.

**Comment by Bawhoppen** [comment]
It was all 4 ayylien pods, 
I don't know the exact cause but there was all sorts of shenaniganery on z2 at the time involving VR sleepers and explosions so it somehow affected them I guess
