### ISSUE TITLE
Character Creation Screen Issues

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#19567]
![untitled2](https://cloud.githubusercontent.com/assets/8237862/17252301/34787080-557a-11e6-88df-76bdd9239f9e.jpg)
![untitled](https://cloud.githubusercontent.com/assets/8237862/17252306/369b6b24-557a-11e6-90a8-13f2af0313dc.jpg)
It appears that the front-facing sprite is displayed on all three pictures, which creates the eyes-in-the-back-of-the-head effect.

**Comment by Cruix** [comment]
This is my fault. Getflaticon detects that the eye icon is blank for some directions, and displays the south icon instead. Revert #19504 to fix this.

It seems photography will remain broken until Lummox adds a built in getflaticon.
