### ISSUE TITLE
C4 falling off tails

### ISSUE THREAD

**Issue by DfourC** [tgstation/tgstation#19570]
If you surgically remove a lizard's tail, attach C4 to it, then reattach the tail surgically, the C4 vanishes from the world completely and the tail sprite doesn't reappear on the lizard. The tail DOES reattach, and can be removed again surgically. If you do this, you can see the C4 has certainly vanished from the tail.

**Comment by MMMiracles** [comment]
Less of the C4 falling off and more of the fact tail attachment just modifies the target's appearance to appropriately visualize the tail and deletes the severed tail item.

**Comment by Detective-Google** [comment]
Still happens, however the tail is removed (aka the tail is being exploded and destroyed, without an actual explosion)

**Comment by nightred** [comment]
Items are being moved to null space not in to body.
