### ISSUE TITLE
Client crashes due to certain menus

### ISSUE THREAD

**Issue by Beezbrax** [tgstation/tgstation#19571]
This is an issue I've only experienced so far with /tg/ code. Upon opening certain menus, such as the cargo shuttle menu and others like it, the game will freeze for a second before crashing. My BYOND is updated to the most recent version and have tried clearing the cache but neither seem to make a difference.

**Comment by Jalleo** [comment]
What OS and version of IE do you have?

**Comment by Beezbrax** [comment]
The OS is Windows 8.1 64 bit, and by IE I assume you mean Internet Explorer, the version for that is 11.0.9600.16384

**Comment by Jalleo** [comment]
@optimumtact I believe you know who to ask to tryand work out where the problem is.

**Comment by Robustitron** [comment]
I've been having this problem too since yesterday, and people occasionally complain in ooc about it, it's especially bad with the r&d console.
