### ISSUE TITLE
Photocopier not copying correctly and eating the original

### ISSUE THREAD

**Issue by BananaSenor** [tgstation/tgstation#19596]
Currently very hard to properly play HoP, if you copy a paper with writing on it, the copied paper will use the blank sprite, not the one with lines on it (The text itself is copied properly, though, just the sprite thats wrong).

Also, the photocopier doesn't give back the original paper when pressing "eject paper". It seems to eat it. This is too close to real life and potentially triggering.

**Comment by ModernViolence** [comment]
Currently you can take out the original paper by dragging sprite of your character on photocopier.
