### ISSUE TITLE
Leg layering is fucked up

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#19598]
![oh boy unfixable bugs](http://puu.sh/qk2QD/89854517c0.png)
Top row is left leg removed, middle row is right leg removed, bottom row has both legs.

You'll notice that bottom right's leg looks like it's the left leg and that's because it's the left leg, even though that mob is facing to the right.

###### fun with unfixable layering bugs unless we redo icons every time a human changes dir

**Comment by xxalpha** [comment]
>fun with unfixable layering bugs unless we redo icons every time a human changes dir

what why who when

**Comment by RemieRichards** [comment]
That's not such a terrible thing to do anymore, it's just taking some images out of overlays, redoing their layers based on dir (all of this would be happening in ```setDir()``` btw) and putting them back in.
with legs that's only 2 images.
