### ISSUE TITLE
Drones are not shock proof (anymore?).

### ISSUE THREAD

**Issue by fizbump** [tgstation/tgstation#19604]
Server: Sybil

Revision: "Server revision compiled on: 2016-07-31
Test merge active of PR #19602 
Based off master commit b01460c2bfff1459e5f4c192143c5767ed648924 "

Problem Description: Drones are apparently not shockproof anymore. Shocks from a single APC short or shocked door instakill drones. They WERE shockproof before, right?

What did you expect to happen: I expected that drones would be immune to shocks, as it would severely cripple their ability to fix, maintain and improve the station were they not.

What happened instead: I got shocked and died. Several times.

Why is this bad/What are the consequences: While drones are not the most important of player controlled characters, it is a bit annoying having the looming prospect of instant death hanging over you should you try to fix any power issues.

Steps to reproduce the problem: Observed a round, saw a drone shell become available, and occupied it. Power was out in a number of places and I determined it was from someone cutting the wires. I began to repair APCs. I successfully repaired several APCs up until the Kitchen APC shocked me and insta-killed me. I respawned as a new drone, went to fix TCOMMS, got shockd by the door and died instantly. I then tested all three drone types on an APC and found that none of them had any kind of shock resistance.

Possibly related stuff (which gamemode was it? It was a standard traitor round with the AI as a traitor. Not sure if the AI can set up APCs to kill drones but that would be a bit silly. It's most likely that someone made drones and other npcs susceptible to shocks so that the Tesla can harm them, but didn't realize that they were making drones open to shocks from station equipment.

**Comment by GunHog** [comment]
This is caused by https://github.com/tgstation/tgstation/pull/19556.

**Comment by Robustitron** [comment]
Staple insulated gloves to their drone hands.

**Comment by Jalleo** [comment]
@korphaeron

**Comment by fizbump** [comment]
https://github.com/tgstation/tgstation/pull/19606
Already fixeroni'd
