### ISSUE TITLE
Theremite overlay has MAP on it.

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#19612]
![dreamseeker_2016-07-31_20-19-48](https://cloud.githubusercontent.com/assets/4047233/17278376/5e748908-575c-11e6-8d44-12957d24559c.png)

What it says on the tin.

**Comment by Bawhoppen** [comment]
ah thats interesting, its because the shuttle walls before they smooth have the map texture because there needs to be some level of transparency in order to place above another turf, so thermite must do some real fiddly business with how the sprites work for it

**Comment by ChangelingRain** [comment]
They smooth they don't need transparency(and I removed it from the sprites!)

**Comment by Bawhoppen** [comment]
if you are placing it over another turf they do

**Comment by ChangelingRain** [comment]
That literally doesn't do anything if they're not diagonal, and if they're diagonal they're using some other turf's underlay!!!

**Comment by Bawhoppen** [comment]
it should be taking the one under it for diagonals though
