### ISSUE TITLE
Engineering Engine Room Airlocks to Space are Terrible at Locking Air

### ISSUE THREAD

**Issue by C0NTR** [tgstation/tgstation#19623]
The airlocks from inside the engine room to outside where the generator is housed are constantly allowing copious amounts of atmosphere to leave the station, along with whatever else may currently be within ~20 feet of the airlock. It makes it difficult to regulate the atmosphere inside the station, and it also makes it next-to-impossible to transport large items inside (i.e.: singulo generator, when one is making a tesla) without decompressing most of the room. Is there a way to make these airlocks act like proper airlocks and keep the air indoors?

**Comment by callanrocks** [comment]
There used to be proper airlock airlocks but they broke all the time.

**Comment by xxalpha** [comment]
MSO added his new airlocks to boxstation, are these not working?

**Comment by AnturK** [comment]
Might be on metastation ? Only box got these and i'm not sure if MSO replaced engine ones.

**Comment by Hatfish** [comment]
The same thing happens with the mining shuttle airlocks as well, everything in the mining office will get sucked out into space after the first few trips to and from the station.

**Comment by xxalpha** [comment]
Specify maps.

**Comment by Hatfish** [comment]
I've seen both happen on box, meta, and dream within the past week.

**Comment by Kromgar** [comment]
Could we not just install those little fans that keep in air in those airlocks? They have them in the mining pods

**Comment by MrStonedOne** [comment]
those tiny fans don't actually keep air in, they block atmos movements.

actual tiny fans to keep air in could be useful.

**Comment by WJohn** [comment]
Tiny fans also quite heavily break realism when you just put one in the doorway and it utterly prevents venting things to space. I guess it's more acceptable in engineering where engineers exit and enter through there constantly with a near express purpose of reaching the engine, but still.

**Comment by Cyberboss** [comment]
Wasn't this fixed? With that cyclelinked airlock pr?

**Comment by WJohn** [comment]
As stated above, those are not enough to prevent a couple of tiles from getting completely vented to space, and then those two vacuum'd tiles sucking in everything from engineering. Since people pass through these friggin constantly, you nearly always have two tiles sucking up air.

**Comment by Cyberboss** [comment]
Set the lockers to anchored.
