### ISSUE TITLE
new powergame technique for lavaland

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#19628]
Apparently keeping your hood down is the new powergame strat, cause mobs never attack your head, but you can vent the watcher's cooldown or whatever I don't really know exactly, but we should fix it

**Comment by Darkgenerallord** [comment]
This isn't really an issue with anything other than simplemobs. For some reason they only attack everything except your head. The rest is an intended thing as far as I'm aware.

**Comment by Bawhoppen** [comment]
the fact its optimal to not have your hood on to be more immune to watchers is dumb

**Comment by TechnoAlchemisto** [comment]
How would that make you immune to watchers

**Comment by Bawhoppen** [comment]
because the like air temp around you heats your head or some shit, I don't know how it works but thats what everyones doing now and thats the reason they gave

**Comment by Darkgenerallord** [comment]
How it works is you heat up from cold, but it's slowed by insulating clothing. By removing the insulation from the hood, you're less insulated, so you heat up faster. It's enough that you don't go to red from a single watcher beam, but it's nothing absurd.

**Comment by Kromgar** [comment]
Yeah but if you get set on fire the hood protection wont help meaning you will die of temp damage

**Comment by Darkgenerallord** [comment]
It is a fair sacrifice.

**Comment by optimumtact** [comment]
this isn't a bug
