### ISSUE TITLE
Cyborgs can be devil agents

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#19627]
Ran a round of devil agents and a roundstart borg was picked as a devil.
@lordpidey

**Comment by lordpidey** [comment]
Welcome to robot hell.

**Comment by lordpidey** [comment]
Seriously though, that's unintended, but I think it might be worth keeping in.  Did it work properly?

Did they have spells and were able to cast?
Did they have a zeroth law?

**Comment by GeneralGoose** [comment]
**feature**

**Comment by Shadowlight213** [comment]
@lordpidey no zeroth law. they were asimov.
Not sure about the spells but maybe.

**Comment by lordpidey** [comment]
Okay, cyborgs being devils is unintended, but hilarious, and deserves to stay, but them not having a zeroth law is a problem.

**Comment by Shadowlight213** [comment]
@lordpidey there's also going to be issues in regards to resurrection and blood lizard/true devil stuff probably.
I haven't tested that, but you'll definitely need to make sure they don't get screwed.

**Comment by lordpidey** [comment]
The transformation to blood lizard SHOULD already be handled, if somehow the devil wasn't humanoid, it would simply change color.  I'll have to test resurrection, it might work, it might not.

Either way, I'll test all of that, make sure it doesn't explode or something.
