### ISSUE TITLE
Strange issues with attempting to copy station blueprints.

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#19624]
It's worth noting that the blueprints can't be put onto the photocopier, which is annoying, but there's a slightly more jarring issue in which taking a photograph of the blueprints won't show the blueprints in the picture.

This is especially annoying as I'm given to understand that this was supposed to be one of the methods by which a traitor could complete their "steal a copy of the station blueprints" objective.

**Comment by xxalpha** [comment]
Does it not count for objective?

**Comment by AnonymousNow** [comment]
I don't know whether one of these glitched photos can count; I didn't have the means to test it. I'd guess not, seeing as though the blueprint sprite physically wasn't appearing in the picture.

**Comment by ModernViolence** [comment]
1. `p.blueprints = photocopy.blueprints //a copy of a picture is still good enough for the syndicate`
According to code, blueprints could be copied in the past. Definately a bug.

2. Glitched photo of blueprints could be another, separated bug.

**Comment by MrStonedOne** [comment]
>I don't know whether one of these glitched photos can count;
You can check by just taking a picture, and checking for the blueprint var on the picture, can't remember what it's called but you should see it in vv if you look.

**Comment by MrStonedOne** [comment]
or ask an admin to check if your on one of the game servers.

**Comment by ModernViolence** [comment]
I've checked locally , that photographs of blueprints:
1. Have blueprints visible
2. Have "blueprints" variable set as 1
3. Copies of photos of blueprints also have this flag.
4. Are counted as success in "steal blueprints" missions if traitor has them by the end of round.

Next, photocopies of blueprints.
1. Blueprints are not insertable into photocopier.
2. If 1. is fixed, blueprint copying is still not implemented in game. Currently photocopier produces blank photo with "blueprint" variable = 0.

Ways to solve:
1. Forbidding inserting of blueprints into copier with message, like, "Blueprints are too large for the photocopier. Consider finding another way of <s>stealing</s>copying this confidential data"
2. Implementing /obj/item/areaeditor/blueprints/photocopy (like /obj/item/documents/photocopy).
This would require adding several if's to photocopier code, and deciding whether copy of blueprints should have the ability to rename areas.

**Comment by AnonymousNow** [comment]
When I took the photographs, they were sitting on the detective's desk, and the other objects on the table appeared just fine. I'll see if I can recreate the issue, else it's just another bug I've run into facefirst.

**Comment by PKPenguin321** [comment]
ModernViolence's comment seems to indicate that this is not a bug as it works as intended.
