### ISSUE TITLE
Engineering Storage Field Generator Problem

### ISSUE THREAD

**Issue by Groxic** [tgstation/tgstation#19643]
The field generators in engineering storage can be moved around, but they are supposedly already welded an wrenched to the floor. If you want to make them unmovable, you'd have to un-weld them, un-wrench them, wrench them again, and then re-weld them.

**Comment by Jalleo** [comment]
Which station is this?

**Comment by Groxic** [comment]
Metastation

**Comment by optimumtact** [comment]
Probably incorrectly set welded/anchored vars.

**Comment by WJohn** [comment]
They're unwrenched and unanchored from what I've seen, so I'll assume meta fixed this.
