### ISSUE TITLE
The Phantom Ore

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#19664]
![image](https://cloud.githubusercontent.com/assets/6778786/17349012/a23b199e-58e8-11e6-960f-62a4dbe72d1c.png)

Kept getting alerts of minerals in cargo.

I'm guessing this is because free golem ship bullshit or something

**Comment by optimumtact** [comment]
it's because someone was withdrawing glass.

**Comment by Kromgar** [comment]
Yeah interesting thing about that is that I NEVER SAW ANY ORE.

Everytime i went to the machine there was 0 ore ever and robotics didnt have any ore either where did the ore go?

**Comment by optimumtact** [comment]
Oh hmm, that is strange.

**Comment by XDTM** [comment]
Golem ship ORM sends a message to science consoles like a normal one, the "in the cargo bay" text is just hardcoded

**Comment by optimumtact** [comment]
Smart, obviously needs some concept of channels.
