### ISSUE TITLE
Someone missing both legs can't hold items at all

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#19700]
This is dumb, you should at least be able to HOLD items, if not necessarily move holding them.

**Comment by anconfuzedrock** [comment]
you can still fucking hold dicks if you buckle yourself into a chair get a wheelchair aka scooter you fat fuck

**Comment by phil235** [comment]
For balance reason: unbuckled legless humans are always prone and can move, which gives a huge advantage in firefights if we allow them to hold items.

**Comment by ChangelingRain** [comment]
Maybe give them slowdown based on the item's w_class, then.
being unable to HOLD ITEMS IN YOUR HANDS because you HAVE NO LEGS is idiotic.

**Comment by anconfuzedrock** [comment]
they are already slow as fuck and if you pick up an item and unbuckle from the chair you are still holding it

**Comment by Shadowlight213** [comment]
That would require making everyone able to hold stuff while prone.
I mean, all you have to do is not be prone while legless and you'll be fine.

**Comment by XDTM** [comment]
@AnturK fixed
