### ISSUE TITLE
Three-Tile Graffiti Visibility Problem

### ISSUE THREAD

**Issue by Twentytwo22** [tgstation/tgstation#19705]
It seems the three tile long runes are able to be seen through non-glass airlocks from the left side while being completely invisible on the right when placed under an airlock.

I would imagine that the half that should logically be visible should indeed be visible when looking at it from any angle.

The consequences are merely aesthetic and does not have a large impact, although I still believe this is not what was intended.

I was able to recreate this on multiple occasions, as seen in the pictures below.

This all happened on Basil, Server revision compiled on: 2016-08-01
407a2d568bd27dd5d5f57b682c5977bc7b08e249.

This was able to be reproduced when other players had drawn the runes too.

![tgstation bagil english 100 free lag mining drydock lambda 2016-08-04 144137](https://cloud.githubusercontent.com/assets/5247878/17419379/02bbbafc-5a52-11e6-8656-df21cfc7be49.png)

![tgstation bagil english 100 free lag mining drydock lambda 2016-08-04 145134](https://cloud.githubusercontent.com/assets/5247878/17419618/1b326a9e-5a53-11e6-8da8-66c45a73c27b.png)

![tgstation bagil english 100 free lag mining drydock lambda 2016-08-04 145220](https://cloud.githubusercontent.com/assets/5247878/17419614/1123dda8-5a53-11e6-9f2b-3bda3aee5458.png)

![tgstation bagil english 100 free lag mining drydock lambda 2016-08-04 144641](https://cloud.githubusercontent.com/assets/5247878/17419461/661be9fa-5a52-11e6-926a-4f8ef0195a0e.png)

**Comment by KorPhaeron** [comment]
@xxalpha 

Would it be insane to split this into 3 objects,and have the middle piece automatically spawn the two side pieces on creation?

**Comment by xxalpha** [comment]
This is a byond bug, but we can get around it by doing what Kor suggested. I had thought of doing it at the time but for some reason I didn't, but now I can't remember of anything that would prevent doing it.

**Comment by Detective-Google** [comment]
![image](https://user-images.githubusercontent.com/48196179/64509581-aae3bf80-d2a5-11e9-940b-0d366bbc8da0.png)
![image](https://user-images.githubusercontent.com/48196179/64509597-b0410a00-d2a5-11e9-89d8-07454f783c67.png)
no longer an issue
