### ISSUE TITLE
MiniStation Telecom

### ISSUE THREAD

**Issue by vernillet** [tgstation/tgstation#19719]
Hello, I have actually encountered a bug with Ministation, the telecom doesn't work anymore and the computers can't find the server for PDA and radio.

A french player with the SCP french section.

**Comment by Bawhoppen** [comment]
oh yea I think I accidentally removed them when I was trying to get it to compile, not much lost but we can readd them easily

**Comment by vernillet** [comment]
So... there is a way to easly put it back or i have to wait until is corrected ?

**Comment by Bawhoppen** [comment]
yes we can fix it I will one minute
