### ISSUE TITLE
Problem with Telekinesis

### ISSUE THREAD

**Issue by wavesuponwaves** [tgstation/tgstation#19711]
When using telekinesis, if you switch hands while holding an object, it breaks one of your hands and you can no longer pick things up using that hand.

**Comment by phil235** [comment]
the empty hand is actually full, it's holding the swapped tk grab. You can clear the hand by dropping the grab.

**Comment by XDTM** [comment]
Not a bug?

**Comment by phil235** [comment]
Definitely a bug. Switching the tk grab from one hand to another need to be fixed.
