### ISSUE TITLE
Tele-Gulag removes Plasmamen suits/internals

### ISSUE THREAD

**Issue by Falamazeer** [tgstation/tgstation#19724]
The telegulag is pretty much a very exciting execution chamber for plasma people, you are teleported in, and immediately combust in the atmosphere, meanwhile you suffocate to death because there is no plasma tanks available anywhere in the vicinity, which of course is the least of your worries.

**Comment by TechnoAlchemisto** [comment]
natural selection

**Comment by evsey9** [comment]
feature

**Comment by Falamazeer** [comment]
It really shouldn't be, the space resistance is seemingly gone from their special suits already, and the gulag sends them to Lavaland where they take double damage from fire already.

the least you could do is let the poor little bastards try to meet their goals.
because at this point there is no benefit to being a plasmaman, and many many negatives.
-double damage from burns.
-catch fire by default leading to burns
-can't wear internals in pocket. why? cause fuck you that's why.
-double damage in space, because burn damage (Seemingly)
-Non human to silicons
-Non human for head positions
-Can't be gulagged without die-ing by default


Just a little love is all I'm asking. their jumpsuits are already orange so why not?

**Comment by Falamazeer** [comment]
Oh, and it's difficult to clone a plasmaman, or at least slightly more inconveiniant so nobody does it.
and cryo kills you even better than telegulag at last check.

all those negatives are features, fine, I can accept that price, but the telegulag being a murdermachine? c'mon man.

**Comment by lzimann** [comment]
This got fixed in #19821

**Comment by XDTM** [comment]
Close this if fixed
