### ISSUE TITLE
30 second rev rounds

### ISSUE THREAD

**Issue by Thunder12345** [tgstation/tgstation#19734]
>Round starts
>It's rev
>Captain is only head
>Captain opens locker
>Captain steps in locker
>Captain closes locker
>YOU HAVE SURVIVED THE EVENTS OF SPEEDRUN STATION 13

**Comment by DfourC** [comment]
Don't do that then.

**Comment by Thunder12345** [comment]
Yeah but if the completely unaware captain closes himself in his locker for a second, and happens to be the only head, the round just... ends

**Comment by DfourC** [comment]
Don't do that then.

**Comment by Thunder12345** [comment]
Don't walk into a closet on the off chance it's rev and the round will end instantly?

Also, 1 revhead, 1 head, revhead walks up to head without ever flashing anyone, pulls closet over them, closes

**Comment by RemieRichards** [comment]
it shouldn't even end, both Revs and Heads have their turf's Z checked, so entering a locker shouldn't be counting as leaving the Z.

**Comment by AnturK** [comment]
More likely is the Captain went into closet to go AFK for a moment.

**Comment by YakumoChen** [comment]
Honestly I don't even know why rev rounds can have less then two heads of staff in the first place, I'm frequently forced into head position (I have most of them on medium) when rev comes up.

**Comment by Jalleo** [comment]
This is a reverse of the old issue of leaders on both sides hiding in lockers. No easy solution. Apart from maybe starting the check 5 mins in?

**Comment by callanrocks** [comment]
Get rid of the check and make it ping admins to yell at them?

**Comment by optimumtact** [comment]
Relies on admins being online.

**Comment by kevinz000** [comment]
NOT AN ISSUE

**Comment by kevinz000** [comment]
@lzimann

**Comment by PKPenguin321** [comment]
It actually is an issue though
