### ISSUE TITLE
Cyborgs getting shocked by electricity (wires and grilles). Unconnected wires generating 'shock' messages.

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#19731]
I have been getting reports as AI of borgs taking burn damage (which is notoriously hard to fix) by running into electrified grilles, as well as getting shocked by laying down cable coil in the power grid. Borgs are supposed to be insulated to these things, and burn damage is rare and hard to fix, it makes playing unreasonably difficult (especially as engi borg when doing station repairs does burn damage for no reason).

Related, but I am also getting shocked as a cyborg setting down single cable coils, unconnected to anything.

**Comment by YakumoChen** [comment]
![untitled2](https://cloud.githubusercontent.com/assets/10399117/17455992/d362e848-5b96-11e6-9158-c19f6fafffc8.png)

**Comment by xxalpha** [comment]
Why is this even a thing?

**Comment by Boggart** [comment]
I have been shocked and received damage while wiring as an engiborg but couldn't reproduce it on the testing server and running into a shocked grille as a borg can result in death very quickly as you don't get stunned.

**Comment by kevinz000** [comment]
No longer happening.

**Comment by kevinz000** [comment]
@lzimann
