### ISSUE TITLE
Hotel security jumpsuit missing a sprite

### ISSUE THREAD

**Issue by DfourC** [tgstation/tgstation#19733]
The jumpsuit worn when you come out of the hotel security sleeper can be alt-clicked to be work casually, but doesn't have a casual sprite.

![kindergarten phi mmcv 2016-08-06 145703](https://cloud.githubusercontent.com/assets/20377602/17457162/3b8979f0-5be7-11e6-9bf0-931da0dfa309.png)

**Comment by stew9703** [comment]
well thats as casual as it gets dont you think?
