### ISSUE TITLE
you can't use slime fireproofing potions on suits with pockets

### ISSUE THREAD

**Issue by XDTM** [tgstation/tgstation#19749]
It'll just put the potion in the pocket.

**Comment by KorPhaeron** [comment]
@Core0verload

**Comment by Bawhoppen** [comment]
the pockets are real buggy and annoying sometimes, you also should be able to use internals from them

**Comment by Core0verload** [comment]
Pockets mimic behavior of storage items because they are storage items. That's why you can't use internals and such.

**Comment by Bawhoppen** [comment]
yes I know why but they should be given snowflake ability to
