### ISSUE TITLE
Supermatter induced singulo hallucination locks up dreamseeker.

### ISSUE THREAD

**Issue by Boggart** [tgstation/tgstation#19747]
When the fake singularity touched my mob, I went into fake crit and dreemseeker instantly froze. The only way to recover was to force close dreamseeker.

Byond 511.1351, Sybil.
Happened to myself, Gamarr and Vexint. (Happened to Vexint while he was running from it.)

**Comment by Alek2ander** [comment]
Probably caused by hallucination in general, I've seen reports of client freezes after ling hallucination stings

**Comment by Buggy123** [comment]
Hippystation fixed it by removing the singularity hallucination: https://github.com/HippieStationArchive/HippieStation13-2/pull/352

**Comment by Cyberboss** [comment]
@XDTM any ideas?

**Comment by XDTM** [comment]
We should see if the latest rework fixed it, datumizing the hallucinations has to be better than invisible objects.

My second theory is that client += image has a chance of causing issues.

**Comment by XDTM** [comment]
Singulo hallucination no longer exists, close at will
