### ISSUE TITLE
The bartenders soda/alcohol dispenser tgui wackyness.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#19745]
It turns out my original report was fake and gay.

The dispenser can't support having the dispense amount listed on both of them at the same time. So if you open the alcohol one, then open the soda dispenser the amount option will not appear on the soda dispenser.

**Comment by phil235** [comment]
cannot reproduce.

**Comment by Buggy123** [comment]
Couldn't be reproduced, stale, no further reports etc. Can probably close this.
