### ISSUE TITLE
Space Ruins Spawning On Top Of Each Other

### ISSUE THREAD

**Issue by Cheridan** [tgstation/tgstation#19768]
![srb33nx](https://cloud.githubusercontent.com/assets/3827314/17476432/a143d260-5d25-11e6-8e76-16050cae14fc.png)

Ahhhhhhhh

**Comment by Durkel** [comment]
It's fine, the buses crashed into the building, that's how everyone died obviously.

**Comment by Jalleo** [comment]
Top kek.
