### ISSUE TITLE
Plasmamen in hardsuits/firesuits stay on fire forever.

### ISSUE THREAD

**Issue by Falamazeer** [tgstation/tgstation#19774]
Even when sealed with the helmet.
even when extinguished with a fire extinguisher
shower stops it, for like.. 30 seconds or less.

Everywhere but space you stay on fire, I'm guessing because if you're wearing the hardsuit helmet you aren't wearing your plasmaman mask.

**Comment by francinum** [comment]
Yeah, it's snowflakey as fuck.

**Comment by Falamazeer** [comment]
Pretty sure it's a bug, As it makes no sense at all, the atmosphere should be sealed from you in a sealed hardsuit or it wouldn't be space worthy.

**Comment by Jalleo** [comment]
Normal firesuits it makes sense for. Spacesuits it dosent make sense.

**Comment by Falamazeer** [comment]
Also, does something similar with regular EVA suits, but the damage also kills you.
again cannot be put out unless you're in space. and it re-ignites and kills you on station

**Comment by phil235** [comment]
I don't understand the issue, do you mean when the plasmaman is not wearing its plasmaman jumpsuit and plasmaman helmet?

**Comment by francinum** [comment]
Wasn't this back when they were exosuits instead of jumpers.
