### ISSUE TITLE
Cult floors are affected by space wind and stashable in crates and lockers.

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#19792]
Any kind of depressurization makes cult floors move, closing a crate above the cult floor makes it vanish, stashed inside the crate, revealing plating.

**Comment by MrStonedOne** [comment]
wot.... how.... but... aren't cult floors turfs,

**Comment by xxalpha** [comment]
Duplicate / same as #19723?

**Comment by WJohn** [comment]
I tried spawning cult floors on existing floors (spawn command) and while it SAYS it's an engraved floor, it still looks like regular flooring. Tried spawning it on plating, same results, just looks like plasteel.
