### ISSUE TITLE
The new Virus Chems are unmakeable

### ISSUE THREAD

**Issue by XDTM** [tgstation/tgstation#19797]
Their recipes are there, but the reagents themselves are never defined, so when the reaction happens it results in nothing. As an added note, the recipe for Stable Uranium Gel conflicts with Unstable Uranium Gel (5 uranium + 1 virus plasma; 10 uranium + 10 silver + 1 virus plasma respectively).

**Comment by KorPhaeron** [comment]
@LanCartwright

**Comment by LanCartwright** [comment]
woah my apologies, i'll fix it now.

**Comment by LanCartwright** [comment]
its fixed
