### ISSUE TITLE
Pixel projectile paths are broken

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#19801]
If you take a projectile and set it up to fire at the turf to its left, its path will eventually(within about 15 tiles) move it a tile down, even though you fired it directly at the turf to its left.

This happens to some extent with other directions, but left is the most immediately obvious one.

**Comment by Jalleo** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
@KorPhaeron

**Comment by kevinz000** [comment]
@KorPhaeron

**Comment by kevinz000** [comment]
still an issue

**Comment by ChangelingRain** [comment]
not an issue anymore something fixed it
