### ISSUE TITLE
Broken Wizard spell

### ISSUE THREAD

**Issue by Lexorion** [tgstation/tgstation#19824]
Spacetime Distortion spell can have a 0 second cooldown and spamming it (using it 2+ times) causes the distortion to stay forever.The spell tab allows you to spam it,while the button in the top left corner is red and unclickable. You can reproduce this by upgrading the spell to Instant,just keep casting it.
![bug](https://cloud.githubusercontent.com/assets/13591098/17597417/f58c62ba-5ff5-11e6-9873-d87ba354ab96.png)

**Comment by KorPhaeron** [comment]
@xxalpha

**Comment by PKPenguin321** [comment]
lmao

**Comment by xxalpha** [comment]
This is more of a spell code bug.

**Comment by xxalpha** [comment]
Working as intended? :clock1:
