### ISSUE TITLE
[Critical] Turf's Destroy is Never called

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#19834]
This is pretty critical of a problem. Basically, turfs are almost never directly deleted or `qdel`'d--new turfs are just made with `ChangeTurf`, which creates a new turf on top of the old one.

The big problem with this, though is that any turf `Destroy` is never called, because of this, resulting in something like this:

![img](https://i.gyazo.com/c5447fe15e01e552efe3335c7d6d4e88.png)

Utilized an RCD on the floor and stepped away; it's been like this for 5+ minutes with no air moving. 

This has nasty implications as anything that's reliant on `turf/Destroy` (or children) is neverrrr being called.

**Comment by PKPenguin321** [comment]
ohhhh that's why when i tore a hole in the floor with the RCD as a traitor one time it didnt start stucking people in like i intended

**Comment by AnturK** [comment]
I'm confused how this gone unnoticed during last changeturf changes

**Comment by xxalpha** [comment]
It used to trigger atmospheric update in /turf/proc/ChangeTurf() but maybe it was changed with dunc's refactor.

**Comment by optimumtact** [comment]
turfs not being deleted is a byond optimisation, but we do need to trigger a linda update when they're changeTurfed.

**Comment by Fox-McCloud** [comment]
@optimumtact 

There's plenty of other things in various turf `Destroy`'s which never gets called, as well, which is problematic.

**Comment by optimumtact** [comment]
That is a good point.

**Comment by Fox-McCloud** [comment]
https://github.com/tgstation/tgstation/blob/bd61b3cb68c422e95219638d134bc87b2aae63c9/code/game/turfs/simulated/walls_misc.dm#L63
https://github.com/tgstation/tgstation/blob/5a2c13ad0d2f5b602e528364c99b10701ce0fd59/code/game/turfs/simulated/floor/plating.dm#L162
https://github.com/tgstation/tgstation/blob/1bd74a3d19c216ae038ef95f30e4b2591ca22698/code/game/turfs/turf.dm#L39
https://github.com/tgstation/tgstation/blob/7a05f7b033cbf359517e3808e8134c7543aef373/code/game/turfs/simulated/floor/misc_floor.dm#L20
https://github.com/tgstation/tgstation/blob/c57deb8fbae750fd87ec01aad2dd8560e5cc412d/code/modules/atmospherics/environmental/LINDA_turf_tile.dm#L44

I'm not sure if there's any others, but these are all the turf `Destroy`'s I could find

**Comment by xxalpha** [comment]
Couldn't we just call it in ChangeTurf?

**Comment by Fox-McCloud** [comment]
@xxalpha 

Yeah, though `Destroy` typically isn't meant to be called outside of qdel or pooling, but...in this case, it may be best.
