### ISSUE TITLE
Emergency Firesuits make you space immune?

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#19835]
![image](https://cloud.githubusercontent.com/assets/6778786/17609964/afaf3e0e-6007-11e6-8a5d-245233ede0a4.png)

**Comment by Kromgar** [comment]
He had been fighting like that for 5 minutes

**Comment by PKPenguin321** [comment]
it makes you pressure immune but eventually youll freeze to death. he may have applied a burn patch before going EVA.

likely not a bug

**Comment by Shadowlight213** [comment]
Emergency firesuit + core is ghetto spacesuit

**Comment by Kromgar** [comment]
Why would you be pressure immune its a firemans suit it doesnt even a self sealing hood thing

**Comment by PKPenguin321** [comment]
feedback forum
