### ISSUE TITLE
Commiting suicide with an tank while wearing explorer's suit and hood, causes hood to drop as an item.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#19832]
Commiting suicide with an oxygen tank while wearing an explorer's suit and hood causes the hood to drop sometimes. Anyone can pick up said hood and have it stuck to them.

What did you expect to happen: The hood to retract back to it's suit.

What happened instead: The hood dropped as an item, can't get rid of it if you pick it up. Seems like if you pick up the suit, the hood goes back to it. However, the hood got absolutely stuck to me on Sybil.

Why is this bad/What are the consequences: Not able to wear other helmets or use a hand is pretty bad.

Steps to reproduce the problem: Have one person commit suicide using any tank while wearing an explorer's suit and hood on, the "explosion" should knock off the suit and the hood, may require a couple of tries.

Server: Sybil

Revision: Server revision compiled on: 2016-08-11

**Comment by lzimann** [comment]
I think this is an old issue with NODROP items being forced to drop with the suicide, I remember seeing a fix for it a few months ago though

**Comment by Mervill** [comment]
Related #18601
