### ISSUE TITLE
ListTargets is Incredibly Expensive

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#19855]
Not too hard to see this; just profile the server--it's outpacing nearly everything, up to, and including LINDA.

Source is likely the 150+ hostile mobs on lavaland.

Server CPU, at rest is 16-25, but is typically 40-50 because of this proc, alone (or rather it being called so much).

**Comment by MrStonedOne** [comment]
ya, its been on my list to look at, today seems as good as any I guess.

**Comment by MrStonedOne** [comment]
Found it out, it's the stupid snowflake for mechs and turrets.

I'm testing 9 variations of the proc, (by making 9 versions of the proc, then making the original randomly call 1 of them, so I can see all of the profiles at once getting a good sampling of real world usage for each) so far i have it down to 1/10 of the original cost.
