### ISSUE TITLE
You can scan in multiple autocloners at once

### ISSUE THREAD

**Issue by imtakingabreakdontatme** [tgstation/tgstation#19862]
If you scan yourself in two cloners, they will both attempt to clone you, causing two clones to get spawned (and your mind forcibly moved from the first one to spawn to the second).

That's the message I got on BYOND anyway, didn't see it myself

**Comment by Kromgar** [comment]
Incredible. So uh also if your a changeling and you regenerate you get cloned

**Comment by Jalleo** [comment]
But if you get shaded you wont be moved over.

**Comment by callanrocks** [comment]
Autocloners will pull you out of MMIs in some cases now.

**Comment by YakumoChen** [comment]
Wait, I thought that cloners were supposed to only clone one at a time, in the order you got scanned in, not all at once.

**Comment by YPOQ** [comment]
I don't think this should happen anymore now that cloners move the mind at the start of the cloning process rather than the end.

**Comment by ShizCalev** [comment]
Still an issue? Will close in a week without further report.

**Comment by KorPhaeron** [comment]
It is yeah

**Comment by kriskog** [comment]
Autocloning is gone, both scanning and starting cloning now requires the mind to be associated with the old body. This shouldn't happen anymore.
