### ISSUE TITLE
Revenants completely broken

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#19861]
Using the create antagonist button does nothing
Triggering the event does nothing
Forcing the revenant to spawn using ectoplasm creates a revenant that is invisible to even ghosts.

**Comment by callanrocks** [comment]
Didn't they remove revenant?

**Comment by Shadowlight213** [comment]
Not that I can tell.
All the related buttons, items, spells, and the mob still exist.
It may have been made admin only.

**Comment by X-TheDark** [comment]
Should have been fixed by #19884
