### ISSUE TITLE
Ordinary Space Tile Issue

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#19867]
@Incoming5643 The satchel is not hidden.

**Comment by PKPenguin321** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by Incoming5643** [comment]
I've seen it in game properly hidden. Did something weird happen like another ruin spawning on top of it?

**Comment by AnturK** [comment]
Was close to the west edge of the space bar, not sure if it was on top of it

**Comment by Incoming5643** [comment]
Some ruins contain a bit of space around the structures, I'm going to guess that is what happened, because just spawning OSTs by themselves always hides successfully

**Comment by Jalleo** [comment]
Likely it could of overridden the ordinary space tile with a space tile.

**Comment by Incoming5643** [comment]
so this is just a really good reason to solve #19768

**Comment by Jalleo** [comment]
Yes
