### ISSUE TITLE
Black Box using Mandom

### ISSUE THREAD

**Issue by Repukan** [tgstation/tgstation#19865]
Black box contents will remain the same, no matter how many are removed between rounds. This can be tested by killing a colossus, removing items, and killing it again in the next round.

![tgstation bagil english 100 free lag system edition xi 2016-08-06 175142](https://cloud.githubusercontent.com/assets/19575516/17643736/f20116f8-6140-11e6-9ee4-35feea494f50.png)

Attached is a picture shown of a weird bug, I suppose, also noticed earlier. Only one blue cube and one red cube were added, but for some reason 18 Blue cubes were generated in the box. Not sure if it is connected.

**Comment by Repukan** [comment]
I must add the picture was taken when the Box was not visible.

**Comment by KorPhaeron** [comment]
@MrStonedOne I think you were the last to touch how it worked

**Comment by AnturK** [comment]
Thought that was intended. Pretty sure it worked like that from the start ?

**Comment by Jalleo** [comment]
It could be that somehow more than one copy got saved due to MC, Byond and lag? Woupd be a extreme edgecase if true.

**Comment by MrStonedOne** [comment]
It seems that its not processing for some reason. I'll take a look at this.
