### ISSUE TITLE
Suicide and Meteor rounds.

### ISSUE THREAD

**Issue by Jalleo** [tgstation/tgstation#19868]
[Note]: This occured during the meteor round that was done by Judicator on Friday on dream station. It was mentioned by a player in deadchat that once the round started to chug that they attempted suicide. But they didnt die. Instead they became effectively immortal and was able to survive direct hits by meteors ( need log diving to confirm ). But after a fair while they did suddenly die. (possibly when the suicide finally got processed) 

Things to be aware of. Atmos was processing seriously hard most of the station was damaged or destroyed by the end of the round when it had to be force restarted as the shuttle timer was even slowing down (deadchat was talking about how it was still about 5 minuites to go for like 3 minuites or more?)
Also atmos fires were staying active even though they were right in the middle of breaches. So it was seriously overwhelmed.

**Comment by optimumtact** [comment]
This will be life handling being held up by atmos taking up all the proc time.
