### ISSUE TITLE
Blob cannot attack diagonally, this is suffering.

### ISSUE THREAD

**Issue by callanrocks** [tgstation/tgstation#19876]
Especially since pixel aiming now exists. Especially since it costs resources to attack and blobs are generally fucked if they haven't eaten a quater of the station before they are found.

**Comment by Jalleo** [comment]
Its a old nerf to blobs that should be reverted now.

**Comment by PKPenguin321** [comment]
Feedback forum

**Comment by ChangelingRain** [comment]
#19831
