### ISSUE TITLE
Turning welders off also turns off your other light sources

### ISSUE THREAD

**Issue by Deputi** [tgstation/tgstation#19883]
Turning a welding tool off causes the other light sources a person is carrying such as PDAs, flashlights, and flares to stop producing light. I think this issue is related to the PR that made welders produce light.
![temple of ratvar 2016-08-14 110911](https://cloud.githubusercontent.com/assets/4474395/17650215/4a3c38a4-6216-11e6-92b5-d1aee50ddf1a.png)

**Comment by Jalleo** [comment]
Dupe
