### ISSUE TITLE
Fireball toggle sometimes gets stuck on

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#19888]
Somewhere along the line the fireball spell became a toggle that you turn on to allow you to target a fireball. 

Problem is that sometimes (seemingly every time after the first time the toggle works right) the toggle remains on while the spell is on cooldown and consequently you can blast yourself at point blank range because the first click you make once the cooldown ends will throw a fireball.

**Comment by lzimann** [comment]
No longer happening since #21480 changed fireball's behavior.
