### ISSUE TITLE
Dreamseeker freezing due to ash storm

### ISSUE THREAD

**Issue by soulgamer** [tgstation/tgstation#19895]
I was AI when a miner used an ash rod (or whatever they are called) and made an ash storm in mining on boxstation. Once the ash storm animation started dreamseeker froze. I force closed it and restarted. Once I got near the storm on my cameras and it froze again. After that storm ended I restarted my dreamseeker once more and never had the issue again even with further use of the rod.

**Comment by Jalleo** [comment]
Version of OS and byond please.

**Comment by ShizCalev** [comment]
Will close in a week without another repo.
