### ISSUE TITLE
Cyborg can still use 'Power warning' while broken

### ISSUE THREAD

**Issue by Mysak0CZ** [tgstation/tgstation#19905]
I can still use Power warning as engi cyborg, while i was baten to death and my battery was removed. I was kept with closed wiring, not locked down, opened hatch.

**Comment by A-t48** [comment]
Beep, going to try and tackle

**Comment by phil235** [comment]
https://github.com/tgstation/tgstation/blob/57d9a1b43dc5b3213109e30c3fd87606bb6dc63d/code/modules/mob/living/silicon/robot/emote.dm#L247
