### ISSUE TITLE
cloning can result in eternal sleep

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#19906]
server revision: https://github.com/tgstation/tgstation/commit/c835551f3f9b6f8a4a6dee4d0b887a99e0a2dc44

what happened:
- i was a traitor
- a geneticist gave me all the powers
- later, a rad storm happened and i got the mute defect
- tesla killed me shortly after
- ejected from an auto cloner i was scanned in earlier before i got the defect, died, was cloned again
- ejected from cloner a second time at full health, this time only with xray and hulk
- a doctor shakes me about 10-15 times but i do not wake up
- my HuD does not have the sleeping debuff icon
- the shuttle was about five minutes away when i was cloned
- by the time the round ended about 7 minutes later i was still asleep
- nothing like morphine was injected as far as i could tell

cost me my greentext and i am mad please fix

**Comment by Kromgar** [comment]
Oh man i remember shaking you and thought why wont this guy wake up

**Comment by Jalleo** [comment]
Was the server really choking up from needing to process a lot @Kromgar?

**Comment by PKPenguin321** [comment]
https://github.com/tgstation/tgstation/issues/18491
