### ISSUE TITLE
Traitors can get ashwalkers as assassinate objectives

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#19917]
![untitled](https://cloud.githubusercontent.com/assets/8237862/17702788/5cd2103c-639d-11e6-985e-fcb37369a1b6.png)
Osheeka was actually an ashwalker situated near the necropolis, there was practically no chance of Seth actually being able to kill him.

**Comment by Jalleo** [comment]
Wait why does the syndicate think its a assistant?

**Comment by Kromgar** [comment]
Probably because they are given the assistant job when spawned?
