### ISSUE TITLE
Showing up as all right when having all limbs

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#19912]
![right](http://puu.sh/qCWH0/d9ef084dfe.jpg)
@optimumtact

**Comment by optimumtact** [comment]
Oh, hmm, okay let me check that out.

**Comment by KorPhaeron** [comment]
@optimumtact 

Is it possible to not make it the very last line? It was nice having the important health information at the very bottom so you could see it quickly/easily.

**Comment by optimumtact** [comment]
Yes

**Comment by RemieRichards** [comment]
@optimumtact it's cos you used the numerical defines, not the text ones.
