### ISSUE TITLE
Singulo is not properly turning all of lavaland into a massive chasm

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#19923]
![image](https://cloud.githubusercontent.com/assets/6778786/17722595/6870d9c8-6401-11e6-946c-5bf7c93d2c38.png)

When it eats asteroid walls it makes lava tiles it cant suck up. It can suck up normal lava randomly generated. It also can't seem to eat the normal ground tiles it makes either. It was able to eat the ground near the mining station. It was also able to eat the lava near the necropolis which is pregenned.

@KorPhaeron I mean you already know but i thought to make an issue report. This needs to be fixed it's a critical issue for BoH Bombing the Planet which happens all the time i swear. Should totally be an achievement to have a singulo eat the entire planet.

**Comment by Iamgoofball** [comment]
this is intentional

**Comment by YakumoChen** [comment]
I mean, it's not like the planet is supposed to be hollow or something....

**Comment by TechnoAlchemisto** [comment]
it should probably make lava OR chasms

**Comment by Kromgar** [comment]
Its a blackhole. It should eat up all the lava and make chasms

**Comment by TechnoAlchemisto** [comment]
unless you're walking on a hardened basalt crust on top of lava flows, which is likely considering the lava oceans around :3c. But then again, that would make chasms weird anomalies with no lava in them

**Comment by Dorsisdwarf** [comment]
Solution: make "deeplava" chasms which have an orange glow at the bottom, have lava make those, make singulo chasm everything

**Comment by optimumtact** [comment]
This is better suited for the feedback forum.
