### ISSUE TITLE
Goofball dusts you when it doesn't land on you

### ISSUE THREAD

**Issue by yackemflam** [tgstation/tgstation#19929]
Constantly I get dusted from the tesla, even when it doesn't land on top of me.

**Comment by PKPenguin321** [comment]
I believe it happens if you're adjacent or on top of it. Non-issue

**Comment by Iamgoofball** [comment]
#salt

**Comment by YakumoChen** [comment]
did they change that? what happened to the challenge of putting one in a locker?

**Comment by kilkun** [comment]
fun isnt allowed

**Comment by optimumtact** [comment]
This is not a bug, discuss balance concerns on the feedback forum.
