### ISSUE TITLE
There is space on lavaland

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#19954]
![image](https://cloud.githubusercontent.com/assets/6778786/17789798/c53cf540-6561-11e6-9b43-e0d02d267d9c.png)

I think this is the construction site

**Comment by GunHog** [comment]
Oh. God. How do I even fix this. Why does the mining shuttle not do this when blown up? How would I make sure the aux base deconstructs to space on the station, and volcanic floor on lavaland without snowflake checks?

# HELP

**Comment by KorPhaeron** [comment]
Baseturfs gunhog

**Comment by GunHog** [comment]
It would have to remain set to space while docked at the station, and turned to lavaland base turfs upon landing. What is the best way to do that?

**Comment by bobdobbington** [comment]
There's space everywhere, man.

**Comment by TechnoAlchemisto** [comment]
everyone knows lavaland is a disk in space fucknuts

**Comment by MrStonedOne** [comment]
just make a new mobile type, over ride it's dock, and assign the proper basetype after a ..()

**Comment by Kromgar** [comment]
![image](https://cloud.githubusercontent.com/assets/6778786/21447201/2bf0e95e-c89f-11e6-9205-d5261563a436.png)


It happened again

**Comment by Kromgar** [comment]
![image](https://cloud.githubusercontent.com/assets/6778786/24225191/975d91ce-0f35-11e7-84ae-9f46d9b0d7db.png)

@Jordie0608  

ITS GETTING WORSE

**Comment by KorPhaeron** [comment]
@Cyberboss 

please fix this soon thanks

**Comment by Cyberboss** [comment]
Ree

**Comment by Cyberboss** [comment]
Dupe of #19954
