### ISSUE TITLE
Printing a Laptop Frame in the autolathe completely locks it up.

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#19950]
The autolathe will be permanently stuck busy, making it impossible to use or deconstruct.

**Comment by optimumtact** [comment]
@Shadowlight213

**Comment by Shadowlight213** [comment]
Odd. I'll look into it.
Also who the fuck made it so you can't decon a busy autolathe? Seriously.

**Comment by Shadowlight213** [comment]
Ok. I think I know what the issue is. The laptop frame is a machine. The autolathe seems to assume that it will be building an item.
I'll see what I can do.

**Comment by Jalleo** [comment]
This is fixed please close it https://github.com/tgstation/tgstation/pull/20003
