### ISSUE TITLE
Unable to cure zombism if zombified human is beheaded

### ISSUE THREAD

**Issue by DeliriumFaustus** [tgstation/tgstation#19969]
Zombie code. I often play CMO as Delirium Faust. Encountered the zombie-code for the first time last night, figured out how to remove the tumor that causes Zombism. Unfortunately after a symptomatic victim of Zombism has been beheaded, it's impossible to reattach it to their body which makes curing the condition harder to treat with no logical reasoning. I'm speculating that the code converts the person into a playable mob or whatever, I ain't a coder so pardon my lack of knowledge here, that makes some surgical procedures impossible.

<i>(edited by phil235)</i>

**Comment by PKPenguin321** [comment]
Dat title

**Comment by WJohn** [comment]
welcome to github

we have a title section and a body section

like forum posts or literally anywhere else on the internet

**Comment by MMMiracles** [comment]
i'm honestly surprised github allows for a title that large.

**Comment by xxalpha** [comment]
thanks phil

well this doesn't sound like a bug

**Comment by PKPenguin321** [comment]
Could fix by refactoring the tumor to be a chest organ instead of a head one.
