### ISSUE TITLE
Megafauna end up on station tooi much

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#19971]
Mega-fauna are challenging end game lavaland bosses. They are extremely deadly and require careful preparation.

Traitors have found a way to bring them onto the station which makes rounds absolute chaos.

This sucks for everyone.

Most mega-fauna don't logically work on the station ether

**Comment by ChangelingRain** [comment]
Are you challenging my right to grab the hand tele and just throw a boss on the station instantly for free

**Comment by Supermichael777** [comment]
yes

**Comment by Ergovisavi** [comment]
I'm also not a fan of it... especially when I do it on accident with the jaunter (I'm sorry). Just remove their ability to be affected by bluespace.

I think them getting on station is hilarious every time, but if someone's forcing it every round the meme can get overdone.

**Comment by Hatfish** [comment]
Perhaps only certain items should be able to teleport them to the station?

**Comment by PKPenguin321** [comment]
singulo can also get loose 5 minutes into a round but you dont see issue reporst like this for it

feedback forum

**Comment by AdamElTablawy** [comment]
okay look 

you people added 'end game bosses' to lavaland to roam freely with no restrictions and you're getting upset that people are using them to their advantage in ways unintended (emitter farming bosses ect)?

this is what people do eventually-develop new ways to approach something in a game.

**Comment by Jalleo** [comment]
Solution remove bosses or make them easily die from pressure damage in station.

**Comment by KorPhaeron** [comment]
They should probably not seek out bodies if we want them to ever be killable on station either

**Comment by KorPhaeron** [comment]
This is a problem but not a bug, feedback forum or just open a PR, it's really simple code to stop them going through portals
