### ISSUE TITLE
Large quantities of space cash disappear sometimes when exported

### ISSUE THREAD

**Issue by bobdobbington** [tgstation/tgstation#19973]
After exporting 150 or so 1000 credit space cash bills, in stacks of 20, I failed to recieve any credits for them. All the bills were in the same crate, stacked up. AFAIK there's been no recent change to space cash exports.

**Comment by Jalleo** [comment]
You likely overran the export systems time on counting the money. There is no way to detect this as I know of.

**Comment by MrStonedOne** [comment]
when was the round, it was most likely a runtime that happened after removing the bills, but before granting the credits, we can look it up in the runtime log.

**Comment by Jalleo** [comment]
@Mrstonedone bob sometimes hangs about in IRC so you might be able to use pirou to get their attention that way.

**Comment by RemieRichards** [comment]
@Jalleo MrStonedOne knows how to find bob, they used to be roommates lol

**Comment by optimumtact** [comment]
Fixed by removing cash lemons

**Comment by Jalleo** [comment]
That I didnt know @RemieRichards.
