### ISSUE TITLE
Equipping fire axe doesn't remove "off-hand"

### ISSUE THREAD

**Issue by Lobachevskiy** [tgstation/tgstation#19982]
This happens if you click on your back while dual-wielding fire axe (maybe other dual-wielding items too), not when using quick-equip. Off-hand remains and it is usable. You can hit stuff with it.

**Comment by ChangelingRain** [comment]
@Ergovisavi

**Comment by bobdobbington** [comment]
feature, make it possible to sharpen the off-hand icon for maximum damage

**Comment by optimumtact** [comment]
abstract items man

**Comment by Ergovisavi** [comment]
What the shit, I thought I fixed this. I'll take a whack at it when my arm isn't so messed up and I can type at a decent pace.
