### ISSUE TITLE
Chameleon Kit menus do not open

### ISSUE THREAD

**Issue by kpeculier** [tgstation/tgstation#19986]
Buying a chameleon kit and using said chameleon items will not work other than putting on the initial default wear as the menu will not open when clicked on in the hud on the top left.

**Comment by KorPhaeron** [comment]
quality goof code

**Comment by PKPenguin321** [comment]
rushed code

**Comment by Iamgoofball** [comment]
This is what happens when you force deadlines, I'm still on vacation and can't debug this until Monday
