### ISSUE TITLE
Clown shoes cannot be used with a speed potion.

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#19980]
The clown shoes pocket can only hold bike-horns, but fails to 'hold' a red slime potion when attempting to apply it.

**Comment by KorPhaeron** [comment]
@Core0verload

**Comment by bgobandit** [comment]
honk

**Comment by optimumtact** [comment]
what?

**Comment by optimumtact** [comment]
The handling shouldn't be firing when you're clicking on your mob sprite

**Comment by KorPhaeron** [comment]
You smack the shoes with a detective scanner/slime potion etc.

Instead of the item functioning it tries to store it in the shoes pocket, and fails.

**Comment by optimumtact** [comment]
what a strange potion

that makes more sense now.
