### ISSUE TITLE
Metastation - Broken warn plating in few places.

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#19985]
![dreamseeker_2016-08-20_21-11-53](https://cloud.githubusercontent.com/assets/4047233/17833341/cbee5b58-671a-11e6-92e7-2ad871ad3e8a.png)

**Comment by Shadowlight213** [comment]
This was caused by the moving of warn plates sprites into their own dmi.

**Comment by Dorsisdwarf** [comment]
@Metacide Is this still a Thing?

**Comment by Metacide** [comment]
I'm not sure, was under the impression it was fixed at some point.

**Comment by Shadowlight213** [comment]
should have been fixed by #20678
