### ISSUE TITLE
Strained Muscles can somehow trigger an eternal godmode stasis?

### ISSUE THREAD

**Issue by Darkgenerallord** [tgstation/tgstation#19992]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)
I've had this happen maybe three times. The first was when I slipped on some water with strained muscles, and also canceled it at the same time. I immediately fell over, entered stasis, and became invincible. The second was I ran into a door at the same instant I ended strained muscles, same result. The third I didn't actually touch anything, but I was pressing it pretty fast. I am unsure as to why the fuck this happens.

**Comment by Jalleo** [comment]
@optimumtact i think this may be related to my issue report about suicide and meteors. Not sure though.

**Comment by optimumtact** [comment]
which one is that?

it sounds like one of the slipped flags is getting stuck on and short circuiting a bunch of other handling.

Also what on earth is strained muscles?

**Comment by optimumtact** [comment]
#19982 

I suppose it could be causing a similar issue if the users life get's suspended or held up by a sleeping proc so that user couldn't do anything.

**Comment by Darkgenerallord** [comment]
Strained muscles is a changeling power.

**Comment by Kierany9** [comment]
Improper bitflag removal, see:

https://github.com/HippieStationCode/HippieStation13/pull/2785

**Comment by optimumtact** [comment]
Great catch, putting a patch in now
