### ISSUE TITLE
being in a locker when it gets qdel'd causes you to instantly die and get violently dismembered

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#20002]
how to reproduce
1. go into locker
2. delete locker with admin magic
3. die violently

how to reproduce with ingame stuff
1. go into locker
2. get a ripley with a drill to drill the locker while youre in it
3. die violently

**Comment by RemieRichards** [comment]
ripley drills are known to ```ex_act(1)``` things, and when lockers explode (```ex_act()```) they explode their contents too, which for humans throws limbs around.

just sounds like that, which technically isn't a bug, think about it, the first case is an admin's fault, the second is a literal drill smashing through metal and into you, lockers are about people-sized so it's not like it missed.

Not a bug.

**Comment by PKPenguin321** [comment]
ok

**Comment by PKPenguin321** [comment]
Happens with anything not just Ripley drills

**Comment by phil235** [comment]
Blame things using ex_act() when they have nothing to do with explosions...
