### ISSUE TITLE
Efficiency station AI SMES power output setting starts too low to supply all the apcs.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#20025]
Meaning that unless an AI turns it up, their apc will drain and they will die.

Why is the SMES connected to all the apcs anyways? It's supposed to be soley for the AI apc. The rest are supposed to run off another SMES.

**Comment by ChangelingRain** [comment]
Issue report is technically incorrect; the actual issue is that the SMES's input and output are on the same grid, and the SMES has priority for power drain over APCs. Thus, by default, the SMES will send out 50000 and then just recollect that 50000 and guess how much APCs have left over

**Comment by Shadowlight213** [comment]
@ChangelingRain Actually i noticed that while editing it.
Why do the smes have priority anyways?

**Comment by ChangelingRain** [comment]
Fuck if I know but I encountered this ages ago while making dream and it's pretty obvious, given that the four starting engineering SMES can keep the station powered(and its 60some APCs) for a good 30 minutes.
