### ISSUE TITLE
Show server revision doesn't show all testmerged prs

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#20034]

**Comment by Incoming5643** [comment]
It also breaks the "based on commit" link because it's referencing a version of the code with other testmerged shit in an arrangement that doesn't actually exist.

**Comment by Jordie0608** [comment]
https://github.com/tgstation/tgstation/pull/16042#issuecomment-195660054 @MrStonedOne

**Comment by MrStonedOne** [comment]
Fixed.
