### ISSUE TITLE
Upside down sinners

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#20032]
![image](https://cloud.githubusercontent.com/assets/6778786/17866014/e83c03ce-6872-11e6-95f7-81ca783190d1.png)

**Comment by phil235** [comment]
Wasn't this happening with the meatspike thing?

**Comment by Kromgar** [comment]
Yep. Wear teleport armor

**Comment by YakumoChen** [comment]
the championship belt also does this with drop-knee, it's hilarious. Feature.

**Comment by lzimann** [comment]
If you are meatspiked and the meat spike gets destroyed, your mob will stay upside down aswell.

**Comment by Kromgar** [comment]
Wear teleport armor get hit after being put on stake upside down sinners
