### ISSUE TITLE
Collision issue: Larvas aren't passable anymore.

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#20044]
Larvas don't seem to be passable anymore. Heading in their direction causes one to bump into them, instead passing over them.

`/mob/living/carbon/alien/larva`
`   name = "alien larva"`
`   real_name = "alien larva"`
`   icon_state = "larva0"`
`   pass_flags = PASSTABLE | PASSMOB`
`   mob_size = MOB_SIZE_SMALL`
`   density = 0`

Here's the code snippet provided by Gun Hog.

**Comment by Jalleo** [comment]
What intent were you and she on?

**Comment by Sligneris** [comment]
It was disarm intent.

That being said, I don't mean the 'help intent switching' kind of passable. I mean the 'walk onto the same tile' passable, like Beepsky.

Larvas used to work like this for a long while, but it appears to be bugged now.

**Comment by ChangelingRain** [comment]
I can't reproduce this locally; open this issue again if it happens again but I can't get it to happen with any combination of alien intents moving at the larva, human intents moving at the larva, the larva on either intent moving at a human/alien on any intent, so I'm pretty sure it's fixed?

**Comment by Sligneris** [comment]
By "can't reproduce", you mean that you were able to walk over alien larvas without moving them, right?
