### ISSUE TITLE
Beachbum Bartender and Space Bartender don't have access to their kitchen closets.

### ISSUE THREAD

**Issue by Boggart** [tgstation/tgstation#20059]
> OOC: Zed Xionova: i noticed both the space bartender and the beach bum bartender don't have access to their kitchen closets

Reporting it for them since they doesn't have a github account, I can confirm that the beach ruin bartender/cook can't open the kitchen freezer.

**Comment by TornadoKirby** [comment]
ghost roles don't have to be too special but they need to at least work :V
