### ISSUE TITLE
You can mod Ebows with KA modkits

### ISSUE THREAD

**Issue by Lexorion** [tgstation/tgstation#20086]
You can use modkits on the ebow. Most mods won't work but some like the cooldown modification do work and make the weapon very strong.

**Comment by RemieRichards** [comment]
this is because crossbows are kinetic accelerators these days.

**Comment by ChangelingRain** [comment]
also only cyborg KAs have 80 modpoints normal have 100

**Comment by TechnoAlchemisto** [comment]
this is pretty emergent

**Comment by xxalpha** [comment]
Working as intended.

**Comment by Kromgar** [comment]
AMAZING 10/10

**Comment by WJohn** [comment]
this is amazing

does the aoe mod work? can you aoe stun people? jesus christ that'd be horrifying

**Comment by PKPenguin321** [comment]
real talk, a proper fix to this is to make a parent object to KAs and ebows that is just a gun that recharges itself, then make KAs a child and move upgrades etc to it, make ebow a child and put toxic bolts etc on it

**Comment by Lexorion** [comment]
Well since only some of the modkits work it is a bug,right? Can someone disable those (so you don't waste them) or make all of them work (miiight be broken so limit it to a single mod perhaps)?
