### ISSUE TITLE
Statues spawned from gold cores are death machines that ignore vision

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#20080]
holy shit i got turned into a syndie cyborg the thing could see me through walls and was waiting at the door as soon as it opened it moved at me like lightning and beat me to death

**Comment by Jalleo** [comment]
I think they arent affected by cyborgs. Dont quote this until someone confirms.

**Comment by Kromgar** [comment]
Well there was a magicarp standing there and a drone and it gunned straight for the polymorphed drone

**Comment by Jalleo** [comment]
Okay I shall check out the statue code later today or tomorrow.

**Comment by Jalleo** [comment]
Okay so statues definitly can move fine while there are drones and and silicons about and mobs have to have a client to be able to stop it moving.

**Comment by Dorsisdwarf** [comment]
I saw statues chasing humans down lit hallways, but never attacking.

**Comment by Jalleo** [comment]
That may be down to how it was processing if to attack or n

**Comment by Kromgar** [comment]
Used to be player statues couldnt move if they were watched by a human. 

Oh right i forgot to mention the fucking statue chased me down and killed me infront of two roboticist humans. GUNNED STRAIGHT FOR ME THE ROBOT WITH TWO HUMANS IN THE ROOM

**Comment by Kromgar** [comment]
@Jalleo
