### ISSUE TITLE
As a malf AI, you can use Overload Machine on a gang dominator

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#20088]
[Note]:Malf AIs can use Overload Machine on a gang dominator, blowing it up and defeating the gang very easily.

**Comment by PKPenguin321** [comment]
oy vey

**Comment by Boredone** [comment]
For those who think it can only happen during admin memes, you can get a 'Combat Upgrade Module' or similar as loot from a Ash Walker nest that gives AI malfuncation powers as well.
So probobly something that should get fixed.

**Comment by TechnoAlchemisto** [comment]
couldn't you just cut the camera, this doesn't seem like an issue, they are machines after all

**Comment by Boredone** [comment]
Malf AIs can get powers to reactivate cameras, and/or give them X-Ray Vision.

**Comment by ChangelingRain** [comment]
Plus I'm pretty sure the AI can use the verb to bypass needing a camera if it's smart, so that wouldn't help.

**Comment by Shadowlight213** [comment]
New anti gang meta strat. 10/10

**Comment by TechnoAlchemisto** [comment]
If anything the verb bypass is the bug. Having to make your dominator impossible to see by the AI because they were given an illicit combat upgrade seems like cool gameplay to me.

**Comment by Kromgar** [comment]
This  is not an issue. This is a feature

**Comment by ShadowDeath6** [comment]
this sounds like a quality feature

**Comment by Shadowlight213** [comment]
>using overload machine instead of override machine

**Comment by Dorsisdwarf** [comment]
It would be a feature if it wasn't "Instant game over if mining made the AI secretly gay"

**Comment by Anonmare** [comment]
Combat-Upgraded AIs may get malf powers but they don't get the Law 0 and you can permanently deactivate a camera by welding it after cutting it. Was it running Asimov? If it was, it should be really easy too kill and it's hardly a threat if it's shunted (No powers). Plus you could have re-programmed it if you got your hands on a law module and an upload console.

**Comment by optimumtact** [comment]
Actually no, this isn't a bug and is a very rare situation but is otherwise working as intended.

Feedback forum for discussion of balance concerns.
