### ISSUE TITLE
(e) Bolas penetrate hardsuit or otherwise, shielding

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#20093]
I ded pls nerf. Bolas penetrate hardsuit shielding.

**Comment by TechnoAlchemisto** [comment]
haven't you read dune? everyone knows slower projectiles don't get blocked by shields.

**Comment by PKPenguin321** [comment]
Have you tried getting good?

**Comment by ChangelingRain** [comment]
This happens with riot shields, too. It gives the blocked message and still wraps/slows.

**Comment by Shadowlight213** [comment]
Ok riot shields might be a bug then. I can see how they would block it.

**Comment by Arianya** [comment]
Seems to be an underlying issue with throwcode.

**Comment by Nickkoranda** [comment]
Fixed
