### ISSUE TITLE
Theungibbable corpse

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#20116]
![image](https://cloud.githubusercontent.com/assets/6778786/17989615/c6a3b69e-6afc-11e6-807d-e1c412594488.png)

After being placed on a meatspike and then being placed on a pyre and reviving multiple times singulo took my corpse... and kept gibbing it and gibbing it repeatedly. Even bubblegum was chasing my corpse. Even though i had no body to return to.

7:40PM 8/25/2016 i was a ling

Garl Glitter

Admin added me back to the body. Had no changeling tab. He then used admin button to ash the corpse. Corpse was still there. Pushed button to gib the corpse corpse was still there.

![image](https://cloud.githubusercontent.com/assets/6778786/17989906/e97292e2-6afe-11e6-9955-7edd287a9971.png)

Oh and its still on fire in space. Admins could still interact with the body it interacted with the world when he flung it at grilles to break them

**Comment by francinum** [comment]
Improper GC?

**Comment by ChangelingRain** [comment]
Sounds like it's runtiming somewhere.

**Comment by Jalleo** [comment]
@mrstonedone

**Comment by MrStonedOne** [comment]
I see no mention of what server this was on, so i can't check runtime logs for clues.

**Comment by Kromgar** [comment]
@MrStonedOne Sybil
