### ISSUE TITLE
Can't make anything with runed metal not even construct shells

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#20119]
![image](https://cloud.githubusercontent.com/assets/6778786/17990460/01f1c914-6b04-11e6-88fc-ea10250cb928.png)

@KorPhaeron you suck.

**Comment by KorPhaeron** [comment]
Blame Robustin for not fixing his code for three months, I'm not refactoring structures to clean up his mess

**Comment by ChangelingRain** [comment]
NOT A BUG NOT A BUG
