### ISSUE TITLE
Entering a jaunter portal in a boat leaves you behind...

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#20113]
...But the boat still goes through and you're left buckled to the boat, meaning that you get dunked in lava but cannot move into the portal unless you can unbuckle quickly enough (good luck with that).

**Comment by Jalleo** [comment]
Who added the boat again?

**Comment by Detective-Google** [comment]
Testing on lava with a jaunter, the boat does indeed teleport *with you attached*, no longer an issue
