### ISSUE TITLE
Secret Satchel Status: Still Screwed

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#20121]
Essentially a note to myself to try another bugfix for secret satchels. I hate this is taking so long but testing the pull locally takes about 60 minutes of undivided processor time to run three rounds of any given attempt, with many failed attempts. Currently old_secret_satchels refuses to load anything except the first satchel data despite other data being on the save.

issue will remain open until I can confirm it works perfectly in a real round of play.

**Comment by Supermichael777** [comment]
you need to scramble the list before picking or you get the first one every time

**Comment by RemieRichards** [comment]
@Supermichael777 uh... No.
```pick()``` is random.
