### ISSUE TITLE
Hydroponic's trays save grown status

### ISSUE THREAD

**Issue by stew9703** [tgstation/tgstation#20145]
[Note]: # If I use a spade on a ready to harvest hydroponic's tray and plan a seed the next seed will be instantly ready to pick. Although after picking it will revert to young age if its a plant that stays alive.

**Comment by phil235** [comment]
`harvest = 0` after this line: https://github.com/tgstation/tgstation/blob/70c723c6554129268b189a6d54fd33aef0aa4272/code/modules/hydroponics/hydroponics.dm#L854

**Comment by stew9703** [comment]
I have no clue how to write the code in here or if i can? Is that a suggestion for someone else?

**Comment by phil235** [comment]
Anyone wishing to fix the issue can do it, I'm just helping by giving you the exact problem with the code (missing "harvest = 0")

**Comment by stew9703** [comment]
Ah okay, thanks.

**Comment by CyberbossJHCB** [comment]
Fixed #20455 please close
