### ISSUE TITLE
Rollies and Pipes are doing nothing

### ISSUE THREAD

**Issue by stew9703** [tgstation/tgstation#20143]
[Note]: # Even 100 potency Ambrosia of all three kinds does nothing when smoked. No chemical effects at all. Repeatable every time.

**Comment by optimumtact** [comment]
Potentially related to #20069

**Comment by optimumtact** [comment]
@xxalpha

**Comment by phil235** [comment]
https://github.com/tgstation/tgstation/blob/feeccd3fe4e2d0c8161027061d6837cb89b8db52/code/game/objects/items/weapons/cigs_lighters.dm#L208
`reagents.trans_to(C, REAGENTS_METABOLISM)` (where REAGENTS_METABOLISM is 0.4)
Ambrosia has like 4 or 5 reagents, you do the math.

**Comment by Mervill** [comment]
marijuana in rollies doesn't seem to do anything either (I assume I should get the drugs effect)

What is this, the Nixon administration?

**Comment by Tacolizard** [comment]
old issue, but i did some testing.

the problem isn't only with reagents metabolism, but also that rollies and pipes, no matter what is put inside, spawn containing nicotine. When smoked, the nicotine is the first reagent and only reagent that gets absorbed before the rollie or pipe goes out.

**Comment by PKPenguin321** [comment]
It's possible if Tacolizard's explanation was wrong that this is still an issue, but I doubt it
