### ISSUE TITLE
Russian Revolver description error

### ISSUE THREAD

**Issue by phil235** [tgstation/tgstation#20155]
When the russian revolver has one round spent in it, the description still says:
"Has 1 round remaining.
1 of those are live rounds."
Emptying the gun and putting the round back in it doesn't solve the issue.

**Comment by CyberbossJHCB** [comment]
/obj/item/ammo_box/magazine/internal/cylinder/ammo_count: https://github.com/tgstation/tgstation/blob/master/code/modules/projectiles/ammunition/magazines.dm

 isn't overriding

 /obj/item/ammo_box/magazine/proc/ammo_count: https://github.com/tgstation/tgstation/blob/master/code/modules/projectiles/ammunition.dm

Does byond allow for new arguments in overrides?
