### ISSUE TITLE
donut boxes show donuts even when there are no donuts

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/tgstation#20166]
[Note]: # When checking the brig, I drag-opened a box of donuts on myself. Box was empty, but icon said it was full.

**Comment by bgobandit** [comment]
there have been issues with candle packs too so I suspect a fancy-box bug

**Comment by optimumtact** [comment]
Potentially related to #20069

**Comment by optimumtact** [comment]
@xxalpha

**Comment by xxalpha** [comment]
There's a problem with the candle box, but I can't reproduce the donut box bug.
