### ISSUE TITLE
Twinkie reduces hunger more than cup ramen

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#20174]
This is clearly immersion breaking. A single twinkie should not heal more than four bloody Mr. Noodle cups. I know this is silly, because it is.

**Comment by phil235** [comment]
@tabsiforu dry ramen or hot ramen? You need to add water to ramen before eating it.

**Comment by tabsiforu** [comment]
@phil235 I got it out of the vending machine I don't know if it's cooked

**Comment by optimumtact** [comment]
Feedback forum.
