### ISSUE TITLE
attack_log text in VV is no longer in color

### ISSUE THREAD

**Issue by phil235** [tgstation/tgstation#20181]
`[15:48:42] <font color='red'>Has punched Kyra Gray(phil235) (NEWHP: 99)(140,113,1)</font>`
The font stuff doesn't do its job and appear in the attack log text when it should be interpreted to color the actual text, no idea why this happens.

Likely caused by https://github.com/tgstation/tgstation/pull/19022

**Comment by bgobandit** [comment]
this is fairly recent I think, it worked a month or so ago

**Comment by TechnoAlchemisto** [comment]
It was caused by #19022 I remember asking MSO about it.

**Comment by PKPenguin321** [comment]
I think this is a dupe but can't confirm right now

**Comment by Jordie0608** [comment]
It is #19074
