### ISSUE TITLE
Chameleon projectors and containers don't play nice

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#20185]
Examples:

**_Sleeper Fuckery**_:
- Have a chameleon projector in-hand, have a sleeper be closed on you
- Activate the cham projector, it won't make a sound but it will still work
- Move out of the sleeper area.

The sleeper will continue to display the closed sprite and the contents will still list your name, but you're not in it anymore. Opening the sleeper fixes.

**_Body Bag Fuckery**_
- Have a cham projector in-hand, close yourself in a bodybag
- Activate projector, move out of the body bag

The body bag will open, but you will still get the dark overlay around the bodybag tile and the camera will not update.

**_Holy Shit The Crematorium**_:
- Same deal, get in a crematorium, have cham projector in hand, activate it
- Get cremated
- YOU DON'T DIE
- But ashes still spawn

**Comment by Razharas** [comment]
Cham proj used to protect against any kind of damage from ex_act(1) to singulo eat
Truly a miracle

**Comment by PKPenguin321** [comment]
Could probably just be fixed by not allowing the user to activate the projector while in a closet or whatever

**Comment by TheWiznard** [comment]
Server revision compiled on: 2017-05-02 784b9c3626304a8aac6f3bad86b43b1576998b7c

This happened two rounds ago to me I was in a locker and used a cham projector, and then moved while in the locker and it opened and my view was still centered on the locker but I could see the cig that I look like moving around still and I could move off screen of where the locker was. Saw this issue so I didn't make another one.

**Comment by PKPenguin321** [comment]
If(!isTurf(loc))
 return
