### ISSUE TITLE
Ratvar (almost[?]) always wins against Narsie

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#20194]
In the code that lets ratvar and narsie fight ratvar makes his attempt to "win" first every time. If he wins, and he always seems to,  the fight ends before poor nar-nar can do anything.

Just saw an adminspawned ratvar with no followers win against a naturally spawned narsie with plenty of them.

**Comment by ChangelingRain** [comment]
"No followers" is incorrect; there were 15~ cogscarabs and I'm pretty sure there were less living harvesters+cultists than that(also nar-sie only counts player harvesters so all the NPC harvesters from monkeys and such didn't count)

**Comment by Incoming5643** [comment]
In any case, ratvar checks for victory first, which biases things towards it

**Comment by ShadowDeath6** [comment]
if harvesters aren't cultists then there's your problem right there

**Comment by ChangelingRain** [comment]
Harvesters are checked for nar-sie's win but there generally aren't a lot of them because they're not much fun to play.

**Comment by PKPenguin321** [comment]
maybe you could fix it by making Ratvar's win check and Nar'Sie's win check procs, then having a rand(1,2) and if it's 1 it procs ratvar's first and if it's 2 it procs nar'sie's first?

**Comment by Incoming5643** [comment]
or you could just have them both roll then pick whoever did better

**Comment by PKPenguin321** [comment]
oh yeah that too

**Comment by evsey9** [comment]
It's a feature.
Ratvar is better.

**Comment by ShadowDeath6** [comment]
no
