### ISSUE TITLE
Ore box fell into chasm full of ore... Chasm failed to fulyl form until all the ore fell in... even after it was moved out of the chasm

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#20198]
![image](https://cloud.githubusercontent.com/assets/6778786/18037573/ff046816-6d55-11e6-985d-72329907e2ff.png)

Sybil 7:35ish PM 

So the ore falls into the chasm one at a time after the ore box fell in.  I move all the floating ore onto land and it keeps falling. I leave come back with a new ore box and load the ores they all disappear from the box. As i go to grab my knife a new chasm tilei appears and swallows my knife i run and the tile i was on turned into a chasm. Image is when that happened. apparently i was nearly swallowed intothe abyss as well

**Comment by PKPenguin321** [comment]
sounds like there's a rogue sleep somewhere
