### ISSUE TITLE
Bomb Testing becomes a tesla trap

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#20199]
![image](https://cloud.githubusercontent.com/assets/6778786/18038558/b8b76950-6d67-11e6-870e-f3cbbaf2c628.png)

Stuck for 15 minutes

**Comment by PKPenguin321** [comment]
not my fault this happened before bomb tesla

**Comment by Cheridan** [comment]
And?

**Comment by Kromgar** [comment]
Atleast singulo has a chance of coming back if he fucks off to space

**Comment by PKPenguin321** [comment]
yeah this is really bad and needs a fix
