### ISSUE TITLE
Xenos cant attack wood barriers

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#20202]
![image](https://cloud.githubusercontent.com/assets/6778786/18040213/472777be-6d79-11e6-86d6-067b6854cef6.png)

We couldnt attack them at all new meta.

ITS LIKE SIGNS. ALIENS DONT LIKE WOOD

**Comment by PKPenguin321** [comment]
>ALIENS DONT LIKE WOOD

wj on suicide watch
