### ISSUE TITLE
The laser gatling fusion core magazine does not have a sprite, making it invisible

### ISSUE THREAD

**Issue by ma44** [tgstation/tgstation#20206]
https://github.com/tgstation/tgstation/blob/99620ffe76ba40289efbe91837e6d5bbe264319d/code/modules/projectiles/ammunition/magazines.dm#L172

**Comment by GunHog** [comment]
Because you totally need to reload your 5,000 (actual count) shot full-auto weapon!

**Comment by Davdichan** [comment]
I assume in this case it's more to do with EMPs and or if some chuckle fuck decides to use a chamcloak on it and get free invisibility by mimicking a sprite-less item.

**Comment by KorPhaeron** [comment]
You aren't able to remove it under normal circumstances, it's not meant to be held or seen
