### ISSUE TITLE
ruin stuck surrounded by lava

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/tgstation#20218]
![image](https://cloud.githubusercontent.com/assets/13142400/18071654/9a496dae-6e4f-11e6-9de4-a27cc6d1d09e.png)

**Comment by LanCartwright** [comment]
![image](https://cloud.githubusercontent.com/assets/13142400/18071654/9a496dae-6e4f-11e6-9de4-a27cc6d1d09e.png)

**Comment by ChangelingRain** [comment]
Not a bug, also impossible to fix; you'd need an infinite size ruin to avoid a configuration where it could be blocked by lava.

**Comment by tabsiforu** [comment]
@ChangelingRain move the stick
