### ISSUE TITLE
Candle box sprites are missing

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#20212]
All but the default sprite have gone missing, meaning as soon as you open the box and/or remove a candle, it becomes invisible.

Other /fancy/ boxes seem unaffected

**Comment by KorPhaeron** [comment]
@xxalpha

**Comment by xxalpha** [comment]
If only you merged my fix

**Comment by Mervill** [comment]
@optimumtact closeable, no longer an issue (tested on runtimestation).
