### ISSUE TITLE
ERROR: Eyeobj not found. Creating new eye...

### ISSUE THREAD

**Issue by A-t48** [tgstation/tgstation#20238]
1. Get meteored as AI
2. Go blind
3. Try to view a camera

ERROR: Eyeobj not found. Creating new eye...

**Comment by xxalpha** [comment]
Do you get a new eye or not?

**Comment by phil235** [comment]
Someone test if mob/camera or mob/camera/aiEye can be deleted by an explosion.

**Comment by A-t48** [comment]
I got a new eye, but it seemed to fuck up every time I tried to switch cameras. Fuck meteors.

**Comment by AnturK** [comment]
cameras have godmode and standard atom ex_act so this probably isn't explosion related.

**Comment by A-t48** [comment]
I couldn't repro this on my local machine. Tried manually deleting the eye, it recreated it once only with the error message, and continued to work after. Are there any states in which the aiEye is intentionally deleted?

**Comment by Alek2ander** [comment]
>Are there any states in which the aiEye is intentionally deleted?

I once had my eye sold to Centcom by the cargo shuttle.

Oh, and it was qdelled, so the new eye wasn't actually created until the old eye was put to rest, so I was completely stuck.
