### ISSUE TITLE
Multiple reports of Radiation storms managing to tag/kill people in maintence

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#20235]
@Shadowlight213 

Also the nuke op shuttle wasn't immune to the storm and it nearly wiped them out

**Comment by Shadowlight213** [comment]
@Incoming5643 It's not a fault of radstorms technically.
Every APC in maint has  the area it's powering be on that turf, meaning if someone stands right in front of an apc, they get radded.

**Comment by Incoming5643** [comment]
the reports seemed a little too frequent for it to be JUST that

**Comment by Jalleo** [comment]
The way areas are worked out in weather is really inefficent and may be bugging out due to it being so silly in how it is currently setup.

**Comment by Ergovisavi** [comment]
The "maintenance" inbetween the teleporter and the captain's room isn't shielded due to it not actually being labeled as the captain's quarters.

**Comment by Shadowlight213** [comment]
Sounds like an issue with areas?

**Comment by AnturK** [comment]
These are specific map issues usually, so closing generic issue.
