### ISSUE TITLE
Tesla explosions that occur withing range of the tachyon detector spam chat

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#20231]
The tachyon detector was pointed at the AI sat on meta or something and was next to an intercom.
Tesla reached the sat and chat was suddenly FLOODED with explosion detection info statements.
@PKPenguin321

**Comment by PKPenguin321** [comment]
pretty much a side effect of https://github.com/tgstation/tgstation/issues/20199 which i already made a fix to
