### ISSUE TITLE
Batteries don't fit into tablets or laptops.

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#20247]
Exactly what it says on the tin, you aren't told if you're doing something wrong and nothing seems to work.

**Comment by nullbear** [comment]
are you using energy cells or tablet battery components?

**Comment by AnturK** [comment]
Honestly could just use the standard type.

**Comment by Jalleo** [comment]
Yeah it could all be merged down.

**Comment by Hatfish** [comment]
It's definitely the tablet battery component.

**Comment by Shadowlight213** [comment]
Did you check the description?

**Comment by Hatfish** [comment]
I did, as I said I made absolutely sure the part would fit and it didn't.

**Comment by Jalleo** [comment]
@corruptcomputer

**Comment by Jalleo** [comment]
@Core0verload

**Comment by CorruptComputer** [comment]
Wut

**Comment by Hatfish** [comment]
Actually, I was just retarded and didn't know how modular computer construction works.
Oops.
