### ISSUE TITLE
RND material error

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#20251]
![REPORT THIS](http://puu.sh/qVRyQ/3ce1a9f56a.png)

**Comment by PKPenguin321** [comment]
Relevant line? https://github.com/tgstation/tgstation/blob/master/code/modules/research/designs/medical_designs.dm#L286

**Comment by Jalleo** [comment]
Which test merge is breaking this?

**Comment by Iamgoofball** [comment]
this was my goofmos PR, the testmerge was disabled ages ago
