### ISSUE TITLE
Research and Development is broken in lavaland.

### ISSUE THREAD

**Issue by Repukan** [tgstation/tgstation#20252]
Found golem ship, main station got fucked from traitors so started research with my points and some materials i ordered through cargo.

Got them high enough for femto and bluespace bins, can't print without mats, logically enough. However, introducing enough materials didn't allow me to print either.

![error](https://cloud.githubusercontent.com/assets/19575516/18156467/628c9486-6fe4-11e6-95e5-5f6394d0dca1.PNG)
![error 2](https://cloud.githubusercontent.com/assets/19575516/18156470/67d1685e-6fe4-11e6-804d-adb169fd5020.PNG)

I suggest removing Golem spawn from ruin spawn chance until this is fixed, since their main gimmick is about developing research. Let more ruins spawn in their place, I suppose, since they're nigh useless without the RnD portion.

**Comment by Boredone** [comment]
Dupe of #20251 mostly.

**Comment by nullbear** [comment]
This is caused by testmerge afaik.

**Comment by AnturK** [comment]
#20251 Same issue
