### ISSUE TITLE
Restart vote spams chat.

### ISSUE THREAD

**Issue by nullbear** [tgstation/tgstation#20255]
[see this](http://imgur.com/a/1LYZr)

Restart vote spams chat.

Still ended up restarting though.

**Comment by Jalleo** [comment]
Strange

**Comment by PKPenguin321** [comment]
This has probably been in the game for months but nobody noticed because it requires a restart vote to pass

**Comment by kriskog** [comment]
Have seen several restart votes go through painlessly, closing.
