### ISSUE TITLE
RPEDs and Bluespace RPEDs aren't picking up items

### ISSUE THREAD

**Issue by Saegrimr** [tgstation/tgstation#20256]
Basically the title. RPEDs just aren't grabbing the piles of manipulators or anything when clicked like they used to. They seem to work normally otherwise and you can still put items in there one at a time manually.

**Comment by Kromgar** [comment]
Mining satchels seem kinda funky too like i have to click multiple times to pickup ore. Who the fuck broke satchels?

This hsould clearly be priority

**Comment by Saegrimr** [comment]
Theres also complaints minerborg's satchels aren't picking up ores as they run over them as well.

**Comment by Kromgar** [comment]
@Saegrimr #20186
