### ISSUE TITLE
Radiation Storms ignore radiation protection

### ISSUE THREAD

**Issue by GunHog** [tgstation/tgstation#20258]
They do direct toxin damage in addition to radiation pulses: https://github.com/tgstation/tgstation/pull/20222/files#diff-046742919ea166ad687b3919b3eedb81R155

This toxin damage ignores all forms of radiation protection, meaning that wearing even a radiation suit helps little when the storm comes: 

Before:
![screenshot 2016-09-01 08 43 21](https://cloud.githubusercontent.com/assets/4955510/18169686/e271e7be-7020-11e6-882c-7d279bf6aac5.png)

Few seconds after storm began:
![screenshot 2016-09-01 08 44 46](https://cloud.githubusercontent.com/assets/4955510/18169695/eed0f676-7020-11e6-9717-cbd4c19c3076.png)

Dead in storm:
![screenshot 2016-09-01 08 45 04](https://cloud.githubusercontent.com/assets/4955510/18169703/f815f024-7020-11e6-8e6c-ef105d16eab3.png)

### Suggestions for improvement (select one):
- Remove the direct toxin damage, making the storm work entirely from radiation.
- Run the additional toxin damage through the armor check procs so it is properly reduced by radiation armor values.

**Comment by xxalpha** [comment]
Who thought it was a good idea to have it to give tox damage on top of radiation stacks?

**Comment by TechnoAlchemisto** [comment]
that overlay is just god awful

**Comment by xxalpha** [comment]
Radiation is green and you can't prove otherwise.
