### ISSUE TITLE
RnD just doesn't work anymore

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/tgstation#20261]
reporting this now because nobody else did.
The machines like don't link no matter what happens or something or just error if you try print something.  Multiple players have reported the debug broken message popping up for them.  Don't know what broke it, how it's broke or why, but it's broken.  Helpful issue report is helpful.

**Comment by Kromgar** [comment]
I didn't have any issue linking machines...

**Comment by GunHog** [comment]
Did you try unscrewing all the machines and the console at once? In rare cases, you may need to completely decon the machines and rebuild them, while screwing out the console's screen and back in again.

**Comment by PKPenguin321** [comment]
Reported twice before, I think it has to do with a testmerge

**Comment by Jordie0608** [comment]
This sounds like #20252 and #20251 but it's hard to tell since the description is so incredibly vague that I'm going to close this anyway.
