### ISSUE TITLE
Goofcode breaking Watchers 

### ISSUE THREAD

**Issue by IvanIssaccs** [tgstation/tgstation#20268]
When a miner is hit by a watcher stare they turn into an ice cube. 
When that icecube immediately melts the miner is then stuck unless they lie down and get up or eat something.

**Comment by Kromgar** [comment]
[Goof Fix your shit]

**Comment by InsaneHyena** [comment]
> Be miner
> Get frozen

REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Jordie0608** [comment]
Fixed by #20236
