### ISSUE TITLE
Scrubbers can't be set to scrub Freeon

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#20278]
You can't enable it, it's just an option you can't check.

**Comment by Jalleo** [comment]
That is due to how its been setup

**Comment by Iamgoofball** [comment]
Huh, why the fuck does the check not work

Fucking tgui

**Comment by Shadowlight213** [comment]
You habe the ui_data not setup correctly

**Comment by Iamgoofball** [comment]
@Shadowlight213 I checked it, it should be working

**Comment by Shadowlight213** [comment]
@Iamgoofball I'm guessing this report is from before your rework/fixes getting merged.
