### ISSUE TITLE
You can bat an ash drake into space at maximum speed

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#20271]
Yeah so... brought a drake to station it was entering escape and a guy fucking hit it with his bat and it launched into space. I dont htink you should be able to bat large creatures and throw them around

**Comment by ChangelingRain** [comment]
home run

**Comment by ShadowDeath6** [comment]
feature

this is your reward for bring it onto the station

**Comment by KorPhaeron** [comment]
that's amazing

**Comment by evsey9** [comment]
f e a t u r e

**Comment by Shadowlight213** [comment]
And it's out of the station folks! My oh my!
