### ISSUE TITLE
Lizard facial details missing.

### ISSUE THREAD

**Issue by LAdmiralAckbarl** [tgstation/tgstation#20288]
When I joined the server my lizard character had no facial details when it clearly said I had them on. When I asked the admins about how to fix this one of them told me that I had a beard that only human characters could have and requested that I post about it.

**Comment by InsaneHyena** [comment]
Agreed, lizard players ARE an issue that needs solving.

**Comment by PKPenguin321** [comment]
Yes

**Comment by Incoming5643** [comment]
Beards aren't supposed to render on lizards ever, nor should them rendering cause any of their own features to go missing.

I'm more than a little confused about this one.

**Comment by Incoming5643** [comment]
Alright someone just cocked up lizards completely

**Comment by Incoming5643** [comment]
Due to a test merge and dodgy lizard dmi naming. Will self resolve once the test merge ends.

**Comment by LAdmiralAckbarl** [comment]
Ok thanks

**Comment by Incoming5643** [comment]
fixed now

**Comment by LAdmiralAckbarl** [comment]
nice
