### ISSUE TITLE
Drones can't see more than 1 tile of Ash Drakes

### ISSUE THREAD

**Issue by Lexorion** [tgstation/tgstation#20284]
(Drone (729)) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): drones see only 1 tile of lesser ash drakes on both blank and static filters

Not supposed to be like that,I think.

**Comment by JJRcop** [comment]
the static overlay is 32x32 that gets blended with the drake. I guess we would need to have a way to tile it to whatever icon size it needs to be then blend it

**Comment by RemieRichards** [comment]
@JJRcop it has to be a ```/icon``` to blend anyway so we may as well just ```Scale()``` it, quality won't matter much as it's just a static effect and it'll get blended onto the dragon anyway.
