### ISSUE TITLE
Metal rods display the wrong stack icon upon creation

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#20294]
When you make multiple metal rods, let's say 10 at a time, it shows the sprite for only one rod, despite the stack containing a lot more. Only after using the rods does the sprite refresh (via update_icon I assume) and show the sprite for multiple rods.

**Comment by nullbear** [comment]
This is such an OLD issue.

**Comment by bgobandit** [comment]
I don't remember it showing up until just recently...?

**Comment by YakumoChen** [comment]
It's been an issue since forever

**Comment by Firecage** [comment]
Huh, didn't we already have an issue open for this? I know since bug has been there ever since rods sprites were changed to work this way
