### ISSUE TITLE
New radiation storm incompatible with xenobiology

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#20313]
The new radiation storm is so powerful that full health slimes have trouble living through the damage, potentially causing a full job wipe at any given point in the round.

It's also, as has previously been stated, REALLY STRONG.

**Comment by GunHog** [comment]
Slimepeople have reversed toxin damage (healing becomes damage, damage becomes healing). Do the same for slimes.

**Comment by Shadowlight213** [comment]
FFS I'll cut to toxin damage to like 3

**Comment by Incoming5643** [comment]
There really shouldn't be toxin damage at all, radiation damage already does that, and anyone who actually bothers to wear a radiation suit _should_ be ok

**Comment by GunHog** [comment]
>There really shouldn't be toxin damage at all, radiation damage already does that, and anyone who actually bothers to wear a radiation suit should be ok

This. There should either be zero toxin damage, or it needs to respect radiation armor.  See this for why: https://github.com/tgstation/tgstation/issues/20258

**Comment by Shadowlight213** [comment]
Fine I'll revert the tox damage.
