### ISSUE TITLE
Abductors character sprites turn invisible occassionally

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#20321]
![1ad60890b44d8e2ab5aa696f73dd86c2](https://cloud.githubusercontent.com/assets/12747768/18231088/d3595e52-72ae-11e6-9a62-187bb3fa1993.png)

I'm not sure what causes this, but it might be something related to their equipment, since I saw it happen to crew in possession of abductor items as well.

**Comment by Jordie0608** [comment]
Dupe #20298
