### ISSUE TITLE
Lava staffs are a zero counterplay weapon against blobs

### ISSUE THREAD

**Issue by Ergovisavi** [tgstation/tgstation#20336]
Using the lava staff on a blob will kill it. Given that the lava staff can change any tile in sight to lava, this bypasses having to breach an opening to the core.

@KorPhaeron

**Comment by xxalpha** [comment]
Good.

**Comment by KorPhaeron** [comment]
I cant think of anything except removing the lavastaff or making blobs lavaproof (dumb)

**Comment by Incoming5643** [comment]
For the record I think the blob core IS lavaproof, so you can't one hit kill it this way.

@KorPhaeron Make the lava staff a magic gun and just make the projectile turn the turf to lava on hit or when it passes over the get_turf(target). As a bonus it will add the shot to staff of chaos.

**Comment by KorPhaeron** [comment]
You could still cut an irreperable path to the blob core like that

**Comment by Incoming5643** [comment]
Well yes but at least doing THAT takes a good amount of time and gives the blob the chance to try and attack the staff holder

**Comment by Ergovisavi** [comment]
@Incoming5643 
The blob core is NOT lavaproof. It will shortly die after lava is placed under it.

**Comment by Kromgar** [comment]
Make the core lavaproof then

**Comment by Kromgar** [comment]
Considering the cooldown is 20 seconds using staff to bore your way to the core would be extremely difficult

**Comment by optimumtact** [comment]
This needs to be in the feedback forum
