### ISSUE TITLE
You can move while sliding from freon ice

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#20349]
THIS MIGHT BE BAD

**Comment by Jalleo** [comment]
@Iamgoofball

**Comment by phil235** [comment]
Is this going to be #5441 all over again?

**Comment by Iamgoofball** [comment]
I need more details and reproduction information.

**Comment by ChangelingRain** [comment]
While sliding press a movement key(wow woah)

**Comment by Iamgoofball** [comment]
Fucking how

**Comment by Durkel** [comment]
Sad part is when the server shit itself during a freon test with people hulked out I pointed out that this may be problem since the slipping bug was never actually fixed, it just removed slipping from hulk.

Honk honk

**Comment by XDTM** [comment]
Stun removing chems maybe

**Comment by ChangelingRain** [comment]
The actual lag behind hulk slipping never got fixed, no.

**Comment by Iamgoofball** [comment]
# REMOVE HULK

**Comment by Jalleo** [comment]
Or do the same sort of fix Phil did for lube hulk slip.

**Comment by Cyberboss** [comment]
Fixed in #22490 @lzimann
