### ISSUE TITLE
Floor is made of lava is broken

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#20341]
Summon events version, probably also the admin button version

Nothing happens, the event procs and the turfs never turn

**Comment by Shadowlight213** [comment]
This is horribly vague.
What actually happens?

**Comment by Incoming5643** [comment]
Nothing happens, the event procs and the turfs never turn

**Comment by Jalleo** [comment]
Maybe@xxalpha. Except from that no idea.

**Comment by xxalpha** [comment]
Explain how
