### ISSUE TITLE
Hand labelers don't work on crates and doors, probably other items as well

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#20347]
Hand labeling a crate opens the crate, hand labeling an airlock opens the airlock. I assume this behavior generalizes to anything that can be opened

**Comment by BeeSting12** [comment]
Try using harm intent, think I remember having the same problem and using harm intent fixed it.

**Comment by Mervill** [comment]
@bgobandit @AnturK Closeable, not a bug, Use the Harm Intent

**Comment by Cyberboss** [comment]
>Harm intent

This fucking game
