### ISSUE TITLE
Ghosts can do various alt click interactions

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#20361]
alt clicking an abandoned crate brought up the input interface and I was able to attempt unlocking. I actually put in the correct code and it unlocked.

For sheet stacks, I could alt click and as long as I was adjacent to it, could take sheets out of a stack and they would end up inside my ghost.

**Comment by PKPenguin321** [comment]
It's fire extinguisher cabinets all over again

**Comment by Jalleo** [comment]
Oh god.

**Comment by lzimann** [comment]
Is this still an issue? Can't reproduce the mineral thing. And the abandoned crate is intended for admins.

**Comment by Shadowlight213** [comment]
@lzimann this was after deadminning

**Comment by lzimann** [comment]
Alt clicking crates no longer work, and neither does alt clicking sheet stacks.
