### ISSUE TITLE
Thrown items don't start burning on lava

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#20368]
Throw item on lava to reproduce.
Moving/throwing a mob makes it start processing.

@MrStonedOne

**Comment by MrStonedOne** [comment]
hmmmmm

**Comment by MrStonedOne** [comment]
not my fault, it normally ignores thrown objs, the sad part is there is no way in throwing code to know if an object being thrown is reaching it's final turf in that turf's entered

I can mitigate the issue somewhat by having the turf bind to throwing's hitby proc, but if the object hits something else and falls (like a lava mob) then this will still be the case.

**Comment by Jalleo** [comment]
For information on where this issue currently stands #20380.

**Comment by Qustinnus** [comment]
@KorPhaeron
