### ISSUE TITLE
AI's "Skin feels warm" when near a failing gravity generator

### ISSUE THREAD

**Issue by BrokenCycle** [tgstation/tgstation#20369]
Ripley drilled grav gen APC while I was moved to AI upload. I started seeing repeated messages of "Your skin feels warm." M'immersions were ruined.

**Comment by yodaman888** [comment]
also effects drones

**Comment by InsaneHyena** [comment]
CRAWLING IN MY SKIN

**Comment by peoplearestrange** [comment]
THESE FEELS THEY ARE NOT REAL
