### ISSUE TITLE
atmos hardsuits can't survive freon cold

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#20371]
its dumb

**Comment by XDTM** [comment]
did you have internals on?

**Comment by Jalleo** [comment]
I think this may be a atmos bug. We need more details than that to pinpoint what the actual issue is. @iamgoofball @ass34

**Comment by Iamgoofball** [comment]
That's weird

**Comment by anconfuzedrock** [comment]
I had internals on and there was also plasma in the nearby air thats about it

**Comment by Jalleo** [comment]
maybe it was a edgecase of freon going negative temp and possibly spacesuits arent setup to protect that.

**Comment by KorPhaeron** [comment]
Tested/confirmed with an ERT hardsuit

**Comment by Jalleo** [comment]
@KorPhaeron what was the temp and pressure?

**Comment by Iamgoofball** [comment]
This is fixed in the latest goofmos PR

**Comment by Jalleo** [comment]
Then reference it?

**Comment by jughu** [comment]
Nope it wasnt my atmos suit still had trouble @iamgoofball

**Comment by Iamgoofball** [comment]
There was a fix with goofmos I'll PR it

**Comment by calzilla1** [comment]
@optimumtact is this fixed?

**Comment by optimumtact** [comment]
how would I know

**Comment by Cyberboss** [comment]
Someone grab a hardsuit and smash a freon canister in the janitors closet

**Comment by lzimann** [comment]
Still happening

**Comment by Iamgoofball** [comment]
I keep forgetting to push the fix for this
