### ISSUE TITLE
Hand of God cults can't distinguish teammates

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#20392]
Outside of the god themselves, the standard crew, and even the prophets have no indicator of friend or foe.

**Comment by Incoming5643** [comment]
I don't know if we're even supporting HoG anymore. I wasn't sure any downstreams even ran it.

**Comment by francinum** [comment]
HOG can stand to be ripped out.

**Comment by ChangelingRain** [comment]
it gone
