### ISSUE TITLE
We have two competing standards for decks of cards

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#20407]
![avatar_134682b6a0bb_128](https://cloud.githubusercontent.com/assets/4176358/18365720/cad6836e-75e1-11e6-93c9-c647e58732c0.png)

From left to right:
/obj/item/toy/cards/deck, /obj/item/weapon/deck, and /obj/item/toy/cards/deck/cas

All offer benefits and draw backs, but it's kinda confusing we have both of these.

**Comment by optimumtact** [comment]
That's three standards

**Comment by lordpidey** [comment]
I mean cas is a subtype of the first one, which is logical object oriented programming, so it's really just two.

**Comment by Incoming5643** [comment]
Yeah I realized only after taking the picture that it was subtyped to the older decks. I got confused mostly because CAS was ported with the other standard for some reason.

**Comment by bgobandit** [comment]
Yeah, I realized halfway into porting CAS that there were two paths. Why there are two paths, I have no fucking idea.
