### ISSUE TITLE
DNA Vault is uncompletable.

### ISSUE THREAD

**Issue by A-t48** [tgstation/tgstation#20414]
![dna vault](https://cloud.githubusercontent.com/assets/8206540/18377203/8f200028-761a-11e6-9d33-6e0269e7509e.png)
![failed](https://cloud.githubusercontent.com/assets/8206540/18377204/915a3250-761a-11e6-8a57-3be32da81f47.png)

2 hours of extended as AI for this shit...

**Comment by GunHog** [comment]
https://github.com/tgstation/tgstation/blob/f7fdfe31b26eb80c55cbafdd3e57205b16e4e714/code/modules/station_goals/dna_vault.dm#L55

I **believe** the problem here is that the human dna list check should be `V.dna.len`, not `V.dna`.

**Comment by AnturK** [comment]
Yeah. i'll open pr with few goal fixes when i get home
