### ISSUE TITLE
Tgui Crash

### ISSUE THREAD

**Issue by nullbear** [tgstation/tgstation#20417]
Went to use rnd console to print a capacitor. The Tgui didn't load fully (it was just a white screen with blue hyperlinks) and when i clicked something, i received this message:

```
Unable to open cache file.
Connection failed.
Reconnecting in 10 seconds...
```

And after reconnecting, was immediately disconnected again. And was unable to do anything:

```
Aubrey Holmes's Memories:

Unrecognized or inaccessible verb: .moveup
Unrecognized or inaccessible verb: .moveup
Unrecognized or inaccessible verb: .moveup
Unrecognized or inaccessible verb: .moveup
Unrecognized or inaccessible verb: .moveup
Unrecognized or inaccessible verb: .moveup
Unrecognized or inaccessible verb: .movedown
Unrecognized or inaccessible verb: .movedown
Unrecognized or inaccessible verb: .movedown
Unrecognized or inaccessible verb: .moveleft
Unrecognized or inaccessible verb: .moveright
Unrecognized or inaccessible verb: .moveup
Aubrey Holmes says, "Ugh."
```

Reproduce by opening tgui console such as autolathe or rnd protolathe, and clicking on a link before it finishes loading tgu interface. Higher chance of it happening on first time using the machine, and on machines with more data (such as autolathe and protolathe)

Following this, there was a fuckton of net-lag.

**Comment by MrStonedOne** [comment]
sounds like a disk/filesystem issue, the verb stuff is confirmed byond issue.

delete your byond cache (documents -> byond -> cache -> delete) and it should be fine.

**Comment by PraiseRatvar** [comment]
@DorsisDwarf

**Comment by nicbn** [comment]
@Dorsisdwarf close
