### ISSUE TITLE
Things disappearing on equip + Gibbing sending to lobby

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#20416]
Happened around an hour before this report. Was on Bagil, playing as HoP.
1. Don't remember exactly what I did before, but at some point I was sitting on the bridge when I noticed that if I took out my items from my backpack and put it back in, my screen didn't update to show that it's in my backpack untill I clicked on the backpack, and it didn't make a text message that I put it in. Also, when I took them out, their inhand sprites weren't showing on my sprite.
2. I thought that was weird, reconnected, didn't fix it like usual when I have sprite bugs.
3. Took off backpack, bug was still there
4. Put on backpack. Noticed that, IT WASNT ON MY BACK
5. Ask people around me if they see a backpack on the floor as I definately didn't see it and alt-clicking showed nothing on the floors. I can still use point-to verb autocomplete to see that it was still near me, only not on the floor.
6. Maybe it's just my backpack being fucky. Then I realized that I was bugged when the captain's antique laser, cloak, my PDA + ID, and jumpsuit disappeared when I tried to put them on
7. Call admins, blah blah..
7.5. Run around station equipping public clothing and backpacks :^)
8. Alphaabeta offers to make new body, I ask Razharas on coderbus to take a look
9. Razharas says that I have "a whole ton of pjs inside me" after trying to put clothing on me and removing it again :^) (I tried to equip every pair of pjs in the dorms :^) )
10. Razharas gibs me and gets me a new body, but before he does..
11. .... I crash when I get gibbed.....
12. Closed Dream Seeker, reconnected
13. IM IN THE LOBBY!!!!!
14. Rejoin as assistant. Oh well, the fuck was that?
15. Razharas gives me HOP job equipment.
Wew

**Comment by Razharas** [comment]
All the items he tried to put on were ending up in the "contents" list but didnt fill the slot vars
Also when i was trying to forcefully put clothes on him through menu they would just drop from my hand and nothing else would happen

**Comment by Razharas** [comment]
@Miauw62 
I only remember you of people who touched equipping ever, also maybe 
@RemieRichards

**Comment by MrStonedOne** [comment]
take a glance thru here: https://tgstation13.org/parsed-logs/basil/runtimes/

Sounds like something might be runtiming before assigning the slot var.

**Comment by Shadowlight213** [comment]
I saw something similar happen a few days ago. 
It was caused by my observer hud code. There was a null in the mob's observers list, which was causing equipping to runtime.
I'll try and fix this when I get home.

**Comment by phil235** [comment]
```
runtime error: 
[11:00:08]Cannot read null.client
[11:00:08]proc name: equip to slot (/mob/living/carbon/equip_to_slot)
[11:00:08]  source file: inventory.dm,41
[11:00:08]  usr: (src)
[11:00:08]  src: Skylar Lineman (/mob/living/carbon/human)
[11:00:08]  src.loc: the floor (51,137,1) (/turf/open/floor/plasteel)
[11:00:08]  call stack:
[11:00:08]Skylar Lineman (/mob/living/carbon/human): equip to slot(the antique laser gun (/obj/item/weapon/gun/energy/laser/captain), 17, 1)
``` 

There are some nulls in the observers list.
