### ISSUE TITLE
You don't drop items when you unbuckle from a chair without legs

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#20415]
So this is a report of a thing i saw
if you loose both legs and strap yourself to a chair you can hold items and then unbucke and move with them.

Honestly the whole dimemberment system/ drop while prone needs rework

**Comment by Dorsisdwarf** [comment]
edited to make the actual bug here clearer

**Comment by nullbear** [comment]
im pretty sure this is a duplicate.

**Comment by optimumtact** [comment]
Why would you drop items when you have no legs? You still have arms

**Comment by RemieRichards** [comment]
@optimumtact we've been over this before, you need your hands to walk on when you have no legs.
