### ISSUE TITLE
After playing  ss13, world-viewing-screen freezes, yet my chat viewer is still functional.

### ISSUE THREAD

**Issue by SgtxRootbeer** [tgstation/tgstation#20428]
As the title states, 5 minutes or so, after I join sybil and basil, the part of the game window that displayes the world fails to update, but I can right-click stuff, I can also move in the game world (as evidenced by me hearing doors opening when I walk into them after the soft-lock occurs.

This has been occuring since yesterday, (9/8/16, yesterday's date, pacific time)

I will be disabling software/overlays, and trying different servers to see if this problem is related to just /tg/station, byond, or my pc's software configuration. I will be updating with any new information I find during my testing. 

upon request, I can provide an *.nfo file in a *.zip for any "maintainer" who asks. 

Update:
After going onto yogstation, which uses a slightly older version of /tg/station code, the problem persisted, however upon joing a paradise station server, I have yet to experience the soft-lock.

This means that a recent change to byond, or /tg/station (which was also copied to yogstation recently) is not compatible with one-another on my specific computer (as I have yet to see anyone else making a report about this)

After attempting to use the beta branch of byond, the problem persists.

**Comment by SgtxRootbeer** [comment]
After going onto yogstation, which uses a slightly older version of /tg/station code, the problem persisted, however upon joing a paradise station server, I have yet to experience the soft-lock.

I don't think I need to say that the problem is either connected with a new version of byond interacting with /tg/station, or /tg/station interacting with my pc in a weird manner, (yogstation may have updated their code recently enough to nullify my test)

**Comment by Jordie0608** [comment]
This is quite an old byond issue #2601

**Comment by AterSoul** [comment]
Its happening to me too, but im hosting
