### ISSUE TITLE
Suggestion: R&D can make kinetic accelerators

### ISSUE THREAD

**Issue by BlueNothing** [tgstation/tgstation#20425]
In the current state of events, about half of science is rendered obsolete or pointless by mining asking chemistry for some sulphuric acid, taking the metal and glass from (I think) Auxiliary Tool Storage, and the science boards from Tech Storage, then they can pretty much rebuild Robotics and R&D on Lavaland, To counterbalance this, I propose granting R&D the ability to make a proto-kinetic accelerator with a decently high level of research so that they can use the auxiliary mining base to address their mining needs if mining decides to declare independence on a given shift. 

Under the current state of affairs, mining can live without R&D, and even build half or so of the Science department (no toxins, and xenobio would be a bit tricky unless they build telescience first, but good luck getting all of that done unless it's some kind of marathon round), as well as at least a mid-sized Medbay. R&D and Robotics, however, are significantly hindered by a lack of support from the mining asteroid at present, and an upgrade to bring parity in this respect seems appropriate for this reason.

**Comment by BlueNothing** [comment]
Agreed, this isn't a bug. Just wasn't sure where to put suggestions, so I put it here. Sorry.

**Comment by PKPenguin321** [comment]
Suggestions go on the ideas section of the forums

**Comment by BlueNothing** [comment]
Oops! Thanks for the redirect.

**Comment by KorPhaeron** [comment]
This is a good suggestion though
