### ISSUE TITLE
Typing "notes" into the command line brings up admin notes and not memory notes

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#20421]
Typing notes into the command line now brings up this screen instead of the old notes screen (where your memories are)

memory notes were moved to the much clunkier "Notes-Memory" and on more than one occasion I've seen people complaining that they couldn't figure out their pda codes/objectives because they assumed notes still pointed there.

Is Bad.

**Comment by TechnoAlchemisto** [comment]
View admin notes is in the OOC tab, whilst Notes-Memory is in the IC tab, which makes sense.

There was an announcement on sybil, at least, that you need to request an admin to move your old notes to public, since they're automatically private or something.

**Comment by lzimann** [comment]
every single note is set to secret, so the view-admin-notes won't show anything unless the note is public

**Comment by Incoming5643** [comment]
either way, can we return "notes" to the memory notes? It's used a lot more often than checking one's admin notes

**Comment by lzimann** [comment]
i don't know why it was changed to be honest, it doesn't conflict...

**Comment by Jordie0608** [comment]
https://github.com/tgstation/tgstation/pull/20426#issuecomment-246086293

**Comment by MrStonedOne** [comment]
http://www.byond.com/forum/?post=2145878

**Comment by Jalleo** [comment]
I believe this is now fixed and merged.

**Comment by lzimann** [comment]
not exactly fixed but worked around(it's a byond issue)
