### ISSUE TITLE
Arrivals shuttle isn't immune to rad storms/No warning for people joining that there is a radiation storm

### ISSUE THREAD

**Issue by MrAlphonzo** [tgstation/tgstation#20432]
If you are unfortunate enough to join during a radiation storm, you will have your ass handed to you by rads before you can find the nearest maintenance shaft. If you are EXTRA unfortunate, like me, you'll run into a traitor at your first maintenance shaft and then have your ass double handed to you.

**Comment by KorPhaeron** [comment]
We need a system that lets coders customize the message people receive when they sign up, for things like storms or war ops

**Comment by peoplearestrange** [comment]
Or just make it so the arrivals/all shuttles are immune to radiation storms?

**Comment by KorPhaeron** [comment]
@peoplearestrange 

That could still lead to things like

1. Radstorm warning

2. Sign up 10 seconds later

3. Obliviously walk into the main hall

4. Get roasted by the radstorm afterwards

**Comment by peoplearestrange** [comment]
True, but at least having the pods/shuttles immune give some kinda of safe haven if its not possible to get to maint and you spawn.

Also I take it the rad storm doesnt effect other Z levels?
