### ISSUE TITLE
Lightgeist Cannot be created outside of normal means [give me the jellies!]

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#20431]
When trying to spawn a Lightgeist using game panel/spawn [aka badminnery], the Lightgeist will appear for a few seconds then delete itself [im assuming because it's not linked to an anon crystal].

This issue also sorta extends to stands.

**Comment by Ergovisavi** [comment]
Yeah I can add this I guess. Lightgeists despawn if they don't have a ckey because otherwise they act as hostile mobs and aggressively seek out people and heal them automatically, and I didn't want ghosts spawning shittons of them all over the place. I'll just handle this another way.

**Comment by Ergovisavi** [comment]
#20531 

Fixed
