### ISSUE TITLE
tesla revolver is even more broken than grilles

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#20462]
tesla revolver projectiles don't seem to get destroyed, so it will hit the same target multiple times as well as pierce through them, and if that wasn't enough the projectiles don't go away on hitting a wall, so if you shoot it at a wall it will shock the next person who walks into it, or if the wall gets destroyed it will continue flying. did I mention it does a fuckload more damage than intended?

**Comment by ChangelingRain** [comment]
I am going to bet 50 fucking bucks that this is the Beam() that both tesla revolvers and meathooks use  #16981

**Comment by Ninja137** [comment]
It's a feature

**Comment by PKPenguin321** [comment]
That shouldn't happen I think

**Comment by optimumtact** [comment]
Yeah that's why they call it a bug

**Comment by PKPenguin321** [comment]
Oh

**Comment by evsey9** [comment]
feature

**Comment by kevinz000** [comment]
**# Already fixed by my teslium PR which made only tesla engine blow shit up. Close this.**
