### ISSUE TITLE
Cogscarabs worn as hats are invisible

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#20460]
@ChangelingRain

**Comment by ChangelingRain** [comment]
I should probably make an override so you can't pick them up and instead just attack them bleh bleh

**Comment by KorPhaeron** [comment]
Don't you dare

**Comment by ChangelingRain** [comment]
HAT DRONES ARE ALL AWFUL SPRITES

**Comment by ChangelingRain** [comment]
THEY'RE ALL HORRIBLY PROPORTIONED MESSES I HATE THEM

**Comment by ChangelingRain** [comment]
you can't pick scarabs up anymore~
