### ISSUE TITLE
vehicles allow you to maneuver in space

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#20465]
How to reproduce:
1. Get a scooter/janicart/skateboard etc
2. Go into space (preferably with EVA gear)
3. Buckle into your vehicle
4. Ctrl+click the vehicle to drag it while you are in it
5. You can now maneuver freely in space

Why this is bad:
skateboards allow jetpack-tier space movement

**Comment by optimumtact** [comment]
Did you have magboots on at the time?

**Comment by ChangelingRain** [comment]
THIS ONE ISN'T MY FAULT

**Comment by RemieRichards** [comment]
@ChangelingRain prove it!

**Comment by jughu** [comment]
Untill you hit a meteor with your skateboard 😏

**Comment by PKPenguin321** [comment]
>Did you have magboots on at the time?

been a while since i found this but i don't believe so. i've known this bug for like maybe a month or two now but kept forgetting to report it, the magboots issue that got reported a while ago reminded me

**Comment by phil235** [comment]
I think this is the fault of the testmerge of carbon dismemberment, I touched vehicle code.

**Comment by PKPenguin321** [comment]
I just had a thought, this could probably be prevented by not allowing the rider of a vehicle to pull said vehicle while they are riding it. Would probably prevent other future unforeseen bugs as well

**Comment by Mervill** [comment]
Related #21510

**Comment by Mervill** [comment]
https://github.com/tgstation/tgstation/issues/14540 Is not directrly related but also deals with vehicle issues

**Comment by Mervill** [comment]
weird that this didn't auto-close :/

**Comment by optimumtact** [comment]
it did?
