### ISSUE TITLE
pAIs are really fucked up

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#20482]
I've been hesitating to make this report for a while because the bug itself is really weird and hard to describe. 

I think it happened around the time that PR that generalized ghost role prompts (the one that put a "never for this round" on "would you like to be a spider?") got merged.

Basically, before this change if you clicked yes to be a pAI when the prompt appeared, you would immediately get the panel to enter your pAI info. Once you entered your info, the person with the pAI would immediately get notified that a new personality is available.

Now once you click yes on the pAI prompt, the panel to enter your info does not appear for several seconds. During this time, it's not uncommon to receive more prompts from the same device, which others can click yes to. Once the panel pops up and you enter your info, the pAI device often won't even alert the carrier than a personality is ready (I think? I haven't been able to test this very well).

The person with the pAI device can also send many requests. If he closes the window after sending lots of requests, then a few seconds later the window will automatically open back up.

My guess of why this is happening is that the PR to generalize ghost role prompts put a 60 second timer on the prompts after you click Yes on them, but for pAIs you don't directly go into the mob when you click Yes, you instead get the info panel where you fill out your name, desc, etc.

This is a really weird bug and definitely needs reproduction

**Comment by Jalleo** [comment]
Sounds like it would be happening due to how pAI's are currently handled

**Comment by optimumtact** [comment]
There was a runtime related to this and suffice to say, PAI code is a bit of a mess and I couldn't trace it exactly

**Comment by bgobandit** [comment]
is this still happening

**Comment by PKPenguin321** [comment]
I think the Mekhi thing might have fixed it? I've seen pAIs running around as normal, so probably not.
