### ISSUE TITLE
[s] How to cause fun lag with a locker, containment field and a wall!

### ISSUE THREAD

**Issue by F-OS** [tgstation/tgstation#20480]
Step 1: put on EVA+Magboots with a turned on singularity

Step 2:make a wall and have one tile free between field and wall. 

Step 3:Pull locker onto free tile

Step 4:proceed to pull the locker into field = causing lots of sparks and entities = crash under 1 minute of doing it.

Step 5:laugh as sybil dies.

did this on my test server and caused a crash within 30 seconds, could probably be fixed if we limited the number of effects.

**Comment by phil235** [comment]
The return of #13212 ?

**Comment by F-OS** [comment]
god i am a moron, happened on a really old build of tg i had on a usb stick.

**Comment by phil235** [comment]
You had me worried for a second ! :disappointed_relieved:

**Comment by F-OS** [comment]
yeah, sorry.
