### ISSUE TITLE
Crashed  UFO lavaland ruins can provide over 500,000 supply points, intended?

### ISSUE THREAD

**Issue by ma44** [tgstation/tgstation#20495]
Can't tell if this is intended or not, but it's still a very rare ruin and no one really bothers to disassembling it, but it's still worth 500,000 supply points VIA exporting the alien alloy it's made out of

**Comment by KorPhaeron** [comment]
Why the fuck is alien alloy worth so much, you can print that stuff in RD as well

**Comment by Jalleo** [comment]
Because exports.

**Comment by ma44** [comment]
@KorPhaeron You need to magically get a alien tool somehow, otherwise you would see me doing this every round

Also interesting to know is that alien alloy was NEVER exported for the last 30 days 
SOURCE: http://www.ss13.eu/tgdb/tg/stats_2016-07-19_to_2016-08-18.html

**Comment by Ergovisavi** [comment]
>Alien alloy was never exported for the last 30 days
>Explicitly remember giving a cargo tech alien alloy

REE, etc.

Anyway. I think alien alloy fetching a nice price in cargo is a good thing and am even using it as a mechanic (One of the anomalous crystal variants can turn the place into an alien location, allowing you to strip the place down for alloy), but that involves you killing the colossus and getting lucky twice.

That said you probably shouldn't be able to print alien alloy out at science. That's just silly.

**Comment by ma44** [comment]
Being able to print "fake" alien alloy (makes metal that's similar to the design but can't be exported) or just having to pour in a lot more materials for the alloy would be a lot better

**Comment by Tacolizard** [comment]
viva cargonia fam

**Comment by kevinz000** [comment]
@lzimann not a bug

**Comment by PKPenguin321** [comment]
Close
