### ISSUE TITLE
Bluespace artillery goal doesn't recieve credit when finished.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#20493]
We finished the bluespace artillery about a minute before the round ended, fired it at a drake even, and when the round ended it had said we failed.

Can't manage to get the revision for some reason, happened at 6:52 am today.

**Comment by AnturK** [comment]
Was it powered at the round end ?

**Comment by Durkel** [comment]
I'm pretty sure, I was standing right next to waiting to fire another shot, The console was still working and such.

**Comment by Durkel** [comment]
Managed to complete another artillery today and got credit for it, Perhaps it was depowered at the end.

**Comment by Jalleo** [comment]
@Durkel i would of said to keep it open encase this is a edgecase issue.
