### ISSUE TITLE
The newscaster does not appear to broadcast messages to the radio anymore.

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#20494]
Was near roundstart, comms were fine, it was the newscaster near arrivals on box

**Comment by AnturK** [comment]
Wait, you mean the local talk or radio ? Newscasters don't broadcast to radio by default iirc.

**Comment by Shadowlight213** [comment]
They don't. If they are on the radio, it's due to an intercom being on nearby.

**Comment by Jalleo** [comment]
Newscaster never were meant to.

**Comment by bgobandit** [comment]
By message I mean the thing that says "New story" or whatever

**Comment by Shadowlight213** [comment]
Yes. They never were meant to broadcast on the radio.

**Comment by bgobandit** [comment]
that's dumb -- how else are people supposed to know there's a new story

**Comment by phil235** [comment]
not a bug
