### ISSUE TITLE
Make some proper project stuff

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/tgstation#20515]
We currently have:
- No Projects
- No Project Columns
- No Cards!

https://github.com/tgstation/tgstation/projects/1

**Comment by Jalleo** [comment]
#Panic

**Comment by Jalleo** [comment]
Can I suggest we have a project for working out how to solve the big issues facing our code at the moment? e.g. locating areas of the code that are either broken and doesn't report its broken (look at food processor before my PR fixing that the new for bloodbucket was using a deprecated one that didn't even work anymore and was spawning a non defined path NO RUNTIMES) and probably other things.

**Comment by AnturK** [comment]
I made a thing. Not sure that's how it's supposed to be used ?

**Comment by optimumtact** [comment]
boring

**Comment by bgobandit** [comment]
can this be closed

**Comment by optimumtact** [comment]
I guess

**Comment by Mervill** [comment]
I'll manage this, if that's what needed

**Comment by optimumtact** [comment]
wasteful bureaucracy

**Comment by Mervill** [comment]
\> tfw im working on a bureaucracy update for after the code freeze
