### ISSUE TITLE
You randomly stop in space

### ISSUE THREAD

**Issue by yackemflam** [tgstation/tgstation#20518]
If you float in space sometimes you stop moving without touching an object in space.

**Comment by Tacolizard** [comment]
This would probably be related to the moving in space bug right?

**Comment by PKPenguin321** [comment]
@anonus ?

**Comment by ChangelingRain** [comment]
Sounds more related to #20441 so @MrStonedOne

**Comment by MrStonedOne** [comment]
hmm, i'll take a look after work.

**Comment by MrStonedOne** [comment]
could also be #19686

**Comment by MrStonedOne** [comment]
I haven't been able to reproduce, and i can't seem to find anything in the code that looks off.

**Comment by yackemflam** [comment]
To reproduce I would hold down a movement key

**Comment by MrStonedOne** [comment]
I did find ***A*** issue with space movement so i'll work on patching that in a bit. No idea if it caused what you saw.

**Comment by PraiseRatvar** [comment]
@MrStonedOne @Dorsisdwarf 

sounds like this needs some closing then? No?

**Comment by ninjanomnom** [comment]
This pr is outdated enough to be worthless, if a similar issue is found make a new issue with details on the circumstances
