### ISSUE TITLE
Protect Master Branch

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/tgstation#20516]
@Cheridan this ping doesn't work from project notes, _sigh_

**Comment by optimumtact** [comment]
NO!

**Comment by CyberbossJHCB** [comment]
This happening or what? (Muh issues count)

**Comment by optimumtact** [comment]
I'm against this, it doesn't give us anything really

you shouldn't hire any maintainers who will abuse the privelege of master pushing

**Comment by Cyberboss** [comment]
Politics aside, you guys can't do this without majorly reworking changelog generation and compilation. Should be closed

**Comment by RemieRichards** [comment]
@Cyberboss you give the bot commit access and have it autoreview it's changelog PRs.
duh.

**Comment by Cyberboss** [comment]
I'm fairly certain it's impossible to push to a github protected branch without a PR

**Comment by RemieRichards** [comment]
bots can make PRs.

**Comment by duncathan** [comment]
What's the point of this?

**Comment by Jordie0608** [comment]
It's possible but yeah why? We haven't had any issues with stuff getting pushed when it shouldn't (if anything it's been helpful to be able to do this) and in the event of mistakes it's easy to revert a commit.

**Comment by KorPhaeron** [comment]
Cheridan never responded to this

**Comment by Cyberboss** [comment]
This is actually completely doable if you just make @tgstation-server an admin on the repo which bypasses branch protection for pushing but still disables force-pushing

**Comment by duncathan** [comment]
we also never really heard a reason why
