### ISSUE TITLE
Fire locks broke atmos again

### ISSUE THREAD

**Issue by yackemflam** [tgstation/tgstation#20517]
If you crowbar a fire lock closed and reopen it the air is gone and space winds starts happening.

**Comment by MrStonedOne** [comment]
Can not reproduce, Could it have just been a coincidence with some other breach catching up to your location?

Could have also been that the firelock triggers a force turf wakeup and atmos differences that weren't getting processed because of a another bug started getting processed.

**Comment by phil235** [comment]
Reproduced it. You need to crowbar the floor to make it into plating while the firelock is closed (using altclick on turf), then you crowbar open the firelock (also happens with any other method of opening).

**Comment by MrStonedOne** [comment]
Ohhh, ok, so i'm just gonna have to make change_turf in those cases properly transfer the existing air with the tile, and at the least default to the tile's air text if it has no air.

**Comment by duncathan** [comment]
Oh hey I fixed this in #31655
