### ISSUE TITLE
Stock market is broken

### ISSUE THREAD

**Issue by chickenboy10** [tgstation/tgstation#20522]
The stock market is broken. The problem is with the borrow ability in the full list.
Heres an example: Here i start with 5000 credits on an ordinary shift and i just look for a cheap burrow option to burrow stocks.
![stepone](https://cloud.githubusercontent.com/assets/11432022/18532175/579a6fbe-7ad2-11e6-9fee-8755f94a5c4b.PNG)

I use this option, selling the stocks straight after

![steptwo](https://cloud.githubusercontent.com/assets/11432022/18532178/609385c4-7ad2-11e6-9392-6ce1fbdcb953.png)

With the increase in money, i "borrow" even more stocks and keep selling, getting a huge amount of money in a very short amount of time.
With this money i can freely buy huge amounts of anything from cargo, in this example i get around 20000 credits in about 2-3 minutes.

![stepthree](https://cloud.githubusercontent.com/assets/11432022/18532206/8b52559c-7ad2-11e6-80c1-0887663d2479.png)
![stepfour](https://cloud.githubusercontent.com/assets/11432022/18532208/8d36defa-7ad2-11e6-917e-7a10bba89117.png)

Note: after the stocks expire you go straight into a massive amount of negative money, but who cares since you just bought out centcomm

**Comment by KorPhaeron** [comment]
@Iamgoofball

**Comment by nullbear** [comment]
possible fix (without removing the feature) would be to only be able to have 1 or 2 active borrows at a time. Would make borrowing more strategic as well.

**Comment by Iamgoofball** [comment]
Borrow removal process is up

**Comment by Jalleo** [comment]
Why dont you reference the fixes iamgoofball?

**Comment by Cyberboss** [comment]
Is this fixed??

**Comment by Iamgoofball** [comment]
this is fixed yes WHY CAN'T YOU FUCKERS REMEMBER TO CLOSE THIS SHIT

**Comment by Cyberboss** [comment]
Y U NO REFERNCE IN PRS!?!?!

**Comment by Cyberboss** [comment]
@optimumtact
