### ISSUE TITLE
Engineering Cyborg Metal/Glass/Rods Bug

### ISSUE THREAD

**Issue by TehPear** [tgstation/tgstation#20521]
As of right now as the engineering cyborg if you select the metal sheets, glass, or rods and attempt to construct anything through the menu it will not let you do that. Thus it makes the engineering cyborg unable to build things like wall girders, grilles, and various other items through the menu.

This is only affecting the cyborg's resources. Resources used by humanoids is unaffected.

**Comment by phil235** [comment]
Reproduced, not due to a runtime.
