### ISSUE TITLE
laughter demon revive does not heal status effects

### ISSUE THREAD

**Issue by nullbear** [tgstation/tgstation#20539]
Now i admit, i wasn't paying any attention when this happened, but:

Was arcane bola'd by a mage, and then shortly afterwards fireball'd causing me to lose my left arm, and die. I alt-tabbed for a bit, and when i came back it appeared that i had been revived by a laughter demon (no idea how that works) But i still had the arcane bola legcuffed status effect icon (as well as the icon overlay) but without the actual effect. As in i could run at normal speed.

As well, my arm had grown back. (You could see it on my sprite, and examine/medical analyzers said i was in pristine health.) But i still had the X overlay on my left hand, and was unable to use it. (you look at your left hand and sigh)

**Comment by phil235** [comment]
I can only reproduce the X overlay not being removed by using revive(1,1) while dead. Bola legcuff alert is removed just fine.

**Comment by tralezab** [comment]
has already been fixed, tested locally
