### ISSUE TITLE
Using a clockwork slab makes you lose all the components in your slab

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#20532]
If you cancel recital, open recollection, recite a scripture, or really do anything, once you're finished you'll receive a message saying "You transfer your slab's components into the clockwork slab." and ALL the components will disappear.
Not sure if it's relevant, but when I used a stack of runed metal inhand i got a "Your runed metal stack now contains 50 runed metal sheets." message.
Priority high as this utterly fucks the gamemode
@ChangelingRain

**Comment by ChangelingRain** [comment]
This is, uh, really not my bug because it means items are calling attackby() on themself with themself as the item argument instead of attack_self()
