### ISSUE TITLE
Buttons in Character Settings/Game Preferences do nothing (BYOND 511.1356)

### ISSUE THREAD

**Issue by erwgd** [tgstation/tgstation#20538]
On BYOND 511.1356, I am unable to change any of my settings on the Character Settings or Game Preferences screen. I can join and play games as usual.
I can open Character Setup from the New Player menu. 
On the Character Settings screen, if I click any button nothing happens: clicking the name doesn't open a prompt to enter a name, clicking a different character doesn't change to that character, clicking on Game Preferences doesn't take me to Game Preferences, etc.

The same thing happens on the Game Preferences screen. I am able to open it using the 'Game Preferences' verb from the Preferences tab, but clicking any button doesn't do anything.

I experienced this issue on Sybil:
> Server revision compiled on: 2016-09-15
> Test merge active of PR #20508 
> Based off master commit cc9c07a499bf9d22bc601223dba481f978d328bc 

and on Basil:
> Revision unknown

This doesn't happen when on the stable version, BYOND 510.1347. I'm using Windows Vista and have Internet Explorer 9.

**Comment by optimumtact** [comment]
Downgrade to stable

**Comment by MrStonedOne** [comment]
http://www.byond.com/forum/?post=2148122

downgrade to 511.1355 http://www.byond.com/download/build/511/511.1355_byond.exe
