### ISSUE TITLE
Antihol things

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#20546]
For some reason antihol isn't purging alcohol from you.. I think. testing soon.
Tested with beepsky smash and neurotoxin ;)

**Comment by PKPenguin321** [comment]
I don't think it purges alcohol, does it? As far as I'm aware it just removed or reset your drunkenness.

**Comment by Iamgoofball** [comment]
It's supposed to purge booze like calomel does, I'll check it

**Comment by XDTM** [comment]
Should purge 3 per tick, not instantly

**Comment by nullbear** [comment]
It removes your drunkenness and dizziness instantly. But should purge alcohol over time. IIRC

**Comment by kevinz000** [comment]
Ah crap, purge 3 per ticks, but I'm not sure even that works. Let me just test.
