### ISSUE TITLE
You can pick up metal/glass as a creature with no hands.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#20556]
I was able to pick up metal and glass sheets by splitting the stacks as a morph, obviously you're not supposed to be able to do that.

**Comment by phil235** [comment]
Two bugs in one: there should be a check to see if we can split a stack (check if we have hands or something), and then there's put_in_hands() who somehow works for animals even when they don't have hands.

**Comment by Jalleo** [comment]
This is linked to the ghost altclick issue. I shall link in just a moment

**Comment by Shadowlight213** [comment]
More bugs caused by multihands wew.

**Comment by RemieRichards** [comment]
@Shadowlight213 you try removing all the two-hand assumptions from a codebase more than 10 years old and not cause any issues.

**Comment by Shadowlight213** [comment]
@RemieRichards
>not being able to do that in your sleep

And you call yourself a coder :hooray:
:P

**Comment by Shadowlight213** [comment]
I'm not shitflinging.

**Comment by Jordie0608** [comment]
http://people.howstuffworks.com/sarcasm.htm

**Comment by lzimann** [comment]
This got fixed somewhere(alt clicking sheets now have a dexterity check).
