### ISSUE TITLE
Revheads can not spawn correctly and instantly end the round

### ISSUE THREAD

**Issue by BrokenCycle** [tgstation/tgstation#20554]
I saw my objective, did not enter the map, and the round instantaneously ended. According to Cobby, the server glitch half-spawned me in the lobby. I didn't even have a mob.

**Comment by PKPenguin321** [comment]
Maybe a symptom of https://github.com/tgstation/tgstation/issues/14469 ?

**Comment by BrokenCycle** [comment]
Wish I hit the join button fast enough, then I could've been a CMO revhead or something.

**Comment by Shadowlight213** [comment]
Should be fixed by #20950
