### ISSUE TITLE
Clicking follow character links from chat results in client going unresponsive

### ISSUE THREAD

**Issue by nero1024** [tgstation/tgstation#20564]
Clicking on the "(F)" in front of the character name in the chat when as a ghost results in the Byond Dream Seeker client going unresponsive, audio still plays for some reason. This forces me to end-task Dream Seeker. This also happens when clicking on certain links in the chat, probably for ingame stuff.

Byond version 510.1347 (latest Stable)
OS is Windows 10 32-bit

**Comment by nero1024** [comment]
I've yet to check this latest beta

**Comment by nero1024** [comment]
After running this with the latest beta of Byond, 511.1357. I notice that the "(F)" follow thing seems work normally when SS13 justs starts, up until the chat starts getting a lot of text where the game starts freezing for a second or two. If you click on the follow link when chat log is huge is when SS13 becomes an unresponsive mess. The game seems to return to normal if you click outside of the chat window before it goes unresponsive.

**Comment by evsey9** [comment]
Same thing with AI

**Comment by Shapsy** [comment]
This has been a thing for a long time, I was getting the same thing in my laptop like a year ago (and still do), it's with all chat links which makes adminning a royal pain in the ass as well

**Comment by optimumtact** [comment]
have you tried turning it off and on again?

**Comment by Jalleo** [comment]
Its more the beta fixes it SOMEHOW so probably byond issue fixed tags required.

**Comment by nero1024** [comment]
@Jalleo The client still likes to go unresponsive even on the latest beta though. It likely has something to do with how big the chat log gets, and I remember this happening on other Byond versions like 509 as well.

I'm in also in agreement that this might be a Byond issue as I've had this happen on other flavors of SS13 like Polaris and whatever /vg/ uses.

**Comment by Jalleo** [comment]
Probably best to report it to the Byond bug reports section and see if Lummox knows of this issue.

**Comment by nero1024** [comment]
There's apparently a post on this issue in Byond's bug reports forum: http://www.byond.com/forum/?post=2082440

The last post was in late June until I necro'd it, and apprently Lummox isn't exactly sure what's causing it.

**Comment by optimumtact** [comment]
I suspect this and #26688 are semi related

**Comment by Cyberboss** [comment]
Goonchat actually fixes this for me, hopefully it's a workaround

**Comment by ShizCalev** [comment]
If that's the case, will close in a week without another repo.
