### ISSUE TITLE
Posters placed can print a square above/below where they were supposed to be placed

### ISSUE THREAD

**Issue by MrAlphonzo** [tgstation/tgstation#20579]
An issue that may be exclusive to Meta/Meta Maintenance, but an issue nontheless. Several attempts placing a poster resulted in them being placed above or below the wall, depending on where I was standing in relation to the wall.

**Comment by Niknakflak** [comment]
Sort of kind of a bug.  Its because they are mapped with a pixel_x or pixel_y changed which doesnt reset and carries over if the posters are snipped from the wall and placed elsewhere

**Comment by Mervill** [comment]
Duplicate of #13430
