### ISSUE TITLE
How should the gamemode role distribution and the configs look.

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#20588]

**Comment by AnturK** [comment]
I'd like to see simple json files with a list  "role - weight " grouped by pop restrictions ? Might be too limiting.

**Comment by MrStonedOne** [comment]
Json files are not easy nor intuitive to edit by humans, and don't support comments.

**Comment by MrStonedOne** [comment]
Look at the maps.txt rotation config for a good example of flexible sectioned configs.

**Comment by AnturK** [comment]
Yeah, json might not be the best fit given these would be would probably be edit pretty often, it will be more or less flat anyway.

**Comment by KorPhaeron** [comment]
Leave discussion for datum antags on the currently open PR please
