### ISSUE TITLE
Tesla coils degrade arcs even if they're not TAKING ANY POWER INTO THE GRID

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#20585]
Tesla coils will at the very least halve all tesla bolt power before passing it on, even if they're not connected to wires to pass it into.
1. FIRST LAW OF THERMODYNAMICS
2. So you're telling me that with explosive tesla blowing all other machines up and tesla coils draining so much power when they don't need it I can't conduct a bolt across the station into the captain's office to recreate the sybil round where a captain got shocked with a tesla bolt when he walked into his office? ;-;

**Comment by Supermichael777** [comment]
space magic

**Comment by kevinz000** [comment]
reddit downthumbing you wew

**Comment by nullbear** [comment]
doesn't this make sense though?
