### ISSUE TITLE
What should the antag datum handle

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#20586]

**Comment by ChangelingRain** [comment]
Innate ability assignment/removal(changeling, cults), handling stuff on mind transfer(including ability reassignment if needed), antag HUD updates, storing any vars specifically used by the antag(changeling, also devil I think)

**Comment by AnturK** [comment]
- Admin panels
- Objective tracking per role not per mind  ?

**Comment by ChangelingRain** [comment]
Should blobs actually HAVE an antag datum? I'm wildly unsure if they actually need or could get any use out of one.

**Comment by AnturK** [comment]
We'd have to add some section for "natural" antagonists like aliens/player animals etc to check antags panel but yeah blob doesn't really have much use and honestly blob as could be shunted completely to events without anything of value lost (aka blob mode is mediocre)

**Comment by ChangelingRain** [comment]
The main reason I'm asking is that blob(and hod gods, I guess, but fuck if I'm going to support those) is the only antag that isn't a `/mob/living` subtype. 

Incidentally, with #20591 any mob-bound antag would just have an antag datum that'd call `be_removed()` in `transfer_to_new_body(mob/new_body)` instead of transferring, which feeeeels like the right way to go about it.

**Comment by lordpidey** [comment]
Devil already has a /datum/devilinfo/ that handles a lot of the devil related code, and mind has a var to hold one instance of devilinfo.  There is also a var/global/list/allDevils, which contains an array of all devilinfos, including nonexistant devils (If you lookup the wrong devil in the codex gigas, it produces a fake randomized entry, and that same entry will show if you research the same non-existant devil)

**Comment by KorPhaeron** [comment]
Leave discussion for datum antags on the currently open PR please
