### ISSUE TITLE
Weather datums are added to the list in two different locations

### ISSUE THREAD

**Issue by CyberbossJHCB** [tgstation/tgstation#20594]
See 
https://github.com/tgstation/tgstation/blob/master/code/controllers/subsystem/weather.dm#L36-L38
`existing_weather |= new W`
and
https://github.com/tgstation/tgstation/blob/master/code/datums/weather/weather.dm#L45
`SSweather.existing_weather |= src`

Mainly just a maintainability issue methinks, just wondering weather (kek) or not it was intentional

**Comment by Incoming5643** [comment]
Since it's a |= I think this is just a redundant thing, but there might be some reason why it's like this.

@KorPhaeron

**Comment by KorPhaeron** [comment]
@Xhuis 

Rewrote weather

**Comment by Xhuis** [comment]
@CyberbossJHCB u lil bitch dont u fkin make puns bout my code like that
Anyways, yeah. Mistake on my part. It isn't actually a problem and will have no effect, although I'll admit it's messy. I'll cut it out when I can.
