### ISSUE TITLE
Syndicate operative reinforcements, syndicate cyborgs, blobs grab ghosts without popop

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#20593]
Given that I introduced "WOULD YOU LIKE TO PLAY AS A GIANT SPIDER" messages for all other ghost roles, we might as well go the whole hog and finish them off.

Because nothings more annoying than observing idly while talking in #coderbus before suddenly being dragged into existence as a syndiborg.

**Comment by Jalleo** [comment]
We currently have bugs with some of the ghost pop up ones.

**Comment by optimumtact** [comment]
It's a pain in the ass to rewrite this shit which is why I only did spiders

it really needs a proper system and clean documentation on how to poll for new antags.
