### ISSUE TITLE
Neurotoxin drink is not a path of alcoholics

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#20604]
Why. It's a drink.

**Comment by PKPenguin321** [comment]
We have two neurotoxins, one the actual chemical and one the booze, are you looking at the right one?

**Comment by XDTM** [comment]
He is, apparently neurotoxin, atomic bomb, pan-galactic and hippie's delight are not childs of ethanol like normal drinks. Which means they get special drunk effects instead of the classic one and more importantly are not purged by antihol.
