### ISSUE TITLE
JOB TIME RESTRICTIONS

### ISSUE THREAD

**Issue by Saegrimr** [tgstation/tgstation#20606]
For the love of fuck please fix this bullshit, we have goddamn idiots with 10 connections running around as head of security doing absolutely dumb shit because they don't even understand the basics of the game.

**Comment by BeeSting12** [comment]
It might be a better idea to base job restrictions on connections rather than how many days since you joined the server.

**Comment by Iamgoofball** [comment]
PEBKAC.

Check with your local headmin in the configs.

**Comment by Ergovisavi** [comment]
>There's still no whitelist for HoS/Captain

**Comment by Jalleo** [comment]
@Cheridan wont support a whitelist and I dont know if @Mrstonedone would be willing to do a literal time on server based blacklist.

**Comment by Shadowlight213** [comment]
It's NOT days since joined the server.
@KorPhaeron asked me to make an option to have it be days since byond account creation. He had job restriction timers completely turned off before. Not sure if he turned on the new one or if it's still turned off completely.

**Comment by KorPhaeron** [comment]
@Shadowlight213 

I think the config comment might need to be updated to be a bit clearer, didnt realize you had to have the original config on and the second config to edit it, rather than just picking one.

There is no bug though
