### ISSUE TITLE
Weird defib paddle glitch.

### ISSUE THREAD

**Issue by FIXTHERADBOXPLEASE** [tgstation/tgstation#20602]
Some guy was holding unwielded defib paddles in his hand when he walked into some lava from a lava staff and died on it. The paddles showed up on the lava, I picked up the paddles, and got usable defib paddles attached to my dude's hand. I couldn't drop the paddles, or put them in another defib, or anything like that.

Also, when I picked up the paddles, there was still another unwielded defib paddle on the lava.

**Comment by phil235** [comment]
likely a dupe.

**Comment by kriskog** [comment]
Can't reproduce. The paddles will actually burn and make the defib forever unusable but thats for another issue.
