### ISSUE TITLE
Enchanced view range leaves smaller crit overlay

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#20618]
![crit](http://i.imgur.com/VnEcszU.png)

**Comment by optimumtact** [comment]
Solution, dont' be an admin

**Comment by Shadowlight213** [comment]
@optimumtact This was a screenshot by a player.
The devil knowledge contract gives you xray and increased view rage.

**Comment by optimumtact** [comment]
solution, don't use the devil knowledge contract

**Comment by Jalleo** [comment]
Can be solved via using client methods too apparently.

**Comment by Iamgoofball** [comment]
we should not be allowing increased view ranges for players

**Comment by optimumtact** [comment]
Your comment is too late now goof

**Comment by MrPerson** [comment]
The solution is to remove the extra view range from players.

**Comment by PKPenguin321** [comment]
Remove enhanced view range memes
