### ISSUE TITLE
Having no legs means you can't use your arms??

### ISSUE THREAD

**Issue by Cheridan** [tgstation/tgstation#20619]
> Get both legs chopped off
> Can't pick up anything at all
> Anything you try to get out of your backpack or inventory slots immediately drops to the ground

Holy shit I get the whole "you crawl on your hands and knees" thing but realistically I'd be able to stop crawling in order to do things with _the two arms I still have._ 

Having no legs is worse than just having no arms, since you can still run around fast. No legs is the same thing but with slowdown.

Reeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.

**Comment by Shadowlight213** [comment]
@phil235 i guess?

**Comment by optimumtact** [comment]
That's what I said!

**Comment by Ergovisavi** [comment]
I genuinely would prefer this to the alternative of being able to hold things while you're on the ground, as that just confuses visual combat states. If you're on the ground, you should be incapable of meaningful action, at least in regards to combat actions.

**Comment by JJRcop** [comment]
How about, if you stand still for a second, you flip upright and can then use your hands.

**Comment by ChangelingRain** [comment]
Yeah this is super awful design just in general. Having no legs shouldn't automatically also make you unable to hold stuff as though you had literally no limbs.
Maybe do something like skateboards and have legless people be 'upright' but very low to the ground?

**Comment by phil235** [comment]
I don't care either way tbh.

**Comment by Jalleo** [comment]
This is already reported @Cheridan
