### ISSUE TITLE
Dron heal has no range check after its Doafter

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#20611]
so a drone can heal after running form it healer

**Comment by xxalpha** [comment]
Don't the do_after and the do_mob procs already handle this?

**Comment by Supermichael777** [comment]
aparently not

**Comment by xxalpha** [comment]
Apparently the bug is not this?

**Comment by Jalleo** [comment]
A lot of snowflake checks can probably be removed if the do after checked for things were correct or not.

**Comment by optimumtact** [comment]
do_after is not the kitchen sink for you to shove your validity checks in

**Comment by xxalpha** [comment]
It is already supposed to return false if you fail a distance check.

**Comment by ChangelingRain** [comment]
do_after DOES check, who even said it doesn't???
