### ISSUE TITLE
CMO cloak doesn't accept penlight in suit storage slot

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#20625]
!?!?!?!?

**Comment by TechnoAlchemisto** [comment]
sounds LIKE A FEATURE REQUEST TO ME

**Comment by TechnoAlchemisto** [comment]
the cloaks can only hold the key job specific items hypospray/gun/rped-rpd etc etc

**Comment by optimumtact** [comment]
indeed, technically not a bug and should go in the feedback forum
