### ISSUE TITLE
AI carding doesn't work

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/tgstation#20653]
when you're carded your view is locked to wherever you were looking when carded, not where you actually are.

also happens if you are transferred into a mech.

**Comment by GunHog** [comment]
Did you try the "Return to core" button?

**Comment by Cebasiz** [comment]
yes, it's busted, seems to happen no matter what you're transferred into, card or mech. only works when you're transferred back into core again.

**Comment by optimumtact** [comment]
Confirmed, had this happen to me too.

**Comment by phil235** [comment]
Not using forceMove() to place the AI in its new loc.

https://github.com/tgstation/tgstation/blob/60af397dce859472980ffdc19c84005a5a796bb9/code/game/mecha/mecha.dm#L641

https://github.com/tgstation/tgstation/blob/7b2a1b6aa7568eb20a86ba2c9107f2cb3dedc0db/code/game/objects/structures/ai_core.dm#L243

https://github.com/tgstation/tgstation/blob/60af397dce859472980ffdc19c84005a5a796bb9/code/modules/mob/living/silicon/ai/ai.dm#L762
