### ISSUE TITLE
You still slip on ice with magboots

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#20660]
This isn't realistic as the magnetic properties of magboots should be holding you to the floor, not gravity. Friction shouldn't be taken into account here as ice isn't Space Lube, and sliding around on ice should have some kind of decent counter other then crowbarring (which goof wants to remove anyway)

**Comment by yackemflam** [comment]
No, slipping on ice even with magnets still makes sense.
Just imagine yourself on the floor with bottom of your feet still touching the floor. :honk:

**Comment by YakumoChen** [comment]
but the boots would realistically clamp your feet to the floor

**Comment by Iamgoofball** [comment]
realism doesn't matter, this is a gameplay element

also where did I say I wanted to remove crowbarring to remove ice, stop putting words in my mouth

**Comment by optimumtact** [comment]
This isn't a bug it's a balance/consistency issue. please report on the forums
