### ISSUE TITLE
The shovel has no reason to exist.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#20675]
A pickaxe does its job entirely. Why do we even have shovels? Can we at least give them a significant advantage at shoveling over a pickaxe's job?

**Comment by phil235** [comment]
You can dig sand with a pickaxe? I thought you couldn't.

**Comment by erwgd** [comment]
Pickaxe digging was added some time ago. Compact pickaxes also make the shovel less useful than it was in the past.
I'd consider making the digspeed a faster value and I'd definitely increase the force of the shovel to at least 9. Maybe make it easier to carry by making it collapsible into a small but less robust item.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm assuming it would also be possible to code it in a way that you could obtain more ash when using the shovel.

**Comment by WJohn** [comment]
Yeah, make it significantly faster than basically any other tool, and also gets you more ash per tile you dig. That'd be a little more worthwhile if miners *ever* felt like digging up ash.

**Comment by ExcessiveUseOfCobblestone** [comment]
this would also band-aid fix gulag mining drops since you can just get more glass in bulk.

**Comment by KorPhaeron** [comment]
Balance, not a bug
