### ISSUE TITLE
flask inside detective hat cannot be removed

### ISSUE THREAD

**Issue by phil235** [tgstation/tgstation#20676]
the detective hat starts with a  flask in it. The flask is inside the hat's pocket codewise, but it doesn't appear in the storage slot when clicking the hat.

@Core0verload

**Comment by MimicFaux** [comment]
Might be related to other similar pocket-clothing like the clown mask and shoes, which also can't have things removed from them.

**Comment by Iamgoofball** [comment]
@Cheridan disabled the pockets

**Comment by Core0verload** [comment]
use clickdrag, like with stroages on the ground

**Comment by phil235** [comment]
@Core0verload So when I click the hat, it shows a storage slot with nothing in it, but if I clickdrag from the worn hat to my mob (something that no other storage item requires when worn) then the storage slot appears and shows the content.
Please fix this.

**Comment by Core0verload** [comment]
Weird. I tested it more than once, any preinserted item was `layer`ed and `screen_loc`ed on first storage open. Did anyone changed storage behavior?

**Comment by Mervill** [comment]
@optimumtact closeable (#22268)
