### ISSUE TITLE
As test local host admin - cant use "player panel" to spawn or change character.

### ISSUE THREAD

**Issue by cookins** [tgstation/tgstation#20695]
Hi
i want to try to play abductor, never tried, so i created local test server to try it. but as host - i can do many things on server, i launched tg station, last one, and cant spawn some player or heal some mob, etc. how that happening? well can fire blue artillery, can gib something, like acting as host and many, many!
BUT, when using player panel - cant do anything - what i not pressing there, heal not working... transform to other mob class not working - it just npt respond and nothing happens after click! can somebody explain me why?last time i tried test server its about 4 years back - all was fine. maybe they changed something? same in antag panel - nothing happens. im sure that i have all priv on server!

**Comment by nullbear** [comment]
abudctors despawn without a proper mind iirc. 

Your best solution is to multikey.

**Comment by cookins** [comment]
nvm.. it looks like i fugured out what was problem....
how many ghosts need to be to start abductor event?

**Comment by cookins** [comment]
and tell me how to "multikey"?

**Comment by JJRcop** [comment]
Multikey means logging in to multuple accounts, via: 
1. Joining the game
2. Logging out
3. Logging in to another BYOND account
4. Repeat from step 1 until done

**Comment by Jordie0608** [comment]
You can also log in as a guest to a local server to do it.
