### ISSUE TITLE
Ministation uplink config actually decreases telecrystal cost of weapons that promote murderboning

### ISSUE THREAD

**Issue by ma44** [tgstation/tgstation#20699]
https://github.com/tgstation/tgstation/blob/35bfb9abb6d3e7952d14a1781c9ffc3a68d2df00/_maps/map_files/MiniStation/uplink_item.dm
Source

In ministation, the TC cost of murderboning weapons should be increased so no one runs around with weapons killing everyone. Unfortunately, the prices are outdated and actually makes the cost of the murderboning items decrease. 

**Esword**
Original: 8 TC
Ministation: 7 TC

**Revolver .357**
Original: 13 TC
Ministation: 10 Tc

**Singularity beacon** (pretty sure ministation doesn't have a sing)
Original: 14 TC
Ministation: 4 TC

**Mini Energy Crossbow**
Original: 10 TC
Ministation: 7 TC

**Syndicate minibomb grenade**
Original: 6 TC
Ministation: 6 TC (unchanged)

**Comment by PKPenguin321** [comment]
Looks like they weren't updated when traitor TC was made to 20

**Comment by Giacom** [comment]
I could remove the file and the special price changes.

I don't think anyone will bother updating and balancing it so it might as well just have the standard pricing.
