### ISSUE TITLE
safe lacks adjacency checks

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#20705]
The big blue safe in the vault that you need a stethoscope to open lacks adjacency checks on opening/closing the door and increasing/decreasing the dial. Taking items from it DOES seem to have adjacency checks, however.

How to reproduce:
1. Open the safe in the vault (have fun)
2. Open the safe menu
3. Walk away from the safe
4. Open/close the safe via the safe menu
5. Notice that the safe opens/closes despite you not being near it
6. Increase/decrease the value on the dial
7. Click on the safe again to update the safe menu
8. Notice the number increase/decrease corresponding to the amount of times you clicked

Also as a side note the safe UI is really outdated and could use a touchup

**Comment by Mervill** [comment]
How to quickly badmin hack the safe:
- View Variables
- Filter for `tumbler_`
- Make `tumbler_1_pos` equal `tumbler_1_open`
- Same for `tumbler_2_*`
- Open the safe
