### ISSUE TITLE
Any human mob can be forced to become a traitor

### ISSUE THREAD

**Issue by Chnkr** [tgstation/tgstation#20716]
The `betraitor` topic call on the [Syndicate Beacon](https://github.com/tgstation/tgstation/blob/master/code/game/machinery/syndicatebeacon.dm) can be abused to force any human mob in the game to become a traitor.

```dm
/obj/machinery/syndicate_beacon/Topic(href, href_list)
        if(..())
                return
        if(href_list["betraitor"])
                if(charges < 1)
                        src.updateUsrDialog()
                        return
                var/mob/M = locate(href_list["traitormob"])
```

**Comment by ChangelingRain** [comment]
Does that actually require the beacon? Hmm. Anyway this thing isn't actually used anywhere so I'm going to do the much more easy fix.
