### ISSUE TITLE
Chairs that have been picked up and placed back down can only be rotated left or right.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#20728]
If you pick up a chair (click drag onto yourself), then place it back down where it isn't on its side (use it in your active hand), it will be forcibly locked into left or right directions. Attempting to rotate it will only swap between those, with an inbetween rotate attempt that does nothing.

**Comment by PKPenguin321** [comment]
This happened to me once with an emitter for seemingly no reason
