### ISSUE TITLE
Characters with NOHUNGER still get hungry after a while

### ISSUE THREAD

**Issue by erwgd** [tgstation/tgstation#20725]
Currently, characters who shouldn't become hungry will still hunger, just at a later time.
Example: At around 13:08 station time I noticed that my plasmaman character has the hunger warning.
![Screencap of tgstation on the Sybil server. The game window shows my plasmaman character and the hunger warning](https://i1.someimage.com/Eb5cfE9.png)
Back when hunger was disabled for humans due to a bug that was fixed in tgstation/tgstation/pull/16076, my human character still became hungry in long rounds.

Revision unknown, but this issue seems to be around since 14 March 2016, when NOHUNGER actually started working (though not 100%).

**Comment by XDTM** [comment]
Seems that walking removes nutrition regardless of NOHUNGER
