### ISSUE TITLE
Particular space ruin turfs are gravity/friction-less

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#20730]
Some of the space ruin turfs, including and not limited to the syndicate vs pirate fleet ruin and the bunker ruin, including some others with relevant "Asteroid Sand" assets do not have the friction and gravity. Players who visit these sites have to cling closely to the walls in order to not drift off or become marooned in awkward spaces should they draw to a halt, the floor may as well not exist and this could be because unlike the former mining asteroid, its bottom-most supporting structural turf is not plating.

Speculatively this is a oversight, and makes navigating and exploring these ruins (some which are deliberately made to be explored) difficult, and also difficult to colonize and build upon, other relevant ruins like the space bar use the same turf assets but have no issues, indicating that its all the same work of a singular mapper or old content.

Most of them appear to be taken directly from away missions in design, one such ruin has no content whatsoever besides from a room where a mech would usually be housed which now lies empty in equally gravity and friction-less space.

![frictionless turf asteroid example](https://cloud.githubusercontent.com/assets/18471896/18893074/33180192-8504-11e6-8b9e-e36965c95bde.png)

Picture relates to the entrance to the bunker ruin, which is affected by the said issue problem.

To replicate - load up a random assortment of ruins relevant to this issue by starting/restarting rounds, manifesting from observer mode and double clicking between space level planes also helps, from there with administrative tools you can manifest your person and experience the gravity loss for yourself. Alternatively float away in a space suit from the station in space until you encounter one.

**Comment by WJohn** [comment]
Likely just due to the areas not having their has_gravity set to 1. Super easy to fix. Go in dreammaker, change the value of one of those tile's area to 1, replace the whole area with that.

**Comment by MMMiracles** [comment]
As the creator of the syndicate v. pirate ruin, lack of gravity is completely intentional. Why would a bunch of disabled ships and small bits of asteroid debris have gravity to keep you grounded?

I'd also imagine most ruins involving small wrecked shuttles/small asteroid chunks are left gravity-less on purpose for the same reason stated above.

**Comment by WJohn** [comment]
Well in that case.

**Comment by FantasticFwoosh** [comment]
I challenge MMImiracles case, he put down crates upon the asteroid turfs definitely intended to be stood upon in order to access the loot. Also this blanket closure is unfair due to lots of other ruins MMImiracles may not be associated with not having the proper turfing whether it was intentional or not, items are being placed down on asteroids but not subject to proper gravity checks or in some cases not even being adjacent to a sufficient surface (such as a rock wall).

Im aware this may sound accusational but MMImiracles's logic doesn't hold up or hasn't accounted to the functionality of his work or map design before application drawing upon the unlockable crate example. The bunker example and even random rocks in space are also experiencing the same issues but has been nullified by this blanket closure by WJohn, in which case i will make separate issue of them.
