### ISSUE TITLE
Wizard apprentices and TC bought syndicates spawn naked, spellless, and comatose

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#20746]
Something is breaking very early in apprentice creation code. Someone didn't test their coooooode.

**Comment by AnturK** [comment]
Possibly #20612 @ChangelingRain ?

**Comment by ChangelingRain** [comment]
I'd expect that to be it but I can't imagine how, exactly.

**Comment by Incoming5643** [comment]
Wild gues, might have to do with the code trying to assign spells to a mindless mob.

**Comment by Incoming5643** [comment]
The problem is growing

**Comment by KorPhaeron** [comment]
Joan trying to break every mode but clockcult
