### ISSUE TITLE
Escape Pods can land within necropolis walls, which cannot be pickaxe'd through.

### ISSUE THREAD

**Issue by ChemicalRascal** [tgstation/tgstation#20743]
In short: http://puu.sh/rrhpO/e3ee072d62.png

Not sure if this is intended or not, I'd argue it's a bad thing given that pickaxes are provided (and thus it seems the escape pods were designed so that folks at least had _some_ measure of a chance to get to the mining base).

**Comment by PKPenguin321** [comment]
this may be a dupe

**Comment by ChemicalRascal** [comment]
Eh, I didn't find anything open. I know this has been an issue in the past, though, with pods spawning in the old walls.
