### ISSUE TITLE
The gas tiles in atmospherics are suddenly much less full of gas

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#20757]
I'm not sure if the atmos gas tiles were actually infinite sources of gas or simply extremely large, but suddenly there's only a very small amount in the tiles to start, and no more after that. Saw a round where they literally ran out of plasma to burn.

**Comment by MrStonedOne** [comment]
What map was this on, because on box i just checked, each tile of the plasma tank has 69888.7 moles (canisters come with 200)

**Comment by Incoming5643** [comment]
It was box, so maybe the ""bug"" isn't so much that the gas is less, rather than the loss of gas between space tiles and gas tiles is much faster. I just know historically that puncturing the plasma tank so there's a one tile opening to space didn't use to really affect whether or not plasma was available for use, but now it's actually practical to vent all the plasma/grief gas of choice to space in a fairly timely manner.

**Comment by Cyberboss** [comment]
@lzimann
