### ISSUE TITLE
Dismemberment bug; arm unusuable after reattachment

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/tgstation#20759]
Arm was cut off by energy sword in 1 hit.
Went to get arm reattached.
Arm was reattached.
Arm couldn't be used.
Apparently something was nulled.

![lifeweb journey to vape city 2016-09-29 221733](https://cloud.githubusercontent.com/assets/13142400/18973575/14550456-8696-11e6-8af7-0ae7f94c8c2d.png)

**Comment by PKPenguin321** [comment]
Probably a dupe

**Comment by phil235** [comment]
yep

**Comment by AnturK** [comment]
Dupe of #20457
