### ISSUE TITLE
Testing new map... map making questions.

### ISSUE THREAD

**Issue by cookins** [tgstation/tgstation#20764]
hi again!
i making map for testing purposes...
im have couple questions - if anybody knows:
1. I playing map and made some new objects and placed it (by construction) - its walls, consoles, tables, etc. How to save map that already played - so all this stuff saved, which placed? it sounds strange, but i playing sometimes only with couple freinds and need to do everything each round. its kinda really cool cab be for me!
2. how to make in dream maker usual sand (asteroid sand - in plating) undestructable? i mean it can be damaged - like everything, but cant be penetrated to space! idea in making like surface of planet.
3. if i changing ID of object, example conveoyr switch in cargo - its "Cargo1" and controlling conveyor same named. so i have second conveyor ID "Cargo2", so i changing it IC via admin (view variables) to "Cargo2", so it control now other "Cargo2" switches, but "Cargo2" conveyor not moving......  and still only "Cargo1" conveyor is switching.... can it change to in "live" game or need to restart server. so its changed normally and not switch "Cargo1" without changes?

**Comment by phil235** [comment]
You should probably ask your questions on the forum instead of here (but it's currently down for maintenance, it'll probably be back in less than 24hrs)

**Comment by cookins** [comment]
ok ty

**Comment by nullbear** [comment]
1. We don't currently have map-saving abilities for changes to the map made in-game.

2. You might be thinking about changing the baseturf of the tile to a non-space tile. Or alternatively overriding the ex_act proc in the turf's code.

3. Conveyor systems can be re-linked in-game without admin commands by pry-ing up the conveyors, and attacking them individually with the switch(es) that you want to link them to.

4. Sorry, phil.
