### ISSUE TITLE
Newb question about atmos

### ISSUE THREAD

**Issue by cookins** [tgstation/tgstation#20765]
and guess who here!
i came about to ask - newb question:
i dont get it one thing in whole game - from where oxygen taking IC?
i know that there already canisters with it and there mix in station of o2 and nitrogen - air!
but how air or oxygen, whatever - generated? is it can be produced from botany? just curious what other methods, maybe - to GENERATE it, not taking it from stores.

**Comment by PKPenguin321** [comment]
I think there are a handful of methods. Plasmamen exhale air iirc, mechs get an air canister when they are built, oxygen canisters can be ordered from cargo.

Not a bug btw

**Comment by F-OS** [comment]
the github is for bugs with the game, not feature requests as pk penguin said, try the wiki or forums.
