### ISSUE TITLE
Gateway to celestial derelict doesn't stop the shuttle from leaving

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#20777]
Shuttle had docked and the clock cult managed to start the gateway countdown, however when the timer for the shuttle reached 0, it left instead of having a hostile enviroment, cucking over the cult because the round ended before ratvar could emerge.

@ChangelingRain

**Comment by ChangelingRain** [comment]
This is not a bug xhuis did it intentionally
I'm not sure I totally agree with that design decision, though.

**Comment by KorPhaeron** [comment]
Well, you can make a PR about it or something then
