### ISSUE TITLE
Miscellaneous features of interest that rely on gamemode code

### ISSUE THREAD

**Issue by JJRcop** [tgstation/tgstation#20776]
This issue is intended as a discussion to be added to the Datum Antags project, but as I am not a team member, I can't add it myself, and can only request it to be added.

Just want to pick up some things that aren't directly a part of any of the gamemodes on their own, but that rely on the current gamemode system in order to function.

**Comment by Shadowlight213** [comment]
Does this apply to everything that jhst checks if someone is an antag?

**Comment by JJRcop** [comment]
Yes, just not things that are directly a part of an antag's normal arsenal. Like, maybe a non-related item to wizard has a certain effect if it's being used by or on a wizard, but it's not in the spellbook and you can get it outside of wizard.

If you could only get such an item during a wizard round, it would be considered part of the wizard gamemode and wouldn't count for this discussion.

**Comment by AnturK** [comment]
Well, baseline for me is the less restrictions the better. Items should be constrained by arbitrary meta information like mode as little as possible. Not yet at the point where i start on converting these though.

**Comment by KorPhaeron** [comment]
Leave discussion for datum antags on the currently open PR please
