### ISSUE TITLE
[Feature Request] Let ghost medhuds see hidden diseases

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#20783]
There's no real reason to hide diseases from ghosts, so it would be nice if it could see stuff that has the HIDDEN_SCANNER and/or HIDDEN_PANDEMIC flags.
Also, being able to examine as a ghost and get medscanner info with the hud on would be nice, similar to how examining a blob gives you that info.

**Comment by phil235** [comment]
feature request
