### ISSUE TITLE
Big halting lag in the ticker

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#20785]
Since some time yesterday there's been a sporadic but intense lag that locks up the ticker, not in a way that the DEFCON system catches, but rather ticks seems to just stop happening for a period of time, leaving things that don't require the ticker to play in the meantime.

My guess is a sleep somewhere it shouldn't be. Again according to the playerbase this lag only manifested yesterday, so we're talking code that was merged no sooner than the 29th

**Comment by Incoming5643** [comment]
Primary testing suggests it's something in/related to air subsystem

**Comment by Incoming5643** [comment]
lag has happened with air off, but doesn't seem to happen as much

**Comment by Incoming5643** [comment]
might be server side, somehow

**Comment by Jordie0608** [comment]
Run a profile, that'll be much more helpful.

**Comment by Incoming5643** [comment]
I did, nothing seemed odd. Seems to have resolved. Probably server? Will reopen if it reappears.
