### ISSUE TITLE
Blood cult is entirely fucked

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#20781]
Blood cult now also gives people ratvar cult, and makes them unable to use either tome or slab. Not sure if this was a unique round, but it got so bad I had to just end it.

**Comment by phil235** [comment]
Linked to  #20591 maybe?

**Comment by ChangelingRain** [comment]
I really wish people would give me all possible info, like how many goddamn buttons the admins pressed. I'll probably have a fix up relatively shortly, but still.
