### ISSUE TITLE
Handheld crew monitor doesnt close on round end

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#20782]
Also the regular 'X' button stops responding, you have to minimize it and then use the Windows 'X' button

**Comment by Shadowlight213** [comment]
Wait, does it still show people with sensors or something?
Windows not closing on round end is like that for a number of admin windows I know.

**Comment by CyberbossJHCB** [comment]
Never kept it open that long, I'll update next time I play doc
