### ISSUE TITLE
You can only add reagents to vapes with glass beakers

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#20798]
Can't use other reagent containers like coffee cups, etc.
Extremely counter-intuitive

**Comment by CyberbossJHCB** [comment]
Well, I'm no VNer so help me out. What kinds of things should be able to fill them?

**Comment by PKPenguin321** [comment]
ideally any open reagent container, IE bottles from the bar, bottles from chemistry, soda cans, coffee cups, ramen cups, etc

**Comment by BrokenCycle** [comment]
Same case with dipping cigarettes. Can't do it inside of a drinking glass/shot glass/etc. Only beakers.
