### ISSUE TITLE
Ninjas can get non-Crewmembers as objectives

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#20792]
![image](https://cloud.githubusercontent.com/assets/12382984/19019171/d5f37d74-8874-11e6-936d-7c64dac9f9bf.png)
Might need to add some checks for that, I'd also advise going over the other antags to keep this weirdness from happening.

**Comment by Shadowlight213** [comment]
I thought there was a pr that made only people on the crew manifest eligible for assassination targets?
Or does ninja not use that?

**Comment by Anonmare** [comment]
I don't think Ninjas got included in that PR. They usually get _forgotten_ quite often.

**Comment by AnturK** [comment]
Because of course ninja uses snowflake target selection. Sigh.
https://github.com/tgstation/tgstation/blob/master/code/modules/ninja/ninja_event.dm#L67

**Comment by Anonmare** [comment]
Honestly Ninja code needs a lot of review, even the items it starts with are a little odd (*coughNVGsandFlashlight*cough*)*.

**Comment by ShizCalev** [comment]
The code now lives here, for reference;
https://github.com/tgstation/tgstation/blob/4c46a0e2e71a91e1ad91740b1ab9db88b6068f12/code/datums/antagonists/ninja.dm#L29

**Comment by Anonmare** [comment]
I'm 99% sure this is fixed now
