### ISSUE TITLE
Syndi minibomb has no sprite in evidence bag

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#20795]
Trying to place a syndi minibomb in an evidence bag causes it to "disappear" sprite wise. The bag appears empty though the VV shows its actually in the bag.

See attached pic:
http://puu.sh/rvhHa/d39feea625.png

This happens when doing it in hand. Happened on Basil, by a sec officer.

**Comment by phil235** [comment]
can't reproduce. It's most likely an issue with overlays getting deleted somehow, did you reproduce the bug yourself? What happened to the evidence bag itself prior to the bug?
