### ISSUE TITLE
Chemgrenade's contents can't be examined with Googles/Reagent scanner

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#20827]
Says "No active reagents." If this is a balance thing, it should at least say "The scanner can't detect the contents of the grenade."

**Comment by nullbear** [comment]
the grenade doesnt actually have any reagents. The reagents are in the beakers inside the grenade. This is an oversight.

**Comment by GunHog** [comment]
Cannot scan syringes either
