### ISSUE TITLE
Bombs can be dodged

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#20820]
By dodge, I mean move onto a tile that has exploded and off the tile that's about to be exploded, and not simply outrunning it. As in, run towards the blast wave and survive but run away and die.

**Comment by Jalleo** [comment]
Already reported I believe

**Comment by MrStonedOne** [comment]
there isn't much of a performance friendly way to fix this sadly.

**Comment by TechnoAlchemisto** [comment]
couldn't you make explosions process two tiles at a time instead of just one?

**Comment by RemieRichards** [comment]
@TechnoAlchemisto 
Legend:
O - Human/Player/"Damageable mob"
# - Tile
X - Bombing spot

1 tile at a time:
###
XO#
###
Simply walk left towards X, after it processes but before the bomb gets around to you

2 tiles at a time:
####
#OX# (O is on top of an X)
####
Once again, simply walk left

Whichever number you use, besides ALL of the tiles, there will be a place to stand to avoid the next "wave" of processing.

**Comment by MrStonedOne** [comment]
The only way i could see to fix this, is have turfs check this on entered(), but that can lead to all sorts of things like double calling ex_act on things, two bombs from the same spot at the same time not applying properly, etc.

**Comment by AnturK** [comment]
If we always had a  boundary, preventing things from moving inside would be some solution.

**Comment by xxalpha** [comment]
Pre process bombed states of things that are costly and slow down the explosion process? Just throw more RAM at the problem.

**Comment by Alek2ander** [comment]
Process mobs before other atoms?

**Comment by ChangelingRain** [comment]
You could cheat and put a 'dense object' on turfs that it processed and wait until the explosion finishes to remove them, though that would make large admin explosions kind of weird.
