### ISSUE TITLE
You can turn drying racks into smartfridges.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#20846]
Problem Description: You can deconstruct drying racks into smartfridges.

What did you expect to happen: Disassembled into 10 wooden planks.

What happened instead: The drying rack turned invisible, crowbarring it would deconstruct it into a machine frame, a matter bin and a smartfridge circuit board.

Why is this bad/What are the consequences: Can technically.. grow metal, matter bins and smartfridge circuit boards?

Steps to reproduce the problem: Use a screwdriver on a drying rack, it turns invisible. Alt click the floor it was on and check the floor tab, use a crowbar on the drying rack, it will turn into a deconstructed smartfridge.

Server: Sybil.

Revision: Server revision compiled on: 2016-10-06
Test merge active of PR #20794 
Test merge active of PR #20840 
Based off master commit ff607fb2eb8a363a79a711392a87d167cdfbcb2a

**Comment by PKPenguin321** [comment]
Haha wow

**Comment by phil235** [comment]
that's because codewise drying racks are smartfridges.. https://github.com/tgstation/tgstation/blob/fde89043099b2988d7d87e202c63d9e1c70377ab/code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm#L239

**Comment by Militaires** [comment]
feature not bug

**Comment by ShadowDeath6** [comment]
technically all you need to turn wood into metal is some mutagen and a welder, but this isn't the way that it should be gone about
also swarmers eating a drying rack does this as well
