### ISSUE TITLE
What I'd like to see to """fix""" virology

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#20844]
Each mob only has one virus slot (no more stacking healing viruses).

When a virus tries to infect a mob that already has a virus, the two viruses compare resistance stats to see which one stays/which one is discarded (or maybe the "defending" virus can use resistance and the "attacking" virus can use "transmittable" or something).

Maybe increase max symptom slots in a virus to keep deadlier viruses scary.

@XDTM @Shadowlight213

**Comment by Dorsisdwarf** [comment]
D:
