### ISSUE TITLE
Turrets can stunlock and possibly suffocate people stuck inside of walls.

### ISSUE THREAD

**Issue by BrokenCycle** [tgstation/tgstation#20841]
Any poor bastard unfortunate enough to be teleported between an AI turret and a hard place will be stunlocked, permanently. You don't fall onto the floor when being stunned inside of a wall, so the turrets won't deactivate. If you're extra unfortunate, your internals are off. All you can do is hope the admins are feeling nice, or help is nearby.

**Comment by Jordie0608** [comment]
Dupe #19630
