### ISSUE TITLE
Shooting the gravgen with meteorshot makes it disappear

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#20854]
i nearly died from laughter after discovering this please test it

**Comment by TechnoAlchemisto** [comment]
yeah, throwing the gravgen does this too, for some reason

**Comment by GunHog** [comment]
Is it DESTROYED or is this a sprite issue?

**Comment by TechnoAlchemisto** [comment]
it gets destroyed and grav turns off when thrown

**Comment by Militaires** [comment]
how to sabotage grav 

get improvised shotgun

get 4 meteorshots and breach down the airlocks using them, and then shoot the grav gen with the meteorshot to make it disappear

**Comment by Bawhoppen** [comment]
Working as designed
