### ISSUE TITLE
You can keep lawyer speech bubbles without attorney's badge

### ISSUE THREAD

**Issue by erwgd** [tgstation/tgstation#20857]
If you drop or throw away a jumpsuit with an attorney's badge attached to it, you will still have the lawyer speech bubbles. This means you can have the bubbles without the badge.

You will get lawyer bubbles if you hold a suit with the badge. You will keep the bubbles as long as you don't remove the badge by alt clicking the suit.
### Workaround

To remove your lawyer bubbles, Alt-click any suit with an attorney's badge attached to remove it, either while wearing the suit or while you're holding it.
### Reproducing this problem

I reproduced this in a local server, Server revision compiled on: 2016-10-07, 38d311e1a1bd9bfb09459f6727a759d57f01cb6b 
1. Wear suit with badge as an accessory, enjoy lawyer bubbles;
2. Take off suit with badge, keep it in hand. Still have lawyer bubbles;
3. Drop suit with badge. Still have lawyer bubbles.

**Comment by PKPenguin321** [comment]
@Incoming5643 im guessing you modified the equip proc to check for jumpsuit attachments but never modified the unequip proc for this?

**Comment by Incoming5643** [comment]
I attached it to the drop proc, not the unequip one (what even is the unequip proc?). I'm not sure why it wouldn't work on drop, but I knew the bit about it working in your hands.

**Comment by RemieRichards** [comment]
```dropped()``` IS the unequip hook.
items are "dropped" to your hand from your inventory.

it's stupid, we know.

**Comment by Incoming5643** [comment]
Oh, right.

I remember being really dumbfounded the last five times I independently remembered that nonsense.
