### ISSUE TITLE
Detective office privacy shutters are 100% wrong

### ISSUE THREAD

**Issue by pubby** [tgstation/tgstation#20855]
1. The entrance airlock is glass which defeats the purpose of privacy shutters.
2. The shutters are blast-door style which is not 50s noir at all. Use `door/poddoor/shutters` instead.

**Comment by pubby** [comment]
Also add a RC console and and an intercom as those are missing too.

**Comment by pudl** [comment]
Alright I'll do this when I'm home tonight.
