### ISSUE TITLE
Shorten door timings not working (speed light)

### ISSUE THREAD

**Issue by Aqualie** [tgstation/tgstation#20877]
Problem Description: Cutting the speed light (sets to off) does not shorten door timings 

What did you expect to happen: The door is suppose to close instantly after opening 

What happened instead: The door doesn't close instantly and stays open for the standard amount of time.

Why is this bad/What are the consequences: Very useful for securing secure areas and preventing people from rushing in behind you (e.x. command areas, security, AI upload, etc...)

Steps to reproduce the problem: Tools required [Screwdriver & wirecutter or an AI] Cut the speed light so it shows "OFF"

Server: Bagil

Revision: Server revision compiled on: 2016-10-08
Thanks for helping us out!

**Comment by CyberbossJHCB** [comment]
Cutting the speed wire is supposed to disable door timing altogether, pulsing the wire is what changes the setting. That is broken though.
