### ISSUE TITLE
Person with one robotic limb has no leg sprite

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#20889]
If you give someone one robotic limb, three sides will have a sprite and the inside of the leg does not. I'm assuming this could happen with other types of legs, but I saw it with robotic legs.

**Comment by ChangelingRain** [comment]
@phil235
You said this wasn't a problem, at least I think it was you that said that.

**Comment by phil235** [comment]
You mean, when the mob only has as single leg, right? Yeah, I messed that up. It didn't occur to me when doing the sprites that they be used when you have a missing leg. Someone just need to fix the sprites for the legs.
