### ISSUE TITLE
Taking something out of your backpack while on lava sets it on fire.

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#20885]
Because taking things out of your backpack apparently places said items on the floor for an instant before putting it in your hand if you're on lava when this happens (In a lavaboat/just immune to lava) the item will appear in your hand on fire and will eventually burn to ash.

**Comment by phil235** [comment]
Hard to fix. This would require rewriting how we handle in equipping and unequipping.

**Comment by Weisyl** [comment]
Yeah, still an issue. Kinda hacky but can we make KAs immune to lava for the time being so that miners aren't fucked or have to hike all the way back to base and spend points (they may not have) for another KA (and possibly upgrades)?

**Comment by Incoming5643** [comment]
would be easier to just give lava a very brief mercy period before it sets things aflame.

**Comment by phil235** [comment]
Cannot reproduce.
The bug only occur when:
- you take something out of your pocket
- you put something inside your belt/backpack or any held storage.
- you unequip an equipped clothing (except suit storage item)
- you swap an item to your other hand.

**Comment by Weisyl** [comment]
@phil235 Perhaps I mistook it then for when I put it back in my backpack. Still a very annoying issue.

**Comment by jughu** [comment]
Theres litteraly 6 KA'S why would you ever need to buy one no need them being lavaproof

**Comment by Weisyl** [comment]
@jughu The issue is losing an upgraded KA and then having to hike all the way back to the mining base with likely no decent ranged means of defense.
