### ISSUE TITLE
You can break down all the doors in the gulag and prison shuttle as a prisoner.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#20897]
<s>With the new object damaging system, prisoners can simply break down the gulag shuttle door and enter the cockpit to send the shuttle back instead of needing to gather points.</s>

Prisoners can break down the gulag doors by hitting it with the gulag pickaxe which is force 15.

They can also break down the monitoring room door and kill the gulag securitron for a free stunbaton.

@phil235

Ok so it turns out the shuttle console is locked, so i guess they cant escape. but they can still nab the stun baton.

<s>But yeah. This makes perma useless as you can just bust out through the doors.</s>

**Comment by Shadowlight213** [comment]
You can also just break out of perma this way.

**Comment by kevinz000** [comment]
feature

**Comment by phil235** [comment]
All doors and airlock are immune to item attack with less than 10 force, is there really a weapon with force = 10 available to the prisoner?

**Comment by Crushtoe** [comment]
The gulag's pickaxe has a force of 15.

I assume a traitor with an uplink implant can buy an esword to crack a door open, but that seems more like a feature than a bug itself.

**Comment by nullbear** [comment]
definitely a feature. Also your warden is shit if he's not keeping tabs on his prisoners well enough to see them busting down the doors.

**Comment by Shadowlight213** [comment]
Yeah. I saw this happen with the gulag initially.

Oh. Ok. I see why they got out of perma now. I had given them a gold cup for escaping the gulag by breaking down all the doors, and I guess the cup is force 14.

**Comment by Tacolizard** [comment]
@Shadowlight213 kek

**Comment by TheNightingale** [comment]
Make the gulag pickaxes force 9; if they want to break down the doors, they'll have to kill the Securitron and use the stunbaton.

**Comment by Giacom** [comment]
Give them inflatable pickaxes which do 0 damage and honk when you hit something.

**Comment by Crushtoe** [comment]
Does the gulag currently get normal pick axes?

**Comment by Crushtoe** [comment]
Fixed by #20909
