### ISSUE TITLE
Picking things up goes to left hand even with right hand selected

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#20913]
I'd think this already has an issue, but I didn't see one so here it is. If you take something like, say, a fire extinguisher from it's wall mounting, it will go to your left hand even if the right hand is selected. Same for rechargers, air pumps, etc.

**Comment by phil235** [comment]
@RemieRichards

**Comment by PKPenguin321** [comment]
This also applies to taking items out of your pockets it's awful
