### ISSUE TITLE
Using cham projector on the sign backing item from dismantling the bar sign lets you be invisible.

### ISSUE THREAD

**Issue by Ausops** [tgstation/tgstation#20929]
Using cham projector on the sign backing item from dismantling the bar sign lets you be invisible.

Probably a missing icon in a dmi. Reported by Saul_Myers

**Comment by phil235** [comment]
Do you mean that the sign backing is invisible?

**Comment by Onule** [comment]
Yes, the bar's sign backing is invisible when you unwrench it.

**Comment by phil235** [comment]
The issue is that the bar sign shouldn't be unwrenchable in the first place. I fixed its attackby recently and this made the bug apparent.
