### ISSUE TITLE
Krav Maga and Antidrop Implants

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#20930]
There's a glitch involving krav maga and anti-drop implants. It happened between 9-10:00 am, EST on 10/11/16 on basil, in case anyone wants logs. Disarming someone with antidrop enabled with krav maga on creates a no-drop duplicate of the item in the other person's hand. (It happened with the HoS laser gun in this case.) I guess dorsi can explain how he fixed it better than me, but both people involved had to go through a lot to get the HoS laser gun removed. Attempting to disable the implant told me my hands were relaxed, yet I couldn't put the gun away.
Edit: Not sure if both people had antidrop, I think it was, but not sure.

**Comment by PKPenguin321** [comment]
Krav disarm moves the item disarmed directly into the krav user's hand. It needs to respect nodrop.

**Comment by Dorsisdwarf** [comment]
We 'fixed' it by deleting and recreating you. It is pretty much unresolvable by any other means
