### ISSUE TITLE
Pushing a fulltile window fucks up its dir and lets you walk through it

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#20937]
I''''m pretty sure this is @phil235

**Comment by phil235** [comment]
nope, it was already there when I was doing my PR, I wasted an hour trying to figure out whether it was my fault. Turns out it's not, the bug was already happening on sybil when I was working on the obj damage system PR.

**Comment by MrStonedOne** [comment]
either pushing doesn't call setDir() or there are fulltile windows without the fulltile var set, because windows reject direction changes if they are fulltile windows.
