### ISSUE TITLE
BSA can be instantly reloaded by screwdrivering the console

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#20939]
1. Fire
2. Unscrew console
3. Screw in console
4. Aim
5. Repeat

**Comment by TechnoAlchemisto** [comment]
BLAT BLAT

**Comment by AnturK** [comment]
The admin-spawned or buildable one ?

**Comment by PKPenguin321** [comment]
Station goal buildable one

**Comment by FantasticFwoosh** [comment]
Many Bothans died to bring us this information.

_Shhhhhhhhhhhhhh_
