### ISSUE TITLE
Using a syringe on slime cores in a bio satchel deletes the stack

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#20955]
> fill satchel with grey slime cores
> inject one core in it with blood
> makes 3 monkey cubes while the rest disappear

**Comment by Supermichael777** [comment]
Thats what hapens when somthing never designed to stack is interacted with in a stack

**Comment by YakumoChen** [comment]
I thought you couldn't inject things in biobags?

**Comment by lzimann** [comment]
Fixed on #22418

**Comment by Cyberboss** [comment]
@lzimann That reference can't possibly be right??

**Comment by lzimann** [comment]
Oh, I copied the wrong shit.
