### ISSUE TITLE
Tripple Citrus turns the glass invisible, Changling sting is now impossible to make. 

### ISSUE THREAD

**Issue by Cuboos** [tgstation/tgstation#20954]
I was a bartender on Sybil trying to make a changeling sting for an assistant. After putting the lime/lemon/orange juice together it suddenly resulted in a "Triple Citrus" . Right clicking the soda dispenser shows that the glasses are still "there", just invisible and can't be picked up without right clicking. After finishing the drink, the glass reappears and can be used as normal.

**Comment by phil235** [comment]
icons/obj/drinks.dmi : "Triplecitrus" should be "triplecitrus", no capitalization.

**Comment by Supermichael777** [comment]
changeling sting should be made with soda considering its sprite
