### ISSUE TITLE
Death nettles don't produce sulphuric acid.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#20969]
It seems that death nettles will never produce sulphuric acid, even if that's their only trait gene. At the very least, grinding them won't give you sulphuric acid.
Regular nettles still produce it though.

**Comment by phil235** [comment]
Death nettles have both fluorosulphuric acid and sulphuric acid in them, but the mixer code thinks it should only give sulphuric acid when blended. https://github.com/tgstation/tgstation/blob/b4804c7ee85bc28a0293a263167f1382fb6684d8/code/modules/reagents/chemistry/machinery/reagentgrinder.dm#L30

**Comment by Tacolizard** [comment]
That's weird, I ground up death nettles just recently and it worked.
