### ISSUE TITLE
People who enter CTF will have their old body dusted and replaced with an ammo pickup

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#20966]
Even if that body was never actually in CTF and happens to be on the escape shuttle, for example.

**Comment by Shadowlight213** [comment]
10/10

**Comment by ChangelingRain** [comment]
coiax did this, and coiax is ~back, so!
@coiax

**Comment by coiax** [comment]
Sounds hilarious. Surprised it hasn't been noticed before. I'll have a look.

**Comment by coiax** [comment]
Shouldn't this be prevented by https://github.com/tgstation/tgstation/blob/fee08e60a7fe1c8439a34e4b68f3cddf35be4457/code/modules/awaymissions/capture_the_flag.dm#L223

I will test later.

**Comment by JJRcop** [comment]
Why don't you just check if they are a part of the respective faction?

**Comment by coiax** [comment]
Yes, that did occur to me.

**Comment by Tacolizard** [comment]
i say keep it in
