### ISSUE TITLE
Pulling a Kinetic Accelerator off your suit storage momentarily drops it.

### ISSUE THREAD

**Issue by TechnoAlchemisto** [tgstation/tgstation#20965]
Put KA in your suit slot, take it out, notice that it drops for a microsecond before going into your hands.

**Comment by ChangelingRain** [comment]
Duplicate of #20885

**Comment by PKPenguin321** [comment]
sort of but not really, try dropping a KA, it is MUCH more noticeable for them than other objects. started happening right after coiax's thingy that made them self charge
