### ISSUE TITLE
You can ride over lava with skateboards/scooters

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#20970]
fuck

**Comment by PKPenguin321** [comment]
oh and the janicart works as well, i assume it works with any vehicle

**Comment by Crushtoe** [comment]
Feature of the Year.

**Comment by Iamgoofball** [comment]
:+1: FEATURE

**Comment by PKPenguin321** [comment]
I propose we make a lava surfboard in memory of this bug

**Comment by Crushtoe** [comment]
Don't lava boats already exist? 

Maybe the implementation of them was just making all vehicles fireproof and hoping no one brought any janicarts over.

**Comment by Crushtoe** [comment]
Don't lava boats already exist? 

Maybe the implementation of them was just making all vehicles fireproof and hoping no one brought any janicarts over.

**Comment by phil235** [comment]
It's not a problem with vehicles... You noticed that particular bug, but didn't notice that lava literally can't burn any object at all????

**Comment by Crushtoe** [comment]
Maybe it happened when that pull request to make anything that exists burn unless it has a fireproof flag went through?

**Comment by PKPenguin321** [comment]
>It's not a problem with vehicles... You noticed that particular bug, but didn't notice that lava literally can't burn any object at all????

Whoooooops

**Comment by Tacolizard** [comment]
Yeah this is a feature. Just think of how fun it'll be to watch the free golems fight Ash Drakes on their scooters now.
