### ISSUE TITLE
The eternally falling talisman

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#20979]
http://i.imgur.com/jXAY4pW.png

So from what I could get from the player, the player dropped the talisman down the chasm and it just kept falling... And falling.... And falling. I couldn't get the vars for it because it doesn't exist.

**Comment by nullbear** [comment]
You couldn't have toggled darkness for this screenshot?

**Comment by Anonmare** [comment]
There's not really much to see. I was screenshotting the chatlogs. I'd have tried getting the vars of the talisman but I legit could not find it.

**Comment by KorPhaeron** [comment]
Probably because it's indestructible

**Comment by optimumtact** [comment]
yeah likely just not respecting qdel when it should.

**Comment by JJRcop** [comment]
Maybe chasms should spit out items that don't qdel.

**Comment by optimumtact** [comment]
I don't think there is any way for code to tell when things are qdeleted.

The problem is more so code for items that prevent their own qdeletion

but also partly that we use qdeletion instead of death or gibbing or destroy of items for many cases.

**Comment by Crushtoe** [comment]
Just a small maintainability issue, it's fine. What can go wrong?
