### ISSUE TITLE
Many items aren't replaceable, but are now easily destroyed by normal combat

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#20999]
@tgstation/commit-access 

What to do?

**Comment by optimumtact** [comment]
Deal with and wait for the next round.

**Comment by KorPhaeron** [comment]
Not an acceptable solution, the game has been developed for a long time with the assumption that destruction of items is limited, we need things to either fall apart less easily or have more ways of replacing things.

**Comment by KorPhaeron** [comment]
Especially for jobs like security or mining that involve combat

**Comment by phil235** [comment]
I need a list of items that shouldn't be destroyable through combat according to you.

**Comment by nullbear** [comment]
all unique traitor objective items, to start.

**Comment by YakumoChen** [comment]
Having a backpack or belt slot item burn in a fire is incredibly annoying, especially when you're working a job that makes you fireproof, like CE or Atmos Tech. (including my snazzy white CE belt). Having engineering bags and a few other items naturally fireproof would be a lot more convenient.

Lots of whitelist items are destroyed in a fire, like Emitters and Shield gens too, stuff is turning to ash that tends to be made of materials you don't expect to burn, lots of machines.

The fact you can only fix (some) items with one item only available through one department, or make them immune to fire through one (much more rare) item available through one other department isn't really an acceptable way of handling making lots and lots of items of varying usefulness/rareness is bad design.

**Comment by YakumoChen** [comment]
also the supermatter shard should PROBABLY be immune to fire. I saw one get burned to ash a few days back.

**Comment by phil235** [comment]
@YakumoChen Already done https://github.com/tgstation/tgstation/blob/4ed6c9894a4bfb405cd31024e00137596128209d/code/modules/power/supermatter/supermatter.dm#L27
