### ISSUE TITLE
Player had their ID turn invisible and dissapear

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#21003]
What happened:
- Player was the HoS
- Was caught by a syndicate bomb blast, deleting most of their clothes
- Later, in the brig, took out ID to unlock an implant case
- When they swiped the implant it turned invisible
- Upon placing the ID back in their PDA, it was gone

I'm guessing the ID was deleted or something by the bomb. @phil235 ?

**Comment by phil235** [comment]
I don't see how the ID could be destroyed but not immediately deleted, the code is pretty straightforward.

**Comment by PKPenguin321** [comment]
I believe so. Sorry if there isn't a lot of data, I was mostly going off of what the player told me. Might be able to check runtime logs from yesterday about it if it made one.

**Comment by PKPenguin321** [comment]
I've literally never heard of this happening again. Probably safe to close
