### ISSUE TITLE
Xeno chestbursting leaves behind a head and brain.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#21000]
Not sure if this is intended or not, considering it makes getting someone scanned before they burst not as big a deal.

**Comment by phil235** [comment]
https://github.com/tgstation/tgstation/blob/eace4eec148e8a366ee2fe6673f852b59a2e77b1/code/modules/mob/living/carbon/alien/special/alien_embryo.dm#L102

Give it the correct argument for gib().

**Comment by FantasticFwoosh** [comment]
All sorts of gib's work like that, megafauna for instance.

**Comment by PKPenguin321** [comment]
Yeah but chestbursting is supposed to be a little more permanent

**Comment by Thunder12345** [comment]
Wasted get

**Comment by Shadowlight213** [comment]
Oh no. I just saw the get. :cry:
