### ISSUE TITLE
Space drifting is incredibly slow

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#21024]
During a nuke ops round, I was in a hardsuit in metastation atmos. Upon the delta alert being sounded, I immediately ran and threw myself out the external airlock to space to try and escape the blast.

I then proceeded to float at a speed equivalent to slowdown 2 or 3.
Throwing things didn't help, nor did using an extinguisher.
By the time the nuke went off, I had only floated about halfway past the AI sat, which isn't very far at all.

@MrStonedOne since coderbus said that you touched space drifting last.

**Comment by MrStonedOne** [comment]
Its a subsystem now. Could be something related to delays...
