### ISSUE TITLE
False armblades never wear off

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#21023]
Multiple players in a changeling round got stung with a false armblade, some five minutes in, and still had it come round end. They are supposed to wear off by themselves.

**Comment by AnturK** [comment]
Possibly relevant runtime from the log:
```
The following runtime has occurred 5 time(s).
runtime error: Cannot read null.name
proc name: remove fake (/obj/effect/proc_holder/changeling/sting/false_armblade/proc/remove_fake)
  source file: tiny_prick.dm,160
  usr: null
  src: False Armblade Sting (/obj/effect/proc_holder/changeling/sting/false_armblade)
  src.loc: null
```

**Comment by phil235** [comment]
so the fake blade was qdelled before the timer ran out? But then how come the false blade icon was not removed from the mob when it was deleted? don't we call unequip on deletion?

**Comment by PKPenguin321** [comment]
This really needs a fix, I keep having to mass delete false armblades
