### ISSUE TITLE
Vitrium Froth doesn't metabolize.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#21033]
One of the new chemicals (Vitrium Froth) from the ash flora (cactus and mushroom leaves) doesn't really metabolize, it'll just stay in you forever, with the healing effects.

Also, are mushroom bowls suppose to do anything?

**Comment by TechnoAlchemisto** [comment]
o

**Comment by TechnoAlchemisto** [comment]
i don't know why this is happening

**Comment by TechnoAlchemisto** [comment]
actually i might give me a sec

**Comment by sen4eg** [comment]
Bowls has a wrong path
```
/obj/item/reagent_containers/food/drinks/mushroom_bowl //wrong
/obj/item/weapon/reagent_containers/food/drinks/mushroom_bowl //correct
```

**Comment by TechnoAlchemisto** [comment]
I'll try to fix that too, thanks for the report.
