### ISSUE TITLE
Blood can remain on hardsuit/magboots/complionator icons in top left after showering

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#21042]
The icons on the mob and in the bottom left are fine

**Comment by bgobandit** [comment]
button icon state updating is fucky in general, something similar happens a lot w/ mime masks

**Comment by Cyberboss** [comment]
Someone reverify this please. Lots of shower changes since then

**Comment by kriskog** [comment]
Still a bug. Get blooded hardsuit, shower, icon stays bloodied.

**Comment by Detective-Google** [comment]
reproduced, still an issue

**Comment by Donkie** [comment]
This is probably fixed

**Comment by Cyberboss** [comment]
Willing to believe it
