### ISSUE TITLE
The proto-kinetic crusher can 'backstab' diagonally from the front

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#21047]
If `check_target_facings()` happens to return FACING_INIT_FACING_TARGET_TARGET_FACING_PERPENDICULAR, which is very possible if you're attacking your target diagonally from the front, as the conditions to return that define are just 'targets are facing perpendicular to each other'.

**Comment by ChangelingRain** [comment]
![valid](http://puu.sh/rNeC3/1eed36bc5a.png)
This is a valid backstab.

**Comment by PKPenguin321** [comment]
we tf2

**Comment by ChangelingRain** [comment]
at minimum this is extremely unintended, as ergo wanted it to Actually Be A Backstab and this, uh, isn't.
