### ISSUE TITLE
Inconsistent/duplicate examine messages on emagged HoP locker

### ISSUE THREAD

**Issue by somefuckingguy** [tgstation/tgstation#21041]
I latejoined as HoP. My locker's lock was broken. When I examined it I received the following messages:

> That's head of personnel's locker.
> It's a card-locked storage unit.
> It looks broken.
> It seems pristine and undamaged.
> It appears to be broken.

**Comment by phil235** [comment]
the broken line in closet/examine needs to be removed since it's already handled in structure/examine().
Don't know what to do about the emagging, maybe reduce the integrity level to failure level so it doesn't appear undamaged?

**Comment by Qbopper** [comment]
http://i.imgur.com/B2Ws6Ti.png untouched

http://i.imgur.com/XACHC01.png 1 laser shot

http://i.imgur.com/SVVuF8V.png heavy damage

http://i.imgur.com/OnV9Xx4.png broken

http://i.imgur.com/tRhMHfp.png emagged

couldn't replicate this, unless there's something I'm missing here this can be closed

**Comment by Qbopper** [comment]
untouched locker
![untouched](http://i.imgur.com/B2Ws6Ti.png)

a single laser shot
![1 shot](http://i.imgur.com/XACHC01.png)

heavy damage
![heavy damage](http://i.imgur.com/SVVuF8V.png)

**broken via laser shots**
![broken](http://i.imgur.com/OnV9Xx4.png)

**emagged**
![emagged](http://i.imgur.com/tRhMHfp.png)

Security lockers:

untouched
![untouched](http://i.imgur.com/7WRUz6c.png)

emagged 
![emagged](http://i.imgur.com/dXsvDEC.png)

shot 
![shot](http://i.imgur.com/xkZLOkv.png)

still an issue, as far as I can tell happens with any secure locker.
