### ISSUE TITLE
Guthens can still move when buckled to chairs

### ISSUE THREAD

**Issue by MrAlphonzo** [tgstation/tgstation#21058]
A kind miner donated a Guthen to xenobiology, and when I found it problematic when it started running into slime chambers, I buckled it to a chair. But it could still move, and it brought the chair with it.

**Comment by Bawhoppen** [comment]
Fyi Guthen is just the name of one, the creature is called a Gutlunch

**Comment by RemieRichards** [comment]
Actually it's not just the name of one, it's the name of a female Gutlunch.
Like Cows/Bulls
it's Guthens/Gutlunches

**Comment by Bawhoppen** [comment]
Yes it's the name of one specific indivual is what I meant

**Comment by Bawhoppen** [comment]
Oh wait I misread your post, That doesn't seem right? Why is one named Gubbuck then and th othernis Guthen?

**Comment by RemieRichards** [comment]
Actually, I think it's:
Species: Gutlunch
Female: Guthen
Male: Gubbuck

**Comment by Bawhoppen** [comment]
That may be correct, but I thought those were just the named ones

**Comment by Firecage** [comment]
Can't reproduce this. Perhaps its already fixed?

**Comment by PKPenguin321** [comment]
Needs reproduction. I doubt this is a real issue.

**Comment by kriskog** [comment]
Can't reproduce, even when in control.
