### ISSUE TITLE
Fire Extinguisher cabinets do not display the proper sprite when a fire extinguisher is put back inside

### ISSUE THREAD

**Issue by Mooseykins** [tgstation/tgstation#21051]
If you take a Fire Extinguisher out of a cabinet and then attempt to put it back inside, the cabinet displays the empty cabinet sprite while open.
I would supply a picture, but I'm at work at the moment.

**Comment by phil235** [comment]
There's also two update_icon in the cabinet's attackby: https://github.com/tgstation/tgstation/blob/4ed6c9894a4bfb405cd31024e00137596128209d/code/game/objects/structures/extinguisher.dm#L60
