### ISSUE TITLE
The electric guitar is annoying as fuck 

### ISSUE THREAD

**Issue by Cuboos** [tgstation/tgstation#21054]
I CAN'T FUCKING HEAR SHIT WHEN SOMEONE IS PLAYING THAT THING, WHO THE FUCK THOUGHT THIS WAS A GOOD IDEA? REMOVE IT!!!!!

**Comment by Mooseykins** [comment]
I remember when I was pretty excited for NikNak to implement the eguitar, all of that excitement has melted away when I realized just how bad the eguitar actually is.

**Comment by TechnoAlchemisto** [comment]
yeah eguitar made me turn off instruments

**Comment by optimumtact** [comment]
there is a toggle, this isn't a bug. take it to the feedback forum.
