### ISSUE TITLE
CTF guns can't be removed from belt

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/tgstation#21064]
Put CTF laser gun on belt, attempt to remove from belt. Gun can't be removed from belt

**Comment by KorPhaeron** [comment]
@coiax

**Comment by PKPenguin321** [comment]
This has always been broken ever since it was added because the gun is NODROP

**Comment by coiax** [comment]
The question is how you managed to put it on the belt in the first place, given that it's NODROP.
