### ISSUE TITLE
Swarmers can attack and destroy airlocks leading to space

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#21075]
@phil235 
I don't think swarmers had any restrictions on attacking airlocks before, since they couldn't destroy them.

**Comment by phil235** [comment]
I didn't touch that, swarmer being able to disintegrate doors is intended by the swarmer code.

**Comment by Shadowlight213** [comment]
@Phil235 its a side effect. Doors weren't able to be destroyed by anything really before. Pulse rifles, swarmers, etc.. But now they can. But yeah, I'll try your suggestion.

**Comment by phil235** [comment]
Oh, you're right, DisIntegrate() calls ex_act(3) (totally not stupid way to code this...)
