### ISSUE TITLE
Metal module for engineering borg disappeared

### ISSUE THREAD

**Issue by Leon9621** [tgstation/tgstation#21071]
Attempted to make wall girders with what I presume was one sheet of metal, because it booted me out and told me I did not have enough. I picked up another stack and noticed that the module has disappeared, And I could not click on it to use it, but ctrl + z worked to make more girders. After storing the module, there is a blank space where the metal should be that I cannot select.

**Comment by pubby** [comment]
I've gotten this glitch before too. Same circumstances.

**Comment by YakumoChen** [comment]
did you try recharging to get more metal?

**Comment by optimumtact** [comment]
it probably tried to merge them incorrectly

**Comment by kriskog** [comment]
Havent heard of this lately.
