### ISSUE TITLE
Comprehensive list of disliked features and issues with Object damage refactor, requested by phil

### ISSUE THREAD

**Issue by AdamElTablawy** [tgstation/tgstation#21078]
# please let me know if i've missed any concerns and/or possible fixes for aforementioned concerns. This is just for Phil to work off of when he's fixing issues since he asked me to make this for him.
## Specific objects being damaged that should not be

Some objects do not drop anything when destroyed and are thus irreplaceable or hard to replace without significant effort. Below is a list of the aforementioned objects and suggested fixes.
- Particle Accelerator-Goes bye bye when smashed up. Suggestion-Make PA have circuit boards so it is constructable/deconstructable, so that smashing it apart will break it into that frame.
- Gravity Generator-Goes bye bye, not damaged state (can also enter damaged state) when hit with object of sufficient damage. Includes meteorshot. Suggested fix-Enter 'damaged' state instead of qdeling, increase damage threshhold and health significantly.
- Gateway-Also destructible and irreplaceable. Suggestion-Make indestructible by normal means.
- Singularity Generator, Tesla Generator, Tesla Coils, Rad collectors-All destroyable with relative ease. Mostly requires cargo to replace, extremely difficult. Suggestion-make sing and tesla generator fall apart into 'damaged' versions of themselves, requiring some metal to repair, but not being outright destroyable. Make rad collectors also enter 'damaged' state, but not be deleted outright.
- Mirrors, sinks, all-in-one grinders, intercomms, secure safes, wall monitors and request consoles-Irreplaceable. Suggestion-Make them fall apart into metal, allow construction of mirrors, sinks, showers, secure safes. Make wall monitors (like the ones in RD office) a subtype of security console and thus have security console circuitboards of a subtype so they can be built. Make request consoles either not break or make them constructible.
- Emitters-Destroyable with simple weapons, which is bad since despite being ID locked and on you can still destroy them, releasing engine. Suggestion-Make them require a very high damage threshhold to damage instead of 'lol spear.'
- Suit Storage Units-Irreplaceable. When destroyed, GG. They qdel. Possible solution-make them constructible.
## Damage issues itself
- Objects damaged fall apart into components. Makes little sense and is easy to greytide with if you just run around stabbing things with spears. Essentially easier in some circumstances than regular deconstruction. Suggestion-Make machines falling below their integrity simply enter a 'broken' state. Broken state is similar to broken state on APCs-completely nonfunctional and must be repaired or rebuilt. Makes a little more sense than stabbing a light switch until it falls off the wall and dies. This also allows for simply making a lot of objects that were otherwise deleted-showers, sing generator, PA, chem dispenser in chemistry-simply repairable if just attacked instead of having to worry about bullshit with circuitboards, et cetera.
- Broken objects would simply just not function and have broken sprites, similar to having no power. For other objects like tesla or sing generators, they would just be inert until repaired. Repairing could range for for machines deconstruction and reconstruction, to applying metal/glass and welding.
- Damaged machines cannot be repaired currently. If you dent the PA, it's dented forever. If something is heavily damaged and you accidentally hit it, it's fucked. Solution-Make welding on help intent fix damaged machines.
- Hardsuits, miner suits, cannot be repaired when damage. Solution-Welding the hard metal of the hardsuits/EVA suits will repair them, same with miner suits.
## Fire & Acid
- IDs, PDAs, are extremely difficult to replace in most cases, and when destroyed by fire/acid/regular damage, is gone. Especially if it's a traitor PDA. Solution-Make ID's and PDAs fireproof.
- Traitor objectives, such as the nuke disk, HoS's laser, should be fire and acid proof as to avoid your object being permafucked GG. 
- Backpacks delete all objects in them when they burn. Solution-make backpacks drop their contents when burned.
- Fire can destroy airlocks, but not walls. Solution-Burn the walls.
- Fire burns things it logically should not, such as machines, magboots, etc. Solution-define fire damage as a fire damage threshhold where if the heat of a room exceeds a specific temperature the object starts taking damage until it enters it's broken state if a machine, or deletes otherwise, so magboots don't roast in a barely-hot fire.
- Airlocks, which are capable of resisting space, should be resistant to station acids. There's already thermite if you want to burn through into an area.
## Other Concerns
- You can use generally cheap items available to most antagonists to be able to open most objects that are previously access restricted. This is mostly a balance concern in relation to being able to say, slash open the Captain's locker or charge through bolted doors with acid. No real solution immediately available, but addressing this would be appreciated.

**Comment by CyberbossJHCB** [comment]
Burn the walls? That's insane. Airlocks should take fire damage. That's what we have firelocks for

**Comment by NSSherlock** [comment]
Fire should burn walls, but regular airlocks (not firelocks) should resist acid? Seems inconsistent.

Also, any acid resistance needs to not interfere with xeno acid, which has traditionally been able to melt pretty much anything.

**Comment by AdamElTablawy** [comment]
these are suggestions i've gotten from other people, not my own

**Comment by Supermichael777** [comment]
this whole feature was a bad idea and poorly executed to boot

**Comment by Bawhoppen** [comment]
Machines being bashed with melee (like emitters) should electrocute the basher

**Comment by jughu** [comment]
Cremator shouldnt be industricble or atleast higher damage then 20 this allows changelings to cheese it and break them and be basically a warling god you cant kill without bombs

**Comment by kriskog** [comment]
Most of this has been adressed, the rest are just facts of life by now.
