### ISSUE TITLE
A tile from lavaland's ruined birthday ruin has no gravity.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#21083]
The tile my character is standing on has no gravity what so ever. If you create an area on it, that area will have no gravity, in this case, the entire room made from sandstone doors has no gravity.

![lavalandruin1](https://cloud.githubusercontent.com/assets/4581352/19534640/850a2a5e-963c-11e6-9231-5710adb42cdf.png)

**Comment by Crushtoe** [comment]
Intended: Ashligger Zero-G Emulation Zone for the Preperation of the Occupation of Space Station 13 (AZGEZPOSS13)
