### ISSUE TITLE
Necropolis gate can be destroyed.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#21084]
Because of the object damaging system, you can break the gate.

![necropolisgate](https://cloud.githubusercontent.com/assets/4581352/19535787/161bb932-9641-11e6-9e20-d3137a0c4745.png)

**Comment by jughu** [comment]
Inb4 a start of a new solarium

**Comment by phil235** [comment]
uuuuuuuuuuuuughhhh
