### ISSUE TITLE
Spray bottle bugged in chem dispenser

### ISSUE THREAD

**Issue by Hikurac** [tgstation/tgstation#21093]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)
When you place a spray bottle in the chem dispenser, it doesn't give you any options of how much chems to dispense.

**Comment by TheDreamweaver** [comment]
Yes, thank you for reporting this. I've noticed it for two weeks now, but was to lazy to report it, or figured it was designed like that for some reason that's beyond me.
