### ISSUE TITLE
Latejoiners Spawn at Title Screen

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#21097]
This issue occurred somewhere between 3 and 3:55 p.m. EST, on bagil. The map was metastation. I latejoined as the CMO and ended up at the title screen. Thinking it was that glitch, I rebooted BYOND and upgraded to 511. Finally, I gave up and used the suicide command. Upon ghosting, I found that I really was in the title screen area. By the end of the round, there was about 10 people there.

**Comment by optimumtact** [comment]
Sounds like a possible issue with the spawner locations on metstation

**Comment by Bawhoppen** [comment]
How many players cause on some shitty new maps (disc) I've seen it happen when there are a large amount of players

**Comment by Dorsisdwarf** [comment]
>disk is shitty and new

also this is meatstation

**Comment by Shadowlight213** [comment]
>disk

Disk has been gone for like months

**Comment by Dorsisdwarf** [comment]
Also this is probbably an admin hitting the "Delete latespawns" button which HAS NO CONFIRMATION WARNING OR UNDO and not realising

**Comment by swankcookie** [comment]
@Dorsisdwarf where is the code for that verb?

**Comment by Dorsisdwarf** [comment]
https://github.com/tgstation/tgstation/blob/2a8b848f9bbba884aca4119e55ef517a5e0d5692/code/modules/admin/verbs/randomverbs.dm#L774

**Comment by Cyberboss** [comment]
Why does that exist?

**Comment by swankcookie** [comment]
4raisins. I'll take a look at it

**Comment by Mervill** [comment]
@optimumtact fixed, closeable
