### ISSUE TITLE
tesla has an absurd bias to the east

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#21092]
it gets stuck at the east of the station pretty much every time without fail

**Comment by optimumtact** [comment]
dupe of a previous issue I'm pretty sure, but nothing to be done easily.

https://tgstation13.org/phpBB/viewtopic.php?f=10&t=7969

**Comment by PKPenguin321** [comment]
I don't think there's any actual github issue about this already

**Comment by optimumtact** [comment]
you're right

**Comment by CyberbossJHCB** [comment]
I always thought it was you guys griffing science/medbay

**Comment by CyberbossJHCB** [comment]
Potential cause.

https://github.com/tgstation/tgstation/blob/b5b4037e2eeae424ce7580b29f1597bdc1d4e501/code/modules/power/tesla/energy_ball.dm#L84

Maybe it's just attracted to all that juicy machinery?

**Comment by PKPenguin321** [comment]
Yes, BUT! MSO said it picks targets to zap starting with targets to the east, then travels to the zapped targets. So it always moves east because it zaps machines to the east before it zaps machines to the west.

**Comment by A-t48** [comment]
Randomizing the start direction should fix it then.

**Comment by PKPenguin321** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/23312 (hopefully)
