### ISSUE TITLE
No melee combat logs when attacking

### ISSUE THREAD

**Issue by CyberbossJHCB** [tgstation/tgstation#21107]
Was dicking around with my prs. 

Attacked a monkey with a crowbar -> No logs
Attacked myself with a crowbar -> No logs

#20962 #20962 #20962
@phil235 @phil235 @phil235

**Comment by phil235** [comment]
that's intended.

**Comment by CyberbossJHCB** [comment]
But how will I ever mop myself in the chest with a mop again?

**Comment by NSSherlock** [comment]
@phil235 that's true in most cases, but when the affray gets hectic (e.g., when instead of a one-on-one fight, it's a whole crowd fighting) it's important to be able to tell if/when you accidentally hit an ally or a bystander. Just because you know who/what you're _trying_ to hit doesn't always mean you know who/what you _actually_ hit, and the combat log was in many cases the only sure way to know.

**Comment by PKPenguin321** [comment]
Yeah, messages showing what you did are also important for new players who haven't learned what their actions do or what feedback to look for besides text box messages as well

**Comment by Shapsy** [comment]
Yeah, I'd really rather keep the logging, it doesn't really clutter the chat considering this is information I'd say is important

**Comment by Crushtoe** [comment]
Yeah. It's important to know if my line of fire is hitting an ally when it travels diagonally from my current position or if it hits an enemy.

**Comment by PKPenguin321** [comment]
New player accidentally killed the wrong person in a big fight yesterday because he couldn't read who he was attacking

**Comment by Iamgoofball** [comment]
Your own actions should log, others should not.

**Comment by optimumtact** [comment]
Since phil indicated this was by design, please move discussion to the feedback forum.

**Comment by phil235** [comment]
> but when the affray gets hectic (e.g., when instead of a one-on-one fight, it's a whole crowd fighting) it's important to be able to tell if/when you accidentally hit an ally or a bystander. Just because you know who/what you're trying to hit doesn't always mean you know who/what you actually hit, and the combat log was in many cases the only sure way to know.

In a big crowd fight, having the attack logs visible not only won't prevent you from hitting allies but it will also be very hard to read the dozen attack logs in the now clogged chat to see if you hit an ally. Now that we have visual effects on the victim, I think it's easier to simply rely on it to detect friendly fire (both melee and guns) than trying to read the dozen fast moving attacks messages in your chat.


>Yeah, messages showing what you did are also important for new players who haven't learned what their actions do or what feedback to look for besides text box messages as well

I think the visual effect for punching is a way better method to tell new players what happened. newbies don't always read the chat so it's easy for them to miss the text feedback for their action, visual effects (and sound effect) on the other hand can't be missed.

>Yeah. It's important to know if my line of fire is hitting an ally when it travels diagonally from my current position or if it hits an enemy.

Then it's a good thing we have a visual effect appearing on the thing your bullets hit.

**Comment by Crushtoe** [comment]
@phil235 You act as though it's some unforeseen affect of adding this revolutionary chat log feature, but it's what we've had for literally a decade.

Visual affects are great and they offer so much more by allowing you to see if something landed without reading chat. But it's still important to be able to tell if that punch your ally got was from the enemy landing one or you hitting them by accident.

**Comment by PKPenguin321** [comment]
Phil, this is very detrimental to new players, see my last post. There is as it stands not enough visual feedback to make up for your own attacks being logged.

**Comment by CyberbossJHCB** [comment]
Frankly, in a fight, everyone looks the same unless you have a sechud.
