### ISSUE TITLE
AIs can't see C4 being planted on their own core

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#21113]
#20962 @phil235

AIs used to receive a combat log message if someone tries to attach c4/x4 to an AI core, they don't after #20962

**Comment by optimumtact** [comment]
dupe of the more general #21107

**Comment by phil235** [comment]
not the same issue.

**Comment by phil235** [comment]
You can't plant c4 on an AI: https://github.com/tgstation/tgstation/blob/4cddd81120b08cada8856576ad2f1d62221dba9b/code/game/objects/items/weapons/explosives.dm#L71
