### ISSUE TITLE
Swarmers can sever limbs when the person is piloting a mech

### ISSUE THREAD

**Issue by Archie700** [tgstation/tgstation#21116]
Apparently swarmers, which by right do not have anything sharp, can sever limbs of humans when they are piloting a mech by damaging it.

Get a human to pilot a mech and have a swarmer attack it and watch limbs fly.

**Comment by phil235** [comment]
Swarmer attack on /atom/ calls ex_act(3)
https://github.com/tgstation/tgstation/blob/b4804c7ee85bc28a0293a263167f1382fb6684d8/code/game/gamemodes/miniantags/bot_swarm/swarmer.dm#L334

Explosion on mech calls explosion on the occupant.
https://github.com/tgstation/tgstation/blob/f6db08af2e67c0a8933557f9f69bb9a5eb4fa6f0/code/game/mecha/mecha_defense.dm#L131

**Comment by PKPenguin321** [comment]
I'm guessing if a human is in a locker and a swarmer breaks it the human dies and limbs fly everywhere as well

**Comment by Onule** [comment]
Oh, I forgot to report this when it happened to me around.. two weeks ago, I hid in a locker from a swarmer, and once it broke it, I got unconscious and had lost an arm.

**Comment by bgobandit** [comment]
serves them right for mech powergaming imo

**Comment by phil235** [comment]
Same thing happens with mech drill calling ex_act(). There's probably more cases.

**Comment by kriskog** [comment]
Not true anymore
