### ISSUE TITLE
Deconstructing transport tube with pod inside leaves unremovable pod

### ISSUE THREAD

**Issue by A-t48** [tgstation/tgstation#21137]
[Note]: # Deconstructing transport tube with pod inside leaves unremovable pod

![image](https://cloud.githubusercontent.com/assets/8206540/19621624/903af9f2-984a-11e6-9437-235ad77b5710.png)

**Comment by A-t48** [comment]
Never mind. Apparently it fixes itself if you hit it with a crowbar a few times.

**Comment by CyberbossJHCB** [comment]
Its still bad form. Don't close this
