### ISSUE TITLE
Spectral sword doesn't seem to work any longer

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#21135]
You can't see ghosts orbiting it.

It doesn't count ghosts orbiting it for attack or defense.

@MrStonedOne you changed orbit recently, it's the only thing I can think of off the top of my head that might have caused this

**Comment by MrStonedOne** [comment]
Its @MrPerson's plane master changes

**Comment by MrPerson** [comment]
Probably not, ghosts are still plane 0.

**Comment by MrStonedOne** [comment]
I had just woke up, I didn't see the part about not counting them.

I had remembered the lighting plane master bit, remembered ghost images to override see darkness, and some how linked the two in my mind as the same thing.

Ignore me.

**Comment by MrStonedOne** [comment]
Oh yes, I see why.

the var `orbiters` stores orbit datums, not the atoms orbiting, I need to change https://github.com/tgstation/tgstation/blob/ce40d29ead50eff452ccdad7f46bac17e0dae4d7/code/modules/mining/lavaland/necropolis_chests.dm#L538 to dereference the datum to get the atom inside of it.
