### ISSUE TITLE
People don't deathgasp on death anymore

### ISSUE THREAD

**Issue by Shapsy** [tgstation/tgstation#21136]
Deaths are silent now, happens both when you're in a body observing the death, beating the person to death, or observing the death as a ghost

**Comment by CyberbossJHCB** [comment]
@phil235 #20962

**Comment by phil235** [comment]
not me, I didn't touch emotes.

**Comment by Cyberboss** [comment]
@ChangelingRain @optimumtact  #21448 Close this
