### ISSUE TITLE
You can tk hulk punch certain things from a distance.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#21148]
If you have telekinesis and hulk you're able to hit airlocks that you either have access to or are all access. There may be more items that have this problem too, my rampage didn't last long enough to test it fully.

**Comment by ChangelingRain** [comment]
@phil235

**Comment by Durkel** [comment]
Oh, just want to add this.

Technically this isn't a bug, but the shuttle launch console on the escape shuttle should be more resilient, Having some ass beat the console to pieces while you're trying to quick launch is rather unfortunate.

**Comment by phil235** [comment]
That's a bug. My obj damage refactor didn't create the bug but made it more visible. It was already happening with various damageable objects, some of these objects were overriding attack_tk() to avoid the issue (tables, cables) but some didn't have that (grille).
