### ISSUE TITLE
ghosts can alt click abandoned crates

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#21153]
Can type in any code and the crate with react to it.

**Comment by TechnoAlchemisto** [comment]
Stupid ghosts

**Comment by Bawhoppen** [comment]
the neverending bug

**Comment by optimumtact** [comment]
goddamn it every time

**Comment by Supermichael777** [comment]
Remove ghosts

**Comment by lzimann** [comment]
Not an issue, only admins can interact with it(because of mob/dead/observer/canUseTopic() )

**Comment by Shadowlight213** [comment]
Last time I tried this, I was able to do it after deadminning.

**Comment by Mervill** [comment]
Related
#14601
#11683

**Comment by Mervill** [comment]
Also
#20361

**Comment by lzimann** [comment]
I believe all of these were fixed, someone should test again though. Just remember to deadmin if you try, some stuff let admins alt-click even as a ghost.

**Comment by karlnp** [comment]
i don't think these loot tables were ever updated. i suspect abandoned crates don't serve much of a purpose except to generate bugs in the game as stands today.

**Comment by Mervill** [comment]
last time I tried it all I got for my mastermind skillz was a box full of cat collars

**Comment by lzimann** [comment]
No longer an issue(it lets admins alt click it, but not regular players).
