### ISSUE TITLE
HoS spawned as a headrev.

### ISSUE THREAD

**Issue by Owegno** [tgstation/tgstation#21150]
![hosisheadrev](https://cloud.githubusercontent.com/assets/23005535/19623242/2da4d196-9877-11e6-9f8b-f8862a64a29c.png)

What it says on the tin, the HoS was a roundstart headrev, complete with objectives to kill themselves.

Revision was: 975120282b4489ba50f90004ddd27586abb2501d

Happened around 2016-10-23 0:00

**Comment by francinum** [comment]
Who do we blame for this one.

**Comment by optimumtact** [comment]
trust no one, not even yourself

**Comment by Anonmare** [comment]
It's a Feature(TM)

**Comment by MimicFaux** [comment]
Fuck, that's funny. "MY LIFE FOR THE REVOLUTION!!"
It looks like Tyber Riers is attempting to commit suicide!

**Comment by phil235** [comment]
maybe linked to #20950 ?

**Comment by optimumtact** [comment]
@Shadowlight213 this is why you don't touch gamemode

**Comment by optimumtact** [comment]
@Shadowlight213 this is why you don't touch gamemode code

**Comment by Shadowlight213** [comment]
Fuck. I see what's wrong. I'll fix it.
