### ISSUE TITLE
Duplicating fire axes.

### ISSUE THREAD

**Issue by Leon9621** [tgstation/tgstation#21154]
Playing a round as an atmos tech, when I wanted to pop the fire axe back into it's case. As soon as I popped it back in, another seemed to be on the ground and could be picked up while the original axe was in the case. There seemed to be some restrictions, though; I'm pretty sure it only made duplicates if the original axe was popped back into the case, and you needed more than one person to make more than two. I also had the axe sprite on my person at one point, but it didn't appear in either of my hands. I ahd to drop it, then pick it up again to see it there.

**Comment by ShadowDeath6** [comment]
dupe issue

**Comment by PKPenguin321** [comment]
by the way i believe this might be a desync, not a duplication bug. IE the object is in multiple places at once, not that there are multiple objects.
