### ISSUE TITLE
/turf/Entered(); START_PROCESSING(SSobj, src) isn't safe

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#21161]
I have no fucking idea why, exactly, but I managed to get a clockwork floor in the processing list multiple times by quickly entering and exiting it before process, well, processed with me off the clockwork floor I was quickly entering and exiting.

I'm pretty sure it's an internal issue, because START_PROCESSING is supposed to check if it happens to be processing already(and does; `#define START_PROCESSING(Processor, Datum) if (!Datum.isprocessing) Datum.isprocessing = 1;Processor.processing += Datum`)

@MrStonedOne

**Comment by ChangelingRain** [comment]
#21162 is the code in question but I suspect it'd happen even without it; the glow just made it really obvious when it was happening.

**Comment by Carbonhell** [comment]
can't you just replace the += with a |=

**Comment by ChangelingRain** [comment]
Way too much overhead and defeats the purpose of why it's like this at all

**Comment by MrStonedOne** [comment]
ya, the entire reason for using this setup is that removing |= took 7 to 15 seconds off of world startup time.

thousands of items add themselves to processing at world start.

**Comment by MrStonedOne** [comment]
I can't see any reason why this would happen... the codeflow is perfect.

unless..... something was causing the turf to changeturf, in a way that would reset the isprocessing var

**Comment by ChangelingRain** [comment]
Nope, turf wasn't being changed at all/there's no way it could have been; no subtypes and changeturf returns if the type given is the same as the current type

**Comment by MrStonedOne** [comment]
I'll download your repo and test this out.

**Comment by MrStonedOne** [comment]
#define START_PROCESSING(Processor, Datum) if (!Datum.isprocessing) if (Datum in Processor.processing) {throw EXCEPTION("[Datum]([Datum.type]) is already in [Processor]")} else { Datum.isprocessing = 1;Processor.processing += Datum}

I can't get it to happen.

The only explanation I can offer is there are some edge cases that might cause the floor to process last one fire, then process first the next fire, Mainly if it had been in the processing list for a long time, got removed, then readded during a fire. so if the mc was having to spread the processing out across ticks, that would make it seem that the healing is happening multiple times.

**Comment by ChangelingRain** [comment]
The steps to reproduce are "wait for the glow to appear, step off and step back on before the glow appears again, repeat"
It's easiest to see the effect if you're A: a servant of ratvar and B: have like 1 tox damage and godmode on, so you have no slowdown and don't get the damage healed so the result is visible.

**Comment by ChangelingRain** [comment]
Oh, better way to see the issue; 1 tox damage+godmode your mob, spawn a floor, walk on it, and spam the player panel 'jump to mob' command(which forceMoves your mob, the same as entering the turf a large amount of times).

This is what I got doing that, every process tick.
![holy shit](http://puu.sh/rTgrv/b98a9a39a3.png)

**Comment by MrStonedOne** [comment]
alright, I think I see the bug, I couldn't get it to happen, and that means it was one of my changes fixing it. since I only made that change quoted above to trigger a runtime if it's already in processing, and in doing so had to add {} I'm guessing (the test is compiling now) that the normal version `#define START_PROCESSING(Processor, Datum) if (!Datum.isprocessing) Datum.isprocessing = 1;Processor.processing += Datum` the if is only applying to the first command before the ; and adding is happening regardless.
