### ISSUE TITLE
dough is invisible

### ISSUE THREAD

**Issue by somefuckingguy** [tgstation/tgstation#21170]
Dough (made by mixing flour and water) doesn't have a sprite, so you can't see it.

**Comment by Supermichael777** [comment]
its spriting looks valid, is this still hapening?

Note the dough drops at the turf of the container

**Comment by Supermichael777** [comment]
Could not reproduce

**Comment by phil235** [comment]
was there a test merge done recently that changed that sprite file?

**Comment by bgobandit** [comment]
my guess is that somehow you are producing an undefined kind of dough

**Comment by Iamgoofball** [comment]
Maybe its going into something again

**Comment by somefuckingguy** [comment]
It was definitely on the table beneath the beaker I'd used. I could see it in the right click menu.

**Comment by phil235** [comment]
Can't reproduce. I don't really see how this could even happen. The code for dough creation is pretty straightforward and never modifies the icon_state.
