### ISSUE TITLE
After detonation AI nuke spams aborting message.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#21171]
Sybil 10/24/2016
05:19
![AHHH](http://puu.sh/rTCTR/12b8c63379.png)
@KorPhaeron

**Comment by KorPhaeron** [comment]
Not me, @optimumtact and @coiax touched this last as far as I know

**Comment by Shadowlight213** [comment]
Well, it looks like the STOP_PROCESSING call in the destroy is failing or something.

@MrStonedOne any ideas why that could be happening? Could it have anything to do with it ending the round?

Anyways, It looks like the nuke is being qdel'd, which is sending it to nullspace, but it's still processing which is causing it to activate the out of range message.

**Comment by optimumtact** [comment]
This is a shitty error report because it doesn't say if it was after a nuke exploding

**Comment by Shadowlight213** [comment]
Oh.
Yes it was.
