### ISSUE TITLE
DOOMSDAY DEVICE OUT OF STATION RANGE, ABORTING

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#21172]
Nuking as the AI doesn't have the satisfying ending I desire, it just spams "DOOMSDAY DEVICE OUT OF STATION RANGE, ABORTING" when the timer rolls out, but complete with roundend text and **BOOBEEP** endlessly until the server restarts.

**Comment by AnturK** [comment]
Dupe of #21171
