### ISSUE TITLE
Devils should be able to remotely issue a contract for a player or at least be able to do so quietly without the whispering. 

### ISSUE THREAD

**Issue by straycat0000** [tgstation/tgstation#21182]
Devils should be able to remotely issue a contract for a player or at least be able to do so quietly without the whispering. This way a devil could for example walk up to the QM desk, and silently place a contract and walk away and leave the contract for consideration. Especially on crowded maps a devil will be instantly spotted by whispering to people.

**Comment by Shadowlight213** [comment]
This belongs in the feedback forum
https://tgstation13.org/phpBB/viewforum.php?f=10
