### ISSUE TITLE
Add a list of the current character's abilities to the player notes or make it a special status screen. So that "fly people players" can see at a glance what the current traits are.

### ISSUE THREAD

**Issue by straycat0000** [tgstation/tgstation#21188]
Add a list of the current character's abilities to the player notes or make it a special status screen. So that "fly people players" can see at a glance what the current traits are.

**Comment by ChangelingRain** [comment]
Feature requests go in either the [Coding](https://tgstation13.org/phpBB/viewforum.php?f=5) or [Ideas](https://tgstation13.org/phpBB/viewforum.php?f=9) forums.
