### ISSUE TITLE
Pointing at a severed head points at the body it belonged to instead

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#21200]
Probably an issue with brain ownership

**Comment by phil235** [comment]
Cannot reproduce. I tried with both human and changeling decapitation.

**Comment by PKPenguin321** [comment]
Reminds me of that weird bug from way back where you'd point to the HoP's ID and it would point to his desk since they had similar names or something. If that's the case it's a byond bug

**Comment by XDTM** [comment]
Cannot reproduce. Probably closable.
