### ISSUE TITLE
Shooting a table hits the mobs hiding under it.

### ISSUE THREAD

**Issue by phil235** [tgstation/tgstation#21203]
An unintended consequence of https://github.com/tgstation/tgstation/blob/a2f86e6182993fdbab7269ac8c0b03d6f0aa6920/code/modules/projectiles/projectile.dm#L155 which is here to prevent players avoiding projectiles by staying on top of a dense object.

Should be easily fixed by checking if the mobs on that tile are on a layer above the dense object.

edit: apparently larvas would still be shootable when hiding under table since they're currently density = 1. Maybe we could make them density = 0 when using the hiding ability, and make them slower while using it to prevent it being OP. (also applicable to borers probably)

**Comment by Supermichael777** [comment]
Wjohnson give phil his skin back with that alium buff request.

**Comment by ExcessiveUseOfCobblestone** [comment]
this is the only way to shoot them if they're under a table though.

Don't hide under a table in the way of a firefight if you don't want to die.

**Comment by PKPenguin321** [comment]
I don't think checking the actual layer is a proper fix. Don't some vehicles layer you under them while going south, but not other directions?

**Comment by Ordonis** [comment]
Possibly necroing, but I'm not sure there's a fix for this which doesn't involve 
a) Increasing the number of checks when moving/firing near tables
b) Changing a whole bunch of densities to make the table code happy
c) Refactoring how bullets interact with layers
d) Removing guns, thus solving the problem completely

Also, tables aren't the best of cover; can this one be chalked up to 'there is nothing between you and the bullet and some bullets go low also shrapnel' and closed?

**Comment by RandomMarine** [comment]
This seems to be also resulting in a lot of stuff like pipes and cables being damaged because someone shot a girder that was on top of them.

**Comment by phil235** [comment]
@RandomMarine not according to the code I posted.

**Comment by RandomMarine** [comment]
Not originally, but what that piece of code's evolved into today also has it hitting structures too.

**Comment by ArcaneDefence** [comment]
Fixed by kevinz
