### ISSUE TITLE
[FR] Basic runtime checks

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#21220]
Add a script to travis that can start the server, load every map file/ruin, and make sure that no runtimes~~/atmos diffs~~ occur. This would entail fixing said bugs first

**Comment by xxalpha** [comment]
So basically it would fail every time.

**Comment by Shadowlight213** [comment]
Theres some atmos diffs that show up on station, but the map in dm shows nothing wrong.
This isn't really viable.

**Comment by CyberbossJHCB** [comment]
Maybe just runtimes then

**Comment by Shadowlight213** [comment]
Have we fixed every roundstart runtime yet?

Atmos diff unit tests for ruins is a decent idea though.

**Comment by CyberbossJHCB** [comment]
Ruins definitely have some runtimes in them

**Comment by optimumtact** [comment]
please use the code feedback forum for this
