### ISSUE TITLE
Resting humanoids can't be interacted with.

### ISSUE THREAD

**Issue by Archie700** [tgstation/tgstation#21228]
Apparently you can't interact with resting humans now. I don't know whether it's the new BYOND update or something in the code. May make a screenshot of this.

EDIT:
<img width="960" alt="bug" src="https://cloud.githubusercontent.com/assets/17823321/19794807/00e52440-9d08-11e6-804c-6bafe15c76ba.png">

**Comment by Tacolizard** [comment]
it's byond. check the forums. it's fixable

**Comment by Archie700** [comment]
Yep, confirmed it's the latest update.
