### ISSUE TITLE
Borgs that are blown dont appere round end

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#21223]
Borgs blown from the console are not listed on the round end mesage

**Comment by Shadowlight213** [comment]
Not really a bug, since they aren't a borg anymore.

**Comment by Supermichael777** [comment]
its sort of a bug you cant see their laws so you never know that you fucked up and theirfore cant die a little inside

**Comment by jughu** [comment]
But if your blown up which laws did you have?

**Comment by A-t48** [comment]
Ideally it would say the laws the borg had at end of round

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't think this is much of an issue, if you are killed in the process you can examine the AI/Borg or Ahelp.
