### ISSUE TITLE
Unable to click on prone people

### ISSUE THREAD

**Issue by Lobachevskiy** [tgstation/tgstation#21239]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

Hovering over prone (as well as stunned and such) people doesn't actually select them, meaning you can't shoot them directly, or stun baton them, or disarm them, or anything. When cursor is over them, it just shows "floor" in the bottom left. Alt+clicking works, however, and all click actions work from there just fine.

I'm running the latest version of beta byond at the time, 511.1361. Also I have IE9, not 11, dunno if that could be a cause.

**Comment by Shadowlight213** [comment]
Dupe of #21228

**Comment by Lobachevskiy** [comment]
Also, right clicking on the tile shows only the floor (and items if there are any), but not the person/body.

**Comment by Lobachevskiy** [comment]
And since it's a dupe I guess I'll close.
