### ISSUE TITLE
ClockCult's "Kill All Silicons" objective too easy

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#21232]
I don't understand how a group antag would get an objective that is literally as easy as updating a silicon's laws to make them 'kill yourself' in some fashion. You can do it on asimov, even, or just purge and make the only law say "Kill yourself".

**Comment by BrokenCycle** [comment]
Blood cult gotta haul ass to get that sacc but Clock Cuckies just gotta wait for the fuckers to inevitably get themselves killed.

**Comment by GunHog** [comment]
Making it so that you must have at least one AI and a borg converted and alive. But, you are right. This objective is easy unless Security is actively defending the AI; sometimes they do not care, and let them get killed or converted.

Requiring x number of converted silicons active at round's end might fix it.

**Comment by Xhuis** [comment]
How is this a bug @ChangelingRain?
Also, @GunHog makes a good suggestion here. Converting all the silicons would be a good alternative but then we might run into powergame problems where the crew off the AI and card it to prevent the cult from greentexting.

**Comment by KingPhilipIII** [comment]
That's like pretending the cult isn't capable of producing their own AI. Plasteel is hardly contraband for the core, steal a board from tech storage or convert a scientist. Toss in a volunteer or someone you murdered or a soul vessel. Boom. AI.

**Comment by GunHog** [comment]
That is still work! You had to do something to get that AI! It should still count!

**Comment by KingPhilipIII** [comment]
That was a response to powergaming crew. Yes it requires work to make your own AI
