### ISSUE TITLE
Changelings cannot use biodegrade to escape cocoons

### ISSUE THREAD

**Issue by BrokenCycle** [tgstation/tgstation#21233]
Made myself into a changeling via xenobiology. Unfortunately, a spider put me in a cocoon before I burst. Waiting two minutes? Fuck that, bought biodegrade, and it didn't work. Kor had to yank me out of the cocoon.

**Comment by YakumoChen** [comment]
There's actually no way to escape cocoons without outside help.

**Comment by ShadowDeath6** [comment]
You can resist or just hit it from inside if that wasn't changed

**Comment by BrokenCycle** [comment]
If lings can melt cuffs and a straightjacket, they should be able to biodegrade a cocoon.

**Comment by Shadowlight213** [comment]
@yakumochen
Incorrect. Unless it was changed extremely recently, as long as the spider can go on top of you, it can cocoon you. There are like no checks for anything at all except for it being a mob I think.
