### ISSUE TITLE
Can't open wire panel on C4 with screwdriver.

### ISSUE THREAD

**Issue by Grazyn** [tgstation/tgstation#21236]
Spawn C4 from uplink, use screwdriver on it to expose the wires, nothing happens. Use other tools, nothing happens.

Server revision compiled on: 2016-10-28
9efd0b594cfc43751c250bd9a1fa329a17e948a8

**Comment by nullbear** [comment]
Sry.

**Comment by PKPenguin321** [comment]
It doesn't use wires anymore. It can be attached directly to signallers, etc now.

**Comment by TechnoAlchemisto** [comment]
C4 should either be brought up to the functionality is used to have as obj/item/weapon/c4 or reverted back tot he old fully functional path

**Comment by tedward1337** [comment]
Not a bug

**Comment by nullbear** [comment]
Having wires implies it can be hacked or disabled. But once it's placed you CAN'T INTERACT WITH IT WHATSOEVER
