### ISSUE TITLE
Attacking a Cak gives no message

### ISSUE THREAD

**Issue by Grazyn** [tgstation/tgstation#21235]
Hitting a Cak on harm intent is supposed to show "X takes a bite out of Cak", or at least it used to, now it doesn't show anything. Petting it still gives the message.

Server revision compiled on: 2016-10-28
9efd0b594cfc43751c250bd9a1fa329a17e948a8

**Comment by PKPenguin321** [comment]
Phil's thing makes your own attack messages not show up. Intended, but dumb.

**Comment by Grazyn** [comment]
Oh right, I forgot about that. Duh
