### ISSUE TITLE
No way to dump the contents of transit tubes

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#21251]
This is inconvenent if you need to put people in it to rescue them and cant dump them out

**Comment by Bawhoppen** [comment]
Singulo

**Comment by duncathan** [comment]
Transit tubes are a fucking mess

**Comment by nullbear** [comment]
use a crowbar to empty the transit tube.

This already exists as a feature, but may be little known.

**Comment by Mysak0CZ** [comment]
You can also use hand to empty pod, while it is in station.
