### ISSUE TITLE
library archive system is busted

### ISSUE THREAD

**Issue by d4n0w4r** [tgstation/tgstation#21253]
For a good year or so, the library archive system has been nothing but trouble.  Originally, all the books uploaded into the external archive showed up on the librarian's computer in one long list.  Sometime last year, this list was segregated into pages of book titles.  Ever since this happened, the game would crash whenever you try to go past page 3.  Trying to order books by their SSBN doesn't work, either.  Trying to read some books would also crash the game in a similar manner, although I don't know why this happens.
This is what the crashing error looks like:
http://i.imgur.com/vOy663K.png

What I would like is if someone could import /vg/ station's library system.  It's much more stable, and allows for several search options when you're trying to print out books.  I don't know how easy it would be to do this, but I would vastly appreciate it.

http://i.imgur.com/QvDGuCT.png

**Comment by A-t48** [comment]
This is gonna require a db setup to test\fix isn't it?

Maybe related:
https://github.com/tgstation/tgstation/issues/17176
https://github.com/tgstation/tgstation/issues/16180

**Comment by lzimann** [comment]
Gonna try to rewrite this entire library system so it's better. Won't be fast because I have some other stuff to do.
