### ISSUE TITLE
Disposals sometimes ends up in HoP's office on Box

### ISSUE THREAD

**Issue by CyberbossJHCB** [tgstation/tgstation#21262]
We've all been there. Gone to get a job change/more access. Then suddenly, Ian is hit by a medical HUD auto-implanter.

Couldn't believe this wasn't an issue yet

**Comment by Xhuis** [comment]
This is a product of manually rerouting disposal pipes. That's not a bug.

**Comment by PKPenguin321** [comment]
^
go out of your office and walk like 3 tiles to the left and you'll see the maint door there, there's a single pipe you have to rotate to sabotage disposals like this

**Comment by AdamElTablawy** [comment]
it is also hilarious to put a bunch of beakers of chlorine trifluoride in disposal sand watch them all impact the hop at mach 10, ignite, and crit him

**Comment by tedward1337** [comment]
Not a bug

**Comment by optimumtact** [comment]
scrub
