### ISSUE TITLE
510 Stable doesn't render planes right for some people

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#21264]
This is occurring on my system on 510 stable but not 511 latest beta 

---

**Mod edit: -- for people with this issue - first update to the latest 511 beta byond client
Then try the steps listed in https://tgstation13.org/phpBB/viewtopic.php?p=220316#p220316 if you are still having the issue**

The screen will stop updating, any animations playing will freeze. You however will not be frozen and can move around, taking the whole frozen scene with you. As you move the unrendered blank tiles will properly render under the frozen image (the plane?).

Eventually the frozen image will "update" and the new still will replace the old one. Bizarrely I've only seen this off station. It happens constantly when z != 1, but never when z == 1.

This never stops happening. Ever.

**Comment by Incoming5643** [comment]
I'd also like to point out that none of this happens as an observer, it's only when you're actually playing a living mob.

**Comment by Incoming5643** [comment]
here's an image that more obviously portrays the effect:

![d10_icon](https://cloud.githubusercontent.com/assets/4176358/19833122/347414f8-9e05-11e6-8d5e-1b5aa57b503e.png)

The chunk of centcom is the actual true image here, as I moved off the shuttle and to the back of the docking area, the only part of it actually rendering are the tiles blocked by the shuttle wall in the previous "ghost" image.

This never stops happening. Ever.

**Comment by Incoming5643** [comment]
The steps in https://tgstation13.org/phpBB/viewtopic.php?p=220316 and asking some portion of the playerbase to reinstall drivers isn't a valid request anyways.

**Comment by Incoming5643** [comment]
Yes I've noticed this: 5
No I've not noticed this: 13
Pass: 0
Did not vote: 27

**Comment by Incoming5643** [comment]
So this is fixed in the very latest beta build of 511. I got through like 95% of the byond bug report before I realized this... I'm posting it here because I did too much work not to post it somewhere.

THAT SAID: we're currently requiring the playerbase to use the beta build of byond to properly render the game. This is "very bad"™ and we REALLY should remove the use of planes until 511 properly goes gold at the very least!

---

<b>Descriptive Problem Summary:</b>
In TGstation SS13 servers the plane system implemented in (https://github.com/tgstation/tgstation/pull/20707) often fails to update on z levels other than the main station (z = 1).

When this occurs the previous plane image becomes static, and moves with the player until a new plane (usually also frozen) takes its place. This is a little hard to picture so here's a visual.

<img src = "http://i.imgur.com/FDoPdU7.png">

1. How the surrounding area looks.

2. The player initially spawns to the immediate right of the blue wall, hidden black tiles to the west as expected.

3. As the player moves to the eastern grey wall the image from 2 remains static on the screen, the actual motion of the tiles properly shown only on the hidden black tiles from number 2.

4. After a while (erratic, up to 20 seconds!) the static overlay updates, showing the true visuals for standing at the eastern wall. Note that you can make image 3 by overlaying image 2 (minus the black tiles) over image 4. This is only a snapshot, and if we moved back towards the blue wall, the same problem would happen, image 4 would overlay onto image 2.

This happens constantly on z levels other than 1, but not for everyone. Some portion of the player base is affected, and this has nothing to do with the "Use Graphics Hardware for displaying maps" maps (which is on in these screen shots).

Leaving z = 1 by any means starts the issue, and returning to z = 1 by any means fixes it. In SS13 you need to be a mob/living for this to occur, but I believe that's just because other mobs (observers) don't use planes. Moving the cursor over items on the screen correctly shows their proper positions regardless of what the visuals show, so this is a purely visual problem.

<b>Numbered Steps to Reproduce Problem:</b>
1. Have an older GPU/OS(?). Personally I have an NVIDIA Quadro NVS 140M (based on a NVIDIA GeForce 8500M GT). It is a relic of an integrated GPU from 2008 but I never expected this to be relevent for Byond.

2. Be anywhere that isn't z = 1

<b>Expected Results:</b>
The game renders correctly on z > 1

<b>Actual Results:</b>
It's very hard to see what's going on in z > 1

<b>Does the problem occur:</b>
  <b>Every time? Or how often?</b>
Constantly on z > 1, never on z == 1
  <b>In other games?</b>
I do not know of any other byond games using planes, if you know of one I can try I'd be happy to check
  <b>In other user accounts?</b>
Yes
  <b>On other computers?</b>
Unable to check, does not happen on most machines from what the community says, but is not limited to just me.

<b>When does the problem NOT occur?</b>
when z == 1

<b>Did the problem NOT occur in any earlier versions? If so, what was the last version that worked?</b>
Problem seemed to manifest with the addition of planes to the game. Said addition seemed to make no changes to how z levels are handled however. This also occurs as of shit it works on the newest.
<b>Workarounds:</b>
None. Messing with different rendering sizes changes nothing, clicking off "Use Graphics Hardware for displaying maps" does not resolve the problem either (and breaks the visuals in SS13 in other ways anyways).

**Comment by optimumtact** [comment]
You shoudl still post it to byond forums since they may push a hotfix for 510

**Comment by optimumtact** [comment]
also if you think people using the client is bad, wait till you realise we've been running the 511 server for the past couple of months.

**Comment by MrStonedOne** [comment]
as it stands, fixes tend to only come to the beta, so once we get to this point, shortly before the beta is released, using it starts to become a necessity.

That being said, a bug that only some people see, in relation to an issue with their video card drivers, requiring a move to beta to fix isn't that fartetch. I'm not gonna support reverting a rather beneficial change that will lead to us being able to completely remove the whole ghost images mess just because some people have to upgrade to the beta to make it work.

**Comment by optimumtact** [comment]
I've cleaned up this PR a lot so we can centralize discussion to one place.

**Comment by A-t48** [comment]
> . Have an older GPU/OS(?). Personally I have an NVIDIA Quadro NVS 140M (based on a NVIDIA GeForce 8500M GT). It is a relic of an integrated GPU from 2008 but I never expected this to be relevent for Byond.

I have a 980Ti and I still hit this issue with stable.

**Comment by MrStonedOne** [comment]
So far my studies showed its exclusively a nvidia issue.

AMD and Intel graphics work fine.

**Comment by straycat0000** [comment]
I don't think this happens with other z levels. I get this bug very very frequently when:
Switching vision modes for creatures or items that have i.
Playing blob (nearly all the time)

Only a reconnect fixes it.

GF1060 card

However when I play I rarely ever leave the station z.

**Comment by Cyberboss** [comment]
@lzimann 510 issue
