### ISSUE TITLE
Destroying a traitor AI when they enable the doomsday device makes it loop an infinite message.

### ISSUE THREAD

**Issue by Ultimate-Chimera** [tgstation/tgstation#21274]
If an AI gets destroyed when they arm the nuke, it spams "ERROR ER0RR $R0RRO$!R41.%%!!(%$^^__+ @#F0E4 DOOMSDAY DEVICE OUT OF STATION RANGE, ABORTING" over and over.

**Comment by Shadowlight213** [comment]
Known bug
The doomsday device isn't stopping processing.
@optimumtact has a pr up to fix it

**Comment by Ultimate-Chimera** [comment]
Ah.
