### ISSUE TITLE
Bug with toggling Engineering Scanner Goggles

### ISSUE THREAD

**Issue by Blonkz** [tgstation/tgstation#21284]
To reproduce:
Equip engineering scanner goggles. Toggle them on via HUD. Then move character.
Shadows from earlier will move with you, until you turn off the goggles.

**Comment by phil235** [comment]
Sounds like a byond issue. Which version are you using?

**Comment by phil235** [comment]
Most likely a duplicate of #21264

**Comment by Blonkz** [comment]
Was using the stable one. After upgradeing it disapered.
