### ISSUE TITLE
Telescopic baton seems a bit op

### ISSUE THREAD

**Issue by A-t48** [tgstation/tgstation#21297]
100 percent knockdown even vs HoS armour. There's a bunch of them floating around the station, too. With other stuns there's some defense or downside -

Flash is defeated by sunglasses
Taser runs out of ammo pretty quickly, is dodgeable and is fucking obvious when you are using it.
Slips are annoying, but at least in general they are either visible, defeated with walk, or fixed in place.

Could we make body armour have some defense against them? 

Inb4 "it killed me it must be op!"

**Comment by PKPenguin321** [comment]
it has basically the same strengths as a stun baton, not an issue, feedback forum

**Comment by Tacolizard** [comment]
the baton makes a loud as fuck noise when you extend it and is easy to see. it's also just a stun so armor dosn't matter.

**Comment by PKPenguin321** [comment]
>>>>>>not an issue, feedback forum

**Comment by bgobandit** [comment]
it also lasts for basically zero time

**Comment by phil235** [comment]
Not a bug. Feedback goes into the feedback forum.
