### ISSUE TITLE
After assuming a players dna when playing ling I can hear dead chat

### ISSUE THREAD

**Issue by straycat0000** [tgstation/tgstation#21296]
After assuming a players dna when playing ling I can hear dead chat

**Comment by Tacolizard** [comment]
more info ples

**Comment by Tacolizard** [comment]
#21277 ?

**Comment by straycat0000** [comment]
Not sure if related to that bug. Here is what happened. I slurped out the dna of a player, then used the ability to appear like him. Then I was able to hear ALL dead chat all the time, even after transforming back to my own character's appearance. All with 23/10/2016 code.

**Comment by Shadowlight213** [comment]
What's your ckey/the name of the character you played that round?

I'm not seeing anything in the runtimes log for the 23rd, but it would help if I knew what I was looking for.
