### ISSUE TITLE
Hulks are able to bypass syndicate shielded hardsuit shields and armour, dealing a load of direct brute damage.

### ISSUE THREAD

**Issue by jakeramsay007** [tgstation/tgstation#21294]
Exactly what it says on the tin. Seems like it wasn't intended for hulks to be able to do it.

**Comment by CyberbossJHCB** [comment]
#justhulkthings

**Comment by ChangelingRain** [comment]
hulksssssss

**Comment by phil235** [comment]
Afaik shielded hardsuits only protects against projectiles.

**Comment by jakeramsay007** [comment]
@phil235 Nope, they protect against melee attacks too. And lasers. And pretty much everything to be honest, even flying objects.
