### ISSUE TITLE
Wearing Mesons Makes Shadows "Hover"

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#21293]
I don't really know how to describe this, other than this:

If you're wearing mesons and there's shadows in vision range and you move in any direction, the shadows will affix to your screen and stay with it--this can be corrected by removing your mesons and putting them back on, though, it'll just generate a new set of shadows that affix to your screen, instead.

**Comment by jakeramsay007** [comment]
Update to 511 beta.

**Comment by optimumtact** [comment]
See #21264 and associated
