### ISSUE TITLE
Backpack is impossible to take off at high resolutions

### ISSUE THREAD

**Issue by A-t48** [tgstation/tgstation#21301]
If I have my game fullscreen at 1440p, I can't take off my backpack. Lower resolutions work. I suspect this has to do with the cursor going over the space between the icons

**Comment by AnturK** [comment]
Check again on fresh byond version, there were some issues with click interception in fresh .1361

**Comment by GunHog** [comment]
You can also mousedrop your pack to your empty hand in order to remove it.

**Comment by A-t48** [comment]
Mousedrop? That's just click drag, right? That's what I've been doing. Or is it some other obscure BYOND mouse gesture?

**Comment by ExcessiveUseOfCobblestone** [comment]
@A-t48 is this still an issue

**Comment by A-t48** [comment]
Unsure! I think updatingbfixed it

**Comment by Iamgoofball** [comment]
I use 1440p can't reproduce

**Comment by MrStonedOne** [comment]
@tgstation/commit-access
