### ISSUE TITLE
Crew Monitoring crashes system

### ISSUE THREAD

**Issue by JayIRay** [tgstation/tgstation#21328]
About 90% of the time when I use a crew monitoring system the game will crash. Sometimes it'll work, usually when there are less people on.

**Comment by YakumoChen** [comment]
set tgui off the 'fancy' selection in prefs

**Comment by PKPenguin321** [comment]
>set tgui off the 'fancy' selection in prefs

I don't think this is why. I believe it's the completely broken minimap thing.

**Comment by JayIRay** [comment]
I set it to no frills but it still doesn't work and looks the same.

**Comment by Shadowlight213** [comment]
Crew monitor doesn't use tgui. It uses some alternate html system.
As for the minimaps, I find it unlikely they are the cause. I'm fairly certain lummox fixed the issue with the generation, and besides it would cause the server to crash, not the client.
It must be some issue with the suit sensor data being sent and rendered.

**Comment by optimumtact** [comment]
Minimaps are a server crash not a client one.

If your machine is simply not very powerful it may not be able to handle and render the data being displayed.

Can you reveal your OS specs or browser?

**Comment by JayIRay** [comment]
It's a toaster, Toshiba Satellite C55. I thought that it would be a performance issue. 1.8Ghz cpu, Intel HD integrated graphics, and 4GB of RAM. Is there any sort of work around?

**Comment by vuonojenmustaturska** [comment]
the crew monitor with its multitude of issues is no longer in the game
