### ISSUE TITLE
Being decapitated as a devil makes it impossible to revive. 

### ISSUE THREAD

**Issue by KingPhilipIII** [tgstation/tgstation#21321]
Right. So this happened a while ago. I was doing my infernal thing. Going around. Offering deals, harassing the chaplain who wouldn't stop spraying me with holy water. Eventually things got violent and security got involved. I was beaten to a pulp and the Chappie decapitated me with his chain sword. Despite having a lesser infernal form( Lizard person.) and having six souls, I never revived. 

This is kind of a problem maybe. Maybe it's intentional, but info regarding the devil says only being banished or being repeatedly beaten into the ground can get rid of them, so it's a bit deceptive if that was the intended mechanic. The reason I think it's a bug though is I got the message to remain in my body. Stayed in my severed head. Eventually the 'WE RISE AGAIN!' Message appeared but I was not revived. 

 I know Changelings can revive without heads. Could that code be cannibalized for this?

Any other info that might be relevant was I was a TC trade Devil.

**Comment by lordpidey** [comment]
Good catch, I'll fix this in datum devils.

I'll just have a new body be created if the old one is unsuitable.  (Similar to how devils get a new body if gibbed).

**Comment by KingPhilipIII** [comment]
I guess it has to do with how the player is attached to the brain, and subsequently the head, rather than the body. And it doesn't understand how to generate a new body for the head. 

This makes me wonder. If Changelings are attached to their body. What would happen if you surgically reattached someone's head to a decapitated changeling and revived them via cloning or defib?

**Comment by lordpidey** [comment]
I think it might have to do with bodies needing a brain to revive under normal circumstances.  I'll look into it.
