### ISSUE TITLE
Highlander Bug:Everyone is the only left standing

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#21332]
![AHH](http://puu.sh/s3ECb/16a9354fb0.png)
And then we were treated to 19 last man standing oggs played simultaneously.
@Xhuis

**Comment by PKPenguin321** [comment]
the ear rape from this is funny as fuck to be honest

**Comment by Xhuis** [comment]
Oh my fucking god how do these things happen? Lmfao I'll get this patched once I get home

**Comment by Xhuis** [comment]
I'm not seeing how this can happen. If you check [the code for claymores](https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/weapons/weaponry.dm#L120), this can only trigger if there's only one claymore, which should always be the case except when everyone else is dead.

Thoughts?

**Comment by PKPenguin321** [comment]
something about the shuttle docking must be triggering the check despite there being more than one claymore

**Comment by Shadowlight213** [comment]
For reference, the part in the logs where it happened was right after [04:16:48] on 2016-11-02.
Oddly enough, I don't see any related runtimes that round.
