### ISSUE TITLE
Ice never fucking melts

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#21330]
I've seen fires burning over ice, but nothing ever seems to get it to melt.

**Comment by Bawhoppen** [comment]
which kind of ice

**Comment by GunHog** [comment]
Ice formed as a result of freon, I suspect. Freon + Plasma fire is one of the deadliest killers. Especially with Phil's global object damaging system causing people to lose their suits!

**Comment by XDTM** [comment]
Intended by goof, but i agree it shouldnt be permanent.

**Comment by Iamgoofball** [comment]
THIS WASN'T A BUG @Dorsisdwarf FUCK YOU
