### ISSUE TITLE
Somehow had toolbelt and backpack overlays open at the same time

### ISSUE THREAD

**Issue by zig-for** [tgstation/tgstation#21336]
![wut](https://cloud.githubusercontent.com/assets/8206540/19939853/d399a93c-a0e7-11e6-8b03-0bd08ea96c56.png)

Not sure what happened.

**Comment by Cyberboss** [comment]
Yeah I noticed this a while ago. Something in my routine setting up of my inventory as HoS makes it happen consistently. Just need to figure out what.

**Comment by deranging** [comment]
I've seen this happen recently

**Comment by ShizCalev** [comment]
Still an issue?
