### ISSUE TITLE
Dead alien headcrabs still move when in your hand

### ISSUE THREAD

**Issue by A-t48** [tgstation/tgstation#21331]
![image](https://cloud.githubusercontent.com/assets/8206540/19916578/7308377e-a078-11e6-9494-eef2ee38af8e.png)

**Comment by jughu** [comment]
Not a bug? More a sprite issue its not like they gonna add a special inhand sprite because its dead

**Comment by Bawhoppen** [comment]
We can do exactly that

**Comment by jughu** [comment]
N0 TO MUCH EFFORT

**Comment by RemieRichards** [comment]
4 lines of effort
WOW

**Comment by Anonmare** [comment]
4 lines is 4 too many

**Comment by Cyberboss** [comment]
unable to repro

**Comment by Cyberboss** [comment]
https://github.com/tgstation/tgstation/blob/eace4eec148e8a366ee2fe6673f852b59a2e77b1/code/modules/mob/living/carbon/alien/special/facehugger.dm#L216

Seems fine to me

**Comment by A-t48** [comment]
Aha. This is a ruin specific bug.

![image](https://cloud.githubusercontent.com/assets/8206540/20044103/aa2d1456-a44a-11e6-8a67-c50e8a3ce1f0.png)

**Comment by Bawhoppen** [comment]
Oh yea, I think when I made that ruin, I copy-pasted the dead huggers from the abandoned mining outpost (which obviously doesn't exist anymore)
