### ISSUE TITLE
You can no longer run and examine at the same time.

### ISSUE THREAD

**Issue by TechnoAlchemisto** [tgstation/tgstation#21343]
Using the shift + click hotkey will have you walk until you release shift, even with hotkey mode off. 

If it's intended cool, but I don't quite think it was when the walk hotkey was made.

**Comment by kevinz000** [comment]
Walk hotkey should be a pref, this is extremely annoying, I try to do exactly this and slow down to a crawl.

**Comment by BeeSting12** [comment]
>chasing criminal
>try examining
>lose him because of this hotkey
I think there's better keys to bind this to.

**Comment by phil235** [comment]
#21039

**Comment by Cyberboss** [comment]
@BeeSting12 There literally isn't, frankly I regret proposing that hotkey

**Comment by jughu** [comment]
>people cant make their own macros

**Comment by TechnoAlchemisto** [comment]
using macros is dirty
