### ISSUE TITLE
Prostetic replacement does not work. When putting the drapes, it just makes a thud sound and any scalpel interaction will stab.

### ISSUE THREAD

**Issue by straycat0000** [tgstation/tgstation#21355]
Prostetic replacement does not work. When putting the drapes, it just makes a thud sound and any scalpel interaction will stab. code from 23/10/2016

**Comment by Tacolizard** [comment]
it does work. you need to cauterize any surgery that the patient has undergone before you do another.

**Comment by straycat0000** [comment]
Are you sure? Because the arm was lost in combat, not a previous surgery

**Comment by phil235** [comment]
Were you aiming at the correct limb zone? Did you check the surgery console to see if there was some surgery already started? Were you on help intent?

**Comment by Supermichael777** [comment]
We need bay-surgury

**Comment by straycat0000** [comment]
Why do you ask me if I was on help intent. Don't you think that would not have been the first thing I checked?

**Comment by Cyberboss** [comment]
It's really easy to get confused with previously started surgeries. This probably isn't a bug. We should probably have surgeries time out after a while if nothing happens in their steps.

**Comment by Dorsisdwarf** [comment]
Could not reproduce.
