### ISSUE TITLE
Sometimes, grass tends to take a long time to harvest

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#21350]
**I haven't checked with non DNA manipulated grass**, but I've noticed that grass seeds, having maturation speed 2 and modifying it to have production speed 1, will sometimes take a lot longer to mature/be ready for harvest. Last time this happened to me, it went past age 15 without any harvest.

**Comment by Tacolizard** [comment]
i think this is happening with a lot of plants. it seems to me like production speed isn't working properly.

**Comment by ShizCalev** [comment]
Is this still an issue? Will close in a week without any more reports.
