### ISSUE TITLE
Monkeying someone removes cloneless.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#21367]
1. start a cloning
2. turn off the apc
3. drag the human to the genetics modifier and make him a monkey real quick
3. turn back into human
4. enjoy being back in the round in under 20 seconds.

Props to the player Lydia Alice for being a shithead and using the bug.

Someone drop a high priority on this.

**Comment by phil235** [comment]
So the clone damage are healed by monkeying?

**Comment by PKPenguin321** [comment]
Do monkeys even have cloneloss
