### ISSUE TITLE
The Celestial Ark doesn't actually proselytize everything when Ratvar isn't summoned.

### ISSUE THREAD

**Issue by KingPhilipIII** [tgstation/tgstation#21360]
I don't know if this has been fixed since I last witnessed it, but the last time I invoked the gateway and we managed to defend it, even though Ratvar didn't come forth, the AI sat(Where we had the gateway) was totally converted, but on further parts of the station such as past engineering, here and there there was clockwork stuff, but not totally.

I don't know if it's a bug or just how it was intended, but I was always under the impression it made EVERYTHING brass, so it was a little disappointing. Maybe it was a one time thing, but if it wasn't reproduction is as simple as making a gateway without intending to summon Ratvar and waiting.

**Comment by ChangelingRain** [comment]
It's not everything but it does convert absolutely everyone who didn't happen to be in a closet or locker at the time. "Everything" is kind of just an exaggeration for effect.

**Comment by KingPhilipIII** [comment]
The lack of Clockwork Station saddens me.
