### ISSUE TITLE
Pinpointers broke after nuke defused

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#21373]
(About 12:00 pm, EST, bagil.) Nuke ops round, I was the leader. Blah blah blah, skip to the part where we had the disk. Someone set the nuke and left it in arrivals with the disk in it and code entered. The AI apparently disabled the nuke. The pinpointers automatically point toward the Syndicate ship once the nuke is armed, and when it was disarmed, the pinpointers wouldn't point toward the disk. We had a pretty good chance of getting the disk back, but the pinpointers wouldn't tell us where it was- just where the ship is parked.

**Comment by jughu** [comment]
The real bug is here that ai turns the nuke off ots confirmed syndiecate nuke has a wifi port

**Comment by Anonmare** [comment]
It's a Nanotrasen brand nuke, of course it has wi-fi. How else are they supposed to compete with competitor brand nuclear devices?

**Comment by CPTANT** [comment]
Why don't pinpointers just have a mode selection?

**Comment by Xhuis** [comment]
Mainly because I didn't think of it when I refactored them. It would also be clunky to use and largely unnecessary with conventional ones.

**Comment by CPTANT** [comment]
Clunky to use?

click - the pinpointer now points to the disk
click - the pinpointer now points to the AI
click - the pinpointer is now off

how is that clunky.....

**Comment by Xhuis** [comment]
That kind of self-activating cycle - the same way we had old suit sensors and beaker transfers - is both really bad code-wise and means that if you go one over you have to go through all the options again. Similarly, it wasn't an important enough issue that using an input for every activation was justified.

**Comment by CPTANT** [comment]
Wow, all 3. In the future when antag datums will allow multiple threats to occur at once the lack of this option will become a problem.

**Comment by Xhuis** [comment]
A pop up window is an input, in case you didn't know. As for the future, I'll burn that bridge when I come to it. Now then, let's stop continually posting on an issue, and put this in the Minor Suggestions thread on the forums - that's what it's there for.
