### ISSUE TITLE
When playing alien, turning on night vision, then smashing a nearby light source causes the shadowed tiles to freeze in place and parts of the screen appear to be frozen and move with the player.

### ISSUE THREAD

**Issue by straycat0000** [tgstation/tgstation#21377]
When playing alien, turning on night vision, then smashing a nearby light source causes the shadowed tiles to freeze in place and parts of the screen appear to be frozen and move with the player.

Fixes itself most of the time by turning off the nightvision.
Happens on tg build from 23/10/2016.

This happens on the station Z level and is NOT caused by being on a different z level.
Nvidia 1060 card.
510.1347
5.0 Public

**Comment by phil235** [comment]
update byond to the latest version. See #21264
