### ISSUE TITLE
Teslium can destroy Syndicate Nuclear Devices(And possibly other indestructible objects.)

### ISSUE THREAD

**Issue by KingPhilipIII** [tgstation/tgstation#21382]
Right. So this happened a little while ago. Nuke Ops. I'm the leader, team goes in, takes the Captain out in Cargo(LMG in your face son.) and then we plant the nuke. Code Delta, get out of there, we think we won. I set the nuke for three minutes. 

Three minutes later the station is still intact. Other surviving Nukie and I just figure it's been less than three minutes later. Five minutes later were pretty confused. Seven minutes later we head back to the station. We go to where we planted the nuke(Anchored and disk secured.) and it's gone.

After we get over the initial shock of our nuke is missing, the other nukie scrounges through some scrap on the ground and finds a green plutonium core. Someone destroyed our nuke. After the round we found out the CMO used Teslium to destroy our nuclear bomb via OOC.

It was to my understanding the nuke was supposed to be indestructible, so just slap on a 'Not a Bug' label if it isn't, but otherwise I think that was kinda bullshit.

**Comment by phil235** [comment]
https://github.com/tgstation/tgstation/blob/25daa7b5f18bc7a2a74a6313212f756574245539/code/modules/reagents/chemistry/recipes/pyrotechnics.dm#L380
then
https://github.com/tgstation/tgstation/blob/b5b4037e2eeae424ce7580b29f1597bdc1d4e501/code/modules/power/tesla/energy_ball.dm#L264
and finally
https://github.com/tgstation/tgstation/blob/d4943f83ef18fef5ff33778578ca2b60e8127b5a/code/game/gamemodes/nuclear/nuclearbomb.dm#L404

**Comment by KingPhilipIII** [comment]
I don't understand code. At all. Please use simple English.

From what I can decipher from that, it makes a tesla ball, which blows up electrical objects(Which the nuke is one) and then deletes it.

**Comment by Delimusca** [comment]
wtf, that comment on the nukes tesla_act(). why would someone delete game critical structures on purpose instead of just removing the explosion call?

**Comment by GunHog** [comment]
Just make it Tesla proof, sure the singulo can eat it, but that should not be the case for Tesla.

**Comment by jughu** [comment]
Why does it needs to be the difference it isnt singulo prove why should it be tesla proof they both destroy pretty much anything

**Comment by GunHog** [comment]
Because otherwise you need to nerf Teslium and anything else that can use telsa shocks to the point it causes explosions, else you will have this situation again.

**Comment by PKPenguin321** [comment]
Ahem my bad
I was going to report this myself but wasn't able to reproduce, I guess it is an issue after all though. Tesla_act deletes nukes and grav gen to be comparable to singulo. Just need to do the thing @kevinz000 did to make sure that it's a zap from a real tesla before deleting the obj.

**Comment by PKPenguin321** [comment]
Plus making it not get destroyed would cause it to just explode over and over

**Comment by Delimusca** [comment]
couldn't you just make them both not explode?
it's not like tesla wouldn't be round ending without deleting those things.

**Comment by PKPenguin321** [comment]
I guess, but a proper fix still exists

**Comment by XDTM** [comment]
Nuclear bombs are machinery, simply removing the tesla_act override should make it explode on a real teslaball but not on teslium grenades

**Comment by kevinz000** [comment]
Woops

**Comment by PKPenguin321** [comment]
Not your fault, it was mine
