### ISSUE TITLE
Orbitting sometimes doesn't cause the orbitting effect

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#21385]
Every once in a while, stuff just doesn't get the orbitting effect, even though it's still following the target around. I'm pretty sure it's clientside, as one of the people I questioned about it said they still saw the orbitting thing orbit visually.

**Comment by Bawhoppen** [comment]
Surely this is a dupe this bug has been noticed for months

**Comment by ShizCalev** [comment]
Still an issue?

**Comment by ShizCalev** [comment]
Will close in a week without further report.
