### ISSUE TITLE
Wish Granter Immortality conflicts with cloning process.

### ISSUE THREAD

**Issue by Repukan** [tgstation/tgstation#21392]
If you get the wish granter immortality buff, trying to use it will trigger the normal cloning cycle when you die. When the cloning autoprocess finishes, you will be pulled out of the old body into the newly cloned body.

**Comment by YakumoChen** [comment]
conflicts the same with changelings and other attempts to revive people who are freshly dead

**Comment by Shadowlight213** [comment]
Probably needs a check and failure case for the person still being alive on clone completion.

**Comment by ExcessiveUseOfCobblestone** [comment]
#22528
