### ISSUE TITLE
ling stasis does not regenerate internal organs.

### ISSUE THREAD

**Issue by CPTANT** [tgstation/tgstation#21408]
Be a Ling, loose lungs and die. Revive and you still have no lungs, you can't speak and die of oxygen damage.

**Comment by XDTM** [comment]
Use the Regenerate skill that lings start with, it's there for that reason.

**Comment by PKPenguin321** [comment]
I've gotten reports that that doesn't work for lungs either

**Comment by jughu** [comment]
Why do lings need to breathe first place

**Comment by CPTANT** [comment]
@XDTM 

Even if regenerate would work it seems horribly inconsistent that ling stasis heals everything except your lungs, stasis also regrows limbs.

**Comment by factoryman942** [comment]
Stasis doesn't do limbs
I've been decapitated before as ling, and revived with no head

**Comment by CPTANT** [comment]
well it did regrow my legs last time.

**Comment by PKPenguin321** [comment]
Stasis regrows limbs, but not the head

**Comment by CPTANT** [comment]
I thought your mind resided in the head in the first place.....

**Comment by PKPenguin321** [comment]
Not for lings

**Comment by CPTANT** [comment]
Tested this again, regenerate does not regenerate lungs.

**Comment by CPTANT** [comment]
Ok small comment on this: There IS no restore organs function, ANYWHERE in the code.

**Comment by PKPenguin321** [comment]
Also I noticed that regular revives like healing staff doesn't regenerate organs, so yeah this is the real issue

**Comment by CPTANT** [comment]
Well I guess this is significant enough of a change to warrant opening a new more general issue.
