### ISSUE TITLE
guns dont log when they miss

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#21409]
Technically a feature request but this is getting to be a real issue and needs to be done ASAP, too many ahelps are left practically unresolvable due to this since one side can claim "he was shooting at me" and I have no way to discern if it's a lie.

**Comment by phil235** [comment]
Can't log misses, but we can log when someone fires a gun.

in projectile/proc/fire():
```
if(firer && original)
add_logs(firer, original, "fired at", src)
```

or something.

**Comment by PKPenguin321** [comment]
That would work 

Maybe log the area as well
