### ISSUE TITLE
People randomly stop being able to equip items

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#21415]
The items go directly into their contents without going into the slot for some reason, I don't know why. Putting the player in a new body fixes it, though.

**Comment by PKPenguin321** [comment]
I think this is a dupe, IIRC it happened to @kevinz000 before

**Comment by lzimann** [comment]
maybe an item not being properly unequipped and not removed from the wear_ var...

**Comment by phil235** [comment]
related to #20416 ?

**Comment by Shadowlight213** [comment]
Should be fixed by #21422
