### ISSUE TITLE
Deca-code Lock Chest is not solvable 

### ISSUE THREAD

**Issue by Cobraman202** [tgstation/tgstation#21410]
Problem Description: The abandoned crate on the mining outpost isn't solvable. Its based on the game mastermind, but it will only give the "A red light flashes" instead of giving either, No lights flash, or light 1 flashes red, light 2 flashes red, etc   

What did you expect to happen: It to play like mastermind.
What happened instead It gave no feed back for which positions were right, In fact, Kore spawned a second one in for me to test and I got no green lights that time aswell . The odds for guessing the number correctly are 10/5040(10 guesses 5040 solutions)

Why is this bad/What are the consequences: If someone trys to open the chest by just randomly guessing, they blow an important chunk of the mining station up

Steps to reproduce the problem: The most important section. I walked into the room where the chest is on the mining station, prayed for the code, got told by Kore it was mastermind, proceed to play, got the code wrong 10 times, got blown up.

Server: Which server were you playing on? Bagil

Revision: What revision was the server running? 146f057545cfe7f4455d776038a9720a09562f71 

Possibly related stuff: None

**Comment by Supermichael777** [comment]
use multitool after attempt

**Comment by ExcessiveUseOfCobblestone** [comment]
where did you get 5040 from?

**Comment by Cobraman202** [comment]
@excessiveuseofcobbl3stone 10 possible number for the first combo, 9 for the second, 8 for the third, 7 for the fourth. 10 × 9 × 8 × 7=5040

**Comment by lzimann** [comment]
this is not a bug, use a multitool for feedback
