### ISSUE TITLE
HUD Shows wrong arm as missing

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#21412]
![glitch](https://cloud.githubusercontent.com/assets/22053757/20083681/d3fc3884-a52b-11e6-86c6-96f0ad8ff9dd.png)
This is Edward Sloan!
He is wearing   a grey jumpsuit.
He is wearing   a black bandana on his head.
He has   a leather satchel on his back.
He has   a toolbelt about his waist.
He is wearing   some blood-stained black shoes on his feet!
He has   a radio headset on his ears.
He is wearing   PDA-Edward Sloan (Assistant).
His left arm is missing!

Examination and your sprite shows the left arm as missing. Your hud has a mark over the right hand, and it shows the left hand as functional. 11/7/16, 8:54 p.m., EST- Bagil.

**Comment by BeeSting12** [comment]
Just lost the opposite arm and it showed up properly on the hud, I think the hud is glitched to only show the right hand as missing.

**Comment by phil235** [comment]
yet more issues wih hand index...

**Comment by RemieRichards** [comment]
@phil235 same one no doubt, Lziman's PR that oranges was going to revert but then didn't.

**Comment by A-t48** [comment]
I'm planning on working on this issue today, unless @RemieRichards is gonna go for it

**Comment by RemieRichards** [comment]
Actually, this isn't an issue at all (unless you have more/new info)
The healthdoll is facing the player, as such *THEIR* left arm is on the right, same for the legs.
While this may seem odd, this actually matches the Aimdoll in the bottom right too, so it's consistent.

Nonissue.

**Comment by PKPenguin321** [comment]
Remie, look again. The aimdoll has an L and an R on its sides to denote which side you're looking at. The left arm on the health doll is missing. The hands on the hud show that the right hand is unusable

**Comment by RemieRichards** [comment]
@PKPenguin321 Yes, the aimdoll FACES THE PLAYER, that's what the inverted R and L represent.
the Healthdoll follows the same logic.

**Comment by PKPenguin321** [comment]
Alright, but the actual player sprite is also facing south, and you can clearly see that this left arm is off, yet the hands HUD claims his right arm is off.

**Comment by RemieRichards** [comment]
@PKPenguin321 because the HUD is facing THE PLAYER.

Both the player sprite and the doll are "facing south" it's just the Aim and Health dolls will ALWAYS face south.

It's consistent, and not an issue, seriously, just look at the picture above, it's correct.

**Comment by PKPenguin321** [comment]
No, I mean look at this http://i.imgur.com/kn0avoD.jpg

It says the Right hand is missing, when every other sprite says the Left is missing.

**Comment by RemieRichards** [comment]
Oh well that's just indexes, which was fixed 4 days ago so the issue was just a dupe is all.
