### ISSUE TITLE
ghostize returning null when it shouldn't be

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#21427]
Ok. I've spent hours trying to fix a bug with mind swap that seems to stem from this.
Here is the code for ghostize
```
/mob/proc/ghostize(can_reenter_corpse = 1)
	if(key)
		if(!cmptext(copytext(key,1,2),"@")) // Skip aghosts.
			var/mob/dead/observer/ghost = new(src)	
			SStgui.on_transfer(src, ghost) // Transfer NanoUIs.
			ghost.can_reenter_corpse = can_reenter_corpse
			ghost.key = key
			return ghost
```

I've put a debug statement `world << ghost` between `ghost.key = key` and `return ghost`.
It properly shows the ghost.

However, when I do `var/ghost = mob.ghostize(0)` in another proc, doing `world << ghost` returns null.

For reference, here is where it's used in the code itself.
https://github.com/tgstation/tgstation/blob/master/code/modules/spells/spell_types/mind_transfer.dm#L73
As ghost is returning null,  mindswap runtimes and the victim is ghosted and not swapped into the caster's body. This is the cause for #21417.

I've already asked incoming and oranges on how to solve this in coderbus, and both of them were stumped as well.
@phil235 please save us all.

**Comment by Incoming5643** [comment]
My gut here is that somehow the ghost is being recreated in a race condition. Possibly a problem that's been around for a long time, but only recently became obvious due to some speed improvement/deprovement elsewhere.

**Comment by Shadowlight213** [comment]
Github search has failed me, and Joan is has angered me
