### ISSUE TITLE
You can re-mag emagged borgs to change master

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#21430]
Borgs shouldn't be able to be emagged twice, but in a recent round I had a borg that changed masters after I emagged it (I build the borg and emagged it originally so it should have been slaved to me)

**Comment by jughu** [comment]
I mean if i emagg a borg of a traitor AI it doesnt change laws at all why would even work

**Comment by CPTANT** [comment]
why not?

**Comment by RemieRichards** [comment]
Intended.

**Comment by YakumoChen** [comment]
>intended

When did this change?

Also does this affect malf borgs now? Because before they just got a message stating someone tried to emag them and canceled it out.

**Comment by YakumoChen** [comment]
> if(syndicate)
		src << "<span class='danger'>ALERT: Foreign software execution prevented.</span>"
		log_game("[key_name(user)] attempted to emag cyborg [key_name(src)], but they were a syndicate cyborg.")
return

**Comment by RemieRichards** [comment]
```syndicate``` != Emagged borg.
The ```syndicate``` var means a Nuke Ops' borg.

**Comment by YakumoChen** [comment]
/shrug

I think it's dumb but if it's intended I guess it can be closed

**Comment by RemieRichards** [comment]
I actually found the PR, too
@YakumoChen 
https://github.com/tgstation/tgstation/pull/10830

(was hard to find, the file's history is all jank)
