### ISSUE TITLE
Facehuggers can latch onto bodies without a head

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#21437]

**Comment by Shadowlight213** [comment]
So, do they work like halflife combine headcrab zombies then? Latch onto the neck hole?

**Comment by A-t48** [comment]
Yeah, why can't they just impregnate your neck?

**Comment by WJohn** [comment]
I mean you're not exactly alive if you don't have your head.

Oh wait, changelings exist.

Shit. Gotta cover every base, exception, and eventuality then, huh?
