### ISSUE TITLE
2 Disposal Units in Xeno don't work properly

### ISSUE THREAD

**Issue by Lakart** [tgstation/tgstation#21458]
On MetaStation

The disposal unit at the top of Xenobiology(below the chem dispenser) throws things into the kill room instead of out into space.

The disposal unit at the bottom of Xenobiology(connected to the test chamber) throws things out on the window block instead of into the pen.

Noticed this issue a few weeks ago and keep forgetting to report it.

**Comment by Mysak0CZ** [comment]
Replicated and found probkem, there are missing pipes (trunk under cute in test chamber and pipe under rwall in killing room). It will be my first map edit, but i will try to fix it.
