### ISSUE TITLE
Borer round end report doesn't distinguish between ghostless slugs and hosts

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#21459]
When the round end report came up one round, it showed 26 borers alive and 6 hosts escaped.
We weren't able to tell how many of them were actually player controlled or in hosts but just didn't escape.

It's super hard to track how many borers you actually have.

@uraniummeltdown

**Comment by uraniummeltdown** [comment]
I'll redo the borer roundend report to be more like the cult one
