### ISSUE TITLE
Vote to restart bugged out.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#21467]
![voterestart](https://cloud.githubusercontent.com/assets/4581352/20188831/57c530ce-a772-11e6-9d7f-1ffe4c21156c.png)

9 votes to restart, 15 continue, game said it was tied and voted to restart..
Followed by another vote result saying to continue playing.
Absolutely no end round results either, bit weird.

**Comment by jughu** [comment]
To add on this 3 people wanted to continue the round and 8 people wanted to restart those were the confirmed votes others are afk

**Comment by A-t48** [comment]
Restart Vote
Restart Round: 10
Continue Playing: 5
Vote Result: Restart Round
Rebooting World in 40 seconds. Restart vote successful.
(F) DEAD: Shizuka Marikawa says, "how emo of you"

Restart Vote
Restart Round: 10
Continue Playing: 9
Vote Result: Restart Round
Rebooting World in 40 seconds. Restart vote successful.

Restart Vote
Restart Round: 10
Continue Playing: 13
Vote Result: Continue Playing

**Comment by KorPhaeron** [comment]
@Onule 

It auto fails with an admin online. Was an admin online?

**Comment by MrStonedOne** [comment]
it prints a message to the players when that happens. 

The `Rebooting World in 40 seconds.` tells me world.reboot was called. so i'm stumped.

**Comment by Onule** [comment]
@KorPhaeron Been a while.. If I remember correctly, there were no admins on.

**Comment by ShizCalev** [comment]
Will close in a week without another repo.
