### ISSUE TITLE
Brains are not being assigned a ckey when it is removed from a body

### ISSUE THREAD

**Issue by lzimann** [tgstation/tgstation#21463]
After surgery/removed by opening a dismembered head, you won't enter the brain, requiring an admin to put you in. I believe it started happening after borers were added.

**Comment by Cyberboss** [comment]
https://github.com/tgstation/tgstation/commit/ea81370dcef1a85e1c23ccf3b415915fe15484ab#diff-caf13efe3a77e81b49a7ad1dd2db9fec

Something must be wrong here, but it's too early for me to understand it

**Comment by uraniummeltdown** [comment]
there are a few unnecessary lines there, I'll fix it
I didn't understand borer code when I put that in
