### ISSUE TITLE
Shuttle often bugs out, causing the /tg/station splash picture to be the only thing on screen

### ISSUE THREAD

**Issue by JayIRay** [tgstation/tgstation#21468]
Occasionally when the shuttle sakes off, parts of the screen or the entire screen will be obscured by the picture you see when entering the lobby of the server. It's a real hassle because you can't see anything happening on screen. 
![Here's what I'm talking about.](https://cloud.githubusercontent.com/assets/23201761/20193183/816c46ee-a752-11e6-83f1-400c215d3eda.png)

**Comment by Hatfish** [comment]
Pretty sure this is a dupe of #21099

**Comment by JayIRay** [comment]
Seems to be. Closing.
