### ISSUE TITLE
Syndrones can't use Syndicate guns

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#21475]
Any gun with a Syndicate firing pin, syndicate drones can't use. Probably an oversight.

**Comment by JJRcop** [comment]
probably syndrones were added before firing pins

**Comment by Shadowlight213** [comment]
No, basass syndrones had a weapon Auth implant.
Bug is caused by #20934
@phil235 made implants only work for carbons.

**Comment by KorPhaeron** [comment]
@AnturK 

Your recent PR should have fixed this correct?

**Comment by AnturK** [comment]
Yes, should be working fine now.
