### ISSUE TITLE
Supply consoles get stucked on loading.

### ISSUE THREAD

**Issue by rsanchezbalo** [tgstation/tgstation#21486]
Sometimes when playing cargo, Cargonia supply console goes banana and get stucked on "Loading" like this:

https://gyazo.com/b865d25ed534b0fd040dba051f0a4cc4

I'm not even sure how this happen but i would love to know how to fix it but stay like that forever. Any lead on how to fix it?

**Comment by ShizCalev** [comment]
Will close in a week without another repo.
