### ISSUE TITLE
Revheads can become borgs without losing revhead status

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#21487]
They still count as dead, but have the icon and appear to be a revhead.

**Comment by TechnoAlchemisto** [comment]
I think this applies to all factions with icons, I remember being a borg with the cult and/or nukeop overly still on me.

**Comment by xxalpha** [comment]
Emergent gameplay.

**Comment by Anonmare** [comment]
Shouldn't being a silicon override faction loyalty?

**Comment by kriskog** [comment]
No longer happens
