### ISSUE TITLE
Player wasn't getting the tgUI for a canister

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#21491]
Happened at about 2016-11-11 20:50 maybe a little earlier, the player, Pdgamer wasn't getting the tgUI for an oxygen canister but could still open the tgUI for a nearby plasma canister, and it worked when I tested it.

Weird issue, ho.

**Comment by Cyberboss** [comment]
I'd close this, purely because it sounds exactly like it was minimized

**Comment by lzimann** [comment]
Sometimes the tgui for something simply won't open(it will open a first time but after you close it won't), happened to me a few times, I don't have reprodution steps though.

**Comment by optimumtact** [comment]
zero chance we'll reproduce this successfully
