### ISSUE TITLE
Mulligan and ghost roles

### ISSUE THREAD

**Issue by silicons** [tgstation/tgstation#21499]
Apparently hotel roles at the very least can mulligan.
Why...

**Comment by GunHog** [comment]
You would mind providing a better explanation here?

**Comment by MMMiracles** [comment]
Mulligan pulls from a list of every active client inside a human mob and has mid-round antag enabled in their preference, which means it can pull from ghost roles. There should probably be a check that they're on the crew manifest, considering the list it pulls from is even called 'living_crew'.

**Comment by coiax** [comment]
Wait, so mulligan means "pick the appearance of a crewmember"? I thought it was just a random human appearance
