### ISSUE TITLE
Heads destroyed by recycler

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#21505]
I think there's already an issue for this but too lazy to look it up. Detached heads get destroyed by a recycler with safety mode on.

**Comment by PKPenguin321** [comment]
Not a bug imo

**Comment by BeeSting12** [comment]
I believe this is a bug because brains should not be easily destroyed.

**Comment by Dorsisdwarf** [comment]
Do detatched brains get destroyed or do safeties trigger is the question deciding whether bug/not bug

**Comment by PKPenguin321** [comment]
Safeties trigger, but it's still destroyed

**Comment by bgobandit** [comment]
feature
