### ISSUE TITLE
Error: Eyeobj not Found | Serverroom Pubbystation

### ISSUE THREAD

**Issue by Blonkz** [tgstation/tgstation#21503]
Be AI. Have camerer alarm in Tcoms Server Room! Click link. Recive following error:

ERROR: Eyeobj not found. Creating new eye...
View resets on AI-Core.

To recreate: do it again.

**Comment by PraiseRatvar** [comment]
@pubby ?

**Comment by timothymtorres** [comment]
Duplicate of #20238
