### ISSUE TITLE
Disposal pipes burning in fire not actually fixed

### ISSUE THREAD

**Issue by Cairo283** [tgstation/tgstation#21523]
[Note]: Disposal outlets STILL burn when placed in fire. They seem to burn when the temperature reaches around 5000 degrees, and just vanish when they do.

**Comment by Cyberboss** [comment]
They are fire_proof so this makes no sense :/

**Comment by A-t48** [comment]
"#define FIRE_PROOF 2 //100% immune to fire damage (but not necessarily to lava or heat)"

**Comment by Cyberboss** [comment]
They are lava proof as well...

**Comment by Cairo283** [comment]
After assorted "testing" (Read: lighting shit on fire), disposal pipes, while immune to the fire itself, are, like A-t48 said, _not_ immune to heat, so if an area is hot enough, they will still burn.

**Comment by msgerbs** [comment]
Is this still an issue?
