### ISSUE TITLE
disassembling survival pod storage doesn't delete it, just makes it invisible

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#21538]
1. make a survival pod
2. deconstruct (or maybe just screwdriver open) the storage thingy that has the donk pockets in it
3. notice that you cant walk where it was
4. right click where it was and see that it's still there, just spriteless

**Comment by MimicFaux** [comment]
If you crowbar it, it becomes visible again. It doesn't have a icon-state for having the maintenance panel open.

**Comment by Saegrimr** [comment]
Still a thing.
