### ISSUE TITLE
Feature request: Add antag on/off buttons

### ISSUE THREAD

**Issue by wingy** [tgstation/tgstation#21533]
There are rounds where I want to play only non-antag. To my knowledge there is no easy way to turn them all of, you have to do it one by one. It would be useful if we had "Antag: Yes No" buttons (preferably in the lobby menu).

**Comment by PKPenguin321** [comment]
Not a bug and should be closed

That aside though I agree this would be handy

**Comment by xxalpha** [comment]
He didn't say it's a bug.

**Comment by Iamgoofball** [comment]
Not a bug. Close it.
