### ISSUE TITLE
Cyborgs are taking fire damage from welders

### ISSUE THREAD

**Issue by imtakingabreakdontatme** [tgstation/tgstation#21549]
>but kor it's a welder they do fire damage!

For the past six years or so they've taken brute though. This is important because firing damage is "internal" for borgs, and something they can't actually fix without a human. Even with a human, it involves removing the cell and poking around in the borg guts.

Borg fire damage either needs to be easier to heal, or they need to not take fire damage from normal attacks again, because it's essentially clone loss for cyborgs

@phil235 I think you touched silicon life last, do you know what the cause is?

**Comment by ShadowDeath6** [comment]
As far as I can tell, harm intenting a borg with a lit welder has ALWAYS done burn, at least in the past year and a half I've cared to notice it. Somewhat related is that using a lit help intent welder to repair a borg will still fire as repairing dents if the borg has burn damage, even if it has no burn damage.

**Comment by Anonmare** [comment]
They've done burn damage ever since I've been playing, it's a pretty legit way of wearing a borg down via attrition

**Comment by Cebasiz** [comment]
welders did not do burn as of a month ago

t. borg expert

only electrical disturbances do burn to borgs, slamming into containment fields, EMP etc

fire / welders never did as long as i've been playing sillicon

**Comment by Anonmare** [comment]
EMPS do brute damage though

**Comment by ShadowDeath6** [comment]
EMPs do brute.

**Comment by dragomagol** [comment]
Unable to reproduce.
