### ISSUE TITLE
Lawyer has access to perma

### ISSUE THREAD

**Issue by JohnOxford** [tgstation/tgstation#21557]
i cant efficently execute people no more with a shitty lawyer dragging them away

lawyer has access to both interrogation doors, one of them leads into perma.

pls fix

(1. Play Lawyer)
(2. Go to Brig)
(3. Go into Interrogation)
(4. Go into the North Interrogation Door)
(5. Congrats, your now in perma)

**Comment by ExcessiveUseOfCobblestone** [comment]
@JohnOxford what map
