### ISSUE TITLE
First aid equipment takes a moment to apply to yourself but not others

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#21560]
Anything in the white box (with the exception of pens), seems reversed

**Comment by Iamgoofball** [comment]
Intentional

**Comment by Cyberboss** [comment]
But for chem patches it's reversed again...

**Comment by PKPenguin321** [comment]
patches can be weaponized, so they need a delay on others. honestly they should also have a delay on yourself but i think it's buggy since they're a child of pills or something

**Comment by KorPhaeron** [comment]
patches are supposed to have a self delay as well but it broke
