### ISSUE TITLE
Medical cyborgs cant fold or pick up with roler beds or mourge trays

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#21561]
this makes it difficult to do your job.

unable to fold the bed
unable to pick up folded or unfolded beds
unable to open or close mourge trays

**Comment by AnturK** [comment]
You mean the roller bed module is not working properly ?

**Comment by Supermichael777** [comment]
yeah and i cant open morgue trays
i think its related

**Comment by Shadowlight213** [comment]
Medborgs were never able to open or close morgues though.

**Comment by XDTM** [comment]
Tested, borgs can open/close morgue trays when adjacent, and can pick up unfolded roller beds as long as they've got the module selected, so no folding is needed.
