### ISSUE TITLE
a new shuttle can be bought when the shuttle is already in flight

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#21564]
this DELETES EVERYBODY ON IT
@KorPhaeron

**Comment by PKPenguin321** [comment]
its really funny

**Comment by A-t48** [comment]
It was me! I stole the shuttle!

![image](https://cloud.githubusercontent.com/assets/8206540/20293434/3f4aff10-aaab-11e6-8e7d-fa539ee53d3e.png)

**Comment by Crushtoe** [comment]
NanoTrasen doesn't give a damn if it's occupied, they want cash more than crew

**Comment by A-t48** [comment]
Can we add FUCK label please?

**Comment by Crushtoe** [comment]
Bug, Edge Case, FUCK, optionally Not a Bug

**Comment by AdamElTablawy** [comment]
incidentally can you buy the asteroid right as the shuttle docks
