### ISSUE TITLE
Neck slot is apparently not on stripping menu

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#21566]
Means you can't strip neck slot.

**Comment by coiax** [comment]
Security can take our gloves, but they can't take our bedsheets!

**Comment by Cyberboss** [comment]
Uhhh... no.
![untitled](https://cloud.githubusercontent.com/assets/8171642/20371759/fdd5f950-ac34-11e6-90c3-d63a7e743647.png)

**Comment by coiax** [comment]
Apparently security CAN take our bedsheets. Rise up!
