### ISSUE TITLE
Mice spawning in space

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#21574]
5:20 pm EST 11/15/16, Bagil. Map is metastation, a mouse spawned in space near the AI upload.
![home trade post xxx 2016-11-15 172140](https://cloud.githubusercontent.com/assets/22053757/20326710/e351fa8a-ab57-11e6-8563-ca7e0229f8aa.png)

**Comment by A-t48** [comment]
Space mouse!

**Comment by ChangelingRain** [comment]
@coiax

**Comment by PKPenguin321** [comment]
nice going coiax ya blew it

**Comment by Incoming5643** [comment]
just a note: Entirely possible it spawned in the adjacent window and then walked into space.

**Comment by pubby** [comment]
I saw a mouse spawn over a grille. It seems very likely that mice can spawn over walls too.

**Comment by PKPenguin321** [comment]
Mouse spawned on window by the story today, i caught it right as round started.

**Comment by PKPenguin321** [comment]
By the armory*

**Comment by coiax** [comment]
Yes, I think the spawning on the grille and then walking into space seems the most likely. SSsqueak looks for plating that has wires on it, I will put a check for grilles, I guess.

**Comment by A-t48** [comment]
Can't you just check for density of the tile?

**Comment by Incoming5643** [comment]
The density of a turf isn't affected by the density of anything IN the turf. A floor with density = 0 but a dense window+grill on it is a still a floor with density = 0  This is a tricky thing you have to check for.

**Comment by coiax** [comment]
Yeah, but you can loop through the atoms in the turf, checking for density. It's not that hard, I've got a fix in the works, just need to test it.
