### ISSUE TITLE
Singularity jumped straight past Level 3 after an emergency shutdown and restart of PA

### ISSUE THREAD

**Issue by EvilJackCarver** [tgstation/tgstation#21573]
Singularity jumped straight from Level 1 to Level 4 after an emergency shutdown of the PA and restart.

I was Engineer and was getting the Singularity up and running. I manged to get it up to Stage 2 and was about to leave it when I saw the Tesla generator come into view. I performed an emergency shutdown of the PA and attempted to recover the Tesla generator, which took several minutes. 

The Singularity dropped down to a Stage 1 during this time, and stopped moving at the 9-o'clock containment field generator. After recovery was successful, I attempted to get the Singulo back up to Stage 2 by turning on the PA back up to 2. After a few minutes passed, I debated with Chief Engineer Godwin Ivanov (RumblyStubble) about hacking the PA to allow Level 3, as Level 2 was not appearing to work, but before I got around to it, the Singulo visibly jumped straight to Stage 4 or 5, I'm not really sure which. (See image below.)

![atheist_transport_village_94_2016-11-15_16-04-03](https://cloud.githubusercontent.com/assets/1784490/20326263/9ae5cbd2-ab4d-11e6-896d-44a70448c57a.png)

I ahelped the issue, and Okand was able to confirm that it jumped to Level 3 in less than a second, but noted that it was 'right after it was created', implying the Singulo died, then recovered and went back up to Stage 3.

I was logging at the time, and the log is attached. I play under the character name 'Andreas Spitzer'.

[log 2016-11-15 (3 50 pm).htm.zip](https://github.com/tgstation/tgstation/files/593249/log.2016-11-15.3.50.pm.htm.zip)

MetaStation/Bagil, 2016-11-15
Windows 7 Ultimate, build 7601, byond 511.1363

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by coiax** [comment]
Is this the bug where a stage 1 singularity on the edge of containment will just not grow until it hits stage 4 and eats containment?

**Comment by EvilJackCarver** [comment]
Very well might be; the stage-1 singulo was literally 1 tile to the right of the 9-o'clock containment field generator.

**Comment by MrStonedOne** [comment]
Ya, its not exactly a *bug* per se, but has to do with how growing works. It counts it as a move and does a containment check because other wise the now bigger sing would expand into the containment and eat it. The intended part is that you can make a smaller containment field and it will never grow byond it.

I'll look at having it check if it can move then expand when it does these growth checks.
