### ISSUE TITLE
Pubbyshuttle ruins emergency shuttle

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#21579]
PUBBY RUINS EVERYTHING!!
this was on basil i bought pubby emergency shuttle after a while the shuttle arrivered... but... there was no shuttle it was just... space! Forcing everyone into pods who did launch afterwards

Server:basil
Shuttle purchase:pubby emergency shuttle(metastation shuttle was still in centcom docks even when i purchased pubby shuttle)
Map:metastation

**Comment by GunHog** [comment]
This should be made into a feature. The Captain can sell the shuttle ENTIRELY for money, at the risk of demotion and/or lynching!

**Comment by Shadowlight213** [comment]
>not selling the shuttle every round to cuck escape alone antags
