### ISSUE TITLE
Bananas put into custom pizzas always leave behind a 50 potency peel.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#21583]
![banangs](https://cloud.githubusercontent.com/assets/4581352/20356532/b1ef86ea-ac1c-11e6-94e0-b71714f357ef.png)
On the left, 25~ potency banana and peel, leaves behind a 50 potency peel when put into the pizza.
And on the right, 100 potency banana and peel, same result as before.

**Comment by bgobandit** [comment]
>grow a bunch of shitty bananas as clown
>make pizzas with them
>clowning intensifies
