### ISSUE TITLE
Round end breaks if the nuke detonates not on station

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#21594]
No score screen is shown, and the animation for the syndies failing to detonate on station doesn't play.
It just says station destroyed by nuclear device, rebooting in 45 seconds.

**Comment by Cyberboss** [comment]
@lzimann I broke this in a different way

**Comment by lzimann** [comment]
But the issue is still valid isn't it? Or did you fix it(and brke something else) ?
