### ISSUE TITLE
Changeling "Escape with the Identity as X" doesn't complete

### ISSUE THREAD

**Issue by A-t48** [tgstation/tgstation#21595]
[Note]: # Absorbed DNA of my target, transformed to them. Is the fake ID that comes with a transform not enough? Do you need the original, physical ID? If so, that's really confusing, especially as transforming seems to nuke IDs in your ID slot.

[Admins]: # 11/16/2016 around 10:50 if there's relevant logs.

![image](https://cloud.githubusercontent.com/assets/8206540/20379084/0c220c14-ac4f-11e6-887f-9c29dff6c6c2.png)

**Comment by A-t48** [comment]
Ok, so it appears that this is because of my flesh ID. That's really....confusing. If this is intended, it's super unclear, as if you transform with no ID in your slot, you get a fake one that looks just like the real thing.

**Comment by Incoming5643** [comment]
For the record if you forge an id it also works, as long as you perfectly spell the name and job.

**Comment by A-t48** [comment]
The code doesn't even seem to care about the job. Can we just drop the ID requirement? You can pass with an ID with no access at all right now. What's the logic here? Does NT put everyone with no ID coming on base through the ringer to test if they are a changeling?

**Comment by TechnoAlchemisto** [comment]
Getting the ID is the reason the objective is risky.

**Comment by A-t48** [comment]
He already has to be dead or incapacitated once you get on the shuttle, or else you look super suspicious.

**Comment by Kraseo** [comment]
I mean most of the time the same person you have to change identities with is your assassinate target but yeah.

**Comment by Shapsy** [comment]
You could just switch forms at the very last second before the shuttle docks if you don't need the ID, this forces you to take some action in securing their identity beyond DNA stinging them
