### ISSUE TITLE
Slime man blood affects slime men.

### ISSUE THREAD

**Issue by chaoko99** [tgstation/tgstation#21600]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

I recently found that a slimeman can draw his own blood and then inject it back in, and thus recieve the slime blood buff (heals brute, deals toxin), and found it actually heals the player in said case (As is to be expected.), making them effectively invincible.. I also found that it causes slime production to skyrocket, and it actually allowed about thirty clones in a span of five minutes... Is this a bug?

**Comment by Incoming5643** [comment]
I guess exotic blood isn't being taken in correctly

**Comment by XDTM** [comment]
The rapid cloning is not a bug per se, toxin damage increases blood volume.

**Comment by XDTM** [comment]
Tested and it's working properly with both slimepeople and jellypeople, with both slime jelly taken from veins and taken from slime cores. Do you remember any other circumstances while you tried this?

**Comment by Incoming5643** [comment]
Maybe he was using iv bags?

**Comment by chaoko99** [comment]
Nope, just syringes straight from the player, right back into the  same player.

**Comment by XDTM** [comment]
Needs reproducing, i couldn't do it.
