### ISSUE TITLE
PubbyStation: Filing cabinet at Cargo sec post blocks the records console from being used.

### ISSUE THREAD

**Issue by EvilJackCarver** [tgstation/tgstation#21609]
The filing cabinet at the Cargo security post blocks the security records console from being used. This may also be this case in other departments as well.

![paranoia_city_lxvi_2016-11-17_16-45-03](https://cloud.githubusercontent.com/assets/1784490/20411636/ff5612c0-ace7-11e6-96b7-d76678c23869.png)

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by JJRcop** [comment]
@pubby
