### ISSUE TITLE
EMPs remove summon Nar'Sie barriers

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#21626]
Might not be an bug, but it is stupid that EMPs mess with ancient blood magic.

**Comment by TechnoAlchemisto** [comment]
Nanomachines

**Comment by AdamElTablawy** [comment]
The reason for this @TechnoAlchemisto and @optimumtact is because the barriers are literally the breach shielder barriers from the emergency breach shielders in engineering

And they pop when hit with an eMP

**Comment by optimumtact** [comment]
why are you tagging me, I don't care

**Comment by PKPenguin321** [comment]
Easy fix, just make emp act return

**Comment by PKPenguin321** [comment]
wow nevermind some asshole made them not their own path so they're snowflaked out
