### ISSUE TITLE
Syndicate Lavabase Ruin

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#21648]
The Agent ID associated with syndicate on the lavabase ruin requires the individual to be a traitor, which I'm assuming puts the tcomm memery in a bind.

@KorPhaeron

**Comment by Armhulen** [comment]
I'll also put this here

> Didn't know where to go to comment on this, but a few important things are missing. Notably fans to keep air from getting sucked out, monkeys can open the virology door themselves, no virus food dispenser.

**Comment by FantasticFwoosh** [comment]
If steelpoint was here' he'd really mention how all of the weapons are unsecure and how much of a loot drop it is.

Without a camera feed, the comms specialist is there just to make funny voices on non syndicate based rounds (to which syndicates with traitor earpieces would be able to hear all comms anyway) without context.

**Comment by Armhulen** [comment]
guns should atleast have syndicate pins and as a side note, please add a miror

**Comment by FantasticFwoosh** [comment]
None of the doors have any security access whatsoever.

Literally strip off and run through the base.

**Comment by jughu** [comment]
Guns having syndiepins is just a excuse for being unrobust since they can remove the pins anyways on station or anywhere really if they have a toolbox on them

**Comment by Armhulen** [comment]
yes but when you have an armory protected by unenforced walls and anybody can use the door it's just laughable, this atleast stops that

**Comment by ExcessiveUseOfCobblestone** [comment]
it's not hard to remove the pins either, just no one cares to do it.
