### ISSUE TITLE
You can't resist out of straightjackets at all

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#21644]
It will throw a message saying you're out once the five minutes is up, but it doesn't remove the jacket.

**Comment by PKPenguin321** [comment]
As an aside, every object in the game has a breakouttime var

**Comment by phil235** [comment]
https://github.com/tgstation/tgstation/blob/c7e474ccaecf25a4256c9708b51cd3fe5d2507c2/code/modules/mob/living/carbon/carbon.dm#L360

**Comment by Xhuis** [comment]
It's because you aren't Houdini, amateur.
