### ISSUE TITLE
Ratvar end of round stats show up on non clockcult round

### ISSUE THREAD

**Issue by CPTANT** [tgstation/tgstation#21654]
Ratvar's servants had 0 Tinkerer's Caches.
Construction Value(CV) was: 0
Script scripture was: LOCKED
Application scripture was: LOCKED
Revenant scripture was: LOCKED
Judgement scripture was: LOCKED

traitorling round, no cultists.

**Comment by ChangelingRain** [comment]
god damn it end-round code
