### ISSUE TITLE
Ctrl+click grabbing has no delay

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#21653]
Instant aggro grab anyone?
Also, allows for instastun with sleeping carp because of that.

**Comment by Arianya** [comment]
Could you clarify what you experienced and under what circumstances? I tested out the combos of the following on the live servers and saw nothing amiss:

Ctrlclick + click: passive grab then after normal delay aggro grab

Ctrlclick + ctrlclick: passive grab then nothing

Click + Ctrlclick: passive grab then nothing

Click + Click: Passive grab and then after normal delay aggro grab

**Comment by Cyberboss** [comment]
WIT close this
