### ISSUE TITLE
Metastation : Broken wooden floors not fixable

### ISSUE THREAD

**Issue by ktccd** [tgstation/tgstation#21667]
As the engineer cyborg, crowbar-ing the broken wooden floortiles on the Meta map in the abandoned bar does not let you place metal tiles properly. Instead of a metal floor, the broken wooden floor is created.
If crowbar-ed again, it makes a metal tile, but no matter how much I try, I keep ending up placing wooden broken tiles instead of metal tiles.

**Comment by XDTM** [comment]
It's a reskinned metal floortile; you can see the same behaviour when replacing tiles with department markings on them. If you want them to look different you need to use a tile of a different type.

**Comment by ktccd** [comment]
That... I don't know.... that still sounds like a bug, since it sounds so counter-intuitive... I mean, if it's a reskinned floor tile, why not make it a reskinned wooden tile, so replacing it with metal works? :S

**Comment by WJohn** [comment]
Already fixed, apparently.
