### ISSUE TITLE
The click catcher is not catching clicks properly

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#21662]
Clicks caught aren't actually clicking the proper tile
@MrPerson I'm guessing this is due to you change to the click catcher

**Comment by MrPerson** [comment]
Please be more vague about what the problem actually is so I can continue to not help

**Comment by ChangelingRain** [comment]
I don't know anything more than "i clicked on something that was out-of-view and it fired in the wrong goddamn direction rather than where I clicked"

**Comment by factoryman942** [comment]
Try using a KA or a crusher in lavaland
If you shoot at something out of view (e.g. Something behind a rock when you aren't using mesons) i think it shoots diagonally or something
Is that what you mean changelingrain
