### ISSUE TITLE
Engineering venders have a null component parts list

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#21668]
Since I guess they don't have refill canisters, they dont have any parts, and cant be deconstructed.

**Comment by PKPenguin321** [comment]
Same with the kitchen vendor I believe

**Comment by PKPenguin321** [comment]
And the sec vendor

**Comment by Mervill** [comment]
Ok this is easy to address, but I guess the question is /should/ the sec vendor (or other vendors with this issue) have a refill canister? Or should vendors without refill canisters simply dust their contents when deconstructed?

What is the expected behavior?

**Comment by Shadowlight213** [comment]
Probably the latter. Infinite knives (not sure if the whetstone is still in the kitchen vendor) isn't a good idea.

**Comment by PKPenguin321** [comment]
Whetstones are not in the vendor any more

**Comment by Mervill** [comment]
also we will have this problem for obscure vending machines IE the BODA soda machine has no refill canister

**Comment by ExcessiveUseOfCobblestone** [comment]
can you not set them to have a single refill canister, the rest you buy from cargo or something?

**Comment by Mervill** [comment]
It's not simply that they lack a refill, it's that there is no refill canister defined for some vending machine types.

See `code\game\machinery\vending.dm` and `code\game\objects\items\weapons\vending_items.dm`
