### ISSUE TITLE
Changelings aren't getting the DNA from people they absorb

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#21684]
DNA sting seems to work fine, but I've gotten two reports of people that were eaten via the Absorb ability (the one that requires a chokehold) not putting the DNA of the victim into their list.

**Comment by swankcookie** [comment]
attempting to reproduce...

**Comment by PKPenguin321** [comment]
Yeah I haven't attempted to reproduce this, so if you don't find anything let me know. I only posted this because I've gotten two different reports from two different people on separate days complaining about this.

**Comment by swankcookie** [comment]
yeah it worked fine for me. Not sure what the problem was.

**Comment by PKPenguin321** [comment]
Has anybody been able to reproduce this? I'm thinking it could be closed.

**Comment by jughu** [comment]
Last tike i absorbed people as ling a week ago it was working fine

**Comment by Cyberboss** [comment]
@lzimann

**Comment by lzimann** [comment]
If it keeps happening either tell me to re-open or create a new issue.
