### ISSUE TITLE
can't do slime core surgery

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#21682]
Attacking a dead slime with the drapes doesn't make a prompt appear. The surgery is still in the code.

**Comment by jughu** [comment]
Yes this is what i meant with my chef cant grind slimes for slime jelly anymore because

When you cut out the cores out of the slime it gets that flat slime sprite then you could give it to the chef so he could grind it up and it would give you a jar of slime jelly

**Comment by jughu** [comment]
This one is related to it #19033

**Comment by XDTM** [comment]
Currently the method to get jelly out of a slime as a chef is to put it in the food processor(=slime grinder), get the extracts, and put them in the all-in-one grinder, where they'll give 20 jelly each if unused.

**Comment by jughu** [comment]
I know they can get slime jelly that way but my snowflake brain wants the jar instead when you processed a empty slime
