### ISSUE TITLE
Box: The windows at the bar's entrance and the kitchen don't have shutters

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#21685]

**Comment by swankcookie** [comment]
I'd suggest making an argument for why you think they are necessary.

**Comment by Cyberboss** [comment]
More matter of why have the shutters at all if they're only blocking half the windows

**Comment by swankcookie** [comment]
What do you mean only half the windows?

**Comment by Cyberboss** [comment]
The port windows have shutters but not the stern window. The kitchen is debatable
