### ISSUE TITLE
Wormholes can be frozen

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#21698]
![](https://file.house/6qhU.png)

**Comment by ChangelingRain** [comment]
anything can be frozen yell at goof

**Comment by MrAlphonzo** [comment]
Can't wait for Goof to "fix" Freon another dozen times.

**Comment by Shadowlight213** [comment]
Just open a freon revert PR and give him an ultimatum. That seems to be the most effective way of getting him to fix things.

**Comment by Supermichael777** [comment]
just remove goof
and then freon
problem solved

**Comment by XDTM** [comment]
If fixing this is a feature then this is not a bug.

**Comment by Cyberboss** [comment]
It's not, the fruit was fruiting
