### ISSUE TITLE
Meat spikes only deal damage, do not convert to 'gutted' state

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#21705]
Currently meat spikes for actually harvesting meat are extremely inefficient short of actually stabbing the animal to death and butchering it yourself using a knife on harm intent like you can do on any floor tile away from the spike. The damage of the meatspike when you place a monkey (such as the bar roundstart pun-pun) contributes to killing it, but a lot of the actual work required for it to die comes from stabbing it until it is dead and butchering it, making the meatspike pointless other than keeping it stationary to be stabbed

> The kitchen knife is ineffective for quickly stabbing the monkey to death and you might be there for a while.

Though the picture isn't working entirely as intended, this image borrowed from the merged PR  #11556 shows a correct gutted state, this one uses a corgi but there are monkey states too.
https://camo.githubusercontent.com/23fd7f0bab9cce589c8d0b38946581b6628515ad/687474703a2f2f692e696d6775722e636f6d2f4475626a4b56702e706e67

> I am also aware of the possibility that it might have been commented out for balancing issues vs ling monkeys and the instant gutting death it used to create, but i appeal to you that it never converts to the gutting state now and is unfit for purpose, re-approaching the balance to keep the feature in would be a good move in my personal opinion especially how easy it is to destroy machines and objects.

Especially with the recent gibber nerf (1 body=1 slab), there are very few ways to professionally & efficiently collect meat.

The bug is reproducible very easily with testing monkeys both dead & alive, neither will convert to the gutted state where it simply becomes a interaction of slicing the contents off them cleanly rather than them bloodily exploding all at once in a butcher interaction on harm intent while on the spike.

**Comment by bgobandit** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
Not a bug. You butcher monkeys and simple animals with sharp objects on harm intent, the spike has nothing to do with it

**Comment by Cyberboss** [comment]
Then why do we even have it?

**Comment by FantasticFwoosh** [comment]
@KorPhaeron - Please read _the content_, there is a specific interaction with the meat spike that pre-bug instantly kills monkeys and converts them to a gutted state where they are butchered piece by piece.

> The point is that, that way of butchering monkeys is more efficient & clean and doesn't require butchering the monkey on the spike via harm-intent, as the monkey bloodlessly has its products taken away from it per click then is q-deleted.

> Compared to butchering them bloodily on the floor as per the usual harm intent or using the gibber which has been recently nerfed to only produce 1 slab of meat.

Please elaborate if in your understanding if I am wrong (I can prove i am right with the supplied picture & rollbacks to when the meathooks were implemented) or if this is your personal opinion that the only way to use a meatspike is to buckle, because the original PR coding intended it to have purpose.

> @Cyberboss : "_Then why do we even have it?_"

https://github.com/tgstation/tgstation/pull/11556/commits/94490f12d190602c00feb58ffc35195bf4671992#diff-9654ae1793b7ac38fbe7f31735f2ea43R78

^^^ Shows the guttable types of creature, including the corgi type in the original screenshot of the OP and from the OP pr.

**Comment by KorPhaeron** [comment]
That functionality was removed on purpose

**Comment by FantasticFwoosh** [comment]
I addressed that in the OP, thank you for the eventual concise reply.

> _I am also aware of the possibility that it might have been commented out for balancing issues vs ling monkeys and the instant gutting death it used to create, but i appeal to you that it never converts to the gutting state now and is unfit for purpose, re-approaching the balance to keep the feature in would be a good move in my personal opinion especially how easy it is to destroy machines and objects._

**Comment by KorPhaeron** [comment]
I am aware, but requesting balance changes is not what the issue tracker is for
