### ISSUE TITLE
Cogscarabs can open Nar'Sie cultdoors.

### ISSUE THREAD

**Issue by Kevak** [tgstation/tgstation#21706]
Ratvarian Cogscarabs can open narnar doors. I feel like it's probably an oversight.

I'm not very clear on how cultdoors work codewise, but if cogscarabs can do it, I'd feel it reasonable to assume narnar constructs can open ratvar doors and other ratvar constructs could open narnar doors.

Or maybe it's just a carryover from drone. Unsure. It's not a real concern but I feeeel like it should be dealt with eventually.

**Comment by ChangelingRain** [comment]
Can't reproduce with normal cult doors; were these the "cult doors" on the cult shuttle? Because those doors allow anyone to open them.

**Comment by Kevak** [comment]
It was doors that I'm fairly sure were adminspawned. So possible that they had different access definers.
