### ISSUE TITLE
Ash Drake Jump Gib

### ISSUE THREAD

**Issue by Repukan** [tgstation/tgstation#21727]
Jumping as a lesser ash drake it's an automatic suicide.

I jumped on another ash drake corpse and it killed me automatically. Either the jump or the fire balls are doing heavy damage to the user. Not sure if intended.
![tgstation bagil english 100 lagfree regret station 2mil 2016-11-24 140845](https://cloud.githubusercontent.com/assets/19575516/20608401/9e5276c2-b24f-11e6-8fbf-18c4f3e0df5a.png)

**Comment by PKPenguin321** [comment]
Wasn't able to reproduce by making self lesser ash drake on thunderdome and jumping around/shooting fire.

**Comment by Repukan** [comment]
I jumped on top of another drake corpse.

Hence the bones and diamonds.

**Comment by ExcessiveUseOfCobblestone** [comment]
Just tested this and it wasn't an issue. Lesser Dragoons are really susceptible to being GG'd by normal dragoons

**Comment by Thunder12345** [comment]
Seems to be caused by things on the ground being thrown when you land and hitting you
