### ISSUE TITLE
telecrystals not spawning

### ISSUE THREAD

**Issue by kilkun** [tgstation/tgstation#21734]
[Note]: # Buying Telecrystals while your hands are full doesn't spawn them, but it still gives you the "telecrystal materializes on the floor" message while also subtracting 1 TC from the uplink

**Comment by Firecage** [comment]
Tested on local server and couldn't reproduce this bug.

**Comment by kilkun** [comment]
It happened when I was holding a telecrytsal. I think it might have been trying to "stack" them for some reason.

**Comment by uraniummeltdown** [comment]
Still a bug, it seems that if your hands are full and you click Buy slowly, it spawns correctly but if you click too fast they don't get spawned

**Comment by kilkun** [comment]
thats really fucking strange

**Comment by PKPenguin321** [comment]
These things stack, right? Possibly related to https://github.com/tgstation/tgstation/issues/22701 then?

**Comment by uraniummeltdown** [comment]
They do stack, might be related to that issue

**Comment by XDTM** [comment]
@AnturK doesn't seem to happen, i couldn't reproduce it with the same conditions
