### ISSUE TITLE
Pirates in the syndiecate vs pirates space ruin are invincible 

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#21746]
Right what says on the can i attack a pirate esword guy with 30 welder hit still not died so i gone back to the station to get a egun and after 7 lasers it still didnt die plus they were in space and still didnt die at the end of the round

**Comment by FantasticFwoosh** [comment]
Entire ruin is pretty much as broken as the syndicate ship away mission, the intended sort of progression through it is to down 1 mob, kill a syndicate commando/ (get a esword or a shield from any mob) and work through from there using blocking chances and baiting mobs away to 1v1.

Obviously if the mobs are WAY too strong or bugged to be invincible = aesthetic additions, then it goes contrary to the ruin design choice without literally bringing a huge amount of weapons.
