### ISSUE TITLE
Plasmamen are not getting their own random names

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#21741]
Latest changelog promises randomized names for plasmemes. Default names are being applied. Tried with existing, and new characters.

**Comment by bgobandit** [comment]
related to https://github.com/tgstation/tgstation/issues/21725 probably

**Comment by MrAlphonzo** [comment]
PR had literally one job.

**Comment by lzimann** [comment]
Fixed already. Nothing wrong with the pr, it's just that server's config folder won't update by itself and we have to manually put new stuff there.
