### ISSUE TITLE
One of the wizard race options from the magic mirror makes them invisible. 

### ISSUE THREAD

**Issue by Saegrimr** [tgstation/tgstation#21751]
It was Synth

**Comment by francinum** [comment]
https://youtu.be/R-g-u9wYt1Q

**Comment by Shadowlight213** [comment]
Known bug for a while. Synths were already held together with tape and wishes, and the dismemberment refactor didn't help.

**Comment by ExcessiveUseOfCobblestone** [comment]
throw it under the rug by just removing the option from the mirror :^)

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm removing the option in an upcoming pr soon :tm:
