### ISSUE TITLE
Seclites on Helmets don't turn on

### ISSUE THREAD

**Issue by DfourC** [tgstation/tgstation#21759]
Attaching a seclite to a security helmet makes it unable to be activated or deactivated, meaning it is permanently in whatever state it was in before attachment. If you detach it with a screwdriver, you can turn the seclite off and on again.

**Comment by scoopscoop** [comment]
You can toggle them on and off, but you have to hold them in your hand and use the command in the right click menu. But yeah, something is broken about them.

**Comment by FantasticFwoosh** [comment]
Question, are you wearing them on your head. If so...

Did you move the button out of the bar?/Opened the button gui options at the top if concealed?

**Comment by scoopscoop** [comment]
You can reproduce it pretty easily. Start as a sec officer, and slap a seclite onto your helmet. If you click the new gui button that shows up, it doesn't do anything. Take the helmet into your hands and use it, it doesn't toggle the state. Right clicking the helmet in your hands and using the command to toggle the state works, though.

**Comment by xxalpha** [comment]
>But yeah, something is broken about them.

It's the code. All of it.

**Comment by ExcessiveUseOfCobblestone** [comment]
I have a fix for this coming soon.
