### ISSUE TITLE
Taking Syndicate hardsuit off dead syndie in wishgranter ruin leaves helmet

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#21771]
![t](https://cloud.githubusercontent.com/assets/22053757/20637349/61e6d19c-b353-11e6-918f-eeeedc2b06ee.png)

Took hardsuit off the dead syndie, he left the helmet on. I could then activate the hardsuit helmet on myself. 9:10 pm, EST 11/25/16 Bagil

**Comment by PKPenguin321** [comment]
Probably a dupe, this has been around since this was an away mission

**Comment by jughu** [comment]
Psst this already existed at the time when hardsuits had their helmet not on them but with them it be i think a simple code change 👌

**Comment by Supermichael777** [comment]
its actually because the hardsuit's helmet is inside it and to map helmets onto mobs you need to put a second one on its head.

**Comment by AnturK** [comment]
Corpsespawners just need a specific variable.

**Comment by ChangelingRain** [comment]
Fixed by #22845
