### ISSUE TITLE
Runtime Error from /datum/pipeline on private test server

### ISSUE THREAD

**Issue by Lakart** [tgstation/tgstation#21787]
No idea what causes it, first noticed it with the updates last night that also broke a bunch of other shit like tcomms and such. Spams constantly after round start. 

I have made no changes to TG code and the error has shown on Bird, Pubby, and Mini which are the only stations I've tried so far.

runtime error: 
[06:31:05]/datum/pipeline has one or more null gas mixtures, which may cause bugs. Null mixtures will not be considered in reconcile_air().
[06:31:05]proc name: stack trace (/proc/stack_trace)
[06:31:05]  source file: unsorted.dm,1285

**Comment by Cyberboss** [comment]
This sounds like a mapping bug

**Comment by optimumtact** [comment]
We have this same runtime, nobody has bothered to trace it yet

you can see all the current runtimes here : https://tgstation13.org/parsed-logs/sybil/runtimes/

**Comment by duncathan** [comment]
dupe
