### ISSUE TITLE
Holodeck carp not doing shit

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#21785]
Sic carp on revhead as valadin AI
They sit there and stare at my cameras
Everyone laughs at me
:(

**Comment by jughu** [comment]
Earlier yesterday i saw nuke ops use viscerators and they weren't hostile too they werent doung shit either

**Comment by jughu** [comment]
legions arent HOSTILE EITHER

**Comment by jughu** [comment]
basalisks doesnt either

**Comment by Armhulen** [comment]
yeah legion just kind of sit around

**Comment by Cyberboss** [comment]
Possibly related to #21688 ? @MrStonedOne ?

**Comment by Kevak** [comment]
Syndie and pirate mobs aren't doing anything either in the spaceruin.

**Comment by Armhulen** [comment]
WE BROKE IT

**Comment by AnturK** [comment]
Dupe of #21806
