### ISSUE TITLE
Gulag Labor shuttle wont go back down.

### ISSUE THREAD

**Issue by B00tz** [tgstation/tgstation#21790]
Problem Description: If a prisoner tries to send the labor shuttle back down it won't go.

What did you expect to happen: I expected the shuttle to go back down as one does. It prints out the message "Shuttle received message and will be sent shortly." 

What happened instead: Didn't go back down.

Why is this bad/What are the consequences: Power was out and I was stuck in a 3x3 room with no way out.

Steps to reproduce the problem: Attempt to send the shuttle back down using the point claim console with a prisoner id that has enough points to move it.

Server: Bagil

Revision: What revision was the server running? 

Server revision compiled on: 2016-11-27
Test merge active of PR #21778 
Based off master commit f9f7fd731fe56bd21eb811d2f2a9597d0e740cb9

**Comment by optimumtact** [comment]
This is probably related to the broken addtimers and should be fixed now
