### ISSUE TITLE
Apparently all hostile mobs on are broken

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#21806]
OOC: Repukan: legion skulls just float in place

OOC: Repukan: and watchers are just
OOC: Repukan: uh

OOC: Jerry Derpington: . . Oh and that. Alot of mobs in lavaland are actually fucking broken tbh
OOC: Jerry Derpington: sometimes they literally come back as zombies
OOC: Jerry Derpington: and do nothing

**Comment by Kromgar** [comment]
Its all mobs. Carps too.

Goliaths still work not sure how that is

**Comment by KorPhaeron** [comment]
@MrStonedOne 

You touched hostile mob targeting last, right? Not sure though

**Comment by MrStonedOne** [comment]
Hmm, it was 4 days ago, should have been noticed before now...

**Comment by MrStonedOne** [comment]
Ya, all I edited was object targeting, mob targeting was untouched. I'm compiling some tests now (old code, new code, new code with my pr reverted) to see

**Comment by Kromgar** [comment]
Ocular wardens are not attacking non-cultists either accord to OOC

**Comment by KorPhaeron** [comment]
So this only applies to "flying" mobs, and said flying mobs will start attacking and moving normally once put into space (maybe zero grav?)

@kevinz000 probably did something with mob movement in the flight suit thing

**Comment by Durkel** [comment]
Possibly unrelated but the mobs in the space ruins of syndie vs pirates will randomly break too, The pirates in the ships will act normally but once they enter space they stop working and just float there, even though they're ranged mobs.

**Comment by kevinz000** [comment]
currently running through my refactor of flying.
Before, simple mobs had a var that determined if they were flying, and humans had a FLYING bitflag in their species specflags
Now I made both into a bitflag named movement_type, that is normally ground except in the cases of a flying mob. However, to do that I made flying mobs have movement_type = FLYING instead of GROUND | FLYING. don't know if that's the problem but I'm doing stuff to test.

**Comment by swankcookie** [comment]
well, mining just got a lot easier.

**Comment by KingPhilipIII** [comment]
Watchers will still shoot but do not move. Their corpses float too for the record.

**Comment by Kromgar** [comment]
Watchers will not shoot unless you attack at ranged

**Comment by SgtxRootbeer** [comment]
Also, kromgar
I was in a Ripley, fighting cult last night, and ocular wardens did damage my ripley.

**Comment by MrStonedOne** [comment]
I think this issue was fixed....

**Comment by KorPhaeron** [comment]
https://github.com/tgstation/tgstation/pull/21813

This isn't merged yet, so unlikely

**Comment by Cyberboss** [comment]
It's merged now, is this fixed?
