### ISSUE TITLE
Space tiles indoors are entirely black

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#21808]
@MrPerson 

If you blow a hole in the floor of a hallway, space will be entirely black, and can't be lit

Tested as cyborg and observer, not sure about human

**Comment by RandomMarine** [comment]
I see them as drone, too.

**Comment by Thunder12345** [comment]
Let's add on this just happened on the emergency shuttle kit on basil. Only happened partway through the round, I think around the time it got bombed. Changing shuttle has no effect, turfs seem to be missing lighting objects. Oh and almost all of space has no lighting objects either.

**Comment by Supermichael777** [comment]
are light objects getting blown up again?

**Comment by coiax** [comment]
I will investigate when this was introduced.

**Comment by KorPhaeron** [comment]
This is probably resolved since we reverted the night vision thing

**Comment by RandomMarine** [comment]
Is that live on the servers yet? Because I'm still getting it.
