### ISSUE TITLE
Space tiles in areas previously station are black

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#21827]
![scrnshot1](https://cloud.githubusercontent.com/assets/22053757/20686987/c16ce85e-b588-11e6-829a-485273784a24.png)
As issue states, breaches that expose an area to space have the space tiles totally black. Has been happening since yesterday, the current issue happened at 4:39 pm 11/28/16, EST, on bagil. Turning darkness off remedies it, maybe the space tiles are going dark when they're not meant to?

**Comment by Jordie0608** [comment]
Dupe of #8282
