### ISSUE TITLE
RCD has confusing text, as well

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#21831]
That's some metal.
Sheets made out of metal.
They are a normal-sized item.
There are 3 metal sheets in the stack.
You insert 0 metal sheets into the RCD. 
The RCD now holds 136/160 matter-units.

hmm

**Comment by FantasticFwoosh** [comment]
Sort of bordering on suggestion but a valid point

> Try here (Coding Feedback) https://tgstation13.org/phpBB/viewforum.php?f=10
