### ISSUE TITLE
Un/sheathing Officers Sabre causes mass item drop

### ISSUE THREAD

**Issue by Lakart** [tgstation/tgstation#21842]
When you sheathe or unsheathe the officers sabre as a golem(titanium specifically), it causes your ID, Belt, and pockets to all immediately drop.

**Comment by TechnoAlchemisto** [comment]
Is this using the quickdraw method or just removing it from the sheath storage?

**Comment by Lakart** [comment]
Removing or putting it back in normally

**Comment by FantasticFwoosh** [comment]
_Captains pants dropping down when they unsheathe is intentional._

From a literal point though this is pretty dumb bug that debases the value of a very robust weapon the captain has a right to own.

**Comment by Armhulen** [comment]
i think this only happens with golems, it happened when I was adamantine

**Comment by Thunder12345** [comment]
Have pinned this issue down to being caused by calling regenerate_icons() on the mob.
