### ISSUE TITLE
Freon is still available despite being a lag potential.

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#21840]
See title, available via traitor grenades and cargo.

**Comment by Lakart** [comment]
I think a few weeks ago the server was crashed by throwing a freon cluster grenade and then a plasma cluster grenade.

**Comment by Chnkr** [comment]
Fix your shit @Iamgoofball

**Comment by PKPenguin321** [comment]
And the holodeck winter wonderland emag module

**Comment by XDTM** [comment]
Also via dark blue slimes

**Comment by Aloraydrel** [comment]
shouldn't you fix it :^)?

**Comment by Iamgoofball** [comment]
@optimumtact

**Comment by ExcessiveUseOfCobblestone** [comment]
I thought it was a feature that freon was so cold it froze time, creating the well known space time distortions [formerly known as STDs].

**Comment by YakumoChen** [comment]
Even goof agrees Freeon is cancer

please remove it

**Comment by Iamgoofball** [comment]
Where did I say it's cancer?

**Comment by optimumtact** [comment]
they tagged it priority high lmao, absolute madpeople

**Comment by ExcessiveUseOfCobblestone** [comment]
@optimumtact @KorPhaeron is this still an issue?

**Comment by KorPhaeron** [comment]
It isn't available anymore so far as I know

**Comment by Iamgoofball** [comment]
We fixed the freon lag I believe
