### ISSUE TITLE
Microwaves explode (unintentionally i think) with the functions of commit #21774

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#21857]
Instead of heating the reagents (which to my knowledge were not bomb components, just alcohol & a bit of miscalculated cola to make a hearty punch) to a 1000k as the commit #21774 describes it caused the actual microwave to explode and spit out a error when i tried to interface with it.

I used my 100 unit drink mixer - To which that was probably Q deleted or remains within the (bugged) microwave with from memory all the required reagents for a balanced (brave bull, syndicate bomb beer with 20 units of cola left over and 20 units of Absinthe. It did not mix in the microwave and took a amount of time to process with giving a deafening bang, and i was thankfully not flashed seriously by my sunglasses, but it blew the wall off & damaged the doors.

![](http://puu.sh/szsEr/590fd96564.png)

> Oh my god have i created a accidental alcoholic pipebomb?

**Comment by Ratvar** [comment]
=> heating Syndicate bomb in makeshift heater
Feature.

**Comment by FantasticFwoosh** [comment]
Its a drink mixture (whiskey cola & beer)

So you're saying that the drink explodes? Why isn't that detailed anywhere on the wiki etc.

**Comment by PKPenguin321** [comment]
Microwaves can malfunction by themselves at random when cooking stuff, requiring repairs. This has been true since forever

**Comment by FantasticFwoosh** [comment]
_Good Lord, what is happening in there?_

_A microwave malfunction?_

_A microwave malfunction? At this time of year? At this time of day? In this server? Localized entirely within your kitchen?_

_Yes._

_May I see it?_

_No._ 

I concur, its still a pretty bullshit result and didn't even heat up the mixed contents (which mixes into a drink when exposed to heat which it surpassed) leading me to believe that if it was a manfunction, it was induced because the microwave had bad memory and didn't know what to do.

**Comment by PKPenguin321** [comment]
Microwaves just randomly malfunction when cooking, not a bug meme man

**Comment by FantasticFwoosh** [comment]
But i wasn't cooking food, i was specifically heating up a reagent container with booze in it (i mentioned this in my OP)

I've never seen that happen in my entire SS13 career.

**Comment by PKPenguin321** [comment]
The explosion is very deliberately coded in and the "bad memory" message is as well as a cheeky metajoke about the github

**Comment by Mervill** [comment]
git gud m8

But perhaps we ought to make it a bit clearer that this is, in fact, a flavor-text error and not a runtime causing the html to become corrupt.

**Comment by optimumtact** [comment]
not a bug, take it to the feedback forum

**Comment by FantasticFwoosh** [comment]
Buuuut Oranges, my method works EVERY time for a malfunction
