### ISSUE TITLE
Kudzu is broken.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#21879]
![kudzubekiddingme](https://cloud.githubusercontent.com/assets/4581352/20807642/a9401762-b7f7-11e6-851b-e2e962370737.png)

You can get over 100 potency or under 1 production speed with holy water and amatoxin, this only applies to kudzu (THANK GOD.)
Kudzu in general doesn't seem to mutate at all, although I'm not sure if I tested it with a completely normal seed..
Negative production speed can lead to instantly harvestable at age 2.

**Comment by Armhulen** [comment]
not a bug
