### ISSUE TITLE
One atmos window is not fulltile.

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#21887]
![](https://file.house/bbUo.png)
It uses some weird varedit trick.

**Comment by RandomMarine** [comment]
Map looks like metastation. Should probably include that info in your report.

**Comment by ChangelingRain** [comment]
There are two similar windows in metastation's escape wing, too.

**Comment by RandomMarine** [comment]
It also has obj_integrity of 10000. Is it because it's adjacent to the waste release tile?

**Comment by ChangelingRain** [comment]
aaaaa who even mapped that in, that's terrible
for reference never do that for actual maps

**Comment by RandomMarine** [comment]
![2016-12-01 17_57_10-tgstation _maps_map_files_metastation_metastation dmm - dream maker](https://cloud.githubusercontent.com/assets/6583225/20820371/ac43909a-b7ef-11e6-9536-f72949068d94.png)

Don't need special varedited windows when this could be done instead.

**Comment by Cyberboss** [comment]
Fucking that was me, but it looks like a regular ass window :/

**Comment by francinum** [comment]
It breaks when you do things that rely on typepath over appearance, like prosetylizers.

**Comment by ChangelingRain** [comment]
It's not even typepath, it doesn't have the fulltile var set right.
