### ISSUE TITLE
Lavaland Mobs have no dead sprite

### ISSUE THREAD

**Issue by Arianya** [tgstation/tgstation#21895]
**Issue:** Lavaland mobs that are dead have no dead sprite, and just have their normal sprite.

![Butchering a "live" goliath](https://puu.sh/sBTHw/de5e43991e.png) 

**Expected behaviour:** Upon dying, they should change to their dead sprite

**Possible reproduction help:** Mobs killed by myself did swap, but I only had a limited number of mobs to test with. All mobs that experienced this issue died off screen (i.e. by another miner)

**Comment by RemieRichards** [comment]
This isn't strictly true, they go dead for a few seconds and then switch back to their living icon erroneously.

**Comment by Arianya** [comment]
I didn't experience that myself but is entirely possible.

**Comment by PKPenguin321** [comment]
Same thing used to happen with carp (and maybe still happens)

**Comment by Armhulen** [comment]
can confirm it does happen

**Comment by KorPhaeron** [comment]
stop breaking lavaland please

**Comment by Armhulen** [comment]
lavaland keeps breaking players

**Comment by Kromgar** [comment]
So i see their death sprites and then they rise from the dead. This happened before... would be if y ou damaged them their sprites would look alive
