### ISSUE TITLE
Going blue/green alert after calling shuttle on red prevents recall

### ISSUE THREAD

**Issue by CPTANT** [tgstation/tgstation#21897]
Yes this is a bug and its super annoying.

**Comment by Chnkr** [comment]
Feature

**Comment by Incoming5643** [comment]
I've known about this but put off fixing it because no one was really abusing it. Seems like we've arrived.

Humorously the reverse is also true. If you call the shuttle in blue/green alert you can recall it 5 to 7.5 minutes later by going to red first.
