### ISSUE TITLE
Gaia'ing multiple Hydro trays with 1 Ambrosia Gaia leaf.

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#21892]
Yesterday I noticed a minor(well, technically minor) bug involving using Ambrosia Gaia on Hydroponics Trays.

First, take a single Ambrosia Gaia leaf, then go stand next to multiple Hydro Trays. Now click on each of them with the leaf. If you did it with 3 trays, you will get 3 pop up boxes. Put yes in all three, and all 3 trays will be Ambrosia Gaia'd.

**Comment by ExcessiveUseOfCobblestone** [comment]
Fixed in #21894
