### ISSUE TITLE
Nuke Ops Drop Pod can't change location

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#21904]
The first designation will lock the location. If the operatives are so inclined as to spend an additional 30 TCs on it, the second one won't work.

**Comment by WJohn** [comment]
I'm not sure if this is a bug or an oversight. Maybe kor never thought that players would for some reason spend 30 TC to change the location that's already unknown to everyone.

**Comment by PKPenguin321** [comment]
TCs store still needs stock system reee

**Comment by ExcessiveUseOfCobblestone** [comment]
I read that as goofstocks and was quite intrigued.

**Comment by ShizCalev** [comment]
Is this still an issue?

**Comment by ShizCalev** [comment]
No repos, closing.
