### ISSUE TITLE
Bio bag visual bug

### ISSUE THREAD

**Issue by Haevacht** [tgstation/tgstation#21929]
Bio bag contains multiple of a type of slime core, open bag, inject core, reaction occurs, bio bag now says there's none of those cores in there. Hit smartfridge with bio bag, the missing cores reappear.

Probably similar occurences with similar bags, but not sure where it'd happen.
Low priority.

**Comment by Arianya** [comment]
Looking into this at the moment. I suspect this has to do with qdel being used on stacks in a bag. Need to do further testing and investigation tonight, just leaving a note in case anyone else is looking into it.

**Comment by Arianya** [comment]
Confirmed, any stacked item that its deleted (whether via code or admin verb) will disappear from that bag, reappearing, with the stack one part lower, when the bag UI is redrawn (whether by putting something in bags or merely closing it and reopening it).

This affects anything using stacks like they are in bags (including RPEDs)

**Comment by XDTM** [comment]
This issue was fixed and can be closed.
