### ISSUE TITLE
It's possible to strip helmets off people wearing hardsuits.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#21928]
This creates an actual hardsuit helmet item on the floor. If you pick it up, it disappears, you can produce a new one simultaneously afterwards. Not sure if you could make as many as you want.

This occured when stripping a hardsuit helmet off a simple animal syndicate stormtrooper's corpse (they have elite syndicate hardsuits), which don't gib on death.

**Comment by ShadowDeath6** [comment]
Syndicate simplemobs have the items generated onto them, I don't think this would work on regular people's hardsuits
