### ISSUE TITLE
gatfruit is not capitalized

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#21934]
It has Reishi planted.

vs

It has gatfruit planted.

**Comment by MisterTikva** [comment]
Ghost Chili is also bad.
It has chilighost planted.

**Comment by WJohn** [comment]
award for world's most inconsequential issue report

**Comment by Armhulen** [comment]
I have not reported anything that really matters at all now that I think about it

**Comment by Firecage** [comment]
Honestly, I think, for example, reishi would be better than Reishi. For example

Correct: "I am eating an orange."
Wrong: "I am eating an Orange."

Though yah, Ghost Chilli is the real issue.

**Comment by Armhulen** [comment]
in the game's defense, you chew lollipops

**Comment by bgobandit** [comment]
Already fixed, needs to be closed
