### ISSUE TITLE
There is NO WAY to get out of the experimentation machine, and you can attack from inside it

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#21930]
i'm locked in the least fun machine on the fucking ufo

it's invincible too, so you can't just break it from the inside either. You can open up the interface but none of the buttons do anything. Resist doesn't work either

**Comment by GunHog** [comment]
We are going to need a little more detail here, such as reproduction steps.

**Comment by Armhulen** [comment]
find alien experimentation machine (lavaland ruin has one)
drag yourself to it
find yourself stuck, no way to get out
cry to admins

**Comment by GunHog** [comment]
OOOOH, your first post was not well written, I assumed you meant the Experimentor!

**Comment by TehPear** [comment]
The ayy's most powerful weapon.

**Comment by Armhulen** [comment]
sorry laddie

**Comment by WJohn** [comment]
Should at least be able to resist out of it like any locker or restraining device.

**Comment by MimicFaux** [comment]
Make sure that any fixes don't affect that functioning UFO experimentation machine.
Otherwise a scientist might find a naked assistant yakkity saxing around the ufo...
actually nevermind, that's hilarious

**Comment by AnturK** [comment]
Was intended to simplify life for abductors, probably needs one now it's in ruins.

**Comment by Armhulen** [comment]
If the subject is awake during surgery then the scientist deserves a greyshirt suprise
