### ISSUE TITLE
Being a restricted race when only restricted jobs are open prevent players from latejoining

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#21952]
1. Have the HoP set every job slot to a race-restricted job (sec officer)
2. New player joins into the lobby and currently has a non-human character (plasmaman)
3. New player hit joins and sees the only available job as Assistant, but clicking on it yields a message saying that job is unavailable

The new player can then switch to a human character and the join panel will properly show sec officer, but this is extremely unintuitive.

The player sent me this screenshot: ![reeee](http://i.imgur.com/WnH4NVb.png)

**Comment by optimumtact** [comment]
What race is restricted from assistant?

**Comment by Crushtoe** [comment]
I believe the issue is other jobs are available.

**Comment by PKPenguin321** [comment]
>What race is restricted from assistant?

It's not that assistant is restricted, but Security Officer is, which is the only job available. With no jobs available, the game defaults to showing Assistant as open when it isn't.

**Comment by dannno** [comment]
ez solution just switch to a human until next round

**Comment by kriskog** [comment]
Forced backup human added in #32131
