### ISSUE TITLE
Swarmer Beacon still kinda exists after destruction?

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#21954]
![image](https://cloud.githubusercontent.com/assets/6778786/20873811/99f03434-ba79-11e6-83cc-041004250b47.png)
Topright. I can punch it still and it exlamation points. Also that thing was so fucking beefy what the fuck we stabbed it for a full minute me and another miner.

Oh and its in a wall i threw a fucking bleuspace and it teleported.

Also 0 loot for fighting hordes of swarmers is kinda shit. Especially with mass ranged attacked

**Comment by ShadowDeath6** [comment]
I think it has 1000 health, so stabbing it a lot won't work too well

**Comment by GunHog** [comment]
It has **3,000** health, greater than all other bosses! https://github.com/tgstation/tgstation/blob/c304c5f9d7968efdebf1b44ffbb3193b9d99213a/code/modules/mob/living/simple_animal/hostile/megafauna/swarmer.dm#L51 Hilarious comment, too.

**Comment by Kromgar** [comment]
Why the fuck does it have 3k. I understand making it have 1k. But we had killed the fucking swarm and it took forever to kill that thing

**Comment by ShadowDeath6** [comment]
>low-ish hp

**Comment by RemieRichards** [comment]
the comment was before I added another thousand on, so it would have had 2000 which would have fallen into "low-ish" compared to other megas.

**Comment by Kromgar** [comment]
Why is it so high? 1000 is enough so people cant zerg rush it which is impossible with all the yellow and red swarmers
