### ISSUE TITLE
Numpad 0 not changing intents?

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#21963]
I know my keyboard is working 000000000 but it's not changing my god damn intent only hotkey mode works

**Comment by Cyberboss** [comment]
Try Ctrl+num0? I don't think any of the hotkey shit works outside of hokey mode without holding Ctrl

**Comment by RemieRichards** [comment]
What @Cyberboss said is true.

**Comment by Kromgar** [comment]
It used to work without having to press ctrl

**Comment by PKPenguin321** [comment]
Numpad prioritizes hot key mode for area selection now

**Comment by Kromgar** [comment]
OH GOD DAMN IIIIIIIT. It's because i switched to basil and i didn't realize the toggle intent selecito nstlye was a thing. Now when i press 0 it rotates HURRRRR
