### ISSUE TITLE
Restraints can teleport and become invisible

### ISSUE THREAD

**Issue by MrAlphonzo** [tgstation/tgstation#21970]
Removed handcuffs off someone, they finished resisting a few seconds afterwards. Handcuffs were in my hand, then they teleported onto the floor below the guy who was restrained, as soon as they finished resisting. Picked them up, their sprite poofed. Dropped them, sprite poofed back.

**Comment by PKPenguin321** [comment]
do_after memes

**Comment by XDTM** [comment]
@AnturK couldn't reproduce, the cuffs stayed on the guy who removed them
