### ISSUE TITLE
Random mouse placement resulted in them releasing the tesla on pubby

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#21979]
![MICE](http://puu.sh/sFSlG/c13bdbaf14.jpg)
@coiax 
@pubby

**Comment by TechnoAlchemisto** [comment]
they're learning

**Comment by Armhulen** [comment]
Feature

**Comment by Cyberboss** [comment]
Seriously, just kill them, they are your mortal enemy as engineers.
