### ISSUE TITLE
What do the tgui polyfills actually polyfill? 

### ISSUE THREAD

**Issue by Mervill** [tgstation/tgstation#21981]
So tgui has a bunch of polyfill code (code that smooths out browser differences). But why? Besides the power monitoring console graph and a few other little things, I don't see anything in tgui that's so advanced as to require a polyfill. @optimumtact please teach me all the things I don't know

**Comment by Mervill** [comment]
@MrStonedOne

**Comment by optimumtact** [comment]
we have people on xp using ie 8 and 9

**Comment by optimumtact** [comment]
but as far as I know it's only a few things that actually use the polyfills

**Comment by MrStonedOne** [comment]
https://github.com/ractivejs/ractive/issues/2597#issuecomment-246400839

**Comment by MrStonedOne** [comment]
@neersighted
