### ISSUE TITLE
cyborg intent selector (help/harm) disappears and does not return

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/tgstation#21988]
so you're stuck in harm often enough. v. bad for non-rogue sillycon

it's happened to more than just me and multiple times now. no idea what causes it.

**Comment by Cebasiz** [comment]
oh also i swear there used to be a fuel remaining gauge on the cyborg's industrial welder

where'd it go

**Comment by Cebasiz** [comment]
also after they modified the borg transformation process it always reports they've taken the default module even if they haven't

**Comment by AnturK** [comment]
Hmm, might have been my fault with the ui_style changes. I'll take a look into it.

**Comment by Mervill** [comment]
@AnturK it was either that or my recent refactoring of the a_intent variable

**Comment by Mervill** [comment]
Related
https://github.com/tgstation/tgstation/issues/21973
https://github.com/tgstation/tgstation/issues/21963

**Comment by AnturK** [comment]
https://github.com/tgstation/tgstation/blob/f292bc2b3151ee136fc14c5563a0ce47f391419a/code/modules/mob/mob_helpers.dm#L314

Should only switch between harm/help with INTENT_NEXT

**Comment by TehZombehz** [comment]
This is pretty troublesome. Clicking the button makes the intent button disappear, and I don't leave help intent. In addition, hotkeys like 'f' and 'g' do not cycle intent. I also can't seem to ctrl+click drag people, I assume because intent effects people depending on the intent you're in. I can still ctrl+click drag items and simple mobs, though.

**Comment by AnturK** [comment]
#22019

**Comment by Mervill** [comment]
For the record here is where I broke everything:
https://github.com/tgstation/tgstation/pull/21910/files/d4a49d509dabdfb78a513232c8daf4a61b937fad#diff-daecf71cbda1fe634e079ccc6201915eL329
