### ISSUE TITLE
borg module change notice is wrong

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#21997]
i just love reporting weird grammar shit

NOTICE - Cyborg module change detected: Default Cyborg-187 has loaded the Default module.

Robotic Talk, Allied Mastercomputer (AI) states, "You loaded the default."
Robotic Talk, Engineering Cyborg-187 (Engineering Cyborg) states, "nah"

**Comment by Cebasiz** [comment]
there's a lot of stupid broken stuff in sillicons of late
