### ISSUE TITLE
[Critical] [Fuck] [Etc] You can buy a new shuttle multiple times

### ISSUE THREAD

**Issue by Thunder12345** [tgstation/tgstation#22003]
See title.

So far I've seen people get deleted along with the build your own shuttle, and this abomination of multiple shuttled fused together:

![](http://puu.sh/sHfAW/42d983ff1d.png)

**Comment by Shadowlight213** [comment]
https://github.com/tgstation/tgstation/blob/c9dcd9547307b1d9b954634d599c5d54ade8caf9/code/game/machinery/computer/communications.dm#L163

This should have been an else if.
