### ISSUE TITLE
Screwdrivering survival pod food storage makes it invisible.

### ISSUE THREAD

**Issue by Saegrimr** [tgstation/tgstation#22000]
Basically that.

Can still alt-click the tile and finish deconstruction from the item list but closing the maintenance panel doesn't restore visibility, it's still impassable.

**Comment by Saegrimr** [comment]
Whoops i'm an idiot, already an issue for this 

https://github.com/tgstation/tgstation/issues/21538

**Comment by Thunder12345** [comment]
Wasted get @Saegrimr

**Comment by PKPenguin321** [comment]
holy fuck what a waste

**Comment by Saegrimr** [comment]
:honk:
