### ISSUE TITLE
Captain's hardsuit fire immunity not working

### ISSUE THREAD

**Issue by Electronics** [tgstation/tgstation#22021]
Captain's hardsuit as far as I can see is supposed to have FIRE_IMMUNITY_SUIT_MAX_TEMP_PROTECT, but immediately take dammage on entering any fire.

Think this is due to missing` heat_protection = CHEST|GROIN|LEGS|FEET|ARMS|HANDS`

**Comment by KorPhaeron** [comment]
You're correct

**Comment by Electronics** [comment]
Still seems to still provide no protection :/

**Comment by jughu** [comment]
This should fix it #22545

**Comment by Core0verload** [comment]
It was merged. Close.
