### ISSUE TITLE
you used to be able to cook goliath meat in the lava, but now it just ashes

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#22023]
see title, it was a really cool mechanic

**Comment by KorPhaeron** [comment]
@phil235 

I don't know if it's possible to override with your new system

**Comment by Cyberboss** [comment]
Just make it lava/fire proof and readd the old functionality

**Comment by Armhulen** [comment]
what cyberboss said, it should be too hard, right? maybe?
