### ISSUE TITLE
Not much of a issue but knowledge

### ISSUE THREAD

**Issue by DerekPlays** [tgstation/tgstation#22027]
Does anyone know where medi-bots text to speech came from.

**Comment by PKPenguin321** [comment]
try asking in coderbus. i think @Incoming5643 added them?

not an issue, by the way

**Comment by Incoming5643** [comment]
Documented in #19901

**Comment by Cyberboss** [comment]
Close this

**Comment by Armhulen** [comment]
DELET THIS
