### ISSUE TITLE
Nonhumans can't ctrl+click to drag humans

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#22031]
I was an engiborg with no modules active. Ctrl+click on laying mobs did not drag them. Ctrl+click on items dragged them as normal.

I could still right click+pull mobs, and ctrl+clicking floors let go of them as normal.

Duncdar confirmed as well as a janiborg

**Comment by PKPenguin321** [comment]
Probably cobbys fault

**Comment by ChangelingRain** [comment]
https://github.com/tgstation/tgstation/pull/21920/files#diff-a707cc42ebf047e20d05704da7e04b0cR233

**Comment by KorPhaeron** [comment]
@ExcessiveUseOfCobblestone 

?

**Comment by Cyberboss** [comment]
>not living
>not carbon
>but human

Ya done fuked up

**Comment by ExcessiveUseOfCobblestone** [comment]
h-h-h-honk

**Comment by Supermichael777** [comment]
because control click is the call thats made when it gets control clicked not when it control clicks something else. same with alt click.
