### ISSUE TITLE
C4 and bomb payload explosion issue

### ISSUE THREAD

**Issue by Grazyn** [tgstation/tgstation#22035]
C4 will make a bomb payload explode, but only as long as you're not wearing the backpack they're in. To reproduce: have bomb core in backpack, spawn C4, attach it to the core. Only the C4 explodes killing you. Now do the same thing but drop the backpack to the ground. C4 explodes and the core explodes too. Same bug happens if you set off the C4 without attaching it, for example with a signaller assemply, it won't set off the core if it's in the same backpack and you're wearing it.

**Comment by AnturK** [comment]
Probably some side effect of the lowering the power of explosions in objects.

**Comment by Grazyn** [comment]
Yeah but the payload still explodes if the C4 is applied to it INSIDE the backpack but the backpack is on the ground and not on yourself. Also, if the C4 is in your pocket when it goes off, and the core is in your backpack, it still doesn't explode.

**Comment by ShizCalev** [comment]
This was fixed.
