### ISSUE TITLE
Ash drake flame breath is broken

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#22048]
Probably due to #21992 the fire no longer appears and it doesn't appear to do damage, either

**Comment by KorPhaeron** [comment]
stop breaking lavaland

**Comment by Kromgar** [comment]
Yeah it was rough being a ling and an ash drake fighting the entire station with no firebreath

**Comment by KorPhaeron** [comment]
@MrStonedOne ?

**Comment by MrStonedOne** [comment]
i knew there was something i was forgetting to test

**Comment by MrStonedOne** [comment]
I'm gonna need a server this is happening on so i can find the runtimes to figure out what happened.

**Comment by KorPhaeron** [comment]
Basil

**Comment by Kromgar** [comment]
Sybil too
