### ISSUE TITLE
AI's sechud still shows on targets that have digital camo

### ISSUE THREAD

**Issue by JustSumBody** [tgstation/tgstation#22040]
Was playing AI a few weeks ago when I saw a changeling using digital camo to hide from cams, when I switched to sechud mode I was able to see him running around and even track him to an extent from his job icon/wanted status.

**Comment by KorPhaeron** [comment]
Solution: Remove HUDs

**Comment by Cebasiz** [comment]
but HUDs are the only things that make playing mediborg even bearable

**Comment by ShadowDeath6** [comment]
solution: remove AI HUDs

**Comment by kriskog** [comment]
AI no longer has the hud.
