### ISSUE TITLE
DeltaStation: Janitor's Closet spawns with no key (pimpin' ride)

### ISSUE THREAD

**Issue by EvilJackCarver** [tgstation/tgstation#22067]
Minor issue at best, the custodial closet in Delta has no key to the self-propelled janicart, unless I'm just blind.

**Comment by ShadowDeath6** [comment]
>minor issue

**Comment by Jordie0608** [comment]
Since Delta is just being tested for now and not part of the codebase i'll close this and direct Okand to it.

**Comment by Okand37** [comment]
Already fixed! Its specifically labeled 'playtest' as it isn't the final version and is intended entirely for testing.
