### ISSUE TITLE
Crafting system lacks expandability

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#22078]
Recipes cannot customize output, how materials are consumed, if a material has to be of a specific type or in a specific state.
The pin removal crafting recipe only works because of this bit of code, which is obviously unsustainable;

    /obj/item/weapon/gun/CheckParts(list/parts_list)
	..()
	var/obj/item/weapon/gun/G = locate(/obj/item/weapon/gun) in contents
	if(G)
		G.loc = loc
		qdel(G.pin)
		G.pin = null
		visible_message("[G] can now fit a new pin, but old one was destroyed in the process.", null, null, 3)
		qdel(src)

**Comment by ChangelingRain** [comment]
As a side note, you can 'remove' a pin from a pinless gun, and, well.

**Comment by Shadowlight213** [comment]
`G.loc = loc`
Shouldn't this be forcemove?

**Comment by PKPenguin321** [comment]
https://github.com/tgstation/tgstation/issues/16107

**Comment by optimumtact** [comment]
This is a feature request, take it to the forums and stop shitting up the tracker.
