### ISSUE TITLE
Toggle darkness also removes the bomb timer overlay

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#22084]
!!

**Comment by ChangelingRain** [comment]
Set ghosts of others to their sprite to avoid this issue you'll get used to it

**Comment by Shadowlight213** [comment]
@changelingrain Why in the world would those two things be tied together? That's ridiculous.

@Coiax ree.

**Comment by Iatots** [comment]
the red light overlay from fire alarms also disappears.

**Comment by Shadowlight213** [comment]
Actually unlike the fire alarm overlay, I've had  turning darkness back on not make the timer come back sometimes. Toggling ghost vision didn't fix it either.

**Comment by Dorsisdwarf** [comment]
Also the timers can be hard to see because they're not that bright and smooshed into the bottom-right, esp. cloning
