### ISSUE TITLE
Blood contracts are temporary

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#22089]
Blood contracts and the bottle of mayhem both have the same duration, while blood contracts still keep someone marked for death even after the bloodbath effect runs off. This means that while missing the chainsaw and adminordrazine they normally have, the station still has the objective to kill them while they are marked.

**Comment by jughu** [comment]
Contract for assistination son

**Comment by ExcessiveUseOfCobblestone** [comment]
not sure who made the feature, but it could be possible the goal of the chainsaw adminordrazine is to get away from the immediate people [since you're not SUPPOSE to know you're getting marked] then hold out for the rest of the game.

Seems like almost a waste otherwise.

**Comment by kevinz000** [comment]
@lzimann not an issue because of how op adminorazine/chainsaws under bloodbath are.

**Comment by Cyberboss** [comment]
@KorPhaeron Needs to judge this

**Comment by Cyberboss** [comment]
@KorPhaeron !!!

**Comment by KorPhaeron** [comment]
!
