### ISSUE TITLE
Magical Detectives Flask

### ISSUE THREAD

**Issue by Mervill** [tgstation/tgstation#22094]
- Spawn as the Detective
- Open the Detective's Fedora inventory
- Notice that it's empty
- Try to insert either the crayon or the zippo into the Fedora 
- You cant, it's full
- **drag** the Detective's Fedora onto your sprite
- Detectives Flask suddenly appears in the Fedora's inventory
- Flask now appears if you open the Fedora by clicking it
- Remove the flask, you can now insert the crayon or the zippo into the Fedora

**Comment by Mindustry** [comment]
I had a detective round today and my flask started in my bag. Was it supposed to start in my hat?

**Comment by karlnp** [comment]
You can also drag items into the noir Fedora and they will disappear and be irretrievable.

**Comment by Incoming5643** [comment]
the pockets system was supposed to be removed last I checked, but it was like, half removed. So now there's like these weird secret items that still have hidden pockets.

**Comment by Shadowlight213** [comment]
Lmao

**Comment by jughu** [comment]
Remove detective hat pocket its already a infinite candy corn storage which is not junkfood

**Comment by Mervill** [comment]
I suspect that because of this bug, the detectives flask was added to the backpack. So you'll always have two

**Comment by PKPenguin321** [comment]
Played as the detective today and the flask was in my hat as normal. I got a second separate flask in my backpack.

**Comment by Shadowlight213** [comment]
Wait, so how does the candycorn storage or whatever work?
Does it use the pockets system?

**Comment by Mervill** [comment]
@karlnp If you put an item into the black fedora, you can get it back by dragging the fedora onto your sprite. It's basically the opposite problem of the regular fedora.

@PKPenguin321 Are you sure you just clicked on the hat? Or did you drag it onto your sprite?

**Comment by PKPenguin321** [comment]
dragged the hat to my sprite

**Comment by Mervill** [comment]
Dragging the hat to your sprite is the workaround to the current issue. At some point the flask was also added to the belt, so if you know about this issue you have two flasks

**Comment by Shadowlight213** [comment]
Well, the bandaid fix is changing the priority flag to false for the detective's hat.

**Comment by Mervill** [comment]
@Incoming5643 I actually really like the idea of a "pockets" and the detective hat storage. Do you have more info on why it was removed / when?

**Comment by PKPenguin321** [comment]
It was actually deliberately not removed for detectives hat. We used to have pockets on hardsuits and lab coats for a while that were removed.

**Comment by Mervill** [comment]
Related
https://github.com/tgstation/tgstation/issues/20676

**Comment by Core0verload** [comment]
Someone changed the way storages generate their content boxes, and now pre-spawned pockets don't work.

**Comment by AdamElTablawy** [comment]
does the hat irremovability still exist because that should probably be fixed before some fuck captain stuffs the disk in there
