### ISSUE TITLE
No way to deconstruct a delivery chute

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#22091]
> You put the screwdriver in the chute
> You put the wrench in the chute
> You put the welding tool in the chute

**Comment by XDTM** [comment]
I think you have to pry up the floor tile then screwdrive

**Comment by jughu** [comment]
Just snack untill it breaks

**Comment by Cyberboss** [comment]
@XDTM There was no floor tile

**Comment by Cruix** [comment]
Turn off the pump

**Comment by PKPenguin321** [comment]
>Turn off the pump

^
You have to disable the pump before screwdrivering

**Comment by jughu** [comment]
Uh baby thats a disposal bin!~

This is a chute

**Comment by Cyberboss** [comment]
Yeah, chutes have no pumps, they insta send

**Comment by PKPenguin321** [comment]
since when did clicking directly on chutes place items in them

**Comment by jughu** [comment]
It always was like that harm intent doesnt tho

**Comment by PKPenguin321** [comment]
>It always was like that harm intent doesnt tho

i will have to code history dive because i believe this isnt true

**Comment by jughu** [comment]
Wanna bet for 5 antag tokens?

**Comment by PKPenguin321** [comment]
not really

**Comment by phil235** [comment]
@PKPenguin321 
>since when did clicking directly on chutes place items in them

Pretty sure I added that functionality.
