### ISSUE TITLE
light bugs with seclite on an energy gun

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#22099]
Wearing an energy gun with a seclite attached screws up the light a mob produces, sometimes nullifying it. Example: flashlights in pockets and Egun with seclite on riot suit slot .

**Comment by MrPerson** [comment]
To fix this I'm going to need an exact checklist to follow to reproduce the issue

**Comment by Iatots** [comment]
Alright, IIRC I:
-went to the space hotel through the cap's handheld teleporter, wearing a riot suit, carrying an egun in my backpack, and two lit flashlights in my pockets. Possibly a lit PDA but I think I shut it off by then, as two flashlights is plenty.
-found a seclite and decided to try and attach it to the e-gun in my backpack
-held said egun with a seclite attached and equipped it on my riot suit slot using the WASD mode hotkey 

Either once building or once equpping the Egun, my light output decreased considerably. Toying around with the HUD shortcuts to turn on/off the flashlights/eguns only temporarly fixed the issue, and my brightness went back down once I moved around a bit IIRC.

**Comment by YakumoChen** [comment]
putting a lighting gun in a recharger also bugs the light

**Comment by Cyberboss** [comment]
Lighting refactor fixed this
