### ISSUE TITLE
Play global sound no longer plays the sound for the person who called the sound (but only on basil?)

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#22092]
The admin button play global sound now plays the file for everyone BUT the admin who started it.

Play local sound is not affected.

Edit: Now I'm confused. This doesn't happen on Sybil, but it does happen on Basil. Is this an admin permission meme?

**Comment by MrStonedOne** [comment]
You did check to make sure you didn't have admin midis disabled right? local sound bypasses that preference.

**Comment by Incoming5643** [comment]
IT'S MEMES
