### ISSUE TITLE
a stun baton with a high capacity powercell containing 100u stable plasma acts as a normal stun baton

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#22105]
I could not test this on the original stun baton's battery, but filling a high capacity powercell from metastation's tool storage with 100u stable plasma using a syringe and inserting it in a baton will have no effect whatsoever on its functionality.

**Comment by jughu** [comment]
Intended

**Comment by jughu** [comment]
Balance reasons

**Comment by PKPenguin321** [comment]
>stable plasma

you mean ground up plasma from plasma sheets?

**Comment by PKPenguin321** [comment]
also i tested this, the explosion happens when the baton is used to hit somebody, not when it's activated

**Comment by SgtxRootbeer** [comment]
Stable plasma from the Chem machine is supposed to do that, it's "stable".
Grind up plasma sheets with a grinder to get non-stable plasma
