### ISSUE TITLE
Mechs can push necropolis tendrils.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#22107]
Just by walking towards it, mechs can push tendrils. Time to take one to the station as decoration for everyone to enjoy!

**Comment by ExcessiveUseOfCobblestone** [comment]
crouching tiger, hidden feature

**Comment by Kromgar** [comment]
Please no fixerino.

**Comment by Mervill** [comment]
The solution to this might be that tendrils be converted from a literal `/mob` to a mob-like structure (ocular warden)
