### ISSUE TITLE
Cultist clowns are no longer clumsy but randomly drop guns while firing

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#22117]
Cultist clowns are no longer clumsy but randomly drop guns while firing

**Comment by optimumtact** [comment]
Are you sure you weren't trying to fire a two handed weapon that had kickback with one hand? That can cause the weapon to fly out of your hand.

**Comment by golfer45** [comment]
nope egun

**Comment by Qustinnus** [comment]
most likely doesn't happen anymore; trait system has changed how its handled. should be tested anyways

**Comment by optimumtact** [comment]
it's  a two year old PR quist

**Comment by Qustinnus** [comment]
;^) better safe than sorry
