### ISSUE TITLE
Pressing F to Cycle Intents Cycles the Wrong Way

### ISSUE THREAD

**Issue by ShadowDimentio** [tgstation/tgstation#22111]
F is supposed to cycle counterclockwise, and G is supposed to cycle clockwise. Currently, they both cycle clockwise. Please fix.

**Comment by AnturK** [comment]
@Mervill Not sure if that removed intentionally

**Comment by Mervill** [comment]
Not removed intentionally. I know what I need to fix

**Comment by Mervill** [comment]
Related
https://github.com/tgstation/tgstation/issues/21988
