### ISSUE TITLE
The Crew Monitoring console isn't actually tgui

### ISSUE THREAD

**Issue by JJRcop** [tgstation/tgstation#22124]
It's a foreign bootleg tgui we got from a dollar store because we didn't read the label.
It tries to mimic tgui to fool us old grandmas into buying it thinking it's the real thing but they use underpaid basically-slave workers instead of advanced machining plants so the cuts are way off.

![](https://cloud.githubusercontent.com/assets/5211576/21082864/6e02d5c8-bfb2-11e6-8c36-34d3d9ec266a.png)

Not like we'd notice, we need to get Timmy a Christmas present.

[code/game/machinery/computer/crew.dm line 93](https://github.com/tgstation/tgstation/blob/1642a32ea0d1a899f90da18014bbed9d5de30e8c/code/game/machinery/computer/crew.dm#L93)

**Comment by dannno** [comment]
It also crashes my game any time I try to open the piece of shit

**Comment by Shadowlight213** [comment]
It never was tgui.
It's its own html thing. This isn't a secret or anything.
I mean, if you want to make a map wrapper and crew monitor for tgui, be my guest. It would be quite useful.

**Comment by Mervill** [comment]
Where is that map coming from? It's almost certainly outdated

**Comment by Incoming5643** [comment]
There is a subsystem you can turn on to generate it, but it really slows down round start so it's only run sparingly.

**Comment by Shadowlight213** [comment]
It slowing down roundstart was a bug.

**Comment by kilkun** [comment]
this isnt a bug, its a godsend

tgui is a meme

**Comment by lzimann** [comment]
I thought minimap generation was crashing the server, not just slowing down.

**Comment by Shadowlight213** [comment]
@lzimann that was a byond bug that was fixed a while ago.

**Comment by XDTM** [comment]
Is this an actual bug

**Comment by Cyberboss** [comment]
No

**Comment by JJRcop** [comment]
But it's not going to get closed

**Comment by JJRcop** [comment]
But it's not going to get closed just because it's not a bug, it is a valid issue.

**Comment by kilkun** [comment]
the real issue is tgui existing and the fact that we moved away from plaintext html uis

**Comment by PKPenguin321** [comment]
Please just revert the minimap on these things

**Comment by lordpidey** [comment]
Honestly, before we move more stuff over to tgui, could we fix tgui first?  It's way slower than basic HTML, and the windows randomly stick to the right side of my screen, when they aren't deciding to just render completely off of my screen.
