### ISSUE TITLE
Attempting to put an item into your backpack will cause you to hit the backpack with the item

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#22121]
Probably works with belts, webbing, etc. as well

**Comment by Firecage** [comment]
I can confirm, its not just backpacks. Take a toolbox, take a tool out and put it back in. It will attack the toolbox AND put the tool back in.

**Comment by Crushtoe** [comment]
Happens with all storage items, including belts.

**Comment by MimicFaux** [comment]
And using screwdriver on a door.

**Comment by TrustyGun** [comment]
Please fix, this is extremely annoying

**Comment by optimumtact** [comment]
@ExcessiveUseOfCobblestone

**Comment by Cebasiz** [comment]
CLUNK

**Comment by ShizCalev** [comment]
Happens when using droppers on beakers as well, introducing attack delay to the process of doing viral research (slowing it down quite a bit.)
