### ISSUE TITLE
wizard-bought wands run out of charges after several recharges even with charge spell

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/tgstation#22136]
maybe this is intentional but after a few recharges wands (fireball, death, polymorph etc) go to -1 charges, appear as if they have been recharged but don't fire.

this is pretty fuggin gay because MM+einath which is way more cancerous is barely more expensive than wands + charge

also it doesn't mention this happens on the description of charge or the wands it probably should because if you are a wand-based blaster wizard and you run out of fireball you can't do anything anymore.

**Comment by TechnoAlchemisto** [comment]
Recharge gives diminishing returns

**Comment by PKPenguin321** [comment]
^

not an issue

**Comment by Cebasiz** [comment]
reeeee

**Comment by Cebasiz** [comment]
rebalance wizard for my benefit thx

**Comment by KorPhaeron** [comment]
@Incoming5643 ?

**Comment by Cebasiz** [comment]
i guess it's not an issue but it seems a little weird personally 

you can have way more cancerous bullshit and it's infinite, doesn't seem like wand of polymorph should have a fixed limit when it's way less awful

**Comment by Cebasiz** [comment]
maybe wand of death/fireball or something

**Comment by Incoming5643** [comment]
The weardown on wands is intentional, though I gotta say I'm impressed you actually used the wands enough to notice this, as the wand belt wands are given maximized charges.

**Comment by Cebasiz** [comment]
i didn't really have anything else besides time stop

at least there should probably be a warning on charge or the wands, or both

**Comment by Incoming5643** [comment]
I'll look into it. For a while charge wasn't even a purchasable spell, so when it was added I must have forgotten the feature.

**Comment by Cebasiz** [comment]
oh and it probably only took maybe 3 recharges on a wand of fireball

if you are considering using wands as your primary armament, there is no way like 3 recharges of fireball/death is enough to kill a crew above lowpop

**Comment by Cebasiz** [comment]
you get like what, maybe 10 shots of death total before it's permanently out of charge, also the wands appear charged when they are at -1 charges, which nearly got me killed like twice before i figured out wtf was going on

**Comment by Incoming5643** [comment]
Yeah that actually is a bug

**Comment by Incoming5643** [comment]
Upon playtesting, This actually is a bug, after a few recharges the wands suddenly drop to 0 uses left.

VERY odd.

**Comment by Cebasiz** [comment]
i knew it

since the charge degradation is fundamentally broken we can now remove it

REMOVE NOT IMPROVE WANDS FOREVER TWO ONE ZERO SIX

**Comment by PKPenguin321** [comment]
yeah honestly i wouldn't mind just nixing the diminishing returns, just make things like the wand of death only get 1 or 2 charges back instead of a full charge when recharged though

**Comment by Cebasiz** [comment]
>wands plus charge 3 points
>charge has a long cooldown which means if you are using wands at a decent rate you will have to slow down your rampage frequently to recharge

3 points is lower than 4 but you should be able to get potent utility for 3, and you do until like 1/3 of the way through the crew all of your offensive power runs out.

**Comment by Cebasiz** [comment]
if death wands is such a problem just nerf that instead of whole wandbelt plx

**Comment by Cebasiz** [comment]
personally though fireball is better but don't nerf fireball because it is my favorite thx

**Comment by Incoming5643** [comment]
The wand belt's primary point is utility, giving tools to the wizard that maybe they negated in spell selection. It's not supposed to match/surpass the effectiveness of a spell by itself.

**Comment by Cebasiz** [comment]
personally i think that's dumb, if you have to "for balance reasons" increase charge's cost to 2 to make it cost enough to get decent "permanent" wands, go ahead, then if people just want temporary utility they don't buy charge

i wasn't going for temporary utility at all, i wanted blasting power, which i had for a little while and then lolnope.

it's not like the wands are without their drawbacks: limited charges (in the short/long term if you don't have charge, fireballing yourself, they can get disarmed, can be used against you, can be destroyed, etc)

i don't think there's any real balance reason why they couldn't be more permanent than they are. at least a wizard with a fireball wand isn't the super-safe """""control wizard""""" lmao i spam MM+einath am i cool yet guys?????

**Comment by Dorsisdwarf** [comment]
If you wanted blasting power, you should have bought the actual spells, not the Box Of Tricks

**Comment by YakumoChen** [comment]
Yeah, you're exchanging power for utility, eg 2 spell points gives you access to like 6 different spells, with charge you get those 6 different spells for much, much. much more time, not to mention the added utility of charging any gun or similar item for free.

4 spell points gives you 2 good reliable spells, which you can cast infinitely, on the other hand, with only a cooldown. Infinite Ranged Ei Nath might make a good 3-pointer alone, but you also get 5 other spells along with it if charge doesn't give diminishing returns.
