### ISSUE TITLE
Broken yet pristine objects

### ISSUE THREAD

**Issue by Mervill** [tgstation/tgstation#22148]
The current implementation of [/obj/structure/examine(mob/user)](https://github.com/tgstation/tgstation/blob/master/code/game/objects/structures.dm#L91) allows an item to be both 'broken' and 'pristine and undamaged' at the same time, leading to things like

```
That's a mirror.
Mirror mirror on the wall, who's the most robust of them all?
It looks broken.
It seems pristine and undamaged.
```

In the case of the mirrors in the envy lavaland ruin

**Comment by XDTM** [comment]
that's just mirror code i think, the sprite becomes broken and updates the sprite with it but the actual item health is full

**Comment by Cyberboss** [comment]
I would like to know why this shit is in 3 places https://github.com/tgstation/tgstation/search?utf8=%E2%9C%93&q=It+seems+pristine+and+undamaged.

**Comment by Mervill** [comment]
@Cyberboss because in order to have the same functionality apply to `/obj/structure`, `/obj/vehicle` and `/obj/machinery` you would have to define the function on `/obj`

**Comment by optimumtact** [comment]
it should have been, with a flag that enabled it on structure/vehicle/machinery

**Comment by Dorsisdwarf** [comment]
The same with mecha wreckage happens.

Basically any item that could be broken before objsmashing was added does this
