### ISSUE TITLE
Inconsistent use of /area/space/nearstation on boxstation

### ISSUE THREAD

**Issue by Mervill** [tgstation/tgstation#22142]
I edited `areas.dm` to remove the text from the `/area/space` icon and gave a very visible icon to `/area/space/nearstation`. Here are some of the uses of the tile on boxstation (interestingly metastation does not use  `nearstation` at all).

Whats this big square of tiles for?
![](http://i.imgur.com/mJTvi22.png)

Missing from the top of the atmos cages?
![](http://i.imgur.com/bOc84MY.png)

Construction areas are lit, but the space around the vault isn't
![](http://i.imgur.com/J2ozVWZ.png)

Here they are used to light the engine area, but the metastation engine area isn't like this
![](http://i.imgur.com/C4LHzKI.png)

A lone tile near permma
![](http://i.imgur.com/8vrzmsB.png)

A lone tile on a wall near toxins
![](http://i.imgur.com/5FOiesK.png)

Inconsistent application near the mining doc
![](http://i.imgur.com/8GSr7NC.png)

Why does it feel like a vestigial feature to me?

here's the definition for reference

```DM
/area/space/nearstation
	icon_state = "space_near"
	lighting_use_dynamic = DYNAMIC_LIGHTING_IFSTARLIGHT
```

**Comment by XDTM** [comment]
Maybe it's related to where nuke ops can plant the bomb to win?

**Comment by Mervill** [comment]
Doesn't appear to be referenced by any other code

**Comment by XDTM** [comment]
It's lighting related, it seems that these do not emit light by themselves

**Comment by MrStonedOne** [comment]
basically, nearstation turfs have lighting on non-/turf/space turfs, where as /area/space turfs never have lighting, even if they are a non-space turf.

**Comment by Mervill** [comment]
That makes sense to me. What they actually DO is clear, but what they are actually FOR is less clear.

What is trying to be lit in the first image in the OP? What about around the vault? I'm just saying it seems inconsistently applied and I don't know if fixing that inconsistently involves adding or removing nearstation tiles.

**Comment by MrStonedOne** [comment]
I was just looking to replace any space areas that are likely to get built on or already have non space tiles.

Some of it was never fixed after people changed shit and just let it default to space, like that line above atmos tanks.

**Comment by Mervill** [comment]
I'm also fairly certain that the `nearspace` icon being practically indistinguishable from regular space has something to do with it, which is why https://github.com/tgstation/tgstation/pull/22143 is a thing

**Comment by Mervill** [comment]
well I guess now that the tiles are more visible this sort-of issue is closer to being resolved

closed for now
