### ISSUE TITLE
Only the roundstart electropack can be used to make electric chairs.

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#22155]
>One round I was me
>Print off an electropack from the autolathe
>Get a borg to fetch a helmet from security
>Make an electric chair, ensure I have a signaller set to the correct frequencies
>Make sure there was a powered cable knot underneath
>*click*
>Nothing
>Guy gets an electropack from re-education
>Switches them out
>It works

Probably something very snow-flakey going on codewise, can someone take a look? It's extremely non-intuitive about why that would be a thing

**Comment by MrStonedOne** [comment]
I bet if you change the frequency of the electropack it works.
