### ISSUE TITLE
Cremator can be destroyed

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#22162]
Not a bug
But this makes changelings tottaly invincible if they buy chit armor unless they get bombed

**Comment by FantasticFwoosh** [comment]
Critical question whether it can be reconstructed? Im not sure if there's a board attached to it to do the job, least i don't remember there being a board.

> Same applies to other machinery that is mutually exclusive and non constructable with R&D

(It could always be destroyed @jughu but you make a good case that a changeling could just armblade bash it to rubble rather than go to the effort to blow it up with high-power explosives prior to the damage PR.)

**Comment by jughu** [comment]
It cant be reconstructed even if admin spawns one it it doesnt work because its linked to a button to activate it

**Comment by Cebasiz** [comment]
these should probably be constructable along with gibbers imo

**Comment by jughu** [comment]
Cremating should just be a alt click on the cremator instead a button tbh and boards yeah

**Comment by GunHog** [comment]
>But this makes changelings tottaly invincible if they buy chit armor unless they get bombed

- Gibber
- Singularity/Tesla
- Brain removal surgery (?)
- Lavaland boss monsters
- Shield generators (The ones in Xenobiology)

There are more, but I cannot think of them at the moment.

**Comment by jughu** [comment]
@GunHog 
cant gib with chit armour on
contained ???
fake brain
SURE YOU GO WALK ALLLL THE WAY TO LAVALAND WITH THE LING YOU JUST CAUGHT AS OFFICER
i mean it doesnt stop the ling but it locks him up

**Comment by RemieRichards** [comment]
@jughu the admins can link the button.

**Comment by jughu** [comment]
@RemieRichards i guess but we still cant rely on admins for everything

**Comment by GunHog** [comment]
Are you **certain** that the gibber does not work on changelings with chitin armor? I just tried this locally and it worked on a default gibber.

**Ling with armor**
![screenshot 2016-12-13 12 05 53](https://cloud.githubusercontent.com/assets/4955510/21152598/961af588-c12c-11e6-862c-bd91957c9180.png)

**Gibbed ling**
![screenshot 2016-12-13 12 06 14](https://cloud.githubusercontent.com/assets/4955510/21152608/a2551298-c12c-11e6-83aa-9a27ebdb9843.png)

**Comment by KorPhaeron** [comment]
Not a bug

**Comment by jughu** [comment]
it used not to work
