### ISSUE TITLE
Coins not counting for luxury shuttle fare

### ISSUE THREAD

**Issue by Grazyn** [tgstation/tgstation#22167]
Have a lot of plasma coins (each worth 100 credits) in backpack, attempt to board the luxury shuttle, YOU DON'T HAVE ENOUGH MONEY

**Comment by jughu** [comment]
i tried to enter with diamond which is 2500 points they cannot afford they poor people

**Comment by Mindustry** [comment]
You need to have the money in your hand.

**Comment by KorPhaeron** [comment]
It doesn't work in bags, the loop needs to be recursive to check inside storage

**Comment by Arianya** [comment]
For low-value coins to work, maybe allow coins to be "stacked" in some way? Otherwise its impossible to board the station with any coin worth less then 250.

**Comment by coiax** [comment]
It just needs to check for stuff inside storage.

**Comment by ninjanomnom** [comment]
This was fixed by #23903
