### ISSUE TITLE
Coffee machine in permabrig metastation

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#22163]
Not a bug but probaly a oversight of the metastation mapper idk if intended but
Having coffee machine in permabrig is basically a free escape and makes the spacewalk to arrivals possible since it removes cold damage and then you can heal the kpa damage with donk pockets and escape to arrivals basically a free unjailcard

**Comment by FantasticFwoosh** [comment]
Its a hacking feature in the regular boxstation perma to hack the soda machines for a cup of coffee

> Getting the donk pocket is hypothetical given that if you just steal in a donk pocket, you could probably steal in a emag within your storage implant.

**Comment by jughu** [comment]
But this just gives you robust coffee without any effort of hacking and a box of donk pockets next to a microwave atleast make it a subtype coffee machine you need to hack to get robust coffee

**Comment by KorPhaeron** [comment]
@Metacide

**Comment by lzimann** [comment]
this makes meta's perma a big joke, not even a challenge to escape from

**Comment by ShadowDeath6** [comment]
when will being exposed to space without pressure-resistant gear be realistic and instantly gib you smh

**Comment by PKPenguin321** [comment]
that isn't realistic
do you even space?

**Comment by ShadowDeath6** [comment]
trust me, I went to space and instantly exploded irl, can you say the same

**Comment by MimicFaux** [comment]
Or we could just move to ZAS atmos for that explosive decompression fun.

**Comment by Cyberboss** [comment]
@MimicFaux LYNCH!!!

**Comment by Metacide** [comment]
I think back when I left this in people argued that it was still virtually impossible to survive the walk.

Happy to get rid of the coffee machine if you can hack the gruel dispenser for coffee anyway.
