### ISSUE TITLE
Xenos and facehugging are broken

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#22175]
Reply PM from- [REDACTED]: I'm sayin the aliens are broken right now and dont face-hug, though for some reason implanted alien egg sacs produce aliens that work

Reply PM from- [REDACTED]: Nothing else that I've noticed, I only spotted this yesterday when I rolled alien and got to be a queen, but the face-huggers didnt hug, yet last round before that I had an egg sac that worked fine

**Comment by WJohn** [comment]
So how many times has facehugging been completely broken? I'm gonna say at least 3 already, and this the 4th time.

**Comment by karlnp** [comment]
looking into it.
