### ISSUE TITLE
Air cycling in toxins doesn't actually work

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#22199]
At least on Box

> Walk into toxins airlock to up pump pressure
> Accidentally hit cycle airlock button
> Door bolts, air drains from room
> "Always enjoyed the vaccum burn anyway"
> Push again
> Air not refilling
> Why is air not refilling?
> Crit

Apparently the airlock doesn't actually refill the air and, once drained, it can't be opened again

**Comment by Cebasiz** [comment]
this shit has been busted literally forever as far as i know

maybe for LITERAL YEARS

it's a super snowflake system IIRC that probably needs to be replaced and/or standardized

**Comment by lzimann** [comment]
yea this has been around since forever and using cycle completly fucks up the door(you gotta ask an AI to open for you, or hack, etc)

**Comment by Cyberboss** [comment]
Why is it even necessary? Heat doesn't transfer through airlocks as far as I know (Although that sounds like a nice feature)

**Comment by Cyberboss** [comment]
Dupe of #10676
