### ISSUE TITLE
pAI hologram bugs

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#22206]
Can't examine the pAI holograms.
Pretty sure I saw one pull someone earlier.
AND ALL ACCESS JUST WHYYY
I'll edit it if I see anymore.
12-14-16 6:00 pm EST Bagil

**Comment by PKPenguin321** [comment]
@kevinz000

**Comment by karlnp** [comment]
- they can pull people. i got pulled into bridge.
- they cannot suicide. they might not be able to die at all, i saw someone say that.
- they have all access and no laws or tether
- they are pretty cool though and i do like them

**Comment by WJohn** [comment]
- Does not respect player preferences, sounds and text notification still appear and play, and it's really aggravating. Button doesn't show up, so at least that's working correctly.

**Comment by Anonmare** [comment]
pAis should be really weak, unable to pull and have zero-access by default. 

Maybe you could give pAIs some features to improve their holographic frame from science but they should be weak at the start.

**Comment by kevinz000** [comment]
@anonmare doing so

**Comment by kevinz000** [comment]
@karlnp I think PAIs have a special suicide verb I'l test that

**Comment by JJRcop** [comment]
I think they should just walk through doors

**Comment by kevinz000** [comment]
@lzimann fixed
