### ISSUE TITLE
Vending machines and airlocks can shock you from a distance.

### ISSUE THREAD

**Issue by RandomMarine** [tgstation/tgstation#22229]
Step 1. Wear Insulated gloves.
Step 2. Cut/pulse a vending machine's shock wire.
Step 3. Keep the wires window open and step away from the machine.
Step 4. Remove gloves.
Step 5. ?????
Step 6. Die
![shocking](https://cloud.githubusercontent.com/assets/6583225/21227898/a37d92e8-c290-11e6-979b-2a2b59e084c0.gif)

**Comment by jughu** [comment]
They learned lightning bolt clearly

**Comment by karlnp** [comment]
should add a proximity check to the hacking interface, since i can't imagine there being a justification for long-distance shocks like this.  i'll look at it presently

**Comment by karlnp** [comment]
does this also work with airlocks?

**Comment by RandomMarine** [comment]
Didn't bother testing those. I figure the issue's that it's calling shock() whenever the tgui updates. Can't be assed to find where it's doing this myself.

**Comment by karlnp** [comment]
Should be a quick test. _stares at you meaningfully_

**Comment by RandomMarine** [comment]
Yeah, they do the same thing.

**Comment by karlnp** [comment]
Thanks. Think I've found the issue. Time to try fixing and test and PR.

**Comment by karlnp** [comment]
yup. `modules/power/power.dm`, `electrocute_mob` proc. Checks for gloves but not adjacency. Will PR a fix that adds an argument which enables an adjacency check, off by default to preserve most current functionality. (and of course i'll fix this issue by specifying the arg on vendors and doors.)

**Comment by karlnp** [comment]
this was also true of most things with maintenance panels and wire interfaces.

**Comment by Mervill** [comment]
This can also be solved by modifying the tgui to do distance checks

**Comment by karlnp** [comment]
Mervill: https://github.com/tgstation/tgstation/pull/22231#issuecomment-267463837
