### ISSUE TITLE
autodrobe has some items unstocked roundstart

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#22222]
see title, how can I bee a bee without my bee suit

**Comment by Armhulen** [comment]
oh shit this get

**Comment by Iamgoofball** [comment]
FUCK I WANTED THIS

**Comment by PKPenguin321** [comment]
another WASTED FUCKING GET

**Comment by Armhulen** [comment]
>wasted
>to bee or not to bee

**Comment by dannno** [comment]
I moved around some things in it and it seems to just stop stocking things at a certain amount of things

**Comment by dannno** [comment]
using a restock on it stocks everything

**Comment by dannno** [comment]
after 81 things stocked, it just stops stocking
which seems like a weird and arbitrary number.

**Comment by RandomMarine** [comment]
Because somebody added products without updating vending_items.dm accordingly. Now those vendors don't start with full stock.

**Comment by dannno** [comment]
I WILL FIX IT BOYS
IT WAS PROBABLY MY FAULT :D

**Comment by ExcessiveUseOfCobblestone** [comment]
[Probably this](https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/weapons/vending_items.dm#L66)

**Comment by dannno** [comment]
well it's actually 81 not 75
whoever changed it previously just didn't change the comment
27 x 3 = 81
which explains the apparent arbitrary-ness of it
