### ISSUE TITLE
Setting mob reference in VV is broken

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#22233]
It will instead try to set it to path.
Same for Atom/Datum.
Not sure if this is a bug or just confusing naming and the actual reference option is missing.

@MrStonedOne

**Comment by ExcessiveUseOfCobblestone** [comment]
it does that to narrow what kind of mob you want.

For instance, if I want to set the mob as Lola Cobblestone, I'd click mob ref, put in mob/living/carbon/human, click strict type, then click on Lola's name.

Will say it's less convenient though.

**Comment by AnturK** [comment]
Oh, should have tried it to the end then, my fault. Could probably use some clarification in the popup name.
