### ISSUE TITLE
Windoor assembles can't be rotated

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#22248]
They always face south. Newly made ones with reinforced glass and ones made by deconstructing existing windoors are both broken. You can still flip them.

**Comment by XDTM** [comment]
Until it's fixed, you can sort of get around the bug by pulling the windoor

**Comment by PKPenguin321** [comment]
?

**Comment by AnturK** [comment]
Tested this yesterday, seemed to work fine ?
