### ISSUE TITLE
Nanotrasen bedsheets have no capesprite

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#22257]
see the problem is that pubby has these in every on-station dorm
and they're invisible and stuff we don't like that

should specify that it's invisible when WORN

**Comment by jughu** [comment]
Nanotrasen bedsheets do have sprites atleast the metastation ones pubby are bugged i guess

**Comment by Armhulen** [comment]
[http://i.imgur.com/KxbcbdO.png](test)
this

**Comment by jughu** [comment]
They do have sprites as i said just the pubby ones are some snowflake ones i think

**Comment by jughu** [comment]
Oh wait im dumb captain bedsheets differs from this one altough they look the same

**Comment by Armhulen** [comment]
you know what jughu
just GO >:(

**Comment by jughu** [comment]
![images-4](https://cloud.githubusercontent.com/assets/14280283/21277391/682c279e-c3d6-11e6-8228-b7bc3fd84709.jpg)

**Comment by Mervill** [comment]
also an issue for the ian blanket. Also, there is an ian blanket

**Comment by Crushtoe** [comment]
I had to make a cape sprite for the black bedsheet a while back. Never thought this would be an issue again.

*You keep adding more blankets.*

**Comment by Mervill** [comment]
- [ ] NT
- [ ] grey
- [ ] ian

**Comment by Armhulen** [comment]
capesprites are so shit that someone should just redo them all anyways
