### ISSUE TITLE
You always slide on broken glass, never step on it

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#22258]
Being dragged over broken glass makes you slide on it, checks out

Walking over broken glass makes you slide on it, uhhhhh

**Comment by jughu** [comment]
The only snowflake coded this for his immersion
And fucked up at it too

**Comment by Militaires** [comment]
@jughu yeah

**Comment by jughu** [comment]
But would glass shards hury when i slide trough them with clothing on :)

**Comment by Militaires** [comment]
Yes.

**Comment by ExcessiveUseOfCobblestone** [comment]
@optimumtact can you close this
