### ISSUE TITLE
ai laser turrets do not get reflected, they pass through the dualesword instead

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#22265]
ai turret lasers passed through, no reflections.

the guy didn't get hurt, so you know

**Comment by XDTM** [comment]
Reflection code re-shoots the laser when reflecting it. I think that it couldn't recognize the source and thus didn't reset the direction.

**Comment by Armhulen** [comment]
so i'll rename it to ai turrets, howsa that.
