### ISSUE TITLE
Changeling Last Resort doesn't work

### ISSUE THREAD

**Issue by uraniummeltdown** [tgstation/tgstation#22267]
I was a changeling who last resorted after regenerative stasis, went to Genetics and killed a dying Geneticist and laid my egg, then climbed into a disposals unit and ghosted out of the dead headslug. A few minutes later the monkey hatched from the egg and gibbed the Geneticist, but I didn't get control of the monkey. I asked Incoming to place me inside the monkey, and the monkey didn't have changeling status or my memories, it was just a normal monkey instead of carrying over my changeling mind. This makes the whole ability pointless.

**Comment by PKPenguin321** [comment]
You aren't supposed to ghost out of the headslug, its just supposed to die a while after planting the egg

**Comment by Armhulen** [comment]
what a noob, lmao

**Comment by uraniummeltdown** [comment]
It did die after planting the egg, and after it died I ghosted out (you know when you move when dead and it auto ghosts you)

**Comment by Armhulen** [comment]
i retract my previous statement, we should really fix it.

**Comment by jughu** [comment]
Probaly cuz you were in a disposal

**Comment by uraniummeltdown** [comment]
Well I was a headslug recently and got monkeyed just fine, so it's probably the disposals that caused the problem.
