### ISSUE TITLE
Evidence bags don't show contents

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#22273]
Evidence bags don't show contents when used on a item in your backpack and stay at the same sprite like it never has been used but still include the item

**Comment by Mervill** [comment]
If you drop the Evidence bag, or place an item into the bag while it's on the ground, the item in the bag will be shown correctly. Only seems to be an issue when you're holding the bag

**Comment by Mervill** [comment]
The issue seems to be that when you're holding the evidence bag, the sprite of the item it contains is below (obstructed by) the left/right hand UI image

**Comment by Mervill** [comment]
https://github.com/tgstation/tgstation/blob/master/code/modules/detectivework/evidence.dm#L54

**Comment by MrPerson** [comment]
If you don't fix this bug by the time 511 comes out of beta, I'll fix it then since I'll pretty much be rewriting how this all works. You can fix it sooner if you want, which'll make it easier. Your call.
