### ISSUE TITLE
Shuttles should probably be shielded from radiation storms.

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#22276]
![tgstation bagil english 100 free lag come and nuke us 13 5-pigreytide algoritm 2016-12-17 151427](https://cloud.githubusercontent.com/assets/4047233/21287445/f5c03664-c46b-11e6-8a41-bf4bd57782b8.png)

Or not because it's pretty funny.

**Comment by GunHog** [comment]
They should not be a shelter, **unless they move to a place where the storm is not occurring.**

**Comment by jughu** [comment]
just add a unique shuttle that can be bough which is rad proof so there be some adventage to it :)

**Comment by Firecage** [comment]
@GunHog To be fair, Arrivals Shuttles ARE already shielded from radiation storms. So this would be more of a consistency thing than anything else.

**Comment by karlnp** [comment]
do arrivals shuttles move at all?

**Comment by Cyberboss** [comment]
@AnturK dupe of #20432

**Comment by Cyberboss** [comment]
@karlnp They really should. Stops spawncamping too

**Comment by RandomMarine** [comment]
Arrivals shuttles don't move. And SHOULD remain exempt from any adverse weather effects, it'd be shit to join the round and spawn right into the middle of a rad storm. While anyone trying to board the escape shuttle has a fair enough warning to either hole up in maint until seconds before launch, or obtain a radsuit.

**Comment by AnturK** [comment]
Whoops, didn't notice issue already exists
