### ISSUE TITLE
pAI Pushing

### ISSUE THREAD

**Issue by Nabski89** [tgstation/tgstation#22286]
You are able to push people on a scooter as a pAI, vs walking through everyone else.

**Comment by Armhulen** [comment]
pAIs shouldn't be able to get on a scooter

if i'm understanding this right the scooter is pushing the people, not the pAI.

**Comment by Nabski89** [comment]
Sorry. If someone is on a scooter you can push them.

**Comment by Aloraydrel** [comment]
moving pAI's was a mistake
