### ISSUE TITLE
Objs that go on walls need to be handled better when the wall is removed

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#22283]
I mean, we need a better solution that just leaving them there honestly
![untitled](https://cloud.githubusercontent.com/assets/8171642/21290228/5e449220-c480-11e6-9d85-76de5971181e.png)

**Comment by PKPenguin321** [comment]
Smells like a feature request

**Comment by Cyberboss** [comment]
More like a consistency issue

**Comment by Firecage** [comment]
B-but....they aren't even on the wall. They are on the tile infront of the wall. Like that newscaster is on the same tile as the file cabinet, just pixel shifted.

**Comment by RandomMarine** [comment]
Even with those objects that are actually on the tile beside the walls, what do you propose be done about them? Just delete them too so that bomb repairs are an even bigger pain in the ass?

**Comment by Mervill** [comment]
Almost everything that goes on walls is actually on the tile "in front" of the wall and is then pixel-shifted  onto the wall.

It simplifies a bunch of stuff, both in calculations and usability. For example, if you had an APC behind a computer and the APC was actually on the wall tile, you wouldn't be able to access the it (as it's blocked by the computer), with the computer and APC on the same time (APC pixel-shifted) this issue is sidestepped.

You might be able to tag various objects as "on the wall" and check for any "on the wall" objects in the neighboring tiles of any wall that's destroyed. Edge cases will abound.

**Comment by karlnp** [comment]
>edge cases
heh heh. good one, mervill.

**Comment by coiax** [comment]
@Mervill what if we got rid of the map specified pixel shifting, and had the objects automatically "dock" onto the wall that they are facing (with dir). Then the objects know what wall they're on, and it also makes map editing uglier from a map editing viewpoint, but easier from a maintainaiblity standpoint

**Comment by Mervill** [comment]
I was thinking the opposite, actually. We could have a tag of some kind, say `IS_WALL_MOUNTED` along with a minimum tolerance `MIN_WALL_MOUNT_SHIFT` anything that's wall mounted and has either its X or Y value "above" the minimum wall shift can give it's reference to the wall it's supposed to be attached too (the wall could keep a list of `var/mounted_objects`), then when the wall is removed it simply tells any `mounted_objects` to react to the remove event. The initial assignments could be done as a roundstart hook similar to icon smoothing.

Alternately, you could place wall mounted objects directly onto the target wall in the editor (without pixel shift) and do a similar process to the above (taking place at roundstart) that moves the object to the tile "in front" of the wall and then pixel shift backward.

The devil really is going to be in the edge cases (har har), especially with objects that are currently happy to live directly on the wall tile without pixel shift.

It's definitely worth looking into more, but it will be a big project no matter which route we take.

**Comment by coiax** [comment]
> Alternately, you could place wall mounted objects directly onto the target wall in the editor (without pixel shift) and do a similar process to the above (taking place at roundstart) that moves the object to the tile "in front" of the wall and then pixel shift backward.

That also works. Using dir as the direction it advances onto.

It's either going to be a big project codewise, or a big project mapwise. There are also weird side cases, like light fittings (any others?).

**Comment by Firecage** [comment]
Of course, if this does ever get around to being done, it would probably also be great if wall mountings, like, say, security cameras, could also go on windows just for the sake of gameplay.

**Comment by timothymtorres** [comment]
This would be very nice but it would also take a lot of work to do.
