### ISSUE TITLE
Monkeys burn forever

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#22285]

**Comment by karlnp** [comment]
Good.

**Comment by Mindustry** [comment]
What's the issue?

**Comment by Firecage** [comment]
Can you perhaps expand in this issues explanation? Just tested setting two monkeys on fire(one directly, second indirectly). Both set on fire and extinguished after a bit correctly.

**Comment by Cyberboss** [comment]
May have been fixed then. Will test tomorrow and see if that's the case.
