### ISSUE TITLE
Multiple Advanced Virus Infections

### ISSUE THREAD

**Issue by Nabski89** [tgstation/tgstation#22282]
User can be infected with multiple custom virus's. Only one will show up on the health scanner.

Step 1: Create a custom virus (V1). Something with easy to notice effects such as self combustion or respiration is advised. Infect self with V1.
Step 2: Create a second unrelated virus(V2). Infect self with V2, method used here was drinking.
Step 3: Examine self with health scanner. Only one illness is visible, but effects of both continue to occur.

Step 4: Repeat with more virus's. I am unsure how many can be stacked, and how the transmission rate interacts with it, but I am pretty sure it has some effect.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

This bug was checked with Thunder12345. As far as I could tell they couldn't see the second infection either.

**Comment by XDTM** [comment]
That is pretty odd. Virus code checks that there is no other virus in the mob's viruses var before adding a new virus. I'll have to test this out.

**Comment by AnturK** [comment]
You sure you just didn't mix them ?

**Comment by Nabski89** [comment]
Yes. I am sure.

**Comment by Tacolizard** [comment]
iirc the wiki says you can be infected with 3 viruses at once

**Comment by XDTM** [comment]
That's before my rework, and i think i updated that part of the wiki as well.

**Comment by Robustin** [comment]
I have yet to see this reproduced

**Comment by Nabski89** [comment]
I've played with this one a little more. Something with transmission (N) will stay if you get something with transmission (N+1). Going the other way around doesn't work. I haven't done it in the last few months so maybe it got accidently fixed. I will try and re-replicate it again.

**Comment by timothymtorres** [comment]
I believe this was fixed with #38777 or maybe #28556.  There have been about a dozen Virus PRs that could have solved this issue.  Ping me if it doesn't appear to be fixed.
