### ISSUE TITLE
tgui compilation should be worked into the build process

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#22293]
Less room for error on our parts.

Just have the bot that does the changelogs handle it if there are changes to ract files without changes to tgui.css/js

**Comment by karlnp** [comment]
or you can just build_assets.bat/sh && byond commandline args. that should take care of it and only lengthen startup by 30s

**Comment by Cyberboss** [comment]
Maybe, that'd require all coders to build it themselves though.

**Comment by karlnp** [comment]
they have to build anyway and i'm adding a script that lets them build tgui & also compile byond in one step

**Comment by AnturK** [comment]
If you want to add it to travis makes sure to check if /tgui changed, it's slow enough as is.

**Comment by optimumtact** [comment]
This is not a bug, use the feedback forum/coding forum or irc!
