### ISSUE TITLE
People can get the Ratvar conversion message without being converted

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#22300]
Reply PM from [redacted]: Well I ran into [redacted] and got fucking destroyed as far as things go so I was in crit, but the rune that(?|F) converts glowed and dissapeared and I got the flavor text 

Reply PM from [redacted]: Your mind is racing! Your body feels incredibly light! Your world glows a brilliant yellow! All at once it comes to you. Ratvar, the Clockwork Justiciar, lies in exile, derelict and forgotten in an unseen realm. 

This was well into the round, but the person did not get converted, I checked. The person in question was implanted if that helps

@ChangelingRain

**Comment by ChangelingRain** [comment]
Feature I'll just make it more obvious that you aren't actually affected
