### ISSUE TITLE
After Ark of Ratvar was activated massive server lag 

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#22308]
![image](https://cloud.githubusercontent.com/assets/6778786/21300618/7f73e614-c573-11e6-9e00-f2c317bdcebe.png)

@ChangelingRain I bet its that shit you did where you make it move rooted stuff.

Kor's theory is it fucked atmos

**Comment by ChangelingRain** [comment]
this is 0% useful I don't even know what was near it at the time can you get some actually useful info, like what was near it, maybe????

**Comment by Kromgar** [comment]
IT was in the AI satellite on meta south of the core that center room

**Comment by ChangelingRain** [comment]
or in other words there was literally nothing next to it?

**Comment by Kromgar** [comment]
We have no other explanation for the sudden lag after the ark went up. ARk went up and the server fucking chugged

**Comment by ChangelingRain** [comment]
yes but those aren't dense objects
I'm blaming kor and his holodeck plasma flood because there are no related runtimes or infinite loops

**Comment by Cyberboss** [comment]
I have had holodeck floods crash MC before
