### ISSUE TITLE
Can't finish Firefighter Ripleys

### ISSUE THREAD

**Issue by Leon9621** [tgstation/tgstation#22329]
Not much to say here, I've done every step up to adding the metal for the internal armor on a firefighter Ripley and I just can't add the metal for it.

**Comment by lzimann** [comment]
This is not entirely a bug. You need to add the external armor twice(it requires 10 plasteel and it only adds 5 each time). You can get around it by just using the plasteel twice and then continue the build normally.

**Comment by Leon9621** [comment]
It's the internal armor, the regular metal that I can't add.

**Comment by lzimann** [comment]
Internal armor is plasteel aswell.
