### ISSUE TITLE
Human with Blood Crawl can delete other humans

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#22325]
Basically, if you are a human with blood crawl, and you are in the blood crawl stage, you can delete other humans by grabbing them around the neck.

Step 1. Get Blood Crawl
Step 2. Crawl into any blood you wish.
Step 3. Grab a human until you finish grabbing them around the neck.
Step 4. Behold as they disappear from this universe.

**Comment by karlnp** [comment]
at a guess: 
https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/bloodcrawl.dm#L138

that seems like a silly line of code. anyone know why it'd be set up like this?

**Comment by ExcessiveUseOfCobblestone** [comment]
you should probably just have a check for if someone is already in the bloodcrawl state.

**Comment by Crushtoe** [comment]
@karlnp Do the blood and honk demons that the wizard summon use that proc?

**Comment by coiax** [comment]
> Step 3. Grab a human until you finish grabbing them around the neck.

The problem is hands free grabbing, I think. Human blood crawling fills the hands, so with old grab, this wouldn't be possible.

**Comment by coiax** [comment]
@karlnp the reason that bloodcrawl_swallow() is a seperate proc is so laughter demons can put people in their stomach when swallowing them

**Comment by kriskog** [comment]
This is fixed, cant interact with anyone while blood crawling.
