### ISSUE TITLE
Shuttle lands at syndie base if ANY antag hijacks

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#22337]
See https://github.com/tgstation/tgstation/pull/22184

Breaks immersion for things like all-cultist shuttles

@coiax

**Comment by Cebasiz** [comment]
SYNDICATE IS BEHIND THE CULT #WAKEUPSHEEPLE

**Comment by lzimann** [comment]
probably because it only checks for `player.mind.special_role` instead of checking if it is an actual traitor(it was not a problem before)

**Comment by Kromgar** [comment]
Coiax even specifically states he left that in

**Comment by jughu** [comment]
I mean technically changelings, traitors, nuke ops, wizards, rev are alligned with the syndiecaTE

BUT RATVAR AND NARSIE TOO?
NEW LORE NEW LORE

**Comment by Cyberboss** [comment]
only traitors and ops are syndie. rev is the crew, wizards are the federation and lings are ayyish

**Comment by lzimann** [comment]
So... I accidently commited a fix to this(while trying to make a pr) [here](https://github.com/tgstation/tgstation/commit/a8e280c2e20deb747ef159083eb8f032e96e249d)

I can make a revert if people prefer all antags hijacking the shuttle(or at least a PR on this)...

**Comment by optimumtact** [comment]
Well it's fixed now
