### ISSUE TITLE
Dead drones can be used to open doors

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#22334]
The following is for cyborgs and drones(PREFERBLY DEAD DRONES)

So today i killed a drone i wondered if i alt click the door pull the drone then click the floor so it forced it into a door and guess what IT OPENED! DEAD DRONES ARE THE ULTIMATE ALL ACCEED

**Comment by karlnp** [comment]
not a bug? it's documented on the wiki

**Comment by jughu** [comment]
But drones?

**Comment by lzimann** [comment]
Pretty sure a dead drone opening a door is not intended.

**Comment by Kromgar** [comment]
If its on the wiki it can't be a bug

**Comment by Mindustry** [comment]
You've always been able to do this with borgs and really anyone who has access, just throw them into the door and it will open.

**Comment by lzimann** [comment]
I don't think you can do it with borgs. But honestly using a dead drone really feels like it shouldn't be happening.

**Comment by PKPenguin321** [comment]
You can definitely do it with borgs and that much is a feature, but doing it with dead drones is a bit too far IMO.

**Comment by Cyberboss** [comment]
The problem is doors rely on `Bump` to check who opened them

**Comment by Supermichael777** [comment]
delete drones id on death.

**Comment by lzimann** [comment]
You could do that, but drones can revive other drones, so you would have to spawn other ID after.

**Comment by ExcessiveUseOfCobblestone** [comment]
just not build drones is the best solution.

**Comment by Mervill** [comment]
I like playing drones, tbh

**Comment by jughu** [comment]
Who even revives drones they just go to a new shell when they die
