### ISSUE TITLE
Combat Gloves can't be colored

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#22336]
Can't color combat gloves with the washer?

**Comment by bgobandit** [comment]
possibly intentional, you can only color subtypes of /obj/item/clothing/gloves/color/

**Comment by jughu** [comment]
Kinda lame tbh

**Comment by BeeSting12** [comment]
Doesn't sound intentional, and even if it is, it shouldn't be. Doesn't make sense that insulated gloves and black gloves can be colored, but combat gloves can't.

**Comment by lzimann** [comment]
It's more of a balance thing. I'll close since it's not really a bug.

**Comment by Iamgoofball** [comment]
Why is the non-coder a maintainer?

**Comment by lzimann** [comment]
not a maintainer and what are you talking about of "non-coder"

**Comment by Iamgoofball** [comment]
"lzimann closed this issue 12 minutes ago"

**Comment by Iamgoofball** [comment]
"lzimann added the Not a bug  label 12 minutes ago"
