### ISSUE TITLE
You can disarm syndiebombs by bashing them until they break

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#22341]
How to reproduce
- Find a syndiebomb, armed or not
- Bash it with something for a little bit (or blow it up)
- It vanishes and drops a bomb core

**Comment by lzimann** [comment]
should probably make it explode if it's armed(or even if it's not, after all you are bashing a bomb)

**Comment by Cyberboss** [comment]
THA'TS WHY MY BOMB DIDN'T GO OFF??? THEY LIFTED MY PRINTS OFF THAT SHIT!!!!

**Comment by Cyberboss** [comment]
THIS SHIT GETTIN FIXED NAOW!!!!

**Comment by KingPhilipIII** [comment]
Well. Technically speaking modern plastic and high explosives don't detonate when struck or damaged kinetically. It's from electricity.  Being able to smash apart a bomb isn't that unfair. Maybe make it more damage resistant.

**Comment by Cyberboss** [comment]
The bomb core is intentionally unstable

**Comment by KingPhilipIII** [comment]
Well. I guess that's more a matter of lore on what the explosive core is made of I suppose. I understand logic always takes a backseat to gameplay but unless the bomb is already armed and you break the detonator in an unfortunant manner no chance of an explosion really exists.
