### ISSUE TITLE
Meta xenobio slime killing pen has two output vents. Needs a gas intake vent

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#22350]
So the freezer has 0 use. None of the slimes get sucked into the vent because there is no vent taking in any air

**Comment by XDTM** [comment]
One thing that annoys me about vents is that all the slimes are sucked into one tile making it hard to pick a single slime to grind

**Comment by ExcessiveUseOfCobblestone** [comment]
@XDTM if you could make a space heater+ [one that uses power from the local apc instead of a battery] you could replace the vent with a scrubber which would solve that [unless you siphoned or something dumb].

**Comment by Kromgar** [comment]
Fixed
