### ISSUE TITLE
Cyborg Medborg Hypo upgrades do nothing

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#22373]
I got the max-strength one but the chems were the same

**Comment by coiax** [comment]
Fuck

**Comment by coiax** [comment]
I have attempted to reproduce this, but have been unable to. Could you provide any more details?

**Comment by YakumoChen** [comment]
The chem list didn't update despite having an upgrade and I couldn't use any further number of chems.

**Comment by coiax** [comment]
Well, I tried performing an upgrade locally, and the chem list was fine. I'll see if I can get a check on the main server, see if it's present in production.

**Comment by coiax** [comment]
Doesn't seem to be present in production either.

**Comment by YakumoChen** [comment]
weird.. I'll report it if I get it again, I'll play more borg.
