### ISSUE TITLE
PLANT POD BUG HIGH EMERGENCY

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#22378]
IF YOU WRAP PLANT POT
IF YOU UNWRAP IT IN YOUR HAND
YOU HOLD SAID PLANT POT WITH ONE YES ONE HAND
IF YOU WRAP ANOTHER PLANT POD AND HOLD IT
YOU BUG YOUR SPRITE OUT INTO A PERMAMENT PLANT POT

**Comment by WJohn** [comment]
How do people find these bugs?

**Comment by jughu** [comment]
@wjohn a person on para station reported it so i tested if it was for this code base too since they ported from afterall i think this is the same case for mining axe anything that autowields and is wrappable

**Comment by XDTM** [comment]
should check for mob_can_equip in parcel code and drop it on the ground if false

**Comment by Armhulen** [comment]
finally i can play as a diona on tg

feature

**Comment by Incoming5643** [comment]
Edge case bugs are always the funniest bugs
