### ISSUE TITLE
[Delta Station] Test range won't work with test range weapons

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#22386]
Cant fire test range weapons in test range

**Comment by Okand37** [comment]
Which testing range are you unable to fire in, security or research?

**Comment by jughu** [comment]
Probaly science

**Comment by golfer45** [comment]
sci

**Comment by Okand37** [comment]
I don't seem to be able to replicate the issue, could you try replicating it and if you're successful, tell me how you've managed to replicate it in detail?

**Comment by optimumtact** [comment]
Report on the map thread
