### ISSUE TITLE
You can not modify xeno organs via the VV menu

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#22396]
The VV dropdown menu has an opetion to modify organs, attempting to do so on a xeno will give an error and state that this type of mob cannot have its organs modified. 

However, you evidently can modify organs via old fashioned surgery and the cyber implants function as intended, suggesting to me this is a consistency issue. It's not a serious issue but if I ever wanted to mod a xeno's organs for any reason, doing it manually is very time-consuming.

**Comment by lzimann** [comment]
What kind of alien was it?  If it was a simple_animal they don't have organs. Plus I tested on a carbon/alien and it worked just fine.

**Comment by Anonmare** [comment]
I tested it on a player-controlled carbon mob xeno. The specific alien I was using was an alien queen and praetorian, I didn't check the sentinels or hunters

**Comment by MrStonedOne** [comment]
that vv option only shows for carbons, the code says carbons have organs. it could be moved to human, but if carbons have the ability to have organs, might as well keep it lower on the chain.

**Comment by lzimann** [comment]
Carbons do have organs(aliens have like 10 organs) and I was able to edit normally when I tested it.
