### ISSUE TITLE
No cooling system for Supermatter and it stabilizes?

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#22403]
I dunno if its been super toend down but these things are harder to break than any other engine and it screams if its gonna go nuclear too

![image](https://cloud.githubusercontent.com/assets/6778786/21415048/9172a2bc-c7d3-11e6-8b51-b6026d3c0770.png)

Cooling sysstem breaks down and it actually starts to stabilize

**Comment by Firecage** [comment]
Kromgar. So whats the issue? That it's not a round ending engine?(That is, unless you fail to set it up on Birdboat and the power fails)

**Comment by Kromgar** [comment]
Every engine should have the chance of catastrophic failure fucking everything up if not mantained properly. Otherwise why would anyone choose singulo or tesla over supermatter... which still really only affects the engine area its in

**Comment by Armhulen** [comment]
we could have demons pour out of a supermatter portal

we could have the explosion shoot supermatter shards that act like immovable rods

i mean it shouldn't be that hard to make a round ending engine that doesn't copy the other two

**Comment by Firecage** [comment]
Fuck no. We do not need bloody round ending engines. I personally wish we could just remove the Tesla and Singularity, since I am tired of round #99999 being over in virtually 5 minutes due to loose singularity/tesla! Please wait until the shuttle finishes refueling!

**Comment by jughu** [comment]
Its not the engine thats the problem its the engineers and antags!

**Comment by Kromgar** [comment]
Also the engineers need SOMETHING to keep them on their toes

**Comment by lzimann** [comment]
Unless I'm horribly wrong, this is not really a bug, more of a feature request to supermatter not being deadly enough.

**Comment by Iamgoofball** [comment]
I'll fix it
