### ISSUE TITLE
plant reagents are...fucky

### ISSUE THREAD

**Issue by vcordie** [tgstation/tgstation#22401]
Plant reagents don't seem to behave evenly, the way say, a chemmaster does. let's take for example deathnettle. Deathnettle has 50% facid, then 50% sacid. At 50 potency, you would expect that each death nettle would therefor contain 25u of facid, and 25u of sacid. therefore, grinding up a 50 potency death nettle should net you 25u of facid, and 25u of sacid. Actual result: 26u of facid, and 24u of sacid. grinding 2 provides you with 52u of facid, and 48u of sacid. Furthermore, they bug out at 100 potency, due to reagent capacity. The reagent capacity of a death nettle is 50. Therefor, at 100 potency, a death nettle contains 50 facid, and nothing else.

**Comment by Core0verload** [comment]
Stronger reagents displace the weaker ones. It's supposed to work like that.

**Comment by Buggy123** [comment]
According to Core0verload this is not a issue, should we close it?
