### ISSUE TITLE
Condiment bottles are..fucky

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#22400]
Condiment bottles are...fucky, with their last unit. Their last U seemingly doesn't dispense a full u of it, though everything else displasy it as a full u. This creates situations such as the following (beaker is not cyrostasis) http://imgur.com/a/pVxeW

Steps to reproduce:
have a condiment bottle that contains 20 corn oil
empty it into a beaker
put 10 more corn oil into that beaker, and 10 sulphuric acid
scratch your head as only 9 units of gylcerol are created due to the bugged unit of corn oil.
I've also noticed that this affects syringes too
have a bottle containing 15u of something
draw all of it via syringe
notice as the syringe doesn't swap over to inject mode, instead staying in draw mode, able to draw an "extra" u more then usual.

**Comment by Firecage** [comment]
With the part part of the Glycerol, I couldn't reproduce it. It gave me 10 units of Glycerol.

**Comment by Qustinnus** [comment]
couldnt reproduce

**Comment by PKPenguin321** [comment]
Very late to this but this probably isn't specific to condiment bottles, lots of chem transfer procs would seemingly get random floating point errors. This may have been since fixed
