### ISSUE TITLE
Revenants can't alt-click floor tiles to list pile contents, corpse piles new chaplain meta

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#22410]
Title says it all. Alt-clicking returns the same as shift-clicking, giving a description of the floor tile.

**Comment by ExcessiveUseOfCobblestone** [comment]
Why

**Comment by Iatots** [comment]
if you are asking why corpse piles are the new meta, it's because you need to click on corpses to absorb their souls. There is no right-click option or button for it.
