### ISSUE TITLE
black and red space suit descriptions

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#22419]
I don't know what to call this so I'll just present it
That's a black and red space suit.
Has a tag on it: Totally not property of of a hostile corporation, honest!
It is a normal-sized item.
  That's a black space helmet.
Has a tag: Totally not property of an enemy corporation, honest.
It is a normal-sized item.
tags on a helmet, weirdly same descriptions on items that shouldn't... :confused:

**Comment by lzimann** [comment]
[Helmet](https://github.com/tgstation/tgstation/blob/a9be4e68d08697aad2bab6c2dbad955e733fadc6/code/modules/clothing/spacesuits/syndi.dm#L6)
[Suit]
(https://github.com/tgstation/tgstation/blob/a9be4e68d08697aad2bab6c2dbad955e733fadc6/code/modules/clothing/spacesuits/syndi.dm#L13)

Not exactly an issue, althought the "has a tag" on the helmet does feel weird.

**Comment by Armhulen** [comment]
I know it's a stretch, it just seems really off to me

**Comment by Shapsy** [comment]
Why would similar items in a set having similar descriptions be wrong? If anything, the differences in exact wording sticks out more to me

**Comment by Armhulen** [comment]
> the differences in exact wording sticks out more to me

this
If we're going to do the same sets have same descriptions, we should at least do it right.
