### ISSUE TITLE
Cycler Shotgun back sprite isn't quite right

### ISSUE THREAD

**Issue by dannno** [tgstation/tgstation#22413]
![](http://i.imgur.com/3nQTNsM.png)

**Comment by jughu** [comment]
dupe

**Comment by Haevacht** [comment]
Fucking. It's onback sprite is invalid, causing the sky bulge, which at the time had no name in the .dmi, to show up instead. This is since fixed by #22381 in part. There won't be a shotgun, but there won't be a spear.

**Comment by Armhulen** [comment]
literally make that rod shorter, black, and without the purple shit on the sides and you have a cycler shotgun backsprite
