### ISSUE TITLE
Simple mobs can survive in space

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#22424]
I think I fucked up somewhere along the lines of the basic atmos checks. Currently mice and Ian ignore the rigours of space.

**Comment by jughu** [comment]
Oh thats why the space pirates didnt die last time in space

**Comment by Armhulen** [comment]
space pirates have built an immunity to space

**Comment by Mindustry** [comment]
I've noticed when fighting the syndicate operative in the listening post, that besides being space proof and able to turn and thrust in space magically, they also HEALED IN SPACE.

**Comment by coiax** [comment]
wait I noticed that as well

**Comment by coiax** [comment]
give me a second
