### ISSUE TITLE
Unable to change filter type on gas filters

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#22456]
Unable to change filter type on gas filters

**Comment by Okand37** [comment]
As some additional extra information on this, you can change the volume, turn it on/off, but when you try to change the filter it acts funny:
Nothing is selected on the filter initially, so if its say, set to filter plasma at roundstart nothing will be highlighted, then if you try to change it, it gets stuck on 'nothing' and you can't change it.

**Comment by MrStonedOne** [comment]
most likely related to the test merged pr. 

Also please be sure to include the name of the server the bug was found on. tg has two, and they can run different versions of the code.

**Comment by jughu** [comment]
Yesterday this was working fine when i was filtering plasma so yeah its the pr

**Comment by MrStonedOne** [comment]
I need more than "yesterday"

I need a server name. sybil or bagil. it's only test merged on one, and it was only test merged for certain period of time.

It's better to be sure

**Comment by Iamgoofball** [comment]
easy fix the filters directly reference gas IDs from the tgui

**Comment by jughu** [comment]
Yesterday on bagil around 8pm cest they were working fine

**Comment by Cyberboss** [comment]
Yeah, that was my fault, this can be closed

**Comment by lzimann** [comment]
Result of a test merge.
