### ISSUE TITLE
Syndicate Bombs not detonating

### ISSUE THREAD

**Issue by Okand37** [tgstation/tgstation#22451]
It seems theres an issue with syndicate bombs not exploding. When you try to active it them, they'll 'prime' and switch to the primed sprite, then simply turn off and go back to the regular sprite. Mashing all of the wires fails to blow it up as well, and the bomb cores are still inside. The bomb core can still work when taken out and blown up through other means, but the bomb itself refuses to activate regularly.

**Comment by Kromgar** [comment]
Oh god damn it.

@coiax Pretty sure you fucked with syndiebombs or was that @Cyberboss you have similar avatars

**Comment by Kromgar** [comment]
Also they detonate when shot at

**Comment by Kromgar** [comment]
#22349 is the cause

**Comment by Cyberboss** [comment]
https://github.com/tgstation/tgstation/pull/22349/files#diff-43602ee63bd4ec742c4e894b058f12ddR73

Yep, missed that

**Comment by Cyberboss** [comment]
Also our avatars are NOT similar

**Comment by coiax** [comment]
We both have the color blue, clearly they are the same
