### ISSUE TITLE
AI CANNOT INTERACT WITH THE SATELLITE CONSOLE

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#22460]
HOW WILL I MAINTAIN COMPLETE CONTROL

**Comment by lzimann** [comment]
Gotta be more specific on which console/map.

**Comment by Armhulen** [comment]
the anti meteor console named satellite control

**Comment by Haevacht** [comment]
And which map?

**Comment by jughu** [comment]
Metastation

**Comment by Mindustry** [comment]
Isn't that the station goal, anti-meteor shield console? It connects to the hopefully setup meteor shield generators or whatever they are.

**Comment by Armhulen** [comment]
it is a station goal

**Comment by AnturK** [comment]
Whoops, probably put the code in attack_hand instead of interact.
