### ISSUE TITLE
Someone apply this fix from yogs

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#22492]
It's 1AM and I'm too lazy to do it

https://github.com/yogstation13/yogstation/pull/1491

**Comment by AnturK** [comment]
Sure, but the churn will still be there for item buttons which are the 99% of them. And it's there because there's no easy way to detect if item's appearance changing is due to px changes. The alternative was to make the ab icons update manually which would make them pointless.

**Comment by ExcessiveUseOfCobblestone** [comment]
If this is a problem on TG, we can probably just make generic sprites (see standus for ref) that show it's a toggle but doesn't actually change. Aside from Hiero staff, I'm not sure of any item that toggles itself with an action button that doesn't provide a visual indicator somewhere else on the screen (usually the player's sprite)

**Comment by AnturK** [comment]
Guns. And everything else that relies on overlays and possibly other more rare changes like name/color/transform

**Comment by RemieRichards** [comment]
What's that idiot even ranting about, We don't call it on ```Life()```, we update them dynamically as needed.
just like mob ```update_icons()```

Sure, this'll help, but it's no source of lag on our end, if Yog went lazy with it and stuck it in ```Life()```, who's really to blame?

**Comment by AnturK** [comment]
We do update it in Life Remie. Mostly because of legacy code from the previous item actions but still.

**Comment by RemieRichards** [comment]
couldnt find it, prove it.

**Comment by AnturK** [comment]
Well you're not wrong. Now i feel silly.

**Comment by RemieRichards** [comment]
this is still worthwhile, don't get me wrong, it'll probably save a few cycles here and there, and a bit less churn obviously, but it's certainly not god's gift to humanity slayer of the lag demon.

**Comment by AnturK** [comment]
Got MrPerson to discover appearance comparison issues so probably worth it 📯

**Comment by RemieRichards** [comment]
true.

**Comment by monster860** [comment]
I'm not insane

https://github.com/yogstation13/yogstation/blob/80d40a521ae890e851b707a30fae0dcc87c92773/code/game/atoms_movable.dm#L149

https://github.com/yogstation13/yogstation/blob/747ee99c3b404bd06f6a210d8f8d45c396357321/code/modules/mob/mob.dm#L684

https://github.com/yogstation13/yogstation/blob/f589a9ca72e7273ba8d85d7d115da0ad4de6ce75/code/_onclick/hud/action_button.dm#L67

https://github.com/yogstation13/yogstation/blob/f589a9ca72e7273ba8d85d7d115da0ad4de6ce75/code/datums/action.dm#L82

**Comment by AnturK** [comment]
You call forceMove every tick ?

**Comment by monster860** [comment]
This was causing massive amounts of lag on FTL13.... Large amounts of update_canmove being called.

**Comment by AnturK** [comment]
Ah i see what's going on, i'll need to separate the stat/restrained checks and actual icon updates since in this case the latter are not needed.

**Comment by AnturK** [comment]
@monster860 #22494
