### ISSUE TITLE
Map issue Delta Station

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#22509]
![image](https://cloud.githubusercontent.com/assets/609465/21505430/39afa508-cc5f-11e6-87cf-440d5b698f3b.png)

Server revision compiled on: 2016-12-27
1dff0b8457d6ebafe0e3e68e9a6442ba9476a9f2 

This intercom is on the floor for some reason. @Okand37

**Comment by Okand37** [comment]
I noticed I played a few items on accident around that area, but I thought I cleaned up most of it. I'll take a look at it later today!

**Comment by optimumtact** [comment]
Report on the map thread
