### ISSUE TITLE
Drone dispenser can delete some of its materials if retrieved

### ISSUE THREAD

**Issue by Mervill** [tgstation/tgstation#22506]
Insert 50 sheets of metal into the drone dispenser: `It has 100000 units of metal stored.` Insert another 50 sheets of metal into the drone dispenser: `It has 200000 units of metal stored.`

Use a crowbar on the drone dispenser to retrieve the materials (calls `material_container/retrieve_all()`). You now have 50 sheets of metal, `It has 0 units of metal stored.` 50 sheets of metal have been lost to the void.

Found while trying to fix #18155

**Comment by TehZombehz** [comment]
This is also a problem for exosuit fabricators and likely anything else that can contain larger than 50 sheets of a material.
