### ISSUE TITLE
Defribilators are not reviving people

### ISSUE THREAD

**Issue by Paesani** [tgstation/tgstation#22519]
I get a message saying that they were revived but they are still dead, I know its a bug because the guy died 10 seconds ago from oxiloss and it was not a suicide

**Comment by athompson11** [comment]
This one is a little hard to fix (if a bug) without the circumstances leading up to it. Why did he have oxyloss? Maybe he had chems that killed him immediately after he was defibbed?

**Comment by jughu** [comment]
Maybe he bad no heart :thinking:

**Comment by XDTM** [comment]
If the ghost is not in the body it doesnt work, but you can try again

**Comment by erwgd** [comment]
I've had something like this happen several times in the past.
1. dead guy comes in, usually dismembered but defib-able
2. defib guy
3. "rescusitation successful" - guy is still dead
4. defib guy again
5. "rescusitation successful" - guy lives
6. usually the guy outright stands up after the second defib.

I'm not sure, but I think this may be related to the healing effect of dismemberment; after losing a heavily damaged limb, only some of the limb's damage is kept with the character.

**Comment by jughu** [comment]
Tfw you play zombie and you lose your leg but you put it back in your socket but the limb has max damage and crits anyways

**Comment by BeeSting12** [comment]
I just had this issue. Defibbed three-four times, person was still dead and it said successful.

**Comment by Cyberboss** [comment]
Agree

**Comment by rainbowjose** [comment]
Agree
