### ISSUE TITLE
Security Bomb Suit on Delta Station has a buggy texture and equip icon.

### ISSUE THREAD

**Issue by Segalowitz** [tgstation/tgstation#22517]
When attempting to equip the Security Bomb Suit, I noticed that the icon seemed oddly garbled, as if the texture were wrong.  Putting it onto my character rendered them naked, with green text beside them saying UIT.  Attached is a picture.

![](https://i.gyazo.com/2bccf6a4577ed011e64369350cef6c6c.png)

**Comment by Okand37** [comment]
Oh woops, I meant to put in the regular bomb vest, as the security bomb vest sprite is.. well.. very old.
I'll make sure to replace the bomb closet with a regular one, cheers!

**Comment by Segalowitz** [comment]
No problem.

**Comment by optimumtact** [comment]
Report on the map thread
