### ISSUE TITLE
Spiders can wrap ghosts

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#22513]
This will also feed the spider, allowing it to lay eggs.
Only tested with player spiders.

**Comment by Armhulen** [comment]
oh GOD

**Comment by bgobandit** [comment]
FEATURE

**Comment by MimicFaux** [comment]
Feature

**Comment by Supermichael777** [comment]
holy fuck

**Comment by Supermichael777** [comment]
Could not reproduce, HOW DO?

**Comment by Hatfish** [comment]
It might've been a ghost orbiting something?  I have no fucking idea.
