### ISSUE TITLE
The syndicate shuttle is in the main map files

### ISSUE THREAD

**Issue by JJRcop** [tgstation/tgstation#22522]
For some reason the syndicate shuttle is in the main .dmm for the various maps we have available instead of being a shuttle template defined in  [_maps/shuttles](https://github.com/tgstation/tgstation/tree/e4053877ad6d29d80cf4a77f57db8359021d7080/_maps/shuttles). This means we have to modify every map if we want to touch the shuttle.

**Comment by Kromgar** [comment]
So thats why delta has a better syndie shuttle

**Comment by Mervill** [comment]
This is a relic from when ships had to be defined on the map they got used on, the whiteship(s) and emergency shuttle(s) are the same way.

Now that everything is fancy and dynamic, we can better separate these concerns.

**Comment by Okand37** [comment]
I've been meaning to go through and replace the shuttles with the syndicate shuttle reskin I made for delta, but haven't gotten around to it. This would make it a lot easier!

**Comment by coiax** [comment]
Yes, I've been meaning to make all shuttles load from templates. It's on my todo list.
