### ISSUE TITLE
Metastation is missing modular computers.

### ISSUE THREAD

**Issue by GunHog** [tgstation/tgstation#22523]
Metastation has no stationary modular computer consoles! After looking at the Box map, I found three of importance that I recommend adding to Metastation:

**Bridge:** `/obj/machinery/modular_computer
/console/preset/command`
* I recommend putting one in the HoP's office as a secondary ID console.

**Research Director's Office:** `/obj/machinery/modular_computer
/console/preset/research`

**Engineering:** `/obj/machinery/modular_computer
/console/preset/engineering`

Metastation is the second of the primary maps, behind Box! While not every map has to have everything another map does, modular computers deserve a little more attention!

**Comment by Mervill** [comment]
Maybe after this there will be a reason to not just immediately drop the tablet

**Comment by GunHog** [comment]
Try the ID program if you are a head. You will never drop it again.

**Comment by Mervill** [comment]
Hmm, do you have any suggestion as to _where_ precisely they should go? There's nothing in engineering, for example, that looks like it could be trivially replaced with the engineering console

**Comment by jughu** [comment]
Doesnt matter where its placed as the only programs are power based shit and ai maintance and a idd modifier

**Comment by jughu** [comment]
Basically useless

**Comment by Shadowlight213** [comment]
engineering one replaces the power monitor console in engineering.

**Comment by optimumtact** [comment]
Report on the map thread
