### ISSUE TITLE
Changelings can not regenerate lungs

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#22520]
Reviving stasis and regenerate, neither does it.

**Comment by Armhulen** [comment]
the new meta is to cut the chest of a dead changeling until it's organs spill out, which it cannot regenerate

**Comment by jughu** [comment]
That always been the meta of every murderboner :^)

**Comment by jughu** [comment]
Why do lings need to breathe anyways they are fucking shapeshifters

**Comment by Armhulen** [comment]
give changeling  warped alien organs that he can live without

ih and the organs come alive too

**Comment by XDTM** [comment]
I swear regenerate used to restore organs too.

**Comment by Armhulen** [comment]
tfw too intelligent to regenerate

**Comment by PKPenguin321** [comment]
Dupe

**Comment by lzimann** [comment]
Dupe of #21408
