### ISSUE TITLE
Explosive implants don't auto-explode on death

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#22546]
During a nuke op round, Cayenne died with multiple microbomb implants in them. It had to be activated manually. Later on after we won, two ops committed suicide and never blew up.

**Comment by Kromgar** [comment]
...

Carps dont make deathgasps

**Comment by KorPhaeron** [comment]
@AnturK 

Since implants?

or maybe

@ChangelingRain 

I saw you touching deathgasp

**Comment by ExcessiveUseOfCobblestone** [comment]
oh

**Comment by ChangelingRain** [comment]
Simple animals don't actually deathgasp, and, on top of that, deathgasp is broken right now(#22538)

**Comment by lzimann** [comment]
This got partially fixed with #22538, but simple animals, like Joan stated, never actually deathgasp so only manual triggers will work.
