### ISSUE TITLE
I managed to gib myself with a gibtonite... wearing a fully upgraded explorer suit

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#22540]
![image](https://cloud.githubusercontent.com/assets/6778786/21527132/f37bfe22-ccf6-11e6-8c87-cf75668ae1fb.png)

I was mining with plasma cutters and fucked up I was going too fast and blew a gibtonite standing right next to it somehow MY ENTIRE BODY GOT GIBBED.

MY EXPLORER SUIT WAS FULLY UPGRADED HOW

**Comment by ChangelingRain** [comment]
Pff. I guess you ran into the center of the explosion before it processed. Good job.

**Comment by GunHog** [comment]
Explorer suits have 50 bomb armor. That means a 50% chance of not being gibbed when caught in a devastation level explosion. You were unlucky. Bomb armor on the explorer suit **cannot be upgraded.** Goliath hide only increases your _melee_ defense, not your bomb defense.

**Comment by Kromgar** [comment]
Should upgrade bomb armor i unleashed 2 level 0 gibtonites on 3 goliaths and those fuckers did not die

**Comment by Mindustry** [comment]
lol
