### ISSUE TITLE
Deltastation: Duplicate windoors at the security checkpoint outside the big

### ISSUE THREAD

**Issue by Mervill** [tgstation/tgstation#22554]
http://imgur.com/a/UjcU2

**Comment by ExcessiveUseOfCobblestone** [comment]
double protection!

**Comment by Okand37** [comment]
The wonders of working on two maps at once, is when you change the direction on one object it likes to change it on the other! I fixed this earlier and it will be included in the next batch of updates!

**Comment by Mervill** [comment]
Instances in the editor are a huge bitch

**Comment by optimumtact** [comment]
REPORT ON THE THREAD REE
