### ISSUE TITLE
Proto-Kinetic Crusher no longer fits on the back

### ISSUE THREAD

**Issue by Leon9621** [tgstation/tgstation#22550]
Multiple times I've tried to store the crusher on my back and make do with the webbing you get, but all it does is fall to the ground.

**Comment by Mervill** [comment]
dosen't look like it was my recent refactor of `w_class`

**Comment by Mindustry** [comment]
Duplicate issue

**Comment by Mervill** [comment]
@Mindustry of what issue, please

**Comment by lzimann** [comment]
Dupe of #22536
