### ISSUE TITLE
halluncinations (BZ exposure?) causing repeated crashing

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#22565]
Some form of runtime perhaps, but I was having the same issue when dealing with a SM crystal and begun to hallucinate, and again recently when dealing with changelings/BZ hallucinations.

**Comment by Haevacht** [comment]
Ignore that refrence, wrong number.

**Comment by optimumtact** [comment]
@MimicFaux do you mean server crashing or client crashing?

If it's client crashing it's a byond issue and not a runtime

**Comment by Firecage** [comment]
optimum, mmm, most likely a Byond issue. My own client has come close to crashing several times due to either BZ or SM hallucinations. Aka window stopped responding.

**Comment by kriskog** [comment]
Haven't heard mention of this lately, assume fixed.
