### ISSUE TITLE
Security Transport Vessel 5 explodes

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#22568]
Something in one of the crates on the purchasable shuttle Security Transport Vessel 5 explodes once it docks with the station. Perhaps it's the crate itself, I'm not sure, but it consistently blows a giant hole in the shuttle every time the shuttle is used.
![tesajdfks](http://puu.sh/t52M9/630a54d7ef.png)
The hole can be seen in this image sort of near the bottom right.

**Comment by jughu** [comment]
Not a bug theres 2 abandoned crates which explodes when too many failed attemps or damage

**Comment by Mindustry** [comment]
What jughu said, the abandoned crates are more than likely the cause. Any damage to them and they explode, setting off the other one as well.

**Comment by coiax** [comment]
This is not a bug, it's just the abandoned crates being blown up by people trying to hack them.

I did not design most of my shuttles with the expectation that they'd be used frequently.

**Comment by Kromgar** [comment]
Well everyone orders this shuttle because MEMES LEL

**Comment by KorPhaeron** [comment]
People are using the abandoned crates to create unlogged explosions

**Comment by PKPenguin321** [comment]
Yeah that's a huge part of why I thought this was a bug, these explosions aren't even logged so until now I just thought the shuttle itself was exploding for no reason

**Comment by Bawhoppen** [comment]
people also commonly carry nades which are detonated when the crate explodes
