### ISSUE TITLE
Voice of god with the new colossus organ does not work with commands

### ISSUE THREAD

**Issue by Croneman12** [tgstation/tgstation#22569]
I've managed to kill and get the organ implanted, However when I issued commands to Stop, Burn, Fall and sleep. Etc, They did not work and I've tried using them in sentances and directing them at a single person and a variety of people, All commands did nothing besides make a loud noise and scare the jeebus out of some people.

**Comment by XDTM** [comment]
Odd, in testing it works fine. I'll try to find the issue.

**Comment by XDTM** [comment]
Can you remember how much cooldown did it give you?

**Comment by Croneman12** [comment]
I believe when I used it it was around 10-11 seconds or 9 but it was very short and I could use it before the Icon went out of the Grey

**Comment by ChangelingRain** [comment]
Does the regex properly account for capitalization? Because if it doesn't, then any capitals will keep it from  working properly.

**Comment by RemieRichards** [comment]
The way @XDTM has made the regexes means they are case sensitive.
this means that "Fuck" is not matched to "fuck", and thus all sentences where you START with a command word won't work, since we auto capitalise the first word, whenever a command word is the second word onwards it should work fine.

**Comment by XDTM** [comment]
Actually it parses the text before the actual speech so as long as you speak lowercase it'll be fine. Joan said he'd incorporate the fix in her own PR.
