### ISSUE TITLE
Seed vault lavaland ruin floors have fucked up iconstates

### ISSUE THREAD

**Issue by Haevacht** [tgstation/tgstation#22560]
Looks fine in editor.
Path is turf/open/plasteel/freezer.
Floor tiles can be removed, producing a standard tile. Replacing the tile does not fix it.

![](https://puu.sh/t4ATF/d3a44b7426.png)
Again round this screenshot is from is over.

**Comment by xxalpha** [comment]
This is what happens when you var edit icon states.

**Comment by Kromgar** [comment]
This is a known bug ruins will get this honk floor where a tunnel in the rock is supposed to be

**Comment by Mervill** [comment]
Seealso #17450

**Comment by KorPhaeron** [comment]
Dupe

**Comment by Mervill** [comment]
@KorPhaeron of what

**Comment by KorPhaeron** [comment]
From the issue you just linked and I'm sure several more
