### ISSUE TITLE
Perpetual energy engine

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#22575]
I uh... i cant even
![image](https://cloud.githubusercontent.com/assets/6778786/21557033/8eb3424e-cdf4-11e6-987d-936772bd4f97.png)

**Comment by PKPenguin321** [comment]
that's really really funny

**Comment by Kromgar** [comment]
Muh laws of physichs tho

**Comment by optimumtact** [comment]
Not a bug, unintended game interaction, file it on the feedback forum if it's really too strong
