### ISSUE TITLE
Potato wedges have no sprite, have an extra "the," and produce tator tots instead of fries in the processor

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#22584]
Reported by a player on sibyl

**Comment by Okand37** [comment]
https://github.com/tgstation/tgstation/pull/21678
https://github.com/tgstation/tgstation/pull/21591
Might be some good PR's to take a look at for anyone tackling this.

**Comment by WJohn** [comment]
Pretty astonishingly non-functional.

**Comment by Mervill** [comment]
> Potato wedges have no sprite

It does have a sprite ... it's just in `icons/obj/hydroponics/harvest.dmi`. Is the bug that `.../grown/potato/wedges` is missing `icon = 'icons/obj/hydroponics/harvest.dmi'`, or should the `potato_wedges` sprite (a plate of wedges) be moved to `icons/obj/food/food.dmi`?

> have an extra "the,"

Can't see any evidence for that

>  produce tator tots instead of fries in the processor

Can be fixed buy the suggestion in #21678

**Comment by bgobandit** [comment]
It's in messages, where "the the potato wedges" appears, the title was probably unclear
