### ISSUE TITLE
Drakes (Megafauna?) Aren't Gibbed by the Singu

### ISSUE THREAD

**Issue by ShadowDimentio** [tgstation/tgstation#22580]
Drakes for certain and probably all other megafauna by extension are immune to singu gibbing. This is dumb, the singu can devour an elder god but not a shitty fire dragon? Coders pls fix

**Comment by jughu** [comment]
This was intended so you cannot cheese the cheese

**Comment by ShadowDimentio** [comment]
If someone has the patience and skill to throw a megafauna into the singu and then nab the loot before it's devoured by the singu I say more power to them.

**Comment by jughu** [comment]
No its about the stats killing them think about kor's precious stats!

**Comment by ShadowDimentio** [comment]
Give the singu its own kill counter, what could go wrong

**Comment by Kromgar** [comment]
It's actually because drakes are given gib immunity thus making them immune to singulo

**Comment by PKPenguin321** [comment]
Is this still the case because it's fucking stupid and should be removed if so
