### ISSUE TITLE
Space overlaying everything on screen

### ISSUE THREAD

**Issue by Kombosabo** [tgstation/tgstation#22595]
Bug with space texture overlaying everything. (Maybe a transparency problem?)

What happens is, whenever I try to leave the station and go into space, the space overlays everything, and I can't seen anything but the space texture, it even gets on top of the hud.

This is also an issue when I wear Optical Meson Scanner and other items that allow for nightvision.

**Comment by Mindustry** [comment]
Have you tried updating byond?

**Comment by Kombosabo** [comment]
It fixed it. Thanks. (I'm using Beta now)
