### ISSUE TITLE
Swarmers can explode gas tanks inside lockers they deconstruct

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#22598]
probably ex_act mimes

**Comment by RandomMarine** [comment]
CAN WE STOP CALLING EX_ACT WITH STUFF THAT ISN'T FUCKING EXPLOSIONS

**Comment by PKPenguin321** [comment]
See https://github.com/tgstation/tgstation/issues/20002

**Comment by kriskog** [comment]
Cant reproduce
