### ISSUE TITLE
You can put things in a smuggler satchel hidden beneath the floor if you have a t-ray scanner

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#22601]
title

tested with a crowbar

**Comment by XDTM** [comment]
I think you can interact with anything underfloor if you have a t-ray scanner. Try snipping a wire.

**Comment by jughu** [comment]
The buff that the scanner needed

**Comment by Mervill** [comment]
I'm with jughu, even if this is a bug it's hardly a powercreep

**Comment by jughu** [comment]
I want to imagine your using the t ray scanner to figure where it lays and sneakily lift the floortike to put a object in without removing the tile

**Comment by jughu** [comment]
Real smugglin!

**Comment by Iatots** [comment]
Still, everyone else can see it if you use a scanner, not sure about the glasses though.

**Comment by Okand37** [comment]
Probably around the same reason you can hit a pipe if you can see it with a t-ray scanner.
