### ISSUE TITLE
Papier-Mch Robe spelt wrong

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#22609]
Papier-Mch Robe spelt wrong

**Comment by Mervill** [comment]
Duplicate of #22609

**Comment by lzimann** [comment]
It has a special character that acts weird in byond `name = "papier-mâché robe"`

**Comment by optimumtact** [comment]
People need to stop using non latin characters

**Comment by Mervill** [comment]
Préparez-vous à mourir infidèle!

**Comment by Mervill** [comment]
@optimumtact implying that the solution is to change this too `mache`? I swear I've seen non-latin characters in other places. Or is it that older clients can't render them?

**Comment by Jordie0608** [comment]
Yes that's really the best answer here.
