### ISSUE TITLE
Adamantine, Mithril smelting

### ISSUE THREAD

**Issue by Lostduty** [tgstation/tgstation#22604]
Tried to make some adamantine and mithril sheets using the old smelter.  Only to find that it is no longer possible, the machine is processing the ore before taking the required amounts to make a full sheet. Resulting in slag from a mix of one plasma, and one silver. Rather than taking the three plasma and one silver to make mithril. The same issue occurred when I tried to make adamantine taking a 1 - 1 ratio before taking the required amount to make the rare material.

**Comment by XDTM** [comment]
I don't think they're obtainable in /tg/.

**Comment by RandomMarine** [comment]
Wrong codebase. Mithril and adamantine sheets can't be obtained outside of admin activity. Even then they're mostly useless.

**Comment by jughu** [comment]
Lets readd mithril so i can make mithril tipped spears

**Comment by Lostduty** [comment]
You used to be able to smelt them using the smelter. I've only ever played on /tg/ although I haven't attempted to make mithril and adamantine since massive mining changes until recently. The ratio was 3 plasma, 1 silver for Mithril. 2 uranium, one diamond for adamantine.

**Comment by Iamgoofball** [comment]
When did you last play? As we had mith. and adamantine years ago.

**Comment by Lostduty** [comment]
I never stopped playing, I just moved away from mining. I only recently attempted to make the material for coins, and I wanted to see if there were cool secret golems using the two extremely rare and forgotten metals.

**Comment by jughu** [comment]
![screenshot_2016-12-31-02-56-42](https://cloud.githubusercontent.com/assets/14280283/21575189/0829e7d4-cf05-11e6-8e2c-6ac0c82c9e63.png)

**Comment by jughu** [comment]
Its not really in the code its just a comment currently so you cant make them not a bug

**Comment by jughu** [comment]
Maybe in 2017 he will finish it... haha...

**Comment by lzimann** [comment]
These minerals cannot be obtained, so not really a bug here.
