### ISSUE TITLE
AI turrets on the lethal setting do not seem to target lying humans

### ISSUE THREAD

**Issue by GunHog** [tgstation/tgstation#22606]
I witnessed a round in which the AI stunned the CE with its turrets, then flipped them to lethal to finish him. The turrets did not fire lasers while he lying down, only when he stood back up.

AI turrets, on the lethal mode, are supposed to fire until the target is dead, regardless of lying or standing. Basically, the turrets are still acting as if they are on the stun mode.

I have not taken the time to examine the code or figure out who broke AI turrets.

**Comment by YakumoChen** [comment]
It was caused by #22052 
@AnturK

**Comment by AnturK** [comment]
Oh, forgot to switch two checks out when i separated lethal and emagging.
