### ISSUE TITLE
Delta: Aux Base Construction front doors require ALL accesses, Science, Construction, Mining.

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#22607]
It requires ALL the accesses.

**Comment by WJohn** [comment]
Okand must have accidentally set the accesses on req_one_access, which is an AND, instead of req_access, which is an OR.

**Comment by ChangelingRain** [comment]
wj that's backwards, req_one_access is OR, req_access is AND

**Comment by Okand37** [comment]
It was accidently set to req_access opposed to req_once_access, the same issue cargo and engineering suffered from. It is fixed and is currently included in the next batch of updates, whenever that gets merged.

**Comment by optimumtact** [comment]
REPORT ON THE MAP THREAD
