### ISSUE TITLE
Instant summon spell lets you use marked items as any type of mob.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#22616]
Mark an item and change/get changed into a different mob like an alien hunter or an ash drake, summon the item and bam, you can use that item.

**Comment by lzimann** [comment]
Should probably drop the item on the floor if the mob doesn't have hands.

**Comment by PKPenguin321** [comment]
High priority

**Comment by Mindustry** [comment]
It also allows you to hold two handed things in one hand, but I'm not sure if #22457 fixed that

**Comment by Incoming5643** [comment]
This is wonderful

**Comment by PKPenguin321** [comment]
Reopened why? Was this not actually fixed by those two PRs?

**Comment by kriskog** [comment]
Can't reproduce, should be fixed.
