### ISSUE TITLE
Sentient EDs can smash down doors

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#22612]
also apparently you can just turn them off which disables them like lockdown, even though sentient bots usually can ignore that

**Comment by GunHog** [comment]
I believe that ED-209 being able to smash things is intended; Making them player controlled is a wizard power, and NPC ones are meant to smash things in order to reach their arrest target. pAIs cannot be put in security bots, so it is okay for them to be strong.

**Comment by Shadowlight213** [comment]
Turning off any player controlled bot locks them down.

**Comment by YakumoChen** [comment]
I have never seen an NPC ED smash walls or windows to get to a target, usually they wait outside the window like beepsky does.

**Comment by optimumtact** [comment]
This is intended for ones with a client mob only, not a bug
