### ISSUE TITLE
Temperature guns ignore most kinds of shielding. So do bolas and banana cream pies

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#22624]
Title.

**Comment by Kromgar** [comment]
RIP hardsuiterinos.


Temp gun now most op weapon in the game what have we come to?

It was added to sec as a memeeeee

**Comment by ShadowDeath6** [comment]
Where's that tempgun issue when you need it?

**Comment by Mervill** [comment]
I was just reading that the other day, actually

**Comment by KorPhaeron** [comment]
Dupe
