### ISSUE TITLE
You can buy raw TC and then redeem them infinitely, which is still logged for end round

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#22628]
![tc](http://puu.sh/t7jEm/3415b7e678.png)
This is why we can't have nice things

**Comment by Shadowlight213** [comment]
@uraniummeltdown

**Comment by Kromgar** [comment]
You can refund shit?

**Comment by jughu** [comment]
Its RAW tc which yoi can basically put in any traitor PDA for more TC

**Comment by Incoming5643** [comment]
you can also refund some items, a mechanic that was advertised so poorly no one even knows its a thing.

**Comment by Mervill** [comment]
@Incoming5643 Half of the mechanics I know of I only discovered as a result of reading issues and debugging the code

Smugglers satchels, Draggable Action Buttons, Inventory in the Detective's Hat, all kinds of stuff

**Comment by Shadowlight213** [comment]
The only refundable items are the syndieborg and additional op spawner nuke op items, since if there aren't any ghosts available, those items are worthless

**Comment by Shadowlight213** [comment]
oops

**Comment by uraniummeltdown** [comment]
I'll try and fix it in the morning

**Comment by coiax** [comment]
I mean, the solution here is just to put a x300 next to the image of the telecrystal.

**Comment by jughu** [comment]
the solution is here making tele crystals not show up i mean they gonna buy items of it anyways

**Comment by PKPenguin321** [comment]
Maybe make refunded items not appear in the list

**Comment by uraniummeltdown** [comment]
The telecrystals aren't refunded through the refund mechanic, they just get deleted and added to the uplink they were used on. 

I made it so that using raw TC causes `spent_telecrystals -= 1`, however I'm not sure how to not make it appear in the list, I tried `I.hidden_uplink.purchase_log -= "<big>\icon[src]</big>"` but that just causes runtimes because of type mismatch or something

**Comment by PKPenguin321** [comment]
Not fixed for other refundables, such as syndieborg

**Comment by Mervill** [comment]
See my earlier comment about that being a slightly harder fix. Telecrystals are suppressed completely, while we would ideally want syndieborg to appear in the list if bought

**Comment by PKPenguin321** [comment]
Regardless of difficulty in fixing, it is still an issue
