### ISSUE TITLE
all mobs at necropolis bridge have no delay between shots

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#22629]
all mobs at necropolis bridge have no delay between shots

**Comment by Kromgar** [comment]
Uh... like on the bridge to necropolis mobs have no delay whatsoever?

**Comment by golfer45** [comment]
not he salvage workers at necropolis bridge.

**Comment by KorPhaeron** [comment]
Salvage workers?

**Comment by golfer45** [comment]
Yep, the elite workers fire like 10 shotgun shots in a second aswell as firing smg rounds.

**Comment by KorPhaeron** [comment]
Uh, are these on lavaland?

**Comment by Okand37** [comment]
The salvage workers are supposed to be in the syndicate salvage/caravan ruin thingymabobber, aren't they? I don't think they appear on lavaland naturally.

**Comment by KorPhaeron** [comment]
Well Xhuis used a generic area/ruin thing for the bridge, so it often renames space ruins to Necropolis Bridge.

That might be the source of confusion

**Comment by Xhuis** [comment]
Goddamn areas. What the hell kind of drugs are they on? I'll patch that out.
