### ISSUE TITLE
Stations missing modular computer presets

### ISSUE THREAD

**Issue by Mervill** [tgstation/tgstation#22637]
```
- [ ] Missing
- [x] Present
```

Bird (are we still supporting this?)
- [ ] Bridge
- [ ] Engineering
- [ ] Research Director

Delta
- [x] Bridge ~~(Wrong! #22636)~~
- [ ] Engineering
- [x] ~~Research Director~~

Meta
- [ ] Bridge
- [ ] Engineering
- [ ] Research Director

Pubby
- [x] Bridge
- [ ] Engineering
- [x] Research Director

TG
- [x] Bridge
- [x] Engineering
- [x] Research Director

Closes #22523 as a duplicate

**Comment by Okand37** [comment]
Delta Station's modular computer set up is intended.

**Comment by Mervill** [comment]
What about the Engineering computer?

**Comment by Penguaro** [comment]
@Mervill 
Updates to the list above
Meta has command and RD
Omega (not listed) has none
