### ISSUE TITLE
Warden's cycler shotgun holds to much ammo on tube B

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#22638]
This is only roundstart where tube A holds 4 and tube B holds 5 and theres supposed to be 4 in each tube the real problem here is Tube A fires perfectly no problem but Tube B shoots 1x and then says you have no ammo left you check the cycler shotgun it says it has 4 ammo left if you switch tube a then back to b it can fire perfectly again

**Comment by Mervill** [comment]
You just have to click the gun again to pump the next round in the 'new' tube into the chamber

This actually isn't a bug now that I think about it. This behavior allows you to do clever things like have one tube with lethal and one tube with nonlethal and also not get them mixed up accidentally.

**Comment by jughu** [comment]
Yeah but having TUBE b to clog up forcing you to switch to a and back to b kinda sucks

**Comment by jughu** [comment]
![image](https://cloud.githubusercontent.com/assets/14280283/21589420/da5c5f96-d0f1-11e6-9b06-6a549bea362b.png)

**Comment by Mervill** [comment]
did you pump the gun (click it once) after switching? It should `pump()` before it lets you switch. There should be a sound, probably

**Comment by jughu** [comment]
i cant pump it altough because if i click it it just switches tubes

**Comment by jughu** [comment]
its also a automatic combat shotgun

**Comment by Mervill** [comment]
Is the point of this weapon to basically have a extended-mag gimmic (click it to switch tubes) or is it indented to be used cleverly ie: placing different ammo types in each tube. The answer to that question determines this.

**Comment by jughu** [comment]
to have different ammo in each tube both tubes should hold 4 ammo

**Comment by Mervill** [comment]
It already does, the usage is just weird/bad

- Create a cycler shotgun
- Examine: 4 rounds remaining
- Pick it up
- Attempt to fire: `*click* *click* *click*` (it hasn't been pumped!)
- Click the cycler shotgun ONCE, notice that you don't get the message about switching tubes
- Examine: 4 rounds renaming / live one in the chamber
- Click the cycler  shotgun again to switch to tube B
- Examine: 5 rounds  renaming / live one in the chamber
- Fire 5 rounds (the one in the chamber plus the 4 in tube B
- Click the shotgun again to switch to tube A
- Examine: 3 rounds remaining
- Attempt to fire: `*click* *click* *click*`
- Click the cycler shotgun ONCE, notice that you don't get the message about switching tubes
- Examine: 3 rounds remaining / live one in the chamber
- Fire 3 rounds
- You have no more ammo
- 5 + 3 = 8

**Comment by Mervill** [comment]
@optimumtact this is a crappy gun, but it is working as intended
