### ISSUE TITLE
A* (astar) problems with windoors

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#22631]
If a bot manages to astar path behind a windoor (meaning they're both on the same tile but the windoor is still "in the way" of the bot's path) then the bot will become confused and start endlessly recalculating astar, never figuring out that it has to bump the door to continue. With enough bots this constant astar cost can start to pile up and cause lag

The only place this naturally seems to happen is in the robotics delivery windoor door on metastation as occasionally bots patrolling the halls will see a [mess/hurt person/criminal/breach] inside robotics as they pass it. From that position the shortest route is to scoot into maintenance to the south and attempt to use the delivery windoor as all bots have robotic access. They get stuck behind the windoor that they have access to.

Strangely once they enter this state it can be very hard to get them to "snap out of it", even moving the bots doesn't seem to update the astar calculations and they'll just park in place as they figure out how the hell to get past that windoor.

**Comment by Incoming5643** [comment]
Once it's stuck it's stuck, even opening the door won't help at that point.

**Comment by XDTM** [comment]
usually a cleanbot or a medibot get stuck on the meta rnd maint windoor, but usually opening it frees them

**Comment by Cyberboss** [comment]
Should we just avoid pathing through windoors then?

**Comment by MrStonedOne** [comment]
ya... might be best to have them return false on canastarpass

**Comment by MrStonedOne** [comment]
or make bots learn how to use them

**Comment by Iamgoofball** [comment]
Or make them full-time instead border objects

**Comment by PraiseRatvar** [comment]
@Iamgoofball does your goap bolognese fix this since i think i seen you mess with a*

**Comment by Iamgoofball** [comment]
that's a negative

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/tgstation/blob/e8b963a004a0714212f765e3a8bcf54fb8911ff1/code/game/machinery/doors/windowdoor.dm#L116

So, astar does attempt to check windoors.

**Comment by MrStonedOne** [comment]
ya, so its just that the bots don't understand how to use windows, that seems like a better fix.

**Comment by MrStonedOne** [comment]
Oh, wait, I see it.
