### ISSUE TITLE
Antimatter engine doesn't seem to be usable

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#22653]
I bought an antimatter engine and set it up properly, but I couldn't seem to get the interface on the control unit working when I clicked on it.

**Comment by optimumtact** [comment]
This is not a bug yet unless you can prove it doesn't actually work even when setup properly

**Comment by Cheridan** [comment]
#20744

>I'm going to work on making the UI be in a later PR.

He never did it.
It doesn't freaking work.

**Comment by Shadowlight213** [comment]
It does work. It has a ui. I meant making a tgui.
It just requires power to run.
Most of the issues I've seen people have with it resulted from them building it in an unpowered room.

**Comment by Robustin** [comment]
Worst engine I've ever seen but it works, RIP this issue

**Comment by PKPenguin321** [comment]
Yeah, not a bug
