### ISSUE TITLE
non-latin characters clearly render fine, but can't be used in descriptions? 

### ISSUE THREAD

**Issue by Mervill** [tgstation/tgstation#22651]
Here is an item with non-latin characters (`é`)

```DM
/obj/item/clothing/head/canada
	name = "striped red tophat"
	desc = " It feels sticky, like maple syrup - <i>il se sent collante, comme le sirop d'érable</i>"
	icon_state = "canada"
	item_state = "canada"
```

Here it is when examined
```
That's a striped red tophat.
It feels sticky, like maple syrup - il se sent collante, comme le sirop d'Ã©rable
It is a normal-sized item.
Justin Trudeau exclaims, "Préparez-vous à mourir infidèle!"
```

So what do we have to do to make non-latin characters appear properly in descriptions?

Related #22609

**Comment by PKPenguin321** [comment]
we stop using non-latin characters

**Comment by Mervill** [comment]
Cette suggestion offense mon patrimoine canadien, comment osez-vous!

**Comment by Jordie0608** [comment]
I think it's trying to communicate

**Comment by Mervill** [comment]
Les chaînes Dream Maker acceptent-elles les codes d'échappement? Pouvons-nous les configurer pour qu'ils soient pilotés par les données? Qu'en est-il des putains de Russes?

**Comment by Mervill** [comment]
あなたはロボットの戦いをしたいですか？

**Comment by optimumtact** [comment]
I already told you
