### ISSUE TITLE
(delta) secure tech storage airlock is all access

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#22661]
See title.

**Comment by KingPhilipIII** [comment]
I was actually just about to open this issue.

**Comment by KorPhaeron** [comment]
@Okand37

**Comment by Okand37** [comment]
I'll take a look at this later today. The tech storage airlock leading in has no requirement, or the secure door holding the secure boards has no requirement?

**Comment by BeeSting12** [comment]
@Okand37 The secure door holding the secure boards has no requirement. The door leading in to the main tech storage room is okay.

**Comment by optimumtact** [comment]
Please report on the map thread for that map,
