### ISSUE TITLE
Parcels.

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#22663]
That's a small parcel.
A small wrapped package.
It is a huge item.

**Comment by Mervill** [comment]
Notices ur parcel

**Comment by Mervill** [comment]
This isn't simply a case of a misassigned `w_class`, `/obj/item/stack/packageWrap/afterattack()` should be refactored to properly inherit the size of the object being wrapped ([code](https://github.com/tgstation/tgstation/blob/a9be4e68d08697aad2bab6c2dbad955e733fadc6/code/game/objects/items/stacks/wrap.dm#L49))

**Comment by bgobandit** [comment]
it's a grower not a shower

**Comment by Mervill** [comment]
Relevant recent pr #22648
