### ISSUE TITLE
Being soul sharded does not trigger explosive implant

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#22673]
Was a nuke op on Basil, was knocked into crit and then instantly soul sharded before I could whisper to trigger my explosive implant. All of my belongings were then available to be looted.

Is this a bug or a feature?

Server revision compiled on: 2017-01-02
93bd91fcaaff0e080e8a293d366d1395a966cd5f

**Comment by KorPhaeron** [comment]
Feature

**Comment by jughu** [comment]
_chaplain gone op when he got smoke anyways_
