### ISSUE TITLE
(delta) lawyers can access sec gear room

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#22670]
this also means they can enter the armory if the shutters are open.

**Comment by Mervill** [comment]
![](http://i1.kym-cdn.com/entries/icons/original/000/004/590/OBJECTION!.jpg)

This is a feature /s

**Comment by KorPhaeron** [comment]
@Okand37

**Comment by improvedname** [comment]
@Mervill objection overruled

**Comment by Jordie0608** [comment]
@improvedname you mean
![overruled](http://vignette1.wikia.nocookie.net/aceattorney/images/a/af/ZamvJ.png/revision/latest?cb=20140726143516)

**Comment by Okand37** [comment]
I'll make sure to take a look at this later today! Chances are the gear room is just set to regular brig access, is all.

**Comment by optimumtact** [comment]
Please don't report map issues on the tracker, use the map thread.

**Comment by optimumtact** [comment]
Unless it's box that is

**Comment by KorPhaeron** [comment]
The map that nobody plays?
