### ISSUE TITLE
Holodeck spawns being sold for infinite cargo credits.

### ISSUE THREAD

**Issue by Saegrimr** [tgstation/tgstation#22692]
![I sell fuel tank and fuel tank accessories](http://i.imgur.com/cnGJ5PA.png)

1. Remove holodeck safety
2. Spawn fuel tanks
3. Sell fuel tanks
4. Reload holodeck

BONUS EFFICIENCY ROUND

- Get the captain to give you a hand tele/steal the spare out of the teleporter room.
- Put teleport beacon on the supply shuttle
- Shove fuel tanks into hand tele portal while rapidly respawning them in the holodeck

**Comment by GunHog** [comment]
Paper engines, _corgi_ engines ,megafauna containment devices, megafauna termination chambers, self-regenerating fight pits...

We really have some creative players out there!

**Comment by Cyberboss** [comment]
Needs an emagged holodeck, feature

**Comment by Saegrimr** [comment]
Incorrect, any silicon can remove the safeties.

**Comment by Tacolizard** [comment]
@Saegrimr i'd argue removing safeties as an asimov silicon should be at least warnable, because it will almost certainly cause human harm.

**Comment by Cebasiz** [comment]
turning off the safeties does not cause human harm in the same way that turning the emitters off doesn't

stop making bullshit law addendums

this is not a fucking sillicon problem it is a PROBLEM WITH THE FACT THAT GENERATING THE HOLODECK DOES NOT REQUIRE POWER AND/OR YOU CAN SELL IMMATERIAL INFINITELY REPRODUCIBLE SHIT

REEEEEE

**Comment by peoplearestrange** [comment]
I still don't get why turning off holodeck safeties allows you to take things OUTSIDE of the holoprojected area...

**Comment by Cebasiz** [comment]
i mean all you have to do is drain power from the holodeck APC for every thing the holodeck is manifesting

at least that way if you're doing enough of these things you'll eventually need a singulo to power the holodeck which would be pretty cool

**Comment by Bawhoppen** [comment]
tbh we need to add being able to telesci stuff out of the holodeck to make it real like that star trek episode

**Comment by ma44** [comment]
Besides that dragging 18 tanks from holodeck to cargo back and forth, without anyone interrupting you or any greytider taking your shit/shitcurity questioning you, or someone not blowing up all the tanks. You will also need to make sure no one enters the holodeck and changes the setting while loading said 18 tanks into cargo shuttle.

**Comment by callanrocks** [comment]
@Bawhoppen we need a Moriarty antag that can spawn when the safties are off.

**Comment by Bawhoppen** [comment]
give detective some classic holmes gear so we can play out the entire episode

**Comment by Tacolizard** [comment]
@ma44 yeah, the practical limitations are enough here.

**Comment by Saegrimr** [comment]
@ma44 
@Tacolizard 
Except in the screenshot provided this is exactly what is happening. The first time around they ran them manually, and it was slow. Round 2 they grabbed the hand tele and just zipped them all onto the shuttle in about 30 seconds.

**Comment by Arianya** [comment]
I may be wrong, but doesn't even safeties disabled holodeck have a range limit? I seem to recall trying to take the medieval weapons out of the recroom and them eventually fading away.

May just be an issue with the holodeck's fading away on fueltanks, if so.

**Comment by Cyberboss** [comment]
Emagged holodeck items are 100% real, not even a special var flagging them as holo

**Comment by PKPenguin321** [comment]
If the holodeck is emagged then objects taken out of it fade away when the holodeck changes setting instead of when they're taken out of it

**Comment by alexkar598** [comment]
Is the issue still open id yes i suggest adding a var to objects : holospawned witch if active prevents the object from being sold at cargo or prevents the shuttle from departing as dose an living entity do

**Comment by alexkar598** [comment]
I will try to find a way to assign a z-level to holo objects deleting should be easy its just finding a way to do a check for the z-level without lagging the server each time the holodeck is activated

**Comment by SweaterKittens** [comment]
What check does the nuke disk use? I realize that's one object compared to what could be many many many objects, but it might be a jumping-off point, since that's the other object I know we have that has interactions as it leaves the z-level.

**Comment by alexkar598** [comment]
The nuke disk uses process() which is called every tick it works well for the nuke disk as we only have one nuke disk but having all objects on the holodeck being tracked a couple time each second may cause some unwanted lag when a emaged holodeck with multiple items is activated so i will try on private server and see if it work and/or lags

**Comment by SweaterKittens** [comment]
Shoot, I thought it might be something like that. Yeah that could be rough if it's doing it for EVERY holographic object. And would make it hard to transplant that var to other objects in the future.

**Comment by alexkar598** [comment]
The best is to implant a var when the things are copied and checking for that var in the cargo selling code
