### ISSUE TITLE
Floortile Placing Bug

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#22701]
Standing on a tile with a floor tile (item) on it and placing a floortile on a plating next to you will make the tile beneath you disappear.
How to reproduce:
1. Crowbar up two floortiles.
2. Stand above one of the areas you crowbarred up.
3. Pick up the other floortile and place it where it was.
Both floortiles should be gone- One placed and the other disappeared.

**Comment by PKPenguin321** [comment]
I believe when you pick up an item it's moved to your tile for a fraction of a moment, and when two stackable materials like floor tiles are on the same tile, they automatically stack together, meaning both tiles would then be stacked in a stack of 2 in your hand.

**Comment by BeeSting12** [comment]
That may be the case, but it deletes the tile that should be placed in the stack.

**Comment by lzimann** [comment]
Some items can be hidden on the plating after you use the floortile. Are you sure it's not the case?

**Comment by BeeSting12** [comment]
Pretty sure, I'll check just in case but I don't think it was hidden.

**Comment by XDTM** [comment]
@AnturK doesn't seem to happen, i couldn't reproduce it with the same conditions
