### ISSUE TITLE
blob is in rotation

### ISSUE THREAD

**Issue by kilkun** [tgstation/tgstation#22705]
[Note]: # this is the worst fucking gamemode holy shit, even bay's meme mode is better

**Comment by PKPenguin321** [comment]
good joke

**Comment by Armhulen** [comment]
*laughs in overmind*

**Comment by kilkun** [comment]
as ironic as this is, there is the underlying truth that blob is the least enjoyable gamemode

**Comment by dannno** [comment]
yeah it's just poorly balanced
