### ISSUE TITLE
Prison really easy to escape

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#22711]
Now that machines and such are more desctructable, you can take a potted plant or any high damage object and bash machines (windoors are especially good as they have all the materials you need) until you get glass shards, rods, and cable coil. For spears.

From there you just throw spears at the doors till you can escape.

**Comment by Mindustry** [comment]
How is this a bug?

**Comment by kilkun** [comment]
feature

**Comment by YakumoChen** [comment]
perma is supposed to be hard to escape without preparation or outside help, hence the name. If you can escape it just by bashing the door, it isn't really very effective.

**Comment by Supermichael777** [comment]
Wjohnson has a lot to answer for.

**Comment by Cebasiz** [comment]
i think making airlocks bashable was a huge mistake

t. sillicon that earnestly tries to prevent murderboners

**Comment by improvedname** [comment]
Just make bolted doors require a high brute forcer then unbolted

**Comment by optimumtact** [comment]
This isn't a bug in that it's intended features working as expected, but it is a balance concern so you should make a forum thread and report to mappers.
