### ISSUE TITLE
Pipes under walls don't explode

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#22722]
![untitled](https://cloud.githubusercontent.com/assets/8171642/21634116/b16e4914-d222-11e6-9e93-6bd21a1892ad.png)

**Comment by AnturK** [comment]
Fairly sure this is dupe but can't find the old issue

**Comment by optimumtact** [comment]
This is *intended* in that it was a pain to fix pipes that exploded when the wall didn't, so they were excluded from exact

**Comment by ChangelingRain** [comment]
This isn't supposed to save pipes if the turf got destroyed, though.
