### ISSUE TITLE
There is no restore organs function

### ISSUE THREAD

**Issue by CPTANT** [tgstation/tgstation#22734]
Turns out issue #21408 is way more general than originally thought. There is NO restore organs function anywhere in the code. This means no type of healing restores organs and the only way to regain organs is through surgery.

This means organs are not restored for:

Changelings using stasis or regenerate. 
healing staffs.
probably admin heals as well?
Anything else you would expect to heal organs.

**Comment by KingPhilipIII** [comment]
Admin heals restore organs I think.

**Comment by Mindustry** [comment]
@KingPhilipIII is right
![ss 2017-01-04 at 01 01 49](https://cloud.githubusercontent.com/assets/8491500/21659156/5bd53eb6-d27e-11e6-8eaa-2847fae88b26.png)

but it should be an easy fix to apply to other things, ill probably attempt it when i get home tonight

**Comment by CPTANT** [comment]
Man, who codes things like that and doesn't just make it a function like regenerate limbs is.
