### ISSUE TITLE
[CTF] You can drag a person holding a flag to bypass the flag slowdown

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#22739]
1) grab the flag.
2) your teammate drags you, much faster, back to base.
3) PROFIT!!

**Comment by TehZombehz** [comment]
The value of teamwork.

**Comment by calzilla1** [comment]
Feature

**Comment by bgobandit** [comment]
emergent gameplay

**Comment by ma44** [comment]
Is the flag suppose to weigh a lot, or does it just slows down t he holder by MEGIC?

**Comment by coiax** [comment]
I don't know, it's a game, maybe it's heavy or something

**Comment by Cebasiz** [comment]
moving above a certain speed is very unsporting so spessmen refuse to do it

unless they are pulling in which case they can pass it off to someone else's guilty conscience
