### ISSUE TITLE
[New Centcom] There is a "Captain" start location in the Admin office and you will sometimes start there

### ISSUE THREAD

**Issue by Mervill** [tgstation/tgstation#22758]
I've spawned in the Centcom office at round start at least twice as the Captain.

**Comment by Kromgar** [comment]
HAHAHHA

**Comment by bgobandit** [comment]
captain's safest there

**Comment by XDTM** [comment]
Captain can run gimmicks better with the full power of centcomm, while safe from greytide.

**Comment by Tacolizard** [comment]
kek, imo this might be interesting if there's a really low chance of spawning there.

**Comment by Kromgar** [comment]
Feature

**Comment by Mervill** [comment]
The unfortunate thing is that the centcom doors are all special access so unless you talk to an admin you'll be stuck in the admin office

**Comment by Armhulen** [comment]
centcom administration new ghost role: because you'll be surprised on how long people will fuck around doing nothing
