### ISSUE TITLE
R&D - Mass Spectrometers no longer accepted by destructive analyser

### ISSUE THREAD

**Issue by fagotron9001** [tgstation/tgstation#22753]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))
See the title
[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by Mindustry** [comment]
See #22743

**Comment by optimumtact** [comment]
Dupe

**Comment by optimumtact** [comment]
of #22738
