### ISSUE TITLE
Delta Station: A few misplaced or unconnected atmos pipes

### ISSUE THREAD

**Issue by Mitchrock** [tgstation/tgstation#22763]
There's a few locations I've noticed crawling through the vents around Delta that have either unconnected or misplaced pipes. Pictured is one of them, located in the hallway near the kitchen/bar area. I'll try and upload more places as I find them.
![untitled](https://cloud.githubusercontent.com/assets/1880163/21672962/bd87ca3c-d2da-11e6-9d4a-a6c2d08602cb.png)

**Comment by optimumtact** [comment]
REport on map thread
