### ISSUE TITLE
Pubby Station: Random books aren't spawning

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#22768]
Fails a if(!establish_db_connection()) pass i.e. spawns this:

There once was a book from Nantucket
But the database failed us, so f*$! it.
I tried to be good to you
Now this is an I.O.U
If you're feeling entitled, well, stuff it!

**Comment by optimumtact** [comment]
REport on map thread

**Comment by PKPenguin321** [comment]
REEEEEEEEEEEEEport

**Comment by optimumtact** [comment]
WRONG
