### ISSUE TITLE
Voice of God commands affect who is in possession of the person's ID, not the person themself

### ISSUE THREAD

**Issue by MrAlphonzo** [tgstation/tgstation#22776]
Someone used a voice of god command to burn an assistant, but the HoS had their ID, which resulted in the HoS being set on fire. The ID was not equipped in his ID slot, and it may have something to do with the person being targeted being unknown due to all of the damage to their body.

**Comment by XDTM** [comment]
VoG should check for true_name, are you sure you didn't get bamboozled by a disguised assistant?

**Comment by XDTM** [comment]
Scratch that. If it doesn't recognize a name it should hit everyone; was the name used at the start or the middle of the command? It only accepts it at the start.

**Comment by XDTM** [comment]
Another thing that could've caused it is the target's name being right, but since the target was dead it was not in the listener list in the first place, which caused the command to go global.

**Comment by XDTM** [comment]
Couldn't find the BURN or IGNITE command preceded by a name in any of the last three days' logs. Maybe the command was wrong?
Also i totally need to add logging to VoG.

**Comment by XDTM** [comment]
Could neither reproduce nor find any log of this happening. Any mention of BURN or IGNITE said in the previous 4 days of the issue were not preceded by any name.

**Comment by MrAlphonzo** [comment]
Maybe I was on some BZ.

**Comment by SweaterKittens** [comment]
I was adminning when this happened, and I watched him say "*assistant's name* BURN" and the HoS burst into flames. I wish I remembered the day so I could dredge it up for you, but it was definitely the HoS and not someone in disguise. If you can't reproduce it then maybe there was something else going on that me and @MrAlphonzo did not remember correctly.

**Comment by XDTM** [comment]
I added logging to VoG, so if it happens again i'll be able to see the circumstances. Still, if the assistant that was named was dead, naming him would have had no effect as he wouldn't have been on the target list in the first place, and the command would have gone global affecting the HoS.

**Comment by SweaterKittens** [comment]
Oh I completely missed your comment saying that it would've gone global. Got it! Thanks for adding logging as well.
