### ISSUE TITLE
Dead bodies can hallucinate from the supermatter

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#22777]
Tried fixing the supermatter.. got killed and my body continued to hallucinate whilst dead

**Comment by Mervill** [comment]
A E S T H E T I C

**Comment by Tacolizard** [comment]
feature

**Comment by XDTM** [comment]
From what i could see from code, you won't get new hallucinations, but you'll see the ones that already started before death. Is that the case or it was actually generating new hallucinations?

**Comment by Kromgar** [comment]
@xdtm new ones would appear

**Comment by phil235** [comment]
>new ones would appear

The new hallucinations are actually produced by the handle_hallucination() proc that was started while alive. It create a series of hallucinations as long as the hallucination var is above a certain value.

Need a `if(stat == DEAD) break` in the while loop here: https://github.com/tgstation/tgstation/blob/9feab253b8c4c47283fe16bbd1df11b9d8c0ddb5/code/modules/flufftext/Hallucination.dm#L38

**Comment by Kromgar** [comment]
@phil235 holy shit your alive

**Comment by RemieRichards** [comment]
he's not, it's a lingering ghost.
