### ISSUE TITLE
NaN temperature

### ISSUE THREAD

**Issue by monster860** [tgstation/tgstation#22782]
Somehow, the temperature of reagents can become NaN, which completely fucks you up if you are a chemist and causes tgui to error when you try to heat it. 

Note, this was not observed on base /tg/ but on FTL13 (https://github.com/FTL13/FTL13) which branched off of /tg/ on 1st July 2016, but does not have any changes related to chemistry. The server was running on linux and this has happened several times. However, a search for nan temperature on this repository yields no results.

**Comment by lzimann** [comment]
Was the temperature displayed as NaN in a TGUI window? If I'm not mistaken, TGUI will show "NaN" when there's a bad arg.

**Comment by monster860** [comment]
No, the tgui was giving a javascript error on the heater because of the NaN.

**Comment by monster860** [comment]
There was ahelps about chemistry not working so when I VV'ed the reagents datum it showed the temperature was NaN in VV. I'm pretty sure that VV shows the variable exactly as it is.

**Comment by francinum** [comment]
Any more information on possible reproduction of the issue?

**Comment by SpaceManiac** [comment]
Closing as old + unreproduced + not even produced on /tg/ in the first place
