### ISSUE TITLE
Stealth/invisimin is revealled by the ping in the who tab.

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#22786]
If an admin is stealth/invisimin'd, they show up on the who list without their ping being visible. This allows you to sniff out admins in stealth/invisimin stupidly easily.

**Comment by PKPenguin321** [comment]
screeee @MrStonedOne

**Comment by Bawhoppen** [comment]
i have excellent deduction skills i can fish them out anyways dont worry

**Comment by Armhulen** [comment]
invismins are scary :cry:
