### ISSUE TITLE
Vending Machines and Doors no longer make tool noise when you use a screwdriver on them

### ISSUE THREAD

**Issue by Mervill** [tgstation/tgstation#22790]
- See Title
- Also applies to the hand drill
- Air Filters and Light Fixtures (two that I checked) are unaffected, if that helps

**Comment by Mervill** [comment]
Apparently this hasn't been in the game since at least May 2015?

I swear I've heard vending machines make noise when I open them

**Comment by lzimann** [comment]
I don't think they ever had a noise.

**Comment by Arianya** [comment]
Doors absolutely use to have a screwdrivering sound, which is also partially a "balance" concern since door hacking should be audible

Looking into this now, think I've found the fix.

**Comment by Arianya** [comment]
Okay, yes, my fix works. I've already put it back on airlocks, should I add it to vending machines for consistency's sake? I'm not sure if it use to.
