### ISSUE TITLE
photon torpedo desc

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#22798]
![ss 2017-01-06 at 09 14 50](https://cloud.githubusercontent.com/assets/6510293/21722048/945562ca-d3f0-11e6-927a-88d886024162.png)

**Comment by calzilla1** [comment]
D E E P L O R E

**Comment by lzimann** [comment]
What is the issue here?

**Comment by TehZombehz** [comment]
The issue is that the description is that of the mini-meteor when that is clearly a photon torpedo. Simple text problem.

**Comment by bgobandit** [comment]
do we even have photon torpedos

**Comment by Bawhoppen** [comment]
@bgobandit H  O  L  O      D  E  C  K

**Comment by bgobandit** [comment]
yes I know hence the fact that I already have a pr fixing it
