### ISSUE TITLE
[Centcom] Missing tiny fan

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#22806]
![image](https://cloud.githubusercontent.com/assets/609465/21737149/290424b0-d46e-11e6-8945-3a65132ca992.png)

I don't know what this area is, but there was no air in this part.

Also, tiny fans are the devil.

**Comment by coiax** [comment]
@Okand37

**Comment by Okand37** [comment]
thats missing more than a tiny fan sir

**Comment by PKPenguin321** [comment]
the object you are looking for is called a wall

or an airlock
