### ISSUE TITLE
Bug with limb replacement surgery(augmentation) & Bug with Prosthetic Replacement surgery.

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#22813]
Lets take digigrade legs for example. If you want to replace someones existing leg with a digigrade leg, you first have to do amputation surgery on said leg, and then do the prosthetic replacement surgery on them to replace their leg.

If you don't do this, and instead opt for the Augmentation option to try to replace their leg, instead of replacing their leg with a digigrade leg, it will replace their leg with a cyborg one(or at least, it looks 100% like a leg augmented by a cyborg limb).

Either it should only allow you to use cyborg limbs during the augmentation surgery, or it should correctly replace said limb with the one you intend to replace it with and be renamed to Limb Replacement Surgery. Heck, the Prosthetic Replacement surgery should possibly also be renamed.(This also explains why that frankenstein I tried to make instead ended up as an augmented human.)

Edit: Also, apparently I am suffering from terrible Engrish today.

Edit 2: Okay, time to expand the bug report. So, I tried to replace someones legs with Plasmeme legs. Now, as with above, the augmentation surgery gave them a cyborg leg. Buuut, when I tried to do it like I did with Digigrade legs....well. It correctly gave them the toxin damage that adding mutant limbs is supposed to do, but it didn't replace their leg with a plasmeme leg. Instead it gave them a perfectly normal human leg. (Or atleast, the leg looks like a perfectly normal human leg. The medical analyzer still lists it as a Synthetic Plasmaman leg). Thus I guess I now have to change the title aswell.

**Comment by kevinz000** [comment]
The bug is it working with augmentation because augmentation is specifically designed for robotic limbs.

**Comment by RemieRichards** [comment]
Easy bug, though it's your own fault for having the wrong zones selected,
this https://github.com/tgstation/tgstation/blob/eace4eec148e8a366ee2fe6673f852b59a2e77b1/code/modules/surgery/limb_augmentation.dm#L26 needs to be an ||, if you have the right zone selected for the limb it *should* correctly deny you, but it needs fixing all the same.
