### ISSUE TITLE
Botany is making mutation toxins

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#22812]
Shit's supposed to be xenobio only.

**Comment by coiax** [comment]
This is thanks to the mystery or ancient seeds or whatever they're called right?

Don't those require cooperation from Cargo anyway?

**Comment by XDTM** [comment]
Praise the any-chem-at-all seeds

**Comment by ma44** [comment]
1/300~ chance of that happening, I say it's feature

**Comment by Armhulen** [comment]
feature

**Comment by Core0verload** [comment]
Feature. Now close.

**Comment by improvedname** [comment]
LYNCH HYDRONICS THEY ARE TURNING PEOPLE INTO ASH WALKERS

**Comment by calzilla1** [comment]
Close

**Comment by optimumtact** [comment]
this is clearly not a bug @lzimann close these in future and direct them to feedback forum to argue balance concerns
