### ISSUE TITLE
Nuke ops cybernetic bundles are empty

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#22814]
Spending 40TC for box containing two autoimplanters is not fun.

**Comment by Nabski89** [comment]
Just had this happen to me too.

**Comment by MimicFaux** [comment]
Surprised it took this long to be noticed.

**Comment by Nabski89** [comment]
It was 75% off in the discount menu for me.

**Comment by Mervill** [comment]
Related to #22962??

**Comment by coiax** [comment]
Doubtful.
