### ISSUE TITLE
Crushers break hand slots when slotting into back

### ISSUE THREAD

**Issue by Arianya** [tgstation/tgstation#22821]
**Issue:** When the crusher is equipped to the back slot, it leaves a rogue offhand in your non-active hand, which can't be dropped other then by a forcedrop from admins. If this offhand is swapped to, you are then unable to swap hand at all or use that hand for anything.

**Expected Outcome:** The crusher should go into the back slot and the offhand deleted

This is presumably caused by #22712 

@Haevacht 

![Before Equipping](https://puu.sh/teo22/21d9d5217d.png)
![After Equipping](https://puu.sh/tenG0/79b0b12e98.png)
![Error when trying to swap off the hand](https://puu.sh/tenHe/203273131b.png)

**Comment by Haevacht** [comment]
For now, you should be able to activate it inhand to qdel the offhand item. If #22679 is in, that is.

This never happened on local, if anyone has details hit me up.

**Comment by Arianya** [comment]
Reproduction details:

1. Equip mesons
2. Remove backpack/satchel/duffelbag/[initial back slot]
3. Equip explorer's webbing on belt slot
4. Insert bluespace shelter capsule into webbing
5. Insert survival medipen from pockets to hands to webbing
6. Insert emergency extinguisher into webbing
7. Grab mining satchel from backpack (click drag on to self) and put in vacant pocket
8. Pick up kinetic crusher
9. Put kinetic crusher on back

You should now have the off-hand while the crusher is on your back.

**Comment by Arianya** [comment]
@Haevacht While activating in hand does work, but it also causes a runtime

![See here](https://puu.sh/teO1F/78f5f3411e.png)

This happens whether you activate it via hotkeys or click it manually
