### ISSUE TITLE
Buildmode fuckery

### ISSUE THREAD

**Issue by kilkun** [tgstation/tgstation#22826]
If you re-enter your body when you have buildmode enabled, it "disables" buildmode HOWEVER, your ability to right-click becomes broken until you enable and disable buildmode again.

**Comment by kilkun** [comment]
an obscure issue that's easy to work around, but all the same it should probably be fixed for QoL of admins who ~~abuse~~ use it.

**Comment by kriskog** [comment]
Can't reproduce
