### ISSUE TITLE
Energy Axe fuckery

### ISSUE THREAD

**Issue by kilkun** [tgstation/tgstation#22827]
Captain's Sabre, Eswords and basically all robust melee weapons that are sharp tend to dismember in one or two hits. However, the Energy Axe, the most robust of all, does not dismember at all.

My immulshions!

**Comment by kilkun** [comment]
I might to an overhaul of the energy axe to bring it into the modern age, so feel free to neglect this issue because it'll be fixed after the feature freeze is over.

**Comment by Armhulen** [comment]
make the energy axe great again
