### ISSUE TITLE
Swarmers can cause breaches with shuttles

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#22834]
- Shuttle docks next to a wall
- The walls next to the shuttle walls are now technically not adjacent to space
- Swarmer eats those walls
- Shuttle leaves
- There is now a massive breach

Very noticeable with Pubby's monastery shuttle

**Comment by Iamgoofball** [comment]
this cant be fixed

**Comment by PKPenguin321** [comment]
Not sure about that since I have a fix in mind but I'm not sure how swarmer code does its do

**Comment by PKPenguin321** [comment]
Never mind it was easier than expected
