### ISSUE TITLE
Instant summons allows you to move anchored machinery/objects.

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#22837]
If you place an instant summoned object into a suit storage unit, microwave, destructive analyzer, or any anchored machinery that holds items, it teleports the anchored object to you. This also allows instant summons to steal the actual paradox bag itself and not the gimmick satchels.

**Comment by PKPenguin321** [comment]
Instant summons PLEASE

**Comment by Incoming5643** [comment]
This isn't a bug

**Comment by coiax** [comment]
I've had anchored disposal bins summoned to my tile, and wall safes (which are items for some reason), summoned into your hand. This just causes some WEIRD interactions.

**Comment by Detective-Google** [comment]
still a problem

**Comment by timothymtorres** [comment]
> I've had anchored disposal bins summoned to my tile, and wall safes (which are items for some reason), summoned into your hand. This just causes some WEIRD interactions.

This is hilarious

**Comment by timothymtorres** [comment]
This was fixed with #64862
