### ISSUE TITLE
borgs can have no name

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#22844]
states, "Ow."
http://i.imgur.com/1BfXX4J.png

**Comment by calzilla1** [comment]
STEALTH MODE ACTIVATED

**Comment by YakumoChen** [comment]
it's really annoying / impossible to track no-name borgs through cameras or as AI

**Comment by lzimann** [comment]
Might have been caused by #22211 
@coiax

**Comment by coiax** [comment]
Almost certainly.

**Comment by improvedname** [comment]
Who woulda guessed having no borg name setup would cause this

**Comment by Armhulen** [comment]
sssh, let em go
