### ISSUE TITLE
Synthetic arm sprite glitch

### ISSUE THREAD

**Issue by TribeOfBeavers** [tgstation/tgstation#22850]
Placing a synthetic human left arm on a table from the left side makes the sprite super tiny: http://imgur.com/a/cTJz0 (Its just to the left of the APC, its about 3 pixels)
 You can pick it up and it will stay tiny: http://imgur.com/a/6xZv4
 If you place it on a table from any other side the sprite returns to normal: http://imgur.com/a/xahEx

I haven't tested with other limbs.

**Comment by Firecage** [comment]
@lzimann Mmm, actually a sprite issue. And its easy to see how its caused, since the sprites are directional, because humans, flymen, liggers, etc. are all build up using those parts. Soooo.....yah...

**Comment by RemieRichards** [comment]
those limbs can override ```SetDir()``` so that their dir is always ```SOUTH``` (the one that works best, imo)

**Comment by Firecage** [comment]
Wouldn't that interfere with how mobs are...well...put together though?

**Comment by RemieRichards** [comment]
No, because the sprites used on mob are an overlay, not the actual object.

**Comment by Firecage** [comment]
Ah, cool.
