### ISSUE TITLE
Spraycans are spammy

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#22851]
With the sound update to spraycans, now every letter you make with it you get 3 messages -starting, spraying, and finishing

This is horrendously chat-spammy, especially when using it a lot.

**Comment by Dorsisdwarf** [comment]
Actually @lzimann I think it's partially a bug, in that you recieve the "you hear spraying sounds" deafmessage even if you can see the spraying

**Comment by optimumtact** [comment]
that's a seperate issue, but a valid one, so I'll let this slide for now. Ideally you would use the feedback forum for these kinds of annoyances/things needing tweaking

**Comment by Mervill** [comment]
I was the one who made spraycans not silent, I'll check this out
