### ISSUE TITLE
bad food's reagent id is "????"

### ISSUE THREAD

**Issue by ShadowDeath6** [tgstation/tgstation#22864]
https://github.com/tgstation/tgstation/blob/master/code/modules/reagents/chemistry/reagents/toxin_reagents.dm#L462

My best guess as to why it looks like is to make it not show up as something on health analyzers but it was switched, maybe? It's extremely weird and the id that is only used in code and admin stuff shouldn't be a bunch of question marks.

**Comment by improvedname** [comment]
????

**Comment by Cyberboss** [comment]
Food poisoning should be a disease not a reagent
