### ISSUE TITLE
Syndicate commandos  dont leave a body

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#22865]
Warpstorm event: Buncha syndicate commandos and elite nuke ops  show up.

Elite ops drop their bodies with all their gear. Commandoes in red hardsuits just disapppear from reality

**Comment by improvedname** [comment]
Bluespace

**Comment by YakumoChen** [comment]
intended, was instated back when away missions were a thing to stop everyone from having free syndie armor

**Comment by lzimann** [comment]
Intended: #15445

**Comment by RemieRichards** [comment]
They should atleast drop corpses without their weapons.
And since this mentions the portal storm variant, those ones should be fine dropping loot, it's a rare event.

**Comment by lzimann** [comment]
Should probably make the portal spawn a sub-type of the mobs with some loot/leaving body. But gotta wait the freeze.

**Comment by KorPhaeron** [comment]
This is a bug, they dont leave their gibs either
