### ISSUE TITLE
RPD can't make half the disposals junctions it needs to

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#22875]
Disposals pipes can only face one direction. T shaped junctions will sort right, for example. There is no way to flip them, such as making them sort left but still be T shaped. Same with Y junctions. You can't pick up disposals pipes (for whatever fucking reason) so you can't flip them.

**Comment by Core0verload** [comment]
Try RMB menus, alt-click, shift-click. Then close this.

**Comment by PKPenguin321** [comment]
Maybe related to https://github.com/tgstation/tgstation/issues/22248

**Comment by ShadowDeath6** [comment]
Can't you pull it around to make it change directions?

**Comment by YakumoChen** [comment]
pulling it can't ''flip'' the pipe to mirror it.

**Comment by YakumoChen** [comment]
alt click is the first thing I tried and it does the same thing as dragging it. RMB has no discernible difference, either

**Comment by Core0verload** [comment]
rgb menu has a fucking "Flip Pipe" button in it

**Comment by optimumtact** [comment]
This is not a bug
