### ISSUE TITLE
Traitor panel spawned nuke ops have regular traitor uplinks

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#22883]
1) Run testing server, mode defaults to extended.
2) Make someone an operative via traitor panel.
3) Examine uplink, it's a traitor one, with no fun cybernetics or the ability to buy your own cyborg.

**Comment by coiax** [comment]
On an extended local server, spawning an "uplink/nuclear" will not give you a nuclear uplink either. Also event lone operatives don't get nuclear uplinks either.

**Comment by AnturK** [comment]
I said it on irc but not sure anyone noticed, @Incoming5643 made these cache at object level for some reason, but made it generate before gamemode override variables are assigned.

**Comment by Incoming5643** [comment]
I'll look into it, there was a reason why I did that.

Forgot what it was though.

**Comment by coiax** [comment]
I think this is fixed as well.
