### ISSUE TITLE
Issue with Modular Computer(ID Card Modification Program)

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#22906]
Well, more like 2 issues I recently encountered actually.

1. Tried to use it to give myself all access with the captains spare ID. The cards were in the correct slots. What happened instead? There were no options to give myself any access at all, instead, it only had the option to demote my ID. Interestingly, when I put the captains ID in the target slot, and my assistant ID in the Auth Slot, I could demote the captains ID.

2. You can use it to open job slots no matter your access level. You can have assistant level access, yet be able to open more job slots.

3. In the ID Card Modification Program, it seems it lacks some jobs in the section where job slots can be closed or opened. As an example, there's no Chaplain option, despite it being available on normal ID computers.

**Comment by Mervill** [comment]
❄️ ❄️ ❄️ ❄️

**Comment by optimumtact** [comment]
@Shadowlight213

**Comment by Mindustry** [comment]
The chaplain is actually on the blacklist of jobs you're not allowed to open up more slots for.

https://github.com/tgstation/tgstation/blob/master/code/modules/modular_computers/file_system/programs/card.dm

**Comment by Firecage** [comment]
@Mindustry Well, you can on the traditional ID computer. It was enabled quite awhile ago.
