### ISSUE TITLE
Centcom fire alarm icons show green even when its code blue

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#22901]
They dont update the icon

**Comment by Core0verload** [comment]
It's intentional. Security codes affect SS13 (z1), but not the other stations or ships.

**Comment by optimumtact** [comment]
How do you know they were not referring to an onstation alarm

**Comment by Core0verload** [comment]
>Centcom fire alarms

**Comment by Shadowlight213** [comment]
I should probably point out that the UI of the alarms properly shows the alert level

**Comment by optimumtact** [comment]
Shadowlight that's a bug, since they shouldn't change at all
