### ISSUE TITLE
ashwalker tendrils take small amounts of damage from limbs every time they eat a body

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#22907]
Tendrils will eventually die, which megasucks.

Thank you Grazy for pointing this out

**Comment by ShadowDeath6** [comment]
Easy fix, just make the tendril behave like regular mining mobs when thrown stuff hits it

**Comment by Armhulen** [comment]
=free antag token

get on it lads

**Comment by KorPhaeron** [comment]
This is a problem with using EI NATH as well, you just get pelted by limbs (which will eat through your shields as well)

**Comment by Armhulen** [comment]
we shouldn't make limbs do throw damage at this point

**Comment by coiax** [comment]
I think you're implying that being hit by a detached arm at high velocity wouldn't hurt. Let's just give the tendril some low level regeneration or hardness or armor or something.
