### ISSUE TITLE
Ayys say "..." when talking

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#22910]
Ayy telepathy should be silent.

**Comment by calzilla1** [comment]
Feature

**Comment by PKPenguin321** [comment]
Dupe

**Comment by Mervill** [comment]
OF WHAT ISSUE SHDFLKJSDHFLKJHDSLFKJSDFKJ

**Comment by JJRcop** [comment]
I have a PR almost done that will fix this

**Comment by Armhulen** [comment]
i actually really hate this so go for it @JJRcop

**Comment by PKPenguin321** [comment]
dont remember what issue but i recall https://github.com/tgstation/tgstation/pull/21792 being in response to it

**Comment by XDTM** [comment]
Issue is in line 67 of code/game/say.dm. Apparently that line stops runtimes, so i'll leave the fix to someone who knows what they're doing.

**Comment by Armhulen** [comment]
i was hoping this was easy 4 ez tokens but i suppose not
