### ISSUE TITLE
Firelocks can have their maintenance panel opened, but have no write sprite and aren't hackable

### ISSUE THREAD

**Issue by Mervill** [tgstation/tgstation#22927]
> You open the maintenance hatch of the firelock.

You can open the panel with a screwdriver, but no wires appear and clicking the lock with hacking tools does nothing. I assume this is because firelocks are not meant to be hackable.

**Comment by BeeSting12** [comment]
Its used to deconstruct them

**Comment by Mervill** [comment]
Right. So I guess it's just missing the wires sprite? or should it be a different sprite to indicate that the panel is open, since wires imply hacking? @WJohn

**Comment by ma44** [comment]
Opening the panel only serves for deconstructing and upgrading with plasteel. 

Alternatively, I believe that they cannot be hacked, ever.

**Comment by optimumtact** [comment]
This isn't a bug as such, just a missing UI feature

**Comment by Cyberboss** [comment]
Crowbar is hack mode for firelocks.

Just remove maint panels from them
