### ISSUE TITLE
Trying to refill fire extinguishers with a water tank makes you hit the watertank

### ISSUE THREAD

**Issue by Trinerc** [tgstation/tgstation#22921]
Well, as the title says, whenever i try to fill an extinguisher with a water tank i end up hiting the water tank which damages it so it ends up being destroyed before i can bless the whole station as the chaplain.

(note ive tried both with normal water and holy water and the bug still persists
![watertank](https://cloud.githubusercontent.com/assets/22849794/21833378/60d51988-d777-11e6-89f5-0e722263e830.png)

**Comment by coiax** [comment]
DIE WATER TANK DIE
