### ISSUE TITLE
Magic Missile not working on people on secways

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#22937]
See title.

**Comment by calzilla1** [comment]
Feature

**Comment by ExcessiveUseOfCobblestone** [comment]
Paul Blart, Part-time Mall Station Cop and Wizard Killer.

**Comment by improvedname** [comment]
F e a t u r e

**Comment by jughu** [comment]
feature

**Comment by Haevacht** [comment]
Probably due to the target being buckled to the secway. Onhit unbuckle maybe?

**Comment by coiax** [comment]
When someone is knocked down by stamina damage, they fall off the segway.

**Comment by Detective-Google** [comment]
No longer an issue during testing
