### ISSUE TITLE
can't emag suit storage containers anymore

### ISSUE THREAD

**Issue by kilkun** [tgstation/tgstation#22945]
give me back my obscure murder devices.

**Comment by Mervill** [comment]
I assume you mean `/obj/machinery/suit_storage_unit`, which doesn't even have an `emag_act` defined, so I suspect it may have been intentionally removed?

**Comment by optimumtact** [comment]
It was intentionally removed, complain about it on the forum.

**Comment by PKPenguin321** [comment]
I was never aware of being able to emag them, turning them into murder devices has always required wire hacking I thought
