### ISSUE TITLE
Got a emp kit from a surplus crate but it was empty

### ISSUE THREAD

**Issue by improvedname** [tgstation/tgstation#22962]
I got a emp kit from a surplus kit just to find out it was empty

**Comment by Mervill** [comment]
explain this to me like I only joined this community last October

**Comment by improvedname** [comment]
Oke 
1 buy surplus crate
2 get 50 tc worth of shit
3 items were. Powersink, stetchkin, 10mm(normal), 375 revolver, freedom implant, boxed suit, emp kit, 375. Speedloader, surgery dufflebag,
4.Grab emp kit notice its empty

**Comment by Arianya** [comment]
@Mervill One of the available options for the traitor to buy from their uplink is a surplus crate, which costs 20 tc but comes with 50 total tc of randomized gear.

The EMP kit normally comes with a box containing an EMP implant and a number of EMP grenades, but when bought from this surplus crate it (allegedly) comes empty

**Comment by Mervill** [comment]
I assume you mean this
```
(Pointless) Badassery
    Syndicate Bundle          (20 TC)
```

**Comment by PKPenguin321** [comment]
No, the surplus crate, not the bundle

**Comment by Mervill** [comment]
Ok I got the right one now

**Comment by calzilla1** [comment]
Although bundle>surplus crate

**Comment by Mervill** [comment]
I can't forcibly reproduce this (short of endlessly rolling surplus crates)

**Comment by PKPenguin321** [comment]
Would be really easy just vv uplink to have infinite TCs and spam crates

**Comment by Mervill** [comment]
Tried that too, can't reproduce

**Comment by bgobandit** [comment]
I can't reproduce this at all including via spamming crates

**Comment by PraiseRatvar** [comment]
@Dorsisdwarf 
if no one can reproduce then lets just assume he got a 1/1000000 chance bug

ccclose?
