### ISSUE TITLE
Tesla can kill invulnerable mobs.

### ISSUE THREAD

**Issue by TheDreamweaver** [tgstation/tgstation#22961]
The tesla can kill mobs that are meant to be invulnerable/invincible (i.e. Statues, etc.) if the main energy ball touchs/explodes on them.

**Comment by Buggy123** [comment]
To be fair, so does the singularity. Might be intended behavior.

**Comment by Armhulen** [comment]
*Should be intended behavior

**Comment by TheDreamweaver** [comment]
Singulo, maybe. But tesla doesn't really make sense, especially for thing
like the Statue.

**Comment by improvedname** [comment]
It is a giantic ball of electrical shit with high force you think you wont explode when you touch such ball?

**Comment by Firecage** [comment]
Well, to be fair, Statue mobs aren't invincible. Ridiculous amount of health? Yes. Invincible? Nope.

**Comment by ShadowDeath6** [comment]
https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/simple_animal/hostile/statue.dm#L46

**Comment by XDTM** [comment]
Godmode has already been defined as "invulerablility expect for instant kills" aka gibbing or, in this case, dusting. This is consistent with how it usually works.

**Comment by KorPhaeron** [comment]
I'm pretty sure Doctor Who kills the weeping angels by throwing them into a singularity and the tesla is the electricity version of that so

**Comment by ShadowDeath6** [comment]
KOR CONFIRMS SINGULO IS STRONGER THAN TESLA 2017
