### ISSUE TITLE
AI "nothing" objective that I also failed

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#22967]
![untitled](https://cloud.githubusercontent.com/assets/10399117/21886187/a54c4a2a-d888-11e6-8a05-9cb8c62ae4a9.png)

**Comment by evsey9** [comment]
feature

**Comment by improvedname** [comment]
Only a true mime can accomplish this ovjevtive

**Comment by calzilla1** [comment]
Did you do something? If so, you failed doing nothing!  Non issue close now

**Comment by Shadowlight213** [comment]
Oh hey, you managed to protect the scientist guy. Good work. Sucks that the objective got bugged.

**Comment by bgobandit** [comment]
Still happening

Saul_Myers was P.O.C.K.-IT the AI and survived
Objective #1: Protect Enjoys-Her-Sweets, the Security Officer. Success!
Objective #2: Nothing Fail.
Objective #3: Stay alive until the end. Success!
The traitor has failed!

**Comment by bgobandit** [comment]
So after testing I have it narrowed down to the source of the Nothing objective being this: 

https://github.com/tgstation/tgstation/blob/bdb1f38ed306144270c26e251a91d4da3081527d/code/game/gamemodes/traitor/traitor.dm#L115

but I have no idea WHY it's "Nothing." in the mind it still shows up as a maroon objective type
