### ISSUE TITLE
MORPH BLUE PIPE RETURN TO BLOB BE BLUE BLOB

### ISSUE THREAD

**Issue by improvedname** [tgstation/tgstation#22973]
So when your morph and you take the form of a blue pipe(any color i think) and then turn back you are a blue morph

**Comment by lzimann** [comment]
Probably not removing the color properly after returning to original form.

**Comment by PKPenguin321** [comment]
Yep, same thing used to happen with transparency values

**Comment by PKPenguin321** [comment]
See: https://github.com/tgstation/tgstation/pull/16010
