### ISSUE TITLE
Lavaland base ID doesn't work

### ISSUE THREAD

**Issue by Goodstuff123456** [tgstation/tgstation#22987]
On the lavaland syndicate base the ID's don't work.

**Comment by optimumtact** [comment]
Which server was this on?

**Comment by KorPhaeron** [comment]
@Shadowlight213 

Your fix unfixed it

**Comment by calzilla1** [comment]
AAAAAAAAAAAAA

**Comment by Armhulen** [comment]
COME ON

AGAIN

COME ON

**Comment by Shadowlight213** [comment]
@KorPhaeron it wasn't my fix.
And I asked the person if they actually tested the fix before pring it as it was exactly the same as my fix that didn't work, and they said no.

**Comment by Goodstuff123456** [comment]
This was on Sybil
