### ISSUE TITLE
Blob zombies are apparently invisible.

### ISSUE THREAD

**Issue by dannno** [tgstation/tgstation#22982]
![](http://i.imgur.com/y7FJ6Xc.png)
Can't see them unless you alt click the tile they're on
pretty confusing when you're nowhere near the blob and getting killed by an alleged zombie

**Comment by Militaires** [comment]
let me add more details

- the blob in question wasnt meant to exist, it was var edited to have adminordazine as a chem, that may have fucked with shit.

**Comment by PKPenguin321** [comment]
Adminordrazine blob wot who approved this

**Comment by Kromgar** [comment]
That means it would inject adminordrazine into people... 

if anything  that poor blob was doomed form the start

**Comment by ChangelingRain** [comment]
admin varedits cause issues, no more at 11

**Comment by ChangelingRain** [comment]
Hey Look It Turns Out When You Edit A Typecast Var To The Wrong Type It Causes Runtime Errors When You Try To Access Vars It Doesnt Have

**Comment by dannno** [comment]
Didn't know, mb

**Comment by Militaires** [comment]
@Kromgar @Pkpenguin321

i was that blob it was a fun round full of runtime errors but people learned to be nice to me in the end
