### ISSUE TITLE
Striking someone with a Power Fist causes them to be unable to be pulled

### ISSUE THREAD

**Issue by SweaterKittens** [tgstation/tgstation#22992]
Using a Power Fist on a player makes their mob unable to be pulled or grabbed.

**Comment by Cyberboss** [comment]
@MrStonedOne looks like throwing is fucky? https://github.com/tgstation/tgstation/blob/e9ebe52616d1ada3009253a31263f5dc0ae1c4d7/code/game/objects/items/weapons/powerfist.dm#L90

**Comment by Profakos** [comment]
I have ran a few test about this. The person seems to be stuck in the state of being thrown. If someone bumps into them, both of them fall over, and you get a message about the punched person colliding with the other one.

 Changing the speed argument from 0.2 to 1 seems to fix this, so i digged deeper, into the throwing subsystem. 
https://github.com/tgstation/tgstation/blob/31ee152489791a9cd0bb61bcfef6ab910b97eb90/code/controllers/subsystem/throwing.dm#L80

The rounding above rounds tilestomove down to 0, thus skipping the entire while loop, therefore the object won't move, nor will be the throwing finalized until someone bumps into the projectile person.

**Comment by Cyberboss** [comment]
That helps a ton, thanks
