### ISSUE TITLE
No ingame documentation on how to build a Bluespace Artillery and the Bluespace Artillery computer is a machine board and gives free glass if deconned because the machine turns into a computer

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#22997]
The whole thing is a fucking mess. 

Also  just building the damn machine it  looks absolutely retarded and makes no sense Coiax had to look at the code just so we could build this  thing

It has to be built in a precisely specific way because once it is finished the thing unfolds  into a GIANT FUCKING MASSIVE  CANNON which  there are no instructions saying it does. Oh and it does have to be in a large open area

It can not be oriented right either it can only be oriented  left... this  resulted  in me and cherry cutting the station  inhalf.

Oh and the machine parts that aren't the computer can  not be deconned they have to be destroyed because you cant screwdriver and crowbar them

**Comment by Iamgoofball** [comment]
Not a bug, close

**Comment by SgtxRootbeer** [comment]
It is however an issue, a pretty big one at that.

**Comment by XDTM** [comment]
there's a guide on the wiki on how to build it

**Comment by Kromgar** [comment]
Oh and the machine parts that aren't the computer can  not be deconned they have to be destroyed because you cant screwdriver and crowbar them

**Comment by XDTM** [comment]
also you _can_ turn it right, it depends on how you place the machines

**Comment by optimumtact** [comment]
report it on the forum as there are no specific bugs
