### ISSUE TITLE
staff of change memes

### ISSUE THREAD

**Issue by kilkun** [tgstation/tgstation#23005]
players turned into an ash drake cannot fly, summon fireball storms and have really low health

if this is a balance thing why even fucking bother having it in what a buzzkill

**Comment by Haevacht** [comment]
Title your bullshit better.

**Comment by KorPhaeron** [comment]
Alt+click to fly

**Comment by lzimann** [comment]
It's a lesser ash drake and not a full drake. Also this is not an issue.

**Comment by kilkun** [comment]
@KorPhaeron I tried that and it didn't work

@lzimann then why doesn't it say "lesser ash drake"
