### ISSUE TITLE
Blob Glitched As Hell

### ISSUE THREAD

**Issue by Hazrond** [tgstation/tgstation#23003]
Played a game and was spawned as blob, first the game wouldnt get off of the main lobby screen until i relogged despite the Admin trying to manually move me, then the game froze completely and i was stuck waiting in the bathrooms as a catatonic blob until crew eventually killed me. Running latest stable version of BYOND and the most recent update of DirectX.

**Comment by Mervill** [comment]
How do you know this was related to the blob? Did you play normal rounds before / after this?

**Comment by ShizCalev** [comment]
Will close in a week without another repo.
