### ISSUE TITLE
Explosions can still be dodged

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#23014]
At some point someone fixed the server-wide lag caused by an explosion but not the explosion's lag.

The result is that crew can pretty effortlessly walk away from a maxcap explosion if they weren't standing immediately next to it. The results can be a little inconsistent based on how the server is performing.

My proposed solution would be to have a stun immediately go out within X range to represent the "shockwave" of the blast, then the blast (slowly) processes like normal. If we still want people to be able to dodge at the outer reaches of the blast make "X" range relatively small (6 tiles), otherwise if we want bombs to be fairly lethal then put the stun at flash range.

**Comment by ChangelingRain** [comment]
Walking away isn't the same as dodging, and also isn't an actual bug.
Dodging was the trick where you could move into an already-hit tile to avoid getting exploded, which is fixed.

**Comment by Robustin** [comment]
Still an issue... just like wavedashing and all the other shit we fixed even though it was just code performing like it was written.

**Comment by ChangelingRain** [comment]
Being able to run away from bombs is not a bug and would make bombs, of every sort, actually just ridiculous to deal with.
Do you, oldman robustin, master bomber, have an *agenda* here?

**Comment by MrStonedOne** [comment]
that is it working as intended. bombs can only process as fast as the server has time for.

The solution is to not set off multiple explosions at once. let one finish before starting the next.

**Comment by Arianya** [comment]
Cool guys can run away from explosions.

Rule of cool applies, and anyone in flash range will probably get gibbed or smacked to death by flying debris before they realize whats going on anyway.
