### ISSUE TITLE
Decapitated head showing the wrong name

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#23016]
Now, normally when you get decapitated, your head is named after like, for example: "Zoey Webb's Head"

Now, here's the issue. If you are wearing someone else's idea, lets say "Eric Honkerome", and you get decapitated, your head won't have your own name, it will instead have the name of the ID you were wearing, like: "Eric Honkerome's Head". And note, I wasn't wearing a mask or anything which actually fully disguised my name. I was just wearing the ID with no face hiding gear.

**Comment by lzimann** [comment]
The whole naming thing is WEIRD

**Comment by improvedname** [comment]
I mean it makes sense if your wearing that idd because you dont know their real idenity

**Comment by XDTM** [comment]
Seems to grab the name instead of the real_name. I'm surprised it doesn't do stuff like Jack (as James)'s head

**Comment by Supermichael777** [comment]
okay what revision was this?

and was it tg's server
