### ISSUE TITLE
Outbomb Cuban Pete uses old syndicate tank transfer valve bombs.

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#23024]
Said tanks are over pressurized but do not explode without removing the tanks from the TTV. The only explosion you can get is a tank rupture with the size 0,0,2 and bombs never hit bombcap due to what I assume is in a change to bomb/atmos code?

**Comment by Armhulen** [comment]
cuban pete is now literally a dead meme

**Comment by lzimann** [comment]
This was never meant to hit the bombcap. But them not exploding sounds like a bug.
