### ISSUE TITLE
Jetpacks = Superfast starvation

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#23030]
I have no idea why hunger works based on tiles moved but the counter intuitive result is that effortless jetpacking through space leaves you starving within a couple minutes.

**Comment by Mervill** [comment]
I just flew in from lavaland

and boy are my arms tired

*snare drum*

**Comment by WJohn** [comment]
wait, what? it's based on tiles moved? not time?

MY WHOLE LIFE WAS A LIE

**Comment by PKPenguin321** [comment]
Is this really even fixable?

**Comment by optimumtact** [comment]
Well yes but not too easily.

The code is correct in that faster speeds are supposed to burn energy quicker. We just lack the concept of user expended energy versus energy provided by some other means. So to the code it's just like the player mob is running really fast, even though they just have a jetpack.

**Comment by Davdichan** [comment]
Tiles moved was one of the lesser ways they 'balanced' ninja cause he moves so damn fast and needs to a lot of time to take his hood on and off.

**Comment by Supermichael777** [comment]
> balance ninja

haha

**Comment by XDTM** [comment]
@WJohn it's both, by the way
