### ISSUE TITLE
Mint toxin doesn't gib fat people

### ISSUE THREAD

**Issue by Goodstuff123456** [tgstation/tgstation#23043]
Fat people don't explode when they eat it.

**Comment by swindly** [comment]
The fat alert appears when a mob's nutrition is higher than 600. After being fat for several minutes, the overeatduration will exceed 500 and the mob will receive the fat disability. A mob with the fat disability can be gibbed with minttoxin.

**Comment by Goodstuff123456** [comment]
Alright I couldnt get it it work
