### ISSUE TITLE
Slaughter demons can heal from eating drones

### ISSUE THREAD

**Issue by vcordie** [tgstation/tgstation#23055]
An entirely mechanical contraption lacking any blood, or really even the definition of "alive" heals slaughter demons (and probably laughter demons) when dragged into blood, encouraging the slaughter of these helpless drones. for only a dollar a day, you can make slaughter demons make sense and save the lives of the poor little robot helpers.

**Comment by ShadowDeath6** [comment]
They can eat borgs as well, which makes them drop brains

**Comment by calzilla1** [comment]
Techno demons

**Comment by KorPhaeron** [comment]
They're magic they dont need to make any sense
