### ISSUE TITLE
Reviver Implant is hot garbage that completely fails.

### ISSUE THREAD

**Issue by vcordie** [tgstation/tgstation#23053]
The reviver implant's healing is so weak, it doesn't outheal the oxy damage caused by being in crit, meaning you'll die with it anyways if you get knocked into crit. needs a buff, badly.

**Comment by XDTM** [comment]
It has a 90% chance of healing 3 oxy damage per tick, which should be more than crit does unless you've bled badly. Looking at the code, though, it seems that the cooldown never gets reset, which means that the revival time would stack up infinitely. Maybe it was just inactive.

**Comment by XDTM** [comment]
It has 90% chance of healing 3 oxy damage a tick. Are you sure you didn't bleed badly or that it wasn't on cooldown?

**Comment by vcordie** [comment]
I wasn't bleeding badly, but trust me, it's very very shit. it NEEDS a buff, badly.

**Comment by lzimann** [comment]
Use forums to request buffs. Unless the implant is failing somehow, this is not a bug.

**Comment by KorPhaeron** [comment]
It being so bad as to be non functional is a bug

**Comment by lzimann** [comment]
A bug it is then.
