### ISSUE TITLE
Posters generate a progress bar despite not being interruptable

### ISSUE THREAD

**Issue by Arianya** [tgstation/tgstation#23069]
When placing a poster, the object will remain in hand and a progress bar will come up while the poster deployment animation is played, but the player can move away from the poster without interrupting poster placement and the poster will just zoop out of their hand upon finishing.

More a graphical inconsistency then anything.

**Comment by alexkar598** [comment]
Then do you think that the best would be to remove the posterfrom the hand as soon as you start placing it or just not placing it if you move?
