### ISSUE TITLE
Syndicate dark mauler mechs have no cooldown on attacking doors

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23071]
Might also be regular mechs as well?

**Comment by Kromgar** [comment]
Oraoraoraora

**Comment by kilkun** [comment]
it is, i saw a mauler use it's ac2 to spam click its way through a bunch of walls once.

**Comment by kevinz000** [comment]
i believe I fixed this..? can someone test?

**Comment by Jordie0608** [comment]
Tested, fixed.
