### ISSUE TITLE
nuke ops can get discounts on mechs

### ISSUE THREAD

**Issue by vcordie** [tgstation/tgstation#23073]
This is more of a balance thing, because it allows them to get the mauler or whatever without declaring war.

**Comment by ChangelingRain** [comment]
This isn't a bug, and also it's not *impossible* to get the mauler without declaring war though I think it requires a shitton of population.

**Comment by vcordie** [comment]
like i said, balance issue. I'm of the opinion it shouldn't be possible to get a mauler for 30tc.

**Comment by ChangelingRain** [comment]
But that's the point of the discounts! Sometimes you get fancy shit for hella cheap.
