### ISSUE TITLE
The "asteroid with engines on it" shuttle is too big for new Centcom

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23077]
![image](https://cloud.githubusercontent.com/assets/609465/22036209/9dbebe08-dcea-11e6-81d5-5706acbf1ef2.png)

**Comment by Arianya** [comment]
Beat me to it 📯

**Comment by Kromgar** [comment]
So... what happens if your on the side thats not on the zlevel? Do you get nullspaced?

**Comment by coiax** [comment]
that's how the shuttle loads in, so there shouldn't be anyone on it at that time

**Comment by coiax** [comment]
although I do see your point, I don't know what happens if you're on a shuttle where the ends are off the map

Probably bad things

**Comment by Mervill** [comment]
Just need to move everything on z2 a couple tiles to the left
