### ISSUE TITLE
A level 5+ singularity will rip metal rods from lava

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23074]
BECAUSE IT'S ACTUALLY PLATING, HUEK

**Comment by Cyberboss** [comment]
https://github.com/tgstation/tgstation/blob/master/code/game/turfs/simulated/floor/plating/asteroid.dm#L97

Makes literally no sense

**Comment by PKPenguin321** [comment]
Low priority

**Comment by XDTM** [comment]
https://github.com/tgstation/tgstation/blob/master/code/game/turfs/simulated/floor.dm#L154

There's your answer
