### ISSUE TITLE
After metal rods are ripped out of the lava by singuloth, the ash left behind doesn't disappear

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23075]

**Comment by XDTM** [comment]
Couldn't reproduce, the ash burns instantly.

**Comment by coiax** [comment]
When I had my singularity ripping up metal rods from the lava, there would be huge fields of ash left behind.

**Comment by XDTM** [comment]
The code for burning makes the ash call Entered on the laval which in turn would burn up the ash. Maybe the server was getting lagged from all the rods making the lava process?

**Comment by PKPenguin321** [comment]
Probably caused by addtimer refractor testmerge

**Comment by Cyberboss** [comment]
This is my fault, forceMove doesn't call Entered/Exited if the loc is the same anymore

**Comment by XDTM** [comment]
Turns out i was testing on an outdated master
