### ISSUE TITLE
Old ore smelter doesnt drop ore if destroyed

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#23093]
![image](https://cloud.githubusercontent.com/assets/6778786/22047015/7c2caafe-dcf2-11e6-88d6-1ae3307322e6.png)

SCREAMS INTERNALLY

I didnt want to smelt it all but i couldnt eject it

**Comment by YakumoChen** [comment]
there's literally a written warning NOT to use it though right by the smelter

**Comment by XDTM** [comment]
Oh god that code is a mess

**Comment by KorPhaeron** [comment]
We should just remove the old smelter

**Comment by Thunder12345** [comment]
It's the gulag one. Let's replace it with a gulag ORM

**Comment by Kromgar** [comment]
This isnt the gulag smelter this is the mining smelter the old one when points werent a thing
