### ISSUE TITLE
[Delta] RD has no direct AI sat access, no teleport beacon on AI sat

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#23098]
Given the RD is one of the two people on the station with access to the AI core on normal stations, the RD needing to go through space to get to the AI is a little ridiculous. The Power Tool Storage doors block the way normally, and you can't teleport to the AI sat on Delta.

**Comment by Mindustry** [comment]
I think you would have a better chance reporting this in the thread, if delta is even maintained anymore

**Comment by Cyberboss** [comment]
@Okand37
