### ISSUE TITLE
divine vocal chords screws up targetting when namebanned

### ISSUE THREAD

**Issue by vcordie** [tgstation/tgstation#23118]
I'm namebanned, so my character name is randomized at the start of round, but the name on the character screen is Fluke Madrow. someone say burn luke gadow with the divine vocal chords (they were stuttering as well, so it came out as b-b-urn l-luke g-gadrow oor something simliar) and I got burned, despite not being luke gadow.

**Comment by XDTM** [comment]
were there others in range who were unaffected?

**Comment by XDTM** [comment]
Appearance bans rewrite the real_name, which is what is getting checked here, so it should work properly.

**Comment by XDTM** [comment]
Also, name focusing does not work if the name is not on the first part of the command, so you likely got hit by a global command.

**Comment by vcordie** [comment]
only two people were hit, myself, and luke gadow.

**Comment by XDTM** [comment]
[22:35:54]GAME: YOSHMASTER/(Reese Diyu-Nailao-Marcotte) has said 'BURN, LUKE GADOW' with a Voice of God, affecting Cecilia White, Sixteen Twenty, Ziggy Yoyo, ABDUCTOR Mothership Scientist, Armillus Dynat, Dayton Reichard, ABDUCTOR and Harrison Jenner, with a power multiplier of 1.

The name has to be said first to focus on someone.
