### ISSUE TITLE
Rotating chairs doesn't update their layer

### ISSUE THREAD

**Issue by TribeOfBeavers** [tgstation/tgstation#23112]
If you buckle yourself into a chair, then rotate it with alt click, the initial layer the chair is on is maintained.

So if you start by buckling yourself in facing north, then rotate it to face south, you'll end up with the chair's sprite being on top of yours while still being buckled to it.

The opposite is also true, starting by facing south and rotating to north will cause your sprite to be above the chair's. 

This happens with the chairs in escape shuttles, at least. Haven't checked with other ones.

**Comment by KorPhaeron** [comment]
@PKPenguin321 

Onshuttlemove

**Comment by PKPenguin321** [comment]
Gahhhh fuck I'll fix it in a bit
