### ISSUE TITLE
dmm_suite load_map() not initializing things loaded

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#23125]
Nothing loaded is initialized, this makes APCs , comms, and everything else not working.

**Comment by MrStonedOne** [comment]
This normally isn't an issue because the mapping subsystem loads before objects subsystem, and ssobj calls initialize on everything

and anybody fixing this needs to take that into account, if the objects subsystem hasn't loaded yet, having dmm_suite call initialize is actually bad, and will break pipes along other things because they depend on this order.

**Comment by AnturK** [comment]
This isn't really a bug loading maps directly through dmm_suite is deprecated, use map templates to load it after roundstart, can't remember if i added a helper for new z loading but it would be trivial.

**Comment by kevinz000** [comment]
@AnturK It's the only way to load in extra zlevels that admins can use (far as I'm aware), and it doesn't lag nearly as bad as map templates.

**Comment by MrStonedOne** [comment]
its actually things that don't call their parent new. as new() should be handling that for items spawned post map load.

**Comment by MrStonedOne** [comment]
oh wait, i'm high, #22778 hasn't been merged yet

once merged that would fix this bug.

**Comment by Cyberboss** [comment]
@MrStonedOne Do we actually load any kind of map after world/New? If so I need to tweak that PR a bit

**Comment by Cyberboss** [comment]
OK this is an issue, I'll look into it.

@lzimann Close this, it's a PR bug

**Comment by Cyberboss** [comment]
Oh @kevinz000 are you using that VERB??? You evil person, use the helpers!!! No wonder shit isn't getting initialized, SSobj doesn't know you called it! It will be WORSE after #22778 because loading things directly like that will cause fucktons of init runtimes

**Comment by PKPenguin321** [comment]
Nice one memelhi

**Comment by MrStonedOne** [comment]
cyberboss, you need to make the basic map loader smarter, it should prevent initialization until after all things are spawned, then init those things in mass.

**Comment by Cyberboss** [comment]
Yeah thats fixed in the Initialize refactor

**Comment by MrStonedOne** [comment]
What ever functionality that is in map templates that works properly should be moved from map templates and placed directly into dmm_loader

**Comment by Cyberboss** [comment]
The fact that those two are separate is REALLY starting to get annoying! I'm gonna take care of this real soon
