### ISSUE TITLE
Chameleon thermals don't have an action button when the code suggests they should

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#23124]
All other chameleon items that are wearable have action buttons, and the code to generate one exists for glasses, but it doesn't appear when wearing them (reported, duplicated datum, tried wearing). Clicking in-hand still works.

**Comment by XDTM** [comment]
I think you're referring to the chameleon HUDs that revs get, which are not related to chameleon clothing.

**Comment by Emilc4h** [comment]
I'm pretty sure he means the Chameleon Thermals from the traitor uplink, which last time I used them (admittedly, a few months ago) worked as above. No action button, but you get the basic station eyewear when you use it inhand.

**Comment by vcordie** [comment]
can confirm chamelon thermals have no action button.

**Comment by XDTM** [comment]
Which are, like cham HUDs, not actual chameleon items.

**Comment by coiax** [comment]
It's a bit inconsistent though. How much work would it take to make thermals inherit from camoglasses?

**Comment by XDTM** [comment]
Probably not that much, thinking about it; it's just a matter of implementing a whitelist on it.

**Comment by kriskog** [comment]
Can't reproduce, these have an action button now.
