### ISSUE TITLE
tgUI is borked again

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#23142]
Specifically the suit sensors console/handheld suit sensors monitor.
When I attempt to use either of them, the screen goes completely black and none of the game windows can be closed.  Sounds from the game can still be heard in the background.
This problem doesn't seem to exist with any other tgUI interfaces (air alarms, APCs, etc).

**Comment by AnturK** [comment]
Senors is not tgui it's snowflake interface. And there's a few issues about it being generally broken already.
#11774
#21328
#22124
