### ISSUE TITLE
You can push past cuffed people on help intent if you're the one pulling them.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#23165]
Probably caused by 
https://github.com/tgstation/tgstation/commit/11ca987acb96fbf6092ea897ed6429db79cfdf34#diff-df7fe1c87ccd86bb2878257cd89bc8f5R108

**Comment by bgobandit** [comment]
feature and a damn fucking good one

**Comment by AnturK** [comment]
This is a problem why ?

**Comment by KorPhaeron** [comment]
>This is a problem why ?

**Comment by Shadowlight213** [comment]
Cuffed people block movement past them in every other case. If this is a feature, then those other instances need to be modified.

**Comment by PKPenguin321** [comment]
Literally a feature and a non issue

**Comment by Cyberboss** [comment]
It's to prevent others from accidentally detaching the pull by walking through a person

**Comment by Shadowlight213** [comment]
Actually. never mind. I thought that it also applied if they weren't being pulled, hence.
