### ISSUE TITLE
random radio chatter is in italics and slightly delayed

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#23162]
![untitled](https://cloud.githubusercontent.com/assets/10399117/22137712/ae584024-deaa-11e6-97a8-f788827dc873.png)
Fuck this is so constantly triggering, and there's no reason why it's happening.

**Comment by XDTM** [comment]
Does someone remember when this started? Maybe i broke it when touching saycode for VoG.

**Comment by XDTM** [comment]
I saw the bug myself, but i couldn't reproduce it in testing, could it have been a testmerge?

**Comment by coiax** [comment]
It looks like radio chatter that's been looped through a station bounced radio

**Comment by XDTM** [comment]
it happened with no radio around, only my headset, on the science radio channel
