### ISSUE TITLE
Freon goes through hardsuits

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#23175]
Had CE hardsuit on, walked into a freoned area, got a cold alert and took damage.

**Comment by XDTM** [comment]
did you have internals on?

**Comment by lzimann** [comment]
I'm pretty sure hardsuits will block freon, but you need internals to be fully protected. Leaving this open until someone confirms the interaction.

**Comment by CPTANT** [comment]
dupe #20371
