### ISSUE TITLE
Putting on mesons releases parallax space

### ISSUE THREAD

**Issue by Razharas** [tgstation/tgstation#23179]
![image](http://i.imgur.com/o9Lwfam.gif)

**Comment by Razharas** [comment]
@MrStonedOne

**Comment by XDTM** [comment]
So powerful they see through the floor

**Comment by Razharas** [comment]
I CAN SEE FOREVER

**Comment by AnturK** [comment]
10/10 bug

**Comment by optimumtact** [comment]
He's SEEING THROUGH THE REALITY DISTORTION FIELD, CALL IN THE ELIMINATORS

**Comment by MrPerson** [comment]
I'll fix this later.

This is almost a feature though if you think about it. Mesons let you see through walls and now they let you see through floors too.

**Comment by ChemicalRascal** [comment]
Eugh, please no. Being able to see things while wearing mesons is a balance change.

**Comment by callanrocks** [comment]
This should be the emag meson effect tbh.

**Comment by MrStonedOne** [comment]
This doesn't happen when i tested.

**Comment by Cyberboss** [comment]
BYOND issue

**Comment by Razharas** [comment]
Latest beta fixed this
