### ISSUE TITLE
cargo shuttle occassionally not giving credit for tech disks thrown onto the shuttle floor

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#23188]
Put combat 7 tech disk on shuttle just loose. only item ON the shuttle. definitely had combat 7 on it, I put it on the disk myself, Had not previously sold ANY tech disks. Didn't get any credits for it.

**Comment by XDTM** [comment]
I think only stuff in crates gets sold

**Comment by vcordie** [comment]
why?

**Comment by vcordie** [comment]
wrong button

**Comment by ma44** [comment]
It doesn't matter if it's in a crate or not, as long as it's on the floor or somewhere in the cargo shuttle, it will be sold

Source: me exporting cash

**Comment by vcordie** [comment]
well, it fails to work for tech disks

**Comment by SgtxRootbeer** [comment]
Were the doors left open? The disks could have gotten sucked out.

**Comment by kriskog** [comment]
Tech disks can no longer be sold.
