### ISSUE TITLE
Post-nuke leaves screen too big

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23189]
![image](https://cloud.githubusercontent.com/assets/609465/22168392/3602e2ae-df64-11e6-8f83-cd027629645e.png)

You can see that the view range is bigger than the HUD.

**Comment by Mervill** [comment]
This miiiight be a duplicate of an Issue @WJohn posted a while back

**Comment by PKPenguin321** [comment]
Yeah this bug is ancient, I'm almost sure it's been reported before

**Comment by callanrocks** [comment]
Its been around literally forever but I don't think anybodies ever bothered to fix this since the round ends a few seconds later anyway.

**Comment by Kromgar** [comment]
Coiax is gonna add the station entirely getting blown up by nuke for funsies which is why hes trying to get this fixed

**Comment by Cyberboss** [comment]
No, that's me #22586

**Comment by Cyberboss** [comment]
WE DON'T LOOK THE SAME DAMMIT!!!

**Comment by Cyberboss** [comment]
might have something to do with this line maybe? https://github.com/Cyberboss/tgstation/blob/5f0b403b47561e7a0dd1c940aaf8828abded6dae/code/controllers/subsystem/ticker.dm#L231

Disclaimer: I don't understand screen code

**Comment by coiax** [comment]
why are people confusing us? because our avatars are blue?

**Comment by PKPenguin321** [comment]
Yes and your names start with c

**Comment by Cyberboss** [comment]
>Not even same case

**Comment by Kromgar** [comment]
You blues all look the same to me.

**Comment by Cyberboss** [comment]
This is @coiax's image: ![](http://www.allgeek.tv/wp-content/uploads/2010/Eve-Huge.jpg)
This is my image: ![quantum_space_617](https://cloud.githubusercontent.com/assets/8171642/22178353/e3ec9ae8-e001-11e6-8181-d66a23bc7672.jpg)

How can you not tell the difference?

**Comment by XDTM** [comment]
That's two images of a blue planet coiax

**Comment by coiax** [comment]
XDTM, you don't even have a gravatar

**Comment by MrPerson** [comment]
@Cyberboss Try changing that screen_loc="1,0" to screen_loc="1,1" and see if the problem goes away.

**Comment by Cyberboss** [comment]
@XDTM REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Kromgar** [comment]
Calm down Coiax

**Comment by XDTM** [comment]
I joined the blue tide

**Comment by Kromgar** [comment]
We are one we are many

**Comment by Cyberboss** [comment]
...

**Comment by Kromgar** [comment]
All shall join the blue tide

**Comment by coiax** [comment]
Wow this is a meme now?

**Comment by Cyberboss** [comment]
@coiax Just turn it around on them wherever you see them

**Comment by Kromgar** [comment]
I will XDTM

**Comment by WJohn** [comment]
Yep, this is a dupe of #8171

Also recently to further add to this: Ghost view range is a thing now, and if you have your screen set to stretch-to-fit, you can momentarily gain extra tile vision as your screen is enlarged to roughly 10 tiles.

I'll close the other issue, but this one IS from mid 2015.
