### ISSUE TITLE
atv+space lube

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#23183]
When you're on other vehicles, you're incapable of slipping on space lube. when you're on the atv, you still slip on space lube.

**Comment by Militaires** [comment]
this bug was active with janicarts before i believe

**Comment by jughu** [comment]
What part of all terrain vehicle dont you understand?

**Comment by WJohn** [comment]
Yup, driving over space lube with a janicart will cause you to slip and fall off, even if water and banana peels have no effect.

**Comment by kriskog** [comment]
Same as  #23558
