### ISSUE TITLE
Scalpel has a low success  chance in surgery

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23193]
Context:  Final step of organ manipulation targeting the head.

You begin to make an incision in Suzuka Nakamoto's head...
You screw up!
Braxton Cherry has pinched Suzuka Nakamoto in the right arm with the hemostat!
[Common] Kolton Rockafeller says, "He tried."
[Common] John ''Totally-Human'' Smith says, "But that's not fun"
[Common] Brenden Priebe says, "Fucking Centcomm."
You begin to make an incision in Suzuka Nakamoto's head...
You screw up!
[Common] Jacqueline Grenouilles exclaims, "Thanks Keeeeeeeeeeee....Centcom!"
You begin to make an incision in Suzuka Nakamoto's head...
[Common] Donald Sanders says, "Thanks centcomm"
You screw up!
You begin to make an incision in Suzuka Nakamoto's head...
You screw up!
You begin to make an incision in Suzuka Nakamoto's head...
[Common] John ''Totally-Human'' Smith says, "Well the HOS is arresting me like a faggot"
[Common] Dark Efencee says, "Why is centcomm so autistic"
You screw up!
You begin to make an incision in Suzuka Nakamoto's head...
[Common] Dick Gumshue says, "THE NATIONS WAR STAR- Oh..."
You screw up!
You begin to make an incision in Suzuka Nakamoto's head...
Suzuka Nakamoto seizes up and falls limp, her eyes dead and lifeless...
[Common] Troubled Steve says, "Ai can you inform sec that i found a redsuit"
You screw up!
You begin to make an incision in Suzuka Nakamoto's head...
You succeed.

**Comment by erwgd** [comment]
looks like tgstation/tgstation/pull/22656 causes this.

**Comment by KorPhaeron** [comment]
@Core0verload
