### ISSUE TITLE
Locker + Soap = stunlock everyone inside

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#23197]
Open a locker with soap and a mob inside and they instaslip.

**Comment by Cyberboss** [comment]
FEATURE!!!!

Also literally no way to fix this due to how atom slips work

**Comment by ChangelingRain** [comment]
Well there IS a way you can just remove mobs from the locker first, then everything else

**Comment by Cyberboss** [comment]
Literally no one but clowns/mimes do this. Don't take it from me TT

**Comment by PKPenguin321** [comment]
One time I teleported from the wizard den as a wizard to the captains office and landed on the soap in his bathroom and slipped

**Comment by XDTM** [comment]
Maybe a fix would be to not call Entered on forceMove if the turf is the same

**Comment by Cyberboss** [comment]
That's not the issue, Entered gets called because of loc changes.

**Comment by Tacolizard** [comment]
@PKPenguin321 cool story

**Comment by PKPenguin321** [comment]
Thanks

**Comment by XDTM** [comment]
@Cyberboss, as far as i could see we only check if the loc is the same, not the turf. It should probably check the get_turf() instead.

**Comment by Cyberboss** [comment]
That changes how Entered/forceMove works fundamentally. Tons of shit expects Entered to be called even if the turn is the same. E.g. picking up something on the same tile as you calls Entered for your inventory

**Comment by Iatots** [comment]
It was possible to rest, open the locker, then get up and not slip.
Some funny guy patched that out in the last couple days.

**Comment by kevinz000** [comment]
ok my salt is over it's no longer a bug
