### ISSUE TITLE
Shuttle docking sound is a few seconds earlier than the actual dock.

### ISSUE THREAD

**Issue by lzimann** [tgstation/tgstation#23218]
Probably caused by the addtimer refactor and threw the timing a bit off.

**Comment by Cyberboss** [comment]
Nooo, I think this has always been a thing

**Comment by lzimann** [comment]
Even if it has, it feels really weird now(never noticed before). The sound pretty much plays fully before shuttle actually docking.

**Comment by MrStonedOne** [comment]
the launch/take off, or the slowdown?

**Comment by Cyberboss** [comment]
The docking at centcomm

**Comment by MrStonedOne** [comment]
That doesn't even use addtimer()

**Comment by Cyberboss** [comment]
The sound just needs to be played after whatever causes the lag spike when
the shuttle docks.

**Comment by MrStonedOne** [comment]
I'll take a look at this. I've been meaning to make the dock/ign stuff use client_time anyways so we can sync that up right real and proper
