### ISSUE TITLE
Wanted posters can be created for the AI, resulting in no sprite

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#23228]
more specifically, the wanted poster has a sprite, but there's no overlay photo obviously

**Comment by Anonmare** [comment]
Feature

**Comment by SpaceManiac** [comment]
@Cyberboss Can't figure out how to print the wanted poster in the first place.

**Comment by Cyberboss** [comment]
You use the computer in the brig

**Comment by SpaceManiac** [comment]
The AI doesn't receive a security record so there's nothing to print.
