### ISSUE TITLE
EXTREME MONKEY CASCADE 

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#23223]
http://i.imgur.com/TYZCnHD.mp4

STEP 1: ACQUIRE MONKEYS OR MONKEY CUBES
STEP 2: ~~SEIZE THE MEANS OF PRODUCTION~~
STEP 3: PUT THEM ALL UP IN ONE PLACE.

DONE.

OPTIONAL: GIVE THEM ITEMS FOR MORE SPAM.
OPTIONAL: AGITATE THEM SOMEHOW TO MAKE THEM MOVE AROUND MORE.

**Comment by francinum** [comment]
This is entirely a feature, and entirely your fault.

**Comment by AnturK** [comment]
^
