### ISSUE TITLE
PAIS ARE FUCKING HARD TO STOP

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#23224]
i know people say ion gun but i mean those things dont even get fucking stunned i blame mekhi there was a PAI in a emagged janibot this round i destroyed the janibot it kept runnin runnin and runnin i tried to stun it with a baton but it didnt even fucking stop I MEAN DRONES CAN BE STUNNED WHY CANT PAI'S???

**Comment by dannno** [comment]
pAIs can hide in vents and be functionally untouchable and harass certain captains for the entire round and hurt their feelings

**Comment by jughu** [comment]
I mean them being in vents wont acid me when they are inside a janibot and escape too when destroyed and basically can tank the damage and crawl in a vent

**Comment by AnturK** [comment]
Add pAI's to robot control for remote termination.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm not sure if this was fixed but pAI's could just morph in and out of a hologram to avoid being acided by aliens.

also pais being mobile was a mistake, but meh.

**Comment by kevinz000** [comment]
someone go put pai killswitches on robotic control that require someone with a robotics ID to stop
kthx

**Comment by kevinz000** [comment]
alternatively jughu can get good and use a taser but I think option 1 is more well liked.

**Comment by jughu** [comment]
If a baton doesnt stun it why would a taser work?

**Comment by kilkun** [comment]
just examine the pAI to find its master and laser them so the pAI has to mope about it

**Comment by kevinz000** [comment]
yeah jughu get good also the ventcrawling kill pr fixes this.

**Comment by jughu** [comment]
No it doesnt

**Comment by PKPenguin321** [comment]
Yeah this isn't really fixed, at least make EMPs affect them or make them slower or something.

**Comment by Armhulen** [comment]
Make transforming something a human can toggle, not the pai itself.

**Comment by jughu** [comment]
@armhulen that isnt helping its auctally the part of GETTING the ai out of his mobile

**Comment by dannno** [comment]
I get that nu-pAI is your baby, Kev, but for christ sake

they SUCK dude.

**Comment by kevinz000** [comment]
@lzimann not an issue they're nerfed to uselessness

**Comment by PKPenguin321** [comment]
Make them layer under humans to stop bodyblocking
