### ISSUE TITLE
Gas Filter wrong direction.

### ISSUE THREAD

**Issue by Hanador** [tgstation/tgstation#23237]
Started with a West South East pipe
Right clicked and flipped pipe (East North West)
Wrenched pipe and it came out like this facing the wrong direction.

![prefix hazard quebec 2017-01-21 183951](https://cloud.githubusercontent.com/assets/8175582/22179461/7bf5481a-e009-11e6-8c38-641e30fe39eb.png)
![prefix hazard quebec 2017-01-21 184001](https://cloud.githubusercontent.com/assets/8175582/22179462/7d31ff3e-e009-11e6-8f92-286cf5cfeab1.png)

**Comment by jughu** [comment]
Yeah its definitly missing some directions the gas can be filtered on which i think causes this since theres no proper direction to go into it when flipped

**Comment by duncathan** [comment]
will investigate

**Comment by duncathan** [comment]
dupe of another issue with the atmos label
