### ISSUE TITLE
Robot factories and AI sync

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#23234]
A robot factory built by a malf AI can shit out borgs that are either not synced if it's dead, or synced to another AI if it's not the AI at the top of the list.

**Comment by ChangelingRain** [comment]
It's supposed to sync to the AI with the least borgs.... And it does so perfectly

**Comment by lzimann** [comment]
So.. is this intended or what?

**Comment by kevinz000** [comment]
I hope this isn't intended lol...

**Comment by CPTANT** [comment]
@ChangelingRain 

That's pretty stupid, they should obviously sync to the AI that put down the borger.

**Comment by Anonmare** [comment]
@ChangelingRain That sounds like a bug. Considering how expensive a robo factory is and removes your shunting ability it really should only benefit the AI who placed it only.
