### ISSUE TITLE
Swarmers cant eat brass

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#23240]
![image](https://cloud.githubusercontent.com/assets/6778786/22179901/270c0e7c-e02e-11e6-81df-f4810b89a295.png)

**Comment by bgobandit** [comment]
swarmers can only eat things with metal (i.e. iron) in it

**Comment by ChangelingRain** [comment]
Brass is Fucking Magic, it's formed entirely out of 250W of Pure Energy per sheet.
