### ISSUE TITLE
Insulated gloves no longer protect from light bulbs

### ISSUE THREAD

**Issue by CPTANT** [tgstation/tgstation#23244]
Trying to remove a lightbulb while wearing insulated gloves burns your hands.

Which is super stupid since lighting is electrical work and if this is a feature it would mean engineers have to constantly juggle between two types of gloves while working on lighting.

**Comment by PKPenguin321** [comment]
Not an issue, they are not fireproof, black gloves are.

**Comment by lzimann** [comment]
This is intended. Plus lights generate heat(have you ever touched a light bulb?) which is only blocked by the black gloves.

**Comment by CPTANT** [comment]
What, that's fucking retarded.  INSULATED GLOVES, for working with ELECTRICAL systems. Like I said engineers not being able to replace a simple lightbulb with their insulated gloves is super stupid.

What PR changed this?

**Comment by PKPenguin321** [comment]
It's been like this as long as I can even remember.

**Comment by lzimann** [comment]
You are not getting shocked touching a lamp, you are getting burned by the heat.
