### ISSUE TITLE
Items keep flickering.

### ISSUE THREAD

**Issue by ShadowDimentio** [tgstation/tgstation#23267]
Someone fucked up the item layers so now doors are appearing under firelocks and stacked items constantly flicker on top of each other. Fix.

**Comment by Cyberboss** [comment]
The fuck caused this?

**Comment by Cyberboss** [comment]
Update BYOND and report back

**Comment by Cyberboss** [comment]
Confirmed to be happening on 510. Tag as BYOND issue

**Comment by Cyberboss** [comment]
Not happening anymore @lzimann
