### ISSUE TITLE
Orion Trail Realism

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#23270]
Allows for infinite eshields and C-20Rs with preloaded electronic firing pins.

**Comment by jughu** [comment]
With a high risk of getting instantly killed plus you have to auctally defeat the opratives to get the stuff too!

**Comment by GunHog** [comment]
Not an issue!

**Comment by lzimann** [comment]
Unless I'm mistaken, this is not a bug. Use the forums for balance discussions.
