### ISSUE TITLE
pAIs running into field generators might cause a server crash

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#23290]
uh oh
![sbbgutl](https://cloud.githubusercontent.com/assets/3886584/22223741/02de9594-e18a-11e6-9c3a-9f24db9dd166.png)

**Comment by PKPenguin321** [comment]
Remove mekhi remove pAI fox memes

**Comment by ExcessiveUseOfCobblestone** [comment]
good feature

**Comment by RandomMarine** [comment]
Walking pAIs were a mistake.

**Comment by Kromgar** [comment]
Mekhi was a mistake
