### ISSUE TITLE
EMPing a Cleanbot with a pAI inside of it doesn't stun it

### ISSUE THREAD

**Issue by Emilc4h** [tgstation/tgstation#23306]
A pAI inserted into a Cleanbot can keep moving once it's been EMPed. It gains the red light to show it's been EMPed, but it doesn't stun it or anything like that.

Probably happens to the other types of bots you can put pAIs into.

**Comment by kevinz000** [comment]
god fucking damnit well wasn't me.

**Comment by Militaires** [comment]
actually it prevents it from operating eg stunning, spraying acid or cleaning

**Comment by jughu** [comment]
@militaires but whats the point anyways if it can move away from you when emped and activate themself anyways i dont see beepsky doing this when emped
