### ISSUE TITLE
No-Drop Implant fails to release weapon once it's disabled

### ISSUE THREAD

**Issue by SweaterKittens** [tgstation/tgstation#23305]
Captain ahelped becuase they couldn't drop their weapon even after they disabled their no-drop implant. 

![](http://i.imgur.com/4dS4F6l.png)

What should happen: The weapon should be able to be placed into a backpack, dropped, thrown, or placed into a recharger once the implant is disabled.

**Comment by lzimann** [comment]
I think the problem is that it is never actually making the item non-droppable in the first place.

**Comment by XDTM** [comment]
Fun fact: all the captain needed to do was toggle it on and off again.

**Comment by SweaterKittens** [comment]
I'm certain that they tried that. Also you can see in the screencap that they tried to turn it on then off, to no avail.

**Comment by Armhulen** [comment]
guess that captain needs to get a grip

**Comment by XDTM** [comment]
Until it gets fixed, only the "your hands relax..." will toggle the NODROP, as i could see in testing.
