### ISSUE TITLE
If a singularity eats a supermatter while the supermatter is in a crate it won't go supersingulo

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#23301]
See title

**Comment by Cyberboss** [comment]
Something something recursive atom contents...

**Comment by MrStonedOne** [comment]
Make containers drop contents on sing_act, then the sing can just gobble gobble gobble =P

**Comment by bgobandit** [comment]
This is an issue with ex_act as well, containers used to delete making their contents available but now the whole thing goes. (Swarmers are the place where it is most visible)
