### ISSUE TITLE
Where are the IC commands stored and how can I add new ones?

### ISSUE THREAD

**Issue by gt33** [tgstation/tgstation#23315]
And how do I play a sound at a player's location?

**Comment by francinum** [comment]
http://qchat.rizon.net/?channels=coderbus

**Comment by gt33** [comment]
can't right now

**Comment by PKPenguin321** [comment]
Post in the coding section of the forums then

**Comment by Cyberboss** [comment]
@lzimann

**Comment by lzimann** [comment]
Please don't open issues that are questions like this. Use our forums/irc for that.
