### ISSUE TITLE
Some overlays arnt deleting properly

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#23316]
![Imgur](http://i.imgur.com/8zcFO1G.png)

the health symbols and the point were around for at least 10 min

**Comment by XDTM** [comment]
maybe related to the pooling pr? all these overlays used PoolOrNew

**Comment by ChangelingRain** [comment]
The timer system might be getting overloaded for some reason, which would prevent these from disappearing.

**Comment by MrStonedOne** [comment]
Same issue as [23070]

SStimer is getting overloaded because a bug is causing timers to not qdel. (and i'm almost pretty sure its a byond bug because i can't see how this could be happening)

**Comment by xxalpha** [comment]
Why pooling still beeing used, I thought it didn't really help.

**Comment by lzimann** [comment]
Dupe of #23070
