### ISSUE TITLE
scatter shot is the best in the list of very very shitty ballistic mech weapons

### ISSUE THREAD

**Issue by vcordie** [tgstation/tgstation#23319]
4 pellets, each does 25 brute and 65 stamina. That's quite decent, if it was a handheld weapon. As a mech weapon, that seems....meh. not that great. the stamina damage is fucking NICE, but the mechs should be a real goddamn threat. I'd up number of pellets to 5 or 6 but that's just me.

**Comment by dannno** [comment]
4 new "issues"
you're ruining everything the freeze did
