### ISSUE TITLE
hades carbine is hot garbage, literally

### ISSUE THREAD

**Issue by vcordie** [tgstation/tgstation#23317]
5 damage (not sure if burn or brute) per projectile, plus it lights you on fire ITS TERRIBLE. TERRRRIBLE. Terrible weapon. getting lit on fire is no an excuse for 5 FUCKING DAMAGE 5. 5? 5!?!? FIVEEEEEE? ARE YOU KIDDING ME.
replace with exosuit mounted flamethrower, because right now all it is is a shitter flamethrower, or change the projectile to the one that's still incid and does 20 damage a shot, which it probably was supposed to be but the coder mistook the wrong projectile.

**Comment by Emilc4h** [comment]
correct me if i'm wrong but isn't this a balance concern instead of a bug or issue

if it is then mention it in coding feedback or something

**Comment by vcordie** [comment]
balance issues are also handled here, the balance tag exists for a reason.

**Comment by KorPhaeron** [comment]
This might be a balance issue but it isn't a bug
