### ISSUE TITLE
No Frills TGUI Interfaces Still Feature Intense Lag

### ISSUE THREAD

**Issue by Surrealistik** [tgstation/tgstation#23313]
Per title.

This doesn't seem to work for circumventing the need to have IE11 as the lag for certain consoles remains intense (Chem Dispenser for example).

**Comment by ShadowDeath6** [comment]
tgui in general is lag intensive

**Comment by Surrealistik** [comment]
As in, there is a considerable delay that is recurring whenever there is any kind of refresh. It seems to obviate the point of No Frills which is apparently supposed to kill the offending elements that create the lag.

**Comment by kilkun** [comment]
kill tgui

bring back the black text, blue hyperlink interfaces of old.

**Comment by optimumtact** [comment]
what do you expect, it's a compatibility mode for a 16 year old browser, of course it's going to be extremely slow

**Comment by Incoming5643** [comment]
to be clear the no frills mode isn't supposed to kill lag, it's just supposed to make the ui compatible with legacy OS

That said regardless of your OS TGUI is slow to load and generally not great.

**Comment by Haevacht** [comment]
Not a bug. Kilkun just remake every interface we have, that can be your first project.

**Comment by Surrealistik** [comment]
Slow to load is pretty bad in SS13, especially on sanic gotta go fast paced servers. 

Honestly I'd prefer much less pretty interfaces if it meant superior performance; function over form.

**Comment by kilkun** [comment]
im not the one who ruined our interfaces with this hot garbage

**Comment by ShadowDeath6** [comment]
tbh every single argument I hear for tgui is "yeah but do you want to do ALL of it by yourself"
does anyone even like it or are they just not interesting in taking the task to do it?

**Comment by optimumtact** [comment]
pulls accepted, but must have the same quality of life for developers as tgui (centralised topic checks for distance and visibility - easy to manage streaming data updates)

**Comment by Niknakflak** [comment]
It's still slow, it still sucks and we are only on a train headed for more shit with tgui

**Comment by optimumtact** [comment]
[unsubscribe]

**Comment by Dennok** [comment]
I think now with new TGUI this no more issue?
@optimumtact

**Comment by optimumtact** [comment]
most likely
