### ISSUE TITLE
Unequipable hardsuit

### ISSUE THREAD

**Issue by kustridaren** [tgstation/tgstation#23310]
When i was trying to take off the hardsuit i still have it on even if I try to drop the suit. it also shows the suit on the floor and no suit in the suit slot. When i press once on the suit slot i grab the suit but it's invicibel. other players seem to see that i got a hardsuit on. I don't know how to reproduce this bug  sadly. I think it happen when i was trying to remove the suit by dragging the suit off while moving or something similiar.

Edit it appears to have fixed itself by somone removed the suit.

Edit 2 it appears to be back after equipping the hardsuit again.

**Comment by lzimann** [comment]
Caused by #22918, which is just testmerged.
