### ISSUE TITLE
AC2 mech weapon needs a bit of a buff

### ISSUE THREAD

**Issue by vcordie** [tgstation/tgstation#23318]
3 bullets each doing 20 damage isn't bad, but its 100% worse then the scattershot. scattershot is 4 pellets, 20 damage, 65 stamina. I'd bump it up to five bullets for the ac2 to be worthwhile.

**Comment by dannno** [comment]
Why don't you make a thread for all of these instead of making issues for things that aren't bugs and arguably aren't even issues

**Comment by vcordie** [comment]
I don't use the forums.

**Comment by dannno** [comment]
very good reasoning

**Comment by Kromgar** [comment]
Why don't you use the forums?

**Comment by Supermichael777** [comment]
no one uses the fourms

**Comment by PKPenguin321** [comment]
nice meme

**Comment by kevinz000** [comment]
Not an issue.

**Comment by KorPhaeron** [comment]
This might be a balance issue but it isn't a bug
