### ISSUE TITLE
X4/C4 can be attached to throwing stars

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#23324]
?!?!!??!!
How the hell are you throwing it with complete accuracy and having it embed if it's now a block of sharp C4?!
How the hell does that embed?!!

**Comment by Kromgar** [comment]
...  That's incredible.

Did somebody gib with this?

**Comment by kevinz000** [comment]
No but that's an instant kill for X4.

**Comment by PKPenguin321** [comment]
This was noted shortly after embedding was added and deemed a feature.

**Comment by Iamgoofball** [comment]
I don't see the problem here

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation/pull/1612

in case you want to fix it, we had the same issue

**Comment by KorPhaeron** [comment]
This might be a balance issue but it isn't a bug

**Comment by RemieRichards** [comment]
as the creator of tg embedding and throwing stars, feature.
