### ISSUE TITLE
Insane lag on TG station

### ISSUE THREAD

**Issue by Ignies** [tgstation/tgstation#23326]
**Problem:** 
Insane lag on TG servers after last (server) update. (24 January 2017)
**Server:** 
Both.
**Steps to reproduce:**
_lobby:_ Normal ping.
_In game:_ Near the station everything renders slower, disappears when i'm out of view, and reappears when i enter the area again, causing massive lag (2000 ms), on space, the ping goes back to normal since there isn't really anything to render except for the parallax, from 100 to 200 ms.

**Possible related stuff:** 
The only thing in the changelog close enough to cause this, is the fix for the starting lag.

**Comment by jughu** [comment]
Wasnt there a test merge active?

**Comment by Ignies** [comment]
No idea, but whatever is causing it, only affects a small portion of the player base and has something to do with the rendering of objects.

**Comment by Haevacht** [comment]
If this is an actual thing, whoever fucked with the nearspace areas for starlight last should look into it.

**Comment by Kromgar** [comment]
ITs been bad for the last several days constant lag at roundstart. One time i joined station was in perfect working condition no bombs or anything just horrendous lag

**Comment by Cyberboss** [comment]
@Ignies Report back if this happens again and list any testmerges that are going on

**Comment by Ignies** [comment]
@Cyberboss The problem is constant on my end, from 1000 to 3000 ms when near station tiles, normal ping between 100 and 200 ms when in space or in the lobby. As weird as it sounds.

**Comment by crvsindex** [comment]
it happen the same to me. https://gyazo.com/710994ad385174798068d31a1436eda5

**Comment by ExcessiveUseOfCobblestone** [comment]
@Ignies does this still occur

**Comment by Ignies** [comment]
@ExcessiveUseOfCobblestone yeah, still there.

**Comment by ExcessiveUseOfCobblestone** [comment]
I was told it was byond related so you may just have to hold out.

**Comment by MrStonedOne** [comment]
Found it.
![Traffic Graph](https://tgstation13.org/msoshit/traffic%20graph.PNG)

(note, for outgoing traffic, lower means more traffic).

That is exactly when I updated byond versions.

**Comment by Cyberboss** [comment]
B Y O N D
Y
O
N
D

**Comment by Ignies** [comment]
@MrStonedOne  Thank you, that indeed fixed it, hopefully they can find out what is causing this.

**Comment by Ignies** [comment]
Issue seems solved, thank you guys for everything, should i close it?

**Comment by MrStonedOne** [comment]
generally these things are closed when the byond bug is fixed byond side or we get to a point where we won't hit it.

because we will at some point have to update to a version that has the bug, and because downstreams might update to the latest beta for the server, this should stick around

**Comment by Cyberboss** [comment]
Lummox found the issue, this can be closed
