### ISSUE TITLE
Hallucinations crashing my game, permanent while dead

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#23338]
Just had a game where hallucinations crashed my game 3 times, and whenever I re-entered my corpse the hallucinations would continue indefinitely.

**Comment by BeeSting12** [comment]
Dupe of #22777 and #22565?

**Comment by Robustin** [comment]
Reopen the other crash is closed, we're losing tons of connections every time a ling does mindbreaker memes.
