### ISSUE TITLE
Janicart was unusable.

### ISSUE THREAD

**Issue by DoctorPork** [tgstation/tgstation#23331]
Problem Description: Player ahelped that the Janicart was unusable because it wouldnt let him mount it.

What did you expect to happen: The normal click and drag to buckle into/mount the janicart. 

What happened instead: When clicked and dragged onto the janicart it would move the player onto the cart but not mount it. I tried it and had the same result.

Why is this bad/What are the consequences: Janicart was unable to be used.
Edit: Upon further testing it also happens with the ATV.

Steps to reproduce the problem: The player joined the station, walked into their office, and tried to mount their cart. I spawned a new cart and tried to the same result.

Server: Sybil

Revision: 
Server revision compiled on: 2017-01-25
Test merge active of PR #23269 
Based off master commit 70689384f50ba91479a15ab15a95f8c947030622

**Comment by jughu** [comment]
Also happens with skateboard probaly also segway

**Comment by ExcessiveUseOfCobblestone** [comment]
@Militaires

**Comment by PKPenguin321** [comment]
something broke vehicle buckling cough cough the refactor by that one guy i think it was @Militaires

**Comment by kevinz000** [comment]
This is related to every single vehicle.

**Comment by Militaires** [comment]
dindu nuffin

**Comment by lzimann** [comment]
This got fixed already.
