### ISSUE TITLE
Hydroponics Plant Gene Modder Contains a null \ref

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#23346]
https://github.com/tgstation/tgstation/blob/master/code/modules/hydroponics/gene_modder.dm#L142

`gene=\ref[target]` will be null here, but since it's a `\ref`, it will fail silently with no runtimes generated.

**Comment by ArcaneMusic** [comment]
Could probably be closed with the removal of the DNA Modifier in botany.
