### ISSUE TITLE
Some things can't be seen with cameras

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#23342]
Read: Windows for one.
Also it's mob detection is a crappy text string but that's not a bug. Honk.

**Comment by PKPenguin321** [comment]
Can almost guarantee this is a dupe, it has been around since the dawn of time itself

Some things also have their rotation broken, such as crayon drawings

**Comment by kevinz000** [comment]
Hmmmm.....

**Comment by Cyberboss** [comment]
Dupe of #7092
