### ISSUE TITLE
Tcomms being down stops the use of the Syndicate channel

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23355]
What's the point of having a syndicate channel if it's reliant on the station's tcomms system

**Comment by RemieRichards** [comment]
extremely amusing, furthers the agenda that <i>nanotrasen are the ones who hired the syndicate!</i>

**Comment by Cyberboss** [comment]
It's kinda a lore question. Is station tcomms some sort of unbiased relay or do they explicitly handle NT comms. If it's the latter then the syndicate should get it's own tcomms at the nuke ops base.

**Comment by Hatfish** [comment]
Aren't syndie comms supposed to run off of the nuke op's ship?

**Comment by KingPhilipIII** [comment]
Well. From what I understand of telecommunication equipment, which isn't much to be honest, I think it hijacks NT's machinery to use it but its encrypted somewhere off station, presumably an outpost. 

With regards to Nuclear operatives, they have their own stuff for interception and communication.

**Comment by coiax** [comment]
Nuke ops use the same syndi encryption chips as regular tators.

**Comment by KingPhilipIII** [comment]
I know. I mean lore wise traitors use NT's equipment for communication but all Syndicate affiliates in the area utilize the same encrypted channel.

**Comment by Detective-Google** [comment]
No longer an issue (presumably since the syndicate channel is now handled on the ops ship?)
