### ISSUE TITLE
You can clean floors by crowbarring the floor tile

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23354]
If this is faster than the janitor with a mop, or someone with soap, then maybe something is wrong here.

**Comment by XDTM** [comment]
Not faster than a janitor with space cleaner. Maybe mopping speed should be buffed?

**Comment by Cyberboss** [comment]
Mopping is way too fucking slow tbqhfam

**Comment by Cyberboss** [comment]
Quite frankly, there's no way we're storing mess data in tile stacks so there's no way around this

**Comment by Cyberboss** [comment]
As I say that though....

**Comment by coiax** [comment]
Why not just have the mess be transfered to the plating

**Comment by XDTM** [comment]
stacking will definitely cause issues if you store stuff on tiles

**Comment by Saegrimr** [comment]
>Not faster than a janitor with space cleaner. Maybe mopping speed should be buffed?

You can thank Paprika.
https://github.com/tgstation/tgstation/pull/5427

**Comment by coiax** [comment]
This is no longer happening.
