### ISSUE TITLE
Necropolis bridge no longer protects from ash storms

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#23360]
See title.  Not sure if this is intended behavior.

**Comment by Kromgar** [comment]
The wish granter spawned on top of the Necropolis Bridge recently may be related

**Comment by PKPenguin321** [comment]
Doesn't seem like a bug to me. Why would the bridge be sheltered?

**Comment by Hatfish** [comment]
It's been a sheltered zone for as long as I can remember and nobody ever attempted to "fix" it.

**Comment by Hatfish** [comment]
Doesn't seem to be a bug, closing unless someone decides otherwise.
