### ISSUE TITLE
[Metastation] The field generators in Engineering Secure Storage are "welded to the floor" but not anchored

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23387]
I don't know if this is a map problem or just in general.

The field generators in Engineering Secure Storage are draggable and bumpable, but are apparently "welded to the floor". In order to actually anchor them, I had to unweld them, then wrench them, then weld them again.

**Comment by XDTM** [comment]
likely anchored through varediting but not set to the corresponding welding status.
