### ISSUE TITLE
Round stats are being saved inconsistently

### ISSUE THREAD

**Issue by nfreader** [tgstation/tgstation#23396]
Alright,

Right now, every round is at least saving a `round_end` time to the feedback database. Some rounds are getting a `round_start` and `game_mode` (+ other useful stats) saved, but I don't know why some rounds aren't getting that information saved.

Here's a round with "good" data: 
https://atlantaned.space/newSS13tools/stats/viewRound.php?round=65615

And one with insufficient data: 
https://atlantaned.space/newSS13tools/stats/viewRound.php?round=65624

And here's the raw data for that round (65624): 
https://gist.github.com/nfreader/b4aaf64efb58f78435d549feff3ace60

**Comment by lzimann** [comment]
Yea something is weird but I had no luck figuring out what is going on(probably something weird with the blackbox recorder).
The round_start feedback datum IS being generated, but it might not be querying properly. The issue might be more than one blackboxes spawning.

**Comment by AnturK** [comment]
https://github.com/tgstation/tgstation/blob/b7efc2cef43dbb88607b0cafc4f8bc8b2d7db9e3/_maps/RandomRuins/SpaceRuins/deepstorage.dmm#L3

...

**Comment by AnturK** [comment]
SEE THIS IS WHY MAKING STAT GATHERER PHYSICAL OBJECT IS RETARDED.
