### ISSUE TITLE
Pylons changing floor to cult floor causes air changes

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23391]
Often when I've been sitting in my blood cult base and then open the door, a bunch of stuff blows out, like the cult turfs are at slightly higher pressure?

**Comment by ChangelingRain** [comment]
the turf under the door lost all its air
have fun trying to fix this it's been around for ages

**Comment by PKPenguin321** [comment]
So is this a real bug or should it be closed because it's actually what @ChangelingRain described?

**Comment by ChangelingRain** [comment]
This is a real bug and it's what I described! Those aren't mutually exclusive!

**Comment by PKPenguin321** [comment]
Change the title to reflect air under the door being the issue rather than the cult thingy described in the OP then, reee

**Comment by Robustin** [comment]
Ironically this is now the worst way to confront this bug since the day this issue was opened cult turfs are now atmos-dense, so cult turfs are probably one of the only turfs that won't succumb to this bug.

**Comment by Nickkoranda** [comment]
Seems to be fixed
