### ISSUE TITLE
Infinite 1-bite custom kebabs by adding a custom burger to rods

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#23410]
Adding a custom burger to a rod will create a one bite kebab, which has the same sprite as a single rod, without either consuming the burger or part of its reagents.

Tested with a donut burger: control was 5 nutriment 2 sugar, test burger still retained the same amount after creating a dozen kebabs, eact containing at least .6u of nutriment. I say at least because there is some kind of cooldown between eating something and scanning yourself for reagents with a health scanner, so part of the bite could have been processed inbetween. Burger content was checked by grinding it up.

**Comment by Detective-Google** [comment]
Tested, still an issue

**Comment by Fikou** [comment]
you cant customize either kebabs or burgers anymore
