### ISSUE TITLE
type mismatch: cannot compare "fall" to 0

### ISSUE THREAD

**Issue by rainbowjose** [tgstation/tgstation#23414]
"fall" is not 0. Obliviously.
http://pastebin.com/7Qm7WuTW

**Comment by AnturK** [comment]
Would need full stacktrace, this can be literally any with variable time

**Comment by rainbowjose** [comment]
Full log
http://pastebin.com/c0sAAkUg

**Comment by vuonojenmustaturska** [comment]
Timers have been overhauled since this bug report was made, but the whole log is so full of absolute brokenness like missing files that figuring out if this was a real bug is probably impossible.
