### ISSUE TITLE
You can take decimal values of bluespace polycrystals

### ISSUE THREAD

**Issue by Mindustry** [tgstation/tgstation#23427]
If you alt+click refined bluespace polycrystals, you get a prompt to pick up an amount of sheets. You can use a decimal in this prompt and it will give you that amount, including less than one. See images.
This is particularly bad because you can easily get research levels high by just abusing stacks. Also free teleports. And lets be real, you probably shouldn't be able to take less than one of a thing from a stack.

![poly2](https://cloud.githubusercontent.com/assets/8491500/22399357/91b68966-e54f-11e6-9d09-25f41bd34192.png)
![poly3](https://cloud.githubusercontent.com/assets/8491500/22399359/93243bae-e54f-11e6-8bf0-4f3955d79a06.png)

**Comment by lzimann** [comment]
Probably true for any sheet type.
