### ISSUE TITLE
Carding the AI when it has the doomsday device active does not stop the doomsday device

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23429]
You have to actually wipe it. I just tested this.

**Comment by GunHog** [comment]
Reminder to the guy fixing this to avoid hurting mech based transfers. Stealing mechs and using them to hide/fight during the timer is intended.

**Comment by PKPenguin321** [comment]
Sounds like a feature

**Comment by ShizCalev** [comment]
Can it actually detonate the device while carded though? From what I saw on the server the other day, it just kept counting down since the AI was still alive.

**Comment by alexkar598** [comment]
Is the ai doomsday device a machine to make the on board nuke explode or the doomsday device is actually the bomb?
