### ISSUE TITLE
Shrinking with the resize var is broken?

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#23422]
- Get manlet genetics power
- Grow instead of shrink

- One time PaS var edited someone too big on accident and when they tried to shrink them by editing resize car to be between 0 and 1 it just kept making them bigger until they covered the entire map

**Comment by Haevacht** [comment]
Did he try negative values or?

**Comment by Poojawa** [comment]
You shrink people by putting in decimal values. You can also flip them via -1

**Comment by PKPenguin321** [comment]
Doesn't seem to still be happening
