### ISSUE TITLE
Incorrect area name on DeltaStation

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23423]
> Central Command Higher Dimensionsal Affairs
> 
> 
> Figments from an eldritch god are being summoned by Levi Crypt into **Library** from an unknown dimension. Disrupt the ritual at all costs!

![image](https://cloud.githubusercontent.com/assets/609465/22398997/c82b6922-e58a-11e6-9a3c-17acdba5a488.png)

That is not the Library. That is the ABANDONED LIBRARY.

**Comment by Tofa01** [comment]
Accidental reference (Second one) sorry,

**Comment by PKPenguin321** [comment]
Can I just say how pretty the lighting is in that image in the OP
