### ISSUE TITLE
lesser ash drake regen is broke

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#23435]
Gibbing someone regenerates your health, but the limbs hitting you takes it away and then makes you go down even more.
EDIT: Yes, this is a staff of change ash drake.

**Comment by Magikarpet** [comment]
I'm pretty sure staff of change drakes are where the issue comes from, and not lesser drakes themselves. Unless the staff of change makes you a lesser drake?

**Comment by Mindustry** [comment]
I think it's staff of change, if I recall correctly lesser ash drakes can't swoop.

**Comment by KorPhaeron** [comment]
alt+click to swoop

**Comment by Kromgar** [comment]
As an ashligger ive been getting hit by the exloding legs and taking damage its annoying as fuck

**Comment by Kromgar** [comment]
Staff of change makes you a lesser drake

**Comment by ChangelingRain** [comment]
no this is the same issue as the ashwalker tendril dying to legs

**Comment by KorPhaeron** [comment]
Surely eating a body and healing 100 damage would outweigh the limbs though unless I broke something

**Comment by BeeSting12** [comment]
Yeah, this is a staff of change lesser drake, although I wouldn't think there's any difference between a regular lesser drake and staff of change lesser drake
