### ISSUE TITLE
Add handle bars throughout the ship

### ISSUE THREAD

**Issue by tylerh95** [tgstation/tgstation#23441]
This came from an idea put out in OOC. Essentially, place "handle bars" around the ship that are on the wall. A player should be able to "grab on" similar to sitting in a chair. This would prevent you from falling during a FTL jump.

**Comment by Armhulen** [comment]
feature request tag

**Comment by tylerh95** [comment]
PR'd this to the wrong code base. top kek

**Comment by PKPenguin321** [comment]
it's a decent idea though!
