### ISSUE TITLE
The room names on Delta/Meta are utterly inaccurate

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#23445]
>Room labeled engimaint on Meta
>Its in fucking medbay maint on the opposite side of the map

>Room labeled library on Delta
>Its the fucking abandoned library in maint

**Comment by Kromgar** [comment]
>Makes quality rooms
>Slaps random names on shit

**Comment by ChangelingRain** [comment]
It's less inaccurate and more "mappers that don't understand how areas work"
If you go into the map editor for delta, you'll see them all labelled properly; except they're the same type, and you can only have one instance of an area, so only one of the area names is saved.

That, and cult doesn't use the right var for area announcing~

**Comment by Tofa01** [comment]
@ChangelingRain Are you working on this? If not i can go through and fix the area names and make new areas for map makers who have var edited areas.

**Comment by ChangelingRain** [comment]
I'm not working on it but I do know what's wrong

**Comment by Robustin** [comment]
I only steal code from other modes, thats how Gang War announced its dominator location and that got some thorough vetting... but if changing a var makes it more accurate then by all means go for it.

**Comment by KorPhaeron** [comment]
Dupe
