### ISSUE TITLE
Cryotube remembers its last inhabitant, doesn't realise that they've left

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#23460]
Long story short, playing on Sybil, found that both the cryotubes weren't updating after their last occupant was injected. With a bit of testing, it was found that...

- They'd kept a memory of the last occupant's health
- Ejecting someone showed the little bit of burn damage applied to the person leaving the tube
- This didn't stop the tubes from being used
- They'd copy the next inhabitant when re-used.

**Comment by Cyberboss** [comment]
That's a GC bug waiting to happen.
