### ISSUE TITLE
Delta Station - Fore Port Solar array shouldn't require Atmos access

### ISSUE THREAD

**Issue by ElfLeaderMike** [tgstation/tgstation#23476]
Server revision compiled on: 2017-01-29
Test merge active of PR #23385 
Test merge active of PR #23260 
Test merge active of PR #23455 
Based off master commit 6ff43daaf623909275c7872531d236d78e69a25e 

Whats wrong: Only Atmos can access the Fore Port Solar array on Delta station. I don't think Atmos sets up solars. At the very least the airlocks going into the access area should be accessible by engineering for setup (coming in from the outside).

**Comment by jughu** [comment]
Is this the one solar next to atmos? Because i think that one is intended so atmos can edit pipes

**Comment by coiax** [comment]
Make it any access, engineering + atmos

**Comment by Cyberboss** [comment]
yeah, sounds like a req_access should be a req_one_access
