### ISSUE TITLE
Crate contents are unharmed when a crate is burned by lava

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#23473]
See title

**Comment by jughu** [comment]
Dont worry im nerfing cargo bigtime :joy:

**Comment by nfreader** [comment]
Definitely still a thing. Someone fix this!

**Comment by spessbandit** [comment]
this seems to be fixed? @PKPenguin321

**Comment by PKPenguin321** [comment]
Did you test it personally?
