### ISSUE TITLE
[Bug] Welding Goggles gave Nightvision when toggles up.

### ISSUE THREAD

**Issue by DoctorPork** [tgstation/tgstation#23475]
Problem Description: Was notified by a player they got nightvision from welding goggles on Delta station
What did you expect to happen: When toggled up you can see normally while wearing the goggles

What happened instead: They actually gave nightvision.

Why is this bad/What are the consequences: Free nightvision with every pair of goggles, shenanigans for sure.

Steps to reproduce the problem: I went human and tested it and it totally works.

Server: Bagil

Server revision compiled on: 2017-01-29
Test merge active of PR #23385 
Test merge active of PR #23260 
Test merge active of PR #23455 
Based off master commit 6ff43daaf623909275c7872531d236d78e69a25e

**Comment by MrStonedOne** [comment]
Anything to do with vision or graphics should include info about the client's byond version, os, and gpu.

**Comment by Arianya** [comment]
Can confirm I've had this happen too.

BYOND version is latest beta (don't have access to specific v. number at the moment
OS is Windows 10 (again, no specific v. number)
GPU is EVGA GeForce GTX 1080 FTW GAMING ACX 3.0

**Comment by jughu** [comment]
I can confirm it too when i messed around goggles
