### ISSUE TITLE
Slimes & Radiation = ???

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#23483]
In a round just past, as an adult sentient slime, I was sitting near the supermatter shard on the SM shuttle for about a minute or more before I suddenly stopped being able to move. After a couple of seconds I split off into a number of smaller slimes - one of which was me, I saw when I spoke - and a few seconds after that, I died.

All the while, my damage indicator was at 100%. Do slimes & radiation not have an interaction properly written in?

Probably relevant note: I had tried, and failed due to lack of energy, to split about five to ten minutes before.

**Comment by KorPhaeron** [comment]
Simple animals are not hit by rads

**Comment by AnonymousNow** [comment]
Then how does this explain the strange behaviour I was undergoing?
