### ISSUE TITLE
Ratvarian shenanigans-Trendy Brass Eyewear

### ISSUE THREAD

**Issue by KingPhilipIII** [tgstation/tgstation#23495]
Right, so a few days ago( I neglected to make the issue earlier) there was a clockwork cult about the station. While doing my duty as a greytider I wandered into disposals and found a pair of spectacles, made of brass, sitting in front of the recycler. 

Rather than scream cult as any self respecting Nanotrasen employee should have, I thought it would be fun to see what happens upon wearing these antique eye-assisting tools. Much to my surprise, I was not struck blind by Ratvar. 

When the glasses were pushed up, as one does to avoid going blind in ordinary circumstances, I was granted X-ray vision, without the night vision however. I took them off just to check, put them on. Still worked. When flipping them down I was rewarded with blindness as anticipated. Upon giving them to my fellow greytider they experienced the same problem. 

Joan, Ratvar isn't very picky about who models his brand of fashion it seems. Pretty big problem if you ask me.

**Comment by ShadowDeath6** [comment]
>pushes glasses up essentially removing them
gets xray vision

**Comment by KingPhilipIII** [comment]
Yes that would be the short version. Having the glasses pushed up to avoid eye damage (ordinarily) gave me X-ray. 

Removing the glasses from my head took away the X-ray, but it was returned when I re-equipped them.

Way to remove the elements of story telling Shadow. You do my art a disservice.

**Comment by ShadowDeath6** [comment]
it's what I'm here for
