### ISSUE TITLE
Field generators can be damaged by thrown objects

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#23497]
>Dumbshit engineers leave loose objects in the field area
>They start bouncing off the field generators
>Field generators lose 10 integrity from 500 per second
>OH BOY!

**Comment by PKPenguin321** [comment]
Feature. Don't leave the shit in the thing.

**Comment by Cyberboss** [comment]
Actual feature, unlike the sparks thing

**Comment by AnturK** [comment]
Indeed
