### ISSUE TITLE
Decals on Deltastation

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23515]
![image](https://cloud.githubusercontent.com/assets/609465/22443629/7fd54b6c-e737-11e6-89f9-57d1dc01450e.png)

This is the Virology airlock. @AnturK

**Comment by Tofa01** [comment]
I may not have the power to self assign this to myself but this is 24 days too long i will be going through soon and fixing all of these.

![bar](https://cloud.githubusercontent.com/assets/24999255/23294773/370cc21e-fac1-11e6-835d-fc5d44593101.PNG)
_This bar needs to be full for probably myself and myself only as i am the only one who is more then likely bothered by it._

**Comment by AnturK** [comment]
Whoops , forgot about this one. I can fix it when i get home today or leave it to you if you're already changing delta.

**Comment by Tofa01** [comment]
Its not that hard of a fix i am alright doing it unless you really want to do it, i am just waiting until my other Delta PR gets merged so i can do quickly do this i'd rather keep that one atomic.
