### ISSUE TITLE
Doing basically anything to an item as a drone puts it inside of you

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#23520]
this is probably @Cyberboss 's fault

**Comment by Cyberboss** [comment]
Idk, unless there's something fucky about how done bags work it should be
exactly the same as everything else

**Comment by Cyberboss** [comment]
In regards to the unequipping refactor

**Comment by ChangelingRain** [comment]
It's also trying to put things in your box, in your storage, or dropping them.

**Comment by AnonymousNow** [comment]
Can confirm.

**Comment by Cyberboss** [comment]
![1io7io](https://cloud.githubusercontent.com/assets/8171642/22452680/f7864116-e746-11e6-917d-2bce2a73f486.jpg)

**Comment by Incoming5643** [comment]
gonna guess it's hands on a non carbon thing

**Comment by rainbowjose** [comment]
Can confirm
