### ISSUE TITLE
Upgraded sleepers don't work

### ISSUE THREAD

**Issue by TribeOfBeavers** [tgstation/tgstation#23534]
Test merge active of PR #23493 
Test merge active of PR #23494 

When a sleeper is upgraded only the base chems work, clicking on the buttons of anything below kelotane does nothing.

**Comment by jughu** [comment]
Yeah i can confirm this by trying to inject ant toxin in  person didnt work

**Comment by AnturK** [comment]
Caused by #23191 ?

**Comment by RemieRichards** [comment]
Yeah, needs a ```reset_scrambled_chems()``` in ```RefreshParts()```, until then, simply upgrade machines the old way (dismantle and replace components)
