### ISSUE TITLE
[Boxstation] Strange lighting in the chapel after a plasma fire

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#23532]
![see?](http://puu.sh/tHPju/f05fe0ec1f.jpg)

Notice how all the tiles that arent pitch black are the ones that usually have carpet on them, while the pitch black ones are all the regular tiles.

**Comment by MrPerson** [comment]
oh jeez more changeturf bullshit yayyyyyy

**Comment by Cyberboss** [comment]
oldlighting

@lzimann
