### ISSUE TITLE
Autoprocess does nothing.

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#23535]
Autoprocess doesn't automatically scan anyone in the scanner, and I'm fairly certain it doesn't automatically clone people. Normal behaviour is automatic on both.

**Comment by kevinz000** [comment]
@coiax

**Comment by Cyberboss** [comment]
FUCK YOU @kevinz000

**Comment by coiax** [comment]
topkek

**Comment by XDTM** [comment]
honk

**Comment by Cyberboss** [comment]
This is closable @lzimann
