### ISSUE TITLE
Mc crashing

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#23536]
Test merge active of PR #23493 
Test merge active of PR #23494 

In a number of rounds so far, the MC has locked up or something, causing effects such as speech not working, lighting and smoke freezing, etc..

Restarting the MC fixes it

@MrStonedOne

**Comment by MrStonedOne** [comment]
Server?

**Comment by Shadowlight213** [comment]
bagil

**Comment by MrStonedOne** [comment]
if this happens again while i'm not around, try to send me some screenshots of the mc tab.

also VV the mc and paste bin it's vars.

**Comment by kevinz000** [comment]
reagent mc :^)

**Comment by Cyberboss** [comment]
Still a problem?

**Comment by Cyberboss** [comment]
Close this in favor of ^

@lzimann
