### ISSUE TITLE
User gets stuck in walk when alt-tabbing w/ Hotkeys enabled

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#23537]
Alt-tabbing toggles you into walk mode, however after tabbing back into the game, you are not returned running. (this is a pretty common issues for programs that have functions with alt that don't continue listening once the window loses focus.) 

Would it be possible to switch the run-toggle to a different key? It's rather inconvenient to tab back into a situation where it's critical that you are running (tator eswording you, bomb exploding, insert terrible thing here) and end up just hobbling away.

**Comment by ShizCalev** [comment]
Nevermind, see https://github.com/tgstation/tgstation/pull/23479

**Comment by Cyberboss** [comment]
If you are still having problems with this it may be an issue

**Comment by ShizCalev** [comment]
@Cyberboss I am.

**Comment by ShizCalev** [comment]
It's happening again.

When the window loses focus, it never registers that the alt key is released. The fix your attempted does not resolve that.

**Comment by MrStonedOne** [comment]
if you don't mention your os version and byond version when mentioning you have this bug you aren't helping but are just pissing in the wind.

**Comment by Cyberboss** [comment]
Happens to me on Windows 10, 510. Alt tabbing doesn't fire he ALT+UP event

**Comment by MrStonedOne** [comment]
for completeness, doesn't happen to me in 511.1370 on windows 7.

**Comment by Cyberboss** [comment]
See #24188 for more reports

**Comment by ShizCalev** [comment]
10, 511.1373

**Comment by Steelpoint** [comment]
Happens to me on Windows 10, I'm using the most up to date beta version of byond.

**Comment by MrStonedOne** [comment]
http://www.byond.com/forum/?post=2214392 fixed
