### ISSUE TITLE
Crash on clicking link to testmerged PR

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#23543]
![untitled](https://cloud.githubusercontent.com/assets/8237862/22467754/d4d25626-e793-11e6-95b1-3eda926faa43.png)
Clicking on the PR that's only a hashmark will crash your game.  The PR in question is #323497, which doesn't even exist.

**Comment by Cyberboss** [comment]
Side effect of the testmerge of #23359 @lzimann
