### ISSUE TITLE
New bug with the cyborg riding

### ISSUE THREAD

**Issue by TimeIsEndless** [tgstation/tgstation#23541]
When you try to climb on a cyborg someone else is riding by dragging yourself onto it you cannot use your hands anymore. The Icons in your hand are replaced with Off-hand icons that you would see normally when twohanding a weapon. 

 Here is a picture of the problem  :  http://i.imgur.com/X9oe9Vj.png

**Comment by lzimann** [comment]
@kevinz000 

Cyborg riding is not merged yet, only test merged. #23440

**Comment by kevinz000** [comment]
already fixed.
