### ISSUE TITLE
Computers dont start off framed

### ISSUE THREAD

**Issue by calzilla1** [tgstation/tgstation#23547]
But machines do
Consistency error or feature?

**Comment by XDTM** [comment]
By framed you mean wrenched down? I'm so used to it i never questioned it.

**Comment by calzilla1** [comment]
Ye

**Comment by PKPenguin321** [comment]
Consistency error. Machines shouldn't start wrenched down

**Comment by Cyberboss** [comment]
Uhhhh grandtheft chemdispenser every round? no thanks.

**Comment by PKPenguin321** [comment]
No no, I mean when you make a machine frame from metal.

**Comment by AnturK** [comment]
Not sure which way it should work if it uniform

**Comment by PKPenguin321** [comment]
Start unwrenched. Iirc machine frames used to be snowflake and couldn't be unwrenched at all then were changed to work more like computer frames, but whoever did it just forgot to unwrench them by default
