### ISSUE TITLE
[Metastation] Modular computer in meta's RD office blocks off request console and AI restore console

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#23540]
low effort implementation to be honest.

**Comment by jughu** [comment]
@latots already being worked on

**Comment by lzimann** [comment]
Being fixed by #23491. 
Next time please include which map the issue is happening.

**Comment by Iatots** [comment]
------>meta's RD office
              ^
               |
               |

**Comment by lzimann** [comment]
Also I'm blind sometimes so there's that.

**Comment by Tofa01** [comment]
Will be fixing my bad placement shortly
