### ISSUE TITLE
xray laser guns don't hurt kudzu unless its the targetted tile

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#23553]
Otherwise the beam passes through harmlessly

**Comment by XDTM** [comment]
I really need to work on my pr

**Comment by Kromgar** [comment]
This is the case for every laser type

**Comment by kevinz000** [comment]
@lzimann not an issue because kudzu doesn't give a shit about projectiles even if they're hardened fully grown anyways.

**Comment by kriskog** [comment]
Not a bug
