### ISSUE TITLE
Duplication in list of test merges

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23550]
![image](https://cloud.githubusercontent.com/assets/609465/22471637/dabd7732-e7ca-11e6-8a14-d50ddd6efd3b.png)

@MrStonedOne

**Comment by Cyberboss** [comment]
Yeah, something fucky with prtestjob.lk

**Comment by MrStonedOne** [comment]
not fixable

the script just appends to the file when something is test merged, and re-test merging the same pr is how you update the test merge if the pr'er pushed changes

**Comment by RemieRichards** [comment]
depending on how long-lasting the file is, you could just check for > 1 and label any after the first as "Testmerge-updates" or w/e.

**Comment by Cyberboss** [comment]
I suppose I could do a duplicate check when reading the file
