### ISSUE TITLE
Transit Pods absorb air into themselves

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#23556]
After using transit tubes on meta several times in the last few weeks, I've noted that nearly every time I take brute damage and get a high pressure alert. Just took a ride on one on delta and got the same issue. Don't think this is intended but let me know if it's supposed to happen and I'll close this.
Edit: This may happen on all maps, I'm not sure. Maybe it's not a map issue.

**Comment by ChemicalRascal** [comment]
This is still an issue, at least on Meta.

**Comment by duncathan** [comment]
will investigate

**Comment by duncathan** [comment]
appears to be an issue with the map. normal transit tubes on box (AI satellite tube was tested) have acceptable pressure

**Comment by duncathan** [comment]
jk this is a symptom of something much greater holy shit fuck my life

**Comment by BeeSting12** [comment]
This is not a map issue. Pods absorb air into themselves.
