### ISSUE TITLE
People buckled to vehicles can slip

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23558]
Including cars and cyborgs

**Comment by lzimann** [comment]
I'm pretty sure this is intended(althought there was a PR to change it) so people wouldn't bypass lube with a janicart.

**Comment by Cyberboss** [comment]
Yeah, we don't need more lube nerfs

**Comment by PKPenguin321** [comment]
Dupe and I think a fix is already up

**Comment by coiax** [comment]
It doesn't make any sense, why would someone slip on lube when driving a car

**Comment by RandomMarine** [comment]
Someone should code vehicles losing control on slippery surfaces.

**Comment by 81Denton** [comment]
Didn't driving over lube use to fling you off the vehicle?

**Comment by Angustmeta** [comment]
To clarify, you do still slip when driving a vehicle over water/lube. Tested with janicart.

**Comment by AWalton** [comment]
This happened to me yesterday whilst buckled to a Peacekeeper cyborg, and it makes no sense that it still affects you like this.

**Comment by Qustinnus** [comment]
this is intended.
