### ISSUE TITLE
id changing tablet program eats id's instead of ejecting them

### ISSUE THREAD

**Issue by vcordie** [tgstation/tgstation#23579]
see title.

**Comment by Cyberboss** [comment]
@lzimann assign this to me if you can

**Comment by jughu** [comment]
You are fired

**Comment by GunHog** [comment]
@AnturK Please re-open this, it is still an issue, I lost my ID and the Captain's spare using a tablet.

**Comment by GunHog** [comment]
Addendum to @Cyberboss: This also affects other things, like bags of holding and probably other storage items.
