### ISSUE TITLE
The Sol Gov Rep can't seem to use their fax

### ISSUE THREAD

**Issue by Dilqui** [tgstation/tgstation#23572]
As the title says. As of today, the Sol Gov representative can't seem to log in to their fax terminal. I tried to place a piece of paper in, see if that changed anything, but it didn't seem to do so.

**Comment by PKPenguin321** [comment]
I think you've got the wrong codebase.

**Comment by Jordie0608** [comment]
Most certainly.

**Comment by Dilqui** [comment]
Well, that's embarrassing. RIP me. Sorry 'bout that.
