### ISSUE TITLE
pAIs leave behind their cards when entering holoform.

### ISSUE THREAD

**Issue by YourNeighborsObnoxiousCat** [tgstation/tgstation#23581]
Exactly as the title implies. PAIs will leave behind their card when entering holoform. The card will teleport to the holograms current location when the pai leaves holoform, and will again remain in position if the pai chooses to enter holoform again.

![pai](https://cloud.githubusercontent.com/assets/25470377/22491394/b4f1f550-e7e8-11e6-8c4f-120c0a4955d3.png)

**Comment by ExcessiveUseOfCobblestone** [comment]
@Cyberboss

**Comment by Cyberboss** [comment]
Probably
