### ISSUE TITLE
can dupe rollerbeds

### ISSUE THREAD

**Issue by vcordie** [tgstation/tgstation#23582]
Step 1: buckle person to rollerbed. step 2: push rollerbed through teleporter. person will be left behind. step 3: drag person, rollerbed will magically appear. step 4: another rollerbed is at the location you teleported

**Comment by Cyberboss** [comment]
if the teleporter is new/qdeling objs, so help me...

**Comment by Jalleo** [comment]
It isnt that is two locations one object.

**Comment by Incoming5643** [comment]
yeah true duping is very very rare in SS13
