### ISSUE TITLE
SNPCs are HORRIBLY LAGGY

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#23595]
Gave 200-300ms to everyone's pings
https://gyazo.com/bcc927d00d8af4ad56694ab041617bc8
What the hell?
I'm not even sure if this is a bug but no mob should be using that much processing time, as we have cleanbots and they don't lag the server when there's 5 of them.

**Comment by RemieRichards** [comment]
Cleanbots don't do a lot and have had a lot of optimisation done to the things they do do (such as their A* pathing)
Where as SNPCs were a science project abandoned by their author, they've received no changes beyond minor fixes and required-changes-because-of-another-feature (such as multi-hands)

**Comment by kevinz000** [comment]
Fuck now I take a look and there's sleep()s everywhere, thought we deprecated..?!

**Comment by kevinz000** [comment]
Oh yeah, and this was from 5 snpcs, not all of them were janitors.

**Comment by RemieRichards** [comment]
SNPCs pre-date the rise of ```addtimer()```, so of course they use the inefficient methods, that's all we had at the time!

**Comment by PKPenguin321** [comment]
This is why I keep saying we can't add these things. Nobody listens.

**Comment by Iamgoofball** [comment]
they just need a little love thats all

**Comment by ExcessiveUseOfCobblestone** [comment]
>  that's all we had at the time!

STOP RIGHT THERE REMIE

**Comment by RemieRichards** [comment]
@ExcessiveUseOfCobblestone what are you implying?

**Comment by PKPenguin321** [comment]
Time timer pun meme

**Comment by Cyberboss** [comment]
I will literally 100% rewrite the NPC code one day.

... but, not fucking today.
