### ISSUE TITLE
Update sandbox panel

### ISSUE THREAD

**Issue by Keofox** [tgstation/tgstation#23596]
Sandbox panel is too old and need updating.  Here is my suggestions about it
   Need buttons to spawn BZ and Freon canisters
   Change suit in button "Gear up (Space Travel Gear)" to normal EVA or other suit
   Add button to quick spawn RPD (Rapid Pipe Dispenser)
   Need buttons for quick spawn other minerals, e.g 50 Plasma sheets, 50 Diamond sheets, 50 Uranium        sheets...
   Change button from "Spawn toolbox" to "Spawn full belt", because the toolbox is useless
   Need button for spawn mesons

**Comment by PKPenguin321** [comment]
Sandbox panel is pretty deprecated, yeah. Not sure of a good way to fix it without giving access to all items in the game which would inevitably cause chaos.

**Comment by Cyberboss** [comment]
Feature request

**Comment by AnturK** [comment]
Yeah, the sandbox panel needs a revamp if we're gonna support the gamemode. It's ancient.

**Comment by nightred** [comment]
This is a feature request and not an issue.
The panel is old and no one has touched this in 3 years.
Feel free to recreate and PR a new panel as you desire.
