### ISSUE TITLE
If you are meatspiked and the meat spike gets destroyed your mob will stay upside down

### ISSUE THREAD

**Issue by lzimann** [tgstation/tgstation#23603]
Pretty funny bug.

**Comment by PKPenguin321** [comment]
Probably a dupe

**Comment by Cyberboss** [comment]
Im certain this is a dupe

**Comment by Cyberboss** [comment]
Ok it's related to #11971 I guess

**Comment by lzimann** [comment]
There is #20032 but has no info about it.

**Comment by BeeSting12** [comment]
feature

**Comment by Kromgar** [comment]
@lzimann Its right there in the messages. WEar teleport armor get hit on a meatspike and you teleport off the meatspike
