### ISSUE TITLE
Nuking a Space Hotel level will result in a Syndicate Major Victory

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#23609]
...despite the fact that they're not nuking the station.

Makes me wish that nukes detonated off the main station Z-level didn't end the round.

**Comment by KorPhaeron** [comment]
@Cyberboss

**Comment by Cyberboss** [comment]
The round still ends, but yeah, syndies shouldn't win wtf

**Comment by Armhulen** [comment]
sure does show what we do to them there RPers

**Comment by XDTM** [comment]
At least we nuked _something_ boys, good work there!

**Comment by Firecage** [comment]
This PR is honestly just silly and doesn't make sense.

**Comment by ExcessiveUseOfCobblestone** [comment]
> implying killing a civilian area AND being able to pin it on nanotrasen isn't a major win for the syndicate.
