### ISSUE TITLE
Engraved messages moving/being placed in the wrong place

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23613]
![image](https://cloud.githubusercontent.com/assets/609465/22531853/89115a40-e8db-11e6-9913-cd0a92ce441e.png)

These are both my messages, and neither of them was originally engraved there. Unless someone is removing and replacing them next to each other, maybe there's some bug somewhere in the loading.

Even if there were Metastation changes, they were never next to each other.

**Comment by KorPhaeron** [comment]
They're coming back after I smash them as well

**Comment by coiax** [comment]
Smashing them doesn't remove them permanently, only a chisel can. Stops them from being killed by explosions,

**Comment by jughu** [comment]
@coiax could it possible be caused by tile pulling things like singularity?

**Comment by coiax** [comment]
@jughu that is a fantastic idea.
