### ISSUE TITLE
If you start flying on shuttle with toggled wings, you teleport to space

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#23627]
Someone say me about this bug, but im not sure - need testing.

**Comment by SweaterKittens** [comment]
It's the game trying to tell us that wings are terrible and should never have gotten added

**Comment by Robustin** [comment]
In testing I only found that launching/landing without buckling would cause your wings to "spazz out and launch you". If a door was open it would be possible to straight up space you but thats not a bug.

**Comment by ninjanomnom** [comment]
Unable to reproduce this and it's been over a year since this was put up, I think there was a refactor of related code in there somewhere.
