### ISSUE TITLE
Build your own shuttle kit bugged (shuttle manipulator replacement)

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#23628]
It's meteor shuttle
I use it to give the crew the BYOS because it was ordered by some random nonantag who was being a dick.
It 
LAUNCHES
AND TAKES OUT A PORTION OF THE STATION
AND THEN IT DELETES ITSELF AND SPAWNS THE BUILD SHUTTLE KIT
WHY @coiax FIX YOUR SHIT REEE!!!

**Comment by KorPhaeron** [comment]
The meteor shuttle moves the docking point when you buy it

Ordinarily you can't rebuy the shuttle so this isn't an issue

**Comment by coiax** [comment]
I was not responsible for the meteor shuttle or the shuttle purchasing system, that honour is exclusively for @KorPhaeron

**Comment by PKPenguin321** [comment]
Maybe don't swap out the asteroid shuttle for a dumb reason next time Kevin

**Comment by kevinz000** [comment]
:/

**Comment by PKPenguin321** [comment]
No but seriously this should be closed, not really a bug just egregious misuse of admin tools
