### ISSUE TITLE
Consistency Issue: You can night vision sec and med hugs before night vision goggles

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#23633]
>Plasma 4 
>Emp 5

NVG Sec hud and NVG Med hud

>Get plasma 5
>Suddenly night vision goggles

>Get engi 6 
>Night vision mesons

Highy inconsistent

**Comment by xxalpha** [comment]
It's called power creep.

**Comment by XDTM** [comment]
engi 6 is one of the hardest tech levels to get since it requires genetics, an expensive cargo crate or a mining jetpack.

**Comment by ExcessiveUseOfCobblestone** [comment]
just switch the reqs lmao

**Comment by Emilc4h** [comment]
You can get Engi 6 as soon as you've got diamonds. An upgraded destructive analyser will retain enough diamond from deconstructing it for Mat 7 for you to make a Piercing Syringe, which has Engi 5.

But yeah, you still need outside assistance, so I guess it is a pain.

**Comment by lzimann** [comment]
Not really an issue and more of a balance concern, going to close this, which is probably just an oversight when someone last touched research stuff.

**Comment by lzimann** [comment]
Actually

**Comment by Kromgar** [comment]
Realized the fact that its odd that night vision goggles appear after night vision?

**Comment by lzimann** [comment]
Yea
