### ISSUE TITLE
Slimejelly got MORE Lethal

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#23632]
So as we al know slimejelly got more lethal considering its also a bloodtype
Before we had bloodtypes slimejelly did plain burn damage
So i injected myself with 5 units slimejelly i saw my health decreasing fast as fuck major toxins damagr with the burn damage stacked up on it this could be traitor poison tier at killing
What i done
Had a slime person extracted from.
I injected myself with 5 units (i wasnt the slimeperson i was just a human)
Notices how i gone from 100% health to orange health and then fastly decreasing to red then crit

I dont remember slimejelly being this strong

**Comment by XDTM** [comment]
you got bad rng, slimejelly deals rare but significant tox damage while healing brute

**Comment by KorPhaeron** [comment]
What xdtm said
