### ISSUE TITLE
resisting out of a bluespace body bag destroys the body bag.

### ISSUE THREAD

**Issue by vcordie** [tgstation/tgstation#23637]
1021e93ead4f8ce1cdcc558edbdf6a745c765630 
Test merge active of PR #23493 
Test merge active of PR #23605 
Test merge active of PR #23616 
Test merge active of PR #23618

**Comment by PKPenguin321** [comment]
Feature

**Comment by vcordie** [comment]
shit one. :c

**Comment by KorPhaeron** [comment]
bad feature but a feature, feel free to change it
