### ISSUE TITLE
I don't even know what's happening here

### ISSUE THREAD

**Issue by dannno** [tgstation/tgstation#23647]
![](http://i.imgur.com/JaserCJ.png)

1. put bible in suit storage
2. open bible
3. double take

**Comment by Cyberboss** [comment]
please tell me this wasn't my fault...

**Comment by PKPenguin321** [comment]
@jughu lowered the max storage space of books/bibles to 1 slot, but forgot to remove the stuff from the default bible.

**Comment by Cyberboss** [comment]
Thank god....

**Comment by lzimann** [comment]
Good job

**Comment by dannno** [comment]
@jughu

**Comment by jughu** [comment]
Right on it 👌
