### ISSUE TITLE
Clicking a stack of metal in your hands to a stack of metal in your drone bag deletes the metal.

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#23651]
This appears to happen with every resource, including cables and other stackables. putting the object into your bag still autostacks it properly.

**Comment by Haevacht** [comment]
P sure this is a dupe.

**Comment by Cyberboss** [comment]
Maybe not. I fixed the exosuit thing, but I do remember stacks being extra fucky

**Comment by Hatfish** [comment]
Not just a drone thing, this can happen with any stackable item so long as there's at least two in each stack.

**Comment by Iatots** [comment]
Rods are particularly prone to this. Also, it does not require one stack to be in a bag, your other hand is enough.

**Comment by feemjmeem** [comment]
Confirmed as affecting glass as well.
