### ISSUE TITLE
Map Conflict Fixer Broken?

### ISSUE THREAD

**Issue by Tofa01** [tgstation/tgstation#23658]
## **Map Conflict Fixer Broken**

Upon using the Map Conflict Fixer to attempt to solve a conflicting map file using dictionary mode (Not sure about full mode) it outputs this when attempting to fix the map conflict.

## **Error Received While Trying To Fix Map**
FIXING: _maps/map_files/Deltastation/DeltaStation2.dmm
Traceback (most recent call last):
  File "map_conflict_fixer.py", line 103, in <module>
    main(sys.argv[1])
  File "map_conflict_fixer.py", line 99, in main
    if map_helpers.fix_map_git_conflicts(base_map, ours_map, theirs_map, mode, marker, priority, relative_root+path):
  File "C:\Users\(Nice Try!)\Desktop\My Files\Github\tgstation\tools\mapmerge\map_helpers.py", line 685, in fix_map_git_conflicts
    write_dictionary_tgm(path+".fixed.dmm", merged_dict)
TypeError: write_dictionary_tgm() missing 1 required positional argument: 'header'
Press any key to continue . . .

## **Summary**
If anyone could fix this issue it would be great, my Map Conflict Fixer always outputs this error when attempting to use it i may be doing something wrong but it seems pretty straight forward. If further information is required comment here and i will reply as soon as possible.

**Comment by AnturK** [comment]
@xxalpha Please.

**Comment by xxalpha** [comment]
I cucked myself.

**Comment by xxalpha** [comment]
You can look at my fix #23661 to temporarily fix your version of the script until my fix is merged, should be an easy thing to do. Sorry for that.
