### ISSUE TITLE
A really really weird surgery bug.

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#23686]
I'm not sure if i can replicate it, but I put a facehugger on someone, cut it out of their chest, and then ghetto-implanted it back into them. They never exploded when the larva burst, and I couldn't preform any other surgeries on them.

**Comment by XDTM** [comment]
Doesn't it come out as a larva corpse? Did you implant that?

**Comment by Magikarpet** [comment]
Yep, and it's an embryo not a larva. It should work naturally that way though.

**Comment by YakumoChen** [comment]
a corpse won't come back to life to kill someone obviously

**Comment by Kromgar** [comment]
@YakumoChen Zombies

**Comment by AnturK** [comment]
Not a bug.
