### ISSUE TITLE
Autoimplanters aren't being given to nuke ops when they purchase a cyber implant

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#23687]
They're supposed to come packaged in a box with the cyber implant.

**Comment by Kromgar** [comment]
I was wondering about that purchased x-ray and there was no autoimplanter i assumed it was balance change

**Comment by Cyberboss** [comment]
I think this is a dupe

**Comment by PKPenguin321** [comment]
Did some codediving. Found out that the code to spawn the boxes with the implant and the autoimplanter only checks for the path "/obj/item/organ/cyberimp". Eye implants are no longer cyber implants after Kor's thing. I think I know a fix.

**Comment by coiax** [comment]
This has been fixed. @lzimann
