### ISSUE TITLE
Minor Chainsaw Crafting Bug

### ISSUE THREAD

**Issue by Nelson01023** [tgstation/tgstation#23702]
Essentially, you can craft a chainsaw using the holodeck circular saw, and the game will register it as a normal, non holodeck chainsaw.

**Comment by PKPenguin321** [comment]
100% certain this is a dupe, not sure what the original issue is though

**Comment by PKPenguin321** [comment]
Found the first issue, supposedly it was closed but never actually fixed.
https://github.com/tgstation/tgstation/issues/15046

**Comment by Armhulen** [comment]
no NO I LIKED THIS ONE

**Comment by Nickkoranda** [comment]
Closed by https://github.com/tgstation/tgstation/pull/17136
