### ISSUE TITLE
People with flashlight eyes can still see.

### ISSUE THREAD

**Issue by KingPhilipIII** [tgstation/tgstation#23731]
Right. So after I disconnected for thirty minutes, I came back to find I had been rather vividly abused. My arms were removed and my eyes had been replaced with flashlights.

More importantly, I was not blind as expected when possessing flashlight eyes. Or was that a joke when Kor said flashlight people can't see?

**Comment by KorPhaeron** [comment]
I went to thunderdome, put flashlight eyes in a braindead mob, then put myself in that mob and they couldn't see.

**Comment by Armhulen** [comment]
perhaps the eye damage is wearing off or something? there is 30 minutes of inbetween here

**Comment by KingPhilipIII** [comment]
Does the blindness work via massive eye damage or are you just totally blind due to the implants? If it's the former my torturer was a chemist and may have fed me tons of oculine.

**Comment by KingPhilipIII** [comment]
Just realized I closed this. Whoops.

**Comment by KorPhaeron** [comment]
The implants should have kept you blind
