### ISSUE TITLE
YOU CAN EAT FLASHLIGHT EYES

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#23738]
FEATURE? FEATURE!

**Comment by dannno** [comment]
you can eat all eye implants actually
and it makes them unusable, even if you only take 1 bite

**Comment by xxalpha** [comment]
Wait, why.

**Comment by RemieRichards** [comment]
because they're organs, and you can turn all organs into an edible form.

**Comment by Cyberboss** [comment]
needs a flag for nonedible implants

**Comment by Armhulen** [comment]
i dunno guy

**Comment by Armhulen** [comment]
wait fuck
