### ISSUE TITLE
Fancy windows are borked

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#23741]
![untitled](https://cloud.githubusercontent.com/assets/8237862/22626609/98b66dae-eb7f-11e6-841f-ac21a6eb4d12.png)

Occured on both servers.
Testmerged PRs:  #23729, #23359 

The On, Off, and Manual text can be used like regular buttons, though this is not immediately apparent.  This affects all UIs and all machines as far as I can tell.  
Probably a BYOND bug related to the latest beta update.

**Comment by lzimann** [comment]
People were reporting this happening after updating to byond 511.1371

**Comment by lzimann** [comment]
Byond released a new beta, can anyone confirm me if 1372 fixes this?

**Comment by Hatfish** [comment]
Apologies, should have mentioned that this occurs on 1371 and 1372.

**Comment by Hatfish** [comment]
This has been fixed by the 1373.
