### ISSUE TITLE
unconcious cultists count for cultist amount for a conversion rune

### ISSUE THREAD

**Issue by vcordie** [tgstation/tgstation#23759]
would have wrecked that cult if the critical cultists somehjow didnt count for the conversion rune, god damn it.

**Comment by ChangelingRain** [comment]
Unconscious cultists do not actually count for runes; it's most likely one of the cultists was down and stunned, so unless you have more info I'm going to assume this didn't actually happen.

**Comment by vcordie** [comment]
Blood cult @ChangelingRain not clock cult. And yes they were in crit, i fireaxed them to crit.

**Comment by vcordie** [comment]
ill give you the logs in a minute here.
