### ISSUE TITLE
pai master dna imprinting failed

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#23760]
HELP: Mooseykins/(TOWN GUARD) (?) (PP) (VV) (SM) (FLW) (TP) (REJT) (IC): For some reason every time my master as a pAi tries to imprint his DNA, it says his DNA does not match my stored master DNA. But he was the first one to try to imprint me 

his mob had null for master_dna

**Comment by RandomMarine** [comment]
Could the master's DNA had something to do with it?

**Comment by MrStonedOne** [comment]
Failed to reproduce.
