### ISSUE TITLE
Cutting off an infectious zombie's arm, then reattaching the arm doesn't give the zombie a claw back

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23783]
I mean, this is an admirable attempt to circumvent the species restrictions.

**Comment by KorPhaeron** [comment]
NODROP items should probably just stay stuck to limbs when they come off

**Comment by Kromgar** [comment]
What about eyes of god? I've had to remove the eyes by cutting open the head before.

**Comment by coiax** [comment]
I mean, ideally, they'd be a special limb like chainsaw/arm blade. @XDTM 

But I don't know how those work just yet.

**Comment by XDTM** [comment]
Speaking of, after that PR limbs should delete if they were holding NODROP items. Won't 100% prevent this but at least should require a new arm.

**Comment by KingPhilipIII** [comment]
Give zombies robot arms. New ways to circumvent restrictions.

**Comment by XDTM** [comment]
Should probably just give claws in species_life if it doesn't have them in both hands.
