### ISSUE TITLE
you can delete clothing by attempting to draw it while stunned

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#23794]
dragging a clothing item from its slot into your active hand destroys it while stunned, not sure if this goes on to stuff in pockets as well but it works for backpacks.

**Comment by Cyberboss** [comment]
almost certain this is my fault

**Comment by ShadowDeath6** [comment]
you shouldn't be able to strip your own clothes while stunned in the first place, but that's been around for a long time

**Comment by bgobandit** [comment]
lizards finding bugs that make them naked

very suspicious

**Comment by anconfuzedrock** [comment]
it started with my backpack for the record

**Comment by rainbowjose** [comment]
Love you, Cyberboss <3
