### ISSUE TITLE
There is a deep fryer inexplicably in the middle of metastation's kitchen.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#23806]
![](http://i.imgur.com/TEY0aD5.png)

Why. How. When.

**Comment by Iamgoofball** [comment]
All the kitchens start with deep fryers?

**Comment by KorPhaeron** [comment]
You can't walk around the table goof

**Comment by Iamgoofball** [comment]
oh i'm dumb

well if you want to haev you can technically wrech it

i'll fix it tomorrow

**Comment by Emilc4h** [comment]
We tried to wrench it and instead deep-fried the wrench, which was admittedly hilarious _(and delicious)_.

**Comment by BeeSting12** [comment]
i can see this deepfryer causing some funny issues

**Comment by WJohn** [comment]
Why was a second one added when one already exists anyway?

**Comment by jughu** [comment]
Put the deep fryers on the side in the middle remove table left and right bam design

**Comment by Iamgoofball** [comment]
Bad mapmerge

**Comment by Militaires** [comment]
remove the racks and replace with fryers

**Comment by SouDescolado** [comment]
Add the wrench to the Deepfry blacklist

**Comment by Penguaro** [comment]
Added a quick tweak to my PR for other map edits. Arguably the kitchen could use a review of its layout. I considered moving the fryer somewhere else or taking out a table but there is already very limited work space for a cook, so I just deleted the offensive fryer.
