### ISSUE TITLE
VV add organ bugs

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#23800]
Adding an eye cybernetic implant overwrites whatever they had before, even when they're supposed to be able to hold both.

**Comment by PKPenguin321** [comment]
Recently a couple were refactored so the new eye completely replaces the old one. Which eye implant were you applying?

**Comment by kevinz000** [comment]
Cyberimplants, a ling was bugged so I tried giving them thermals/welding shield, but they kept overwriting each other :/

**Comment by PKPenguin321** [comment]
Yeah, those implants now replace the eyes themselves instead of just adding on, and you can only have one pair of eyes at a time. Not a bug, this is working as intended.

**Comment by XDTM** [comment]
Welding shield should really not be an eye, it could easily be an auto-darkening lens that goes over the eye.
