### ISSUE TITLE
Pyrosium and Cryostylane does not react with atmosphere oxygen

### ISSUE THREAD

**Issue by Keofox** [tgstation/tgstation#23813]
Pyrosium and Cryostylane does not react with normal atmosphere air that contains **oxygen** while spilled or sprayed on anything object. Please fix that, or add special reagents, which react with atmosphere.

**Comment by duncathan** [comment]
@iamgoofball I'm hesitant to call this a bug, thoughts?

**Comment by Iamgoofball** [comment]
They only react with the reagent oxygen, but I guess it could check the air in the turf.

**Comment by Iamgoofball** [comment]
More of an oversight if anything tbh

**Comment by duncathan** [comment]
well this is consistent with chem as it is, making it react would be a feature request. not a bug
