### ISSUE TITLE
Deep fryer ate muh beaker!!!

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#23812]
I TRIED TO POUR SOME ROMEROL IN THE DEEP FRYER IT WAS A SUCCESS IT POURED 10 UNITS INSIDE BUT ALSO FRIED MY BEAKER

**Comment by kevinz000** [comment]
goofball fix your shit.

**Comment by PKPenguin321** [comment]
You aren't allowed to be bad at goof for lazy errors like this Kevin"moving pAIs"z000

**Comment by Iamgoofball** [comment]
Fucking hell you'd think after 10 years we'd make beakers not hardcoded
