### ISSUE TITLE
single tank bombs don't dump their contents to atmos if they're in a backpack when triggered

### ISSUE THREAD

**Issue by vcordie** [tgstation/tgstation#23824]
Step 1: fill tank up with plasma
step 2: attach igniter assembly to tank
step 3: drill a hole in the tank with a welder
step 4: put "bomb" (really a plasma flood device) on the floor
step 5: activate it
what happens is the room floods with plasma which is immediately ignited. Very nice.
repeat steps 1 to 3
step 4: put bomb in backpack
step 5: activate it
what happens: you catch on fire and no plasma is leaked. Very very sadness. Probably a feature, but a dumb one.

**Comment by Cyberboss** [comment]
Sounds like there are some missing get_turf's here

**Comment by vcordie** [comment]
ignore. am retarded.

**Comment by vcordie** [comment]
actually no, this is actually true. Had 5 bombs in a backpack, let them all off, 3019kpa at 20c*5=more then a plasma cannister, yet it only flooded the tile i was on plus the 4 adajacent ones. what the fuck?

**Comment by vcordie** [comment]
no, nevermind, I AM actually retarded.
