### ISSUE TITLE
Shuttle engines have inconsistent west/east icons with north/south.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#23821]
This means that if a shuttle were to flip from north/south to east/west at any point, the engines would appear backwards. Sprite issue and subsequent map issue.

![](http://i.imgur.com/TGKYdFr.png)

The fix would be to flip all these west/east icons, then go in the map maker and go through each and every map, looking for shuttles that face east/west and flipping the engine dirs on those.

**Comment by coiax** [comment]
I did notice this when I was doing shuttles. I then shuddered and successfully made myself forget.
