### ISSUE TITLE
Unwrenching the directional signs (Sec ==>, Med <== etc) will make the arrow fucky

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#23839]
Normally this means it will now point down, so if the sign said Sec ===> it will now say Sec V. 

Weirdly if you drag them around, the arrow will change direction based on where you drag it

**Comment by SweaterKittens** [comment]
I think the arrow changing direction based on where you drag it is a product of directional sprites. The same thing happens if you drag an office chair or any of the other sprites that have multiple directions, since that's the direction that they're moving, so they change "facing".

**Comment by bgobandit** [comment]
that helps explain it, but on the other hand, they're signs so it shouldn't be changing at all, also there's a huge bias toward down, possibly related to where you face while placing one
