### ISSUE TITLE
Swarmers take damage from electrified grilles, and have no stun or cooldown on shocking themselves

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23830]
Walking into an electrified grille can kill instantly, since there's no cooldown on shocks, and swarmers have a tiny health pool anyway.

**Comment by XDTM** [comment]
If drones are immune it makes sense for swarmers to be as well

**Comment by PKPenguin321** [comment]
This has been a thing for ages and iirc is a vintage xeno defense method to trick them into walking into an electric grille and instacritting
