### ISSUE TITLE
Inquisitor's helmet item sprite uses clothing sprite instead

### ISSUE THREAD

**Issue by Markolie** [tgstation/tgstation#23841]
The inquisitor helmet item sprite (found in icons/obj/hats.dmi under hardsuit0-inq) uses the smaller clothing sprite (from icons/mob/head.dmi) instead of the enlarged item sprite items normally uses. This means the sprite when viewed in a user's hand or on the ground is very small.

Perhaps @KorPhaeron still has the original item sprite?

**Comment by KorPhaeron** [comment]
Don't have a larger sprite for it, sorry. Don't know that one was ever made

**Comment by Dorsisdwarf** [comment]
Not a bug, several hat items do this, whenever they cant get a spriter to do a big sprite.
