### ISSUE TITLE
Space carp are turning into salts-the-wound

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#23840]
A bunch of "The space carp's suit can't take anymore damage and rips apart!" are showing up. 

(This is the pirate death message, I VV'd the dead carps I found in mob list and they were normal pathed carps with a null deathmessage, not sure what's going on here)

**Comment by Poojawa** [comment]
I've been seeing Space carp gnashing at ghosts on the odd occasion as well

**Comment by Repukan** [comment]
Also present with Goliath's and drones.

**Comment by ChangelingRain** [comment]
@Cyberboss

**Comment by KorPhaeron** [comment]
Saw it happen with @Petethegoat

**Comment by Kromgar** [comment]
So what the hell did @Cyberboss do?

**Comment by Cyberboss** [comment]
Simple animal deathgasps...

**Comment by Cyberboss** [comment]
wait gnashing at ghost? fucking how?
