### ISSUE TITLE
Metal closets protect from Tesla

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#23846]
Only survivor of a shuttle hit by the Tesla was a viro who hid in a closet

**Comment by Haevacht** [comment]
Very known, at least to the players. You hear a tesla you GET IN A FUKKEN LOCKER.

This helps survivability and I would like it to stay.

**Comment by PKPenguin321** [comment]
Goofball insists this is intentional, and has said so since the tesla was added. It's like a faraday cage

**Comment by lzimann** [comment]
Tbh faraday cages are a real thing so we can just go with that. A maintainer can open this issue if they feel like this is not intentional though.
