### ISSUE TITLE
Drones cannot manipulate machinery with multitools.

### ISSUE THREAD

**Issue by cedarbridge** [tgstation/tgstation#23853]
Drones attempting to build teleporters and telecomms machinery have been incapable of linking the devices with multitools.  Multitools still work for normal hacking processes, but do not interact with more complex machines like those noted above.

**Comment by jughu** [comment]
@cedarbridge  screwdriver the station and then use wirecutters you dont need multitools not a bug

**Comment by Militaires** [comment]
you dont link teleporters with multitools, you screwdriver the station and wirecut it

**Comment by cedarbridge** [comment]
I'm aware of that.  The report about teleporters was reported second hand from somebody else.  I presume they mean telepads which do require a multitool

**Comment by jughu** [comment]
Telepad should be screwdriver multitool

**Comment by ShadowDeath6** [comment]
Telecoms machinery doesn't work with them, though, which is a bug. I think it also happens with borgs.

**Comment by cedarbridge** [comment]
Did some testing.  It works.  For some reason the instructions on the wiki implied needing to screwdriver open the telecomms hub to access the multitool link.  Guess not.  I think this is resolved.  

For the record, I tested it on both drones and an engieborg.

**Comment by ShadowDeath6** [comment]
hm
