### ISSUE TITLE
Maps Not Compiling After Recently Merging With Upstream Master

### ISSUE THREAD

**Issue by Tofa01** [tgstation/tgstation#23857]
## **Maps Not Compiling After Recently Merging With Upstream Master**
I am not sure this is me but this is what i did to get this result. I pulled into my local master from upstream master then pushed to my remote master. But upon attempting to load a map i get this error in Dream Maker:

### **Before Attempting Map Compile**
![error1](https://cloud.githubusercontent.com/assets/24999255/22737834/032fcdc0-ee59-11e6-9ad1-c5dff4c9a290.PNG)

Then when i follow what this error tells me to do i get these sets of errors in the compilation log.

### **After Attempting Map Compile**
![error2](https://cloud.githubusercontent.com/assets/24999255/22737890/43e5c61c-ee59-11e6-8f0a-58e61467ffd7.PNG)

Once again i am not sure if this is just me but this error happened after i synced with the upstream master, so i think a recent merge must have broke the maps. Looking at whats been recently merged PR #23723 was the last to touch those .dm files (My branch "FireAlarmSound-Master" still works without problems as i have not merged it yet with the most recent updated master)

**Comment by lzimann** [comment]
I can't seem to reproduce this on latest master(i even compiled with all maps). Seems to be on your side, try pulling from the upstream again(and check if you don't have any file open to have a chance of not overriding).

**Comment by Cyberboss** [comment]
Can confirm, your fork/branch must be borked

**Comment by Tofa01** [comment]
Looks like it fixed itself somehow, thanks for the help.
