### ISSUE TITLE
sky bulges runtime when thrown across z-levels + giving airlocks damage

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#23864]
- `runtime error: 
- **[18:21:50]Cannot read null.z**
- [18:21:50]proc name: throw impact (/obj/item/weapon/twohanded/skybulge/throw_impact)
- [18:21:50]  source file: twohanded.dm,700
- [18:21:50]  usr: 0
- [18:21:50]  src: Sky Bulge (/obj/item/weapon/twohanded/skybulge)
- [18:21:50]  src.loc: the floor (53,147,1) (/turf/open/floor/plasteel)
- [18:21:50]  call stack:
- [18:21:50]Sky Bulge (/obj/item/weapon/twohanded/skybulge): throw impact(the security wardrobe (/obj/structure/closet/wardrobe/red))
- [18:21:50]Sky Bulge (/obj/item/weapon/twohanded/skybulge): Bump(the security wardrobe (/obj/structure/closet/wardrobe/red), 1)
- [18:21:50]the floor (53,148,1) (/turf/open/floor/plasteel/red/side): Enter(Sky Bulge (/obj/item/weapon/twohanded/skybulge), the floor (53,147,1) (/turf/open/floor/plasteel))
- [18:21:50]Sky Bulge (/obj/item/weapon/twohanded/skybulge): Move(the floor (53,148,1) (/turf/open/floor/plasteel/red/side), 1)
- [18:21:50]Sky Bulge (/obj/item/weapon/twohanded/skybulge): Move(the floor (52,148,1) (/turf/open/floor/plasteel/red/side), 9)
- [18:21:50]/datum/thrownthing (/datum/thrownthing): tick()
- [18:21:50]Sky Bulge (/obj/item/weapon/twohanded/skybulge): throw at(the floor (46,154,1) (/turf/open/floor/plasteel/delivery), 7, 4, null, 1, 0, /datum/callback (/datum/callback))
- [18:21:50]Sky Bulge (/obj/item/weapon/twohanded/skybulge): throw at(the floor (46,154,1) (/turf/open/floor/plasteel/delivery), 7, 4, null, 1, 0, /datum/callback (/datum/callback))
- [18:21:50]Sky Bulge (/obj/item/weapon/twohanded/skybulge): throw at(the floor (46,154,1) (/turf/open/floor/plasteel/delivery), 7, 4, null, 1, 0, /datum/callback (/datum/callback))
- [18:21:50]Sky Bulge (/obj/item/weapon/twohanded/skybulge): throw at(the floor (46,154,1) (/turf/open/floor/plasteel/delivery), 7, 4, null, 1, 0, null)
- [18:21:50]explosion(space (59,143,1) (/turf/open/space), 1, 3, 8, 8, 1, 0, 0, 0, 1)
- runtime error: 
- [18:21:50]Cannot read null.z
- [18:21:50]proc name: throw impact (/obj/item/weapon/twohanded/skybulge/throw_impact)
- [18:21:50]  source file: twohanded.dm,700
- runtime error: 
- **[18:23:50]Cannot execute null.start().
- [18:23:50]proc name: take damage (/obj/machinery/door/take_damage)**
- [18:23:50]  source file: door.dm,173
- runtime error: 
- [18:23:57]Cannot execute null.start().
- [18:23:57]proc name: take damage (/obj/machinery/door/take_damage)
- [18:23:57]  source file: door.dm,173
- runtime error: 
- [18:24:07]Cannot execute null.start().
- [18:24:07]proc name: take damage (/obj/machinery/door/take_damage)
- [18:24:07]  source file: door.dm,173
- runtime error: 
- [18:24:18]Cannot execute null.start().
- [18:24:18]proc name: take damage (/obj/machinery/door/take_damage)
- [18:24:18]  source file: door.dm,173
- runtime error: 
- [18:24:19]Cannot execute null.start().
- [18:24:19]proc name: take damage (/obj/machinery/door/take_damage)
- [18:24:19]  source file: door.dm,173
- runtime error: 
- [18:24:35]Cannot execute null.start().
- [18:24:35]proc name: take damage (/obj/machinery/door/take_damage)
- [18:24:35]  source file: door.dm,173
- runtime error: 
- [18:24:35]Cannot execute null.start().
- [18:24:35]proc name: take damage (/obj/machinery/door/take_damage)
- [18:24:35]  source file: door.dm,173
- runtime error: 
- [18:25:07]Cannot execute null.start().
- [18:25:07]proc name: take damage (/obj/machinery/door/take_damage)
- [18:25:07]  source file: door.dm,173
- runtime error: 
- [18:26:51]Cannot execute null.start().
- [18:26:51]proc name: take damage (/obj/machinery/door/take_damage)
- [18:26:51]  source file: door.dm,173
- runtime error: 
- [18:26:53]Cannot execute null.start().
- [18:26:53]proc name: take damage (/obj/machinery/door/take_damage)
- [18:26:53]  source file: door.dm,173

`

**Comment by SpaceManiac** [comment]
Sky Bulge is no longer in the game
