### ISSUE TITLE
Syndicate Surplus Crate spawns job-specific traitor gear

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#23868]
On a side note plz gib antag token. I shot my own face off with a fucking clown revolver as a shaft miner.

**Comment by coiax** [comment]
Not a bug, intended.

**Comment by KorPhaeron** [comment]
A bad idea though

**Comment by coiax** [comment]
Yes, in this case, probably a bad idea.

**Comment by jughu** [comment]
I saw that miner ran into bar with a ebow and a revolver and shot himself it was hillarious

**Comment by InsaneHyena** [comment]
Intended.

**Comment by jughu** [comment]
@anturk can be closed? The only job spefific item that can spawn inside now is his grace and its very rare too

**Comment by coiax** [comment]
Also, I made clown revolvers come inside boxes of hugs for identification, if they spawned in a surplus crate. Not that they can do that anymore.

**Comment by Robustin** [comment]
Closing because its largely resolved and I hate trivial issues
