### ISSUE TITLE
calls to add overlay needs to be batched

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#23870]
add_overlay supports taking a list, the way it adds entries to the overlays list causes byond to only regenerate the appearance once even when adding a list.

Most of the overhead of add_overlay is from regenerating the appearance.

So the obvious answer is that things that call add_overlay need to batch it's calls so all overlays get added at once.

Most actually do, purely because they only add 1 overlay.

But shit like mobs and other things that add/remove overlays alot do not.

(It doesn't help that @RemieRichards's current system for human overlays makes batching them up kinda hard.)(not trying to call you out rr, just pointing this out in case you can think up a solution since you know your system better then I do.)

I thought about doing a subsystem and batching all overlay calls in a given tick, but removing becomes an issue because of how byond treats overlays. The only way we could do that is if all overlay operations only added/removed /appearance/s, because -='ing from an overlay list is treated specially compared to a normal list if what you are removing is not an appearance.

@tgstation/commit-access 
@Cyberboss (because you've done some performance prs)

If at the least, maintainers could require this on new content, we can start to hedge off this issue.

**Comment by RemieRichards** [comment]
@MrStonedOne I mean, just alter ```apply_overlay()``` to store an assoc list of index->image list, and then apply that list every whatever ticks.

**Comment by optimumtact** [comment]
If you could reliably have a subsystme that ticks every round, you could batch all updates in add_overlay and only apply them once in a new proc, saving time and effort

I was speculating to the possiblity of this but goof put me off by saying it wouldn't be fast enough to not break immersion

**Comment by Cyberboss** [comment]
Ticker subsystem with highest priority, should be fine. I'll work on this
once I finish the currentrun fuckery I'm in.

**Comment by MrStonedOne** [comment]
>If you could reliably have a subsystme that fires every tick, you could batch all updates in add_overlay in a temp list and only apply them once in a new proc, saving time and effort (marking atoms as dirty by storing them in some needs_overlay update list)

see:

>I thought about doing a subsystem and batching all overlay calls in a given tick, but removing becomes an issue because of how byond treats overlays. The only way we could do that is if all overlay operations only added/removed /appearance/s, because -='ing from an overlay list is treated specially compared to a normal list if what you are removing is not an appearance.

**Comment by Cyberboss** [comment]
list -= list?

**Comment by MrStonedOne** [comment]
there are like 5 different ways to add an overlay for what is basically the same thing, this is converted to an appearance, -= on an overlay list will convert to an appearance before attempting to match, but it will not do that on a normal list or a copy of the overlay list. so if we did a subsystem, we would have to convert to an appearance on add and remove.

**Comment by xxalpha** [comment]
Do the advantages of this system outweight this problem?
