### ISSUE TITLE
ratvar ai's don't look brass colored on some peoples screens

### ISSUE THREAD

**Issue by vcordie** [tgstation/tgstation#23877]
on my screen
![](http://i.imgur.com/a/ZNnBX.png)
on everyone elses
![](http://i.imgur.com/tvU9mgi.png)

**Comment by francinum** [comment]
It's also frankly ugly as hell but that's besides the point.

**Comment by ChangelingRain** [comment]
I have no fucking idea why or how this would happen. Setting an atom's color shouldn't fuck up at all ever.

**Comment by francinum** [comment]
Do you have that AI sprite you used during an event? That looks better and is also extremely obvious as a **_HEY THIS AI'S ROUGE AS SHIT._**

**Comment by ChangelingRain** [comment]
I have it but it's terrible and I'd have to add overrides to AI code to prevent them from changing away from it(also it doesn't have a deathsprite(also ai revive just resets their sprite(basically it's a pain in the ass)))

**Comment by Armhulen** [comment]
maybe change it's screen to a clockwork ai, and it can't change it's face sprite

**Comment by anconfuzedrock** [comment]
does the ai look blue and white or brass and gold

**Comment by francinum** [comment]
It looks like it's covered in piss.

**Comment by SweaterKittens** [comment]
Hey, maybe you could make a new sprite if it bothers you so much instead of bitching on an unrelated issue report

**Comment by ChangelingRain** [comment]
this is fixed it has a sprite
