### ISSUE TITLE
Progress bar not appearing when operating on held items 

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#23874]
Tested with secure briefcase, holding it in your hand and using either a screwdriver to open/close the panel or a multitool to reset the circuitry will not display any progress bar; not above your character nor around your hands. This has been happening after they were made to stack, and adds to #19245, which reports no progress bars with actions on worn items. So possibly no progress bars on any items that aren't on the floor.

**Comment by lzimann** [comment]
They DO appear, the problem is that they appear behind the HUD so it's easy to miss.

**Comment by Iatots** [comment]
If it's there but you can't see it, is it really there?

**Comment by PKPenguin321** [comment]
yeah, just make the tiny little button at the top left of the hands HuD layer slightly lower so it goes under progress bars
