### ISSUE TITLE
Simple animals that del_on_death do not produce a deathrattle in deadchat

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23887]
..() isn't being called on this code path. https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/simple_animal/simple_animal.dm#L304

I've seen this bug for a while, but only when seeing one of @Cyberboss ' PRs did I realise what it was.

**Comment by coiax** [comment]
@KorPhaeron @Cyberboss hasn't been fixed, still present in master.

**Comment by Cyberboss** [comment]
@lzimann reopen
