### ISSUE TITLE
Flightsuit Teleportation Bug

### ISSUE THREAD

**Issue by Steelpoint** [tgstation/tgstation#23897]
When using the RnD 'Flightsuit' indoors it rarely will result in a teleportation glitch where I will be teleported back to a position I was in a few moments ago.

This bug only occurred twice but both times were indoors. 

Both events occured usually when I was moving through a lot of doors at once.

The one bug I recall with good memory occurred as I was leaving Boxstation's armoury. I started behind the middle rack of guns and began to fly out of the armoury, I was only using the suits flight ability and no boosters, as I moved south out through the Warden's door and through the main security entrance I was suddenly teleported back into the armoury.

**Comment by kevinz000** [comment]
hmmmmmmmmmmmmmmmmmmmmmmmmm.

**Comment by kevinz000** [comment]
can't be replicated by normal airlocks, i'll test windoors separately later. might be an issue with it waiting for the open proc and then forcemoving, instead of spawn() and ignoring hte open proc.
