### ISSUE TITLE
A certain ruin spawns a bit too close to the mining base.

### ISSUE THREAD

**Issue by YourNeighborsObnoxiousCat** [tgstation/tgstation#23911]
SUPER SEKRIT COMRADES.
THEY'LL NEVER FIND US HERE.
![sekrit](https://cloud.githubusercontent.com/assets/25470377/22797994/f6376d54-eec5-11e6-980a-efc5b8d99991.png)

**Comment by KorPhaeron** [comment]
EMERGENT GAMEPLAY

**Comment by AnturK** [comment]
Good old trench warfare round.

**Comment by MrStonedOne** [comment]
@KorPhaeron: http://tinysubversions.com/spelunkyGen/

True procedural generation when?

**Comment by KorPhaeron** [comment]
@MrStonedOne 

If I was smart enough to do that I'd go make my own videogame

**Comment by Repukan** [comment]
Just get an RCD and make her blow

**Comment by PKPenguin321** [comment]
I think this isn't really an issue.

**Comment by SpaceManiac** [comment]
Formally not a bug
