### ISSUE TITLE
[Delta] Virology's entrance hall is blocked by a wall and lacking a second access button

### ISSUE THREAD

**Issue by Emilc4h** [tgstation/tgstation#23910]
Presumably caused by #23780, not too sure. Only noticed it this morning!

[Pictures probably help more than my bad explanations could.](http://image.prntscr.com/image/99e0fcfcfced4b8aa2387ce97e53390d.png)

**Comment by Tofa01** [comment]
Hm, this looked perfectly normal in my pictures, possible map merge being weird, fixing this now.

**Comment by Brimcon** [comment]
Wish to add to this issue. Virology isn't wired to the grid correctly
