### ISSUE TITLE
miner survival shelter from capsule spawns without oxygen inside

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#23928]
had to wear internals in my shelter to not choke

**Comment by AnturK** [comment]
@Cyberboss likely.

**Comment by Cyberboss** [comment]
Uggghhhh, I know what it is already.

I changed it so that things loaded from templates (mining pods) don't reinitialize any atoms. Problem being, map loads don't use ChangeTurf. So the Destroy proc isn't called. And because of T U R F P E R S I S T E N C E initialized remains TRUE.

**Comment by Cyberboss** [comment]
Wait, no, it does ChangeTurf, WTF?

**Comment by feemjmeem** [comment]
Just saw this behavior from the shuttle on Delta Station, too... not sure if it's related.
