### ISSUE TITLE
Stuffed legion recipe calls for legion head, requires a legion skull, and what the fuck is that?

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#23927]
Please change the recipe to ask for the right stuff. 
Also, what the fuck is a legion skull? A renamed brain from dismembered heads?

**Comment by RemieRichards** [comment]
An item that does nothing and isn't spawned.

**Comment by Iatots** [comment]
wew lads

**Comment by FantasticFwoosh** [comment]
It is something, its a food that heats you up

**Comment by Iatots** [comment]
fwoosh are you seriously shitposting on months-old issues now?
