### ISSUE TITLE
Built a thristy thirsty hydroponics tray

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#23939]
I built some hydroponics trays with super matter bins and similar tier components. They spawned in with 300/300 water, but kept accepting more. They were also linked through wirecutters.

**Comment by Davdichan** [comment]
Irrigation tubes is known to waste water, I don't know what the diminishing returns are but it's definitely not treating all the trays as one big pool but rather checking the linked trays if anyone is thirsty and just pushing smaller and smaller amounts from tray to tray as each keeps/eat some of the water regardless of being full.

**Comment by kriskog** [comment]
No longer an issue.
