### ISSUE TITLE
Fireplace flame overlay broken

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23937]
Add wood/paper and light, does not produce any visual effect, but still makes sounds.

**Comment by jughu** [comment]
@coiax just used it this round it did create visual effect i guess since you used a paper bin it wasnt enough fuel

**Comment by bgobandit** [comment]
@coiax is this still happening

**Comment by Qustinnus** [comment]
Overlay is extremely subtle on low fuel amounts, paper adds VERY little fuel and thus causes this.
