### ISSUE TITLE
Emagged cleanbots don't do any damage.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#23943]
As the tittle says, if a cleanbot goes up to a downed person and sprays acid, the acid will do no damage, nor will it damage clothing.

**Comment by PKPenguin321** [comment]
If the victim is armored, they take just about no damage, but their clothing and items do. If the victim is nude, they go into crit in like 4 sprays. Cleanbots use the actual acid act proc.

Needs testing.

**Comment by Durkel** [comment]
I just spawned five emagged cleanbots in the thunderdome and laid down for a minute clothed and then unclothed. Nothing happened.

**Comment by PKPenguin321** [comment]
Guessing Phil's changes to acid broke it.
