### ISSUE TITLE
List of items missing sprites, using coder sprites, or missing inhands

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#23942]
Maybe this isn't the best place to do this but it'd be nice to have a master list so when someone wanders into coderbus saying they want to help sprite we have somewhere to point them. I know there are like a thousand more so just comment her with missing things and I'll add them I guess.

**Things using placeholders/coder art**
- [ ] Door remotes (they use gangtools currently)

**Things missing inhands:**

- [ ] Severed Limbs

- [ ] Changeling tentacle

- [ ] Security gas masks currently use normal gasmask inhand

- [ ] Bags of holding use normal bag inhands

**Comment by XDTM** [comment]
Adrenal/freedom implants

**Comment by Repukan** [comment]
Security gas masks use normal gasmask inhand

**Comment by PKPenguin321** [comment]
Door remotes being gangtools is fine imo, metabreaker and it's not like we're using gang anyways

**Comment by ChangelingRain** [comment]
Bags of holding don't have a unique inhand; they just use the backpack sprite.

**Comment by MrPerson** [comment]
This shouldn't be an issue, it should be a project

**Comment by SweaterKittens** [comment]
Oh yeah this would be a really good use of the projects tab. It'll be nice having this all in one place either way

**Comment by AnturK** [comment]
Open an issue with the sprite name and ping me to add it to the project.

**Comment by AnturK** [comment]
https://github.com/tgstation/tgstation/projects/6

**Comment by PKPenguin321** [comment]
Oars for lavaland boats use the same inhands as metal rods as far as I can tell

**Comment by PKPenguin321** [comment]
Lockboxes need inhands (for example, mindshield implants lockbox)
