### ISSUE TITLE
Fried foods are tiny, regardless of their origin item

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23949]
- Fry firesuit
- Firesuit is now tiny item, eat to expand into full firesuit.

**Comment by jughu** [comment]
FEATURE

**Comment by PKPenguin321** [comment]
It's like the reverse of tiny things that grow when you add water

**Comment by Iamgoofball** [comment]
wtf

@kevinz000

**Comment by 9600bauds** [comment]
THE RETURN OF
BLUESPACE
WRAPPING
PAPER
