### ISSUE TITLE
Janitor soap stone / dull chisel useless because 0 charges (cannot remove messages)

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#23954]
The janitor spawns with a 0 use dull chisel which I assume is meant to erase soap stone messages. Well, it can't because it has 0 charges, or at least that's what the game reminds you of if you hit a soap stone message with it.

**Comment by KorPhaeron** [comment]
@coiax

**Comment by coiax** [comment]
We might have been running on the pre revert soapstones at this point. I will check on master.

**Comment by coiax** [comment]
yeah, not present on master anymore. probably was pre-revert.
