### ISSUE TITLE
Welding helmet dos

### ISSUE THREAD

**Issue by rainbowjose** [tgstation/tgstation#23967]
If you start fast clicking on welding helmet, or, in other words, take off and wear by the hud button, then servers starts lagging. 

[https://cloud.githubusercontent.com/assets/25691138/22835138/c9bb74ba-efc8-11e6-8b76-40d456a6773a.png](scr)

**Comment by kevinz000** [comment]
atleast he didn't do it to us this time.

**Comment by PKPenguin321** [comment]
Could probably be fixed by putting a cooldown on the helmet toggling action button

**Comment by Cyberboss** [comment]
The lag isn't generated from the clicks actually, it's all guarded. The problem is apply/unapplying the vision overlays

**Comment by PKPenguin321** [comment]
yeah i figured that much, but a cooldown on the helmet toggling to just pace the overlays would probably be sufficient

**Comment by CosmicScientist** [comment]
What happens if you put it on and take it off a lot with it down? Wouldn't it cause the same effect?

A draconian way of fixing that... if that is a problem, might be to not let you take it off without it being up?

I dunno, just speculating like a madman.

**Comment by rainbowjose** [comment]
Thank you for priority. I can show you how it works, if you want.

**Comment by PKPenguin321** [comment]
>What happens if you put it on and take it off a lot with it down? Wouldn't it cause the same effect?

Just make taking it off flip up the helmet

**Comment by kevinz000** [comment]
Actually you know what would be a better idea?
Adding a click cooldown of 1 ds because anyone clicking faster is most likely using an autoclicker.

**Comment by Cyberboss** [comment]
It already has that, the problem is the overlays.

**Comment by rainbowjose** [comment]
So what?

**Comment by Cyberboss** [comment]
On my to-do list @lzimann

**Comment by Cyberboss** [comment]
Potentially fixed with #23922? Could you test this locally to see if it's still an issue?

**Comment by rainbowjose** [comment]
Resolved.
