### ISSUE TITLE
you cannot do mouth surgery

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#23975]
it just slaps them in the head.

**Comment by bgobandit** [comment]
did you have harm intent on

**Comment by Armhulen** [comment]
no, or at least I HOPE THEY DIDN'T.
i asked two people to remove my tongue and both of them said they were on help and after selecting mouth it slaps them

**Comment by WJohn** [comment]
Just did this on basil rev:
Server revision compiled on: 2017-02-11
3762403553296fd1c24d40b427b973efc32f9a34 

Works completely fine.

**Comment by Armhulen** [comment]
i was an abductor/lizard while doing this. maybe that's related?

**Comment by WJohn** [comment]
Who or what were you performing this on? Any information about what you two were and what tools you were using will help.

**Comment by Armhulen** [comment]
i don't know what they were up to, but a borg and a doctor tried removing my tongue. they kept saying "once i select mouth, it just hits you"
i think they were able to put on the drapes the first time, but they accidentally took it off and every time after it'd just hit you.

**Comment by XDTM** [comment]
Having an active surgery already can make other surgeries fail, usually closing with drapes + cautery fixes it.

**Comment by Armhulen** [comment]
ah, I think some borg tried to do a brain surgery OR SOMETHING. I'll just assume it was their fault and that they're both retarded
