### ISSUE TITLE
Odd smoothing consistency

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#24004]
I'm guessing the pod shouldn't be smoothing with the windows/airlocks here

![untitled](https://cloud.githubusercontent.com/assets/8171642/22859280/4bc15c1e-f0a4-11e6-8fe2-6711fe16386c.png)

**Comment by Kromgar** [comment]
Oh god its hideous

**Comment by optimumtact** [comment]
so smooth

**Comment by WJohn** [comment]
For some reason these things smooth with everything else? Why? They should only be able to smooth with themselves.

**Comment by ChangelingRain** [comment]
iirc kor requested they be able to smooth with windoors and such

**Comment by Kromgar** [comment]
BUT WHY? They have a totally different aesthetic to everything else ingame

**Comment by Cyberboss** [comment]
@KorPhaeron

**Comment by Thunder12345** [comment]
Just make them smooth with survival pod windows and not every other window then
