### ISSUE TITLE
MAD GETS FOR SINGULO

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#24000]
# memez

**Comment by kevinz000** [comment]
BAN

**Comment by Chnkr** [comment]
gitban in 3..2..1..

**Comment by Iamgoofball** [comment]
this is time honored tradition

**Comment by kevinz000** [comment]
FUCK YOU GOOF!!

**Comment by vcordie** [comment]
this night will go down in coderbus history as the night goofball gets gitbanned

**Comment by kevinz000** [comment]
You say that like he wasn't gitbanned before.

**Comment by PKPenguin321** [comment]
now you've gone too far
