### ISSUE TITLE
Hulks slip on lube, but only if they're buckled to a vehicle

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#24049]
- Have lube on the ground
- Be a hulk
- Walk on it and notice nothing happens
- Buckle into any vehicle (scooter, skateboard, janicart, etc.)
- Ride over lube
- >You slipped!
- Don't actually get stunned by fly off in a direction and spin around

**Comment by XDTM** [comment]
Makes sense tbh

**Comment by Cyberboss** [comment]
Duplicate of #23558
