### ISSUE TITLE
R&D Materials Duplication Bug

### ISSUE THREAD

**Issue by Memelizard** [tgstation/tgstation#24050]
When holding a stack of materials (Diamonds specifically, unsure if it affects other materials) greater than 1 and alt clicking to take one item out of the stack with a free hand, I managed to duplicate a stack of diamonds from 8 diamonds up to 13 diamonds.

So basically what I did was.
1. Picked up 8 diamonds
2. Alt clicked diamonds with spare hand to bring up text box.
3. Entered 1 into the text box
4. Pressed confirm on text box
5. The one diamond was removed, but all the diamonds from my free hand before the removal came too, causing a dupe.

PKP remotely confirmed it works with any value, not one.

**Comment by PKPenguin321** [comment]
Works with any value, not just 1. Just make sure it's in your hand when you alt click it and whatever value you enter is added to the stack. High priority

**Comment by PKPenguin321** [comment]
After more testing it's not ANY value, but any value *that is lower than the current value in the stack.* So if you have a stack of 15, hold the stack in your hand, and enter 14, you'll come out with a stack of 29.
