### ISSUE TITLE
Progress bars

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#24056]
Racks.
https://gyazo.com/f01a6fdc5cff0fdfd269f68140c309c9

**Comment by jughu** [comment]
NOT A BUG

your mass constructing it by mass clicking it??

**Comment by WJohn** [comment]
I guess it'd be nice if it didn't spam the same progress bar for the action you are already doing.

**Comment by Cyberboss** [comment]
This is a bug. Every single progress bar that doesn't check for the same action is a bug. Keep reporting these.
