### ISSUE TITLE
Split gender reassignment between groin and chest.

### ISSUE THREAD

**Issue by The-clown-known-as-Pepe** [tgstation/tgstation#24085]
We'll finally be able to have those diccgrillz and cuntboiz.

**Comment by PKPenguin321** [comment]
What?

**Comment by PKPenguin321** [comment]
Oh so like gender reassignment but just for boobs

Yeah that'd be cool if we still had that surgery at all

**Comment by lzimann** [comment]
Gender reassigment surgery is no more.
