### ISSUE TITLE
changeling vision (augmented eyesight) is actually x-ray, cannot be turned off

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#24086]
It says on the wiki it's meant to be heat+dark, but it's straight up x-ray, combine with mesons for easy mode. 
Even if that were intended, it cannot be turned off.

**Comment by PKPenguin321** [comment]
@KorPhaeron touched eyes

**Comment by GunHog** [comment]
Thermals usually include night vision, with mesons that gives you turfs + mobs.

**Comment by Iatots** [comment]
I could clearly see objects too

**Comment by Emilc4h** [comment]
I had the same issue when I rolled changeling like a week ago. Couldn't turn it off, saw everything in x-ray, and it didn't deactivate until I died a horrible death and revived.

**Comment by msgerbs** [comment]
Working on a fix for this. Do we want changeling Augmented Eyesight to be x-ray like it currently is, or do we want to "nerf" it and make it actually function as thermals? (complete with that godawful space texture everywhere)
