### ISSUE TITLE
Hulks can fire the pneumatic cannon

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#24081]
Seems unintended considers hulks cant fire anything with a "trigger".

**Comment by PKPenguin321** [comment]
I think this is a dupe

**Comment by Supermichael777** [comment]
considering they can operate the air-tank valve I don't see the problem. Tis a brutish weapon, dangerous and unpredictable .

**Comment by Iatots** [comment]
only if they have a decent chance of abusing the valve too much and having it explode in their face.

**Comment by Arianya** [comment]
As I recall the pneumatic cannon is programmed as its own snowflakey thing instead of a gun.

It'd probably be relatively easy to make a snowflake check against it specifically.

**Comment by Robustin** [comment]
@Supermichael777 

This isnt about realism, its about balance. The whole tradeoff for hulk goes out the window when they can one-shot you from 5 tiles away.

**Comment by Screemonster** [comment]
https://github.com/tgstation/tgstation/blob/74f0214a14911ada72bd7a583bff02d347551815/code/modules/mob/living/carbon/human/human_helpers.dm#L137

Probably easiest to copypaste this proc, as sleeping carp users being able to fire the cannon is probably an oversight too.

**Comment by jughu** [comment]
What sbout flamethrowers 🤔
