### ISSUE TITLE
The Arena shuttle is weak to singularities

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#24089]
![image](https://cloud.githubusercontent.com/assets/6778786/22910397/b81dcb84-f227-11e6-81df-1e650d933689.png)

This can be a ... problem

**Comment by KorPhaeron** [comment]
Strange. All the turfs used in the mapping are indestructible. That shouldn't be happening.

**Comment by KorPhaeron** [comment]
@AnturK 

You fixed baseturfs right?

**Comment by AnturK** [comment]
Yes, but shuttles inherit  the target's baseturf so you'd have to test it.
