### ISSUE TITLE
Bubblegum stops moving after charging

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#24090]
![image](https://cloud.githubusercontent.com/assets/6778786/22909790/33af01e0-f224-11e6-91f3-c5eb26ee4337.png)

@ChangelingRain fix your shit

#23960

**Comment by Repukan** [comment]
Why didn't you attach your second seclit to your ka?

**Comment by Kromgar** [comment]
@Repukan  

Because that breaks lighting once i put it away

**Comment by Repukan** [comment]
It would be good if bubblegum were disabled until this is fixed. Not only is it free megafauna tier loot, bubblegum is notorious for having the griefiest drops too.

**Comment by jughu** [comment]
Only on valentines day bubblegum does the opposite of slaughter 😏

**Comment by jughu** [comment]
Featur
