### ISSUE TITLE
Malf AI shunting to an APC offscreen in an intellicard

### ISSUE THREAD

**Issue by club5000205** [tgstation/tgstation#24116]
[Note]: # (Please enter the commit hash and active testmerge numbers from the "Show Server Revision" verb if you can. If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

I found out this was possible today, and am almost positive it is a bug. I had an apc under my control as a malf AI. I had the window (the apc window, with the shunting option on it) open and put in the corner of my screen. I was in an intellicard at the time. The person carrying me brought me to the escape shuttle. I got thrown out, and someone started wiping my core files. I hit the shunt button on the window that I had kept open. Keep in mind, the APC was not visible at all at this point. I ended up winning the round because of this bug. I don't want to see it used ever again. Thank you.

**Comment by Cyberboss** [comment]
Fucking magnets
