### ISSUE TITLE
We are still having 5 second rev rounds

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#24124]
I think my last report was closed but it's still happening
- Only one staff head in a rev
- Their internet burps a little too hard near round start
- They briefly go braindead
- Round instantly ends before anything has happened

**Comment by Cyberboss** [comment]
How do you propose we solve this? If someone DCs then we can't expect them to come back

**Comment by JJRcop** [comment]
Why does rev count braindeads as gone anyway?

**Comment by PKPenguin321** [comment]
>How do you propose we solve this? If someone DCs then we can't expect them to come back

When a head/revhead goes braindead, start a timer, maybe like 3 minutes, of grace time for the player to reconnect. After that, another two minute timer is set so admins are pinged notifying them of the braindead so they can throw another player in. If that two minute timer expires and they are still braindead, then truly mark them as "defeated" for the revolution.

**Comment by Kromgar** [comment]
Or you could just you know make an active player a revhead

**Comment by PKPenguin321** [comment]
I'll leave how you do it up to you, I was just throwing out a suggestion

**Comment by MrStonedOne** [comment]
DC's happen a lot actually, we can not assume they won't come back
