### ISSUE TITLE
Lava freezes after the forward base blows up

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#24126]
![image](https://cloud.githubusercontent.com/assets/6778786/22959909/dbba1e36-f307-11e6-881a-20d883c77795.png)

I literally cant even.

It should clearly turn into obsidian afterwards

**Comment by Mindustry** [comment]
Don't know if it still can, but you could blow up a hole to space in that base. Fun stuff

**Comment by bgobandit** [comment]
@Iamgoofball fix your shit

**Comment by Iamgoofball** [comment]
That's not my freezing

**Comment by Iamgoofball** [comment]
My freezing uses a different sprite

**Comment by dannno** [comment]
explosions make heat
heating lava does not make it cool down and become solid
am I missing something here

**Comment by Cyberboss** [comment]
This is even more ghetto than goof's freezing

**Comment by Repukan** [comment]
@Cyberboss this got fixed IIRC
