### ISSUE TITLE
Space bugging the game

### ISSUE THREAD

**Issue by etrenat** [tgstation/tgstation#24137]
Hello, the space is bugging the main lobby picture and other areas please solve this problem guys! Here is a print demostrating the space bugging the Abandoned Ship area.

![wer](https://cloud.githubusercontent.com/assets/25797661/22984535/6607bf40-f384-11e6-9ae8-2409333e5165.png)

**Comment by Kromgar** [comment]
Turn off parallax its aparallax issue

**Comment by etrenat** [comment]
where i turn off the parallax?

**Comment by etrenat** [comment]
?

**Comment by PKPenguin321** [comment]
in the lobby hit character setup then go to the Preferences tab at the top, there's an option for Parallax in there, set it to None or Off or whatever

**Comment by etrenat** [comment]
Thanks.

**Comment by PKPenguin321** [comment]
This issue can be closed
