### ISSUE TITLE
Augmenting someone makes them invisible

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#24130]
The augged limb's sprite is missing or something.

**Comment by Poojawa** [comment]
can confirm this downstream as well.

Humans are hit or miss, depending on any mutations.

**Comment by TrustyGun** [comment]
Dupe??? #23952

**Comment by Cyberboss** [comment]
Yes, but close the other one. @lzimann

**Comment by KorPhaeron** [comment]
https://github.com/tgstation/tgstation/pull/23766/files#diff-919aeecfd27738b229072d09c451cfb1

Not sure why this broke it, since surplus limbs work fine

**Comment by PKPenguin321** [comment]
Fixed by kor, he forgot to tag this

**Comment by Cyberboss** [comment]
@lzimann
