### ISSUE TITLE
Mine bots deal full (40) damage in pressurized environments

### ISSUE THREAD

**Issue by Markolie** [tgstation/tgstation#24136]
I haven't actually tested this on one of /tg/'s servers, but we ran into this issue after porting https://github.com/tgstation/tgstation/pull/19870 to Paradise, and as far as I can tell from the code this issue is also present here.

Because https://github.com/tgstation/tgstation/blob/master/code/modules/projectiles/guns/energy/kinetic_accelerator.dm#L155 is indented one step too far (so it's part of the kinetic_accelerator gun location check) the kinetic projectile deals its full forty damage when it's not fired from a kinetic accelerator (as is the case with mine bots) because the pressure check is never applied. 

If this is actually intended or not the case on the server do close this though - my bad in that case!

**Comment by PKPenguin321** [comment]
That would explain why they're so fucking lethal
