### ISSUE TITLE
Runtime error: Cannot execute null.HasProximity()

### ISSUE THREAD

**Issue by Quardbreak** [tgstation/tgstation#24143]
I don't know what else to say, but there a runtime log
`[22:49:23] Runtime in turf.dm,135: Cannot execute null.HasProximity().
  proc name: Entered (/turf/Entered)
  usr: Archie Richter (sladkoeshka) (/mob/living/carbon/human)
  usr.loc: The floor (84,125,1) (/turf/open/floor/wood)
  src: the floor (84,125,1) (/turf/open/floor/wood)
  call stack:
  the floor (84,125,1) (/turf/open/floor/wood): Entered(Archie Richter (/mob/living/carbon/human), the floor (83,125,1) (/turf/open/floor/wood))
  the floor (84,125,1) (/turf/open/floor/wood): Entered(Archie Richter (/mob/living/carbon/human), the floor (83,125,1) (/turf/open/floor/wood))
  Archie Richter (/mob/living/carbon/human): Move(the floor (84,125,1) (/turf/open/floor/wood), 4)
  Archie Richter (/mob/living/carbon/human): Move(the floor (84,125,1) (/turf/open/floor/wood), 4)
  Archie Richter (/mob/living/carbon/human): Move(the floor (84,125,1) (/turf/open/floor/wood), 4)
  Archie Richter (/mob/living/carbon/human): Move(the floor (84,125,1) (/turf/open/floor/wood), 4)
  Archie Richter (/mob/living/carbon/human): Move(the floor (84,125,1) (/turf/open/floor/wood), 4)
  Sladkoeshka (/client): Move(the floor (84,125,1) (/turf/open/floor/wood), 4)
  Sladkoeshka (/client): .moveright()`

Also, he spams this to me!

**Comment by Cyberboss** [comment]
Fixed by my proximity refactor @lzimann
