### ISSUE TITLE
You can't rename the Proto-kinetic Accelerator with a pen

### ISSUE THREAD

**Issue by Emilc4h** [tgstation/tgstation#24141]
Super minor and cosmetic but I was reminded of it while browsing old PRs. Since several months ago I've been unable to rename my PKA, and I don't think it was ever intentionally removed or anything. Clicking on it with a pen just... doesn't do anything.

**Comment by kevinz000** [comment]
@lzimann no longer an issue tested on bagil at thunderdome with adminspawned pen/KA
