### ISSUE TITLE
Title screen is not visible on 510 and space broken

### ISSUE THREAD

**Issue by KillingTorcher** [tgstation/tgstation#24153]
**Problem Description**: On latest stable 510 the title screen isn't visible and when you travel in space out of view of the station you become invisible

**What did you expect to happen**: The title screen to be visible and you not to pull a houdini disappearing act when you move out of view of the station

**What happened instead**: The title screen wasn't visible, and when I observed and moved outside of view of the station I became invisible

**Why is this bad/What are the consequences**: Because a lot of people still use 510

**Steps to reproduce the problem**:
1. Install Byond 510.1347
2. Join the server, notice no title screen
3. Observe and go outside of view of the station. Notice you are no longer visible.

**Server**: Tested on Bagil and local git

**Revision**: What revision was the server running? be2b80ca78f5af791a3a6d36eb5cbfcc1194b185

**Possibly related stuff** (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?):

**Comment by Kromgar** [comment]
Did you turn off parallax?

**Comment by KillingTorcher** [comment]
parallax isn't 510-friendly?

**Comment by KillingTorcher** [comment]
Disabling it did not fix the title screen until I rejoined after having disabled it, but it does fix the disappearing problem. There were some weird issues with upgrading darkened areas, however. When they are supposed to go off screen, there's a delay before they disappear.

**Comment by KillingTorcher** [comment]
In general there seemed to be problems with client eye updating

**Comment by optimumtact** [comment]
You're better of going with 511, it's basically required, although nobody has officially come out and said so yet

**Comment by Cyberboss** [comment]
We're done with 510 @lzimann
