### ISSUE TITLE
Pod Capsule Issue

### ISSUE THREAD

**Issue by Daturix** [tgstation/tgstation#24155]
Using the pod capsule, 5x5 with you in center, when used at the edge of lavaland as such giving enough space but the side of the pod is the further tile you can go will use the capsule, small animation of smoke and red dust (ash storm? dont know) but no pod will be created.

Visual because im bad at explaining.
oooooN
oooooN
ooXooN
oooooN
oooooN

o empty space
X you 
N outside the physical map

**Comment by Cyberboss** [comment]
ugh, this must be a dmm_suite bug
