### ISSUE TITLE
Ninjas using their cloak have their socks visible

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24151]
![image](https://cloud.githubusercontent.com/assets/609465/22999650/7f98b234-f3d4-11e6-8224-4fda54b40a0e.png)

be2b80ca78f5af791a3a6d36eb5cbfcc1194b185 

RIP ninja invisibility.

**Comment by Militaires** [comment]
this is hilarious

bug of the year

**Comment by PKPenguin321** [comment]
Ninja invisibility is shit now anyways, barely even makes you transparent
