### ISSUE TITLE
The sky bulge gets incredibly fucky in zero G

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#24156]
Tossing the sky bulge at a mob in zero gravity makes it hit 6+ times, if aimed behind the mob. This near instantly kills airlocks, if not kills them and objects behind them, kills nearly all non-godmoded mobs. It gets really fucky at certain angles, and can destroy multiple objects including airlocks in a single toss. I can make a webm to showcase if necessary, but http://puu.sh/u5zsn/607dbc27bc.png is a minimum description of what I'm talking about. It can also net 2-3+ hits if you target behind a mob/airlock even with gravity.

Double note, it can duplicate itself multiple times into your hand as an invisible object while leaving a spare third on the ground during zero-g at the right throwing angle. http://puu.sh/u5zRI/ff9c879d4b.jpg

A low quality webm showcasing it. http://puu.sh/u5Beh/9c1465e1cd.mp4

**Comment by Haevacht** [comment]
Cannot reproduce on my local even in a flight suit will try again with a more up to date thing later.

**Comment by ShizCalev** [comment]
Will close in a week without another repo.
