### ISSUE TITLE
Moving a shuttle to Lavaland makes it go dark

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#24167]
Usually shuttles are on full-bright, much like space. However, landing a shuttle on Lavaland makes it lose its full-bright effect.

**Comment by SgtxRootbeer** [comment]
When it's on the station, it has light from spess, or the sun coming in through the windows.
When it's on a planet, there is no sun (due to lavaland's ashy clouds) and without a light in the shuttle, it gets dark.

**Comment by XDTM** [comment]
Shuttles should not have natural lighting at all tbh. Map some lights in the existing ones, and maybe add a gimmick shuttle that is permanently dark.

**Comment by Kromgar** [comment]
@XDTM Its fucking agony being a shadow person because of the wish granter and getting on the shuttle WHICH IS PERMANENTLY BRIGHT

**Comment by XDTM** [comment]
what if full clothing protected you from light

**Comment by SgtxRootbeer** [comment]
No, hardsuits must offer light protection.

**Comment by Sligneris** [comment]
@XDTM Then either make shuttles full-bright, or allow light frames to be placed on the shuttles. Cause the current setting makes no sense.
