### ISSUE TITLE
Old secret satchels string occasionally malforms entries.

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#24178]
The secret satchel system stores old stachels in a single huge string formated like this:

x cord | y cord | item # x cord | y cord | item # .... [note there are not actually spaces]

For some reason that trailing # sometimes is lost on old entries, and as a result the two entries run together and have to be trashed.

A note to myself to fix this, or to implement a json file like I totally should have initially.

**Comment by Cyberboss** [comment]
@Incoming5643

**Comment by kriskog** [comment]
These are no longer stored
