### ISSUE TITLE
Ruins can be spawned right up to the map transition point.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#24182]
![](http://i.imgur.com/7CtA8rY.png)

This means there is no room to sidle through the very bottom. Furthermore, it's very jarring that the ruin just vanishes from sight entirely even if there were barely enough room to move under it.

Ruins should spawn at least 15 tiles from the map edge so you both have a bit of breathing room, and so they don't jarringly vanish from sight when you leave the z level.

**Comment by Razharas** [comment]
I support this message

**Comment by Cyberboss** [comment]
@lzimann Not my fault but assign me anyway

**Comment by Mervill** [comment]
This should be as easy as

wherever it's appropriate
```
#define SPACERUIN_MAP_EDGE_PAD 15
```
modules\mapping\ruins.dm (Lines 35 & 36)
```
var/width_border = TRANSITIONEDGE + SPACERUIN_MAP_EDGE_PAD + round(ruin.width / 2)
var/height_border = TRANSITIONEDGE + SPACERUIN_MAP_EDGE_PAD + round(ruin.height / 2)
```
