### ISSUE TITLE
Bluespace Mesh Issues

### ISSUE THREAD

**Issue by GunHog** [tgstation/tgstation#24183]
![image](https://cloud.githubusercontent.com/assets/4955510/23053974/b2fe5268-f4a2-11e6-927b-7cd50652fec9.png)

I deconstructed artifical bluespace crystals, which are supposed to get a limited amount of mesh. I got none. Also, some material levels for the mesh are incorrectly set, preventing construction of items that now require it.

@XDTM

**Comment by XDTM** [comment]
Welp, i'll fix it asap

**Comment by XDTM** [comment]
@GunHog Couldn't reproduce not getting mesh from crystals, both normal and artificial.

**Comment by GunHog** [comment]
I was perhaps mistaken from that. Still, I forgot you could simply insert them into the protolathe.
