### ISSUE TITLE
The water in beach dome black for some reason

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#24193]
![image](https://cloud.githubusercontent.com/assets/6778786/23052189/60243364-f49d-11e6-962a-b41ff02e2198.png)

![image](https://cloud.githubusercontent.com/assets/6778786/23052202/746aca0e-f49d-11e6-9157-6cb70d960599.png)

And a goliath inside?

**Comment by Repukan** [comment]
Monsters always spawned inside

**Comment by coiax** [comment]
No, that was fixed. Monsters shouldn't be inside ruin templates anymore.

**Comment by Repukan** [comment]
My anecdotal experiences go the opposite way.

Although a beach dude beating the everliving shit out of a Goliath with a pickaxe is fun to watch

**Comment by WJohn** [comment]
I'm guessing that the area doesn't completely cover the ruin.
