### ISSUE TITLE
Space cleaner washes off the fried foods apperance

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24205]
![image](https://cloud.githubusercontent.com/assets/609465/23085900/4203a746-f562-11e6-9ed4-7e4b0fcc7d9f.png)

This is post space cleaner grenade.

Server revision compiled on: 2017-02-17
The following pull requests are currently test merged:
#24132: 'Ports some low level New()s to Initialize' by Cyberboss 

Based off master commit:
d951c125a1d3a02b83829263b9e2285bb86be029

**Comment by XDTM** [comment]
The deep fryer sets the atom color manually which might be interpreted as WASHABLE_COLOR_PRIORITY and deleted by space cleaner. Should use the proper procs to set the right priority.

**Comment by Iamgoofball** [comment]
Didn't know there was procs

**Comment by Mindustry** [comment]
This is pretty funny tbh

**Comment by MMMiracles** [comment]
its just cleaning off the grease, obviously.

**Comment by bgobandit** [comment]
feature

**Comment by Tungul** [comment]
I just reproduced this bug in 742fcf0ffea1012ef7906222695461b85b7f9396, for whatever that's worth.
