### ISSUE TITLE
Mapspawned portable air pumps are broken

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#24202]
@Cyberboss Nobody touched the atmos code recently.

**Comment by Cyberboss** [comment]
@AnturK Are you sure about that? They look fine to me

**Comment by AnturK** [comment]
Yep, there were ahelps from scientists for the few rounds i was on, manually spawned ones worked flawlessly, mappped in didn't didn't change the air contents in any way, Map was box, maybe it's just mapping issue not the New move.
