### ISSUE TITLE
Freon flood crashed the server

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#24214]
Although there was kudzu growing at the same time but regardless 11pm est bagil 2/17

**Comment by Iamgoofball** [comment]
we need more reproduction steps

Active testmerges?

**Comment by Kromgar** [comment]
I dunno can't you check the logs?

**Comment by Iamgoofball** [comment]
No, we can't.

**Comment by Kromgar** [comment]
I'll check one the server is done crashing on bagil

**Comment by Iamgoofball** [comment]
It's important since we've been doing loads of back end processing changes and this could be any number of issues

**Comment by Kromgar** [comment]
![image](https://cloud.githubusercontent.com/assets/6778786/23090566/c22909f0-f56e-11e6-97c7-d63c6b530439.png)


Don't open dead inside 

Server right niow

**Comment by Kromgar** [comment]
Doesn't look like anything is testmerged

**Comment by XDTM** [comment]
Kudzu is very crashy, might have been that.

**Comment by optimumtact** [comment]
This is a completely useless bug report
