### ISSUE TITLE
Mass Hallucinations affects z-levels beyond the station and Golems don't heal stamina damage

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#24212]
Long story short, buttons got pushed and Lavaland golems get knocked out forever by the mass hallucination unless adminhealed, which still leaves them with the health indicator with the crit indicator.

No screenshots because someone pressed petsplosion enough times to crash the server

**Comment by XDTM** [comment]
The indicator is a hallucination and not related to stamina damage.
