### ISSUE TITLE
You can crash the server with bluespace satchels of holding

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#24220]
If you manage to get 4k or 5k ore in a satchel and dump it... or pick it up rip server

![image](https://cloud.githubusercontent.com/assets/6778786/23090566/c22909f0-f56e-11e6-97c7-d63c6b530439.png)

**Comment by PKPenguin321** [comment]
So it should probably have some kind of upper limit, huh? Shame

**Comment by optimumtact** [comment]
Yes man what the hell, how did this get in
