### ISSUE TITLE
Please fix windoors

### ISSUE THREAD

**Issue by Keofox** [tgstation/tgstation#24231]
When windoors being destroyed, they will drop 2 glass shards and 2 metal rods instead of 5, that needed for building it again. And further, they will drop 2 cable piece instead of 1

**Comment by WJohn** [comment]
Lots of things don't drop as much metal as used to construct them, such as wall girders.

**Comment by Iatots** [comment]
>  And further, they will drop 2 cable piece instead of 1

Does this actully generate more cable than used? that seems like a bug to me

**Comment by Anonmare** [comment]
Don't windoors have some fucky construction? Like, the pre-built sprite isn't a good indicator of how it will look when finished?

**Comment by Iatots** [comment]
Have not encountered anything like that while building a bunch of them a week ago.
