### ISSUE TITLE
Drawn canvas are invisible to other players.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#24241]
![fix your shit](https://cloud.githubusercontent.com/assets/4581352/23094826/b75b8230-f5f7-11e6-8fff-b21441e88dc9.png)

Other people couldn't see the canvas, no one at all.

EDIT: Attitude fixed.

**Comment by RemieRichards** [comment]
Well it hasn't, because observers/adminghosts used to record people drawing.
Not to mention I know for a fact it did work, because I tested it.

You fix your fucking attitude.

**Comment by Onule** [comment]
Sorry, got real upset when this happened, and also realizing that on previous rounds, no one really saw any other drawings I did.

**Comment by CrAzYPiLoT-SS13** [comment]
An issue on Paradise was opened about this like 2 years ago. Still running,
I see.

**Comment by RemieRichards** [comment]
@CrAzYPiLoT-SS13 would have really helped to, you know, get it to the author?

Anyways, this is an issue with byond itself, every new pixel added to a canvas builds a new image (yikes!), but byond is obviously skipping out on sending them sometimes, I know there's a few workarounds to FORCE images to go to clients, and that's what we'll have to do for canvases.

**Comment by MrStonedOne** [comment]
Fixed in 512 when lummox fixed blend issues.
