### ISSUE TITLE
There's enough problems with getting the game to display properly that we should offer in game troubleshooting

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#24247]
Over the last X months we've stuffed in plenty of features (mostly relating to **planes**) that work inconsistently depending on a lot of client settings. Currently these settings are:

1. Whether they're using 510 or 511 (and within 511, if they're using certain versions)
2. What kind of graphics card they have, how recent their drivers are, and if they have a second graphics card.
3. How much of DirectX they have installed.
4. If they have fancy space on.
5. What their OS is.
6. Maybe others?

Nothing in game references these problems, or offers any solutions. A way of telling these people how to fix the problems that isn't reliant on people visiting the website would be good.

**Comment by KorPhaeron** [comment]
@tgstation/commit-access

**Comment by AnturK** [comment]
Not sure what you mean. A help page with common issues ? F1 directs to ahelp for a reason. Most of these are volatile enough the information will be outdated by the time players see it. Maybe with some config file.

**Comment by optimumtact** [comment]
Stop tagging things that aren't critical with the tag.

**Comment by KorPhaeron** [comment]
Large numbers of people being unable to play a game they've been playing for years and /tg/ not being stable enough to serve as the standard codebase feels critical to me

Tags obviously don't matter much though

**Comment by Incoming5643** [comment]
For context a server that wanted to run tgcode as a base is now instead running on somewhat recently rebased yog code over this sort of stuff.

It's a bad look, it's gotta be handled. Optimally by making sure these sorts of situations don't come up to begin with, but lacking that we need solutions to keep people from just giving up.

First impressions matter a lot, always have.

**Comment by Cyberboss** [comment]
The admin memo about the DXSDK should be shown to players.

Or is it not an admin memo? I'm not sure

**Comment by lzimann** [comment]
It is an admin memo. Maybe we should put in the MOTD.

**Comment by Marflowerose** [comment]
Is this related to the bug where Parallax (Fancy Space) makes things invisible with Mesons or when moving to a wrong spot?

**Comment by Bawhoppen** [comment]
we were focused on solely stability for like 2+ years

**Comment by Cyberboss** [comment]
Anyone have issues if I close this?
