### ISSUE TITLE
APC's don't install properly

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#24240]
APCs fail to install properly in new rooms. A bare APC frame installs onto a wall already completed and indifferent of what the room is named and even tinkering with it after the fact fails to power equipment in the room.
(Would also stop hindering malfs by destroying their hacked APCs)

**Comment by Onule** [comment]
You can sort of duplicate metal and cable coil with this. Trying to remove it with a welder won't delete it, but still creates an APC frame. Placing cable where it's terminal would be, then cutting it, spawns a terminal..
