### ISSUE TITLE
Flashlights (and maybe others) don't light the new area after a shuttle moves

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#24260]
Repro:

Spawn as shaft miner
Turn on flashlight
Send shuttle to lavaland
Shuttle remains dark after transitions

**Comment by optimumtact** [comment]
is vg lighting testmerged?

**Comment by Cyberboss** [comment]
This is my local, updated master

**Comment by XDTM** [comment]
Very noticeable on the lavaland outpost, it has static lamps that stop working after launch.
