### ISSUE TITLE
Finish porting to forceMove

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#24261]
Regex: [\\.\t ]loc[\t ]*=(?!=)

>766

wew

**Comment by XDTM** [comment]
So what does forceMove do that loc doesn't

**Comment by Cyberboss** [comment]
Everything that moving something somewhere should (Entered,Moved,Crossed, etc...)

**Comment by optimumtact** [comment]
@XDTM mostly it makes sure everything that expects a call back when something moves, gets a callback.

Inventories, buckling, vehicles etc etc

**Comment by vuonojenmustaturska** [comment]
ree
