### ISSUE TITLE
people buckled in xeno nests can still interact with other mobs

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#24271]
If two people are strapped in next to each other they can release each other
they can also punch xenos

**Comment by WJohn** [comment]
Known bug, I think this happens with beds, too. I believe that xenos are also able to interact with people even when lying down (not buckled). Capable of disarming/slashing like that.

**Comment by PKPenguin321** [comment]
Interacting with things while buckled to a bed isn't the bug, it's the xeno nest not counting as a restraint while buckled that is.
