### ISSUE TITLE
Stings working through hardsuits

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#24273]
Saw someone get mutestung through a hardsuit, I think this is a bug and if it isn't then someone should consider making stings not work through hardsuits.

**Comment by kevinz000** [comment]
why is this still an issue if it's not a bug?

**Comment by BeeSting12** [comment]
Idunno but it should be a bug if you ask me. Why would a sting work through hardsuits but not a hypospray?

**Comment by jughu** [comment]
Needs a i ded tag
But yeah it never was a bug in the first place but i wouldnt mind if this would be "fixed" 😏

**Comment by XDTM** [comment]
It also works when cuffed

**Comment by BeeSting12** [comment]
it sorta makes sense to work when cuffed but not through a suit that shouldn't have any holes in it.

**Comment by xxalpha** [comment]
Because everyone has a hardsuit, it would be a huge nerf to changelings.

**Comment by jughu** [comment]
Atmos x1 engineering x2 ce x1 sec x2 cap x1 hos x1 cmo x1 rd x1 traitors x 2(as they can buy with their tc)
They slow you down plus only engineees are the ones wearing it 24/7 sometimes with rd and xaptain

**Comment by BeeSting12** [comment]
^what jughu said. and honestly changelings are powerful enough without stings. 
>ranged stun
>armblade

**Comment by KorPhaeron** [comment]
Not a bug
