### ISSUE TITLE
There's no way to put in cybernetic/robotic eyes as nukeops

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#24294]
They don't work with autoimplanters :/

**Comment by XDTM** [comment]
Don't ops have a surgical table? There is a way if you can do it manually :^)

**Comment by KorPhaeron** [comment]
You have a surgery table and full set of tools

**Comment by PKPenguin321** [comment]
Auto implanters do need a rewrite and to be fixed to spawn with nuke ops implants though
