### ISSUE TITLE
Custom species organs are broken.

### ISSUE THREAD

**Issue by Quardbreak** [tgstation/tgstation#24317]
Well, in first, i trying to add to ashwalker lizards a night vision eyes.
When i testing in game, lizard still have default eyes type (and i know, they must have LIZARD tongue, but why they have default tongue type?)

**Comment by Quardbreak** [comment]
Still need learn english for posting issues, oh hell. 👌

**Comment by Incoming5643** [comment]
I just checked and lizards seem to be getting the right tongue "the forked tongue"

When you want to make an organ differ between races you have to take that organ out of a general list somewhere in human/New and put it into "mutant_organs" in the mob's species datum.

**Comment by Supermichael777** [comment]
in  tgstation/code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
after line 41 put in a line like
mutant_organs = list(/obj/item/organ/tongue/lizard, /obj/item/organ/eyes/nightvision)

Obviously you need to change the path on those eyes to match the eyes your making. VV the mob to check its organ list (right mouse menu on the mob).  Night vision code is old and terrible and runs on see invisible.

**Comment by XDTM** [comment]
There's a mutanteyes var which seems to be used when first generating organs but not on_species_gain, not sure if @KorPhareon did it on purpose.
