### ISSUE TITLE
Delta has no ferry shuttle

### ISSUE THREAD

**Issue by Repukan** [tgstation/tgstation#24320]
Got death squad officer and we were supposed to go station side to kill bubblegum.

Ferry shuttle was not docked. I exploded the door into the control room (which apparently NT cards have no access to) and the shuttle computer showed *Missing*

**Comment by KorPhaeron** [comment]
Deathsquad is bad anyway so this sounds desirable

**Comment by Repukan** [comment]
But what about our high RP™ inspectors?

**Comment by Tofa01** [comment]
All stations should have a Centcomm ferry in my opinion for RP events such as the Centcomm inspectors, ill look into this as soon as the coast is clear regarding other PRs causing map merge conflict issues.

**Comment by Niknakflak** [comment]
I thought it had a ferry, maybe the variable is just set wrong somewhere

**Comment by Tofa01** [comment]
I don't think it has a ferry at all looking at it now, not at least at the arrivals dock where it should be I am working on adding it now should have a PR up in a bit.
