### ISSUE TITLE
Changeling Augmented Eyesight is broken?

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#24322]
I bought it today and used it, and it gave me full xray. It also gave me the same message every time I activated, something similar to "You can see prey through walls now"

Anyways, this looks pretty broken, might be a good idea to look at it.

8:30 pm 2/20/17 EST Bagil

**Comment by ShadowDeath6** [comment]
this is a dupe of another issue I think

**Comment by Emilc4h** [comment]
Dupe of #24086, yessir.
