### ISSUE TITLE
Roundstart crew does not appear on the crew manifest

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#24359]
Roundstart crew does not appear on the crew manifest and has no records, security or medical.

**Comment by lzimann** [comment]
@Cyberboss ?

**Comment by Cyberboss** [comment]
Important question, is it just the photos? Or everything?

**Comment by Sligneris** [comment]
Crew manifest is empty and the roundstart crew doesn't exist at all as far as records are concerned.
