### ISSUE TITLE
Crit overlay does not appear at all

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#24365]
This means that you can see everything around you while you're in crit.
Testmerged PRs:  #24356 
Edit: The nuclear explosion cutscene doesn't appear either.

**Comment by lzimann** [comment]
@Cyberboss probably you(have to test this with the reverts testmerged).

**Comment by Cyberboss** [comment]
Well this make no sense. Did overlays crash?

**Comment by Cyberboss** [comment]
It's this still happening?

**Comment by lzimann** [comment]
Pretty sure it is fixed. Someone ping me in case this is still happening.

**Comment by Hatfish** [comment]
It's happening again @lzimann

**Comment by Cyberboss** [comment]
Consistently?

**Comment by Hatfish** [comment]
Yes.
It might be something to do with explosions, the only times I've noticed it happening were when IEDs had gone off in my face and sent me into crit.

**Comment by Cyberboss** [comment]
Ugh, I'd kill for definitive repro steps

**Comment by Hatfish** [comment]
Seems to be fixed finally.
