### ISSUE TITLE
Uplink implant

### ISSUE THREAD

**Issue by DanteRU0312** [tgstation/tgstation#24375]
Problem Description: If you get an uplink implant from syndicate bundle with implants, it comes empty.

What did you expect to happen: Expected it to have TC.

What happened instead: I think the uplink implant was changed, and now it comes empty and you need to load it with spare TC. But if you get an implant bundle from syndicate bundle, you can't buy any TC to it, because syndicate bundle costs all TC.

Why is this bad/What are the consequences: Useless uplink in the bundle, it should contain TC or bundle contents should be revised.

Steps to reproduce the problem: Become traitor, pray to RNG that you'll get an implant bundle from syndicate bundle, implant yourself with uplink implant, sigh.

Server: Bagil

Revision: Server revision compiled on: 2017-02-23

**Comment by Dorsisdwarf** [comment]
Looks like everyone forgot about the uplink implant bundle, whoopsie

**Comment by XDTM** [comment]
I believe it only accounts for 4 tc. Still, it'll always be useless due to the crate's cost, so they should just be blacklisted.

**Comment by Dorsisdwarf** [comment]
I'd have said this was a flat-out oversight bug myself, Lzi.

Coiax changed uplink implants to be cheaper but not have any crystals in them, Coiax forgot the implant bundle has an uplink implant, uplink implant lost all its TC

**Comment by coiax** [comment]
I did specifically make a precharged uplink implant, I think. Probably missed adding it somewhere though.
