### ISSUE TITLE
Derelict drone shell spawn

### ISSUE THREAD

**Issue by DanteRU0312** [tgstation/tgstation#24376]
Problem Description: Unactivated drone shell is blocking the way

What did you expect to happen: I wanted to get access to SMES

What happened instead: Unactivated drone shell is blocking the way to SMES

Why is this bad/What are the consequences: You can't move this shell, so you can't access the SMES unless you're spawned in that shell/someone else spawns in it/you dismantle the reinforced wall to get access to SMES

Steps to reproduce the problem: Spawn as a derelict drone that not the problem one, go to the Aft Solars.

Server: Bagil

Revision: Server revision compiled on: 2017-02-23
![derel](https://cloud.githubusercontent.com/assets/25978025/23256905/35cb096c-f9e3-11e6-9dff-d16f93629d7e.png)

**Comment by coiax** [comment]
Technical explanation, these are just reskinned "ghost spawn sleepers".

**Comment by RemieRichards** [comment]
@coiax is that to stop "Drone shell has spawned"?
because the drone shell item can do all of the "put ghost in drone" stuff.

**Comment by coiax** [comment]
Actually they just wanted the derelict drone shells to be in the orbit list.

**Comment by RemieRichards** [comment]
... just add drone shells to the poi list then! gosh.
Fix:
* Remove drone spawn sleepers (DUMB)
* Replace with standard drone shells
* Add drone shells to poi list

**Comment by coiax** [comment]
I'd like to move towards the drone solution that other servers have, where drone shells don't normally exist, and drones are just produced on demand for ghosts who wanna drone it up.

**Comment by RemieRichards** [comment]
won't work, too many of our drone players are hitlers, which sadly ruins it for the good ones.

**Comment by coiax** [comment]
normally that'd be countered by good administration...

**Comment by RemieRichards** [comment]
we have way more hitlers than other servers when it comes to drones.
the ratio of drones:hitlers is like, 1:zweiundzwanzig

**Comment by xxalpha** [comment]
How about don't make them dense?
