### ISSUE TITLE
Abductor Beam-in Delay and Alert can be Bypassed

### ISSUE THREAD

**Issue by feemjmeem** [tgstation/tgstation#24381]
1) As abductor scientist, set experiment release point.
2) As scientist or agent, stand on teleport pad
3) Activate emergency teleporter

This can be used repeatedly without substantial side-effects.

**Comment by XDTM** [comment]
Another abductor bug: beaming down creates the overlay even if there's nobody on the pad, which makes it spammable to spook people.

**Comment by AnturK** [comment]
The former is a bug, the latter was intended.
