### ISSUE TITLE
Poster is bad?

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24388]
![image](https://cloud.githubusercontent.com/assets/609465/23281354/dbc5530a-fa14-11e6-8228-65aaf318c5a0.png)

![image](https://cloud.githubusercontent.com/assets/609465/23281360/e1c4f648-fa14-11e6-8d3b-662f6a892dde.png)

@dannno

**Comment by Repukan** [comment]
A e s t h e t h i c

**Comment by dannno** [comment]
fuckin what

**Comment by dannno** [comment]
I don't know what I did wrong help!

**Comment by dannno** [comment]
Oh.
![](http://i.imgur.com/dD0r9g3.png)
