### ISSUE TITLE
you still bleed even if you are bandaged

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#24391]
as in, blood drops, not just the message. I am not sure if this is just a quirk of improvised gauze or not.

**Comment by factoryman942** [comment]
Only difference between improv and proper gauze is the stop_bleeding variable (900 for improv, 1800 for normal) which seems to just affect how long the bandage lasts or something when applied

**Comment by Robustin** [comment]
Youre probably just seeing some lag in how bleeding is updated. I haven't seen this issue at all beyond the few seconds where bleeding is "healing" but still resolving some blood loss.

**Comment by Qustinnus** [comment]
Cannot reproduce.
