### ISSUE TITLE
space has no light

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#24397]
Server revision compiled on: 2017-02-23
6da76d83fd7b5917abe3ff04decfdec9de5a23de 

Looks awfull

![Imgur](http://i.imgur.com/RyfJYe4.png)

**Comment by Mervill** [comment]
Make sure you have the starlight config enabled

**Comment by Incoming5643** [comment]
This is happening live on sybil/basil, space just stops being rendered after a tile or two

**Comment by optimumtact** [comment]
still happening?

**Comment by Incoming5643** [comment]
Still happening. Essentially lighting draw distances apply to space tiles, so if you turn on more lights, you can "see" further into space.

**Comment by MrPerson** [comment]
I just looked into this and I suspect it was fixed because of the lighting redo that was just merged

**Comment by rainbowjose** [comment]
Space have lights now
