### ISSUE TITLE
Progress bars for bags of holding do not disappear

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#24408]
![aspie factory zulu 2017-02-24 113121](https://cloud.githubusercontent.com/assets/8237862/23312629/6d9959ac-fa88-11e6-9734-4f9a31338122.png)
Edit:  This seems to occur when any container is dumped into another one.
Testmerged PRs:  None

**Comment by AnturK** [comment]
@MrStonedOne changed the dumping recently.

**Comment by MrStonedOne** [comment]
has this happened two seperate times in two seperate rounds?

some times timers break and timed things don't happen.

**Comment by Hatfish** [comment]
Yes, it has.
