### ISSUE TITLE
Starkist vendor is invisible on Boxstation

### ISSUE THREAD

**Issue by Mindustry** [tgstation/tgstation#24405]
What it says on the tin etc etc
![starkist](https://cloud.githubusercontent.com/assets/8491500/23291172/3b9b40e6-fa0b-11e6-8369-45b35a69a7b3.png)

**Comment by dannno** [comment]
Should already be fixed, the fuck.

**Comment by dannno** [comment]
![](http://i.imgur.com/eecrZej.png)

????????????????????

**Comment by lzimann** [comment]
Seems to be fixed, maybe it was before server update.
