### ISSUE TITLE
Voice analyzers trigger incorrectly

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#24401]
Voice analyzers trigger when the person who recorded the phrase says anything. As opposed to the phrase being said.

**Comment by Militaires** [comment]
you're probably using the fuckkinnggg VOICE RECOGNITION setting, it has 2 settings, the quote detection which checks for a specific quote said by fukkckckeennnigng anyone or the other one, you have to set it famangerino.

**Comment by Cyberboss** [comment]
This doesn't sound like an issue...

**Comment by XDTM** [comment]
Feature

First time i can use it unironically

**Comment by Cyberboss** [comment]
@lzimann
