### ISSUE TITLE
Space bar kitchen cabinet

### ISSUE THREAD

**Issue by DanteRU0312** [tgstation/tgstation#24416]
Problem Description: Space Bartender has no access to the kitchen cabinet

What did you expect to happen: Expected to open it.

What happened instead: It's not opening.

Why is this bad/What are the consequences: The map is Box Station, i managed to open it on other map, sadly, can't remember which one. So you're supposed to be able to open it on all maps, or exact opposite.

Steps to reproduce the problem: Become the Space Bartender on Box, try to open the cabinet.

Server: Bagil

Revision: Server revision compiled on: 2017-02-24
![default](https://cloud.githubusercontent.com/assets/25978025/23321858/1d6ed22e-fb03-11e6-91a7-18fc76fae7c7.png)

**Comment by lzimann** [comment]
Space bartender is a ruin and it's not related to Box or any other station map.
