### ISSUE TITLE
Auxillary Base Shuttle Landing...

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#24414]
... Is actually capable of turning out like this:

![059056fbb3](https://cloud.githubusercontent.com/assets/12747768/23320991/94e967b8-fadd-11e6-8bb0-1aa107a7158b.png)

Personally, I'd suggest replacing the mining shuttle beacon with two beacons that must be placed in two opposite corners of a 5x7 field, both facing in the direction the shuttle is supposed to face - leaving no room for this kind of error.

**Comment by GunHog** [comment]
Rage. Rage and hate. I do not know how, I do not know when, but I will have a fix for this. Eventually.

**Comment by Sligneris** [comment]
Well, I already suggested one solution I guess.

**Comment by GunHog** [comment]
I gave your suggestion a shot, @Sligneris. It seemed really annoying during testing as well as being somewhat hacky codewise. I think simply fixing the check makes things easier on the players.
