### ISSUE TITLE
Sniper Rifles shooting at 45+ degree angles

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#24415]
1) Aim down range with a sniper rifle
2) Click in front of you
3) Marvel as you shoot almost directly to your right

After 4 mags only one of my bullets actually hit what I clicked on.

**Comment by CrAzYPiLoT-SS13** [comment]
Yeah, this is due to pixel projectiles. I did a fix for this for another
codebase I worked on. I'd have to dig a bit to get it back, but expect a PR
soon.

**Comment by Robustin** [comment]
Thanks!

**Comment by optimumtact** [comment]
How soon is soon

**Comment by kevinz000** [comment]
please fix the damn projectile drift too, jesus fucking christ.
