### ISSUE TITLE
Abductor surgery steps are wrong(?)/abductor surgery is broken

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#24423]
Got multiple ahelps that the steps for doing abductor surgery on the alien paper in the abductor ship is incorrect, and also one ahelp saying that the fourth step in the surgery (the second incision) didn't work and would just attack the patient. Haven't reproduced it myself but have gotten enough ahelps to report it here.

**Comment by GunHog** [comment]
The paper is indeed wrong. When you get to the last step, you must **remove the heart using an empty hand** before you can insert the replacement abductor organ. This is not communicated to the player in any way.
