### ISSUE TITLE
MMIs can't use ripley tools when theyre placed inside the mech.

### ISSUE THREAD

**Issue by DoctorPork** [tgstation/tgstation#24422]
Server revision compiled on: 2017-02-24
a50fd64440c3a0a178bd95fd1c694d182fbc2508 

MMIs can't use ripley tools when theyre placed inside the mech. I replicated it with the person who initially had the issue and then PKP and I replicated it in thunderdome. It's definitely not working.

**Comment by lzimann** [comment]
MMIs and mechs are all sorts of fucked up.

**Comment by LetterJay** [comment]
Yea, I can confirm this. This is with any mech at all. You can walk around, you just can't use any of the weapons.

**Comment by XDTM** [comment]
I think they had to use middle-click instead, although i could be confusing it for another action.

**Comment by octareenroon91** [comment]
issue persists
