### ISSUE TITLE
Explosive spear sometimes fails to be crafted (still taking resources) and might not produce war cry

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#24420]
Sometimes, crafting an explosive spear results in none. 
Also, the war cry is not shouted if the spear is thrown. Does one need to suicide-impale for that? Did not test melee.

**Comment by lzimann** [comment]
I believe the war cry is only when you attack someone melee, and not throw.

**Comment by Qustinnus** [comment]
cant reproduce and war cry is melee only its specified in the text
