### ISSUE TITLE
server hop just doesn't work anymore.

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#24439]
sending you to bagil...
and then it just shows a black screen until you exit.

**Comment by Cyberboss** [comment]
@MrStonedOne Is the config updated properly?

**Comment by Supermichael777** [comment]
reconnecting in general is broken i think the issue lies in that code

**Comment by Jordie0608** [comment]
I believe it was a BYOND issue.

**Comment by optimumtact** [comment]
This was actually an issue with the addresses @MrStonedOne was using

believe it's solved now?

**Comment by MrStonedOne** [comment]
its fixed.

It was namecheap being a meme and converting all of my relative `CNAME`s to absolute `CNAME`s

I'm getting fucking sick and tired of this trend to user friendliness at the cost of functionality.

**Comment by Cyberboss** [comment]
Yeah, I was hoping to test this but the bot automerged it, wew.

**Comment by Cyberboss** [comment]
Replied to the wrong thread whoops

**Comment by Qbopper** [comment]
@optimumtact server hop works fine please close this
