### ISSUE TITLE
Gatfruits do not spawn revolvers

### ISSUE THREAD

**Issue by fizbump** [tgstation/tgstation#24434]
[Note]: # Server revision compiled on: 2017-02-24
10f38a4d1789a07401c35750ffeab39a43d9829a

Gatfruits do not seem to properly spawn a revolver when used in hand. Instead, they just disappear, leaving nothing behind. Tested with a player-grown gatfruit and an admin spawned one with the same result.

**Comment by cacogen** [comment]
i experienced this last night on hippie as well

**Comment by Tofa01** [comment]
You need to eat the fruit to get the revolver the real bug is that you can click it in the first place and it disappears

**Comment by Kromgar** [comment]
@Tofa01 Uh... you could click on it to get the gatfruit immediately i did this before as a plant person. You peel the fruit and get the gat.

**Comment by Repukan** [comment]
I had this issue as well, but I was told that gatfruit was removed because it was too OP. In any case, eating the fruit didn't drop the gun either.

**Comment by ExcessiveUseOfCobblestone** [comment]
it was just a bug lol
