### ISSUE TITLE
You have to walk to pickup ores now

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#24435]
If you run you more than likely will not pickup ores now usually every one in 3 tiles

**Comment by lzimann** [comment]
Most likely caused by #24310

**Comment by DanteRU0312** [comment]
Yeah, noticed that. Also, ores now picking up really weird, sending three-four messages in the chat about picking up and emptying in the ore box.

**Comment by Kromgar** [comment]
@DanteRU0312 I can confirm its really annoying

**Comment by Kromgar** [comment]
When the fuck did i close this
