### ISSUE TITLE
Changelings can use the pockets of flesh jumpsuits

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24448]
1) Be a changeling.
2) Have no jumpsuit equipped, transform into an identity that has a jumpsuit.
3) Use pockets.

**Comment by ShadowDeath6** [comment]
Well, how would it make the holes for pockets in the jumpsuit be fake? It seems easy enough to emulate as flesh considering how well they can imitate any other items or clothes as flesh.

**Comment by PKPenguin321** [comment]
I think this is a dupe, and also I don't consider this an issue

**Comment by lzimann** [comment]
The flesh disguises shouldn't be interactable IMO.

**Comment by XDTM** [comment]
It would make life as ling infinitely worse if they didn't. What they need instead is to be able to take off the clothes separately so a fake id doesn't clog my id slot.

**Comment by DanteRU0312** [comment]
Don't see a bug, golems have pockets too.

**Comment by XDTM** [comment]
In any case they're necessary for fake belts/ids. Plus we shouldn't discourage actually disguising as a ling.

**Comment by coiax** [comment]
Okay, but if a ling grows a clothing item with pockets (certain jackets, detective's hat), it should also have access to pockets.

Hypothetically. But that would be difficult to code, I think?

**Comment by bgobandit** [comment]
why wouldn't the ling be able to grow flesh with pockets

**Comment by coiax** [comment]
Good points.
