### ISSUE TITLE
The Chemical Tirizene is broken

### ISSUE THREAD

**Issue by TimeIsEndless** [tgstation/tgstation#24444]
[Note]: # (Please enter the commit hash and active testmerge numbers from the "Show Server Revision" verb if you can. If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

Server revision compiled on: 2017-02-25
32954538d4be3d23730c217d9767f246ff0b274b 

 (#24410)

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

The chemical Tirizene found in Poison-Berrys and Sleepy Pens does currently not induce Stamina Damage.

I have no Screenshot of it but i tested it ingame as a botanist and had over 300 units of tirizene in me.

**Comment by XDTM** [comment]
Maybe it regenerates faster than it is dealt?

**Comment by TimeIsEndless** [comment]
Could be maybe change it so that it stops stamina regen?

**Comment by XDTM** [comment]
it's probably easier to just make it deal more damage than the regen

**Comment by XDTM** [comment]
Found the issue: tirizene gets less effective as time goes on, until it's removed. It ends up dealing 3 stamina every two seconds, so below the regen level, but initially it's 13 per second. I'm not sure who implemented the falloff or why, though.

**Comment by TimeIsEndless** [comment]
right especially since it is supposed to knockout in large doses

**Comment by Repukan** [comment]
Stealth nerf to peacekeepers
