### ISSUE TITLE
Syndicate Base characters have incorrect names

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#24440]
Whenever a ghost joins as a Syndicate Agent, male characters are assigned female name and female characters are assigned male name.

**Comment by jughu** [comment]
Did you just assume my gender?

**Comment by kriskog** [comment]
Still a thing

`This is Ezekiel Aultman ! 
She is wearing  a tactical turtleneck. 
She is wearing  a labcoat. 
She has  a backpack on her back. `
