### ISSUE TITLE
Engraved messages aren't loading/saving on server

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24446]
1) Make note in relatively obscure location.
2) Come back next round, message has disappeared.

This continues, I'm pretty sure it's not just someone wiping all my messages clean.

**Comment by YakumoChen** [comment]
I haven't even seen any of the messages recently.

**Comment by kriskog** [comment]
Haven't enountered this and messages seem to apply/remove as they should, assume its fixed.
