### ISSUE TITLE
Progress Bars stay above a container after transferring items to it.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#24445]
If you transfer items to a box from another box, done by dragging the sprite of box one to box two, the progress bar will stay above box one.

EDIT: Pics: https://gyazo.com/614d1f6b3f118302d2bbba547d4d278b

**Comment by lzimann** [comment]
@cyberboss or @Iamgoofball

**Comment by lzimann** [comment]
Fixed by #24413.
