### ISSUE TITLE
Traitors and Syndicate Base operatives can't communicate

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#24441]
While traitors should be able to purchase a syndicate radio key and talk over syndicate channel, the comms agent at the syndicate base can not hear traitors speaking on the radio.

**Comment by coiax** [comment]
I've seen lavaland base syndies and traitors talk over the radio before...

**Comment by Sligneris** [comment]
Well, it's based on a salty miner traitor claiming in deadchat that he told us he's coming in despite us never getting a word.

Needs testing to confirm whether it's really broken now, or whether the miner was just talking out of his ass.

**Comment by YakumoChen** [comment]
This shouldn't be the case, I talk with Mining Base Ops all the time as malf AI.

**Comment by optimumtact** [comment]
please don't report a bug unless you actually verified it yourself
