### ISSUE TITLE
borgs have access to centcomm ferry

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#24454]
1. Use ferry to deliver something to crew
2. Borg swoops in with a human and they take off to centcomm
3. Crew gets phat loot/mad when I kick them out

**Comment by Tofa01** [comment]
I forgot aiControlDiabled on the doors, fixing now should have a PR up soon.

**Comment by GunHog** [comment]
You need to have it return nothing on attack_ai() or attack_robot(). That is, unless you add a Centcomm/Deathsquad borg.

**Comment by Tofa01** [comment]
Indeed i am doing that now i will do the map edit later. If someone adds a centcomm borg then they can add the simple if istype to bypass this later.
