### ISSUE TITLE
explosive tesla bolts are too deadly

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#24453]
max range form a low level Tesla: instant death. This can happen outside of hearing range

**Comment by PKPenguin321** [comment]
Feedback forum

**Comment by Supermichael777** [comment]
Do you read the feedback fourm?

**Comment by PKPenguin321** [comment]
Yes

**Comment by PKPenguin321** [comment]
>it's a "salty i ded issue that uses 'nobody looks at feedback forum xd' as its reasoning to not be instaclosed" episode

**Comment by lzimann** [comment]
Not a bug/issue(althought I agree that explosive tesla, even if it's funny, is kinda too much).
