### ISSUE TITLE
Shuttles don't properly make hyperspace parallax occur

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#24457]
emergency shuttle, space looks as if it is still instead of properly going into hyperspace parallax.

**Comment by lzimann** [comment]
Image from the other issue:
![img](https://cloud.githubusercontent.com/assets/12747768/23340019/e4b7c576-fc2e-11e6-84e9-16153fe8a3bf.png)

**Comment by Shadowlight213** [comment]
@MrStonedOne

**Comment by Cyberboss** [comment]
@MrStonedOne please review https://github.com/tgstation/tgstation/pull/24694/files#diff-d5d51208409832527dd15451f013e148 This may be my fault

**Comment by Shadowlight213** [comment]
When is it not your fault tbh? :^)

**Comment by MrStonedOne** [comment]
Can somebody confirms this happens on humans, because in my testing it only happened to ghosts and it resets if they leave the shuttle area and come back

**Comment by MrStonedOne** [comment]
Actually, after updating the linux test server, I was unable to reproduce the issue there.

**Comment by Bawhoppen** [comment]
Still a problem for me virtually every single round
If you need me to test something MSO, I'll be happy to

**Comment by WJohn** [comment]
This is still broken. Seems to occur if you start moving around before the actual hyperspace parallax happens. If you sit still until then, THEN you move, it works fine.

**Comment by MrStonedOne** [comment]
@ninjanomnom i'm blaming you for no reason

**Comment by ninjanomnom** [comment]
odd, it was working when it was closed but I expect the recent change broke it again
