### ISSUE TITLE
Missing a leg slows you down in space

### ISSUE THREAD

**Issue by CPTANT** [tgstation/tgstation#24459]
Most notable when you move around using the new internal jetpack in space. You move as slow as you would while walking in a station with gravity.

I think this is also going to be the case when moving around the station in zero g?

**Comment by XDTM** [comment]
Probably jetpack movement overrides no-grav fixed speed.

**Comment by lzimann** [comment]
If it's WALK speed then it's a bug, otherwise built-in jetpacks no longer offer movement speed bonus anymore.

**Comment by CPTANT** [comment]
You move slower without a leg using an internal jetpack than you do using the same jetpack with both legs.

**Comment by CPTANT** [comment]
How is this a consistency issue, being slowed down in space using a jetpack makes no sense in ANY consistency.

**Comment by lzimann** [comment]
Because space shouldn't be applying any slowdown, that's not consistant.

**Comment by BeeSting12** [comment]
Being an imp also slows you down in space, not sure if it's a bug or not.

**Comment by coiax** [comment]
Also, if you are affected by no-leg slowdowns in space, but not stamina damage, then it's all kinds of confusing.

**Comment by optimumtact** [comment]
a lot of the slowdowns simply don't take the lack of gravity into account
