### ISSUE TITLE
Bedsheet problems

### ISSUE THREAD

**Issue by KingPhilipIII** [tgstation/tgstation#24468]
Right. So. Apparently the Nanotrasen bedsheet, one of which can be found in Pubby's dorms, lacks a sprite when worn as a cape.

**Comment by jughu** [comment]
@lzimann i think this is auctally map related considering pubby nanotrasen bedsheets are auctally custom ones then the one used in meta caps office its snowflak

**Comment by lzimann** [comment]
It is still a sprite issue, since there is an object([here](https://github.com/tgstation/tgstation/blob/9feab253b8c4c47283fe16bbd1df11b9d8c0ddb5/code/game/objects/structures/bedsheet_bin.dm#L177)) that has no worn sprite.

**Comment by jughu** [comment]
Im pretty sure centom/nt are the same bedsheets doesnt meta captain gets a centcom one?
