### ISSUE TITLE
Shuttle walls smooths with engine

### ISSUE THREAD

**Issue by TrustyGun** [tgstation/tgstation#24471]
It looks gross

![scrnshot1](https://cloud.githubusercontent.com/assets/7079721/23343764/94b0892c-fc3e-11e6-99ea-15786089c17b.png)

**Comment by WJohn** [comment]
Should smooth with heaters only, not engines.

**Comment by Sligneris** [comment]
Shuttle walls look somewhat gross in general to be honest
