### ISSUE TITLE
Immortal changeling tentacles

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24475]
![image](https://cloud.githubusercontent.com/assets/609465/23344052/697d2592-fc6d-11e6-82e9-aa200db25f87.png)

Just like changelings, they DO NOT die. More specifically, the "beam" never disappears.

@XDTM 

Seen this a couple of times.

**Comment by XDTM** [comment]
If nobody's seen these anymore this might've been fixed by #24705

**Comment by DoctoreMad** [comment]
>Just like changelings, they DO NOT die.

![1439257804994](https://user-images.githubusercontent.com/29125781/28252588-30a1003c-6a6c-11e7-9a25-fe6d302187dc.jpg)

**Comment by XDTM** [comment]
Has this ever happened again?
