### ISSUE TITLE
You are immune to stamina damage slowdown in space

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24484]
1) Stamina damage someone.
2) They are in space lol, they run at full speed

**Comment by dannno** [comment]
I mean
makes sense?

**Comment by coiax** [comment]
How? Are you saying really tired people move at the same rate in space?

**Comment by dannno** [comment]
conserved momentum

**Comment by PKPenguin321** [comment]
space is supposed to remove all slowdowns, any slowdown that still applies in nograv (save maybe magboots) is a bug

**Comment by lzimann** [comment]
No slowdown should be applying in space. A maintainer can re-open if I'm wrong about this.

**Comment by coiax** [comment]
Why is an injured person able to move as fast as a non-injured person in space? Gravity may not be present, but your muscles still are...
