### ISSUE TITLE
Numerous glitches during long rounds

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#24488]
Should a round be abnormally long, such as 5+ hours, the game doesn't seem to handle it well. What I've noticed so far is that at some point:

- Some sounds do not play (airlock opening or closing, console sounds)
- Projectile effects do not vanish (kinetic force from KA, disablers, etc)

It's not a problem during regular gameplay, but it does make working with test servers somewhat annoying.

**Comment by Kromgar** [comment]
Projectile effects do not vanish can happen in only hour and a half long rounds

**Comment by bgobandit** [comment]
the first one sounds disturbingly close to cleanbot bug

**Comment by optimumtact** [comment]
I've never encountered any of these issues

**Comment by kriskog** [comment]
Never seen this either, and I frequently run long local rounds. Open a new issue if its still a thing.
