### ISSUE TITLE
Changelings can absorb 5+ DNA without having to transform

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24485]
Originally, I thought there was some sort of limit on the DNA buffer a changeling had, and they couldn't absorb more than 5 without being forced to transform.

Without this limit, the changeling no longer has to transform at all to get it's DNA objective, losing half the point of the WHO IS THE CHANGELING fun

**Comment by lzimann** [comment]
Can't find any pr changing this behavior so I'll assume it's a bug.

**Comment by DanteRU0312** [comment]
I thought it was random? I'm pretty sure as a changeling i was able to absorb around 4-6 DNA points randomly. Maybe i'm wrong.

**Comment by BeeSting12** [comment]
Once they transform they lose their original identity

**Comment by coiax** [comment]
Except they can just DNA channel their original identity to the airwaves, and then reabsorb it back...
