### ISSUE TITLE
Radiations Shutters on Supermatter Engine are Chief Engineer only.

### ISSUE THREAD

**Issue by Brimcon** [tgstation/tgstation#24494]
As the title says, trying to close the Radiation shutters on the Supermatter Engine on box gives an Access Denied as Station Engineer. Is this intentional?

**Comment by Armhulen** [comment]
And the air alarm isn't set for engineers to tinker with it, even though it's basically required for the engine to work

**Comment by jughu** [comment]
Lets put a atmosbased engine for notmal engineers without atmos access to use 🤔

**Comment by XDTM** [comment]
it's been fixed, i think, servers just need to update

**Comment by Penguaro** [comment]
On boxstation, an Engineer can access the Air Alarms and the shutter control. On Metastation same though the shutters don't work there until the other PR about them gets merged.

**Comment by Penguaro** [comment]
My utmost apologies. I was testing this on a private copy which had Skeleton crew access enabled. On a standard pop server you would not be able to access those controls. The air alarms closest to the coolant loop scrubbers are unlocked at round start. The other air alarms in general are locked to Station Engineer in a normal pop server. I'm creating a PR for the radiation shutters access level.
