### ISSUE TITLE
Blood cult being able to greentext consistantly before 10 minutes

### ISSUE THREAD

**Issue by StuAhpla** [tgstation/tgstation#24492]
So it's like the fourth round in a row now where the blood cultists managed to complete their objectives before even the engine was finished setting up. It seems right now that cult feels way too overpowered and don't even try to stealth anymore, instead spamming stunprods and converting in the hallway and rushing the summon.

With clock cult getting its doors nerfed this should be addressed at least

**Comment by juanototo2** [comment]
ah, yes. Prod + quikpaper + rushed offer rune + SUMMON GHOSTNARNAR =

15 minute instawin.

**Comment by Kromgar** [comment]
I'd like to state in the last round this happened the cult was actively doing their shit IN THE BAR ON BOX STATION.

Also they did not use the manifest rune. They actually converted people while they were summoning nar nar IN THE BAR

**Comment by Kromgar** [comment]
Also this could easily be corrected by convert being a channel once they are on rune similar to geis.


So they get put on rune and blood bindings surround them.
