### ISSUE TITLE
Deleting a mob leaves tablet batteries behind if there is a tablet in their bag

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24522]
![image](https://cloud.githubusercontent.com/assets/609465/23373162/9d8f19ea-fd16-11e6-9a3a-3ef4888f384f.png)

Seen this when people being incinerated in cremator, or being killed via SM

**Comment by bgobandit** [comment]
nanotrasen uses heavy duty batteries

**Comment by Kromgar** [comment]
Ultra batteries

**Comment by Armhulen** [comment]
supermatter batteries? lore?

**Comment by MimicFaux** [comment]
This kinda shit is hilarious to me because of the circumstances that had to happen for it to be discovered.

**Comment by Cyberboss** [comment]
Is this still happening?

**Comment by coiax** [comment]
Pretty easy to test.

**Comment by 81Denton** [comment]
@Cyberboss This is still happening if someone has a tablet computer in their pocket. It drops `/obj/item/stock_parts/cell/computer`.

**Comment by kriskog** [comment]
Yeah, still a thing
