### ISSUE TITLE
Monkey cube boxes have overlays for normal boxes on top of their sprites

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#24526]
Everyone forgot monkey cube boxes existed didnt they

![image](https://cloud.githubusercontent.com/assets/6778786/23375302/d5a83562-fcf5-11e6-9d7d-39e3d195fd36.png)

**Comment by Militaires** [comment]
i actually commited code fixing this seconds after the shit was merged

will fix rn
