### ISSUE TITLE
Reflector frames cannot be constructed

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#24545]
I know we removed them because pixel projectiles but if some asshole just wrenches or a engineer wrenches it by accident it gets deconstructed and you cant repair it greatly decreasing emitter beams

**Comment by Tokiko1** [comment]
Just readd their construction and make them only work with the emitter beams, those only fire in 4 directions anyway.

**Comment by octareenroon91** [comment]
Ready to close because #25084
