### ISSUE TITLE
shuttle manipulator template load does not play well with asteroid shuttle

### ISSUE THREAD

**Issue by bobdobbington** [tgstation/tgstation#24542]
[Note]:
Server revision compiled on: 2017-02-27
4a0b7cdd754aeb1950851eccb7ff85362f2af6d3 

>be admin
>honk mech dies a noble death against an enraged mob of crew
>clown is beheaded
>honk mech turned out to still be in warranty
>shuttle manipulator load snappop
>honkco customer service upgraded the shuttle to the snappop from asteroid
>and put the replacement honk on top of the greentext
>shuttle docks
>wipes out almost all of chapel
>chasm with honk right where chapel office used to be
>no refunds

This should probably update where the shuttle is supposed to dock after using shuttle manipulator to load another template

[Admins]:
After a player bought asteroid shuttle, loaded snappop with the shuttle manipulator.

Expected behavior: The shuttle docks normally at the escape airlocks.
Observed behavior: The shuttle destroys the shit out of the chapel as if it were the northwest corner of the asteroid.

**Comment by KorPhaeron** [comment]
dupe
