### ISSUE TITLE
Pubby station still has a singularity engine setup, rather than new and improved SM

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24551]
@KorPhaeron

**Comment by Cyberboss** [comment]
>MFW yall did this before I did template engines and it's gonna make the job harder

**Comment by KorPhaeron** [comment]
We no longer desire template engines

**Comment by Cyberboss** [comment]
IM BRINGING THE TEG BACK KICKIN AND SCREAMING!

**Comment by optimumtact** [comment]
We no longer desire template engines

**Comment by optimumtact** [comment]
Also this isn't a bug.
