### ISSUE TITLE
Freon freeze interacts visually strangely with lockers, computers, and things with overlays, I guess

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24561]
![image](https://cloud.githubusercontent.com/assets/609465/23438811/7e31fd7e-fe0b-11e6-8d82-54273d2449e6.png)
![image](https://cloud.githubusercontent.com/assets/609465/23438819/8d11691a-fe0b-11e6-8a0c-2dddcbc27e41.png)

**Comment by Cyberboss** [comment]
SS13 could be the most advanced, well written game in the world. And freon would still be broken af

**Comment by XDTM** [comment]
Basically it's ignoring overlays

**Comment by coiax** [comment]
That's what I figured
