### ISSUE TITLE
Mimery Fingerguns can be fired while handcuffed

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#24567]
Tiny fingercuffs required.

**Comment by coiax** [comment]
feature.

**Comment by Cyberboss** [comment]
>HELP: Ninja137/(********) (?) (PP) (VV) (SM) (FLW) (TP) (REJT) (IC): Uh, so, as it turns out, you can fire the mimegun while straightjacketed, cuffed, and buckled to a table.

**Comment by PKPenguin321** [comment]
Will fix

**Comment by coiax** [comment]
Okay, being able to fire mime guns while straightjacketed and/or buckled is less cool. But regular handcuffed should still be permitted. Aren't there restrictions when people can emote?
