### ISSUE TITLE
Bolts of healing do not bring back beheaded people

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24568]
You can literally bring back suicides, but not beheaded people? Botany can do it, so why not wiznerds

**Comment by ShadowDeath6** [comment]
doesn't their brain hold the ckey info

**Comment by coiax** [comment]
you can podclone from a blood sample, which I think also has the ckey info

**Comment by XDTM** [comment]
I put a workaround to make that possible.

**Comment by coiax** [comment]
@XDTM chop chop then, fix it

**Comment by XDTM** [comment]
for podpeople, i mean; bolts of healing are a bit more complicated, but i'll see what i can do

**Comment by Qustinnus** [comment]
@XDTM do it nerd


also this should result in them turning into dullahans kek
