### ISSUE TITLE
Something is wrong with Mech Tesla shit

### ISSUE THREAD

**Issue by dannno** [tgstation/tgstation#24560]
![](https://vgy.me/fP8bQB.png)
left these bolts going from maint bar all the way to space above brig on metastation.

**Comment by kevinz000** [comment]
@vcordie you fuck

**Comment by vcordie** [comment]
Probably not my fault, shits been sucked with beams for a while (ie: Infinitentacle). Either way I'm not in a position to fix, I'm on hiatus
