### ISSUE TITLE
Z-Level transition by colliding with level edges is broken

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#24585]
![jj8xui 1](https://cloud.githubusercontent.com/assets/17237624/23471308/2c8dc496-fea9-11e6-898f-0da63fbe062a.png)
Server revision compiled on: 2017-03-01
The following pull requests are currently test merged:
#24171: 'Runtime Dynamic Station Loading' by Cyberboss 

Based off master commit:
ceb04ebbf5131690e28e8373d6e4d6d6c2e9fb7d 

I launched myself out of the mass driver but I got stuck on the edge of a level instead of ending up on the derelict Z-level.

**Comment by Cyberboss** [comment]
Was this within 8 hours ago? Also what server?

**Comment by Cyberboss** [comment]
Fixed in d4de751 @lzimann

**Comment by DaxDupont** [comment]
Sybil, an hour ago

**Comment by Cyberboss** [comment]
Yeah, it's fixed, sybil isn't updated yet
