### ISSUE TITLE
Being frozen in an ice cube by freon exposure causes runtimes

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24596]
[01:00:25] Runtime in overlays.dm,103: undefined variable /icon/var/dir
  proc name: cut overlay (/atom/proc/cut_overlay)
  src: Houdini Weatherwax (/mob/living/carbon/human)
  src.loc: the snow (142,153,1) (/turf/open/floor/holofloor/snow/cold)
  call stack:
  Houdini Weatherwax (/mob/living/carbon/human): cut overlay(/list (/list), null)
  /datum/status_effect/freon (/datum/status_effect/freon): on remove()
  /datum/status_effect/freon (/datum/status_effect/freon): Destroy(0)
  qdel(/datum/status_effect/freon (/datum/status_effect/freon), 0)
  /datum/status_effect/freon (/datum/status_effect/freon): process(2)
  Fast Processing (/datum/subsystem/processing/fastprocess): fire(0)
  Fast Processing (/datum/subsystem/processing/fastprocess): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)

You still get frozen and can't move, but there is no visual for the ice cube

**Comment by Kromgar** [comment]
Freon will never be bug free will it?

**Comment by Cyberboss** [comment]
Freon literally never gave a shit about overlays

**Comment by optimumtact** [comment]
#24561 is likely the same root issue, closing that in favour of this

**Comment by coiax** [comment]
@optimumtact I'm not sure if it is.

**Comment by Cyberboss** [comment]
No, this was fixed by #24530
