### ISSUE TITLE
My clothing slot keeps transforming

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#24606]
Testmerged:

#24171: 'Runtime Dynamic Station Loading' by Cyberboss
#24504: 'Smoother roundstart take II' by Cyberboss

![image](https://cloud.githubusercontent.com/assets/6778786/23491192/b4cdb886-feca-11e6-9cbe-4ea6d6008658.png)

Turned into a basilisk the fist time i saw one then a goliat then it turned into a radiation collector

**Comment by Kromgar** [comment]
![image](https://cloud.githubusercontent.com/assets/6778786/23491229/f03d274e-feca-11e6-80ae-094edf135e32.png)
![image](https://cloud.githubusercontent.com/assets/6778786/23491234/f7c60198-feca-11e6-9fb9-2d8e7bfbe1c7.png)


Running windows 10 511.375

**Comment by Kromgar** [comment]
![image](https://cloud.githubusercontent.com/assets/6778786/23491281/3ef064be-fecb-11e6-8cfe-158251753b8c.png)


I dont even know

**Comment by PKPenguin321** [comment]
Clear byond cache and reconnect

**Comment by Kromgar** [comment]
@PKPenguin321 how do i do that?

**Comment by PKPenguin321** [comment]
Google it I don't have the link on me atm
