### ISSUE TITLE
Stripping a person of (advanced?) magboots (on) does not make them immediately able to be dragged/pulled

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#24616]
Encountered on a guy with advanced magboots on moving shuttle.

Stripped him of his advanced magboots, couldn't drag him. He was laying on an open locker, and after a quick close/open he was draggable again.

**Comment by Davidj361** [comment]
Possibly due to lag/delay in the code.

**Comment by kriskog** [comment]
Magboots don't prevent pulling (anymore?)
