### ISSUE TITLE
Shuttle launching causes people to fall out of disposal pipes

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#24620]
How to recreate bug.
Make infinite disposals loop on shuttle. 
Jump in loop
Launch shuttle
fall out of loop

**Comment by GunHog** [comment]
Shuttles break pipes and wires, especially if they change direction.

**Comment by coiax** [comment]
Oh no, what a horrible bug, people are being freed from infinite disposal loops :( :( :( :(

**Comment by duncathan** [comment]
The real issue here is breaking pipes and wires, which I need to fix
