### ISSUE TITLE
Monkeys attempt to strip and disarm even when devoured

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24629]
1) Become fat, somehow.
2) Devour a monkey.
3) Laugh as the monkey attempts to do shit while inside your stomach.

**Comment by RemieRichards** [comment]
somehow? just eat...

**Comment by coiax** [comment]
I thought it required like the fat statusflag, but maybe not anymore

**Comment by Iatots** [comment]
They are not held back by cuffs either but I guess that's opposable toes for you.

**Comment by Kromgar** [comment]
Eating monkey should be easier!
