### ISSUE TITLE
there is no way to filter gas by temperature

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/tgstation#24639]
ey, feature request i guess. can we get a gas mixer/filter that filters by temperature of gas? as it is it'd be nice for the supermatter engine, which uses atmos as coolant; as it is you can have all the space/cooling loops attached to it you want but you either have to choose between superhot gases circulating or no gas at all circulating because there is no way to let things through that are sorted by temperature.

anyway yeah it'd be neat if possible thx

**Comment by Iamgoofball** [comment]
I can look into it

**Comment by Cebasiz** [comment]
thanks babe

**Comment by Cebasiz** [comment]
it'd be nice i think because then you could have filter --> cooling loop setups that only allow very hot gas out, and only allow fairly cool gas in, making "brake loops" that isolate gas inside heat exchangers until it cools down.

**Comment by Cebasiz** [comment]
also when are we going to get machines that run on freon that supercool things faster than space thanks

**Comment by Iamgoofball** [comment]
You should try running Freon through the Supermatter

**Comment by Cebasiz** [comment]
unfortunately there is little enough of it that it may not even work. there isn't a tank in atmos and you can't produce it

anyway when are we getting machines that can produce gases of various types incl. freon and reagent gases thanks goof

**Comment by Cebasiz** [comment]
also i'd like a pony

thanks

**Comment by XDTM** [comment]
You can get gas from cargo

**Comment by xxalpha** [comment]
This makes no sense, just learn to atmos better.

**Comment by jughu** [comment]
Theres a whole canister in secure storage

**Comment by lzimann** [comment]
Not a bug/issue.

**Comment by Iamgoofball** [comment]
>This makes no sense, just learn to atmos better.

this guy obviously knows how to atmos you fuck

**Comment by Cebasiz** [comment]
lzimann you jerk

there is a feature request for a reason you doofus

also goof fix game thanks my man i trust in you

**Comment by lzimann** [comment]
We don't use the issue tracker to request features.
