### ISSUE TITLE
aux mining console starts the camera at centcom

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#24637]
makes using the mining console impossible, so
#24171 testmerged

**Comment by AnturK** [comment]
@GunHog Probably needs moving the eye creation to Initialize

**Comment by GunHog** [comment]
It is because some jerkface put an aux base console in Centcom. It would be easier to remove it, or have a z-check when looking for a console.

**Comment by Cyberboss** [comment]
Sorry, where is this camera?

**Comment by GunHog** [comment]
I will take care of it. I will have the camera console check that the Aux Base's launch computer is actually inside the base.
