### ISSUE TITLE
Meta & Box CE singulo camera monitor not connected

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#24635]
[Note]: 41bb3a6d32cf2a05ed60c2c1f9a2423bbdcef12d 

New engine cameras aren't set on the CE's camera monitor.

**Comment by Penguaro** [comment]
Which Camera Monitor are you referring to? As far as I can tell, the Cameras that used to exist around the singulo/tesla _and_ the monitor for them that was outside the chamber with the particle emitter have been removed.
