### ISSUE TITLE
Atmos to engine piping.

### ISSUE THREAD

**Issue by DanteRU0312** [tgstation/tgstation#24642]
No idea if this is intended, but probably belongs to map tweaks. On Metastation, pipes from Atmos to Engine lead to Heat Exchange piping, and only then cooled mix comes into Engine Chamber. On Box, pipes from Atmos to Engine lead first to Engine Chamber, and only then mix will be syphoned and cooled.
Also, don't want to create a separate report for it, just noticed, that on Metastation radiation shutters are called Chapel privacy Shutters and the shutter button isn't working on them.

**Comment by Penguaro** [comment]
Arguably, the metastation setup is more efficient as you'd want to cool the air going into the supermatter chamber as much as possible whereas on box station it goes in essentially at room temperature and then is cooled.

I'm creating a PR for the "chapel" shutters. Please either open a different issue for the PR to reference or just remove your comment about them from here.

**Comment by Penguaro** [comment]
@DanteRU0312  Arguably, the Meta Station setup is more efficient as you'd want to cool the air going into the supermatter chamber as much as possible whereas on Box Station it goes in essentially at room temperature and then is cooled.

The issue with the shutters has been resolved. Consider removing your comment about them here to keep the Issue specific.

**Comment by Penguaro** [comment]
@DanteRU0312 - I get that the two stations have a different approach. What are you saying they should be or what do you believe is broken about either setup? What is the ideal outcome you would expect to see?

Also the issue with the shutters has been resolved. Consider removing your comment about them here to keep the issue specific.

**Comment by ShizCalev** [comment]
This doesn't seem like an issue really.

**Comment by PraiseRatvar** [comment]
@Dorsisdwarf i refer to what shizcalev said, close thy issue
