### ISSUE TITLE
Portable Air Pumps cause plasma floods.

### ISSUE THREAD

**Issue by Shuffl3** [tgstation/tgstation#24643]
Every so often when overfilling plasma tanks with cold plasma using a portable air pump attacked to a connector port, the portable air pump will overshoot the target pressure causing the plasma tank to rupture and flood the compartment.

Steps to reproduce:
1. Attach a portable air pump to the connector port of an active cooling loop.
2. Set to max, and "Out" to empty the tank.
3. Flip to "In" to fill the tank.

Overshoot seems more dramatic if there are active fridges on the same pipenet.

Seems related to lag.

I ahelped this first few times this happened. Admins seem to understand that this happens regularly

**Comment by lzimann** [comment]
Are you sure the gas inside the tank is not reacting when you fill it, causing it to rupture?

**Comment by Shuffl3** [comment]
@lzimann Yup. Pure plasma, empty tanks. There might be some thermal expansion if the next tick of air getting pumped in is a different temperature from the gas already inside. This would explain why active freezers exacerbate the issue. 

To compensate Ive either set it to just under max, or creep up to max incrementally. And normally the tank wont rupture immediately, so if you pay attention you can quickly flip it back to "Out" before anything happens.

**Comment by lzimann** [comment]
I'll see if I can reproduce this later then.

**Comment by duncathan** [comment]
this is weird. @lzimann have you been able to reproduce?

**Comment by lzimann** [comment]
No, because I forgot and never came back to this

**Comment by PKPenguin321** [comment]
?

**Comment by duncathan** [comment]
@as334 thoughts

**Comment by as334** [comment]
Without investigating, it's probably because portable pumps fill literally to the burst threshold, and then some very small fluctuation(probably from a temperature gradient or rounding error) puts it over, and it bursts. Would require some more careful debugging though.

**Comment by RandomMarine** [comment]
Every day I fuck around with atmos on a test server and this has never occurred for me.

But once this happened while playing on one of the /tg/ servers a while back.

Possibly a lag/CHECK_TICK related issue?
