### ISSUE TITLE
Base construction console shows centcomm ferry area instead of base construction area

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#24659]
![gentleman spess junk six 2017-03-03 180149](https://cloud.githubusercontent.com/assets/8237862/23573183/2d3b08be-0042-11e7-8640-f2f7680c9378.png)
Testmerged PRs: #24171, #24504 
Has been reproduced across multiple rounds, surprised that nobody has noticed this yet.

**Comment by GunHog** [comment]
Duplicate of https://github.com/tgstation/tgstation/issues/24637.
Addressed in: https://github.com/tgstation/tgstation/pull/24652.

**Comment by Hatfish** [comment]
Whoops.
