### ISSUE TITLE
O2 Gas Filter Orientation in Atmo

### ISSUE THREAD

**Issue by Penguaro** [tgstation/tgstation#24656]
Recent changes to the basic TG station map have changed the starting orientation of the O2 gas filter in the waste loop. It is switched off and installed misaligned. This doesn't seem like it would be canon.

![atmo](https://cloud.githubusercontent.com/assets/9791590/23569623/c40b278c-0025-11e7-9b92-e7b27e9cfd50.jpg)

**Comment by Penguaro** [comment]
Creating a pull request instead.

**Comment by Cyberboss** [comment]
You don't close the issue until it's fixed. You can close it with the PR
