### ISSUE TITLE
You can turn the party alarm on, but not off

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#24661]
Details: This was in the bar and theater. I tried using Admin AI interact, it only showed "Activate." Tried doing in person, it says "No party :(." My client crashed once for other reasons, maybe that's why?

**Comment by Anonmare** [comment]
Feature.

**Comment by ShadowDeath6** [comment]
the PARTY never ends

**Comment by Iamgoofball** [comment]
feature

**Comment by ShizCalev** [comment]
This was fixed.
