### ISSUE TITLE
Maint exposed to space on pubbystation

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#24679]
![](https://cloud.githubusercontent.com/assets/24999255/23487448/51ea8c56-ff3a-11e6-826c-2b0d4c51fecd.PNG)
@Tofa01 
there's the visible bottom part and there's also another part open to space above

**Comment by jughu** [comment]
Wait wait this is pubby? When they get a new escape wing

**Comment by Tofa01** [comment]
This is Omegastation. I am also releasing a quickfix now, sorry guys i must have missed that.
