### ISSUE TITLE
Bubblegum uses his claw attack trough non blood floor

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#24695]
Im not sure if this is a bug or not but considering bubblegum is the king of slaughterdemons and slaughterdemons are known from going trough blood yet bubblegums claws can go to floors wheres no blood not even drips

**Comment by Sligneris** [comment]
Was there any blood on your person? Bloodstained shoes perhaps?

**Comment by jughu** [comment]
nope i was 100% clean

**Comment by jughu** [comment]
I need to git gud i guess...
