### ISSUE TITLE
freon doesn't show up on analysers?

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#24697]
You use the analyzer on   the pipe.
Results of analysis of   the pipe.
Pressure: 240.8 kPa
Nitrogen: 49.5 %
Temperature: -232 °C

**Comment by Tacolizard** [comment]
this is really irritating pls fix

**Comment by duncathan** [comment]
will investigate

**Comment by Robustin** [comment]
I fixed this in #25369, its such an innocuous PR too

**Comment by duncathan** [comment]
resolved on live
