### ISSUE TITLE
deoxyribonucleic saboteur virus effect "cures" being a human when cured

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#24691]
As stated in the title, The deoxyribonucleic saboteur virus effect for virologists somehow assumes being a human is a "disability" that was caused by the virus, and when cured, will "cure" you by turning you into a monkey.  The virus that it was used on was cured as early as stage 1 and still turned you into a monkey when it was cured, so it's possible this happened because the virus was fast-acting, This happened during a clock cult round, and the virus initially started in a monkey, before spreading to the crew.

**Comment by feemjmeem** [comment]
1) Create virus with dna sabo
2) Inject monkey with virus
3) Monkey -> Stage 5
4) Catch virus from monkey as human
5) Human -> Stage 5
6) Cure (NaCl)
7) Human is now Monkey

**Comment by XDTM** [comment]
That's pretty odd, all it does is save your SE and restore it when cured

**Comment by feemjmeem** [comment]
I was only able to replicate this by including the monkey, so I'm pretty sure the monkey SE is carried from virus carrier to virus carrier.

**Comment by XDTM** [comment]
oh i see now
Symptom datums are actually global and disease just reference them, so it saves the dna of the first infected, aka a monkey, and uses that as a restoration point.
A proper fix would require a refactor of symptom code to make them use instances instead of a library, currently a quick fix would be to make it clear dna when cured instead of saving dna states.

**Comment by bgobandit** [comment]
FEATURE

**Comment by Repukan** [comment]
Awesome feature

**Comment by Anonmare** [comment]
I'm reminded of a Doctor Who episode where a piece of medical equipment didn't recognise what a Human was

**Comment by XDTM** [comment]
While the FEATURE is fun, remember this affects completely independent viruses with the same symptom. The first one picks the dna, and any other instance remembers it.

**Comment by kriskog** [comment]
Not an issue anymore.
