### ISSUE TITLE
FLASH CRASH

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#24698]
>BE OLDMAN
>SOMEONE FLASHES ME
>SUDDENLY HAVE MESON VISION
>DREAMSEEKER CRASHES

AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by Repukan** [comment]
Remove oldman

**Comment by Robustin** [comment]
This was during the "reverts /vg/ rebase" was in effect BTW

**Comment by Robustin** [comment]
IT HAPPENED AGAIN THIS TIME NO FLASH JUST MESON VISION + CRASH AHHHH

**Comment by Robustin** [comment]
Because I'm trying to reduce the number of issues and I'm confident that this was only due to the chaos surrounding the initial /vg/lighting runs/reverts, I'm closing this.
