### ISSUE TITLE
The explosion implant action button is disabled in crit

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24717]
It should always be an option.

**Comment by Mindustry** [comment]
whisper *deathgasp or something like that

**Comment by PKPenguin321** [comment]
yeah just going 'say "*deathgasp"' still works

**Comment by XDTM** [comment]
or whisper anything at all while in crit

**Comment by jughu** [comment]
Or just succumb

**Comment by coiax** [comment]
Yes, I am aware that you can trigger it via whispering, but not everyone is. Having the button disabled is still silly.

**Comment by coiax** [comment]
I fixed this.
