### ISSUE TITLE
Nuclear operative Syndicate cyborgs can be module reset

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24716]
1) Be a syndicate assault borg.
2) Get ioned a bajillion times, module resets.
3) Pick a new module, the old assault module is not an option.
4) The new module doesn't even have emag gear.
5) am cry

**Comment by ChangelingRain** [comment]
The reset wire was a mistake tbh
Also seriously EMPs hit borg wires? That's terrible and also your fault.

**Comment by Anonmare** [comment]
It resets every kind of borg, not just Syndies

**Comment by coiax** [comment]
The main issue is that you can't pick the assault module again, I'd say. Borgs being reset through EMPs is hilarious.

**Comment by ShadowDeath6** [comment]
aren't syndieborgs canonically illegally modified versions of borgs, not module types? it doesn't make sense for them to be able to be reset at all

**Comment by Shadowlight213** [comment]
Once the feature freeze is over, I'm removing the reset wire as it's been abused for free resets too much.

**Comment by coiax** [comment]
@Shadowlight213 or just change it to cutting the wire, rather than pulsing it.
