### ISSUE TITLE
Crayons cannot be juiced

### ISSUE THREAD

**Issue by feemjmeem** [tgstation/tgstation#24723]
Crayon powder is a reagent but you cannot extract it from crayons using a reagent grinder or juicer.

**Comment by bgobandit** [comment]
critical priority

**Comment by GunHog** [comment]
I read the title of this and thought "What? Why would you need to juice a crayon?".

**Comment by feemjmeem** [comment]
why wouldn't you

**Comment by DanteRU0312** [comment]
Can confirm, very important, needs fixing ASAP.

**Comment by Thunder12345** [comment]
Have you tried grinding it instead?

**Comment by feemjmeem** [comment]
yes, i have tried both grinding and juicing, that's why i said that you cannot extract reagents from either a grinder or a juicer

**Comment by Armhulen** [comment]
This is a bug though

**Comment by Armhulen** [comment]
@Dorsisdwarf

**Comment by bgobandit** [comment]
https://github.com/tgstation/tgstation/blob/ce23a1d059364426c301a5e683aab6dcb61e49a3/code/modules/reagents/chemistry/machinery/reagentgrinder.dm#L357

crayons aren't reagent containers, hence they are not picked up, idk when this got refactored

**Comment by feemjmeem** [comment]
BUT CRAYON POWDER IS A REAGENT REEEEEEE [AGENT]

**Comment by bgobandit** [comment]
the for loop only checks for reagent_containers, crayons are not pathed as that
