### ISSUE TITLE
Role restricted traitor items isnt really role restricted

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#24735]
>be assistent>give uplink to metabuddy chaplain>ask him to buy his grace
Multiple traitors can do the same
Meaning multiple his grace without the auctall chaplain being a traitor 😏

**Comment by coiax** [comment]
Feature.

**Comment by SgtxRootbeer** [comment]
That is by design, so is buying an agent card, or being hop and manipulating your ID

**Comment by coiax** [comment]
@SgtxRootbeer not true, the role restriction applies only to your ROUNDSTART job. ID changes or Hop memery won't change your roundstart job.

**Comment by SgtxRootbeer** [comment]
@coiax 
I was reading
#23227
When was it changed?

**Comment by coiax** [comment]
At the end of the PR's life

**Comment by SgtxRootbeer** [comment]
I'm a fucking turbo-autistic moron.
