### ISSUE TITLE
Head removal destroys flashlight eyes

### ISSUE THREAD

**Issue by octareenroon91** [tgstation/tgstation#24739]
(Revision 59ed05ed5101a49553fef7be10fb0ab221e91085 )

Exactly what it says:
Implanting flashlight eyes, then removing head, then reattaching head, leaves no flashlight eyes, neither in the head nor on the ground. The head and body do not even shed light. Thus:

1. Head amputation loses prosthetic eyes, seemingly irreversibly. (bug)
2. Amputating a head with flashlight eyes COULD give you a luminous head, but it does not. (feature/consistency)

Possibly also of interest #23783

**Comment by XDTM** [comment]
Probably readding the head does not trigger the eyes' Insert, so the luminosity isn't added.

**Comment by KorPhaeron** [comment]
1) The eyes do transfer to the head. If you were to dismember the head, they'd come out.

2) XDTM is probably right about reattaching

3) We can't have the head glow because objects giving off light and not breaking when picked up is terrible snowflake that applies to flashlights only

**Comment by octareenroon91** [comment]
Yeah, I guess I rushed to a conclusion before.

**Comment by XDTM** [comment]
So can we put the light on the head now that we have vg lighting?
