### ISSUE TITLE
pAIs can access the strip menu and disable internals from it.

### ISSUE THREAD

**Issue by Haevacht** [tgstation/tgstation#24736]
BrownElfTrapMaid: Oh hey. Something I noticed earlier: As a pAI hologram, you can disable or enable someone else's internals.
BrownElfTrapMaid: Iunno if that's supposed to be a thing.

BrownElfTrapMaid: Haevacht: I dragged their sprite to mine, and they had an internals tank set up. I pressed the disable interna;s button

@kevinz000 fix your shit

**Comment by Poojawa** [comment]
I miss the days where pAIs could steal people's shoes.

have the pAi strip all the shoes, throw glass everywhere and run.
