### ISSUE TITLE
Mousetrap box no sprites

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#24741]
Default box sprites .

**Comment by kevinz000** [comment]
still not fixed FIX IT FIX IT I NEED TO KNOW WHICH BOX HAS MY HACKING TOOLS WHICH BOX IS MY INTERNAL BOX WITH RANDOM ITEMS AND WHICH BOX CARRIES AMMO FIX IT FIX IT ;-;-;-;-;

**Comment by kriskog** [comment]
They do now
