### ISSUE TITLE
Frozen overlay doesn't work on objects that smooth, like tables

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24744]
![image](https://cloud.githubusercontent.com/assets/609465/23623814/549d942a-029b-11e7-85d2-720cad9ac5a9.png)

#fuckingfreon

**Comment by Cyberboss** [comment]
THAT'S WHAT IT IS!!

**Comment by Cyberboss** [comment]
It would be nice if we could make it so that the overlay is ACTUALLY an overlay and not weirdass icon blended voodoo bullshit

**Comment by xxalpha** [comment]
2smooth4goof

**Comment by Iamgoofball** [comment]
That's weird, it worked awhile ago. Did someone change smoothing code?

**Comment by xxalpha** [comment]
Did it work before or after the overlay queueing?

**Comment by Iamgoofball** [comment]
Def. before.

**Comment by MrStonedOne** [comment]
@MrPerson do you know of any trickary we could do to make this work as an overlay?

**Comment by MrPerson** [comment]
Freezing uses icon procs so it needs to go through GetFlatIcon().

**Comment by MrStonedOne** [comment]
ya, but do you know of any trickary we could do make this work as an overlay so it wouldn't need to?
