### ISSUE TITLE
Some areas are permadark

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#24766]
![permadark](http://puu.sh/uxkpj/7e638b3f51.jpg)

Player said they walked through it repeatedly with a PDA light on, but it didn't light up. Toggling darkness removed it.

**Comment by PKPenguin321** [comment]
This was on Deltastation, by the way.

**Comment by BeeSting12** [comment]
Happened for me too. Also in that area just south of arrivals hallway and north of bridge.

**Comment by ChangelingRain** [comment]
Probably something not updating opacity properly.

**Comment by Armhulen** [comment]
This isn't your everyday darkness...

**Comment by Cyberboss** [comment]
This isn't happening for me on master. Looks like the lights just broke

**Comment by Cyberboss** [comment]
Or I may have fixed it with #24762

**Comment by Cyberboss** [comment]
Someone double check for me?

**Comment by PKPenguin321** [comment]
I'll be keeping an eye out.

**Comment by PKPenguin321** [comment]
Haven't seen this happening lately, anybody else?

**Comment by PKPenguin321** [comment]
Still haven't seen this. Probably fixed.
