### ISSUE TITLE
Ore Boxes when emptied empty everything causing massive lag similar to the ore satchel bug

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#24767]
Yeah so the fix wasnt applied to ore boxes and they are lag machines.

To replicate place about 3,000 sand on the ground pick them up in an ore satchel while dragging ore box. Then empty ore box after getting spammed with messages 6,000 times and then watch the lag roll in

**Comment by Quardbreak** [comment]
I need information about when this problem been fixed.
