### ISSUE TITLE
Smooth lighting is several kinds of fucked

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#24779]
![explosive outpost 17 2017-03-06 213905](https://cloud.githubusercontent.com/assets/8237862/23639537/5cc3a41c-02b6-11e7-8204-fef85a9e2ca9.png)
Not pictured: Horrible flickering as if my GPU was dying a slow, agonizing death.  Was able to fix by reconnecting to the server.
Server was Sybil, no testmerged PRs.

**Comment by Hatfish** [comment]
Have a few more pictures:
![rogue tomb 9 2017-03-06 215533](https://cloud.githubusercontent.com/assets/8237862/23639827/b5646f10-02b7-11e7-8fda-ac48d7289eba.png)
This was taken mid-flicker on a separate round.
![rogue tomb 9 2017-03-06 215355](https://cloud.githubusercontent.com/assets/8237862/23639830/b8562d62-02b7-11e7-829b-7bdff2bd5e52.png)
![rogue tomb 9 2017-03-06 215024 1](https://cloud.githubusercontent.com/assets/8237862/23639832/bd017330-02b7-11e7-9245-c60c0a7e41ff.png)
These are probably related to smooth lighting, but I don't have any way to confirm.

**Comment by ShadowDeath6** [comment]
the giant triangle actually made me chuckle

**Comment by MrStonedOne** [comment]
byond full version number and system specs please.

**Comment by Hatfish** [comment]
BYOND version is the latest beta, 1376.

If you need any more specific specifications please tell me.

Operating System
	Windows 10 Home 64-bit
CPU
	Intel Core i7 @ 2.50GHz
	Skylake-U/Y 14nm Technology
RAM
	12.0GB Dual-Channel Unknown @ 1063MHz (15-15-15-36)
Motherboard
	HP 81EB (U3E1)
Graphics
	E28h-C1 (1360x768@59Hz)
	Intel HD Graphics 520 (HP)
Storage
	931GB Hitachi HGST HTS541010A9E680 (SATA)
	931GB TOSHIBA External USB 3.0 USB Device (USB (SATA))
Optical Drives
	hp DVDRW GUD1N
Audio
	Realtek High Definition Audio

**Comment by WJohn** [comment]
![](http://i.imgur.com/yxW8O4E.png)

Not sure what caused this. Might be foam or smoke or carpet grenades.

**Comment by MrStonedOne** [comment]
@wjohn that looks like an admin mass varedited lights to a range of 3 the only thing that looks out of place is the water tank, but that just as easily be bluespace, teleporter, etc. Am i missing something?

@Hatfish I can't remember, did i ever have you try to install the directx SDK to see if that resolved the issue?

**Comment by Hatfish** [comment]
This seems to have been fixed by the optimizations to the new lighting system, if it's still an issue for anyone it can be reopened.
