### ISSUE TITLE
Cannot automatically type in chat box

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#24776]
Even with chatmode on, the chatbox must be reselected after clicking anywhere outside of it, otherwise no typing will be registered.  Probably a BYOND bug.
Occurred on Sybil with no testmerged PRs.

**Comment by AnturK** [comment]
Byond version ?

**Comment by lzimann** [comment]
Latest byond is having issues with the chatbox focus. I suggest downgrading to 1375 meanwhile.

**Comment by Hatfish** [comment]
@AnturK Beta 1376

**Comment by Hatfish** [comment]
Fixed by the latest update.
