### ISSUE TITLE
MAJOR DESIGN ISSUES: NUKE OPS AND EMPS

### ISSUE THREAD

**Issue by Cheridan** [tgstation/tgstation#24775]
Originally an antag item to be used against the station, these items currently completely fuck up nuke ops.

They fry mechs, ops most expensive items, causing battery loss and malfunction.
If the nuke ops use augments they just goddamn explode. The CNS Rebooter item that they can buy just gives you a heart attack when EMP'd and you die.

Because of the existence of eshields/sword, the station crew have adapted to use ballistic shotguns instead of energy weapons in response to nuke ops anyway, so EMPs don't even provide a defense against the crew at all. 

We've gone so completely backwards on what EMPs are supposed to be, especially in this game mode, that I'm labelling this as a priority design issue. It's crippling anti-synergy in a mode where the odds are already stacked against you.

**Comment by ShadowDeath6** [comment]
make syndieborgs emp resistant when

**Comment by Iamgoofball** [comment]
just slap EMP resist on all of it

**Comment by PKPenguin321** [comment]
One time I had thermals and CNS rebooter and we also bought a mech, later I got hit from down a full hallway by a stray ion gun shot that was fired at the mech and instagibbed

Feels bad

**Comment by ExcessiveUseOfCobblestone** [comment]
Will cheridan be /ourguy/ in the removal of EMPs?

**Comment by Robustitron** [comment]
@Iamgoofball

Just making all op gear resistant sounds sloppy and would probably spill into regular traitor gear, and make it hard to tell what emp works on.

How about just giving each op an "emp shield" implant that makes them and everything they hold immune, then slap emp resistance on the mechs and borgs.

**Comment by Robustitron** [comment]
Or slap that emp shield on all the op hardsuits of you want risky stealth ops and emp executions

**Comment by xxalpha** [comment]
Who merged steelpoints ballistic security PR?

**Comment by WJohn** [comment]
EMPs should be nerfed in general, really. They're effectively an AoE 1 hit kill on cyborgs, AIs (by hitting the APC), and implants/thermals. Also shuts down energy weapons, mechs, and a host of other things.

At the VERY LEAST remove the AoE, and prevent it from triggering wires in cyborgs so it doesn't randomly lock them down effectively permanently.

**Comment by kriskog** [comment]
So some quick testing on current master yielded:
-CNS rebooter and Reviver implant have a fairly low chance of catastrophic effects when hit by ion/emp.
-Mechs still get fucked over by anti mech weapons like ion and emp (though this has recently changed as well).
-Augments get fucked over by emp.

The nukie meta moved away from maining these implants and augmenting a while ago, and it seems they have gotten less bad. There should be drawbacks to auging yourself. Closing this, post a feature request on forums if you disagree.

**Comment by ExcessiveUseOfCobblestone** [comment]
emps will forever be trash, good job for closing it lol
