### ISSUE TITLE
The new lighting is hard on weak GPUs

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#24782]
Because the new lighting uses a lot more client side operations than the old lighting does people with old computers and/or cruddy GPUs are adversely affected. This issue is just a general call for optimization and/or configurable options to reduce the burden on the less fortunate people who might be playing SS13 because it traditionally asked very little of client's machines.

Until then you'll probably be able to tell who's affected the worst because they'll be the people wearing mesons all the time.

**Comment by Arianya** [comment]
I'm not sure we can make it a user-side configurable option, given that not only would running two seperate lighting systems wreck the server, but they offer different levels of visibility which would result in situations where you can see someone who on their screen is shrouded in deep darkness, etc.

**Comment by Incoming5643** [comment]
I'm not sure exactly how it works but I was thinking less "Keep both lighting systems and let players choose which to use" and more "use two planes, one of a rough basic look and a second for the nice looking minutiae effects and let people option to either show both or just the basic layer."

**Comment by MrStonedOne** [comment]
@Incoming5643 some of it will go away when the new version of byond is released. the trick i'm doing right now to fix the memleak creates extra color matrixes for the client to track that don't get used

**Comment by Incoming5643** [comment]
It wasn't fantastic even before the memleak fix, but yeah I'm aware of that one.

**Comment by MrStonedOne** [comment]
could you maybe play around on a local server and tell me how updating lights vs static lights effect shit?

But it would be easy to actually do both lighting systems and let players choose via planememes. I'd just be worried about having to track two lighting objects for each tile and image overrides would be worst. maybe i could do something via planememes to make it still be one lighting object, just a different icon...

**Comment by Incoming5643** [comment]
Sure but just from what I've already experienced:

* Worse in observer mode than playing (due to more tiles in sight obviously)
* Most/all lag experienced while moving my character. A light source moving across my static screen has very little impact, but moving my screen over new tiles has a large one
* Darkness seems "more expensive" than light. Less lag in fullbright areas.
* Lag is somewhat remedied by dropping client fps, but dips are still noticeable even in 5 fps (I keep mine synced at 20 usally).

**Comment by Durkel** [comment]
How poor of gpu or pc are we talking here?

**Comment by MrStonedOne** [comment]
like a 5 year old low/mid end laptop iirc

**Comment by Incoming5643** [comment]
I use a Thinkpad T61, which was considered a very nice laptop (but not a """Gaming Laptop""") when it was released. 

In 2009.

That said I've heard complaints from people who's machines aren't quite so comically old too. My dire computing straights just makes me a good barometer for the extremes of these things.

**Comment by PKPenguin321** [comment]
dude go on like craigslist or something i'm sure somebody will be giving away an at the very least more recent laptop

**Comment by Incoming5643** [comment]
Old thinkpads are addicting. Even if financially I was equipped to move on I probably wouldn't. You aren't gonna find nice seven row switch keyboards and matte screens in the thrift shop.

http://ktgee.net/post/49423737148/thinkpad-guide

**Comment by PKPenguin321** [comment]
stockholm syndrome is real

**Comment by Arianya** [comment]
For anyone reading who may not know, the graphics card is _very_ underpowered.

You could go out now and buy a Radeon R7 250 card for $40 that would be over fifteen times as powerful, and even that would be very low-spec as far as gaming is concerned.

Assuming these issues are intrinsic to the lighting system as opposed to related to the memleak/workaround, the question comes down to "how much can we optimize the lighting system" and "how far back do we want our compatibility to go". 

Obviously quite a few players play SS13 due to its low requirements, but even so we don't support Commodores, for good reason.

**Comment by Incoming5643** [comment]
>We don't support Commodores, for good reason

Well I mean I think the point here is historically we _have_. BYOND has only comparatively recently given us the ability to do things that are client intensive. For the decade+ that preceded that BYOND was an engine that asked almost nothing of the client.

**Comment by Shadowlight213** [comment]
I'm using a relatively new computer and am experiencing lag spikes when moving around as a ghost in dark areas, so it's not just incoming's pc being bad.

**Comment by Dorsisdwarf** [comment]
Same here, I get crippling spurts of lag with the new lighting system despite having a decent and not old PC that just didnt exist beforehand.

It sucks because the new lighting is fucking ace and I love it

**Comment by MrPerson** [comment]
Part of this is byond's fault. It's comically shitty at rendering.

**Comment by ShizCalev** [comment]
Still needed?

**Comment by Incoming5643** [comment]
I did, _eventually_, get a better laptop
