### ISSUE TITLE
Ghosts can change active hands of players they're observing

### ISSUE THREAD

**Issue by spectralexplorer** [tgstation/tgstation#24825]
3177ddd52a244025099e941a05ac53c28d3d7a62 
testmerge #24253 

If you observe someone as a ghost (the full on Observe, not just orbit) you can change their active hand by clicking it the same way you would as the player

**Comment by AnturK** [comment]
Just a visual effect. Still should probably be fixed

**Comment by jughu** [comment]
@AnturK it auctally isnt visual

**Comment by jughu** [comment]
Aka IT is high priority as you can ruin somoenes round by mass clicking tbe other hand as them prevent shooting
