### ISSUE TITLE
Nuke explosion killing people extremely delayed

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#24828]
The round has ended.
    Shift Duration: 0:40:11
    Station Integrity: Destroyed
    Total Population: 49
    Survival Rate: 45 (91.8%)

The actual killing of people on station didn't occur until almost a full minute later, after the cinematic disappeared.

Also, hiding in disposals/lockers lets you avoid the gibbing.

**Comment by AnturK** [comment]
I guess it's done only after the check ticked giant explosion.

**Comment by Cyberboss** [comment]
It's done after the animation plays, this isn't a bug

**Comment by Shadowlight213** [comment]
@cyberboss it's a bug that it kills people after the round end report comes up though.

**Comment by coiax** [comment]
@Cyberboss yes, please kill everyone before the round end report, k thanks

**Comment by coiax** [comment]
@Cyberboss also, make sure cockroaches are immune like they were before.

**Comment by Shadowlight213** [comment]
@Cyberboss also, since nuke ops aren't killed until AFTER the round end has been calculated, they don't have to escape to avoid getting the total annihilation ending.
They'll get syndie major victory as if they escaped

**Comment by coiax** [comment]
@Shadowlight213 not true, the victory calculation checks if they're on the station, and sets it to TOTAL ANNIHILATION if none of them are off the station z-level.

**Comment by Shadowlight213** [comment]
Ah. My bad then. I thought it would check to see if they were alive

**Comment by coiax** [comment]
Yes, it also checks if they are alive.
