### ISSUE TITLE
Fix for fixing problems with icons causes problems with icons and needs a fix

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#24838]
Server revision compiled on: 2017-03-08
The following pull requests are currently test merged:
#24530: 'Fixes problems with icon overlays' by Cyberboss 

Based off master commit:
81ed80bf0b6c4c973e5f5e7d9a2fe33f11634872 

Items never get removed from hands, body is missing aside from eyes and hair etc.

![dreamseeker_2017-03-08_18-09-46](https://cloud.githubusercontent.com/assets/17237624/23714784/c95fd292-042a-11e7-9baa-2a7540d59ede.png)
![dreamseeker_2017-03-08_18-09-27](https://cloud.githubusercontent.com/assets/17237624/23714786/c96157e8-042a-11e7-80e8-8dad83f4bf0c.png)
![dreamseeker_2017-03-08_18-07-02](https://cloud.githubusercontent.com/assets/17237624/23714785/c9604984-042a-11e7-8269-8b100aa0875e.png)
![dreamseeker_2017-03-08_17-00-32](https://cloud.githubusercontent.com/assets/17237624/23714788/c96294d2-042a-11e7-98fa-a64536a9422c.png)
![dreamseeker_2017-03-08_16-57-08](https://cloud.githubusercontent.com/assets/17237624/23714787/c962d4d8-042a-11e7-8c8a-51d8af92781d.png)

**Comment by Cyberboss** [comment]
Ruh roh

**Comment by AnturK** [comment]
This is still broken on sybil without the pr testmerged. So this is kinda priority.

**Comment by optimumtact** [comment]
@AnturK that can't be right

**Comment by Cyberboss** [comment]
Yeah, it was an update race condition with the PR still running while not showing it

**Comment by optimumtact** [comment]
report this on the PR in question, not as a seperate bug
