### ISSUE TITLE
ex_act'ing the little atmos blocking fans doesn't restore proper gas flow

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/tgstation#24851]
What the title says. This shouldn't affect much at the moment as these are only used in airlocks right now, but if a mapper decides to use these creatively(example: using these fans in corridors at breach heavy areas), then this might become a problem.

**Comment by Cyberboss** [comment]
Nice find

**Comment by coiax** [comment]
TINY FANS ARE EVIL, PLEASE REMOVE THEM

**Comment by Cyberboss** [comment]
@coiax is right, tbh

**Comment by duncathan** [comment]
will investigate

**Comment by duncathan** [comment]
also tiny fans are infinitely better than what they replaced. feel free to come up with a better solution

**Comment by Cyberboss** [comment]
@AnturK didn't you fix this?

**Comment by coiax** [comment]
The better solution is CYCLING AIRLOCKS.

**Comment by AnturK** [comment]
Not me, but i recall someone adding air update in their destroy.

**Comment by duncathan** [comment]
cycling airlocks take up a whole 3*3 space tho don't they that's way too bulky

**Comment by coiax** [comment]
better than magic fans that make no sense.

**Comment by duncathan** [comment]
a little bit of handwave is worth not having to deal with bulky ass inefficient cycling airlocks that have always been terrible

**Comment by duncathan** [comment]
is this still around

**Comment by ShizCalev** [comment]
Fixed by #39210
