### ISSUE TITLE
Luxury shuttle design missing floors.

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#24864]
The "Luxury" shuttle design appears to be missing a large segment of the floor (see picture). I think from memory this is where the bar is.

Taken on Basil Server on Meta-station
![ss 2017-03-09 at 01 19 53](https://cloud.githubusercontent.com/assets/7211040/23731714/08455e96-0467-11e7-9ee8-a041b78381d6.jpg)
.

**Comment by Repukan** [comment]
That's where the swimming pool is.

**Comment by BeeSting12** [comment]
dupe of #24843

**Comment by Dorsisdwarf** [comment]
closed as dupe.
