### ISSUE TITLE
People can be bucked to pipes through floor tiles 

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#24866]
Saw this in an ahelp.
Someone was bucked to a pipe and a floor tile was placed over the pipe. The body then couldn't be moved and wasn't evident that they were buckled.

**Comment by coiax** [comment]
I wonder if you can buckle someone to a pipe that you can see with a t-ray scanner.

**Comment by duncathan** [comment]
my guess is that the floor tile was placed after buckling. will investigate and confirm

**Comment by duncathan** [comment]
yes, this is indeed what's happening. not sure what the best way to fix is just yet

**Comment by duncathan** [comment]
you can unassign me but don't remove the atmos label from atmos stuff svp
