### ISSUE TITLE
/vg/ light bug with plantpeople

### ISSUE THREAD

**Issue by Doppeltongue** [tgstation/tgstation#24872]
Under /vg/ lights, plantpeople don't heal under lighting, no matter how strong the lights are. This has happened consistently when spawning into the well-lit lavaland plant vault and taking light brute damage.

**Comment by coiax** [comment]
The plant vault doesn't have lighting, it's one of the special areas like shuttles that are just permalit. It's not been a problem before, but I guess NEW LIGHTING MEMES

**Comment by Doppeltongue** [comment]
I'm pretty sure that there's also been issues with the light from bioluminescent plants, even the ones that should light up the area don't help plantpeople heal. It's probably an issue with light in general.

**Comment by MrStonedOne** [comment]
fixed in #24963

**Comment by Buggy123** [comment]
This is fixed, Close this. @MrStonedOne
