### ISSUE TITLE
Floorbot creation

### ISSUE THREAD

**Issue by DanteRU0312** [tgstation/tgstation#24885]
You can only create floorbot from a blue toolbox. It seems logical, and you can technically print toolboxes on autolathe if you need more. But you can only print red ones and they can't be used for floorbot creation. So, we need to add ability to print different toolboxes for different purposes, or add differently colored floorbots from different toolboxes, like medibots, or add different bots like firebot, that you can make from other toolboxes.

**Comment by Dorsisdwarf** [comment]
Feature requests do not belong in the issue tracker, bring it up on #coderbus or make a forum thread.
