### ISSUE TITLE
Butterflies are moved by conveyer belts

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24880]
Based off master commit:
61888156be7463ccc9616afc52495c324dd275b7 

PLEASE FIX, CRITICAL BUG

**Comment by RemieRichards** [comment]
conveyor belts create wind that pushes the butterflies, this is science.

**Comment by coiax** [comment]
LIIIIIIIIIIIIIIIIIIIIES

**Comment by ShadowDeath6** [comment]
implying butterflies aren't bugs

**Comment by MrPerson** [comment]
goddamnit I was going to make a butterfly-bug joke YOU STOLE MY THUNDER
