### ISSUE TITLE
Space cult

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#24897]
![](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTryFuLva4rj2xL9uBcLRxLIpr3kVTgd6dwI38nGJRFReMbOmMwRAJ66RI)

**Comment by ChangelingRain** [comment]
>Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity.

**Comment by PKPenguin321** [comment]
Make a better bug report nerd
