### ISSUE TITLE
Handheld crew monitors cause a ping spike when activated

### ISSUE THREAD

**Issue by TheAutism** [tgstation/tgstation#24895]
It's pretty straight forward handheld crew monitors cause a vary large ping spike when first activated. this seems to vary. One of the admins reported a spike hitting around 440 while i hit around 1300 and then crashed beyond. The admin also reported that the monitor did not keep the ping up after the initial spike.

**Comment by PKPenguin321** [comment]
I think this a dupe

These things just crash the game for me

**Comment by Mark9013100** [comment]
Lags me on Box and Meta station, flat out crashes me on Delta station.

**Comment by optimumtact** [comment]
yah because it's a bigass png that gest streamed to you with updates about crew location

in short it's garbage
