### ISSUE TITLE
A changeling suiciding with a tentacle has an odd message

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24908]
> Changel Ling is twisting the tentacle above their head, releasing a magical blast! It looks like they're trying to commit suicide!

I assume they're like... wands or something? @XDTM

**Comment by jughu** [comment]
>implying changelings arent just very advanced biomagic

**Comment by XDTM** [comment]
I kinda left that in to see how long it would be for someone to notice, but i'll patch it out if too unimmersive.

**Comment by PKPenguin321** [comment]
Is it a reference

**Comment by Incoming5643** [comment]
It's a side effect of the ability being pathed as a magic based gun (a staff/wand)

**Comment by XDTM** [comment]
Those are projectile-based, tentacles wouldn't be in the list anyway since they're their own type.
