### ISSUE TITLE
Cults make space bases too much

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#24900]
![](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTryFuLva4rj2xL9uBcLRxLIpr3kVTgd6dwI38nGJRFReMbOmMwRAJ66RI)

![Imgur](http://i.imgur.com/59PtjZ5.png)
When did this become normal and acceptable.

**Comment by PKPenguin321** [comment]
Did they use blueprints or ?????
Make a better issue report

**Comment by DanteRU0312** [comment]
LMAO, first space base i saw, so no, they don't make these too much.

**Comment by Supermichael777** [comment]
this is more about a strategy that's too play to win. clock cult got nerfed when they did this, so blood cult should suffer the same.

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation/pull/1717

We had the same problem, maybe this'll help

**Comment by jughu** [comment]
Auctaly they usef a ghetto space suit aka firesuit and coffee to get it first place probaly also a rcd from a hacked autolathe

**Comment by xxalpha** [comment]
not a bug

**Comment by optimumtact** [comment]
post on forum
