### ISSUE TITLE
The lower robotics fabricator on Box can't sync to RnD

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#24912]
;-;

**Comment by GunHog** [comment]
Probably distance related.

**Comment by Penguaro** [comment]
The problem is the physical distance from the Robotics R&D Console. If rebuilt in game in the same position, sync error occurs. Relocating the machine closer to the Console allows it to sync.

**Comment by xxalpha** [comment]
The problem is the bad way of syncing these machines.

**Comment by Sligneris** [comment]
Actually it'd be better if it were area based.

**Comment by factoryman942** [comment]
What about signallers? Set the computer to sync on a specific frequency, and put signallers set to that frequency on the machines?

**Comment by xxalpha** [comment]
Area based means you can't have more than one pairing in the same room.

**Comment by Sligneris** [comment]
Actually you can, since RnD consoles don't really use exosuit fabricators, it's just exosuit fabricators that use the RnD console.

Kinda like Robotics was able to have two exosuit fabricators connected to a single RnD console since forever.

**Comment by factoryman942** [comment]
It's just that they work in a range of like 3 tiles
And the bottom fabricator's too far from the console
Maybe make the console sync range a variable or something, which defaults to what it is now, and have the robotics one be longer range

**Comment by Sligneris** [comment]
Metastation fabricators are much further from the console and they work just fine, though?

**Comment by factoryman942** [comment]
Hm
Something's fucky

**Comment by Penguaro** [comment]
The current distance was set to 5 tiles. I created a PR to adjust the range to look 7 tiles out and that now allows it to sync.
