### ISSUE TITLE
Be able to stick paper onto packages & boxes

### ISSUE THREAD

**Issue by Davidj361** [tgstation/tgstation#24910]
You should be able to stick paper onto packages, boxes, and boxes. It helps with the cargo bay roleplay, etc. I will add this myself if I have to. I WANT TO STICK RECEIPTS AND REQUEST FORMS ONTO PEOPLE'S ORDERS.

**Comment by XDTM** [comment]
Feature requests/ideas go on the forum

**Comment by Davidj361** [comment]
oh

**Comment by lzimann** [comment]
What he said.
