### ISSUE TITLE
Odd Spear Glitches

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#24916]
So basically I was fighting with a spear and at one point the offhand object got equipped and I could hit stuff with it, and couldn't switch hands back. And another time, the spear sprite showed as in my right hand, but I couldn't pick things up with my left hand. So I think that equipping with spears is being weird lately. Might be hard to reproduce, sorry, can't really say what actions led up to it, just that it happened. 
9:40 pm EST, 3/9/17, tgstation Bagil
Sorry if this was kinda vague, I'm tired whiel writing this

**Comment by Arianya** [comment]
Twohandeds have been weird for a while.

For reference, if you end up with the "offhand" as your active, you can activate it to self destruct the offhand

**Comment by BeeSting12** [comment]
@optimumtact 
This is probably a dupe of #25814 so I think it could be closed unless you think it's something else.

**Comment by optimumtact** [comment]
yep
