### ISSUE TITLE
Every person that talks in deadchat has like 7 (F) links next to their name

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#24925]
See title

![aaaaa](https://puu.sh/uCc9Y/681b3f6056.png)

**Comment by PKPenguin321** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAA!!
![AFJDKSFJDSKFDSKJFDSLF](https://puu.sh/uCcAb/7b0671c9ec.png)

**Comment by YakumoChen** [comment]
there's only more as time goes on

**Comment by Boredone** [comment]
Huh, it went down for me as a near round start observer, 4 (F) near roundstart, 2 (F) near nuking.
As a note, this only applies to messages specifically to ghosts, like deadchat, or death annoucements.
Doesn't effect normal folks chatting. (Atleast didn't for me)

**Comment by Bawhoppen** [comment]
working as intended

**Comment by xxalpha** [comment]
many respects were paid

**Comment by Iamgoofball** [comment]
F
