### ISSUE TITLE
Follow links are borked

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#24934]
![untitled](https://cloud.githubusercontent.com/assets/8237862/23799623/2d6da8fc-0577-11e7-8109-a4822e05cf8c.png)
Possibly related to #24927, which was also the only testmerged PR at the time on Sybil.

**Comment by Iatots** [comment]
Oh hey, that's my name. 
Was this my suicide with the instakill rifle?
Did any of the other deaths I caused with it show that error?

**Comment by Hatfish** [comment]
Yes, it was your suicide.
I don't remember if any other deaths did this, yours was the only one I saw at the time.

**Comment by Hatfish** [comment]
Doesn't seem to be occuring any more, closing unless it occurs again.
