### ISSUE TITLE
Input delay/freeze bug

### ISSUE THREAD

**Issue by dhostak** [tgstation/tgstation#24931]
At random times during a round any input I try to send to the server gets ignored. I can see people move and talk around and at me normally but I cannot respond, move, use commands, and so on. I asked about this on supportbus and atleast one other person has said they've experienced this (ausops). The best way around this seems to be spamming connect and that takes 10-20 seconds to regain control.  Sometimes my input will be delayed by 10-20 seconds and if I leave it alone it might recover in a full minute or so.

What I've ruled out that could be causing this:
Shaky internet - I've had two different ISP's and a solid internet connection, different routers/modems as well. I tested for packetloss by pinging google while this was happening and it was at 0%.
Byond version - I've had this on a previous version, the new stable release, and now the beta release and it happens across the board.
/tg/ inclusive bug - Tested on Bay and some others (including one I hosted locally albeit on like 8month old tgmaster code)

Only ideas are byond not playing well with my win7 version or packet loss on some specific route to where the server is hosted

**Comment by CrAzYPiLoT-SS13** [comment]
It's indeed possible that one of the bounce servers your packets are routed
to to get to the server is down/slow periodically. Try using a VPN or a
proxy, and see if it happens then.

**Comment by dhostak** [comment]
Used a VPN and it solved the issue, I'm concluding it was on my end with a DNS mix up.
