### ISSUE TITLE
Runtime in turf.dm,256: undefined variable /turf/basic/var/air

### ISSUE THREAD

**Issue by rainbowjose** [tgstation/tgstation#24949]
[23:51:34] Runtime in turf.dm,256: undefined variable /turf/basic/var/air
proc name: Assimilate Air (/turf/open/proc/Assimilate_Air)
src: the mech bay recharge station (125,173,1) (/turf/open/floor/mech_bay_recharge_floor)
call stack:
the mech bay recharge station (125,173,1) (/turf/open/floor/mech_bay_recharge_floor): Assimilate Air()
the mech bay recharge station (125,173,1) (/turf/open/floor/mech_bay_recharge_floor): AfterChange(0)
the mech bay recharge station (125,173,1) (/turf/open/floor/mech_bay_recharge_floor): ChangeTurf(/turf/open/floor/mech_bay_rech... (/turf/open/floor/mech_bay_recharge_floor), 0, 0)
the mech bay recharge station (125,173,1) (/turf/open/floor/mech_bay_recharge_floor): ChangeTurf(/turf/open/floor/mech_bay_rech... (/turf/open/floor/mech_bay_recharge_floor))
the mech bay recharge station (125,173,1) (/turf/open/floor/mech_bay_recharge_floor): ChangeTurf(/turf/open/floor/mech_bay_rech... (/turf/open/floor/mech_bay_recharge_floor))
the mech bay recharge station (125,173,1) (/turf/open/floor/mech_bay_recharge_floor): New(the mech bay recharge station (125,173,1) (/turf/open/floor/mech_bay_recharge_floor))
/dmm_suite (/dmm_suite): instance atom(/turf/open/floor/plasteel/red/... (/turf/open/floor/plasteel/red/side), /list (/list), 125, 173, 1, 1)
/dmm_suite (/dmm_suite): parse grid("/obj/machinery/atmospherics/pi...", 125, 173, 1, 1)
/dmm_suite (/dmm_suite): load map impl(_maps/map_files/TgStation/tgst..., 1, 1, 1, null, null, 1)
/dmm_suite (/dmm_suite): load map(_maps/map_files/TgStation/tgst..., 0, 0, 1, null, null, 1)

**Comment by Cyberboss** [comment]
Fixed by #24856

**Comment by duncathan** [comment]
oh no

**Comment by Cyberboss** [comment]
Basic turfs don't exist anymore so this is closable @lzimann
