### ISSUE TITLE
Infinite loop suspected--switching proc to background.

### ISSUE THREAD

**Issue by rainbowjose** [tgstation/tgstation#24958]
Loaded station in 14.4s!
Infinite loop suspected--switching proc to background.
If it is not an infinite loop, either do 'set background=1' or set world.loop_checks=0.
proc name: get area turfs (/proc/get_area_turfs)
source file: unsorted.dm,650
usr: (src)
src: null
call stack:
get area turfs(/area/space (/area/space), 0, 0)
process teleport locs()
Mapping (/datum/controller/subsystem/mapping): Initialize(849594)
Master (/datum/controller/master): Initialize(10, 0)
Infinite loop suspected--switching proc to background.
If it is not an infinite loop, either do 'set background=1' or set world.loop_checks=0.

**Comment by rainbowjose** [comment]
This is not a runtime. This shit freezes server completely

**Comment by Razharas** [comment]
@Cyberboss

**Comment by MrStonedOne** [comment]
the runtime is a red harring
the real freeze is in a runtime that happens just after that one, but you don't see in dd unless you have world.log redirected

**Comment by Cyberboss** [comment]
FUCK WHY IS IT BACK?

**Comment by MrStonedOne** [comment]
>This is not just a runtime. This shit freezes server completely

It is a runtime,

**Comment by rainbowjose** [comment]
okay
