### ISSUE TITLE
Metal stack issues

### ISSUE THREAD

**Issue by feemjmeem** [tgstation/tgstation#24957]
Spawn fifty-stack of metal
Remove one from stack with open hand
Drop the one you remove
Remove again

OH NO INVISIBLE 0-COUNT STACK

it shows in-hand on sprite but stacking seems to be broken again

**Comment by DanteRU0312** [comment]
Encountered the same thing with other materials. Grab some uranium from ORM, click on it with other hand, receive a stack of uranium with 0 uranium in it. It's invisible in hand, and if you drop it, it'll dissapear, but you can stick it into destructive analyzer and get Material research, for example.

**Comment by AnturK** [comment]
Fixed by #24941
