### ISSUE TITLE
Duplicate plant vaults spawning in lavaland

### ISSUE THREAD

**Issue by ma44** [tgstation/tgstation#24956]
[Note]: # (Please enter the commit hash and active testmerge numbers from the "Show Server Revision" verb if you can. If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))
https://github.com/tgstation/tgstation/commit/2e3bba939216f17ad0c33533951ab39f37359898
Current test merged prs: https://github.com/tgstation/tgstation/pull/24927

https://i.gyazo.com/60908756d9d375e5c87c86ccbff56426.png

https://i.gyazo.com/2e955a9517c153fff11250da6024654c.png

Two plant vaults in lavaland, don't know what caused this

**Comment by RemieRichards** [comment]
are you sure it wasn't an admin? admins can load any template they please, anywhere, at any time, this was the original usecase of the template system.

**Comment by ma44** [comment]
I don't know if this was the cause of an admin

**Comment by PKPenguin321** [comment]
Can this not happen naturally?

**Comment by RemieRichards** [comment]
Then come back with evidence it was the code's fault, there have been no major changes to the template/ruin system in quite a while, and I'm sure this bug would have appeared during that time if it existed.

**Comment by ShizCalev** [comment]
still a bug?
