### ISSUE TITLE
Can't order surplus syndie crate (assistant, latejoin)

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#24968]
Step to reproduce:
1) late-join assistant and roll traitor
2) unlock PDA, realize surplus crate can't be ordered
3) adminhelp it to kevin, receive no response
4) come up with a decent prayer for kevin, get no response
5) just order random items
6) stimpacks are fucking useless

**Comment by XDTM** [comment]
They're disabled on lowpop

**Comment by Iatots** [comment]
oops
