### ISSUE TITLE
Auxiliary base console can't build airlock over tiny fans

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#24969]
When using auxiliary base building console, it's impossible to build airlocks on top of tiny fans.

**Comment by GunHog** [comment]
Build the airlock first. This one will be a bit harder to fix without specific type checks on the RCD

**Comment by Sligneris** [comment]
Regular RCDs can build over tiny fans just fine, though?

**Comment by kriskog** [comment]
Can't reproduce
