### ISSUE TITLE
SPACE TRANSITIONS ARE BROKEN

### ISSUE THREAD

**Issue by Cheridan** [tgstation/tgstation#24965]
Transitions off of z1 to other z-levels results in teleporting the user to the rupee room with the message "X was found to have no .loc with an attached client, if the cause is unknown it would be wise to ask how this was accomplished."

Loops from z1 to z1 seem to be working fine.

**Comment by Razharas** [comment]
All the transition code is at least 3 months old, most of it is untouched since i made it
Also judging by the live server testing any attempt to transfer people to zlevels higher than 5 results in being sent to nullspace
@Cyberboss 
Your dynamic zlevels arent working properly

**Comment by rainbowjose** [comment]
Approve
