### ISSUE TITLE
[Downstream] Fingerprints aren't applied to TK interactions

### ISSUE THREAD

**Issue by Poojawa** [tgstation/tgstation#24971]
So had a Chemist who was doing Chemistry things, then left an empty beaker in the dispensor. All well and good.

Geneticist being a shit before being smacked, ended up doing a K/H2O explosion, but with TK, his fingerprints weren't assigned to the admin log

'ADMIN LOG: Reagent explosion reaction occurred at Chemistry (JMP). Last Fingerprint: <chemist>/(Ashlyn Sinclaire)? (FLW).
The solution violently explodes!
ADMIN LOG: Explosion with size (0, 1, 3, 0) in area Chemistry (135,122,1 - JMP)'

Chemist, at the time of explosion, was elsewhere, and wasn't interacting with the machine. Technically TK has no visible fingerprints, but like AI interactions having the hidden ones, it might be good to slap that detector on there.

our last sync was 2/28, but nothing has changed with fingerprints since then, least from a simple search turns up.

**Comment by XDTM** [comment]
also worth adding for silicon interactions i suppose

**Comment by ShizCalev** [comment]
Fixed by #29709
