### ISSUE TITLE
Window item interaction broken

### ISSUE THREAD

**Issue by Jordie0608** [tgstation/tgstation#24972]
You are unable to interact with fulltile windows using item to i.e. fasten a window or hit it with a fire extinguisher.
@ChangelingRain

**Comment by Sligneris** [comment]
Window interaction broken in general, I would say - you can't even click on them to knock. It also applies to windoors, that can't be opened by click on them.

**Comment by xxalpha** [comment]
Tell @ChangelingRain

**Comment by rainbowjose** [comment]
Approve!

**Comment by Sligneris** [comment]
Why would you approve of gamebreaking issues?

**Comment by rainbowjose** [comment]
That's because my bad english. I mean "confirm"

**Comment by octareenroon91** [comment]
Tools and melee attacks achieve nothing, and return no feedback to the player.
 #24842

**Comment by lzimann** [comment]
Fixed on #24994
