### ISSUE TITLE
Changelings Absorbtion malfunction

### ISSUE THREAD

**Issue by KingPhilipIII** [tgstation/tgstation#24986]
Right. So I was going about doing my linggy business, part of which involved mass murder, when I tried to absorb one of my victims.

After a normal changeling absorbtion wait period, you will get a message saying you absorbed so and so, and nothing more. No voices, no memeries. They don't even die. From then on if you try to husk them again it just says you're already absorbing. No more absorbtion for you, the sad ling.

**Comment by Repukan** [comment]
Dupe

**Comment by nfreader** [comment]
Unable to reproduce!
