### ISSUE TITLE
Beepsky arrests bar monkey when set to arrest unidentifiable persons

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#24991]
![cc8ddb8686](https://cloud.githubusercontent.com/assets/12747768/23825587/daa3c90a-068c-11e7-81dd-ee8976960d58.png)

I'd say arresting random monkeys is easily a feature (for example, it could be used against changelings or during a monkey infestation), but the bar monkey should be exempt from that.

**Comment by Anonmare** [comment]
Feature.
No ID, no mercy.

**Comment by AnturK** [comment]
Not a bug but i'll keep this open since it should probably display level or reason for these, there's also some runtime with monkey asses_threat iirc

**Comment by actioninja** [comment]
feature
