### ISSUE TITLE
Freeze Date

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#24992]
@tgstation/commit-access 
@MrStonedOne 

I suggest 22.03 + 2 weeks as starting point

**Comment by Cyberboss** [comment]
What for?

**Comment by XDTM** [comment]
785 issues and counting i'm guessing

**Comment by TrustyGun** [comment]
786 you mean?

**Comment by AnturK** [comment]
The pileup of major errors from recent refectors and features. This issue exist just to keep the discussion somewhere that's not IRC, this is nothing set in stone yet.

**Comment by optimumtact** [comment]
:+1: 
maybe start after April 1 though?

**Comment by JJRcop** [comment]
This is unrelated to the error count, but I have completed the identity system #25016, and would like to request a really short freeze until I am done retrofitting the codebase so that it can begin the testmerge process. Like a few days at most, ideally it will be done in 1 day.

**Comment by Iamgoofball** [comment]
what @optimumtact said

**Comment by PKPenguin321** [comment]
At earliest a bit after April 1st because April 1st memes

**Comment by Bawhoppen** [comment]
April fools stuff would be on a separate branch anyways? Start it right before so that way there are no features that are missed out on at April fools

**Comment by MrPerson** [comment]
The real april fool's is that the freeze will start a day early

Surprise!

**Comment by Xhuis** [comment]
@Bawhop Oranges has stated that there will be no April Fool's branch this year.

That said, unless we go that route, the freeze should probably start after the holiday imo. If we do a separate branch it could start sooner.

**Comment by Bawhoppen** [comment]
why did oranges say we wouldn't have an april fool's branch?

**Comment by Xhuis** [comment]
Ask him, not me. @optimumtact

**Comment by optimumtact** [comment]
We're starting 24th this month, exceptions are in place for april fools pr's that will be test merged by admins.

**Comment by Iamgoofball** [comment]
Can we still planet station?

**Comment by KorPhaeron** [comment]
@Iamgoofball 

Secretly name your PRs as fixes and I'll speed merge them before oranges sees them

**Comment by optimumtact** [comment]
screee
