### ISSUE TITLE
Unable to hear or speak in deadchat while in corpse

### ISSUE THREAD

**Issue by SamSamsonthe3rd** [tgstation/tgstation#25008]
2062e3610090de55c998b0c8ef8f4b8d3c547448
#24974: 'Temporal solution to transitioning to nullspace problem' by Razharas 
#24963: 'Fixes lighting of pixel shifted objects and reverts the hacky memleak fix.' by MrStonedOne 
#24941: 'Fixes stack splitting' by AnturK 
#24994: 'Fix for windows being uinteractable.' by AnturK 

Title sums it up. While my ghost is in my body, I cannot see deadchat or speak in deadchat. Any non-ooc chat I do doesn't go through. I've seen this bug on both humans and AI.

**Comment by coiax** [comment]
Yeah, I know about this, I've got a PR in the works to fix.

**Comment by Cyberboss** [comment]
This is a dupe of something...
