### ISSUE TITLE
Very very expensive lavaland

### ISSUE THREAD

**Issue by rainbowjose** [tgstation/tgstation#25007]
![ws2jvo3p3s7aevfjvgqtipcxyf9xh8 1](https://cloud.githubusercontent.com/assets/6819554/23827846/ac0761b4-06ce-11e7-8960-dc3144ff4c8c.png)

**Comment by Supermichael777** [comment]
retaliate is a lot of mobs

**Comment by Haevacht** [comment]
Not just lavaland, some spaceruins may have retaliate mobs.

**Comment by Iamgoofball** [comment]
we need to do an optimization pass on ListTargets()

**Comment by AnturK** [comment]
List target is the default hostile mob proc, retaliate or not. This is kinda meaningless profile, there might have been 10000 clowns there.

**Comment by rainbowjose** [comment]
You kidding. What a 10000 clowns. Its clear map after 5 minutes of loading.
