### ISSUE TITLE
The map editor in byond adds tags to items randomly fucking up all href links to that item

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#25004]
so byond does this stupid fucking thing of returning the tag for `\ref` if it has a tag.

byond also does this stupid fucking thing of adding tags to things when you map edit them

shit with these tags are fucked because of item one. rather then get a unique value for use in locate() in our link, we get a maybe unique value that sometimes is also shared because >byond

I propose we do the following things to clean this up:

Remove all uses of map edited tags (landmarks use this legitimately atm)

Travis check for no set tags in maps.

Bump my byond threads on this issue:
http://www.byond.com/forum/?post=2089978
http://www.byond.com/forum/?post=2089976
http://www.byond.com/forum/?post=2089979

**Comment by xxalpha** [comment]
We could have the mapmerger strip these?

**Comment by coiax** [comment]
I'm also changing the follow links to just use coordinates rather than turf /refs.

**Comment by Cyberboss** [comment]
@xxalpha Landmarks need a refactor first

**Comment by MrStonedOne** [comment]
This is is fixed in 512 and when travis or the codebase moves to 512 this can be closed.

**Comment by ShizCalev** [comment]
travis is now on 512.
