### ISSUE TITLE
Red circuit tiles do not glow

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25000]
@ChangelingRain fix plz

**Comment by Xhuis** [comment]
#25000

**Comment by PKPenguin321** [comment]
WASTED GET AAAAAAAARGGGG

**Comment by Cyberboss** [comment]
Every fuckin time

**Comment by coiax** [comment]
?

**Comment by Xhuis** [comment]
This is the 25,000th issue/PR. People have a long-standing tradition of using a meme PR or issue for the spot, but you ninjaed it before they could.

**Comment by coiax** [comment]
Turns out they do glow.

**Comment by Cyberboss** [comment]
WASTED FUCKING GET!!!!
