### ISSUE TITLE
Posibrains can be deleted from inside a mech by an explosion

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#25014]
Ash drakes fireball made my mmi get deleted as the dragon punched my empty mech frame to death after

**Comment by PKPenguin321** [comment]
First part is a dupe

**Comment by MrPerson** [comment]
After the explosion but before the dragon destroyed it, where you still in the mech or were you ghosted out of the mech?

**Comment by Kromgar** [comment]
@MrPerson Been busy playing breath of the wild. The mech was unharmed but my brain was instakilled. The dragon then proceeded to tear the mech apart
