### ISSUE TITLE
Posters + Windows

### ISSUE THREAD

**Issue by Davidj361** [tgstation/tgstation#25036]
Posters cannot be posted on windows. Makes it hard for security to post posters in medbay or the cafeteria since there are a lot of windows.

**Comment by WJohn** [comment]
I believe this is a layering issue. You COULD raise the posters to be layer 3.1 (or 3.2, whichever you want) but then that would be above item layer. I guess it's not so bad if it's above a window.

Second to that, windows can be screwed to be moved around, you'd have floating posters. I'm not sure how it's handled for when you decon a wall with a poster on it, but the same issue would crop up.

**Comment by Davidj361** [comment]
No, the poster stays in your hand.

**Comment by xxalpha** [comment]
Probably related to the window interaction issue.

**Comment by Iatots** [comment]
No alpha, this has been the case for a really long time.
I even rationalize it as deiberate in that hanging a poster on a window would make you unable to see through it. That said, they could just turn the window opaque.

**Comment by xxalpha** [comment]
Can you place posters anywhere else besides walls? I never really tried, but if you can't place them anywhere else then I wouldn't say it's deliberate, more like it never came to mind.

**Comment by JStheguy** [comment]
You can't place posters on anything but walls, the proc for placing posters is /turf/closed/wall/proc/place_poster() for some reason

**Comment by Jordie0608** [comment]
I'm going to say this is intended behaviour.
