### ISSUE TITLE
Arrivals Shuttle request console shows up as "Unknown" when it "talks"

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#25035]
I.e. when it says "Shuttle departing".

**Comment by Davidj361** [comment]
You mean in the chat window that in person it has the name unknown and not the announcement? And you mean the communications console, correct?

**Comment by bgobandit** [comment]
yes

**Comment by Davidj361** [comment]
And: "You mean in the chat window that in person it has the name unknown and not the announcement?"

**Comment by bgobandit** [comment]
"Unknown requests console beeps:"

**Comment by Cyberboss** [comment]
What map?

**Comment by Davidj361** [comment]
I have a feeling this is an issue with \code\game\machinery\computer\communications.dm.

**Comment by Cyberboss** [comment]
Box station looks fine to me, which map was this?

**Comment by Bawhoppen** [comment]
Pretty sure its meta

**Comment by bgobandit** [comment]
"Beeps" is the verb used when machines "talk," much like humans "say" and lizards" hiss.

This was on Box. You can hear it when you join the station.
