### ISSUE TITLE
The Tomb of the Unknown Employee really shouldn't be directly inside the endgame griff zone

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#25047]
Like, yes, it's kind of in the spirit of the game, but, uh. Kind of disrespectful?

**Comment by optimumtact** [comment]
disrespectful to who?

**Comment by Incoming5643** [comment]
pathing

**Comment by cacogen** [comment]
make the windows unbreakable if it's really that much of an issue

**Comment by Durkel** [comment]
There is no greater honor for a spaceman to be in the heart of the chaos and survive to see another day. For those who have come and gone we honor them in the most respectable way a spaceman can; By being part of every single round, carrying on their memory,and showing them that the chaos they helped create is still preserved. 

When you're smashing the clowns head in with a toolbox at round end, look up for a moment and think about the guys who helped make it all possible and aren't here to enjoy it anymore. Then hit that clown one more time because that's what they would have wanted.

**Comment by Iamgoofball** [comment]
It's supposed to be indestructible, I believe the fluff tag takes care of that.

**Comment by Iamgoofball** [comment]
it's placed directly at the end because much like life, the escape dock is something we all pass through.

**Comment by lzimann** [comment]
It's the best place to guarantee people will see it, better than in the station(and easier to maintain since there is only one centcomm map).

**Comment by Xhuis** [comment]
I don't know about y'all, but if I passed away and someone dedicated a memorial to me in game, I would definitely want it in the round end griff spot. It'd be hilarious to me. Just sayin'!

**Comment by Sligneris** [comment]
The Unknown Employee is watching over the crew, as they struggle to come out at the top in their final death battle, the most dangerous battle of them all.

**Comment by xxalpha** [comment]
All the souls of the spessmen who die near the statue are absorbed by the statue so one day the unknown employee can come back to life and remake ss13 in a new engine. So for this end it is placed in a very appropriate spot.

**Comment by factoryman942** [comment]
@Iamgoofball it can be broken
http://i.imgur.com/Q64dk1K.png

**Comment by Sligneris** [comment]
I can't believe the Unknown Employee has been turned into a Wraith

**Comment by Iamgoofball** [comment]
Oh for fucks sake

**Comment by optimumtact** [comment]
You could probably embed it in the wall behind some indestructible glass up in that grassy area above the shot there goof

**Comment by factoryman942** [comment]
>behind indestructible glass
>Wraith

just make the damn thing immortal

**Comment by Xhuis** [comment]
I have the perfect solution to this.

**Comment by Iamgoofball** [comment]
Just leave it where it is and make it indestructible that's all you need to do

**Comment by optimumtact** [comment]
no

**Comment by optimumtact** [comment]
remap it or else

**Comment by Iamgoofball** [comment]
Why are we hiding​it from view?

**Comment by Iamgoofball** [comment]
Stop shoving shit you don't like in the sidelines

**Comment by Iamgoofball** [comment]
Seriously it's supposed to be visible

**Comment by Iamgoofball** [comment]
Fuck it why am I arguing the creator of stuff has no control over the vision better put cat tail on it for le may Mays and put it in a box in the corner of the z level

**Comment by optimumtact** [comment]
It's not hiding it from view you scumbag it's putting it at the top of the arrival shuttle area like a recessed shrine how are you so dense

**Comment by Xhuis** [comment]
Can we not get in a flaming match over giving respects to someone who died? How fucking low can you go?

**Comment by optimumtact** [comment]
Much lower

**Comment by Incoming5643** [comment]
Personal opinion: Leave in the center for a month or so, put it behind the glass afterwards. Bring it back out the next time something like this happens (hopefully never but unfortunately an unrealistic expectation).

**Comment by optimumtact** [comment]
It doesn't make any sense in the center there sitting over the top of the N, move it up above so it actually looks like a monument/shrine

**Comment by Xhuis** [comment]
I think you're being incredibly pushy about this and I don't think it's necessary. But because it seems like I'm not going to sway you, I'll make your change.

**Comment by Xhuis** [comment]
Or not. HoG, economy, a new station, and now this.

**Comment by Iamgoofball** [comment]
I just want to make sure it's seen when people undock and is obvious

**Comment by optimumtact** [comment]
it would still be in arrivals you dip, it's just at the top instead. 

considering 99% of our players are just going to kill each other in arrivals anyway they're not looking at shit.

**Comment by cacogen** [comment]
it should be destructible but spawn a hostile mob when you do so
