### ISSUE TITLE
Brute damage overlay doesn't vanish after damage is healed

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#25049]
If you get hurt and heal, you still appear as hurt.

Also, are golems and slimepersons even supposed to have human damage overlays?

**Comment by Armhulen** [comment]
Do you mean the damage on the health doll, the red pulsing overlay or the actual blood effects on your character

**Comment by Sligneris** [comment]
Effects on the character.

**Comment by Armhulen** [comment]
I tried to reproduce this but I couldn't.

**Comment by Sligneris** [comment]
It can be reproduced pretty easily

- Be naked
- Get your body parts visibly hurt
- Try to find a Medibot
- See your health doll healed
- Body parts still look hurt

If that's not the case anymore, I guess this is resolved. Might also be an issue solely with slimepeople and golems.
