### ISSUE TITLE
Screen flickering

### ISSUE THREAD

**Issue by Charmisokay** [tgstation/tgstation#25055]
All the floor tiles and several textures (walls and tables) turn black (and back to normal) a couple of times per second. This happened immediately after I approached the brig on box station.

I restarted the game which fixed the problem, but the dynamic lightning looks a bit odd.

![image](https://cloud.githubusercontent.com/assets/25822752/23871492/f544f708-082a-11e7-9e51-4b7e87788f7e.png)

**Comment by AnturK** [comment]
Byond version ? OS ? Did you follow the steps outlined here : https://tgstation13.org/phpBB/viewtopic.php?f=2&t=5525#p220316

**Comment by lzimann** [comment]
Try following these steps: 
1: Update byond to latest beta 
2:Update video card drivers 
3:Install DirectX SDK

**Comment by Charmisokay** [comment]
The problem seems to have fixed itself after I restarted the game.
Windows 10, most recent version. Byond 511.1377
Nividia video card, updated my driver a couple of days ago.
