### ISSUE TITLE
Unable to use hands due to plant weilding. No plant in hands.

### ISSUE THREAD

**Issue by Nabski89** [tgstation/tgstation#25063]
"your other hand is too busy holding the potted plant (wielded) - Offhand error."

One hand shown with the dual wield sprite, the other empty.

I had tried to pick up a plant around the same time as I was clicking on an offer rune (with an offering and second player active to convert).

I ended up being unable to use my hands for anything. I could not throw or the plant. The plant was still an item that could be interacted with on the ground in other ways.

**Comment by Robustin** [comment]
Yea just had this happen to me, its a pretty big deal when it happens since you can't use any hands once this bug triggers.
