### ISSUE TITLE
Unable to use Ripley tools. while being MMI pilot.

### ISSUE THREAD

**Issue by LordGrimnar** [tgstation/tgstation#25064]
After becoming an MMI for borging and them not having enough stuff to complete a borg i was put in a Ripley to help mining after being put in, my tools were attached and then i was unable to use them on lavaland and on station

**Comment by PKPenguin321** [comment]
Dupe

**Comment by Armhulen** [comment]
Will someone just FIX THIS ALREADY

**Comment by lzimann** [comment]
This is a dupe and I've been lazy to dive into mecha code once again(it is a mentally tiring task).
