### ISSUE TITLE
A changeling test still exists.

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#25076]
changeling brains aren't real if you use decapitation + cutting it out of their head so you can use it to meta because it'll make a braindead mmi/borg. this isn't as hard of a tell as before but it's still a hard tell and I don't know how to fix it short of allowing lings to transfer between their fake and real bodies at will.

**Comment by XDTM** [comment]
It's definitely hard to abuse

**Comment by Cyberboss** [comment]
Could auto-prompt ghosts to take over a changeling fake-brain MMI like a posibrain

**Comment by RemieRichards** [comment]
What's the behaviour for when the brain has ghosted? it should just match that.

**Comment by MrStonedOne** [comment]
feature.

**Comment by Iamgoofball** [comment]
is it time for another "bugfix = fork" game?

**Comment by CPTANT** [comment]
Is there an inconsistency between this and braindead brains?

If not this should be closed.
