### ISSUE TITLE
Xenomorphs can't use double ctrl click for aggressive grab

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#25070]
As the title says - grab intent works just fine, but ctrl clicks stop at passive grab.

**Comment by XDTM** [comment]
Intended

**Comment by Sligneris** [comment]
I'm not sure if it should be - given that it's completely different to what people are used to when playing as humanoids.

**Comment by Repukan** [comment]
@Cyberboss this is intended, pls close

**Comment by Slignerd** [comment]
Humanoids now also can't use double ctrl for aggressive grab, so this issue seems to be resolvesd
