### ISSUE TITLE
My insane pipe dream

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#25073]
https://tgstation13.org/phpBB/viewtopic.php?f=9&t=10105&view=unread&sid=5eb9c4bcdb7a319bfe73a111c8fab6d1#p266575

I would like to try and attempt developing this. I'm not going to do it if the people who can actually code aren't willing to try it and support it though. I realize not physically being in space is seemingly a pretty big departure though so I understand if people are uneasy.

The end goal would be to make this the standard after committing the parts piecemeal to /tg/ and testing it over time , because side projects never live for very long. There is a pretty significant (by our standards anyway) list of contributors who are willing to code/sprite/map for this as well.

Anyway if you have any questions/concerns let me know, if you think it's terrible please also let me know before I start wasting time on it.

**Comment by KorPhaeron** [comment]
@tgstation/commit-access @MrStonedOne

**Comment by tgstation-server** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by ChangelingRain** [comment]
I'll deal with clockcult balance on this if you do it and maybe, like, help with some projects

**Comment by WJohn** [comment]
I'll contribute sprites if you can start pushing us in any real direction with this, I guess. Mapping too, if I can get off my lazy ass.

**Comment by Dorsisdwarf** [comment]
I might actually contribute some sprites for this because it's interesting.

I still feel like we should have space in the game though. Maybe R&D can build a shuttle that launches to space?

**Comment by KorPhaeron** [comment]
@Dorsisdwarf 

The idea that @AnturK and I came up with was going into orbit to poke around a debris field.

So we'd have space Z over jungle Z over lavaland Z

**Comment by ChangelingRain** [comment]
Maybe not jungle, but, like, the watery ash planet stuff ausops did might be good, because it can be pretty lush. Maybe huge mushroom trees or something.

**Comment by Jordie0608** [comment]
Am ambivalent; This sounds cool but I'm not a huge fan of leaving behind most of the "Space" part of "Space Station 13". We'll have to see how this goes.

**Comment by duncathan** [comment]
the title of this issue baited me into thinking it was atmos and I'm upset about it

**Comment by KorPhaeron** [comment]
We have a project for this (also its never happening)

**Comment by duncathan** [comment]
I got baited again FML

**Comment by KorPhaeron** [comment]
Dont worry Okand is making the map now and she made omega and delta so she has an actual track record on producing stations

**Comment by Cyberboss** [comment]
If I'm not giving up hope on Y.A.L.P.E.R. you're not allowed to give up on this!
