### ISSUE TITLE
Delta station telecomms air mixing.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#25088]
![](http://i.imgur.com/V21LiCl.png)

The telecomms chamber on delta station is 80* K, and the areas outside it are 293* K. They are separated by mini fans to prevent air mixing and supposedly intensive atmos processing as those mix pretty much forever.

Unfortunately, the air under the door immediately AFTER the mini fans is still 293* K, so there will still be air mixing if you open them.

The solution is just to use the 80* K tiles under those doors instead. It's as simple as making them your active selection, and replacing the ones under the door.

**Comment by Tofa01** [comment]
I'll do this now, but is this about both omega and delta or just delta because your title says omega.

**Comment by WJohn** [comment]
oh whoops, meant delta

**Comment by Tofa01** [comment]
Telecomms is not cooled at all on omega so ill have to add that in another PR because it would require extending and moving some stuff.

**Comment by WJohn** [comment]
It's not even necessary for comms to be cooled, but if you want to you can do it.

**Comment by Tofa01** [comment]
Meh ill do it anyway to be consistent with other maps, its something i can do map issues have been slow recently.

**Comment by Poojawa** [comment]
Ahaha, I knew I was going to miss something. My apologies.
