### ISSUE TITLE
Invincible Windows

### ISSUE THREAD

**Issue by Repukan** [tgstation/tgstation#25085]
I did three tests today with Windows on station.

1. Can't attack windows at all as a normal human
2. Can't attack windows as a simple animal (xenobio monster for example.)
3. Shooting a window with a proto ka broke the grill underneath first, then took a long number of hits (this was in low lavaland pressure) to break. The message for the window being hit did not appear for me, but it did show cracks and damage the more I shot at it.

**Comment by WJohn** [comment]
A normal functioning window has a path of /obj/structure/window/reinforced/fulltile
It's likely that the window you were trying to hit stopped at reinforced, they're not hittable like that, I don't think.

What map has this happened on? I cleaned up a few of these error windows on metastation last seen in https://github.com/tgstation/tgstation/issues/21887

**Comment by optimumtact** [comment]
@AnturK

**Comment by Repukan** [comment]
Box station in xenobio and human examples, Delta on grille being destroyed first in lavaland.

**Comment by WJohn** [comment]
I can't find irregular windows on box station's xenobio. Maybe it's something else then. Can you think of anything that occured to you or the windows that might affect being able to hit them? (Losing a limb, maybe some help intent with a tool, I don't know).

I tried hitting them as a human and as a simple animal in xenobio, it worked fine. Cannot reproduce right now.

**Comment by Repukan** [comment]
I'll update as soon as I can take screenshots since I think I will not be able to pinpoint the exact locations in words.

**Comment by AnturK** [comment]
You sure it wasn't simply done when the fix wasn't testmerged

**Comment by BeeSting12** [comment]
Related to #25013?

**Comment by coiax** [comment]
There were unclickable windows for a while, maybe this is related?

**Comment by kevinz000** [comment]
fixed i believe not 100% sure

**Comment by AnturK** [comment]
If you can reproduce open new issue.
