### ISSUE TITLE
A lot of deltastation's warning lines used to be double warning lines

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#25083]
Delta's warning lines are super fucked and a lot of them used to be doubles but antur's decals didn't account for that and I didn't catch it so I guess somebody is going to have to fix those manually

**Comment by Okand37** [comment]
The issue also effects centcom since I used the same warning lines for under doors too.

**Comment by AnturK** [comment]
Hmm, weird this was in the repath script

**Comment by Penguaro** [comment]
@ChangelingRain I can likely work on this. Do you know a commit when this wasn't a problem so I can compare what it should look like?

**Comment by Penguaro** [comment]
Or even a rough time frame when this was okay, like two months ago?

**Comment by Mark9013100** [comment]
@ChangelingRain If there's a map of delta station before the line changes I can try and fix them.

**Comment by ChangelingRain** [comment]
Map of delta before warning line changes; https://github.com/tgstation/tgstation/blob/c5a9a8e16e50a53c808082f623d163db164f3e27/_maps/map_files/Deltastation/DeltaStation2.dmm

**Comment by Mark9013100** [comment]
I'll take a look at it and see what I can do.
