### ISSUE TITLE
Arrival shuttle should not knock you down when transiting.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#25092]
@Cyberboss the arrival shuttle should be a special case where it doesn't knock you down if it arrives/departs, it serves no purpose other than to create instances where players can be robbed/attacked while stunned. Granted, that's spawnkilling, but it isn't helping anyone to have it here.

**Comment by jughu** [comment]
If somoene manages to strip you while a shuttle transit stun thrn good job i guess? Since that one is pretty short

**Comment by lzimann** [comment]
You already spawn buckled in, this is not really an issue.

**Comment by WJohn** [comment]
Someone pointed out that the shuttle would depart immediately as soon as they unbuckled. I'm just relaying the issue they had.

**Comment by Cyberboss** [comment]
That is definitely not the case, the shuttle will only depart with people on it if there is a new player waiting to spawn. Otherwise, it stays docked until all living clientmobs leave it.

**Comment by lzimann** [comment]
Not a bug and making this shuttle not knock you down would be inconsistent with every other.
