### ISSUE TITLE
Grape Soda

### ISSUE THREAD

**Issue by DanteRU0312** [tgstation/tgstation#25096]
Maybe i'm just misunderstanding something, but glass of grape soda doesn't look like anything special and it's called glass of what.
![default](https://cloud.githubusercontent.com/assets/25978025/23912308/11b33158-0901-11e7-94bf-71df8c8721bc.png)

**Comment by XDTM** [comment]
When you use the wrong type of glass it doesn't name it properly

**Comment by ExcessiveUseOfCobblestone** [comment]
That's why the unique_rename is on it so you can rename it [opens up the ability to poison drinks, etc.]

**Comment by ExcessiveUseOfCobblestone** [comment]
I'll have a fix for this soon [tm]
