### ISSUE TITLE
Lights getting bugged due to foamed metal

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#25127]
Foamed metal irreversibly fucks over lighting on its tiles making them permanently dark.

**Comment by WJohn** [comment]
Is this what it looks like? I brought it up in #24779 and didn't know specifically where it came from. I need to test this later. This could also just have been admins messing with lights, but I didn't check if they were var-edited at the time.

![](http://i.imgur.com/yxW8O4E.png)

**Comment by AnturK** [comment]
Cmon, i reported this on the original PR, i assumed pjb fixed this
