### ISSUE TITLE
After deselecting a certain law, all the laws after are not said.

### ISSUE THREAD

**Issue by SamSamsonthe3rd** [tgstation/tgstation#25128]
e7b9af73eac5d870eeeb82ffadeb3edaa26acffa

I received a total of 6 laws as an AI, with the fourth being a "do not state". However, after deselecting the fourth and stating my laws, 5 and 6 were not stated, only 1, 2, and 3.

**Comment by Tungul** [comment]
I was not able to reproduce this on a server running commit 742fcf0ffea1012ef7906222695461b85b7f9396. My hunch is that this bug was introduced at a later date - I'll cherry-pick to find it.

**Comment by Tungul** [comment]
I am not able to reproduce this bug in a clean be36e4b964e1ccc5beaf24cedf768d93cb993e11 build. I'll try e7b9af7 specifically.
