### ISSUE TITLE
Table stuck to box of crayons

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#25124]
Guy in perma points out a crayon box that has a table sprite attached to it. Quote from discover "...it was just like that. Picked up the crayons and the crayon box was just the whole sprite, table and all. "
See pictures:

https://puu.sh/uJeW5/17eb3e9d1f.jpg
https://i.gyazo.com/efe50d547143c9b7f57f0e338e8b4c4f.mp4

Server revision compiled on: 2017-03-15
70d9391b13a47666c74687c3cb1fcd3856c016d6 
Current Infomational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
Enforce Continuous Rounds: 10 of 21 roundtypes
Allow Midround Antagonists: 7 of 21 roundtypes
All Game Mode Odds:
blob 3.4%
traitorchan 20.7%
double_agents 12.1%
traitor 15.5%
clockwork_cult 6.9%
cult 6.9%
extended 1.7%
nuclear 13.8%
revolution 10.3%
wizard 8.6%

**Comment by MMMiracles** [comment]
This happens whenever a map maker has two turfs on-top of each other in dream maker with an item on-top of it.

![turf](https://cloud.githubusercontent.com/assets/9276171/23930835/2ce3f7c4-0905-11e7-8aa8-b6cc4d314637.png)

I ran into this issue when making away missions (when it was still relevant) and made an issue report, don't think anything came of it.

**Comment by peoplearestrange** [comment]
It was on one of the newer maps. I forget which one right now, should have checked at the time. Ill figure it out and write back.

**Comment by PKPenguin321** [comment]
I saw this, I think it was delta. The map with security east, cargo north.

**Comment by Tofa01** [comment]
Woah that is pretty weird, wonder how that happened, ill check it out now.

**Comment by WJohn** [comment]
what the hell??? how did this happen?

**Comment by RemieRichards** [comment]
If this happens again, please check if the object/item has the mystery sprite as an overlay.
I suspect our implementation of turf stacking (which takes all the turfs and makes them an overlay of the lowest turf) is getting something wrong.

**Comment by peoplearestrange** [comment]
@RemieRichards I think it had its standard sprite (the box of crayons) see the picture I included, has the Icon VV searched for.
