### ISSUE TITLE
Materials dispensed from the ORM can't be used for construction

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#25120]
It's impossible to open the construction interface of material stacks dispensed from the ORM.

**Comment by SgtxRootbeer** [comment]
Try swapping hands first. That worked for me...

**Comment by Sligneris** [comment]
I'm pretty sure I had metal in the active hand.

**Comment by lzimann** [comment]
This was fixed with #25181. The ORM was creating a stack with a bad argument name, not applying any of the construction recipes.

**Comment by lzimann** [comment]
Actually this is still happening, althought it will be fixed by #25224
