### ISSUE TITLE
Mime's finger gun still only fires a single bullet despite changelog saying 3.

### ISSUE THREAD

**Issue by Daundra** [tgstation/tgstation#25138]
Recently played a round as a mime traitor and bought the advanced mimery series. 

The most recent changelog that popped up said that the finger guns fire 3 bullets at once now, however, they seem to still be only firing one. Unless all 3 are overlapping eachother, or I'm not firing it right, it seems to be incorrect or just not merged yet or something.

I hope this is the right string of numbers and letters for the compile version the server is using:
acb141bf7129267f21e9b4724bf11bac1e436130

**Comment by KorPhaeron** [comment]
@TrustyGun

**Comment by XDTM** [comment]
@UnTrustyGun

**Comment by kevinz000** [comment]
Not him. My projectile spells broke again.

**Comment by kriskog** [comment]
Can't reproduce, you can fire three bullets every time you activate guns.
