### ISSUE TITLE
Wizards cant spawn

### ISSUE THREAD

**Issue by rainbowjose** [tgstation/tgstation#25147]
The screen centered to a shuttle

![b092a67b96 1](https://cloud.githubusercontent.com/assets/6819554/23972064/7b701da0-09e1-11e7-98e0-ff7db1b44570.png)

**Comment by PKPenguin321** [comment]
Type cancel-camera-view as a temporary fix.

**Comment by Cyberboss** [comment]
@PKPenguin321 do you know why that works?

**Comment by PKPenguin321** [comment]
No, just that 99% of bugs that involve seeing where your character isn't is fixed by that.

**Comment by Cyberboss** [comment]
Hmm, ignore my fix then, I don't know why it's happening

**Comment by Jordie0608** [comment]
@Cyberboss It seems like you never PR'd that last commit as a fix, did it not work?

**Comment by Cyberboss** [comment]
Another maintainer asked me to find the root cause

**Comment by ShizCalev** [comment]
Still an issue?
