### ISSUE TITLE
When a shuttle is hijacked and has holes in it, space follows too

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#25145]
Terrible title so let me explain, if you for example bombed the shuttle and then hijacked it when it lands it would replace the landing zone with space instead of landing pad or just snow

**Comment by Cyberboss** [comment]
That... shouldn't happen...

**Comment by Armhulen** [comment]
Oh, i'm glad that it is a bug then, I just keep posting shitty consistency issues.

**Comment by Penguaro** [comment]
This may be related to #24826.

**Comment by Cyberboss** [comment]
@lzimann This was fixed
