### ISSUE TITLE
Chasms not smoothing properly

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#25140]
I believe it was tendril created one.

![dreamseeker_2017-03-15_18-43-34](https://cloud.githubusercontent.com/assets/4047233/23962738/5e8badf8-09af-11e7-9c38-ec67a8b1f79b.png)

**Comment by KorPhaeron** [comment]
@Cyberboss because I can't think of anyone else at all who touches systems that would impact smoothing

**Comment by Cyberboss** [comment]
I disrespectfully disagree

**Comment by XDTM** [comment]
Could have something to do with Initialize over New though

**Comment by xxalpha** [comment]
Yeah that's probably the cause

**Comment by Iamgoofball** [comment]
![dreamseeker_2017-03-19_09-37-18](https://cloud.githubusercontent.com/assets/4081722/24082754/cc585824-0c87-11e7-9adb-1ccae7b23ab7.png)

**Comment by Iamgoofball** [comment]
it's tendrils I thik

**Comment by PKPenguin321** [comment]
The thing in the OP happens with adminspawned chasms as well

**Comment by Iamgoofball** [comment]
But those in my picture ARE adminspawned chasms

**Comment by PKPenguin321** [comment]
Weird, I adminspawned some on lavaland and they didn't smooth maybe one or two days ago

**Comment by Iamgoofball** [comment]
Weird
