### ISSUE TITLE
Chaplain's arrhythmic knife is busted

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#25162]
It's supposed to make you alternate between fast and slow but instead you go SUPER TURBO FASTER THAN I THOUGHT WAS POSSIBLE all the time

**Comment by KorPhaeron** [comment]
@coiax

**Comment by coiax** [comment]
Flag changes shouldn't have caused any behavioural changes. Let me check if it was present before I did my changes.

**Comment by KorPhaeron** [comment]
Couldn't reproduce

**Comment by PKPenguin321** [comment]
Hmm. Will ping this if I see this happen again.
