### ISSUE TITLE
Shadow people created via shadow mutation toxin do not have nightvision.

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#25163]
Shadow people created via shadow mutation toxin do not have nightvision.

**Comment by Armhulen** [comment]
BUFFSHADOWPEOPLE

**Comment by golfer45** [comment]
not a buff cheack the shadowperson code they are supposed to have nightvision

**Comment by Armhulen** [comment]
I know, but shadowpeople SUCK.
