### ISSUE TITLE
Areas that don't need lights are dark

### ISSUE THREAD

**Issue by Thunder12345** [tgstation/tgstation#25164]
![moon colony phi 2017-03-16 122507](https://cloud.githubusercontent.com/assets/5479091/23996036/ed54d76e-0a43-11e7-8576-9cbb05cddade.png)

**Comment by Sligneris** [comment]
wait, how is that an issue

**Comment by Cyberboss** [comment]
Spacelight should be lighting it

**Comment by MrStonedOne** [comment]
No, re-read

Areas with lighting disabled are dark rather then full brite.

it seems to be a plane master issue

@MrPerson

**Comment by XDTM** [comment]
That's some spooky space though, it could be a feature for cult or shadowling wins

**Comment by MrPerson** [comment]
Yeah maybe another day, if somebody wants to implement that, ask me and I'll show you how.

**Comment by Sligneris** [comment]
Still not truly fixed - any breaches created by explosives are still pitch black.
