### ISSUE TITLE
Ore refiner can't be used to refine titanium and plastitanium

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#25166]
While ORM is now the main way of refining ores, the old ore refiners still exist you know?

Ore refiners at the mining outpost and labor camp ignore titanium ores.

**Comment by Kromgar** [comment]
No one will touch that code

**Comment by lzimann** [comment]
Watch me

**Comment by ExcessiveUseOfCobblestone** [comment]
I hope he touches it by removing them :^)

**Comment by lzimann** [comment]
I plan to just replace the refiner with ORM soon, it will make life easier to everyone.

**Comment by jughu** [comment]
Dont touch NOSTELGIA

**Comment by Profakos** [comment]
As a madman, I am cleaning up this code, and this one's code is quite terrifying. I'll probably have to rewrite it by merging all those vars into a single flag check, to keep the most important functionality: wasting ore to smelt into slag....
