### ISSUE TITLE
Neurotoxin spit hits user if running in same direction as spit

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#25193]
Neurotoxin spit hits user if running foward. Happens if you implant a spit gland into a human

**Comment by GunHog** [comment]
It could be a situation of you outrunning your own projectile!

**Comment by BeeSting12** [comment]
Happens with fireballs unless it was changed since last time I was wizard.

**Comment by MrStonedOne** [comment]
I should port the momentum transfer i made for throwing objects over to projectiles.
