### ISSUE TITLE
Space is completely white

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#25199]
Well, currently when I took at space, well, it is completely white.

![ss13 space bug](https://cloud.githubusercontent.com/assets/4686269/24051206/13c86c5c-0b3a-11e7-8916-90d7d67fba8f.png)

**Comment by Cyberboss** [comment]
@MrPerson Ya botched it again!

**Comment by lzimann** [comment]
The issue is still with parallax. Althought turning it on and then turning off fixes it.

**Comment by MrPerson** [comment]
Did you have parallax on or off when you originally spawned?

**Comment by MrPerson** [comment]
nvm I figured it out
