### ISSUE TITLE
Unary vents set to "internal" pressure mode always vent no matter what they are set to.

### ISSUE THREAD

**Issue by SgtxRootbeer** [tgstation/tgstation#25209]
A few days ago, I designed a sm engine that used plasma as a coolant, but I noticed that eventually it would clog if the engine ran too long. To fix that issue, I designed and installed a governor, mainly a small 1x1 room with a vent and 3 scrubbers in it. I installed it into the cooling line (on the side, so if the vent was turned off, it wouldn't stop the cooling system) and set the vent to internal pressure of 300. Despite the pipes pressure being 100, the vent still vented gasses, almost causing a delamination.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'll probably have a fix for this soon [tm] @SgtxRootbeer

**Comment by ExcessiveUseOfCobblestone** [comment]
Okay so I'm pretty sure it is because nowhere in the airalarm machinery does it send the `set_internal_pressure` signal. I don't know how to mess with the UI so I'm not sure how to add a button that sets the internal pressure check, but I am almost certain that's the issue.

**Comment by octareenroon91** [comment]
why not a passive gate though?

**Comment by SgtxRootbeer** [comment]
For what? My governor? A passive gate is like a pressure pump except it doesn't require an APC, and moves gasses via differences in pressure.

**Comment by octareenroon91** [comment]
1. It requires power at present
2. If you're trying to set a max pressure in a line, a passive gate might do.

````
/obj/machinery/atmospherics/components/binary/passive_gate/process_atmos()
        ..()
        if(!on)
                return 0

        var/datum/gas_mixture/air1 = AIR1
        var/datum/gas_mixture/air2 = AIR2

        var/output_starting_pressure = air2.return_pressure()
        var/input_starting_pressure = air1.return_pressure()

        if(output_starting_pressure >= min(target_pressure,input_starting_pressure-10))
                //No need to pump gas if target is already reached or input pressure is too low
                //Need at least 10 KPa difference to overcome friction in the mechanism
                return 1

        //Calculate necessary moles to transfer using PV = nRT
        if((air1.total_moles() > 0) && (air1.temperature>0))
                var/pressure_delta = min(target_pressure - output_starting_pressure, (input_starting_pressure - output_starting_pressure)/2)
                //Can not have a pressure delta that would cause output_pressure > input_pressure

                var/transfer_moles = pressure_delta*air2.volume/(air1.temperature * R_IDEAL_GAS_EQUATION)

                //Actually transfer the gas
                var/datum/gas_mixture/removed = air1.remove(transfer_moles)
                air2.merge(removed)

                update_parents()

````

**Comment by SgtxRootbeer** [comment]
yes, i can, by having a destination loop set at say... 290kpa, and constantly filtering out gas from it, however, that would be more complicated and runs the risk of the gas changing volume due to temp fluctuation affecting the coolant in the main line.

**Comment by ExcessiveUseOfCobblestone** [comment]
While that might be another option, that's no excuse for the bug to be present.

**Comment by octareenroon91** [comment]
agreed

**Comment by duncathan** [comment]
will investigate

**Comment by PKPenguin321** [comment]
?

**Comment by SgtxRootbeer** [comment]
Nice.

**Comment by duncathan** [comment]
#28557
