### ISSUE TITLE
Random reagent selection is terrible

### ISSUE THREAD

**Issue by octareenroon91** [tgstation/tgstation#25207]
As it stands, `get_random_reagent_id()` in `code/modules/reagents/chemistry/holder.dm`  includes
 * all consumables; 
 * all alcohols;
 * all the species mutation toxins (most notably including plasmaman mutation toxin);
 * yes **clf3**.

Very little is actually blacklisted with `can_synth = 0`.

**Comment by Iamgoofball** [comment]
this is intentional

can_synth is only for things that aren't supposed to be obtainable by normal play

stop making issue reports to get my events PR nerfed

**Comment by Cyberboss** [comment]
Solution is to get rid of can_synth and instead, in SSatoms initialization, run through all reagent recipes and build a list of ones that can be synthd

**Comment by Cyberboss** [comment]
also who the fuck cares if get_random_reagent_id include clf3. Don't bring politics into my issue tracker REE!

**Comment by Iamgoofball** [comment]
what he said

**Comment by octareenroon91** [comment]
Excuse me if I find 20% consumable + 20% booze a little less than thrilling. In any case, I only found the function in use with randomized bees.

````
[byond@server1 code]$ git grep -E "^/datum/reagent/[^)(]*$"|wc -l
407
[byond@server1 code]$ git grep -E "^/datum/reagent/[^)(]*$"| grep consumable|wc -l
162
[byond@server1 code]$ git grep -E "^/datum/reagent/[^)(]*$"| grep ethanol|wc -l
83
````

**Comment by Iamgoofball** [comment]
That's still 60% legit chems

**Comment by ShadowDeath6** [comment]
I thought can_synth was intended for odysseus mech chem synthesizer

**Comment by Iamgoofball** [comment]
Yes but it also applies to any chem we want to ensure doesn't show up

**Comment by lzimann** [comment]
This is not a bug.
