### ISSUE TITLE
Arrivals shuttle cockpit grilles are smiling tables

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#25217]
![obraz](https://cloud.githubusercontent.com/assets/12747768/24063047/56dc1588-0b5e-11e7-922a-6a1914ca458a.png)

**Comment by Armhulen** [comment]
everything is ok :)

**Comment by Penguaro** [comment]
This was added to help new players feel at ease if spawned in the smaller room of the shuttle...

**Comment by Armhulen** [comment]
relax :)

**Comment by Repukan** [comment]
Feature

**Comment by Penguaro** [comment]
@Cheridan This issue can be closed.

**Comment by Penguaro** [comment]
@AnturK This issue can be closed.
