### ISSUE TITLE
Atmospheric hardsuits are not immune to Freon gas

### ISSUE THREAD

**Issue by swagbringer** [tgstation/tgstation#25239]
As above
![freon](https://cloud.githubusercontent.com/assets/26507545/24073912/27d3e178-0bf7-11e7-81b7-e4ff95f9cabd.png)

Im not sure why this is occuring, I wasnt able to test it with other hardsuits, but earlier in the day I saw one person using the medical hardsuit and walking around fine in it.

It could possibly be due to wearing a gasmask instead of a breath mask?

**Comment by ExcessiveUseOfCobblestone** [comment]
If they don't have internals on the suit is useless.

**Comment by swagbringer** [comment]
I did have interals on, I am absolutely certain.

**Comment by uraniummeltdown** [comment]
This also happened to me, you still freeze in an atmos hardsuit

**Comment by lzimann** [comment]
Dupe of #20371
