### ISSUE TITLE
Bluespace Shelter Capsules deleting rocks on lavaland create space tiles

### ISSUE THREAD

**Issue by Rosello6** [tgstation/tgstation#25231]
See title. I used a bluespace shelter capsule without all the tiles cleared of rocks and the corner pieces have space tiles under them. I'm pretty sure this didn't happen before.

![](http://i.imgur.com/3pA0YKs.png)

**Comment by KorPhaeron** [comment]
@Cyberboss I'm just going to keep pinging you in these because I don't know anyone else who would fix it

**Comment by Cyberboss** [comment]
The problem is when the bluespace capsule map template is loaded, it overwrites the baseturf of the turf, changing it to space. Seems like an easy fix, I'll do it later

**Comment by KorPhaeron** [comment]
Weird, it wasn't doing that previously

**Comment by coiax** [comment]
@KorPhaeron well, originally, bluespace shelters used hardcoded item and turf placement, and I switched it to a template?

**Comment by KorPhaeron** [comment]
@coiax 

It worked for a long time as a template @Cyberboss says @PJB3005 broke it with lighting somehow

**Comment by coiax** [comment]
Speaking of, @KorPhaeron, when are you going to make a new Bluespace Shelter template.

**Comment by KorPhaeron** [comment]
No, why?

**Comment by coiax** [comment]
You should.

**Comment by KorPhaeron** [comment]
What is wrong with the current one?

**Comment by coiax** [comment]
Nothing. But you should make a luxury shelter available for purchase or something.

**Comment by PJB3005** [comment]
Unless I fucked up the changeTurf override somehow, no way this can be lighting.

That or there's a runtime causing a proc to abort midway due to a catch.

**Comment by Cyberboss** [comment]
It happened in the first 4 commits of vg lights

That's as specific as i can get, because none of them compile
