### ISSUE TITLE
AIs uploaded into mechs and then downloaded back into a core retain the mech's action buttons

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#25258]
And the ability to interact with the mech with said buttons.

Ask the tormented robo Tam Lin about the constant ejecting whenever he got in.

**Comment by GunHog** [comment]
Reproduction steps, please.

**Comment by Anonmare** [comment]
Step 1: Make AI
Step 2: Put AI in intellicard
Step 3: Put Intellicard in mech
Step 4: Take Ai from mech into intellicard
Step 5: Put Ai back in its core
Step 6: Profit

**Comment by GunHog** [comment]
Oh, you said "core", not "card". You really need to be specific in your reports!

**Comment by GunHog** [comment]
This is fixed, I forgot to put the "Fixes <PR#>" thing in the right place.
