### ISSUE TITLE
Toolbelts stuck on beltslot, can't access or take them off

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#25259]
Essentially the title. Had this happen at about 8:00 pm EST, 3/18/17, and an hour or two before that. PKPenguin helped me fix it the second time so he might be able to give more information about it.

**Comment by BeeSting12** [comment]
Apparently taking your jumpsuit fixes it. Still an issue.

**Comment by PKPenguin321** [comment]
had @optimumtact spectate this ingame and apparently two different players were wearing the same belt at once which led to issues. not sure how they managed it

**Comment by BeeSting12** [comment]
oh, its possible we both managed to take it at the same time at primary tool storage, y'know how everyone races to get it roundstart. this could've caused a duplication glitch.

**Comment by optimumtact** [comment]
That's my best guess, you both raced to pick it up and there was a race condition and you both ended up with it in hand and on your belt.

Then I think whenever one of you had it open the other couldn't interact with it.

**Comment by Iamgoofball** [comment]
Good shit

**Comment by Cyberboss** [comment]
Fucking byond, you're supposed to save us from this shit

**Comment by optimumtact** [comment]
It will be a missing loc check during the handling somewhere.

**Comment by bgobandit** [comment]
This happened with the captain's spare ID when the HoS and clown picked it up at the same time.

The implications of this should speak for the priority of this bug

**Comment by PKPenguin321** [comment]
should be closed in favor of https://github.com/tgstation/tgstation/issues/25814

**Comment by PKPenguin321** [comment]
ahem close this
