### ISSUE TITLE
The syndicate borg request remote can spam deadchat with ghost popup messages

### ISSUE THREAD

**Issue by harmonyn** [tgstation/tgstation#25254]
It also doesn't give feedback to the user, so someone can easily accidentally spam deadchat.

**Comment by Armhulen** [comment]
>accident

hehehe

**Comment by PKPenguin321** [comment]
same for the reinforcements nuke ops item

**Comment by ShadowDeath6** [comment]
slaughter demon vial has something preventing this, should be an easy fix since they work the same way

**Comment by ExcessiveUseOfCobblestone** [comment]
same for just about every device that works like these.

**Comment by Bawhoppen** [comment]
Fix: Ban people who do that

**Comment by ShizCalev** [comment]
fixed a while ago
