### ISSUE TITLE
Eating a lightly-fried mouse creates a non-fried dead mouse at your feet.

### ISSUE THREAD

**Issue by Tungul** [tgstation/tgstation#25269]
Commit: 742fcf0ffea1012ef7906222695461b85b7f9396
I tested (and discovered) this on a local server.

1. Locate a mouse
2. Kill and grab mouse
3. Place dead mouse in deep fryer
4. Remove fairly quickly so it is lightly-fried
5. When set to help intent, click self to eat mouse
6. Observe dead mouse on floor
7. Grab mouse and goto 3 -> infinite nutriment

Let me know if you need anything else.

**Comment by PKPenguin321** [comment]
This is true for any non-food object. Not a bug

**Comment by Tungul** [comment]
My bad - wasn't aware that was the case.

Thanks.
