### ISSUE TITLE
Delta station broken map sprites

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#25271]
![f](https://puu.sh/uPyy3/98fc8023be.jpg)

**Comment by lombardo2** [comment]
I've seen that. Thought It was a problem with my client. Weird.

**Comment by Tofa01** [comment]
Huh weird this is more then broken sprites, it appears from the screen shot that everything on the tile was evaporated as you can see the floor tiles and fire door are missing, very weird looking into this now.

**Comment by Tofa01** [comment]
If this is seen anywhere else let me know please.

**Comment by AnturK** [comment]
Should be fixed already in #25243

**Comment by Shadowlight213** [comment]
@Tofa01 The firedoor is actually still there, just hidden.
Also both the turf and the door are named "WARNING: PRESSURE DOOR" or something like that
