### ISSUE TITLE
Holoparasite can't manifest if user turns into ash drake, ghosts the holo upon user rehumanizing

### ISSUE THREAD

**Issue by jimmstar** [tgstation/tgstation#25287]
This issue occurred as a support holoparasite on healing mode. Apparently the user had no idea that the holo was ghosted, either.

**Comment by Repukan** [comment]
Can confirm, was drake

**Comment by PKPenguin321** [comment]
I'd imagine this happens with anything that transforms you into a non-human, like the xeno or borg nanites or the borging machine

**Comment by ChangelingRain** [comment]
Uuuuugh. This happens because holos manifest at user.loc, to at least discourage some abuse cases, like having a holo in a mech/locker/etc

**Comment by InsaneHyena** [comment]
Also happens if you're a changeling, and you monkey yourself.

**Comment by timothymtorres** [comment]
Duplicate of #59127

**Comment by timothymtorres** [comment]
> Also happens if you're a changeling, and you monkey yourself.

Anykind of polymorph spell, ability, or effect all have different procs they use to transform, which is really really bad.
