### ISSUE TITLE
Drones can't weld airlocks

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#25292]
Recent changes require harm intent to weld airlocks, this makes repairing an emagged airlock not possible by simple mobs.

**Comment by RemieRichards** [comment]
they can use the verb.
but yes, simples need a hud element for intent.

**Comment by MimicFaux** [comment]
That's something at least. Although, I'm not seeing where that verb is/what is typed to use it.

**Comment by octareenroon91** [comment]
there's a hidden, raw verb or proc, `a-intent`

**Comment by octareenroon91** [comment]
From code/modules/mob/mob_helpers.dm :
````
/mob/verb/a_intent_change(input as text)
        set name = "a-intent"
        set hidden = 1
````

**Comment by octareenroon91** [comment]
However, the **default choice of intents is a null list**.
`mob_defines.dm: var/list/possible_a_intents = null//Living`
Only carbons and silicons are assigned choice of intent.
