### ISSUE TITLE
Ventcrawl vision isn't rendering right.

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#25299]
![image](https://cloud.githubusercontent.com/assets/4176358/24087108/fd0fcbe6-0cf0-11e7-9b4e-b4aa5acea440.png)

You get the pipes, but the meson vision doesn't appear. Putting the cursor over the darkness reveals the turfs as if it were there however.

Only turfs that properly display are space tiles and for some reason the holodeck.

**Comment by ChangelingRain** [comment]
Hmm. I think you're losing the lighting objects, but not the lighting plane, possibly.

**Comment by Jalleo** [comment]
@MrPerson possibly?

**Comment by MrPerson** [comment]
tbh I actually really really like how this looks

Without testing, Joan probably has this right.

**Comment by kriskog** [comment]
You get meson vision now, this shouldn't be happening.
