### ISSUE TITLE
Items fall to the ground but leave a sprite in your hand/bag

### ISSUE THREAD

**Issue by fizbump** [tgstation/tgstation#25305]
[Note]: # 29f47c8b6bf7d96303ef527a053eac0b70edba84 

Issue: When attempting to put items into a bag, the item falls to the ground but leaves a sprite in your hand or bag. Picking the item up temporarily fixed it for me, but another player reported that picking up the items would just make them drop again while leaving the sprite in his hands. 
In some cases, the item sprite would remain in the screen position where it was dropped, and would stay in that position as I moved around, but could not be interacted with.
It's a weird bug and somewhat hard to explain but it's super annoying.

**Comment by optimumtact** [comment]
This appears to happen when there is no gravity @Cyberboss do you have any thoughts based on your overhaul of inventory procs?

**Comment by francinum** [comment]
It's likely related to the testmerged pr #25149

**Comment by AnturK** [comment]
Caused by testmerge.
