### ISSUE TITLE
Cant turn off disposal bins

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#25304]
The UI just does nothing

**Comment by Tokiko1** [comment]
To add to this: It works fine if the bin is not at 100% power.

**Comment by Cyberboss** [comment]
Uhh, so are you saying you can flush a disposal bin at full charge but it won't recharge? That's not a bug. A disposals bin uses power to pressurize itself. When it's full, it can flush without power.

**Comment by PKPenguin321** [comment]
No, the button to disable flushing entirely (the power button) does not work.

**Comment by Cyberboss** [comment]
The flush function is a manual handle, if you want to shut off the pump and empty the pressure guage. You have to turn of the power and pull the handle (Like flushing a toilet with the water off)

**Comment by PKPenguin321** [comment]
no you shit im talking about THIS BUTTON RIGHT HERE
![REEE](https://puu.sh/uSk3g/63251426b0.png)
i know for a fact before tgui you could push it regardless of how full the pressure is

**Comment by Cyberboss** [comment]
Oh wow, some scrub made it so you can't turn the pump off if the pressure is maxed and it uses 1 var for like 7 states reee
