### ISSUE TITLE
Directional windows leaking air

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#25312]
Based off master commit:
4c1d9131a358225584d4feed4bd3bb94c2c7b376 

Built a section with floors and windows, mainly one sided/directional windows. All windows are screwed, double checked. Section is not assigned as a room. Air seems to leak from everywhere, made a shitty video of the situation.

https://youtu.be/ghs51fIaLEY

**Comment by Cyberboss** [comment]
@AnturK

**Comment by AnturK** [comment]
Hmm, doubt this is anything to do with Adjacency changes but i'll take a look.

**Comment by jughu** [comment]
Last time i had a 1 tile supermatter setup 4 directional windows and a vent freezing emitter shot into it supermatter made plasma plasma gone trough the window???

**Comment by Marflowerose** [comment]
As an update, I replaced the directional windows with full tiles and it was airtight.

**Comment by AnturK** [comment]
The issue is with windows built from glass stacks, they don't set their initial direction properly. In-game fix is to rotate them before using. I'll drop a proper fix later.

**Comment by AnturK** [comment]
Scratch that, 100% fault of #25149 @MrPerson  you forgot to readd window Move -> Moved.

**Comment by optimumtact** [comment]
directional windows should be completely removed

**Comment by duncathan** [comment]
I hate this bug because directional windows are fucking awful to work with/around

**Comment by optimumtact** [comment]
Directional windows should be completely removed
