### ISSUE TITLE
RCD Creates extra set of Airlock Electronics

### ISSUE THREAD

**Issue by Penguaro** [tgstation/tgstation#25319]
On Server revision compiled on: 2017-03-20
4c1d9131a358225584d4feed4bd3bb94c2c7b376 
No test merges present.

As an Engineering Cyborg and as a Station Engineer, I successfully created an airlock using the RCD, however, upon opening the airlock there are spare airlock electronics sitting on the ground.

**Comment by BeeSting12** [comment]
I think doing this on the auxiliary base console does this too.

**Comment by Penguaro** [comment]
@BeeSting12 tested and confirmed.
