### ISSUE TITLE
Cyborg RCD can't build airlocks

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#25314]
If you try to build an airlock as an engineering cyborg, the airlock doesn't appear at all.

**Comment by Penguaro** [comment]
Tested locally with current build and the airlock was created. A PR fixed this yesterday, when did you experience this and was the Server revision/test merge info? Otherwise #25289 has fixed this.

**Comment by Sligneris** [comment]
It was yesterday, so it might've been already fixed.

**Comment by Penguaro** [comment]
I'm going to say #25289 Fixed this but it did create another issue with duplicated electronics. I made a separate issue. When you have a moment, please test again.

**Comment by lzimann** [comment]
Should be fixed already, if it's not tell me and I'll reopen this.
