### ISSUE TITLE
Various Aux Base Console Problems

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#25315]
Happened last night, I'd assume these bugs are still a thing.
1: You can only build one airlock with the console. I'm assuming this is a bug but maybe not. You should be able to build four because there's also four tiny fans.

2: No way of getting back tiny fans and plasma turrets. Probably not a bug, but I still see it as an issue since you can misplace stuff or whatever.

3: Can't place glass on grilles. Maybe I'm dumb and was doing it wrong but I wasn't able to do it earlier.

**Comment by GunHog** [comment]
1 and 3 have been fixed. 2 is a different issue, however.

**Comment by BeeSting12** [comment]
Okay then, I'll close the issue since 2 is more of a feature request and the rest are fixed. Thanks gunhog
