### ISSUE TITLE
Removing pens from your PDA while it's in a container is EXTREMELY fucky

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#25328]
I'd love to describe it but I literally can't, i'll keep it at invisible pens for now

**Comment by Armhulen** [comment]
Just do some testing in the thunderdone, alt click to remove pen while it's in the backpack to reproduce

**Comment by Penguaro** [comment]
From what I can tell, the pen is placed on the same slot as the PDA so the PDA obscures its presence. If you move the PDA or items to the left of the PDAs position, the inventory will show the pen.

**Comment by Sligneris** [comment]
Many items are invisible recently when handled improperly in general - it's common with materials and floor tiles as well.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Cyberboss 
https://github.com/tgstation/tgstation/blob/14a7a856bbd3292ef150aa26f4be78e3c1287399/code/game/objects/items/devices/PDA/PDA.dm#L762

**Comment by Cyberboss** [comment]
THAT PROC DOES NOT EXIST WTF??

**Comment by Cyberboss** [comment]
@ExcessiveUseOfCobblestone Yeah, that's an older revision, what are you smoking?

**Comment by Cyberboss** [comment]
It's just using loc instead of get_turf

**Comment by ExcessiveUseOfCobblestone** [comment]
what the frick how did I get there
