### ISSUE TITLE
You can alt-click on adjacent tiles while ventcrawling to see what's there

### ISSUE THREAD

**Issue by JJRcop** [tgstation/tgstation#25339]
I was ventcrawling on 4c1d9131a358225584d4feed4bd3bb94c2c7b376, and I alt-clicked one of the tiles to see what would happen, and I could see everything on the tile!

I mean, that is expected, but you're not supposed to see ANYTHING when you're ventcrawling.

**Comment by ExcessiveUseOfCobblestone** [comment]
I know this is a bug but honestly if you're altclicking every tile to check what's there then props to you tbh.

**Comment by GunHog** [comment]
>I mean, that is expected, but you're not supposed to see ANYTHING when you're ventcrawling.

I believe that all ventcrawling mobs are meant to see turfs such that they can navigate properly, and mobs with material vision (drones) and thermal vision (Xenos) will be able to see additional things. Borers may be intended to have a vision advantage as well. 

No mob should be *completely* blind while ventcrawling.

**Comment by JJRcop** [comment]
I meant only seeing the turfs.

**Comment by timothymtorres** [comment]
I'm going to test this later to see if this is still a problem.
