### ISSUE TITLE
Can't freely ghost out while cloning

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#25338]
While your body is being generated in the cloning pod, you can't ghost out of it without giving up control of the mob entirely.

While the game does ghost you out shortly after the cloning starts, once you re-enter the body, you're pretty much trapped until the cloning is done.

**Comment by Sligneris** [comment]
Also, while the clone is being created, the cloning console simply does not detect the cloning pod's existence, making it impossible to check who is being cloned.

Related to #25230

**Comment by lzimann** [comment]
It ghosts you out after 10 secs, but not detecting seems like a bug. @coiax

**Comment by coiax** [comment]
I guess I never figured that people would want to reenter an unconscious cloning body, and then become bored and want to ghost out again.

**Comment by kriskog** [comment]
Detection is fixed, not being able to ghost again after manually entering your new body isn't really a bug.
