### ISSUE TITLE
you cannot make mummies out of medical gauze because gauze is only six in a stack

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#25363]
smh

**Comment by lzimann** [comment]
@XDTM

**Comment by XDTM** [comment]
:(

Would anyone mind if i raised the gauze's stack max to 10?

**Comment by Repukan** [comment]
Aren't they cloth golems?

Shouldn't it be cloth only?

Literally making this role too easy to gain immortality

**Comment by Armhulen** [comment]
If you can get cloth, you can get gauze

besides, cloth makes gauze
