### ISSUE TITLE
RCD tiles turn Lavaland tiles into space

### ISSUE THREAD

**Issue by Cirrial** [tgstation/tgstation#25361]
https://github.com/tgstation/tgstation/commit/37a325d8971f75136aae2c7f87c74b94ff12d9c9
Playing as an Ash Walker, picked up the RCD to remove a wall. Misclicked a few extra times. Suddenly, space. Fortunately, as ashwalker, suddenly venting what little air existed in the lair to space didn't affect much. Still seems like an oversight?

**Comment by optimumtact** [comment]
@Cyberboss you broke baseturfs when you changed maploading

**Comment by Sligneris** [comment]
On a related matter, whenever syndicate base gets blown up, it also leaves a hole to space.

**Comment by Cyberboss** [comment]
It's not lavaland tiles, it's tiles that were loaded by dmm_suite

**Comment by Cyberboss** [comment]
Dupe of #19954
