### ISSUE TITLE
Mining Drone AI upgrade is referred to as sentience potion

### ISSUE THREAD

**Issue by Mark9013100** [tgstation/tgstation#25370]
Server revision compiled on: 2017-03-21
37a325d8971f75136aae2c7f87c74b94ff12d9c9 

When using a mining drone AI upgrade on a minebot, it is referred to as a sentience potion.

Message: "You offer the sentience potion to the nanotrasen minebot..."

**Comment by ExcessiveUseOfCobblestone** [comment]
i'll fix this soon [tm]
