### ISSUE TITLE
medibots can STILL overdose you!

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#25409]
Goddamnit did we not fix this?

**Comment by GunHog** [comment]
This report is useless without reproduction steps, or at least conditions under which it happened.

**Comment by CPTANT** [comment]
You sure it wasn't hacked?

**Comment by GunHog** [comment]
Emagged/hacked Medibots inject the toxins chem, and only forgo checking OD when injecting this chem. I need more detail before I can proceed.

**Comment by jughu** [comment]
@gunhog its probaly medibots just injecting him on the same time like a stack medibots

**Comment by GunHog** [comment]
More information required. 
![image](https://cloud.githubusercontent.com/assets/4955510/24253179/93869906-0fad-11e7-93ed-4666b36ff365.png)

**Comment by ShadowDeath6** [comment]
Do they still do the thing where if you have multiple damage types they inject you with bicaridine, kelotane, and antitox ao it makes tricord then thinks you're taking more damage because you're ODing and it injects more of everything until you're dead?

**Comment by GunHog** [comment]
No, because medibots use charcoal as a tox fixer now. Also, they are coded to avoid injecting anything if tricord is in the patient's system.

Again, @kevinz000, your report is useless without reproduction steps.

**Comment by kevinz000** [comment]
Ok, I just read this and yeah I'm stupid for not realizing it but:
1. Got into fights as HOS, I always get into fights as HOS 
2. Get on shuttle, in low(red) health
3. there's 3 medibots around me
4. They all start trying to inject me
5. I move two of them around via ctrl+click to try to interrupt them incase they would overdose me
6. YOU FEEL LIKE YOU TOOK TOO MUCH OF BICARDINE!
7. Fuck
8. Run to cockpit before getting critted
9. People try to help me
10. Medibots come in. YOU FEEL LIKE YOU TOOK TOO MUCH OF KELOTENE!
11. YOU FEEL LIKE YOU TOOK TOO MUCH OF ANTI-TOXIN!
12. YOU FEEL LIKE YOU TOOK TOO MUCH OF TRICORDRAZINE!
13. I was in crit the entire time from right after I got OD'd on bicardine.

**Comment by GunHog** [comment]
This seems to be possible by you having antitoxin in your system, injected by an outside source (medibots inject charcoal). Medibots stop injecting you if they detect tricord already in you, but it is possible to mix enough of it to OD you in the first injection. 

Having them scan for antitoxin instead of tricordrazine may help, perhaps. The one chem that could have saved your life, charcoal, was not injected by the medibot due to it detecting tricordrazine.

**Comment by kevinz000** [comment]
That's pretty strange, I don't recall having any meds injected/eaten but I might be wrong, but what I know is three medibots followed me around and killed me :(

**Comment by jughu** [comment]
Dont forget people can put custom chems in medibots mekhi!

**Comment by Repukan** [comment]
>taking damage as HoS

Lmao get good

**Comment by Bawhoppen** [comment]
>mfw kekhi so unrobust he gets defeated by a medibot

**Comment by jughu** [comment]
An apple a day keeps me away.
