### ISSUE TITLE
You can't extract DNA sting other changelings?

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#25402]
If I extract DNA sting someone I don't get them on the transform list even after I've transformed to make more room for them. This is very bad and denied my greentext. I demand a replacement greentext

ORIGINAL CONTENT ABOVE ^^^
who the fuck thought that was a good idea

**Comment by PKPenguin321** [comment]
Lings are immune to stings and get a tiny prick message when stung, not a bug

**Comment by Armhulen** [comment]
>encouraging ling teamwork

come-on-now

**Comment by XDTM** [comment]
Consume them or ask for a dna channel

**Comment by BeeSting12** [comment]
if its not a bug then im closing this and whining on the forums about it
