### ISSUE TITLE
Flightpacks can fall off the flightsuit and bug out

### ISSUE THREAD

**Issue by StuAhpla** [tgstation/tgstation#25405]
I don't have a clue how to reproduce this but randomly my flight pack came off the suit and someone grabbed it, having it fuse to their character. We both had full flight but the person who grabbed the pack could control all the functions on it while the original user was permanently in the air.

Also the flightpack got stuck in my hand during this bug

**Comment by StuAhpla** [comment]
I forgot to bring this up but also the name of whoever is using the flightsuit is overridden by whoever has the flightpack:

IE when the person A in the flightsuit goes through a door or a person it will use person B's idenity instead

**Comment by kevinz000** [comment]
already fixed
