### ISSUE TITLE
When one item from a stack vanishes, the entire stack vanishes from sight

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#25418]
Usually the case with slime core extracts - when you inject a slime core stack with something, the entire stack vanishes from sight, while in reality only one core is removed in the reaction.

While you can see the stack again when you reopen the bag, it's honestly quite annoying.

**Comment by Kromgar** [comment]
This is in bio bags i assume

**Comment by Sligneris** [comment]
Same issue with trashbags, truth be told.

**Comment by Cyberboss** [comment]
i detect something not using forceMove...

**Comment by XDTM** [comment]
goddammit i fixed this bug once already and it took several hours

**Comment by XDTM** [comment]
@AnturK tested, does not happen
