### ISSUE TITLE
The CtrlShiftClick transform shortcut for ghosts doesn't work

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#25427]
@RemieRichards @PKPenguin321

**Comment by Sligneris** [comment]
What's that supposed to do again?

**Comment by MrStonedOne** [comment]
>What's that supposed to do again?

**Comment by Cyberboss** [comment]
Transform ghosts to humans

**Comment by Cyberboss** [comment]
https://github.com/tgstation/tgstation/blob/master/code/modules/mob/dead/observer/observer.dm#L825

**Comment by Shadowlight213** [comment]
Never knew that was a thing.

**Comment by MrStonedOne** [comment]
Ya, when using transform as a primary descriptor of something, it's best to differentiate from matrix transforms, as thats what my mind went to.
