### ISSUE TITLE
Mobs attacking grilled reinforce windows manage to smash the grilles without breaking the window

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25459]
Humans cannot do this, simple mobs (and for that matter explosions) shouldn't be able to do this. Somehow.

![image](https://cloud.githubusercontent.com/assets/609465/24303991/d76985e0-10af-11e7-8058-68003c313265.png)

**Comment by Jalleo** [comment]
This might be a oversight from something being changed.

**Comment by kriskog** [comment]
Cant reproduce
