### ISSUE TITLE
Centcom air alarm alerts

### ISSUE THREAD

**Issue by Jalleo** [tgstation/tgstation#25451]
[Note]: 
183716e0dd0529c570bc139981548eb6ccbab9db 
Centcom Supply Dock air alarm can activate meaning  you see it on station. NOT EVEN JOKING

**Comment by Cyberboss** [comment]
This is an issue with alarms showing shit not one the zlevel in general

**Comment by duncathan** [comment]
will investigate

**Comment by PKPenguin321** [comment]
Fancy centcomm was a mistake

**Comment by SpaceManiac** [comment]
@Cyberboss Cannot reproduce.
