### ISSUE TITLE
Space turns white when you observe someone

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#25479]
Go to the OOC tab and click observe while dead. Choose any living (or dead?) person. Space should turn white. @MrPerson ?? 11:04pm 3/24/17 EST, tgstation Bagil

**Comment by Jalleo** [comment]
Maybe a byond thing.

**Comment by MrStonedOne** [comment]
Observing causes you to inherent the hud of the person you're observing. Parallax is done as a hud.

Most likely a bug in that process

**Comment by MrPerson** [comment]
I'm working on this
