### ISSUE TITLE
Thermal goggles gives you night vision

### ISSUE THREAD

**Issue by imtakingabreakdontatme** [tgstation/tgstation#25470]

**Comment by PKPenguin321** [comment]
Note that it has a feature where it gives night vision in a 3x3 area around you, been like this forever. Mesons give 1x1 night vision on top of you too. I'd have to test and see if this is actually a bug

**Comment by GunHog** [comment]
For the longest time, I thought it intentional. It certainly is for the eye implant!
Eyes: https://github.com/tgstation/tgstation/blob/361d4f7547082f70260d6120bf0a20ed4bdd3b33/code/modules/surgery/organs/organ_internal.dm#L826

**Comment by Bawhoppen** [comment]
Pretty sure intentional for the 3x3

**Comment by PKPenguin321** [comment]
3x3 is in fact intentional

**Comment by kriskog** [comment]
Intentional
