### ISSUE TITLE
EMPs don't always disable headsets anymore

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#25480]
got caught by security in a cult round because despite using an EMP paper on the CE, it didn't deactivate the headset like it's supposed to, which made me get caught by security

**Comment by Cyberboss** [comment]
@coiax You did random wire pulsing right?

**Comment by coiax** [comment]
Headsets are always affected by EMPs, and you'll only get wire pulsing if you call super.

**Comment by BeeSting12** [comment]
@YakumoChen 
Did you hit the CE with the EMP paper? I'm pretty sure it's an AOE thing.

**Comment by YakumoChen** [comment]
@BeeSting12 Yes, I used it in my hand, it EMPed several doors and cameras, and I was cuffing and pulling the CE, yet he seemed to have no trouble calling for help on his headset.

**Comment by ExcessiveUseOfCobblestone** [comment]
> Headsets are always affected by EMPs, and you'll only get wire pulsing if you call super.

what do you mean by this @coiax

**Comment by coiax** [comment]
Assuming that emp_act() is called on a headset object, it always loses functionality.

My wire pulsing changes wouldn't have modified this.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm going to take a gander and say it's because it uses src and not usr for it's location.

**Comment by AnturK** [comment]
Can't reproduce.

**Comment by kevinz000** [comment]
@AnturK think this is just a freak incident of lag helping the CE. You know how you can dodge bombs by running towards the center? I believe empulse uses the same proc/spiral_range_turfs to emp things, so if the CE moved the right direction at the right time in theory he can dodge it.
