### ISSUE TITLE
Cannot Eject tank from Canister

### ISSUE THREAD

**Issue by Penguaro** [tgstation/tgstation#25497]
You can load a tank into a canister for filling. You can fill it. Pressing eject has no effect. This is the case for Oxygen Canister/Tank and Plasma.

Server revision compiled on: 2017-03-25
79296e902cbdf2352c9303e4769ea39bf3b34e5 
No Test Merges

**Comment by Penguaro** [comment]
Hang on, let me change that server info... Forgot to change branches locally. Unlikely that my map edit affected this, but will certainly close if somehow it did...

**Comment by Cyberboss** [comment]
No, its happening to me too.

**Comment by Penguaro** [comment]
Edited Server Revision Info...
