### ISSUE TITLE
Early shuttle launch announcements are still incredibly fucked, with new rollover errors

### ISSUE THREAD

**Issue by harmonyn** [tgstation/tgstation#25495]
I feel like this code is probably still fucky so the full log:

ADMIN LOG: HollaHollaFoADolla/(Ezri Dax) (?) (FLW) has authorized early shuttle launch
Attention:
2 authorizations needed until shuttle is launched early

ADMIN LOG: Kreeping poo/(Vincent Draudy) (?) (FLW) has authorized early shuttle launch
Attention:
1 authorizations needed until shuttle is launched early

Attention:
2 authorizations needed until shuttle is launched early

Attention:
Early launch authorization revoked, 2 authorizations needed

ADMIN LOG: Kreeping poo/(Vincent Draudy) (?) (FLW) has authorized early shuttle launch
Attention:
1 authorizations needed until shuttle is launched early

Attention:
2 authorizations needed until shuttle is launched early

Attention:
Early launch authorization revoked, 2 authorizations needed

ADMIN LOG: Kreeping poo/(Vincent Draudy) (?) (FLW) has authorized early shuttle launch
Attention:
1 authorizations needed until shuttle is launched early

Attention:
2 authorizations needed until shuttle is launched early

Attention:
Early launch authorization revoked, 2 authorizations needed

ADMIN LOG: Kreeping poo/(Vincent Draudy) (?) (FLW) has authorized early shuttle launch
Attention:
1 authorizations needed until shuttle is launched early

Attention:
2 authorizations needed until shuttle is launched early

Attention:
Early launch authorization revoked, 2 authorizations needed

ADMIN LOG: Kreeping poo/(Vincent Draudy) (?) (FLW) has authorized early shuttle launch
Attention:
1 authorizations needed until shuttle is launched early

Attention:
2 authorizations needed until shuttle is launched early

Attention:
Early launch authorization revoked, 2 authorizations needed

ADMIN LOG: Kreeping poo/(Vincent Draudy) (?) (FLW) has authorized early shuttle launch
Attention:
1 authorizations needed until shuttle is launched early

Attention:
2 authorizations needed until shuttle is launched early

Attention:
Early launch authorization revoked, 2 authorizations needed

ADMIN LOG: Kreeping poo/(Vincent Draudy) (?) (FLW) has authorized early shuttle launch
Attention:
1 authorizations needed until shuttle is launched early

Attention:
2 authorizations needed until shuttle is launched early

Attention:
Early launch authorization revoked, 2 authorizations needed

ADMIN LOG: Kreeping poo/(Vincent Draudy) (?) (FLW) has authorized early shuttle launch
Attention:
1 authorizations needed until shuttle is launched early

Attention:
2 authorizations needed until shuttle is launched early

Attention:
Early launch authorization revoked, 2 authorizations needed

ADMIN LOG: HollaHollaFoADolla/(Ezri Dax) (?) (FLW) has emagged the emergency shuttle 58 seconds before launch.
SYSTEM ERROR:
The emergency shuttle will launch in 10 seconds

ADMIN LOG: Kreeping poo/(Vincent Draudy) (?) (FLW) has authorized early shuttle launch
SYSTEM ERROR:
The emergency shuttle will launch in 10 seconds

Attention:
-9 authorizations needed until shuttle is launched early

**Comment by Cyberboss** [comment]
-_-

**Comment by ExcessiveUseOfCobblestone** [comment]
lol
