### ISSUE TITLE
Setup Character

### ISSUE THREAD

**Issue by idontwannasignup** [tgstation/tgstation#25506]
The set up character creation menu is bugged. All ways the character face is now forwards. 
It's been this way for a good month at least. 

The image of your character will have a hard time showing up, but you can usually switch it back and forth (between hairstyles or anything) and it'll show up.

**Comment by Profakos** [comment]
The first problem one could be an issue with getFlatIcon, as if you take a photo of someone with a Camera, they will always face forwards.

**Comment by idontwannasignup** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE IT'S BEEN MONTHS
