### ISSUE TITLE
stacking is broken somewhere

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#25512]
in addition to #25453 and #25418, I just played a round with meteors wrecking the station, and the metal rods resulting from the destruction were broken:

- they didn't stack

- their sprites DID stack, so you could drag one single rod over another and they would both change their sprite from single to double

**Comment by Cyberboss** [comment]
@AnturK @lzimann

**Comment by lzimann** [comment]
Will be solved by #25504
