### ISSUE TITLE
N2O nitrous oxide does not show up on analyzers

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#25511]
There used to be a bug I forgot to report where N2O would show up as nitrogen in the pipes, and not print a digit of its composition (ex Nitrogen 1 .3% for n2o 12.3%).

It seems someone tried to fix it, but as it is now it flat out does not show up on analyzers when examining pipes, canisters etc.

**Comment by Tacolizard** [comment]
I think this happens because n2o is a subset of nitrogen and scanners do `if(abs(n2_concentration - N2STANDARD) < 20)` and n2o isn't N2STANDARD.

**Comment by Iamgoofball** [comment]
this is intentional I believe

**Comment by duncathan** [comment]
can confirm this is unintentional and needs to be fixed

**Comment by duncathan** [comment]
resolved on live
