### ISSUE TITLE
A nuclear operative using the explosive implant will sometimes leave the syndicate headset behind

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25521]
I mean, what's the point of blowing yourself up if it's going to leave random items for the crew to collect?

**Comment by BeeSting12** [comment]
I don't think this is a bug is it? And I also think that they always leave the headset.

**Comment by optimumtact** [comment]
hard to call this a bug really

**Comment by Dorsisdwarf** [comment]
Do you feel like people are opening bug reports for things they'd never normally do right now?
