### ISSUE TITLE
When Ian has both a helmet and armor you cant kill him with objects, but can kill him with punches

### ISSUE THREAD

**Issue by Goodstuff123456** [tgstation/tgstation#25526]
This just doesn't make sense, it being impossible to kill him with objects with full armor but being able to with punches.

**Comment by calzilla1** [comment]
Make him just unkillable via brute

**Comment by Bawhoppen** [comment]
It makes perfect sense to me?

**Comment by ExcessiveUseOfCobblestone** [comment]
feature?

**Comment by jughu** [comment]
Make it swat armour do that :^)
