### ISSUE TITLE
Roundstart (CAPTAIN) is on deck announcement doesnt show up

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#25523]
Same for dept head messages I think but you might want to try reproducing

**Comment by Bawhoppen** [comment]
Heads are sent via announcement system I believe

**Comment by BeeSting12** [comment]
Yes, and they don't show up at roundstart. Just checked and neither of them work.

**Comment by Profakos** [comment]
I have looked into this. Nothing calls the job.announce() proc, which would call head_announce() for heads, and would do a minor_announcement() for the captain.
