### ISSUE TITLE
If the nuke goes off on a non-nuke ops round, the end splash screen and cross server message say it was a self destruct

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25522]
The reason for the nuke exploding seems to be tied to the mode, rather than the type of nuke that was set off.

**Comment by Cyberboss** [comment]
nuke checks is a fuckton of shitcode in general

**Comment by XDTM** [comment]
On the other hand if you made it bomb-based nuke ops wouldn't be able to use the station bomb as a backup plan

**Comment by coiax** [comment]
well if the nuke ops use the station's self destruct device, then you'd use the station self destruct splash screen

**Comment by Bawhoppen** [comment]
Station bomb is a different code I thought

**Comment by Cyberboss** [comment]
Nope, it's just a reskinned syndiebomb

**Comment by optimumtact** [comment]
nuke has not really been adapted to fire outside of a nuke round properly, it's mostly an admin hack

**Comment by Shadowlight213** [comment]
@cyberboss they meant the station bomb has a different activation code than the syndie one.
Normally the station bomb can't be activated at all, as its code is set to "ADMIN"
