### ISSUE TITLE
XRAy eyes don't see through blindfold

### ISSUE THREAD

**Issue by MegaZeus101** [tgstation/tgstation#25531]
[Note]: # (Please enter the commit hash and active testmerge numbers from the "Show Server Revision" verb if you can. If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by ExcessiveUseOfCobblestone** [comment]
nice

**Comment by Penguaro** [comment]
How else are we supposed to kink-ERP when we have XRay eyes?

**Comment by TechnoAlchemisto** [comment]
Must have been too dark in that locker!

**Comment by ExcessiveUseOfCobblestone** [comment]
You meta roleplay by roleplaying as someone roleplaying during erotic roleplay

**Comment by ShizCalev** [comment]
probably just need to tweak update_tint() a bit.
