### ISSUE TITLE
Monkey interaction is broken

### ISSUE THREAD

**Issue by XDTM** [tgstation/tgstation#25533]
A few things that were borked:
- Putting a backpack on created a tie inventory slot icon on top of the backpack slot while leaving the backpack icon in my hand. The hand was still free to use.
- Couldn't open lockers with an empty hand. Items worked.
- Couldn't interact with non-dna syringes. No error message displayed, but could be intentional to prervent mutadone. Pills work tho.

**Comment by XDTM** [comment]
Also they can't drag/drop containers to open them

**Comment by AnturK** [comment]
Can't reproduce the drag/drop issue, seems to be working ?
