### ISSUE TITLE
Ash storms not visible with meson vision

### ISSUE THREAD

**Issue by cedarbridge** [tgstation/tgstation#25534]
Exactly what it says on the tin.  Ash storms are invisible when using meson vision goggles of all types but visible with them off.

**Comment by xxalpha** [comment]
How is this a bug?

**Comment by ChangelingRain** [comment]
@MrPerson 
And of course this is a bug, miners need mesons to MINE and ash storms used to be visible even with mesons.

**Comment by Dorsisdwarf** [comment]
I was able to see an ash storm with mesons on yesterday

**Comment by cedarbridge** [comment]
Not sure how you did it then.  The referencing issue report above combined with every-round ahelps and my own round this morning shows the overlay is still bugged for most.

**Comment by Kromgar** [comment]
I just got killed by this shit

**Comment by Kromgar** [comment]
This shit should be priority it gets people killed super fucking easy

**Comment by golfer45** [comment]
Yep happened to me too

**Comment by Kromgar** [comment]
When will the agony end

**Comment by cedarbridge** [comment]
This applies to measons, NV measons, Eye of God, Gar measons.

Extra problematic for the EoG since it can't be removed.
