### ISSUE TITLE
Abductors say ... when using telepathic speak

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#25543]
This is probably a dupe but I did a brief search and couldn't find one

**Comment by coiax** [comment]
Yeah, dupe of #22910. I know that because it 's one of my issues.

**Comment by XDTM** [comment]
I also pinpointed the code that causes it, but i don't have a solution yet

**Comment by Armhulen** [comment]
It's a dupe but MY GOD DO I HATE THIS
