### ISSUE TITLE
"Asteroid with engines on it" stuck on igniting

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#25550]
The shuttle arrives, however, it gets stuck on Ignite. Perhaps it can't find a transit space large enough to fit in, and it keeps retrying? The map was Boxstation, using the generic centcom z level.

Server revision compiled on: 2017-03-27

**Comment by coiax** [comment]
Is this reproducible? Transit space is very large, it SHOULDN'T have a problem. But it is a shuttle where the whole gimmick is being stupidly large, so idk.

**Comment by Profakos** [comment]
Reproduced about five times on my testserver and on the server of a friend. Bought the shuttle, waited for it to arrive, and waited for it to launch. When ETA hit 0, it got stuck on IGN 10:00, and the engine powerup sound failed to play too.

Being unable to locate transpit space was just a hunch from me, based on the code.

**Comment by octareenroon91** [comment]
OK, I just ran the asteroid shuttle on a recent revision, and the asteroid rendered with space instead of sand-floored tunnels. I interpret this as template/maploading is using space rather than asteroid baseturf.

**Comment by Penguaro** [comment]
@octareenroon91 Is what you're talking about this issue #24826 or a new one?

**Comment by octareenroon91** [comment]
It is likely that would have fixed it.  The other side of the issue likely remains. I got the feeling it was taking forever to find a usable transit box.

**Comment by WJohn** [comment]
Definitely still a problem, the shuttle won't depart. Maybe has to do with it taking a huge chunk of the station upon arrival?

**Comment by octareenroon91** [comment]
I've seen one or two asteroid shuttles launch since posting on this issue. This suggests that the problem depends on one of the random elements of the shuttle -- most likely how large the asteroid may become.  I suggest the needs a hard limit on its outside shape.

**Comment by WJohn** [comment]
Is this still the case? It's been 6 months and a shuttle rewrite since.
