### ISSUE TITLE
Advanced Darkness is broken

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#25578]
The weather. You can no longer see one tile in every direction.

@MrPerson

**Comment by MrStonedOne** [comment]
@PJB3005

**Comment by PKPenguin321** [comment]
Please fix or at least disable. It also causes space lighting to break for the rest of the round.

**Comment by PJB3005** [comment]
I still want to know how in the name of fuck "advanced darkness" works and what it does because unless it's been REALLY poorly explained lighting shouldn't touch it at all.

**Comment by KorPhaeron** [comment]
Lighting doesnt touch it at all. This would be too much effort to fix. Just axe the event.
