### ISSUE TITLE
Wrenching left facing gas filter / mixer over an existing pipe switches it to right facing

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#25585]
Pretty self explanatory.

http://c2n.me/3IX233H.png

Left facing Filter / Mixer + wrenched over existing piping =

http://c2n.me/3IX248O.png

**Comment by duncathan** [comment]
will investigate

**Comment by duncathan** [comment]
deferring until kevinz finishes mutlipipes; i'll probably rework pipe construction AGAIN ugh
