### ISSUE TITLE
No APC in Delta R&D Server Room

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#25582]
You cannot turn off the power in the room as there are no APCs leading to it.

Asked an admin to confirm;

-- Administrator private message --
Admin PM from-Cedarbridge: Apparently not.
Click on the administrator's name to reply.
-- Administrator private message --
Admin PM from-Cedarbridge: Yeah, best I can tell the server room is just powered by magic
Click on the administrator's name to reply.

**Comment by BeeSting12** [comment]
I can fix this once I get home
