### ISSUE TITLE
oneuse spellbooks cannot be picked up

### ISSUE THREAD

**Issue by feemjmeem** [tgstation/tgstation#25591]
Single-use spellbooks cannot be picked up when clicked on. They can still be used if forced into the hand.

**Comment by Tacolizard** [comment]
I could not reproduce this on the test server

**Comment by feemjmeem** [comment]
This is still happening live.

**Comment by PKPenguin321** [comment]
Servers are maybe not updated?

**Comment by optimumtact** [comment]
in over two days?

**Comment by PKPenguin321** [comment]
Good point

**Comment by lzimann** [comment]
This has been fixed, I believe the server was not updated at the time.
