### ISSUE TITLE
Androids slip and slide in broken glass but they take no damage

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#25590]
Either OR guys

it might not be a bug but if they take no damage...

:confused: :exclamation:

**Comment by XDTM** [comment]
They're supposed to neither be stunned or take damage from glass due to NOPIERCE, if they actually _slipped_ maybe the ground was wet or lubed.

**Comment by Armhulen** [comment]
Nope, no lube or water.

**Comment by AnturK** [comment]
This whole functionality is locked behind human check, you sure it wasn't human in a cardboard suit or something like that.

**Comment by RemieRichards** [comment]
@AnturK Android, not Cyborg, I think we need to rename Posibrain Cyborgs away from "Android" now that people call Synths/Androids... Androids.

**Comment by AnturK** [comment]
Ohhh, forgot these existed.

**Comment by Repukan** [comment]
@ChangelingRain Wasn't this fixed with Kor's changes to augmented legs and shit

**Comment by Repukan** [comment]
@KorPhaeron you fixed this
