### ISSUE TITLE
Space Travel slower?

### ISSUE THREAD

**Issue by YAllanonY** [tgstation/tgstation#25598]
I tried space travel on Bagil/Basil, Boxstation. Multiple times I would get stuck on nothing. I would drop something to make sure I was moving. and I wouldn't be, so I'd throw something and it would still start and stop the movement sporadically, without input from me. I could tell it wasn't the server lagging, the chat was moving by fine, and I could access my bags without delays. Just lettin ya know

**Comment by AnturK** [comment]
@kevinz000

**Comment by optimumtact** [comment]
#25610

These are related and this is far more likely to be an out of memory issue or runtime killing the tickers

**Comment by optimumtact** [comment]
@MrStonedOne

**Comment by kevinz000** [comment]
dindunuffin.

**Comment by PKPenguin321** [comment]
Still happening?
