### ISSUE TITLE
Abductors can reach everything on the Centcom z-level

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#25600]
As the title says, you can go anywhere on the Centcom z-level using the abductor observation console.
Tested locally using a recent/latest master branch version.

To set this up simply:
 Build a camera on your abductor ship.
 Jump to the constructed camera with the observation console.
 Pan around the Centcom z-level. 
 Access any area by setting the experiment release point there and using the emergency teleport function    from the main Abductor console.

Notes:
 For better visibility you can cancel using the observation console and using it again will clear a wide area of   static around where you were last viewing.
 You can also teleport normally around the three cameras at the thunderdome.
 The observation console eye can simply start at the thunderdome for reasons I'm unsure of.

Abductors probably shouldn't have access to a bunch of free explosives, a suit of deathsquad armor, the one hit kill CTF flags, and a hoard of other gear.

**Comment by Tacolizard** [comment]
this is the kind of thing that's obviously overpowered, but I gotta congratulate people for finding this.

**Comment by bgobandit** [comment]
ayy lmao

**Comment by optimumtact** [comment]
there needs to be another z level for things like antags

**Comment by anconfuzedrock** [comment]
wait a sec I figured it out I know exactly how to fix this bug I am a genius

**Comment by anconfuzedrock** [comment]
oh was it already fixed

**Comment by RemieRichards** [comment]
yes, the camera eye can now be locked to a z level, in the abductor's case it's locked to the station.

**Comment by anconfuzedrock** [comment]
FUCK

**Comment by lzimann** [comment]
Poor rock, his moment of glory was stolen by evil maintainers.

**Comment by AnturK** [comment]
Sorry, i should be leaving easy fixes to other people.

**Comment by RemieRichards** [comment]
nah, it was your feature it makes sense to clean up your own messes.
