### ISSUE TITLE
Bluespace Anomolys pull you even with magboots on

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#25604]
so i was doing my normal supermatter anomoly farming and there was this bluespace anomoly that kept pulling me into a wall stunning me

**Comment by Tacolizard** [comment]
this might not be a bug but idk. were the magboots powered on?

**Comment by jughu** [comment]
they were on definitly

**Comment by XDTM** [comment]
Boots only prevent air from moving you

**Comment by jughu** [comment]
BOOTS ALSO PREVENT SINGULO PULLING YOU

**Comment by PKPenguin321** [comment]
This isn't a broken feature and not really a bug, more of a consistency issue/feature request

**Comment by Barhandar** [comment]
Bluespace anomalies teleport instead of pulling, gravitational anomalies pull and I made magboots protect against these in #41583.

**Comment by kriskog** [comment]
Intentionally left out of magboots fix.
