### ISSUE TITLE
Landing zones placed near map borders break shuttles attempting to dock there.

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#25615]
See title,
this results in the aux base, mining shuttle, and rarely escape pods being sliced apart, with the lost/undocked section remaining back in hyperspace.

This can be abused to stay on the Centcom z-level and infiltrate Centcom, as hyperspace reverts back to normal space.

Steps to reproduce:
 Get landing beacon.
 Go to the edge of the lavaland map south of where the white ship lands.
 Create an aux base landing zone next to the map border.
 Head back to the station and launch the aux base while buckled to a chair on the south half of the base.
 Watch as the other half is torn off leaving you stranded in hyperspace.
 You are now free to EVA over to Centcom.

**Comment by WJohn** [comment]
One fix would be to have a border of lava/indestructible walls surrounding all of lavaland, but that would make lavaland smaller by quite a bit. Maybe prevent the placement of the aux base beacon within certain range of the border? Would probably need to be at least 4 of NO BUILD distance, as the aux base is 9x9.  Make it 7 in case someone wants a bigger aux base.

**Comment by ninjanomnom** [comment]
This is no longer an issue exactly but instead shuttles moving onto null turfs will refuse to move. So you'll be left in transit space.
