### ISSUE TITLE
Lighting on metal foam is inconsistent, depending on whether it is in space or not

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25616]
![image](https://cloud.githubusercontent.com/assets/609465/24476449/2ae025e8-14cb-11e7-98d0-b4c7378cdd8f.png)

**Comment by MrStonedOne** [comment]
Feature:

Space has no lighting.

**Comment by YakumoChen** [comment]
isn't space supposed to be lit?

**Comment by Cyberboss** [comment]
Maybe we could consider giving space white dynamic lighting if #25654 does what it's supposed to

**Comment by ChangelingRain** [comment]
Giving space dynamic lighting has its own issue, that is, having too many fucking objects in the game world.

**Comment by PKPenguin321** [comment]
This issue also happens with asteroid walls, noticeable on cerestation

**Comment by Cyberboss** [comment]
OK, I think the real solution is to make metal foam a closed turf

**Comment by Cyberboss** [comment]
The asteroid thing sounds like a separate issue

**Comment by timothymtorres** [comment]
![dreamseeker_IqULcMx7YV](https://user-images.githubusercontent.com/5195984/130641898-ee61ed73-70db-45ab-b278-c98c134b2404.png)


> Feature:
> 
> Space has no lighting.


> isn't space supposed to be lit?

This is intended.  Having to have dynamic lighting on space tiles would be a big PIA.
