### ISSUE TITLE
Lighting objects needlessly uses expensive color matrices for fully lit/fully dark tiles.

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#25629]
For whatever reason Byond's implementation of color matrices is very inefficient on older computers (that or it's inefficient everywhere but just harder to ignore on older computers). Costly client rendering seemingly occurs every time a matrix colored object enters the screen. Considering the fact that there's up to 215 lighting objects on the screen at once this cost can really add up.

It is impossible not to use color matrices for colored/gradient light objects. However for uncolored fully lit (read: transparent) and fully dark (read: black) lighting objects this expensive matrix operation could be replaced with a much simpler flat color/alpha that would save a lot of client cost without changing what the lighting actually looks like at all.

I've been chipping away at why the new lighting runs so terribly on my local machine and this bug represents my findings. I am currently attempting to figure out a nice and cheap way to solve this but if someone else with a better understanding of the system beats me to the punch I wouldn't mind it at all.

**Comment by optimumtact** [comment]
@PJB3005 thoughts

**Comment by optimumtact** [comment]
@MrPerson thoughts also

**Comment by PJB3005** [comment]
My thoughts are WYCI.

**Comment by Tacolizard** [comment]
@tacolizard thoughts

**Comment by Tacolizard** [comment]
hmm yes  I think incoming needs a better computer
