### ISSUE TITLE
ADVANCED DARKNESS DOESN'T WORK WITH ADVANCED LIGHTING

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#25626]
THE WIZARD EVENT IS PITCH BLACK AAAH

**Comment by MrStonedOne** [comment]
@PJB3005

**Comment by PJB3005** [comment]
What's advanced darkness?

**Comment by YakumoChen** [comment]
It's a Wizard Event where everything turns pitch black

**Comment by PJB3005** [comment]
Unless you're failing to explain it, why the shit would such a thing rely on the lighting engine.

**Comment by anconfuzedrock** [comment]
nevermind then
