### ISSUE TITLE
Placing objects on a table by pixel location doesn't work anymore

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#25630]
idk if it was removed or if someone broke it, but you cannot do this anymore

@RemieRichards

**Comment by octareenroon91** [comment]
Wow, very strange.

**Comment by RemieRichards** [comment]
What happens instead?
Were you on HARM intent?

**Comment by bgobandit** [comment]
a) It just goes on the table, like it used to before the pixel stuff
b) nope

**Comment by RemieRichards** [comment]
Ok, I would guess the click params were broken by joan in 25516, causing them not to get to the ```attackby()```, which bails out of the pixel stuff because without params it can't know what pixels to use.

@ChangelingRain
