### ISSUE TITLE
Taking items from someone hands via CQC can make bug

### ISSUE THREAD

**Issue by Ultimitium** [tgstation/tgstation#25641]
When you have CQC/CQB techniques from nuke uplink and use disarm (that move which one taking item held by someone) on someone which have items like tactical defibrillator using it - you will take pads from that and offhand, which one you can't put away.

**Comment by Kromgar** [comment]
That should totally have the person get knocked down as you grab the  pads and pull them to the ground

**Comment by BeeSting12** [comment]
Looks like CQC isn't respecting nodrop like krav maga in #20930
