### ISSUE TITLE
An AI borg shell and AI installed in mech can interact weirdly

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25645]
Both communication consoles were destroyed, and the emergency shuttle was called.

The AI core was physically intact, but the AI couldn't return to it from the mech?

The point is, the 25 minute shuttle shouldn't have been called, at some point the AI didn't count.

**Comment by GunHog** [comment]
Deployed AIs are clientless, and fail the active AI check. Checking if the AI is deployed and has a client controlling the shell should fix this.

More investigation is required regarding the AI and things that can possibly clear its home var.

**Comment by GunHog** [comment]
If you insert 
`if(AI.deployed_shell && !AI.deployed_shell.client)`
`callShuttle = 0`
`break`
Below the line here:
https://github.com/tgstation/tgstation/blob/master/code/controllers/subsystem/shuttles.dm#L263
I think that should fix the problem.

**Comment by GunHog** [comment]
I believe that inserting this code (with proper indentation)
			`if(AI.deployed_shell && !AI.deployed_shell.client)
				continue`
Below this line: https://github.com/tgstation/tgstation/blob/master/code/controllers/subsystem/shuttles.dm#L263

Should solve the issue. Anything that would cause a deployed AI to be stat _should_ disconnect the AI from its shell, and the AI mob need not be checked for a client as it would be attached to its shell. If the AI is deployed to a shell, we should check the shell for an active client. It is not important that we check the shell for stat, as such does not affect its controlling AI.
