### ISSUE TITLE
The air injector and pipe on Metastation can be dissolved by alien acid

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25658]
I thought it was supposed to be acidproof.

**Comment by Kromgar** [comment]
Shit they used to be not sure if they are anymore

**Comment by ShizCalev** [comment]
pipes (and other atmospheric machines) don't have the ACID_PROOF flag.

**Comment by kriskog** [comment]
They can be slashed apart anyway, why waste the plasma.
