### ISSUE TITLE
Aliens cannot succumb by whispering or deathgasping

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25657]

**Comment by GunHog** [comment]
Xenos or Ayys?

**Comment by coiax** [comment]
Xenomorphs.

**Comment by Jalleo** [comment]
Ghosting works though I am trying to work out exactly now and PR a fix

**Comment by JJRcop** [comment]
Succumb isn't working because IsCritical on aliens still returns FALSE when they are at exactly 125 damage, which is their crit threshhold. At 126 damage and above it returns TRUE like it is supposed to and all works well.

**Comment by timothymtorres** [comment]
I code dived and almost all the xenos (except larva) have their crit values set via the default `/mob/living/carbon` which is 0 for crit, and -100 for death.  I suspect that this has been fixed at some point, but I will test this later to be sure.

**Comment by timothymtorres** [comment]
![SrHreujj0o](https://user-images.githubusercontent.com/5195984/130637797-0eb312bb-2f65-4121-b626-6578c799708c.png)

Xenos death whispering behaves just like normal humans.  They can crawl while at SOFT_CRIT but the moment they hit hardcrit they can no longer whisper.  While in any kind of crit they can click on the FINAL WORDS ghost icon to succumb or they can just use the succumb verb.

**Comment by timothymtorres** [comment]
I just realized that normal human mobs take oxy damage when they go into crit but xenos ignore this.  This allows them to stay in softcrit without any risk of dying.
