### ISSUE TITLE
When attacking a carbon with a facehugger, the message that the alien leaps at their face is printed twice

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25650]
The alien leaps at the monkey (562)'s face!
The alien leaps at the monkey (562)'s face!

**Comment by Tacolizard** [comment]
is this when a person is holding the facehugger and throws/hits them with it or is it when someone picks it up?

**Comment by coiax** [comment]
It's when I, the alien queen, attacked a monkey with the facehugger in my hand.

**Comment by WJohn** [comment]
This is fixed now.
