### ISSUE TITLE
Metastation xenobiology maintenance isn't maint for radstorm purposes.

### ISSUE THREAD

**Issue by GideonThermonuclearWar** [tgstation/tgstation#25661]
The following pull requests are currently test merged:
#24883: '[READY FOR REVIEW] ITS BACK : ATMOSPHERICS MULTILAYER PIPES!' by kevinz000 
#25333: 'Language datums; removes the talk wheel' by coiax 

Based off master commit:
d17aacc8cd5b7cc64d6f3920d0efc1825bf651df 

Basically title. It looks like maintenance, it talks like it's maintenance. You hide in there, you get irradiated by the radstorm event.

**Comment by kevinz000** [comment]
not my pr's fault

**Comment by Penguaro** [comment]
This is how CentComm saves on overhead for Xeno Specimens... #feature
