### ISSUE TITLE
Facehuggers rip off gas masks while your in a hardsuit

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#25660]
Da fuck

**Comment by XDTM** [comment]
dupe

**Comment by optimumtact** [comment]
Link to dupe?

**Comment by Kromgar** [comment]
@optimumtact i remember seeing a fix pr a week ago but i guess its still broken.

I was in a inquisitors hardsuit wearing a miners gas mask if that matters

**Comment by optimumtact** [comment]
fix hasn't been merged yet #25488 perhaps that's what @XDTM was referring to

**Comment by Cyberboss** [comment]
So this is a dupe of #25282
