### ISSUE TITLE
pAIs with universal translator taking control of bots, do not keep their languages

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25663]

**Comment by Sligneris** [comment]
pAI's inserted into bots seem to lose most of their pAI functionalities in the first place.

**Comment by coiax** [comment]
This will be fixed when I make languages attached/superceded by the mind.

**Comment by Sligneris** [comment]
Alternatively, just make pAIs inside bots be just that codewise - pAIs inside bots.

Make them their app interface, including security and medical HUDs just as accessible inside a Medibot as it is in their master's pocket.
