### ISSUE TITLE
Arrow on Y-Junction face wrong direction 

### ISSUE THREAD

**Issue by furryowl** [tgstation/tgstation#25670]
![bug](https://cloud.githubusercontent.com/assets/14878501/24522771/481071da-1599-11e7-83a9-6e135fd071cd.png)

**Comment by coiax** [comment]
I'm unclear on what the sprite should be doing.

**Comment by furryowl** [comment]
i will make a better picture

**Comment by furryowl** [comment]
![pr](https://cloud.githubusercontent.com/assets/14878501/24526272/3ef6a1fc-15a6-11e7-8a0a-63a63d6c9e47.png)

**Comment by Jalleo** [comment]
bottom right one its not rotated

**Comment by furryowl** [comment]
Bottom line is how it should work, but in game it work like on top line

**Comment by furryowl** [comment]
Jalleo
![pr](https://cloud.githubusercontent.com/assets/14878501/24529393/04145bb6-15b4-11e7-9618-d0d50c032cb8.png)
