### ISSUE TITLE
Chemical Implants broken

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#25698]
**[Note]: #** 
(Server revision compiled on: 2017-03-30
The following pull requests are currently test merged:
#24883: '[READY FOR REVIEW] ITS BACK : ATMOSPHERICS MULTILAYER PIPES!' by kevinz000 
#25333: 'Language datums; removes the talk wheel' by coiax 

Based off master commit:
d17aacc8cd5b7cc64d6f3920d0efc1825bf651df 

________________________

**Reproduction;**
Get box of chem implants
Try to use normal (or lethal) syringe on implant case / implant
Nothing happens

Insert into implantpad
Remove
Try to inject implant again
Nothing happens

**Comment by kevinz000** [comment]
not my pr's fault

**Comment by PKPenguin321** [comment]
Probably a dupe

**Comment by ShizCalev** [comment]
Not a dupe. Last one about the implants was closed about 4 months ago.

**Comment by coiax** [comment]
Probably not my PR's fault either.
