### ISSUE TITLE
Stealing Tech objective should be updated and reworked

### ISSUE THREAD

**Issue by Jalleo** [tgstation/tgstation#25697]
https://github.com/tgstation/tgstation/blob/master/code/game/gamemodes/objective.dm#L583
After the freeze we should rework this to not be hardcoded to ninjasuits only and more allow it to be a objective for anyone to steal tech.

**Comment by ktccd** [comment]
Just writing this up so I don't forget it:
It should check your items and allow tech-disks to count for the objective, just like any other theft-objective can. Not sure if this might be SUPER easy for scientists to do?

**Comment by Cyberboss** [comment]
Just don't let scientists get the objective

**Comment by Kromgar** [comment]
@Cyberboss can't scientists get steal plasma and steal a slime core

**Comment by optimumtact** [comment]
Not a bug, take it to the forum.

**Comment by Jalleo** [comment]
Cant I need MSO to manually email me a reset pass again...
