### ISSUE TITLE
Borers don't show up in Check Antagonists

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#25700]

**Comment by optimumtact** [comment]
please remove borers

**Comment by coiax** [comment]
Borers are also buggy because they're only played when admins are in the mood for it. Tbh, given how much I see borers, I don't know why the event is disabled. I often see admins make borers and then logout.

**Comment by ExcessiveUseOfCobblestone** [comment]
Borers are yucky

**Comment by PKPenguin321** [comment]
Remove em
