### ISSUE TITLE
AIs should have a laws reminder when they disconnect and reconnect

### ISSUE THREAD

**Issue by StuAhpla** [tgstation/tgstation#25708]
So I got subverted one round and got disconnected for a minute, and in that time someone reset me, I wasn't updated on any law changes when I reconnected and only knew after getting bwoinked.

Might be a problem if you disconnect, get hacked, and return and contiune to act normal if a traitor was intending for you to do somthing since you don't get the LAWS UPDATED status marker when you come back

**Comment by optimumtact** [comment]
not a bug, please report on ideas or feedback forums

**Comment by Cyberboss** [comment]
Idk man, if people are getting bwoinked for it by no fault of their own it seems like an oversight
