### ISSUE TITLE
Borers can become servants of ratvar

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#25701]
@ChangelingRain weeeeeew

>ADMIN: Durkel/(Tim Ebow) (FLW): >if you convert a player who's being controled by a borer(?|F) you convert the borer and not the host(?|F)

**Comment by optimumtact** [comment]
please remove borers.

**Comment by ChangelingRain** [comment]
The borer method of control is a mess and I'm not responsible for this.

**Comment by factoryman942** [comment]
Praise ratvar

**Comment by coiax** [comment]
I mean, this is fairly easy to understand. Borer control is just a mindswap, except the host's mind goes into a /mob/living/captive_brain. So if you use antag conversion methods while they're in control, it'll be the borer's mind.

**Comment by Cyberboss** [comment]
@lzimann You should consider what @coiax said for datum antags

**Comment by coiax** [comment]
I mean, what's the bug here? That borers can be converted at all? That converting a body controlled by a borer converts the borer, and not the host?

**Comment by Cyberboss** [comment]
@ChangelingRain What coiax said^
