### ISSUE TITLE
Dried blood from roundstart looks fresh

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#25709]
![image](https://cloud.githubusercontent.com/assets/6778786/24531977/e7048056-158a-11e7-8709-49379819d97d.png)

**Comment by bgobandit** [comment]
are you sure this is not a lighting thing

**Comment by Kromgar** [comment]
Oh it might be because mesons are deleting overlays

**Comment by Cyberboss** [comment]
>Administration

**Comment by PKPenguin321** [comment]
Misleading tags!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Repukan** [comment]
Fake news

**Comment by Bawhoppen** [comment]
N A N O W A R S . C O M

**Comment by coiax** [comment]
I'm going to refactor blood in a bit.

**Comment by Profakos** [comment]
Perhaps this happens because when decals were ported to Initialize,  a few of the child classes hiding in dirtystation.dm were not ported, and are still calling New().

**Comment by Cyberboss** [comment]
Ew

**Comment by Profakos** [comment]
Looks like i was wrong, and they seem to be dark and old again, but I'm still going to port their new to Initialize for consistency.

**Comment by Cyberboss** [comment]
@lzimann
