### ISSUE TITLE
<oranges> feature freeze is OVER

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#25712]
<oranges> feature freeze is OVER

![](http://i.imgur.com/YCdmvfC.png)

**Comment by MrStonedOne** [comment]
![](http://i.imgur.com/YCdmvfC.png)

**Comment by ma44** [comment]
This is a bug, it happens every couple months and it prevents people from making new and fun feature prs to this lovely codebase

**Comment by MrStonedOne** [comment]
***REEEEEEEEE! I'M FORKING***

**Comment by PKPenguin321** [comment]
Pro tip delete and recreate the repo and there will be 0 issues
