### ISSUE TITLE
Hyperfractal Gigashuttle Lockers require you right click to pickup gear from lockers. Can't just normally left click

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#25720]
I dunno... I just keep reporting bugs the freeze never ends

**Comment by coiax** [comment]
@Cyberboss this isn't locker code again is it?

Also, Hyperfractal Gigashuttle is played so rarely.

**Comment by Cyberboss** [comment]
Which locker?

**Comment by coiax** [comment]
Uh, they're the yellow radiation lockers, I think
