### ISSUE TITLE
Mulebot pathfinding struggles on larger maps

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#25745]
Mulebots have a fairly delayed response to sometimes out-right failing to find a proper path to a delivery beacon if the distance is lengthy. 

I'm mostly noticing this while trying to map working nav-beacons to CereStation. I've done mulptile test-runs and I'm getting fairly consistent results with the issue.
![cereroute](https://cloud.githubusercontent.com/assets/9276171/24573515/fee8b058-1651-11e7-97b4-61e5f848d41d.png)

The green lines are routes the mulebots seem to take fairly consistently, with orange lines being the odd route the mule bot occasionally takes to get to the destination. Red lines are routes the mule bots seem to almost never managed to take, almost always failing to find a route. On the rare chance they do manage to take this route, they usually fail to route back to their home designation.

The only real way I could think of solving this issue is being able to add nodes mid-way to help aide the pathfinder make a successful route consistently, or allow pre-making entire routes similar to how patrol  seem to currently work.

**Comment by Poojawa** [comment]
Space Mules.

I think you don't have any actual delivery zones, the ones with the plastic flaps that Box/Meta have. 

also, wasn't it a thing where delivery tagged wrapped packages would be ejected out of the disposal bins themselves, rather than needing an output chute?

**Comment by MMMiracles** [comment]
The map image itself is outdated, I just used it to demonstrate where I had the delivery zones, otherwise the mulebots couldn't of even been told where to go in the first place.

**Comment by ShizCalev** [comment]
was changed a few months back.
