### ISSUE TITLE
Beach Dome: The Blackening

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#25758]
![image](https://cloud.githubusercontent.com/assets/6778786/24579621/bffa594e-16c6-11e7-87a9-408d6b3c4859.png)

I guess natural tunnels fuck up the generation

**Comment by KorPhaeron** [comment]
@Cyberboss @AnturK

**Comment by AnturK** [comment]
icon_regular floor is set in initialize of original turf, and that original (non-initialized) value is used in ChangeTurf when the ruin is set if it fires up first.

**Comment by Penguaro** [comment]
Is this different than your other issue #24193 or is this a duplicate?

**Comment by AnturK** [comment]
Same error. Might be some regression since i can't recall seeing this that much.

**Comment by LemonInTheDark** [comment]
still an issue, see #55819
