### ISSUE TITLE
[s] Wizard's Magic Mirror allows memezombie race

### ISSUE THREAD

**Issue by octareenroon91** [tgstation/tgstation#25754]
Memezombies get the zombie claw stuck in each hand, so they can't use the mirror to change back: this is a way to render Wizard unwinnable before even teleporting to the station. Any blacklisting for the magic mirror has likely fallen out of date relative to the variety of races added.

**Comment by Armhulen** [comment]
>secret issue

**Comment by Kromgar** [comment]
Oh the trick is to learn teleport before coming a memezombie
