### ISSUE TITLE
Firing a bow drops a spent arrow as well as firing an arrow

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#25764]
Take the bow and fire it, it shoots the arrow and drops another arrow, which is technically a casing, but now spent. Firing the bow with the spent casing breaks the bow and makes it so you can't fire anymore arrows.

**Comment by octareenroon91** [comment]
Possibly of interest:
````
git grep ^/obj/item/ammo_casing/caseless/arrow
code/modules/projectiles/ammunition/caseless.dm:/obj/item/ammo_casing/caseless/arrow
code/modules/projectiles/guns/ballistic/bow.dm:/obj/item/ammo_casing/caseless/arrow
````

**Comment by WJohn** [comment]
Already mentioned in #27581
