### ISSUE TITLE
Chainsaw Arm gets stuck on pickup

### ISSUE THREAD

**Issue by Repukan** [tgstation/tgstation#25774]
>Cut chainsaw off corpse that had it surgically attached
>Drops a chainsaw arm, not a chainsaw
>Pick it up
>Can't drop it anymore

**Comment by Kromgar** [comment]
Haha holy fuck

**Comment by Cyberboss** [comment]
fuck fuck fuck

**Comment by DaxDupont** [comment]
feature

**Comment by PKPenguin321** [comment]
They're supposed to delete and drop a real chainsaw, somebody broke it

**Comment by QualityVan** [comment]
Can't replicate this. Removing a chainsaw arm results in a regular chainsaw on the ground, no matter how I did it. I discovered that if you dismember a chainsaw arm you get both an arm and a chainsaw though.

**Comment by Repukan** [comment]
Weird.

I remember I cut their arm off with a spear by stabbing the shit out of it. This was on box, so I'm not sure if it counts.

**Comment by AnturK** [comment]
Already fixed.
