### ISSUE TITLE
Lasers pass through Kudzu

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#25791]
Absolutely haram

If its dense enough to block all light passing through, it sure as hell shouldnt let lasers whiz by without harming it.

**Comment by PKPenguin321** [comment]
Dupe

**Comment by Robustin** [comment]
Kevinz told me to open it so he could fix the Xray laser/Kudzu issue without it being a "feature" that lasers now hit kudzu on contact.

**Comment by optimumtact** [comment]
this is not a bug in the sense that these items are not dense and do not block projectiles.

That makes it a rebalance and you can't have em during teh freeze.
