### ISSUE TITLE
Spawned items may be un-initialized.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#25806]
If you spawn an item as an admin via var editing, or through template spawning, there's a good chance that it will not be initialized. I'm not sure exactly what causes it to not initialize (it seems consistent but specific to certain items like medkits and sometimes backpacks).

As a result, these items cannot be picked up without using the pick up verb, and if placed in backpacks that item is not coming out.

This may or may not happen when ruins are spawned, and possibly also with away missions (but who cares, those are never loaded anyway).

**Comment by Cyberboss** [comment]
Give me an example?
