### ISSUE TITLE
Syndicate Stormtroopers NPCS with shotguns fire most of their bullets only north

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25807]
Server revision compiled on: 2017-04-01
The following pull requests are currently test merged:
#25763: '[DNM] [TEST MERGE ONLY] Revert "Fastmos III.5: Redux"' by coiax 

Based off master commit:
b33ee1aa28183a82a18f6fc06354ddb24176df7f

**Comment by Haevacht** [comment]
#25837 should fix. Potentially.
I guess reproduce afterwards? I can't see any other cause besides rounding memes.

**Comment by kriskog** [comment]
Should be fixed in #44700
