### ISSUE TITLE
Kevinz Flood Lights stay lights up when unwench

### ISSUE THREAD

**Issue by PaznerIV** [tgstation/tgstation#25800]
When I unwench one of the flood light it still stays light up, when it should turn off when its cut off/unwench from a wire nod contented to the power net

**Comment by Repukan** [comment]
Quality goo- I mean kevcode

**Comment by optimumtact** [comment]
@kevinz000

**Comment by ExcessiveUseOfCobblestone** [comment]
this man...

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't see a single update icon in floodlight.dm how tf do these even work
