### ISSUE TITLE
Monkeys can grab "offhands" from people riding borgs

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25810]
Deempisi's Revenge VII snatches the offhand from Grandmaster Honk.

**Comment by ExcessiveUseOfCobblestone** [comment]
They also steal zombie claws, imagine...

**Comment by coiax** [comment]
At that point, there's already someone with a zombie claw though. 

Not sure if they can steal NODROP items...

**Comment by XDTM** [comment]
i'm guessing they can also do it on people not on borgs

**Comment by Haevacht** [comment]
Coaix, the offhand is ABSTRACT | NO_DROP.

https://github.com/tgstation/tgstation/blob/0cf2e02bb6a78a94dc38e6880649382eb1732a04/code/game/objects/items/weapons/twohanded.dm#L122

They may steal changeling armblades, theoretically.

**Comment by Tacolizard** [comment]
@Haevacht feature

**Comment by Haevacht** [comment]
No, you shitty meme, bug.

**Comment by Sligneris** [comment]
Truth be told, a monkey taking away your offhand sounds extremely helpful.

**Comment by bgobandit** [comment]
Has been fixed @optimumtact 

https://github.com/tgstation/tgstation/pull/29257
