### ISSUE TITLE
Two people being able to pick up the same item

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#25814]
Server revision compiled on: 2017-04-02
The following pull requests are currently test merged:
#25801: '[DNM]Revert to last server compile' by Cyberboss 

Based off master commit:
6405a412a1122776f620ea5d142c8141beb11945 

I was going to write it off as a goof but it happened at least 5 times over the last week or so.
Sometimes when two people are fighting over an object they can pick up at the same time which does one or more of the following:
The item is inhand for one person but invisible and they can't pick up anything else on that slot.
The item is undroppable or duplicates on drop.
One case the mime was throwing a toolbox we both picked up, and it was animating(doing the rotating thing) in hand.
 Some other weird behaviours I don't remember exactly.

**Comment by octareenroon91** [comment]
Yay the desync bug.

I'm pretty sure it has to do with player screens or overlays, since disconnect/reconnect will fix a lot of these things.

**Comment by Qbopper** [comment]
I've seen this happen with a .50 cal

**Comment by ShizCalev** [comment]
Confirmed, happened between me and a syndie fighting over a .50. Both of us picked it up and had usable versions. When he placed his into his bag it ghosted into mine, but also remained in my hands. On drop I got a full dupe.

**Comment by Daturix** [comment]
Happend during a wizard round with a staff of healing.

**Comment by Sligneris** [comment]
Same, happened with my energy gun as a HoP.

**Comment by DaxDupont** [comment]
Someone reported having this issue today with soap

**Comment by ShizCalev** [comment]
Issue is present again.

**Comment by Cyberboss** [comment]
@AnturK !!!

**Comment by AnturK** [comment]
Hm, probably some issue with that horrible delayed  throwing finalize.
