### ISSUE TITLE
Constant lasers hitting freezer and xenobio console

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#25824]
![image](https://cloud.githubusercontent.com/assets/6778786/24591538/cb047af2-17d1-11e7-8cf4-285c81e6a6c6.png)
![image](https://cloud.githubusercontent.com/assets/6778786/24591539/cff16cf0-17d1-11e7-8db9-d45be716c7bc.png)

I'm going to assume admin memery but uh waht the fuck

Xenobio 6:26est bagil 4/2/2017

**Comment by ExcessiveUseOfCobblestone** [comment]
It's the hardlight bow all over again PANIC

**Comment by PKPenguin321** [comment]
This bug with repeated projectile hitting has been around for a while in many different forms, possible there's a related/dupe issue of this but I can't confirm

**Comment by Cyberboss** [comment]
Might be the same issue as the timer crashes

**Comment by Cyberboss** [comment]
Fixed by #26471 @lzimann
