### ISSUE TITLE
Heater and Freezer pipe connection bug to any pipe direction dir.

### ISSUE THREAD

**Issue by Jalleo** [tgstation/tgstation#25838]
To duplicate move the freezer/heater onto a pipe. Doesn't matter what type it will connect.
Just make sure all outer connections are being used.
Image of the bug http://imgur.com/ewWoTb9
![](http://i.imgur.com/ewWoTb9.png)

**Comment by Jalleo** [comment]
This is probably located in https://github.com/tgstation/tgstation/blob/master/code/modules/atmospherics/machinery/datum_pipeline.dm#L90
due to the else
Also it turns out this only occurs when there is a pipe to the south....

**Comment by duncathan** [comment]
interesting this may be linked to a couple other issues

**Comment by Jalleo** [comment]
[16:59:03] Runtime in atmosmachinery.dm,119: list index out of bounds
  usr: Marion Swarner (jalleo) (/mob/living/carbon/human)
  usr.loc: The floor (132,90,1) (/turf/open/floor/plasteel)
[16:59:03] Runtime in components_base.dm,109: list index out of bounds
  usr: Marion Swarner (jalleo) (/mob/living/carbon/human)
  usr.loc: The floor (132,90,1) (/turf/open/floor/plasteel)
[16:59:03] Runtime in datum_pipeline.dm,127: Cannot execute null.addMember().
  usr: Marion Swarner (jalleo) (/mob/living/carbon/human)
  usr.loc: The floor (132,90,1) (/turf/open/floor/plasteel)
[16:59:03] Runtime in components_base.dm,105: list index out of bounds
  usr: Marion Swarner (jalleo) (/mob/living/carbon/human)
  usr.loc: The floor (132,90,1) (/turf/open/floor/plasteel)
[16:59:03] Runtime in components_base.dm,94: list index out of bounds
  usr: Marion Swarner (jalleo) (/mob/living/carbon/human)
  usr.loc: The floor (132,90,1) (/turf/open/floor/plasteel)
Discovered by rotating the freezer/heater while on a pipe.
