### ISSUE TITLE
Shuttle movement should immediately update lighting objects

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#25857]
Having that 2 seconds of darkness is really immulsion breaking

**Comment by Jalleo** [comment]
Simple just move it with the shuttle.

**Comment by octareenroon91** [comment]
>Escape at maximum speed
>Lights don't dim

**Comment by Cyberboss** [comment]
Can't move it with the shuttle, lighting objects aren't designed to be moved

**Comment by MrPerson** [comment]
Just going to reiterate that moving the lighting objects is a triple plus bad idea

**Comment by Jordie0608** [comment]
Easy IC explanation: Shuttles move faster than light so it takes a little while for all the light inside the shuttle to catch up.
