### ISSUE TITLE
You can touch wormholes with tk and get teleported

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#25855]
WE ARENT GOING BELOW 800 YOU SWINES.

But yeah touch a wormhole during the wormhole event and you can get telported across station dont even need to be standing next to one

**Comment by octareenroon91** [comment]
Not a feature?

**Comment by XDTM** [comment]
Make it only teleport your brain

**Comment by octareenroon91** [comment]
:ok_hand:
