### ISSUE TITLE
Stock prices can still go absolutely apeshit

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#25854]
Yes, it's a bug, stock prices should not be going into 1e50.

The most info I've been able to gather is that the government bailout event seems to be happening a lot (like, several times simultaneously) for stocks where this happen. My guess is that this creates an exponential effect. However, given that both event queuing and news logging are coded IDIOTICALLY, it is very hard to get hard data on it, let alone figure out wtf is causing it.

Does anyone know the original Goon <s>clown</s> coder who made this? @Iamgoofball

**Comment by octareenroon91** [comment]
>1e50

**Comment by Iamgoofball** [comment]
Marq made it but he's MIA

**Comment by Supermichael777** [comment]
BET BIG ON A BAILOUT
