### ISSUE TITLE
Items removed from backpack catch fire while using the Mysterious Boat

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#25860]
Steps to reproduce: 
1) Have any item in your backpack. 
2) Move the Mysterious Boat into Lava and board it.
3) While buckled to the Boat and on a Lava turf, remove an item from your backpack
4) The item catches fire and is destroyed quickly.

Server: Bagil

**Comment by Cyberboss** [comment]
I swear i fucking fixed this

**Comment by Arkvold** [comment]
This seems to be still happening.

As a lavaproof (from bottle of dragon's blood) and fireproof (fully augmented) human, standing in a Mysterious Boat from the Ship in a Bottle while travelling over lava caused my Proto-Kinetic Accelerator to catch fire, and damaged my clothing (detective's hat and trenchcoat, but no other articles of clothing).

If I wade through lava without the boat, however, I don't suffer any item damage whatsoever - checked by examining variables as I went for a lava swim.
