### ISSUE TITLE
Supermatter random delamination with no warning

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#25867]
(F) [Common] supermatter crystal beeps, "CRYSTAL DELAMINATION IMMINENT. Instability: 723708%"
10:37:37 [0x200677e] (113,66,1) || the supermatter crystal has been created.
10:45:39 [0x200677e] (113,66,1) || the supermatter crystal has consumed the metal rod.
10:49:55 [0x200677e] (113,66,1) || the supermatter crystal has been powered for the first time.
11:31:54 [0x200677e] (113,66,1) || the supermatter crystal has reached the emergency point for the first time.
11:31:54 [0x200677e] (113,66,1) || the supermatter crystal has exploded.
11:31:54 [0x200677e] (113,66,1) || the supermatter crystal has spawned additional energy balls.
11:31:54 [0x200677e] (113,66,1) || the supermatter crystal has been destroyed.
Note the 4 identical timestamps on the latter 4 logs.
Guy who set it up says they turned off emitters and there was no gas in the chamber.
What the fuck?!

**Comment by Jalleo** [comment]
No gas at all maybe the issue.

**Comment by octareenroon91** [comment]
It was running just fine for 42 minutes, wasn't it?

**Comment by Tokiko1** [comment]
Could be related to issue #25824 since projectiles damage the crystal.

**Comment by Jalleo** [comment]
Improper SM setup and how the SM needs gas to not explode. 
If you are talking about how it failed suddenly we may be missing something here. I suggest closing the issue/clarifying.

**Comment by octareenroon91** [comment]
@Jalleo am I reading the timestamps wrong?

**Comment by Tokiko1** [comment]
There's certainly something wrong here: The thing should have never reached these extreme amounts of damage, much less instantly. Also sounds like it gained unreasonably high amounts of energy instantly too. Most likely scenario would be the crystal getting hit by some projectile with a bizzare, 100,000+ damage value though I don't think any such projectile should exist.

**Comment by PKPenguin321** [comment]
Reminds me of that old singulo bug where it would never expand past level 1 if it was in a 1x1 field, and would instantly go to max level the second you opened the field

**Comment by kevinz000** [comment]
@PKPenguin321 that still happens, if it's on containment edge nothing happens till it hits 5x5 then you die. :/

**Comment by XDTM** [comment]
Division by almost 0 due to no gas?

**Comment by kevinz000** [comment]
I /believe/ it's fixed.
