### ISSUE TITLE
Freon frozen things with animations are faster and desynced

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25874]
A frozen airlock will open rapidly multiple times. A frozen security camera will be rotating constantly.

**Comment by Iamgoofball** [comment]
I feel like this is a BYOND bug, or something out of our control, because I've tried various fixes but it's never worked.

**Comment by Iamgoofball** [comment]
Could you do me a solid @coiax and rig up some code to freon an airlock and then export the icon it produces to a DMI for analysis?
