### ISSUE TITLE
Mining Boots can store two knives

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#25872]
Server revision compiled on: 2017-04-02
fb05a4f906226753a9bd611535bfb7e88f263a60 

I was just wandering around and found the Bluespace Shelter ruin. I took the survival knife  and just on a whim I tried to stick it into my boots. Surprisingly, it fit, and I was able to remove both of them with alt-click. I ahelped about it, and apparently this is wrong, so I'm making the issue.

Steps to reproduce: 
1) Get more than one survival knife
2) Put one in your boots
3) Put the others in your boots.

**Comment by Kromgar** [comment]
Dude... you have TWO BOOTS

**Comment by Repukan** [comment]
Whoa shit I've been doing it all wrong.

Brb gotta assault the other miners for more knives

**Comment by RemieRichards** [comment]
the shoe "pocket" inherits from the base ```/pocket```, which has two slots.
Just need to make it have one slot OR decide this is a feature (as mechanically, there's nothing -wrong- here, and you *DO* have two shoes)

**Comment by Cyberboss** [comment]
I'm gonna say this is a feature, you have TWO BOOTS

**Comment by RemieRichards** [comment]
Actually I'm just going to say this is fine, as I've said, mechanically valid, both items are accessible (via drag-drop or from two altclicks)

##FEATURE!
