### ISSUE TITLE
During shuttle transit, diagonal smoothed turfs don't have lighting

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#25882]
![](http://puu.sh/v9bwC/d233aa9058.png)
wow fukc I can't hold all these lightning ISSUSES

**Comment by Cyberboss** [comment]
The issue pile don't stop getting taller

**Comment by Cyberboss** [comment]
@PJB3005

**Comment by ChangelingRain** [comment]
this is not his fault because it didn't happen before; it was one of our changes

**Comment by MrPerson** [comment]
I caused this. I didn't feel like futzing with shuttles at the time.

**Comment by ChangelingRain** [comment]
This has been.. fixed???
