### ISSUE TITLE
Bubblegum  can pull people from the station to lavaland

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#25891]
I used a jaunter to flee bubblegum and suddenly his hand showed up from under me and pulled me back to lavaland WHAT THE FUCK. 

I DIDNT EVEN KNOW HE COULD GRAB PEOPLE. He shouldn't be able to affect the station zlevel

**Comment by ChangelingRain** [comment]
oh my god that's great
his grab can have a delay, depending on targetting, so this is a hell of an edge case, also I'm calling it a feature

**Comment by RemieRichards** [comment]
@ChangelingRain

legitimise it with a feature, if they grab you when you're on another Z it should give a unique message, so people know not to report it as a bug.
