### ISSUE TITLE
AI Floor Bolts broken vs Help Intent

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#25894]
Walk into an AI with help intent selected, the AI swaps position as a player would. This happens regardless of if the AI is anchored or unanchored, and switching back and forth between them has no effect.

**Comment by octareenroon91** [comment]
>team AI exfil

**Comment by Cyberboss** [comment]
The solution is to keep them on harm intent :honk:

**Comment by ChangelingRain** [comment]
Who broke this again aaaaa

**Comment by SpaceManiac** [comment]
@Cyberboss Cannot reproduce, AI starts on harm intent and has no interface to change it.
