### ISSUE TITLE
You can attach pills/patches to IV drips

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#25892]
?!?!?

**Comment by octareenroon91** [comment]
Container

**Comment by octareenroon91** [comment]
Actually hmm

**Comment by Profakos** [comment]
Food too, it is kinda beautiful.

**Comment by SgtxRootbeer** [comment]
An IV of deep-fried braincake.

**Comment by Bawhoppen** [comment]
cigs work still right?

**Comment by Profakos** [comment]
No, because they are not reagent containers, they are masks.

**Comment by PKPenguin321** [comment]
Only they are reagent containers

**Comment by octareenroon91** [comment]
They're not `/obj/item/weapon/reagent_containers` though.

There's no convenient way of distinguishing between beakers and IVs though.

**Comment by PKPenguin321** [comment]
didnt we make flags for this kind of thing? OPEN_CONTAINER or something?

**Comment by octareenroon91** [comment]
Blood packs aren't OPENCONTAINER though

**Comment by Jalleo** [comment]
its old code there are going to be issues like this.

**Comment by octareenroon91** [comment]
Are IV drips really that oldcode?

**Comment by PKPenguin321** [comment]
Like two or three years old

**Comment by Jalleo** [comment]
It was added by paprika a lot of things were added before and after then which may or may not have had considerations for this code.
