### ISSUE TITLE
Bioterror Spray Gun sprays self when clicking belt item

### ISSUE THREAD

**Issue by Davidj361** [tgstation/tgstation#25899]
I was playing war/OPs and I bought the Bioterror bundle. I was using that syndie belt as well that you grab from the locker. I tried to place the spray gun into my syndie belt and sprayed myself which killed me. Which hilariously led to me accidentally exploding myself I think while I was ahelping the admin about what happened and the typing might have accidentally pressed the yes button.

Steps to Reproduce:
1. Wear a belt storage item on your belt slot.
2. Have the bioterror spray gun in your hand with the active hand set to it.
3. Click your belt storage item.

Video: https://youtu.be/PEQYLEfDn1E

In my opinion, you should not spray yourself when you click your belt item, and I do not see any reason why this feature should be enabled for anything at all.

**Comment by Bawhoppen** [comment]
Is this the round where we won anyways without you being respawned?
