### ISSUE TITLE
Simple bots can be frozen

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#25900]
![what the fuck goofball](https://i.gyazo.com/3ffff4a91dd6bdde0307d97f90891a91.png)
revert freon
yes that IS beepsky.

**Comment by XDTM** [comment]
So what's the issue, they're mobs

**Comment by xxalpha** [comment]
How is this a bug

**Comment by BeeSting12** [comment]
yes revert freon but no i dont think this is a bug

**Comment by Kromgar** [comment]
I don't think we can revert freon we can't "Definitively prove" freon is crashing the server when it just conveniently happens everytime massive amounts of freon get released

**Comment by Cyberboss** [comment]
Not a bug @lzimann
