### ISSUE TITLE
bottle of chaos no longer has any of its overlays like turning everyone into demons or the blood red filter

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#25903]
I CANT REND AND TEAR WHEN IM CUTTING UP CLOWNS.

4/5/2017 9:46am est bagil

**Comment by KorPhaeron** [comment]
@MrPerson @Cyberboss @PJB3005 

Only people I know who touch overlays and color things regularly

**Comment by PJB3005** [comment]
No fucking clue

**Comment by KorPhaeron** [comment]
To be clearer than the OP hallucinations aren't working, and client.color isn't working

**Comment by Kromgar** [comment]
I blame Cyberboss

**Comment by MrPerson** [comment]
Probably cyberboss if other client.color stuff is still working.

**Comment by Kromgar** [comment]
@Cyberboss #fixyourshit

**Comment by Kromgar** [comment]
@KorPhaeron this seems to have been fixed very recently within the past week or so

**Comment by Kromgar** [comment]
@KorPhaeron so this has been fixed slightly.  Everyone turns into demons again but the blood red filter still does not show.

**Comment by AnturK** [comment]
Demon visual not showing was named argument problem. Not sure about the color filters, i'll take a look.
