### ISSUE TITLE
Losing off-hand with twohanded weapons doesn't make you drop it

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#25904]
Reproduction;
Have chainsaw / fireaxe / ect in left hand
Lose right arm
Continue dual wielding weapon

**Comment by Qbopper** [comment]
If you've lost an arm BEFORE dual wielding, can you still dual wield? Or is it only what's reported here?

**Comment by ShizCalev** [comment]
No you can't. If you try to pick up a twohanded weapon with only one hand you'll get the message 

"<span class='notice'>[src] is too cumbersome to carry in one hand!</span>"

**Comment by Kromgar** [comment]
The chaos in a bottle chainsaw is specialll

**Comment by Haevacht** [comment]
Looking into it. Looks like it's going to be annoying, but looking into it all the same.

Kromgar, so that chainsaw should stay in your hand regardless of dismemberment?

**Comment by Kromgar** [comment]
@Haevacht Yep. It's called The Great Communicator and i'm pretty sure its nodrop and it has always been able to be wielded even if one of your arms get cut off. Its no a chainsaw arm either

**Comment by Haevacht** [comment]
While attempting to actually test this, you have to be stunimmune for this to even happen.
Otherwise you drop your weapon due to the stun of losing an arm.

PR soon though.

**Comment by Haevacht** [comment]
It's turned into blizzard soonTM. But it's being turned into a sort of feature, because i can't check it in the normal places, it checks when you attack with it now, so you get one last hit before dropping it.
