### ISSUE TITLE
Plasmamen are dying while being cloned

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25921]
I deliberately changed this in my cloning PR, the cloning pod is supposed to be an "air neutral" environment, not interacting with the outside air (because they're floating in clonebrine).

But it's still happening, I must have missed something.

**Comment by Jalleo** [comment]
How do they die?

**Comment by coiax** [comment]
Interaction with the oxygen in the atmosphere causes them to catch fire, even when immersed in liquid. They then burn to death.

**Comment by Tacolizard** [comment]
this might be intentional, but has been known for a while. It's not a bug

**Comment by Tacolizard** [comment]
Even if they could be cloned properly, their clone wouldn't have a suit when the cloning finished so they would burn.

**Comment by coiax** [comment]
It is a bug, they are not supposed to catch fire until the completion of their cloning.

**Comment by Davidj361** [comment]
Just tested this, they catch on fire during cloning.
