### ISSUE TITLE
Toggle darknes hides the SM's energy indicator

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#25928]

**Comment by Kromgar** [comment]
Same with cloning pods timer... which is fucking dark blue and barely visible

**Comment by Tokiko1** [comment]
Also applies to the anomaly timers.

**Comment by MrStonedOne** [comment]
So i have a better fix for darkness being how it is.

You can now make all of darkness go away via the use of a planemaster, this would avoid the invisibility hack.
