### ISSUE TITLE
Abductor Console teleporting people to God knows where

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#25933]
https://github.com/tgstation/tgstation/blob/9feab253b8c4c47283fe16bbd1df11b9d8c0ddb5/code/game/gamemodes/miniantags/abduction/machinery/experiment.dm#L216

Probably due to the arrivals shuttle being able to move, gives them something similar to that of the previous "assistant traitors" bug where it appears they're at arrivals but not really.

**Comment by Jalleo** [comment]
Has this been tested yet to see if it works or not?

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm not sure what you mean by that @jalleo , sorry.

**Comment by Jalleo** [comment]
Has it actually occured that people did not end up on the arrival shuttle?

**Comment by ExcessiveUseOfCobblestone** [comment]
yes people teleport into god knows where, as my title suggests

**Comment by ExcessiveUseOfCobblestone** [comment]
I think this issue has since been fixed as other shuttle-related bugs were fixed @KorPhaeron @optimumtact
