### ISSUE TITLE
Light updates really slow when your FPS is set high

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#25955]
I guess it updates based on fps, so if i set my fps higher than normal then flashlights are useless while moving.

with FPS set to 100, it can take several seconds for lights to update

**Comment by ShadowDeath6** [comment]
That's what you get for using a good computer that can handle >12 fps

**Comment by duncathan** [comment]
the human eye can only process images at a rate of 11 fps

**Comment by MrStonedOne** [comment]
No, lighting updates should still be based on server tick rate.

This is might be a byond bug with it splitting/chunking updates across multiple ticks/packets

**Comment by Tacolizard** [comment]
yeah, i tested this again the next day and the problem didn't appear. I guess i was just lagging hard
