### ISSUE TITLE
Drones can't weld airlocks

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#25952]
I know you're thinking: "Why would a drone need to weld something shut?"

The answer: Deconstructing airlocks. And not all of us can afford RCDs, Dr Moneybags

**Comment by octareenroon91** [comment]
Even using the intent verb seems not to work.

**Comment by Repukan** [comment]
Feature

Fuck you drone shitters

**Comment by Iatots** [comment]
#25292 duplicate
