### ISSUE TITLE
It's still possible to explosion dodge by running into the explosion

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25971]
Just saw an engineer sidestep a devestation range supermatter explosion.

Server revision compiled on: 2017-04-07
e658b32b4922274aca4fa0ffdbf21449d425ba6f

**Comment by Cyberboss** [comment]
fuck me

**Comment by Robustin** [comment]
Yea I saw a nukeop do it too when I maxcap'd em. They ran to the edge of the room and then ran back into the blast radius unharmed. 

Bring back oldsplosions!

**Comment by kevinz000** [comment]
@Robustin only if i get to lower maxcap :^)
