### ISSUE TITLE
Fueling Station holodeck template explodes itself??

### ISSUE THREAD

**Issue by Cheridan** [tgstation/tgstation#25972]
![mij0x82](https://cloud.githubusercontent.com/assets/3827314/24806320/1a658428-1b7a-11e7-813e-fb77859b4056.png)

Basically, someone blew up the holodeck with the refuelling station but it ALSO blew up the template on z2. wtf?

**Comment by PKPenguin321** [comment]
The boom is too big

**Comment by Cyberboss** [comment]
I literally can't even...

**Comment by Cyberboss** [comment]
Related #25996

**Comment by AnturK** [comment]
I'll take a look

**Comment by octareenroon91** [comment]
````
(E) (C) (M) atmos_adjacent_turfs = /list (8) 
the floor = 1 
the lush grass = 1 
the lush grass = 1 
the floor = 1 
the floor = 1 
the lush grass = 1 
the floor = 1 
the lush grass = 1
````
