### ISSUE TITLE
Holodeck aint working

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#25996]
How to reproduce:

1) Go to Delta (optional haven't tested it elsewhere)

2) Try to select a setting

3) Fucking nothing

**Comment by Robustin** [comment]
NOW MY JUMPSUIT SLOT IS A FUCKING QUIETUS MECH WHAT DID YOU DO

**Comment by Tokiko1** [comment]
I see this happening occasionally on other stations too.

Also yeah, the deck is horribly broken right now. Sometimes people get (improperly) deleted along with the holo items, sometimes people and their held items get copied or might even become part of the template.

**Comment by optimumtact** [comment]
More like a fix

**Comment by kevinz000** [comment]
@Cyberboss

**Comment by Cyberboss** [comment]
i have no idea man
