### ISSUE TITLE
Can't transition z-levels if on lattice

### ISSUE THREAD

**Issue by uraniummeltdown** [tgstation/tgstation#25999]
So I was a drone drifiting in space and building lattices and I came across the DJ Station. I built a lattice with metal rods to it but when I tried to move from station z-level to the DJ Station z-level I couldn't transition, there was an invisible wall. Not sure if a bug but it's weird and doesn't make sense

**Comment by Cyberboss** [comment]
We should ban lattice when it gets too close to the map transition edge tbh

**Comment by RemieRichards** [comment]
how on earth does this even happen.
lattices are structure, they have nothing to do with map transitions...

**Comment by coiax** [comment]
Is this reproducable?

**Comment by Razharas** [comment]
Nothing in transition code ever makes turfs dense
And lattices arent even turf code

**Comment by uraniummeltdown** [comment]
By invisible wall I mean, you can't transition. Just like on Lavaland if you go to the edge of the map there is a black border, you can't transition to another z-level from lavaland though. I kept laying down lattice to the edge of station z-level, if I latticed all the way to the edge I could not transition, but if the last few tiles didn't have a lattice and were just empty space tiles I could transition to the DJ Station z-level just fine

**Comment by xxalpha** [comment]
Transitions should be areas.

**Comment by Razharas** [comment]
Transition have no use of areas because the place to transition is calculated per-turf at setup for less cpu usage afterwards

**Comment by RemieRichards** [comment]
```
/turf/proc/ReplaceWithLattice()
	ChangeTurf(baseturf)
	new /obj/structure/lattice(locate(x, y, z))
```

You SHITBUTT, the ```destination_[x,y,z]``` variables are being wiped by the turf being replaced with just another blank space turf.

**Comment by RemieRichards** [comment]
Why is that ```ChangeTurf()``` even there? for example if you were to ```ReplaceWithLattice()``` some lavaland tiles, they'd suddenly turn to lava for no reason.

**Comment by RemieRichards** [comment]
I'm not in love with the idea of them being areas, but they almost certainly shouldn't be turfcode.
