### ISSUE TITLE
My UI gets fucked when I swap out my jumpsuit

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#25997]
How to reproduce:

- Swap out jumpsuit

- Suddenly the background box for the jumpsuit is now a portion of an R_wall

- Wat

http://imgur.com/a/vnBIK

**Comment by TalkingCactus** [comment]
If this is your private test server, clean compile in Dream Maker after closing Dream Daemon and Dream Seeker.

**Comment by PKPenguin321** [comment]
Also try clearing your byond cache/updating byond/clean installing byobd

**Comment by Kromgar** [comment]
Clear your cache this shit happened to me delete the entire cache folder

**Comment by lzimann** [comment]
Clearing your cache will do, if I'm not mistaken this is a byond issue and nothing we can do.

**Comment by Robustin** [comment]
This is on Bagil, ill close it if I dont see it reproduce soon

**Comment by francinum** [comment]
Byond issue.

**Comment by Robustin** [comment]
Haven't seen it again since I cleared cache so closing this.
