### ISSUE TITLE
It's possible to deafen GODMODE dummy humans with flashbangs

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#25990]
They took ear damage, which never healed, and ignored all attempts at healing with chemicals. Maybe something's not checking for GODMODE?

**Comment by XDTM** [comment]
The never-healing issue can happen without godmode, usually seen with mech clusterbangs

**Comment by kevinz000** [comment]
ic issue dont nerf flashbangs kkthx

**Comment by Iatots** [comment]
Radiation doesn't care about godmode either.
It seems like god mode just applies the heal effect every tick or two, meaning that with a bad radiation roll your DNA blocks get fucked with.

**Comment by timothymtorres** [comment]
The relevant code for this issue:

https://github.com/tgstation/tgstation/blob/55b92786dcf0f9c5172efd111a6ecbf83ec0dae2/code/game/objects/items/grenades/flashbang.dm#L9-L42

https://github.com/tgstation/tgstation/blob/12bef0e39cfb68294f55e8b9d7de61efc3c1b3a0/code/modules/mob/living/carbon/carbon_defense.dm#L580-L606

https://github.com/tgstation/tgstation/blob/55b92786dcf0f9c5172efd111a6ecbf83ec0dae2/code/modules/surgery/organs/ears.dm#L56-L58

To fix this just change `adjustEarDamage` with the following check and it should be fixed.

```
if(owner.status_flags & owner.GODMODE)
  return FALSE
```
