### ISSUE TITLE
Space is completely black and you can see in critical.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#25993]
Might need reproducing, could've just been a one time thing for me.

EDIT: AND WELDER HELMETS

**Comment by BeeSting12** [comment]
huh relogging helped? i dont know anymore

**Comment by BeeSting12** [comment]
idk it looks to be fixed but it happens sometimes randomly

**Comment by Davidj361** [comment]
I had the same thing happen to me when I was a syndie medborg, and also a syndie assault borg complained about it too. It happened before the wizard started using spells I think, or maybe after. There were a lot of antags that round.

**Comment by Tacolizard** [comment]
Space turning black was a symptom of having an outdated directx sdk. it may be unrelated, but it might be good to try to install the latest directx sdk (june 2010) and updating BYOND

**Comment by BeeSting12** [comment]
I'm no longer experiencing this issue and haven't been for a while. I'll make a new bug report if anything similar pops up again.
