### ISSUE TITLE
Nar'Sie cult runes disappearing randomly or going 2x the size

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#25995]
Happens after using them, they get twice as big taking up multiple tiles or disappear altogether, you can still click them though

**Comment by ChangelingRain** [comment]
@Cyberboss

**Comment by Robustin** [comment]
Runes were massive or invisible

People were growing to 2x+ their size as well

I also saw the RD lying flat on the ground but able to move/drag/attack/interact like he was standing up

RED ALERT

**Comment by XDTM** [comment]
Wasn't the point of a freeze to avoid making new bugs

**Comment by Repukan** [comment]
Saw this today

Weirdly enough you can use runes if you click the tile they're in

**Comment by Jalleo** [comment]
@XDTM because refactoring isnt perfect. If it was then we wont be talking about it. Also lots of code that interacts with each other weirdly.
