### ISSUE TITLE
The transit tube pod on Delta Station seems to absorb air into itself

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26004]
By about 20 minutes into the shift, the pod is red level overpressured for a human, and there's no air in the Engineering side of the pod entry.

**Comment by Tokiko1** [comment]
I've seen this happen on meta aswell.

**Comment by BeeSting12** [comment]
Possibly the cause of #23556

**Comment by coiax** [comment]
Yes, this is a dupe.
