### ISSUE TITLE
Holodeck bees seem to have the ability to make ALL limbs (including the chest???) to drop off a person

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26003]
Seen this bug twice:

Person is stung by holodeck bees, and loses all of their limbs, including the chest.

This is Braxton Cherry!
He is wearing   a grey jumpsuit.
He has   a satchel on his back.
He has   PDA-Braxton Cherry (Assistant) about his waist.
He is wearing   some black shoes on his feet.
He has   a radio headset on his ears.
He is wearing   Braxton Cherry's ID Card (Assistant).
His head is missing!
His chest is missing!
His left arm is missing!
His right arm is missing!
His left leg is missing!
His right leg is missing!
He doesn't seem all there.

**Comment by RemieRichards** [comment]
What even.
Does it like, dismantle the person?

Also I just noticed holodeck bees are the random /toxin reagent ones, meaning they can give people skewium, god help us.

**Comment by coiax** [comment]
No limbs are dropped, but that's the message on examine. The first time it happened, they were naked, so all you could see was a bit of injury overlay. Later, after I made measures to podclone them, all of their limbs apart from their head reappeared.

**Comment by RemieRichards** [comment]
would need to see the person in VV tbh, the would probably be something weirdly obvious (species limb ids, perhaps)

**Comment by Tokiko1** [comment]
I had this happen to me too, though it happened on the emag simulation that spawns the armors and weapons. Just before deleting, it copied my mob, complete with all items too.

**Comment by coiax** [comment]
Maybe this is not to do with holodeck bees, and something to do with the holodeck... changing... modes.

Oh god, this is @Cyberboss' qdel contents operating on the holodeck!

**Comment by AnturK** [comment]
Sigh, i'll take a look since i'm already touching this

**Comment by Cyberboss** [comment]
That shouldn't be merged though!

**Comment by AnturK** [comment]
Can't see anything obvious that would delete these, and the area mismatch should only happen with the area with lowest x/y (refueling station right now) so not sure what's causing this one.

**Comment by FantasticFwoosh** [comment]
Maybe its the venom the bees are making, something attached to the bees because its their innate type (but bees don't dissapear when they leave the simulation)

**Comment by Kylerace** [comment]
cannot reproduce this in the far future of 2021, i cant get bone hurting juice (the best suspect i have for what the bees could be doing) to cause limbs to fall off and if it was somehow related to the holodeck changing programs the holodeck now uses map templates and not area_copy()

**Comment by coiax** [comment]
RIP mystery bee issue.
