### ISSUE TITLE
That's some combat boots

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#26008]
>That's some combat boots.
High speed, low drag combat boots.
They are a normal-sized item.
Your the combat boots's storage opens when dragged to yourself.
Your the combat boots can store 2 items.
Your the combat boots can store items that are small or smaller.
You can quickly remove an item from your the combat boots using Alt-Click.
Adding or Removing items from your the combat boots makes no noise.

Awful description bloat, and practically every line has butchered grammar

**Comment by RemieRichards** [comment]
1. it's autotext what do you expect.
2. just needs the [src] swapping for [name]
3. It's not bloat, there's literally no way of knowing this without code diving at the moment, and this was required to legitimise a bug.

**Comment by PKPenguin321** [comment]
well fix the grammar at least, my the combat boots shouldnt be prefixed with `the` every time

**Comment by RemieRichards** [comment]
literally read point 2.

**Comment by Bawhoppen** [comment]
it has achieved meme status

we need to add more just like how we did with the KA

**Comment by Armhulen** [comment]
Yeah that desc is pretty tacticool

**Comment by SpaceManiac** [comment]
The grammar was fixed in a50ca185a1c5c31c5fab5d9f1153815f7611c166
