### ISSUE TITLE
Top-right tile of ss13 sign on box has random description

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#26000]
![](http://i.imgur.com/eMy10j6.png)

**Comment by WJohn** [comment]
how do you find these kinds of things

**Comment by Qbopper** [comment]
definitely an easy fix

**Comment by francinum** [comment]
It's present on all maps.

**Comment by JJRcop** [comment]
get

**Comment by Penguaro** [comment]
@francinum Offhand do you know if Cerestation has the sign? I did a quick glance and didn't see it anywhere.

**Comment by Qbopper** [comment]
http://i.imgur.com/dY3CdMv.png

still an issue on metastation, at the very least

**Comment by Penguaro** [comment]
What server were you on did you have the revision information by chance?

**Comment by Penguaro** [comment]
@Qbopper What server were you on do you have the revision information by chance?

**Comment by Qbopper** [comment]
It was on sybil, 5 hours ago

don't know what to tell you - examining the tiles on meta retains the issue

**Comment by Penguaro** [comment]
@Qbopper Ah Important detail.... There are _two_ of those signs on MetaStation... The forward one was and still is fixed. The second Aft sign was not fixed.

**Comment by Qbopper** [comment]
weird, it must have snuck into the boxstation sign's tile descriptions and then been copy pasted over? not sure how else it could be explained
