### ISSUE TITLE
Airlock wires generating incorrectly, or not displaying all wires.

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#26015]
![](http://i.imgur.com/g4YuzZF.png)
No wire assigned to bolts or primary power.

**Comment by octareenroon91** [comment]
I'm seeing vendors with four wires, none are contraband.

**Comment by xxalpha** [comment]
@Cyberboss this may have been caused by your global variable change

**Comment by francinum** [comment]
![](http://i.imgur.com/8bRo5j5.png)
The wires appear to not be generating period.

**Comment by octareenroon91** [comment]
#25325 ?

**Comment by francinum** [comment]
That's the one, yes.
