### ISSUE TITLE
Syndicate Bomb wire issue , unable to pry out the bomb core

### ISSUE THREAD

**Issue by Lexorion** [tgstation/tgstation#26017]
## Can't pry out bomb core despite cutting "all" visible wires
Apparently only some wires show up. During a round it only gave me 3 wires, later when I tested it the bomb had 4. Despite cutting all wires it keeps giving you this message (see picture)
![](http://i.imgur.com/5baOPny.png)
It used to have more wires for sure.
**How to reproduce:** Get a syndi bomb, cut all the wires and try to use a crowbar on it

**Comment by francinum** [comment]
Likely related to issue #26015

**Comment by xxalpha** [comment]
@Cyberboss this may have been caused by your global variable change

**Comment by lzimann** [comment]
Can't reproduce this, wires are working fine.
