### ISSUE TITLE
Syndicate EMP implant doesn't short circuit stunbatons

### ISSUE THREAD

**Issue by PLISKINN** [tgstation/tgstation#26016]
Yeah, shouldn't it at least kill the battery in the baton, instead of ignoring it in general

**Comment by PKPenguin321** [comment]
It does, it's just that it only removes 10% of the baton charge

**Comment by Kromgar** [comment]
>Emp only removes 10% of a baton charge

WHAT THE FUCK

**Comment by GunHog** [comment]
https://github.com/tgstation/tgstation/blob/9e1ef0ffe2a7d955a40fd2d83382785353a29cb4/code/game/objects/items/weapons/stunbaton.dm#L172

https://github.com/tgstation/tgstation/blob/9feab253b8c4c47283fe16bbd1df11b9d8c0ddb5/code/modules/power/cell.dm#L135

As you can see here, EMP is simply not as strong against EMP as they should be.

**Comment by Bawhoppen** [comment]
baton still best weapon

**Comment by kevinz000** [comment]
not a fucking bug.

**Comment by Dorsisdwarf** [comment]
Closed because this is an intended feature and has been for ages
