### ISSUE TITLE
Player controlled crab grammar issue

### ISSUE THREAD

**Issue by Qbopper** [tgstation/tgstation#26014]
"[crab name] pinches the [object]", no period at the end.

![crab](http://i.imgur.com/DEteCp5.png)

**Comment by ExcessiveUseOfCobblestone** [comment]
wtf where is this located

**Comment by Qbopper** [comment]
right? I figured I could fix it myself, but in the crab code it just has a var for the "pinches" section of the sentence, it must handle the object that's being clicked on in another file

**Comment by Jordie0608** [comment]
https://github.com/tgstation/tgstation/blob/master/code/game/objects/obj_defense.dm#L103
and
https://github.com/tgstation/tgstation/blob/master/code/game/mecha/mecha_defense.dm#L75

**Comment by ExcessiveUseOfCobblestone** [comment]
>>>>>>>>>>>>>>>>> MECHA DEFENSE
