### ISSUE TITLE
Beards are gone - facial hair prefererence missing

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#26010]
How to reproduce:

1) Have a beard

2) Join the game

3) No beard

You can still get the beard back at a mirror though.

**Comment by BeeSting12** [comment]
check your character setup screen. i had that glitch earlier and i looked and for some reason it was set to something else

**Comment by kevinz000** [comment]
2beard

**Comment by HeddyLamarr** [comment]
It appears that the facial hair features of characters is being replaced with hair styles by some kind of bug. I'm pretty sure this happens every time a round restarts.
<img width="53" alt="capture" src="https://cloud.githubusercontent.com/assets/19778176/24836259/84014fe8-1d5a-11e7-9ded-c3681c8b9108.PNG">

**Comment by AnturK** [comment]
Someone probably messed up preferences versioning again.

**Comment by Cyberboss** [comment]
I probably copy pasted something wron gin the globals port.

Why the fuck are those globals

**Comment by Robustin** [comment]
I set my facial hair to FULL BEARD and saved

Reconnect and my facial hair SHORT HAIR 3
