### ISSUE TITLE
A clockwork posibrain that was put into a cyborg shell was bound to an AI

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26022]
I don't know the exact circumstances, but I ended up bound to an AI, losing my cult status, and having whatever meme laws the crew had uploaded to the poor AI that round.

**Comment by FantasticFwoosh** [comment]
Probably something in the code to do with the shell interactions, given that shells can be disconnected from AI's

**Comment by GunHog** [comment]
While testing my AI shell fixes (Not the same thing as a cyborg exoskeleton), I spawned a soul vessel, put my second character in it, then inserted it into a normal, empty borg shell. I had also spawned a normal AI beforehand. The soul vessel became an ordinary, slaved borg. The add_servant_of_ratvar() proc is probably failing to run.

**Comment by coiax** [comment]
@ChangelingRain

**Comment by xxalpha** [comment]
This isn't a bug, unless clockwork posibrains are supposed to be snowflake. Cyborg bodies are what receive laws and are bound (or not) to AIs, not their brains. Losing antagonist status is also intended, since cult silicons were patched out some time ago.

**Comment by coiax** [comment]
Clockwork posibrains are supposed to be snowflake. Putting a clockwork brain in a borg shell is supposed to make it automatically ratvar.

**Comment by ChangelingRain** [comment]
I never actually saw this happen and soul vessels are gonetm
