### ISSUE TITLE
Changelings in a regenerative stasis (ie. FAKEDEATH) still bleed, unlike dead bodies

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26020]

**Comment by coiax** [comment]
You know, the FAKEDEATH flag is bothering me enough with changelings.

What if we just let changelings speak on hivemind when dead, and just kill them when they enter a regenerative stasis? Or are we worried about deadchat abuse?

**Comment by XDTM** [comment]
fakedeath is also used on zombie powder so circumventing it with lings won't solve the bug

**Comment by ChemicalRascal** [comment]
Clearly the easy fix here is to make dead bodies bleed

**Comment by coiax** [comment]
@XDTM except zombie powder doesn't have its own gamemode.

**Comment by Davidj361** [comment]
Why not just make fakedeath not able to see deadchat and see like as if were alive?

**Comment by QualityVan** [comment]
Yeah you can actually check a variety of things to see if a ling is faking it. If it's both in stasis and actually dead, though, none of them will work.
