### ISSUE TITLE
Runtime when I shot a monkey with an instagib rifle

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26034]
[17:20:00] Runtime in damage_procs.dm,16: list index out of bounds
  proc name: apply damage (/mob/living/carbon/apply_damage)
  usr: Braxton Cherry (coiax) (/mob/living/carbon/human)
  usr.loc: The floor (135,132,1) (/turf/open/floor/plasteel/bar)
  src: Coco II (/mob/living/carbon/monkey/punpun)
  src.loc: null
  call stack:
  Coco II (/mob/living/carbon/monkey/punpun): apply damage(200, "fire", "l_leg", 0)
  Coco II (/mob/living/carbon/monkey/punpun): bullet act(the instagib laser (/obj/item/projectile/beam/instakill), "l_leg")
  Coco II (/mob/living/carbon/monkey/punpun): bullet act(the instagib laser (/obj/item/projectile/beam/instakill), "l_leg")
  the instagib laser (/obj/item/projectile/beam/instakill): Bump(Coco II (/mob/living/carbon/monkey/punpun), 1)
  the instagib laser (/obj/item/projectile/beam/instakill): fire(null, null)

**Comment by octareenroon91** [comment]
Weird. `apply_damage` should be acting on the limb before gibbing happens.

**Comment by octareenroon91** [comment]
Replicated.

Also this runtime doesn't happen if the BB is set to `nodamage=1`, which I suppose would be expected.

**Comment by optimumtact** [comment]
it definitely got qdeleted  before the rest of the code was applied.

**Comment by Qustinnus** [comment]
they dont runtime anymore
