### ISSUE TITLE
Chaplain no longer starts with ability to use bible or reskin null rod

### ISSUE THREAD

**Issue by Togopalis** [tgstation/tgstation#26038]
The Chaplain no longer has the ability to use the bible (The book sizzles in your hands) or reskin their null rod from the lobby when the round begins. I have not tried latejoining.

**Comment by AnturK** [comment]
This happened yesterday, forgot to put a issue. Chaplain's mind was missing isholy.

**Comment by lzimann** [comment]
ugh, hold on I'll fix it
