### ISSUE TITLE
Flashing Objects and Missing Textures

### ISSUE THREAD

**Issue by ViperSnake01** [tgstation/tgstation#26047]
On **Box Station**, some doors are blatantly missing textures and an object is flashing over and over again. Another example, which gives an advantage possibly, is **the ability to see your whole screen while something is impairing your vision**. I didn't manage to get a screenshot of this, but things like a Welding Mask wouldn't limit my vision like they normally would; I would be able to see normally. This also happened when I was in crit, as I could see my whole screen and no whiteing out. Again, I did not catch a screenshot of this. But I did get screenshots of the doors missing textures, and a flashing object.
![66217055e8ba4ba5f85cec38f1068260](https://cloud.githubusercontent.com/assets/22404305/24841763/4874ebc8-1d83-11e7-9173-99c36344ee35.gif)
![e036fe45a5cb26a3967f969ba975e965](https://cloud.githubusercontent.com/assets/22404305/24841764/4b54da9c-1d83-11e7-9f71-367620ff3b76.png)
![e458a52c87ee74a593141eb976c1f49c](https://cloud.githubusercontent.com/assets/22404305/24841766/4e5bdef2-1d83-11e7-8437-a5d35dc18165.png)
![10701ca0b6f062998c295053be62e3ff](https://cloud.githubusercontent.com/assets/22404305/24841767/4f800650-1d83-11e7-8b06-3b2f8a0380ac.png)

**EDIT**

I got cloned this round, so I managed to finish catching these weird vision problems.

![2ea5de11fb553b84e5d68ecf1ef77a8c](https://cloud.githubusercontent.com/assets/22404305/24841802/5339f96c-1d84-11e7-88c1-506a4471a7c5.gif)
![8d8e39c888a9a5efc340605d7c950bfd](https://cloud.githubusercontent.com/assets/22404305/24841803/54c617ca-1d84-11e7-939d-7b0660cc2d9e.gif)
![6b3b3c96176c0bc5042458767d04fd10](https://cloud.githubusercontent.com/assets/22404305/24841934/63e7cb92-1d87-11e7-9feb-e6ce1c969675.png)

**EDIT 2** (Last Edit, I swear. These glitches are just getting weirder.)

This is on CereStation now.
![9a110f736865b1ed55b7b4f72e232f90](https://cloud.githubusercontent.com/assets/22404305/24841935/65d07544-1d87-11e7-8710-dc47e9f58e82.png)
![eca7b20835301a5c93aa39bebddabc5d](https://cloud.githubusercontent.com/assets/22404305/24841937/66ae01ac-1d87-11e7-90d3-83dae7cab02f.png)
![35579345008c8072d1162dbd70b2f119](https://cloud.githubusercontent.com/assets/22404305/24841938/6948804a-1d87-11e7-9da8-c6996f49d549.png)
![c919413e3df666fe03bab1f6fa46335f](https://cloud.githubusercontent.com/assets/22404305/24841939/6b50dc70-1d87-11e7-8f21-26e9aaf46853.png)
![8ffa8f0f376edaec0dd5d7def286ad6b](https://cloud.githubusercontent.com/assets/22404305/24841941/6c5d911c-1d87-11e7-8f77-02fa7397f1ea.png)

This is just stupid now.

**Comment by xxalpha** [comment]
This has to be your client's fault somehow.

**Comment by PKPenguin321** [comment]
http://www.byond.com/forum/?post=29715

Clear your byond cache

**Comment by jughu** [comment]
>dunk actionbuttin

**Comment by optimumtact** [comment]
not a bug we can help wiht
