### ISSUE TITLE
Bluespace atmospherics

### ISSUE THREAD

**Issue by octareenroon91** [tgstation/tgstation#26053]
Background:
#26005
#25972

Not the map copy task nor anything else seems to bother to blank var/list/adjacent_turfs in turfs, in the process of copying from Centcom-mapped template to target zone. The adjacent_turfs list thus ends up holding eight rather than four turfs, bleeding gas and temperature back to Z2.

**Comment by AnturK** [comment]
Hmm, it should be calling update adjacent.
