### ISSUE TITLE
somebody added doors to the thunderdome that you can just smash down with weapons and walk out of and get into centcomm through

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#26050]
please remove these doors the separation between the thunderdome and the rest of centcomm must remain absolute

**Comment by octareenroon91** [comment]
You can just walk in or out of the otherwise-indestructible/impenetrable thunderdome area.

**Comment by Shadowlight213** [comment]
it was okand when they did their remake of centcom. I TOLD them it was a bad idea and to remove...

**Comment by octareenroon91** [comment]
The geometry is also wrong: the template is a tile shorter than the Centcom thunderdome on the y-axis.

**Comment by BeeSting12** [comment]
I'll fix it when I get home unless someone else does it first

**Comment by optimumtact** [comment]
not de bug
