### ISSUE TITLE
You cannot pickup chameleon stamps

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26069]
Bought a camo kit, could pick up everything out of the box except the stamp

**Comment by GunHog** [comment]
The click blocker strikes again! https://github.com/tgstation/tgstation/blob/2d5e127eaed8cc20900daeac2ab6ee3e3046840a/code/modules/paperwork/stamps.dm#L81 does not call `..()` in `New()`. I guess you should join the `Initialize()` train and make sure it calls `..()` there.
