### ISSUE TITLE
Using autosurgeon to replace brains

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#26078]
Using autosurgeon with a target's brain results in the brain's player being put in control instead.

That's easily a feature, but the problem with it is that the brain that drops on the floor as a result of the procedure is not the brain of the autosurgeon user, `John Doe's brain` that John Doe can re-enter after ghosting out.

Instead, it's just a playerless `brain` and John Doe has no body to re-enter once his ghost leaves the brain

**Comment by XDTM** [comment]
Does the autosurgeon call Remove on the old organ?

**Comment by Sligneris** [comment]
It doesn't refer to the old organ at all. When it comes to the actual replacement, all is done by just this like

```storedorgan.Insert(user)//insert stored organ into the user```

**Comment by coiax** [comment]
`Insert` calls `Remove` if there's already an organ in the slot.

**Comment by Sligneris** [comment]
Then `Remove` really needs to start giving the removed brain's its owner's identity.

**Comment by PKPenguin321** [comment]
What's replacing brains?
