### ISSUE TITLE
You can't pick coloured shoes in the chameleon shoes menu

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26071]
Where are my black shoes, my brown shoes?

@XDTM

**Comment by Cyberboss** [comment]
Probably another copypasta fail in #25325

**Comment by PKPenguin321** [comment]
no, chameleon items have a hard time listing multiple items that share the same name

**Comment by PKPenguin321** [comment]
well wait actually that might not be the case here, do brown and black shoes share the name `shoes` or not

**Comment by XDTM** [comment]
I think i fixed this a while ago with my chameleon refactor
