### ISSUE TITLE
Scientists don't have the required access to enable the shield wall generators in the xenobiology lab

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#26087]
Server Revision: 8d1ee2267ad7231824b725baffd96daa643cdfc2 

The shield wall generators in xenobiology can't be enabled by the scientist who works there.

**Comment by ExcessiveUseOfCobblestone** [comment]
which map daddio

**Comment by Expletive** [comment]
I have tried them on Meta and Box, and couldn't enable them on either.

**Comment by Sligneris** [comment]
We should really just remove access requirement from the shield generators. Make them work like containment field, where you need specific access to lock them, but only if they're on.

**Comment by GunHog** [comment]
The Xenobio shield generators are "access_teleporter", or in other words: Research Director only.

**Comment by Jalleo** [comment]
Its always been like this

**Comment by BeeSting12** [comment]
I might be able to just make them unlocked roundstart or some shit

**Comment by Jalleo** [comment]
There is a really easy way to do that but balance change and in a feature freeze.

**Comment by Kromgar** [comment]
Uh..... No it has not always been like this. 


I distinctly recall being able to unlock those as a normal xenobiologist.

**Comment by Dorsisdwarf** [comment]
It might have been varedited on a specific map but I remember always having to get the RD to do it and it was a huge pain and I never used them unless centcomm tried to send us aliens. Do scientists get Teleporter access on skeleton crew access? If so that's why

**Comment by GunHog** [comment]
Scientists do not gain tele access on skeleton crew. It is RD only, and has been since 2012. https://github.com/tgstation/tgstation/commit/807c13fa47a8c989dec9c9dba7a040015750ec68 It is possible that a map was var-edited to change this, but the generators themselves have always been teleporter access.

**Comment by BeeSting12** [comment]
If there's a var to make it start unlocked at roundstart then I'll use that one, if not then I'll just varedit the access to xenobiology on all maps.

**Comment by GunHog** [comment]
>I'll just varedit the access to xenobiology on all maps.

And not simply just...edit the item itself?

**Comment by BeeSting12** [comment]
The ones in the teleporter should stay as teleporter access

**Comment by GunHog** [comment]
Make a subtype with Xeno access instead. If not that, then just edit the item. It is not as if the only three people with access (Cap, RD, All-access HoP) would be locked out anyway...

**Comment by BeeSting12** [comment]
When taking a look at the shield generators on meta, there were two access listings, one had xeno and one had teleporter. Looks like the teleporter one overrides the xeno one. Pretty sure it was the mapper's intent to have scientists be able to access it but he never tested it.
