### ISSUE TITLE
Optical Material Scanners are broken

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#26084]
They give a strange pseudo-xray vision.
![bug](https://puu.sh/vgepJ/790b3223f4.jpg)
They probably should just be removed (they've been long obsoleted), they are found on CereStation at cargo.

**Comment by KorPhaeron** [comment]
Nothing broken about this screenshot

**Comment by KorPhaeron** [comment]
They see items through walls. It looks weird but it works

**Comment by PKPenguin321** [comment]
yeah but they didnt even see ore as far as i could tell

**Comment by KorPhaeron** [comment]
Did you use the correct kind of scanner? It's adminspawn right now

**Comment by octareenroon91** [comment]
They don't show turfs like mesons do.
