### ISSUE TITLE
Misuse of Shuffle()

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/tgstation#26098]
A lot of code does this: 
```
shuffle(some_list) //A
...
```
And a lot does this:
```
for(var/a in shuffle(some_list)) //B
    ...
```
or this:
```some_list = shuffle(some_list) //C```

B or C is completely fine as ```shuffle()``` returns the new list.
A however, is wrong, as ```shuffle()``` operates on a copy of the list, not the list itself (there's ```shuffle_inplace()``` for that!)

This means that a lot of things that should be being shuffled (ghost role candidates!, late join DAs!) aren't getting shuffled at all.

Either ```shuffle()``` and ```shuffle_inplace()``` need combining, to prevent this issue occuring in future, or we need to teach people that this proc does NOT act in place (probably with a rename?)

I've known this one for quite a while (2+ years) but never got around to writing it up/fixing it, just noticed it again today.

**Comment by AnturK** [comment]
Oh boy ,there's even a few in antag picking code.

**Comment by RemieRichards** [comment]
yep, I mentioned DAs but there's also the nuke strike teams and things.
it's quite bad.

**Comment by octareenroon91** [comment]
Maybe move to shuffle and shuffle_and_copy ?

**Comment by RemieRichards** [comment]
```shuffle()```, which acts on it inplace (but also returns it, so you can use it as you please) and ```shuffle_copy()``` which shuffles a copy (so the current ```shuffle()```

that sounds good to me.
