### ISSUE TITLE
Observers some times don't get to understand all languages

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation#26093]
Observer
![](https://file.house/qDuF.png)
Their lang vars
![](https://file.house/m0wj.png)

Server revision compiled on: 2017-04-11
The following pull requests are currently test merged:
#26026: '[s] refactors linear phase delta inducer in the MC to penalize subsystems that overrun a tick' by MrStonedOne 

Based off master commit:
363e04d5689ab323473e6a551f320a1f9d56eeee

**Comment by optimumtact** [comment]
@coiax along with the irc memeos

**Comment by optimumtact** [comment]
Haevact made a good point that these could be people observing very early on before the subsystems are initing and getting setup properly

**Comment by RemieRichards** [comment]
Observers should get their omnitongue by setting a callback to ```OnRoundstart``` or something (if the round has already started ```OnRoundstart()``` is just ```InvokeAsync()``` so it'll still cover normal non-early observers)

**Comment by coiax** [comment]
`grant_all_languages` is called in the Initialize() of all observers. I don't know why they would lose their languages...

**Comment by Cyberboss** [comment]
@coiax Initialize of /mob/dead is called ASAP even before SSatoms if you didn't know

**Comment by coiax** [comment]
Well, when feature freeze is over, I'm going to let observers edit their own language comprehension.

**Comment by optimumtact** [comment]
have not seen this in a very long time

**Comment by coiax** [comment]
I haven't seen you in a long time either, @optimumtact :heart:

**Comment by optimumtact** [comment]
hello! hope you're doing well

**Comment by optimumtact** [comment]
also I feel like I was against languages, at least that's what I remember, but they worked out okay, mimichu boop
