### ISSUE TITLE
Photocopying papers doesn't copy stamps

### ISSUE THREAD

**Issue by Davidj361** [tgstation/tgstation#26108]
Photocopying paper doesn't copy over stamps. Just approve this so I can write a PR for it and get this fixed & merged quickly.

**Comment by Jalleo** [comment]
@Davidj361 if you want to make a fix report it and then PR a fix right afterwards. Dont leave it. Also you dont need to issue report to make a fix just PR the fix and say what the fix is for.

**Comment by Davidj361** [comment]
I wanted this to be labelled bug and then make a PR. But I guess I can just make a PR without the issue like you said.
