### ISSUE TITLE
You can see locked door hallucinations through walls

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#26115]
You can see the door bolt lights through walls.

**Comment by XDTM** [comment]
Maybe i didn't set the layer properly

**Comment by Sligneris** [comment]
You can even see locked door hallucinations on doors that aren't closed.

**Comment by Davidj361** [comment]
What does that mean? Aren't you supposed to be hallucinating that the door is locked but it really isn't?

**Comment by Sligneris** [comment]
You are supposed to be hallucinating that the door is locked, but in reality you see it wide open with bolt lights appearing in thin air.
