### ISSUE TITLE
Restarts don't work outside of hard restart 

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#26123]
Read above. I'm not sure if server killing works, though.

**Comment by Jordie0608** [comment]
Need more info; tested all restart methods and they worked.

**Comment by Magikarpet** [comment]
Might be going insane. After a round is delayed short of hard restarts, restarts don't work. @Cyberboss was there that round too. Happened on bagil later on

**Comment by Cyberboss** [comment]
Huh, I'll look into it

**Comment by MrStonedOne** [comment]
Please tell us what verbs were tried.

"restarts" is undescriptive

**Comment by MrStonedOne** [comment]
As in, HOW did you try to restart that failed.

**Comment by Shadowlight213** [comment]
@MrStonedOne I think they mean the End Round Button doesn't work after the round has ended but the restart was delayed.

This is normal though. and has always been the case.

**Comment by Cyberboss** [comment]
End Round != Restart Server

**Comment by Magikarpet** [comment]
It's probably me being dumb, just surprised about the multiple round end buttons not also working, requiring a hard restart instead when an admin delays the round. Probably intended behaviour so i'll just close this up.
