### ISSUE TITLE
Beards seem to be changing at random?

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#26127]
Everytime i spawn my beard is different

**Comment by Cyberboss** [comment]
GLOB

**Comment by Sligneris** [comment]
>\> Having a beard
Ew

**Comment by AnturK** [comment]
If you changed your beard prefs when sanitize was broken you need to change and save it again.

**Comment by Kromgar** [comment]
I never changed my prefs in like 3 months
