### ISSUE TITLE
Admin logs on a ckey read from said mob's specific status, rather than all logs.

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#26124]
This means that when looking at a ghost's logs through the player panel, it only shows ghost death logs, if you examine bodies it shows body combat logs, etc.

**Comment by PKPenguin321** [comment]
critical priority please this is a bitch

**Comment by Jordie0608** [comment]
I just testing getting killed and ghosting and my logs were copied; are there more details to this where the logs weren't?

**Comment by lzimann** [comment]
It's when cloning that it doesn't copy. I've been meaning to change the whole logging to be ckey based for a while now.
