### ISSUE TITLE
synth race and military synth race no longer have skin and they cant restore it with synthflesh patches

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26149]
when they should be able to have and repair their skin to look like humans but no matter what theyre just endoskeletons fuck

**Comment by optimumtact** [comment]
@RemieRichards

**Comment by RemieRichards** [comment]
I haven't touched synths in a long time, I know Phil was the last to change them visually, besides Kor breaking all robot arms that is.

**Comment by Militaires** [comment]
@remierichards

more info: i found that being a normal human and using magic mirror to make yourself synth will let you have skin but if you VV set species synth then everything is fucked

**Comment by RemieRichards** [comment]
as I said, tag the people who broke it, not me.

**Comment by Militaires** [comment]
@RemieRichards how do i know who broke it when 10 people can change one file in the course of some weeks

**Comment by RemieRichards** [comment]
@Militaires Perhaps if you read what I wrote.
"as I said"

You'll be like "Oh, she said something?" and then perhaps you'd scroll up just a tiny bit further, and see where I said Phil and Kor did.

Learn to read.

**Comment by Militaires** [comment]
@remierichards i did read that and you said.

>I haven't touched synths in a long time, I know **Phil was the last to change them visually, besides Kor breaking all robot arms that is.**

how can you be so sure that it's phil who broke them cause he was the last to change them 

>as I said, tag the people who broke it, not me.

how can i be omniscient and know exactly the person who broke it just because phil is the last one to change them does not imply that he's the one who broke them

it's like you're ACTIVELY trying to be a condescending dick 24/7 remie jesus christ.

**Comment by RemieRichards** [comment]
No, once again you can't read.
"besides Kor"

I said BOTH of them were the last two people to touch it, where as my last changes to it are FAR older, the odds are WAY in favour of it being on of those two, I'm not "so sure that it's phil" because I didn't say explicitly that was it was phil, just that he's one of TWO prime candidates.
Two people who heavily altered that code, far more recently that I did? No shit it's more likely to be one of those two. no omniscience required.

Once again I say, "Learn to read"

**Comment by Militaires** [comment]
absolutely disgusting

@RemieRichards here's the list of people who changed them after you complete with their changes.

Cruix: applied a fix that supposedly stopped them from being invisible when becoming a different species. **this is after phil's pr too!**

Firecage: in their split the species file pr they changed various |= to -= which could've broken things.

Incoming: Changed code regarding synths setting correct gender and synth jumpsuits

and many other prs changing synth interactions and shit i cant be bothered to look up

obviously more people changed synths than you thought and you should've read

> how do i know who broke it when 10 people can change one file in the course of some weeks

if i were a condescending dick i'd tell you "learn to read111111111111111111"

also in fact i never saw any major PR changing synths done by kor? really makes you :thinking:

**Comment by RemieRichards** [comment]
/shrug

whatever fucko.

**Comment by Militaires** [comment]
@RemieRichards 
on the news: person acts like condescending dick and tries to make me look bad on prs that may or may not exist, resorts to insulting me when proven wrong...

:thinking: 

i mean it's better than the autistic fits you have on irc so good luck not letting one of those out :1st_place_medal: 

more on 11

**Comment by RemieRichards** [comment]
I mean sure, you sure showed me up by pointing out how there were MORE people than 2 who edited it after me, further decreasing the validity of pinging me, which some how definitely doesn't prove you're an idiot.

totally.

**Comment by Militaires** [comment]
@RemieRichards 

> @RemieRichards how do i know who broke it when 10 people can change one file in the course of some weeks

i wasnt pinging you because i think you broke it im replying to you only at this point because of your response to that ^^^^^^^^^^^^^^^^^^^^^^^^^

:thinking:

**Comment by RemieRichards** [comment]
considering that isn't where you first pinged me, sure ...???

**Comment by Militaires** [comment]
@RemieRichards 

yeah i first pinged you to tell you more info about the issue then you replied with pure garbage so i replied to THAT pure garbage how do i even need to explain this to you

work on your shitty behaviour

**Comment by RemieRichards** [comment]
No thanks.

**Comment by Militaires** [comment]
/shrug

whatever fucko.

**Comment by kriskog** [comment]
Synths have skin now
