### ISSUE TITLE
flashlight eyes dont emit light

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26145]
self explanatory

**Comment by XDTM** [comment]
Even if implanted?

**Comment by Militaires** [comment]
@xdtm yeah i implanted them into me and ask @GunHog

**Comment by GunHog** [comment]
Yes, we did the "Human Flashlight" gimmick where I brutally chop off all his limbs with a circular saw, stick a red air tank on his back as a 'battery', then gouge out his eyes and replace them with flashlight eyes. Sadly, he emitted no light. I even put a firefighter's helmet on him, and only its light registered.
