### ISSUE TITLE
sm delaminates but not into an SM singulo just a normal one

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26147]
when it should spawn and then eat the SM and become supermatter

**Comment by optimumtact** [comment]
This is based on the gases present afaik
@Tokiko1

**Comment by PKPenguin321** [comment]
not a bug intentionally not a supermatter singulo because reasons

**Comment by Militaires** [comment]
@PKPenguin321 wasnt it supposed to suck the sm when it spawns tho

**Comment by PKPenguin321** [comment]
no i think they left it because they wanted SM singulo to be limited to multi SM setups for some reason i think its stupid but its not a bug regardless

**Comment by Tokiko1** [comment]
@optimumtact 
This does sound like a bug. If you get it to delaminate into a singulo then it should always eat the supermatter too.
