### ISSUE TITLE
Beepsky can spacewalk while drifting.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#26141]
If beepsky is in space and is drifting, he can still move around, trying to path his way back to the station, even while drifting.

You cannot outrun the law, even in space.

**Comment by Repukan** [comment]
Feature.

He doesn't have wheels, he floats

**Comment by GunHog** [comment]
Feature!

**Comment by Militaires** [comment]
@repukan he does have wheels dude, here are the oldsprites tg missed during its inception

https://www.youtube.com/watch?v=9bys_q25_Dw

**Comment by Daturix** [comment]
Asked this question to coderbus myself, it is a FEATURE.

**Comment by optimumtact** [comment]
not a bug, it stops pathing lag storm
