### ISSUE TITLE
Badass Syndrone not actually Syndicate

### ISSUE THREAD

**Issue by extramrdo** [tgstation/tgstation#26142]
End of round shenanigans with several syndrone printers set up. Purchased a gun from the provided uplink, and the implant check failed, thus leaving the Syndrone unable to fire the weapon with the Syndicate pin.

I expected the Syndicate Drone to be able to fire Syndicate weapons. However, the Syndrone lacks the Syndicate implant and thus fails the Syndicate Firing Pin's checks. The consequence is that a Syndrone without guns isn't badass at all.

> This is   Badass Syndrone (461)!
> It has   a donksoft SMG in its left hand.
> It is holding   a station bounced radio in its internal storage.
> It is wearing   an elite syndicate hardsuit helmet on its head.
> Its display is glowing red!
> Its screws are very loose!
> *---------*
> 
> 
>   That's a donksoft SMG.
> A bullpup two-round burst toy SMG, designated 'C-20r'. Ages 8 and up.
> It is a normal-sized item.
> It has the syndicate firing pin installed.
> Has 20 rounds remaining.
> 
> IMPLANT CHECK FAILED.
> IMPLANT CHECK FAILED.

Server revision compiled on: 2017-04-11
The following pull requests are currently test merged:
#26039 
#26044 
#26902 
#26092 

Based off master commit:
6e720cf807cf64f544b212ace6bb31fbdf426e03 

On Sybil, about 5:15PM EST, 04/12/2017

**Comment by BeeSting12** [comment]
Kor closed my issue report about this a while back saying that @AnturK fixed it.

**Comment by AnturK** [comment]
Hmm.
