### ISSUE TITLE
if you load a stunbaton with a plasma-fouled 100% battery it wont turn on at all even though it's charged

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26151]
battery is 100% full but it was injected with plasma to be broken and dangerous

**Comment by Davidj361** [comment]
Should it explode too when you turn it on?

**Comment by Militaires** [comment]
@davidj361 should explode when you stun but it doesnt even turn on

**Comment by Davidj361** [comment]
I guess a different issue will be made for that later then?

**Comment by Militaires** [comment]
only gnome knows.

**Comment by XDTM** [comment]
Couldn't reproduce, i put a full powercell with plasma, and it both turned on and exploded on stun.

**Comment by Militaires** [comment]
will close per @XDTM 's observation then
