### ISSUE TITLE
Meta and boxstation prison farms offer no way to provide nutrition for plants.

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26158]
i just want to be a farmer king of my land and there's no vendors to get robust nutrient from to feed my precious weed

**Comment by octareenroon91** [comment]
Could try composting whatever's in the food vendors directly into your little plot.

There's still a biogenerator there right?

**Comment by Militaires** [comment]
@octareenroon91 yeah but that's bound to run out and when it does you're fucked

**Comment by Militaires** [comment]
i've tried it before and man it's shitty just have a real vendor

**Comment by optimumtact** [comment]
map issue thread

**Comment by optimumtact** [comment]
scratch that didn't notice it was for box

**Comment by PKPenguin321** [comment]
not a bug, use the bio thingy and print nutrients

**Comment by Militaires** [comment]
@PKPenguin321 it doesnt run on fart air it needs to be supplied

with what? you ask? vegetables

that's like running on the electricity from your laptop to power it

**Comment by optimumtact** [comment]
Balance concern not a bug

**Comment by Jalleo** [comment]
I suggest you remove the bug thing then @optimumtact
