### ISSUE TITLE
sometimes if you're holding a plant and you go braindead and you come back you wont see yourself as a plant anymore and youll no longer be able to pick it up and become a plant again

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26152]
GIANT title explains this weird phenomenon regarding breaking of alt appearance datum

@RemieRichards

**Comment by optimumtact** [comment]
Known bug with the system taht late joiners do not get custom appearance overlays, still unsolved to this day.

**Comment by XDTM** [comment]
Could be due to client images being reset on reconnection, i've seen this with hallucinations.

**Comment by RemieRichards** [comment]
Not really a bug, just, something hard to solve. Nobody ever offered up an acceptable solution (Not even the one bay use in their port is good), so we never solved it at all.

There's no easy way of saying "You should be seeing this thing you have no references for", bay solve it iirc by just forcing them all onto players in Login() and removing the invalid ones, it's something gross though I do remember that.

**Comment by optimumtact** [comment]
yeah bug is uncharitable sorry, it's a difficult edge case that needs a good solution.

**Comment by Militaires** [comment]
keep it up as a higgs buggson for history

**Comment by Cyberboss** [comment]
I have a solution

**Comment by Militaires** [comment]
A final solution...
