### ISSUE TITLE
you can make a hole in lava if you bomb it hard enough

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26153]
if i had that picture of the guy who did it i would post it but this is completely mysterious and DOES happen.

edit: i mean lavaland lava not the meme one

**Comment by octareenroon91** [comment]
Chasm or sandy turf?

**Comment by Militaires** [comment]
@ModernViolence chasm

**Comment by octareenroon91** [comment]
As intended, I think. 

````
/turf/open/floor/plating/lava/smooth/lava_land_surface
        initial_gas_mix = "o2=14;n2=23;TEMP=300"
        planetary_atmos = TRUE
        baseturf = /turf/open/chasm/straight_down/lava_land_surface
````

**Comment by Cyberboss** [comment]
yeah, if you bomb lavaland hard enough it makes chasms, not a bug

**Comment by Militaires** [comment]
@lzimann @Cyberboss no no you dont get it

it made a hole into space.

**Comment by octareenroon91** [comment]
You said chasm earlier so this was a bit confusing.
