### ISSUE TITLE
cutting off limbs to heal [consistency issue]

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26150]
currently because of how we compute total health and that our crit is an ugly simplified blob the crit threshold sees the health of ALL limbs of your body, the inconsistent part with this is that you can magically get rid of your total damage and GO OUT OF CRIT BY CUTTING LIMBS OFF?

which is weird.

**Comment by PKPenguin321** [comment]
Stop reopening this, not a bug, as has been said the last two times this was reported

**Comment by Militaires** [comment]
okay
