### ISSUE TITLE
"The midnight rollover macro doesn't work"

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#26156]
Revision: 6e720cf807cf64f544b212ace6bb31fbdf426e03 
![loadtimes](https://cloud.githubusercontent.com/assets/9963278/24984319/6d5b4b4c-1fa1-11e7-93bc-d1da5a1deefd.PNG)

**Comment by optimumtact** [comment]
Hmm @MrStonedOne your real midnight rollover macro sucks

**Comment by duncathan** [comment]
that's awfully quick

**Comment by Cyberboss** [comment]
Please edit your issue title to "The midnight rollover macro doesn't work"

**Comment by Cyberboss** [comment]
@MrStonedOne

**Comment by optimumtact** [comment]
@tgstation/commit-access
