### ISSUE TITLE
arrival shuttle flying away will play the loud hyperspace launch noise no matter how far you run away from arrivals

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26168]

**Comment by optimumtact** [comment]
It might be setting the wrong loc

**Comment by Iatots** [comment]
The shuttle starts traveling away as soon as you get out. The ignition lasts about 3 seconds, and all throughout a sound effect is played: it starts with a faint wind-up noise, and then the "jump" hits.  Could you just have missed the wind-up part? SFXs play to completion, and the ignition one is relatively long.

**Comment by Cyberboss** [comment]
This is because we have no way to update the location of the sound while it's playing. The only fix is to split the sound into segments and play each of them individually so it sounds like the loc is updating

**Comment by Cyberboss** [comment]
It's all one sound btw https://github.com/tgstation/tgstation/blob/master/sound/effects/hyperspace_begin.ogg

**Comment by Davidj361** [comment]
Isn't this more of a byond issue where the sound doesn't change based off changing location?

**Comment by Cyberboss** [comment]
Yes
