### ISSUE TITLE
if you spawn a human they will have no eyes but when you slap them their eyes will appear.

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26169]
bug of the year? @KorPhaeron

**Comment by Sligneris** [comment]
Eyes are very buggy anyway.

Many times, when I had robotic eyes implanted, my sprite indicated I had no eyes anyway. Still the case for unobtainable eyes, such as alien nightvision ones.

**Comment by Militaires** [comment]
@sligneris if you slap yourself eyes appear

**Comment by xxalpha** [comment]
Insert lol what meme here

**Comment by Davidj361** [comment]
It's like having to spank a newborn when coming into life, but you spank their eyes instead.

**Comment by Militaires** [comment]
@Davidj361 arent you that hippy admin...

**Comment by Davidj361** [comment]
No they would never make me an admin with the account name PoopLicker.

**Comment by Militaires** [comment]
@Davidj361 look at the second post

http://ss13.moe/forum/viewtopic.php?f=15&t=3666
