### ISSUE TITLE
delta toxin bomb range does not use a riveted wall

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26160]
it uses a different probably indestructible wall but it's kind of **inconsistent**

![dreamseeker_2017-04-13_03-27-33](https://cloud.githubusercontent.com/assets/16103879/24984912/44bf5d60-1ff9-11e7-9bf9-8c1e723130ba.png)

**Comment by optimumtact** [comment]
map issue thread, yadydyyad

**Comment by PKPenguin321** [comment]
not a bug either
