### ISSUE TITLE
Solidification reaction inconsistent

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#26167]
I was autisming as drone in derelict and trying to make solid ingots of gold and uranium from custom plants, potatos with Frost Oil and gold/uranium. This worked well for gold but for some reason didn't for uranium. It did make reaction sound and use up ALL the reagents but nothing happened.
Super high definition 4K video to illustrate situation:
https://youtu.be/kdQdwfLHsuY

Server revision compiled on: 2017-04-11
The following pull requests are currently test merged:
#26039 
#26044 
#26902 
#26092 

Based off master commit:
6e720cf807cf64f544b212ace6bb31fbdf426e03

**Comment by ExcessiveUseOfCobblestone** [comment]
the reaction doesn't exist wtf
