### ISSUE TITLE
[WHY DID NO ONE GET IRKED ABOUT THIS YET] wall mounts stay floating if the wall they're on is destroyed

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26164]
convicts: posters, fire axe displays, mirrors and intercoms.

let us END THIS please just make them deconstruct or delete or something fuck my emulsions
![dreamseeker_2017-04-13_03-38-52](https://cloud.githubusercontent.com/assets/16103879/24985153/fb52f5fe-1ffa-11e7-804f-3126ee265d04.png)

**Comment by optimumtact** [comment]
Mostly due to the fact they're nto actually on the wall.

**Comment by PKPenguin321** [comment]
dupe i think

**Comment by Militaires** [comment]
@PKPenguin321 i dont think so i searched

**Comment by RandomMarine** [comment]
Dupe of  #22283
