### ISSUE TITLE
delta hos office has TWO security record consoles and prisoner consoles

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26163]
![dreamseeker_2017-04-13_03-36-49](https://cloud.githubusercontent.com/assets/16103879/24985066/7b5d58ee-1ffa-11e7-8f0f-5bd38fc743c3.png)

**Comment by Sligneris** [comment]
He's making a list,
And checking it twice;
Gonna find out who's naughty and nice.

**Comment by Sligneris** [comment]
He sees you when you're sleeping
He knows when you're awake
He knows if you've been bad or good
So be good for goodness sake!

**Comment by optimumtact** [comment]
map issue report in thread
