### ISSUE TITLE
Current byond memory leak detected

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#26176]
I'm posting this issue so you all know, but i've detected cases where large amounts of memory are remaining after server reboots.

Looks like it was triggered by something that happened/was merged on the 9th.

also, lately our memory usage has just in general been higher, might be related.

**Comment by Cyberboss** [comment]
If it started on the 9th, the culprit is likely something between https://github.com/tgstation/tgstation/commit/8d1ee2267ad7231824b725baffd96daa643cdfc2 and https://github.com/tgstation/tgstation/commit/c5999bcdb3efe2d0133e297717bcbc50cfa022bc

**Comment by Cyberboss** [comment]
#26013 has this ever been done before? Could be the cause?

**Comment by Jalleo** [comment]
That was merged two days ago. Its very unlikely. We might need to try reverting a couple of PRs and test merging to see if it was any of them causing it and then trying again with another few.

**Comment by Cyberboss** [comment]
Right, fucking merge commits

**Comment by MrStonedOne** [comment]
so there is a good chance the memory leak existed for a while, and either something on the 9th made it worst, or something on the 9th increased our memory usage to make the crashes happen more often.

**Comment by MrStonedOne** [comment]
Update, I'm no longer seeing the gradual increase in memory on the servers. =\

So something defucked this or what i was seeing was from a test merge, or its something that only applies at certain times..

Who knows....
