### ISSUE TITLE
Canvases sometimes choose random sprites

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#26184]
I've seen cryopod canvases before and a few others.

**Comment by Tokiko1** [comment]
This sounds like something that should be turned into a feature perhaps?

**Comment by Armhulen** [comment]
I've seen a singulo canvas.

**Comment by RemieRichards** [comment]
smells like resource corruption, clear your caches.

**Comment by PKPenguin321** [comment]
Definitely clear your caches but I have noticed that instances of this happen more frequently with specifically canvases for some reason
One time I saw a Ratvar portal canvas

**Comment by RemieRichards** [comment]
there's a valid reason it happens more with canvases.
each pixel added to the canvas is a new icon that has to be made/accidentally loaded from somewhere.

you do the maths as to what's happening here.

(by the same rights, the rarely seen space time agent's gun that slowly melts someone pixel-by-pixel should have similar odds of showing this, but as said, is rare in and of itself)

**Comment by MrStonedOne** [comment]
fixed in 512
