### ISSUE TITLE
Reset Thunderdome to Default State doesn't work properly

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#26198]
When the Centcomm fancification happened, the thunderdome changed size while the template that this button uses does not. As a result, the very bottom row of tiles in the thunderdome won't be reset when this button is pressed.

**Comment by octareenroon91** [comment]
Can confirm. It's a little better without the centcom-template atmos backbleed at least.

**Comment by Cyberboss** [comment]
Thisll be fixed when I do @kevinz000's partial map repair

**Comment by WJohn** [comment]
![](http://i.imgur.com/5OhP4Pa.png)

The thunderdome was shifted up and to the right 1 tile. Not sure what happened, because it normally works fine. Is it simply a map issue?

**Comment by AnturK** [comment]
Probably a bug since that centcom remap.

**Comment by octareenroon91** [comment]
>shifted up and to the right 1 tile.

OK, that could be it.
