### ISSUE TITLE
You can understand a pAI on your person talking on the radio in a different language

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26192]
[AI Private] P.O.N.K : Personal Edition states, "Unit recommends locking down the area containing the captain until she can be disarmed."
P.O.N.K : Personal Edition states, "Beepboophisswurrwahhbeep. Hssbeepdeekssshhissboopbeeptzzzbopbeepdeetzzzboopdee. Tzzz boop."

**Comment by coiax** [comment]
My gut feeling suggests this may have something to do, with you "overhearing" their radio.

**Comment by valuial** [comment]
Well, I was understood by every fleshbag on the channel wehn I used ,6 to talk Encoded Audio... afaIct languages are totally broken.

**Comment by coiax** [comment]
:(
