### ISSUE TITLE
lava gets wet

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26207]
![2017-04-14_04-44-18](https://cloud.githubusercontent.com/assets/16103879/25030423/93cf898c-20cd-11e7-8c22-7400faac12c5.png)

**Comment by jughu** [comment]
Its just very cold lava

**Comment by Kromgar** [comment]
DUPE

**Comment by Kromgar** [comment]
#24126


ITs not freon freezing either

**Comment by XDTM** [comment]
Where does that sprite even come from, i've never seen it ingame on /tg/

**Comment by Kromgar** [comment]
Its when wet floor tiles become frozen near holes in space

**Comment by octareenroon91** [comment]
^^
It's lava with the icy-plating overlay.

**Comment by Iamgoofball** [comment]
this isn't my code

please contact someone else, the freon ice overlay is a completely different sprite

**Comment by Iamgoofball** [comment]
@optimumtact

**Comment by Iamgoofball** [comment]
![freon](https://cloud.githubusercontent.com/assets/4081722/18035808/e1e79b8e-6d11-11e6-883e-413116338953.gif)

this is what freon floor tiles look like
