### ISSUE TITLE
Slimes can no longer move in space

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#26209]
Server Revision: 4ef90caf4e84b30d853a4eb324e8e13cdbc8af55 

There was a pyroclastic anomaly event, and at the end of it, I spawned as a Red Slime. Since the anomaly had originally spawned on a window in arrivals, it moved into space, thus the slime spawned in space, next to a wall and on top of a lattice. However, I was unable to move. I confirmed hotkey mode was enabled. I can confirm that slimes have been able to spacewalk within the last two days, due to playing as a slime and having to spacewalk.

![deadslime](https://cloud.githubusercontent.com/assets/9963278/25035988/e65ed61c-20a5-11e7-85e4-887f00fe052d.PNG)

**Comment by PKPenguin321** [comment]
Possibly misleading issue title, since you didn't move into space, you spawned there

**Comment by ShizCalev** [comment]
Think this was fixed. Will close in a week without another repo
