### ISSUE TITLE
Titanium isn't smeltable at the mining furnace.

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#26205]
In the mining base with the mining furnace, you can't smelt titanium. Normally this would be irrelevant to most people but the gulag prisoners can only smelt ores via the furnaces, thus giving them useless ores to work with.

**Comment by KorPhaeron** [comment]
Titanium should be removed and replaced by a silver/plasma alloy

**Comment by Profakos** [comment]
Duplicate of #25166

**Comment by duncathan** [comment]
Other issue is more accurate
