### ISSUE TITLE
Lighting tiles are either fully bright or weird blue-green colored tiles

### ISSUE THREAD

**Issue by Man-Shroom-** [tgstation/tgstation#26224]
![rimward suffix two 2017-04-13 172408](https://cloud.githubusercontent.com/assets/6549019/25056280/dc23ce60-2135-11e7-990f-a9d44f47fb4c.png)

I recently came back to this game after a several-month hiatus. I'm on the latest beta and my cache has been cleared. what do

**Comment by Jalleo** [comment]
@MrStonedOne

**Comment by MrStonedOne** [comment]
download and install the directx sdk

**Comment by octareenroon91** [comment]
^^

**Comment by Tacolizard** [comment]
just out of curiosity, can you tell me if you're using a discrete graphics card, which version of windows you're on/which vm program you use and the host and virtual OS?
