### ISSUE TITLE
Delayed slime core reactions delete the core before the reaction occurs

### ISSUE THREAD

**Issue by XDTM** [tgstation/tgstation#26223]
Likely caused by #26139, @ChangelingRain

**Comment by Armhulen** [comment]
NO WONDER I WASN'T STOPPING TIME AT ALL

**Comment by XDTM** [comment]
No, that one works _too well_, since it stops time for everyone, user included, which causes the user to not notice time ever stopping.

**Comment by ChangelingRain** [comment]
wow it sure would help if you said which reactions

**Comment by TheDreamweaver** [comment]
From personal experience, this makes gold slimes unusable because as stated, the core dissapears before any mobs are spawned.

**Comment by XDTM** [comment]
I've reported this secondhand, so i only know of golds for sure.
