### ISSUE TITLE
Animal spawning relic has no delay

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#26225]
Animal spawning relic has no time window to drop it after seeing the warning - it spawns animals immediately.

This is unlike all other dangerous relic effects (teleportation, explosion), which give you a warning that serves as a hint to its effect and wait a short time to activate - canceling the activation if dropped.

There *is* a warning message that appears upon activation, which makes me believe that animals spawning immediately is unintended:

`var/message = "<span class='danger'>[src] begans to shake, and in the distance the sound of rampaging animals arises!</span>"`

**Comment by Sligneris** [comment]
It does actually show a warning message, which makes me believe that animals spawning immediately is unintended:

`var/message = "<span class='danger'>[src] begans to shake, and in the distance the sound of rampaging animals arises!</span>"`

**Comment by PKPenguin321** [comment]
Don't think this is a bug, smells like balance

**Comment by Sligneris** [comment]
Then how do you explain the message worded like it's meant to warn the user prior to activation?

**Comment by PKPenguin321** [comment]
That's really just up to the readers interpretation. It doesn't scream timed delay to me. The only thing that needs fixing is the message saying "begans"

**Comment by kriskog** [comment]
Intentional
