### ISSUE TITLE
Atmospherics conditions hit infinity

### ISSUE THREAD

**Issue by octareenroon91** [tgstation/tgstation#26236]
That's Waste Loop.
It measures something.
The pressure gauge reads -1.#IND kPa; -1.#IND K (-1.#IND°C)

Apparently it had to do with space.

Current server time 2017-04-15 03:27:14

Server revision compiled on: 2017-04-15
The following pull requests are currently test merged:
#26092: 'AHelp improvements' by Cyberboss 

Based off master commit:
4cd00f576c17dc282569f627de29a6c23e58bc66

**Comment by Expletive** [comment]
![plasmaspace](https://cloud.githubusercontent.com/assets/9963278/25060408/5758b292-2151-11e7-9649-b16435836843.PNG)
Transitionspace was full of plasma, and apparently the mining shuttle carried it to lavaland.

**Comment by Marflowerose** [comment]
The pressure actually changes even in same space tile if you use analyzer, it seems to be some loop and it keeps overflowing

**Comment by Magikarpet** [comment]
http://puu.sh/vkDSo/b506f71790.png https://puu.sh/vkDgF/c95f98b820.jpg jesus christ shit's fucked

**Comment by Kromgar** [comment]
What the everloving fuck

**Comment by Kromgar** [comment]
Apparently this happened on  Bagil and Sybil at the same time fucking wot

**Comment by Cyberboss** [comment]
Fixed by #26238 i think

**Comment by BeeSting12** [comment]
https://gyazo.com/d8f9e0a45b3add91774592aa3e9f4675

**Comment by TheColdTurtle** [comment]
So basically infinite pressure. I just wanna know how this happens on a feature freeze of all times.

**Comment by francinum** [comment]
![](http://i.imgur.com/a2zjyUP.png)

**Comment by Robustin** [comment]
@TheColdTurtle 

Not that unexpected when people go meddling in foreign code territory and make changes they don't quite understand.

**Comment by duncathan** [comment]
@Robustin it's not so much that it's not understanding changes. more so that Atmos is a very sensitive module where even tiny mistakes have huge effects

**Comment by Jalleo** [comment]
Hot dang.

**Comment by Robustin** [comment]
@duncathan 

Ok not every case falls under my generalization but I don't think its an exaggeration to say the game's been less playable during the "feature freeze" because of people trying to spitfire out fixes.
