### ISSUE TITLE
Deltastation Chemistry Lab does not have any pill bottles

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#26233]
There's a chemical closet and a chemist's wardrobe, but there is no closet containing boxes of pill bottles. This usually means you have to steal the mannitol pills, or the one pill bottle in the room next to the morgue.

**Comment by octareenroon91** [comment]
For reference the closet with bottles is `/obj/structure/closet/secure_closet/chemical`

**Comment by BeeSting12** [comment]
I'm fixing this right now. Thanks @octareenroon91 for the chemical closet path.
