### ISSUE TITLE
Emitters don't shoot emitter beams

### ISSUE THREAD

**Issue by obscolene** [tgstation/tgstation#26249]
There's no further explaination needed. They basically just don't shoot lasers, ever. Turning on an emitter does nothing. This makes the SM unusable. 

[pictured: 4 emitters on and powered, not shooting beams](https://i.gyazo.com/158d37a8dc064a0aa3eae0c68da6418d.mp4)

**Comment by factoryman942** [comment]
and no emitters means no tes/singulo either
time for antimatter

**Comment by octareenroon91** [comment]
Solars, turbine, teg

**Comment by PKPenguin321** [comment]
I believe a fix is already up for this, https://github.com/tgstation/tgstation/pull/26237

**Comment by Cyberboss** [comment]
Referenced issue says it's still not working @Robustin

**Comment by Iamgoofball** [comment]
Was the server updated?

**Comment by AnturK** [comment]
Yeah, servers are still 2 days behind the repo.

**Comment by Jalleo** [comment]
The fix is merged we can close this.
