### ISSUE TITLE
androids are invisible when created by a magic mirror

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#26244]
And it riddles me greatly

**Comment by Profakos** [comment]
What is the server revision? I downloaded the latest version, and it I was not invisible after using the mirror.

**Comment by Armhulen** [comment]
I can check today

**Comment by optimumtact** [comment]
synths are broken

**Comment by Profakos** [comment]
Oh, synths and not androids? I'll check it later today.

**Comment by Profakos** [comment]
Neither synths, nor andoids were invisible when I used the magic mirror in the wizard den.   Latest commit: https://github.com/tgstation/tgstation/commit/8a8b2c1c6c29b3ba99169b7882acccf9600763cc
