### ISSUE TITLE
You can use android mutation toxin on monkeys, which removes its sprite

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26253]

**Comment by AnturK** [comment]
Monkeys using human species strikes again

**Comment by FantasticFwoosh** [comment]
Unless you want to make this work as a feature by adding a humanising morph effect transition.

**Comment by coiax** [comment]
@AnturK just make monkeys a human subspecies.

**Comment by Profakos** [comment]
Two causes, looks like it. One of them is that on_species gain applies when a monkey is forced to change species, making all the limbs robotic.
https://github.com/tgstation/tgstation/blob/67b0a7293e8a62f98caafb174650c2c6adc2dc49/code/modules/surgery/bodyparts/bodyparts.dm#L306
This line assumed augments.dmi has monkey limbs in them, which is not the case.
