### ISSUE TITLE
Conveyor belts are too fast for stacking machines

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#26254]
The stacking machine in maintenance can't keep up with the fastprocessing of conveyor belts, therefore its process won't grab the sheets created by the recycler.

**Comment by Cyberboss** [comment]
An idea is you could create a ghost object on the four cardinals of the stacking machine and automatically add items that call Crossed on it

**Comment by Profakos** [comment]
I suppose I could try that, now that I am refactoring all of the mining machines (oh god the stacking machine's code gives me a headache)

**Comment by RemieRichards** [comment]
```Crossed()``` is the only way to go about this correctly.
NEVER poll when you can react.

**Comment by coiax** [comment]
@RemieRichards isn't there some sort of proximity system? I know that xeno eggs use it to wake up when people are next to them.

**Comment by Profakos** [comment]
I gazed upon the code and looks like someone set the CONSOLE to speed_process but not the actual stacking machine :/

**Comment by Cyberboss** [comment]
doesn't matter, still wouldn't be fast enough.

**Comment by Profakos** [comment]
I have made a test, and it worked, but there no guarantee that it would work all the time. I will work on these after I did the various standardization updates.

**Comment by RemieRichards** [comment]
@coiax there is but i hate it it's gross.
instead of ghost objects it lends extra baggage and weirdness onto the turfs themselves.
Having just fixed something else caused by turfs having weird functionality (space transitions) I stand against such code (but I hated it before that anyway)

**Comment by Profakos** [comment]
@Cyberboss , the issue still exists, however, in a much more weirder way: the abstract proximity sensor which sets off the HasProximity check, actually gets destroyed when a conveyor belt is involved, and only if the conveyor belt is not heading towards the stacker.

**Comment by Cyberboss** [comment]
@lzimann, reopen please.
