### ISSUE TITLE
Kudzu not growing apparently

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#26251]
(F) DEAD: Kevin Parkinson asks, "like HOW is kudzu broken?"
(F) DEAD: Charles Bukowski says, "it is not growing"
(F) DEAD: Charles Bukowski says, "after you plant it it stays on one tile forever"
(F) DEAD: Charles Bukowski says, "so it is COMPLETELY broken"
(F) DEAD: Charles Bukowski says, "or almost"
(F) DEAD: Charles Bukowski says, "after you activate the seed on your hand, it simply won't grow"

Haven't tested to see if it is true yet

**Comment by RemieRichards** [comment]
@Cyberboss

**Comment by Bawhoppen** [comment]
how were you so fast 
![ss 2017-04-15 at 12 44 55](https://cloud.githubusercontent.com/assets/6510293/25065690/5820b002-21d9-11e7-8d53-06638495ec2c.png)

**Comment by RemieRichards** [comment]
emails.

**Comment by RemieRichards** [comment]
oh and tabcomplete on the ```@Cyberboss```

**Comment by factoryman942** [comment]
literally one second

**Comment by Bawhoppen** [comment]
okay well I guess the seconds aren't fully accurate, but it was still like under 5 seconds

**Comment by TalkingMime** [comment]
Seems we made two issues about this =X

**Comment by AnturK** [comment]
#26250

**Comment by Bawhoppen** [comment]
I fiercely apologize

**Comment by Cyberboss** [comment]
Apparently the controller is GCing before it starts processing? But how is that possible???
