### ISSUE TITLE
Aliens can't slash hacked APCs

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#26265]
It's impossible for xenos to slash hacked APCs like regular ones.

**Comment by FantasticFwoosh** [comment]
For clarity does this apply on harm intent?

**Comment by Sligneris** [comment]
Aliens slash objects regardless of intent but yes, I wouldn't be making this issue otherwise.

**Comment by XDTM** [comment]
https://github.com/tgstation/tgstation/blob/master/code/modules/power/apc.dm#L674

apparently it's intended, but i cannot fathom why
