### ISSUE TITLE
You gain the powers from contracts before it checks if you are capable of signing it

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#26261]
I became a Hulk from a contract of power, even though signing the contract failed, because the person was not an actual devil, just had Summoncontract bestowed upon them.

**Comment by GunHog** [comment]
How would anyone gain this ability outside being a devil or badminnery?

**Comment by Profakos** [comment]
Probably there is no way for that, but still, sanity checks are nice.

**Comment by octareenroon91** [comment]
What's the point of "summon contract" if the contracts are so worthless?

**Comment by lordpidey** [comment]
Huh.  That's certainly a new edge case.  I'll work on fixing this.
