### ISSUE TITLE
Cryocells have invalid follow links (Cerestation)

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#26269]
`<a href=?src=[mob_779];follow=[icon-cell-off (WEST)]>(F) [Medical] cryo cell beeps, "Patient fully restored"
`

**Comment by AnturK** [comment]
I'm going to shank next mapper who uses tags in their map.

**Comment by Iatots** [comment]
Auto-what whats?

**Comment by AnturK** [comment]
When you use generate icon states from dir/states buttons in dreammaker it auto adds tags to these instances which is absolutely wrong.
