### ISSUE TITLE
Bluespace Shelter Capsules don't hurt you if you hold them when they activate.

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#26272]
Revision: 3952aed40bf369618cf6a62012eeb5d72382ad08 
The bluespace shelter capsules warn you in red text that you should stand back when you activate them, but if you don't bother and let it activate with it in your hand, you are completely unharmed, rather than being gibbed.

**Comment by Kromgar** [comment]
This has been the case since they were introduced like 2-3 years ago i don't exactly remember when lavaland itself got added

**Comment by KorPhaeron** [comment]
If shelter pods gibbed people you'd probably see miners stunning + shelter podding in the primary halls unfortunatley

**Comment by XDTM** [comment]
So we can close this

**Comment by KorPhaeron** [comment]
Yeah
