### ISSUE TITLE
Xeno acid melts lava

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#26282]
![image](https://cloud.githubusercontent.com/assets/6778786/25074468/47e1f6ce-22c9-11e7-88df-4e9d7b92e46e.png)

![image](https://cloud.githubusercontent.com/assets/6778786/25074475/5a0e21f6-22c9-11e7-9c7c-00fba121ea17.png)

AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by PKPenguin321** [comment]
Feature

**Comment by Jalleo** [comment]
@KorPhaeron your input as designer is needed.

**Comment by KorPhaeron** [comment]
Probably a bug

**Comment by ExcessiveUseOfCobblestone** [comment]
that acid is really strong!

**Comment by Sligneris** [comment]
Isn't that just the same effect as deconstructing lava with an RCD?
