### ISSUE TITLE
Emitters still don't shoot emitter beams

### ISSUE THREAD

**Issue by StuAhpla** [tgstation/tgstation#26294]
https://github.com/tgstation/tgstation/pull/26237

I know there was a fix merged but from testing it hasn't fixed the problem yet

**Comment by Jalleo** [comment]
If there are no fixes up for this until later today I may take a look at this.

**Comment by Cyberboss** [comment]
Dupe #26249

**Comment by Iamgoofball** [comment]
Was the server updated?
