### ISSUE TITLE
GAME: Error: /obj/item/weapon/gun/ballistic/minigun([0x202c7cf]) took longer then 1 second to delete (took 809 seconds to delete)

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#26295]
I have found this in the log files

https://tgstation13.org/parsed-logs/basil/logs/2017/04-April/17-Monday.txt (control+f for `08:21:55`)

@tgstation/commit-access 

There are a few more. https://tgstation13.org/parsed-logs/deletelagfind.txt

This happened after a bagil "crash" only one that nobody was around to fix, so it resolved itself manually

**Comment by optimumtact** [comment]
Ammo boxes are retarded and store ammo as a list of intialized objects of the casing type, that means the laser gatling gun is storing 5000 copies of the laser ammo casing.

this list is not properly released on qdel so will probably hard del and require reference searching on all thsoe objects.

1) Clear this list on destroy
2) refactor ammo boxes to not store the ammo but to store counts of each item, for some (specifically revolvers) it may be worth having a list that book-keeps empty slots, but it should do this with a list of 1/0's representing the empty/full ammo cases. A smarter implementation can do it with a bit flag, but would be limited to the length of one binary flag (there shouldnt' be any weapons for which the ammo count is significantly larger than that limit where the simulation would matter anyway)

**Comment by optimumtact** [comment]
Hmm it strikes me that at least some of this funcitonality might have to live on for shotguns, which allow mixed loads, either that or special handling to store the types of ammo loaded as a count

**Comment by KorPhaeron** [comment]
You can theoretically do the same with other weapons as well if you load different types of bullets into the magazine, though it isnt really worth the time. Whoever coded the system really liked guns.

**Comment by optimumtact** [comment]
most of the magazines only allow one type of calibre/ammo type through, shotguns are basically the only projectile with multiple types at one calibre.

**Comment by Thunder12345** [comment]
There's other guns with multiple ammo types too, like sniper rifles

**Comment by optimumtact** [comment]
hmm okay so that functionality should still live at the ammo_box/magazine path then.

something like a list of type paths, and a measure of start/end so you can calculate where the current round position would fall in to pull out the appropriate ammo type.

Is there any instance of an ammo_casing that modifies the projectile in such a way that only having it's type information would cause information/functionality loss?

**Comment by KorPhaeron** [comment]
Chem darts for shotguns off the top of my head

**Comment by optimumtact** [comment]
Alright so people are at least using the functionality this provides so that scuppers a less detailed rewrite of the simulation

**Comment by optimumtact** [comment]
I guess a split of the type path between simulated (storing the full objects) and unsimulated(storing the count only) would work, laser gatling is an obvious target for that optimisation, then a warning comment about simulating large amounts of ammunition.

everything else is fairly restrained in it's ammo_count.

**Comment by KorPhaeron** [comment]
We could change the minigun to an energy weapon so it generates shots on the fly. Automatic weapons werent possible as energy weapons when the minigun was added but Phil fixed that

**Comment by MrStonedOne** [comment]
None of that is important right now.

I want to actually find out why (reproducible and tested and confirmed) that this happens before it change it out because we need to know if its a byond bug that needs to be reported or another quirk to remember.

Atm we have an assumption, thats it.

**Comment by optimumtact** [comment]
yeah sorry I did not mean to derail this issue, which is only mildly related to projectile code

**Comment by xxalpha** [comment]
@optimumtact it's simple, store an assoc list with the different bullet paths with respective counters.

**Comment by Cyberboss** [comment]
As an aside, this kind of logging should be in the del log, not game logs

**Comment by MrStonedOne** [comment]
cyberboss, its an admin msg, thats why its in the game logs.

**Comment by MrStonedOne** [comment]
in fact we don't even have a delete log

**Comment by duncathan** [comment]
we log paths that fail to GC in `world.log`

**Comment by MrStonedOne** [comment]
I mean this error is something thats sent to admins and logged to the game log because its not about logging that it happened, but telling admins why the lag they just saw was the case.

Putting it in the qdel log to only be outputted at world end isn't appropriate

**Comment by duncathan** [comment]
imo putting it in both would be best so we can target the most costly deletions

**Comment by duncathan** [comment]
while also providing that useful info to admins

**Comment by MrStonedOne** [comment]
This happening is strictly a bug, not something that happens often enough to log, if you look at the grep text file i linked, we went like 6 months without it ever triggering.

**Comment by MrStonedOne** [comment]
if anything i'd make it create a github issue report before i'd add it to the del log

**Comment by duncathan** [comment]
in that case yeah this is fine in just admin message
