### ISSUE TITLE
Languages on are broken. Normal humans understand Encoded Audio Language.

### ISSUE THREAD

**Issue by valuial** [tgstation/tgstation#26306]
Talking on the common channel using Encoded Audio Language (EAL):
say ";,6Some text that only silicons should understand
but every human on the station could understand me XD
this was as pAI, but I believe similar problems are with borgs.

No idea if talking normal (not using radio) has the same issue.

Possible common problem with issue #26192

[Note]: # The following pull requests are currently test merged:
#26092: 'AHelp improvements' by Cyberboss 

Based off master commit:
3952aed40bf369618cf6a62012eeb5d72382ad08

**Comment by Armhulen** [comment]
Pais know all languages.

**Comment by coiax** [comment]
This was caused by afa847bf353048019380d9883a3ae6ab517798a4

**Comment by coiax** [comment]
@JJRcop you caused this with your whisper changes. I'm looking at the code now.
