### ISSUE TITLE
Can't arrest piggybacked persons

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/tgstation#26312]

**Comment by coiax** [comment]
Going to need more description on what this means and what you do to replicate this.

**Comment by LanCartwright** [comment]
If they're piggybacked, cuffing one of the mobs is difficult and may not cuff the right mob.

**Comment by kevinz000** [comment]
difficult != can't do so
Did you even reproduce the "didn't cuff right mob" because I'm not sure that's possible.

**Comment by Repukan** [comment]
@Cyberboss this is not a bug, rather a feature off piggy backing
