### ISSUE TITLE
Tagged turfs on Cerestation

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26335]
<a href=?src=[mob_704];follow=[icon-cell-off (WEST)]>(F) [Medical] cryo cell beeps, "Patient fully restored"
<a href=?src=[mob_704];follow=[icon-cell-off (WEST)]>(F) [Medical] cryo cell beeps, "Auto ejecting patient now"

FIX IT FIX IT

**Comment by MMMiracles** [comment]
it was fixed the server just isn't updated with the changes

dingus
