### ISSUE TITLE
Mindshield implants block admin culting

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#26348]
If you create a cult and it targets a shielded person, they'll get objectives in their notes, but wont get antag status or items. Can't antag them through the traitor panel either.

**Comment by octareenroon91** [comment]
Random cult draft will try implanted people, or just if you try to cult a specific person directly?

**Comment by PKPenguin321** [comment]
Both

**Comment by ExcessiveUseOfCobblestone** [comment]
just remove the implant from them

**Comment by Cyberboss** [comment]
I fundamentally disagree with forcefully antag-ing implanted people. It ruins the purpose of the implant. HELLO? SECURITY!

**Comment by optimumtact** [comment]
not a bug

**Comment by PKPenguin321** [comment]
Them still getting objectives but not antag status is a bug

**Comment by bgare89** [comment]
Do not "just remove the implant from them".

**Comment by ExcessiveUseOfCobblestone** [comment]
@Rockdtben we can forcefully remove the implant anyways if we are going to do it.

A simple prompt before hand that says "This will remove their implant, are you sure mr moderator?" would suffice.

**Comment by Detective-Google** [comment]
![image](https://user-images.githubusercontent.com/48196179/64513449-319c9a80-d2ae-11e9-8d31-516b59167a02.png)
TP currently greys out on mindshielded personel, means this isn't applicable

**Comment by PKPenguin321** [comment]
This happened when creating a cult with the Create Antagonists menu, not just with the traitor panel. Are you sure that was also fixed?
