### ISSUE TITLE
Several outdated buttons exist in the secrets menu

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#26347]
`Show Crew Manifest` has been obsoleted by the much more modern and fancy View-Crew-Manifest verb

**Comment by PKPenguin321** [comment]
Oh, and the Show Game Mode button

**Comment by PKPenguin321** [comment]
There's a completely non-functional button, `Show current traitors and objectives`

**Comment by PKPenguin321** [comment]
Show Job Debug could be moved out of the secrets panel to the Debug verbs tab

**Comment by PKPenguin321** [comment]
Show Admin List is kind of obsoleted by the Permissions Panel

**Comment by Cyberboss** [comment]
Can people without +PERMISSIONS see the perm panel?

**Comment by PKPenguin321** [comment]
Oh, good question, I'm not sure

**Comment by Jordie0608** [comment]
No

**Comment by bgobandit** [comment]
please don't remove crew manifest in secrets panel, it is one of the few admin tools that doesn't crash my client

**Comment by dragomagol** [comment]
Fixed by #55698
