### ISSUE TITLE
ash Drake transformation fucked up action button bar.

### ISSUE THREAD

**Issue by Repukan** [tgstation/tgstation#26340]
Using the ash Drake transformation makes the action button bar extend more and more. I tried logging in again but it remained extended, and further uses of the transformation extended it more.

**Comment by AnturK** [comment]
You mean it was adding another button ?

**Comment by Repukan** [comment]
No, the space was blank and kept extending.

**Comment by Armhulen** [comment]
If I remember correctly this happens to the wizard shapeshift as well.
