### ISSUE TITLE
Careful, the frozen Robust Coffee you're about to enjoy is extremely hot!

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#26349]
![3jc1rod](https://cloud.githubusercontent.com/assets/6209658/25113717/5b53ae10-23c7-11e7-86f6-f30c0959dfea.png)

>Freeze coffee with Freon
>Drink frozen coffee
>Warm up

**Comment by optimumtact** [comment]
thats' because the temperature warmth of coffee and the temperature of objects are two completely different systems because nobody has written a unified temperature system yet.

**Comment by ExcessiveUseOfCobblestone** [comment]
The obvious response is to make coffee untouchable by freon for memes.

**Comment by octareenroon91** [comment]
All thermal drinks still have near-identical duplicate code don't they?

**Comment by xxalpha** [comment]
If it wasn't hot after being frozen it wouldn't be _robust_, now would it?

**Comment by SgtxRootbeer** [comment]
The cup has working insulation. This isn't a bug.

**Comment by coiax** [comment]
Also, the temperature of the reagents inside have no effect. It's the coffee reagent that warms people.

**Comment by Kromgar** [comment]
Universal temperature system would probably fry the servers. We already know how cpu intensive dorf fort is

**Comment by octareenroon91** [comment]
Maybe not universal, but there are some temperature systems to harmonize. Chems in beakers don't seem to cook in fire anymore.
