### ISSUE TITLE
Clockcult Mass brain damage spell is busted.

### ISSUE THREAD

**Issue by Repukan** [tgstation/tgstation#26342]
Used a legion core after being hit by it, only healed brain damage but my movement was still fucked.

**Comment by ChangelingRain** [comment]
legion cores don't heal confusion or hallucinations or any of the sideeffects!

**Comment by Repukan** [comment]
Isn't it supposed to heal EVERYTHING sans death?

**Comment by jughu** [comment]
It heals all damage hallucination isnt a damage
