### ISSUE TITLE
Light is not visible within ruins that are not naturally completely lit up and start off in darkness

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#26351]
Quite clearly, when you are joining a a ghost role etc, and you have the very lowest setting of light for ghosts, (out of mister person's spectrum PR for light) the lighting system will fail to work and you'll be left in the dark. 

To recreate, join a ghost role with no natural source of light while having the lowest light setting (one click from default darkness) active. Ashwalkers are recommended because they start off in the dark, you will be unable to activate lighting objects around you even while they are in a active light emitting state.

It is to my belief that without encountering another source of light (lets say another ashwalker with above lowest settings for light activates a lantern no problem) that this would update the lighting for your screen but that is unconfirmed.

> This might be connected to related light bugs of lights never turning (turn light on and off multiple times, no effect) on or objects that emit the new lighting system never activating.

**Comment by MrStonedOne** [comment]
That system is per-mob and should be getting reset on mob change.

**Comment by FantasticFwoosh** [comment]
Sorry, on further investigation the problem seemed to be localised lighting errors (everything inside area X when you spawned into a ghost role is permadark) mistaken because thats a ghost starting area.

**Comment by MrPerson** [comment]
That's a much more serious and very different problem

**Comment by FantasticFwoosh** [comment]
![](http://puu.sh/vqxOK/86ce7e2d7c.jpg)

Apolgies about the misunderstanding, would you like me to re-open a new issue report or edit this one sufficently? Notice how the ashwalker hut ruin is permanently dark.

**Comment by WJohn** [comment]
![](http://i.imgur.com/6bzWtfu.png)

It's all dark.

**Comment by Charmisokay** [comment]
I tested something in the abandoned teleporter. For both pictures, I had several lights turned on (pda and hardsuit)
After removing the floor:
![image](https://cloud.githubusercontent.com/assets/25822752/25312415/912147d2-2818-11e7-9214-a34c62e281b0.png)

After replacing it: 
![image](https://cloud.githubusercontent.com/assets/25822752/25312424/af3b8c64-2818-11e7-8454-565fa8a1dd8b.png)
