### ISSUE TITLE
Ghosts drift in space

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#26359]
Who was that added Moved recently.

**Comment by AnturK** [comment]
@coiax Nice testing.

**Comment by Cyberboss** [comment]
w e w

**Comment by coiax** [comment]
Sounds like a feature, honk.

**Comment by Qbopper** [comment]
high priority bug, everyone in deadchat keeps complaining about it

**Comment by WJohn** [comment]
pretty cute bug tbh

**Comment by Bawhoppen** [comment]
do revs drift?

**Comment by coiax** [comment]
Revs are living things. No relation.

**Comment by Bawhoppen** [comment]
I was under the knowledge they used the same moving code as ghosts
