### ISSUE TITLE
[Cerestation] Bad disposals piping in disposals from Departures

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26363]
![image](https://cloud.githubusercontent.com/assets/609465/25152009/98605fb6-247f-11e7-91b9-baa2d201af0b.png)

Two disposal pipes on one tile here.

@MMMiracles

**Comment by optimumtact** [comment]
map thread

**Comment by coiax** [comment]
Stop closing map issues.

**Comment by optimumtact** [comment]
no

**Comment by coiax** [comment]
@tgstation-server/commit-access please, can we have a ruling please, make citrus stop this.

**Comment by coiax** [comment]
@KorPhaeron @Cheridan @lzimann @ChangelingRain @RemieRichards @duncathan @WJohn MAKE ORANGES STOP CLOSING MAP ISSUES
