### ISSUE TITLE
[Cerestation] CE office in space

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26364]
![image](https://cloud.githubusercontent.com/assets/609465/25152085/d3b4ce94-247f-11e7-96c5-c43a2bc5dfd8.png)

Looks like a duplicate of the CE office tiles, in space. Makes a second Poly, which immediately died and started haunting comms.

**Comment by coiax** [comment]
@MMMiracles

**Comment by MMMiracles** [comment]
😂👌

**Comment by WJohn** [comment]
i figured the ghost of poly was what made that intentional.

**Comment by GunHog** [comment]
Hrm. So I guess he mapped out the offices in an open space, then made room after, then forgot to delete his template.

**Comment by WJohn** [comment]
this looks to be from boxstation, he probably did what i and i assume a lot of other mappers do and just ripped it from another map to make sure he has all the parts in his own office. this is done with just about every room until you have a complete map.

**Comment by optimumtact** [comment]
map thread
