### ISSUE TITLE
Beepsky not affected by gravity loss

### ISSUE THREAD

**Issue by Togopalis** [tgstation/tgstation#26362]
Beepsky moves as normal without gravity, I am assuming the other bots do too.

**Comment by coiax** [comment]
I think this is a dupe, and it's marked as a feature, because JUSTICE KNOWS NO LIMITS.

**Comment by GunHog** [comment]
### F E A T U R E

**Comment by WJohn** [comment]
Likely related to #26141, don't know if I should close this or the other.

**Comment by optimumtact** [comment]
not a bug, all pathing ai's must do this to prevent pathing lag storm.
