### ISSUE TITLE
Rollies and pipes spawn with nicotine in them, even if nicotine was not used to make them

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#26379]
No matter what type of dried plant you put in them, they start with a bit of nicotine because they are children of cigarrettes. This makes it so that smoking anything hallucinogenic doesn't work because A: the chems enter your body super slow. (which is a seperate issue) and B: The rollie/pipe will burn out before any non-nicotine chems enter your body. The chems are absorbed one at a time, not all at once, and nicotine always ques first

**Comment by octareenroon91** [comment]
One at a time, really?

**Comment by Iamgoofball** [comment]
this is actually my fault from the goonchem update

i'll fix it soon

**Comment by Iamgoofball** [comment]
@octareenroon91 That can't be right. I'll check it out.

**Comment by Tacolizard** [comment]
@octareenroon91 @Iamgoofball i tested this ingame, and VV showed that only nicotine was ever absorbing, which also happened to be the first chem on the list of chems in the rollie/pipe.

**Comment by Iamgoofball** [comment]
probably just chem handling fuckery

**Comment by octareenroon91** [comment]
Cigarettes usually deliver only one tick's worth of a chem at a time, so any chem might never spend two ticks in a human.

**Comment by imw-Oculus** [comment]
"i'll fix it soon"

Still broken

**Comment by Cyberboss** [comment]
I remember this being an issue with list_reagents that was fixed
