### ISSUE TITLE
The protolathe can accept negative amounts of ores

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#26374]
![image](https://cloud.githubusercontent.com/assets/6778786/25161631/2cb29674-248b-11e7-83b9-95051fc628be.png)

**Comment by octareenroon91** [comment]
IT NEVER ENDS

**Comment by GunHog** [comment]
https://github.com/tgstation/tgstation/pull/26320

**Comment by xxalpha** [comment]
Please detail how you triggered this bug, I am sure that is asked in the issue template.
