### ISSUE TITLE
Having to download the title screen leads to aesthetics problem

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#26372]
Because the title screen needs to download there is always a period upon first booting up the game where you can see the walls hiding behind the image before it pops in.

The download of the image does not begin until the title screen is "seen" by the client.

**Comment by octareenroon91** [comment]
It sounds inevitable, but we could at least put a "hello" on the wall, no?

**Comment by Jordie0608** [comment]
Or leave the default titlescreen there and have the config one appear above it.

**Comment by Incoming5643** [comment]
it wasn't inevitable when I first added the subsystem, I'm still not entirely clear why we NEED to download it.

**Comment by Cyberboss** [comment]
Didn't work @lzimann

**Comment by timothymtorres** [comment]
@Cyberboss did your PR #25541 fix this?

**Comment by Cyberboss** [comment]
Probably
