### ISSUE TITLE
Repairing floor on escape shuttle while in transit causes them to become black voids.

### ISSUE THREAD

**Issue by SamSamsonthe3rd** [tgstation/tgstation#26382]
Server Revision: 5a9f4906d0e2df019eb98f6c923747584e60d233 

Minibomb went off on escape shuttle, and as engiborg, I tried to repair the gaping holes. However, after placing the lattice, floor tile, floor tile, the repaired floor became a black void. It acted like a normal floor, except entirely black, and when I moved into the square, it covered me. The void disappeared when the shuttle arrived at centcomm.

**Comment by octareenroon91** [comment]
Sounds like broken lighting.

**Comment by Cyberboss** [comment]
Closed by the dock rewrite
