### ISSUE TITLE
'Dangerous power level' supermatter does not spawn an energy ball.

### ISSUE THREAD

**Issue by Sligneris** [tgstation/tgstation#26387]
From what I understood...

- If supermatter has no additional warnings, its delamination results in an explosion.
- If supermatter warns of "critical coolant mass", its delamination results in a supermatter-charged singularity being spawned.
- If supermatter warns of "dangerous power level", its delamination results in an energy ball being spawned.

Except the last one doesn't work. When a "dangerous power level" supermatter delaminates, it explodes as usual.

**Comment by Tokiko1** [comment]
Change Line 178 in supermatter.dm to "if(power > POWER_PENALTY_THRESHOLD)"
