### ISSUE TITLE
Gold slime reagent reactions are broken

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#26392]
The slime core is consumed, but no mobs spawn.

**Comment by SamSamsonthe3rd** [comment]
Beat me to the punch, Bgo. White cores don't work either.

**Comment by Jalleo** [comment]
@Cyberboss maybe?

**Comment by Pierows** [comment]
Tried it out on a local server and can confirm, it's broken.

**Comment by XDTM** [comment]
@changelingrain

**Comment by ChangelingRain** [comment]
I don't understand how this is happening
