### ISSUE TITLE
Gas filters and scrubbers make for infinite pressure

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#26391]
This applies to most merges recently and has been a long standing bug.
Second output of gas filters doesn't have pressure check, it can reach infinite pressure.
Scrubbers can also reach infinite pressure by using scrub mode. Venting mode does have pressure limits.
This may or may not have something to do with attaching 1st output of gas filter as a Connector.

**Comment by duncathan** [comment]
Can you be more specific? Be more clear about infinite pressure

**Comment by Marflowerose** [comment]
When pumping gas through a filter, the second output will have no pressure limit. When scrubbing gases the scrubbers have no pressure limit as to how much they will input to the pipes connected if in Scrub mode.

**Comment by octareenroon91** [comment]
Gas filters limit their output to both the isolated-gas and cleaned-mix sides based only on their pressure setting and the pressure in the cleaned-mix pipeline.

Scrubbers push gas into their pipes as long as there is any on their turf that's set to be pulled in.

Thus the pressure on one output of each of these is limited only by pipeline volume and available heat/gas moles.

**Comment by octareenroon91** [comment]
This is kind of known atmos behavior though: it's more a balance thing than a bug at this point.

**Comment by Marflowerose** [comment]
I think it's a legit bug that a syphoning scrubber has pressure limit whereas scrubbing scrubber doesn't.
