### ISSUE TITLE
Blob gas tastes of "slime and errors"

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26406]
@ChangelingRain assured me that blob chemicals would never be ingested. She was wrong.

**Comment by bgobandit** [comment]
feature, that's fucking hilarious

**Comment by Iamgoofball** [comment]
yeah uh they shouldn't actually be occuring in the wild at all

they're abstractions for effects

fuckin blobcode

who was it that touched it last again? i did the original chemblob but someone else did too

**Comment by coiax** [comment]
Blob spores make the gas when they die, and I assume that some of the smoke inhalation effects mark the chemicals as "INGESTED".

**Comment by Qbopper** [comment]
not an issue, the "error" is you making a mistake with your life by ingesting the gas tbh
