### ISSUE TITLE
If you set someone on fire their flashlight eyes stop working

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#26413]
@XDTM
@optimumtact 
I told you this was not a proper fix, and, surprise, it has caused a bug.

**Comment by XDTM** [comment]
Fun fact, the flashlight eyes fix takes into account other possible lights and being on fire instead overrides previous lights. This is why i said that we need an adjust_light proc on top of set_light, but i don't know how to add colors properly so i couldn't do it myself.

**Comment by optimumtact** [comment]
not a bug, feature

**Comment by ChangelingRain** [comment]
We don't need an adjust light proc, as putting a light-emitting object inside a mob, like a human, affects their lights properly. Doing that to both fire and flashlight eyes would be the correct solution, as you'd get the fire fight and the flashlight eye light.
Also god damn it oranges if you merge something with a bug own the fuck up.
