### ISSUE TITLE
welding an airlock on help intent damages your eyes but doesnt weld the airlock shut

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26421]
aaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by octareenroon91** [comment]
The blinding effect in welders is too early in the logic tree. Lighting cigs or paper would also blind the operator.

**Comment by QualityVan** [comment]
Not welding the airlock shut isn't a bug, change off help intent. Damaging your eyes without also starting to repair is, though.

**Comment by PKPenguin321** [comment]
It not welding it shut is intended, help intent is to repair it
