### ISSUE TITLE
Organs are stored in nullspace

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26426]
This is just dumb.

**Comment by Cruix** [comment]
If they were not, wouldn't drop-everything drop/delete people's organs?

**Comment by coiax** [comment]
Then maybe code shouldn't assume that the contents of a person is their inventory

**Comment by XDTM** [comment]
I recently added a drop_everything proc, but it only drops inventlry-slot items. The admin drop-everything instead drops all items in the contents, which would include organs.

**Comment by Cyberboss** [comment]
sadly, grepping for content iteration is nigh impossible

**Comment by Cyberboss** [comment]
I say we yolo it and deal with bugs as they arise

**Comment by XDTM** [comment]
Feature freezes: where we add bugs with refactors instead of features!

**Comment by kriskog** [comment]
Not a bug
