### ISSUE TITLE
Escape Pod computers say "Send to Asteroid" despite not going to an asteroid.

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#26434]
Server Revision: 77a1ac97c6a6bb4342a256b2a93c50df96b5a9fc 
Escape pods have the option of launching to Lavaland during a red or delta alert, or if the computer has been emagged. However, the button that does this says "Send to Asteroid" instead of "Send to Lavaland" or "Send to [Insert Name of Lavaland Planet Here]"

**Comment by minrun** [comment]
because it goes to a asteroid-lavaland place so you cant get back to the base through mining, only tele or lucky drifting

**Comment by bgobandit** [comment]
I literally cannot find where the fuck "asteroid" is coming from, it's the name field of something but idk what

**Comment by Jordie0608** [comment]
It uses the name of the pod's stationary docking port, which is still called asteroid.

**Comment by bgobandit** [comment]
I can't find that anywhere in the code or maps though, I've searched
