### ISSUE TITLE
Facehuggers will not be killed by explosions or being on fire.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#26430]
Facehuggers cannot be "killed" by explosions or being directly on fire, which means they could still jump on your face and infect you if they're not dead from those.

This is different than death by being smashed with an extinguisher or high temperatures (as usually accompanies fire), which makes them VISUALLY look dead. Sort of an oversight.

**Comment by Sligneris** [comment]
Undead facehuggers. Even in death, they can still jump you.
