### ISSUE TITLE
Can't fill the deep fryer with pills or bottles.

### ISSUE THREAD

**Issue by dannno** [tgstation/tgstation#26448]
![](http://i.imgur.com/S0gqwTM.png)

Using a bottle on it will fry the bottle while also filling it with some reagent. Unreliable and unintuitive.

![](http://i.imgur.com/fSIq9Tv.png)

Using a pill on the fryer will slip the pill inside, but will perma fuck the fryer making it unusable.

**Comment by Iamgoofball** [comment]
>>>reagent code

**Comment by Iamgoofball** [comment]
someone tag this as GFYS

**Comment by Jalleo** [comment]
Less reagent more reagent_container

**Comment by octareenroon91** [comment]
Food, bottles, glasses, and beakers are all reagent_containers though.

Maybe change the criterion to "OPENCONTAINER" with a special quick check for pills?

Styptic patches fried in omnizine should be a thing though.

**Comment by praisenarsie** [comment]
@Iamgoofball still gotta fix this!!!!!!
