### ISSUE TITLE
Camoguns make projectiles that get stuck on a turf, hitting it over and over

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26447]
>The reinforced window is hit by a meteor!
> The reinforced window is hit by a meteor!
> The reinforced window is hit by a meteor!
> The reinforced window is hit by a meteor!
> The reinforced window is hit by a meteor!
> The reinforced window is hit by a meteor!
> The reinforced window is hit by a meteor!
> The reinforced window is hit by a meteor!
> The reinforced window is hit by a meteor!
> The reinforced window is hit by a meteor!
> The reinforced window is hit by a meteor!
> The reinforced window is hit by a meteor!

How to replicate:

Use a camogun, and fire it a lot? In my experience, you can see this bug when you pass out a lot of camokits to greytide and they run around non-lethally shooting everything.

Server revision compiled on: 2017-04-22
2836a9a47e17c425161e3c5922adac729070efb4

**Comment by lordpidey** [comment]
@cyberboss according to kevinz000 this is fixed.
