### ISSUE TITLE
the top corners of meta's xenobio cold chamber can't be used by the console

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#26455]
the top row of the killroom, where the walls are
the corners and one rwall next to them can't have the cam view placed over them, but the squares of maint right above them can

**Comment by WJohn** [comment]
likely just a missing area, super easy fix.

**Comment by Penguaro** [comment]
@factoryman942 In testing, I am able to use the console to access every tile of the kill chamber easily. I was able to pick up and drop a slime on each tile of the kill room. Can you show me a picture of which tiles you are unable to access with the console?
