### ISSUE TITLE
the fryer can use any reagent

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#26458]
it runs off fucking water that's boiling not frying

**Comment by PKPenguin321** [comment]
Not a bug

**Comment by octareenroon91** [comment]
^^^
This is as intended.

The damn thing starts half-full of nutriment, not even corn or motor oil.

**Comment by PKPenguin321** [comment]
Yeah, and chems you put into it are fried into the foods, so you can poison the friers

**Comment by octareenroon91** [comment]
I suppose welder fuel and plasma should maybe ignite, for consistency, but anything else is pushing it.
