### ISSUE TITLE
Photocopying your ass gives a pixel offset to the left

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#26469]
As in, the ass photo appears shifted to the left on the sprite.

"how the fuck do you find these things bandit"
idk man

This is a very recent change, the past few days it worked just fine.

**Comment by coiax** [comment]
![image](https://cloud.githubusercontent.com/assets/609465/25362765/eb81b7a8-294d-11e7-8ebc-7ab3f72dfcce.png)

**Comment by bgobandit** [comment]
yeah that explains it better
