### ISSUE TITLE
flightsuit wearers get fucked up by glass tables

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#26461]
.

**Comment by SgtxRootbeer** [comment]
Intentional.

**Comment by Sligneris** [comment]
As do dwarves, angels, and others that supposedly fly over them/crawl under them.

**Comment by Bawhoppen** [comment]
this isn't a bug? if your feet smash into a glass table, it will break

**Comment by Shadowlight213** [comment]
Completely intentional. Not a bug

**Comment by kevinz000** [comment]
not a bug

**Comment by RemieRichards** [comment]
This is dumb.
If you land on the table, yes, fuck them up.
If they fly over the table, no they absolutely should not get hit.

**Comment by Shadowlight213** [comment]
Angels crashing into glass tables was known during the making of the original pr, I found it hilariois, asked around, and other people also found it a funny hard counter, so it was kept.
It's stupid, yes, but so is making a complex autonomous cleaning robot out of nothing but a bucket, motion sensor, and robotic arm.

**Comment by RemieRichards** [comment]
No, the first one is just flat out dumb.
The second is just funny.
