### ISSUE TITLE
AI borging factory only places a single conveyor belt underneath it when created

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#26460]
It's supposed to have three belts, the ones on the left and right aren't spawning

**Comment by Cyberboss** [comment]
It only places 1 belt in the code, seems intentional to me

**Comment by PKPenguin321** [comment]
Not intentional. Must have been changed erroneously. Anybody who plays can tell you it's supposed to have a three tile long belt

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/b12fb728abf789ea2fa20f1b4f7df1626b0a4e68/code/game/machinery/transformer.dm#L124

It's supposed to spawn one to the left and one to the right.

**Comment by Iamgoofball** [comment]
yeah it was supposed to be 3 belts

**Comment by Cyberboss** [comment]
In my testing, it spawns 3 belts just fine

**Comment by WJohn** [comment]
Happened on live server.
