### ISSUE TITLE
Unable to interact after using freedom implant while resisting

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#26466]
1. Get handcuffed
2. Pop a freedom implant, dropping the cuffs.
3. Do not move, and click on something nearby to pick it up. Notice that it works as expected.
__
1. Get handcuffed.
2. *Start resisting out of the cuffs.*
3. Pop a freedom implant, dropping the cuffs. Notice that you still have the progress bar indicating that you're resisting after the cuffs are off.
4. 🐛  Do not move, and click on something nearby to pick it up. Notice that you can't interact with anything!
5. Move a step, causing the `You fail to remove the handcuffs!` message to appear and the resisting progress bar to vanish.
6. Notice how you can now interact with things.

**Comment by UncleBourbon** [comment]
My nigga cazz dying to find the bugs for tg, may he be remembered.

**Comment by coiax** [comment]
This is due to the click delay of resisting out of cuffs, I believe

**Comment by kevinz000** [comment]
@PKPenguin321 same bug that i dealt with when i got salty bolas were stunning me for 10 ticks, kek.
