### ISSUE TITLE
Radiation storms can affect you in maint

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#26475]
I don't know whether this is a radstorm issue or a map issue, but it happened to me on Box Station, in the segment of maint one tile above the Bar APC.

**Comment by Cyberboss** [comment]
Is the Bar APC in maint? I think it's a weird thing where the APC needs to be IN the area its powering so the game doesn't see it as maint

**Comment by KorPhaeron** [comment]
Yeah, that tile is part of the bar

**Comment by Metacide** [comment]
The problem is much worse on Ceres, but also more of an issue on Meta, as there aren't that many maint areas designations to work with and it's a bother to code in more.

I think radstorms need to show which areas are safe for a longer period before actually killing everyone who thinks they're safe in maint but actually aren't. Seem shitty otherwise. At the moment on Ceres, certainly, it's "take a guess and if you're wrong you're dead".

**Comment by WJohn** [comment]
It's not a bug, it's how APCs work when connected from behind rooms, inside maintenance. They still need to be part of the room to function, so the area has to extend to the tile they're in, which is what visually looks like maintenance. The "real" solution to this is to not have APCs in maintenance at all. Boxstation and cerestation have this problem, others do not.

**Comment by Cyberboss** [comment]
the real solution is to have apcs be on the actual wall.

**Comment by bgobandit** [comment]
It's not the tile with the APC it's the tile directly above it. shitty ASCII map:

X <=== death is here
APC TILE
WALL
BAR

**Comment by Cyberboss** [comment]
The apc object is on the maint tile but pixel shifted onto the wall

**Comment by WJohn** [comment]
So unless we *undo* having APCs in maintenance, this bug isn't going anywhere.

**Comment by Cyberboss** [comment]
There are solutions to this, it shouldn't be closed just because it's hard.

**Comment by bgobandit** [comment]
@Cyberboss @WJohn no you're not getting it

this area of maintenance is 2 tiles deep. there is the tile, adjacent to the wall, that contains the APC, pixel shifted onto the wall. this is about the tile right above that.

![death](http://i.imgur.com/6xeOkbA.png)
