### ISSUE TITLE
Cargo shuttle mob lock misfunctioning

### ISSUE THREAD

**Issue by Nabski89** [tgstation/tgstation#26470]
No duh, right?

The actual issue is that someone walked into the shuttle the same second as it was about to depart, so it didn't leave. Once it "arrived" at centcom it disappeared, but didn't give credits for anything on the shuttle.

**Comment by Iatots** [comment]
Why not title it differently then?

**Comment by Dorsisdwarf** [comment]
Please name your issues in a constructive fashion, this isn't Buzzfeedhub
