### ISSUE TITLE
Borgs can reset themselves an unlimted number of times on demand

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#26472]
By having a voice analyzer attached to their reset wire. This is clever but also seems to fly in the face of borg specialization

@coiax

**Comment by bgobandit** [comment]
who the fuck figures this shit out

**Comment by XDTM** [comment]
I thought this was well known

**Comment by ChangelingRain** [comment]
this is very clever, but also very shitty and should really be removed.

**Comment by Kromgar** [comment]
Can we just go back to Borg Reset Boards?

Why was it made a wire?

**Comment by BeeSting12** [comment]
I didn't even think this was a bug. I also thought this was pretty well known

**Comment by SgtxRootbeer** [comment]
This isn't a bug, but, to get it, they make themselves vulnerable to emagging/etc. It's a vulnerability in borgs more than anything else.

**Comment by Core0verload** [comment]
This is a 100% fucking feature. And borgs getting fucked by people who overheard the reset code is a 200% feature.

**Comment by coiax** [comment]
When freeze is over, I'll change the wire to activate on cut.

**Comment by xxalpha** [comment]
>removing fun

What is this, league of legends

**Comment by coiax** [comment]
I mean, if we want to keep the reset wire, we can make it drain the cyborgs battery a great deal, make it take longer, idk.

**Comment by xxalpha** [comment]
There are plenty of ways of balancing this without neutering yet another emergent gameplay feature

**Comment by Repukan** [comment]
Make it stun borgs for 1 whole minute and add a 10% chance to explode

**Comment by Repukan** [comment]
Also xxalpha if you want to powergame Borg modules just print a lot of reset boards and lock them in a locker to drag with you :^)

**Comment by KorPhaeron** [comment]
The existence of the reset wire in the first place was too much creep towards borg flexibility

**Comment by Sligneris** [comment]
It requires setup by a human mob, makes borgs vulnerable while they're resetting, and anyone who knows their codephrase can stun them with a voice command.

That's enough vulnerabilities to balance out the advantage it provides, imo.

**Comment by PKPenguin321** [comment]
Because borgs can self change their module at will

**Comment by Sligneris** [comment]
If they went thought the effort of getting it set up, yes.

Is that a problem?

**Comment by KorPhaeron** [comment]
Yes

**Comment by Kingsableye** [comment]
you can set the code to be in binary, and thus humans can't repeat it

**Comment by DaxDupont** [comment]
Wasn't this fixed? Need to cut the reset wire now.
