### ISSUE TITLE
Drones can not weld or unweld airlocks.

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#26488]
Server revision compiled on: 2017-04-23
The following pull requests are currently test merged:
#26465: 'Fixes Advanced Proc Call' by Cyberboss 

Based off master commit:
e2e24371294fc507d9d2ef31948e47497387ee1d 

I was playing a drone and decided to clean up after someone who blocked a main hallway with high access airlocks, only to find that I could not disassemble them. As drones have no intents, they can not weld or unweld an airlock, which is a required step for their disassembly.

**Comment by Cyberboss** [comment]
Dupe of #25292
