### ISSUE TITLE
A lot of things assume sortedAreas has all areas but it doesn't

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#26494]
Need to make a new list which actually has all the areas

Someone add this to the Cyberboss milestone

**Comment by Supermichael777** [comment]
world has every area in it

**Comment by Cyberboss** [comment]
Iterating world is bad though, mmkay?

**Comment by xxalpha** [comment]
It isn't, iterating through world to find areas is optimized internally.

**Comment by Cyberboss** [comment]
Not as optimized as a regular list would be

**Comment by xxalpha** [comment]
https://github.com/tgstation/tgstation/issues/26453
