### ISSUE TITLE
Fire alarms are INCREDIBLY IRRITATING to hear.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#26505]
Fire alarms can be heard from far away, are very high pitched, and can stack as you will often find several in a small area all making that god-awful ringing noise.

The radius at which their sound plays should be MUCH smaller (2 or 3 tiles instead of 7) and perhaps make them have a delay between looping their sound or SOMETHING. It's agony to hear all those going off.

Perhaps even use a NEW sound effect for fire alarms that's *not* so insanely high pitched.

**Comment by Cyberboss** [comment]
Why did we change sounds again? Old one was fine

**Comment by banthebantz** [comment]
use this sound https://www.youtube.com/watch?v=7pg-JQyrPLw

**Comment by WJohn** [comment]
That's less a fire alarm and more a nuclear bomb warning or something extreme like that. We have something like that for radiation storms.

**Comment by Shadowlight213** [comment]
Realism feature. Fee alarms are supposed to be annoying.

**Comment by Repukan** [comment]
@Cyberboss this is not a bug, and the volume and pitch of fire alarms got lowered.
