### ISSUE TITLE
Nanotrasen bedsheets are invisible when worn

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26500]
Server revision compiled on: 2017-04-23
The following pull requests are currently test merged:
#26465: 'Fixes Advanced Proc Call' by Cyberboss 
#26493: '[DNM] Revert "Speeds up lighting initialization"' by Cyberboss 

Based off master commit:
0a1107a91b87e156a6f18a7461bfd90f3a26a36c

**Comment by XDTM** [comment]
Back to 800 issues!

**Comment by coiax** [comment]
Issues are not bad. A lack of issues is not good.

**Comment by octareenroon91** [comment]
There's a signal-to-noise issue though

**Comment by WJohn** [comment]
Dupe of #24468 
This is slightly more detailed so I'll close the other one.
