### ISSUE TITLE
Body deleted when released from infinite disposal loop via welding pipe

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#26512]
There were multiple people in the loop. Upon the loop being opened my body was deleted. Others were unaffected.

**Comment by WJohn** [comment]
Cannot seem to reproduce. I made a 2x2 disposals loop and stuffed in 9 people, then welded one of the pipes open and all 9 came back out. Can you explain this in more detail? Were you dead? How was the loop opened?

**Comment by golfer45** [comment]
I was alive before being deleted, Loop was welded open.

**Comment by WJohn** [comment]
What kind of junction was it? As much detail as possible. How many people were in the loop (can you give an estimate?) Were there other objects in there? What were you doing at the time while in the loop? Were you the first or last one to reach the now opened pipe?

**Comment by golfer45** [comment]
a few items, Nothing. Not sure, the second it open I became a ghost and my body was gone.

**Comment by WJohn** [comment]
I tested it yet again with about 7 players, all in the loop. None of them got deleted. I don't know how you did this.

**Comment by Dorsisdwarf** [comment]
Recently reproduced. nature of bug is that unwelding a disposals pipe deletes all items currently inside it @WJohn

**Comment by timothymtorres** [comment]
It looks like the `expel` proc

https://github.com/tgstation/tgstation/blob/55b92786dcf0f9c5172efd111a6ecbf83ec0dae2/code/modules/recycling/disposal/pipe.dm#L87-L116

needs to be placed somewhere inside the `deconstruct` proc

https://github.com/tgstation/tgstation/blob/55b92786dcf0f9c5172efd111a6ecbf83ec0dae2/code/modules/recycling/disposal/pipe.dm#L144-L159

**Comment by Mooshimi** [comment]
Reported to have become an issue again

**Comment by msgerbs** [comment]
Pretty sure this was fixed in #71276. I don't think we should reopen old issues because they're happening a year later, anything could've changed to cause it in that time.
