### ISSUE TITLE
5.56 and 5.56x45mm are apparently different calibers, even though they're the same thing IRL.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#26514]
5.56 does 35 brute and has a small shell casing size.

5.56x45mm does 45 brute and has a medium shell casing size.

These are the SAME THING in real life. Can we just make them both use the same 35 brute 5.56 bullets since they're both 3-hit-kills, with the l6 saw's strength relying on crazy bullet spam? 7.62 isn't an option since that does 60 bute, and is used in the mosin nagant.

**Comment by Tacolizard** [comment]
imo we should get rid of every type of ammo and start from scratch. There are way too many undocumented variants, some of which are only used in single guns.
