### ISSUE TITLE
Alt Tabbing can easily result in TOGGLING your movement to walk.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#26516]
1. Push tab (which changes your controls)
2. Alt + tab to swap windows
3. Alt + tab back into the game
4. See that your movement is now TOGGLED to walk, even after letting go of alt.
5. Be forced to either press tab (changing your controls again) to reset it, or manually click on the walk/run button.

This is pretty annoying, as alt tabbing is a thing I do all the time, so I have this happen to me constantly. I'm guessing this is more an oversight than a bug.

**Comment by xxalpha** [comment]
Wasn't this fixed?

**Comment by WJohn** [comment]
I'm still getting it so no.

**Comment by xxalpha** [comment]
Update Byond, I think.

**Comment by Cyberboss** [comment]
This was a byond bug and was fixed. Update byond #23537

**Comment by WJohn** [comment]
Oh! Alright, thank you.
