### ISSUE TITLE
Sniper rifle zoom function is very bugged.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#26515]
Firing at a corpse will cause the bullet to horribly miss the target, but only when firing from just beyond 7 tiles (8 will display this best) It becomes more accurate at higher range once again (not noticeable at 14 tiles). This ONLY occurs when firing specifically at a corpse. Living humans will cause it to fire as normal, and be perfectly accurate.

Firing the gun within your normal line of sight range <=7 tiles while zoomed in will cause you to fire BEHIND YOU.

Ghosting while zoomed in will keep you zoomed in, and you will be unable to go back to normal. Cancel-camera-view will not save you.

**Comment by Robustin** [comment]
Kind of a dupe of what I put up: https://github.com/tgstation/tgstation/issues/24415

I don't think your issue is specific to corpses, though I have never had a shot go behind me either.

**Comment by WJohn** [comment]
Looking at your issue, I think mine has more detail on how bugged the zoom is, so I'm closing yours.

**Comment by WJohn** [comment]
The ghosting with your view still zoomed in a direction is still bugged. Reopening.
![](https://i.imgur.com/tfaovSL.png)

I am way off to the right, any time I orbit something my view shifts accordingly. Cancel camera view still won't save you.

**Comment by WJohn** [comment]
This has been fixed.
