### ISSUE TITLE
Lighting errors, game lag

### ISSUE THREAD

**Issue by Charmisokay** [tgstation/tgstation#26523]
Server revision compiled on: 2017-04-23
0a1107a91b87e156a6f18a7461bfd90f3a26a36c 

After putting on some masons in lavaland, my game grinded to a halt, screen turned into pic related and I couldn't use my hands (you look at your arm and sigh), and I was unable to swap between control modes. I was also unable to see the OOC chat. 

Restarting the game did not fix this, but when the round was over the problem fixed itself.

Apparently everyone suffered from the same error. 
![image](https://cloud.githubusercontent.com/assets/25822752/25337627/e49c246a-28fc-11e7-92a9-054ea0a89200.png)

**Comment by GunHog** [comment]
I LOVE that lava, though! We should have some of that extra bright lava in certain locations!

**Comment by Charmisokay** [comment]
It does actually look pretty cool. After the round OOC chat speculated that this all might have happened because of freon flooding.

**Comment by Jalleo** [comment]
Which server is this? Also version of byond client please. Encase its relevant.

**Comment by Tacolizard** [comment]
install the june 2010 directx sdk, report back if it's fixed. specs of your comp would be nice as well

**Comment by Charmisokay** [comment]
It happened on Sybil moments before I posted this, and I think it was a server-wide issue as people in the next round were asking "what happened?" 
Byond should be the most recent update, as I was unable to update it after the issue occured. 
My system, with windows 10: 
![image](https://cloud.githubusercontent.com/assets/25822752/25375652/a5b3d252-29a1-11e7-891c-faa097c2c458.png)

As I mentioned, the issue fixed itself when the round ended (Maybe the server rebooted?). I don't know how to reproduce the glitch, but there had been a freon flood shortly before this all happened.

**Comment by Tacolizard** [comment]
admin fuckery mabye?

also thanks for the specs. There's an unlikely possibility it has something to do with your gpu.

**Comment by Charmisokay** [comment]
I'll report to you if it happens again.

**Comment by Tacolizard** [comment]
or we cold apply small amounts of it to create bloom effects

**Comment by WJohn** [comment]
![](http://i.imgur.com/c6PPXt5.png)

I managed to replicate this by OBSERVING (not orbiting) a simple animal. Other things might cause this, but simple animals, such as slimes, work best to cause this.

**Comment by MrStonedOne** [comment]
Oh hey, I'll look to see if this can be used to make excessive light flaring.

Since it's per client, I might even be able to do things like let you adjust to light levels such that hiding in maint makes total darkness slightly less dark but going back in light makes it all saturated and over bright.

Also a good reason to bring back shadowling. less thrills/super antag and more side antag thats about making maint/darkness scary.

**Comment by ShizCalev** [comment]
Also see #29663

**Comment by Daturix** [comment]
Had this issue with a drone ahleping it, they ghosted and then put back into their body and it was fixed.

**Comment by ShizCalev** [comment]
Able to trigger it consistently by disconnecting and reconnecting as a simple_animal.

**Comment by MrStonedOne** [comment]
This is the lighting rendering planes getting added multiple times to the client's screen list.

**Comment by kriskog** [comment]
Never seen this, closest I've got was the washed out lighting/textures when reconnecting into oom crashes last year. Also cant reproduce, I assume this is fixed somewhere.
