### ISSUE TITLE
Omega Station has two APCs not wired properly

### ISSUE THREAD

**Issue by flashdim** [tgstation/tgstation#26526]
The Central Hall APC and Primary Hall APC don't have wiring knots under them, so the terminals don't connect by default.

Needs to be:
![image](https://cloud.githubusercontent.com/assets/11363274/25353184/6ebbccb4-28fc-11e7-8907-f349a48b17f3.png)

Instead of:
![image](https://cloud.githubusercontent.com/assets/11363274/25353197/7493c97a-28fc-11e7-8464-a34c53b7c9fe.png)

Posting to confirm as an issue since I'm not as familiar with mapping as others. Also tried out the mapmerge tool to make a patch, file is attached.

[OmegaStation.dmm.diff.zip](https://github.com/tgstation/tgstation/files/952849/OmegaStation.dmm.diff.zip)

**Comment by BeeSting12** [comment]
@flashdim 
Are you making a PR to fix this?

**Comment by flashdim** [comment]
I've honestly never done them before. Would this be a good issue for a first try?

**Comment by BeeSting12** [comment]
Yeah, map issues are usually pretty easy to do. Read the wiki guide and go to #coderbus on rizon.net if you have any questions. Just remember to use the map merge tools before and after you make the changes or you'll have a huge line diff, looks like you remembered to do that though.

**Comment by BeeSting12** [comment]
Here are the relevant wiki pages:
https://tgstation13.org/wiki/Setting_up_git
https://tgstation13.org/wiki/Map_Merger
https://tgstation13.org/wiki/Getting_Your_Pull_Accepted

**Comment by flashdim** [comment]
Thanks for the assist - I'll get a PR in.

**Comment by WJohn** [comment]
Literally all that needs to be done is putting a knot on that tile. That's it. You can make another wire knot your active object (right click on that tile, go to the knot, make active object) and ctrl+click on the the tile shown above.

Most mapping issues are effortless "easy fix" things like this that are one or two button presses to do.

**Comment by flashdim** [comment]
@WJohn Thanks! I noticed there were more changes to Omegastation today prior to the updates I made getting submitted. Should I cancel and resubmit the pull request?

**Comment by flashdim** [comment]
Resubmitted just to make sure I include the turf fixes made earlier today.

**Comment by BeeSting12** [comment]
@optimumtact 
please close this as it is fixed

**Comment by optimumtact** [comment]
@flashdim for future reference if you include a line like the following in your Github PR desc

Fixes #26526

Then it will be closed automatically when the PR is merged
