### ISSUE TITLE
Transparent turf on Deltastation Auxillary Tool Storage

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26531]
![image](https://cloud.githubusercontent.com/assets/609465/25361007/b27fdd0e-2943-11e7-96ac-125de221a248.png)

**Comment by WJohn** [comment]
We're gonna be cleaning up after antur's decal tool for months, aren't we?

**Comment by BeeSting12** [comment]
@optimumtact @WJohn 
This is fixed by #26541
