### ISSUE TITLE
you can see holodeck floortiles while ventcrawling

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26532]
![dreamseeker_2017-04-24_21-37-19](https://cloud.githubusercontent.com/assets/16103879/25361342/5d7a78ec-2956-11e7-85f5-c22ea0567fb7.png)

**Comment by Incoming5643** [comment]
you have the bug backwards, you're supposed to see all floor tiles when crawling ala meson vision.

This is a dupe of an issue I can't look up offhand...

**Comment by Militaires** [comment]
hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
