### ISSUE TITLE
You can piggyback out of a choke/strangle

### ISSUE THREAD

**Issue by obscolene** [tgstation/tgstation#26545]
1. Get choked
2. Clickdrag your sprite onto the choker's
3. Stand up and be free
It doesn't even matter if you're on the same tile as the choker, you can still do it.
You do not actually piggyback onto the person, you just become ungrabbed and stand up instantly.
This makes choking literally useless. In my opinion, being able to get out of an aggressive grab via piggybacking was fine. Choking, not so much.
This also creates a notification in the top-right of the screen, indicating that you are piggybacking on someone. But you are not. I am currently unaware of how to remove this notification, but I have seen it disappear on occasion. 
@kevinz000

**Comment by WJohn** [comment]
There was a PR to nerf piggybacking times bu it was closed due to the freeze. #26480 
It should be re-opened shortly.

**Comment by obscolene** [comment]
Except this one includes choking as well. I'm 90% sure this is a new bug that has arisen somehow, because I do not recall being able to get out of a choke (not just aggro grab) via piggybacking prior to a few days ago.
