### ISSUE TITLE
Admins' Egalitarian Station Mode button is broken

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#26553]
Supposed to make all airlocks all access; did not. This was on Omega Station, might be a map issue?

**Comment by octareenroon91** [comment]
Command areas were still secure?

**Comment by Shadowlight213** [comment]
Egalitarian station makes all non sec and non command departmental airlocks all access.

If sec and command are still locked, that's part of it and not a bug.

**Comment by bgobandit** [comment]
yeah it was in fact command, honk
