### ISSUE TITLE
Dead people can still dance on the disco machine

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation#26555]
![](https://file.house/YTXO.png)

![](https://file.house/C3Em.png)

@Robustin

**Comment by kevinz000** [comment]
NECRODANCER!!!

**Comment by Kromgar** [comment]
I think we should give wizards a spell version of this so we can have necrodancers

**Comment by Robustin** [comment]
My PR fixed this fam. Go merge it.

**Comment by optimumtact** [comment]
What pr

**Comment by InsaneHyena** [comment]
Not a bug

**Comment by ExcessiveUseOfCobblestone** [comment]
Great feature, Robustin.

**Comment by optimumtact** [comment]
@Robustin can you identify the pr so I can close this please?
