### ISSUE TITLE
Omega station lacks a centcom ferry dock

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#26554]
See title.
Just like delta didn't have one until recently, omega does not have one.

**Comment by WJohn** [comment]
Will require some more extensive mapping to integrate this one, as arrivals will need a fair bit of changing around to accommodate this, especially given how small omega station is in general.

**Comment by Bawhoppen** [comment]
or have a unique station and don't have one

**Comment by Shadowlight213** [comment]
@Bawhoppen how does not having one make the map unique? It's an expected feature in every map that breaks stuff if it's not there.
Would you consider a map without an emergency shuttle dock or arrivals shuttle "unique" and request that one not be added?

**Comment by Bawhoppen** [comment]
A station with no shuttle and only pods could be fun.

Just because it's expected doesn't mean it needs to be there.

In this case though, it seems fairly reasonable to have it. I was just bringing up a different point of view.

**Comment by Penguaro** [comment]
@Shadowlight213 I'm working on this. I noticed that there isn't a whiteship either and some of the other maps don't have one either. Do you think that's necessary as well?
