### ISSUE TITLE
Safe malfunctioning

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#26567]
A player asked for help but I really, really don't understand how safes work.

http://puu.sh/vvVG1/ac66f7c24b.png

**Comment by KorPhaeron** [comment]
The safe has been able to generate impossible combos for like five years now

**Comment by ExcessiveUseOfCobblestone** [comment]
That's why it's /safe/ :^)

**Comment by PKPenguin321** [comment]
>The safe has been able to generate impossible combos for like five years now

On that note this issue is a dupe of an accent issue

**Comment by Tacolizard** [comment]
the entire safe system needs to be rewritten

**Comment by ShizCalev** [comment]
Duplicate of #12474
