### ISSUE TITLE
if you're hallucinating and you die your dead body will keep jumping around

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26562]
Oat Ismm jumps backwards, falling on the ground!
Oat Ismm jumps backwards, falling on the ground!
Oat Ismm jumps backwards, falling on the ground!

my dead headless body was feared by the station, oat ismm was known as a cursed man...

**Comment by XDTM** [comment]
why are hallucinations ticking when there's no life ticks

**Comment by AnturK** [comment]
Hallucination processing is in separate spawn since times immemorial. Needs a refactor.

**Comment by timothymtorres** [comment]
This was probably fixed with #56422 or #55927.  If this problem still persists ping me and I will reopen this.
