### ISSUE TITLE
If we are going to make mob's hard delete, we still have to clear their references.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#26568]
See: Title

Basically, if by the time Del() runs, the mob has no outside references (other than the stack that called Del() on it) byond reverts to a soft delete, even then, if it only has one or a few, that's still massively less references 

Atm hard deleting mobs is taking 7 to 10 byond ticks  (0.3 to 0.5 seconds) ***per mob***

**Comment by Cyberboss** [comment]
We should probably have a mob directory mobid -> mob and enforce that anything that wants to reference a mob and doesn't have it in it's contents or isn't a child var of the mob reference it via id.

**Comment by Cyberboss** [comment]
```
$ git grep "var/mob" | wc -l
2893
```

Ugh...

**Comment by MrPerson** [comment]
If we had a handle on all the mob references, we wouldn't need to hard del them in the first place

**Comment by Cyberboss** [comment]
Better to move towards that now then never, then

**Comment by Cyberboss** [comment]
@vuonojenmustaturska did a good job clearing up most offenders
