### ISSUE TITLE
I don't even know what this is. Oh and ignore the Coiax line, but yeah, everyone's deathgasping before server init.

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#26577]
https://gyazo.com/5e17df08ad61d3869347d5ac10f7e59e

**Comment by Kromgar** [comment]
That is fucking horrifying

**Comment by Repukan** [comment]
The old crew is killed before the fresh clones are teleported into the fixed station. Sometimes glitches occur and powers or botnets in the clones neural nets are activated without NT input.

It's part of the lore

**Comment by Cyberboss** [comment]
There should not even be humans on the title screen REEE!!
