### ISSUE TITLE
Hitting a fulltile window with an artistic toolbox makes it invisible..?

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#26576]
And you can hit the grille under it? What the fuck they're supposed to be dense?
https://gyazo.com/6737169ee0cd187e5d4f5a89cb8b25d5

**Comment by TheDreamweaver** [comment]
This seems to be happening now while hitting it with anything

**Comment by AnturK** [comment]
@MrPerson side-efect of mutable appearances ?
