### ISSUE TITLE
cant move or se my hatacter after ayyliens

### ISSUE THREAD

**Issue by gustufus** [tgstation/tgstation#26573]
i played as a chaplain then while walking around the station i got hit by a advanced stunbaton and draged into a dorm, then i got teleported to the ayylien space ship they probed me and then sudenly the camera got swithed to the arival shuttle but my character was not there.

**Comment by BeeSting12** [comment]
You need to type Cancel-Camera-View in the command line. This happens when you become an abductor sometimes, wizard, etc.

**Comment by PKPenguin321** [comment]
Dupe of https://github.com/tgstation/tgstation/issues/25147
