### ISSUE TITLE
The reactive teleport armour can teleport you outside the abductor UFO

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26572]
We captured an RD, and then the armour spaced them. Given the space outside ayy UFOs is Z2, probably should either be a no-teleport zone.

**Comment by WJohn** [comment]
I thought you generally couldn't teleport while in z2? The wizard's jaunt and blink abilities don't work there, but I guess they're just DISABLED rather than blocking teleportation as soon as it's attempted.

**Comment by bgobandit** [comment]
given coordination and patience, would this allow one to teleport elsewhere in z2

**Comment by octareenroon91** [comment]
You could bring and hydrate monkey cubes for a source of attacks.

**Comment by coiax** [comment]
I know that bluespace golems teleport doesn't work.

**Comment by Dorsisdwarf** [comment]
Just tested and yes RTA absolutely does work on centcom for no apparent reason

**Comment by dragomagol** [comment]
"[RTA] used to just change coordinates, which wasn't affected by noteleport zones, but it was changed recently to use a teleport proc, so now it doesn't work in noteleport zones"
