### ISSUE TITLE
Throwing a thing or using machinery via telekinesis doesn't leave behind fingerprints for admin

### ISSUE THREAD

**Issue by ma44** [tgstation/tgstation#26571]
https://i.gyazo.com/123bf43a6c7e73e01512086c1a50d34b.gif

Telekinesis should leave a fingerprint behind (for admin reasons)

Also pretty sure that telekinesis doesn't leave fingerprints *anywhere*, which can lead to certain situations where it's hard to prove theres a tele grief if there's only one witness reporting it and the admin didn't see it.

**Comment by ma44** [comment]
Turns out this applies to mostly anything

**Comment by SpaceManiac** [comment]
Fixed by #32311 as far as I can tell
