### ISSUE TITLE
Sparks flying from Emitter's  start position in Engineering Secure Storage

### ISSUE THREAD

**Issue by Brimcon** [tgstation/tgstation#26592]
Noticing sparks are flying as if an Emitter is firing from a location it is not.

How to Produce:
Move an Emitter from Engineering Secure Storage and set it up somewhere.
Turn on Emitter.
Return to Engineering Secure Storage
Watch sparks fly.
![image](https://cloud.githubusercontent.com/assets/7198283/25411845/f8f12c30-29d3-11e7-9395-bab2bfa7ec55.png)

**Comment by WJohn** [comment]
The sparks seem to be spawned from where the emitter was first created, moving it doesn't update the location where these are meant to be spawned.

![](http://i.imgur.com/tLEgqan.png)

The red square is where I spawned the emitter for testing. After moving it to its new location and activating it, sparks came from where it spawned, not where it currently IS.

**Comment by coiax** [comment]
I think this might be my fault. I'll look into it.
