### ISSUE TITLE
The abductor console is broken

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#26593]
Alright so spawned as abductor and went on cams to scan people. I couldn't scan people with the scanner. Yes it was in scan mode and I was clicking with the scanner on them, didn't work. They were in the blue box if that matters. I decided to send my agent anyway as I figured he could stun one nigger with a meme stun stick. I went down, marked the person, and then went back. The console would not retrieve him. I know I marked him because I got the message that I did. I figure I might've done it wrong so I mark the agent and summon him and that also doesn't work.

**Comment by Core0verload** [comment]
Damn, looks like it's my fault in #26501. Will fix.

**Comment by Core0verload** [comment]
Until this is fixed: just click abductor console with scanner to sync it manually.
