### ISSUE TITLE
Planes blinking out of existence momentarily

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/tgstation#26596]
Every so often, even if viewing a completely static screen, certain planes will fail to appear for what looks to be a tick. The screen will be properly rendered missing them

The most common offender is the space plane (note: I have parallax off) but I've also seen it affect the lighting plane and in one instance only the snow around the nuke ops shuttle on z = 2 vanished for a moment.

Recent problem only manifesting in the last 48 hours.

Might be potato computer related.

**Comment by Tacolizard** [comment]
what are your specs incoming?

**Comment by Incoming5643** [comment]
Bad to Comically Bad

**Comment by Jalleo** [comment]
Report it to the byond forums it sounds like a byond bug.

**Comment by Militaires** [comment]
@incoming i also feel this, especially around shuttles

**Comment by coiax** [comment]
I have seen space blink from time to time.

**Comment by Militaires** [comment]
boom
![dreamseeker_2017-05-19_21-04-06](https://cloud.githubusercontent.com/assets/16103879/26265182/b37444bc-3ce8-11e7-9444-0504268763ce.png)

**Comment by Shadowlight213** [comment]
Had this issue as well.

**Comment by timothymtorres** [comment]
I can't find any recent reports about this.  It appears it was fixed with #32350 or #48287
