### ISSUE TITLE
"Laughter" reagent combination overlaps "Banana Honk" drink mix recipie

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#26614]
It is impossible to mix the drink "[Banana Honk](https://tgstation13.org/wiki/Guide_to_food_and_drinks#Mixed_Drinks)" because when the components are mixed, it will yield the "[laughter](https://tgstation13.org/wiki/Guide_to_chemistry#Other_Recipes)" reagent instead which isn't in the recipe via combining sugar & banana juice together.

![](https://tgstation13.org/wiki//images/0/04/BananaHonk.gif)

The cream in the mixture for banana honk does not react at all because of the laughter reagent (Banana Honk: Cream, Banana Juice & Sugar) and finish the drink because it does not react with laughter which combines first.

**Comment by octareenroon91** [comment]
>laughter can be brewed
>it breaks the Banana Honk

Solution would be to add a cream/laughter BananaHonk recipe I guess?

**Comment by FantasticFwoosh** [comment]
Well if the drink doesn't make you laugh i guess you could drain the additional unintended laughter too.
