### ISSUE TITLE
Spectral Sword alert no longer shows the owner

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#26621]
Spectral swords, as of 2 months ago, would show the user's image in the alert when they would call for aid.

Now its just a blank alert box.

I was also using this (now non-functional) code for another alert I've been working on.

**Comment by KorPhaeron** [comment]
@MrPerson could this have changed during the appearance/image thing?

**Comment by Robustin** [comment]
Sec Records still work (albeit they get more fucky with each passing month, the UI is barely usable anymore) but that image system is like 6 procs spread across 4 files, yeesh.

**Comment by PKPenguin321** [comment]
Happens for lots of ghost alerts, drones haven't been showing an image lately either

**Comment by Robustin** [comment]
Just saying it worked 2 months ago

**Comment by MrPerson** [comment]
Probably my bad, I'll look into it
