### ISSUE TITLE
Can't extract seeds from lavaland plants

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#26632]
I brought some Cactus fruit to botany, since miners get plant bags, but they couldn't extract any seeds from the mushroom fruits.

**Comment by ChangelingRain** [comment]
They're not actually hydroponics plants because that would have been effort to do.

**Comment by WJohn** [comment]
They're just basic "snack" food types, not "grown" that you can plant, though I suppose that'd be a cool feature.
