### ISSUE TITLE
You can see undershirts under EVERYTHING now

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#26635]
Recent change, I think.

**Comment by octareenroon91** [comment]
"Jumpsuits never cover undershirts"

**Comment by bgobandit** [comment]
ok but 

this is a jumpsuit: https://s7.toryburch.com/is/image/ToryBurchLLC/TB_39457_441?$trb_pdp_main_v3$

this is an undershirt: https://content.artofmanliness.com/uploads/2013/06/White-Cotton-Tank.jpg

which covers which, logically

**Comment by evsey9** [comment]
you can see undershirts under hardsuits, actually.
actually, wait, you can see undershirts over EVERYTHING.
i think i was buckled to a chair that was facing away from the screen and i STILL could see the undershirt.

**Comment by ChangelingRain** [comment]
@MrPerson

**Comment by octareenroon91** [comment]
It shows through the radiation storms layer.

**Comment by AnturK** [comment]
Just an unnecessary - sign for layer definition here: https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/carbon/human/species.dm#L364

**Comment by Enemy4465** [comment]
https://imgur.com/BjGmRCc
Good vibes.

**Comment by Bawhoppen** [comment]
this needs to be fixed sooner rather than later, it's starting to piss me off
