### ISSUE TITLE
Recharger sprite

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#26640]
right at the start of putting something into a recharger it flashes yellow like it's done even if its not

this is another one of those small things people don't report cause they're like universally known yet ignored

**Comment by WJohn** [comment]
"Universally known yet ignored"

Pretty much, actually. I've noticed this for a while and never thought to make an issue report on it. Good a time as any, I guess.

**Comment by SgtxRootbeer** [comment]
I assume this is because when you put the baton/gun in the charger, during that tick, it isn't charging, so it displays the charged sprite, and next tick, it recognizes that it should be charging and fixes the issue.

**Comment by Tacolizard** [comment]
i always thought this was just lag or something

**Comment by Tacolizard** [comment]
I'm working on a fix, I think the issue is that when a gun is inserted, the recharger calls update_icon() before starting to charge the gun.
