### ISSUE TITLE
you can abuse ratvar cogscarab spawning by queuing windows to spam the heirophant network

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26669]
i find new ways to fuck with the game constantly

![dreamseeker_2017-04-28_04-25-11](https://cloud.githubusercontent.com/assets/16103879/25510729/01cd0d9e-2bcb-11e7-9227-8edb4a77c022.png)

**Comment by coiax** [comment]
Rude.

**Comment by coiax** [comment]
Also, this only spams cogscarbs, regular servants don't hear this.
