### ISSUE TITLE
Runtime: Cannot read null.secondary_flags in ears.dm

### ISSUE THREAD

**Issue by LetterJay** [tgstation/tgstation#26673]
As the title says. This floods for a good while before DD suppresses it.

![Ears](http://i.imgur.com/WlUoMoP.jpg)

No stack trace.

Only ``proc name: on life (/obj/item/organ/ears/on_life)``

**Comment by KorPhaeron** [comment]
@coiax

**Comment by Cyberboss** [comment]
Which server was this on? We'll have to check the logs

**Comment by coiax** [comment]
This was fixed in #26442

**Comment by LetterJay** [comment]
Weird. This is the only PR that didn't mirror. Anyway, resolved, thanks.
