### ISSUE TITLE
Clown ruin disposals not working correctly

### ISSUE THREAD

**Issue by 4dplanner** [tgstation/tgstation#26674]
I forgot to report this when it first occured yesterday, so don't have server revision numbers.

In the clown ruin, I would get into the provided disposals chutes, but would then be ejected partway through the pipes. This happened both from the early exit chute, and the one next to the staff of the honkmother. In both cases, I was ejected on a turf with a floor tile and no outlet.

**Comment by Anonmare** [comment]
I got caught in that and assumed it was intended

**Comment by 4dplanner** [comment]
I went in the clown ruin a while back, and it didn't act like this.

**Comment by ShizCalev** [comment]
Everything looks good on the map itself.

From what I'm seeing, it looks like the pipes under the indestructible floor (pretty much anything that isn't plating) are getting deleted. I'm unable to duplicate the issue when copying clown planet ruins to the main station, so I think it might be an issue with away mission generation.

**Comment by ShizCalev** [comment]
fixed.
