### ISSUE TITLE
Weed killer grenade runtime

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26675]
[14:49:01] Runtime in chem_grenade.dm,357: Cannot execute null.add reagent().
  proc name: New (/obj/item/weapon/grenade/chem_grenade/antiweed/New)
  src: the weedkiller grenade (/obj/item/weapon/grenade/chem_grenade/antiweed)
  src.loc: the floor (90,211,10) (/turf/open/floor/plasteel)
  call stack:
  the weedkiller grenade (/obj/item/weapon/grenade/chem_grenade/antiweed): New(the floor (90,211,10) (/turf/open/floor/plasteel))
  /dmm_suite (/dmm_suite): create atom(/obj/item/weapon/grenade/chem_... (/obj/item/weapon/grenade/chem_grenade/antiweed), the floor (90,211,10) (/turf/open/floor/plasteel))
  /dmm_suite (/dmm_suite): instance atom(/obj/item/weapon/grenade/chem_... (/obj/item/weapon/grenade/chem_grenade/antiweed), /list (/list), the floor (90,211,10) (/turf/open/floor/plasteel), 0)
  /dmm_suite (/dmm_suite): parse grid("\n/obj/structure/table/reinfor...", "aX", 90, 211, 10, 0)
  /dmm_suite (/dmm_suite): load map impl(_maps/RandomRuins/SpaceRuins/a..., 79, 200, 10, 1, null, null)
  /dmm_suite (/dmm_suite): load map(_maps/RandomRuins/SpaceRuins/a..., 79, 200, 10, 1, null, null)
  Biological Storage Facility (/datum/map_template/ruin/space/zoo): load(space (79,200,10) (/turf/open/space/basic), 1)
  the random ruin (/obj/effect/ruin_loader): Load(/list (/list), Biological Storage Facility (/datum/map_template/ruin/space/zoo))
  seedRuins(/list (/list), 1, /area/space (/area/space), /list (/list))
  Mapping (/datum/controller/subsystem/mapping): Initialize(497069)
  Master (/datum/controller/master): Initialize(10, 0)
[14:49:01] Runtime in chem_grenade.dm,357: Cannot execute null.add reagent().
  proc name: New (/obj/item/weapon/grenade/chem_grenade/antiweed/New)
  src: the weedkiller grenade (/obj/item/weapon/grenade/chem_grenade/antiweed)
  src.loc: the floor (90,211,10) (/turf/open/floor/plasteel)
  call stack:
  the weedkiller grenade (/obj/item/weapon/grenade/chem_grenade/antiweed): New(the floor (90,211,10) (/turf/open/floor/plasteel))
  /dmm_suite (/dmm_suite): create atom(/obj/item/weapon/grenade/chem_... (/obj/item/weapon/grenade/chem_grenade/antiweed), the floor (90,211,10) (/turf/open/floor/plasteel))
  /dmm_suite (/dmm_suite): instance atom(/obj/item/weapon/grenade/chem_... (/obj/item/weapon/grenade/chem_grenade/antiweed), /list (/list), the floor (90,211,10) (/turf/open/floor/plasteel), 0)
  /dmm_suite (/dmm_suite): parse grid("\n/obj/structure/table/reinfor...", "aX", 90, 211, 10, 0)
  /dmm_suite (/dmm_suite): load map impl(_maps/RandomRuins/SpaceRuins/a..., 79, 200, 10, 1, null, null)
  /dmm_suite (/dmm_suite): load map(_maps/RandomRuins/SpaceRuins/a..., 79, 200, 10, 1, null, null)
  Biological Storage Facility (/datum/map_template/ruin/space/zoo): load(space (79,200,10) (/turf/open/space/basic), 1)
  the random ruin (/obj/effect/ruin_loader): Load(/list (/list), Biological Storage Facility (/datum/map_template/ruin/space/zoo))
  seedRuins(/list (/list), 1, /area/space (/area/space), /list (/list))
  Mapping (/datum/controller/subsystem/mapping): Initialize(497069)
  Master (/datum/controller/master): Initialize(10, 0)
[14:49:01] Runtime in chem_grenade.dm,357: Cannot execute null.add reagent().
  proc name: New (/obj/item/weapon/grenade/chem_grenade/antiweed/New)
  src: the weedkiller grenade (/obj/item/weapon/grenade/chem_grenade/antiweed)
  src.loc: the floor (90,211,10) (/turf/open/floor/plasteel)
  call stack:
  the weedkiller grenade (/obj/item/weapon/grenade/chem_grenade/antiweed): New(the floor (90,211,10) (/turf/open/floor/plasteel))
  /dmm_suite (/dmm_suite): create atom(/obj/item/weapon/grenade/chem_... (/obj/item/weapon/grenade/chem_grenade/antiweed), the floor (90,211,10) (/turf/open/floor/plasteel))
  /dmm_suite (/dmm_suite): instance atom(/obj/item/weapon/grenade/chem_... (/obj/item/weapon/grenade/chem_grenade/antiweed), /list (/list), the floor (90,211,10) (/turf/open/floor/plasteel), 0)
  /dmm_suite (/dmm_suite): parse grid("\n/obj/structure/table/reinfor...", "aX", 90, 211, 10, 0)
  /dmm_suite (/dmm_suite): load map impl(_maps/RandomRuins/SpaceRuins/a..., 79, 200, 10, 1, null, null)
  /dmm_suite (/dmm_suite): load map(_maps/RandomRuins/SpaceRuins/a..., 79, 200, 10, 1, null, null)
  Biological Storage Facility (/datum/map_template/ruin/space/zoo): load(space (79,200,10) (/turf/open/space/basic), 1)
  the random ruin (/obj/effect/ruin_loader): Load(/list (/list), Biological Storage Facility (/datum/map_template/ruin/space/zoo))
  seedRuins(/list (/list), 1, /area/space (/area/space), /list (/list))
  Mapping (/datum/controller/subsystem/mapping): Initialize(497069)
  Master (/datum/controller/master): Initialize(10, 0)

**Comment by Cyberboss** [comment]
Reagents are created in Initialize, port them to Initialize
