### ISSUE TITLE
Librarians who die and get cloned lose their languages

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26682]
I am aware this bug exists, I'm working on fixing it.

**Comment by TrustyGun** [comment]
Wait, does this apply to all languages, e.x Ratvar?

**Comment by coiax** [comment]
When you put a ratvar mind in a new body, it "converts" that body anew, which readds the language.

Any modification of a mob's languages from its baseline will generally fall afoul of this. I knew that this was a design flaw in the system that I ported, I'm working on fixing it.

**Comment by bgobandit** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
Not my bug

**Comment by KorPhaeron** [comment]
Also its canon because he hit his head when he died and fell over so he forgot

**Comment by jughu** [comment]
then he should just be like ooga booga

**Comment by jughu** [comment]
Make braindamage make you say things in random languages when

**Comment by octareenroon91** [comment]
> ,0 for common
>`0 for inarticulate shouting in common
