### ISSUE TITLE
Disconnect on VV again.

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#26688]
#10881 is back with a vengeance

Reproduction: 
Box, Version b216423d3e6d1fe438b8a2bf491350f2f2829cb9 

VV Center of station gateway (works)
Set awaygate to any reference
VV again (disconnect)
UPDATE /obj/machinery/gateway/centerstation SET awaygate = null
VV again (works)

**Comment by lordpidey** [comment]
Well, I'm not surprised.

The "fix" I implemented was a terrible patch job that treated the symptom rather than the disease (which may or may not be a BYOND issue).

**Comment by timothymtorres** [comment]
#31511 or #31556 appears to have fixed this.
