### ISSUE TITLE
The syndicate lava base message console does not have a key

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#26683]
Without the necessary key you cannot use the computer console for message monitoring (like on the station), and the provided paper supposedly with the key on is blank.

![](http://puu.sh/vz7sj/c38ed5bc83.png)

**Comment by ma44** [comment]
Related to #26665

**Comment by ExcessiveUseOfCobblestone** [comment]
that's actually a dupe because they're the same.

**Comment by FantasticFwoosh** [comment]
My mistake

> Close & delete this then please, i made a mistake.
