### ISSUE TITLE
Proximity Sensors are completely broken

### ISSUE THREAD

**Issue by deathride58** [tgstation/tgstation#26699]
Problem Description: Title. The Proximity Sensor's arming timer does not count down at all, and they do not function at all when armed.

What did you expect to happen: For Proximity Sensors to do as they say on the tin, and for their arming timers to count down

What happened instead: Proximity arming timer is stuck at whatever the timer is set to, and Proximity Sensor does not sense anything in proximity, thus being useless.

Why is this bad/What are the consequences: Proximity Sensors are just paperweights instead of, y'know, proximity sensors.

Steps to reproduce the problem: 1. Grab proximity sensor. 2(OPTIONAL). Attach igniter or signaler. 3. Arm proximity sensor or set the arming timer. 4. Watch as the proximity sensor sits there, doing literally nothing even if it's armed

Server: Local server. Also occurs on Sybil judging from a quick test.

Revision: b216423d3e6d1fe438b8a2bf491350f2f2829cb9

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Pretty sure the recent proximity sensing rework PR broke things.

**Comment by optimumtact** [comment]
@Cyberboss

**Comment by CosmicScientist** [comment]
@optimumtact this is still a problem. I can't get igniter + proximity assemblies to work. Haven't tested proximity sensors alone.

Round ID: 76005
Server revision compiled on: 2017-09-11
[df6e70](https://github.com/tgstation/tgstation/commit/df6e7045f8a80800d86702ae76feafebc4be711f)

**Comment by Cyberboss** [comment]
There's an issue open for that

**Comment by CosmicScientist** [comment]
So there is. I couldn't find it before.
