### ISSUE TITLE
Banana Honk drink chemical is called "Banana Mama"

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#26690]
The "Banana Honk" drink is created but as the title suggests when it is analysed with bartending/reagent reading glasses or in a dispenser it will read out as "Banana Mama" really they should be consistent with one another.

**Comment by bgobandit** [comment]
WHY IS THE BANANA HONK OF ALL THINGS SO BUGGY

**Comment by FantasticFwoosh** [comment]
Gee its like you didn't even playtest it.
