### ISSUE TITLE
Fire can freeze over

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#26697]
A COLD DAY IN HELL @Iamgoofball 

![image](https://cloud.githubusercontent.com/assets/6778786/25551756/cdaed244-2c57-11e7-9608-935296410012.png)

Release freon and plasma at the same time start a fire to reproduce

Fire doesn't normally have that rounded look that the ice cube sprite has

**Comment by Armhulen** [comment]
And hell froze over

**Comment by Bawhoppen** [comment]
the snowflake freon freezing is a bit silly

we need a generalized freezing system

**Comment by Iamgoofball** [comment]
this is the 50th time this "issue" hass been reported, it's not a bug

**Comment by duncathan** [comment]
it's not a bug so I'm closing it but I want it to be known that I hate freon and this is among the reasons

**Comment by Kromgar** [comment]
@Iamgoofball @duncathan  HOW IS THIS NOT A BUG? WHY WOULD FIRE FREEZE

**Comment by duncathan** [comment]
it's intended behavior, regardless of the fact that it's stupid
