### ISSUE TITLE
Spectral Sword sprite isnt removed when you drop it

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#26703]
![image](https://cloud.githubusercontent.com/assets/6778786/25552240/8efd6816-2c62-11e7-96c0-d1bfb311d361.png)

![image](https://cloud.githubusercontent.com/assets/6778786/25552313/2b5e3a5e-2c64-11e7-8c35-2f4da7401f72.png)

It stays there even if you gib yourself via suicide

**Comment by Repukan** [comment]
Wtf why is the helmet detached

**Comment by Kromgar** [comment]
@Repukan Oh more bugs wew

**Comment by WJohn** [comment]
I noticed this with a bone axe recently, it wouldn't come off my left hand. I wielded, dropped, equipped it on my back, put something else in my left hand, the sprite was stuck there. Couldn't reproduce.

**Comment by Kromgar** [comment]
@WJohn one round i had two spectral swords and two plasma cutters in my hands

**Comment by praisenarsie** [comment]
Dupe or similar to https://github.com/tgstation/tgstation/issues/26968

**Comment by Kromgar** [comment]
Havn't seen this issue in AGES so i'm closing this
