### ISSUE TITLE
Supermatter singulo spams logs on its position.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#26711]
![](http://i.imgur.com/uUi9BLh.png)

Nonstop this.

**Comment by Tokiko1** [comment]
Pretty sure that is actually the tesla ball throwing a warning for every new tesla ball that it spawns.

**Comment by lzimann** [comment]
Tesla used to spam this but iirc it was fixed. Probably something else.

**Comment by WJohn** [comment]
Definitely seems to be tesla. I had a couple of these on centcom and they spammed one every time they added an orbiting tesla ball.

**Comment by YPOQ** [comment]
#34181
