### ISSUE TITLE
If you use instant summon in drake form you can use the staff of the hierophant with no arms

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#26710]
![image](https://cloud.githubusercontent.com/assets/6778786/25555896/e323a07e-2cbf-11e7-9d38-f84dbf3539ce.png)

**Comment by Expletive** [comment]
If you kill that many Megafauna in one round, you deserve it.

**Comment by Kromgar** [comment]
@Expletive its only 2 megafauna.

Instant summons is from tendrils

**Comment by coiax** [comment]
How can you use it though? Doesn't it require using a hand?

**Comment by Kromgar** [comment]
@couax i wasnt the drake so not sure

**Comment by blobbernaut** [comment]
feature

**Comment by PKPenguin321** [comment]
This is a dupe but I can't find the old issue. Basically you can use instant summons as a non human mob and it breaks everything

**Comment by dragomagol** [comment]
Seems to have been fixed, teleports the club to your location but you're not holding it and can't use it.
