### ISSUE TITLE
Spawner grenades grammer error.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#26733]
![](http://i.imgur.com/j5qySD9.png)

Occurs on all spawner grenades, so space carp, soap etc.

Yes, the title was intentionally misspelled. Definitely not an accident.

**Comment by Bawhoppen** [comment]
there's an easy fix tag too

**Comment by Repukan** [comment]
Don't you mean grammar

**Comment by WJohn** [comment]
don't you mean SHUTUP

**Comment by BeeSting12** [comment]
shut up*

**Comment by BeeSting12** [comment]
isnt this admin only?

**Comment by BeeSting12** [comment]
oh wait, it spawns with the slipocalypses. my bad!
