### ISSUE TITLE
Cult deconversion is broken

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#26741]
Nothing happens when you drink holy water

**Comment by Repukan** [comment]
So I guess just killing is the new meta?

**Comment by KorPhaeron** [comment]
>new

**Comment by lzimann** [comment]
It is not broken. It takes the exact time stated in the holy water [`on_mob_life` ](https://github.com/tgstation/tgstation/blob/master/code/modules/reagents/chemistry/reagents/other_reagents.dm#L209)
