### ISSUE TITLE
So drake corpses can fly 

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#26753]
![image](https://cloud.githubusercontent.com/assets/6778786/25568532/cc4c2376-2dd2-11e7-8322-24110dfca954.png)

I killed it when it began its swoop and this is when it was swooping in to land. The corpse sprite chased me and when it landed back the drake looked alive and i was shitting bricks

**Comment by Repukan** [comment]
Gee bill how come your mom let's you have THREE seclites?

**Comment by Kromgar** [comment]
@Repukan I like the extra vision at shift start
