### ISSUE TITLE
Eggs do not act as xeno traps

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26766]
1) Be unprotected human.
2) Stand next to xeno egg.
3) You will fall unconscious, but not actually have the facehugger on you, or be infected. The Facehugger's examine will say it is "not active".

**Comment by coiax** [comment]
@Cyberboss

**Comment by Cyberboss** [comment]
If this is a proximity sensor issue (#26699), you shouldn't be falling unconsious...

**Comment by XDTM** [comment]
My bad, i forgot about eggs when refactoring huggers. It should call Leap instead of Attach in line 301.
