### ISSUE TITLE
Nanomed plus cannot be deconstructed or repaired

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#26763]
Since the nanomed isn't considered a constructable vendor, it cant be deconstructed. However, this also means it cannot be repaired. Since everything can break now, we really need a way to fix stuff that can't be rebuilt.

**Comment by Tacolizard** [comment]
The thing is, it also can't be damaged. Bagil just had a round where a nanomed got rampant brand intelligence and we couldn't axe it to death because it wouldn't take damage

**Comment by octareenroon91** [comment]
I don't see a way for mimic machines to shrug off all damage.
