### ISSUE TITLE
[Cerestation] The armory is too secure.

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#26761]
Revision: 862a3d80c817831dba73d9f465b846489fc3c269 

On other maps the Armory is left relatively unsecured to attackers in space, usually only having only a single layer reinforced wall blocking access, while on Cerestation, it's protected not only by a double layer of reinforced wall, but also 4 or more layers of rock that has to be broken through either with explosives or a pickaxe.

**Comment by PKPenguin321** [comment]
I agree, but this isn't a bug

**Comment by Bawhoppen** [comment]
map-specific non-bug balance issues are for the feedback thread

**Comment by KorPhaeron** [comment]
Not a bug
