### ISSUE TITLE
can't move or do anything command wise after getting gibbed as ghost

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/tgstation#26781]
get killed
get cloned
whilst cloning, you are a ghost.
your cloned body/pod gets emped and you are mush
your ghost is now bugged

reconnect fixes bug

**Comment by QualityVan** [comment]
Can't reproduce this on latest revision

**Comment by LanCartwright** [comment]
I'll try to run the events that caused this:
Die.
Scanned in cloner.
Cloner activates and I begin cloning.
At this time, I am a ghost and can look around.
Whilst ghosting and looking around, I suddenly hear a scream.
The cloning pod was likely EMP flashlight hit.
I am gibbed.
Bug occurs.

**Comment by QualityVan** [comment]
The pod was both emagged, which causes the gibbing, and EMP'd?

**Comment by LanCartwright** [comment]
I think it was EMP'd since the pod wasn't completely disabled.
I'm fairly sure I was hit by an EMP flashlight.
It's a strange bug that was fixed by reconnecting. If it can't be duped, I don't know what lead to it.

**Comment by ShizCalev** [comment]
Gonna close in a week without another repo.
