### ISSUE TITLE
Speech for syndicate cyborg is broken

### ISSUE THREAD

**Issue by 4dplanner** [tgstation/tgstation#26788]
Server revision compiled on: 2017-05-01
The following pull requests are currently test merged:
#26776: 'Moves languages to a holder datum, gives mind its own language holder' by coiax 

Based off master commit:
c6ed089214d275f15954a5d1a44852fbe597d8b9 

As syndicate borg, I could not understand common over radio or in person. I could still understand binary chat.
-In addition, any attempt at speech merely resulted in a blank line being outputted.
-Language menu was completely unresponsive, clicking the button did nothing

**Comment by bgobandit** [comment]
High priority tag please, this kills tactical borgs

**Comment by WJohn** [comment]
@coiax

**Comment by coiax** [comment]
This was just the test merge. I'm aware of the bug, you can close this.
