### ISSUE TITLE
You can detonate a bomb, wait a few seconds, then get hit by the damage if you go near it afterwards. 

### ISSUE THREAD

**Issue by blobbernaut** [tgstation/tgstation#26785]
If you're not in the radius when it explodes, you shouldn't get hit.

**Comment by Kromgar** [comment]
I heard some dude detonated a bomb with 5 people right next to him beating his ass and only he was  gibbed no one else on cerestation

**Comment by blobbernaut** [comment]
mso bombcode sucks

**Comment by Kromgar** [comment]
@blobbernaut Actualy it's due to a recent update by uh... coiax i think? Its one of the bluetide

**Comment by factoryman942** [comment]
the explosions' effect goes at a rate of one tile per year

**Comment by kevinz000** [comment]
not a bug this is just lag..?

**Comment by Dorsisdwarf** [comment]
if the system is broken to the point where minor to median lag totally gimps bombs then its a bug

**Comment by Cyberboss** [comment]
This was from the test merge of #26361, close it
