### ISSUE TITLE
Changeling genetic damage has no indicators at all on how it works

### ISSUE THREAD

**Issue by lzimann** [tgstation/tgstation#26782]
So, pretty much yesterday I discoreved about this, each time you use ling power you will have a "genetic damage", probably to prevent spamming too much of a power, that's fine. But the problem with this, is that there is 0 indication on what is going on, the only time you discover is when you try to use a power/sting someone.

**Comment by Kromgar** [comment]
>Revive
>Keep wanting to use that power that melts handcuffs 30 seconds of being alive and keep getting this alert

**Comment by XDTM** [comment]
There should be a HUD element for it

**Comment by PKPenguin321** [comment]
Just remove this system and apply proper cooldowns to ling powers like wizard spells use, it was always shit

**Comment by Robustin** [comment]
Chems are limited enough now and fleshmend has a more aggressive diminishing return, I simply don't see the need for this system at all.
