### ISSUE TITLE
Being bombed as a changeling can boot you to the lobby

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#26790]
Occurred roughly around 19:30 to 20:00 EST, Bagil.

**Comment by QualityVan** [comment]
Did you happen to notice whether you were gibbed? Also, you do mean lobby and not arrivals shuttle, right?

**Comment by francinum** [comment]
Gibbed, Connection lost, reconnecting sends you to the lobby.

**Comment by optimumtact** [comment]
this is more likely a byond bug

**Comment by bgobandit** [comment]
I feel like this is an old ass bug

**Comment by francinum** [comment]
This is an ancient higgs buggson.

**Comment by Iamgoofball** [comment]
we cant call them higgs bugsons anymore

**Comment by francinum** [comment]
Unified Lobby Theory?

**Comment by octareenroon91** [comment]
There's always the elusive "next sig fig of c"

**Comment by kriskog** [comment]
Closing in favor of #47720
