### ISSUE TITLE
Ashstorms not stopping after it says they stopped

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#26792]
Roughly 8:00 pm 5/1/17 EST. Basically I was on gulag and there was an ash storm. I go in and wait, it says the storm stopped. The storm overlay was gone so I went out. I started taking burn damage, went back in, healed up, walked back out and then burned to death out there.

**Comment by Kromgar** [comment]
It's a bug involving the staff of storms

**Comment by timothymtorres** [comment]
I don't see any recent issues with this in the last couple of years.  This may have been fixed with #60043, #18652, or #34633
