### ISSUE TITLE
Entire server randomly being unable to speak

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#26791]
Right, literally everyone but like 5 people on bagil were suddenly randomly unable to speak and then it fixed itself? Looked at runtime logs, saw say.dm runtiming with being unable to read null.stat or something, check runtime logs at around 5:04 pm PST I guess..

Two most common runtimes near the time of the bug

proc name: Hear (/obj/machinery/holopad/Hear)
usr: Zeus Jennings (megazeus101) (/mob/living/carbon/human)
usr.loc: The floor (156,117,1) (/turf/open/floor/plasteel/neutral/corner)
src: Holopad (/obj/machinery/holopad)
src.loc: the floor (37,139,1) (/turf/open/floor/plasteel/vault)
call stack:
Holopad (/obj/machinery/holopad): Hear("<span class=\'radio\'><span cl...", Zeus Jennings (/atom/movable/virtualspeaker), /datum/language/common (/datum/language/common), "NOT YET FAGGOT", 1459, /list (/list), null)
Broadcast Message(Zeus Jennings (/mob/living/carbon/human), 0, the research director\'s heads... (/obj/item/device/radio/headset/heads/rd), "NOT YET FAGGOT", "Zeus Jennings", "Research Director", "Zeus Jennings", 0, 0, /list (/list), 1459, /list (/list), "says", "asks", "exclaims", "yells", /datum/language/common (/datum/language/common))
the subspace broadcaster (/obj/machinery/telecomms/broadcaster/preset_left): receive information(/datum/signal (/datum/signal), the telecommunication hub (/obj/machinery/telecomms/hub/preset))
the telecommunication hub (/obj/machinery/telecomms/hub/preset): relay information(/datum/signal (/datum/signal), "/obj/machinery/telecomms/broad...", 1, 20)
the telecommunication hub (/obj/machinery/telecomms/hub/preset): receive information(/datum/signal (/datum/signal), Common Server (/obj/machinery/telecomms/server/presets/common))
Common Server (/obj/machinery/telecomms/server/presets/common): relay information(/datum/signal (/datum/signal), "/obj/machinery/telecomms/hub", null, 20)
Common Server (/obj/machinery/telecomms/server/presets/common): receive information(/datum/signal (/datum/signal), the bus mainframe (/obj/machinery/telecomms/bus/preset_four))
the bus mainframe (/obj/machinery/telecomms/bus/preset_four): relay information(/datum/signal (/datum/signal), "/obj/machinery/telecomms/serve...", null, 20)
the bus mainframe (/obj/machinery/telecomms/bus/preset_four): receive information(/datum/signal (/datum/signal), the processor unit (/obj/machinery/telecomms/processor/preset_four))
the processor unit (/obj/machinery/telecomms/processor/preset_four): relay direct information(/datum/signal (/datum/signal), the bus mainframe (/obj/machinery/telecomms/bus/preset_four))
...
the telecommunication hub (/obj/machinery/telecomms/hub/preset): relay information(/datum/signal (/datum/signal), "/obj/machinery/telecomms/bus", 1, 20)
the telecommunication hub (/obj/machinery/telecomms/hub/preset): receive information(/datum/signal (/datum/signal), the subspace receiver (/obj/machinery/telecomms/receiver/preset_right))
the subspace receiver (/obj/machinery/telecomms/receiver/preset_right): relay information(/datum/signal (/datum/signal), "/obj/machinery/telecomms/hub", null, 20)
the subspace receiver (/obj/machinery/telecomms/receiver/preset_right): receive signal(/datum/signal (/datum/signal))
the research director\'s heads... (/obj/item/device/radio/headset/heads/rd): talk into impl(Zeus Jennings (/mob/living/carbon/human), "NOT YET FAGGOT", null, /list (/list), /datum/language/common (/datum/language/common))
ImmediateInvokeAsync(the research director\'s heads... (/obj/item/device/radio/headset/heads/rd), /obj/item/device/radio/proc/ta... (/obj/item/device/radio/proc/talk_into_impl), Zeus Jennings (/mob/living/carbon/human), "NOT YET FAGGOT", null, /list (/list), /datum/language/common (/datum/language/common))
the research director\'s heads... (/obj/item/device/radio/headset/heads/rd): talk into(Zeus Jennings (/mob/living/carbon/human), "NOT YET FAGGOT", null, /list (/list), /datum/language/common (/datum/language/common))
Zeus Jennings (/mob/living/carbon/human): radio("NOT YET FAGGOT", "headset", /list (/list), /datum/language/common (/datum/language/common))
Zeus Jennings (/mob/living/carbon/human): Say(";NOT YET FAGGOT")

[23:57:33] Runtime in say.dm, line 231: Cannot read null.stat
proc name: send speech (/mob/living/send_speech)
usr: Cyrus Eridan (cy294) (/mob/living/carbon/human)
usr.loc: The floor (197,147,1) (/turf/open/floor/plasteel/red/side)
src: Cyrus Eridan (/mob/living/carbon/human)
src.loc: the floor (197,147,1) (/turf/open/floor/plasteel/red/side)
call stack:
Cyrus Eridan (/mob/living/carbon/human): send speech("W-wor-rk-k t-t-tog-g-geht-ter?", 7, Cyrus Eridan (/mob/living/carbon/human), "default", /list (/list), /datum/language/common (/datum/language/common), null)
Cyrus Eridan (/mob/living/carbon/human): say("W-wor-rk-k t-t-tog-g-geht-ter?", null, /list (/list), 1, /datum/language/common (/datum/language/common))
Cyrus Eridan (/mob/living/carbon/human): Say("work togehter?")

**Comment by octareenroon91** [comment]
Missing a filename/line number for this, though it's probably unambiguous enough:
`proc name: Hear (/obj/machinery/holopad/Hear)`
`(/obj/machinery/holopad/Hear)`
`/holopad/`

Second looks like a `null` ended up in `GLOB.player_list`
From `code/modules/mob/living/say.dm`:
````
        var/list/the_dead = list()
        for(var/_M in GLOB.player_list)
                var/mob/M = _M
                if(M.stat != DEAD) //not dead, not important
                        continue
                if(!M.client || !client) //client is so that ghosts don't have to listen to mice
````

**Comment by kevinz000** [comment]
@octareenroon91 didn't see one, or didn't look hard enough, wew

**Comment by octareenroon91** [comment]
There's literally one line missing from the top of that first runtime. There's no line number reference.

**Comment by optimumtact** [comment]
@ChangelingRain fixed this I believe

**Comment by kevinz000** [comment]
fixed ifaik
