### ISSUE TITLE
darkness has become light for me and i can only see in the dark.

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#26817]
![](http://i.imgur.com/ZbCkNfD.png)

**Comment by Militaires** [comment]
5.0 beta

511.1370

**Comment by Tacolizard** [comment]
try installing the june 2010 directx sdk, and post comp specs and os

**Comment by Militaires** [comment]
@Tacolizard i do have that

windows 7 but my specs are too embarrassing so no i wish not to fuc let's just close this
