### ISSUE TITLE
Donuts runtime

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26818]
`[19:16:16] Runtime in snacks_pastry.dm,21: Cannot execute null.add reagent().
  proc name: New (/obj/item/weapon/reagent_containers/food/snacks/donut/New)
  src: the frosted donut (/obj/item/weapon/reagent_containers/food/snacks/donut)
  src.loc: the plating (175,158,1) (/turf/open/floor/plating)
  call stack:
  the frosted donut (/obj/item/weapon/reagent_containers/food/snacks/donut): New(the plating (175,158,1) (/turf/open/floor/plating))
  /dmm_suite (/dmm_suite): create atom(/obj/item/weapon/reagent_conta... (/obj/item/weapon/reagent_containers/food/snacks/donut), the plating (175,158,1) (/turf/open/floor/plating))
  /dmm_suite (/dmm_suite): instance atom(/obj/item/weapon/reagent_conta... (/obj/item/weapon/reagent_containers/food/snacks/donut), /list (/list), the plating (175,158,1) (/turf/open/floor/plating), 1)
  /dmm_suite (/dmm_suite): parse grid("\n/obj/structure/table,\n/obj/...", "asz", 175, 158, 1, 1)
  /dmm_suite (/dmm_suite): load map impl(_maps/map_files/TgStation/tgst..., 1, 1, 1, null, null, 1)
  /dmm_suite (/dmm_suite): load map(_maps/map_files/TgStation/tgst..., 0, 0, 1, null, null, 1)
  Mapping (/datum/controller/subsystem/mapping): TryLoadZ("_maps/map_files/TgStation/tgst...", /list (/list), 1, null)
  Mapping (/datum/controller/subsystem/mapping): loadWorld()
  Mapping (/datum/controller/subsystem/mapping): Initialize(657647)
  Master (/datum/controller/master): Initialize(10, 0)
`

@Cyberboss

**Comment by Militaires** [comment]
p sure it's just missing a "roundstart = 1" arg or something
