### ISSUE TITLE
Trophies persistence runtime

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26819]
[19:24:11] Runtime in persistence.dm,117: Unknown value: 0
  proc name: LoadTrophies (/datum/controller/subsystem/persistence/proc/LoadTrophies)
  src: Persistence (/datum/controller/subsystem/persistence)
  call stack:
  Persistence (/datum/controller/subsystem/persistence): LoadTrophies()
  Persistence (/datum/controller/subsystem/persistence): Initialize(662517)
  Master (/datum/controller/master): Initialize(10, 0)

@KorPhaeron 

This is on my testing machine updated to latest.

**Comment by Profakos** [comment]
Darnit, I swear I have tested running it with a nonexistent trophy save file, didn't get a runtime for it. :(
