### ISSUE TITLE
Shuttle lights not working?

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#26812]
![](http://i.imgur.com/eLyRbYn.png)

This is at 1/3 toggle darkness, it is actually pitch black.

I'm not sure what happened, but the shuttle's lighting failed to work after it departed from the station (it was fine before that). The lights did not come back on when it arrived at centcom, either. Light tubes and computers SHOULD have been emitting light.

Mass kudzu on the shuttle. It was metastation.
Server revision compiled on: 2017-05-02
784b9c3626304a8aac6f3bad86b43b1576998b7c

**Comment by ninjanomnom** [comment]
I can't reproduce this and it seems like an edge case anyway. Seeing as the dock code got rewritten this should be closed and if the problem pops up again a fresh issue can be made.

**Comment by ShizCalev** [comment]
See above
