### ISSUE TITLE
Securitrons are unaffected by fluorosulfuric acid foam grenades.

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#26827]
[Note]: # 85b1a44b2f918c17b614c08138e00cacabf43c31 

So I tossed a chem grenade into the armoury. It had 50suf Facid and 50 Fluorosurfactant in one beaker and 50u water in the other. After surveying the damage, all the equipment had completely melted, but Seargent at Armsky was still in pristine condition, now guardian of a bunch of melted grey goo.

**Comment by Repukan** [comment]
The law is unbreakable

**Comment by WJohn** [comment]
Bots are simple animals, most simple animals are totally unaffected by chems or chemsmoke. Thus, not a bug, but just absence of depth and mechanics.
