### ISSUE TITLE
Artificers are immune to ash storms

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#26821]
![image](https://cloud.githubusercontent.com/assets/6778786/25634522/f668ba12-2f48-11e7-8bc3-d17cc2724e5f.png)

Artificers are immune to ash storms but im unsure if thats intentional or not because harvesters sure fucking werent.

Apparently engiborgs can heal through ash storms by constantly repairing themselves... seems kinda stupid

**Comment by ChangelingRain** [comment]
Was the artificer healing itself?

**Comment by Kromgar** [comment]
@ChangelingRain they can do that?


God damn it self healing through a fucking ash storm is stupid. The damage done to borgs and artificers is way less because it only targets one "body" when for humans it targets the heads, both arms, both legs and the torso. Maybe damage should be quintupled

**Comment by ChangelingRain** [comment]
The damage is the same for both humans and simple animals; 4 per weather tick. Humans just spread it across all their bodyparts.

**Comment by Kromgar** [comment]
@ChangelingRain still pretty stupid you  can outrepair a storm of lava ash
