### ISSUE TITLE
Default_unfasten_wrench and power issues

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#26824]
Most unanchored machinery keeps working when unanchored, and keeps working even when re-wrenched in rooms in unpowered rooms. Some of them, like smartfridges, update their powered status when rewrenched however.

Related issue is that you can break into cargo by simply unwrenching the Ore Redemption Machine, or into chemistry by unwrenching the smartfridge, but that is probably intentional.

**Comment by WJohn** [comment]
Expands upon #26810, closing that one.

**Comment by Profakos** [comment]
No, this is different issue I have found while testing that one, but right, I'll make a separate issue for default_pry_open.

**Comment by Marflowerose** [comment]
Probably related to vending machines never powering up when wrenching them to a powered room from unpowered room.

**Comment by Profakos** [comment]
Exact same reason, they are never called to perform power_change()
I have checked, smartfridges update their power because that proc is explicitly called if wrenching them was successful. Power_change() should probably be called inside Default_unfasten_wrench, and probably force depower them, so they are not powered while unanchored.
