### ISSUE TITLE
Default_pry_open issues

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#26833]
Several machines use default_pry_open, which calls open_machine(), which while drops the contents of the machine, also makes them non-dense. This makes sense for sleepers, cryochambers and cyborg rechargers, but has problems in various other devices. 

- Gibber
- Holopad: holopads are already nondense so it isn't much of an issue but still
- Hydroponic trays
- Monkeyrecycler
- Ore Redemption
- Recycler
- Processor
- Seed Extractor
- Smartfridges
- Suit Storage Unit: if opened via the interface instead of a crowbar, it won't become nondense, but crowbar prying makes it so.

**Comment by Profakos** [comment]
I have been formulating a solution: adding a secondary flag called TOGGLE_DENSITY_ON_OPEN or a var to whatever actually needs it and add a check for it in open_machine and close_machine. Is this a good approach?

**Comment by RemieRichards** [comment]
A flag is not really correct for this, an argument on the ```default_X()``` procs is better.

**Comment by Profakos** [comment]
That one is a much neater solution.

**Comment by timothymtorres** [comment]
This still hasn't been fixed.
