### ISSUE TITLE
clicking cancel on advanced proccall prompts will proccall it with whatever you entered so far instead of cancelling

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#26831]
:salt:

**Comment by PKPenguin321** [comment]
it cancels adding args

**Comment by lzimann** [comment]
You will have to be more specific. If it's the named argument, canceling means it will just be a positional argument and is intended. If it's the variable type, then it's a bug.

**Comment by kevinz000** [comment]
@lzimann clicking cancel on any prompt at all will still make the proccall go through
