### ISSUE TITLE
Sleepers are broken

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#26837]
Server revision: Server revision compiled on: 2017-05-02

Issue: Sleeper buttons do not register either Human or silicon input. Deconstructing and re-constructing does not fix the issue. Buttons will be clickable but doing so does not do anything.

Why is this an issue: Do I even need to explain why?

**Comment by Repukan** [comment]
>Not just using cryo for deep wounds and stubbed toes


Stupid rabbit

**Comment by bgobandit** [comment]
@coiax

**Comment by bgobandit** [comment]
never mind, it's an easy ass fix
