### ISSUE TITLE
Floral somatarays don't appear to be working

### ISSUE THREAD

**Issue by Shapsy** [tgstation/tgstation#26866]
Reply PM from-Player: THey should work as you shoot plant(?|F) they either mutate plant or increase its yield, neither oth these things seem to(?|F) be happening 

According to a few podpeople, the somatarays (multiple in this case) weren't hitting the plants, but seem to hit the other pod people just fine. No admin intervention involved, these are just stock and untouched. Unfortunately I don't know enough about how they should function to offer any more information about it than what they had to offer.

**Comment by XDTM** [comment]
Somatorays work, they're just really shit and the mutations barely do anything. Also, if they were using yield mode, it's only a low chance of it working, so it might end up looking like it was doing nothing.
