### ISSUE TITLE
Changeling cult golems can infinitely jaunt

### ISSUE THREAD

**Issue by Darkgenerallord** [tgstation/tgstation#26865]
If a changeling who has a runed metal golem's DNA saved transforms into them, they get all the racial abilities, such as jaunt. If you transform back into a human, you lose these powers. However, if you transform back, all cooldowns are immediately gone. You can also cycle the transformations mid-jaunt, allowing you to basically be jaunting forever.

**Comment by Armhulen** [comment]
OH NO.

**Comment by Robustin** [comment]
Doesn't transform give genetic damage that gives a long lockout to further transforms?

**Comment by Armhulen** [comment]
We're removing genetic damage soon anyways, so...

**Comment by Darkgenerallord** [comment]
Transforming doesn't, transformation sting does.

**Comment by FantasticFwoosh** [comment]
Hahahaha, i've already theorycrafted this and i've got my validation.

Maybe we should put a cap on lings being able to assume golem abilities and keep it cosmetic only, as not to void or alienate the original carbon mob's abilities or functions.
