### ISSUE TITLE
Runtime if you remove every language from someone and try to talk

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#26883]
[05:30:05] Runtime in say.dm, line 65: Cannot execute null.display icon().
proc name: compose message (/atom/movable/proc/compose_message)
usr: Melanie Lara (shadowlight213) (/mob/living/carbon/human)
usr.loc: The floor (163,84,2) (/turf/open/floor/plasteel/green/corner)
src: Melanie Lara (/mob/living/carbon/human)
src.loc: the floor (163,84,2) (/turf/open/floor/plasteel/green/corner)
call stack:
Melanie Lara (/mob/living/carbon/human): compose message(Melanie Lara (/mob/living/carbon/human), null, "Huh", null, /list (/list), null)
Melanie Lara (/mob/living/carbon/human): send speech("Huh", 7, Melanie Lara (/mob/living/carbon/human), "default", /list (/list), null, null)
Melanie Lara (/mob/living/carbon/human): say("Huh", null, /list (/list), 1, null)
Melanie Lara (/mob/living/carbon/human): Say("huh")

@coiax

**Comment by duncathan** [comment]
the effect in-game is printing a completely empty line which I think is funny

**Comment by KorPhaeron** [comment]
Players should never be left with no languages though

**Comment by coiax** [comment]
It's still a big though, people with no language talking should just make "strange noises", rather than runtime.

**Comment by Armhulen** [comment]
When you have no languages you should learn chimpanzee

**Comment by Armhulen** [comment]
When you have no languages you should learn chimpanzee

**Comment by Shadowlight213** [comment]
No var editing was involved. Just the normal admin language menu

**Comment by Shadowlight213** [comment]
This was fixed
