### ISSUE TITLE
Player somehow got cloned roundstart

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#26884]
12:03:11: (Ada Tamzi): I managed to clone myself somehow at roundstart

![](https://puu.sh/vF41x/aae8e4a25b.jpg)

@Cyberboss 

Ticket: (Ada Tamzi): Alright I figured it out. If you leave the game right as you spawn and rejoin. It makes you rejoin the game as a new character.

**Comment by octareenroon91** [comment]
>Captain's spare Captain

**Comment by bgobandit** [comment]
please take this redheaded catgirl fetish out of my game

**Comment by Shadowlight213** [comment]
I got a ghost into the spare body and named it Ada Tamzi's clone. It turned out well.
