### ISSUE TITLE
Omnitongue does not work

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#26889]
Librarian was talking and the language was acting like they had it off
@coiax

**Comment by coiax** [comment]
I'm going to need more context here

**Comment by DaxDupont** [comment]
Did they get cloned? I just lost the ability to talk in other languages after getting cloned.

**Comment by coiax** [comment]
That's a known bug.

**Comment by optimumtact** [comment]
Fix ur shit coiax

**Comment by Bawhoppen** [comment]
I PMed you coiax all about it before

**Comment by Shadowlight213** [comment]
@coiax @DaxDupont No. they weren't cloned.
They could speak each language individually, but omnitongue (which is supposed to make it so everyone can understand you) was not working.

**Comment by coiax** [comment]
Omnitongue does not make everyone understand you, it removes restrictions on speaking different languages that you know.

A drone with omnitongue would be able to speak common, a Ratvar AI with omnitongue would be able to speak common, and a human with omnitongue would be able to speak EAL if they knew it, even though normally they wouldn't.

**Comment by Shadowlight213** [comment]
Oh. Ok. Then this isn't a bug then.
