### ISSUE TITLE
Weird interaction with spawning people and aghost

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26902]
1) Accidentally took control of Lisa the corgi.
2) Aghosted out.
3) Offered control to ghosts.
4) Someone else took control.
5) My ghost goes to thunderdome, uses the Ctrl-Shift spawn as human shortcut.
6) They get yanked out of Lisa's body, and into the new human body.

**Comment by KorPhaeron** [comment]
I'm almost positive this is a dupe

**Comment by lzimann** [comment]
Dupe of #16639
