### ISSUE TITLE
CE's hard-suit isn't protecting you from fire anymore 

### ISSUE THREAD

**Issue by Cuboos** [tgstation/tgstation#26905]
So i was playing a round as the CE earlier and i built a flamethrower to fight off the wizard. I got quite a few blasts on him and got caught in my own fire as well (as to be expected). However i noticed my health was quickly draining when the wizard was hardly doing any damage to me. The only other conclusion was that it was the fire. 

I had the helmet turned on, i was wearing a gas mask, my internals were on and i was even wearing the mag boots (if that counts). The fire should not have effected me. I couldn't find any PRs saying they removed the fireproof feature from the CE's hard suit so i'm assuming it's a bug.

**Comment by Cuboos** [comment]
UPDATE: i just lit myself on fire a few more times with the CE's gear on, and it sometimes works and sometimes doesn't. I was wearing exactly what stated in the original post.

**Comment by FantasticFwoosh** [comment]
`armor = list(melee = 40, bullet = 5, laser = 10, energy = 5, bomb = 50, bio = 100, rad = 90, fire = 100, acid = 90)
	heat_protection = CHEST|GROIN|LEGS|FEET|ARMS|HANDS
max_heat_protection_temperature = FIRE_IMMUNITY_SUIT_MAX_TEMP_PROTECT`

The above code from the CE's suit entry should define that you are fireproof because the armor covers all of your slots, my code professional thought is that wearing another piece of clothing that is not fireproof is allowing you to take damage. For example the magboots, but thats only a theory.

> Set yourself on fire wearing nothing but the hardsuit

**Comment by Cuboos** [comment]
Okay, decided to run some tests on my own server 

CE suit only (no other clothing at all): did not burn when splashed with welding fuel and lit on fire

CE suit with CE uniform only: Did not burn when splashed with welding fuel and lit on fire 

CE suit with round start gear (belt, black gloves, uniform, ID and PDA) did not burn when splashed with welding fuel and lit on fire 

CE suit with round start gear + magboots: did not burn when splashed with welding fuel and lit on fire 

CE Suit with round start gear + magboots + insulated gloves: did not burn when splashed with welding fuel and lit on fire 

CE Suit and uniform with internals (using breath mask) during plasma fire: did not burn in plasma fire 

CE Suit and uniform with internals (using gas mask) during plasma fire: did not burn in a plasma fire. 

CE Suit and uniform with internals (gas mask) using a flame thrower: didn't burn from flame thrower

CE Suit and uniform with internals (breath mask) using a flame thrower: didn't burn from flame thrower 

CE Suit and uniform without internals: took burn damage to head and continued to take burn damage even out the fire and toxin area (ended up getting killed accidentally by a fire door before i could put the fire out, but that's irrelevant) 

So far i only found one area of failure, which wasn't a variable when i was fighting the wizard. I did get glanced by a fireball that only knocked me down and did minor damage, however it was after that, that i started taking continued damage, none of which came from the wizard (he was preoccupied by someone with a laser gun at the time) 

Considering all the random bugs that have been popping up around Sybil and Basil lately, it might just be attributed to that.

**Comment by XDTM** [comment]
Could you have inhaled plasma before turning internals on?

**Comment by kevinz000** [comment]
this probably isn't a bug, internals is required for it, otherwise you're just breathing burning hot gas.

**Comment by kingofkosmos** [comment]
Couldn't reproduce, the CE's hardsuit seems to be fireproof.

Tested with just the hardsuit on, splashed self with welding fuel and spawned a hotspot to lit myself on fire. Fireproof with or without internals. Got fire damage only if I took the helmet off.
