### ISSUE TITLE
It is not possible to eject more than 1 sheet of plasteel from the ORM

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26906]
Server revision compiled on: 2017-05-04
The following pull requests are currently test merged:
#23201: '[wip]DATUM VERBS AND TOP MENUS!' by MrStonedOne 

Based off master commit:
6f429ba9c99ede22efb9d049a5ab450075cf000d 

1) Load metal and plasma ore.
2) Attempt to vend more than 1 sheet of plasteel.
3) Only one sheet comes out, only one sheet of materials are used.

**Comment by Bawhoppen** [comment]
another reason why the ORM is the inferior machine to the smelter

**Comment by Profakos** [comment]
Swear it worked in testing. Will look it into asap.
