### ISSUE TITLE
[Deltastation] The chemistry lab lacks a screwdriver

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#26909]
REV: 6f429ba9c99ede22efb9d049a5ab450075cf000d 

Unlike all the other chemistry labs on other maps, Deltastation's chem lab is missing a screwdriver, making it a hassle when you need to make grenades, since to finish them you have to go find a screwdriver from somewhere else.

**Comment by Repukan** [comment]
God I'm so sorry, are you ok?

Point in this toolbox where the assistant touched you.

**Comment by xxalpha** [comment]
Maps aren't code and don't follow any strict rules, they're more like guidelines subject to a mapper's subjective vew. This isn't a bug or an issue worth tracking. Go to the nearest tool-vend and get a free screwdriver.

**Comment by FantasticFwoosh** [comment]
Subjectively the mapper might not want you to make grenades, backing up @xxalpha 's point, you might want to speak to the mapper or deal with the situation IC  by simply acquiring one.

**Comment by BeeSting12** [comment]
I'll place one anyway since I'm already fixing an issue on the map.
