### ISSUE TITLE
Localhost can't readmin

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#26903]
Nothing happens when you click the button

**Comment by Penguaro** [comment]
It may or may not matter, is the specific ckey localhost listed in the admin.txt? I know to get host privileges it isn't necessary per se.

**Comment by SpaceManiac** [comment]
Cannot reproduce. Connect via full address, not an admin. Connect on localhost, am admin, deadmin, readmin fine.

**Comment by Cyberboss** [comment]
are you logged out of the pager and appearing as a guest key?

**Comment by SpaceManiac** [comment]
ADMIN LOG: Guest-1846455049 re-adminned themselves.

Also note that DD automatically starts the pager now so you have to willfully log out and back in as guest to even get to this situation.
