### ISSUE TITLE
[Deltastation] The chemistry lab's smart fridge is blocked by a garbage chute

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#26904]
This makes the smartfridge inaccessable unless you stand in front of the chemistry desk and open the window.  It should be moved away, so that you don't have to disrupt the line of people asking the chemist for mutagen/space cleaner/lube/chloral hydrate just to get a burn or brute patch.

**Comment by BeeSting12** [comment]
I'll take care of this one too
