### ISSUE TITLE
Players cannot *spin verb.

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#26912]
You will recieve a notification it is playing but the animation will not play, i am uncertain whether any effects like shaking people off your back will still apply and haven't tested that out.

Initially i noticed this during a sole testmerge of #23201 which is still active, not sure if related. consistent across rounds with it present.

> To recreate just go into sybil and while in a carbon mob type *spin in chatbar or whatever you wierd non hotkey people do.

**Comment by Armhulen** [comment]
Side note: also happens with borgs

**Comment by swindly** [comment]
Humans are thrown off of cyborgs.
