### ISSUE TITLE
Equipping then unequipping mesons as an engineering cyborg gives you a weird vision bug

### ISSUE THREAD

**Issue by Limski** [tgstation/tgstation#26918]
basically you get meson vision but you cant see past walls and stuff

**Comment by Tacolizard** [comment]
pics or gtfo

**Comment by Limski** [comment]
ok.
before equipping mesons:
http://i.imgur.com/qAIybCk.png

equipped mesons:
http://i.imgur.com/4pdtN7u.png

after unequipping mesons:
http://i.imgur.com/NzpUOsD.png

**Comment by Tacolizard** [comment]
really activates your almonds

**Comment by cerid** [comment]
Cannot reproduce; insufficient information.

**Comment by Limski** [comment]
@cerid 
Step 1. Be default cyborg module
Step 2. Turn into Engineering Cyborg
Step 3. open your module storage, click the mesons icon
Step 4. Switch to the mesons in your hands and put them back into your module storage
This will result in you having night vision or something very close to it.
I even re-downloaded the latest server version and reproduced it as we speak

Thanks for reading my Minecraft tutorial please like and subscribe.

**Comment by ShizCalev** [comment]
Seems to be affecting engineering scanner goggles as well according to #29589

**Comment by vuonojenmustaturska** [comment]
Cannot reproduce, the underlying code and various visual layers and planes have seen a fair bit of churn since this bug was around so it's possible it was unintentionally fixed.
