### ISSUE TITLE
Miner's Salve sleeps you without warning after you drink coffee to prevent it

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#26932]
As the title says, there's no vision cue that you're going to sleep with miner's salve injected or sprayed if you drink coffee to avoid the initial sleep

**Comment by Expletive** [comment]
Miner's salve doesn't sleep you, it stuns. Are you sure that you aren't thinking of Sulfonal?

**Comment by YakumoChen** [comment]
Ah, hell, I misread a PR + thought it was merged when it wasn't. I think it was Sulf or something though.
