### ISSUE TITLE
RARE BYOND MEME. Managed global initialization procs occasionally fail to generate on linux

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#26954]
```
Fri May  5 20:57:21 2017
World opened on network port 25001.
Welcome BYOND! (5.0 Public Version 511.1380)
map_config not found: data/next_map.json
585 global variables
[20:57:30] Runtime in globals.dm,57: undefined proc or verb /datum/controller/global_vars/InitGlobaltdome1().
 
  proc name: Initialize (/datum/controller/global_vars/Initialize)
  src: Global Variables (/datum/controller/global_vars)
  call stack:
  Global Variables (/datum/controller/global_vars): Initialize()
  Global Variables (/datum/controller/global_vars): New()
  Master (/datum/controller/master): New()
  world: ()
runtime error:
[20:57:30]undefined proc or verb /datum/controller/global_vars/InitGlobaltdome1().
 
[20:57:30]proc name: Initialize (/datum/controller/global_vars/Initialize)
[20:57:30]  source file: globals.dm,57
[20:57:30]  usr: null
[20:57:30]  src: Global Variables (/datum/controller/global_vars)
[20:57:30]  call stack:
[20:57:30]Global Variables (/datum/controller/global_vars): Initialize()
[20:57:30]Global Variables (/datum/controller/global_vars): New()
[20:57:30]Master (/datum/controller/master): New()
[20:57:30]world: ()
```

Happens for all global vars if the bug is triggered

Typing the fully expanded definitions for the failing globals in place of the `GLOBAL_VAR_*` define will fix it. e.g.
```
/datum/controller/global_vars/var/global/list/tdome1
/datum/controller/global_vars/proc/InitGlobaltdome1()
    tdome1 = list()
    gvars_datum_init_order += "tdome1"
```

Related 
We were warned: https://github.com/tgstation/tgstation/pull/25325#issuecomment-292818977
Trigger: #26874 
Fix: #26950 
Different fix: #26953

According to @lzimann RETYPING THE LINE also stops the runtimes. I guarantee you it will happen again. We need to gather data each time it does to determine the cause.

**Comment by lzimann** [comment]
I want to add that this also happened while I was porting goonchat
The entire code was at `goon/code/modules/browserOutput.dm` and the build would runtime in a linux VM(this was tested in my vm and also the linux server we have). 
Moving the code and assets to `code/modules/goonchat` made the runtimes stop completly.

**Comment by Cyberboss** [comment]
Confirmed to be a compiler error

**Comment by MrStonedOne** [comment]
no, confirmed to be a server error, the same dmb/rsc worked fine on windows but not on linux, that tells me its dreamdaemon not dreammaker.

**Comment by Cyberboss** [comment]
Placing the following code before the call to global_vars/Initialize fixes it

```
for(var/I in typesof(/datum/controller/global_vars/proc))
    log_world("[I]")
```

**Comment by Cyberboss** [comment]
@Core0verload because you mentioned this a while back

**Comment by Cyberboss** [comment]
Related probably #14893

**Comment by optimumtact** [comment]
http://www.byond.com/forum/?post=1879691

**Comment by Core0verload** [comment]
I confirm, had this exact bug on Animus (/tg/station codebase compiled and ran on Linux), with same `undefined proc or verb` runtime. Not exactly the same proc, but same pattern. Ended up lobotomizing the globals controller as a hot fix.

**Comment by lzimann** [comment]
This is happening again since commit 15892ac. Which is a map edit... one commit before that works fine.

**Comment by Cyberboss** [comment]
What the fuck

**Comment by Cyberboss** [comment]
Literally what the actual fuck

**Comment by Cyberboss** [comment]
Runtime loading should prevent those files from even being LOOKED AT before the bug happens!

**Comment by Cyberboss** [comment]
@coiax pls confirm

**Comment by coiax** [comment]
That's what the bisect told me. Maybe I should run it again.

**Comment by coiax** [comment]
Bisect ran again tells me it was [1fe0308ffb8e4534102c23f6aaa1d172818d88b4] Fixes the recycler gibbing brainmobs

**Comment by bgobandit** [comment]
THIS is the testing bug I was mentioning earlier

**Comment by Cyberboss** [comment]
The bug is in the linux server. Are you sure about that?

**Comment by optimumtact** [comment]
It has been known to randomly occur on windows

**Comment by optimumtact** [comment]
anyway I've basically given up with running on linux, lummox seems determined to leave it unsupported

**Comment by bear1ake** [comment]
How about place this code https://github.com/tgstation/tgstation/blob/master/code/controllers/globals.dm#L1 after this https://github.com/tgstation/tgstation/blob/master/code/__DATASTRUCTURES/globals.dm#L38?

**Comment by optimumtact** [comment]
it is?

**Comment by PsiOmegaDelta** [comment]
I changed how the global init procs are called in https://github.com/Baystation12/Baystation12/pull/17874 and while it's only been a few days and not too many PRs our Travis builds haven't had issues since.

The main difference is that all procs in `/datum/controller/global_vars` are called directly in the loop that already existed, rather than the seemingly random CLEANBOT_RETURNS bits and the string-based `"InitGlobal[I]"` calls.

Wouldn't be the first time BYOND has had trouble using strings to match against something.

**Comment by Cyberboss** [comment]
I'm gonna close this until it's heard of again
