### ISSUE TITLE
People with wings can land on chasm turfs without falling down

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/tgstation#26955]
1. Get wings somehow.
2. Start flying and move on top of a chasm turf.
3. Stop flying.
4. Notice that you are now standing on top of a chasm turf without falling down.

**Comment by coiax** [comment]
I assume if you then move while not flying, you fall into the chasm and die?

**Comment by Tokiko1** [comment]
That's correct. I suppose landing could call turf/entered on the tile below you?

**Comment by ChangelingRain** [comment]
Nah, it'd probably be better to make chasms just process constantly. There shouldn't be enough of them that doing so has a noticeable cost.
