### ISSUE TITLE
Not always getting killed by bombs

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#26957]
I was defusing a bomb and I hit the wrong wire, second try. I was right next to the bomb when it exploded and I waited a second and said RIP, thinking I was in deadchat. Imagine my surprise when I am alive and now taking low pressure and oxygen damage. I think I was either on the tile the bomb exploded on or right next to it. Anyways I got back to medical, put on some brute patches, and then cucked an esword traitor with a pie. Fun stuff. The only damage I took was from the pressure/lowtemps btw.

**Comment by ChangelingRain** [comment]
@Cyberboss

**Comment by Steelpoint** [comment]
This happened to me. I was disarming a syndi bomb as an Assistant, with no bomb protection. The bomb detonated yet despite the fact I was sitting right next to the bomb I took no damage whatsoever at all. The Head of Personal who was standing a few tiles behind me got launched into crit.

**Comment by kriskog** [comment]
Havent seen this lately.
