### ISSUE TITLE
Icons getting stuck/broken

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#26968]
1) Clock Cult round

2) At some point my in-hands get stuck at Riot Shield + Baton

3) When I equip anything else, it just overlays over the shield+baton icons.

4) The "overlaid" inhands will properly update but the shield+baton icons are eternal.

**Comment by vcordie** [comment]
you can take the player out of the brig, but you can't take the brig out of the player.

**Comment by Jalleo** [comment]
Were any stun batons picked up after and then dropped via the same hand still leave the artifact of the old stun baton?

**Comment by WJohn** [comment]
![](http://i.imgur.com/cUTcu7C.png)

I have had this happen multiple times with multiple different objects, as have other people. It's rare and we don't know the cause of it.

**Comment by ShizCalev** [comment]
Has this happened at all lately? Haven't seen it in a while myself.
