### ISSUE TITLE
Your ghost teleports to the arrivals shuttle when you leave your body

### ISSUE THREAD

**Issue by Deputi** [tgstation/tgstation#26961]
When you press the ghost button, your ghost appears on the arrivals shuttle instead of on top of your body.

**Comment by Armhulen** [comment]
Extremely annoying.

**Comment by KorPhaeron** [comment]
@Cyberboss

**Comment by QualityVan** [comment]
Should've been fixed by #26908

**Comment by vcordie** [comment]
it wasn.t

**Comment by MrStonedOne** [comment]
#26908 isn't live on the server.

**Comment by ShizCalev** [comment]
Seems to be fixed now.
