### ISSUE TITLE
Mobs at roundstart spawning on lobby screen with languages runtime

### ISSUE THREAD

**Issue by Jordie0608** [tgstation/tgstation#26973]
When the round starts, anyone readied up isn't sent to the station and instead left on the lobby screen; late-joining does send you to the arrivals shuttle however. Tracked to https://github.com/tgstation/tgstation/commit/b633cd6ba287258df20e893ab685533de0b12c31
@Cyberboss 
This produces the runtime
>`[17:40:15]Cannot execute null.copy().
>[17:40:15]proc name: transfer to (/datum/mind/proc/transfer_to)
>[17:40:15]  source file: mind.dm,93
>[17:40:15]  usr: null
>[17:40:15]  src: /datum/mind (/datum/mind)
>[17:40:15]  call stack:
>[17:40:15]/datum/mind (/datum/mind): transfer to(Jack Moore (/mob/living/carbon/human), 0)
>[17:40:15]Jordie0608 (/mob/dead/new_player): create character(0)
>[17:40:15]Ticker (/datum/controller/subsystem/ticker): create characters()
>[17:40:15]Ticker (/datum/controller/subsystem/ticker): setup()
>[17:40:15]Ticker (/datum/controller/subsystem/ticker): fire()
>[17:40:15]Ticker (/datum/controller/subsystem/ticker): fire(0)
>[17:40:15]Ticker (/datum/controller/subsystem/ticker): ignite(0)
>[17:40:15]Master (/datum/controller/master): RunQueue()
>[17:40:15]Master (/datum/controller/master): Loop()
>[17:40:15]Master (/datum/controller/master): StartProcessing(0)`

**Comment by AnturK** [comment]
Coiax missed one direct access to language holder. I'll put up a fix
