### ISSUE TITLE
When the lobby timer reaches zero it does not reset itself but instead sets itself to DELAYED. (When there are no ready players)

### ISSUE THREAD

**Issue by straycat0000** [tgstation/tgstation#26977]
When the lobby timer reaches zero it does not reset itself but instead sets itself to DELAYED. (When there are no ready players)

Happens on the May 3rd TG build.

**Comment by MrStonedOne** [comment]
@Cyberboss

**Comment by straycat0000** [comment]
Is that a problem in the code or a wrong config setting?

**Comment by Cyberboss** [comment]
It's a code problem. The issue is the statpanel as well as the ticker interpret negative time_to_start values as the round being delayed. I suppose lag is causing the check to run before ticker can change state

**Comment by straycat0000** [comment]
Was this fixed in the meantime so I can take the fix from the git and use that?
