### ISSUE TITLE
Clothing damage messages are inconsistent

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26979]
1) Be swarmer.
2) Start breaking down a locker with clothes in.

>Your the breath mask starts to fall apart!
>Your the breath mask starts to fall apart!
>Your the breath mask starts to fall apart!

**Comment by BeeSting12** [comment]
This additionally happens when attacking someone. Their engineer jumpsuit starts falling apart and you get the message too, just like this one.
