### ISSUE TITLE
You can move while buckled to some objects

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation#26972]
Pull an unanchored, bucklable object, buckle yourself to it, click where you want to move 

voila, player made disgusting stacks of human flesh crawling about the station

**Comment by RandomMarine** [comment]
Well, if you tie up someone to an insecure object, you can expect they could still awkwardly shuffle around. Especially something designed to move like a desk chair. Feature?

**Comment by Cyberboss** [comment]
Yeah this is a feature

**Comment by Jalleo** [comment]
Examples are required @optimumtact

**Comment by MrPerson** [comment]
If we want people to move around in desk chairs and shit that's fine, but not this way.

**Comment by optimumtact** [comment]
@Jalleo petbed

**Comment by Tacolizard** [comment]
'unintentional feature' tag when
