### ISSUE TITLE
Patients can only have their blood refilled from the same bloodtype

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#26983]
I cannot count for how recently this happened, but O+ is a universal (perhaps maybe not to lizards) bloodtype in the game that USED to refill anybody up, however when injected into a patient using a UV drip it will poison prior compatible recipients of the blood with toxic incorrect kinds of blood causing large amounts potentially fatal toxin damage. The only way to safely inject blood into yourself now as a result of this bug is to find a matching blood type.

> Its very common to catching out old players pre-bug who assume O+ still refills generally all types of blood, as well as makes the blood tomato plant (which gives O+ blood) redundantly specific.

Blood substitutes (saline glucose) remain unchanged and working in its place.

**Comment by Cruix** [comment]
O- is universal, O+ is toxic to anyone with a - blood type

**Comment by FantasticFwoosh** [comment]
Oh wait no, i haven't got this wrong have i? Sorry everyone if thats the case.

**Comment by DaxDupont** [comment]
Poor poor patient.

**Comment by Penguaro** [comment]
You get an A+ for effort, but O- for knowledge. (-;
