### ISSUE TITLE
Monkeys can still attack & tackle whilst restrained

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#26996]
It is impossible to restrain a monkey properly in order for some temporary respite from their attacks, for example with something simple like cable coil cuffs they will still repeatedly bite & tackle you (**which both require being unrestrained when being a ckey monkey as a thesis & basis of this bug**), the only way to get them to stop once they are angered is to literally knock them out or to kill them.

Mentioned in @Iatots post https://github.com/tgstation/tgstation/issues/24629#issuecomment-283802670

**Comment by jughu** [comment]
Sounds a feature to me
Sure you cuffed his hands but what does stop him from tackling and biting and moving

**Comment by jughu** [comment]
Also if you chairbuckle them with cuffs on they stop

**Comment by Penguaro** [comment]
Isn't that what a syringe gun of chloral-hydrate is for? Bro do you even Animal Test?

**Comment by kriskog** [comment]
Cant anymore
