### ISSUE TITLE
The auxillary base can land partially outside of the map's borders.

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#26997]
Server Revision: bee517e1ac749eea93d84a5b94ad5884a7186b2e

On this one, the base landed and the right side wall was outside the boundaries of the map, and so was one of the turrets.
![basebug](https://cloud.githubusercontent.com/assets/9963278/25776381/6bb67964-3271-11e7-8f59-721dec9ccab6.PNG)

**Comment by PKPenguin321** [comment]
I think this is a dupe

**Comment by GunHog** [comment]
It is, I have sadly forgotten about this!

**Comment by Jordie0608** [comment]
#25022
