### ISSUE TITLE
Implants don't deconvert gang

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/tgstation#27003]
Gang members can be mindshield implanted and remain gang

**Comment by PKPenguin321** [comment]
needs reproduction steps

**Comment by LanCartwright** [comment]
Sec officer was gang implanted? (unknown, round was fast paced until bug occured), but appeared as implanted on HUD. Immediately killed me.

Sheryl Sherman, gang around was 00:10~ hours GMT.

**Comment by PKPenguin321** [comment]
might just be a bug with huds

**Comment by LanCartwright** [comment]
never happened with rev, I think it's an issue with gang then.

**Comment by DaxDupont** [comment]
I had someone who was implanted that was listed as gang on round end and was showing as implanted at that time.
