### ISSUE TITLE
Gang members can have implanted status on their SecHUD

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/tgstation#27005]

**Comment by PKPenguin321** [comment]
dupe of https://github.com/tgstation/tgstation/issues/27003 ?

**Comment by LanCartwright** [comment]
Possibly. Atlanta-ned asked me if i was broken implanted which leads me to suspect there might be a bug all together (if I wasn't showing up as implanted).

**Comment by DaxDupont** [comment]
I had someone who was implanted that was listed as gang on round end and was showing as implanted at that time.
