### ISSUE TITLE
Lighting persistence issue leaving residue everywhere

### ISSUE THREAD

**Issue by obscolene** [tgstation/tgstation#27016]
I started noticing random blue lights all over the station, and thought it was out of the ordinary. 

https://gyazo.com/85c4462e81b225b9c3b5c4db83396231

Then I realized that lights are leaving some kind of weird residue, after I had shot someone with disablers in the brig and it having left piss stains everywhere. 

https://gyazo.com/d312b4fe52818bb2193b6a2c045c7760

As well as emitter beams leaving a blue trail, getting more powerful as the round goes on.

https://gyazo.com/fee9985e1c79165b799628af2e8b258e

I have no idea what causes this, but it seems to only be coming from projectiles maybe. If this is the case, then I'm not sure what the faint blue spots in image #1 would be coming from. 

How to recreate: 
1. Shoot disabler repeatedly
2. Watch as piss puddles form around you out of thin air

**Comment by MrStonedOne** [comment]
caused by test merge, fixed
