### ISSUE TITLE
All the prefs buttons are broke

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#27017]
Whoever it was who ninja moved all the preferences tab's verbs to the file tabs broke them, 

Aside from them no longer existing in the actual preferences tab, they also don't work when you try to use them giving the non-recognized command error

**Comment by Bawhoppen** [comment]
Stop sound, Ghostwhispers, etc.

**Comment by Bawhoppen** [comment]
Seems to only happen under random circumstances, fixes when restarting client

**Comment by PKPenguin321** [comment]
You can fix faster by going File -> Reconnect

**Comment by Bawhoppen** [comment]
has happened to me again
