### ISSUE TITLE
A cultist being turned to a cult master creates a visible "HAS REMEMBERED THEIR OLD FAITH" message

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#27021]
@Robustin 

>Braxton Cherry looks like he just reverted to their old faith!

**Comment by YakumoChen** [comment]
It actually deconverts you then reconverts you as a cultist master.

**Comment by coiax** [comment]
Someone on basil got turned into a cult master in front of non-cultists, who noticed the giant message and called it out, thus outing the cult.

150 hours of testing.

**Comment by ChangelingRain** [comment]
This would be my fault except I specifically made it silent????
