### ISSUE TITLE
Cult shackles when removed produce two messages

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#27039]
> Gene Ball tries to remove Rebecca Lee's cult shackles.
> Rebecca Lee's shackles shatter in a discharge of dark magic!
> Rebecca Lee's shackles shatter in a discharge of dark magic!

Was a ghost watching Gene remove Rebecca's shackles.

**Comment by lzimann** [comment]
Was fixed/not happening anymore according to @XDTM
