### ISSUE TITLE
Semi-Duplication Bug

### ISSUE THREAD

**Issue by Work4Bots** [tgstation/tgstation#27033]
I picked up the X-01 Multiphase gun at the same time as someone else did and immediately pressed E to equip it, putting it in my bag. This put the X-01's sprite in my backpack but not the actual object. Whenever the other person would take out the X-01 it would appear in my hand and would actively update it's charge. 
It's place in the bag seemed to be linked to whereever it was in the other person's bag.

**Comment by AnturK** [comment]
Dupe of #25814
