### ISSUE TITLE
Cloning a plasmaman turns it into a plasma-breathing human.

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#27046]
Admin turned me into a plasmaman, I died and was cloned, after cloning I notice that I continuosly get toxins and have no oxygen.
After some time, the doctors stabilised me and I could do perfectly fine except i would fall over every five seconds or so unconscious.
After getting a plasma tank attached to my internals, the toxins sign disappeared, and I didn't get KOd. Although, the no oxygen warning remained.

**Comment by QualityVan** [comment]
Were you scanned before or after you got turned into a plasmaperson?

**Comment by evsey9** [comment]
after turned to plasmaman
also, yes, i had my species to plasmaman, and when cloned i appeared as a plasma-breathing human

**Comment by evsey9** [comment]
note: i did NOT light up on fire after being cloned

**Comment by QualityVan** [comment]
Alright. Were you rattling when you talked or were you talking normally?

**Comment by evsey9** [comment]
I was talking normally, I think?
Also uhm, might be irrelevant, but still - before being turning me to plasmaman, admin turned me into a lizardperson with digitrade feet, and THEN to plasmaman

**Comment by Penguaro** [comment]
> before being turning me to plasmaman, admin turned me into a lizardperson with digitrade feet, and THEN to plasmaman
What on earth was that round like...

**Comment by evsey9** [comment]
i prayed



also extended i think

**Comment by PKPenguin321** [comment]
Needs reproduction, sounds like this was just fuckyness from admin shenanigans

**Comment by evsey9** [comment]
Yeah probably
