### ISSUE TITLE
An self destructing operative does not cause the grenades on their belt to explode

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#27049]
I was an op with EMP grenades in my backpack, and explosive grenades on my belt.

I was being stripped, someone removed my backpack, so I detonated, which causes the EMP grenades to all explode, but the high amounts of explosives on my person did not do anything.

**Comment by Bawhoppen** [comment]
they used to

**Comment by PKPenguin321** [comment]
I think things detonating in your bag just doesn't work at all at the moment

**Comment by timothymtorres** [comment]
Pretty sure this was fixed with

https://github.com/tgstation/tgstation/blob/dbd0193928f36f007d3249b0b143661dce1674d0/code/controllers/subsystem/explosions.dm#L352-L368

Needs to be tested to confirm.
