### ISSUE TITLE
"X opened a canister that contains the following:" admin messages appear even for empty canisters

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#27062]
By "empty" I mean "are not releasing any discernible gas into the atmosphere."

Why is this an issue: Leads to bwoinks that are not necessary, clogs the logs

How to reproduce: I reproduced it by var-editing the gas_mixture contents of a freon canister to 1 (effectively 0, shows up as 0 on the canister) then opening it.

**Comment by BeeSting12** [comment]
so you bwoink people whenever they open a canister?

**Comment by duncathan** [comment]
@bgobandit
What threshold of moles would you prefer? This is an easy change.

**Comment by Iamgoofball** [comment]
@duncathan just default this to the moles visible threshold

**Comment by bgobandit** [comment]
@BeeSting12 The admin message reads "___ opened a canister that contains: Freon" (or whatever), it is not a stretch to assume the person involved released freon, considering it literally says so. as an admin I hate it because you have to figure out whether the canister was actually empty or whether they're lying, and players hate it because they get bwoinked when they actually did do nothing

@duncathan what goof said, moles visible
