### ISSUE TITLE
Possible to have the same item picked for multiple display cases

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#27075]
Saw the same stun baton in two cases

**Comment by Profakos** [comment]
Trophies are setup using pick_n_take from the trophy item list, so what I suspect was that multiple stun batons were entered multiple rounds, with the same (probably default) text.

I could fix this by either a new description overriding the description of a new one, or just skip on saving if a saved item with the same description already exists. Which one would be more desirable?

**Comment by Profakos** [comment]
Alternatively saving is broken and resaves all the items, but that wasn't the case when I outputted the contents of the save file post saving when i was testing. Perhaps a trophy cases investigation panel is warranted too?

**Comment by octareenroon91** [comment]
Maybe add a date/time of acquisition?

**Comment by Profakos** [comment]
Perhaps, definitely a good idea for testing and logging purposes.

**Comment by Profakos** [comment]
I feel bad for not getting around fixing this. When the freeze ends, I should come back and fix the issues with the cases...
