### ISSUE TITLE
Ghosts block clicking under them

### ISSUE THREAD

**Issue by silicons** [tgstation/tgstation#27096]
oranges turned on ghosts and hit highlander and I couldn't hit anyone near me because I had a small ring of ghosts.
and i lost.
not acceptable
:salt:
critical priority issue

**Comment by Repukan** [comment]
Also an issue with the ghost sword

**Comment by MrStonedOne** [comment]
This issue has came up before, the issue is that we can't make them block left click without also removing them from rightclick, and this fucks up adminstration.

**Comment by bgobandit** [comment]
this kills tactical ghosts

**Comment by Cyberboss** [comment]
maybe put visible ghosts on the turf layer?

**Comment by MrPerson** [comment]
We can forward clicks on ghosts to the thing they're orbiting.

**Comment by PKPenguin321** [comment]
That would be worse if they're orbiting you

**Comment by MrPerson** [comment]
We can also only do that for things other than you

**Comment by MrStonedOne** [comment]
it would almost never be what you are trying to click.

What we will just have to do is make visible ghosts loose mouse opacity on orbit.

We could also use client images and make them put up a mouse visible client image to admin ghosts to keep right click and drag click working.

**Comment by TheBonded** [comment]
I feel like this has become more of a feature/known thing than a bug anymore. going to mark this as cleanup flagged unless anyone objects

**Comment by SuperNovaa41** [comment]
I disagree, this is unintended... and some people with more power than I agree

**Comment by Cyberboss** [comment]
Yeah, this is definitely a bug

**Comment by TheBonded** [comment]
I feel like this isnt a bug but more of an oversight (code working in the intended way having unintended consequences as an oversight, rather than code working in unintended ways as a bug), unless there is code that exists to stop this from happening that isnt working for some reason
