### ISSUE TITLE
You can use the RCD to build on hyperspace tiles

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#27093]
- Enter mining shuttle with RCD
- During transit, open door and build floors
- Enter hyperspace once shuttle docks

**Comment by evsey9** [comment]
Feature

**Comment by Marflowerose** [comment]
Can be used to get into Centcomm and other fun areas, I just built RnD at centcomm.

**Comment by Militaires** [comment]
maybe it's not a bug 

it kind of feels like a feature almost

please keep this.

**Comment by PKPenguin321** [comment]
Getting to centcomm is illegal
