### ISSUE TITLE
You can buckle the ash walker nest to a chair and move it around

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#27109]
![](http://puu.sh/vLo7J/f31f726ca7.png)
Might be able to do the same with tendrils
@KorPhaeron

**Comment by Expletive** [comment]
Feature

**Comment by octareenroon91** [comment]
I thought someone had tried to fix this about tendrils.

**Comment by KorPhaeron** [comment]
Buckling is letting you buckle anchored mobs then for whatever reason

**Comment by WJohn** [comment]
Applies to all tendrils.
