### ISSUE TITLE
The cerestation evac shuttle has a table right infront of several consoles

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#27111]
This table blocks 3 consoles, one of which being the shuttle control console. This requires you to decon the table to use the consoles.

**Comment by Penguaro** [comment]
From the most recent commit, the cere evac shuttle looks like this.

![cereshuttle](https://cloud.githubusercontent.com/assets/9791590/25899919/4cb91380-3557-11e7-8a99-b8be4a122a27.jpg)

Were you on the cere evac shuttle or was a different shuttle purchased by chance? What server revision were you on? Any chance of a screen shot? Is it possible the server you were on wasn't using the latest Cere Shuttle commit?

**Comment by Dorsisdwarf** [comment]
Are you sure someone didnt build a table there to annoy you taco

**Comment by Tacolizard** [comment]
re
