### ISSUE TITLE
Pipe meter breaks when the pipenet is changed

### ISSUE THREAD

**Issue by Jalleo** [tgstation/tgstation#27128]
When a pipe is removed at least the meter shall stop returning new changes to the air pressure as it is still referencing to the old parent in the pipe and not the new parent for some reason. 
See the relevant snippets from each proc here.
/obj/machinery/meter/New()
	src.target = locate(/obj/machinery/atmospherics/pipe) in loc

/obj/machinery/meter/proc/status()
		var/datum/gas_mixture/environment = target.return_air()

/obj/machinery/meter/examine(mob/user)
	to_chat(user, status())

/obj/machinery/atmospherics/pipe/return_air()
	return parent.air

/obj/machinery/atmospherics/pipe/build_network()
	if(!parent)
		parent = new /datum/pipeline()
		parent.build_pipeline(src)

I dont understand exactly how it stops getting the correct return_air but it does.

@duncathan Feature?
 
PS by the way when I mean break it just keeps returning what it returned last before the pipenet was built again.

**Comment by duncathan** [comment]
yo weird I'll look into this when I'm doing my pipenet shit

**Comment by Dennok** [comment]
Все еще актуально?

**Comment by Jalleo** [comment]
Not sure need to check. I can do that tomorrow evening probably.

**Comment by Dennok** [comment]
Still actual?(2)

**Comment by msgerbs** [comment]
Almost positive it's fixed as I have been doing a lot of screwing with pipes and meters and shit and not seen any issues with them. Will do some basic testing tomorrow.

**Comment by LemonInTheDark** [comment]
This does not appear to be the case, in either testing or when inspecting the code

**Comment by Mooshimi** [comment]
this is fixed
