### ISSUE TITLE
Can't RPD on catwalks

### ISSUE THREAD

**Issue by Shihrt** [tgstation/tgstation#27122]
Would be nice if the RPD could pipe directly onto catwalks. At the moment the only way is to either decon the catwalk or alt-click to get at the space tile underneath.

**Comment by CPTANT** [comment]
You can't RCD on catwalk either.

**Comment by RemieRichards** [comment]
It's not a floor, this isn't a bug.

**Comment by CPTANT** [comment]
it is a consistency issue. Catwalk should behave like a floor that has a vacuum on it for all applications.
