### ISSUE TITLE
Revenant respawning is broken

### ISSUE THREAD

**Issue by Thunder12345** [tgstation/tgstation#27130]
Die as revenant
Respawn from ashes
A few seconds later, get DCed, booted back to lobby
Other random player was forced into the revenant instead
Put myself back in, they get DCed and booted as well

I'm guessing #26784 is at fault here

**Comment by Cyberboss** [comment]
The fact that people have been getting DC'd and not ghostized recently really irks me...

**Comment by Thunder12345** [comment]
Booting to he lobby seems is a recurring issue that's cropped up occasionally over the years

**Comment by evsey9** [comment]
yeah i experienced this
got put into a revenant, with like, A LOT of prompts
then got DCed and booted back to lobby



decided to respawn

**Comment by Thunder12345** [comment]
Saw it work fine today, guess this got resolved
