### ISSUE TITLE
Rev rounds ending in revolutionary victory with all heads alive and not lockered.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#27135]
Happened 4:30pm EST, 5-10-17. Bagil.

**Comment by Jalleo** [comment]
What was the end reporting?

**Comment by BeeSting12** [comment]
End said that heads of staff were killed or exiled. I should've copy pasted it and included it here but the summary is that one head rev was dead, all four heads were alive and not attempted to flee the station. Two other head revs were alive.

**Comment by coiax** [comment]
Late join heads?

**Comment by CPTANT** [comment]
most likely linked to #11532
