### ISSUE TITLE
Spawn leaves reference to object it's called on, preventing garbage collection

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#27136]
More of a BYOND issue/quirk than codebase related, but still important enough I figured an issue report would be warranted.

Either case, yet another reason to hate/disallow use of `spawn`. Whenever `spawn` is used, it leaves an external reference to the object it's called on, which will prevent the object in question from garbage collecting. 

For instance:

```
/obj/widget/New()
	spawn(600)
		qdel(src)
```

If something were to delete `widget` before spawn ran, then `widget` would fail to soft delete/GC.

Moral of the story: don't use spawn as a timer function, as it'll prevent GCing under some circumstances and therefore increase total CPU cost of deletion.

**Comment by Cyberboss** [comment]
Yeah, spawn has been dying a slow death across the codebase. I guess we can close this when they're all gone

**Comment by Cyberboss** [comment]
Also
>widget
@MrStonedOne

**Comment by MrStonedOne** [comment]
Now, byond is smart enough to halt the hard delete process once it's found the last reference. So I wonder where searching proc references are on it's list of things to search. if its high up, it won't be that bad, but other wise, ya.

**Comment by Fox-McCloud** [comment]
@Cyberboss @MrStonedOne 

There's still plenty of spawns left, as far as I'm aware.

That only caught instances of `spawn(x)`. There's still instances of `spawn do_thing()` left.

**Comment by MrStonedOne** [comment]
i should point out, that byond only does a hard delete reference search until it deletes all references, since it knows how many exist, it can stop once it finds them all. and spawn/sleep are some of the first things checked.

So this only technically triggers a hard delete, its basically a softdelete in terms of performance
