### ISSUE TITLE
Cameras are borked

### ISSUE THREAD

**Issue by TrustyGun** [tgstation/tgstation#27134]
For some reason, cameras produce a completely blank image.

![image](https://cloud.githubusercontent.com/assets/7079721/25919140/bb2dcc72-359b-11e7-82b9-e5bd7a9153a6.png)

**Comment by Penguaro** [comment]
Did you try turning the server off and then on again and then shaking it from side to side?

**Comment by MrPerson** [comment]
Breaking news: Rapper "Photography" has been shot.

Again?

Again.
