### ISSUE TITLE
Offering ghost roles to players will throw a random player in regardless of whether or not they clicked yes

### ISSUE THREAD

**Issue by feemjmeem** [tgstation/tgstation#27133]
Multiple players in the same round on Bagil this afternoon ended up in ghost roles they didn't ask for after an admin offered the role.

**Comment by ChangelingRain** [comment]
I know I caused this, but I have no idea how.
#26990

**Comment by KorPhaeron** [comment]
150 hours of testing

**Comment by Jalleo** [comment]
Were ANY of these players not a observer beforehand?

**Comment by ChangelingRain** [comment]
This is my fault not robustin's!

**Comment by AlexCrimson** [comment]
Ive been pulled into a Sentience Potion Slime and a Possessed Blade whilst observing. All my preferences are disabled, as well as midround antag. Pretty damn annoying yo.

**Comment by Cyberboss** [comment]
Please for the love of all that is holy keep that label

**Comment by Bawhoppen** [comment]
priority tags mean nothing, we still have that priority critical tag from a year ago that lets you crash the server on demand but nobody fixes it

**Comment by feemjmeem** [comment]
All players were observers.

**Comment by Jalleo** [comment]
Then I am not sure what is causing it exactly by quickly looking over the code. I shall reread it later.

**Comment by cedarbridge** [comment]
Title is misleading.  Many of the cases don't actually give prompts at all.   I was pulled into several xenobiology sentience potion mobs last night instantly and withoutany prompt at all as per 27253
