### ISSUE TITLE
'Kent' serviceborg looks like a medborg

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#27165]
![img](http://image.ibb.co/cnjPgQ/kent.png)

**Comment by Jordie0608** [comment]
And why is this a problem?

**Comment by Tacolizard** [comment]
because serviceborgs don't look ike that

**Comment by GunHog** [comment]
Not an issue, it is intended.

**Comment by Dorsisdwarf** [comment]
Literally intended. It's a medborg but all the tubes are full of booze
