### ISSUE TITLE
[Cerestation]There are very few places to place a gang dominator

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#27164]
There seems to be very few places to place it with enough room.

**Comment by GunHog** [comment]
>Biggest station with the highest population restriction
>> Few suitable places to install a dominator

Just....wow!

**Comment by MMMiracles** [comment]
I mean, can't you just, like, take down a few walls at worst? Whoever added a restriction with walls next to doms is dumb tbh.

**Comment by Cyberboss** [comment]
No, @Robustin made the area too big. Dupe of #27177
