### ISSUE TITLE
[ASTEROIDSHUTTLE] Asteroid with engines can't launch to centcomm.

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#27162]
@kevinz000 You may have better logging than me.

Ignition time is locked at 10.

**Comment by kevinz000** [comment]
shitloads of high_pressure_movement() runtimes from the mineral turfs from first glance, round ID  70268 for logs.

**Comment by octareenroon91** [comment]
It MAY eventually launch if you give it forever.

Maybe we'll be able to find out if the ground turfs get left behind after that.

**Comment by Profakos** [comment]
Dupe of #25550, but this report is closer to finding out the reason probably.
