### ISSUE TITLE
YOU CANT FUCKING PLACE DOMINATORS AS GANG

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#27177]
FUCK YOU ROBUSTIN YOU PIECE OF SHIT YOU BROKE GANG YOU LITTLE FUCK

**Comment by evsey9** [comment]
#26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948 #26948

**Comment by Cyberboss** [comment]
150 hours of testing

**Comment by optimumtact** [comment]
150 hours of testing
