### ISSUE TITLE
panic bunker isn't filtering new players

### ISSUE THREAD

**Issue by LetterJay** [tgstation/tgstation#27179]
It's leaving the notice of a new player and their BYOND creation date, but it's not rejecting the connection despite the bunker being enabled.

**Comment by AnturK** [comment]
@Jordie0608 Age tracking changes ?

**Comment by Iamgoofball** [comment]
Why are we rejecting players still?

Bounce them to Basil/Sybil. Stop being retards about new players. Also, remove bunker being used to be xenophobic against new players.

**Comment by lzimann** [comment]
@Iamgoofball LetterJay is citadel's host. Plus, we don't always turn the bunker on because "fuck new players".

**Comment by Iamgoofball** [comment]
oh yeah i forgot about citadel

we used to turn the bunker on because "fuck new players", wasn't certain if that changed recently

**Comment by LetterJay** [comment]
We don't turn it on because "fuck new players". We use it to prevent anticipated raids

**Comment by PKPenguin321** [comment]
It's a goofball doesn't know what ban evasion is episode

**Comment by Iamgoofball** [comment]
@PKPenguin321 it's almost like Back In The Day it was turned on to "fuck new players"

**Comment by LetterJay** [comment]
Any news on this?
