### ISSUE TITLE
Hitting a dead player drone with a bolt of death prints a message to deadchat

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#27188]
They're already dead, it shouldn't generate a message.

**Comment by timothymtorres** [comment]
https://github.com/tgstation/tgstation/blob/c19b63c22bbc381e560b84154419fd562d481760/code/modules/mob/living/simple_animal/friendly/drone/_drone.dm#L232-L239

https://github.com/tgstation/tgstation/blob/55b92786dcf0f9c5172efd111a6ecbf83ec0dae2/code/modules/mob/living/simple_animal/simple_animal.dm#L435-L457

https://github.com/tgstation/tgstation/blob/c19b63c22bbc381e560b84154419fd562d481760/code/modules/mob/living/death.dm#L71-L81

It appears that the `death` proc is getting passed down all the way to the `/mob/living/proc/death(gibbed)` which causes a announcement to be made.  This may be happening for nearly all simple mobs that are killed and controlled by a player.  A simple fix might be to add a special trait that ignores death messages but then you'd have to make a blacklist of all mobs this applies to.
