### ISSUE TITLE
Plastic and titanium golems are the same colour

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#27194]
@XDTM 
We gotta hash out new shades of white for them.

**Comment by Armhulen** [comment]
Plastic should be see through.

That, or a custom sprite like mummy and cult golem.

**Comment by XDTM** [comment]
I was waiting on customsprites initially to code them. As we are now i think i or someone else could do a quick edit making the limbs smooth instead of rocky, reflecting the golem's stretchiness.

**Comment by coiax** [comment]
@XDTM also, you need to code golem tattoos.

**Comment by ChangelingRain** [comment]
maybe make the golems use the old colored sprite, but with color matrices applied to them?

**Comment by XDTM** [comment]
Isn't that what we do now
