### ISSUE TITLE
I detonated a maxcap in my hands and survived unharmed

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#27209]
Nice

**Comment by Jalleo** [comment]
MORE DATA REQUIRED!

**Comment by ChangelingRain** [comment]
@Cyberboss

**Comment by BeeSting12** [comment]
kind of a dupe: #26957

**Comment by Robustin** [comment]
I think it was fixed in one of Cyber's bazillion explosion changes so I'm closing this until I see it happen again
