### ISSUE TITLE
The invoker's shield Manifest Spirit summons no longer prevents people from bumping the invoker

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#27222]
ha ha. hoo hoo.
this is very annoying.

**Comment by Robustin** [comment]
I thought I saw this going on, are they not dense or does position swapping just ignore density now?

**Comment by ChangelingRain** [comment]
you bump them, they move to your tile, you dust because you're an idiot ghost
they're still dense though!

**Comment by octareenroon91** [comment]
Can the rune come with a free chair or something?

**Comment by Robustin** [comment]
But the shield/barrier should be dense, i.e. nobody can move onto that tile in the first place.

**Comment by kriskog** [comment]
Not an issue anymore.
