### ISSUE TITLE
Lavaland ruins spawned inside others.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27233]
![](http://i.imgur.com/wkgsaTt.png)

Likely also the case for space ruins. I thought this was fixed?

**Comment by Jalleo** [comment]
template_noop or bad area decuding maybe the issue. I will look at it later.

**Comment by WJohn** [comment]
This is definitely still happening, at least to space ruins.
![](https://i.imgur.com/2IvcbIV.png)

**Comment by Dennok** [comment]
Now ruins have protection from random placing another ruins on it.
So this is outdated.

**Comment by kriskog** [comment]
Yeah, this doesnt seem to be happening anymore.
