### ISSUE TITLE
for no clear reason there were a couple errors when i was blown as a borg

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#27236]
Sorry, the following is not valid: 1
usage: Toggle-Module is not accessible

**Comment by GunHog** [comment]
Additional explanation is required. Did this happen at the moment you were blown, or did it continue for a while? It looks like you were trying to use a borg specific verb, but having being blown, you were no longer a borg and therefore no longer had access to the verb.

Did this happen only once or multiple times? What were you doing when you exploded?
