### ISSUE TITLE
Attached proximity sensors are broken

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#27235]
The timer to arm proximity sensors does not count down, and even when manually armed, proximity sensors do not trigger when people walk by.

**Comment by PKPenguin321** [comment]
Might be a dupe?

**Comment by Jalleo** [comment]
Likely a bug caused by untested changes.

**Comment by Cyberboss** [comment]
Hey I tested it, but I can't test everything!

**Comment by Cyberboss** [comment]
They do count down btw, it just doesn't update because classic html

**Comment by CosmicScientist** [comment]
Still around. Sadface.

**Comment by imw-Oculus** [comment]
Add it to the processing list, and force proximity_monitor to keep checking even when the host is not on a turf. Wew.
