### ISSUE TITLE
TURN RUSSIAN REVOLVER INTO A REAL REVOLVER

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#27232]
![](http://i.imgur.com/wsrfBEU.png)

**Comment by GunHog** [comment]
THAT is AWESOME.

**Comment by obscolene** [comment]
why would someone share this in ooc instead of abusing it like mad

**Comment by PKPenguin321** [comment]
Remember when you could do this by default?

**Comment by Jalleo** [comment]
This is intended.
Just wait for russian revolver pins to be placed inside tasers or laser guns.

**Comment by ohnopigeons** [comment]
Undocumented feature

**Comment by BeeSting12** [comment]
>bug of the year
>isnt even a bug

**Comment by ohnopigeons** [comment]
"A mechanism prevents you from shooting anyone but yourself!" with standard firing pin. I can't find a PR fixing this so I'm guessing this never worked in the first place. Close this meme issue.
