### ISSUE TITLE
Metal rod duplication. (Reinforced Floor bug)

### ISSUE THREAD

**Issue by furryowl** [tgstation/tgstation#27256]
Video
https://drive.google.com/file/d/0B7wEdUY5vEbgcUpDMm1yQVVVRDQ/view?usp=sharing

**Comment by Dorsisdwarf** [comment]
I thought this was fixed. Good catch.

EXPLANATION: When you go through a floor tile being shot out of a pipe, it breaks the floor and leaves a tile behind. the tile item for reinforced floors is a rod. Reinforced floors are not broken by this however, but still spawn the rod.

**Comment by ohnopigeons** [comment]
So should reinforced floors break or should the rod not spawn

**Comment by furryowl** [comment]
@ohnopigeons I think second one
