### ISSUE TITLE
Sky Bulge Tomb space ruin has lavaland base turf under it's minable rock instead of asteroid baseturf

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#27251]
Revision: ff5272 

I went into space and found Sky Bulge.  Since I had mesons and mining gear, I smashed a couple of the rock walls, and they had lavaland volcanic turf under them instead of asteroid floors.

**Comment by Penguaro** [comment]
@Expletive I'm honestly unfamiliar with what the Sky Bulge is and this is something I can fix in five minutes. Can you give me any other details to identify it? Like Artifacts or special mobs there or a basic description of what the area looks like?

**Comment by Kromgar** [comment]
@Penguaro Its a magic spear. It has flan mobs in it.

**Comment by Penguaro** [comment]
@Kromgar I believe I know which map you're describing. Thanks!

**Comment by Haevacht** [comment]
let me fucking remove the tomb already cheridan
