### ISSUE TITLE
Gang winning does not display gang details or who won at round end

### ISSUE THREAD

**Issue by TehZombehz** [tgstation/tgstation#27255]
I, and others, saw no gang details after a recent gang rounded ended in a Clandestine gang victory recently. The gang clearly won, but only the normal 'The round has ended' statistics displayed; No details regarding who won, what gangs existed, or who were in said gangs appeared at the round end.

I was observing when this happened.
Others who were playing claimed to have seen this as well after the round ended.
This can probably currently be replicated by winning (or maybe just ending) a gang round.

**Comment by Dorsisdwarf** [comment]
tentatively @Robustin since you've been up to your elbows in gang's guts lately

**Comment by Robustin** [comment]
This has been an issue since last year but my big gang PR fixes it.

**Comment by Repukan** [comment]
@Cyberboss this is fixed, had a gang round that showed north gang winning
