### ISSUE TITLE
Xenobiology Mobs do not ask ghosts before forcing them into sentience

### ISSUE THREAD

**Issue by cedarbridge** [tgstation/tgstation#27253]
This ends up with the mobs being occupied with either busy admins or afk ghosts 90% of the time because there is no prompt for the role.  It merely grabs the ghost and stuffs it into the body.

**Comment by QualityVan** [comment]
Is this with sentience potions or something else?

**Comment by cedarbridge** [comment]
Yeah, sentience potions.

**Comment by Dorsisdwarf** [comment]
dupe of #27133
