### ISSUE TITLE
If you have 99HP you can enter an infinite loop of Take Oxy loss -> Crit -> Heal Oxy loss

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#27274]
Not sure the specifics of it but basically every 2 seconds you'll get up and fall back down. Dealing +/- 1 of any damage will break out it

**Comment by XDTM** [comment]
You heal oxyloss when you breathe, i think that just as you enter crit you don't have any losebreath yet and get the 1 point heal that causes this.

**Comment by nicbn** [comment]
Can't reproduce this

**Comment by Cyberboss** [comment]
soft crit
