### ISSUE TITLE
Lack of head does not prevent flashbangs from working.

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#27273]
Same with tear gas.

Poor changelings.

**Comment by RemieRichards** [comment]
well... arguably all of their cells are reacting to it.
but this only works for lings (but then again, only lings can survive headless atm)

**Comment by Iatots** [comment]
But then, how would you explain almost-naked lings wearing gasmask, sunglasses and earmuffs resisting them?

**Comment by PKPenguin321** [comment]
Require the victim to actually have functioning eye/ear organs to apply the flashbang effects

**Comment by ShizCalev** [comment]
Tear gas should still cause a reaction though, since I would assume they would be breathing it in through their... neck hole... yeah.
