### ISSUE TITLE
i can greytide grilles from under windows

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#27287]
https://gyazo.com/0a2336fc01b47eeaccf131b8eccbe28c

**Comment by Cyberboss** [comment]
@AnturK

**Comment by deathride58** [comment]
But how will harmless greytide be possible if this gets fixed? Greyshirts gotta have fun somehow!

**Comment by AnturK** [comment]
Ugh, fiix 10 bugs with Adjacent, 10 more pop up.
