### ISSUE TITLE
No leg, slow jetpack travel

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#27286]
Lost my leg during war ops, escaped into space, but I was flying slowly as if I was limping on the station.

**Comment by YakumoChen** [comment]
built in jetpack uses your current speed, not fastmove

**Comment by MimicFaux** [comment]
When you're in zero-G though?

**Comment by PKPenguin321** [comment]
Yeah inbuilts were nerfed to be slower than regular jetpacks
