### ISSUE TITLE
Nuclear Operatives Literally do not have brains.

### ISSUE THREAD

**Issue by SamSamsonthe3rd** [tgstation/tgstation#27293]
The irony, it is delicious.

Was roboticist, figured I'd take an op's head that was blown off when she self-destructed and make a borg out of her brain. However, when I pried it open, all that came out were the tongue, ears, and the x-ray eyes. I don't know if this is intended, or if the explosive implant destroys the brain, but it seems a little too literal for fluke ops to actually not have any gray matter between them.

**Comment by jughu** [comment]
They are auctally synths
Sekret lore

**Comment by InsaneHyena** [comment]
Why do you think they fluke so often?

**Comment by AnturK** [comment]
Not a bug, intended implants do not leave brain.
