### ISSUE TITLE
Adding reagents to sliceable foods does not share the reagents with the resulting slices

### ISSUE THREAD

**Issue by cedarbridge** [tgstation/tgstation#27300]
This applies to pizzas but may not apply to breads/cheeses only in that those will likely take away your syringe rather than inject it.

Adding a reagent (any) to a whole pizza and then slicing it produces new slices without the extra added reagents.  This means you can poison a pizza and waste the toxins used by cutting the pizza into parts instead of just producing a set of reagent laced slices.

**Comment by Armhulen** [comment]
Ruined the borg gimmick

**Comment by QualityVan** [comment]
I can't replicate this, syringing reagents into a regular pizza or custom pizza and slicing it leaves the proper reagents in the resulting slices.

**Comment by cedarbridge** [comment]
Yeah, I don't know what's up.  It seems to be working normally now. It definitely didn't at the time.
