### ISSUE TITLE
Icon Scaling Mode preference doesn't seem to actually save

### ISSUE THREAD

**Issue by dannno** [tgstation/tgstation#27307]
Every time I start up the game, I wonder why it's so ugly looking. I check Scaling Mode, and it SAYS it's on point sampling, but it's actually on the first option; Nearest Neighbor. Picking point sampling (even though it's already checked) will make it point sampling.

**Comment by ShizCalev** [comment]
dupe #27281

**Comment by MrStonedOne** [comment]
http://www.byond.com/forum/?post=2253345
