### ISSUE TITLE
Free Golem name generation can sometimes lack a sirname

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#27318]
I saw a golem just called "Adamantine"

Server revision compiled on: 2017-05-15
The following pull requests are currently test merged:
#26677: 'Codespeak language and manual' by coiax 

Based off master commit: 768fb0

**Comment by deathride58** [comment]
They're cheap golems, surnames weren't fully covered in the Liberator's budget.

**Comment by ArcaneMusic** [comment]
Tested locally by S. .S#7958 on discord:
 

>  ...It never game a empty last name even when I lowered the possible name to 2.
