### ISSUE TITLE
Communications Console Non-Functional

### ISSUE THREAD

**Issue by Steelpoint** [tgstation/tgstation#27329]
Comms Consoles in a recent round were nearly non-functional. The round was a Traitor round, we were also test merging #27305

If you clicked a console you would end up at the log in screen, if you attempt to log in nothing will happen. If you close the console screen and attempt to open it again, nothing will happen.

Only way to get the screen to re-appear is to screwdriver the console and rescrewdriver it, but that does not fix the issue.

This made it impossible to evacuate, forcing a second AI to be built just so we could call evac.

**Comment by Lumipharon** [comment]
I encountered this earlier today, exactly the same.
This plus that other pr has made a hilarious situation where the ride never ends.

**Comment by Steelpoint** [comment]
I don't know if the 'you can never call evac' PR has anything to do with this, but I thought its worth mentioning. 

Either way this is a very annoying bug.

**Comment by Cyberboss** [comment]
Is this still happening?

**Comment by Steelpoint** [comment]
Seems to not be occurring anymore, perhaps it had to do with the test merge.

**Comment by Steelpoint** [comment]
This seems to be resolved.
