### ISSUE TITLE
AI languages are randomly forgotten, AI language menu does not open consistently

### ISSUE THREAD

**Issue by Daundra** [tgstation/tgstation#27327]
Server commit (I think this is the right thing to use): 768fb0 

Randomly throughout the round for no apparent cause, I, as an AI, keep forgetting my languages, and become completely unable to speak to the crew. It has happened at completely random times, such as after following someone on a camera, or having done nothing at all. It has happened a total of 3 times in this one round. Picture related:

http://i.imgur.com/1DpNYRQ.png

This issue persists until an admin has to manually reset my languages (I think that's what they're doing), or it just goes away on its own.

Related to this probably, but clicking my "language menu" button sometimes does nothing at all, including when the first issue is occurring, where it does not appear whatsoever.

**Comment by coiax** [comment]
God dammit, how can this keep happening

**Comment by XDTM** [comment]
Transfer between core and camera?

**Comment by carshalash** [comment]
Happened pretty much every round I was AI today. 

Makes the role pretty unplayable when you randomly become unable to hear or say anything outside of binary

**Comment by coiax** [comment]
At least the no languages is being handled correctly. So what's likely happening is the language holder is disappearing for some reason, but I have no idea why.

**Comment by Alek2ander** [comment]
Apparently this happens when AI uses a holopad

**Comment by ShizCalev** [comment]
Confirming, triggered it by using a holopad.
