### ISSUE TITLE
Mining Points counter does not work

### ISSUE THREAD

**Issue by Vakulum** [tgstation/tgstation#27320]
When using the Ore Maschine or the mining vendor the mining points do not update. 
On ore maschine switch from unclaimed points to card.
On Vendor it does hnot substract points when you buy things. 

They get counted right but is wont update in the window. If the card is removed and inserted again then its correct. 

Server Bagil

**Comment by Penguaro** [comment]
@Vakulum - I just want to be sure I understand.

For all intents and purposes, the credits are being added to the card and deducted appropriately but the pop-up window is not reflecting that unless you close it and reload it?

**Comment by Profakos** [comment]
This was happening before I touched it with the disk slot PR imho, can confirm that it is not calling updateusrdialog for some reason, but it updates the card itself.

**Comment by Penguaro** [comment]
@Profakos If it's what we think then yeah I've known about this for a while but didn't feel bothered by it enough to post an issue. I just wanted to confirm it wasn't something new that I was misunderstanding in the original post.

**Comment by Vakulum** [comment]
@Penguaro 
correct. 
The Bug is there for a while, too but I remebered my GitHub pasword recently so I just added it yesterday

**Comment by WJohn** [comment]
Yeah this bug has been around since its implementation, I think.

**Comment by Profakos** [comment]
With the TGUI remake, this issue is probably no longer an issue.

**Comment by bgobandit** [comment]
I think this has been fixed @Vakulum

**Comment by lordpidey** [comment]
@Cyberboss I beliee this was fixed.

**Comment by Repukan** [comment]
@ChangelingRain This can be closed, apparently fixed
