### ISSUE TITLE
Shuttles fail to function entirely

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#27325]
Arrivals shuttle refuses to dock if used by late joiners, extremely problematic. Even if forced to dock with the shuttle manipulator, still fails.

**Comment by reizoku** [comment]
The supply shuttle doesn't work as well

**Comment by kevinz000** [comment]
rip

**Comment by Ausops** [comment]
mining shuttle doesnt work either as of 
Server revision compiled on: 2017-05-16

Based off master commit: db22ad

**Comment by WJohn** [comment]
Should be fixed, now.
