### ISSUE TITLE
Operating consoles with brain damage is not obvious on what's going on.

### ISSUE THREAD

**Issue by Steelpoint** [tgstation/tgstation#27330]
Any kind of console that use the newer HUD system (Like the solar array console. ID console or APC interface) is unreliable to use for me.

What happens is that when I use these consoles, my HUD will constantly grey out the icons every couple of seconds before restoring the buttons a few seconds later.

In addition, some times the consoles don't respond to clicks or commands, forcing me to re enter the command multiple times.

**Comment by XDTM** [comment]
Could it be brain damage? It has that exact effect.

**Comment by Steelpoint** [comment]
I actually did have brain damage that round. 

So this is less of a bug and more the fact the game fails to communicate as to why this is happening.

**Comment by WJohn** [comment]
What's the point of making buttons gray out for a couple of seconds? It doesn't prevent someone from doing anything, only makes the UI looks messy. If you want to prevent people from using the console, actually bar them from doing so (and giving them a message in the bottom right, like "You're too stupid to use this!" or something).

**Comment by Kromgar** [comment]
@WJohn 

That's what it used to do

**Comment by Steelpoint** [comment]
I can see the justification already for the change.

On paper its a good idea, it still gives a negative to having brain damage but it won't stop you from using a console in a annoying manner.

In practice it leads to a confusing system where you have no idea you're not suffering from a genuine bug but actually from a game mechanic that is never explained or hinted at. 

The old system may have been annoying but at least you knew why it was happening.

**Comment by Iamgoofball** [comment]
all we have to do is just drop a "you forget how to use X" message

**Comment by XDTM** [comment]
It's because tgui is too responsive, with the old UI what happened was that you _could_ click the button but doing so spawned the `too stupid` message. Tgui instead greys the buttons as soon as you are unable to use them, so you can't click them to get the message.

**Comment by Steelpoint** [comment]
Then it gets awkward when you're typing a message that is constantly denied when the screen greys out, or you spend twenty seconds trying to set a SMES cell to maximum power input but you can't due to bad luck.

**Comment by coiax** [comment]
What we need is for brain damage to have a chance of making you press the wrong button when using consoles. Probably would have to be done by hand, since not all tgui are IC.

**Comment by Penguaro** [comment]
Wow, I had no idea this was related to brain damage. I've had this happen and I just assumed the tgui was glitching on me and I'd spend half the round re-logging, clearing cache, updating byond and IE trying to fix it.

**Comment by RemieRichards** [comment]
@coiax like how emagged sleepers work?

**Comment by Repukan** [comment]
@Cyberboss not a bug, can be closed.
