### ISSUE TITLE
Chaplain possess sword can only speak Narsie

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#27334]
Because it's actually just a shade inside the sword.

**Comment by TehZombehz** [comment]
If there's not an issue already, this would totally be related to how shards can only speak narsie. I dunno if the chaplain's shard does this. Even if your master is not a cultist, you still speak narnar. Is that intended?

**Comment by Kromgar** [comment]
This would presumably also effect mining

**Comment by FantasticFwoosh** [comment]
It does cromgar, the swords do not respond to manual inputs of ,O to speak galcomm for instance and have no UI hud to change languages or view the languages in which you speak.

**Comment by coiax** [comment]
All mobs have the IC->Show Language Menu even if you don't have the HUD element.
