### ISSUE TITLE
Throwing items can be used to destroy airlocks you otherwise wouldn't be able to damage.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27348]
If you try to hit an airlock with a weapon that doesn't deal enough damage to actually damage it, nothing will happen and it won't take damage.

If you THROW the weapon, it'll actually damage the airlock. A powerful throw force weapon like a spear could be used to destroy one when you otherwise wouldn't be able to.

I'm guessing there's something missing about throwforce with integrity.

**Comment by PKPenguin321** [comment]
Literally a feature

**Comment by GunHog** [comment]
A spear is a very poor example here, WJ. Spears have a greater throwforce, which passes the 20 force threshold required to damage them. This will be true for any throwing item, and is entirely intended.

**Comment by Repukan** [comment]
Spears have higher throw force.

**Comment by Repukan** [comment]
So do hatchets

**Comment by WJohn** [comment]
Except that doors have 30 armor, which is the minimum required damage to actually DAMAGE the door.

Unless there's some mechanic going on here that I'm not aware of on how integrity armor works (66% armor threshold?)

**Comment by Repukan** [comment]
Different doors have different armor.

I think you need at least 21 damage to damage normal airlocks

**Comment by Cyberboss** [comment]
Literally a feature

**Comment by lzimann** [comment]
Items have a different throwing force than force, which is intended.
