### ISSUE TITLE
Calling other holopads doesn't work at all.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27345]
If you stand on a holopad and request another one for an audience, and you don't get any answer (possibly even IF you get an answer), the holopad will no longer be useable. You won't be able to call another holopad again.

More than that, it doesn't seem as if the other holopad even RESPONDS, there is no light emitted or anything, there's no way to know it's being called.

**Comment by AnturK** [comment]
@Cyberboss There's still ton of runtimes.

**Comment by kevinz000** [comment]
ripperonies!
