### ISSUE TITLE
cloned zombies still have undead eyes and tongue

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#27350]
memes

i was a cloned brain when this happened

**Comment by QualityVan** [comment]
Infectious, non-infectious or drug? Did you have claws? How was your brain removed from your body?

**Comment by FantasticFwoosh** [comment]
Because of coiaxes headcloning commit #27068 , I cannot remember if the zombie tumor is also located in the head and replicating what the zombie lost, those are the exceptional zombie type organs.

> Zombies are a species remember, when you convert to a zombie you need to be de-converted by having the necessary operation to remove the tumor.

**Comment by Militaires** [comment]
i was a romerol zombo, i got brain'd, cloned, then had no claws but an undead tongue and eyes

**Comment by QualityVan** [comment]
Did you get claws at any point?

**Comment by FantasticFwoosh** [comment]
@Militaires it literally doesn't matter. Its a carbon zombie species because the simplemob was phased out, if anything the bug would be not re-attaching the claws & a fix would be instantly curing the cloned person when they come out of the cloner without a romerol organ tumor.
