### ISSUE TITLE
If an admin logs out and a player tries to respond to an in-progress ticket, it creates a blank entry

### ISSUE THREAD

**Issue by harmonyn** [tgstation/tgstation#27353]
"but why would an admin log out?" For example, if the client crashes, which happens to me about once per 2 minutes in game. This can get spammy fast in tickets.

**Comment by Cyberboss** [comment]
Can you screencap this please?

**Comment by bgobandit** [comment]
@Cyberboss 

!(http://i.imgur.com/l3w8UeS.png)[ticket]

**Comment by bgobandit** [comment]
(The censored parts are simply a bunch of "Reply PM from -")

**Comment by magatsuchi** [comment]
issue no longer occurs after attempting reproduction
