### ISSUE TITLE
buckled walking mushrooms are able to move their chair around if they're aggroed

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#27363]
rogue shrooms

**Comment by banthebantz** [comment]
shrooms strong

**Comment by Tacolizard** [comment]
stronk slavic shroom

**Comment by PKPenguin321** [comment]
Might be a dupe

**Comment by kriskog** [comment]
Still an issue.

**Comment by dragomagol** [comment]
![image](https://user-images.githubusercontent.com/66640614/98324640-b31ab600-1fa1-11eb-8bc1-ce4e775ab8b6.png)
