### ISSUE TITLE
Transfering to a new body as a golem and having it stolen by someone else entering it first will send you to nullspace.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27373]
If you are a golem, and click on a new golem shell to transfer yourself (for upgrade purposes as of #26765 ) and someone else (a ghost, for example, because they receive notifications on new shells) enters the body BEFORE you manage to hit yes on the prompt, and THEN you hit yes? You will be sent to nullspace.

Thanks for the help in testing @Dorsisdwarf

**Comment by Armhulen** [comment]
150 hours of testing
