### ISSUE TITLE
Job preferences being ignored?

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#27390]
![image](https://cloud.githubusercontent.com/assets/6778786/26201735/645d4140-3ba2-11e7-8a06-53b4a0b4d145.png)

![image](https://cloud.githubusercontent.com/assets/6778786/26201756/77e1f1de-3ba2-11e7-8863-fbad492059d5.png)

Spawned as RD with shaft miner set to high and RD low

**Comment by lordpidey** [comment]
Were you an antagonist?  Antag overrides job prefs.

**Comment by Iamgoofball** [comment]
@Kromgar Game prioritizes empty jobs over jobs with people in them now. Intentional.

@Dorsisdwarf close this, non issue

**Comment by lzimann** [comment]
@Iamgoofball That was reverted. Although this is not an issue, heads of staff roll before regular jobs(at least one head will be rolled before), which means a low chance when no one else has set will give you a good chance of getting it.
