### ISSUE TITLE
You can put the nuke disk on the arrivals shuttle making it unobtainable for a period.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#27399]
Title says it all. Someone stuck it in a medkit and the shuttle went back into space leaving it stranded.

**Comment by octareenroon91** [comment]
>Centcom Z level

Are we going to have to put all the cargo-shuttle restrictions on the damn thing?

**Comment by TheDreamweaver** [comment]
Thank god this was reported. I hate to be accused of something... -_-

**Comment by Cyberboss** [comment]
Creative fucks...
