### ISSUE TITLE
Logs are broken

### ISSUE THREAD

**Issue by Repukan** [tgstation/tgstation#27401]
Ahelped today and admin said logs for a blown Borg was broken. Dunno much about it since it wasn't me noticing it being broken, but reporting it since it did affect the ahelp/process.

**Comment by Jordie0608** [comment]
Who was the admin?

**Comment by Repukan** [comment]
Niknak

**Comment by optimumtact** [comment]
@Niknakflak can you explain this or I'm gonna close it

**Comment by lzimann** [comment]
Logs are working fine. Public logs are not working right now, but it has nothing to do with the code.
