### ISSUE TITLE
Using a holopad as AI can make everyone incoherent to you.

### ISSUE THREAD

**Issue by Gouty** [tgstation/tgstation#27400]
When you are an AI, if you use a holopad after exiting it you can:

- no longer understand any non silicons (all their text appears as Ratvarian)
- no longer talk over non silicon channels (when you try to talk it just says _"[AI NAME] made a strange noise"_
- talk and receive fine on silicon chat
- send and receive PDA messages just fine
- talk if you go to a holopad, but everyone's text still appears garbled

This has been happening for the last few days for me

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/pull/27367

Already fixed? Or is it still happening for you?

A workaround if it's still happening is to reconnect.

**Comment by WJohn** [comment]
Already fixed.
