### ISSUE TITLE
Jetpacks turned on in gravity cause you to act as if you're in no gravity

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#27406]
Essentially the title. If you turn on a jetpack onstation, you get the zero gravity popup and the ability to go SONIC SPEED. It's supposed to act as normal until you go into zero gravity.

**Comment by WJohn** [comment]
Huh. Thought this way maybe a feature?

**Comment by BeeSting12** [comment]
If it's a feature it needs work. Such as maybe not having the zero gravity symbol show up? I'm pretty sure it's a bug unless this was added recently.

**Comment by Kromgar** [comment]
This is a dupe.

**Comment by WJohn** [comment]
So it is. Dupe of #26482
