### ISSUE TITLE
if you become a ling and lose your head before reviving you'll be able to see ghosts

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#27408]
![](http://i.imgur.com/Cr2Ejkl.png)

**Comment by Repukan** [comment]
Ling or Dullahan?

**Comment by octareenroon91** [comment]
The head, like the brain, is vestigial, no?

**Comment by kriskog** [comment]
Still an issue

**Comment by Mooshimi** [comment]
I actually saw a ghost while in crit, and no wizard so taking this label off

**Comment by timothymtorres** [comment]
Being near death has a chance to let you see ghosts with `TRAIT_SIXTH_SENSE`

https://github.com/tgstation/tgstation/blob/9d3f121722e6c3f0a99c88698e7e602cc2d32616/code/modules/mob/living/carbon/carbon.dm#L795-L807
