### ISSUE TITLE
[Delta Station] You can launch the Emergency Shuttle on Code Delta

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#27419]
Delta emergency shuttle can launch on ops rounds even if the operatives have already activated the nuke and it's still live. 

Shuttle should stall out due to hostile situation, as it does for other Delta scenarios on other stations.

Not tested for other round types but observed to happen on Nuclear Emergency.

**Comment by WJohn** [comment]
Oh, I thought it was intended where the shuttle could leave even if the nuke was ready? It's specific to delta station, then?

**Comment by YakumoChen** [comment]
I'm pretty sure the shuttle shouldn't leave if it's Code Delta at all, it stops the shuttle on all other round types.

**Comment by BeeSting12** [comment]
This happens on all maps and I also think it's intended.

**Comment by Cyberboss** [comment]
Yeah it's a design of the gamemodes. Not related to code delta.
