### ISSUE TITLE
Projectile dampener fields broken in multiple ways.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27410]
![](http://i.imgur.com/RHtuOEl.png)

These things do not follow the cyborg, are PERMANENT (even after cyborg death), and can be made screwy looking by moving while clicking the device to activate it.

Did you test this at all?

**Comment by ChangelingRain** [comment]
@kevinz000

**Comment by Cyberboss** [comment]
@kevinz000

**Comment by PKPenguin321** [comment]
>test

*laughs in kevinz*

**Comment by ma44** [comment]
_laughs in ma44_

**Comment by GunHog** [comment]
I totally tested this and told him about it!

**Comment by kevinz000** [comment]
im sorry ;-;
