### ISSUE TITLE
Ceres' countless problems

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#27411]
Use this issue report to catalog the several bits of ceres that need polishing 

To start: The ACME doors near arrivals that have walls under them

**Comment by WJohn** [comment]
Should probably note that cerestation has seemingly some sort of power problem with its north (horizontal) hallway. It ALWAYS dies out every round.

**Comment by Penguaro** [comment]
@Bawhoppen Because different issues can have broader causes this is rather impractical here. This would be better suited as a Forum post that you coordinate with @MMMiracles.

**Comment by Bawhoppen** [comment]
I've explained this in that PR, this is the best way to do it IMO

**Comment by lzimann** [comment]
It's an awful way to do. The best is keep each issue separated so it's easier to control what has been fixed and what has not.

**Comment by Penguaro** [comment]
You're basically creating a nested issues list. 

> nobody is going to spend the effort to make a full issue report for a super minor thing, but those minor things add up

That's true of any aspect of the software, not just Cerestation. The best solution is to submit issues and encourage others to submit issues if you see them salt about it.

**Comment by Bawhoppen** [comment]
people don't like ceres because of the issues, so they don't report them which just creates a vicious cycle

**Comment by Penguaro** [comment]
Then tell them to submit an issue. If they hee and haw about doing that, then don't worry about it since it doesn't bother them that much. People who lament about a problem but refuse to take easy action toward solving it are just looking for attention.

**Comment by MMMiracles** [comment]
There are people who dislike the map and therefore refuse to actually comment on said issues because then they'd get fixed, I know because I've actually ran into a few people who are non-ironically doing this when I observe for issues.

You're better off listening for issues and reporting them individually, either in git or on the feedback thread.
