### ISSUE TITLE
Delta level threat caused by nuke activation uses the dying toy-noise.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27418]
Instead of the actual sound it uses the one from the nuke toy, which sounds all dead and cute.

This is kind of an adorable bug.

**Comment by ShizCalev** [comment]
Are you sure you weren't just around someone with a pinpointer when the nuke was activated? They play the same sound to alert the holder that shit's getting real.

**Comment by WJohn** [comment]
I did not know the pinpointer made that sound when delta alert was reached. Case closed, I guess?
