### ISSUE TITLE
Chameleon guns set to a medical beamgun shoot bullets

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#27428]
Chameleon damageless bullets but bullets nonetheless

**Comment by Dorsisdwarf** [comment]
I'm not sure this counts as a bug seeing as I have no idea how this could be implemented or why the beamgun is even an available skin

**Comment by Repukan** [comment]
Beamgun

Beam gun

Gun

**Comment by kevinz000** [comment]
this is technically not a bug, I only made it work for the 95% of the guns that people will use in game.
Beamgun? While I could have it fire a beam or something, is it worth it?
Basically I'd call it "this feature isn't fully developed due to not being needed at the time"

**Comment by DaxDupont** [comment]
@Cyberboss cham guns were removed can be closed.
