### ISSUE TITLE
Tendril Spawned in mining base

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#27433]
![image](https://cloud.githubusercontent.com/assets/6778786/26250940/b1706ac0-3c79-11e7-8a7f-27a4f0d7dec4.png)

**Comment by Kromgar** [comment]
Roundstart: Entire mining station was depressurized due to goliaths breaking in

**Comment by GunHog** [comment]
Looks like it spawned just outside the base, not in it.

**Comment by Kromgar** [comment]
@GunHog Never seen a tendril spawn that close before i thought there was a couple tile buffers it was right outside the window

**Comment by Repukan** [comment]
Misleading pr title.

Also I've had watcher and legion tendrils spawn that close too.

**Comment by KorPhaeron** [comment]
Are you sure an admin didnt do it? This is well into the buffer zone

**Comment by Kromgar** [comment]
@KorPhaeron It was right at round start . Last round get this 5 steps out the door was the crashed alien ship and the hierophant arena was like 3 tiles north of the eva

**Comment by KorPhaeron** [comment]
Alright I did the math for this its a 1/7000 chance for this to happen on that tile

**Comment by Repukan** [comment]
Feature

**Comment by Cyberboss** [comment]
Feature

**Comment by Repukan** [comment]
Jinx

**Comment by WJohn** [comment]
What buffer zone? We frequently have megafauna spawning literally outside your front doors because there doesn't seem to be any sort of control over where monsters can spawn. The monster spawning system in general is super dumb, being tied to both the turf and the area.

**Comment by Repukan** [comment]
Surely you have screenies or data to back up such bullshit claim, Cloaca?

**Comment by WJohn** [comment]
I've definitely seen some megabeast (either colossus or ash drake) sitting about 3-4 tiles above mining's EVA before. I'll keep an eye out on extremely close megabeast spawns, though. I don't know if a buffer WAS added since but it doesn't look that way, given the areas are still all the same.

**Comment by Kromgar** [comment]
One time round start i landed with the shuttle. AS BUBBLEGUM RAMMED ME TO DEATH UPON LANDING. 

Turns out he spawned in the lava river and was close enough to wreck shit

**Comment by Penguaro** [comment]
I've seen bubblegums in open space just outside of gulag near round start. That's just more fuel for the "But Gulag is a death sentence waa waa waaaaa" nonsense.
