### ISSUE TITLE
Survival pods are fullbright again

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#27437]
h e l p

**Comment by octareenroon91** [comment]
What should they be?

**Comment by ChangelingRain** [comment]
they should have normal lighting, like everything else.

**Comment by Bawhoppen** [comment]
golem ships have fullbright too, fix please

**Comment by YakumoChen** [comment]
how is this a bug? Golem ship should be fullbright, it's a shuttle and any starting lights are very far away from where golems spawn.
