### ISSUE TITLE
Wall buttons don't work

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#27432]
Players can't cycle the airlocks to get into virology or xenobio. People are getting trapped roundstart and are left unable to do their jobs at all.

I couldn't get the EVA shutters open on metastation either.

**Comment by KorPhaeron** [comment]
@Cyberboss send help

**Comment by GunHog** [comment]
Needs the 150 hours of testing tag

**Comment by Cyberboss** [comment]
@AnturK !

**Comment by AnturK** [comment]
#27417
