### ISSUE TITLE
player panel breaking after de/readminning

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#27451]
1. deadmin
2. readmin
3. hit player panel
4. it's now a select list instead of a popup that gives you a search function

**Comment by Durkel** [comment]
Fuck, I was wondering what made it break that one time.

**Comment by Cyberboss** [comment]
Related #27091

**Comment by lzimann** [comment]
Can't reproduce this.

**Comment by nfreader** [comment]
Same.
