### ISSUE TITLE
Teleport talisman grammar can be broken with he or she

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#27462]
`user.visible_message("<span class='warning'>Dust flows from [user]'s hand, and [user.p_they()] disappear with a sharp crack!</span>"`

> Dust flows from Bob's hand and he disappear with a sharp crack!

It works with they, but not with he or she.

**Comment by ChangelingRain** [comment]
needs to be changed to `disappear[user.p_s()]`
