### ISSUE TITLE
Space Ninja adrenals are maybe broken

### ISSUE THREAD

**Issue by Goodstuff123456** [tgstation/tgstation#27461]
Before ninjas got the buttons and just used verbs, they could use their adrenals to escape stuns but now once they get stunned they are unable to use the adrenals not sure if this is intended but it seems kind of pointless to have if you cant escape a stun with it.

**Comment by lordpidey** [comment]
That's really wierd.  It literally calls the same proc as before.  The only change to the proc is I removed the verb-ness from it.  I'll look into this.
