### ISSUE TITLE
No Gravity on lavaland

### ISSUE THREAD

**Issue by oprayx77** [tgstation/tgstation#27469]
Problem Description: No gravity on lavaland

What did you expect to happen: All other instances you enter the lavaland from, you have gravity

What happened instead: You should immediately have gravity and not be able to jet around using your jetpack on the lavaland,

Why is this bad/What are the consequences: You can move at the speed of sound into and burn yourself on lava, also everyone else has gravity but you.

Steps to reproduce the problem: The most important section. Review everything you did leading up to causing the issue.
Take the station teleporter to abandoned teleporter. Fly due north. Get on the white ship, fly to the derelict. Then fly to the lavaland whilst wearing a jetpack. Tada! you have no gravity.

Server: Which server were you playing on?
Sybil

Revision: What revision was the server running? Type 'show-server-revision' ingame to find out.
Server revision compiled on: 2017-05-20
c571d2 

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Just a normal assistant, had a medical hardsuit on from the whiteship.
had the jetpack on without stabilization.

**Comment by BeeSting12** [comment]
Dupe of #26482

**Comment by oprayx77** [comment]
whoopsy
