### ISSUE TITLE
When the Peacekeeping Cyborg's hardlight field stuns you when you climb onto it, it leaves the item sprite of whatever you were holding in your hand permanently. 

### ISSUE THREAD

**Issue by obscolene** [tgstation/tgstation#27464]
kevinz 'literally cannot stop creating bugs' 00 strikes again

**Comment by BeeSting12** [comment]
150 HOURS OF TESTING

**Comment by Repukan** [comment]
1 5 0

**Comment by kevinz000** [comment]
brb testing

**Comment by kevinz000** [comment]
right ok this isn't my fault
https://puu.sh/vWfls/6307eabb69.gif
![lmao](https://puu.sh/vWfls/6307eabb69.gif)

**Comment by kevinz000** [comment]
ER, THIS ISNT MY FIELDS BUGGING OUT, BUT THIS DEFINITELY IS A BUG, AND THIS HAS HAPPENED TO ME BEFORE, IT JUST ISN'T SPECIFICALLY FIELDS BREAKING THEM!

**Comment by MrStonedOne** [comment]
I can't see your inventory so the gif is useless. make a bigger one please.

**Comment by MrStonedOne** [comment]
Also you don't make it clear where you are clicking, are you trying to pick the things back up? is it failing? what is showing when you hover over them in the status bar, does it show as being part of the borg?

**Comment by Lumipharon** [comment]
This isn't (only) with light fields.
I've had this bug happen to me like 4 rounds in a row the other day, and I have yet to even see a hardlight field. From memory it happened after being stunned, but I'm not sure if every time it happened it was from the same source.

**Comment by kriskog** [comment]
Not happening anymore.
