### ISSUE TITLE
can't shoot guns by clicking in blocked screen areas if there's a window in that area.

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#27486]
https://puu.sh/vWGdD/b9308ea275.gif
Notice how nothing happens when I'm clicking the tile with the window...

**Comment by ChangelingRain** [comment]
@AnturK

**Comment by Bawhoppen** [comment]
nothing new though?

**Comment by AnturK** [comment]
Oh right i forgot to add plane check.
