### ISSUE TITLE
The tiles that power terminals are on in maint are not immune to rad storms

### ISSUE THREAD

**Issue by obscolene** [tgstation/tgstation#27482]
https://gyazo.com/70f6f6e759291b71179c29607dbd6c40

**Comment by ShizCalev** [comment]
it's leaking through because of the wiring


that's cause for APC's in maint to work, you have to tag them as part of the room they're in, thus making that square not a shielded maintenance area.

**Comment by ShizCalev** [comment]
Thinking of a way to fix this; can you have a check to see if the square contains an APC, then if that returns true, check all squares adjacent to it to see if there are maint areas, and if 2 or more squares are maint then count it as shielded?

**Comment by Penguaro** [comment]
I think the better solution would be to make them have a variable for the area they power instead of the tile they're on. This has been proposed before.

**Comment by SgtxRootbeer** [comment]
Ya, but that would make them a pain in the ass to map in, and makes it hard to find...

**Comment by ShizCalev** [comment]
Would fucking love it tbh. Good thing I have pr already to fix all the area paths so we can use them without headaches.

Also how would it make them harder to find? You'd still name the apc and would want to place it in the general area, no? And setting the area they power would be on the same screen as setting the name lol


In the 7 years I've been playing, I can't believe this wasn't done already if it was possible. I'll set up all the apcs in a fukken heartbeat if someone does the code for it.

**Comment by Penguaro** [comment]
> if someone does the code for it.

That is the key point... While I'm happy to take that on, I'm still learning the ins and outs of DM as I go and this isn't really a topic I can devote a lot of time learning each week. So someday maybe...

**Comment by Penguaro** [comment]
@SgtxRootbeer Yes, it would involve an extra step when adding an APC. Initially it will be a little time consuming to manually convert all of them. It isn't hard to find stragglers though.

**Comment by MrStonedOne** [comment]
you make it optional, if the apc area var is null, use the real area. basically make it an override.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm pretty sure it actually already does this with the area_string var

**Comment by ShizCalev** [comment]
@ExcessiveUseOfCobblestone areastring doesn't seem to be working for me. 

What should you change the line to? I've tried `areastring = "/area/hallway/primary/central"`, `areastring = /area/hallway/primary/central`, and `areastring = "/hallway/primary/central"`

**Comment by ShizCalev** [comment]
....jesus fuck it pulls it by the area's name. what the hell is that shit.
