### ISSUE TITLE
Mobs other than carbon mobs feel fuzzyness around the SM

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#27499]
When a mob such as a revenant manifests itself in adjacency to the supermatter shard, the chatlog will be spammed with instances of "your skin feels fuzzy" even though the revenant is not a carbon entity or for that matter even has skin, it seems to be a oversight on not restricting this sensation.

> Radiation does not hurt revenants so it was fine for me to be in the SM's presence.

**Comment by spessbandit** [comment]
I don't think this message even exists in game anymore
