### ISSUE TITLE
I just got hard deleted out of nowhere.

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#27491]
No admins on, runtime logs were clear of anything suspicious (from my browsing anyways), 70703 round ID.
I'm security fighting a cult. I threw a flashbang and stunned a few cultists, and was dragging one out while stunning them with a baton.
I suddenly turned into a ghost, and I readminned to see if someone was fucking with me
>Nope

Welp, I check mob lists. 
>It's like I never existed!

What the fuck, yo.

Only thing I found that was linked to me in any way was https://puu.sh/vWLu5/3a0f8b2195.png
:joy: :joy: :joy: :joy: :joy:

**Comment by kevinz000** [comment]
https://github.com/tgstation/tgstation/pull/26990
This one caused it, QDEL_NULL blood target
I was the blood target, so was the other guy.
150 hours of testing boys.

**Comment by Bawhoppen** [comment]
road to 900 issues

**Comment by YakumoChen** [comment]
150 hours of testing

**Comment by kevinz000** [comment]
fixed

**Comment by Cyberboss** [comment]
Where??

**Comment by RemieRichards** [comment]
@Cyberboss it was the ```QDEL_NULL(GLOB.blood_target)``` VS. ```QDEL_NULL(GLOB.blood_target_image)```

**Comment by Cyberboss** [comment]
Yeah but which PR fixed it?

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/pull/27494
