### ISSUE TITLE
The Oxygen contamination problem. (Science/Toxins)

### ISSUE THREAD

**Issue by BorhilIan** [tgstation/tgstation#27505]
So under multiple configurations it seems trying to fill a plasma or empty canister always gives you a 0% oxygen containment that prevents bomb explosions. (During the bugged rounds, maps or updates) You can straight up fill the plasma for bombs directly from a plasma tank and get this bug. The inconsistency of this bug is really strange as well given it seems to only happen every other update or map. (I have experiend this bug randomly over the past month)

I really want this fixed so I can finally be a traitor and blow my target up...

> Server revision compiled on: 2017-05-20
> The following pull requests are currently test merged:
> #27409: 'Mesons no longer show turfs on lavaland, but miners no longer need mesons to see minerals scanned by a mineral scanner through walls' by ChangelingRain 
> 
> Based off master commit: da4fa2

**Comment by kevinz000** [comment]
@duncathan i've noticed it somewhat too. My maxcaps just.. didn't go off, the gasses were always the right temperature.

**Comment by Jalleo** [comment]
The maps likely do not matter if this is what I am thinking it is.

**Comment by Kromgar** [comment]
Gratian sloan told me he could never get his bomb mix to work on box

**Comment by Tacolizard** [comment]
I might be retarded but I've tried using the wiki's bomb guide mabye five times and never made a working bomb.

**Comment by BorhilIan** [comment]
Seems bombs work again though the oxygen contamination is still an issue. Here is a short gallery of me testing the air transfer and a tiny capacity bomb.

http://imgur.com/a/VXX7c

**Comment by BorhilIan** [comment]
Slight update, if you try to empty a air pump with the contaminant it will remain and be un-removable no matter how long you leave it running or at what pressure.

**Comment by duncathan** [comment]
Is this still an issue?

**Comment by as334** [comment]
@duncathan This is probably from the fire reaction asserting Oxygen(the 0% ghost plasma.) i've noticed it in assmos testing, it appears when your gas gets above a certain temp(cause that triggers fire).
