### ISSUE TITLE
can't grab anything with ctrl-click

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#27506]
presumably caused by https://github.com/tgstation/tgstation/pull/27492

**Comment by kevinz000** [comment]
That's why I closed it I didn't test it yet >:[

**Comment by AnturK** [comment]
That wasn't even correct variable...

**Comment by AnturK** [comment]
@optimumtact

**Comment by Robustin** [comment]
FIXITFIXITFIXIT

**Comment by optimumtact** [comment]
it is fixed
