### ISSUE TITLE
Morphs sometimes keep overlays when changing to default form

### ISSUE THREAD

**Issue by Alek2ander** [tgstation/tgstation#27511]
Revision ad649506e9b530329dd7059df4f2e9a793f1dfee
2017-05-21

http://qs.lc/2zu5w
http://qs.lc/q50x9
http://qs.lc/8fdhr

1. Be a morph
2. Change into an object that uses the overlay subsystem, such as an airlock, window, table, apc etc.
3. Change back into default morph form
4. You still have the overlays visible

#23922

**Comment by kevinz000** [comment]
maybe related to people getting inhands stuck.

**Comment by AnturK** [comment]
If our_overlays is not initialized cutting overlays skips the update. I'll fix this morph-side for now, but this is going to be an issue for anything that gains overlays outside the subsystem

**Comment by Cyberboss** [comment]
The problem is things using overlays outside the SS then

**Comment by AnturK** [comment]
Fix in #27513
