### ISSUE TITLE
icon smoothing broken on buildmode shuttle/full

### ISSUE THREAD

**Issue by silicons** [tgstation/tgstation#27522]
https://puu.sh/vXr1K/10107d8f27.png
reproduction steps:
enter buildmode
go to "G"/map generator
use shuttle/full
get ugly results
cry about your event getting ruined.

**Comment by WJohn** [comment]
@xxalpha

**Comment by xxalpha** [comment]
Don't blame me, any new problems are someone else's fault.

**Comment by dragomagol** [comment]
It looks like the shuttle/full was removed; the shuttle template smooths properly now though.
