### ISSUE TITLE
You cannot wet hairless hide, in order to dry hides on a rack.

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#27539]
Some kind of issue is breaking the production chain of leather, when i tried talking to this to @WJohn , over IRC even with the instructed steps they reported they were unable to complete what they were doing, as the drying rack refused the non-wet hide.

> WJohnston	Fantastic_Fwoosh: yes, i spawned a corgi hide
14:57	used a knife on it
14:57	turns it into a hairless hide
14:57	then i spawned a kitchen sink, and used the hide on that
14:57	it says it washed it
14:57	it was not wet
14:57	tried it again with a water puddle
14:57	same results

This issue is important because it effectively breaks the natural production chain for leather besides getting the stack object solely from the biogenerator.

**Comment by WJohn** [comment]
So to clarify: Only clothes washers work when wetting hairless hides, sinks do nothing. It should be possible to wet them with sinks, steam, fire extinguishers, and showers.

**Comment by Profakos** [comment]
I have investigated things, and apparently the only implemented way to create them is to.... machine wash it, which is silly and barebones indeed.

**Comment by FantasticFwoosh** [comment]
@WJohn it was never possible to wet them outside of sink type items & washing machines before, but as you say any additional contribution to wetting (be it any kind of interaction with water reagent) is welcome.
