### ISSUE TITLE
Bluespace Artillery Cannon is extremely buggy.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27538]
1. The BSA is invisible upon its construction being completed.
2. If the icon is put on, the computer will be nowhere near where it's supposed to be, the computer should be near the back, where all the cables are laying on the ground, not smack dab in the middle.
3. The computer is underneath the gun's cables, layering issue.
4. The gun's layer is beneath people, meaning that when they are standing on the top tiles they appear to be walking on the gun, instead of behind it. (3/4th perspective)
5. The gun can't even fire.

**Comment by Cyberboss** [comment]
Donlt overuse the 150 hours meme, the BSA is just old shitcode

**Comment by WJohn** [comment]
I figured it'd be okay to use it because it is hilariously non-functional.

**Comment by Kromgar** [comment]
Isn't the computer wherever you put it? IIRC you could plant the ocmputer anywhere. Either way yeah BSA and DNA vault are fucking shitcode.


THe machines dont except higher level parts whatsoever

**Comment by Shadowlight213** [comment]
@Wjohnston which bsa are you referring to? There's the station goal bsa, and the old structure dummy bsa.
The old bsa cannon itself doesn't do anything, it's all from the control console. The new one however is supposed to fire.

**Comment by WJohn** [comment]
I'm talking the station goal one, I don't know if the old one even exists.

**Comment by Kromgar** [comment]
![image](https://cloud.githubusercontent.com/assets/6778786/26502099/7c754d3c-4209-11e7-99cc-d6bd1c6189e8.png)

**Comment by Steelpoint** [comment]
I was the HoS who helped organise the cannon built in the image above.

The cannon is just broken right now, I've never seen it fully constructed and work properly in a game. The after round report will state the cannon is complete however.

At first I thought you had to clear all tile spaces around the cannon or it won't spawn, but even then the cannon failed to appear.

Should just remove it, its a waste of time.

**Comment by kevinz000** [comment]
you're a waste of time.
