### ISSUE TITLE
Crafting a satchel from leather produces a regular satchel instead of a leather one

### ISSUE THREAD

**Issue by Grazyn** [tgstation/tgstation#27547]
See title, I expected the fancy satchel but I got the regular one.

Server revision compiled on: 2017-05-22
The following pull requests are currently test merged:
#27409: 'Mesons no longer show turfs on lavaland, but miners no longer need mesons to see minerals scanned by a mineral scanner through walls' by ChangelingRain 
#27496: 'Necropolis Tendrils will produce an outer ring of lava when collapsing' by ChangelingRain 

Based off master commit: 7ed3c6

**Comment by WJohn** [comment]
Don't know if this is a bug or if someone just wasn't thinking.

**Comment by Grazyn** [comment]
It's called leather satchel in the crafting window so it's definitely a bub
