### ISSUE TITLE
Runtime is a magical redneck.

### ISSUE THREAD

**Issue by Owegno** [tgstation/tgstation#27550]
This is pretty simple, Runtime is able to reproduce with her own children and can even do it through windows.

Can be quickly reproduced by spawning Runtime a mate, deleting that mate after she has a child and then watching in horror as she reproduces with her own children.

**Comment by WJohn** [comment]
![](http://i.imgur.com/P1NTSkX.png)

Gibbed 62 kittens.

**Comment by Kromgar** [comment]
NUCLEAR CATSPLOSION IS BAAAAAAAAAAAAAAAAAAAAACK

**Comment by YakumoChen** [comment]
feature

**Comment by Kromgar** [comment]
Absolutely a feature. Coded in reference to dwarf fortress

**Comment by lzimann** [comment]
Not a feature.

**Comment by lordpidey** [comment]
Reproducing when the parents are separated by a window is CLEARLY unintentional.

**Comment by cerid** [comment]
It was originally left like this just because Pete didn't want to put more pathfinding calls in. Shouldn't be an issue if it's not called often.

**Comment by PraiseRatvar** [comment]
@Iamgoofball gfys

**Comment by Iamgoofball** [comment]
?????

**Comment by PraiseRatvar** [comment]
see #28396

you said you'll fix this issue in dorf pr (but you discontinued dorf pr so idk)

**Comment by Iamgoofball** [comment]
ah
