### ISSUE TITLE
gang turrets can change direction while firing

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#27560]
@Robustin 

>"can't change direction while firing so you're stuck and fucked if they dodge it"

>fight a turret, changes direction to fire at me after only a few rounds, no cooldown

>"low bullet damage means it won't blow people away either"

>die immediately despite wearing HoS armor because massive damage after just a few shots

150 hours of testing.

**Comment by YakumoChen** [comment]
I read the commit wrong, going to close this

**Comment by YakumoChen** [comment]
no wait, kevin told me it wasn't intended, so I'm still right

1 5 0 hours

**Comment by kevinz000** [comment]
woops i read it wrong too haha lmao
