### ISSUE TITLE
Can't Buy New Escape Ships 

### ISSUE THREAD

**Issue by Steelpoint** [tgstation/tgstation#27571]
The Communications Console does not show a list of ships to buy under any circumstances.

You can still get a admin to send a ship, but you can't buy one.

**Comment by jughu** [comment]
They are disabled you doofus

**Comment by Steelpoint** [comment]
For what purpose?

Ausops said it was a bug.

**Comment by jughu** [comment]
Because when you bought a shuttle shuttle never came then the backup came and try to have fun in a 9x9  5x5 room also most of the shuttles were broken like some parts not going trough transition aka a asteroid shuttle without its floor

**Comment by Steelpoint** [comment]
If the issue is with certain ships being broken then why not remove those ships?

**Comment by kevinz000** [comment]
because there's an underlying issue, it isn't the ships that need removing it's the issue that needs fixing, if something that's loaded in by something else breaks because that something else can't load it properly when that something is fine you fix the something else, not the something.

**Comment by Iamgoofball** [comment]
Yeah, something got fucked with the shuttle subsystem stuff after all the cyberboss refactors. Someone needs to take a look at it.

**Comment by lzimann** [comment]
The shuttles not appearing is not a bug, they are bugged right now, so I disabled them.
