### ISSUE TITLE
Manned turrets become more accurate the further the tile you aim at.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27577]
If you click on the tile immediately in front of you, you will have a 180 degree cone, and at the furthest away will be around a 10 degree cone.

Naturally this leads to huge friendly fire incidents, and IMMENSE balance differences when guns can be THAT accurate.

**Comment by kevinz000** [comment]
THIIIS ISSS NOOOOT HOOOOW PIXXXEEL PROOOJECTTIILLLES ARE DOONNEE REEEEEEEEEEEEEEEEEEEEEEEEEEEE!!!

**Comment by evsey9** [comment]
i was a person on centcomm before round end
there were 4 turrets
i fired one tile next to me
I END UP INJURING HALF THE FUCKING TEAM
