### ISSUE TITLE
Armor penetration does not work on objects.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27575]
Pretty much every object is destructible now, and also has armor stats. However, once you deal enough damage to get over the threshhold (usually 20), the damage will be reduced by the listed stats. On airlocks, that'd be 30% reduction for melee weapons.

If you were to hit an airlock with a 30 damage weapon like an esword (this is above the minimum threshhold), you would deal 21 damage (30% reduction due to the airlock's armor).

If the weapon has armor penetration, say 100 armor penetration? It still only deals 21 damage. I also tested this with a toolbox (edited values) and it still did not deal its full damage.

**Comment by RemieRichards** [comment]
armour pen pre-dates armoured objects.

**Comment by WJohn** [comment]
I wasn't sure if almighty phil had simply forgotten about armor penetration in his great object refactor, or if it's actually just non-functional.
