### ISSUE TITLE
Bows have multiple bugs and usability issues.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27581]
1. When firing a bow, a duplicate arrow will be spawned directly beneath you.
2. This arrow can be fired from the bow, but only once, afterwards the bow itself will be permanently broken and impossible to fire from using regular arrows, either.
3. Not sure if a bug or balance decision, but arrows do not embed even with a 45% embed chance. Shouldn't that be their selling feature? Who has ever heard of an arrow that does NOT embed??
4. Bow have extremely unwieldy loading mechanics. You need to hold an arrow in one hand, place it in the bow held in your other hand, swap TO that hand (and being careful not to grab the bow, as it will swap hands and DROP the arrow), use the bow to stretch it, THEN fire. This could all be simplified to a simple arrow -> bow is ready + swap hands.

**Comment by lzimann** [comment]
3. Arrows are projectile, and projectiles don't embed.

I think bows could just be removed/completly re-done. I don't think they have been used ever since I added them.
