### ISSUE TITLE
Station decals spawning on lavaland

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#27590]
![orbital suffix upsilon 2017-05-23 112121](https://cloud.githubusercontent.com/assets/8237862/26362501/21490a84-3fac-11e7-9432-9744bee02a54.png)
Not pictured:  Crusty dried vomit spawning on lava.

Server revison: 6d05b8
No testmerged PRs.

**Comment by Kromgar** [comment]
![image](https://cloud.githubusercontent.com/assets/6778786/26366019/7e428b24-3fb7-11e7-8290-63ba4263d37b.png)


Oh god joan this is hilarious

**Comment by AnturK** [comment]
The dirtystation code is horrible, needs refactor.

**Comment by Kromgar** [comment]
Why doesn't blood and vomit even dry ingame anyway?

**Comment by AnturK** [comment]
It's ancient and nobody added that.

**Comment by Kromgar** [comment]
![image](https://cloud.githubusercontent.com/assets/6778786/26366856/93db411c-3fba-11e7-9c81-a405ff9f44a7.png)


Oh my

**Comment by ChangelingRain** [comment]
How the fuck did the changes in #27476 cause this, why does adding a subtype for an area make it spawn decals this is really dumb

**Comment by ShizCalev** [comment]
@ChangelingRain The old areas had flags = NONE, which removes the CAN_BE_DIRTY flag that all areas inherit by default.
