### ISSUE TITLE
The nuke can be blown up by a maxcap, defusing it

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#27608]
there goes that greentext

**Comment by francinum** [comment]
leave it, literally the only way to redeem yourself in nuke is to commit jihad.

**Comment by Kromgar** [comment]
This happened once when someone set the station nuke to delta. It was incredible. 

So is the argument nukes should be 100% invincible or should when it is armed instantly detonate if someone bombs it

**Comment by BeeSting12** [comment]
No @francinum nuke ops are encouraged to leave once the nuke is set and this makes that impossible as one would have to stay to defend it. Defending it would also be impossible because voice triggers, deadman switches, and the scientist has to get within like three tiles and GG. 

@Kromgar 
Making it 100% invincible is probably the best solution. Making it detonate if someone bombs it would just cause ops to detonate a bomb two inches from it as the ship is leaving.

**Comment by BeeSting12** [comment]
Basically, as someone in deadchat said, there's no point to the mode if you can just maxcap the nuke and all your troubles are solved. Like literally leave the disk out, find the nuke when it goes delta, and you win and the ops have no chance of winning!
