### ISSUE TITLE
Rig suits that have their mask flipped open still protect you from diseases, even through drinking them.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27619]
If you have a syndicate hardsuit and switch it to armor mode, thereby exposing the face, and drink diseased blood, xenomicrobes, or nanites, you will not be infected.

**Comment by XDTM** [comment]
Nanites/xenomicrobes should force infect and ignore armor, do they not?

**Comment by WJohn** [comment]
Nope.

**Comment by Penguaro** [comment]
I fully believe this happened, I'm just curious what series of events transpired that revealed this...

**Comment by WJohn** [comment]
This has since been fixed.
