### ISSUE TITLE
gender-neutral to gendered term conversion in emote code is too agressive

### ISSUE THREAD

**Issue by SgtxRootbeer** [tgstation/tgstation#27613]
for example, i was trying to give my character some flavor when he was in tool storage picking up a toolbox and gloves by emoting
"george melons hums the 'Mission Impossible' theme to himself"
which came out as
"george melons hums the 'Mission Impossible' hime to himself"
by what i assume is the
them -> him code,
therefore
them+e -> him+e

**Comment by GunHog** [comment]
Was this done using the "me" custom emote?

**Comment by optimumtact** [comment]
I wasn't aware it did any conversion lmao

**Comment by SgtxRootbeer** [comment]
@gunhog yes, this was done using the me command

**Comment by GunHog** [comment]
It is the use of single quotes! '

**Comment by RemieRichards** [comment]
@GunHog why is it?

**Comment by GunHog** [comment]
Nevermind, it is unrelated.

**Comment by lzimann** [comment]
good code
