### ISSUE TITLE
DeltaStation supermatter setup doesn't allow using multiple gasses as coolant

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#27637]
you can basically make all freon vent out to space on accident or some other coolant because some retarded map designer thought that making a filter that would filter only ONE gas into the supermatter chamber would be a good idea
MAKE IT WORK LIKE THE OTHER STATIONS GOD DAMNIT THIS SETUP JUST SCREAMS "SABOTAGE ME"

**Comment by ShizCalev** [comment]
There's a filter right after the gas leaves the chamber that you can set to filter freon, that way it doesn't vent.

Regardless, I was going to redo its loop and standardize the SM setups all in a day or two anyway.
