### ISSUE TITLE
Nuke op base has blood and filth all over in the snow, even though though it should start clean.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27644]
It's possible to set some areas as dirty at round start (grime on the station in general, puke in the bar, blood and guts in medbay). Some areas have more or less grime than others, but sometimes it's not supposed to be filthy at all.

![](http://i.imgur.com/nObtAgv.png)

Round ID 70882 2017-05-25

Pretty sure the entirety of the nuke ops' base, snow and all, should not be covered in blood and guts as far as the eye can see.

**Comment by MMMiracles** [comment]
dirtystation seems to hate changing/adding areas in general and acts up by throwing old blood and vomit in areas it probably shouldn't be

**Comment by Niknakflak** [comment]
Remnants of Nanotrasen crew's attempt to breach the base

**Comment by Kromgar** [comment]
@ChangelingRain YOU  BROKE EVERYTHING

**Comment by ChangelingRain** [comment]
this is not my fault

**Comment by Kromgar** [comment]
@ChangelingRain happened after you changed subtypes on lavaland so therefore i blame you

**Comment by WJohn** [comment]
Also saw this happening on the thunderdome, but seems inconsistent on whether or not blood and filth spawns in these areas on a per-round basis.
