### ISSUE TITLE
Mining inhands are sticking on the sprite

### ISSUE THREAD

**Issue by 4dplanner** [tgstation/tgstation#27640]
![1](https://cloud.githubusercontent.com/assets/26886304/26423657/5f920348-40c6-11e7-8cbc-a7eb00df67fb.png)
This has happened once before, but basically sprites stick on hands after you switch hands or drop them, leaving you with a bunch of (admittedly cool looking) junk

**Comment by Kromgar** [comment]
I think this is a dupe. I reported it involving the uh spectral sword did you pick one up earlier?

**Comment by 4dplanner** [comment]
Yes, yes I did
