### ISSUE TITLE
Pipe mixer/filter directions and flipping are super retarded and also broken.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27650]
While it is possible to normally rotate these, flipping them causes all kinds of problems. They allegedly require a "flipped" variable, even though these still use the same set of icons, just different directions (5,6,9,10 instead of 1,2,4,8).

While it is possible to achieve these in game, the map maker will not accept "flipped" or these extra directions, and will instead revert to the standard 1,2,4,8, making a lot of piping configurations impossible for mappers. I suspect a lot of our map's atmospherics designs are being hampered by this quite badly, as they are forced to conform to the specific output directions these provide.

**Comment by ShizCalev** [comment]
They have a different path with different icons for flipped states

/obj/machinery/atmospherics/components/trinary/filter/flipped
/obj/machinery/atmospherics/components/trinary/mixer/flipped

**Comment by WJohn** [comment]
wait what that's a thing holy shit i'm dumb--
