### ISSUE TITLE
Growth Serum applies the visual effect nonsensically

### ISSUE THREAD

**Issue by dannno** [tgstation/tgstation#27683]
![](http://i.imgur.com/SzsOlmP.png)

The feet of the mob should end at the bottom of the tile the actual hitbox is on.
It shouldn't expand outwards from the center of the mob like this.

**Comment by ChangelingRain** [comment]
also you can clearly see it's using the wrong transform style, ie, not using PIXEL_SCALE for some reason

**Comment by dannno** [comment]
Also I forgot to mention, after that round had ended the person affected by growth serum suddenly stopped looking blurry and interpolated and their sprite was just properly enlarged
I don't know what did it but it looked much nicer tbh

**Comment by ChangelingRain** [comment]
yeah it fixed itself somehow after I adminhealed the guy and added more growth serum

**Comment by TheBonded** [comment]
this seems to just be a feature of growth serum, its been nearly 5 years, does anyone have any opposition for me cleanup flagging this?
