### ISSUE TITLE
Random roundstart decal creation happening everywhere

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#27682]
Supposed to only be on the station 
![ss 2017-05-25 at 06 52 14](https://cloud.githubusercontent.com/assets/6510293/26475151/5d90eb62-417b-11e7-81c5-ef4116060d41.png)

**Comment by lzimann** [comment]
Probably a side effect of the area rewrite.

**Comment by PKPenguin321** [comment]
Dupe

**Comment by Cyberboss** [comment]
like 3x dupe

**Comment by Repukan** [comment]
Dupe

**Comment by Kromgar** [comment]
This is all joans fault
