### ISSUE TITLE
Stetchkin APS does not fit in military belt or pockets

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#27703]
This may not be an issue but it's still a small balance thing. The nuke ops' stetchkin APS, which is found in the flame thrower kit for 30 TCs, cannot fit in a military belt or pockets which means they have to hold in their hands- with the flamethrower backpack they can't hold anything in it.

**Comment by QualityVan** [comment]
It fits in suit storage. I don't op much though so I don't know if that slot is particularly contested.

**Comment by BeeSting12** [comment]
It's contested by the oxygen tank that usually is sitting there.

**Comment by lordpidey** [comment]
@Cyberboss this seems intentional, it specifically sets it's size to medium.
