### ISSUE TITLE
Deconversion should be more doable.

### ISSUE THREAD

**Issue by Repukan** [tgstation/tgstation#27702]
I might be out of place posting this here, but it affects the game due to how deconversion was coded to work, and thus I hope this can get coderbus into reaching a consensus.

Deconversion is currently a privilege that is absent if there's a lack of chaplain or implants. While sometimes the lack of chaplain can be due to player problems, I think it would be healthy for the game to have one guaranteed, but not outright unbalanced, way to deconvert.

If this is the wrong place to post this just I'll fuck off but I feel this affects the server overall to be treated as an issue.

**Comment by Cyberboss** [comment]
It's not a bug in the code, post it on the forums

**Comment by QualityVan** [comment]
Cargo can order holy water to provide a supply if there's no chaplain, botany can grow holy melons.

**Comment by SgtxRootbeer** [comment]
There is a single 100u via round-start in the chaplain's closet.

**Comment by lzimann** [comment]
Forums, not issue tracker
