### ISSUE TITLE
Lava baseturf burning through ruins at roundstart

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#27719]
There appears to be a chance at roundstart that lava baseturf will destroy random squares of turf and items above it from ruins on the lavaplanet.

Think it might also be an extension/cause of #26674 , where piping underneath indestructible floor on the clownplanet ruin is getting deleted randomly.

**Comment by MrStonedOne** [comment]
@KorPhaeron @coiax @Cyberboss

**Comment by ShizCalev** [comment]
Another roundstart terrain gen issue; #22289

**Comment by ShizCalev** [comment]
Noticed that it seems to happen when the terrain system puts corridors down nearby/intersecting ruins. Perhaps it's trying to generate a corridor inside populated squares and just ends up deleting the turf or something?

**Comment by Iamgoofball** [comment]
I've noticed it'll do shit like generate through ruins before, this occurs a shitton with the dwarf ruin.

**Comment by WJohn** [comment]
![image](https://user-images.githubusercontent.com/5988156/34783929-da57eed2-f5fa-11e7-8b3b-fb9eb79157e0.png)

Yup this is still around.

**Comment by KorPhaeron** [comment]
This is the game attempting to make lava rivers
