### ISSUE TITLE
A Kinetic Accelerator with Bayonet and Seclite cannot be picked up normally / requires use of the laggy left-click menu to pick up

### ISSUE THREAD

**Issue by Tsuchigumo550** [tgstation/tgstation#27729]
Unfortunately, I was not able to get the specific revision, the command returns "revision unknown". Thankfully, I was at least able to strip the following from motd:

The following pull requests are currently test merged:
#27720: 'Fixes pre-round-start logs' by MrStonedOne 
#27721: 'Fix roundid' by MrStonedOne 
#27551: 'Pixel projectile ricochets and reflections!' by kevinz000 

I do not believe this is the result of a testmerge, but all info is good info.

I suspect that KAs in general, and possibly goliath tendrils causing stun+item drop, have some broken elements that will only get worse as they are added onto. As a result of dropping a KA due to a goliath tendril attack, I dropped my KA (with seclite + bayonet), and was unable to pick it back up off the ground normally. I was able to pick it up using left-click, implying that it simply wasn't being "highlighted" like most items are when you mouse over them. For the record, a goliath corpse was on top of the KA. I can absolutely confirm that I was not simply "missing" the KA, as I tried many, many times to pick it up, it simply wasn't being "highlighted".

Somewhat unrelatedly, I find that goliath tendril attacks can sometimes cause "phantom" in-hand item sprites that won't go away, although I cannot replicate this regularly and it's not specifically KAs, I've had a spectral blade do it as well. As-is, I don't have enough material on this phenomenon to report it as its own bug so I'm dumping it here.

**Comment by lzimann** [comment]
@kevinz000

**Comment by kevinz000** [comment]
hm

**Comment by kevinz000** [comment]
@lzimann not caused by stuns or my code, probably tendrils

**Comment by kriskog** [comment]
Doesnt seem to be happening anymore
