### ISSUE TITLE
proslytized airlocks have no atmo in their tile.

### ISSUE THREAD

**Issue by SgtxRootbeer** [tgstation/tgstation#27734]
if an airlock gets proslytized to the clockcult variant, all the atmo on that turf gets deleted, causing space wind, and minor oxyloss damage initially. its annoying, and shouldn't be happening.
this happens regardless of how the airlock was proslytized, ratvar, scarab with a proslytizer, etc.
i dont know if airlocks made with brass to be ratvarian are like this, nor do i know if you can even make ratvarian airlocks in any other way than proslytizing.

**Comment by ChangelingRain** [comment]
this happens when the turf under a closed airlock is changed, and is not specific to proselytized airlocks.

**Comment by ChangelingRain** [comment]
@duncathan please fix this awful bug finally

**Comment by duncathan** [comment]
this probably can't be toooo hard to fix, i'll see what i can do tonight

**Comment by Cyberboss** [comment]
>4 days ago

**Comment by duncathan** [comment]
well that only took 137 days. long night
