### ISSUE TITLE
command bar capturing input from file selection

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#27755]
Probably a byond bug but
1. Any admin command that requires selecting files with the popup, in this case, varediting icon to a file
2. Type in the file name box, so I can autocorrect to the file
3. What? My characters aren't appearing?
4. Wait, why are in they in the command bar?!!
![sigh](https://puu.sh/w2yhZ/4d98fde922.gif)

**Comment by Cyberboss** [comment]
100% a byond bug

**Comment by Jordie0608** [comment]
Indeed http://www.byond.com/forum/?post=2021735
