### ISSUE TITLE
Glass airlock sprites fail to load.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27752]
![](http://i.imgur.com/kC0eDIc.png)

![](http://i.imgur.com/AyCK6m6.png)

If you CREATE the airlock with glass, the glass sprite won't show up.

Likely related to #27753

**Comment by ShizCalev** [comment]
Noticed this happening at roundstart an hour or so ago. Opened the airlock and the sprite updated.

**Comment by xxalpha** [comment]
But did it ever work?

**Comment by DaxDupont** [comment]
@xxalpha yes they did work fine, it's something new

**Comment by WJohn** [comment]
Uh, this is long since fixed.
