### ISSUE TITLE
Using Envy's knife on a wizard does not give you their Wizard Name.

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#27751]
Today during a wizard round as miner, I thought I'd try something tricky, so I stabbed the wizard with Envy's knife. Rather than changing my name to "Geraldo The Sorcerer Supreme", it was changed to "Jebediah D. Wheat" which I assume is apparently their name according to dna.real_name, since that's what Envy's knife goes by. Additionally, stabbing a wizard with Envy's knife does not allow you to use their spellbook. This is probably intentional, but I'll mention it just in case.

**Comment by Armhulen** [comment]
just change it to real name
