### ISSUE TITLE
Edge case: Headslugging a body that a blob zombie takes over causes problems

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#27757]
13:09:43: redacted/(headslug): my body broke as if it was blob zombie but i was human with no lungs it was bugged 
13:10:40: Reply PM from-redacted/(headslug): i was human ling inside a npc blob zombie 
13:11:00: Reply PM from-redacted/(headslug): no i headslugged a body then the blob took it over 

Not so much of an edge case considering xenobio is where this is likely to happen

**Comment by ShizCalev** [comment]
Closing in favor of #31258 as it explains a bit more.
