### ISSUE TITLE
Cap's spare ID spawn (Delta Station) has no access (roundstart no-captain)

### ISSUE THREAD

**Issue by Roboman100** [tgstation/tgstation#27772]
Captain's spare ID didn't have access on it. This occurred when the round had just started and there was no captain on-board the station yet on Delta Station. (Round ID 71029)

_got me brigged reeeee_

**Comment by Repukan** [comment]
How can anyone say cere is not good when it retroactively catches greytiders.

**Comment by Armhulen** [comment]
boxstation doesn't have it etiher, i'm assuming it's not a problem with the map

**Comment by PKPenguin321** [comment]
Fixed, failed to auto close

**Comment by Cyberboss** [comment]
@lzimann
