### ISSUE TITLE
APC sprites are EXTREMELY slow to update.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27785]
When an APC goes from not charging to charging or whatever other automated sprites there are like this, it can take around **15 seconds** for the sprite to show, even though in the APC UI the delay is closer to 2 seconds, fast enough to not notice when messing with SMES cells and checking frequently on the APC.

This can confuse people long enough for them to start cutting and rewiring things trying to fix it, even though it was actually working fine, but just hadn't updated the sprite fast enough.

**Comment by AnturK** [comment]
That was ancient artificial delay added to limit updates when the network was fluctuating and the icons were rebuilt every time, probably can be removed now.
