### ISSUE TITLE
Admiral recall doesn't actually do anything

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#27787]
It gives an admin message that the admin sent the recall, but the recall is never actually triggered
@coiax

**Comment by Profakos** [comment]
https://github.com/tgstation/tgstation/pull/27450/files#diff-2aec593799a15c879d8f95f7276b689aL1439 Looks like this line was lost when the trigger proc was moved to a different file?

**Comment by Cyberboss** [comment]
@coiax
