### ISSUE TITLE
Can't use Comms console on DeltaStation

### ISSUE THREAD

**Issue by ClosingBracket** [tgstation/tgstation#27780]
As HoP, I was unable to log into the comms console on Delta. 

Occurred on round 71034.
![rimward_depot_nineteen_2017-05-27_23-19-55](https://cloud.githubusercontent.com/assets/9065180/26526172/d3dd294a-4336-11e7-932c-be67b4e358a1.png)

**Comment by Armhulen** [comment]
probably related to centcom z1 pr

**Comment by Bawhoppen** [comment]
road to 900 issues

**Comment by Cyberboss** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
I already fixed this
