### ISSUE TITLE
Some "can't put in container" messages have disappeared

### ISSUE THREAD

**Issue by octareenroon91** [tgstation/tgstation#27795]
Attempting to stow an item into a container when the container is overfull may obtain no message.
Likewise for non-allowed types.

It's likely the codepaths that emit the failure message have been broken (runtimes) or pruned (impossible logic cases).

**Comment by QualityVan** [comment]
Examples?

**Comment by octareenroon91** [comment]
Try to put an eighth item into a mechanical toolbox.

**Comment by AnturK** [comment]
https://github.com/tgstation/tgstation/pull/26445
@XDTM

**Comment by octareenroon91** [comment]
Got a fix but I'm on my phone.
