### ISSUE TITLE
Infinity gun (badmin gang machine gun) doesn't work.

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#27807]
It doesn't shoot bullets!

**Comment by KorPhaeron** [comment]
150 hours

**Comment by Armhulen** [comment]
Correction: It shoots bullets, but it shoots it out of your cursor not out of the gun

**Comment by factoryman942** [comment]
that sounds hilarious with thermals

**Comment by KorPhaeron** [comment]
@kevinz000 You fixed this right
