### ISSUE TITLE
You heat the footprints with the advanced plasma cutter!

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#27803]
![image](https://cloud.githubusercontent.com/assets/6778786/26530355/892f06a0-43a1-11e7-80c0-35c8b62e1f8f.png)

**Comment by GunHog** [comment]
Can you do that with a welding tool as well? Heating things with a plasma cutter works because they work as a welding tool for certain things like lighting cigars, cutting walls, etc.

**Comment by Kromgar** [comment]
Kinda weird you can heatup footprints though

**Comment by PKPenguin321** [comment]
Well they're a reagent container

Doesn't seem like a bug to me

**Comment by ShizCalev** [comment]
Make heating up turn them into dried blood
