### ISSUE TITLE
Gold slime reaction to_chat and flashes working through walls

### ISSUE THREAD

**Issue by octareenroon91** [tgstation/tgstation#27815]
Wearing mesons, and in maint, I saw the flash and chat notifications associated with a gold slime reaction that happened somewhere else. I'm pretty sure it happened in Metastation's experimentation room, since the mesons let me see its turfs.

**Comment by lzimann** [comment]
Can't reproduce this. No flash or message when the reaction happened.

**Comment by SpaceManiac** [comment]
Closing as unreproduced
