### ISSUE TITLE
you can hop on the mounted turret, hop of and run at your enemies as you spit out bullets

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#27816]
LOCUST ATTACK!

**Comment by kevinz000** [comment]
150 hours

**Comment by Lumipharon** [comment]
Didn't we have this issue back when whatshisface first tried to add long bust fire to the SAW?

**Comment by Robustin** [comment]
This was literally due to @kevinz000 change to the turrets firing system (either pixel projectiles or the autoaim). I believe he fixed it but that doesn't change him being an insufferable twat who broke the gun a few times and tried to foist it on me.

**Comment by vuonojenmustaturska** [comment]
@KorPhaeron
