### ISSUE TITLE
Return to lobby after crash

### ISSUE THREAD

**Issue by CapiDuffman** [tgstation/tgstation#27811]
In a cultist round, as their target, was sacrificed, sharded, became an artificer and finally got killed, in that very moment the client crashed.
On restarting the client, instead of being sent to the game, I was returned to the lobby, where I was offered to join and observe, as usual, I was able to join with the character that got killed before.
I ended the round dead, the sacrifice target remained completed.

**Comment by PKPenguin321** [comment]
Might be a dupe

**Comment by Repukan** [comment]
Dupe of #27647

**Comment by CapiDuffman** [comment]
closing up then
