### ISSUE TITLE
mexican lizard janitors ridin dirty

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#27828]
![ss 2017-05-28 at 11 55 02](https://cloud.githubusercontent.com/assets/6510293/26537418/0050d05c-4405-11e7-841e-b4229593c3bc.png)

**Comment by octareenroon91** [comment]
Now that you mention it, I saw a golem on a janicart that looked just a little offset. Less than that.

**Comment by KorPhaeron** [comment]
https://github.com/tgstation/tgstation/pull/27265

@Militaires
