### ISSUE TITLE
All ruins missing light bulbs

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#27829]
Means podpeople die before glowshrooms.

@ma44 You're the last to touch the map.

**Comment by Repukan** [comment]
Feature

**Comment by AnturK** [comment]
Oh nevermind it's just all ruins not having lights. I assume whoever mapped them assumed they'd be always lit

**Comment by WJohn** [comment]
Yep, most ruins were designed with no dynamic lighting in mind, and would always be fullbright. They also lack any atmos piping, wiring, or anything like that, making them pretty dull and uninteresting.

**Comment by FantasticFwoosh** [comment]
No lighting in the podpeople ruin makes them completely uninhabitable for plants & podpeople since it will deal brute damage until you die. Base glowshrooms (unless you are lucky and roll glowberry) also do not give off enough light to make you survive.

Upgrade this issue bug to critical please.

**Comment by Repukan** [comment]
Just add a couple of flashlights and they'll be fine.
