### ISSUE TITLE
Cats drop finished leather when butchered instead of hide

### ISSUE THREAD

**Issue by Grazyn** [tgstation/tgstation#27834]
I understand Goof did this to help dwarves but this is sloppy, every other mob drops hide which must be skinned first, wet and dried before it becomes leather. Dwarves can do this with any sharp item, the pool and the drying rack.

Revision unknown, #27761 is testmerged

**Comment by Iamgoofball** [comment]
fair point

**Comment by octareenroon91** [comment]
I lost track, but make sure that the leather process uses washing in sinks or water exposure. Last I checked the only tool for that step was the _washing machine_.

**Comment by Grazyn** [comment]
It was fixed, you can now use a sink or drop water on it

**Comment by AnturK** [comment]
Report on the PR
