### ISSUE TITLE
dwarves can be catpeople

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#27836]
![nyatansmug](https://cloud.githubusercontent.com/assets/10399117/26543934/d9ed95a2-442d-11e7-8d64-132c43dde897.png)
![xh4ksffy1rq91ajo1_500](https://cloud.githubusercontent.com/assets/10399117/26543936/dce1fdde-442d-11e7-8fca-d68d0fb4c8aa.png)

**Comment by Haevacht** [comment]
slippery slope next we'll allow elf lizards

**Comment by SgtxRootbeer** [comment]
@Iamgoofball 
is it that time again already?

**Comment by kevinz000** [comment]
OH GOD YES AHAHAHAHAHAH

**Comment by XDTM** [comment]
Feature

**Comment by RemieRichards** [comment]
Oh so that's what I saw.
If it is indeed what I saw, then sprites actually fit, maybe leave it up to the dorfs whether they want to outcast catdorfs or not.

**Comment by lzimann** [comment]
PR wasn't even merged yet. Post this in the actual PR/forums/talk with goof.

**Comment by Iamgoofball** [comment]
This is a bug yeah
