### ISSUE TITLE
A multitude of gang apparel lacks sprites of any kind.

### ISSUE THREAD

**Issue by KingPhilipIII** [tgstation/tgstation#27841]
As stated in the title.

**Comment by WJohn** [comment]
All weapons should have inhands, the boots aren't such a big deal though.

**Comment by KingPhilipIII** [comment]
They aren't weapons, and I'm jsut a moron. They lack sprites completely. On your person, in hand, anything.

**Comment by WJohn** [comment]
Oh, that's definitely a bug then.

**Comment by bgobandit** [comment]
it's just robustin's brilliant new plan for gang

**Comment by WJohn** [comment]
Might honestly be caused by goof's PR, too, seeing as it likely adds a few new inhands and weapons. I wouldn't be surprised.

**Comment by KingPhilipIII** [comment]
Right. This was corrected some time ago. So.
