### ISSUE TITLE
You can make reagent swords

### ISSUE THREAD

**Issue by Repukan** [tgstation/tgstation#27859]
Dorf testmerge

They're not even the adequate level to learn imbue weapon c'mon

**Comment by Jordie0608** [comment]
Comment issues with testmerges on the PR (#27761).

**Comment by Iamgoofball** [comment]
This is quite literally working as intended

**Comment by Repukan** [comment]
Stop being obtuse and fix it.

People being to spacewalk with synthflesh swords is not balanced whatsoever.

**Comment by Iamgoofball** [comment]
Too bad. I'll just make it so you can't craft it station side.

**Comment by Repukan** [comment]
Why not make it so broadswords can only be crafted from metals, but have a specialized weapon (imbued/assassin dagger) that can be crafted from reagents?

**Comment by Iamgoofball** [comment]
No.

**Comment by Repukan** [comment]
Reeeeeeeeeeeeeeeee

**Comment by PKPenguin321** [comment]
Reagent swords are neat
