### ISSUE TITLE
Delta station SM air filter is bugged

### ISSUE THREAD

**Issue by PaznerIV** [tgstation/tgstation#27853]
The air filter on Delta station SM stop sending the filter gas back into the loop if you change it from the normal O2 to any other gas.

**Comment by ShizCalev** [comment]
Working fine ingame for me.

Checked map wise, looks fine. Might've just been an initialization bug or something. If it happens again, just disconnect and reconnect it.

**Comment by Dorsisdwarf** [comment]
if this isnt reproduced in a week imma close this

**Comment by ShizCalev** [comment]
Week later, no repo?

**Comment by Cyberboss** [comment]
I'm going to assume this was fixed by #28380 @shizcalev

**Comment by ShizCalev** [comment]
It was likely the init issue with filters where they (very rarely) randomly don't work at roundstart until reconnected.

**Comment by ShizCalev** [comment]
@Cyberboss It was very likely the issue where filters don't work properly at roundstart until they are reconnected. I've seen it happen once in a blue moon (like once a month at most.)

**Comment by Cyberboss** [comment]
It's a dupe of that issue then

**Comment by ShizCalev** [comment]
What's the actual issue? Haven't seen that one before
