### ISSUE TITLE
[Dorf Testmerge] Metal being created but not initialized

### ISSUE THREAD

**Issue by Neuroplasty** [tgstation/tgstation#27854]
Commit hash and server revision are saying "Unknown" under the show server revision listing, but I've been coming across metal the other dorfs have made and left on the ground that I cannot interact with, Kev told me it wasnt initialized and to post an issue report here.

**Comment by Jordie0608** [comment]
Tell Kev to direct people to comment on the PR #27854 and not to open issues for testmerges.
