### ISSUE TITLE
Losing martial arts abilities (Sleeping Carp) after being cloned doesn't also remove the inability to use ranged weapons.

### ISSUE THREAD

**Issue by Daundra** [tgstation/tgstation#27850]
Revision unknown but current version of sybil server at the time of posting.

Purchasing the 17 TC Martial Arts scroll and then losing it through cloning will correctly remove the abilities but will not correctly remove the inability to use ranged weapons.

To reproduce, just get cloned after using a martial arts scroll then try using a ranged weapon.

**Comment by WJohn** [comment]
Yep. Cloning, deleting yourself and making a new body via admin, doesn't matter. It carries on.

**Comment by calzilla1** [comment]
Wasn't there a pr to allow retaining sleeping carp after Cloning?

**Comment by XDTM** [comment]
It should stay beyond cloning now, the abilities not carrying over is the bug
