### ISSUE TITLE
spelling mistake in codespeak uplink description

### ISSUE THREAD

**Issue by meeeeme** [tgstation/tgstation#27875]
/datum/uplink_item/device_tools/codespeak_manual
	name = "Codespeak Manual"
desc = "Syndicate agents can be trained to use a series of codewords to  **_comvey_** complex information, which sounds like random concepts and drinks to anyone listening. This manual teaches you this Codespeak. You can also hit someone else with the manual in order to teach them. One use."

pretty sure it's "convey".

**Comment by Armhulen** [comment]
Coderspeak
