### ISSUE TITLE
Salglu change nerfed gubbucks

### ISSUE THREAD

**Issue by octareenroon91** [tgstation/tgstation#27889]
Gubbucks produced salglu and dairy, which offered slow overall healing.

With the recent change to how saline-glucose solution works, its healing effect may have been decreased by a significant fraction.

**Comment by QualityVan** [comment]
wat
The healing from saline-glucose wasn't changed, only the blood regeneration.

**Comment by octareenroon91** [comment]
oh, pardon me. I didn't feel like codediving at that moment, and a lizard brought it up.
