### ISSUE TITLE
Hacked cleanbot foam doesn't actually clean

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#27895]
Makes no sense

**Comment by YakumoChen** [comment]
isn't it just lube foam like the AI slip foam is?

**Comment by GunHog** [comment]
When I coded it, I was reluctant to spawn and prime cleaning grenades or copypaste from it. It is not a true bug, but I would not mind giving this another look.

**Comment by SgtxRootbeer** [comment]
Use the ez-clean grenades for the janitor whynot

**Comment by Repukan** [comment]
@Cyberboss  not a "true bug," can be closed.
