### ISSUE TITLE
Power outage event STILL MAKES THE SM DELAMINATE

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#27902]
This issue persists on MetaStation, that fix PR didn't fix shit.
( round id 71195 if needed )
Basically, the power outage event requires IMMEDIATE attention to SM.
If you don't instantly go there, turn the APC on and everything else? It will DELAMINATE.
Hell, it's hard enough just to do that! The SM begins spawning electricity arcs less than a minute after the power outage, knocking down people.

**Comment by WJohn** [comment]
Perhaps have the engine room's APC always turned on? #27901 shows that APCs that are manually ON will not suffer at all from power outages.

**Comment by evsey9** [comment]
That CAN work, but please, fix this bug, as it can be a round killer easily.
Not all engis know this.

**Comment by WJohn** [comment]
Oh of course, I'm just saying that currently this is the way to prevent it if you are playing engineer/AI.

**Comment by evsey9** [comment]
happened again on deltastation, pumps didnt turn off but the filter did. :/

**Comment by Penguaro** [comment]
Testing my fix now, will upload the PR in about 5-10 minutes.
