### ISSUE TITLE
Power failure event doesn't do anything if APC settings were set to always ON.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27901]
![](http://i.imgur.com/pZXWALo.png)

The left is manually on, and everything in that rooms works fine, the right is auto, and turns off forcibly. Because this event happens literally once per round, it is possible to negate the problem as an AI and just turn it all on and never suffer from it.

**Comment by Xhuis** [comment]
Using the Grid Check event, I can't reproduce this. The APC still shuts off like normal, even when everything is manually on.

**Comment by SpaceManiac** [comment]
@Cyberboss Cannot reproduce.
