### ISSUE TITLE
adamantine is worth more than most miners will make in their lifetimes

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#27918]
>me and other miners find a few veins of adamantine on lavaland

>23k points
>50k points
>30k points

were the numbers each of us had

**Comment by Repukan** [comment]
Yeah it's crazy.

**Comment by Kromgar** [comment]
Its 5k a piece maybe it should be 1k a piece?

**Comment by WJohn** [comment]
it's goofball he doesn't give a shit about balance

**Comment by factoryman942** [comment]
if i'm reading this correctly
adamantine has same spawn weight as diamond
diamond is 50pts
adamantine is 5000pts
so for the same rarity addy is 100x points

**Comment by Kromgar** [comment]
I thought it was supposed to be rarer than diamodn lol what

**Comment by Repukan** [comment]
We can finally afford space timbs. Don't take this away from me

**Comment by Kromgar** [comment]
Tbh i think adamantien should stay 1k and we need to give it an actual use on station.

**Comment by PraiseRatvar** [comment]
make it the same cost of diamonds for now until it gains an actual use

**Comment by Iamgoofball** [comment]
No.

@KorPhaeron mind closing this

**Comment by dannno** [comment]
goof it seems to me that there is an evident problem here concerning the balance of this material

**Comment by Iamgoofball** [comment]
It's actually not supposed to be in the ORM at all.

**Comment by ChangelingRain** [comment]
@Iamgoofball you really need to learn how to comply. Fix your shit or you will stop having a pr.

**Comment by Repukan** [comment]
It doesn't appear in the ORM but it will be accepted and will give out points. It just can't be printed out

**Comment by Iamgoofball** [comment]
Here let me translate it so you can read it joan because you apparently can't read English 

Vg'f npghnyyl abg fhccbfrq gb or va gur BEZ ng nyy.

**Comment by Repukan** [comment]
Wew

**Comment by Iamgoofball** [comment]
And to clarify this isn't supposed to be usable in the ORM at all, you need dwarves to process adamantine

**Comment by YakumoChen** [comment]
> goof balances cargo before immediately breaking the shit out of it again

"Feature" -goof

Wew

**Comment by Iamgoofball** [comment]
I forgot weebs can't read

**Comment by Iamgoofball** [comment]
Here I translated it into weeb for you

それは実際にはORMにあるはずがありません。

**Comment by YakumoChen** [comment]
Please make reagent  swords inject too and allow alloys too please goof I want to make full traitor chem box swords that kills people in one hit to further abuse your shitty meme

**Comment by Iamgoofball** [comment]
no problem bby

**Comment by VeryRealAccount** [comment]
>goof continues to ignore legitimate criticism

Why is this guy even part of the coderbase?

**Comment by FantasticFwoosh** [comment]
Obvious solution is to refactor the ORM under the new smelter designs so that only the base ORM smelting functions are availible and not have the ORM suck up minerals that aren't whitelisted. #27224

**Comment by factoryman942** [comment]
goof
putting adamantine ore in the orm
causes it to eat the ore, destroying it
but gives out the bajillion points

**Comment by PKPenguin321** [comment]
All this aside, this issue should be closed as the feature is not yet fully merged.

**Comment by Repukan** [comment]
@Iamgoofball shouldn't this be closed since you patched it out?

**Comment by Iamgoofball** [comment]
Yeah

**Comment by nicbn** [comment]
I summon @Cyberboss the closer of posts.

**Comment by vuonojenmustaturska** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
Dwarves are gone
