### ISSUE TITLE
Freeze traps cause the thing you're holding to stay in your hand on the sprite

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#27915]
When frozen, you drop what you're holding. (by a freeze trap at least) This doesn't seem to show on the sprite so it'll look like you're holding a sword but you're really not.

**Comment by WJohn** [comment]
This is not freeze traps causing it. It happens seemingly at random, with any object. I don't know how or why, and its probably a byond issue thats been going on for the past month at least.

Detailed in #26968
