### ISSUE TITLE
Flash RNG burnout mechanic can screw revs over.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27919]
In a lowpop rev round, if there is only one headrev and his flash burns out first try due to RNG? He will be unable to get off the ground and the mode will end almost immediately.

We really ought to just get rid of RNG flashes burning out, and make set mechanics on how they work (maybe some sort of cooldown, like how you can use welders without protection more than 3 times, as long as you wait long enough).

**Comment by WJohn** [comment]
To add to this: flashes that BURNT OUT on use DO NOT convert! This means a first try fail will prevent you from getting even a single rev.

**Comment by bgobandit** [comment]
just steal a flash like a man

**Comment by MMMiracles** [comment]
@bgobandit did you read his follow-up comment? Roundstart flashing is practically a dead give-away, and if your flash fucks over on the first use and leaves you without a way to convert and now an angry crewmember that you just tried to flash, rev is going to have a much more rocky start for something not even their fault in the slightest.

**Comment by lzimann** [comment]
Not a bug, should go on the forums instead.

**Comment by Cyberboss** [comment]
This is a bug, it breaks the functionality of a gamemode

**Comment by lzimann** [comment]
As far as I know this is intended. Rev heads can use any flash to convert, not just the one they start with, so no, it doesn't break the gamemode.
