### ISSUE TITLE
you can fire particle acceleration rifles while inside mechs

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#27929]
![image](https://cloud.githubusercontent.com/assets/20155238/26664497/c01e4762-4657-11e7-9e5f-b47780376893.png)
sorry for shitty screenshot but it's totally a thing you can do

**Comment by factoryman942** [comment]
pro screenshot tip
press f2

**Comment by Repukan** [comment]
This tickles me in a funny way

**Comment by AnturK** [comment]
@kevinz000

**Comment by WJohn** [comment]
extra-wide mech beam lasers when?

**Comment by kevinz000** [comment]
fixed

**Comment by kevinz000** [comment]
i think
