### ISSUE TITLE
Temp visuals stop deleting themselves late into the round

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#27937]
>2 hour round 

>things won't qdel

Why.

**Comment by Cyberboss** [comment]
Sounds like the timer system conked out

**Comment by AnturK** [comment]
Seen this happen yesterday on 2h+ round too. Was pretty noticeable with emp blob.

**Comment by Cyberboss** [comment]
Let's fold this one into a dupe of #23818

**Comment by RocKeD** [comment]
I noticed this too, could this be related to the issue I submitted? #28177

**Comment by Cyberboss** [comment]
Dupe
