### ISSUE TITLE
Can't place Kinetic Crushers into Bags of Holding.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#27943]
You just drop it when you try putting it inside.
![crusher and boh](https://cloud.githubusercontent.com/assets/4581352/26684172/2bd916f4-46de-11e7-8451-0e6741172b71.png)

**Comment by Repukan** [comment]
Feature

**Comment by Kromgar** [comment]
Camt put gibtonite in there anymore either

**Comment by octareenroon91** [comment]
Ree another twohand/required bug

**Comment by kriskog** [comment]
This isnt happening anymore.
