### ISSUE TITLE
Lich (and the round) do not work if the wizard dies while in a body that leaves no remains.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27946]
Certain bodies do not leave a corpse when killed, such as in this case with a mining bot. The wizard was killed as one (mindswap), and he neither went back to his phylactery, nor did the round end (he was the only antag).

**Comment by octareenroon91** [comment]
I heard Mulligan could choose extended.

**Comment by WJohn** [comment]
I don't think I saw it even fire, this needs testing though.
