### ISSUE TITLE
Dual Colossus?

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#27953]
![2colossi](https://cloud.githubusercontent.com/assets/29125781/26704823/201c0342-4708-11e7-8795-cc24baf3acf4.png)

I am not sure how to reproduce this, but I'm pretty sure there's only supposed to be one Bubblegum/Colossus per map generation.

**Comment by Repukan** [comment]
Only bubblegum is tied to one per map.

Not an issue

**Comment by ShadowDeath6** [comment]
only one bubblegum can exist in the world at all iirc

**Comment by Repukan** [comment]
Yeah but collosi don't share that restriction.

**Comment by DoctoreMad** [comment]
Oh are you _serious_

**Comment by Repukan** [comment]
*meaty whack*
