### ISSUE TITLE
people are getting put INSIDE chairs on the arrivals shuttle

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#27957]
![WHAT THE FUCK](https://puu.sh/w8nur/b2aea53094.png)

**Comment by PKPenguin321** [comment]
yikes

**Comment by LaharlMontogmmery** [comment]
The chairs

They EAT people

**Comment by Penguaro** [comment]
They're old like the couch at your grandparent's house. They practically swallow you. #Feature #Traditional #Antique #NanotrasenDoesntHaveABudgetForNewChairsEveryTimeWeLoseAnAssistantInOne
