### ISSUE TITLE
You can set internals for another character but not activate their hardsuit helmet

### ISSUE THREAD

**Issue by Penguaro** [tgstation/tgstation#27966]
Not sure if this an oversight or intended. If another character is unconscious and all that is around is one of the nice hardsuits, you can enable internals but you can't get their helmet on them since it's inside the suit / deactivated. We kinda need a way to activate the helmet to assist an unconscious character if they're in a depressurized environment with you.

**Comment by Expletive** [comment]
If they're unconscious from lack of oxygen, apply CPR until they wake up. If they're unconscious from other wounds, then fix those and apply CPR. In either case, your best bet would be to apply epinephrine or similar and then get them to a pressurized environment where they can receive medical attention some other way.

**Comment by Penguaro** [comment]
@Expletive Unfortunately a pressurized environment and medical supplies weren't available but their engineering hardsuit was. They basically died without a helmet. I realize it's an uncommon scenario, still one should be able to get their helmet on if need be. Not everyone has the suit from EVA that has the detached helmet.
