### ISSUE TITLE
Abductors have not invented recharging technology.

### ISSUE THREAD

**Issue by KingPhilipIII** [tgstation/tgstation#27970]
Right, so I guess this would be more of an oversight than anything else, but why give the agent what I assume is some plasma based radiation gun that can be recharged, without giving the ayy ship a recharger of it's own.

I know thats not a bug, or maybe it was intentionally done like that, but I figured I would bring it up. If this belongs on the forum tell me and I'll get around to making a forum account I guess.

**Comment by Kromgar** [comment]
Its a decloner gun

**Comment by KingPhilipIII** [comment]
What it is doesn't matter. The point is they give the agent a gun that needs to be recharged but not a recharger.

**Comment by Repukan** [comment]
Because they're meant to use the advanced baton to kidnap, not the gun to shoot.

Literally meant as a last resort.

**Comment by WJohn** [comment]
I think it'd be good if it can only be recharged by going back to the ship, so it only functions as a last resort and is not at all reliable for continually firing. We could do the lazy route and have an actual unique alien charger there specifically for their gun.

**Comment by KingPhilipIII** [comment]
I'm just saying, even as a last resort, you would think that they would have some means of safely recharging their last resort on their ship, as opposed to having to teleport back down to borrow one of the station's chargers.

**Comment by Tacolizard** [comment]
how would they even charge it in the first place?

**Comment by ShadowDeath6** [comment]
>make a gun that somehow generates a large chunk of radiation
>don't have the technology to recharge it

**Comment by Steelpoint** [comment]
Would we be fine if we added a recharger that only accepts the Abductors gun?
