### ISSUE TITLE
Holopad usage needs more feedback.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27976]
When calling another holopad, you, the caller, have no feedback given whatsoever. You aren't told you are now calling the other holopad, there is no change in the UI (it becomes outright unresponsive, making it feel buggy), no sound or sprite changes either. When you are actually on the other side, it's not obvious that you have to type in cancel-camera-view at all, when a button would be much preferred like advanced camera consoles do it. Lastly, you are stuck and unable to move for a short while after using a holopad.

**Comment by Cyberboss** [comment]
It's unclear yes, but Alt-clicking the pad or moving your hologram out of area is the proper way to terminate a call.

If someone wants to take up porting the UI to tgui be my guest

**Comment by WJohn** [comment]
Alt clicking is super awful and should never be the go-to on how something works. I definitely want alt clicking to be removed from ventcrawling and any other source, or at least have A LOT more pointers on this kind of thing.

**Comment by optimumtact** [comment]
it's bad
