### ISSUE TITLE
Turrets take INCREASED damage from simple animals due to their armor.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27972]
Turrets naturally have 50 melee armor, and take double damage from simple animals as a result (15->30), increasing it to something like 75 will quadruple the damage taken and so on (15->60). Some calculation or other was either written wrong or is being interpreted wrongly.

**Comment by timothymtorres** [comment]
Pretty certain this had to have been fixed at some point in the last 5 years.  Someone needs to test it.

**Comment by Mooshimi** [comment]
MonkeyWhoCodes redid the hit 11 months ago, and it looks good 
![image](https://user-images.githubusercontent.com/85910816/182205638-2a7f7610-21c2-4246-a283-f3c9ac98c418.png)
