### ISSUE TITLE
cyborgs that are locked down can still use modules they had equipped before they were locked down

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#27988]

**Comment by factoryman942** [comment]
wait fuck disregard

**Comment by factoryman942** [comment]
wait actually no don't disregard

**Comment by optimumtact** [comment]
its' not a bug, they're just stopped from moving

**Comment by WJohn** [comment]
disregard? disregard.

**Comment by factoryman942** [comment]
if they're meant to be able to use modules while locked down
why can't they equip new ones
@optimumtact
