### ISSUE TITLE
Tachyon doppler array doesn't talk anymore

### ISSUE THREAD

**Issue by Grazyn** [tgstation/tgstation#27980]
The dish is rotated correctly towards the bomb testing site, bomb explodes (max cap) but the doppler doesn't say anything.

Server revision compiled on: 2017-06-02
The following pull requests are currently test merged:
#27954: 'Gangmageddon: Hell March Edition' by Robustin 

Based off origin/master commit: c7ee03

**Comment by Cyberboss** [comment]
Dupe of #27896
