### ISSUE TITLE
Lifesteal Crystal doesn't work on simple mobs?

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#27981]
Shooting simple mobs does not heal you

**Comment by ChangelingRain** [comment]
Of what damage type, and what type of mob? Was the mob alive? The mob DOES need to be alive.

**Comment by ChangelingRain** [comment]
What modules did you have in your KA, and what order did you add them in?

**Comment by Kromgar** [comment]
@ChangelingRain  It was a goliath and it was alive

**Comment by ChangelingRain** [comment]
I can't reproduce this; it might just be that it heals for 2.5 per hit and you didn't see yourself getting any healing.
