### ISSUE TITLE
Editing alternate_worn_icon is screwy with ghost roles.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27993]
If I edit an item's worn clothing (alternate_worn_icon was created specifically for admins), it will work fine on me, if I were to either spawn myself in as a human, or create a human body, then move my ghost into that.

However, if I spawn from a ghost role, say a lavaland syndie, and I try putting on the same piece of clothing? It won't work. I could literally strip them of their clothing and put my working suit on them and it will stop working ONLY on them. I can then put it back on myself and it'll be just fine again.

**Comment by magatsuchi** [comment]
alternate worn icon isn't a thing anymore, woohoo
