### ISSUE TITLE
malf AI Machine Overload ability is the stuff of nightmares

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#28000]
IT CREATES A GIANT LIST OF EVERY MACHINE IT CAN AFFECT
The list isn't even organised in any clear fashion

**Comment by Haevacht** [comment]
shit get

**Comment by francinum** [comment]
you're supposed to use it on rightclick. rightclicking the machine you want to explode.

**Comment by factoryman942** [comment]
so
hang on
right clicking at like any other point in time as AI doesn't do jack shit
but
in this one particular instance
it's the one thing you need to do

reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

then why does the list exist

**Comment by AnturK** [comment]
Because it's old code.

**Comment by FantasticFwoosh** [comment]
Tie it to a key/button prompt over the machine or something.

**Comment by CPTANT** [comment]
I think the most elegant UI solution would be to have an action button which after clicking on it gives you the ability to left click a machine to explode it.

**Comment by factoryman942** [comment]
#28334
