### ISSUE TITLE
Display cases not working properly?

### ISSUE THREAD

**Issue by Dizor** [tgstation/tgstation#28001]
I attempted to remove an item set in a display case (namely, my ID) after unlocking the case with the Curator's case key. The only response was the character kicking the case. I was told this is a design decision (which I can understand if the cases carry over from rounds, it would prevent a strong item from being powergamed into a round start) but in the case of something being inserted the same round, is it impossible to remove said item?

**Comment by francinum** [comment]
You can't. get good. don't do that.

**Comment by Repukan** [comment]
Lmao fucking retard

**Comment by optimumtact** [comment]
you can break the case to get your item back out

**Comment by Iamgoofball** [comment]
That will trigger the alarm, though, so bring some tools to break out/something heavy to break a window.

**Comment by WJohn** [comment]
Not a bug, it's just these things are kind of dumb intentionally.
