### ISSUE TITLE
Drones can be Vigilantes if they spawn in at roundstart

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#28042]
![image](https://cloud.githubusercontent.com/assets/12382984/26756477/25af130a-489b-11e7-9f13-14945932c2dd.png)

**Comment by KorPhaeron** [comment]
150

**Comment by factoryman942** [comment]
freedrone

**Comment by Dorsisdwarf** [comment]
@Robustin jfc

**Comment by msgerbs** [comment]
How do you spawn as a drone at roundstart anyway?

**Comment by Anonmare** [comment]
>observe>Go to derelict>Click on shell and select yes the minute the round starts

**Comment by TrustyGun** [comment]
can this apply to other ghost roles if you spawn the moment the round starts

**Comment by Anonmare** [comment]
Probably

**Comment by Lumipharon** [comment]
>army of vigilante dorfs swarm onto station with adamantine broadswords and dunk the gangers

Pls.

**Comment by octareenroon91** [comment]
Vigilante dorfs have happened yes.

**Comment by Cyberboss** [comment]
@Robustin I told you to use carbon/human dammit!!

**Comment by Xhuis** [comment]
This isn't in the live game (or even the code). Would it be a good idea post this in his PR and close the issue to get it off the tracker?

**Comment by KorPhaeron** [comment]
Not a live bug
