### ISSUE TITLE
Virology Stable Uranium Gel

### ISSUE THREAD

**Issue by Dariuscpt** [tgstation/tgstation#28059]
Stable Uranium Gel doesn't seem to work in viruses anymore, no matter how many or what symptoms are currently in the virus. 
No effect when mixed with base rhinovirus, and no effect when mixed with other more advanced viruses.

**Comment by QualityVan** [comment]
Are you using 5u gel? Unlike everything else, 1u stable uranium gel won't work.

**Comment by DoctoreMad** [comment]
That's kinda rude.

**Comment by XDTM** [comment]
Yeah you need 5u, although i wouldn't mind bringing it down to 1

**Comment by lzimann** [comment]
This got changed on #28122
