### ISSUE TITLE
Freon just crashed the server

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#28052]
9:30 pm EST, 6/3/17. Bagil. Freon had just been released so that's the most likely reason for the server crashing

**Comment by Iamgoofball** [comment]
prove it

**Comment by DoctoreMad** [comment]
>Not including important data on things that could also have been the cause of the crash

Come on now not even trying

**Comment by Iamgoofball** [comment]
my house burnt down, freon was added 3 years beforehand, i think freon burned my house down.

**Comment by ShadowDeath6** [comment]
goof burned my house down

**Comment by BeeSting12** [comment]
I'm not an admin so I don't have those details. All I know is that freon has a rep for causing crashes and we had a crash after freon was released.

**Comment by Bawhoppen** [comment]
circumstantially it did seem very likely for it to be freon

**Comment by Tacolizard** [comment]
Assistants were also probably in the round, that's probably what crashed it.

**Comment by AnturK** [comment]
Irrelevant without any data.

**Comment by BeeSting12** [comment]
Couldn't an admin pull data from the round? I'm not an admin so I can't- I obviously would if I could.

**Comment by AnturK** [comment]
Profile data which would be most useful here is not stored.

**Comment by Cyberboss** [comment]
The reboot memory leak is a much more likely culprit
