### ISSUE TITLE
Hierophant is hostile to lavaland fauna

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#28063]
This causes to some fun stuff like Hierophant going in a rampage against Legion tendrils and possibly losing.
Should be fixable with a faction change.

**Comment by Repukan** [comment]
Feature

**Comment by Repukan** [comment]
Fauna doesn't fight back so it's mostly it aggroing

**Comment by DoctoreMad** [comment]
Fauna does actually fight back m8, otherwise we wouldn't be having sick "skull x hierophant" fights.

**Comment by Repukan** [comment]
The fuck, I see it smack Goliaths with no opposition.

It's a bug then

**Comment by DoctoreMad** [comment]
Legions spawn skulls at it, and watchers shoot their little beams. Obvious aggression in there.

**Comment by Repukan** [comment]
Nevermind me then, I remember stuff differently

**Comment by DoctoreMad** [comment]
Even if there's a bug the main issue is not a bug I suppose
