### ISSUE TITLE
Shield projector shields become temporarily opaque for 1 tick when struck.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28060]
![](http://i.imgur.com/jq3YEOM.png)

Why? What balance purpose does this serve other than confusing people? I'm quite sure this wasn't the case before, either, but I don't know if it was changed to do this intentionally.

**Comment by Expletive** [comment]
Oh, so when you hit the thing, it blocks vision? That's kind of silly.

**Comment by Expletive** [comment]
Also this has apparently been a thing for a really long time, accorrding to the git history. Who knows when it was introduced.
