### ISSUE TITLE
Plasma & titanium sheets have no icons.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28076]
At least, full stacks don't appear to. It says "NO ICON" as an icon.

@Expletive

**Comment by Iamgoofball** [comment]
which server and are dorfss tesstmerged

**Comment by WJohn** [comment]
Clay, too.

Bagil has these, goofball. I imagine dwarves are responsible?

**Comment by Iamgoofball** [comment]
probably

I'll check it out

**Comment by WJohn** [comment]
probably dwarves related. will re-open if still broken after testmerge is over (for the 6th time).
