### ISSUE TITLE
Non-mineral gibtonite is instantlyexploding

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#28071]
WHAT THE FUCK DID YOU DO

Shoot the rock with your ka stop the detonation at 0 seconds.

Move rock and hit with your pickaxe and prepare to run but wait IT INSTANTLY FUCKING EXPLODES of having 10 second countdown

**Comment by Repukan** [comment]
I ded

**Comment by Kromgar** [comment]
@Repukan Nah i didn't die still startled

**Comment by Repukan** [comment]
Pls nerfe
