### ISSUE TITLE
Drones can't let go of the backpack water tank nozzle.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#28074]
![](http://puu.sh/wb0VD/130027e3b9.jpg)
using the action button gives the messages
The nozzle snaps back onto the tank!
You need a free hand to hold the mister!

Removing the backpack keeps the nozzle in your hand.
I dropped what I was holding in my other hand, and ended up with a second undroppable nozzle.

**Comment by Shadowlight213** [comment]
@Cyberboss

**Comment by Xhuis** [comment]
I can't for the life of me figure out why this is a thing. I imagine it's part of drone code rather than a problem in the water tank object, but if so it might be really hard to pin down.
