### ISSUE TITLE
janiborgs can clean the supermatter with soap

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#28075]

**Comment by DoctoreMad** [comment]
Working as Intended(Source: My ass)

**Comment by Penguaro** [comment]
There's missing information needed to resolve this. What type of soilage was present and did the soap clean it?

**Comment by Crexfu** [comment]
what should the result be? Nothing? Vaporize the user?

**Comment by WJohn** [comment]
You can also mop the supermatter crystal.

Normally doing this as a human would vaporize the object and activate the supermatter, dealing out loads of rads and hallucinations.

**Comment by DoctoreMad** [comment]
Clearly cyborgs have advanced motors and circuits that allow them to clean the blood on the supermatter without actually touching it

**Comment by kriskog** [comment]
Still an issue
