### ISSUE TITLE
AIs power alarms are buggy.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28086]
--- Power alarm detected in Prison(?|F) Wing! (<A HREF=?src=[mob_456];switchcamera=[icon-camera (SOUTHWEST)]>Brig Perma Cell 6 | <A HREF=?src=[mob_456];switchcamera=[icon-camera (SOUTHWEST)]>Brig Perma South | Brig Cell 1 | Brig Cell 10 | Brig Perma Wing 1 | <A HREF=?src=[mob_456];switchcamera=[icon-camera (SOUTHWEST)]>Brig Perma Cell 5 | Brig Cellblock South | Brig Cell 2 | Brig Cell 9 | <A HREF=?src=[mob_456];switchcamera=[icon-camera (SOUTHWEST)]>Brig Perma Cell 4 | Brig Perma Middle 2 | Brig Perma Wing 2 | <A HREF=?src=[mob_456];switchcamera=[icon-camera (SOUTHWEST)]>Brig Perma Cell 3 | <A HREF=?src=[mob_456];switchcamera=[icon-camera (SOUTHWEST)]>Brig Cellblock North | Brig Perma Middle 1 | Brig Cell 3 | Brig Cell 8 | <A HREF=?src=[mob_456];switchcamera=[icon-camera (SOUTHWEST)]>Brig Perma Cell 2 | <A HREF=?src=[mob_456];switchcamera=[icon-camera (SOUTHWEST)]>Brig Perma Cell 1 | Brig Cell 4 | Brig Cell 7 | Brig Perma Wing 3 | Brig Perma North | <A HREF=?src=[mob_456];switchcamera=[icon-camera (SOUTHWEST)]>Br

**Comment by Anonmare** [comment]
This was on Cerestation FYI

**Comment by GunHog** [comment]
Lots of AI stuff seems broken. Camera chunks on Lavaland, Xray-cameras not working on Golem Ship, etc..
