### ISSUE TITLE
Missing sprites for bunch of minerals

### ISSUE THREAD

**Issue by meeeeme** [tgstation/tgstation#28092]
There are shitty placeholder sprites for gold, silver and titanium (probably more).
Probably because of this #27964

**Comment by QualityVan** [comment]
Is anything testmerged? If so it's probably an icon conflict thing.

**Comment by Expletive** [comment]
It's because #27761 conflicts with #27964 (and also a lot of other things)

**Comment by DoctoreMad** [comment]
Yeah its goof's testmerge.

**Comment by AnturK** [comment]
Goof can't resolve confilicts and someone keeps merging his broken pr
