### ISSUE TITLE
Cancelling making a player poll after adding an option still creates the poll

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#28103]
wow thanks this sure is useful

**Comment by lordpidey** [comment]
Is this the reason behind the poll that was basically as follows?

What should be done with gang?
1.) Remove it.

**Comment by ChangelingRain** [comment]
Yyyyyup

**Comment by Shadowlight213** [comment]
Thay was the correct poll tbh

**Comment by Jordie0608** [comment]
Well once you've added one option, you're cancelling adding more, not creating the poll =P
But I can see a few ways this could be improved.

**Comment by ChangelingRain** [comment]
uh, the input has three options: "Add Option", "Finish", and "Cancel", but both finish and cancel create the poll, but cancel does so without any indication that it did.

**Comment by Cyberboss** [comment]
It'd be nice if we didn't run any queries at all until the creator said so
