### ISSUE TITLE
Should Abductor ships really be that close?

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#28119]
Last round(It'll have been a while since you read this though), all 4 ships got blown by a explosion in the top left one. now you must be a retarded abductor to let someone assplode in your ship but doesn't mean other abductors should be punished for it.

**Comment by 4dplanner** [comment]
It's quite sad that voice-activated toxins means you get punished for not sleeping the target through the whole thing

**Comment by WJohn** [comment]
That's some next level "I'm taking you with me" right there.

**Comment by octareenroon91** [comment]
https://www.youtube.com/watch?v=wQKKj_qeOBQ

**Comment by RemieRichards** [comment]
Rather than waste space moving them apart, just surround them with invisible walls with extremely high ```explosion_block```

**Comment by DoctoreMad** [comment]
@4dplanner can't you strip off the backpack and unmake the bomb while he's sleeping?

**Comment by 4dplanner** [comment]
@DoctoreMad Good point, I retract my complaints

**Comment by lzimann** [comment]
Just do Remie's suggestion. Don't even need to be invisible walls(althought they will "look" better).

**Comment by Xhuis** [comment]
I might've actually found another bug.

I was working on this, and I made a "forcefield" wall subtype of indestructible walls, with 99999 `explosion_block.` I then surrounded the abductor ships with it. Dropping a maxcap in one ship still affects the other ships, even though they're all surrounded by explosion-immune turfs.

**Comment by Cyberboss** [comment]
Can you drop a max cap on centcom and see if the indestructible walls are
blocking it? Also, make sure config.reactionary_explosions is enabled

**Comment by Xhuis** [comment]
Sure to both of those, let me see...

**Comment by Xhuis** [comment]
Reactionary explosions are enabled, yeah.

Before explosion:
![](https://puu.sh/wgA2V/7567ec0d56.png)

Just after explosion (5, 10, 20):
![](https://puu.sh/wgA3N/a3f53c19e0.png)

After the smoke has cleared:
![](https://puu.sh/wgA4b/ae1aa9e7a7.png)

**Comment by octareenroon91** [comment]
Centcom indestructibles were supposed to do that?

I thought it was a known thing, since explosions would leak out of thunderdome.

**Comment by Xhuis** [comment]
They're flagged as having an explosion resist of 50 in the code, which is pretty high. They should be blocking explosions.

**Comment by Cyberboss** [comment]
Just increase it to INFINITY

**Comment by ChangelingRain** [comment]
It clearly isn't doing anything, though.

**Comment by Cyberboss** [comment]
Drop a maxcap in the middle of centcom and you can see the explosion
deform. Drop a 512 and nothing blocks it. Leads me to believe the values
just aren't high enough

**Comment by octareenroon91** [comment]
Experiments `soon`

**Comment by Xhuis** [comment]
Nope. When `explosion_block` is set to INFINITY it does not block any explosions.

**Comment by DoctoreMad** [comment]
(Fuck)

**Comment by DoctoreMad** [comment]
EASY FIX THEY SAID
Someone just do the "widen the ships apart" fix, since explosion blocking walls aren't working apparently.
