### ISSUE TITLE
Lavaland plant people receive new law notifications

### ISSUE THREAD

**Issue by TheWiznard** [tgstation/tgstation#28129]
Server revision compiled on: 2017-06-05
f6063b 

the lavaland plant people receive a new law notification blip on the upper right for some reason. I don't know if it happens when ever any law is uploaded because I was a plantperson at the time but I still received a notification saying that I did.

**Comment by bgobandit** [comment]
are you sure you weren't hallucinating, this is one possible hallucination

**Comment by TheWiznard** [comment]
oh actually that might be the case I totally forgot about that. sorry
