### ISSUE TITLE
Engiborg cable coil alt-click creates dummy cablecoil stack

### ISSUE THREAD

**Issue by TheWiznard** [tgstation/tgstation#28131]
Server revision compiled on: 2017-06-05
f6063b

I attempted to altclick my cable coil module and it brought up a prompt for dropping x number of cables from my internal stack. Inputting any number removes that number from you internal stack and drops a dummy cable coil with 0 actual cables in it and you can't pick it up.

I originally thought that altclick would change the color of wire, like the minerborg prism stones, but that is not the case and is only related because that's what I thought it would do.

**Comment by WJohn** [comment]
Could've sworn I've seen 0 stack size cable coils many, many times before.

**Comment by TheWiznard** [comment]
Well when I did this it didn't actually say there was a number in the stack when I examined the coil
