### ISSUE TITLE
The ORM doesn't actually properly use plasma and iron when making plasteel

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#28155]
Instead of using one iron and one plasma for one plasteel, it uses 0.5 iron and 0.5 plasma for one plasteel. Since it can accept plasteel again, this means infinite plasteel.

**Comment by XDTM** [comment]
Hold up it accepts smelted plasteel?

**Comment by Profakos** [comment]
Inserting sheets was added in #28057 apparently.
