### ISSUE TITLE
Sorry, the following is not valid: 1.11295e

### ISSUE THREAD

**Issue by RocKeD** [tgstation/tgstation#28177]
Hey guys I have a strange issue, been running this particular round for about 34 hours straight and seemed to have come to an "Sorry, the following is not valid: 1.11295e  usage: .update_ping number"
error. The server revision is from about 6 days ago, tried the revision verb and states unknown. The messages appearing are being spammed constantly. No I did not manually use this function / verb.

Not sure what other information to give but here is a picture of what I am seeing. The has started to run very laggy. I know this is not a standard round situation but I figure could be useful in fixing an issue or optimization.
http://i.imgur.com/nFpyUOc.png
http://i.imgur.com/jS9FsMb.png

**Comment by AnturK** [comment]
Ping commands needs explicit num2text call so scientific notation format is not used.

**Comment by RocKeD** [comment]
Thanks for the response! Does this have any affect on the lag I was experiencing? Hopefully this will be fixed soon! Want to get back into those day long rounds haha!

**Comment by Tacolizard** [comment]
@RocKeD Unfortunately, no matter how hard we try your server will probably always lag at rounds of the length you describe. The fact of the matter is that this codebase isn't tested to work in long rounds.

**Comment by RocKeD** [comment]
You don't think it could be related to the spam I was getting?

**Comment by timothymtorres** [comment]
I believe this was fixed with #33098
