### ISSUE TITLE
Round end hangs indefinitely at end and doesn't get logged properly

### ISSUE THREAD

**Issue by nfreader** [tgstation/tgstation#28173]
[See round in question here](https://atlantaned.space/newSS13tools/round.php?round=71498).

There was no readout of any post-round information (greentext, duration, etc).

**Comment by Jordie0608** [comment]
Were there runtimes from the round?

**Comment by optimumtact** [comment]
14:13 <%LeoZ> runtime error: 
14:13 <%LeoZ> [01:33:03]Cannot execute null.score().
14:13 <%Jordie> that used to break reporting a lot
14:13 <%LeoZ> this is why
--------------------------------------------------------------------------------
14:13 <%LeoZ> [ticker.dm]
14:13 < TheGhostOfWhibyl1> https://github.com/tgstation/-tg-station/blob/master/code/controllers/subsystem/ticker.dm
14:13 <%LeoZ> why would the start_state be null though
14:14 <+oranges> https://github.com/tgstation/tgstation/blob/6dece515128821ac5ba567dd52620cbfad0e5fe8/code/game/gamemodes/game_mode.dm#L97
14:14 <+oranges> would have to be skipped
14:14 <+oranges> runtime in that proc maybe?
14:14 <+oranges> post_setup
14:15 <%LeoZ> yes
14:15 <%LeoZ> there was actually
14:15 <%LeoZ> runtime error: 
14:15 <%LeoZ> [23:57:56]Cannot execute null.make changeling().
14:15 <%LeoZ> on traitor_chan
14:15 <%Jordie> hah
14:16 <+oranges> https://github.com/tgstation/tgstation/blob/9e1ef0ffe2a7d955a40fd2d83382785353a29cb4/code/game/gamemodes/changeling/traitor_chan.dm#L57
14:16 <%LeoZ> this being null means the mob failed to spawn..

The stuff around stats and commit hash sould be moved into ticker, which is much less likely to runtime
