### ISSUE TITLE
Scrubber over pump.

### ISSUE THREAD

**Issue by NazarFogmann** [tgstation/tgstation#28186]
![image](https://user-images.githubusercontent.com/19737119/26884776-5039ade0-4ba9-11e7-9ce9-a59706398fd0.png)

Pump under scrubber. Cant click on pump.

**Comment by GunHog** [comment]
Until a mapper fixes that, use alt-click on the turf to get a view of that pump in a new tab. You can click to control it from there.

**Comment by Cyberboss** [comment]
MAP NAME!

**Comment by GunHog** [comment]
Looks like Metastation.

**Comment by NazarFogmann** [comment]
Meta

**Comment by ShizCalev** [comment]
click on the red band to open the interface for now

will move it in a moment.

**Comment by WJohn** [comment]
would be better if the layering of pumps was higher than that of vents/scrubbers.
