### ISSUE TITLE
Icon dropdown menu empty/fails to open

### ISSUE THREAD

**Issue by Tsuchigumo550** [tgstation/tgstation#28191]
Server revision compiled on: 2017-06-07
473600 

Tried everything in my power to get the icon window to open (it was bad enough that it couldn't remember not to default to the ugliest possible sprite mode), and it simply will not open. Relogging does nothing. Closing the window and rejoining does nothing. Admin dropdown also fails to open.

No OOC response as to if anyone else is having this problem. No testmerges to speak of.

**Comment by XDTM** [comment]
Which icon was it? This might be a symptom of a botched qdelete

**Comment by Tsuchigumo550** [comment]
Confirmed that some others were having this problem as of 2:17 PM. Not sure what the cause is, but I'm apparently not the only one.

**Comment by Cyberboss** [comment]
Mean I fucked up #28109

**Comment by Repukan** [comment]
150 hours

**Comment by Tsuchigumo550** [comment]
I'm not an admin, that's probably intended behavior. Figured that was the same as ahelp/etc.
