### ISSUE TITLE
If on any turf not zoned for station the staff of storms will default to nearspace aroudn the station

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#28228]
^ Unless things changed you used to be able to turn the shuttle into an ash storm hell.

I was an antag so... valid tactic but someone told me this was an intended change? 

I think the staff may have keyed off the "Near Space" zone along the edge of the station rather than the shuttle because escape wasn't turned into an ashy hell either

To replicate: Activate staff of storms in "space" region like 10 tiles out from lattices etc. outside of station and it will default to nearspace same with activating it on shuttle

**Comment by Kromgar** [comment]
It won't transform surround space into ash storms anymore either. It only defaults to near space. So near space seems to be overriding the staff of storms

**Comment by kriskog** [comment]
Cant reproduce
