### ISSUE TITLE
Cure all diseases doesn't work

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#28256]

**Comment by Xhuis** [comment]
Can't reproduce this.

**Comment by Cyberboss** [comment]
Everyone was still sneezing when I used it

**Comment by Xhuis** [comment]
Hmm. Maybe try spawning some humans in on a local server, infecting them with the flu, and seeing if curing it does anything? If not, it might be a problem with `cure()` for diseases, because the code for mass-curing seems fine.

**Comment by kriskog** [comment]
Couldn't reproduce this
