### ISSUE TITLE
Highlighting strings in goonchat does not work with spaces

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#28259]
How to reproduce: 
1. Set a string to highlight, save. The string must have a space in it.
2. Wait for those words to show up in your chat.
3. Watch as they're not highlighted.

**Comment by Tacolizard** [comment]
works for me

**Comment by Cyberboss** [comment]
This works for me. Please provide repro steps or I'll close this in a few days

**Comment by BeeSting12** [comment]
Okay, sorry, was gone for a week counseling at a summer camp. It turns out that it does work, you just can't use spaces.

**Comment by Dorsisdwarf** [comment]
Goonchat is dead. We have an entirely new set of string filter bugs now.
