### ISSUE TITLE
Bicons in ahelps spam the ticket window

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#28253]

**Comment by optimumtact** [comment]
ticket window should support bicon

**Comment by Repukan** [comment]
Bicons?

**Comment by optimumtact** [comment]
a base64 encoded byond icon to be shown in a goonchat window

**Comment by Cyberboss** [comment]
@optimumtact I mean the panel, We can't support them there

**Comment by ShizCalev** [comment]
Still an issue?

**Comment by Cyberboss** [comment]
Definitely

**Comment by Mooshimi** [comment]
![image](https://user-images.githubusercontent.com/85910816/182713182-c43f7729-6083-414b-b9b1-5c604ea75375.png)
