### ISSUE TITLE
Limb RNG can totally bypass armored limbs under certain conditions.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28260]
![](http://i.imgur.com/QZqo8F0.png)

Even if you have a 100 bullet protection armor vest (only covers the torso), RNG (which sometimes makes you hit other limbs) can target back ONTO the chest and do full damage, totally ignoring the armor. Normally it says nothing to the person firing the gun, implying they were not hit at all, but he went and took full damage to the chest anyway. It did a full 35 brute (m90's 5.56 rounds).

Performing the same test with full body (riot) armor  & helmet at 100 bullet protection made them properly immune to bullets no matter what.

**Comment by Tacolizard** [comment]
This is actually a pretty big bug, I'm glad you found it. Mabye this is why armor always seems to suck?
