### ISSUE TITLE
Goonchat doesn't work

### ISSUE THREAD

**Issue by randomperson777** [tgstation/tgstation#28265]
Goonchat doesn't work, It only loads font size strings and higlight color, then tells me I am either AFK, experiencing lag, or the connection has closed. 
I tried clearing byond cache, didn't work. Goonchat on goon does work. 
This happens the moment I join.

**Comment by Cyberboss** [comment]
@lzimann So he has the HTML but the js isn't starting for some reason, ideas?

**Comment by lzimann** [comment]
That's odd. What is your IE version?

**Comment by randomperson777** [comment]
9.0.8.112.16421.

**Comment by Iamgoofball** [comment]
Windows version, and is it a VM or Wine?

**Comment by Iamgoofball** [comment]
@Cyberboss Maybe embed a button in the html to boot up the JS manually?

**Comment by Cyberboss** [comment]
Windows version is a needful

**Comment by randomperson777** [comment]
Windows 7 32bit,  no service pack IIRC,  no wine/VM

**Comment by Iamgoofball** [comment]
Why haven't you installed the service packs?

**Comment by Cyberboss** [comment]
Update to ie 11 please and see if that fixes it

**Comment by randomperson777** [comment]
Got it, thanks.  And I don't know how to install them  :(

**Comment by Iamgoofball** [comment]
Internet Explorer has a button to run Windows Update.
