### ISSUE TITLE
Earmuffs broken

### ISSUE THREAD

**Issue by GrumbleNose** [tgstation/tgstation#28267]
**Problem Description**: Earmuffs failing to block any sounds or alter hearing in any way

**What did you expect to happen**: I expected earmuffs to have an effect similar to deafness, or at least not knowing a language or being unable to read.

**What happened instead**: Both ambient sound and spoken text were entirely unaffected.

**Why is this bad/What are the consequences**: While I only wanted earmuffs to block out the various undesirable things being spammed over comms this presumably also effects flash-bangs and explosions

**Steps to reproduce the problem**: My method was to run into medbay and grab the earmuffs next to cloning, this was on metastation, I assume it would be as easy as getting earmuffs and equipping them 

**Server**: Bagil

**Revision**: What revision was the server running? 2017-06-08
6f5157

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**: Gamemode was rev that ended within a few minutes, I was seeking earmuffs to block out the sound after discarding my headset proved to not be enough, I was able to reproduce this the very next round.

**Comment by Kromgar** [comment]
As far as i knew earmuffs just prevent you from getting fucked by flashbangs

**Comment by Xhuis** [comment]
Yup, looking at the code, this is intentional. When you put them on, it applies flashbang protection and heals your ears over time; no muting of sounds involved. This isn't a bug!

**Comment by GeneralGoose** [comment]
immersion machine broken

**Comment by GrumbleNose** [comment]
Oopsie daisy, well anyway.  Thanks for your time.
