### ISSUE TITLE
goonchat bug

### ISSUE THREAD

**Issue by 41300** [tgstation/tgstation#28277]
when i'm enter the in server, in the chat i see this message in red "you are afk, experiencing lag or the connection has closed." and this other one "loading... if this takes longer than 30 seconds, it will automatically reload a maximum of 5 times. if it still doens't work, use the bug report button at the top of the window.", and i'm wait, wait, and wait a bit more, and it doesn't work! this problem have started to happen when the goonchat have been put in tg code, im can still play the game, but im cant see the chat, like, i'm can pick a job and whatever but i'm can't see what the other players are sayng and im cant see my own messages.

**Comment by 41300** [comment]
![dreamseeker_2017-06-09_13-28-46](https://user-images.githubusercontent.com/29311090/26986952-9818990e-4d17-11e7-89a5-20eeab84abcd.png)

**Comment by 41300** [comment]
![dreamseeker_2017-06-09_13-28-46](https://user-images.githubusercontent.com/29311090/26986991-c2c58590-4d17-11e7-9e72-a1dc5f559040.png)

**Comment by 41300** [comment]
![dreamseeker_2017-06-09_13-35-05](https://user-images.githubusercontent.com/29311090/26987280-f64ed17c-4d18-11e7-94ae-fc72224dd37d.png)
![dreamseeker_2017-06-09_13-35-53](https://user-images.githubusercontent.com/29311090/26987288-feddc154-4d18-11e7-85ba-5b65f2461be7.png)
![dreamseeker_2017-06-09_13-36-47](https://user-images.githubusercontent.com/29311090/26987290-fffe3bd6-4d18-11e7-9bd3-d33c17dc6686.png)

**Comment by Cyberboss** [comment]
Windows and ie version please

**Comment by MrStonedOne** [comment]
Its working for me on IE8, funny enough

**Comment by 41300** [comment]
windows 7, but, i'm don't know what is IE, its internet explorer? if it is, how i'm know his version?
