### ISSUE TITLE
Sniper Zoom Bug (HUD)

### ISSUE THREAD

**Issue by Butterrobber202** [tgstation/tgstation#28274]
https://gyazo.com/7cfc6dc5d576c36db12e5b8755fe4184

Just this.

**Comment by GunHog** [comment]
@kevinz000

**Comment by ShizCalev** [comment]
This still happening after the refactor to how the zoom works?

**Comment by WJohn** [comment]
Still the case: http://i.imgur.com/w4URVlp.png
