### ISSUE TITLE
Effects breaking throughout the whole round.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28283]
![](http://i.imgur.com/Z2ttM8l.png)
![](http://i.imgur.com/QdbBXzN.png)
![](http://i.imgur.com/3GsDlCu.png)
![](http://i.imgur.com/4f5z2Af.png)
![](http://i.imgur.com/hDnbTWu.png)

Round ID 71628

I have no idea what causes this, but it's very common, doesn't happen with EVERY effect at every time, but at random they may suddenly break. I think I've seen this happen with projectiles, too? Happens with the BRPED very commonly, too.

**Comment by MrStonedOne** [comment]
This is the timer bug

There is already an issue report up for it.

**Comment by Cyberboss** [comment]
Dupe of #23818  @lzimann
