### ISSUE TITLE
Engineering (and maybe mining) cyborgs can ghetto NVGs on the station

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#28296]
First, equip your mesons
Next, de-equip your mesons once the overlay comes up
Now you are blind to darkness and can see as though you had night vision goggles on

**Comment by ShizCalev** [comment]
Dupe #26918

**Comment by ShizCalev** [comment]
Duplicate of #26918

**Comment by ShizCalev** [comment]
Duplicate of #26918
