### ISSUE TITLE
Admin - Deleting self with Chief Engineer w/Hardsuit Equipment leaves behind 

### ISSUE THREAD

**Issue by Penguaro** [tgstation/tgstation#28306]
On the most current build with no test merges. 

Observing round as an admin.
Through player panel become human
Select Equipment -> CE with Hardsuit
Delete self through right click.
Standard Battery is left behind.

I was able to do this several times. Spot checked a few other equipment sets and didn't see this happen with other jobs though I may not have hit ones affected.

**Comment by Kromgar** [comment]
It's the fucking tablet batteries we have a issue report for this already involving supermatting deleting everything but tablet batteries

**Comment by Penguaro** [comment]
Good to know. I'll close this since it is duplicate.
