### ISSUE TITLE
Can we PLEASE start logging succumbs?

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#28310]

**Comment by KorPhaeron** [comment]
Sure, make a pull request

**Comment by banthebantz** [comment]
suCC

**Comment by PKPenguin321** [comment]
Pretty sure we do in attack logs?

**Comment by QualityVan** [comment]
![image](https://user-images.githubusercontent.com/3839620/27007938-527cdb32-4e32-11e7-9c14-7f5a63ec445f.png)
Yeah it's logged under attack.

**Comment by Cyberboss** [comment]
@lzimann
