### ISSUE TITLE
the fact that the furfaggotry and anime promoting kike shill minority administrators haven't been removed yet

### ISSUE THREAD

**Issue by Spacedong** [tgstation/tgstation#28311]
remove degenerate shit, give me back my space station game with no bullshit retarded references to weebshit and dumb deviantart tier bullshit

**Comment by DoctoreMad** [comment]
![1471460966894-1](https://user-images.githubusercontent.com/29125781/27004528-c8f6a7ea-4de0-11e7-9e62-866f4d47ac10.png)

**Comment by GeneralGoose** [comment]
**# s-stop fur/anime/fetishsecuting me!!!!!!!!!!!**

**Comment by RemieRichards** [comment]
![laughing](https://user-images.githubusercontent.com/4043781/27004548-a336849a-4e02-11e7-9b28-dbf199f49abd.gif)

**Comment by TrustyGun** [comment]
high priority

**Comment by Spacedong** [comment]
further proving my point that u unintelligent faggots cant communicate with anything other than crudely drawn chinese cartoons

**Comment by RemieRichards** [comment]
![nottodisushittoagen](https://user-images.githubusercontent.com/4043781/27004655-b1c7378c-4e04-11e7-8160-243bd5ac2312.png)

**Comment by GeneralGoose** [comment]
their lack of social skills probably tells them that this is somehow offensive or provoking

**Comment by RemieRichards** [comment]
>their lack of social skills probably tells them that this is somehow offensive or provoking

Coming from you.

**Comment by GeneralGoose** [comment]
what do you know about me

**Comment by RemieRichards** [comment]
That you keep trying to be offensive and provoking, see:
> s-stop fur/anime/fetishsecuting me!!!!!!!!!!!

**Comment by GeneralGoose** [comment]
it was a satirical prediction of people getting triggered about this
i was right (as usual)

**Comment by RemieRichards** [comment]
How is me memeing on the idiot op, being triggered?

![mimimeme](https://user-images.githubusercontent.com/4043781/27004685-462079de-4e05-11e7-8a8d-c1000bead0de.jpg)

**Comment by GeneralGoose** [comment]
>trying to cover tears with "mémes
yeah not triggered at all

**Comment by RemieRichards** [comment]
And you've failed for the final time.
