### ISSUE TITLE
Goonchat icons for language are tiny.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#28316]
Server revision compiled on: 2017-06-09

961bb7

see:
![4beyvmx 1](https://user-images.githubusercontent.com/17237624/27005708-208fe29e-4e24-11e7-86aa-c29de4a8859e.png)
Windows 10/IE 11

**Comment by BeeSting12** [comment]
Pretty much any in chat icon is tiny with goonchat.
