### ISSUE TITLE
File name case confusion is causing fuckups on linux

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#28329]
BUG: Resource conflict: files sound/weapons/gunshot.ogg and sound/weapons/Gunshot.ogg have the same CRC!
BUG: Resource conflict: files sound/items/welder2.ogg and sound/items/Welder2.ogg have the same CRC!
BUG: Resource conflict: files sound/weapons/gunshot_smg.ogg and sound/weapons/Gunshot_smg.ogg have the same CRC!
BUG: Resource conflict: files sound/magic/WandODeath.ogg and sound/magic/WandoDeath.ogg have the same CRC!
BUG: Resource conflict: files sound/weapons/laser.ogg and sound/weapons/Laser.ogg have the same CRC!
BUG: Resource conflict: files sound/weapons/taser.ogg and sound/weapons/Taser.ogg have the same CRC!
BUG: Resource conflict: files sound/AI/attention.ogg and sound/ai/attention.ogg have the same CRC!

https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#files (3rd bullet point)

This is (one) of many issues blocking creation of a byond-cdn.

@hornygranny @optimumtact @Cyberboss @WJohn 

Both the file name, and everything that uses `''` to include the file, has to use the same cases or byond sees them as different resources then tries to add them to the same node in whatever data structure byond uses.

Some things will do shit like `'sound/AI/attention.ogg'` and then also `'sound/ai/attention.ogg'` causing byond to see them as two different files on linux.

**Comment by lzimann** [comment]
Working on a fix for this right now.
