### ISSUE TITLE
Tables show the icon for the whole dmi file instead of the proper sprite when examining.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28322]
![](http://i.imgur.com/uoRuku1.png)

**Comment by ChangelingRain** [comment]
@Cyberboss bicon() bug!

**Comment by WJohn** [comment]
It's not just tables, I think hooded items and a few others suffer from this.

**Comment by ShizCalev** [comment]
![3lpjug2](https://user-images.githubusercontent.com/6209658/27255384-ad1f0dc4-536b-11e7-882d-76f345cda7a8.png)

**Comment by WJohn** [comment]
Toooons of things suffer from this. Structures, several kinds of mobs and clothing etc.

**Comment by RandomMarine** [comment]
Examining a blood trail stalls the client for 20+ seconds because of this.

**Comment by SpaceManiac** [comment]
@Cyberboss Cannot reproduce.
