### ISSUE TITLE
Deltastation's Engineering south maintenance access door has organs

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#28326]
Every time I open this door as a cyborg, I see a bunch of random organs cycling into one another, changing colour from normal to black as well

![image](https://user-images.githubusercontent.com/12382984/27007265-83b7745c-4e44-11e7-87c3-a4835f82d88b.png)

**Comment by DaxDupont** [comment]
what

**Comment by DoctoreMad** [comment]
Are you implying SS13 stations are not ethical? SS13 stations are ethical.

**Comment by Anonmare** [comment]
And no, they're not actual organs they disappear as soon as the door's animation finished

**Comment by Kromgar** [comment]
This sounds like a cache bug

**Comment by WJohn** [comment]
Cannot reproduce. Airlock is fine in game.

**Comment by PKPenguin321** [comment]
Clear your BYOND cache. http://www.byond.com/forum/?post=29715

**Comment by Tacolizard** [comment]
no don't clear your cache that's awesome

**Comment by Jalleo** [comment]
@dorsisdwarf this can be closed I believe.

**Comment by ShizCalev** [comment]
@Cyberboss Mind closing this?

**Comment by vuonojenmustaturska** [comment]
@KorPhaeron

**Comment by Anonmare** [comment]
I got it
