### ISSUE TITLE
Shielded syndicate hardsuit has no facemask

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#28339]
Since it doesn't inherit the eva/combat mode toggle from /hardsuit/syndie, if you turn the lights off on your helmet you reveal that the helmet visor is never present.

**Comment by kriskog** [comment]
Still an issue. With gas mask on underneath
![image](https://user-images.githubusercontent.com/33292112/61475613-83e6cc80-a98b-11e9-9250-4093689c7101.png)

**Comment by ArcaneDefence** [comment]
![image](https://user-images.githubusercontent.com/51932756/114257406-1bb8f500-997d-11eb-9ed4-f01a891462c0.png)
This got fixed sometime or another.
