### ISSUE TITLE
the floor isn't actually lava any more

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#28344]
The pain stays but the tiles don't change

**Comment by Jalleo** [comment]
Not enough information provided.

**Comment by Bawhoppen** [comment]
That's definitely enough information?

**Comment by Kromgar** [comment]
So from what i can interpret the floor is no longer lava.... but you keep getting burnt

**Comment by YakumoChen** [comment]
The tile sprite doesn't change to lava.

**Comment by Cyberboss** [comment]
Please clearly outline the error or be closed

**Comment by Qustinnus** [comment]
@KorPhaeron tested, not occuring.
