### ISSUE TITLE
Machines spawn with excess cable coil.

### ISSUE THREAD

**Issue by Shihrt** [tgstation/tgstation#28340]
Rev 6e2ea5.
Freezers, heaters, SMES, the PACMAN generator, and likely other machines that need cable in construction, all spawn with a full stack of cable coil, rather than the amount they actually require. This doesn't apply to computers though.
This only applies to roundstart machines(eg atmos freezer). Does not apply to admin spawned, or player constructed machines. Only tested on Box so far.

**Comment by Tacolizard** [comment]
aw man this makes it harder to break out of permabrig

**Comment by Jalleo** [comment]
@Cyberboss Initialize Mapload issue?

**Comment by nicbn** [comment]
Can you reproduce this?

**Comment by Cyberboss** [comment]
@lzimann did you fix this?

**Comment by kingofkosmos** [comment]
Couldn't reproduce on a private server or on MetaStation, all worked as intended.
