### ISSUE TITLE
[consistency] You can straightjacket yourself instantly but can't take it off 

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#28355]
You can instantly equip a straight jacket like any suit but this immediately restrains your hands. Good luck getting it off anytime soon. A delay like with cuffing is needed to prevent self-restraining instantly. 
Tested with hot keys (did it by accident the other say but forgot to report it)
Might also apply to cuff shoes.

**Comment by WJohn** [comment]
Straight jackets are super old and dumb in many ways, tbh.

**Comment by improvedname** [comment]
Yes but why ate you putting a straightjacket on yourself?

**Comment by YakumoChen** [comment]
hotkey'd it by accident trying to bag it

**Comment by ExcessiveUseOfCobblestone** [comment]
Remove straightjackets
