### ISSUE TITLE
'Cannot execute null.ClientLogout()' preventing connections

### ISSUE THREAD

**Issue by JohannesMP** [tgstation/tgstation#28353]
On commit: f1f356a running BYOND 5.0 Public (Version 511.1384) on Linux

After having a server successfully up and running for a few rounds, occasionally after a round finishes, the server enters a loop where no-one can connect anymore.

Tailing the log reveals the following message each time a user attempts to connect:

    [20:04:48] Runtime in client_procs.dm,163: bad index
    [20:04:48] Runtime in client_procs.dm,389: Cannot execute null.ClientLogout().
    BUG: Finished erasure with refcount=1 (ref=5:0) DM (:0)

**Comment by Cyberboss** [comment]
The runtime on line 163 is a failure to add a ckey to the directory
null.ClientLogout is a call to the global ahelp tickets datum.

Sounds like your globals are fucky, are you running on linux?

**Comment by MrStonedOne** [comment]
>Sounds like your globals are fucky, are you running on linux?

>On commit: f1f356a running BYOND 5.0 Public (Version 511.1384) on Linux

@Cyberboss Please read posts if you are going to reply to them, to do otherwise is rude as fuck.

**Comment by Cyberboss** [comment]
Right, can write this off as a dupe of #26954 then

**Comment by JohannesMP** [comment]
Hmm, any recommended workarounds like what you mentioned in [this comment](https://github.com/tgstation/tgstation/issues/26954#issuecomment-299591334)?

**Comment by optimumtact** [comment]
Realistically the answer seems to be to run on windows instead becuase lummox does not appear to want to support linux

**Comment by AnturK** [comment]
Closing since it's the same thing as #26954
