### ISSUE TITLE
Survival bunker's SMES cells are not properly wired.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28369]
@MMMiracles 
You reversed  the inputs and outputs.

Edited the mean things out.

**Comment by MMMiracles** [comment]
Not sure why a simple mistake is enough to make needless insults. Something you need to talk about?

**Comment by WJohn** [comment]
Because I merged your PR hoping it'd be an improvement over the current one, yet there are high pressure windows everywhere (1000 HP a piece), the SMES cells do not power anything, and the gas miners do not start connected either (though that may not be achievable through mining). RTGs themselves appear to be broken, separate issue.

**Comment by MMMiracles** [comment]
Sure is a real shame nobody noticed the wiring issue in the PR considering the image had both piping and wires visible.

**Comment by ShizCalev** [comment]
>casts shade in an issue report for wiring something wrong on a map
>screw up the wiring in the pr meant to fix it

It happens to everyone, @WJohn

**Comment by Repukan** [comment]
Geez John, that time of the month again?

**Comment by WJohn** [comment]
It's 1 AM shuddup
