### ISSUE TITLE
RTGs do not seem to work.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28376]
What it says on the tin. Not even the monstrously powerful 400,000 watts from an abductor RTG makes any power.

**Comment by Marflowerose** [comment]
At least the 4 in Deep Storage/bunker sort of work, just in very odd manner. I tend to combine all the grids and set 2 SMES to input 100k and output 99,999. That sort of works in a weird way. Could also be that the RTGs don't have fuel in them.

**Comment by WJohn** [comment]
Nevermind im STUPID
