### ISSUE TITLE
You can't remove flamethrower plasma tanks

### ISSUE THREAD

**Issue by CPTANT** [tgstation/tgstation#28385]
The only way you can change the tank seems to be by deconstructing the flamethrower.

Either that or the way is so convoluted that nobody knows how to do it even after asking on 4 different occasions.

**Comment by AnturK** [comment]
Just slapping another tank with it should work. If not that's a bug.

**Comment by GunHog** [comment]
You must use a _plasma_ tank on it, and only a plasma tank. No other type works.

**Comment by CPTANT** [comment]
You slap another tank directly on?

Then this is a consistency issue, no other weapon uses that way of reloading.

**Comment by QualityVan** [comment]
You can reload guns like that.

**Comment by CPTANT** [comment]
damn its true.

But seriously, nobody knows this.

**Comment by CPTANT** [comment]
Actually I still consider this an issue since you can't remove your only tank from the flamethrower to refill it.

**Comment by Tacolizard** [comment]
you can remove the tank by using either a wrench or screwdriver, i don't remember which

**Comment by CPTANT** [comment]
No, using a screwdriver unsecures the igniter.

Using a wrench on a flamethrower without the igniter secured dismantles the whole thing into its basic components.
