### ISSUE TITLE
Lava tile spawning in the lavaland bases

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#28389]
![dreamseeker_2017-06-12_16-40-45](https://user-images.githubusercontent.com/28678854/27042517-1c0e412c-4f8f-11e7-9ad3-a6f3a9771467.png)
also there is a river of lava where the entrance is unless that's normal

just before i submitted this, a new round started with the same thing in the vet base and the syndie base again (the lava tile has changed its location on the syndie base)

**Comment by DoctoreMad** [comment]
It also drains all the atmos so welcome to hell

**Comment by DaxDupont** [comment]
The river of lava is so people don't get in or out.

**Comment by DoctoreMad** [comment]
Dude, do you realize that lava tile is eating a space where a wall should be?

**Comment by DaxDupont** [comment]
@DoctoreMad 
See this part:

> also there is a river of lava where the entrance is unless that's normal

**Comment by DoctoreMad** [comment]
oh

**Comment by WJohn** [comment]
Seems to be a dupe of #27719
