### ISSUE TITLE
Shield/field generators and projectors cannot be emagged.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28405]
Even though they have an actual emagged var and logically emagging them would at least remove locking restrictions on them, nothing happens. No text, no effects, nothing.

Don't know if this is a bug or just simply a feature request.

**Comment by Jalleo** [comment]
Feature request. 
Field generator has no code from what I saw in a quick search. You can double check to prove me wrong or right if you want. 
Its inherited with the emagged var
https://github.com/tgstation/tgstation/blob/eace4eec148e8a366ee2fe6673f852b59a2e77b1/code/game/machinery/machinery.dm#L103

**Comment by Jalleo** [comment]
Other two maybe the same I didnt check.

**Comment by ShizCalev** [comment]
Closed by #30065
