### ISSUE TITLE
we have 911 issues

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#28400]
# never forget :us: :eagle: 
![](http://www.az-desertriders.com/wp-content/uploads/never-forget-flag-and-eagle-1000.jpg)
![](http://pulse.ardexamericas.com/wp-content/uploads/2015/09/Never-forget.jpg)
![](http://www.evolutionscientific.com/blog/wp-content/uploads/2013/09/Never-Forget-9-11.jpg)
![](https://craigt73.files.wordpress.com/2011/09/9111.jpg)

**Comment by Cyberboss** [comment]
You are not the first one to do this you fucking meme

**Comment by Iamgoofball** [comment]
thats what makes it special
