### ISSUE TITLE
Smashing chairs doesn't give back any mats

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#28408]
Repo;
Pick up chair
Spam click ground until it smashes
Chair gets deleted, no metal returned.

**Comment by octareenroon91** [comment]
Chair code says you lose one sheet, and most chairs take only one sheet to begin with.

**Comment by ShizCalev** [comment]
So it'll only return something if you pick up a wooden chair... hm. It feels weird when states it smashes to pieces on the ground but doesn't leave anything.
Perhaps check if mats are metal, and if it doesn't have enough to return a full sheet, return a pair of rods or something?
