### ISSUE TITLE
All the tiles under the spacebridge windows on ceres are space tiles with catwalks instead of plating

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#28410]
![](http://puu.sh/wiruK/c49a043afb.png)

**Comment by ShizCalev** [comment]
I noticed the parallax and assumed it was a feature (since they weren't that way before) tbh, it looks pretty cool.

**Comment by ChangelingRain** [comment]
It actually means it's EASIER to depressurize the airbridges, since you only need to break one window and not two like it looks like you do.

**Comment by ShizCalev** [comment]
Will hit this after #28617 is merged.
