### ISSUE TITLE
Gang turret infinite stacking

### ISSUE THREAD

**Issue by Daturix** [tgstation/tgstation#28416]
You can buckle as many people onto the turret at once as you please, only 1 person controls it at a time.

**Comment by WJohn** [comment]
0.00000000000000000150 hours of testing

**Comment by Jalleo** [comment]
@Robustin

**Comment by Robustin** [comment]
The buckling code was changed recently and I think buckling itself was caught up as part of a refactor, when I put in the buckling code it was essentially the same as riding code's buckle effect and there is a var included in the base buckling proc that prevents buckling more than the "max buckled" var.

**Comment by Robustin** [comment]
Tested it: This isn't an accurate issue report. You can attempt to buckle additional people but they won't buckle, you'll just move them to that turf, just like tables or whatever. Not sure this should even be treated as a bug.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Robustin so this is fixed?

**Comment by Robustin** [comment]
I mean you can close it because it won't allow more than 1 buckle right now. All the OP was doing was moving people onto the same turf.

**Comment by ExcessiveUseOfCobblestone** [comment]
@optimumtact

**Comment by optimumtact** [comment]
what do you want

**Comment by ExcessiveUseOfCobblestone** [comment]
it's not an issue supposedly

**Comment by optimumtact** [comment]
And what do you want me to do about that

**Comment by ExcessiveUseOfCobblestone** [comment]
to close it reeeeeeeeeeee

**Comment by optimumtact** [comment]
![](https://file.house/gBDJ.png)

**Comment by Cyberboss** [comment]
My how the tables have turned
