### ISSUE TITLE
admin shuttle call and regular shuttle calling at the same time results in !FUN!

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#28424]
![fuck this](https://puu.sh/wiIzq/0bb4bc06b6.png)
![damnit](https://puu.sh/wiInF/7cfcd390a8.png)

**Comment by MollyKristoph** [comment]
wew

**Comment by VeryRealAccount** [comment]
Should have thrown the asteroid shuttle on top of it.

**Comment by GunHog** [comment]
Maybe we can enable shuttle buying again and make a new scrapheap shuttle in the process!

**Comment by ninjanomnom** [comment]
Looking at the code this shouldn't be an issue and I can't reproduce it
