### ISSUE TITLE
Syndicate Salvage Worker slashes Syndicate Salvage Leader!

### ISSUE THREAD

**Issue by ishitbyabullet** [tgstation/tgstation#28426]
[Note]: #28354: 'Make goonchat use unverified asset sending' by MrStonedOne
#28356: 'Workaround for byond bug causing clients to flood the server with repeated asset cache arrival messages' by MrStonedOne | Based off origin/master commit: 07a955

http://i.imgur.com/bgzP81F.png

One day, the Possessing Ghosts random magic event happened and I possessed the Syndicate Salvage Leader simplemob. Afterwards, every Syndicate simplemob in the area tried to kill and attack me.

**Comment by RemieRichards** [comment]
https://github.com/tgstation/tgstation/blob/f3b34f0669a14b5ad0c5abb812b8c279398addf8/code/modules/mob/dead/observer/observer.dm#L588

Intended, apparently.

**Comment by ishitbyabullet** [comment]
>be syndicate salvage worker
>notice your leader has a ghost inside him
>sound an alarm and kill your leader

Dang, the Syndicate doesn't fuck around.

**Comment by kevinz000** [comment]
wtf teamkillers they all deserve bans.

**Comment by factoryman942** [comment]
Theyre not even making a minimum effort theyre just tking
Paermban pl0x

**Comment by ishitbyabullet** [comment]
So if this is intended then why not close it? There's no reason to make the issues counter grow higher if there's useless issues.

**Comment by RemieRichards** [comment]
It's still open as we can discuss whether it's wanted.
This isn't a bug/non-bug situation, it's something intended but weird.

It was presumably done to stop the ghosts from looting their comrades without them fighting back,

**Comment by ishitbyabullet** [comment]
>be a simplemob
>kill comrades
>loot comrades
Dang, that guy must be a saint who found a locker if he does that. Also, I think the Syndicate Salvage Leader is the only syndicate mob who drops loot while the pirates always drop loot.

**Comment by factoryman942** [comment]
What about if the syndies are passive unless you attack them, then they open fire?

**Comment by ishitbyabullet** [comment]
You would have to do that for the other Possessing Ghosts mobs.

Even a necropolis tendril will be attacked if you possess it.

Even Mjor The Creative.
