### ISSUE TITLE
Various shuttles not going to Centcomm

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#28432]
What happened: I told white ship to move to Deep Space when shuttle was emagged, White ship moved to Deep Space and then was jammed
What I expected: White ship would continue it's travel to Centcomm even if I had ordered it to go to Deep Space as the order was moved during transit

Possibly also applies to pods if sent to Lavaland during Red Alert.
Normally when White Ship is wherever, it will automatically fly to CentComm, apparently being in transit messes it up.

**Comment by Jalleo** [comment]
I believe this is a dupe.

**Comment by ninjanomnom** [comment]
I've not heard of any issues with this in a long time. Bring this up again in another issue with reproducible steps if it happens again.

**Comment by adamkad1** [comment]
heres https://github.com/tgstation/tgstation/issues/44447
