### ISSUE TITLE
Shade cult masters lose master abilities when put into a construct

### ISSUE THREAD

**Issue by GLACoding** [tgstation/tgstation#28431]
[Note]: Shades that win cult leadership will have all their abilities while a shade, but will lose then on being put into a construct (in my case i was made into an artificer).

They also lose big text and their cult master icon.

**Comment by XDTM** [comment]
hold on you can make shades masters?

"Chaplain, we decided that you're the most qualified person to lead us to victory"

**Comment by DoctoreMad** [comment]
The Chaplain is always proselytizing the cult, so maybe he IS the most qualified person
