### ISSUE TITLE
Something is weird with Bump() and ratvar

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#28433]
Ratvar cannot escape this tiny brass window box: ![](http://puu.sh/wj0vh/eb0b7d8d59.png)
The following code should allow Ratvar to move through any given object. Somehow, Bump() isn't getting called in \~certain cases\~ of which I'm not entirely sure of; movement is called via `step(src, dir_to_step_in)` which should call Bump if it runs into anything.

    /obj/structure/destructible/clockwork/massive/ratvar/Bump(atom/A)
	var/turf/T = get_turf(A)
	if(T == loc)
		T = get_step(A, A.dir) //please don't run into a window like a bird, ratvar
	forceMove(T)
    
    /obj/structure/destructible/clockwork/massive/ratvar/Process_Spacemove()
	return clashing //this var will be FALSE usually, so ratvar will drift

**Comment by Repukan** [comment]
>Ancient steampunk god of machines cucked by windows

**Comment by DoctoreMad** [comment]
>This is how RatVar was sealed
>Couldn't break the glass because his sprite was huge

**Comment by kevinz000** [comment]
oh yeah, flightsuits don't automatically fly through windoors but ONLY if it's facing away from the direction of movement. Weird, eh?

**Comment by optimumtact** [comment]
forceMove calls bump doesn't it so you're just in an infinite loop?, you should probably just move the loc manually

**Comment by Cyberboss** [comment]
I don't think so, setting loc manually doesn't call turf/Enter, which should be the only place Bump is called

**Comment by ChangelingRain** [comment]
and even if it did call bump, ratvar should move to the fucking outer tile and not stay in the box.
since there's no loop warning it clearly doesn't.
