### ISSUE TITLE
Using an inducer on anything that doesnt have a cell breaks it forever

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#28439]
I noticed that if you try to charge a 100% APC, or do just about anything else with it, the inducer will permanently stop functioning.

**Comment by Expletive** [comment]
This has something to do with the recharging var being set to true, and then never being reset. The recharging var was supposed to stop someone from clicking multiple times and charging a thing repeatedly and much faster than intended, but for some reason it doesn't get reset in some cases. I'm not sure what those cases are, or I'd fix them.

**Comment by Robustin** [comment]
It seems to be any case where the APC was fully charged and thus an attempt to charge was never made.
