### ISSUE TITLE
Supermatter still needs adjustments for faster processing

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/tgstation#28443]
Going to put this as an issue so people actually see this. The SM recently got added to the air subsystem which processes (usually) 4x as fast regular objects so some things have become unbalanced. A few were fixed but some other issues remain. The biggest one seems to be that the crystal now produces 4x as much heat and moles of waste which quickly overwhelms the pipes and makes most advanced gas setups either extremely hard or impossible.

**Comment by Lumipharon** [comment]
Are you MAN enough to make void cooled engines?

**Comment by Jalleo** [comment]
I will try to check it out next week.
