### ISSUE TITLE
Syndicate Elite suits in combat mode do not respect face masks.

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#28450]
![image](https://user-images.githubusercontent.com/6778786/27109430-d1168250-5070-11e7-856e-a8a5eb8d446e.png)

It is really jarring. I would prefer to see my syndicate visor's red glare

**Comment by DoctoreMad** [comment]
Are you sure its not COMBAT mode? Because no lights on is combat mode.

**Comment by Kromgar** [comment]
@DoctoreMad Combat mode now reveals your face. It was done so to make it more obvious that you are in combat mode

**Comment by DoctoreMad** [comment]
Well yeah, and that's what's happening.
The title should be "Syndicate Elite suits in **combat** mode do not respect face masks.

**Comment by Expletive** [comment]
The issue is that he's wearing a syndicate gas mask and instead of seeing that through the visor, you see the character's face.

**Comment by ShizCalev** [comment]
also see #28339
