### ISSUE TITLE
Appendicitis vomiting doesn't actually leave vomit on the floor.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28461]
Bumbly Bee vomits on the floor!
Bumbly Bee throws up!

Doesn't leave anything on the floor.

Also seems to stack as you eat more and more things, you puke several times and the messages start to spam.

**Comment by bgobandit** [comment]
this looks like a flyperson bug, not an appendiciti sbug, regular mob vomiting for some reason uses different messages than this

also the "eating more and more things" part = normal fly behavior

**Comment by lordpidey** [comment]
did you perchance have something covering your face?  I know sometimes wearing a helmet when you vomit causes you to not vomit on the floor, but inside the spacesuit instead.

**Comment by WJohn** [comment]
This was definitely a fly person. I don't think he had anything covering his face, although he did have a bee costume with the hood up.
