### ISSUE TITLE
Traitor Clowns still clumsy

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#28467]
Traitor clowns still clumsy and unable to use guns.

**Comment by bgobandit** [comment]
honk tag pls

**Comment by Cheridan** [comment]
best i can do

**Comment by factoryman942** [comment]
Doesn't the clown-specific revolver check for clumsiness tho

**Comment by lordpidey** [comment]
How did the clown become a traitor?

Roundstart?  Adminfuckery?  Mulligan?  Latejoin?

**Comment by golfer45** [comment]
Roundstart, also happened to me after being converted to gang

**Comment by improvedname** [comment]
Being converted never removed the tag only roundstart antag should remove it besides gimme some SWEET muTaDone

**Comment by golfer45** [comment]
mutadone doesnt work, still clumsy after mutadone aswell

**Comment by MimicFaux** [comment]
Can confirm. Ambushed the HoP, said a bad joke, and shot myself into crit with my discount revolver.
Get what you paid for I guess. 
Honk honk! :o)

**Comment by CPTANT** [comment]
I don't get what the problem is with traitor clowns being clumsy in the first place.

If anything it adds to the consistency of the job.

Find some clown ways to kill people, there are plenty.

**Comment by optimumtact** [comment]
https://file.house/MdiD.txt

I added some stack trace outputs

it's removing then immediately readding when it calls specialise

antur is working on this as part of some overhaul work he's doing

@AnturK

**Comment by CPTANT** [comment]
Like I said before, traitor clowns should just be clumsy anyway.
