### ISSUE TITLE
I box, I die, I box again.

### ISSUE THREAD

**Issue by MrAlphonzo** [tgstation/tgstation#28489]
Dying with boxing gloves being equipped/Getting cloned while boxing gloves are still on your body result in a cloned player's hands remaining in a perpetual state of boxing, unable to punch lethally or grab.

**Comment by Kromgar** [comment]
Putting money down this is a bug with the system that keeps martial arts when cloned

**Comment by PKPenguin321** [comment]
That's technically working as intended, but the unequip on boxing gloves is being bypassed. Maybe make cloning force remove temporary martial arts.

**Comment by nicbn** [comment]
Feature
You leave the life but not the boxing
