### ISSUE TITLE
the disabler beam hits Unknown's X4, setting it off! What a shot!

### ISSUE THREAD

**Issue by Cheridan** [tgstation/tgstation#28481]
Blowing up grenades in people's hands should check for nodamage, similar to welding fuel tank explosions.

Also, the first letter should be capitalized!

This is probably a shitty feature to begin with, it's literally a prob(15) to just explode and die every time someone shoots you if you're holding any form of grenade.

**Comment by Repukan** [comment]
I ded

**Comment by WJohn** [comment]
Wait what this is a thing? WHY?

**Comment by Lumipharon** [comment]
The chance to happen should only be if you aim/hit their arms tbh, would make a tacticool reason to shoot people's arms if they're running around with a flamethrower or whatever.
