### ISSUE TITLE
Teleprods fit in backpacks

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#28496]

**Comment by nicbn** [comment]
How is it an issue?

**Comment by Supermichael777** [comment]
it shouldent that behavior was changed
what backpack?

**Comment by factoryman942** [comment]
Fuck
Meant teleprods
Kill me now

**Comment by XDTM** [comment]
Teleprods fitting in backpacks is intended, only stunprods are too big.

**Comment by GunHog** [comment]
It is intended. Note how teleprods are children of stunprods, yet the weight class is overridden. 
https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/weapons/teleprod.dm#L4

It makes sense when you think about it. They are much less accessible than normal stunprods, and it can become rather difficult to hit a person with one more than once!

**Comment by factoryman942** [comment]
K
