### ISSUE TITLE
gang turrets broken again

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#28507]
Can't climb on turrets, three seconds of fucking nothing to try and get on, and you can't
150 hours.

**Comment by Kraseo** [comment]
please just put gangs to sleep

**Comment by Cyberboss** [comment]
Can you verify this please, I swear I fixed it

**Comment by Robustin** [comment]
This was probably during a testmerge due to the forcemove change you requested.

**Comment by vuonojenmustaturska** [comment]
@KorPhaeron
