### ISSUE TITLE
statues newtonian motion is arested by the vision mechanic

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#28501]
Floating in space and suddenly get the message and stop dead.  Because i cant propel myself i cant move after

Server revision compiled on: 2017-06-15
The following pull requests are currently test merged:
#27954: 'Gangmageddon: Hell March Edition' by Robustin
Based off origin/master commit: b53a5f

**Comment by timothymtorres** [comment]
This bug report is not reproduceable and is lacking critical information to explain what is happening and what is broken.  Marking it as `Cleanup` and it will auto-close in 7 days.

**Comment by msgerbs** [comment]
Auto close in 7 days huh?
