### ISSUE TITLE
Pulsing mulebot wires no longer results in messages

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#28523]
Server revision compiled on: 2017-06-15

The following pull requests are currently test merged:
#27954: 'Gangmageddon: Hell March Edition' by Robustin

Based off origin/master commit: b53a5f

Pulsing wires while hacking mulebots no longer result in messages.
see 
https://tgstation13.org/wiki/Hacking#MULEbot

**Comment by Cyberboss** [comment]
Yeah, that is supposed to happen

**Comment by vzhegalov** [comment]
yep same too
