### ISSUE TITLE
give cats nightvision

### ISSUE THREAD

**Issue by Roboman100** [tgstation/tgstation#28525]
pushed yes for a deathsquad ghostrole and became a cat instead. atleast i could get my own night vision goggles man cmon
(or no balls do it u wont)

http://www.businessinsider.com/pictures-of-how-cats-see-the-world-2013-10

[Note]: # (Please enter the commit hash and active testmerge numbers from the "Show Server Revision" verb if you can. If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by YakumoChen** [comment]
go to the forums dude

also inb4 the Goof Brigade coming in and using this as a new excuse to ban catgirls or smth

**Comment by Iamgoofball** [comment]
# SLIPPERY SLOPE

**Comment by nicbn** [comment]
By cat you mean tarajan or pet cat?

**Comment by TrustyGun** [comment]
Im assuming it's catperson

**Comment by Cyberboss** [comment]
Feature requests go on the forums
