### ISSUE TITLE
Menu Ghost Bug

### ISSUE THREAD

**Issue by Nilons** [tgstation/tgstation#28542]
ROUND ID: 72014

As a ghost server hopped to see if some fucker was icky ockying sybil on the forums, didnt touch any button except server hop through out the entire process, when I was back on basil the menu from the lobby with Join game etc on it was in my screen, none of the buttons work but I also couldn't get rid of it.

**Comment by Cyberboss** [comment]
@optimumtact

**Comment by optimumtact** [comment]
what do you want

**Comment by SuperNovaa41** [comment]
No longer an issue
