### ISSUE TITLE
When bumping solid objects like walls, Ratvar jumps to the tile past the object rather than to the object

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#28545]
Before Ratvar hits the wall, with me standing in for him;
![](http://puu.sh/wnbak/b33776f3bb.png)
After "Ratvar" hits the wall;
![](http://puu.sh/wnbbF/2750851a9d.png)

Help this is not supposed to happen, Ratvar is supposed to at least be on the wall.
@Cyberboss

**Comment by Cyberboss** [comment]
damn bumpcode

**Comment by Xhuis** [comment]
This might have been caused by #28515. Probably was, actually.
