### ISSUE TITLE
sm charged singulo is invisible

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#28559]
![](http://i.imgur.com/7a3pVhz.png)
![](http://i.imgur.com/haH72le.png)

**Comment by optimumtact** [comment]
how do you know there was a singularity there

**Comment by Militaires** [comment]
@optimumtact i can see things getting succed

**Comment by banthebantz** [comment]
like a real black hole

**Comment by kriskog** [comment]
I dont think this is a thing that happens anymore? Make a new issue if it does.
