### ISSUE TITLE
Automatically generate the /airless type for turfs

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/tgstation#28554]
At the moment only a handful of turfs have a ```/airless``` variant.
This makes it quite annoying to make space ruins (something we're pushing for ever more)

The solution is simple:
```
/turf/open/floor/plasteel/barber
    blah blah
```
*Script ran by Travis*
```
/turf/open/floor/plasteel/barber
    blah blah

/turf/open/floor/plasteel/barber/airless
    initial_gas_mix = "TEMP=2.7"
```
The script would search all subtypes of ```/turf/open```

Just putting up an issue for it as I'm busy at present, just incase anyone wants to grab it (potentially one of the "freeze-skip" PRs?)

**Comment by Jalleo** [comment]
I approve but we might also want planet variants for each type of atmosphere we have.

**Comment by Dorsisdwarf** [comment]
Dead feature request
