### ISSUE TITLE
Ashstorms and cortical borers

### ISSUE THREAD

**Issue by ktccd** [tgstation/tgstation#28555]
[Note]: # (Please enter the commit hash and active testmerge numbers from the "Show Server Revision" verb if you can. If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

Server revision: 
https://github.com/tgstation/tgstation/commit/d0be33f480910f03db2b71736cab1f40c357679b

Cortical borers inside a host who walks through an ash-storm just dies, no matter if they pump their host full of healing chems.

**Comment by Repukan** [comment]
Feature

**Comment by GunHog** [comment]
Does the borer take damage within the host or something like that? If your host is dying because he walked into an ash storm and took damage faster than you can heal, then this is not a bug. Unless your host is made of metal, and not soft, weak flesh, then the burning hot volcanic ash is going to crisp him.

**Comment by AnturK** [comment]
Just so we're clear, this is not the case of borer inside storm-resistant host ? If so this is not really a bug.

**Comment by ktccd** [comment]
Ok, to clarify: Host was not resistant to ash-storms, but why would the borer take damage? The host was basically unharmed but the storm somehow ripped right through him and turned the borer to dust?
I've not tested this on a storm-resistant host, but it still feels like the borer shouldn't take damage as if he was crawling around unprotected when they're inside a host who's doing alright...

**Comment by GunHog** [comment]
The borer itself dying while in the host IS a bug, so this issue should be re-opened. You were not clear about this earlier. The borer should be safe from damage while in a host, barring certain reagents, changelings, etc. In this case, the resistance of the host to an ash storm would not matter.

**Comment by ktccd** [comment]
How do you request something to be considered for re-opening?

**Comment by improvedname** [comment]
Nah the ash gets in your ears

**Comment by KorPhaeron** [comment]
@AnturK 

Should I make weather not impact mobs inside other mobs or make borers get godmode while in a living host?

**Comment by AnturK** [comment]
I'd make mob-in-mob check ash storm specific, since makes less sense for rad-storms and such. Also Cyberboss PR.
