### ISSUE TITLE
Plasma Cutters lose charge from  emp charges

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#28566]
... They are powered by liquid plasma not electrical energy. Seems like a consistency issue

**Comment by Repukan** [comment]
Feature

**Comment by Repukan** [comment]
They're not powered by liquid plasma either

**Comment by Kromgar** [comment]
You shove plasma into them to charge them. So i suppose it's solid plasma which begs the question why would an emp effect plasma when plasma is used to emp proof cameras

**Comment by factoryman942** [comment]
are you sure it's not just a giant laser gun strapped to a pacman

**Comment by AnturK** [comment]
Not really a bug, feel free to change the emp flavour.
