### ISSUE TITLE
pen uplink auto-locks

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#28569]
the other uplinks stay open if you close the menu
with the pen you have to unlock it again
you can never be caught accessing your uplink

**Comment by Xhuis** [comment]
This isn't an issue. It looks to be intended from the code.

**Comment by DoctoreMad** [comment]
What he's saying is you should make a post on the forums

**Comment by Xhuis** [comment]
Well, I mean, if he wants. But this isn't a bug, and the issue tracker is for bugs, which this is not! I just think the issue should be closed, and the thing posted to minor ideas or minor feedback instead.
