### ISSUE TITLE
Metastation robotics starts with low resources

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#28563]
It has less platsteel than usual and only enough glass for one exosuit fab.
Did the guy behind this hate robotics or something?

**Comment by YakumoChen** [comment]
Same amount as Box had before the robotics rebuild actually.

**Comment by DoctoreMad** [comment]
What a coincidence. Must be unintentional, then.

**Comment by Shadowlight213** [comment]
More like no one updated it when box's was buffed.

**Comment by factoryman942** [comment]
they appear to both have 10 plasteel?
