### ISSUE TITLE
Morphs can morph into light itself

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#28576]
This issue was shown to me by armhulen with NPC morphs. Their AI allows them to morph into light, which seems to turn them invisible sometimes and other times turn them weirdly see-through.

**Comment by Kromgar** [comment]
This was supposed to be fixed by @kevinz000  iirc

**Comment by nicbn** [comment]
Featur-WHAT??!!

**Comment by RandomMarine** [comment]
REVENGE OF #27509

**Comment by Armhulen** [comment]
*unzips light overlay*

**Comment by evsey9** [comment]
Aww, only AI morphs?
Fix this right now.

**Comment by Cyberboss** [comment]
Fixed by 98b05ff1213fe2893c1b1b22b831af3bc53488a7
