### ISSUE TITLE
Premium Shuttle Capsule false antag item can hold abstract items

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#28589]
![0quality](https://user-images.githubusercontent.com/29125781/27278702-8638b61c-54b8-11e7-9d93-a39e78d8c5dc.png)

In this case, a 2-handed item's offhand.

**Comment by outbools** [comment]
Feature

**Comment by DoctoreMad** [comment]
Wait is it?

**Comment by AnturK** [comment]
For some reason it just has riding offhand on the possible replica list, i'm gonna guess it was just path typo but no idea what it was supposed to be.

**Comment by DoctoreMad** [comment]
Wew
