### ISSUE TITLE
Stuns broke

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#28602]
Slipstuns only last a single second.
Lzimann asked if we noticed something weird about stuns so i am guessing it's related.
Server revision compiled on: 2017-06-19

The following pull requests are currently test merged:
#28580: 'Fix cid reconnect message not showing' by MrStonedOne

Based off origin/master commit: 9c9691

**Comment by improvedname** [comment]
Taserslugs acted weird too like i shot clown got up after 3 seconds shot another stayed longer down unless taserslugs is random but im pretty sure it isnt
