### ISSUE TITLE
There is no Slime Processor board in the circuit imprinter

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#28615]
^ Also built a smart fridge but it wouldn't accept slime cores but i heard you had to screwdriver the board for a slime smartfridge or something?

But yeah i searched in every fucking area bio was 6 everything else was 5 or above. There was no slime processor board or any boards with the name slime in them. I saw the monkey recycler no slime recycler or slime processor board.

**Comment by DoctoreMad** [comment]
I think the slime processor is a renamed food processor, have you tried _that_?

**Comment by DoctoreMad** [comment]
Hm.

>+/obj/item/weapon/circuitboard/machine/processor/attackby(obj/item/I, mob/user, params)
+	if(istype(I,/obj/item/weapon/screwdriver))
+		if(build_path == /obj/machinery/processor)
+			name = "circuit board (slime Processor)"
+			build_path = /obj/machinery/processor/slime
+			user << "<span class='notice'>Name protocols successfully updated.</span>"
+		else
+			name = "circuit board (Food Processor)"
+			build_path = /obj/machinery/processor
+			user << "<span class='notice'>Defaulting name protocols.</span>"

**Comment by DoctoreMad** [comment]
Yeah there also should be a multitool proc
Don't close it

**Comment by Kromgar** [comment]
@DoctoreMad 

Or to multitool. You can only learn these things by being told. It's totally obfuscated and unintuitive

**Comment by Jalleo** [comment]
Gonna see if I can sort this out tomorrow. I should of done this ages back but I didnt understand how to. Also I will clean up the code too.

**Comment by XDTM** [comment]
close this pls
