### ISSUE TITLE
While wearing activated magboots items still fly out of hands when walking on ice

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#28621]
Ice being tiles frozen by freon. However the player does not fall or slip.

**Comment by DoctoreMad** [comment]
Yeah nevermind the aesthetic Freon is a shit gas that should be removed

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/2672d888001d74672696bd6d494488e7301c027c/code/game/turfs/turf.dm#L178

Looks intentional

**Comment by ShizCalev** [comment]
Should this actually be changed? It seems intentional

**Comment by vuonojenmustaturska** [comment]
@KorPhaeron ?

**Comment by KorPhaeron** [comment]
It seems weird that items would fly out of your hands if you're otherwise immune, this seems like a bug to me

**Comment by KorPhaeron** [comment]
@kevinz000 they should either slip and lose items, or not slip and not lose items, I don't mind much which as long as it is consistent

**Comment by kriskog** [comment]
Still an issue. Reproduced with cold water vapor.

**Comment by kriskog** [comment]
Wait, I only dropped stuff when I slipped. Scratch that
