### ISSUE TITLE
Mindshield implants can work multiple times

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#28629]
I was doing this on a gangs round. Occasionally, when deconverting a gang member, the mindshield implant would not need to be refilled and could be used about three times. Not quite sure how to trigger it, seemed to happen when I implanted a gang member.

**Comment by Repukan** [comment]
Sssh

**Comment by BeeSting12** [comment]
it's only a matter of time before an admin catches me abusing this and bans me for it

**Comment by Repukan** [comment]
It's a feature

**Comment by vuonojenmustaturska** [comment]
@KorPhaeron

**Comment by AverageJoe82** [comment]
is this only gang related? and is this still an issue there?
