### ISSUE TITLE
Somehow engraved messages are getting onto the syndie base

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#28632]
in the upper left of the snowy area around the syndie ship, i found this:

![](https://file.house/vTyB.png)

The thing is, this area is inaccessible to players and both messages are about the lavaland aux base, not at all acknowledging that they're on the syndie base.

**Comment by Jordie0608** [comment]
This'd be due to #27697 wherein the z level of station and centcomm were switched; existing messages just weren't updated to account for it (not really worth doing).
