### ISSUE TITLE
Spawnable slime processors have a weird description

### ISSUE THREAD

**Issue by Lexorion** [tgstation/tgstation#28647]
Spawn and examine a slime processors (/obj/machinery/processor/slime) and you see sSSticker in the description. The frozen processors is the normal one (/obj/machinery/processor) xenobio on box uses.
![](http://i.imgur.com/evFVyKl.png)
Someone should just remove the unused slime processors since the normal one works just as fine. I don't think it's used on the other maps but I did not check it yet.

**Comment by XDTM** [comment]
imagine a lizard whispering this to your ear every time you look at the grinder

**Comment by nicbn** [comment]
Uh... I can pull request it but I'm not sure if it's a meme

**Comment by RemieRichards** [comment]
Technically it's not a typo, as no human wrote that.
it was the ticker -> SSticker regex, so sticker -> sSSticker
