### ISSUE TITLE
Sounds on lavaland are way quieter since it's low pressure

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#28641]
Not a bug, technically, but it's annoying that KAs and stuff rely on the low pressure for damage since it makes everything a little quieter than normal.

**Comment by Cyberboss** [comment]
Feature imo

**Comment by Repukan** [comment]
Feature.


Turn up your volume

**Comment by RemieRichards** [comment]
>Joel: It's a feature
