### ISSUE TITLE
Admin abusing jungle fever on a monkey without a player bypasses logs

### ISSUE THREAD

**Issue by LetterJay** [tgstation/tgstation#28655]
As the title says.

If you spawn a monkey without a player assigned to it and infect it with jungle fever, you can bypass the admin logging.

**Comment by Repukan** [comment]
Which admin did this tho

**Comment by DoctoreMad** [comment]
Well, we don't know because we don't have logs :^)

**Comment by Cyberboss** [comment]
@kevinz000 says its fixed
