### ISSUE TITLE
Paper Bin Ghost

### ISSUE THREAD

**Issue by ishitbyabullet** [tgstation/tgstation#28653]
[Note]: Server revision compiled on: 2017-06-20

The following pull requests are currently test merged:
#28334: 'Malf AI module refactor and small additions' by Xhuis
#28616: 'Makes movement delay calculation not round to the tick' by MrStonedOne

Based off origin/master commit: 3259e2

http://i.imgur.com/6RU5kHW.png

While making paper frames, I noticed that they have no sprites.

**Comment by nicbn** [comment]
Wait
Can a paper bin get empty?
