### ISSUE TITLE
Cultist summoning doesn't properly remove them form cryo

### ISSUE THREAD

**Issue by Thunder12345** [tgstation/tgstation#28651]
\>Place cultist in cryo, turn it on
\>Summon them with a rune
\>They remain asleep, build up cryox, and heal as if they're still in the cryotube
\>Doesn't turn off only when fully healed
Occupant var on the cryotube is still set to them, even though they were pulled out, and the sprite isn't updated

**Comment by Cyberboss** [comment]
Wew
