### ISSUE TITLE
Turned into a catperson after being cloned

### ISSUE THREAD

**Issue by TribeOfBeavers** [tgstation/tgstation#28669]
After dying and being cloned as a regular human, I had cat ears and a tail. 

I had the ears and tail enabled in character preferences and late joined as the CE.

**Comment by Sligneris** [comment]
Feature

**Comment by Thunder12345** [comment]
Proof that if you sign up as a head while a cat, CentComm simply snips the ears and tail off

**Comment by kevinz000** [comment]
Cloning invoke your inner degen- I mean, kawaii-ness.

**Comment by CPTANT** [comment]
Aren't cat ears/tail determined by a regular SE/UE/UI mutation?

If that is the case than this is the expected behaviour.

**Comment by TribeOfBeavers** [comment]
If you have cat stuff enabled and join as a head it is supposed to remove them entirely, like if you didn't have them enabled in the first place (as catpeople aren't supposed to be heads of staff). And I'm pretty sure it's a separate thing from SE/UE, as you can't make someone a catgirl through genetics afaik.
