### ISSUE TITLE
Abductor gear on R&D has unreachable tech level but are still coded

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#28666]
For example, Abductor Wrenches need about 4 abductor to build. Usually, you'll get 2 abductor points at best.
Can we lower them to 2? It shouldn't be too bad since jaws of life and other better gear are in already.

**Comment by XDTM** [comment]
You need real abductor equipment, not just lavaland stuff.

**Comment by XDTM** [comment]
Also they're 2.5 times faster than jaws of life and hand drills making them near instant.

**Comment by DoctoreMad** [comment]
Oh

**Comment by DoctoreMad** [comment]
R-RIP

**Comment by GunHog** [comment]
Yep, to get Abductor tools, you must loot an actual Abductor!

**Comment by DoctoreMad** [comment]
Won't be changed so let me cry in the corner
