### ISSUE TITLE
Ghosts can create sparks with portals

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#28667]
Step 1. Be Human
Step 2. Open a portal with portable portal maker thing form captain's quarters or research
Step 3. Become Ghost
Step 4. Click portal to spark beyond the grave

**Comment by Tacolizard** [comment]
wait how do they open portals

**Comment by DoctoreMad** [comment]
OP updated.

**Comment by ShizCalev** [comment]
bluespace shadow realm

**Comment by Cyberboss** [comment]
@kevinz000
