### ISSUE TITLE
SM can be instantly fucked over pretty easily.

### ISSUE THREAD

**Issue by Darkgenerallord** [tgstation/tgstation#28663]
If one turns on the emitters after opening a tile to space in the SM chamber, then replaces the tile a few minutes later, it'll instantly delaminate. This is a relatively big problem for obvious reasons.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by ShizCalev** [comment]
dupe #28638
