### ISSUE TITLE
Disposal Bins don't stay turned off

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#28672]
>Be me
>Ops gunning people down in my department
>Round a corner
>See a dsisposal bin
>Turn it off (and I made sure it was, the sprite has a light on it that goes black when it is turned off)
>Hop inside
>Disposal bin turns itself back on
>Get flushed into space due to bombs breakign the pipes

I've tested this a few times now and it seems disposal bins will "correct" themselves if turned off.

**Comment by PKPenguin321** [comment]
I'd still argue this is a bug, as the old functionality worked by just turning the power to off and it would not flush, and the functionality was lost when the UI was refactored.

**Comment by actioninja** [comment]
Not a bug, flush first if you want it to not flush you.
