### ISSUE TITLE
Chaplain's Clown Dagger uses an unnamed scroll sprite instead of the clown render.

### ISSUE THREAD

**Issue by obscolene** [tgstation/tgstation#28678]
You know, I always found it pretty strange that the clown dagger looked like a fucked up bone-looking thing instead of the actual clown dagger sprite. I haven't looked through the code, but the only logical reason for this is because the clown dagger was assigned no icon_state. The rolled up scroll being the first thing in wizard.dmi, where the clown render sprite is, it would default to it.

![](https://gyazo.com/59052717d5f685427b2965817cc35db4.png)

**Comment by kilkun** [comment]
lol

**Comment by BeeSting12** [comment]
wow, and all this time i thought it was meant to be a bone

**Comment by DfourC** [comment]
I always figured it was blunt and that was the joke.
