### ISSUE TITLE
Goonchat window is solid white, No messages, error or otherwise.

### ISSUE THREAD

**Issue by GuyonBroadway** [tgstation/tgstation#28687]
This is currently an issue for me on Sybil Bagil and Hippiestation (and presumably anything that mirrors /tg/ code but I do NOT want to go to citadel) however in goon itself everything is normal so I am pretty sure it's a /tg/ derrived issue.

![image](https://user-images.githubusercontent.com/22083966/27409793-2e94dfba-56db-11e7-9682-fc59ce833f5c.png)

There isn't even a warning message about goonchat not working so it seems different than the other goonchat issue. 

The strange thing is, it started happening on my local test server while coding, I compiles, ran and it was fine, complied, ran again and assumed I broke something while coding and then suddenly Hippie and /tg/ are like this too.

**Comment by GuyonBroadway** [comment]
Forgot to mention, IE 11 and windows 7 64 bit premium with all the latest updates installed. Byond version 511.1385

**Comment by MrStonedOne** [comment]
dupe of #28346

**Comment by GuyonBroadway** [comment]
Ya sure? My window is behaving differently and I don't get that "window not loading" message. I can't even interact with the chat window at all. Right clicking does nothing.

**Comment by MrStonedOne** [comment]
None the less, this could (or should) be fixed on sybil, try it out.

**Comment by GuyonBroadway** [comment]
How recently has a fix been deployed to sybil? Becase last night when I posted the issue it wasn't workingbon sybil.

**Comment by MrStonedOne** [comment]
like, just recently, I test merged a fix that changes how goonchat loads.

**Comment by GuyonBroadway** [comment]
Well I can see the chat now but it is strange that goonchat isn't working at all when it worked just fine not too long ago...

It actually happened while I was doing some coding, it worked for a while, then I complied something and it suddenly stopped. 

I'll try re-installing byond and running ccleanr to purge every trace of it and see if that helps.

**Comment by GuyonBroadway** [comment]
**Update**, the nuclear option worked.

For anyone with the same  issue, uninstal byond, delete the Byond folder in program files, then delete the byond folder in my documents and run ccleaner and fix registry issues.

This is how I fixed my version of the issue.

**Comment by ShizCalev** [comment]
Can this be closed then?

**Comment by GuyonBroadway** [comment]
Yes, no problems since the update that couldn't be fixed by clearing cache.
