### ISSUE TITLE
Nuclear fission explosive is irradiated

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#28688]
The nuclear fission explosives the nuke ops have currently gives out 40 rads per second WITH a syndicate hardsuit, not sure if the station nuke is doing the same thing. Reported after I witnessed two separate nuke ops die from radiation whilst around the nuke.

**Comment by MrAlphonzo** [comment]
Can confirm the vault nuke behaves the same while fully contained. Took rads from it before, wish I had realized it was a bug with nukes sooner.

**Comment by PKPenguin321** [comment]
The nuke core inside of it which is usually inaccessible has massive rads and is probably acting despite still being in the nuke somehow

**Comment by ShizCalev** [comment]
@bgobandit  likely caused by your changes in #27913
