### ISSUE TITLE
Nukes might or might not be emitting radiation by default

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#28690]
1.Whenever I enter the Vault as a swarmer, I get "you feel radiation" messages. Might or might not be the nuke, but I'm never here as a human.
2.Two nuke ops died the round before this was written because their portable nuke kept spewing radiation everywhere.

**Comment by ShizCalev** [comment]
1 is a dupe of #28656

**Comment by DoctoreMad** [comment]
The nuke on the vault is not supposed to be emitting radiation so no

**Comment by DoctoreMad** [comment]
That second note though

**Comment by DoctoreMad** [comment]
Wait no shit that issue doesn't cover the station nuke spewing radiation

**Comment by ShizCalev** [comment]
@DoctoreMad The first reply is literally talking about the vault (station) nuke.

Either way, both nukes share the same parent, and the issue is with the nuke_core item (which is a shared item between the two,) ergo one pr covers both.

**Comment by DoctoreMad** [comment]
No, I'm pretty sure the first reply is abstractly talking about the vault nuke.
