### ISSUE TITLE
Blob Forced Away From Core

### ISSUE THREAD

**Issue by Daturix** [tgstation/tgstation#28695]
Blob round, planning with other blob, I at RnD servers, Other at perma. I start going towards toxins storage and a scientist cuts off the arm which my controller was on then killed that last blob piece, i was unable to get back to my blob and it jumped my screen to the second blob. I then tried to jump to core/node but the only 2 options were the second blobs core and his node he had. I was still alive and had blob overlay but had no way to get back to core to defend myself.

**Comment by timothymtorres** [comment]
I'm going to test this today to see if this still exists.  I remember seeing this bug years ago, but I suspect with a lot of the new UI features added to blob that this is no longer a problem.

**Comment by JohnFulpWillard** [comment]
@timothymtorres Update?

**Comment by timothymtorres** [comment]
Tested it now.  If you get your controller cutoff from your blob network you can still jump to your core and nodes. (as well as other blobs nodes)

I think this bug was happening before the blob rework.
