### ISSUE TITLE
sound/vox_fem/o.ogg is really sound/vox_fem/i.ogg

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#28691]
sound file is an incorrectly named dupe. i can't say "l m a o" over vox announcements because of it

**Comment by Cyberboss** [comment]
I'd ask where we got these sounds from, but last time I did we had to replace the security mask sounds...

**Comment by bgobandit** [comment]
it's not I, it's the short O vs. long O

**Comment by Davidj361** [comment]
I couldn't make the synthesizer pronounce "O".

**Comment by dragomagol** [comment]
Will be closed by #55626, but writing "oh" is closer to the "o" sound, rather than what it says, which is more like the "ou" in "ought"

**Comment by Cyberboss** [comment]
That PR does not replace old vox

**Comment by Iamgoofball** [comment]
It will afterwards, I haven't deleted the files yet to keep the diff clean.
