### ISSUE TITLE
AOE mods from the mining vendor are not mining out 3x3

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#28692]
![image](https://user-images.githubusercontent.com/6778786/27410830-fd8db8ec-56b7-11e7-9931-d0361e6a9f3b.png)

**Comment by octareenroon91** [comment]
Yes, vendor gives the combat upgrade;
Sci gets the mining upgrade;
Tendrils drop the combo upgrade.

**Comment by Repukan** [comment]
Not a bug, Mining mods are damage only

**Comment by octareenroon91** [comment]
I'm not happy with it either, but this isn't the right _forum_ to discuss this.

**Comment by Kromgar** [comment]
The names are pretty fucking shite then

**Comment by BeeSting12** [comment]
@ChangelingRain 
The AOE mod is named "AoE Damage Mod," which describes its function pretty well. Don't think there's an issue here.

**Comment by Repukan** [comment]
@KorPhaeron this can be closed, Kromgar is just a tard.
