### ISSUE TITLE
Detective's Gun Disappearing

### ISSUE THREAD

**Issue by RandolfTheOkay** [tgstation/tgstation#28699]
[Note]: #28344, #28616, #28696 

Det's gun, regardless of skin, loses its sprite and becomes invisible when reloading, and sometimes when emptying the chamber/firing the last bullet in its chamber.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/40de86de351f4ccc01a2107cd8a052b143936eee/code/game/objects/objs.dm#L219

When reskinning the object, this returns choice instead of what choice is associated to. Probably has something to do with it.

**Comment by ExcessiveUseOfCobblestone** [comment]
oh poo something is setting the icon back each time
