### ISSUE TITLE
ERT Team can be any race through a simple trick

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#28698]
1. Spawn as ERT(I think you need Amber access or higher)
2. Walk North, should be a bathroom or library backroom near you
3.Interact with magic mirror, click "race"
4.Oh god
5.Oh god why are military synths here
6.Bluespace Golem ERT is a thing???
7.WHERE THE HELL WAS CENTCOMM HIDING THIS

**Comment by ShizCalev** [comment]
feature

**Comment by Armhulen** [comment]
you can't actually do this, i think

there's a centcom id and an ert id

**Comment by DoctoreMad** [comment]
I barred into that place as a medical officer last round.

**Comment by DoctoreMad** [comment]
Aren't there multiple ERT alert levels? Maybe red alert can't enter but amber can.

**Comment by Shadowlight213** [comment]
@armhulen ert commander actually has full centcom access. Don't ask me why, but it's a thing.
It's more of a flaw in centcom's design. On bay, their ert is seperated from the rest of cc by blast doors that can only be opened from inside centcom.

**Comment by Durkel** [comment]
Learn this one neat trick I used to powergame.

ADMINS HATE IT!

**Comment by Steelpoint** [comment]
Anyone with a RCD or hacking tools can break into anywhere on Centcom. 

Best solution is to remove the mirror.

**Comment by banthebantz** [comment]
mirror is fun

**Comment by FantasticFwoosh** [comment]
You could just downgrade the mirror instead so you can still racechange to XYZ roundstart races, say if you wanted to become a lizard instead.

**Comment by Steelpoint** [comment]
ERT and DS being Humans was a intentional game play decision.
