### ISSUE TITLE
revhead flash stun times

### ISSUE THREAD

**Issue by Ausops** [tgstation/tgstation#28702]
[Note]: #28670: 'Makes oldchat show while goonchat loads, sends preload messages there.' by MrStonedOne at commit 7a1393
Based off origin/master commit: 58c054

Revheads flashing someone will make them go down for a really long time, more so than a normal person flashing someone.

**Comment by BeeSting12** [comment]
actually, i'm pretty sure a lot of stuntimes are broke. from after a cult round:

OOC: Jaraxxus: >when you spend 20 minutes just sitting around editing peoples variables to unstun them
