### ISSUE TITLE
oddyseus interface updating.

### ISSUE THREAD

**Issue by SgtxRootbeer** [tgstation/tgstation#28700]
the oddyseus' reagent synthesizer interface auto-updates whilst one tries to remove (strangely, not add) chemicals from the list of reagents to synthesize.

for example, I have bicaridine and kelotane as synthesizable reagents, and I am synthesizing bicaridine, but i wish to start synthesizing kelotane. if i de-select bicaridine, and wait too long before pressing the "apply settings" button, then the bicaridine option will re-select itself.

this is annoying for obvious reasons.

**Comment by msgerbs** [comment]
Does this still happen? IIRC mechs have been completely reworked since this was submitted.
