### ISSUE TITLE
Chat gets stuck every time a new round starts

### ISSUE THREAD

**Issue by Charmisokay** [tgstation/tgstation#28709]
Whenever a round ends and I am online, the chat gets stuck on the following message:
![image](https://user-images.githubusercontent.com/25822752/27440895-50e3f97a-576c-11e7-8da9-7a41b37f49b2.png)

I can still log on and play, but the chat message will not go away and I cannot scroll away.

**Comment by ClosingBracket** [comment]
I've noticed that reconnecting from File -> Reconnect will not fix the problem, but closing BYOND completely and (waiting 30 seconds for an ad of course) rejoining will oddly enough.

**Comment by MrStonedOne** [comment]
This should have been fixed in #28750

@ClosingBracket @Charmisokay do you still see this bug?

**Comment by ClosingBracket** [comment]
@MrStonedOne The issue's been resolved on my end.
