### ISSUE TITLE
Wormhole Jaunter portals are not able to be interacted with and last forever

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#28718]
![image](https://user-images.githubusercontent.com/6778786/27457849-3bea7906-5774-11e7-8f6b-431a3ccc1632.png)

![image](https://user-images.githubusercontent.com/6778786/27457872-518acbb2-5774-11e7-94eb-14d28ea658c9.png)

@kevinz000 

I know you redid portals

**Comment by Cyberboss** [comment]
@kevinz000 did your pr fix this?

**Comment by kevinz000** [comment]
@Cyberboss i believe so

**Comment by Cyberboss** [comment]
#28706
