### ISSUE TITLE
The SM sliver doesn't "work" as intended

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#28710]
I'm not sure how the SM silver when it's in the extraction tongs is exactly supposed to work, but I'm pretty sure it's not supposed to be a silent better super matter sword that can dust people in one hit, destroy walls and doesn't irradiate you at all. I was able to go on a killing spree of about 8 people before I was stopped just by tapping them with it and I suffered no downsides. Fix pls

**Comment by bgobandit** [comment]
yeah this is unintended

**Comment by Jarektheraptor** [comment]
RIP
