### ISSUE TITLE
Malf doomsday device is still possible to use, even though it's never the AI's objective.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28712]
The malf AI objective to nuke/takeover the station has been removed a long time ago, yet it is still possible to go all doomsday on people. Shouldn't it ONLY be available under the circumstances where an admin changes the AI's objectives to include nuking everyone?

Furthermore, destroying the station with a nuclear device (admin objective) is apparently not connected to the AI nuking the station, and will fail the objective even if it DOES nuke the station.

**Comment by Sligneris** [comment]
I was under impression that it was intended to remain as an option for the AI.

**Comment by Xhuis** [comment]
Yes, I believe this is intentional. When I was refactoring malf AI code, the option was there regardless of the AI's objective.

**Comment by KorPhaeron** [comment]
It's just meant to be a fun optional stunt for the AI to pull.

It will almost always finish the ais other objectives as well
