### ISSUE TITLE
Whiteship no longer counts as an escape.

### ISSUE THREAD

**Issue by JusticeGoat** [tgstation/tgstation#28719]
At round end i had noticed that it blue texted me rather then escaping, i suspect it might have to do with the new travel zlevel.
Happened on bagil about a day ago

**Comment by Sligneris** [comment]
> blue texted

??

**Comment by JusticeGoat** [comment]
@Sligneris "Marooned" its what you get for living yet not making it on the escape shuttle.

**Comment by Iamgoofball** [comment]
Well, you are technically lost in space.

**Comment by DoctoreMad** [comment]
A spaceship that can travel around is lost in spess??

**Comment by AnturK** [comment]
Ugh, forgot this was a thing.
