### ISSUE TITLE
Entering an invalid command into the command bar will break goonchat until client restart

### ISSUE THREAD

**Issue by ClosingBracket** [tgstation/tgstation#28717]
Entering anything that is not a recognized command into the command bar breaks goonchat bad until you completely restart your client. The fallback chat doesn't function or update at all. Reconnecting from within the client will not fix this.

Example below:
http://i.imgur.com/aSioYy5.gifv

**Comment by Cyberboss** [comment]
what. the. fucking. fuck

**Comment by ClosingBracket** [comment]
I feel it's also important to add that I only started experiencing this bug today (or yesterday, depending on where you live I guess), so it must be something recent.

**Comment by Cyberboss** [comment]
@MrStonedOne

**Comment by MrStonedOne** [comment]
omg byond, why you do dis?

I'll have to put a bug report up and get byond's feedback, for now i can make the alt window stay up to date always.

**Comment by MrStonedOne** [comment]
http://www.byond.com/forum/?post=2200940

This is a byond bug that has been already fixed.

Update your byond and confirm.

**Comment by ClosingBracket** [comment]
Updated to .1385 and I can confirm the bug is fixed. Thanks y'all!
