### ISSUE TITLE
Yellow Glow form Ambrosia Gaia is really wonky

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#28729]
The tray beeps yellow once when converted, then goes back to normal blue water, for starters. Then it beeps back into yellow when being harvested, sometimes. It only really stays yellow when there's no plant in the tray.

What is the point?

**Comment by Kromgar** [comment]
I had a gatfruit in one

Just kept fucking beeping yellow  every minute

**Comment by FantasticFwoosh** [comment]
The changing of states is not continuous, it should be on in the background so i guess someone deleted some overlaying thing that was there previously.
