### ISSUE TITLE
You can attack blobs that are behind other blobs diagonally

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#28722]
Basically, if you're the guy circled in red, you can attack the strong blob with the blue X on it.
This happens with all blob parts.
![sybil outpost 2014-02-06 142440](https://f.cloud.github.com/assets/3886584/2102891/d8ba6cb8-8f64-11e3-9d87-2413cb1f3593.png)

### **#2664 except it was never actually fixed**

**Comment by ChangelingRain** [comment]
@Razharas

**Comment by lzimann** [comment]
That's an old picture

**Comment by ChangelingRain** [comment]
Yes but it explains the issue concisely and I didn't want to bother with a new picture; I did actually test the fucking thing, yes.
