### ISSUE TITLE
You can flip up the welding helmet while welding and avoid eye damage

### ISSUE THREAD

**Issue by dannno** [tgstation/tgstation#28728]
By flipping the helmet down, starting to weld, and flipping it back up, you can weld without damaging your eyes while also foregoing the reduced vision of the helmet.

**Comment by Sligneris** [comment]
Can't we just make it so that they eye damage gets applied over time, each time with eye protection check, instead of the instant you click on anything with a lit welder, anyway?

**Comment by dannno** [comment]
That would make more sense.

**Comment by ShizCalev** [comment]
dupe #15472

**Comment by AnturK** [comment]
Duplicate of #15472
