### ISSUE TITLE
Cortical borer + changeling +monkey devolve = death?

### ISSUE THREAD

**Issue by Anundeadguy** [tgstation/tgstation#28731]
[Note]: # Based off origin/master commit: cb4ca0

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

Uh, roundstart I was a traitor, but I traded to be a borer. I jumped into a ling, and we had fun for a while, but eventually sec caught on. at which point, she got handcuffed, and when she monkied to escape, we both got insta-ghosted.

**Comment by Kromgar** [comment]
Wait YOU BOTH DID?

Oh god

**Comment by Cyberboss** [comment]
> # b o r e r s

**Comment by nicbn** [comment]
Funniest bug ever



No
It isn't

**Comment by Armhulen** [comment]
hi i'd like uuuuuuuuuh Bodyless ling and a 2 liter coke
