### ISSUE TITLE
AI core can catch on fire, yet the fire is not visible.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28737]
This means that running into the core during this will set you on fire, with no visual tell.

**Comment by Xhuis** [comment]
Assuming that you're referring to the AI core _mob_, I can't reproduce this. If you're referring to the AI core _area_, that was likely an atmos bug in general, or something else lit anyone walking in there on fire. (That sounds dumb, but superheated air _might_ do it? I'm not sure how atmos works entirely)

**Comment by Cyberboss** [comment]
kev fixed this
