### ISSUE TITLE
People are slipped everytime they open a locker with soap on it

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#28733]
Step 1.Stuff high level security member into locker
Step 2.Add soap
Step 3.Close/Open
Step 4.**What the flying FUCK are you people smoking?**

**Comment by XDTM** [comment]
Add a check for same turf on forceMove

**Comment by ClosingBracket** [comment]
I always thought this was a feature

**Comment by Marflowerose** [comment]
For added hilarity, put glass shards, honking items and corpses on it to completely overwhelm the audio system

**Comment by DoctoreMad** [comment]
@ClosingBracket cuffing someone without cuffs or wait time is a feature?

**Comment by ClosingBracket** [comment]
yes.
see: (closed) issue #23197

**Comment by DoctoreMad** [comment]
**I will close this but know that this is a horrible feature that lets anyone stunlock anyone with a locker and a soap**

**Comment by ClosingBracket** [comment]
*shrug
