### ISSUE TITLE
Botany can cause a fair bit of lag by spamming loads of reagent reactions all at once.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28738]
![](http://i.imgur.com/zlvm4vy.png)

I had reed glover here help me with this. If you try and have multiple reactions at once in a plant, and also have maximum plant yield happen, and then harvest several of these trays at once, it gets quite laggy.

**Comment by MrStonedOne** [comment]
@Iamgoofball reaction subsystem when?

**Comment by Iamgoofball** [comment]
more like chemistry subsystem when

**Comment by Iamgoofball** [comment]
someone better at optimization will have to do it

**Comment by Cyberboss** [comment]
Closing in favor of other issue
