### ISSUE TITLE
Engineering Modular Console Not Functioning

### ISSUE THREAD

**Issue by Steelpoint** [tgstation/tgstation#28745]
I noticed in game and on my offline code that the modular engineering console (one in the top right of power storage on boxstation) is non-functional, in that none of the modular components (hard drive, etc) spawn. 

Spawning in a new computer in game works, but the one's set down at round start don't seem to work.

**Comment by GunHog** [comment]
This is also happening with the RD's modular console.

**Comment by DaxDupont** [comment]
And the ones on the brig
