### ISSUE TITLE
Weed crate scythe doesn't cut kudzu in efficient ways

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#28743]
![000](https://user-images.githubusercontent.com/29125781/27489413-e0739cea-5810-11e7-95f7-da8fe1021071.png)

Orange is where it was clicked. Red is what was cleared. You can't clear the orange block, by the way.
Being able to cut only in squares is fucking mad.

**Comment by Gouty** [comment]
This could be intentional, have you seen a scythe in use? you use sweeping motions, so you cut a lot around you, but not underneath you

**Comment by DoctoreMad** [comment]
If its intentional its pretty horrible because it means you can't REALLY get rid of the kudzu invasion. Kudzu spreads in a block around it, cutting that block it grows around only means it can spread again in a few seconds.

**Comment by Kromgar** [comment]
.... Why don't you stand south of where the kudzu is and keep cutting north?

**Comment by DoctoreMad** [comment]
Kromgar: What?

**Comment by ExcessiveUseOfCobblestone** [comment]
That almost looks intended lol.
