### ISSUE TITLE
Elite syndicate hardsuits loaded through templates lack most of their functions.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28757]
This one is made via a template, then loaded in the game:
![](http://i.imgur.com/X45LIBW.png)

And this one is spawned in game via the spawn command.
![](http://i.imgur.com/saMQqfi.png)

Main problem is that as a result of this, you can't even toggle the helmet mode, which is what determines if it's space proof or not.

**Comment by KorPhaeron** [comment]
@cyberboss

Initialize problem I think

**Comment by WJohn** [comment]
Seems to also extend to SSU suits, they're not initialized and cannot be picked up. Even if you do give em initialized 1, they still won't be possible to interact with, and won't be giving you a helmet to toggle on or anything.

**Comment by WJohn** [comment]
This is the case for any hardsuit loaded at all through template (load template or shuttle manipulator), as it turns out.
