### ISSUE TITLE
Item inhand sprites sticking

### ISSUE THREAD

**Issue by Mark9013100** [tgstation/tgstation#28759]
[Note]: # (Please enter the commit hash and active testmerge numbers from the "Show Server Revision" verb if you can. If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

Server revision compiled on: 2017-06-23

The following pull requests are currently test merged:
#28556: 'Virology Rework: The Thresholdening' by XDTM

Based off origin/master commit: 69b8a6

I've been noticing this for the past week or so, that inhand sprites, such as guns, tools, etc. will sometimes fail to go back to the empty hand, resulting in it looking as if you have the item still equipped.

Screenshot:

![](http://i.imgur.com/M1znkhh.png)

**Comment by WJohn** [comment]
We've had this issue reported like 4-5 times already.

#26968
