### ISSUE TITLE
Weird ass glitch w/ pre round

### ISSUE THREAD

**Issue by oogtarded** [tgstation/tgstation#28756]
[Note]: # An admin told me to report this, but an admin was spawned in pre round on the SS13 screen. My game froze, so I left and rejoined and it spawned me there with him without any admin interaction. I did not have any clothes or items. This is all I know that happened
[Admins]: # Not sure, sorry

**Comment by AnturK** [comment]
Runtime in roundstart code, impossible to reproduce without more information or round id.
