### ISSUE TITLE
Opening the maintenance panel of an emitter will cause it to briefly turn to the east.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28758]
If an emitter is facing north, south, or west, then opening the panel will cause it to briefly face the east, then back to where it was facing.

ONLY opening does this, closing has no effect on its direction.

**Comment by Jalleo** [comment]
Can it fire east when this occus?

**Comment by WJohn** [comment]
Nope.
![](http://i.imgur.com/vBOIHOJ.png)

**Comment by Jalleo** [comment]
Then it could be a visual issue only. @Anturk

**Comment by SpaceManiac** [comment]
Visual only, the `emitter_open` state in the icon file only has an east sprite. It's set by the call to `default_deconstruction_screwdriver` in `attackby`. The emitter then changes back to the `emitter` state in `update_icon` next time `process` is called.

**Comment by SpaceManiac** [comment]
The actual bug here got fixed at some point. The emitter will still always face east when open but that's a sprite issue only.

**Comment by kriskog** [comment]
This is fixed
