### ISSUE TITLE
Bad mapping on roundend pod station area

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#28761]
![overwolf_2017-06-24_17-21-39](https://user-images.githubusercontent.com/28678854/27510084-be02f164-5901-11e7-85d4-57c29dec99fc.png)

ya see

**Comment by DoctoreMad** [comment]
There's no sprite for the wall that would look proper there, I believe.

**Comment by TrustyGun** [comment]
actually this is a pretty easy fix. you just need to change the wall to the nodiagonal subtype I believe

**Comment by WJohn** [comment]
Yeah, diagonal smoothing walls come in many variations to prevent them from doing this exact thing.
