### ISSUE TITLE
Upgraded industrial welding tool inhand sprite inconsistency

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#28768]
When facing to the left or right with your character, the inhand for the upgraded industrial welding tool is inconsistent when turning it on to off or vice versa. The issue is that the welding tool appears to extend when it's on. Pictures are worth a thousand words so here's two:

Off:
https://file.house/C8h9.png
On:
https://file.house/HppY.png

**Comment by Jalleo** [comment]
Nice essay. 
Issue is flame and sprite beind moved fowards.

**Comment by Lexorion** [comment]
It's in the wrong hand when you turn it on. Fixing this in a minute.
