### ISSUE TITLE
Adminhelping with a ticket open

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#28763]
If you adminhelp with a ticket open, it will give you a box that says you already have a ticket open, is this for the same issue. Here, you can select yes/no. No will open a ticket and show you your ahelp in the chat box while clicking yes possibly does nothing at the worst and at best doesn't show your PM in chat.

**Comment by lzimann** [comment]
I've tested this and clicking yes does send the ahelp, but only visible to admins. Clicking no will just close the old ticket and open a new one(intended).
This is just lacking a proper feedback.
