### ISSUE TITLE
Template spawned shuttles do not seem to grab plating (and the objects on those) when they fly.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28767]
![](http://i.imgur.com/v96yNYI.png)

![](http://i.imgur.com/d94CKHi.png)

These are both custom made shuttles, they seem broken now, even though they used to work fine before.

**Comment by Jalleo** [comment]
@Anturk maybe?

**Comment by AnturK** [comment]
That seems like you just set the base turf type of docking port to wrong value

**Comment by WJohn** [comment]
The turf type of the docking port these two land at that causes this is in fact plating. This might not be so much shuttles causing this but rather the turf type they're trying to depart from.

**Comment by ninjanomnom** [comment]
This got fixed by #30261 from what I can tell
