### ISSUE TITLE
Vault's Bank Machine won't accept coins

### ISSUE THREAD

**Issue by Aurafag** [tgstation/tgstation#28807]
Still accepts bills, some merge must have broke it in the past. Reporting for formality.

**Comment by ShizCalev** [comment]
assuming #28505

**Comment by ShizCalev** [comment]
intentional with #27252

**Comment by nicbn** [comment]
I don't think any ATM accepts coins btw.

**Comment by Aurafag** [comment]
Then the values can be fixed instead of remove the ability to deposit.

**Comment by Cyberboss** [comment]
Working as intended
