### ISSUE TITLE
One package wrapper, infinite carboard tubes

### ISSUE THREAD

**Issue by nicbn** [tgstation/tgstation#28804]
Take a wrapper
Select your empty hand
Click the wrapper two times
A cardboard tube drops
Repeat infinitely
Profit

![1](https://user-images.githubusercontent.com/20824501/27512834-9e4099de-5925-11e7-84e9-736f46973849.png)

**Comment by Jalleo** [comment]
How are cardboard tubes useful?

**Comment by WJohn** [comment]
doesn't matter, still a duping glitch.

**Comment by RocKeD** [comment]
I'm curious what they're used for as well.
