### ISSUE TITLE
Wizard time stop is broken

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#28806]
https://file.house/c2Au.png

1. That was placed there five minutes ago and it hasn't disappeared.
2. It was not effective even immediately after it was placed.

Server revision compiled on: 2017-06-23

The following pull requests are currently test merged:
#28556: 'Virology Rework: The Thresholdening' by XDTM

Based off origin/master commit: 69b8a6

**Comment by Armhulen** [comment]
The only issue I see in that picture is the borer

**Comment by DoctoreMad** [comment]
>    1.That was placed there five minutes ago and it hasn't disappeared.
    2.It was not effective even immediately after it was placed.

**Comment by Armhulen** [comment]
that too i guess

**Comment by Armhulen** [comment]
but borers really are cancer

**Comment by Tacolizard** [comment]
~~timer bug I think~~ uh no its a new feature of time stop it just stops time on its animation

**Comment by Xhuis** [comment]
I fixed this but I forgot to close the issue. You can safely close this now.
