### ISSUE TITLE
Some machines drop one stack of wire instead of one cable piece when deconstructed

### ISSUE THREAD

**Issue by nicbn** [tgstation/tgstation#28810]
Heater and freezer are exceptions because #28577.
Don't use the same workaround as #28577, it causes #28808.

**Comment by Supermichael777** [comment]
a list of the machines would be nice could you add that?

**Comment by nicbn** [comment]
Haven't tested each one of them, but it's in the req_components (/obj/item/stack/cable_coil = 1).
Don't change /obj/item/stack/cable_coil = 1 to /obj/item/stack/cable_coil/one = 1 or you'll have #28808.
Also #28577 needs to be reverted and the same workaround applied.

**Comment by nicbn** [comment]
I think that's a dup of #28340, but I'm not sure if it only happens at round spawned machines, gonna test it later.

**Comment by nicbn** [comment]
Can't reproduce anymore
