### ISSUE TITLE
Delta has useless teleporter console

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#28818]
![0uselessnote](https://user-images.githubusercontent.com/29125781/27516638-097ed74c-5994-11e7-8088-cbacfabbee12.png)

What is the teleporter here for

**Comment by RandomMarine** [comment]
So does meta and box and probably other maps

**Comment by Anonmare** [comment]
Meta has it too. It's for rounding out the number of consoles on the bridge and A E S T H E T I C S
