### ISSUE TITLE
[Rusted station] Beta station access leaks oxygen out

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#28824]
The door labelled "Beta station access" leaks oxygen out when opened. Can we not have more atmospheric drains? Oxygen is scarce enough on that station as is.

**Comment by DoctoreMad** [comment]
Actually I should just request more oxygen sources in the station in general

**Comment by Cyberboss** [comment]
@Steelpoint

**Comment by DoctoreMad** [comment]
While we are here can you add a insulated glove to the ship
Like oh god what the fuck did they not invent insulated gloves during this station's time?

**Comment by Steelpoint** [comment]
I'll add some insulateds to engineering.

I can't see why oxygen is leaking when Beta Access opens so I'll check in game. I should note that oxygen becomes a minor issue once you fully pipe up the Beta Station atmospherics and link it to the station proper.

**Comment by ShizCalev** [comment]
@Steelpoint Pretty sure there was an issue report on here somewhere that states that blastdoors create vacuums under them if they're closed at roundstart or something along the lines of that.

**Comment by DoctoreMad** [comment]
>Beta Station atmospherics

You mean that singular air canister that the engineer usually loses because of a blast?
I am very panic

**Comment by ShizCalev** [comment]
back in my day you used to have to bring an air canister with you when space exploring /s

**Comment by PraiseRatvar** [comment]
@Steelpoint

Has this been fixed? If so, tag Dorsisdwarf or a maintainer to close this (or ask someone on coderbus)

**Comment by Steelpoint** [comment]
This was resolved @Dorsisdwarf
