### ISSUE TITLE
Rusted Station players show up as "assistant" in MIND

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#28827]
At least, I think that's what causes them to show "Job:Assistant" when a admin offers the mob to someone. Any help with that?

**Comment by AnturK** [comment]
It's the default assigned role.

**Comment by DoctoreMad** [comment]
Well, it makes ghosts want to not take the role.

**Comment by PraiseRatvar** [comment]
@Steelpoint 
also call it abandoned station!!!

**Comment by Steelpoint** [comment]
I'll investigate the issue later, and I'll rename the station as well.

**Comment by YPOQ** [comment]
Fixed by #29044
