### ISSUE TITLE
No end of round readout for rounds ended by restart votes

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#28835]
In the rare event a restart vote passes (which usually happens during a lowpop round when there are no admins and someone is murderbonering) the end of round readout isn't printed to chat so nobody knows the antags or their objectives, which is useful to know to verify nobody was griefing. Probably should print either way just in case an antag was able to finish their objectives before the restart vote passed.

**Comment by SuperNovaa41** [comment]
intended
