### ISSUE TITLE
Traitor AIs can lose their Law 0 and their traitor abilities whilst retaining their malf module.

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#28845]
I had a round where a traitor AI somehow managed to lose their law 0, objectives and the ability to hack cyborgs whilst retaining their malf modules. 

Next round, I spawned myself as a traitor AI and connected an AI shell and a cyborg to me. After bouncing in the AI shell and back to my core, I accessed the robotics console and found that I could not hack any of my connected shells or cyborgs. I then found that I could overwrite then remove the Law 0 via the OneHuman board and then using the purge board.

**Comment by Anonmare** [comment]
It appears that bouncing between an AI shell does something strange to the AI's mind as its faction was also reset to Loyal

**Comment by ChangelingRain** [comment]
@GunHog @Shadowlight213

**Comment by DoctoreMad** [comment]
conditions seem eerily like #28422
