### ISSUE TITLE
Borgs being unlinked doesn't update in status

### ISSUE THREAD

**Issue by club5000205** [tgstation/tgstation#28852]
[Note]: # (Please enter the commit hash and active testmerge numbers from the "Show Server Revision" verb if you can. If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

The past several rounds i have played as an AI and have had roundstart borgs. Due to some circumstance or another, that borg would become unlinked. I wouldn't know about this at all until they tell me, as the status screen still shows them as connected.

**Comment by Repukan** [comment]
Is it randomly or do they get unsynchronized by shitter roboticists cutting the link while replacing batteries.

**Comment by GunHog** [comment]
https://github.com/tgstation/tgstation/blob/master/code/datums/wires/robot.dm#L62
Is missing code for removing the borg from the AI's connected borgs list. Very simple fix.

**Comment by Anonmare** [comment]
Also as a secondary issue, if there's multiple AIs, pulsing the AI connection gives the cyborg the option to re-sync to an AI of its choice and not the roboticist's.

**Comment by Supermichael777** [comment]
shit i'm going to fix these.

**Comment by Supermichael777** [comment]
the reported bug is super easy(alredy done). the secondaryt issue im going to have to make every pulse pass its user and make the function randomize if its null
