### ISSUE TITLE
Evac rate is zero while plenty of people are on the shuttle

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#28869]
Round: https://atlantaned.space/newSS13tools/round.php?round=72473
![dreamseeker_2017-06-27_13-08-43](https://user-images.githubusercontent.com/17237624/27584890-3bd2fde8-5b3a-11e7-93be-c1d0efc45b19.png)

**Comment by AnturK** [comment]
Bluh, probably my fault.
