### ISSUE TITLE
Box station has a fan in engineering

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#28862]
![overwolf_2017-06-26_23-47-07](https://user-images.githubusercontent.com/28678854/27564266-6c6e5de2-5ace-11e7-8338-e44537431588.png)
The left airlock in the supermatter area has a fan while the right one doesn't.

**Comment by WJohn** [comment]
I'm pretty sure these are actually obsolete leftovers from the singulo/tesla engine, when engineers so frequently made their way out to space every round that a fan would be necessary to prevent it from depressurizing most of engineering every time they left to set the engine up.

Could do with their removal entirely.

**Comment by PraiseRatvar** [comment]
Then the closets would just float out of space because airlocks n' stuff suck. can we get a removal of the those closets or add fans to both because no one even uses those airtanks.

**Comment by Penguaro** [comment]
You can just use a wrench on the closet to bolt it in place.

**Comment by Cyberboss** [comment]
Closets need to be anchored, fan needs to be removed
