### ISSUE TITLE
Jumpsuits on the floor only showing pocket protector

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#28864]
server vers; https://github.com/tgstation/tgstation/commit/df10933abc4b157dbb2adb3edd630a55ddd44bf7
testmerge; https://github.com/tgstation/tgstation/pull/28750

Drop jumpsuit on floor
Alt click to bring up tile inspect tab

![3ledpmr](https://user-images.githubusercontent.com/6209658/27569133-e6104a9e-5ac3-11e7-8c84-cb9ceee328e1.png)

**Comment by PraiseRatvar** [comment]
i /think/ this happened to medals as well so only medals show up but im probably wrong

**Comment by Couls** [comment]
No longer an issue on browser panel
