### ISSUE TITLE
Strange plants can make reagent

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#28865]
strange plants can make a chemical known as reagent. Isnt this supposed to be the reagent base and is not supposed to be ingame at all?

**Comment by Tacolizard** [comment]
kek

**Comment by FantasticFwoosh** [comment]
You should rename the PR so its clear what the problem is, it would be easy to write off this issue report.

**Comment by kevinz000** [comment]
i don't think this is a bug anymore as the get_random_reagent_id uses subtypesof().
@Cyberboss
