### ISSUE TITLE
Changelings do not do well with being turned into a monkey and then a human.

### ISSUE THREAD

**Issue by Darkgenerallord** [tgstation/tgstation#28863]
If a changeling is turned into a monkey and then a human via genetics, all their organs disappear. Tongue/Lungs/Heart/Brain. This leads to their rather swift death. If you use it on a human, this doesn't occur.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by optimumtact** [comment]
don't do that then

**Comment by SgtxRootbeer** [comment]
Hidden ling check

**Comment by LaharlMontogmmery** [comment]
Ho dear.

Check ASAP, else we have a new meta check on our hands.

**Comment by Penguaro** [comment]
You ever look at these and wonder, "What could possibly have prompted that series of events in a round?"
