### ISSUE TITLE
Emag doesn't unlock products on vending machine

### ISSUE THREAD

**Issue by ninjablooper** [tgstation/tgstation#28878]
The emag used to unlock products on most vending machines, but now it doesn't do anything except show the message that it unlocked products.

**Comment by XDTM** [comment]
Do you mean locked by access or contraband? Emags remove access but dont open contraband

**Comment by Anonmare** [comment]
Emagging a cigarette machine lets you buy syndismokes from it

**Comment by Xhuis** [comment]
From vending.dm, line 509:

``` DM
if((!allowed(usr)) && !emagged && scan_id)	//For SECURE VENDING MACHINES YEAH
	to_chat(usr, "<span class='warning'>Access denied.</span>"	)
	flick(icon_deny,src)
	return
```

Not a bug! This is intentional. All it does is remove access requirements.

**Comment by DoctoreMad** [comment]
@optimumtact I read something about this thing called "Book of Job", and I think it was christian. I haven't actually read it other than the title, but I think Jesus persuades you to do your job on that one.

**Comment by optimumtact** [comment]
Luckily I'm anglican
