### ISSUE TITLE
Goonchat prepends and appends spaces to every radio message

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#28876]

**Comment by factoryman942** [comment]
These spaces are slowly driving me insane

**Comment by fludd12** [comment]
Bug still present?

**Comment by kingofkosmos** [comment]
Seems to happen on Windows 7 and not on Windows 10, correct me if I'm wrong.

Here's a pic on Windows 7:

![image](https://user-images.githubusercontent.com/5420151/63672295-54c54580-c7ea-11e9-8864-251e95f0272e.png)

Windows 10:

![image](https://user-images.githubusercontent.com/5420151/63672321-60b10780-c7ea-11e9-92a7-05eef5814d5c.png)

**Comment by kriskog** [comment]
Gone for me after 513, anyone else seeing them?

**Comment by kriskog** [comment]
Yeah seems to have been resolved. Closing, let me know if you still see this.
