### ISSUE TITLE
Goonchat has major lag issues when outputting many lines of text at once

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#28875]
^^^^

this makes it really easy to lag people, be it shooting shotguns, making a ton of reactions at once, or using a ton of radios to lag out every person wearing a headset.

One of the worst effects of this problem is viruses, if many people close together have a virus with a symptom like sneeze, they'll all sneeze at the same time, which in one case I saw caused multiple seconds of total lock-up lag.

**Comment by WJohn** [comment]
Ah, I assume that's the cause of #28738?

**Comment by MrStonedOne** [comment]
@PJB3005 any hints or tricks you could give us?

**Comment by PJB3005** [comment]
Curse at BYOND and bribe Lummox to implement CEF.

**Comment by MrStonedOne** [comment]
its likely to be how it updates the dom. I might have to add some batching to everything so it can just do multiple lines as 1 dom update. (likely on goon chat side, since i can do better resolution of timers)

**Comment by MrStonedOne** [comment]
I would need to get my slower laptop working again or otherwise reproduce this bug to see how the lag looks, and profile what routines DS is lagging in.

**Comment by tralezab** [comment]
HAH

**Comment by tralezab** [comment]
HAHAA

**Comment by tralezab** [comment]
WOOOOOOOO
