### ISSUE TITLE
ghosting while holding a plant resets your icon

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#28888]
what it says on the tin. the plant is no longer visible despite still being in the body's hand.

probably happens with other image overrides / add_alt_appearance's

![3lgg1np](https://user-images.githubusercontent.com/6209658/27613763-71adaba8-5b6b-11e7-99da-b753915b77fa.png)

**Comment by MrStonedOne** [comment]
@RemieRichards

**Comment by RemieRichards** [comment]
Haven't touched the system in a while, somebody refactored it into being part of datum HUDs, so it's probably an issue with that system.

**Comment by RemieRichards** [comment]
@Cruix you around?

**Comment by Cruix** [comment]
It is probably because ghosts are not reloading their huds when they are made. If that is the case, then everyone who is not a ghost will still see the alternate appearance.

**Comment by Cruix** [comment]
It is actually because /mob/dead/Initialize() does not call ..(), so observers do not get added to the list of who can see the alternate appearance.
