### ISSUE TITLE
katanas aren't given to ninjas anymore

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#28880]
traitor panel EQUIP button, I mean.

**Comment by Kromgar** [comment]
Aren't they an implant now?

**Comment by Armhulen** [comment]
no i know exactly why this is happening kor made the katana into a weapon/dash/katana path and so it doesn't find the OLD katana in equip

**Comment by PraiseRatvar** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
How did it even compile though if that is the case

**Comment by Armhulen** [comment]
:thinking: :thought_balloon: :crossed_swords:

**Comment by KorPhaeron** [comment]
I figured it out
