### ISSUE TITLE
Contributing.md "meet the team" is out of date

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#28883]
It lists Project Lead, Project Managers, and Maintainers.

We no longer have Project Managers and Maintainers have largely taken on their role

Does not list my snowflake title of Design Lead, the Issue Managers, or Art Director either

This has lead to some confusion with the merge process for some people

@tgstation/commit-access 

Anyone want to rewrite this? Particularly Cheridan?

**Comment by RemieRichards** [comment]
if we rewrite this can we also remove the names from the changelog :^)
I'm still bitter I missed out being in the changelog by like, a week, while miauw (who is now dead) gets to be on there, grrrr.
