### ISSUE TITLE
Narsie and ratvar won't fight anymore

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#28898]
Spawning both of them doesn't make them go near each other, and both of them bumping into eachother doesn't set off the battle.

@ChangelingRain @Robustin

**Comment by MimicFaux** [comment]
The only bit of confirmed Lore we have, and it doesn't work. What is this world coming to?

**Comment by Sligneris** [comment]
Nar-sie and Ratvar made peace with themselves and became a happy couple. It's canon now.

**Comment by Armhulen** [comment]
"I WANT TO BE INSIDE OF YOU."

**Comment by Xhuis** [comment]
I was the person who most recently poked Ratvar's code, so I'll take a look at this.

**Comment by Xhuis** [comment]
Shooooould be good once that PR's merged
