### ISSUE TITLE
Preferences that are set to enable by default don't enable by default.

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#28907]
For example, take my tooltips PR. in preferences.dm the var that enables tooltips is set to TRUE (`var/enable_tips = TRUE`) but ingame it starts off disabled. Something is disabling it. This same problem affects my reverb PR

**Comment by Cyberboss** [comment]
@MrStonedOne

**Comment by Tokiko1** [comment]
I'm fairly sure this is because it tries to load the preferences from the player config and sets them to null instead of looking up the default value.
