### ISSUE TITLE
I'm getting the update BYOND message on the latest BYOND beta

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#28909]
^^^^

only happens occasionally. i'm on the latest version of byond and on IE 11. fix chat button does nothing

**Comment by Penguaro** [comment]
Did you try turning it off and on again?

**Comment by Cyberboss** [comment]
@AnturK , this has to do with @MrStonedOne's goonchat changes

**Comment by AnturK** [comment]
Ohhh. I thought this was about the byond level notification.

**Comment by MrStonedOne** [comment]
That shows in the old chat when goon chat loads. if you can still see the old chat at that point, its because you have the output control stealing focus bug (likely) there might be other causes, but that is the most common.

**Comment by ShizCalev** [comment]
Still an issue?

**Comment by MrStonedOne** [comment]
Any time this happens now is a client side issue, so it might not be appropriate to have a bug report open, but i'll close this by re-wording the message to not mention upgrading since any version too old already fails default client version checking code.
