### ISSUE TITLE
Pandemic can't read non-advance virus immunity data

### ISSUE THREAD

**Issue by Repukan** [tgstation/tgstation#28904]
During a rev round where Fungal TB was released, I got infected and used a legion core to heal myself. Later on when I wanted to make a vaccine off my blood, no antibodies could be found in my blood.

**Comment by Cyberboss** [comment]
Working as intended I believe, it's the legion core that's curing you. Not any kind of resistance

**Comment by Repukan** [comment]
That's inconsistent then, isn't it? It heals you and makes you immune after, why wouldn't you be able to harvest antibodies?

**Comment by Repukan** [comment]
You're tearing me apart Cyberboss

**Comment by XDTM** [comment]
Clearing viruses with a fullheal intentionally does not give immunity, it needs to be cured in the proper way.

**Comment by Repukan** [comment]
It did give me immunity to Fungal TB for the rest of the round though. I was literally touching, in sneezing range and moving through the infected trying to heal them.

**Comment by Repukan** [comment]
You can use the legion core to get healed to and gain immunity to monki virus, red fever and so on, too.

**Comment by XDTM** [comment]
Actually, what i said is true for advanced viruses, but fungal TB isn't one. Dunno about the lack of vaccines though, i'll investigate.

**Comment by XDTM** [comment]
I may be wrong, but it could be that whoever reworked the pandemic forgot that resistance data is in type form for non-advance viruses and in id (string) form for advance viruses, and only considered the latter. So it wouldn't display immunities no basic viruses.

**Comment by XDTM** [comment]
Yeah, i'm confirming that. This means that stuff like pierrot's throat, magnitis, brainrot etc. won't be vaccinable until it's fixed, which involves somehow checking if the resistance data is an id or a type and treat it accordingly.

**Comment by RocKeD** [comment]
Cyberboss you're cracking my shit up with those labels LOL!

**Comment by KorPhaeron** [comment]
@XDTM 

Did you fix this?

**Comment by XDTM** [comment]
I don't think so, i'll give it a look when i'm able to.

For the record, this was introduced by whoever converted the pandemic to tgui, not in one of my reworks.

**Comment by vuonojenmustaturska** [comment]
@XDTM Did you possibly fix this in one of your recent changes?

**Comment by delaron** [comment]
Not fixed. Confirmed a problem still 10/25 

Fugal TB cured with suggested meds.
Vaccine data produces empty bottles
