### ISSUE TITLE
MySQL outage causing players unable to join

### ISSUE THREAD

**Issue by JamieH** [tgstation/tgstation#28926]
If the MySQL server goes down the "New Player Options" window won't load appear for anyone joining after the connection was down, admins have to manually reestablish the MySQL connection before it will show it again.

2 solutions (ideally both):
1 - fix the new player options requiring MySQL
2 - automatic reconnect to MySQL every 30 seconds or something when it goes down

❤

**Comment by Cyberboss** [comment]
@Jordie0608 @optimumtact @MrStonedOne

**Comment by MrStonedOne** [comment]
number 2 already happens, but it has a lockout after a certain number of failed attempts.

number 1 should already be the case, odds are something is runtiming now.

**Comment by MrStonedOne** [comment]
I see it, if the database is down, it's all good, but if its up but not working (such as a dead connection where byond side doesn't know its dead) it returns. likely a copy paste failure. easy fix
