### ISSUE TITLE
Plasmaman cook spawned in without his tank

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#28922]

**Comment by loqoman** [comment]
Way to reproduce?

**Comment by PKPenguin321** [comment]
I'd assume you sign up for Chef while having Plasmaman as your race

**Comment by loqoman** [comment]
Just tested this on Meta and Box, I spawned in with my plasma tank. Close the issue?

**Comment by Repukan** [comment]
@KorPhaeron tested and bug was not found again, I think this can be closed.
