### ISSUE TITLE
no gateway on pubby = no swarmer event

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#28923]
there's no gateway on pubby so the swarmer shell can't spawn.

credit to @Doctoremad for finding this

**Comment by Armhulen** [comment]
wow, pubby really is the best station

**Comment by PraiseRatvar** [comment]
@Armhulen 
SINGULO BEST ENGIN

**Comment by WJohn** [comment]
and this is why refraining from including a system, no matter how outdated or useless it seems, can break stuff. mapping a station can be needlessly limiting sometimes.
