### ISSUE TITLE
Ancient Station Transit Tube

### ISSUE THREAD

**Issue by evilkyle24** [tgstation/tgstation#28947]
When entering the transit tube on the ancient station, to get into Delta (The station with research) from Charlie, you will be slammed with a massive amount of overpressure, enough to inflict injuries up to and including bleeding. It knocked me from yellow into orange, not bleeding into bleeding.

**Comment by Tacolizard** [comment]
@Steelpoint

**Comment by Steelpoint** [comment]
This issue is being resolved in my latest PR: https://github.com/tgstation/tgstation/pull/28843

Its due to the airless tiles in the adjacent Charlie Station corridor getting into the tube.
