### ISSUE TITLE
Borgs can flood freon/plasma/etc with canisters

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#28948]
probably not a bug but why can they do it anyway???

i mean it makes a little sense if its an engiborg but ANY module can operate canisters and that seems just plain stupid

also yes im a lil salty from a round

**Comment by GunHog** [comment]
Not a bug.

**Comment by banthebantz** [comment]
Not a bug.

**Comment by Penguaro** [comment]
Not a bug. Consider that even if it is the wrong Module, a borg can be ordered to help a human. Think if they had an Air canister to refill a section that was depressurized. They're not going to say, "Sorry I'm a medical cyborg, does not compute." Can an evil cyborg open a canister? Sure. Can a good silicon following its laws open one? You bet.
