### ISSUE TITLE
Detectivs revolver goes invisible after one shot

### ISSUE THREAD

**Issue by gustufus** [tgstation/tgstation#28955]
dont know if it happens on the standard skin or any other skins, but on the peace keeper it turns invisible after one to two shots

**Comment by PKPenguin321** [comment]
Saw this happen live once and the icon state kept changing itself to things like "The Peacekeeper" or something, basically the full name of the custom skin complete with capitalizations and spaces. Probably a bug with some recent changes to the reskinning system
