### ISSUE TITLE
Becoming a swarmer doesn't make you on the endgame clockwork list?

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#28964]
![dreamseeker_2017-06-30_23-04-03](https://user-images.githubusercontent.com/28678854/27755639-d1ca85b8-5de8-11e7-9b20-aeb6e223d0ab.png)
i was clockwork person but not on the list? (one of the roundstart ones too)

I did become a swarmer twice but I also got severely drowned in holy water by the chaplain but I died in a radstorm before anything happened to me other than some lousy messages.

**Comment by Xhuis** [comment]
The actual deconversion done through the holy water doesn't seem to give you a message if you're unconscious. This seems like an oversight. You were likely deconverted before your death, but weren't informed. This isn't an issue!
