### ISSUE TITLE
Escape pods do not allow you to escape

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#28965]
If you board the escape pods to escape you will be marooned even though you were not actually marooned, Objectives will consider it a failure to escape, too, which is particularly annoying.

**Comment by PraiseRatvar** [comment]
i blame @AnturK because this https://github.com/tgstation/tgstation/pull/28870

unless i am 99% wrong but who knows

**Comment by AnturK** [comment]
Ugh. One moment
