### ISSUE TITLE
Modified syringe gun does 60 brute per syringe.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#28967]
I don't see why a syringe gun that's meant to turn people into monkeys should also be doing the same damage as a revolver.

**Comment by Repukan** [comment]
What the fuck

**Comment by DoctoreMad** [comment]
Get outta the way revolverboner, THIS is the true path...

**Comment by banthebantz** [comment]
Looks like someone forgot how inheritance works...

**Comment by Shadowlight213** [comment]
Feature
