### ISSUE TITLE
Missing cables on metastation armory windows

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#28972]
![2017-07-01_13-42-03](https://user-images.githubusercontent.com/28678854/27762126-425b8438-5e63-11e7-9e24-f9bad66b594a.png)
^ Highlighted by the blue rectangle, there are no cables there to stop people from breaking in.

**Comment by Armhulen** [comment]
not a bug

**Comment by loqoman** [comment]
On it

**Comment by DoctoreMad** [comment]
Map issue.

**Comment by loqoman** [comment]
This is Metastation. Not boxstation. Change the title

**Comment by PraiseRatvar** [comment]
im smart

**Comment by ShizCalev** [comment]
![3lqheq9](https://user-images.githubusercontent.com/6209658/27815359-93882308-6051-11e7-8e45-7b9582e7e62c.png)
close

**Comment by ChayseRamsay** [comment]
@ShizCalev He means the windows into the sub-armoury (with the flashers) from the warden's office.
