### ISSUE TITLE
Cant Rotate Doppler array

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#28979]
Cant rotate it

**Comment by Cyberboss** [comment]
It's not meant to be?

**Comment by Cyberboss** [comment]
They most certainly do not: https://github.com/tgstation/tgstation/blob/master/code/datums/explosion.dm#L254

**Comment by fizzle7** [comment]
Don't really know how dirs work in byond, but I think this says otherwise, since rotate modifies the dir and it AND checks the dir to be the same.
https://github.com/tgstation/tgstation/blob/24de3629fb75d8101b44b9d1bb4f1ebd01f73823/code/game/machinery/doppler_array.dm#L74

**Comment by Cyberboss** [comment]
Well that's pretty dumb

**Comment by ChangelingRain** [comment]
https://github.com/tgstation/tgstation/blob/24de3629fb75d8101b44b9d1bb4f1ebd01f73823/code/game/machinery/doppler_array.dm#L58

**Comment by banthebantz** [comment]
doppler arrays are always so fucking unreliable afaik
