### ISSUE TITLE
summoning ratvar when the shuttle has already arrived causes the text "The emergency shuttle will reach its destination in 1 minutes." to appear in chat, when shuttle transit time to centcom remains the same and all that is affected is the ETD timer, which is set to 1 minute

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#28984]

**Comment by octareenroon91** [comment]
>"The emergency shuttle will reach its destination in 1 minutes."

There's a generic announcement for any forced change of the current shuttle timer, but I'm not sure it would be used without admin intervention.

**Comment by Xhuis** [comment]
I can't reproduce this issue, leading me to believe that it was likely caused by an admin and not by Ratvar himself.

**Comment by factoryman942** [comment]
if it helps at all the shuttle had already docked at the station when the summon started, and its departure was blocked by the (non-summoning at that point) gate's presence

**Comment by Xhuis** [comment]
It does not; this is not an issue, as I have already stated. It was an admin action, and this can be safely closed.

**Comment by factoryman942** [comment]
Potassium
