### ISSUE TITLE
Roboticist PDA "Bots Access" broken

### ISSUE THREAD

**Issue by octareenroon91** [tgstation/tgstation#28985]
1. Be Roboticist
2. Use PDA
3. Click "Bots Access"
4. See nothing but refresh and return buttons.

**Comment by GunHog** [comment]
@ohnopigeons

**Comment by ohnopigeons** [comment]
Short term IC solution: Eject your cartridge, re-insert

**Comment by octareenroon91** [comment]
>Short term IC solution: Eject your cartridge, re-insert

Well I'll be.
