### ISSUE TITLE
Cloner bug with monkey dna injected players

### ISSUE THREAD

**Issue by OmegaShoots** [tgstation/tgstation#28987]
commit 5b66f2f1b2e7296c4df2842298f57afd2125490c

Getting cloned after being injected with monkey dna crashes the client and upon relog you can repick you occupation as if you were a new join.

Was injected with monkey dna in round id 72703, played the whole round up until about an hour in when I got sucked into an electrified grille (rip) and was getting put into the cloner.
When someone activated me dna to be cloned, my ghost appeared in the arrivals shuttle, and when I clicked Return To Body, the client froze and had to be restarted, which I was greeted with the normal join screen after reconnecting.

![snip](https://user-images.githubusercontent.com/29739454/27768100-4d3866b6-5ed9-11e7-9b71-d4bfe3f14229.PNG)

**Comment by Tacolizard** [comment]
were you able to reproduce this bug?

**Comment by kriskog** [comment]
Cant clone monkeys anymore.
