### ISSUE TITLE
Atmospherics bugs - Filters/mixers/that kind of stuff breaking randomly after pipes are disconnected from them

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#28990]
Basically I had mixers and filters that kept going on their initial settings even though I changed them. I believe it's because I disconencted their pipes while they were on. Unwrenching and wrenching (recreating) them and then setting the settings while pipes were connected already and the nturning them on did the trick. @duncathan

**Comment by Tacolizard** [comment]
this is really irritating.
