### ISSUE TITLE
Cant slip people wearing laceup shoes with clown pda

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#28996]
can slip with bananas not, pda

**Comment by Xhuis** [comment]
I'm not able to reproduce this. Laceup shoes are allowing people to slip on the PDA. Is it possible that the PDA wasn't a starter clown PDA, and just had the paint applied to it later on? That doesn't give it slipping properties; only the clown's starter PDA can slip people.

In short, this is either an edge case or a mistake on your part; I'm inclined to believe the latter.

**Comment by Cruix** [comment]
Were the laceup shoes just chameleon noslips?

**Comment by golfer45** [comment]
It was a starter pda. Tested twice on two different rounds. On two different bartenders. Both times clown pda could not slip laceup shoes but bannana could. Both rounds I tested clown pda could slip people wearing all other shoetypes that I found.

**Comment by BeeSting12** [comment]
you sure it wasnt noslips and you just got unlucky?

**Comment by octareenroon91** [comment]
The PDA slip uses the following invocation, assuming mob has shoes.
`                if(M.slip(0, 6, src, NO_SLIP_WHEN_WALKING))`

Banana slip has no such filter. We'll need to test in an isolated environment, but it's realistic to suppose that both bartenders were walking.

**Comment by Xhuis** [comment]
I did some testing with this. I slipped with the bartender outfit equipped while running, but walking resulted in no slip, implying to me that they were walking.

**Comment by Tacolizard** [comment]
it could be that they were wearing chameleon noslips.

**Comment by Cyberboss** [comment]
Seems to be chams
