### ISSUE TITLE
You can only be infected with one disease at a time

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#29000]
I know this is intentional for advanced diseases, but this seems to apply to ALL diseases, even the non viro ones.
Someone had pierott's throat, and I attempted to add the cold to them. The virus would not be added. They could not be infected until the first virus cleared.

**Comment by Iamgoofball** [comment]
GODDAMN IT

**Comment by XDTM** [comment]
I must've botched something and made infection impossible for multible base viruses as well, but i don't know where

**Comment by Shadowlight213** [comment]
Oh wow this was a get. Darn.

**Comment by KorPhaeron** [comment]
@XDTM 

You fixed this right?
