### ISSUE TITLE
When you examine the cult rune that spawns in lavaland you crash.

### ISSUE THREAD

**Issue by JusticeGoat** [tgstation/tgstation#29018]
latest Server revision compiled on: 2017-07-03 60a0c8

When you examine the rune that spawns round start sometimes in lavaland it causes a client crash.

**Comment by Tacolizard** [comment]
were you able to reproduce this issue, and if so, how many times?

**Comment by JusticeGoat** [comment]
I tested it three times in a row and had another test it and same thing happens it crashes you.

**Comment by Xhuis** [comment]
Which rune is this referring to? I'm not super up-to-date on lavaland.

**Comment by JusticeGoat** [comment]
The only one that allows you to orbit it in the ghost menu, its in the cult ruin.

**Comment by Cyberboss** [comment]
If this happens again can you link the round id? I'd like to see the logs

**Comment by Xhuis** [comment]
Yeah! I'm kind of curious as to why this is happening. That's just the Nar-Sie rune, but I'll take a look around and see if there's anything that might be causing it.

**Comment by Xhuis** [comment]
I've found the issue. It seems like, due to goonchat's method of rendering icons, the rune lacking an icon (due to a known bug) is causing the game to crash. There's a PR that fixes this up already, and I've requested that its creator include the line to automatically close this issue once it's merged.

**Comment by ChangelingRain** [comment]
This issue should be converted to a generalized one if that is the case, as my pr only fixes one instance of it.

**Comment by factoryman942** [comment]
the rune is so horrific it drives your byond client insane
