### ISSUE TITLE
Emagged doors cannot be welded shut to be deconstructed

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#29011]
After a door is emagged open (or closed) fixing the wiring and regaining control of the door by isolating the door bolt wire you cannot take further action to fix the emagged door. By this step you would want to deconstruct the door so that you can replace the airlock electronics or alternatively build a entirely new door in its place. However when you try to welder the door it will return "The airlock doesn't need repairing." and cancel the action

Repairing the door with a welder takes higher priority it seems, and it doesn't acknowledge a emagged but structurally intact door to be 'damaged'. Its broken because it forces engineers to use a RCD, and makes it impossible to restore emagged doors to working order.

**Comment by Repukan** [comment]
Did you make sure you were in harm intent to weld it

**Comment by FantasticFwoosh** [comment]
Probably not. Oops.

**Comment by Xhuis** [comment]
Harm intent makes the welding function properly. This is a non-issue!

**Comment by FantasticFwoosh** [comment]
Close it then please, i must have forgotten it was a thing.

**Comment by Xhuis** [comment]
I'm not a maintainer. You should be able to close them.
