### ISSUE TITLE
You can use spells on the wizard outpost during (very bullshit) Ragin Mages

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#29013]
see title

**Comment by GunHog** [comment]
Ragin' Mages was removed, was it not? An admin probably summoned a bunch of wizards instead. It is not an issue in that case, as wizards are supposed to be able to cast there for practice before leaving the station.

**Comment by Iamgoofball** [comment]
oh i forgot we should remove that downstream ass well

**Comment by PKPenguin321** [comment]
This is the case for regular wizard as well and was done intentionally I think

**Comment by improvedname** [comment]
Everything is allowrd but teleport/jaunt/bind soul
