### ISSUE TITLE
Changeling bug found. Alive but dead? End game stats are mixed.

### ISSUE THREAD

**Issue by srifenbyxp** [tgstation/tgstation#29033]
Original post here: https://tgstation13.org/phpBB/viewtopic.php?f=2&t=11980&p=314090#p314090

 I escaped on a pod alive but it said I didn't, also I never did die but another ling greentexted saying I did die. Don't know whats up with that but like any other law abiding spessman tis my duty to report such strange things. 

http://i.imgur.com/G7Sq5hi.jpg

**Comment by DoctoreMad** [comment]
>Hugbox server gives everyone greentext

**Comment by Tacolizard** [comment]
The bug in question related to escaping on pods has been fixed. It's either not merged, or it is and the server hasn't updated yet.
