### ISSUE TITLE
Goonchat stops auto-scrolling after double-quote (")

### ISSUE THREAD

**Issue by Electronics** [tgstation/tgstation#29045]
Server revision compiled on:  2017-07-03 
b0a5aa 

If a double-quote appears on a new line in chat, the chat will stop auto-scrolling until _x NEW MESSAGES_ is clicked. Happens repeatably and reliably every time.

Example:
![capture](https://user-images.githubusercontent.com/422393/27843264-bd0d18c4-6109-11e7-8e83-29cea202b31f.PNG)

With the line below the hang shown:
![capture2](https://user-images.githubusercontent.com/422393/27843274-d19a8740-6109-11e7-8751-dcf4cbb7c1d8.PNG)

**Comment by Cyberboss** [comment]
Thanks for tracking this down

**Comment by Cyberboss** [comment]
I also just noticed that the commemorative plaque's desc https://github.com/tgstation/tgstation/blob/1b7c4a63dc983bfaee9f1825564bb38bf06e119c/code/game/turfs/simulated/floor/misc_floor.dm#L4 is completely blank but it shows a backslash

**Comment by Tacolizard** [comment]
@Cyberboss I'm pretty sure that was an issue since before goonchat. The plaque on Boxstation has the correct description.

**Comment by Cyberboss** [comment]
my fix failed btw

**Comment by kriskog** [comment]
Cant reproduce, seems fixed.
