### ISSUE TITLE
Wearing ablative armor doesnt count as stealing it

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#29078]
Wearing ablative armor doesnt count as stealing it, as per antag objectives.

**Comment by bgobandit** [comment]
are you sure you needed the ablative armor and not some other armor vest (I ask because I have made this mistake0

**Comment by Cyberboss** [comment]
@golfer45 pls confirm

**Comment by BeeSting12** [comment]
You sure you didn't need the reactive teleport armor instead?

**Comment by Xhuis** [comment]
I booted up a local server to test this.
![](https://i.imgur.com/jZDPHei.png)
This was while I was wearing the reflector vest properly, in the chest slot. Thus, I'm unable to reproduce this.

**Comment by golfer45** [comment]
Im sure I was wearing it in my chest

**Comment by golfer45** [comment]
on bagil

**Comment by Xhuis** [comment]
And you're certain that it was a reflector vest, and not a different kind?

**Comment by FantasticFwoosh** [comment]
Was it a chameleon vest a traitor swapped for the real vest?

**Comment by CPTANT** [comment]
Probably memed by chameleon kit.

**Comment by KorPhaeron** [comment]
Nobody has been able to reproduce
