### ISSUE TITLE
Chefs can never attain dessert science purrfection.

### ISSUE THREAD

**Issue by KingPhilipIII** [tgstation/tgstation#29077]
Right. So even after assembling all the ingredients to make a cak in various beakers and putting them all on my table, I was unable to bring my glorious cake cat hybrid to life.

Not much to it otuside of that, wouldn't know what else to say.

**Comment by KingPhilipIII** [comment]
Yea. The button was grey'd out.

**Comment by PraiseRatvar** [comment]
I think you were missing an ingredient considering I see a cak on sybil rn

**Comment by KingPhilipIII** [comment]
Wew, thought my comment went through. And I'll even relist all the ingredients. Liquid reagents I had in their own seperate containers. I had three piecesof meat, originally monkey meat, switched to generic meat to check if that was the issue, a beaker with teslium(About 40 units), 30 units of blood, a heart, a brain from a monkey, 7 units of sprinkles, and a birthday cake.

**Comment by YakumoChen** [comment]
I think it needs to be a living brain

**Comment by KingPhilipIII** [comment]
Hm. Perhaps. I'll try and verify and if I can I'll close this.

**Comment by fludd12** [comment]
Have managed to craft a cak with both player-controlled and monkey-controlled brains. I don't think this issue is present anymore.
