### ISSUE TITLE
The collosus can't "Judge" you properly

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#29089]
The collosus seems to get stuck on certain bodies and is unable to dust them, thus being stuck judging them forever.

https://gyazo.com/3a213e8908ca3399e3f012334740ff8b

Later on I actually took in on the station and put it in a cage: https://gyazo.com/7d5a676aa6ae19eac4f1adbad9fd77d6

**Comment by Jarektheraptor** [comment]
An update, it's not just certain bodies, It can't dust people at all. It gets stuck attacking the body it's trying to dust but will never actually manage to do it.

**Comment by Shadowflame909** [comment]
Hello all mega fauna do this, it appears the gibbing part of megafaunas are broke. Ash drakes get stuck and don't gib, bubblegum does also. So plz fix

**Comment by lzimann** [comment]
This was caused by the GOAP testmerge.
