### ISSUE TITLE
Things might be breaking faster than they're supposed to be.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#29117]
Not sure if this is an issue for just this round- I'll close if thats the case, but windows, airlocks, personal closets, etc seem to be breaking faster than they used to. 

ex. I threw a spear twice at the det's closet and it broke it open.
I three tapped a reinforced window with a welder. 
One throw of a spear made an airlock slightly damage. Usually it takes two or three.

edit: I'm thinking it could be admin fuckery. I just repaired a bunch of windows that looked like they were in good shape, but hitting them once would send them to the really big cracks, almost broken sprite.

edit2: Examining the "good as new" windows showed they were heavily damaged, yet the sprite did not change. It appears almost every window I've found (boxstation) is like this except the ones I've repaired, which makes them act as intended.

edit3: Making new windows seems to start them out as heavily damaged, this time with the proper sprite. Round number is 72947

edit3.14: Plasma windows appear to be unaffected, possibly a bug brought from that PR.

**Comment by BeeSting12** [comment]
I believe this is fixed by #29095 its just that servers have not updated yet. If there's a way to force the servers to do that, a headmin or @MrStonedOne doing that would be great

**Comment by Cyberboss** [comment]
Was it just windows though?

**Comment by MrStonedOne** [comment]
I updated the servers so check if its fixed

**Comment by BeeSting12** [comment]
I think it was just windows, the locker might've been a fluke.
