### ISSUE TITLE
Normal reinforced glass and reinforced plasma glass can merge

### ISSUE THREAD

**Issue by MoreRobustThanYou** [tgstation/tgstation#29113]
```The following pull requests are currently test merged:
#28900: 'GOAP: Goal Oriented Action Planning' by Iamgoofball at commit af51eb
#29100: 'Make timer debug info more robust' by MrStonedOne at commit 10bb93


Based off origin/master commit: e80769
```

just what the title says

Possibly due to reinforced glass being ```merge_type = /obj/item/stack/sheet/rglass``` while reinforced plasma glass is ```merge_type = /obj/item/stack/sheet/rglass/plasma```

fixed by https://github.com/tgstation/tgstation/pull/29114

**Comment by RemieRichards** [comment]
it's exactly that.

**Comment by MoreRobustThanYou** [comment]
Would it be bad to make ```/obj/item/stack/sheet/rglass``` into ```/obj/item/stack/sheet/rglass/normal```?

**Comment by RemieRichards** [comment]
yes it would.

**Comment by RemieRichards** [comment]
it'd be easier, to just make plasma glass and plasma rglass NOT be subtypes of those types, they're not inheriting much from being those types, so ie:

```
/obj/item/stack/sheet/rglass

/obj/item/stack/sheet/plasmarglass

/obj/item/stack/sheet/glass

/obj/item/stack/sheet/plasmaglass
```

It's the simplest cleanest solution, not the best, but the best without putting in more work (like: reworking smoothing for mineral walls, or repathing rglass to be abstract), it's the simplest idea that will be accepted, is my point.
