### ISSUE TITLE
Crew manifest is blank.

### ISSUE THREAD

**Issue by fizzle7** [tgstation/tgstation#29115]
Join as CE late in round, look at PDA crew manifest, blank. Refresh, blank, reenter, blank, reinsert id card, blank, look at console manifest then look at pda, blank.

**Comment by ohnopigeons** [comment]
Can't reproduce. Probably fixed with https://github.com/tgstation/tgstation/pull/28989. Good meme reporting this bug RIGHT after the fix was merged.
