### ISSUE TITLE
Goonchat doesn't log well.

### ISSUE THREAD

**Issue by callanrocks** [tgstation/tgstation#29122]
Attempting to save a chat log with goonchat menu option just opens a new IE window with the log in it, doesn't actually save the log like the old system did.

**Comment by MrStonedOne** [comment]
i don't think it can

**Comment by MrStonedOne** [comment]
you are basically asking for a webpage to be able to save file on to your computer.

**Comment by SpaiR** [comment]
@Cyberboss you may be interested https://github.com/TauCetiStation/TauCetiClassic/pull/1672
