### ISSUE TITLE
Cannot build AutoDrobe from scratch.

### ISSUE THREAD

**Issue by fizzle7** [tgstation/tgstation#29124]
Decon AutoDrobe, you get a ClothesMate board from it, insert ClothesMate board, asks for 3 resupply units, try to insert AutoDrobe units, can't, only ClothesMate work. It's impossible to construct AutoDrobe.

**Comment by ShizCalev** [comment]
You need to screwdriver the board to switch it to an AutoDrobe one for it to accept the autodrobe units.

Unable to replicate it dropping a ClothesMate board though.

**Comment by fizzle7** [comment]
Oh I screwed it and didn't notice, thanks, closing then.
