### ISSUE TITLE
Creating tiles out of metal only produces 1 tile instead of 4

### ISSUE THREAD

**Issue by CosmicScientist** [tgstation/tgstation#29135]
Round ID: 72975
Server revision compiled on: 2017-07-07

- Have a stack of iron in your hand
- Create 4 tiles
- 4 tiles appear in your hand
- Create 4 tiles
- 4 tiles appear below you
- Create 4 tiles
- __1__ tile added to the 4 tile stack below you, making it 5
- Create 4 tiles
- __1__ tile added to the 5 tile stack below you, making it 6

**Comment by CosmicScientist** [comment]
This appears to be the same for rods too.

I imagine anything that goes from crafting->stack, at least on the floor, is affected.

**Comment by Tacolizard** [comment]
@Cyberboss was not able to reproduce

**Comment by CosmicScientist** [comment]
Round ID: 73286
Server revision compiled on: 2017-07-14

The following pull requests are currently test merged:
#29207: 'Rename Bump to Collide' by optimumtact at commit 734337
#29241: 'ClickCross now uses CanPass instead of density directly.' by AnturK at commit a90688
Based off origin/master commit: 2b053f

Followed the same steps as above. Put a stack of metal in your hand. Click make floor tile or rod three times. Observe stack below you containing an odd, incomplete number.

**Comment by Tokiko1** [comment]
In stack.dm, this line was the issue: 
`var/atom/O = new R.result_type( usr.loc )`
Sheets are kinda aggresive on merging, so they'd immediatly try to merge this thing when it appeared, before it could properly set its amount.
