### ISSUE TITLE
Holopara scout mode broken

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#29146]
The camera doesn't follow the holopara, you can't see SHIT!

**Comment by Repukan** [comment]
You mean after you get out your view is focused on your master?

Afaik scout mode means the Holo can go farther out to see stuff, not that the master can see

**Comment by Armhulen** [comment]
yeah, that's what i mean

**Comment by Repukan** [comment]
Can you write it in your own words because mine confused me

**Comment by Armhulen** [comment]
"when you emerge in scout mode, the camera doesn't follow you but sticks onto your host"

**Comment by ExcessiveUseOfCobblestone** [comment]
just call reset_perspective() when the scout comes out, easy fix.

**Comment by Armhulen** [comment]
it wasn't even my first issue
