### ISSUE TITLE
Cleanbot interface is locked to AIs

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#29152]
Can still turn it on and off as well as emag it, but settings cannot be altered.

**Comment by Iamgoofball** [comment]
Cleanbot settings were removed for the purpose of "whats the point". Nobody ever actually used the settings, aside from on/off.

**Comment by GunHog** [comment]
That is a really poor reason. Did you at least enable all the modes (clean blood, dissolve trash, etc?)

**Comment by Iamgoofball** [comment]
Yeah, it's all enabled by default.

**Comment by Anonmare** [comment]
Would at least like the patrol setting back. I've noticed the cleanbots just sit around doing nothing even when surrounded by blood.

**Comment by msgerbs** [comment]
I agree, that seems like a poor reason to remove the settings. I can think of a lot of things that should be removed if never being used is a reason to remove them.

**Comment by Iamgoofball** [comment]
I'm actually working on fixing the patrol setup, that will be returning but I have to migrate it to GOAP.

**Comment by PKPenguin321** [comment]
In other words it is gone forever

**Comment by Iamgoofball** [comment]
fuck you leatherhead

**Comment by Dorsisdwarf** [comment]
Not a bug, just goofball.
