### ISSUE TITLE
Packadge wrapper bugs

### ISSUE THREAD

**Issue by vzhegalov** [tgstation/tgstation#29157]
Bug 1:
Steps to reproduce:
1.Try to wrap  crate with FULL (25 sheets) packadge wrapper.
2.See "you need more paper!" messadge.
3.Examine wrapper,and see that some sheets are gone!
I exepted wrapped crate,but crate doesn't look wrapped,and i cannot tag it with destination.
Bug 2:
Steps to reproduce:
1.Try to wrap box with FULL (25 sheets) packadge wrapper.
2.See messadge saying you have wrapped it.
3.See that box doesn't look wrapped,you cannot tag it ith destination,and sheets are gone in wrapper.
What i exepted:wrapped box,with full functionality.

P.S  Sorry for bad english.

**Comment by PraiseRatvar** [comment]
@Cyberboss 
https://github.com/tgstation/tgstation/pull/29125
?

**Comment by vzhegalov** [comment]
Okay.closed
