### ISSUE TITLE
Transit stations suck in atmosphere every time they dock

### ISSUE THREAD

**Issue by msgerbs** [tgstation/tgstation#29164]
Every time a transit station opens and closes, the transit pod sucks in whatever atmosphere is on the tile. This causes the pod to eventually become extremely overpressurized to the point where it damages you quite a bit just to ride on it. It also causes a bunch of space wind in the room. It's especially obvious and annoying on Charlie Station where you have to go back and forth constantly.

**Comment by BeeSting12** [comment]
Dupe #23556

**Comment by msgerbs** [comment]
Oh, I missed that one because the silly person who made it didn't use "transit" in the title.

**Comment by BeeSting12** [comment]
i made it.

**Comment by BeeSting12** [comment]
but i changed the title original did have it :P
