### ISSUE TITLE
It is possible to create a bar drink with multiple overlays in use.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#29169]
![](http://i.imgur.com/fKYvZi3.png)

Haven't replicated this myself, but this is what it looked like in action alongside the steps to make it in the PM.

**Comment by DoctoreMad** [comment]
This is it
You have confused the drink
Rude

**Comment by FantasticFwoosh** [comment]
Make compatible overlay DMI's by using a drinks that can be combined and its a feature.

**Comment by kriskog** [comment]
Cant reproduce
