### ISSUE TITLE
Shades can't move after being tabled.

### ISSUE THREAD

**Issue by Mark9013100** [tgstation/tgstation#29175]
Server revision compiled on: 2017-07-09

The following pull requests are currently test merged:
#29155: 'A* improvements' by MrStonedOne at commit 85de15

Based off origin/master commit: 4358c0

In a recent round, I grabbed a shade and placed it on a table, the player controlling it couldn't move whatsoever. I think this can happen with other simple mobs such as Ian and cows.

**Comment by Xhuis** [comment]
I can't reproduce this on the latest master.

**Comment by Armhulen** [comment]
LOL!

**Comment by DoctoreMad** [comment]
THE MEMES JACK

**Comment by AnturK** [comment]
Can't reproduce.
