### ISSUE TITLE
Add rwalls around SM space loop

### ISSUE THREAD

**Issue by fizzle7** [tgstation/tgstation#29177]
Quote from SM exploding too quickly issue:
> Oh i have a secret method that does this its very simple. I break the cooling loop from space.
> Guaranteed supermatter explosion in one minute

 Just had that happen to me, someone casually strolled into space, broke the space loop and it went from 30K to 4000K in about 10 seconds or so, by the time I fixed the space loop the freon was out cause I wrenched it in without noticing the space loop. After that the waste pipes filter to cooling pipes stopped working for some fucking reason and the gases werent cycling so the SM ended up exploding, which might be a bug on its own but I'm not sure enough to report it.

 This is really fucking annoying, add rwalls around the space loop at least, cause any fucklet asking the AI for eva can fuck up the SM 2 minutes into the round every fucking round.

This is for boxstation, unsure about the rest.

**Comment by Repukan** [comment]
You can make the rwalls yourself.

Not everything needs to be safety padded.

**Comment by fizzle7** [comment]
you want me to make like 20 rwalls? and take 10 minutes off the round, probably more since you dont have enough plasteel to stop shitlers from taking 10 seconds to fuck up the whole round? No thanks, maybe antags shouldn't be spoonfed grieflike retarded station-disabling mechanics.

**Comment by Repukan** [comment]
>People are griefing
>How dare you tell me to take action to stop the Griff

Even normal walls stacked line after line would deter normal people. Hell, grilles would too because tedium drives griefers away

**Comment by fizzle7** [comment]
It's not grief when it's antags doing it. Even if it's grief, the action you're suggesting is hugely disproportional to the time it takes to grief, and no, anyone with half a brain to sabotage the space loop has tools for normal walls or grilles, it literally takes 1 second to cut the grille and 10 for a normal wall.

**Comment by fizzle7** [comment]
For discussion purposes, yes you could use the fridges, not sure if every map has them, but whether they can handle it or not, I don't know.

**Comment by factoryman942** [comment]
what about shockgrilles?

**Comment by Cyberboss** [comment]
Feature request go on the forums, or PR it yourself
