### ISSUE TITLE
Internal chemical explosions are reduced by external armor

### ISSUE THREAD

**Issue by Hikurac** [tgstation/tgstation#29172]
It seems that if you're wearing armor, you take reduced damage from chemical explosions that occur within your body.

**Comment by XDTM** [comment]
also goes for fire damage

**Comment by Iamgoofball** [comment]
life, uh, finds a way

**Comment by Tacolizard** [comment]
it works because the armor helps hold your severed body together!

#loredealwithit

**Comment by Iamgoofball** [comment]
not a bug, this is how explosions work, there is no way to make this not occur without a massive rewrite of how explosions work for incredibly little gain
