### ISSUE TITLE
The extended vision on MG turrets is also broken.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#29189]
It ends up with a little square in the center with your effects and stuff and then extended view which is extremely disorienting. No pictures right now and I'm pretty sure there's another issue for this open anyway but couldn't find it. @Robustin

**Comment by DoctoreMad** [comment]
150 hours or something

**Comment by vuonojenmustaturska** [comment]
@KorPhaeron gang was removed

**Comment by BeeSting12** [comment]
@KorPhaeron turrets are still in the game

**Comment by magatsuchi** [comment]
no longer seems to occur when using mg turrets
