### ISSUE TITLE
MG Turrets have no cooldown

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#29187]
THE FUCKING MACHINE GUNS APPARENTLY HAVE ZERO COOLDOWN BETWEEN VOLLEYS, LEADING TO ME RUNNING DOWN THE HALL THINKING IT'S SAFE TO APPREHEND TO IDIOT ON THE TURRET AND THEN DYING ALONG WITH MY OFFICER WHO HEARD THE GUNFIRE AND FIGURED IT WAS SAFE.

**Comment by BeeSting12** [comment]
@Robustin

**Comment by PKPenguin321** [comment]
Balance issue and a really really shitty report, close

**Comment by DoctoreMad** [comment]
Turrets are supposed to have a cooldown before firing.

**Comment by BeeSting12** [comment]
I was somewhat salty during the making of this. But it is in fact supposed to have a cooldown, I remember him mentioning it in the original PR and I believe it was there for a while.

**Comment by ShizCalev** [comment]
They have a cooldown now it seems, this can be closed.

**Comment by ShizCalev** [comment]
@Cyberboss They have a cooldown now it seems, this can be closed.
