### ISSUE TITLE
Cloning is broken

### ISSUE THREAD

**Issue by Limski** [tgstation/tgstation#29200]
It's currently auto ejecting people as they're getting cloned, I believe it might be related to the new organs update.

note: no outside factors are affecting this (I.E powerloss/someone with access ejecting people)
They might be dying to toxin damage mid-cloning due to not having livers, however I cannot confirm this.

**Comment by Armhulen** [comment]
H A R D  M O D E

**Comment by Tacolizard** [comment]
ok lemme see if this is my fault

**Comment by Tacolizard** [comment]
ok i don't think this is my fault because if you put the nugget that you get from the first cloning back into the scanner and clone from that, you get a perfectly normal healthy clone.

**Comment by Cyberboss** [comment]
@Tacolizard did you remember to add the liver and stomach to the cloning process?

**Comment by Tacolizard** [comment]
afai can tell, I don't need to. It just loops through a list of organs. Also if that was the case, then cloning from a nugget wouldn't be possible. 

On the first cloning attempt, the pod instantly ejects the clone, a nugget, who dies instantly. The pod plays a message "Cloning failed due to irrecoverable tissue damage"

**Comment by Tacolizard** [comment]
now like i said I don't think this is my fault but the issue may be that cloning starts without administering corazone fast enough. in that case it should be a simple check_brine() further up in the process() proc

**Comment by Tacolizard** [comment]
ok problem is CONFIRMED NOT MY FAULT!

upon local testing i found that the clone is dying from taking oxy and brain damage, not toxin damage. meaning, they are not dying of liver failure

**Comment by Iatots** [comment]
but what if another organ was usually processed first to give them oxy/brain juice and now your organs have displaced it from first position? How does that list loop work?

**Comment by Tacolizard** [comment]
what

**Comment by kevinz000** [comment]
Someone fix this..

**Comment by Mark9013100** [comment]
I haven't done much testing on this, but in two cases I've seen someone with cloning scans have no issue at all during cloning, whereelse someone cloned from their body can die possibly up to 6 times during cloning.

**Comment by Armhulen** [comment]
this is the change we needed remove cloning hardmode lifeweb fuck the system fuck quality of life

**Comment by Tacolizard** [comment]
ok the issue was the clones dying of heart failure because their bodies were removing corazone from themselves faster than the clonepod could add it to the brine. easy fix.

**Comment by Tacolizard** [comment]
the second part of the issue was that clones are fed reagents to keep them alive while they can't breath and such. While clones had no liver, they could not process those reagents and were taking damage.

**Comment by Tacolizard** [comment]
The reason why cloning a failed clone may work is because by the time the failed clone popped out, the brine was already filled with enough chemicals (mainly corazone) to heal the clone.
