### ISSUE TITLE
Tongs with supermatter crystal sliver disappear when trying to put the sliver into the containment bin

### ISSUE THREAD

**Issue by Bod9001** [tgstation/tgstation#29203]
[Note]: # (<B>Please enter the `Round ID` from the `Status` panel if you can!</B> If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

73139 Round ID

I was the CE and a traitor, my objective was to steal "a sliver off a supermatter crystal" so a little bit into the round I had some time and privacy, and so I cut a bit off, that worked fine, picked it up with the tongs and got the box/supermatter bin/whatever it's called in the other hand, and then uesed tongs on the supermatter bin and the tongs disappeared with the sliver and the bin remained empty luckily somebody killed themselves trying to get in to do the same objective so I stole their tongs and tried again but it did the same

Summary for ,objective "Steal a sliver of a supermatter crystal" the part where you put it into the box causes your tongs to disappear and your sliver as well

**Comment by Dorsisdwarf** [comment]
Observed this bug occuring on basil.

**Comment by MoreRobustThanYou** [comment]
can confirm, personally experienced this once
