### ISSUE TITLE
Reflectors don't reflect handgun beams properly

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#29211]
If you fire a disabler shot at a reflector it'll reflect incorrectly. Either it'll go straight through the reflector or it'll bounce back and hit you instead of reflecting at a 90 degree angle. I'm assuming this has something to do with pixel projectiles.

**Comment by kevinz000** [comment]
yeah it's called i never added proper support. :^)

**Comment by YakumoChen** [comment]
it used to be the case before pixel projectiles, now it doesn't work at all because angles and shit
