### ISSUE TITLE
Bodies infected with headslugs eggs that become blob zombies, cuase some strange things to happen.

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#29213]
Start by being a headslug. Lay eggs in body. Body is then taken over by blob spore becoming  a blob zombie. When the eggs hatch you will come back as the body you infested before promptly loosing all your organs, and then being alive but unable to move.

**Comment by Armhulen** [comment]
edge case

**Comment by Shadowlight213** [comment]
Dupe of #27757
