### ISSUE TITLE
Putting C4 in a Storage Implant after activating said C4 doesn't detonate

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#29216]
Putting C4 in a Storage Implant after activating said C4 doesn't detonate. I put in a activated C4 in my implant so it would explode after I died and it didn't do the boom.

**Comment by MimicFaux** [comment]
Maybe related. I once tried to kill my target by putting a long-timer c4 on a medical implant, and then surgically attached the c4'd implant. It never went off.

**Comment by Supermichael777** [comment]
because its put inside the implant code wise and as organs they are in nullspace. if their not going off its probably because they somehow left the processing loop otherwise their exploding in nullspace and therefor doing nothing

**Comment by ShizCalev** [comment]
Probably the same issue as #22035

**Comment by timothymtorres** [comment]
According to #22035 this was fixed.  There is also an open issue at #45053 where putting c4 inside the storage implant works fine.
