### ISSUE TITLE
Mapmerge corrupts small maps with full dictionaries

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#29210]
Mapmerge doesn't trim smaller maps due to the extremely high value set to trigger trimming, resulting in their dictionaries getting overfilled and causing the map to corrupt when merging.

Suggested fix - update the python script to;

1. Check for unused keys
2. Always delete/replace unused keys
3. Check for new keys
4. Replace new keys with a random key from the available pool (to reduce probability of merge conflicts)
5. No longer bother sorting the dictionary alphabetically

**Comment by xxalpha** [comment]
Explain how they become corrupt.

**Comment by ShizCalev** [comment]
MM tries to write keys past the available dictionary resulting in an overflow that ruins the map.

Example file;
https://github.com/ShizCalev/tgstation/commit/e8c32c5d70ef516bb47a289e45326f16698da7d3

**Comment by xxalpha** [comment]
Ah I get it now. I'll fix it later.

**Comment by xxalpha** [comment]
I'll have a fix for it later, but you can just push the new version. It's mostly different at that point.

**Comment by ShizCalev** [comment]
@xxalpha Any luck on it? Had it happen to me while I was fixing things on Cere

**Comment by xxalpha** [comment]
I completely forgot about this. I think if it overflows you're supposed to push as is without merging, as you alter the entire file regardless of merging or not.
