### ISSUE TITLE
Liver PR breaking some viruses

### ISSUE THREAD

**Issue by Forest3r** [tgstation/tgstation#29214]
Round ID: 73159
I made a heal virus and could not get myself infected after downing a full bottle of said virus. I tested multiple things and other player made virus could infect me, while my heal virus could not. I downed about 60 units of the healing virus in total, and inject about 20 units with no successful infection. However I took some toxic damage instead of being infected and said toxic damage was slowly healed, making me think this has some connection to the liver PR as "if it becomes too damaged, it will undergo liver failure and you will slowly die of toxin damage. Your liver naturally heals a small amount of its damage." I tested said virus on others and they had the same toxic damage rather than infection.

**Comment by XDTM** [comment]
Toxin damage may be caused by blood incompatibility instead. Also, check that the virus isn't simply stealthy.

**Comment by Cyberboss** [comment]
Liver PR was reverted. @Tacolizard take note

**Comment by Tacolizard** [comment]
I have no idea why this would be happening. I didn't touch anything remotely virus related.
