### ISSUE TITLE
Floorbots suck at placing floortiles efficiently.

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#29222]
![2017-07-12_16-51-05](https://user-images.githubusercontent.com/28678854/28126803-80b4fe40-6722-11e7-85dd-65269b81908e.png)
i gave it these commands however for some reason it likes going to the furthest floortile then once it finishes placing that floortile it goes to the next furthest floortile

i'm /guessing/ floorbots will be improved when this is merged - https://github.com/tgstation/tgstation/pull/28900

**Comment by Shadowlight213** [comment]
Floorbots aren't part of it

**Comment by Iamgoofball** [comment]
I will likely add floorbots to GOAP soon.

**Comment by TheBonded** [comment]
better detailed in https://github.com/tgstation/tgstation/issues/63258
