### ISSUE TITLE
prototype hardsuit sprite doesn't cover the body fully

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#29229]
the toes stick out!

**Comment by Mark9013100** [comment]
budget cuts

**Comment by Armhulen** [comment]
so prototype!!

**Comment by Repukan** [comment]
Well it's a prototype

**Comment by Mark9013100** [comment]
Prototype (stylized as [PROTOTYPE]) is a 2009 open world action-adventure video game developed by Radical Entertainment and published by Activision. The game was released in North America on June 9, 2009, and in southwestern parts of North America as well as Oceania on June 10, and was released in Europe on June 12. Versions for PlayStation 4 and Xbox One were released on July 14, 2015 alongside the sequel as Prototype Biohazard Bundle. Separate versions of the games became available on August 12, 2015.[4]

**Comment by banthebantz** [comment]
All right, Gordon. your suit should keep you comfortable 
through all this. The specimen will be delivered to you in a few 
moments. If you would be so good as to climb up and start the rotors, 
we can bring the anti-mass spectrometer to 80 percent and hold it there 
until the carrier arrives.

**Comment by Xhuis** [comment]
Assuming you mean the RD hardsuit, this isn't reproducible; the directional sprites all cover up the toes.

**Comment by Armhulen** [comment]
i mean the space one

**Comment by Armhulen** [comment]
space ruin one
