### ISSUE TITLE
Lings aren't stunned by N2O permenantly anymore

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/tgstation#29225]
RoundID 73188

Changeling by Y0SH1_M4S73R repeatedly broke out of cuffs even when under N2O internals AND/OR N2O filled gas room on Pubbystation.

Changeling was able to break out and use their ling powers whilst under N2O influence.

Changeling was contained and removed.

**Comment by KorPhaeron** [comment]
Are you sure an admin didnt do it?

**Comment by Y0SH1M4S73R** [comment]
I was using adrenaline, which can be used while unconscious and sets sleeping/unconscious to 0 along with stun and knockdown. See the code here:
[https://github.com/tgstation/tgstation/blob/master/code/game/gamemodes/changeling/powers/adrenaline.dm](url)

Feature.

**Comment by RemieRichards** [comment]
Not a bug, see Yosh's comment.
