### ISSUE TITLE
Plasteel, metal sheets, metal rods, glass, r-glass are all tiny items

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#29220]
Might be the same for any smelted ore sheet.

**Comment by Repukan** [comment]
You're a big guy

**Comment by RandomMarine** [comment]
See #27964

This is a non-issue unless you're getting tiny sized stacks that are over a third full

**Comment by XDTM** [comment]
Pocket metal may be a balance issue but idk

**Comment by BeeSting12** [comment]
Ah, okay, thanks. Being able to fit enough metal to finish off a wall in your pocket seems a bit weird but whatever. A maintainer can close if they want, I still think this is kind of dumb.
