### ISSUE TITLE
Wanted plant, gotten seed instead 

### ISSUE THREAD

**Issue by SuspiciousMan** [tgstation/tgstation#29237]
I wanted a flower, instead I got flower seeds.
Plant ready to be taken:
https://i.gyazo.com/2a6e18144a3c75bf43dc4ef35d6df066.png

What was given instead:
https://i.gyazo.com/b6bbc4b022d0fffae18442e31a14ed15.png

**Comment by FantasticFwoosh** [comment]
I am the creator of the PR that made it drop seeds in  #27214 . It is intentional for it to not drop a harvest.

The code is a slightly modified and updated version of pod-seeds, which also return seeds on harvest.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Cyberboss not a bug

**Comment by Dorsisdwarf** [comment]
Not a bug
