### ISSUE TITLE
Traitor objectives don't always show up in the greentext at end of round

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#29264]
https://file.house/GYUp.png

https://file.house/P8Jr.png

This happened to two other people around 3:30 pm EST 7/14/17. 

The following pull requests are currently test merged:
#29241: 'ClickCross now uses CanPass instead of density directly.' by AnturK at commit a90688

Based off origin/master commit: 2b053f

**Comment by Anajamois** [comment]
Can confirm. Stealing plasma didn't greentext me either.

**Comment by FantasticFwoosh** [comment]
It happened to me whilst i died while also AFK.
