### ISSUE TITLE
Shuttle walls reflect missiles

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#29261]
I don't think that beam and bullet reflection should work on missiles

**Comment by Armhulen** [comment]
and it shouldn't work on pulse rifles either >:(

**Comment by DoctoreMad** [comment]
Pulse rifles are also lasers.

**Comment by FantasticFwoosh** [comment]
What if its a laser guided missile.

I GUESS, this is a feature, if you want to say nanotren did it for security purposes.
