### ISSUE TITLE
APC Areastring & turret control_area both work poorly

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#29271]
Both APCs and turret controllers (/obj/machinery/turretid) have their area related strings (areastring & control_area) working off an area's name as opposed to an area's path, which results in issues when you have areas with duplicate names (ie Medbay)

Turret controllers also have copypasta'd code for getting an area by name, instead of using the get_area_by_name proc.

**Comment by Cyberboss** [comment]
It searches for the area by name instead of type, which is stupid

**Comment by ShizCalev** [comment]
Noticed that turret controllers (/obj/machinery/turretid) work the same way with the control_area variable as well (though it uses copypasta'd code instead of using the get_area_by_name proc.)
