### ISSUE TITLE
Blob suffers no ill effects from freon.

### ISSUE THREAD

**Issue by GuyonBroadway** [tgstation/tgstation#29275]
So on hippie we had a blob round, blob was in engineering storage and broke the freon canister.

The blob was now basically free to do whatever as nobody could do anything due to the slippy freon floors.

**Comment by BeeSting12** [comment]
More of a balance issue than code issue. I do agree that freon is dumb as heck though

**Comment by banthebantz** [comment]
freon freeze bleb make it ;( and slow down it growth

**Comment by nicbn** [comment]
Same happened in tg with me playing like 2 times, why do we have freon btw, we can replace it with some gas that we already have and just super cool it.

**Comment by jughu** [comment]
Jusy pry the floor with a crownar

**Comment by CPTANT** [comment]
I wouldn't consider this a consistency issue at all, since the blob can perfectly survive in other cold environments like space.

**Comment by BeeSting12** [comment]
@optimumtact 
Not a bug, close please.

**Comment by optimumtact** [comment]
don't ping me, I'm not your personal bug handler.

**Comment by nicbn** [comment]
Balance issue.

**Comment by nicbn** [comment]
Why close? The balance is supposed to be fixed, freon is too op.

**Comment by CPTANT** [comment]
Freon being  OP has nothing to do with its effect on blobs. Blobs not being effected by freon is logical since blobs can survive in cold environments.

If blobs took damage from cold environments than every area exposed to space would fuck them over.
