### ISSUE TITLE
Panic bunker only blocks the intial connection

### ISSUE THREAD

**Issue by LetterJay** [tgstation/tgstation#29279]
The recent update fixed the initial check. But after that, it filters the reconnect as it already being seen, so it allows players to be rejected by the first connection, but then try again and be allowed to join.

Only reason I even see the panic bunker having major use is it deters people who have nothing better to do than make multiple accounts just to troll for an hour.

**Comment by MrStonedOne** [comment]
@Jordie0608 I fucking knew there was a reason i kept those two procs seperated!
