### ISSUE TITLE
3 Ashwalkers took on a Goliath, attacking it with spears and pickaxes. Each strike gave off "The goliath looks unharmed." 10 minutes of this continued until it killed all 3 while being undamaged, after dozens of spear/pickaxe hits. Obviously, something went wrong.

### ISSUE THREAD

**Issue by Anajamois** [tgstation/tgstation#29286]
[Note]: # (<B>Please enter the `Round ID` from the `Status` panel if you can!</B> If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by Dorsisdwarf** [comment]
You should probbably have put that in the description

**Comment by FantasticFwoosh** [comment]
Im here thinking you were throwing the spears at the goliath and not twohanding the spears for the maximum amount of damage.

Or a admin was playing a joke and var-edited all your equipment.

**Comment by Anajamois** [comment]
There was a mixture of spear-chucking and regular stabbing involved.

**Comment by Ergovisavi** [comment]
Throwing is intentionally ineffective against mining mobs. Otherwise, beating them to death with regular weapons should work just fine?

**Comment by Anajamois** [comment]
As I said - There was a mixture of everything involved. When stabbing it with spears gave off "The Goliath appears unharmed", we turned to throwing. When throwing didn't harm it, we turned to pickaxes. When pickaxes didn't harm it, we changed to slashing it. And then we died and were all very salty in deadchat.

The only weapon I know harms a goliath is the Miner's mining gun.

**Comment by kevinz000** [comment]
lol git gud

**Comment by Anajamois** [comment]
fite me cunt

**Comment by KorPhaeron** [comment]
Nobody else has reported a similar issue in 2 months now, never reproduced
