### ISSUE TITLE
The RIPLEY's clamp often causes bugs when attacking nonstandard mobs

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#29282]
Probably because of the Oxygen damage proc, but I can't confirm.
Clamping a borg(I remember this one form long time ago so it might be fixed) or a alien empress(tested recently) causes them to receive the darkness overlay forever.

**Comment by Jacquerel** [comment]
Can no longer reproduce this.
I couldn't squeeze a cyborg at all and squeezing an alien queen resulted in just the usual pain overlay, which receded as I healed by standing on weeds.

**Comment by Sealed101** [comment]
with the issue above fixed this is also fixed by https://github.com/tgstation/tgstation/pull/85070
