### ISSUE TITLE
Laser guns seem to cause continuous errors

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#29309]
It gets REALLY fucking awful when it starts passing through windows.

**Comment by AnturK** [comment]
No idea what are you trying to say here. Describe the issue.

**Comment by Jalleo** [comment]
We need proper information or this will end up being closed @DoctoreMad

**Comment by DoctoreMad** [comment]
I'm more surprised that this pull request is still here.
Anyways, this is on the wrong git so good luck finding the issue(there isn't one)
