### ISSUE TITLE
Being Blood Drunk doesn't actually reduce damage

### ISSUE THREAD

**Issue by JakeFlex** [tgstation/tgstation#29301]
I've used a crusher and obtained the Eye from the miner a few times. The description reads "It has an eye of a blood-drunk hunter attached, which cause mark detonation to grant stun immunity and 90% damage reduction for 1 second." However this is not the case. By detonating a mark you go up to 90% hp for a second and can be hit. After the second ends you take whatever damage you were supposed to and it's not sustainable. So partway through a fight with a boss you just randomly crit or go red and can't heal fast enough. It delays damage rather than reducing it from what I can tell.

**Comment by ChangelingRain** [comment]
It should be reducing the damage you gained when it wears off: when it starts you get 10x health, it multiplies the damage you have by 10 when it does that, and when it wears off it multiplies your health and damage by 0.1

accordingly whatever you gain should also be reduced...
what were you fighting? did you detonate a mark while still blood-drunk?

**Comment by JakeFlex** [comment]
I've fought the Hierophant, dragon and many small mobs using it. I notice my health goes green when the mark is detonated, I get hit and am still green. Afterward I'll walk away and my health will drop drastically after the mark ends. Often into lethal levels against bosses. My guess is the damage is not being reduced properly upon leaving the blood drunk state.

**Comment by banthebantz** [comment]
@ChangelingRain umm what?

You can make it far less snowflakey by just adjusting the species damage modifiers surely.

**Comment by ChangelingRain** [comment]
You'd think that, but species damage modifiers also modify healing, don't have toxin, oxygen, clone, or stamina, and then it wouldn't account for other mob types.

**Comment by banthebantz** [comment]
how IRKSOME
