### ISSUE TITLE
TK overlay not disappearing after losing TK

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#29306]
Round ID: 73355
Server revision compiled on: 2017-07-15
The following pull requests are currently test merged:
#29240: 'Reworks and rebalances Geis, merges conversion sigils' by Xhuis at commit 7c2e5f
Based off origin/master commit: 5ad0aa

I got the the feel smarter message and the aura, but after a bit the TK disappeared but the overlays for that power is still showing. Other powers may or may not be affected.

**Comment by meeeeme** [comment]
I think Cold Resistance too

**Comment by MimicFaux** [comment]
This is especially annoying when testing with injectors.
