### ISSUE TITLE
monkey is able to live without heart

### ISSUE THREAD

**Issue by furryowl** [tgstation/tgstation#29307]
They don't take damage.

**Comment by PraiseRatvar** [comment]
@Tacolizard 
since you love organs so much

**Comment by Xhuis** [comment]
That would be because monkeys are heartless monsters

**Comment by Tacolizard** [comment]
monkeys don't really use organs the same way humans do. This is 100% not a bug because monkeys just have organs as fluff when they're gibbed. They don't actually do anything and since the heart attack code is on human.dm, well...

**Comment by furryowl** [comment]
@Tacolizard But they need lungs to live.

**Comment by CPTANT** [comment]
Shouldn't processing organs be on carbon instead of human?

**Comment by RemieRichards** [comment]
should doesn't mean is.

**Comment by CPTANT** [comment]
Carbons living without organs is a consistency issue.

**Comment by RemieRichards** [comment]
what isn't, there's nothing new here.
