### ISSUE TITLE
Med cyborgs can't perform Limb Augmentation

### ISSUE THREAD

**Issue by furryowl** [tgstation/tgstation#29318]
They need to perform Amputation and Prosthetic Replacement

**Comment by GunHog** [comment]
Allow me to fill in missing details here. When you get to the last step in the surgery where you add the augmentation/new limb, a Medical Cyborg must use its organ bag to apply the limb. Nothing happens. They also seem to be unable to cancel active surgeries. I tested this using my own roller bed.

**Comment by MimicFaux** [comment]
Canceling surgeries involves drapes in one hand, cautery in the other. Being limited to a single active at once, may be part of that problem.
