### ISSUE TITLE
hivebot invasion event occurring at .

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#29331]
Impact location determined from trajectory to be . Leave the area immediately or risk annihilation.

**Comment by Cyberboss** [comment]
Can anyone reproduce this? Because I can't

**Comment by Shadowlight213** [comment]
Also should point out it didn't actually land.
@Cyberboss I used the admin trigger event if that helps.

**Comment by Cyberboss** [comment]
Funny it always works locally. Time to good servers I guess :/

**Comment by kevinz000** [comment]
![wew](https://puu.sh/wPYcG/9c39a52005.png)

**Comment by ShizCalev** [comment]
fixed by #29443
