### ISSUE TITLE
it seems like the hivebot invasion doesn't even land?

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#29348]
impact imminent but the actual machine doesn't land??

**Comment by Cyberboss** [comment]
may have landed in space...

**Comment by PraiseRatvar** [comment]
did some madman place something in spess?

**Comment by PraiseRatvar** [comment]
wait https://github.com/tgstation/tgstation/issues/29331

@Armhulen 
@Cyberboss 

dup?

**Comment by Cyberboss** [comment]
Possibly

**Comment by Cyberboss** [comment]
Yes
