### ISSUE TITLE
Multiple progress bars when clickspamming

### ISSUE THREAD

**Issue by kingofkosmos** [tgstation/tgstation#29346]
You can get multiple progress bars when clickspamming a task, such as adding metal plating to a girder.

This only completes the first task and then ends the others, no extra material is wasted, but it still looks kinda buggy.

![image](https://user-images.githubusercontent.com/5420151/28334147-e4c831d8-6c02-11e7-9522-6e41ebbc9301.png)

**Comment by Cyberboss** [comment]
These are bugs unique to each task so if you have a list please give it

**Comment by kingofkosmos** [comment]
I don't have a list. It happened when building a girder, adding plating to it and also when unbuckling from a bed while straightjacketed. Seemed to be whenever you do an action which uses the progress bar.

**Comment by BeeSting12** [comment]
You can do this with butchering animals and removing brains from the head.

**Comment by ShizCalev** [comment]
Implanting does it too.

**Comment by DoctoreMad** [comment]
Some actions can be repeated multiple times and get multiple progress bars, that is normal. Bandages for example.
That being said the girders one like in the OP seems pretty wrong since you can only complete a wall once.

**Comment by alexkar598** [comment]
It looks nice tho

**Comment by optimumtact** [comment]
you can start the action many times, only one of them will actually complete. This isn't a bug as such

**Comment by kingofkosmos** [comment]
That's what I was getting at,, it doesn't affect the gameplay in any way, it just looks/feels kinda sloppy.

**Comment by furryowl** [comment]
You can force feed somebody multiple time

**Comment by Daturix** [comment]
Feature

**Comment by KorPhaeron** [comment]
@tgstation/commit-access 

Can we just label this "will not fix" rather than adding checks for everything in the game to see if you're already interacting with it?

**Comment by kingofkosmos** [comment]
Can the check be made into do_after itself to check if it's already running?

**Comment by lzimann** [comment]
It is possible, but not sure how feasible would it be.

**Comment by Dorsisdwarf** [comment]
as requested
