### ISSUE TITLE
View Range is fucking crashing the server

### ISSUE THREAD

**Issue by Limski** [tgstation/tgstation#29342]
Setting view range to 10 (in ghost tab as a ghost) then clicking the view range button again causes the screen to go wild on EVERYONEs screens. I have confirmed it several times through testing with Thunder on basil

also setting the view range to 128 crashes dreamseeker

It only started happening in the last ~12 hours or so, it's fair to assume one of the new PRs are the cause of this

**Comment by Limski** [comment]
Unconfirmed but if you do this enough times it can crash the server

**Comment by Cyberboss** [comment]
This is crashing the servers someone fix it

**Comment by DoctoreMad** [comment]
rip

**Comment by JamieH** [comment]
Replicated this issue on Hippie station today using gang turrets.

**Comment by ma44** [comment]
Just don't change your view range
Also remove gangs

**Comment by JamieH** [comment]
Sniper rifles also do it, as do mechs.

**Comment by Limski** [comment]
I will update the title to reflect the urgency of this

**Comment by Limski** [comment]
people are starting to abuse this because "i ded"

**Comment by optimumtact** [comment]
oh no, what will we ever do

**Comment by optimumtact** [comment]
btw it's patched out with #29352

**Comment by optimumtact** [comment]
which is test merged

**Comment by Limski** [comment]
o

**Comment by Limski** [comment]
Using the ghost observe verb on a living player when you have 10 set as view range still shakes peoples screens up and makes them angry even with the test merge
