### ISSUE TITLE
Spamclicking setup preferences is a DoS vector and most likely a memory leak

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#29359]
oranges told me to report it on the tracker so people fix it faster but w/e
1. Spamclick setup preferences
2. Oh look the MC's instances is skyrocketing
3. Oh look the CPU is skyrocketing
4. Oh look the runtimes are skyrocketing
5. I can't confirm for sure but I'm pretty sure the topic limiter isn't able to block this action.

When we're having memory leaks out the ass (atleast far as I've gotten from people) this might be an issue with 90 people generating previews on highpop, eh?

**Comment by RemieRichards** [comment]
Of all the times to use [s], this was one of them.
Thank you for completely failing that.

**Comment by optimumtact** [comment]
why would you use [s] on an issue report

**Comment by RemieRichards** [comment]
ASS

**Comment by optimumtact** [comment]
![](https://file.house/aG1_.png)

**Comment by ShizCalev** [comment]
Confirmed, topic limited doesn't apply to any of the setup preferences.
Managed to spike CPU up to 320 on a local server (idle is 10~20)
Also applies to opening the game preferences menu from the preferences tab.

**Comment by optimumtact** [comment]
@tgstation/commit-access I thought we fixed this @tgstation/toolmasters

**Comment by MrStonedOne** [comment]
It could be the runtimes. It might be runtiming before the anti-flood stuff

**Comment by AnturK** [comment]
It does. https://tgstation13.org/parsed-logs/sybil/data/logs/2017/07/20/round-73540/runtime.txt
Also AI/Cyborg icon operations are done immediately.

**Comment by MrStonedOne** [comment]
The antiflood is in client topic. There are two, one is the per minute/second thing, the other is the inpref check that keeps you from doing multiple generate operations until the first finishes, I think they might not be enough

**Comment by AnturK** [comment]
I don't see the preferences limiter it seems to be done instantly. Generic client topic applies.

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/tgstation/blob/master/code/modules/client/client_procs.dm#L89

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/tgstation/pull/22853

**Comment by optimumtact** [comment]
fixed I'm sure
