### ISSUE TITLE
Shuttle can take off with 3/4 of it eaten by a singularity but won't land

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#29397]
>singularity at escape

>3/4 of the shuttle gets eaten

>somehow the shuttle still takes off

>round ends

>you are marooned on the station

>what

>steps into space tile

>wtf it was a transit tile

>>>>>>the shuttel can take off with only 1/4 of it intact but can't land and if you're stuck in hyperspace you're marooned on the station

mods, my immersions.

**Comment by Repukan** [comment]
>enough engine capabilities for take off but fucked enough that you can't steer or land 

Sounds immersive to me

**Comment by AnturK** [comment]
Write something readable next time. Also 
\>learn markdown
