### ISSUE TITLE
Ore satchel can hold infinite ore

### ISSUE THREAD

**Issue by Yiu113** [tgstation/tgstation#29392]
Mining's standard ore satchels are capable of holding far more than they should be able to, possibly infinite amounts.

[This is the load from a single satchel, never reached a limit if there is one on it.](https://i.gyazo.com/b849c4955771b93d16488d0b5ce562cf.png)

**Comment by GunHog** [comment]
To clarify, you are not talking about _bluespace_ satchels, right? Just the normal roundstart ones? The limit on those should be 50 ores total.

**Comment by Yiu113** [comment]
Talking about roundstart satchels, yeah.

**Comment by Yiu113** [comment]
Did some additional testing. This ONLY occurs if you have the ore satchel automatically pick up ore that you cross, it does not work with ore that you try to manually pick up. Will add a gif momentarily.

**Comment by ChangelingRain** [comment]
@Xhuis

**Comment by Qustinnus** [comment]
ores don't check if there's room in the bag when they get walked over.

**Comment by Xhuis** [comment]
Oh, huh. This bug actually existed _before_ I refactored them, so I never fixed it. I'll do that sometime today.

**Comment by Qustinnus** [comment]
no you created it because in all other places where handle_item_insertion is called, they check if theres room before calling it, so you'll have to do something similar for crossing over ore.

**Comment by Xhuis** [comment]
I know that, but I don't believe the old version checked either, and I didn't do the old version. I by extension did not cause this bug.

**Comment by Qustinnus** [comment]
the old version just acted like you attack the ore when you walk over it, which does check for space.
