### ISSUE TITLE
forced_movement can sometimes cause infinite movement loops

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/tgstation#29394]
A very minor and rare bug and likely not something that will become a problem until you guys implement things like multi z stairs, but I feel this is still worth pointing out:

forced_movement can cause things to move back and forth infinitely if they never actually reach their target without actually being blocked. An example would be making a very large, open room, then putting a hand teleporter portal somewhere in the middle of it and then slipping into it via lube: You'll be teleported away, then move back towards the portal and this will repeat until it disappears. Not quite endless, but you get the point.

It also doesn't seem to check for z levels, so if you slip in the southern part of a map into a teleporter set to the northern part of a different map... you'll end up moving hundreds of tiles.

**Comment by AnturK** [comment]
Likely just needs interruptable param that stops it on forceMove

**Comment by JohnFulpWillard** [comment]
This isn't a problem anymore is it? @LemonInTheDark

**Comment by LemonInTheDark** [comment]
> Endless drifting seems like an intended feature @AnturK? If I'm not mistaken it's apart of the laws of physics.

Not what's being discussed

This is still very technically a problem.
I have deprecated all but one use of the forced_movement datum, all that remains is the meathook, which requires speeds that I refuse to support with moveloops

**Comment by san7890** [comment]
forced movement is killed as of #80002
