### ISSUE TITLE
Can only make white medical robots

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#29407]
Start with any colour medkit and it'll be the right colour all the way through assembly up until you put the last piece on, when it turns white.

I am badly triggered.

**Comment by Penguaro** [comment]
Well white medibots communicate a certain effectiveness. The crew won't be certain that a medibot of color will be able to fully address their needs, afterall, how do they know it wasn't just sped through the assembly process to meet a manufacturing quota.

**Comment by AnonymousNow** [comment]
#BLUEBOTSMATTER
![kormedibot2016](https://user-images.githubusercontent.com/6266927/28491188-7778eee4-6ee4-11e7-99ce-11304d55b07a.png)

**Comment by Penguaro** [comment]
I believe all bots matter...
