### ISSUE TITLE
Delta Maintenance Oversight

### ISSUE THREAD

**Issue by TrustyGun** [tgstation/tgstation#29408]
Round ID: #73567
![image](https://user-images.githubusercontent.com/7079721/28441014-ab2ab502-6d76-11e7-8721-d478f6f43b34.png)
This maintenance door doesn't have access for the bartender (and most likely the chef, clown, and mime too). It's the only maintenance door connected to their workplaces, which is an issue when there is a radstorm.

![image](https://user-images.githubusercontent.com/7079721/28441064-e5e56ac0-6d76-11e7-8e9a-13a0c7ea0950.png)
This spot that connects to chemistry and genetics is not considered a maintenance area. This also seems like an oversight.

(yes this is an i ded)

**Comment by ShizCalev** [comment]
honk

(will fix)
