### ISSUE TITLE
Losing your heart causes your ling revive to fail

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#29403]
If you lose your heart as a ling, you will be unable to revive. You technically will revive and will become conscious for a brief period of time before you fall unconscious and start dying. Nothing you can do will save you when you fall unconscious past reviving again. The only way to recover from this is to transform or use last resort in the very brief period you're awake when you revive since you can't use most abilities whilst unconscious, and those two are the only abilities that seem to regenerate organs one way or the other. Regenerate won't help you, adrenals can't wake you up and turning into a monkey still keeps you unconscious without your organs

**Comment by Tacolizard** [comment]
@Xhuis there's already a regenerate organs button for lings, so your PR is redundant.

just push regenerate organs before reviving

**Comment by bgobandit** [comment]
OBJECTION: lizards don't have hearts
