### ISSUE TITLE
lavaland Syndicate base self destruct too senstive

### ISSUE THREAD

**Issue by JusticeGoat** [tgstation/tgstation#29405]
I honestly have no idea why we should even have payloads in the walls around the test lab after all its a test lab! I have seen five separate people on different rounds blow the base killing friendly's from monkeys grabbing the payloads or just by random mistake.

Either make the explosives in the walls shock and fireproof so its just set off from the main console or remove it.

**Comment by Repukan** [comment]
They're there because the prime directive of the test lab is to commit seppuku if external forces find it.

The reason so many explosives were put into the walls is a)scientists used to take them off/disable them b)the base needed to be completely and utterly destroyed.

All in all it's a feature

**Comment by JusticeGoat** [comment]
Then can the explosives be "stabilized"? I see no reason that they cant set it off when they want to, also the people who spawn there come with guns and weapons.

**Comment by Repukan** [comment]
Iff assholes didn't try to leave, then maybe. U til then it's a needed feature.

**Comment by JusticeGoat** [comment]
I honestly have no idea why blowing up a wall starting a chain of explosions is a feature.

**Comment by AnturK** [comment]
Not really a bug, but i agree this might be annoying.
