### ISSUE TITLE
Chloral hydrate seems to be broken

### ISSUE THREAD

**Issue by Darkgenerallord** [tgstation/tgstation#29402]
Round ID 73562. Chloral hydrate does not process, have any effects, etc. It also does not metabolize, so it just sits in your system forever.

**Comment by Iamgoofball** [comment]
Nice

**Comment by Supermichael777** [comment]
wait realy?
Does this still fucking happen? Because this should not be happening.

what was the server revision?

**Comment by Supermichael777** [comment]
could not reproduce in private testing.

**Comment by Supermichael777** [comment]
@maintainers Resolved in current build, server needs to be updated

**Comment by AnturK** [comment]
Duplicate of #27983
