### ISSUE TITLE
Interface zooms out strangely when changing form (?)

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#29416]
I've had this every time I've gone into a ghostrole in the past few days, wherein everything is zoomed out, and it doesn't get fixed unless I reload the game, at which point someone has already stolen my ID card from my 30-seconds braindead body. Unsure if zooming out as a ghost had something to do with it.

I also had it happen when I was a PAI entering a medibot. No in-game setting seems to be able to fix it. What's going on?

**Comment by MrStonedOne** [comment]
You might have to explain what you mean by zooming out, maybe with before and after screen shots (don't use the built-in screenshot function, that tends to not include render oddities)

**Comment by MrStonedOne** [comment]
also, was this on bagil?

**Comment by MrStonedOne** [comment]
#29352

**Comment by AnonymousNow** [comment]
This was on Sybil. Apparently no option available can fix this in-game; I need to reload my client into the server to get it fixed.

In order:
1. Normal pre-ghostrole.
2. Normal ghostrole.
3. Zoomed pre-ghostrole.
4. Still-zoomed ghostrole.

![1normalpre](https://user-images.githubusercontent.com/6266927/28483884-6e5d0b60-6e67-11e7-84ae-bb2fc7b0d8ab.png)
![2normalpost](https://user-images.githubusercontent.com/6266927/28483888-6e860ab0-6e67-11e7-9355-d73c8e57f9f8.png)
![3zoompre](https://user-images.githubusercontent.com/6266927/28483885-6e804ae4-6e67-11e7-8857-3246c6f757f3.png)
![4zoompost](https://user-images.githubusercontent.com/6266927/28483886-6e8410d4-6e67-11e7-8f2d-238608467bf3.png)
