### ISSUE TITLE
Cannot inject people as PAI in medibot.

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#29417]
Clicking on someone just plays a random TTS line. No other click combination seems to have an effect. Nobody seems to know what the problem is.

**Comment by jughu** [comment]
Was he at full health? If so ya cant ha him

**Comment by AnonymousNow** [comment]
I tried it on a variety of people at various health values, and none of them worked.

I do vaguely remember that the people with full health I tried it on had different messages to the tune of "all patched up", though.

**Comment by Xhuis** [comment]
Turns out that this wasn't a bug; because of the heal threshold functionality medibots have, you couldn't actually heal them, and it didn't mention anything. I made a PR to add a notice for that, though.
