### ISSUE TITLE
hivebot invasion thing doesn't defend itself or make hivebots

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#29422]
>it stood there and let itself be hit until it broke

@Cyberboss

**Comment by Tacolizard** [comment]
it should also spawn with more hivebots than it does. It's super easy to kill.

For example, the hivebot core landed in the Janitor's closet on Box, and it was dead before I could get there from the Brig.

**Comment by Anonmare** [comment]
It could do with some deflection to prevent it from being an easier target
