### ISSUE TITLE
You cannot directly fill yourself (Injecting yourself in the head with a syringe doesnt work)

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#29424]
Injecting yourself in the head with a syringe produces "You cannot directly fill yourself" as the message.
Tested with a hardsuit and a syringe on inject.

**Comment by FantasticFwoosh** [comment]
More detail, also lay off the botox @kevinz000

**Comment by banthebantz** [comment]
can you add some fucking detail please

**Comment by kevinz000** [comment]
lmao fwoosh

**Comment by Tacolizard** [comment]
rename shitposting to fwooshposting

**Comment by FantasticFwoosh** [comment]
You are the one who did not actually provide a original description, don't pretend you were being helpful to people actually trying to resolve this issue.

> _Throws mekhi on the table_

**Comment by DaxDupont** [comment]
Tried injecting someone in the head with anti-tox kit charcoal, got the "You cannot directly fill John Doe!" message.

**Comment by optimumtact** [comment]
https://github.com/tgstation/tgstation/blob/master/code/modules/reagents/reagent_containers/syringes.dm#L115
