### ISSUE TITLE
Viral Symptoms are neutered but do not show up as such on the pandemic.

### ISSUE THREAD

**Issue by Nabski89** [tgstation/tgstation#29426]
Server: Both

Revision: Post pull #28556

Problem Description: What is the problem?

What did you expect to happen: Why do you think this is a bug?: Neutered a symptom with formeldhyde, Named the virus, created a new bottle. Infected Self and was not affected by neutered. Shows the virus name it was given.

What happened instead: How is what happened different from what you expected? Virus created was unnamed. When putting it back in the pandemic it shows as if nothing is neutered. The symptom remains neutered.

Why is this bad/What are the consequences: Why do you think this is an important issue? Without being able to tell if something is neutered or not you can't tell if something is actually hostile or not. It also breaks being able to name anything.

Steps to reproduce the problem: The most important section. Review everything you did leading up to causing the issue.: Create a virus. Neuter something and name it. Create a bottle and put the bottle back in the machine. There might be interesting double neutering achievable here as well.

**Comment by XDTM** [comment]
Damn, i thought i fixed that
