### ISSUE TITLE
>Freon blobs

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#29421]
>Freon doesn't do damage to blobs

>Blob can just grow in it and it will easily expand to win because no one will be able tos top it even with suits you still slip

>thanks goof!

**Comment by Iamgoofball** [comment]
not a bug

move 2 forums

**Comment by FantasticFwoosh** [comment]
![](http://1.bp.blogspot.com/-2Bvktz1MZe0/UCTXkdlukvI/AAAAAAAAALA/B_bQ4FkulpU/s320/laughing.gif)
