### ISSUE TITLE
RD server consoles can see *all* RnD computers

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#29439]
The console which is responsible for administrating the information gathered usually situated in the station's server room accessible via access to the RD reads off other RnD computers not present on the station z level belonging to the ownership of others including the abandoned station.

The arguable problem is that this allows meta-knowledge of the existance of certain ruins by checking this console and the responsibility that comes with it for a RD to not abuse said power, and because the servers are not independent, all of the other consoles are affected by server failures on the station (deconstructed server etc)

- Golems can already be identified by the teleporter beacon, but a malicious RD could lock them out of their own console, and steal their synced data and effectively until the golems build another console they cannot get back in.

**Comment by Anonmare** [comment]
Couldn't the golems just deconstruct and reconstruct their old console?

This is arguably more of an issue with the research system as you can sync with the servers off z-level

**Comment by kriskog** [comment]
Gone with techwebs
