### ISSUE TITLE
CTF Gun issues

### ISSUE THREAD

**Issue by TribeOfBeavers** [tgstation/tgstation#29435]
Spawned in on blue team for CTF and didn't have a gun. Upon clicking my right hand slot one appeared, but it only had one shot in it.

**Comment by PKPenguin321** [comment]
Pretty sure this is a dupe

**Comment by GunHog** [comment]
It sounds like your gun had no loaded (gun + mag loaded) sprite. When you clicked your hand, you unloaded your gun's mag, switching it to a new icon state and causing it to display. It also could have simply spawned with an incorrect item state, which you could confirm by trying to put the mag back in.

**Comment by TribeOfBeavers** [comment]
It's possible, but there wasn't a mag visibly spawned. It may have been invisible too

**Comment by PraiseRatvar** [comment]
p sure the gun is there however for some reason the sprite is not there

**Comment by Jalleo** [comment]
Dupe. 5 pages back same issue reported better saying a fully loaded gun isnt showing as a sprite. Due to the revert of a merc lavaland ruin.
