### ISSUE TITLE
disappearing orders in cargo

### ISSUE THREAD

**Issue by MrDoomBringer** [tgstation/tgstation#29433]
RID: 73628 

if you order more than one glass crate, metal sheet crate, etc. the shuttle will arrive with only one of the crates fill, the rest of the respective types will be empty.

**Comment by FantasticFwoosh** [comment]
Thats intentional.

Mark the manifest with the red cargo stamp to reject it and send it back for extra points, then order again. The system throws out purposeful mistakes like that for cargo to sort through.

**Comment by Tacolizard** [comment]
@Dorsisdwarf not a bug

**Comment by Jalleo** [comment]
It suggests that if you order 4 crates of glass you will only get 50 sheets not 200. Requires testing.

**Comment by optimumtact** [comment]
yes, it's not clear if this is due to the gameplay feature of some crates going missing and being misfiled, or if there is a bug where ordering many crates is not working

@Roboman100 can you clarify?

**Comment by AnturK** [comment]
Can't reproduce the stacking issues, missing cargo is a feature.
