### ISSUE TITLE
Timers are crashing (or something else is that is causing temp_visuals to not delete) consistently nearing 2 hours into the round

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#29438]
For the past few days every time it's nearing 14:00 shift time shit just starts going wack.
What happened to the robust MC that can handle everything?

**Comment by ninjanomnom** [comment]
remember when I warned it was floats

I can't believe it actually ended up being that

**Comment by Tacolizard** [comment]
how many times has this issue been duped

**Comment by kevinz000** [comment]
@Tacolizard it's consistently happening in relatively high octane rounds that approach the two hour mark.

**Comment by optimumtact** [comment]
stuipd github
