### ISSUE TITLE
space cash is worth many of credit

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#29447]
That's some space cash. 

It's worth 1000 credit 

>1000 credit

**Comment by WJohn** [comment]
space cash in general needs to be reworked so it's actually a stackable item, instead of just bundles of 1, 5, 10 etc dollars.

heck we even have a proper system now to make the sprites change when it gets appropriately large enough, so it should be effortless to do.

**Comment by banthebantz** [comment]
make space cash a material

**Comment by Supermichael777** [comment]
Money golems

**Comment by KingPhilipIII** [comment]
Speed merge money golems plox.

**Comment by Fox-McCloud** [comment]
@WJohn Over at Para I reworked it to be exactly like you mention.

All money stacks with all other kinds of money up to a cap of 1,000,000 credits; it makes handling money an absolute breeze (too bad no one still uses it).
