### ISSUE TITLE
You can hand-tele Necropolis Tendrils on board the station

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#29441]
Meteorshot was used to knock it through.

**Comment by MimicFaux** [comment]
*Not an 'I ded'

**Comment by DoctoreMad** [comment]
Feature

**Comment by DoctoreMad** [comment]
Edge Case

**Comment by MimicFaux** [comment]
They fixed miners being able to shove tendrils with ripley's, no reason this should be left flapping in the wind too.

**Comment by DoctoreMad** [comment]
Not worth trying the time to fix

**Comment by DoctoreMad** [comment]
Minor issue

**Comment by DoctoreMad** [comment]
Unimportant

**Comment by Grazyn** [comment]
Can you still buckle them to roller chair and drag them on the station?

**Comment by RandomMarine** [comment]
Seems like this and all other tendril relocation fuckery can be fixed by porting them to being structures instead of mobs. Since generalized object damage is a thing nowadays.

**Comment by XDTM** [comment]
making it a structure won't help, meteorshot can knock fucking anything short of a wall away

**Comment by XDTM** [comment]
we _could_ make it check for anchored but it's so fun to knock down airlocks and pretend you're the LAW

**Comment by RandomMarine** [comment]
But they would stop going through portals, right?

**Comment by Tacolizard** [comment]
@DoctoreMad just a tip, try to condense your thoughts into a single comment instead of blurting out whatever crosses your mind

**Comment by XDTM** [comment]
Goddammit portals used to check for anchored, but @kevinz000 re-added megafauna teleporting with #28055 without documenting it

**Comment by kevinz000** [comment]
woops
also @DoctoreMad go take a cup of shut the fuck up and fuck off, thanks.

**Comment by DoctoreMad** [comment]
Sheesh sorry I don't have a metaclub membership so I can't ask metabuddies to tag-team with me

**Comment by Tacolizard** [comment]
@DoctoreMad you're also not a coder so fuck off telling us what is and isn't worth fixing.
