### ISSUE TITLE
SUGGESTION/QUESTION:lavaland ruins

### ISSUE THREAD

**Issue by vzhegalov** [tgstation/tgstation#29440]
So,i have a suggestion: at roundstart print all ruins(liveable,like syndies base,seed vault,etc) and jump button right to them(or anything) for ghosts to jump to this ruins.

**Comment by AnonymousNow** [comment]
I don't think this is the place for such suggestions.

Why not use Orbit? Ghostrole positions are at the bottom of the ghost Orbit list, after all.

**Comment by FantasticFwoosh** [comment]
[Use the forums, close this please](https://tgstation13.org/phpBB/viewforum.php?f=9)
