### ISSUE TITLE
Bees appear to be completely invincible.

### ISSUE THREAD

**Issue by Darkgenerallord** [tgstation/tgstation#29445]
Bees appeared to be unable to die, ignored being deleted, etc. Revision was e2eb80 as far as I can tell, round number was 73666.

**Comment by Repukan** [comment]
🐝

**Comment by QualityVan** [comment]
🐝

**Comment by Mark9013100** [comment]
🐝

**Comment by Xhuis** [comment]
🐝

**Comment by ChangelingRain** [comment]
🐝

**Comment by Xhuis** [comment]
I can't bee-produce this issue.

**Comment by BeeSting12** [comment]
🅱️ ees

**Comment by Tacolizard** [comment]
@Xhuis that is one of the worst puns I have ever heard. It's not even a play on words.




🐝

**Comment by DoctoreMad** [comment]
Missing the label "Send help"

**Comment by calzilla1** [comment]
According

**Comment by WJohn** [comment]
Anything special about those bees? Were they produced by hydro or had something happen to them?

**Comment by Darkgenerallord** [comment]
As far as I can tell they were just hydroponics bees. I had to put them all on centcomm by varediting since they were literally impossible to delete.

**Comment by nicbn** [comment]
try killing bees
fail
try deleting bees
fail
try removing bees from the code
fail
send help

**Comment by FantasticFwoosh** [comment]
Bees are one shotted by flyswatters that come with the beekeeping crate, and you can reduce the amount of  bees to like five at any time by installing only 1 tray. Id only ever recommend 2 trays and full capacity if you had more room to not be overcrowded.

- When all your plants are potency 100 or you feel satisfied/annoyed at bee spam, harvest the honey and splat all but 1 of your worker bees to reset the hive.

IC player issue, though codifying apiary trays to be easier to manage (and reworking how bees collect/store resources so they don't sperg out) and having clearer health values of bees to die quite easily would be a adequate solution.

**Comment by Repukan** [comment]
The prize for not reading goes to fwoosh

**Comment by FantasticFwoosh** [comment]
Best way to beat the bug(s) is to not let it happen is more the point of my interjection. Smaller amounts of bees are also easier to track for testing purposes.

**Comment by praisenarsie** [comment]
![2017-09-14_20-50-05](https://user-images.githubusercontent.com/31222036/30452719-8769902c-998e-11e7-9cbc-38b732c20861.png)
![2017-09-14_20-50-26](https://user-images.githubusercontent.com/31222036/30452722-887698ca-998e-11e7-8b29-604f69fcf35f.png)
![2017-09-14_20-50-30](https://user-images.githubusercontent.com/31222036/30452724-897fed0c-998e-11e7-9413-560350b41628.png)
aAAAAAAAAAAAAAAAAAAAAAA @KorPhaeron why did you close this when @pubby didn't say he fixed it

**Comment by pubby** [comment]
My bad it got hit with auto-close cause of 'fixes #'

**Comment by praisenarsie** [comment]
@pubby no prob
