### ISSUE TITLE
Old Delta Station's main-to-science transport tube sucks in all the air

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#29469]
You know the station I mean, right? the one with the three old cryo ghostroles and the hivebots.

The transport tube between the main station and the science station will quickly get a ridiculously damaging air pressure inside the transport pod while the chambers on either side will become vacuum. For some reason, this only seems to start happening when the doors to these chambers are opened, or perhaps when the tube is actually used for the first time - it's hard to tell, but the end result is the same.

**Comment by BeeSting12** [comment]
This is a dupe

**Comment by BeeSting12** [comment]
#23556

**Comment by Repukan** [comment]
Yeah dupe of #23556, just close it

**Comment by AnonymousNow** [comment]
Wow, this has been an issue forever, it looks like.
