### ISSUE TITLE
On Delta station the maintence hatch below chem is not radiation shielded.

### ISSUE THREAD

**Issue by Anundeadguy** [tgstation/tgstation#29468]
[Note]: #Round ID 73727 map Delta station.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by BeeSting12** [comment]
Are you talking about the morgue connecting to medical maint?

**Comment by ShizCalev** [comment]
It was already fixed by #29386, the servers just needs to be updated.
