### ISSUE TITLE
Abandoned Miner APLUs that randomly spawn in Lavaland don't have drills, have a garbage item instead

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#29465]
![miner](https://user-images.githubusercontent.com/6266927/28504598-bb5c90ce-7011-11e7-9145-6d03bde8088e.png)

This cannot drill.

**Comment by factoryman942** [comment]
draw me

**Comment by octareenroon91** [comment]
That was supposed to be a plasma cutter actually. You got fucked.

**Comment by calzilla1** [comment]
Drae me like one of your french drills

**Comment by AnonymousNow** [comment]
>That was supposed to be a plasma cutter actually. You got fucked.
Multiple times, as well. I never got to use it more than dropping it off outside the mining base and hoping someone with more time would fix it.
