### ISSUE TITLE
Lavaland Ruin Ripley doesn't get generated properly.

### ISSUE THREAD

**Issue by JochenScheisse** [tgstation/tgstation#29478]
The Lavaland Ripley "Miner" that is sometimes randomly generated as a "Ruin", does (sometimes?) not generate its main equipment attachment properly. Instead of a Drill or Cutter, it generates a "PAINT ME" mecha equipment called "mecha equipment" in its slot.

My suspicion is that the error rests in [tgstation/code/game/mecha/working/ripley.dm](url="tgstation/code/game/mecha/working/ripley.dm"), most likely in the lines 100, 103 and 107.

**Comment by RemieRichards** [comment]
This is a duplicate report, and a fix is already up, thanks for your report.
Duplicate of #29465
Fixed in #29477

**Comment by RemieRichards** [comment]
And for your own curiosity, it WAS line 107.
