### ISSUE TITLE
purchaping shuttle is not working.

### ISSUE THREAD

**Issue by vzhegalov** [tgstation/tgstation#29479]
STEPS:
1.be capitain.
2. call the shuttle.
3.declare red alert.
4.recall the shuttle.
5.try to buy shuttle wwhen it's at centcomm.
6. ????
7. NO SHUTTLES AT purchaping shuttle window.

**Comment by meeeeme** [comment]
I think it's disabled because some shuttles break the game

**Comment by DoctoreMad** [comment]
It was re-enabled a while ago, keep up with the news mate.

**Comment by Tacolizard** [comment]
this bug report is actually overcomplex. shuttles don't appear in the purchase window no matter what, even at roundstart.

**Comment by PraiseRatvar** [comment]
it doesnt work when you call then recall

im 90% about this however havent played in a relatively long time
