### ISSUE TITLE
people are randomly losing objectives at round end report..?

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#29470]
![a](https://puu.sh/wRqss/71b2f4744c.png)meme

**Comment by calzilla1** [comment]
What a quality buh report

**Comment by calzilla1** [comment]
Bug*

**Comment by YakumoChen** [comment]
I lost my objectives when my body was deleted.

**Comment by ohnopigeons** [comment]
Also happened to me when my body was deleted.

**Comment by optimumtact** [comment]
no reproduction steps, no logs, no round number, no check if admins edited the round

no viewvar drops, nothing

how are we supposed to replicate and or begin to find the bug in this?

**Comment by BeeSting12** [comment]
perhaps by yknow logging into the server and watching a few rounds. it's common enough that you'll see it pop up if it's traitor, hell, ive even seen cults/gangs not have their antag lists pop up endround

**Comment by nicbn** [comment]
Some admin please try forcing traitor until it happens then take the logs.

**Comment by optimumtact** [comment]
I don't have any admin permissions on the servers

**Comment by jughu** [comment]
Its just if your body gets destroyed really

**Comment by callanrocks** [comment]
This also happens with AI laws if they get removed from existence.
