### ISSUE TITLE
Traitors have infinite TC provided they just sell a few stacks of minerals and emag the console.

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#29472]
see title

**Comment by calzilla1** [comment]
F u c k o f f

**Comment by AnonymousNow** [comment]
![](http://c2.thejournal.ie/media/2017/01/why-are-you-752x501.png)

**Comment by Iamgoofball** [comment]
>Buy an E-Mag, which seriously limits their options

since when does an emag limit you lmao

**Comment by AnonymousNow** [comment]
Limits what else you can do with your TCs, ya doofus.

**Comment by Ratvar** [comment]
But you get infinite gear with it, you doofus-you remove all limits original uplink had

**Comment by AnonymousNow** [comment]
Theoretically infinite, which is not likely to be anywhere near viable in normal gameplay.
