### ISSUE TITLE
Slimes no longer generate extra jelly breathing in plasma

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#29482]
@Fox-McCloud

**Comment by XDTM** [comment]
**The real issue is that plasma gas no longer gives you plasma reagent when breathed.**
Toxin damage still increases slime blood volume, and plasma gas does give a small amount of regeneration since it deals 1 tox per tick.

**Comment by Fox-McCloud** [comment]
They absolutely do still regenerate blood by by breathing plasma.

Plasma causes toxin damage *directly* now, as opposed to indirectly (via adding adding the plasma reagent, which itself caused tox damage); this is so we can customize lungs in a far more modular fashion.

Either case, I have no doubt the amount of blood restored is less than it used to.

I'll leave it up to maintainer discretion on what to do here, though, to me, this seems to make things far more consistent, in the long run.

**Comment by XDTM** [comment]
It's a large damage downgrade from breathing plasma, which was an important component of plasma floods. It should probably be adjusted to 3/second to be in line with liquid plasma.

**Comment by Repukan** [comment]
@KorPhaeron This is not a bug, toxin damage just produces more slowly.

**Comment by XDTM** [comment]
From testing it appears the toxin damage goes from 1 o 10 based on gas pressure. Which feels like a bad idea, in my opinion, since you're only going to breathe at higher pressure if you turn an internals tank up, which you pretty much have to do intentionally.

Another thing: what's the point of making tox damage vars for gas if you're going to set them with a define?

**Comment by Fox-McCloud** [comment]
@XDTM 

Because there's a default value; just because you can have a different value on a subset doesn't mean the parent value can't be a define.

For example, reagent's metabolization rate is a define, but there's most certainly different (arbitrary) metabolization rates.

**Comment by FantasticFwoosh** [comment]
Can we just get some plasma wall injectors into the xenobio pens please that'll cause slimes to nourish and split faster and passively when not chewing monkeys? Id happily cart away a plasma container from toxins storage to do it.

Xenobio is such a armchair activity nowadays. Edit - oh i just realised you were talking about slimepeople, nevermind but its a good idea anyway eh @XDTM ? You did check whether slimepeople have livers right?
