### ISSUE TITLE
blowing a borg while riding it deletes the rider

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#29480]
no brain, no gibs

**Comment by Xhuis** [comment]
I can't reproduce this.

**Comment by BeeSting12** [comment]
If the cyborg was emagged that would make sense. Was the cyborg emagged @YakumoChen ?

**Comment by YakumoChen** [comment]
yes

**Comment by kevinz000** [comment]
emagged cyborgs can gib people when they blow up as they have dev explosion radius.

**Comment by MimicFaux** [comment]
not a bug

**Comment by KingPhilipIII** [comment]
I've been killed instantly riding an exploding emagged borg, but not gibbed.

**Comment by DoctoreMad** [comment]
Closeable

**Comment by YakumoChen** [comment]
shouldn't it leave a brain then?

**Comment by Jalleo** [comment]
This is a bug if it is flat out deleting people.

**Comment by Cyberboss** [comment]
Dev explosions don't leave brains
