### ISSUE TITLE
Injured overlay is visible while zoomed out w/ a sniper rifle.

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#29490]
![3mox8as](https://user-images.githubusercontent.com/6209658/28554342-fdf590ce-70c6-11e7-8141-7593e1dc16d8.png)

**Comment by WJohn** [comment]
That's because the overlay is just a 15x15 tile sprite. I suppose this applies universally with other zoom mechanics like mechs, change camera view, and syndie sniper rifles.
