### ISSUE TITLE
You can get on the cargo shuttle while its in transit with this one simple trick!

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#29494]
step 1: Get a bluespace wormhole projector
step 2: shoot one wormhole on the shuttle
step 3: launch shuttle
step 4: go through portal onto shuttle
step 5: ???
step 6: profit

**Comment by BeeSting12** [comment]
It's pretty useless for getting to centcomm though since it deletes mobs on the cargo shuttle upon arrival

**Comment by BeeSting12** [comment]
Nevermind I memed a way onto centcomm

**Comment by banthebantz** [comment]
DELET THIS

**Comment by BeeSting12** [comment]
Okay so replace the question mark with this:
Wait till the shuttle's been gone around 45 seconds and make a new wormhole.
Jump off the shuttle and make a platform.
Shoot another wormhole onto the platform. Wait till you think the shuttle's docked at centcomm, probably about 10 seconds, and go through it. You'll be at centcomm.

**Comment by BeeSting12** [comment]
https://file.house/kRho.png

**Comment by Repukan** [comment]
You can also get noted for it

**Comment by optimumtact** [comment]
hehe, that's very clever
