### ISSUE TITLE
(boxstation) Bridge/Captain's office immune to radstorms

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#29519]
I'll close this if it's intended

**Comment by WJohn** [comment]
I don't think this is the case, it might be #29382 being abused.

**Comment by ShizCalev** [comment]
Confirmed unable to replicate. Was likely #29382 abuse.

**Comment by Tacolizard** [comment]
@BeeSting12 was just the overlay missing? Or were you able to enter the area unharmed by radiation?

**Comment by BeeSting12** [comment]
Not sure, @Tacolizard  , I only saw the overlay since I was a ghost and I briefly flew over and noticed.
