### ISSUE TITLE
Nuke explosion did not actually detonate or display round end text.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#29522]
During nuke ops, the ops successfully blew up the station, but the explosion cutscene never happened, instead staying at the zoomed out view of the station screen and staying there until it vanished, no boom. Everyone still died and the station was still wrecked. Greentext was not displayed at all, though "Rebooting World in 60 seconds. Station destroyed by Nuclear Device." did show. Not sure what the cause was.

**Comment by ShizCalev** [comment]
Didn't happen locally, strange....

https://pastebin.com/51CKmkQL

**Comment by WJohn** [comment]
I don't know if the detonation happened on a space tile or off the zlevel. Test for those?

**Comment by ShizCalev** [comment]
Tried it on mining & CENTCOM z-levels, then on a space tile outside the station, all of them triggered the proper endings.

**Comment by WJohn** [comment]
Looks like my issue is a dupe of #21594
