### ISSUE TITLE
NVG's, thermals, etc make the user see stars outside of vision range instead of normal tiles

### ISSUE THREAD

**Issue by MrDoomBringer** [tgstation/tgstation#29521]
RID# 73852
self explanatory

**Comment by WJohn** [comment]
I think this is due to how we no longer show black space for the edge of the map as totally black, rather as a transparent darker background into yet more space.

**Comment by Jalleo** [comment]
Wait we do that now?

**Comment by ShizCalev** [comment]
http://i.imgur.com/bqcjjfG.png
from #29539 

Honestly I kinda like it, even though it is immersion breaking haha

**Comment by ShizCalev** [comment]
![3munw8d](https://user-images.githubusercontent.com/6209658/28696511-f100a7c0-7303-11e7-8d87-85ad0ad2a9c3.png)
happens for revenants too.

**Comment by callanrocks** [comment]
Its more interesting then the old empty blackness was.

**Comment by FantasticFwoosh** [comment]
Applies also to night vision goggles on lavaland when the line of sight is blocked similarly to the rest.

**Comment by CPTANT** [comment]
No this is pretty bad, it makes it almost impossible to distinguish between out of sight and actual space tiles.

**Comment by TribeOfBeavers** [comment]
Probably related to this: If you put on and take off mesons as an engineering borg you have permenant night vision and see space instead of darkness.

![](http://i.imgur.com/75IcfTs.png)

**Comment by ShizCalev** [comment]
@TribeOfBeavers That's an older issue; #28296

**Comment by ShizCalev** [comment]
Space shows up as grey with this issue if parallax is off.

![image](https://user-images.githubusercontent.com/6209658/28869007-4ebd42e4-7749-11e7-9f18-9982a9889e4e.png)
