### ISSUE TITLE
Freon freezes ratvar's timer.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#29528]
This lets you shut the roundtype down by rushing in with a freon canister and opening it vaguely nearby the portal.

Can we remove freon already it's broken in almost every single way.

EDIT: Can be bypassed by creating a new portal. Still utterly nuts.

**Comment by ChangelingRain** [comment]
If it's disabling the timer, then it's totally breaking the processing subsystem.
God damn it, freon.

**Comment by BeeSting12** [comment]
freon freezes even the server

**Comment by DoctoreMad** [comment]
>Can we remove freon already it's broken in almost every single way.

In this video, TGstation is punished for their sins and is sent to meme hell

**Comment by Iamgoofball** [comment]
Do you have proof it does this

**Comment by DoctoreMad** [comment]
Do you have proof that you're not an idiot
