### ISSUE TITLE
Wearing a t-ray scanner shows out of sight areas as space

### ISSUE THREAD

**Issue by CPTANT** [tgstation/tgstation#29539]
It doesn't even need to be on, just wearing the goggles changes all out of sight areas to show as space.

http://i.imgur.com/bqcjjfG.png

**Comment by WJohn** [comment]
Interestingly, engineering scanner goggles (they yellow ones) which can swap to tray mode do not experience this problem. Meson mode reveals space fully brightly, as intended, and tray mode hides it completely, also intended.

It's optical tray scanners that do this, the black goggles, that show transparent space like in that picture, when both on and off.

Seems related to #29521

**Comment by Supermichael777** [comment]
some naughty person is using blend mode multiply

**Comment by ShizCalev** [comment]
@WJohn It is the same issue.

**Comment by Cyberboss** [comment]
Dupe
