### ISSUE TITLE
Potential Tank Transfer valve bug

### ISSUE THREAD

**Issue by jericho140** [tgstation/tgstation#29548]
Round ID: 73911
interacting with a tank transfer valve in-hand seems to open the attached containers. This happened to me  and another guy although I don't know how to replicate it exactly.

**Comment by CPTANT** [comment]
Are you sure the tanks did not exceed their 3000KPa threshold?

**Comment by GunHog** [comment]
Did it have any attachments? A prox sensor, signaler, etc? Does it happen ONLY when you hold it and click it to open the interface?

**Comment by qbmax32** [comment]
I was the other dude. And yeah it just happened today again. It hasn't exceeded the 3000kpa threshold on either canister. I had made the bombs both times, both with remote sigs. As far as I can tell, it only happens when I open the TTV interface.

**Comment by qbmax32** [comment]
I'll see if I can fuck with it tomorrow at some point, test it. See what happens.

**Comment by Tacolizard** [comment]
@qbmax32 did you ever test it?

**Comment by duncathan** [comment]
this still exist?
