### ISSUE TITLE
Spray bottle heating is bugged

### ISSUE THREAD

**Issue by Hikurac** [tgstation/tgstation#29557]
I was testing out multiple liquid containers and noticed that spray bottles don't heat up from lighters, igniters, etc.

**Comment by YakumoChen** [comment]
Might be for the best, considering it's like a 300 u container

**Comment by kingofkosmos** [comment]
So... bug or a feature? Should this be fixed or issue closed?

**Comment by Cyberboss** [comment]
Should either heat up, or, preferably, break the bottle because it's plastic!
