### ISSUE TITLE
Optical T-Ray Scanner Goggles see space instead of darkness

### ISSUE THREAD

**Issue by TribeOfBeavers** [tgstation/tgstation#29566]
When you use the goggles they see space through the walls instead of regular darkness. Doesn't happen with the double purpose ones engineering has.

![Screenshot](http://i.imgur.com/SbriHde.png)

**Comment by jughu** [comment]
Tbh i like this

**Comment by ShizCalev** [comment]
Dupe #29521

**Comment by CPTANT** [comment]
haha that screenshot is almost literally the one I posted as an example.
