### ISSUE TITLE
Alien Brain Borgs cannot speak GalCom, Only Alien

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#29569]
Might need more testing, but I had an amusing round the other day where I managed to kill an alien queen, gib it, and borg the brain. It would only speak Alien after I put it in the MMI and after I borged it, continued to speak Alien for the rest of the shift. Only the AI could understand it though Robotics Chat.

**Comment by banthebantz** [comment]
Why not both?

**Comment by Supermichael777** [comment]
thats what you get for NT cheeping out

**Comment by FantasticFwoosh** [comment]
- Did you use the appropriate galcom language messages instead of speaking normally? MMI's i think can convert languages since they are linked sometimes to radios within the device but it'd be a easy fix anyway.

> ,0 Hello world (Galcom)

**Comment by Anonmare** [comment]
Could it understand common? It might have been that it's default language was still on alien and they had to simply switch the default in the language menu

**Comment by GunHog** [comment]
From my testing of this, I get the result below. I believe this feature is functioning properly, and that this is simply player ignorance. The language menu and system is pretty tucked away and not needed for most crew, so it is an understandable mistake. Note that the three languages that all silicons must know (GalCom, Draconic, EAL) are present, along with the Xeno's native language.

![screenshot 2017-07-30 22 26 02](https://user-images.githubusercontent.com/4955510/28761709-3bdc9ca8-7576-11e7-87ef-e623f0d3a2a0.png)

**Comment by YakumoChen** [comment]
Well I guess it's not a bug, though perhaps it should force a default so that alien borgs aren't only speaking Alien when they ought to understand and communicate with humans.
