### ISSUE TITLE
Not a single battery module from R&D will go into tablet frames

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#29567]
reee!

**Comment by FantasticFwoosh** [comment]
Freeze and all, but this is not a bug as much as a oversight.

**Comment by YakumoChen** [comment]
kevin is bad and doesn't know about the battery connector module

**Comment by GunHog** [comment]
You have to insert the battery holder thing before you can install an actual battery!

**Comment by FantasticFwoosh** [comment]
Shitty tech companies selling crucial extra's at premium price separate to the product.

**Comment by Anonmare** [comment]
Gotta buy those peripherals
