### ISSUE TITLE
Simplemobs dominated by a runic golem do not appear to be properly inheriting factions

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#29584]
I've done some numerous testing on my own server. 
Test 1: I spawned myself in as an unaligned runic golem and dominated a carp. It gained the Cult faction.
It was friendly to me and hostile to everyone else. I then spawned myself in as a cultist Human. It considered me friendly.

Test 2: I spawned myself in as a ratvar runic golem and dominated a carp. It inherited the bloodcult faction but not the ratvar faction. I then spawned myself in as a ratvar Human and was subsequently attacked. 

Test 3: Traitor golem, same result as above
Test 4: Golem-aligned golem, same result as above

Incidentally, there was a strange interaction when assigning both a cultist and traitor role in that I could see my traitor status on the team HUD, and switching to another cultist body showed the traitor cultist as a traitor first

**Comment by Anonmare** [comment]
As a side note, de-converting a runic golem strips it of its inherent cultist faction and makes its dominated mobs hostile to it.

**Comment by FantasticFwoosh** [comment]
Runic golems are not explicitly cultists on creation rending your previous examples of cult alliegances flawed, though inheritence might be broken, on free golems using salvaged rune metal from ruins it works fine.

**Comment by Anonmare** [comment]
Well tell that to the dominated mobs because I spawned in many runic golems and each one had the cult faction despite not being cultists

**Comment by XDTM** [comment]
Cult golems apply the cult faction on their victims, not all their factions.

**Comment by Xhuis** [comment]
This is intentional; runic golems are only coded to apply and have the cult faction.

**Comment by XDTM** [comment]
De-converting a golem removing its key faction is kind of unintended, though, and may warrant just making a faction for the cult golems

**Comment by octareenroon91** [comment]
Put a few lines in cult golem spec_life to enforce `"cult"` faction membership.

A copy of the caster's faction list would make the target harmless to the crew, typically, no?

**Comment by ExcessiveUseOfCobblestone** [comment]
you would have to remove the neutral faction

**Comment by octareenroon91** [comment]
Quick reminder of what exactly Dominate does.

https://github.com/tgstation/tgstation/blob/057aa31cda6eb47505bc9fdd263fd1427b1276ed/code/modules/spells/spell_types/construct_spells.dm#L268

**Comment by ExcessiveUseOfCobblestone** [comment]
haha oh my lord
