### ISSUE TITLE
engineering scanner goggles have different lighting when you toggle them off meson vision for the first time

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#29589]
1. put on engi goggles, enjoy seeing through walls but still being able to see lighting level
2. toggle engi goggles to t-ray mode
3. turn goggles back to meson mode, observe mysterious lack of lighting

**Comment by PraiseRatvar** [comment]
they have normal/old meson lighting when you do this

**Comment by ShizCalev** [comment]
Dupe #28296

**Comment by ShizCalev** [comment]
Duplicate of #26918
