### ISSUE TITLE
Void Torches can be used to identify cultists by noncultists.

### ISSUE THREAD

**Issue by KingPhilipIII** [tgstation/tgstation#29594]
Right. So. Officer killed me in a raid on my cult base. Grabbed a void torch lying on the ground, which can teleport shit to people. Officer remarks to Lawyer in brig that she can see a list of all the cultists. I think the problem here is evident.

They used this torch to hunt down remaining cultists that were still incognito.

**Comment by calzilla1** [comment]
Amazing

**Comment by Shadowlight213** [comment]
150 hours of testing

**Comment by MoreRobustThanYou** [comment]
time to drop maxcaps onto cult bases
