### ISSUE TITLE
Devils become permanently unable to move if stunned during devil jaunt.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#29607]
Steps to reproduce:
1. Have devil perform devil jaunt
2. Wait until he's about to jaunt
3. Hit him with a lightning bolt packet, which will stun him
4. He will be permanently on fire and unable to move, though can still rotate by clicking.

Seems to be either a dupe or otherwise related to #23025

**Comment by Repukan** [comment]
Dupe
