### ISSUE TITLE
Devil objective bug

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#29609]
1: You shouldn't see this text. Error:DEVIL5 Edit Delete Toggle Completion
2: Purchase, and retain control over at least 8 souls. Edit Delete Toggle Completion

It was an actual devil agents round, admin forced. All devils got the first objective there.

Also show all devil info in the check-antagonist panel does nothing, stating "Target is not a devil." Even though they most definitely are.

**Comment by PraiseRatvar** [comment]
@Cyberboss close thy issue

**Comment by MoreRobustThanYou** [comment]
Nope, still happening
