### ISSUE TITLE
Devil pitchfork is not initialized.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#29608]
@Cyberboss 
Also why can you drop this thing? Shouldn't it vanish like you dispel it if you drop it? Why do you have to use the spell a second time to get rid of it?

**Comment by lordpidey** [comment]
It's intended that they can be stolen/disarmed.  Devils can have a lot of obscure weaknesses if you look at them in the codex gigas.  Find one weak to bright lights?  Super easy to steal his pitchfork if he goes on a rampage.

**Comment by Ratvar** [comment]
Soulsold one also can use pitchforks, i think, so, yeah, intended to be droppable
