### ISSUE TITLE
Rapid Cable Layer ended up INSIDE the CE

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#29616]
![yes](http://puu.sh/wYkxa/455c3a6542.png)
notice the entry on the very bottom

He said in ahelps that this happened when he went to put more wire into it

**Comment by MoreRobustThanYou** [comment]
what the fuck why

it's like WGW with cables

**Comment by MoreRobustThanYou** [comment]
i'll see if i can find what caused this

**Comment by MoreRobustThanYou** [comment]
```

<bgobandit> Oh, CE-senpai!

<Xhuis> lay your cables all over me senpai engineer

<bgobandit> I'm alive and I want to be INSIDE OF YOU.

```

**Comment by bgobandit** [comment]
One day while the CE was engineering, the cable coil got stiff. He could no longer help himself! He watched as the CE hacked his juicy kawaii airlock. He approached the CE which startled him and make him pee everywhere on the tiles and on the cable coil too. Being drenched in his urine made the coil stiffer than ever! 

the cable coil: "CE Senpai! I'm alive and I want to be INSIDE OF YOU." 
CE: "Oh cable-chan! I always knew you were alive! I want to stuff you up my kawaii ass!" The CE grabbed a bunch of flavored space lube and rubbed it all over the cable coil. CE: "Oh my! It's cherry flavored lube! Cherry is my favorite! The CE then stuffed the cable coil up into his tight ass! The other tools around the office watched intently as the CE shoved the cable coil back and forth into his nice ass, continuously making a squishy wet noise. The other tools also became aroused and they all gathered around the CE and started to urinate all over them, and then they started to work. CE: "Oh my goodness, cable-chan! You are churning my insides up so well! Your coil is stimulating my prostate! OH YES! All the other tools became so aroused by this, that they could not help themselves anymore! They pushed the cable coil completely inside, and they all went inside. All of them wanted to be inside the CE's nice round ass. CE: "No wait guys! My ass cannot hold this much! I'm getting so full! All the tools went inside of the poor squirming CE and pretty much, he was beyond full, and died from having his insides completely damaged. The captain came inside and found the CE, dead with a huge ass hemorrhage on his anus, with a HUGE belly full of tools.

**Comment by PKPenguin321** [comment]
<oranges> https://github.com/tgstation/tgstation/blob/22e60ddb444bf8183e30a2ee606dd408e924bd60/code/game/objects/items/weapons/RCL.dm#L26
<oranges> this takes more than one argument
<oranges> should be W, src probably
