### ISSUE TITLE
Monkeys can't hide using potted plants

### ISSUE THREAD

**Issue by Qbopper** [tgstation/tgstation#29629]
Not really a bug, but I feel like this should certainly be a thing

I'd imagine holding a potted plant just changes your sprite to the plant, and it specifically does it for human mobs, hence the problem?

**Comment by PraiseRatvar** [comment]
sounds like a bug to me

**Comment by Qbopper** [comment]
I haven't actually checked potted plant code so it could just be an unintended side effect

**Comment by FantasticFwoosh** [comment]
I thought monkeys couldn't doublehand objects?

**Comment by Qbopper** [comment]
I feel like they should be able to, that's a bit odd

**Comment by PraiseRatvar** [comment]
i.   think i used the chappys warhammer

**Comment by RemieRichards** [comment]
Monkeys are specifically excluded from all twohanded items.
There's no bug here.

**Comment by bgobandit** [comment]
maybe monkeys could get a Hide verb like alien larvae?

**Comment by Qbopper** [comment]
I don't know about a hide verb, but I think it would be a good touch to make it so monkeys can use potted plants to hide

unfortunately I don't know how you could do that cleanly

**Comment by KorPhaeron** [comment]
Not a bug

**Comment by Qbopper** [comment]
I don't mind it being closed but why have the other tags if issues are just for bugs
