### ISSUE TITLE
Bans and notes do not save Round ID in which they were applied

### ISSUE THREAD

**Issue by Repukan** [tgstation/tgstation#29633]
You gotta log BIG TO GET BIG C'MON

**Comment by Cyberboss** [comment]
Yes they do, explain what the problem is you meme

**Comment by Repukan** [comment]
I asked two mins and they told me they don't

**Comment by Jordie0608** [comment]
Ok well they're wrong.
https://github.com/tgstation/tgstation/blob/master/code/modules/admin/DB_ban/functions.dm#L125
https://github.com/tgstation/tgstation/blob/master/SQL/tgstation_schema.sql#L74
