### ISSUE TITLE
Command reports aren't being logged

### ISSUE THREAD

**Issue by pubby** [tgstation/tgstation#29639]
Apparently command reports haven't been logged since March, which roughly coincides with commits 0c97f42d63e and  f096307c206c5 (but I don't see anything wrong with them so maybe it was another commit).

Testing locally I can get them to log correctly, but grepping the past few months of Bagil and Sybil returns nothing.

**Comment by MrStonedOne** [comment]
show me some example log line.

something could be causing it to get filtered or censored by the public logs script.

**Comment by Cyberboss** [comment]
@nfreader

**Comment by pubby** [comment]
@MrStonedOne 

`[13:29:38]ADMIN: Pubby/(Peter Lineman) has created a command report: Hello world!`

**Comment by MrStonedOne** [comment]
oh, its triggering for the old has created a note line, so its getting filtered

**Comment by Cyberboss** [comment]
Server side issue

**Comment by PraiseRatvar** [comment]
👏

**Comment by pubby** [comment]
@MrStonedOne 
I think something broke. Nothing is being logged now.
