### ISSUE TITLE
"Bloom" Mining bot bug

### ISSUE THREAD

**Issue by zacmanthedamned** [tgstation/tgstation#29643]
[Note]: # (<B>Please enter the `Round ID` from the `Status` panel if you can!</B> If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

Round ID 74163, TGstation Sybil
While playing as a Minebot, game client crashed after several minutes (no distinct trigger). After re-launching and connecting, the game screen was heavily blotted out by white colour - similar to extremely high-intensity bloom. Attemts to reconnect, restart the client, restart windows and purge cache did not fix it, however Ghosting did. Bloom effect was serious enough to render the game unplayable.
![wat](https://user-images.githubusercontent.com/30655378/28871226-40f7342c-77b6-11e7-93ac-f503b2e61320.png)

**Comment by ShizCalev** [comment]
Perhaps related to #26523

**Comment by PraiseRatvar** [comment]
and #29248

**Comment by PraiseRatvar** [comment]
@MrStonedOne
