### ISSUE TITLE
AI cores lack a bolting apparatus.

### ISSUE THREAD

**Issue by KingPhilipIII** [tgstation/tgstation#29649]
Right. So I've noticed lately as an AI that anchoring myself doesn't actually stop anyone from moving me.

**Comment by ShizCalev** [comment]
#25894 ?

**Comment by KingPhilipIII** [comment]
Pushing past me on help intent.

**Comment by ShizCalev** [comment]
dupe then

**Comment by KingPhilipIII** [comment]
'Aight. Closing.

**Comment by Cyberboss** [comment]
Duplicate of #25894
