### ISSUE TITLE
chemicals on basil not metabolizing

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#29650]
[RIP medical

**Comment by Cyberboss** [comment]
This is very generic for something we know works 99% of the time and I'm thinking it's just an MC crash. Unless you have repro steps I'm gonna close this

**Comment by MrStonedOne** [comment]
I got a report from some downstream on something similar

**Comment by Cyberboss** [comment]
@Tacolizard

**Comment by MimicFaux** [comment]
I think it might be tied to the '___looks a bit grossed out' upon examining.

**Comment by PraiseRatvar** [comment]
@Qustinnus

**Comment by Qustinnus** [comment]
I'll go look into it.

**Comment by Qustinnus** [comment]
Also if it's happening on a downstream it might not be my PR as that is not merged yet downstream.

**Comment by AnturK** [comment]
Likely fixed by #29653

**Comment by BeeSting12** [comment]
This did happen but it no longer appears to be.

**Comment by Tacolizard** [comment]
this isn't my fault probably.

also nice detailed bug report you got there

**Comment by Tacolizard** [comment]
@AnturK the stomach only processes nutriment though, so I don't know how that would fix this

**Comment by Tacolizard** [comment]
@MimicFaux what race were you when you experienced this? did you have a liver? please provide more details, this report isn't at all helpful

**Comment by Qustinnus** [comment]
this is already fixed but the issue just wasn't closed

**Comment by Tacolizard** [comment]
@Dorsisdwarf close this please
