### ISSUE TITLE
Bloom Glitch. (Possible fix?)

### ISSUE THREAD

**Issue by KnightofDark001** [tgstation/tgstation#29663]
Round ID 74194
This glitch has occurred several times on TG Station, and only once on a different station (name I cannot recall.) As for how it occurs it has only happened to me when I was in the "drone" mode, I have shitternet, so I lose connection quite often. In this case it has happened to be where as I am a drone, that if I lose connection a odd bloom glitch happens, lighting seems to be brightened, so any source of light emits a near blinding white light. As for how to fix it, I had to suicide as a drone, simply getting out of the mode entirely. (sorry if the layout of this issue is odd, I am new to github.)

**Comment by Bombpants** [comment]
Same issue happened with me. Constant loss of connection and visual bugs to boot.

**Comment by Mitchrock** [comment]
Happened to me as well, though I was playing Revenant.

![2017-08-11 01_12_49-sybil_ death-world town 33](https://user-images.githubusercontent.com/1880163/29206876-b90705e0-7e38-11e7-849e-b0d2db64b7e4.jpg)

Happened on relog in attempt to fix another bug.

**Comment by ShizCalev** [comment]
Can consistently trigger this when relogging as a spider. Ghosting and reentering body as an admin fixes it.

**Comment by RandomMarine** [comment]
\>be drone
\>round 76572
\>disconnect like I always do
\>get back in
\>this shit happens
\>reconnecting or fussing with parallax doesn't help
\>get an idea. Ghost then let an admin put me back in the drone.
\>it works
\>drone around for another fifteen minutes
\>it happens again
\>FUCK

![dronfuk](https://user-images.githubusercontent.com/6583225/30794489-3273639e-a17d-11e7-8253-c0767728d6d9.png)
On an unrelated note, this inverted lighting bug could make a cool feature if we ever want a mob that can see in darkness but can't see what's lit up.

There's also no sound while this is occurring.

**Comment by ShizCalev** [comment]
Fixed by #31299
