### ISSUE TITLE
Using Dead cultist to use sacrifice rune

### ISSUE THREAD

**Issue by jericho140** [tgstation/tgstation#29661]
Sybil Round 74187
How to reproduce:
Step 1: Have alive cultist
Step 2: have dead cultist
Step 3: place both next to rune with valid target on said rune
step 4: the rune will activate

**Comment by Xhuis** [comment]
I can't reproduce this.

**Comment by FantasticFwoosh** [comment]
Is the dead culstist's ghost currently inside their body? Easy way to do this is the "re-enter corpse" action from the ghost tab

**Comment by ShizCalev** [comment]
Will close in a week without another repo
