### ISSUE TITLE
L6 Saw 1.95x129mm Hollow-Point are too good.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#29674]
Hollow point for the l6 saw does 60 brute and has -10 armor penetration. It also only costs 6 TC, the same as all other L6 saw ammo types and the standard rounds.
Some side by side tests:

Unarmored:
Regular: 45 Brute (3 Shots)
Hollow point: 60 Brute (2 Shots)
NOTE: This is the most common thing you'll fight.

Regular vest: 30% Bullet resistance
Regular: 33.75 (3 Shots)
Hollow point: 36 (3 Shots)
NOTE: Most officers you'll fight have this armor.

Bulletproof vest (no one uses this and there's only one): 60% Bullet resistance.
Regular: 20.25 (5 Shots)
Hollow point: 18 (6 Shots)
NOTE: This is the highest bullet resistance you are likely to find anywhere. The ONLY time regular is better. By one shot. And only one person can even wear this, if they're insane enough to believe RNG hitting other limbs for the full 60 isn't going to happen.

Sec/HoS hardsuits: 15/25% Bullet resistance respectively, worse than a regular old vest.
Regular: 40.5/36 Respectively (3 shots)
Hollow point: 45/39 Respectively (3 shots)

Captain's carapace: 40% Bullet resistance
Regular: 29.25 (3 Shots)
Hollow point: 30 (3 Shots)

Captain's hardsuit: 50% Bullet Resistance
Regular: 24.75 (4 Shots)
Hollow point: 24 (4 Shots)
NOTE: Doesn't even come off as worse against the most important target.

I say we greatly raise the negative armor penetration. Maybe to -30 or something, with a few tests run on it.

**Comment by PraiseRatvar** [comment]
let me see other nukie weapons b4 i give an intellectual reply

**Comment by ShizCalev** [comment]
Hollow points should be doing less damage against armored targets compared to FMJ rounds, as hollow points do not have the same penetrating properties (the rounds are meant to mushroom on impact causing more damage to soft targets by increasing surface area, as opposed to the jacketed casing of FMJ which limits the deformation of a bullet on impact, leading to it penetrating deeper when striking harder/armored targets.) 

It's not really that they're too good, it's more of an issue of them being unrealistic; in that they're supposed to be better against the normal unarmored crew than they are armored officers.

**Comment by PraiseRatvar** [comment]
holy shit who made the L6 its unbalanced as shit

lower hollow to like -50 AP

and while you are at it lower the damage of every L6 bullet (excluding
incen) or increase its TC cost because the L6 outvalues the C-20R by like
every stat

**Comment by lzimann** [comment]
Use forums
