### ISSUE TITLE
everyone is a bit grossed out at all times

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#29672]
also take a look at #29669

**Comment by PraiseRatvar** [comment]
@Qustinnus

**Comment by AnturK** [comment]
https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/carbon/human/examine.dm#L228 

0 -> 1

**Comment by Qustinnus** [comment]
https://github.com/tgstation/tgstation/pull/29666 already a pr open
