### ISSUE TITLE
Sibyl: Emoji and language icons are broken and display the wrong thing

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#29671]
No, it isn't just me, I made sure of that just in case @Shadowlight213 was meming again. 

No matter what emoji people type, it comes out as the clown emoji. Language icons are affected as well, so if you try to speak for instance Draconic, the icon is also that of the clown. This is on Sibyl only, Bagil is fine.

HONK and/or FUCK tags pls

EDIT: MrStonedOne: you fucked up the caching 
everything gets the first icon loaded 
https://file.house/_sPv.png

**Comment by Shadowlight213** [comment]
:clown_face:
