### ISSUE TITLE
icons in chat are really blurry sometimes

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#29673]
![lol](https://puu.sh/x0vwL/3535c2c3f0.png)

**Comment by PraiseRatvar** [comment]
![screenshot_2017-08-03-16-02-58](https://user-images.githubusercontent.com/28678854/28923062-491b0d9a-7865-11e7-8a7f-b0d39e8a93d2.png)
boi the bottom half of that implanter is just Gone

**Comment by lzimann** [comment]
Probably caused by #29575

**Comment by MrStonedOne** [comment]
I could scale them to world.icon_size if they aren't and then have the browser scale them down to fit on a line.

Then I can have ie9 and up also use the fancy scaling args to control how it scales.
