### ISSUE TITLE
When bomb explode kudzo vine floor it create metal

### ISSUE THREAD

**Issue by furryowl** [tgstation/tgstation#29694]
![bugg](https://user-images.githubusercontent.com/14878501/28938636-576c5d90-7897-11e7-9a7b-0c8672afb4ee.png)

**Comment by Tacolizard** [comment]
do you speak english

**Comment by banthebantz** [comment]
When the act of commencing the act of bombo explodo kudzo space plant vine metalo is create

**Comment by Ratvar** [comment]
when boom floortile
