### ISSUE TITLE
random potted plant inside machine on DeltaStation

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#29710]
![dreamseeker_2017-08-04_16-37-37](https://user-images.githubusercontent.com/28678854/28975807-61eabe00-7933-11e7-859d-0b6707819bbf.png)

@ShizCalev

**Comment by PraiseRatvar** [comment]
its inside in the augment machine in robotics btw, forgot to point that out

**Comment by pubby** [comment]
That's Delta station.

**Comment by PraiseRatvar** [comment]
how retarded am i with maps.
