### ISSUE TITLE
shitty fire alarm placement on DeltaStation

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#29715]
![dreamseeker_2017-08-04_17-56-54](https://user-images.githubusercontent.com/28678854/28978814-6ef49272-793f-11e7-85af-7d1a23dc6df2.png)
how do you even get to there????

**Comment by WJohn** [comment]
Deltastation has a number of buttons and fire alarms tucked into corners behind objects. They're still actually clickable, but not at all obvious where they would be.
