### ISSUE TITLE
White-Screened GUI Bug. (Please help.)

### ISSUE THREAD

**Issue by KnightofDark001** [tgstation/tgstation#29723]
I have no clue why this is occuring, to my knowledge it seems as if the game is just bugging out or something else is happening. All I know is whenever I try to interact with objects like a vending machine, or say something more important like a Terminal it seems to now only be getting this weird WHITE screen. No idea how to replicate it, just know that it exists. Here's a screenie
![weirdbugthing](https://user-images.githubusercontent.com/30680644/28991037-587279f8-7951-11e7-8162-a717a35dcbca.PNG)

It also appears that when I am at the start of the round, that when I try to interact with anything like the "Ready" button, it does not change itself so it shows that ready is selected. It instead just simply sits there, as if it were frozen. I have been searching all over for a solution, PLEASE someone help me out here.

**Comment by PraiseRatvar** [comment]
have you tried waiting for about 15+ seconds or so, it should fix itself.

**Comment by Armhulen** [comment]
it does fix itself but i looooooooove working with tickets that are a white screen FIX IT

**Comment by KnightofDark001** [comment]
I have waited at least 30 seconds for the white box to fix itself, nothing changed.

**Comment by Tacolizard** [comment]
>(Gamebreaking bug.)

**Comment by Tacolizard** [comment]
do you have the latest version of internet explorer?

**Comment by KnightofDark001** [comment]
To my knowledge I believe I do, though even then I dont think internet explorer prompts you when it is "out of date"

**Comment by Tacolizard** [comment]
@KnightofDark001 either you do or you don't. please update it, and update BYOND

**Comment by KnightofDark001** [comment]
Byond is always kept up to date, as for internet explorer it is also up to date.

**Comment by KnightofDark001** [comment]
UPDATE: Apparently after 3 days it has decided to fix itself, not sure why but it DID.

**Comment by ShizCalev** [comment]
No longer an issue then.
