### ISSUE TITLE
Lich glitch

### ISSUE THREAD

**Issue by sirnat** [tgstation/tgstation#29722]
Round ID: 74268

What happened: 
I was a lich wizard, got killed and waited to respawn, when I did respawn I didn't have any of my spells which included: Fireball, jaunt, and magic missle. 

Had my round ruined by this bug and hope a solution can be found, or if it can be explained why it happened.

**Comment by ShizCalev** [comment]
How did you die?

**Comment by sirnat** [comment]
Got gangbanged but they didnt incin my body. I still respawned at the ensouled object

**Comment by BeeSting12** [comment]
hey dat rhymes!

**Comment by MimicFaux** [comment]
I've had this happen to me. Lost my spells the first time (was incin'd) was given a second spellbook by admins, subsequent deaths I remembered my spells through death

**Comment by AnturK** [comment]
Duplicate of #28846
