### ISSUE TITLE
White Tile Artifacting

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#29738]
![whitestuff](https://user-images.githubusercontent.com/6266927/28999385-cfaf5ebe-7a3c-11e7-8496-7d7b0a19db04.png)

Happened when I observed a round. Don't know what it was, what caused it or how to reproduce it, but it's not the first time I've seen it.

**Comment by ShizCalev** [comment]
Do you have parallax turned off by chance?

**Comment by bgobandit** [comment]
This sometimes happens if your computer is lagging or if your BYOND graphics settings are fucky

**Comment by AnturK** [comment]
Same as your other PR, update your byond.
