### ISSUE TITLE
Exploding plasma golems drop livers (and possibly other golems)

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#29736]
![dreamseeker_2017-08-05_20-49-06](https://user-images.githubusercontent.com/28678854/28998339-03e8b8a0-7a20-11e7-9c92-6417e0c08078.png)
@Tacolizard

**Comment by Ratvar** [comment]
Feature. They use liver to dream.

**Comment by Tacolizard** [comment]
yes, this should happen for all golems.

golems have livers because without them they would be unable to process reagents. I just don't have any golem-specific sprites so i was lazy and used human livers.

**Comment by Ratvar** [comment]
Use xenoarch rock sprite?

**Comment by Tacolizard** [comment]
@PraiseRatvar please change your title to update with the comment i made

**Comment by PraiseRatvar** [comment]
taco. they ONLY drop livers upon their exploding death

**Comment by Tacolizard** [comment]
are you sure other organs didn't fall into the lava?

even if they just drop livers, it's not that weird and it's not a bug

**Comment by AnturK** [comment]
What's exactly the problem here ?

**Comment by Tacolizard** [comment]
@AnturK I have no idea

**Comment by PraiseRatvar** [comment]
forgot about this issue.

basically i exploded as a plasma golem and i see only my liver dropped
instead of all my organs so what did/was supposed to happen?

a) all my organs apart from my liver fell into lava (which i dont think
what happened)
or
b) my liver dropped when i exploded when it shouldn't be dropping
or
c) i am supposed to drop all my organs upon explosive death

(typed this on a phone so i might've not explained the issue well)

**Comment by ExcessiveUseOfCobblestone** [comment]
I think the issue is if you have to make them have a liver then on gib make it delete the liver because golems having livers doesn't really make IC sense.

**Comment by FantasticFwoosh** [comment]
Golems do not have hearts or lungs to drop @PraiseRatvar and from my memory of that round, the golem's head flew off away constituting its brain eyes & ear organs.

- Liver is the odd one out, the only necessary organ all others accounted for

**Comment by KorPhaeron** [comment]
Its RNG which organs survive an explosion
