### ISSUE TITLE
Airtank Toggle Turns Into... Stuff

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#29743]
Unfortunately I don't have a screencap of this, but in the round just passed, my airtank toggle (mid-right of the screen) turned into what looked like a random bit of metal (when off), and then, when I approached the open teleporter room, turned into a teleporter hub.

Still completely functional. But what happened here?

**Comment by MimicFaux** [comment]
admemes var editing is my guess.

**Comment by Tacolizard** [comment]
@Dorsisdwarf close this?

**Comment by AnonymousNow** [comment]
Seems strange, since there was no other evidence of editing buggery in the round.

**Comment by AnturK** [comment]
This sometimes happens when using outdated byond. Purge the cache and update.
