### ISSUE TITLE
slime people get grossed out by their own food, then vomit (which harms slimepeople)

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#29744]
slime people now cannot eat slime based foods, which should be healing them (due to being made of their own blood), and it gives them toxins damage which is impossible to remove.

**Comment by PraiseRatvar** [comment]
@Qustinnus

**Comment by Qustinnus** [comment]
what food did you eat specifically? slime people can't eat dairy or meat so if the food had either of those that is why.

**Comment by YakumoChen** [comment]
slime cake.

**Comment by Qustinnus** [comment]
that has dairy which slime people dislike.

**Comment by Qustinnus** [comment]
this can be closed seeing as this isn't really a bug

**Comment by YakumoChen** [comment]
>Slime cake
>People can't eat it because it's got slime
>Slime people can't eat it because it's dairy
why does this exist then????

**Comment by YakumoChen** [comment]
I don't really see how it makes sense for slimes to dislike dairy and meat, that basically limits them severely on anything they can eat and they already have severe hunger problems.

**Comment by Qustinnus** [comment]
guess you're going to be a vegan slime person from now on bud

**Comment by octareenroon91** [comment]
1. The slime cake recipe uses a slime extract, so there's no slime reagent to be expected in the final product.
2. Lime juice, tricordrazine, or omnizine should cure tox damage without removing a slime's slime blood.

**Comment by octareenroon91** [comment]
````
modules/food_and_drinks/food/snacks_cake.dm:
/obj/item/weapon/reagent_containers/food/snacks/store/cake/slimecake
	name = "Slime cake"
	desc = "A cake made of slimes. Probably not electrified."
	icon_state = "slimecake"
	slice_path = /obj/item/weapon/reagent_containers/food/snacks/cakeslice/slimecake
	bonus_reagents = list("nutriment" = 1, "vitamin" = 3)
	tastes = list("cake" = 5, "sweetness" = 1, "slime" = 1)
	foodtype = GRAIN | DAIRY | SUGAR


modules/food_and_drinks/recipes/tablecraft/recipes_cake.dm:
/datum/crafting_recipe/food/slimecake
	name = "Slime cake"
	reqs = list(
		/obj/item/slime_extract = 1,
		/obj/item/weapon/reagent_containers/food/snacks/store/cake/plain = 1
	)
	result = /obj/item/weapon/reagent_containers/food/snacks/store/cake/slimecake
	subcategory = CAT_CAKE

````

**Comment by Iatots** [comment]
>eggs

>dairy

REEEEEE

**Comment by XDTM** [comment]
Any tox damage healing WILL harm slimepeople and remove blood, no matter the source. They need poison to heal.
Slime extracts contain slime jelly if grinded.
Also, slimes eat monkeys, why would they be vegan? They should probably avoid vegetables, due to the connotation of them being healthy, and slimepeople being hurt by stuff that heals toxins.

**Comment by Qustinnus** [comment]
im willing to change meat to vegetables but dairy is staying

**Comment by Iatots** [comment]
I don't see why 
Milk is the most basic food
eggs are the closest thing to a slime, big fat single cells.

In fact I'd rather it be similar to what xdtm said: slimes are strictly carnivores and eat all animal products.

**Comment by Qustinnus** [comment]
I can make them strictly carnivores but that means grain also gets put in the dislike list which only make more slime food inedible for them

**Comment by DoctoreMad** [comment]
**What.**
Why is dairy bad for slimepeople?
Are we just going to have slime people feed themselves using chemistry now?

**Comment by YakumoChen** [comment]
Why the fuck are we giving slime massively debilitating food restrictions in the first place when their gimmick is already "I eat everything"

**Comment by YakumoChen** [comment]
They can't even eat donuts and that's the most basic food on the station

**Comment by Qustinnus** [comment]
i mean feel free to remove the dislikes in a PR if you really feel like it and then if people want it to be changed it'll be changed.

**Comment by YakumoChen** [comment]
Why does he his even exist in the first place though

**Comment by YakumoChen** [comment]
If when I am playing a race that has the main gimmick of increased hunger and I would literally rather grind everything I eat to avoid getting sick rather then enjoying a food system you have a basic design problem at the core.

**Comment by Qustinnus** [comment]
because i made the system and added dislikes and likes to every species, if you want to remove it, remove it. you don't need to try and lecture me about design.

**Comment by DoctoreMad** [comment]
​>Hey dude you should change X
​>Nah if you hate my PR you should remove it
I take it he was agreeable.

**Comment by octareenroon91** [comment]
Q never said remove the whole PR.
