### ISSUE TITLE
bloom bug as drone

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#29751]
![dreamseeker_2017-08-06_21-58-29](https://user-images.githubusercontent.com/28678854/29007028-d2a5b1de-7af2-11e7-9b33-5664660460e3.png)
decided to becom drone, found pai and got a pai, couldn't hear myself, reconnect, BLUM BUG

**Comment by ShizCalev** [comment]
Duplicate of #29663

**Comment by Cyberboss** [comment]
Duplicate of #29663
