### ISSUE TITLE
Clothes can not be repaired with cloth, code is redundant & bugged.

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#29774]
- 150 hours of testing obviously

To run though the event where i discovered this, i had my jumpsuit (red pants from autodrobe) partially burnt and damaged, i then walked into hydroponics and printed a roll of cloth to put this to the test, and naturally it failed.

[This is the code](https://github.com/tgstation/tgstation/blob/c7c557162fb6bed7de77c740ae6755496ad03d59/code/modules/clothing/clothing.dm#L79)
```DM
/obj/item/clothing/attackby(obj/item/W, mob/user, params)
	if(damaged_clothes && istype(W, /obj/item/stack/sheet/cloth))
		var/obj/item/stack/sheet/cloth/C = W
		C.use(1)
		update_clothes_damaged_state(FALSE)
		obj_integrity = max_integrity
		to_chat(user, "<span class='notice'>You fix the damage on [src] with [C].</span>")
		return 1
	if(pockets)
		var/i = pockets.attackby(W, user, params)
		if(i)
			return i
	return ..()
```

As you can see it should clearly state that there is a chat-log response and the damage is fixed in exchange for consuming the cloth, however this is not the case and i tried taking my jumpsuit on and off to try applying the cloth to it without it working.

- To note, this is the only way any clothes can be repaired via this generic repairing funtion, even spacesuits as dumb as that may sound so its a important fix required in the case of unique clothes that are hard to replace.

- To replicate; damage clothes by burning them partially, aquire cloth from a biogenerator and try multiple ways of fixing it.

**Comment by RemieRichards** [comment]
>even spacesuits as dumb as that may sound so its a important fix required in the case of unique clothes that are hard to replace.

I have a hard time believing you tested anything other than jumpsuits, as as far as I can see, the issue is specific to jumpsuits (the code you pointed out gets ignored by jumpsuits)

**Comment by FantasticFwoosh** [comment]
Remie there's literally no code attached other than 'damaged_clothes' to even differentiate, so i feel safe enough to say something like that without sounding inaccurate or particularly idiotic.

- But good point made, always a good idea to push testing.

**Comment by RemieRichards** [comment]
You're wrong, it's an unwanted "feature" of DM that methods (functions) can be overridden multiple times, with the last one taking priority, and as my PR shows, there was a shitty one that did nothing but handle attachments (ties/medals)

so yes, it was jumpsuit only.

**Comment by RemieRichards** [comment]
also, for reference, you should use triple back ticks ` not single for multiline code (I've fixed it for you)
