### ISSUE TITLE
All languages other than Galactic Common are prone to not working

### ISSUE THREAD

**Issue by tortellinitony** [tgstation/tgstation#29776]
This has occurred with several languages, but I initially spotted it with Beachtongue. Someone on Hippie Station just reported that it is happening with drones now, too. I tested it and found that no language other than Galcom works. When you speak in the language, nothing appears in the chat (but you do get a speech bubble)! Radio, normal, whisper, and any other type of speech does not work! Switching to the old chat instead of Goonchat does not work either!

See also:
#28498
#29762

**Comment by Darkgenerallord** [comment]
Just had it happen with some ashwalkers.

**Comment by PraiseRatvar** [comment]
dronespeak works

**Comment by AnturK** [comment]
Likely caused by #29690 (language icons)

**Comment by MrStonedOne** [comment]
as somebody who has never worked with languages and never plays

I need steps on reproducing, and on debug tools to fuck around with languages so i can figure this out

**Comment by Iamgoofball** [comment]
@MrStonedOne 
admins can grant languages to themselves from the language button in the bottom-middle-right of your hud

**Comment by MrStonedOne** [comment]
this should be fixed
