### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#29783]
![chrome_2017-08-08_04-27-29](https://user-images.githubusercontent.com/4081722/29070062-63a1202e-7bf2-11e7-8494-c40782e603e9.png)

**Comment by outbools** [comment]
godtier emery

**Comment by PJB3005** [comment]
[I'm working on a fix for it but it's still highly work in progress.](https://github.com/space-wizards/space-station-14)

**Comment by Megamaw** [comment]
@PJB3005 add skeletons or it's doomed to fail like the rest, that's the megamaw guarantee

**Comment by Megamaw** [comment]
the emojiocracy thinks i jest

but i know the truth

**Comment by Megamaw** [comment]
this is still an issue
reopen it, baby

**Comment by outbools** [comment]
Why you closed this? 

HAVE YOU RESOLVED IT?

**Comment by RemieRichards** [comment]
We have resolved it.
The dream is dead.

**Comment by Iamgoofball** [comment]
@optimumtact 
![byond](https://file.house/2Cht.png)

**Comment by RemieRichards** [comment]
@Iamgoofball a unique WHAT.

**Comment by Iamgoofball** [comment]
p a s s w o r d
![byond2](https://file.house/WPWa.png)

This is the Director's Cut

**Comment by PJB3005** [comment]
![](http://i.imgur.com/UXtCqoM.png)

The hero we need.
