### ISSUE TITLE
warden can't open his own locker on metastation

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#29787]
@ShizCalev I DEMAND THIS FIXED

**Comment by ShizCalev** [comment]
feature

**Comment by ShizCalev** [comment]
That locker's not vareddited, and the type has proper ACCESS_ARMORY access.

Did you get a jobchange? Did anyone mess with your ID?

**Comment by ShizCalev** [comment]
Cannot reproduce inworld. Might've been an initialization issue with your ID or something.

**Comment by jughu** [comment]
@praiseratvar that was me shooting the locker with the ion gun hence you couldnt open it since it breaks the lock

**Comment by jughu** [comment]
Not an issue.
