### ISSUE TITLE
Abductor Console doesn't work on someone for some reason

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#29788]
I went down, marked him, and then used the retrieve button a few times. I know I marked him properly because I got the message saying I did. He was not an antagonist roundend, if that's relevant. When I attempted summoning him, a black person shaped hole went over him for a moment and disappeared. Marking and retrieving worked for everyone else that I attempted it on that round, about four - five people. Round ID was 74436, the person I was attempting to retrieve was Monte Fleming if this is relevant/anyone wants to check. Didn't get the commit info/testmerges since the round ended too fast.

**Comment by Tacolizard** [comment]
seems like an extreme edge case. this issue can probably be closed

**Comment by AnonymousNow** [comment]
Was he buckled into a chair or something? I found that that's a factor as an abductor myself a few weeks back.

**Comment by AnturK** [comment]
Yes, the teleportation fails if the target is buckled. If that was the case this can be closed.

**Comment by BeeSting12** [comment]
Yeah, he was buckled... woops, I'll close this
