### ISSUE TITLE
Frozen objects don't unfreeze

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#29791]
And frozen turfs do...
@Iamgoofball

**Comment by Iamgoofball** [comment]
>maintainer

>didn't use the format

also, not my fault, I didn't code object unfreezing, bug the guy who did

**Comment by nicbn** [comment]
> I didn't code object unfreezing

That's the problem.

**Comment by Iamgoofball** [comment]
Someone else did.

**Comment by Tokiko1** [comment]
I am fairly sure that's because you guys refactored slipping and unfreezing objects was handled in these. As horrifying as that sounds, it was actually pretty cheap low on the processing.

**Comment by Cyberboss** [comment]
That hasn't been merged yet I think?

**Comment by WJohn** [comment]
Was it test merged, maybe? IDK.

**Comment by AnturK** [comment]
This is just lack of feature not a bug.

**Comment by Cyberboss** [comment]
@Anturk I did code unfreezing things when they get warm enough.

**Comment by AnturK** [comment]
After quick glance at the code i see i was mistaken, they just unfrezee on Entered for some reason

**Comment by duncathan** [comment]
begrudgingly applying the atmos tag grr freon
