### ISSUE TITLE
You can't hit a stunned/knocked out/dead person with a thrown object

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#29806]

**Comment by AnturK** [comment]
Former is not a bug, only humans can embed the latter is actually a bug.

**Comment by Tacolizard** [comment]
@AnturK edit the title to only include the latter half then

**Comment by PraiseRatvar** [comment]
turns out it happens with humans as well

**Comment by Jordie0608** [comment]
Fixed in #60604
