### ISSUE TITLE
tablet has a print feature, if you print something inside of a locker it dispenses the printed paper outside the locker

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#29802]

**Comment by Cyberboss** [comment]
The terror of get_turf() begins

**Comment by RemieRichards** [comment]
annoying one to fix.
if you make it use ```loc```, you're printing paper in mecha that then can't be accessed (I know you cant use your inventory in mecha but still)
if you make it use ```get_turf()```, it will fall out of lockers and things

**Comment by Cyberboss** [comment]
Time to add loc.SensibleDropPosition()

**Comment by DoctoreMad** [comment]
>if you make it use loc, you're printing paper in mecha that then can't be accessed (I know you cant use your inventory in mecha but still)

That sounds like a relatively minor drawback, maybe even a edge case. I don't think anyone will care.

**Comment by Cyberboss** [comment]
My solution is the correct one, it's just a MASSIVE PITA to implement fully

**Comment by RemieRichards** [comment]
@Cyberboss your solution is a shit version of mine, plebian.
