### ISSUE TITLE
Cant slip on wet floors

### ISSUE THREAD

**Issue by Togopalis** [tgstation/tgstation#29824]
People who run on wet floors cannot slip, even without galoshes on. Foam is still capable of slipping. As somebody who plays janitor frequently, this is a very important issue to me.

**Comment by ShizCalev** [comment]
@Cyberboss #29628

**Comment by YakumoChen** [comment]
@Togopalis 
Are you sure they didn't have noslips or active magboots or gravity wasn't off?

**Comment by Togopalis** [comment]
@YakumoChen Yes. I myself tried it on the same round this was happening and I didn't slip, even without shoes on.

**Comment by Cyberboss** [comment]
Round id?

**Comment by Togopalis** [comment]
I'm not sure, it was yesterday late at night. How do I check?

**Comment by Cyberboss** [comment]
Don't worry about it, I found the cause
