### ISSUE TITLE
Mech medibeams keep crossing themselves

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#29827]
somehow it interacts with beams that get stuck.

**Comment by DoctoreMad** [comment]
Amazing.

**Comment by bgobandit** [comment]
Pretty sure this is the same bug as https://github.com/tgstation/tgstation/issues/30229 -- you can spamclick a regular medibeam on someone and cause the same thing. It's not qdelling correctly or on time, I think.

Medbeam code although this may be an issue with how clicks are processed w/ guns in general https://github.com/tgstation/tgstation/blob/af4d9a85c9a3eeef1e5e0637ef4ebd0312794ac7/code/modules/projectiles/guns/medbeam.dm
