### ISSUE TITLE
Creating stacks of floor tiles adds only 1 tile to an existing stack

### ISSUE THREAD

**Issue by Oirgialla** [tgstation/tgstation#29830]
Creating a stack of 4 or 20 tiles adds 1 tile to any stack on the ground. Bit annoying wasting half a stack of metal

Recreate: 
Hold metal in one hand and something in the other
create some floor tiles
create some more

**Comment by PraiseRatvar** [comment]
Dup of https://github.com/tgstation/tgstation/issues/29135

@Dorsisdwarf
