### ISSUE TITLE
Sleeping carp users can wield and use flamethrowers

### ISSUE THREAD

**Issue by ro5490** [tgstation/tgstation#29847]
Round ID was 74532 I think

Just as the title said, I encountered an antag with sleeping carp, an atmos suit, and a flamethrower.
Managed to kill the entire station easily.
If I recall correctly Sleeping Carp is meant to stop the user from being able to use ranged weaponry.

**Comment by jughu** [comment]
Dupe of somewhere

**Comment by ShizCalev** [comment]
@jughu you're probably thinking of #24081
