### ISSUE TITLE
Vending Machines unable to be disassembled, and not dropping any parts when destroyed

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#29850]
Round: 74539
All the vending machines I interacted with during this round reported not having any items loaded. Additionally, I was unable to disassemble them. I tried multiple combinations of crowbar, screwdriver, wrench, and wirecutters. I then destroyed it with a stunbaton that was turned off, and when the machine was destroyed, no components dropped from it at all, or even a machine frame. A medical doctor that round also told me there were no portable crew monitors, which I assume means the medical vendors were not working as well.

**Comment by JStheguy** [comment]
Our new sponsorship deal with Space Cola(TM) and 4no Rasins(UM) means we can't let people dissemble their product placements anymore.

**Comment by lzimann** [comment]
Fixed on #29823
