### ISSUE TITLE
Singulo doesn't like asteroid sand.

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#29857]
it doesn't eat asteroid sand.

**Comment by Kromgar** [comment]
It never has

**Comment by Kromgar** [comment]
Singulo doesn't eat basalt either.

**Comment by ShizCalev** [comment]
Intentional;
https://github.com/tgstation/tgstation/blob/be721a5e689d3ab832463fd7509c0dfebbcd3fea/code/game/turfs/simulated/floor/plating/asteroid.dm#L106

**Comment by GunHog** [comment]
>Singulo doesn't eat basalt either.

If it turned to lava, that would be fantastic.
