### ISSUE TITLE
chat icons going huge

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#29852]
![untitled](https://user-images.githubusercontent.com/10399117/29202203-ba75d226-7e33-11e7-8f42-12f6bc544465.png)

**Comment by Cyberboss** [comment]
@MrStonedOne

**Comment by pubby** [comment]
round isn't over you big gay baby

**Comment by ShizCalev** [comment]
feature

**Comment by Ratvar** [comment]
Yeah, cog is small

**Comment by MrStonedOne** [comment]
Only icons with the class icon are resized

This was intentional to allow bigger icons.

This could only happen if for some stupid reason, clock cult stuff isn't using the bicon system, but instead doing some of its own fucky bullshit.

**Comment by ChangelingRain** [comment]
this is language icons not clockcult icons

**Comment by MrStonedOne** [comment]
ya, but only cult icons do this. all other language icons work fine.

**Comment by MrStonedOne** [comment]
nvm, i found it.

.ratvar					{color: #BE8700; font-size: 48px; font-weight: bold; font-style: italic;}

bicon gives images a class name identical to the icon state, this is old behavior, my new thing makes icons fill the size of the font-size. so this was making the image 48 px high. I'll just change this to give it a css class of icon-[statename]

**Comment by MrStonedOne** [comment]
test merged thingy.. this is fixed
