### ISSUE TITLE
GBS kills far too quickly.

### ISSUE THREAD

**Issue by SyruseEln** [tgstation/tgstation#29862]
Round ID: 74576, on Bagil.
Someone TC traded for GBS and loosed it immediately. I contracted it and 30 seconds later it was stage 4 and I was in crit. Other people were coming into medbay and gibing within a minute of contracting it. GBS did not advance this quickly before the recent virology update.

**Comment by PraiseRatvar** [comment]
@Fox-McCloud @XDTM any idea?

**Comment by XDTM** [comment]
Fairly sure that none of the latest changes should affect nonadvanced viruses.

**Comment by XDTM** [comment]
It is and was a 4% chance of advancing every two seconds, according to the code.

**Comment by XDTM** [comment]
Admin varedit maybe?

**Comment by SyruseEln** [comment]
I have no idea, you would have to ask Armhulenn but I seriously doubt that's the case. I'm going to test it on my own tomorrow to see if this wasn't just a case of a whole ton of people getting very unlucky.

**Comment by ExcessiveUseOfCobblestone** [comment]
That's what actual GBS is suppose to do

**Comment by SyruseEln** [comment]
No? Maybe? Its kinda not fair to die within a minute of showing symptoms. You wont make it to medbay most of the time before you die. And the last time I even saw GBS was before the virology updates and it was no where near this deadly.

**Comment by YakumoChen** [comment]
GBS was adminonly for a reason

**Comment by Armhulen** [comment]
no vars or nothing, the virus kills faster than it can spread tbh

**Comment by GunHog** [comment]
Not an issue! It is an admin virus!!

**Comment by XDTM** [comment]
If gbs does this it's likely other simple viruses do

**Comment by XDTM** [comment]
Currently testing it, it's taking longer than two mintes to even get to stage 2

**Comment by XDTM** [comment]
After testing i think this was just the good ol' BYOND rng. Plus the symptoms show rarely and only from stage 2 onwards, meaning that the disease usually has a headstart before being noticeable, which could give the impression of a too-fast virus.

**Comment by Fox-McCloud** [comment]
This isn't my doing, nor anyone else's fault really. This is just how the disease system works.

You advance through the stages based on probability; sometimes that means you sit at stage 1 forever, other times, you go through all stages in a matter of a few cycles; this was present before my refactor and was present even when I first started playing SS13 in 2013.

**Comment by Dorsisdwarf** [comment]
Just how the game works
