### ISSUE TITLE
you can link stuff in chat

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#29874]
![2017-08-13_12-01-34](https://user-images.githubusercontent.com/28678854/29249046-4a629bfc-801f-11e7-84c8-6604183e5aec.png)
here's the heckin' image
https://media.8ch.net/file_store/dbd4f10ccef3ac22e6552e5dcc58904fe6b79ff77cbf4cb56f4df2b8008eb2ca.jpg

**Comment by XDTM** [comment]
I guess when they said that _a picture is worth a thousand words_ they meant it was a really long link

**Comment by Cyberboss** [comment]
Working as intended
