### ISSUE TITLE
*surrender verb has bad grammar

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#29879]
Tasmin Elliot  puts his hands on his head and falls to the ground, they surrenders!

**Comment by factoryman942** [comment]
also borgs can surrender

**Comment by DoctoreMad** [comment]
The "they" is _"intentional"_

**Comment by pubby** [comment]
It was fixed a few hours ago in #29853

Presumably the server wasn't updated in time.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Cyberboss no longer an issue

**Comment by factoryman942** [comment]
wew
