### ISSUE TITLE
Space Z-Levels Lead to Lavaland

### ISSUE THREAD

**Issue by ninjablooper** [tgstation/tgstation#29875]
Going off a space z-level seems to be able to send the person to the lavaland z-level, thus killing them. This is probably the same way people have been getting to reebe.

**Comment by Kromgar** [comment]
I like the idea of a chance of falling into lavaland orbit when transitioning zs tho

**Comment by Kromgar** [comment]
Also lavalands border can be seen as space with nvgs on

**Comment by Iamgoofball** [comment]
That's a regression from Parallax.
