### ISSUE TITLE
What I did for the tgui component icons doesn't work now

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#29928]
This was kind of a hack probably but hey @MrStonedOne can you fix this thing
https://github.com/tgstation/tgstation/blob/master/code/game/gamemodes/clock_cult/clock_helpers/component_helpers.dm#L66

**Comment by MrStonedOne** [comment]
uhh, that should still work....

**Comment by MrStonedOne** [comment]
but likely you want to use the asset cache,

**Comment by ChangelingRain** [comment]
wellll it kind of doesn't, or at least it failed to load at least once when I opened the slab tgui, and it probably doesn't work for in-chat icons.
