### ISSUE TITLE
Dyed cargo tech jumpsuit is invisible with red "jsuit" text.

### ISSUE THREAD

**Issue by McRex007** [tgstation/tgstation#29938]
I dyed a cargo technician jumpsuit black and it made me naked with "jsuit" above my head in red text. Not that I don't mind being able to go around naked while still wearing a toolbelt, and I would like if that were a feature, but I'd still like to be able to go around in black short shorts as a ligger with digitigrade legs.

**Comment by McRex007** [comment]
Oh, also it seems the cargo tech jumpsuit doesn't have a more casual way of wearing it. Making it just shorts for casual would be pretty cool.

**Comment by nicbn** [comment]
What the

**Comment by ShizCalev** [comment]
Can't seem to replicate this. 
![3n5mwvi](https://user-images.githubusercontent.com/6209658/29505564-0cc90032-8615-11e7-9468-46853f6caaa6.png)


Also adjusting the cargo tech jumpsuit does roll up the sleeves.

**Comment by TheVekter** [comment]
Same here, can't replicate. The cargo jumpsuit already has shorts.
