### ISSUE TITLE
You can remove zombie status by using mutation toxin/transform sting

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#29962]
Laaaaaaame

**Comment by Kromgar** [comment]
Also oddly everyone that got mutation toxined turned into escape-the-shuttles sybil 8/16/2017 6:50 pm est

**Comment by NewSta1** [comment]
This makes me wonder then - is it normal to still have changeling powers (incl. Transform) as a zombie?

**Comment by Kromgar** [comment]
OH WAIT FUCK. It was transform sting wasn't it.

**Comment by XDTM** [comment]
Is zombie NOTRANSSTING? Zombifying people with a sting is both cool as fuck and horribly broken

**Comment by MrStonedOne** [comment]
why is this blame mso?

**Comment by ma44** [comment]
Should be fixed by #30681 as that prevents zombies from being transferred.
