### ISSUE TITLE
Unable to hear radio while in body with admin on

### ISSUE THREAD

**Issue by Gouty** [tgstation/tgstation#29978]
Round: 74835

Really strange bug, Started a round as an assistant without deadmining, could not hear radio, assumed tcomms was fucked so went to help fix it, got there and couldn't interact with any of the Tcomms equipment (even though it looked to be all working fine) tried a Station Bounced Radio and it did not work.  

Deadmined and could hear radio
Readmined and could not
Aghosted and could hear radio

I'll try it again next round and see if I can reproduce

**Comment by MrStonedOne** [comment]
its a admin preference

**Comment by MrStonedOne** [comment]
why it exists, i don't know

**Comment by Gouty** [comment]
I can't find the option, what tab is it under?
