### ISSUE TITLE
430 hard deletions (didnt_gc) of lighting objects

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#30006]
Round ID 74872
Is it just me or is this a bad thing?!

**Comment by Cyberboss** [comment]
KEV DOES YOUR ADMIN BS DELETE LIGHTING OBJECTS?

**Comment by kevinz000** [comment]
No

**Comment by Cyberboss** [comment]
Round ID?

**Comment by kevinz000** [comment]
![screenshot_20170817-222147](https://user-images.githubusercontent.com/2003111/29445245-8b6180b8-839a-11e7-99b1-22a1e716cd8e.jpg)
Uh cyberboss...

**Comment by Cyberboss** [comment]
Fixed by #30684
