### ISSUE TITLE
Drag-and-drop to empty containers isn't happening.

### ISSUE THREAD

**Issue by octareenroon91** [tgstation/tgstation#30007]
Drag-and-drop to empty containers isn't happening. No messages in chat, nothing. Can't dump to floor.

Round ID 74877
Revision 093cb1a184f5a4d31ad71e8f522827f3493c5a69

**Comment by Cyberboss** [comment]
@AnturK you added some `/weapon`s with your inventory PR, does #30005 fix this?

**Comment by octareenroon91** [comment]
Looks favorable

**Comment by Sartorius7** [comment]
Drag-and-drop to floor doesn't work, but you can drag-and-drop to tables.

**Comment by AnturK** [comment]
Yes, almost certainly that.  Must have missed that when fixing conflicts
