### ISSUE TITLE
catsplosion is back?

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#30018]
roundid 74903
map metastation
![2017-08-19_00-43-48](https://user-images.githubusercontent.com/28678854/29481292-8bd28910-8477-11e7-847d-9ccb9499d2e7.png)

**Comment by PraiseRatvar** [comment]
dupe of https://github.com/tgstation/tgstation/issues/27550

**Comment by Cyberboss** [comment]
Duplicate of #27550
