### ISSUE TITLE
hair goes through hardsuits

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#30017]
![](https://file.house/f_1D.png)

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/af4d9a85c9a3eeef1e5e0637ef4ebd0312794ac7/code/modules/clothing/spacesuits/hardsuit.dm#L233

Easy fix, just add |HIDEHAIR to the end

**Comment by ShizCalev** [comment]
Adding the HIDEHAIR flag doesn't fix this (it already inherits that flag from it's parent, so I'm not sure why it's duplicated.) The lower half of longer hair isn't hidden by HIDEHAIR.

**Comment by Cyberboss** [comment]
@ShizCalev it definitely doesn't have HIDEHAIR on master. Did you test that?

**Comment by ExcessiveUseOfCobblestone** [comment]
any inheritance would be overridden with the line I posted anyways though?

**Comment by ShizCalev** [comment]
@Cyberboss Testing it as we speak. It inherits the proper flags from it's parent. You can see the same issue present with it's parent which definitely does have the flags /obj/item/clothing/head/helmet/space 
https://github.com/tgstation/tgstation/blob/2e58d7bc86af6e4c5edd9b60c65501b4fbd68981/code/modules/clothing/clothing.dm#L477
