### ISSUE TITLE
Supermatter sliver objective can be had on maps without a supermatter

### ISSUE THREAD

**Issue by pubby** [tgstation/tgstation#30016]
Heard this through the grapevine so I can't 100% confirm.

I guess you can technically order one from cargo, but it seems like a bug still.

**Comment by ChangelingRain** [comment]
Solution: add a supermatter.

**Comment by PraiseRatvar** [comment]
@ChangelingRain i like my maps unique!

**Comment by Repukan** [comment]
Buy one from cargo

**Comment by banthebantz** [comment]
dumb objective anyway

**Comment by MoreRobustThanYou** [comment]
Hippie has this problem, and even there, everybody hates the SM
