### ISSUE TITLE
Atmos Technicians on Delta don't have an airlock to spess.

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#30015]
They have a hardsuit yet there's no airlock in atmosia to leave into spess. They also have only one hardsuit, add more.

**Comment by ShizCalev** [comment]
![deltastationmap](https://user-images.githubusercontent.com/6209658/29488998-4431b49c-84e4-11e7-9310-771ef06ef072.png)

**Comment by Repukan** [comment]
Not an issue then?
