### ISSUE TITLE
Photos are now black/empty

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#30026]
1. Take photo
2. It's blank
3. Cry

Multiple shots taken present same error.

![dreamseeker_2017-08-19_21-22-35](https://user-images.githubusercontent.com/17237624/29489581-a02f6d9e-8524-11e7-86b2-acb2e2646fa4.png)

Server revision compiled on: 2017-08-17
The following pull requests are currently test merged:
Based off origin/master commit: 093cb1

**Comment by jughu** [comment]
That means you are a vampire!

**Comment by TheVekter** [comment]
This is an ANCIENT bug, I have no idea how we've fixed it in the past, but I'll take a look after this round.
