### ISSUE TITLE
Freezer/Heater board turns into a nameless board that doesn't work when screwdrivered

### ISSUE THREAD

**Issue by callanrocks** [tgstation/tgstation#30034]
Server revision compiled on: 2017-08-17
Based off origin/master commit: 093cb1

Not much more to add, you can put it in the machine but the final screwdrivering won't build the freezer/heater.

**Comment by ShizCalev** [comment]
Guessing #29747 for this one, @lzimann

**Comment by lzimann** [comment]
Yea probably my fault.
