### ISSUE TITLE
can't deepfry tablet computers

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#30054]
vote goofball 2017

i'm sorry

**Comment by ShizCalev** [comment]
![3n5mtpn](https://user-images.githubusercontent.com/6209658/29505265-42784b04-8613-11e7-8fdd-d33f7ca8d8e5.png)
Works fine for me.

**Comment by GunHog** [comment]
I have tested this with no issues as well. Maybe your deep-frier was unpowered or empty of oil?
