### ISSUE TITLE
Many instruments have no inhands

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#30060]
[Note]: # (<B>Please enter the `Round ID` from the `Status` panel if you can!</B> If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by factoryman942** [comment]
nor does saxophone

**Comment by ShizCalev** [comment]
@kevinz000 apparently missed importing inhand sprites with #29277.

**Comment by ShizCalev** [comment]
Also missing: glockenspiel, accordion, recorder, harmonica.

**Comment by PraiseRatvar** [comment]
FINALLY SOMEONE USES THE FUCKIN' MILESTONE @Cyberboss

**Comment by factoryman942** [comment]
there's a milestone just for kevinz?
wew

**Comment by PraiseRatvar** [comment]
@factoryman942 one for goofball too except goof's milestone actually was used

**Comment by kevinz000** [comment]
fuck
