### ISSUE TITLE
Stone tile boss flooring cannot be eaten by the singularity, but can be pulled by it.

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#30062]
Title. I'm not sure which way the intended behavior is supposed to go (IE can be eaten & pulled, or should not be pulled nor eaten,) however it seems strange to have one happen but not the other.

**Comment by Supermichael777** [comment]
probably have a returned singularity act but not the flag to tell stage five to beat it

**Comment by ShizCalev** [comment]
stone_tile doesn't have a singularity_act defined for it.

**Comment by Supermichael777** [comment]
HOLD YOUR BUTTOCKS
