### ISSUE TITLE
Morph Form Stacking

### ISSUE THREAD

**Issue by Nabski89** [tgstation/tgstation#30066]
[Note]: #Round 75006

Antag trade to become a morph (Armuleen). I eat my starting room, then transform into my old corpses head. I speak a few lines, then go knock down a door. I transform into that door, then go to transform back into the head. I stay the door. I try to transform into a locker and it adds the locker onto my sprite.

See attached pictures. I am the window locker handcuff combo. None of those are in the stack with me, but all were things I had become.

![image](https://user-images.githubusercontent.com/22940977/29504331-82f5edb2-8604-11e7-8926-5d4b127bac05.png)

I don't think items eaten matter, but there's 
![image](https://user-images.githubusercontent.com/22940977/29504392-110fe314-8605-11e7-9b40-e0f6919c2325.png)

**Comment by Nabski89** [comment]
I don't think my bug report was clear enough. It only stacked some items. Lockers, Doors, Windows, Computers, Paper Bins, Tables, Newscasters, Fire Alarms, AI Displays, were all guilty.

Items like Bedsheets, Glass, Pens, Chairs, Logos, Posters, Breifcase, Notice Board, Flashes, Handcuffs, Recharger, Filing Cabinet, Windoor were not stacking and would clearly change it.

You could change from the stack, to a normal item, back into the stacked items and it would store everything in it's memory still.

**Comment by ShizCalev** [comment]
Unable to replicate the issue during testing. Appearances are being cleared properly between transformations as intended with the mentioned objects/structures. 

The *flip thing was most likely admin fuckery. Not sure they also touched something that broke the transformation states clearing as well.

**Comment by Armhulen** [comment]
I didn't *flip nothing, or touch any admin fuckery things. I just made a morph and popped him in.

**Comment by ShizCalev** [comment]
Oh wait, strike my previous, just managed to get it to happen on master - it isn't consistent however.

**Comment by Nabski89** [comment]
Yeah, I couldn't replicate the flip one, but it did happen and was hilarious.

Best I can tell if it's a wall style object more likely to fail than otherwise.
