### ISSUE TITLE
foam armblade doesn't have a inhand

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#30076]

**Comment by TheVekter** [comment]
Screenshot?

**Comment by PraiseRatvar** [comment]
picture a spessman holding nothing

**Comment by TheVekter** [comment]
Is this happening from all angles? What were you wearing? Have you tested it without any clothing on to see if something is interfering with it?

We need more info than just "it doesn't have an inhand".

**Comment by PraiseRatvar** [comment]
![2017-08-21_20-44-20](https://user-images.githubusercontent.com/28678854/29535386-90c456e2-86b1-11e7-99e7-99609b58f04d.png)
he was buttnaked

**Comment by Firecage** [comment]
Vekter, I am simply guessing its the same issue that the chaplains Dark Blessing had. The wrong .dmi file.

**Comment by TheVekter** [comment]
Probably. I just wanted to make sure there wasn't anything interfering with
the .dmi showing up.

I'll take a look at it after work.

**Comment by TheVekter** [comment]
Fixed by #30079
