### ISSUE TITLE
Wearing certain hats can cause you to go partially bald when they are removed.

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#30074]
I assume this happens with all hats which partially covers your head, though hats which I have had personal experience with causing this sometimes is the Captains hat, the Birthday Cake Hat, the CE hard helmet(and probably all hard helmets).

Basically what happens is that when said hat is removed, it sometimes causes the spot where the hat was to appear bald. Thus you can literally be partially bald, since the area where the hat didn't cover isn't bald.

**Comment by PraiseRatvar** [comment]
https://www.youtube.com/watch?v=F9PuLqYQGTs

you glued on your hat!!

**Comment by ShizCalev** [comment]
![3nka2nm](https://user-images.githubusercontent.com/6209658/29858325-03394618-8d2b-11e7-99f2-c151858b4b30.png)

![3nka0ob](https://user-images.githubusercontent.com/6209658/29858329-05af4910-8d2b-11e7-9990-60e40be1fa6f.png)

Example.

**Comment by Cyberboss** [comment]
@RemieRichards ?

**Comment by RemieRichards** [comment]
There's no bug here.
Somebody (I forget who) made a bunch of hair extensions sprites for the detective hat, and then someone else made all of those the generic ones that are used for all items.

the "fix" is to either create better fitting hair extensions for the hats that are problematic, or to remove the hair extensions on those hats (```dynamic_hair_suffix = ""```)

**Comment by KorPhaeron** [comment]
There is a bug here though that if you remove a deathsquad helmet or something it leaves you bald even when the helmet is gone

That image ShizCalev posted is actually an example of a different bug

**Comment by ShizCalev** [comment]
Oh my b.

**Comment by timothymtorres** [comment]
I'm pretty sure the previous merged PR that was mentioned fixed this but someone forgot to close this issue.
