### ISSUE TITLE
Ashwalker necropolis destroys objects gibbing when they shouldn't

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#30071]
The ashwalker necropolis no longer drops _***all**_ the contents of its victims, objects namely referring to belt slot objects & bags and chest gibs are destroyed wheras they weren't before. Anything worn on the torso is generally destroyed.

This is a deviant behaviour because ashwalker tendrils are supposed to not destroy the contents of its sacrifices after it was summarily changed to preserve its contents. Suggesting that the code for gibbing is obsolete or needs tweaking.

**Comment by Grazyn** [comment]
Just strip the corpse before gibbing it you lazy lizard

**Comment by FantasticFwoosh** [comment]
We had a explicit change to how the tendril worked because it used to gib bodies in full, this issue report is to apply bug feedback that the condition has changed unintentionally.
