### ISSUE TITLE
you can burn lava tiles into chasm tiles with a plasma fire, tossing a stack of plasma into lava superheats the area and does exactly that.

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#30082]
title

**Comment by Kromgar** [comment]
Considering plasma can get hotter than the sun I am not surprised it can evaporate lava

**Comment by Repukan** [comment]
Isn't lava molten rock though

**Comment by ShizCalev** [comment]
@Repukan Given a high enough temperature and pressure, molten rock does in fact vaporize.

**Comment by LaharlMontogmmery** [comment]
...Emergent gameplay?

Seriously, that does sound awesome. Keep that in.

**Comment by AnturK** [comment]
How is this an issue. Don't throw volatile fuel into lava.
