### ISSUE TITLE
Missing / Nonexistant inhands defined in code

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#30081]
**Missing / nonexistant inhands;**

- [ ] walkietalkie - /obj/item/radio
- [ ] bandaid - /obj/item/reagent_containers/pill/patch
- [ ] atoxinbottle - /obj/item/reagent_containers/glass/bottle (probably not actually needed)
- [ ] flight -	/obj/item/hand_labeler & /obj/item/device/pipe_painter
- [ ] ed209_frame - guess
- [ ] ed209_leg
- [ ] ed209_legs
- [ ] ed209_shell
- [ ] ed209_proxy
- [ ] ed209_taser
- [ ] corncob - /obj/item/grown/corncob & /obj/item/grown/snapcorn
- [ ] flour - /obj/item/reagent_containers/food/condiment/flour & /obj/item/reagent_containers/food/condiment/rice
- [ ] waterbackpack - /obj/item/watertank
- [ ] waterbackpackjani - /obj/item/watertank/janitor & /obj/item/watertank/operator
- [ ] waterbackpackatmos - /obj/item/watertank/atmos & /obj/item/reagent_containers/chemtank
- [ ] candlebox5 - /obj/item/storage/fancy/candle_box
- [ ] flash - /obj/item/device/pressure_plate
- [ ] bananalamp - /obj/item/device/flashlight/lamp/bananalamp
- [ ] candle1 - /obj/item/candle
- [ ] bombsuit - /obj/item/clothing/head/bomb_hood
- [ ] bombsuit - /obj/item/clothing/head/bomb_suit
- [ ] bombsuit_sec - /obj/item/clothing/head/bomb_hood/security
- [ ] bombsuit_sec - /obj/item/clothing/head/bomb_suit/security
- [ ] bombsuit_white - /obj/item/clothing/head/bomb_hood/white
- [ ] bombsuit_white - /obj/item/clothing/head/bomb_suit/white
- [ ] sheet-polycrystal - /obj/item/stack/sheet/bluespace_crystal
-
- [ ] everything in https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/stacks/sheets/leather.dm
- [ ] everything in https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/stacks/sheets/mineral.dm
- [ ] everything in https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/stacks/sheets/sheet_types.dm that isn't sheet-metal or sheet-plastic
- [ ] everything in https://github.com/tgstation/tgstation/blob/master/code/modules/mining/ores_coins.dm

**needs unique sprite;**

- [ ] render - /obj/item/kitchen/knife/ritual, /obj/item/kitchen/knife/envy, /obj/item/veilrender, /obj/item/melee/cultblade/dagger

**Comment by Cyberboss** [comment]
These really should be separate issues or cards in the project

**Comment by epochayur** [comment]
are these all still needed?

**Comment by ShizCalev** [comment]
@epochayur Yes.

**Comment by ShizCalev** [comment]
Added everything from https://github.com/tgstation/tgstation/pull/35772/files that isn't sprited to the list.

**Comment by KomradeSpectre** [comment]
My boy, I'll see what I can do about this for you. Just keep the checklist updated if and when I do.

**Comment by TheTeenyTiny** [comment]
So, for stuff like " corncob - /obj/item/grown/corncob & /obj/item/grown/snapcorn" 
Did you want a corncob or the snapcorn? Same with the "flash - /obj/item/device/pressure_plate". 

Sorry, I'm still new to this so I find it a bit confusing.

**Comment by ShizCalev** [comment]
@TheTeenyTiny They'll need unique sprites in most cases since they're using placeholders (most of which don't even exist)

**Comment by ShizCalev** [comment]
#49714

**Comment by Bokkiewokkie** [comment]
Can you tick the boxes for the things that are already completed so it's a little more clear what's still needed?

**Comment by timothymtorres** [comment]
I'm marking this with the `Cleanup` label (auto close it in 7 days) because this is like a feature request but with sprites.  I don't think the bug tracker is the appropriate location to put a to-do list.
