### ISSUE TITLE
Hulk being able to break reinforced wall, standard holoparasite unable to

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#30085]
Seems like a bit of a hiccup in the code, I mean holoparasites are pretty difficult to be able to get and pretty much exclusive to antags and lucky miners.

**Comment by XDTM** [comment]
They have other qualities. For example they can drag you away if you get stunned.

**Comment by ShizCalev** [comment]
Weren't they removed from antags?

**Comment by PraiseRatvar** [comment]
you can still get 'em somehow, either way hulk sucks and should be nerfed

**Comment by jughu** [comment]
Standard holoparasite was not intended to break reinforced walls only standard so they could eacape quicker (this was before the damage refactlr where you couldnt break doors and stuff also miners and wizards can get them

And why should hulk be nerfed they are pure muscle

**Comment by KorPhaeron** [comment]
Not a bug
