### ISSUE TITLE
Drag and Dump is nonfunctional

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#30099]
#29839: '[s] Adds a security token to all admin hrefs' by Cyberboss at commit d4c8da but I don't think this is the problem

You used to be able to drag the sprite of a bag/box onto a turf and it would dump contents out onto the turf. Now it simply doesn't do that.

No progress bar or anything.

**Comment by Cyberboss** [comment]
Duplicate of #30007
