### ISSUE TITLE
`ore_mined` stats are busted

### ISSUE THREAD

**Issue by nfreader** [tgstation/tgstation#30094]
And have been since round #69027, roughly April 14th of this year. Looks like #26129 might be the culprit, but I'm not an expert.

**Comment by PraiseRatvar** [comment]
@Cyberboss

**Comment by Cyberboss** [comment]
https://github.com/tgstation/tgstation/blob/master/code/game/turfs/simulated/minerals.dm#L82 Idk why

**Comment by ExcessiveUseOfCobblestone** [comment]
why is it mineraltype and not "[mineraltype]"
