### ISSUE TITLE
you can gorillify people easily

### ISSUE THREAD

**Issue by MoreRobustThanYou** [tgstation/tgstation#30091]
this was on hippie, they listed their gorillification steps:

1. get monkey SE into buffer
2. put person into scanner
3. spam the occupant button until they turn into gorilla
4. profit

**Comment by Iatots** [comment]
The issue tracker is mostly for bugs.
If you feel like something should be rebalanced, make a post to your station's official forums.

**Comment by MoreRobustThanYou** [comment]
latots, this isn't related to hippiecode, this feature was mirrored directly form /tg/

**Comment by DoctoreMad** [comment]
Yeah and on /tg/ we also have a feature request part of the forum, which is kind of what this is depending on how you plan on fixing it.
Y'know what it is MRTY, you gotta _go through the motions_
