### ISSUE TITLE
Mining Aux Base won't launch.

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#30090]
Possibly related to #29881 and #29941 
@lzimann 
![2017-08-22_13-35-08](https://user-images.githubusercontent.com/28678854/29565659-be91ee44-873e-11e7-80c4-0a2cff3cd780.png)
in the 4 corners there were turrets.

yes, there was an annoucement for the landing field designator.

**Comment by PraiseRatvar** [comment]
roundid 75062

**Comment by GunHog** [comment]
Seemed to be working fine on Basil, I did not test on Sybil though.

**Comment by PraiseRatvar** [comment]
i was on sybil and was an assistant.

**Comment by GunHog** [comment]
Please let me know if this happens again to you, and when it does, include the steps you took to cause it. (Not this time, a second time)

**Comment by BeeSting12** [comment]
@PraiseRatvar 
If you were an assistant you might not have had access. I believe there's an access requirement for this.

**Comment by GunHog** [comment]
I forgot about that! The Aux Base indeed has access restrictions. I thought it was related to a shuttle runtime previously reported elsewhere, as PraiseRatvar never mentioned an "Access denied" message. Go ahead and close this if you indeed got an "Access denied" message. If you had stolen access or did not get a message, please let me know.

**Comment by Cyberboss** [comment]
@PraiseRatvar ?

**Comment by PraiseRatvar** [comment]
I got no message saying Access Denied, I got the message preparing to launch shuttle or whatever. When I tried clicking it again, it said somewhere along the lines of shuttle is in transit?

**Comment by GunHog** [comment]
Was your ingame name "Decimus"? The only runtime I could find in the logs relating to a shuttle refers to a shuttle with a null ID.

**Comment by PraiseRatvar** [comment]
@GunHog 
my ingame name is 'FrozenGuy5'

i didn't place the land. field designator btw, i only saw the message and decided to build the aux base.

**Comment by PraiseRatvar** [comment]
right turns out im dumb
