### ISSUE TITLE
A bunch of admin buttons are busted.

### ISSUE THREAD

**Issue by MrAlphonzo** [tgstation/tgstation#30101]
On the player panel, Jump To/Get/Send To/Traitor Panel/Narrate To/Subtle Message/Language menu refuse to open, and on Show Ticket List in the admin tab, while the ticket list does pop up, the tickets can't actually be opened, and have to be opened in the tickets tab.

Clearly all these buttons were broken to sabotage my candidacy and we are adminspiracy now.

WEW I probably should've mentioned that this is a recurring issue although I can't remember what other rounds it occurred.

**Comment by Cyberboss** [comment]
Round ID?

**Comment by MrAlphonzo** [comment]
Uhhhh 75075 I think.

**Comment by ExcessiveUseOfCobblestone** [comment]
It's the href auth thing blocking it.

**Comment by lzimann** [comment]
Related to the testmerged thing.
