### ISSUE TITLE
Gorillas can use guns and don't have identifier numbers

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#30104]
WHAT THE FUCK. LETS JUST MAKE SUPER HULKS THAT DONT BLEED AND CANT LOSE LIMBS BUT CAN ALSO USE GUNS AND STUN BATONS

**Comment by factoryman942** [comment]
they also apparently can't be converted to cults
and they don't have numbers, so you can't actually discern them from one another

**Comment by Kromgar** [comment]
Also why the fuck can they speak human

**Comment by factoryman942** [comment]
in other words gorillas are objectively better than humans, monkeys, lizzers or plasmamen

**Comment by Kromgar** [comment]
@factoryman942 but they are slower... but they can make up for that with tasers

**Comment by factoryman942** [comment]
sec's final form

**Comment by ExcessiveUseOfCobblestone** [comment]
Solution: Kill all gorillas

**Comment by Armhulen** [comment]
Suggestion: GET FUCKING GOOD

**Comment by DoctoreMad** [comment]
"Dude I'm not overpowered get good" -t. Not A Gorilla

**Comment by Armhulen** [comment]
they shouldn't be as common, not weaksauce
