### ISSUE TITLE
Jquery versions

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation#30122]
we have about three different jqueries

jquery.min.js v1.11.1 html interface code/modules/html_interface/js/jquery.min.js

"jquery-1.10.2.min.js" = 'html/IRV/jquery-1.10.2.min.js' (irv, possibly required by that widget for sorting)
https://code.jquery.com/jquery-1.11.3.min.js for tooltips (loaded from cdn)

@RemieRichards @MrStonedOne can you please comment on the reasons for your versions of jquery? 
Ideally we can bump to 1.11.3 at least and combine them all

**Comment by RemieRichards** [comment]
mine came with the goon tooltip port.
don't believe it relies on specific version support, @wirewraith?

**Comment by Cyberboss** [comment]
Pretty sure all jquery is backward compat

**Comment by Wirewraith** [comment]
Combining to 1.11.3 should be fine.

As a very general rule, jQuery is backward compatible within major release numbers. E.g. going from 1.x to another 1.x is fine, but 1.x to 2.x would probably cause problems.

**Comment by MrStonedOne** [comment]
I can't remember why i picked that version, but there was a reason that latest wouldn't work

**Comment by MrStonedOne** [comment]
also, goonchat and a few others use the html_interface version.

I think we should move that file to html/ and make everything that doesn't need a special version use it under the generic name
