### ISSUE TITLE
Player controlled gorillas cannot smash walls/rwalls

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#30133]
Even though NPC ones can.

**Comment by optimumtact** [comment]
Not a bug probably

**Comment by pubby** [comment]
It's a problem with all player-controlled simple animals. Even animals that can't break things have strange interactions with walls.

**Comment by optimumtact** [comment]
I'm gonna rule it a bug on teh basis that if players could do this it would be extremely annoying

**Comment by optimumtact** [comment]
I meant not a biug
