### ISSUE TITLE
Densified Chemicals doesnt do anything

### ISSUE THREAD

**Issue by xTrainx** [tgstation/tgstation#30135]
Densified Chemicals doesnt seem to do anything, it doesn't add to the chemical capacity of the plants, so you still can't have more than 100 reagents from a plant, and doesnt seem to raise the reagent production either. This make it so you can't do some stuff, like making healing gaia with mannitol, or potency 100 nitro tomatos.

**Comment by XDTM** [comment]
Plants normally hold 50, if you can fit 100 in it's working

**Comment by octareenroon91** [comment]
Strip out unneeded chems.
Use a lower potency so mannitol fits. Also a few foods have larger capacity don't they?

**Comment by xTrainx** [comment]
oh, i wasnt aware of th 50 chems cap, also, when i try to add hydrogen, it's displayed as 0 in the plant analyzer, is that normal?

**Comment by vuonojenmustaturska** [comment]
@KorPhaeron this seems not a bug
