### ISSUE TITLE
Monkeying the last revhead counts as a station victory

### ISSUE THREAD

**Issue by Sartorius7** [tgstation/tgstation#30142]
#75141
The heads of staff managed to stop the revolution!

    Command's Approval Rating: 73.9%

The head revolutionaries were:
Ninja137 was Ismael Catleay the Cargo Technician and survived as monkey (739)

**Comment by YakumoChen** [comment]
good, that makes total sense.

**Comment by Repukan** [comment]
Feature

**Comment by ShizCalev** [comment]
Intentional.
