### ISSUE TITLE
Pizza boxes are weird and don't stack right

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#30145]
it makes the pizza box invisible but doesn't stack it?

**Comment by PraiseRatvar** [comment]
@Xhuis

**Comment by Xhuis** [comment]
This doesn't really describe the issue in any detail.

**Comment by TheVekter** [comment]
@Armhulen can we get a screenshot or something?

**Comment by Armhulen** [comment]
hmmmmmmm i'll see what i can do

**Comment by Armhulen** [comment]
but it's hard to take a screenshot of an invisible item

**Comment by PraiseRatvar** [comment]
@Armhulen that doesn't matter? you're not explaining the issue properly

**Comment by Armhulen** [comment]
OK here, when you stack a pizza it doesn't stack it and makes the pizza in your hand go invisible, that's what happens

**Comment by Armhulen** [comment]
http://i.imgur.com/SlYFp0z.png done, distinct lack of pizza in my hands

**Comment by Xhuis** [comment]
>Using Syndicate UI style ever
wow and I thought you were cool

(Let me test this)

**Comment by Xhuis** [comment]
I can reproduce the issue, but I don't know why it's happening or who broke it. vOv

**Comment by Armhulen** [comment]
I switch between plasmafire, operative and clock cult when i get bored on the one i'm currently on
