### ISSUE TITLE
Messages table doesn't have a round ID/server info

### ISSUE THREAD

**Issue by nfreader** [tgstation/tgstation#30163]
Bans have em, but not notes. I am super sad as a result. Plus this is also making it difficult to cross reference things that need to be cross referenced.

EDIT: Messages DO have a server field, but it's a varchar and not a standard IP/port like it is everywhere else. Consistency issue!

**Comment by optimumtact** [comment]
what other tables could use the round id?

**Comment by nfreader** [comment]
Uhhhhh let's see...
`connection_log` (would be great)
`library` (when the book is added)
`player` (maybe `firstseen_round` and `lastseen_round`?)

**Comment by Jordie0608** [comment]
Do you graph `legacy_population` anywhere?

**Comment by nfreader** [comment]
Oh, I thought that was broken. Yeah, gimme round IDs on that if you can please <3

**Comment by Jordie0608** [comment]
For reference, `messages` stores `server` as varchar as it's player-facing, IP/Port columns could be added but I'm not sure how they'd be used.
