### ISSUE TITLE
People dont turn in their chairs when shuttle starts moving

### ISSUE THREAD

**Issue by naltronix** [tgstation/tgstation#30177]
You know how the shuttle turns 90 degrees in transit? People stay in the same rotation as they were when in the shuttle. So if you were facing forward, it would look really fucking weird if the chair you were on were facing right.

**Comment by Cyberboss** [comment]
@ninjanomnom

**Comment by Cyberboss** [comment]
@ninjanomnom did you shuttle pr fix this?

**Comment by Cyberboss** [comment]
Closed by the dock rewrite
