### ISSUE TITLE
Virology unabel to make vaccine bottles but instead makes (spammable) empty bottles when tried.

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#30174]
14:23:11: Reply PM from-Hamfam77/(Dr.Riggle): I'm about to log off here in a bit, can I just give you the info? <3 
14:23:36: Reply PM from-Hamfam77/(Dr.Riggle): Alopecia(N), Sneezing, Viral Metabolism, Shivering(N), Cough(N), Voice Change (( Cure - Saline-Glucose Solution, Airborne)) 
14:23:59: Reply PM from-Hamfam77/(Dr.Riggle): Infect monkey --> cure monkey --> draw blood --> insert into machine --> manufacture vaccine --> empty bottles, no vaccine

**Comment by XDTM** [comment]
Fucks sake

**Comment by Hamfam77** [comment]
Keep in mind that this bug makes syndicate virologists unnecessarily powerful because the ability to effectively mass-cure a fast-spreading and lethal disease is currently almost nonexistent.
