### ISSUE TITLE
Nukeops spawn with no uplink, turrets are hostile

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#30194]
>Spawn as nukeop leader
>Our own turrets start ceaselessly firing on us from off-screen
>We dont have an uplink so 0 TC's
>All my teammates are killed by the ship's turrets as they move around inside

Nice

**Comment by lzimann** [comment]
caused by #29785 and what caused the problem is a dupe of #30170

**Comment by Cyberboss** [comment]
Duplicate of #30170
