### ISSUE TITLE
Antimatter Engine needs new sprites/sounds/ui and some improvements/fixes

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#30213]
Antimatter Engine needs:

- [ ] new sprites, the current ones look straight outta' v1.0.0
- [ ] new sounds, the current sounds just clang
- [ ] improvement on the ui, current one is literally just text
- [x] power does not display properly, it's literally just displaying a random number - #30240
- [ ] improvements on actually building the engine, it's just multitooling a couple of boxes when it could probably be done better somehow
- [x] a wiki page - https://tgstation13.org/wiki/Antimatter_Engine
- [ ] inhands for antimatter containment jars (and probably for the packaged parts)

![2017-08-26_16-27-11](https://user-images.githubusercontent.com/28678854/29742827-15b05f2a-8a7e-11e7-8c2d-24fa6c0c8c7d.png)
<img src="http://i.imgur.com/tAk769q.png"/>

let's make the antimatter grate!!1

**Comment by ShizCalev** [comment]
1.8e+006 = 1,800,000 (1.8, then move the decimal 6 spaces to the right after the whole number.)

http://www.dummies.com/education/math/algebra/how-to-write-numbers-in-scientific-notation/

**Comment by PraiseRatvar** [comment]
@ShizCalev random number as in it's not even giving some type of measurement like megawatts, or volts to go with the number

**Comment by naltronix** [comment]
it would really be nice if the wiki included anything about the antimatter engine, as nobody uses it because nobody knows how to fucking use it

**Comment by naltronix** [comment]
the antimatter is the one engine along with the turbine that has seen no love at all
i dont mind spriting it, do you want me to send you a copy of it when its finished?

**Comment by jughu** [comment]
Dont change it man engineers cant even handle a supermatter its too complicated for em!

**Comment by jughu** [comment]
Also your injecting too much in the screenshot this is the reasom why engineers dont get fun things.

**Comment by PraiseRatvar** [comment]
@jughu this was on roundend that we decided to fuck with the engine

@naltronix probably make a pr yourself if you're able to, i would much rather that you get feedback by people who actually are good at spriting, unlike myself

**Comment by PraiseRatvar** [comment]
i've learned that you need to press a button for the light in the middle to actually appear, called "Force Shielding Update" it should able to turn the flippin' light itself

also antimatter containment jars don't have inhands

**Comment by naltronix** [comment]
i made a wiki page for it

**Comment by banthebantz** [comment]
It should also have a more interesting failure state imo as currently it just maxcaps the controller which is pretty uninspired.

**Comment by naltronix** [comment]
the sprite for the engine is fine, but the controller looks ancient. plsfix
