### ISSUE TITLE
Leftover shuttle pieces when ordering different model.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#30212]
![](http://i.imgur.com/Ha5cJnJ.png)

Server revision compiled on: 2017-08-25
fb134b
Round ID 75258

Happened on metastation, a different shuttle was ordered than the metastation one. For some reason, there were leftover floor tiles. The shuttle also was not aligned with centcomm:

![](http://i.imgur.com/Y03fB7a.png)

**Comment by ninjanomnom** [comment]
This got fixed by #30261
