### ISSUE TITLE
Revolution round ends within 5 minutes if all revas are miners and decide to go strike some earth

### ISSUE THREAD

**Issue by 24twelve** [tgstation/tgstation#30219]
We've encountered this sad bug today.
Steps to reproduce:
1. Be the one and the only head rev in revolution round.
2. Don't know that fleeing the station counts as losing
3. Leave the station to get some ore
4.

The heads of staff managed to stop the revolution!
  Command's Approval Rating: 93.9%

The head revolutionaries were:
Alex971 was Quinn Seelig the Shaft Miner and survived while fleeing the station

The revolutionaries were:
Xrenoid was Lenny Kelly the Shaft Miner and survived while fleeing the station

The heads of staff were:
FinalTRy was Claus Fon Zimmermann the Head of Security and survived
Jones Stap was James Power the Head of Personnel and survived
Giaguarozebra was Walker Mueller the Chief Medical Officer and survived

**Comment by Repukan** [comment]
Not a bug.

Read the chat.
