### ISSUE TITLE
Space-Time anomalies aka wormholes don't teleport you? (Random Event)

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#30236]
roundid 75308

this was before the announcement was actually made

**Comment by jughu** [comment]
I dont know why but i blame @kevinz000

**Comment by Slignerd** [comment]
They still teleport you, but you need to click them instead of walk into them.

**Comment by PraiseRatvar** [comment]
@Slignerd that sucks, the event is so rare that you might as well make it so when you walk into them you get teleported.

**Comment by XDTM** [comment]
I blame @kevinz000 and i know why
