### ISSUE TITLE
Atmos tech tablet PCs can't access SM monitoring despite SM being in atmos on Delta

### ISSUE THREAD

**Issue by JamesDenholm** [tgstation/tgstation#30232]
As title states.

**Comment by jughu** [comment]
No thats just map design
Theres a way around it letting the ce/engineers letting download rhe program but honestly for an atmos based engine  it would make the most sense they would have it

**Comment by JamesDenholm** [comment]
Well obviously this bug/design issue relates to Delta, the point is that, on Delta, the branch of engineering that maintains the SM can't monitor the SM using their tablets.

SM being atmos on Delta makes a lot of sense, mainly because it frees up the engineers to go do repairs on the much larger station (while presumably atmos techs wouldn't go as far from engineering).
