### ISSUE TITLE
Chasm paths are all kinds of messed up

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#30267]
Originally chasms deleted things, and chasm/straight_down dropped things a z level

Now for some reason all the animation code is defined under

 /turf/open/chasm/straight_down/lava_land_surface

A lavaland only variant, with the wrong path at that because lavaland chasms delete rather than drop

Which leads to an even sillier path

 /turf/open/chasm/straight_down/lava_land_surface/normal_air

@Xhuis I guess since you added this code (I think?), I'm very confused why you put it in the place you did

**Comment by optimumtact** [comment]
turf/open/chasm should have most of the behaviour, including anims
