### ISSUE TITLE
Changeling DNA absorption bug

### ISSUE THREAD

**Issue by Kuromoi** [tgstation/tgstation#3026]
Sometimes (and I'm really not sure why), changelings cannot absorb more than five DNA strands even when they transform after absorbing the first set.  This makes greentext literally impossible.

This isn't a new issue either; it's been in place since the new changeling code was added.  I do not know how to reproduce this.

**Comment by Iamgoofball** [comment]
is this still even relevant

**Comment by optimumtact** [comment]
old higgs bugson
