### ISSUE TITLE
Being healed back from the new soft crit makes it unable for you to get up again.

### ISSUE THREAD

**Issue by ThePainkiller** [tgstation/tgstation#30264]
Round ID: 75380

I was the Warden (Ollanius Pius) trying to hunt down a traitor with a .357 revolver. Multiple shots got me into crit and I was dying normally. A few people patched me up enough for me to be able to hear (the new _"soft crit"_ mechanic), but I also found myself able to **TALK** in soft crit.

When I was healed back to 100% health, I was still blinded and lying on the floor, unable to get up or get helped to get back up again. I had no other reagents on my body. The only solution was to monkeyfy me and make me back human (thanks to admin intervention, thanks **Duncdar**!).

**Please solve this ASAP as it's extremely game breaking.**

**Comment by ChangelingRain** [comment]
Please post bugs for testmerges on the relevant pr. #30262
