### ISSUE TITLE
toolbelt has no sprite for CE's upgraded tools

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#30280]
jaws of life / power drill / experimental welder

**Comment by ChangelingRain** [comment]
my prediction has come to pass, what a surprise

**Comment by factoryman942** [comment]
h-honk?

**Comment by KorPhaeron** [comment]
@Xhuis you were doing these right

**Comment by Xhuis** [comment]
yeah, there wasn't enough real estate on the belt icon to fit 'em all; I'd chalk this up as a "not worth fixing" unless someone has the time and spriting finesse to make an icon for it that won't overlap other ones or that would just cover them up

**Comment by Xhuis** [comment]
actually since I made them the least I can do is whip up some sprites, hold on
