### ISSUE TITLE
Dragging something while on a drug that increases run speed, causes you to go to default dragging speed, while you are dragging it

### ISSUE THREAD

**Issue by Bod9001** [tgstation/tgstation#30282]
Sadly I forgot to get the round ID 

I think you should be able to drag stuff in an increased rate if the drugs allow you to run at an increased rate?

I found this out while in an nuclear operatives round, where I used Ephedrine (15u patch) to + baton to run up to one of the nuclear operatives, and batonning him, but when I tried dragging his gun away, I ran at the normal dragging speed.

**Comment by PraiseRatvar** [comment]
im p sure this is intentional

**Comment by Cyberboss** [comment]
Not a bug
