### ISSUE TITLE
Protolathe and Imprinter don't let you choose an amount of sheets to put in

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#30296]
now it just slots in whatever is in your hand, which is annoying. It used to ask for a number.

**Comment by AnturK** [comment]
@Cyberboss

**Comment by Anonmare** [comment]
`if(istype(O, /obj/item/stack/sheet))
		. = 1
		if(!is_insertion_ready(user))
			return
		var/sheet_material = materials.get_item_material_amount(O)
		if(!sheet_material)
			return

		if(!materials.has_space(sheet_material))
			to_chat(user, "<span class='warning'>The [src.name]'s material bin is full! Please remove material before adding more.</span>")
			return 1

		var/obj/item/stack/sheet/stack = O
		var/amount = round(input("How many sheets do you want to add?") as num)//No decimals
		if(!in_range(src, stack) || !user.Adjacent(src))
			return
		var/amount_inserted = materials.insert_stack(O,amount)
		if(!amount_inserted)
			return 1
		else
			var/stack_name = stack.name
			busy = TRUE
			use_power(max(1000, (MINERAL_MATERIAL_AMOUNT*amount_inserted/10)))
			to_chat(user, "<span class='notice'>You add [amount_inserted] sheets to the [src.name].</span>")
			add_overlay("protolathe_[stack_name]")
			sleep(10)
			cut_overlay("protolathe_[stack_name]")
			busy = FALSE
		updateUsrDialog()

	else if(istype(O, /obj/item/weapon/ore/bluespace_crystal)) //Bluespace crystals can be either a stack or an item
		. = 1
		if(!is_insertion_ready(user))
			return
		var/bs_material = materials.get_item_material_amount(O)
		if(!bs_material)
			return

		if(!materials.has_space(bs_material))
			to_chat(user, "<span class='warning'>The [src.name]'s material bin is full! Please remove material before adding more.</span>")
			return 1

		materials.insert_item(O)
		busy = TRUE
		use_power(MINERAL_MATERIAL_AMOUNT/10)
		to_chat(user, "<span class='notice'>You add [O] to the [src.name].</span>")
		qdel(O)
		add_overlay("protolathe_bluespace")
		sleep(10)
		cut_overlay("protolathe_bluespace")
		busy = FALSE
		updateUsrDialog()

	else if(user.a_intent != INTENT_HARM)
		to_chat(user, "<span class='warning'>You cannot insert this item into the [name]!</span>")
		return 1
	else
		return 0`

Original code for reference

**Comment by Kevak** [comment]
Fix iiiit. This is irksome.
