### ISSUE TITLE
Cargo

### ISSUE THREAD

**Issue by riley1231** [tgstation/tgstation#30290]
Round ID: 75461

Conveyor belts in cargo bay are both outgoing from the shuttle. As the QM I do not have access to my own office.

**Comment by Ratvar** [comment]
Change your message to "Cargo" and it will be perfect

**Comment by ShizCalev** [comment]
#30201

**Comment by BeeSting12** [comment]
Assuming this is for Alinastation. Might want to add the map in OP.

**Comment by ShizCalev** [comment]
Fixed, close.
