### ISSUE TITLE
Atmos Filters placed in series are buggy.

### ISSUE THREAD

**Issue by SyruseEln** [tgstation/tgstation#30305]
Can be most easily observed on Omega station. When atmos filters are placed in a series (one immediately after the other) if they loose power and are restored they will no longer move gas and get stuck. The only way to fix them is to unwrench them and wrench them back into position. To replicate simply set up the engine on omega and toggle the environment power off then back on at the APC.

**Comment by msgerbs** [comment]
I noticed similar a while back when trying to make a horrible contraption. I had 2 filters in series, one filtering O2 and one filtering Plasma, and I could not for the life of me get the second filter to work.

**Comment by pubby** [comment]
I can't reproduce this. Are you sure you turned this filter back on?

![image](https://user-images.githubusercontent.com/1446540/30073852-fb4349d6-9234-11e7-838d-a0438b215a3a.png)

**Comment by Cyberboss** [comment]
@pubby You need multiple filters right next to each other with nothing in between

**Comment by pubby** [comment]
@Cyberboss Yeah I tested the two adjacent ones in the lower part of the image, but my suspicions are this is a human error caused by the wonky power behavior of filters.

I'm gonna fix the power behavior so I'll clarify what I meant when I make the PR in a few minutes.

**Comment by Cyberboss** [comment]
@pubby fixed?
