### ISSUE TITLE
/obj/item/storage/box/security/radio providing wrong contents

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#30312]
/obj/item/storage/box/security/radio is supposed to spawn a sec internals box with a radio inside of it.
Instead, it gives you a normal internals box with a radio, instead of one with a sechailer.

**Comment by Cyberboss** [comment]
https://github.com/tgstation/tgstation/blob/33d0a8d2d0efbc8cd42972edbed5aa2535f2f686/code/game/objects/items/storage/boxes.dm#L128

**Comment by pubby** [comment]
I can't reproduce this.

**Comment by ShizCalev** [comment]
Might be a bit more specific of an issue then. 
@pubby Getting a 100% repo rate testing roundstart officers w/ #30201
https://github.com/tgstation/tgstation/pull/30201/files#diff-eaa4e2b36e12087c2be291e7186029feR43

**Comment by pubby** [comment]
Oh, I see.

`/datum/outfit/job/officer` is not the correct outfit path.

`/datum/outfit/job/security` is the correct one

**Comment by ShizCalev** [comment]
Alina's gone.

o7
