### ISSUE TITLE
Reagent Grinder reacts oddly to multiple sheets

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#30316]
If you put in a small stack of sheets - say, a stack of five plasma - then it'll be fine. But putting in the sheets one at a time will cause a grinder to act strangely. It'll still grind properly, but it will fill up with reagents it should be using and, when ejected, will remove them only to have them not exist when they pop out. If you've ground two or three instances of individually-placed sheets of five materials, then it won't know quite how to behave and think it's full when it's essentially empty.

It's a little hard to describe. I recommend looking at it personally to get what I mean.

**Comment by msgerbs** [comment]
So to make sure I'm understanding this.

1. Put in 5 sheets individually (without grinding each one)
2. Grind them
3. Try to remove them?

**Comment by AnonymousNow** [comment]
Sort of. They're like ghost versions after being ground, inside the grinder. My best guess is that the grinder is grinding all the material, but only THINKS it's ground the first stack, for some reason.

I've said grinding too much now. It sounds weird. Grinding. Ground.

**Comment by Cyberboss** [comment]
My fault probably

**Comment by kevinz000** [comment]
nope. check history. when the code was fixed to use transferItemToLoc it started using forcemove instead of directly setting loc. doing that will call Crossed which makes stacks merge.
When they merge, the merged one disappears. However, it doesn't get deleted from holding_items.
