### ISSUE TITLE
Space Transit Tiles Not Appearing

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#30321]
I've had this issue for about two months now, but it absolutely will not shift, despite me thinking it would.

When a shuttle begins moving, the space tiles in its new area of space begin to speed up and move. But then, once they reach full speed mid-transit, they stop, turning into regular old space tiles. When the shuttle starts slowing down again, they'll show the correct tiles for that, but everything in the middle is completely stopped.

**Comment by ChangelingRain** [comment]
@MrStonedOne
