### ISSUE TITLE
You can't climb into the disposal unit while restrained.

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#30336]
title.

If this is on purpose then don't close this as there is a consistency issue too. When you attempt to climb into the unit it'll say "You start climbing into the disposal unit..." yet there's no progress bar and you pretty much do nothing.

yes this is an i ded

**Comment by PKPenguin321** [comment]
IIRC this was removed because you could hop in bins while somebody was dragging you while you were in cuffs. Are there separate checks for being in cuffs and being restrained?

**Comment by dragomagol** [comment]
Appears to have been fixed
