### ISSUE TITLE
Using "Say" while in crit makes you deathwhisper

### ISSUE THREAD

**Issue by msgerbs** [tgstation/tgstation#30330]
Round ID: 75529
Server: Sybil

I was crit by a spider, and was calling for help over the radio while in softcrit (using "say" of course). I fell into hardcrit just as I spoke (again, using "say" not whisper) and I ended up deathwhispering and suiciding even though I am 100% sure I was not using the whisper verb (It's pretty hard to accidentally type "whisper" when you meant to type "say"). Using "say" while in crit _should_ simply tell you that you can't speak, rather than making you last whisper and die. This is probably related to #28649.

**Comment by ChangelingRain** [comment]
Please report testmerge-related bugs on the relevant PR.
