### ISSUE TITLE
Atmos gasses occasionally spread unreasonably far and fast

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/tgstation#30333]
This bug is somewhat difficult to explain: Occasionally, gasses will behave very strangely and instantly fill out a room completely for no apparent reason. Sometimes, it stays like this, sometimes it fixes itself in what appears to be a single air subsystem tick. This is a lot more noticeable with gasses that have a visible overlay, like water vapor or plasma, but it may happen with other gasses aswell. Some gasses like freon or water vapor even cause effects on the tiles they appear briefly on, which means you could freon all the hallways instantly if you know how to abuse this.

Here's some steps to reproduce this in a hopefully not very abuseable way:

1. Ensure you are in a normal, pressurized area and that all areas you are going to be entering are also correctly pressurized.
2. Grab a water vapor canister, set it to a release pressure of 110 kPa, open it and keep dragging it everywhere, switch rooms often.
3. You'll notice that the gas will only spread slowly, which is the correct behaviour.
4. Occasionally, you will notice that the water vapor overlay will suddenly fill out all of the room, much faster than you would expect from that release pressure and the previously observed gas spread. The moment this happens you have successfully reproduced this bug.

**Comment by Cyberboss** [comment]
@MrStonedOne

**Comment by MrStonedOne** [comment]
"feature"

What you are noticing is a feature of linda to convert to zas style spreading if a connected group of spreading gases goes too long with it doing very small amounts of spreading.

**Comment by Cyberboss** [comment]
Ahh yeah, this really
