### ISSUE TITLE
Inconsistent Xenomorph Identities (Regarding Death)

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#30349]
![ayy](https://user-images.githubusercontent.com/6266927/29991227-743ffa26-8f7b-11e7-8059-a074232ae865.png)

This is the same mob.

**Comment by YakumoChen** [comment]
aliens get a new number when evolving.

**Comment by AnonymousNow** [comment]
Seems so. Doesn't match up with their ghost, though. Guess it's a fringe issue?

**Comment by AnturK** [comment]
Not really a bug, they do not keep the number.
