### ISSUE TITLE
Item stacking overaggressive

### ISSUE THREAD

**Issue by extramrdo** [tgstation/tgstation#30353]
[Note]: #75580

Pick up stack of 50 glass from table. Click with other hand to take 1 sheet out from it. Switch back to the 49 stack sheet's hand. Click table. Glass from other hand is taken too, stack on table is 50 glass.

Pick up stack of 50 glass from table. Click with other hand to take 1 sheet out from it. Drop that sheet of glass on floor. Repeat 4 times, leaving a stack of 5 on the floor. Switch back to the 45 stack sheet. Click table. Glass on floor is taken too, stack on table is 50 glass.

**Comment by kevinz000** [comment]
yeah the autostacking is way, way too much.

**Comment by XDTM** [comment]
Related to #29135

**Comment by msgerbs** [comment]
As long as somebody is fixing stacking, having a full backpack doesn't allow you to add to stacks in your backpack, you have to take the stack out, drop it, then pick it back up and put it back in.
