### ISSUE TITLE
Nutriment pump implants slot conflict

### ISSUE THREAD

**Issue by MrROBUST** [tgstation/tgstation#30358]
Both /obj/item/organ/stomach and /obj/item/organ/cyberimp/chest/nutriment has property [slot = "stomach"]. That makes it impossible to implant them together.

**Comment by DaxDupont** [comment]
This is intended, it replaces the stomach.

**Comment by GunHog** [comment]
Nutriment pumps are actually stomachs!

**Comment by AnonymousNow** [comment]
Seems intended.

**Comment by AnturK** [comment]
Not a bug.
