### ISSUE TITLE
AI Set Auto Announce Mode broken for alternate channels

### ISSUE THREAD

**Issue by extramrdo** [tgstation/tgstation#30352]
[Note]: #75579 

Set Auto Announce verb for AI, set to command, went to announce laws, "C Law 1: You must..." over Common. Set Auto Announce to Security, "S Law 1:..." over Common. Set Auto Announce to Common and it works.

**Comment by Anonmare** [comment]
The autoannouncement for the other channels appear to be missing either a ":" or a "." before the channel key, resulting in the laws not being stated over the selected channel - if it wasn't clear from Extramdo's description.
