### ISSUE TITLE
Virological Vaccines are empty when produced

### ISSUE THREAD

**Issue by Daturix** [tgstation/tgstation#30365]
as title says, joined round. some harmful virus is about.
it was unnamed. i cured myself. got my blood as per. put in the cured blood.
option to make vaccine
make a vaccine
bottle comes out empty and its not even named the "virus name here" vaccine
just bottle and its empty.
i took the virus and put it in and named it
took a fresh blood sample and clean beaker
put it in the machine
says the virus that im immune to is the same name of the virus i just renamed
so they match
try to make a vaccine again.
same thing

Vaccines produced are empty and not even a vaccine bottle. just 'bottle'

![image](https://user-images.githubusercontent.com/19328411/29999567-da8c79c6-9002-11e7-92d0-692a690f35d7.png)

**Comment by DaxDupont** [comment]
Known issue see #30357 #30174

**Comment by XDTM** [comment]
Fixed by #30357, someone close this
