### ISSUE TITLE
Second-hand sad trombone implants dont work

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#30376]
If you successfully remove the clown's existing sad trombone implant, you will be unable to trigger its effects with the *sad emote after you've implanted it into yourself again. Whether it triggers when you die is unknown as i didn't test it.

- As follows i removed implant with surgery by holding a implant case in my offhand while i removed the implant with a hemostat, i then used a RnD injector (identical to the normal object) to insert it into myself.

I dont know if there was any other conflictions either with other implants but it should have all still been inside my body, given i also extracted out someones "health implant" and put that into myself too.

If there's a PR to add this to RnD it should most definitely be tested to work on people. #19535

**Comment by Repukan** [comment]
Isn't the sad trombone implant activated on death?

Did you try death gasping?

**Comment by RemieRichards** [comment]
It only runs on death.

**Comment by FantasticFwoosh** [comment]
Well why are people telling me it activates when you enable the *sad emote? are they just wrong?

**Comment by RemieRichards** [comment]
borgs have a *sad that plays the sound.
but that's borgs.
