### ISSUE TITLE
Stands become invincible when the user falls into a chasm

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#30377]
If you are a stand and you are manifested when you user falls into a chasm, you become invincible and can't take any damage. I tried fighting a bubblegum after my host jumped into a chasm and my "host health" wasn't dropping, even when bubblegum was hitting me with attacks constantly. I THINK that you can also wander around by yourself without being teleported back to where your host was, too.

**Comment by Repukan** [comment]
Is this how we achieve Requiem holoparasites?

**Comment by Supermichael777** [comment]
null != 0

**Comment by Supermichael777** [comment]
what the fuck it even checks if its null
