### ISSUE TITLE
Borging clears traitor objectives

### ISSUE THREAD

**Issue by extramrdo** [tgstation/tgstation#30373]
round 75622

End-round green text:

The Traitors Were:
Durandal_VII was Easy Pete the Curator and survived (used 10 TC) 
Objective #1: Steal the station blueprints. Fail.
Objective #2: Escape on the shuttle or an escape pod alive and without being in custody. Success!
The traitor has failed!

SaveVatznick was Leora Fleebish the Cyborg and survived as Le.Ra Fleebot (used 11 TC) 
The antagonist was successful!

Leora had an assassinate objective at the start according to post-round OOC chat.

Leora, during the course of the round, got killed, debrained, and borged. So at round end, instead of displaying her failed objectives, there simply were none and thus greentext.

**Comment by CPTANT** [comment]
Confirmed got the same thing just now:

Louges was James Waddler the Cyborg and survived as THIS ROBOT IS TRAINED TO ROBUST YOUR ASS (used 6 TC) 
The antagonist was successful!
