### ISSUE TITLE
Escapes pods are broken

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#30390]
I previously made a ticket about it being broken on ceres but it's actually been broken on meta too.

This might apply to all maps, it's pretty high priority.

The other ticket was closed.
Server revision compiled on: 2017-09-02

288560

**Comment by ShizCalev** [comment]
@lzimann

**Comment by DaxDupont** [comment]
Can't edit the ticket on mobile but I forgot to add they display status: *missing*
