### ISSUE TITLE
centcom's cargo dock is always depressurized due to the station controlling centcom blast/supply doors

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#30408]
@ShizCalev @pudl @pubby 

![firefox_2017-09-04_17-19-58](https://user-images.githubusercontent.com/28678854/30033787-532c62c2-9195-11e7-9a2e-48a877dc4cdb.png)

This also causes the cargo shuttle to be depressurized. 😞

**Comment by pubby** [comment]
I'll fix.
