### ISSUE TITLE
Cargo shuttle broken?

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#30428]
![](http://i.imgur.com/IZ7RPE3.png)

Round ID 75708

The shuttle's arrival circles kept appearing and flashing over and over. Shuttle never left. Time actually appeared to increase to 00:01 after a bit, then back to 00:00. Over 50% time dilation at the time.

Not sure if a system was broken somewhere.

**Comment by pubby** [comment]
Closed by #30422 I think

**Comment by WJohn** [comment]
Ah, I suppose the fix hadn't been put in at the time of the issue report.
