### ISSUE TITLE
Sneezing requires bio-suits to block

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#30447]
Diseases with specific symptoms such as blood (if exposed to being bloodied, such as attacking the patient or getting the saw bloodied via surgery) airbourne and bodily contact reasonably require within the bounds of logic, tight biosuits to stop contamination and quarantine maintenance.

Sneezing however acts upon adjacency but unless there's a mis-interpretation of what defines 'sneezing' as if sneezed upon body contact, even with all careful provisions such as sterile masks, latex gloves & exosuit lab coats or a seperate air supply, you will still be infected regardless as long as you have adjacency.

It seems to be broken when compared to the rest, not sure whether this is a bug or a oversight but since sneezing is extremely common it causes diseases to rapidly spread amongst doctors in medbay, which are usually the most disease concious people on the station unintentionally infecting patients if they can't cure themselves fast enough because the alternative is to wear a bio suit 24/7 if someone in staff develops the sniffles.

- Usual expected manner is that patients outside medbay develop sneezing symptoms, not that medical staff become a large source of it because there's only a handful of bio suits to go around and supplied alternative provisions don't protect against this common symptom.

**Comment by Cyberboss** [comment]
@XDTM

**Comment by XDTM** [comment]
If it's only on contact my guess would be that it's a contact-based disease, that is not just passed by breathing. The infectiveness needed to reach ON_CONTACT would also penetrate a lot of protection, which is kind of a design issue, but to solve that we'd need a better idea to replace that system with.

**Comment by FantasticFwoosh** [comment]
> Unless there's a mis-interpretation of what defines 'sneezing' as if sneezed upon body contact, even with all careful provisions such as sterile masks, latex gloves & exosuit lab coats or a seperate air supply, you will still be infected regardless as long as you have adjacency.

Not even directly on contact, its just based on adjacency with everyone in a 8 tile radius around you, which can be hard to manage when you're sneezing extremely aggressively for regular players to avoid unless fully decked in bio suits.

- I don't know if its the same for coughing either

You were the last person to touch sneezing and virology symptoms @XDTM it seems clear from the code you raised its airbourne effectiveness by making it frequent & constant so this isn't so much as a bug as **extremely poor balancing of something that was already broke** from what is apparent.

> https://github.com/XDTM/tgstation/commit/4f75da628bfbb3b62b23675c7d032bf60984f6c1#diff-0adbe2a50f2e8bc0c7a1540578cf2288R19

- Sneezing according to the code here is a airbourne which makes it egible to be biosuit only, now leaving us with a problem of poor game design in which we have to wear bio suits vs every single symptomatic disease in the game, of which spreads very rapidly.
