### ISSUE TITLE
AI camera issue.

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#30467]
So I've been testing this a few times to make sure it wasn't just a one round thing.  It seems to happen the first time I do it each round for some off reason and no issues after that.

**Comment by GunHog** [comment]
So...what is the actual issue?

**Comment by carshalash** [comment]
Byond crashing when switching from lavaland cameras to station cameras. Whooooops.

**Comment by ExcessiveUseOfCobblestone** [comment]
lol the server crashes or just the client?

**Comment by GunHog** [comment]
Client. This happens to me as well, it is obviously a bigger problem for AIs installed on Lavaland rather than ones switching camera networks.

**Comment by ShizCalev** [comment]
Duplicate of #28689
