### ISSUE TITLE
[Downstream] rapidly examining an object while ghosted can randomly throw the object even anchored

### ISSUE THREAD

**Issue by Poojawa** [tgstation/tgstation#30468]
So we discovered this on Citadel tonight whilst on Pubby with a properly set Tesla engine. 

In a report to me, some chucklefuck decided to spam shift click a mini tesla ball, and it managed to delete the ball and a containment field section, thereby loosing the Tesla into the station.

They apparantly also quickly tested it offline and were able to reproduce the bug.

When I tested it, I couldn't click enough myself on the Tesla, but while doing it to a field generator, it did suddenly act as if thrown, sparking against its own containment field, but not breaking it or the field.

@kevinz000 was mentioned for a similar case tested on live TG as well, though a quick search didn't bring up any issue with this sort of title already reported.

**Comment by YakumoChen** [comment]
why doesn't it have a click delay...?

**Comment by kevinz000** [comment]
@Poojawa yeah i showed anturkey directly incase this was hard to fix so people don't find out and abuse it continuously.

**Comment by Tokiko1** [comment]
So this is how people would loose the singulo every single round.
