### ISSUE TITLE
Announcements from wall-mounted consoles fail if they include symbols like £

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#30471]
They just bump you back to the main menu.

**Comment by ExcessiveUseOfCobblestone** [comment]
I can't help but wonder in what situation would you require pounds~~ when the only real currency is the dollah~~ in ss13

**Comment by Sealed101** [comment]
- seems to have been fixed in #75067 by disabling the ascii sanitization in `reject_bad_text()`
___
![изображение](https://github.com/tgstation/tgstation/assets/75863639/f2d6677b-3360-430e-80bf-1a193822b0b6)
