### ISSUE TITLE
Muh game menus stuck on loading

### ISSUE THREAD

**Issue by Hard4Women** [tgstation/tgstation#30470]
round ID: 75772
Yeah when i load up my game it says 'sending resources' and just gets stuck on that, and the menus for things like the 'craft menu' don't work and are just stuck on loading, as well as other things like machinery menus. can't play like this pls help. yes byond is updated and yes i have reloaded my game and reinstalled byond. I can't use an older version of byond when i start with an old on it just says i need to update

**Comment by Tacolizard** [comment]
https://tgstation13.org/phpBB/viewtopic.php?f=2&t=12793

**Comment by Hard4Women** [comment]
I dun fixed it boys, just had to uninstall some flash player security update.

**Comment by Cyberboss** [comment]
@MrStonedOne juicy info?

**Comment by Hard4Women** [comment]
NEVERMIND ITS STILL FUCKED

**Comment by Cyberboss** [comment]
You can keep this closed if it's working for you

**Comment by Hard4Women** [comment]
yeah its not working again

**Comment by Hard4Women** [comment]
it works briefly when i first start up the game

**Comment by Supermichael777** [comment]
flush byonds catch
gear in the top right
preferences
advanced

if that dosnt work redownload byond

**Comment by Hard4Women** [comment]
it no work. I said that i have tried reinstalling byond and all that shit

**Comment by MrStonedOne** [comment]
http://www.byond.com/forum/?post=2211145

**Comment by Hard4Women** [comment]
it just fixed itself now. byond fucking sucks.
