### ISSUE TITLE
Mechs can't restore their internal air tank content?

### ISSUE THREAD

**Issue by MrROBUST** [tgstation/tgstation#30491]
Some time ago, mechs was controlled via verbs. And there were verb "connect to port" which allowed you to connect with Atmos to refill (or to empty) mech's internal air. Now I can't see it anywhere. Is this functionality missing?

**Comment by AnturK** [comment]
Isn't this automatic now ?

**Comment by SgtxRootbeer** [comment]
Does it matter? (Except for plasmemes) the normal air supply will last literally days.

**Comment by FantasticFwoosh** [comment]
You can if i remember correctly, remove & add air tanks using maintenance protocols and crowbarring it out.

**Comment by AnturK** [comment]
Quick glance shows some dead code and no way of refilling so original issue is completely correct.

**Comment by MrROBUST** [comment]
Fixed in #30551
