### ISSUE TITLE
The Colossus seems to get confused and just stand still for long periods of time after shooting

### ISSUE THREAD

**Issue by imtakingabreakdontatme** [tgstation/tgstation#30513]
I have a sneaking suspicion someone intended this (why?) but it might be a bug who knows

**Comment by Daturix** [comment]
havent noticed this besides a time when there were multiple targets to choose from.

**Comment by YakumoChen** [comment]
I once killed a colossus that stood still and didn't attack because it was targeting a legion corpse it couldn't eat.

**Comment by KorPhaeron** [comment]
@Daturix That might be it, it was in cargo bay so monkeys and mules everywhere
