### ISSUE TITLE
Orion Trail breaks forever when you fail

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#30511]
![nyo56pp 1](https://user-images.githubusercontent.com/17237624/30213016-854fa204-94a7-11e7-9281-17c1255f6f98.png)

**Comment by PraiseRatvar** [comment]
i _think_ @Xhuis did this

**Comment by XDTM** [comment]
Now _that's_ realistic

**Comment by Xhuis** [comment]
Orion Trial: *HARDCORE MODE*

Let me see if I can reproduce this.
