### ISSUE TITLE
Chaplain book/bible sprites broke

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#30523]
![2017-09-08_21-06-54](https://user-images.githubusercontent.com/28678854/30229412-bb630fde-94d9-11e7-9b51-e0827d8789f6.png)
this is supposed to be the dead sea scrolls. the dead sea scroll should not look like the normal bible

**Comment by pubby** [comment]
I don't think anything is bugged, its just the dead sea scrolls doesn't have a unique sprite.
