### ISSUE TITLE
Monkeys can open PDAs by clicking inhands, but not drag click

### ISSUE THREAD

**Issue by Poojawa** [tgstation/tgstation#30536]
Pretty minor, to be honest.

the usual method of looking at pdas via dragclicking it onto the screen gives the 'You don't have the dexterity to do this! ' but clicking it inhands opens the pda as intended, though selecting any options instantly closes with 'You don't have the dexterity to do this! '

**Comment by praisenarsie** [comment]
@morerobustthanyou

**Comment by MoreRobustThanYou** [comment]
why are you pinging me

**Comment by PraiseRatvar** [comment]
tgmonkey 2.0.....................................

**Comment by MoreRobustThanYou** [comment]
tgmonkey 2.0 is an AI change
