### ISSUE TITLE
Rev round ends as soon as it's started.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#30539]
![hdmxwix 1](https://user-images.githubusercontent.com/17237624/30240541-a6aa5a0e-9572-11e7-9181-438ae3d24a0c.png)
![mpgyr1r 1](https://user-images.githubusercontent.com/17237624/30240546-bdc5e956-9572-11e7-8f00-42a0383a9044.png)
https://atlantaned.space/newSS13tools/round.php?round=75890
Not sure what caused it.

**Comment by DoctoreMad** [comment]
Working as intended.

**Comment by praisenarsie** [comment]
actually it is working as intended because there (might because this issue was probably fixed already) be a bug where if you are in softcrit, it counts as death for some reason.

**Comment by DaxDupont** [comment]
@praisenarsie There's no attack messages in the log, the round ended as soon as it started.
See https://atlantaned.space/newSS13tools/round.php?round=75890&logs=true#L-235

**Comment by Repukan** [comment]
Did they enter a locker?

**Comment by PraiseRatvar** [comment]
> 

13:21:46 | 130,130,2 | OOC | Plapatin/(Removes-The-Kebab): SS13 WR SPEEDRUN 0.01 SECONDS
-- | -- | -- | --

**Comment by DaxDupont** [comment]
@Repukan I don't think so, not right on roundstart at least.

**Comment by PraiseRatvar** [comment]
did joan even add logging for softcrit

**Comment by DaxDupont** [comment]
If they softcritted there would be attack logs no?
There's no health loss.

**Comment by Jordie0608** [comment]
@AnturK regarding https://github.com/tgstation/tgstation/issues/31659#issuecomment-336369443; that doesn't look like the case here, in the linked round there is a 4 second difference between the round starting and ending with no disconnections during

**Comment by AnturK** [comment]
Hmm.

**Comment by DaxDupont** [comment]
Maybe a db search for short rev rounds will yield results.

**Comment by AnturK** [comment]
Yeah, i found some other cases.

**Comment by DaxDupont** [comment]
It just happened again in https://atlantaned.space/statbus/round.php?round=80858
Round end report only had one head and one headrev for some reason and the round lasted 1 minute 22.
One head and one headrev seems weird for a population of 85 so maybe something to do with initialization?

**Comment by AnturK** [comment]
Looks fine to me, please read the logs before making assumptions what happened. The sole revhead logged out.
