### ISSUE TITLE
Making someone  a traitor in the traitor panel automatically gives them a PDA

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#30534]
Which sucks if you're just trying to set antag status

@Xhuis Did you change this in your rework?

**Comment by Xhuis** [comment]
Hrmm, I don't think I messed with it, no. I'll take a look, though.

**Comment by ShizCalev** [comment]
Issue would be here somewhere https://github.com/tgstation/tgstation/blob/18f329a3f106844c2fb91e3d20acef5a13a23160/code/datums/mind.dm#L256

That said, I can't seem to replicate TP giving a player a new PDA.
