### ISSUE TITLE
End Round Bad Auth Key

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#30549]
~~NOT (F) but FLWs~~ Under Check Antags.

ADMIN LOG: ExcessiveUseOfCobby/(Lola Cobblestone) clicked an href with a bad authorization key!

**Comment by PraiseRatvar** [comment]
https://github.com/tgstation/tgstation/issues/30541

**Comment by ExcessiveUseOfCobblestone** [comment]
fine ill change this issue

**Comment by Cyberboss** [comment]
#30554
