### ISSUE TITLE
SM's delam projectile/whatever range is borked.

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#30545]
![2017-09-09_17-06-02](https://user-images.githubusercontent.com/28678854/30241738-39295dcc-9581-11e7-8037-33f50ffed12e.png)
I'M GETTING HIT FROM HERE, WHEN THE SM IS WAY OVER THERE. OTHER SHIT IS GETTING HIT TOO AAAAAAAAAAA

sybil, roundid 75895, metastation, Server revision compiled on: 2017-09-09
176312

i predict a higgs-bugson or some stupid stupid bug

edit: also it could've been anomalies spawning faraway either

**Comment by Tokiko1** [comment]
Actually a feature, beams arc more often if the shard has more power, which results in longer range.
