### ISSUE TITLE
Lavaland is supported by lattices now

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#30550]
This is all a centcomm conspiracy.
![wn3b9rz 1](https://user-images.githubusercontent.com/17237624/30243553-fd75f526-95ab-11e7-8fc4-22e9ce84041f.png)
(after gibtonite goes boom_

**Comment by KorPhaeron** [comment]
@ExcessiveUseOfCobblestone

**Comment by ExcessiveUseOfCobblestone** [comment]
Lavaland, Hologram, Shazamm!
