### ISSUE TITLE
Trying to follow a mob while not ghosted gives the auth error

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#30560]
I was in the thunderdome in a human mob, saw a grenade notice, clicked it, jumped to him but got all this nonsense.

ADMIN LOG: kerbinfiber/(Jacqueline Ulery)(?) (FLW) has primed a chemical grenade for detonation at Secret Base(JMP).

ADMIN LOG: KorPhaeron/(Kor Phaeron) clicked an href with a bad authorization key!

ADMIN LOG: Debug mode enabled, call not blocked. Please ask your coders to review this round's logs.

ADMIN LOG: KorPhaeron/(Kor Phaeron) admin ghosted.

**Comment by lzimann** [comment]
already fixed #30554
