### ISSUE TITLE
Regenerating as Lich Without Spells

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#30562]
Whilst playing as wizard and being regenerated as a lich, I have risen without any spells. Died and regenerated again to confirm issue. I was cloned earlier in the round, this may have triggered the lich-dom not working. I also had created an infinite-lasting immovable rod after rod-forming inside a locked closet earlier in the round which may also have something to do with this.

Round ID: 75915

**Comment by ShizCalev** [comment]
#28846 & #27946
