### ISSUE TITLE
Softcrit limits jetpack speed

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#30565]
Was op.
Planted bomb, use detonator. Got too impatient and checked on bomb.
It blew up and I went into softcrit. I was jetpacking INCREDIBLY SLOW, which seems dumb since we are in softcrit, and not the hardsuit.
Bug/consistency issue?

**Comment by YakumoChen** [comment]
see #30563

**Comment by PraiseRatvar** [comment]
@ChangelingRain
