### ISSUE TITLE
Pulse rifles hitting the wall blow up anything in the same tile

### ISSUE THREAD

**Issue by Lobachevskiy** [tgstation/tgstation#30573]
Round ID: 75933

Phazon is phasing through a wall, deathsquad pulse rifle the wall. The pilot of the mech dies before the mech, because apparently pulse rifles call ex_act(), which blows up the contents of everything on a tile (meaning the pilot).

1. I don't think pulse rifles should explode everything in a tile, though that can be debatable.
2. Person inside a mech (inside of anything, really, in my opinion) sure as hell should be at least partially protected from explosion damage.

**Comment by ExcessiveUseOfCobblestone** [comment]
It's deathsquad.

**Comment by PraiseRatvar** [comment]
It's still a bug.

**Comment by Arianya** [comment]
Something something phasing exposes the pilot to heightened damage from energetic forces something something

**Comment by banthebantz** [comment]
is there even a decent alternative to ex_act?

**Comment by Lobachevskiy** [comment]
It can use ex_act I suppose, but my point is, ex_act shouldn't affect contents of all things in the same way. It should have lesser impact on things inside other things (perhaps with the exception being the strongest explosions).

**Comment by PKPenguin321** [comment]
This would also be the case for humans in lockers as a pulse beam hits the locker, or anything similar. We need a category for ex_act bugs.

**Comment by magatsuchi** [comment]
pulse rifles no longer call ex_act, all mentioned bugs no longer reproducible
