### ISSUE TITLE
Play Internet Sound is not being played for all people.

### ISSUE THREAD

**Issue by GuyonBroadway** [tgstation/tgstation#30577]
Some people (myself included) do not hear anything an admin puts fourth via play internet sound. Yes I have all sound settings enabled, yes I have that goonchat slider set to something not 0 and yes I can hear every other sound in the game besides these ones. 

Minor issue yes but it might be indicative of other sound based problems.

**Comment by Cyberboss** [comment]
@JJRcop

**Comment by JJRcop** [comment]
Confirming that enable admin midis is enabled?
I may have to investigate getting a new sound url if it doesn't work the first time. Also did this just happen once or does it happen every time? Have you tried restarting DreamSeeker?

**Comment by GuyonBroadway** [comment]
Yes admin midis are enabled, yes it happens every time, I can hear standard admin midis but can't hear ANYTHING played by play internet sound. I have tested this on both /tg/ and hippie, yes I've rebooted dreamseeker, cleared my byond cache, deleted my skins folder and redownlaoded it, re-installed Byond JUST to be sure and have even tried running the command locally and none of it works.

**Comment by GuyonBroadway** [comment]
windows 7 64 bit whatever the latest update is, I.E version 11 (latest as far as I can tell). 

I did uninstall flash from I.E and pretty much everywhere else on my computer, if that makes any difference.

**Comment by JJRcop** [comment]
What country do you live in, might I ask?

**Comment by GuyonBroadway** [comment]
UK.

**Comment by JJRcop** [comment]
Is there anyone else in the UK that can hear the sounds? Or even outside the US.

**Comment by Cyberboss** [comment]
@RemieRichards is a brit

**Comment by JJRcop** [comment]
So i'm not home atm but I'll try and find out what's going on when I get home. Also @kevinz000 using Play Internet Sound, leaving it blank, then pressing OK will stop playing internet sounds.

**Comment by JJRcop** [comment]
I am suspecting that youtube isn't providing any content if the same link gets spammed by 70 people at once? I'll see what I can do for some testmerges to try and find the issue.

**Comment by GuyonBroadway** [comment]
I'm not sure, but I HAVE found that I cannot hear anything if I try to use it on a local server.

**Comment by JJRcop** [comment]
Does it give an error message on local server, or (you) played web sound (url)?

**Comment by JJRcop** [comment]
@GuyonBroadway please tell me if you hear anything at this url: https://jjrcop.github.io/ie_m4a_test/

**Comment by GuyonBroadway** [comment]
No it does not return an error message but no I do not ear anything at that URL... I have disabled a few plugins for IE, what would I need to hear that?

**Comment by JJRcop** [comment]
Which url?

**Comment by GuyonBroadway** [comment]
the second one does not play via I.E, I think this is an issue on my end.

**Comment by JJRcop** [comment]
does the first url play in game?

**Comment by GuyonBroadway** [comment]
It does actually... how strange

**Comment by JJRcop** [comment]
ok i know what it is...

**Comment by GuyonBroadway** [comment]
Is it something I fucked up? or something wrong with IE in general?

**Comment by JJRcop** [comment]
I'm looking into this, I may need to replace m4a with something else.

**Comment by DaxDupont** [comment]
IE is literally hitler with audio tags. 
Doesn't help audio tags are loose standards.
https://hpr.dogphilosophy.net/test/

**Comment by JJRcop** [comment]
@GuyonBroadway Please try this page in internet explorer and tell me the results https://jjrcop.github.io/ie_m4a_test/mp4.html

**Comment by GuyonBroadway** [comment]
@JJRcop yes that works very nicely.
