### ISSUE TITLE
/atom/movable/lighting_object is stupid expensive to hard delete and is causing alot of lag.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#30589]
````
/atom/movable/lighting_object
    Total Hard Deletes 556
    Time Spent Hard Deleting: 313247ms
````

@PJB3005 any ideas? @tgstation/issue-managers high priority please

**Comment by PJB3005** [comment]
I can't even think of anything that would make them need to be hard deleted. No clue.

**Comment by Cyberboss** [comment]
Lag is from this line probably: https://github.com/tgstation/tgstation/blob/master/code/modules/lighting/lighting_object.dm#L37

Granted, why the fuck are these even being deleted?

**Comment by PJB3005** [comment]
Anything like blowing up floors will delete lighting overlays.

**Comment by MrStonedOne** [comment]
@PJB3005 it was transit turfs throwing the lighting after the shuttle turfs were deleted into transit turfs

This changed the loc, so it couldn't remove the reference to itself
