### ISSUE TITLE
pAI integrated lights broke

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#30581]
They do not emit light. It's like they don't toggle to the on state.

You enable your integrated light.
You enable your integrated light.
You enable your integrated light.
You enable your integrated light.

**Comment by Torston420** [comment]
You have to be in holoform to use your intergrated light, but disabling it isn't possible when you do this, only going back to card form turns it back off. 
Not printing a message saying that it can't be enabled while in card form is probably an oversight?

**Comment by DaxDupont** [comment]
I was in holochassis mode but it didn't emit light at all
