### ISSUE TITLE
RCD Access Control Settings close button doesn't work

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#30591]
Repo;
Right click RCD -> open "Change Airlock Access" window -> click close. Nothing happens.

Every other button on the interface works as intended.

https://github.com/tgstation/tgstation/blob/2e58d7bc86af6e4c5edd9b60c65501b4fbd68981/code/game/objects/items/RCD.dm#L199

**Comment by PraiseRatvar** [comment]
this is a bit recent then, since i believe it worked last week

**Comment by Mooshimi** [comment]
![FdPjfIvPvS](https://user-images.githubusercontent.com/85910816/138021835-ee343a74-7280-4e93-b342-f9df0a298235.gif)
Seems to work fine now. Please reopen if I closed this in error
