### ISSUE TITLE
Putting a KA with a sec light on it that's on in a bag will break light till reactivated.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#30595]
1. Put KA with light on in bag.
2. Take KA out.
3. No more light emitted from it.
4. Toggle KA.
5. Light emits once more

**Comment by vuonojenmustaturska** [comment]
I remember noticing this on the real server at some point but I can't reproduce it on my local machine at all

**Comment by vuonojenmustaturska** [comment]
I haven't been able to reproduce this in-game on the real server and I have shaft miner set to high, I think it's a side-effect of the really high server lag the server had before the shuttle light del fixes went in.
