### ISSUE TITLE
Nuclear Operative toy C20rs and L6 saws no longer start with riot darts

### ISSUE THREAD

**Issue by ma44** [tgstation/tgstation#30614]
#30531 

How to reproduce
1. Buy either a toy submachine gun or a toy machine gun from the nuclear operative uplink
2. Shoot it and realize there's only blue darts coming out. 

Sure you can spend 2 tc on 20 riot darts, but that's a pretty heavy nerf to the LMG.

**Comment by BeeSting12** [comment]
dont L6s have lethal ammo?

**Comment by ma44** [comment]
The toy l6 saws used to have riot darts, but now it's foam darts.

**Comment by msgerbs** [comment]
Working on a fix. That PR really didn't think of what else would be effected by just changing all toy guns to use toy darts...

**Comment by msgerbs** [comment]
Working on a fix for this. That PR changed the base toy C20r and L6 for no apparent reason, since the toy guns in the vending machine use a variant anyway.
