### ISSUE TITLE
Ever since the 4th MC crashes have become much more frequent

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#30611]
https://tgstation13.org/parsed-logs/mcrash.txt

@tgstation/commit-access

**Comment by DaxDupont** [comment]
Sooo all the timers breaking and what not might not be hurricane related?

**Comment by bgobandit** [comment]
The timers were breaking well before the hurricane

**Comment by DaxDupont** [comment]
That was what I was thinking but I wasn't sure if I remembered it wrong or not. It's been way worse the last few days or so.

**Comment by ninjanomnom** [comment]
Made a quick thing to make that more readable, repeat crashes from the same round are excluded.
https://pastebin.com/7sVQdYPG

That means
May had 13
June had 5
July had 22
August had 10
And this month so far has 14

July seems suspicious but honestly this isn't enough information. In ftl13 we crash almost every round but we have far longer rounds.

This wasn't happening last week for us but we are far behind in mirror prs at the moment so problem is somewhere in https://github.com/tgstation/tgstation/compare/d951b65...23dd7dd which are the prs merged in that timeframe.

This is all assuming we share the same bug as mso thinks. If that is the case though it means the bug only happens in longer rounds than is normal for tg but is almost every round in ftl13. The sudden crash increase in July does provide some evidence towards that, though as I said before the amount of data here isn't enough to verify a pattern.

**Comment by Cyberboss** [comment]
This still an issue?

**Comment by MrStonedOne** [comment]
yes

**Comment by ninjanomnom** [comment]
What fixed this?
