### ISSUE TITLE
Supply Console can't be set to allow contraband

### ISSUE THREAD

**Issue by Somenerdsomewhere** [tgstation/tgstation#30615]
In at least 2 shifts I've done today as quartermaster I've attempted to deconstruct a supply console and retool its board to "broad". However, when you put the board back in and reassemble the console, there is no contraband options because the board is somehow resetting itself once you put it back into the console.

To reproduce, disassemble a console, multitool the board to broad, reinsert and construct the machine

**Comment by msgerbs** [comment]
I thought you had to emag a supply console to order contraband? Can you actually just deconstruct it instead?

**Comment by YakumoChen** [comment]
multitooling it allows you to gain 'contraband' as opposed to 'syndicate items' which come from emag.

**Comment by Somenerdsomewhere** [comment]
examples of "Contraband" include the Biker kit (Leather coat, Cargo Cap, bandana, ATV and keys for the ATV) and the High yield clown grade cream pie crate (8 banana cream pies)
