### ISSUE TITLE
Pickaxe not digging sand

### ISSUE THREAD

**Issue by Artemiuz28** [tgstation/tgstation#30616]
Round ID: 75980

Joined for free golem. Can't dig sand with pickaxe. If it's meant to be this way, add shovel to vendor. If not, fix this.

**Comment by Cyberboss** [comment]
@ExcessiveUseOfCobblestone

**Comment by Onule** [comment]
Shovels don't seem to work either, so anything that used to dig sand doesn't work now I guess.

**Comment by Firecage** [comment]
@ExcessiveUseOfCobblestone You broke digging on asteroid tiles with your archeology PR.

**Comment by Cyberboss** [comment]
@ExcessiveUseOfCobblestone or myself fixed this I believe
