### ISSUE TITLE
Robotic prostheses. Organ manipulation steps and descriptions.

### ISSUE THREAD

**Issue by MrROBUST** [tgstation/tgstation#30623]
Operations on robotic limbs acting like they are for organic (retract the skin? clamp bleeders? saw through the bone? What?)
May be there should be different way, as with xenomorphs. Using mechanical tools perhaps?

**Comment by QualityVan** [comment]
Most/some? surgeries specifically don't work on non-organic limbs. What procedure were you seeing this with?

**Comment by MrROBUST** [comment]
>Most/some? surgeries specifically don't work on non-organic limbs.
Organ manipulation working. Augmented chest and arms can receive/lose organs.
So, you have patient with robo arm, and he want toolarm implant to it. Then you start to cut skin (of metal arm?), retract it, etc.
We need more logical way.

**Comment by QualityVan** [comment]
Got it, thanks

**Comment by SpaceManiac** [comment]
Fixed by #30818
