### ISSUE TITLE
Turrets on the Centcom Battlecruiser shuttle shoot at the crew.

### ISSUE THREAD

**Issue by SyruseEln** [tgstation/tgstation#30642]
Round ID 75998
See subject. Please correct me if I am wrong.

**Comment by Teepeepee** [comment]
were there any mobs like slimes or xenobio spawned mobs? the turrets shoot at them by default, even if there's humans in the way of the shot.

**Comment by TribeOfBeavers** [comment]
There were slimes on the shuttle that were being shot at, if this is the round I was thinking of.

**Comment by Supermichael777** [comment]
not a bug

**Comment by Anonmare** [comment]
Tell the xenobio mobs to stay off the shuttle

Slimes are _healed_ by lasers so make sure they don't go on the shuttle
