### ISSUE TITLE
easel

### ISSUE THREAD

**Issue by SgtxRootbeer** [tgstation/tgstation#30703]
metastation, right above the boxing ring in, near the holodeck
![easel](https://user-images.githubusercontent.com/22112255/30396359-3c18feb6-987e-11e7-9c3d-58fad94b1a0a.PNG)

**Comment by praisenarsie** [comment]
easel

**Comment by Cyberboss** [comment]
hmmm, no varedited icon states actually

**Comment by BeeSting12** [comment]
I made this issue once, someone told me it's a cache issue. I'll try and find the issue

**Comment by BeeSting12** [comment]
#17643
#26184

**Comment by Cyberboss** [comment]
Duplicate of #26184
