### ISSUE TITLE
Player Panel isn't working with certain actions

### ISSUE THREAD

**Issue by LetterJay** [tgstation/tgstation#30721]
I have debug admin hrefs enabled. Clicking things such as mute, get, or send to lobby yields no action nor a runtime/feedback.

Other actions such as forcesay work.

**Comment by Poojawa** [comment]
transformation, heal, kick/ban/send to lobby All work as well.

**Comment by Poojawa** [comment]
oh. Jay should totes look a few touches down. but yee

**Comment by Cyberboss** [comment]
Duplicate of #30687
