### ISSUE TITLE
Heat exchange pipes are broken

### ISSUE THREAD

**Issue by Sunoplyrus** [tgstation/tgstation#30737]
Basically the heat exchange manifold pipe is not connecting with the junction, as shown in the image, and no air goes through.
I've been only doing this on MetaStation, however I doubt this has something to do with the map, since we're replacing common pipes with heat exchange ones.

![dreamseeker_2017-09-14_15-39-58](https://user-images.githubusercontent.com/31968974/30447637-263359d0-9963-11e7-9e46-760433b6a6b8.png)

**Comment by CPTANT** [comment]
I noticed this as well, it seemed like only one of the four heat exchange manifold orientations was broken however.

**Comment by Cyberboss** [comment]
@pubby  was this fixed?
