### ISSUE TITLE
Emergency oxygen tank issues

### ISSUE THREAD

**Issue by Bremlo711** [tgstation/tgstation#30748]
Round ID: 76116
Map: Metastation

I went to go drain the oxygen from my emergency oxygen I started with upon round start, so I went to the pumps outside of engineering and drained it. It reads '0 kPa', yet I can still breathe from it just fine, I have been for about 10 minutes.  
https://i.imgur.com/Lc5HajE.png
~~Upon seeing this, I searched around for another oxygen tank, drained it using a different pump, and now it displays it having '3.63004e-005 kPa', and I can't breathe from that one. 
https://i.imgur.com/4D5N98I.png~~ (fixed on #30749)

**Comment by ShizCalev** [comment]
3.63004e-005 = 0.0000363004.

**Comment by GLACoding** [comment]
if the output pressure of a tank is 0kPa then you will be "breathing" from it if you set internals, but you will actually be taking air in from the environment i believe.
Try testing this by using the tank in space.

**Comment by YPOQ** [comment]
Fixed by #31422
