### ISSUE TITLE
Androids will consume Vitality from Clockwork healing abilities without being healed.

### ISSUE THREAD

**Issue by Torston420** [tgstation/tgstation#30755]
Round ID: 76134 

Thanks for Kevinz for helping me confirm this on Thunderdome:

I used Sentinel's Compromise on myself, I took Toxin damage without healing any of my Brute damage.
This also applies to Vitality Matrices pointlessly wasting Vitality but I have no on-server proof of this, only local testing.

If Androids not being able to heal from Clockwork healing abiltiies is somehow intended, I doubt them consuming Vitality and giving you Toxin damage isn't an oversight.

**Comment by ShizCalev** [comment]
@Xhuis

**Comment by Xhuis** [comment]
This is not my bug; I didn't make androids. I'll see what I can do.

**Comment by Xhuis** [comment]
Nevermind, my local copy doesn't want to play nice so I can't test to see if this happens. I'll have to reproduce this some other time.

**Comment by dragomagol** [comment]
Rip clockwork
