### ISSUE TITLE
Duplicating boards

### ISSUE THREAD

**Issue by Sunoplyrus** [tgstation/tgstation#30758]
Disconnecting an AI upload monitor with a screwdriver duplicates the board.
I haven't tried other monitors yet.
![2017-09-15_10-37-19](https://user-images.githubusercontent.com/31968974/30484826-fe2e0a62-9a01-11e7-8d77-4c901a91f413.gif)

**Comment by Cyberboss** [comment]
#30693

**Comment by Cyberboss** [comment]
@KorPhaeron @lzimann

**Comment by Sartorius7** [comment]
It also works with arcade boards. Unless this is intentional?
