### ISSUE TITLE
Atmos distro stopped working correctly?

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#30759]
Round ID: 76137 if that helps.
Station was Metastation.
As a drone, only very few vents would let me ventcrawl, all scrubbers were working fine.
I couldn't unwrench any distro pipes nor vents.
The distro's gas flow meter would say "The sensor error light is blinking."
I managed to fix it by unwrenching and wrenching back a gas pump connected to the distro.
Afterwards, distro would very slowly fill up.

**Comment by Penguaro** [comment]
@Onule What happened with the vents that wouldn't let you vent crawl. Was a message given? Can you give an example of one of the vents that didn't work?

**Comment by Onule** [comment]
If I remember correctly, the vents couldn't be interactable, no message. I think the working vents weren't connected to the broken vents, there was a medium sized bomb in brig, the vents in there were working.
Hallway vents weren't work.

**Comment by duncathan** [comment]
weird, sounds like missing parents. the eternal bug. usually they're supposed to resolve themselves these days, though.....
maybe one day i will return with a glorious pipenet rewrite to follow once more in father aran's footsteps

**Comment by kriskog** [comment]
This predates, but #36642 describes it better.
