### ISSUE TITLE
The ORM will consume an rcd if you click with it

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#30764]
You insert a material total of 100000 into the ore redemption machine.

This deletes the RCD and as far as I can tell gives no resources

**Comment by ExcessiveUseOfCobblestone** [comment]
@Cyberboss Material Component

**Comment by GunHog** [comment]
Or the Protolathe **eating my bluespace garbage bag and everything inside of it!**

**Comment by YakumoChen** [comment]
Protolathe and ORM eats things that aren't meant to be deconstructed like the honkmother staff

**Comment by YakumoChen** [comment]
also #30296 is related and still isn't fixed
