### ISSUE TITLE
Replace TerrainPassthrough on TheDerelict space ruin with space tiles so the lighting won't be so fucked.

### ISSUE THREAD

**Issue by McRex007** [tgstation/tgstation#30782]
I like to build a mini base on KC13 sometimes, but those funky terrainpassthrough tiles make anything built on them fully illuminated from all directions.

**Comment by TheBonded** [comment]
this seems to be a feature request, which is no longer accepted on the issue repo

Also after 4 years I assume something has been done to this extent anyways.
