### ISSUE TITLE
Meta/Box station Arrivals shuttle depressurizing

### ISSUE THREAD

**Issue by Poojawa** [tgstation/tgstation#30780]
https://i.gyazo.com/c20c1249b0530e006efcb52d8f0240ff.png

The cockpit area ends up being space. nadda clue where the leak actually is. It kills people before the shuttle arriving sequence finishes and they actually are able to realize there's an issue.

[20:31:11] Runtime in gas_mixture.dm, line 394: Cannot read null.gases
proc name: compare (/datum/gas_mixture/compare)
src: /datum/gas_mixture/immutable/s... (/datum/gas_mixture/immutable/space)
call stack:
/datum/gas_mixture/immutable/s... (/datum/gas_mixture/immutable/space): compare(null)
space (122,159,1) (/turf/open/space/basic): process cell(4430)
Atmospherics (/datum/controller/subsystem/air): process active turfs(1)
Atmospherics (/datum/controller/subsystem/air): fire(1)
Atmospherics (/datum/controller/subsystem/air): ignite(1)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)

[20:31:10] Runtime in LINDA_turf_tile.dm, line 92: Cannot execute null.archive().
proc name: archive (/turf/open/archive)
src: the plating (124,137,1) (/turf/open/floor/plating/airless)
call stack:
the plating (124,137,1) (/turf/open/floor/plating/airless): archive()
space (124,136,1) (/turf/open/space/basic): process cell(4430)
Atmospherics (/datum/controller/subsystem/air): process active turfs(1)
Atmospherics (/datum/controller/subsystem/air): fire(1)
Atmospherics (/datum/controller/subsystem/air): ignite(1)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)

**Comment by Poojawa** [comment]
To be honest, the runtimes are in empty centcom space, since the arrivals shuttle's hyperspace is 11. But maybe it touches in there on the way to the station? Damnifino.

**Comment by ShizCalev** [comment]
@ninjanomnom @AnturK

It's an issue with shuttle movement from what I'm seeing, happening with all maps.

probably related to #30212
also mentioned in #30767

Video of the tiles loading slowly, which is causing the depressurization;
https://i.imgur.com/4MpduSJ.gifv
https://i.imgur.com/tI3lnqV.gifv

**Comment by ShizCalev** [comment]
It's FAR worse on Omega / Delta.

https://i.imgur.com/g9XCltA.gifv

**Comment by Cyberboss** [comment]
WHO CHECK_TICKED SHUTTLE MOVEMENT!!!! AHHHHH!!!!

**Comment by SpaceManiac** [comment]
Ran a bisect, the bug was introduced in f860464b6278f8f90410b60a27528e10dd9489c8 (#30684).
