### ISSUE TITLE
Unable to remove embedded throwing star

### ISSUE THREAD

**Issue by TheAutism** [tgstation/tgstation#30783]
Round # 76160 i was playing the detective and after someone threw a throwing star at me i was unable to remove it normally (clicking the embedded objects icon then the embedded object itself) it was stuck in my right arm. Surgery was able to remove it.

**Comment by Supermichael777** [comment]
that button has never worked

**Comment by Poojawa** [comment]
Really should be able to remove embedded stuff easier than just surgery. Have surgery nullify or super reduce the pain modifier.

**Comment by Supermichael777** [comment]
it falls out fast for most items, but you start bleeding super fast.

**Comment by Poojawa** [comment]
Yah, but no-one else can help tug things out of other people, the only way is to preform surgery or to have them run around until it procs the fall out chance so you can slap a bruise patch on.

**Comment by jughu** [comment]
Auctaly you can remove but its kinda random at times because its buggy

**Comment by ShizCalev** [comment]
Pretty sure this is fixed. Will close in a week without another repo.
