### ISSUE TITLE
Limit wizards to 1 teleportation type spell, and maybe make it not guaranteed when stunned or otherwise incapacitated?

### ISSUE THREAD

**Issue by McRex007** [tgstation/tgstation#30792]
If you combine get out of jail free spells as a wizard, like rod, jaunt, and other movement or teleportation spells, you basically become impossible to keep around long enough to kill. Having complete power over an engagement and always being able to say "I'm losing, so I'm not gonna keep going" and teleport away to freedom makes them nigh impossible to kill.

**Comment by BeeSting12** [comment]
This is an idea/balance change, please post it in the ideas section of the forums located at tgstation13.org/phpBB

**Comment by Repukan** [comment]
Not an issue.
