### ISSUE TITLE
Syndicate Medical Cyborg missing Energy Saw toggled-on sprite

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#30790]
Bonus - Syndicate Medical Cyborg missing module sprite (the one off-centre right of the HUD at the bottom, next to active modules).

**Comment by ShizCalev** [comment]
Module sprite looks fine to me.
![x6mqkrd](https://user-images.githubusercontent.com/6209658/30509731-5e561cc6-9a85-11e7-819a-f9d57d832901.png)

**Comment by Supermichael777** [comment]
@AnonymousNow Clear your catch and retest
open byond (the hub not a game)
click the gear in the upper right hand corner
click the preferences option
click the games tab
press clear catch
Then retest (ask an admin when dead or something)

if it still happens consult with a coder-min, but this looks like a local resource file error

**Comment by AnonymousNow** [comment]
Instructions followed.

![cyborgsaw](https://user-images.githubusercontent.com/6266927/30516543-3fbb1f9a-9b3a-11e7-8ad9-87438f5214bb.png)

Bug reproduced.

**Comment by ShizCalev** [comment]
@AnonymousNow Are you talking about the saw? I see the module sprite fine in your picture
![ctwdq5j](https://user-images.githubusercontent.com/6209658/30516931-6a21ae44-9b1b-11e7-9596-c8936d756a0d.png)

**Comment by AnonymousNow** [comment]
I'm talking about both. In my active module slot is the activated energy saw. The sprite you posted is a blank one used for non-selected modules, not a Syndicate medical cyborg module sprite.

**Comment by ShizCalev** [comment]
Oh I see what you mean now. Syndicate borgs & syndicate medical borgs don't have a unique sprite for those.

**Comment by ShizCalev** [comment]
Oh I see now, lets see herrrrre.

**Comment by ShizCalev** [comment]
Hm. Both syndicate borg's module `moduleselect_icon` vars are set to the `"malf"` icon, but instead it's defaulting back to the base `"nomod"`.

**Comment by ShizCalev** [comment]
Why closed? The module sprite it still messed up

**Comment by AnonymousNow** [comment]
Oh, doy, yes - I was thinking of the main issue, the invisible saw sprite. 

Er, how do I reopen this thing?

**Comment by Bawhoppen** [comment]
There's a button next to comment?

**Comment by AnonymousNow** [comment]
Ah, yes. Guess I was too used to seeing that as something else.

**Comment by Mooshimi** [comment]
![image](https://user-images.githubusercontent.com/85910816/137454281-3147cad2-2890-44ca-a7c1-d991eafd9413.png)
saw seems to be fine now but the cyborg module icon(the tiny computer screen thing) doesn't have a special icon for this borg is what I think they're also saying?
