### ISSUE TITLE
Chemfridge :b:roke

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#30808]
Server revision compiled on: 2017-09-14

20e541

![2017-09-16_16-13-47](https://user-images.githubusercontent.com/17237624/30513260-b3d121b6-9b00-11e7-9f83-c0b00507dc81.png)
Those missing are .1u vaccine pills.

**Comment by praisenarsie** [comment]
@vuonojenmustaturska

**Comment by vuonojenmustaturska** [comment]
I'll take a look. Any idea if the items had a goofy name of any kind?

**Comment by vuonojenmustaturska** [comment]
I thought the fix would be easy, maybe vaccines are weird? Let's repro something real quick.
`[19:50:47] Runtime in pandemic.dm,198: Cannot read null.name`

Looks like there's a bigger bug hiding in the vaccines/antibodies/diseases system, I'll take a look at that as well, if only to reproduce this to fix chemfridges.

**Comment by vuonojenmustaturska** [comment]
Good news, i managed a repro and they're separate bugs
