### ISSUE TITLE
Lightgeists cannot be Servants of Ratvar yet becoming a Nar'Sian acolyte is perfectly fine.

### ISSUE THREAD

**Issue by Torston420** [tgstation/tgstation#30812]
I don't know why they're even elegible for conversion, but hey, they are.

![Converted Lightgeist](https://i.imgur.com/kOJi0c0.png)

**Comment by Supermichael777** [comment]
lightgeist?  friendo are you sure your in the right place?

**Comment by Torston420** [comment]
https://github.com/tgstation/tgstation/blob/6e468720ab02d72f0545c871abd79ca5a6b9a49c/code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
CTRL+F, 'Helpers', or 'Lightgeist'.

**Comment by Iamgoofball** [comment]
test

**Comment by Bawhoppen** [comment]
See no problem here?

**Comment by Bawhoppen** [comment]
Clockcult and Bloodcult aren't supposed to be 100% parallels of each other. Bloodcult kind of makes more sense as being just available to every mob and stuff.

**Comment by KorPhaeron** [comment]
Not a bug
