### ISSUE TITLE
Independent tally of votes for the headcoder position right now

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#30815]
Since Remie is incredibly untrustworthy(lied about quitting)
https://file.house/SpZc.png
and is already back trying to start a coup, I think we need to make sure an unbiased person is keeping tally of the votes to prevent Remie from tampering with shit.

![tally](https://file.house/AUG1.png)
As of right now, this is the current tally.

**Comment by praisenarsie** [comment]
you are biased

**Comment by Cyberboss** [comment]
> Lied about quitting

![untitled](https://user-images.githubusercontent.com/8171642/30514939-3a0c4814-9aed-11e7-9de6-5c5512e549f6.png)

Low effort shitpost
