### ISSUE TITLE
Lavaland Treasure - Strange Elixir & Cloning

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#30817]
Round: 76167

As a miner, got wings from the strange elixir in lavaland. Died, got cloned. Cloned body still had the wings, but no button in the top left corner to activate or deactivate flight. Gouty spawned in another elixir to fix it, by it had no effect. Had to resort to making a new mob for me to control, along with another elixir.

So in short, wings don't carry over properly when cloned.

**Comment by Repukan** [comment]
Might be a problem with species change or the angel race, since the potion technically just makes you an angel.

**Comment by jughu** [comment]
WHEN WILL WE MAKE THE WINGS A ORGAN

**Comment by MrROBUST** [comment]
@jughu good point. Do we have only that angelic wings or some another (bat wings for devils)?

**Comment by MrROBUST** [comment]
What to do with `/ datum / species / angle`?
Should you become an angel species when you get wings? Should wings work if your species is not an angel?

**Comment by XDTM** [comment]
We just have to call update_action_buttons() on the cloned mob after the client gets in

**Comment by DoctoreMad** [comment]
>/datum/species/angle

Heh

**Comment by MrROBUST** [comment]
Yea, this potion actually mekes you an angel. And wings is species mutation. So, we need to think about what to do: remove/leave angels, leave wings as mutation or make it organ. Or just fix button (Aaaaand, it was done while I wrote it -_-).

**Comment by XDTM** [comment]
it did reveal a bigger, deeper issue so that's nice

**Comment by FantasticFwoosh** [comment]
Angel race is a flawed attempt to apply a mutation bodypart, in itself its poorly made.
