### ISSUE TITLE
Proto-Kinetic Accelerator Visibility-Based Firing Issue

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#30822]
If you can't see a tile at all when firing a proto-kinetic accelerator, it won't fire.

That may seem like an insignificant issue, or even a good thing - but if you're a miner, you'll know why this is an issue. The PKA digs at the wall in the direction where you're facing, but since you can't fire it at a rock wall directly next to you, you need to either back up or click at the tile behind it (the latter is what most miners do). If you aren't wearing mesons for some reasons - say, as a miner borg, who recently lost them from their possible equipment - the PKA will no longer fire if you do this.

This makes digging awkward, since you'll likely be dragging an ore box behind you for the most part, so stepping backwards can be annoying - and you'll have to do it every time you step too close.

**Comment by TheWiznard** [comment]
so this issue is about not being able to fire by clicking directly on the tile? I don't see why this is an issue since you can just click past the tile at the black space in the first place??

**Comment by AnonymousNow** [comment]
You CAN'T click the tile behind it that you can't see. It won't fire if you do this. It was mentioned.

**Comment by TheWiznard** [comment]
I don't know if I'm insane or what but is this not what you're talking about?

[https://www.youtube.com/watch?v=PaXiA1ode_Q](url)

**Comment by AnonymousNow** [comment]
...huh.

I've been incapable of doing that for a few rounds. I'll see if I can replicate this issue my end again.

**Comment by AnonymousNow** [comment]
Okay, it's been replicating inconsistently in some rounds and working as intended for others. I'm not sure what could be causing it.
