### ISSUE TITLE
Sleepy pens can be refilled.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#30838]
Yeah I kinda just saw someone take down 6+ players using one and a mixture of poisonous chemicals.

**Comment by Cyberboss** [comment]
Intentional, not a bug

**Comment by Onule** [comment]
"The pen holds one dose of the mixture, and cannot be refilled."
From the uplink description.

**Comment by CPTANT** [comment]
Uplink description is outdated. The sleepy pen being refillable is intentional.

**Comment by TheWiznard** [comment]
#12827 ?

**Comment by ExcessiveUseOfCobblestone** [comment]
Cyberboss is abusing the PR GBP system.
