### ISSUE TITLE
Emitter and Reflector Issues

### ISSUE THREAD

**Issue by ChucklesMcPickle** [tgstation/tgstation#30849]
76257, 76258, 76259
2017/09/17

1) Emitters cannot fire north no matter what orientation they are placed in. If they are pointed north and activated they will fire east.

2) At the beginning of the round all reflectors are placed in a 0 degree, 90 degree, 180 degree, or 270 degree orientation. This happens both on MetaStation and DeltaStation.

3) When an emitter beam is fired east at a reflector whose orientation is -45 degrees, the beam will be reflected back in the direction it came from instead of being reflected north. -44 degrees and -46 degrees both work. 315 degrees does not work. There may be other orientations that have the same problem but I could not find them.

**Comment by ShizCalev** [comment]
@kevinz000 think you were refactoring these for directional ones anyway, no?

**Comment by kevinz000** [comment]
can we please put things about testmerged prs into testmerged pr comments this isn't an issue far as im aware right now because im pretty sure i fixed them.

**Comment by AnturK** [comment]
Caused by #30599
