### ISSUE TITLE
Goonchat still messes up formatting for MOTD on basil

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#30843]
Been this way since goonchat first was added.

**How MOTD should look (took in brief period of lag before it resets):**
![image](https://user-images.githubusercontent.com/6510293/30525460-760ee7ce-9bcc-11e7-939d-2245bbb5afdc.png)

**How it actually looks:**
![image](https://user-images.githubusercontent.com/6510293/30525466-7fa18a26-9bcc-11e7-8873-9127b0316909.png)

@Cyberboss x :100:

**Comment by Bawhoppen** [comment]
hastily thrown together issue report

**Comment by praisenarsie** [comment]
@MrStonedOne too i guess

**Comment by Cyberboss** [comment]
goonchat html bs
