### ISSUE TITLE
posi brain announcement sound is noticeably louder than the rest of the announcement related sounds 

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#30855]
@GunHog

**Comment by GunHog** [comment]
The posibrain ghost notification sound does not specify the volume. To what are you comparing it?
Code here: https://github.com/tgstation/tgstation/blob/6e468720ab02d72f0545c871abd79ca5a6b9a49c/code/modules/mob/living/brain/posibrain.dm#L40

**Comment by vuonojenmustaturska** [comment]
I can confirm the posibrain ghost sound is extremely loud

**Comment by kriskog** [comment]
Reduced
