### ISSUE TITLE
Wormhole Jaunters are not working properly.

### ISSUE THREAD

**Issue by Mey-Ha-Zah** [tgstation/tgstation#30879]
Round 76313

Stuck it on the belt then walked into a hole, trying to see how they worked.

It activated one tile below me and I fell to my death. The tile had walls above and to the right, with ash turf to the left and anothe chasm below.

**Comment by Hatfish** [comment]
It's because wormholes don't activate when you touch them anymore, the portal needs to be clicked on to teleport something but you can't exactly do that when falling down a chasm.

**Comment by DoctoreMad** [comment]
​>You can't use Pride's mirror anymore
​>Its actually impossible
Amazing
