### ISSUE TITLE
Silencer and bypassing w_class limits

### ISSUE THREAD

**Issue by Pyko1** [tgstation/tgstation#30886]
You cant fit a silenced whatever in to a pocket.
But you can attach a silencer to the said whatever while it is in your pocket.
Hence allowing you to have silenced-whatever in your pocket even tho it does not fit in it.

Should probably allow attaching silencers only if the whatever is in your hand or on map.

**Comment by Cyberboss** [comment]
sounds like w_class changes need a wrapper function

**Comment by Bawhoppen** [comment]
I thought you were only able to attach a silencer if it was in your hands.
