### ISSUE TITLE
Wizards (and other roles?) start buckled to the arrivals shuttle

### ISSUE THREAD

**Issue by pubby** [tgstation/tgstation#30892]
Admin tab -> Create Antagonist. Pick wizard and spawn. You'll spawn in the wizard ship but be buckled to a chair in the arrivals shuttle.

**Comment by AnonymousNow** [comment]
> You'll spawn in the wizard ship but be buckled to a chair in the arrivals shuttle.

![surprised bill](https://user-images.githubusercontent.com/6266927/30618909-7b5c8096-9d94-11e7-8f12-2aa34decf3b5.jpg)

# BUH-WHAT.

**Comment by bgobandit** [comment]
magic
