### ISSUE TITLE
roburger doesn't do anything

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#30928]
it's supposed to give you a disease that borgs you but I've tested it multiple times and have yet to become a borg

**Comment by Repukan** [comment]
🅱orging disease 🅱roke

**Comment by praisenarsie** [comment]
@XDTM i thought it was a reagent rather than a disease

**Comment by YPOQ** [comment]
Can't reproduce. Were you a species immune to diseases?

**Comment by bgobandit** [comment]
iirc this was specifically removed

**Comment by XDTM** [comment]
it wasn't removed, it seems functional from the code

Did you already have a disease/were an immune species?

**Comment by Cyberboss** [comment]
Closing this in 24hrs if no one can reproduce. Sounds like the disease just didn't run for some reason

**Comment by YakumoChen** [comment]
I was human and I ate the roburger as is. Got it from Silver Slime foods. It's difficult to reproduce due to the difficulty of actually acquiring one.

**Comment by Cyberboss** [comment]
Just ate a roburger on sybil and waited, worked fine

**Comment by ShizCalev** [comment]
24 hours passed, no repo
