### ISSUE TITLE
create custom outfit button makes the message appear

### ISSUE THREAD

**Issue by Ausops** [tgstation/tgstation#30930]
[Directions]: # ADMINS you have to report EVERY button that triggers the href token prompt or is other wise broken, as a separate issue report, on github, if you want it fixed. Stop assuming some other admin is going to report it. *Come October 14 debug mode will be disabled and these will cease working.*

[For Admins]: # ADMINS you have to report EVERY button that triggers the href token prompt or is other wise broken, as a separate issue report, on github, if you want it fixed. Stop assuming some other admin is going to report it. *Come October 14 debug mode will be disabled and these will cease working.*

**Comment by AnturK** [comment]
Should i go full admin abuse, and make these persist.
