### ISSUE TITLE
Universal translator module doesn't work on pAIs

### ISSUE THREAD

**Issue by McRex007** [tgstation/tgstation#30937]
Not sure how its supposed to work, but I can't even turn it on. I can understand others, however.

**Comment by GunHog** [comment]
Download and activate the module. Click the little language button that all mobs get near the bottom, or use the action button to choose langages.

**Comment by optimumtact** [comment]
Please request help with using items via the ingame admin help with f1 or via the forum or looking on the wiki.

Only after you've had help and confirmed it doesn't work should you file a bug here.

Thanks
