### ISSUE TITLE
De-conversion due to brute trauma does not show up fully in attack logs

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#30952]
It shows that the person got de-revved but doesn't show who did it. Sometimes that is clear from the context but if there are multiple attackers, not necessarily.

**Comment by BeeSting12** [comment]
It doesn't tell you your deconverted in the chat either. You have to look for your R to disappear

**Comment by Robustin** [comment]
I mean it doesn't tell you specifically but there's definitely a "[your name] remembers their true allegiance" or something like that.

**Comment by BeeSting12** [comment]
I was unconcious when deconverted so I almost attacked the guy who hit me on the head then I noticed the lack of R on my head

**Comment by Robustin** [comment]
I fixed this with a PR, the lack of a message and the lack of log details.
