### ISSUE TITLE
Jump Boots break if used in a sleeper

### ISSUE THREAD

**Issue by imw-Oculus** [tgstation/tgstation#30963]
Round # 22905 (Hippie)

Reproduced and confirmed by me, an administrator. If Jump boots are used in a sleeper, the HUD icon for the user no longer produces the desired effect.

**Comment by vuonojenmustaturska** [comment]
Reproduced here also, the most straightforward fix is not necessarily the best one but I have a good hunch on how to fix this.

**Comment by vuonojenmustaturska** [comment]
The bug was that jump boots relied on the throw_at callback to reset their "jumping" state back to false, however throw_at would never call the callback on an early failure return. See PR for fix details.
