### ISSUE TITLE
Cloned nightmares spawn without armblade

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#30964]
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by KorPhaeron** [comment]
wtf why are people cloning nightmares

**Comment by praisenarsie** [comment]
what if they are antag

**Comment by BeeSting12** [comment]
@KorPhaeron 
The dude said he was curious about what it did and didn't see it in action so he cloned it.

**Comment by KorPhaeron** [comment]
Fair enough. Did it get its spell or no?

**Comment by BeeSting12** [comment]
I didn't get the chance to take a look. I think it could jaunt and use night vision but not 100% sure. It definitely didn't get the armblade.

**Comment by BeeSting12** [comment]
tested in thunderdome. spells are broke too

**Comment by AnonymousNow** [comment]
Tested a week back, we got the spells but not the armblade.

**Comment by BeeSting12** [comment]
spells were greyed out might be because area was lit up.

**Comment by XDTM** [comment]
Nah action buttons dont self-update, so since they begin stunned they start out looking not available and never change.
