### ISSUE TITLE
Metastation issues

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#30978]
@ShizCalev @pubby 

- there are outdated metal foam grenades in metastation's engi storage, they should be **smart** metal foam grenades or at least renamed to them if they already like that.
- there is no engineer's wardrobe in engineering (engi clothing)
- there's no paper (and paper bins) in the art storage, add some fountain pens too while you're at it ;)
- secure network access/ai upload is missing firelocks

![2017-09-23_12-58-12](https://user-images.githubusercontent.com/31222036/30773189-6e12a736-a063-11e7-8e6e-df39146a5c93.png)
YUCKY TRIANGLE WALL NEAR HOLODECK

**Comment by praisenarsie** [comment]
![2017-09-23_19-37-48](https://user-images.githubusercontent.com/31222036/30776026-be3698c0-a096-11e7-999c-9ffdeb291009.png)
to add to it i guess

**Comment by ShizCalev** [comment]
> there is no engineer's wardrobe in engineering (engi clothing)

there's two, actually.
