### ISSUE TITLE
blueprints can fuck over the white ship causing to just break or somethin

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#30981]
![2017-09-23_14-04-42](https://user-images.githubusercontent.com/31222036/30773457-c390e65a-a068-11e7-8d30-2a0aab8efa9b.png)
the whip ship landed under derelict, borg wanted to make a ghetto airlock and so did. someone launched the white ship causing it to lose a piece of it because derelict's ghetto airlock took the piece?

![2017-09-23_14-05-20](https://user-images.githubusercontent.com/31222036/30773463-e1ce26a0-a068-11e7-923b-dac92a0e662d.png)
i don't even know what happened, i think the shuttle arrived somewhere and just fucking BROKE itself, smashing just everything somehow.

roundid 76495
Server revision compiled on: 2017-09-23

The following pull requests are currently test merged:
#30972: '[MOSTLY READY] Atmospherics Multilayer Pipes - Last PR got bugged and couldnut be testmerged properly!' by kevinz000 at commit b769ec

Based off origin/master commit: d7b48a

**Comment by newfren** [comment]
Hi I was a borg riding this ship. I was told to make an airlock section to the north and I did so then I used my blueprint to make it an airlock - when the ship left it tore away the doors and walls that were part of the whiteship. I didn't actually see the ship leave cause I was dc'd but that's why this happened.

**Comment by kevinz000** [comment]
my pr is not related

**Comment by jughu** [comment]
![knipsel5](https://user-images.githubusercontent.com/14280283/30778025-056785c8-a0ca-11e7-9850-e32996db780d.PNG) miners are gonna be mad aftee this one...

**Comment by praisenarsie** [comment]
i didnt explain this good but this is more of a blueprint bug rather than a shuttle bug. i already explained this to antur and ninjanom.

**Comment by ninjanomnom** [comment]
This is more of a feature request for better area control than anything. Blueprints work like that and changing it is pointless.

Turf by turf area control would solve this as would a way to view the area you're in as an overlay.
