### ISSUE TITLE
admin gibprocs are sql fucked

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#30994]
ADMIN LOG: Feemjmeem/(Lilly Mcclymonds) called Lilly Mcclymonds's gib() with no arguments.

Lilly Mcclymonds has died at Bar.

ADMIN LOG: ERROR: Advanced admin proc call led to sql query. Query has been blocked

**Comment by Cyberboss** [comment]
Not a bug, you need to use Smite -> gib instead of advanced proc call.

**Comment by lzimann** [comment]
not being able to proccall gib is fucking stupid

**Comment by Cyberboss** [comment]
Figure out a better way to guard sql from apcs and you can change it
