### ISSUE TITLE
Play Internet Sound is missing a volume specifier

### ISSUE THREAD

**Issue by JamieH** [tgstation/tgstation#31001]
Play Global Sound has one but Play Internet Sound doesn't, normally I like to play my things at like 25-30 volume, can we please get a modified on the server side for Play Internet Sound too?

Thanks

**Comment by JJRcop** [comment]
I considered this when I made the feature, but I decided that I'd let the players use the midi volume slider in the options menu.

**Comment by JJRcop** [comment]
I may change my mind, but I don't want players to nearly not hear something because they have their volume set to 30, an admin plays music at volume 30, so they turn it up, then later their ears bleed because another admin plays some music at a higher volume.

**Comment by JamieH** [comment]
The issue is there is a HUGE lack of awareness of the volume slider.

**Comment by JJRcop** [comment]
I do plan to address this
