### ISSUE TITLE
href authorization

### ISSUE THREAD

**Issue by bobdobbington** [tgstation/tgstation#31007]
Round ID 76574:
ADMIN LOG: Bob Dobbington/(Daisy Holmes) clicked an href with no authorization key!
ADMIN LOG: Debug mode enabled, call not blocked. Please ask your coders to review this round's logs.
ADMIN LOG: Bob Dobbington/(Daisy Holmes) jumped to coordinates 121, 86, 2

**Comment by Cyberboss** [comment]
What did you click?

**Comment by Cyberboss** [comment]
There was one misfire in that round: `UAH: _src_=holder;adminplayerobservecoodjump=1;X=121;Y=86;Z=2`
