### ISSUE TITLE
Forcing a secret mode causes admin href shittery

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#31006]
ADMIN LOG: Bgobandit/(Bgobandit) set the forced secret mode as [redacted].

ADMIN LOG: Bgobandit/(Bgobandit) clicked an href with no authorization key!

ADMIN LOG: Debug mode enabled, call not blocked. Please ask your coders to review this round's logs

**Comment by Cyberboss** [comment]
https://github.com/tgstation/tgstation/blob/a479714b5fa43b88db2d89ad98d8e9285ea3198b/code/modules/admin/topic.dm#L1256 This shittery again
