### ISSUE TITLE
Pandemic says virus is spread on contact when it should be airborne.

### ISSUE THREAD

**Issue by Adanps** [tgstation/tgstation#31019]
Round ID 76603
While mucking about I created a virus with 11 transmission, which should be the point at which they become airborne as far as I know. When I looked at in the Pandemic 2200 the spread was shown as on contact. I did not test to see if the virus actually spread on contact or was airborne for various reasons.

![ss 2017-09-25 at 05 08 46](https://user-images.githubusercontent.com/32281090/30834298-1dda0ba4-a218-11e7-9b3f-1f159a5581a0.png)

I'm not 100% sure about this because I'm using the wiki for my information despite parts of it being outdated. Perhaps I'm wrong and 12 transmission is when viruses become airborne now.

**Comment by Cyberboss** [comment]
@XDTM

**Comment by XDTM** [comment]
I think having more symptoms makes it harder for the transmission vector to improve

**Comment by XDTM** [comment]
To be exact to be airborne you need (transmission - symptom number) to be at least 6, so yeah it was 12

**Comment by Adanps** [comment]
Good to know, thanks!
