### ISSUE TITLE
Air tanks issues

### ISSUE THREAD

**Issue by ktccd** [tgstation/tgstation#31011]
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)
AIR tanks (mixed air that is), use the O2 icon, which is downright confusing at best. Further, pressing "reset" sets them to 16 pressure, which will kill you if you relied on that before and didn't notice the change now.

Similarly, O2 tanks seem to start at 101 pressure, despite only needing 16.
(This is for the large tanks, by the way)

**Comment by nicbn** [comment]
No, the air tanks are actually pure O2.
At least for the last time I checked.

**Comment by RandomMarine** [comment]
Tanks only start with either plasma, oxygen, or an oxygen/n2o anesthetic mix.

There are no tanks that come with an oxygen/nitrogen mix
Are you mixing up tanks and **canisters**?

**Comment by RandomMarine** [comment]
Actually there are o2/n2 mix tanks.
One in the metastation white ship.
A few in emergency supply kits from cargo.
And one in the RD's locker(?????????????????????)

**Comment by msgerbs** [comment]
Wait really? How did I never notice this?

This honestly sounds more like a mapping oversight.

**Comment by msgerbs** [comment]
Never mind, I get what you're talking about now. I thought you mean the emergency size ones.

**Comment by ktccd** [comment]
Seems Random got it working in his PR. And yeah, further testing showed the O2 started properly, my testing just got them mixed up 'cause I got confused by the pile of tanks XD.
