### ISSUE TITLE
If someone's appearance changes, their preview changes or character preview is borked

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#31013]
![2017-09-25_19-02-02](https://user-images.githubusercontent.com/31222036/30823491-337a33ba-a224-11e7-817c-6f8f70295f12.png)
does not match up to hair, facial hair, etc too

**Comment by praisenarsie** [comment]
Ok? It fixed iteself when I re-entered the setup character menu

**Comment by BeeSting12** [comment]
cute

**Comment by praisenarsie** [comment]
![2017-09-27_17-45-47](https://user-images.githubusercontent.com/31222036/30926612-a4049f32-a3ad-11e7-91bf-1483a0b1be65.png)
seems somewhat consistent, the bearded one is mine

**Comment by Cyberboss** [comment]
@kevinz000
