### ISSUE TITLE
Engineering borgs can't use their pseudocircuit as an airlock circuit board

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#31018]
@Xhuis probably an oversight given that they can make doors with their RCD normally but they should still be able to do so for completeness

**Comment by Xhuis** [comment]
This was intentional; airlock circuits aren't "simple" (they need to be interacted with), so I let the RCD keep that function alone.

**Comment by KorPhaeron** [comment]
Not a bug apparently
