### ISSUE TITLE
Cyborg internal lights are immune to nightmares' Light Eaters

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#31023]
I got into a fight as a mining cyborg against a nightmare, and they whacked me several times with their light eater to no effect. This really screwed over the nightmare I was fighting at the time, though I didn't realise it was unusual until afterwards.

Duncdar and I replicated this at the end of the round; he was an engineering cyborg this time, but it didn't matter. When he was first hit, his icon updated and the edges of the light seemed to flicker, as if becoming a little dimmer. It didn't happen again after that.

Cyborg lights are important, and without them they're pretty boned. But I'd expect a nightmare's hard-counter not to be cyborgs, of all things. Their lights should be turned off and unusable for ten seconds, like the lights-out effect of being hit by a goliath.

**Comment by Repukan** [comment]
@KorPhaeron

**Comment by msgerbs** [comment]
I believe there was another issue about this where people were debating how to actually do it. Somebody suggested an internal bulb to replace.

**Comment by KorPhaeron** [comment]
The camera fix is still not on server as far as I know

**Comment by Cyberboss** [comment]
Not yet live then I guess, bug me if this isn't fixed in a day
