### ISSUE TITLE
If your brain is taken out as a syndicate borg and re-borged as a station borg, you will still have the syndicate icon above your head.

### ISSUE THREAD

**Issue by awesine** [tgstation/tgstation#31021]
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.) 76607

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by SgtxRootbeer** [comment]
Are syndieborgs nothing but brokenness?

**Comment by CoffeeDragon16** [comment]
I don't think this is an issue, you keep your status as an operative no? And it's an 'antag with asimov' deal.

**Comment by SuperNovaa41** [comment]
i mean yeah, this literally isn't a bug. You aren't losing any antag status by having your brain moved around.. as said above: asimov is preventing you from harming people.
