### ISSUE TITLE
Cannot recast wizard touch spells to regain cooldown and disable spell using the action button

### ISSUE THREAD

**Issue by AutomaticFrenzy** [tgstation/tgstation#31039]
[Directions]: # 
Steps to recreate: Be wizard, cast touch spell and then try to cast it again to disable it and regain cooldown
Expected result: Spell leaves your hand and becomes recastable
Observed result: Spell stays on your hand

**Comment by ShizCalev** [comment]
Minor correction, they can't recast through the action button. Casting through the spell menu works as intended.
