### ISSUE TITLE
engieborg adaptive circruitboard won't apply to a windoor.

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#31047]
What it says on the tin.

**Comment by ShizCalev** [comment]
See #31018

**Comment by SgtxRootbeer** [comment]
Windoors can't be made with the Borg's rcd though

**Comment by ChangelingRain** [comment]
The solution here should be to make the circuit a subtype of airlock boards so you get the interface, and have it just spawn a normal airlock board and copy the vars for the door.

**Comment by magatsuchi** [comment]
cyborg's adapative circuitboard's no longer apply to windoors (or airlocks for that matter)
