### ISSUE TITLE
Clockcult z level is loaded on non-clockult rounds.

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#31051]
Waste of Z and resources. Also likely cause of #31050

**Comment by AnturK** [comment]
That requires admin who can load it up anyway, so it's no excuse

**Comment by ChangelingRain** [comment]
It spawns with ghost roles, though.

**Comment by Xhuis** [comment]
Reebe does spawn with two cogscarab shells regardless of roundtype. The scarabs can't interact with or get to the station in any way and their sole purpose is so people can toy with base designs as ghosts.

I'll try to figure out if it's causing the z-level issue, though. I'm not very familiar with z-level code so it's very possible that it might cause some issues.

**Comment by Cyberboss** [comment]
Given that this is intentional, I guess it's here to stay
