### ISSUE TITLE
Lings can use envy's blade to become lingmares.

### ISSUE THREAD

**Issue by Bluespace** [tgstation/tgstation#31057]
Wew lad.

**Comment by DoctoreMad** [comment]
CARRY THE BLACK TORCH
ROUSE THE IDLE DEAD

**Comment by calzilla1** [comment]
E M E R G E N T

**Comment by Mercenaryblue** [comment]
Bug? Feature!

**Comment by Repukan** [comment]
The darkness holds much worst than mere trickery… and boogiemen.

**Comment by praisenarsie** [comment]
@KorPhaeron

**Comment by AnonymousNow** [comment]
Absolutely a feature.

If you're a changeling who's got a hold of Envy's Knife and found a Nightmare to stab, I think you deserve this.

**Comment by ExcessiveUseOfCobblestone** [comment]
why is it limited to lings?

**Comment by AnonymousNow** [comment]
I'm guessing that it isn't, but the idea of being a changeling with the power to darkjaunt is too much for some.

**Comment by Bluespace** [comment]
Never forget the medbay massacre.
