### ISSUE TITLE
Unable to fly off station sector

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#31050]
Round ID: 76664
Server revision compiled on: 2017-09-27
The following pull requests are currently test merged:
#31034: 'Nightmare organ' by KorPhaeron at commit b6fa79
Based off origin/master commit: b0dd98

Jetpacking north, south, east or west all resulted in getting back to station sector (2), used GPS to verify.

**Comment by Xhuis** [comment]
This is definitely caused by #31051. I have no idea how to fix it, though...
