### ISSUE TITLE
shade was invincible on blood cult

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#31055]
Round ID 76681. As seen by logs I emptied a full energy gun into it and hit it with a stunbaton on harm intent several times and the fucker wouldn't die. Also witnessed a chaplain hit it many times with a null rod.

https://pastebin.com/3MtBRp3A

**Comment by AnturK** [comment]
The shade must have left the soulstone in non-conventional way but i can't find anything in the logs/runtimes.

**Comment by Robustin** [comment]
Was fixed by #31055

**Comment by vuonojenmustaturska** [comment]
A september bug was not fixed by a PR merged in may

**Comment by ShizCalev** [comment]
Gonna close in a week without another repo
