### ISSUE TITLE
You can crash everyone around you by doing somethign that spams chat messages under goonchat

### ISSUE THREAD

**Issue by silicons** [tgstation/tgstation#31052]

**Comment by ExcessiveUseOfCobblestone** [comment]
sounds like a high priority bug!

**Comment by DaxDupont** [comment]
Yeah that was the cause of the pressure plate crasher

**Comment by PKPenguin321** [comment]
This issue was opened about 3 months after goonchat was merged, and has remained open for the last 2 years or so. Have we had any instances of goonchat spam outright crashing the game lately?

**Comment by ExcessiveUseOfCobblestone** [comment]
funny enough yes

**Comment by notfrying1pans** [comment]
goonchat can cause the game to lag for a few seconds but i havent crashed due to it

**Comment by kriskog** [comment]
SSChat limits the amount of goonchat messages over time now, this should be fixed
