### ISSUE TITLE
Starting Cogscarabs can complete the ark, summoning ratvar in non-cult rounds

### ISSUE THREAD

**Issue by TheWiznard** [tgstation/tgstation#31068]
Round ID: 76696
Server revision compiled on: 2017-09-27
The following pull requests are currently test merged:
#31034: 'Nightmare organ' by KorPhaeron at commit 0246ac
#31053: 'Revert pull request #30773 from Cyberboss/Rats' by ShizCalev at commit 05fa11
Based off origin/master commit: 59e755

Nuke ops round where nukes flopped then the two roundstart  cogscarabs somehow completed the requirements to start the ark and summon ratvar, preventing the shuttle from leaving

![ss 2017-09-27 at 04 24 32](https://user-images.githubusercontent.com/9158683/30939193-3e85f83c-a3a2-11e7-945e-cb1b580f72ae.jpg)

**Comment by Anonmare** [comment]
I will only tell how I did it to a coder in PMs

**Comment by ChangelingRain** [comment]
Given that the only possible way to activate it is to varedit it, I am seriously impressed.

**Comment by Xhuis** [comment]
Yes, this is seriously weird and I don't have any idea how it could have happened.

**Comment by Xhuis** [comment]
@Anonmare Give a look at your forum inbox.

**Comment by Cyberboss** [comment]
Stupid rabbit

**Comment by Anonmare** [comment]
@Xhuis Sent. I can do this reliably on any roundtype

**Comment by AnonymousNow** [comment]
I love the FUCK tag.

**Comment by Xhuis** [comment]
Looks like it wasn't the scarabs after all.
![](https://puu.sh/xKyOn/dcc893054e.png)
Go home, everyone. Party's over.

**Comment by kevinz000** [comment]
thanks jerome

**Comment by ChangelingRain** [comment]
wow what a surprise

**Comment by msgerbs** [comment]
How did somebody even get to control the cogscarabs?

**Comment by AnonymousNow** [comment]
There are two cogscarab shells in Zebes every round that can be used by ghosts. They're limited in what they can do by their toolset - they can't recite scripture, nor can they visit the station. But they can run around R'lyeh and test out their own equipment, which is the intended purpose.
