### ISSUE TITLE
You can use an inducer to recharge a mech from the inside

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#31065]
>When you counter the combat mech's one weakness

👌👌👌😂

**Comment by SgtxRootbeer** [comment]
i dont see this as a problem. you cant swap hands whilst inside, or mess with your backpack, iirc so you only got the one inducer and whatever it has as charge...
in theory, if the mech has a slimecore, and your inducer has a slime core, you might be at a little advantage, but not by much.

**Comment by Anonmare** [comment]
We had a phazon guy with a yellow slime core inducer and self-repair drone and literally laughed off ion rifles

**Comment by AnonymousNow** [comment]
Seems fun, but also seems like it'd tip the balance just a little bit too much.

**Comment by SgtxRootbeer** [comment]
yeah but like, why go through the inducer juggle when you can just install a yellow core into your mech from the get-go?

**Comment by AnonymousNow** [comment]
Why not both? You could outstrip the power drain on practically anything that way.

Tell me, do you need to be stopped in order to internally use the in-hand inducer? Can you still move the mech? Can you still use its equipment?

**Comment by Anonmare** [comment]
As far as I can tell, you don't need to stop and can continue using your equipment

**Comment by YakumoChen** [comment]
the self-repair drone is laughably slow, sustained fire can still destroy a mech with ease.

**Comment by XDTM** [comment]
just make inducers able to feed ion rifles so the field is even

**Comment by YakumoChen** [comment]
How do you even do this because untried replicating it and couldn't get it to work

**Comment by YakumoChen** [comment]
Also a phazon with a yellow slime core cell installed  is going to have literally zero trouble with power anyway. You have to be a gygax with the actuators on to even remotely have a chance to outstrip the power regen
