### ISSUE TITLE
Abductor scientist can't use science tool.

### ISSUE THREAD

**Issue by awesine** [tgstation/tgstation#31104]
[Directions]: #76737
Neither the agent or the scientist could use the science tool.

**Comment by bgobandit** [comment]
Were they event-spawned abductors, or did they become abductors via admin spawning ayys manually (without the event button -- this will make more sense to admins), or some other method?

**Comment by XDTM** [comment]
May have something to do with my species fix, i'll check

**Comment by Dorsisdwarf** [comment]
event ayys

**Comment by ExcessiveUseOfCobblestone** [comment]
did you hit the tool on the camms console?
