### ISSUE TITLE
Rebee floors break to space

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#31102]
Doesn't seem very lore friendly

Floor should probably have itself as a baseturf (chasms with void sprites might be cool but also overpowered)

@Xhuis

**Comment by Xhuis** [comment]
Reebe is secretly a big ball of paper mache floating through space made to look spooky
It is known

**Comment by Xhuis** [comment]
The white "void" tiles do actually have themselves as a baseturf. I'm not especially sure why they're becoming space.
