### ISSUE TITLE
You can't give golems chainsaw arms

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#31109]
Hey maybe the scientist was shitty but please test this

**Comment by ShizCalev** [comment]
It's cause they're made of rock and can't lose limbs, ergo you can't replace the limbs either.

**Comment by Armhulen** [comment]
makes sense but they can get augments but not chainsaw arms?

**Comment by GunHog** [comment]
Perhaps you should consider **amputation surgery!**

![image](https://user-images.githubusercontent.com/4955510/30997614-caebd9a8-a48e-11e7-8825-2a58a9db8fb7.png)

**Comment by KorPhaeron** [comment]
Not a bug

You're of course free to change how chainsaw arms work if you'd like
