### ISSUE TITLE
Revheads can be spotted MedHUD

### ISSUE THREAD

**Issue by Suicidalpickles** [tgstation/tgstation#31101]
pretty much what the title says, tried it out on a test-server. Made a revhead dummy, then plucked on Medical HUD as another dummy.
![4](https://user-images.githubusercontent.com/32374784/30991837-a6680b2a-a45b-11e7-8745-2e1624617eb5.PNG)

**Comment by ShizCalev** [comment]
@Robustin IT'S ALL YOUR FAULT.

#30957
