### ISSUE TITLE
Supermater Sliver Objective: Tongs dust on removing sliver from the supermatter.

### ISSUE THREAD

**Issue by Nabski89** [tgstation/tgstation#31107]
[Directions]: #  Round76740

Had the extract a super-matter silver objective. Removing the supermatter sliver with the tongs dusts the tongs.

"You touch the supermatter crystal with the supermatter extraction tongs, and everything suddenly goes silent.
The supermatter extraction tongs flashes into dust as you flinch away from the supermatter crystal."

**Comment by ShizCalev** [comment]
User error.

When you use the scalpel on the crystal, it spawns a shard underneath you. You pick THAT up with the tongs. What happened here was that they clicked the crystal itself with the tongs, which is what the manual provided explicitly says not to do.

> Approach an active supermatter crystal with proper protective gear. DO NOT MAKE PHYSICAL CONTACT.
> Physical contact of any object with the sliver will dust the object, as well as yourself.

**Comment by ChangelingRain** [comment]
User, possibly design error; sliver should be above shard if it isn't.

**Comment by ShizCalev** [comment]
It spawns underneath the user. Correcting now.

**Comment by Nabski89** [comment]
Well I'm just retarded then. I read it as slice it off, then remove the slice from the crystal, like you do organ removal. I didn't see that it showed up below me. Possibly because it showed up below me.
