### ISSUE TITLE
Which BYOND version(s) are confirmed to compile this codebase?

### ISSUE THREAD

**Issue by DogmaOfDan** [tgstation/tgstation#31119]
I have the current version of BYOND, but am getting compile errors.  What version(s) of BYOND are known to compile this codebase without error?  If it is really more accurate to check the version of DreamMaker (or other program) that actually does the compile, please let me know.

I'd like to hear from those who compile this codebase without errors.  If you respond, please do me the favor of including confirmation of the version (and program, if talking about something other than BYOND) that you compile with.

It makes sense to me to do this simple check up front.  I've looked and searched for this specific confirmation, but not finding it.  Thank you.

**Comment by lzimann** [comment]
Latest stable(511.1835). 
You can check either [here](https://github.com/tgstation/tgstation/blob/master/code/_compile_options.dm#L65) or the [travis script](https://github.com/tgstation/tgstation/blob/637b4feee2fcc8f1fcdadcbca256b8f7de1b1b00/.travis.yml#L5) to get the major version required.
