### ISSUE TITLE
Smart metal foaming agent: Unable to mix

### ISSUE THREAD

**Issue by 81Naoki** [tgstation/tgstation#31120]
Combining the ingredients for smart metal foaming agent doesn't mix them.
I assume that this wasn't reported yet since it was never put on the wiki and people just grab smart foam grenades from vending machines.

See: required_reagents = list("foaming_agent" = 3, "acetone" = 1, "iron" = 1)

**Comment by ExcessiveUseOfCobblestone** [comment]
@KorPhaeron @optimumtact just checked this and it works fine for me.

Make sure you're using normal foaming agent which is lithium and hydrogen!
