### ISSUE TITLE
Plasma Cutters hits only one tile

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#31124]
Only relevant recent pr from my understanding is #30714

No testmerges, Bagil 76768 in case it's just something derpy with that particular round.

**Comment by praisenarsie** [comment]
@KorPhaeron

**Comment by Repukan** [comment]
Finally, the nerf it needed

**Comment by Mey-Ha-Zah** [comment]
If you want to nerf plasma cutters, offer an alternative.

**Comment by DaxDupont** [comment]
@Mey-Ha-Zah doesn't understand what jokes are.

**Comment by jughu** [comment]
Why dont you just make plasma cutters moddable like kas but instead if you get extra range you get lower delimb etc eyc

**Comment by Repukan** [comment]
Plasma cutters should honestly drop the pretense of being a direct reference and instead be changed to burn damage to reflect firing plasma derived projectiles.
