### ISSUE TITLE
Floor is lava doesn't seem to work

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#31148]
Didn't actually happen after it being randomly triggered by a summon events.
Needs testing

**Comment by Bawhoppen** [comment]
Also the button in secrets doesn't even seem to work properly

**Comment by Bawhoppen** [comment]
Seems to just be visual.

**Comment by YPOQ** [comment]
#28344

**Comment by Cyberboss** [comment]
Duplicate of #28344

**Comment by ShizCalev** [comment]
Dupe #28344
