### ISSUE TITLE
When a station name is changed, cargo's stock computers don't update the station name.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#31154]
![2017-09-30_13-33-50](https://user-images.githubusercontent.com/31222036/31045886-4b74d000-a5e5-11e7-8238-56f9ff3ca2c4.png)
![dreamseeker_2017-09-30_13-34-50](https://user-images.githubusercontent.com/31222036/31045887-4cb41980-a5e5-11e7-9e94-30fcc0f44787.png)

**Comment by Cyberboss** [comment]
Caused by #30763  i think
