### ISSUE TITLE
Launching a shuttle with aliens weeds on it makes the weeds unaligned

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#31164]
![2017-09-30_15-45-04](https://user-images.githubusercontent.com/31222036/31046754-5b9d1b2a-a5f6-11e7-89f4-0d8bb762439f.png)

occured on wabbajack shuttle, someone got turned into xeno and planted weeds BEFORE shuttle launched.

**Comment by Cyberboss** [comment]
@ninjanomnom

**Comment by ninjanomnom** [comment]
Interesting, I have no clue how this one would be caused. Did the shuttle rotate mid flight and if so what were the rotation amounts on entering and leaving transit space?

**Comment by praisenarsie** [comment]
dupe of #25410

but anyway afaik it did roate midflight @ninjanomnom 90degrees counterclockwise

**Comment by ShizCalev** [comment]
Duplicate of #25410

**Comment by ShizCalev** [comment]
also Duplicate of #18519
