### ISSUE TITLE
Aggressive metabolism viruses are cured instantly if spread by sneezing.

### ISSUE THREAD

**Issue by Adanps** [tgstation/tgstation#31169]
Round ID 76810

While testing viruses I found that a combination of sneezing and aggressive metabolism is near useless thanks to what I believe to be a bug. Aggressive metabolism normally starts a virus at level 5 instead of level 1, and will decrease over time. But if someone with the virus sneezes and spreads it, the recipients will nearly instantly have the virus cured. I even checked their blood and found they had antibodies for the disease. 

When I asked someone else, they found it odd and said sneezing probably forced the virus to start at level 1, which causes it to be instantly cured since it has aggressive metabolism. My guess is that this is unintended, because the virus starts at level 5 when spread normally.

![dummy](https://user-images.githubusercontent.com/32281090/31047964-c06a60f2-a5d9-11e7-8469-aac6e7b5f5b5.png)

Here is the symptoms of the virus I tested to see what would happen.

**Comment by XDTM** [comment]
Aggressive metabolism is actually supposed to set a timer for the disease, after which it should self-cure. My theory is that somehow multiple diseases shared a timer, so everyone who was infected by a person got cured at the same time. I'll test.

**Comment by XDTM** [comment]
Scratch that, it's literally self curing instantly on every infectee.

**Comment by XDTM** [comment]
Turns out that spreading diseases never call Start on their symptoms, since they copy the `processing` var!
Goddamn var copying

**Comment by Adanps** [comment]
Alright! The fix seems to have worked! I tested out a few combination, and I can safely say the escape shuttle is going to be a lot scarier to be on if there's an evil virologist.
