### ISSUE TITLE
You can't attack people crawling away as blob

### ISSUE THREAD

**Issue by Dicks1** [tgstation/tgstation#31178]
Round: 76817

I watched the same RD crawl away from me 4 different fucking times in crit and I couldn't do anything to stop him. Why can't I attack people who are in crit?

I may be wrong but it sure looked like as soon as they got knocked down none of my blob's spawning on them did anything.

**Comment by kevinz000** [comment]
you...
can?

**Comment by kevinz000** [comment]
can you not? just grow on their tile..?

**Comment by Dicks1** [comment]
But they just crawled away when I would grow on them.

**Comment by Dicks1** [comment]
Maybe I'm wrong but I kept clicking their bodies while they were crawling away and I could never stop them, so if this isn't a bug then something should be done about them being able to just crawl to safety.
