### ISSUE TITLE
The "Change Map" verb does nothing.

### ISSUE THREAD

**Issue by GuyonBroadway** [tgstation/tgstation#31170]
Download tgstation as zip.

Compile, launch local server via dream daemon.

Wait for server to be ready, hit start game then change map.

Feel like you missclicked and missed the verb try again, and again and again.

Lament at the nothingness of your actions.

**Comment by Cyberboss** [comment]
The map change doesn't go into effect until the server reboots.

**Comment by GuyonBroadway** [comment]
No as in clicking the verb doesn't even bring up a window with which to select a map to change to.

**Comment by Cyberboss** [comment]
This is due to the maprotation line in the default config being commented out for some reason https://github.com/tgstation/tgstation/blob/master/config/config.txt#L299
