### ISSUE TITLE
Responding to deadminned admin(???)PM causes href shittery

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#31182]
Tsaricide was deadminned, ahelped something, I clicked the link in chat:

ADMIN LOG: Bgobandit/(Clown) clicked an href with a bad authorization key!
ADMIN LOG: Debug mode enabled, call not blocked. Please ask your coders to review this round's logs.
ADMIN LOG: Bgobandit/(Clown) has started replying to Tsaricide's admin help.

round 76820, Sybil

**Comment by ShizCalev** [comment]
@Cyberboss
