### ISSUE TITLE
Traitor Brothers is violently broken

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#31197]
Round ID: 76836

We had a Traitor Brothers round start earlier today and got this:

https://puu.sh/xN9f9/7ebf2f74df.png

Antags didn't know who their brother was. Logs should be able to point out more of the chaos.

Yeah. Assign to Pubby please.

**Comment by kevinz000** [comment]
#31196 fixes the screenshot, the "doesnt know who their bro is" thing isn't though.

**Comment by JJRcop** [comment]
@pubby

**Comment by BeeSting12** [comment]
i knew who my bro was that round

**Comment by Jalleo** [comment]
@kevinz000 This fixed or not?
