### ISSUE TITLE
Papercode is broken

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#31195]
Priority CRITICAL

**Comment by calzilla1** [comment]
The HoP class is litterally broken

**Comment by Bawhoppen** [comment]
It literally is hence the priority critical tag request. Without paper the HOP's role is defunct and he's a pretty important role.

**Comment by Bawhoppen** [comment]
Explanation: Writing anything on paper does not work

**Comment by Iamgoofball** [comment]
<Iamgoofball> check if stamps work
<Iamgoofball> if stamps dont work
<Iamgoofball> then it's priority high because cargo broke
<Iamgoofball> otherwise, priority low

**Comment by Bawhoppen** [comment]
Goof, you don't need to be antagonistic about things like this.

**Comment by Iamgoofball** [comment]
I'm being frank, paperwork is an optional feature. We're not high RP enough to require its use via rules.

**Comment by kevinz000** [comment]
itt goof makes dumb comments.
