### ISSUE TITLE
Captured non-cultists can slip out of grasp and out of reach past the Reebe barrier

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#31194]
Literally no one could get me after I got past, slipped off my restraints and deconned the front defences before the ARK started summoning Ratvar

**Comment by ShizCalev** [comment]
@Xhuis Opinion? Not sure if this is a map issue or something else you'd like to handle in another way.

**Comment by Xhuis** [comment]
This is intentional, though it may be overly punishing. I'd say it's alright as-is, since non-servants can't do anything without crossing the barrier again.

**Comment by ShizCalev** [comment]
Intentional.
