### ISSUE TITLE
Night vision of all kinds makes dark areas into space

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#31207]
![image](https://user-images.githubusercontent.com/6510293/31057588-b71d2c60-a6aa-11e7-8edd-356a3fa956b7.png)

![image](https://user-images.githubusercontent.com/6510293/31057589-bab7ff1c-a6aa-11e7-8df4-6b1f3eb08d8c.png)

This should only happen for magical mobs or nightmares or whatever

**Comment by BeeSting12** [comment]
I've also seen this occur with thermals

**Comment by ShizCalev** [comment]
Dupe #29521
