### ISSUE TITLE
Dropper transfers weird numbers that aren't integers sometimes.

### ISSUE THREAD

**Issue by Adanps** [tgstation/tgstation#31206]
Round ID 76863

Sometimes when I'm working in virology my droppers will start transferring 0.9 solution instead of 1. I'm not sure what exactly causes this, seems almost random to me. It's really annoying because it messes up mixing and virus feeding, often wasting a lot of time and resources. This round it happened with weakened virus plasma, which I created and then tried to transfer one unit of with a dropper. I made different amounts in a couple beakers, and transferred the amounts in the pictures below.

![garbo](https://user-images.githubusercontent.com/32281090/31057459-abe6eeb4-a6a8-11e7-8fa1-8f107f6e4312.png)

![garbage 2](https://user-images.githubusercontent.com/32281090/31057504-775cf5fc-a6a9-11e7-9247-6c533889a1fc.png)

I changed the beaker the solution was in once and it transferred a single drop like it was meant to. At another point I changed the dropper I used, but still transferred 0.9 solution. I also tried transferring a different solution other than weakened virus plasma, and it was 1 unit like normal. This bug doesn't seem to be only with one unit transfers either, as shown below.

![garbo tres](https://user-images.githubusercontent.com/32281090/31057550-2c5dd7dc-a6aa-11e7-8713-75567f4c32a2.png)

I can't seem to figure out what the cause is anyway, or if it happens with any chemicals. All I know is there's something weird going on here.

**Comment by YPOQ** [comment]
Related #23798

**Comment by bgobandit** [comment]
this is an ANCIENT bug, been around for years

**Comment by Adanps** [comment]
I also had an issue with sucrose agar later on in a different round. It seems very likely this is an issue with the chemicals mixed specifically in virology, though I cannot be certain.

**Comment by bgobandit** [comment]
it isn't a virology bug, I remember it happening as xenobiologist when I played that

**Comment by Mooshimi** [comment]
#61748 same issue
