### ISSUE TITLE
Catpeople organs are broken as fuck

### ISSUE THREAD

**Issue by The-clown-known-as-Pepe** [tgstation/tgstation#31204]
Here's why its shitcode

Cat tail is inside the groin, its not tail attachement/removal.

Removing the tail from inside the groin doesn't update the sprite and the tail is still there.

Catpeople that spawn as head still have those organs inside them (giving them 2.0 modifier on flashbang stuns)

Getting changed into another species via xenobiology toxins and back to human also removes your cat organs. (probably not a bug, but a ""feature"")

**Comment by Cyberboss** [comment]
@KorPhaeron

**Comment by DaxDupont** [comment]
I vaguely remember being able to use tail removal on cattails before.

**Comment by KorPhaeron** [comment]
if("waggingtail_human" in dna.species.mutant_bodyparts)
		dna.species.mutant_bodyparts -= "waggingtail_human"
		dna.species.mutant_bodyparts |= "tail_human"


wtf

**Comment by KorPhaeron** [comment]
Why did we allow people to add actual organs tied to species to what was previously a text string for an icon update in DNA

**Comment by The-clown-known-as-Pepe** [comment]
@KorPhaeron because leoz and hate on catpeople meme

**Comment by KorPhaeron** [comment]
@Cyberboss 

There is the hacky fix, which is to make the proc that removes cat ears from heads remove mutant organs as well. Maybe just set species human again once anturs PR to remove mutant organs is up.

There is the real fix that involves making tails actual organs which is probably more work than I'm willing to put in to clean up someone elses mess in a non feature

And the lazy fix which is to make the ears purely visual again and remove the related surgeries

**Comment by YakumoChen** [comment]
You can actually remove the ears and put them back and the sprites will appear on them again.

I didn't know there was a flashback stun mod tho. I've been playing hard mode as head the whole time? Nice.

**Comment by The-clown-known-as-Pepe** [comment]
@YakumoChen I've been playing hard mode as head the whole time? 

No since you allways powergame and go for bowmans

**Comment by YakumoChen** [comment]
Only when there's no captain, mind you.

**Comment by banthebantz** [comment]
Good, nekos should burn
