### ISSUE TITLE
Drone movement speed is slow now

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#31209]
Either a bug or an unlogged balance change, movement speed of drones is now painfully slow.

**Comment by Slignerd** [comment]
Ignore these, I misclicked.

**Comment by AnturK** [comment]
@Cyberboss you were doing something with move delay recently.

**Comment by Cyberboss** [comment]
#31037 Not a bug necessarily, rather it was a bug to be so much faster before

**Comment by KorPhaeron** [comment]
Not a bug, someone can make their case in a balance PR if they want to
