### ISSUE TITLE
Typo: Holy Book of Atheism -> Athiesm

### ISSUE THREAD

**Issue by nicbn** [tgstation/tgstation#31214]

**Comment by BeeSting12** [comment]
are you saying it looks like atheism already or it needs to look like atheism

**Comment by ShizCalev** [comment]
User error. There is no "Holy Book of Atheism/Athiesm", it was a custom religion.

**Comment by nicbn** [comment]
Nope. It even gives you an atheist hat and haves a big A in the book.

**Comment by ShizCalev** [comment]
![n10mqhu](https://user-images.githubusercontent.com/6209658/31059705-c61084e0-a6d4-11e7-9f25-a829af3358bc.png)

**Comment by ShizCalev** [comment]
There is no Atheism religion. It was a user error. The big A is The God Delision book, and the Atheist's hat is just a state for the nullrod.

**Comment by nicbn** [comment]
Oh.
