### ISSUE TITLE
PDA interface is a blank window

### ISSUE THREAD

**Issue by Angustine** [tgstation/tgstation#31215]
ROUND ID:76870
WHEN I OPEN THE PDA SCREEN IT ONLY APPEARS BLANK WHITE, AND IT HAPPENS REGULARLY.
FIX IT!

**Comment by praisenarsie** [comment]
@Cyberboss @Supermichael777 @TungstenOxide

**Comment by TungstenOxide** [comment]
Shit shit shit. Why couldn't this happen gradually? Okay, uhh. Fuck. Someone undo the patch and I'll rebuild my original **not** fucked up code that I know actually worked.

**Comment by AnonymousNow** [comment]
TO, are you responsible for the PDA interface change? Can you make clickable text/elements a little more distinct from non-clickable text/elements, if possible?

**Comment by TungstenOxide** [comment]
I am responsible for the PDA changes. It's working fine on my end. I'm experimenting rn. I'm probably going to make a new pull request for the build I have on file RIGHT NOW because that one works. I apologize profusely for any inconveniences this has caused.

**Comment by praisenarsie** [comment]
btw it works for me 2, i don't know what's the guy's problem

**Comment by Electronics** [comment]
Possible extension of the problem outlined here: http://www.byond.com/forum/?post=2211145
I used to have this bug but tried downgrading to a bunch of different revisions until I found one that worked for me.

**Comment by ShizCalev** [comment]
Duplicate of #31745
