### ISSUE TITLE
Nightmare's light eater does not correctly deactivate light on cyborgs

### ISSUE THREAD

**Issue by feemjmeem** [tgstation/tgstation#31220]
A nightmare hitting a cyborg with its light eater makes the light 'turn off,' updating sprite and displaying appropriate messages, but does not actually clear the light entity in the room, making a permanent light spot in the room which continues to damage the nightmare.

**Comment by AnonymousNow** [comment]
Known bug, already reported. But good to have multiple instances for logging purposes.
