### ISSUE TITLE
Handcuff UI Bug

### ISSUE THREAD

**Issue by JayIRay** [tgstation/tgstation#31224]
Round ID is 1fd50a

Being Handcuffed caused me to be unable to change clothes, target body parts,  or use any part of the ingame UI besides intent, hands, and health status. The real problem occurs after being unhandcuffed, where all the UI changes stayed. Closing and reopening the client didn't help at all. 
![image](https://user-images.githubusercontent.com/23201761/31060896-abf1e7d2-a6e0-11e7-919d-41bde8decbe0.png)

**Comment by nicbn** [comment]
That's because you pressed F10 or something.

**Comment by nicbn** [comment]
Try pressing all Fs from F5 to F12 and see if it works
It may make your ui disappear, so press it twice

**Comment by JayIRay** [comment]
It was F12, I am an idiot.
