### ISSUE TITLE
Bug with right clicking

### ISSUE THREAD

**Issue by genarall1** [tgstation/tgstation#31223]
Round ID: 76877 
Server revision 1fd50a
Darkgenerallord helped me with this.
So, in the server during this round on bagil, i wasn't able to access right click menu anymore. Nothing was working. Later, after being told by admins to ghost, then put into other mobs, i was able to use right click menu again, however when going back into my own body, i could. Only after completely regenerating my mob is when i was able to use right click menu again.

**Comment by Darkgenerallord** [comment]
To fix this, I attempted a few things.

First up, I tried putting them in a corgi, and then back in their body. It worked while a ghost/corgi. Then I monkeyed them, worked until they were turned back into a human. Finally, I deleted their mob and humanized them again, which worked.

**Comment by Darkgenerallord** [comment]
Apparently stopped working again after maybe five minutes. Unsure why.

**Comment by Darkgenerallord** [comment]
The root cause appears to be Night Vision Goggles. Works while they're off, immediately stops working when they're on.
