### ISSUE TITLE
Weird Graphical Problems.

### ISSUE THREAD

**Issue by Ninjahzzzz** [tgstation/tgstation#31243]
Round ID:  76903, but it has happened consistantly for multiple rounds before this.
After certain points, the entire screen will have it's icons glitch out, organizing them in places they shouldn't be, even sometimes allowing vision through walls. Happens every time the weather in Lavaland changes, though it does occur at moments besides that. It simply is assured to happen when the weather messages are shown. Has happened on multiple computers now, BYOND cache has been cleared to see if that helped, it didn't. Fixes itself upon moving.

http://puu.sh/xOm0X/00cb1f5dc3.jpg (An example.)

**Comment by jughu** [comment]
Clear cache

**Comment by praisenarsie** [comment]
> BYOND cache has been cleared to see if that helped, it didn't. Fixes itself upon moving.

@jughu REEEEEEEEEEEEEEEEEEADDDDDDDDDD

**Comment by jughu** [comment]
I DELETED THE COMMENT OKE

**Comment by nicbn** [comment]
Rare byond gem?

**Comment by ShizCalev** [comment]
Gonna close in a week without another repo
