### ISSUE TITLE
Blob spores taking control of the body you laid an egg in as a changeling headslug will be broken.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#31258]
![](https://i.imgur.com/5IFvlOe.png)

If you lay an egg inside a corpse as a changeling headslug, then the corpse is taken over by a blob spore, you wake up with a blob spore on your head. If the blob zombie is killed, you leave no body behind, only your organs and limbs.

This does not happen to a regular changeling who already has control of a body, died, and started reviving but was taken over by a blob zombie, although reviving themselves will not give them control back.

**Comment by Armhulen** [comment]
Dupe of something!

**Comment by ma44** [comment]
Probably a dupe of #27757 , as #29213 was closed because of that

**Comment by timothymtorres** [comment]
Duplicate of #49543
