### ISSUE TITLE
Alien Alloy Stack Sprite Broken

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#31257]
Above a certain amount, an alien alloy stack is invisible.

**Comment by Jordie0608** [comment]
What certain amount?

**Comment by XDTM** [comment]
Probably the same all other stacks use to change sprite

**Comment by Jordie0608** [comment]
There are three states, I mean which one does it get to, if any
https://github.com/tgstation/tgstation/blob/23d8387f9668e1831b1672e4f05c2a4db1aa872e/code/game/objects/items/stacks/stack.dm#L48-L53
(tbh i checked, there's no `sheet-abductor_2` or `_3`)
