### ISSUE TITLE
Shuttles with docking ports placed over existing docking ports will always send an error.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#31305]
![](https://i.imgur.com/UGTLYjR.png)

This error is spammed every time you bring up the interface for the shuttle. Regardless of whether or not there is another shuttle actually in that location. This is pointless and spammy, and would be much more valuable if it both worked and was displayed next to greyed out buttons on the console so they'd know why they can't go to that location right now.

**Comment by ninjanomnom** [comment]
I'm not sure what the problem here is or where it's happening. I'm guessing this is a mapping issue but I need reproduction steps to be sure.

**Comment by WJohn** [comment]
This is actually more of a mapping error, yes. Turns out all you really need is to have a sufficiently large docking port location to accept whatever shuttle you want along with it.
