### ISSUE TITLE
Shuttle corners rotate the wrong direction when the shuttle rotates.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#31303]
What it says on the tin. Most noticeable with the syndicate infiltrator since now you can set its location and also rotate it, so the smoothed corners all stick out the wrong way.

**Comment by ShizCalev** [comment]
@ninjanomnom Did #31303 cover this as well?

**Comment by ninjanomnom** [comment]
No the recent rotation change was just a bit of code cleanup mostly
