### ISSUE TITLE
admin button for disabling random events is broken.

### ISSUE THREAD

**Issue by SgtxRootbeer** [tgstation/tgstation#31301]
running on a private server, one can press the 'toggle random events on/off' button/verb and nothing will happen. pressing it multiple times results in the following image.
![shap](https://user-images.githubusercontent.com/22112255/31160824-50e55b5e-a888-11e7-8998-4c583f8dd9c9.PNG)

**Comment by bgobandit** [comment]
Cannot reproduce this
