### ISSUE TITLE
New Clock Gets Cucked

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#31318]
If the shuttle docks, it counts as the ark getting destroyed, even if it doesn't activate to let the crew in.

**Comment by chall8908** [comment]
Bit of extra info, Round ID: 76987 (Sybil).

**Comment by Dicks1** [comment]
Ark was still on it's first countdown when the shuttle left the station.

**Comment by Xhuis** [comment]
Ratvar Gets Cucked By Big Brass Clocks
