### ISSUE TITLE
using a Soulstone Shard on a dead lich causes the wizard to become shaded,  and the reviving lich becomes catatonic.

### ISSUE THREAD

**Issue by Somenerdsomewhere** [tgstation/tgstation#31313]
#76982 Sybil 

Wizard had lich, got dropped and killed. Someone used a soulstone shard on him, binding him as a shade and leaving his actual body catatonic.

Just raising it as an issue because I don't think this is an intended feature, the phylactery is meant to house its soul, so there would be no soul to take with the shard, logically.

**Comment by Ratvar** [comment]
I now want to be able to sacrifice/soulstone phylactery

**Comment by praisenarsie** [comment]
lich is so broke

**Comment by ShizCalev** [comment]
Clever.

**Comment by Incoming5643** [comment]
Ow the edge. Clever but yeah a LORE VIOLATION. Will fix.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/523625f485311e697e53acf316dd712b49bcb69f/code/modules/antagonists/wizard/equipment/soulstone.dm#L134#L151
