### ISSUE TITLE
Boxstation Xenobiology missing portable chem dispenser, chem master, dropper

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#31328]
Not a bug; possibly an oversight, possibly intended, but Meta and Delta's xenobiology departments have these features and went through development later on (I think), so I was thinking that Box should be brought up to speed.

The chemical machines are bonuses, for the most part - they both start weak and unupgraded, but they become very useful to a green slime breeder quite quickly, and provide for all of science. The dropper is the more essential bit, being a simple, fairly standard piece of equipment that makes five plasma sheets last 100 doses rather than 20 for a syringe.

Thoughts?

**Comment by YakumoChen** [comment]
Not a bug,box just has less to start with then other maps. Go make one yourself.

**Comment by YakumoChen** [comment]
Meta is a map with extra goodies for everyone compared to box, and delta is meant for highpop (and has more everything). Box is the plan map with bells but no whistles.
