### ISSUE TITLE
Cannot Refill Welding Torch from Beaker of Welding Fuel

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#31339]
You'd think this would make sense, but is there a code reason for it? Having to detect the chemical involved or something?

**Comment by WJohn** [comment]
Similarily should be possible to do so for fire extinguishers. Though I suspect that might actually be quite powerful, so perhaps not.

**Comment by ma44** [comment]
#26608

**Comment by WJohn** [comment]
Okay but the other one got closed fnr since gunhog agreed with it.
