### ISSUE TITLE
Animals can play cards

### ISSUE THREAD

**Issue by Daturix** [tgstation/tgstation#31332]
Sentient animals can pick up cards, only cards no other items. And use those cards. click and drag the cards to yourself as an animal and play cards. Bug or Feature where 5 corgis are playing poker?

**Comment by RandomMarine** [comment]
Also applies to paper bins. And I imagine anything else that's picked up by clickdrag.

**Comment by AnonymousNow** [comment]
Don't even need to bring up the painting for it to be clear it's a feature.

**Comment by Kerbin-Fiber** [comment]
This is all intentional, I've figured out pAI's that are in bots and animals can pick up paperbins and cards a long time ago, this is a feature 10/10

**Comment by Anonmare** [comment]
Feature

**Comment by dragomagol** [comment]
No longer an issue (the cards/bin are dragged to your tile but not picked up)
