### ISSUE TITLE
Can't access new canisters' interface.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#31342]
Round ID: 77018

Couldn't access any newly created canisters' interfaces, no idea why.

**Comment by praisenarsie** [comment]
@Onule how were the canisters made? through cargo?

**Comment by Onule** [comment]
Building from metal.

**Comment by praisenarsie** [comment]
Just tested on Sybil. It works?

**Comment by ShizCalev** [comment]
Gonna close in a week without another repo
