### ISSUE TITLE
Clockwork Golems can slide on glass.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#31343]
Other golems don't step and slide, so...

**Comment by AnonymousNow** [comment]
As much as I like having more golem types, clockwork golems seem a little snowflakey. IIRC, their available slots are different to other golems and their main draw is electricity resistance, which I could've sworn that other golem types had too. Things like that and this PR make me feel as though they were engineered from a different base mob.

**Comment by Xhuis** [comment]
I seem to recall that the base clock golems have more or less the same mechanics as normal ones. War golems are different and serve as a "Human 2.0" type race that does everything better. This can thus be viewed as a balance concern, but it also makes sense for them to have glass immunity.
