### ISSUE TITLE
Wood is invisible.

### ISSUE THREAD

**Issue by SnekMcSnek** [tgstation/tgstation#31361]
Issue reported from Round ID: 77040 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Wood cannot been seen, has no sprite or something.

**Comment by Repukan** [comment]
I'll show you some wood

**Comment by SnekMcSnek** [comment]
I want your wood.

**Comment by ShizCalev** [comment]
Duplicate of #31360
