### ISSUE TITLE
Ocular Wardens and Cogscarabs can detect and kill invisible Revenants

### ISSUE THREAD

**Issue by Neuroplasty** [tgstation/tgstation#31373]
Issue reported from Round ID: 77056 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

RIP My griffghost feast. Ocular wardens will also infinitely attack Revenant remains, which probably isn't useful for clock cult, either.

**Comment by ShizCalev** [comment]
feature

**Comment by ShizCalev** [comment]
@Xhuis

**Comment by kevinz000** [comment]
there's a specific line to reveal revenants in the code.

**Comment by GunHog** [comment]
Intended for ocular wardens: https://github.com/tgstation/tgstation/blob/b10c6c513632acf14fca6c8c7669afa27961200e/code/game/gamemodes/clock_cult/clock_structures/ocular_warden.dm#L64

**Comment by DoctoreMad** [comment]
Aren't revenants supposed to help antagonists on the station?

**Comment by Dorsisdwarf** [comment]
marking as a bug because even if wardens are supposed to reveal revenants, the bug report is that they don't. They and cogscarabs (allegedly) can just kill them while invis

**Comment by Xhuis** [comment]
That's weird. I'll test this and post back shortly.

**Comment by Xhuis** [comment]
After testing, it appears that this happens because the revenant is never actually deleted until its remains are destroyed. I can easily make them untargetable in this state.

**Comment by Anonmare** [comment]
Don't cogscarabs inherit code from drones? I think Drones might also be able to see and target revenants as well if Cogscarabs can

**Comment by Xhuis** [comment]
Scarabs are just clockwork drones, yeah. They shouldn't be able to see revenants if they can't see ghosts, but even if they can I think it inconsequential enough that I'm fine leaving it in.
