### ISSUE TITLE
Map maker autolathe with "hacked" set to 1 does not actually spawn in hacked.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#31384]
Though it will have the variable set to 1 as normal, you won't get the expanded inventory. When hacking and looking into the wires, the blue light will show itself to be on as normal, but the corresponding wire will not be cut. You have to cut the corresponding wire in order to actually get the expanded inventory (blue light remains on before and after cutting).

**Comment by ma44** [comment]
The designs only appear when the adjust_hacked proc is called, and it's only called if the wires are reseted, cut or pulsed. Either check if the hacked var is true in Initialize() or some other fancy way of doing it.
