### ISSUE TITLE
Traitor uplinks are totally fucked.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#31402]
In the traitor panel, it says:

Uplink: .

Literally that. No code or anything in their memory, either. Seems to have like a ~5-10% chance of happening.

EDIT: New bullshit happening!
![](https://i.imgur.com/NXpl240.png)
![](https://i.imgur.com/5A1jLni.png)

Uplink **_DEGREES?_** And what the hell is (pen)??

**Comment by Marflowerose** [comment]
Could this have something to do with F.R.A.M.E PDA Cartridge or does this happen to legit round start traitors?

**Comment by WJohn** [comment]
I'm not certain exactly how it happens. I've seen traitors with this issue pretty much at round start, though.

**Comment by vuonojenmustaturska** [comment]
02:07 -!- Daturix [cgiirc@Rizon-24C7AE3C.hsd1.or.comcast.net] has joined #coderbus
02:08 < Daturix> which one of you fucks made it so uplink pens priortize the pocket protector one?

**Comment by vuonojenmustaturska** [comment]
Fixing

**Comment by WJohn** [comment]
This is still happening. On 11/Oct/2017, ~4 days after that PR was merged.
![](https://i.imgur.com/Uu3K1A7.png)

**Comment by WJohn** [comment]
Oh boy! These just got WORSE!

**Comment by PKPenguin321** [comment]
Degrees is how far you have to rotate the pen lid in degrees to unlock it, which is a feature iirc

**Comment by ShizCalev** [comment]
what pkp said.

(pen) is the pen in their inventory.

**Comment by vuonojenmustaturska** [comment]
@WJohn were these mime/clown traitors, do you remember?

**Comment by ShizCalev** [comment]
Gonna close in a week without another repo.
