### ISSUE TITLE
Teleports work inside the Syndicate Ops shuttle and drop pod while on the Centcom z-level.

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#31429]
Title,
Acquire hand-tele, go back, warp out of your base from the edges of the shuttle and profit from Centcom loot, leave "surprise" on escape shuttle, etc.
The rest of the Syndicate base also has the no_teleport flag, so I see no reason why the shuttles are exempt other than oversight.

**Comment by Metroidlover** [comment]
#37111 Should have fixed this

**Comment by Dennok** [comment]
Maby close this?

**Comment by GravitronBlue** [comment]
#37120 only addresses the bluespace launchpad, there are still several other methods including the previously mentioned hand_teleporter that still works, although attaining it and going all the way back takes considerable effort.

**Comment by GravitronBlue** [comment]
#46802

**Comment by Detective-Google** [comment]
![image](https://user-images.githubusercontent.com/48196179/65845502-23b3c580-e300-11e9-9fdb-aaa9424d31ef.png)
still an issue, though you'd have to be real lucky.

**Comment by GravitronBlue** [comment]
#44837
Use bluespace crystals to craft a usable tele-prod and hit yourself with it, saves on telecrystal costs should RNG not get you out to space the first time.

**Comment by GravitronBlue** [comment]
#66149 overhaul should take care of this with a wider 'catch' region surrounding the shuttles and pod areas, if not my suggestion would be to point out space tiles that can still be reached over on that PR.

Should've perhaps consolidated this issue report with #44837 as well.
