### ISSUE TITLE
tracking someone in a camera dead zone as ai crashes game

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#31438]
12:12:09: Reply PM from-Gameguru09/(B.Y.O.N.D.): Tracking someone who is in a camera(?|F) dead zone crashes the game

**Comment by WJohn** [comment]
This is gonna need some confirmation, AI players should be screaming and hollering over this so I expect we'll find out quickly.

**Comment by ShizCalev** [comment]
Not able to reproduce.

**Comment by BeeSting12** [comment]
Might be just that guy

**Comment by ShizCalev** [comment]
Unable to reproduce, likely just a client issue. Closing since there's been no other reports.
