### ISSUE TITLE
Escape shuttles gib at odd ranges

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#31436]
ID: 77136
Server revision compiled on: 2017-10-07   e4163a

Escape shuttle rams at people (gibbing them) who are not in vicinity of the actual blue arrival bubbles. Tested at range of 1 and 2 empty tiles between the bubbles. On "Oh Hi Daniel" there was two empty spaces in between, this is not exclusive to that ship.

**Comment by WJohn** [comment]
Tested with metastation shuttle on metastation with corpses placed at the far corners. Corpses were gibbed in the corners that technically didn't have any walls to smoosh them with.

![](https://i.imgur.com/K5DY21j.png)

Presumably a shuttle like ye-olde asteroid and its X shape or some other concave design would also do this.

**Comment by Marflowerose** [comment]
![ship](https://user-images.githubusercontent.com/6935094/31316411-5f1d1314-ac35-11e7-9f2b-3ea633ec3b89.jpg)
Elaboration on what can happen on Oh Hi Daniel ship, this happens on the same ship side when it returns to Centcomm, there seems to be 3 deadly blocks on the side with the computers.
