### ISSUE TITLE
Mousetraps in your bag can still be triggered while restrained.

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#31431]
title,
Create lethal mousetrap activated grenade, stick in box, stick box in bag, get kidnapped by cult, drag box onto yourself to deny conversion and score valids.
Blood and clock cult rely on abilities that mute and restrain their target which prevents voice activated grenades from working. Mousetraps aren't affected by this limitation and should be looked at in terms of balance.
Mousetraps also aren't triggered if you open containers containing them while unconscious, so this doesn't work against ayys and might be a separate side issue.

**Comment by Ryll-Ryll** [comment]
Unable to reproduce, restraints have at some point totally stopped the ability to open up or interact with storage items
