### ISSUE TITLE
9mm ammo can spawn in surplus crates

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#31433]
probably my fault

**Comment by msgerbs** [comment]
Why would it not?

**Comment by BeeSting12** [comment]
@msgerbs traitors can't get pistols that use 9mm. stetchkins use 10mm, the stetchkin APS takes 9mm but thats not in the uplink and i dont think its in the crate

**Comment by msgerbs** [comment]
I thought there was a 9mm SMG? Maybe that's gangs. I swear I've seen a 9mm SMG though.

**Comment by BeeSting12** [comment]
the uzi probably does take 9mm but this is a 9mm pistol mag with 15 shots meaning stetchkin aps

**Comment by WJohn** [comment]
Should be 10mm, not 9mm, yeah. Traitors have no use for it.

**Comment by jughu** [comment]
The 9mm aps stetchkin is a space ruin reward
