### ISSUE TITLE
Neutered viruses still show up as bad

### ISSUE THREAD

**Issue by Doppeltongue** [tgstation/tgstation#31445]
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

Round ID: 77155

Virus had the following neutered symptoms: 

- Eternal Youth
- Itching
- Viral Evolutionary Acceleration
- Fever

And the following good (and unneutered) symptoms:
-Flesh Mending
-Temperature Adaptation

Cure was Spaceacillin and a medibot ended up curing the entirely good virus.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by MrROBUST** [comment]
Do not stats of this symptoms make the virus invisible? Why medbot tried to treat you?
