### ISSUE TITLE
Making lizard wine does not reset the sprite whatever contains the ethanol

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#31458]
1. Make lizard wine with large beaker with ethanol, using the crafting menu.
2. Observe how beaker is empty when examined but the sprite shows it as full.

**Comment by PKPenguin321** [comment]
Not sure I understand the bug report. "ethanol using menu"?

**Comment by DaxDupont** [comment]
Engrish slightly fixed

**Comment by Cyberboss** [comment]
Duplicate of #33619
