### ISSUE TITLE
Non-abductor abductors can't talk.

### ISSUE THREAD

**Issue by ishitbyabullet** [tgstation/tgstation#31453]
Issue reported from Round ID: 77166 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

[Directions]: 77166. Make yourself an abductor through xenobiology or something then try to talk. I think abductor antags can talk, though. I miss the good ol' days of being able to shitpost while no one else can hear you, man. This would really suck if you heard real abductors yet you couldn't talk to them or call for help because your fucking telepathy won't work.

[For Admins]: I doubt the admins just var-edit me while I'm not looking so I can't talk.

**Comment by WJohn** [comment]
Abductors are only able to speak in their hivemind to their linked partner, a scientist and his agent. They can't even talk to OTHER scientist/agent pairs in shuttles right next to their own. Frankly a hivemind chat would make a ton more sense.

**Comment by praisenarsie** [comment]
i remember someone made abductor mutation pills and everyone was in the same hivemind

**Comment by ishitbyabullet** [comment]
@WJohn  Agents and scientists can't talk to other agents and scientists, but if you were a xenobio ayy and got lucky then you could be in a specific group's hivemind chat. This allowed the glory known as 3 man abductor teams.

I can't even talk now, though. That was the best part about abductors imo. They have the equivalent of a changeling chat where they can't escape from it without emoting or using pdas/paper/tongue surgery.

**Comment by XDTM** [comment]
The intended functionality is private channels for real abductors and one shared channel for everyone else with an abductor tongue

**Comment by WJohn** [comment]
I don't recall being able to talk to other ayys when I myself was spawned in side by side with multiple abductor spawns, but that was a long time ago so my memory may be hazy.

**Comment by optimumtact** [comment]
this is not a bug, pls take to forum or go shitpost in irc until someone changes it
