### ISSUE TITLE
Neutered Symptoms Switching When Creating New Culture

### ISSUE THREAD

**Issue by mopacpl** [tgstation/tgstation#31455]
Issue reported from Round ID: 77167 (Sybil)

After neutering a specific symptom amongst other un-neutered symptoms - the neutered symptom will switch to a different one upon creating a virus culture bottle. I've found it's often the symptom at the top of the list. For example:

*Viral Evolutionary Acceleration
Eternal Youth
Itching (neutered)*

became

*Viral Evolutionary Acceleration (Neutered)
Eternal Youth
Itching*

After creating a culture bottle of the former

I'm not entirely sure that this is a bug, but it seems like it to me. 

[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by XDTM** [comment]
already fixed, the server just needs to update

**Comment by ShizCalev** [comment]
Fixed by #31435
