### ISSUE TITLE
Aux base management console sprite does not change when you break it

### ISSUE THREAD

**Issue by imtakingabreakdontatme** [tgstation/tgstation#31471]
That's an auxillary base management console.

Allows a deployable expedition base to be dropped from the station to a designated mining location. It can also interface with the mining shuttle at the landing site if a mobile beacon is also deployed.

It looks broken and non functional.

**Comment by DaxDupont** [comment]
Yeah this needs a new sprite since I don't think error will do.
![fdfha55 1](https://user-images.githubusercontent.com/17237624/31441477-8f3debc6-ae93-11e7-91f5-e6f16c4ded0e.png)

**Comment by Sealed101** [comment]
it could easily use the crack overlays like the newscaster does; right now it just shows its `off` state when damaged enough

https://github.com/tgstation/tgstation/blob/9bb105efa8f7c51b814653fa0802bf8119c5b628/code/game/machinery/newscaster/newscaster_machine.dm#L94-L119
