### ISSUE TITLE
changing someones species to nightmare doesnt give them the shadowwalk spell

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#31476]
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by AnonymousNow** [comment]
Likely a result of the recent jiggery with organs, I'd imagine.

**Comment by Hathkar** [comment]
Can confirm, did an antag trade a few days ago to be a nightmare, didn't get shadowwalk.

**Comment by Cyberboss** [comment]
Unable to repro can one of you try again and detail?

**Comment by BeeSting12** [comment]
It's been fixed since then, I believe. If not I'll reopen.

**Comment by ShizCalev** [comment]
Fixed apparently.
