### ISSUE TITLE
The white ship on meta is very bugged.

### ISSUE THREAD

**Issue by Metroidlover** [tgstation/tgstation#31486]
Issue reported from Round ID: 77188 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

The white ship on meta is bugging out, strips of the sides just get left behind at times, the shuttle windows and doors might just disappear, Or the whole ship will bug out and gib everyone inside it.

**Comment by ShizCalev** [comment]
@ninjanomnom

**Comment by ShizCalev** [comment]
also see #30981

**Comment by ninjanomnom** [comment]
#30981 is unrelated

**Comment by ninjanomnom** [comment]
I'm not able to reproduce this.

**Comment by Cruix** [comment]
This can be reproduced by flying the shuttle somewhere, using the shuttle navigation computer while the ship is in transit to set a new location such that the mobile docking port is in the area the shuttle will land but offset slightly, then flying to that custom location. This will cause the custom docking port to be transported to transit space and lots of nasty things happen.

**Comment by ninjanomnom** [comment]
@Cruix open a new issue then indicating that it's a problem with the custom docker and how to replicate it. I'll handle it within the next few days.

**Comment by Cruix** [comment]
There are already two issues about it and it has already been handled.
