### ISSUE TITLE
Xenomorph Text Log - You feel confused and nauseous...

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#31489]
Issue reported from Round ID: 77191 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Text log constantly filled with the message: "You feel confused and nauseous..." when playing as a xenomorph. This has happened as a larvae and hunter, across several different xeno mobs.

**Comment by ShizCalev** [comment]
Liver failure.... hm.

**Comment by YPOQ** [comment]
#30572 changed the liver check

**Comment by ShizCalev** [comment]
@XDTM reeeeeeee
