### ISSUE TITLE
Xenomorph Disarms not stunning

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#31488]
Issue reported from Round ID: 77191 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

As per the title, xenomorph stuns/knockdowns were not working this round. I personally disarmed someone two or three times as a sentinel and they were not stunned at all. I also witnessed a xeno queen try and disarm someone, with no effect. They weren't on harm intent, since they weren't doing any damage.

**Comment by Armhulen** [comment]
which class were you

**Comment by Hathkar** [comment]
I was a sentinel, but I also saw the queen unable to stun as well.

**Comment by ShizCalev** [comment]
@Cyberboss 
Caused by #31386
