### ISSUE TITLE
Custom Shuttle Placement with White Ship Gone Wrong (Gone Sexual!)

### ISSUE THREAD

**Issue by Neuroplasty** [tgstation/tgstation#31485]
Issue reported from Round ID: 77188 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Upon rotating the white ship with the custom console and sticking us backwards in the aux docks, the ship was spun 180 degrees and after that only the outermost 1 wide layer of walls and airlocks on the docking side of the ship would move, and the rest of the ship was left marooned.

**Comment by ShizCalev** [comment]
@ninjanomnom

**Comment by ninjanomnom** [comment]
duplicate of #31486 and also I can't replicate it

**Comment by AnturK** [comment]
Duplicate of #31486
