### ISSUE TITLE
Ore redemption machine ate my ID and ores, and then became locked to any further interaction.

### ISSUE THREAD

**Issue by absalammi** [tgstation/tgstation#3150]
Had a nasty lag spike when ejecting my ID, UI disappeared, and then the ore machine became completely inanimate. Nothing happened when clicked on, right clicked on, I moved away, checked the UI wasn't minimized, had other people with access try and do something with it, tried dumping more ores in the hopes of unfreezing it much later, nada.  

Relevant Admin PM from-Jordie0608: I managed to fix it by changing a var that broke, unlikely to have been a UI problem. Plese report this on github as it's liable to happen again.

**Comment by Iamgoofball** [comment]
highly doubt this deserves higgsbugson

**Comment by optimumtact** [comment]
old higgs bugson
