### ISSUE TITLE
sentience potion spamming is really annoying

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#31523]
It takes my screen focus away and a persistent xenobiologist or whatever will do it every five seconds, which is long before the "mob didn't seem interested" message appears saying nobody wanted to play. As a ghost it is insanely obnoxious and if you press 'never' then you're barred from all xenobio roles for the rest of the round (which might not be wanted if the xenobio decides to sentience something more to your liking)

**Comment by WJohn** [comment]
Basically the same deal as #15583 with our pop up system being really loud, intrusive, obnoxious, and inconsistent.

**Comment by BeeSting12** [comment]
It needs to be changed to an inchat thing similar to spiders. Might be harder to notice but I'd rather have xenobio not get a slime than have to click out of one of these every five seconds while answering tickets.

**Comment by AnturK** [comment]
Not a bug, suggestions go on the forums
