### ISSUE TITLE
Multiple antags per round

### ISSUE THREAD

**Issue by JJRcop** [tgstation/tgstation#31531]
This has always been one of the goals of [Datum Antags](https://github.com/tgstation/tgstation/projects/4), where a potential mix of antags are spawned instead of just one, so that you could possibly see nuclear operatives during a revolution, or the threat of changelings while Ratvar's servants are among you, maybe with traitor on top for good measure, et cetera. Maybe it's just blood cult and nothing more, but nobody really knows.

The [design document](https://tgstation13.org/phpBB/viewtopic.php?f=10&t=4013) says that each gamemode type has the possibility of spawning other antags, however, we may want to consider making "gamemodes" a config file, so that each server can tune the numbers however they want.

**Comment by AnturK** [comment]
Suggestions go on the forums.

**Comment by JJRcop** [comment]
This wasn't a suggestion, sorry for the bad wording, meant to be used to track the goal of multiple antags per round.
