### ISSUE TITLE
The automatic emergency shuttle call doesn't work.

### ISSUE THREAD

**Issue by GuyonBroadway** [tgstation/tgstation#31535]
It does not trigger a shuttle call when it triggers.

It sometimes forces a standard shuttle call to be unrecallable with no warning message and even disalows the admin verb from recalling.

See also https://github.com/HippieStation/HippieStation/issues/3880

**Comment by ShizCalev** [comment]
@Cyberboss

**Comment by GuyonBroadway** [comment]
You may have cucked me of my code but you also cucked me of my mistakes too!

Is this not what you wanted?

**Comment by JamieH** [comment]
```[15:12:34] Runtime in shuttle.dm, line 168: Division by zero
proc name: CheckAutoEvac (/datum/controller/subsystem/shuttle/proc/CheckAutoEvac)
src: Shuttle (/datum/controller/subsystem/shuttle)
call stack:
Shuttle (/datum/controller/subsystem/shuttle): CheckAutoEvac()
Shuttle (/datum/controller/subsystem/shuttle): fire(0)
Shuttle (/datum/controller/subsystem/shuttle): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)```

**Comment by Cyberboss** [comment]
The disallowing admin recall thing must be a side effect of `emergencyNoRecall` which is not a part of the issue

**Comment by Cyberboss** [comment]
@JamieH what's your config value set to for reference?

**Comment by JamieH** [comment]
@Cyberboss EMERGENCY_SHUTTLE_AUTOCALL_THRESHOLD 0.2
