### ISSUE TITLE
Autolathe broken, can't put shit into it.

### ISSUE THREAD

**Issue by JamieH** [tgstation/tgstation#31538]
It's not broken on /tg/ yet, but you broke it for us...

I tested on: https://github.com/tgstation/tgstation/commit/a15d879f48c567c5eac0c2629371df512fa2f067 and it worked but @Guyonbroadway tested on https://github.com/tgstation/tgstation/commit/0cd3f2ba4e2846f667f84675316cee40dad17897 and it was broken.

**Comment by Cyberboss** [comment]
@kevinz000

**Comment by YPOQ** [comment]
Fixed by #31555
