### ISSUE TITLE
Virology unable to make vaccine bottles but instead makes (spammable) empty bottles when tried 2: Electric Boogaloo

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#31534]
#30174 is back.
Tried making a vaccine for pierre's throat. 
#30357 did not fix the issue or is undone by other changes.
@XDTM 

Server revision compiled on: 2017-10-09
9b6b75

**Comment by Ausops** [comment]
https://pastebin.com/Jxf7nwUD

**Comment by AnturK** [comment]
Type mismatch, basic resistances use types everywhere else assumes text

**Comment by XDTM** [comment]
That fix only fixed advance diseases vaccines, the basic diseases are still unvaccinable due to what antur said. I'll have to work on the pandemic code a bit when i have time.

**Comment by DaxDupont** [comment]
I'd argue this is rather high priority.

**Comment by delaron** [comment]
This is still an issue. Had a course of Fugal TB rip through station and nothing but empty vaccine bottles.
