### ISSUE TITLE
Crates layered under conveyor belts

### ISSUE THREAD

**Issue by Mark9013100** [tgstation/tgstation#31566]
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

Server revision compiled on: 2017-10-11

The following pull requests are currently test merged:
#31166: 'Fixes material container flags precedence' by Cyberboss at commit 524c31

Based off origin/master commit: 9b6b75

see title, crates were layered under cargo's conveyor belt on boxstation

**Comment by ShizCalev** [comment]
Caused by #31493
