### ISSUE TITLE
Space exploration is broken

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#31563]
As of right now if you decide you want to explore space on pretty much any station, you can randomly come across what I /think/ is the shuttle transit z-level, everything will be blue, there'll be an orange border around the edges of the z-level and you can even run into the moving space tiles if you look hard enough.

Related image: https://gyazo.com/1df8775f32851f01791959a790d4753d

**Comment by ShizCalev** [comment]
Iirc someone mentioned this being related to Reebe being added or something like that. Not sure if that issue was fixed, or if this is a separate one.

**Comment by Jarektheraptor** [comment]
That brings up more questions then, like if you were to float to that particular Z-level and stay on it, would you technically be counted as an escapee? Could you actually find centcomm?

**Comment by praisenarsie** [comment]
@Jarektheraptor nah pretty sure you have to be on shuttle/pods/white ship to escabe
