### ISSUE TITLE
Cryo tubes broke and stopped cooling down the subject inside.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#31564]
Somehow cryo tubes broke and stopped cooling down the subject inside and doesn't make the person pass out.

Air tanks were still getting cooled, just not the people in the tube.

Only thing out of the ordinary was robustin spamming carpet with the smoke machine everywhere but I don't think that should have an effect on it unless it messes with the pipes.

Roundid https://atlantaned.space/newSS13tools/round.php?round=77290
Server revision compiled on: 2017-10-11

The following pull requests are currently test merged:
#31166: 'Fixes material container flags precedence' by Cyberboss at commit 524c31

Based off origin/master commit: 9b6b75

**Comment by WJohn** [comment]
Saw this in action, not sure what caused it.

**Comment by DaxDupont** [comment]
happened again 77326

**Comment by duncathan** [comment]
fixed by #31605
