### ISSUE TITLE
Smoke Machine does not produce an admin message upon activation

### ISSUE THREAD

**Issue by sawrge** [tgstation/tgstation#31578]
Smoke grenades and smoke reactions both do. It makes it much much easier to deal with misuse of this feature as it is very easy to abuse, and the smoke machine literally makes it shit-your-diaper baby tier to mess around with smoke.

For ease of use and consistency's sake please add an admin message similar to other smoke reactions when the machine is activated. Thankyou.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/a5aea354e90b235a174e8912a4fc11783acc8224/code/modules/reagents/chemistry/machinery/smoke_machine.dm#L109

There should be one... hm.

**Comment by Cyberboss** [comment]
They mean message_admins
