### ISSUE TITLE
Die Of Fate gives nothing when rolling 20

### ISSUE THREAD

**Issue by MrAlphonzo** [tgstation/tgstation#31589]
Nothing happens.
You just roll 20.
And that is it.
No wizard.

**Comment by AnturK** [comment]
Round ID ? Also you sure it wasn't used already.

**Comment by KorPhaeron** [comment]
Used? Did you try to cheat and rig it?

**Comment by praisenarsie** [comment]
sTOP COUNTING YOUR CARDS LIKE YOU'RE IN VEGAS

**Comment by KorPhaeron** [comment]
I just tested this and it works fine
