### ISSUE TITLE
Radiation based power gen seems to be acting weird.

### ISSUE THREAD

**Issue by Darkgenerallord** [tgstation/tgstation#31591]
According to multiple reports, the SM either straight up doesn't produce power, or produces significantly less than it should (180 KW on air pump filled plasma tanks.)

Singulo might also be similarly fucked, but I've only gotten one report about this and haven't had a chance to confirm it.

**Comment by ShizCalev** [comment]
Tested, seeing the same issue. No power is going through the wires connected to rad collectors w/ an active SM.

**Comment by BeeSting12** [comment]
Is this related to the testmerge?

also #31521

**Comment by ShizCalev** [comment]
Don't recall anything being testmerged when I last tested it.

**Comment by praisenarsie** [comment]
@ninjanomnom
