### ISSUE TITLE
Gas filters aren't working

### ISSUE THREAD

**Issue by Grazyn** [tgstation/tgstation#31606]
If you click a filter you can't change the gas settings, it's stuck on "nothing".

Server revision compiled on: 2017-10-11

The following pull requests are currently test merged:
#30599: 'Moves projectile processing to a subsystem' by kevinz000 at commit 2e50b3

Based off origin/master commit: a15d87

**Comment by praisenarsie** [comment]
@duncathan 

Were these map-loaded gas filters or filters created from a RPD or pipe dispenser?

**Comment by Grazyn** [comment]
Both. Those in atmos switched to nothing when clicked and the one I dispensed from the machine was stuck too.

**Comment by Grazyn** [comment]
Didn't notice this was already fixed #31596

I guess the fix isn't merged yet

**Comment by AnturK** [comment]
Yes, this is already fixed.
