### ISSUE TITLE
A bunch of rooms roundstart are freezing

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#31629]
![image](https://user-images.githubusercontent.com/12382984/31514126-886cebda-af88-11e7-95bc-1cb3ea6bf4f9.png)

A few minutes into the round and it should not be this cold. No it's not breaches

**Comment by Anonmare** [comment]
The problem appears to be the holding tanks. Dunno if it's just box but they're way into the minuses

**Comment by YPOQ** [comment]
#31542 made space cold but windows don't block cold so now everything that has a window to space is cold?

**Comment by optimumtact** [comment]
The pipes are cold
