### ISSUE TITLE
No round end antag report

### ISSUE THREAD

**Issue by Knoxon** [tgstation/tgstation#3162]
b1e2493b517ffd329646ad00a94f5f7bd5fa2fbe
Basil
Boxstation
Was a very obvious cult round, with cult robes and runes and everything. At round end there was no standard antagonist report. Also observed at the end of a changeling round.

**Comment by JJRcop** [comment]
does this still apply?

**Comment by phil235** [comment]
I've never witnessed this recently and the issue is more than two years old, so I'm going to assume it's fixed.
