### ISSUE TITLE
Job preferences are buggy

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#31626]
Mrs_Sybil: RELAY: cleverboy12 | Ticket #1: My occupation preferences are Shaft Miner high and only that and i put the return to lobby if preferences are unavailable but i got Atmospheric Technician - All admins stealthed[nothing], AFK[nothing], or lacks +BAN[Incoming]! Total: 1 

I've gotten several similar adminhelps as well

**Comment by YPOQ** [comment]
Do you have a round number? If they get selected as an antagonist they will be forced into a random job even if return to lobby is set.

**Comment by Incoming5643** [comment]
In that specific instance it was because he had been selected to be a traitor yes.

Side effect of antag selection coming first
