### ISSUE TITLE
Rev ending listed revhead as alive, but the revhead had died to trigger round end

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#31659]
This is Gigglesworth!
She is wearing  a clown suit.
She is  handcuffed!
She has severe bruising!
She is bleeding!
She is barely conscious.
She has a blank, absent-minded stare and appears completely unresponsive to anything. She may snap out of it soon.

Round ID 77363

The heads of staff managed to stop the revolution!

The head revolutionaries were:
Hunterh98 was Gigglesworth the Clown and survived

The head of security had just beaten him to death

Maybe it counts people in soft crit as dead in the round check?

**Comment by praisenarsie** [comment]
this is 100% a dupe issue or the previous issue was 'fixed' but not actually fixed. let me find it

**Comment by AnturK** [comment]
>She has a blank, absent-minded stare and appears completely unresponsive to anything. She may snap out of it soon.

It's just DC win, so this is technically correct.

**Comment by praisenarsie** [comment]
@AnturK can you investigate #30539 then?

**Comment by AnturK** [comment]
Probably the same thing as soon as first head disconnects it's game over since it doesn't try to do anything in that case.

**Comment by KorPhaeron** [comment]
Isnt there supposed to be a timer when they DC to prevent games ending instantly on connection loss or restart?

**Comment by AnturK** [comment]
Only for being AFK, standard disconnected just fails the thing instantly.
