### ISSUE TITLE
Warm donk pockets can't be grinded in a grinder

### ISSUE THREAD

**Issue by CitrusGender** [tgstation/tgstation#31650]
No idea why. I tried it twice on sybil. This makes getting omnizine basically impossible, by the way.

Round ID: 77351

The following pull requests are currently test merged:
#31633: 'Vacuum Heat Capacity Revert' by AnturK at commit 0e619a

Video of it happening
https://feen.us/2x7pmefe.mp4

**Comment by CitrusGender** [comment]
FIX IT

**Comment by TheDreamweaver** [comment]
This isn't a fix, obviously, but in case you were not aware botany has a pretty good and easy source of ominizine through Ambrosia deus.

**Comment by CitrusGender** [comment]
![discord_2017-10-13_18-29-29](https://user-images.githubusercontent.com/31262308/31568838-9e5cd92a-b044-11e7-9f45-1f054df88401.png)
https://github.com/tgstation/tgstation/blob/3d39ad3501316a018ac686b2af38ba43598a3353/code/modules/reagents/chemistry/machinery/reagentgrinder.dm#L20

add donkpockettype = list("reagent" = amount as number)
FREE POINTS FOR ANYONE WHO CAN FIX THIS

**Comment by Armhulen** [comment]
ok one sec

**Comment by ExcessiveUseOfCobblestone** [comment]
@optimumtact this is still an issue
