### ISSUE TITLE
Slapping works despite being buckled

### ISSUE THREAD

**Issue by epochayur** [tgstation/tgstation#31658]
Round ID: 77355

[Adds Slappers #31406](https://github.com/tgstation/tgstation/pull/31406)

![untitled](https://user-images.githubusercontent.com/32695675/31528408-f43d6e9e-af87-11e7-9093-8e227ef5fc1b.png)

Seems like you can use "*slap" regardless of whether or not you're buckled in, despite what the text says.

**Comment by Cyberboss** [comment]
@Robustin @Armhulen ?

**Comment by WJohn** [comment]
I thought this was intentional?
