### ISSUE TITLE
Xeno disarm is broken

### ISSUE THREAD

**Issue by Qbopper** [tgstation/tgstation#31675]
I don't have many details because this is hearsay and the user in question refused to make a report (because ~apparently it could have been an intentional nerf so therefore don't make a report???~ "lol i wanted the bug to stay in because xenos are unfun with disarm") but 

apparently disarming as a xeno doesn't work at all

i'll try to replicate in the thunderdome soon

**Comment by Cyberboss** [comment]
Cause by #31386 probably

**Comment by praisenarsie** [comment]
dupe of some issue iknowit

**Comment by ShizCalev** [comment]
#31491 should've fixed this, hm..

Also @praisenarsie #31488 was closed.

**Comment by Cyberboss** [comment]
@Thunder12345 says it was fixed, servers probably weren't up to date

**Comment by Cyberboss** [comment]
I blame @Qbopper for not p o s t i n g   t h e   r o u n d i d

**Comment by Qbopper** [comment]
fuck i forgot

**Comment by Qbopper** [comment]
seems to work now, don't know if a fix got merged or what but disarms knock people over/make them drop what they're holding
