### ISSUE TITLE
Constructed freezers have a -10 pixel x/y offset and don't work.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#31672]
![](https://i.imgur.com/lVxkXe7.png)

This only happens when you actually construct the freezer (deconning it and putting it back together does this too). Does not happen to spawned freezers via admin. Rotating the freezer by screwdrivering the panel, then wrenching will keep the offset where it is.

**Also, the freezer won't work.** Bigger bug there.

**Comment by DaxDupont** [comment]
Someone said gas filters didn't work either. Someone said that it had something to do with multilayer pipes. @kevinz000

**Comment by WJohn** [comment]
Oh hey, didn't notice the pipe thing from kevinz was testmerged, my bad.
