### ISSUE TITLE
Grinders are wonky

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#31697]
Stuff doesn't get ground up and no reagents are extracted. Sometimes it works though. It's weird.

**Comment by praisenarsie** [comment]
REEEEEEagent code

@Cyberboss you're smart, can you fix this

**Comment by Doppeltongue** [comment]
It seems to only apply to foodstuffs and not to materials like plasma or uranium.

**Comment by newfren** [comment]
Wheat successfully grinds, cocoa beans do not.

**Comment by Bawhoppen** [comment]
Like donuts ground for me (albeit not the whole thing at once but maybe that's intended), but lollipops did not. Then I tried some fruit and that didn't work either.

**Comment by DaxDupont** [comment]
Related to https://github.com/tgstation/tgstation/issues/31650?

**Comment by Bawhoppen** [comment]
Appears to be so. Some things need to still be added to that grinder list I didn't know existed.

**Comment by ShizCalev** [comment]
> @Teepeepee 
> 
> All-in-one Grinder is not working for some stuff, tried the one in botany, in the bar and in chemistry. When grinding nutriment filled wheat it gives flour as intended, when I put pottasium into the wheat and grind it it does the grinding animation but it doesn't consume the wheat nor give pottasium

> @AnonymousNow 
> 
> Tried this with Space Twinkies and nothing happened. Xenobiology's plasma grinding escaped the worst of it even as other departments lamented their grinders, but that might have changed.
