### ISSUE TITLE
I CANT STOP WAGGING MY TAIL

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#31702]
1. *wag as catperson
2. *wag to stop
3. Wait I AM STILL WAGGING MY TAIL!!

**Comment by Hatfish** [comment]
@kevinz000 This seems to be an issue with lizards now (or something similar).  Occuring on Bagil.  
Round ID:  78981
Based off of master commit 1daf43
Testmerged PRs:
#31026 
#32835

**Comment by Anonmare** [comment]
High priority issue

**Comment by CosmicScientist** [comment]
We should just make it so that even in death, you still wag.
