### ISSUE TITLE
Genetic disability that makes people fall on the floor can't get fixed

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#31716]
Whatever genetic disability that gives you the falling on the floor by either radiation or mutagen causes you to stay laying on the floor, unable to move.

Mutadone and clean SEs do not fix it.

Saw it in two separate rounds. One because of SM explosion rads and one because some idiot ate shrooms with mutagen in them.

You feel weak.
You feel weak.
You feel weak.
You feel weak.

**Comment by ShizCalev** [comment]
That's not a disability, that message means that you have a ton of rads in you and you need to be treated with antitoxin. Giving them SEs increases the amount of radiation in them. Likewise, injesting mutagen irradiates the mob over time (radium) until it wears out in their system.

The knockdown time (which is reset after each message) is 20 seconds.

https://github.com/tgstation/tgstation/blob/d511f3bf0437efe09228800a4dd320e1daf93701/code/modules/mob/living/carbon/human/species.dm#L980

**Comment by DaxDupont** [comment]
I had a case where a person no longer had any toxins/mutagen in him and stayed in that state for over half an hour.
I doubt that's intended?

I spent like a fuckton of time trying to fix him, gave him potassium iondine, mutadone and charcoal. He was not getting toxins damage.
Something is broken, disorder or not.
