### ISSUE TITLE
Atmospheric Pressure and Tempreture Breaking after a bomb

### ISSUE THREAD

**Issue by TheAutism** [tgstation/tgstation#31715]
Issue reported from Round ID: 77430 (Sybil)

After the brig was bombed i went to go and fix the breaches, but found that space wind was pushing me around in odd ways (pushing me away from walls and out of corners) after i took a pressure reading i found the area had a pressure of around -1000kpa and a temperature of -8000C in a few places and -1000C in most other places. I am unsure if the bomb caused this or something else. Another note of possible interest is a few minutes after the bomb went off the area was fairly hot ( enough to cause minor burns) but then cooled to the ridiculous temperatures i was seeing.

**Comment by duncathan** [comment]
Uh oh
