### ISSUE TITLE
Panic bunker is hidden from being VV'd and cannot be disabled

### ISSUE THREAD

**Issue by LetterJay** [tgstation/tgstation#31712]
This is using a very recent build of /tg/, Post refactor of the config resulted in the panic bunker being locked from change via the Panic Bunker verb. I've merged #31252 but it still yields the same result of being hidden from VV as well as not being able to be changed via the verb in the admin tab.

**Comment by Cyberboss** [comment]
https://github.com/tgstation/tgstation/blob/4178c209f139ad9d78eda609d539f2b24af94565/code/modules/admin/verbs/panicbunker.dm#L1-L9

Provided you have sql enabled, toggle panic bunker should never cease to function

**Comment by Cyberboss** [comment]
Care to provide any details of why the toggle wasn't working?

**Comment by LetterJay** [comment]
There is no logged error message. Trying to toggle it only provides the feed back of

``ADMIN LOG: Admin/(Admin) has toggled the Panic Bunker, it is now disabled.``

This is the only message that appears
