### ISSUE TITLE
Radiation in genetics console rising to unusually high levels

### ISSUE THREAD

**Issue by JannisKuckei** [tgstation/tgstation#31724]
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

I joined a game about 30 minutes in, set the output level to 8 and pulse duration to 5 on my genetics console. After just one pulse on the gene that specifies whether the monkey is human or not, the radiation level rose to about 130%. Kept climbing in similar intervals with subsequent pulses.

Sorry, don't have much other information about what may have caused this. But this much radiation can't be right.

Edit: Should probably have said the happened on Sybil

**Comment by qbmax32** [comment]
Can confirm this currently on Bagil, happened to me just now (diff. round)

**Comment by ShizCalev** [comment]
@ninjanomnom
