### ISSUE TITLE
Radiation stun does not clear up even long after rads are out of a persons system

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#31729]
On a clockcult round we had someone staying in the stun state for at least 20-30 minutes. 
They were no longer taking toxin damage nor did they still have radium/mutagen in them and the effect long persisted. 

https://atlantaned.space/newSS13tools/round.php?round=77427&logs=true

**Comment by ShizCalev** [comment]
@ninjanomnom
