### ISSUE TITLE
Plant People attacked by "friendly" vines

### ISSUE THREAD

**Issue by Doppeltongue** [tgstation/tgstation#31730]
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

Round: multiple

Plant people are cut by thorny vines when they walk through them, but are supposed to be immune to the vine thorns.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by GunHog** [comment]
Explosive vines are a hoot as well! Auto-dismembering!

**Comment by AnonymousNow** [comment]
Are wood golems also supposed to have vine/plant affinity?

**Comment by GunHog** [comment]
Yes, they are. https://github.com/tgstation/tgstation/blob/331c166074c3c013d898a9720d5eaa101cbb186c/code/modules/mob/living/carbon/human/species_types/golems.dm#L248

**Comment by tralezab** [comment]
this seems to have been fixed! i did test this
