### ISSUE TITLE
Radiation can stun you infinitely (even when its source is long since gone)

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#31746]
>See singularity
>Your round is forfeit two minutes from now.

Constant weakening even when the singularity is on the other side of the Z-level is ridiculous. You get spammed by it every second or so, and you literally never get up.

**Comment by DaxDupont** [comment]
see #31729

**Comment by ShizCalev** [comment]
Duplicate of #31746

**Comment by AnonymousNow** [comment]
>Duplicate of itself

What.

**Comment by ShizCalev** [comment]
honk.

Meant #31729
