### ISSUE TITLE
bandanas block you from shaving your hair

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#31758]
![2017-10-15_15-37-16](https://user-images.githubusercontent.com/31222036/31586669-ed9db2ba-b1cb-11e7-81d7-e39090e610b6.png)

**Comment by Cyberboss** [comment]
How were you attempting to shave your hair?

**Comment by praisenarsie** [comment]
targetting head, clicked on myself

**Comment by Cyberboss** [comment]
with what?

**Comment by praisenarsie** [comment]
razor

**Comment by BeeSting12** [comment]
It's because bandanas can act as a hat when flipped, I'm assuming. It would make a bit of sense though- it does wrap all the way around your head

**Comment by Jared-Fogle** [comment]
Bandanas also stop you from getting head surgery (at the very least, brain surgery).

**Comment by Nickkoranda** [comment]
All masks seem to block shaving, seems to be a separate issue that still makes some sense.
