### ISSUE TITLE
"Repair: Reload Block - Mass Delete - In Place" strips players naked.

### ISSUE THREAD

**Issue by JamieH** [tgstation/tgstation#31767]
Big boom, decide to use "Repair: Reload Block - Mass Delete - In Place" - player is in the area and it will strip them nekid.... guys please, not good.

**Comment by Cyberboss** [comment]
@kevinz000

**Comment by kevinz000** [comment]
@Cyberboss this is no longer the case AFAIK

**Comment by SpaceManiac** [comment]
No repro
