### ISSUE TITLE
L6 Saw won't fire automatic

### ISSUE THREAD

**Issue by Dicks1** [tgstation/tgstation#31779]
Round:77496

Can only fire the L6 Saw single fire.

**Comment by Dicks1** [comment]
This is the same for the c20 smg, doesn't fire in burst mode only single fire.

Might affect all guns that have burst fire.

**Comment by DaxDupont** [comment]
Reproduced with saw and other burst enabled things.
@kevinz000

**Comment by DaxDupont** [comment]
Can be closed @shizcalev
