### ISSUE TITLE
Deltastation SM chamber has improper piping

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#31785]
![image](https://user-images.githubusercontent.com/12382984/31593042-20dd1a00-b224-11e7-8e28-21e62b4564cd.png)

The pipes on the rad collectors are improperly designed and will not function, the bent pipes on the southmost vent/scurbber should be manifolds and the topmost ones should be bent pipes

**Comment by Anonmare** [comment]
This is roundstart so this is a mapping issue

**Comment by ShizCalev** [comment]
What the fuck?

**Comment by ShizCalev** [comment]
@ninjanomnom #30909 >:(

**Comment by ninjanomnom** [comment]
The fuck?
