### ISSUE TITLE
Slappers can break windows

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#31786]
They can also be used to break stuff you normally couldn't barehanded (windows for example)

0/10

**Comment by francinum** [comment]
make them call unarmed attack instead of dealing force.

**Comment by nicbn** [comment]
@ShizCalev close!

**Comment by ShizCalev** [comment]
The window thing wasn't fixed.

**Comment by nicbn** [comment]
JUST BE A DULLAHAN AND USE YOUR HEAD.
MWAHAHAHAHAHAHAHAHA.
