### ISSUE TITLE
Radiation is insanely powerful

### ISSUE THREAD

**Issue by Thunder12345** [tgstation/tgstation#31797]
Join as sec officer, head down arrivals hall, find space where the singulo ate the station, take one step into space and turn back, instantly hit with chain you feel weak and 17000 radiation. Other people in deadchat reporting similar radiation induced permastun and death.

**Comment by praisenarsie** [comment]
@ninjanomnom basically level6/7 singulo rads are op, nerf em

**Comment by DaxDupont** [comment]
Related to https://github.com/tgstation/tgstation/issues/31729

**Comment by bgobandit** [comment]
i ded

**Comment by AdamElTablawy** [comment]
revenants can be irradiated and proceed to irradiate others while invisible
