### ISSUE TITLE
Singularity cannot support pubbystation

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#31804]
Radiation changes resulted in it putting out a measley 200-300kW depending on singularity level, with full plasma tanks.

**Comment by DaxDupont** [comment]
@ninjanomnom

**Comment by WJohn** [comment]
As I understand it, power generated now depends on how much of the circumference you actually successfully surround with rad collectors, not how many rad collectors are present, correct? Then wouldn't singularity engines in general totally suck ass at producing power unless we buffed the shit out of singularity radiation, making it even more dangerous than it is right now?

**Comment by Armhulen** [comment]
No complaints with that
