### ISSUE TITLE
Supercooled gas expands when pumped inside an empty tank

### ISSUE THREAD

**Issue by Grazyn** [tgstation/tgstation#31802]
Before @duncathan says this is working as intended, this is how it used to work: supercool gas at x temperature, use pump to fill empty tank, tank is filled with the gas at x temperature and at the target pressure you set.
What happens now: gas expands inside the tank, even causing it to explosively rupture in some instances (gibbing you and making a small explosion).
Happened 2 times to me in game and was able to reproduce it on local server, using this setup:

![5395f1f75a07d1675b015817a2591cc5](https://user-images.githubusercontent.com/4902573/31616154-2f4eca6c-b28c-11e7-97aa-993dea5f1101.png)

Set freezer to -200 °C. Get an empty tank (I used a plasma tank which I emptied with a portable scrubber), insert in pump, set target pressure to 1000 kPa, fill it. Instead of getting a tank with 1000 kPa at -200 °C (like I used to up to last week), I got 2440 kPa at -35 °C.

Server revision compiled on: 2017-10-16

The following pull requests are currently test merged:
#31727: 'Complete rework of brain damage' by XDTM at commit a6240b
#30599: 'Moves projectile processing to a subsystem' by kevinz000 at commit 091dd2
#30972: 'Atmospherics Multilayer Pipes' by kevinz000 at commit 39ce47

Based off origin/master commit: 51c052

**Comment by duncathan** [comment]
since this is a much more detailed issue report I can verify that there actually is a minor issue here which is increasing the magnitude of the pressure expansion. thanks for making a workable report pal
