### ISSUE TITLE
Disengaging gygax leg overload breaks scanning module

### ISSUE THREAD

**Issue by JohnMcLaime** [tgstation/tgstation#31801]
[Directions]: Build a gygax with top tier "triphasic" scanning module, look at how much energy is consumed by your guns or walking. For example regular walking is energy free with top tier SM, but when you you turn on and off the overload mode on gygax, your regular walking starts to consume energy, same with guns, the mounted taser will eat ~3x more energy per shot.
First time you use overload, it works as intended (?) till you turn it off, every other overload will consume more energy than first one.
Recently there was a change which added minimal cost for movement during overload , but this bug/issue was present before that change was implemented.

**Comment by Y0SH1M4S73R** [comment]
Maybe this has to do with calling initial() when disengaging leg overload. If anybody else agrees, I can fix it.
