### ISSUE TITLE
Some dirty footprints can act like dirty puddles exactly once.

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#31805]
Steps to reproduce:  
1:  Get a puddle of blood, oil or whatever, walk around a bit to create footprints.
2:  Walk in the footprints with darker color and track even more footprints around the place.
3:  Repeat until the janitor kills themselves.

Round ID:  77524
Testmerged PRs:
#31727 
#30599 
#30972

**Comment by AnturK** [comment]
Pretty sure that's intended.

**Comment by Hatfish** [comment]
If that's the case then I can't find the PR that introduced it.

**Comment by RemieRichards** [comment]
As you walk with dirty boots, you deposit some of it on the ground, this forms the footprint(s)
The footprint is as bloody (or oily, but that's still "bloodiness) as the shoes that created them.

This is also why footprints appear to fade as you "walk the blood off" of your shoes, if it's very faded it most likely won't have enough blood on it to make more prints, but if it's full colour it probably does.

**Comment by duncathan** [comment]
Intended; ty for the verification Remie
