### ISSUE TITLE
Titanium walls from original shuttle is left behind when buying another shuttle.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#31815]
https://i.imgur.com/PHQfeol.png

**Comment by ninjanomnom** [comment]
This issue needs more details: Which map, which shuttles, what code revision etc

**Comment by praisenarsie** [comment]
All maps (IF A SHUTTLE IS BOUGHT), all BUYABLE shuttles (e.g. Build your own shuttle kit or NT lepton violet) and the most recent code revision. @ninjanomnom 

You can also can't weld the left behind walls so an admin has to delete them.

**Comment by Supermichael777** [comment]
wait did you buy a shuttle when it was docked?
