### ISSUE TITLE
WOW A LIGHTING BUG - Build your own shuttle kit lighting looks weird

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#31816]
![2017-10-16_23-22-41](https://user-images.githubusercontent.com/31222036/31637945-031a0c30-b2c9-11e7-9678-36380e61654d.png)
![2017-10-16_23-22-34](https://user-images.githubusercontent.com/31222036/31637946-03d83cbe-b2c9-11e7-81af-0092b2eb2125.png)

**Comment by alexkar598** [comment]
Can't have more than 1 milestoen

**Comment by YakumoChen** [comment]
it's probably part of the rooms system, stuff in rooms are subject to lighting effects, stuff that isn't a room is fullbright like space.

**Comment by ninjanomnom** [comment]
I'm not able to reproduce this
