### ISSUE TITLE
All PDA logs are showing recipient as invalid

### ISSUE THREAD

**Issue by nfreader** [tgstation/tgstation#31817]
See https://tgstation13.org/parsed-logs/sybil/data/logs/2017/10/16/round-77540/pda.txt

All PDA message recipients in the pda text logs are showing up as `*invalid*`. This is not the desired behavior.

**Comment by praisenarsie** [comment]
dupe of https://github.com/tgstation/tgstation/issues/31161

**Comment by nfreader** [comment]
Dag nabbit!
