### ISSUE TITLE
Things that are not cyborgs suddenly become them

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#31812]
This was round-end so I don't know if this was adminbuse or what

![image](https://user-images.githubusercontent.com/12382984/31633530-9a725864-b2b8-11e7-8598-a12e8caf426f.png)

Context: Round-end, AI remote piloting an exosuit on Centcom

**Comment by YPOQ** [comment]
https://tgstation13.org/parsed-logs/basil/data/logs/2017/10/16/round-77531/game.txt
`[20:25:29]ADMIN: shadowlight213/(Drone (670)) polymorphed all living mobs.`

**Comment by Anonmare** [comment]
Ah then never mind
