### ISSUE TITLE
Wizard Jaunting while stunned doesn't let you move

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#31825]
As said on tin.

**Comment by ShizCalev** [comment]
I believe this is intended behavior.

**Comment by RandomMarine** [comment]
Hasn't this been the case since forever?

**Comment by Dicks1** [comment]
Feature not a bug, it's always been like this.

**Comment by AnonymousNow** [comment]
Seems very, very strange.

**Comment by jughu** [comment]
If you could move it would make wizard especially hard to catch even if you just got hum down they could be everywhere even in walls.youcant reach

**Comment by Repukan** [comment]
Not a bug

**Comment by Repukan** [comment]
Get fucking good

**Comment by Repukan** [comment]
Pubby lmao

**Comment by AnonymousNow** [comment]
Can't tell if you're serious. Either way, embarassed on your behalf.
