### ISSUE TITLE
You can't read papers copied with a chameleon projector

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#31832]
![image](https://user-images.githubusercontent.com/6209658/31648201-69469b20-b2da-11e7-93b8-1a26d6f351e6.png)

honk
(Top is the paper, which opens the correct interface. Bottom is the copied version.)

**Comment by RandomMarine** [comment]
Because chameleon projections aren't actually the copied object, silly rabbit.

**Comment by moonheart08** [comment]
they should at least have text, dontcha think?

**Comment by PKPenguin321** [comment]
Not a bug and should be closed. Examining anything produced by the chameleon projector gives it away by not showing the desc, wouldn't it?

**Comment by RandomMarine** [comment]
It does copy the description. Though since the dummy effect isn't an item it doesn't add the size description that all scannable items have, so that's still a giveaway.
