### ISSUE TITLE
Cat ears stay on sprite after being removed

### ISSUE THREAD

**Issue by Mark9013100** [tgstation/tgstation#31840]
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)
Server revision compiled on: 2017-10-17

The following pull requests are currently test merged:
#31630: 'Datum rev u related upgrades to base datum antag' by AnturK at commit d0b9d3
#31835: 'Removes 200mb of wasted memory usage' by MrStonedOne at commit 706042

Based off origin/master commit: 7882cc

Surgically removing cat ears only removes the ears organ and not the sprite as well.

**Comment by praisenarsie** [comment]
critical priority

**Comment by bgobandit** [comment]
feature

**Comment by Supermichael777** [comment]
Weird organ mannip should regenerate sprites

**Comment by The-clown-known-as-Pepe** [comment]
100% sure its not fault of testmerges, its how it works after catpeople organs PR

**Comment by ShizCalev** [comment]
Unable to reproduce. Tried both admin adding / removing the ears and normal surgery, update_body is being called properly from what I'm seeing.

https://github.com/tgstation/tgstation/blob/04c05d8e5c081b61bc0c9dd755c7aefbb659b214/code/modules/surgery/organs/ears.dm#L92-L96

**Comment by ShizCalev** [comment]
Will close in a week without another repo.
