### ISSUE TITLE
SM no longer outputs enough energy to power station properly on default

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#31846]
Default setup seems no longer be generating enough power to properly feed the station power. 
On meta at least.

**Comment by Marflowerose** [comment]
The power on meta is a bit honky to begin with, Cargo Loading Dock APC runs dry in the first few minutes.

**Comment by duncathan** [comment]
@ninjanomnom is this cuz of you or cuz of me

**Comment by ninjanomnom** [comment]
Probably me but I'll take a look

**Comment by ninjanomnom** [comment]
What was the gas mix in the SM?

**Comment by ninjanomnom** [comment]
![image](https://user-images.githubusercontent.com/1234602/31701971-e24c3f4e-b3a1-11e7-8ada-cb277291f668.png)

**Comment by duncathan** [comment]
ninja tells me that power draw was achieved with no repiping so i guess the solution is to git gud

**Comment by ninjanomnom** [comment]
You can easily get in far in excess of what I did, but that's basically what you get with as default a setup as you go
