### ISSUE TITLE
Being blown as a borg causes you to be dead, unable to be borged.

### ISSUE THREAD

**Issue by Akkryls** [tgstation/tgstation#31843]
Issue reported from Round ID: 77572 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

[Directions]:  Be a borg, get blown by someone, MMI displays the brain as being lifeless, unable to be put into a new borg body, when dropped out the MMI and placed into a new one, get booted out into deadchat and can't re-enter the MMI.

The round in question was a wizard round, ghosts were visible from wizard magic so I'm unsure if the two are related.

**Comment by Repukan** [comment]
Isn't that intended?

**Comment by Anonmare** [comment]
It shouldn't be flatlining the MMI, flatlined MMIs should only happen if the MMi chooses to suicide

**Comment by ShizCalev** [comment]
We're you a roundstart Borg, one made by magic, ect?

**Comment by Akkryls** [comment]
I was a roundstart borg, and was blown by the console; I didn't ghost prematurely or leave the brain/MMI at all until I got booted out when the guy trying to re-borg me tried swapping MMIs to fix the issue. I could still talk to people the entire time despite it displaying the MMI as being lifeless.

**Comment by TheWiznard** [comment]
Round ID: 77681

Minerborg when I'm destroyed by the blood drunk miner, it leaves an mmi but ghosts me and shows me in deadchat as borg name (player name) as if I suicided as mmi. If i re-enter corpse I still only speak in deadchat

**Comment by kriskog** [comment]
shouldnt be happening anymore.
