### ISSUE TITLE
Particle Accelerator\Engine Starter orientation

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#31844]
Though it's been a little while but there is a painfully annoying bug that makes it so that if you orientate the Particle Accelerator to shoot left or right the console detects that it's missing parts making setting up a makeshift tesla or singulo very annoying to set up if you make the mistake of orientating it to shoot at it from the left or right.
When I retest this on tg or on a single player server I'll get some pictures to show those viewing this post what I mean.

**Comment by RandomMarine** [comment]
Can't reproduce. Are you setting up the containment grids backwards?

**Comment by davethwave** [comment]
I guess I am, thanks for testing this
