### ISSUE TITLE
Meters don't function

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#31850]
![](https://file.house/GJ7m.png)

```
That's a gas flow meter. 
It measures something. 
The connect error light is blinking. 
```
Caused by multilayer piping: #30972
@kevinz000

**Comment by duncathan** [comment]
This only applies to meters placed by players, correct? Ones at roundstart work?

**Comment by ShizCalev** [comment]
Roundstart ones do appear to be working.
