### ISSUE TITLE
Delta station engine fucked up??

### ISSUE THREAD

**Issue by Dicks1** [tgstation/tgstation#31856]
[Round:]() 77594
Broken pipes and reflectors not set up properly.

https://imgur.com/a/Glg7h

**Comment by ShizCalev** [comment]
Pipes were fixed by #31791

Reflectors will be fixed by #31845

**Comment by Teepeepee** [comment]
The reflectors not being the rght direction has been a thing for a while, at least I know I've seen them before like that. All the engineers I was with the times I saw it understood it as an intended feature so we have the job to rotate them the right direction (which is unintuitively done with unwelding from floor, alt+click, select the right angle out of 45° and such, and then welding them to the floor). What I'm getting at is that if this is a problem its high time it gets fixed.

**Comment by ShizCalev** [comment]
Wasn't an intended feature. The reflectors were updated to support angles outside of Cardinals, and the maps were never updated to correct their directions at roundstart because nobody reported the issue.
