### ISSUE TITLE
Revenants can soak up radiation and murder people with it

### ISSUE THREAD

**Issue by Poojawa** [tgstation/tgstation#31862]
OOC: Adam El-Tablawy: i spent like 15 minutes breaking the supermatter shard windows with defile because they're strong
OOC: Adam El-Tablawy: turns out
OOC: Adam El-Tablawy: the entire time
OOC: Adam El-Tablawy: i've been getting irradiated
OOC: Adam El-Tablawy: at a certain point of being adjacent to the supermatter for 15 minutes i start irradiating MYSELF by virtue of this
OOC: Adam El-Tablawy: i am now outputting more rads than the actual SM shard
OOC: Adam El-Tablawy: now any time i fly over someone they proceed to get about 4000 rads and get stunlocked

This new radiation needs work.

**Comment by ChangelingRain** [comment]
RADIATION GHOST

**Comment by AnonymousNow** [comment]
Hoho.

Apparently the AI Eye can pick up rads, too.

**Comment by ike709** [comment]
@ninjanomnom

**Comment by ninjanomnom** [comment]
The soaking up part is intended but the amounts sound off, what server revision is this?

AI Eyes did in fact used to get contaminated but that was patched minutes after finding out.

**Comment by Poojawa** [comment]
We're downstream but reasonably close to being to-date.

Incorporeal grief ghost probably shouldn't be getting radiation contaminated.

**Comment by ninjanomnom** [comment]
Yeah you're behind radiation versions if that's happening.

Further back than should be possible actualy, that sort of behavior was only happening for testmerge versions of the code.

**Comment by Poojawa** [comment]
by just shy of being equal I mean a day behind. So currently merged radiation code is what we've got right now.

**Comment by The-clown-known-as-Pepe** [comment]
why am i not suprised @AdamElTablawy did it

kek

**Comment by Anonmare** [comment]
Shadowrun toxic spirits when?
