### ISSUE TITLE
all in one grinder not working

### ISSUE THREAD

**Issue by Teepeepee** [tgstation/tgstation#31867]
Issue reported from Round ID: 77609

All-in-one Grinder is not working for some stuff, tried the one in botany, in the bar and in chemistry. When grinding nutriment filled wheat it gives flour as intended, when I put pottasium into the wheat and grind it it does the grinding animation but it doesn't consume the wheat nor give pottasium

**Comment by AnonymousNow** [comment]
Tried this with Space Twinkies and nothing happened. Xenobiology's plasma grinding escaped the worst of it even as other departments lamented their grinders, but that might have changed.

**Comment by ShizCalev** [comment]
Duplicate of #31697
