### ISSUE TITLE
Replica Pods & Suicide

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#31861]
Issue reported from Round ID: 77596 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Replica pods do not properly create a new body if the person who has their blood injected suicides. Not sure if intentional or a bug.

**Comment by AnonymousNow** [comment]
Likely intentional, due to the nature of suicide.

**Comment by ShizCalev** [comment]
Intentional, if you suicide you're out.
