### ISSUE TITLE
Cat people can apparently bypass the config option if they had it enabled before the config was disabled

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#31884]
According to a recent PR:
"Catpeople are litteraly cancer **people rush genetics as a head to turn themself into a monkey then a human so they regain their cat organs** which is litteraly cancer and goes against the no cat/non humans as head lore once again catpeople players cant be seen responsible"

From what I can tell:
1. Go to genetics
2. Inject monkey SE after making a clone of your original SE
3. Inject again
4. Game will "fix" you and will pull cat ears due to not respecting the config option during the transformation

We really need to adjust all instances of applying cat ears to respect the config option.

**Comment by Iamgoofball** [comment]
whoops

**Comment by Cyberboss** [comment]
Duplicate of #31869
