### ISSUE TITLE
Two white ships spawn, only one move.

### ISSUE THREAD

**Issue by Ignies** [tgstation/tgstation#31886]
Map = Meta and box

Found this bug twice, after finding in space the old, large white ship (medical hardsuits), it wouldn't move but instead it spawned (or moved) the more fitted one (with botany and stuff).

This can be kind of abused, more loot, a spare board to hide the ship away and summon it from the station or lavaland, being able to hijack the whiteship with a custom destination if someone is using it without even getting close to it.

**Comment by AnonymousNow** [comment]
There was a recent changeover to the new frigate, and the old ship was added as a ruin, which is cool. Didn't think they'd interact like this, though.

#31709

**Comment by nicbn** [comment]
Not a bug
