### ISSUE TITLE
Unable to fly the White ship

### ISSUE THREAD

**Issue by TheAutism** [tgstation/tgstation#31898]
Issue reported from Round ID: 77645 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

I could not fly the white ship, the flight console just said "Status: *Missing*"

**Comment by ShizCalev** [comment]
What map

**Comment by ShizCalev** [comment]
Delta station was the map.

**Comment by vuonojenmustaturska** [comment]
related to #31886 ?
