### ISSUE TITLE
fully_revive doesn't regenerate missing limbs or organs

### ISSUE THREAD

**Issue by JJRcop** [tgstation/tgstation#31895]
https://github.com/tgstation/tgstation/blob/c4a4a19ae4b680e906aa781508f412c49433aa9c/code/modules/mob/living/living.dm#L409-L435

so if you die without a liver or something and you are revived with this proc, you will die quickly

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/aac6b076c704ddafa408f4b67edf5d1a6d41be02/code/modules/mob/living/carbon/human/human.dm#L792

it does for humans

**Comment by JJRcop** [comment]
whoops
