### ISSUE TITLE
Screwdrivering open cryotube base makes it vanish.

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#31897]
![bug - cryo tube base vanishing](https://user-images.githubusercontent.com/6266927/31753956-2a306f34-b48c-11e7-9ef1-9f159558320c.png)

I was trying to help, and I made something vanish from this dimension.

**Comment by Robustin** [comment]
This is a pretty big deal, saw this happen yesterday, cryo is pretttty important.
