### ISSUE TITLE
Lasering mech also lasers the pilot inside.

### ISSUE THREAD

**Issue by Ausops** [tgstation/tgstation#31899]
[Directions]: #77647 bagil
Server revision compiled on: 2017-10-19
#31855: 'Dullahans' by KorPhaeron at commit dc51cf
Based off origin/master commit: c4e8a3

spawn durand, put a pilot in durand, laser the durand, pilot falls out dead from burn damage while mech still functional

**Comment by optimumtact** [comment]
@kevinz000 probably your vehicle change

**Comment by banthebantz** [comment]
>we still let kevinz touch the code

**Comment by GuyonBroadway** [comment]
its not his vehicle change it was his projectile refactor.

**Comment by GuyonBroadway** [comment]
@kevinz000 YOU DONKEY!

**Comment by Kaptinalexander** [comment]
This is a shitty bug, hope it gets fixed soonish
