### ISSUE TITLE
Malf AI's hacking apc texture is the old one

### ISSUE THREAD

**Issue by naltronix** [tgstation/tgstation#31906]
Issue reported from Round ID: 77658 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Title

**Comment by Cyberboss** [comment]
It uses apcemag in power.dmi. Seems to be the right one to me

**Comment by naltronix** [comment]
its the old bsod apc texture that you get when you are hacking an apc, it appears in the top right my fren

**Comment by ShizCalev** [comment]
@Armhulen still an issue?
