### ISSUE TITLE
Space cash is awful to sort and kind of buggy.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#31928]
![](https://i.imgur.com/xUFPFwF.png)

>Blue cash equals 200 credits
>There are stacks of 5 and 20, worth 1000 and 4000 respectively, still using the blue sprite.
>Both are apparently worth 1000 and two hundred at the same time
>Is actually worth 5000 in total.

What the hell??

We have stack icon changes now, make it so it actually changes sprites based on how much cash there is, and tell us exactly how much there is in there rather than how many chunks of space money there are. I don't know, limit it to stacks of 5,000 cash with the blood red 1k cash icon?

**Comment by praisenarsie** [comment]
Somebody (or I) gotta port bay's or vg's money system.
