### ISSUE TITLE
officers beret from special ops officer kit (select equipment) makes hair look retarded

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#31926]
https://file.house/KKCf.png

**Comment by ShizCalev** [comment]
Extension of #30433

**Comment by Bawhoppen** [comment]
This was only partially fixed 
![image](https://user-images.githubusercontent.com/6510293/54075616-14d3cb80-4267-11e9-8df9-e3fe00c05d38.png)
![image](https://user-images.githubusercontent.com/6510293/54075622-1d2c0680-4267-11e9-93a6-ce1e51ea3036.png)
