### ISSUE TITLE
People lying on the ground become extremely difficult to click

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#31962]
I've seen this multiple times this week. Once I've stunned someone, clicking them again with your weapon becomes almost impossible, you can mouse right over their center of mass and you will still be "aiming" for whatever is behind them. 

I've wiggled my mouse all over to account for this but there's no reliable way to melee people once they're done.

**Comment by calibraptor** [comment]
I have the same fucking issue

**Comment by AnturK** [comment]
Byond version, OS etc, and some steps to reproduce, because i don't really see this happening

**Comment by Bawhoppen** [comment]
Happens to me too actually

**Comment by calibraptor** [comment]
Windows 10
Byond Version 511.1370

**Comment by Cyberboss** [comment]
report what's on the same tile next time this happens

**Comment by AnturK** [comment]
>511.1370

That's 15 versions from current stable and ~261 days old.

**Comment by Electronics** [comment]
Happens here too, This may be related to another problem where the lying down person will seemingly jump to the tile above (whether it be a wall/floor/etc) and will become unclickable either in the old or new location. After a few seconds their sprite jumps back to the correct place and becomes clickable again.

**Comment by calibraptor** [comment]
Bug seems to be solved by updating to the latest byond stable version for me.

**Comment by KorPhaeron** [comment]
Dont think this has happened in a while
