### ISSUE TITLE
Lizard characters aren't being made lizards

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#31985]
They sign up as their lizard character and have their same name but enter the game as humans. Also removes restrictions, so you can have, say, Loves-the-Lizards as a human captain.

**Comment by calzilla1** [comment]
Hahahahahahahahah yeeees

**Comment by Supermichael777** [comment]
Not a bug/s

**Comment by Repukan** [comment]
Pretty sure lizards are barred from head positions.

**Comment by ShizCalev** [comment]
Different field for Lizard name perhaps?

**Comment by Dorsisdwarf** [comment]
oops

**Comment by bgobandit** [comment]
@Repukan it's not just head positions this happens to, a warden had the issue as well
