### ISSUE TITLE
Increase log time precision

### ISSUE THREAD

**Issue by JamieH** [tgstation/tgstation#31980]
Is there any reason we're not doing this? Can we do milliseconds?

**Comment by lzimann** [comment]
Is it really needed?

**Comment by JamieH** [comment]
https://tools.hippiestation.com/stats/round.php?round=23729&logs=true

"Log time resolution is limited to seconds, and a lot can happen in one second. The logs are parsed on the backend in the correct order in which they are recevied. For display purposes though, they are re-sorted and displayed in order by seconds. This may put certain events out of order, but those incidences should be minimal." <- it'd be nice if this wasn't an issue.

**Comment by Cyberboss** [comment]
best we can do if we tried is ds

**Comment by lzimann** [comment]
Technically speaking it is already in ds, I believe all you need to do is add `:ms` to timestamp calls on logging
https://github.com/tgstation/tgstation/blob/master/code/__HELPERS/time.dm#L5

Might be wrong/might

**Comment by Cyberboss** [comment]
Dm reference says otherwise http://www.byond.com/docs/ref/info.html#/proc/time2text. I'm going to close this because the only other way we could get more precision is by offloading logging to a dll or shell command. This is more a failing of @nfreader's site anyway.
