### ISSUE TITLE
Nightmares dont get their armblade when cloned

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#31999]
Because clones start with no limbs now, it will attempt to equip the arm blade on species gain, and fail to do so, deleting it

**Comment by ExcessiveUseOfCobblestone** [comment]
It's hacky af but you COULD force them to remove and regain the species upon finishing their cloning :^)

**Comment by KorPhaeron** [comment]
I think just forcing them to grow an arm if they don't have one would be way saner
