### ISSUE TITLE
Test Range Firing Pins not working at Delta Station Science Firing Range

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#31994]
Like the title says, if you make a test-range firing pin and put it in a gun, the gun won't fire in the firing range at the science department. I have not tested to see if this holds true for the security firing range.

**Comment by vuonojenmustaturska** [comment]
Only box, centcom and meta have a /obj/machinery/magnetic_controller

Map edits are a bit byond me, but whoever fixes this should also fix omega and pubby.
