### ISSUE TITLE
Showers are kind of loud.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#32011]
They can be heard from a solid 7-10 tiles away, probably should only be possible to hear within 3-4 tiles (and very quiet at that distance). Also standing in a shower is pretty noisy, could be reduced just a smidge.

**Comment by Supermichael777** [comment]
have you ever bathed? showers are loud

**Comment by ShadowDeath6** [comment]
>plays ss13
"have you ever bathed?"

showers should be loud while you're standing in them imo

**Comment by WJohn** [comment]
sure, when you're standing in them, but it shouldn't be possible to hear them from like 10 tiles away.

**Comment by praisenarsie** [comment]
they're fine as is?

**Comment by KorPhaeron** [comment]
Hearing things from like three rooms over is not a shower bug and I'm pretty sure robustin already made an issue report about it

**Comment by WJohn** [comment]
Yeah 'cause I can hear these things running from 18 tiles away, though it's very faint at that distance. Much more noticeable by the time you're at ~15 tiles or less.
