### ISSUE TITLE
Typing in your headset frequency will always set it to 144.1

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#32014]
Found this while trying to recreate an unrelated unicorn bug. Using the arrows works fine.

**Comment by ShizCalev** [comment]
Oldddddddddd bug. Forgot to report it when I was testing something else.

**Comment by ShizCalev** [comment]
Oh, right now I remember. I was trying to test setting the headset to the radio frequency to the syndi channel and found this a while back.

In extension to this, you can also spam the left and right arrows to sweep for the syndicate frequency to unlock the headset, which should probably be blocked out when using the arrows once this is fixed.

**Comment by SpaceManiac** [comment]
The input code is just really bad, typing e.g. `1451` without a decimal will set it to `145.1` successfully

**Comment by Davidj361** [comment]
Wow
