### ISSUE TITLE
It is impossible to remove radiation from a mob via chemistry with pentetic acid/potassium iodide

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#32026]
title, mob gets peramfucked too. Seems kinda dumb that potassium iodide/pentetic acid aka the anti rad chems do nothing to stop radiation

**Comment by AnturK** [comment]
@ninjanomnom from quick glance min clause in pen acid is wrong. 
Potassium iodide just does it very slowly.

**Comment by ninjanomnom** [comment]
yeah I have a balance pr 90% done with the fix for this
