### ISSUE TITLE
Bloody footsteps replicate blood

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#32020]
1) Step in a pile of blood

2) Your first footprint outside the blood will now have 95 bloodiness or whatever in it. Your shoes will now have 95 bloodiness as well

3) Run about to get the rest of the blood off your shoes

4) Step in that first footprint, which sets your shoe bloodiness to 95 again

5) Repeat forever until the entire station is covered in footprints

**Comment by WJohn** [comment]
i have noticed that the whiteship had an abnormal amount of blood and oil all over it, like way more than the few scattered blood/oil piles suggested.

**Comment by Repukan** [comment]
Dupe

**Comment by Hatfish** [comment]
I made a similar issue report in #31805 but this seems to be different since the footprints aren't actually losing bloodiness whenever they create a new trail.

**Comment by KorPhaeron** [comment]
Here is a pile of blood. It has 100 bloodiness.

![blood1](https://user-images.githubusercontent.com/14340985/31894290-9b59a3fc-b7d3-11e7-8857-249b439a9769.png)

Here I have stepped in the blood, setting bloodiness to 0, and my shoe bloodiness to 95

![blood2](https://user-images.githubusercontent.com/14340985/31894350-cd77b9dc-b7d3-11e7-9ccb-e78009d5026e.png)

However in the same step I also left footprints on the turf (that I forgot to screencap the var of) with 95 bloodiness. I have now turned 100 bloodiness into 190 bloodiness

Every step I lose 5 or whatever bloodiness from my shoes, but it leaves a new puddle behind. So for 5 more bloodiness lost on my shoes, I create a new 90 blood puddle in the next step which I can use to reset the process over and over and over and manage crisscrossing footsteps on almost every tile of the centcomm dock from a single starting blood tile

![janitorhell](https://user-images.githubusercontent.com/14340985/31894444-13ff75d4-b7d4-11e7-9d4d-9f8881fb8401.png)

**Comment by RemieRichards** [comment]
lol

**Comment by KorPhaeron** [comment]
I was getting the shuttle as well but the crew ordered the luxury one and it reset my progress/locked me out

**Comment by KorPhaeron** [comment]
Anyway a single footprint has more blood than the human body in it at the end of the day, it's pretty wild

**Comment by Arianya** [comment]
This has made being a janitor living hell, and applies to oil as well as blood.

Please high priority fix.

**Comment by nicbn** [comment]
I'm on it.
