### ISSUE TITLE
You can't place pipes on top of catwalks or girders with the RPD

### ISSUE THREAD

**Issue by PaznerIV** [tgstation/tgstation#32034]
I noticed that you cant place pipes on top of catwalks or girders with the RPD you can still place them but, you have to alt click the tile and click on the space tile to place them down or on a space tile next to it and drag it on top of it to wrench it down.

**Comment by praisenarsie** [comment]
@duncathan

**Comment by PKPenguin321** [comment]
This isn't really a bug if you think about it
