### ISSUE TITLE
Mutant hands (zombie claws) show up on prosthetic limbs

### ISSUE THREAD

**Issue by imtakingabreakdontatme** [tgstation/tgstation#32033]
1. Cut zombies arm off

2. Give it a robot arm so it can be a productive employee that holds things

3. Robot arm turns into a zombie claw

**Comment by XDTM** [comment]
Either you get zombies who can be relimbed to have arms, or you keep the claws regardless of limb swapping. I think it used to be the latter, which was then changed to the former after a bug report.

Which one is the right one?

**Comment by KorPhaeron** [comment]
The old bug was that if you cut off a zombies arm and reattached it that arm would have no claw because the item deleted on drop

**Comment by KorPhaeron** [comment]
Maybe mutant hands should be applied on arm Insert()

Maybe we need mutant arms that track mutant hands so if you cut off a zombie arm and attach it you have a zombie claw

**Comment by XDTM** [comment]
i'm 90% sure we have a system like that for chainsaw arms and artificial armblades, could be what we're looking for
