### ISSUE TITLE
In critical health "You feel your heart slow down..." is kinda spammy.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#32035]
![2017-10-23_18-22-32](https://user-images.githubusercontent.com/31222036/31903160-36dce492-b81f-11e7-9eb7-8086e969cb3a.png)

**Comment by banthebantz** [comment]
yes

**Comment by ShizCalev** [comment]
Did you get popped with Epi or something? 

https://github.com/tgstation/tgstation/blob/04c05d8e5c081b61bc0c9dd755c7aefbb659b214/code/modules/surgery/organs/heart.dm#L58-L61

It sets your heartbeat to slow when it procs, so something was raising your heartrate right afterward.

**Comment by banthebantz** [comment]
what causes heartrate to change because certain chems spam this

**Comment by ShizCalev** [comment]
Epilepsy, hallucinations, getting shocked, earthsblood (ambrosia gaia reagent), coffee, or tea could've also been the cause here.

**Comment by praisenarsie** [comment]
@ShizCalev i got hit with multiple wiznerd fireballs
