### ISSUE TITLE
Lightgeists cannot be spawned from Gold Slime Cores

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#32040]
They were supposed to be added to the pool in a recent merged pull (past few weeks), but extensive testing has shown that they simply don't appear at all.

**Comment by praisenarsie** [comment]
@Armhulen

**Comment by Ergovisavi** [comment]
Wait why the hell were these even added? They're explicitly supposed to only come from anomalous crystals.

**Comment by praisenarsie** [comment]
@Ergovisavi blame the person i just tagged

**Comment by AnonymousNow** [comment]
Since they're incredibly rare and weak, adding a more frequent, but non-renewable means of spawning for them made sense.

I have seen three lightgeists since they were added to the game, and they were all adminspawned.

**Comment by YPOQ** [comment]
https://github.com/tgstation/tgstation/blob/8e434b7d9689cf60c7468fe97cb4040c70dfdf9a/code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm#L619
This needs removed.
