### ISSUE TITLE
You slap Unknown in the r_arm! 

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#32044]
1. *slap
2. aim at arm
3. You slap Unknown in the r_arm!

**Comment by praisenarsie** [comment]
aim at the "lower body" now and immediately regret it @factoryman942

**Comment by deathride58** [comment]
Slappers were a mistake

**Comment by Mark9013100** [comment]
If you set your target zone to none, you'll get a message such as:
You slap Unknown in the  !
