### ISSUE TITLE
the cable coils mapped in roudnstart on the solars cannot be picked up by your cable coil dispenser

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#32060]
To reproduce, spawn as a cyborg and spend your coil. If you attempt to pick up coils from the solars it it wont work, until you split said cable coil up. Not sure if this is a general issue with mapstart cable coil stacks though

**Comment by ShizCalev** [comment]
Fixed by #31992, servers aren't updated yet.
