### ISSUE TITLE
Radiation on highpop seems to kill/lag the server out 

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#32063]
Exact numbers forgotten but @BeeSting12 has also seen repeated behaviour, maybe a few other people can also go on about it, but radiation also seems to be absurdly exponential instantly jumping into the thousands from just a single tick or two of exposure to the SM or something else making it beyond hilariously lethal, and effectively impossible to remove too on clothing and mobs.

**Comment by ShizCalev** [comment]
@ninjanomnom

**Comment by ninjanomnom** [comment]
The radiation subsystem is a heavy system but is set up correctly to only use extra ticks after the more important subsystems.

@MrStonedOne found out the overlay subsystem is the/a source of tick overrun which is the real cause of the lag.

I will be working on performance and if it continues being an issue I have some last ditch ways to minimize lag but for the moment it's not an issue.

This should get somewhat helped though by my balance and tweaks pr already out.

**Comment by MrStonedOne** [comment]
Very likely this will be fixed today. waiting for highpop to see.
