### ISSUE TITLE
Toxins Bombs not Exploding

### ISSUE THREAD

**Issue by Zytolg** [tgstation/tgstation#32064]
I was doing a regular job in Toxins. I did mess up the plasma so that only ever got heated to 48 degrees. The oxygen was cooled to 120. I've asked an admin if that would make the bomb go off, even if it were extremely weak, and it was affirmed. So I made 5 bombs using full oxygen tanks and plasma tanks of the above the above temperature values, and one with a default oxygen tank with the full plasma tank. None of them exploded during the round. I tried different methods of detonation down to manually switching the tank to open, yet it provided no explosion. I've been directed to report a bug here in the aftermath of the round. 
![bombs are broken gg ss13](https://user-images.githubusercontent.com/33048583/31924903-b87cd498-b852-11e7-9200-53fa9c821de1.JPG)

I've attached an image of the atmosphere readouts of the canisters I was utilizing for toxins that round along with the interaction menu for the bomb. Hopefully this helps you locate this problem.

Issue reported from Round ID: 77863 (Sybil)

[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by Arianya** [comment]
A 48*C plasma canister isn't going to explode when mixed with O2.

Most likely not a bug.

**Comment by ShizCalev** [comment]
Yeah, the explosion is caused by the rapid change in pressure forcing the container past it's limit when a gas past ignition point mixes with another far below. In this case, the plasma wasn't heated sufficiently to cause the desired reaction.
