### ISSUE TITLE
Staff of Changing a gorilla can make an invisible, invulnerable, untargetable gorilla.

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#32074]
![image](https://user-images.githubusercontent.com/6209658/31946257-54be16ae-b89f-11e7-8058-dc8682f8d43a.png)

![image](https://user-images.githubusercontent.com/6209658/31946287-71dd1c4e-b89f-11e7-9047-faabcb4f1e05.png)

both of these pictures contain a gorilla.

**Comment by Mark9013100** [comment]
THE ULTIMATE EVIL

**Comment by jughu** [comment]
THEY ARE ADVANCING

**Comment by pantherpusher** [comment]
Rise of the station of the invisagorilla

**Comment by Repukan** [comment]
Nonsense, I don't see an invisible gorilla anywhere in that picture.

**Comment by calzilla1** [comment]
You need to check your eyes, I can ser the gorrilla just fine!

**Comment by Anonmare** [comment]
Gorilla warfare has changed

**Comment by praisenarsie** [comment]
https://github.com/HippieStation/HippieStation/issues/5420 is possibly related.
