### ISSUE TITLE
A player released from a bluespace bodybag loses the majority of their HUD and their inventory is glitched.

### ISSUE THREAD

**Issue by Daundra** [tgstation/tgstation#32072]
Issue reported from Round ID: 77879 (Sybil)

based off 324193.

images related:
https://i.imgur.com/vizXwhZ.png (several minutes after being released from the bluespace bag. I was initially naked and could not interact with my inventory at all, which I still cant. I was able to pick up and equip new clothes and even a backpack despite my original one never being looted off me and the sprite still being shown on my character.)

https://i.imgur.com/7QJTAXo.png (not really picture of the bug but just proof that I was in fact stuffed in a bluespace bodybag before this bug started occuring)

this is a pretty damn bad bug as essentially my hands are the only "inventory" slots I have left and I cant interact with my clothing, PDA, or backpack in any way.

**Comment by nicbn** [comment]
You pressed F12 accidentally. Press it again twice.
@ShizCalev not a bug, close.

**Comment by ShizCalev** [comment]
honk
