### ISSUE TITLE
explain what "some_magic_bullshit" timers are.

### ISSUE THREAD

**Issue by moonheart08** [tgstation/tgstation#32092]
```Timer: Timer: 2580, TTR: 1678, Flags: TIMER_STOPPABLE, callBack: [0x21023b1b], callBack.object: some_magic_bullshit[0x60001ae](GLOBAL_PROC), callBack.delegate:/proc/qdel(the green laser)Prev: NULL, Next: NULL```

This could do with explaining. (I partially suspect my fellow admin, but still, it needs explaining)

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/529077d98285b498c867b7eb4f2a9d52f44b16d1/code/__DEFINES/callbacks.dm#L1

**Comment by Anonmare** [comment]
I don't think anyone knows what it does

**Comment by Bawhoppen** [comment]
Delete it and see what breaks then we'll know

**Comment by MrStonedOne** [comment]
It means its a global proc

callbacks have to have an affirmative object to call back on. if we used null for global procs, there would be no way to know if the callback was for a global proc or a object that was deleted. So we use the define GLOBAL_PROC, this define currently resolves to "some_magic_bullshit"

**Comment by MrStonedOne** [comment]
it even says this in the debug message:

`callBack.object: some_magic_bullshit[0x60001ae](GLOBAL_PROC)`

`callBack.object:` == the `object` variable on the `callBack` variable

`some_magic_bullshit` = the string representation of the `object` variable from above

`[0x60001ae]` == the `\ref` for the `object` variable from above

`(GLOBAL_PROC)` == the `type` of the `object` variable from above (where it nicely shortcuts this to `GLOBAL_PROC` for global procs rather then a null type)
