### ISSUE TITLE
You can't touch a table in atmos (MetaStation)

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#32105]
![2017-10-25_19-23-55](https://user-images.githubusercontent.com/31222036/32015840-2e4bffe2-b9ba-11e7-90df-c5e4fccac0d2.png)

**Comment by praisenarsie** [comment]
@ShizCalev

**Comment by ShizCalev** [comment]
Out till after Halloween. Only way to resolve this would be to move the table left or down one and move the corresponding computer into it's place.

**Comment by BeeSting12** [comment]
I'll get it when I get home.
