### ISSUE TITLE
You can use solid objects such as food and pills to fill the smoke machine

### ISSUE THREAD

**Issue by Daundra** [tgstation/tgstation#32102]
Issue reported from Round ID: 77919 (Sybil)
324193
https://i.imgur.com/A5P2Yuq.png

self explanatory.

image taken after inserting a pill and patch (patches work too!) from fire and toxins medkits. earlier in the round I "inserted" donuts into the smoke machine, but what this did is take the nutriment in the donut but leave the donut itself behind. (attempting to eat the donut after filling the smoke machine with it just gives you the "Oh no! There's no donut left!" message.)

An interesting thing to note about this is after turning it on, the patch affects applied and I was healed of damage very slowly. I don't know if being able to do this is intended at all though.

**Comment by praisenarsie** [comment]
@Robustin Fix it.

**Comment by AnonymousNow** [comment]
Breaking down a patch/food for its constituent chemicals to create smoke makes a lot of sense to me; leaving a ghost doughnut does not.

**Comment by GunHog** [comment]
Having the machine delete the item containing the reagents is the more fun solution to this bug, in my opinion. (Over simply preventing them being used)

**Comment by BlueNothing** [comment]
It makes more sense, but the ghost donuts are funny.
