### ISSUE TITLE
Augmented heads and torsos disappear in excess of 200+ burn damage

### ISSUE THREAD

**Issue by Ziiro** [tgstation/tgstation#32113]
![dreamseeker_2017-10-25_21-24-11](https://user-images.githubusercontent.com/26494679/32033709-560db712-b9cb-11e7-9b22-80bd661834da.png)

It appears to dump all other damage decals when it happens, too.

**Comment by kevinz000** [comment]
not an i ssue i think

**Comment by kevinz000** [comment]
@Cyberboss

**Comment by Ziiro** [comment]
This is pretty old. I think it has something to do with it attempting to find the husk (or gendered husk) sprite, but there is none. Might not be around anymore.

**Comment by JohnFulpWillard** [comment]
![image](https://user-images.githubusercontent.com/53777086/216479504-bac81c17-99d5-40ca-a263-680f4c479a5a.png)
