### ISSUE TITLE
X4 planting on bags

### ISSUE THREAD

**Issue by jericho140** [tgstation/tgstation#32111]
Issue reported from Round ID: 77940 (Sybil)

Putting X4 into a bag with no more space will attempt to plant the X4 on the bag. Putting an X4 into an empty bag works fine and the issue doesn't exist with C4.

**Comment by Dorsisdwarf** [comment]
I mean, this seems like a reasonable functionality? If you cant fit it in bag, attempt to plant?

**Comment by ShizCalev** [comment]
That sounds like correct functionality imo

**Comment by PKPenguin321** [comment]
The problem is that this functionality isn't immediately obvious and has lead to at least one player blowing themselves up (although frankly I think that's pretty funny and should stay anyways)

**Comment by jericho140** [comment]
It seems like an inconsistency to me since you can't plant C4 on a bag.

**Comment by Durkel** [comment]
I've seen ops blow themselves up on their shuttle like this before. Watching a team wipe because someone x-4'd their combat belt is a good laugh but leaves four angry players.

**Comment by kevinz000** [comment]
function is same as c4 now not an issue
@Cyberboss
