### ISSUE TITLE
Mix console fucked after reconnecting it

### ISSUE THREAD

**Issue by naltronix** [tgstation/tgstation#32122]
Issue reported from Round ID: 77969 (Sybil)
For context, assmos was merged.
Basically, trying to do fusion n shit, and i thought what if i disconnect the mix console to tox and then reconnect back to mix
fucked.png
basically, output regulator got fucked open and input just showed up as NaN L/s
by pressing inject on and off it returned to normal, but the output regulator appeared to be closed but was actually open. i cant mix plz restart.

**Comment by AnturK** [comment]
#30791 Testmerge related issues go to PR comments.

**Comment by naltronix** [comment]
it was merged, but it might not be an assmos bug.

**Comment by AnturK** [comment]
Possibly, but i'll go with the simplest explanation, if that's not it i'll reopen the issue.

**Comment by as334** [comment]
@Anturk I can confirm this bug existed before atmos, I've noticed this in rounds without assmos.

**Comment by Mooshimi** [comment]
Can we have this reproduced recently?

**Comment by jlsnow301** [comment]
I'm wondering if this is related to #36668
