### ISSUE TITLE
Dullahans and Ling dont mix well

### ISSUE THREAD

**Issue by Daturix** [tgstation/tgstation#32135]
If a dullahan ling uses regenerate to get another head they die instantly.

**Comment by KorPhaeron** [comment]
lmao

**Comment by SgtxRootbeer** [comment]
F E A T U R E
fuck lings

**Comment by KorPhaeron** [comment]
Plasmamen die if they dont have their suits on

A ling will burn to death if they transform into a plasmaman without a suit

Dullahans gib if they break the rules and get a new head

A ling will gib if they transform into a dullahan and grow a new head

**Comment by PKPenguin321** [comment]
>get ling objective to take the identity and ID of a dullahan
>literally cant do it because you will gib
>this isnt a bug

**Comment by KorPhaeron** [comment]
Just dont try to grow a new head while a dullahan
