### ISSUE TITLE
Centcomm battle cruiser turret (escape shuttle) have the wrong turret faction

### ISSUE THREAD

**Issue by imtakingabreakdontatme** [tgstation/tgstation#32147]
Their faction is "turret" meaning if you bring Runtime or whatever inside the shuttle they go nuts and start killing everyone in the crossfire

**Comment by WJohn** [comment]
They only have a human mob check, meaning they shoot at anything non human. This includes carp, cats, dogs, and simple animal humans (pirate/syndie mobs). This also means they WON'T shoot at priority targets like wizards or actual nuke ops (who only have the syndicate faction).

**Comment by 81Denton** [comment]
This has been fixed in #35427

**Comment by 81Denton** [comment]
@SpaceManiac
