### ISSUE TITLE
Same round type in a row for at least 3 rounds

### ISSUE THREAD

**Issue by Dicks1** [tgstation/tgstation#32149]
Been noticing the same rounds repeating a lot lately, 2 days ago there was 3 clock cult rounds so I forced the fourth round to be traitor, yesterday there was 3 rev rounds in a row so I forced traitor, today there was 3 nuke op rounds in a row. Just seems too common to be getting triple rounds everyday it seems. Maybe it's nothing.

**Comment by Magikarpet** [comment]
![rng](https://user-images.githubusercontent.com/13814514/32090708-f2ea46c6-baad-11e7-9d3f-bf229826ec84.png)

**Comment by BeeSting12** [comment]
Not a bug

**Comment by vuonojenmustaturska** [comment]
Are you sure an admin isn't forcing specific round types? Some unnameds have been known to force modes such as revs 5 times in a row.

**Comment by MrStonedOne** [comment]
Op mentioned forcing a round type on the 4th, so i'd assume they are and admin and would know

**Comment by AnturK** [comment]
From quick glance at atlanta's site this seems to be just coincidence.
