### ISSUE TITLE
Photocopiers

### ISSUE THREAD

**Issue by NanookoftheNorth** [tgstation/tgstation#32169]
Issue reported from Round ID: 78026 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

Copy machines remove the %f function from each piece of paper when placed in the machine.

**Comment by Bawhoppen** [comment]
This must be new because it was working only a couple days ago

**Comment by NanookoftheNorth** [comment]
False alarm. I didn't have a pen in hand, so the form slots weren't
working. I am going to update the form guide soon.
