### ISSUE TITLE
Vampires can't get out of bat form

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#32178]
Round ID:78040 Edit: On sybil! (also first issue post. woot.)

1. As a vampire I kept going through maint trying to get into virology during this cult round, I passed the chapel several times in maint figuring out why I couldn't reach virology.

2.  I kept reaching the medbay surgery maint. Well as a bat, I screamed with my human character name every time I passed chapel and I was on fire.  "No biggy." I just thought and I would put it out with a fire extinguisher.

3. But eventually I started collapsing and went into bat form, I think I might of supposed to be critted, but I went into bat form at the nick of time..so I was stuck as a bat. Every time I hit the transformation button, I would just squeak. So, halp???

**Comment by KorPhaeron** [comment]
Its possible your real body ran out of blood and vaporized
