### ISSUE TITLE
(Halloween event) Vampire using legion souls, clonning.

### ISSUE THREAD

**Issue by Ignies** [tgstation/tgstation#32177]
- Using a regenerative core from a legion resets your blood level to the default state.
- After being clonned, you are given the bat power once again, thus, getting two powers that you can alternate to get in and out of bat form faster  (No idea if being clonned more than once will add even more of them).

**Comment by YakumoChen** [comment]
first issue is intended, regenerative core is an admin heal and gives you a default state.
