### ISSUE TITLE
Transforming into a Dullahan and then into something else leaves you without a head.

### ISSUE THREAD

**Issue by darkpaladin109** [tgstation/tgstation#32175]
Self-explanatory. I've had this happen both as a wizard (using the magic mirror) and a changeling.  

Transforming into a Dullahan seems to work fine, but changing to anything else just leaves your head lying on the ground. 
You also seem to keep the ability that's supposed to let you switch vision between head and body.

**Comment by adamkad1** [comment]
It also let you keep powers of some races, and prevents your sprite from changing when you put on clothes or draw a weapon. Like a nightmare looks like a naked dullahan
