### ISSUE TITLE
MMIs die inside mechs during ash storms(?)

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#32187]
I have no idea what happened, but I just straight up died as a MMI inside a Ripley.
There was an ash storm happening, but mechs are ash storm proof.
No sounds, no effects, nothing, just badabingbadaboom you're dead.

**Comment by SpaceManiac** [comment]
Reproduced. The brain's loc is not the mecha but its MMI, so the shielding of the mecha doesn't apply.
