### ISSUE TITLE
Atmos filters changing orientation when they are wrenched down

### ISSUE THREAD

**Issue by Gouty** [tgstation/tgstation#32184]
Issue reported from Round ID: 78051 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Reproduction: Get a RPD - put down a filter, wrench it down, notice how the side sometimes flips and the orientation changes.  I haven't worked out the pattern as to what it is doing, but it makes filtering stuff really difficult,

**Comment by GunHog** [comment]
Confirming this. They are incorrectly sprited or labeled. Hover your mouse over one pointing north and filtering west, but the tooltip says it goes south. Also, when activated, it does not show the active mode animation either. Atmos has plenty of equipment for gas mixing autism, but Toxins needs heavy modification to achieve the same. Being unable to make more filters with the RPD is a pain.

**Comment by ShizCalev** [comment]
#25585 made worse I guess?

**Comment by ShizCalev** [comment]
@duncathan

**Comment by lightcat** [comment]
This is still a problem and needs to be addressed. Probably could destroy the SM just by unwrenching and then re-wrenching these things. Also confirmed on Citadel that this is a upstream issue.

https://github.com/Citadel-Station-13/Citadel-Station-13/issues/3767

**Comment by duncathan** [comment]
@lightcat thank you for the detailed report, it will be a big help
