### ISSUE TITLE
cloning doesn't clone cat organs/doesn't do it properly and afterwards a cat tail is unable to be attached through surgery 

### ISSUE THREAD

**Issue by Bod9001** [tgstation/tgstation#32190]
Issue reported from Round ID: 78053 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

so was cat girl, Go to cloning to get a backup of myself so I don't get completely destroyed by ash Drake get killed by ash Drake (I don't know why but it's probably why The surgeries not working, i am cloned with no cat organs, that I can see),

 die multiple times get cloned again Die again get cloned again , finely "kill" the ash Drake, managed to salvage my original tail, go to surgery to put it on, unable to put the tail on successfully, I'm just hit with the tail

**Comment by optimumtact** [comment]
you were no longer a cat

**Comment by Bod9001** [comment]
yep, I think it's something to do with the  ash Drake Gibbing me? Maybe?

**Comment by YPOQ** [comment]
Doesn't seem to happen anymore probably due to #32101
