### ISSUE TITLE
You can't place pipes by clicking on lattices 

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#32193]
See #32034 but replace catwalks with lattices

**Comment by DoctoreMad** [comment]
I seriously hope this is a joke label

**Comment by ShizCalev** [comment]
Should honestly just tack this onto the other issue instead imo

**Comment by praisenarsie** [comment]
not a joke label

**Comment by BeeSting12** [comment]
what does this label even mean

**Comment by PKPenguin321** [comment]
It means it's easy to fix so it would be a good issue to fix if you've never tried fixing issues before
