### ISSUE TITLE
Vampires cannot drain simple animals of blood

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#32194]
I know it's because they have no blood as defined in the code but I should be able to drain Ian's blood or start a farm of corgi puppies to feed myself

**Comment by Shadowflame909** [comment]
if vampires kill ian, we need an ian vampire!!

**Comment by KorPhaeron** [comment]
Feature request, WYCI, etc

**Comment by KorPhaeron** [comment]
You can farm and sell corgi hides for blood crates from cargo if you are really looking for the most evil way to stay alive possible though
