### ISSUE TITLE
Large amount of toolbelts in meta maint

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#32192]
Issue reported from Round ID: 78059 (Sybil)

There appears to be an abundant amount of toolbelts in the maint behind botany and theater on MetaStation. Found up to five on one round.

**Comment by praisenarsie** [comment]
not a bug, it could be rng or the clown stealing them all

**Comment by ShizCalev** [comment]
Loot spawners just felt like giving out some tools.
