### ISSUE TITLE
Thermite aint working.

### ISSUE THREAD

**Issue by B00tz** [tgstation/tgstation#32207]
Problem Description: Thermite when applied to a wall cannot be ignited.

What did you expect to happen: For the Thermite to ignite burning the wall.

What happened instead: Did not ignite even when tested with various different methods of ignition. Welders, igniters, lighters both cheap and zippo.

Why is this bad/What are the consequences: A chemical that is used in the most dire of situations is now null. This buffs any antag that relies on base building.

Steps to reproduce the problem: Apply Thermite to a wall and attempt to ignite it.

Server: Bagil

Revision: 
Server revision compiled on: 2017-10-28

The following pull requests are currently test merged:
#32174: 'Dullahan Fix' by KorPhaeron at commit 2730b6
#32204: 'Revert "Map config cleanup (#32132)"' by MrStonedOne at commit 532b54

Based off origin/master commit: 21bb39

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): I was playing as a skellyboi not sure if that had anything to do with it.

**Comment by Bawhoppen** [comment]
Normal type of wall?

**Comment by Dorsisdwarf** [comment]
Did you put enough thermite on it? I saw thermite used to melt down rwalls just the other day

**Comment by praisenarsie** [comment]
@ninjanomnom

**Comment by ninjanomnom** [comment]
So the problem is that closed turfs don't call the attackby parent when attacked which means the signal isn't sent to the thermite. Thermite currently works on floors and I'll have a turf attackby refactor up soon to deal with walls.
