### ISSUE TITLE
Staff of ress kills Dullahans (because it tries to give them a head)

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#32208]
Round ID: 78088
Pubbystation

**Comment by praisenarsie** [comment]
feature

**Comment by ShizCalev** [comment]
Hahahahaha

**Comment by PKPenguin321** [comment]
healing staff killing unholy creatures actually should be a feature tbh

**Comment by ShizCalev** [comment]
^

**Comment by KorPhaeron** [comment]
Feature

**Comment by nicbn** [comment]
Completely-not-a-feature is now a feature because lazy ass coders

**Comment by PKPenguin321** [comment]
welcome to coderbus

**Comment by KorPhaeron** [comment]
you're free to come up with a way to change it if you'd like

**Comment by nicbn** [comment]
Just reopen this
