### ISSUE TITLE
Revival stasis and zombie glitch

### ISSUE THREAD

**Issue by JohnFuckingMooney** [tgstation/tgstation#32203]
[Directions]: #78071 I was a ling and killed by zombies, before I came back as a zombie I activated revival stasis, after about a minute I heard the noise and got the text to say that I came back as a zombie but I was still on the ground and my screen looked as if I was in crit, when I tried to activate the revival it said that "we are already reviving" even after the prompt said that I was able to revive. My character also kept making the noises of a zombie.

*Side note, sorry if this does not follow the correct format, I have never have done one of these before

**Comment by JohnFuckingMooney** [comment]
Just as a side note I noticed that someone else described being in a similar state with a previous glitch https://github.com/tgstation/tgstation/issues/7641, whilst the glitch is different the way the player us left is similar

**Comment by Xander3359** [comment]
I have not been able to reproduce this, revival stasis works as intended and you can unzombify yourself with Anatomic Panacea.
If you ever run into this bug again please report it.
