### ISSUE TITLE
Mutant parts dont show up on severed heads

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#32229]
Cat ears, lizard horns, etc

**Comment by Mooshimi** [comment]
Still a thing, this is a beheaded felinid in thunderdome. The ears didn't drop, and they can't be seen on the head.
![image](https://user-images.githubusercontent.com/85910816/135705581-d14a2f48-033e-48dc-a138-75a35281bbf4.png)

**Comment by Mooshimi** [comment]
Ears now drop on the ground

**Comment by SuperNovaa41** [comment]
still an issue
