### ISSUE TITLE
dullahans can't hear departental radios

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#32228]
I was playing a dullahan warden and was having serious issues trying to get sec conms to work. Eventually I gave up and asked to be race changed. Tried it with bounced, wall mounted, and leaving a radio headset by my head, but nothing worked. People could hear me just fine but I couldn't hear anything aside from common.

related: I had cat ears

**Comment by KorPhaeron** [comment]
For the record I could not hear your wall mounted radio as a skeleton either

**Comment by newfren** [comment]
For the record - when my head was being held by the CMO I could hear medical comms.

**Comment by ChangelingRain** [comment]
for the record, dullahans can't wear headsets, because their head is an object with no clothing slots.

**Comment by YakumoChen** [comment]
That isn't the issue though, since headset slots don't matter for wall mounted or bounced radios, or just being on the same tile as a radio in general

**Comment by KorPhaeron** [comment]
Can't reproduce.

@YakumoChen How did you build a wall radio that could tune to security in the first place?

**Comment by YakumoChen** [comment]
@KorPhaeron admin fiddled with it

**Comment by KorPhaeron** [comment]
They spawned it wrong then (which explains why I couldnt hear it as a skeleton eithe probably tried manually var editing freq rather than setting free range
