### ISSUE TITLE
Atmos filter [B]roke and more 

### ISSUE THREAD

**Issue by jericho140** [tgstation/tgstation#32239]
Issue reported from Round ID: 78122 (Sybil)

there's a lot more to this under the surface im sure of it so
here's the scientific method that scratches the surface

![atmos1](https://user-images.githubusercontent.com/969922/32149472-0aef826c-bcfd-11e7-805a-34a69384eafe.PNG)

we begin with a T junction setup with everything ready to be wrenched

![atmos2](https://user-images.githubusercontent.com/969922/32149478-1e6218dc-bcfd-11e7-92be-cde0f1c21ace.PNG)

we wrench everything but the gas filter, as you can see the gas filter is pointing to the right with the split going upwards

![atmos3](https://user-images.githubusercontent.com/969922/32149481-2c25abfa-bcfd-11e7-9acf-6edc77ac3d77.PNG)

as we wrench we see that it's trying to attach to a previously hidden pipe that isn't even facing in the right direction

![atmos4](https://user-images.githubusercontent.com/969922/32149485-3fe7725e-bcfd-11e7-8b81-d14cb4d92418.PNG)

as we remove the pipe we see that the filter has now "corrected" itself and is facing the opposite way

![atmos5](https://user-images.githubusercontent.com/969922/32149492-58b9d510-bcfd-11e7-94d3-e85f6b1b8ae1.PNG)

so we plug in a full (4559kPa, default roundstart cannister) can of O2 into it, the results are pretty much as expected

![atmos6](https://user-images.githubusercontent.com/969922/32149499-70208014-bcfd-11e7-998a-27c5e5bd41e7.PNG)

as we turn on the filter however, we notice that we now have more pressure than we started with, spoopy

![atmos7](https://user-images.githubusercontent.com/969922/32149511-8d097c26-bcfd-11e7-88bb-6e2b6a93d150.PNG)

we have some leftover pressure so if we start filtering oxygen it should fill up the split pipe even a little, right? nope. It's pushing the air through, but at a snails pace

Sybil Round ID : 78124

![atmos9](https://user-images.githubusercontent.com/969922/32149705-854be322-bd00-11e7-8fb6-16857588d241.PNG)

because it's not scientific unless you do multiple tests, a repeat of the previous task after the server has restarted shows that now it pushes the gas properly (again this was 1 roundstart tank at 4559 kPa), switching the filter to the split however reveals that we now have twice the pressure we started with, double spoopy.

**Comment by duncathan** [comment]
weird, I wonder why. interesting bug I'll take a look

**Comment by jericho140** [comment]
I only managed to test the filter before sleep punched me to unconciousness, I'll let you know if I find anything else broken with atmos but the fact that the filters seem to have a mind of their own could be gamebreaking if the roundstart filters decide to bug (which I don't think has happened yet but I'll do some testing and let you know.)

**Comment by duncathan** [comment]
thanks, I appreciate it.

**Comment by jericho140** [comment]
while we're on the topic, oxygen and plasma will now burn inside pipes, I'm guessing  this is intentional?

**Comment by jericho140** [comment]
did a bit more testing, it looks like filters and mixers try to correct themselves by the split always in "one direction"
![capture](https://user-images.githubusercontent.com/969922/32195640-c53c59e8-bdb5-11e7-96c8-c4327a0d1d83.PNG)

i put down one of every direction for them, and they all turned so that the split would always be facing up if the arrows were pointing left

**Comment by duncathan** [comment]
Reactions happening inside pipes is intentional and has been so for a while. Thank you for the continued testing tho this will make my life much easier while trying to fix

**Comment by SpaceManiac** [comment]
As far as I can tell #37982 has fixed the issues with filter construction changing orientation.

The reason you have more pressure than you started with is because you have filled a smaller volume. The single pipe between the filter and connector has a much smaller volume (70 liters) and requires many fewer moles of gas to reach the same pressure compared to the canister (1000 liters).

Closing, but feel free to reply if you think this is still a bug.
