### ISSUE TITLE
When you monkeyize a species with NOBREATH, the resulting monkey has no lungs

### ISSUE THREAD

**Issue by nicbn** [tgstation/tgstation#32237]

**Comment by WJohn** [comment]
Does this apply to ash walkers, too?

**Comment by PKPenguin321** [comment]
I mean, this makes sense if you think about it

**Comment by nicbn** [comment]
I don't think the problems is the lungs.
If a dullahan gets transformed, the monkey still holds his head.

**Comment by KorPhaeron** [comment]
@WJohn @nicbn Had a vampire ling ahelp the same thing

**Comment by nicbn** [comment]
Seems to have fixed itself but I'm not sure

**Comment by Nickkoranda** [comment]
Seems fixed
