### ISSUE TITLE
Dullahans mouth is in their bodies

### ISSUE THREAD

**Issue by nicbn** [tgstation/tgstation#32236]
They can eat using their bodies
They can drink using their bodies
They can play russian roulette- ok you got it.

**Comment by deathride58** [comment]
Eating and drinking via body makes sense, since eating with the head would just result in the food dropping onto the ground unless it's on the body.

**Comment by nicbn** [comment]
They shouldn't eat.

**Comment by GoldenAlpharex** [comment]
This is a non-issue to me, the only thing I'd consider needing to be fixed is the fact they can shoot their "head" with the russian roulette revolver, and that should be in a separate issue, as that's a Russian Revolver issue and not inherently a Dullahan issue.
