### ISSUE TITLE
Screwdrivers on trays lose their colour

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#32240]
[Directions]: # Place a screwdriver on a tray. Observe as the tray sprite has a bone white handled screwdriver where your original screwdriver was probably brown or whatever.
http://puu.sh/yagcC/b49e31094a.png

**Comment by PKPenguin321** [comment]
Effectively a dupe of https://github.com/tgstation/tgstation/issues/31871

**Comment by ShizCalev** [comment]
Duplicate of #31871
