### ISSUE TITLE
Spatial Gateway abuse can allow servants limited access to reebe spawn

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#32245]
The lattice/catwalk with the arrows isn't marked to reject servants, with spatial gateways spawning in front of the target, allows servants to break into the space around the crew spawn.
![](https://file.house/1p1m.png)

**Comment by Xhuis** [comment]
There's actually a failsafe in place for this that warps any servants who walk in that area back to their own spawn.

**Comment by francinum** [comment]
this does not apply to the walls after fabrication and the lattices around said walls, I said limited access for a reason.

**Comment by Xhuis** [comment]
Every time.

**Comment by dragomagol** [comment]
RIP reebe
