### ISSUE TITLE
Smoke Machine and Chem Dispenser can't be screwdrivered.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#32268]
This disallows the use of the RPED.

@Robustin

**Comment by Robustin** [comment]
I made it like the chem dispenser, which also uses components and apparently can't be screwdrivered.

If someone could direct me to code for machines that enables this feature I could add it to the chemistry machines I guess.

**Comment by alexkar598** [comment]
It was done on the chem machine to prevent greifing

**Comment by YakumoChen** [comment]
the default chem machine doesn't use components
