### ISSUE TITLE
If you hit a (jani)borg while buckled to it, it shifts your sprite down.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#32261]
![2017-10-30_19-52-38](https://user-images.githubusercontent.com/31222036/32192426-0aa496d0-bdac-11e7-8091-c106600f1b74.png)

It fixes itself by moving (and probably unbuckling)

**Comment by praisenarsie** [comment]
![2017-10-30_19-58-05](https://user-images.githubusercontent.com/31222036/32192642-af792ae0-bdac-11e7-9662-d572db15ad8d.png)
this managed to happen too, the borg was pushed.

**Comment by PKPenguin321** [comment]
I think this is the case for most vehicles, since attacking changes your pixel_x and pixel_y and afaik vehicles only update it when you buckle in
