### ISSUE TITLE
Security records console gives the front sprite for the side view.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#32267]
![2017-10-30_21-20-41](https://user-images.githubusercontent.com/31222036/32196649-4979de9e-bdb9-11e7-8507-087f3fea2a45.png)
Server revision compiled on: 2017-10-30
b2a4c7 

Local

**Comment by YakumoChen** [comment]
It's the same bug for character preferences, it's just coded badly for '''performance'''

**Comment by AutomaticFrenzy** [comment]
fixed in #32332, can be closed
