### ISSUE TITLE
Vampires drinking blood from containers don't get more blood.

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#32278]
Seems kind of inconsistent.

**Comment by JJRcop** [comment]
Sorry, do you mean reagent containers or another kind of container?

**Comment by JJRcop** [comment]
Unable to reproduce

**Comment by AnonymousNow** [comment]
Tested example was a bucket o'blood.

**Comment by AnonymousNow** [comment]
Reproduced. Specifically it was monkey blood, from a bucket; it also caused a bunch of toxin damage.

**Comment by JJRcop** [comment]
Food processor doesnt't transfer blood data properly. https://github.com/tgstation/tgstation/blob/75f35591b5b6bee40fe18fb986024c8237a119dc/code/modules/food_and_drinks/kitchen_machinery/processor.dm#L120-L149

This can be resolved by taking cues from this proc https://github.com/tgstation/tgstation/blob/75f35591b5b6bee40fe18fb986024c8237a119dc/code/modules/mob/living/blood.dm#L117-L154
