### ISSUE TITLE
[BUG] [Boxstation] telecomms

### ISSUE THREAD

**Issue by Keofox** [tgstation/tgstation#32286]
On long rounds, telecoms are always discharged and communication is lost. 
The reason for this is the lack of wires going up to SMES
To fix this, engineers need to lay the cable to SMES manually.
Please fix that map bug

**Comment by SgtxRootbeer** [comment]
I think that's by design, as there's a similar situation on meta

**Comment by ShizCalev** [comment]
Intended.
