### ISSUE TITLE
Spooky ghosts can pull people onto vehicles

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#32287]
Issue reported from Round ID: 78175 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

See title,
Discovered that ghosts can click-drag people onto things like the janicart for loads of SPOOKY FUN.
(Probably works for other vehicles too!)

2SPOOKY/FUN things you can do: 
Kidnap people from maint into an autism fort, drag the HoP from behind his desk, keep the janitor from leaving the custodial closet, and certainly more.

**Comment by Supermichael777** [comment]
can you drag shit as a ghost?

**Comment by GravitronBlue** [comment]
You don't end up dragging them, you just teleport people onto the cart/vehicle, this ends up only works on mobs.

**Comment by nicbn** [comment]
bug of the year?

**Comment by davethwave** [comment]
You can also drag people onto borgs but you're ghost guy has to be within touching distance for it to work.

**Comment by calzilla1** [comment]
IM GONNA TAKE YOU FOR A RIDE
