### ISSUE TITLE
Fusion bombs

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#32294]
I don't know if this could possible works or if it can be considered a issue but if it does it might need to be nerfed somehow.
You have a full canister of plasma at normal or high temp then another canister of tritium, use a connecter to mix them or some other method, then heat them up enough to start a fusion in the canister, then get a handheld plasma tank or whatever they are called to almost full capacity and then put one of them in the canister thats undergoing fusion inside, then if it works the fusion process starts in the small canister that your going to use for the bomb bringing it to a higher temp and pressure than any normal burn mix. Cool down a oxygen tank/canister and fill it up via air pipe siphoning then you have a possible op fusion bomb in your hands

**Comment by CPTANT** [comment]
The tank will just burst due to overpressure.

**Comment by banthebantz** [comment]
I don't see the issue because bomb cap exists and Freon let you make 1000 tile range bombs anyway

**Comment by duncathan** [comment]
>freon

lmao we killed that shit dude

but yes, the tank should burst in your face due to high pressures. fusion in a tank is very unsustainable. please do not write issue reports for hypothetical issues which you have not produced live.

**Comment by davethwave** [comment]
Okay, sorry
