### ISSUE TITLE
Glitch with golem mutagion

### ISSUE THREAD

**Issue by JohnFuckingMooney** [tgstation/tgstation#32293]
[Directions]: #78179 I ate some golem mutagion and then the following appeared in the chat box Allowing golem type adamantine golem
Allowing golem type plasma golem
Allowing golem type diamond golem
Allowing golem type gold golem
Allowing golem type silver golem
Allowing golem type plasteel golem
Allowing golem type titanium golem
Allowing golem type plastitanium golem
Allowing golem type alloy golem
Allowing golem type wood golem
Allowing golem type uranium golem
Allowing golem type sand golem
Allowing golem type glass golem
Allowing golem type bluespace golem
Allowing golem type bananium golem
Allowing golem type runic golem
Excluding golem type clockwork golem servant
Allowing golem type clockwork golem
Allowing golem type cloth golem
Allowing golem type plastic golem
I have no idea what caused this, I have never seen it appear before and I do not think anything actually triggered it

**Comment by AnturK** [comment]
Already fixed.
