### ISSUE TITLE
Meteor Shield doesn't protect against pumkpin meteors.

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#32295]
Issue reported from Round ID: 78188 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

As the title says, meteor shielding doesn't stop pumpkin meteors. Several of the meteors passed right past several shields.

**Comment by KorPhaeron** [comment]
Spooky

**Comment by WJohn** [comment]
this halloween is hilariously broken good thing we're throwing all this shit out tomorrow

**Comment by KorPhaeron** [comment]
I just tested this, worked fine.
