### ISSUE TITLE
[HIGH PRIORITY] Machines (with components) do not work at all.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#32305]
Confirmed to be a tgstation issue.

Related issues:
https://github.com/HippieStation/HippieStation/issues/4468
https://github.com/HippieStation/HippieStation/issues/4469
https://github.com/HippieStation/HippieStation/issues/4463

Tested locally.

Occurred in some pr after https://github.com/tgstation/tgstation/commit/fc92519d451935ecca345d7ffac1ec83e978e936

**Comment by optimumtact** [comment]
if you don't know, then don't report it

**Comment by GuyonBroadway** [comment]
The components system in general is broken.

**Comment by SpaceManiac** [comment]
Bisect points to d088549da04120f2a20db2a13571c68fd6f7f9e8 (#32155)
