### ISSUE TITLE
Can't produce brown gas

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#32315]
@as334 

Its already undocumented that you need no2 as a catalyst but even when I've got a full 50,000c+ canister with oxygen/nitrogen/no2 it never reacts.

Ironically the only way I've seen it exist is when plasma+tritium fuses in a canister which has none of the required gases.

**Comment by RemieRichards** [comment]
The required temperature to produce brown gas is 149,260 degrees.
50,000 is not enough.

**Comment by RemieRichards** [comment]
also plasma fusion produces waste products, including brown gas as waste, so it is intended for it to appear during fusion.

```
	//Fusion produces an absurd amount of waste products now, requiring active filtration.
	cached_gases[/datum/gas/plasma][MOLES] = max(cached_gases[/datum/gas/plasma][MOLES] - plasma_fused,0)
	cached_gases[/datum/gas/tritium][MOLES] = max(cached_gases[/datum/gas/tritium][MOLES] - tritium_catalyzed,0)
	cached_gases[/datum/gas/oxygen][MOLES] += oxygen_added
	cached_gases[/datum/gas/nitrogen][MOLES] += waste_added
	cached_gases[/datum/gas/water_vapor][MOLES] += waste_added
	cached_gases[/datum/gas/nitrous_oxide][MOLES] += waste_added
        cached_gases[/datum/gas/brown_gas][MOLES] += waste_added
```

And if it was hot enough, the waste produced could turn into more brown gas as all the gas requirements for brown gas are also present.

**Comment by Robustin** [comment]
Ah I missed the definition for T0C and thought 40,000 was the minimum.

Jesus christ that's an obnoxiously high heat value to hit.

**Comment by RemieRichards** [comment]
Apparently so.
If you want some it may be better to obtain it as waste from plasma fusion, and filter it out into a canister.

**Comment by Robustin** [comment]
Perhaps, but the waste products of fusion come out so hot its useless. Both H-N and Stimulum can't be hotter than the sun if they're going to be used for their intended purposes. 

Well that explains what I'm missing anyway, aside from the undocumented no2 catalyst in the changelong its all working as designed.

**Comment by davethwave** [comment]
@Robustin  What I would do is to make a place for the waste gas to go like a atmos gas holding type of setup with cooling for the gasses as it feeds in as their super heated, probably a space loop kinda set up or bluespace tier coolers set at max cooling. Then I would set up the output to use a scrubber and then pick and choose what gas you want that's mixed together via gas filter with the filtered side being output and the rest would stream back into the structure you make to hold the gas.

**Comment by davethwave** [comment]
Also, I've been able to achieve fusion inside air pipe before so as a suggestion perhaps don't use a burn chamber, instead pump the two gasses into separate pipe networks, then once their full of their respected gasses, then connect the two and use that for your brown gas production.

**Comment by Robustin** [comment]
As it stands I can barely get all the gases before the round is over so getting a cooling loop up is... challenging.
