### ISSUE TITLE
Nar-Sie is capable of horrifying inanimate objects.

### ISSUE THREAD

**Issue by RandolfTheMeh** [tgstation/tgstation#32324]
Issue reported from Round ID: 78238 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

An issue I ran into a couple times whilst using one of the lesser used talismans in blood cult

Talisman of Horror can be used on _anything_. This makes using it on anyone who isn't standing perfectly still hard as balls, and you end up getting messages like "You disturb the floor with visions of madness!", since you misclick, or you're moving or he's moving. All in all very difficult to use the talisman whatsoever now.

**Comment by WJohn** [comment]
👻  📦😨  👻
