### ISSUE TITLE
Deconstructing a security camera creates an extra camera assembly

### ISSUE THREAD

**Issue by kingofkosmos** [tgstation/tgstation#32335]
Deconstructing a security camera which is already at roundstart on the map works fire.
But if you construct a security camera, install it on a wall, then decide to deconstruct it, it creates a new security camera assembly on top of it which you cannot interact with.

Steps to reproduce:
1. Make a security camera assembly
2. Install it completely on the wall
3. Decide to deconstruct it: screwdriver it open, cut wires, weld it
4. And notice after welding how the other security camera pops on top of it

![capture](https://user-images.githubusercontent.com/5420151/32309043-a439dc56-bf91-11e7-93f8-e80272de3279.PNG)
![untitled](https://user-images.githubusercontent.com/5420151/32309057-bfb8e206-bf91-11e7-9263-127662cb81fd.png)

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/626302c1bf4bb2a37aa6508145751f6c4c78696d/code/game/machinery/camera/camera.dm#L254
