### ISSUE TITLE
Burning objects do not set the plasma on fire.

### ISSUE THREAD

**Issue by Keofox** [tgstation/tgstation#32345]
Just watch 
![bugge](https://user-images.githubusercontent.com/12028974/32327754-b7720e68-bfe8-11e7-9cf9-ee616a716b21.jpg)

**Comment by Marflowerose** [comment]
Having issues getting anything to set plasma on fire, lighters, igniters, welders etc. Even +1000C plasma+oxy mix won't start burning

**Comment by Jalleo** [comment]
This has been mentioned in coderbus yesterday. I dont know what has caused this.

**Comment by Jalleo** [comment]
Also dupe this is a worse report please close.

**Comment by Cyberboss** [comment]
Duplicate of #32337
