### ISSUE TITLE
Beam rifles spaz the hell out when aiming at titanium walls due to their reflective nature.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#32343]
![](https://i.imgur.com/aCJzAql.png)
![](https://i.imgur.com/n6M53Mh.png)

This, combined with the totally unecessary "stepper vs instant" modes as well as being able to toggle between no zoom, locked directional, free directional, and center modes makes this gun feel extremely messy. Just have it be on instant center mode and have that be the only option, remove the action button abilities that only serve to make using this thing completely nauseating.

@kevinz000

**Comment by GunHog** [comment]
I disagree entirely with removing the zoom options. It was singular mode before, and it was rather difficult for me to use well. As for Titanium walls, things can get really interesting when you try to aim this thing within a shuttle cockpit or other small room.

**Comment by WJohn** [comment]
What possible benefit is there to stepper mode which repeatedly jolts your screen as it gradually grows to the enormous view range? Or why would you want to use free directional which prevents you from even being able to fire at anything close range because the sensitivity becomes unmanageable? Why not just have it always be instant centered view which doesn't throw you off or fight you?

**Comment by GunHog** [comment]
Stepper mode: So I can see where I am aiming in relation to myself, when using directional modes. It is helpful for noobs that have not memorized the distance provided by the scope.

I play using the default 32x32 screen size, not full screen. So, I do not normally see the expanded view in center mode. Locked directional is great for shooting, and free directional is great for scouting or following a distant target. 

So, the short of it is simply that my preference is different from yours. You only favor the one mode, and thus see the others as unnecessary. Instant Center mode does not work properly if you are not playing on full screen. To me, it just looks as if my icons disappear.

I am happy that Kev tried to accommodate the most players with this. The first version without stepper mode was jarring and disorienting to me. When I want to use the gun at close range, I just turn off the scope! Please do not take away these options. They seem messy to you, but they are extremely helpful to me.

**Comment by WJohn** [comment]
At the very least then make them way less jolting, because both stepper mode and center mode horribly shift you screen before it snaps back into place (with stepper mode doing it a dozen times all at once and is absolutely hideous to look at). Free directional's sensitivity is absolutely monstrous and you can't move your mouse to anywhere within like 20 tiles of yourself without it flinging your camera in the other direction.

**Comment by kevinz000** [comment]
stepper i can deal with throwing out
every other mode has its own use
i don't see what the issue with high sensitivity is.

**Comment by kevinz000** [comment]
the only bug here is the reflection which i'll be dealing with in the next projectile refactor which i'm already working on.
