### ISSUE TITLE
Gas Filter Issues

### ISSUE THREAD

**Issue by Gouty** [tgstation/tgstation#32340]
I have had this issue occur a few times now.

Gas filters cease functioning, particularly when pressures are high.  The most common scenario in which this occurs is on the Supermatter (particularly on meta), if the pre cooling loop filter (the first one out of the SM chamber) is set to plasma and the canisters are filled, which is possible since the recent atmos changes, then the filter ceases to function and no gas travels through (which I guess is expected behaviour).

The problem comes when the backed up filter is bypassed or set to "nothing", the gas travels through the cooling loop just fine, but the filters are non functional (pressure is shown before filters but 0kpa after filters)

I managed to fix this temporarily by disconnecting and reconnecting the filters, but after a couple minutes they failed to function again.

This is a pretty big problem, as if it occurs then it is much just a matter of time before the SM delaminates.

**Comment by Morgan-Edlund-1516** [comment]
Check and make sure the pipe you're filtering to isn't at max pressure; filters no longer can pump infinite pressure into a pipeline.

**Comment by ShizCalev** [comment]
@duncathan

**Comment by Gouty** [comment]
Same thing happened again just now on bagil straight after the SM was activated for the first time, disconnecting and reconnecting the filter fixed it for a couple seconds.  It could also have been an issue with the air injector outside the station as I noticed that there was no plasma coming out of it and that the pressure was very high before it

**Comment by Gouty** [comment]
I just found out that air injectors can be controlled (for some reason I thought they were passive) but the it definitely was on and outputting to max when the problem occurred.
