### ISSUE TITLE
Blob is completely unbalanced now.

### ISSUE THREAD

**Issue by scrubs2009** [tgstation/tgstation#32365]
Making the blob a side antag that spawns an hour into the shift means that the crew already has access to x-rays, advanced healing viruses, hulk, lavaland weapons, and other loot before the blob even spawns. This means that unless you happen to get a crew that has done nothing all shift you will get curbstomped 100% of the time. For the love of god who let kor do this?

**Comment by WJohn** [comment]
As if blob was ever balanced to begin with.

**Comment by scrubs2009** [comment]
At least before both the blob and the crew had a chance of winning. Now the blob has 0 chance. There is no defense against 3 crew members with x-rays aside from rerolling your type and hoping you get Electromagnetic Web.

**Comment by KorPhaeron** [comment]
I've spawned blob roundstart (event button) and near roundstart (TC trades) and science gets xrays at ~16 minutes. It only takes cargo ordering a single crate of shotguns and they hit max weapons tech.

https://atlantaned.space/newSS13tools/stats/monthlyStats.php?year=2017&month=09

September blob had an 11% winrate

https://atlantaned.space/newSS13tools/stats/monthlyStats.php?year=2017&month=10

28% in October

Xrays and RD taking no time or resources are both big problems but please don't pretend I trashed some perfectly balanced mode and created the issue
