### ISSUE TITLE
DNA vaults can be used infinitely

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#32373]
As the title says you can infinitely use DNA vaults, though not in the way of getting infinite selections of powers just by building the thing. If you build another DNA vault after building and managing to fill up the first one and getting your free power you can build another one and get another free power and you can do this as many times as you like. This could be a feature, but you can do the same thing by building a DNA vault, completing it, and then destroying it by hitting it. the parts will drop and you'll be able to rebuild the entire thing and keep your upgrade and get another upgrade to go along with your first one, and you can do this as many times as you like so long as you have the patience.

**Comment by Kaptinalexander** [comment]
Honestly though the only way to do this is to get ALL the DNA points on ONE scanner. It took me over an hour on a low pop round to do this as a traitor CE with captain level access. So the likely hood of it happening when a normal crew decides to do this probably small.
