### ISSUE TITLE
Heating reagent containers needs to be generalized

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#32372]
Heating beakers, drinking glasses, and piles of chemicals on the floor all have the actual heating process coded their own way.

[Piles](https://github.com/tgstation/tgstation/blob/e7da251e4685c8de5c5363eb97ce9ecf77aafbfc/code/game/objects/effects/decals/cleanable.dm#L45)
[Drinking glasses](https://github.com/tgstation/tgstation/blob/d3dcc118ecb5f5410de684b1bb46289f8066ab23/code/modules/food_and_drinks/drinks/drinks.dm#L92)
[Glass beakers](https://github.com/tgstation/tgstation/blob/b83d77711999124fb33de984724653039a7e41e2/code/modules/reagents/reagent_containers/glass.dm#L92)

Notice slight differences between how these are all coded. For example, you can't heat reagents in a beaker to be hotter than the thing you're using to heat it, but you can in a drinking glass (meaning you could turn chems in a regular glass into magma with a match, but not in a beaker), which is a bug. Generalization would fix this.

**Comment by WJohn** [comment]
Not to mention how chems do not change temperature with high body heat or ambient room temperature. Shouldn't the reagents in a beaker get really hot if they're caught in a boiling hot room?

**Comment by Jalleo** [comment]
Requesting FUCK tag.
