### ISSUE TITLE
EVERYTHING IS BLOOD STAINED

### ISSUE THREAD

**Issue by Togopalis** [tgstation/tgstation#32389]
https://i.imgur.com/OfgE6RC.png

This happens when examining anything, including objects that are not covered in blood

Test merges are
 #32371: 'SSoverlay improvements and tweaks' by MrStonedOne at commit 5494ff
#32311: '[wip]Component Forensics' by kevinz000 at commit 7f38bf
#32183: 'Ling datum antag standarization.' by AnturK at commit fc400a

**Comment by praisenarsie** [comment]
**BLOOD FOR THE BLOOD GOD, SKULLS FOR THE SKULLTHRONE :angry:**

**Comment by ShizCalev** [comment]
#32311 is the cause.

**Comment by Ratvar** [comment]
break this bug on hellowheeeen again
