### ISSUE TITLE
Guests still can connect regardless of config setting.

### ISSUE THREAD

**Issue by McBawbaggings** [tgstation/tgstation#32388]
https://github.com/tgstation/tgstation/pull/32384
This didn't fix it, apologies. I have no idea why this is the case.

**Comment by Cyberboss** [comment]
Did you test this locally or live? Servers haven't been updated yet

**Comment by optimumtact** [comment]
![](https://file.house/MOzc.png)

**Comment by McBawbaggings** [comment]
apologies, we have an autoupdate system and i made the assumption.
no been quite on the ball today
