### ISSUE TITLE
Supermatter destroys my ears

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#32385]
What kind of madman would add a sound to the supermatter that makes it have a loud as shit high pitched wailing noise from the depths of hell?

**Comment by Qustinnus** [comment]
doesnt seem like an issue to me. i think youre just sensetive. Theres a volume slider on PCs luckily enough, though.

**Comment by Repukan** [comment]
Lower your volume you sensitive faggot

**Comment by YakumoChen** [comment]
It's almost as low as my volume goes already, it shouldn't be this loud compared to every other sound in the game.

**Comment by WJohn** [comment]
Yeah SM being eaten by a singularity, for example, is ridiculously, HORRIFICALLY loud. Needs to be less ear-rape.

**Comment by Repukan** [comment]
Did you not read the flavor text that accompanied such event.

**Comment by Ratvar** [comment]
Add flavour text "earrape" to every floortile to justify earrape every time you walk on floor when

**Comment by Qustinnus** [comment]
will do @Ratvar

**Comment by YakumoChen** [comment]
I'm not talking about it exploding though, I'm just talking about the general ambient ringing that it emits constantly now.

**Comment by WJohn** [comment]
Oh yes, I've noticed that and showers to be pretty loud, too.

**Comment by praisenarsie** [comment]
@WJohn that's the portable generators' sounds. anyway the reason why it's so high pitched is that the looping of the sound is repeated and stacked on top of each other so you'll hear the supermatter engine sound like 3 times at once.

**Comment by AnonymousNow** [comment]
Have to second, it's a grating noise.

**Comment by RandomMarine** [comment]
Looks like engineering's earmuffs have a legit use now.

**Comment by vuonojenmustaturska** [comment]
Yeah i can't look directly into as a ghost either.

**Comment by jughu** [comment]
![image](https://user-images.githubusercontent.com/14280283/32429902-12c32c52-c2cd-11e7-8797-2074039c492d.png)

**Comment by lightcat** [comment]
Alot of you are just coming off as rude dicks and assholes.

The entire game is fine but when turning the sound down you literally can almost not hear a thing and the shit still ear rapes you. I **will admit I have sensitive ears so I all ready keep the sound low so when something with my all ready low sound blows one of my headphones there is a problem.**

I'm not sure if this is still an issue on this server as I play on another server that forks off of this main code but if its still as loud as it originally was fix that shit.

**Comment by AnonymousNow** [comment]
That's all well and good, jughu, but then I can't hear the game properly.

The supermatter sound is comparitively loud and shrill, overpowering everything else in the game in my ears.

**Comment by Mercenaryblue** [comment]
We only need to lower the volume of the supermatter.

Easy fix.

**Comment by lightcat** [comment]
Close this issue its no longer a problem.

**Comment by YakumoChen** [comment]
@lightcat tell me what fixed it and I'll close

**Comment by YakumoChen** [comment]
@repukan @jughu get the fuck out of my issue and stop shitposting on github if all you're going to do is shit up everything with retarded useless and uninformed shit, your posts don't help and don't contribute to the actual issue, nor fix it, thanks.

**Comment by Qustinnus** [comment]
![image](https://user-images.githubusercontent.com/20987591/32467507-18d1b428-c34b-11e7-821b-bdeb3e95c0d9.png)

**Comment by YakumoChen** [comment]
@Cheridan can I get some shitposting off of my issue because he lack of moderation makes it toxic to use this tool

**Comment by Qustinnus** [comment]
![image](https://user-images.githubusercontent.com/20987591/32469788-9eeecd58-c354-11e7-83ef-c82e40ff8cd2.png)

**Comment by AnonymousNow** [comment]
TBF, I don't think I've ever seen a productive post by Repubkan.

**Comment by lightcat** [comment]
It's still ear rapy Must've not been as loud as earlier.

**Comment by Repukan** [comment]
Lmao fucking earlets

**Comment by Qustinnus** [comment]
![image](https://user-images.githubusercontent.com/20987591/32586535-5c3e507c-c503-11e7-968a-af72aac4cdae.png)

**Comment by Repukan** [comment]
Lmao how are shrill noises real hahaahahaha like nigga turn down your volume hahahahaha mute it hahahahahaha

**Comment by Repukan** [comment]
>catplayer is sensitive to noises irl

What level of furry is this.

**Comment by Brimcon** [comment]
Going to confirm the sound is rather shrill, at 40% and at even 5% volume.

**Comment by WJohn** [comment]
For real what the hell, guys? Make shrill ear-piercing noises not shrill, or use a new sound entirely. Nobody likes ear rape, either from the SM passively making sound OR when it's consumed by a singularity.

**Comment by Repukan** [comment]
It's only three people complaining.

Damn earlets lmao

**Comment by Qustinnus** [comment]
its not even that earraping Ive went to check atleast 3 times now

**Comment by WJohn** [comment]
Looks like they were made quieter. It used to be super duper loud. Can close this, then.

**Comment by WJohn** [comment]
Checking on this again no, actually, it's loud as shit. Didn't realize that the SM is quiet when not active, and SO MUCH NOISIER when activated. Definitely still an issue, it needs to be made quieter like in the inactive version. Maybe have it make no noise when inactive, and the volume of the inactive version for when it's activated?

**Comment by Repukan** [comment]
Lmao
