### ISSUE TITLE
AncientStation has wonky lighting on it's betastation.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#32382]
![2017-11-03_13-32-05](https://user-images.githubusercontent.com/31222036/32377445-a4232bbe-c09f-11e7-9984-a4db1f3ca8c6.png)
![2017-11-03_13-31-38](https://user-images.githubusercontent.com/31222036/32377446-a494f136-c09f-11e7-96f6-62911099be1f.png)

probably due to areas and whatnot, also admins deleted every light fixture this round but that doesn't matter

**Comment by Jalleo** [comment]
Areas issue

**Comment by WJohn** [comment]
Easy fix. I can do this.
