### ISSUE TITLE
Titanium airlock glass panels

### ISSUE THREAD

**Issue by Mark9013100** [tgstation/tgstation#32392]
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

Server revision compiled on: 2017-11-03

The following pull requests are currently test merged:
#32371: 'SSoverlay improvements and tweaks' by MrStonedOne at commit 5494ff
#32183: 'Ling datum antag standarization.' by AnturK at commit fc400a

Based off origin/master commit: 910be9

Glass panels installed in a titanium airlock don't show up when closed, however in their opening/closing transition sprites, the panels appear.

**Comment by WJohn** [comment]
I didn't even know we HAD titanium glass airlocks. But I did test this and it's confirmed broke.

**Comment by Anonmare** [comment]
Also as a side note, if you reinforce a titanium airlock - it doesn't have a proper sprite for it so it makes the maintenance panel invisible.
