### ISSUE TITLE
another shuttle arrived on top of the original shuttle, killing everyone

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#32419]
round id: 78340
so a shuttle arrived
it was the super fucking small emergency shuttle
then another one arrived on top, gibbing everyone
after that, the only part of the shuttle that left was the original small cube
when shuttle docked.
afterwards, it arrived at centcomm. no round end.
after some time, that little shuttle fucking left centcomm
and then i think admins triggered round end

**Comment by evsey9** [comment]
is this the master controller fucking up? everything was also SUPER laggy that round

**Comment by Boredone** [comment]
In case it's relevent, second shuttle was the Russian One with the bears and fighting pit.

**Comment by Kerbin-Fiber** [comment]
I think it was that PR that made the shuttle come when too much of the population is dead so that triggered but fucked up really bad

**Comment by AnturK** [comment]
The timer subsystem died somewhere before shuttle docked (not sure if this was first time that round) so that's likely cause of everything going sideways. @ninjanomnom  @MrStonedOne

**Comment by AnturK** [comment]
Actually at second glance it was only possible from emergency mobile port getting force deleted somehow.

**Comment by ninjanomnom** [comment]
I'll need additional information for this to be relevant anymore. I did some basic attempts to reproduce this and wasn't able to make anything interesting happen.
