### ISSUE TITLE
Head of department cloaks dont actually do what they say they do

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#32412]
CE's cloak says it is rad shielded. It is not.
HOS's cloak says it is armored. It is not.
CMO's cloak says it is bio resistant. It is not.
RD's cloak says it is bio resistant. It is not.
https://github.com/tgstation/tgstation/blob/master/code/modules/clothing/suits/cloaks.dm They are not

What you expected to happen: Cloaks to do what they say they do

**Comment by Bawhoppen** [comment]
These are flavor descriptions. Not mechanical descriptions.
Not an issue.

**Comment by RemieRichards** [comment]
>descriptions actively lying.
>not an issue.

Bawhoppen pls.

**Comment by Bawhoppen** [comment]
The RD's for example used to have a special description about how it was resistant to stuff that would basically never be encountered in reality. The descs can just be flavorful descriptions for RP purposes.

Also we shouldn't actually give them any armor because that's the last thing we need.

**Comment by RemieRichards** [comment]
Yes but all of these things ARE encounter-able, so the descriptions are lying.

**Comment by Bawhoppen** [comment]
Just doesn't seem like a big deal. It would theoretically provide so little armor/resistance that balance and logic-wise it might as well not actually exist.

**Comment by Bawhoppen** [comment]
I mean I'm not trying to pick a fight about it. We can just remove those parts of the descriptions and I'd have no problem with that.

**Comment by evsey9** [comment]
does 10% rad resist count as "slight radiation shielding"?
if so, then no, it wouldnt be so little resistance that it might not actually exist because it would provide 100% rad resistance with CE's hardsuit, which is neat

**Comment by Bawhoppen** [comment]
10 is incredibly way too much

**Comment by evsey9** [comment]
oh
what about 5

**Comment by Bawhoppen** [comment]
They're just cloaks. They don't even cover your full body. It needs to be a very minimal amount like 2.5

**Comment by evsey9** [comment]
hmmm how about 3

**Comment by Boredone** [comment]
Looks like its more they didn't get their descriptions changed much when they got swapped from fitting on the exosuit slot to the neck slot, which also included removing any protection they had to make them just cosmetic.
