### ISSUE TITLE
Singulo is literally impossible to contain

### ISSUE THREAD

**Issue by lightcat** [tgstation/tgstation#32413]
This is really an oversight.
 The range of the EMP on the Singulo is 10 which for starters no map you ever had no matter what PA setup can handle this. Not even Delta station with their in game built Singulo/tesala room can handle this. That right there is an oversight.
I'm not even sure if the PA can be out of range.

Why is this a problem?
When the PA get's emp'd it gets its strength increased which feeds more to singulo and it gets free. This entire feature is literally a traitor only feature now.

Possible solution
Reduce or remove the EMP range of the singulo, preferably shrink.

**Comment by RandomMarine** [comment]
None of the PA parts have an emp_act()

**Comment by Cyberboss** [comment]
emp_act on machinery can do this i think

**Comment by praisenarsie** [comment]
why does the singularity even EMP. it's a stupid idea lol

**Comment by banthebantz** [comment]
because radiationz n shieeet

**Comment by deathride58** [comment]
Hippiestation solves this by making the PA immune to EMPs. Could probably steal that.

**Comment by Anonmare** [comment]
Engineering should be mostly EMP-proof

**Comment by McBawbaggings** [comment]
Objects that have wires get them randomly EMPed
You need to override the EMP act on the PA.
https://github.com/HippieStation/HippieStation/pull/1090

I think it was already reported to /tg/ before since it was citadel who told us about it.

**Comment by lightcat** [comment]
Is doing the above the only way its going to get fixed or will there be some kind of code that fixes it? Also I can confirm this is happening through testing on the main TG branch.

**Comment by Cyberboss** [comment]
It shouldn't override emp_act it should use the NOEMPWIRES flag or whatever
it's called
