### ISSUE TITLE
White Ship and Singulo bork the lighting of the white ship

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#32423]
![2017-11-04_20-14-15](https://user-images.githubusercontent.com/31222036/32409094-f96fbcce-c19c-11e7-8a66-60882b0eea5a.png)

**Comment by WJohn** [comment]
I wonder if this is actually more the case of the server lagging out the ass and lighting generally being super unresponsive, more so than the singulo actually breaking that specific area's lighting.

**Comment by ShizCalev** [comment]
Gonna close in a week without another repo
