### ISSUE TITLE
"when an abductor takes someone as a disguise and you look up their security records their role is listed as abductor"

### ISSUE THREAD

**Issue by banthebantz** [tgstation/tgstation#32420]

**Comment by Mark9013100** [comment]
When i show up im just a little sectoid 
But later on i become a mechtoid
You spot me, then i move free
Then i hit a crit on your rookie 
Cant see me cant shoot me
But im fucked when you try to flank me

**Comment by vuonojenmustaturska** [comment]
well, it's not wrong
