### ISSUE TITLE
Xenobio blobs are OP against blobs

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#32439]
>Be xenobio blob
>Can walk on blob tiles
>Nothing the blob can make or do hurts you very much
>Walk up to the blob's various strucutres and smack them while it can't do anything to stop you
>Win the game

**Comment by Anonmare** [comment]
Also no, blob spores and blobbernauts can't help you because they can't damage one another

**Comment by DoctoreMad** [comment]
_lol?_
