### ISSUE TITLE
Slimes coming out of ventcrawling can sometimes move at mach 1.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#32454]
No idea how this happens. There were bluespace tiles but all the vents I crawled into weren't under them.

**Comment by AnonymousNow** [comment]
Funnier in my head than in the game, I imagine.

**Comment by YPOQ** [comment]
I think slimes are supposed to move faster when they get heated up.  Could that be it?

**Comment by ShizCalev** [comment]
Gonna close in a week without a repo
