### ISSUE TITLE
'Who' command not working for admins

### ISSUE THREAD

**Issue by Gouty** [tgstation/tgstation#32468]
Issue reported from Round ID: 78424 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

`Who` command does not work for admins currently

**Comment by vuonojenmustaturska** [comment]
Can you be more specific? Is the "admin-only" functionality broken in some way, or does the verb not work at all?

**Comment by Gouty** [comment]
It works now, how strange.

It wasn't working at all while observing, if I deadmined the regular who did work. It is back to normal now

**Comment by PKPenguin321** [comment]
Issue should be closed then
