### ISSUE TITLE
Ninja Objectives change

### ISSUE THREAD

**Issue by rustledjimm** [tgstation/tgstation#32467]
Issue reported from Round ID: 78424 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Randomly Spawned a Ninja. When I changed it from a Nanotrasen Ninja to a Syndicate Ninja it ended up with double objectives and memory notes for both an NT and Syndicate Ninja.

**Comment by praisenarsie** [comment]
not a bug but still an issue regarding consistency/oversight

**Comment by davethwave** [comment]
It's a double agent then?
