### ISSUE TITLE
Cyrillics do not appears in chat in any form

### ISSUE THREAD

**Issue by BezpalevniyPasan** [tgstation/tgstation#32469]
Issue reported from Round ID: 78429 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])
Like at all. I used to play with friends in local network, so it work for us, in the past.
Now it is not.

**Comment by praisenarsie** [comment]
@Cyberboss gooooooooooooooooooooooooooobchat

**Comment by Supermichael777** [comment]
yeah goonchat has a English only font. Hell it doesn't even support some special characters that are on US/UK keyboards.

**Comment by MoreRobustThanYou** [comment]
@Cyberboss @AnturK  hurry up and fix this so i can finish porting goonchat to yog

**Comment by spookydonut** [comment]
513 will bring native unicode support to fix stuff like this.
