### ISSUE TITLE
Deleting a mob riding a cyborg results in the borg having no .loc and getting teleported to the error box.

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#32463]

**Comment by PKPenguin321** [comment]
Seems more like an admin bug instead of a code bug, except for maybe the rare instance where a mob on a borg is gibbed by a bomb but the borg somehow survives

**Comment by Dorsisdwarf** [comment]
>be ling >ride borg >last resort >borg is sent to the nether realms ?

**Comment by PKPenguin321** [comment]
"Edge Case"

**Comment by Coconutwarrior97** [comment]
Just tested it, no longer reproduceable.
