### ISSUE TITLE
Some, Possibly All Antags Show in Manifest before Joining a Round in Progress

### ISSUE THREAD

**Issue by dentaldam** [tgstation/tgstation#32488]
Round ID : 24184
Server Revision: 92ebc4

Before late joining I checked the manifest and noticed it showed under the Miscellaneous section on manifest the abductors in the round.
![manifest](https://user-images.githubusercontent.com/33442254/32477273-c2bf53ec-c331-11e7-84b3-ebedc3943845.png)

**Comment by PKPenguin321** [comment]
Abductors having their antag role listed in the code as a job seems to cause multiple bugs, see https://github.com/tgstation/tgstation/issues/32420

**Comment by AnturK** [comment]
Someone typo'd assigned_role instead of special_role
