### ISSUE TITLE
Xenobio Lightgeist only speaks slime

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#32499]
Xenobio creates Lightgeist using gold slime and then gives it sentience potion, the player Lightgeist can only understand/speak Slime. This makes following orders from the creator rather inconvenient.

**Comment by Armhulen** [comment]
not a bug

**Comment by Anonmare** [comment]
How about letting it understand but not speak common? Same as a drone being able to understand people but unable to communicate back

**Comment by XDTM** [comment]
natural lightgeists are meant to speak slime when naturally spawned, but sentienced mobs are meant to gain common speech through the potion, so it doesn't make sense to make an exception for lightgeists

**Comment by Repukan** [comment]
It doesn't make sense to add light geists to xenobio either.

**Comment by Armhulen** [comment]
don't you have some mining job to be powergaming right now?

anyways @XDTM it's all yours!!

**Comment by Armhulen** [comment]
since i have no clue on how i'd fix this

**Comment by PKPenguin321** [comment]
Yoink

**Comment by PKPenguin321** [comment]
Also *technically* codewise all animals including cows, corgis, etc. already know how to speak common, they just don't
