### ISSUE TITLE
Virus has no name in body, has a name in pandemic.

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#32492]
[Directions]: # 78460
So I'm pretty sure I did everything the same as I normally did in virology but when I went to scan myself I saw the disease had the name unknown instead of Fev- Itch- VEA EY TA FM. When I drew a syringe of my own blood and put it in the pandemic the correct name appeared. I experienced no symptoms other than those intentionally added to the virus.

https://puu.sh/ygHYz/d312c9f233.png

**Comment by Cyberboss** [comment]
@XDTM 			

https://github.com/tgstation/tgstation/blob/efc8d3ad85577688459e625bcec59c3391076f29/code/game/objects/items/devices/scanners.dm#L243

Seems D.name is wrong here for some reason

**Comment by Cruix** [comment]
@newfren can you try to reproduce this again? The code for naming viruses has changed a bit and it might have been fixed.

**Comment by newfren** [comment]
I have made and seen viruses since that don't have this problem so it's probably fine now? I'll just open it again if it happens again.
