### ISSUE TITLE
Some looping sounds haven't been cleaned of background noise

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#32501]
Specifically the sound that plasma collectors make while active, listen to it long enough and you'll start hearing a (mostly illegible) conversation.

**Comment by Armhulen** [comment]
floooooooooooooooooyd

**Comment by ShizCalev** [comment]
Nanotrasen realized that one of the best ways to help reinforce the weakening seal on Ratvar was to include a microspeaker in various devices which loops banishment chants.

**Comment by ninjanomnom** [comment]
@Qustinnus

**Comment by Qustinnus** [comment]
uhhhh none of my looping sounds have been merged yet and I havn't touched plasma collectors

**Comment by ninjanomnom** [comment]
Oh then that's the SM sound being refered to then.

I don't hear any sort of whispered conversation in the sounds?
https://puu.sh/yhyLb/69a516ef7b.ogg
https://puu.sh/yhyLt/b2fa70deaf.ogg
https://puu.sh/yhyLG/ff5f1f287f.ogg

**Comment by Hatfish** [comment]
The machine sounds must have been testmerged and it wasn't the SM sound, that's just the ear-piercing screech.  When I put plasma tanks into the collectors a sound played that was mostly clanking and thrumming with a faint conversation being audible after a few minutes.

**Comment by Hatfish** [comment]
If it's still testmerged tonight I'll see if I can get a recording of it somehow, unless someone else finds it first.

**Comment by Qustinnus** [comment]
🤔 I think you're going crazy there's no rad collector looping sounds like that

**Comment by praisenarsie** [comment]
@Qustinnus psst... your bloat ambience pr... psst..

**Comment by duncathan** [comment]
I'm worried that this will turn out to just be schizophrenia

**Comment by Qustinnus** [comment]
@praisenarsie listen up here kiddo my ambience is the toppest of quality freshly imported from yogstation so fight me ya geezer

**Comment by Hatfish** [comment]
fuck it, I'll reopen this once I have my proof.  you'll see, you'll all see!
