### ISSUE TITLE
All wires on derelict station point up

### ISSUE THREAD

**Issue by chall8908** [tgstation/tgstation#32519]
Round ID: 78491

For clarity, I mean the exploded, "Russian" station.  I spawned on one of the derelict drone shells and discovered (along with one other player) that all the wires point north.  On tiles where there was more than one wire, they were all on top of each other.

I crowbarred up a few floor tiles to take [this image](https://i.imgur.com/FDyxM59.png), in case my description sucks.

I don't recall this being a problem the last time I was on the derelict station (which I believe was last night) and the server revision points to a [commit from 3 days ago](https://github.com/tgstation/tgstation/commit/d5b9b56858e7c0c52fe1fe239e76defef1f2b180).  I'll be trying it again in a moment to see if it persists between rounds.

EDIT: Seems to have persisted to the next round.  Oddly, the round ID is now 78493.  Maybe I mistyped it originally?

EDITx2: [Extra obvious photo](https://i.imgur.com/SV0SXvo.png), because a friend didn't believe me.

EDITx3: Was poking around the recent commits and noticed [this one](https://github.com/tgstation/tgstation/commit/f6e7a7f249386d5b21179cb4ea59c488e83fee5a) from a couple days ago that was meant to clean up some wires.  It may have cleaned a bit too much.

**Comment by chall8908** [comment]
Seems to have persisted to the next round.  Oddly, the round ID is now 78493.  Maybe I mistyped it originally?

**Comment by ShizCalev** [comment]
Seems to be an issue with https://github.com/tgstation/tgstation/blob/fb9116abb5ced55c792b18db6bcf428630be39cd/code/modules/power/cable.dm#L81 not pulling the icon-state of the cables to generate d1 & d2 vars on ruin maps

**Comment by SpaceManiac** [comment]
Confirmed that f6e7a7f249386d5b21179cb4ea59c488e83fee5a is the cause, no idea why `Initialize()` isn't working correctly though.

**Comment by ShizCalev** [comment]
Would necessarily say #32427 is the cause, just that cleaning it up revealed another bug.

**Comment by ShizCalev** [comment]
Zlevels 1 2 & 5 are loading fine, everything else is resetting the icon-state on apparently?

**Comment by SpaceManiac** [comment]
`update_icon()` is being called prior to `Initialize()`:

```
Runtime in unsorted.dm, line 1249: (154,175,9) icon first: icon_state=1-2 d1=0 d2=1
proc name: stack trace (/datum/proc/stack_trace)
src: the power cable (/obj/structure/cable)
src.loc: the plating (154,175,9) (/turf/open/floor/plating)
call stack:
the power cable (/obj/structure/cable): stack trace("(154,175,9) icon first: icon_s...")
the power cable (/obj/structure/cable): update icon()
the power cable (/obj/structure/cable): hide(0)
the plating (154,175,9) (/turf/open/floor/plating): levelupdate()
the plating (154,175,9) (/turf/open/floor/plating): AfterChange(1)
the plating (154,175,9) (/turf/open/floor/plating): AfterChange(1)
/dmm_suite (/dmm_suite): load map impl(_maps/RandomRuins/SpaceRuins/o..., 124, 163, 9, 1, null, null, -1e+031, 1e+031, -1e+031, 1e+031)
/dmm_suite (/dmm_suite): load map(_maps/RandomRuins/SpaceRuins/o..., 124, 163, 9, 1, null, null, null, null, null, null)
Ancient Space Station (/datum/map_template/ruin/space/oldstation): load(space (124,163,9) (/turf/open/space/basic), 1)
the random ruin (/obj/effect/ruin_loader): Load(/list (/list), Ancient Space Station (/datum/map_template/ruin/space/oldstation))
seedRuins(/list (/list), 14, /area/space (/area/space), /list (/list))
Mapping (/datum/controller/subsystem/mapping): Initialize(90014)
Master (/datum/controller/master): Initialize(10, 0)
```

**Comment by chall8908** [comment]
So, I've been thinking about getting into developing SS13 stuff; I'm curious if preventing update_icon from completing before Initialize has run (since Initialize calls update_icon at the end) would be an appropriate fix for this?

**Comment by ShizCalev** [comment]
That does resolve the issue for now, however it would be better to figure out why update_icon is being called first in the long run.

**Comment by Supermichael777** [comment]
> EDIT: Seems to have persisted to the next round. Oddly, the round ID is now 78493

uhh reread that

**Comment by chall8908** [comment]
@Supermichael777 I still don't see anything wrong with what I wrote.  If you'll notice, the round I was on was 78491 while the following round was 78493.  I don't know about you, but skipping an entire integer seems a little strange.
