### ISSUE TITLE
After being made into an AI via robotics, I'm now permanently blind.

### ISSUE THREAD

**Issue by Daundra** [tgstation/tgstation#32517]
Issue reported from Round ID: 78484 (Sybil)
d5b9b5

After being made into an AI in robotics, after like 5 seconds of normal vision, I've been rendered blind. I can still interact with everything an AI normally could, including the APC pictured, but neither canceling my camera view nor reconnecting has fixed this issue and I'm now reduced to a one tile sight radius permanently it seems.

Picture related: https://i.imgur.com/36w0SY4.png

**Comment by YakumoChen** [comment]
were you depowered?

**Comment by AnonymousNow** [comment]
Judging by the picture, no.

**Comment by ShizCalev** [comment]
Gonna close in a week without another repro
