### ISSUE TITLE
Somehow I became the invisible man

### ISSUE THREAD

**Issue by JusticeGoat** [tgstation/tgstation#32524]
It was the round before Round ID 78501. I Just late joined and it was apparent from when i was on the arrivals shuttle.  https://i.imgur.com/lzQ7km0.jpg

**Comment by nicbn** [comment]
I don't see any bug

**Comment by nicbn** [comment]
I can't see any invisible man on the image

**Comment by SkowronX** [comment]
INCREDIBLE HOW YOU CAN

**Comment by RandolfTheMeh** [comment]
Posting because this happened again midround. Unsure if this was a related bug cause, but everyone who spawned in after a certain point was invisible, except for their clothes, hair, and eyes. Round ID: 79093

**Comment by KorPhaeron** [comment]
Someone hit me with envies knife while I was a nightmare and they became an invisible nightmare

later I hit a shocked grille and became an invisible nightmare and continued being invis after cloning

**Comment by Mooshimi** [comment]
Can we see if this can be reproduced in recent time?

**Comment by Xander3359** [comment]
I dont think this is reproducible. If it comes up again make a new issue.
