### ISSUE TITLE
Emitters are ignoring wires

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#32537]
[image](https://user-images.githubusercontent.com/12382984/32570451-0eb73afe-c4bc-11e7-9dcd-46779264f96c.png)

Looks like powered wires aren't neccessary for emitters to keep firing

Round ID: 78515

**Comment by Jalleo** [comment]
Possibly a powernet bug where it didnt rebuild correctly or thinks it is still connected.

**Comment by RandomMarine** [comment]
Next time something like this happens ask an admin to spawn a drone or something to multitool the cable to determine if it's still powered or if the emitter is gnoring power.

**Comment by YPOQ** [comment]
Probably fixed by #33288
