### ISSUE TITLE
Grindables dont grind

### ISSUE THREAD

**Issue by naltronix** [tgstation/tgstation#32532]
With the new grindables anonmare pr, I wanted to make some meth. I tried grinding down some glowsticks and lighttubes, and got nothing. It didnt even fucking grind.

**Comment by Anonmare** [comment]
That's odd, nobody mentioned that I'd have to touch anything else. Grinder code is so hacky

**Comment by praisenarsie** [comment]
p much nothing is grinding?

**Comment by naltronix** [comment]
no, only the added chems

**Comment by ExcessiveUseOfCobblestone** [comment]
oh lol I thought I made an issue for this
