### ISSUE TITLE
Airlock sprite not updating to show it's open.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#32538]
Box station, round ID 78516.

The brig door (bottom right one) at the entrance would not update its sprite to show it's opened/closed. People could go through it when it appeared to be closed.

**Comment by praisenarsie** [comment]
did you try reconnecting

**Comment by BeeSting12** [comment]
It happened for me and another player, and yes I did.

**Comment by ShizCalev** [comment]
Gonna close in a week without another repro
