### ISSUE TITLE
Decreasing ghost zoom level doesn't work properly

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#32544]
Normal zoom:
![tgstation bagil english 100 free lag never going back nope 2017-11-08 182933](https://user-images.githubusercontent.com/16315400/32580374-ff21796e-c4b2-11e7-88e5-f09b0fecca45.png)
Zoom level 5:
![tgstation bagil english 100 free lag never going back nope 2017-11-08 183017](https://user-images.githubusercontent.com/16315400/32580379-045edf02-c4b3-11e7-99eb-f7e204255a09.png)
Zoom level 3:
![tgstation bagil english 100 free lag never going back nope 2017-11-08 183023](https://user-images.githubusercontent.com/16315400/32580396-1beff610-c4b3-11e7-91a1-75fde3487174.png)
Zoom level 1:
![tgstation bagil english 100 free lag never going back nope 2017-11-08 183029](https://user-images.githubusercontent.com/16315400/32580399-229e33f0-c4b3-11e7-8716-2777b46e7835.png)

**Comment by AnonymousNow** [comment]
Never thought to report this, always considered it a fringe feature for the sake of some nutter.
