### ISSUE TITLE
Webhook isn't auto updating

### ISSUE THREAD

**Issue by JJRcop** [tgstation/tgstation#32571]
Likely caused by me in #32151, the webhook (@tgstation-server) is not updating itself when a PR is merged that changes its code. In my observations the live version run by @MrStonedOne is stuck at fd26a2884325b205c507babda358090e1321ac06, from PR #32157 (also by me). The reasoning for my suspicions is that @tgstation-server is still tagging PR's with the outdated "Review Again" tag, which was completely removed from the code in f7ed9b5f7ed3349b92b76910738af4cc512ed668. (#32151)

This is probably my fault but I have no idea what I did wrong, I don't have access to error logs. It's also worth keeping in mind that #32151 was merged when the webhook was taken offline for a short duration.

**Comment by praisenarsie** [comment]
@Cyberboss @MrStonedOne @lzimann

**Comment by JJRcop** [comment]
The bot should be manually updated once to see if that fixes this @MrStonedOne

**Comment by timothymtorres** [comment]
@MrStonedOne was this ever fixed?

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/tgstation/pull/65739#issuecomment-1084024112 looks like it.

**Comment by timothymtorres** [comment]
Closing this then, thanks for letting me know.
