### ISSUE TITLE
Filters Are Incapable of Setting Certain Gases

### ISSUE THREAD

**Issue by RandolfTheMeh** [tgstation/tgstation#32596]
Issue reported from Round ID: 78594 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

[Directions]: Neither Nitryl or Stimulum can be set for either filters, and should you try, it doesn't select any of the settings on the filter. This makes filtering out stimulum from a created batch more tedious than it should, and also contaminates it with undesirable gases like BZ.

**Comment by Grazyn** [comment]
I stumbled into this as well, but apparently it's just the gas name not being highlighted, the filter is working.
