### ISSUE TITLE
Wires broken on most if not all space ruins

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#32599]
Saw this on the derelict and on the ancient station, here's a pic: https://file.house/oOjl.png

**Comment by BeeSting12** [comment]
This occur roundstart

**Comment by praisenarsie** [comment]
@ShizCalev @ninjanomnom

**Comment by ShizCalev** [comment]
Why are you pinging me there's already another issue and 2 fix prs

Duplicate of #32519
