### ISSUE TITLE
Honkruin's outside area for blocking ashstorms looks garbage.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#32600]
![2017-11-10_17-00-45](https://user-images.githubusercontent.com/31222036/32669578-e8ecfa24-c638-11e7-9275-8f3bfc21404b.png)

**Comment by ShizCalev** [comment]
Area issue, can't fix this since the machinery in those squares need power.

**Comment by jughu** [comment]
Auctally this is intended because the ash storm can damage the disposals
