### ISSUE TITLE
Layering multiple decals on a tile in a DMM only results in one decal showing.

### ISSUE THREAD

**Issue by deathride58** [tgstation/tgstation#32601]
Title.

![image](https://user-images.githubusercontent.com/6356337/32670163-ed3dbfdc-c610-11e7-847f-3867b2b5b9e3.png)
Dreammaker

![image](https://user-images.githubusercontent.com/6356337/32670170-f6c9a00c-c610-11e7-8136-9573fa68bb11.png)
Ingame

It was working properly a couple of weeks ago, I'm not sure what PR broke it.

**Comment by SpaceManiac** [comment]
Boxstation's xenobio has some tiles like this, can't reproduce there.

**Comment by Jalleo** [comment]
@ninjanomnom possibly?

**Comment by ninjanomnom** [comment]
This was a problem with newer decals overriding older decal components. It's been fixed in the current version.
