### ISSUE TITLE
You cannot cough while unconscious

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#32617]
![image](https://user-images.githubusercontent.com/16315400/32681082-b6125164-c63b-11e7-8f75-66fe0c20ffc1.png)

**Comment by Jalleo** [comment]
Is this softcrit you are in?

**Comment by praisenarsie** [comment]
p sure he's in hardcrit or something but anyway the message is quite spammy

**Comment by Buggy123** [comment]
I don't remember actually, if i encounter the situation again i'll edit this post.
