### ISSUE TITLE
Zipties go invisible once you take them off of somebody.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#32633]
@ninjanomnom

**Comment by scrubs2009** [comment]
I believe this is done on purpose to keep sec borgs from acting as an infinite supply of cuffs to the crew/sec.

**Comment by DaxDupont** [comment]
@scrubs2009 that's non nonsensical since zipties BREAK on removal.

**Comment by praisenarsie** [comment]
i fixed this
