### ISSUE TITLE
Your game freezes and turns black if you attempt to phase shift as a bloodcult golem while agressively thrown in space.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#32634]
yah

**Comment by praisenarsie** [comment]
Reconnecting does fix it tho.

**Comment by WJohn** [comment]
this seems ridiculously specific. i'm gonna test this shit.

**Comment by WJohn** [comment]
Tested, this is real. What the shit lol.

**Comment by praisenarsie** [comment]
note you can still type and possibly see shit in chat too.

**Comment by Shadowlight213** [comment]
Shouldnt getting sent to nullspace send you to the secret room? Did it not trigger?

**Comment by ArcaneDefence** [comment]
Failed to reproduce.
