### ISSUE TITLE
Singularity and clock cult

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#32643]
Few issues:
1. Singularity can move spell/trap/runes/whatever you call em regardless of tile
2. Singularity can eat the barrier between the crew spawn area and cult area making it impossible to cross. which I assume is a bug since the other tiles don't get deleted.
3. Timers and other markers seem to move towards singularity and snap back except for the arrow markers

**Comment by DaxDupont** [comment]
@Xhuis

**Comment by praisenarsie** [comment]
it's a singularity.....................

**Comment by ShizCalev** [comment]
Can you elaborate on "other markers"? Hard to correct something if it's left so vague.

**Comment by Robustin** [comment]
You can no longer BOH on Reebe so this is all moot. Pulling traps independent on their turf doesn't sound like a bug either.
