### ISSUE TITLE
dismembered limbs look awful

### ISSUE THREAD

**Issue by Blute1** [tgstation/tgstation#32661]
In this image, my left arm is removed, but there is a skin-shaped hole in the sprite that makes it seem like I still have an arm. 

![](https://vgy.me/vNDGSE.png)

this would take reworking the entire layering system or respriting everything, whoever attempts to fix this is probably partly insane but be my guest

**Comment by PKPenguin321** [comment]
It would absolutely require respriting all east and west clothing items that cover that region, so yeah pretty insane

**Comment by WJohn** [comment]
Fixing this would indeed require respriting of pretty much all clothes, or at least an absolute ton of them. By that point you might as well go the extra mile and just resprite humans. I do have something in mind for that but there won't be results for it any time soon.

**Comment by TheBonded** [comment]
I am almost positive that this no longer happens
