### ISSUE TITLE
I'm not sure if this radio menu is supposed to be here

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#32674]
![000](https://user-images.githubusercontent.com/29125781/32700073-4954234a-c79e-11e7-8026-5c4824f0492f.png)

**Comment by DaxDupont** [comment]
It has been for years.

**Comment by DoctoreMad** [comment]
It doesn't do anything

**Comment by DaxDupont** [comment]
Yeah, but if it's deemed a bug then it's one going back till at least 2014

**Comment by DoctoreMad** [comment]
Okay.
Where are you going with this, though?

**Comment by DaxDupont** [comment]
That it's probably not considered a bug since it's been reported about 30 times before?

**Comment by DoctoreMad** [comment]
But what
It legitimately doesn't do anything
Why?

**Comment by Jalleo** [comment]
To be honest I think it was added to eventually make it so tracking beacons only worked if you had the right frequency but it was never done.

**Comment by SpaceManiac** [comment]
It does do stuff, the tracking beacon is also a functional station-bounced radio.

**Comment by PKPenguin321** [comment]
Yeah, you can speak into it with .l and .r if it's in your hands

**Comment by DoctoreMad** [comment]
>Yeah, you can speak into it with .l and .r if it's in your hands

WHAT

**Comment by ShizCalev** [comment]
what

**Comment by PKPenguin321** [comment]
.l speaks into whatever's in your left hand, .r for right
