### ISSUE TITLE
Players, when apes, have no feedback that they are injured.

### ISSUE THREAD

**Issue by ChemicalRascal** [tgstation/tgstation#32673]
As title.

To reproduce: Get hit by bolt of change, become ape. Go into area without oxygen. Remark to borgs around you that it seems you don't need to breathe. Die.

**Comment by YakumoChen** [comment]
applies to all simplemobs

**Comment by msgerbs** [comment]
Pretty sure this has been fixed since simplemobs now have a health dummy on the screen.
