### ISSUE TITLE
Shuttle curses can be bypassed by recalling and calling again.

### ISSUE THREAD

**Issue by scrubs2009** [tgstation/tgstation#32683]
Round ID: 78700

We had about 10 minutes of time due to shuttle curses during code red. They recalled and then called again less than 5 minutes later and had the extra time removed.

**Comment by alexkar598** [comment]
Maybe just make the shuttle un recall able

**Comment by scrubs2009** [comment]
That sounds like a bad idea Alex. Having a cult member with high access recall a shuttle is a useful thing.

**Comment by YakumoChen** [comment]
make the curse add the curse time to recall if they do it
