### ISSUE TITLE
gas filters have freon listed, but not assmos gases

### ISSUE THREAD

**Issue by cyclowns** [tgstation/tgstation#32682]
round #78699

testmerges:
#32645: 'Circuitry Lab Testmerge: Report ALL BUGS HERE' by Iamgoofball at commit b23bda
#32487: 'The Thingling' by Armhulen at commit efe3cc
neither of them have anything to do with atmos so I don't think its caused by that

to reproduce:
click on a gas filter and see that freon is a thing when it shouldn't be and that none of the new gases are listed. also clicking on freon does nothing

https://i.imgur.com/sF8Yu0Q.png

**Comment by duncathan** [comment]
uncompiled tgui during testmerge
