### ISSUE TITLE
Clients can use BYOND reconnect to spam ahelps

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#32686]
Ahelp, right click title, reconnect. repeat ad-infinium.

**Comment by Jordie0608** [comment]
The best solution to this is probably some liberal application of ban.

**Comment by Jalleo** [comment]
Or sanity checking?

**Comment by SuperNovaa41** [comment]
still an issue

**Comment by Mooshimi** [comment]
possible to set the client/var that stores the timer for ahelp cooldown after a client reconnects to the full timer in client_procs.dm?

**Comment by san7890** [comment]
This was fixed in #62711 with the addition of `var/list/ahelp_cooldowns = list()` on the adminhelp datum (i believe)

**Comment by Cyberboss** [comment]
I don't think so? Isn't that list purged when the client reconnects?

**Comment by san7890** [comment]
![image](https://github.com/tgstation/tgstation/assets/34697715/cc79c015-ef53-4b1b-9457-c6292161859d)

Nothing appears to "purge" the list as suggested

**Comment by Cyberboss** [comment]
Ah my bad then
