### ISSUE TITLE
Cables lacking d1 or d2 in templates do not load correctly.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#32694]
![](https://i.imgur.com/7c8fRMK.png)

These are ripped straight from metastation, as all main stations have had their cable d# variables made obsolete. Unfortunately, these break if loaded in via template.

@ShizCalev

**Comment by ShizCalev** [comment]
@ninjanomnom #32584

**Comment by ShizCalev** [comment]
@WJohn Server revision?

**Comment by WJohn** [comment]
Server revision compiled on: 2017-11-12

36d9e5

**Comment by ninjanomnom** [comment]
That pr should have no impact on this, I'll take a look at what's causing this regardless.

**Comment by ninjanomnom** [comment]
I'm not seeing any issues on the most recent master
![image](https://user-images.githubusercontent.com/1234602/32711946-c1b799b8-c80f-11e7-9933-c3f58eb81f4c.png)

**Comment by WJohn** [comment]
On templates spawned midgame specifically using d1-d10 cables like those from the station (in this case I used metastation which it and all station maps had those removed). Templates still using d1-d10 work fine, and templates without d1-d10 but spawned in init also work fine (you can also just tick the file to force it to spawn in the bottom left someplace).

**Comment by SpaceManiac** [comment]
Away missions also do not load correctly.

**Comment by WJohn** [comment]
Presumably they would work fine if they were loaded in at init, but after that they'd likely break.
