### ISSUE TITLE
Offset pipes can stick out from above floor tiles.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#32697]
![](https://i.imgur.com/7CFN7yK.png)

Notice the pipe sticking out above the floor in the bathroom, even though it's supposed to be on the level of the plating. I don't know any good way to actually fix this, either. 

Covering the floor under the door with a tile will just hide the problem under the airlock, but it will become visible again as soon as you open the door.

@kevinz000 

Don't mind the broken cables that's another issue on its own.

**Comment by kriskog** [comment]
Shouldnt be happening anymore
