### ISSUE TITLE
Pipe dispensers can't dispense bent pipes

### ISSUE THREAD

**Issue by Mark9013100** [tgstation/tgstation#32703]
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

See title, while using a regular pipe dispenser, I didn't have the option to dispense bent pipes.

**Comment by WJohn** [comment]
Related to #32695

**Comment by ShizCalev** [comment]
Oversight from #32435

**Comment by ShizCalev** [comment]
@ACCount12

**Comment by ACCount12** [comment]
My fault. I suspect atmospherics pipe dispenser has the same problem.
