### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Artemiuz28** [tgstation/tgstation#32704]
Really, not sure where else to post this.

Is it possible to include a compiled .dmb to the downloadable build?

**Comment by PKPenguin321** [comment]
You'd have to have a new compiled build with every PR so not really
It's really really really easy to compile the game, if you have BYOND you have the tools to do it
Also an appropriate place for this would have been on the forums, perhaps on the Coding board

**Comment by ShizCalev** [comment]
Forums for requests, please.
