### ISSUE TITLE
Goon chat doesn't load

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#32711]
Client loads old chat everytime. 
It seems to have occurred after cleaning cache a bit ago.

Issue exists on both 511 and 512.

Relevant runtimes:
https://tgstation13.org/parsed-logs/basil/data/logs/2017/11/13/round-78737/runtime.txt
`[2017-11-13 17:11:40] Client: HollaHollaFoADolla triggered JS error: Error: IndexSizeError | url: http://-censored-:50076/tmp15552/jquery.min.js | line: 4 | column: 12459 | error: IndexSizeError | user agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)`
https://atlantaned.space/newSS13tools/round.php?round=78737

**Comment by Armhulen** [comment]
stop using firefox, duh.

**Comment by DaxDupont** [comment]
@Armhulen pls tell me you're joking

**Comment by ike709** [comment]
Even if he is joking, chrome is better.

**Comment by ShizCalev** [comment]
It was a joke.

**Comment by lzimann** [comment]
Loading both chats is intentional.

**Comment by ACCount12** [comment]
NOT loading the new chat is definitely not.

**Comment by DaxDupont** [comment]
Whatever happened it seems to be fine for now. Do others still have issues?

**Comment by ACCount12** [comment]
It fixed itself for me too. No idea what caused it in the first place.

**Comment by lzimann** [comment]
it was fixed by #32705

**Comment by DaxDupont** [comment]
wew
