### ISSUE TITLE
Cave generator acts on space ruins, causing atmos runtimes

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#32728]
Runtime in open.dm, line 137: Cannot execute null.compare().
proc name: Initalize Atmos (/turf/open/Initalize_Atmos)
src: the asteroid sand (172,60,11) (/turf/open/floor/plating/asteroid/airless/cave)
call stack:
the asteroid sand (172,60,11) (/turf/open/floor/plating/asteroid/airless/cave): Initalize Atmos(1)
Atmospherics (/datum/controller/subsystem/air): setup allturfs()
Atmospherics (/datum/controller/subsystem/air): Initialize(80202)
Master (/datum/controller/master): Initialize(10, 0)

BMPship, _maps/RandomRuins/SpaceRuins/crashedship.dmm

![image](https://user-images.githubusercontent.com/222630/32759606-1160732e-c89f-11e7-8007-c215ef95ab3f.png)
![image](https://user-images.githubusercontent.com/222630/32759645-4eb68eca-c89f-11e7-98c4-220afbb177c8.png)

**Comment by WJohn** [comment]
Cave generation could just be removed outright for space, or perhaps restricted to a specific type of area.

**Comment by ACCount12** [comment]
So THIS is what was causing those elusive runtimes. Nice catch!

**Comment by kriskog** [comment]
Can't reproduce this, seems fixed.

**Comment by Whoneedspacee** [comment]
cave generation is tied to areas now so this is kind of pointless to have open anymore
