### ISSUE TITLE
Stimulum Metabolization Does Not Coincide With Next Dose

### ISSUE THREAD

**Issue by RandolfTheMeh** [tgstation/tgstation#32727]
Issue reported from Round ID: 78746 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Unsure if this is a bug, but now, irregardless of how much stimulum you breath, it will metabolize out of your body before you get your next "dose", resulting in awkward spurts of HIGH LEVEL, PHYSICAL ACTIVITY.
The current cycle is about 50% on stim, 50% off.

**Comment by joonoro** [comment]
I think this might also affect Nitryl, I can't seem to get the speed effect to work at all.
