### ISSUE TITLE
Multiple people are unable to hear admin internet sounds

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#32731]
I am getting informed that people cant hear my dumb meme music and some admins cant even hear their own meme music. I have no idea why this is but I'm reporting it anyways.

**Comment by JJRcop** [comment]
I am very interested to see why this is occurring. It's working fine for me and we already dealt with this before with the format stuff. I might try something out and see what that does, using the [<source>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source) tag to include every available source that the youtube-dl query can find that is valid.

**Comment by BeeSting12** [comment]
Sometimes people in Europe can't hear stuff blocked in Europe. Which makes sense but it also might be the source of the issue

**Comment by Spaceinaba** [comment]
It's happening to people who live in america too, so I don't think it's that.

**Comment by Mark9013100** [comment]
It's related to Goonchat bugging out, I think.

**Comment by Spaceinaba** [comment]
Yeah but I can hear every single sound I play I'm pretty sure it's not location based

**Comment by PKPenguin321** [comment]
Well yeah because you'll play sounds you searched which will be sounds from your region

**Comment by JJRcop** [comment]
The content url is fetched by the server, so contrnt locking will only affect the server

**Comment by JJRcop** [comment]
I think #32705 fixed this.

**Comment by ShizCalev** [comment]
Will close in a week without another repo.
