### ISSUE TITLE
Loss of Cult Status when implanted upon calling a vote for leader.

### ISSUE THREAD

**Issue by Nabski89** [tgstation/tgstation#32755]
ROUND 78795

I was a cultist.
I got implanted.
I called a vote to make me the leader.
I think the vote passed then it made me not a cultist. When I asked an admin to fix it then said that I already had cult status. (SpaceInaba)

**Comment by YakumoChen** [comment]
becoming a cult leader actually momentarially decults you because of snowflake code.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Robustin
