### ISSUE TITLE
Unable to move, tab brings up autocomplete rather than enabling hotkeys

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#32766]
[Directions]: #78803
The very round before worked perfectly with the same shit testmerged but whatever:
#32756: 'Robot pulls are not strong enough to restrain handcuffed prisoners; Re-enables secborgs, with no config. ' by MrStonedOne at commit 357f40
#32757: '511 client fix and a config to make the version warning a popup' by ninjanomnom at commit 3b46de
#32751: 'In-code key handling system, Take 2' by ninjanomnom at commit d5bbe4
#32758: 'Remove shocker circuit' by optimumtact at commit 468828
 
So I can't move with the arrowkeys and wasd just types in the chat box. Hitting tab brings up autocomplete instead of enabling hotkeys mode. I was playing AI at the time and I could move my camera by double clicking or by tracking people but not by the standard means. The literal round before it worked fine. I tried restarting, clearing cache, redownloading byond, etc etc.

This is probably a result of #32751, please remove it from testmerge so I can play this game.

**Comment by YakumoChen** [comment]
the problem is 512, everything works if you downgrade back to stable.

**Comment by newfren** [comment]
I have downgraded and it did not solve my problem.

**Comment by nicbn** [comment]
Same problem here

**Comment by nicbn** [comment]
The problem is that you are playing Sybil using the stable version. You need the beta version to play it.

**Comment by nicbn** [comment]
Had the same issue with 511 and 512. #32751 broke the game

**Comment by Cyberboss** [comment]
Caused by #32751 @ninjanomnom

**Comment by MrStonedOne** [comment]
no it is not.

its a bug in byond.

**Comment by newfren** [comment]
For the record if this is a bug in BYOND it has been fixed. If it's not a bug in BYOND then 32751 has also been untestmerged.
