### ISSUE TITLE
TTVs dont blow up in drone assemblys

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#32770]
>stuff 6 maxcaps into drone grabbers
>signal
>6 beeps
>no explosions
wtf???
What did you expect to happen:
Massive fucking explosion

**Comment by Supermichael777** [comment]
>6
>never tested the mix

**Comment by evsey9** [comment]
I did the same thing I did the previous round
It had 2533 kPa of superheated plasma and 2533 kPa of supercold oxy

**Comment by Supermichael777** [comment]
was the bomb deleted, did it never get the signal, did it explode the moment you took it out?

**Comment by evsey9** [comment]
I didnt take it out because i was dead

**Comment by evsey9** [comment]
Also it beeped which means it got the signal

**Comment by GunHog** [comment]
I wonder if the bombs exploded in null space?

**Comment by evsey9** [comment]
THIS KILLS SHEER HEART ATTACK

**Comment by arsserpentarium** [comment]
IDK,what's wrong.But you still can eject all the shit from grabber right before explosion.
