### ISSUE TITLE
Trunks don't send you into disposals outlets

### ISSUE THREAD

**Issue by nichlas0010** [tgstation/tgstation#32772]
[Directions]: #78807, bagil, Omegastation
Testmerged PRs:
#32756: 'Robot pulls are not strong enough to restrain handcuffed prisoners; Re-enables secborgs, with no config. ' by MrStonedOne at commit 357f40
#32758: 'Remove shocker circuit' by optimumtact at commit 468828
#32763: 'Adds microtransactions allowing players to buy lag,' by MrStonedOne at commit b7d093

If you set up a chute -> outlet disposals ride, you get ejected by the trunk not the outlet. The outlet still plays the animation and the noise, but you're ejected immediately instead of with the animation.

https://gyazo.com/3466de783f8b09ade44af6120fddcc54

**Comment by Cyberboss** [comment]
@ACCount12
