### ISSUE TITLE
Round ends too much time after shuttle docks at centcomm

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#32780]
Round should end right as shuttle fucking docks not five seconds later

**Comment by evsey9** [comment]
This killed my greentext because i activated bites za dusto right as shuttle docked and NOT RIGHT AS SHUTTLE ENDED WHICH SHOULD BE THE EXACT SAME TIME

**Comment by optimumtact** [comment]
this isn't a bug, you got played

see you next round gamer
