### ISSUE TITLE
2 Abductor teams all spawned on the same ship and team.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#32798]
A random ayy event triggered, then i forced another abductors event to make two teams. however, both teams were lambda team and spawned on the same ship
![image](https://user-images.githubusercontent.com/9410002/32873046-bf63fd60-ca3e-11e7-9940-ce31cd9a4c44.png)

**Comment by Armhulen** [comment]
cool

**Comment by KorPhaeron** [comment]
I spawned an abductor team for a TC trade, they got killed by a metagamer, and I compensated by spawning a second abductor team and they ended up in the same shuttle as well.

**Comment by Arianya** [comment]
From a previous incidence of this, the shuttle also "binds" to one of the two teams, probably the first team, which causes things like the secondary scientist being unable to warp anyone back up, the "switch armor mode" button changing the wrong soldier's armour, etc etc.
