### ISSUE TITLE
UI windows turning solid white

### ISSUE THREAD

**Issue by Grazyn** [tgstation/tgstation#32806]
Can someone tell me what I can do to fucking fix this because it is turning me insane. I can't reproduce it, it just happens from time to time, UI windows from machines turn white and I can only fix it by relogging, and even then it will just happen again randomly.

**Comment by lzimann** [comment]
Sadly this is a byond issue: http://www.byond.com/forum/?post=2211145

**Comment by WJohn** [comment]
Yep, had this happen to me too. Had to relog.

**Comment by Shadowlight213** [comment]
You can fix it temporarily by using the fix chat verb and forcing a reload of goonchat.

**Comment by ShizCalev** [comment]
Duplicate of #31745

**Comment by MegaRhinoKing** [comment]
I have no experience so I don't know what shadowlight meant by his most recent post. Can someone guide me through this?
