### ISSUE TITLE
Using a chameleon projector while riding a vehicle breaks things

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#32819]
1. Get on a quad bike

2. Use chameleon projector

3. You are still visually on the bike, and you drive off leaving the projector holder on the ground

4. Someone touches the projector holder

5. Your screen turns to space

**Comment by PKPenguin321** [comment]
Prevent using it while buckled would fix

**Comment by vuonojenmustaturska** [comment]
This is because chameleon projector creates things at your loc rather than at your turf, fixing
