### ISSUE TITLE
Clown horn and shoes are activated by picking up/putting down unrelated items

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#32817]
If I have a horn in my pocket as a clown and I pick up a crowbar or something it triggers the horn for some reason

If I put the crowbar into my backpack (where my clown shoes are) then it triggers the clown shoes

**Comment by zamolxius** [comment]
FEATURE

**Comment by Grazyn** [comment]
It's consistent? You lean down to pick up something and you squeeze the horn in your pocket. You put something in your backpack and it bumps into your shoes

**Comment by DaxDupont** [comment]
We need to go back to each time that any object moves to a floor turf, is checks if it's a human. If it's a human, it checks if they're wearing clown shoes, just to make the clown step sound.

https://tgstation13.org/phpBB/viewtopic.php?f=5&t=1442

**Comment by newfren** [comment]
I think this happens with a BRPED as well actually.
