### ISSUE TITLE
A couple of things I noticed as plasmaman

### ISSUE THREAD

**Issue by Vynncerus** [tgstation/tgstation#32828]
Server: Bagil

Revision: It gave me a whole bunch of information, I think this number is what I am supposed to give. 038998. If that's the wrong thing, it was today, 11/16/2017.

Problem Description: Pocket protector spawns on plasma envirosuit.

What did you expect to happen: I expected to not have a pocket protector on my plasma envirosuit, because I am unable to attach items like medals or pocket protectors manually.

What happened instead: I instead had one, and when I took the pocket protector off I could not put it back on again.

Why is this bad/What are the consequences: I think it should be consistent whether or not plasma envirosuits can have items like pocket protectors attached, either not have one spawn on it, or allow them to be attached.

Steps to reproduce the problem: Choose plasmaman as your race and atmos tech or something as your job at character setup.

I encountered a second issue, I am not sure if it's intended or not but I figured it was worth listing as well.

While I'm able to put my plasma internals tank in my suit slot when wearing a hardsuit, I am unable to put it in the same slot when wearing something like a firesuit, even though an oxygen internals tank is able to go there. I've noticed this for both firesuits and emergency firesuits, winter coats, hazard vests, and emergency life vests.

**Comment by PKPenguin321** [comment]
Odd that it doesn't support attachments

**Comment by Jalleo** [comment]
At least one should be a easy fix.

**Comment by tserpas1289** [comment]
I just made a pull request to fix the plasma man internals issue, I have not found a fix for the pocket protector though. [https://github.com/tgstation/tgstation/pull/32897](url)

**Comment by Vynncerus** [comment]
I'm no coder or anything so I don't know how easy it would be to fix the pocket protectors part. Honestly I've only even been playing this game a few weeks, so perhaps I'm very naive, maybe it's intentional that you should not be able to do this, but would getting around the issue by just allowing things like pocket protectors or medals to be attached to the plasma envirosuit be an acceptable solution? It wouldn't be a problem to have them spawn attached if you were of course able to actually attach them.

**Comment by PKPenguin321** [comment]
Yeah, as far as I know all jumpsuits allow attachments so I'm not sure why the plasmaman one is even an exception to begin with.

**Comment by tserpas1289** [comment]
As it turns out all other jumpsuits, including ones like the sundress, can equip accessories and it seems to have been unintentionally overrode when allowing plasma men to refill their extinguisher count with the refiller items. This seems to actually be a bug so I'm going to refer to it as one.
