### ISSUE TITLE
Black slime toxin doesn't work

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#32832]
If you're not a slimeperson, the disease progresses through 5 states. At stage 3, it turns you into a slimeperson, and then at stage 5 it turns you into a slime simplemob. And when it first starts at stage 1, it checks if you're a slimeperson and if you are instantly skips to stage 5. So, no matter how you use it you have to become a slime person first and then either infect yourself or allow the disease to progress... but there's one problem.

Slime people are immune to diseases.

Yeah.

**Comment by XDTM** [comment]
Someone fixed the bug with virusimmune species keeping their viruses, so now this happens. IMO slimepeople shouldn't be immune anyway

**Comment by Buggy123** [comment]
It might be a bad idea if they weren't. I haven't read through the code but depending on how it handles the whole "toxins heal you, toxin healing hurts you" thing, a typical healing virus might be deadly.

**Comment by XDTM** [comment]
It would hurt them, and i'm assuming it would be acceptable (especially if conditional healing is merged)
