### ISSUE TITLE
AI HUDs are non-functional

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#32848]
Cycled through all three - no result. Not even job icons. 

Round ID; 78909

**Comment by Anonmare** [comment]
**Update**: Some HUDs are working but there's no rhyme or reason to them. Some people are showing up on medical, some on security and some cyborgs show up on the diagnostic HUD but not always. Doesn't matter what my actual HUD is either

**Comment by GunHog** [comment]
Perhaps https://github.com/tgstation/tgstation/pull/32786 has something to do with it? It is just a guess, as I cycled HUDs as a borg and noticed that both showed on up on the same human.

**Comment by Shadowlight213** [comment]
Possibly fixed by #32852?

**Comment by Cyberboss** [comment]
Gonna assume so
