### ISSUE TITLE
HUDs seem to randomly not work for one person

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#32847]
I've seen this happen two rounds in a row, once with a security HUD and once with medical on two different people. Most recent round is ID 78906. Reconnecting does not work, nor does taking the HUD off/putting it back on, wasn't an issue with that specific HUD either as I spawned a new one and it didn't fix it. One player tried clearing their cache, didn't fix it. 

I deleted them and rehumanized them, which seemed to work.

**Comment by SpaceManiac** [comment]
The fix has hit live and things should be good now.
