### ISSUE TITLE
Deconstructive Analyzer eats all sheets again

### ISSUE THREAD

**Issue by Grazyn** [tgstation/tgstation#32854]
Issue reported from Round ID: 78925 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

[Directions]: To reproduce, insert any number of sheets of mineral inside the DA, deconstruct. I expected it to eat only one sheet like it used to do. It ate the whole thing instead.

**Comment by Grazyn** [comment]
#31026: '[READY] RND TECHWEBS + DEPARTMENTAL LATHES' by kevinz000 at commit eeb1c9

**Comment by praisenarsie** [comment]
techwebs related

**Comment by Cyberboss** [comment]
@kevinz000

**Comment by SpaceManiac** [comment]
The sheets are not deleted, they're placed in some limbo:

1. Insert 2 sheets of glass.
2. Deconstruct. No glass remains.
3. Insert 2 sheets of metal.
4. Deconstruct. No metal remains.
5. Insert a sheet of glass and eject it.
6. There are now two sheets; the lost sheet is recovered.
7. Repeat with metal.

Basically, the eaten sheets can be recovered by inserting & ejecting one sheet of the same type.
