### ISSUE TITLE
Ghost role became a shade, but was blind, deaf, and mute

### ISSUE THREAD

**Issue by Sven-Grey** [tgstation/tgstation#32863]
Issue reported from Round ID: 78939 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Problem Description: I ended up dying during the wizard round. The wizard was making all the bodies into constructs. Many prompts of: "Do you want to be a shade?" appeared so I pressed Yes to all of them. I became the shade of  someone, however the screen was all black except for the 'weightlessness' icon. I tried to reconnect and at first nothing happened. However, after trying to reconnect again I was sent to the New Player Options screen with the ability to rejoin.

What did you expect to happen: To be a shade

What happened instead: I became a blind, deaf, mute shade, then the game acted as though I could respawn. At the same time (not sure if coincidence or I caused the glitch) everyone else on the server could no longer talk in IC.

Why is this bad/What are the consequences: hard to be a blind deaf shade, but also there may be a way to abuse this to respawn

Steps to reproduce the problem: The most important section. Review everything you did leading up to causing the issue. 
1. Die During a wizard round.
2. have someone start cloning your body? (not sure if related)
3. When multiple prompts for becoming a shade appear, mash YES
4. Screen should go black and deaf (OOC still works though)
5. Mash reconnect
6. you should be on the main screen

Server: Issue reported from Round ID: 78939 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Revision: What revision was the server running? Issue reported from Round ID: 78939 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): It was a wizard round (though when the round ended it did not show greentext info). At the time of wanting to be a shade my body was cloning. Apparently the whole server went mute judging by OOC chat.

**Comment by XDTM** [comment]
Sounds like nullspace

**Comment by timothymtorres** [comment]
This could possibly be related to #57217 since both of these are ghost roles and may be getting triggered by the same thing.

**Comment by JohnFulpWillard** [comment]
This has had to have been fixed a long time ago because I've never seen it in my life and I've accepted becoming a shade many times

**Comment by Bawhoppen** [comment]
It's worth noting that it may be part of a broader issue, since I have had an instance before when something very similar happened to me after being cloned. Perhaps something about creating a mob on a wrong tick? I can only speculate since I know little about that type of thing. It's also possible that bigger issue was fixed too.
