### ISSUE TITLE
Navigational Ships do not land where designated

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#32867]
I was flying white ship around the station when I apparently managed to eat part of the brig - Nukeops landed near me so I tried to park above them, landed on their cockpit instead.

I made Beesting really mad too.

**Comment by BeeSting12** [comment]
I originally thought you used the navigation console to meta the nuke ship location

**Comment by Robustin** [comment]
I told you, they literally parked in screen length so when I opened to console to fly away from the fucking operatives boarding my ship to kill me, I saw their ship next to mine.

**Comment by ShizCalev** [comment]
@ninjanomnom

**Comment by WJohn** [comment]
I noticed this, too. Not sure what caused it.

**Comment by WJohn** [comment]
@Cruix this is more your thing, I guess.

**Comment by Cruix** [comment]
Please be more specific about bugs like this.

Where was the designated landing spot?
How far away did you land from the designated landing spot?
Was the shuttles rotation different than expected?
Were the camera view and highlighted area strange in any way?
Was there any overlap in the designated and actual landing locations?
What sequence of shuttle moves had you done before this happened?
Were all subsequent shuttle moves also bugged? Were they bugged in the same way?

This information would make reproducing this bug much easier than just flying the white ship around randomly until it breaks. I happened to get very lucky and reproduce it just before I was going to give up.
