### ISSUE TITLE
When shuttles are late to arrive the landing indicator doesn't stick around

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#32873]
It was stuck on 00:00 ETA for a full minute and then arrived and crushed everyone since the blue rings disappeared.

Round id: https://atlantaned.space/newSS13tools/round.php?round=78952

Server revision compiled on: 2017-11-18

The following pull requests are currently test merged:
#31026: '[READY] RND TECHWEBS + DEPARTMENTAL LATHES' by kevinz000 at commit eeb1c9

Based off origin/master commit: https://github.com/tgstation/tgstation/commit/1daf43814f0514f10668132215be29a46f90281d

**Comment by Shadowlight213** [comment]
The shuttle arriving late is usually due to lag

**Comment by ninjanomnom** [comment]
I'm going to go with blaming lag or a full transit space for the lateness of the shuttle.

The bug here though is that the landing indicator doesn't stick around until it actually arrives.
