### ISSUE TITLE
Oversights with robot devils

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#32872]
After some bug testing I've noticed a number of oversights with regards to silicon devil agents:
-Cyborg devils do not have scrambled security codes, meaning they can be locked down and killed using the robo console
-AI devils are unable to get anyone to sign a contract with them on account of being immobile
-All robot devils cannot use pitchforks
-All robot devils can be given obligations they cannot physically perform (such as playing the fiddle)
-There is no easy means of making a robot devil through the traitor panel 

There could be more but this is what I found by myself

**Comment by Anonmare** [comment]
Another thing I noticed is that all robot devils get the "You can not use violence to get someone to sell their soul" Law as seen in pic related:

![image](https://user-images.githubusercontent.com/12382984/32985257-be162042-ccae-11e7-85b3-fd8b298b86ff.png)


I am not sure if this is intended or an oversight.

**Comment by DoctoreMad** [comment]
I am 666% sure that there is no way a "bug" could have happened so perfectly as to give every cyborg a law that is VERY related to their current situation.

**Comment by praisenarsie** [comment]
@AnturK

**Comment by Shadowlight213** [comment]
Afaik i mentioned this to the creatir of devils and they called it a feature or something.
Getting the fiddle one probably is an oversight though.
Giving devil borgs scrambled sec codes might be a good idea too.

**Comment by lordpidey** [comment]
Wait what?  AI devil?  that shouldn't be possible.

@Anonmare how did you do that, because AI should be blacklisted from devil.

I'll look into the traitor panel stuff and the fiddle/pitchfork stuff.

**Comment by Anonmare** [comment]
I don't really remember since it was like 2 months now. All I remember was there not being an easy way to make devils so I had to restart the round and force Devil Agents every time I wanted to test it. But that screenshot was of the AI Devil's laws

**Comment by vuonojenmustaturska** [comment]
AI shouldn't be able to become a devil but a devil MMI may be used to create a borg or an AI
