### ISSUE TITLE
pAI interface is 10 years crap.

### ISSUE THREAD

**Issue by psykzz** [tgstation/tgstation#32879]
![image](https://user-images.githubusercontent.com/1134201/32986054-548b8240-ccc0-11e7-8294-551c52261278.png)

**Comment by davethwave** [comment]
A better UI... perhaps it would encourage people to use them or to be them more if the UI was better

**Comment by psykzz** [comment]
This is what i was thinking, im also thinking about doing some balance changes to them if their welcome.

I think  the pAI should be like an AI but with "energy" and as actions are taken energy goes down, and slowly recharges.

I may do two PR's one for an updated UI another for updated balance.

**Comment by epochayur** [comment]
I'd love to see some changes to the pAI system, I can count on two hands the amount of times I've seen them used in the past year, plus I'm totally for anything that gives dead players more things to do

**Comment by psykzz** [comment]
Some thoughts i had

pAI should feel like a limited AI that can't use only view machines. They have their view locked to the player, but can move around them as a hologram (similar to AI around a holopad).
They should be able to interface with typically every machine, but not use them (unless specific software has been downloaded to allow usage to that specific machine. pAIs are required to be next to a machine to use it, this can be as a hologram or while on the carrier.

pAIs should:
- [ ] - be able to walk around the player, as like AI around a holopad
- [ ] - have energy / action points
- [ ] - be able to interface with any computer / machine (within sight), but not use them directly.
- [ ] - Download software to allow controlling with specific machines
- [ ] - double as a multitool (initiated by the pAI not carrier)

**Comment by Bawhoppen** [comment]
Your avatar reminds me of Paprka. Are you secretly them?

**Comment by RemieRichards** [comment]
fix your eyes bawhoppen.
Paprika's avatar was... paprika... from the film... paprika.

*sigh*

**Comment by Bawhoppen** [comment]
I don't even remember it very well I just was going off memory

**Comment by Bawhoppen** [comment]
Also do you honestly still have the repo on watch mode?
