### ISSUE TITLE
Setting scurbbers to contaminated doesn't make them filter plasma/N2O etc.

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#32881]
Set a scrubber to contaminated should be scrubbing these gases.

**Comment by ShizCalev** [comment]
@duncathan

**Comment by praisenarsie** [comment]
i thought it was a ui issue when it was reported downstream

**Comment by praisenarsie** [comment]
found a runtime on hippie.

```
The following runtime has occurred 18 time(s).
runtime error: Undefined variable /obj/machinery/atmospherics/components/unary/vent_scrubber/var/scrub_N2O

**Comment by ShizCalev** [comment]
#32746 thing @duncathan forgot something

https://github.com/tgstation/tgstation/blob/0389985397f719eaad162d1d99e8ab18cd127959/code/modules/atmospherics/machinery/airalarm.dm#L448-L507

**Comment by duncathan** [comment]
I know what the problem is I just haven't been on my computer to fix it

**Comment by ShizCalev** [comment]
any luck with this @duncathan ?
