### ISSUE TITLE
Xenobio crashes the game when you press buttons.

### ISSUE THREAD

**Issue by JessHorserage** [tgstation/tgstation#32907]
Issue reported from Round ID: 78988 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

How to repoduce.

Go onto the xenobiology console.

Press some buttons.

Wait for your game to crash.

Crash.

**Comment by praisenarsie** [comment]
what's your byond version?

**Comment by JessHorserage** [comment]
The most recent beta version.

**Comment by WJohn** [comment]
Related to what I experienced in #28689? They're both advanced cam consoles.

**Comment by Rinoka** [comment]
After some basic examination, I think it has to do with the AI eye effect, yeah. When fooling with Xenobio on Sybil, my game crawls & crashes. I'm gonna try it with a clean non-beta on Basil soon and see if that fixes it; if it does, then 512 might be fuccin with adv. cam code.

**Comment by ShizCalev** [comment]
Merging this all into #33377
