### ISSUE TITLE
Bardrones can be blown from the RD's robotics console

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#32903]
Even though it's immortal in almost every other regard (except singulos and chasms I guess).  Escape bar staff probably shouldn't be subject to being blown from station consoles.
Round ID: 78981
Based off of master commit 1daf43
Testmerged PRs:
#31026
#32835

**Comment by Anonmare** [comment]
This should be an easy fix, setting the hacked var to 1 should make it immune to the robo console
