### ISSUE TITLE
Security Huds partially working

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#32910]
Issue reported from Round ID: 78995 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

There's been an issue with security huds not properly displaying either job, wanted status, or implant status at all. From what I can tell, it's mainly on security positions that start with sec huds equipped at spawn, mainly the Warden and HoS.

I could see some crew's sec hud status, but not others. Pretty sure I could only see people's status if they arrived after roundstart, but cannot confirm.

**Comment by SpaceManiac** [comment]
#32852 should fix this, it only just hit live on Sybil and hasn't reached Bagil yet.
