### ISSUE TITLE
Crashing after updating to firefox quantum

### ISSUE THREAD

**Issue by Eldunari95** [tgstation/tgstation#32927]
I've been having issues crashing every 2-3 minutes, after troubleshooting for a few days I realized that the only difference between when it didn't crash and when it did is that I updated firefox to firefox quantum.
After reverting firefox the crashing issues stopped, I liked quantum so I installed IE 11 and updated firefox back to quantum and the crashes have not come back.
Obviously my fault for not having IE installed but if you're having crashing after the firefox update try installing IE again.

**Comment by nicbn** [comment]
Byond issue

**Comment by duncathan** [comment]
I don't think there's anything at all that we can do about this. If I'm wrong any maintainer is more than welcome to reopen but afaik this is all on the BYOND side of things

**Comment by Cyberboss** [comment]
Please report this on the BYOND forums though
