### ISSUE TITLE
Meters created by the RPD are invisible

### ISSUE THREAD

**Issue by Electronics** [tgstation/tgstation#32920]
Create a meter with the RPD, looks like nothing happens, right click the tile, a "fitting" has been created with examine being:` That's fitting. A pipe. It is a normal-sized item. Alt-click to rotate it clockwise.`
![image](https://user-images.githubusercontent.com/422393/32996623-02d7560a-cd7d-11e7-89a9-5ff14229fede.png)

Round ID: 79000

Server revision compiled on:  2017-11-19 
The following pull requests are currently test merged: 
#31727: '[Pls No Forget] Complete rework of brain damage' by XDTM at commit b2c039 
Based off origin/master commit: ef21d9 
Server tools version: /tg/station 13 Server v3.2.0.11 
Server tools API version: 3.2.0.1

**Comment by YPOQ** [comment]
#32736 seems to have fixed this

**Comment by ShizCalev** [comment]
@duncathan

**Comment by praisenarsie** [comment]
https://github.com/tgstation/tgstation/blob/b7a9a2a452466d411115bb9b8d925fd0a02132a3/code/game/objects/items/RPD.dm#L33

why is meter different from the other atmos pipes

**Comment by duncathan** [comment]
They're a totally different type with different behavior. Meters need to be able to attach on top of pipes, which pipes cannot do.

**Comment by ShizCalev** [comment]
Seems that it just isn't kicking into METER_MODE at all

https://github.com/tgstation/tgstation/blob/8e5297e52b1c40ae2d6940cedc9d605b42f42f94/code/game/objects/items/RPD.dm#L349
