### ISSUE TITLE
R&D Console disappears once finished building.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#32936]
Issue reported from Round ID: 79028 (Sybil)

The title says all. Once I finished screwing in the monitor, the whole thing vanished. I guess the recent RND update messed up something.

**Comment by Marflowerose** [comment]
Also happened to me, building R&D console makes it disappear into ether. This did happen on the White Ship if that matters.

**Comment by Marflowerose** [comment]
Same thing happened to cloner computer

**Comment by praisenarsie** [comment]
feature

**Comment by praisenarsie** [comment]
someone test repairing computers with glass.
https://github.com/HippieStation/HippieStation/issues/4953 also it looks like all consoles are affected even though hippie have the old console sprites so @ShizCalev might've dungoofed in his recent computer pr
