### ISSUE TITLE
Reflector angle

### ISSUE THREAD

**Issue by kustridaren** [tgstation/tgstation#32930]
If you write like -45 the sprite moves to correct position but then reflects the emitter beam like it was 45

**Comment by ShizCalev** [comment]
@kevinz000

**Comment by praisenarsie** [comment]
not a kevinz bug for once

@ACCount12 an account bug for once

**Comment by ACCount12** [comment]
Doesn't seem to be my fault, I only touched visuals and some construction/deconstruction stuff. I may take a look at it anyway.

**Comment by kustridaren** [comment]
hmm as of the date 17-11-23 it apears as the reflectors as they start on the map metastation is bugged.

**Comment by Dennok** [comment]
Actual?

**Comment by kriskog** [comment]
This translates to the correct angle now (-45 turns into 315)
