### ISSUE TITLE
when pulling crates and lockers/similar stuff you always face the object your pulling

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#32946]
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by praisenarsie** [comment]
feature though i thought this was supposed to be only for roller beds.

@nicbn ?

**Comment by Cyberboss** [comment]
Intentional

**Comment by nicbn** [comment]
No this feature was supposed to be for everything that's not mob.
If you didn't like it you can revert but I liked it.
