### ISSUE TITLE
Mesons allow you to hear people through walls

### ISSUE THREAD

**Issue by ishitbyabullet** [tgstation/tgstation#32952]
Issue reported from Round ID: 79040 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Ever since shuttle ETA had hit 2:00 or something, I noticed I was flashed and stunned earlier but could still hear. Later on when the shuttle was moving and it was like the last minute, I could hear people talk, emote, and get hit through walls. I even got flashbanged but it didn't make me deaf.

[Directions]: I don't know how to replicate it. I was just told to report it.
![owsasdgasdga](https://user-images.githubusercontent.com/29403316/33046456-03fd9aba-ce1f-11e7-8047-912b91eec60c.png)

I was in a room with no one else in it while wearing a normal headset.

**Comment by newfren** [comment]
I was just hearing people through walls on sybil, no flashbanging occurred, but I was wearing mesons, and when they were removed I could no longer hear through walls.

**Comment by AnturK** [comment]
@vuonojenmustaturska say changes ?

**Comment by WJohn** [comment]
Mesons allow you to hear people through walls outright, now, it seems. It just so happens that wearing a security headset protects your hearing so you'll still be able to hear people through walls immediately after.

**Comment by newfren** [comment]
relevant: you can also seem them doing shit like loading the viro chemfridge, for example, even though they aren't on screen.
