### ISSUE TITLE
Heat Exchange Junction Pipes not functioning correctly... Again

### ISSUE THREAD

**Issue by Sunoplyrus** [tgstation/tgstation#32953]
Issue reported from Round ID: 79043 (Sybil)

![image](https://user-images.githubusercontent.com/31968974/33048338-7ce36686-ce41-11e7-8e9a-d401ab91ce46.png)

They do not connect nor circulate air.
I've also tried connecting it with a 4-Way Manifold and it didn't work as well.

**Comment by FantasticFwoosh** [comment]
Did you wrench it to the floor?

**Comment by praisenarsie** [comment]
he did
