### ISSUE TITLE
Plasmamen cannot breathe plasma, instead breathe air and do not burst into flame when exposed to oxygen.

### ISSUE THREAD

**Issue by ShattForte** [tgstation/tgstation#32962]
Title, basically humans that start with plasmamen suits currently.

**Comment by WJohn** [comment]
wow that's uh, completely broken.

**Comment by Armhulen** [comment]
oh dear

**Comment by Anonmare** [comment]
Ah I see this is the Plasmaman subspecies, the Oxygenman

**Comment by Spaceinaba** [comment]
this is my new favorite bug

**Comment by ShattForte** [comment]
I'm on the server right now, and Plasmamen appear to be working properly. I have no idea why it wasn't working last night.

**Comment by Supermichael777** [comment]
thats why show server revision is so important

Prevents higgs bugsons
