### ISSUE TITLE
Crashing as AI, unpredictable but reproducible

### ISSUE THREAD

**Issue by Eldunari95** [tgstation/tgstation#33000]
Sybil
Round:# 79110, but this can happens on any round/any map.

Issues with AI crashing whether by jumping with cameras or just double clicking tiles, however the issue is reproducible by moving normally.
Here's a few examples

Moving quickly will crash you quite often, here I crash myself twice on purpose in quick succession to prove it's reproducible. 
https://my.mixtape.moe/wfgakl.webm
https://my.mixtape.moe/unfzyg.webm

but it's also possible to crash while moving slowly and non-erratically, straight lines standard with tracking someone.
https://my.mixtape.moe/mlyihe.webm

Edit:
Here's a crash while jumping to a camera target.
https://my.mixtape.moe/dlflsa.webm

This might seem like a non-issue at first glance, simply don't spam your camera around and you'll be fine.
But as AI you have to jump to players who are making requests, and you are often tasked with tracking other players and if they move unpredictably they can abuse this issue. I haven't seen this reported  (at least one closed for not being reproducible) before so I assumed it was just a client issue.

I had a crashing issue previously related to byond using firefox quantum but I no longer have that issue, that one was specific to opening menus.

A short list of things I've tried to rule out this being a client issue:
Reinstalled byond/cleared cache, updated drivers/reinstalled a few to make sure they were properly installed the first time.
Reproduced it on a separate computer at a different location.

**Comment by JJRcop** [comment]
so many big round numbers these days are issues.. what happened to the old days

**Comment by Shadowlight213** [comment]
Not seeing any runtimes related to the AI that round, and  I recall hearing complaints about a similar issue to this before. Might be a byond issue

**Comment by ShizCalev** [comment]
Also see #28689

**Comment by MoreRobustThanYou** [comment]
33000

**Comment by Marflowerose** [comment]
Started happening after moving to the beta BYOND, any camera view tends to crash the game, presumably moving fast would also do it.

**Comment by DaxDupont** [comment]
If it's the byond beta, I saw some bug report with crashes related with lot's of animated things/movement.

**Comment by CPTANT** [comment]
I had the same AI crashes while switching camera's and I don't use beta BYOND

**Comment by DaxDupont** [comment]
@Cyberboss see @CPTANT

**Comment by DaxDupont** [comment]
This is also a relative recent thing so I doubt it's a byond issue unless it was introduced in the stable recently.

**Comment by AlexTheSysop42** [comment]
This also happens as an AI on the derelict station when jumping to certain (most?) on-station cams, on byond 511. Armory (internal) is safe for some reason.

**Comment by Cyberboss** [comment]
Duplicate of #33377

**Comment by Cyberboss** [comment]
@Eldunari95 if your reproduction steps still work please reply in the above issue with the details @MrStonedOne is asking for

**Comment by CPTANT** [comment]
I like how the older report gets marked as a duplicate
