### ISSUE TITLE
Delta kills most of the crew at roundstart

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#33003]
Like 75% of the crew was taking pressure/oxygen damage at roundstart, RIP. 

Apparently there are holes in the map outside HOP/teleporter/god knows where.

**Comment by Ausops** [comment]
there are holes underneath the hop queue shutters for starters

**Comment by epochayur** [comment]
intended, as this keeps them from having to play delta

**Comment by deathride58** [comment]
Thought this was a downstream issue, wtf

**Comment by WJohn** [comment]
Jesus, I thought I covered this. Shit, my bad.
