### ISSUE TITLE
Drop key doesn't work as drone, works as humanoid

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#33017]
Server revision compiled on: 2017-11-22
The following pull requests are currently test merged:
#32751: 'In-code key handling system, Take 2' by ninjanomnom at commit 397c6f
Based off origin/master commit: 2a89f3
Server tools version: /tg/station 13 Server v3.2.0.12
Server tools API version: 3.2.0.1

I'm unable to press HOME to drop but it works as humanoid.

**Comment by praisenarsie** [comment]
It might not work due to that testmerge.

@ninjanomnom

**Comment by ninjanomnom** [comment]
fixed in current pr version
