### ISSUE TITLE
plants are FUCKING HUGE

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#33019]
![2017-11-22_21-04-27](https://user-images.githubusercontent.com/20155238/33157638-0b084aca-cfc9-11e7-8179-8130fbd1ee6a.png)
![2017-11-22_21-03-44](https://user-images.githubusercontent.com/20155238/33157639-0be3a6ce-cfc9-11e7-8f09-47c1b0b99eab.png)
![image](https://user-images.githubusercontent.com/20155238/33157646-128cf34a-cfc9-11e7-96fa-46f06fe91aef.png)

**Comment by Qbopper** [comment]
did someone fuck with the icon vars or did they start this way

**Comment by Spaceinaba** [comment]
I have no idea I joined as the only admin and they're all like this and it's only plants.

**Comment by Spaceinaba** [comment]
A new round has just started and they are still broken so.

**Comment by Qbopper** [comment]
you're supposed to include round id/what's testmerged in issue reports dumb inaba

isn't there a clockcult thing merged rn

**Comment by Spaceinaba** [comment]
fuck

**Comment by Spaceinaba** [comment]
https://github.com/tgstation/tgstation/pull/32935
this is testmerged I think
round id is 79144

**Comment by YPOQ** [comment]
So I was able to fix this on a local server by reverting #32925 but according to Show Server Revision on Sybil (where this bug is happening) they're on commit 3afc40 which is before #32925's commit?

**Comment by ShizCalev** [comment]
@ninjanomnom
