### ISSUE TITLE
Return to Lobby setting doesn't work if you get antag.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#33029]
>Set jobs that you never, ever want to play to "never"
>Set the last-resort option, which is picked if none of your preferred jobs are available, to "return to lobby"
>Round starts
>Get antag
>None of your jobs are available
>Automatically picks the job you hate most in the universe instead of returning you to lobby
>Suicide with a bomb core instead of having to stand even a second of whatever shitty job you got.

**Comment by XDTM** [comment]
Intended

**Comment by alexkar598** [comment]
If I remember right it was because if you returned to lobby while being selected for antag you could get any job and be an antag


I could be also wrong as a wall has more memory than me

**Comment by Cyberboss** [comment]
Intended
