### ISSUE TITLE
Projectiles only fire directly upwards

### ISSUE THREAD

**Issue by Xhuis** [tgstation/tgstation#33020]
This happened on round id 79140.

Projectiles fired from any source (this included clockcult's Kindle scripture and any gun item) only fired north, even at point-blank. I'm not sure of specifics like distance and the like.

**Comment by ShizCalev** [comment]
Likely related to #33019

**Comment by ShizCalev** [comment]
#32925 perhaps?

**Comment by ShizCalev** [comment]
@ninjanomnom

**Comment by Rinoka** [comment]
It looks like it's unrelated to the plant bug; unmerging the hotkey PR fixed the plant bug, but not the guns.

That means it's probably something to do with #32935.

**Comment by Xhuis** [comment]
I tested that issue locally. #32935 does not cause that issue. It was most likely caused by something merged between me starting the patch and its testmerge.

**Comment by Rinoka** [comment]
Next round on Sybil won't have your PR, so we'll know then.

**Comment by Rinoka** [comment]
Unmerging did fix the issue @Xhuis.

**Comment by Xhuis** [comment]
@Armhulen theorized that @AnturK's testmerges were causing the issue and working off of a bad master. I can guarantee that I haven't touched projectiles in my patch and I can get a gif of projectiles working as intended in it it to prove it.

**Comment by AnturK** [comment]
Fixed by #33035
