### ISSUE TITLE
Lathes  and Other Machines are completely non-interactable.

### ISSUE THREAD

**Issue by Boredone** [tgstation/tgstation#33043]
[Directions]: Attempt to interact with lathes, circuit printers, or exosuit fabs. Don't even turn around if you weren't facing it, and nothing at all happens. Mousing over it doesn't even show the name.
Round ID: 79165
Server Revision: https://github.com/tgstation/tgstation/commit/faaf1515807c67100c5f4ad2d324fb29b7c92c60
Nothing Test Merged.

**Comment by praisenarsie** [comment]
sounds like #32305 is back with vengeance

@Cyberboss

**Comment by AnturK** [comment]
Should be fixed with #33045
