### ISSUE TITLE
Nuclear Operative Uplinks Broken

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#33044]
Issue reported from Round ID: 79166 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

[Directions]: Uplinks appear to be regular station bounced radios, do not function properly. Cannot be inserted into management terminals.

**Comment by MrStonedOne** [comment]
all uplinks are broken.

confirmed on a few rounds on sybil

**Comment by DaxDupont** [comment]
@kevinz000 https://github.com/tgstation/tgstation/commit/beb255dbf15c017664b77a4100d484323be97418 ?

**Comment by kevinz000** [comment]
working fine right now, sybil with ninja's math fix testmerged.

**Comment by ShizCalev** [comment]
If reverting math changes fixed it, this can be closed via #33059

**Comment by AnturK** [comment]
Fixed in #33045
