### ISSUE TITLE
fucking with a monkeys dna is just appending its enzymes to itself

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#33042]
@ninjanomnom 

antur says its macro related.

Append a string to itself! out of memory crash within 64 iterations or your money back!

**Comment by AnturK** [comment]
https://github.com/tgstation/tgstation/blob/807311a2cc8952581cd2144322f582286e83b9ca/code/game/machinery/computer/dna_console.dm#L475

Returns 0 so it copytext(blah,0,1) and it all falls down because it's shitcode.
