### ISSUE TITLE
Plasma Sheets make no cargo points for Cargonia when exported.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#33067]
Issue reported from Round ID: 79183 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

I'm not sure if this feature was removed, but plasma sheets give cargo no points at all. Does not matter if the sheets are in a crate or just on the floor of the cargo shuttle. Other metals appear to still give cargo points.

If this was removed, I'm confused as to why the value of plasma would be removed because every other metal has monetary value AND in story, CentCom would love to get their hands that plasma.

**Comment by Repukan** [comment]
Not an issue, intended.

**Comment by Potato-Masher** [comment]
Aw, well that is pretty hecking lame.
