### ISSUE TITLE
Stun bug

### ISSUE THREAD

**Issue by calzilla1** [tgstation/tgstation#33061]
ID:71985 (but has happened multiple rounds in the past)
https://puu.sh/ysm0a/0aac93300c.png
Simply, when ever someone gets stunned their icon goes up one tile, making it impossible to interact with them

**Comment by ShizCalev** [comment]
Likely fixed by #33059

**Comment by ShizCalev** [comment]
Will close in a week if there are no more reports of this.

**Comment by calzilla1** [comment]
Well,  is there any fix for it?

**Comment by jughu** [comment]
He indeed hit the fans

**Comment by ShizCalev** [comment]
@calzilla1 Is it still happening?

**Comment by calzilla1** [comment]
Ill check once I get back on

**Comment by calzilla1** [comment]
Nope, still not fixed

**Comment by calzilla1** [comment]
And when I get electrocuted, my skeleton stays where I was shocked but my body goes off to the side

**Comment by calzilla1** [comment]
THis bug also happens to mutated people

**Comment by calzilla1** [comment]
Ok, so when someone talks, their sprite moves up. I think that may be the source of the problem.

**Comment by calzilla1** [comment]
Lmao new version fixed it
