### ISSUE TITLE
Alt-click doesn't seem to be revealing this massive gear

### ISSUE THREAD

**Issue by DoctoreMad** [tgstation/tgstation#33076]
![00](https://user-images.githubusercontent.com/29125781/33224525-ff8724c4-d148-11e7-9c31-c57981b106d4.png)

How am I going to complete my BRASS TABLE-FULLTILE WINDOW-COGWALL ON FIRST DEFENSE LINE strategy if I can't complete the cogwall and it doesn't appear on alt-click?

**Comment by Xhuis** [comment]
This is an issue with windows as a whole; they prevent you from interacting with anything beneath them, including normal fulltile windows.

**Comment by ChangelingRain** [comment]
this isn't a bug, it's intentional.
