### ISSUE TITLE
Integrated circuits can fire pinless guns 

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#33084]
Heard about this from a player in discord

**Comment by ShizCalev** [comment]
@ACCount12

**Comment by jughu** [comment]
heard it from me heard it from me!

**Comment by ACCount12** [comment]
It's the same as stationary turrets I think. Is this really an issue?

**Comment by jughu** [comment]
Yes it is because its a super simple design and can be used super accurately with an examiner and ranged sensor plus not forgetting you can stack them and have multiple shots

**Comment by ma44** [comment]
The code makes a projectile that the gun uses then fires it, so there needs to be a pin check coded in for it.

**Comment by MrMaclang** [comment]
>makes an aimbot circuit that has 3 adv e guns without pins

**Comment by optimumtact** [comment]
Fixed
