### ISSUE TITLE
Screen still shaking after chemicals are gone from bloodstream

### ISSUE THREAD

**Issue by ShiggyDiggyDo** [tgstation/tgstation#33085]
I drank some Nuke Cola and I got the whole high effect with the screen shaking and the colorful filter, but after the nuka cola was gone from my blood and the rainbow effect stopped my screen was still shaking. I scanned myself with a medical scanner in reagent mode and there were no chemicals in me.

**Comment by jughu** [comment]
Not a bug? Nuka cola is alcohol
