### ISSUE TITLE
Ayylien tech broken

### ISSUE THREAD

**Issue by Metroidlover** [tgstation/tgstation#33097]
Issue reported from Round ID: 79284 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

No specific round, Alien alloy doesn't even have a node assigned to it in the DA and the medical tools give a 0 bonus to the alien tech and alien biotech nodes, which don't appear in the tech list even if you DO DA the tools and alloy.

**Comment by SpaceManiac** [comment]
#33151 should take care of the "0 bonus" thing and make it so the techs show up in the list properly. Alien alloy not being DA'able for anything is a separate issue.

**Comment by Chocodaemon** [comment]
Alien tech is still broken. You can make the node visible if you deconstruct alien tools but cannot unlock the node even with the points required. Let me know if I should open a new issue for this.

**Comment by SpaceManiac** [comment]
Alien alloy being unresearchable (#35102) has something to do with `available_nodes` not updating correctly some of the time, haven't reproduced without varediting yet.
