### ISSUE TITLE
Monkey Mobs can attack while cuffed.

### ISSUE THREAD

**Issue by Nabski89** [tgstation/tgstation#33093]
You can cuff a monkey and it will still bite and tackle you. If you buckled them to a chair/bed they stop.

**Comment by PKPenguin321** [comment]
Intended as they don't need their hands to bite

**Comment by Nabski89** [comment]
So what, player monkeys are too refined for that kind of nonsense?

**Comment by AnturK** [comment]
No, they can do this too.
