### ISSUE TITLE
cycle door code is shit code

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#33103]
they tend to break when 2 people press the botton at the same time which causes them to stop working and the doors are perma closed

**Comment by Cyberboss** [comment]
I know exactly why this happens, I've just been too lazy to properly fix it

**Comment by Eldunari95** [comment]
Please fix it when you can.
I've had this happen a few times from someone standing in the airlock doorway while you're trying to cycle it. Seems pretty consistent, although I've only had people standing in the exterior airlock, I don't know if the same happens to the interior door. Both doors become unresponsive, the only way to fix it ingame is to unbolt, open and close then rebolt. Then it should cycle normally.

**Comment by AlexTheSysop42** [comment]
it happens with the interior door too
