### ISSUE TITLE
Harvesters Cannot Attack Golems

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#33108]
Issue reported from Round ID: 79300 (Sybil)

Harvesters cannot attack golems.

**Comment by Marflowerose** [comment]
Seems to be because Golems can't lose limbs from attacks and Harvester attacks on non-simple mobs are strictly to slice off limbs, not to do damage as such.

**Comment by vuonojenmustaturska** [comment]
i was wondering why i was doing so well against two harvesters as a golem
