### ISSUE TITLE
The Eminence's mass-recall message shows up for ghosts

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#33114]
![image](https://user-images.githubusercontent.com/16315400/33244290-963b861a-d2c2-11e7-8097-76d629adcf12.png)

**Comment by Supermichael777** [comment]
0.9 minutes

I think that should be a seconds counter

**Comment by ShizCalev** [comment]
Testmerge issue #33114

**Comment by ShizCalev** [comment]
also @Supermichael777 i believe a player typed that.
