### ISSUE TITLE
Devils Gamemode Round-End Messages Broken

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#33111]
Issue reported from Round ID: 79304 (Sybil)

It appears that for the players listed as devils, there is some sort of check that doesn't pass. "Target is not a devil."

![dreamseeker_2017-11-26_15-19-06](https://user-images.githubusercontent.com/10467687/33243476-4a5c3366-d2bd-11e7-86a5-6b428106d173.png)

**Comment by praisenarsie** [comment]
@AnturK
