### ISSUE TITLE
Departmental Prolathes Eating My Necropolis Disks

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#33132]
How to reproduce: 1. destroy a necropolis tendril and get a miner disk. 2. Be a confused miner and put design disk in cargo departmental prolathe because thats where all the other miner junk is. 3. Lose disk as the prolathe accepts it but doesn't have any design disk options. 4. That's it.

Changes I want: Departmental prolathes not accepting my design disks if it doesn't work! Stop the sad miners losing there necropolis chest items.

**Comment by praisenarsie** [comment]
there needs to be a list of items which ask you 'are you sure you want to recycle the disk?' if you try to put in a autolathe/protolathe/etc

**Comment by Armhulen** [comment]
i don't even think it should allow people to put the disk in tbh

**Comment by ShizCalev** [comment]
@kevinz000

**Comment by GunHog** [comment]
I think the easiest fix would be to remove the material datum from all disks. No one would care anyway.
