### ISSUE TITLE
 Ahelp tickets from non human mobs are not being shown in chat, but are still visible via tickets.

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#33130]
Issue reported from Round ID: 79333 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Any ahelps from nonhuman mobs aren't being shown to chat. Bwoink still plays and it's still tracked on tickets.

**Comment by FantasticFwoosh** [comment]
Deliberate & canon feature to never reply to lizards or catpeople screaming for help they don't deserve from admins or spamming "Hiss~" or "Nya~"

**Comment by Cyberboss** [comment]
Unable to reproduce
