### ISSUE TITLE
Necropolis gate can be moved by mining shuttle

### ISSUE THREAD

**Issue by Gouty** [tgstation/tgstation#33155]
Reproduction steps:

- Send aux base to lavaland so that the shuttle dock area overlaps with necropolis gate
- Send shuttle to aux base
- Move shuttle anywhere else and the gate will be taken with it

If you have any questions the best person to ask is Cxmu3 who (until I asked them not to) was doing it frequently.

**Comment by Gouty** [comment]
Worth saying that the gate can still be "activated" when it is away from lavaland

**Comment by Armhulen** [comment]
>Cxmu3 who (until I asked them not to) was doing it frequently.
what an asshole

still this is funny as fuck
