### ISSUE TITLE
Cursed Katana cannot be belt worn

### ISSUE THREAD

**Issue by Gouty** [tgstation/tgstation#33168]
this might not be an issue, I might be dumb.

/obj/item/katana/cursed (the one you get from lavaland chest) can't be worn on the belt, at least not with miner gear on.

What is the cursed aspect of it anyway?

**Comment by Gouty** [comment]
Frozenguy5 informs me I am dumb and the cursed aspect IS that it can't be worn.

This could be more obvious as there is nothing that differentiates it from a regular katana in game.

Perhaps a message that comes up when you try and wear it?

**Comment by praisenarsie** [comment]
i never said you were dumb!

**Comment by jughu** [comment]
i thought the cursed aspect was that it was stuck to your hand

**Comment by FantasticFwoosh** [comment]
Cursed objects are supposed to stick to your hand the moment you pick them up.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/8e5297e52b1c40ae2d6940cedc9d605b42f42f94/code/game/objects/items/weaponry.dm#L215

for some reason it doesn't have curse flags but is specifically made to not be worn.

**Comment by coiax** [comment]
this is not a bug.

**Comment by ShizCalev** [comment]
not a bug.
