### ISSUE TITLE
Syndicate flamethrower backpacks from the spetsnaz pyro bundle are shit now

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#33160]
Instead of making halfway decent plasmafires like they used to, they just spray out 3x1 lines of fire that disappear quickly, making it basically useless for crowd control/combat.

**Comment by praisenarsie** [comment]
@Armhulen

**Comment by BeeSting12** [comment]
How is this not a bug when it worked the other way a few weeks ago when I lasted played Syndicate pyro loadout?
