### ISSUE TITLE
Traitorchan Round-End Message Broken

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#33162]
Issue reported from Round ID: 79410 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Only changelings were listed in this round of traitorchan at the end of the round.

**Comment by praisenarsie** [comment]
@AnturK

**Comment by praisenarsie** [comment]
it worked on id: 79431?

**Comment by AnturK** [comment]
It's almost certainly the baddass icon2html issue again, but that's pretty hard to reproduce.

**Comment by AverageJoe82** [comment]
Traitors disappear with out longs being in the game mode also, I’ve had it happen to me on multiple occasions
