### ISSUE TITLE
Supermatter Shard in Extraction Tongs One-Use

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#33161]
Issue reported from Round ID: 79410 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Supermatter shard extracted using extraction tongs [from traitor objective] can only dust a person once. After this, the shard will no longer fall out of the tongs if thrown or affect a player if hit.

**Comment by ACCount12** [comment]
It's supposed to vaporize on the first hit. Is the icon not being updated?

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/7c69cdcb8ad7a731fbf631f7b15e30f12e687036/code/modules/power/supermatter/supermatter.dm#L571

It irradiates the area when it hits something that isn't a machine.

**Comment by octareenroon91** [comment]
https://github.com/tgstation/tgstation/blob/f37c68d959f62d4c0dae90f5a2c9abb1f4e8ef8d/code/game/objects/items/theft_tools.dm#L230

````/obj/item/hemostat/supermatter/throw_impact(atom/hit_atom) // no instakill supermatter javelins````

So, replication would be throw, recover sliver, throw again?

**Comment by octareenroon91** [comment]
OK, there IS an issue. The tongs don't update despite consuming the sliver.
