### ISSUE TITLE
No indication of damage in ash storms as a positronic brain being inside a Ripley

### ISSUE THREAD

**Issue by Bod9001** [tgstation/tgstation#33176]
Issue reported from Round ID: 79436 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

As an positronic brain being inside a Ripley in an ash storm, there is no indication of taking damage so you will just suddenly die when you reach the threshold.

**Comment by vuonojenmustaturska** [comment]
duplicate of #32187 , posibrains are a subtype of MMI

**Comment by AnturK** [comment]
Duplicate of #32187
