### ISSUE TITLE
Cargo conveyor belts appear to use a lots of energy

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#33173]
On Metastation:

1) Before bottom cargo belt is turned on, equipment usage is reported by the APC to be 435W
2) Turning on the bottom cargo belt reports a usage of 10.44 kW

---
Server revision compiled on: 2017-11-29

The following pull requests are currently test merged:
#32487: 'The Thingling' by Armhulen at commit 229339
#33165: 'Revert "Ore Stacking"' by MrStonedOne at commit 8c4885

Based off origin/master commit: 8e1ac5

Server tools version: /tg/station 13 Server v3.2.0.14

Server tools API version: 3.2.0.1

**Comment by AnturK** [comment]
The power use wasn't changed when it was switched to fast processing ?
