### ISSUE TITLE
[URGENT] [VITAL] [TOP PRIORITY] Mice Migration has a low-effort Command Update

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/tgstation#33188]
> **Migration Alert**
> Due to bad luck, a horde of rodents have swarmed into the maintenance areas.

Due to bad luck? What is that garbage. Really low-effort not impressed immersion shattered. Needs better fluff.

How about, 

"Due to pest control equipment cutbacks, a horde of rodents have swarmed into the maintenance areas."
or
"Due to poor sanitary procedures, a horde of rodents have swarmed into the maintenance areas."
or
"Due to a lack of population control, a horde of rodents have swarmed into the maintenance areas."
or literally anything that isn't just bad luck.

I don't want to attack the author or make them feel bad but if they could post a video of themselves being eaten by a swarm of mice that would be fair reparations thanks.

**Comment by epochayur** [comment]
make a PR then

**Comment by Cyberboss** [comment]
Its literally three random lists of descriptors
Due to [A], [B] into [C]
It's fine as is
