### ISSUE TITLE
Disconnected cables still think they are linked

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#33196]
ID: 79502
The following pull requests are currently test merged:
#33151: 'Vastly enhance the R&D Console UI' by SpaceManiac at commit 0fb7f2
#33165: 'Revert "Ore Stacking"' by MrStonedOne at commit 8c4885
#31727: '[Shitcode-Free] Complete rework of brain damage' by XDTM at commit 0795b4
Based off origin/master commit: 8e1ac5
Server tools version: /tg/station 13 Server v3.2.0.13
Server tools API version: 3.2.0.1

This results in rats eating cables not really do anything, the power still moves around normally even though the cables are cut. Probably also means building SMES is honky as the powernets are not refreshed.

**Comment by praisenarsie** [comment]
@ninjanomnom @ShizCalev

**Comment by AnturK** [comment]
Was this happening on ruins or station

**Comment by SpaceManiac** [comment]
Was able to repro on station, have also observed constructed SMES not connecting to the powernet until cable is cut & replaced.
