### ISSUE TITLE
"The floor is lava" event does not treat beds as surfaces you can be on top of.

### ISSUE THREAD

**Issue by Nitrousoxide** [tgstation/tgstation#33194]
Issue: Being on a bed during a floor is lava event does not protect you from lava
How to repeat: buckle yourself to a bed and cause the lava floor event.  Die to lava

It would make sense that chairs/beds/etc should probably all protect from the floor is lava event, provided the user is strapped onto them.

Issue reported from Round ID: 79491 (Sybil)

[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

![image](https://user-images.githubusercontent.com/1363931/33463836-a0545cfa-d60d-11e7-9cdc-0b18ef7daf33.png)

**Comment by PKPenguin321** [comment]
It should just check if you're on the same tile as an anchored object honestly

**Comment by XDTM** [comment]
Should vents count?

**Comment by PKPenguin321** [comment]
I mean technically
Think about it, the floor is lava not the vents
Stand on the vent with one foot and you're good so why not

**Comment by Spaceinaba** [comment]
Also kills people that xenos strap to resin for probably the same reason
