### ISSUE TITLE
When thrown outside a shuttle (with your eyes surgically removed) the parallax visual bugs out?

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#33190]
![2017-11-30_13-58-31](https://user-images.githubusercontent.com/31222036/33455446-06d2263c-d614-11e7-9a97-61d34649e5c6.png)

yucky low res when it should've slowed down into nice high res pixels.

**Comment by Dennok** [comment]
Seems like default hyperspace.
Outdated i think.

**Comment by magatsuchi** [comment]
can't reproduce this one, doesn't seem to apply anymore
