### ISSUE TITLE
the internet thing in circuit sometimes doesnt work 

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#33205]
so uh i had 2 machines linked with the internet thing, works fine but then suddently it stops working (the receiver wont receive ) if i build a  new machine it fixes it (removing and putting it back doesnt fix)  but it happens again after some time

**Comment by SailorDave** [comment]
This is most likely because of the NTnet relay going down. NTnet relies on a physical machine to work, and it can be taken down along with tcomms. To prevent this, I'd suggest building a backup somewhere with an Ntnet relay board.

**Comment by PKPenguin321** [comment]
Not a bug/cannot reproduce, likely what SailorDave said. Should be closed
