### ISSUE TITLE
Ash Walkers Spawn Ambience Cannot Be Muted

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#33212]
Issue reported from Round ID: 79534 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

The ambient sound of [very loud] wind blowing in the Ash Walkers spawn is not muted when "Hear/Silence Ambience" and "Hear/Silence Ship Ambience" are used.

Please help.

**Comment by praisenarsie** [comment]
@ChangelingRain

**Comment by KorPhaeron** [comment]
Think they're talking about the ash storm sounds

**Comment by ShizCalev** [comment]
Doesn't seem like a bug to me, it's not as much an ambience as it is a warning that there's a death storm event going on outside.
