### ISSUE TITLE
[Monkey Mode Related] Monkey Mode Issues

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#33228]
Issue reported from Round ID: 79577 (Sybil)

I was a monkey leader and ended up dead. I got put in the cloner, and scanned, then the person attempting to clone me tried to activate the cloning cycle and the game froze up for an entire minute or two. When I came back, everyone else reported the same problem, and I had the ability to possess and haunt things. I possessed a monkey, and it worked, so it was not just showing up but not letting me actually do anything. On top of that I lost the ability to possess my own body, and in the deadchat, my name had the extension of "died as" except there was no name, it was simply "Loves-the-lizards (Died as ").

**Comment by Jarektheraptor** [comment]
Update: On top of this, monkey leaders are supposed to get an effect called "heart of freedom" which triggers at low health and gives ephedrine and a small heal at low health, this did not happen for either of the existing monkey leaders, One died to beepsky smash stuns and the other to pressure and cold damage. Both times the server froze for several seconds.

The text you start with also states that the jungle fever disease the monkey leaders start with is undetectable by health huds and scanners, except this is not currently true, any health hud and scanner can see it and medibots will even attempt to cure your disease and chase after you saying you're injured. I dont know if they actually can cure jungle fever since I didn't let them try.

**Comment by Cyberboss** [comment]
Report test merge bugs on the PR: #32916
