### ISSUE TITLE
It is possible to park custom destination shuttles very near the z-level edge

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#33252]
![image](https://user-images.githubusercontent.com/609465/33530681-5bd8bd76-d87b-11e7-9e7e-486364babafd.png)

**Comment by ShizCalev** [comment]
@ninjanomnom

**Comment by ninjanomnom** [comment]
the part I fixed is it parking *on* the edge which actualy broke things, if you want to force it further away that's another matter

**Comment by coiax** [comment]
But I hear if you park it near the edge, it's possible to end up INSIDE the ship when transitioning from another z level, or if the ship is small enough, become impossible to enter the ship.
