### ISSUE TITLE
A player was having an issue with their viewport skewing

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#33255]
Round ID 79629

Unrelated to #32950 

23:41:38: TheMythicGhost/(Respii Varenos): I really should issue report this, but since it's clientside, I don't think searching on the round ID list would fix it. Sometimes when initializing the round after the counter has finished, my viewport is skewed to the left. I can provide screenshots if necessary.
23:43:51: TheMythicGhost/(Respii Varenos): http://prntscr.com/hiopp5
23:44:04: PM From Cyberboss/(Maximillian Ryder): will look into it, thansk 
23:44:22: Reply PM from-TheMythicGhost/(Respii Varenos): No problem, it only happens around either round start, or inhabiting a new mob. 
23:47:46: Client disconnected.
23:48:31: Client reconnected.
23:57:09: PM From Cyberboss/(Maximillian Ryder): Has this happened before today? 
23:57:14: Reply PM from-TheMythicGhost/(Respii Varenos): Many times. 
23:57:23: PM From Cyberboss/(Maximillian Ryder): ok thanks

**Comment by duncathan** [comment]
I have experienced this bug locally but haven't a clue what might be causing it

**Comment by SpaceManiac** [comment]
I've had this on Sybil while running 512.1392 client, but never locally. Switching mobs sometimes helps. I also have noticed images being in the wrong place in the HUD, such as hat being mirrored to other inventory slots (visually only, there's still just one hat object) and.

**Comment by vuonojenmustaturska** [comment]
holy shit is that windows xp

**Comment by KomradeSpectre** [comment]
It's not windows xp, but it is the classic mode in Win 7's themes. I'm TheMythicGhost there. Just thought I'd clarify the OS if that had any impact.

**Comment by KomradeSpectre** [comment]
Fixed on the latest beta version (the one that was recently released.), however it is replaced by a bug that lags the client every half second for about 5-10 minutes on round join/start.
