### ISSUE TITLE
Blob preventing Malf-AI's takeover win.

### ISSUE THREAD

**Issue by KomradeSpectre** [tgstation/tgstation#33256]
Round ID# 79632 on Sybil

Not sure if intentional design or bug, the AI could not take station over despite being malfunctioned and meeting all requirements in Delta status after a blob had spawned. Just to clarify, the blob did not take the AI over, nor was near it, but the self-destruct device did not trigger after the blob had spawned.

**Comment by praisenarsie** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
@KomradeSpectre Need more details. Could it not buy the doomsday? Not turn it on? Failed to count down? What messaeges or errors or whatever did it see when it clicked the button?

**Comment by KomradeSpectre** [comment]
I believe it did not count down, or it did not detonate. The AI had succeeded in reaching Delta status and taking over the station, but the nuke did not detonate despite being triggered while a blob was present

**Comment by SuperNovaa41** [comment]
This is probably intended.. the blob is a large round altering event, theres probably something stopping the nuke from being used or something idk

**Comment by SuperNovaa41** [comment]
changed my mind

**Comment by JohnFulpWillard** [comment]
I can't replicate this
![image](https://user-images.githubusercontent.com/53777086/153669287-e4b84c47-6986-4bcd-862f-f6a5c69ea547.png)

**Comment by SuperNovaa41** [comment]
Probably fixed then
