### ISSUE TITLE
You can meta the roundtype easily with command reports

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#33266]
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=14289&p=363004#p362771

**Comment by praisenarsie** [comment]
this is a feature...?

also similar issues have been constantly opened from time to time, just close this.

**Comment by ma44** [comment]
**Feature**

**Comment by ShizCalev** [comment]
that's literally the point of them.
