### ISSUE TITLE
fire extinguisher cabinets can be used at range

### ISSUE THREAD

**Issue by Deitus** [tgstation/tgstation#33289]
https://imgur.com/a/zaqr0

as title says, can be opened and extinguisher taken out 2 tiles away

**Comment by GunHog** [comment]
It could be a pixel shifting thing?

**Comment by Deitus** [comment]
dunno, i tried it on multiple cabinets across metastation and they all did it.

**Comment by GunHog** [comment]
Some (if not all) wall objects are actually on the tile in front of it, instead of on the wall itself. That is my guess as to why that is happening.

**Comment by Deitus** [comment]
if this was intended then its fine, i just saw it and thought it was weird, didnt know if it was a bug or not

**Comment by WJohn** [comment]
Not a bug. Objects are just placed on the floor, then pixel shifted onto the wall. They still have the large reach that all objects and structures do (with the exception of AI turret controls which have too small of a range).
