### ISSUE TITLE
Revenant's defile does not remove salt

### ISSUE THREAD

**Issue by scrubs2009** [tgstation/tgstation#33291]
This has happened every round I've played revenant. Wiki says that defile should remove salt piles but it doesn't. This means that anywhere with salt is permanently impassable to revenants. Even worse, if someone makes a cloud of salt on top of you you are permanently trapped without an admin helping you.

**Comment by AverageJoe82** [comment]
I can fix this as soon as I get home.

**Comment by scrubs2009** [comment]
Luv u bb <3

**Comment by Anonmare** [comment]
Funny, it usually creates it
