### ISSUE TITLE
:h departmental chat radio code is not working

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#33301]
1) Say ":h look this isn't talking on the departmental chat"

Nothing happens.

---

Issue reported from Round ID: 79704 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Server revision compiled on: 2017-12-05

The following pull requests are currently test merged:
#32433: '[READY]Refactors projectile trajectories, fixes piercing projectile inaccuracy and beam rifle visual deflections' by kevinz000 at commit c77ebb

Based off origin/master commit: feae17

Server tools version: /tg/station 13 Server v3.2.0.17
Server tools API version: 3.2.0.1

**Comment by Lumbermancer** [comment]
It's all true and real. I have to :s like a plebe to talk on sec channel now.

**Comment by Cyberboss** [comment]
Fixed
