### ISSUE TITLE
Mechs allegedly do not respect clock cult boundaries

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#33300]
ID: 79703

Gygax mech piloted by a cultist went through a clockwork portal and ended up on the crew side, where he slaughtered the assault team with impunity while they were regrouping in their safe area.
Is there actually a check for cultists inside objects in the clockwork portal?

**Comment by coiax** [comment]
Mechs are **_SpEcIaL_** CODE

**Comment by imsxz** [comment]
I've seen this happen with a durand before, so it's not just a one time thing. It feels so unfair to die to this.
