### ISSUE TITLE
Changelings speak aloud anything they send on the hivemind

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#33304]
![image](https://user-images.githubusercontent.com/609465/33626871-b9ea5b08-d9f3-11e7-928d-d2286648c210.png)
---
Server revision compiled on: 2017-12-05

The following pull requests are currently test merged:
#33246: 'Roundend report refactor' by AnturK at commit 1fd38f

Based off origin/master commit: 40a1de

Server tools version: /tg/station 13 Server v3.2.0.17

Server tools API version: 3.2.0.1

**Comment by Cyberboss** [comment]
Fixed
