### ISSUE TITLE
Hotkey mode keeps activating!

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#33315]
AHHH!!! I have to press tab at least once a minute to keep hotkey mode off what is this madness.

**Comment by ShizCalev** [comment]
get rekt

**Comment by octareenroon91** [comment]
No U. This is impressively obnoxious and means that screen and game are in inconsistent state.

**Comment by MrStonedOne** [comment]
This is a "feature" of the mouse pr that was merged earlier this week. 

That pr is currently on a test merged revert until me an ninja can solve this "feature".

**Comment by Robustin** [comment]
Pretty sure this is completely fixed now.
