### ISSUE TITLE
Protolathes and Exosuit Fabricators do not appear to accept materials

### ISSUE THREAD

**Issue by feemjmeem** [tgstation/tgstation#33321]
This is replicable as of 917572c, with 85ddf6b and 418f9ed testmerged.

Using in-hand materials on protolathes and exosuit fabricators does not result in the materials being consumed by the machine.

**Comment by SpaceManiac** [comment]
@Cyberboss Bisect on this points to #33274.

**Comment by epochayur** [comment]
where's the FUCK tag?

**Comment by octareenroon91** [comment]
Destructive Analyzer material reclamation isn't doing anything either.

**Comment by kevinz000** [comment]
@octareenroon91 fixed soon
