### ISSUE TITLE
Light sources emmiting light even after being broken/affected by power outage event.

### ISSUE THREAD

**Issue by InsaneKatrina** [tgstation/tgstation#33326]
As the title suggests, all light sources act as normal despite being smashed, or affected by a power outage event, however they seem to work accordingly by being turned off with a power switch and when the light tubes/bulps (smashed or not) are removed from their fixtures.

![image](https://user-images.githubusercontent.com/34294901/33645288-4779b2ba-da4a-11e7-80ba-7e59209bbba9.png)
![image](https://user-images.githubusercontent.com/34294901/33645346-96bdda9a-da4a-11e7-8c27-91b2cf44ed2b.png)

Note: Smashed bulps and tubes with light being emmited around as normal, where as a fixture with a removed tube emits no light.

EDIT: I have only noticed this happen on Terry, I'm not sure if this goes to the rest of the servers or if this is in fact that rounds occurance, I will keep an eye on it and edit if I see it again.

**Comment by octareenroon91** [comment]
Can confirm on Terry. A fixture even lit up if when I a broken bulb back in.

**Comment by AnturK** [comment]
@Xhuis

**Comment by Xhuis** [comment]
This is incredibly bizarre. I tested emergency lights thoroughly (for 150 hours, I might add!) and actually made sure that lights worked as normal with breaking, replacing, and the like. I guess running it locally had no lag and thus couldn't reproduce issues caused by server lag.
