### ISSUE TITLE
When Blob reaches critical mass, blob tiles appear on pods that have landed on lavaland.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#33322]
Issue reported from Round ID: 79720 (Sybil)

What it says on the tin. Also, once we opened the door to the pod into a lava river, the blob instantly flooded to every open tile without a wall on it, lava included.

**Comment by Potato-Masher** [comment]
Drat, sorry I forgot to add an image, I was unable to get a screen cap of it.

**Comment by praisenarsie** [comment]
@KorPhaeron i told you this (2 weeks ago or so)

**Comment by kriskog** [comment]
This doesnt seem to be a thing anymore.
