### ISSUE TITLE
Protolathes wont accept minerals!

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#33338]
Testmerge might be responsible: #33082: 'tweaks techwebs' by Dorsisdwarf at commit 418f9e

But yea, can't put jack shit into the protolathes, rendering them useless.

**Comment by Cyberboss** [comment]
R O U N D I D

**Comment by Robustin** [comment]
Uh current round on Bagil, where do I get round ID

**Comment by Spaceinaba** [comment]
in the status tab
you know
where it says round id

**Comment by vuonojenmustaturska** [comment]
dupe of #33321

**Comment by Cyberboss** [comment]
Duplicate of #33321
