### ISSUE TITLE
borgs arent inpaled by clock spear  traps

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#33340]
[Directions]: # The following pull requests are currently test merged: 
#33310: 'Revert "In-code key handling system, Take 2"' by MrStonedOne at commit 85ddf6 
#33333: 'Revert "Removes ComponentActivated in favor of callbacks"' by Shadowlight213 at commit 69008a 
#32935: 'Clockwork Cult Defenses Patch - Leader role, traps and wiring, hulk and mech soft-counters, +more' by Xhuis at commit 383ba1 

Based off origin/master commit: e0487f 
the spear traps that clock cultists can make dont affect borgs (not sure if they take damage but they dont get stuck in one place )

**Comment by Xhuis** [comment]
This is intentional; since they're silicons, a spear couldn't reasonably pierce their casing.

**Comment by ChangelingRain** [comment]
It should probably still do something, since the ratvarian spear both does damage and extra burn damage to silicons.

**Comment by Anonmare** [comment]
Perhaps a brief stun? That or a battery drain

**Comment by Xhuis** [comment]
A battery drain would make sense, plus perhaps a bit of extra damage.

**Comment by Tlaltecuhtli** [comment]
the problem is that a borg went trough a spear maze and activated them all making them useless

**Comment by Xhuis** [comment]
That's actually a bug, as I believe pressure plates shouldn't activate if non-carbon mobs cross them.

**Comment by DaxDupont** [comment]
IIRC they do stun at least
