### ISSUE TITLE
Sloth moves slowly between tiles when being pulled

### ISSUE THREAD

**Issue by epochayur** [tgstation/tgstation#33347]
round ID: 79771

not that big of a deal, but looks weird, produces a jittery effect when pulling quickly

**Comment by KorPhaeron** [comment]
@MrStonedOne

**Comment by OmegaShoots** [comment]
it's a feature

**Comment by epochayur** [comment]
it's literally not, when it's moving on its own, sure but it looks weird as fuck when being pulled

**Comment by MrStonedOne** [comment]
Ya, when we finally do smooth movement and get the community to not throw a fit about it this could be made to account for that until its just how it has to be.

**Comment by vuonojenmustaturska** [comment]
can you change glide_size on the fly? we could make the sloth take on the puller's glide_size, or alternatively make the puller move as a sloth.

**Comment by MrStonedOne** [comment]
@vuonojenmustaturska ya, that is something the smooth movement pr i had up 2 years ago did. it handled setting these things.

The hard part is that you have wait for the glide to finish before you can reset it back, as changing it mid glide causes the atom to jump to the center of the tile the moment the client gets the update msg

**Comment by dragomagol** [comment]
Still a little jittery on the diagonals but works well pulling in a straight line

**Comment by magatsuchi** [comment]
no longer occurs when attempting to reproduce
