### ISSUE TITLE
Latejoiners don't show on AI medical HUD

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#33352]
Round ID: 79783.

Latejoiners didn't show on the AI medical HUD, but they did when deployed to a shell. Latejoiners still showed on the AI security HUD as far as I could tell at the time.

**Comment by GunHog** [comment]
The AI's medical HUD works differently than cyborg ones. **Only people wearing a jumpsuit set to health tracking or higher will appear.** The AI's Security HUD shows only a human's job, never wanted status or implants. Cyborgs have normal medical and security HUDs, so this is why it shows on the shell. As a shell, you are actually playing as a cyborg with the added ability to return to being an AI at will.

**Comment by SpaceManiac** [comment]
User error then.
