### ISSUE TITLE
Smoke machine full of salt produces salt pile on space transit tiles

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#33354]
![image](https://user-images.githubusercontent.com/609465/33714194-03aa6dfc-db46-11e7-8b12-3c9d29f08f9b.png)
---
Server revision compiled on: 2017-12-06

The following pull requests are currently test merged:
#33310: 'Revert "In-code key handling system, Take 2"' by MrStonedOne at commit 85ddf6
#33333: 'Revert "Removes ComponentActivated in favor of callbacks"' by Shadowlight213 at commit 69008a
#32935: 'Clockwork Cult Defenses Patch - Leader role, traps and wiring, hulk and mech soft-counters, +more' by Xhuis at commit 383ba1

Based off origin/master commit: e0487f

Server tools version: /tg/station 13 Server v3.2.1.4

Server tools API version: 3.2.0.1

**Comment by kevinz000** [comment]
salty

**Comment by coiax** [comment]
I mean, I am pretty proud of myself as the revenant for making them cover the ENTIRE shuttle in salt

**Comment by praisenarsie** [comment]
intended feature, i bet if you made a salt grenade it would do the same thing.
