### ISSUE TITLE
Revenant essence HUD is difficult to read on grey

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#33353]
![image](https://user-images.githubusercontent.com/609465/33712388-20042c1a-db3f-11e7-8abe-efaf54f5dd90.png)

---
Server revision compiled on: 2017-12-06

The following pull requests are currently test merged:
#33310: 'Revert "In-code key handling system, Take 2"' by MrStonedOne at commit 85ddf6
#33333: 'Revert "Removes ComponentActivated in favor of callbacks"' by Shadowlight213 at commit 69008a
#32935: 'Clockwork Cult Defenses Patch - Leader role, traps and wiring, hulk and mech soft-counters, +more' by Xhuis at commit 383ba1

Based off origin/master commit: e0487f

Server tools version: /tg/station 13 Server v3.2.1.4

Server tools API version: 3.2.0.1

**Comment by ChangelingRain** [comment]
There's supposed to be a background to that...

**Comment by coiax** [comment]
Maybe it's related to #33363

**Comment by ShizCalev** [comment]
possibly fixed by #33369

**Comment by ShizCalev** [comment]
Pretty sure this was fixed. Will close in a week without another repo.
