### ISSUE TITLE
MY GHOST HAS THE WRONG COLOUR HAIR

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#33363]
![image](https://user-images.githubusercontent.com/609465/33720083-c5f6272a-db5a-11e7-9ce6-cf89233952d9.png)

Braxton Cherry's hair is light blonde, not this blue shit.
---
Server revision compiled on: 2017-12-07

The following pull requests are currently test merged:
#32935: 'Clockwork Cult Defenses Patch - Leader role, traps and wiring, hulk and mech soft-counters, +more' by Xhuis at commit 383ba1
#33333: 'Revert "Removes ComponentActivated in favor of callbacks"' by Shadowlight213 at commit 69008a
#33310: 'Revert "In-code key handling system, Take 2"' by MrStonedOne at commit 0e837a
#33098: '[dnm]Timer queuing tweaks: binary sorted inserts and rolling buckets.' by MrStonedOne at commit 4bb7cc

Based off origin/master commit: a788d4

Server tools version: /tg/station 13 Server v3.2.1.4

Server tools API version: 3.2.0.1

**Comment by coiax** [comment]
This issue is caused by 9aa8a911fa963ac2f40d393b1f0384ae80cb2265

**Comment by ShizCalev** [comment]
@MrStonedOne

**Comment by Spaceinaba** [comment]
immersion: ruined
