### ISSUE TITLE
golem RND console not functioning.

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#33367]
Fuck I really shoulda done this last night...

So basically, at the free golem ship, I built the RND console in the ship. The room was powered, and all the other machines in the ship worked fine, but the RND console showed the unpowered sprite. Literally NOTHING we did to fix it worked. Admin spawned RND consoles didn't function either.

Forgot the round ID but @beesting12 was the admin I was talking to during it, it was SO weird. The ones on station worked fine, only the one in golem ship had issues.

**Comment by Bombpants** [comment]
Are the free golems (and old station) RND stuff using the new RnD code or the old system?

**Comment by imsxz** [comment]
they use techwebs, the new stuff.

**Comment by SgtxRootbeer** [comment]
@kevinz0000

**Comment by KorPhaeron** [comment]
Saw golems doing rnd fine yesterday
