### ISSUE TITLE
Unable to Insert Materials into Engineering Departmental Protolathe

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#33380]
Issue reported from Round ID: 79819 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Title is self explanitory, could not insert glass or metal into the machine even though power was online and there appeared to be no issues.  I attempted reconstructing the machine, and this did not change the issue.

**Comment by Cyberboss** [comment]
Duplicate of #33321
