### ISSUE TITLE
Icons spontaneously changing into something else.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#33385]
![](https://i.imgur.com/PJ607Ye.png)
![](https://i.imgur.com/uogEBL6.png)
![](https://i.imgur.com/ReS4yKv.png)

I really don't understand. People also reported their inernal buttons changing, too. These sprites would randomly disappear and then come back as something else. Vars show nothing is wrong.

**Comment by AnonymousNow** [comment]
Existing; I've had it explained to me as admin fuckery, adventures in varediting and the like.

**Comment by SuperNovaa41** [comment]
I don't think this is a bug anymore

**Comment by timothymtorres** [comment]
Yeah this behavior hasn't been seen in years.
