### ISSUE TITLE
Strange Lighting Bug 

### ISSUE THREAD

**Issue by qbmax32** [tgstation/tgstation#33383]
ROUND ID: 79828, another round on Bagil and another round on Terry (tried all three servers)

essentially, all the tiles that you can't see appear as a bright white rather then black. And a black circle appears to cover this up when I get within 1-2 tiles of areas I can't see. Screenshots below. I've tried the basics, reinstall byond, change versions, clear cache, mess with parallax. 

https://ibb.co/nxLChw

https://ibb.co/caeYpb

https://ibb.co/bKca2w

**Comment by qbmax32** [comment]
As a ghost, with the darkness completely normal, I can see everything like I have Toggle Darkness turned on. 

https://ibb.co/gb67FG

**Comment by praisenarsie** [comment]
bloom bug's brother

**Comment by Bawhoppen** [comment]
Has this happened to anyone again in the past few years?

**Comment by SuperNovaa41** [comment]
I've never seen this, nor have I heard of anyone complaining about this

**Comment by msgerbs** [comment]
Same.
