### ISSUE TITLE
Engineering borg north/south facings are unbalanced/off-center

### ISSUE THREAD

**Issue by vuonojenmustaturska** [tgstation/tgstation#33399]
This hinders improvements
![borgo](https://user-images.githubusercontent.com/20017308/33786521-26fa29aa-dc72-11e7-8b48-2a551c474649.gif)

**Comment by praisenarsie** [comment]
🖕

**Comment by WJohn** [comment]
This is due to engie cyborgs being an even amount of pixels wide. They are actually dead center. The only way to fix this is to either make them thinner, or thicker, in their north and south sprites. Other cyborg types have this as well. I think it's a total non-issue though.ggg

**Comment by feemjmeem** [comment]
critical bug
