### ISSUE TITLE
Being forced to reconnect as the Clockwork Eminent instead makes you a ghost.

### ISSUE THREAD

**Issue by Daundra** [tgstation/tgstation#33401]
Issue reported from Round ID: 79871 (Sybil)

Server crashed during this round while I was the Eminent. I was currently viewing the station and after I was able to reconnect to the server, I instead rejoined as a ghost. Attempting to reenter my body gave the "You have no body" message.

**Comment by YPOQ** [comment]
#33752

**Comment by ShizCalev** [comment]
fixed
