### ISSUE TITLE
Toggle Internals HUD icon now has a Ratvarian Speach bubble icon

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#33403]
Issue reported from Round ID: 79872 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

And my screenshot didn't save. Great. Basically, the icon has swapped to the tiny icon that appears next to players when they speak. It's specifically the Ratvarian Question bubble.

**Comment by praisenarsie** [comment]
it's just some corruption or a higgs-bugson i had this before but it was a different icon

i'm betting it's your byond being corrupted 🤷‍♂️

**Comment by Potato-Masher** [comment]
My friend who was on the server at the time originally pointed it out to me; we both had the same issue, with the same icon. Seems kinda odd really, since just the other day it was fine.
