### ISSUE TITLE
thermals don't seem to work

### ISSUE THREAD

**Issue by Ausops** [tgstation/tgstation#33409]
#33310: 'Revert "In-code key handling system, Take 2"' by MrStonedOne at commit 0e837a
Based off origin/master commit: e82fb4
Server tools version: /tg/station 13 Server v3.2.1.4
Server tools API version: 3.2.0.1

screen is very very dark and no mobs appear

**Comment by JohnMcLaime** [comment]
Uncuck thermies

**Comment by WJohn** [comment]
![](https://i.imgur.com/fFi4BJi.png)

**Comment by Ausops** [comment]
oy vey we are losing TCs from having to refund them all the time

**Comment by JamesDenholm** [comment]
Yeah, this is still an issue.
