### ISSUE TITLE
The deadline for "Remove ui_action_click()" is soon.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#33408]
https://github.com/tgstation/tgstation/milestone/17
https://github.com/tgstation/tgstation/milestone/17
https://github.com/tgstation/tgstation/milestone/17
https://github.com/tgstation/tgstation/milestone/17
https://github.com/tgstation/tgstation/milestone/17

https://github.com/tgstation/tgstation/search?utf8=%E2%9C%93&q=ui_action_click%28%29&type=

31 Dec

**Comment by Cyberboss** [comment]
Fuck off
