### ISSUE TITLE
Blindfolds still block vision with xray and thermal eyes.

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#33404]
dumbest issue report I've ever done but I feel like reporting it anyways because I cant do funny blind swordsman gimmicks with this

**Comment by praisenarsie** [comment]
dupppppppppppppppppppppeeeeeeeeeeeeeeeeeee

**Comment by YPOQ** [comment]
#25531

**Comment by ShizCalev** [comment]
duplicate of #25531
