### ISSUE TITLE
Voice of god "play dead" is an instant kill to nuke ops with explosive implants.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#33406]
As it forces you to deathgasp, it will cause you to explode.

This is fucking retarded.

**Comment by WJohn** [comment]
![](https://i.gyazo.com/54e4c5e46d125511577fc57362242f67.png)

**Comment by praisenarsie** [comment]
LOL

**Comment by MoreRobustThanYou** [comment]
i thought Play Dead was removed

**Comment by WJohn** [comment]
This one was caused by brain damage lines, in particular.

**Comment by RandomMarine** [comment]
Already brought up and dismissed in #29818

Only difference now is that the brain trauma exists.

**Comment by WJohn** [comment]
Except this can be spammed by anyone who has brain trauma.

**Comment by praisenarsie** [comment]
> LOL

**Comment by RandomMarine** [comment]
Anyone that's lucky enough to roll godwoken syndrome when there's nuke ops AND is lucky enough for it to trigger while ops are in range.

This is only a problem if it becomes a regular occurrence.

**Comment by BeeSting12** [comment]
Make bowmans block VOG

**Comment by Ausops** [comment]
brain trauma simply shouldn't give VoG but VoG should continue to cuck nuke ops.

**Comment by praisenarsie** [comment]
>>LOL

**Comment by Repukan** [comment]
Feature

**Comment by Kromgar** [comment]
I think the [Edge Case] tag needs to be added

**Comment by XDTM** [comment]
since we have an action button for explosive implants anyway we can retire activating them via emote if this is a problem

**Comment by ExcessiveUseOfCobblestone** [comment]
> brain trauma simply shouldn't give VoG but VoG should continue to cuck nuke ops.

**Comment by praisenarsie** [comment]
>>>LOL
