### ISSUE TITLE
the circuit conponent " advanced list locator " doesnt work

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#33416]
it never worked
why the fuck does it need a list of types

**Comment by ShizCalev** [comment]
@ACCount12

**Comment by arsserpentarium** [comment]
it needs list of names.

**Comment by Tlaltecuhtli** [comment]
what do you mean by names? like refs? @arsserpentarium

**Comment by arsserpentarium** [comment]
It means list like ["orange","potato","carrot"]
List of strings. Not names

**Comment by arsserpentarium** [comment]
Not refs. Sorry
