### ISSUE TITLE
Potassium+Water fruit bombs dont work properly

### ISSUE THREAD

**Issue by uBadush** [tgstation/tgstation#33412]
i made a fruit with 

water, potassium, separated chemicals, liquid contents

when i throw the fruit at someone who is standing the fruit just explode on the floor and does no damage to the target as he wasnt here
but when the target is on resting position, lying on the floor he take the damage

it it supposed to be this way ?

**Comment by praisenarsie** [comment]
pretty sure liquid contents _might_ be broken

**Comment by Potato-Masher** [comment]
Hm. That explains why my exploding bananas did jack shit against those silly warops the other day.

Still got one with my friend's slippery watermelons. They never expect the melons.
