### ISSUE TITLE
thermals broke

### ISSUE THREAD

**Issue by RobustAndrun** [tgstation/tgstation#33411]
Issue reported from Round ID: 79889 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

[Directions]: 
thermals don't give thermal vision, they just make it look really dark

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by ShizCalev** [comment]
duplicate of #33409
