### ISSUE TITLE
Name Bug Thingy What

### ISSUE THREAD

**Issue by letmepickausernamedammit** [tgstation/tgstation#33421]
Problem Description: Name for my character keeps changing back to the previous name

What did you expect to happen: To actually have my name

What happened instead: Had the name of my previous name for my character

Why is this bad/What are the consequences: Humans aren't given Lizard names and it's getting annoying for me

Steps to reproduce the problem: Literally just join the game

Server: Bagil

Revision: No idea so I'll copy paste this Server revision compiled on: 2017-12-08

The following pull requests are currently test merged:
#33310: 'Revert "In-code key handling system, Take 2"' by MrStonedOne at commit 0e837a

Based off origin/master commit: e82fb4

Server tools version: /tg/station 13 Server v3.2.1.5

Server tools API version: 3.2.0.1

Current Informational Settings:

Protect Authority Roles From Traitor: 1

Protect Assistant Role From Traitor: 0

Enforce Human Authority: 1

Allow Latejoin Antagonists: 1

Enforce Continuous Rounds: 9 of 18 roundtypes

Allow Midround Antagonists: 6 of 18 roundtypes

All Game Mode Odds:

traitorchan 24.5%

traitor 18.4%

clockwork_cult 8.2%

cult 8.2%

secret_extended 2%

nuclear 16.3%

revolution 12.2%

wizard 10.2%

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): I can temporarily fix it by changing the name, but it seems to be the next time I load the server after exiting BYOND, my name is back to my previous character's name.

Thanks for helping us out!

**Comment by praisenarsie** [comment]
did you click save setup

**Comment by Tlaltecuhtli** [comment]
did you turn it on and off

**Comment by ShizCalev** [comment]
Will close in a week without reply.
