### ISSUE TITLE
Engineering Cyborg Station blueprints don't show pipes and wires.

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#33429]
Issue reported from Round ID: 79928 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Viewing station blueprints as a engineering cyborg doesn't show the layout of wires and pipes.
Tried hiding and showing the floorplans a few times, didn't work.

**Comment by nemvar** [comment]
This works now, but we have different problems.
