### ISSUE TITLE
N2O is invisible.

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#33439]
round id 79947
commit https://github.com/tgstation/tgstation/commit/e13513ac9d03b5e045940c5c2171b28c5932d6a5
there was enough n2o to knock out but no one could see it, no overlays.
high as 5% from atmos scanners.

**Comment by duncathan** [comment]
Are you on 511 or 512? That was a Sybil round so if you're running 511 then this issue can be closed as it's known behavior

**Comment by praisenarsie** [comment]
what dunc said

**Comment by ShizCalev** [comment]
Tested on 512, overlays functioning as intended.
