### ISSUE TITLE
Skewium glitching out and completely blinding consumer

### ISSUE THREAD

**Issue by KomradeSpectre** [tgstation/tgstation#33431]
Round #79931 on Sybil
I had been force-fed skewium, and aside from making my screen flip the fuck out, it completely blinded me after a short while. 

![image](https://user-images.githubusercontent.com/12734451/33800556-198a3514-dd10-11e7-8726-8005b2034517.png)

**Comment by Iamgoofball** [comment]
https://file.house/IcY3.webm

Close this.

**Comment by Iamgoofball** [comment]
@KomradeSpectre What are your specs, exactly? Include BYOND version and your IE version
