### ISSUE TITLE
Inserting metal into protolathes also slaps the lathe with the metal

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#33437]
Also affects circuit imprinter. Autolathe is fine.

**Comment by vuonojenmustaturska** [comment]
also exofabs. it also damages the exofabs.

**Comment by Cyberboss** [comment]
Fixed by #33436

**Comment by MrDoomBringer** [comment]
what the fuck how did i fix this

**Comment by Cyberboss** [comment]
https://github.com/tgstation/tgstation/pull/33393/files#diff-35d0e1f29d703c7c145b5f04ab3df9fcR70

**Comment by Cyberboss** [comment]
oh wait wrong PR

**Comment by MrDoomBringer** [comment]
i was so confused haha
