### ISSUE TITLE
Destroying an assmos canister will give it the caution destroyed sprite

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#33448]
I destroyed a pluoxium canister and it had the caution destroyed sprite.

**Comment by ShizCalev** [comment]
![image](https://user-images.githubusercontent.com/6209658/33808897-bc5cd4ee-ddbb-11e7-8420-4814ff0f1e3c.png)
unable to reproduce.

**Comment by praisenarsie** [comment]
It had about 700-900kpa of -182 degrees or so of Pluoxium. I broke it as a zombie, also it didn't spray any pluoxium around once it broke. I also broke a plasma canister but that had the right sprite and it spewed plasma around.

**Comment by YPOQ** [comment]
Relabeled canisters revert to their initial icon state when destroyed. I can't think of a good way to rewrite this.
https://github.com/tgstation/tgstation/blob/fc9b7eca534d236b22de5d141e453c070f64db24/code/modules/atmospherics/machinery/portable/canister.dm#L220
