### ISSUE TITLE
Round starts with shuttle half docked on Omega, Delta

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#33459]
![image](https://user-images.githubusercontent.com/609465/33828971-1ed9a0fc-de66-11e7-97a7-369dc3cc8bfc.png)

---
Round ID: 80022
Server revision compiled on: 2017-12-11

The following pull requests are currently test merged:
#33216: 'Player Z-tracking, again' by vuonojenmustaturska at commit 84a514
#33310: 'Revert "In-code key handling system, Take 2"' by MrStonedOne at commit 0e837a

Based off origin/master commit: 1f32d1
Server tools version: /tg/station 13 Server v3.2.1.8
Server tools API version: 3.2.0.1

**Comment by coiax** [comment]
Present on DeltaStation at 1ab2a7c90f0a588779299bb04c41d64495c44bf6
![image](https://user-images.githubusercontent.com/609465/33829168-09225474-de67-11e7-8612-76776a3f1093.png)

**Comment by coiax** [comment]
According to my bisect, this started in commit 8edd8e9a9ad64dc55d0765ffcc56a0b1ed5761ff

**Comment by coiax** [comment]
that makes no sense, however...

**Comment by praisenarsie** [comment]
@ninjanomnom 🕵️

**Comment by ninjanomnom** [comment]
`-` was supposed to be `+`
