### ISSUE TITLE
Cannot Insert Materials into Departmental Lathes that don't have an R&D console in the same room.

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#33455]
Issue reported from Round ID: 80006 (/tg/Station Bagil [ENGLISH] [100% FREE LAG])

Like the title says, can't insert materials into lathes in rooms that lack an R&D console. Building an R&D console in the room with the lathe allows you to insert materials.

Reproducible in pretty much every single round I've played in the past few days.

**Comment by ShizCalev** [comment]
@kevinz000

**Comment by Tlaltecuhtli** [comment]
can we just remove machine synching with consoles and leave it like it was when dep lathes were first merged? its a dumb mechanic that doesnt contribute in improving gameplay

**Comment by Cyberboss** [comment]
This has been fixed, servers weren't updated
