### ISSUE TITLE
Smoke machine's radius cannot be increased beyond 9 when upgraded.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#33453]
It contains the following parts:

 Smoke Machine (Machine Board).

 Some glass.

 A quadratic capacitor.

 A bluespace matter bin.

 A bluespace matter bin.

 A femto-manipulator.

 A bluespace power cell.

Max radius was 9. The machine was wrenched down. Clicking any number above 9 did not change the radius.

**Comment by Cyberboss** [comment]
I specifically told the guy to make it upgrade with components

**Comment by vuonojenmustaturska** [comment]
![image](https://user-images.githubusercontent.com/20017308/33837355-be164d2c-de94-11e7-9be0-6a5fa9df06d9.png)

Guess what, that didn't happen

**Comment by praisenarsie** [comment]
_grumble grumble_

**Comment by Buggy123** [comment]
fuckin finish your job u blubbering code-slave ffs istg wtf wdfdtfbtta

**Comment by nicbn** [comment]
Fix this or remove
