### ISSUE TITLE
Clockwork Eminence makes sound effects when walking over broken glass

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#33461]
1) be eminence
2) walk over broken glass

---
Server revision compiled on: 2017-12-11
Round ID 80026
The following pull requests are currently test merged:
#33310: 'Revert "In-code key handling system, Take 2"' by MrStonedOne at commit 0e837a

Based off origin/master commit: 1f32d1

Server tools version: /tg/station 13 Server v3.2.1.8

Server tools API version: 3.2.0.1

**Comment by praisenarsie** [comment]
#33422 is similar (dupe)
