### ISSUE TITLE
reinforcement ops spawn w/o gear or syndicate faction or antag status

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#33469]
[Directions]: # (INCLUDE THE ROUND ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by ShizCalev** [comment]
@AnturK

**Comment by AnturK** [comment]
Any round ID
