### ISSUE TITLE
No Genetic Cloner Boards

### ISSUE THREAD

**Issue by Seagleb** [tgstation/tgstation#33464]
It appears that when science research was fixed that genetic circuit boards were not re-added back anywhere.  I checked engineering and medical.  It is researched, no boards are showing in the circuit imprinter in engineering and there is no circuit imprinter in medical. Other researched boards are appearing in engineering however.

Round ID: 80035

**Comment by praisenarsie** [comment]
it's probably better if it stays like this because i hate how people make dozens of cloners and plop them around the station

**Comment by epochayur** [comment]
uh oh, narsie doesn't like something, better not fix it

**Comment by ShizCalev** [comment]
It should be under Medical Machinery.

**Comment by Dorsisdwarf** [comment]
I think the issue is that the design is medtech, but medbay doesnt have an imprinter to make the boards?

**Comment by Marflowerose** [comment]
Also applies to many engineering designs and hydroponics designs, even the "omni" circuit imprinters cannot print any of them even after researching everything
