### ISSUE TITLE
Free GBP to anybody willing to remove some legacy code

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#33473]
### Remove this check, make it set the fps var directly
https://github.com/tgstation/tgstation/blob/3d813853b5a98d26efde877b80382fe7d49bdbba/code/modules/client/client_procs.dm#L196-L197

### Remove this check
https://github.com/tgstation/tgstation/blob/08504355d4f716813c36826d2362ba03e5a066bf/code/_onclick/hud/parallax.dm#L63-L64

### Remove these byond_version checks and make it set the fps var directly
https://github.com/tgstation/tgstation/blob/ddc060f963e19e81c58774e61d16b14a359823e0/code/modules/client/preferences.dm#L1137-L1145

@Armhulen

**Comment by Shadowlight213** [comment]
@everyone
