### ISSUE TITLE
Shuttle hyperspace ripples don't appear

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#33479]
>wizard
>orders meteor shuttle
>it arrives without ripples
>i thought it wasn't going to gib me
>gibbed
>no warning

@ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom @ninjanomnom

**Comment by Bawhoppen** [comment]
>killed by a shuttle

**Comment by vuonojenmustaturska** [comment]
i ded

**Comment by Cruix** [comment]
https://github.com/tgstation/tgstation/commit/7848d73acc990904b217a38dcbef883a3d701050#diff-8d50796c8e2b4ec669f94278cf488abdR463 ?
