### ISSUE TITLE
Battle cruiser shuttle spawning 2 of everything

### ISSUE THREAD

**Issue by Michael-Ashfield** [tgstation/tgstation#33491]
#80083 Bagil. Box station

The Centcom battle cruiser escape shuttle spawned 2 sleepers stacked on top of each-other, making 4 sleepers in total when there should just be 2 on the shuttle.
This is the same for the recharger, suit storage, chairs and much of the other items on the shuttle, hough it seems that walls and floors are only spawned once.

**Comment by praisenarsie** [comment]
@ninjanomnom 🕵️

**Comment by AnturK** [comment]
Fixed by #33462 
Server needs update.
