### ISSUE TITLE
New movement system is janky as FUCK

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#33502]
Good things about new movement:
1: diagonal movement
2: movement isn't _negatively_ affected by lag

downsides:
1: essentially, the server assumes that you held a key unless informed otherwise.

let me repeat that:

# **_THE SERVER ASSUMES YOU KEEP HOLDING A MOVEMENT KEY DOWN IF YOU LAG_**

Why is this bad, might you ask?

A:
![image](https://user-images.githubusercontent.com/16315400/33928948-adfed40a-dfb5-11e7-9cb0-524915e0ee83.png)
B:
(picture of a chasm here)

"walk directly next to things which will instantly kill you if you misstep" is LITERALLY HALF OF MINING'S JOB. I have died THREE TIMES in the past SIX ROUNDS directly because of this. YES, because of NEW MOVEMENT, I know this because I almost exclusively play mining and before it went in, I DIDN'T die constantly to instant permakill chasms.

We can no longer precisely control our character. Fix this or remove instantkills for missteps.

**Comment by ninjanomnom** [comment]
We can't fix lag. Either you overstep or understep due to it and the better choice for people who have bad ping is the overstep. Just move a bit more carefully near lava/dangerous things.

Quite a few people have said this is *more* responsive so that's up to opinion.

**Comment by lzimann** [comment]
This is actually a legit issue, even on slower movement this can fuck you up royally.

**Comment by Buggy123** [comment]
>This is actually a legit issue, even on slower movement this can fuck you up royally.
