### ISSUE TITLE
MINDSWAP EVENT CAUSES EVERYONE'S HEAD TO FALL OFF

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#33500]
Race Swap has just been randomly triggered!

Freyja the Unending has hit the supply console with Freyja the Unending's head!

(F) Briana Schofield has died at Arrival Shuttle.

(F) Jorge Henry has died at Aft Primary Hallway.

(F) Sick Boye has died at Fore Primary Hallway.

(F) Aidan Whittier has died at Cloning Lab.

(F) Little Jimmy has died at Chemistry.

(F) Pajeen-Deekus has died at Central Primary Hallway.

(F) Chloe Chatreuse has died at Robotics Lab.

(F) Clutches-The-Crusher has died at Medbay Central.

(F) Kellen Christman has died at Chemistry.

(F) Alice Tanner has died at Surgery.

(F) Frank Izelmann has died at Xenobiology Lab.

(F) Butch Clark has died at Teleporter Room.

(F) Potato has died at Unexplored Location.

(F) Smoke Lewis has died at Aft Primary Hallway.

(F) Marco Bicknell has died at Central Primary Hallway.

(F) Richardo Zamenhof has died at Medbay Central.

(F) Fiona Langston has died at Cargo Bay.

(F) Keaton Wood has died at Arrival Shuttle Hallway.

(F) Zackary Pinney has died at Council Chamber.

(F) Receives-The-Beatings has died at Port Primary Hallway.

(F) Jack Tancosson has died at Locker Room.

(F) Mute Honking Chen has died at Surgery.

(F) Lukas Moon has died at Surgery.

(F) Ed Smith has died at Hydroponics.

(F) River Buzzard has died at Hydroponics.

(F) Mario Saylor has died at Lavaland Wastes.

Freyja the Unending seizes up and falls limp, her eyes dead and lifeless...

(F) Freyja the Unending has died at Cargo Bay.

(F) Diamond Zeal has died at Labor Camp.

(F) Melody Starlight has died at Space.

(F) Laura Kohr-Ah has died at Brig.

(F) Mikey Guidolini has died at Medbay Central.

(F) George Hathcock has died at Bridge.

(F) Theo Legend has died at Central Primary Hallway.

(F) Manuel Stein has died at Surgery.

(F) Rachel Zimmer has died at Surgery.

(F) Artyom Kozlov has died at Surgery.

(F) Lane Stewart has died at Lavaland Wastes.

(F) Kira Yoshikage has died at Library.

(F) Jaye Snyder has died at Transfer Centre.

(F) Ben Dover has died at Robotics Lab.

(F) Lillith Stugz has died at Custodial Closet.

(F) Goh-Bijoh has died at Medbay Central.

(F) River Callison has died at Space.

(F) Imani Bicknell has died at Chemistry.

(F) Boots McGee has died at Brig.

(F) Jell E. Donnit has died at Research and Development.

(F) Lyla Parker has died at Library.

(F) John Prodman has died at Mining Office.

(F) Clayton Prescott has died at Brig.

(F) Freya Milne has died at Chemistry.

(F) Phyllida Pierisame has died at Surgery.

(F) Phoebe Lotsu has died at Surgery.

**Comment by PKPenguin321** [comment]
uh ohhhh

**Comment by Doppeltongue** [comment]
This probably needs a priority fix, because it means that wizard summon events can randomly kill everybody.

**Comment by davethwave** [comment]
No no, this is obviously a feature.

**Comment by AnturK** [comment]
Pretty hilarious.

Was #33465 testmerged ? Also : ROUND ID.

**Comment by XDTM** [comment]
Race swap into dullahan?

**Comment by AnturK** [comment]
Ah yes, that seems more likely.

**Comment by vuonojenmustaturska** [comment]
This is very possibly something #33465 could cause, but you've provided absolutely no information on where I could look for further information.

**Comment by SpaceManiac** [comment]
It's race swap into dullahan. I've reproduced.

**Comment by Tlaltecuhtli** [comment]
intended gameplay

**Comment by JJRcop** [comment]
rename issue to race swap

**Comment by praisenarsie** [comment]
i wish halloween horseshit was still a milestone @ShizCalev

**Comment by JJRcop** [comment]
It is! https://github.com/tgstation/tgstation/milestone/32

**Comment by imsxz** [comment]
feature

**Comment by praisenarsie** [comment]
just blacklist dullahans from the event

**Comment by Doppeltongue** [comment]
Turns out romerol zombies is also on the race change event list, which means that everybody loses their arms, counts as dead for round end, and have no non-zombies to kill.

**Comment by Robustin** [comment]
Yea its pretttty bad

**Comment by pyronie** [comment]
its a feature

**Comment by MrMaclang** [comment]
headswap

**Comment by KorPhaeron** [comment]
This got fixed I'm pretty sure
