### ISSUE TITLE
Progress bars move far away for some reason

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#33514]
![2017-12-13_20-45-07](https://user-images.githubusercontent.com/31222036/33962556-df0fa59e-e049-11e7-92c4-5af3ef21cb44.png)
it switched positions randomly

**Comment by praisenarsie** [comment]
The following pull requests are currently test merged:
33460: 'Re-Support old hotkey mode behaviour' by ninjanomnom at commit d0e455


Based off origin/master commit: 16a8b1

Server tools version: /tg/station 13 Server v3.2.1.8

Server tools API version: 3.2.0.1

**Comment by Cyberboss** [comment]
forget all that just giff round id!!!

**Comment by praisenarsie** [comment]
whoops roundid 80140 terry

**Comment by Mothblocks** [comment]
haven't seen this in my life so i'll assume it's fixed
