### ISSUE TITLE
XENOBIO SLIME EXTACTS ARE BROKEN

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#33518]
The following pull requests are currently test merged: 
#33460: 'Re-Support old hotkey mode behaviour' by ninjanomnom at commit d0e455 
#33470: 'Refactors reagent container types' by ACCount12 at commit 9de85e 
#33480: 'Deadmin tweaks: Admins without +AUTOLOGIN start deadmined. AUTOLOGIN defaults to on.' by MrStonedOne at commit 2ac9d8 
#33465: 'Replaces a bunch of loc assignments with forcemoves and moves to nullspace' by vuonojenmustaturska at commit b82ed5 

you cant extract chemicals from the slime extracts

**Comment by vuonojenmustaturska** [comment]
**R O U N D I D**

**Comment by ShizCalev** [comment]
Caused by testmerged PR #33470
