### ISSUE TITLE
After some recent merges, auto and protolathes have been draining APCs far more than they should be. You cant use a lathe more than 5 times on a full apc, before equipment is shut off.

### ISSUE THREAD

**Issue by YogsMcree** [tgstation/tgstation#33522]
Just go to science at roundstart, use the lathe a few times and cry as you cant print anymore delicious large beakers or .38 speed loaders

**Comment by Tlaltecuhtli** [comment]
sounds like a feature fuck infinite power

**Comment by praisenarsie** [comment]
> sounds like a feature fuck infinite power

![nick-young-confused-face-300x256_nqlyaa](https://user-images.githubusercontent.com/31222036/34004762-ad1501ae-e0f0-11e7-8055-12b9b69e4df1.png)

**Comment by Cyberboss** [comment]
Here are the use_power lines that weren't running before but now are

https://github.com/tgstation/tgstation/blob/master/code/modules/research/rdmachines.dm#L113

Need to be adjusted sanely
