### ISSUE TITLE
Moving diagonally can make you exit a ventcrawl

### ISSUE THREAD

**Issue by AverageJoe82** [tgstation/tgstation#33528]
[Directions]: # (INCLUDE THE ROUND ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

I noticed this while I was testing a bug on a clone of the master branch. It also appears that if you would move diagonally on a tile that has another pipe then you will swap to that pipe instead of exiting the ventcrawl.

**Comment by WJohn** [comment]
Confirmed, it can cause you to exit vents that are in the total opposite direction of the diagonal you are trying to move in, and you can also swith into other pipe systems ENTIRELY if they border yours.

**Comment by AverageJoe82** [comment]
Just to clarify I mean to say you can pop out of the floor anywhere so long as you input a diagonal move.

**Comment by praisenarsie** [comment]
@ninjanomnom

**Comment by PKPenguin321** [comment]
I think this is a dupe

**Comment by ShizCalev** [comment]
@ninjanomnom :(
