### ISSUE TITLE
White Ship counts as you getting marooned when roundends.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#33520]
roundid 80140

**Comment by Marflowerose** [comment]
Was the ship in transit when the actual evac started? That tends to cause you to get stuck in hyperspace

**Comment by SpaceManiac** [comment]
Normal escape shuttle also seems to be counting as marooned, round 80172.

**Comment by JamesDenholm** [comment]
Can confirm this happened to me, though I was in crit at the time.
