### ISSUE TITLE
Jump boots don't let you jump over lava.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#33526]
NOT sure if this is intentional or not, but if you try to jump over lava with jump boots you still catch fire and take damage. I was under the impression that they were intended to be used for jumping over lava lakes.

**Comment by Spaceinaba** [comment]
I think they're just for jumping over chasms (and tables because fuck climbing) but I could be wrong

**Comment by RandomMarine** [comment]
See #25858

**Comment by Buggy123** [comment]
Okay, didn't see that before... but wait...
>Not going to be fixed because of the balance issues it causes, change jumpboots to give you a different movement type that gives more immunity

So... he said "Not going to be fixed, fix it" and then closed it...?

Well, the consensus seems to be "fix it but don't make thrown mobs immune to lava" so this can stay open.

**Comment by vuonojenmustaturska** [comment]
As mentioned in the other issue, I've outlined a very easy, "proven" way to fix jump boots. However, i have no damn idea what "balance" tg has around lava. The only thing where lava actually plays a part is the gulag? What sort of gulaggers have jump boots? And also, you can literally already just... walk across and roll the fires away on the other side. or if you don't want to play the odds, eat a donk-pocket before you do or run inside the lavaland base and put yourself out with the emergency extinguisher stored next to the vending machines.

**Comment by ShizCalev** [comment]
Not to be fixed per #25858
