### ISSUE TITLE
Division by zero by plasmic fusion

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#33532]
Issue reported from Round ID: 80176 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% LAG FREE])
![image](https://user-images.githubusercontent.com/2003111/33988932-c3f2d246-e07a-11e7-8823-189ef8af3051.png)

The following pull requests are currently test merged:
#33460: 'Re-Support old hotkey mode behaviour' by ninjanomnom at commit d0e455
#33470: 'Refactors reagent container types' by ACCount12 at commit 9de85e
#33480: 'Deadmin tweaks: Admins without +AUTOLOGIN start deadmined. AUTOLOGIN defaults to on.' by MrStonedOne at commit 2ac9d8
#33465: 'Replaces a bunch of loc assignments with forcemoves and moves to nullspace' by vuonojenmustaturska at commit b82ed5

**Comment by praisenarsie** [comment]
SOMEONE ATTEMPTED FUSION?

also, @duncathan

**Comment by evsey9** [comment]
fusion is ass-easy to do
