### ISSUE TITLE
White ship shuttle mobile dock is on zlevel 2 while the ship is in transit space

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#33533]
Ship was pretty blown up, the tile with the docker is obliterated.
Round ID 80176

**Comment by WJohn** [comment]
how the hell??? shouldn't they be connected by the area, not by actual physical tiles? how did this even happen

**Comment by AnturK** [comment]
@ninjanomnom

**Comment by MrMaclang** [comment]
use those special docking consoles, set the location to the shuttle would normaly dock, then set your destination to the normal docking area

**Comment by ninjanomnom** [comment]
Forgot to close this, it got fixed in #36261
