### ISSUE TITLE
Clock cult vitality matrix does not replace catatonics. Blood cult's revive rune doesn't either.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#33540]
Both of these were intended features, I think. Blood cult will play the message, but no prompts appears to ghosts. Clock cult's will make the rune turn blue, but again no prompt. Tested this with ForcefulCJS in the thunderdome, the only var edit I did was setting clock cult's vitality high enough to use the sigil.
@Robustin

**Comment by Robustin** [comment]
Been working on it, I think its a problem with the ghost prompt but I haven't verified it.
