### ISSUE TITLE
Unable to type an asterisk into chat

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#33546]
Repo;
Toggle hotkeys off
Type `say "`
Try to press `*` on the keypad.
Nothing happens.

**Comment by ShizCalev** [comment]
@ninjanomnom

**Comment by praisenarsie** [comment]
i swear this is happening to me on goonstation too

@ShizCalev can you try doing shift + F8 for *?

**Comment by epochayur** [comment]
is it just keypad? what about the * on the 8-key?

**Comment by ninjanomnom** [comment]
I have some suspicions about why this is happening and the fix isn't pretty. I'll get to it tomorrow.

**Comment by ShizCalev** [comment]
Just keypad.

**Comment by praisenarsie** [comment]
i got a feeling 512 has some correlation here. does this only occur on 512 servers?

**Comment by SuperNovaa41** [comment]
Yeah i dont think this is really worth keeping around, why would you want to say `*`?
