### ISSUE TITLE
problems with integrated injector

### ISSUE THREAD

**Issue by arsserpentarium** [tgstation/tgstation#33544]
Integrated hypoinjector on reverse mode don't want to drain reagents if it's empty. But can drain, if there is at least one unit.

**Comment by arsserpentarium** [comment]
I've investigated it. 
L.transfer_blood_to(src, tramount)
AM.reagents.trans_to(src, tramount)
This procs gives 1, but in real don't do anything. Can't figure out, why.

**Comment by kriskog** [comment]
Circuits are gone
