### ISSUE TITLE
potato can't be juiced

### ISSUE THREAD

**Issue by arsserpentarium** [tgstation/tgstation#33557]
But it should!

**Comment by FantasticFwoosh** [comment]
Flawed coding, the recipie  to make vodka (like most other juicable reagents) cites [potatoes](https://github.com/tgstation/tgstation/blob/743729baf94a4502bed948bc61ff415133d2ab9b/code/modules/food_and_drinks/recipes/drinks_recipes.dm#L65) & enzyme hence if you can't extract it, its a no-go zone.
