### ISSUE TITLE
Spam clicking adding accesses to a mech's internal permissions can cause duplicates.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#33552]
![](https://i.imgur.com/ZXC4u3Z.png)

There's a ton more issues here, actually, like not properly updating the panel once you click "finish" and it still tells you it's in effect (when you have to use your card on it again to reset it) among many others.

The whole damn thing needs to be changed or thrown out tbh.

**Comment by magatsuchi** [comment]
mech access thingy has been refactored
