### ISSUE TITLE
Brain insertion gives me an invisible, duplicate, dummy brain

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#33564]
I was fixing up ling victims yesterday and I noticed when I would put a (player) brain into a brainless corpse, the brain would go in fine but I would be left with an invisible brain in my hand.

Dropping/Throwing the brain would make it "appear".

**Comment by vuonojenmustaturska** [comment]
This bug is *probably* fixed. Congratulations, you found the elusive bare brainmob.

**Comment by Robustin** [comment]
This happened ~4 days ago, what fix was implemented since then?

**Comment by YPOQ** [comment]
It doesn't seem to be a brainmob issue, but rather the brain doesn't get removed from the players hand slot if they use the non-surgical brain insertion (why does this exist?).
