### ISSUE TITLE
Rainbow jumpsuits dont have rolldown sprites

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#33571]
as a result they get the ugly default SUIT sprite when rolled down

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/b0f24a892b795a008325a80e8d5c9ed4dd9dc1bd/code/modules/clothing/under/color.dm#L126-L132

You shouldn't be able to adjust it.....

**Comment by Dorsisdwarf** [comment]
some assistant was running around toggling it rapidly a few rounds ago on basil

**Comment by YPOQ** [comment]
Chameleon jumpsuits can be toggled even when disguised as rainbow jumpsuits.

**Comment by Iatots** [comment]
The syndacate stylish turtleneck can be toggled into the error too. The one with the sharp collar.
