### ISSUE TITLE
strange objects and display cases don't like each other much

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#33575]
![2017-12-15_23-15-05](https://user-images.githubusercontent.com/31222036/34064029-0b4d663c-e1ee-11e7-9d39-9b17ff3fa259.png)
![2017-12-15_23-15-20](https://user-images.githubusercontent.com/31222036/34064031-0c6a4daa-e1ee-11e7-8dca-2f890a45ef40.png)

roundid 80249

note this was already in the display case

**Comment by coiax** [comment]
It's probably how display cases "fake" the objects in them in subsequent rounds

**Comment by MrMaclang** [comment]
would be nice if it cant find the texture, i'l just find a random texture from that thing

**Comment by nemvar** [comment]
Could not reproduce.
