### ISSUE TITLE
[DISCUSSION] I got high and profiled compilation [not a real issue] [this is the only place you guys actually read] [brackets as hashtags]

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#33588]
Using
![](https://i.imgur.com/ofRPhxc.png)

and https://github.com/paypal/gnomon

I was able to profile compilation times by inserting two compile errors in every proc, one triggered on the compiler's first pass, and one triggered on the compilers second pass.

https://tgstation13.org/parsed-logs/compile%20time%20tracking%20sorted.txt 

https://tgstation13.org/parsed-logs/compile%20time%20tracking%20unsorted.txt 

Be sure to check out entries from the sorted version in the unsorted version to see what it does after, as I couldn't find an easy way to add a line at the end of every proc, so some thing happening between files or things line objects being defined might show up as part of a proc's time.

The time listed before a line is how long between that line being outputted, and when the next line was outputted.

This modifies the line counts, so use this repo for matching: https://github.com/MrStonedOne/tgstation/tree/bf64a9c202a2ec820dbf40b923158160c967869d

**Comment by SpaceManiac** [comment]
Top N modules according to this measurement:

```
22.15  loading tgstation.dme
12.64  code/game/objects
10.26  code/modules/mob
7.027  code/game/machinery
5.169  code/game/gamemodes
2.323  code/modules/power
2.107  code/modules/admin
2.014  code/modules/reagents
1.891  code/modules/clothing
1.822  code/game/mecha
1.656  code/modules/atmospherics
1.557  code/modules/projectiles
1.522  code/modules/food_and_drinks
1.459  code/modules/mining
1.295  code/modules/research
1.27   code/modules/hydroponics
1.049  code/modules/integrated_electronics
1.039  code/controllers/subsystem
1.022  code/modules/surgery
0.9652 code/modules/shuttle
0.8871 code/modules/spells
0.8554 code/modules/modular_computers
0.7924 code/game/turfs
0.764  code/_onclick/hud
0.6662 code/modules/paperwork
```

**Comment by Cyberboss** [comment]
I'm honestly suprised gamemodes is that high

**Comment by Cyberboss** [comment]
power probably needs a rewrite

**Comment by Supermichael777** [comment]
gamemodes is also almost totally self contained, a lot of things are probably stuffed in there that should be parted out.

**Comment by MrStonedOne** [comment]
So likely what we'll have to do is identify trends in the compile time. why is it that some procs compile instantly, while others of similar length take longer. from that we should be able to figure out something(s) that disproportionately increase compile time and avoid them and/or report them to lummox as a opportunity for optimization

**Comment by MrStonedOne** [comment]
Like take `code/modules/power`

It has half the amount of code as `code/modules/admin` but about the same cost.... I wonder if we could figure out why.
