### ISSUE TITLE
Can't see ores while mining correctly while mining (BUG)

### ISSUE THREAD

**Issue by Pathofchaos1** [tgstation/tgstation#33589]
THE ROUND ID: 80278 

I was unable to see ores in the wall with an advanced mining scanner, and meson scanner combo. I had to be in a certain position. Restarting Byond did not help, Swapping meson scanners, turning the mining scanner off/on, and even getting Gods eye didn't help. (no screenshot for gods eye as I was busy rushing to the Shuttle) It happened again anyway on a new round.
 
![dreamseeker_2017-12-16_03-13-35](https://user-images.githubusercontent.com/6301019/34070004-6b76f54e-e222-11e7-8d55-2642a95ff653.png)
![dreamseeker_2017-12-16_03-16-33](https://user-images.githubusercontent.com/6301019/34070005-6b85d5be-e222-11e7-87fe-8621fa0beb28.png)
![dreamseeker_2017-12-16_03-20-58](https://user-images.githubusercontent.com/6301019/34070006-6b950ebc-e222-11e7-99fb-b868387a5925.png)
![dreamseeker_2017-12-16_03-12-28](https://user-images.githubusercontent.com/6301019/34070007-6ba3ef4a-e222-11e7-83cd-025692996223.png)

**Comment by vuonojenmustaturska** [comment]
Afaik this is because of the 512 client optimizations in latest byond builds

**Comment by kriskog** [comment]
This should be fine now.
