### ISSUE TITLE
Lava can be spawned around the mining base, blocking the miners in.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#33585]
![](https://i.imgur.com/ZcbpI1D.jpg)

Nice.

**Comment by jughu** [comment]
Just getca rcd

**Comment by ShizCalev** [comment]
Doesn't seem like a bug to me.

**Comment by Repukan** [comment]
Just break the coin maker window and go out that way. Guaranteed not to be blocked by lava

**Comment by Dennok** [comment]
Now it generates propertly or this is very rare situation.

**Comment by kriskog** [comment]
Yeah, this cant happen anymore.
