### ISSUE TITLE
Donuts are gross

### ISSUE THREAD

**Issue by calibraptor** [tgstation/tgstation#33587]
Issue reported from Round ID: 80269 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% LAG FREE])

Donuts inflict the grossness status effect upon devouring them. Who the fuck is responsible for this.

**Comment by GunHog** [comment]
Were you playing as a human?

**Comment by calibraptor** [comment]
Was playing as a ligger

**Comment by SgtxRootbeer** [comment]
Lizards find bread/plant products disgusting. It's a feature, albeit a poor one.

**Comment by ShizCalev** [comment]
Not a bug.
