### ISSUE TITLE
Photocopiers can't make photos of your ass

### ISSUE THREAD

**Issue by Mark9013100** [tgstation/tgstation#33596]
[Directions]: # (If you discovered this issue from playing tgstation hosted servers

INCLUDE THE ROUND ID 

from the Status panel or retrieve it from https://atlantaned.space/statbus/round.php ! If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

Server revision compiled on: 2017-12-15

The following pull requests are currently test merged:
#33460: 'Re-Support old hotkey mode behaviour' by ninjanomnom at commit 088e35

Based off origin/master commit: c8d7d4

Server tools version: /tg/station 13 Server v3.2.1.9

Server tools API version: 3.2.0.1

Title, it'll show the message but there'll be no photo.

**Comment by DaxDupont** [comment]
I did this yesterday, still worked fine.
