### ISSUE TITLE
Deep-fryers are too loud.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#33592]
literally the loudest looping sound rn

**Comment by Xhuis** [comment]
Boy you ever *use* a deep fryer? Them things greasy as hell.

**Comment by praisenarsie** [comment]
yeah but i don't my ears raped each time i walk past the kitchen

**Comment by Potato-Masher** [comment]
Shhh, it's all good. They make great cover noise when murdering someone near the kitchen with an esword!
