### ISSUE TITLE
SYNDI NAVIGATION COMPUTERS DONT FUCKING WORK

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#33600]
RoundID: 80286

Syndi nav computers cause you to be stuck in transit hell that doesnt even show you're in transit 

Steps to reproduce:
1. Be nukie
2. Use syndi ship nav computer
3. Go to custom location
4. Watch as ship takes off
5. Never lands.
6. No transit tiles are seen
7. Jump off because you think you arrived
8. Rage

**Comment by praisenarsie** [comment]
@ninjanomnom

**Comment by ninjanomnom** [comment]
![image](https://user-images.githubusercontent.com/1234602/34075296-14851928-e290-11e7-91d0-6fd8958474d5.png)

Seems to work fine

**Comment by ninjanomnom** [comment]
If something like this happens again it's probably some rare bug and I need more details about exact coordinates for source and target preferably with pictures.

As it stands this issue is worthless and no one seems to have reproduced it.
