### ISSUE TITLE
Androids do not have their race specific bonuses

### ISSUE THREAD

**Issue by KomradeSpectre** [tgstation/tgstation#33603]
Round ID #80288 on Bagil

Androids do not exhibit their race specific bonuses aside from being able to weld/coil damage.
I had suffocated, froze, and experienced depressurization despite being fully augmented as stated here: https://tgstation13.org/wiki/Guide_to_races#Androids. Androids also cannot use limbs without surgery as stated, they bleed, and need to eat.

Likely guess is that this code wasn't maintained after some damage/mob overhaul.

**Comment by XDTM** [comment]
My bad, i worded it badly in the wiki. Full augs do not give the android species, but the opposite is true. They _should_ make you space immune, though, not sure what was up with that.

**Comment by KomradeSpectre** [comment]
It's happened every round as a fully augmented human. I was able to be injected, could bleed, etc. I'd assume at the very least the augmentation removes the bleeding and being able to be injected not to mention the space immunity, but it doesn't currently.

**Comment by XDTM** [comment]
It's not an implemented feature codewise. It could be added eventually, but it's more of a lack of a feature than an issue.

**Comment by vuonojenmustaturska** [comment]
did someone write a feature fanfic in the wiki?

**Comment by XDTM** [comment]
Androids, as the species, do have those bonuses. They also happen to look exactly like a fully augmented human, and share some traits with them, hence the confusion.

**Comment by Armhulen** [comment]
why don't we just make full augments turn into androids

**Comment by XDTM** [comment]
Then we'd have to explain why an android with a human limb is different from a human with all but one limbs augmented

**Comment by KomradeSpectre** [comment]
Ezpz, if the torso and head are changed, android, if the arms and legs are only changed, augmented human, if the whole body is changed, full android.

**Comment by FantasticFwoosh** [comment]
Androids are a species, you can turn into one by mixing unstable mutation toxin & teslium together but are not at base augumented, just protected by additional code similar to what is given to golems.

![](https://tgstation13.org/wiki//images/3/3e/Androids.png)


[Android on the wiki](https://tgstation13.org/wiki/Android#Androids)

> Can attach limbs from the ground without surgery.  

This is a zombie code trait that essentially proves that they are un-augumented at base because augumented person's can't regularly re-attach limbs.

> Humanlike robots, distant cousins of synths. _**A similar result** can be achieved by fully augmenting a human._

Whoever wrote this, have a word because its not helpful to read even when you know the difference between the two

**Comment by XDTM** [comment]
>My bad, i worded it badly in the wiki.

**Comment by FantasticFwoosh** [comment]
badly is a understatement

**Comment by XDTM** [comment]
I already fixed it, but you can edit it yourself if it irks you so much
