### ISSUE TITLE
Drinking glass not updating when used in crafting

### ISSUE THREAD

**Issue by TribeOfBeavers** [tgstation/tgstation#33619]
Issue reported from Round ID: 80318 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% LAG FREE])

If a drinking glass is used to hold a liquid used in crafting, the glass type doesn't update after the liquid is consumed by a recipe. 

Basically you end up with an empty glass that has the icon and name as if it still had the liquid in it.

I tested this by using a glass of milk to make muffins, and a glass of egg yolk ( a glass of ...what?) for Khachapuri. I ended up with an empty glass of milk, and an empty glass of ...what? respectively.

Adding a new liquid fixes the icon and name.

**Comment by praisenarsie** [comment]
i swear this was fixed months ago
