### ISSUE TITLE
Anomalies can spawn in uncomfortable locations

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#33611]
Seems to be a recent thing, so far I've seen Arrivals Shuttle get anomaly twice and once for Abandoned Ship. While there can be hilarious results, I'd assume at least Arrivals Shuttle is secure from anomalies seeing as nobody can get to them unless someone is arriving or if the shuttle is already docked for repairs. I guess it's not strictly a bug but seeing as even antags are told to leave Arrivals Shuttle alone, it'd make sense that the Arrivals Shuttle wouldn't get mini singuloths or other amusing anomalies that can make mincemeat of people trying to join.

**Comment by ShizCalev** [comment]
Shuttles should be blacklisted, hmm..

https://github.com/tgstation/tgstation/blob/b7a9a2a452466d411115bb9b8d925fd0a02132a3/code/controllers/subsystem/events.dm#L96-L104

**Comment by MrMaclang** [comment]
is it also a feature that it can spawn IN the supermatter engine room?

**Comment by Ordonis** [comment]
One solution might be to blacklist areas immediately surrounding the most critical no-anomaly spots. Not the most elegant, but possibly necessary to prevent noclipping into those areas. Also, if anomalies are spawning inside walls, that might be another way they're getting from designated areas to nondesignated.

**Comment by 81Denton** [comment]
![anomaly wall](https://user-images.githubusercontent.com/32391752/67147724-a1cc1200-f297-11e9-9e30-ab6cf6c2e9ea.png)

They routinely spawn inside walls, looks like an easy fix if you make their spawn proc check for density.

**Comment by Sealed101** [comment]
appears to have been resolved in #69512

https://github.com/tgstation/tgstation/blob/bbbc36a738d7b9094519063585751cd593fa313d/code/modules/events/anomaly/anomaly_placer.dm#L21-L55

which calls for `is_blocked_turf()` that checks for the target turf's density

https://github.com/tgstation/tgstation/blob/bbbc36a738d7b9094519063585751cd593fa313d/code/game/turfs/turf.dm#L239-L253
