### ISSUE TITLE
Split personality lings can't use ling hivemind or ling abilities.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#33623]
Round ID: #80327

I'm not sure how this person got split personality at round start, but I inadvertently fucked over this guy's round due to this bug.

![dreamseeker_2017-12-17_06-29-18](https://user-images.githubusercontent.com/33107541/34079163-e4938bda-e2f5-11e7-8087-eec8b549d557.png)

It appears that I have the objectives and some UI elements for ling (selected sting is usable), and I can evolve new powers, but otherwise I can't do ling things. No hivemind, no nothing. Kinda screwed up my partner quite a bit, because many times something required a ling action, and it would swap to me.

**Comment by Potato-Masher** [comment]
BUT, we still won somehow. Fucking heck.

**Comment by XDTM** [comment]
Changeling is a mind datum, for some reason, so the second mind has no powers of its own. It should be reworked into a transferrable body datum to avoid cases like these.

**Comment by RemieRichards** [comment]
maybe lings just shouldn't get brain traumas.
or maybe the "split" personality for a ling is just the original personality/one of the absorbed ones gaining temporary control (due to the brain damage)

**Comment by GunHog** [comment]
Building on RR's idea, what if we extended this fix for lings into a feature? Give the ling the ability to put an absorbed personality in control for a while! The ling, having absorbed the memories of its prey, can perfectly mimic that prey's actions. We could use temporary control transfers to replicate this!

**Comment by XDTM** [comment]
They should also be able to speak with the ling even when not in control to suggest what they'd do in a normal situation, or just give advice.

**Comment by QualityVan** [comment]
Lings don't use their brains, it's weird that traumas would do anything to them.

**Comment by Mooshimi** [comment]
#41601 this is the main issue report for this afaik
