### ISSUE TITLE
if you try to become a marauder and the shell got taken it sends you to nullspace

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#33630]
at least i think that's null space

**Comment by Xhuis** [comment]
Round ID? Circumstances? Come on now!

**Comment by YPOQ** [comment]
https://github.com/tgstation/tgstation/blob/3d813853b5a98d26efde877b80382fe7d49bdbba/code/game/gamemodes/clock_cult/clock_items/construct_chassis.dm#L43
Probably needs a QDELETED check before this since the alert can outlive the shell itself.

**Comment by YPOQ** [comment]
Fixed by #34040
