### ISSUE TITLE
Mannually reviving people (not through cloning) by replacing all organs does not work

### ISSUE THREAD

**Issue by CitrusGender** [tgstation/tgstation#33649]
The following pull requests are currently test merged:
#33601: 'Fixes cross comms' by Cyberboss at commit 3bf1c2
Round ID: 80375

I recently had a patient attacked by a ling that lost all of their organs. So, I'm probably the only person who does this, but it appears that when you attempt to revive someone who has been killed by a ling with (as follows)

Synthflesh the body to under 100 damage in Brute and Burn
Strange Reagents the body
Do surgery on their body, replace all four organs in their chest (heart, lungs, stomach, liver)
Ussually they die during this process, and I attempt to revive them again.

For some reason, they appear to take respiration damage and brute damage to quickly dieafterward, even after I attempt to stabilize them and replace all of their organs. Is this a glitch or am I just missing something?

**Comment by CitrusGender** [comment]
I have provided a 4 minute video showing me doing the exact same thing. I cut it short but they died shortly after, you can see them taking respiratory damage even though all I delete was their four chest organs. They also were taking brute damage.

**Comment by XDTM** [comment]
Heart attack still on maybe?

**Comment by coiax** [comment]
Heart attack is dynamically calculated by the presence or absence of a heart.

Wait, did you start the heart beating again before you inserted it via surgery?

**Comment by SgtxRootbeer** [comment]
If you don't start the heart, a defib is needed.

**Comment by CitrusGender** [comment]
Yeah, nevermind. I thought the heart kept beating for a longer time than a few second. It was because the heart wasn't started.
