### ISSUE TITLE
T-rays sometimes see the wrong directions on disposal pipes

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#33642]
Round id: 80364
Map was Box, don't know if it's a map or code issue.

![image](https://user-images.githubusercontent.com/222630/34090034-1167c50e-e369-11e7-8516-f3fddf5ba718.png)
![image](https://user-images.githubusercontent.com/222630/34090035-12acb546-e369-11e7-82be-232cbafae781.png)
![image](https://user-images.githubusercontent.com/222630/34090037-14175ce2-e369-11e7-8e36-792d5be43f5a.png)

**Comment by praisenarsie** [comment]
@ACCount12

**Comment by ACCount12** [comment]
Oh, this one. I encountered it back when I was doing the disposal refactor. A worst type of bug possible: I can reproduce it pretty reliably, but still have no idea at all on how and why it happens. 

Seems like a BYOND bug to me, but the way it manifests is really weird.
