### ISSUE TITLE
Holding another key disables movement keys temporarily

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#33648]
Round ID: 80364, and private servers

While holding any of WASD or the arrow keys, pressing another key like E or R or V will interrupt movement until either that key is released or the movement key is released and pressed again. Releasing and pressing the key again, the small number of keys involved, and a variety of players reporting the same issue make it seem like this isn't a client-side issue.

The movement keys still appear in `keys_held` when they're not doing anything.

@ninjanomnom

**Comment by Anonmare** [comment]
I had a similar issue and only disabling and re-enabling hotkey mode fixed it

**Comment by ninjanomnom** [comment]
I found the problem and it's a byond bug though there's an easy workaround

```
var/foo = 4
foo |= null

var/bar = 4 | null
```
foo will be 0 (not null)
bar will be 4
