### ISSUE TITLE
Runtime when AI uses Voice of God spell

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#33650]
> [11:52:56] Runtime in ,: bad arg name 'spans'
>   proc name: say (/mob/living/silicon/ai/say)
>   usr: Emerald (coiax) (/mob/living/silicon/ai)
>   usr.loc: The floor (171,134,2) (/turf/open/floor/plasteel/neutral/corner)
>   src: Emerald (/mob/living/silicon/ai)
>   src.loc: the floor (171,134,2) (/turf/open/floor/plasteel/neutral/corner)
>   call stack:
>   Emerald (/mob/living/silicon/ai): say("HI THERE", null, null)
>   voice of god("HI THERE", Emerald (/mob/living/silicon/ai), /list (/list), 1, 0, 1)
>   Voice of God (/obj/effect/proc_holder/spell/voice_of_god): cast(null, Emerald (/mob/living/silicon/ai))
>   Voice of God (/obj/effect/proc_holder/spell/voice_of_god): perform(null, 1, Emerald (/mob/living/silicon/ai))
>   Voice of God (/obj/effect/proc_holder/spell/voice_of_god): perform(null, 1, Emerald (/mob/living/silicon/ai))
>   Voice of God (/obj/effect/proc_holder/spell/voice_of_god): choose targets(Emerald (/mob/living/silicon/ai))
>   Voice of God (/obj/effect/proc_holder/spell/voice_of_god): Click()
>   Voice of God (/datum/action/spell_action): Trigger()
>   Voice of God (/obj/screen/movable/action_button): Click(null, "mapwindow.map", "icon-x=16;icon-y=6;left=1;scre...")

1) Be an AI.
2) Grant Voice of God spell.
3) Try using it, it runtimes.

@XDTM

**Comment by XDTM** [comment]
Does the ai say proc have no spans argument?

**Comment by coiax** [comment]
I don't know. Also, go on IRC, I have some ideas I want to run by you.

**Comment by SpaceManiac** [comment]
`/mob/living/silicon/ai/say(message, language)`
