### ISSUE TITLE
Shuttle movement interrupts machines

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#33654]
When a shuttle starts moving or lands somewhere and you've clicked lathe or other machine to produce something, the shuttle movement will interrupt the process. I don't know if you actually lose the resources and not gain the parts but more annoyingly you can lose diamond or other valuables when you click Release on ORM while the shuttle moves and now they're gone. It's a bit of an edge case but annoying nonetheless.

**Comment by ninjanomnom** [comment]
Is this while the ORM is *on* the shuttle or does a shuttle moving anywhere somehow reset machines and people using them elsewhere?

**Comment by Marflowerose** [comment]
This is for machines on the shuttle
