### ISSUE TITLE
Casing ejection sound plays in space

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#33668]
@ShizCalev 

Not sure if a gravity check or space check is more appropriate (or maybe only playing on regular floors and plating so it doesnt make the sound on carpet/water/dirt etc)

**Comment by ShizCalev** [comment]
oh shoot.

**Comment by duncathan** [comment]
get it? shoot? like a gun?

**Comment by RemieRichards** [comment]
the sound should be getting muffled by the environment checking code, which should be fine.
