### ISSUE TITLE
Everyone is stupid

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#33675]
Round ID 80437
Everyone has brain damage and is headbutting doors and has a stupid expression on their face.
We know the game should be realistic but this is kinda overkilll.

**Comment by MrStonedOne** [comment]
`@ms_github ahelp 33675 I bet it was kevinz abusing sdql2`
`@ms_github ahelp 33675 ticket IC`

**Comment by Spaceinaba** [comment]
feature

**Comment by Ratvar** [comment]
not a bug, close and embrace

**Comment by XDTM** [comment]
My bad, fix is up but bundled in a feature pr until i can get home and atlmize
