### ISSUE TITLE
Intercom on top of service protolathe on MetaStation

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#33671]
Probably should be changed to be actually wall-mounted.

![image](https://user-images.githubusercontent.com/222630/34141914-307fc4b6-e439-11e7-9495-8555efcfccad.png)

**Comment by BeeSting12** [comment]
150 hours of testing.

**Comment by vuonojenmustaturska** [comment]
@BeeSting12 can you also fix the ORM being inside cargo, inside a door in... whatever the station is where cargo is to the left of the hopline
