### ISSUE TITLE
Mass Drivers are broken

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/tgstation#33674]
Issue reported from Round ID: 80434 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% LAG FREE])

[Directions]: 
1. Try to use the chapel mass driver on Metastation
2. It doesn't work
3. Try to make a mass driver and button linked using text or numbers in the id variable for both
4. Driver doesn't trigger

**Comment by Stickymayhem** [comment]
OK IT SEEMS TO HAVE BEEN JUST THAT ROUND THAT THEY ALL STOPPED WORKING

**Comment by ShizCalev** [comment]
Will close in a week without a repo then lol.

**Comment by Buggy123** [comment]
Different issue: last time I used a mass driver (~ a week ago), the second countdown was off by a decimal point. A delay of "3 seconds" was actually 30 seconds, and the increments on the buttons seemed like they were off by a decimal too (smallest was 0.1 seconds)

This was with the white ship driver.

**Comment by Qustinnus** [comment]
@ShizCalev
