### ISSUE TITLE
text squashing/enlarging doesn't work for radio chat

### ISSUE THREAD

**Issue by awesine** [tgstation/tgstation#33670]
[Directions]: # (If you discovered this issue from playing tgstation hosted servers) spam "; traps are gay" or something a few times

INCLUDE THE ROUND ID:

from the Status panel or retrieve it from https://atlantaned.space/statbus/round.php ! If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.) 80423

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

what happened:
spammed "traps are gay" over radio
it did not enlarge over the radio
please fix so we are TRULY goonstation

**Comment by awesine** [comment]
reproducing: https://www.dropbox.com/s/8xlujdo00z3zqn7/2017-12-19_15-16-09.mp4?dl=0

**Comment by optimumtact** [comment]
09:38 <%Antur> that's just dumb user
09:38 <%Antur> if you talk on radio you hear your own whisper

**Comment by awesine** [comment]
@optimumtact 
yeah but it doesn't actually enlarge it on the radio did you-
oh
