### ISSUE TITLE
moving diagonally in vents forces you to exit the vent

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#33693]
[Directions]: # (If you discovered this issue from playing tgstation hosted servers

INCLUDE THE ROUND ID 

from the Status panel or retrieve it from https://atlantaned.space/statbus/round.php ! If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by ShizCalev** [comment]
@ninjanomnom

**Comment by ninjanomnom** [comment]
duplicate of #33528
