### ISSUE TITLE
The game stops responding every few minutes and requires a restart. Only when playing as AI

### ISSUE THREAD

**Issue by scrubs2009** [tgstation/tgstation#33694]
The most recent event was earlier today. I don't have the round ID but it was on bagil at around 3:00. It's happened many times though.
When playing as AI every few minutes the game will freeze and stop responding. The entire application. Not just lag. Restarting the game fixes it but it happens again later. It can happen seconds or 10 minutes after restarting.

This only happens when playing AI. Ghosting will immediately stop the issue.

**Comment by ninjanomnom** [comment]
Undoubtedly the same base cause as #33000 and a few other camera crashes.

**Comment by ShizCalev** [comment]
#33377
