### ISSUE TITLE
Light Eater from Nightmare Heart has no examine text on-person.

### ISSUE THREAD

**Issue by YogsMcree** [tgstation/tgstation#33701]
Round ID doesnt really matter.
Light Eater, from consuming a nightmare heart, has no examine text. This could lead to validhunters just killing innocents who managed to gib a nightmare. Similar to dark blessing, this should appear on the players examine to prevent validhunters from just murderizing non-lings

**Comment by jughu** [comment]
All no drop items has this and i been told this was an feature???

**Comment by YogsMcree** [comment]
I was under the impression that Dark Blessing, and chainsaw arms, and God Hand, all had examine texts.

**Comment by AnturK** [comment]
Abstract items do not show in examines, why the arm replacements are abstract is another issue.

**Comment by KorPhaeron** [comment]
Not a bug, this is how "limb" items work
