### ISSUE TITLE
Server Crash via Too many minerals in mining satchel of holding

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#33712]
Issue reported from Round ID: 80519 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% LAG FREE])

Server started lagging VERY hard when I was mining with bombs and picking up ore. Lag started as soon as I was picking up ores, and stopped when I stopped picking them up. Sever eventually crashed right as I picked up some ore after not picking up anyone for about 10 seconds.

Probably reproducible pretty easily with either another mining satchel of holding or an ore box.

Also not the first time this has happened to me while mining.

**Comment by Hathkar** [comment]
Well, maybe 1000 or 2000 iron, 500 or so plasma, 20 diamond, 10 bluespace, 150 titanium, 300 uranium, 600 gold, 500 silver? That's the best I can remember when I checked inside my mining satchel.

**Comment by davethwave** [comment]
well no wonder...

**Comment by davethwave** [comment]
perhaps it might be time to put a cap on the mining satchel of mining. like 500 ore or something.
