### ISSUE TITLE
If you use up all your metal sheets in the metal dispenser while it's active as a cyborg, it will delete itself

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#33725]
[Directions]: Be engieborg, equipe metal sheet dispenser, dispense metal until it's used up, have no more metal because it deletes itself

ROUND ID: 80542

**Comment by Anonmare** [comment]
It only does this with the metal sheet dispenser as far as I can tell

**Comment by DaxDupont** [comment]
Does it regen when on the charger?

**Comment by Anonmare** [comment]
No, the dispenser itself deletes and you can't equip it anymore

**Comment by DaxDupont** [comment]
i fix
