### ISSUE TITLE
Overlapping sprite issue.

### ISSUE THREAD

**Issue by Smudged** [tgstation/tgstation#33720]
![tg sprite overlap problem](https://user-images.githubusercontent.com/12579846/34241101-55e78462-e5d0-11e7-8012-43185ffd100b.png)

Much like on every other TG coded server, the sprites overlap oddly on non-human races.
Problems: Not matching up with side sprites, also deletes parts of the sprite while on face.

Left picture is a face-masked raised over my mouth, which is oddly going into it, not matching with side sprite.
Right Picture is face mask down on my neck, and sec-hud over my eyes, with the center portion missing.

*Edit: Sprites overlap on top properly on Yog coded. 
**No picture at the time, but can do a quick screen cap on request

**Comment by MrStonedOne** [comment]
Please use the byond screenshot tool (file -> take a screenshot) then crop it/expand it, as it will never have scaling artifacts like the screenshot you uploaded does. (and when you blow it up, always do so in powers of 2 (2x, 2x, 4x, 8x, etc) so that you don't add any new scaling artifacts)

**Comment by AnturK** [comment]
I have no idea what i'm supposed to be looking at here. Breathing mask sprite ?

**Comment by Smudged** [comment]
On the side note, the left image is specifically in regards to the mask you find round-start in your box, and in emergency oxygen lockers, on humans that part would go over their mouth.
I'll rework my images and send more comparisons, so it's more clear, once I have the time.

**Comment by Smudged** [comment]
First up, Sec Hud.
TG Sec HUD Comparison: Front View + Side view
![front sec hud comp](https://user-images.githubusercontent.com/12579846/34273083-251a759e-e650-11e7-9ebb-5ad7af6ca78b.png)
![side sec hud comp](https://user-images.githubusercontent.com/12579846/34273103-35ab9a50-e650-11e7-8f51-c5e1ceec2f26.png)
Issues: Front view is missing pixels, side view is relatively similar

Yog Comparison: Front View + Side View
![yog sec hud side front comp](https://user-images.githubusercontent.com/12579846/34273133-52c1a8b4-e650-11e7-9dfa-c844fda740dc.png)
![yog side sec hud comp](https://user-images.githubusercontent.com/12579846/34273139-5d187810-e650-11e7-9621-893aec629416.png)
Because the sprite overlaps ontop on Yogs code, no pixels are lost and it looks similar to both.

Second Breath Mask
TG Breath Mask Comparison: Front view + Side view
![breath mask front comp](https://user-images.githubusercontent.com/12579846/34273365-3bc4b786-e651-11e7-93d9-463d529694de.png)
![side breath mask comp](https://user-images.githubusercontent.com/12579846/34273367-41668656-e651-11e7-8afc-350eab76dd66.png)
Problems: The biggest part of the breath mask disappears on the lizard, seeming to go into the mouth, which I doubt was the intention, side view is again the same.
Yogs Breath Mask Comparison: Front view + Side view
![yog front breath mask comp](https://user-images.githubusercontent.com/12579846/34273441-9438e810-e651-11e7-9216-226790eaef8a.png)
![yog side breath masp comp](https://user-images.githubusercontent.com/12579846/34273452-9bee1fb2-e651-11e7-94b9-9cfb80465b0b.png)

**Comment by Smudged** [comment]
32x32 sprite sizes again.
TG Helmet Comparison: Front + Side
![tg helmet front comp](https://user-images.githubusercontent.com/12579846/34316702-57868572-e759-11e7-926e-ed715c713c39.png)
![tg side helmet comp](https://user-images.githubusercontent.com/12579846/34316704-5b93a8de-e759-11e7-9c5d-abb7a4cece43.png)
Frills stick out the side of the helmet on front, but disappear on the side sprite.

Yogs Helmet Comparison: Front + Side
![yogs front helmet comp](https://user-images.githubusercontent.com/12579846/34316721-ba106a14-e759-11e7-8f57-3567b10a3a4b.png)
![yogs helmet side view](https://user-images.githubusercontent.com/12579846/34316724-c064c32e-e759-11e7-8072-f12b28d84154.png)
Frills don't stick out, and just like the opposing side sprite, it also matches.

Differences noted: Yogs on the sprite is slightly darker than TG, but that might be a consistency thing.

The overlap to yogs would be a quick and dirty fix, but it's unavoidable considering the majority of the items only have the one human variant to it, so sprite issues will almost always certainly exist.

**Comment by dragomagol** [comment]
![image](https://user-images.githubusercontent.com/66640614/209274664-46e91ae8-0db5-47b2-827b-8344241ff896.png)

Seems to have been fixed.
