### ISSUE TITLE
shitcode causing issues with refs and circuits

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#33729]
INCLUDE THE ROUND ID ab1297 
so the snowflake name of the absthine bottles causes sensors to be unable to obtain the ref of the bottles

**Comment by arsserpentarium** [comment]
can you explain more?

**Comment by arsserpentarium** [comment]
What you tried to scn and how? and what happened?

**Comment by Cyberboss** [comment]
that's not a round id

**Comment by Tlaltecuhtli** [comment]
i was scanning the absinthine bottle but it wouldnt give me a ref

**Comment by arsserpentarium** [comment]
Scanning with sensor or locator?

**Comment by Tlaltecuhtli** [comment]
sensor

**Comment by arsserpentarium** [comment]
![image](https://user-images.githubusercontent.com/32496644/34326124-b80184d4-e8b6-11e7-8312-df9606190f5c.png)

**Comment by arsserpentarium** [comment]
all is working

**Comment by Tlaltecuhtli** [comment]
did you try with the long names? maybe thats what it broke it

**Comment by arsserpentarium** [comment]
still can't.
