### ISSUE TITLE
Inconsistencies when chopping down christmas tree during event

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#33748]
![image](https://user-images.githubusercontent.com/609465/34282986-4dddf8b8-e6c1-11e7-89c3-a1b2300e11cf.png)
![image](https://user-images.githubusercontent.com/609465/34282990-518f239c-e6c1-11e7-8aa2-824144ab1184.png)

Round ID: 80578

Someone chopped down the tree before the presents event fired, and then the event fired, it's still a stump, but there are presents below it (which can be collected)?

**Comment by coiax** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
Cant stop christmas

**Comment by coiax** [comment]
I fixed this.
