### ISSUE TITLE
Revenants can't talk, and ghosts from dead revenants can't talk in deadchat.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#33744]
step 1: be griffghost
step 2: try to talk, nothing comes out
step 3: be bad griffghost, die
step 4: try to talk in deadchat, watch as you do a excellent mime ghost impression.

Round Id: irrelevant, It's happened repeatedly and consistently.

**Comment by vuonojenmustaturska** [comment]
Round id is not irrelevant, it's not used for "proof" that your bug report is valid, but it allows us to go check through the round logs to see if there's some sort of an obvious logged bug. Not including a round id is a very unappreciated waste of everyone's time.

**Comment by Buggy123** [comment]
Okay, I'll wait until I get revenant again and then put it here.

**Comment by imsxz** [comment]
This has happened to me too, was a few days ago and forgot to report it because it was a crazy round.

**Comment by Anonmare** [comment]
Also happened to me

**Comment by YPOQ** [comment]
There seems to be some issue with the \a macro in the revenant's name. Removing it fixed the issue. I'm not sure if this is a problem with the macro itself, a goonchat bug, or something else so hopefully someone else knows what is going on.
