### ISSUE TITLE
Metal Vanishing as Engiborg

### ISSUE THREAD

**Issue by Suicidalpickles** [tgstation/tgstation#33750]
Round ID: 80582
Basically, once your metal is depleted as an engiborg module, it vanishes entirely; Even after recharging and stocking on more again, you can't select it since the sprite is gone from your tools, so you can't do anything metal-related like finishing girders or whatever.

![capture](https://user-images.githubusercontent.com/32374784/34285642-eb751624-e68f-11e7-8eec-ccf59687e0a2.PNG)
![capture2](https://user-images.githubusercontent.com/32374784/34285646-efaab3c0-e68f-11e7-950c-0e2b2022aebf.PNG)

**Comment by Jordie0608** [comment]
Dupe #33725
