### ISSUE TITLE
Shielded hardsuits sometimes do not show their shields failing.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#33754]
This can make it impossible to tell when your shield is down. Not sure how to reproduce, but I see it happen quite often, so something in the chaos of the round seems to cause it. Maybe being hit while the shield is regenerating, or something.

**Comment by kevinz000** [comment]
can confirm

**Comment by Bod9001** [comment]
yeah, I experienced it as well, I think it doesn't seem to make sounds when depleted because I heard it charging but not depleting.
