### ISSUE TITLE
Sentient colossi do not speak with voice of god

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#33776]
[Round ID]: # 80632

THIS IS A TERRIBLE OVERSIGHT, @XDTM PLZ FIX IMMEDIATELY

**Comment by KorPhaeron** [comment]
Do I wanna know why there was as a sentient colossus

**Comment by coiax** [comment]
Actually it turns out it was a non-sentient corgi with a colossi skin

**Comment by KorPhaeron** [comment]
Feature request
