### ISSUE TITLE
Disco inferno shuttle reignites on launch

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#33779]
[Round ID]: 80639

The Disco inferno shuttle was ordered and lit on fire. However, the fire had burnt itself out before the shuttle launched.
Once the shuttle launched, the fire spontaneously reappeared and began burning again.

**Comment by Tlaltecuhtli** [comment]
feature

**Comment by DaxDupont** [comment]
This is indeed a feature
