### ISSUE TITLE
Combat Upgrade AI can Eject User out of Mech

### ISSUE THREAD

**Issue by Electronics** [tgstation/tgstation#33771]
What the title says, a combat upgraded AI (traitorous or not) can eject a user out of a mech effectively trapping the AI despite whether the mech has a beacon or not. Surely it should be able to take control over a period of time IF there isn't a user in it already?

**Comment by TheBonded** [comment]
This is a thing malf AIs (and thus combat upgraded AIs) can do. I'll mark this as cleanup flagged and it will automatically close unless anyone has anything else to add
