### ISSUE TITLE
remove the ability to insert stuff that shouldnt go in the autolathe or give a warning 

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#33794]
>accidentally hit the autolathe with a cool gun
>2000 worth of metal has been inserted

**Comment by Wad67** [comment]
cool guns _should_ be able to go into an autolathe and a warning would be annoying.

The user preferences panel does not have enough bloat yet, add a setting in there for it

**Comment by praisenarsie** [comment]
tbh we need to make it so disposals can recycle shit rather than grind everything into pure nothing

overhaul disposals when? 🤔

**Comment by RandomMarine** [comment]
The disposals crusher _already does that._
