### ISSUE TITLE
Cogscarabs are no longer able to perform Script and Application tier scripture in noncult rounds.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#33797]
Issue reported from Round ID: 80677 (/tg/Station Bagil)

It appears that Clockwork Scarabs are now unable to use anything above Driver tier scripture now during non-clockcult rounds. Cogscarabs are intended to have full access to all of the Scripture as I remember. I was able to perform scripture T2 and T3 about a week or so ago, so unless this was changed intentionally I don't know what could have broken it. The UI when trying to access these tiers looks like this:

![dreamseeker_2017-12-23_14-36-44](https://user-images.githubusercontent.com/33107541/34322199-551acf50-e7ef-11e7-87a5-49b774dde5df.png)

**Comment by praisenarsie** [comment]
@Xhuis

**Comment by Xhuis** [comment]
I have no idea what could have broken this, but I'll look at it.

**Comment by Potato-Masher** [comment]
Well, this seems to be fixed as of late. I'll close this now.
