### ISSUE TITLE
Supermatter Air Alarms usually don't work right.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#33808]
They measure the gasses of wherever the alarm is, which is usually outside the SM chamber. Consequentially, things like the supermatter monitoring program don't get the right gas readouts.

**Comment by Marflowerose** [comment]
I'm pretty sure supermatter monitoring is completely independent from any air alarms, it's always shown me correct gases within the chamber and the chamber itself has no air alarm to detect the gases.

**Comment by Buggy123** [comment]
I can check again, but last time I checked a SM monitoring program it told me the chamber had the standard 80/20 mix, which is really unlikely because oxygen is almost never used as a coolant, it almost always is filtered out, it didn't report _any_ plasma in the mix, and it _just so happened_ to be _exactly_ what you would expect if the air alarm was just reading the contents of the airlock.

**Comment by Buggy123** [comment]
![image](https://user-images.githubusercontent.com/16315400/34335819-c1f1177a-e91f-11e7-9d0d-178ed9387279.png)
Air alarm is reporting incorrect values at least.

**Comment by Marflowerose** [comment]
Tested and the supermatter monitoring is working normally and reports correct gases. Air alarm in your image is also showing correct gases.

**Comment by Buggy123** [comment]
Its... reporting... 80/20 nitrogen/oxygen at room temperature...

**Comment by Marflowerose** [comment]
![correct](https://user-images.githubusercontent.com/6935094/34339820-10a4a488-e982-11e7-9fec-690ad895cfbd.png)

I placed handy red rectangle and arrow to show where the air alarm is giving you that reading. Air in that section is most likely 80/20 at room temperature because it's supposed to. I have also tested just an hour ago on Terry that yes, Supermatter Monitoring console shows correct gases within the chamber, I added 2 cans of nitrogen and 1 can of n2o and filtered out everything else and it did show correctly that the chamber had only nitrogen and n2o

**Comment by DaedalusGame** [comment]
As fucked up as it is, tactical air alarms are usually placed to allow control of scrubbers and vents in the area. Both mixing chambers have air alarms placed like this.

**Comment by Buggy123** [comment]
I mean, I get that it's there to control the vents/scrubbers, but there are a lot of reasons that it should actually display the conditions _inside_ the chamber. For one, without it, ghosts can't tell what's going on with the SM.

**Comment by Marflowerose** [comment]
You can want it to display the conditions inside the chamber all you want but that's a feature request or some such, as it is there's no actual bug involved, everything's working as intended.

**Comment by duncathan** [comment]
the proper solution is to include an air alarm (likely with no checks) inside the SM chamber as well as outside.

**Comment by Buggy123** [comment]
I mean there technically isn't a _error_ or such, but it isn't working as you would expect. But if you look at the supermatter air control panel, the panel responsible for manipulating the atmospheric devices pertaining to the supermatter, you'd expect it to display the atmospheric conditions _of the supermatter chamber_. And "technically working as intended but makes no sense" is a valid issue topic which we see all the time.

**Comment by duncathan** [comment]
air alarms displaying conditions other than the tile they are on is unsupported and will remain so. I encourage you to look for a better solution

**Comment by Cyberboss** [comment]
I remember I wanted to add air sensors as floor machines but gave up because air alarm code

**Comment by ShizCalev** [comment]
Not a bug.
