### ISSUE TITLE
Chameleon thermals don't work

### ISSUE THREAD

**Issue by OmegaShoots** [tgstation/tgstation#33818]
Issue reported from Round ID: 80717 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Tried to put chameleon thermals on only to have them turn my entire screen black and not work at all (not even showing anyone in the darkness.)

**Comment by ShiggyDiggyDo** [comment]
Dupe #33409

**Comment by Cyberboss** [comment]
Duplicate of #33409
