### ISSUE TITLE
camera consoles crashes me constantly

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#33823]
STOP DOIN THAT YOU FUCK

**Comment by cyclowns** [comment]
im pretty sure all camera consoles do this
i crash a lot using the clockcult teleport console

**Comment by arsserpentarium** [comment]
Me too.
Looks like,problem is 512 version of byond

**Comment by praisenarsie** [comment]
> im pretty sure all camera consoles do this
i crash a lot using the clockcult teleport console

**Comment by WJohn** [comment]
Dupe of #33377 it's been around for months now. Seems to be a byond issue.
