### ISSUE TITLE
Mass purrbation only gives people cat ears and not a tail

### ISSUE THREAD

**Issue by Hatterhat** [tgstation/tgstation#33838]
[Round ID]:
80766, on Sybil

[Testmerges]:
#33831, #33834, #33705, #33828

[Reproduction]: 
1. Put the crew on mass purrbation
2. Watch the real weebs complain they don't have tails
3. Realize the inherent mistake in putting the crew on purrbation

[For Admins]: Only happens with purrbation, so something's probably broken there.

**Comment by The-clown-known-as-Pepe** [comment]
this also happens under normal purrbation

[Reproduction]:

1. Purrbation someone (he has no tail)
2. Take it away
3. Purrbation them again (now they have a full set)

**Comment by banthebantz** [comment]
feature
