### ISSUE TITLE
doing an action that shows up in chat more than twice in a row will show 'xNaN' instead of 'x3'

### ISSUE THREAD

**Issue by cyclowns** [tgstation/tgstation#33854]
![image](https://user-images.githubusercontent.com/19853115/34344285-8ffbe664-e9a1-11e7-833c-63d2a907a429.png)

![image](https://user-images.githubusercontent.com/19853115/34344283-897450ce-e9a1-11e7-9366-7bfff0b02034.png)

![image](https://user-images.githubusercontent.com/19853115/34344276-775779fc-e9a1-11e7-9aab-6a7e20967d83.png)

**Comment by cyclowns** [comment]
oh yeah
The following pull requests are currently test merged:
#33831: 'adds handholding' by kevinz000 at commit af87ed
#33834: 'Drones now spawn with seasonal hats depending on active holidays [VERY Important PR]' by Xhuis at commit ddfc97
#33705: 'Turns the baseturf var into a part time list' by ninjanomnom at commit 56ab86
#33828: 'Revert "Vending TGUI"' by Cyberboss at commit b70f58

**Comment by ShizCalev** [comment]
@AnturK

**Comment by Slignerd** [comment]
x3

**Comment by OmegaShoots** [comment]
> x3 turns into xNaN
> x3 is a cat face
> xNaN is dangerously close to xNyaN

is this some kind of furry conspiracy

**Comment by AnturK** [comment]
Can't reproduce. IE version ?

**Comment by optimumtact** [comment]
@cyclowns ^

**Comment by cyclowns** [comment]
11
