### ISSUE TITLE
You can't switch vents to 'internal'

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#33865]
It's thinking it's still on 'external'.

also i have a sneaking suspicion that it's because it doesn't detect when the target pressure is changed.

**Comment by praisenarsie** [comment]
@duncathan

**Comment by SgtxRootbeer** [comment]
It's because there's no signal sent to the vent.

I had an issue for this month's ago but was closed because it was a duplicate.

**Comment by SgtxRootbeer** [comment]
Wait, it was fixed... I'm retarded.

**Comment by praisenarsie** [comment]
this was on delta btw

**Comment by kriskog** [comment]
Long since fixed
