### ISSUE TITLE
OmegaStation: Two chemists one dispenser

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#33860]
OmegaStation has two Chemist job slots, but only one of each:
- Chem dispenser
- ChemMaster 3000
- Chemical heater
https://i.imgur.com/2SH2Hkf.jpg

This means that only one Chemist can do their job.

Proposed solution: Either reduce Chemist job slots to one by default or add the missing machinery.

**Comment by BeeSting12** [comment]
hot

**Comment by WJohn** [comment]
could probably be changed so there are two chem dispensers but only one chem master, since you don't typically USE the chem master for long stretches like you do with dispensers.
