### ISSUE TITLE
Its somehow possible to fill the ENTIRE station with metal foam

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#33898]
Happened a few days ago and I don't know the round ID, but it was in the middle of the day and essentially everyone in the entire server noticed it so there are probably a few witnesses here. I'm not sure HOW it was done either, and either no one else knows, or they won't speak up when I ask about it.

Nonetheless despite the lack of info this is a pretty serious thing. Suddenly making the entire station solid and difficult as fuck to move through is a big deal, so I'm making a issue report to see if anyone else can help figure out whether this was just some debug item from a christmas tree or not.

**Comment by OmegaShoots** [comment]
Christmas tree can produce admin items and I'm very certain a no maxcap metal foam nade is one of said items.

**Comment by AnturK** [comment]
Useless report without round ID
