### ISSUE TITLE
Frequent crashing as AI while moving camera around

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#33890]
```
Byond; 512.1401
Server revision compiled on: 2017-12-28
The following pull requests are currently test merged:
#33766: '[READY FOR TESTING] Refactors shuttles to be loaded in, rather than be on the station maps' by coiax at commit 508233
#33888: 'relic teleport no longer recursively calls itself' by optimumtact at commit f69125
Based off origin/master commit: 585674
Server tools version: /tg/station 13 Server v3.2.1.9
Server tools API version: 3.2.0.1
```

What is says on the tin. Rapidly moving the camera around with diagonal movement seems to be the worst offender, but it's also happening after leaving the camera stationary in a busy area for 5~10 minutes and then moving.

Easy repo;
Hold down two directions at once and do laps around the station
20~ seconds later, dreamseeker hangs.

**Comment by newfren** [comment]
#32907 (maybe)
#33000

**Comment by optimumtact** [comment]
this doesn't need to keep being re-reported, it's most likely a byond issue

**Comment by ShizCalev** [comment]
#33377
