### ISSUE TITLE
wHAT THE FUCK KIND OF ABOMINATION DID THESE ABDUCTOR ORGANS MAKE

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#33894]
![image](https://user-images.githubusercontent.com/16315400/34400956-b60e910c-eb64-11e7-83c5-1742c9922935.png)
![image](https://user-images.githubusercontent.com/16315400/34400959-c0faa416-eb64-11e7-9f65-fe12c8220976.png)
It was still moving while dead, and delimbed, and cuffed, and buckled, and stunned. It couldn't die no matter what, it couldn't be stopped, and it randomly liked to move to one specific spot for some reason.

Roundid: 80930

I think the ayy organ makes a snpc but WHY IS IT MOVING WHILE DEAD AND DELIMBED AND WHY CAN'T IT BE STOPPED?!

**Comment by XDTM** [comment]
Welcome to hardcoded behaviour

**Comment by ShizCalev** [comment]
Terminator, Terminator!

**Comment by ChangelingRain** [comment]
snpcs are bad code

**Comment by banthebantz** [comment]
feature

**Comment by YPOQ** [comment]
https://github.com/tgstation/tgstation/blob/bc20a758d5f2e75e93587a58c4cd0ea5009bf243/code/modules/mob/living/carbon/human/interactive.dm#L611
missing a call to IsDeadOrIncap() here (and like a million other places as well, the whole thing probably should be rewritten or cut down)
