### ISSUE TITLE
Roundstart and roundend music and sounds no longer play

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#33901]
The roundstart song, roundend song, and roundend noise (eg "APC DESTROYED MISSION ACCOMPLISHED") no longer play. 

The following pull requests are currently test merged:
#33766: '[READY FOR TESTING] Refactors shuttles to be loaded in, rather than be on the station maps' by coiax at commit 508233 
#33892: '[DNM] Revert "[READY]Component Forensics and Item Blood OverlayS!"' by MoreRobustThanYou at commit b9c012 

This does not occur on local servers, even with the latest version downloaded from git.

Other users have reported this and it's occurred 100% consistently for a while now, some examples are rounds 80940 through 80944, though it occurred earlier than 80940 and will probably continue after 80944.

**Comment by MoreRobustThanYou** [comment]
this will need someone with access to the server files, as my PR changed the folder structure of roundstart music and roundend sounds

**Comment by lzimann** [comment]
Not a bug, it's just that the old system was removed entirely and no one updated the live servers with the new config folders.
