### ISSUE TITLE
Plasma floor tiles, once ignited, add the standard 101kpa airmix to their tile in addition to their plasma

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#33913]
[Round ID]: 80964

[Testmerges]: The following pull requests are currently test merged:
#33766: '[READY FOR TESTING] Refactors shuttles to be loaded in, rather than be on the station maps' by coiax at commit 508233
#33892: '[DNM] Revert "[READY]Component Forensics and Item Blood OverlayS!"' by MoreRobustThanYou at commit b9c012
#33908: 'Revert "[READY] Easy hosting of roundend sounds (#33618)"' by Cyberboss at commit 5e961e

[Reproduction]: Get a room under vacuum, and pave it with plasma floor tiles. Ignite them and notice a fire is formed. Using an analyzer you will find the air to contain about 70% nitrogen and 20% oxygen, which normally shouldn't be there. This only happens floor tiles, plasma sheets and statues both only produce superheated plasma.

**Comment by praisenarsie** [comment]
p sure hitting any floortile will say the standard 79% 21% airmix

**Comment by Iatots** [comment]
No.

**Comment by duncathan** [comment]
hm interesting

**Comment by ShizCalev** [comment]
@duncathan

**Comment by duncathan** [comment]
cannot reproduce

**Comment by ninjanomnom** [comment]
It's been a while and we've had some changes to the related code so I'm just closing this

**Comment by kriskog** [comment]
Should be fixed in #44980
