### ISSUE TITLE
Holding W in WASD mode and then switching to arrowkeys will make your W key "stuck"

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#33921]
how to reproduce

1) hold W in WASD mode
2) While holding W, press TAB to switch to arrowkeys.
3) you are now being forced to walk up

To fix this;
1) Click TAB to switch back to WASD
2) Click W

This works for the other WASD keys too. It doesn't work for arrowkeys though.

**Comment by ninjanomnom** [comment]
This is not worthwhile to fix as the only fix I see would make tab a fairly expensive operation for something available to players on a hotkey.

You'd need to loop through available keys in the last mode and keyUp every one that isn't also in the mode you're switching to.

**Comment by DaxDupont** [comment]
It constantly get stuck, it's really fucking annoying. Fix your fucking shit @ninjanomnom.

**Comment by ninjanomnom** [comment]
Why are you pressing tab while moving?

**Comment by DaxDupont** [comment]
Because sometimes you need to rapidly switch to chat mode and I hate use the chat text box.

Like when you're getting chased by say marauders, you only have like a few seconds to scream help while moving without having to worry about depressing keys.

This was the old behaviour and was fine.

**Comment by kriskog** [comment]
This isnt happening anymore after they hotkey PR
