### ISSUE TITLE
Create Command Report should be IC

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/tgstation#33936]
After a discussion in the administrator forums, the pop-up text when you press the Create Command Report says "Please enter anything you want. Anything. Serious."

This has been giving new admin candidates the wrong impression, and should be updated to reflect the new policy.

I'd suggest "Enter a Command Report. Ensure it makes sense IC."

**Comment by praisenarsie** [comment]
😕

**Comment by Armhulen** [comment]
@praisenarsie hi

**Comment by praisenarsie** [comment]
🚶
