### ISSUE TITLE
It's possible to fry water misters

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#33946]
![image](https://user-images.githubusercontent.com/609465/34450481-cd7b9c2e-ed01-11e7-8a68-306d25248db1.png)

![image](https://user-images.githubusercontent.com/609465/34450483-e12201e6-ed01-11e7-9ce2-c8283311241f.png)

Round ID: 81034

**Comment by arsserpentarium** [comment]
Why not?
Was it tasty?

**Comment by DaedalusGame** [comment]
water mister is abstract i think, it shouldn't exist without the tank, that's why.
