### ISSUE TITLE
Hallucination text formatting is leaky

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#33952]
Round ID: 81058

[Common] Landen Carmichael exclaims, "[target.first_name()] is a ling!"

**Comment by XDTM** [comment]
i forgot that file text replacement is not a thing yet

**Comment by RemieRichards** [comment]
@XDTM it should never be, atleast not like the above.
What if ```target``` is renamed? what if ```first_name()``` is renamed or removed?

if you want shit like that you need a small DSL like %TARGETNAME%, and you process that, not raw brittle DM code.

**Comment by XDTM** [comment]
Thing is, i initially made it as a list of possible sentences, which did work with that code, but i've missed a couple of these when moving them to a json file.

I didn't think of that method, i might use that instead of just giving up on the idea

**Comment by RemieRichards** [comment]
its done for Ion laws, for example, so it's certainly got precedence in game.
(and is pretty much how you should do it anyway)
