### ISSUE TITLE
Lattices and catwalks are burnt by lava in templates.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#33963]
It's a shame because these look really nice on lava AND they can't even be built on them. I'd like to see them *not* burn on it so it's possible to use them in lavaland ruins. This is probably a bug since there exists mechanics to prevent you from burning on lava if there is a catwalk there, and using spawn does not have them burn when placed on lava.

Unsure if these burn when spawned in via pre-round ruin placement, but definitely with admin template spawning.

**Comment by ShizCalev** [comment]
Lava _can_ melt steel beams. Intended.

**Comment by WJohn** [comment]
So from further testing, these do not burn when loaded in pre-round. They *only* burn if placed via admin template.

**Comment by AnturK** [comment]
It's the same thing as the wire issue, uninitialized lattices get affected by turf AfterChange
