### ISSUE TITLE
GUID() is expensive but some stoned idiot made timers use it so now stoppable timers are needlessly expensive to create

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#33972]
see: title.

Also that stoned idiot wasn't me, I swear.

Should we move that back to numbers, or try to speed up guid.

the cost is mostly self, so I think it might be the rand() calls or the proc calls or the way it concats the string, the actual num2hex couldn't be causing it or we'd see that show up in total more than self.

**Comment by Iamgoofball** [comment]
just scrape the numbers from every connected ckey and randomly assemble them

**Comment by vuonojenmustaturska** [comment]
We can do both, PR soon

**Comment by vuonojenmustaturska** [comment]
@MrStonedOne 
```
GLOBAL_VAR_INIT(BigID_cur,1)
GLOBAL_VAR_INIT(BigID_pfx,1)

// These generates IDs like 1A1, 1A2... 1A16777210, 2A1, 2A2...

#define BIGID (GLOB.BigID_cur > 16777210 ? "[num2text(GLOB.BigID_pfx++,8)]A[num2text((GLOB.BigID_cur/=GLOB.BigID_cur),8)]" : "[num2text(GLOB.BigID_pfx,8)]A[num2text(GLOB.BigID_cur++,8)]")

/proc/BigID() 
	if (GLOB.BigID_cur > 16777210)
		GLOB.BigID_pfx++
		GLOB.BigID_cur = 1
	return "[num2text(GLOB.BigID_pfx,8)]A[num2text(GLOB.BigID_cur++,8)]"
````

Tested and works, guaranteed to be unique during a round. The define and the proc are equivalent. What are your requirements for GUIDs, do you require them to be unique across restarts, servers etc or just during a round?

**Comment by MrStonedOne** [comment]
GUID is a universal format. https://en.wikipedia.org/wiki/Universally_unique_identifier#Format

It should guaranteed to be unique across servers across continents across time zones across dimensions across alternative universes.

Thats why its both time based and random based. 48bit collision window that rolls over every millisecond.

So your system could work, but its not a GUID.

**Comment by optimumtact** [comment]
so don't use it for timers then you chumbis

**Comment by MrStonedOne** [comment]
They asked if it would work to replace GUID, read their comment you chumbis

**Comment by optimumtact** [comment]
you a chumbis first
