### ISSUE TITLE
You stop orbiting a xeno when it evolves

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#33973]
1) Orbit a drone as an observer
2) It evolves into prae.
3) You stop orbiting it.

Round ID: 81096

**Comment by ShizCalev** [comment]
it's because evolve spawns a new mob and the user is transferred over to it via alien_evolve()

**Comment by coiax** [comment]
Yeah, I'm aware, but it's still annoying.

**Comment by WJohn** [comment]
This is a pretty minor bug but I imagine this occurs with orbiting anything that changes subtype.
