### ISSUE TITLE
Instant Summoning Demon Hearts from Players in Bloodcrawl traps their bodies.

### ISSUE THREAD

**Issue by Mey-Ha-Zah** [tgstation/tgstation#33977]
[Round ID]: # 81098

Ausops helped me test this.

[Reproduction]: # If a wizard with instant summons, casts the spell on a demon heart, then leaves it somewhere or gives it to someone and waits for them to bloodcrawl, he can then summon the heart from them, killing them and trapping their body in nullspace where they cannot be saved.

**Comment by ChangelingRain** [comment]
this. is a feature.

**Comment by ChangelingRain** [comment]
to expand upon that, being able to steal organs with instant summons is intended and I think this is hilarious enough to keep.

**Comment by Mey-Ha-Zah** [comment]
Alright
