### ISSUE TITLE
making a wall on shuttle and then deconstructing it creates space tiles

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#33984]
[Round ID]: 81131
How to reproduce:
1. Be on shuttle.
2. Make wall to protect yourself.
3. Wonder whats going on other side of the wall.
4. Decon wall.
5. See space.
6. Get spaced instantly.
7. Die.
I am going to strangle the fucking coder that did this. This isnt even a mapping issue.

**Comment by evsey9** [comment]
probably related to https://github.com/tgstation/tgstation/issues/33907

**Comment by 81Denton** [comment]
See #33968

**Comment by ShizCalev** [comment]
@ninjanomnom

**Comment by ninjanomnom** [comment]
It's expected and part of the transition to list baseturfs, this can't be dealt with until shuttles aren't loaded directly on to maps anymore

**Comment by evsey9** [comment]
You can fucking depressurize the shuttle VERY easily with this.
Plop down a bunch of walls, deconstruct them - BAM. Space tiles.
Also, please explain how the thing with what you said would make new walls that appear on shuttles make space when deconned.

**Comment by WJohn** [comment]
Oh yeah, and girders are deleted upon being completed. Throw that in as part of the issue. Walls in general, really.

**Comment by evsey9** [comment]
TG sure is a quality codebase, where every change is thoroughly tested before being merged to make sure it doesnt have any issues.

**Comment by evsey9** [comment]
why the fuck is this not priority high rn
a huge feature of the game is literally unusable

**Comment by ninjanomnom** [comment]
because there's already another issue for that, don't combine bugs into one issue

**Comment by evsey9** [comment]
well @WJohn told me to do it, so

**Comment by Kromgar** [comment]
Base turfs are fuuuucked

**Comment by evsey9** [comment]
STILL NOT FIXEDD

**Comment by Kromgar** [comment]
IT NEVER ENDS

**Comment by AlexTheSysop42** [comment]
sonic jackhammer is the best way to kill everyone

**Comment by Buggy123** [comment]
What PR started this all?
