### ISSUE TITLE
A Ghostly Ravarian Spear Appears!

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#33988]
Issue reported from Round ID: 81142 (/tg/Station Bagil)

A large image of a bloody ratvarian spear appeared randomly on my HUD. Not sure how or why.

![dreamseeker_2017-12-31_16-01-21](https://user-images.githubusercontent.com/33107541/34464199-6cabc524-ee44-11e7-8156-3fc5c2ce8cb4.png)

**Comment by davethwave** [comment]
armament spell icon bug perhaps?
