### ISSUE TITLE
Mouse cursor flickers loading icon

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#33997]
Not sure how to trigger it intentionally but it happens now and then when loading into the game and seemingly never stops

Multiple people reported the same issue in OOC

I'm running Windows 10 64 bit and shit idk
Might be a byond issue

.gif of it happening

![flicker](https://file.house/jZ3Y.gif)

**Comment by ShiggyDiggyDo** [comment]
Windows 7 64bit, same problem

**Comment by SpaceManiac** [comment]
This has been happening for a while and also interferes with the ability to see something's name in the status bar by hovering over it. Probably related to resource loading.

**Comment by WJohn** [comment]
Windows 10, also happens.

This is it due to loading assets, if I recall being told. It's also the reason why looking in the bottom left of the screen at what an object is also has its name flicker constantly. Probably a byond issue.

**Comment by ShizCalev** [comment]
Curious, this couldn't have been affected by precaching all the R&D console UI stuff (that generates icons of -everything-,) would it?

**Comment by SpaceManiac** [comment]
Precaching all the icons increases load times and thus makes this BYOND bug more obvious but I thought of a workaround to try so I'll see if that goes anywhere.
On Jan 25, 2018 2:23 PM, ShizCalev <notifications@github.com> wrote:Curious, this couldn't have been affected by precaching all the R&D console UI stuff (that generates icons of -everything-,) would it?
