### ISSUE TITLE
Lavaland syndicate base self-destruct literally breaches lavaland to space

### ISSUE THREAD

**Issue by awesine** [tgstation/tgstation#33993]
[Round ID]: 81153

[Testmerges]: The following pull requests are currently test merged:
#33766: '[READY FOR TESTING] Refactors shuttles to be loaded in, rather than be on the station maps' by coiax at commit 49f8a0
#33979: 'Implements the Ballmer Peak: Now the bartender can help R&D!' by Iamgoofball at commit aeae5e

[Reproduction]:
1. activate lavaland self-destruct
2. wait for it to blow up
3. lavaland is exposed to space

![wow](https://i.imgur.com/UMCFQz4.png)

**Comment by WJohn** [comment]
Oh fuck whoops I forgot to put in the baseturf editor balloons I'll get a fix up ASAP.
