### ISSUE TITLE
Runic Golems literally blind you forever

### ISSUE THREAD

**Issue by ShiggyDiggyDo** [tgstation/tgstation#33998]
Round ID: 81158

Server revision compiled on: 2018-01-01

The following pull requests are currently test merged:
#33766: '[READY FOR TESTING] Refactors shuttles to be loaded in, rather than be on the station maps' by coiax at commit 49f8a0
#33979: 'Implements the Ballmer Peak: Now the bartender can help R&D!' by Iamgoofball at commit aeae5e

Based off origin/master commit: e84a7f
Server tools version: /tg/station 13 Server v3.2.1.9
Server tools API version: 3.2.0.1

I was an abductor and abducted a Runic Golem. He used Abyssal Gaze to blind me, but the blindness effect didn't wear off and I was blinded forever. Admin gave me 3 different pairs of eyes but it didn't help at all.

**Comment by XDTM** [comment]
Probably related to the disability refactor, i'll check.
