### ISSUE TITLE
Adding plating to wall girders deletes them

### ISSUE THREAD

**Issue by ShiggyDiggyDo** [tgstation/tgstation#33994]
Round ID: 81153

Server revision compiled on: 2018-01-01

The following pull requests are currently test merged:
#33766: '[READY FOR TESTING] Refactors shuttles to be loaded in, rather than be on the station maps' by coiax at commit 49f8a0
#33979: 'Implements the Ballmer Peak: Now the bartender can help R&D!' by Iamgoofball at commit aeae5e

Based off origin/master commit: e84a7f

Steps to reproduce:
1. Build normal wall girders with metal
2. Try to add plating with metal
3. Watch the wall girders disappear

**Comment by MrMaclang** [comment]
but did it build a wall? if it did, not a bug.

**Comment by InsaneKatrina** [comment]
This is an issue I've noticed on my round as an engi, adding the final plating to finish up a wall immediately causes it to vanish upon completion, with that you also lose the metal sheets you've been using to build it.

Gouty has also made confirmation of this by testing it on his end, I am still uncertain if this is a random round bug or if its consistent. I'll have another try at it.

**Comment by ShiggyDiggyDo** [comment]
Adding plating does not create a wall, it just deletes the girders.

**Comment by WJohn** [comment]
Known issue #33984
