### ISSUE TITLE
BALANCE:Pinion airlocks are even immortal from pulse rifle fire.

### ISSUE THREAD

**Issue by JessHorserage** [tgstation/tgstation#33990]
Issue reported from Round ID: 81149 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

I try to shoot a clock cultist door with a shotgun with a pulse slug in it, basically a shot from death squad  themselves, and it eats up an infinite number of shots. This

**Comment by Anonmare** [comment]
>Wasting pulse slugs on a door you can just deconstruct

Also I've encountered this but I presumed it fixed after clock ops. 
@Xhuis

**Comment by Xhuis** [comment]
This is pretty ridiculous, I'll look at it.

**Comment by YPOQ** [comment]
I think I found part of the problem:
The pulse projectile calls ex_act with a severity of EXPLODE_HEAVY (1) and null target on the airlock
https://github.com/tgstation/tgstation/blob/e75964f584b9f963228f33aa032f083c6c0e425c/code/modules/projectiles/projectile/beams.dm#L79
Door's ex_act decrements the severity to 0
https://github.com/tgstation/tgstation/blob/c4a495929c81ae92d756b61e70d1965464c6d410/code/game/machinery/doors/door.dm#L369
However obj's ex_act doesn't handle the 0 case at all (unless target == src)
https://github.com/tgstation/tgstation/blob/0c473c45319756a8d7f8245f055e47ba17fd2eb1/code/game/objects/obj_defense.dm#L65
That being said the airlock is still taking the non-explosive damage in my testing and will be destroyed in roughly 8 hits.
