### ISSUE TITLE
Katana from Lavaland Sheathing

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#33991]
Issue reported from Round ID: 81149 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Katanas from lavaland chests do not fit into backpacks (Excluding bags of holding obviously), backpack slots, or belt slots. Or any exosuit slots that I tried out.

Not sure if bug or feature.

**Comment by lzimann** [comment]
Not a bug, changed on #31699
