### ISSUE TITLE
golems' genetics are fucked up

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#33999]
their dna doesn't match humans', so they can't use the genetics console/use the occupant button on buffers.
however, the occupant:delayed function still works on them, and gives them powers
i think one of these is unintended, but i don't know which

**Comment by XDTM** [comment]
It's because they're immune to radiation; it should block all types of use.

**Comment by factoryman942** [comment]
ok so the delayed occupant buffer thing shouldn't work for them then
or maybe just make it not close on golems or something?
