### ISSUE TITLE
borg names can have links

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#33996]
presumably non-borg names can have links too 
time for me to name my borg pornhub.com

**Comment by ShizCalev** [comment]
feature

**Comment by SpaceManiac** [comment]
Full HTML or just links? The latter also applies to IC dialogue, it's a goonchat thing.

**Comment by optimumtact** [comment]
yeah what @SpaceManiac said

all the ways borgs are name has reject bad name, so you could only set something like www.pornhub.com and have that linkified (annoying feature of goonchat though)
