### ISSUE TITLE
SME Delamination gives weird blackscreen visuals then returns to normal.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#34004]
Round ID: 81184

Server revision compiled on: 2018-01-01

The following pull requests are currently test merged:
33979: 'Implements the Ballmer Peak: Now the bartender can help R&D!' by Iamgoofball at commit aeae5e
33766: '[READY FOR TESTING] Refactors shuttles to be loaded in, rather than be on the station maps' by coiax at commit 49f8a0

Based off origin/master commit: e84a7f

**Comment by Tlaltecuhtli** [comment]
its because of the shaking

**Comment by praisenarsie** [comment]
@Cyberboss did you even test your explosive shake pr

**Comment by Cyberboss** [comment]
I did, idk why it's causing black screen
