### ISSUE TITLE
Gasses mined from gas miners do not spread to other tiles when spawned in pre-round.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#34000]
![](https://i.imgur.com/3mzG1Hd.png)

This syndicate lavaland base spawned in pre-round, and the gas did not spread from that one tile. The survivalist bunker also had the same issue.

Maps with gas miners in them loaded in via admin template work fine, however.

**Comment by praisenarsie** [comment]
@duncathan

**Comment by duncathan** [comment]
sounds like a map loader problem in which these aren't calling `air_update_turf(TRUE)` at the appropriate time

**Comment by WJohn** [comment]
Yup, in some rounds they work, others they do not.
