### ISSUE TITLE
Scout stands can touch the SM and instantly die while in ghost mode

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#34002]
Roundid:81173

Steps to reproduce:
1: Be ranged stand in scout mode (incorporeal, unlimited range, **can't touch anything**)
2: Touch supermatter
3: Dust yourself and your master

WHY

**Comment by GuppyLaxx** [comment]
btw, doesnt dust the master, only the stand

**Comment by Buggy123** [comment]
Which dusts the master.

**Comment by GuppyLaxx** [comment]
ye

**Comment by Buggy123** [comment]
TBH any instantkills for stands really shouldn't kill the master as well, just delete the stand. Stands are kinda meh anyway so it wouldn't be a big deal.

**Comment by KorPhaeron** [comment]
>can't touch anything

This isn't true at all, you even take extra damage in this mode if something manages to hit you

**Comment by Buggy123** [comment]
Well, I mean technically YOU can't touch anything... other things can touch you, but you can't touch other things. And the issue is specifically if you touch the SM, not if you bump into it/it touches you somehow.
