### ISSUE TITLE
Construction Issues

### ISSUE THREAD

**Issue by Daturix** [tgstation/tgstation#34017]
A player ahelped that when you add rods to a normal, (wrenched and secure) girder it will delete the girder.
When done to an unsecured girder it makes a rough metal wall.

Then when adding a tile to a catwalk, it deletes the catwork and tile.
When applying another rod to where the tile was placed, then makes an underside tile and the lattice.
See picture link for each part of what happens step by step. http://prntscr.com/huu5d1
When applying another floor tile to the undertile+lattice and removing the tile, the lattice is gone.

**Comment by WJohn** [comment]
Yes, this has been reported a dozen times. #33984
