### ISSUE TITLE
Lavaland syndicate base: Turret targeting

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#34012]
Related to: #33962
@WJohn 

**Issue**:
When enemies (fauna, miners, etc.) are at certain areas outside the lavaland syndie base, the turrets will shoot windows and depressurize rooms.
Look at this crappy MSPainted screenshot for an example:
https://i.imgur.com/Qsmw8NH.jpg

**Comment by WJohn** [comment]
Yeah, Noticed this myself. May have to make telecomms inset like with virology so the windows don't get hit. I'll fix it shortly.
