### ISSUE TITLE
Camera gets stuck when you go through a portal by clicking

### ISSUE THREAD

**Issue by ShiggyDiggyDo** [tgstation/tgstation#34011]
Round ID: 81190

Server revision compiled on: 2018-01-01

The following pull requests are currently test merged:
#33979: 'Implements the Ballmer Peak: Now the bartender can help R&D!' by Iamgoofball at commit aeae5e
#33766: '[READY FOR TESTING] Refactors shuttles to be loaded in, rather than be on the station maps' by coiax at commit 49f8a0

Based off origin/master commit: e84a7f
Server tools version: /tg/station 13 Server v3.2.1.9
Server tools API version: 3.2.0.1

1. Click on a portal next to you
2. Your camera is now stuck on the portal
3. Use Cancel-Camera-View to fix it

**Comment by praisenarsie** [comment]
@kevinz000 FYS

**Comment by ShizCalev** [comment]
doTeleport() should be canceling camera view, weird.

**Comment by SpaceManiac** [comment]
Reproduced. Bisect points to #33881. @AnturK

**Comment by ShizCalev** [comment]
Forgot to update the tag after testing it myself, whoops.
