### ISSUE TITLE
Bugs where floor platings and walls disappear upon construction.

### ISSUE THREAD

**Issue by InsaneKatrina** [tgstation/tgstation#34010]
Issue reported from Round ID: 81186 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG]) - and every round after that.

As the name suggests, floor platings (The floors you build on top of lattices in space) and walls disappear immediately upon being built.

[Reproduction]: Trying to place a floor down on a lattice causes the lattice to outright delete itself, making any breaches to space impossible to repair (I'm wirting this as of a moment a floorbot came by to fix it, even they have no match against the holes to space!), additionally the floor tile is removed from the hand with no effect.

ADDITIONALLY, any time you finish up building a wall by setting the final sheet of plasteel/metal/whatever causes the wall to vanish, losing all the materials you've put into it to waste.

**Comment by WJohn** [comment]
Known issue #33984
