### ISSUE TITLE
Lavaland syndie base: Fauna smashing base walls without LoS

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#34015]
Related to: #33962
@WJohn

Issue:
Lavaland fauna will "detect" syndie agents through base walls (no line of sight) and proceed to smash the walls in order to get to them.
https://i.imgur.com/rPemdEc.jpg
I am unsure if this is related to the current turf issues, like #33993 and #33907.

**Comment by GunHog** [comment]
Did any of them see you through the windows?

**Comment by 81Denton** [comment]
No, it started attacking the walls without seeing me.

**Comment by WJohn** [comment]
That probably isn't my fault, then. Might be some bug with simple animals.

**Comment by Buggy123** [comment]
Megafauna (and normal fauna too i think) can and will aggro through walls if you're close enough. The range is less than their line-of-sight aggro range, I'm guessing 2-4 ish tiles.

**Comment by WJohn** [comment]
Had this happen to me, too.

**Comment by 81Denton** [comment]
My bad! Didn't know that this is usual behavior for fauna.

**Comment by WJohn** [comment]
I doubt this is "normal" behavior tbh.

**Comment by FantasticFwoosh** [comment]
Might want to review whether placing tendrils & allowing simple that aren't flying like watchers to cross lava is really a good idea if they are going to bash things.

**Comment by WJohn** [comment]
This has been fixed.
