### ISSUE TITLE
Splash fried food is not edible.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#34024]
When you fry stuff by splashing it, you cannot eat it.

None of the fried metal rod left, oh no!

Round ID: 81204

Server revision compiled on: 2018-01-01

The following pull requests are currently test merged:
#33766: '[READY FOR TESTING] Refactors shuttles to be loaded in, rather than be on the station maps' by coiax at commit 49f8a0
#34005: 'Reverts explosion shaking' by praisenarsie at commit 56a19a

Based off origin/master commit: 28c42f

Server tools version: /tg/station 13 Server v3.2.1.9

Server tools API version: 3.2.0.1

**Comment by Cyberboss** [comment]
@vuonojenmustaturska
