### ISSUE TITLE
Construction is fucked

### ISSUE THREAD

**Issue by Catistian** [tgstation/tgstation#34053]
[Round ID]: # not round specific

[Testmerges]: #34005 Reverts Explosion Shaking
[Reproduction]: 
Step 1: Try to build a wall
Step 2: Add metal to girders
Step 3: Its gone

Step 1: Try to build on space
Step 2: Add floor tile to lattice
Step 3:  Its gone

**Comment by Electronics** [comment]
+1
If you then add rods to the space that is generated when you add the floor tile, the tile magics into reality with a lattice on top.

**Comment by DaxDupont** [comment]
Dupe of #34027 will be fixed when server updates

**Comment by AnturK** [comment]
Duplicate of #34027
