### ISSUE TITLE
Survival Pod Walls/Most other walls in ghost ruins when deconstructed on lavaland create lava

### ISSUE THREAD

**Issue by F-OS** [tgstation/tgstation#34055]
[Round ID]: # Happened over multiple rounds so sadly i do not have the round id, however shouldn't be needed afiak

[Reproduction]: #
1. Place survival pod/a ruin
2. Weld down walls
3. Expect to get regular basalt
4. Get lava.

**Comment by AnturK** [comment]
Duplicate of #33984 , maploader issue
