### ISSUE TITLE
Excess vars on objects ought to be flattened into bitfields/components

### ISSUE THREAD

**Issue by vuonojenmustaturska** [tgstation/tgstation#34063]
This issue is more of a personal memo so that i remember all i wanted to do. If you've got any ideas along these lines, feel free to post them here and i'll see if i can't get them done when i get all of this done.

/obj
* Pack in_use, can_be_hit, crit_fail, on_blueprints, force_blueprints, unique_rename, dangerous_possession into one bitfield var. Also pack in emagged from item and machinery and various other sparse subtypes, and perhaps various "on" states from machinery, cybernetics organs etc
* Long-term goal: consider replacing armor with a shared component to remove tens of thousands of immutable lists

/obj/item
* Pack the 8 embed vars into shared component instances
* Move emagged into the obj bitfield
* what the shit is this:
![image](https://user-images.githubusercontent.com/20017308/34522225-4fefdf44-f09a-11e7-903b-9c16868ccb96.png)
* Pack being_removed, needs_permit, suittoggled, hooded, in_inventory into new bitfield var/item_flags
* Investigate whether subtype booleans should be packed into parent bitfield

/obj/machinery
* consider packing stat into obj fields, as "broken" and "emped" are at least states shared with items and structures
* Move emagged into the obj bitfield
* Pack panel_open, state_open, critical_machine, interact_open, interact_offline, speed_process into var/machinery_flags  
* Investigate whether subtype booleans should be packed into parent bitfield

/obj/structure
* See if broken can be removed and replaced with a parent flag shared with machinery, if not make a new structure_flags var and pack in climbable and broken in it, possibly some child booleans as well.

**Comment by Cyberboss** [comment]
Related #34118

**Comment by MrStonedOne** [comment]
i feel like the issue op should go into why a bit more, as its likely to get linked to in the future when justifying change requests

**Comment by vuonojenmustaturska** [comment]
This was mostly done, at least to the point that there's no need to keep this issue up
