### ISSUE TITLE
Spawner apparently visible

### ISSUE THREAD

**Issue by LetterN** [tgstation/tgstation#34062]
Issue reported from Round ID: 81307 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])
station: omega
Testmerges: 
#34005: 'Reverts explosion shaking' by praisenarsie at commit 56a19a
#34061: 'Fixes compiler errors in the preload_rsc external resource thingy' by MrStonedOne at commit 4c3fb5

![spawner bug](https://user-images.githubusercontent.com/24603524/34521288-f710a56a-f0c7-11e7-8c18-35ed5a574652.PNG)

**Comment by praisenarsie** [comment]
@ShizCalev

**Comment by ShizCalev** [comment]
Will check in a bit.

**Comment by ShizCalev** [comment]
hng. found the issue.

**Comment by LetterN** [comment]
it got merged, closing this
