### ISSUE TITLE
Ventcrawling Mobs can leave vents my using diagonal movement

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#34071]
Issue reported from Round ID: 81318 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

As a drone (and probably a xenomorph too), you can leave the vents by moving diagonally instead of exiting through a pump or scrubber normally.

**Comment by Ratvar** [comment]
dupe of #33966, #33891, #33717, #33528 ... stop et
