### ISSUE TITLE
Technology disks cost to much?

### ISSUE THREAD

**Issue by furryowl** [tgstation/tgstation#34072]
OP

**Comment by furryowl** [comment]
For example:
time: 4 min.
tech list:
Biological Technology
Data Theory
Industrial Engineering
Basic Bluespace Theory
Electromagnetic Theory
Basic Research Technology
value: 50000 credits

**Comment by Buggy123** [comment]
WHY DID YOU REPORT THIS FUCK NO INTENDED FEATURE IGNORE THIS AAAAAAAAAAAAAAAAAAAA

**Comment by furryowl** [comment]
@Buggy123 Because cargo raids RnD every round on a server where i play and having 130.000 credits makes mechanics like stocks,mining,sending crates back e.t.c useless?

**Comment by Buggy123** [comment]
And all of those methods are also kinda useless for about half of the cases where you would want to order a bunch of shit, so it works out just fine?

**Comment by MrMaclang** [comment]
you cant sell ores.

**Comment by ma44** [comment]
To be fair, tech disks are the new king of cargo exports, making several millions in points over literally everything.

**Comment by Tlaltecuhtli** [comment]
who was that faggot scientist that didnt research adv mining

**Comment by Repukan** [comment]
Actually you can sell ores again, afaik Kor reverted it

**Comment by kevinz000** [comment]
why is this not in the techwebs thread and instead in a BUG, BUG, and I emphasize, BUG REPORT?

**Comment by FantasticFwoosh** [comment]
Why are you suprised? Go figure nobody uses the forums or enforces use of it anyway for the inevitable division of code & community meme. On the subject there's been multiple attempts to nerf etc but people collectively get so much powergame value out of the disks (even before i "quit") to actually let go and remove it if head coders don't care about changing it.

**Comment by KorPhaeron** [comment]
Can no longer sell them
