### ISSUE TITLE
ShadyCigs Deluxe vendor in Captain's quarters not showing item names

### ISSUE THREAD

**Issue by yorii** [tgstation/tgstation#34079]
[Round ID]: 81333

[Testmerges]: Revision unknown. Server tools version: /tg/station 13 Server v3.2.1.9

[Reproduction]: ShadyCigs Deluxe vendor in captains quarters not showing names of items.

[For Admins]: N/A

[Image here](https://i.imgur.com/DYmY7nA.png)

**Comment by yorii** [comment]
Hmm, I added the roundid but it doesn't show up, for anyone wondering it was 81333.

**Comment by LetterN** [comment]
:4

**Comment by ShizCalev** [comment]
round logs are missing for that round, assuming this was on meta?
