### ISSUE TITLE
blob camera gets stuck when spawned in certain locations

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#34073]
Forgot the round ID that I saw it most recently, but it had happened in others as well (including to me once). When someone becomes a blob overmind, their blob camera remains wherever their ghost/body was. There are some tiles that blob cameras can't move over, such as space tiles. If you become an overmind while over a space tile, your camera can get stuck until autoplacement.

**Comment by LetterN** [comment]
cancel-cammera is a quickfix
