### ISSUE TITLE
Traitors don't always show up in end report

### ISSUE THREAD

**Issue by Catistian** [tgstation/tgstation#34098]
Issue reported from Round ID: 81371 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

[Round ID]: # 81371

[Testmerges]: #34005 #34061 

[Reproduction]: # Play entire round as a traitor. Was Threads-The-Needle, I had to get some research and escape alive. At the end round panel, I wasn't there. No idea how to reproduce

**Comment by AnturK** [comment]
Did you use any TC this round ?

**Comment by Catistian** [comment]
Yep, I did. I got a syndicate tome, a syndicate encryption key, an uplink implant, and I think that is it.

**Comment by ShizCalev** [comment]
![image](https://user-images.githubusercontent.com/6209658/34599937-0e3d4bc0-f1c3-11e7-9b47-7ada109967b1.png)
What I spent my TCs on didn't show up in the final window, 81397 - bagil.
