### ISSUE TITLE
Gibtonite won't explode

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#34103]
Issue reported from Round ID: 81382 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

![image](https://user-images.githubusercontent.com/6778786/34589755-6c555bdc-f180-11e7-943c-eb7d1b149200.png)

If you fire at gibtonite deposits they never explode. If you fire at them again they drop no gibtonite. Gibtonite crystals do not explode either.

**Comment by Repukan** [comment]
Wouldn't it have been easier to screen cap the whole screen showing round ID too instead of cropping only the date.

**Comment by Buggy123** [comment]
Note, this issue did not reoccur as of next round.

**Comment by MrStonedOne** [comment]
Fixed by #34091
