### ISSUE TITLE
Omegastation has a second departure lounge that looks leftover from mapping

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#34115]
Round ID:81401
![image](https://user-images.githubusercontent.com/12382984/34602439-a4a279a8-f1f7-11e7-8d02-9d951a0e83a6.png)
![image](https://user-images.githubusercontent.com/12382984/34602444-aa804512-f1f7-11e7-8526-fb0d2a53fcd3.png)
![image](https://user-images.githubusercontent.com/12382984/34602453-afea12da-f1f7-11e7-82d9-72d595e9c708.png)

**Comment by Anonmare** [comment]
Just keep heading right from the actual departure lounge to see it, I saw a dead person there who looks like an actual player as well who got caught short

**Comment by ShizCalev** [comment]
Already fixed by #34070
