### ISSUE TITLE
when using a mind transference potion on a headslug with an automatic cloning pod with your record saved you get cloned instead of turning into a changeling

### ISSUE THREAD

**Issue by yorii** [tgstation/tgstation#34137]
[Round ID]: 81446

[Testmerges]: #33916, #34061, #34086, #34118

[Reproduction]: Upgrade cloning pod to have autoprocess enabled, save a record of yourself, use a mind transference potion on a headslug, lay an egg in your now dead body, once the headslug death triggers you will find yourself automatically cloned instead of the intended result of your old body turning into a changeling.

**Comment by yorii** [comment]
Also related: headslugs only have one egg? We tried reviving it with a lazarus injector only to find it couldn't lay any more eggs.

**Comment by The-clown-known-as-Pepe** [comment]
when it lays eggs it dies

**Comment by yorii** [comment]
Yes, but we revived it to try again, didn't work.

**Comment by kevinz000** [comment]
this is literally a feature wtf.
