### ISSUE TITLE
Spectral blade damage to objects is unaffected by # of ghosts

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#34135]
A spectral blade seemingly cannot break a window even if 50 ghosts orbit the same person. Even though ti should be doing decent damage
  
Seems to include damage to mechs as well

**Comment by Hatfish** [comment]
are they orbiting the person or the blade?

**Comment by Kromgar** [comment]
@Hatfish How can you tell?

**Comment by Hatfish** [comment]
I honestly don't know whether it affects the blade's power or not, I was kind of hoping someone else would chime in on whether it did anything or not.

**Comment by kriskog** [comment]
Closing in favor of #47302
