### ISSUE TITLE
Syndicate Internal Radio Implant Prevents Headset from Working on Other Channels

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#34136]
Issue reported from Round ID: 81447 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Like the title says, when you use the internal syndicate radio implant, you cannot use any of the other channels in your headset. For example, mining headset cannot use the supply or science channels, even when swapping to another headset. Same with the research director's headset.

**Comment by Jalleo** [comment]
Apparently this is intended to work as it does. It seems to be a consistency and usability issue to me.
