### ISSUE TITLE
Explosive plastitanium walls destroyed by simple animals will detonate.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#34144]
This, paired with #34015 means that a plucky goliath situated someplace next to an explosive wall who agros THROUGH the wall can detonate the whole base with no way of seeing this coming.

GENIUS.

**Comment by Repukan** [comment]
How do they aggro through the wall?

**Comment by praisenarsie** [comment]
a* is magic

**Comment by ShizCalev** [comment]
That seems like intended behavior, since the walls are supposed to detonate when destroyed?

**Comment by WJohn** [comment]
They're supposed to detonate when hit by the self destruct, that's their entire purpose. Unfortunately, any random ol' goliath or other creature can just bash down a wall and cause the whole base to explode.

**Comment by ShizCalev** [comment]
Oh, when I made those I thought they were supposed to be triggered by just destroying the walls to break in.

**Comment by Kromgar** [comment]
@ShizCalev Fucking what?

People were allowed to break in and loot the place if they are good enough to survive the snipers or worst case scenario the syndicates decide to detonate the base.

**Comment by ShizCalev** [comment]
#31637 / #31645

Nobody mentioned it ¯\_(ツ)_/¯

**Comment by ShizCalev** [comment]
Oh wait right, I made it so they could dismantle the wall to break in, however if you destroy the wall it would blow up.

**Comment by WJohn** [comment]
Unfortunately, sniper bullets from accidentally carrying that can destroy walls. If you accidentally hit one of these, you can blow the whole base up, too.

**Comment by Repukan** [comment]
Sounds like an issue on trigger discipline rather than the wall fault.

**Comment by ShizCalev** [comment]
>can accidentally blow up a wall rigged with explosives by shooting it with explosive ammo

sounds like a feature to me.

**Comment by Chocodaemon** [comment]
Goliath's can aggro people in the chemistry room, even with windows closed. Round ID: 81634, around the 25 minute mark. Goliath broke 2 windows then hit a wall, blowing up the entire base.
