### ISSUE TITLE
can't rename ian with collar

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#34159]
checked ian's code, you should still be able to rename him. unless a mapper has set his pcollar var to 1 (though he'd have the collar overlay in that case i think)

**Comment by FantasticFwoosh** [comment]
Obviously a code solution is to just make map-generated unique pets like ian have unalterable names compared to other pet collarable like the generic pugs & corgi's you can buy from cargo/get from xenobio.

Nobody is renaming Ian, no.

**Comment by cacogen** [comment]
You used to be able to rename Ian. Now you can't. I checked the code and there's nothing in his code to prevent him from being renamed. He doesn't have the collar sprite. So either his pcollar var has been set on the map and his sprite isn't updating correctly, or something is wrong with the code that allows you to rename him. Regardless of how you feel about renaming him, there's a bug.

**Comment by ShizCalev** [comment]
#33156 broke it.

**Comment by yorii** [comment]
Don't fix it.
