### ISSUE TITLE
Injecting welding fuel into a cigar does no longer result in prank cigar

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#34167]
Instead it fucking blows up violently.

Either the wiki is wrong when I read it a while back but I definitely remember that welding fuel cigars had tiny harmless explosions and injection plasma ones would have a big one that kills/dismembers.

**Comment by ShizCalev** [comment]
![image](https://user-images.githubusercontent.com/6209658/34653180-7f4afe44-f3b6-11e7-9ffd-adb24829fc80.png)

Working fine here. How many units did you inject into them?

**Comment by DaxDupont** [comment]
Like 5? @Thunder12345 reproduced it as well

**Comment by ShizCalev** [comment]
![image](https://user-images.githubusercontent.com/6209658/34653423-8cd1441c-f3b9-11e7-958d-213248886d83.png)
Tried with exactly 5 units, worked fine. 

https://github.com/tgstation/tgstation/blob/f3a6fe14c805c2a41f232224524848432da501f0/code/game/objects/items/cigs_lighters.dm#L173-L184

Code looks fine too.

**Comment by Repukan** [comment]
You mean five units, or you injected it five times?

**Comment by DaxDupont** [comment]
That or it might've been an error on my end? Like double injecting a cigar accidently since I was doing it in on a box of them

**Comment by ShizCalev** [comment]
You should be able to inject that as much as you want, it'll just increase the size/force of the explosion.

**Comment by davethwave** [comment]
plasma cigars could be what your thinking of.

**Comment by Teepeepee** [comment]
I did this a while back, but instead of injecting some units into it I just dipped it into a beaker of welding fuel, I dismembered the arm I lit it with, tried again just to be sure with the other arm and ended up as a grey gondola. The "put welding fuel for prank" line really should specify injecting instead of dipping.

**Comment by Repukan** [comment]
Mate if your arm got blown the fuck out the first time and you decided to do it again it's less in the dipping/injecting specifications tbh

**Comment by Teepeepee** [comment]
well, I did it knowing it harmed me really bad the first time, I wanted to find out if it really did dismember the arm I lit it with or just a random limb and was happy to find the answer; what upset me was just losing a limb with what I was introduced to as a "harmless prank."

**Comment by ShizCalev** [comment]
it was just a prank bro

**Comment by epochayur** [comment]
should prank cigars really blow a hole through the floor? i don't remember any loony tunes gags that ended in explosive decompression

**Comment by ExcessiveUseOfCobblestone** [comment]
> I did this a while back, but instead of injecting some units into it I just dipped it into a beaker of welding fuel, I dismembered the arm I lit it with, tried again just to be sure with the other arm and ended up as a grey gondola. The "put welding fuel for prank" line really should specify injecting instead of dipping.

They should be relatively consistent.

**Comment by ShizCalev** [comment]
@epochayur the size of the explosion is based upon how much you put in the cigarette. i had used -alot- of plasma for that one haha,.

**Comment by jughu** [comment]
Remember when welding fuel didnt make ciggaretes explode but there was this one guy that was like HURR DURR PLASMA IS HARD TO GET IT ISNT LIKE THE WALLS ARE MADE OUT OF THEM WE GOTTA ADD WELDING FUEL FOR IT TOO

**Comment by ExcessiveUseOfCobblestone** [comment]
You can put like 15u into it which would give you a heavy 3?

**Comment by Jalleo** [comment]
https://github.com/tgstation/tgstation/pull/32300 could use the same sort of solution here.

**Comment by ShizCalev** [comment]
![image](https://user-images.githubusercontent.com/6209658/34749238-4507a020-f56e-11e7-9c26-1288abf8e2de.png)
this was 15 units of welding fuel.
