### ISSUE TITLE
golems arent virus proof

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#34165]
Issue reported from Round ID: 81524 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE bj
Round ID:  81524 

Server revision compiled on:  2018-01-05 

The following pull requests are currently test merged: 
#34118: 'Reduces the memory footprint of the gas_mixture datum' by MrStonedOne at commit b715be 
#34061: '[dnm]Fixes compiler errors in the preload_rsc external resource thingy' by MrStonedOne at commit 5e983e 
#34113: 'Fixes camera if destination changes mid forceMove' by AnturK at commit dda4f1 
------------------------------------------------------------------------------------------------
they have SPECIES_INORGANIC why do they get aids

**Comment by XDTM** [comment]
There is a symptoms that allows viruses to work on inorganics, maybe it was that. Or was it a basic disease?

**Comment by Tlaltecuhtli** [comment]
oh probably forgot about those
