### ISSUE TITLE
Goliath hide boat does not work on lava.

### ISSUE THREAD

**Issue by Memelizard** [tgstation/tgstation#34175]
Issue reported from Round ID: 81546 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

[Round ID]: # 81546
[Round ID]: # 81546
[Round ID]: # 81546

[Reproduction]: Using the tablecrafted goliath hide boat in lava does not make you immune to lava and still sets you on fire.

**Comment by 81Denton** [comment]
Worth noting that it also sets your handheld items on fire

**Comment by imsxz** [comment]
Denton that's a bug that affects flying people as well; if you move an item to one of your hands while over lava, it catches on fire. If you're already holding something and begin flying over the lava, it won't catch on fire. The same bug affects chasms, where it'll instantly drop the item.

**Comment by praisenarsie** [comment]
@kevinz000 nice fix
