### ISSUE TITLE
Golem ships walls deconstruct into lava pits

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#34172]
![image](https://user-images.githubusercontent.com/6778786/34651061-dfab1dc8-f398-11e7-8965-ea5eabc4a17d.png)

![image](https://user-images.githubusercontent.com/6778786/34651062-e46e4ff6-f398-11e7-98bf-3aa198cda573.png)
![image](https://user-images.githubusercontent.com/6778786/34651063-e85b12de-f398-11e7-9e67-8340fe680005.png)

![image](https://user-images.githubusercontent.com/6778786/34651066-ed30d5a0-f398-11e7-889f-fe977d7e5895.png)

If the front entrance is lava then the golems are completely and utterly fucked as there is literally no escape

**Comment by Marflowerose** [comment]
Probably same thing as https://github.com/tgstation/tgstation/issues/33907 https://github.com/tgstation/tgstation/issues/33968
https://github.com/tgstation/tgstation/issues/33984

**Comment by WJohn** [comment]
Yeah, dupe.
