### ISSUE TITLE
Hostile AI cant deal with circuits

### ISSUE THREAD

**Issue by imtakingabreakdontatme** [tgstation/tgstation#34176]
Circuit bots can be used to seek out and attack simple animals, but the mob AI does not recognize them as a threat.

**Comment by coiax** [comment]
Could just make circuit bots little mobs. We already have some existing code for "picking up" mobs as items, right?

**Comment by KorPhaeron** [comment]
Dont think itd be that simple to translate circuit ai into mob ai

**Comment by Jalleo** [comment]
If you see how pAI's and MoMMis work you will see that one has a mob following the pAI object about statically and the other creates a object to store the mob in or something when it gets picked up. The only weird solution would be to put a mob overlay invisible where the object is and let the simple AI be able to target it. I don't know how that would be possible. I think there was a bug where simple mobs attacked pAI's at one point or something.....

**Comment by arsserpentarium** [comment]
fixed
