### ISSUE TITLE
Chemistry Macros not Functioning Correctly

### ISSUE THREAD

**Issue by TribeOfBeavers** [tgstation/tgstation#34178]
Issue reported from Round ID: 81551 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Using the macro:
nitrogen=10;silicon=10;potassium=10;carbon=10;oxygen=10;sugar=10;carbon=15;silicon=15
Expected output is 
90 units of Tricord (30 Anti-Tox, 30 Bicaridine, 30 Kelotane)

Instead I get:
90 units of Tricord
10 units of Kelotane

Using the macro:
nitrogen=10;silicon=10;potassium=10;carbon=10;oxygen=10;sugar=10;carbon=20;silicon=20

Expected output is: 
90 units of Tricord
10 units of Kelotane

Instead I get:
90 units of Tricord
30 units of Kelotane

**Comment by TribeOfBeavers** [comment]
I did a bit more experimenting, this seems to be from repeating chems in the formula, and is dependent on the order:
water=2,water=1 gives 2 units of water
but 
water=1;water=2 gives 4 units

**Comment by SpaceManiac** [comment]
@MoreRobustThanYou

**Comment by MoreRobustThanYou** [comment]
I think you can't use the same ID twice in a macro, so combine like, carbon

**Comment by TribeOfBeavers** [comment]
I figured that out, but it probably should give an error or something. Right now it adds or removes chems seemingly at random without giving any feedback to the player.

**Comment by MoreRobustThanYou** [comment]
I'll make it automatically combine
