### ISSUE TITLE
macro chem cant do 15 or 30

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#34188]
http://take.ms/8Vh1Z

**Comment by ShizCalev** [comment]
@MoreRobustThanYou

**Comment by MoreRobustThanYou** [comment]
what's the macro TEXT you were using

**Comment by TribeOfBeavers** [comment]
I've made recipies with 15 and 30 so this seems like an error in the recipe you put in.

**Comment by Cyberboss** [comment]
The error is still non-descriptive. Improve it @MoreRobustThanYou
