### ISSUE TITLE
Chemistry macro requires that suphuric acid be spelt "sacid"

### ISSUE THREAD

**Issue by TribeOfBeavers** [tgstation/tgstation#34182]
Issue reported from Round ID: 81557 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

When using sulphuric acid in a recipe, it needs to be spelt "sacid".

**Comment by XDTM** [comment]
I guess it requires the code id for the chems, probably not much can be done about that

**Comment by MoreRobustThanYou** [comment]
this isn't a bug: this requires chem IDs, sacid is sulpacid ID

**Comment by ShizCalev** [comment]
Sadly this isn't a bug.
