### ISSUE TITLE
Mindshield Implant lost when changed into a monkey then back.

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#34192]
Issue reported from Round ID: 81586 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

As a changeling, I mindshield implanted myself, turned into a monkey, then back to human form, and the mindshield implant was no longer in me.

**Comment by OmegaShoots** [comment]
Probably also related, changing someone from monkey to human and vice versa causes them to not have the same reagents in them (genetics rejuvinators, the human has none if you pumped the monkey full of them)

Probably seems to be that it creates a new mob and then gives control over it?

**Comment by XDTM** [comment]
Everything has to be manually transferred from monkey to human and viceversa, probably chems and implants are missing

**Comment by Iamgoofball** [comment]
monkey is now a human species, which should have fixed this bug
