### ISSUE TITLE
Being hit by bullets from piggyback riding/borg riding

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#34193]
Issue reported from Round ID: 81588 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

So, if you're riding on a syndicate assault borg, and you have a shielded hardsuit and energy shield, and the syndie borg shoots its gun, the shots will hit you, instead of firing out ahead normally.

**Comment by praisenarsie** [comment]
@kevinz000

**Comment by Tlaltecuhtli** [comment]
can confirm shooting + vehicle causes it, i saw a magicarp on a scooter shooting, it shot the scooter

**Comment by kevinz000** [comment]
feature, intended for balance mechanic, it works fine if you don't charge forward in the direction you're shooting but if you use it to rush people you're liable to get shot.

**Comment by kevinz000** [comment]
ok
