### ISSUE TITLE
Active pipe components (pumps, connectors etc.) sometimes doesn't do anything.

### ISSUE THREAD

**Issue by kisiel090** [tgstation/tgstation#34200]
[Round ID]: 81565

Observed on multiple revisions in last couple of days.

[Reproduction]: Reattach existing pump. Sometimes it works, sometimes it doesn't.

Why is it bad: In this particular round I tried to make tritium, and to get more space moved the bottom filter (Filters nitrogen by default) a tile up. It didn't work even after reattaching twice in a row, and caused cooling loop of SM to be opened.

I have ecountered this bug multiple times, almost every round when i'm working with pipes.

**Comment by Jalleo** [comment]
@kisiel090 does this occur on multiple maps or the same map only?

**Comment by kisiel090** [comment]
As I play mostly on Metastation, and sometimes Omegastation, it's hard to say. I don't remember observing this issue on Omegastation though.

**Comment by Archemagus** [comment]
It has same problem, when u try to use pipes with shuttles. I maked pipe system on Aux Base before droping, and after drop used pipes on shuttle to transfer gas from station to base. So i'm reconecting pump after each fly

**Comment by LemonInTheDark** [comment]
This isn't very clear, and I'm honestly not sure if it should still be a thing
