### ISSUE TITLE
Reagents don't mix correctly sometimes.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#34238]
roundid 81646, terry **NOT USING MORTY'S CHEM MACROS BECAUSE TERRY WASN'T UPDATED**

![2018-01-09_21-13-24](https://user-images.githubusercontent.com/31222036/34743724-b70c9608-f582-11e7-94d4-7388fb48416e.png)
i wanted to get kelotane, i do 50carbon/50silicon and gives me the above amounts. i know it's not actually 1 carbon and 1 silicon and it's actually some really fucking long decimal like 0.4859083295 or some shit because i've had this happen before.

here's how i did it.
1. input 50 carbon
2. eject beaker and switch to a different chem dispenser
3. input 50 silicon and you don't get 100 kelotane

note this only happens SOMETIMES.

**Comment by newfren** [comment]
This happens very frequently when you have, for example, 20u of three different things and remove 10u three times instead of 30 all at once due to rounding errors.
