### ISSUE TITLE
Deadchat shuttle/alert information is formatted slightly differently

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#34230]
Event notification:
![image](https://user-images.githubusercontent.com/609465/34736652-a19f85bc-f56b-11e7-9db7-a62d2f80c048.png)
Death notification:
![image](https://user-images.githubusercontent.com/609465/34736668-aef9bc3c-f56b-11e7-9c2d-352712d1d5fe.png)

The new ghost notifications are inconsistent with the above.

Call the shuttle notification:
![image](https://user-images.githubusercontent.com/609465/34736832-2776cd8a-f56c-11e7-9408-b4e791c0be32.png)
Change the alert level notification:
![image](https://user-images.githubusercontent.com/609465/34736790-01501422-f56c-11e7-9767-41118d38b1d7.png)

Only the name should be in bold, and possibly also include an area name.

Round ID: 81642

**Comment by DaxDupont** [comment]
Eh, you can change it if you want. I wanted to have them completely bold.

I didn't include area name since there's a follow link anyways.
