### ISSUE TITLE
Lavaland ash storm indoor noise is too loud.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#34255]
I think both the oncoming storm and the full-blown thing should be quieter when you're indoors because it's nearly as loud as outside. Probably a very easy number tweak.

**Comment by yorii** [comment]
For anyones information: https://github.com/tgstation/tgstation/blob/master/code/datums/looping_sounds/weather.dm

I'm not comfortable enough having a guess at a reasonable volume to set.

**Comment by Repukan** [comment]
If all noises in the game are TOO LOUD for your ears, I think it's more of an issue of you having your volume too high up rather than the game, no?

**Comment by yorii** [comment]
I interpreted it as the indoor and outdoor sounds being of almost the same volume which is immersion breaking, not that any were too loud.

**Comment by WJohn** [comment]
What yorii said.

**Comment by Iatots** [comment]
Alright what's the meme behind "good first issue"?

**Comment by imsxz** [comment]
"good first issue" as in "good first issue to fix if you are trying to learn to code". Took me a fair bit to get that it didn't mean "this is your first issue and it's good".

Pretty sure the "good first PR" thing is a meme of people misunderstanding "good first issue" but I dunno

**Comment by PaznerIV** [comment]
Can we just add these new ambient sounds too hear/silence ship ambient sounds & hear/silence ambient sounds
