### ISSUE TITLE
Jump boots set you on fire when jumping over lava

### ISSUE THREAD

**Issue by xenon-difluoride** [tgstation/tgstation#34257]
When you jump over lava it still burns you, even when you wouldn't land on lava

I don't know the round ID or remember anything about the round because this was a while ago

To reproduce: get jump boots, stand next to a lava river small enough that you'll land on ground, face lava river, use jump boots (recommended but not part of reproduction steps: use extinguisher and burn patch after you get set on fire)

Might be a bug, might be intentional, but you should really be able to jump over lava

**Comment by WJohn** [comment]
Guess this is broken again.

**Comment by praisenarsie** [comment]
@kevinz000 
probably broke it when he ""fixed"" lava boats

**Comment by RandomMarine** [comment]
The fix was never merged in the first place.
#33526
#25858

This is the third time this was posted and I doubt it'll be the last.

**Comment by ExcessiveUseOfCobblestone** [comment]
Not a bug.

**Comment by optimumtact** [comment]
I'm gonna fix this

**Comment by optimumtact** [comment]
turs out I did not fix it

**Comment by LemonInTheDark** [comment]
better yet, someone fixed it for you
