### ISSUE TITLE
R&D console has inaccurate picture of slot machine

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#34269]
![image](https://user-images.githubusercontent.com/609465/34787535-7fd6444c-f62f-11e7-97c6-bd3351719abd.png)

Round ID: 81696

**Comment by Kromgar** [comment]
They both spit out money its the same thing amirite

**Comment by Archemagus** [comment]
I think that better to change Vendors icon too, becouse Booze-o-Mat looks like chem\xeno storages. Just same size. U can use meal vendor or drinks...
