### ISSUE TITLE
Bolting lockers to a floor makes you hit them with a wrench

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#34281]
![image](https://user-images.githubusercontent.com/12382984/34795547-94b7bbf0-f64a-11e7-882a-f672f6a155c2.png)

Round ID: 81705

**Comment by Ratvar** [comment]
screwing camera frame close to finish it hits it with screwdriver as well

**Comment by Cyberboss** [comment]
@Ratvar that's a seperate issue, open a new one
