### ISSUE TITLE
Starting menu remains after Server Hop!

### ISSUE THREAD

**Issue by kisiel090** [tgstation/tgstation#34284]
[Reproduction]: When the game is starting and you have your menu showing, use Server Hop! function in the OOC tab and switch to another server.

![image](https://user-images.githubusercontent.com/35222553/34799177-28ed4ba0-f65f-11e7-99e5-3dd2e55ae800.png)

**Comment by ShizCalev** [comment]
Have a feeling this more a BYOND issue.

**Comment by Mooshimi** [comment]
Can't reproduce at this time. Either fixed by newer byond versions or by a pr that was merged. Reopen if this is reported again.
