### ISSUE TITLE
Pumps dump into unconnected connectors infinitely

### ISSUE THREAD

**Issue by DaedalusGame** [tgstation/tgstation#34299]
(unrelated to cryptocurrencies)

Pumps have an output pressure check that should prevent this, but some oddity (possibly related to #18354) is causing connectors directly connected to pumps to make the overall volume of pipenet 0 despite the output of the pump having a volume of 200. 0 volume means 0 pressure always, so pumps can continue pushing gas from the input to the output.

You can reproduce this by hooking any gasline up to a connector with a volume pump directly adjacent and leading into the connector. The connector will accumulate more and more gas, and when a canister is attached, it will instantly jump to several million kPa worth of pressure.

**Comment by cyclowns** [comment]
can't reproduce this on a private server

**Comment by DaedalusGame** [comment]
Actually yeah that's weird, I last had this issue before new years and there's no relevant changes to the files but it's gone. Volume Pumps do only push to their output air, not the pipenet, and I doubly checked the filters aswell. I guess that's what I get for reporting issues from memory.
