### ISSUE TITLE
The round says it has ended before it actually ends

### ISSUE THREAD

**Issue by imtakingabreakdontatme** [tgstation/tgstation#34300]
https://i.imgur.com/1JXGX1f.png

So what I think happened here was

"Round has ended" message

Bomb/lag

I die

The round end report finally pops up a few seconds later

I'm listed as dead when the report generates

The delay between docking/ROUND HAS ENDED/round report generation is not good considering our server culture is to immediately self destruct when we see ROUND HAS ENDED

**Comment by optimumtact** [comment]
I dont' see the problem here

**Comment by KorPhaeron** [comment]
I died after the round ended, but I showed as dead in the report

**Comment by AnturK** [comment]
I can try to alleviate the worst parts but it's either that or freeze on roundend. Choose one.

**Comment by Cyberboss** [comment]
Maybe we can use speculative execution to predict the round end conditions :)

**Comment by SpaceManiac** [comment]
There's also several rounds where post-round highlander made it into the antag stats.

**Comment by coiax** [comment]
There's also different definitions of "ended".

Why not just display the "ROUND HAS ENDED" messages at the end of the round ending process, rather than at the start?

**Comment by optimumtact** [comment]
someone just needs to split the sealing of the blackbox and user objectives away from the display of those objectives

one is faster

**Comment by KorPhaeron** [comment]
@AnturK I'd go with freeze at round end at this point

**Comment by Cyberboss** [comment]
I can think of like, 3 better ideas you memes

**Comment by optimumtact** [comment]
freezing lol classic

**Comment by TheBonded** [comment]
this seems to be an accepted thing now and generally eorg doesn't start until the roundend report appears.
