### ISSUE TITLE
Sleepers in Reebe don't work

### ISSUE THREAD

**Issue by Chocodaemon** [tgstation/tgstation#34304]
[Round ID]: # 81721

The sleepers in Reebe outright do not work. The UI will show the person's status for a second and then revert to as if the sleeper was empty. Wasn't able to get feedback on where the occupant goes.

**Comment by Potato-Masher** [comment]
They appear to be moved to the Ark as if they just returned to Reebe. Works on living and dead humans, as well as putting yourself in it.
