### ISSUE TITLE
Magnitis stuck on stage 1 and creating random culture bottles.

### ISSUE THREAD

**Issue by Jord1081** [tgstation/tgstation#34311]
Round ID: 81729
Server: Bagil
Revision: be8ddad1c3444b7308fe9be7ccb2900949db9139

Magnitis would not change from stage 1, either progressing or getting cured. Other viruses such as the flu changed stages and could be cured.

In addition, a blood sample in the PANDEMIC correctly displayed Magnitis, but a culture bottle created from it appeared to be random with only one symptom, including a virus with "Basic Healing (does nothing)", with the description "You should not be seeing this". Again, other viruses created correct culture bottles.

**Comment by kriskog** [comment]
This is fixed
