### ISSUE TITLE
Mining base walls break to lava when deconstructed

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#34321]
Goliath punched wall, walls turned to lava.

**Comment by Kromgar** [comment]
#33984

**Comment by KorPhaeron** [comment]
Not a dupe, these are regular walls, not shuttle walls

**Comment by PsyCommando** [comment]
Bluspace shelters also have that issue!  I had a goliath track me through a layer of rock + the shelter's wall, and it broke through it all and when it tore down the walls, they turned to lava..

**Comment by ninjanomnom** [comment]
Bluespace shelters would be something else, probably it's doing ChangeTurf instead of the proper PlaceOnTop for a new construction
