### ISSUE TITLE
experimentor is broken (maybe?)

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#34320]
it doesnt trigger ANY irradiate prob() except global malfunctions and fail messages
the discover thing works fine
it once triggered the ++coef on manipulation mode
it didnt do any irradiate probs in over 500 rolls

**Comment by GunHog** [comment]
Did you use different items? Items of a certain type respond only to one experiment type. Try them all until you get a different result. If you ONLY want to use a single experiment type, such as "Irradiate", then you must try different items until you find a type that responds to the "Irradiate" experiment type.

**Comment by kriskog** [comment]
No reproduction steps, and old.
