### ISSUE TITLE
Pet collars no longer rename pets when used on them.

### ISSUE THREAD

**Issue by The-clown-known-as-Pepe** [tgstation/tgstation#34348]
basically the title

**Comment by DaxDupont** [comment]
Unique pets can no longer be renames for some dumb reason

**Comment by ShizCalev** [comment]
#34177, intentional. You can't rename Ian, but you can rename a generic Corgi ordered through Cargo.

**Comment by ShizCalev** [comment]
Also you can't currently rename Corgis because of a bug with #33156. #34184 fixes said bug.
