### ISSUE TITLE
Gas filter fitting produced by pipe dispenser cannot be flipped

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#34345]
The "Flip Pipe" verb only rotates it 180 degrees and does not flip it. It is still an `/obj/item/pipe` and the flip handling code is under `/obj/item/pipe/trinary/flippable`.

5b9eeb8935743622b6211c76c31e392e908c18f7

**Comment by ShizCalev** [comment]
@duncathan
