### ISSUE TITLE
RPD painting is underpowered

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#34356]
Cannot produce some colors of pipes:
* [x] Gray (aka general)
* [x] Red
* [x] Blue (aka supply)
* [x] Cyan
* [x] Green
* [x] Yellow
* [x] Purple
* [x] Amethyst (aka supplymain)
* [x] Orange
* [x] Violet
* [x] Brown
* [x] Dark

It doesn't work at all the right times:

* [ ] Pipe items (unwrenched) cannot be painted.
* [ ] Non-pipe components can be placed colored but not repainted afterwards, resulting in stuff like unfixable double-purple:

![image](https://user-images.githubusercontent.com/222630/34878206-3aff57b6-f75e-11e7-95ab-7415a8a9ba7e.png)

**Comment by WJohn** [comment]
Huh, didn't know about the double painting thing.
