### ISSUE TITLE
xenomorph inventory uses old UI or something

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#34369]
So I had cuffed this xenomorph while preforming an arrest (as you do), and later on when I went to remove her cuffs via dragging her sprite to mine, her inventory looked like it used some older outdated UI rather than the one we see when viewing other humans inventories. Still worked fine but was kinda strange.

**Comment by Kromgar** [comment]
Wjohn tags it of course.

But uh how did you cuff a xenomorph

**Comment by dragomagol** [comment]
Closed (properly) by #57889
