### ISSUE TITLE
paint job is wrong on doors

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#34375]
![image](https://user-images.githubusercontent.com/222630/50668806-577edc00-0f76-11e9-9711-3b1cf24f17ba.png)

one of these was made with the rcd the other was already there

**Comment by YPOQ** [comment]
The darker purple is the one in research.dmi and the other is science.dmi
Both are available in the rcd/airlock painter but we could honestly just remove one since they're so redudant.

**Comment by WJohn** [comment]
not a bug, it's just the brighter purple science one is a redundant type that should be removed.
