### ISSUE TITLE
Pouring/injecting reagents into a container doesn't transfer fingerprints

### ISSUE THREAD

**Issue by YPOQ** [tgstation/tgstation#34370]
Local server e2edd

1. Get a beaker of water and beaker of potassium
2. Find an empty beaker that you have not touched (print one at an autolathe)
3. Pour both full beakers into the empty one without picking the empty one up
4. Explosion but admin message lists null fingerprints (or someone innocent)

Arguably we only need to set the hidden fingerprints for this, since admin tools and certain reactions (slime time stop) rely on it.

**Comment by ShizCalev** [comment]
@kevinz000

**Comment by arsserpentarium** [comment]
If you'll try this IRL, you aren't gonna find any fingerprints
