### ISSUE TITLE
Changelings are sometimes given no changeling datum.

### ISSUE THREAD

**Issue by Giacom** [tgstation/tgstation#3438]
It was traitorling and I received an adminhelp about someone receiving changeling objectives but not having changeling chat or powers. When I investigated their variables, their mind datum showed their changeling datum was null. @Hornygranny confirmed that he had run into this issue before. I later re-changeling'd the guy to give him his changeling powers.

**Comment by Dorsisdwarf** [comment]
Anyone know if this happens still? I remember roundstart code and antags in general have been jimmied since 2014

**Comment by lzimann** [comment]
This got fixed 2 years later in #21026
