### ISSUE TITLE
Reinforcing glass leaves invisible stack with amount 0

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#34397]
Hold two or more glass in one hand, rods in the other, and insert rods until the stack is exhausted. Your empty hand now contains a stack of reinforced glass of amount 0. It is qdel'd (has `gc_destroyed` set) but remains in your hand and can be examined to reveal its amount of 0 and activated to open the crafting menu.

@JohnGinnane maybe?

b413546bc0711faa0400af278236c9911c3d758c

**Comment by JohnGinnane** [comment]
Gonna test this but I put up pr to fix: #34396

**Comment by JohnGinnane** [comment]
Still broke, gonna fix
