### ISSUE TITLE
Removing your mask does not remove the green color from the internals action button

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#34390]
Round ID: 81835

The one in the top-left, with the tank icon, that is. Wasn't paying attention to the one on the right side. It stays green until you click it twice, the first time to re-enable it for real (where it stays green) and the second time to disable it.

**Comment by nicbn** [comment]
Couldn't reproduce it locally

**Comment by ShizCalev** [comment]
Unable to repo

**Comment by SpaceManiac** [comment]
Reproduced reliably. Place the emergency oxygen tank from the internals box in a pocket and equip a **gas mask** (problem does not occur with breath mask). Enable internals. When the gas mask is removed, the right-side internals button updates, but the tank's action button does not. No runtimes.

**Comment by kriskog** [comment]
Still an issue

**Comment by SweptWasTaken** [comment]
Still an issue

**Comment by TheBonded** [comment]
how is this *still* an issue
