### ISSUE TITLE
Sand tiles on Omegastation spawn metal rods when under singularity's pull

### ISSUE THREAD

**Issue by kisiel090** [tgstation/tgstation#34404]
[Round ID]: 81851

[Reproduction]: spawn a singularity on Omegastation, observe asteroid sand.

![image](https://user-images.githubusercontent.com/35222553/34908955-2b2ade3c-f899-11e7-8769-0f08075adaf5.png)

**Comment by WJohn** [comment]
the sand just has very high iron concentrations and is being spaghettified by the singulo. duh!

**Comment by kriskog** [comment]
Omega is gone
