### ISSUE TITLE
Putting an MMI into amech rendered it unable to move/do anything

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation#34408]
[Round ID]: 81864, Sybil

all it got was a message stating that it tried to move out and then duplicated MMI's

**Comment by SpaceManiac** [comment]
Reproduced locally, this must have broken in the last week or two because it was fine when I was testing #34349.

**Comment by factoryman942** [comment]
i don't think it's duping the mmi, because when i tried to do it when the mmi moved i could climb into the mech as robo
