### ISSUE TITLE
Machines that produce items are vending the items below the machine

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#34405]
EX: Protolathe, Mining Redemption machine

**Comment by praisenarsie** [comment]
happens to me too

**Comment by DaedalusGame** [comment]
Not limited to just machines that produce items really, chem heaters also eject the beaker underneath them

**Comment by Kromgar** [comment]
The latest 512 update seems to be the cause holy fuck 512 is buggy as fuuuuuck.

I beleive this is a byond issue because i reverted to 511 and no longer have this issue

@AnturK

**Comment by AnturK** [comment]
512 changed ordering within same layer. Usually it doesn't matter but we used that to keep things like this working. This is pretty trivial fix.

**Comment by Kromgar** [comment]
Just went back to 512 This shit IS STILL HAPPENING

**Comment by Kromgar** [comment]
Just went back to 512 This shit is still ongoing @AnturK
