### ISSUE TITLE
Interactive humans can open windoors they don't have access to

### ISSUE THREAD

**Issue by nicbn** [tgstation/tgstation#34403]
Maybe related to #7041

**Comment by WJohn** [comment]
the solution is to remove interactive humans.

we don't use them for literally anything and they haven't been touched in years.

**Comment by ShizCalev** [comment]
also see #7041

**Comment by vuonojenmustaturska** [comment]
@WJohn not strictly true, they are used by abductors and away missions, also maybe one of @XDTM 's brain traumas?

**Comment by XDTM** [comment]
They aren't in trauma, and you wrote that comment right while i was removing the abductor one
