### ISSUE TITLE
F2 and Shift+F2 act the same

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#34412]
F2 is supposed to be "Quick Screenshot", which works when you select it in the "File" menu, but pressing F2 brings up the save-file prompt same as Shift+F2 does.

@ninjanomnom

b413546bc0711faa0400af278236c9911c3d758c

**Comment by ninjanomnom** [comment]
It actually *was* working to take quick screenshots but it was also asking to take a second. I'll have a fix up for this in a bit.
