### ISSUE TITLE
Attack sprites popping up randomly + crash

### ISSUE THREAD

**Issue by ishitbyabullet** [tgstation/tgstation#34419]
Issue reported from Round ID: 81876 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

[Reproduction]: I updated to the latest beta build, 512.1403, and saw attack sprites such as cleaving saws and baseball bats start hitting disposal pipes that weren't covered by floortiles. After ghost data/med/sec huds acting strange aswell, I crashed in only 1-3 minutes.

**Comment by ShizCalev** [comment]
Have you cleared your cache by chance?

**Comment by ShizCalev** [comment]
Will close in a week without a repro
