### ISSUE TITLE
Invisible Gas

### ISSUE THREAD

**Issue by jcll** [tgstation/tgstation#34420]
[Round ID]: # 81879
[Round ID]: # 81881 As well

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # Invisible Gasses. Looked at the Plasma and N2O holding tanks in atmos. As well as test opening a N20 tank in a empty room. 

https://i.imgur.com/OFsqCQK.png

Bagil is on 512 now?

**Comment by AnturK** [comment]
Yes, this is unfortunately correct if you're using 511 client on 512 server.
