### ISSUE TITLE
space food is gross

### ISSUE THREAD

**Issue by Catistian** [tgstation/tgstation#34422]
...title. any time you eat anything (except some vending machine foods) you get "that didn't taste very good..." and a grossed out moodlet. It kind of defeats the purpose of a chef if nothing they can make tastes good

**Comment by Catistian** [comment]
Its almost every single dish, but I've tested it with banana nut bread, meat bread, cutlets/steaks, burgers, cheesecake. And its as a lizardperson (If that matters, I guess. Are there different tastes for different species?)

**Comment by Armhulen** [comment]
yep, different species like different things. you can close this with a button next to comment
