### ISSUE TITLE
sm engine maxcap delam in ~5 seconds on normal setup

### ISSUE THREAD

**Issue by Deitus** [tgstation/tgstation#34421]
[Round ID]: # 81878
[Testmerges]: # dunno

[Reproduction]: i was doing the sm engine with some other engie and as far as i could tell everything was normal in terms of piping and gasses (i double checked because i didnt trust him), turned on the emitters and engine started spazzing out with electricity and shit before maxcap delamming in around five seconds. even with sabotage (which very well could have happened before i got there) ive never seen it go so fast. could be just a one time thing but it seems significant enough to post here i suppose.

**Comment by kisiel090** [comment]
Well, i had power discharges and anomalies in 5 sec after turning emmiters on. But i still had a lot of time to turn on pumps  in the airlock between SM and engineering, which i forgot. Died shortly after because of anomalies...

**Comment by AverageJoe82** [comment]
Did you analyze what was in the pipe? It coulda been the AI removing the N2 or pumping in CO2.

**Comment by Robustin** [comment]
I had this happen last month as well, and I'm very confident with my setups. It was on Delta and within seconds of activating it was spewing anomalies and exploded in a matter of moments.
