### ISSUE TITLE
removing and putting tiles back in the chapel broke something

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#34435]
Issue reported from Round ID: 81898 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

![image](https://user-images.githubusercontent.com/6209658/34947073-0264d842-f9d7-11e7-92e8-a713145a428b.png)

**Comment by JJRcop** [comment]
In the future, could you upload images to github by pasting them in the comment section?
![](https://user-images.githubusercontent.com/5211576/34929090-c60a1926-f98f-11e7-9c46-d930a4c123aa.png)

**Comment by ShizCalev** [comment]
![image](https://user-images.githubusercontent.com/6209658/34950073-08abd88c-f9e0-11e7-9541-a2127494002a.png)
Something's wrong with the carpet's icon in general, it's supposed to be a different icon. When replacing the floor with a normal plasteel tile, you get 
![image](https://user-images.githubusercontent.com/6209658/34950089-2301b512-f9e0-11e7-9276-306f5661b952.png)
