### ISSUE TITLE
code blue sometimes happens at 12:00

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#34433]
Issue reported from Round ID: 81898 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

not sure if a feature

**Comment by JJRcop** [comment]
Could you provide more details? Is this the code blue announcement showing to players in the lobby before the game starts? is it showing immediately, before map load?

**Comment by Tlaltecuhtli** [comment]
like at round start

**Comment by SpaceManiac** [comment]
Wild guess that this has something to do with game start taking more than 1 minute (which is supposed to be the minimum timer on code blue).

**Comment by kriskog** [comment]
No reproduction steps, very old, havent seen it happen.
