### ISSUE TITLE
Gorilla movement.

### ISSUE THREAD

**Issue by kustridaren** [tgstation/tgstation#34437]
well was turned into a gorilla was put on a operating table and could not move. or it could be because i was draged.

Round ID 81900

**Comment by Hatfish** [comment]
this happens with any mob, not just gorillas.  I experienced the same bug as a human a few days ago.

**Comment by deathride58** [comment]
Did you try using the "rest" verb?

**Comment by kustridaren** [comment]
yeah I did try to use the rest verb to lay down on the operating table but nothing happend
