### ISSUE TITLE
Survival pods aren't entirely safe from ash storms

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#34436]
![image](https://user-images.githubusercontent.com/6778786/34917045-40a567fc-f90f-11e7-9324-33628091eef7.png)

**Comment by Tlaltecuhtli** [comment]
seems more a visual bug because of smoke were the tiles actually damaging?

**Comment by Kromgar** [comment]
@Tlaltecuhtli never tried but i did it during an ash storm so maybe it was a visual bug

**Comment by Buggy123** [comment]
I can confirm, this has happened to me before and the tiles are not damaging. It is purely visual.
