### ISSUE TITLE
You can wrap something as many times as you like.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#34443]
This includes the nuclear disk. Hundreds of times. Makes it basically impossible to unwrap and use. Funny, but now everyone's gonna do this because they saw an op unwrap it for 5 minutes straight.

nuclear authentication disk, in a tiny parcel in a lightly-fried tiny parcel in a tiny parcel in a lightly-fried tiny parcel in a tiny parcel in a lightly-fried tiny parcel in a tiny parcel in a lightly-fried tiny parcel in a tiny parcel in a lightly-fried tiny parcel in a tiny parcel in a lightly-fried tiny parcel in a tiny parcel in a lightly-fried tiny parcel in a tiny parcel in a lightly-fried tiny parcel in a tiny parcel in a lightly-fried tiny parcel in a tiny parcel in a lightly-fried tiny parcel in a tiny parcel in a lightly-fried tiny parcel in a tiny parcel in a lightly-fried tiny parcel in a tiny parcel in a lightly-fried tiny parcel in a tiny parcel in a lightly-fried tiny parcel in a tiny parcel in a lightly-fried tiny parcel in a tiny parcel in a lightly-fried tiny parcel in a tiny parcel in a lightly-fried tiny parcel in a tiny parcel in a lightly-fried tiny par

**Comment by KomradeSpectre** [comment]
Not a bug, intended feature.

**Comment by DaedalusGame** [comment]
intended feature
