### ISSUE TITLE
Select equipment cancel button will confirm anyway.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#34444]
This caused a rather embarassing disk loss when I accidentally brought up select equipment when intending to view variables (it's positioned right beneath it), and then cancelling it CONFIRMED it anyway, leaving the op naked and the disk respawned elsewhere.

**Comment by SpaceManiac** [comment]
Can't reproduce locally. Round ID?

**Comment by BeeSting12** [comment]
nice quads

**Comment by ExcessiveUseOfCobblestone** [comment]
4444, Quad-Squared

**Comment by WJohn** [comment]
i can reproduce this 100% of the time on bagil, as can all other admins.

**Comment by SpaceManiac** [comment]
Reproduced, broken by #34155 @deathride58
