### ISSUE TITLE
Shotguns have to be pumped once before firing for the first time

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#34456]
A riot shotgun, fresh out of the armory, has to be pumped once before it can be fired. This has gotten me killed several times. Wouldn't you expect them to be ready to fire right out of the box?

Round ID: irrelevant, this issue is consistent and reproducable.

**Comment by GunHog** [comment]
Actually, no. Basic gun safety (ignoring the lack of actual safeties on weapons) would demand that you *not* have rounds already chambered.

**Comment by DaxDupont** [comment]
This is so not a bug.
If you don't cock your shotgun you're an absolute idiot, even Hollywood movie get this right.

**Comment by Buggy123** [comment]
I mean, I _get_ that, but none of the _other_ guns have safeties on, or even safeties at all.

**Comment by DaxDupont** [comment]
Just stop complaining about gameplay features because you're too lazy/unrobust to check the shotgun

**Comment by Anonmare** [comment]
Just get in the habit of pumping a shotgun when you get it and just reload any ejected shells that fall out if it's already been pumped.

**Comment by DaxDupont** [comment]
You can also examine shotguns to see if it has one in the chamber.

**Comment by Buggy123** [comment]
Fair enough, I _am_ unrobust.

**Comment by optimumtact** [comment]
specifically not a bug, but someone could float a rebalance and see how it was
