### ISSUE TITLE
"You cannot scream while unconscious"

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#34451]
This wasn't actually fixed
![image](https://user-images.githubusercontent.com/16315400/34921771-684f136c-f954-11e7-870d-724ccdee5e70.png)
Roundid 81924

**Comment by awesine** [comment]
you can do the moth scream noise while unconscious

**Comment by FantasticFwoosh** [comment]
Why should it be fixed, you're unconscious. I can't say i really understand.

**Comment by Buggy123** [comment]
I didn't try to *scream or anything, It tried to do a involuntary scream and it failed because I was unconscious and gave that message.

**Comment by MrROBUST** [comment]
@FantasticFwoosh This happens every time when you have become unconscious, with some emotion forcing (explosion with dismemberment and scream, sleep with snore, etc). It spams "You cant .. while unconscious" even when you are not try to do anything.

**Comment by Potato-Masher** [comment]
Uh, how is this a bug? The only issue I see is that its giving a manual scream fail for a involuntary scream fail. 

Personally I think this line is kinda funny as you lay on the floor unconscious with nobody making any move to help you.

**Comment by Buggy123** [comment]
It's not too big of a deal now, but it used to be worse:
"You cannot gasp while unconscious.
You cannot gasp while unconscious.
