### ISSUE TITLE
turf icon smoothing overriding carpetstar & carpetsymbol icons

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#34474]
![image](https://user-images.githubusercontent.com/6209658/34950073-08abd88c-f9e0-11e7-9541-a2127494002a.png)

Broken off from #34435

**Comment by xxalpha** [comment]
I am not sure this is a bug, by design icon smoothing doesn't let you have icons that deviate from the pattern. If you want a floor to look different you need to code it to not smooth.

**Comment by ShizCalev** [comment]
#58104
