### ISSUE TITLE
Monkey mode end of round summary repeats itself

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#34488]
![image](https://user-images.githubusercontent.com/609465/34961151-fa754644-fa35-11e7-978a-be8275e35e36.png)

This window only has a fraction, but that scrollbar is a hint to the number of times the message repeated.
This window scrolled a lot (I'd guess equal to the number of antagonist monkeys).

Round ID: 81983

**Comment by ShizCalev** [comment]
@AnturK

**Comment by AnturK** [comment]
Please stop mering mrty "fixes"

**Comment by Robustin** [comment]
Should've been fixed by #34709
