### ISSUE TITLE
Slime Management console didn't work.

### ISSUE THREAD

**Issue by JayIRay** [tgstation/tgstation#34495]
Issue reported from Round ID: 81991 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

[Round ID]: #81991 (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: #33166  (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.) The Slime Management Consoles didn't work. Clicking on them resulted in nothing happening. I walked through all the possible problems that could've caused it with Jerry Derpington and was told to report it here. The only odd thing that round that may have caused it was that I was cloned.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by SpaceManiac** [comment]
Couldn't reproduce locally and there weren't any obvious runtimes in that round's logs.

**Comment by Kaptinalexander** [comment]
It happened after the server updated to the changes on the 21st. because Sybil was updated on the 21st, but Bagil wasn't. Xenobio consoles wouldn't work, along with some other consoles, and bags in general can't pick things up, like the plant bag for botany, and the slime bag for xenobio.

Everything worked fine on Bagil though, until it updated probably. I had the same problem.
