### ISSUE TITLE
doors are unhackable

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#34496]
bagil. round ID 81991
#33166 is the only thing testmerged, dunno if it's the one causing it but eh
the interface for door wires isn't opening at all, and its impossible to open doors via clicking on them (unless you're hitting it with an ID card)

known bug, no issue on git for it yet, multiple people have experienced it across multiple rounds though

**Comment by kevinz000** [comment]
it was.

**Comment by kevinz000** [comment]
also it was testmerged for a single round.

**Comment by imsxz** [comment]
it's been testmerged for a few rounds now

**Comment by Cyberboss** [comment]
Its the testmerge
