### ISSUE TITLE
Stacked turfs cause weird issues with icon_states

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#34518]
![image](https://user-images.githubusercontent.com/9276171/35004920-ba58c8d0-fabf-11e7-8753-3acf09ee4c8b.png)

In cases where two turfs end up stacked on each other (the top turf has to has some transparency ) with an object, icon_states get all fucked up and do some weird stuff for everything in that turf's square.

The turf changes color if an item in that spot has a custom color set to it, items with directional sprites get duplicates if they aren't the default direction, and all items in that turf get an icon of the accumulative of everything on that turf at map load. 

The issue is a lot more rare now since turf visuals like caution lines are effects and the issue can be avoided entirely by making sure there aren't any stacked turfs, but the underlining issue has been around for awhile.

**Comment by ShizCalev** [comment]
Stacked turfs is no bueno since it causes issues with items on top of it, runtimes with icon smoothing, ect.  #20259 #26476 #25124 for a couple examples.

**Comment by AnturK** [comment]
We're not supporting multiple turfs on maps.
