### ISSUE TITLE
Luminescent: Cryoxadone/Tricord interaction

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#34517]
@XDTM 

When Luminescents use their major purple slime ability, they get dosed with 10u Tricordrazine.
Since toxin damage is reversed for slimepeople, they end up taking tox damage instead of healing it.

Similar issue with minor dark blue ability: The 5u cryoxadone end up causing tox damage. On top of that, the 5u frost oil metabolizes more slowly than the cryoxadone, which means you end up having ~1u left over in your system once the cryoxadone is gone.

**Comment by XDTM** [comment]
Fuck i forgot to change the chem for purples.
For cryoxadone i think i'll change it to universally heal toxins, though.
