### ISSUE TITLE
time stop still affects who makes the reaction

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#34525]
Issue reported from Round ID: 82045 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

**Comment by Tlaltecuhtli** [comment]
with slimes

**Comment by Tlaltecuhtli** [comment]
if mixed in a bag

**Comment by YPOQ** [comment]
We will probably need to fix #34370 to fix this.

**Comment by Repukan** [comment]
Isn't that intended?

You're not producing the time stop like a wizard. Merely making the reaction happen

**Comment by XDTM** [comment]
The code is set to make the last one to touch the extract immune so it's a bug, making them nonimmune would be a balance change if you want to do it

**Comment by kriskog** [comment]
This has been reworked
