### ISSUE TITLE
monkey mode should stay as a monkey mode 

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#34535]
round id 82072
https://api.monosnap.com/rpc/file/download?id=PArheJFa9QeRNqB7DticgMb7RsrOch

monkeys shouldnt be able to use guns, monkeys with guns is just revs 2 where the revs are browns instead of greys
also only monkey leader should be able to use the monkey chat

**Comment by PKPenguin321** [comment]
Take it to the forums feedback section
