### ISSUE TITLE
Health scanners displaying cat people as human.

### ISSUE THREAD

**Issue by LameFlame** [tgstation/tgstation#34536]
Issue reported from  Round ID: 82075 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG]

Small issue after being informed that cat people where not human I checked with a health scanner to see it showed up as human.

**Comment by DaxDupont** [comment]
They are human but they aren't. 
Same how hulks are still humans but they don't count as human to the AI.

**Comment by ShizCalev** [comment]
It's because catpeople aren't a subtype of `/datum/species`, but instead just a human with ears and tail organs added on.

**Comment by LameFlame** [comment]
character select also made it seem like the cat ears and tail where just an cosmetic appearance changer but when an admin informed me that doing so makes you a cat person causing you to be seen as non human by the ai with no racial advantages what so ever only removing one "AI Protection under the default Asimov lawset" I was compelled to undo it in character select even though I liked it just for the ears.

**Comment by FantasticFwoosh** [comment]
As a AI it is difficult to distinguish a human from a catperson with concealing pieces of clothing without cross reference of records or sending out a borg to remove the clothing for visual feedback. Hence this creates issues in silicon and crew interaction and is significantly easier than other non-humans taking measures to be inconspicuous and vague with appearance.

- Its the least detrimented form of non-humanity amongst the crew.
