### ISSUE TITLE
Adminrazine kills TOXINLOVING species

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#34539]
Round ID: 82082

@XDTM 

A Race Swap event made a bunch of people slimepeople, and then Invincibility gave people Adminrazine, which heals toxic damage, resulting in about 10 people all dying simultaneously.

Given that Adminrazine is supposed to be GODMODE THE CHEMICAL, this is probably an unintentional bug.

**Comment by XDTM** [comment]
It is, i'll include the fix in my last pr
