### ISSUE TITLE
simple mob wander is broken.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#34543]
![](https://i.imgur.com/ckH799h.png)
![](https://i.imgur.com/nSG55f7.png)

They've been like this for over 10 minutes, they have wander = 1, they do not wander.

**Comment by Cyberboss** [comment]
@vuonojenmustaturska

**Comment by Cyberboss** [comment]
This is probably a side effect of the optimizations he did, was any living player on the z level?

**Comment by WJohn** [comment]
No, and the second I spawned myself on, they started to wander. Once I died, they stopped. This is intended, then?

**Comment by vuonojenmustaturska** [comment]
This is completely intended as per #33574 which completely stopped running mob AI on empty Z-levels (empty as in do not contain any players that the mob could reasonably interact with)
