### ISSUE TITLE
Xenos can use acid to melt reinforced floors

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#34559]
![image](https://user-images.githubusercontent.com/6778786/35076319-c84eb5ba-fbc5-11e7-8459-f1bde3e7ee58.png)

**Comment by YPOQ** [comment]
That tile is actually plating at roundstart, even though the one to the right is reinforced flooring.

**Comment by Kromgar** [comment]
He actually melted the reifnorced flooring too

**Comment by WJohn** [comment]
Hm, it's definitely plating under there, but I'll do testing on reinforced flooring.

**Comment by WJohn** [comment]
Hah, whoops. I completely forgot about this issue! Anyway, I can't replicate this on reinforced floors, but there IS plating underneath the windows there, so that would explain it. Easy fix.
