### ISSUE TITLE
Bag of money instantly collapses in on itself

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#34568]
roundid: 81126
![image](https://user-images.githubusercontent.com/16315400/35082719-62a4a0d4-fbe9-11e7-9d0f-217fe9edc079.png)
Delay between winning and the collapse was less than one second.

**Comment by YPOQ** [comment]
The code looks pretty clean so maybe there's some bug with timers? See #34433

**Comment by YPOQ** [comment]
This should be max(), right?
https://github.com/MrStonedOne/tgstation/blob/603dc1fd1ba9a832aa99e7f9da760018ab9da2ec/code/controllers/subsystem/timer.dm#L319

**Comment by Buggy123** [comment]
Very strange, but the _next_ time i got a bag it didn't collapse immediately. Really weird.

If it helps anything, at the time i was rapidly clicking on the tile and probably clicked on the bag a few times. Nonetheless, no dice came out and the bag didn't just end up in my hand or bag or on the ground or anything, I checked thoroughly.

**Comment by SpaceManiac** [comment]
How long into the round did this take place? The round ID you posted seems to be wrong so I can't check.

**Comment by Buggy123** [comment]
Uh... fuck, I honestly don't remember.

**Comment by Buggy123** [comment]
It happened again

![image](https://user-images.githubusercontent.com/16315400/35894703-18069fe8-0b82-11e8-803f-c4a5c57502ab.png)
roundid: 83198, station time: 12:19:30 ish

**Comment by Ordonis** [comment]
Okay, I think I've figured this out. As long as this is based on any kind of modulo or quotient of the round ID, there's a chance it'll be either. I'd need to find what SHORT_REAL_LIMIT is, but if you ever get anything where that's fractional or close to zero, the timer will then choose between either 1 or some incredibly small value, possibly zero, meaning that the bag collapses almost instantly.

**Comment by kriskog** [comment]
Has to be a timer issue, but doesnt seem to have happened in a while. Closing
