### ISSUE TITLE
Smashing Bluespace pod walls opens lavaland floor to lava

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#34586]
Issue reported from  Round ID: 82143 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

This needs to stop.

![dreamseeker_2018-01-18_12-51-17](https://user-images.githubusercontent.com/33107541/35113101-5a5f15ca-fc4e-11e7-825f-c9aba09b9dbf.png)

**Comment by Bawhoppen** [comment]
It's because people messed with the baseturfs system. @coiax I think

**Comment by Bawhoppen** [comment]
Sorry maybe it wasn't coiax. There's been several PRs related to things like this lately though.

**Comment by Kromgar** [comment]
There's been several bug reports that baseturfs are all fucked

**Comment by ninjanomnom** [comment]
will be fixed with the same changes as #33984

**Comment by ninjanomnom** [comment]
actualy I may be able to fix it early, one moment
