### ISSUE TITLE
Deleted Space Pods don't delete, they just get moved.

### ISSUE THREAD

**Issue by Mey-Ha-Zah** [tgstation/tgstation#34593]
[Round ID]: # 82149

[Reproduction]: Blow up a space pods and it will end up in a new location, in exactly the same state. I blew one up in thunderdome and it showed up in atmospherics much to the confusion of Techs.

**Comment by praisenarsie** [comment]
@MoreRobustThanYou this is like a super old issue with spacepods and you still haven't fixed it.

**Comment by MoreRobustThanYou** [comment]
Should be fixed now.

**Comment by MoreRobustThanYou** [comment]
well, not now, whenever someone can re-testmerge
