### ISSUE TITLE
Shipping manifest disappeared when opening crate.

### ISSUE THREAD

**Issue by mkl-0** [tgstation/tgstation#34592]
Round ID: 82139

I didn't really do anything out of the norm, ordered the usual metal sheets, glass sheets and insul gloves. First I opened the glass sheets crate, then the metal sheets crate, which didn't give me the manifest. I have a longer footage on youtube if needed.

https://youtu.be/tpZaROanqIY

![qualitygame.gif](https://i.imgur.com/gJWBWXQ.gif)

**Comment by ShizCalev** [comment]
That's strange, so going off your chat it would seem that the manifest didn't generate properly or something.

**Comment by JohnFulpWillard** [comment]
Is this still happening? I assume it was something to do with ``MANIFEST_ERROR_CONTENTS``, but it seems to be patched now
