### ISSUE TITLE
Clock cult is unbelievably obnoxious to observers.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#34607]
It plays an absolutely ridiculous amount of sounds to ghosts. Imagine the pop up BOOP sound every time a blood cultist spams a soul shard, now have this play fucking endlessly with nearly every conceivable action, reaction, and progression for the entire duration of the game mode. The eminence made this problem even worse.

Oh, and when the ark activates? That's when it reaches a whole new level of annoying. At least give us an option to mute it.

**Comment by DaxDupont** [comment]
@Xhuis

**Comment by Potato-Masher** [comment]
>eminence begins spamming orders to get a marauder to do something

The Eminence has ordered an offensive rally at the R&D Server to the south east! x27

BWEENBWEENBWEENBWEENBWEENBWEEN

**Comment by Xhuis** [comment]
This tells me absolutely nothing. Why not list some of the actions instead of screaming about them?

**Comment by WJohn** [comment]
Seemingly every action the eminence takes plays a sound, declaring war, every time a follower is converted successfully, every time a new scripture is unlocked, the ENTIRETY of the ark, its activation, taking damage, its multiple states where it plays sounds for everyone, fuck, what DOESN'T play a sound to ghosts?

**Comment by Xhuis** [comment]
I made CC a very sound-heavy mode on purpose. In my eyes, it makes it more immersive and I've always felt that the Ark is very atmospheric. A mute button would be snowflakey and I'm not sure it's doable, but reducing the volume would be easy.

**Comment by Kromgar** [comment]
The ark noises are so fucking annoying. Clocks arent supposed to be obnoxiously loud just ticking as background noise instead. Seriously the ark is way too loud for how long it runs

**Comment by ExcessiveUseOfCobblestone** [comment]
Why not add an arg for playsound that doesn't play for ghosts?

I can't imagine anyone wanting to hear nearly every sound cc makes as they're observing.
