### ISSUE TITLE
You can get infinite materials by welding mineral doors

### ISSUE THREAD

**Issue by Repukan** [tgstation/tgstation#34615]
Reported by Anonmare

This goes to a special someone

Fuck♂

**Comment by uraniummeltdown** [comment]
Mineral doors or mineral airlocks?

**Comment by Anonmare** [comment]
Airlocks.

I got infinite bannanium from the clown ship ruin

**Comment by Anonmare** [comment]
When you're following the deconstruction steps, after you crowbar out the electronics - Weld the mineral door and it'll produce a sheet of what it was made from but it doesn't actually remove the plating from the airlock.

**Comment by 81Denton** [comment]
Can confirm, you can get infinite titanium from the white shuttle airlocks.

**Comment by Potato-Masher** [comment]
>implying infinite Bananium is a bad thing

Honk!

**Comment by awesine** [comment]
Feature.

**Comment by arsserpentarium** [comment]
Feature
