### ISSUE TITLE
Suit Storage Unit locks don't need relevant access

### ISSUE THREAD

**Issue by Mark9013100** [tgstation/tgstation#34617]
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 82170

Server revision compiled on: 2018-01-18

The following pull requests are currently test merged:
#34236: 'Antag Panel / Check antagonists Refactor' by AnturK at commit c0973f
#34133: 'Temperature Refactor and Fixes' by Robustin at commit 24b06a
#34047: '[READY] Spacepods!' by MoreRobustThanYou at commit a03ad8

Based off origin/master commit: f43c94

Revision: 9f1bf2bb7bbcaf5e7a5d433a2480d89074a85de0

Server tools version: /tg/station 13 Server v3.2.1.11

Server tools API version: 3.2.0.2

See title, the various SSUs all around the station don't pay any attention to what access the person has, and can be freely locked and unlocked by anyone.

**Comment by RandomMarine** [comment]
The lock is for locking things _inside_

**Comment by ShizCalev** [comment]
Intended.

**Comment by ShizCalev** [comment]
The lock is there to keep you from getting burned when you initiate UV cleaning.
