### ISSUE TITLE
Updating to Byond 512 results in constant crashing while observing

### ISSUE THREAD

**Issue by ElfLeaderMike** [tgstation/tgstation#34618]
Round ID: 82170
Server revision compiled on: 2018-01-18

The following pull requests are currently test merged:
#34236: 'Antag Panel / Check antagonists Refactor' by AnturK at commit c0973f
#34133: 'Temperature Refactor and Fixes' by Robustin at commit 24b06a
#34047: '[READY] Spacepods!' by MoreRobustThanYou at commit a03ad8

Based off origin/master commit: f43c94
Revision: 9f1bf2bb7bbcaf5e7a5d433a2480d89074a85de0

Ever since I've updated to Byond 512 i've been crashing constantly. On 511 I never crashed while observing, now its as often as once every five minutes to half hour. Something that happens during observing doesnt agree with 512. For now I'm back to 511.

**Comment by ShizCalev** [comment]
likely related to #33000

**Comment by SpaceManiac** [comment]
Relevant [BYOND forum thread](http://www.byond.com/forum/?post=2337438). We can see if it gets fixed in 512.1404.

**Comment by Kromgar** [comment]
I got this shit so i had to downgrade back to 511 i couldn't use cuckwork computers at all or do xenobio without crashing constnatly. It didnt happen as much if i moved slowly
