### ISSUE TITLE
the circuit component: integrated hypoinjector doesnt suck out [integrated circuits]

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#34628]
82174 bagel
#34236: 'Antag Panel / Check antagonists Refactor' by AnturK at commit c0973f 
#34133: 'Temperature Refactor and Fixes' by Robustin at commit 24b06a 
#34047: '[READY] Spacepods!' by MoreRobustThanYou at commit a03ad8 
[Reproduction]: http://take.ms/CoNtn
it does inject with positivie values but it doesnt succ with negative values

**Comment by arsserpentarium** [comment]
I've tried to fix it.
I've found,that it can suck liquids only if there is at least on u of reagents inside injector. IDK where is ptoblem. If somebody will find out,I'd be grateful

**Comment by yorii** [comment]
I PR'ed a fix that I haven't tested at all, but I feel confident.
