### ISSUE TITLE
spacepods are op

### ISSUE THREAD

**Issue by LetterN** [tgstation/tgstation#34638]
Issue reported from  Round ID: 82186 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])
#34236: 'Antag Panel / Check antagonists Refactor' by AnturK at commit c0973f
#34133: 'Temperature Refactor and Fixes' by Robustin at commit 24b06a
#34047: '[READY] Spacepods!' by MoreRobustThanYou at commit a03ad8

[Pod issue]
You cant destroy a pod apparently, it goes boom one time then it breaks, Also you can still use the normal pod fuctions.

[Reproduction]:
1. make a spacepod
2. fly the spacepod arround
3. destroy the said pod
4. wait until it explodes
5. the pod will be there on 0 integrity, but you can still use the pod fuctions

![pod machine brke](https://user-images.githubusercontent.com/24603524/35153929-4de3fef8-fd63-11e7-9e71-909c94b529e0.PNG)
![pod mahine bwoke](https://user-images.githubusercontent.com/24603524/35153930-4e322862-fd63-11e7-8e3a-24c31832e80a.PNG)
![pods r us](https://user-images.githubusercontent.com/24603524/35154007-8c598e00-fd63-11e7-8d0f-83119882db7e.PNG)

[Pod construction issue]
 It does NOT use rods, cables and metal, also the welding part does not need any welding protection

[Reproduction]:
1. make a spacepod
2. see as it does not take any rods/metal and does not blind your eyes without welding protection

@MoreRobustThanYou fix your shit

**Comment by lzimann** [comment]
PR is not merged yet.

**Comment by LetterN** [comment]
yet™

**Comment by MoreRobustThanYou** [comment]
i think i fixed this, but the update hasn't been testmerged yet
