### ISSUE TITLE
no shuttle

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#34647]
Round ID: 82194
Testmerges: #34623 
[Reproduction]: 1. Call shuttle. 2. Wait shuttle. 3. No shuttle
It seems coders don't care AT ALL about TESTING THEIR FUCKING CODE

**Comment by ShizCalev** [comment]
@ninjanomnom

**Comment by ninjanomnom** [comment]
You seem to think tests can catch every issue, this is the testmerge.

**Comment by evsey9** [comment]
how can you not catch the shuttle literally not being there
