### ISSUE TITLE
Slimes won't eat monkies, monkeys die of mysterious burns

### ISSUE THREAD

**Issue by Kaptinalexander** [tgstation/tgstation#34663]
Issue reported from  Round ID: 82202 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

![image](https://user-images.githubusercontent.com/8625925/35172400-5d73c3e0-fd1c-11e7-9825-29d0c9e26930.png)

So yeah, monkeys will start taking burn damage after being put in the pens via slime management console.

How to reporduce: 
step 1 - put monkeys in pen via slime management console
step 2 - wait ten - twelve minutes

all the monkeys die of burn damage, and the slimes have not fed on them.

**Comment by Kaptinalexander** [comment]
Also xenobio is working fine on sybil as of round 82203, so it's prolly something to do with the recent updates as to where things borked.

**Comment by vuonojenmustaturska** [comment]
@AnturK #34133 ?
