### ISSUE TITLE
Xenobio + monkeys broken

### ISSUE THREAD

**Issue by ishitbyabullet** [tgstation/tgstation#34684]
Issue reported from  Round ID: 82228 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

[Round ID]: 82228

[Reproduction]: Slimes wouldn't eat monkeys, even if set to 50 nutrition, and monkeys were randomly dying from low burn damage over time. Nothing else was hurt by this damage.

EDIT: I think it's from cold damage if I remember correctly from one time i was a monkey

**Comment by XDTM** [comment]
The monkey eating part is fixed
