### ISSUE TITLE
Anatomic Panacea kills slime people

### ISSUE THREAD

**Issue by Names-Are-Hard** [tgstation/tgstation#34681]
[Round ID]: # 82223

[Testmerges]: # None

[Reproduction]: # Be a changeling, be a slime person, and use anatomic panacea.

**Comment by YakumoChen** [comment]
I mean, it DOES purge all the toxins from your body by giving you a huge dose of pentetic acid. Given detoxifiers are poison to slime (it destroys their blood - a toxin), it's obvious this would kill slimes.

Really, you'd have to be a total idiot to use panacea as a slime ling. Slimes are immune to almost every function its designed to cure...

**Comment by UncleBourbon** [comment]
Yea uh i thought slime people want toxins in them and anti tox out of them? Thats their entire gimmick... the whole reversal of toxins affecting you.

**Comment by Armhulen** [comment]
You purged toxins out of a creature made up of extremely toxic slime jelly what did you expect

**Comment by ShizCalev** [comment]
feature

**Comment by coiax** [comment]
Given that Anatomic Panacea is supposed to represent the changeling's mastery over the biological, I would say this is an unintentional side effect of the _implementation_ of Anatomic Panacea.

You shouldn't have to know the implementation of a power to avoid killing yourself with it.

**Comment by tralezab** [comment]
feature
