### ISSUE TITLE
wizards have pride mirrors for no reason

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#34689]
http://take.ms/5oMJg

they can raceswap into bad stuff

**Comment by Buggy123** [comment]
>wizard
>no reason
># magic
>mirror

**Comment by GunHog** [comment]
They are not "Pride" mirrors, as they do not have the trap. Also, this is entirely intended. Wizards are the ultimate solo antags, after all.

**Comment by Tlaltecuhtli** [comment]
is free shadowling intended?

**Comment by evsey9** [comment]
they already can't swap into romerol zombies

**Comment by Buggy123** [comment]
Also shadowling is a a downside as much as a upside because 90% of the station is bright and if you go around breaking APCs as a literal _wizard_ you won't last long before you get valided.

**Comment by Kromgar** [comment]
WHY IS THIS NOT CLOSED YET?

**Comment by ShizCalev** [comment]
races_blacklist could probably stand to use an update.

**Comment by ninjanomnom** [comment]
Feel free to open a pr to update the races blacklist and we can argue balance there
