### ISSUE TITLE
ref decoder broken with mobs

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#34693]
OOC:  KyleTheCookie:  everyone will think you're a traitor tho 

OOC:  KyleTheCookie:  or are probably greytiders who think it's an energy sword and kill you for it 

Server-Side Code Modifications:  https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm 

Round ID:  82244 

Server revision compiled on:  2018-01-19 

b960c7 

Revision: 14d7c322c6233085dd85574a69e0da4334d154c2 

Server tools version: /tg/station 13 Server v3.2.1.11 

Server tools API version: 3.2.0.2 

Current Informational Settings: 

Protect Authority Roles From Traitor: 1 

Protect Assistant Role From Traitor: 0 

Enforce Human Authority: 1 

Allow Latejoin Antagonists: 1 

Enforce Continuous Rounds: 8 of 17 roundtypes 

Allow Midround Antagonists: 6 of 17 roundtypes 

All Game Mode Odds: 

traitorchan 24.5% 

traitor 18.4% 

clockwork_cult 8.2% 

cult 8.2% 

secret_extended 2% 

nuclear 16.3% 

revolution 12.2% 

wizard 10.2% 

the ref decoder doesnt decode mobs
it stopped working from yesterday it seems

**Comment by AnturK** [comment]
REF -> /ref

**Comment by kriskog** [comment]
Circuits are gone
