### ISSUE TITLE
there is no smoke machine design

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#34694]
Issue reported from  Round ID: 82247 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

@kevinz000

**Comment by praisenarsie** [comment]
RnD doesn't need to have EVERYTHING y'know

**Comment by XDTM** [comment]
It should, if it's powerful lock it behind more techwebs

**Comment by Buggy123** [comment]
Smoke machine also can't be screwdrivered or deconstructed normally.

**Comment by Ratvar** [comment]
there is no supermatter machine design iN R&D

**Comment by Buggy123** [comment]
The snowflakery of the smoke machine is a legitimate issue that should be addressed. It makes upgrading it more difficult (you have to use a BRPED or literally break it and rebuild it with the better parts) and makes it more painful to disable as well.

**Comment by ExcessiveUseOfCobblestone** [comment]
> RnD doesn't need to have EVERYTHING y'know

Put it in the medical proto then :^)

**Comment by Tlaltecuhtli** [comment]
i think it was ported on techweb
