### ISSUE TITLE
Completing a cleanbot spawns it away from you

### ISSUE THREAD

**Issue by nicbn** [tgstation/tgstation#34703]
Issue reported from  Round ID: 82263 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

**Comment by ShizCalev** [comment]
What exactly do you mean away from you?

**Comment by ShizCalev** [comment]
@nicbn

**Comment by nicbn** [comment]
Some tiles away, not sure how many, they can spawn right below you or several tiles away. I think they spawn near other cleanbots or near some cleanable, not sure

**Comment by nicbn** [comment]
Noticed it in a round that I built like 10 cleanbots, after the 3rd one they started to spawn away from me
