### ISSUE TITLE
oh god putting an xray gun on a chameleon vest lets you hear deadchat for a few seconds

### ISSUE THREAD

**Issue by AlexTheSysop42** [tgstation/tgstation#34700]
Issue reported from  Round ID: 82255 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

So I stole a chamvest and was making xrayguns to fight a blob, when I tried to equip the gun on the suit storage slot I "died" for a few seconds (couldnt speak or leave body though) and came back to life just fine.

This is what I saw, chatlog-wise
![xraygunonchamvest](https://user-images.githubusercontent.com/25281214/35186429-26168bfa-fde2-11e7-905f-3dc1a1e9d24d.PNG)

"you put the xray gun in the BoH" is proof that I came back

**Comment by KorPhaeron** [comment]
@xdtm your hallucinations are too good

**Comment by XDTM** [comment]
Wew

**Comment by KorPhaeron** [comment]
yep, I got the same one last night and nearly adminhelped
