### ISSUE TITLE
Some walls do not have floors under them.

### ISSUE THREAD

**Issue by SyruseEln** [tgstation/tgstation#34710]
Issue reported from  Round ID: 82266 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Shuttle walls, when deconstructed, have no floors under them.

Walls that spawn on airlocks in maintenance also do not have floors under them when deconstructed.

There might be more examples of this but that's all I remember. This has been going on for at least more than a week.

**Comment by WJohn** [comment]
Yes, known bug, there's a million dupes by now. Coiax's shuttle refactor is involved for its fix but has been on hold for a long time, so this bug is gonna persist for a while longer yet.
