### ISSUE TITLE
AI's cannot understand Mothspeak.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#34736]
Issue reported from  Round ID: 82296 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Unlike Draconian (lizardperson language), AI's are unable to understand the snowflake lanugage. This becomes a problem when you are unable to learn of the moth's attempt at revolution.

**Comment by KorPhaeron** [comment]
remove mothspeak they already have a flight gimmick

**Comment by Teepeepee** [comment]
talking smack at the back of humies is fun... add the moth language as part of the "unlockable" stuff you wanna do at least please.

**Comment by WJohn** [comment]
yeah no, an exclusive club of metabuddies who can only be understood by eachother is the last thing we wanna add.

**Comment by Teepeepee** [comment]
Don't lizards have a language too? or was it taken away with the same reasoning? I get it if it was, but if not then that's not a valid argument.

**Comment by WJohn** [comment]
because you want that to be added to an "unlockable" thing, which is what paying members would get. byond members should get nothing that actually influences the game.

**Comment by Teepeepee** [comment]
I must have read the unlockable things thread wrong then, thought it said complete a space ruin or some goal to get stuff.
