### ISSUE TITLE
Interaction doesn't work with multiple objects

### ISSUE THREAD

**Issue by ayyourboibilly** [tgstation/tgstation#34747]
[Round ID]: #82310
[Round ID]: #82310
[Round ID]: #82310

[Testmerges]: # Might be due to #33166 

[Reproduction]: # Can't use xenobio console,rapid part exchange,bio bag and a few other things

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by AnturK** [comment]
@kevinz000
