### ISSUE TITLE
botany - fungal vitality,weed adaptation bugs

### ISSUE THREAD

**Issue by typnct** [tgstation/tgstation#34754]
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
in botany after you add fungal vitality(no need for water nor nutriants)
the plant still requires water and nutriants - even though it wont die without it

a plant with weed adaptation - same issue - shows the weeds

**Comment by Marflowerose** [comment]
Will the plant get overtaken by weeds even if it has weed adaptation? If not, this seems to work as intended, the tray has the weeds, not the plant itself. Fungal vitality also seems to work just fine, presumably the plant should utilize at least the nutrient since different nutrients provide different bonuses.

**Comment by typnct** [comment]
yes it does get overtaken even with weed adaptation(tested on lemon trees and combustible lemon trees)

**Comment by typnct** [comment]
and for a weird reason even in a golden tray the plants still get overtaken

**Comment by typnct** [comment]
anyway when a plant has fungal vitality it shouldnt ask for water and nutriants anymore right?
and because it doesnt really need it it should show that it requires it

so just turn it off - because it has no impact

**Comment by Marflowerose** [comment]
Fungal vitality does not need water or light, it still needs nutrients.

**Comment by ShizCalev** [comment]
Weed hardy (weed adaptation) negates the requirement for nutrients

Fungal metabolism halves the light requirement, however does not remove it completely. It also removes the water requirement.

That said, neither of them should be vulnerable to weeds, so if that's happening then something's wrong with https://github.com/tgstation/tgstation/blob/b2b3f7f7c0cbb357a5452bc6f31e3f8ee2b7d9ab/code/modules/hydroponics/hydroponics.dm#L215

**Comment by ShizCalev** [comment]
The only but here is weedinvasion() proc'ing incorrectly, the rest is intentional by design (as per the comments in the code.)

**Comment by newfren** [comment]
I have used weed adaptation to protect plants from being overtaken by weeds fairly extensively and it has worked in the past - this would be a very recent bug.

**Comment by ArcaneMusic** [comment]
As a result of #50001, this should no longer be an issue, as weedinvasion() no longer works on trays that contain existing plants, only empty trays.
