### ISSUE TITLE
Lava river generation can overwrite any turfs.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#34758]
![](https://i.imgur.com/tJ3s9gD.png)

I'm guessing it has to do with the area. This section of bridge here is outdoors, so it is affected by ash storms. I'm guessing that area is what's used to determine whether or not lava can overwrite turfs, rather than checking what turfs are actually present (basalt rock vs steel plating).

It's a bit limiting since that means you *need* a unique area for your ruin in order to prevent it from being overwritten by lava, but this will simultaneously prevent you from being exposed to ash storms which can look jarring.

**Comment by Kromgar** [comment]
Happens with ash ligger ruins too
