### ISSUE TITLE
Nuke Ops can arm the nuke unanchored

### ISSUE THREAD

**Issue by SyruseEln** [tgstation/tgstation#34760]
Issue reported from  Round ID: 82322 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

I observed this during this round. An op armed the nuke while it was floating in space and just ran around dragging it through space as it counted down. Eventually dragging it off the station z-level where the disc auto-teleported out and the nuke remained armed.

[Testmerges]: #34686: 'Ends the great monkey freezing epidemic' by Robustin at commit 822aa5
#34648: 'Monkeymode tweaks' by MoreRobustThanYou at commit b72e80

**Comment by RandomMarine** [comment]
Hasn't this been intended behavior for years? Hell, I remember the nuke op guide on the wiki suggesting to to arm the nuke on the shuttle before taking it to the station.

**Comment by ChangelingRain** [comment]
This is absolutely intended; you do not have to actually anchor the nuke to arm it, it's just useful to do so if you want to leave with the disc and all your operatives.

**Comment by SyruseEln** [comment]
Well thats dumb
