### ISSUE TITLE
Sniper rifles are able to hit people inside mechs.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#34761]
A sniper rifle round will take off one of your limbs from inside the mech, and also deal upwards of doubled damage to the mech, oftentimes 1-2 shotting it, dealing far more than it normally does. Sniper rounds normally deal 70 brute, but against a durand (35% bullet armor) it dealt 168.8 in one hit.

**Comment by RandomMarine** [comment]
Another case of non-explosions calling ex_act

**Comment by JohnMcLaime** [comment]
Mech damage is weird in general, 1 fueltank can take up to 90% hp off gygax for example, when it has 250 hp, yet fueltank explosions dont oneshot people directly (unless they arent on same tile). kinda same with srm8 missiles vs mechs and people, damage difference is noticeable.
Or punching a gygax with a durand almost destroys it.

**Comment by WJohn** [comment]
It might be a similar case to #27972, where turrets take EXTRA damage for having more armor. Turrets with 75% damage resistance will actually take 4x more damage, for example.

**Comment by RandomMarine** [comment]
I forgot to mention that ex_act also applies to the mech's contents, which is why the pilot also gets damaged and often de-limbed.

**Comment by Tlaltecuhtli** [comment]
any kind of explosion seems to oneshot gygax (and phazons i think) while durands are just scratched

**Comment by RandomMarine** [comment]
If a mech passes a deflect_chance roll, an explosion's severity is increased (weakened) by 1. But aside from the H.O.N.K., that number's pretty low.

**Comment by ExcessiveUseOfCobblestone** [comment]
someone's never played C&C RA3
