### ISSUE TITLE
Arming a (real) nuclear bomb creates a static-y sound as if it was a toy bomb.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#34763]
See title
roundid: 82327

**Comment by WJohn** [comment]
I'm pretty sure this is intentional as it is actually your pinpointer making that sound, which is also when it changes targets to instead point at your shuttle.

**Comment by ChangelingRain** [comment]
yup, the pinpointer does that. could probably use a custom sound but fuck if we ever keep sound guys.

**Comment by kevinz000** [comment]
feature
