### ISSUE TITLE
SM activates itself after entering the chamber

### ISSUE THREAD

**Issue by kisiel090** [tgstation/tgstation#34779]
[Round ID]: 82359

[Reproduction]: Before SM is activated on MetaStation, place two additional scrubbers inside the chamber.
Set up all scrubbers and vents, without setting up cooling loop.
Wait for a while. SM activates itself.

I don't know what part of this proccess can cause the issue, so i just included everything.

**Comment by Marflowerose** [comment]
How long does it take for it to activate?

**Comment by kisiel090** [comment]
I had it happen to me twice: 
First time SM activated after I walked out of the chaber, and was halfway through  colling loop modification (which took few minutes). 
Second time was right after i walked out of the chamber and set up the air alarm. 
First time might have also happened, because someone else was setting up air alarm.

**Comment by Marflowerose** [comment]
Is it possible that the trace amounts of co2 caused it to start?

**Comment by kisiel090** [comment]
Is it possible? I asked in OOC and got the answer that self-starting SM is impossible

**Comment by Spaceinaba** [comment]
did you turn on the scrubbers before you walked in

**Comment by YPOQ** [comment]
Tested it on a local server. Siphoning the chamber and then standing inside for roughly 30 seconds will get the carbon dioxide percentage high enough to start the delamination. Wouldn't really call it a bug personally.

**Comment by kisiel090** [comment]
scrubbers were off while i was walking in chamber. I only turn on scrubbing after i exit it.

**Comment by Marflowerose** [comment]
Unable to reproduce, even 3% co2 did nothing to the SM

**Comment by kriskog** [comment]
I expect the siphon from air alarm set the SM off, as it doesnt like vaccum. Air alarm is the last checkpoint on the list, after you start the circulation.
