### ISSUE TITLE
Space ruins present a small but serious teleport risk.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#34772]
There are various things which teleport you to either a random spot in space, or a random (but fixed per round) spot in space. If this location is inside a space ruin, it can prove potentially hazardous or deadly.

For instance, there was a round where a pride's mirror always teleported into a ship ruin with 2 syndicate simplemobs nearby. It also stuns you when you teleport. Completely unavoidable death. Without prior knowledge of the dangerous teleport location you can die with absolutely no way to prevent it.

![image](https://user-images.githubusercontent.com/16315400/35208672-7e758176-ff17-11e7-8101-9953d75cd374.png)

**Comment by ShizCalev** [comment]
I fail to see the issue here.

**Comment by SpaceManiac** [comment]
You say "various things". Can you list the other things, or is the problem specific to pride's mirror?

**Comment by Buggy123** [comment]
Pride's mirror
Touching transit space (shuttles)
Possible some BoH+teleport interactions
Jacob's Ladder (not exactly random but you aren't going to know the exact spot you'll end up at in all 5+ z-levels)

**Comment by AnturK** [comment]
The only issue here is transit should be dumping in EMPTY_SPACE. The rest is clear case of gitgud.
