### ISSUE TITLE
Omega station kitchen has two milk/egg fridges

### ISSUE THREAD

**Issue by CosmicScientist** [tgstation/tgstation#34780]
Round ID: 82361
Master revision unknown
Revision: a52b18eeecef38fc8426ea6a2b96c84e3d0ef266
![double milk mapping problem](https://user-images.githubusercontent.com/11809482/35221455-1bc2b6d8-ff72-11e7-8e1d-1e5b0af7747d.png)
One of these needs to be the sugar/flour/rice fridge or I have to start interacting with the botanists!

Whilst fun to grow your own ingredients and to walk in the colourful hallway over to botany for some early supplies, it might not be fun for new players to only be able to make egg, steak and fried donk pocket. Though they can make half a breakfast buffet if they follow the truest dwarven profession of cheese making.

**Comment by Tlaltecuhtli** [comment]
unplayable

**Comment by Mark9013100** [comment]
Will fix when I get the chance.

**Comment by DaxDupont** [comment]
@Mark9013100 2slo

**Comment by Mark9013100** [comment]
@DaxDupont reee
