### ISSUE TITLE
Reviving stasis never finishes, cannot revive

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#34789]
[Round ID]: #82379

[Reproduction]: 

1) Be a ling in crit from my own spider nom'ing me

2) Hit reviving stasis

3) Ghost out of hard crit

4) Wait

5) Re-enter corpse, no revive option available, clicking reviving stasis says "We are already reviving!" Revive option never appears. Restarted the game and still no revive option.

**Comment by Repukan** [comment]
Aren't you not supposed to ghost out until you die?

**Comment by ExcessiveUseOfCobblestone** [comment]
if you ghost out in crit it's the same as succumbing

**Comment by Robustin** [comment]
When I ghosted I didnt get any "catatonic" warning since I was deep in crit, my body didn't show as catatonic and I was able to re-enter my body freely but any powers I used were unavailable because I was "incapacitated" and reviving stasis was telling me "We are already reviving!"

**Comment by PKPenguin321** [comment]
Were there any overlays not going away that round or anything like that? Maybe timers were broken that round

**Comment by PKPenguin321** [comment]
Cannot reproduce
