### ISSUE TITLE
Mime doesn't get an uplink if Pen is Chosen as uplink

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#34790]
Issue reported from  Round ID: 82380 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Like the title says, I was a mime traitor, but didn't get an uplink or uplink codes. I had my uplink preference set to pen.

**Comment by coiax** [comment]
The Mime PDA has `inserted_item = /obj/item/toy/crayon/mime`, which is not a pen.

This bug makes sense.

**Comment by OmegaShoots** [comment]
Strange, I've rolled traitor mime after recently changing my uplink to pen and had a pen that I could use.

**Comment by ExcessiveUseOfCobblestone** [comment]
@OmegaShoots wym
