### ISSUE TITLE
Attempting to build and run tgstation on the 512 beta results in multiple issues.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#34792]
Local server. 512 beta, clean pull from master.
Byond issue, but just putting this out there.

![image](https://user-images.githubusercontent.com/9410002/35240494-7896491a-ff68-11e7-978c-59d231fdc241.png)

**Comment by Cyberboss** [comment]
Is this 1404? If so it's a know issue with regex iirc

**Comment by Shadowlight213** [comment]
yes 1404

**Comment by Cyberboss** [comment]
Try on 1403

**Comment by Cyberboss** [comment]
We don't go to 1404
