### ISSUE TITLE
Changing the shuttle's area with station blueprints only sends that part of the shuttle

### ISSUE THREAD

**Issue by Qbopper** [tgstation/tgstation#34797]
Issue reported from  Round ID: 82380 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

if you set only the shuttle cockpit as the shuttle area, only the cockpit will launch when the shuttle departs

likely due to the way the shuttle works and might be a pain to fix, just curious if this is intended behaviour or not

it's funny but makes very little sense IC

**Comment by praisenarsie** [comment]
known that blueprints fuck shuttles

**Comment by Qbopper** [comment]
didn't see an issue for it until now but if you link a number of an existing one i'll close this

**Comment by RandomMarine** [comment]
#33104

**Comment by Qbopper** [comment]
man our issue database is fuckedl mao
