### ISSUE TITLE
The item icon of a photograph is animated if the subjects photographed are animated

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#34806]
1) Take a photo of Poly.
2) The photo itself does not move.
3) But some motion is visible in the item icon.

**Comment by deathride58** [comment]
Feeeeeeaaaaaaaaaaatuuuuuuuuure

**Comment by coiax** [comment]
Then the full photograph should also be animated.

**Comment by DaxDupont** [comment]
@coiax that would be hella cool

**Comment by Cyberboss** [comment]
@AnturK fucking lol

**Comment by Kerbin-Fiber** [comment]
We could use this to make a special camera obtainable via adminspawn or wiznerd fun
