### ISSUE TITLE
Explosions on the nuke op base cause space to appear, rather than snow

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#34809]
Round ID: 82394

1) Detonate large syndicate bomb on Syndicate Snowy Nuke Op base.
2) Space appears, rather than snow.

**Comment by SpaceManiac** [comment]
This should be fixable by placing appropriate baseturf helpers in the syndicate base areas.

**Comment by ninjanomnom** [comment]
Ignore that, I thought this was refering to the lavaland syndicate base for a moment
