### ISSUE TITLE
Chameleon Kit Shoes - Number of available disguises

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#34805]
I feel the chameleon kit no-slip shoes are missing a very large variety of shoe types to disguise as. Brown shoes, white shoes, laceups, etc etc. Kinda strange considering the other parts of the kit have a HUGE variety of disguises.

**Comment by Bawhoppen** [comment]
It's supposed to be dynamic so it pulls from every type of shoe that exists in the code, but for some reason it's missing some.

**Comment by ArcaneMusic** [comment]
It appears that the list of chameleon options for shoes is now far more indicative of the intended list now.
Only thing it seems to do differently is check against `	chameleon_action.chameleon_blacklist = typecacheof(/obj/item/clothing/shoes/changeling, only_root_path = TRUE)`
That said, it seems like this is working properly yet again. Comment in case it's still interacting weirdly with the blacklist.
