### ISSUE TITLE
You can move other people's action button toggle using the observe verb

### ISSUE THREAD

**Issue by YPOQ** [tgstation/tgstation#34816]
Round ID: 82408
1. Be a ghost/observe
2. Select observe verb in the ooc tab then choose your victim
3. Annoy the shit out of them by constantly moving the toggle button in front of things they're trying to click on.

The other action buttons are hidden from observers so it doesn't work with them.

**Comment by optimumtact** [comment]
@tgstation/commit-access

**Comment by Buggy123** [comment]
Wew

**Comment by AnturK** [comment]
Easy fix, but i'd prefer finally wrapping Click/AltClick/MouseStuff finally.

**Comment by optimumtact** [comment]
yeah all the extra click paths need the same handling
