### ISSUE TITLE
Poly's ghost can be consumed infinitely by the SM crystal

### ISSUE THREAD

**Issue by PsyCommando** [tgstation/tgstation#34814]
**Reproduction:** Dump poly into the SM room, it will walk into the crystal and die, or you can throw it into it. Then its ghost will stay in the chamber and constantly waltz into the SM crystal and trigger admin messages, and spawn tons and tons of ashes in the chamber. You can pretty much run the SM without emitters this way though.
Also, poly's ghost changes sex in the fluff text messages from time to time XD
![2018-01-23 00_52_44-space station 13](https://user-images.githubusercontent.com/8772299/35260141-c46acf2c-ffd7-11e7-8bd5-b21a92c293e5.png)

To be clear, I didn't do that on the TG server, just on localhost while testing another bug.

**Comment by Armhulen** [comment]
that's an epic gamer fail for all of us XD

**Comment by PKPenguin321** [comment]
That's really funny

**Comment by Buggy123** [comment]
f e a t u r e

**Comment by 81Denton** [comment]
Truly the engine of the future if you RCD out the floor too

**Comment by LetterN** [comment]
quantum cracker theory did this

**Comment by Anonmare** [comment]
The polycrystal engine

**Comment by Buggy123** [comment]
Maybe we should just put a sanity limit on the adminmessage so it doesn't cause spam?

**Comment by PsyCommando** [comment]
I guess Nanotrasen found a new way to run their SM engine using crackers and hate XD 
And maybe changing dust so it doesn't spawns ashes each time poly's ghost run into the crystal might be necessary too. 

And well, I ran the engine for a while using poly, even cold started it using her! And it stayed cool and all! Very safe, and cheap! 
![2018-01-23 20_06_32-mail](https://user-images.githubusercontent.com/8772299/35309155-f377cd00-0078-11e8-963f-7beffc9611b1.png)
I guess it could also help warn when gray tide and etc mess with the engine if they get possessed by poly XD

**Comment by PsyCommando** [comment]
Ok, so I left the thing running on its own for a while, and now there's 4 poly ghosts? 
![2018-01-24 08_58_17-space station 13](https://user-images.githubusercontent.com/8772299/35336427-5e727ca0-00e6-11e8-8f58-5dc5a10e34c0.png)
And right clicking on an ash pile just crash beyond.
