### ISSUE TITLE
beakers dont fit inside rpeds

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#34824]
beakers are a component inside some machines u should be able to upgrade thrn with rped/brped

**Comment by Buggy123** [comment]
You should also probably be able to put bluespace crystals in them as well.

**Comment by ExcessiveUseOfCobblestone** [comment]
add types to
https://github.com/tgstation/tgstation/blob/4f1f265d7269a6185131afbac3e7cc62e6e92e9b/code/modules/research/stock_parts.dm#L12

add tiers to https://github.com/tgstation/tgstation/blob/dd9ddf6261353091078b12ea7f2ddd023d9dc918/code/modules/reagents/reagent_containers/glass.dm

and edit https://github.com/tgstation/tgstation/blob/647ea873a30e243193bcf1d8a0fb33466bf117f5/code/game/machinery/_machinery.dm#L393
