### ISSUE TITLE
Lavaland clown ruin floors aren't lubed

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#34839]
Issue: The lavaland clown ruin floors aren't slippery. You can just enter, walk to the trophy room and stroll out.

Expected result: The floors are supposed to be slippery as if covered in space lube, forcing you to slip from wall to wall to get to the trophy room.

**Comment by praisenarsie** [comment]
@ShizCalev

**Comment by ShizCalev** [comment]
Pretty sure this is an initialize issue where the turf's wet var isn't getting passed to anything.

@Cyberboss

**Comment by Buggy123** [comment]
Ohhhhhh i always wondered what was up with that ruin, now it makes much more sense.

**Comment by 81Denton** [comment]
Yeah this is one of the very rare cases where the wiki was right

**Comment by KorPhaeron** [comment]
@ninjanomnom maybe your template changes?

**Comment by Kromgar** [comment]
AFAIK the floors have been like this for hte past... 2 weeks? I forgot to submit the bug report.

**Comment by Potato-Masher** [comment]
Damn it, this was never to be spoken of. 

This has been the case for a REALLY long time, like 2 or 3 months back I found one and the floors were not slippery. Wiki seems to be correct in this case.

**Comment by 81Denton** [comment]
Yeah, it's definitely been the case for 3+ months (should have just abused it and enjoyed my free honk staffs fuck)

**Comment by Buggy123** [comment]
delet this and maybe no one will try to fix it
