### ISSUE TITLE
Syndicate lavaland base atmos computers link to station vent tags

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation#34833]
Their tag id's only include the station ones, so will break if you try to use the reconnect functionality as it sets the output tag incorrectly.

They should have that button removed, since they start connected to the correct syndicate vents and tags

**Comment by 81Denton** [comment]
Should be an easy fix if you make a subtype with a TGUI interface that has the button removed. I'll try to do it in the next few days.

**Comment by 81Denton** [comment]
Nvm I take that back, my solution is horribly hacky. Someone else try their luck.
