### ISSUE TITLE
Changelings don't lose their false brains upon losing changeling

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#34846]
Round 82447

An admin gave Nightmare to a traitor as a ling trade

The Nightmare was killed and I removed its brain

The brain that came out was a normal pink human one, rather than brain/nightmare

**Comment by KorPhaeron** [comment]
@AnturK @XDTM 

I think you two touched mutant organs/brains last

**Comment by AnturK** [comment]
Can't reproduce. How was the nightmare spawned / what was the previous species.

**Comment by KorPhaeron** [comment]
We discussed this in coderbus, realized it was probably a changeling > nightmare trade via admins
