### ISSUE TITLE
Pirate Ship Turrets Fires at Syndicates But Not Crew

### ISSUE THREAD

**Issue by Terogeth** [tgstation/tgstation#34845]
Found in Round #82442 where the Pirates Ship auto-turrets fires at Syndicate agents, but it doesn't doesn't fire at crew nor borgs.

**Comment by AnturK** [comment]
Why wouldn't they fire at syndicate agents ?

**Comment by AnturK** [comment]
Should be shooting at borgs though.

**Comment by PKPenguin321** [comment]
And crew

**Comment by Robustin** [comment]
I've definitely been shot at by Pirate Turrets.

Borgs seem to have a turret problem in general.

**Comment by AnturK** [comment]
Can't reproduce. Borgs are ignored with all turrets but that's easy fix
