### ISSUE TITLE
Fire melts Lava

### ISSUE THREAD

**Issue by DaedalusGame** [tgstation/tgstation#34842]
Found this on localhost. If you ignite a sufficiently hot fire on lava (say, throwing inferno clusterbangs or somesuch) when the fire disappears, the lava will melt into chasm.

**Comment by praisenarsie** [comment]
https://github.com/tgstation/tgstation/issues/32977

reminds me when thermite could melt lava

**Comment by DaedalusGame** [comment]
ikr

**Comment by alexkar598** [comment]
It gets so hot the lava evaporates,feature

**Comment by DaedalusGame** [comment]
lava is just molten papermache

**Comment by WJohn** [comment]
This is most easily observable with the syndicate listening post, which as a turbine that can get hot enough to melt all the lava nearby. If the base is destroyed, the location which held the turbine fire will melt a 20 tile wide hole.
