### ISSUE TITLE
snuke ops have a hole in their crotch

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#34847]
normal state (with the hole):
![image](https://user-images.githubusercontent.com/6209658/35310742-e7227bb0-0080-11e8-92f8-c66148f355ae.png)
alt state (no hole):
![image](https://user-images.githubusercontent.com/6209658/35310748-eb48a98a-0080-11e8-887a-4663a66767ea.png)

The pixel isn't alpha in the sprites, so i have no clue why it's happening. probably happens for all the other variants too.

**Comment by Cyberboss** [comment]
revenge of the dixels

**Comment by deathride58** [comment]
# OwO

**Comment by WJohn** [comment]
god damnit lol

**Comment by theOperand** [comment]
THE RIDE NEVER ENDS

**Comment by ArcaneMusic** [comment]
**IMPORTANT DIXEL UPDATE:**
Worn non-casually:
![image](https://user-images.githubusercontent.com/41715314/97796672-10e68100-1be3-11eb-9bb8-1e2218153b15.png)
Worn casually:
![image](https://user-images.githubusercontent.com/41715314/97796680-1d6ad980-1be3-11eb-8b63-46d3f062a89d.png)

It seems that someone, somewhere down the line, fixed the dixel dix hole.
