### ISSUE TITLE
Players get shoved into new admin bodies under certain circumstances

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#34851]
- Spawn a human
- Place yourself in control of it
- Ghost out and offer control of the human to ghosts
- Once a ghost is in the human, make yourself a human via the player panel
- The player will be pulled out of the previous human and placed into the one you made from the player panel and you remain a ghost

**Comment by KorPhaeron** [comment]
Dupe

**Comment by PKPenguin321** [comment]
Please fuckign somebody fix it reeeeeee
