### ISSUE TITLE
Can't ride the bicycle

### ISSUE THREAD

**Issue by improvedname** [tgstation/tgstation#34854]
Unable to ride it

**Comment by Iamgoofball** [comment]
problem:
I want to ride my bicycle

**Comment by improvedname** [comment]
It was my childhood dream to ride a bicycle

**Comment by Marflowerose** [comment]
I thought it was intentional thing just to annoy people.

**Comment by Iamgoofball** [comment]
@kevinz000 git blame says it was you lmao
fix it
