### ISSUE TITLE
If you're a engiborg with someone buckled to you, spacewind will impact you again

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#34850]
Be engiborg

RCD hole in floor

Nothing happens, you're spacewind immune

Buckle a mob to yourself

You now get sucked towards the hole, your immunity is lost from having a rider somehow

**Comment by KorPhaeron** [comment]
@kevinz000 @MrStonedOne

**Comment by ChangelingRain** [comment]
my guess is that spacewind affects both the buckled object and whoever is buckled to it, for maybe double effect if both aren't immune

**Comment by ExcessiveUseOfCobblestone** [comment]
Can someone reproduce this just to make sure we weren't pushed in or anything like that?

**Comment by KorPhaeron** [comment]
@ExcessiveUseOfCobblestone I went and tested in the thunderdome before making this issue report
