### ISSUE TITLE
stock market bug

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#34864]
http://take.ms/GRtHN

my shares disappeared i tought the ai took them but the logs disnt show anyone selling them happening on multiple rounds

**Comment by LetterN** [comment]
_local station crashes the entire Nanotrasen GDP by about 150%_

**Comment by Tlaltecuhtli** [comment]
round id:82469

**Comment by Marflowerose** [comment]
I've seen this happen billion times, I think it deletes some of the stock when the stock goes to 10 or "below" / crashes

**Comment by ExcessiveUseOfCobblestone** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
lemme check

i think companies can tank so hard they do get destroyed, did the NEWS mention it at all?

**Comment by theo2003** [comment]
@Iamgoofball they can go bankrupt, if that happens it's permanently destroyed

**Comment by ExcessiveUseOfCobblestone** [comment]
if that happens though the screen shows that they've tanked.

**Comment by Iamgoofball** [comment]
yeah it's possible a bankrupcy occured

**Comment by yorii** [comment]
Can't they consolidate or split? I've seen stock numbers being halved before but I dismissed it as a feature.

**Comment by Tlaltecuhtli** [comment]
closing because its a """""""feature""""""""
