### ISSUE TITLE
ChemMaster 3000 - Pill form issues

### ISSUE THREAD

**Issue by Seltem** [tgstation/tgstation#34863]
Issue reported from  Round ID: 82471 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

[Round ID]: #82471
[Testmerges]: #33166: 'Refactors storage handling from /obj/item/storage to a component.' by kevinz000 at commit f44620

[Reproduction]: Unable to create things in pill form at the ChemMaster 3000. Was tested across multiple containers such as the differing beaker sizes and a spray bottle, across different terminals. This applies for both the option to create a single pill and multiple pills.

[For Admins]: Under normal playing situations.

**Comment by AnturK** [comment]
#33166 @kevinz000
