### ISSUE TITLE
TGstation13 has 1000 issues

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#34865]

**Comment by Durkel** [comment]
but a bitch aint one.

**Comment by CosmicScientist** [comment]
>tgstation stops having 1,000 issues

>opens an issue to make it 1,000

>999

**Comment by Dorsisdwarf** [comment]
its not my fault someone fixed two issues.

**Comment by optimumtact** [comment]
Guys, this issue has no value, please stop opening and closing it.
