### ISSUE TITLE
Client's crashing mega thread. v3

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#34862]
1404 fixed the crash we were able to reproduce, using the shuttle placer thingy. I was able to confirm this.

So what we need to do is reset, as too much info in related issue threads applies to an old bug.

Bugs relating to hangs on clients that involved mobs that can see all turfs (ais, ghosts, advance camera consoles) have been fixed 3 times since 512 first came out.

What I need is more examples of what is going on when the hangs happen.

What I need is for everybody to list the following info for times when you have crashed on 1404 only.
1. state the general area you were looking at
1. state what kind of mob you were in, 
    1. state what view mode changes you had active (mason vision, darkness toggling, huds or invisibility changes, etc.)
1. If the turfs you had seen had changed since their round state, state any changes that you remember.
    1. like being changed, being filled with a gas or gas overlay, being on fire, etc.

Also please note that there is a difference between a hang and a crash that requires a difference approach to solving. If it locks up or Windows says its `not responding`, thats a hang, if Windows says it has `stopped working` or the game window just closes flat out, that is a crash. Please specify which you are seeing.

Please close #33377 as it is too full of old info with no way of knowing what still applies.

**Comment by ike709** [comment]
I hang at least once, often twice (depending on round length), _every_ round on 512.1404. However, I've only been playing on Bagil, which to my knowledge still uses 511, so I assume that's probably part of the problem?  It has happened during all of the five or six rounds I've played in the last few days. This has been my first time playing on 512, so I'm not sure if it was a problem on earlier 512 versions. Now, to answer your specifics:

1. Various departments on the station. Engineering, security, escape, science, etc. 
2. Every round I was spawning at the syndicate listening outpost and using the advanced camera console.  I also frequently left the advanced camera console and returned to it, but hangs only occurred while using it.
3. Honestly, I can't relate any big changes to the hangs. I've watched the SM explode without issue. I've seen security become bathed in blood due to an army of badmin-spawned clowns. Neither resulted in a hang. I've experienced hangs while moving the camera around, and while not moving it at all. It seems entirely random aside from the fact that it usually doesn't occur before at least about 20 mins into the round, and at least that much time until the next hang. 

And yes, it is indeed hangs, not crashes. I haven't crashed once. After I get some sleep I'll try to narrow it down more but it seems pretty random.

**Comment by Cyberboss** [comment]
Bagil has been on 1403 for a while now

**Comment by Kromgar** [comment]
It didn't matter what area i was looking at it seemed to happen FASTER if i was moving the camera rapidly if it was slower it would take longer to crash. This was not responding for me in 512. When i used cuck cult consoles and advanced security consoles. I had to downgrade to ever use any advanced consoles like xeno

**Comment by ike709** [comment]
Would updating Bagil to 1404 potentially solve this problem, then?

**Comment by MrStonedOne** [comment]
@Kromgar 1404 was released on friday, did you update to it and how much of your examples applies to 1404?

**Comment by newfren** [comment]
on sybil, round ID 82576. Can't get any more information because it's currently hanging. Was playing as a xenobiologist using the advanced cam console. Used it fine several times in a row, the only changes I can recall happening to the area I was looking at was some walls being removed with an RCD. I have byond version 1404.

**Comment by silencino** [comment]
Oi, so i was on terry. And this happened twice. I went to the bar and beat the ever livin' piss outa Pun Pun, at first i just had a massive spike and ignored it but then the game crashed, i came back and pun pun was very much dead. The second time i did the same, was chaplain this time and used pride hammer to bash pun pun a few times with the bartender watching, crashed again xept this time on 2nd hit or so without a single spike.

**Comment by Anonmare** [comment]
Still broken as shit

**Comment by MrStonedOne** [comment]
@Anonmare what version?

**Comment by Anonmare** [comment]
Beta branch latest version

**Comment by Anonmare** [comment]
512

**Comment by MrStonedOne** [comment]
full version number, xxx.xxxx

in the pager, its cog wheel -> about byond

**Comment by Anonmare** [comment]
512.1405

**Comment by newfren** [comment]
on 1405, tried to weld a wall near tech storage without eye protection, game hangs without the usually white flash appearing on screen. 82634 on sybil

**Comment by newfren** [comment]
82679 on sybil, game hangs whenever I tried to use the xenobiology console without moving my view to the normal selector or giving me buttons or whatever, just hangs.

**Comment by newfren** [comment]
82681 on sybil, game hung when I was being attacked by a laughter demon in genetics - both windoors were in the process of opening, if that's important, otherwise nothing had really changed.

**Comment by SpaceManiac** [comment]
512.1405, private server, regular game hangs when moving around too rapidly as AI eye, no HUDs or vision modifiers. Visible distortion (static showing through to space, screen objects becoming invisible, parts of the screen being rendered white or gray) present briefly at random when moving eye and for several seconds directly before hang. Waiting for a long time **sometimes** resolves hang, but this is unreliable. On a nonstandard map, seems most intense in Xenobiology lab, but occurs even in space with no objects around.

One particular hang which lasted ~15 seconds before resolving, while scrolling in deep space. Note the absence of static and the "Deploy to Shell" button as well as the white rectangle. In other cases, the right 3-4 buttons on the bottom bar go missing.
![image](https://user-images.githubusercontent.com/222630/35487112-e8135f30-042c-11e8-8b35-ddc05a277a59.png)

After resolving:
![image](https://user-images.githubusercontent.com/222630/35487117-f539f386-042c-11e8-82cb-a78b2296c3b8.png)

Also just observed a hang which lasted 40 seconds before resolving, after which the camera was in the corner of the Z-level and the AI eye static was invisible until the camera moved again.

Suspicious that SSinput may have exacerbated problem by continuing to issue image updates to clients which now continue moving server-side when hung client-side.

Reliable solution to avoid long-term hang is to only tap and not hold movement keys, but visual distortion is amplified.

**Comment by SpaceManiac** [comment]
#35091

**Comment by newfren** [comment]
sybil 82743, unprotected welding in the emergency shuttle caused a hang again. White flash again didn't appear.

**Comment by newfren** [comment]
sybil 82781, unprotected welding caused a hang, white flash DID appear.

**Comment by ShizCalev** [comment]
#35100 Placing poster on wall crashed client DS 1405

**Comment by ShizCalev** [comment]
While I know this is meant for clients, the latest 1405 beta is crashing without fail when loading the TGstation .dmb with DD for me. @MrStonedOne

**Comment by ike709** [comment]
I also can't load the .dmb without DD crashing.

**Comment by SpaceManiac** [comment]
>1405 beta is crashing without fail when loading the TGstation .dmb with DD for me

>I also can't load the .dmb without DD crashing on 1405.

http://www.byond.com/forum/?post=2340645

**Comment by Kromgar** [comment]
I was updated to the latest beta and i constantly crash on first accessing consoles like the shuttle movement console and xenobio console. It seems that isn't fixed. Playing on sybil

**Comment by halitosisman** [comment]
My client was hanging on regular intervals in Bagil today. Happened in escape hallway, command hallway, reebe, and genetics. It happened across 2 or three rounds.

**Comment by DaxDupont** [comment]
https://github.com/tgstation/tgstation/issues/34862

**Comment by ShizCalev** [comment]
deleted comments were for DM hanging due to http://www.byond.com/forum/?post=2340645, now fixed.

**Comment by MrStonedOne** [comment]
Yet another update to byond beta 512 to solve the hang/crash issue has been released.

Try it out and let me know how it works out.

**Comment by davv1** [comment]
BYOND client(not seeker/dreamer/maker, just chat client/game browser) is still hanging when receiving PMs. It's not that bad, until you get like 10 or more messages in minute: then it hangs for fefw minutes.

**Comment by davv1** [comment]
Also. Crashed with new Crew Monitoring Screen, as AI.

**Comment by MrStonedOne** [comment]
Reports have died down.
