### ISSUE TITLE
Atmos overlays are not removed from turfs scraped to space

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#34861]
![image](https://user-images.githubusercontent.com/222630/35320415-95d9d2fe-0098-11e8-96c1-c4608356d61e.png)

d1f3f99a25334b3dc386ffdfa15a56a9dac03d3c but I've been noticing it for a couple of weeks now.

**Comment by WJohn** [comment]
Yeah I think I've seen this recently in the plasmafire shuttle.

**Comment by nicbn** [comment]
Happens with SM too

**Comment by DaedalusGame** [comment]
happens frequently on my test server. about as frequent as 1u clf3 smoke grenades
