### ISSUE TITLE
Can't hit bridge modular computers

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#34874]
What it says on the tin. Attack chain not calling ..() somewhere.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/2e58d7bc86af6e4c5edd9b60c65501b4fbd68981/code/modules/modular_computers/computers/machinery/modular_computer.dm#L127

https://github.com/tgstation/tgstation/blob/647ea873a30e243193bcf1d8a0fb33466bf117f5/code/modules/modular_computers/computers/item/computer.dm#L373

**Comment by ArcaneMusic** [comment]
This appears to have been fixed through the addition of combat mode, or one of several machinery refactors that have occurred since then.
![image](https://user-images.githubusercontent.com/41715314/131542127-68ebd0ad-0fc9-46ce-8fcf-2c5f0f09f582.png)
