### ISSUE TITLE
The telecomms relay on the syndicate outpost doesn't seem to send to the station

### ISSUE THREAD

**Issue by F-OS** [tgstation/tgstation#34898]
1. Deconstruct tcomm relay.
2. Reconstruct it.
3. Spam your dumb gimmick.
4. Nobody responds and it doesn't relay.

**Comment by F-OS** [comment]
Aw fuck 1000th issue get.

**Comment by F-OS** [comment]
oh this issue exists and i don't know how to use a multitool and it isn't even a bug fuck me

**Comment by praisenarsie** [comment]
step 1, get a multitool on your base (there should be one in the toolbox i think)
step 2, click on telecomms relay with multitool
step 3, toggle [OFF] to [ON}

congrats your turned it on

**Comment by F-OS** [comment]
oh
