### ISSUE TITLE
Dead animals continue to drag things, even in death

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#34890]
1) Be Cayenne.
2) Drag something, let's say, a donut.
3) Die.
4) Someone else drags your body.
5) You continue to drag the donut, EVEN IN DEATH.

Also happens for Ian, so I assume it's all simple animals.

Round ID: 82486

**Comment by XDTM** [comment]
You'll have to pry the ball from Ian's cold, dead jaws

**Comment by vuonojenmustaturska** [comment]
easy fix, just put stop_pulling() in /mob/Death(). Humans seemingly stop pulling when something pulls them so this bug doesn't manifest there

**Comment by arsserpentarium** [comment]
No, they stop pulling in crit. You can pull human trains.
