### ISSUE TITLE
putting things into boots isnt correct in chat

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#34911]
![2018-01-24_19-01-57](https://user-images.githubusercontent.com/20155238/35365281-5966c2ea-0139-11e8-88a0-e7eee1aa8611.png)
![2018-01-24_19-03-05](https://user-images.githubusercontent.com/20155238/35365282-597b2e56-0139-11e8-8f69-c8933ad204d9.png)
![2018-01-24_19-03-17](https://user-images.githubusercontent.com/20155238/35365283-598fc802-0139-11e8-8bcc-401d7485db20.png)

**Comment by Spaceinaba** [comment]
I could have written text but I have sharex

**Comment by Cyberboss** [comment]
Testmerge
