### ISSUE TITLE
Moths get stunned by flashbang even with protective gear

### ISSUE THREAD

**Issue by AcuteCircle** [tgstation/tgstation#34924]
I played a moth sec officer and some other officer threw a flashbang. I got stunned even though I was wearing sechud sunglasses + protective headset.

I guess issue comes from this merge: https://github.com/tgstation/tgstation/pull/34794

**Comment by Repukan** [comment]
Feature

**Comment by XDTM** [comment]
Pretty sure it's intentional, sunglasses give +1 resistance, moths have -1

**Comment by evsey9** [comment]
Moth cuck

**Comment by Tlaltecuhtli** [comment]
feature
