### ISSUE TITLE
"magic" damage flag apparently exists and is used but no item provides magic armor

### ISSUE THREAD

**Issue by vuonojenmustaturska** [tgstation/tgstation#34931]
Discovered during armor datums testmerge, magic was not implemented for armor datums. It has silently failed before. 

I have added it to armor datums, however using it doesn't require armor datums to get merged. Just add an item in the armor list that says magic = <whatever>. Perhaps someone should add magic armor to items like inquisitor/DS/gem-encrusted hardsuits, wizard robes, something else?

**Comment by Supermichael777** [comment]
Finaly the wizard might not wipe himself the first fireball he tosses

**Comment by ShizCalev** [comment]
got another one here; https://github.com/tgstation/tgstation/blob/3daff514f9c6974dc519c70ffb092e72443acda2/code/modules/spells/spell_types/construct_spells.dm#L310

**Comment by KorPhaeron** [comment]
I think this might actually be the point of the magic flag, it bypasses armour (the flag predates the armour pen system)

**Comment by PKPenguin321** [comment]
Is this even a real issue?

**Comment by Fikou** [comment]
> Is this even a real issue?

maybe
