### ISSUE TITLE
How to speak draconic as a head of staff

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#34943]
1. Set up a lizard character.
2. Late join into a head role.
3. ???
4. Profit.

**Comment by praisenarsie** [comment]
@coiax

**Comment by BeeSting12** [comment]
this is actually the fault of whoever made nonhumans able to latejoin as heads

**Comment by ExcessiveUseOfCobblestone** [comment]
@LeoZ or @KorPhaeron

**Comment by Buggy123** [comment]
Look Centcom was desperate alright, either they put a dirty lizard in charge or no one at all.

**Comment by ExcessiveUseOfCobblestone** [comment]
Just say the guy was raised by ~~🐺 ~~ :lizard:

**Comment by vuonojenmustaturska** [comment]
fix soon

**Comment by Nilons** [comment]
@Buggy123 none at all then
