### ISSUE TITLE
AIs get thrown in shuttles.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#34944]
I understand that the crew and borgs get thrown but AIs probably shouldn't be thrown out of shuttles or at people due to their size. 
I don't think they can even bolt in shuttles

**Comment by ShizCalev** [comment]
Pretty sure they -can- bolt down.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/a62a978176f2e7420f34ed23c9391c311b567c03/code/modules/mob/living/silicon/ai/ai.dm#L325-L335

yeah they can.

**Comment by MoreRobustThanYou** [comment]
close it then
