### ISSUE TITLE
Tabling/grabbing doesn't cancel out stripping

### ISSUE THREAD

**Issue by improvedname** [tgstation/tgstation#34948]
So if you gonna greytide as i do usual.
you grab a officer for as example.
table him. queue up stripping alt click alt click, table again (on the same table you tabled before) it doesn't cancel out stripping when switching intents and such does or picking items up or grabbing people and doing other actions.

this can be very unbelanced as any greytider can grab a officer and strip them naked without them being able to fight back.

**Comment by praisenarsie** [comment]
@kevinz000

**Comment by kevinz000** [comment]
😡

**Comment by WJohn** [comment]
I mean really, the whole tabling thing is kind of a dumb meme and the only reason it's at all viable is because it lasts long enough to stunlock people. Both of these dumb issues could be fixed just by reducing the stun time you experience from being tabled to a super short period.

**Comment by improvedname** [comment]
@Wjohn the issue isn't the stun the issue is that stripping doesn't cancel out when you table again making it incredible easy to rob somoene

**Comment by OmegaShoots** [comment]
tbh if you got to the point of being tabled, you already lost the fight and should just forfeit your assets to the grey

**Comment by SuperNovaa41** [comment]
Still an issue. Although, shove stunning and table slamming has been dramatically changed since the creation of this issue. The only time when this becomes an issue is when you've already lost too much stamina to withhold the full time it would take to aggro grab and table slam.
