### ISSUE TITLE
Bedsheets look kinda weird when worn as a monkey.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#34956]
Issue reported from  Round ID: 82543 (/tg/Station Bagil)

![dreamseeker_2018-01-25_17-34-43](https://user-images.githubusercontent.com/33107541/35416217-54196f00-01f6-11e8-8f19-8bc3f10f533d.png)
![dreamseeker_2018-01-25_17-34-52](https://user-images.githubusercontent.com/33107541/35416222-5a1df308-01f6-11e8-86e2-ff02dc6e83c5.png)
![dreamseeker_2018-01-25_17-34-59](https://user-images.githubusercontent.com/33107541/35416223-5d97ffc4-01f6-11e8-853e-cfbcbfbb4c8a.png)

**Comment by ExcessiveUseOfCobblestone** [comment]
Give them longer legs when given a bedsheet :^)

**Comment by XDTM** [comment]
Spessmen have cloaks of invisibility but wear them the wrong way around

**Comment by Potato-Masher** [comment]
Looking back at this, the satchel also looks weird. Is there a system built in already to change what an item looks like if it's worn by a different mob?
If not, I may look into adding something like that. Might need some guidance on where to start though.

**Comment by SuperNovaa41** [comment]
Still an issue

**Comment by timothymtorres** [comment]
![dreammaker_8N9qSJ8sVK](https://user-images.githubusercontent.com/5195984/170411239-93a5db2e-d255-41cb-ba86-969d15dd2ef7.png)

So this is definitely a fix for a spriter.  Either we fill in the south facing bedsheet so that it's not empty OR we shorten the length of the bedsheets so that monkeys get a custom shortened length sprite.

**Comment by Profakos** [comment]
![image](https://github.com/tgstation/tgstation/assets/2676196/0b2401e7-2a0d-43d1-a9f8-d31c23d52011)
![image](https://github.com/tgstation/tgstation/assets/2676196/38ce0304-93f7-4719-920c-92a38d171a08)
![image](https://github.com/tgstation/tgstation/assets/2676196/033dc7b6-119a-4405-ad97-580115a1e4cb)

They look nicer now, with the autodistorted sprites, I think this can be closed.

**Comment by JohnFulpWillard** [comment]
Yea this is closed by https://github.com/tgstation/tgstation/pull/81598
