### ISSUE TITLE
You're always marooned on the station

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#34954]
https://atlantaned.space/statbus/round.php?round=82539

I made it out, but end round window said I was marooned

**Comment by praisenarsie** [comment]
@ninjanomnom

**Comment by ninjanomnom** [comment]
I'm not sure why I was pinged here, this is most likely an issue with z level traits.

**Comment by praisenarsie** [comment]
i thought it was shuttle related but ok

@SpaceManiac

**Comment by SpaceManiac** [comment]
This has been happening since the roundend report refactor which went in before z traits. This is a dupe but I don't have the previous issue # on hand.

**Comment by SpaceManiac** [comment]
Duplicate of #33520
