### ISSUE TITLE
Lavaland Syndicate Base has way too many explosions

### ISSUE THREAD

**Issue by DaedalusGame** [tgstation/tgstation#34965]
Previously, the base had 12 bomb walls, somehow, it has 28 now. All of these walls produce maxcaps. If someone reasonable could please lower the amount to the base amount necessary to destroy the base, that would be fantastic. Preferrably with emphasis on the interior walls so the explosions don't clip lavaland walls and produce sixteen thousand sand objects. 

For mapping reference, the explosion radius of one wall is (5,10,20).

**Comment by WJohn** [comment]
Agreed, I can try and reduce the number, I'm just not entirely sure that explosion is guaranteed to happen outside of that 5 total devastation radius, so I put them close packed.

Alternatively we could get rid of self destruction for large bases.
