### ISSUE TITLE
Alien Hunters have no way of propelling themselves down an anti-grav hallway

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#34979]
![image](https://user-images.githubusercontent.com/6778786/35453542-9755cc58-0298-11e8-8a7f-dee2de8797d6.png)

This is how a xenomorph hunter gets permanently stuck. They should be able to spit at a super high plasma cost or somethign to be able to propel themselves

**Comment by Jalleo** [comment]
Pounce doesnt work in zero g?

**Comment by Bawhoppen** [comment]
It wouldn't make sense to be able to pounce in Zero-G. Just add a plasma snowball they can throw or something

**Comment by GunHog** [comment]
@WJohn, do Xenos not have the ability to adhere to surfaces such as walls and ceilings in the lore?

**Comment by Kromgar** [comment]
Being able to bound off walls with  insane Xeno strength ain't possible? Bullshiiit. Would probably hurt a lot more to bash into walls tho

**Comment by Kromgar** [comment]
![image](https://user-images.githubusercontent.com/6778786/35467407-c19f6dc8-02db-11e8-8e39-43e59721ff91.png)
![image](https://user-images.githubusercontent.com/6778786/35467411-cd75fb3a-02db-11e8-80d0-90841441a134.png)

**Comment by WJohn** [comment]
While I'm not really one for *buffing* xenos even further by making turning off the gravity a benefit to them, I could see it being interesting in its own right as sabotage. I do like the idea of xenos trying to take control of the grav gen and keep it permanently down. The problem is that doing so is entirely too easy, as ventcrawling in there and breaking the APC takes a matter of seconds.

**Comment by Kromgar** [comment]
Look all i want is some some sort of high cost acid spit to just get out of 0 grav fuckery

**Comment by WJohn** [comment]
Alternatively, I think simply giving them the ability to pounce even in 0 g (as long as there is an actual floor below them and it's not open space) is okay.

**Comment by Jalleo** [comment]
Okay then I will let them pounce if they have floor below them but will test to see if the animation bugs out after as comment says.

**Comment by AlexTheSysop42** [comment]
same happens for zombies and player simplemobs if they get stuck on a person and the person moves

**Comment by kevinz000** [comment]
>buffing xenos

wtf

**Comment by PKPenguin321** [comment]
this is definitely a feature request, not an oversight.
