### ISSUE TITLE
Traitor round ended as soon as it started without antags showing up on the end round report

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#34976]
https://atlantaned.space/statbus/round.php?round=82584

![nwxbohp 1](https://user-images.githubusercontent.com/17237624/35448009-6937db60-02b9-11e8-81c2-1a6297e9a1d1.png)

**Comment by DaxDupont** [comment]
https://tgstation13.org/parsed-logs/basil/data/logs/2018/01/26/round-82584/game.txt

**Comment by Cyberboss** [comment]
@AnturK perhaps the gamemode code seeing no traitors before they're even assigned?

**Comment by AnturK** [comment]
There were three according to special role, round shouldn't have endend before post_setup is done though so not sure what's going on here.
