### ISSUE TITLE
Roundend report is not completely accurate

### ISSUE THREAD

**Issue by Teepeepee** [tgstation/tgstation#34970]
https://imgur.com/fw8Twdg
See above, this guy got his greenies when I did manage to reach centcom alive ( I was critted once there).
Its not completely wrong since the guy with hijack did get his greentext cucked by at least me and one other loyalist.

**Comment by Jordie0608** [comment]
The linked PR is unrelated to this issue, objective success is done from `check_completion()`, not round end report generation.

**Comment by timothymtorres** [comment]
Hijack was reworked with #54146 You no longer need to kill all players aboard the shuttle achieve the objective.
