### ISSUE TITLE
The order for antag selection is not good for many reasons.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#34991]
Currently, antag/job selection works weirdly, and this causes a lot of issues:

1: You can get a job you never wanted because you rolled antag but didn't have a job available.
2: On some gamemodes, if you roll the antag you do not spawn normally (eg wiz, clock, nukes). This can cause important jobs to be absent and...
3: You can meta the roundtype with antag job absences. If 2/3 shaft miners are missing (one of the most-demanded jobs in the game) in the middle of med/high pop, you can guess that it's either clocks/nukes. Combined with the command report and you can narrow it down further.

**Comment by praisenarsie** [comment]
@AnturK

**Comment by Jalleo** [comment]
This is probably a dupe. (We cant resolve this without very hard work maybe impossible)

**Comment by Poojawa** [comment]
Have antag selection/kidnapping happen before client characters are spawned and assigned a job/loadout. 

then it's just slap a check to see if what role was ultimately selected for them.

**Comment by ExcessiveUseOfCobblestone** [comment]
In laymen terms antag should be first then jobs be distributed rather than jobs being distributing then moving people around if they're antag.

**Comment by Rinoka** [comment]
Related to #4443.

**Comment by Jalleo** [comment]
Then itsone of those fixed issues occuring again probably.

**Comment by Incoming5643** [comment]
I want to point out that I looked into this and as far as game mode code currently exists the problems described in numbers 2 and 3 do not exist.

Off station antags gain an assigned_role in pre_setup() which runs prior to job selection. In job selection ( specifically DivideOccupations() ) players that already have an assigned_role are never added to the pool for job assignment, so they will not leave empty job slots that can be used to meta off station antags.

In theory if a player ONLY ever played a specific role and you knew that player was online and playing but that job was empty you could meta it, but that's more a problem of players taking too few jobs preferences or certain jobs being wildly unpopular. The former is also why number 1 is a thing.

**Comment by kriskog** [comment]
2 and 3 arent current issues, 1 is on purpose to ensure non-antag role mains also get an antag roll.
