### ISSUE TITLE
griff ghost defilery at escape might be able to damage shuttles?

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#34998]
round 82603
extended
griff ghost spawned midround
after stuff happened & shuttle called, griff ghost went to escape and defiled, breaking the windows and shit
when the shuttle arrived, it was completely uninhabitable for slimekind - most windows were smashed, and about half of the walls were broken to space. Shards and girders were present at centcom.

**Comment by Tlaltecuhtli** [comment]
intended

**Comment by Buggy123** [comment]
intended.
