### ISSUE TITLE
The shuttle departure can noclip you through single plane glass windows

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#34997]
![image](https://user-images.githubusercontent.com/12382984/35465072-680b0ad6-02f1-11e8-95aa-b7b9750eba25.png)
Round ID: 82602

I wandered to the back to remove my handcuffs in peace and as the shuttle departed, I got noclipped through the windows at the back

**Comment by Jalleo** [comment]
@ninjanomnom I presume this isnt a easy fix due to how shuttles work right?

**Comment by ninjanomnom** [comment]
no this can be somewhat easily fixed but it does require some slight restructuring

**Comment by ninjanomnom** [comment]
Strictly speaking this should only happen when the shuttle rotates in the move.

**Comment by DaxDupont** [comment]
Which they do on meta and delta.

**Comment by deranging** [comment]
I think they do on Pubby
