### ISSUE TITLE
Attempting to clone monkeys breaks the cloning pod

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#35014]
[Round ID: 82636]

If you scan a monkey and start cloning, it will result in initialization failure.  But something does happen.  The cloner creates a monkey mob inside the cloning pod, and never ejects it.

This results in the cloner being considered occupied and makes it impossible to clone anyone else.

**Comment by arsserpentarium** [comment]
I think,monkeys should be able to be cloned. Both with cloning and replica pod.

**Comment by DaxDupont** [comment]
They really shouldn't. You can mass produce monkeys already.

**Comment by DaxDupont** [comment]
Was this a player controller monkey or npc?

**Comment by Slignerd** [comment]
It was a player controlled monkey.

**Comment by ChuckTheSheep** [comment]
Line 136 of cloning.dm "var/mob/living/carbon/human/H = new /mob/living/carbon/human(src)"

When the clone is being created to copy over values, shouldn't it be creating the same type of mob as what's being cloned?

**Comment by AlexTheSysop42** [comment]
you should still be able to swipe a genetics ID to dump it
