### ISSUE TITLE
There is a syndicate comms officer basically every round now

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#35019]
Changing the space ruin to have a copy of the lavaland role means almost every round there is an antagonist with a voice changer trolling the radio. It stops being a novelty or even effective and gets tiresome.

@WJohn I was going to just replace the ghost role with an NPC again unless you have another plan

I'll probably disable it serverside in the meantime

**Comment by Jalleo** [comment]
I can do that later today or tomorrow. I am also feeling like reworks of ruins in general. I just need to plan the layouts.

**Comment by Robustin** [comment]
Been complaining about this before the Space outpost and its only gotten worse since that was added.

The lavaland one might be tolerable if it had a GPS beacon and was easier to reach and attack.

**Comment by improvedname** [comment]
>top secret base having a gps

**Comment by ExcessiveUseOfCobblestone** [comment]
@improvedname it's like highly trained stormtroopers tasked with defending the multi-gazillion project known as the death star can't shoot for poo.

**Comment by RandomMarine** [comment]
From an in-character perspective, adding a universally-tracked beacon to a secret recon base is retarded.
From a mechanics standpoint, a pinpoint "VALIDS AND LOOT HERE GET YOUR POWERGAME ON" indication is also stupid.

**Comment by RandomMarine** [comment]
If anything, it's the comms agent's role that should be adjusted.

Having an eye in the sky for traitors that buy an encryption key is nice.
But having an eye in the sky for nuke ops to pinpoint the captain's exact location for a pod drop is a little too much. 

Being able to run gimmicks like making jokes and nonsense over the radio as a ACTION NEWS 13 or Nanotrasen Targeted Advertising is a lot of fun.
But being able to say incriminating phrases with the voice of all the different crew members you want is strongly disruptive of the round.

**Comment by 81Denton** [comment]
Is there a sane way to add weighting to ruin spawns? That would fix the issue without completely removing a role that can be very entertaining if done right.

**Comment by deranging** [comment]
the new syndicate space ruin outpost is much better than the old one because the old one had a vacuum floor as a turf and it killed everyone inside
