### ISSUE TITLE
warp whistle + immortality talisman teleports you back

### ISSUE THREAD

**Issue by AlexTheSysop42** [tgstation/tgstation#35015]
Issue reported from  Round ID: 82611 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reproduction: use immortality talisman, then use warp whistle, wait a few seconds and you'll be teleported back to where you used the talisman.

**Comment by vuonojenmustaturska** [comment]
I'd argue the bug is that warp whistle does anything when you're not there
