### ISSUE TITLE
Clockculties can cross the border in a mech.

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#35043]
[Round ID]: #82669

So, as I was healing, all of a sudden a guy I thought was my ally started drilling a borg to death. He was in a Ripley, and it turned out to be a clock cult member who used the Ripley to cross the border. He killed several people who were unaware he was a clock cultist because he was in a mech. So they didn't see him glow. Also, he was on the side of the non-cultists!

**Comment by francinum** [comment]
Duplicate #35042
