### ISSUE TITLE
Mechs are sitll crossing the crew border for cuck cultists

### ISSUE THREAD

**Issue by YogsMcree** [tgstation/tgstation#35041]
[Round ID]: #  82671

[Reproduction]: Be cuck cultist. Get mech. Walk into portal / walk over crew line. You get sent to crew and can walk greely over the line.

@Xhuis

**Comment by Xhuis** [comment]
this literaly shouldn't happen what the h*ck

**Comment by francinum** [comment]
Dupe #35042
