### ISSUE TITLE
Highlight Strings in GoonChat Aren't being saved.

### ISSUE THREAD

**Issue by Kerbin-Fiber** [tgstation/tgstation#35040]

**Comment by praisenarsie** [comment]
p sure they aren't meant to save?
@Cyberboss

**Comment by Kerbin-Fiber** [comment]
I've had my GoonChat Highlight strings load up every time I open the game on Basil, this past week, however, they've disappeared recently. Now every time I close and re-open the game, on Basil, they're gone and I have to put them in every time I close the game. Even the highlight colour too.
