### ISSUE TITLE
Servant-piloted mechs aren't checked for crew-only areas in reebe

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#35042]
RID: 82669

Production: Get a mech on reebe, be servant, have the arrows break from combat, walk over to the crews side.

**Comment by Xhuis** [comment]
end my sssssssssssssssssssssssssssssssssuffering

**Comment by factoryman942** [comment]
also the barriers can be blown up

**Comment by ShizCalev** [comment]
@Xhuis mech drills call ex_act, from the sound of it that's how they managed to do that.

**Comment by francinum** [comment]
I didn't drill it, but explosions were happening a lot in that area.

**Comment by OmegaShoots** [comment]
@ShizCalev someone tried to maxcap the the walls and in turn caused the crew line barriers to be destroyed
It seems very strange that they are able to be damaged at all.

**Comment by Xhuis** [comment]
They're meant to be indestructible. It was just an oversight that was passed over.

**Comment by YPOQ** [comment]
#33300

**Comment by francinum** [comment]
That's a separate issue.
