### ISSUE TITLE
AI shell and client_mobs_in_contents

### ISSUE THREAD

**Issue by silicons** [tgstation/tgstation#35052]
What..?
![image](https://user-images.githubusercontent.com/2003111/35480386-b111bf2e-03c1-11e8-8dbd-d3a03d75e94f.png)

**Comment by GunHog** [comment]
It could be something in `mind.transfer_to()`. This list is a result of an AI switching between its core and shell over the course of the round. I do not believe it is particularly harmful, but I do not know the exact cause. Something is not being cleared or overwritten properly.

**Comment by timothymtorres** [comment]
The `client_mobs_in_contents` isn't documented anywhere in the codebase.  It could be some old relic code that was forgotten and not really used anymore.  @GunHog is probably correct in that something involving this isn't being cleared or reset properly.

**Comment by Sealed101** [comment]
- can no longer reproduce; possibly resolved as part of #61422
