### ISSUE TITLE
You don't need 10 metal rods to make a Rough Metal Wall, only 2

### ISSUE THREAD

**Issue by deranging** [tgstation/tgstation#35059]
Problem Description: Making a fake Rough Metal Wall, which requires 2 metal rods, can be turned into a real Rough Metal Wall by using a screwdriver on it.

What did you expect to happen: I don't know

What happened instead: Should've gave an error

Why is this bad/What are the consequences: Can be used by griefers to mass produce some strong walls

Steps to reproduce the problem: Make a wall girder with 2 sheets of metal, unsecure it with a wrench, use 2 metal rods on it, use a screwdriver on the fake Rough Metal Wall to make it a real one.

Server: I've been doing it for a while, first found on Citadel, also works here on TG

Revision: I have no idea

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): increase the amount of metal rods needed to make a 

Thanks for helping us out!

**Comment by deranging** [comment]
How I found this out: On a citadel round where I was a clown, the RD PDA'd me that security is arresting him for no reason, and for me to fill security's halls with fake walls. I learnt a few days before that you could turn fake metal walls into real metal walls, and I wanted to try it out with Rough Metal Walls. I decided to try it out and I noticed I create a real Rough Metal Wall

**Comment by uraniummeltdown** [comment]
Using a screwdriver on fake walls to make them real is intended

**Comment by MrStonedOne** [comment]
The bug report is that you can make a rough metal wall with less materials than you are suppose to be able to, you could likely break it down to basically dupe materials as well
