### ISSUE TITLE
You can duplicate bluespace crystals

### ISSUE THREAD

**Issue by Polyphynx** [tgstation/tgstation#35057]
Issue reported from  Round ID: 82693 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

-Upgrade the ORM with a better matter bin
-Smelt a bluespace crystal
-Take out the bluespace mesh from the ORM
-With the mesh in one hand, use an empty hand on it to pick off a piece of refined crystal
-Smelt the refined crystal 

You now have more bluespace than you started with. Repeat infinitely.
![ex4](https://user-images.githubusercontent.com/18168689/35482451-b7b3623c-0435-11e8-960b-5276c28d811c.png)

This doesn't get you more points, just more bluespace.

**Comment by XDTM** [comment]
Why does every material container have recycling functionality now?

**Comment by praisenarsie** [comment]
i blame kevinz

**Comment by deranging** [comment]
kevinz is a coder for citadel and he broke the vore functionality which caused us to be able to clone people with vore

**Comment by Kromgar** [comment]
For fucks sake this was supposed to be fix

**Comment by Polyphynx** [comment]
I think the thing fixed was that the broken off crystal would give mining points. It's still affected by the matter bin upgrades to get more than 1 bluespace mesh out of it.

**Comment by Buggy123** [comment]
Figured this was possible, but didn't bother to test it.

**Comment by RandomMarine** [comment]
ORM upgrades were a mistake.

**Comment by Tlaltecuhtli** [comment]
make the 0 units polycrystal qdel

**Comment by evsey9** [comment]
seems fixed

**Comment by Polyphynx** [comment]
Just tried it out. Still works
![ex5](https://user-images.githubusercontent.com/18168689/36068441-15a1bc90-0ed6-11e8-86ad-44a8edae14ce.png)
