### ISSUE TITLE
The glockenspiel sounds real fucken weird

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#35053]
When you play a song on the glockenspiel the tuning sounds a bit out. Really obvious on Chopin's funeral march.

**Comment by ArcaneMusic** [comment]
It seems more or less fine to me. We recently had a rework of the instruments, so I'd like to hear what @silicons thinks if this is resolved or not.

**Comment by timothymtorres** [comment]
Marking this as `Not a Bug` and it will autoclose in 7 days.
