### ISSUE TITLE
Buildmode Walls break to space

### ISSUE THREAD

**Issue by DaedalusGame** [tgstation/tgstation#35062]
Special Verbs -> Toggle Build Mode Self -> Make some walls -> Deconstruct them in some way -> they have space underneath.

This may be of some interest for admin shenanigans... does anyone even still use buildmode??

**Comment by Marflowerose** [comment]
https://github.com/tgstation/tgstation/issues/33984 Probably related to this and 3 other identical issues

**Comment by DaedalusGame** [comment]
It's caused by the scrape away pr, i believe. They have identical cause but they still affect different things so I think it's good to report any occurence you can find.

**Comment by ninjanomnom** [comment]
this is actually a different cause, shuttle have a special case for why they're happening atm.

**Comment by PKPenguin321** [comment]
>does anyone even still use buildmode??

are you serious? of course
