### ISSUE TITLE
AVG reports runtime condenser as malware

### ISSUE THREAD

**Issue by C-F-K** [tgstation/tgstation#35066]
[Reproduction]:  occurs after pulling latest code with `git pull` while running AVG AntiVirus Free version 17.9.3040, virus definitions version 180127-0.

Seems to be low-urgency since I can still build and deploy the server locally (no DB) with Runtime Condenser.exe in quarantine, but this still is probably not intended behavior.

**Comment by praisenarsie** [comment]
@MrStonedOne

**Comment by vuonojenmustaturska** [comment]
https://www.virustotal.com/#/file/42ea5a319ca391e94e902271d5cd9a23a693b3595f14540fd8e70ced7cecaa75/detection virustotal link for runtime condenser, it's not just avg

**Comment by MrStonedOne** [comment]
what the actual fuck.

**Comment by MrStonedOne** [comment]
![](https://i.imgur.com/z2zfukn.png)

???

**Comment by MrStonedOne** [comment]
I compiled that version in december of this year.

**Comment by MrStonedOne** [comment]
I just noticed that that file still has debugging info attached, meaning it's likely not even optimized. I'll recompile it without debugging info and optimizations and see what happens.

**Comment by MrStonedOne** [comment]
https://www.virustotal.com/#/file/ebc3c53449da66aa2cf7630777ae1ab8f9e6572010b871fc28bd6b6ba19f0090/detection `0/65`

**Comment by optimumtact** [comment]
no antivirus can compete with our bitpackers
