### ISSUE TITLE
Players transformed into catpeople can't have tails removed

### ISSUE THREAD

**Issue by AlexTheSysop42** [tgstation/tgstation#35067]
Issue reported from  Round ID: 82700 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reproduction: get transformation stung with DNA of a catperson (or have some wiz event happen), try to get the tail removed via surgery, see that amputate doesn't show up, nor does the tail in the remove organ menu 

I had to have my brain transferred into a monkeyman to fix it

**Comment by praisenarsie** [comment]
@kevinz000

**Comment by dragomagol** [comment]
Appears to have been fixed.
