### ISSUE TITLE
Shuttle never arrived at centcom.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#35076]
https://atlantaned.space/statbus/round.php?round=82712

Tesla shocked the shuttle like it was Mike Pence at a gay pride parade and it never arrived at centcom.

**Comment by praisenarsie** [comment]
@ninjanomnom

**Comment by Dorsisdwarf** [comment]
possibly destroyed the docking port on the shuttle?

**Comment by Poojawa** [comment]
docking ports are invulnerable tho. Aren't they?
