### ISSUE TITLE
Disposal "CLONG, Clong!" size being based on proximity means you still get logspammed by them if there is lots of clonging, especially with multiple people

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#35084]
CLONG, clong!
CLONG, clong!
CLONG, clong!
CLONG, clong!
CLONG, clong!x2
CLONG, clong!x6
CLONG, clong!x2
CLONG, clong!x3
CLONG, clong!x3
CLONG, clong!x11
is the result of orbiting a person going through disposals clonging along with other people
it stacks up properly when they're at an outlet, since they all go on the same tile

**Comment by MrStonedOne** [comment]
Translation:

TGchat taking size into account when checking for duplicated messages causes it to miss duplicated messages

**Comment by factoryman942** [comment]
yeah

**Comment by praisenarsie** [comment]
we need to make clonging less spammy
