### ISSUE TITLE
Soap has no inhand sprite

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#35089]
Stun weapons without inhands are not good

**Comment by KorPhaeron** [comment]
I'll give an antag token to whoever does the tedious work of making tiny 10 pixel boxes to represent soap in someones hand

**Comment by improvedname** [comment]
AANTAG HERE I COME

**Comment by improvedname** [comment]
In other hand i don't care because paper cups are invinsible too

**Comment by coiax** [comment]
Close this
