### ISSUE TITLE
similar items get stacked on the same slot in bags like trashbags, and chembags

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#35098]
like spent and unused shells, bottles with different naems, pills, all get stacked in 1 single slot

**Comment by Buggy123** [comment]
Yes, this is quite annoying. Have a chembag with a bunch of different kinds of pills and they all merge into 1 stack.

**Comment by Shirbu** [comment]
I wanna say that the issue stems from this section in the code:

tgstation/code/game/objects/items/storage/storage.dm

`if(ND.sample_object.type == I.type)
					ND.number++
					found = 1
					break
			if(!found)
				adjusted_contents++
				numbered_contents.Add( new/datum/numbered_display(I) )`

not sure tho, can't read this shit

**Comment by kriskog** [comment]
I changed this
