### ISSUE TITLE
Notes for ckey randomization don't get placed anymore

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation#35096]
According to MSO this has been broken since 22/01/2018

22:45 <%MrStonedOne> stopped 2018-01-22 08:17:06

**Comment by optimumtact** [comment]
@Jordie0608 @MrStonedOne @tgstation/commit-access

**Comment by MrStonedOne** [comment]
This is just getting even more confusing because none of the related lines of code have changed in that time.

**Comment by Jordie0608** [comment]
Ha ha what.

**Comment by Iamgoofball** [comment]
its been 4 years, reopen if real, otherwise it stays closed
