### ISSUE TITLE
Camera Consoles Broken

### ISSUE THREAD

**Issue by halitosisman** [tgstation/tgstation#35091]
Issue reported from  Round ID: 82726 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Issue first occurred on BYOND 1405. 

[Reproduction]: # Clicking on the syndicate or the xenobiology camera console crashes the client. Also, I don't know if this is intended, but the link on the server website does not allow me to connect while on BYOND's stable branch.

**Comment by SpaceManiac** [comment]
Reproduced with 512.1405 client on 1403 server, immediate hang upon clicking xenobio console.

**Comment by ShizCalev** [comment]
Moved into the mega thread.
