### ISSUE TITLE
Alien Alloy can't be researched, even once you scan it

### ISSUE THREAD

**Issue by AlexTheSysop42** [tgstation/tgstation#35102]
Reproduction: find abductor ruin, take stuff back to station, reveal abductor base node, notice that it has a prerequisite that you can't see or something (point requirement is red)

**Comment by vuonojenmustaturska** [comment]
@kevinz000

**Comment by praisenarsie** [comment]
techwebs has been unfinished for how long?

**Comment by Buggy123** [comment]
Weird, I've done this before and it works, researched the tech just fine (though, I took multiple tools and revealed all 3 abductor nodes at once).
I've also done it before, and had it not work...

@kevinz000

**Comment by YPOQ** [comment]
#33097

**Comment by ShizCalev** [comment]
Duplicate of #33097
