### ISSUE TITLE
Pipe Fingerprints are not transferred to constructed pipes

### ISSUE THREAD

**Issue by Poojawa** [tgstation/tgstation#35101]
Discovered today and actually *looked* into just now of this posting, but while #31072 ensures the _item_ of `/obj/item/pipe/binary/bendable` gets fingerprints when you unwrench it or waggle it around, wrenching in a pipe destroys the fingerprint, returning a null in `/obj/machinery/atmospherics/pipe/simple`

[Reproduction]: #  Aquire section of pipe, lay it on the floor, wrench it in. Observe that you have no fingerprints. There is also no investigation log report for wrenching a pipe in.

Unwrench pipe section. New pipe that's generated/returned to be picked up/thrown has fingerprints as intended, it also applies a ``08:46:22 [0x201183c] (123,100,2) || the pipe was REMOVED by Poojawa/(Drone (70))`` tag in the investigation log

I was having issues hunting down someone's nefarious atmosia piping until I got their prints... off of the glass window they built over it to hide the connection. 

Maybe it just needs a bit of transfer_fingerprints_to(stored) or sommat as well when constructed, or however the interaction is handled.

**Comment by praisenarsie** [comment]
@duncathan @kevinz000

**Comment by Poojawa** [comment]
also sometime if the investigate logs can get shiney'd up like the Runtime log viewer, that'd be amazing.
