### ISSUE TITLE
Attacks by players on occupied mechs are not logged

### ISSUE THREAD

**Issue by feemjmeem** [tgstation/tgstation#35119]
It does not appear that attack.txt gets attack logs of players beating up on mechs. If I'm missing it let me know, but otherwise it's difficult to investigate issues post-hoc.

**Comment by TiviPlus** [comment]
![image](https://user-images.githubusercontent.com/57223640/131701898-600423e9-f251-47c2-89a7-db4a52c2d797.png)
Fixed, likely by one of the mech refactors
