### ISSUE TITLE
Spamming deconstruction on a girder grants you Star Platinum powers

### ISSUE THREAD

**Issue by Togopalis** [tgstation/tgstation#35111]
When you spam deconstruction on a girder and switch to harm intent you are capable of hitting something as much times as you started deconstruction, simultaneously.

[Reproduction]: Start deconstructing a girder with a wrench a lot of times, then switch to harm intent and hit it before the progress bar is filled.

**Comment by Spaceinaba** [comment]
so this is the power of your stand

**Comment by evsey9** [comment]
feature

**Comment by arsserpentarium** [comment]
feature

**Comment by ExcessiveUseOfCobblestone** [comment]
this is funny.

**Comment by Togopalis** [comment]
You're funny

**Comment by Tlaltecuhtli** [comment]
couldnt reproduce

**Comment by kriskog** [comment]
Can't reproduce
