### ISSUE TITLE
Lumious Slime Powers Can be Spammed

### ISSUE THREAD

**Issue by Sven-Grey** [tgstation/tgstation#35123]
Issue reported from  Round ID: 82770 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

[Reproduction]: 
1. Use xenobio to become a Luminous Slime
2. Absorb a slime core that has a power with some sort of activation time. For example, gold cores take a few seconds to activate to spawn a hostile/neutral mob.
3. Spam your ability as fast as you can. You should see multiple "progress bars" above your head
4. When each progress bar fills, it will complete the activation of your power. In the example of gold slimes, you will have many MANY MANY mobs now surrounding you.

This apparently works with the other powers, so long as there is a activation time such as the ZA WURADO luminous slime power.

**Comment by AnturK** [comment]
@XDTM

**Comment by XDTM** [comment]
Damn i didn't think of that, will fix asap
