### ISSUE TITLE
Lights and only lights do not work in the abandoned teleporter.

### ISSUE THREAD

**Issue by Teepeepee** [tgstation/tgstation#35129]
I have tried this in many rounds, one time I even got an answer from an admin after praying, its weird cause APCs, air alarms, station intercomms, fire alarms, machines, consoles and AI cameras work, its just light fixtures and floodlights which refuse to get put on the wall (light frames, it says "that can't be built in this area!" like it would say in a non defined area) or it just never turns on (floodlights). Please fix so I can go hide from antags in my autism base and invite others once I make it habitable :3

**Comment by ShizCalev** [comment]
Just checking, did you have a wire node underneath the floodlight? Those are required for them to turn on.

**Comment by Teepeepee** [comment]
I did, checked many times and it still didn't work.
