### ISSUE TITLE
morphs that have turned into status displays keep the numbers on them when they un-morph

### ISSUE THREAD

**Issue by Plapatin** [tgstation/tgstation#35135]
Issue reported from  Round ID: 82791 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

![image](https://user-images.githubusercontent.com/25095454/35562575-a6ee912c-0568-11e8-9dbf-2c773217cfdf.png)
Easily fixed by transforming into something else, however it's very unnerving to see a morph running around with "EAT PANT" affixed to it's body

[Reproduction]:
1. Be morph.
2. Transform into status display with something on it.
3. Un-transform.

**Comment by Togopalis** [comment]
Feature

**Comment by epicmemename** [comment]
feature?
