### ISSUE TITLE
Syndicate ship control only has 1 location

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#35174]
pretty sure it always had 4, but now it only got 1 location to "choose" from
I am talking about the one where you click northeast etc. not the one where you can place it.

**Comment by Cruix** [comment]
This was removed by #32579

**Comment by praisenarsie** [comment]
^

because you can choose a custom location now however since 512 brogged cameras and now 512 brogged itself idek anymore

**Comment by improvedname** [comment]
Why didnt we just keep the 4 what was the issue really lol

**Comment by ShizCalev** [comment]
@improvedname meta.

**Comment by LetterN** [comment]
why are you using 512 anyways
