### ISSUE TITLE
Electrical Terminals cannot be constructed piecemeal

### ISSUE THREAD

**Issue by svokar** [tgstation/tgstation#35189]
Round ID: 82869

"Feature" discovered when trying to move the electrical terminal on the 'Challenge Station' (Old Cryogenics Pod spawner).
Cut the terminal going to the 'Backup Power Storage Unit' SMES (power in) using wirecutters. Discovered that I was unable to rebuild the terminal. aHelped BeeSting12 to let him know the issue, then came here to the TG github to find the recipe in the modules. Found out that terminals are only 'spawned' when an APC is built. 

Direct from '[tgstation/code/modules/power/terminal.dm](https://github.com/tgstation/tgstation/blob/master/code/modules/power/terminal.dm)'
`// the underfloor wiring terminal for the APC`
`// autogenerated when an APC is placed`

Is it possible to create a recipe for these?

Only issue I can see is if an antag runs around and cuts all the terminals under the APCs, causing rolling power failure. Nobody is going to know how to make them magically re-appear. 

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by factoryman942** [comment]
apc terminals can be made by using cable coil on an apc frame which has been unlocked & opened w/ crowbar
smes terminals can be made by standing adjacent (not diagonal) to the smes, with it screwdrivered open, and using cable coil on it
