### ISSUE TITLE
Phobia trauma can be triggered by names

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#35180]
If someone who has a word that triggers your phobia in their name says something unrelated, you will get triggered

**Comment by Tlaltecuhtli** [comment]
seems intended whats the issue?

**Comment by Tlaltecuhtli** [comment]
if a lizard call itself big-snake-in-pants it should trigger the phobia

**Comment by coiax** [comment]
I ended up scared of snakes, and every time Snake Eater spoke on the radio, I had a nervous breakdown

**Comment by Ordonis** [comment]
To be fair, that's a reasonable response to most of what Snake Eater says.
