### ISSUE TITLE
Ancient Goliaths still spread tendrils even when dead

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#35197]
The only way to stop the tendrils is to butcher it

**Comment by Buggy123** [comment]
You found one of mining's greatest secrets...

# AND YOU MADE A ISSUE REPORT?!

**Comment by Kromgar** [comment]
Why is it a treasured secret?

**Comment by Buggy123** [comment]
Because its funny as fuck and no one suspects it.

Welp, check another off the list I guess

 - ~~Hiding ancient goliath corpses.~~
 - ~~Jaunting megafauna to the station.~~
 - The secret lavaland-only server crashing technique

**Comment by Kromgar** [comment]
@Buggy123 instead lure blood drunk miner mwahahahahah
