### ISSUE TITLE
space ruins seem to stack on each other

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#35206]
82909 bagil

![image](https://user-images.githubusercontent.com/222630/50525317-8c2ef700-0a8f-11e9-97a5-2f7963d71229.png)

**Comment by praisenarsie** [comment]
@SpaceManiac is this ztraits' fault

**Comment by SpaceManiac** [comment]
#35170 made the whiteship a ruin which caused this particular screenshot but space ruins have been stacking for some time, e.g. the thing a few months back where the pulse rifle spawned inside of oldstation.

**Comment by Kromgar** [comment]
Oh god i forgot that fucking meme of a single space tile with a pulse rifle in space was a thing

**Comment by AnturK** [comment]
The pulse rifle is feasible because the solars might have been simple space area, really not sure how the OP happened though.

**Comment by SpaceManiac** [comment]
Seems you're right that the solars are space area. I think I have some idea about the OP which is if the whiteship dock was placed first, then oldstation was placed over the space tiles surrounding the dock, then the whiteship was loaded in by the shuttle subsystem. Not sure how to best prevent that.

**Comment by AnturK** [comment]
I added adding NO_RUINS to turfs loaded through ruin generator in #35209, not the cleanest solution but should prevent the most obvious issues.

**Comment by SpaceManiac** [comment]
Fixed by #35209
