### ISSUE TITLE
You discreetly slip the survival knife into /datum/component/storage/concrete/pockets/shoes. Alt-click /datum/component/storage/concrete/pockets/shoes to remove it.

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#35203]
Issue reported from  Round ID: 82901 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

![image](https://user-images.githubusercontent.com/6778786/35687584-20ace830-073d-11e8-8ac8-b9479086b6d7.png)

**Comment by praisenarsie** [comment]
@kevinz000

**Comment by Xhuis** [comment]
This is an issue with the testmerge #33166 and should be posted there, not on the issue tracker.

**Comment by AnturK** [comment]
#33166
