### ISSUE TITLE
Cyborgs can remove light tubes from a distance 

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#35211]
[Round ID]: 82912

**Comment by DaxDupont** [comment]
...with what

**Comment by Anonmare** [comment]
Go play a cyborg and click on a light tube with no module selected while standing away from it

You'll take it out of the fixture.

**Comment by DaxDupont** [comment]
Thanks, that really should've been in your issue description.

**Comment by Anonmare** [comment]
I figure it would be self-explanatory

**Comment by DaxDupont** [comment]
It's really not when you consider the fact that janiborgs have light replacers and I figured that's what your on about.

Clicking on lights should turn them off as a cyborg. That was the old behaviour.

**Comment by DaxDupont** [comment]
Can't replicate this.
Clicking them from a distance or close produces:
Emergency lights for this fixture have been enabled.
Emergency lights for this fixture have been disabled.

But no bulb.

**Comment by DaxDupont** [comment]
Got a round id or something?
Might be https://github.com/tgstation/tgstation/pull/33166 related

**Comment by Anonmare** [comment]
It should have shown up but I guess it didn't

89219 it was I believe.

**Comment by DaxDupont** [comment]
https://github.com/tgstation/tgstation/pull/33166 related, please post it there. this can be closed I think
