### ISSUE TITLE
Creating a new area while on the shuttle results in the area being left behind

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#35222]
![dreamseeker_2018-02-02_12-44-20](https://user-images.githubusercontent.com/12747768/35731981-046b3d62-0818-11e8-9862-e6eda5270a2b.png)

The suggested solution would be to block people from creating new areas or using station schematics in any way while on the shuttle. Which I actually assumed would be already the case.

**Comment by DaxDupont** [comment]
new hijack meta

**Comment by AlexTheSysop42** [comment]
this isnt fixed?

**Comment by praisenarsie** [comment]
@ninjanomnom

**Comment by Jalleo** [comment]
@Slignerd the feature was removed https://github.com/tgstation/tgstation/pull/35049 please close this issue report

**Comment by Slignerd** [comment]
Check the dates. The issue evidently persisted.

**Comment by Jalleo** [comment]
Ah well I thought it was a accidental repeat after it was merged due to being on a server that wasn't updated yet.
