### ISSUE TITLE
Morgue is not functioning properly

### ISSUE THREAD

**Issue by Sunoplyrus** [tgstation/tgstation#35225]
Issue reported from  Round ID: 82948 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
Reporting client version: 511

![2018-02-02_10-37-57](https://user-images.githubusercontent.com/31968974/35735978-a267ce00-080d-11e8-9837-52d2f4436e0d.gif)
Above: Brainless
Middle: Recently deceased
Under: Lifeless brain

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/bb8fec8b6d5d461b64493678acdc0281cfa56db7/code/game/objects/structures/morgue.dm#L165

he forgot M.client

**Comment by ExcessiveUseOfCobblestone** [comment]
oh wait I can just do that on the webbitor
