### ISSUE TITLE
roundstart_template contains an invalid value

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#35226]
@coiax 
roundstart_template contains an invalid value because it's not wrapped.
Ergo if you open and save in dreammaker 
roundstart_template = /datum/map_template/shuttle/arrival/box;
turns into
roundstart_template = !INVALID_VALUE!;
However if you try to wrap it in "" the loading functionality breaks

**Comment by MrStonedOne** [comment]
```dm
"c" = (/obj{mouse_drag_pointer = /turf},/turf,/area)
```
I made this with dream maker, saved with dream maker

you likely unchecked a file accidentally in your project causing it to be unable to find that path.

**Comment by DaxDupont** [comment]
I think it's because of the mapmerge thing

**Comment by MrStonedOne** [comment]
@tgstation/commit-access keep an eye out for this bug on prs over the next few days.

It was a map key overflow causing byond to mis read the value, its fixed in #35133 but people who map merge while on a branch from before that was merged will have issues.
