### ISSUE TITLE
Cobwebs are immune to blobs

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#35229]
![image](https://user-images.githubusercontent.com/609465/35747078-e9309320-0840-11e8-92ab-ad92822e54b2.png)

Round ID: 82956

**Comment by ShizCalev** [comment]
feature, even blobs cannot stop cobwebs.

**Comment by GunHog** [comment]
I do not see the problem, if the webs do not actually obstruct or affect the blob. I thought you were talking about the webs that slows down human movement acting as an unbreakable barrier.
