### ISSUE TITLE
Airlock painter doesn't work

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#35223]
The painter just doesn't work at all. You use it on a door, get a prompt asking you to choose the paintjob, then nothing happens.

**Comment by praisenarsie** [comment]
@uraniummeltdown didn't you mess with airlock stuff a while back?

**Comment by uraniummeltdown** [comment]
![](https://www.leadingagile.com/wp-content/uploads/2017/03/worksonmymachine.png)

**Comment by Mark9013100** [comment]
Airlock painter is broken on my end.

**Comment by Tlaltecuhtli** [comment]
reproduced on current bagil
http://take.ms/YovZD

**Comment by kriskog** [comment]
Seem to work fine now.
