### ISSUE TITLE
CE on meta is fucked over by turrets

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#35231]
\>be me
\>ce
\>shit tcomms are down
\>go to ai sat
\>walk up to turret console
\>no access
\>have to sprint past the two taser turrets guarding the tcomms room
\>get stunned for 10 seconds
\>fix tcomms
\>get stunned for like another 10 seconds
\>reflect on life while on the ground

**Comment by Spaceinaba** [comment]
the best part is how the AI sat is right next to engineering and the only guy who has a reason to go over there cant turn the guns off

**Comment by DEATHRATTLERS** [comment]
get better

**Comment by Anonmare** [comment]
Sounds like a bug as I distinctly remember the CE having access to that turret panel

**Comment by CPTANT** [comment]
CE hasn't had access to those turrets for ages. Should be fixed though.
