### ISSUE TITLE
Cyborgs can control-click broken APCs back online

### ISSUE THREAD

**Issue by YPOQ** [tgstation/tgstation#35257]
1. Break an APC, power to the area is disabled as expected.
2. Control click broken APC as a cyborg (probably AI too), power to the area is restored.

Local server, ce50d105

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/647ea873a30e243193bcf1d8a0fb33466bf117f5/code/modules/power/apc.dm#L914

https://github.com/tgstation/tgstation/blob/647ea873a30e243193bcf1d8a0fb33466bf117f5/code/_onclick/ai.dm#L166

missing checks to see if it's damaged.
