### ISSUE TITLE
Mirror Shield blocking too many things

### ISSUE THREAD

**Issue by YogsMcree** [tgstation/tgstation#35255]
[Round ID]: # (82980

[Testmerges]: # The following pull requests are currently test merged:
#35188: 'Adds a SCP-294 ruin' by MoreRobustThanYou at commit 67f90d
#35095: 'Adds new helper: use_tool, shakes things up in tool code' by ACCount12 at commit cba93c

[Reproduction]: I watched at roundend a mirror shield block an SRM-8 track missile. Now, I dont know about you, BUT MIRRORS DONT BLOCK MISSILES MY DUDE. These also block far too much melee, since they offer complete immunity to the main weapon type of security, energy weapons. They need to be toned down very heavily. But also i think they are intended to be broken by slugs / .357 / SRM MISSILES

**Comment by Tlaltecuhtli** [comment]
its a magic shield

**Comment by Potato-Masher** [comment]
If slugs break it, fucking missiles should. I'm not sure how Robustin managed to make an item arguably better than the Bastard Sword. 

>knock over 4 crewmembers and myself with one throw of captain america's shield

**Comment by Robustin** [comment]
Hilarious.

But yea this is a shield thing not a mirror shield thing.

**Comment by AlexTheSysop42** [comment]
is this still an issue
