### ISSUE TITLE
Scanning multiple slimes gives a result that's nearly impossible to read

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#35262]
![dreamseeker_2018-02-03_14-11-41](https://user-images.githubusercontent.com/12747768/35767417-3777d47a-08ec-11e8-938f-959a04c9cb67.png)

It's difficult to tell at first glance where one slime's scan result ends and where another begins

**Comment by Tlaltecuhtli** [comment]
make the name bold

**Comment by Slignerd** [comment]
"Slime scan results" should be emphasized somehow too

**Comment by Slignerd** [comment]
I think "Feedback" would be an appropriate label

**Comment by GunHog** [comment]
Add bolding to the name, and a space between entries.
