### ISSUE TITLE
Blood packs have question marks

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#35279]
Issue reported from  Round ID: 83027 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

![l2lbemm 1](https://user-images.githubusercontent.com/17237624/35772586-b4ab2202-0942-11e8-8478-8c3edd2e1354.png)

**Comment by praisenarsie** [comment]
@ShizCalev

**Comment by ShizCalev** [comment]
well that's new.

**Comment by ShizCalev** [comment]
@nicbn #35087

**Comment by nicbn** [comment]
I don't think I caused it

**Comment by ShizCalev** [comment]
@nicbn You changed it to > 0, previous was 0 = empty.
