### ISSUE TITLE
Deconstructing any part of the aux base after deployment makes rock walls

### ISSUE THREAD

**Issue by DaedalusGame** [tgstation/tgstation#35276]
Round ID: 82966

Reproduction: We blind-launched the base and then started expanding it for a few hours. Anytime we deconstructed a wall on the aux base an intact rock wall would replace it, and later an ash walker bombed the aux base with a fireball staff, and half the base was turned into rock walls.

**Comment by GunHog** [comment]
I am guessing that is because the rock was the turf the Aux Base replaced upon landing.
