### ISSUE TITLE
Body temperature should probably be tweaked to be a little more sane

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#35278]
Note: this all assumes that "body temperature" is the internal temperature of a person, not external.

My main issue is things like this:
![image](https://user-images.githubusercontent.com/16315400/35772346-42363d34-090a-11e8-81d3-a1167d0a1270.png)
So, this person was in a fire but got dragged out just as they entered crit. Someone had some ointment, and about a second after this picture they used it and he got up and limped to medbay. Nothing wrong there balance-wise. But, I have issues with this:

![image](https://user-images.githubusercontent.com/16315400/35772352-706ab982-090a-11e8-8a98-f70590327441.png)

Yes, 2000°C. Their entire body was heated to **two thousand degrees Celsius**. Ointment will not help you if your entire body is heated to 2000°C. You can't live for 10 seconds at 2000°C. You can't live for a TENTH of a second at 2000°C. The highest temperature any known form of life can survive at is slightly over 100°C.

At that temperature, every single molecule of water in your body would instantly boil into superheated steam. A not-insubstantial portion would break down into hydrogen and oxygen purely due to the sheer temperature.

Setting aside the fact that every cell in your body suddenly exploded with the combined force to rival a actual bomb, nearly every single organic molecule in your body would denature instantly. Every single thing remotely resembling something which results in life would instantly break apart into useless pieces and in many cases would also boil into a gas.

I am struggling to imagine any sort of life that could survive at that temperature, without dying and/or exploding at normal temperatures.

And lets set aside the fact that you can reach near-absolute-zero and still move around. Simply put, we should tweak values at least a little so that body temperatures aren't absolute insanity, preferably without altering balance in any way.

**Comment by Kromgar** [comment]
hard to do considering plasma fires can be hotter than the fucking sun

**Comment by nicbn** [comment]
Just make fires colder and more dangerous

**Comment by Poojawa** [comment]
Human beings can melt steel beams.

**Comment by AlexTheSysop42** [comment]
> plasma fires can be hotter than the sun

The sun is something like 2 MILLION degrees (or more), why do people keep saying this?

**Comment by Buggy123** [comment]
Depends on where you look, they can absolutely be hotter than the surface of the sun.

**Comment by nicbn** [comment]
No the sun is 6000 Kelvin on surface

**Comment by DaedalusGame** [comment]
This is the truth, and it's also the white point, or standard temperature of plasma fires

**Comment by Dorsisdwarf** [comment]
This is a feature request, isnt it

**Comment by ExcessiveUseOfCobblestone** [comment]
MUH REALISM

**Comment by Buggy123** [comment]
WTB photorealistic simulation ss13 where you mess up with a blowtorch and go permanently blind and have to spend real months recovering from severe burns.

**Comment by PKPenguin321** [comment]
How do you suggest we fix this? Gameplay wise it works fine. Should the internal temperature just be capped at some point?

**Comment by Poojawa** [comment]
Obviously you shouldn't be going below zero.

And burn damage applied when you'd be getting frostbite or, y'know, melting would be good. Make clothes actually effect insulation in general per limb it's covering.

**Comment by PKPenguin321** [comment]
>And burn damage applied when you'd be getting frostbite or, y'know, melting would be good.

but this happens. if you want a "realistic" fix we could just make you dust when you get too hot but that's a massive balance change for a feature freeze
