### ISSUE TITLE
"You require 8 more cultists" spam on Nar-Sie Rune.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#35287]
Issue reported from  Round ID: 83038 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

So, this happened when I panic spammed the rune with 7 people on it.

![image](https://user-images.githubusercontent.com/33107541/35773652-3ca23294-0926-11e8-94f6-04dec5c33ba1.png)

**Comment by DaxDupont** [comment]
...so you spam clicked it and you're surprised it spammed you?

**Comment by Robustin** [comment]
Hes talking about it saying he needed 8 more when he only needed 2 more.

I've verified this bug and im trying to figure it out.
