### ISSUE TITLE
Removing a reinforced floor duplicates rods infinitely

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#35280]
Step 1: make reinforced floor
Step 2: crowbar it up. The reinforced floor is not deleted but it creates rods
Step 3: infinite metal.

Roundid: 83030

**Comment by Robustin** [comment]
Technically youre supposed to wrench reinforced floors to remove them, this just inexplicably creates rods despite using the wrong tool.

**Comment by Mey-Ha-Zah** [comment]
So that was what the drone was doing

**Comment by JigenEagle** [comment]
I can confirm this happens with both the Jaws of Life and all variants of crowbar.
