### ISSUE TITLE
Mime's bottle of nothing failing to heal if turned into a hulk

### ISSUE THREAD

**Issue by OmegaShoots** [tgstation/tgstation#35297]
Round ID: 83044

Got cloned and went to genetics to get powers and got the whole package.
Later on on the shuttle with a few seconds left, got shot up and wanted to use my Nothing to heal me, only to see it's not doing anything and I'm still in near critical condition.

Post round I take a few more swigs while in near crit, 10-20 seconds go by and my health is still in blinking red, and get caught on fire and crit out.

Seems that Nothing doesn't work if you get turned into a hulk.

**Comment by Spaceinaba** [comment]
feature due to the mime's IC mental conflict between hulks only being able to yell and mimes being required not to speak

**Comment by ExcessiveUseOfCobblestone** [comment]
why does it check job and not miming wtfffffff.
