### ISSUE TITLE
IC Grabbers not updating inventory properly

### ISSUE THREAD

**Issue by halitosisman** [tgstation/tgstation#35298]
Issue reported from  Round ID: 83048 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

{"assembly":{"type":"type-b electronic mechanism","opened":1},"components":[{"type":"ranged sensor"},{"type":"examiner"},{"type":"thrower","inputs":[[1,0,2],[2,0,2]]},{"type":"number pad"},{"type":"two pulse demultiplexer","inputs":[[1,0,2]]},{"type":"beeper circuit","inputs":[[1,0,"beep"],[2,0,3]]},{"type":"beeper circuit","inputs":[[1,0,"chime"],[2,0,3]]},{"type":"text-to-speech circuit","inputs":[[1,0,"examine"]]},{"type":"text-to-speech circuit"},{"type":"grabber","inputs":[[2,0,1]]}],"wires":[[[1,"O",1],[2,"I",1]],[[1,"O",1],[10,"I",1]],[[1,"A",1],[2,"A",1]],[[2,"O",3],[3,"I",1]],[[2,"O",4],[3,"I",2]],[[2,"A",2],[5,"A",1]],[[2,"A",2],[8,"A",1]],[[3,"I",3],[10,"O",1]],[[3,"A",1],[5,"A",3]],[[4,"O",1],[5,"I",1]],[[5,"A",2],[6,"A",1]],[[5,"A",2],[10,"A",1]],[[5,"A",3],[7,"A",1]]]}

[Reproduction]: This circuit is designed to pick things up with a grabber and throw them. The grabber part does not update its contents list after a thrower removes an item stored in it.

**Comment by arsserpentarium** [comment]
I know,but didn't know,how to fix it yet without snowflakes.
