### ISSUE TITLE
Defibillator mounts glitch out

### ISSUE THREAD

**Issue by Togopalis** [tgstation/tgstation#35312]
If you put a defibillator on a mount and try to take the paddles off from it, you get the entire defibillator instead. It doesn't count as removing the defibillator from the mount, and will give you an inhand sprite AND the wall mounted sprite will stay the same.

**Comment by SpaceManiac** [comment]
Round ID? Testmerges? Unable to reproduce on 82f61efcbbc6183e3bb1cccce1c943c8346914b5.
