### ISSUE TITLE
neutrition update ruins xenobio

### ISSUE THREAD

**Issue by ayyourboibilly** [tgstation/tgstation#35318]
[Testmerges]: it was originally a test merge but I cant find it on the pull request page

[Reproduction]: # Slimes require a ton of food to split this makes xenobio repetitive and boring

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by AlexTheSysop42** [comment]
Pretty sure it was that one that gave players a random amount of starting nutrition, the effects _should_ go away after the first split

**Comment by ayyourboibilly** [comment]
It still happens after the first split but it completely makes xenobiology hard to do

**Comment by newfren** [comment]
Yeah I'm pretty sure when the slime splits the baby slimes also have a random amount of nutrition so they'll take a load of monkeys to grow as well.

**Comment by ayyourboibilly** [comment]
Yeah it honestly caused all of the xenobiologists on bagil and sybil to quit and just spam monkies in a cell

**Comment by chesse20** [comment]
FIX THIS NAOW

**Comment by 81Denton** [comment]
Is this still an issue? #35085 got merged a while ago.

**Comment by Jalleo** [comment]
No this is fixed it can be closed.

**Comment by XDTM** [comment]
close pls
