### ISSUE TITLE
Meatspiked monkey attacked with kitchen knife causes crashes

### ISSUE THREAD

**Issue by ChuckTheSheep** [tgstation/tgstation#35314]
[Round ID]: # 83073
[Round ID]: # 83073
[Round ID]: # 83073

[Reproduction]: Strung up a dead monkey onto the meat spike, with friendly intent attacked it with a kitchen knife, instantly crashed twice.

**Comment by 81Denton** [comment]
Had the same issue when attacking a non-restrained monkey with a kitchen knife. Pretty inconsistent since I crashed twice but nothing happened afterwards.

**Comment by DaxDupont** [comment]
What version of byond, this is important to mention when crashing

**Comment by 81Denton** [comment]
512.1401 for me

**Comment by DaxDupont** [comment]
512 crashes constantly

**Comment by DaxDupont** [comment]
https://github.com/tgstation/tgstation/issues/34862

**Comment by ChuckTheSheep** [comment]
512.1403 for me.

**Comment by Jalleo** [comment]
@MrStonedOne I presume this is fixed now?

**Comment by kriskog** [comment]
Can't reproduce, havent seen or heard of it live. Assume fixed.
