### ISSUE TITLE
syndicate ambush ruin shuttles can't be piloted

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#35315]
when using the shuttle consoles, all it said was that it was missing? @WJohn 

it wasn't working on any of the ships I tried. i had an ID with syndicate access and stuff as well. on another note, the turrets target people with syndicate ID cards which I dunno if its intentional or not.

**Comment by 81Denton** [comment]
It was working about a week ago, wish I had any proper data.

Had it happen to me yesterday on the repairable freighter - right now the main console says missing, the nav console doesn't work at all.

**Comment by ayyourboibilly** [comment]
I believe you have to emag the pilotable ones
