### ISSUE TITLE
Asteroid sand spawned on lavaland somehow

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#35326]
![image](https://user-images.githubusercontent.com/16315400/35784625-c6834bee-09e7-11e8-8073-cd7ff89356ff.png)
Roundid: 83089
![image](https://user-images.githubusercontent.com/16315400/35784631-d7826c90-09e7-11e8-9d68-89721a50eb1f.png)

**Comment by Kromgar** [comment]
I saw this once at the border of clown ruin

**Comment by kriskog** [comment]
See comments on #37100 for some more info.
