### ISSUE TITLE
Ratvarian chairspins are laggy as shit when done in mass.

### ISSUE THREAD

**Issue by chaoko99** [tgstation/tgstation#35338]
I don't actually have video on hand for this, but chairspinning ratvar chairs will make them spin forever, causing a CRAPTON of lag and time dialation, allowing them to summon Ratvar rather quickly with little crew action being taken.

Proposed solution; flick a spinning chair *animation* until someone buckles in, at which point it may defer to the old behavior, only stopping once they unbuckle, then falling back to the previous animation.

**Comment by MMMiracles** [comment]
mass-spinning chairs to warp time itself 

is this tactical chairs 2.0?

**Comment by Kromgar** [comment]
ITS ALSO NOISY AS FUCK AND GOD AWFUL

**Comment by praisenarsie** [comment]
@Xhuis

**Comment by DaxDupont** [comment]
How the fuck does this generate lag

**Comment by Buggy123** [comment]
That's honestly a really good question.

**Comment by AlexTheSysop42** [comment]
> warp time itself

I mean this _is_ a clock god's chairs we're talking about here

**Comment by Buggy123** [comment]
S U P E R I O R  R A T V A R I A N  T E C H N O L O G Y

**Comment by praisenarsie** [comment]
it probably doesn't generate lag but is annoying with the sounds

**Comment by ChangelingRain** [comment]
this is not my fault blame xhuis for autospinning chairs

**Comment by Xhuis** [comment]
REEEEEEEEEEEEEEE HOW DO YOU PEOPLE MANAGE TO BREAK EVERYTHING????

**Comment by Buggy123** [comment]
You have no idea Xhuis, no idea.
![](https://static1.squarespace.com/static/59038f2c440243a0d4b45f4c/t/5945a39903596eab7720991d/1497736192100/?format=750w)

**Comment by DaedalusGame** [comment]
this is surely a feature

**Comment by AlexTheSysop42** [comment]
>tactical chairs 2.0

what was 1.0?

**Comment by AdamElTablawy** [comment]
it's a feature, the chairs spin counterclockwise to time

**Comment by PKPenguin321** [comment]
@AlexTheSysop42 standing on top of a chair that was facing up so that it would cover 99% of your sprite preventing you from being clicked on
