### ISSUE TITLE
sheets of ash only making one brick

### ISSUE THREAD

**Issue by JerryTheCool** [tgstation/tgstation#35336]
when you make bricks from say 5 ash in a sheet, you'll only get one sand block instead of the 5 you're supposed to get

**Comment by arsserpentarium** [comment]
how you even make blocks from ash?

**Comment by DaedalusGame** [comment]
you click on them inhand

**Comment by arsserpentarium** [comment]
how can I get sheet of ash?

**Comment by DaedalusGame** [comment]
you dig up ash and click it in your hand to make sandstone

**Comment by vuonojenmustaturska** [comment]
oh, easy fix, sec
