### ISSUE TITLE
Rats spawn on RuntimeStation

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#35347]
this is annoying for testing purposes when you need power

**Comment by Spaceinaba** [comment]
rattime station

**Comment by DaxDupont** [comment]
Solution: Spawn snakes on runtime station

**Comment by DaxDupont** [comment]
Also iirc this a config option

**Comment by SpaceManiac** [comment]
IIRC the generators on runtime station are not even wired, maybe that should be fixed too.

**Comment by Cyberboss** [comment]
This is a config option
