### ISSUE TITLE
Low pressure icon does not go away

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#35357]
Issue reported from  Round ID: 83126 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

If you enter a really low pressure area and then go somewhere safe, the icon doesn't go away like ever.

**Comment by Buggy123** [comment]
Have had similar issues with the low temperature icon - mainly on lavaland, getting hit by a watcher stare (freezes you), and then using a hivelord core (procs revive) will not clear the low temperature icon.
