### ISSUE TITLE
Blood contract failed to bring up victim selection

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#35366]
Issue reported from  Round ID: 83120 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 511

[Reproduction]: Got a blood contract dropped from bubblegum.  I could of sworn i opened the panel at one point but cancelled it to use it later(But i'm not sure). I then put it in my bag of holding and ran back to the station. When i tried to use it i didn't get a screen. Restarted ss13 and still no selection screen appeared. Might have to do with the recent blood contract bug fix?

Admin said they were unable to reproduce with testing in thunderdome but that was with an adminspawned one

**Comment by Buggy123** [comment]
I also had this same issue, but I don't remember the exact circumstances of it or the roundid.
