### ISSUE TITLE
You can block stuff in Suit Storage Unit, preventing removal of them from that unit.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#35382]
[Reproduction]:You can block all items in Suit Storage, if you will press Open button and Lock button fast enough. You will not be able to unlock it in any ways, but destroying that storage unit. And only ranged weapons can be used, because any melee weapon will be placed in compartment slot. 

![bug](https://user-images.githubusercontent.com/34580767/35856642-b36be10e-0b47-11e8-9ff8-8702c3d79d2c.png)

**Comment by alexkar598** [comment]
Congrats on breaking the ui,does t impact other players or stay after a reconnect?

**Comment by IllotAFV** [comment]
Stays after reconnect, also impacts every other player
