### ISSUE TITLE
Despite double ear damage catpeople seem to get up from those types of stun faster.

### ISSUE THREAD

**Issue by Wilchenx** [tgstation/tgstation#35380]
Title.

**Comment by AlexTheSysop42** [comment]
pretty sure flashbangs have stronger effects the closer you are

**Comment by Tlaltecuhtli** [comment]
no

**Comment by YPOQ** [comment]
Doubled ear damage doesn't mean longer stuns, unfortunately. And as Alex said, the closer you are the longer the stun.

**Comment by OmegaShoots** [comment]
Ear damage only means you go deaf easier/for longer

**Comment by DaxDupont** [comment]
four flashbangs is already can't hear for a round

**Comment by Ordonis** [comment]
This needs to be thoroughly tested by repeatedly flashbanging all catpeople until we can determine the success rate.

**Comment by MoreRobustThanYou** [comment]
close this, not a bug

**Comment by PKPenguin321** [comment]
I'm practically certain this is a non issue and can be closed

**Comment by AlexTheSysop42** [comment]
@ShizCalev
