### ISSUE TITLE
Picking up ore with an mining satchel and no box deletes the ore forever

### ISSUE THREAD

**Issue by NoKnowledge** [tgstation/tgstation#35408]
Round ID: #83207

[Testmerges]: #33166 ; #35281 

[Reproduction]: stick a mining satchel in any slot so it picks up ore automatically, then mine some ore. when the ore bag picks it up, it will vanish and the ore bag will remain empty. placing ore in manually also makes the ore vanish. this does not occur when you are dragging an ore box, and it is place in the box with no issue

**Comment by PsyCommando** [comment]
I noticed that too, but I assumed it was just an inventory quirk. I think it actually drops the ore when clicking "empty content" instead of looking at the content of the satchel. Anyone else had "empty content" work?

**Comment by vuonojenmustaturska** [comment]
@kevinz000

**Comment by Cyberboss** [comment]
Test merge issue
