### ISSUE TITLE
Fulton recovery disables internals

### ISSUE THREAD

**Issue by ayyourboibilly** [tgstation/tgstation#35404]
[Reproduction]: # Fultrons disable internals when arriving to the location this can cause death in certain situations

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by ayyourboibilly** [comment]
It also spawns you stunned so you will can't enable internals

**Comment by Jacquerel** [comment]
I cannot replicate this any more.

**Comment by Sealed101** [comment]
getting fulton packed paralyzes you so you can't change the state of your internals until it wears off. sure can be deadly

**Comment by SmArtKar** [comment]
Cannot reproduce, seems to have been fixed.
