### ISSUE TITLE
Adrenals make you fly in space faster

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#35400]
Fucking how

Syndicate hardsuit jetpack flying in space activate adrenals get fucking sanic fast

**Comment by OmegaShoots** [comment]
On a maybe related note, having the walk intent on makes you go slower in space.
Also golems all move at a fucking snail's pace in space. (except of course the ones that move faster)

**Comment by Kromgar** [comment]
Also i think the hardsuit is being slowed down in space from the slowdown it gives in space mode?

**Comment by Tlaltecuhtli** [comment]
does morphine work too?

**Comment by Potato-Masher** [comment]
No-no-no, light speed is too slow! Yes, we're gonna have to go right to... Ludicrous speed!

**Comment by AlexTheSysop42** [comment]
this + flight pack

**Comment by Potato-Masher** [comment]
Thinking about it, space movement is a weird subject. You shouldn't get a speed boost while using a jetpack in open space, BUT while next to a wall or lattice it makes sense because you are pulling yourself along the object in question.

**Comment by Dorsisdwarf** [comment]
Why would you not get a speed boost from using a jetpack

**Comment by PKPenguin321** [comment]
He means while under the affects of adrenaline
Unless adrenaline makes you jetpack harder

**Comment by Kromgar** [comment]
@Dorsisdwarf Adrenaline shouldn't make your jetpack move faster

**Comment by Rohesie** [comment]
This is fixed already. Comment here again or re-open a different issue if you see something like it again.
