### ISSUE TITLE
Remove the bad red overlay from fire alarms and replace them with emergency lights

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#35415]
![firefox_2018-02-07_15-19-27](https://user-images.githubusercontent.com/31222036/35924237-682852b2-0c1a-11e8-8dd4-145a0d644c50.png)
tldr remove the flashing red overlay from fire alarms and replace them with light tubes and bulbs turning into a red hue when the fire alarm goes off

@vuonojenmustaturska gave permission to make this ~~feature request~~ improvement request

**Comment by RandomMarine** [comment]
Too bad you'll only see it when some joker pulls the alarm because any actual fire will break the lights in seconds.

**Comment by Cyberboss** [comment]
@RandomMarine is right

**Comment by DaedalusGame** [comment]
Make the fire alarms themselves emit red light.

**Comment by praisenarsie** [comment]
i'll get one of the reasons why the red flashing overlay sucks probably tomorrow or friday

**Comment by Kromgar** [comment]
The reason it sucks is because even when singulo eats the fire alarm areas still continue to flash red

**Comment by praisenarsie** [comment]
![dreamseeker_2018-02-09_17-55-15](https://user-images.githubusercontent.com/31222036/36042085-9a553e18-0dc2-11e8-8aec-eca8376e69a5.png)
another reason it sucks is that mapping with areas can lead to shit like this, i triggered the fire alarm in the SM room and there's a flashing overlay out there at the injector pipe

besides, i think i'll know if an area is on fire when i hear the BEEPING and i see the fire doors go down

**Comment by ElfLeaderMike** [comment]
I was just complaining how much I hated the fire alarm's red tint, +1 to this for sure.

**Comment by PKPenguin321** [comment]
would it be better to just make firelocks and alarms have their own light sources inside of them that have big range but low intensity
