### ISSUE TITLE
Humans in soft crit can cancel revenant harvesting

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#35411]
It's weird to see a critted person, starting to harvest, and then they just move and immediately cancel the process.

**Comment by Kromgar** [comment]
Is this really a bug? If someone can crawl out of the revenants drain range then they should be able to survive

**Comment by Robustin** [comment]
I vote NOT BUG

**Comment by ChangelingRain** [comment]
it's fluffed as them floating into the air... if they can crawl through thin air then it's not a bug. however, most people cannot fucking dogpaddle through air.

**Comment by Kromgar** [comment]
Its fluffed as them floating in the air but i've never seen the bodies actually float

**Comment by Potato-Masher** [comment]
It's hard to succ out a perfect soul these days...

**Comment by kevinz000** [comment]
ic issue

**Comment by kriskog** [comment]
#41221
