### ISSUE TITLE
weird bugs with slimes mutations

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#35432]
83231 bagil

i noticed it on another round before, same day
so i was giving mut potions to slimes to get 100% and this happened:
some slimes  born from the split of a mutated one had impossible numbers as mut chance, like 18,5%, and similar all the wrong numbers ended with a ,5% even if the adult had like 80%.
only some of the childs had this weird mut chance some were born with the right %

**Comment by ayyourboibilly** [comment]
Not a bug it happends if the slime is mutated to gold or a few other colors
Slime mutation only works with base colors or it just resets the chance

**Comment by AlexTheSysop42** [comment]
it's not supposed to work with adamantine, light pink, oil, and black because those don't have a mutation chance because they don't mutate

**Comment by AlexTheSysop42** [comment]
gold should work though

**Comment by ShizCalev** [comment]
Intentional.
