### ISSUE TITLE
Cig no chem absorb on smoke

### ISSUE THREAD

**Issue by Shardj** [tgstation/tgstation#35438]
Issue reported from  Round ID: 83247 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

[Round ID]: #83247

https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Reproduction]: Dip a cig in some chemicals, smoke it, none of the non cig chemicals end up in your system

**Comment by Shardj** [comment]
Has this been fixed then @kriskog ?

**Comment by kriskog** [comment]
Yeah. can't reproduce. Works fine now.
