### ISSUE TITLE
you can't fully deconstruct firelocks

### ISSUE THREAD

**Issue by iskyp** [tgstation/tgstation#35439]
Round IDs: 83246, 83247

Attempting to deconstruct firelocks into doesn't work, as the last step (welder, slice apart frame) doesn't function properly. It uses up fuel but nothing happens to the frame.

I was attempting to revamp the bar area in Bagil, and after removing the airlocks, I was stuck with the task of removing the firelocks. I got them off, tried to break down the frames, but it did nothing. I had multiple other players try, nothing happen. Went to sybil, still didn't work, even for other players.

This makes it so that the only reliable way to remove firelock frames without wasting resources is via Supermatter Crystal, and that's probably not the best idea.

**Comment by newfren** [comment]
You can also remove them via hulk or high force weapons but of course the welding step oughta work.
