### ISSUE TITLE
Secure Airlocks can be hacked without removing the shielding

### ISSUE THREAD

**Issue by Chickenmonster1** [tgstation/tgstation#35444]
[Round ID]: # 83263

[Reproduction]: # Open the panel on any door with the metal sheeting.  
Use the multitool or wirecutters like normal.

I was able to do this on the morgue and ai upload panels. And when I went to do the vault, someone was already doing it there.

**Comment by ShizCalev** [comment]
Unable to repo.

**Comment by Chickenmonster1** [comment]
You can access the wires of shielded doors like the vault before the metal plates are out.  Screwdriver the panel open, then click on it with the multitool.

**Comment by ShizCalev** [comment]
Caused by testmerge #33166
