### ISSUE TITLE
infinite wand usage via dualwield

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#35448]
10:53:36: Zaross/(Zaross): I think if you dualwield a gun in hand and have a wand with 0 charges in your offhand your wand will go into negative charges, then be still able to fire as normal, giving you infite ammo.

**Comment by DaxDupont** [comment]
itt kevin plays with wands

**Comment by AlexTheSysop42** [comment]
tested on localhost, couldn't reproduce
