### ISSUE TITLE
Trying to split sheet stacks just puts it in your hand

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#35472]
![2018-02-08_19-04-35](https://user-images.githubusercontent.com/20155238/36006519-078be970-0d03-11e8-9148-4a337cd35048.png)
![2018-02-08_19-04-49](https://user-images.githubusercontent.com/20155238/36006520-079faf78-0d03-11e8-9699-012ff8a9927b.png)
im guessing this is probably kevincode ruining everything but whatever

**Comment by AnturK** [comment]
@kevinz000

**Comment by Spaceinaba** [comment]
![image](https://user-images.githubusercontent.com/20155238/36056024-7af9172a-0dc6-11e8-8e5a-8fae5d32911f.png)
