### ISSUE TITLE
Mothmen have fake jetpacks in space with magboots equipped.

### ISSUE THREAD

**Issue by CollieAlphonse** [tgstation/tgstation#35477]
[Round ID]: 83303

[Reproduction]: Issue occurs with mothmen in EVA suits wearing [active] magboots. Don't know if internals being active affects it. Results are mixed.

Mothmen have directional control in certain (seemingly specific) areas of space while magboots are active with the same effects as being in zero-g while in atmosphere. Seems to be the same speed as having wings while in the station. Not exactly game-breaking, but certainly very abusable. Speed is just barely fast enough to outrun space carp.

Issue does not occur in close proximity to traversible tiles like scaffolding and catwalks.
Issue occurs in deep space. 
Issue occurs in certain open areas directly outside of the station. 
Issue halted when I killed the (seemingly) only space carp on the z-level I was on. Maybe related?

**Comment by F-OS** [comment]
MOTHS WERE A MISTAKE

**Comment by CollieAlphonse** [comment]
Upon further inspection *everyone* has fake jetpacks in space in the presence of space carp.

**Comment by MoreRobustThanYou** [comment]
@CollieAlphonse fix title

**Comment by ArcaneDefence** [comment]
This has nothing to do with moths or magboots.
