### ISSUE TITLE
Goliath Hide no longer upgrades Explorer Suits and can be applied infinitely to the suit with zero change

### ISSUE THREAD

**Issue by jakeramsay007** [tgstation/tgstation#35474]
[Round ID]: Any

[Reproduction]: Take a stack of goliath hides. Use them all on the explorer suit (not the hood, the suit itself. You can use an infinite amount on it anyway, which is a symptom of this bug). View the explorer suit's armour variable, and realise there's been no change.

**Comment by SpaceManiac** [comment]
No repro locally, was this on live? Round ID, testmerges?

**Comment by jakeramsay007** [comment]
@SpaceManiac Tested locally and on Citadel, both had the same outcome of the hide not applying correctly to explorer suits.

**Comment by SpaceManiac** [comment]
Yep, it was my mistake. Fix is up.
