### ISSUE TITLE
Player slimes refuse to eat.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#35481]
Issue reported from  Round ID: 83313 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Test Merges: #33166 

Trying to eat any creature as a slime with feed appears to not work. It simply gives a "I'm not hungry anymore..." message.

Reproduction:
1. Gain sentience as slime
2. Attempt to feed on monkey
3. Attempt to explain to your xenobiologist in slime speak why you can't eat the monkey.

**Comment by XDTM** [comment]
Did you have a custom name? If so the xenobiologist likely used a pink potion, which makes you harmless

**Comment by AnturK** [comment]
Quick glance at the code confirms this is message for docile slimes

**Comment by Potato-Masher** [comment]
Ah, silly xenobiologist. I guess I thought he used the sentience potion.
