### ISSUE TITLE
Once full enough, ore satchels stop collecting ore despite having sufficient capacity

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#35487]
![dreamseeker_2018-02-09_13-32-39](https://user-images.githubusercontent.com/12747768/36029081-f261c41c-0da1-11e8-9736-f78f9d89f01a.png)

**Comment by AlexTheSysop42** [comment]
is that a claymore and cult knife in your bag?

**Comment by Kromgar** [comment]
Envy's knife, and the claymorei s from a knight

**Comment by Kromgar** [comment]
#33166

**Comment by Cyberboss** [comment]
Test merge
