### ISSUE TITLE
Mutli-line interfaces are broken

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#35486]
![dreamseeker_2018-02-09_13-04-01](https://user-images.githubusercontent.com/12747768/36029024-c15f1fea-0da1-11e8-958e-fc69ff4dccd0.png)

**Comment by Cyberboss** [comment]
Round ID or close

**Comment by Cyberboss** [comment]
Its from the test merge

**Comment by Slignerd** [comment]
Yep, just like with #35487, the PR #33166 was testmerged at the time.
