### ISSUE TITLE
Wizards can fireball while stunned

### ISSUE THREAD

**Issue by YogsMcree** [tgstation/tgstation#35480]
[Round ID]: # 83305 
[Reproduction]: # Wizards appear to be able to cast fireball at targets even when stunned. I am fairly certain this is not the intended function. While something like jaunt is questionably castable during stuns, casting fireball during stuns means you can lure anyone near you and just fireball their dick off. Its incredibly overpowered. Combine this with lich and max fireball, and you can basically freely fireball shit until youre a corpse. Doesnt seem to be functioning as intended

**Comment by evsey9** [comment]
Intended
As long as you can speak while stunned you should be able to cast any spell

**Comment by AnturK** [comment]
Intended
