### ISSUE TITLE
Shift + middle mouse button no longer work

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#35482]
For as long as I remember, you were able to use Shift + MMB to point at things in game. But now it's broken.

**Comment by praisenarsie** [comment]
@ninjanomnom this was a bind

**Comment by DaxDupont** [comment]
round id for fucks sake it might be related to the test merge

**Comment by Slignerd** [comment]
Statbus no longer works, so I can't give you a round ID, but it's the same round as #35486 and #35487.

**Comment by kevinz000** [comment]
could not reproduce on comp storage.

**Comment by Slignerd** [comment]
Confirmed to be simply an issue with my mouse.
