### ISSUE TITLE
You can spawn as ghost roles before the round even begins

### ISSUE THREAD

**Issue by Spess-Rando** [tgstation/tgstation#35499]
![2018-02-10_00-52-27](https://user-images.githubusercontent.com/12747768/36055445-b1ee5886-0dfc-11e8-81da-16dc9602a28b.png)

![dreamseeker_2018-02-10_00-51-05](https://user-images.githubusercontent.com/12747768/36055429-932f62dc-0dfc-11e8-9b53-f516ec2d8a3c.png)

I believe waiting for the game to at least finish setting up should be the bare minimum.

**Comment by Kromgar** [comment]
I think this is only able to be done through the spawn panel? You definitely cant click on the spawners to spawn in before the round

**Comment by Slignerd** [comment]
Tested it, and it does seem to be the spawn panel - though you the spawner doesn't activate until setup is finished, you get to take the role before the round starts.

**Comment by AlexTheSysop42** [comment]
Why can you observe before roundstart in the first place?

**Comment by kriskog** [comment]
This is fixed
