### ISSUE TITLE
Ore's Icon_state is being changed to "[name]-3" & splitting Funky

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#35492]
#33166: '[READY]Refactors storage handling from /obj/item/storage to a component.' by kevinz000 at commit 4f14e3

May be related I haven't looked at it l0l

Somewhere in how it stacks ore's icon_state is being changed to "[name]-3" which causes the sprite to break, and alt-clicking ore does not change anything (no new stack) albeit giving a message that it did.

**Comment by Kromgar** [comment]
It's probably a combination fo this and the PR that made it so that ore stacks

**Comment by praisenarsie** [comment]
@vuonojenmustaturska

**Comment by Kromgar** [comment]
![image](https://user-images.githubusercontent.com/6778786/36042597-672473f6-0d9a-11e8-8cc1-f90dbe8031c7.png)

**Comment by kevinz000** [comment]
not caused by my pr but i'm fixing it in mine too.

**Comment by ShizCalev** [comment]
Fixed by #35772
