### ISSUE TITLE
Some gas miners don't distribute moles properly

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#35529]
![image](https://user-images.githubusercontent.com/16315400/36070797-b8ba384a-0ed0-11e8-87dc-970258efff3f.png)
This one is in the cat SAW space ruin. The tile with the miner is at 6000kpa, the other 3 are at vacuum.

**Comment by YPOQ** [comment]
#34000

**Comment by ShizCalev** [comment]
duplicate of #34000
