### ISSUE TITLE
Dragging while getting laserpointered as a catperson crashes your game.

### ISSUE THREAD

**Issue by UncleBourbon** [tgstation/tgstation#35527]
[Round ID]: # 83407
[Testmerged PRs]: https://github.com/tgstation/tgstation/pull/35516
[Reproduction]: Basically:
1. Be a catperson
2. Drag someone (or something never really could test)
3. Have someone point a laser pointer to make you grab at it 
4. Bam your game crashes

[For Admins]: # No weird shit happened that round before my game started crashing, only admin thing I saw was after, which was the mime getting her ears back and then centcomm snitching on the last head rev who was being a pussy in maint.

**Comment by MoreRobustThanYou** [comment]
feature

**Comment by SgtxRootbeer** [comment]
Feature

**Comment by ArcaneDefence** [comment]
Failed to reproduce.
