### ISSUE TITLE
Tracking Playtime is broken

### ISSUE THREAD

**Issue by soyconsumer** [tgstation/tgstation#35522]
Basically if I check my tracked playtime during a round it'll save my progress but if the round ends and I get brought back to the lobby it'll reset to 30 minutes assistant.

https://imgur.com/a/8TUxF
First image is during round
Second image is after the round has ended in the lobby

**Comment by praisenarsie** [comment]
@Cyberboss

**Comment by Cyberboss** [comment]
@MrStonedOne
