### ISSUE TITLE
CURATOR CAN STILL GET SCARED OF HEARING SNAKE WHEN HES DEAF

### ISSUE THREAD

**Issue by improvedname** [tgstation/tgstation#35537]
![image](https://user-images.githubusercontent.com/24854897/36073111-7686323e-0f2b-11e8-821b-222b8b021f4a.png)

DESPITE HAVING MY EARS REMOVED I STILL HEAR SNAKE AND GET SCARED OF IT

**Comment by Slignerd** [comment]
Feature

**Comment by Kromgar** [comment]
You read their lips

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/5a08a3aad0e1684fb501eb6e4f7be54311d66e0a/code/datums/brain_damage/phobia.dm#L70-L72

**Comment by Cyberboss** [comment]
on_hear is called at the wrong time. All the can_hear checks are done in show_message. It'd have to be refactored to actually handle it properly

**Comment by Iamgoofball** [comment]
yeah uh dont fix this please?
