### ISSUE TITLE
changing species makes u lose implanted organs

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#35539]
i had a xray eye , changed my species and i lost it, other implants changed fine

**Comment by KorPhaeron** [comment]
From what species to what species

**Comment by Tlaltecuhtli** [comment]
slime to slime subspices

**Comment by ShizCalev** [comment]
This is do to on_species_gain calling regenerate organs

**Comment by ShizCalev** [comment]
this also results in abductor organs being cleared, honk

**Comment by kriskog** [comment]
related #42098

**Comment by Rockdtben** [comment]
in species.dm

//Will regenerate missing organs
/datum/species/proc/regenerate_organs(mob/living/carbon/C,datum/species/old_species,replace_current=TRUE)

**Comment by private-tristan** [comment]
you also lose all augs
