### ISSUE TITLE
Free Infinite Metal

### ISSUE THREAD

**Issue by Daturix** [tgstation/tgstation#35569]
Trying to cut reinforced metal flooring, IE the tiles outside SM produce infinite metal rods and doesnt remove the floor.

**Comment by YPOQ** [comment]
#35280

**Comment by Buggy123** [comment]
Can we start updating terry more often? Please?

**Comment by factoryman942** [comment]
why would more frequently updating terry reduce duplicate issues?

**Comment by ShizCalev** [comment]
Duplicate of #35280

**Comment by ShizCalev** [comment]
fix isn't even merged yet so updating would do nothing.

**Comment by Buggy123** [comment]
>fix isn't even merged yet so updating would do nothing.

Wait, what the fuck? It's a simpleish fix and its been over a week.
