### ISSUE TITLE
Ghosts can change the automated announcements during the round.

### ISSUE THREAD

**Issue by ElfLeaderMike** [tgstation/tgstation#35587]
Round #83487
Ghosts can change the automated announcements during the round.

![Wew](https://i.imgur.com/FGmNAMO.png)

**Comment by ElfLeaderMike** [comment]
As fun as it is it can be abused to do horrible round ruining things, probably is pretty important.

**Comment by Buggy123** [comment]
_The ride never ends._

**Comment by LetterN** [comment]
[ """Design lead approved""" ]
