### ISSUE TITLE
Pubbystation chemistry is missing a wall

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#35595]
https://i.imgur.com/PHdDZBt.jpg

Unwrenching the fridge in the Pubby chemistry lab leaves a hole in the wall that isn't covered by shutters.

The meta chem lab has a wall behind the fridge to fix this.

**Comment by Buggy123** [comment]
Feature.

**Comment by DaxDupont** [comment]
you can put those fridges on the walls.
Meta/delta does it

**Comment by 81Denton** [comment]
Yeah, those two use uhhh bluespace technology to put a fridge and wall on the same spot. That way you can't just unwrench the fridge and create a gaping hole.
