### ISSUE TITLE
You cant add reinforced glass to AI core as engineering cyborg, even when glass is being used.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#35596]
[Reproduction]: Try to finish AI core by putting reinfocred glass into it. Even when glass synthesizer will use 2000 points as it should, AI core will not get that glass.

**Comment by JohnFulpWillard** [comment]
https://user-images.githubusercontent.com/53777086/155152177-a4567f6d-84fb-43de-a54d-10b0bf9cd0ef.mp4
