### ISSUE TITLE
[TOKEN-BOUNTY] Pirate Ship Based Turrets need a Subtype rather than var editing

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#35591]
There are enough as seen in #35427 that warrants a subtype.

![](https://user-images.githubusercontent.com/6209658/36052735-de8d9ec8-0dbc-11e8-9f84-4ac0080b5b33.png)

**Comment by ExcessiveUseOfCobblestone** [comment]
Will provide a Traitor-equivalent antag token since this is blocking me from doing my code improvement for turrets, just an incentive ;-)

**Comment by coiax** [comment]
This seems very easy... am I missing something?

**Comment by MMMiracles** [comment]
shhh free tokens coiax

**Comment by ShizCalev** [comment]
There are all different subtypes and are fine as varedits.
