### ISSUE TITLE
tgui interfaces break when minimized

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#35592]
https://gfycat.com/SandyNeedyJellyfish

**Comment by praisenarsie** [comment]
they don't break for me unless this is recent, needs reproducing

**Comment by ike709** [comment]
This has happened to me pretty much ever since TGUI was added.

**Comment by Slignerd** [comment]
You need to use the 'Fancy' tgui style to reproduce the bug.

**Comment by Cyberboss** [comment]
The workaround is right-click -> restore

**Comment by ShizCalev** [comment]
Duplicate of #26644
