### ISSUE TITLE
Mechs able to be picked up during construction

### ISSUE THREAD

**Issue by TankNut** [tgstation/tgstation#35608]
**Round ID:** [83498](https://atlantaned.space/statbus/round.php?round=83498)
**Testmerges:** #33166 #35535 #35546
**Reproduction:** _(Tested with both firefighter and odysseus mechs as they were being built when I discovered the bug)_

1. Start production of a mech like normal
2. Somewhere after adding the last part and wrenching the hydraulics into place, attempt to pick up the mech like you would an item _(Bug was discovered at around this point, haven't tested earlier states)_
3. Find you can pick up the mech
4. Finish the mech and attempt to pick up the item again
5. Get disappointed as you find it's no longer possible

**Notes:**

- When on the ground the mech still behaves like an unfinished mech would. You can push it around no problem and it's still dense
- While picked up you can throw the mechs around like you would any other item. It doesn't seem to do any impact damage though
- Was playing as a moth, don't think that should make a difference but you never know

**Comment by Hatterhat** [comment]
it's a feature

**Comment by Iamgoofball** [comment]
not a bug, mecha assemblies are items

**Comment by TankNut** [comment]
I swear you used to be unable to pick them up. It doesn't make much sense either considering they're normally dense objects.

**Comment by PKPenguin321** [comment]
Agreed, I'm pretty sure this is non standard behavior

**Comment by TankNut** [comment]
Tested it a few hours ago, couldn't pick them up while retracing my steps as best as possible. Not sure what could've caused it.

**Comment by Fikou** [comment]
@PKPenguin321 close?
