### ISSUE TITLE
Nuke ops are unable to purchase noslips

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#35602]
Round ID: 83504

1) Have nuke op uplink.
2) Go to Stealth section.
3) Noslips are missing.

They SHOULD be purchasable, I can see their entry in the uplink_items.dm but it's not showing.

A workaround is that apparently the shoes in the Broken Camokit bundle are noslip.

**Comment by Darkgenerallord** [comment]
I believe it's based off population.

**Comment by ExcessiveUseOfCobblestone** [comment]
The shoes actually got separated from the rest of the kit iirc.

**Comment by YPOQ** [comment]
#34487 changed them to use the same name as the non-nuke noslips, however the unfilterted uplink list (includes both nuke and non-nuke items) uses the names as keys. https://github.com/tgstation/tgstation/blob/3494dee62461127e8dbf7142b833d991a7426edf/code/modules/uplink/uplink_items.dm#L11
