### ISSUE TITLE
Trying to remove inducer batteries just tells you it's dead

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#35619]
![image](https://user-images.githubusercontent.com/20155238/36135231-6a044148-104f-11e8-802f-e886952dd873.png)

**Comment by SpaceManiac** [comment]
This may be user error - have you tried unscrewing the panel and then using the inducer in-hand?

**Comment by Spaceinaba** [comment]
I think I did but I'll try it again once I get a chance and close it once I find out im just retarded

**Comment by Spaceinaba** [comment]
yea im retarded
