### ISSUE TITLE
Unstable power cells aren't that unstable

### ISSUE THREAD

**Issue by RandolfTheOkay** [tgstation/tgstation#35616]
Issue reported from  Round ID: 83516 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Power cells now have a 5u capacity for plasma, which would be alright if it didn't require 10u for it to explode upon use. I have briefly discussed this with Kevinz, who stated that 5u should be the threshold for explosive cells, yet I have tested this three times (before and after the unstable cell explosion rework), and none of the trials have had the cell explode. I wanted to test if 6u would trigger it, but since there's a hardcap of 5u now, I'm kinda stuck with just telling you all it currently doesn't work.

Unstable cells don't explode.

**Comment by arsserpentarium** [comment]
Last time I tested it, it exploded

**Comment by DaedalusGame** [comment]
this works fine on my end but there's a problem regardless

**Comment by swindly** [comment]
Unable to reproduce
![Capture](https://user-images.githubusercontent.com/22402048/108249146-9d925c00-714c-11eb-8268-19bf6cb5edbf.PNG)

**Comment by timothymtorres** [comment]
Closing this since I don't see any new issues that have been reported since this was opened.
