### ISSUE TITLE
Wizard name change event makes circuitry analyzer unusable

### ISSUE THREAD

**Issue by AverageJoe82** [tgstation/tgstation#35622]
[Round ID]: # 83532

[Reproduction]: # have all object names changed by the wizard name change event, analyzer scans can't be used for making new circuits

This is caused by the fact that the save text uses the circuit name to save but the wizard event changes the name of each circuit.

**Comment by Tlaltecuhtli** [comment]
feature

**Comment by AlexTheSysop42** [comment]
this happened on the round where the admins renamed everything to togopal too

**Comment by ShizCalev** [comment]
feature

**Comment by Potato-Masher** [comment]
>Togopal successfully removes Togopal from Togopal's Togopal with the Togopal!

Larva removal surgery during Togopal madness.

As for the actual issue, holy heck I didn't know the name change affected more than people.

**Comment by AverageJoe82** [comment]
no @Potato-Masher i mean the name change where it makes it like "the locomotive circuit of fortitude +5"
