### ISSUE TITLE
You can outrun bullets and lasers. You can also hit yourself with your own bullets as well as hit yourself with your own thrown objects.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#35623]
i blame @kevinz000

**Comment by Potato-Masher** [comment]
All tg spessmen run on adrenals.

**Comment by davv1** [comment]
Also same applies for spraying with Space Cleaner bottle. Spraying in front, when running, causes to spray on yourself(even all three times in a row)
