### ISSUE TITLE
Human organs have no export value

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#35626]
Human organs don't have any value when you export them via cargo shuttle. 

Scanning them with an export scanner results in a "Scanned the lungs, no export value." message.

Lizard tails/cat ears export just fine and exports\organs.dm seems correct. No clue what causes this issue.

**Comment by ChangelingRain** [comment]
the issue here is that human organs aren't in short supply, and are thus worth nothing.

**Comment by ChangelingRain** [comment]
also checking the code they're marked as contraband so you need to either hack or emag the console first
