### ISSUE TITLE
Heat pipes are not working properly

### ISSUE THREAD

**Issue by Sunoplyrus** [tgstation/tgstation#35631]
Round ID: 83547 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
Reporting client version: 511

![dreamseeker_2018-02-13_15-54-35](https://user-images.githubusercontent.com/31968974/36168227-821ea652-10df-11e8-88f2-2b6a5a6f98cd.png)
Trying to set up heat exchange pipes on layer 1

![image](https://user-images.githubusercontent.com/31968974/36168277-a5c7ed3e-10df-11e8-8b42-302aa8469fc5.png)
Trying to connect a manifold to a junction on layer 1
![image](https://user-images.githubusercontent.com/31968974/36168553-9e552584-10e0-11e8-840d-8622c04365f1.png)
after wrenching it again it now connects.
![dreamseeker_2018-02-13_16-10-39](https://user-images.githubusercontent.com/31968974/36168626-d896f3da-10e0-11e8-9822-7d45a2039667.png)
Connected some pipes around to check if it worked, had to put gas in it otherwise I couldn't wrench it from the floor nor use an analyzer on them.

**Comment by praisenarsie** [comment]
i saw this happen before but forgot to report it or at least i think i did. either way this looks way worse than what i saw

**Comment by duncathan** [comment]
oh yeah this is weird and I know it happens; shouldn't be too tough to fix but I need to figure it out
