### ISSUE TITLE
Excessive amount of <br> in IT COMES shuttle curse

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#35632]
![image](https://user-images.githubusercontent.com/609465/36170606-b9b82d5a-10f7-11e8-8331-15f14929e4d8.png)

Round ID: 83549

@Robustin

**Comment by DEATHRATTLERS** [comment]
hue hue hue

**Comment by Robustin** [comment]
Ah I caught that but forgot to push the fix before it was merged.
