### ISSUE TITLE
Grinders apparently delete items from botany bags

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#35634]
[Round ID]: 83549

[Reproduction]: Recieved reports that the grinder was just silently deleting items from the botany bags when you tried to use them to load it

**Comment by WJohn** [comment]
Apparently when someone tried to put the contents of a plant bag into a grinder, they instead created a copy of the plant bag (which in itself carried nothing), while the original remained in their hands.

**Comment by SuedeFalcon** [comment]
I had a similar bug. Instead of taking the contents of the plant bag, it would take a "copy" of the plant bag itself, leaving the original in inventory. Nothing would grind, and it wasn't possible to remove the plant bag from the grinder.

**Comment by Jalleo** [comment]
@kevinz000

**Comment by kriskog** [comment]
These seem to be working fine now.
