### ISSUE TITLE
Blob tiles randomly become invincible and stay active after the blob core's death

### ISSUE THREAD

**Issue by Xhuis** [tgstation/tgstation#35645]
I cannot provide a round ID for this round, because the round hard-restarted and so did not leave any logs. It happened around 6:20-ish EST. When the blob core died, the vast majority of the blob tiles became invincible and unable to be interacted with. This included several laser barrages and gunshots.

Blob nodes continued spreading, and blob factories continued producing blob spores that were fully hostile and capable of animating corpses.

**Comment by ElfLeaderMike** [comment]
Can confirm I've seen this issue before, if I see it again I'll post up a round ID.

**Comment by YPOQ** [comment]
#32320

**Comment by Xhuis** [comment]
This didn't apply to just reinforced tiles; it applied to *all* tiles. Additionally, that issue doesn't mention that nodes, factories etc. remained active.

**Comment by Nabski89** [comment]
Can confirm I've had and seen this happen.

I spawned a blob node and it grew out as expected, but was invincible unattackable and did not attack. It never had a core to go with it. Could that be related?
