### ISSUE TITLE
valentine objectives bug

### ISSUE THREAD

**Issue by LetterN** [tgstation/tgstation#35669]
Bagil station, Round id: 83607
[Testmerges]:  #35660  #35609  #35535

So, apparently, this can happen

![thank coderbus](https://user-images.githubusercontent.com/24603524/36216869-f0a158c0-11ea-11e8-819b-c4b803e4df6f.PNG)

**Comment by davethwave** [comment]
Not a bug I think...

**Comment by PKPenguin321** [comment]
This is because being borged counts as dead for objectives, so you can borg your kill target and still have it count when you're a traitor

**Comment by YakumoChen** [comment]
dupe of #35663
