### ISSUE TITLE
Cloning as a Monk Chaplain randomizes your name + HUD buttons disappearing bug

### ISSUE THREAD

**Issue by ThePainkiller** [tgstation/tgstation#35666]
**Round ID:** #83597 (Sybil, Omegastation)

As a Chaplain with Monk manual, dying and getting cloned does not reset your "ki levels" (punches stay the same damage, penetrate armor, cleave attack, etc), but your HUD buttons from stun punch onwards completely disappear.

Also, your name gets randomly changed EVERY TIME you clone, and you cannot equip headgears, not even hardsuit ones (is this last one intended?)

**[Testmerges]:** [Adds the Monk Martial Art to the Chaplain's null rod selection #35535](https://github.com/tgstation/tgstation/pull/35535)

**[Reproduction]:** The exact thing is that I died to a normal Legion near a tendril and got absorbed by it. A lizard got me out, cloned me on a stock cloner (i.e., not upgraded at all) back in the station, and when I finished cloning, I had lost all my buttons (the stun punch, chakra and heart stopping punch) including the one to make a disciple (I had already made my first disciple at this point)

**Comment by AnturK** [comment]
Testmerge issues go into PR comments #35535
