### ISSUE TITLE
Chemical explosions aren't capped.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#35681]
@DaedalusGame 

![](https://image.prntscr.com/image/2oDVF2WFTO2NK4wwu7kInA.png)
note this is only nitroglycerin so others could be capped

made a bigger explosion than maxcap according to bord

**Comment by DaedalusGame** [comment]
1000u of nitro, the max you can put on a monkey, make a 7,15,31 (maxcap is 5,10,20)
the new age of cuban pete is clearly at hand

**Comment by Robustin** [comment]
Does the logged explosion include the theoretical or actual explosion size?

**Comment by DaedalusGame** [comment]
actual explosion

**Comment by chesse20** [comment]
not a glitch

**Comment by Darkgenerallord** [comment]
realistically you can only make a certain amount of nitro anyway, so this is fine

**Comment by ElfLeaderMike** [comment]
I don't understand how you can make this work in game?

You can't trigger stabilized reactions inside of mobs, so monkey bombs are not even possible unless you find a way to inject the final ingredient to nitro all at once.

I've been trying to make infinite chem bombs for a long time now and haven't found anything good besides pill grenades stored in your body. Which are actually amazing but no one has abused them enough to be nerfed yet.

**Comment by Buggy123** [comment]
Can you put reagents back into a water tank? If so, can you heat the contents with a plasma fire?

**Comment by ElfLeaderMike** [comment]
The hardest part would be making 1000u of nitro and slowly injecting it, but otherwise setting people on fire does trigger the nitro. I guess I never had a chance to ever mess with nitro because it requires some teamwork from botany.

**Comment by Dorsisdwarf** [comment]
pretty sure chem bombs not being capped is intentional

**Comment by newfren** [comment]
The easiest way to inject it would be probably a lot of IVs + pill forcefeeding.

**Comment by TimeIsEndless** [comment]
actually easiest way is either a cryopod or vapes. vapes still multiply chemicals and it would only take about 300 units to fill someone up fully

**Comment by kriskog** [comment]
Intentional
