### ISSUE TITLE
Space can get wet/icy

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#35684]
Probably a known issue but I can't find a report for it:
![image](https://user-images.githubusercontent.com/16315400/36237984-7f398382-11cd-11e8-89d4-2102d4761dee.png)

**Comment by PKPenguin321** [comment]
this looks like from the screenshot an issue with either shuttles or perhaps the deployable mining base thing but i could be totally wrong

needs more context for the screenshot

**Comment by Darkgenerallord** [comment]
it's neither, it was the area below the Incinerator on Meta

**Comment by Buggy123** [comment]
Correct, it was a area that got eaten by the singularity, no shuttles involved. It might have gotten wet before it was eaten, I'm not sure.
