### ISSUE TITLE
Pubbystation appears to have no way of launching it's aux base.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#35686]
Issue reported from  Round ID: 83633 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 511

So, you know how most maps have a deployable aux base? Pubby does too. Except it doesn't work.
The designator beacons don't operate, and simply say:
![dreamseeker_2018-02-14_22-22-33](https://user-images.githubusercontent.com/33107541/36239219-d5706236-11d5-11e8-978b-fbabe30957f5.png)

The aux base computer also does not have an option for blind dropping.
Here is the pubby aux base construction, stashed away in main near engineering to prove that it, in fact,  exists on the map:
![dreamseeker_2018-02-14_22-22-41](https://user-images.githubusercontent.com/33107541/36239240-01347efc-11d6-11e8-9376-700dc40d5b0d.png)

**Comment by GunHog** [comment]
The particular error given represents a missing Auxiliary Base docking port. The path is `/obj/docking_port/mobile/auxillary_base`. I am going to hazard a guess here and say that someone improperly modified the Aux Base or deleted the docking port object. I will try to check the map to see.

**Comment by Potato-Masher** [comment]
Sounds simple enough. I'll fix this when I get home.

**Comment by Potato-Masher** [comment]
Man, I don't quite have the expertise of hunting down issues in this mess yet. Could you show me where to find the issue, @GunHog ?

**Comment by GunHog** [comment]
Are you a mapper? Open up Pubby's .dmm, Find the Aux Base in the map editor, right-click the central pillar of the Aux Base, you will find the docking point in that list. Open the context menu for it, select 'edit' or whatever, then set the "timid" variable to "0".

Alternatevly, you could just go here https://github.com/tgstation/tgstation/blob/8530c20cc1cc88a0ead4634a743d5aed836f4667/code/modules/mining/aux_base.dm#L242 and add the line `timid = FALSE` there and not have to touch a map.

**Comment by Potato-Masher** [comment]
Damn it, I was looking at the wrong thing. Figures. Thanks man.
