### ISSUE TITLE
I can't see sentience potion popups

### ISSUE THREAD

**Issue by AlexTheSysop42** [tgstation/tgstation#35682]
Issue reported from  Round ID: 83629 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

I have no idea how to reproduce this, it apparently hasn't happened to anyone else and there isn't a sentience potion-related option anywhere I can see in prefs

This has occurred multiple rounds in a row

**Comment by YPOQ** [comment]
They use the alien preference. Also, hitting "never for this round" on the minebot poll will also disable sentience potion polls.

**Comment by AlexTheSysop42** [comment]
yeah I just figured that out

**Comment by AlexTheSysop42** [comment]
to clarify for anyone else, alien = xeno
