### ISSUE TITLE
Hello, I would like to collaborate with your translator project in Spanish since it is my native language, I can translate any document that has text

### ISSUE THREAD

**Issue by LuigiBaute** [tgstation/tgstation#35699]
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by Iamgoofball** [comment]
@KorPhaeron @cyberboss 
This is a good opportunity to set up localization

**Comment by Tlaltecuhtli** [comment]
feature

**Comment by praisenarsie** [comment]
cyber is researching on how to do it, stay tuned

**Comment by factoryman942** [comment]
what

**Comment by Cyberboss** [comment]
Discussion happens on coderbus: irc://irc.rizon.net/coderbus or if you dont have an IRC client, you can click  [here](https://kiwiirc.com/client/irc.rizon.net:6667/?&theme=cli#coderbus).

**Comment by Cyberboss** [comment]
And yes, I am looking into this
