### ISSUE TITLE
Cinematics don't appear on Byond 511 clients

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#35709]
I seem to be incapable of seeing any cinematics whatsoever - not after clearing my Byond cache, not after trying to host a local server.

All I get is suddenly freeze in place, hear weird sounds - but nothing is ever shown to me.

**Comment by SpaceManiac** [comment]
What BYOND client version?

**Comment by DaedalusGame** [comment]
this must be related to ping somehow because I've had this issue for years

**Comment by Slignerd** [comment]
511.1385. Should I upgrade to 512?

**Comment by SpaceManiac** [comment]
should be fine, wanted to confirm you weren't using a known-broken build

**Comment by AnturK** [comment]
There's nothing special about cinematics, they're just screen objects.

**Comment by Dorsisdwarf** [comment]
i dont get cinematics either

**Comment by Slignerd** [comment]
Fixed by upgrading to 512.

**Comment by SpaceManiac** [comment]
The codebase no longer supports 511 clients.
