### ISSUE TITLE
disco machine's "add_track" proc does not work

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#35713]
See: https://github.com/tgstation/tgstation/blob/master/code/game/machinery/dance_machine.dm#L47

Doesn't work at all

Makes me cry

@Robustin @kevinz000 i think you two made this thing didn't you? please fix

**Comment by Robustin** [comment]
I made the dance machine, Kev probably added that proc so he could badmin with the files. I don't recall that particular proc or testing it. It still loads the default tracks right?

**Comment by PKPenguin321** [comment]
Yeah default tracks work fine

**Comment by PKPenguin321** [comment]
@kevinz000 😠
