### ISSUE TITLE
Cyborg expand upgrade has no limit

### ISSUE THREAD

**Issue by Togopalis** [tgstation/tgstation#35712]
https://i.imgur.com/fCgJGwG.png

Also you can reset the module of a cyborg and the expand upgrade will pop out of the borg without resetting its size so it has infinite uses

**Comment by newfren** [comment]
F E A T U R E
E
A
T
U
R
E

**Comment by DaxDupont** [comment]
o fuk

**Comment by Xhuis** [comment]
# E X P A N D C Y B O R G
