### ISSUE TITLE
Gas Heaters/Freezers cannot be rotated via wrench

### ISSUE THREAD

**Issue by Poojawa** [tgstation/tgstation#35719]
Really quite annoying.

I took a gander at it on the off chance that I could fix it, but no, it's got a snowflake 

`if(default_change_direction_wrench(user, I))
		return`

Basically, pop open with screw driver, attempt to use wrench, wrench doesn't rotate the unit. Crowbar deconstructs just fine, however.

**Comment by 81Denton** [comment]
Can confirm this on localhost.
Revision: 329ff642a8fdbdb12e50f23ba5a9e8e06890907e
BYOND: 511.1385

**Comment by DaedalusGame** [comment]
Mechbays can be rotated
Cryopods can't be rotated
