### ISSUE TITLE
[Meta] Circuitry Lab Map Errors

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#35711]
Circuitry Lab cameras are not properly on the Research camera network (for RD's monitor)

The firelock on the Circuit lab door overlaps the closed door, making closing the door behind you difficult.

**Comment by LetterN** [comment]
layering, REEEEEEE

**Comment by ShizCalev** [comment]
Round ID???? .

**Comment by ShizCalev** [comment]
Firedoor issue was fixed, servers haven't been updated in 3 days.
