### ISSUE TITLE
Lings that switch out from being a slime species via transformation lose their spare bodies

### ISSUE THREAD

**Issue by vuonojenmustaturska** [tgstation/tgstation#35721]
Bug reported to me on discord by lmienny.

This seems to be "working as intended" as https://github.com/tgstation/tgstation/blob/a104bffd8b954b66f4996bd515b5679f4ebfe230/code/modules/mob/living/carbon/human/species_types/jellypeople.dm#L123 removes the actions and the spare bodies, however it is a bit nonintuitive.

Should we disable lings gaining species abilites as they're not really a member of those species but rather merely superficially masquerading as them, leave everything as is or refactor ling transformations to keep carry species datum state around so that spare bodies etc can be used?

**Comment by XDTM** [comment]
I'd go with refactoring ling into their own species

**Comment by Kerbin-Fiber** [comment]
ditto

**Comment by TheBonded** [comment]
Changing species from being a slimeperson disconnects you from your other bodies. This is intended and thus not a bug
