### ISSUE TITLE
when wearing cardborg stuff picking up another cardborg item or putting it in a container causes you to cease looking like a borg

### ISSUE THREAD

**Issue by iamafsh** [tgstation/tgstation#35748]
1. put on cardborg suit and hat
2. you look like borg
3. get another suit/hat and put it in your hand
4. you no longer look like borg?

**Comment by dragomagol** [comment]
Appears to have been fixed (still appear as a cyborg to yourself and to actual cyborgs while holding additional cardborg items)

**Comment by dragomagol** [comment]
Scratch that, it removes your disguise when you put the items back in your bag. Just not when holding them.

**Comment by etherware-novice** [comment]
will work on this
