### ISSUE TITLE
Meteor survival information is incorrectly styled in round-end report

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#35749]
Box is missing.

![image](https://user-images.githubusercontent.com/222630/36337340-e2a7c308-1348-11e8-9f22-d579105f5fc3.png)

a2ccca5f9624f9182704b9ee3abde78958461988

**Comment by ShizCalev** [comment]
Should it be indented? Not quite sure what what is incorrect about that as it's the `neutraltext` formatting

**Comment by SpaceManiac** [comment]
All the other antag groupings have boxes around them, this one doesn't.

**Comment by ShizCalev** [comment]
Oh yeah, this'll be an issue with anything using special_report() then 
@AnturK

**Comment by AnturK** [comment]
I forgot to readd it when i made wrappers antag responsibility.
