### ISSUE TITLE
Newton's second law: A object in motion will tend to stay in motion. Unless its in space.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#35747]
See title, some things will not properly keep momentum, losing it after a seemingly random amount of time flying through space. They don't stop completely, instead just reverting to the normal speed things drift at in space.

Observed examples of this:
1: Bodies thrown into space
2: Bubblegum charging through space.

**Comment by Poojawa** [comment]
This happens for z level changes, but I imagine it's also for the sake of the master controller not to seizes up and fall limp trying to count for every single object.

Lord Singuloth isn't the primary engine anymore partly because of that.

**Comment by Buggy123** [comment]
With bubblegum at least, it isn't on z-level changes. He'll go through several z levels, and then stop at a random point in the middle of one. Haven't seen enough bodies to tell if it's the same.

**Comment by Buggy123** [comment]
Can confirm this will also occur with items.
