### ISSUE TITLE
Wizard can have unlimited time of Mutate spell.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#35758]
[Reproduction]: You can have unlimited time of Mutate spell. All you need is learn Mutate once, activate it and refund it. You have 10 points and hulk form with laser eyes for free.

**Comment by Shadowflame909** [comment]
this is a bad cheat. that needs to be fixed B A D G I M M I C K

**Comment by BlueNothing** [comment]
B L A C K M A G I C K
