### ISSUE TITLE
Damaged snow tiles have no icon

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#35750]
Produced by landing the emergency shuttle at the syndicate base and C4ing one of the walls. Welding the tile fixes the icon.

![image](https://user-images.githubusercontent.com/222630/36338111-70a92310-135b-11e8-8f1d-01666c23704e.png)

a2ccca5f9624f9182704b9ee3abde78958461988

**Comment by factoryman942** [comment]
also >weld dents in snow

**Comment by MMMiracles** [comment]
if you keep welding the dents soon there won't be any snow left to be dented
