### ISSUE TITLE
Stacks with amount-variant icons lose their inhands.

### ISSUE THREAD

**Issue by RandomMarine** [tgstation/tgstation#35755]
Stacked items such as metal and glass that change their icons based on their amount are invisible inhand while they're at amounts that change their icon away their base.

For example, metal at amount =<16 have the old ```sheet-metal``` icon, which have inhands.
But anything over that changes the stack's icon to ```sheet-metal_2``` or ```sheet-metal_3```, which lack inhands.

**Comment by ShizCalev** [comment]
Going through and adding a number of missing inhands as well.
