### ISSUE TITLE
Wizard can duplicate items, which allows apprentices usage of duplicated items.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#35757]
[Reproduction]: Wizard can duplicate any item possible, if they will use Instant Summons with Shapechange. Anyone will be able to pick that item up and use it with Wizard. Wizard can even dual weld summoned items with hotkeys. Miners can do that trick too if they got magic book from loot chest.
![123](https://user-images.githubusercontent.com/34580767/36339419-0750ba24-13d6-11e8-8787-83e37ff8f6e1.png)

**Comment by ExcessiveUseOfCobblestone** [comment]
is it a true dupe or a "1 item 2 locations" thing

**Comment by IllotAFV** [comment]
More like one item in two locations, because after shapechanging back to normal wizard form, Wizard is loosing their recalled item.

**Comment by Daxxed** [comment]
It seems to be a bug with sprites staying on your screen after you lose them to a summon.
The item is not duplicated, it is just summoned below you when you use it as a simplemob, but the sprite stays in your bag/hands/whatever.
Discovered this when properly testing hilberts hotel, the hotel would be visible in my hands or bag but be long gone into space.
