### ISSUE TITLE
Sprite issues when ore stacks get high.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#35767]
Issue reported from  Round ID: 83770 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 511

![dreamseeker_2018-02-17_14-23-34](https://user-images.githubusercontent.com/33107541/36344844-374277aa-13ee-11e8-9e9b-71634e39e5db.png)

**Comment by MoreRobustThanYou** [comment]
420
