### ISSUE TITLE
Engiborgs can‘t create airlock electronics

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#35766]
As the title says: Engiborg adaptive pseudocircuits don‘t include airlock electronics.

**Comment by Xhuis** [comment]
This was intentional, since airlock electronics require configuration and so aren't "simple" circuits. They also have inbuilt RCDs which can already create airlocks.

**Comment by ShizCalev** [comment]
Intentional
Duplicate of #31018
