### ISSUE TITLE
Borg internal radio broadcasts out to three tiles over loudspeaker

### ISSUE THREAD

**Issue by CameronWoof** [tgstation/tgstation#35774]
Tested with the assistance of Togopal in Round ID: 83780.

Reproduction steps: install an encryption key into a cyborg. Standing next to them, or up to three tiles away from them, allows you to hear all messages sent over that encrypted channel.

It's worth noting that setting the cyborg radio's speaker to OFF makes them unable to hear or speak over the department radio entirely; that is not the solution to the issue.

**Comment by SpaceManiac** [comment]
Borg radios need a full redo, the "Subspace Transmission" flag has no reason to exist since turning it on just makes the radio stop working if telecomms is down with no upside to speak of.
