### ISSUE TITLE
Syndicate assault pod's status is "missing" even after using the targeting device

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#35776]
1. ~~See the targeting device on 90% discount, costs only 3 TC~~
2. Buy the targeting device
3. Use the targeting device to choose the area
4. Open the assault pod interface
5. It's listed as missing
6. ~~The pod needs to be adminbused in~~
7. ~~It's a mining pod with no turrets~~
8. ~~The crew overpowers us, and we end up as flukes.~~

It gave us a funny story, but this really needs fixing.

**Comment by SpaceManiac** [comment]
Gonna take a wild guess that the pod's docking port needs a helping of `timid = 0`.
