### ISSUE TITLE
you can determine the name of a stealthmin if they bwoink you

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#35781]
being bwoinked by them shows "Admin PM from- Administrator", but clicking on them to reply shows "Private message to [username]"

**Comment by Kerbin-Fiber** [comment]
Feauture

**Comment by CitrusGender** [comment]
oh god

**Comment by Stickymayhem** [comment]
Holy fuck how did no one spot this stealthmin has literally been a lie for years

**Comment by Jalleo** [comment]
I think this has already been reported before....
