### ISSUE TITLE
AI unplayable

### ISSUE THREAD

**Issue by AcuteCircle** [tgstation/tgstation#35788]
Literally can't play as AI. I tried both byond 511 and 512. Every time I pressed to track someone, either "F" next to their name or from new crew monitors, game crashed.

**Comment by praisenarsie** [comment]
@MrStonedOne

**Comment by BeeSting12** [comment]
I reproduced this in BYOND 512 but I didn't get the exact version number.

**Comment by Kerbin-Fiber** [comment]
This happened to me a long time ago but for some reason, it stopped. It happened as a ghost when I tried to follow someone every time without fail. About a year ago.

**Comment by Ordonis** [comment]
Have observed, pretty sure it's a BYOND issue; cameras/eyes in general have been unstable.

**Comment by MrStonedOne** [comment]
the most recent 512 version *should* fix the issue

**Comment by kriskog** [comment]
Doesnt seem to be happening anymore.
