### ISSUE TITLE
Xenobiology computer crashes game

### ISSUE THREAD

**Issue by Shadowizard** [tgstation/tgstation#35787]
[Round ID]: 83800

[Reproduction]: All I did was try to do xenobiology; the game crashed as soon as I clicked on the computer. Running 512 if that helps. Round ID 83800

**Comment by newfren** [comment]
Report this badboy here: #34862 

and try downgrading to 511

**Comment by WJohn** [comment]
Dupe or at least related to #33377. This has been around for a good while now.
