### ISSUE TITLE
You can take shit out of peoples storages as a ghost.

### ISSUE THREAD

**Issue by GuppyLaxx** [tgstation/tgstation#35789]
The following pull requests are currently test merged:
#33166: '[READY]Refactors storage handling from /obj/item/storage to a component.' by kevinz000 at commit 86e4f4
#35609: 'Mandatory pre-Valentines handholding PR for testmerge' by kevinz000 at commit 6dc0ac
#35535: 'Adds the Monk Martial Art to the Chaplain's null rod selection' by Iamgoofball at commit d1eee3

Alt+click any storage like boxes, bags, even shoes, and the first item will be taken out
This can be done as a ghost, specially while observing, was used to fuck a nukies round over with the disk being constantly taken out

**Comment by Buggy123** [comment]
OH WOW THIS IS WAY WORSE THAN JUST TAKING ITEMS OUT OF BOOTS

**Comment by praisenarsie** [comment]
@ShizCalev

**Comment by LetterN** [comment]
this is worst that arrivals announcement getting spammed by WGW over comms

**Comment by ShizCalev** [comment]
roundID?

**Comment by Cyberboss** [comment]
It's certainly #33166

**Comment by ShizCalev** [comment]
Yeah can't repo on master, it's #33166
