### ISSUE TITLE
Fulton packs have no message when applying them to someone

### ISSUE THREAD

**Issue by Catistian** [tgstation/tgstation#35783]
Issue reported from  Round ID: 83793 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Step one: Be in medbay

Step two: Someone pulls a white parachute over your head

Step three: You're now in some maint hell with lava.

Theres no way to avoid this besides never standing still ever

**Comment by Teepeepee** [comment]
Fultons are not supposed to work inside though.

**Comment by 81Denton** [comment]
That sounds like a turf issue, they're only supposed to work in space/lavaland etc.

**Comment by Robustin** [comment]
It displays the Fulton attack animation though.

The biggest bug is that it makes you go invisible and the balloon goes sideways while active.

This was with a balloon that can work indoors (var-edit) but the fundamental issues are all still there.
