### ISSUE TITLE
Megafauna do not aggro Circuit drones

### ISSUE THREAD

**Issue by Poojawa** [tgstation/tgstation#35795]
Megafauna should probably destroy everything moving that isn't a lavaland citter or food.

I just watched a player construct a type A drone with at least 8 cutters on it, and set it loose on lavaland. the megafauna never retaliated the whole time.

completed drones should probably either turn into a mob when 'completed' and on, or have special acts to be ioned/targeted/dealt with.

**Comment by LetterN** [comment]
because they aren't `/mob`, they are `/obj`
mobs get aggroed by megafauna
objects dont

**Comment by Kromgar** [comment]
Oh no

**Comment by ExcessiveUseOfCobblestone** [comment]
still better than killer tomato spam

**Comment by ShizCalev** [comment]
fixed apparently.
