### ISSUE TITLE
You can warp under airlocks as Clockwork Cultist. It hides nearly all teleportation effects.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#35790]
I am not sure about this, maybe this is intended. But you can warp under airlock. Airlock will cover 80% of all teleportation effects. You need to be very caution to actually see that warping Cultist. And then Cultist can just stun you out of nowhere.

**Comment by ChangelingRain** [comment]
weren't abductors able to do this, too

**Comment by Potato-Masher** [comment]
Pretty much anyone who can teleport in jaunt-like can do this. It's been no secret.

**Comment by itseasytosee** [comment]
Clockcult is dead long live clock cult
