### ISSUE TITLE
Technical question about Linux Server

### ISSUE THREAD

**Issue by davv1** [tgstation/tgstation#35801]
Is that normal, if, on 512.1407, Linux distro, I get very often server crashes? If yes, is there any way to avoid them, or to log them, so contributors could bug them out?

**Comment by davv1** [comment]
Also, is that possibility I only "git pull" and "DreamMaker" when I want to update?

**Comment by praisenarsie** [comment]
@Cyberboss

**Comment by davv1** [comment]
After reinstalling github repo from scratch(github clone), and compilling, problem still persist, I've got frequent random crashes of server during gameplay.

**Comment by davv1** [comment]
What things you need to help with reproducing this one? @ShizCalev

**Comment by Jalleo** [comment]
This is something you should take to the Byond forums instead of here it sounds like there are problems with the Linux Byond.

**Comment by davv1** [comment]
I will try to test if this still persist between saved states, both on Ubuntu and on container(Docker).
