### ISSUE TITLE
Pubbystation firelock issues

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#35816]
Atmos fire alarm:
https://i.imgur.com/h8FJeli.png
1) The atmos fire alarm only toggles two of the S/W reinforced atmos firelocks instead of all four.
2) There is no firelock to cover the atmos monitoring room's plastic flaps. I'd suggest either adding one or switching them out for /obj/structure/plasticflaps/mining.

Engineering fire alarm:
https://i.imgur.com/YmsJQ4q.png	
1) The engineering fire alarm toggles a bunch of the reinforced atmos firelocks to the east, instead of just the ones belonging to its own department.

**Comment by 81Denton** [comment]
Let me take better screenshots in an hour

**Comment by ShizCalev** [comment]
Will fix after my camera PR is merged.

**Comment by 81Denton** [comment]
The main atmos airlock also has a firelock on top (engineering doesn‘t). No clue if intended or a mapping oversight.
