### ISSUE TITLE
Supply shuttle conveyor belts don't work

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#35817]
Conveyor belts on supply shuttles don't work. Is that intended?
https://i.imgur.com/MkWFzGm.png

**Comment by Tlaltecuhtli** [comment]
uhhh did u turn on the belts when the shuttle was away ? if yes not a bug

**Comment by 81Denton** [comment]
Let me test in 20 minutes

**Comment by 81Denton** [comment]
The pubby supply shuttle belts don't work no matter when you turn them on. Let me test if that happens on other maps too.

**Comment by 81Denton** [comment]
Looks like they don't work in general, tested it on Meta/Pubby so far

**Comment by ExcessiveUseOfCobblestone** [comment]
them not working at all is a bug, they're not meant to stop when the shuttle leaves.

**Comment by SpaceManiac** [comment]
Caused by #33766, the shuttle is loaded in after the switch initializes and it doesn't get the newly created conveyor added to its list.
