### ISSUE TITLE
Quintuple sec is impossible to make

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#35814]
150 hours of testing folks. Clown's Tears is a soup which isn't a reagent, so you can't add it to the drink. Grinding it just gives banana juice and potassium and shit. Soup can't be poured.

@Ordonis

**Comment by Ordonis** [comment]
It does have a reagent, specifically added to make it possible to make, if it isn't working I will go fix this, although for what it's worth spawning the clowntears reagent does work


fix inc later today if repro-able

**Comment by Ordonis** [comment]
Container changes reeeeeee but this should fix it
