### ISSUE TITLE
dragging things in space breaks your grab when you change zlevels

### ISSUE THREAD

**Issue by AlexTheSysop42** [tgstation/tgstation#35813]
Issue reported from  Round ID: 83850 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

I was exploring space with an oxycan to refuel my jetpack but whenever I changed zlevels it was a pain to regrab

**Comment by AlexTheSysop42** [comment]
It worked for a while but I think something in the past few days broke it

**Comment by AlexTheSysop42** [comment]
updated title because it happens with SCP-294 as well

Also re-updated because spelling error

**Comment by Davidj361** [comment]
Worked 2 days ago for me.

**Comment by AlexTheSysop42** [comment]
fixed in #36587
