### ISSUE TITLE
abductor teleport puts you in space

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#35815]
got sent back from an abductor and I got put in space where shuttle docks and died, still asleep and shit. Kind of not how safe teleports are supposed to work

**Comment by coiax** [comment]
Abductor teleports don't use any form of "safe teleportation" selection. It's just where they decide to dump you. They SHOULDN'T be trying to kill you with where they put your experimented body.

**Comment by Repukan** [comment]
IC issue

**Comment by ShizCalev** [comment]
IC issue.
