### ISSUE TITLE
Gold slime blood reactions are broken. (And others.)

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#35827]
[Round ID]: #83880
Server: Sybil

STEPS TO REPEAT DISAPPOINTMENT, STEP 1: get golden slime extract (also works with orange slime extract, and red)
2: inject blood into the golden slime extract.

3: Have extract disappear and nothing happens, just the reaction sound plays. And then it's poof. :( (Someone fix this MY XENOBIO IS DED)

**Comment by Kromgar** [comment]
Might have to do with Astar testmerge on sybil? 

#34713

**Comment by Kromgar** [comment]
@arsserpentarium

**Comment by arsserpentarium** [comment]
I've seen it before testmerge.so, no.also, there is no a* calling in anything related to cores.

**Comment by XDTM** [comment]
Probably related to someone calling ..() before the reaction is done, deleting the core. I'll check if someone's touched it.

**Comment by Shadowflame909** [comment]
Yeah, I think it was a testmerge. Closing issue.
