### ISSUE TITLE
Ninja clothes are sticky

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#35826]
Ninja clothes keep their nodrop on when the ninja explodes and loses them, so anyone who picks it up has the clothing stuck to their hands or wherever its equipped to

**Comment by DaxDupont** [comment]
feature

**Comment by YPOQ** [comment]
NODROP items should probably lose NODROP if they are forced to be dropped since there are several ways for this to happen (cursed items wizard event + dismemberment).

**Comment by AlexTheSysop42** [comment]
Oh yeah that round, I picked up the gloves but I was a free golem so they couldnt be put on

There should probably be a seperate "sticky" flag that makes it so you can drop things but not take them off

**Comment by Kromgar** [comment]
One time i picked up the eyes of god twice in a round. It was awful i had an eye i couldn't drop. Funnily enough i got a pr so you could stack eyes of gods

**Comment by dragomagol** [comment]
Still an issue after the rework
