### ISSUE TITLE
signaller +IR beam and signaller + proxy sensor assemblies don't work

### ISSUE THREAD

**Issue by AlexTheSysop42** [tgstation/tgstation#35829]
Issue reported from  Round ID: 83879 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

In addition, proxy sensors dont work when attached to a wire

Strangely, voice analyzer + signaller assemblies work just fine

**Comment by PortalVector** [comment]
That's a lot of +

**Comment by SpaceManiac** [comment]
Proximity sensors completely stop working the moment you put them in an assembly or a bag or anything like that. Haven't investigated IR sensors.

**Comment by AlexTheSysop42** [comment]
scratch that, VA/Signaller assemblies also have issues sometimes

**Comment by ShizCalev** [comment]
![image](https://user-images.githubusercontent.com/6209658/39539884-02ed073a-4e0f-11e8-9dc6-9d889d321a06.png)
i fucking wonder why proxy sensors broke.

i'll have a PR up for this fixing all of them later tonight.
