### ISSUE TITLE
Unlimited spraycans.

### ISSUE THREAD

**Issue by Childflayer** [tgstation/tgstation#35833]
[Round ID]: #83906

If you use a spraycan to paint a letter on the floor then switch it to "paint" or one of the other large horizontal graffitis (Doesn't seem to work with the small ones), it will keep applying paint while still displaying the "it doesn't have enough paint left" message. Does not work if you don't first put at least one letter on the floor. Switching it to anything else after that stops it, as does dropping it and picking it up, using it to spray a person in the face or color a window.

**Comment by Shadowflame909** [comment]
>editing spray cans. I feel like any potential fix for this will end up breaking service borg spray cans...
