### ISSUE TITLE
some hats ignore "top" hair

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/tgstation#3583]
![detectivehat](https://cloud.githubusercontent.com/assets/701959/2838157/7d5cda54-d02d-11e3-9274-ca599f6a457e.png)
depending on the hair that you're using and the hat, the hair can go above the hat, unrealistically.
The detective's hat is one of the most noticeable and most common and probably the big afro breaks all hats

**Comment by tedward1337** [comment]
Lmao is that a picture of the IC character I use? (Long fringe, blue hair)
Also has anyone fixed this?

**Comment by ExcessiveUseOfCobblestone** [comment]
just make it a larger hat?

**Comment by PKPenguin321** [comment]
That won't work because some hair styles like big afro can't be covered adequately by just making the hat bigger

**Comment by InsaneHyena** [comment]
Holy shit, it's fixed.

**Comment by PraiseRatvar** [comment]
@WJohn why isn't this closed

**Comment by Cyberboss** [comment]
@lzimann
