### ISSUE TITLE
floor safe issues.

### ISSUE THREAD

**Issue by Zaffinomlb** [tgstation/tgstation#35834]
Issue reported from  Round ID: 83906 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Round ID]: 83906

[Reproduction]: old cryogenics pod security spawn from join observe, at space ruin with blood red hardsuit "floor safe". When attempting to crack safe, safe window interface failed to refresh and display current dial #. Frankly I do not know if this is by design, the dial sound still works. So because of this hacking is far faster for experienced, so I frankly would like this change to remain,

[For Admins]:-- Administrator private message --

Admin PM from-Nabski: Do you see in the upper right where it says report issue? Go there and do it. If you link me to it after I'll give you a reward

**Comment by Tacolizard** [comment]
can we just remove safes? they've been broken for a really long time

**Comment by Zaffinomlb** [comment]
They arent broken anymore.
