### ISSUE TITLE
"Butt"on don't show their names when i push it

### ISSUE THREAD

**Issue by PortalVector** [tgstation/tgstation#35831]
Issue reported from  Round ID: 83889 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

[Reproduction]: # Push a button on a circuit

The name of the button don't show when i push it (name is the button or the toggle button).

**Comment by arsserpentarium** [comment]
I'll make fix PR.

**Comment by AverageJoe82** [comment]
is this still an issue?

**Comment by PKPenguin321** [comment]
not a bug/was likely fixed at some point, close

**Comment by SpaceManiac** [comment]
Circuits have been removed.
