### ISSUE TITLE
No Circuit Lab in PubbyStation

### ISSUE THREAD

**Issue by PortalVector** [tgstation/tgstation#35850]
Issue reported from  Round ID: 83935 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

[Reproduction]: # Start a round on Pubby 

👎  Please add circuitry lab to Pubby.

**Comment by ShizCalev** [comment]
Feature request.

(I'll add it once my cameras PR is merged, along with fixing the firedoors in engineering.)
