### ISSUE TITLE
Whispering in cloning pods gets you ejected.

### ISSUE THREAD

**Issue by Dieknon** [tgstation/tgstation#35851]
Round ID: 83938

Reproduction: Whisper while being cloned. You should get instantly ejected from the cloning pod.

**Comment by ExcessiveUseOfCobblestone** [comment]
> deathwhisper in the pod
> surprised when you die

STOP TRYING TO BREAK THE GAME REEEEEEEEEEEE

**Comment by ShizCalev** [comment]
Should probably also check to make sure they aren't in a sleeper as well.

**Comment by Kromgar** [comment]
Isn't the cloning pod supposed to give you mime's bane?

**Comment by 81Denton** [comment]
Mime's bane only stops you from emoting. Would adding mutetoxin to the brine work as a ghetto fix?

**Comment by ShizCalev** [comment]
@81Denton Should be fine.
