### ISSUE TITLE
Cybernetic limbs are effected by damage the same way has organic ones?

### ISSUE THREAD

**Issue by david425** [tgstation/tgstation#35860]
Cybernetic limbs on tg's codebase at least are effected by toxins damage still

And when there burned or hit for some reason they dont get dented and they have to be healed by patches like organic ones do

plz fix

*note* wait if were going by borg logic cybernetic limbs shouldent be effected by heat or fire at all and just brute

**Comment by XDTM** [comment]
Toxin damage is not limb based

**Comment by PortalVector** [comment]
Toxin affect only your health in general, not a limb

**Comment by kriskog** [comment]
Not a thing anymore, robotic limbs need to be repaired with tools.
