### ISSUE TITLE
Being space lubed into a disposals chute bugs out horribly

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#35864]
The character is stuck in place unable to do anything but spin until an outside force unscrews and dewelds the chute.

![lube](https://user-images.githubusercontent.com/222630/36467489-d6857914-1693-11e8-93a2-65c9f66718e9.gif)

Also it makes noise the entire time.

a2ccca5f9624f9182704b9ee3abde78958461988

**Comment by AlexTheSysop42** [comment]
oh yeah that, I saw someone discover that on a downstream a few months ago but didn't know I could report an issue here at the time

you can also free the person by dragging them to the side and past the disposal (so down and to the side here), but it doesn't work with walls behind it

**Comment by iskyp** [comment]
never fix this please

**Comment by dragomagol** [comment]
Appears to have been fixed (you no longer spin infinitely, just stop at the disposals chute)
