### ISSUE TITLE
Ridden secways don't teleport correctly

### ISSUE THREAD

**Issue by pubby** [tgstation/tgstation#35872]
I tried to enter a teleporter while riding a secway. The secway got teleported but my character did not. I remained buckled and stuck to the floor.

**Comment by AlexTheSysop42** [comment]
yeah this happens with any vehicle (seen with bikes with tele and ATV with gateway) it fixes if you try to move around a bit or unbuckle IIRC

**Comment by YPOQ** [comment]
Probably the same underlying issue as #20113

**Comment by KorPhaeron** [comment]
@kevinz000
