### ISSUE TITLE
Storing advanced surgery disks in a bag changes their names to "Surgery Procedure Disk"

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#35888]
Issue reported from  Round ID: 84004 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 511

Unless i'm remembering wrong before putting them in the bag they had the name of the procedure they were storing

**Comment by XDTM** [comment]
how

**Comment by Kromgar** [comment]
Fuck if i know how

**Comment by SailorDave** [comment]
From what I can see, the disks have never had specific names outside of the protolathe screen? It's always been Surgery Procedure Disk. I can change this.
