### ISSUE TITLE
Night shift announcement occurs before roundstart.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#35881]
Logs, from Round ID: 83995, Sybil.

OOC: Coconutwarrior97: Im good how are you

OOC: BeeSting12: Doing great, you?

OOC: Nervere: OOH OOH AH!

Automated Lighting System Announcement

Good evening, crew. To reduce power consumption and stimulate the circadian rhythms of some species, all of the lights aboard the station have been dimmed for the night.

Starting game...

The gamemode is: secret!
Possibilities: clockwork cult, cult, secret extended, traitor, traitor+changeling and wizard

OOC: Cthulusbro: oh god not monkey round

OOC: Newbie256: I'm getting better

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: 83995

Server revision compiled on: 2018-02-20

The following pull requests are currently test merged:
#34713: '[READY]Astar improvement' by arsserpentarium at commit 33cd64
#35775: '[READY]Randomized Station Time + Night Shifts' by kevinz000 at commit b1b186

Based off origin/master commit: 06dd1b

Revision: 7d765d76d5b9a78ffcee20cc3d8583755cc0498a

Server tools version: /tg/station 13 Server v3.2.1.11

Server tools API version: 3.2.0.2

Current Informational Settings:

Protect Authority Roles From Traitor: 1

Protect Assistant Role From Traitor: 0

Enforce Human Authority: 1

Allow Latejoin Antagonists: 1

Enforce Continuous Rounds: 8 of 17 roundtypes

Allow Midround Antagonists: 6 of 17 roundtypes

All Game Mode Odds:

traitorchan 24%

traitor 18%

clockwork_cult 8%

cult 8%

secret_extended 2%

nuclear 16%

revolution 12%

wizard 12%

**Comment by ShizCalev** [comment]
@kevinz000

**Comment by timothymtorres** [comment]
I believe this was fixed by #36173
