### ISSUE TITLE
Whiskey Sours make no noise when brewed.

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#35898]
[Round ID]: # 84013
#34713 #35775 

It should make a noise.

**Comment by AnturK** [comment]
It has the sound explicitly removed, not sure if it's intended.

**Comment by ShizCalev** [comment]
hearty_punch does too, that's strange.

**Comment by ShizCalev** [comment]
@Xhuis You added 'em, any reason to keep them this way?

**Comment by Xhuis** [comment]
Don't see why they need to have no sound. Hearty Punch is pretty much out of my hands at this point as to how I change it, but it'd be pretty easy to add a sound.
