### ISSUE TITLE
Bullets are interacting weirdly with map edge on lavaland

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#35890]
Issue reported from  Round ID: 84004 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 511

![image](https://user-images.githubusercontent.com/6778786/36519198-2c1842a2-1758-11e8-896b-b396c3d1e9e1.png)

#34713: '[READY]Astar improvement' by arsserpentarium at commit 33cd64
#35775: '[READY]Randomized Station Time + Night Shifts' by kevinz000 at commit b1b186

**Comment by ShizCalev** [comment]
@kevinz000

**Comment by Kromgar** [comment]
Before they used to just bounce off the edge ofthe world and occasionally cut off my legs

**Comment by Kromgar** [comment]
![image](https://user-images.githubusercontent.com/6778786/36553559-a2d55778-17ca-11e8-8119-0146a182dbd2.png)
![image](https://user-images.githubusercontent.com/6778786/36553569-a60e39a0-17ca-11e8-990e-801f49b7d2dc.png)

**Comment by kevinz000** [comment]
fixed
