### ISSUE TITLE
Beepsky also can control the flow of time.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#35893]
Found this while testing on local. Beepsky is seemingly immune to the time stop spell. Not sure if this is the case on the master.

![dreamseeker_2018-02-22_00-40-34](https://user-images.githubusercontent.com/33107541/36522212-467d1ac6-1769-11e8-89ab-72715cb4ed5f.png)
![dreamseeker_2018-02-22_00-40-55](https://user-images.githubusercontent.com/33107541/36522216-4c140c88-1769-11e8-9310-ae1217ee4f6b.png)

**Comment by Ratvar** [comment]
Beepsky is supreme, not a bug

**Comment by Anonmare** [comment]
If you can't do the crime, don't do the time

**Comment by LetterN** [comment]
[ feature ]

**Comment by YakumoChen** [comment]
NO, YOU FREEZE, SCUMBAG

**Comment by Ordonis** [comment]
THREE SECONDS HAVE PASSED.

**Comment by AverageJoe82** [comment]
FOUR SECONDS HAVE PASSED.

**Comment by nemvar** [comment]
Fixed by #42933
