### ISSUE TITLE
Pirate loot values are off

### ISSUE THREAD

**Issue by yorii** [tgstation/tgstation#35897]
[Round ID]: 83993

[Reproduction]: Loot 200-credit bills or diamonds, get super bad loot value.

Loot stolen: 
18 gold bars, 12 diamonds, 1080 two hundred credit bills
Total loot value : 13144/50000 credits
The pirate crew has failed.

I think the bills might not have any value at all, since 1080x200=216000, and diamonds seem to not be worth much at all?

**Comment by 81Denton** [comment]
It looks like the pirate event bases loot value off the cargo export value. Bills/coins have no value at all, blame cargo nerfs for that.

**Comment by AnturK** [comment]
I'll have to do some revamp on that loot counter anyway.

**Comment by 81Denton** [comment]
@AnturK Would it make sense to define cargo export/loot value by type instead of export lists?
I mean similar to how @Xhuis did it with grindables in #33181.

**Comment by Jalleo** [comment]
Cargo exporting money was removed due to balance reasons I believe.

**Comment by Iatots** [comment]
Just make cargo points into bitcoins, and rebalance the vault money to be an emergency fund for red alerts to be exchanged as needed. Also, turn pirates into deep space """miners"""

**Comment by ExcessiveUseOfCobblestone** [comment]
@81Denton  components would probably be more appropriate since some items have unique exporting "rules"

**Comment by MimicFaux** [comment]
Pirates keeping the pirate flavour is fun.

**Comment by yorii** [comment]
Round 85446:

![image](https://user-images.githubusercontent.com/7960287/37860819-a86988ec-2f2d-11e8-924c-09acf179fcfa.png)
