### ISSUE TITLE
You can earn enough points to research every RnD tech within 15 minutes of round start, if you make big enough bombs.

### ISSUE THREAD

**Issue by Polyphynx** [tgstation/tgstation#35909]
Round ID: 84030

You can now earn research points by blowing toxins bombs up at the launch site. It makes sense that making bigger bombs gets you more points. 
But if you know how, you can make extremely large bombs in 15-20 minutes, and earn enough points to research everything.

Which is what happened this round. These were the two bombs

![b3](https://user-images.githubusercontent.com/18168689/36561794-1dd899fe-1815-11e8-8292-96df9004442b.png)

**Comment by XDTM** [comment]
jesus that's twice the nuke explosion radius

**Comment by ExcessiveUseOfCobblestone** [comment]
> 285 devastation

that's larger than the zlevel lol.

**Comment by ExcessiveUseOfCobblestone** [comment]
@DaedalusGame @kevinz000

**Comment by DaedalusGame** [comment]
i will fix this in a moment give me a second

**Comment by ExcessiveUseOfCobblestone** [comment]
It better endup with the array overloading and exploding hehe

**Comment by MrStonedOne** [comment]
The solution here is actually to make it so you can't get a fucking 285 dev explosion at 15 minutes in.

**Comment by LetterN** [comment]
cuban pete

**Comment by ExcessiveUseOfCobblestone** [comment]
Where's the PR that changes bomb formula
