### ISSUE TITLE
Can't rotate doppler arrays

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#35903]
As the title says, you can't rotate tachyon doppler arrays.

Initial issue was #28979; PR #29174 supposed to fix it.

**Comment by SpaceManiac** [comment]
You have to unwrench it, alt-click to rotate, and wrench it down again before the sprite updates.

**Comment by 81Denton** [comment]
That's not so bad then, I'll just have to update the desc.

**Comment by DaedalusGame** [comment]
didn't these use to rotate while wrenched

**Comment by 81Denton** [comment]
Yeah

**Comment by 81Denton** [comment]
They rotate when unwrenched, that's good enough
