### ISSUE TITLE
Rainbow Clusterbang slime cores can't go into bio bags or the fridge 

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#35908]
![image](https://user-images.githubusercontent.com/6778786/36556831-7ec0b256-17d4-11e8-8465-262e4986ff01.png)

They are EXTREMELY fucky. You can pick one off the floor and it will still show up on teh floor but it might move a few tiles to the west or east. This was on the NON VIOLENT option.

Also the cores could not be absorbed by luminescents. Occasionally some cores would not react to any chemicals while others would react.

**Comment by DaedalusGame** [comment]
what the fuck did you do to my baby

**Comment by Kromgar** [comment]
@DaedalusGame No they just move when you pick them up and some of them refused to go in the disposals bin

**Comment by DaedalusGame** [comment]
sounds like all of these are related to clusterbusters so it's time for another round of fixin
