### ISSUE TITLE
delta minisat teleporter doesnt work

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#35916]
00:05:37: Nursk/(SL4VE): teleporter is broken again
00:05:43: PM From BeeSting12/(Edward Sloan): what 
00:05:54: Reply PM from-Nursk/(SL4VE): the minisat teleporter is broken again 
00:06:09: Reply PM from-Nursk/(SL4VE): dosnt make portals 
00:06:28: PM From BeeSting12/(Edward Sloan): How to fix it? 
00:06:47: Reply PM from-Nursk/(SL4VE): i think its a code issue, gotta bring it up to one of them 
00:06:55: PM From BeeSting12/(Edward Sloan): Make an issue report on github 
00:07:11: Reply PM from-Nursk/(SL4VE): no idea how, and its only on this map so w/e 

round id 84046
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 84046

Server revision compiled on: 2018-02-22

The following pull requests are currently test merged:
#33166: '[READY]Refactors storage handling from /obj/item/storage to a component.' by kevinz000 at commit 3ca319

Based off origin/master commit: a635d5

Revision: cf51901d2f4e17184211996c2b3916746134e470

Server tools version: /tg/station 13 Server v3.2.1.11

Server tools API version: 3.2.0.2

**Comment by SpaceManiac** [comment]
No repro on a635d5835af9ab88f01e8e8aa09fecea83bb44e4

**Comment by ShizCalev** [comment]
Issue with testmerge #33166
