### ISSUE TITLE
Cleanbot AI seems to be broken

### ISSUE THREAD

**Issue by Anonymous583** [tgstation/tgstation#35919]
Issue reported from  Round ID: 84063 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

Robotics lab was a complete mess at roundstart due to oilspill and footprints everywhere, created two Cleanbots to clean the mess. Both Cleanbots hovered over the oil several times but never interacted with it, occasionally making the "Cleanbot makes an excited beeping booping sound!" line but never actually doing anything. I turned on all options to see if it would work, no dice. Once I enabled them to patrol the staton they left the room as if there was no mess.

**Comment by ShizCalev** [comment]
#34713 @arsserpentarium

**Comment by arsserpentarium** [comment]
Got it.

**Comment by Poojawa** [comment]
Confirming this down stream, watched a clean bot just sorta, meander around the room filled with bloody footprints. turning on the clean bot's override moved them to attack someone with acid as expect.

**Comment by arsserpentarium** [comment]
I've found,what's problem. I'll make PR soon.

**Comment by arsserpentarium** [comment]
Is there problems with another mobs?
