### ISSUE TITLE
kudzu can be double vine eating

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#35915]
An extremely expansionistic species of vine. 
This one is a **vine eating** flowering **vine eating** vine. 
round 84043

**Comment by ExcessiveUseOfCobblestone** [comment]
I think we call that a murderbone

**Comment by LetterN** [comment]
This one is a vine eating flowering vine eating flowering vine eating flowering vine eating flowering vine eating flowering vine eating flowering murderboning vine vine.

**Comment by arsserpentarium** [comment]
Feature
