### ISSUE TITLE
Something spammed huds causing the server to hang [R 84086/5 Bagil]

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#35929]
Something was causing add_to_single_hud and remove_to_single_hud constantly to the point where a million calls were occurring within a few minutes.

The only insight I was able to gain was that some people were doing skewium nade memes. Not sure if that was the issue but probably wise to include it here.

**Comment by AnturK** [comment]
ROUND ID

**Comment by ExcessiveUseOfCobblestone** [comment]
NOTE IT IS ONE OF THOSE, NOT BOTH.
