### ISSUE TITLE
Mechs cant drill walls anymore.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#35925]
[Reproduction]: I was using APLU Firefighter with diamond drill. I wasted 10 minutes drilling a normal wall and nearly the same ammount of time doing that with a reinforced wall. And i didnt drill them, even when i probably should be able to. Maybe this is intended.

**Comment by Buggy123** [comment]
#34426

**Comment by ShizCalev** [comment]
Duplicate of #34426
