### ISSUE TITLE
First death report doesn't properly record any deaths and so shows "Nobody died this shift!" all the time

### ISSUE THREAD

**Issue by Xhuis** [tgstation/tgstation#35927]
I'm afraid I can't give any round IDs for this, because I just heard of the issue on waking up and wasn't around for the rounds in question. Due to its reliance on the Blackbox subsystem, I can't properly test or reproduce this locally, but it's reproducable on live.

Cedarbridge showed me the VV panel of the subsystem in a round with at least one death, and the `first_death` list hadn't saved at all, leading me to think that it's an issue with the way data is logged.

**Comment by LetterN** [comment]
_nobody has died on this shift!_
