### ISSUE TITLE
Sleeping carp does not confer immunity to attacks from turrets

### ISSUE THREAD

**Issue by theColdflame** [tgstation/tgstation#35939]
Issue reported from  Round ID: 84104 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

[Reproduction]: # Use Martial arts scroll as traitor, then have a turret shoot at you.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by ShizCalev** [comment]
Intended I'm pretty sure.

**Comment by Buggy123** [comment]
Wait what? Why?

If it's about the AI, 17 tc for a hard counter is not that great. You could spend a fraction of that on a EMP kit and do it just as easily.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/b49798c48368ed4bdc528e1c79214ce7f44d6767/code/modules/mob/living/carbon/human/human_defense.dm#L40-L55

I may be wrong but here it looks like it's simply checking the species and returning that prior to checking if the species has a martial art.

**Comment by imsxz** [comment]
projectiles are able to hit the user while theyre laying down, they probably got slipped or something. being hit while laying down with carp is intended.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm almost certain it's what I said, as a human with carp will have dna and a species datum which is checks first.

**Comment by ExcessiveUseOfCobblestone** [comment]
crazy question, has this been reproduced?

**Comment by ShizCalev** [comment]
Gonna close in a week without a repro
