### ISSUE TITLE
seek the harvest tracks drones and juggernauts

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#35935]
jugg 421
round 84093

**Comment by Buggy123** [comment]
wasn't it a morph?

**Comment by ExcessiveUseOfCobblestone** [comment]
are you *sure*

**Comment by AlexTheSysop42** [comment]
yeah it was a morph, but for me it just said "tracking morph" and that it couldn't be found

**Comment by ShizCalev** [comment]
@Robustin

**Comment by factoryman942** [comment]
oh then it should probably track morphs across transforms or something then

**Comment by Robustin** [comment]
The morph can instantly change forms so its "name" can change too. The round in question did have a morph posing as a juggernaut, when it died it took on its original name "morph". 

The list just pulls all living non-cultist players who are on the z_level. I could keep drones off the list but it doesn't seem like a real issue.
