### ISSUE TITLE
Alien brains can appear in tendrils despite doing nothing for anyone

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#35942]
Not a bug but - there's literally no point to getting these since techwebs. Should be removed or replaced with something that gives some tech points or something so there's an actual point to it.

**Comment by Kromgar** [comment]
To be fair the cursed heart is also fucking useless. But it really does feel shitty when you get the brain.

**Comment by MimicFaux** [comment]
Cursed hearts are fantastic self-healing items that come at the cost of having to manually pump them yourself until you get them swapped out. (click yourself with one sometime to try it out!)

But alien brains well and truly lack purpose now that we have tech webs.

**Comment by SpaceManiac** [comment]
They're worth 5000 cargo points each.

**Comment by TheDreamweaver** [comment]
Fixed. Check it out #36143

**Comment by ExcessiveUseOfCobblestone** [comment]
@MimicFaux unless someone put the wizard variant in the loot table, the cursed heart is pitiful.
