### ISSUE TITLE
MANY MACHINERY CAN BE MOVED WITH A WRENCH

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#35967]
Credits to @DaedalusGame (Bord) for finding this

![](https://i.imgur.com/m5O5VI8.png)

**Comment by DaedalusGame** [comment]
autolathes, cloning pods, telecomms machines and other such nonsense resist wrench damage

**Comment by nicbn** [comment]
Feature

**Comment by DaedalusGame** [comment]
this

**Comment by arsserpentarium** [comment]
What's a problem?Isn't it intended?
If not, let's make unwrenchable all types o machines, which isn't unwrenchable yet.

**Comment by RandomMarine** [comment]
Pretty much all of those are intended, especially from back in the day when they weren't constructable.

**Comment by Iamgoofball** [comment]
Uh, yeah. This is intentional. Not a bug and is extremely useful.

**Comment by DaedalusGame** [comment]
holopads are the only one i vehemently disagree with

**Comment by Profakos** [comment]
Intentional indeed, but needs a severe overhaul, like how it messes up powered area requirements, as reported in #26824.

**Comment by YakumoChen** [comment]
not a bug
