### ISSUE TITLE
Explosions travel through blobs.

### ISSUE THREAD

**Issue by halitosisman** [tgstation/tgstation#35961]
Issue reported from  Round ID: 84158 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
(It happened the round before this one)

I used maxcaps on a blob and the explosions affected areas on the other side of the blob.

**Comment by ExcessiveUseOfCobblestone** [comment]
the blob has bomb immunity because of (((robustin)))

**Comment by DaedalusGame** [comment]
If it has bomb immunity it should probably have explosion_block

**Comment by Kromgar** [comment]
STRONG BLOB tiles are immune to bombs.

**Comment by JohnFulpWillard** [comment]
i don't think this is an issue, gasses flow through blobs just fine so why wouldn't explosions
