### ISSUE TITLE
Golden Slime Extracts are broken again

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#35979]
Hey, I made this issue before, I thought it was just a one time glitch because they were working again, but now they aren't again. >Reproduction steps: 1. Get that golden slime extract, put any reagent into it. It makes a sound, has the fluff text, and disappears. With no monsters coming. I believe it also happens to orange slimes, so maybe it does it to other slime types as well? (Ech whats with this problem disappearing and recurring)
Server: Sybil
Round Id:84202

Please help I like xenobio, HELP ME CODERS

**Comment by YPOQ** [comment]
I fixed it here https://github.com/tgstation/tgstation/commit/87e9a2eb53a213e0f55b5b92426ba7ba11944a24 however sybil hasn't been updated yet and is currently on https://github.com/tgstation/tgstation/commit/06dd1bf8e8afef7051dd8931a03fe6896e3775c4.
