### ISSUE TITLE
Items on walls are not on walls

### ISSUE THREAD

**Issue by creeperparty568** [tgstation/tgstation#35983]
Items that are supposed to be on walls are not on them, but on the tile next to them.
![nowalls](https://user-images.githubusercontent.com/12233611/36648286-4cf69ae6-1a5f-11e8-9957-092dc18dda2e.PNG)
![nowalls2](https://user-images.githubusercontent.com/12233611/36648297-74dc970e-1a5f-11e8-82f7-d4c7dec1f0de.PNG)

[Reproduction]: # Simply caused by loading into the game. I've redownloaded the code and recompiled, checked on different maps, but the problem persists. It doesn't impair functionality, but it looks like shit.

**Comment by GunHog** [comment]
I guess someone broke pixel shifting.

**Comment by SpaceManiac** [comment]
Are you on 512.1405? It's known broken. Upgrade.
