### ISSUE TITLE
arm blades dont show up in emagged limb grower

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#35984]
84205

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 84205

Server revision compiled on: 2018-02-25

2b53dc

Revision: 87e9a2eb53a213e0f55b5b92426ba7ba11944a24

Server tools version: /tg/station 13 Server v3.2.1.11

Server tools API version: 3.2.0.2

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/af4d9a85c9a3eeef1e5e0637ef4ebd0312794ac7/code/modules/research/designs/limbgrower_designs.dm#L37
