### ISSUE TITLE
something wrong with roundend report

### ISSUE THREAD

**Issue by arsserpentarium** [tgstation/tgstation#35985]
[Round ID]: # 84205 bagil
You did not survive the events on Muppet Drydock L...
    Shift Duration: 
    Station Integrity: 86.4%
    Total Population: 97

    Evacuation Rate: 50 (51.5%)
    (on emergency shuttle): 43 (44.3%)
    Survival Rate: 55 (56.7%)
    Nobody died this shift!

**Comment by Jordie0608** [comment]
Already fixed in #35944 pending update.
