### ISSUE TITLE
Reagent Gun isn't a child of syringe guns

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/tgstation#35992]
/obj/item/gun/chem is a dumb path for this. It should really be a child of existing syringe guns.

**Comment by Buggy123** [comment]
agreed, makes much more sense even if technically it might be slightly simpler for it to not be a subtype.

**Comment by ExcessiveUseOfCobblestone** [comment]
What is a reagent gun

**Comment by Buggy123** [comment]
The new replicating syringe gun, named "reagent gun" https://github.com/tgstation/tgstation/blob/master/code/modules/projectiles/guns/chem_gun.dm

**Comment by ExcessiveUseOfCobblestone** [comment]
someone please rename that jesus
