### ISSUE TITLE
[Boxstation] N2O gas tank in atmospherics is too low

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#35991]
There's just over 5000KPa in it, which is only 500 KPa more than a single canister. Something about that number does not seem right.

**Comment by RandomMarine** [comment]
This isn't a boxstation specific thing.

https://github.com/tgstation/tgstation/blob/master/code/game/turfs/simulated/floor/reinf_floor.dm

```
/turf/open/floor/engine/n2o
	name = "n2o floor"
	initial_gas_mix = "n2o=6000;TEMP=293.15"

/turf/open/floor/engine/co2
	name = "co2 floor"
	initial_gas_mix = "co2=50000;TEMP=293.15"

/turf/open/floor/engine/plasma
	name = "plasma floor"
	initial_gas_mix = "plasma=70000;TEMP=293.15"

/turf/open/floor/engine/o2
	name = "o2 floor"
	initial_gas_mix = "o2=100000;TEMP=293.15"

/turf/open/floor/engine/n2
	name = "n2 floor"
	initial_gas_mix = "n2=100000;TEMP=293.15"

/turf/open/floor/engine/air
	name = "air floor"
	initial_gas_mix = "o2=2644;n2=10580;TEMP=293.15"
```

**Comment by RandomMarine** [comment]
Also:
>which is only 500 KPa more than a single canister
# PROTIP: NINE TURFS HOLD 1025% MORE VOLUME THAN A CANISTER

**Comment by Anonmare** [comment]
Well you tell the atmos tanks that because on max output, the tank gets drained empty in <4 minutes

**Comment by Jalleo** [comment]
By the way I think this maybe a dupe report

**Comment by 81Denton** [comment]
>initial_gas_mix = "n2o=6000;TEMP=293.15"

I might as well open a PR that sets all floors to 100.000 KPa instead of having 5 different values.

**Comment by vuonojenmustaturska** [comment]
per @duncathan , "we are not supposed to have the same amount of each gas. the obvious one is airmix which i hope i don't have to explain very much, but the gases other than o2/n2 are absolutely supposed to have less than those two gases. they're dangerous and not nearly as important as o2/n2."
