### ISSUE TITLE
Pen uplink does not appear to work.

### ISSUE THREAD

**Issue by h3killa** [tgstation/tgstation#35990]
Issue reported from  Round ID: 84230 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

[Round ID]: 84230

[Reproduction]: Set uplink style to pen. Input degree.
Specific value that failed: 29

**Comment by praisenarsie** [comment]
@AnturK

**Comment by SailorDave** [comment]
I'm not able to reproduce this. Is this still an issue?
