### ISSUE TITLE
When in crit and conscious you cannot do anything besides crawling

### ISSUE THREAD

**Issue by PsyCommando** [tgstation/tgstation#36008]
[Reproduction]: 
So if you fall in crit but not are still conscious and you can still crawl around for miles, but you cannot use anything or speak or use emotes. Its kinda inconsistent. Sounds to me that if you can still crawl that much, you should be able to reach up your  pockets for your medipen or use your radio at least?

For example, in lavaland I stepped in lava, put myself out, but it was enough to send me in crit. I was able to crawl back from one end of the map to the mining base, literally, but I couldn't use a medipen, the ferry console, the shower, the radio, and etc.. 
So I basically just crawled in circle for a good 5-10 minutes, maybe more, until I began choking to death and died. It happened to me several times over, mainly after burning and falling in crit.

I'd assume that's not intended behavior, because it seems the crit state and the unconscious state got somehow half-merged together. I didn't really look into the code though.

**Comment by XDTM** [comment]
It's called softcrit, and intended, although you should probably be suffocating to death far earlier than you described

**Comment by PKPenguin321** [comment]
Not a bug. Take code feedback to the forms

**Comment by PsyCommando** [comment]
@XDTM That's partly why I mentioned it here. There's something odd about it. But I feel its kind of an edge case probably?

**Comment by PKPenguin321** [comment]
No, because it was designed this way intentionally and it would have huge balance implications to allow people in soft crit to heal themselves out of it or whatever you're proposing, not a fix

**Comment by Cyberboss** [comment]
@DaedalusGame the feedback label is for database feedback prs. This is intentional

**Comment by PsyCommando** [comment]
@PKPenguin321 What I was implying there was that being in softcrit for 5-10 minutes before dying from choking might have been an edge case? Why does stepping in lava and burning a bit should softcrit you if you're still obviously healthy enough to crawl around for so long?

Besides, I'm not really sure what you're talking about? When you're in crit/about to be in crit you're usually stunned from being beaten/shot to death anyways. Its doesn't really matters softcrit or crit, you couldn't do shit anyways. You make it sound like its what holds the whole game together?
