### ISSUE TITLE
Circuit Bots Are Immune to Hierophant & Colossus Attacks

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#36010]
Issue reported from  Round ID: 84269 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

Saw a scientist kill the hierophant with nothing but a bot that threw hatchets. None of the hierophant's attacks did any damage to the bot. Same with the colossus.

**Comment by MMMiracles** [comment]
I brought up the issue #32904 here with them being immune to generic attacks, got marked as not a bug. Probably an issue.

**Comment by Potato-Masher** [comment]
Gee, I sure do love when items disguised as mobs spam axes and murder everything, up until the point they are picked up.

**Comment by ExcessiveUseOfCobblestone** [comment]
After that "I can pick up living mobs" pr if it's not closed you could probably easily switch them to mobs.

Semi-related is #35795, Although that's pertaining to the megafauna itself rather than their projectiles.

**Comment by AlexTheSysop42** [comment]
pretty sure this was fixed @ShizCalev

**Comment by AlexTheSysop42** [comment]
same with #35795

**Comment by ChangelingRain** [comment]
#35795 was fixed, but this was not.

**Comment by AlexTheSysop42** [comment]
oh right

**Comment by SpaceManiac** [comment]
Circuits have been removed.
