### ISSUE TITLE
Gas miners do not spread gas moles

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#36014]
Server: Bagil
Round ID: 84271
Revision: 2b53dc
Testmerges: Nothing
Previous issue: #34000

Looks like #35828 doesn't fix the issue all the time. Gas sometimes doesn't spread from the miner tile.

Gas miner tile: 
(86,164,5): 291.574 K (18.4237 C), 6046.81 kPa 
Plasma: 6239.03 mol

Adjacent tiles:
(85,165,5): 2.7 K (-270.45 C), 0 kPa

**Comment by praisenarsie** [comment]
@duncathan

**Comment by duncathan** [comment]
oh lmao
