### ISSUE TITLE
Airlocks only cycle link after being opened/closed once

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#36026]
Revision: https://github.com/tgstation/tgstation/commit/a94a9091464d9fd432720bcb9e57d2a01f88cece

Airlocks only start cycle linking once they've been opened and closed once.

**Comment by Potato-Masher** [comment]
>"Have you tried turning it on and off again?"

**Comment by ShizCalev** [comment]
Unable to repo.

**Comment by ShizCalev** [comment]
Map?

Can you check the airlock's vars and confirm it's not linked to another?

If the helpers were failing, there should be a -ton- of spam in chat.

**Comment by 81Denton** [comment]
I‘ll attempt to repo it this afternoon.

**Comment by 81Denton** [comment]
@ShizCalev Looks like I was wrong; airlocks just stop cyclelinking when a shuttle is docked at them. Is that intentional?

**Comment by ShizCalev** [comment]
I'll take a look when I get power back (likey thursday)

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/6622c3794da3175b58608585cfd1e35f7d3985f4/code/game/machinery/doors/airlock.dm#L334-L339

Intentional.
