### ISSUE TITLE
Caks can nuzzle grilles to death.

### ISSUE THREAD

**Issue by Kerbin-Fiber** [tgstation/tgstation#36033]
Basically, it takes around 13-15 nuzzles to completely destroy a grille as a cak. The picture shows it's just about 13-15.

Server: Bagil (Provided in the picture below)
Round ID: 84300 (Provided in the picture below)

Reproduction: Get turned into a Cak, start nuzzling (clicking) on some grilles and you should hear the grille hit sound, continue about 13-15 times and the grille is now gone and broken, rods are still dropped.

![](https://i.imgur.com/lFppOzx.png)

**Comment by Slignerd** [comment]
Extensive nuzzling

**Comment by DaxDupont** [comment]
...nuzzles do damage?????

**Comment by LetterN** [comment]
you can use the number 4 (hotkey) and make yourself harm intent right?

**Comment by Slignerd** [comment]
Hardcore nuzzling

**Comment by Potato-Masher** [comment]
A weapon to surpass cake gear.

**Comment by AlexTheSysop42** [comment]
caks are spaceproof?

**Comment by Ordonis** [comment]
Feature

**Comment by XDTM** [comment]
simple animal's harm_intent_damage defaults to 3, close if it's intended, or put a 0 on the pet level

**Comment by babydoll** [comment]
`harm_intent_damage` is the damage players inflict on simple_animals when they attack them with an empty hand on harm intent
