### ISSUE TITLE
(Not a Bug) The Byond Medal System Needs Better Integration

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#36032]
Medals have been in for a while now yet no in game “toot your own horn” mechanic. The only way you’d even know they’d exist is by hearing it second hand or looking at the recent prs affecting it if you’re a newer member.

EoR should report all medals earned throughout the round or at the very least something that prompts the user to visit the page. It’s a neat feature that we DO utilize, just very poorly.

http://www.byond.com/games/TgstationHub/TgstationStatsHub#tab=scores

**Comment by actioninja** [comment]
We don't use byond medal system anymore
