### ISSUE TITLE
Being cuffed does not deny greentext

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#36053]
You can still succeed in the Alive and Free objective even when cuffed, straightjacketed, etc, on a pod or in a non-sec area on the shuttle (not sure about in the sec area)

**Comment by SpaceManiac** [comment]
Intended AFAIK, the "not in custody" check is based entirely on being in the brig area of the shuttle.

**Comment by Jordie0608** [comment]
Yes intended.
