### ISSUE TITLE
Singularity engine is hot garbage

### ISSUE THREAD

**Issue by RandomMarine** [tgstation/tgstation#36067]
![singulopower](https://user-images.githubusercontent.com/6583225/36857976-cc7433d6-1d71-11e8-8a53-8fd2f91af2dc.png)
These are with 2500kpa 20c plasma tanks.
In their basic roundstart positions, the collectors never put out more than 10kW.
Seriously what the fuck.

**Comment by RandomMarine** [comment]
Oh and power 0 particle accelerator has such a puny fucking range that the goose reverted to stage 1 outside of it.

**Comment by praisenarsie** [comment]
i think @ninjanomnom could've nerfed the singulo to byond oblivion when he did the radioactivity refactor

**Comment by DaedalusGame** [comment]
just wanna note here (again) that filling plasma tanks all the way does nothing to improve the power output

**Comment by ExcessiveUseOfCobblestone** [comment]
> power spikes literally everytime I chill max them

wtf

**Comment by ninjanomnom** [comment]
The last time I touched on radiation the singulo was making somewhere around 200-400kw, something else likely changed somewhere related to it but I'm not sure what.

**Comment by Dorsisdwarf** [comment]
not related but that is a freakishly big singulo pen

**Comment by 81Denton** [comment]
![q2fwggwrwrg](https://user-images.githubusercontent.com/32391752/38144073-a3ab912c-3443-11e8-8e24-2aff308ce85d.JPG)

oof
I'll see if increasing singulo radiation strength will bring the amount of power generated to proper levels (without killing all of engineering)
