### ISSUE TITLE
Arena shuttle can't be entered properly

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#36069]
Round ID: 84372 (Sybil)
Revision: b127d2

When the arena shuttle docks, players aren't able to enter it properly (they just run into a wall after the first open tile).

>OOC: Nabski: the people that got on it
>OOC: Nabski: I moved by hand
>OOC: Nabski: and that was disgusting and a hassle

**Comment by Buggy123** [comment]
it had a period where it was just kinda fucked up and teleported people around centcom but now its just completely broken.

**Comment by Kromgar** [comment]
Well it would teleport people around centcomm once they get out of the arena

**Comment by ninjanomnom** [comment]
This was broke by #33810

I'll have a fix up in a moment
