### ISSUE TITLE
Brain Surgery gives you irreversible damage (and no, it wasn't from a lobotomy)

### ISSUE THREAD

**Issue by UncleBourbon** [tgstation/tgstation#36076]
[Round ID]: # 84387

[Reproduction]: # Have tinfoil hat on. Melt it off with acid. Get surgery to remove phobia. Person fucks up surgery giving me brain damage and making me unable to talk. Get surgery again to fix it, nothing happens. Take both mannitol and mutadone pills, still nothing fixes it. Ask admins about it, they say that i have 0 brain damage and they aheal me to see if that fixes it either, nothing.

**Comment by Repukan** [comment]
Player issue

**Comment by RandomMarine** [comment]
Traumas from failed surgery are at a resistance level higher than what surgery can fix.

Use sterilizine next time.

**Comment by XDTM** [comment]
A lobotomy should fix it, though.
