### ISSUE TITLE
Visual bug with new Trait system and Character Setup menu.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#36085]
Player character has prosthetic limb(s) even without proper perk.  
![bug](https://user-images.githubusercontent.com/34580767/36897180-9b8c162a-1e26-11e8-8930-741447c37b4d.png)

**Comment by Xhuis** [comment]
Known issue, I spent a good amount of time trying to fix this but couldn't figure out how.

**Comment by Bawhoppen** [comment]
We have that issue with normal character previews anyways

**Comment by Bawhoppen** [comment]
Oh nevermind I misunderstood the issue
