### ISSUE TITLE
Transit tube stations only accessible from 1 side.

### ISSUE THREAD

**Issue by Michael-Ashfield** [tgstation/tgstation#36097]
[Round ID]: # 84419

Issue:
Transit tube stations can only be accessed from 1 side, this affects both terminal and through stations. 
This issue makes it difficult to work with the transit tube system in tight areas (Such as inside the station). There is no way to make a transit tube station work on the other side, this makes having to design rapid transit systems around the opening side of transit stations rather than designing them well.
I'm not sure if it is a feature, because it makes no sense if it is, it provides no benefit game-play wise.

One note, there seems to be no transit bend tube with a crossing. The bend tube is a commonly used part in transit tube systems and it seems like there should be a crossing version like with the straight and diagonal tubes which have crossings, this could make for some interesting in station transit systems without blocking corridors.

**Comment by AlexTheSysop42** [comment]
The onesided bit is intentional, you can just flip it
