### ISSUE TITLE
there is no easy way to get embedded objects out of a corpse

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#36109]
this isnt really a bug but like you have to dismember the corpse and then butcher the limb that you cut off and its a little excessive for pulling a spear out of a dead guy lol

**Comment by XDTM** [comment]
There is surgery

**Comment by evsey9** [comment]
WHY DO YOU HAVE TO FUCKING DO SURGERY TO GET A HUGE FUCKING SPEAR OUT OF A CORPSE

**Comment by WJohn** [comment]
In fact, why do you have to do surgery to pull things out of other people at all? Shouldn't surgery be the safe, no-damage version, while doing it with your bare hands is messy and dangerous?

**Comment by nemvar** [comment]
Surgery is now wanted and only two steps now. This is fine.
