### ISSUE TITLE
White ship walls have no floors under them

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#36107]
dont have a round id but it happened yesterday

**Comment by Jalleo** [comment]
Which one or is it all of them?

**Comment by Dennok** [comment]
Pirate ship on syndicate ambush walls have no floors under them too.
And maby cargo ship on syndicate ambush too

**Comment by Kromgar** [comment]
This is a dupe and has been going on for 2 months now

**Comment by Kromgar** [comment]
https://github.com/tgstation/tgstation/issues/33984
