### ISSUE TITLE
light glow is above camera static

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#36100]
1. be ai
2. go over maint
3. see giant yellow blobs everywhere

**Comment by ChangelingRain** [comment]
@deathride58
downside: anything using this will render above things that aren't using it, even if it shouldn't render above, such as megafauna/alien queens/_other shit_

**Comment by factoryman942** [comment]
it is as the prophecy foretold

**Comment by deathride58** [comment]
Should be ez to fix by making the ai static render above the above lighting layer

**Comment by ChangelingRain** [comment]
for reference that's a good solution and needs to happen anyway

**Comment by factoryman942** [comment]
call it above-above-lighting
