### ISSUE TITLE
Flight suits can move through shutters

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#36112]
Revision: e582cd08a393ac436f4584875dd4b73bedfe5004

Flight suits can dash through closed shutters (door/poddoor/preopen), as long as there is a closed airlock on top of them.

I tested this with the Pubbystation bridge entrance shutters.

**Comment by evsey9** [comment]
Took enough time for someone to report it

**Comment by Garen7** [comment]
arent flight suits removed?

**Comment by 81Denton** [comment]
RIP indeed
