### ISSUE TITLE
Traits do not switch with characters 

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#36119]
Round ID: 84450

Server revision compiled on: 2018-03-03

16db14

I set up traits before round start and then switched chars. Then I joined the game on the traitless char but got the traits from the other char.

**Comment by DaxDupont** [comment]
@Xhuis

**Comment by Xhuis** [comment]
I don't really follow what you mean.

**Comment by DaxDupont** [comment]
Set up character slot 3 with traits.
Switch to slot 2 character which has no traits and join game.
Congrats you have slot 3 traits on slot 2 character for some reason.

**Comment by SpaceManiac** [comment]
Whoever is fixing this should also fix this runtime
```
[14:16:52] Runtime in traits.dm, line 30: Cannot read null.prefs
proc name: AssignTraits (/datum/controller/subsystem/processing/traits/proc/AssignTraits)
src: Traits (/datum/controller/subsystem/processing/traits)
call stack:
Traits (/datum/controller/subsystem/processing/traits): AssignTraits(Joe Bine (/mob/living/carbon/human), null)
/datum/preferences (/datum/preferences): copy to(Joe Bine (/mob/living/carbon/human), 1)
SpaceManiac (/mob/dead/new_player): create character(0)
Ticker (/datum/controller/subsystem/ticker): create characters()
Ticker (/datum/controller/subsystem/ticker): setup()
Ticker (/datum/controller/subsystem/ticker): fire()
Ticker (/datum/controller/subsystem/ticker): fire()
Ticker (/datum/controller/subsystem/ticker): fire(0)
Ticker (/datum/controller/subsystem/ticker): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
Master (/datum/controller/master): Initialize(10, 0)
```

**Comment by Xhuis** [comment]
Upon analysis, seems like traits function as game preferences rather than character ones. This isn't a bug, just a quirk.

**Comment by SpaceManiac** [comment]
I'm not certain. I personally experienced and received multiple reports of people changing to another character, editing their traits, and getting the previous character's traits when the round started.

**Comment by DaxDupont** [comment]
@Xhuis that's a bug not a quirk.
Especially when you switch it says no traits.
ALSO traits need to be tied to characters as they inherently related to characters and not game preferences.  
It would be like hazel eyes being a game preferences.

**Comment by ExcessiveUseOfCobblestone** [comment]
There’s an issue one way or the other if a game pref is veiled as a character pref come on...

**Comment by CRTXBacon** [comment]
As someone who's been using traits as part of roleplay with my separate characters I find this annoying at best. I'd like to be able to set up traits for one character, and be able to have those traits affect that character and no others.

**Comment by Xhuis** [comment]
This is absolutely something I want to change, don't worry. I'm just not certain how. As I mess with traits more I'll be looking at save file code to see if I can do this.

**Comment by DaxDupont** [comment]
They are saved per character right? Did you mess up the saving process?

**Comment by Xhuis** [comment]
I'm not actually sure. I wrote the saving code in the same way that other character slot things save and it doesn't seem to have done that. It currently appears to be client-wide instead of slot-wide.

**Comment by Poojawa** [comment]
Problem with this is your code isn't byond paranoid enough

```
/datum/controller/subsystem/processing/traits/proc/AssignTraits(mob/living/user, client/cli, spawn_effects)
	GenerateTraits(cli)
	if(user && cli && cli.prefs.character_traits)
		for(var/V in cli.prefs.character_traits)
			user.add_trait_datum(V, spawn_effects)

 /datum/controller/subsystem/processing/traits/proc/GenerateTraits(client/user)
	if(user && user.prefs && user.prefs.character_traits)
		if(user.prefs.character_traits.len)
			return
		user.prefs.character_traits = user.prefs.all_traits
```

or something to that effect.
