### ISSUE TITLE
Gas turbine/Incinerator vent doesn't work. Fusion is impossible in BoxStation via atmos due to this.

### ISSUE THREAD

**Issue by necroguemancer** [tgstation/tgstation#36115]
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

Not found on /tg/, but I run a fork of /tg/ and I discovered it there on boxstation.

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.) N/A

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

The vent in the incinerator/gas turbine does not work at all. I've tried using it and it won't work. I've tried resetting it using an RPD, but it doesn't want to work at all. I wanted to use it as a makeshift toxins lab as it could pipe gases from atmos directly in, but I wasn't able to successfully use it to siphon gases into canisters. I've messed around with air alarms, etc, but nothing works. You guys might want to check if the incinerator's vent actually works.

I've also found that when I try to make tritium, it ends up at the blast door after the gas turbine (tritium gas image shows up.) I tried placing a vent there before doing fusion as well as enclose it so that it can't go into the atmosphere, but it also didn't work. The pipe right after the vent was empty as well as any other pipe. Even when I hooked it up to a canister, that canister remained empty.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by Jalleo** [comment]
I will check it later might be a downstream issue
