### ISSUE TITLE
Phobias can cause ghosts to scream

### ISSUE THREAD

**Issue by Singularbyte** [tgstation/tgstation#36118]
Round ID: 84447

Phobias can still affect ghosts that are inhabiting their own corpses, which includes giving phobia messages and causing screaming.
In my case, it was with a robot phobia, but I expect it applies to others.

To reproduce: Get a robot phobia, die, stay in your corpse (i.e. don't become a free-moving ghost), then have AIs speak, or robots move past, etc. One of the random phobia effects you'll get is a scream which is spoken into dead chat.

**Comment by Buggy123** [comment]
In Soviet Russia, you scare ghost!

**Comment by Xhuis** [comment]
Even in death there is no escape from the robot hell.

**Comment by Potato-Masher** [comment]
>You cannot scream while unconscious.

HNNNNNGGGGGGG
