### ISSUE TITLE
Central Primary Hallway vent pump is wanted for releasing plasma

### ISSUE THREAD

**Issue by Sunoplyrus** [tgstation/tgstation#36122]
84454 Sybil 511
![dreamseeker_2018-03-03_17-48-11](https://user-images.githubusercontent.com/31968974/36939155-353aad24-1f0b-11e8-9c67-a36249b0ea16.png)
I assume it happened when someone shot a photo of a wizard with shielded battlemage armor

**Comment by Jalleo** [comment]
It is almost a feature.

**Comment by kevinz000** [comment]
not a bug, security console doesn't check if it's a real person before making the poster or allowing the upload.
@Cyberboss
