### ISSUE TITLE
traits carry over to ctf

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#36127]
you can have a prosthetic in ctf

**Comment by Xhuis** [comment]
I don't really see an issue with this.

**Comment by KorPhaeron** [comment]
You dont see an issue with taking pacifist and being unable to play a completley unrelated admin game?

**Comment by Xhuis** [comment]
Pacifist cleanses automatically in any scenario where it's a problem, like in highlander. Unless CTF doesn't give any kind of mind roles, then it should remove itself in CTF, too.

**Comment by DaxDupont** [comment]
Related to https://github.com/tgstation/tgstation/issues/36119

**Comment by praisenarsie** [comment]
if it carries over to ctf then i'm gonna take a wild guess that it carries over to ash walkers and various lava ruins which is a problem.

**Comment by Xhuis** [comment]
Like I said, it does not carry over to mobs with a special mind role. The changes I'm making to traitcode will prevent it either way, however!
