### ISSUE TITLE
Tesla coil board breaks when screwdriver'd

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#36131]
Revision: 05bc9e9983342a8c555d81d9284553815fd253ba
Related: #35965
@Poojawa 

When you attempt to screwdriver a tesla coil board to research mode, the following happens:
- Message: You change the circuitboard setting to "".
- The board is now broken, has no name and can't even be selected by right clicking. Obviously can't be used to complete construction either.

**Comment by Poojawa** [comment]
reeee, what. 

it uses the same code and path as the gas freezer/heaters, and worked in my testing. Lemmie see what's up

**Comment by Poojawa** [comment]
Okay so, fix that, but now it just flat out clones the damn board instead of finishing the building.
