### ISSUE TITLE
Cuba Libre makes Rum and Coke

### ISSUE THREAD

**Issue by animehater69** [tgstation/tgstation#36138]
I think the recipes overlap, but it sucks since you can't help the revs in rev mode

**Comment by Cruix** [comment]
You need to add lime juice to make it a Cuba Libre.

https://github.com/tgstation/tgstation/pull/36059/files changed the recipe

**Comment by Potato-Masher** [comment]
@animehater69 

As Cruix said, #36059 adjusted the recipes to reflect what they actually are.

**Comment by ExcessiveUseOfCobblestone** [comment]
Is it not edited on the wiki

**Comment by ShizCalev** [comment]
Anyone can edit the wiki. I haven't had a chance to disable it myself because my city got raped by the noreaster.
