### ISSUE TITLE
[Metastation] Cleanbot infinitely producing lube foam even though it;s not emagged and turned off

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#36134]
For some reason it's not displaying round ID normally so it's [Round ID]: 84468

EDIT: Also, it's ONLY the cleanbot on the AI sat. Every other one at roundstart worked fine

The following pull requests are currently test merged: 
#36029: '[READY]GOAP: 2018' by Iamgoofball at commit c821b5 
#33166: '[READY]Refactors storage handling from /obj/item/storage to a component.' by kevinz000 at commit c25eff

**Comment by kevinz000** [comment]
probably not my pr. probably not.

**Comment by Iamgoofball** [comment]
this iss fixed, need a testmerge update

**Comment by ShizCalev** [comment]
Related to testmerge #36029
