### ISSUE TITLE
AI act broke and so are cleanbot interfaces

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#36135]
The round ID is 84468
The following pull requests are currently test merged: 
#36029: '[READY]GOAP: 2018' by Iamgoofball at commit c821b5 
#33166: '[READY]Refactors storage handling from /obj/item/storage to a component.' by kevinz000 at commit c25eff 

Left clicking on an airlock does not bring up the AI control interface but hotkeys still work

In addition:
Clicking on a cleanbot will say that it's behavioural control interface is locked to you, meaning it's impossible to set a cleanbot to autopatrol
It's no longer possible to activate a conveyor switch as an AI
It is no longer possible to interact with a disposal bin
You can no longer select an AI/Cyborg from the respective upload consoles
You can no longer interact with firelocks
You can no longer trigger an AI's foam dispensers

**Comment by kevinz000** [comment]
fxied

**Comment by Iamgoofball** [comment]
cleanbots also cannot patrol at the moment until I finish reverse engineering/rewriting the patrol system entirely

**Comment by ShizCalev** [comment]
Related to testmerges.
