### ISSUE TITLE
Abductor Toxin prevents speech from being logged in player panel

### ISSUE THREAD

**Issue by TribeOfBeavers** [tgstation/tgstation#36145]
[Round ID]: # 84477

If someone is turned into an abductor by mutation toxin their abductor speech is not logged in the player panel. When turned back their speech is recorded again.

**Comment by AlexTheSysop42** [comment]
Does this happen for other hive minds too? (ling, slimelink)

**Comment by XDTM** [comment]
slimelink is logged
