### ISSUE TITLE
Lobby screen trait selection accepts non-standard inputs 

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#36148]
Title, 
Trait 'names' that aren't listed can still be toggled despite them not existing.

Example: https://i.imgur.com/DcRGDWo.png

Steps to reproduce: Join lobby, href abuse, create savvy traits/backstories that nobody will see.

I've yet to find anything outside of cosmetic effects that can performed by abusing this, but given how you can dump text in your client preferences this should at least be looked at by somebody who knows more than I do.

Round ID: 84484
Revision: 52c344575c6c711a642e032a6f917fef44dd8c5f

**Comment by praisenarsie** [comment]
traits were a mistake, who merged them

**Comment by AlexTheSysop42** [comment]
can this affect trait balance?

**Comment by Xhuis** [comment]
This *might* be able to change trait balance, but it's also a security vuln and I'll be patching it around.

**Comment by Xhuis** [comment]
Oh, and thank you for reporting this.

**Comment by GravitronBlue** [comment]
I made several weak attempts at breaking trait balance trying to trick Byond into accepting a list or entry as more than one trait. None were successful, but I share the same concern as Xhuis where enough time and effort spent poking Byond could end up really breaking things.

**Comment by GravitronBlue** [comment]
I haven't looked at how client preferences are loaded, but it may be worth investigating whether this can be abused similar to #36286
