### ISSUE TITLE
Can't build items that I researched in R&D

### ISSUE THREAD

**Issue by cstar117** [tgstation/tgstation#36141]
Issue reported from  Round ID: 84473 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512
When I do R&D I am unable to make certain items. For example I research advanced sanitation, but I am unable to make the advanced mop even when I have the material. To reproduce the result try to make an advanced mop. If you find a solution please tell me.

**Comment by Potato-Masher** [comment]
If you are trying to print the advanced sanitation stuff at the R&D protolathe, that will not work. You would have to print said things at the service protolathe found usually near botany/kitchen.

**Comment by Jalleo** [comment]
Certain items are for certian departmental protolathes only now. This is intended and not a bug. This issue can be closed.
