### ISSUE TITLE
Circuit scanner no longer functional for most items.

### ISSUE THREAD

**Issue by fludd12** [tgstation/tgstation#36159]
[Round ID]: #84502

[Reproduction]: Include a scanner circuit in an assembly, and attempt to activate it by clicking the assembly with any item capapable of dealing damage.

[For Admins]: Unsure, but may have been caused by the change that allows circuits to be damaged.

**Comment by SailorDave** [comment]
Intent affects whether or not the scanner takes a reference to the object you hit it with. Help intent will allow you to scan objects, though weapons will still damage the assembly slightly in the process.

**Comment by fludd12** [comment]
My last test was with (regular) slime extracts, which were not scanned and played the attack animation.

**Comment by SailorDave** [comment]
Having just tested it specifically with a slime extract and several other weapons, I can confirm that you have to be on help intent to scan. No other intent will work.

**Comment by fludd12** [comment]
Fair enough! Wasn't working for me last I checked, but I'll take your word for it.
