### ISSUE TITLE
shuttle walls STILL break to space

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#36164]
its been fucking months

**Comment by 81Denton** [comment]
![1481297959530](https://user-images.githubusercontent.com/32391752/36960363-05521be6-2047-11e8-8dc5-aa5d7a8d6f39.jpg)

**Comment by vuonojenmustaturska** [comment]
well no-one has touched them so... yeah?

**Comment by Buggy123** [comment]
_months_

**Comment by Buggy123** [comment]
for _months_ you've been able to space a quarter of the people on a shuttle with a welder and that's not okay.

**Comment by ShizCalev** [comment]
Duplicate of #35241
Duplicate of #33984

Please stop reopening the same issue.
