### ISSUE TITLE
Spamming harm intent allows you to circumvent pacifism when attacking simple creatures.

### ISSUE THREAD

**Issue by TheDreamweaver** [tgstation/tgstation#36168]
[Reproduction]:

-Gain Pacifism trait

-Spam the harm intent toggle button (Key 4)

-While spamming, attack a simple mob and watch as you are able to damage it.

**Comment by XDTM** [comment]
Must have missed a check somewhere

**Comment by TheDreamweaver** [comment]
I noticed it only works when you are attacking with your barehand
