### ISSUE TITLE
Players unable to ghost out of sentient disease antag

### ISSUE THREAD

**Issue by Ispiria** [tgstation/tgstation#36178]
Okay round's over, honest mistake!

[Round ID]: # 84532

[Reproduction]: Triggered the new Sentient Disease antag event to get a better look at it, the player who received it played for a while and it all went fine, disease was eventually purged except for one last host who was a braindead and isolated atmos tech. The player controlling the disease ahelped after five-ten minutes to report that he was unable to ghost out of his disease role and I wound up having to VV delete him so he could exit his braindead host. Not sure if it's really a bug or just an oversight, but it seems like some kind of non-admin contingency needs to be available for a player virus who ends up stuck in a non-productive host.

**Comment by ExcessiveUseOfCobblestone** [comment]
lol

**Comment by Cruix** [comment]
All these years and no one every complained that blobs cannot ghost.

**Comment by ma44** [comment]
For convenience, it would probably also be great for an easy way for ghosts to regain control of blobs/sentient diseases (dragging ghost onto blob core?)

**Comment by Cruix** [comment]
That probably does not work for cameras either.
