### ISSUE TITLE
Nukeops lacking faction when adminspawned.

### ISSUE THREAD

**Issue by cedarbridge** [tgstation/tgstation#36199]
[Round ID]: #84506

[Testmerges]:
#36029: '[READY]GOAP 2018: Cleanbots and Navmeshes' by Iamgoofball at commit 8fd20f
#33166: '[READY]Refactors storage handling from /obj/item/storage to a component.' by kevinz000 at commit 5ee76d

[Reproduction]: Spawned a nuke team from the admin Create Antagonist prompt series.  Operatives spawned without faction protection from the shuttle turrets.

**Comment by ShizCalev** [comment]
@AnturK

**Comment by AnturK** [comment]
Caused by #33166 but i'll add explicit check in there.
