### ISSUE TITLE
There's a couple messed up pixels in the new parallax

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#36197]
Can't really give an image but if you fly around as a ghost in space you'll probably notice them
(Oriented to the Northeast of the station as its fixed point)

Also does anybody else ever get those weird lone black pixels that ignore parallax?

**Comment by MMMiracles** [comment]
Are you playing in stretch to fit? I only noticed this with stretch to fit and switching fixed it.

**Comment by Bawhoppen** [comment]
I do play on stretch-to-fit. I had the same thought that the old one had it too, since it's not the far background and is closer to the foreground.

**Comment by timothymtorres** [comment]
Not seen related issues involving this for a while.  Marking this as cleanup.
