### ISSUE TITLE
Wormhole projector not making wormholes.

### ISSUE THREAD

**Issue by Jcenderion** [tgstation/tgstation#36196]
Issue reported from  Round ID: 84542 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 511

I built the wormhole projector and when fired at a wall it did absolutely nothing.

**Comment by AlexTheSysop42** [comment]
Where was this?

**Comment by Jcenderion** [comment]
The station. Everywhere.

**Comment by Tlaltecuhtli** [comment]
reproduced on bagil yes its bug
