### ISSUE TITLE
TRAIT_NOCLONE name is misleading

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#36203]
NOCLONE is a misleading name; it doesn't prevent cloning by high-tier scanners or replica pods. Maybe something like HUSKED would be more appropriate?

From what I see, only changeling DNA drain and /obj/machinery/anomalous_crystal/dark_reprise apply the trait.

**Comment by XDTM** [comment]
Will fix

**Comment by SpaceManiac** [comment]
Fixed by #41819
