### ISSUE TITLE
Stock exchange computer doesn't work

### ISSUE THREAD

**Issue by septu1** [tgstation/tgstation#36208]
Clicking stock exchange computer doesn't do anything. Tried multiple computers, asked a random player to use computer which didn't work for him either. 

Was playing on Bagil server.
Reproduction: Click stock exchange computer. A window should pop up, giving you details regarding available stocks etc.

**Comment by Jalleo** [comment]
Please provide a round ID and what test merges were underway if any were.

**Comment by Jalleo** [comment]
@kevinz000 to do with your storage test merge?

**Comment by ShizCalev** [comment]
Likely caused by testmerge #33166
