### ISSUE TITLE
Abandoned crates instantly explode when clicked on

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#36206]
[Round ID]: # 84562
testmerged:
#33166 
#36029 
#36175 

empty hand used, clicked on an abandoned crate, blew up instantly. multitool tells me:

DECA-CODE LOCK REPORT:

* Anti-Tamper Bomb will activate after 10 failed access attempts.

but using an empty hand nevertheless immediately blows it up.

**Comment by 81Denton** [comment]
Can't repo this on a local branch. I suspect it's either #33166 or an explosive holoparasite.

**Comment by 81Denton** [comment]
Doesn't seem to be a holoparasite, all I can see in the logs is 
[13:55:21]GAME: Newfren/(Bill Nefren) has detonated abandoned crate.
[14:07:42]GAME: Newfren/(Bill Nefren) has detonated abandoned crate.
etc

**Comment by Mark9013100** [comment]
Were you on a non-help intent?
