### ISSUE TITLE
Cloner autoprocess clones suicides

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#36205]
When a cloner runs on autoprocess, it will clone scanned players that have suicided.
If I'm not reading this wrong, clone pods should always eject suicides:

`if((mob_occupant.stat == DEAD) || (mob_occupant.suiciding) || mob_occupant.hellbound)  //Autoeject corpses and suiciding dudes.`

> Jayce Metzer is getting too high on life! It looks like he's trying to commit suicide.
Jayce Metzer seizes up and falls limp, his eyes dead and lifeless...
Jayce Metzer has died at Construction Area.
Jayce Metzer's Memories:
Time of death: 12:54:40
Your body is beginning to regenerate in a cloning pod. You will become conscious when it is complete.

**Comment by ExcessiveUseOfCobblestone** [comment]
That suiciding check sounds silly considering a body in the cloning pod will literally never be a suicide (you can't suicide while restrained and it's a new mob) unless the suicide var is somehow transferred.

**Comment by ExcessiveUseOfCobblestone** [comment]
It's missing an update between the scanning of the mob and the actual cloning process to check if they've suicided between then.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/ea8be34eacc66f3bf231327cfc77b15ec752c30e/code/modules/mob/dead/observer/observer.dm#L255

add `ghost.suiciding = suiciding` then when you pull the ghost from the cloning pod have the new cloning mob transfer the ghost's `suiciding` ;)

**Comment by DaxDupont** [comment]
https://github.com/tgstation/tgstation/pull/36212 might fix this

**Comment by XDTM** [comment]
not yet but soon

**Comment by XDTM** [comment]
nevermind i give up

**Comment by SgtxRootbeer** [comment]
We should keep pre-scanning an option for suicides.

**Comment by Iamgoofball** [comment]
@SgtxRootbeer 
No. Suicide is a "I am done playing the video game" button.

**Comment by ExcessiveUseOfCobblestone** [comment]
For some reason what I said already happens, it's just that someone has explicitly removed the suiciding check on clone. See 36212

**Comment by Slignerd** [comment]
Just suicide again tbh

**Comment by AlexTheSysop42** [comment]
@Iamgoofball No, ghost is the "I am done playing the video game" button.

**Comment by Kromgar** [comment]
@ShizCalev Why is this a bug. Ghost is the "I am done playing the video game button"

**Comment by 81Denton** [comment]
People are honestly arguing about this being a bug? Suiciding already excludes you from:
- replica pod cloning
- getting clone scanned
- getting defibbed
- strange reagent
- revival surgery

**Comment by AlexTheSysop42** [comment]
> borging

Actually I'm pretty sure that still works, as does cloning their brain

**Comment by 81Denton** [comment]
Just checked, it does. Pretty inconsistent huh

**Comment by AlexTheSysop42** [comment]
I think it's tied to the body, so all you have to do is take out their brain and you can do anything with that (including cloning/defibbing a monkeyman)

**Comment by Iamgoofball** [comment]
this KILLS TACTICAL SUICIDE

**Comment by george99g** [comment]
@optimumtact This is still an issue.
Someone else can deal with it, I'm tired of all of this.
