### ISSUE TITLE
All limbs in character setup appear as prosthetic

### ISSUE THREAD

**Issue by CRTXBacon** [tgstation/tgstation#36209]
Has happened to me regardless of whether or not I have the prosthetic limb trait enabled, and seems to apply to all characters in character setup until a new round starts. On both occasions I had joined after roundstart.

![image](https://user-images.githubusercontent.com/34610106/37048025-91a9a280-2164-11e8-88e6-4a76666fefbd.png)

**Comment by Xhuis** [comment]
This is fixed now, I believe.
