### ISSUE TITLE
trait picks don't respect character slots

### ISSUE THREAD

**Issue by vuonojenmustaturska** [tgstation/tgstation#36211]
@Xhuis 
Got a bug report via ahelp:
"If you swap characters, the one you loaded on connection's traits apply to whoever you pick; to change, you have to change charslot, then reconnect  If you simply select a different slot and join game, it'll apply the other charslot's trait picks "

**Comment by DaxDupont** [comment]
Dupe of like 3 bug reports

**Comment by Xhuis** [comment]
Duplicate of #36119
