### ISSUE TITLE
screen cant stop doing the harlem shake

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#36213]
i was wearing a heck suit on the mining shuttle in transit, got smashed into by bubblegum hallucination nearly before/directly after landing, my screen started shaking and never stopped until i killed myself out of pain. please dont let this ever happen again

**Comment by Robustin** [comment]
Should probably change title, this almost certainly has to do with screen shake code and not hallucinations.

**Comment by Tacolizard** [comment]
@ShizCalev misleading title

**Comment by ShizCalev** [comment]
fixed.

**Comment by Tacolizard** [comment]
nice meme

**Comment by SuperNovaa41** [comment]
Probably no longer an issue, no recent reports
