### ISSUE TITLE
Movement path of bots has strange texture.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#36223]
If you are a ghost, movement path of all bots will look like this.
![image](https://user-images.githubusercontent.com/34580767/37094949-9896c9b2-2225-11e8-8ad7-327ffc1a4a0b.png)
This is a beespky path for example.

**Comment by Buggy123** [comment]
That's the universal "MISSING TEXTURE" texture. Looks like someone fucked up the sprite path or something.

**Comment by ShizCalev** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
I haven't touched those textures or the code for this at all. I don't think it was me.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/100c4b6114fa3ce544063831349994544ea0df37/code/modules/mob/living/simple_animal/bot/bot.dm#L1008-L1014

**Comment by Cruix** [comment]
This appears to be caused by a difference in how 512 handles images with null icons compared to 511.
