### ISSUE TITLE
Pacifists can't use tasers, but can use stun batons

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#36224]
Seems inconsistent. To me, it'd be more fun if pacifists had access to all non-damaging weaponry. Similar to a non-lethal playthrough.

**Comment by AlexTheSysop42** [comment]
yeah, they also can't use wormhole projectors (although to be fair, those do a small amount of damage) and probably wands/staves, because they're a subtype of gun (once again, some of those a pretty deadly, so those are reasonable, but healing isn't).

**Comment by TheDreamweaver** [comment]
For the same reason, pacifists ironically also cant use medibeam guns

**Comment by PKPenguin321** [comment]
fixing
