### ISSUE TITLE
Circuit printer says there's negative time until print is completed

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#36239]
1. take circuit imprinter
2. insert metal
3. i pasted in this script: https://tgstation13.org/phpBB/viewtopic.php?f=2&t=14420#p365647
4. start printing it
5. when the timer hits 0 it keeps going well into the negatives. print never completes

![](https://puu.sh/zCUF5/62a5009876.png)

apparently my circuit printer wasnt upgraded or something maybe thats part of it 
round ID 84620 on bagil

**Comment by ShizCalev** [comment]
@Xhuis #35657

https://github.com/tgstation/tgstation/blob/e582cd08a393ac436f4584875dd4b73bedfe5004/code/modules/integrated_electronics/core/printer.dm#L145
https://github.com/tgstation/tgstation/blob/e582cd08a393ac436f4584875dd4b73bedfe5004/code/modules/integrated_electronics/core/printer.dm#L280
These should all be using DisplayTimeText too.

**Comment by Xhuis** [comment]
Gahhhh
