### ISSUE TITLE
Damaged Shuttles aren't landing

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#36231]
Twice in the last 24 hours I've seen both White Ship and Emergency Shuttle stay in transit space when partially destroyed before/during launching (one by a bomb, the other by a BOH sing).

Needless to say having the nuke disk on a ship that never leaves transit space is problematic for nukeops.

**Comment by SpaceManiac** [comment]
Did a couple quick tests on local and bombing the mobile port seems to leave the port itself in perpetual transit while still delivering the shuttle contents to the destination. No idea what's happening there or why it differs from Robustin's observations.

**Comment by Dennok** [comment]
Destroying turf under docking_port broke the shuttle.
When the shuttle flies, the docking port remains.
