### ISSUE TITLE
The Radience (Endround Eminence) is stopped by mere holy tiles.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#36248]
Issue reported from  Round ID: 84627 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

It's round end, let the poor boy zoom around.

>![dreamseeker_2018-03-08_00-39-38](https://user-images.githubusercontent.com/33107541/37135009-3f9d04f4-2269-11e8-8d97-59747b69e8c4.png)
![dreamseeker_2018-03-08_00-39-48](https://user-images.githubusercontent.com/33107541/37135013-442ad8ac-2269-11e8-882a-a24f55e6df2a.png)

**Comment by ExcessiveUseOfCobblestone** [comment]
let him be a rethemed ascended sling who blows people up on a whim.
