### ISSUE TITLE
It is currently now IMPOSSIBLE to clean anything off the floor.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#36249]
Issue reported from  Round ID: 84629 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

THE CURRENT STATE OF TG:
![dreamseeker_2018-03-08_00-49-05](https://user-images.githubusercontent.com/33107541/37135271-892066f6-226a-11e8-91e9-124c9bd8d6e4.png)

EDIT: _NOTHING_ CLEANS. NOT EVEN THE **JANICART FLOOR BUFFER**.

**Comment by Teepeepee** [comment]
![image](https://user-images.githubusercontent.com/17479709/37135577-9c229172-227c-11e8-8aa0-c151282a9a81.png)
add it onto this

**Comment by ExcessiveUseOfCobblestone** [comment]
#36246

**Comment by ShizCalev** [comment]
Duplicate of #36246

**Comment by ShizCalev** [comment]
Fixed by #36242
