### ISSUE TITLE
Airlock Painters don't paint airlocks.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#36245]
Issue reported from  Round ID: 84625 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

Using an airlock painter on a finished airlock and selecting an option does nothing to the airlock.

**Comment by ShizCalev** [comment]
@kevinz000 attack chain issue? #33166

**Comment by Singularbyte** [comment]
Duplicate of #35223?

**Comment by ShizCalev** [comment]
duplicate of #35223
