### ISSUE TITLE
Unable to Clean Floors with anything

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#36246]
Issue reported from  Round ID: 84627 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Tried to clean floors with: Space Cleaner in a bottle, cleaning grenades, soap, and a wet mop. None of them resulted in any clean floors. Tried reconnecting to see if the problem was on my end, floors were still dirty.

**Comment by Doppeltongue** [comment]
Add janicart floor buffer upgrades to that list.

**Comment by ShizCalev** [comment]
This would potentially cause major issues if someone becomes a slaughter demon.

**Comment by ShizCalev** [comment]
Unable to repo on master.

**Comment by Qustinnus** [comment]
Because I fixed it already

**Comment by ShizCalev** [comment]
Fixed by #36242
