### ISSUE TITLE
Syndie Lavaland Base Turrets Shoot Monkeys

### ISSUE THREAD

**Issue by killerbrochen** [tgstation/tgstation#36256]
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm
Round ID: 84647
Server revision compiled on: 2018-03-08
The following pull requests are currently test merged:
#36186: 'this must be the work of a syndicate guardian: adds a new gamemode' by Iamgoofball at commit 0a4f9a
Based off origin/master commit: 84d4b3
Revision: 79b96dd55df6140a0ea79a6c62b9af869a655c9e
Server tools version: /tg/station 13 Server v3.2.1.15
Server tools API version: 3.2.0.2
Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
Enforce Continuous Rounds: 8 of 19 roundtypes
Allow Midround Antagonists: 6 of 19 roundtypes
All Game Mode Odds:
traitorchan 24.5%
traitor 18.4%
clockwork_cult 8.2%
cult 8.2%
secret_extended 2%
nuclear 16.3%
revolution 12.2%
wizard 10.2%

Easy to see, just pull a monkey out and the turrets shoot it. Admin said they already had Syndie faction.

**Comment by ExcessiveUseOfCobblestone** [comment]
Monkeys don't have the syndicate faction???

**Comment by ShizCalev** [comment]
@ExcessiveUseOfCobblestone 
![image](https://user-images.githubusercontent.com/6209658/37215717-c3423d74-2386-11e8-9afc-5bda93edc87d.png)

**Comment by killerbrochen** [comment]
I said in the post that they already do have syndie tag. They get shot anyway.

**Comment by ExcessiveUseOfCobblestone** [comment]
@ShizCalev you won't believe the bug
