### ISSUE TITLE
ai-type things can go to lavaland

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#36269]
as far as I'm aware ai cannot directly access mining station or gulag's cams; however, they can track a person on mining base or gulag and see through the cams down there. In addition, the eminence can move its view over the mining shuttle and ride it to lavaland

**Comment by Kromgar** [comment]
jump to network

**Comment by GunHog** [comment]
The AI certainly can through switching camera networks, just as Kromgar mentioned. The AI being able to interact with the Gulag and Mining Base equipment through the cameras there is not a bug.

**Comment by ExcessiveUseOfCobblestone** [comment]
@optimumtact non-issue sweetie

**Comment by factoryman942** [comment]
fucky
