### ISSUE TITLE
byond 511 cant see plasma

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#36262]
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by praisenarsie** [comment]
fucking beesting, close this before a maintainer shouts at you.

511 can't see gases and just run 512 already.

**Comment by BeeSting12** [comment]
no i dont like change

**Comment by praisenarsie** [comment]
2bad, it's not getting reverted

**Comment by ninjanomnom** [comment]
update

**Comment by Dennok** [comment]
Compile on 511, launch and connect 511 512 clients, and see gasses.

**Comment by ninjanomnom** [comment]
If the server is run in 511 then yeah 511 clients can see gases
