### ISSUE TITLE
skewium doesn't move light glows

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#36267]

**Comment by AlexTheSysop42** [comment]
light glows used to also show over the AI static thing, maybe related?

**Comment by py01** [comment]
This also occurs with rotatium. Here are some screenshots from rotatium and skewium respectively.
https://gyazo.com/bb5fa8ebd3c5e89515b801830a219b7f
https://gyazo.com/0b71dda9c070a255fde36b5db57f57a7
