### ISSUE TITLE
Sentient Disease holds back arrivals shuttle

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#36279]
Round ID: 84680

TC traded to become disease, landed in a miner, was cured before I could do anything, was given a redo, and ended up in a brain-dead on the arrivals shuttle.

Waited a bit to see if they would come back, Ghosted, and the arrival shuttle left.

**Comment by ExcessiveUseOfCobblestone** [comment]
If this is a bug i'd like this to be elevated to a feature.

A disease should not be trapped in arrivals nowhere land
