### ISSUE TITLE
Players with TRAIT_PACIFISM are able to fire mech weaponry

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#36276]
Revision: 55f5870b7bf48a5a17b46386e8bf6244978d751f

As the title said, players with the pacifist trait are able to fire mech guns freely.

**Comment by XDTM** [comment]
I don't kill people, my mech does

**Comment by Irafas** [comment]
working on a fix at the moment. With a bit of luck I should be able to make the pr soon.

**Comment by Irafas** [comment]
ha holy shit it actually worked first time. PR up soon.

**Comment by 81Denton** [comment]
Fixed in #36293 (that was fast!)
