### ISSUE TITLE
Prosthetic legs do not respect other leg layering

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#36272]
![image](https://user-images.githubusercontent.com/6209658/37191154-e573fe6a-232b-11e8-9ad9-329ae7a23fa1.png)

![image](https://user-images.githubusercontent.com/6209658/37191151-decfc81e-232b-11e8-97e6-41ef124aa668.png)

**Comment by ArcaneDefence** [comment]
This is a duplicate of https://github.com/tgstation/tgstation/issues/20603
