### ISSUE TITLE
Custom steal objectives do not announce properly

### ISSUE THREAD

**Issue by cedarbridge** [tgstation/tgstation#36273]
[Round ID]: 84674 
[Testmerges]: None likely involved though two present at the time.

[Reproduction]: Granted a player mob a generic antagonist role.  Gave them two objectives.  Survive on the shuttle and a custom steal objective to steal "/obj/item/stack/spacecash/c200"

End of round report and player notes only reported a single objective (the escape objective)

**Comment by Mooshimi** [comment]
Could we have an admin test this and see if any changes between now and 2018 fixed this?

**Comment by Mooshimi** [comment]
Justice12345 was willing to test this for us, seems to show just fine now.
![image](https://user-images.githubusercontent.com/85910816/178158122-cc9f9130-4f92-46e2-b71d-35dd14faf393.png)
