### ISSUE TITLE
Turbine in vacuum on round start can generate power

### ISSUE THREAD

**Issue by Jalleo** [tgstation/tgstation#36284]
Just turn it on and somehow it produces 9.9 kW power this was done on metastation. Its blast door was closed for both gas exits.

**Comment by vuonojenmustaturska** [comment]
Can confirm the turbine was producing power, though by the time i got there they had already started pumping 600K oxygen in, which maybe shouldn't produce power either?

**Comment by factoryman942** [comment]
Isn't turbine just 'there's air here, there's less/no air on the other side, air goes from one to the other, therefore turbine turns and makes power'? If so, just oxygen should be driving it even w/o a flame

**Comment by RandomMarine** [comment]
Yeah, that's the basic on how it works.

But there's an actual issue in that after all the air is _gone_, it will continue to produce power.

**Comment by Poojawa** [comment]
This is also present on the Pirate shuttle. and dumping fuel into it doesn't generate any more power. Upgrading the parts does magically generate more power though.
