### ISSUE TITLE
Delta whiteship airlocks fail to cyclelink

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#36282]
Revision: 55f5870b7bf48a5a17b46386e8bf6244978d751f

The Delta whiteship's airlocks fail to cycle link:

`MAP WARNING, External Airlock at Abandoned Ship (128,153,10) failed to find a valid airlock to cyclelink with!`
`MAP WARNING, External Airlock at Abandoned Ship (121,153,10) failed to find a valid airlock to cyclelink with!`
`MAP WARNING, Internal Airlock at Abandoned Ship (110,146,10) failed to find a valid airlock to cyclelink with!`

Cyclelink helpers seem to be placed properly, no clue why they're not working.

**Comment by ShizCalev** [comment]
Pretty sure it's a template loading issue.

**Comment by 81Denton** [comment]
Closed by: #37237

**Comment by 81Denton** [comment]
Nevermind, this is still an issue on: Revision: c4900e785d5e31929f2e469bbc3c60283efedf87

**Comment by kriskog** [comment]
Just went through the logs, this seems to be fixed
