### ISSUE TITLE
Custom Title Screens aren't working

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#36296]
@MrStonedOne Not sure if this is a server or code issue

**Comment by MrStonedOne** [comment]
It could be web/cdn resource related, but clients SHOULD download that from the server.

**Comment by SpaceManiac** [comment]
Been broken on live but working locally for weeks, I suspect it's a config or server issue somehow.

**Comment by PKPenguin321** [comment]
This makes me sad hope it gets fixed

**Comment by KorPhaeron** [comment]
They're working again guess we will never know
