### ISSUE TITLE
PDAs are just a blank window

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#36303]
Issue reported from  Round ID: 84711 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

![sjbyngd 1](https://user-images.githubusercontent.com/17237624/37233935-94b74ab6-23f5-11e8-97f8-d0817f54e799.png)

**Comment by SpaceManiac** [comment]
PDAs only or everything?

**Comment by 81Denton** [comment]
Had the same issue yesterday; it affected machines too. Restarting BYOND fixed it.
Version: 511.1385

**Comment by DaxDupont** [comment]
Both 512 and 511 were a no go so restarting didn't help

**Comment by DaxDupont** [comment]
Also just PDAs it seems

**Comment by Cyberboss** [comment]
This is a dupe of a byond issue i think

**Comment by ShizCalev** [comment]
Duplicate of #31745
