### ISSUE TITLE
can't change admin permissions/ranks via playerpanel

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#36304]
also none of the gamemasters/admintrainers can edit anything now i'm upset

legacy system is set to 1.

when i try to change an existing admin's rank it only shows fakemin and adminobserver and i can't change anyone's flags at all
when i try to change a non admin's rank the window doesn't even pop up but doesn't say i don't have permission either.

**Comment by Jordie0608** [comment]
Server config was incorrect.
