### ISSUE TITLE
Fire Safety budget cuts in lavaland syndicate base

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#36314]
Lavaland base was repurposed for an admin event, where it was discovered all of the fire extinguishers were 'fake'. I don't know if this means they were empty, look-a-likes, or what have you. But they didn't work.

**Comment by 81Denton** [comment]
I'm unable to repo this on localhost (Revision: c532ded9c0ee94485211a183957f3cdd588f15b1).

Maybe it has been fixed already?

**Comment by Jalleo** [comment]
This was probably a error caused by the admin.

**Comment by kriskog** [comment]
Cant reproduce
