### ISSUE TITLE
Signaller Doesn't Trigger Singletanks (Maybe Not TTVs Either)

### ISSUE THREAD

**Issue by BlueNothing** [tgstation/tgstation#36327]
Round ID: #84766
[Testmerges]: # I do not believe testmerges are responsible.

[Reproduction]: # Remote signalling devices do not appear to detonate singletank bombs. For an example, make a full tank of heated plasma, use an igniter and remote signaller for the fuse, and pulse the appropriate signal. In the error case, the bomb won't go off. It may also help to try this with a TTV, with one side hot plasma and the other side cold oxygen, using a remote signalling device as the activator.

**Comment by halitosisman** [comment]
I can confirm signalers do not work on TTVs either.

**Comment by BlueNothing** [comment]
Damn, that sucks.

**Comment by GrayRachnid** [comment]
Cannot reproduce. Both the assembly and the TTV worked for me.

**Comment by kriskog** [comment]
Work fine now.
