### ISSUE TITLE
Dumping Contents goes on the Table

### ISSUE THREAD

**Issue by Kerbin-Fiber** [tgstation/tgstation#36328]
#33166 [READY]Refactors storage handling from /obj/item/storage to a component.
Click and drag a box on a table to attempt empty its contents but the box gets placed on the table instead and doesn't get its items dropped out.

**Comment by kevinz000** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaa

**Comment by AlexTheSysop42** [comment]
was this at the holodeck?
