### ISSUE TITLE
Bluespace Wormhole Projector is broken

### ISSUE THREAD

**Issue by Kerbin-Fiber** [tgstation/tgstation#36329]
[Round ID]: 84771

 #36221: '[kinda sorta ready] Infiltration mode' by astralloop at commit b7dc2b 

#33166: '[READY]Refactors storage handling from /obj/item/storage to a component.' by kevinz000 at commit 680685 

Shoot Bluespace Wormhole projector at a wall, notice a wormhole isn't created, make a titanium wall, shoot it directly to have the bullet bounce off and hitself, get teleported into space. I tried shooting walls multiple times and not a single wormhole was made.

**Comment by kevinz000** [comment]
this is not due to storage as far as i know but i will test

**Comment by ExcessiveUseOfCobblestone** [comment]
@kevinz000 anything to do with that fix for the out of bounds projectiles?
