### ISSUE TITLE
Bluespace body bags can trap mobs who are unable to escape.

### ISSUE THREAD

**Issue by TrojanCoyote** [tgstation/tgstation#36325]
You can easily plop down a bluespace body bag under the mob, zip it, then pick it up and do anything like space or incinerate the body bag for easy disposal of pretty much any mob.

**Comment by Darkgenerallord** [comment]
press the resist button

**Comment by ExcessiveUseOfCobblestone** [comment]
not a bug

**Comment by kevinz000** [comment]
not an issue

**Comment by AlexTheSysop42** [comment]
you can also type resist if you don't have the button

**Comment by ShizCalev** [comment]
pretty sure this is the intent.


though that said..... can you bodybag an ash drake?

**Comment by ExcessiveUseOfCobblestone** [comment]
also a feature if true
