### ISSUE TITLE
Reproduction Crossbreeding does not work.

### ISSUE THREAD

**Issue by JessHorserage** [tgstation/tgstation#36336]
Issue reported from  Round ID: 84795 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Round ID]: #84795

[Reproduction]: # Try to click an adult slime with an extract and it does not consume it.

**Comment by AlexTheSysop42** [comment]
are you sure it was still testmerged?

**Comment by Tlaltecuhtli** [comment]
its not

**Comment by JessHorserage** [comment]
I'm retarded, didn't think it would be not testmerged.
