### ISSUE TITLE
Delta's Incinerator Pipes replaced with Mimics- Adventurers Protest

### ISSUE THREAD

**Issue by RandolfTheOkay** [tgstation/tgstation#36332]
Issue reported from  Round ID: 84776 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

Unsure whether this is also the case for other station's incinerators (and by incinerator I mean turbine, to clarify), but I had tried to make tritium as I usually do, and saw there were so minor map changes that involved some changes to the turbine itself. Set it all up, everything was well, then realized the gas wasn't leaving the output. Went to space, went to check if the pressure was existent in the exterior pipes, and lo and behold, found out that those pipes weren't pipes but a horrid abomination meant to resemble pipes, that were indestructible, irremovable, and didn't move gas. The pipes inside the station were fine, sans one beneath the reinforced table. Everything else from the output to the injector in space were all fake pipes.

**Comment by ShizCalev** [comment]
Unable to replicate issue on master, all the pipes seem to be functioning correctly.

**Comment by ShizCalev** [comment]
Hm, actually I see why it's not outputting properly, but the whole indestructible thing cannot be duped.
