### ISSUE TITLE
tgui Install_dependencies.bat stopped working for me

### ISSUE THREAD

**Issue by JJRcop** [tgstation/tgstation#36338]
I kinda wasted a bunch of time using [install_dependencies.bat](https://github.com/tgstation/tgstation/blob/111cd316a92f5f5840d96b1fc4bbe4cb7b1ce6fd/tgui/install_dependencies.bat) to install node.js dependencies for building tgui, it was suggested that I instead use `npm install` and `gulp --min` myself instead of using the batch scripts, and it worked (I cleaned my working directory first, and I had gulp-cli installed globally.)

The script should either be simplified (even more than it already is), rewritten, or removed.

**Comment by praisenarsie** [comment]
@Cyberboss @vuonojenmustaturska

**Comment by san7890** [comment]
I think the current compile chain has drastically simplified since when this issue has published with vendored Node versions, etc. to where this no longer applies (also install_dependencies.bat isn't a thing anymore i think)
