### ISSUE TITLE
Clicking "Track" as AI on Crew Monitoring Console causes client to freeze

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#36334]
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)
**Round ID** 
84789

**Test merges**
#36321: 'Create ERT refactor' by vuonojenmustaturska at commit dae3dc
#33166: '[READY]Refactors storage handling from /obj/item/storage to a component.' by kevinz000 at commit ea3077

**Reproduction**
1. As the AI, click the Crew Monitoring Console button on your UI. 
2. Click a Track button next to a crewmember. 
3. The client locks up.

**Comment by Jalleo** [comment]
Your byond version please. if Stable or not latest beta go to latest beta as bug is likely fixed.

**Comment by kevinz000** [comment]
not storage far as i know but i will test

**Comment by cacogen** [comment]
@Jalleo 
It's up to date.

![](https://i.imgur.com/ekkYGbA.png)

**Comment by SpaceManiac** [comment]
Looks like you have "Stable" selected. Try "Beta" and see if the issue persists.

**Comment by cacogen** [comment]
shit

**Comment by ShizCalev** [comment]
Gonna guess that fixed it.
