### ISSUE TITLE
Holographic animals can gain sentience

### ISSUE THREAD

**Issue by Catistian** [tgstation/tgstation#36348]
Issue reported from  Round ID: 84829 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 511

Title. The random human-level intelligence triggered and I became a penguin on the holodeck, and I then immediately died as soon as I left

**Comment by XDTM** [comment]
That sounds great tbh, a hologram gaining self awareness knowing it'll stop existing if someone changes the channel

**Comment by Anonmare** [comment]
Add a random event that makes it so that the holodeck can gain sentience

Have it go Moriaty on the crew in its attempt to escape

**Comment by ExcessiveUseOfCobblestone** [comment]
pwease mistaw ai i want to be fwee :33333

**Comment by Kromgar** [comment]
This is a feature. You have to beg the humans to turn off holodeck controls so you can be a real boy

**Comment by AnturK** [comment]
Just give them a warning they will die if they leave.
