### ISSUE TITLE
Rainbow slime clusterbangs do not work properly

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#36342]
Using plasma will clusterbang correctly, but the items are glitchy, some cannot be picked up, some vanish and reappear a moment later, some items are picked up but then dropped at your feet the next time you move.

Roundid:84820

>The following pull requests are currently test merged:
#36321: 'Create ERT refactor' by vuonojenmustaturska at commit dae3dc
#33166: '[READY]Refactors storage handling from /obj/item/storage to a component.' by kevinz000 at commit ea3077

@DaedalusGame

**Comment by DaedalusGame** [comment]
i love clusterbangs and i will fix this soon

**Comment by ShizCalev** [comment]
Also see #35908
