### ISSUE TITLE
PA can't be emaged

### ISSUE THREAD

**Issue by lightcat** [tgstation/tgstation#36356]
The Particle accelerator can't be emaged and uses up the emag (If on citadel code, unless you have it as well.)

This machinery used to be able to and apparently still accepts a card it just doesn't do anything with it.

**Comment by PKPenguin321** [comment]
poor emag what did citadel do to you

**Comment by 81Denton** [comment]
@PKPenguin321 needs an external use only disclaimer for citadel

**Comment by 81Denton** [comment]
@lightcat I don't see an emag_act() or anything regarding IDs in the PA code. It doesn't accept an ID either (Revision: 21dc637879ab9fd7d55d815fcecb0e61585232f0).

Looks like you could never emag it in the first place.

**Comment by ShizCalev** [comment]
There's no logic associated with emagging them. You can however increase the maximum limit of them by cutting their wires.

**Comment by lightcat** [comment]
This used to be a feature, the logic was you could send it up to higher frequencies and release whatever was inside of it.
