### ISSUE TITLE
Bowman Headsets and Flashbangs

### ISSUE THREAD

**Issue by Ahammer18** [tgstation/tgstation#36366]
Security Bowman Headsets do not seem to offer protection from flashbangs anymore, although the flavor text suggests otherwise. Either the flavor text needs to be updated or the protection needs to be fixed.

[Round ID]: # 84865
[Reproduction]: # Simply equip a Security Bowman Headset and trigger a flashbang near yourself, according to the flavor text (and my previous understanding of the item) they should offer complete protection from the 'bang' part of the flashbang.

**Comment by ExcessiveUseOfCobblestone** [comment]
how far are you from the flashbang and what are the effects? flashbangs need both headset and glasses to work, and they won't ever work if you're on the same tile as the flashbang.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/f2263e83fb52bed7f7b33016a5fe70733ee842da/code/game/objects/items/devices/radio/headset.dm#L76-L81

flags are correct.

**Comment by Ahammer18** [comment]
I believe it was user error, I think I was just too close, apologies.
