### ISSUE TITLE
AI is unable to open glass doors

### ISSUE THREAD

**Issue by Davidj361** [tgstation/tgstation#36369]
[Round ID]: # A couple rounds before 84865

[Reproduction]: # 
AI is unable to open glass doors.
1. Be AI
2. Click a glass door and try shift+click.
3. Glass door does not open.

**Comment by ShizCalev** [comment]
#33166 @kevinz000

**Comment by RandomMarine** [comment]
If you're talking about windoors, dupe of #36358
If you're talking about glass airlocks, **be more specific**.

**Comment by ShizCalev** [comment]
Duplicate of #36358
