### ISSUE TITLE
rped accepts tools

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#36378]
holding a tool in your hand, then clicking the rped with it, rejects the tool with a message saying it only accepts stock parts
however, if you're holding the rped and have full pockets, attempting to equip the tool successfully puts it inside the rped
in addition, if you drop a tool then click it with the rped (as if to pick up a pile of parts from the floor) it gets picked up and stored

**Comment by SpaceManiac** [comment]
Round ID? Testmerges?

**Comment by factoryman942** [comment]
Round should be 84877

**Comment by ExcessiveUseOfCobblestone** [comment]
Please put testmerges in >:(

**Comment by SpaceManiac** [comment]
[84877](https://atlantaned.space/statbus/round.php?round=84877) had #33166, #36321, #36350 testmerged.

**Comment by Buggy123** [comment]
I'm calling it, its #33166. Hasn't been a single testmerge where it hasn't broken _something_.

**Comment by ExcessiveUseOfCobblestone** [comment]
@kevinz000
