### ISSUE TITLE
The bots are displaying missing textures when patrolling whilst diagonstic sensors are enabled

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#36373]
[Round ID]:84869

![image](https://user-images.githubusercontent.com/12382984/37309385-b6a84432-2638-11e8-94bd-02d02b91a6fa.png)

[Round ID]:84869

**Comment by Anonmare** [comment]
[Round ID]:84869

**Comment by SpaceManiac** [comment]
Duplicate of #36223.

It's a Markdown thing. `[a]: b` defines the link for a reference, which is an invisible statement and only has an effect if `[a]` is written somewhere else.

**Comment by ShizCalev** [comment]
Duplicate of #36223
