### ISSUE TITLE
Giving a player control of a bot doesn't give the correct hud to the player

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#36381]
Master
Players should be given the appropriate data_hud_type, though it doesn't seem to be happening.

Repo:
Drag a ghost onto beepsky
The player now controlling beepsky has no security hud overlays

**Comment by Mooshimi** [comment]
i am have sechud
![image](https://user-images.githubusercontent.com/85910816/198703328-a811ad5b-3456-42d8-819b-a7c8cfcdd0fe.png)
