### ISSUE TITLE
His Grace can duplicate if you put it in a deep fryer.

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#36385]
I totally forgot about this and was recently reminded about it because of a discord conversation.
STEPS TO REPEAT: 1: Get his grace (late frenzy stage where it cant leave your hand?)
2: Go into the deep fryer and dunk it in. 3: His grace doesn't leave your hand, but somethings deep frying. 
4: You take it out of the deep fryer with your other hand, and now you have a deep fried his grace on the ground, and one in your hand. 
5: You eat the deep fried his grace, and it becomes another one. TWO HIS GRACES WHAT INSANITY.

**Comment by Buggy123** [comment]
f-feature

**Comment by Hatfish** [comment]
How many times can you do that?

**Comment by XDTM** [comment]
Probably loc shenanigans due to a lack of NOSROP checking, not real duplication

**Comment by Jalleo** [comment]
@Iamgoofball

**Comment by vuonojenmustaturska** [comment]
The problem is that his grace jumps out of the deep fry holder object, the frier respects nodrop. Easiest and probably best solution is to just blacklist it.
