### ISSUE TITLE
AI Beepsky Path Graphic Glitch

### ISSUE THREAD

**Issue by Davidj361** [tgstation/tgstation#36395]
[Round ID]: # 84913

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
As AI you see weird missing textures on Beepsky's explored path.

![](https://i.imgur.com/egwsYLb.png)

1. Be AI
2. Look at Beepsky while he's moving around the station
3. See the missing textures.

**Comment by PKPenguin321** [comment]
Pretty sure this is a dupe

**Comment by praisenarsie** [comment]
>Pretty sure this is a dupe

**Comment by Jalleo** [comment]
It is a dupe.

**Comment by AzureWildfire** [comment]
It happens with the medibots too

**Comment by SpaceManiac** [comment]
Duplicate of #36223
