### ISSUE TITLE
Rod of Asclepius Duplication

### ISSUE THREAD

**Issue by darkpaladin109** [tgstation/tgstation#36408]
[Reproduction]:  If you sever a limb that's holding a Rod of Asclepius, a whole bunch of extra copies of it spawn. They get stuck to your arms like normal if you pick them up, but don't seem to give you the pacifism and healing aura, though this may be because I had a Dark Blessing on my other arm at the time.

**Comment by TheDreamweaver** [comment]
Thank you.
