### ISSUE TITLE
Teleporting stuff from the deep fryer to you hand

### ISSUE THREAD

**Issue by AzureWildfire** [tgstation/tgstation#36404]
Issue reported from  Round ID: 84924 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

The bug bassically is, that with telekinesis you can teleport stuff frying in the deep fryer to your hand, from anywhere if you see the deep fryer.

**Comment by Cruix** [comment]
@Xhuis You broke this four days after I fixed it.

**Comment by Xhuis** [comment]
Where?

**Comment by Cruix** [comment]
https://github.com/tgstation/tgstation/pull/32482
