### ISSUE TITLE
Repeating issues

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#36416]
Despite the issues being checked now and then there are probably about 200 or so out there that are repeat issues. Also perhaps 200 of the 1.1k issues probably are just not closed after fixing them.

**Comment by davethwave** [comment]
Just checked and we have even have an issue from 2014 and a load from 2015... Me thinks that someone needs to go through them to at least close the ones that are fixed or not relevant anymore.

**Comment by Davidj361** [comment]
Or just close issues that are more than a year old.

**Comment by Cyberboss** [comment]
We know, this isnt helping
