### ISSUE TITLE
Ghost huds work while alive.

### ISSUE THREAD

**Issue by ishitbyabullet** [tgstation/tgstation#36411]
Issue reported from  Round ID: 84939 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Round ID]: 84939

[Testmerges]: 75979e

[Reproduction]: I don't know how to reproduce it because the person who discovered it won't tell anyone, but apparently having your ghost hud while your body has a diagnostic hud will allow you to have an omni hud if you get revived while still wearing it.

**Comment by ExcessiveUseOfCobblestone** [comment]
@ishitbyabullet if they play TG hmu with their ckey
