### ISSUE TITLE
Player mood is uneven at roundstart

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#36414]
#34791 "Mobs start with a random nutrition amount" made it so that mobs start with a random nutrition amount.

If you're one of the lucky players that start with ≥350 nutrition, you start with the positive "I have recently had some food." moodlet.

**Comment by ExcessiveUseOfCobblestone** [comment]
a-a-a-and?

**Comment by 81Denton** [comment]
On second thought, does it even matter if some player start out with +3 mood and others don't?
