### ISSUE TITLE
GET IT OUT mood never goes away

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#36444]
Say when glass embeds from a window exploding embeds in your chest If you take the glass out of your flesh the bad mood  persists forever.

**Comment by ShizCalev** [comment]
#36434 fixes this.

**Comment by Kromgar** [comment]
@ShizCalev I'm not sure if I should make a report but if you're wearing drake armor and have the self-combustion spell you get a major negative mood from being on fire. Even though fire can not harm you whatsoever in any way.
