### ISSUE TITLE
Transform matrix cannot be accessed by varedit

### ISSUE THREAD

**Issue by Alek2ander** [tgstation/tgstation#3646]
82d72ae0bce442791f1cee512989a3da305cde5a
April 25, 2014

1. VV an object.
2. Find the variable transform, which is a reference to a /matrix.
3. Click it to go to the reference.
4. Whoops, you get the datum with the same ID as the matrix if it exists, or no response if it doesn't. You cannot access the matrix.

**Comment by Razharas** [comment]
Really weird shit, i can do it ok on the live server but cant in the local test game
Unexplainable bullshit

**Comment by Jalleo** [comment]
Is this a bug or not a bug then because by what Raz is saying I dont know.
