### ISSUE TITLE
If the round time hits 24 hours, it loops back to 0.

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#36465]
![image](https://user-images.githubusercontent.com/31222036/37538306-27c0169c-2948-11e8-9bb1-f303929b0fef.png)
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 85065

Server revision compiled on: 2018-03-15

e34930

Revision: e34930714b1e4596c48f5acb019efdb2c8d8bafe

Server tools version: /tg/station 13 Server v3.2.1.15

Server tools API version: 3.2.0.2

**Comment by praisenarsie** [comment]
@Cyberboss @MrStonedOne

**Comment by praisenarsie** [comment]
Terry was at 24 hours, i promise. I don't know if this affects logs.

**Comment by praisenarsie** [comment]
i've been told this
![image](https://user-images.githubusercontent.com/31222036/37538658-2fe62fae-2949-11e8-9c78-25525e89a1a3.png)

**Comment by Iamgoofball** [comment]
do you know how 24 hour time works

**Comment by praisenarsie** [comment]
if it's intended whatever but there is still an alternative issue at hand that round time starts at 23:00:00 for some reason

**Comment by praisenarsie** [comment]
![image](https://user-images.githubusercontent.com/31222036/37543859-ea461bdc-295a-11e8-9235-3b1e49fdf839.png)
confirmed starts at 23

**Comment by praisenarsie** [comment]
@kevinz000 fix your shit

**Comment by RandomMarine** [comment]
Even in space, you cannot escape daylight savings.

**Comment by newfren** [comment]
it's not a fuckin' clock that's supposed to reset at 24 hours lmao it's supposed to show how long the round has gone on for.

**Comment by MrStonedOne** [comment]
kek, i'll fix this, its likely a terry only issue since i don't think i disabled daylight saving on it.

**Comment by MrStonedOne** [comment]
@tgstation/commit-access add blame-mso tag

**Comment by MrStonedOne** [comment]
Confirmed fix.

**Comment by Iamgoofball** [comment]
Wait hold up why was a round STILL ACTIVE AFTER 24 HOURS

**Comment by MrStonedOne** [comment]
Rounds were starting saying it was 23 hours in then overflowing back to 0 at 1 hour in

**Comment by Iamgoofball** [comment]
Ah

**Comment by ShizCalev** [comment]
What's the fix for this? I'm seeing this happen on other servers that I host.

**Comment by Jordie0608** [comment]
Disable daylight saving on the system clock.
