### ISSUE TITLE
I have to double click on things to interact with them unless they are in inventory.

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#36476]
[Round ID]: #85091

so if I have to pick something up or open a door or use a button or punch myself or something I have to double click it

but if I'm taking something out of my bag then I only have to single click it

if I'm using a computer console I have to double click it to open the window but single click the buttons in the window

I need to double click my action buttons to use them

I need to double click the oxy on/off button on the right to use it

I only need to single click the mood icon

help this is the most frustrating shit. I had this problem a long time ago then I downgraded to 511 and stopped having it. I upgraded to 512 and didn't have it then I upgraded again to the most recent branch of 512 (.1415) and the problem came back. I just want to be able to see gas and single click food to pick it up.

**Comment by MrStonedOne** [comment]
I've seen reports this happens if byond is ran on the non-primary monitor in multiple monitor setups.

**Comment by newfren** [comment]
I am running it on my laptop.

**Comment by newfren** [comment]
more info:

action buttons are inconsistent, as is the oxygen button on the right - sometimes they require 1 click, sometimes they require 2.

clicking a tile to turn around is inconsistent, requiring 2 clicks always or sometimes 1 click apparently according to the tile I am clicking on.

It's inconsistent round to round - I played a round earlier today (unfortunately did not note down the round ID) as an assistant where I could single click on anything I wanted. However round 85256 (a round I played later on the same day, although after some merges) I have to double click everything again.

**Comment by newfren** [comment]
more info on turning around: turning south appears to be much more consistently one click than turning north. Turning around by using a tile that's further away seems more consistent than using one that is close. what the fuck is wrong with my game

**Comment by newfren** [comment]
downgrading to 511 did not fix my issue

**Comment by newfren** [comment]
Shrinking my SS13 window and moving it to the bottom of my screen means I can turn around clicking on anything - seems like it's the top 2/3rd or so of my monitor that's causing the problem

**Comment by MrStonedOne** [comment]
reinstall your video drivers, disable any needless video card extras like geforce experience, and uninstall avast or avg if you use those scanners.

**Comment by Davidj361** [comment]
Try clearing your cache.

**Comment by Jalleo** [comment]
@newfren trued the methods above yet?

**Comment by newfren** [comment]
Sorry my computer's been a bit busted - I tried nothing and the problem has gone away. I'm going to assume it's fine because it's been fine over a couple rounds now.
