### ISSUE TITLE
Kudzu isn't supposed to grow into space?

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#36479]
![image](https://user-images.githubusercontent.com/6778786/37552216-18a776f2-2987-11e8-8956-1b1e37493c5d.png)

**Comment by Kromgar** [comment]
None of them had the space adapation ability

**Comment by AlexTheSysop42** [comment]
There's an event that makes kudzu in space, might be that?

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/b7a9a2a452466d411115bb9b8d925fd0a02132a3/code/modules/events/spacevine.dm#L509-L518

**Comment by Jalleo** [comment]
I believe that would be line 516. Since you cannot enter it if its dense. (It probably has the other checks that should be done there too.

**Comment by ExcessiveUseOfCobblestone** [comment]
You might be right, I may be thinking of a long time ago when /I/ initially added a density check to stop it spreading past airlocks which later got removed cuz I thought that was too strong.

**Comment by Razharas** [comment]
Line 516 is indeed there to make it so it doesnt spread through shit
