### ISSUE TITLE
windoor deconstruction hint message doesn't change

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#36482]
pre-screwdrivering it, it says maint panel is screwed in place
post-screwdrivering, it still says this

**Comment by Davidj361** [comment]
You need to have the glass door open to unscrew the maintenance panel.

**Comment by factoryman942** [comment]
this is correct

**Comment by Davidj361** [comment]
I'm unable to replicate this issue.

**Comment by jlsnow301** [comment]
![Screenshot 2021-12-28 230717](https://user-images.githubusercontent.com/42397676/147636155-4d3b09f0-8b20-4511-b5f9-20afa7cf27ff.png)
