### ISSUE TITLE
Syndicate lavaland base atmos is broken

### ISSUE THREAD

**Issue by NocturnalQuill** [tgstation/tgstation#36488]
The atmos tanks in the Syndicate lavaland base appear to not output any gas. Gas is present in the chambers, but the vent won't suck it up. Had an admin spawn in and have a look at it, he couldn't figure it out either.

**Comment by WJohn** [comment]
Looks like #34000 is back. Wasn't properly fixed it seems.

**Comment by Jalleo** [comment]
@Cyberboss

**Comment by AverageJoe82** [comment]
I had this issue in game, I broke though the glass and after doing so the gas started to spread strangely. I checked the other gas containment rooms using the ghost air analyze verb and it confirmed that the unbroken into containers were still not spreading their gasses.
