### ISSUE TITLE
Radio channels aren't logged in terms of what's said on what

### ISSUE THREAD

**Issue by silicons** [tgstation/tgstation#36499]
Tin. Makes some things a bit hard to figure out.1

**Comment by Mooshimi** [comment]
I think this is changed now 
![image](https://user-images.githubusercontent.com/85910816/133534049-dce1998c-10f0-4976-b1b9-7bc7dcbe72b0.png)
 you can find this in the "Get Current Logs" and then "telecomms.log" selection at the bottom

**Comment by dragomagol** [comment]
Appears to no longer be the case.
