### ISSUE TITLE
Cerulean blueprints are still usable even after they're deleted after a use. 

### ISSUE THREAD

**Issue by GrayRachnid** [tgstation/tgstation#36496]
[Round ID]: N/A I forgot and it was on citadel

[Testmerges]: N/A

[Reproduction]: Use a cerulean blueprint, don't close the window, move to another area, mark it again. Rinse repeat.

**Comment by AlexTheSysop42** [comment]
>not using them to hack doors

**Comment by fludd12** [comment]
![image](https://user-images.githubusercontent.com/11167153/37612090-92031d0e-2b7a-11e8-9181-c123cbcad647.png)
