### ISSUE TITLE
Clock Cult can't stop the blob

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#36493]
This is an oversight. 

1.Clock Cult is amazing and converts all/most/majority of the crew. 2.They get mass recalled to rebee. 3.random blob appears. 4.Clock cult can't go back to the station to stop the blob, 5.blob gets plenty of time to gain its win and self-destruct the station whilst the clock cult is in its grace period.

Ratvar you must stop this madness.

**Comment by Kromgar** [comment]
Blobs > Clocks gg

**Comment by Repukan** [comment]
Literal cuck cult

**Comment by praisenarsie** [comment]
oversight, blob should be disabled on clockwork rounds perhaps

**Comment by Tlaltecuhtli** [comment]
blob shouldnt also be able to spawn when shuttle eta is less than 5 (cant be recalled)

**Comment by Rinoka** [comment]
Blob also shouldn't be able to spawn when station z-level is mostly deserted; that should (ideally) keep issues like this from happening in the future.
