### ISSUE TITLE
integrated hypo injector cant  push its ref 

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#36503]
integrated hypo injector cant  push its ref

**Comment by arsserpentarium** [comment]
![image](https://user-images.githubusercontent.com/32496644/37573014-480945d0-2b24-11e8-9583-9ef222d6a725.png)
It can

**Comment by fludd12** [comment]
I can actually confirm that there are weird rare cases where the any reagent storage circuit that has a self-reference pin will occasionally break and only ever return null at times. No clue what the issue is, but it seems to be on a by-circuit basis, so reprinting the circuit usually fixes it.

**Comment by Shdorsh** [comment]
No longer needs to anyway due to the new selfref pins, courtesy of me.

**Comment by PKPenguin321** [comment]
In other words this is fixed

**Comment by SpaceManiac** [comment]
Circuits have been removed.
