### ISSUE TITLE
Plasmamen require more tolerance to oxygen

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/tgstation#36501]
Plasmamen are cool, and the potential for setting up an environment suitable for them is neat, but right now it is practically impossible to do in game. If even the tiniest amount of oxygen leaks through, even through an airlock system, the plasmamen die. 

I think their tolerance to oxygen before flaming should be far higher, in the realm of 10-20%. That way, they can feasibly create an environment for themselves without getting fucked, and there's no real in-game reason for that not to be the case. It's not going to suddenly make them unbalanced, just make a neat possibility actually possible.

**Comment by praisenarsie** [comment]
*t e c h n i c a l l y* an atmos issue

@duncathan

**Comment by ShizCalev** [comment]
Bring this up on the forum please.
