### ISSUE TITLE
Arcade machines don't show their emag_act message

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#36502]
Revision: aaafa1556528322501daf998f353177c1c5be2d0

Emagging arcade machines (computer/arcade/battle) doesn't show a feedback message anymore. Orion trail does.

**Comment by ExcessiveUseOfCobblestone** [comment]
does the emagging function work though?

**Comment by 81Denton** [comment]
Turns out the /battle arcade never had an emag message to begin with; only orion trail did
