### ISSUE TITLE
ocular wardens don't target buckled mobs

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#36510]
god damn secways making people immune to ocular wardens

**Comment by ExcessiveUseOfCobblestone** [comment]
THEY HAVE A RESTRAINED CHECK OMLLLLL

**Comment by Durkel** [comment]
Finally, a tactical use for roller chair+extinguisher.

**Comment by ChangelingRain** [comment]
@Xhuis

**Comment by Xhuis** [comment]
![](https://media.giphy.com/media/yJFeycRK2DB4c/giphy.gif)

**Comment by Davidj361** [comment]
>THEY HAVE A RESTRAINED CHECK OMLLLLL

Probably because you don't want people that are being converted to be shot to death.
