### ISSUE TITLE
There is no female corgi.

### ISSUE THREAD

**Issue by arsserpentarium** [tgstation/tgstation#36518]
There is no way to get Lisa corgi ingame.

**Comment by praisenarsie** [comment]
it's a 50% chance of getting one in corgi crates

**Comment by Jordie0608** [comment]
https://github.com/tgstation/tgstation/blob/3971c3a7e8d0873ea6a8c87da370bfadc1f27840/code/modules/cargo/packs.dm#L1479-L1484
