### ISSUE TITLE
AIs can access AI locked turret controls

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#36525]
Revision: 77bb4d70e1a7d39f347bf666d742b37c82efb436

As an AI, you can toggle AI locked turret controls by CTRL/ALT-clicking them.

**Comment by YakumoChen** [comment]
AI locked...?

**Comment by Anonmare** [comment]
You had to tell people about it, didn't ya?

**Comment by 81Denton** [comment]
![hqdefault](https://user-images.githubusercontent.com/32391752/37769949-11cd3a56-2dd3-11e8-845f-bf9233d4c805.jpg)
