### ISSUE TITLE
False walls don't obscure pipes under them

### ISSUE THREAD

**Issue by AlexTheSysop42** [tgstation/tgstation#36531]
Reproduction: make a false wall with pipes (cable may also work) under it, close the wall.

**Comment by praisenarsie** [comment]
layers are fun

**Comment by SpaceManiac** [comment]
Caused by #36371, probably hard to fix without reverting given the way underfloor hiding logic works

**Comment by Rinoka** [comment]
really, they ought to function more like doors tbh. door layer seems like it would skip all those issues
