### ISSUE TITLE
Experimental Cloner clones's names are ckeys, and they don't copy appearances IF it is not linked to a prototype scanner

### ISSUE THREAD

**Issue by Armhulen** [tgstation/tgstation#36542]
title

**Comment by Armhulen** [comment]
So basically it only works when linked to a prototype scanner, the scanners on station copy ckey and don't do appearances

**Comment by Armhulen** [comment]
Nabski - Tomorrow at 4:11 PM
@armhulen What was the difference that made it not do ckeys?
since I'm having that issue on terry now
armhulen - Tomorrow at 4:12 PM
prototype scanner
vs normal scanner
Nabski - Tomorrow at 4:12 PM
they used the prototype scanner
armhulen - Tomorrow at 4:12 PM
oh no
Nabski - Tomorrow at 4:12 PM
but reconstructed it
armhulen - Tomorrow at 4:12 PM
then i have no fucking clue
NEW MESSAGES
Nabski - Tomorrow at 4:12 PM
so there's a hint maybe?
that it works on the originally built one
but refreshing buffers and shit breaks it?
got what
how

**Comment by ExcessiveUseOfCobblestone** [comment]
what is ancient cloner

**Comment by XDTM** [comment]
I see, i didn't think to test the regular console with the excloner. I think i can fix this relatively quickly.
