### ISSUE TITLE
Inconsistent ventcrawl breath/pressure checks

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#36559]
Discovered locally, c8e21df82461b7c8230e6356285d147f3df01c03

Ventcrawling in an empty or near-empty pipenet causes suffocation, but ventcrawling in a toxins-filled pipenet does not cause toxin poisoning. It seems like ventcrawlers breathe from the turf above, except when the pipe is low-pressure, in which case they suffocate.

This is all itself inconsistent with taking pressure damage based on the pressure of the pipe rather than the turf above.

Tested on a human with `ventcrawling` varedited to `2`,

**Comment by AnturK** [comment]
Pipes are missing /remove_air override.
