### ISSUE TITLE
Something is making people fat without eating (Maybe moodlets?)

### ISSUE THREAD

**Issue by yorii** [tgstation/tgstation#36555]
[Round ID]: 85238

[Reproduction]: Many people have been reporting this in various different rounds, but I noticed it myself today when I was doing botany with a super happy mood, all of a sudden I just turned fat when I hadn't even eaten all round.

**Comment by kevinz000** [comment]
can confirm

**Comment by kevinz000** [comment]
i was afking in security

**Comment by fludd12** [comment]
As a podperson, hunger bar kept showing up fat, then disappearing, over and over. Theory is that it's related somehow to being happy reducing hunger loss.

**Comment by DaxDupont** [comment]
@Qustinnus you're turning people into blobs

**Comment by ExcessiveUseOfCobblestone** [comment]
trips

**Comment by XDTM** [comment]
Podperson is explainable as they feed off light.

**Comment by PKPenguin321** [comment]
this is really really funny. are we doing bug of the year this year

**Comment by Durkel** [comment]
I'm not fat because of a bug. I'm fat because of my genetics.
