### ISSUE TITLE
Wood floors removed via crowbar on boxstation (possibly other maps) go directly to space.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#36583]
round id 85280.

this happened in boxstation library, i tested it there again to reproduce. 

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 85280

Server revision compiled on: 2018-03-19

The following pull requests are currently test merged:
#36388: 'Shuttles have additional baseturfs, and other minor baseturf changes' by ninjanomnom at commit 6ab7b1

Based off origin/master commit: a91c7b

Revision: b3b661c990c8dfcec220679ba8f49cd4705d1234

Server tools version: /tg/station 13 Server v3.2.1.15

Server tools API version: 3.2.0.2

**Comment by ninjanomnom** [comment]
Already fixed in the testmerged pr responsible
