### ISSUE TITLE
The lava planet appears on other Zlevels and in transit

### ISSUE THREAD

**Issue by Qustinnus** [tgstation/tgstation#36588]
The lava planet acts dumb in transit and appear on other Zlevels, obviously because I'm dumb and I didn't prevent them from appearing on other Zlevels properly.

**Comment by cyclowns** [comment]
kind of makes sense for them to appear on other z-levels but not on centcomm or in transit

**Comment by Qustinnus** [comment]
the main issue is that it goes out of view, then comes back into view.

**Comment by Iamgoofball** [comment]
It's alright, shuttles just go really, really fast

**Comment by XDTM** [comment]
They're actually going into a circle really fast until they teleport
