### ISSUE TITLE
Dismemberment while inside a mecha (e.g. PDA explosion) results in bodyparts getting thrown out of said mecha

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#36599]
Issue reported from  Round ID: 85318 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

I was mining in APLU Firefighter when a traitor exploded my PDA, resulting in violent dismemberment. It threw both my arms and my right leg outside the exosuit.

**Comment by GunHog** [comment]
I think it is better than leaving them inside, where they could never be retrieved. The best middle ground would be to have them all fall out when the pilot is ejected.

**Comment by arsserpentarium** [comment]
Feature.

**Comment by Rinoka** [comment]
Emergent limb gameplay.

**Comment by PKPenguin321** [comment]
What @GunHog said, this should be closed

**Comment by Barhandar** [comment]
@GunHog 
>I think it is better than leaving them inside, where they could never be retrieved. The best middle ground would be to have them all fall out when the pilot is ejected.

I think the best outcome would be having an internal "control seat" storage that'd contain the limbs and could be popped out by destroying mech or an option in the UI (or pilot death, if the "hatch" isn't "locked" which could be an option too). But making them pop out only when the pilot themselves ejects, voluntarily or on death, is easiest to implement.

**Comment by ShizCalev** [comment]
in the same vain, the same issue happens with gibs. drop_location won't work for this as is iirc because it just prevents everything from spawning at all. (think it's something with the gib spawner's init)

**Comment by Fikou** [comment]
this isnt really an issue, its good for the game and nobody really cares
