### ISSUE TITLE
Object desync issue with circuit grabbers/throwers

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#36593]
1. Build a basic grabber/thrower circuit that actively seeks out things to grab and then throw
2. Be holding the thing it wants to grab
3. Pick up the circuit itself
4. It will pick up the object out of your hands and throw it on the floor, but the object will simultaneously still be in your hands

**Comment by XDTM** [comment]
Something isn't calling the unequip proc

**Comment by PKPenguin321** [comment]
Needs reproduction

**Comment by AverageJoe82** [comment]
cant reproduce with

>{"assembly":{"type":"type-f electronic machine","opened":1},"components":[{"type":"fast ticker","inputs":[[1,0,1]]},{"type":"half-sec delay circuit"},{"type":"one-sec delay circuit"},{"type":"half-sec delay circuit"},{"type":"advanced locator","inputs":[[1,0,"paper"],[2,0,1]]},{"type":"grabber","inputs":[[2,0,1]]},{"type":"thrower","inputs":[[1,0,0],[2,0,2]]},{"type":"thrower","inputs":[[1,0,0],[2,0,2]]}],"wires":[[[1,"A",1],[5,"A",1]],[[1,"A",1],[7,"A",1]],[[1,"A",1],[2,"A",1]],[[1,"A",1],[3,"A",1]],[[2,"A",2],[5,"A",1]],[[2,"A",2],[8,"A",1]],[[3,"A",2],[5,"A",1]],[[3,"A",2],[7,"A",1]],[[3,"A",2],[4,"A",1]],[[4,"A",2],[5,"A",1]],[[4,"A",2],[8,"A",1]],[[5,"O",1],[6,"I",1]],[[5,"A",2],[6,"A",1]],[[6,"O",1],[7,"I",3]],[[6,"O",1],[8,"I",3]]]}

**Comment by PKPenguin321** [comment]
can't reproduce
