### ISSUE TITLE
Winter theme from the anomalous crystal - Possibly unintended effects

### ISSUE THREAD

**Issue by nervere** [tgstation/tgstation#36602]
[Round ID]: #85326

[Testmerges]: No testmerges relevant to snow had been active during the round. 
#36388 was active but the turfs it modifies do not appear to affect temperature.

[Reproduction]: Spawn the object /obj/machinery/anomalous_crystal/theme_warp until you get the snow theme. It's one-use or has a cooldown or something, so consider spawning one per room until you get the snow theme to expedite the process.

[Issue]: The issue with the winter theme of the anomalous crystal is that it seems to have some unintended effects. It used to be that, upon spawning the theme, the area around the snow was a little bit cold and that was that. Now, presumably as a result of the update to the Snowdin ruin, snow tiles now constantly cool the air around it, making it a dangerous hazard. So hazardous, in fact, that the air becomes a temperature of around -90°C. This has turned a once-benign ruin into one that is dangerous and risky to use, compared to the other non-harmful themes that can result from using the theme-warp anomalous crystal.

**Comment by Sealed101** [comment]
seems to no longer be the case, no temperature changes were observed. seems to have been changed by #60516. judging by the remnant code comments, snow and lavaland themes were supposed to be affecting atmos. cool
![image](https://user-images.githubusercontent.com/75863639/222780845-787d46d1-6c02-49e8-8051-d81fb8e7052d.png)

https://github.com/tgstation/tgstation/blob/aff9cf1b434c7a95d156ea20108d8b2bc015083d/code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm#L432-L441
