### ISSUE TITLE
Death Syphon Disk Obtained from Lavaland Chests Doesn't Upload

### ISSUE THREAD

**Issue by Sven-Grey** [tgstation/tgstation#36603]
Issue reported from  Round ID: 85328 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])
The following pull requests are currently test merged:
#36388: 'Shuttles have additional baseturfs, and other minor baseturf changes' by ninjanomnom at commit f025fb
Reporting client version: 512

[Reproduction]: If you get the lavaland disk (Death Syphon) from one of the lavaland chests and upload it to the autolathe, the mod does not show up. The message for uploading will appear, and the progress bar will appear above your head and fill to completion. However, after uploading there will be no Death Syphon mod in the machine. I've checked both hacked and unhacked protolathes, but there is no mod either way.

I'm unsure if its only this one disk that doesn't work, or if all disks just stopped working.

**Comment by praisenarsie** [comment]
it's not an autolathe disk, it's for your proto-kinetic accelerator ya dumb dumb

**Comment by SpaceManiac** [comment]
The unique modkits require a protolathe or mech fab to construct. I think, but am not sure, that it would work on the supply techfab.

**Comment by Sven-Grey** [comment]
It was not a mod but a disk. (Similar to the golem disk found on the free golem shuttle). When I used it on the autolathe it gave the message that it was uploading. It did not eat the disk (as I was half expecting it to). Using it on protolathes did nothing, and using it on autolathes gave the message that it was uploading along with the progress bar.

**Comment by Sven-Grey** [comment]
Comparing it to the golem creation disk's code, the only difference that is missing from the death syphon disk is "category = list("Imported")". I'm not a coder, but it may be that it doesn't show up because it isn't assigned a category?

**Comment by newfren** [comment]
Did you try jamming it into the rnd console? I believe that's how I got it to work last time I found it. It lets you upload the design from the disk and then you can print it out.

**Comment by ChangelingRain** [comment]
modkit disks require the R&D console, since department protolathes didn't exist at the time they were added.

**Comment by AnturK** [comment]
Should probably be made to work with these.

**Comment by Tlaltecuhtli** [comment]
autolathes dont have a container for minerals required to build the mod

**Comment by Barhandar** [comment]
They require RnD console, they show upload message instead of error feedback when used on autolathe, though. Confused me first time I got one.
