### ISSUE TITLE
Disposal pipe launcher not working correctly

### ISSUE THREAD

**Issue by chesse20** [tgstation/tgstation#36618]
[Round ID]: # 85353

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: #
![image](https://user-images.githubusercontent.com/9161779/37753258-4040857a-2d59-11e8-96f4-2f77fe776aa1.png) Before launch

![image](https://user-images.githubusercontent.com/9161779/37753336-a88d8b6e-2d59-11e8-8ccf-4b27cc166aae.png)
After Launch
I made a pipe network like this, and everytime i would try to launch out of it, it would destroy the floor and rods underneath where i launch out of causing a breach

**Comment by RandomMarine** [comment]
Cannot reproduce.

**Comment by chesse20** [comment]
![image](https://user-images.githubusercontent.com/9161779/37806365-cb94edfc-2dfc-11e8-9fce-eb996444d434.png)
reproduced it on round 85390

**Comment by DaxDupont** [comment]
https://lithi.io/file/9nQ5.mp4

**Comment by YPOQ** [comment]
#36633 is testmerged in round 85390

**Comment by ninjanomnom** [comment]
Fixed in the testmerged pr this is introduced in.
