### ISSUE TITLE
Lots of explosions that should be destroying floors leave lattice+floor underneath

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#36611]
I think it's related to the shuttle turf change but it's making explosions not make a lot of space

**Comment by AnturK** [comment]
@ninjanomnom

**Comment by ninjanomnom** [comment]
Yeah because there isn't space directly below tiled turfs anymore, the lattice being left there is a bug but idk if it should be considered one otherwise.

**Comment by RandomMarine** [comment]
Heavy explosions are supposed to leave some tiles as space with a lattice.
Obviously it's not supposed to leave any floors/plating with lattice.

**Comment by YakumoChen** [comment]
>blow up a station in space
>expect space to be underneath the flooring
>there's only more flooring underneath the floors
>floorcepction

**Comment by YakumoChen** [comment]
http://prntscr.com/iv6el1 an SM exposion isn't supposed to look like this yeah, it's supposed to look like a giant gaping hole.

**Comment by ninjanomnom** [comment]
This bug was exposed by code in the testmerged pr and has now been fixed in the same pr
