### ISSUE TITLE
Mannitol does not cure brain traumas

### ISSUE THREAD

**Issue by Polyphynx** [tgstation/tgstation#36633]
#36301 Still an issue

**Comment by Davidj361** [comment]
Give a detailed reproduction and I'll check it out.

**Comment by Polyphynx** [comment]
Take about 10u of fentanyl or so to give yourself several minor traumas. Take as much mannitol as you want. Your brain damage will go down but you'll keep the traumas.
At least, after trying with several hundred units of mannitol I wasn't cured.

**Comment by Davidj361** [comment]
And this was where you already metabolized the fentanyl that you gave yourself the mannitol?

**Comment by Polyphynx** [comment]
That's right
