### ISSUE TITLE
Reference decoder circuit seems to always return null

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#36646]
Now this one REALLY has me perplexed since it was working like 3 hours ago but isn't now.

Fastest way to test:
- Make a circuit with a ref encoder and decoder in it.
- Wire the encoder output to the decoder input.
- Manually scan a ref with the debugger tool and insert it into the encoder
- Manually pulse the encode pulse in
- Manually pulse the decoder pulse in
- Notice that the decoder has returned null instead of properly returning the ref

Further testing for proof:
- Manually enter a ref to the decoder output
- Repeat the above steps
- Notice that the decoder output actually changes to null, meaning it's being set to null, rather than being left unchanged

**Comment by arsserpentarium** [comment]
it's known bug with ref encrypt.
It is fixed in #36398.
BTW, it's not always null.

**Comment by PKPenguin321** [comment]
Super weird. Is it known why it only happens sometimes?

**Comment by arsserpentarium** [comment]
Yes, it is. It's cryptography bug. When key and ref have same char on position, it gives char(0). It can't be added properly to string. So it glitches.

**Comment by arsserpentarium** [comment]
fixed.close it

**Comment by PKPenguin321** [comment]
Gotcha
