### ISSUE TITLE
Pipenets sometimes mess up initializing, resulting in unattackable/inoperable pipes.

### ISSUE THREAD

**Issue by EmptyLullaby** [tgstation/tgstation#36642]
![image](https://user-images.githubusercontent.com/20155238/37804352-dc13e0f2-2e01-11e8-9e3e-b1b0fc31b28a.png)
like all this shit cannot be analyzed or broken or unwrenched and air doesnt flow through them
id 85385
https://github.com/tgstation/tgstation/pull/36608 testmerged

**Comment by Spaceinaba** [comment]
NOTE: pipes before the pumps are fine its everything else in the main loop that's fucked

**Comment by AnturK** [comment]
I seen something similar with syndicate lavaland base where `/supplymain` pipe subtype failed to set their pipenets properly. I didn't investigate further though.

**Comment by nicbn** [comment]
It happens to me often. When this happens, opening an air outlet can fix the problem. If it doesn't, deleting the pipe can solve it.
