### ISSUE TITLE
AFTER INPUTTING A MESSAGE IT DEFAULTS TO OOC

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#36649]
![image](https://user-images.githubusercontent.com/20155238/37813825-07177434-2e35-11e8-94f5-f00bf5055cca.png)
REALLY FUCKING ANNOYING PLEASE FIX IT

**Comment by GunHog** [comment]
Click the "Chat" button on the bottom right side of your chat bar. It only defaults to OOC if you clicked the "OOC" button, which you may have done by accident.

**Comment by Spaceinaba** [comment]
OH FUCK OK NEVERMIND THEN THANKS GUNHOG
