### ISSUE TITLE
You can staff of animate blob chunks

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#36654]
Blob chunks (nodes, factories, maybe even the core?) will animate when hit by a bolt of animation. Ends with some weird shit like a node running off and it eventually 'dying', dropping the node in that location.

**Comment by PKPenguin321** [comment]
Despite being weird, I don't think this is actually a bug.

**Comment by AnturK** [comment]
What's the issue here because i don't see it ?

**Comment by MimicFaux** [comment]
Breaking News: Magical relics cause strange happenings.

**Comment by MMMiracles** [comment]
The blob itself is a living thing and having parts of 'animate' is probably an oversight due to the fact they're technically structures.

**Comment by PKPenguin321** [comment]
Well if we're arguing realism about giant blobs and magic staffs, I'd say that the staff of animation grants sentience, and that an individual part of a blob is not sentient already (it's controlled by a singular sentient overmind).

**Comment by MMMiracles** [comment]
Well that's fine and dandy until you start shooting the important stuff like the nodes, factories, and even the core itself.

**Comment by XDTM** [comment]
that sounds awesome tbh

Mr. Blob is tired of the siege, he's coming to beat you up

**Comment by ShizCalev** [comment]
hmm....

**Comment by ShizCalev** [comment]
Gonna consider this an oversight/bug since they are technically supposed to be living parts of the blob, unless any other maintainers have differing opinions on that. @tgstation/commit-access

**Comment by KorPhaeron** [comment]
Seems like a bug to me
