### ISSUE TITLE
It is super easy to shut down all monkey cubes

### ISSUE THREAD

**Issue by CPTANT** [tgstation/tgstation#36656]
1. Get 20 monkey cubes.
2. Dump them somewhere nobody will ever come and activate them.
3. Nobody can now use monkey cubes for the rest of the round.

They don't even need to be alive.

**Comment by ma44** [comment]
This is probably more of an oversight (despite it being originally noticed in the pr) and probably not a bug but a balance thing. 

The #36641 would probably fix this issue.

**Comment by GunHog** [comment]
The hard monkey limit was a mistake. It would have been better, in my opinion, to have removed the ability to create many monkeys using a water spray. If players had to apply water to each individual cube via injection or the slime console, the Monkey-geddon could not have happened.

**Comment by ExcessiveUseOfCobblestone** [comment]
36641 doesn't touch the monkey cap?

**Comment by CPTANT** [comment]
It fixes the "need" (it is still a dumb solution in the first place) for the cap existing.

**Comment by Tlaltecuhtli** [comment]
i cant even do xenobio because of this shit

**Comment by Barhandar** [comment]
Can slimes eat dead monkeys?

If yes, just make the extra ones dead on arrival.

**Comment by TheDreamweaver** [comment]
@Barhandar No. They essentially absorb the life out of living creatures for nutrition do a dead monkey provides no nutrition.

**Comment by Barhandar** [comment]
@TheDreamweaver Then GG.

Can the monkey limit be at least per-area + only applied to living monkeys? So at least xenobio and genetics can do their job.

**Comment by Rinoka** [comment]
To be fair, you could just bake it into the xenobio camera to allow it to ignore monkey caps? And have it skim the xenobio area (that it already has stored so that it knows its bounds) and limit the monkies there based on that.

**Comment by TheDreamweaver** [comment]
B-but ... my monkey bombs...

**Comment by CPTANT** [comment]
Not fixed, cap is still too low.
