### ISSUE TITLE
[OMEGA] Can't reach the safe in the detective's office

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#36660]
![2018-03-23_13-13-26](https://user-images.githubusercontent.com/20155238/37846593-0fc5e98c-2e9c-11e8-9fec-37b7cc7d7aed.png)

**Comment by ShizCalev** [comment]
reeeeee

**Comment by 81Denton** [comment]
Can't crack it if nobody can even reach it 🤔

**Comment by Shadowflame909** [comment]
Feature. You gotta climb the tables. THIS IS WHERE YOU HIDE THE NUKE DISK INABA.

**Comment by francinum** [comment]
@Shadowflame909 it's blocked by the camera TV, you can't get to it without deconstructing a console or an rwall
