### ISSUE TITLE
Pacifism trups zombie

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#36669]
Issue reported from  Round ID: 85440 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Zombies retain the pacifism thy had in life
You don't feel like harming anybody.x50000

**Comment by Rinoka** [comment]
@Xhuis 

trait problem alarm weeoo

**Comment by Xhuis** [comment]
lmao, nice

**Comment by Rinoka** [comment]
might be easiest to make some traits drop once the mind is lost

or just dump them all on zombification, though that might make revivals weird
