### ISSUE TITLE
pAIs inside the dance radius of the disco machine occasionally spam chat with rest notifications as the dance4() proc is called

### ISSUE THREAD

**Issue by EvilJackCarver** [tgstation/tgstation#36688]
![](https://i.imgur.com/Ohepsnd.png)

pAI units that are within range of the disco machine will occasionally spam the chat with resting notifications as the machine makes them "dance" by resting repeatedly. 

See [/game/machinery/dance_machine.dm:402~411](https://github.com/tgstation/tgstation/blob/master/code/game/machinery/dance_machine.dm#L402-L411) for the dance code (the proc is `dance4()`), and [/code/modules/mob/living/silicon/pai/pai_shell.dm:83~93](https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/silicon/pai/pai_shell.dm#L83-L93) for how it affects pAIs.

Noticed on /tg/bagil round 85471.

I'll work on a band-aid fix in the meantime.

**Comment by DaxDupont** [comment]
@Robustin

**Comment by EvilJackCarver** [comment]
Forgot to close, this is patched by #36689
