### ISSUE TITLE
this is the most dumb shit i heard incode

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#36685]
Bluespace harmonics prevent the spawning of more than 20 monkeys on the station at one time!

**Comment by YakumoChen** [comment]
yeah because I sure to love seeing the non-antag botanists fill the hallways with griffmonkeys every single round

**Comment by praisenarsie** [comment]
there's a limit though that limit looks extremely low to me

**Comment by Jordie0608** [comment]
Duplicate of #36656
