### ISSUE TITLE
Oingo Boingo Mech Punch can move anchored nukes.

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#36681]
and..... out the airlock it goes.

**Comment by SpaceManiac** [comment]
F E A T U R E

**Comment by Tlaltecuhtli** [comment]
i ded

**Comment by praisenarsie** [comment]
you can only equip that on honk mechs right?

**Comment by francinum** [comment]
Yes

**Comment by DaxDupont** [comment]
Might want to check meteor slugs too if you're fixing this just in case.

**Comment by Ordonis** [comment]
Absolutely a feature. The Honkmother shall not be denied.

**Comment by PKPenguin321** [comment]
Isn't the whole point of the oingo boingo that it can move normally immovable stuff
Which would mean that this is a feature unironically
