### ISSUE TITLE
Chemical Dispenser power regenerates GLACIALLY slowly

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#36687]
Issue reported from  Round ID: 85472 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

I have no idea how it actually regenerates, but it's too slow even before considering that t4 cell gives it 8000 points.

**Comment by vuonojenmustaturska** [comment]
I'll take a look, it was pretty glacial before but it's possible that i halved it...

**Comment by Barhandar** [comment]
I think that if there's going to be upgradable amount of energy, it needs to scale to cell tier (or cell's transfer rate) how fast it regens, so better cells are actually a benefit and not just a buffer to allow chemists to dawdle for longer; or at least make it so disassembling the damn thing and sticking cell in the charger isn't _less_ hassle than waiting.

**Comment by ExcessiveUseOfCobblestone** [comment]
capacitors should handle that

**Comment by SpaceManiac** [comment]
One unit of chem every 120 seconds by default, every 30 second with tier-4 capacitors.

**Comment by praisenarsie** [comment]
@coiax i'm still waiting on those chem cartridges

**Comment by ExcessiveUseOfCobblestone** [comment]
n a n i?

**Comment by vuonojenmustaturska** [comment]
the recharge function is a bit iffy, i got distracted but i'll fix it proper in a minute

**Comment by Rinoka** [comment]
...one unit of chem every 122 seconds

horror gif here

yeah please fix this before it kills me

**Comment by coiax** [comment]
@praisenarsie yeah, that's a nice uncontroversial pr to open after a long absence
