### ISSUE TITLE
Light made by light circuits will not follow the circuit assembly they are in if it moves via a locomotion circuit

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#36706]
- Use integrated circuits to build a basic drone that can move via a locomotion circuit
- Insert a light circuit and toggle it to on
- Have the drone move on its own
- Notice how the light does not follow the drone

Curiously, if you turn the light off, pick up the drone, turn it on while it is still in your hand, and walk around, the light will follow you. If you drop the drone on the floor and have it move on its own, the light will not follow it.

**Comment by arsserpentarium** [comment]
I know about that problem. And I don't know, how to fix it?
