### ISSUE TITLE
If a monkey attacks you with a supermatter sword you dont disintegrate

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#36707]
>Dinner has attacked Lauser McMauligan in the chest with the supermatter sword!

I did not disintegrate from the above

Probably applies to most melee weapons that have unique actions on-hit

**Comment by AlexTheSysop42** [comment]
>attacked

SM sword needs better attack verbs

**Comment by arsserpentarium** [comment]
Also there is no crafting recipe for supermatter sword.

**Comment by Shadowflame909** [comment]
The crafting recipe is a super matter shard (which means a traitor loses his green text.) A katana, and one magic book.

**Comment by AlexTheSysop42** [comment]
actually, you can get multiple shards from one crystal

**Comment by PKPenguin321** [comment]
I vaguely recall a similar issue with monkeys being fixed in the past, maybe it fixed this too?

Needs repro
