### ISSUE TITLE
Unsynced borg from staff of change gets AI laws

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#36718]
No AI selected to sync laws with, disabling lawsync protocol.

Obey these laws:

#%$$: THE STATION REQUIRES SUFFERING

Remember, you are not bound to any AI, you are not required to listen to them.

This was an ion law. However the staff of change is making borgs unsynced, it isn't doing it properly.

**Comment by AlexTheSysop42** [comment]
It can get someone exposed for uploading hacked laws too, kinda cheesy
