### ISSUE TITLE
Reagent containers sometimes get 'stuck' inside a dispenser when taken out, stops further usage.

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#36719]
I managed to take a reagent container out of a dispenser (bar tap in this instance), but the visual for having a beaker loaded on it was there and trying to add the same container or other containers gave the message that an item was still loaded in the machine. Opening the dispenser UI showed that nothing was loaded into the machine and there was no option to eject the container that was apparently loaded.

I'm assuming this stems from the issue of 'one item in two places', as the time dilatation on the server at the time was a bit higher than usual.

**Comment by Jalleo** [comment]
We need someone to debug it next time it occurs to confirm that is the case.
