### ISSUE TITLE
incinerator room air alarm not detecting incinerator vent on meta station

### ISSUE THREAD

**Issue by AverageJoe82** [tgstation/tgstation#36725]
[Round ID]: 85539

Server revision compiled on:  2018-03-24 

[Testmerges]: #36388: 'Shuttles have additional baseturfs, and other minor baseturf changes' by ninjanomnom at commit c64756 

[Reproduction]: Go check the air alarm for the incinerator room on metastation roundstart.

As the title says you cannot find the vent on the air alarm for metastation, this started yesterday and also I play on Basil.

**Comment by ShizCalev** [comment]
map?

**Comment by AverageJoe82** [comment]
fixed issue report
