### ISSUE TITLE
If you have a paperbin in your bag, removing a paper from it causes the bin to be put on the floor

### ISSUE THREAD

**Issue by Qbopper** [tgstation/tgstation#36724]
Issue reported from  Round ID: 85542 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

#36608 is testmerged

if you pick up a paper bin using dragging and put it in a bag, removing a piece of paper/the pen inside causes the paper bin to fall out of the bag onto the floor. Previously the bin would stay in the bag, like it should

**Comment by SpaceManiac** [comment]
Reproduced, probably caused by #36405. The bin is taken out of storage on to the ground, then fails to be picked back up because the user now has a piece of paper in their active hand.

**Comment by optimumtact** [comment]
@kevinz000
