### ISSUE TITLE
AIs cannot interact with windoors.

### ISSUE THREAD

**Issue by Bluespace** [tgstation/tgstation#36730]
[Round ID]: 85558

[Testmerges]: https://github.com/tgstation/tgstation/pull/36388

[Reproduction]: Be me, AI.
Click windoor.
Naaaahthing haaaappen.
Not even a little red blinky light.

**Comment by Bluespace** [comment]
[Round ID]: 85558

[Testmerges]: https://github.com/tgstation/tgstation/pull/36388
I dunno why it didn't post this bit, I was trying to be a good boye.

**Comment by Bluespace** [comment]
[Round ID]: 85558

[Testmerges]: #36388

**Comment by Bluespace** [comment]
round was 85558

**Comment by Bluespace** [comment]
36388 was number of PR that was testmerged

**Comment by Bluespace** [comment]
it kept stripping out that info for some reason

**Comment by ShizCalev** [comment]
#36388

**Comment by DaxDupont** [comment]
@kevinz000

**Comment by Tlaltecuhtli** [comment]
i bet its windoors not having ntnet

**Comment by PKPenguin321** [comment]
Windoors need ntnet

**Comment by Anonmare** [comment]
Conveyor switches are also not interactable despite having been so.

**Comment by ShizCalev** [comment]
Closing in favor of #37103 which has a ton more stuff listed
