### ISSUE TITLE
Gluttony ruin can not be accessed because  you can no longer become fat(Moodlet related?)

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#36735]
I tried eating as much food as possible nonstop consuming cooked beef like 16 plates of the fucking stuff along with 4 donk pockets. But i could not enter the gluttony walls because i was not pig enough.

I would eat the plates as soon as i could as i kept being unable to stuff anymore down my motuh

**Comment by fludd12** [comment]
Actually, that's my fault, sorry! Fixing that now.
