### ISSUE TITLE
Broken APCs cannot be deconstructed

### ISSUE THREAD

**Issue by Electronics** [tgstation/tgstation#36740]
If an APC is broken to the point you can examine it and get: `It looks broken and non-functional. It's falling apart! ` (aka it's cover has been removed and it's broken), it cannot be deconstructed via normal means or by applying brute force.

Reproduced today and a few months ago.

```Round ID:  85598 
Server revision compiled on:  2018-03-24 
The following pull requests are currently test merged: 
#36388: 'Shuttles have additional baseturfs, and other minor baseturf changes' by ninjanomnom at commit c64756 
Based off origin/master commit: 385b62 
Revision: 78bfbbdd093d009ad2e76ee917a9c39f0e945f3c 
Server tools version: /tg/station 13 Server v3.2.1.15 
Server tools API version: 3.2.0.2 ```

**Comment by Davidj361** [comment]
Can you add a list of reproduction steps for someone like me who is shit at the game? So I can test this on my local server.

**Comment by Electronics** [comment]
Not exactly sure as both times I've just found it already fucked, but explode something in-front of the APC to the point it's broken and non-functional with the cover blown off and I think it should examine the same symptoms.

**Comment by Anonmare** [comment]
For some reason, it's not possible to destroy an APC via brute force if it has its power cell for some reason.

Are you positive you followed the deconstruction steps? I deconstructed an APC yesterday with no issues. With a broken APC they should be done like this:
1. Smash the cover off with something heavy, such as a toolbox or fire extinguisher
2. Remove te power cell with an empty hand
3. Screwdriver the frame
4. Expose the power terminal by crowbarring any tile in front of the APC out of the way if there is one
5. Wirecutter the frame
6. Crowbar the frame
7. Weld the frame

**Comment by Davidj361** [comment]
^ Worked for me

**Comment by Poojawa** [comment]
That's literally how it's always been, the only part about brute force is smashing the cover off. I tend to use my hardsuit O2 tank since it's on hand.

**Comment by Electronics** [comment]
Hm, I can't reproduce, but I'm pretty sure I had it at the point the cover was removed and couldn't remove the power cell with a hand.
