### ISSUE TITLE
Guardian ranged+scout can't remove snares

### ISSUE THREAD

**Issue by Davidj361** [tgstation/tgstation#36746]
[Round ID]: A couple rounds before 84865

#36368 is still partially broken:
Ranged+Scout guardian cannot remove his scouting alert snares.
1. Make the snares
2. Try to click remove under Guardian tab even when standing over the snares
3. Snares don't get removed and there's no popup as there should be from input(...)

This line of code isn't showing a popup as it should:
https://github.com/tgstation/tgstation/blob/97522b6aca5b76f766738269b017ca1cb5c5bab4/code/modules/mob/living/simple_animal/guardian/types/ranged.dm#L99

It works with a regular list of strings, the list of `src.snares` is NOT empty, and the proc that it's nested in does run. I'm guessing the list of /obj/effect/snare objects aren't being converted to strings by their `name` variable as they should be.

**Comment by Sealed101** [comment]
this input list was changed in #63354 and now works properly
