### ISSUE TITLE
Bodies gibbed at the ash walker tendril no longer produce gibs, meaning that gubbucks and guthens don't produce milk for ash walkers.

### ISSUE THREAD

**Issue by nervere** [tgstation/tgstation#36755]
[Round ID]: 85642

[Testmerges]: #36608 was testmerged but it's most likely not related at all.

[Reproduction]: 

Make an ashwalker tendril (/mob/living/simple_animal/hostile/spawner/lavaland/ash_walker) surrounded by lava (/turf/open/lava/smooth). Place a stone block (/obj/structure/stone_tile/block) on top of these lava tiles so you won't die when you step on them. Put a dead body near the tendril so that the tendril eats the body and gibs it. No gibs appear to come from the body when the body is placed within a one-tile radius (on top of a lava tile) of the tendril. This was never the case before.

This is how I replicated it in a thunderdome environment and I yielded the same results of no gibs being produced. Goliath hides also don't come from the tendril when goliath corpses are gibbed, according to a player, but I don't know if this was the case in the first place. 

I tested for whether or not the stone block was a part of the reason for gibs not being produced from the bodies, and found that it was not, as in a replicated environment without the lava tiles, gibs were produced. The issue here is most likely that lava tiles are deleting gibs before they can spawn on the tiles around them, as gibs work by starting at the center from where they originated (the body gibbed) and flying outwards.

**Comment by Shadowflame909** [comment]
Yeah, i was wondering why I no longer get milk. FIX THIS!!

**Comment by Barhandar** [comment]
It was fixed by #40914, should be closed
