### ISSUE TITLE
Pin removal fails to work.

### ISSUE THREAD

**Issue by Zaffinomlb** [tgstation/tgstation#36757]
Issue reported from  Round ID: 85644 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Attempting to remove the firing pin in a C-20r SMG, option available, failed, and was given "Construction failed, missing tool." Attempted to remove pin of an egun, same results.

[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by Davidj361** [comment]
How do you remove pins?

**Comment by Zaffinomlb** [comment]
Table crafting. Please required tools and firearm on table, craft pin removal. Pin should remove.

**Comment by newfren** [comment]
I believe you also need a plasma cutter for it to work.

**Comment by PKPenguin321** [comment]
Pin removal using tablecrafting is honestly pants on head retarded

**Comment by AlexTheSysop42** [comment]
use the crafting menu, also you need the tools in your toolbelt/backpack

**Comment by DaxDupont** [comment]
@newfren wrong https://github.com/tgstation/tgstation/blob/aac80eb18bc57fd585790277af68a95fdc24960f/code/modules/crafting/recipes.dm#L19

**Comment by AlexTheSysop42** [comment]
You can use a plasma cutter though, it counts as a welder

**Comment by Davidj361** [comment]
It's still broken, it should check your surroundings for tools too. Not just in your storage.
