### ISSUE TITLE
AI End Round Objectives Not Shown

### ISSUE THREAD

**Issue by Davidj361** [tgstation/tgstation#36764]
[Round ID]: 1 round before 85653

Whenever a round ends, it just shows AI's "Complete your goals" objective as a law. It does not show what objectives the AI had, unless someone can correct me on this.

**Comment by ShizCalev** [comment]
@AnturK

**Comment by Barhandar** [comment]
I think it shows AIs in the traitor section instead of AI's own.

**Comment by AnturK** [comment]
Seems to be working fine ?

**Comment by factoryman942** [comment]
yeah ai is just in the traitor section
