### ISSUE TITLE
Metastation Bad AI Mounted Flash Placement

### ISSUE THREAD

**Issue by Davidj361** [tgstation/tgstation#36760]
Metastation has a bad mounted flash placement that doesn't reach players if they are in this spot, where they can keep attacking the AI while the AI is unable to defend itself. The mounted flash needs to be moved to the center. This is an ultra safe spot for players to harm and change the AI.

![https://i.imgur.com/4XxQ2to.png](https://i.imgur.com/4XxQ2to.png)

**Comment by CPTANT** [comment]
I don't understand what you mean by moved to the centre, because the centre is taken up by the AI itself. You could of course place a second flash of course.

**Comment by Davidj361** [comment]
That could work, or even on the center window. Not sure what that window is for when there's a camera.

**Comment by 81Denton** [comment]
Just tested this on localhost, everyone inside gets flashed properly.
Maybe you were wearing sunglasses?

![asdfaqafegwgwg](https://user-images.githubusercontent.com/32391752/38185306-d57a5394-364d-11e8-8a8c-6668a2b4c675.jpg)

**Comment by Davidj361** [comment]
Yeah works for me too now, closing this.
