### ISSUE TITLE
Subcircuits Feature Request

### ISSUE THREAD

**Issue by robbym** [tgstation/tgstation#36768]
It would be cool to have the ability to create subcircuit assemblies that you can insert into other assemblies. That way we can pack a bunch of useful, modular behaviors into a subcircuit and use it everywhere instead of manually wiring up the same circuit every time.

**Comment by Shadowflame909** [comment]
Dude this is issues.. As in bugs. Not requests! Go on the forum for ideas.

**Comment by PKPenguin321** [comment]
Not an issue but I agree

**Comment by robbym** [comment]
Moved to forum
https://tgstation13.org/phpBB/viewtopic.php?f=9&t=16480
