### ISSUE TITLE
If moodlets are disabled several traits are "free"

### ISSUE THREAD

**Issue by imtakingabreakdontatme** [tgstation/tgstation#36779]
They probably should not be available if the mechanics they are work with are not enabled

**Comment by Shadowflame909** [comment]
I say moodlets should be a trait in of itself, replacing the traits that need moodlets. I guess you could say it gives people the option to torture themselves. With an "OCD" like trait.

**Comment by chesse20** [comment]
how is this a bug just keep moodlets in the game

**Comment by praisenarsie** [comment]
not everyone likes moodlets or traits y'know

**Comment by PKPenguin321** [comment]
not everyone likes dying to traitors either
"oh no my screen is fuzzy because i didnt take 3 seconds to snag something from the kitchen"
boo hoooo

**Comment by Shadowflame909** [comment]
What even is the purpose of moodlets. Is it trying to get us to make more cleanbots?

**Comment by factoryman942** [comment]
no, it's trying to make sims but we play as the sims

**Comment by SpaceManiac** [comment]
This was fixed by #37082
