### ISSUE TITLE
If Moodlets are disabled via config there are no penalties to being hungry.

### ISSUE THREAD

**Issue by GuyonBroadway** [tgstation/tgstation#36774]
[Round ID]: N/A

[Testmerges]: None

[Reproduction]: Fire up a local server, disable moodlets via config and get hungry. (Or play on hippie and do *superfart)

We hippies could add in our own system but it seems like if someone made a pure tg server with moodlets off it would defeat the point of the chef.

**Comment by Qustinnus** [comment]
Not necesarily a bug, I don't mind creating a replacement system, however. (Or just re-adding the previous system, if moods are disabled)

**Comment by Cyberboss** [comment]
Is a bug
