### ISSUE TITLE
clock cultists ghosts cant leave reebe

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#36789]
Issue reported from  Round ID: 85688 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])
i was a clock cultist
as ghost i kept being teled back to the ark if i try to teleport to station

**Comment by AlexTheSysop42** [comment]
it's because it does that to living cultists too to prevent spatial gateways letting them go to the station
