### ISSUE TITLE
Monkeys Can Tackle You Even While Dead

### ISSUE THREAD

**Issue by Sven-Grey** [tgstation/tgstation#36793]
Issue reported from  Round ID: 85692 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Server revision compiled on: 2018-03-28

The following pull requests are currently test merged:
#36388: 'Shuttles have additional baseturfs, and other minor baseturf changes' by ninjanomnom at commit c0ccd4

Based off origin/master commit: 78bfbb
Revision: 5191d4dee078c60576a81d6ded32f05ae479a923
Server tools version: /tg/station 13 Server v3.2.1.15
Server tools API version: 3.2.0.2

[Reproduction]: 
1. Kill a monkey
2. Try to grab it
3. It will always tackle you even while dead

**Comment by Kromgar** [comment]
KEK

**Comment by Therapist1** [comment]
FROM BYOND THE GRAVE

**Comment by ShizCalev** [comment]
@robustin

**Comment by imsxz** [comment]
i have experienced this and seen this experienced across many different rounds, there is nothing more humiliating than getting robusted by a dead cuffed monkey.

**Comment by Robustin** [comment]
@imsxz is this something new?
