### ISSUE TITLE
advanced pathfinder circuit does not give output

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#36798]
- Input X and Y coordinates
- Pulse the calculate path pin
- No output

**Comment by arsserpentarium** [comment]
Put in on ground. It doesn't works in hands.

**Comment by PKPenguin321** [comment]
It was in a drone that was on the ground

**Comment by PKPenguin321** [comment]
Also why is the output in lists of X and Y coords? X and Y coords I'd understand but I don't see why lists are needed. Just curious

**Comment by arsserpentarium** [comment]
1. Also it needs access string from card.
2. Because it is planning path from start to end before motion. So lists contains coordinates of all tiles from start to goal.

**Comment by arsserpentarium** [comment]
Anyway, looks like I made shitty description.

**Comment by robbym** [comment]
I am utilizing the `advanced pathfinder` just fine in conjunction with the `coordinate pathfinder`.
I simply have the `adv pathfinder` generate a list, use 2 `at circuit` and an `addition circuit` as index, feeding coords to the `coordinate pathfinder`, and finally the `locomotion circuit`.

**Comment by PKPenguin321** [comment]
Forgot to close this, yeah it works fine just weird that it requires a passkey
