### ISSUE TITLE
Sillicons can send the centcom ferry away 

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#36799]
Issue reported from  Round ID: 85679 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Also silicons can manipulate the centcom ferry, by using the console.

the silicon thing might be due to @kevinz000's attack hand refactor.

**Comment by Durkel** [comment]
I really hate having to babysit the ferry.

**Comment by PKPenguin321** [comment]
i just delete the ferry console and move it with the secrets panel

**Comment by DaxDupont** [comment]
@PKPenguin321 yeah, but we fixed the emagging and now this thing happens.
