### ISSUE TITLE
Adding cat tails to someone through surgery doesn't visually give them a cat tail

### ISSUE THREAD

**Issue by Polyphynx** [tgstation/tgstation#36802]
Round ID: 85700 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

As the title says. It does work with lizard tails and cat ears.
This is obviously very important.

**Comment by praisenarsie** [comment]
not a bug

**Comment by GuyonBroadway** [comment]
I like to think you cram it in their torso like a second intestine.
