### ISSUE TITLE
stabilized light pink extract giving epinephrine to multiple people

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#36812]
i had a stabilized light pink extract, got into crit with a few other people on the same tile, gave all of them the buff as well...

**Comment by imsxz** [comment]
@fludd12

**Comment by fludd12** [comment]
This is the intended purpose of stabilized light pink. You get the speed boost, but not the stabilization, while people around you are stabilized.

Basically, you become an ambulance. Weewoo.

**Comment by imsxz** [comment]
oh im a dummy, i'll close this then
