### ISSUE TITLE
NPC monkeys arent affected by blood loss

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#36810]
i was draining monkeys as a vampire, they were still standing up perfectly (and tacking me), while the drain ability said their blood supply was gone. med scanner also showed them at 0% blood, they were fine physically though. dont know if this is specific to NPC monkeys, or if its specific to vampires draining, or if its unrelated to either.

**Comment by Robustin** [comment]
I had nothing to do with this one but its an easyish fix
