### ISSUE TITLE
revenant can't siphon

### ISSUE THREAD

**Issue by cambys** [tgstation/tgstation#36820]
[Round ID]: # 85752

During this round I spawned as a revenant, I tried siphoning from a winged corpse in genetics, with the name of Jay Clarke, it said something about it being protected against siphoning, after that I couldn't siphon from any corpses or others, it said I was already siphoning, there was another revenant who also said they couldn't siphon that round

**Comment by Nabski89** [comment]
This messed up at least four revenants, all of whom had siphoned off the winged human.

**Comment by Repukan** [comment]
Is there any special interactions between the angel species and revenants?

**Comment by Shadowflame909** [comment]
I've seen this before. You siphon a special corpse that already got succ'd. It says its protected, then you get glitched because it thinks you're still trying to suck that corpse. I think the "protection" was supposed to ward you off from siphoning it. But it didn't work.

**Comment by Barhandar** [comment]
@Shadowflame909 you're wrong about why it's happening.
@Repukan yeah, angels are SPECIES_HOLY, just like silver golems, so logically revenants shouldn't be able to suck them. Failing to clear the siphoning and therefore making revenants _permanently_ unable to siphon ever again is a bit harsh though.

**Comment by YPOQ** [comment]
Will fix.
