### ISSUE TITLE
Filling plasma tanks does not increase rad collector output

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#36825]
Revision: c43c84f5f5826ddc35faa3933d28c8eb9c7fb5ec

Rad collectors always produce the same amount of power, as long as there is at least a tiny bit of plasma inside the tank.
There is absolutely no reason to fill plasma tanks right now - with how slowly they drain, you can just put in the roundstart ones and they'll last for hours.

This is probably related to: #36067

**Comment by Electronics** [comment]
It was previously discussed to be re-added in #32279 (rejected) and was removed originally in #30909 radiation rework intentionally.

**Comment by Jalleo** [comment]
@Dorsisdwarf not a bug and it is done so for balance.

**Comment by 81Denton** [comment]
Oh man, those PR comments are an absolute shitshow.
I disagree with the balance decision, but alas it's not a bug.
