### ISSUE TITLE
Paradox bags cant be opened at all

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#36823]
The alien brain was removed, but we have another problem for shaft miners.
1.Get the paradox bag via lava land robustness. 
2.put an item inside
3. Try to open the other bag, it doesn't open. Try to open the first bag, it doesn't open either. "wtf I just lost my ka." True story. Ree my paradox bag ate my KA.

**Comment by SpaceManiac** [comment]
@kevinz000

**Comment by AlexTheSysop42** [comment]
You can still open it when it's on your back for some reason

**Comment by Shadowflame909** [comment]
It was a hard round running back to the station without any mining weapons/source of light (I bayoneted) to fight with. I think I died.
