### ISSUE TITLE
Crew Monitor is extremely shitty and causes crashes

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#36821]
I can't use the crew monitor at all, every time I do it it is so laggy it crashes my client. It happens every time, I can't even close it before the crash. 

I'm on the latest BYOND or whatever, but it's TGUI is really god-awful.

**Comment by praisenarsie** [comment]
@AnturK I thought you removed it?

**Comment by Dorsisdwarf** [comment]
yeah it causes crashes for me if I have it open for more than about 10 seconds

**Comment by AnturK** [comment]
The only thing that's remotely unusual in crew monitor is sorting of the data, i can move it DM side i suppose.
