### ISSUE TITLE
Cult can still build on white ship

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#36833]
Issue reported from  Round ID: 85769 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

I thought cult space bases were fixed @Robustin ?
A highly mobile cult base seems like it's not intended.

**Comment by Robustin** [comment]
Space bases aren't disabled but they should have limited rune use. If they leave station level their runes should be disabled outright.

**Comment by DaxDupont** [comment]
@Robustin do they stay disabled or do they re enable on station z? Otherwise they can just move around the shuttle to the next position on the station's Z.

Even so shuttles probably shouldn't be valid since they are movable.

**Comment by JohnFulpWillard** [comment]
can't find the exact PR that added it but https://github.com/tgstation/tgstation/pull/57393 is all the evidence I got that this issue's been dealt with already.
