### ISSUE TITLE
Lavaland Watchers now give chase instead of staying in place

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#36832]
> Issue reported from  Round ID: 85768 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
> 
> Reporting client version: 512

This is not mentioned in the changelog and as such might be unintended. I suspect they inherit their AI from monkeys and monkeys were made more aggressive, so now either you kill the watcher immediately or you're completely screwed because of their slowdown.

**Comment by KorPhaeron** [comment]
Them not moving was the bug, wonder what fixed it

**Comment by Barhandar** [comment]
Apparently they now move _much_ faster and are more dangerous than goliaths.
