### ISSUE TITLE
communications console keeps resetting

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#36837]
NOTE: I WAS AI BUT IT ALSO WAS HAPPENING TO THE CAPTAIN
it is very hard to click things and you cannot input reasons for calling the shuttle because the page resets every ~3 seconds
this was on sybil I dont have a round id because I am not home haha

**Comment by Jalleo** [comment]
I can confirm I noticed this a few days ago.

**Comment by praisenarsie** [comment]
I can confirm too.
