### ISSUE TITLE
as a borg, recharging via cc transmission sigil doesn't cause synthesis of metal, glass, bandages etc.

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#36845]

**Comment by factoryman942** [comment]
it also doesn't restore the flash, which is probably more of a problem

**Comment by iskyp** [comment]
so what i'm getting is that it doesn't repair the cyborg or...?
in that case, it's intended behavior from what i can see. transmission sigil just charges borgs

**Comment by Barhandar** [comment]
It doesn't restore cyborg modules and their material counters which _are_ restored by normal chargers.

**Comment by factoryman942** [comment]
redundant with cc removal
