### ISSUE TITLE
Multiple people with the same randomly generated mothmen name

### ISSUE THREAD

**Issue by zaracka** [tgstation/tgstation#36846]
I forgot the specific rounds, but it has happened once for sure. I can't say if the second time wasn't genetics, but it probably wasn't. 

In Character Settings, select "Mothmen" as your species and enable Always Random Name. I believe the list of randomly selected mothmen names isn't very long or maybe it was pure coincidence. I have never had this happen while playing as a human, lizard, or plasmaman. With plasmamen, even if your base name is the same, the roman numerals will generally vary.

**Comment by 81Denton** [comment]
How about moths get surnames, so you don't just have "Mythimna" but instead something like:
- Mythimna Fibriata
- Mythimna Liebherri
- Mythimna Eucrossa

If it's allowed during the freeze, I'm up for working on it.

**Comment by zaracka** [comment]
RandomMarine, thanks for finding that information.

81Denton, sure that could work. Would it be enough though?

40 x 3 = 120.

120 different names.

**Comment by 81Denton** [comment]
I'd probably add add 30-40 moth surnames (aka steal them from a biology book) so that the total is above 1.000 possible combinations.

**Comment by zaracka** [comment]
Huh, I just looked it up. There are loads of species for the Mythimna genus. Same with Euplexia and Cryphia too. Cool, I'm a biologist now. Haha. This is a good fix in my opinion.

**Comment by 81Denton** [comment]
https://pastebin.com/zpdtVF2Q

I clearly don't know when it's time to stop. PR is done, when I open it depends on whether this counts as a bug or not.

**Comment by ShizCalev** [comment]
@81Denton Do it.
