### ISSUE TITLE
Too much crazy makes new crazy

### ISSUE THREAD

**Issue by Mophise** [tgstation/tgstation#36847]
I'm messing around on my friend's private server of tgstation. We're new to this kind of thing, so we're figuring it out before we try a public server.

I made a character with the following traits:
Prosthetic Limb, Depression, Jolly, Self-Aware, Reality Dissociation Syndrome, Apathetic.

My thoughts were to play a miner with bipolar and schizophrenia. It worked out for a while, and was quite fun trying to keep my character safe while dealing with mood swings and hallucinations.
I took up smoking, and would drink when on breaks up at the station.

Eventually my character developed a severe case of tourettes. he kept spasming, swearing, and I would lose control of him for minutes at a time. he would drop whatever was in his hands and just stand there, occasionally moving to a random adjacent square, and scream out random cuss words over the radio.

The chat was outputting "[my name] twitches violently" occasionally while I was having a fit.

Eventually I died, was cloned, and ended up even worse. I was somehow made blind, and was constantly in a fit with the occasional brief window to try to move or interact with things.

Best of all, my friend told me he couldn't find anything wrong with my character.

I'm not sure if this really counts as an issue, but there seemed to be no recourse, and it eventually made the round unplayable for me in a human body. I had no problems in a cyborg body, and went on merrily mining on the planet for the rest of the round.

[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**) "NULL"
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by RandomMarine** [comment]
Everything seems to be in order except that it's unclear _how_  your character developed tourettes. It's a disability which _may_ occur through radiation exposure or genetic manipulation.

Cloning introducing more genetic disabilities (In you case: blindness) is common, too.
For your information, both of those would have been easy to clear up with the chemical mutadone or through the genetics machines.

**Comment by Mophise** [comment]
I did get caught in a radiation storm for a couple seconds, but I had begun developing tourettes before that, which is why I couldn't get to shelter in time. I had been drinking a mix of pop and vodka in hopes it would improve my character's mood, and he swore a couple times, and then started locking up while I was trying to run for shelter when the warning came up.

I had been to the lava mining area twice before that incident, once with just a hardsuit and emergency oxygen, and the second time in a ripley.

**Comment by Jalleo** [comment]
@Qustinnus

**Comment by Tlaltecuhtli** [comment]
maybe your character has some genetic problems even you didnt know

**Comment by RandomMarine** [comment]
Genetic disabilities don't show up on medical scans.
Genetic (or cloning) _damage_ does, which is a different thing. That usually only happens to people that were cloned.

Other potential sources of radiation include:
Objects constructed with uranium (Uranium ore and sheets themselves are harmless, though)
Close proximity to the singularity or supermatter.
Unstable mutagen chemical (Which can also directly cause disabilities)
A traitor item disguised as a medical scanner that doses people it's used on with rads.

Nonetheless, all those sources would inflict toxin damage as well, did you have that at any point?

**Comment by Mophise** [comment]
Not that I can think of. I'll see if I can get it to happen again and update you with the results.

**Comment by Jalleo** [comment]
Also can be caused when cloned if the cloner isnt upgraded.

**Comment by Mophise** [comment]
no cloning happened until I was already a twitching swearing mess

**Comment by Mophise** [comment]
I've tried a few times now, and have been unable to reproduce it. Sorry.
I do enjoy the challenge of being crazy, so I'll be playing it occasionally. Maybe I'll have it happen again. I'm most confused about it not showing up to my friend when he's the admin.

Thank you for making tgstation, and your patience with me.
