### ISSUE TITLE
Greytide virus can bolt open SME chamber airlocks

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#36841]
The greytide virus event (events/prison_break) can bolt open the SME chamber airlocks since it affects area/engine. On lowpop, this usually results in delamination and round end.

From what I can see, random events aren't supposed to break the engine - filters, pumps etc. in engineering have the critical_machine var set to TRUE, which exempts them from the grid check event.

My best bet is that the greytide virus is older than the SME (singulo doesn't break if a bunch of doors open).

**Comment by Barhandar** [comment]
Can it open airlocks on burn chambers (turbine and toxins) and viro/xeno ones?

**Comment by 81Denton** [comment]
It can open all the airlocks you mentioned, except for the atmos turbine since it's area/maintenance/disposal/incinerator.

**Comment by Jalleo** [comment]
Bug tag required with easy fix as well. Its just a added prevention check required.

**Comment by 81Denton** [comment]
Changing the affected area from "area/engine" to "area/engine/engineering" would be a quick and easy fix, but yeah, being able to exclude specific areas (SME, incinerators) would be even better.

**Comment by Barhandar** [comment]
Specific airlocks, too. Pretty sure it doesn't bolt open _exterior_ airlocks.

**Comment by Dennok** [comment]
Also opening of server rooms and slime kill rooms is freezing a station.
