### ISSUE TITLE
Shuttles fail to clone in properly [TESTMERGE]

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#36848]
RID:85805
Testmerge: #36388
Reprod: Purchase any shuttle with a different footprint than the default.

https://file.house/sWUL.png

Items, turfs not overwritten, and the plasteel floor iconstate are not updated when a shuttle is purchased
@ninjanomnom

**Comment by ninjanomnom** [comment]
Issues with testmerge need to be on the pr.

I can't reproduce this locally so either put more details in the pr or message me.
