### ISSUE TITLE
Changeling's Reviving Stasis ability does not allow the player to revive at all after use.

### ISSUE THREAD

**Issue by rozequartz** [tgstation/tgstation#36854]
Issue reported from  Round ID: 85817 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Round ID]: 85816

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # Playing Changeling; when using the Reviving Stasis ability, I (and Duncdar, the admin who helped me try and solve this problem) cannot revive after using the ability; all abilities in the Changeling tab do not respond at all to clicks (including the 'Revive' ability) except for the Reviving Stasis ability itself, which will only return "We (you) are already reviving." Ling's minimum fake death timer is 40 seconds, and this occurrence makes said ling unable to revive at all. Setting the player's state to alive doesn't work either, and requires a full ghost-to-new body to fix.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by YakumoChen** [comment]
Ling would be a 4000% better mode with revival removed, please don't fix

**Comment by Barhandar** [comment]
I've seen same thing happen with Regenerative Coma symptom yesterday on Sybil.

**Comment by AnturK** [comment]
Caused by the stat define.
