### ISSUE TITLE
Dullahans can "melt their face off" with energy gun suicide (gun/energy/suicide_act() lacks a check for having a head)

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#36853]
Issue reported from  Round ID: 85815 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

> This is Dexter Grifflez!
> He is wearing  a shaft miner's jumpsuit.
> He is wearing  an explorer suit.
> He is carrying  an extended-capacity emergency oxygen tank on his explorer suit.
> He has  an explorer satchel on his back.
> He has  some black gloves on his hands.
> He has  a proto-kinetic accelerator about his waist.
> He is wearing  some blood-stained mining boots on his feet.
> He is wearing  PDA-Dexter Grifflez (Lost his head).
> **His head is missing!**
> He has minor bruising.
> Traits: Heavy Sleeper, Prosthetic Limb, Freerunning
> 
> Dexter Grifflez is putting the barrel of the energy gun in his mouth. It looks like he's trying to commit suicide!
> Dexter Grifflez melts his face off with the energy gun!

For that matter, other descriptions/checks that target head (like revolver's handle_suicide) might lack confirmation of having a head too.

**Comment by PKPenguin321** [comment]
More likely to happen to headless changelings
