### ISSUE TITLE
Tile pointer circuit name is inconsistent and doesn't work

### ISSUE THREAD

**Issue by robbym** [tgstation/tgstation#36861]
Tile pointer circuit name is inconsistent and doesn't work. I should have a PR with a fix soon.

**Comment by robbym** [comment]
Also, because it uses coordinates relative to where it is, it works differently when used in a handheld device, and when in a standalone device like a drone. Recommend switching to absolute coordinates to prevent confusion.

**Comment by PKPenguin321** [comment]
It's possible to convert from rel to abs with addition, just fyi
A better fix IMO would be adding a rel to abs circuit to complement the abs to rel one
