### ISSUE TITLE
Circuit outputs don't get saved on clone

### ISSUE THREAD

**Issue by robbym** [tgstation/tgstation#36860]
Circuit outputs don't get saved, which is a problem if you are using the constant memory circuits.
They just get set to null after you print the assembly. You have to set all your values with the debugger every time.

**Comment by robbym** [comment]
Didn't know you had to set them by hand. Should probably be detailed somewhere. Regardless, it doesn't retain its value if you clone it with an analyzer, unfortunately.

**Comment by arsserpentarium** [comment]
try again. Kevinz fixed it.

**Comment by robbym** [comment]
Tried again. Specifically doesn't work if value is set to 0. If I set it to anything other 0, it shows up on the analyzer.

**Comment by robbym** [comment]
It also allows you to set the output to whatever you want with a debugger, and this saves (again, if non-zero). I don't know if this conflicts with the original idea of setting by hand or not, however.

**Comment by arsserpentarium** [comment]
it's right.but problem with 0 is bug

**Comment by robbym** [comment]
Found it. PR soon.

**Comment by PKPenguin321** [comment]
Why even use constants? Single slot memory circuits do the same thing with the same complexity cost

**Comment by arsserpentarium** [comment]
they are emp proof
