### ISSUE TITLE
Plastic flaps leave behind an atmos "wall" even once removed

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#36874]
This is on a 3-day old version of the master but I dont think its been fixed:

1) Open a plasma can or whatever in a flap room

2) Unscrew the flap and move it

3) Marvel at the invisible wall containing the gas

4) Crowbar the floor tile and marvel at the gas suddenly surging outward

**Comment by Jalleo** [comment]
Likely due to same issue as power with vending machines recently fixed. Its not updating the tile to state this is getting moved no longer blocking stuff here. Not sure of the exact cause until I look at the code.

**Comment by YPOQ** [comment]
They update the turf when destroy()ed but not when moved.

**Comment by Cyberboss** [comment]
preferably the latter
