### ISSUE TITLE
Goonchat buttons are borked

### ISSUE THREAD

**Issue by Kerbin-Fiber** [tgstation/tgstation#36876]
Round ID: Every Round

Just open the game and try opening the Goonchat Settings

![](https://i.imgur.com/ztQsRyo.png)

**Comment by newfren** [comment]
oh yeah mine are borked too

**Comment by praisenarsie** [comment]
@cyberboss

**Comment by SpaceManiac** [comment]
Not as bad over here but still not correct
![image](https://user-images.githubusercontent.com/222630/47261128-e0a96b00-d47d-11e8-8372-ae45577130f6.png)

**Comment by Cyberboss** [comment]
Literally what caused this?

**Comment by kriskog** [comment]
Should be fixed
