### ISSUE TITLE
Telekinesis doesn't let you insert resources into exosuit fabricator from a distance, unlike cells/guns into chargers, stuff into autolathe, etc

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#36894]
Issue reported from  Round ID: 85870 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Specifically the menu to set how many sheets you want inserted appears, but once you click OK it shows "You are too far away!".   
It probably should check whether _sheet_ being inserted is close enough, as opposed to _player_ inserting it.

Probably applies to all other machinery that allows specifying amount of sheets inserted.

**Comment by ExcessiveUseOfCobblestone** [comment]
adjacency should always return true for TK users :^)

**Comment by Barhandar** [comment]
old TK where you literally could grab items into hand from anywhere you can see and then use them on anything you could see when
