### ISSUE TITLE
Viscerators are not vulnerable to EMPs

### ISSUE THREAD

**Issue by halitosisman** [tgstation/tgstation#36917]
Issue reported from  Round ID: 85908 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

They're robotic. Seems like EMPs should work on them.

**Comment by halitosisman** [comment]
Also came up this match. Syndicate turrets aren't vulnerable to EMPs either, I unloaded the ION rifle into them. It did nothing.

**Comment by XDTM** [comment]
The mob biotype thing will come in handy for this stuff

**Comment by Kromgar** [comment]
Maybe viscerators were made using fiber optic cable... 


HMMM? Didn't think of that did you?

**Comment by halitosisman** [comment]
With light powered motors?

**Comment by PKPenguin321** [comment]
Emp proof exterior
There no more bug

**Comment by timothymtorres** [comment]
Someone can make a new branch and reuse the code from #60051 but instead of sparks make it take damage or be destroyed.
