### ISSUE TITLE
Taser overlays are borked

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#36919]
Using the flashlight action button strips the taser of its overlays and using the taser in hand to change mode strips the action button.

**Comment by factoryman942** [comment]
same with kinetic accelerator, turning gunlight on disappears light and bayonet

**Comment by Kromgar** [comment]
@Robustin

**Comment by ShizCalev** [comment]
@robustin

**Comment by ArcaneDefence** [comment]
This isn't an issue now.
