### ISSUE TITLE
www...huuuuuuhhhh.....huhhhhhhh hyperlink in chat from talking?

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#36924]
![image](https://user-images.githubusercontent.com/6778786/38201561-c09ab4dc-3666-11e8-8857-5f4016a67364.png)

**Comment by Kromgar** [comment]
Works with any link it seems.

**Comment by ShizCalev** [comment]
In that case...

**Comment by Cyberboss** [comment]
How did this?

**Comment by optimumtact** [comment]
goon chat's autolinking strikes again

I started fixing this in #34086 but some stuff broke with it and I couldn't be bothered fixing it.

**Comment by PKPenguin321** [comment]
www...huuuuuuhhhh.....huhhhhhhh

**Comment by pigeonsk** [comment]
What's the expected behavior? Should IC chat be able to make hyperlinks at all or should this specific case be addressed or what?

**Comment by Kromgar** [comment]
@pigeonsk you shouldn't be able to hyperlink in normal speech but you can in ooc
