### ISSUE TITLE
curator being freaked out even though nobody is talking

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#36937]
id 85981

im so fucking confused
was also happening earlier when nobody was talking about snakes it would just randomly trigger when they spoke

**Comment by Bluespace** [comment]
Were you the curator with the stand?
That was so funny.

**Comment by Spaceinaba** [comment]
no I was in space fighting people in the ambush ruin and I started convulsing despite being alone

**Comment by Spaceinaba** [comment]
I am compiling a "things that trigger snakes for no reason" collection that I will post soon.

**Comment by Spaceinaba** [comment]
ALSO FOR GODS SAKE PLEASE REMOVE "BOOP" FROM THE TRIGGER TABLE ITS REALLY ANNOYING ESPECIALLY SINCE MACHINES GO BOOP LIKE SERIOUSLY WHAT INBRED MORON DECIDED THAT WAS A GOOD IDEA

**Comment by Therapist1** [comment]
curator went from “man with whip” to “guy you can defeat by talking to”, maybe the phobia should trigger only on sight of snakes.

**Comment by ExcessiveUseOfCobblestone** [comment]
I really like the phobia system, hopefully it can improve with some tiering mechanics!

IE just talking about snakes may make someone uneasy, but if they see a snake then WEW BOY they're filled with fright!

Person number 2 though might be so terribly afraid of snakes that even mentioning them in conversation gives him horrors.

There should be a soft separation between indirect reference of (fear) and directly being exposed to (fear)

**Comment by PKPenguin321** [comment]
All of those examples have `'s`

**Comment by Qbopper** [comment]
also they all have the letters of "snake" iirc? but the 's thing seems like a good place to start looking

**Comment by evsey9** [comment]
just say that the curator has social anxiety and call it a feature
