### ISSUE TITLE
Player sprite randomly bugs out

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#36936]
I don't know what causes this. Sometimes at random, my icon will bug out, and make me appear nude or remove most of the sprite, and changing direction will properly update it again. Also probably related to the icon performance updates.

**Comment by zaracka** [comment]
I had this happen to me after switching to Byond Beta. I was hesitant on opening an issue because I figured it was Byond's fault, not the code. I'm fairly certain it's a Byond issue because I also had it happen while using Byond Beta (client) on an old version of the code (local server).

Sometimes player clothes disappear, sometimes the torso, and sometimes the whole body but not the clothes. It generally happens to other player's characters, but it has happened to mine as well.

I think it goes hand in hand with a bug where a giant black square appears and shifts diagonally (probably because I was moving). Very hard to describe, but general visual glitches.

**Comment by newfren** [comment]
This can also happen to other people in my experience

**Comment by optimumtact** [comment]
without a roundid or testmerges we can't confirm if it was recent changes or a byond issue

**Comment by zaracka** [comment]
Managed to screenshot before it stopped occurring.

![ss13 visual glitch example](https://user-images.githubusercontent.com/37943475/38281760-4587784c-377a-11e8-8d6c-d4f6e66b8370.PNG) ![ss13 visual glitch example 2](https://user-images.githubusercontent.com/37943475/38281759-4573d33c-377a-11e8-975d-307f36729e0e.PNG)

In this case, hair, eye color, and clothes (but not all clothes) disappeared.

It has happened over the course of many rounds and on my local server (which goes back to March 2nd).
The images are from Round 86012.
BYOND Version 512.1418.

**Comment by optimumtact** [comment]
okay so if it's occuring on your local server as well then it's definitely not a test merge, and it's unlikely to be anything merged recently so it does look like a byond issue.

**Comment by praisenarsie** [comment]
ya it appears on other servers too on beta

**Comment by YakumoChen** [comment]
it started right after the icon performance changes hit

**Comment by optimumtact** [comment]
@YakumoChen which PR are you referring to?

**Comment by zaracka** [comment]
Round 87744. Bagil.
Version 512.1423.

This time I didn't change direction which would have properly updated it, like Yakumo said. I crashed.

![ss13 visual glitch example 3](https://user-images.githubusercontent.com/37943475/39900958-5fadefae-5493-11e8-9c16-1748a1b061bf.png)

**Comment by zaracka** [comment]
Don't get this bug on 512.1413, get it on 152.1416 though. Might have been fixed in later versions, can't test that consistently because of frequent crashes.

**Comment by Iatots** [comment]
Oh neat, someone necroe'd this already.
I am on beta 5.0 512.1426 and on terry I sometimes completely disappear. Happened twice in the past two days. Both times I was in lavaland. Rounds were in the last couple days so 9110X. Will post again if I encounter it a third time.

**Comment by Aranclanos** [comment]
Happens constantly to me, I'm on 5.0 Beta v 512.1442 while playing in the main server

**Comment by timothymtorres** [comment]
Issues #36936, #44100, #38820, and #37227 all seem to be related to a BYOND bug that was fixed at some point since there haven't been any recent issues involving overlays in the past few years.  

Going to go ahead and close them all.
