### ISSUE TITLE
Gun icons don't update

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#36935]
Probably related to Robustin's preformance changes but when I charge guns the icons don't update until I do something with them like use them in hand to change modes.

**Comment by ShizCalev** [comment]
@robustin

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/pull/36776/files#diff-55f8432b4eac76b82323ca5b6da7db8fR133

Math pros attack
