### ISSUE TITLE
AI occasionally crashes using the crew manifest

### ISSUE THREAD

**Issue by brotherbotany** [tgstation/tgstation#36941]
Issue reported from  Round ID: 85986 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

85986

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

Whenever the crew monitoring console is opened for an extended period of time whenever playing as an AI, it occasionally causes my Dream Weaver application to crash completely, forcing me to reboot. To reproduce the crash (with varied success), open the crew monitoring console and leave it open as you continue to play. No crashes have occurred when the crew monitoring console was closed up to this point that I am aware.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by CPTANT** [comment]
I am getting occasional AI crashes without using the manifest.
