### ISSUE TITLE
Heirloom trait issues

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation#36940]
1) cloning breaks the heirloom bond, and gives people negative events
2) some peple spawn with out a heirloom item (during april fools at least) and get a negative mood modifier with no fix

@Xhuis ? @Qustinnus ?

**Comment by Barhandar** [comment]
Second one is only an issue if illegal (such as too large for regular backpacks, or abstract) items get added to regular set.

**Comment by Qustinnus** [comment]
Most likely not related to mood code itself.

**Comment by Xhuis** [comment]
The second issue is probably related to what @Barhandar since it picks any valid item in the game during April Fool's. Cloning breaking the bond is a legit issue, however.
