### ISSUE TITLE
factions in trade ambush turrets is brok

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#36949]
the turrets shoot everyone even the mobs supposed to be in the same faction

**Comment by ExcessiveUseOfCobblestone** [comment]
@ShizCalev another riveting tale of "Syndicate" vs "syndicate"

**Comment by 81Denton** [comment]
I can't reproduce this on Revision: a5dbfeeeb2b3d018c68ed090598e1652d750d4df

Maybe it was a testmerge or badmin stuff?

**Comment by kriskog** [comment]
Cant reproduce.
