### ISSUE TITLE
Loss of items as a mediborg if hacked before rebooted.

### ISSUE THREAD

**Issue by zombiegums** [tgstation/tgstation#36955]
Issue reported from  Round ID: 86004 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

[Round ID]: #86004

[Reproduction]: # I was killed by a magicarp and brought to robotics where I was hacked by a traitor. I believe I had my health analyzer equipped at the time in my first module slot prior to the hack. Upon being rebooted, I gained the hacked hypospray, but my health analyzer disappeared. Usually, equipped items tend to "disappear" but their icons are just invisible in the module slots. On this occasion, my health analyzer is actually gone. It's not in any module slots, nor is it in my cyborg inventory. Was told to report this by an admin.

**Comment by Sealed101** [comment]
can no longer reproduce
