### ISSUE TITLE
Signing up for head roles as plamamen turns you into a human but also gives you plasmamen equipment

### ISSUE THREAD

**Issue by zaracka** [tgstation/tgstation#36968]
Round 86032.

Pick "Plasmaman" as your species and sign up for a head role. You receive everything plasmamen usually get, despite being human. Plasma internals, plasma envirosuit, and plasma envirosuit helmet. You start with internals toggled on, which means you're breathing plasma as a human. No idea why this happens, but your suit has no slowdown either.

**Comment by vuonojenmustaturska** [comment]
easy fix
