### ISSUE TITLE
Pet carriers fuction as a makeshift Ghost trap

### ISSUE THREAD

**Issue by Therapist1** [tgstation/tgstation#36979]
[Round ID]: # 86065

[Testmerges]: I didn’t catch what was testmerged, but I doubt it’s relevancy in this situation, for it is due to the revenants tiny size being able to be picked up by pet carriers.

[Reproduction]: Find a revenant that is corporeal (I.E draining a corpse of essence), Get a pet carrier and use it on the revenant while it is open. Close and lock the pet carrier, put on a conveyor belt. Result: https://www.youtube.com/watch?v=0tdyU_gW6WE

**Comment by arsserpentarium** [comment]
feature!

**Comment by arsserpentarium** [comment]
No,seriously. Ability to bind evil spirits into vessel is feature.

**Comment by Therapist1** [comment]
must’ve made em lined with silver or something

**Comment by arsserpentarium** [comment]
They are already have silver color

**Comment by Therapist1** [comment]
welp, time to build the patented B.U.S.T.I.N ghost containment system

**Comment by arsserpentarium** [comment]
No, please, change tag to feature.

**Comment by dragomagol** [comment]
Revenants can still be caught by pet carriers while visible, but being in a locked one on a conveyor doesn't trap them.
