### ISSUE TITLE
Clown ruin is entirely space lube.

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#36971]
![image](https://user-images.githubusercontent.com/6778786/38313835-ef676c32-37f2-11e8-92a4-62c7f140b572.png)

 The yellow floors did used to slip you but only if you ran and now you can get ejected out of the ruin trying to get into the prize room now as the floor tile the door is on is also lubed and send you spiraling into the disposal i only managed to luck out by diagonal walking into the room.

Also yes i know the first half was bugfixed but the yellow bananium floors only used to slip you if you ran rather than walked. Also everything has a lube sheen it was never like that before.

**Comment by KorPhaeron** [comment]
It is supposed to slip you when walking, its an ice maze puzzle 

It has evidently been bugged a very long time and is finally fixed

**Comment by Barhandar** [comment]
It's a "bring a jackhammer and break through the walls" puzzle.
