### ISSUE TITLE
Supermatter instant delam megathread

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#36970]
https://github.com/tgstation/tgstation/issues/34732
https://github.com/tgstation/tgstation/issues/35468
https://github.com/tgstation/tgstation/issues/33507
https://github.com/tgstation/tgstation/issues/33982
https://github.com/tgstation/tgstation/issues/28638

**Comment by CPTANT** [comment]
And #28638

**Comment by pigeonsk** [comment]
It's been a while since I last looked at the supermatter code but I'll just reiterate my previous thought that to fix this "bug" you would need to add a hack or overhaul SM mechanics.

**Comment by DaxDupont** [comment]
The rapidly delams in a vacuum was fixed by my does not explode on a vacuum fix too. 
The old code for vacuums/space tiles made it delam in under 20 seconds.
