### ISSUE TITLE
Lifegiver Ruins Chem dispenser takes eons to regenerate.

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#36972]
Issue reported from  Round ID: 86047 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

![image](https://user-images.githubusercontent.com/6778786/38316345-7ecd981a-37f8-11e8-9a3a-9c59227926d6.png)

EX: From 6 unit wait 2 minutes and your at 20

Maybe they should be given an inducer with a void cell or something? Seems to be the reed glover choice for refilling chem machines now that they have been heavily nerfed

**Comment by Barhandar** [comment]
Does their dispenser start with T4 capacitor?

Also make the regen percentage-based instead of flat-value-based so regardless of cell tier the chemdisp will recharge completely in specific amount of time.

**Comment by Kromgar** [comment]
It starts charged. But when you are mutating plants it can go by pretty quick
