### ISSUE TITLE
Inconsistent shuttle tiles with DYI shuttle

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#36987]
Noticed on meta-station that large chunks of the shuttle, while part of the initial template, don't leave with the shuttle. I've seen beautifully crafted gold plated shuttles with functioning atmos and fancy seating get ripped to shreds.

**Comment by ninjanomnom** [comment]
Not enough information was given and this was probably during the shuttle baseturf changes pr being testmerged.

Related issues have been fixed.
