### ISSUE TITLE
Dual-Mode hardsuits (such as the blood-red hardsuit) start in EVA mode, but automatically turn to combat mode once you take the helmet off.

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#36986]
Tested on localhost, latest commit,

Reproduction:
1) Spawn in /obj/item/clothing/suit/space/hardsuit/syndi
2) put it on, take note that it's in EVA mode and the helmet is off
3) Toggle the helmet on and off, notice how it turns to combat mode automatically when turned off

The suit automatically turning to combat mode when you take the helmet off seems to be intended behavior, but starting in EVA mode before you even put the helmet on is a bit inconsistent.

**Comment by ExcessiveUseOfCobblestone** [comment]
I want to say it's a newbie safety measure, and because of that i'm not sure if we should even "fix" it.

**Comment by iskyp** [comment]
how is this a safety measure in any way
like, they require a spaceworthy helmet unless they just use the helmet on the suit

**Comment by ExcessiveUseOfCobblestone** [comment]
Because you'd otherwise have to set it to space-worthy AS WELL AS toggle the helmet.

**Comment by PKPenguin321** [comment]
See https://github.com/tgstation/tgstation/blob/6401ba57081efb3db2f39320eeefeb13c1be4d8c/code/modules/clothing/spacesuits/hardsuit.dm#L301 and the related procs just below it.
My theory is that popping out the helmet spawns a new one, and the starting setting that the helmet is set up for is combat mode. You could change this so it starts in EVA mode but then you might have the opposite problem.
