### ISSUE TITLE
null crates use copypasta rather than pulling from surplus

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#36984]
https://github.com/tgstation/tgstation/blob/master/code/modules/cargo/packs.dm#L155-L168

https://github.com/tgstation/tgstation/blob/master/code/modules/uplink/uplink_items.dm#L1490-L1510

Top should pull from bottom, post #36983 (should it be merged) a new proc should be made handling the item generation with an arg to differentiate between a null and a syndicate crate.

**Comment by kriskog** [comment]
Nulls are gone
