### ISSUE TITLE
Firing the station BSA possibly disconnects all players from the server

### ISSUE THREAD

**Issue by pigeonsk** [tgstation/tgstation#36988]
I'm basing it on hearsay and correlation, but apparently "Firing the station BSA possibly disconnects all players from the server". Global disconnects happened two times on one round, directly after the firing of the BSA each time.

Round ID: 86082, Bagil

**Comment by EvilJackCarver** [comment]
Poking in to confirm this, at least for the second time.

The disconnects took between 1.5~2.5 minutes to resolve each time, and the server tracker on the homepage showed Bagil as offline both times.

**Comment by DaxDupont** [comment]
This must be recents since on the 1st I installed one of them and they worked fine.

**Comment by EvilJackCarver** [comment]
It's entirely possible it was its placement that was causing issues; the crew decided to build it in the (vertical) centre of the brig foyer facing right, and it cut a line all the way from the brig foyer to the airlock to space near engineering.

**Comment by Jalleo** [comment]
I presume it smashed everything in its path?

**Comment by EvilJackCarver** [comment]
That's correct, for the most part. I believe it left plating where a wall was, but everywhere there was plating it just cut a line to space.

**Comment by Jalleo** [comment]
It probably has a bad setup with how its coded I will try to look at it later.
