### ISSUE TITLE
Admin AI interaction doesn't work on at least the APC and airalarm, possibly more.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#36993]
Issue reported from  Round ID: 86092 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Admin AI interaction doesn't work on at least the APC and airalarm, possibly more.

Clicking does nothing.

**Comment by DaxDupont** [comment]
@kevinz000 ?

**Comment by kevinz000** [comment]
Just tested it works fine right now? Firelocks and disposals don't though.
