### ISSUE TITLE
Self sustaining extract crossbreeding doesnt work

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#36996]
Dark Purple crossbreeds (self-sustaining) dont work

[Reproduction]: # 
1: Get adult slime and 10 darkpurple extracts
2: Feed the extracts to the slime
3:Profit. or lack thereof
Exceptected outcome- Get self sustaining extract. 
Actuall outcome-Get nothing. Waste a slime and 10 darkpurple extracts

http://prntscr.com/j1c4v0

**Comment by ExcessiveUseOfCobblestone** [comment]
@fludd12

**Comment by fludd12** [comment]
Incessant Screaming. Will fix.

**Comment by fludd12** [comment]
Currently in class - if anyone wants to get at this before me, it means there's a mismatch between the effect name on the extract and the effect name on the crossbreed.

**Comment by adamkad1** [comment]
what time you in class at? with timezone, if you decide to answer

**Comment by ExcessiveUseOfCobblestone** [comment]
meet behind the bleachers 5pm sharp ~~~

**Comment by adamkad1** [comment]
i cant seem to spawn them throught sandbox menu when everything else works

**Comment by adamkad1** [comment]
seems like its not gonna be that fast. when im gonna be able to stop asking the chaplin?

**Comment by fludd12** [comment]
I *think* I fixed this at some point. Someone confirm?
