### ISSUE TITLE
CANT CLICK SHIT IN MY INVENTORY ANYMORE

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#37003]
Issue reported from  Round ID: 86102 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

O BçAem.) I BLçAME KEV CODE

**Comment by Tlaltecuhtli** [comment]
update: my dress inventory( pockets, belt) was unclickable, restarting game didnt fix it, grabbing something from my bag fixed it

**Comment by francinum** [comment]
Can we get your client minor version as well?

**Comment by Jalleo** [comment]
@kevinz000

**Comment by kevinz000** [comment]
...?

**Comment by Tlaltecuhtli** [comment]
i havent experienced this bug again in a while will close it in 1 week if no one experiences it and solve this as a byond anomaly

**Comment by Armhulen** [comment]
DOOR STUCK

**Comment by ShizCalev** [comment]
Related? #37023

**Comment by kriskog** [comment]
Seems fixed.
