### ISSUE TITLE
Plasmamen start with their internals if they sign up as head when humanized.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#37018]
https://tgstation13.org/parsed-logs/terry/data/logs/2018/04/06/round-86136/

1. Be plasmaman
2. Sign up for head role
3. Start with plasmamen gear as a human

**Comment by 81Denton** [comment]
Maybe #36969 didn't get merged on Terry yet? That server is always ages behind Bagil/Sybil.

**Comment by DaxDupont** [comment]
derp probably
