### ISSUE TITLE
Can't view the contents of people's bags with the observe verb

### ISSUE THREAD

**Issue by Metroidlover** [tgstation/tgstation#37010]
It's really annoying not being able to see what people have

Just use the observe verb and try to look in someone's bag. You can't.

**Comment by YPOQ** [comment]
https://github.com/tgstation/tgstation/commit/f300a5c155c6bc69fd2a158bc1f79dca2b7ce6d8#diff-3da44c64d03131c50b931ad1dfdfac48L79
@kevinz000 Was this intentional?

**Comment by ShizCalev** [comment]
@kevinz000 ?
