### ISSUE TITLE
Space Pirate Booty Locator Crashes Server

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#37016]
Interacting with the Booty Locator to see how many credits you've gotten causes the game to immediately runtime and lock up for a solid minute. Tested today and yesterday and it works.

**Comment by Metroidlover** [comment]
Can confirm. Broke server 3-4 times before I realized it was me.

**Comment by praisenarsie** [comment]
@AnturK

**Comment by Armhulen** [comment]
If it's a runtime someone should post what the runtime is

**Comment by DaxDupont** [comment]
Where's the round ID

**Comment by SpaceManiac** [comment]
No repro locally, couldn't find anything obviously related in the condensed logs

**Comment by YakumoChen** [comment]
Someone said it was related to the Heirloom trait if that helps. Kevin saw a bunch of errors related to GETCONTENTS of heirloom in the logs.

**Comment by Metroidlover** [comment]
Can confirm I had the heirloom trait when i used it. It could be trying to check every person's heirloom on the station as well.

**Comment by vuonojenmustaturska** [comment]
the heirloom bug is unrelated

**Comment by kevinz000** [comment]
something something for var atom movable am in world =|

**Comment by optimumtact** [comment]
it's more likely that the vault being moved about put it's area in space so it tried to locate in a massive area

**Comment by YakumoChen** [comment]
I'm sure this is fixed by now
