### ISSUE TITLE
Circuits can't have more than 1 input pulse

### ISSUE THREAD

**Issue by robbym** [tgstation/tgstation#37011]
Circuits are not able to have more than 1 input pulse. Not really a bug, but a design failure in my opinion.
The on_data_change() and do_work() procs are not able to differentiate the input pulses _if_ a component had more than one. None of the components currently do have more than one (because it doesn't work maybe?), but I believe the lack of this ability stifles certain additions (subcircuits for example).

**Comment by Jalleo** [comment]
This is a feature request @KorPhaeron

**Comment by arsserpentarium** [comment]
They can. Look at chem circuits with pulse ref pins

**Comment by arsserpentarium** [comment]
Subcircuits was coded by Carbonhell and wasn't added yet because of feature freeze

**Comment by robbym** [comment]
Oooooh. I was wondering what the hell ord was for. Thanks.

**Comment by arsserpentarium** [comment]
there is problem, that all pulse in pins have same cooldown and energy consumption.But IDK how to make it better in not clunky way/
