### ISSUE TITLE
SMES cannot be deconstructed

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#37020]
Round ID: Various

Step 1 - Screwdriver SMES
Step 2 - Crowbar floor tile to reveal the terminal underneath
Step 3 - Wirecutter the SMES to remove terminal
Step 4 - Attempt to crowbar out the parts but fail as it still thinks there's a terminal attached
Step 5 - Wirecutter the SMES again and start cutting non-existent terminals

**Comment by praisenarsie** [comment]
There's already a similar issue for this somewhere. It can be deconstructed if you rotate it with a wrench, then crowbar out the parts.

**Comment by factoryman942** [comment]
#30979
close dis
