### ISSUE TITLE
MetaStation's SM cooling loop has next to no meteor protection

### ISSUE THREAD

**Issue by EvilJackCarver** [tgstation/tgstation#37034]
### Issue

Meteors tend to break the Supermatter cooling loop on Meta very often. Doesn't happen on Delta or Omega due to the station design having the cooling loop protected by other objects (the solars and more grilles [possibly with R-walls] in Delta's case, a few R-walls with part of the asteroid protecting them in Omega's). Pubby doesn't use the Supermatter, and Box already has protection.

![](https://i.imgur.com/bOC0glM.png)

*MetaStation's cooling loop, after a meteor shower. There is no R-wall or any further protection under those grilles; only lattices.*

### Suggested fixes:

**Suggestion 1**: MetaStation's master Atmos tanks have two-to-three-thick grille-over-R-walls to protect them from meteors; and they have gaps between them every so often to allow a chance meteor or a saboteur/repairman to get in to fix the loop. 

![](https://i.imgur.com/xW02rIQ.png)

*MetaStation's master atmos tanks, from the east. The three grille/R-wall combo walls (two on the south) have small breaks in between to allow a saboteur, a repairman, a nukie, etc inside. The gap at the bottom has allowed a chance meteor to strike the master CO₂ tank.*

You could set up walls similarly to that near the cooling loop with it ending near (but not fully covering) the bottom of the loop, which would only allow incidental meteors to strike the loop and still allow saboteurs/nukies to manoeuvre.

**Suggestion 2**: Boxstation's ([map](https://tgstation13.org/wiki//images/d/d1/Boxstation.png)) Supermatter cooling loop is protected by an R-wall sandwiched between two grilles. This doesn't allow a meteor a direct angle to the cooling line without the meteor first hitting a grille or two. The gaps are two tiles wide at the bottom left, which lets saboteurs/nukies/etc to manoeuvre more freely, while still providing decent protection from meteors. 

![](https://i.imgur.com/CB7e11j.png)

*Boxstation's cooling line setup, from the wiki.*

This is already set up somewhat behind the emitter area; you could extend this a bit further, e.g. to the grilles below the cooling line, to protect it better from meteors.

**Suggestion 3**: Make it an IC issue, make the meteor shield always available, and make the crew set up the shield themselves.

[Round ID]: 86194

**Comment by CPTANT** [comment]
Feature.

**Comment by 81Denton** [comment]
Gotta agree with you there, Box has r-walls and Delta a solar array to catch stray space dust. 
Meta on the other hand

![wfefqwefweq](https://user-images.githubusercontent.com/32391752/38459511-c9cdb444-3aaa-11e8-9c0f-af880c38ffb7.jpg)

**Comment by SgtxRootbeer** [comment]
Meta issue, box and Delta should be nerfed

**Comment by Repukan** [comment]
Feature, engineers should reinforce defenses

**Comment by pigeonsk** [comment]
+1 for feature, box and delta nerf

**Comment by EvilJackCarver** [comment]
@ShizCalev you can remove the 'good first issue' tag; this isn't the first issue I've submitted (it's the second)
