### ISSUE TITLE
Telecomms being down breaks door remotes

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#37046]
stealth nerf by the NTNet change, either document or fix

**Comment by PKPenguin321** [comment]
Would make sense if NTNet devices had a local range that they could operate on in addition to the telecomms system, so if you're in the local range you can still have two devices interact despite the telecomms device being down

**Comment by Tlaltecuhtli** [comment]
ntnet dies when the ntnet machine in tcomm dies this is intended

**Comment by ShizCalev** [comment]
feature
