### ISSUE TITLE
[Escape pod bug: No CentComm destiny]

### ISSUE THREAD

**Issue by MortoSasye** [tgstation/tgstation#37048]
[Round ID]: # 86222

[Reproduction]: # I was a traitor playing a round on the Basil server. My first objetive was to steal the captain antique gun, which i did, and the second objective was to escape alive on an escape shuttle or pod without being in custody. When the shuttle arrived at the station, i decided to use the escape pod, so i got in, waited for the countdown to finish and started the travel to CentComm... or so i though.

When i was on the escape pod the computer said i was going towards an unknown location, i though that it maybe was a visual bug until i noticed at the round end that i got marooned in space and my second objective was failed.

**Comment by ninjanomnom** [comment]
I'll take a look at this tomorrow, probably a fairly easy fix based on the runtimes I see.
