### ISSUE TITLE
Syndicate Radio Implant prevents you from talking over non-common channels.

### ISSUE THREAD

**Issue by TechnoAlchemisto** [tgstation/tgstation#37047]
After installing the implant, I was unable to speak over any channels besides common. Even with a captain level headset. 

There's no way of disabling this, and from what I know of the implant can't be surgically removed.

**Comment by factoryman942** [comment]
#36522 #36981 #34136 aaaaaaaaaaaa

**Comment by AlexTheSysop42** [comment]
@ShizCalev dupe(s)

**Comment by ShizCalev** [comment]
Duplicate of #34136
