### ISSUE TITLE
emps break lathes

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#37060]
Issue reported from  Round ID: 86240 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512
you cant put materials inside until you decon and rebuild it

**Comment by YPOQ** [comment]
You sure it wasn't just depowered?

**Comment by Tlaltecuhtli** [comment]
there was power and i was able to open the interface but i couldnt put minerals in

**Comment by Barhandar** [comment]
It gets "disabled" for some time by EMP, the problems are 1: there is _zero_ feedback about this and 2: Pubby's lathes are too close to the engine due to it running on tesgulo (Box and Meta don't have the issue because SM doesn't spam EMPs).

**Comment by Tlaltecuhtli** [comment]
the lathe was working it just wouldnt accept minerals

**Comment by Tlaltecuhtli** [comment]
also it was perma disabled not temorarly
