### ISSUE TITLE
dying in a vr sleeper glitches a lot

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#37061]
Issue reported from  Round ID: 86240 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

my camera was free moving while in crit, when i finally died the ghost became invisible

**Comment by praisenarsie** [comment]
@RemieRichards ;)

**Comment by RemieRichards** [comment]
Not my issue anymore bby.

**Comment by DaxDupont** [comment]
can't replicate, byond issue?

**Comment by DaxDupont** [comment]
@ShizCalev VR has been completely redone and doesn't bug like this anyone. You can close it.
