### ISSUE TITLE
Electric grills are deleting doors

### ISSUE THREAD

**Issue by Michael-Ashfield** [tgstation/tgstation#37078]
[Round ID]: #86282 (Bagil - Delta Station)

What happened: I was breaking into security via the gulag shuttle entrance from the public sec corridor on Delta, I destroyed the glass then threw a fire extinguisher at the electrified grill. The grill made one visible arc of electric then the security door next the the grill deleted completely, it didn't damage but just was not there anymore.

Continuing my break-in, I broke the glass on the next door north to it, after 3 normal hits with the extinguisher (the door remaining there and electric arcing normally), the 4th hit deleted the door.

I continued after notifying an admin, the last door (The right door of the gulag teleporter room) didn't delete, I broke the grill normally.

**Comment by Michael-Ashfield** [comment]
Enough damage to completely remove them with no trace in one hit? They take a good few shocks to crit a player so removing an entire airlock doesn't sound right.

**Comment by 81Denton** [comment]
The issue seems to be how tesla_zap interacts with machinery. You could add machinery/doors to blacklisted_tesla_types, but that feels kinda wrong.

**Comment by kevinz000** [comment]
can't fix it without changing tesla_zap and i have a refactor branch that will fix this but freeze so 🤷‍♂️

**Comment by pigeonsk** [comment]
Your change is now a fix, see https://github.com/tgstation/tgstation/pull/36977
