### ISSUE TITLE
Wicker doll cooldown is shorter than knockdown allowing chainstun from any z-level

### ISSUE THREAD

**Issue by zaracka** [tgstation/tgstation#37076]
var/cooldown_time = 30 //3s
target.Knockdown(40)

Maybe this is the trade-off for finding an item someone touched. Seems unreasonable though, at least in my opinion. It is a wizard item, however rarely shaft miners are able to obtain it as well.

**Comment by ExcessiveUseOfCobblestone** [comment]
just add a do_after so the individual doing it has to be immobile as well :^)
