### ISSUE TITLE
Clones heirlooms are bugged

### ISSUE THREAD

**Issue by Michael-Ashfield** [tgstation/tgstation#37079]
[Round ID]: #86284

If you have the heirloom trait and get cloned then your mood goes depressed saying you don't have your heirloom, even if you do have it.

Step 1: Have heirloom trait
Step 2: Have Have the heirloom in a safe place and die
Step 3: Get cloned
Step 4: Recover Heirloom as clone and see that you are still depressed

**Comment by YPOQ** [comment]
Looks like the heirloom var on the trait is getting set to null after cloning. I'll try to fix.

**Comment by PKPenguin321** [comment]
Pretty sure this is a dupe

**Comment by YPOQ** [comment]
Yeah #36940
