### ISSUE TITLE
Splitting stacks can be used to bypass the item size limit of certain containers.

### ISSUE THREAD

**Issue by Null0Null0** [tgstation/tgstation#37087]
Round ID: 86296
 -Not that this should really need it.

When item stacks are split into stacks of 30 or less they become "small" items. You can place these into cardboard boxes and, presumably, other containers with a similar item size restriction. 2 stacks added to a container in this way will still combine to their total, in one inventory slot. The resulting stack can be above 30, making a "normal-sized" item, which should not fit in a box.

Steps to reproduce should be implicit in the description.

**Comment by Rinoka** [comment]
@kevinz000

**Comment by octareenroon91** [comment]
This bug is at least as likely to annoy the user, since they will later pull out something that cannot be put back in directly.
