### ISSUE TITLE
Crowbaring playermade floor on lavaland does not change floor to plating, resulting in being able to get infinite floor tiles.

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#37097]
Issue reported from  Round ID: 86308 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])  
Reporting client version: 512  
>The following pull requests are currently test merged:  
>#37024: 'Puts some brakes on the Cult Train' by Robustin at commit 3a5c2d  
>#37039: 'testing new icons for webs!' by Armhulen at commit 5ad857  

Might be related to baseturf changes. Trying to deconstruct such tile with RCD does nothing - tile remains, RCD ammo is not changed.  
Though lavaland flooring was buggy even before, #37099

Logically using floor tiles on lavaland turf should create plating, not full-on floors; or actually treat the turf like plating like map tiles already do.

Crowbaring roundstart tiles (e.g. mining station) correctly results in floor removal, but shows it's lavaland turf underneath. These can be replaced successfully and repeatedly as well.

P.S. Floor tiles can be weldered back into sheets and this bug _does_ happen with titanium, gold, silver and plasma so presumably all materials, giving infinite sheets.

**P.P.S.** The bug does not happen if the tile has had wire placed on it. Volcanic floors which had wiring on them operate correctly, being able to remove the tile.

**Comment by AlexTheSysop42** [comment]
wow this is even worse than the rfloor one
