### ISSUE TITLE
Conveyor belts are broken.

### ISSUE THREAD

**Issue by Durkel** [tgstation/tgstation#37091]
[Round ID]: Any round, they flat busted.

Placing down conveyor belts and then trying to remove them with create a duplicate of the original, the same occurs for the switch. Essentially you end up with a shitload of conveyor parts that you either can't use or ones that are in the wrong position.

**Comment by zaracka** [comment]
These suddenly work again. Not broken.

Tested on round 86573. Bagil.

**Comment by SpaceManiac** [comment]
Seems like it fixed itself, post again if they are still broken.
