### ISSUE TITLE
Drones can't drag themselves into crates

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#37098]
Issue reported from  Round ID: 86308 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

**Comment by RandomMarine** [comment]
https://github.com/tgstation/tgstation/blob/master/code/game/objects/structures.dm#L46
It's child's play to add a isdrone check here but I wonder if a helper should be made that checks for dextrous instead.
