### ISSUE TITLE
Alternate Appearance doesn't work on new mobs

### ISSUE THREAD

**Issue by Davidj361** [tgstation/tgstation#37102]
The functionality of alternate appearance from code\game\alternate_appearance.dm doesn't work on new mobs.

Case 1:
1. Have 2 clients
2. Client 1 wears a cardboard cyborg suit
3. Client 2 spawns in as a cyborg
4. Client 2, the cyborg, sees client 1 as a cardboard suit and not as a cyborg as they're supposed to

**Comment by Cruix** [comment]
I cannot reproduce this.

**Comment by DaxDupont** [comment]
It sometimes happens, in some cases it gets refreshed though

**Comment by ExcessiveUseOfCobblestone** [comment]
The part that sets the appearance to other mobs loops through a list of current mobs without ever taking into consideration future mobs...

Now why would you do that, I have no idea lol.

**Comment by Davidj361** [comment]
This bug didn't happen when I tested on master. It's from a PR I'm working on.

**Comment by JohnFulpWillard** [comment]
Tested this locally and was unable to replicate.
