### ISSUE TITLE
Bluespace shelters break (don't set area on some tiles, resulting in these getting exposed to ash storms) much more often now

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#37101]
Issue reported from  Round ID: 86322 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])  
Reporting client version: 512

First shelter in this round only had 2 safe tiles, this one has 4. Good thing storms can't get you when you're in a sleeper.

**Comment by Kromgar** [comment]
Did the ash tiles actually damage you?

**Comment by Barhandar** [comment]
I have no idea, didn't want to risk trying.

**Comment by Kromgar** [comment]
I reported this glitch already its only visual its non-harmful

**Comment by ExcessiveUseOfCobblestone** [comment]
@ninjanomnom ??

**Comment by SpaceManiac** [comment]
Duplicate of #34436.

>Good thing storms can't get you when you're in a sleeper.

Pretty sure this isn't true.

**Comment by ninjanomnom** [comment]
^
