### ISSUE TITLE
Clothing Dissaperaing inw ashing maschine

### ISSUE THREAD

**Issue by Vakulum** [tgstation/tgstation#37108]
played on Bagil

Put a black crayin a jumpsuite and a grey cap in the wahing maschine. It returned (after wasching) just the recoloured suite, cap was gone.

**Comment by PKPenguin321** [comment]
Did you check underneath the washing machine

**Comment by Vakulum** [comment]
no. Did not think of that.....

**Comment by Rinoka** [comment]
this happens pretty often with equipment

rightclick the equipment's square when things "disappear" like this, it's almost always to do with the way we layer things

**Comment by Rinoka** [comment]
@KorPhaeron pretty sure this is a misunderstanding and can be closed.

**Comment by KorPhaeron** [comment]
We need to change the washing machines layer then

**Comment by Rinoka** [comment]
you're not wrong, i suppose, but iirc this is inconsistent. i'll peek at it later i suppose
