### ISSUE TITLE
Marksman rifles can damage Blazing Oil Blobs

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#37104]
The round ID is 86328

![image](https://user-images.githubusercontent.com/12382984/38580559-2b20a52c-3d02-11e8-89c1-3ed28b832ee5.png)

>Blob whose one gimmick is immunity to burn based weapons
>Burn-based weapon that bypasses their special caveat

Definitely not broken.

**Comment by Barhandar** [comment]
["Immune to fire", not "immune to burn".](https://github.com/tgstation/tgstation/blob/master/code/modules/reagents/chemistry/reagents/blob_reagents.dm#L174) Which is entirely fucking useless though and it was getting damaged by a welder, as well. 

What weapons do even _have_ flag "fire"?

**Comment by Kromgar** [comment]
Those guns are so fucking awful. Do they even need to be charged?

**Comment by Barhandar** [comment]
Yes.

But they use an internal _power cell_...  
...which can be recharged with inducers...

**Comment by Anonmare** [comment]
Inducer weapon charging is actually really kind of broken as you can use them to recharge Advanced Energy Guns - Which explicitly disallow charging with weapon chargers.

**Comment by Barhandar** [comment]
@Anonmare, if they can be used to recharge AEGs, they can also be used to recharge plasma cutters.

**Comment by kevinz000** [comment]
once again with the "but it can be recharged with inducers" when in reality you can get a shot off by doing so with a single inducer every ~25 seconds and that's just a guesstimate assuming inducer_act has a delay for cycles of 0.5 seconds and you're using an engineering inducer.

**Comment by Barhandar** [comment]
>although i can make beam rifle damage calcs keep blazing oil in mind.

Seriously? How about making blazing oil actually function at negating ALL OTHER SOURCES OF BURN DAMAGE?

**Comment by Tlaltecuhtli** [comment]
its not real burn damage it just makes explosions

**Comment by kevinz000** [comment]
@Tlaltecuhtli the explosion is just a visual and a simulation the real damage is still burn
@Barhandar hell fucking no even replicating foam doesn't get full immunity.

**Comment by kevinz000** [comment]
infact blazing oil isn't supposed to be /the/ burn counter, it's supposed to counter FIRE. Make it more useful in setting things on fire.

**Comment by Barhandar** [comment]
It's supposed to counter the one thing that station is liable to actively prevent usage of due to friendly-fire?

**Comment by Shadowflame909** [comment]
Blobs need a buff. They're a easy 1 hit win meme now. Especially now that they're only an event that happens once the crew gets late game loot and countered all of there antags. Robust crew, versus a weak blob.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/044a626dc3836d6bf74a9d2c3a51c79fbfc26394/code/modules/antagonists/blob/blobstrains/blazing_oil.dm#L20-L28

This is a feature and intentional.

**Comment by Shadowflame909** [comment]
Necromancer!!! Run for your lives!!
