### ISSUE TITLE
AI can't open glass doors / windoors + Levers, door buttons, showers, upload, disposal bins

### ISSUE THREAD

**Issue by Davidj361** [tgstation/tgstation#37103]
AI still can't open glass doors / windoors. Apparently it got fixed recently, but it still doesn't work.

>Other things that have lost AI act:
Levers
Door buttons (the kinds on virology and xenobiology)
Showers
AI/Cyborg Upload (for the purposes of selecting whose laws to alter)
Disposal bins (Haven't tessted this one recently, put it as a maybe)

>I can confirm disposal bins.

**Comment by ShizCalev** [comment]
@kevinz000

**Comment by Davidj361** [comment]
I searched "ai glass doors" no results popped up.

**Comment by Anonmare** [comment]
Other things that have lost AI act:
Levers
Door buttons (the kinds on virology and xenobiology)
Showers
AI/Cyborg Upload (for the purposes of selecting whose laws to alter)
Disposal bins (Haven't tessted this one recently, put it as a maybe)

**Comment by pigeonsk** [comment]
I can confirm disposal bins.

**Comment by SpaceManiac** [comment]
#36730

**Comment by kevinz000** [comment]
buttons should not be only physical, working on it.
