### ISSUE TITLE
Drones cannot mine things by walking into them with mining tool held in hand

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#37105]
Issue reported from  Round ID: 86331 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])  
Reporting client version: 512

They have to click manually.

**Comment by Durkel** [comment]
Why would a drone be off station mining anyway?

**Comment by Barhandar** [comment]
Why would it not? Ahelping confirmed that drone autism fortress on mining is within rules as long as no mobs are touched.
