### ISSUE TITLE
Floor is Lava is lethal to AIs for no good reason

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#37118]
Usually silicons can ignore heat and fire damage, and AIs can't get on a table, so why is the floor is lava event deadly to AIs?

**Comment by DaxDupont** [comment]
I swear I saw an issue about this before and it was fixed somehow.

**Comment by praisenarsie** [comment]
> When lava first breaks through Earth's surface, it is an extremely hot liquid. On average, fresh lava can be between 1,300° F and 2,200° F (700° and 1,200° C)! 

> Steel is just the element iron that has been processed to control the amount of carbon. Iron, out of the ground, melts at around 1510 degrees C (2750°F). Steel often melts at around 1370 degrees C (2500°F).

not that far off, it would surely burn the circuitry inside.

**Comment by YakumoChen** [comment]
it would also instantly kill humans but we don't do that for balance reasons either.
