### ISSUE TITLE
Bluespace launchpads can be used to escape Syndicate HQ as a nuke-op

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#37111]
Title,
Tested locally using a (very) recent version of TG
Related to issue #31429

A bluespace launchpad can be used to warp from either the Syndicate infiltrator ship or the drop pod to leave the base without having to pick up anything from the station.

[https://i.imgur.com/54h0Gnu.png](https://i.imgur.com/54h0Gnu.png)

Consequences of Ops stealing from the rest of the z-level are both extreme and obvious.
_No fun allowed.jpg_

**Comment by Tlaltecuhtli** [comment]
can it reach anywhere significant?

**Comment by DaxDupont** [comment]
So that's how that syndrone escaped the Thunderdome one time

**Comment by 81Denton** [comment]
>can it reach anywhere significant?

Probably the ERT armory, ayy ship, wizard shuttle and lots of other fun as well
