### ISSUE TITLE
Syndicate lava base turbine doesn't output power

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#37127]
Issue reported from  Round ID: 86356 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

>set up engine
>proper pressure and what not
>power generated = 0

**Comment by 81Denton** [comment]
I have no clue why, but most times it starts generating power after opening the aux exhaust blast door.

**Comment by Jalleo** [comment]
I have waited up to 20 odd minuites and repipe how the air mixes to get it working.

**Comment by Cyprex** [comment]
Tested once, worked for me without problems.

**Comment by Jalleo** [comment]
@Cyprex how did you start it up?

**Comment by 81Denton** [comment]
I haven't seen this issue occur anymore in the last couple of weeks. Anyone else?

**Comment by 81Denton** [comment]
This issue hasn't appeared again in 6+ month, I'm closing this.
