### ISSUE TITLE
Radiation collectors can't be constructed or deconstructed

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#37128]
What it says in the title: You can't deconstruct rad collectors or build new ones (no circuit boards exist either).

Also worth mentioning that they wrench/unwrench instantly unlike pretty much any other machinery.

**Comment by DaxDupont** [comment]
I think the building part is intended, unwrenching probably not.

**Comment by Anonmare** [comment]
Honestly I think them being unbuildable is basically everyone thinking it's meant to be that way because legacy code or some reason

**Comment by 81Denton** [comment]
Probably the same with the PA yeah

**Comment by SpaceManiac** [comment]
Can't you order rad collectors from cargo?

**Comment by 81Denton** [comment]
You can order them, but being able to construct them would be nice for building engines.

**Comment by Jalleo** [comment]
Thats because its very oldcode. Pre r4407 with both PA and rad collector.
