### ISSUE TITLE
Airlocks/pod doors/shutters have no rad_insulation?

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#37133]
Either I'm reading this wrong, or airlocks have absolutely zero rad insulation.

Simple metal walls, mineral doors and even girders have insulation, but this space age airlock reinforced with plasteel doesn't. Or pod doors for that matter.

**Comment by praisenarsie** [comment]
@ninjanomnom

**Comment by ninjanomnom** [comment]
![image](https://user-images.githubusercontent.com/1234602/38669381-36868b58-3e14-11e8-9d71-43c0d5945cd8.png)
You're reading it wrong

**Comment by ninjanomnom** [comment]
Please don't make issues that are effectively just questions
