### ISSUE TITLE
Syndie lavaland engineering gets irradiated by incinerator

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#37134]
Using the syndie lavaland incinerator will eventually produce tritium, which in turn will irradiate the hell out of the engineering room and will make it uninhabitable (easily 100 to 200+ rads).

This is an issue because the base has no radsuits available.

Solutions I could think of are either 1) adding a radsuit closet or 2) giving plastitanium walls better rad insulation (aren't they supposed to be these super advanced walls that reflect lasers anyway?).

**Comment by Kromgar** [comment]
Plastitanium is super advanced but can be cut down by a welder. Seems like a consistency issue

**Comment by Barhandar** [comment]
Plas-x alloy walls should be equivalent to rwalls IMO, not to regular ones with fancy plating.

**Comment by Tlaltecuhtli** [comment]
literally diamond walls can be cut down with a welder

**Comment by Jalleo** [comment]
@Anturk

**Comment by AnturK** [comment]
Not sure why you're pinging me, this is basically mapping issue ?

**Comment by Jalleo** [comment]
Its a radiation issue. I didnt think to ping @ninjanomnom for their advice.

**Comment by ninjanomnom** [comment]
As antur said this a mapping issue, I don't know why you're pinging me here

**Comment by Jalleo** [comment]
Sorry.
