### ISSUE TITLE
Borgs can buckle mobs to things, but can't unbuckle them

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#37131]
Borgs can buckle mobs to things (chairs, beds etc.), but can't actually unbuckle them. The borgs I've watched usually just smashed the chairs they buckled someone to earlier.

**Comment by Jalleo** [comment]
@Anturk how should this be resolved or would you say its intended?

**Comment by ninjanomnom** [comment]
Let them do neither imo

**Comment by AWalton** [comment]
This is a huge issue for the new Stasis Beds replacing Sleepers change. There's no way for medical cyborgs to treat patients without another human present.

**Comment by carlarctg** [comment]
ree

**Comment by optimumtact** [comment]
spamming the issue won't fix it @carlarctg knock it off.
