### ISSUE TITLE
viruses permanently gain scanner invisibility if the stealth level is ever over 2

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#37145]
ok so basically if you get a virus to over a stealth level of 2, it keeps the invisibility even if the stealth level goes below 2. if i need to explain this again please let me know

**Comment by imsxz** [comment]
needs reproducing im not entirely sure thats what happened but im FAIRLY sure

**Comment by Kingtrin** [comment]
Round ID - 86440

Viruses are supposed to show when stealth is below 2, but currently the virus will only show when it is below 0. Tested this with a healing virus with stealth values of 1 and 0. Neither showed up. On the same day earlier rounds with negative stealth values had HUD displays. Others reported the issue infrequently within the past week but I have only confirmed it now.

**Comment by davethwave** [comment]
I think this happened when created a super virus on sybil during the ash lizard tendril invasion about 12 hours back.
