### ISSUE TITLE
Abductors can screw over traitor AIs too easily

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#37143]
>Teleport into AI core right on top of rogue AI
>Laugh as it can't do anything against you
>Card+wipe/Saw it to death

>inb4 >salt

**Comment by Kromgar** [comment]
You didn't even mention we abducted you to our ship

**Comment by iskyp** [comment]
this seems like an admin issue, although it'd be pretty easy to blacklist the AI core from teleportation if we want to go down that route

**Comment by cyclowns** [comment]
@iskyp we already do that for clock cult teleportation so it works fine here I think

**Comment by Ratvar** [comment]
Give them the same blocks clockcultists get?

**Comment by kriskog** [comment]
Not a bug, policy discussion on the subject also concluded this is fine.
