### ISSUE TITLE
Voice Analyzers cannot trigger armed C4

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#37153]
Reproduced on a recent clone of the server

[Reproduction]: Attach a voice analyzer with an input to either wire on a C4 (both cause detonation when pulsed) and deploy the C4 with a large timer. Saying the trigger word will not detonate the C4 early.

This seems to be an inconsistency, as remote signaling devices are capable of triggering a C4 early, and voice analyzer are able to pulse wires in APC's and doors. In addition, voice analyzers are able to trigger unarmed C4.

**Comment by Tlaltecuhtli** [comment]
try these: 
1 put proxy sensor on wire
2 put voice on bolt door
3 put proxy sensor on bolt door
if any of these work tell me

**Comment by AlexTheSysop42** [comment]
voice works on bolt door, proxy doesnt work on bolt door

**Comment by Barhandar** [comment]
Proxy doesn't work at all in my experience.

**Comment by SpaceManiac** [comment]
See #27235 for proxy sensors, they are long-broken.

**Comment by AlexTheSysop42** [comment]
Assemblies in general are iffy/broken too, I've tried a voice analyzer + signaller before and it didnt work
