### ISSUE TITLE
Runtime condenser stopped working after rust logging PR

### ISSUE THREAD

**Issue by vuonojenmustaturska** [tgstation/tgstation#37155]
https://tgstation13.org/parsed-logs/basil/data/logs/2018/04/12/round-86394/runtime.condensed.txt vs 
https://tgstation13.org/parsed-logs/basil/data/logs/2018/04/12/round-86394/runtime.txt

This is because the runtime condenser looks for a line with `runtime error:` on the first 14 characters, but with rustg the lines have a timestamp like `[2018-04-12 06:17:18.979] runtime error: Cannot read null.z`

@MrStonedOne @neersighted

**Comment by Tlaltecuhtli** [comment]
intended

**Comment by MrStonedOne** [comment]
That's not it

The actual line reader function pre-strips all timestamps, this just needs to know the new format.

anywho, i'll fix this when I can, but it should be easy to fix https://github.com/tgstation/tgstation/blob/master/tools/Runtime%20Condenser/Main.cpp#L123
