### ISSUE TITLE
[Meta] Morgue doors are too high security for no reason

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#37150]
The morgue doors in meta's medbay are Centcomm doors, have a gigantic health pool for no reason, they aren't even guarding anything that interesting (corpses?), it doesn't make any real sense.

**Comment by XDTM** [comment]
It's guarding us _from_ the corpses

**Comment by Tlaltecuhtli** [comment]
i think zombies have no problem break those doors

**Comment by AlexTheSysop42** [comment]
Are you sure it isn't just cosmetic?

**Comment by ShizCalev** [comment]
It's intended as cosmetic, think someone didn't realize that they had 
	normal_integrity = 1000
	security_level = 6
	explosion_block = 2

as well as trigger phobias.

**Comment by 81Denton** [comment]
>as well as trigger phobias

That would explain all the cases of "why the hell am I having random panic attacks?"

**Comment by Bombpants** [comment]
What phobias does it trigger?

**Comment by ShizCalev** [comment]
@Bombpants https://github.com/tgstation/tgstation/blob/89a46677d060556ff8a178e1266a1090fbddfe86/code/controllers/subsystem/traumas.dm#L78-L90
