### ISSUE TITLE
Miner borgs still lack mesons 

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#37151]
Mining Cyborgs had mesons way back before we nerfed Lavaland to make mesonvision not work, and we removed mesons from them to keep up with this feature.

Despite the fact that change has since been reverted, miner cyborgs have not had their meson module re-added to bring them back in line for how lavaland worked originally.

**Comment by Barhandar** [comment]
Similarly, engies' combined scanner goggles still have meson mode shut off on entering lavaland even though all other meson sources work fine.

**Comment by 81Denton** [comment]
https://github.com/tgstation/tgstation/blob/206c66def9e163c1f049380dd6e267ab875d9ece/code/modules/clothing/glasses/engine_goggles.dm#L64

Why does this garbage even exist

**Comment by SpaceManiac** [comment]
Engineering goggles' meson mode doesn't make things fullbright anymore, so the restriction could probably be removed.

**Comment by 81Denton** [comment]
@ExcessiveUseOfCobblestone I forgot that mesons used to make everything fullbright, huh.

**Comment by ExcessiveUseOfCobblestone** [comment]
how the times have changed lol

**Comment by CosmicScientist** [comment]
I thought it was to obscure ruins, not to preserve atmosphere?

**Comment by ExcessiveUseOfCobblestone** [comment]
that too

**Comment by vuonojenmustaturska** [comment]
You guys forgot mining drones used to have mesons too, for shame
