### ISSUE TITLE
Stargazer's and their liver problems

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#37164]
[Round ID]: # 86418

[Testmerges]: #37039: 'testing new icons for webs!' by Armhulen at commit 5ad857
#37024: 'Puts some brakes on the Cult Train' by Robustin at commit 3a5c2d

[Reproduction]: I was a stargazer so be that, eat 2 warm donk-pockets, realize your getting tox damage, head to medical and down 20u of toxin, then wonder how the heck you died.

As this has not happened to me before I will take a guess and blame this pr that was merged recently.
https://github.com/tgstation/tgstation/pull/37032

**Comment by Barhandar** [comment]
Not only stargazers. Nonlethal amount of chloralhydrate now kills humans too due to lol liver damage, a bit of a problem when wanting to subdue criminals.

**Comment by YakumoChen** [comment]
isn't stargazer a type of slime? Slimes take tox damage from anti-tox sources like omnizine.

**Comment by ExcessiveUseOfCobblestone** [comment]
> fixes liver
> it’s actually not balanced

Darn you tacolizard...

**Comment by 81Denton** [comment]
I did some testing, that's only the tip of the iceberg.
1) Peace borg dizzying/tiring solution give people liver damage and kill them
2) The fucking SLEEPY PEN kills people
3) Mindbreaker toxin and other non-damaging toxin_reagents kill people
4) TOXINLOVER species die the same way when they ingest any toxin
