### ISSUE TITLE
Voice change virus: Trans 14 symptom is unobtainable

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#37160]
To quote a guy from discord:
Voice change's scramble_language symptom requires transmission speed 14, which is unobtainable.

Sneezing + inorganic bio + VEA + alopecia + coughing + voice change = 13 transmission speed with 6 symptoms.

**Comment by Alomga** [comment]
Actually, it is possible, voice change has transmittability of 2, wiki has outdated informations so if anything, that's the problem we're having.

**Comment by 81Denton** [comment]
Oof

**Comment by Barhandar** [comment]
Archibald Kiln says it's perfectly possible.
