### ISSUE TITLE
Tactical cryo cell clickdrag

### ISSUE THREAD

**Issue by zaracka** [tgstation/tgstation#37184]
Clickdragging someone into cryo cells can be used mid-combat to restrain someone. The person being clickdragged does not need to be adjacent to the cell. They only need to be adjacent to the person doing the clickdragging. Resisting out of cryo cells takes 30 seconds. If you are hurt and the cell is turned on, you will be put to sleep. Resisting out of other machines, like DNA scanners and sleepers, acts instantly.

This has been around for as long as I can remember. I believe I am the one who initially discovered and spread knowledge of this, so please do not get mad at me for reporting it. I have personally used it on changelings, Syndicate traitors, and nuclear operatives.

Click on someone while they are standing still and do not let go. Wait for them to get within range (adjacent) of you. Move your cursor to the cell and let go. Essentially, you do not need to aim your cursor mid-combat. Make sure you have them "clicked," stand still to bait them into getting close or do it while they are chasing you, perform tactical cryo cell clickdrag. If you do not have them "clicked," your best bet is to run in circles until you do.

Feature or bug?

**Comment by Barhandar** [comment]
"Easy" fix: make instant cryo require incapacitation or help intent for the one getting stuck into it.

**Comment by PKPenguin321** [comment]
No, the easy fix (and the proper one) is putting a brief do_after on putting people into the thing.
