### ISSUE TITLE
Basic Pathfinder

### ISSUE THREAD

**Issue by robbym** [tgstation/tgstation#37181]
Observe: http://prntscr.com/j4v5dq

Setting the basic pathfinder target to the robust coffee and pulsing it.
Result: http://prntscr.com/j4v69q

Intended behavior or bug?

**Comment by robbym** [comment]
It looks like `/proc/get_step_towards2` only scans perpendicular to the blocking turf. It seems like this is intended by what `/proc/get_step_towards2` actually does, but is this what we want?

**Comment by robbym** [comment]
Why not use the A* path? It shouldn't be too intensive based on the fact that the ref has to be in view, making it a relatively short path solve.

**Comment by arsserpentarium** [comment]
1. It is intended behavior. It have simple algorhythm to avoid obstacles(which can be toggled off with second pin. It is still relatively dumb, throught. It can avoid mostly pillar-type obstacles.
2. A* for every step? U mad?

**Comment by ExcessiveUseOfCobblestone** [comment]
> A* for every step

what did he mean by this?

**Comment by robbym** [comment]
Yeah, I know it sounds pretty intensive, but with small distances, it should be ok no?

> what did he mean by this?
Well if one were to use A* for the basic pathfinder, you'd have to calculate the entire path every time you ran it and just the use the first element in the list. Which is extremely inefficient and costly. My argument is that the basic pathfinder relies on the fact that the target has to be in view, meaning a small path to calculate.

I don't like the idea of calculating A* every step either, but I can't see anothing solution around this. (Other than changing my circuit to use adv pathfinder)

**Comment by arsserpentarium** [comment]
No.Not OK.It may help if we add better obstacle avoiding mechanism in basic one.Like left/right arm rule.
But for any clever pathfinding you'll need adv PF.

**Comment by robbym** [comment]
What about implementing a jump point search?

**Comment by arsserpentarium** [comment]
won't work.It's based on assumption, that tile check is far faster, then Open/closed lists fuckery.If you'll investigate, JPS check far more tiles than a*,yet saving sorting time.
I've managed to remove closed list completely.But slowest part is tile check. It iterates throught all the contents with shitton of can_astar_pass proc calls.
Most sad thing, thaat I didn't managed to do something with it.
Lummox told, that my alghorhytm can be improved,if we'd change data representation, taking in account byond magic.Because list calls faster, than datum var interaction.

You could try anyway.

**Comment by ninjanomnom** [comment]
This is intended functionality, if you want true pathfinding you need the advanced version.

**Comment by robbym** [comment]
What about beam search with max depth of like 10? I feel like the problem depicted in the pictures I posted should be able to be solved by the basic pathfinder.

**Comment by robbym** [comment]
Would it help if we switched from propagating down a huge call tree to a loop with a queue?

**Comment by arsserpentarium** [comment]
Could you explain your suggestion better?

**Comment by arsserpentarium** [comment]
So you suggest to emulate call stack INSIDE byond?Just with queue , instead of stack?
Did you know, that there aren't big diference in performance between stack and queue?

**Comment by robbym** [comment]
No, that's not what I am suggesting at all. Its the same idea as taking a recursive function and transforming it into an iterative one.

And no, that's wrong. There is definitely a performance difference between a stack and a queue if they are implemented correctly. The LIFO nature of a stack is much more efficient because its just a vector (in C++ terms), and pushing elements on and off the end of the vector is super cheap. A queue on the other hand basically requires two stacks and some juggling during the enqueue or dequeue step.

Now, if you implement both of them with a linked list and doubly linked list respectively, that's a different story. Cache misses for days.

I do not know the internals of the BYOND VM, but I would hope its using a vector-like data structure to utilize the cache.

**Comment by robbym** [comment]
Also, having a queue instead of a propagation tree allows you throttle the circuit easily.

**Comment by robbym** [comment]
It does have associations, so maybe its using a hashtable internally. Or maybe a variant of many list types and it chooses which ever is more efficient at the time. No idea.
