### ISSUE TITLE
Cyborgs can be put in cryo cells

### ISSUE THREAD

**Issue by zaracka** [tgstation/tgstation#37185]
Have the cyborg on the same tile as the cryo cell and close it through the UI. You can turn it on at this point. If the cyborg is damaged, it will be put in a never ending sleep until the cryo cell is turned off. The cyborg will not heal, but it will snore. It will take just as long as humans to wake up after coming out.

**Comment by Anonmare** [comment]
You can also use *emotes like *faint as a cyborg to give yourself a permanent sleeping indicator
