### ISSUE TITLE
Bluespace cookies can warp you to the Centcom z-level

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#37187]
Title,

The cookies made by feeding bluespace consuming extracts can allow teleportation to the centcom z-level when used in space.

To reproduce, do xenobiology until you have silver and bluespace slimes, feed silver extracts to an adult bluespace slime until it becomes a bluespace consuming extract, feed it with random food until you get a bunch of cookies, grab EVA gear, GPS, as many cookies as possible and start eating them in space until you wind up in places you shouldn't.

Obviously bad because CentCom should not become the local Toy-R-Us store for high-tech prototype hardware, and neither should the neighboring areas.

WJohn encouraged me to still report this, even though I had hoped it could've lived on as the _Secret Cookie Technique._
_(Insert Cookie_Monster.jpg here)_

**Comment by vuonojenmustaturska** [comment]
The bluespace cookie code has some rough edges, fixing
