### ISSUE TITLE
Storage requirements are broken

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#37186]
Revision b7af6c169b0d358bb37aae64cc89ab7649573415

Anything smallish fits in the RPED, power cells and materials fit in toolbelts, etc.

@kevinz000

**Comment by YakumoChen** [comment]
powers cells are intended as they are an upgradable.

**Comment by Jalleo** [comment]
Power cells are meant to fit in RPEDs. If cigs do that is a issue.

**Comment by SpaceManiac** [comment]
All requirements are broken. Toolbelts can hold anything below their max weight class, jackboots can hold anything below their max weight class, etc.
