### ISSUE TITLE
Show server log/show attack logs is missing

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#37180]
Issue reported from  Round ID: 86447 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

It seems the verbs got removed and now I need to use get server log and navigate through several folders to get to the logs for this round. For each seperate log file too.

Can those verbs be brought back or can there be a get current logs verb that opens the get server logs window in the current round folder?

**Comment by Cyberboss** [comment]
@neersighted
