### ISSUE TITLE
you can shoot your own bullets

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#37200]
Issue reported from  Round ID: 86510 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512
http://take.ms/WCQex

moving and shooting forward

**Comment by WJohn** [comment]
Cannot reproduce. Might only happen when the round is very, very laggy.

**Comment by ShizCalev** [comment]
Unable to repo
