### ISSUE TITLE
Opening SSU wire panel attacks it

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#37210]
Revision: 2570384371bd9a92cedb1db979c52a0e13128193

Opening a SSU's (/obj/machinery/suit_storage_unit) wire panel by using a multitool/wirecutter on it causes you to attack it once before the TGUI wire panel opens.

**Comment by Anonmare** [comment]
This is fixed as of #39780

**Comment by 81Denton** [comment]
noice

**Comment by 81Denton** [comment]
noice

**Comment by BootlegBow** [comment]
If this got fixed 2 years ago why is the issue still open
