### ISSUE TITLE
Centcom officials don't get their custom mission assigned to them

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#37226]
Issue reported from  Round ID: 86540 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

1.  Create Antagonist
2. Press response team
3. Select official
4. Input custom mission.
5. Ok
6. They spawn without the custom mission objective and have the default instead.

**Comment by vuonojenmustaturska** [comment]
I'll fix it
