### ISSUE TITLE
[ATMOS (?)] "air" mix suffocates you

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#37228]
The default air canisters will make you suffocate to death if you fill a tank with them. I'm not sure if this is like intended or an atmos change broke it but it's really annoying.

**Comment by vuonojenmustaturska** [comment]
This is because you are using the portable tanks with the release pressure set to 16 kPa, which works for pure O2 but doesn't work for 8/2 N2/O2 mix. When you breathe, only the "oxygen pressure" matters, you will be able to breathe the air tank air with a release pressure of 80+ kPa.

**Comment by Spaceinaba** [comment]
oh I see I just schooled myself
