### ISSUE TITLE
Something caused the chemistry dispenser to dispense acid, but only once. For some reason it kept adding overlays recursively.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#37227]
Issue reported from  Round ID: 86542 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Something caused the chemistry dispenser to dispense acid, but only once. **For some reason it kept adding overlays recursively.**

![ariizvz 1](https://user-images.githubusercontent.com/17237624/38779796-a78ed83a-40cd-11e8-8aab-00936857474e.png)

I think it was an EMP or the malf AI.

Potentially acid level wasn't set. I've seen this happen before, so it's probably not related to the test merges.

The following pull requests are currently test merged:
#37202: 'Fixes cat parts not showing up in perfs.' by DaxDupont at commit eef589
#37024: 'Puts some brakes on the Cult Train' by Robustin at commit 2096a4
#36866: 'refactors overlays to append/remove individual overlays instead of cutting' by Robustin at commit 01f139
#36890: '[TESTMERGE ONLY] getFlatIcon performance!' by kevinz000 at commit 03ca5d

Based off origin/master commit: a859eb

**Comment by Robustin** [comment]
What do you mean by dispense? It looks like the Xeno acid effect, I need to see what causes this to happen so I can figure out what overlays are involved.

**Comment by vuonojenmustaturska** [comment]
I'm thinking someone had made a couple bottles of acid, they were on the chem master and then the guy working on the other machine below discovered potassium and water

**Comment by Robustin** [comment]
Its not an EMP as far as I can tell. I just emptied multiple boxes of EMP grenades onto the dispenser and the "glowing goo" was its own decal, it didnt create any overlay on existing objects.

**Comment by timothymtorres** [comment]
Issues #36936, #44100, #38820, and #37227 all seem to be related to a BYOND bug that was fixed at some point since there haven't been any recent issues involving overlays in the past few years.  

Going to go ahead and close them all.
