### ISSUE TITLE
ABSTRACT_1 and NODECONSTRUCT_1 in __DEFINES/flags.dm share the same bitflag

### ISSUE THREAD

**Issue by pigeonsk** [tgstation/tgstation#37230]
I don't know if this is actually a bug that affects gameplay in any way but I also don't know if I'll have time to thoroughly investigate this so I'm posting it here. If it's intended it definitely feels wrong and evil.

**Comment by SpaceManiac** [comment]
Current, not double-checked thought: `ABSTRACT_1` applies only to `/obj/item` and `NODECONSTRUCT_1` applies only to `/obj/machinery`

**Comment by vuonojenmustaturska** [comment]
`flags_1` is pretty nastily reused for different contexts, there's a completely different set of meanings for the flags for turfs as well, for example `NOJAUNT_1` is the same as `STOPSPRESSUREDMAGE_1`.

AFAIK the thing with `ABSTRACT_1` and `NODECONSTRUCT_1` is that the former is the generic flag and `NODECONSTRUCT_1` is for `/obj/machinery`, as there are no abstract machines. I've been meaning to give the flags another pass after the freeze is over, moving turf flags to their own bitfield and packing in some excess booleans in the style of #34063

**Comment by pigeonsk** [comment]
\>a bitfield named only as flags
\>unrelated flags are shoved in to the point we've reached a flags\__n_ scheme
I'll do some flag moving after my bitflag refactor PR is closed

**Comment by Cyberboss** [comment]
I hate flags because of this reason and will infinitely prefer something strongly typed such as components

**Comment by vuonojenmustaturska** [comment]
We discussed this briefly on #coderbus and it looks like we could remove flags_1 and flags_2 by moving stuff into obj_flags and item_flags (which already exist) and making machinery_flags and turf_flags (which don't). There are only two /atom level flags right now, at least one of which might be unneeded. We can punt them into datum_flags, we have room there.

**Comment by XDTM** [comment]
I think this is fixed now
