### ISSUE TITLE
Mechs are immune to time stop

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#37249]
[Round ID]:  86594
[Round ID]: # (**INCLUDE THE ROUND ID**)

[Reproduction]: Try timestopping a ripley they can still act and fire their plasma cutters

MECHS ARE NOT GOLEMS AND ARE THUS NOT MAGIC IMMUNE REEEEEEEEEEEEEEE

**Comment by Kromgar** [comment]
Should affect the pilot in the mech at the least

**Comment by Tlaltecuhtli** [comment]
slime timestop for sure

**Comment by Kromgar** [comment]
Oh wizard time stop
