### ISSUE TITLE
Emitters hit things they're not supposed to

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#37247]
Issue reported from  Round ID: 86587 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512
Emitters hit multiple things on the same time even when not supposed to
[Reproduction]: 1. Setup emitter
2. Setup disposal junction under supermatter
3. Fire emitter at supermatter
4. Disposal junction breaks
5. Trash gets spewed out at the supermatter

**Comment by praisenarsie** [comment]
@kevinz000

**Comment by ShizCalev** [comment]
Dupe of #21203 ?

**Comment by timothymtorres** [comment]
This apparently was fixed by kevinz.  

See - https://github.com/Citadel-Station-13/Citadel-Station-13/pull/10125
