### ISSUE TITLE
MetaStation cargo shuttle conveyor wrong way around.

### ISSUE THREAD

**Issue by MIC132** [tgstation/tgstation#37248]
The bottom (into-shuttle) conveyor on the shuttle itself is wrong way around (pushing outside) causing crates to bounce back-and-forth between it and the station conveyor.

This is on MetaStation.

**Comment by SpaceManiac** [comment]
Box and Meta share a shuttle, either Box needs to change to `verted = 0` on the conveyors or Meta needs `verted = 1`.
