### ISSUE TITLE
The TTV won by beating an emagged arcade machine has an ineffective mixture

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#37259]
Title, beating Cuban Pete from an emagged arcade machine gives you a TTV bomb, however the mix used in the TTV no longer results in an explosion when the valve is opened.

Confirmed on Sybil - Round ID: 86605
Revision: 81e965bcf8a1b82e494d1d653cdbdc63136d575d

To reproduce: Be traitor, emag a battle arcade machine, outbomb Cuban Pete and win a TTV and Cuban pete hat, open the TTV valve, nothing happens other then the tanks rupturing after awhile.

Probably borked as a result of #37116

**Comment by 81Denton** [comment]
https://github.com/tgstation/tgstation/blob/395c0ee6a0a59f8bcc2ffc8ad0b11f2d6e198f32/code/game/objects/effects/spawners/bombspawner.dm#L5-L6
https://github.com/tgstation/tgstation/blob/395c0ee6a0a59f8bcc2ffc8ad0b11f2d6e198f32/code/game/objects/effects/spawners/bombspawner.dm#L37-L38

My best guess is that those temps have to be adjusted.

**Comment by SgtxRootbeer** [comment]
It's been like this for over a year noe

**Comment by ma44** [comment]
Probably related to #23024

**Comment by Anonmare** [comment]
Explosions are dependant on mole counts more than anything, may wanna check them first

**Comment by ma44** [comment]
According to the tanks, they both have gases put into them on initialize, probably has to do with the temperatures or something.

**Comment by ExcessiveUseOfCobblestone** [comment]
It just seems like a fruitless endeavor to have to constantly check this uncommon item everytime atmos code gets changed to ensure the desired bomb effect is retained.

**Comment by chesse20** [comment]
yea just have a bomb that's just coded to be max cap like the other guy said
