### ISSUE TITLE
Experimentor sometimes breaks, only fixed on reconstruct

### ISSUE THREAD

**Issue by xenon-difluoride** [tgstation/tgstation#37254]
Issue reported from  Round ID: 86600 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

After repeatedly experimenting on something, it goes into a state where it is permanently on cooldown, only fixable when reconstructed, but that rerolls experiments making it impractical to do so.

**Comment by AlexTheSysop42** [comment]
Ok, it seems to only happen with the toxic waste malfunction\

**Comment by Sealed101** [comment]
was fixed in #37822
