### ISSUE TITLE
SCP Ruin - Turret & Mob Factions are incorrect

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#37253]
Issue reported from  Round ID: 86598 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512
the mobs and the turrets fight at round start because they have different faction and also trigger all the traps really shitty ruin i ll add

**Comment by ExcessiveUseOfCobblestone** [comment]
@ShizCalev

**Comment by Kromgar** [comment]
Also the ids dont protect you from turrets

**Comment by Armhulen** [comment]
why don't we just remove it

**Comment by praisenarsie** [comment]
that will just encourage admins to spawn the machine every round

either remove it completely or fix the ruin

**Comment by PKPenguin321** [comment]
shit issue title

**Comment by YakumoChen** [comment]
clearly a feature if the turrets are preventing [redacted] from [reacted] due to a containment breach, the automated [redacted] systems are designed to [redacted] in situations like this.
