### ISSUE TITLE
Trying to humanize a split personality instead humanizes the host

### ISSUE THREAD

**Issue by EmptyLullaby** [tgstation/tgstation#37255]
I forgot the round id and stuff but like I tried to spawn myself to do something after I was a split personality who got removed from the host and it turns out when you try to humanize yourself it instead puts the real personality in your body and leaves you as a ghost

**Comment by XDTM** [comment]
Since the monkey transformation destroys the human, spawns a monkey, and copies some vars, i'm afraid that's pretty much the best outcome you can get. At least split personalities can't get permanent control with this.

**Comment by timothymtorres** [comment]
This issue is really light on details which makes it nearly impossible to troubleshoot.
