### ISSUE TITLE
Phazon phasing + strafing doesnt work

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#37269]
you move in the direction its facing instead of the arrow key you pressed

**Comment by Rinoka** [comment]
it's strafing

phasing, though. which spell? for clarity

**Comment by Barhandar** [comment]
I don't know _anything_ that can strafe other than mechas so pretty sure they mean Phazon.

**Comment by Rinoka** [comment]
@Barhandar i don't either but i also don't know if anyone added strafing in the last month or two to something else so i wanna be sure

anyway this's in mecha.dm:575

>if(phase_state)
>flick(phase_state, src)
>forceMove(get_step(src,dir))
>use_power(phasing_energy_drain)

not familiar with movecode but i get the feeling that dir might be sent wrong
