### ISSUE TITLE
Feeding Reproductive Slime Extracts with Biobag tries to pick the extract up and fails

### ISSUE THREAD

**Issue by KomradeSpectre** [tgstation/tgstation#37264]
Issue reported from  Round ID: 86625 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Reproduction]: Attempt to use a biobag with monkeycubes in it on a reproductive slime extract. It used to feed it 1 per click about 2-3 weeks back, but now when attempting tries to pick the reproductive extract up and fails.

**Comment by Barhandar** [comment]
>It used to feed it 1 per click about 2-3 weeks back

Mere two days ago, actually.

**Comment by fludd12** [comment]
Ok who broke my child

**Comment by AlexTheSysop42** [comment]
I _think_ this was caused by #36696

**Comment by fludd12** [comment]
I'm pretty sure, but I don't know *why* it happened - @kevinz000 updated the code for the biobags and from what I've looked at it, it *should* work...

**Comment by fludd12** [comment]
I believe this was fixed?
