### ISSUE TITLE
Getting addicted to a drug and kicking the habit will leave you with a permenant mood debuff

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#37277]
[Round ID]: I don't remember

Got addicted to krokodil, kicked the habit but I was still debuffed by the addiction desire. Took krokodil, didn't abate it and I had to die and get cloned to remove it.

**Comment by Tlaltecuhtli** [comment]
also witdrawal debuff keeps persisting even if you took the drugs

**Comment by Ratvar** [comment]
Cloning resets moodlets, huh, time to fix dat

**Comment by Armhulen** [comment]
feature this is just like real drugs

**Comment by arsserpentarium** [comment]
Real drugs works same way.
If you'll get addicted to krocodil and kick habit, you'll get permanent mood debuff with similar cure.
Depressingly real behaviour.
