### ISSUE TITLE
Space Ninja tech disk functionality is broken

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#37275]
How to reproduce: As a Space Ninja, try using a tech disk with research nodes in it on your suit. It's supposed to upload the research, but instead it prints the message "No research information detected." Presumably this is just something that was missed when techwebs was added?

**Comment by Repukan** [comment]
I think you can click the research console with interactive mode on and it steals that way

**Comment by subject217** [comment]
Yeah the gloves interact version works, but the tech disk functionality should still function and is still an issue.
