### ISSUE TITLE
MMIs cannot use Exosuit equipement.

### ISSUE THREAD

**Issue by Gousaid67** [tgstation/tgstation#37285]
Issue reported from  Round ID: 86694 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512
[Round ID]: #86694

[Reproduction]: Shove an MMI with a brain in a mech. And make it try to use the equipement with it, He will not be able to use them.

**Comment by Anonmare** [comment]
I have found a workaround in reconnecting to reinitialise the mech. 

Also AIs use middle-mouseclick for their equipment so make sure that's the button you're using

**Comment by Gousaid67** [comment]
i see, well il change the title to MMIs only for now, but i will be testing wheter AIs can control it

**Comment by Barhandar** [comment]
@Anonmare reconnecting to what exactly? Server? Doesn't work.

**Comment by PKPenguin321** [comment]
I think this is a dupe of a very old issue

**Comment by Gousaid67** [comment]
Well middleclicking doesnt work for MMIs either, so they are their own problem currently

**Comment by Kromgar** [comment]
Weird posibrains work

**Comment by Gousaid67** [comment]
i didnt mention posibrains, as they pretty much work like the AI does. but this doesnt Apply to MMIs.

**Comment by SpaceManiac** [comment]
Fixed by #41167
