### ISSUE TITLE
Metastation's map for the aux base is broken

### ISSUE THREAD

**Issue by ariever** [tgstation/tgstation#37287]
[Round ID]: 86700
metastation's map does have an aux base, but that aux base doesn't have a mining locker, orebox, or even the center console to set it down. One top of that, you cannot build on the auxillary base construction for some reason.

[https://puu.sh/A5X1q/59c8b4df14.png](url)

**Comment by 81Denton** [comment]
Can't reproduce this on localhost Revision: c5bced213c85385884b92ccd9d1c761e88c82de6

https://i.imgur.com/GHaI4sY.jpg

**Comment by Jalleo** [comment]
I confirmed this is fixed
