### ISSUE TITLE
Falsewalls process atmos but only if they're closed....

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#37290]
Title.

@Robustin maybe?

**Comment by Supermichael777** [comment]
I think its because their tile processes it when open?

**Comment by ExcessiveUseOfCobblestone** [comment]
I found this bug while making a falsewall to a room in maint to sabotage atmos.

I noticed things weren't shifting to the opening and checked the pressure and it was actually _rising_. When I closed the falsewall however is when everything shifted to the wall and the room began to get cold and pressure-less.

**Comment by YakumoChen** [comment]
Not a bug, false walls shouldn't let air through. I remember the PR to change it to how it is now.
