### ISSUE TITLE
Fireball randomly deleting my borg modules

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#37291]
http://prntscr.com/j76rhe 

Admin wouldn't help me and I was at full health and they didn't come back. Also at some point my battery deleted itself making me completely useless.

**Comment by Nabski89** [comment]
https://tgstation13.org/parsed-logs/basil/data/logs/2018/04/19/round-86718/

This round.

You never mentioned the bit about your battery being gone as well.

**Comment by kevinz000** [comment]
the real shitty part is contents_explosion already is set to do nothing on /mob/living/silicon, so how is this even happening?

**Comment by YakumoChen** [comment]
@Nabski89 Naw, I did ahelp it as well.

**Comment by Nabski89** [comment]
Oh I guess I just missed/forgot about that part. Sorry.

**Comment by Bluespace** [comment]
I remember this bug, this is an old one, come back it seems.
Shame fireballing humans doesn't delete brains.

**Comment by SpaceManiac** [comment]
Might be related to #34635

**Comment by YPOQ** [comment]
Issue comes from these lines 
https://github.com/tgstation/tgstation/blob/183936d043c18cb904c0cd4eea0d31b9c019e6ec/code/datums/explosion.dm#L198-L205
Which are also causing #36310 and #33175 and possibly more.
It's also causing mech pilots, inventory items, etc. on the epicenter tile to take explosion damage twice.
