### ISSUE TITLE
Regular plating or any fancy floors (i.e. reinforced) that require it cannot be built on lavaland turf

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#37309]
Issue reported from  Round ID: 86775 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])  
Reporting client version: 512

Possible solution: make floor tiles build plating instead of covers.

**Comment by Jalleo** [comment]
yeah you gotta first place plating before placing tiles this is intended I believe.

**Comment by Barhandar** [comment]
It's _not possible_ to place plating on lavaland unless it requires something specialsnowflakey - floor tiles create floors directly and rods don't work. The only way to get some there is to RCD lava.

**Comment by ExcessiveUseOfCobblestone** [comment]
@ninjanomnom I believe you did something with turfs and lavaland?
