### ISSUE TITLE
Nested menus have stopped working

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#37317]
This is a BYOND issue but I can't report without a minimal example and I can't create one without understanding how our menu code works, maybe someone who already does can.

Works in DD 512.1419, broken in DD 1420-1422. DS/DM versions irrelevant.

![image](https://user-images.githubusercontent.com/222630/39082038-42d9eb5e-4501-11e8-9c47-dade73be245b.png)

**Comment by Barhandar** [comment]
I have *512.1413* and I have exactly the same menus as your screenshot on current Sybil round (86815) as an observer ghost. This persists after relog or restarting BYOND and on all three of /tg/'s servers.

**Comment by SpaceManiac** [comment]
Issue appears based on server version, not client version. The servers updated from 1419 to 1422 today.

**Comment by AnturK** [comment]
@MrStonedOne
