### ISSUE TITLE
like all the syndicate ambush ruin ships are broken and only the windows move

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#37329]
round id 86830
self explanitory
![dreamseeker_2018-04-21_12-49-08](https://user-images.githubusercontent.com/20155238/39087196-3bef0326-4563-11e8-9852-3098a00d8280.png)

**Comment by DaxDupont** [comment]
same cause as https://github.com/tgstation/tgstation/issues/36992 I bet, probably needs to be fixed too @ninjanomnom

**Comment by ninjanomnom** [comment]
Yes the shuttles need to be made into templates

**Comment by ninjanomnom** [comment]
They're the same kind of bug but each need to be solved individualy

**Comment by SpaceManiac** [comment]
Fixed by #37474 as far as I can tell
