### ISSUE TITLE
moving diagonally into a disposal chute with an end location outside of it makes your camera stick to the chute

### ISSUE THREAD

**Issue by Teepeepee** [tgstation/tgstation#37323]
[Round ID]: 86825
pretty much what the title says
https://imgur.com/a/CxQWS5m

**Comment by AlexTheSysop42** [comment]
Oh eugh that happened to me once with a transit tube and I thought I was there for like 15 minutes

**Comment by Teepeepee** [comment]
forgot to add: entering the chute correctly (or any other chute) fixes the problem, as well as reconnecting.
