### ISSUE TITLE
Mining shuttle can't go to the aux base construction room.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#37335]
Round ID: 86830

You can't send the shuttle to the aux base construction room once the aux base mining shuttle landing spot is set up, there's no option for it.

**Comment by KomradeSpectre** [comment]
One of the issues underlying this is the fact that the auxbase room doesn't empty to space when you launch. It still has tiles there. This may be a reason behind this.

**Comment by DaxDupont** [comment]
@ninjanomnom

**Comment by ninjanomnom** [comment]
That isn't an issue @KomradeSpectre

**Comment by KomradeSpectre** [comment]
@ninjanomnom I don't know if you play the game at all, but, the behavior it used to have is when you launched the auxbase, it would empty the room the auxbase was constructed at to space so the shuttle could dock there. That's an issue, not an oversight you egg.

**Comment by ninjanomnom** [comment]
No that's not an issue, it was one of the intended changes
