### ISSUE TITLE
Bug: Replica Pods not working.

### ISSUE THREAD

**Issue by USB3pt0** [tgstation/tgstation#37333]
Issue reported from  Round ID: 86833 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Round ID]: # 86833

[Reproduction]: Grabbed a Replica Pod from the servitor.  Took a blood sample from a dead, brainless corpse that did not commit suicide.  Injected it into the seeds and modified potency with the DNA modifier.  Let it grow fully, harvest it...and produces seeds.  Try again, without modification and again, more seeds.  This has been happening quite a bit recently, only saw one pod-person grow properly.

[For Admins]:

**Comment by DaxDupont** [comment]
if they ghost out or something that will cause them to not be podded

**Comment by w779431h** [comment]
I see.  I think the body wasn't ghosted yet.

I assume it gives a warning about it like cloning/positron brain/etc?

**Comment by kriskog** [comment]
Haven't encountered this. can't reproduce. Brain might be in use somewhere else, like an mmi.
