### ISSUE TITLE
Atmos component piping_layer can't be changed by hand

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#37338]
Players can't manually change the piping_layer of atmos components (pipes, scrubbers etc.) - the only option is to create new ones with an RPD or pipe dispenser.

**Comment by SpaceManiac** [comment]
Scrubbers/etc could probably be fixed, but you can change the layer of a pipe by clicking with it on a wrenched pipe or other atmos component of the desired layer.

**Comment by 81Denton** [comment]
Oh darn, I did not know that. I'll close this and reopen one for scrubbers etc. later.
