### ISSUE TITLE
Pandemic layer issue

### ISSUE THREAD

**Issue by pubby** [tgstation/tgstation#37346]
Server revision compiled on: 2018-04-15

Sometimes the Pandemic machine creates bottles beneath it, meaning you can't see them unless you right-click. I noticed this happens mostly on Delta station, so use Delta station when reproducing.

**Comment by ShizCalev** [comment]
could probably tweak the machine's layering to fix this.

**Comment by MIC132** [comment]
Happens with other things too, like tank dispensers.

**Comment by py01** [comment]
Auto lathes also do this sometimes
