### ISSUE TITLE
Radiation collectors are affected by tesla shocks

### ISSUE THREAD

**Issue by pubby** [tgstation/tgstation#37348]
Server revision compiled on: 2018-04-15

The tesla can explode radiation collectors, which is a problem since rad collcetors are now mapped adjacent to the field.

**Comment by Poojawa** [comment]
They really shouldn't be mapped next to the field, but it's the engineer's fault for not moving them before setting up the engine if they ain't using the Singulo

**Comment by 81Denton** [comment]
Can be fixed by adding /obj/machinery/power/rad_collector to
https://github.com/tgstation/tgstation/blob/d7c5fca020c1370a1107877a9f1142ae179c5b4d/code/modules/power/tesla/energy_ball.dm#L176

**Comment by Barhandar** [comment]
Can also be fixed by gitting gud and moving the rad collectors.
>They really shouldn't be mapped next to the field

It's Pubby. It's _full_ of terrible decisions like this.

**Comment by 81Denton** [comment]
>It's Pubby. It's full of terrible decisions like this.

That's a funny way to write Omega

**Comment by pubby** [comment]
Radiation collectors have to be adjacent to the field ever since the radiation rework went in. Putting them in the engine room behind glass does not work anymore.

**Comment by Barhandar** [comment]
>That's a funny way to write Omega

While Omega is terrible, it has SM and not tesgulo.
>Radiation collectors have to be adjacent to the field ever since the radiation rework went in. Putting them in the engine room behind glass does not work anymore.

Then radiation rework is fucking trash.

**Comment by Iamgoofball** [comment]
hey guys

# step 1. get a grounding rod from storage

# step 2. get the tesla coils from storage

# step 3. watch as the lightning bolt prioritizes zapping tesla coils and grounding rods before **anything else**

#wow #whoa 
i fixed the bug guys

@ShizCalev can you close this non-issue

**Comment by Iamgoofball** [comment]
@Poojawa theres some things that need blacklisted for abstracting and game design purposes

**Comment by Poojawa** [comment]
Oh I'm aware. This is one of those times where it isn't, which is why I'm complaining about this being an 'issue' :P

**Comment by Iamgoofball** [comment]
Then someone broke targeting. File a bug report.

**Comment by ShizCalev** [comment]
@Iamgoofball pretty sure this _is_ a bug report

**Comment by GuyonBroadway** [comment]
On hippie we use the "Tesling" setup on box (in addition to the supermatter, and we used to have a system where shocked doors could do 300 damage if you were an insane enough engineer) and all we did was when we had to move the rad collectors post rad update was stick a couple grounding rods by them and called it a day.

To date we've never had a tesla related rad collector explosion incident (if the engineers didn't forget to secure the grounding rods.)
