### ISSUE TITLE
Unable to Harvest Grass

### ISSUE THREAD

**Issue by Alterist** [tgstation/tgstation#37340]
Issue reported from  Round ID: 86837 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

[Round ID]: 86827

[Testmerges]: #37024: 'Puts some brakes on the Cult Train' by Robustin at commit 6bba1f

[Reproduction]: Grow some grass, try to harvest it, I guess

Had a few rounds where people were unable to harvest grass, not sure of the specifics, but it seems like it just won't grow to maturity

**Comment by Teepeepee** [comment]
I've also had this bug happen to me, I blamed gaia trays and gaia dirt plots, planted it on non gaia'd and it grew normally. Not sure that's really it though.

**Comment by ma44** [comment]
I believe maturation speed isn't effected by mutagen, or like any other chemical/mechanic in existence.

**Comment by improvedname** [comment]
Mutaratiom speed IS affected by mutagen

**Comment by Jord1081** [comment]
Just played a round where this occurred. Its not that you CANT harvest grass, its just that it takes forever to harvest the first time SOMETIMES. Even when I play as a podperson with god-plants i've seen the grass reach 30 years without one harvest, but the moment the first one comes through it starts to work fine.

**Comment by LemonInTheDark** [comment]
I swear to god
