### ISSUE TITLE
Sneezing escapes bio suits

### ISSUE THREAD

**Issue by pubby** [tgstation/tgstation#37347]
Server revision compiled on: 2018-04-15

If you're wearing a bio suit and you sneeze, others can be infected.

**Comment by AlexTheSysop42** [comment]
>about to sneeze
>lift up hood to sneeze in arm because hygine
>miss arm

Feature

**Comment by Tlaltecuhtli** [comment]
wouldnt it mean all suits should contain stuff like vomit and sneezing

**Comment by ExcessiveUseOfCobblestone** [comment]
gross!
