### ISSUE TITLE
Ash storm instantly ended??

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#37352]
Round ID: 86847 (I think.)

![a5ywjo9](https://user-images.githubusercontent.com/4581352/39090540-cc086b0c-45d9-11e8-9ef3-ade4fcc5ae30.png)

No idea how this happened. No sound for the storm happened either, I was about to alt tab to do other stuff while waiting and realised it already went.

**Comment by Repukan** [comment]
Did someone use a staff of storms?

**Comment by Onule** [comment]
No idea. As far as I remember, Legion was not summoned/killed, and saw no one with the staff.
Even if it was used, the sound for the storm would've played

**Comment by SpaceManiac** [comment]
Round ID was 86843 and the event appears to have happened approximately 68827ds from roundstart.

Nothing in weather code that should cause this as far as I can tell.
