### ISSUE TITLE
Secways (sometimes) ignore invisible walls

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#37354]
[Round ID]: #86854

[Reproduction]: So in the round, I was playing as mime. An officer on a secway was chasing me, and I used invisible wall to stop them. However, they passed right through it. At the time, I could not check to see if a normal human would be barred from passing through, as I was arrested and carried off in a different direction. Later, me and Virtual John decided to test it out in thunderdome. At first, the secway passed right through, however walking humans couldn't. However, after we tried the traitor only 3x1 invisible wall, the secway could not pass through. So, we tried a normal invisible wall again, and this time the secway WAS blocked from passing through. I'm pretty confused on this one.

**Comment by Tlaltecuhtli** [comment]
law cant be stopped

**Comment by Jalleo** [comment]
It might be depending on how quickly they are created.

**Comment by timothymtorres** [comment]
This had to have been fixed at some point… but it needs to be retested before I close it.

**Comment by KittyNoodle** [comment]
unable to reproduce on up to date testing server

**Comment by wesoda25** [comment]
works for me
