### ISSUE TITLE
Mousetraps do not trigger if you empty a bag by dragging to a tile

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#37357]
Reproduced on a recent clone of the server

By clicking on a container and dragging to an adjacent tile to empty the entire container, you can remove armed mousetraps, mousetrap assemblies, and mousetrap grenades from the container without triggering them. This seems to violate the intended purpose of mousetraps.

**Comment by DaxDupont** [comment]
@kevinz000

**Comment by Tlaltecuhtli** [comment]
uhh well thats the only way to empty a rigged bag i think it should stay like that?

**Comment by Jalleo** [comment]
Nope if its unintended its unintended.
