### ISSUE TITLE
Alien Queen phasing through mining shuttle

### ISSUE THREAD

**Issue by Magnnarot** [tgstation/tgstation#37376]
Round ID: 86907

As a xenomorph Alien Queen born in lavaland I managed to get inside the mining shuttle towards the station and when the ferry started taking me I phased through it and was put into deep space.

Reproduction: Pubbystation, get into the mining shuttle in lavaland as an Alien Queen, start the ferry, possibly get thrown into deep space by phasing through walls.

**Comment by SpaceManiac** [comment]
Could you be more specific with what you mean by "phasing"? If you were centered on a wall tile you could have walked or (in some way) been dragged off that wall tile, exposing you to space. If a door or window was open and you were removed from the shuttle by the throw force of the launch that would also explain being spaced. Is it either of those?

**Comment by Magnnarot** [comment]
There were absolutely no holes in the shuttle aside for the airlock, it was extremely strange, I was near the middle of the shuttle and I simply ended up in deep space, no lag involved or anything, as a gygax was walking in at the time. Situation was so strange an admin teleported me back to the station.

**Comment by Jalleo** [comment]
@Magnnarot what do you mean in regards to towards centcomm? 
as in it was leaving the mining station and going to centcom at the end of the round or that as it was leaving you got onboard and the gygax followed you on and you got spaced once it left to go to the station?

**Comment by Magnnarot** [comment]
@Jalleo My bad, I remember doing this issue report ages ago after a very late night round, didn't even realize the mistake. I meant the station, not centcomm.

**Comment by Dennok** [comment]
Still issue?

**Comment by kriskog** [comment]
Needs reproducing for over a year, closing.

**Comment by nemvar** [comment]
You forgot to actually close this.
