### ISSUE TITLE
The stupid space dragging bug is back again

### ISSUE THREAD

**Issue by AlexTheSysop42** [tgstation/tgstation#37372]
Issue reported from  Round ID: 86896 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Testmerges: #36270 #37024 #37301 

Reproduction: grab thing, fly off into space, lose grab

**Comment by vuonojenmustaturska** [comment]
i wonder how many times i've fixed this

**Comment by ninjanomnom** [comment]
Don't worry too much about fixing this @vuonojenmustaturska I've got a pr in the works refactoring the map edge teleport.
