### ISSUE TITLE
Some shuttles leave centcom docks exposed to space and depressurizes it.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#37395]
Issue reported from  Round ID: 86926 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

After it leaves centcom for the station:

![dreamseeker_2018-04-23_23-13-00](https://user-images.githubusercontent.com/17237624/39153603-eba8e176-474b-11e8-80a4-942d353a877e.png)

The walls are the open blast doors I covered in walls to prevent air from escaping.

Repo:
Order oh hi daniel shuttel
wait for it to arrive
see this.

**Comment by ShizCalev** [comment]
@ninjanomnom

**Comment by WJohn** [comment]
Probably due to the stationary port having its turf_type being set to plating instead of space.

**Comment by ninjanomnom** [comment]
turf_type was removed as unnecessary now with the improved baseturfs @WJohn 

This may be annoying to track down and I suspect it may be a race condition bug
