### ISSUE TITLE
end game report showing random images

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#37392]
Issue reported from  Round ID: 86925 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512
http://take.ms/7ShfL

**Comment by Barhandar** [comment]
That's not random, that's devices. What did it say on mouseover?

**Comment by Tlaltecuhtli** [comment]
other people had the same problem and i think they had different images

**Comment by ShizCalev** [comment]
@Fox-McCloud

**Comment by MIC132** [comment]
I think it might be related to all autosurgeons not having icon/sprite and not working.
Someone mentioned one of the purchased items was x-ray autosurgeon.

**Comment by davethwave** [comment]
Perhaps it could do with this pr? It's been test-merged a few times so who knows.
https://github.com/tgstation/tgstation/pull/37399

**Comment by MrStonedOne** [comment]
here's the image in a better site: 
![image](https://user-images.githubusercontent.com/7069733/39331277-f51cf418-4958-11e8-9a50-7d3aa97601d8.png)


@Tlaltecuhtli please do not link to image sharing sites. direct links to images or bust. github lets you upload images directly so there is no excuse.

**Comment by PKPenguin321** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/37402
