### ISSUE TITLE
Floorbots can cause infinite tiles

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#37421]
Issue reported from  Round ID: 86972 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

If a floorbot repairs a tile, you can crowbar up two tiles from one spot.

The round before somehow we had INFINITE tiles coming from a spot and we couldn't DELETE the tile with admin delete.

1. Spawn a lizard
2. Give yourself a fireball spell
3. Fire ball the lizard
4. Spawn floorbots and set them to repair tiles
5. drag two floorbots on the same tile
5. crowbar tile.

**Comment by DaxDupont** [comment]
@ninjanomnom

**Comment by praisenarsie** [comment]
tbh comment them out from the code, they are horrendous at their job @Iamgoofball needs to fix their ai

**Comment by Barhandar** [comment]
They're _awesome_ at their job - spacing everything after emagging.

**Comment by ninjanomnom** [comment]
This is caused by the floorbots not checking their target is still valid after delaying to simulate construction speed. You could probably do the same thing with just one floorbot and placing the tile down yourself.

**Comment by DaxDupont** [comment]
@ninjanomnom kinda weird you can't delete the tile though, I am not sure why a hard delete by an admin won't work.

**Comment by Barhandar** [comment]
>@ninjanomnom kinda weird you can't delete the tile though, I am not sure why a hard delete by an admin won't work.

Hard delete does what to turfs exactly? If it resets to baseturf, baseturf might be the floor.

**Comment by ninjanomnom** [comment]
The failure to delete would be a different issue, I have no idea what that would be caused by
