### ISSUE TITLE
Syndicate hardsuit is removable

### ISSUE THREAD

**Issue by iskyp** [tgstation/tgstation#37420]
>The feared suit of a syndicate nuclear agent. Features slightly better armoring and a built in jetpack that runs off standard atmospheric tanks. When the built in helmet is deployed your identity will be protected, even in death, as the suit cannot be removed by outside forces. Toggling the suit in and out of combat mode will allow you all the mobility of a loose fitting uniform without sacrificing armoring. Additionally the suit is collapsible, making it small enough to fit within a backpack. Nanotrasen crew who spot these suits are known to panic.

>When the built in helmet is deployed your identity will be protected, even in death, as the suit cannot be removed by outside forces.

>the suit cannot be removed by outside forces.

reproductation
.be validhunter
.kill syndicate guy
.remove hardsuit

**Comment by praisenarsie** [comment]
not a problem??????????????????????
