### ISSUE TITLE
All hotspots in world are preserved during SM causality destabilization

### ISSUE THREAD

**Issue by Euphausiacea** [tgstation/tgstation#37434]
Title
All hotspot effects in world lasted the entire duration of the causality destabilization, regardless of their intended duration.

[Reproduction]: 
Unmodified and self-hosted server running revision: e21815eb30cc2da3bac71509167772e91a39fa45
Delaminate the shard until the causality filed is deployed, then generate hot spots. Blow some welding fuel tanks up, fire a marksman beam rifle. I do not recommend reproducing this on server, for obvious reasons.

**Comment by AnturK** [comment]
@ninjanomnom sleeps in process

**Comment by ninjanomnom** [comment]
woops, forgot to set waitfor
