### ISSUE TITLE
Airlock Painters No Longer Work

### ISSUE THREAD

**Issue by Nabski89** [tgstation/tgstation#37430]
[Round ID]: # 87016

[Testmerges]: # None
[Reproduction]: Get an airlock painter, click an airlock it does nothing.

These used to be under devices so I blame the device change.

**Comment by Jalleo** [comment]
I believe its already reported.

**Comment by Nabski89** [comment]
You're right this was reported on 2/2/18.

**Comment by ShizCalev** [comment]
#35223
