### ISSUE TITLE
Brain tumor trait is out of control

### ISSUE THREAD

**Issue by Teepeepee** [tgstation/tgstation#37446]
Round ID: # 87046 (but I've been seeing this for many rounds now).

Okay, so brain tumor went from free point to 10 minute permastun/blindness sentence. I can't even start growing mannitol plants before that point and not all chemists cooperate with you. I know this is part of the risk of taking this, but holy fuck its kinda too much. You may deem this not an issue, or intended, at least I'd like to hear from the administration before dropping my gimmick trait build.

As a side note, are traumas tracked anywhere? I feel like I get split personality all the time and its fucking annoying, every single one I've had doesn't want to cooperate or negotiate on what to do, one even welded me inside a pod and made the fuel run out so I couldn't get out (which is kinda okay since he wanted to survive but its still pretty dickish).

**Comment by Tlaltecuhtli** [comment]
well maybe uhhh dont have brain cancer

**Comment by XDTM** [comment]
Traumas are tracked in the statistics.
As for the trauma stacking, it's mostly because the trauma chance is (existing brain damage + brain damage hit) so several 0.1 ticks are going to trigger several traumas once the damage is high enough. I should revisit the formula, but i can't think of a good way of doing it.

**Comment by AlexTheSysop42** [comment]
>split personality trapped you

Ahelp it, the point of the "dont suicide" is so someone's split personality doesn't ruin the round for them.

**Comment by Armhulen** [comment]
i'm so proud of myself for this

**Comment by iskyp** [comment]
if chemists won't give you mannitol, you have plenty of other options.
see:
CMO
engineering (to build you a dispenser)
silicon
the entirety of medical

**Comment by davethwave** [comment]
a lot of medical does not have chemistry access.

**Comment by iskyp** [comment]
a part of medical has access to mannitol (GENETICS) and are able to use their mouth and vocal cords to speak the spess language used by all nanotrasen employees known as common

**Comment by iskyp** [comment]
>it's the tongue not vocal cords iskyp

FUCK

**Comment by Teepeepee** [comment]
I guess I got what I asked for, thanks, I'll close this since its not an issue.
