### ISSUE TITLE
AI Shell Borg Power bug

### ISSUE THREAD

**Issue by Jalleo** [tgstation/tgstation#37459]
[Round ID]: # Terry

[Testmerges]: Not relevant

[Reproduction]: Be a AI get in a shell without power and get about and move about like it isnt a issue (I believe you cannot do that as a borg.

**Comment by Barhandar** [comment]
Borgs can move around without a powercell, they just can't _do_ anything.

**Comment by Jalleo** [comment]
Yeah I thought that got changed
