### ISSUE TITLE
Borg panel scrambled codes and unsyncing from AI does not remove it from AI synced borgs

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#37467]
Issue reported from  Round ID: 87068 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Still shows up under the AI status tab.

Also still shows up in camera list.

**Comment by DaxDupont** [comment]
@vuonojenmustaturska

**Comment by Anonmare** [comment]
>if(!R.shell)
>				R.UnlinkSelf()
>R.module.rebuild_modules()

Wouldn't that do the trick?

**Comment by timothymtorres** [comment]
Duplicate of #44349
