### ISSUE TITLE
Zombies cannot tell who is already a zombie

### ISSUE THREAD

**Issue by Electronics** [tgstation/tgstation#37469]
Any sort of helmet/mask shields the look of a zombie and normally gives rise to zombies killing other zombies. Maybe they should have some sort of badge like the syndicate / rev icons?

**Comment by Anonmare** [comment]
Would be easier to make them force_drop masks, helmets and outer suits

**Comment by MMMiracles** [comment]
Zombies killing other zombies is just an inconvenience at worst and could be avoided if you go 'idiot i'm a zombie' . Having a way to 'hide' among the horde is entertaining as a survivor.

**Comment by XDTM** [comment]
We need a zombie language btw

**Comment by Therapist1** [comment]
zombies 2: special infected boogaloo

**Comment by AlexTheSysop42** [comment]
>we need a zombie language

No we don't

**Comment by Bluespace** [comment]
I've survived by pretending to be a zombie with an engi hardsuit, it's fun.
-1

**Comment by AlexTheSysop42** [comment]
>I've survived by pretending to be a zombie with an engi hardsuit, it's fun.

Same here, but I was a high-functioning (xenobio) zombie and using mutation toxin and a spray to make others high-functioning zombies as well

**Comment by ExcessiveUseOfCobblestone** [comment]
This was intentional and not a bug nor oversight.

**Comment by ExcessiveUseOfCobblestone** [comment]
If you are killed by a friendly zombie it is your fault for not saying literally anything or just hitting them back once with your claws.
