### ISSUE TITLE
clicking as a monkey the backpack unequips it instead of opening it

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#37518]
Issue reported from  Round ID: 87140 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by ShizCalev** [comment]
Monkeyize does causes this from the looks of it.

**Comment by IndieanaJones** [comment]
This is now universal for all monkeys.

**Comment by ArcaneDefence** [comment]
This still happens even after making monkeys a species.

**Comment by timothymtorres** [comment]
This bug has been around for a while and is very annoying.
