### ISSUE TITLE
Plasmamen spawn with an oxy tank in their box

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#37517]
You know the box everyone spawns with, that has a small oxytank, breath mask etc?

Plasmamen also receive an oxygen tank inside their box, which is pretty bad for a race that needs to breathe plasma so they don‘t die.

**Comment by ExcessiveUseOfCobblestone** [comment]
I like to imagine Centcomm does that to be sadistic.

**Comment by kriskog** [comment]
Still do

**Comment by Firecage** [comment]
It appears to have been fixed by this point, so this issue can likely be closed.

**Comment by kriskog** [comment]
Yeah, changed in #45538
