### ISSUE TITLE
Culture Bottles sometimes are hidden by PANDEMIC 220 machines

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#37527]
[Round ID]: #87153

[Reproduction]: Basically, I was playing virologist, and twice during my shift, culture bottles were spawned behind the sprite for the PANDEMIC 220. Only on the second occurrence did I think to right click the tile, and I saw they were hidden behind. For less experienced players, I feel as if this could result in wasted materials. 
Side Note: For the past two weeks, I have experienced the same issue with jetpacks and canisters. Once removed from the canister, the jetpack will be hidden behind its sprite.

**Comment by MIC132** [comment]
I noticed the same when taking tanks from tank dispenser, though it only happens sometimes.

**Comment by Jalleo** [comment]
I believe this is a dupe.

**Comment by Barhandar** [comment]
#37346
