### ISSUE TITLE
34+ sheet plastitanium stacks don't have an icon

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#37520]
Or rather, they show the "NO SPRITE" fallback.

Reproduction: take 35 or more plasma + titanium alloy sheets from the ORM, take one from the stack to refresh the icon so it doesn't show the "1 sheet" one. 
Only really shows up with free golems and if someone wants to decorate like Syndicates.

**Comment by YakumoChen** [comment]
Uhhh, I thought plasteel wasn't supposed to stack past 30?

**Comment by Barhandar** [comment]
None of the sheets have override for max_amount so they all stack to 50.
