### ISSUE TITLE
Proximity sensors don't trigger when attached to wires

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#37545]
Revision: de523243b8211bb57c7a89e0f7e312fa6b228cda
/obj/item/assembly/prox_sensor

If you attach this to a wire (for example an airlock's), it won't trigger once someone enters the detection range.

**Comment by Barhandar** [comment]
Prox sensors are busted in general, duplicate of #27235

**Comment by 81Denton** [comment]
Oof
