### ISSUE TITLE
Bucket on head causes pressure damage

### ISSUE THREAD

**Issue by Nabski89** [tgstation/tgstation#37542]
[Round ID]: # 87177

[Testmerges]: # #37406: 'Adds (fake) ambient occlusion as a client preference' by deathride58 at commit 87a9b1
#34086: 'goonchat linkify has been vastly improved' by optimumtact at commit ab5853
#37410: '[syou can no longer insert a storage object into itself, and therefore, no longer bohbomb with one boh' by kevinz000 at commit 861dc5
#37504: 'Removes an unnecessary file causing github security warnings on tgui, also updates/downgrades some dependencies to ensure a build' by vuonojenmustaturska at commit ef8d06

[Reproduction]: # Put a bucket on your head. Take pressure damage until you die.

**Comment by TribeOfBeavers** [comment]
I did it in the thunderdome and took no damage, oddly enough.

**Comment by Nabski89** [comment]
I'm seeing that too. I looks like you also have to have something in your outer clothing spot.

**Comment by AlexTheSysop42** [comment]
Fixed
