### ISSUE TITLE
Admin Command Check Contents doesn't work.

### ISSUE THREAD

**Issue by GrayRachnid** [tgstation/tgstation#37541]
[Reproduction]: # Check contents on any human mob, doesn't do what it's supposed to do and instead just shows the name of the mob.

**Comment by ShizCalev** [comment]
@kevinz000

**Comment by kevinz000** [comment]
https://github.com/tgstation/tgstation/pull/37656/files should have fixed it 
Should have.

**Comment by SpaceManiac** [comment]
Appears fixed, reply and this can be reopened if it isn't.
