### ISSUE TITLE
Morphs have no counter to eating revivable things.

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#37540]
I think morphs need to be able to spit things out, and heres why.

1.Eat a ling as a morph, it revives in you. It kills you from the inside out and theres nothing you can do about it but die.

2. Eat a mmi/positronic brain as a morph. It can talk on the radio and alert people to your every location. 

So uh, I hope this can be considered an oversight because morphs have no way to avoid this once this happens. edit: Like some sorta list, or GUI that opens and lists everything you ate. Then you click an item in that list and it comes out.

**Comment by Barhandar** [comment]
You can't tell if someone's a ling or not as a morph. Revivers probably should pop out of the morph on revive.
MMI/posibrain though, just don't eat them.

**Comment by ShizCalev** [comment]
Feels like a feature to me.

**Comment by PKPenguin321** [comment]
One time I ate a ling and it would armblade me from the inside whenever it could see me, so I stayed in the vents. I crawled all the way to atmos and put myself into the N2O tank. The ling killed me, but proceeded to get chainstunned for 30 minutes before breaking the window, at which point the shuttle had already arrived. It was pretty funny.

**Comment by Shadowflame909** [comment]
Yeah, I opened a n20 tank before I died. KO'D the people around me for a bit.
