### ISSUE TITLE
All stocks are at a value of 10; number of stocks available are non-integers less than one, or are zero.

### ISSUE THREAD

**Issue by nervere** [tgstation/tgstation#37566]
Round ID: # 87211 on Sybil

Testmerges: #37399 is testmerged but it's doubtful that something touching sprite loading has anything to do with the stock market.

#37416 is probably the full-merged PR most relevant to this issue report.

Reproduction: I found this as a janitor 15 minutes into the round. I went onto the stock computer and found that all stock values were 10 and the number of available stocks were non-integers less than one or at zero. The history of the stock market's price indicates to me that the price was this way since the start of the round. The history, however, as verified by the variables of one example stock (see image 3), shows that the price is actually 5, contrary to the displayed value of 10.

Stock main screen:
https://ibb.co/hnKJtc

History of one stock in particular, the one named "State".
https://ibb.co/gk4ezH

Variables of the stock named "State". Note that, while part of the "values" list is cut off, all other entries were also "5".
https://ibb.co/eoncmx

There were no abnormalities as far as I could see with the stock market events, but I didn't examine it very thoroughly.

This issue is probably caused by replacing the += operator with = as seen in #37416

**Comment by deathride58** [comment]
TFW you accidentally cause an intergalactic stock market crash

Feelsbadman
