### ISSUE TITLE
Nar-sie "arm" animation happens every single cult win despite being "rare"

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#37573]
It should be more rare like it is supposed to be. I haven't seen it actually do the nuke since maybe when the feature was first put in.

**Comment by SpaceManiac** [comment]
It looks like #30888 may have started ignoring the value that's supposed to differentiate between the two cinematics.

**Comment by SpaceManiac** [comment]
@AnturK

**Comment by AnturK** [comment]
Hmm, i'll take a look
