### ISSUE TITLE
Centcom is fucked up by the space transitions

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation#37583]
![](https://file.house/XPBi.png)

![](https://file.house/daTJ.png)

**Comment by optimumtact** [comment]
@ninjanomnom viscontents on z level?

**Comment by GrayRachnid** [comment]
![image](https://user-images.githubusercontent.com/6613514/39483101-4eb072ea-4d3f-11e8-8697-c66830d3fff3.png)
