### ISSUE TITLE
Wumborian Fugu leave behind a massive invisible body on death that blocks the tile it is on and several tiles around it from being clicked on

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#37585]
[Round ID]: # 87237

Reproduction: gold slime blood reactions until you get a fugu, kill it, marvel at the corpse that blocks you from doing shit on the tile it's on.

**Comment by praisenarsie** [comment]
fugu needs a refactor

**Comment by Armhulen** [comment]
I did, I think I left a bunch of 0 alpha pixels on the new sprite

**Comment by newfren** [comment]
It will also have a health bar above the massive invisible corpse if you're wearing a medhud.
