### ISSUE TITLE
Blood-Crawl is kept outside of VR arena

### ISSUE THREAD

**Issue by Electronics** [tgstation/tgstation#37596]
If you obtain blood-crawl by killing a blood-demon in VR (put on by admins or the like), the effect is kept between VR charaters and outside of the arena (on the normal station).

```Round ID:  87255 

Server revision compiled on:  2018-04-30 

The following pull requests are currently test merged: 
#37587: 'Makes the jukebox less terrible' by KorPhaeron at commit 7ec266 
#34086: 'goonchat linkify has been vastly improved' by optimumtact at commit cd19a3 
#37406: 'Adds (fake) ambient occlusion as a client preference' by deathride58 at commit 87a9b1 


Based off origin/master commit: 21de54 

Revision: 74fd305540cef40eb4d3d480afe9efb65d69ad93 

Server tools version: /tg/station 13 Server v3.2.2.0 

Server tools API version: 3.2.0.2 

Current Informational Settings: ```

**Comment by Shadowflame909** [comment]
THERES A VR ARENA? OH SNAP I WISH I knew about this!

**Comment by AlexTheSysop42** [comment]
You can also use the cargo shuttle to bring your crew self into the real world, with its items (which included an infinite-capacity pulse pistol but normally just includes eswords and armor)

**Comment by Shadowflame909** [comment]
Wouldn't a good solution be to make everything in VR function as the holodeck? IE auto removed after you leave VR. Another solution would be that you have to wear a VR suit that functions as the holodeck thunderdome suit. Everything in VR would have safety checks for it.

**Comment by AlexTheSysop42** [comment]
VR is literally just "make a new mob for me in a specific place and when I die I can just replace it." There is no VR "area."

**Comment by Noahnoah55** [comment]
Damn, we could have had our own Corrupted Blood incident, too.
