### ISSUE TITLE
Hard Cider claims it tastes like autumn, actually tastes like apples

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#37604]
Top 10 anime betrayals

**Comment by Kromgar** [comment]
But Cider is usually an autumn thing which is why it tastes like autumn

**Comment by Barhandar** [comment]
>But Cider is usually an autumn thing which is why it tastes like autumn

The problem is that it doesn't taste like autumn, it tastes like apples.
>I think the test desc should be `autumn.... no wait, fall!`

That would be funny.

**Comment by ShizCalev** [comment]
> top google result for autumn taste

verdict says;

> What does autumn taste like?
> Apple cider
