### ISSUE TITLE
Multiplexer select number should start at 0

### ISSUE THREAD

**Issue by 7esla** [tgstation/tgstation#37608]
Right now a two multiplexer has the select bit from 1 - 2. It should be 0 - 1.

**Comment by PKPenguin321** [comment]
Disagree since many components in circuits also start at 1
Also not a bug

**Comment by PKPenguin321** [comment]
Not to mention all this would accomplish at this point is break a bunch of old circuits

**Comment by kevinz000** [comment]
everything in byond starts in 0, just keep it this way.
