### ISSUE TITLE
Escape pods on metastation start out with no atmosphere

### ISSUE THREAD

**Issue by Therapist1** [tgstation/tgstation#37614]
[Round ID]: # 87292

[Testmerges]: # I do not believe this to be caused by testmerges, this has happened on many rounds I've played on, all with different testmerges.

[Reproduction]: # Load up metastation, and head into an escape pod. This will create wind as the air from the hall is sucked into the escape pod chamber. Entering the escape pod will slowly start to kill you through atmos and lack of O2.

**Comment by SpaceManiac** [comment]
The pod itself is fine, atmos initializes before shuttles so the pod bays all vent to space before the pods dock. The "HEY! LISTEN!" from SSatmos that we've let ourselves ignore points this out.
