### ISSUE TITLE
Crate duplication

### ISSUE THREAD

**Issue by drderp3635** [tgstation/tgstation#37611]
((Found on yogstation using TG code))

Using the skittish trait ability on a cargo drop pod sent in from the express supply console will create a duplicate of the crate that arrived.

**Comment by ExcessiveUseOfCobblestone** [comment]
Is it a true dupe or some sort of doubleloc memery?

**Comment by drderp3635** [comment]
Crates created had the same form number and contents as the first. The first crate also retained its contents.

**Comment by AlexTheSysop42** [comment]
Probably a good thing that express consoles cant order nulls

**Comment by SpaceManiac** [comment]
true dupe, the act of opening the pod spawns in the supply crate

**Comment by ExcessiveUseOfCobblestone** [comment]
@Xhuis

**Comment by Xhuis** [comment]
I didn't code cargo pods. Skittish just puts you inside of the locker; the only way it changes it is by opening and closing. Whatever the issue is, it lies in cargo code.

**Comment by XDTM** [comment]
It probably isn't supposed to close after opening, so manually closing with skittish causes the bug

**Comment by ExcessiveUseOfCobblestone** [comment]
@MrDoomBringer
