### ISSUE TITLE
When sticking a pocket protector on a shirt and putting a pen in it, the pocket protector appears in its own contents and can be removed/thrown on the ground, etc.

### ISSUE THREAD

**Issue by EvilJackCarver** [tgstation/tgstation#37634]
Title sums it up, but when you add a pocket protector to your uniform and stick a pen inside it, the pocket protector's attached-to-jumper overlay adds itself to the contents of the pocket protector, allowing you to take your pocket protector out of your pocket protector and throw it on the ground/in your bag/pocket and so forth.

While this doesn't really have any gameplay implications (unless you're a traitor with a pen uplink and stick that pen in there), it's still a visual inconsistency.

Tested over multiple rounds (87334 was one of them, dunno the other but it was Bagil on box yesterday - Statbus says either 87298 or 87304), and both times it happened, it was a black pen that I stuck in there.

**Comment by SpaceManiac** [comment]
@kevinz000 the pocket protector is in the jumpsuit's contents

**Comment by Cyprex** [comment]
This has been around for a bit, I remember encountering this bug one or two months ago.
