### ISSUE TITLE
Children of the flash object can be attached to signallers

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#37635]
This includes:
/obj/item/assembly/flash/cyborg (I assume engiborgs could screwdriver it and use it on a signaller to break shit)
/obj/item/assembly/flash/armimplant (Supposed to be a nodrop arm implant)
/obj/item/assembly/flash/shield (this is a riot shield and has no sprite when attached)

**Comment by Razharas** [comment]
Attachableness needs to be a component

**Comment by arsserpentarium** [comment]
Bike horn can't be attached too.

**Comment by PKPenguin321** [comment]
This becomes an easy fix as soon as https://github.com/tgstation/tgstation/issues/40144 is fixed, since then you could make the implant/shield into their own proper items and simply give them a generalized flash component
