### ISSUE TITLE
Circuitry drones can throw paper at a shocked grille and generate tesla_zap endlessly

### ISSUE THREAD

**Issue by Poojawa** [tgstation/tgstation#37643]
People are building roomfuls of tesla coils and have a drone that just throws paper endlessly at it for free research points and power. 

Remove drones when?

**Comment by 81Denton** [comment]
Feature 🤔

**Comment by AlexTheSysop42** [comment]
Feature, paper engines have been around longer than circuits

**Comment by arsserpentarium** [comment]
Also works works with disposal and mass accelerator.
Why do you think, that problem with drones?

**Comment by AverageJoe82** [comment]
I’ve had someone do this by hand before in combat so I wouldn’t call it a bug. Also circuits are at danger of being one shot  from Tesla shots iirc

**Comment by AverageJoe82** [comment]
I made this circuit to reproduce the issue, use at least a superpacman to make sure that enough power is in the grid to generate a tesla shock.

>{"assembly":{"type":"type-d electronic machine","opened":1},"components":[{"type":"fast ticker","inputs":[[1,0,1]]},{"type":"half-sec delay circuit"},{"type":"one-sec delay circuit"},{"type":"half-sec delay circuit"},{"type":"advanced locator","inputs":[[1,0,"paper"],[2,0,1]]},{"type":"grabber","inputs":[[2,0,1]]},{"type":"thrower","inputs":[[1,0,0],[2,0,2]]},{"type":"thrower","inputs":[[1,0,0],[2,0,2]]}],"wires":[[[1,"A",1],[5,"A",1]],[[1,"A",1],[7,"A",1]],[[1,"A",1],[2,"A",1]],[[1,"A",1],[3,"A",1]],[[2,"A",2],[5,"A",1]],[[2,"A",2],[8,"A",1]],[[3,"A",2],[5,"A",1]],[[3,"A",2],[7,"A",1]],[[3,"A",2],[4,"A",1]],[[4,"A",2],[5,"A",1]],[[4,"A",2],[8,"A",1]],[[5,"O",1],[6,"I",1]],[[5,"A",2],[6,"A",1]],[[6,"O",1],[7,"I",3]],[[6,"O",1],[8,"I",3]]]}

**Comment by PKPenguin321** [comment]
alternatively just make a loop of disposal chutes

**Comment by AverageJoe82** [comment]
Conveyor belt work here also?
