### ISSUE TITLE
Having your PDA snatched by a monkey makes it invisible

### ISSUE THREAD

**Issue by europax** [tgstation/tgstation#37645]
Round ID: 87370 (Bagil)

(If you put round ID in square brackets you can't see what's written there. is that intentional?)

While playing as a bartender, I held my PDA in my hand, and Pun Pun decided to snatch it.
...but the PDA didn't go to Pun Pun's hands.
And it wasn't on the floor.
It was invisible.

Naturally, I assumed it was lost.
But no, it became part of me. I could receive and reply to messages, just could not see the PDA itself and access its interface.

The first time this happened, I asked an admin to have all my items dropped. It reappeared then.

But the second time it did, I took off my jumpsuit myself. Then put it on. It did NOT appear back.
And when an admin tried to drop all my items, it did not appear either. It was a part of me.

Amazing.

[Reproduction]: Have Pun-Pun or any other monkey snatch your PDA while it's in your hand.

To get confirmation of it becoming part of you, ask someone to PDA you.

**Comment by ShizCalev** [comment]
Unable to repo

**Comment by TheRespectedMan** [comment]
Happened to me just 20 minutes ago. Was using a camera, monkey snatched it and it disappeared.
