### ISSUE TITLE
Report issue should include test merges and specific revision in the issue ticket.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#37644]
**Issue reported from  Round ID: 87370 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])**

**Reporting client version: 512**

Looking at the URL I think it's supposed to include this information?

The only info that gets shared is the lines in bold above. I can remember the report issue reporting everything before, maybe something broke or I am misremembering.

![2018-05-03_15-45-52](https://user-images.githubusercontent.com/17237624/39580429-6e29cde6-4ee9-11e8-9e3b-488bfdf0b94a.png)

**Comment by Cyberboss** [comment]
It already includes the round id which tells us most of that

**Comment by Cyberboss** [comment]
All of it actually
