### ISSUE TITLE
Bots will attempt to path through a depowered door for infinity but will path around a bolted one

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#37642]
On meta. Watching 3 bots get stuck against a door as the AI wondering how to make them stop as they tried to path through a door with most of the wires cut. 

Eventually I realized I should bolt it and they immediately repathed.

**Comment by ShizCalev** [comment]
From what I can tell, this seems be more of an issue with astar not changing their path if the door loses power _after_ they're already started it.

**Comment by JohnFulpWillard** [comment]
Tested this in-game locally and seems to have been fixed.
