### ISSUE TITLE
Signallers don't work in button assemblies

### ISSUE THREAD

**Issue by xenon-difluoride** [tgstation/tgstation#37655]
Reproduction: make wall button, get two matching signallers, put in one signaller, close, press, listen for nonexistent beep from the other

**Comment by Mickyan** [comment]
They definitely work, I use them from time to time to make door locks. Were you using a screwdriver to make them attachable? You don't have to do that if you put them in buttons.

**Comment by TheBonded** [comment]
I can't seem to reproduce this, so I assume this has been fixed in the past 3 years

**Comment by TheBonded** [comment]
Ima just close this now because it seems to no longer be an issue
