### ISSUE TITLE
Upon opening a paradox bag the bag UI centers on the opener and can not be closed without resetting

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#37658]
Issue reported from  Round ID: 87399 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

![image](https://user-images.githubusercontent.com/6778786/39608920-de91c272-4f12-11e8-9558-94f8b661b676.png)

can only be fixed by restarting ss13

**Comment by YPOQ** [comment]
#37334 #35285

**Comment by SpaceManiac** [comment]
Duplicate of #35285
