### ISSUE TITLE
If you're swallowed by a xeno, the attack thing has zero cooldown.

### ISSUE THREAD

**Issue by Darkgenerallord** [tgstation/tgstation#37667]
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

Yeah, it's literally just how fast you can press the arrow keys. It's more than fast enough to pretty much instantly kill a drone with a screwdriver.

**Comment by PKPenguin321** [comment]
"the attack thing" is the reverse chestburst yeah?

**Comment by Darkgenerallord** [comment]
yes
