### ISSUE TITLE
Goonchat doesn't save font size

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#37663]
Issue reported from  Round ID: 87420 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512.1423

I have to make my text bigger every time I connect. 
It used to save my preferences.

**Comment by zaracka** [comment]
Think it happened after updating BYOND.

**Comment by iskyp** [comment]
Priority: CRITICAL

**Comment by Birdtalon** [comment]
This seems to be a BYOND issue as the cookies will work on 511
http://www.byond.com/forum/?post=2406876

https://github.com/ParadiseSS13/Paradise/issues/9853
