### ISSUE TITLE
Goof's Ion Law changes makes ion laws able to delete Law 0 Malf

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#37661]

**Comment by optimumtact** [comment]
Abusive language is unacceptable

**Comment by Arianya** [comment]
Goof's changes are pretty handicapable.

**Comment by optimumtact** [comment]
The github terms of service are clear, please don't break them

**Comment by ExcessiveUseOfCobblestone** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
i dont think I've touched ion laws in like 2 years

**Comment by ExcessiveUseOfCobblestone** [comment]
That just makes this issue even more funny.

**Comment by optimumtact** [comment]
I'm gonna close this, it has no actual steps to reproduce, round id's or information and unfairly attacks someone who is unlikely to to be the culprit.

**Comment by DaxDupont** [comment]
@optimumtact it's @Jordie0608's code and seems very much intended. 
https://github.com/tgstation/tgstation/blob/6ec0feeb55ca9188212ba50a25b2c6f2ab46ecc9/code/datums/ai_laws.dm#L318

**Comment by Jordie0608** [comment]
#36463 only affected the handling of hacked laws so I believe this would've been pre-existing, but I can't see how yet. I'll try and catch it happening.
