### ISSUE TITLE
you can take both pineapple traits at once

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#37669]
>like pineapple
>hate pineapple
???

**Comment by PKPenguin321** [comment]
@Xhuis traits need to have a list attached to them of conflicting traits, so traits that do the opposite of each other like this can't be taken together

**Comment by Ordonis** [comment]
Excuse you, some people are just tsundere for pineapple

**Comment by Xhuis** [comment]
I didn't make this trait.
@PKPenguin321 I know, and I've been trying, but Byond makes it godawfully obtuse and difficult.

**Comment by ShizCalev** [comment]
I think that's called schizophrenia
