### ISSUE TITLE
I was able to join the game twice

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#37674]
[Round ID]: # 87461

[Reproduction]: # So I had died (killed myself with detective gun if it helps) and had become the split personality of a catgirl named cupcake. Anyways, I watched her be in control for about 1-2 minutes, and my game froze. When I reconnected, I was greeted with the join game screen, so I really respawned or something. There were two of me, one dead one alive. I had joined the round at round start originally.

**Comment by praisenarsie** [comment]
@MrStonedOne

**Comment by PKPenguin321** [comment]
Isn't this usually an issue with ghostize() or something

**Comment by ShizCalev** [comment]
see #19343

**Comment by ShizCalev** [comment]
https://tgstation13.org/parsed-logs/basil/data/logs/2018/05/05/round-87461

**Comment by kriskog** [comment]
Closing in favor of #47720
