### ISSUE TITLE
Orion Trail Realism Mode Singularity does not wink out

### ISSUE THREAD

**Issue by RandolfTheOkay** [tgstation/tgstation#37677]
Issue reported from  Round ID: 87468 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

As stated in the title, the orion trail generated singularity does not disappear after a short period of time, and instead remains indefinitely. An attempt to BoH the stage 1 singularity failed somehow, resulting in an explosion, but no deletion of the singularity.

**Comment by Barhandar** [comment]
It should get qdel'd in 5 seconds after being created. Any admins to VV it?

**Comment by 81Denton** [comment]
Code in question:

https://github.com/tgstation/tgstation/blob/206c66def9e163c1f049380dd6e267ab875d9ece/code/game/machinery/computer/arcade.dm#L604-L617

**Comment by Barhandar** [comment]
OIC, QDEL_IN getting called on the machine instead of the singularity.
