### ISSUE TITLE
Can't close apc cover with crowbar as it just plucks the battery out instead

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#37682]
![image](https://user-images.githubusercontent.com/6778786/39664358-24af4e3a-5050-11e8-9d13-acd4476b46c7.png)

Xenobio APC went to replace the battery with a hyper cell but instead all i get is some stupid fucking bullshit where if i try to close the cover with a crowbar i pluck out the cell and i can never shut the apc

**Comment by 81Denton** [comment]
Duplicate of #37628
