### ISSUE TITLE
You still cannot use any equipment inside a mech as an MMI

### ISSUE THREAD

**Issue by Nilons** [tgstation/tgstation#37685]
Issue reported from  Round ID: 87480 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

I reported this bug Im pretty sure a year ago or a lot of months ago and was told it was fixed.  I had my brain put in an mmi and that mmi put into a gygax and was able to walk, and use the mech menu, but unable to actually use any of the equipment or to attack anything.

**Comment by Tlaltecuhtli** [comment]
idk if related but ai in mech works

**Comment by SpaceManiac** [comment]
Fixed by #41167
