### ISSUE TITLE
Ninja nets remove plasmaman suit + internals

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#37686]
- Plasmaman gets caught by a ninja, net teleports him into weeb jail
- The net drops his envirosuit, mask and plasma internals tank back at the station
- He is now burning and suffocating to death

I mean weeb jail sucks, but it shouldn't outright murder plasmamen.

Ninja item removal is handled here:

https://github.com/tgstation/tgstation/blob/8a82b16d473a758769349ec66e641404324ff93e/code/modules/ninja/suit/n_suit_verbs/energy_net_nets.dm#L53-L60

**Comment by Tlaltecuhtli** [comment]
also removes you from the round
