### ISSUE TITLE
Ion laws can override zeroth laws.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#37694]
Issue reported from  Round ID: 87487 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Ion laws can override hacked laws.

1. Make AI tot with it's law 0
2. Smash ion storm event button
3. observe as hacked law is replaced by ion law.

Honestly it kinda feels like a feature because of the hilarity of stopping a traitor AI train in it's track but people disagree.

**Comment by Dorsisdwarf** [comment]
the AI traitor tot law is not a hacked law, it's a Law 0. Law 0s are supposed to be un-overridable and the highest priority at all times.

Also it wouldnt stop traitor AIs, the law 0 is just a tell for the crew, not what lets them kill everyone

**Comment by DaxDupont** [comment]
@Dorsisdwarf A zeroth law is the right name yeah.

**Comment by DaxDupont** [comment]
It might override hacked laws too.

**Comment by Tlaltecuhtli** [comment]
feature

**Comment by AlexTheSysop42** [comment]
>the AI traitor tot law is not a hacked law, it's a Law 0. Law 0s are supposed to be un-overridable and the highest priority at all times.

Purge boards remove any non-malf zeroth laws.

**Comment by 81Denton** [comment]
I can't reproduce this. I spawned in an AI on localhost, made it a tator via TP and smashed that MF ion storm button about 20 times.
The only odd thing that happens is that after a while, ion laws start replacing asimov laws until a new basic lawset (asimov, paladin, asimov++ etc.) pops up out of nowhere.

![adsasdadsads](https://user-images.githubusercontent.com/32391752/39674428-09950a2a-514c-11e8-9fb8-6d46fc87ddad.PNG)

**Comment by DaxDupont** [comment]
That's strange, I've seen it happen in-game a lot

**Comment by 81Denton** [comment]
Weird, maybe TP malf AI or event panel ion storm are different from the ones that appear "naturally"?

**Comment by bgobandit** [comment]
Did you get the ion storm event that rearranges law order?
