### ISSUE TITLE
Aphasia is not reset on cloning like other severe traumas are.

### ISSUE THREAD

**Issue by GrayRachnid** [tgstation/tgstation#37690]
And i'm pretty sure brain surgery won't fix it after being cloned so enjoy speaking gibberish forever.

**Comment by XDTM** [comment]
languages are mind-based by default, i'll have to port them to the mob-based shadow languages

**Comment by DaxDupont** [comment]
Please include round id.

Also this is caused by aphasia being set to the default language and doesn't stop being the default language even if it's removed. The trauma itself does NOT remain. Default language doesn't get reset.

**Comment by XDTM** [comment]
The issue is that languages are mind-based by default. There is a system to associate it with a mob, but i wouldn't be able to remove the base mind language.

**Comment by GrayRachnid** [comment]
Experienced this over a few rounds and found it a recurring issue. No specific round ID as of late.
