### ISSUE TITLE
you cant turn off disposals bin

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#37703]
Issue reported from  Round ID: 87521 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])
they send shit even if the power indicator is green or not

**Comment by newfren** [comment]
The power indicator only effects if it refills air or not. You have to flush them then turn off power for them to stop flushing shit.

**Comment by YPOQ** [comment]
#28672

**Comment by PKPenguin321** [comment]
Duplicate of #28672

@YPOQ thanks for getting the issue number but unless you explicitly say that this is a duplicate people will ignore it

**Comment by newfren** [comment]
Also this is totally not a bug. Power only charges the bin with air or whatever, it uses that air to flush people, so turning off the power won't stop the first flush.

**Comment by PKPenguin321** [comment]
Power implies that it controls the power for the flushing mechanism though, not the air pump. Considering how it's on the flushing mechanism control panel.

**Comment by SpaceManiac** [comment]
Duplicate of #28672

More a UI clarity issue than a bug.
