### ISSUE TITLE
bayonet dont do damage as intended

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#37716]
Issue reported from  Round ID: 87546 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])
a gun with a bayonet does the same melee damage as one without

**Comment by Barhandar** [comment]
Cannot reproduce. Which gun, and are you using harm intent?

**Comment by ExcessiveUseOfCobblestone** [comment]
Why are you persistently unable to properly describe your issue in either the body or title?

**Comment by kriskog** [comment]
Cant reproduce, needs more info.
