### ISSUE TITLE
Camera Bug (uplink item) cameras don't appear in alphabetic order

### ISSUE THREAD

**Issue by Vidiveni** [tgstation/tgstation#37713]
Round ID: #87527

Reproduction: 
1. Buy a "Camera Bug" with telecrystals as traitor. 
2. Use it. 
3. See this:
![](https://i.imgur.com/4TIhhln.jpg?1)

This particular image comes from ghosting on Terry, but I've tested on an actual traitor round as well. I personally find it difficult to use the item if the cameras aren't sorted.

**Comment by AlexTheSysop42** [comment]
Ctrl-f for bandaid fix

**Comment by EvilJackCarver** [comment]
I glanced at it at work today, it seems that the code is using `sortList()` rather than `camera_sort()`.

Shouldn't be too hard a fix, but my brain's fried at the moment and I don't have the time to test it.

**Comment by Vidiveni** [comment]
This was fixed in 2018 at some point.
