### ISSUE TITLE
Floor Is Lava is broken

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#37738]
Floor is lava deals damage to everyone on the map, whether theyre on a table, a chair, a bed, or in lockers, and is ridiculously deadly given that it isnt capped in how often it can trigger

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blame/f97258b1a0723886e4e296b2979ec4b43cb85f7b/code/datums/weather/weather_types/floor_is_lava.dm#L28

Wonder if it will fix if you get the turf of L and loop through turf's contents,looping through just `loc` doesn't sit right.

**Comment by SpaceManiac** [comment]
Tables and lockers seem to protect fine. Chairs might be intentional but beds do not protect like they should.

**Comment by YakumoChen** [comment]
the AI also takes damage from it
