### ISSUE TITLE
social anxiety trait is shit

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#37734]
Issue reported from  Round ID: 87589 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512
so not only it makes you unable to talk every 10 seconds but it doesnt even tell you when you can speak again after muting you

**Comment by PKPenguin321** [comment]
not a bug

**Comment by iskyp** [comment]
![image](https://user-images.githubusercontent.com/33264221/39725004-3c8d53ca-51ff-11e8-9c9e-87d87b90df92.png)

**Comment by Tlaltecuhtli** [comment]
what i m saying it needs a message that tells you that you are able to talk again, so you dont have to ctrl c ctrl v ;help while a ling is eating you

**Comment by Repukan** [comment]
Or just don't take it?

**Comment by ExcessiveUseOfCobblestone** [comment]
I can understand the "lol just don't take the trait" for the whole every 10 second thing but I don't see how that's applicable to the feedback issue.

**Comment by ExcessiveUseOfCobblestone** [comment]
It just seems like a poor implementation because they were too afraid to make the silence duration longer. Having to ctrl uparrow enter constantly until "it works" shouldn't be a feature of the game, regardless of if the creator of the trait intended for it or not.

**Comment by Tlaltecuhtli** [comment]
>what i m saying it needs a message that tells you that you are able to talk again, so you dont have to ctrl c ctrl v ;help while a ling is eating you

**Comment by nemvar** [comment]
wyci
