### ISSUE TITLE
AI_Act is still broken with field generators

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#37740]
And potentially digital valves, haven't checked them again yet.

Round ID: Various

**Comment by RandomMarine** [comment]
What a wonderfully descriptive issue report.

**Comment by Anonmare** [comment]
The title alone tells everything. Field gens don't work with AI_act.

**Comment by Jalleo** [comment]
@kevinz000

**Comment by DaxDupont** [comment]
Can confirm

**Comment by AnturK** [comment]
@kevinz000 interaction changes probably.

**Comment by DaxDupont** [comment]
@ShizCalev tag with kevinz fix your shit milestone please.
