### ISSUE TITLE
Crashed Abductor Ship Walls Unbreakable

### ISSUE THREAD

**Issue by timothymtorres** [tgstation/tgstation#37741]
So I played as a Free Golem recently and was attempting to salvage parts from the Abductor ship to make abductor golems.  Turns out the walls cannot be broken down via welder or Gibonite explosions.  I asked an admin about this and he went code diving and discovered that the walls **should** be breakable, but the tiles for some reason were set to not be destructible.  This sounded like a bug, so I'm posting it here.

I still managed to salvage Alien Alloy from the tables, lockers, and surrounding equipment.

**Comment by Jalleo** [comment]
I believe its intended

**Comment by Barhandar** [comment]
FYI alien alloy is printable in the omnilathe under stock parts after you research alien tech (2 alien tools in the analyzer to get both nodes visible).

**Comment by Anonmare** [comment]
I think someone just copy-pasted the abductor ship, made some edits but never changed the walls to be of the destructible variety

**Comment by Kromgar** [comment]
AFAIK these have always been indestructible

**Comment by YPOQ** [comment]
@timothymtorres The wall used in the ruin is
https://github.com/tgstation/tgstation/blob/2a2ad8fd79bc951dc1485eb987445f49473577eb/code/game/turfs/closed.dm#L71
While it could probably be changed to the mineral/deconstructible type they actually look slightly different.

**Comment by iskyp** [comment]
"always been like this" =/= intended
see: decade old atmos miscalculation

**Comment by timothymtorres** [comment]
So it may or may not be intended.  

As far as balance goes, making the walls deconstructible let's a player scavenge a little more alien alloy from the abductor ship.  It is useful to the free golems, and the material amount is limited.  It would allow the construction of a few alien golems, and considering the rarity of the material/ruin location I don't think it should be too gamebreaking to change.  

Thoughts?
