### ISSUE TITLE
Anomalies cannot be disarmed with remote signallers

### ISSUE THREAD

**Issue by Kartograaf** [tgstation/tgstation#37766]
Issue reported from  Round ID: 87669 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
Scanning an anomaly and sending the matching signal no longer disarms it.
Reproduction: Scan any randomly spawned anomaly
Send the matching signal with a remote signaler
Instead of disarming the anomaly, there will be no result and the anomaly will continue to exist
[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by Arianya** [comment]
Had multiple reports across multiple rounds by players.
