### ISSUE TITLE
Defibs can't extend paddles/misters can't expand dong

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#37779]
Issue reported from  Round ID: 87723 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Trying to extend paddles on defibs just makes them snap back in.
1. Spawn Defib
2. Put on backpack slot
3. Click to extend paddles
4. They snap back in without actually expanding.

**Comment by DaxDupont** [comment]
misters are affected too

**Comment by Dunstane** [comment]
compact defibs are 🅱️ roke as well
