### ISSUE TITLE
Cyborg "hand" selection gets stuck.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#37783]
rid: 87735

1. Switch to a borg module like engineering
2. Pick a tool like wrench
3. Make it active(bright green background)
4. Store tool while active
5. Notice how there's no tool but it still shows as active
6. Pick new tool
7. Notice you cannot use new tool
8. Toggle activation of tool
9. notice how tool is now usable

https://imgur.com/a/e86K2j7

**Comment by AnturK** [comment]
@vuonojenmustaturska Something with force move unequip maybe ?
