### ISSUE TITLE
Skewium makes screen turn black after a while.

### ISSUE THREAD

**Issue by Utmanarn** [tgstation/tgstation#37787]
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:) [Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)
It was on my own server.
After use of skewium the screen turns black after some time of screen flipping out up and down (that flipping out part is expected but not the black screen part). After testing about 10 times it gave the same result 9/10 times. Screen just turns black but you can still *see things* at the bottom left where it says what your holding over.
![skarmbild 50](https://user-images.githubusercontent.com/26390071/39895425-7b6f3c9a-54aa-11e8-8fd7-09d293a2effa.png)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)
No testmerges
[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
Take about 40 units of skewium
[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by cyclowns** [comment]
presumably related to ambient occlusion, did you have that enabled?
@deathride58

**Comment by deathride58** [comment]
Are there any runtimes? Does the screen re-appear when you restart dreamseeker?

**Comment by Utmanarn** [comment]
No runtimes from what I know. It does come back when you restart dreamseeker.

**Comment by AlexTheSysop42** [comment]
This happened to me before ambient occlusion

**Comment by Iamgoofball** [comment]
https://file.house/IcY3.webm

Close this.

**Comment by Iamgoofball** [comment]
@Utmanarn What are your specs, exactly? Include BYOND version and your IE version

**Comment by PKPenguin321** [comment]
client crashing juice
ow oof ouch my game

**Comment by Utmanarn** [comment]
Ok, so it happend to more than just me. 4 other persons got the same thing.

**Comment by Iamgoofball** [comment]
@Utmanarn What are your specs, exactly? Include BYOND version and your IE version

**Comment by Utmanarn** [comment]
I used byond verision 511.1382

**Comment by Iamgoofball** [comment]
Computer specs, too
