### ISSUE TITLE
legion core doesnt heal the random movement caused by being hit in the head

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#37798]

**Comment by XDTM** [comment]
for future reference this status is officially confusion

**Comment by AnturK** [comment]
Is it meant to though ?

**Comment by PKPenguin321** [comment]
It's the equivalent of an admin revive iirc, meaning admin heals probably don't fix confusion

**Comment by XDTM** [comment]
we really gotta revisit the whole concept of mixing admin revives with ingame mechanics

**Comment by Barhandar** [comment]
>Is it meant to though ?

It fully heals you and restores hunger, so probably.

**Comment by Shadowflame909** [comment]
The confusion system is wack and needs a rebalance all together. It lasts too long, ling powers don't heal it either. (including reviving stasis) I hate it ree. Also it never goes away!
