### ISSUE TITLE
Nearsightedness may cause the eye damage message to pop up with a welding helmet on

### ISSUE THREAD

**Issue by meijerivoi** [tgstation/tgstation#37796]
Issue reported from  Round ID: 87778 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

It seems like you receive eye damage from welding with a welding helmet on in some cases. As a nearsighted mothman, all my welding results in the eye damage message popping up. I'm not sure if it's causing any damage though. 
Reproduction:
1. Have the nearsighted quick and(/or?) be a mothman.
2. Toggle your welding helmet on as usual and begin welding.
3. _Your eyes sting a little._

**Comment by Therapist1** [comment]
Moths eyes require both welding goggles and a welding helmet to not take eye damage.

**Comment by Therapist1** [comment]
This isn’t a bug. The nearsighted-ness has nothing to do with it. Moth’s eyes are extra sensitive to light.
