### ISSUE TITLE
Some mobs are immune to vaccum, i believe this is a mistake. 

### ISSUE THREAD

**Issue by Ozymandias-1** [tgstation/tgstation#37793]
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)12806 On Citadel station

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
During an attempt to steal the HoS gun, i blew open his office from space, and entered. I was attacked, and followed into vacuu, by the spider araneus. He proceeded to follow me into space, and kill me, because i am a pleb.  But, after checking on him several times after my death, i found that despite the office being breached, he was alive and well. I believe he should have suffocated, as spiders would need air to live.

**Comment by RandomMarine** [comment]
Sergeant Araneus is a map edited space bat and
https://github.com/tgstation/tgstation/blob/3553c12d0bfa4ce2eb75fd2dd0b2d410c167521c/code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm#L38

**Comment by Ozymandias-1** [comment]
Im going to be perfectly, honest, i have no idea what that means. Are you saying its intentional?

**Comment by Ratvar** [comment]
He's saying that Araneus is snowflake codebeast that should be purged

**Comment by Repukan** [comment]
The Law is unkillable

**Comment by AnturK** [comment]
Not really an issue. Also one of the big reasons retaliate needs to be unchained from path.
