### ISSUE TITLE
using a scrying orb made me lose my slime split ability

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#37795]
Issue reported from  Round ID: 87777 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

when i returened i only had regenerate limb power
my species was Xenobiological Jelly Entity

**Comment by XDTM** [comment]
That species should not have the split ability in the first place, are you sure you had it before?

**Comment by Tlaltecuhtli** [comment]
yeah when i finished metagaming with ghosts and returned i didnt have it anymore and i used the health scanner

**Comment by YPOQ** [comment]
I noticed there were several race swap events in that round. It seems likely you were just changed into a different slime species while scrying.

**Comment by optimumtact** [comment]
that would be my guess as well

**Comment by XDTM** [comment]
i think this is closeable, the reason for the change in abilities was pretty clear
