### ISSUE TITLE
Bike horn cannot honk people.

### ISSUE THREAD

**Issue by Jcenderion** [tgstation/tgstation#37803]
Issue reported from  Round ID: 87811 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

The Bike Horn has lost its honkability with it only working on objects or when clicked on. When using a golden horn it causes the flip effect but no horn sound.

**Comment by 81Denton** [comment]
absolute heresy

**Comment by py01** [comment]
This is also occurring with the rubber duck, which also cannot honk people any more.
