### ISSUE TITLE
Missing clothing sprites

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#37817]
These items should either get sprites or get deleted.

* [ ] `/obj/item/clothing/head/helmet/changeling`
* [ ] `/obj/item/clothing/head/hooded/bee_hood`
* [ ] `/obj/item/clothing/head/jester/alt`
* [ ] `/obj/item/clothing/mask/gas/death_commando`
* [ ] `/obj/item/clothing/suit/armor/changeling`
* [x] `/obj/item/clothing/suit/armor/riot/knight/yellow`
* [ ] `/obj/item/clothing/suit/fire/heavy`
* [ ] `/obj/item/clothing/under/cloud`
* [x] `/obj/item/clothing/under/redcoat`

**Comment by ArcaneMusic** [comment]
#46874 fixes  `/obj/item/clothing/under/redcoat`.

**Comment by actioninja** [comment]
iirc changeling "clothing" has the sprite set when it's created. probably should be given a default sprite though.
