### ISSUE TITLE
wielded spears deconvert revs

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#37812]
Tasmin Elliot has attacked Van Darkholm in the head with the spear (Wielded)! 

Van Darkholm looks like it's just remembered its real allegiance! 

round 87847

also >**its** real allegiance

**Comment by PKPenguin321** [comment]
not a bug because blunt trauma to the head has a chance to deconvert
i guess it would make sense if sharp weapons didnt count as blunt trauma though

**Comment by yorii** [comment]
>looks like it's just remembered its real allegiance!

>looks like it has just remembered its [possessive pronoun] real allegiance!

**Comment by yorii** [comment]
Although to be fair I guess this variant should be better:

>looks like they just remembered their real allegiance!
