### ISSUE TITLE
zlevel mob multiplying visual bug

### ISSUE THREAD

**Issue by granpawalton** [tgstation/tgstation#37819]
[Round ID]: 87860

[Reproduction]:  i was pulling my trusty space cat then he multiplied as i was dragging him to next zlevel but only visually and only visually on the zlevel he wasnt on. It could be related to the losing grip bug as it occurs at the same time as that.

https://imgur.com/a/mo0twx8

**Comment by optimumtact** [comment]
@ninjanomnom visual space transition issue?

**Comment by ninjanomnom** [comment]
Probably, it shouldn't be related to losing grip though.

**Comment by optimumtact** [comment]
I think it's just a visual duplication of dragged mobs, no other relation
