### ISSUE TITLE
Lavaproofing clothes do not make them fireproof

### ISSUE THREAD

**Issue by Jord1081** [tgstation/tgstation#37821]
[Round ID]: # 87872 (Sybil)

[Reproduction]: # On an extended round I obtained a lavaproof potion which I applied to some lavaland cult armor and a skull helmet. I walked through lava fine, but upon walking upon a flaming corpse i burst into flames, which damaged me and increased my temperature.

In addition, after being on fire a few more times, my armor deteriorated and was destroyed, causing me to die when I walked into lava.

Considering how long it takes to get lavaproofing armor and how lava is much hotter than fire, a lavaproof potion should probably also give fireproofing as well as lavaproofing.

**Comment by Jord1081** [comment]
Yes, I realize that you should be able to easily get a fireproof potion if you can get a lavaproof one, but I don't see why lavaproofing shouldn't also fireproof clothes.

**Comment by Barhandar** [comment]
Because it's not its job. Also because players' mistakes are players' responsibility and the consequences are funny.

**Comment by Kromgar** [comment]
@Barhandar HOW SHOULD THE CLOTHING NOT BE IMMUNE TO FIRE IF YOU ARE WALKING ON LAVA.

LAVA IS A LOT HOTTER THAN FIRE

**Comment by Barhandar** [comment]
@Kromgar 

Lava temperature at eruption: between 700 and 1200 °C
Butane lighter flame temperature: ~1900 °C
Oxyacetylene welder flame temperature: ~3500 °C

**Comment by Jord1081** [comment]
@Barhandar 
Its not that I "forgot" its that I didn't think it wouldn't fireproof it. And at one point I got lit on fire from a dead legion corpse that fell into lava, I really don't think that fire should be burn hotter than the lava..

**Comment by Kromgar** [comment]
@Barhandar So why the hell does fire proofing your suit not make you lava proof then?

**Comment by ExcessiveUseOfCobblestone** [comment]
From a gameplay perspective you're much more apt to be set aflame than to be burned from Lava, so they should be distinct items.

**Comment by fludd12** [comment]
I made the bottle description say it doesn't fireproof the clothes.

**Comment by kriskog** [comment]
Intended.
