### ISSUE TITLE
Simplemobs recieve no notice of environmental damage.

### ISSUE THREAD

**Issue by Jord1081** [tgstation/tgstation#37820]
[Round ID]: # Any round

[Testmerges]: # None responsible

[Reproduction]: # When playing as a minebot during a plasmaflood I noticed that I was taking damage from the pressure/high temperature without any visual notification.
Normally the player should have a small icon in the top right corner that either shows a thermometer/pressure warning so they know what is wrong and when they are safe again.

Since I cannot tell when I start or end taking damage I have to run far away to an area I know is safe or risk dying arbitrarily.

Note: I only confirmed this for minebots, but I believe the same bug occured in a previous round as a space carp, so I think it might be all simplemobs.

**Comment by AverageJoe82** [comment]
i die to this way too many times, this is an issue with low pressure areas too. It's not a bug since it was never coded to do that I think, my work around was using the health percentage in the status tab.

**Comment by optimumtact** [comment]
simplemobs are not meant to generally be occupied by people, it just so happens that our admins love to stuff people into them

**Comment by PKPenguin321** [comment]
there are a number of ways to play as a simple mob without admin intervention
