### ISSUE TITLE
Broken RPD interface

### ISSUE THREAD

**Issue by DominikPanic** [tgstation/tgstation#37828]
Issue reported from  Round ID: 87886 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

[Round ID]: 87886

[Testmerges]: b99f399fa60ab7f4d13a931a294b5a09c9e3e558

[Reproduction]: The RPD interface has icons missing, even though the pipes_32x32.png file is present.
 _Apparently admin spawned ones dont have the problem_.   Okay, after some confusion this isnt the case, all RPD's have the problem.
I asked more people to see if it affects them and two other people confirmed it. it seems like its a bug. All icons are replaced with little X, the RPD still works but you cant really see what you are going to build. 
![2018-05-13_20-01-25](https://user-images.githubusercontent.com/6252677/39970432-b431e9fe-56eb-11e8-94ee-add9492654e2.png)

[For Admins]:

**Comment by Barhandar** [comment]
Which Internet Explorer version do you have?

**Comment by DominikPanic** [comment]
![iexplore_2018-05-13_20-58-03](https://user-images.githubusercontent.com/6252677/39970703-6d3ec882-56f0-11e8-9041-cfc3c99dc9aa.png)

**Comment by Nabski89** [comment]
Also on Bagil 87895. This worked yesterday.

**Comment by optimumtact** [comment]
@vuonojenmustaturska possibly sprite sheets?

**Comment by Barhandar** [comment]
Spritesheets worked fine for everyone but IE8 users and have shown empty icons (no X) for those when testmerged.

**Comment by SpaceManiac** [comment]
probably sprite sheets somehow, Barhandar brought it up in IRC during the testmerge and I thought it was an IE8 issue, not sure how it would be working most of the time but failing consistently for only some users only in tgui (working fine in goonchat and R&D consoles) though

**Comment by Cyprex** [comment]
I have this issue as well, I am running BYOND via wine/IE8 on Linux. I have tried clearing byond cache and IE cache with no success. This is the only graphics issue I am aware of.
