### ISSUE TITLE
Seven Deadly Sins Ruins Suggestion - Wraith, Sloth, and Lust

### ISSUE THREAD

**Issue by timothymtorres** [tgstation/tgstation#37827]
So far from what I've seen in the code for the current sins it works like this:

### Pride 
* Tranform into chosen mob
* Teleported into space randomly (tough to actually get to the station)

### Envy 
* Dagger that turns you into whoever is stabbed

### Gluttony 
* Injection that turns you into a slug antag that devours everything (antag is pretty weak IMO)
* Must be fat 

### Greed 
* Slotmachine that has a chance to give you wizard powers (not sure if this makes you hostile antag or friendly?)
* May kill you instantly or cause clone damage 

---

Below is a list of different ideas for the unfinished sin based ruins in lavaland.  I'm trying to balance these ideas based on the existing ruins that usually give a reward and drawback to it. 

---

# Wraith

**Wraith is basically about bloodlust.  So we should opt to make it blood themed and aggression.**

`Apperance of Ruin:`  Blood on floor/puddles of blood/dead bodies/etc.

`Requirement to Generate Artifact: ` 
* Cover all ruin tiles in blood
* Cover yourself in blood
* Drink random blood puddle from floor

`Intended Effect:`  (one of these effects is selected randomly)
* Transform player into Slaughter/Laughter Demon
* Transform player into Revenant
* Give player ability to blood jaunt and permanent hulk powers

`Drawback Effect:`
* Player is stuck on harm intent *permanently* 
* Player is given Tourette's (*optional*)

# Sloth

**Sloth is being lazy.  The theme is slowness and not having to lift a finger.**  (literally)

`Apperance of Ruin:` N/A  (ruin is already built)

`Requirement to Generate Artifact:`  N/A (walk to the end of the ruin)

`Intended Effect:`  (one of these is selected randomly)
* Telekinesis + Xray *permanently*
* Transform player into monkey that is infected with Jungle Fever and Narcolepsy

`Drawback Effect:`
* Player is stuck on walk intent *permanently*

# Lust

**Lust is nudity.  The theme is nakeness and obession.**  (trying to avoid turning this into ERP, but *it is lust* after all so obviously it's going to be risque)

`Apperance of Ruin:`  Make it look like a bedroom.

`Requirement to Generate Artifact:`
* Player must not be wearing any clothing or holding objects to enter ruin

`Intended Effect:`
* Spawns a cursed camera and unique handcuffs
* Handcuffs can cuff a mob instantly.  Has a long cooldown before they can be used again.
* Camera works like a flash for revolutionaries.  Only converts a player if they have all clothing slots empty.  Basically nude cultists.
* Deconversion can be soap, wearing clothing, or destroying the camera.

`2nd Intended Effect:` (if the 1st one is deemed too OP)
* An item that removes (all? partial?) clothing items instantly from a target.  The item has a long cooldown between uses.
   
`Drawback Effect:`
* Player gets infected with GBS (infected with STD?) or Hyphema (lust eats away at players eyes) 

---

Now these sin ruins may not be perfect, it is at least pretty consistent with the others as far as reward/risk goes.

**Comment by Barhandar** [comment]
It's "wrath", not "wraith". Wrath is anger, wraith is a ghost.

Arguably, entire Lavaland is the ruin of Wrath. But for specific one... 
I think a better idea for the bonus would be rendering the player gib-proof, permanently... at the cost of having to defeat certain megafauna - either unique to the ruin, or random one targetted in-world, and rendering player hellbound (prevents revival through cloning) until they do so. Better get lucky and not have it target colossus or hierophant!

Sloth already has the working ruin. Adding any benefits or drawbacks would defeat the point.
Also, pretty sure it takes about as long to walk to the end as scientists on station getting the mutations - without drawbacks. And Jungle Fever doesn't even work.
>but it is lust after all so obviously it's going to be risque

Lust is not necessarily sexual lust. It's also overwhelming desire, including desire for pleasures of the body... meaning your idea for Sloth, namely beneficial mutations, actually fits better in Lust.

**Comment by BeeSting12** [comment]
Issues on github is for bugs. Suggestions should go on the forums at tgstation13.org

**Comment by optimumtact** [comment]
suggestions go on the forum
