### ISSUE TITLE
Doors that are sparking dont set plasma on fire (immersion breaking high priority bug)

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#37829]
https://file.house/9ZlD.png

**Comment by Cyprex** [comment]
I feel like this is necessary for balance, as damaged doors aren't necessarily far from from plasma, and often do not get fixed.

**Comment by octareenroon91** [comment]
Airlocks create sparks when they take damage, which can ignite plasma. There's a fire risk already.

Damaged, unpowered airlocks probably also use the sparking sprite.
