### ISSUE TITLE
RPD menu pipe sprites are missing.

### ISSUE THREAD

**Issue by OmegaShoots** [tgstation/tgstation#37830]
Issue reported from  Round ID: 87895 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])
Reporting client version: 512

They're just fucking gone.

**Comment by Barhandar** [comment]
Duplicate of #37828

**Comment by optimumtact** [comment]
dupe

**Comment by OmegaShoots** [comment]
shit had this written up a while ago
