### ISSUE TITLE
Devil crashed the server

### ISSUE THREAD

**Issue by yorii** [tgstation/tgstation#37831]
[Round ID]: 87890

[Reproduction]: Two things that might have contributed to the crash:

1. Reviving a person who had their soul taken out.
2. Devil shot a fireball with rod of ausclepius.

**Comment by Shadowflame909** [comment]
@TheDreamweaver  You have any memecode in that rod that would do such a terrible meme?

**Comment by TheDreamweaver** [comment]
How is the devil shooting fireballs if they have pacifism? Seems like an oversight on whoever coded pacifism.
