### ISSUE TITLE
Proximity sensor assemblies cannot trigger from entering the detection radius

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#37835]
Tested on live server and recent clone of server

Lone proximity sensors function fine, but assemblies do not trigger if you enter the detection radius. I tested this with  prox-signaller and prox-igniter assemblies. 
In addition, making an assembly with a proximity sensor, then deconstructing it leaves the lone proximity sensor unable to trigger through entering the detection radius. Tested this by creating a prox-igniter assembly, deconstructing, then attempting to trigger the lone proximity sensor.

**Comment by ShizCalev** [comment]
```
The following runtime has occurred 51 time(s).
runtime error: Cannot read null.host
proc name: Crossed (/obj/effect/abstract/proximity_checker/Crossed)
  source file: proximity.dm,96
  usr: 0
  src: the proximity checker (/obj/effect/abstract/proximity_checker)
  src.loc: the floor (127,88,2) (/turf/open/floor/plasteel)

```
likely related

**Comment by AlexTheSysop42** [comment]
It looks like it's not setting the `monitor` var
