### ISSUE TITLE
Lings can read the memories of those beyond the grave. 

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#37844]
![image](https://user-images.githubusercontent.com/6778786/40012507-e91039ea-5778-11e8-999c-a37e99a28bda.png)

**Comment by Kromgar** [comment]
Although maybe its just canon that lings gather the salt of their victims

**Comment by SpaceManiac** [comment]
probably caused by #37789

**Comment by ExcessiveUseOfCobblestone** [comment]
please call this a feature

**Comment by davethwave** [comment]
Intended feature don't nerf!

**Comment by ExcessiveUseOfCobblestone** [comment]
In all honesty I think the salt in deadchat helps you better impersonate their character than "WAIT" does.

**Comment by imsxz** [comment]
Time to impersonate characters by prefacing messages with "DEAD: says, "", and using greentexts/netspeak ICly. Time to say "ling reading this a chumbis" when i die to one and am in deadchat.

feature tbh.

**Comment by Shadowflame909** [comment]
poor sarah MCintyre. You can just feel the betrayal and there last attempt at trying to have life.

**Comment by swankcookie** [comment]
@Kromgar is this still an issue?

**Comment by Mooshimi** [comment]
![image](https://user-images.githubusercontent.com/85910816/137574198-8f352c28-a8ea-4b12-9cec-b49d4c252922.png)
I don't think this is still an issue, as I used someone from dchat with lots of dchat logs and the only things I saw were the few messages they said while I absorbed them.

Please reopen if this is seen again.
