### ISSUE TITLE
Disarm and grab intent act like harm intent when using machinery

### ISSUE THREAD

**Issue by zaracka** [tgstation/tgstation#37857]
Round 87970. Bagil.

Be on disarm or grab intent, click on said machines, you attack them with whatever's in your hand.

How it should work: Act like help intent.

**Comment by ExcessiveUseOfCobblestone** [comment]
Are you saying that's how it's suppose to work or that's your personal preference?

**Comment by zaracka** [comment]
Probably how it should work, but it's also my personal preference. As far as I know, everything else works this way.

**Comment by Kromgar** [comment]
Any machine does this

**Comment by ExcessiveUseOfCobblestone** [comment]
That's what I was thinking...

What is "everything else"?

**Comment by Barhandar** [comment]
Tables.

**Comment by zaracka** [comment]
Tables, crates, lockers, extinguisher cabinets, sinks, shutters, airlocks, racks, conveyer belts, firelocks, windoors, buttons. I suppose not everything, but a lot of things. Goes to show you how many inconsistencies there are.

**Comment by ExcessiveUseOfCobblestone** [comment]
can you retitle to say all machinery

**Comment by zaracka** [comment]
> can you retitle to say all machinery

Yes, but are you sure and can you confirm it?

**Comment by dragomagol** [comment]
rip intents
