### ISSUE TITLE
Machinery deconstruct into wrong board

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#37852]
/obj/machinery/computer/rdconsole/production deconstructs into
/obj/item/circuitboard/computer/rdconsole (instead of rdconsole/production)

/obj/machinery/rnd/production/circuit_imprinter/department/science deconstructs into
/obj/item/circuitboard/machine/circuit_imprinter/department (instead of department/science)

**Comment by AlexTheSysop42** [comment]
Syndicate donksoft vendor decons into booze-o-mat parts

>/obj/machinery/rnd/production/circuit_imprinter/department/science deconstructs into
/obj/item/circuitboard/machine/circuit_imprinter/department (instead of department/science)

wew

**Comment by DaxDupont** [comment]
/obj/item/circuitboard/computer/rdconsole is the correct board you nonce

**Comment by DaxDupont** [comment]
wait no reee what is this shit kevinz
