### ISSUE TITLE
problem loading icons

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#37856]
http://take.ms/fU7um

clearing byond cache makes everything black and icon slowly appear until that state while chat is spammed with unable to open cache

**Comment by Barhandar** [comment]
Byond's own clear-cache function is broken, delete the actual folder (Users/[name]/Documents/BYOND/cache) and restart BYOND instead.

**Comment by Tlaltecuhtli** [comment]
i still get the same shit

**Comment by Kromgar** [comment]
Reinstall beyond
