### ISSUE TITLE
Can we please return the roundend report to the chatbox

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#37873]
1. You can't access it after the round ends
2. The pop-up window gets in the way of the post-round murder you're either committing or trying to avoid

**Comment by ShizCalev** [comment]
![image](https://user-images.githubusercontent.com/6209658/40154281-a35a8f6a-595b-11e8-8b3d-7c1c34577493.png)
you can access it by clicking the button in the upper left of the viewport seen here or by clicking the "view report again" prompt in chat.

**Comment by iskyp** [comment]
>The pop-up window gets in the way of the post-round murder you're either committing or trying to avoid
>>the pop-up window gets in the way of my clicking people until they turn turnways

**Comment by RandomMarine** [comment]
What newfren said is my beef with the popup results. Can't double-check it when the server resets.

**Comment by ShizCalev** [comment]
You can view old rounds here, just for the record.
https://atlantaned.space/statbus/round.php

**Comment by Tlaltecuhtli** [comment]
how about round end report saves in that stats website and it gives u a link to it inchat

**Comment by cacogen** [comment]
I wasn't around when it was changed to a pop-up window so I don't know why it was done but it gets in the way of gameplay and not being able to view the report after round end is a problem.

Having to open a separate window in a browser isn't a solution because it removes you from the game.
