### ISSUE TITLE
Welded shut coffins have an odd looking sprite

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#37885]
Tested on a recent clone of the server

If you weld a coffin shut, it gets a grey line overlead on it, the same one as when you weld a locker. However, it looks rather odd on a coffin.
https://gyazo.com/22ade13e59e5df539614c18aa3e007e8

**Comment by DaxDupont** [comment]
The solution is to not make wooden coffins weldable, this is an oversight

**Comment by Barhandar** [comment]
Same way they're disassembled with welder.

**Comment by ExcessiveUseOfCobblestone** [comment]
The welding effect should set it ablaze, burning every~~one~~ item inside.

**Comment by praisenarsie** [comment]
> The welding effect should set it ablaze, burning everyone item inside.

**Comment by Notamaniac** [comment]
haven't coffins been weldable for like several years now

**Comment by py01** [comment]
this got fixed at some point
