### ISSUE TITLE
You can take out a golem's eyes but can't put any back in

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#37889]
Tried doing an organ manipulation on a golem to give them xray eyes. Took the eyes out and tried to insert new ones but couldn't. Called another golem to try to help (was a medical borg) and they couldn't do it either. Old eyes could not be re-inserted. Golem remained blind for the rest of the round.

**Comment by GunHog** [comment]
Oh hey! I was that golem! That was indeed a nasty bug to discover, lol. It is a bit late to ask now, but did you get any feedback when you tried? Perhaps it said that I was wearing something?

**Comment by Barhandar** [comment]
Bug happened relatively recently, a month ago I was doing golem eye surgery just fine.

**Comment by swindly** [comment]
Unable to reproduce with any golem type. What error message appears when failing to insert eyes?

**Comment by nemvar** [comment]
Can not reproduce. Probably fixed by the split of the eye traits.
