### ISSUE TITLE
Removing IDs from a PDA in bag broken

### ISSUE THREAD

**Issue by Michael-Ashfield** [tgstation/tgstation#37893]
Round ID: 88066

If your ID is in your PDA and in your bag, then alt-clicking with an empty hand to remove your ID from your PDA places the ID and PDA in the same bag slot, looking like your ID has vanished.

to recreate:
Put your ID in your PDA
Put your PDA in your bag
Get an empty hand and open your bag
Alt-click your PDA
See as the ID light on your PDA goes red, but your ID is nowhere to be seen
Move your ID into your hand to reveal the PDA beneath it

**Comment by DaxDupont** [comment]
@kevinz000

**Comment by AverageJoe82** [comment]
The interface isn’t updating when you pull it out or something, the Id is probably in there rather than under the pda. iirc closing and opening the bag fixes it. Also it’s probably the same issue as #33388

**Comment by PKPenguin321** [comment]
PDA alt clicking should place the ID at the PDAs `get_turf()` but it's probably placing them at the PDAs `loc`
