### ISSUE TITLE
Crew can obtain Syndicate Encryption Key early in round

### ISSUE THREAD

**Issue by Electronics** [tgstation/tgstation#37917]
In multiple rounds it has been observed that crew can get a syndicate encryption key easily from the syndicate outpost on the asteroid therefore making comms in modes such as in nuclear operatives, or cooperating antags useless, and allows a warning to be given to the station possibly even before the ops have landed.

**Comment by Barhandar** [comment]
IC issue of metagaming.

**Comment by Kromgar** [comment]
Wait what syndicate outpost on what asteroid? It's pretty RNG to find the syndicate listening post anyway

**Comment by Anonmare** [comment]
The space syndicate comms agent. The one that used to be player-controlled but is now a mob again.

In the main room, there's an advanced cam console, a message monitor and a syndicate bowman headset with a syndie encryption key loaded.

**Comment by Kromgar** [comment]
Its not a mob.

**Comment by Anonmare** [comment]
It is, it got demoted from player-spawner for redundancy

**Comment by ExcessiveUseOfCobblestone** [comment]
Outside of lowering the ruin to be not 100% if it isn't already I don't see what there is to be done.

Things happen. It sucks but oh well.

**Comment by kriskog** [comment]
This is gone
