### ISSUE TITLE
Skewium locking up client, and my computer

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#37923]
I don't know if it's a graphics card thing but skewium fucked up my game client and even made my computer lock up, made the screen on the client black out with only flashes of game view, and then after it wore off it caused horrible slowdown for my client.

**Comment by Tlaltecuhtli** [comment]
stop using windows

**Comment by YakumoChen** [comment]
>game that only runs on Windows

**Comment by 81Denton** [comment]
Had the same happen to me just now, it locked up my computer for a few seconds and lagged the game until I restarted the client.

**Comment by Iamgoofball** [comment]
https://file.house/IcY3.webm

Close this.

**Comment by YakumoChen** [comment]
that wasn't even the full effect of what it was doing on my client, goof, which was causing shit to spin around and worse, until eventually it started flashing black and actively froze the client and computer.

**Comment by Iamgoofball** [comment]
post specs

**Comment by YakumoChen** [comment]
![image](https://user-images.githubusercontent.com/10399117/40967781-82978d62-68a3-11e8-8afd-c8d896b6befb.png)
Not that my specs should really matter too much since the game is supposed to be more or less designed to run on a toaster.

**Comment by davethwave** [comment]
Well with it only able to use one core, its not too much of a surprise if the game crashes.

**Comment by CitrusGender** [comment]
Literally crashes my computer.
