### ISSUE TITLE
Hydroponics trays can be deconstructed without opening the panel first

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#37931]
Obj: /obj/machinery/hydroponics/constructable

You don't need to open the panel with a screwdriver; just use a crowbar on it to deconstruct.

**Comment by SpaceManiac** [comment]
Has apparently been like this for all time, one-line fix though.

**Comment by RandomMarine** [comment]
Because when machine construction/upgrading was added for them, screwdriver toggled their irrigation hoses.
