### ISSUE TITLE
Ghost-inhabitated corpses converted to slimepeople can still talk via telepathy

### ISSUE THREAD

**Issue by CodyForrester** [tgstation/tgstation#37950]
Issue reported from  Round ID: 88223 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

This was a wizard round, so a clusterfuck as it was, but
1) Died to lava everywhere
2) Ran around as Ghost, got cloned, died immediately after leaving my pod to lava everywhere again
3) Body turned into a slime person with telepathic link
4) Could still use my telepathic link ability to talk to people while inhabiting my body, and also see/talk on deadchat

Dunno if that's intentional, or a side effect of dying twice, or what.

**Comment by XDTM** [comment]
Your spirit lives on in tge slime's hivemind
