### ISSUE TITLE
Heat transfer through walls

### ISSUE THREAD

**Issue by granpawalton** [tgstation/tgstation#37966]
[Round ID]: 88272

[Reproduction]:  I created the following Atmos setup in an attempt to make nitryl (would love any assistance on that too by the way) and the room outside the heating chamber became super heated without changing the air-mix, not sure if this is a bug or if it is meant to transfer heat through walls like that.

atmos setup in question: 
![bug report 2](https://user-images.githubusercontent.com/36310010/40313714-fb238c78-5cdb-11e8-935d-096a3d33405a.PNG)
room to right of chamber was heated by the plasma glass and i forgot to take a scan near metal walls south of chamber to check that

edit: i put 2 N2 canisters and 2 O2 canisters into the chamber along with about half a N2O canister, also this is the 2nd time ive had this happen with the same setup

admin taken gas analysis of said chamber a while after initial heating: https://i.imgur.com/p4cQh6d.png

**Comment by SpaceManiac** [comment]
This is supposed to happen, if you're superheating an area you need to use rwalls.

**Comment by ShizCalev** [comment]
Intended.
