### ISSUE TITLE
Lavaland Plants have Unremovable Reagents

### ISSUE THREAD

**Issue by Jord1081** [tgstation/tgstation#37967]
[Round ID]: # Doesn't Matter

[Testmerges]: # None

[Reproduction]: # I was an ash lizard nearby a pod base, and wanted to remove the nutriment and vitamins from some of my cactus so it would only have vitrium froth (for healing). However EVERY lavaland plant i found (5 or so) only had 10% nutriment as their reagents, which none of them should have.

After I removed the nutriment, the resulting plants (when grinded) had the reagent amounts that they have by default, even though they should have nothing.

**Comment by ma44** [comment]
The cactus doesn't have a set reagents_add variable, so the product's reagents aren't being changed I guess.

**Comment by Jord1081** [comment]
Adding reagents with the DNA manipulator seems to work, I got banana juice into one of the cacti as a test.

**Comment by ma44** [comment]
The harvested plants have a reagent list, so the reagent list from the harvested plants and the manipulated genes are mixed together.

**Comment by Jord1081** [comment]
Which chems? I feel it makes sense for the lavaland plants to have powerful chems since you would need to get a willing miner AND botanist in order to make good use of it, which is probably unlikely.

Vitrium Froth is less powerful than tricord (although it doesn't seem to have an OD limit)

Tinea Luxor just makes you glow a bit.

Entropic Polypnium does have a lot of debilitating stuff to it (oxyloss, brain damage, toxins, and stamina), but it only has a 20% chance of working each tick, so you would either need to get very high potency plants, or get a lot into your target, especially since they are only 4%.

**Comment by kriskog** [comment]
This has been changed
