### ISSUE TITLE
Living slimes can be sucked into the slime processor and can't resist out.

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#37975]
Getting sucked into a slime processor as a result of being put into stasis by BZ gas leaves you with no option to escape unless someone turns the machine on.

Round ID: 88282

Get made into a sentient slime by xenobiologists, attempt to leave but get knocked into stasis next to the processor, get sucked in, abandoned, have your pleadings to the space gods marked "IC," spend eternity stuck in a machine until the round ends.

Slimes are already forced to crawl out of the machine when it's turned on, why shouldn't they be able to resist out if they aren't dead?

**Comment by GravitronBlue** [comment]
Slimes also can't resist after getting ensnared by vines/kudzu

**Comment by Jord1081** [comment]
I also noticed that I couldn't unbuckle myself or resist off wheni was feeding off of somebody.
