### ISSUE TITLE
Escape pod Safe Containing Emergency Space Suits Unlocked Regardless of Threat Level

### ISSUE THREAD

**Issue by wrightcameron** [tgstation/tgstation#37996]
[Round ID]: # 88332

The escape pods have a feature where if the threat level is red (Code calls it SEC_LEVEL_RED) the pod can be launched to Lavaland and a safe is unlocked containing space suits.  Currently the safe on the escape pod is unlocked regardless of threat level.  This creates a balance issue where anyone on the station can get a free spacesuit from the pod and not have to go to EVA (or department space suits) at the start of the round.

The flavor text of the pod safe says "A wall mounted safe containing space suits. Will only open in emergencies." So I assume the original intention was to have it locked until code red.  The code for this pod safe is located in file [modules/shuttle/emergency.dm](https://github.com/tgstation/tgstation/blob/026fdeaa01e8e4a8763ca639b8e6cf9caeee899c/code/modules/shuttle/emergency.dm#L515), on line 515.

**Steps to Reproduce:**
1. Join game or start server
2. Check threat level to see if it is not threat level **red**
3. Go to escape pod, click and drag from safe to character model
4. Safe opens up and contents of safe can be removed.

**Actual Results:**
The safe on the escape pod can be accessed during lower threat levels of blue or green.

**Expected Results:**
If threat level is Red contents of safe should be able to be removed, if the threat level is green or blue the safe should be locked and give a warning similar to trying to launch the pod to Lavaland during threat level green or blue.

**Other notes:**
I included [Round ID] because of formatting and guidelines but this bug is very easy to reproduce, it was over the course of a few rounds that I discovered that you can take space suits when threat level is not red.

**Comment by 81Denton** [comment]
Can confirm this, you can access the thinga even on green alert.

**Comment by SpaceManiac** [comment]
The cabinets are being unlocked automatically by the shuttle moving from the shuttle loading zone to their location on the station.

**Comment by chesse20** [comment]
free spacesuits are balanced if you make them slow you down(which most do already) please someone give plasmamen spacesuits instead of envirosuits
