### ISSUE TITLE
Feature Request - Window Screen Circuit

### ISSUE THREAD

**Issue by Jared-Fogle** [tgstation/tgstation#37991]
I may or may not crack and code this myself, so this may just end up acting as a discussion.

I want to make wall-mounted circuits for things like chats or whatever. The best way to do this is using a large screen, which is only on examine.

I suggest a window screen circuit, which when examined opens up a window like paper does with BBCode on it. Perhaps there can be varying sizes that allow more lines/characters on the screen.

Pulse In:
prepend line
append line
clear screen

Pulse Out:
on clear?
on append?

Data:
line to write (text) - the line to prepend/append
make new line (bool) - when appending or prepending, should a new line be put after?
accept bbcode (bool) - should `[b]text[/b]` be displayed as **text** or [b]text[/b]?

**Comment by Jared-Fogle** [comment]
lame

**Comment by arsserpentarium** [comment]
You've been heared.
