### ISSUE TITLE
Flamethrower is not craftable through the crafting menu

### ISSUE THREAD

**Issue by TribeOfBeavers** [tgstation/tgstation#38007]
Issue reported from  Round ID: 88351 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Although it appears on the crafting list, having all the ingredients and tools doesn't allow it to be crafted by clicking the craft button; It stays greyed out.

Standard slapcrafting still works.

**Comment by Tlaltecuhtli** [comment]
/obj/item/flamethrower/full has all the parts maybe use that and remove the parts() ?

**Comment by CitrusGender** [comment]
@Tlaltecuhtli Disassembled a flamethrower/full and still wasn't able to make it. Something is wrong here then. Not sure what, other recipes use a pipe and igniter but not a welding tool. That may be the issue here but I'm not sure.
