### ISSUE TITLE
thrown objects take up the entire tile's clicking space

### ISSUE THREAD

**Issue by Hatterhat** [tgstation/tgstation#38013]
Issue reported from  Round ID: 88377 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

[Round ID]: 88377

[Testmerges]: 37867: 'Adds an admin punishment: Spewapalooza

[Reproduction/Issue]: Throwing stuff causes them to take up the whole tile's clicking space. To reproduce, throw a thing (i.e. sunglasses, flashlight, etc.) and watch as it takes up the entire clicking space of the tile.
EDIT: okay so turns out sec bowman headsets aren't affected

[For Admins]: Nothing, really.

**Comment by SpaceManiac** [comment]
The problem is not throwing but placing the item into storage. It is set to take up the whole tile's clicking space while it's in the inventory but this status is not properly reset when it is removed.

@kevinz000
