### ISSUE TITLE
Drones can see Revenants while they're supposed to be invisible

### ISSUE THREAD

**Issue by Alterist** [tgstation/tgstation#38016]
It's been a while since the round I experienced it but whatever.

So drones can see revs even when they're supposed to be invisible to everyone.
I could even hit it when it was invisible, although I couldn't be sure if I did damage to it, as there was no on-hit message showing up in the chat
[Reproduction]: 
1. Spawn Rev
2. Spawn as Drone
3. See a staticy griff ghost

**Comment by DaxDupont** [comment]
the solution is to remove drones
