### ISSUE TITLE
Scanning a chameleon projector disguise with a chameleon projector turns you invisible

### ISSUE THREAD

**Issue by Alexch2** [tgstation/tgstation#38015]
[Round ID]:  88379

[Reproduction]: Person A becomes literally any object with their chameleon projector.
Person B scans person A, while person A is disguised.
Person B will now be completely invisible and impossible to click on, or otherwise interact with short of bombing the place you think they're in.

This is particularly bad with nuke ops, as they can now instantly [*teleports behind u*] the disk holder.
You can't even right click the tile. They don't even show up on that. They're completely untouchable.

**Comment by ExcessiveUseOfCobblestone** [comment]
If the temp object 1 takes on the appearance of object A (literally `1.appearance = A.appearance`), why is it that when 2 scans 1 it doesn't get the appearance of object A like `2.appearance = 1.appearance (== A.appearance)`?

**Comment by ExcessiveUseOfCobblestone** [comment]
Also pretty sure champro isn't available to ops normally.

**Comment by YakumoChen** [comment]
it is, I've done ChamPro ops half a dozen times
