### ISSUE TITLE
If you set blocks_air = TRUE on open turfs they runtime

### ISSUE THREAD

**Issue by imtakingabreakdontatme** [tgstation/tgstation#38012]
Seems weird to have a var you are not allowed to use

@ninjanomnom @duncathan @MrStonedOne I figure you guys are most knowledgable about atmos and where I might start looking to fix it or an alternative I can use to not have open turfs lose air other than 60 invisible tiny fans

[10:45:34] Runtime in LINDA_turf_tile.dm,63: Cannot execute null.remove().
  proc name: remove air (/turf/open/remove_air)
  src: the tear in the fabric of real... (51,28,1) (/turf/open/indestructible/binary)
  call stack:
  the tear in the fabric of real... (51,28,1) (/turf/open/indestructible/binary): remove air(0)
  Janelle Russell (/mob/living/carbon/human): breathe()
  Janelle Russell (/mob/living/carbon/human): breathe()
  Janelle Russell (/mob/living/carbon/human): handle breathing(8)
  Janelle Russell (/mob/living/carbon/human): Life(2, 8)
  Janelle Russell (/mob/living/carbon/human): Life(2, 8)
  Janelle Russell (/mob/living/carbon/human): Life(2, 8)
  Mobs (/datum/controller/subsystem/mobs): fire(0)
  Mobs (/datum/controller/subsystem/mobs): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)

**Comment by ninjanomnom** [comment]
I use the var in shuttles but only for very short periods of time, has this runtime popped up on live servers before now?

**Comment by KorPhaeron** [comment]
No clue

I resolved it by setting their CanAtmosPass or whatever instead

**Comment by AnturK** [comment]
Initialization only setups turfs without it so it's not properly set up.

**Comment by MrStonedOne** [comment]
ya its a compile time var that basically makes atmos treat it like a wall or closed turf, it has the side effect of blocking automatic changes to the turf's CanAtmosPass, hence why shuttles use them to when moving turfs arounds.
