### ISSUE TITLE
Ghosting in VR brings up the real ghosting menu, which can ghost you for real if you accidentally click the wrong button

### ISSUE THREAD

**Issue by AlexTheSysop42** [tgstation/tgstation#38021]
Round 88387, I was trying to investigate a bug involving VR ghost, but ended up misclicking and killing myself permanently

**Comment by SpaceManiac** [comment]
Would it make sense to change the override to throw you out of VR but *not* bring up the original Ghost menu? Not sure whether that's really a good idea though.

**Comment by DaxDupont** [comment]
I mean I could take that as feature request sure, but it's not a bug.

**Comment by SpaceManiac** [comment]
Fixed by #37915
