### ISSUE TITLE
Humans don't die with negative blood

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#38024]
id 88397

ok so pro strats here
if you have the blood deficiency thing and you get changed to a race that doesn't get effected by bloodloss you can go into negative blood and even when you switch back to human you don't die (given you are below 0% at that point)

**Comment by msgerbs** [comment]
Seems to be caused by this line https://github.com/tgstation/tgstation/blob/e5eba087cded0d1f27e13435bb1771df632d694d/code/modules/mob/living/blood.dm#L71

**Comment by msgerbs** [comment]
I'm curious, how did you end up with negative blood? As far as I can tell, bleed() shouldn't allow you to hit negative blood. This should be fixable by changing up that line above, but it's probably better to prevent having negative blood in the first place.

**Comment by Spaceinaba** [comment]
I have the blood deficiency trait that drains your blood level gradually while stuck as a race that doesn't use blood for anything

**Comment by Armhulen** [comment]
Seems like it would be better to stop blood from being removed if you're a noblood species, and set blood when changing species. Finally, just make a check if you have negative blood and instantly kill a mob that has negative blood.
