### ISSUE TITLE
Fried monkey hides spontaneously become un-fried when eaten

### ISSUE THREAD

**Issue by msgerbs** [tgstation/tgstation#38025]
[Round ID]: # 88400

[Testmerges]: # #37867: 'Adds an admin punishment: Spewapalooza' by Armhulen at commit b13873b73e 

[Reproduction]: # Obtain a monkey hide, fry the monkey hide (the ones I ate were lightly-fried but it probably works with any level of fried), eat the monkey hide. The monkey hide will drop at your feet, un-fried, after the first bite. You can fry this hide and repeat this infinitely.

**Comment by msgerbs** [comment]
Seems this happens with brains as well.

**Comment by cacogen** [comment]
I think this happens with everything deep fried. Instead of being consumed the item is returned unfried.

**Comment by msgerbs** [comment]
Definitely not everything, I was able to eat fried monkey meat without issues. Perhaps every inedible fried item?

**Comment by SpaceManiac** [comment]
AFAIK, this is intended behavior when frying non-edible items.

**Comment by msgerbs** [comment]
I don't recall this ever being the behavior before, and I've eaten plenty of inedible fried items. If it is intended, there should probably be some message indicating what happened besides the usual "you bite the thing" message.

**Comment by AverageJoe82** [comment]
i thought this was a feature, its not just monkey hides its any non food item that can be refunded, so like cult bastard swords can be deepfried and put into your pocket then you can eat it later when you need a quick weapon

**Comment by ShizCalev** [comment]
This has been the behavior for quite a while (6~ months)

also @AverageJoe82 I fixed the size swapping issue a long while back.
