### ISSUE TITLE
Security bots don't increase threat level for weapons worn on back

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#38033]
Sec bots give +2 threat level for weapons worn on the belt slot (+4 for inhand), but the back slot is ignored completely:

https://github.com/tgstation/tgstation/blob/ba1030f8038f07bfba17d4b2887c584d09b8c9fe/code/modules/mob/living/carbon/human/human.dm#L571-L578

**Comment by 81Denton** [comment]
I think it also involves lasertag turrets

**Comment by ShizCalev** [comment]
Lasertag weapons are handled in the line above it, and they can't be put on back so it shouldn't be a concern atm.
