### ISSUE TITLE
Egg

### ISSUE THREAD

**Issue by Sunoplyrus** [tgstation/tgstation#38036]
88417 Sybil 512
Egg
![dreamseeker_2018-05-24_12-52-48](https://user-images.githubusercontent.com/31968974/40497056-a21f3bf4-5f51-11e8-85cd-b837243b51c3.png)
![dreamseeker_2018-05-24_12-52-13](https://user-images.githubusercontent.com/31968974/40497058-a247293e-5f51-11e8-9c07-51eb0fde0b98.png)
Happened while pouring out eggs from a tray.

Also this just in, containers broke 
![dreamseeker_2018-05-24_13-04-28](https://user-images.githubusercontent.com/31968974/40498934-cdd2dd0a-5f56-11e8-9ee2-d8a167692c48.png)

**Comment by ShizCalev** [comment]
Closing in favor of #38041
