### ISSUE TITLE
The ability to have different kinds of static overlays in drones is too niche of a feature to continue supporting.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#38031]
I bet if I did a scan of preferences I'd find 99% of people never change it from default and it involves allocating a bunch of images for mobs then looping over all of them whenever we want to do anything with them.

See #38019 for an example of why its not worth the hassle to continue supporting.

@RemieRichards tagged to defend their feature if they want.

**Comment by RemieRichards** [comment]
Only included the others as the original /vg/ pr had them, and they seemed interesting.
The best really is the default so probably best to remove the others.

**Comment by Alterist** [comment]
I would really prefer if the static overlay was gone, to be honestly.  Currently the overlay breaks for no reason. This issue still exists: https://github.com/tgstation/tgstation/issues/29717  (Hell, I don't even know why it was closed) and removing drone filters was put forwards as an solution, but that was axed for some reason.

**Comment by Alterist** [comment]
And holy shit this this was an issue from back then. Ash drake sprites(and other large sprites) are fucking broken: https://imgur.com/YXHJVoJ I didn't think it would matter, but I've killed half the station because I didn't know what the fuck I was looking at until it was too late.

**Comment by chesse20** [comment]
i love the drone extra overlays DONT REMOVE

**Comment by AlexTheSysop42** [comment]
The static overlay looks terrible, if only one is kept make it the void one

**Comment by zaracka** [comment]
I like this personally, but the filter is kind of a foolproof way of knowing what you can and cannot interact with.

**Comment by Alterist** [comment]
> the filter is kind of a foolproof way of knowing what you can and cannot interact with.
Sadly not true, beings as defined in the code is different from beings defined by policy

**Comment by Shadowflame909** [comment]
The animal one is pretty nice and I like it. The void one also looks cool though and more easy to understand. I'd be at a tie between those two.
