### ISSUE TITLE
ID's telepotation.

### ISSUE THREAD

**Issue by Archemagus** [tgstation/tgstation#38037]
1) ShitSec load his ID into secdata console.
2) Cyborg eject his ID
3) ID spawns under borg.

Is it window on the way? Wall? All station? No matter.

**Comment by AlexTheSysop42** [comment]
Oh that's... fun.

One time I ejected an AA id as an AI and I disappeared, guess it just teleported to me.

**Comment by Tlaltecuhtli** [comment]
i did see an ai stealing hop id this way time ago i tought it was fixed

**Comment by AlexTheSysop42** [comment]
>AI-stealing hop id

Impressive for an inanimate object to steal an AI

**Comment by ExcessiveUseOfCobblestone** [comment]
This is a dupe of a very old bug.
