### ISSUE TITLE
Visible numbers on items outside storage

### ISSUE THREAD

**Issue by zaracka** [tgstation/tgstation#38041]
Round 88421. Bagil.

I think it applies to any item that has numbers when stacked in storage, but for sake of accuracy I'm going to mention only one.

Machine parts taken out of an RPED and thrown onto the ground keep their stack number.

![ss13 visible numbers on items outside of storage bug](https://user-images.githubusercontent.com/37943475/40503870-7819a3d8-5f5d-11e8-9f35-f951ca100ef6.PNG)

**Comment by Sunoplyrus** [comment]
Hey I did a nice job fu

**Comment by Teepeepee** [comment]
![image](https://user-images.githubusercontent.com/17479709/40510936-9526f81a-5f74-11e8-9a1e-3e30d6b0325c.png)
yeah, any stackable item

**Comment by Teepeepee** [comment]
![image](https://user-images.githubusercontent.com/17479709/40511575-86d6c39c-5f76-11e8-8961-f9590a3ffea0.png)
it gets worse, every single item keeps their number and dropping many on the same tile induces suicide, not only that but if you had the container you dropped them from open the sprites of that item won't leave the spot it took on your screen before being dropped until those items stop existing.

**Comment by ShizCalev** [comment]
mai immersion

**Comment by 81Denton** [comment]
>dropping many on the same tile induced suicide

how in the name of honk

**Comment by Teepeepee** [comment]
just look at it, I fucking surrendered after that.

**Comment by DaxDupont** [comment]
How the fuck

**Comment by AlexTheSysop42** [comment]
Confirmed, happened to me too

**Comment by Kromgar** [comment]
Who fucked with the storage last?

**Comment by Kromgar** [comment]
![image](https://user-images.githubusercontent.com/6778786/40523218-a4240b22-5fa2-11e8-89db-a8aee6d04978.png)


![image](https://user-images.githubusercontent.com/6778786/40523230-b4f4e5b6-5fa2-11e8-9e97-8de5932402db.png)

**Comment by Jord1081** [comment]
If you reconnect the items will disappear off your HUD.

**Comment by davethwave** [comment]
Also works if you throw or drop the bag that your using if I remember right.

**Comment by ShizCalev** [comment]
#37943 perhaps?

**Comment by ShizCalev** [comment]
@SpaceManiac

**Comment by SpaceManiac** [comment]
Can't reproduce, I suspect #38022 may have fixed it

**Comment by SpaceManiac** [comment]
Repro before & no repro after baf3fbb, calling this one fixed.
