### ISSUE TITLE
Spawning in as Syndicate Mediborg defaults to an uninteractable black screen

### ISSUE THREAD

**Issue by KomradeSpectre** [tgstation/tgstation#38057]
Issue reported from  Round ID: 88443 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

![image](https://user-images.githubusercontent.com/12734451/40526185-bcec240e-5fb2-11e8-8f18-137903a7ff9b.png)

Reproduction: Accept the 'Do you want to be a Syndicate Mediborg?' ghost role from Nuclear Emergency. Enter hell.

Can't talk, Can't move, Can't see, only can complain.

**Comment by Therapist1** [comment]
This also happens with regular reinforcements, not sure why.

**Comment by Armhulen** [comment]
That's nullspace

**Comment by Armhulen** [comment]
Probably a runtime that explains it well

**Comment by davethwave** [comment]
That once happened to me a while back when a bluespace anomaly ticked to 0

**Comment by Shadowflame909** [comment]
Yeah. I had to click ooc and stop viewing camera. It went away after like 10 seconds. Or maybe an admin teleported me? Who knows!

**Comment by SpaceManiac** [comment]
I highly suspect that the repro case is refunding the spawner while ghosts are being polled.
