### ISSUE TITLE
Navbeacons: can't be built/deconstructed

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#38064]
- Underfloor bot nav beacons (/obj/machinery/navbeacon) can't be built/deconstructed.
If just one beacon is sabotaged/broken, all patrolling bots will start pathing back and forth between the last intact one and the second to last one.

- There is no overview of roundstart beacon names and their transponder codes. If someone changes a beacon's name/transponder codes, there is no way to find out the proper ones short of opening the map file and looking for its `codes_txt` and `location`.

**Comment by Jalleo** [comment]
@81Denton this is goon code it probably hasnt been touched from back when robotics was under the CE or something.
