### ISSUE TITLE
Admin messages report old accounts as new ones

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#38070]
Issue reported from  Round ID: 88460 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

ADMIN LOG: Ekaere/(Ekaere) (IP: -snip-, ID: -snip-) is a new BYOND account days old, created on 2011-06-22.

**Comment by Tlaltecuhtli** [comment]
1922?

**Comment by BeeSting12** [comment]
I'm surprised noone's reported this yet, it's been an issue since I started adminning. I always assumed it was reported.
