### ISSUE TITLE
Mindswap may cause UI style change

### ISSUE THREAD

**Issue by Michael-Ashfield** [tgstation/tgstation#38081]
[Round ID]: #88480
If you mindswap into a player who has a a different UI style, you will be given the other users chosen UI style.
This is very similar to a recent fix (#37943) which mindswap gave the user the targets ambient occlusion.

To recreate:
>Have a UI style such as Midnight
>Have a player with a different UI style, such as Retro
>Get mindswapped into that other player
>You now have their UI style on your screen

**Comment by ShizCalev** [comment]
@SpaceManiac

**Comment by SpaceManiac** [comment]
HUD styles will need the same treatment that occlusion got in that PR. I'll take a look but it'll probably be a little more complicated.
