### ISSUE TITLE
Examining lathes do not list material contents

### ISSUE THREAD

**Issue by Jord1081** [tgstation/tgstation#38099]
[Round ID]: # Seen in multiple rounds

[Reproduction]: # Examine any lathe or circuit imprinter, they will always say that they contain nothing. I know this has worked in the past.

**Comment by SpaceManiac** [comment]
@kevinz000 easy fix

**Comment by Cyprex** [comment]
This bug has been around for a while, at least a week or two, was it not reported before?

**Comment by Cyprex** [comment]
Exosuit fabs are also affected.
