### ISSUE TITLE
Flashlights/light sources work from inside bags

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#38109]
Issue reported from  Round ID: 88558 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

1. Grab a backpack
2. Grab a light source
3. Put backpack on the floor
4. Put light in bag
5. Observe as backpack now emits light
6. Pick up backpack
7. Backpack no longer emits light
8. Throw backpack back on the floor
9. Backpack emits light again

**Comment by DaxDupont** [comment]
@kevinz000 pls

**Comment by zaracka** [comment]
So what you're saying is flashlights are strong enough to shine through jumpsuits (when they're in your pocket) and lab coats (when they're in your suit slot), but not backpacks.

**Comment by DaxDupont** [comment]
@zaracka welcome to gameplay balance

**Comment by AnEggGit** [comment]
@DaxDupont go play baystation

**Comment by DaxDupont** [comment]
Flashlights actually don't shine through worn bags, or even bags in your hand.

Just bags on the floor. I fail to see how this is not a bug.

**Comment by zaracka** [comment]
I was kind of making a joke, but what if flashlights actually didn't emit light through pockets and suit storage? Would that change be too crazy?

And yeah, based on the way you said it works, it's clearly a bug.

**Comment by CitrusGender** [comment]
is it really a bug though
This may just be a balancing thing.

**Comment by timothymtorres** [comment]
Tested again today and this was fixed at some point.
