### ISSUE TITLE
Firesuit has no armor component

### ISSUE THREAD

**Issue by Electronics** [tgstation/tgstation#38112]
Firesuits don't appear to have any armor vars meaning that they don't block bio or even absorb some amount of lasers.

**Comment by Buggy123** [comment]
For consistency, probably yeah.

**Comment by Electronics** [comment]
It must be almost the single piece of pressure resistant clothing that doesn't have it.

**Comment by Buggy123** [comment]
yeah, it doesn't need to be _much_ but for consistency you'd expect something like 5-10 laser and maybe 20+ bio.

They slow, anyway, so no powergamers are going to start wearing them every round.

**Comment by Jalleo** [comment]
its probably been missed it likely had protection beforehand someone should check via the history.
