### ISSUE TITLE
lizard and other nonhumans having forced last names

### ISSUE THREAD

**Issue by Spaceinaba** [tgstation/tgstation#38117]
bug is on sybil i dont admin bagil lol
round id: all of them with the config option that forces last names enabled
![image](https://user-images.githubusercontent.com/20155238/40595176-b3d7b2dc-61f8-11e8-8e45-b44c66854d40.png)

**Comment by CitrusGender** [comment]
what inaba meant to say is:
the "HUMANS_NEED_SURNAMES" is not affecting only humans

**Comment by CitrusGender** [comment]
also I tried this on Terry and Sybil and I was able to have a lizard name as a human and as a lizard. I can't reproduce this.
