### ISSUE TITLE
Regular crewmembers can use blood-cult items now

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#38125]
Server: Sybil
Round ID:88597
Regular crewmembers can use ALL cult items now without any dizzy effects or stuns or messages against that of any kind. Zealots Headband, Mirror Shield, Bloody Bastard Sword. THEY'RE ALL USABLE!!

**Comment by Therapist1** [comment]
*scream

**Comment by Tlaltecuhtli** [comment]
mirror shields were able to be used before, there was a dizziness tweak but you say even stuns dont work?

**Comment by Tlaltecuhtli** [comment]
uhhh it seems this pr disabled all kind of stun to not cultists http://github.com/tgstation/tgstation/pull/37823/files

**Comment by ExcessiveUseOfCobblestone** [comment]
@DaxDupont really nibba

**Comment by DaxDupont** [comment]
@ExcessiveUseOfCobblestone Welp people/maintainers told me to remove the stuns and the drops don't blame me.

Too busy to fix much this week.

**Comment by DaxDupont** [comment]
At least the crew will have a chance now I guess lmao

**Comment by Therapist1** [comment]
“people/maintainers”

**Comment by DaxDupont** [comment]
maintainers aren't people

**Comment by ShizCalev** [comment]
intentional.

**Comment by Shadowflame909** [comment]
What a triggering buff. WTF?

**Comment by Shadowflame909** [comment]
NO WAIT. RE-OPEN THIS @ShizCalev  I can prove this is not intentional. @DaxDupont 
![dax dupont](https://user-images.githubusercontent.com/29222521/40630069-43fb4352-6284-11e8-9929-91b94eca6c46.png) WHAT DID THEY MEAN BY THIS? The use penalty is completely removed!

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/f48e8542e77e98a3b84e60b1ba50d987e4a40c95/code/modules/antagonists/cult/cult_items.dm#L50-L61

**Comment by Shadowflame909** [comment]
That's pretty lame. Not all of them have a use penalty. So some items are completely risk free, like zealots blindfold. Free x-ray + medhud and Bloody Bastards Sword. which is head of the blood cult only!

**Comment by DaxDupont** [comment]
the solution is to remove cult obviously

**Comment by Shadowflame909** [comment]
We would have no cult modes left though.

**Comment by lolman360** [comment]
remove little timmy's first oc cult please

**Comment by kriskog** [comment]
This isn't the case anymore.
