### ISSUE TITLE
Posibrain/MMI in Odysseus can't load syringes or see medhud

### ISSUE THREAD

**Issue by Ispiria** [tgstation/tgstation#38130]
Issue reported from  Round ID: 88618 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

[Round ID]: #88618

[Reproduction]: Seems to be an issue where MMI brains or posibrains have difficulty loading syringes into an Odysseus, and also lack a medhud once in them. I built a posibrain Odysseus mech several rounds earlier this morning myself and it reported having trouble loading syringes, but for some reason this spontaneously resolved itself a short time later - in the round being reported, an MMI brain Odysseus couldn't load syringes at all and wound up being admin-removed from the Odysseus because nothing we tried was helping. The medhud issue seems to be consistent for both types of brains loaded into Odys, though.

**Comment by SpaceManiac** [comment]
Fixed by #41167
