### ISSUE TITLE
YOU CAN VIEW OBJECTS FROM OTHER Z-LEVELS WITH THEIR MIRAGES.

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#38137]
Round ID: 88632

Server: Sybil

This is some serious memetic stuff coder-bus. I hope this gets fixed soon.

![](https://i.gyazo.com/2fc0362e278e36e0b37ac3dbe4f6d265.png)

The mirage holder, this bug allows you to view items, mobs, tables, literally anything from SEPARATE Z-LEVELS as if you were watching them on some sort of camera or something.

1. I tried to pull a syndicate tool-box from a separate z-level. I accidentally ended up pulling its mirage form. IE. What you see from across z-levels (a picture of that at the end.)

2. I ended up putting the mirage of that item on station and once I realized it was a dupe, I went back for it across z-levels.

3. This is when stuff got weird, the admins could see me at the station when I was actually in a different z-level! I was just phasing in and out of the toolbox!

4. With testing from Nevere we realized that we could pull the Z-level IMAGERY. (IE that image you see when you're about to head into the next z-level.) OF ANYTHING and we could bring it to the station, and literally, observe a z-level object from the station!

How can this be abused: You can literally bring a mirage of bubblegum on the station, and you can see him stomping around as if he was actually on the station. But it's just an image of him, and he's actually on a z-level of across from the station. This is some weird buggy byond code stuff.

How can this be fixed: By being a lamer and just not allowing you to pull mirages. OR we can try to solve that problem from the beginning of z-levels existing where you can't drag items across z-levels! Only push them and throw them!

The final image of me duping myself, and being able to view myself across z-levels.

![](https://i.gyazo.com/40cf7018dc2ab0ca3b033620965f1a84.png)

I hope this has been a very detailed explanation of the hazards, the bugs, and the problems z-level dupings can do. Coders when will we be able to drag items across z-levels so this doesn't occur more often? Thanks and have a good day!

Edit: With this image given to me from the admins, turns out I did something much worse for the ghosts.  I ended up breaking the barriers to the z-levels for them and they ended up duped as well! Say hi to Wubli and Nevere!
![i broke the z-level barriers for ghosts as well haha poor byond code](https://user-images.githubusercontent.com/29222521/40631797-ba353ffe-6294-11e8-96a7-9ef7ba75a67a.png)

**Comment by SpaceManiac** [comment]
mirage holder needs to be anchored, #37819 possibly related

**Comment by Shadowflame909** [comment]
I believe it is. I've duped and dragged myself before. But the duped version of myself I'm dragging usually dissapears a second later. This is the first time I've seen it become a serious issue to this extent!

**Comment by Therapist1** [comment]
He is the one.

**Comment by deranging** [comment]
i was the scientist who ahelped the issue

**Comment by Shadowflame909** [comment]
I was grabbing a toolbox from across the z-levels and I was seen in science when I was across a z-level. ^
