### ISSUE TITLE
Blood Cults manifest rune is broken

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#38135]
[Round ID]: 88627
Server: Sybil

1. Use the manifest rune with patient ghosts. ALL THE MANIFEST BODIES END UP BRAINDEAD.

Holy shit the cult that round literally needed 1 more person to summon but because of this bug they had 20 braindead bodies. wtf is this??

**Comment by zaracka** [comment]
This is because the ghost limit check happens after the mob is created. What really happened was you went over the ghost limit (4) so the subsequent invocations spawned braindead mobs. It's not supposed to invoke at all.

**Comment by Shadowflame909** [comment]
All the ghosts were braindead. It first started with some braindead standing up. They got ashed, and then it just started to spew braindead bodies while there were like 10 ghosts on the manifest rune.
