### ISSUE TITLE
Syndicate Medborg Cannot use Defib unless in slot 1

### ISSUE THREAD

**Issue by Jord1081** [tgstation/tgstation#38142]
[Round ID]: # 88640 and #88642

[Testmerges]: # #38075: 'Make typecache checks twice as fast, stop using single-type typecaches where appropriate' by vuonojenmustaturska at commit f695eacdfb
#38002: 'refactors overlays to append/remove instead of cutting' by optimumtact at commit 666e0bdfbe

[Reproduction]: # Become a syndicate mediborg and try to activate the defibrilator in hand. It will work if in slot one, but if in any other slot with not activate and give the message "You need your other hand to be empty!"

Note: I don't know if this is also an issue with the regular mediborg.

**Comment by YakumoChen** [comment]
Borgs don't have hands, Alex.

**Comment by AlexTheSysop42** [comment]
Of course they don't have hands which is why it's foolish to assume I meant actual hands rather than modules, which work almost just like hands but is slightly slower to type.

**Comment by Jord1081** [comment]
Yes, even when only one module was active (the defib) it still wouldn't work in slots 2 or 3. I don't remember for sure, but i believe the defib worked in slot 1 when slot 2 and 3 were occupied.

**Comment by CitrusGender** [comment]
So I just tested it. It's not that it will only work in slot one, it's that it won't work if something else is in a different slot. You can have it in any slot but as long as the other ones are empty, it will work. This is still a bug though.
