### ISSUE TITLE
when cargo shuttle is called, the status displays show 00:03 rather than 01:03

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#38157]
the timer starts slightly over 1 minute; when it reaches 1 minute exactly, it does seem to go to 01:00, but when it's over a minute it shows 00:xx instead of 01:xx

**Comment by AlexTheSysop42** [comment]
Pretty sure it's because that means there's 3 seconds until departure, for any last minute orders or something

**Comment by SpaceManiac** [comment]
There's a phase before the shuttle launches where the thrusters wind up. This is more of a design issue with the cargo shuttle monitors, if it didn't say "CARGO" it would say "IGN" for ignition. The emergency shuttle acts the same way.

**Comment by SpaceManiac** [comment]
0:03 until ignition, ... 0:01 until ignition, ignition, 1:00 until arrival, 0:59 until arrival, ...

**Comment by msgerbs** [comment]
Oh I misunderstood what the issue was, this is talking when it's arriving from centcomm.

**Comment by kriskog** [comment]
Not a bug, you are also able to keep shopping for the duration of the ignition timer.
