### ISSUE TITLE
It's possible to burn through indestructible tiles

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#38167]
Issue reported from  Round ID: 88714 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

1. Spawn indestructible floors (/turf/open/indestructible) on centcom or wherever
2. Spawn toxin/oxygen canisters
3. Start a fire with them, observe how indestructible tiles disappear.

**Comment by DaxDupont** [comment]
@ninjanomnom ?

**Comment by Jalleo** [comment]
@DaxDupont likely due to code that has changed somewhere look at turf/open and the indestructible to see where it went wrong.

**Comment by Cyprex** [comment]
If this is from the round with sepia floor tiles, I was using thermite to burn it.

**Comment by DaxDupont** [comment]
No, sepia tiles aren't indestructible.

**Comment by MrDoomBringer** [comment]
You can do this in VR, that's where I first noticed it.
