### ISSUE TITLE
phazon can achieve sanic speed by moving diagonally

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#38177]
When phasing is active, moving diagonally into a long wall will cause you to move two tiles in a cardinal direction rather than diagonally onto the wall. This basically lets you double your speed on corridors.

**Comment by praisenarsie** [comment]
@ninjanomnom

**Comment by Teepeepee** [comment]
Don't know if it's related, but janicart, secway and other vehicles ignore the diagonal speed slowdown too.

**Comment by SpaceManiac** [comment]
this is actually return of drifting

**Comment by ArcaneDefence** [comment]
This is no longer the case.
