### ISSUE TITLE
ai-controlled mechs can't be used fully without a middle mouse button

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#38178]
which is kinda shit if you don't have one
by default, leftclick does ai actions while you're in a mech, and middle mouse does mech actions

which means if you don't have a middle mouse, all you can really do is be a giant metal gondola

**Comment by steamp0rt** [comment]
you can use autohotkey as a workaround til it's fixed

**Comment by DaxDupont** [comment]
Who the fuck doesn't have a middle mouse button? Even touchpads allow you to middle click.

**Comment by SpaceManiac** [comment]
I find the middle mouse button is the first to go on mice, usually I work without one until the whole mouse breaks.

**Comment by timothymtorres** [comment]
The PR that added middle-clicking causing this was #55248

**Comment by Sealed101** [comment]
today, AIs possessing a mech can use AI abilities when the mech's safeties are on. you either toggle them with the dreaded MMB or through the View Stats menu. it wouldn't hurt to have an action button on the main game hud for toggling safeties

![изображение](https://user-images.githubusercontent.com/75863639/222820960-7988bb30-bd9e-43dd-ab24-0445cff5007e.png)
