### ISSUE TITLE
You can put a box in a backpack that's in said box.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#38189]
Issue reported from  Round ID: 88748 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

1. Spawn chameleon kit
2. Open it in your hand.
3. Put chameleon kit in backpack that's in the chameleon kit without taking it out
4. Box disappears from hand and is now in the backpack that's in itself

@kevinz000

**Comment by Tlaltecuhtli** [comment]
cool

**Comment by Aurantiaco** [comment]
MY BAG HAS DECIDED TO EAT MY BOX
IT HUNGERS
FOR MORE!

**Comment by SgtxRootbeer** [comment]
![eve_knowledge](https://user-images.githubusercontent.com/22112255/40797581-e09e522e-64c5-11e8-99e5-0dca16ecd966.jpg)

**Comment by chesse20** [comment]
not a bug

**Comment by bgobandit** [comment]
https://www.youtube.com/watch?v=47mRCz1QwTU
