### ISSUE TITLE
Pubby throws admin warning/runtime about missing mobile docking port

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#38188]
Issue reported from  Round ID: 88751 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

ADMIN LOG: load_template(): Shuttle Template _maps/shuttles/aux_base_small.dmm has no        mobile docking port. Aborting import.

On each round load.

@pubby 

[10:25:52] Runtime in manipulator.dm, line 220: Cannot execute null.canDock().
proc name: action load (/obj/machinery/shuttle_manipulator/proc/action_load)
src: the shuttle manipulator (/obj/machinery/shuttle_manipulator)
src.loc: the floor (148,76,1) (/turf/open/floor/circuit/green)
call stack:
the shuttle manipulator (/obj/machinery/shuttle_manipulator): action load(auxilliary base (Small) (/datum/map_template/shuttle/aux_base/small), the aux base zone (/obj/docking_port/stationary))
the aux base zone (/obj/docking_port/stationary): load roundstart()
Shuttle (/datum/controller/subsystem/shuttle): initial load()
Shuttle (/datum/controller/subsystem/shuttle): Initialize(375409)
Master (/datum/controller/master): Initialize(10, 0)

**Comment by SpaceManiac** [comment]
Fixed by #38179, I was just complaining when I noticed the issue that nobody had reported the obvious admin message so thanks for the report.
