### ISSUE TITLE
phazons can bypass arena shuttle's arena

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#38182]

**Comment by YakumoChen** [comment]
Intended, it's a PHAZON. If you managed to build one, get in it, AND get the arena shuttle, you deserve a free ride, buddy.

**Comment by RandomMarine** [comment]
\>mech with special ability to bypass obstacles ... bypasses obstacles.
Unless this legitimately breaks the game this isn't even an issue.

**Comment by SgtxRootbeer** [comment]
Non-issue.

**Comment by Borisvanmemes** [comment]
Same goes for bluespace launch pads as far as i know, but yeah not really that big of a issue

**Comment by Cyprex** [comment]
Does the gygax's leg actuator overload work for this as well? I'd guess there are indestructible walls?

**Comment by factoryman942** [comment]
k
