### ISSUE TITLE
You can't unlock nodes from alien tools

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#38181]
Yeah that "fix" didn't fix it

round id: 88733

**Comment by SpaceManiac** [comment]
AAAAAAAAAAAAAAAAAAAAAAAA

**Comment by SpaceManiac** [comment]
the server just hasn't updated to include the fix yet

**Comment by Kromgar** [comment]
@SpaceManiac  my bad thought that since it had been over a day it was updated
