### ISSUE TITLE
Going in VR ends revs

### ISSUE THREAD

**Issue by Michael-Ashfield** [tgstation/tgstation#38194]
[Round ID]: #88757

A solo headrev went into VR, ended the round with staff winning. Seems to be a bit of a bug.

**Comment by KomradeSpectre** [comment]
Not a bug, the mind transfers and leaves the old body catatonic until the host returns.

**Comment by AlexTheSysop42** [comment]
It was changed so the ckey transfers instead, if the mind did there would be a living headrev in VR.

**Comment by Therapist1** [comment]
But VR isn’t the station, his would be off the station, and therefore he would’ve abandoned.

**Comment by DaxDupont** [comment]
Lockers also count as fleeing, spending your round in VR should count too.

Either way, if someone wants to fix it go ahead, I'm not really interested in fixing this.

**Comment by vuonojenmustaturska** [comment]
What dax said
