### ISSUE TITLE
Accelerated particle runtimes

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#38190]
Issue reported from  Round ID: 88750 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

[10:57:06] Runtime in atoms_movable.dm, line 298: No valid destination passed into forceMove
proc name: forceMove (/atom/movable/proc/forceMove)
src: Accelerated Particles (/obj/effect/accelerated_particle/weak)
src.loc: null
call stack:
Accelerated Particles (/obj/effect/accelerated_particle/weak): forceMove(null)
Accelerated Particles (/obj/effect/accelerated_particle/weak): move()
Accelerated Particles (/obj/effect/accelerated_particle/weak): move()
Accelerated Particles (/obj/effect/accelerated_particle/weak): move()
Accelerated Particles (/obj/effect/accelerated_particle/weak): move()
Accelerated Particles (/obj/effect/accelerated_particle/weak): move()
Accelerated Particles (/obj/effect/accelerated_particle/weak): move()
Accelerated Particles (/obj/effect/accelerated_particle/weak): move()
Accelerated Particles (/obj/effect/accelerated_particle/weak): move()
/datum/callback (/datum/callback): InvokeAsync()

**Comment by SpaceManiac** [comment]
@kevinz000 caused by the particle going off the edge of the map

**Comment by DaxDupont** [comment]
Doesn't matter as @AnturK since it doesn't have steps to repo and is copypaste from public logs
