### ISSUE TITLE
BYOND's input bar processes escape codes like \n and \t

### ISSUE THREAD

**Issue by moonheart08** [tgstation/tgstation#38200]
**Round ID**: 88771

**Reproduction**: It's incredibly easy to do. just type, say, \n or \t into BYOND's input bar. it will get processed, sent to the server, and, for example, put in chat.(may not apply to all characters, some may go through unfiltered. haven't tested.)
The issue with this is, of course: _**why the fuck is BYOND processing escape codes.**_

Solution should be simple now that @optimumtact and I figured out the root cause. Just filter out anything escapecodes can send to the server, like backspaces, properly. or even better, revert them back to an escape code all together so i can finally say `\o/` in chat.

**Comment by moonheart08** [comment]
I found some escape codes that actually go through unfiltered:

\b Backspace
\o ??? i dunno but it's a thing

**Comment by ShizCalev** [comment]
@Cyberboss

**Comment by ShizCalev** [comment]
@Cyberboss @optimumtact

**Comment by optimumtact** [comment]
this only happens when using the byond chat input at the bottom of the screen, and is probably being processed long before we see the text

you cant trigger it in hotkey mode or the verb.
