### ISSUE TITLE
Visual bug with ghost sword, grammar bug

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#38205]
![image](https://user-images.githubusercontent.com/10399117/40815766-47fadd26-6538-11e8-945a-919a684e4578.png)
Also when you mouse over it, it says "Body Created"

character in question I believe was also borg-riding when he did this

**Comment by SpaceManiac** [comment]
Probably fixable by setting `pixel_x` and `pixel_y` in `/proc/notify_ghosts`.
