### ISSUE TITLE
Blob falling into tear in reality creates an unending round state

### ISSUE THREAD

**Issue by Ispiria** [tgstation/tgstation#38203]
Issue reported from  Round ID: 88778 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

[Round ID]: Not really applicable, but 88778

[Reproduction]: If a blob is hit with a BoH bomb they fall into the tear in reality and can continue to expand to the limits of the new z-level, which is not enough to reach a victory state for the blob but makes it virtually unassailable by the crew, barring perhaps an extremely coordinated maxcap bombing which would have a high chance of failing. Given the right circumstances and server population this would effectively extend the round indefinitely, since the shuttle can't leave while a blob is alive - in the specific instance being reported admin intervention was required to remove the blob after even an eight-member deathsquad failed to destroy it.

**Comment by SpaceManiac** [comment]
we were warned

**Comment by XDTM** [comment]
This could make for great lore tbh

Imagine blobs spilling from corrupted pockets of reality creared by careless scientists in the past

**Comment by davethwave** [comment]
Actually, that could be a great explanation for blobs spawning in during rounds.

**Comment by Shadowflame909** [comment]
Actually, I've seen them win using this. They get the max territory from this. Then expand with whatever is left on station to get 200 tiles more. (Or, we can just make it so blobs can climb the lavaland ladder..)

**Comment by ExcessiveUseOfCobblestone** [comment]
Lore aside, having indefinite rounds is not ok unless it's terry

**Comment by CitrusGender** [comment]
THIS is REALLY a problem if an admin isn't online.
