### ISSUE TITLE
leaving vr while inside a mech causes your cursor to stay changed

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#38204]
1. enter vr
2. buy a gygax
3. get in, cursor becomes green circle thing
4. leave vr, cursor is still green circle thing

getting into and climbing out of a mech again fixes cursor

**Comment by SpaceManiac** [comment]
Also noticed this if aghosting (probably normal ghosting) while inside a mech. Sane thing is probably to reset cursor on mob/Login
