### ISSUE TITLE
Oh fuck, What have I done - Syndie Lab Atmos Bug

### ISSUE THREAD

**Issue by legoscape** [tgstation/tgstation#38206]
[Round ID]: # Sybil
[Round ID]: # 88777

[Reproduction]: # I was a syndie onboard the toxins-making-lab-place-thing that you can go to on the spawner menu. I was looking at the Atmos system and was trying to get it working to make a good mix for the turbine on the lab. It wasn't working properly so I disconnected the monitors for the o2 and n2 miner and tried to reconnect to the syndie lab atmos loop, it didn't work. So I tried to connect to o2. Apparently, I connected to the station's loop of oxygen and other gases and I coud both turn them off and manipulate them.

**Comment by legoscape** [comment]
Oh, You can also flood the station with plasma and turn off oxygen and manipulate it a bunch.

**Comment by AlexTheSysop42** [comment]
You cant plasma flood because you can't set the pumps

**Comment by Jalleo** [comment]
This is due to a bad direct var set up.

**Comment by SpaceManiac** [comment]
Duplicate of #34833
