### ISSUE TITLE
Making chemicals sometimes consumes reagents without any product?

### ISSUE THREAD

**Issue by Winterous** [tgstation/tgstation#38216]
Round ID: 88799

I discovered this when making silver sulfadiazine in a 100 unit container as I normally do; 30 hydrogen, 10 nitrogen to make 30 ammonia, remove 10 ammonia, 20 silver, 20 sulfur, 20 chlorine, 20 oxygen (all in input values of 10). And instead of getting 100 units like I should, I get 50. If I change it to blocks of 20 input, it gives me 100.
Making styptic powder, 25 hydrogen, sulphacid, oxygen and aluminium produces 100 units, but if I break the aluminium into 15 units, THEN 10 units, it only makes 60; the second reaction producing nothing.

This is extremely bizarre behaviour, and was not happening 20 hours ago. I can't see anything in the update log that would affect this, so I have no idea which commit could have caused this bizarre and slightly game-breaking behaviour, but it really needs to be fixed.

Reproduction: Described above, it also works when adding reagents from another container instead of the dispenser. Pretty sure it has something to do with the container being filled, the reaction that occurs when the container is filled doesn't produce anything if certain conditions are met.

**Comment by jegub** [comment]
I've encountered what is preumably the same issue when making synthflesh - add blood in 5 unit increments from a syringe or beaker to 20 units apiece of styptic and carbon. The first three additions work as per usual, leaving you with 45 synthflesh and 5 units each of styptic and carbon, but the fourth gives a final result of 55 synthflesh.
Adding the blood in 10 unit increments produces 60 synthflesh as expected, and adding the styptic/carbon mix to the blood in 5 or 10 unit increments also gives the desired result.

**Comment by Winterous** [comment]
THIS IS STILL AN ISSUE REE

**Comment by Vidiveni** [comment]
A less clusterfucky way to reproduce:
1. Get a large beaker
2. Add 30u **acetone**
3. Add 30u **unstable mutagen**
4. Place in chem dispenser
5. Add 15u **bromine**

Result: **45u mutadone, as intended**. Beaker now contains 15u acetone, 15u mutagen and 45u mutadone = 75u total. 

6. Add 15u **stable plasma**

**Intended result:** 45u cryoxadone   (and 45 mutadone from before). 
**Actual result:** 10u cryoxadone.      (and 45 mutadone from before). 

Only **10u** cryox were made. 

**After adding 15u stable plasma, the reaction seems to think the beaker has** **75+15=90u already in it,** **without consuming the the used reagents before checking.**

**Comment by Winterous** [comment]
New issue report up with actual code diving investigation.
