### ISSUE TITLE
You can give yourself cult spells from anywhere, totally naked. (And can also give yourself infinite stuns, instead of the 5 cap limit)

### ISSUE THREAD

**Issue by Bluespace** [tgstation/tgstation#38219]
![Image of issue](https://puu.sh/Axauk/e185c4345b.png)

[Round ID]: 88807

[Testmerges]: #37790

[Reproduction]: 
Steps may not be rigid but this is the gist of it.

Draw an empower rune.
Click the empower rune a million godamn times.
Move AWAY from the empower rune.
Click the spell you want. Hit yes.
You'll channel it onto your hotbar.
Continue until you have 30 stun action buttons.
Get arrested by security, get stripped and have no gear.
You still have the dialog box.
Twisted construction out of nowhere.
TC out of perma.

You get the picture.

**Comment by Therapist1** [comment]
FUCK
