### ISSUE TITLE
When a countdown timer is above 99, it displays only the last digit

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#38214]
Issue reported from  Round ID: 88796 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

![dreamseeker_2018-06-01_11-51-53](https://user-images.githubusercontent.com/17237624/40834868-488574ea-6592-11e8-8474-21094014342f.png)
Bomb at 107 seconds remaining

Repo:
1. Spawn syndi bomb or use nuke
2. Activate bomb/nuke with 120 timer
3. Observe how countdown displays only one digit till it goes lower than 100

**Comment by SpaceManiac** [comment]
Will be fixed by #38132
