### ISSUE TITLE
Atmos Engineer Has No Access To The Engineering Lathe In Meta

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#38227]
The title speaks for itself.

**Comment by praisenarsie** [comment]
Stop Typing Like This Please

**Comment by 81Denton** [comment]
Do You Mean The Airlocks Leading Up To It?

**Comment by zaracka** [comment]
The Protolathe Is In The Engine Room Instead Of The Engineering Foyer.

I was thinking... What if Engineering had its own desk or a combined Engineering/Atmos desk? Maybe a public or private autolathe too.

**Comment by 81Denton** [comment]
Oh yeah, looks like pretty much every map has that issue.
@KorPhaeron What would you prefer, giving atmos techs access to the lathe area or moving the lathe to a shared space?

**Comment by YakumoChen** [comment]
Titles Are Supposed To Use Capitalization On Every Word So The OP Is Grammatically Correct

**Comment by lolman360** [comment]
Capitalizing every first letter in a word isn't correct grammar.

**Comment by davethwave** [comment]
I wasn't worried or cared for the grammar.

**Comment by zaracka** [comment]
fixed by #39144
