### ISSUE TITLE
Electrical sparkles produce to much heat

### ISSUE THREAD

**Issue by ArnMl** [tgstation/tgstation#38224]
Issue reported from  Round ID: 88815 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Round ID]: 88815

[Reproduction]: Electrical sparkles generated from devices (like the Rapid Piping Device) generate a lot of heat. One click is enough to bring the temperature of a tile from 20°C to 150°C. Maybe it's a bit much ?

**Comment by SpaceManiac** [comment]
Resolved by #38232
