### ISSUE TITLE
Push ref is broken for integrated circuit reagent components

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#38237]
[Round ID]: # 88843

[Reproduction]: In the reagent section of integrated circuits, I attempted to push the reference to the reagent grinder, big reagent storage, and reagent hypoinjector, to no avail. No amount of pulsing, using starters, tickers, or connecting them to any other outgoing pulse allowed any of them to push their reference, instead leaving it null. To recreate, simply make an assembly with a power source, and, for instance, the reagent grinder, then pulse the "push ref" part of the reagent grinder's ingoing pulse section. It will not in fact push its reference to the self reference output section.

This means that circuits using these components cannot use reagent pumps, and thus, cannot work.

**Comment by PKPenguin321** [comment]
Did you have a battery in your assembly

**Comment by AverageJoe82** [comment]
Can you post a circuit code that can reproduce this? all of my regent bots work

**Comment by Shirbu** [comment]
I apologize for the late response. I posted this at 4:00 AM my time.
In all cases, I had a battery in my assembly.
Below is the code for my device.

{"assembly":{"type":"type-d electronic machine","name":"Plasma Still"},"components":[{"type":"reagent pump","inputs":[[3,0,200]]},{"type":"reagent pump","inputs":[[3,0,200]]},{"type":"integrated hypo-injector","inputs":[[2,0,10]]},{"type":"custom ticker","inputs":[[1,0,1],[2,0,1]]},{"type":"big reagent storage"},{"type":"reagent pump","inputs":[[3,0,200]]},{"type":"reagent grinder"},{"type":"large tesla power relay"},{"type":"large tesla power relay"},{"type":"tile analyzer"},{"type":"pick circuit","inputs":[[1,0,["Plasma Still"]]]},{"type":"reagent pump","inputs":[[3,0,20]]},{"type":"ranged sensor"},{"type":"sensor"},{"type":"starter"}],"wires":[[[1,"I",1],[7,"O",2]],[[1,"I",2],[5,"O",2]],[[1,"A",1],[4,"A",1]],[[2,"I",1],[5,"O",2]],[[2,"I",2],[3,"O",2]],[[2,"A",1],[4,"A",1]],[[3,"I",1],[14,"O",1]],[[3,"A",1],[4,"A",1]],[[3,"A",4],[15,"A",1]],[[4,"A",1],[7,"A",1]],[[4,"A",1],[6,"A",1]],[[4,"A",1],[10,"A",1]],[[4,"A",1],[11,"A",1]],[[5,"O",2],[6,"I",2]],[[5,"O",2],[12,"I",1]],[[5,"A",1],[15,"A",1]],[[6,"I",1],[7,"O",2]],[[7,"I",1],[11,"O",1]],[[7,"A",2],[12,"A",1]],[[7,"A",4],[15,"A",1]],[[10,"I",1],[13,"O",1]],[[10,"O",1],[11,"I",1]]]}

**Comment by AverageJoe82** [comment]
yeah i just got the issue with that circuit, not sure whats causing it right now

**Comment by Shirbu** [comment]
Understood. A shame really. It makes setting it up a real pain

**Comment by Shirbu** [comment]
I assume that the starter setup with your grinder or hypo-injector or what have you works with push ref?

**Comment by AverageJoe82** [comment]
the grinder and injector dont push their refs when pulsed by the starter, the grinder would push its ref when pulsed by a multitool but not the injector

**Comment by Shirbu** [comment]
I see. In that case, the ticker should start off, I assume

**Comment by Shirbu** [comment]
This has been helpful, thank you both
