### ISSUE TITLE
The evacuation rate is nonsensical

### ISSUE THREAD

**Issue by imtakingabreakdontatme** [tgstation/tgstation#38231]
![evac](https://user-images.githubusercontent.com/14340985/40869316-87927b5a-65de-11e8-8286-f6efa1fcca1e.png)

@AnturK

**Comment by iskyp** [comment]
🤔

**Comment by AnturK** [comment]
RoundID would be good

**Comment by Jalleo** [comment]
its likely counting the mobs on centcom itself

**Comment by WJohn** [comment]
Those are cardboard cutouts. However, if someone were to bring a whole crate of butterflies, bees, or something to that effect it might mess with the numbers pretty hard. Should really only count the players/robots (not including AI) that spawned on the station or latejoined.

**Comment by timothymtorres** [comment]
This appears to have been fixed by #48188
