### ISSUE TITLE
Sentient animal CentCom annoucement still fires when nobody takes it

### ISSUE THREAD

**Issue by CitrusGender** [tgstation/tgstation#38241]
[Round ID]: # 88847 Bagil

[Testmerges]: #37790 #38225 
[Reproduction]: Happened right during the round. The Central command notification came up even though nobody signed up.

ADMIN LOG: random animal cannot be spawned due to lack of players signing up.

"Central Command Medium-Priority Update

Based on scans from our long-range sensors, we believe that one of the station's animals/bots has developed clown level intelligence, and the ability to communicate."

**Comment by ShizCalev** [comment]
This would be an issue with all round events.
