### ISSUE TITLE
Production 12 Glowshrooms and subtypes spread instantly potentially causing an infinite loop.

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#38248]
[Round ID]: # 88860

Egg-Plants(/obj/item/seeds/eggplant/eggy) start with production 12, which can be transferred to glowshrooms, shadowshrooms and glowcaps.
Glowshroom spread delay is calculated as follows:
delay is initally 1200.
`delay = delay - myseed.production * 100`
This becomes 0 for production 12
Then, this value is used as follows:
``` 
/obj/structure/glowshroom/proc/Spread()
    //try to plant shrooms, removed for brevity here
    if(shrooms_planted < myseed.yield) //if we didn't get all possible shrooms planted, try again later`
          myseed.yield -= shrooms_planted`
          addtimer(CALLBACK(src, .proc/Spread), delay)
```
Full proc: https://github.com/tgstation/tgstation/blob/master/code/game/objects/effects/glowshroom.dm#L85
Couldn't this potentially result in an infinite loop if the shroom fails to spread?
If this is fine from a technical point of view, are instant-spreading glow/shadowshrooms intended?

**Comment by ArcaneMusic** [comment]
Can someone verify that this wasn't fixed as a result of #51023?

**Comment by Cyprex** [comment]
This bug is very old, the underlying code has likely changed significantly, do you mind if I just close this?

**Comment by ArcaneMusic** [comment]
Ye, kill it
