### ISSUE TITLE
Potential metal dupe issue with circuit printers

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#38242]
- Build an assembly with a number of parts
- Slap the printer with it to start recycling it
- Slap the printer several more times before it finishes recycling
- Recycler will run multiple times and give more metal than it took

Haven't actually tested to see if this is a real issue, so it may not even work. Was reported in the circuits discord by a player who apparently doesn't have a github account

**Comment by Tlaltecuhtli** [comment]
delet this

**Comment by Jalleo** [comment]
I can confirm this.

**Comment by DaxDupont** [comment]
Yet another circuit meme.

This solution is to remove circuits!
