### ISSUE TITLE
Blindness doesn't heal over time/by covering your eyes

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#38256]
I thought the wiki was wrong but apparently there's code for it in code\modules\mob\living\carbon\human\life.dm at line 55, but I haven't been able to properly fix it myself.

To the best of my knowledge TRAIT_BLIND is no longer being used and I'm not sure about adjust_blindness, doesn't seem to do anything.

**Comment by SpaceManiac** [comment]
What was the source of the blindness?

**Comment by Mickyan** [comment]
I should have specified - this is for blindness you get through regular eye damage (welding, getting flashed, screwdriver to the eyes etc.)

**Comment by SpaceManiac** [comment]
The wiki implies that the correct cure for blindness is eye surgery, and the code corroborates this. As far as I can tell, wearing a blindfold only makes temporary blindness resolve sooner, and doesn't help permanent blindness.

**Comment by Mickyan** [comment]
You might be right, although the tip on the wiki I was thinking about says "Wearing a blindfold will heal eye damage." which is not exactly accurate and had me confused. Seems like it's working as intended and it was just a wiki error after all, so I'll close this.
