### ISSUE TITLE
Cyborgs can't attach wallframes to walls anymore

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#38265]
Revision: 8e692e6c02786b7b8e605b942d1568af5387abed

When cyborgs use their screwdriver on a wallframe (APC, air alarm, etc.), it's supposed to attach the wallframe to the nearest wall turf. 
This isn't working currently, no error message either.

Code:
https://github.com/tgstation/tgstation/blob/3553c12d0bfa4ce2eb75fd2dd0b2d410c167521c/code/game/objects/items/apc_frame.dm#L61-L67

**Comment by SpaceManiac** [comment]
Unable to reproduce. Looks like it specifically requires the user to face towards the wall they want it on. If I do that it works.

**Comment by 81Denton** [comment]
Oh yeah, my mistake.
