### ISSUE TITLE
Engiborgs Pseudo circuit doesn't work

### ISSUE THREAD

**Issue by lightcat** [tgstation/tgstation#38260]
Airlocks can't be build using them, probably should update the description or fix it.

**Comment by 81Denton** [comment]
The airlock part is intended (iirc due to code limitations?), you'll have to use the RCD for it. Let me test the other uses real quick

**Comment by 81Denton** [comment]
Works with APCs/air alarms/firelock/fire alarm on Revision: 8e692e6c02786b7b8e605b942d1568af5387abed

**Comment by lightcat** [comment]
Here I've updated the description to be more accurate.

**Comment by factoryman942** [comment]
according to #31018 not a bug @SpaceManiac

**Comment by AlexTheSysop42** [comment]
It still affects windoors but is a dupe of #31047
