### ISSUE TITLE
Only one syndicate fighter ship is placed in the ambush space ruin.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#38273]
There's supposed to be a second one to the bottom right. Might have to do with how ships are loaded in nowadays.

Seen here originally:
https://www.dropbox.com/s/7w6zb9hso5z32zp/scrnshot2.png?dl=0

**Comment by SpaceManiac** [comment]
Hmm apparently it was actually just removed during the port to templates. I guess this would require more general support for loading multiple copies of the same shuttle template.

**Comment by SpaceManiac** [comment]
I think I remember we fixed this. @WJohn please reply if I am wrong.
