### ISSUE TITLE
High potency plants have an extra unit of reagents

### ISSUE THREAD

**Issue by Jord1081** [tgstation/tgstation#38271]
[Round ID]: # Any Round

[Testmerges]: # None Relevant

[Reproduction]: # Get almost any plant with high potency and some reagents in it. When harvested notice that the numbers don't add up correctly.

I.E. A glowshroom with 10% chlorine, phosphorus, and radium at 100 potency will actually have 11u of each instead of 10u.

**Comment by DaxDupont** [comment]
Probably a rounding error

**Comment by Winterous** [comment]
This isn't an error, they always have 1 unit of every reagent content added, so they never contain 0 of something.

**Comment by Jord1081** [comment]
Hmm, wouldn't it make more sense for them to round up to 1 unit if they have less than 1? I know it's not that big of a problem, but its still annoying having all the numbers mismatched.

**Comment by ArcaneMusic** [comment]
As far as I can see, this has been fixed by the recent changes to plant capacity/percentages/etc.
![image](https://user-images.githubusercontent.com/41715314/87242505-46c8e500-c3fb-11ea-9252-b3e264570059.png)
