### ISSUE TITLE
Supply Pod Smite Issues

### ISSUE THREAD

**Issue by Arianya** [tgstation/tgstation#38286]
From casual usage:

* Damage is super inconsistent, sometimes they just get bruted up a bunch, sometimes you sever 3 limbs at once
* If you type in an invalid path it will irreversibly go ahead with the smite sending a harebell rather then cancelling the smite or giving the admin a chance to re-enter.
* The smite does not paralyze/stop the smitee and so they can outrun the smite (see Immovable Rod smite to see how this should be handled)

**Comment by Arianya** [comment]
#38069 @MrDoomBringer

**Comment by Tlaltecuhtli** [comment]
can we lower the dmg done from drop pods and also have a no dmg checkmark for admin reasons

**Comment by Tlaltecuhtli** [comment]
like yeah cool drop pods but they destroy windows walls apcs lights cameras

**Comment by MrDoomBringer** [comment]
always thought the non-paralyze thing was supposed to be like that (Fireball doesn't stun).

**Comment by MrDoomBringer** [comment]
@Tlaltecuhtli, I'll try to do that

**Comment by Arianya** [comment]
Re: not stunning, it depends on the smite I believe. Some smites like gib, lightning bolt & brain damage obviously can't miss.

Not sure offhand why fireball wouldn't stun, but hey! Thanks for the quick response 😄
