### ISSUE TITLE
Can create 100 plastic sheets from 100u chemicals

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#38292]
During creation of plastic sheets in chemistry, you can circumvent the usual 10u -> 1 plastic sheet ratio by adding small amounts of the final ingredient to an already heated mix. 

[Reproduction]:
Using the following recipe: 20 Sulphuric acid, 30 Ash, 50 Oil.
Heat a beaker containing 2/3 of the ingredients needed to create plastic sheets (tested with sulphuric acid and ash) to between 374K (Plastic sheet) and 480K (oil -> ash). Add 5u of oil, which results in enough ingredient for the reaction to 1 plastic sheet. Results in 10 sheets, but only consumes the material to create one sheet. Possible to create 100 sheets from 100u if heated repeatedly.

**Comment by Winterous** [comment]
This isn't an issue, and is like the opposite of what the real issue is.
The recipe consumes all the reagents to produce a single batch of product, so adding smaller amounts allows it to produce the correct amount.

**Comment by kriskog** [comment]
I would agree with you if it made 1 sheet. But it makes 10 sheets using 10u of chemicals, and that is not correct.

**Comment by Winterous** [comment]
Why is that not correct? Where did you get the impression that isn't intended?
Since I first used it, it's always produced batches of 10 sheets every time you mix it, regardless of how many units are reacted.

**Comment by kriskog** [comment]
Well, try to make an entire batch (100u). If you heat it at the end, it results in 10 sheets. So that would be the baseline. I could quote the wiki as well, which states that 10u = 1 sheet. 
Now if 10u = 10 sheets is actually the intended outcome (doubt it), then there is another issue with the 100u resulting in 10 sheets.

**Comment by Winterous** [comment]
Why would the baseline be 100 units, and not 10 units? The reaction is 5, 3, and 2 of the components. That's the minimum reaction size, so why wouldn't that be the baseline?

And I agree, it's weird that you get less if you react more at once.
