### ISSUE TITLE
tear in the fabric of reality singulo throws admin warning on round start

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#38295]
`ADMIN LOG: A singulo has been created without containment fields active at Tear in the Fabric of Reality (47, 33, 1) (JMP).`

message is displayed shortly after the mapping subsystem finishes

**Comment by DaxDupont** [comment]
I think it's fine personally, gravgen on the derelict does the same.

**Comment by bgobandit** [comment]
thank you for finally reporting this it's annoying as fuck
