### ISSUE TITLE
Bloodcult soul shard antag test

### ISSUE THREAD

**Issue by improvedname** [tgstation/tgstation#38304]
Chaplain can use his roundstart soulshard and use it on alive people.
if the alive person is a cultist.
it will give the following message
Come on, do not capture your bretheren's soul.
this comfirms they are a cultist and can be used to meta/validhunt the round

**Comment by Tlaltecuhtli** [comment]
solution: remove the shard

**Comment by chesse20** [comment]
not a bug

**Comment by ExcessiveUseOfCobblestone** [comment]
needs to have a not alive `stat` check

**Comment by Dorsisdwarf** [comment]
Chaplain should not be recieving messages calling the cult his brethren, and the soul shard should have no effect on conscious persons
