### ISSUE TITLE
Lattices are missing rcd_act/rcd_vals

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#38311]
Revision: 1c6cd23871567e958cd337aac4a27f5ed805cb84

Lattices are missing rcd_vals/rcd_act for RCD_FLOORWALL mode.

This means that players can't create plating by clicking on lattice with an RCD in 'Floors & Walls mode' - they have to click the space turf beneath.

**Comment by timothymtorres** [comment]
The solution to fix this is in #38312 for anyone interested.

**Comment by ZephyrTFA** [comment]
this can be closed
