### ISSUE TITLE
Tesla coils explode when they zap nearby mobs

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#38317]
If you pulse a tesla coil's WIRE_ZAP wire, it will explode if it zaps a nearby non-insulated mob. 
Maybe the arc lightning bounces back to the coil?

**Comment by XDTM** [comment]
even then it shouldn't be the type that blows up machinery, but somehow it is

**Comment by ExcessiveUseOfCobblestone** [comment]
@kevinz000 I remember you touching zappies a while back, anything from there that might cause this?

**Comment by LemonInTheDark** [comment]
Can't get this to reproduce, not sure if it's still a thing

**Comment by Iamgoofball** [comment]
can't reproduce as of a week ago
