### ISSUE TITLE
The "Be Xenomorph" in the Game Preferences panel is a misnomer

### ISSUE THREAD

**Issue by ModDownloading** [tgstation/tgstation#38315]
Under the Game Preferences panel, the "Be Xenomorph" antag option actually affects whether you will receive notifications for slaughter demons, sentient diseases, uplifted animals, morphs and nightmares, in addition to Xenomorphs. This is because all of those roles have the "Role_Alien" tag, though just stating it under preferences as "Be Xenomorph" seems misleading.

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't think we want preferences for literally every role so probably just best to edit the name to be more generic

**Comment by SpaceManiac** [comment]
This can't be changed without updating the database

**Comment by TheBonded** [comment]
Antag preferences have been completely overhauled so I think we can safely say this is no longer an issue. Maybe.
