### ISSUE TITLE
Medical holograms are barely noticable

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#38313]
Medical holograms created by penlights are barely visible after the initial animation, extremely short-lived, have a long cooldown and aren't context sensitive. 

There is currently no reason to use them when pointing is more noticable, has no cooldown and shows a text message about who you're pointing at.

![medh](https://user-images.githubusercontent.com/32391752/41033882-370fe200-6988-11e8-96c8-ba403092f1ae.jpg)

**Comment by Tlaltecuhtli** [comment]
penlights had an actual function???

**Comment by zaracka** [comment]
If the mob moves, the hologram doesn't move with it, so it becomes even more confusing. Half the time people think it's a death circle and run from it and me, even though I'm a doctor and they're bleeding to death.

**Comment by kriskog** [comment]
Not a bug
