### ISSUE TITLE
The staff of Resurrection doesn't ask the resurrectee if they want to be resurrected.

### ISSUE THREAD

**Issue by moonheart08** [tgstation/tgstation#38327]
Simple issue. the SOR will attempt to pull the resurrectee across space and time into their body to revive them.

**Comment by Repukan** [comment]
Just kill yourself again

**Comment by Borisvanmemes** [comment]
Then they just res you again

**Comment by zaracka** [comment]
There's a lot inconsistencies where you can be brought back into the round even though you used the suicide verb. To avoid this, use the ghost verb either before or after they resurrect you. Be careful though, 'cause things like Blood Cult soulstones work on suicides and admins might yell at you for "ghosting after being converted."

**Comment by PKPenguin321** [comment]
Feature

**Comment by Ratvar** [comment]
Tip: use Ghost. Can't revive if you ain't dead.

**Comment by moonheart08** [comment]
it'll pull you in even if you Ghost

**Comment by zaracka** [comment]
Ghosting while in crit makes you succumb. Ghosting while not in crit means you can't re-enter your body.

**Comment by Anonmare** [comment]
Why not just suicide somewhere your body can't be found?

**Comment by ExcessiveUseOfCobblestone** [comment]
Shadow, People not using the suicide verb properly is 1) not the coder's problem [you are told this boots you out on the alert] and 2) OOS of this PR.

Again, please keep that awful discussion on the forums where I don't get notifications about it.

**Comment by Shadowflame909** [comment]
It's wizard shenanigans. Just space yourself.

**Comment by AlexTheSysop42** [comment]
>people not using suicide properly

Ghost is the "I want out of the round" button, and it isn't affected by the healing staff.

Plus, there's a very good chance someone who suicided near roundstart would want to be back in the round once summon guns/magic happens.

**Comment by ExcessiveUseOfCobblestone** [comment]
STOP STOP STOP STOP STOP

SEE THE FORUMS PLEASE
