### ISSUE TITLE
Crafting with paper does not check nearby Paper Bins

### ISSUE THREAD

**Issue by Jord1081** [tgstation/tgstation#38322]
[Round ID]: # 89078

[Testmerges]: # None relevant

[Reproduction]: # Crafting something that requires paper (paper frames and probably paper sacks) do not check nearby paper bins for paper, so you have to manually remove paper one at a time until you have enough for crafting. For paper frames this is incredibly tedious since you need 20 paper.

Note: I forgot to test this with regular paper bins and used natural paper bins instead, but I imagine it works the same.

**Comment by DaxDupont** [comment]
This is kinda a feature request but it would make paper crafting way less painful

**Comment by Jord1081** [comment]
At the very least you should be able to dump out paper bins, even that would make crafting infinitely easier.

**Comment by Expletive** [comment]
FYI, Natural Paper Bundles can be snipped apart with any sharp object, and this will dump it's contents on the floor.

**Comment by nemvar** [comment]
Not a bug. Sort of a feature request. WYCI?
