### ISSUE TITLE
crafting a flamethrower in a storage item spawns a flamethrower, but the welding tool is still there

### ISSUE THREAD

**Issue by Memager** [tgstation/tgstation#38330]
make a flamethrower in a backpack, the flamethrower spawns in the same slot but the welding tool still there at that same slot
closing the storage item also leaves the welding tool floating in place, interacting with it will still work as your normal welding tool
no testmerges whatever idk lol

**Comment by CitrusGender** [comment]
oh that's my bad

**Comment by Armhulen** [comment]
@CitrusGender slapcrafting!

**Comment by ExcessiveUseOfCobblestone** [comment]
> being able to slapcraft an item that uses tablecrafting

....

**Comment by CitrusGender** [comment]
yeah I can't replicate it via either method

**Comment by Memager** [comment]
@CitrusGender seems like it's fixed, it didn't spawn on your hand before
