### ISSUE TITLE
Standard R&D protolathe no longer buildable

### ISSUE THREAD

**Issue by octareenroon91** [tgstation/tgstation#38337]
There are zero loose protolathe circuits, and none can be manufactured.

Searching through the git logs, this seems more like an error than an intentional act.

**Comment by 81Denton** [comment]
If you mean department protolathes, a spare board spawns inside each head's locker:
https://github.com/tgstation/tgstation/blob/eccad7c095d3b15ae878fe03c70f09cf518419e1/code/game/objects/structures/crates_lockers/closets/secure/scientist.dm#L27

If you mean the old omnilathe that can print everything; that only spawns in space/lavaland ruins.

**Comment by AlexTheSysop42** [comment]
The confusion is probably that the roundstart protolathe is just a protolathe while the one in the RD's locker is actually a techfab (which is just a protolathe that can build circuits too).

**Comment by kriskog** [comment]
The omnilathe isnt supposed to be printable, the department protolathe can be replaced by the department techfab in the RD locker which does everything and more than the protolathe. These are not supposed to be printed, and are intentionally in limited supply.
