### ISSUE TITLE
Techfabs aren't linkable to RnD consoles

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#38343]
Unlike lathes/circuit printers, you can't link techfabs to RnD consoles. 
This is probably why the engineering and science department still use protolathes instead of techfabs.

**Comment by zaracka** [comment]
I feel like all of them being standalone (meaning you can open the UI without a console) is more important than all of them being able to connect to a console.

**Comment by TheBonded** [comment]
I'm almost certain that you can't control protolathes from an rnd console either, so I don't think this is applicable anymore.
