### ISSUE TITLE
The Tear in the fabric of reality stops angel wings.

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#38362]
1. Be me a miner, get angel wings and fly over the lava.

2. Decide to fight an ash drake with a crusher over lava.

3. I'm doing pretty well for myself, and I end up speeding over the tear in the fabric of reality.

4. "THIS ATMOSPHERE IS TOO THIN TO FLY IN"

5. Crash and burn in lava as I stop flying.

The problem here is that it prevents you from flying with the angel wings OVER LAVA. I think it needs some atmosphere, because who wants to randomly stop flying over lava? It's as much of a noob trap as hidden chasms you can't see.

It may not be much of a bug, but I don't think it was intentional to be a debuff to miners using angel wings to fly over lava! The intended feature!

**Comment by AlexTheSysop42** [comment]
The binary area near the ladders acts like space

**Comment by fludd12** [comment]
The more important question is why are wings testing for a space location rather than atmospheric pressure?

**Comment by AlexTheSysop42** [comment]
By "acts like space" I meant was depressurized like it

also maybe has static space-atmos
