### ISSUE TITLE
Disabling human mood in the config doesn't readd slowness to hunger

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#38387]
@Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus @Qustinnus

**Comment by praisenarsie** [comment]
Needs testing however unless floyd already fixed it. i've been merely told this.

**Comment by praisenarsie** [comment]
nevermind there was a recent patch

**Comment by Qustinnus** [comment]
you really are retarded
