### ISSUE TITLE
You can get 10k+ bloodpoints out of five or so monkeys with a upgraded to max gibber

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#38384]
[Round ID]: # 89200

[Reproduction]: Upgrade a gibber to max, grab five monkeys, gib them all using it, then suck all the blood up using bloodrites, which can then end in most of the station getting blood beamed

**Comment by DEATHRATTLERS** [comment]
![chef](https://user-images.githubusercontent.com/35871565/41192497-cf0ab848-6bbb-11e8-9f09-54dba39a53fe.png)
![station](https://user-images.githubusercontent.com/35871565/41192504-e0182e0e-6bbb-11e8-9f19-8031c76ae498.png)
I suggest adding a decent self harm. Something that prevents you from doing it every 20 seconds.
