### ISSUE TITLE
Briefcase teleporters have no limit on how many items they can teleport at a time, and can absolutely destroy the server.

### ISSUE THREAD

**Issue by Alexch2** [tgstation/tgstation#38399]
[Round ID]: # 89253

[Reproduction]: # Buy briefcase teleporter. Put a large amount of items on it. Teleport them back and forth, and watch the server freeze for increasing amounts of time. It's likely due to the massive amount of sparks this creates rather than the teleporting itself, so maybe it's fixable by just reducing the sparks to 1 per teleport, instead of 1 per item?

This was discovered in VR where a syndie research thingy person brought a couple hundred carp and were teleporting them back and forth until they were found and deleted. I don't even think this stuff is logged.

**Comment by optimumtact** [comment]
@tgstation/commit-access
