### ISSUE TITLE
Donksoft LMG fails to fire foam darts

### ISSUE THREAD

**Issue by CosmicScientist** [tgstation/tgstation#38393]
Round ID: 89226
Master revision unknown
Revision: 40a209aef22cbf3546bb255a864d1c960bf8ba4d
(summer ball event)

Firing the LMG failed to produce foam darts until a mob (not the firer) walks on a tile it was... fired from? Aimed at? In front of the firer? Then they would be "hit" by as many foam darts as were waiting. Darts appear to wait indefinitely to achieve a target to hit.

This seemed to happen only after reloading an empty LMG magazine via clicking on it with a foam dart ammo box (different projectile perhaps?). I also, before that, reloaded the magazine partially with darts picked up off the floor I assume from its original load, and it fired fine.

**Comment by CosmicScientist** [comment]
A freshly spawned in from a vending machine shotgun was affected too. I assume the event/mass usage of the darts was a part of the problem.

**Comment by factoryman942** [comment]
The darts existed forever after this happened, and riotfoam applied its stamina damage to people, too.

**Comment by CosmicScientist** [comment]
Its stamina damage was not always applied or so it seemed when 20 of the things hit one person at once.

**Comment by optimumtact** [comment]
they are on the turfs they're just invisible

**Comment by CitrusGender** [comment]
I want to note that this happened WHILE atmos was disabled. The darts appear to be working just fine under normal conditions. I respawned in the ball map and didn't have any problems.

**Comment by CitrusGender** [comment]
![image](https://user-images.githubusercontent.com/31262308/41276104-1eb3d3c0-6df1-11e8-9e38-772b0c2d86dc.png)

https://feen.us/c1chdnr8.mp4

yeah I ended up replicating it.
