### ISSUE TITLE
nade/smoke logging can be abused to get somebody else banned.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#38407]
The prime message for chem nades does not say what chemicals it has, the explosion/smoke message uses last key which can be incorrect and the smoke message says `associated key` not `last touched by` so admins think its a fool proof message of who space lubed an entire area when it is not.

These combined were being used to get other people banned for space lubing the ball's dance floor.

A pr is test merged that disables (`del()`s) all grenades because of the severity of this bug.

**Comment by MrStonedOne** [comment]
@tgstation/commit-access

**Comment by DaxDupont** [comment]
The prime message will require a bunch of code to figure out reactions.
Since @MrStonedOne said we shouldn't list components but reactions unless I am mistaken.

**Comment by MrStonedOne** [comment]
it should be simple to make a reaction datum proc that just says what the output would be without actually reacting, then calling that and snowflaking the reactions like explosions for special log lines and outputing the chems otherwise.
