### ISSUE TITLE
If you load snowdin VR and then snowdin (possibly when snowdin loads after anything?) the server hangs with the whitescreen

### ISSUE THREAD

**Issue by AlexTheSysop42** [tgstation/tgstation#38410]
On a local server:

https://pastebin.com/Ax42Mv0C
https://i.imgur.com/h19ORO4.png

**Comment by SpaceManiac** [comment]
"Load Away Mission" verb does not quite work right, as you can see there's lots of atmos runtimes. I haven't had it hang on me yet though.
