### ISSUE TITLE
h.e.c.k. suit is incompatible with angel wings

### ISSUE THREAD

**Issue by Deitus** [tgstation/tgstation#38411]
as in title. also of note is that it is in two parts (helmet + hardsuit) like old hardsuits, so im not sure if both of these are intended or if the suit just hasnt been updated in a long time.

**Comment by Repukan** [comment]
Intended

**Comment by Borisvanmemes** [comment]
It being two parts isn't a bug, that i'm sure of

**Comment by XDTM** [comment]
the two parts aren't a bug; it's not even spaceproof by the way

**Comment by KomradeSpectre** [comment]
It's not even lavaproof (even though it is supposed to be lavaproof)

**Comment by XDTM** [comment]
The suit itself is, the person inside is not nor intended to be

**Comment by Deitus** [comment]
apologies for late reply, was on vacation. why are the two parts/lack of wing compatibility intended? im fairly certain it cant be for balance reasons as the drake armor is arguably better anyway.

**Comment by Repukan** [comment]
It's based on the suit from DOOM and that doesn't have wing openings.

**Comment by Deitus** [comment]
while i find the reasoning questionable i will leave this matter to coder discretion

**Comment by XDTM** [comment]
The two-part thing is simply because it's not a hardsuit with an integrated helmet. Not everything has that convenience.
As for the angel wings, i'm not actually sure why it would be blocking them; if it does the same for all hardsuits it's fine, but otherwise i'd allow it
