### ISSUE TITLE
inconsistnecy with rcd + TK

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#38428]
you can use the rcd to deconstruct with TK, seem fine but i noticed that the progress bar doesnt alt when you move the rcd away which means you can deconstruct multiple walls at the same time

**Comment by SpaceManiac** [comment]
I suspect this applies to other items with progress bars used under TK, e.g. butchering with a knife. The progress bar system only checks that the user's location and current item in-hand stay the same, nothing about the tool.

**Comment by SuperNovaa41** [comment]
Can't deconstruct with TK anymore
