### ISSUE TITLE
Surplus prosthetics are armored

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#38445]
1. Grab a wrench
2. Smack prosthetic limb repeatedly, take no damage

Anything with force 5 and under does no damage. I doubt this is intentional as the description specifically states it's supposed to be fragile.

**Comment by SpaceManiac** [comment]
They're "fragile" in the sense that they have a lower max HP than standard robotic limbs. I don't see anything that should be making them armored.

**Comment by XDTM** [comment]
Artificial limbs have a hardcoded 5 damage reduction, will fix in the limb refactor
