### ISSUE TITLE
Gulag shuttle "move shuttle" button moves it instantly

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#38464]
Revision: 99f2d26b7d4d33b53d7558b28165d274bb308d74

Hitting "move shuttle" on the gulag shuttle point claim console (/obj/machinery/mineral/labor_claim_console) instantly teleports it to the station z-level without sending it through the transit z-level first.

**Comment by ExcessiveUseOfCobblestone** [comment]
Probably because the individual cuffed doesn't have the option to close the door.

**Comment by 81Denton** [comment]
I meant the machine that lets you send the shuttle back to the station once you've reached your points goal.

**Comment by ExcessiveUseOfCobblestone** [comment]
ah
