### ISSUE TITLE
Tablet alarm monitor shows non-station alarms

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#38462]
[Round ID]: 89408

[Reproduction]: Open up the tablet, download the alarm monitor. Open it up and wait for stuff to happen on syndie lavaland outposts or similar non-station facilities. Or go cause an alarm. 

In the case of round 89408, SYndicate Lavaland Experimentation Lab fire alarms showed up at around 01:08:00 round time. Have seen comms outpost atmos alarms pop up in previous rounds.
Also worth mentioning the on-station alarm monitor terminal does not record these alarms.

**Comment by ExcessiveUseOfCobblestone** [comment]
Sounds like an easy fix, you just check that the z level when you download the program == the z level of the alarm before compiling them.

**Comment by CitrusGender** [comment]
https://github.com/tgstation/tgstation/blob/f2dbe5cf13bdca3e8367bb618d217c1a3650efc4/code/modules/modular_computers/file_system/programs/alarm.dm#L43

It's because it checks air alarms on the mining level as well but this didn't account for the syndicate air alarms on that level.
