### ISSUE TITLE
Using RPED/BSRPED on vending machines deletes their stock

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#38484]
Revision: 176cc32676f1686f07bf55106b49d757962475a8

Using a regular or bluespace RPED on vending machines that allow RPED interaction deletes their stock.

Examples: /obj/machinery/vending/medical, boozeomat, snack, wallmed, donksofttoyvendor.

**Comment by Mickyan** [comment]
Duplicate of #37581
