### ISSUE TITLE
The Kinetic Crusher has an untoggleable light that harms all shadow-people who use it.

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#38480]
The light is pointless, it doesn't even shine so you need to get a flashlight but it does damage to shadow-races. Who made this un-toggleable useless light?

I personally think this is an oversight...

**Comment by Borisvanmemes** [comment]
The light has been in the crusher for as long as the crusher as been a thing as far as i know, see #28714

**Comment by ChangelingRain** [comment]
The light is intended.

**Comment by Shadowflame909** [comment]
Just because somethings intendonk doesn't mean it isnt an oversight ChangelingRain! No way to turn off light from miner weapon = sadness and death.
