### ISSUE TITLE
Active borg modules lost on revive

### ISSUE THREAD

**Issue by Therapist1** [tgstation/tgstation#38497]
[Round ID]: # 89500

[Testmerges]: # The following pull requests are currently test merged:
#38098: 'Transit space refactor' by kevinz000 at commit 93a9015500
#38287: 'Signal define' by ninjanomnom at commit d483ff3ef0

[Reproduction]: Being revived as a cyborg deletes all currently held modules from your inventory, making life extremely painful when you have to explain you lack the modules.
1. Be killed (not gibbed) as a borg
2. Be repaired and hit with an emergency reboot board
3. Any active modules you had while alive are now gone.

**Comment by DaxDupont** [comment]
I think it's supposed to reset your module too

**Comment by GunHog** [comment]
An reboot board is not supposed to reset a borg's module, as far as I know.

**Comment by Sealed101** [comment]
can no longer reproduce
this has probably been fixed for a long ass while and somehow nobody took this issue down
see https://github.com/tgstation/tgstation/pull/52265
