### ISSUE TITLE
incorrect job filling at roundstart

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#38498]
89502 bagil
i had a job set to high and assistant if the job was full
i got assistant
then i check the crew manifest and  the job i wanted has still slots open

**Comment by SpaceManiac** [comment]
Jobs have different roundstart and latejoin limits, are you sure that didn't happen?

**Comment by Tlaltecuhtli** [comment]
does scientist have 3 slots roundstart and 5 later join?

**Comment by SpaceManiac** [comment]
Yes.

**Comment by Tlaltecuhtli** [comment]
for what purpose? like i can just set it to return lobby if job unaivalable and rejoin

**Comment by SpaceManiac** [comment]
Presumably to try to keep the job list a little more balanced. The system was added by mport in 46a7143e3a7983eec88eac3b68153306075020c7 in Oct 2011.

As an aside, I might recommend not opening bug reports until after the round has finished.
