### ISSUE TITLE
simplemob slime AI taking over

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#38503]
Round ID: yogs, downstream
Got to be the special snowflake anomaly slime, and after finishing feeding and reproducing the simplemob AI randomly took over, for about half a minute. 
It ignored all inputs that didn't bring me closer to the 'target' during this time, and simple charged straight forward

**Comment by fludd12** [comment]
Honestly, I kinda want to find out why this happens, then implement it as a feature for some things - instincts taking over, etc.

**Comment by Time-Green** [comment]
it apparently had something to do with bad controles and the client freezing, wich now has a proper issue

**Comment by Time-Green** [comment]
see https://github.com/tgstation/tgstation/issues/39108
