### ISSUE TITLE
Meth (and maybe other chems) don't mix when heated

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#38508]
Issue reported from  Round ID: 89528 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

1. Put meth components in a beaker
2. Put chem heater to 374.
3. Chems don't mix
4. Put chem heater to 375
5. They now mix.

Meth is supposed to mix at 374, this might be some rounding issue?

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blame/2f8f166d8885841869e6212991bdff06553fae80/code/modules/reagents/chemistry/holder.dm#L409-L413

using <> rather than ≥ ≤
