### ISSUE TITLE
Chef CQC works outside of the bar.

### ISSUE THREAD

**Issue by Nabski89** [tgstation/tgstation#38517]
[Round ID]: # 89543

[Testmerges]: # #38098: 'Transit space refactor' by kevinz000 at commit f6564b51f4 
#38329: '[READY] [TESTED] Fusion Rework Episode V: The Phantom Fusion' by cyclowns at commit 7ef2165c90 

CCQ for the chef doesn't seem to care if it's in the kitchen. 
https://tgstation13.org/parsed-logs/basil/data/logs/2018/06/16/round-89543/attack.log
Omegashoots was the chef if you're log hunting.

**Comment by improvedname** [comment]
Who cares bar kitchen part of ome area

**Comment by Nabski89** [comment]
I'm 90% sure they also got someone in the bathrooms with it, which is pretty far away.

**Comment by Therapist1** [comment]
really it should only work in the kitchen itself, not in the bar or club.

**Comment by Supermichael777** [comment]
The RESTAURANT is part of the chefs domain. 

Close quarters cooking was originally developed by the steakhouse samurai after all and they did most of their work at the tables!

**Comment by ExcessiveUseOfCobblestone** [comment]
is it a bug?
