### ISSUE TITLE
TEGs are broken

### ISSUE THREAD

**Issue by kingoftheautism** [tgstation/tgstation#38526]
Issue: TEGs are not working. You see, this is how working TEG before #38056 looks like
![teg](https://user-images.githubusercontent.com/40269243/41497319-ecf775c6-718d-11e8-9899-b83bff2b7e42.png)
It's generating 2 MW. Only admins can spawn it, and you can't get them, since all in rotation maps does not have TEGs. "Free power" issue solution? Maybe.

PR #38056 basically added three more sprites for TEG, and they can be constructed and deconstructed. You still need to get circuit boards from somewhere, and they also not require anything. But, now TEG is not working. Why?

Look. I'm recreating TEG. To prevent confusions, left loop = cold loop, and right loop = hot loop.
![teg-new](https://user-images.githubusercontent.com/40269243/41497368-0a88df66-718f-11e8-9d54-ba2eb2354669.png)

Okay, it's recreated, and... Hey, what the hell, it's not even connecting with pipes.
![teg-broken](https://user-images.githubusercontent.com/40269243/41497395-71b2b892-718f-11e8-958b-b910bbab1e29.png)

I think this is because sprites for HORIZONTAL circulators ARE NOT the same. You, maybe, can say "Well, try to change loops, so input will be not on south but on north", and this can make sense, but, hell, it's not making sense since LEFT circulator not connecting to cold loop, but it supposed to, and input is supposed to be on south.

Even if i will put some gas in loop, it will still not work, you know why? Yeah, because circulators are not connected to pipes.
![bandicam 2018-06-16 18-05-47-103](https://user-images.githubusercontent.com/40269243/41497425-ece33a78-718f-11e8-9113-dbb93e46d1d4.jpg)

Possible solutions:
1) Revert #38056 
2) Add option to mirror circulators, then fix them so they will see and connect to pipes
![solution](https://user-images.githubusercontent.com/40269243/41497460-b0eaff50-7190-11e8-934b-9bf986fd0d97.png)
3) Just fix issue when they can't connect to pipes. I'm mostly fine with changing loop direction

How to recreate: Just try to make TEG

**Comment by kingoftheautism** [comment]
I'm feeling like everyone who will read this will be confused with my english

**Comment by SpaceManiac** [comment]
@nichlas0010 Care to weigh in?

**Comment by Rubikoid** [comment]
I think this problem not in sprits direction. For example, new method `setPipingLayer` sets the piping_layer var to null, but manual defining piping layer for some reason does't fix that problem.

**Comment by nichlas0010** [comment]
yeah I uuh, fucked the directions. I was working on fixing this yesterday with SetInitDirections but that led to the buildPipeline fucking up. Point is, I'm aware and working on it 😄

**Comment by nichlas0010** [comment]
the issue right now is that they look for pipes in their dir, and to the opposite side of their dir, meaning they want the pipes to go towards the main TEG-block and away from it

**Comment by Dennok** [comment]
Now it dont connect to any dir.

**Comment by kingoftheautism** [comment]
I guess issue is closed since #38656
