### ISSUE TITLE
Pubby Station Integrated Circuits Lab Has a Security Lathe, and Can't Print Upgrade Disks For Circuit Printers

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#38520]
Round ID: 89550

This shit is irritating, and makes it so that the protolathe in circuits is entirely useless for circuitry.

**Comment by Tlaltecuhtli** [comment]
a sec lathe ? this is a feature

**Comment by AlexTheSysop42** [comment]
Just walk to rnd

sec lathe is totally a feature, another step towards readding sci omnilathes

**Comment by Ratvar** [comment]
How else R&D will make guns but it's not a gun it's actually an aimbot so you can make it? Feature 100%.
