### ISSUE TITLE
Custom Burger sprites broke

### ISSUE THREAD

**Issue by Therapist1** [tgstation/tgstation#38529]
[Round ID]: # 89565

[Testmerges]: # #38098: 'Transit space refactor' by kevinz000 at commit f6564b51f4
#38329: '[READY] [TESTED] Fusion Rework Episode V: The Phantom Fusion' by cyclowns at commit 7ef2165c90

[Reproduction]: # Make a custom burger. It just looks like the bottom bun!

**Comment by bgobandit** [comment]
dupe https://github.com/tgstation/tgstation/issues/38433?

**Comment by SpaceManiac** [comment]
Duplicate of #38433
