### ISSUE TITLE
Watcher beams heat you up instead of freezing you

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#38548]
[Round ID]: 89606

They aren't magmawing watchers just regular watchers.

**Comment by SpaceManiac** [comment]
Moreover, it wears out very quickly, and doesn't cause any damage in the meantime.

Body temperature: 108.1 °C (226.5 °F)
... 10 seconds later ...
Body temperature: 34.2 °C (93.5 °F)
(still at full health)

**Comment by newfren** [comment]
It was causing me very slight burn damage but nowhere near the regular damage the freezing beams do.

**Comment by cyclowns** [comment]
possibly related to #38414?
