### ISSUE TITLE
Attempting to chain stun cyborgs with an EMP flashlight deletes the EMP flashlight.

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#38546]
For some reason or another when you try to chainstun a borg more than once before it recovered from being EMP'd with the EMP flashlight the flashlight you get the message "You need to open the panel to repair the headlamp!" and the EMP flashlight is deleted and there is no way to get it back.

Pls fix

**Comment by Armhulen** [comment]
AHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHAAHAHAHHAHAHAHAHAHAHA

**Comment by Jarektheraptor** [comment]
how do you block someone on github????????????????

**Comment by PKPenguin321** [comment]
Ohhh shit this happened to me months ago and I had no idea what happened, this explains a lot
