### ISSUE TITLE
In Circuit lists, empty entries cannot be deleted.

### ISSUE THREAD

**Issue by Hate9** [tgstation/tgstation#38559]
[Reproduction]: Create any kind of a list within a circuit (I think I used the "at" component, but it really shouldn't matter), add an item (I did string, but again, it should work regardless), and click cancel in the textbox (or click ok without entering: both work), now try to delete that item.

**Comment by PKPenguin321** [comment]
Same for entries that are just the number `0` I think

**Comment by SpaceManiac** [comment]
Circuits have been removed.
