### ISSUE TITLE
Return to Lobby + fail to roll any jobs you want = start as geneticist???

### ISSUE THREAD

**Issue by ishitbyabullet** [tgstation/tgstation#38569]
Issue reported from  Round ID: 89656 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Round ID]: #89656

[Reproduction]: If you go on bagil and have a job (captain) set to medium while having GO TO LOBBY IF YOU GET JOB then you will still be sent into the round.

**Comment by DaxDupont** [comment]
Did you roll antag?

**Comment by MrStonedOne** [comment]
This likely happens if somebody gets pre-selected for antag, but doesn't make the final cut.

Anywho I've had this happen to me as well.

**Comment by Shadowflame909** [comment]
I've seen something similar happen once. A janitor spawned right next to me in chemistry. It was weird, we looked at each other for 10 minutes and then I let him out.

**Comment by AnturK** [comment]
Fixed in #38586
