### ISSUE TITLE
Gulag stacker not registering points

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#38562]
Round ID: 8943

>Get mindswapped with someone on gulag
>try to reclaim points through minerals
>stacker eats the minerals, no points assigned
>Can't leave at all
![image](https://user-images.githubusercontent.com/12382984/41512066-e27c3206-727a-11e8-9f33-d3965501dce7.png)

**Comment by Shadowflame909** [comment]
I hate that stacker always stealing my fucking metal. I'm not sure what it actually does though, so I fear breaking it.
