### ISSUE TITLE
Text to speech circuits can't handle special characters (including apostrophes)

### ISSUE THREAD

**Issue by Hate9** [tgstation/tgstation#38561]
[Reproduction]: When using an integrated assembly text to speech circuit, any special characters are converted to HTML special character codes.
This means that using one to say `don't` results in the circuit saying `don&#39;t`.
Obviously, this is an issue.

**Comment by fludd12** [comment]
This is unfortunately a symptom of a much larger issue, I think - and one that won't go away for a long time.

It's probably possible to patch this issue up, but this is probably the same thing that makes putting special characters in object names fail, too.

**Comment by Hate9** [comment]
Probably, but it seems like it should be easier to fix (based on my poking around the source).

**Comment by Cyberboss** [comment]
dsay fucks this up too

**Comment by SpaceManiac** [comment]
Circuits have been removed
