### ISSUE TITLE
emergency toolboxes don't count as toolboxes for cargo bounty

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#38563]
or at least the discord man said so
![image](https://user-images.githubusercontent.com/20996272/41513036-306f1214-728d-11e8-97a1-1a6541fe06ef.png)

**Comment by CitrusGender** [comment]
Worked ingame just fine.
![image](https://user-images.githubusercontent.com/31262308/41528605-8aeb0e0c-72b8-11e8-98a5-07c98c4b7984.png)

**Comment by ExcessiveUseOfCobblestone** [comment]
what if he tried to sell his grace without knowing lol
