### ISSUE TITLE
Meta/Delta Maint / Public Autodrobes start with restricted access when they should have all access

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#38572]
Extremely vital issue for hat-wearers

**Comment by 81Denton** [comment]
Can you take screenshots or describe which ones you mean exactly? The ones in dorms have `req_access_txt = "0"` while the theater ones (behind the locked door) have `req_access = list(ACCESS_THEATRE)`.

**Comment by Mickyan** [comment]
On Delta, both the autodrobe in dorms and the one in maint (under arrivals) have restricted access

Possibly related, the booze-o-mat in delta maint also has restricted access, it used to be public and I dont recall that being changed

**Comment by 81Denton** [comment]
Alright, I can confirm all public Delta/Meta autodrobes and booth boozeomats. I'll do a fix PR for them later today.

**Comment by Mickyan** [comment]
This just popped up again by the way. At least on Delta, didn't check the rest but safe to assume it did
