### ISSUE TITLE
Meta has Research Monitors in circuit lab

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#38573]
Research Monitors are a console that should only be in the RD's office. They allow you to view the AI core which makes it extremely easy to spot a malf AI, they shouldn't be all over science for anyone to view.

**Comment by Tlaltecuhtli** [comment]
its there because circuit drones cameras work in the same network

**Comment by 81Denton** [comment]
AI sat cams are supposed to be in a separate `minisat` network that only the RD monitor can access. It's probably a good idea to check for that.

**Comment by DaxDupont** [comment]
Why would circuit drones use the same network.

**Comment by ExcessiveUseOfCobblestone** [comment]
so they can hardcounter malf AIs, obviously.

Any change made to appease circuitry has an underlying, malicious intent until proven otherwise.

**Comment by 81Denton** [comment]
Camera networks are all over the place in general. On some maps the RD has access to the minisat, on some he can also access the vault cam (?), on some the AI upload as well.

**Comment by ExcessiveUseOfCobblestone** [comment]
@81Denton are those defined by the map via varedits or are they subtypes?

**Comment by 81Denton** [comment]
@ExcessiveUseOfCobblestone The ones that don't have ss13 as their network have been var edited individually by some poor sod.

**Comment by ExcessiveUseOfCobblestone** [comment]
If anyone does any more mapping work please make subtypes.

**Comment by 81Denton** [comment]
This can be closed due to #38730.
