### ISSUE TITLE
Logging for Circuits is non-existent

### ISSUE THREAD

**Issue by Arianya** [tgstation/tgstation#38588]
[Round ID]: 89692

Effectively what it says in the title, there is little to no logging about circuits, who made them, what they're doing, they don't even show up in attack logs unless someone attacks the circuit, it can attack people with impunity.

This combined with their /obj/ status makes them a bitch and a half to track down, and almost impossible to act on after the fact, even during the same round.

**Comment by DaxDupont** [comment]
Pretty important since circuits are so rampantly abused.

**Comment by BlueNothing** [comment]
Any advice for even starting on fixing this?

**Comment by Arianya** [comment]
Key things that would be useful to have logged:
- [key]/[character name] putting the battery into [drone name]
- Any throws that hit mobs
- Smoke generation by a circuit

More tentative, since I'm not even sure how feasible these would be to log:

- When someone prints a saved circuit, and what components it includes (may need recursive depth in the case of circuits in circuits)
- If a remote is used then it logs who and what the order given by remote was

Other people might have better/more ideas though.

**Comment by AverageJoe82** [comment]
All those are possible but if you log throwing then it would spam the logs since some throw bots throw  up to 10 objects in a single burst. Throwers are probably the most important thing to log though since they're the main circuits that kill people but I just wanted to make sure that spamming the logs is ok. Also circuits in circuits are printed separately from the main circuit and then gabbed after print so just logging each print is probably enough.

**Comment by Arianya** [comment]
Logs can be filtered/trimmed with relative ease by whoever's collating them after the fact, and circuits show up infrequently enough that I'm not worried about it spamming up the logs too much.

It looks like recursive depth is going away with #38621, so I've struck out the recursive depth part.

**Comment by BlueNothing** [comment]
Throwbots are a lot less burst-capable now, tossing out more like 4 in a burst, as opposed to former outputs on par with, say, 10. You could maybe do 10 with a fixed-emplacement (i.e. large assembly) turret, maybe.

**Comment by XDTM** [comment]
probably closeable now
