### ISSUE TITLE
Shuttles have no chairs

### ISSUE THREAD

**Issue by CitrusGender** [tgstation/tgstation#38598]
[Round ID]: Private server

[Reproduction]: THERE ARE NO CHAIRS

Booted up a private server to test something and I realized the arrival shuttle had no chairs. Possibly related to #38557 ? 
![image](https://user-images.githubusercontent.com/31262308/41581312-2131804a-736c-11e8-93f2-5faee9b3accd.png)
![image](https://user-images.githubusercontent.com/31262308/41581319-24bf23c0-736c-11e8-915d-e14f93b34d43.png)
@Cyberboss

**Comment by Tlaltecuhtli** [comment]
the new chairs sprite is /obj/structure/chair/shuttle

and he added /obj/structure/chair/comfy/shuttle
???

**Comment by ninjanomnom** [comment]
I'm taking a look at it now.

@Tlaltecuhtli they were repathed

**Comment by ninjanomnom** [comment]
Seems to be working fine to me
![image](https://user-images.githubusercontent.com/1234602/41582061-88eb12f8-736e-11e8-9e4a-4774cfda3ec5.png)
Are you on latest?

**Comment by CitrusGender** [comment]
https://github.com/CitrusGender/tgstation
I should be. Let me retry.

**Comment by Jordie0608** [comment]
Tested on latest, seconded that it's fine. This is a you problem fake oranges.

**Comment by CitrusGender** [comment]
I have no idea. I guess we'll see if that's the case when the servers are updated.
