### ISSUE TITLE
Ai cameras become partially obscured when moved across z-levels

### ISSUE THREAD

**Issue by Euphausiacea** [tgstation/tgstation#38595]
Round 89701

Building ai cameras on a shuttle(Meta station white ship in this case), then moving the shuttle across z-levels causes the camera vision to become partially obscured. Camera vision is restored upon revisiting the z-level they were originally placed on. 
Deactivating, then reactivating the cameras had no effect.

**Comment by ninjanomnom** [comment]
I wasn't able to duplicate this in a few different ways that it was breaking before so I'll need much more detailed reproduction steps

**Comment by ninjanomnom** [comment]
I'm going to assume this was one of the many client side bugs or this was inadvertently fixed in the vis_contents refactor. Report it again with clear reproduction steps if it happens again.
