### ISSUE TITLE
Camera upgrades applied before final assembly are removed upon completion.

### ISSUE THREAD

**Issue by Euphausiacea** [tgstation/tgstation#38591]
Test server compiled on 6/18/18

Apply an analyzer camera upgrade before completing the assembly of a camera, upon setting the network and completing the assembly, the upgrade will be gone.

**Comment by Hathkar** [comment]
Just replicated this on Bagil.

**Comment by timothymtorres** [comment]
The steps to fix this were outlined in #63552 for anyone interested.
