### ISSUE TITLE
backpack dont take fire/explosion dmg properly

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#38599]
when someone burns to death or is hit by an explosion on the same tile they lose all clothing except the backpack

**Comment by DaxDupont** [comment]
This always seemed more as a feature since it's hell already if you lose most of your stuff.

**Comment by YakumoChen** [comment]
intended

**Comment by YakumoChen** [comment]
specifically playing any engineer job where you have to work in fire would cause it to burn off your belt and bags, which made doing those jobs needlessly hard

**Comment by kriskog** [comment]
Not a bug. Explosions can also destroy items inside backpacks.
