### ISSUE TITLE
Percentages do not describe plant composition in Botany, to catastrophic effects.

### ISSUE THREAD

**Issue by birchbark** [tgstation/tgstation#38601]
[Round ID]: # 89708

[Reproduction]: #38271 needs to be taken into account, but 100% potency Omega Weed does not produce 420 units of chemicals according to percentage displayed to user. Percentages need to be removed and replaced with units as a measurement, and I can add to the wiki that most plants have a capacity of 100 with the exception of omega weed. Exceeding over 100% chemical composition on a normal plant will act erratically, deleting chemicals that would normally fit, (if the list was processed chronologically.)

![proof 3](https://user-images.githubusercontent.com/4492789/41583082-717512d8-7371-11e8-8b19-f175d036331e.PNG)
![proof1](https://user-images.githubusercontent.com/4492789/41583084-71919b7e-7371-11e8-9692-fff230cba8dd.PNG)
![proof2](https://user-images.githubusercontent.com/4492789/41583085-71ac214c-7371-11e8-83cf-7f279cce6fd6.PNG)
![proof4](https://user-images.githubusercontent.com/4492789/41583086-71c51a12-7371-11e8-9636-de62e5dab823.PNG)

**Comment by Jord1081** [comment]
100 potency doesn't mean the entire chemical volume is used up, it's just a multiplier for the contents. Your 25% capsaicin oil plant at 60 potency means there is 25% * 60 = 15u of capsaicin oil, plus the one extra unit.
So if you want to completely fill up Omega weed you need to add a ton of content genes to get 420 units.

**Comment by XDTM** [comment]
exactly, the percentage is of potency and not capacity

**Comment by ExcessiveUseOfCobblestone** [comment]
how do you convey that information ingame if it isn't already?

**Comment by ArcaneMusic** [comment]
Years later, you were finally vindicated.
