### ISSUE TITLE
If you are inside of the large cardboard box you can go faster than normal

### ISSUE THREAD

**Issue by AzureWildfire** [tgstation/tgstation#38612]
Issue reported from  Round ID: 89730 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

No testmerges

So get a large cardboard box get inside and now just run against a wall and up for example:
    wall on your right, just push right and up.

I suppose is accumulating the two inputs.

**Comment by 81Denton** [comment]
we GoldSrc now

**Comment by AzureWildfire** [comment]
I suppose is a bug, is even faster than running without the box.

**Comment by optimumtact** [comment]
dang it the damn wall running bug is back

**Comment by birchbark** [comment]
This screams "feature" to me.

**Comment by SpaceManiac** [comment]
Probably anything with relay_move has this problem, mechs still do (#38177)

**Comment by praisenarsie** [comment]
can we keep this as a goldsrc joke

**Comment by deathride58** [comment]
This is only really useful over at Citadel, but even then it's minor enough to only be reasonably useful in edge cases. Keep it in and call it a feature!

**Comment by optimumtact** [comment]
would someone fix this already
