### ISSUE TITLE
Priority: critical. I can’t make my box go fast

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#38623]
reproduce: 
-get slime speed potion
- hit large cardboard box
- try to move around in cardboard box
- still slow af
- ???
- suicide

**Comment by Supermichael777** [comment]
Not a bug you moving slower to be sneaky. /s

**Comment by TBartl** [comment]
Thankfully you can just abuse #38612 in the meantime.

**Comment by ExcessiveUseOfCobblestone** [comment]
Low hanging fruit fix is to have it not work with boxes.
