### ISSUE TITLE
We need to revert mood

### ISSUE THREAD

**Issue by nicbn** [tgstation/tgstation#38654]
This is a code improvement and performance issue.
Servers don't use it, people don't like it.
It should be purged from the code as having useless code means more bugs, more lag etc.
I'm not a git wizard so I don't know if there is any way to do this without having to manually delete it manually (I tried it and there were merge conflicts everytime I tried to revert a new commit, so basically I'd have to do it manually anyway).

**Comment by Tlaltecuhtli** [comment]
mood is already disabled which server are you talking about

**Comment by ExcessiveUseOfCobblestone** [comment]
Mood shouldn't have been a config, that was what red flagged it in the first place.

**Comment by nicbn** [comment]
I know it is disabled. I'm saying we need to remove it from the code. This is literally the PR title.
And no it is not a bug. Literally the first line of the PR.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Cyberboss he's saying it's a maintain/hindering improvement issue.

**Comment by nicbn** [comment]
Exactly
