### ISSUE TITLE
Upside down buckets can still carry contents

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#38669]
Putting a bucket on your head will dump its contents on you, but afterwards can still hold fluids by using another container to transfer reagents into it.

To reproduce, grab two buckets, fill one with water, wear the empty bucket on your head, then pour the full bucket with water into it.

Now congratulate yourself for somehow keeping water in the bucket and not drowning in it.

**Comment by Kromgar** [comment]
Fix should make you drown

**Comment by fludd12** [comment]
You're keeping the liquid between the bucket and your head, obviously.


...nevermind how you got it in there.
