### ISSUE TITLE
Right clicking an object on latest Byond  lets you see EVERY VERB.

### ISSUE THREAD

**Issue by GuyonBroadway** [tgstation/tgstation#38670]
Servers tested: Hippie and Bagil

How to reproduce: Update to latest beta, right click a tile and look at an objects context menu

As far as I can tell this is mostly harmless (unless some verbs lack security checks) but this is still pretty bad.

**Comment by SpaceManiac** [comment]
http://www.byond.com/forum/?post=2378537

**Comment by SpaceManiac** [comment]
Fixed in 512.1429
