### ISSUE TITLE
Ninja e-katana can be used by non-ninjas

### ISSUE THREAD

**Issue by Arianya** [tgstation/tgstation#38678]
**Round ID**: 89921
**Testmerges**: Nanites

**Issue**: The space ninja's ekatana can be used with impudence even if one is not a space ninja. Considering the suit gibs you if you try to put this on it feels unintentional. At the very least it shouldn't allow use of the advanced features of the katana such as the dash/doorhack.

**Comment by kevinz000** [comment]
this doesnt' seem like a bug and more of a balance issue

**Comment by kevinz000** [comment]
katana's pretty op

**Comment by AlexTheSysop42** [comment]
It's a weapon unique to an incredibly rare side antag that only has a chance to appear after an hour - 45 minutes. It's supposed to be powerful.

**Comment by SgtxRootbeer** [comment]
Also, the Ninja has a recall ability, so maybe this is a good thing

**Comment by ShizCalev** [comment]
Forum feedback, please.
