### ISSUE TITLE
Pepper Spray goes through hardsuits with security gas masks

### ISSUE THREAD

**Issue by Electronics** [tgstation/tgstation#38686]
What the title says, if you're wearing a security gas mask and a hardsuit (with no glasses), the checks allow you to get pepper sprayed/tear gassed.

It might be just the captain's hardsuit, but not sure?

**Comment by Mickyan** [comment]
All hardsuits and spacesuit helmets seem to have this problem, the only exception I found is the syndie elite hardsuits in EVA mode where the HEADCOVERSEYES flag is applied separately when you toggle the helmet mode

**Comment by CitrusGender** [comment]
If it's spaceworthy, it should cover your eyes.

**Comment by Irafas** [comment]
Just did some testing and even with the syndie elite hardsuit in EVA mode I was being effected by the pepperspray. It might be something wrong with the actual spray code that's causing this. It might not be checking to see if the target has the HEADCOVERSEYES flag.

**Comment by GuppyLaxx** [comment]
reminds me how pepperspray went through my plasmaman helmet once and got me killed
