### ISSUE TITLE
Spawned without a taser as sec and was unable to put another taser in my armor

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#38706]
Issue reported from  Round ID: 89991 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

1. spawned as sec
2. no taser
3. Get new taser
4. try to put in armor
5. "You are unable to equip that"

**Comment by SpaceManiac** [comment]
http://www.byond.com/forum/?post=2379020
