### ISSUE TITLE
Talking in a vacuum doesn't show speech bubble to those out of hearing range

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#38703]
Which lead to some pretty awkward moments when two people in space just stare at each other silently not realizing that they can't hear each other

Normally the bubble still displays while you're deaf and it was also brought up in the original PR #5956 that it should be the case

**Comment by optimumtact** [comment]
why would you see a notification of someone talking when you're not in range to hear them?

**Comment by Mickyan** [comment]
Because you can see the speech bubble even while sleeping
Because you also get a text notification when you're deaf and somebody talks
Because realistically you would see their mouth move

**Comment by jlsnow301** [comment]
I don't think this issue is valid post-runechat,  correct me if I'm wrong
