### ISSUE TITLE
Wizards able to make permanent slaves from statues and transformation staff

### ISSUE THREAD

**Issue by RogueSteampunker** [tgstation/tgstation#38712]
Issue reported from  Round ID: 90002 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Turns out it's completely possible to turn someone into a statue, animate them, and then polymorph them so they retain their allegiance to you for the entire round.

**Comment by Ratvar** [comment]
If you use 2 staffs as wizard - you deserve good results. It's not like artificer+staff of change exists too, but doesn't force you to pull 2 huge items around and works on corpses/afk.

**Comment by Arianya** [comment]
Yeah this is two staffs, a melee spell and extremely exposed to getting stunned/disarmed.

I'm sure this is impressive when it goes right, but it's not really a bug or an issue if it goes right one in a hundred rounds.

**Comment by kriskog** [comment]
Not a bug
