### ISSUE TITLE
Proximity Sensors, Signalers, and ect. can all be activated by ghosts.

### ISSUE THREAD

**Issue by RogueSteampunker** [tgstation/tgstation#38718]
Issue reported from  Round ID: 90009 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Proximity sensors can be triggered on and off by ghosts, and signalers can be actively changed and signaled with.

**Comment by SpaceManiac** [comment]
Duplicate of #38717
