### ISSUE TITLE
Sec Starting w/out Tasers

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#38714]
[Round ID]: # 90007

[Reproduction]: Started round as sec, I didn't have a taser. Dunno if the others officers had one or not.

**Comment by wesoda25** [comment]
Update: no officers had a taser

**Comment by wesoda25** [comment]
Update pt 2: issue with armor. Upon getting a taser, I couldn't equip it to my armor vest. (same for an energy gun)

**Comment by AlexTheSysop42** [comment]
Dupe of #38706

**Comment by SpaceManiac** [comment]
Duplicate of #38706
