### ISSUE TITLE
Examining an NTNet console with the Network monitoring program open gives you a "you shouldn't see this" examine text below the real text

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#38715]
Round ID: 9006

![image](https://user-images.githubusercontent.com/12382984/41828253-3112543e-782c-11e8-9945-b681bf73c759.png)

Doing my civic duty.

**Comment by SpaceManiac** [comment]
Can I get some repro instructions? I'm guessing you built the console yourself but I don't feel like figuring out how to do that. Also remind me which item is "NETWORK INCURSION" just in case it's related.

**Comment by Jalleo** [comment]
I believe the incursion is in regards to DDOS stuff I cant confirm that its just my memory there.

**Comment by Anonmare** [comment]
Cannot give repro instructions, I was an observer examining after the fact.

**Comment by Sealed101** [comment]
can't reproduce; a lot of modular console reworks seem to have fixed this eventually
