### ISSUE TITLE
Ash storms damaging/killing borg MMI's (while inside the borg body).

### ISSUE THREAD

**Issue by zombiegums** [tgstation/tgstation#38713]
Issue reported from  Round ID: 90005 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Round ID]: # Happened on multiple rounds.

[Reproduction]: # Went mining as a borg. Given that borgs are (from what I can tell) are immune to damage from ash storms, I generally refrained from seeking out shelter when one started up. However, upon removal of my MMI (disassembly by a roboticist), the MMI was no longer able to be put back into my borg body. The MMI's appearance was "dead", but I was able to talk in character for around 30s before I began talking in deadchat. After consulting with an admin, they found that my MMI had received 200 fire damage rapidly which led to my MMI being killed. I've also tested this where I've avoided ash storms and gotten my MMI removed and it does _not_ exhibit this issue.

1) Be a borg and chill in an ash storm. 
2) MMI is removed for any reason.
3) MMI will eventually die from rapid fire damage.

I do not know if positronic brains are affected by this issue. I'm assuming it's a bug because I feel that the borg body should protect the MMI from damage.

**Comment by 81Denton** [comment]
The wiki (lol) claims that all borgs are ash storm proof. I sadly don't know if they're actually supposed to be.

**Comment by YakumoChen** [comment]
Borgs ARE supposed to be ash storm proof, MMIs taking damage is unintended

**Comment by ExcessiveUseOfCobblestone** [comment]
I like the idea of them receiving minor scratches but can get a "reinforced plating" upgrade that makes them immune.

this is idea-spitballing, borgs are not suppose to be ash immune per
https://github.com/tgstation/tgstation/blob/e0b4fe6b22c5f5586f9b40015cda22d7190af640/code/datums/weather/weather_types/ash_storm.dm#L77-L87

**Comment by YakumoChen** [comment]
@ExcessiveUseOfCobblestone #18697

**Comment by ExcessiveUseOfCobblestone** [comment]
even better lol

**Comment by ExcessiveUseOfCobblestone** [comment]
@SpaceManiac
