### ISSUE TITLE
Diseases often override eachother

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#38729]
Issue reported from  Round ID: 90035 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Advanced diseases often can't coexist with other diseases. They don't even show up in VV.

**Comment by DaxDupont** [comment]
Sentient diseases do too.

@XDTM

**Comment by XDTM** [comment]
Well yeah that's intended

**Comment by AlexTheSysop42** [comment]
Feature, resistance determines which one stays

**Comment by XDTM** [comment]
Unless you mean nonadvance along with advance, if so it's a bug

**Comment by DaxDupont** [comment]
I mean exactly that @XDTM

**Comment by XDTM** [comment]
I'll check it out
