### ISSUE TITLE
IV drips don't work.

### ISSUE THREAD

**Issue by CreationPro** [tgstation/tgstation#38720]
Issue reported from  Round ID: 90011 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

[Round ID]: # 90011

[Testmerges]: # Occured in this build, although I am not sure it's related.
https://www.github.com/tgstation/tgstation/pull/37922

[Reproduction]: # When you try to apply a blood pack to an IV drip it acts as if you are hitting the drip with the pack. No actual way to attach the pack. Intent doesn't matter.

**Comment by Mickyan** [comment]
There were a bunch of issues that suddently popped up last night (such as #38572 reappearing) that seem to be gone today, seem to work fine now

**Comment by AnturK** [comment]
Going to mark this as caused by 1429

**Comment by dragomagol** [comment]
Appears to have been fixed
