### ISSUE TITLE
Silicons are unable to activate shield generators

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#38724]
Round ID: 90013

![image](https://user-images.githubusercontent.com/12382984/41837981-fad53a32-7856-11e8-986a-d1655c7d1b5b.png)

Tested as both cyborg and AI. Wiring is definitely correct and powered.

**Comment by DaxDupont** [comment]
@kevinz000 didn't you fix this

**Comment by YakumoChen** [comment]
Are you sure it's powered *enough*? Shield gens take up a lot of power

**Comment by Anonmare** [comment]
I am 100% sure it's powered

Same result with xenobio gens which are also definitely powered and definitely secured
