### ISSUE TITLE
Monkey mode applies a null disease on round start

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#38731]
Issue reported from  Round ID: 90041 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Thus people don't convert to monkeys

relevant runtime
[21:29:47] Runtime in _disease.dm, line 54: Cannot modify null.affected_mob.
proc name: infect (/datum/disease/proc/infect)
src: Jungle Fever (/datum/disease/transformation/jungle_fever/monkeymode)
call stack:
Jungle Fever (/datum/disease/transformation/jungle_fever/monkeymode): infect( (/mob/living/carbon/human), 1)
Jungle Fever (/datum/disease/transformation/jungle_fever/monkeymode): try infect( (/mob/living/carbon/human), 1)
(/mob/living/carbon/human): ForceContractDisease(Jungle Fever (/datum/disease/transformation/jungle_fever/monkeymode), 1, 0)
Monkey Leader (/datum/antagonist/monkey/leader): on gain()
Monkey Leader (/datum/antagonist/monkey/leader): on gain()
Bozon Qark (/datum/mind): add antag datum(/datum/antagonist/monkey/leade... (/datum/antagonist/monkey/leader), null)
add monkey leader(Bozon Qark (/datum/mind), Monkeys (/datum/team/monkey))
monkey (/datum/game_mode/monkey): post setup()
Ticker (/datum/controller/subsystem/ticker): PostSetup()
Ticker (/datum/controller/subsystem/ticker): setup()
Ticker (/datum/controller/subsystem/ticker): fire(0)
Ticker (/datum/controller/subsystem/ticker): ignite(0)

**Comment by XDTM** [comment]
Might have found it

When infecting, the new disease is generated with Copy()
in /datum/disease/transformation Copy() also tries to copy all stage1,2,3,4,5 vars, with the list Copy proc

but in /datum/disease/transformation/monkey we have
```
stage1	= null
stage2	= null
stage3	= null
```
which can't run the list.Copy() which likely stops the disease Copy() proc, so it doesn't return the new disease and thus the runtime
