### ISSUE TITLE
Arrivals shuttle hull breach detection is broken

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#38767]
Revision: b17168691a2785806d05ba1b6cca3af725de10b4

The arrival shuttle doesn't properly detect hull breaches anymore.
Things it doesn't detect:
- Broken windows and broken walls that still have girders intact
- Anything deconstructed by an RCD
- Broken airlocks don't get detected all the time

Also, it doesn't seem to detect if the shuttle is fixed or if it's still broken.

This is obviously pretty bad, since players can break a shuttle window and decompress both the shuttle and arrivals.

**Comment by Cyberboss** [comment]
Unsure how this happened, it just checks for bad atmos conditions [on any of the chairs](https://github.com/tgstation/tgstation/blob/master/code/modules/shuttle/arrivals.dm#L102) and then returns if it finds any

**Comment by 81Denton** [comment]
Oh, I could have just looked up the condition instead of doing a bunch of pointless testing. Let me test again real quick.

**Comment by 81Denton** [comment]
Nevermind, it looks like it was caused by some local server issues.
