### ISSUE TITLE
oh god stargazers can use send thought while dead this is really bad

### ISSUE THREAD

**Issue by AlexTheSysop42** [tgstation/tgstation#38772]
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

round 90132

repro: be stargazer, die, be in body near any mob, use send thought

this may also happen for slimelinks, untested

**Comment by Borisvanmemes** [comment]
Makes me think about when borers were still a thing, you could talk to one while you were dead, and it wasn't, also this doesn't for slimelinks, when a stargazer dies, it's slimelink also does

**Comment by XDTM** [comment]
Oh man

**Comment by AlexTheSysop42** [comment]
@borisvanmemes

Yeah but what if you're on someone else's link

**Comment by XDTM** [comment]
I'm 90% sure you get unlinked as soon as you try
