### ISSUE TITLE
Item blood decals are not applying

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#38820]
No idea who touched this last and the code is not obviously wrong.

The component is applying and *something* is ending up in `overlays` but it's not actually delivering the appearance of blood.

**Comment by praisenarsie** [comment]
i swear i fucking saw a gif of blood overlays disappearing on some discord server or github issue but it looks like it ends up applying the blood overlay but after you turn (a couple times) it ends up disappearing

**Comment by DaxDupont** [comment]
I've seen relevant runtimes!

**Comment by ninjanomnom** [comment]
\>Doesn't post said runtimes

**Comment by DaxDupont** [comment]
I was gonna report them but anturk got me to delete my runtime list

**Comment by ninjanomnom** [comment]
Did some testing and this appears to only happen for some clients and fixes itself when you reconnect

**Comment by bgobandit** [comment]
This happens even when there are no runtimes though

**Comment by timothymtorres** [comment]
Issues #36936, #44100, #38820, and #37227 all seem to be related to a BYOND bug that was fixed at some point since there haven't been any recent issues involving overlays in the past few years.  

Going to go ahead and close them all.
