### ISSUE TITLE
Corazone doesn't work, and removing your heart doesn't kill you

### ISSUE THREAD

**Issue by Jujumatic** [tgstation/tgstation#38824]
Corazone code has nothing on mob insertion or deletion, it's defined in reagents code but doesn't actually do anything. Removing your heart does nothing but reinserting it gives you a heart attack

[Reproduction]: Remove your heart via surgery and watch as nothing happens - however if you reinsert your heart you get a heart attack and die. For corazone, get liver failure and drink the corazone, it's supposed to stop liver failure.

**Comment by vuonojenmustaturska** [comment]
broken by #35976
