### ISSUE TITLE
The tear in the fabric of reality space ruin can lead to centcom z-level.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#38839]
Round ID: 90287

Testmerges:
#38754: 'Revert "Port AI static to vis_contents"' by optimumtact at commit c19b2bdd60
#38436: 'Limb damage rework' by XDTM at commit 02f0094476
#38786: 'Gamemode setup failure resets antag rep changes.' by AnturK at commit 54b84e1770

The ladder to the space tear in the fabric of reality can lead to centcom z-levels.
![centcom](https://user-images.githubusercontent.com/4581352/42129991-33d89b7e-7ccd-11e8-97de-0636f45b3f29.png)

**Comment by SpaceManiac** [comment]
the cause is that the location is chosen by `safepick(get_area_turfs(/area/space))`

**Comment by Tlaltecuhtli** [comment]
can we also remove ladders spawning roundstart? it doesnt make sense that you can find ladders before the boh bomb happens

**Comment by Kromgar** [comment]
Its fucking weird finding a ladder when mining
