### ISSUE TITLE
having multiple cloning pods makes shit fucky or something

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#38833]
so I made a bunch of cloning pods during a meteor round to help out with all the dead people. they were all t3 manips and scanners with t2 lasers, i had around 6 or 7 total, autoprocess enabled. The cloning process would be either extremely slow or entirely eject a corpse in a couple situations. The room was fully powered and had perfect atmos, I was able to stand in it without internals or a suit and be fine. All the pods were linked to the same console. Nobody was early ejecting them or emagging the pods.

https://i.gyazo.com/374c8f0fa0ef364ab91bd207c565980e.png

sometimes it would work and clone people fully, other times it would kill the occupant.

**Comment by Hathkar** [comment]
I've also had this happen to me as well. I remember multiple pods working fine about 6 months ago, not sure what might have changed between then and now.

**Comment by kriskog** [comment]
Have you seen this since?
