### ISSUE TITLE
"closet bump"  Closets that are Booby trapped Explode when bumped into

### ISSUE THREAD

**Issue by Bod9001** [tgstation/tgstation#38848]
Issue reported from  Round ID: 90319 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Situation 
someone was dragging a boobytrapped closet and walked into me, that caused the closet to Bump into me exploding causing me to get knocked out.

**Comment by Kromgar** [comment]
Daisan no bokudan. Killer queen bites xa dusto.

Just dont touch booby trapped items. Stand users ignore their stands power

**Comment by optimumtact** [comment]
This isn't really a bug it's just a function of how byond movement code works.

You got pushed into and it triggered it to bump and exploded

**Comment by kriskog** [comment]
This has been changed.
