### ISSUE TITLE
freezing and lags when many  messages happens

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#38863]
stuff like examinating someone with many traits, health analyzers causes freezes on client, someone clogging in disposal pipe can cause even  crashes from too much spam

**Comment by ninjanomnom** [comment]
This is a long time issue with chat that can only really be resolved with a message output refactor. Not too big of one honestly but it's just never been a high priority.

The client lagging a ton from receiving messages may be considered a byond bug but I don't know enough about the chat internals to determine that.

**Comment by optimumtact** [comment]
finally got around to improving this
