### ISSUE TITLE
pAIs can interact with integrated circuits

### ISSUE THREAD

**Issue by Names-Are-Hard** [tgstation/tgstation#38860]
[Round ID]: # 90356 (BAGIL)

[Reproduction]: # Be pAI, examine adjacent circuit, remove, rename or otherwise mess with it.

![5a0d32c8c036968c2354f3b5ebfbc87e](https://user-images.githubusercontent.com/35442306/42153889-34cf6c2a-7d99-11e8-898f-d45738d914a4.gif)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by Tlaltecuhtli** [comment]
add a pulse and wire function for pais, seems like a fun feature

**Comment by Names-Are-Hard** [comment]
That should replace the door jack function
