### ISSUE TITLE
Bedsheet dream_messages don't work

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#38878]
Bedsheets have unique dream_messages, for example this one:
https://github.com/tgstation/tgstation/blob/ecd0d8b53876eef464788969c7bd85199640b686/code/game/objects/structures/bedsheet_bin.dm#L81

They don't show up in dreams, whether you recline on the same tile as a bedsheet/bed, or if you're wearing it. Being buckled to a bed doesn't make a difference.

**Comment by SpaceManiac** [comment]
Got accidentally removed by #33958
