### ISSUE TITLE
Cloning console doesn't save species

### ISSUE THREAD

**Issue by Jared-Fogle** [tgstation/tgstation#38875]
[Round ID]: # 90372

[Reproduction]: # I was a moth and at round start I had myself scanned in the cloning consoles. When I was revived through it, I was cloned as a human.

https://github.com/tgstation/tgstation/blob/ce2d7900052522578624b66e9723ebf12a549d6a/code/game/machinery/computer/cloning.dm#L471 The race is saved and used here: https://github.com/tgstation/tgstation/blob/ce2d7900052522578624b66e9723ebf12a549d6a/code/game/machinery/computer/cloning.dm#L76

**Comment by SpaceManiac** [comment]
Was your dead body still in existence or had it been completely destroyed?

**Comment by Jared-Fogle** [comment]
@SpaceManiac destroyed, is this intentional?

**Comment by SpaceManiac** [comment]
No, just digging into the cause. Destroying the body also destroys its species record, so cloning can't find it and produces a human instead. Should be fixable.

**Comment by Jared-Fogle** [comment]
Could a way to fix this be keeping the mrace line as well as a different backup key that links to the type? The comment says something about some species storing states in their datums, so I don't know the implications of my suggestion.

**Comment by kriskog** [comment]
Tried to reproduce this a few different ways with non-prescan cloning, but couldn't. Assume its no longer a thing.
