### ISSUE TITLE
L6 saw and shielded hardsuits exist

### ISSUE THREAD

**Issue by blobbernaut** [tgstation/tgstation#38904]
>declare war >buy those two items plus ammo >shoot bullets until spacemen are horizontal 

It happens exactly the same way every nuke op round. Perhaps things that actually require nerfs and impact the game more than once every 50 rounds should be what you focus on changing instead of edge cases like BOHs.

**Comment by Tlaltecuhtli** [comment]
i ded pr, just ied spear lmao

**Comment by ninjanomnom** [comment]
>focus

You seem to think we have some sort of central authority in deciding what changes get worked on. We don't. You need to either do the change yourself or convince and individual to do it for you.

**Comment by ninjanomnom** [comment]
Also, this isn't really the place to be discussing the game design. Take it to the forums or something

**Comment by DaxDupont** [comment]
what a chumbis
