### ISSUE TITLE
BoH bombs do not create a singularity but still gib the user. 

### ISSUE THREAD

**Issue by blobbernaut** [tgstation/tgstation#38903]

**Comment by AlexTheSysop42** [comment]
They arent supposed to make a singulo, they're supposed to make the big white chasm thing

@ShizCalev probably non-issue

**Comment by blobbernaut** [comment]
No, they were supposed to make a chasm that you fall into, along with the people around you, nonharmfully. Now, it should create something that actually makes sense killing you.

**Comment by blobbernaut** [comment]
I swear the people who approve PR's don't even play the video game

**Comment by ninjanomnom** [comment]
Take feature requests etc to the forums
