### ISSUE TITLE
You cant use the destructive analyzer to boost nodes anymore

### ISSUE THREAD

**Issue by AlexTheSysop42** [tgstation/tgstation#38910]
Issue reported from  Round ID: 90474 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Reproduction: get any traitor item, put in destructive analyzer, click Illegal Technology (if it doesn't show up use a different item), notice how nothing happens

Very likely caused by #38690

**Comment by SpaceManiac** [comment]
how many times is this now

**Comment by Dawson1917** [comment]
Node unlocking with the analyzer has worked for at least all of 2019, no clue when this was actually fixed
