### ISSUE TITLE
Camera static is not created unless a camera is jumped to by the AI Eye

### ISSUE THREAD

**Issue by cinder1992** [tgstation/tgstation#38919]
[Round ID]: # 90487

[Testmerges]: 
#38754: 'Revert "Port AI static to vis_contents"' by optimumtact at commit  c19b2bdd60
#38436: 'Limb damage rework' by XDTM at commit de9eb262dc
#38913: 'makes centcom festive for 4th of july (testmerge only obv)' by 81Denton at commit 77eb16d53c

[Reproduction]: Spawn in as an AI, and move the eye around the station, the issue is immediately obvious, as all of the station, space, and lavaland is visible, UNLESS you jump to a camera, where static seems to be respected for the visible area around the camera and a small area around the visible area. Moving thereafter leaves the static where it is but does not create new static.

I have tested this with #38907 merged on a local server, and can confirm this does not fix the issue with the AI eye

**Comment by SpaceManiac** [comment]
Looks like the BYOND-side bugfix that fixed the vis_contents port also *broke* the old code. So either the revert needs to be un-testmerged or the servers downgraded.

**Comment by SpaceManiac** [comment]
http://www.byond.com/forum/?post=2381424
