### ISSUE TITLE
Cere station escape shuttle flies backwards

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#38914]
As the title says, the Cerestation escape shuttle flies backwards on the way to CentCom. Oops.

---

Issue reported from Round ID: 90476 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])
Reporting client version: 512
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 90476

Server revision compiled on: 2018-07-03

The following pull requests are currently test merged:
#38754: 'Revert "Port AI static to vis_contents"' by optimumtact at commit c19b2bdd60
#38798: 'Refactors component signals to properly register for specific signals' by ninjanomnom at commit 48486df0df
#38436: 'Limb damage rework' by XDTM at commit de9eb262dc

Based off origin/master commit: 3489afb05f

Revision: 643adf0d7ffdea496c97b7c817c80a831e292964

Server tools version: /tg/station 13 Server v3.2.2.0

**Comment by SpaceManiac** [comment]
https://wombat.platymuus.com/ss13/shuttles.html

tool if you want to try to fix this yourself

**Comment by 81Denton** [comment]
Aw that's neat
