### ISSUE TITLE
the kinetic damperer bug

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#38925]
90513 bagil

so there are 2 borgs one was a peace keeper and one was a medborg

the peace keeper activates the dampener
some dude tries to buckle on top of the medborg
this happens 
Brick Carr is knocked off of Zay-1(((this one is a medborg))) by the charge in Zay-1's chassis induced by Hyperkinetic Dampener Field!

so the peace keeper dampener instead of preventing people to buckle on top of him when the field is active it prevents everyone from buclking on all borgs in range

**Comment by Tlaltecuhtli** [comment]
read it better it caused all the borgs around not only itself from being unbuckable

**Comment by fludd12** [comment]
I... Am aware. That's what I said. It is specifically made to do this in the code.

**Comment by factoryman942** [comment]
the item description says "Still being a prototype, it tends to induce a charge on ungrounded metallic **surfaces**." which does imply all borgs rather than just the peacekeeper

_also make it stun people trying to buckle to chairs when_

**Comment by kriskog** [comment]
Not a bug
