### ISSUE TITLE
Bug Report: Rechargers

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#38924]
Issue reported from  Round ID: 90511 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

All the rechargers on Meta Station appeared to not be working for anyone, regardless of intent. This resulted in being unable to recharge energy weapons and stun prods.

**Comment by ninjanomnom** [comment]
duplicate of #38880
