### ISSUE TITLE
Xenobio Cameras Not Giving Vision

### ISSUE THREAD

**Issue by RandolfTheOkay** [tgstation/tgstation#38926]
Issue reported from  Round ID: 90515 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Posting this on behalf of Fwoosh. While working xenobio one shift, the cameras in all the pens were not giving vision, but were instead all static.

**Comment by RedFoxIV** [comment]
Camera view - https://i.imgur.com/9EJ776W.png
Notices how Cameras - https://i.imgur.com/lxOuc2P.png aren't broken and are active.

**Comment by kriskog** [comment]
I remember this around that time, it was fixed and haven't seen it since.
