### ISSUE TITLE
Canvases cause clients to "crash"and close themselves

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#38942]
[Round ID]: ??? server got hard-rebooted so it doesn't exist 
Server was bagil

Someone call MSO what's going on with my ss13. I felt like this needed to be addressed because it clearly doesn't just happen to me randomly. It's serverside, not client side!

**Comment by SpaceManiac** [comment]
Naksu said this was caused by a canvas

**Comment by vuonojenmustaturska** [comment]
if you were near a hallway, it was caused by a painting

**Comment by Shadowflame909** [comment]
I was floating around the station as a ghost. So maybe? Most of the ghosts said they were crashing.

Who knew that art could close peoples clients. That's interesting.

**Comment by Shadowflame909** [comment]
It's not the canvas. It happens randomly guys

**Comment by Stickymayhem** [comment]
It is the canvas. The crashing stops after all of them are deleted.

**Comment by Jared-Fogle** [comment]
Maybe temporarily make canvases automatically delete themselves while MSO figures it out?

**Comment by ExcessiveUseOfCobblestone** [comment]
`Canvases cause clients to crash"and close themselves `

**Comment by Shadowflame909** [comment]
@ExcessiveUseOfCobblestone Im sorry but sticks and stones may break by bones but lola cobblestone isnt the tgstation meme waifu

**Comment by Mothblocks** [comment]
This was fun
