### ISSUE TITLE
You have failed to qualify for any job you desired.

### ISSUE THREAD

**Issue by DrChef** [tgstation/tgstation#38943]
[Round ID]: # 90559 

[Reproduction]: If I set my job preferences to return me to the lobby if my preferences aren't available, then I'll often get sent back to the lobby and I'll find that the job I wanted is still available.

[Why do you think this is a bug]: If I want to be a certain role at round start I will not always be it, which is understandable when there is a high server population or a popular role, but if I get booted back to the lobby and find the role I wanted at shift start is still available I then I'm assuming it is a bug.

**Comment by SpaceManiac** [comment]
Jobs have different capacities for roundstart and latejoin, this is intended behavior
