### ISSUE TITLE
AI cameras have random glitchy static in places they shouldn't be, rarely

### ISSUE THREAD

**Issue by Daundra** [tgstation/tgstation#38945]
Round ID: 90576
revision a088bde838

Pictures will give most of the info but basically a very small amount of my cameras have static in places that have no business having static which has led to me being unable to follow orders more than 3 times this round due to the static blocking things such as doors and consoles.

I have no idea if this is related to any of the other bug reports involving AI cameras so that is why I put this up as its own issue.

related images:
![dreamseeker_2018-07-06_02-40-48](https://user-images.githubusercontent.com/5360736/42364351-d3455fe0-80c8-11e8-85ae-608623e83498.png)
![dreamseeker_2018-07-06_02-30-16](https://user-images.githubusercontent.com/5360736/42364360-d8f57db2-80c8-11e8-8768-ee7e7af087f6.png)

**Comment by SpaceManiac** [comment]
What client version? Try updating to the latest beta (512.1435) and see if the problem persists.

**Comment by SpaceManiac** [comment]
AI static has been running up against a lot of BYOND issues since a recent tweak to its internals. Eventually we'll land on a version where everything works when client+server are updated.
