### ISSUE TITLE
sneezing and other synthoms caused by viruses ignores the fact you are already dead

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#38947]
round id: 90581 bagil
You cannot sneeze while unconscious.
Your skin erupts into an inferno!
You feel sandy.

all this while fucking dead

**Comment by XDTM** [comment]
Probably a process_dead disease, i guess it needs some checks for emotes and messages

**Comment by XDTM** [comment]
Alright, the disease working during death is a feature, emotes are handled in #39006, and the rest of the messages should probably stay for feedback so you know _why_ your corpse burst into fire. You can just leave the corpse as a ghost if you want to avoid them anyway.

**Comment by XDTM** [comment]
@AnturK i wouldn't consider it a bug due to the reasoning above
