### ISSUE TITLE
The NASA jumpsuit doesn't stop pressure damage in space

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#38955]
Title, the NASA jumpsuit "/obj/item/clothing/under/space" is no longer space worthy since the user will still take pressure damage when worn in space.

To reproduce wear the NASA jumpsuit, shoes, gloves, and a space worthy helmet and jump into space, then watch as you die from the vacuum of space anyway.

Everything about the jumpsuit says it's space worthy, and it used to be so until breaking at some point.

Possibly caused by #37486 but don't trust me on this.

**Comment by GravitronBlue** [comment]
To my knowledge it's adminspawn only at the moment, but lately been needing but unable to create a proper fix in order to fix 'something' else.

![lok-lod-n-stn-boiz](https://user-images.githubusercontent.com/17460297/42416152-f2d4920a-821b-11e8-8699-9b082f096436.jpg)

**Comment by optimumtact** [comment]
it's not worth keeping the historical behaviour given it's just a jumpsuit sprite
