### ISSUE TITLE
Microwaves do not check user range

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#38959]
Open its menu.
Click on the game window and walk away.
You can still turn it on at any range.

tested on 7/5/18v unsure of version

**Comment by Jared-Fogle** [comment]
Extremely easy fix

https://github.com/tgstation/tgstation/blob/2f8f166d8885841869e6212991bdff06553fae80/code/modules/food_and_drinks/kitchen_machinery/microwave.dm#L309

Add `if(!Adjacent(user)) return`

**Comment by Cyprex** [comment]
See https://github.com/tgstation/tgstation/pull/38939
