### ISSUE TITLE
Zombifying process doesn't care if you got revived.

### ISSUE THREAD

**Issue by OmegaShoots** [tgstation/tgstation#38952]
Issue reported from  Round ID: 90591

Zombie event, I got attacked by an infectious zombie and end up dying. Someone revived me with a staff of healing a few seconds later and I'm walking around alive and well.

However, a few minutes later I'm turned into a zombie while alive.

**Comment by Kromgar** [comment]
Magic... how does it work?

**Comment by XDTM** [comment]
```
if(!converts_living && owner.stat != DEAD)
	return
```
Odd, this shouldn't happen

**Comment by XDTM** [comment]
well that's dumb
