### ISSUE TITLE
Flight suits allow you to slip past airlocks with their ID wire cut

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#38957]
Here's one that's NOT reported.

How to reproduce: Cut the ID scanning wire on an airlock and run into it at speed with a flight suit with flight engines engaged. The intended behavior is for you to be stopped (nothing can open an airlock with its ID wire cut except pulsing the open wire) but instead you slip right through.

**Comment by Tlaltecuhtli** [comment]
the flight suit makes you fly on top of the door
