### ISSUE TITLE
Transparent pixels when wearing regular(non departemental) headset

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#38968]
On master c213eaf

With generic headset:
![dreamseeker_2018-07-07_14-34-40](https://user-images.githubusercontent.com/17237624/42410946-2833c552-81f3-11e8-92e1-3399e12fe052.png)
^ note the pixels around the ear height.

Departemental headset:
![dreamseeker_2018-07-07_14-36-50](https://user-images.githubusercontent.com/17237624/42410956-4172bf3c-81f3-11e8-8f89-8fab12ec9ee4.png)

**Comment by Mickyan** [comment]
Upon further inspection this appears to be intended to look like a clear tube earpiece, hair tends to obscure most of it

So I suppose the real issue is that the sprite for the inventory item looks like a regular old headset

**Comment by DaxDupont** [comment]
but why would only the generic one have this and not ANY other.

**Comment by DaxDupont** [comment]
it's also ugly as sin

**Comment by Mickyan** [comment]
Beats me, just saying they're not rogue pixels

**Comment by ArcaneDefence** [comment]
Headset radios have different sprites now
