### ISSUE TITLE
That one PR that made it so rebee would only spawn on clock cult didnt work. Rebee didnt spawn at all

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#38979]
[Round ID] 90695
Server: Bagil

Clock cult machine broke. The only thing that made this round worth it was alphonzo playing "I want Pizza"

**Comment by Ratvar** [comment]
old news

**Comment by SpaceManiac** [comment]
round ID please, also did the admins set the gamemode to clockcult or just spawn clockies in manually

**Comment by Shadowflame909** [comment]
It's really weird how round IDs don't appear on issue requests. Also it was set to clock cult at round start. Rebee didn't appear. The clockies had station jobs. Abscond just made your screen purple.

**Comment by SpaceManiac** [comment]
thanks, I'll look into it
