### ISSUE TITLE
Integrated clock circuit gives round time rather then station time

### ISSUE THREAD

**Issue by Astrolight** [tgstation/tgstation#38971]
[Round ID]: 90668

Integrated time circuit under the 'Time' tab says
"[integrated clock]: Tells you what the local time is, specific to your station or planet."
I expect it to give the station time such as if the lights are in night time or not. What I get is actually the round time"

[Reproduction]: Print integrated clock circut, put in basic shell and pulse the 'get time' ping.

![capture](https://user-images.githubusercontent.com/8404187/42414142-f90f2f5a-81fc-11e8-8df5-588142e1cf91.PNG)

**Comment by Vidiveni** [comment]
Station time existing is a bit annoying imo. I can no longer say "I'll blow my bombs at 12:30" without specifying I mean shift time.

**Comment by Iamgoofball** [comment]
It's handy if you want time shit for "after the game starts" or know exactly how long.

**Comment by Jared-Fogle** [comment]
@Vidiveni Is there any reason station time exists other than night lights (which I still don't understand the point of)? Couldn't station time be axed and night lights just go off of their own hidden time?

**Comment by ExcessiveUseOfCobblestone** [comment]
Station time is the IC version of round time, which is why i'm not sure why we make it visible to the player while they're alive.

**Comment by Jared-Fogle** [comment]
@ExcessiveUseOfCobblestone Hiding round time would just make it impossible to coordinate anything because nobody knows how fast station time moves in relation to round time.

**Comment by ExcessiveUseOfCobblestone** [comment]
no? you'd just use station time to coordinate everything?

**Comment by Jared-Fogle** [comment]
Easier to say "we're leaving in 10 minutes" or "we're leaving at 00:30 shift time" and have it be obvious than to give your times in station time.

**Comment by Astrolight** [comment]
Would it not be easier to take the best of both worlds with an option in this chip to return "Shift time" (round time) or "Station time"?

**Comment by ExcessiveUseOfCobblestone** [comment]
@Jared-Fogle do you really think you can't say "we're leaving in 10 minutes" if everyone is on a sync'd time that isn't round time?

you're absolutely arguing in bad faith.

**Comment by Jared-Fogle** [comment]
@ExcessiveUseOfCobblestone If 10 minutes isn't 10 real time minutes, then yes.

**Comment by ExcessiveUseOfCobblestone** [comment]
I thought that's what we were talking about when referring to "station time"???

**Comment by Jared-Fogle** [comment]
@ExcessiveUseOfCobblestone That's now what station time is on /tg/. Station time moves at an extremely fast rate compared to real time. You can even see in the screenshot.

![image](https://user-images.githubusercontent.com/35135081/42536570-4d479c8c-8447-11e8-8030-99b95550fa9b.png)

If station time were accurate to real time, it'd be `12:31:47`.

**Comment by ExcessiveUseOfCobblestone** [comment]
my bad then, dunno why that's even a thing.

**Comment by Astrolight** [comment]
Fixed by #39140
