### ISSUE TITLE
The server crashes at least 60 percent of the time on bagil.

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#38981]
Round Id: Lost
Server: Bagil
Key Holders:Forced to be awake at all times

is this a bug

**Comment by Shadowflame909** [comment]
dum dum speller

**Comment by Hathkar** [comment]
Yes, server is crashing consistently about every other round. Anything lasting longer than 30+ minutes risks a crash. From what I can remember, this issue has been going on for several days now. Not sure when it started.

**Comment by GuppyLaxx** [comment]
this is why you should play sybil instead

**Comment by Shadowflame909** [comment]
good job you fixed it 

Problem solved

for now
