### ISSUE TITLE
tesla bolts seem to damage wires

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#38984]
Issue reported from  Round ID: 90706 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

pubby has a tesla engine with uncovered wires i think it may cause death and destruction once the emitter wires get cut

**Comment by chesse20** [comment]
proposed fix, put a paper in the engine room thats a note telling the enginners to put tiles over the wires near the tesla

**Comment by 81Denton** [comment]
I've spawned a tesla ball on top of a bunch of cables, they got zapped but didn't take any damage from it. Let me boot up a Pubby test server and leave the engine running for a bit.

**Comment by 81Denton** [comment]
Nothing after 25 minutes. Maybe it's something odd like #38317?

**Comment by Tlaltecuhtli** [comment]
i was ghosting around and what i saw a tesla shock and then a bunch of random fire on the wires, i examinated and they were damaged it happened only once and didnt repeat

**Comment by kriskog** [comment]
Cant reproduce, pubby doesnt have the engine anymore. Lets assume this is fine.
