### ISSUE TITLE
You can break cycle linked bolting airlocks by having something stand in them.

### ISSUE THREAD

**Issue by GuyonBroadway** [tgstation/tgstation#38989]
-Go viro
-punch a few monkeys
-Try to leave viro
-Monkeys block the internal airlock
-None of the buttons or console work to open the viro airlock

From here the virology airlock is bolted forever and there is no way to open it without external help. 

If there's no AI and nobody with the Medical door remote you are fucked.

**Comment by Dorsisdwarf** [comment]
wait this is why linked doors just stop working sometimes? finally

**Comment by newfren** [comment]
I don't know why I never reported this but it is annoying as fuck.

**Comment by Tlaltecuhtli** [comment]
i use this intentionally to remove bolt cycling
