### ISSUE TITLE
Filter/air alarm settings can't be inspected by ghosts

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#38985]
A) Ghosts can't see the current filter settings since the interface is greyed out for them.
B) Ghost can't see current air alarm settings either, since they can't open vent/scrubber/operating mode settings.

Examples:
![filters-ghost](https://user-images.githubusercontent.com/32391752/42419859-2a0a098e-82bd-11e8-8475-7ec3d20e69e6.PNG)
![airalarm-ghost](https://user-images.githubusercontent.com/32391752/42419860-2c29e1d0-82bd-11e8-86ce-1377814342b3.PNG)

**Comment by AnturK** [comment]
Could use another style for disabled and toggled.

**Comment by kriskog** [comment]
A is fixed, B is not.

**Comment by stylemistake** [comment]
N/A for recent tgui.
