### ISSUE TITLE
Hypodermic Prickles doesn't work how it should work. Might be a death nettle problem, though.

### ISSUE THREAD

**Issue by fen0s** [tgstation/tgstation#38993]
[Server]: # Bagil
[Round ID]: # 90729

[Revision]: # 31724d8c709b75fec8ffbdf144b56751d3a7f966

[Reproduction]: # Get a mute toxin gene in death nettle. Test it on yourself. You still can speak. Same with any other chemicals - nettles don't inject it in you. And, even if you remove the acid production, then it will still burn you, though it shouldn't.
Remove acid genes in death nettle. It will still burn you and will deal damage, though it shouldn't, because acid should be the one that deals damage, not just nettle itself.

[For Admins]: Nothing here.

Admins reported me about this problem in discord, which I tested, and it was true.
From unchecked things - if you'll place prickles in other plant with chemicals, then it will work as it should, but it will inject 33% less of chemicals it should inject in you, but I have no things to test it as regular player. So, I'm not sure if it's death nettles problem or hypodermic prickles problem. Maybe both.

**Comment by ExcessiveUseOfCobblestone** [comment]
hypodermic prickles is for throwing only, I looked into it only slightly when @Shadowflame909 told me about it.

**Comment by Shadowflame909** [comment]
>but it will inject 33% less of chemicals it should inject in you.

That spooked me. but I think that might be the plants reagent capacity. 100 potency plants without densified chemicals can only contain 50 units of chems. You have to get densified chems boi

**Comment by XDTM** [comment]
Max of 20 chems either way, it's 0.2u per potency

**Comment by fen0s** [comment]
Shouldn't death nettles still inject things in someone who you hit with them? This kinda makes no sense then. ALL of the admins told me that death nettles should inject chems inside of them on hit.

**Comment by XDTM** [comment]
Codewise they don't, we'd have to ask the coder who added these why it's this way. Nettles' damage and stun is hardcoded.

**Comment by fen0s** [comment]
That's weird. Guess, making a new feature thread so coders will change it on hypodermic that injects chems in melee fight too.

**Comment by AnturK** [comment]
As far as i can tell this was mostly balance, anyway not a bug.

**Comment by ExcessiveUseOfCobblestone** [comment]
I can fix the nettle giving you sulfuric rather than using the chems inside it.
