### ISSUE TITLE
The latest version of byonds unstable build makes ventcrawling a laggy pain

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#39004]
Your client will nearly crash at every move you make. Then you'll find yourself at the other side of the hall.

Scrubbers are a bit better though, this happened a few days ago when I was playing as a morph. So I dont know the round ID. But recent morph players have also reported this being such a bad case.

**Comment by SpaceManiac** [comment]
Cannot reproduce locally

**Comment by ninjanomnom** [comment]
Was having this issue earlier and can confirm it's still present in 1437

**Comment by Jalleo** [comment]
Probably needs to be reported to Lummox.

**Comment by ninjanomnom** [comment]
Oh right I forgot to close this, this seems to be fixed in 1438
