### ISSUE TITLE
AI camera eye can see in maintenance

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#39018]
Round ID: 90778

![image](https://user-images.githubusercontent.com/12382984/42463064-fdc50ea6-839c-11e8-9255-74b5d9717831.png)
I literally just spawned in roundstart and I could see everything

**Comment by Anonmare** [comment]
UPDATE: It just went to static after 5 minutes

**Comment by Yenwodyah** [comment]
I had the same issue on round 94414 on Sybil, it went away after a few minutes too.

**Comment by BebeYoshi** [comment]
Isn't this the same issue as #38857?

**Comment by actioninja** [comment]
Yes, dupe issue of #38857
