### ISSUE TITLE
ID console issue

### ISSUE THREAD

**Issue by Emmanuel-Goldstein** [tgstation/tgstation#39022]
Round ID: 90788

Reproduction: I wish I could be more helpful, but all I know is that twice in the round, the console became unusable and had to be deconstructed and reconstructed. I got a volunteer to try and use it and he couldn't either. Both times it seemed to happen after I put in a card.

**Comment by Jared-Fogle** [comment]
```
The following runtime has occurred 75 time(s).
runtime error: type mismatch: 1 + " - "
proc name: ui interact (/obj/machinery/computer/card/ui_interact)
  source file: card.dm,145
  usr: Emmanuel Goldstein (/mob/living/carbon/human)
  src: the identification console (/obj/machinery/computer/card)```
