### ISSUE TITLE
Cameras messed up in xenobio

### ISSUE THREAD

**Issue by CreationPro** [tgstation/tgstation#39026]
Issue reported from  Round ID: 90797 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Cameras goofed up in xenobio. Real fucky, some tiles showed up right, some were static. Tried deactivating and reactivating, did not help.
https://i.imgur.com/2d18lIT.png
How to reproduce: use the xenobio slime control console more than once.

**Comment by SpaceManiac** [comment]
What client version do you have installed?

**Comment by CreationPro** [comment]
512.1435

**Comment by RedFoxIV** [comment]
https://github.com/tgstation/tgstation/issues/38926
Duped issue.
