### ISSUE TITLE
Wizard mass body swap includes Lavaland roles

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#39033]
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)
Round ID: 90817

Server revision compiled on: 2018-07-09

The following pull requests are currently test merged:
#38995: 'Adds looping timers' by ninjanomnom at commit 7c06a22fef
#38990: 'Allow players to un-ignore previously ignored popups for ghostroles, and ignore notifications with no ignore button' by vuonojenmustaturska at commit 1239163cf1

Based off origin/master commit: ff77dac694

Revision: ca71240a207d0a33ede599de88bec1d76a0daa2c

Server tools version: /tg/station 13 Server v3.2.2.0

Not a bug, but body swap probably shouldn't include people who are off the z-level because then they end up inhabiting ghost roles in the middle of nowhere which isn't really fair on them. Hilarious though.

**Comment by XDTM** [comment]
No such thing as fair in a wizard round

**Comment by zaracka** [comment]
Reminds me of the time I was mindswapped into VR (no you can't get out).

**Comment by fludd12** [comment]
Mindswapping into vr probably is a big but it's a *good* bug

**Comment by optimumtact** [comment]
honestly this seems fine, wizard rounds are gonna be a clusterfuck anyway
