### ISSUE TITLE
Golem shells don't accept certain sheet subtypes

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39048]
Incomplete golem shells (/obj/item/golem_shell) don't accept certain mineral sheet subtypes:
- /obj/item/stack/sheet/mineral/titanium/fifty
- /obj/item/stack/tile/brass/thirty + fifty
- /obj/item/stack/sheet/mineral/sandstone/thirty

Other subtypes like metal/fifty work fine. No clue why.

**Comment by XDTM** [comment]
because it checks the merge_type for the stack, implemented for this reason; all mineral sheets should have it set to their base type, otherwise it picks it automatically which makes the /fifty variants not stack together
