### ISSUE TITLE
"Toggle Nuke" doesn't disable nukes properly

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39042]
1) Enable a nuke with the fun panel "Toggle Nuke" verb.
2) Press the button a second time and select the same nuke - it disables and then instantly activates the nuke again.
3) Press the button a third time; it will deactivate the nuke. From now on, "Toggle Nuke" will properly activate/deactivate this nuke. 

Other nukes will have to be deactivated twice in a row before they can be toggled properly.

**Comment by kriskog** [comment]
Cant reproduce
