### ISSUE TITLE
Bomb beer keg has plutonium core

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#39056]
Round ID: 90849

Server revision compiled on: 2018-07-10

The following pull requests are currently test merged:
#38995: 'Adds looping timers' by ninjanomnom at commit 7c06a22fef

Based off origin/master commit: 0e4cadbcd6

Revision: 96c50fbe1c33a108ed2e4100dcc071f38f32289b

Server tools version: /tg/station 13 Server v3.2.2.0

Beer keg nuke has an actual core what the fuck

**Comment by SpaceManiac** [comment]
it is specifically not supposed to do this

**Comment by Jalleo** [comment]
Tested it locally it does not have a core. @Supermichael777 by what regards do you think it had a core. As in the visual issue if someone tries to break it open in that it looks like one is in there or that you can activate it?

**Comment by Hathkar** [comment]
Replace the plutonium core with a ethanol/hydroxyethane/methylcarbinol core, and have it temporarily flood the vents with beer if activated, similar to the clogged vents random event.

Turn that bug into a feature.

**Comment by 81Denton** [comment]
Can't repo on localhost
`Nanotrasen-brand nuclear fission explosive has had its plutonium core removed as a part of being decommissioned.`

**Comment by RedFoxIV** [comment]
methanol core.

**Comment by bgobandit** [comment]
fucking feature

**Comment by WJohn** [comment]
![](https://i.imgur.com/CsAYLSw.png)

It only LOOKS like it has a core in it, even though we actually have a sprite of it without the core.

Also, crowbaring the inner plate (2nd crowbar use) causes you to also strike the beer nuke after completing the action. Possible this happens on other nuke types as well.

**Comment by swankcookie** [comment]
@SpaceManiac this is pretty clearly just a misunderstanding. It seems like this can be closed

**Comment by PKPenguin321** [comment]
I think I'll leave this open because the bomb keg should really ought to be a resprite of the keg and not a re-code of the actual nuke
