### ISSUE TITLE
Cloth golem bandage piles can't be properly interacted with 

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39051]
The bandage piles cloth golems leave behind on death (/obj/structure/cloth_pile) can't be properly interacted with:
- Can't be clicked on in general, for example for targeting with guns or welders
- Can't be examined with shift+leftclick, only with RMB context menu
- Can't be dragged, put in lockers/crates or picked up
- You can still set them on fire with a flamethrower/CLF3 spray, but they will never actually burn to ashes. Golems that get killed while on fire properly burn to ashes.

**Comment by XDTM** [comment]
something with click opacity it seems

**Comment by fludd12** [comment]
I've noticed this with a lot of structures, actually. What's going on...?

**Comment by dragomagol** [comment]
Appears to have been fixed
