### ISSUE TITLE
Odd cloth golem megafauna death

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39050]
If megafauna kills a cloth golem, they get the "You start gathering your life energy, preparing to rise again..." message and the cloth pile spawns. However, the body also gets gibbed, which ends up preventing revival.

This leaves players in an odd state where game messages tell them that they're getting revived, but they're actually dead. 
Intended behavior would be to dust the cloth pile with no organs spawned.

**Comment by Barhandar** [comment]
Better intended behavior would be cloth golems not getting gibbed, so they're at least _marginally_ useful on lavaland.

**Comment by dragomagol** [comment]
Appears to have been fixed (cloth golems no longer leave bandage piles on gib)
