### ISSUE TITLE
Tesla being released on the station causes server to lag and run poorly. It also leaves behind lightning beams that don't go away.

### ISSUE THREAD

**Issue by yoyobatty** [tgstation/tgstation#39057]
[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

Let the tesla get loose and it lags the server immensely, and it gets exponentially worse the more orbitting energy balls. I think it's related to explosions and objects being damaged without checking if they still exist. I also suspect that beams being left behind by the tesla contribute to this poor performance issue as well.

**Comment by Jalleo** [comment]
This is a reoccurring issue either there is a current issue report before this or its just become a issue again more recently. Round ids and server are suggested for this particular type of issue.

**Comment by LemonInTheDark** [comment]
Should be resolved now that beams are event based, explosions suck less, and the tesla doesn't use explosions any more.
It still eats up a bit of time, but not nearly as much
