### ISSUE TITLE
Ship navigation consoles (the camera ones) don't work

### ISSUE THREAD

**Issue by AlexTheSysop42** [tgstation/tgstation#39065]
Issue reported from  Round ID: 90844 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

It says the connection is severed. I wasnt a pirate but I've had this bug before other times, and this round made me remember to report it.

**Comment by Cyprex** [comment]
Duplicate of #39030
