### ISSUE TITLE
Items thrown onto lava tiles do not burn. Items that are thrown onto a lava tile by a gibtonite explosion do not burn either.

### ISSUE THREAD

**Issue by nervere** [tgstation/tgstation#39066]
[Round ID]: #90868 on Bagil

[Testmerges]: #38995 and #39059 were both testmerged, but I don't know if either would affect this.

[Reproduction]: Throw an object onto a lava tile on lavaland (lavaland is where this was tested). It shouldn't burn. If you trigger a gibtonite explosion, in which nearby items are thrown into a lava tile by that explosion, it shouldn't burn either. It should be noted, though, that objects will still burn if you stand on top of a lava tile and drop the item.

**Comment by ExcessiveUseOfCobblestone** [comment]
> throw something onto lava

> it shouldn't burn

Could you please explain what you mean by that?

**Comment by Bluespace** [comment]
He means it won't burn if you throw it onto lava. It SHOULD burn, but it doesn't.

**Comment by ExcessiveUseOfCobblestone** [comment]
does ore smelt when you toss it into lava?

**Comment by ExcessiveUseOfCobblestone** [comment]
someone touched fire_act then hmmm....

**Comment by Learner10** [comment]
The effects of this bug can be felt by the fact that Goliath meat can not be safely cooked if it is not set on fire by lava.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
If you move the item on top of some lava and call burn_stuff(thing) on it, it will burn, so it's an issue with hitby() or something else related to throwing.

**Comment by octareenroon91** [comment]
hitby() does nothing if throwing is still set.
throwing stays set until the thrownthing datum goes Destroy per #38513 .
