### ISSUE TITLE
Nothing can be done about this says only station where this regularly hapens

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#39082]
On Thursday July 12 Bubblegum was brought up on the mining shuttle and killed 40. Local coders were reported to say that it was "Emergent gameplay" and that "there was just no way to prevent it. They say their asays and prayers go to the victims of this horrible but unavoidable tragedy.

**Comment by ExcessiveUseOfCobblestone** [comment]
is this an issue or a request?
