### ISSUE TITLE
possible client crash inducer

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#39084]
[Round ID]: # 90920 and  90909 BAGEL
byond client version 1435
this happened 2 times in 2 different rounds in similar way so it may have the cause of the crashes
what i was doing:
unwrenching a reinforced floor on an alt clicked floor in the toxin chamber
it froze and crashed midway the do_after

**Comment by DaxDupont** [comment]
the server or the client

**Comment by Jared-Fogle** [comment]
Cant reproduce

**Comment by DingleFlop** [comment]
Old BYOND version?

**Comment by nicbn** [comment]
coincidence?
