### ISSUE TITLE
sometimes, piggyback riding causes sprites to be superimposed on top of each other weirdly 

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#39087]
[Reproduction]: # seems to happen randomly with piggyback riding
![2017-12-10_01-20-59](https://user-images.githubusercontent.com/16103879/42647950-1584dd96-860e-11e8-8e25-c63e0449525c.gif)
@kevinz000

**Comment by Tlaltecuhtli** [comment]
are you sure it wasnt a changeling

**Comment by Militaires** [comment]
@Tlaltecuhtli negroid that's me in the gif

**Comment by kevinz000** [comment]
thonk

**Comment by kevinz000** [comment]
will look into it
