### ISSUE TITLE
Spray can that can paint infinite number of windows

### ISSUE THREAD

**Issue by Slomacz** [tgstation/tgstation#39094]
Issue reported from  Round ID: 90928 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

If you get the new spray can paint few windows with it then draw one random rune on the floor. You will acquire a spray can that can paint infinite number of windows.

**Comment by ShizCalev** [comment]
dupe #38687
