### ISSUE TITLE
Cloning pods continually spit people out early, usually killing them

### ISSUE THREAD

**Issue by Daundra** [tgstation/tgstation#39101]
Round ID: 90948 (if it matters this issue also happened to me the very round before this)
Based off 96c50fbe1c

Attempting to clone the clown during this round instead forced him out of the cloning pod not even a minute in.
It then threw this error in the medical radio channel:
![image](https://user-images.githubusercontent.com/5360736/42674636-950b1910-863e-11e8-87ee-e95da749de96.png)

The corpse it spat out was able to be scanned and another cloning process started. The APC did not suffer a power failure midway through and the equipment option of the APC was not disabled. Here is a picture of the genetics APC to confirm this:
![image](https://user-images.githubusercontent.com/5360736/42674699-cd1d46c0-863e-11e8-94f5-3adc3f1a1597.png)

The clown was then successfully cloned on the second attempt (albeit with less health than he should have had during normal cloning) which is why I don't know if this issue is easily reproduceable.

Is this a bug or was there an undocumented cloning change causing this?

**Comment by yoyobatty** [comment]
We were having this issue on hippiestation as well. Not sure what causes it but I know that the cloning completion percentage is based off of mob health.

**Comment by ThatLing** [comment]
Seen this happen on Yogstation aswell.

**Comment by AnturK** [comment]
Caused by #38828, if the clone doesn't regrow heart fast enough they will die.

@XDTM

**Comment by XDTM** [comment]
ah fuck, i forgot to make STABLEHEART work for missing hearts
