### ISSUE TITLE
Slimes cannot emote, ventcrawling hangs client

### ISSUE THREAD

**Issue by Kagus** [tgstation/tgstation#39108]
Issue reported from  Round ID: 90955 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

Using latest beta version of BYOND client.

Latejoined round as an observer, and after a short while a pyroclastic anomaly event occurred. It wasn't defused, so when it reached the end of its countdown an adult red slime was spawned and I was given the prompt asking if I wanted to take control of the slime. After a little hemming and hawing, I chose to take control of the slime (I didn't time myself for how long it took before making the decision, so I'm uncertain how far the 10-second timer had ticked down).

After taking over the slime, I quickly realized two things: 1) Attempting to move inside of an atmospherics pipe would without fail hang the client and repeat my move command until I reached a bend or natural termination in the pipe. Extremely short button presses of a movement key (using the WASD setup in this case) would momentarily freeze the client before moving me one tile, but anything longer would carry me down the entire length of the pipe. Alternative behavior could be achieved by simultaneously pressing two movement keys, which would freeze the client before stopping and updating me at the first pipe manifold that allowed me to go in the direction of the second move command. I believe this issue has been noticed and reported before, I'm just including it here for completion's sake.

 Issue 2) Attempting to emote would simply ignore the command. Using either say"*(emote) or the "Me" command would return nothing, not even an error message. Even attempting to get a list of applicable terms with the *Help emote was just ignored. Attempting to use a custom emote via "Me" would also just eat the command and return nothing. I attempted some slime-specific emotes via say"*(emote), such as *moodsmile, *moodnone and *vibrate, as well as generic emotes such as *flip and *spin. No result from anything.

**Comment by Kagus** [comment]
This might extend to other simple creatures possessed by players as well. Due to a fairly shenanigan-heavy round, I got the opportunity to attempt emoting while a butterfly, and then later as an Easter bunny after the butterfly was brutally chainsawed to death.  Both mobs displayed the same behavior: Attempting to perform generic emotes such as *flip and *spin had no effect, and using *help returned no message or feedback of any kind.

The chainsaw likely isn't a relevant factor, but y'know... For completion's sake.

**Comment by Cyprex** [comment]
The ventcrawling part was fixed by #41645. I feel like this issue should be closed, and a new issue "Simplemobs cannot emote" should be opened, if that is indeed the case.
