### ISSUE TITLE
Newly created machines are broken

### ISSUE THREAD

**Issue by TerraSleet** [tgstation/tgstation#39109]
A recent update (presumably the one that added nanites) made it so that all newly created machines:

1. cannot be upgraded using an RPED / Bluespace RPED
2. will not drop its corresponding electronics board when disassembled

This essentially means the Free Golem ghostrole is bugged to shit as machines cannot be upgraded and if it's disassembled the board is deleted meaning you have to spend another 2000 points on the Liberator box.

Machines spawned on map generation don't appear to have these issues (although disassembling and reassembling one will cause it to have these issues.)

**Comment by XDTM** [comment]
Issue with the nanite PR, should be fixed after updating
