### ISSUE TITLE
CentCom communications consoles do not work

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39107]
Trying to log into a comms console on CentCom itself gives the following error message: Unable to establish a connection: You're too far away from the station!

Probably needs an area check so admins can use it on CentCom, but not other areas of the centcom z-level (like the tear in reality).

**Comment by Cyprex** [comment]
Intentionally broken by #38249

**Comment by 81Denton** [comment]
Oh, good to know.
