### ISSUE TITLE
change of staff + revs

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#39116]
so uhhhh it was wizard  and rev round i got flashed, i got changed into a xeno (was still a rev) then i got changed again into a borg (no longer a rev) then again into a goat (no longer a rev)
it seems being turned into a  borg by a SoC removes your rev status

**Comment by PKPenguin321** [comment]
Doesn't sound like a bug

**Comment by Wilchenx** [comment]
I think its to prevent borgs messing with heads.

**Comment by Cyprex** [comment]
Silicon Laws overrule antag status IIRC, but not everyone necessarily is aware of that.

**Comment by Wilchenx** [comment]
https://tgstation13.org/phpBB/viewtopic.php?f=33&t=18608
https://tgstation13.org/phpBB/viewtopic.php?f=33&t=18588

**Comment by AlexTheSysop42** [comment]
Being borged normally de-revs you (probably for the reasons wilchen said), this seems like it could be unintended. It happens with blood cult too.

Also @cyprex it completely removes it, unlike (most) other antags

**Comment by AnturK** [comment]
Working as intended.
