### ISSUE TITLE
COMPONENT_DUPE_HIGHLANDER doesn't work

### ISSUE THREAD

**Issue by Garen7** [tgstation/tgstation#39122]
Reproduction steps:
1. get a chair(/obj/structure/chair)
2. pick up the chair and plant it(use in hand) multiple times
3. view variables of chair
4. search for the datum_components variable
5. notice that there are multiple of the component(/datum/component/simple_rotation) that is added to the chair in ComponentInitialize()

I noticed this when creating a component that I would use TransferComponents() a lot with, since the component created on ComponentInitialize() doesn't get removed.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Cyberboss

**Comment by Cyberboss** [comment]
Are you sure they aren't references to the same instance of the component?
The datum_components list does hold multiple references to each component
for organization

**Comment by SpaceManiac** [comment]
@Cyberboss it's a real bug

**Comment by Garen7** [comment]
Yeah each component was a different object I checked that to make sure.
