### ISSUE TITLE
Lesser ash dragon interaction with SM crystal/singulo/tesla

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39130]
If a player controlled lesser ash drake (transformed by /obj/item/dragons_blood -> obj/effect/proc_holder/spell/targeted/shapeshift/dragon) touches a supermatter crystal, their original body gets dropped as a corpse instead of getting dusted as well.

Lesser ash drakes are also immune to singularities and tesla energy balls.

**Comment by Jacquerel** [comment]
I can't duplicate this any more, likely fixed by #69091

**Comment by 81Denton** [comment]
Gonna close this one then
