### ISSUE TITLE
You can't take modules off of mechs

### ISSUE THREAD

**Issue by AlexTheSysop42** [tgstation/tgstation#39137]
Issue reported from  Round ID: 91015 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Reproduction: make mech, add equipment to it, get in the mech and try to remove it with the "equipment" sub menu in view stat

**Comment by SpaceManiac** [comment]
bisect points to 059da4445380b99c5e15299668f40c64014d5c57 @ninjanomnom

**Comment by ninjanomnom** [comment]
Oh yeah I forgot to test things moving outside of other objects, fix should be up momentarily
