### ISSUE TITLE
Footprints are out of control

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#39146]
[Round ID]: 91039

This was 5 minutes into the round, caused by  a single patch of oil just offscreen inside of cargo. The trail extended well down the hallway. 

Footprints were already pretty ridiculous but it feels like something has changed and they're so much worse now. Either way, this can't be right.

![oilpatch](https://user-images.githubusercontent.com/38563876/42729536-85666016-87db-11e8-88f4-d664d7a60226.png)

**Comment by AnturK** [comment]
@ninjanomnom 99% chance caused by Entered changes.

**Comment by AlexTheSysop42** [comment]
If you right click a tile you should also see that there are like 10 different footprint effects

**Comment by ninjanomnom** [comment]
On a bit of a glance I don't see how this could have changed but I did see where this could be componentized. Honestly I'd rather refactor this so it works more sensibly than fix it .

**Comment by Mickyan** [comment]
Dunno if it's related but I've also noticed that sometimes not all footprints appear like they used to. Typically you'd have 4 footprints per tile, now sometimes you only get 2 or 1
![footprints2](https://user-images.githubusercontent.com/38563876/42737907-17737ec2-887b-11e8-9567-ba30312a009b.png)

**Comment by zaracka** [comment]
not sure if related but looks like they're supposed to combine into one 'footprints' per tile but sometimes it bugs out and stacks them instead, causes a lot of lag when it happens

**Comment by nicbn** [comment]
Last time fixed: #32056

**Comment by Mickyan** [comment]
I've seen several people mention that the sheer amount of footprints in certain areas make their game lag out and on a minor note they make playing janitor futile, these might need to be disabled unless a solution can be found soon

**Comment by davethwave** [comment]
Well at least foam grenades are more useful.

**Comment by deathride58** [comment]
Citadel doesn't have this issue. How the fuck did you guys break footprints this time?
