### ISSUE TITLE
Spraying fire extinguishers can move goliath hide boats on solid ground

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#39143]
Round ID: 91026
Server revision compiled on: 2018-07-14
6afa81c207
Revision: 6afa81c207e8e72833d7c27e5232b4ac4273dd90
Server tools version: /tg/station 13 Server v3.2.3.2

Title says it all, it's the same as an office chair. Buckle up on a boat on solid ground and start moving around by spraying a fire extinguisher.

**Comment by AlexTheSysop42** [comment]
It does it on scooters, secways, and any other vehicles too

**Comment by MMMiracles** [comment]
the only change that should be made here is that it should make a loud scratching sound as it scrapes across the floor if it isn't crossing lava/basalt

**Comment by XDTM** [comment]
rename them to hovercrafts when it happens

**Comment by Dorsisdwarf** [comment]
Not sure if this counts as a bug since im pretty sure any movable thing you can be buckled to does this. Rollerbeds do it too if you have a NODROP fire extinguisher somehow.

**Comment by SgtxRootbeer** [comment]
@dorsisdwarf you mean the backpack extinguisher?
