### ISSUE TITLE
Display cases in library can be unlocked with any object

### ISSUE THREAD

**Issue by Kagus** [tgstation/tgstation#39158]
Issue reported from  Round ID: 91055 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: Beta 512.1438

Library display cases can be toggled between "locked" and "unlocked" states by clicking on it with any object, not just the display key. This includes crowbars, screwdrivers, welders (on/off), analyzers, ID cards, strange objects and soap (which also starts cleaning the case at the same time as locking/unlocking it).

Nothing appears to actually open the case, but that's probably more related to a critical user error. This was tested using the roundstart display cases in the library, not on player-made cases.

**Comment by SpaceManiac** [comment]
Cannot reproduce, are you sure you weren't holding the key in your other hand at the time

**Comment by Kagus** [comment]
Quite possibly, just tried opening the cases as a non-curator without the key, and simply got the message to go ask the curator. I don't recall if I'd stowed the key or not on first encountering this.

Even so, it strikes me as slightly odd behavior that having the key in your inactive hand would let you lock/unlock the case with anything _except_ an empty active hand, as that reverts to kicking the display instead. The random items were definitely in my active hand, and the key definitely was not.

If offhand unlocking is actually intended behavior, it might be an idea to maybe add a little more feedback to the messages so other clueless people like me don't go repeating this "bug" report.

**Comment by Kagus** [comment]
Unless someone wants to chime in on the offhand key/anything-but-empty active hand functionality, this can probably be closed. I haven't been able to lock or unlock cases since without holding the display key in one hand or the other.
