### ISSUE TITLE
crashing in game as head revs causes round end

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#39155]
it should wait at least 2 min before round ending when the last headrev/ head of staff crashes (happens at least 2-3 times / round)

**Comment by Cyprex** [comment]
Can the code distinguish between a player who closed their client and a client that crashed?

**Comment by Jalleo** [comment]
@Tlaltecuhtli round ids etc etc

**Comment by AnturK** [comment]
Working as intended, there's no check as in right now.
