### ISSUE TITLE
Paper is highly illegal.

### ISSUE THREAD

**Issue by Bluespace** [tgstation/tgstation#39159]
[Round ID]: #91066

[Testmerges]:
#39132: 'Stops various machines from processing needlessly' by vuonojenmustaturska at commit f1be8a8c4a
#39139: 'Makes damage precision explicit' by AnturK at commit faca150c53
#39135: 'Revert "You can no longer SDQL select certain datums"' by MrStonedOne at commit e289efa87b
#39111: 'Custom names refactor' by AnturK at commit c029b33f05

Round ID: 91066

[Reproduction]: # 
Grab yourself some ordinary paper out the paper bin.
Shove it in the DA.
UNLOCK ILLEGAL TECHNOLOGY BECAUSE PAPER IS THE PRODUCT OF THE SYNDICATE.

![2018-07-15_15-57-40](https://user-images.githubusercontent.com/6324916/42735329-b50fac78-8849-11e8-85c9-6354c77cad88.png)

**Comment by Borisvanmemes** [comment]
I'd make a joke about how this shouldn't count as a bug due to noone liking paperwork but uhhh, this is kinda super broke

**Comment by kevinz000** [comment]
oh no.....

**Comment by kevinz000** [comment]
Okay so really there's two ways to fix it
1. Fix it by making random item not default to paper
2. Fix the node to either require a certain amount of TC and exclude the random item, OR have a blacklist of items, because honestly >illegal tech from syndicate cards and soap
@maintainers

**Comment by Shadowflame909** [comment]
I'd make it a certain amount of TC. Probably 2 tc at most. Or however much a syndicate toolbox costs.

**Comment by Jalleo** [comment]
just switch the thing to be a datum that can never be in it or a effect.

**Comment by nicbn** [comment]
Just remove paper instead

**Comment by Tlaltecuhtli** [comment]
just remove the syndicate
