### ISSUE TITLE
Minor issue with new limb damage and disablers

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#39199]
@XDTM 

Basically, the issue is that when a limb is shot to hell with disablers, it will display as broken and mangled upon examine. This will then go away when the stamina damage heals. Disablers paralyzing specific limbs is presumably intended, however the examine text and also the text presented to the person being shot is rather misleading. Considering that brute/burn damage have different examine text this is probably an oversight. Perhaps it could say the limb is limp and lifeless, or something like that?

**Comment by XDTM** [comment]
Didn't think about that, i'll fix it asap
