### ISSUE TITLE
Disk compartmentalizers are using wrong icon_state

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39206]
Disk compartmentalizers (/obj/machinery/smartfridge/disks) are using the wrong icon_state.

Due to #38793 it's supposed to be "disktoaster" (toaster) instead of "smartfridge" (big fridge). Ingame it's "smartfridge" though.

I don't see any reasons in smartfridge.dm or in map files why they'd be using the fridge sprite.

------------

Issue reported from Round ID: 91194 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 91194

Server revision compiled on: 2018-07-18

The following pull requests are currently test merged:
#39118: '[Ready] Communal Resource Storage II' by SpaceManiac at commit d0eca1a2be
#39136: 'Removes can_vv_get from some things' by Cyberboss at commit 75ea5e3c1b
#39179: 'Convert death query to async' by Cyberboss at commit 8c6c27a290
#39178: 'Move IsBanned query to async' by Cyberboss at commit c69b68f605
#39180: 'MassInsert now defaults to async.' by MrStonedOne at commit defd13a19b

Based off origin/master commit: 79133edae0

Revision: b01d5881597f71faa10828acd2590b317b2e13b2

**Comment by SpaceManiac** [comment]
check `obj/machinery/smartfridge/update_icon`
