### ISSUE TITLE
Turning into a human from a monkey above a tile with a smugglers satchel on it puts the smuggler's satchel on your back.

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#39205]
[Round ID]: # 91193

The smuggler's satchel will be invisible and probably not possible to remove without help (I couldn't figure out how, certainly). When removed it will teleport below the tile you're standing on.

**Comment by Tlaltecuhtli** [comment]
there is some proc called that equips you with whatever is near you when demonkeyd probably that caused it
