### ISSUE TITLE
Modify Armor Values VV runtime.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#39225]
[03:07:35] Runtime in , line : bad arg name 'Type'
proc name: presentpicker (/proc/presentpicker)
usr: Unknown (wjohnston) (/mob/living/carbon/human)
usr.loc: The floor (165,51,1) (/turf/open/floor/plasteel/neutral/side)
src: null
call stack:
presentpicker(Unknown (/mob/living/carbon/human), "Modify armor", "Modify armor: the space helmet", "Save", "Cancel", null, null, 0, null, null, null, null, null)
WJohnston (/client): view var Topic("_src_=vars;admin_token=0418932...", /list (/list), null)
WJohnston (/client): Topic("_src_=vars;admin_token=0418932...", /list (/list), null)
WJohnston (/client): Topic("_src_=vars;admin_token=0418932...", /list (/list))

**Comment by yoyobatty** [comment]
It might be something to with having to modify the list rather than using the built in setarmorvalue proc (or whatever it's name is).
