### ISSUE TITLE
Proximity sensors in backpacks have bizzare and inconsistent properties.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#39224]
![](https://i.imgur.com/ZIH2eBK.png)

This 0 range prox sensor was placed in a backpack, where it beeped upon being put in. The backpack was then dragged around off a ways. Walking on the tile it originally beeped will still cause it to activate.

This is all highly inconsistent, though, and it's hard to reproduce reliably.

EDIT: One of the biggest things that stumped me is actually the range at which you can hear the prox sensor. Turns out it is silent after being more than 3 tiles away from it. I tested it by attaching a signaler to it and listening for another in my hand, and was able to get this to work from across the entire map.

**Comment by ShizCalev** [comment]
@AnturK

**Comment by dragomagol** [comment]
Unable to reproduce
