### ISSUE TITLE
Player panel heal doesn't fix liver damage or liver failure

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39237]
Revision: 57c995d141d09d5e7016fd911a3bdd3e897cf090

- Metabolize enough toxins to cause liver damage/failure.
- Open player panel, hit "heal".
- Liver damage is not healed; you can check this by VV examining the liver's damage var.

**Comment by XDTM** [comment]
Adminheals apply a trauma heal on par with TRAUMA_RESILIENCE_MAGIC, to avoid issues with in-game adminheals (why do they exist) screwing up stuff like temporary traumas like bath salts, which should be cured when the sources leave (in this case when bath salts are removed by the admin heal).

That said, it should only affect bath salts as of now.

**Comment by Arianya** [comment]
@81Denton Fair enough, I don't see brain traumas very often.
