### ISSUE TITLE
Insulated gloves aren't hiding your fingerprints.

### ISSUE THREAD

**Issue by fen0s** [tgstation/tgstation#39233]
[Note]: Round ID - 91250
Server revision 201aaf657e48ae75fb074805c8b0048e7807a180
Steps to recreate the bug -

Touch something in insulated gloves
Try to scan it, and you'll still find fingerprints.

I was been traitor in this round. I've installed a powersink in maint, but cap still SOMEHOW found my fingerprints on it. In reality, this would work this way - I had a hardsuit on, and insulated gloves on. I shouldn't leave both fibers and prints. BUT, somehow, caps just finds my fingerprints and I'm getting busted because of that. This is clearly a bug and isn't way it should be.

**Comment by ExcessiveUseOfCobblestone** [comment]
Need repro

**Comment by fen0s** [comment]
I've said alerady, touch something in insulated gloves and scan it with forensics scanner. There's reproducing.

**Comment by 81Denton** [comment]
@fen0s I just tested it on localhost with a hardsuit and insulateds. Bought a powersink, screwed it to a wire and activated it; the scanner gave me neither prints nor fibers on the powersink itself.
On nearby airlocks, only ever this:
```
Fibers:
Material from an advanced hardsuit.
```

**Comment by ExcessiveUseOfCobblestone** [comment]
@fen0s sorry for not being clear, I needed someone to confirm this happens rather than the steps to make it happen (I didn't find anything in the code that would cause it).

I'm assuming the captain was bluffing and tricked you into a confession.

**Comment by Mickyan** [comment]
I went log diving and you got caught because they found engi hardsuit fibers on it and there was only one hardsuit missing from storage - the one you were wearing. After that you got searched and they found your uplink.

Sorry man looks like you just got outsmarted

**Comment by ExcessiveUseOfCobblestone** [comment]
@SpaceManiac you can close this
