### ISSUE TITLE
Captain's Command Door Remote doesn't interact with Vault Airlock

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#39249]
Issue reported from  Round ID: 91308 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

As the title says, the captain's command remote can't unbolt/open/emergency access the vault airlock. Seems to work normally on other command doors like the captain's quarters and bridge.

**Comment by SpaceManiac** [comment]
It would be possible, yes.

**Comment by Hathkar** [comment]
Hmm, I could try and make a PR with a change then?
