### ISSUE TITLE
portal guns crash the server

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#39259]
if you manage to get the projectile to loop trough portals, yep thats an infinite loop
round id 91334

**Comment by 81Denton** [comment]
They can also lag the hell out of everyone even with non server crashing loops and destroy airlocks wew

**Comment by 81Denton** [comment]
Round ID: Bagil 91334

**Comment by Iamgoofball** [comment]
its almost like hitscan was a bad idea or something
