### ISSUE TITLE
Lighting bug has re-emerged

### ISSUE THREAD

**Issue by octareenroon91** [tgstation/tgstation#39279]
Round ID: 91372
Server revision compiled on: 2018-07-20
The following pull requests are currently test merged:
#39136: 'Removes can_vv_get from some things' by Cyberboss at commit 75ea5e3c1b
#37922: '[WIP] [Testmerge-Ready] Nanites 2' by XDTM at commit ee647338a6
#38944: 'Third time's the charm - Photography update: 7x7 cameras, photo logging with full metadata, persistent albums and wall frames!' by kevinz000 at commit 0b3ea71828

Based off origin/master commit: 672186b5f5
Revision: b0e6056d23a0c41ccdfc1e2f2f8ced68eae784c9
Server tools version: /tg/station 13 Server v3.2.2.0

-----

I've reinstalled the DirectX SDK and updated BYOND to the latest version, and still.

![43043534-4bca9842-8d5b-11e8-89bd-7c62021b6fb5](https://user-images.githubusercontent.com/12420976/43043643-a4d326b4-8d5d-11e8-9936-69b8baa2e6d6.png)
![43043609-0604f81e-8d5d-11e8-86d0-af0b67a9b8e8](https://user-images.githubusercontent.com/12420976/43043644-a4f4271a-8d5d-11e8-8728-4647db3b4541.png)

**Comment by optimumtact** [comment]
Your directx shaders are not working correctly, byond issue, and unfortunately there's not much we can do to help.

**Comment by nicbn** [comment]
Are you using Wine or Windows (which version)?

**Comment by octareenroon91** [comment]
Wine. Turned out I'd flipped some option the wrong way.

Now my TGUI support is totally fucked though.

**Comment by optimumtact** [comment]
our UI support in wine is pretty fucked because it only exposes like ie9 compatibility

try the no frills mode in the preferences and pray @MrStonedOne finishes his ui replacement

**Comment by octareenroon91** [comment]
Super duper fun: the version still on linuxtest works.

**Comment by timothymtorres** [comment]
It sounds like this is a clientside hardware issue.  Marking this as `Cleanup` and will auto-close it in 7 days.
