### ISSUE TITLE
c20r firemode gets stuck on semi-auto once you change it.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#39285]
What it says on the tin. Spawn c20r, toggle firemode to green (semi-auto), toggle it back to burst, see that it's still green (firing will only shoot one round).

**Comment by subject217** [comment]
I can't reproduce the firemode not functioning, it appears to work just fine. Also, as far as I can tell from the icon states, there is no actual icon difference between the C-20r being set to semi or burst.

**Comment by WJohn** [comment]
Huh, could have sworn it only fired a single time. But the color always being green after you change it is definitely something I'm getting. The burst mode is supposed to be yellow, and that's what it starts as by default. Once you touch it, it'll be stuck green.

**Comment by kriskog** [comment]
Can't reproduce, and icon also updates.
