### ISSUE TITLE
Dead pirates are totally white and skin colorless.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#39288]
What it says on the tin. Dead syndicates and russians do not suffer from this, and pick a skin color. Pirates are always colorless and pure white.

**Comment by Tlaltecuhtli** [comment]
they are SKELETONS

**Comment by ShizCalev** [comment]
Duplicate of #34856

**Comment by WJohn** [comment]
whoops duplicate of my own issue lol
