### ISSUE TITLE
Three grab clicks is logged as strangle attempt instead of neck grab attempt

### ISSUE THREAD

**Issue by zaracka** [tgstation/tgstation#39289]
it's being logged incorrectly

**Comment by Tlaltecuhtli** [comment]
https://github.com/tgstation/tgstation/blob/b9c5bad6055496cc38dba541902b55ae1c50234d/code/modules/mob/living/living_defense.dm#L164


seems fine here

**Comment by zaracka** [comment]
https://github.com/tgstation/tgstation/blob/b9c5bad6055496cc38dba541902b55ae1c50234d/code/modules/mob/living/living_defense.dm#L157

attempt
