### ISSUE TITLE
Mech exofabs start with non researched parts available

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39293]
Roundstart exofabs (/obj/machinery/mecha_part_fabricator) are able to print the following roundstart, even when not researched in techwebs:
- All mech parts (no circuit boards ofc)
- Exosuit Equipment: All HONK mech weapons, Ripley/Firefighter drill, hydraulic clamp, mining scanner, extinguisher, cable layer
- Cyborg Upgrade Modules: Borg rename/emergency reset/clown module boards
- Misc: Power cell/MMI/flash/exosuit tracking beacon

If this gets fixed, it will dick Roboticists over pretty hard by roundstart. 
I'll then open a PR so that the parts that actually make sense are available roundstart - like borgs/MMIs/flashes/tracking beacons and ripley parts.

**Comment by GunHog** [comment]
I asked @kevinz000 to do this so Robotics players do not have to sit around tossing together medibots or break into R&D just to be able to do their jobs. It is neither a bug nor an oversight.

**Comment by 81Denton** [comment]
@GunHog Since that's intended, it's IMO better if those items are included as a roundstart techweb node instead of magically existing.
