### ISSUE TITLE
You get put to the lobby if you die, disconect and are not ghosted when sacrificed

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#39297]
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm
Round ID: 91401
Server revision compiled on: 2018-07-21

The following pull requests are currently test merged:
#39118: '[Ready] Communal Resource Storage II' by SpaceManiac at commit 54c0930f2d
#39136: 'Removes can_vv_get from some things' by Cyberboss at commit 75ea5e3c1b
#39220: 'Makes having high body temperature more deadly in general' by vuonojenmustaturska at commit 98cfe0e111
#39261: 'Fixes the pickup animation.' by Iamgoofball at commit 4a84f983c6
Based off origin/master commit: 166e1afd44
Revision: 4061cb3215cb25f431a1b4b811a19437561c3f76
Server tools version: /tg/station 13 Server v3.2.2.0

[Reproduction]: # Die and dc before your body is sacrificed, without ghosting.

Priority critical. Holy fuck.

**Comment by Tlaltecuhtli** [comment]
#38898

**Comment by optimumtact** [comment]
dupe/instance of #38898
