### ISSUE TITLE
Revolver bounty accepts double barrel shotguns and grenade launchers

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39295]
`wanted_types = list(/obj/item/gun/ballistic/revolver)`

This means that revolver/doublebarrel and revolver/grenadelauncher will also be accepted.

The others should probably be left in; the idea of shipping out a russian revolver as a duel weapon is pretty funny.

**Comment by octareenroon91** [comment]
https://github.com/tgstation/tgstation/blob/master/code/modules/cargo/bounties/item.dm#L6

**Comment by Supermichael777** [comment]
I bring my over under and they whined "You can't use a shotgun" and "Buckshot removes all the ARRRG MY LEG"
