### ISSUE TITLE
sleep immunity doesnt work right

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#39305]
if you get the trait and take sleep chems you will sleep and wake up every chem tick

**Comment by Kagus** [comment]
Which sleep chems, specifically? Modafinil overrides sleep immunity, but I suppose it might be possible to stack enough sleep reduction from various sources in order to keep waking up while under its effects.

And what was the source of the sleep immunity?

**Comment by Tlaltecuhtli** [comment]
coffe latte

**Comment by Kagus** [comment]
Coffee latte does not provide the TRAIT_SLEEPIMMUNE trait like bath salts or modafinil, it instead has on_mob_life M.SetSleeping(0, FALSE). So it will remove any current stacks of sleep, but it will not prevent you from getting new ones.

This appears to be working as intended, although the way it's intended might be a little stupid in practice. Repeatedly falling asleep and immediately waking up when injected with a sleeping chem doesn't sound like something that was entirely thought out.

**Comment by ExcessiveUseOfCobblestone** [comment]
It was before sleepimmune was added, which is what it should have now if it's not meant to subtract sleeping.

**Comment by XDTM** [comment]
I am wondering why cafe/soy latte is much stronger than regular coffee, which just reduces the sleeping time.

**Comment by Kagus** [comment]
It's either because milk is Super Space Mammary Magic and fixes everything, or because hipsters never sleep and only drink coffee if it's in the form of a cappuccino au latte.

**Comment by Supermichael777** [comment]
Working as intended, though sleep really should be a stack instead of a timer

**Comment by kriskog** [comment]
Caffe latte will prevent morphine sleep now at least, this was probably fixed.
