### ISSUE TITLE
Mech construction doesn't check for stock part tier

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39313]
Gygax/Durand/Phazon mechs require T2/T3/T3 stock parts for completion according to their entries in mecha_construction_paths.dm - actual construction doesn't check for the stock part tier though, meaning that you can build a Phazon with T1 stock parts.

**Comment by Tlaltecuhtli** [comment]
seems fine tho if you want to have the shittiest mech to give to sec then go for it

**Comment by 81Denton** [comment]
Nvm I didn't realize that stock parts lower energy drain and increase EMP protection
