### ISSUE TITLE
Megafauna - Legion

### ISSUE THREAD

**Issue by Chipped-Ice** [tgstation/tgstation#39321]
Issue reported from  Round ID: 91461 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Legion is 100% unable to be killed after the first split unless thrown into the supermatter, admins tested this by throwing immovable rods at it. I noticed this after a good 10 minutes of slugging him and then getting medihuds and repeating.

**Comment by SpaceManiac** [comment]
oranges indicates it is related to health rounding
```
<oranges> there's a legion on sybil with 
<oranges> E) (C) (M) healable = 1 
<oranges> (E) (C) (M) health = 3.05176e-005 
<oranges> (E) (C) (M) maxHealth = 480
```

**Comment by Repukan** [comment]
Raid boss

**Comment by CoolCatIsFeelingGroovy** [comment]
I also had this, seems to only happen on sybil from what I've seen
