### ISSUE TITLE
Throwing someone will only send them 1 tile, and permanently break grabbing them after.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#39328]
If you aggressive (or neck grab) someone and throw them, they will only be sent 1 tile, after which attempting to grab them will not work at all anymore. You cannot ctrl click drag them anymore, or right click -> pull.

Probably pretty high priority!

**Comment by ExcessiveUseOfCobblestone** [comment]
I just threw people yesterday on aggressive and did not have this issue (like ~10pm EST)

**Comment by WJohn** [comment]
Huh. Suddenly cannot reproduce this. Was this a one time occurrence? What happened? Will re-open when I find out.

**Comment by Cyprex** [comment]
Affixing a round id would have helped here.
