### ISSUE TITLE
Cult Delay distorts shuttle recall timer severely

### ISSUE THREAD

**Issue by Arianya** [tgstation/tgstation#39331]
**[Round ID]:** 91474

**[Reproduction]:**
* Force cult mode
* Set red alert
* Call shuttle (with 5 minute ETA)
* Use cult delay to force ETA timer above 5 minutes
* Recall shuttle

**[Expected Outcome]:** Shuttle is instantly recalled and has no cooldown/time to call again

**[Actual Outcome]:** Shuttle is recalled and has a full 10 minute recall time in spite of both red alert and ETA to station

**[Notes]**: This looks like two seperate bugs, one which is making the game consider the shuttle's recall time to be blue alert levels even on red-alert, and another which is making the shuttle recall timer max out regardless of time elapsed/remaining.

**Comment by ExcessiveUseOfCobblestone** [comment]
Is this exclusive to the mechanic or does recalling in red always give you the 10 minutes?

**Comment by Tlaltecuhtli** [comment]
if you go green and then recall you get 20 min of recall time

**Comment by Arianya** [comment]
@Ratvar if the ETA timer is pushed to 5 minutes 5 seconds by a delay it will take 10 minutes to recall.

The recall timer is meant to be the elapsed time since the shuttle was called, i.e. on a 5 minute timer if the shuttle is recalled after 2 minutes it should take two minutes to recall.

**Comment by SgtxRootbeer** [comment]
To whoever fixes this, the recall shouldn't be instant because the cult did sacrifice their stealth and resources to get this delay, and thematically, "a shuttle worker erupts into laughter and destroys an engine" or something still happened.

 so it makes sense that the issue requires time to sort out before another call can be sent

**Comment by JohnFulpWillard** [comment]
I'm marking this as intentional. You shouldn't be able to completely bypass cult's shuttle delays.
