### ISSUE TITLE
Spritesheet css contains hundreds of duplicate entries

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation#39349]
Reproduction

join game, look in C:\Users\yourname\Documents\BYOND\cache\tmpblah

marvel at the 22.6mb css file for the design icons spritesheet
![](https://file.house/zJLr.png)

enjoy it's 377,000 lines of css declarations

marvel at 613 repeated hits for the quadultra_micro_laser
![](https://file.house/WLhg.png)

**Comment by optimumtact** [comment]
@SpaceManiac

**Comment by optimumtact** [comment]
@tgstation/commit-access this is why the roundstart is so laggy for people with crappy network connections btw

**Comment by optimumtact** [comment]
side note, it would help if we combined all css files into one

**Comment by JohnGinnane** [comment]
Thank you very much for finding this!

**Comment by optimumtact** [comment]
Quick update, people are reporting different sized sheets, some larger, some smaller, is this somehow a byond delivery issue where it's appending the file together?

**Comment by Carbonhell** [comment]
spritesheet_design.css: 18,4 MB
spritesheet_pipes.css: 10,9 MB
spritesheet_chat.css: 3,62 MB
spritesheet_pda.css : 693 KB

**Comment by Jordie0608** [comment]
Not connected for a few days, each spritesheet_x.css file for me was under 2MB, cleared cache and connected to bagil; files now same bloated size.
spritesheet_chat.css: 4.66MB
spritesheet_design.css: 22.6MB
spritesheet_paper.css: 448KB
spritesheet_pda.css: 892KB
spritesheet_paper.css: 14.0MB

**Comment by JohnGinnane** [comment]
![image](https://user-images.githubusercontent.com/3355198/43193577-4bb064f0-8ff8-11e8-9873-232402aaa26c.png)

**Comment by optimumtact** [comment]
temp workaround in https://github.com/tgstation/tgstation/pull/39352

**Comment by Cyprex** [comment]
Yes, BYOND seems to append the files together, see in particular spritesheet_paper.css and the accompanying frequency file listing line frequencys. The extra seemingly identical lines in the frequencys files have Unix-style line endings for some reason, while the rest has windows-style.
https://v.teknik.io/v/KepPy

**Comment by optimumtact** [comment]
#39352 resolved
