### ISSUE TITLE
You can use slime management consoles even when they're unpowered

### ISSUE THREAD

**Issue by TribeOfBeavers** [tgstation/tgstation#39348]
Issue reported from  Round ID: 91519 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Pretty much what it says in the title. Console was visibly depowered, and the APC said equipment was offline, but I was still able to use the consoles. 

Station was Pubby, if that's relevant.

**Comment by 81Denton** [comment]
Can confirm this on Meta+Pubby with revision bdbf855c80676926a0e2207d756234d1d8d6fba6
