### ISSUE TITLE
AI upload motion alarm is lacking

### ISSUE THREAD

**Issue by Charmisokay** [tgstation/tgstation#39346]
Issue reported from  Round ID: 91516 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])
Reporting client version: 512

This is the most recent round where I've had this issue. I'm the AI, and random people get into the AI upload without raising a motion sensor alert. After the incident I check out the AI upload area and see them in there. The first time I noticed it was during the 'clown is god' round. The mime uploaded the 'clown is god' law without alerting my sensors. (I scrolled over to the AI upload manually after my laws got changed) 
And later during the same round somebody else had intruded into the AI upload area and was reported by random people walking past. 

This round it was a random non antag engineer who was fixing my laws. He was in there with a cyborg. Again I manually scrolled over to the upload area after my laws were changed. (Reset). 

In all three cases I've checked my text log afterwards to see if I just missed the alert in all the chaos, but it seems like the alert never popped up. 

The motion sensors on the AI minisat and in the armory (and outside the armory) still work just fine. I'm really at a loss here.

**Comment by ExcessiveUseOfCobblestone** [comment]
And map

**Comment by YPOQ** [comment]
area/Entered and area/Exited aren't being called from Move() (they are from forceMove/doMove though)
Cameras outside ai_monitored areas or created after mapload rely on proximity_monitors instead, which is why they are still working.
