### ISSUE TITLE
Clockwork Floors Allow You to Infinitely Produce Brass Sheets

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#39359]
The clockwork floors found around the ratvar corpse ruin allow you to produce infinite amounts of brass (the clock cult variation of it) by using a crowbar on it. After a short delay it says you pry the floor up and produces a brass sheet, but doesn't actually remove the clockwork floor allowing you to pry it up again. The only real problem with this is that you can make clockwork golems out of the sheets either as free golems or servant golems.

Issue reported from  Round ID: 91528 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Apologies if this isn't formatted correctly, first bug report.

**Comment by Kagus** [comment]
You can also grind brass sheets to get 15u of Teslium, which can be used for FUN purposes.

**Comment by 81Denton** [comment]
My best bet is that it's happening because it's actual `/turf/open/floor/clockwork` straight out of Reebe that has itself as a baseturf

**Comment by 81Denton** [comment]
That turf also has a bunch of code attached to it instead of just being cosmetic and giving you brass tiles.

**Comment by Kagus** [comment]
Ratvar's Revenge
