### ISSUE TITLE
Improve logging of reagents splashing onto stuff

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#39356]
![log](https://i.imgur.com/jAcZMh8.png)

ADMIN LOG: Aldroyd/(Mute)(?) (FLW) splashed (thrown) Thermite on the reinforced wall in Captain's Office (127, 125, 2) (JMP).

it would be nice if it displayed how much of the reagent was thrown

also yes this is technically a feature request

**Comment by dragomagol** [comment]
Appears to have been fixed
