### ISSUE TITLE
instrument music cant be heard

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#39358]
they dont produce any noise
91526 bagil

**Comment by XDTM** [comment]
Do you have the instrument pref enabled?

**Comment by octareenroon91** [comment]
are you using WINE? do you have any MIDI stuff working on your computer/instance?

**Comment by JStheguy** [comment]
Yeah, I can confirm, instruments are capital F Fucked on newer versions of byond.  They worked perfectly fine for me right up until I updated to the latest version. Doesn't matter whether instruments pref is on or off, just nothing but silence.
Oddly, you still get the "soothing music" moodlet  from trying to play a tuned instrument even though no sound is made. So at the very least it doesn't seem like the entire instrument system is bricked.

**Comment by kriskog** [comment]
Seems to have been a byond issue? Not reported recently.
