### ISSUE TITLE
Abductors don't have say logs

### ISSUE THREAD

**Issue by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [tgstation/tgstation#39365]
title

**Comment by AnturK** [comment]
They do ? Even bit too much.
https://tgstation13.org/parsed-logs/basil/data/logs/2018/07/26/round-91561/game.txt

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Sorry, should have been more specific. They don't have say logs in-game, like when you varedit someone and check the say log

**Comment by SuperNovaa41** [comment]
No longer an issue
