### ISSUE TITLE
Round end on nuke op detonation is very delayed.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#39360]
It takes upwards of 20 seconds for the actual round end report to happen AFTER the cinematic has played, during which time people will be unnecessarily toxic about perfectly fine post-round OOC talk happening before it actually *says* the round has ended. (Even though everyone is frozen after the cutscene has played until the round end report and can't possibly abuse IC in OOC info.)

All this serves to do is make people really hostile to eachother for absolutely no reason, and it happens every single time.

**Comment by AnturK** [comment]
This is usually to these silly 200,200,200 explosions happening then.

**Comment by WJohn** [comment]
Why on earth do we have those? We have a literal cinematic that we could stretch on until the game restarts.

**Comment by lolman360** [comment]
it's actually a 0,256,512,0.

**Comment by WJohn** [comment]
If MSO really insists on having this fuckhuge explosion hold up the server (and as a result the round end report), why not make the round end report 2 seconds BEFORE the cinematic/explosion calculations start?

**Comment by EuclidianGeometer** [comment]
i believe this issue has been resolved at some point.

**Comment by EuclidianGeometer** [comment]
https://github.com/tgstation/tgstation/pull/51647 yes, fixed by this pull

**Comment by Sealed101** [comment]
^
