### ISSUE TITLE
Hardsuit fire immunity consistency

### ISSUE THREAD

**Issue by Kagus** [tgstation/tgstation#39368]
Not a bug, just a minor coding inconsistency. Therefore extremely high priority.

The elite syndie hardsuit and helmet both use `max_heat_protection_temperature = FIRE_IMMUNITY_SUIT_MAX_TEMP_PROTECT`, whereas almost every other clothing example of fire immunity uses `FIRE_IMMUNITY_SUIT_MAX_TEMP_PROTECT `for the body and `FIRE_IMMUNITY_HELM_MAX_TEMP_PROTECT `for the headpiece. The only exception I can find offhand is the Ratvarian clockwork helmet, which also uses SUIT.

Near as I can tell, this has no real effect on the game whatsoever, since both SUIT and HELM are just defined as 35000. Unless there's some secret check happening that I'm not aware of (entirely possible, likely even), I don't really understand why they're split up into two separate defines with the exact same values.

Only possible weirdness resulting from this that I could find was the slime fireproofing potion checking to see if a garment's protection value is `== FIRE_IMMUNITY_SUIT_MAX_TEMP_PROTECT`, so all depending on how that's parsed it might let you fireproof the atmos hard hat or other already-fireproof headpieces.

But I'm not a coder, so I wouldn't know.

**Comment by octareenroon91** [comment]
`FIRE_IMMUNITY_HELM_MAX_TEMP_PROTECT` and `FIRE_IMMUNITY_SUIT_MAX_TEMP_PROTECT` are set by `#define`, so when it compiles, 35000 gets put in all those spots. They're indistinguishable.

**Comment by AnturK** [comment]
Since defines are same there's no effect but should be fixed in case they get changed.

**Comment by octareenroon91** [comment]
````
$ git grep -l --full-name -E "FIRE_IMMUNITY_(SUIT|HELM)_MAX_TEMP_PROTECT"
code/__DEFINES/atmospherics.dm
code/datums/weather/weather_types/ash_storm.dm
code/modules/antagonists/clockcult/clock_items/clockwork_armor.dm
code/modules/clothing/head/hardhat.dm
code/modules/clothing/spacesuits/hardsuit.dm
code/modules/clothing/spacesuits/miscellaneous.dm
code/modules/clothing/suits/cloaks.dm
code/modules/clothing/suits/utility.dm
code/modules/mining/equipment/explorer_gear.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/research/xenobiology/crossbreeding/regenerative.dm
code/modules/research/xenobiology/xenobiology.dm
````
