### ISSUE TITLE
Snowdin away mission loading runtimes

### ISSUE THREAD

**Issue by niceping** [tgstation/tgstation#39378]
Reproduction: Load Snowdin that is not VR

`[20:02:56] Runtime in pump.dm,44: Cannot read null.airs
  proc name: process atmos (/obj/machinery/portable_atmospherics/pump/process_atmos)
  src: the portable air pump (/obj/machinery/portable_atmospherics/pump)
  src.loc: the floor (59,215,13) (/turf/open/floor/plasteel)
  call stack:
  the portable air pump (/obj/machinery/portable_atmospherics/pump): process atmos(0.5)
  Atmospherics (/datum/controller/subsystem/air): process atmos machinery(0)
  Atmospherics (/datum/controller/subsystem/air): fire(0)
  Atmospherics (/datum/controller/subsystem/air): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[20:02:56] Runtime in mixer.dm,152: Cannot modify null.update.
  proc name: process atmos (/obj/machinery/atmospherics/components/trinary/mixer/process_atmos)
  src: the air mixer (/obj/machinery/atmospherics/components/trinary/mixer/airmix/flipped)
  src.loc: the floor (58,214,13) (/turf/open/floor/plasteel)
  call stack:
  the air mixer (/obj/machinery/atmospherics/components/trinary/mixer/airmix/flipped): process atmos(0.5)
  Atmospherics (/datum/controller/subsystem/air): process atmos machinery(1)
  Atmospherics (/datum/controller/subsystem/air): fire(1)
  Atmospherics (/datum/controller/subsystem/air): ignite(1)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[20:02:57] Runtime in pump.dm,44: Cannot read null.airs
  proc name: process atmos (/obj/machinery/portable_atmospherics/pump/process_atmos)
  src: the portable air pump (/obj/machinery/portable_atmospherics/pump)
  src.loc: the floor (59,215,13) (/turf/open/floor/plasteel)
  call stack:
  the portable air pump (/obj/machinery/portable_atmospherics/pump): process atmos(0.5)
  Atmospherics (/datum/controller/subsystem/air): process atmos machinery(1)
  Atmospherics (/datum/controller/subsystem/air): fire(1)
  Atmospherics (/datum/controller/subsystem/air): ignite(1)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
[20:02:57] Runtime in mixer.dm,152: Cannot modify null.update.
  proc name: process atmos (/obj/machinery/atmospherics/components/trinary/mixer/process_atmos)
[20:02:57] Runtime in pump.dm,44: Cannot read null.airs
  proc name: process atmos (/obj/machinery/portable_atmospherics/pump/process_atmos)
[20:02:57] Runtime in mixer.dm,152: Cannot modify null.update.
  proc name: process atmos (/obj/machinery/atmospherics/components/trinary/mixer/process_atmos)
[20:02:58] Runtime in pump.dm,44: Cannot read null.airs
  proc name: process atmos (/obj/machinery/portable_atmospherics/pump/process_atmos)
[20:02:58] Runtime in mixer.dm,152: Cannot modify null.update.
  proc name: process atmos (/obj/machinery/atmospherics/components/trinary/mixer/process_atmos)
[20:02:59] Runtime in pump.dm,44: Cannot read null.airs
  proc name: process atmos `

**Comment by kingoftheautism** [comment]
`[20:04:48] Runtime in gas_mixture.dm,384: Cannot read null.gases
MC: SoftReset called, resetting MC queue state.
MC: SoftReset() failed, crashing
## DEBUG: Thu Jul 26 20:04:48 2018 MC restarted. Reports:
	 datum_flags = 0
	 datum_components = 
	 comp_lookup = 
	 processing = 0
	 map_loading = 0
	 random_seed = 8.33313e+008
	 iteration = 3170
	 last_run = 2445.5
	 subsystems = /list
	 init_timeofday = 396593
	 init_time = 488
	 tickdrift = 672.668
	 sleep_delta = 1.45695
	 make_runtime = 0
	 initializations_finished_with_no_players_logged_in = 1
	 last_type_processed = Machines(/datum/controller/subsystem/machines)
	 queue_head = Mobs(/datum/controller/subsystem/mobs)
	 queue_tail = Machines(/datum/controller/subsystem/machines)
	 queue_priority_count = 150
	 queue_priority_count_bg = 0
	 current_runlevel = 3
	 sleep_offline_after_initializations = 1
	 restart_clear = 2547
	 restart_timeout = 2497
	 restart_count = 1
	 current_ticklimit = 40
	 gc_destroyed = 
	 active_timers = 
	 weak_reference = 
`

**Comment by SpaceManiac** [comment]
Is this roundstart or using the Load Away Mission verb?

**Comment by kingoftheautism** [comment]
Using verb

**Comment by SpaceManiac** [comment]
Try loading roundstart, if *that* doesn't work there's a big problem.

The Load Away Mission verb not working is known (to me at least), it should be fixed but it's usually used for testing rather than on live so it hasn't gotten the attention it deserves.

**Comment by kingoftheautism** [comment]
So, how i'm should do this? I know it was somewhere in configs, but it's probably easier to ask that try to figure out by myself

**Comment by kingoftheautism** [comment]
![bandicam 2018-07-28 08-27-45-699](https://user-images.githubusercontent.com/40269243/43350182-3d1e02f4-9240-11e8-84d9-bd96ddc7145c.jpg)
![bandicam 2018-07-28 08-27-55-327](https://user-images.githubusercontent.com/40269243/43350183-3d9ba452-9240-11e8-9243-2b3a124650be.jpg)
![bandicam 2018-07-28 08-28-11-096](https://user-images.githubusercontent.com/40269243/43350184-3e086880-9240-11e8-90b6-1c6fed392512.jpg)
Okay, so i guess this issue can be with Snowdin itself, not Load-Away verb
(i'm turned on away missions roundstard loading in configs also edited another config so it would load only snowdin)

**Comment by kingoftheautism** [comment]
I think somebody should check that, maybe there is some spaghetti-code involved, that is basically making Snowdin unplayable or Away Mission Load verb unusable

**Comment by kingoftheautism** [comment]
@SpaceManiac Do you have any idea what can cause this issue?

**Comment by Dennok** [comment]
Maybe some bad turfs or something etc?

**Comment by kingoftheautism** [comment]
I don't know, i tried to load roundstart VR Snowdin but it didn't worked, errors and shit. Same with Load Away verb. I don't know, maybe this is Snowdin-only-turfs error, or BYOND issue, but seems like VR Snowdin is working fine, same with Snowdin Away Mission on one /tg/ based server.

It's hurting my brain
