### ISSUE TITLE
Cult pre_setup causes several fails on lowpop

### ISSUE THREAD

**Issue by Carbonhell** [tgstation/tgstation#39381]
https://github.com/tgstation/tgstation/blob/master/code/game/gamemodes/cult/cult.dm#L60
Not sure if this can be considered a bug, but cult pre_setup is very prone to fail especially during lowpop. At hippie, we have cult minpop to 10, and there are cases where roundstart fails up to 4 times. The issue seems to be from the CULT_SCALING_COEFFICIENT being set to 9.3, not taking the config MIN POP value into account at all. Thus, with said min pop,only 2 cultists are selected, but required enemies is 4, and it fails. Over and over. Either scrap the coefficient completely, or make the required enemies value scale based on the config min pop value, dunno.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/bcc58d3ab97a67b7b0efb4e9db9b316550527b51/code/game/gamemodes/cult/cult.dm#L40
https://github.com/tgstation/tgstation/blob/fab4ac81b0c431df12e4936b2a8e164090e344f6/code/game/gamemodes/clock_cult/clock_cult.dm#L129

**Comment by Sealed101** [comment]
dynamic has changed a lot, notably lowering the minimum players required to uhh 4? as well as the entire initialization process for the ruleset. in any event, low-pop players would have probably reported any such failures if they were to consistently occur.

https://github.com/tgstation/tgstation/blob/dcc1f9754305ce108f5b83be28ebde512c07f427/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm#L325-L348
