### ISSUE TITLE
You can meta nukies with a blood contract

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#39384]
Issue reported from  Round ID: 91589 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

You can see nukies in their base with the blood contract selection menu. Probably best to limit selection to same Z

**Comment by Tlaltecuhtli** [comment]
you can meta event sentient viruses, just make it pull from a filtered list instead of all people

**Comment by Jord1081** [comment]
Yeah, I got fucked once as an abductor almost immediately, a miner rushing Bubblegum can really easily mess with certain antags.

**Comment by HydroFloric** [comment]
Same with wizards but to a lesser extent since they most likely are already murderboning by the time bubbles it dead but you can still select them.

**Comment by trollbreeder** [comment]
The thing is, how can you kill bubblegum that fast?
