### ISSUE TITLE
Pirate cutter not updating properly when relocating to a rotated position.

### ISSUE THREAD

**Issue by Kagus** [tgstation/tgstation#39405]
Server: Terry
Round ID: 91591
Server Revision: `5afaad1`

When moving between deep space and a rotated position on the station Z-level and back, information about gas in the cutter's incinerator chamber seemed to not be carried over properly.

I unfortunately do not recall the exact sequence of events (not realizing it was relevant at the time), but will try to recreate what happened as best as I can.

I'd attempted to start a burn in the incinerator, and then repositioned to just outside the station in order to plan my attack. I apparently ran out of oxygen and plasma to fuel the burn during this time, and had to reroute nitrogen into the chamber so I could squeeze a few extra cycles out of the turbine.

The strangeness started when the station's chief engineer found my ship and started taking it apart, including fully dismantling the turbine generator. I managed to chase them off, but was left with an empty chamber and a hull breach leaking out into space. I clearly remember fighting against space wind pulling the wall girder the CE had detached out into space, and my having to wait for the chamber (and the ship behind it, which was also now breached) to vent enough that I could wrench the girder down.

I then relocated to deep space (causing the ship to rotate back to its default N/S alignment) to fully assess the damage and get away from the CE. Upon doing this, a fire ignited in the burn chamber (which now had the turbine vent blast doors closed, whereas they'd been open/dismantled on the station Z-level), and there was enough gas pressure to blow me back into the ship. Checking a gas analyzer, I saw that the air was now over 90% oxygen, which couldn't have been the case on the station Z-level since my O2 reserves were already long-since used up and I'd then emptied the N2 tank into the chamber to increase pressure.

Reproduction: Get the pirate cutter, and inject a gas mix into the burn chamber. Close off the chamber input pump or empty the tanks to stop it getting refilled, then relocate to a rotated position on the station Z-level. Also dismantle/toggle the vent blast doors to check if they're updating.

---
It's entirely possible that there were other factors involved here, but I was unfortunately rather preoccupied with the cheeky CE stealing my engine, and didn't pay much attention until heading back to deep space and getting blown away from the ignition chamber which then ignited despite my being quite certain that there was no longer any burn mix available.

**Comment by timothymtorres** [comment]
Might be related to #51513 and #47148

**Comment by Sealed101** [comment]
from what i understand this could have been caused by an airmix being incorrectly copied over when a shuttle rotation happens, which may have caused the appearance of oxygen in the turbine's turf and the subsequent ignition

was unable to reproduce. even though shuttle code is still an enigma, surely in the 6 years that have passed something got nudged enough to have fixed this
