### ISSUE TITLE
advanced roasting stick doesnt work 

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#39404]
91625

i tried cooking a sausage on the super matter from away and it didnt work

it works when next to it

**Comment by Kagus** [comment]
That's just how the code's written, the only thing you can roast it on from a distance is a singularity, due to the natural difficulties involved with being adjacent to one long enough to roast a sausage.

Everything else is an adjacency check, including Ratvar.

**Comment by ninjanomnom** [comment]
Sounds about right to me
