### ISSUE TITLE
All Fedoras Spawn With A Detective's Flask Inside

### ISSUE THREAD

**Issue by Kerbin-Fiber** [tgstation/tgstation#39408]
>Be Curator
>Goto CuraDrobe
>Get treasure hunter's fedora
>Find Detective's Flask in it
>Drink it and get drunk

Happens 24/7 in all vending machines and all fedoras that are spawned.

**Comment by kingoftheautism** [comment]
It's really old bug, i'm surprised that nobody reported that, maybe because they were lazy enough
