### ISSUE TITLE
Occupation Preferences on Terry borked

### ISSUE THREAD

**Issue by DfourC** [tgstation/tgstation#39402]
Currently on Terry the Occupation Preferences window treats Chaplain like the Assistant slot, being set to Yes/No instead of Never/Low/Medium/High. Setting Chaplain to Yes disables the rest of the options, like Assistant should. Setting Assistant to High doesn't disable the rest of the options.

**Comment by AnturK** [comment]
Like and event/admin/map changed overflow role to chaplain. That's how it's supposed to work if that's done.

**Comment by DfourC** [comment]
Current round is 91609 but I think I noticed this being the case yesterday or sometime before, I don't recall precisely.

**Comment by SpaceManiac** [comment]
Without a precise round ID we can't check logs to verify, but this is intended behavior under certain in-game conditions.
