### ISSUE TITLE
the navigation computer( the one that places white ship to custom location ) lags a lot when used if you have TK

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#39406]
91627 bagil

it works fine for like 10 seconds then it freezes, your pointer is at the end of the map and it says " your mind wont reach that far" trying to move more just freezes and lags more

**Comment by Mark9013100** [comment]
On latest Byond beta, using the shuttle nav jumps my disk usage to 100 from 30. Nearly impossible to use.

**Comment by SuperNovaa41** [comment]
No longer an issue
