### ISSUE TITLE
Mech construction is lacking todo steps

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39411]
Much construction is pretty unintuitive to new players, since they have to pull up the wiki and look at each step. 
This could be fixed by adding something like r-wall `deconstruction_hints` that list what to do next.

**Comment by Repukan** [comment]
Isn't there a robotics manual in the labs?

**Comment by zxaber** [comment]
It would be helpful also when there's a half-finished mech in your lab and either you don't remember what you did last, or someone else was building it and then ran off.

Granted, you can usually use the screwdriver to undo the last step to see the progress, but still.

**Comment by Tlaltecuhtli** [comment]
you can examinate to see which step you are on, if a wiki  with every step isnt enough for new players lets just make the mech come out already finished at this point

**Comment by Dennok** [comment]
Make a special huge machine to produce mechas is good idea. We can balance it by time of construction,  price in power, researches and maybe materials.
