### ISSUE TITLE
Prison cubes can break unbreakable walls

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#39425]
[Reproduction]: Get the prison cube from #39307, trap someone in it while next to a unbreakable wall, wall is broken

**Comment by octareenroon91** [comment]
The `turf` `PlaceOnTop()` is indiscriminate

**Comment by ninjanomnom** [comment]
The turf changes need to check they aren't putting open turfs on a closed turf.

@AnturK
