### ISSUE TITLE
APC in new Delta Whiteship is placed slightly wrong

### ISSUE THREAD

**Issue by kingoftheautism** [tgstation/tgstation#39422]
Issue: Crew Quarters hall APC is placed in a wrong place. You can see it even on screenshot from WJohn PR (#39278 ), where it's placed directly above airlock. Isn't it supposed to be a bit right?
![141](https://user-images.githubusercontent.com/40269243/43357982-6ce7bbd0-92c5-11e8-8d13-aba51adef188.png)

**Comment by WJohn** [comment]
whoops.
