### ISSUE TITLE
No shuttle manipulator found

### ISSUE THREAD

**Issue by TheWrongHands** [tgstation/tgstation#39439]
clean install of a new server following the instructions here: https://github.com/tgstation/tgstation

when the server initializes i get the following errors:

[22:20:15] Runtime in shuttle.dm,79: No shuttle manipulator found.
  proc name: initial load (/datum/controller/subsystem/shuttle/proc/initial_load)
  src: Shuttle (/datum/controller/subsystem/shuttle)
  call stack:
  Shuttle (/datum/controller/subsystem/shuttle): initial load()
  Shuttle (/datum/controller/subsystem/shuttle): Initialize(192150)
  Master (/datum/controller/master): Initialize(10, 0)
## WARNING: No /obj/docking_port/mobile/supply placed on the map! in code/controllers/subsystem/shuttle.dm at line 74 src: Shuttle usr: .

I've run every map that comes with the server and none of them seem to have a shuttle
the mining shuttle console says it's *missing*
calling the emergency shuttle does nothing after you enter the reason
the supply console throws a javascript error when opened and then just says "loading" forever

**Comment by SpaceManiac** [comment]
Ensure you have not unchecked `_maps/_basemap.dm` in Dream Maker. Without this file checked, CentCom will not load and various things will not work. While you're at it make sure you have not checked *any* `.dmm` files.

**Comment by TheWrongHands** [comment]
i thought _maps/_basemap.dm was a test map or something but checking it in addition to my desired map seems to have worked, thank you
