### ISSUE TITLE
TGui's range problems

### ISSUE THREAD

**Issue by Archemagus** [tgstation/tgstation#39449]
EngiBorg's RPD
Can't choose pipes, becouse "out of range"
I looked onto "eye" in the corner.
![image](https://user-images.githubusercontent.com/32466328/43368074-cb06496c-935f-11e8-8523-56f87907026d.png)

Well, this is forked build so sorry if this is already fixed

**Comment by Archemagus** [comment]
UPD:
Remote APC control have the same problem.
![image](https://user-images.githubusercontent.com/32466328/43369311-632c2fc2-9374-11e8-8418-be981b224fb8.png)

**Comment by SpaceManiac** [comment]
Cyborg thing fixed by #39412.

Remote APC issue still exists.
