### ISSUE TITLE
Mk Honk Prototype Shoes are Broken

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#39442]
[Round ID]: 91720

There's no way to fuel the mk honk prototype shoes. When trying to insert bananium the only thing that happens is a red message: "The mk-honk prototype shoes cannot hold the bananium!"

The action button causes the message: "You need bananium to turn the prototype shoes on!". Using the shoes in hand tries to take bananium out of the shoes (There is none).

I just want my meme shoes help.

**Comment by Kagus** [comment]
Are you using bananium ore or processed bananium?

**Comment by SpaceManiac** [comment]
Related #35196

**Comment by newfren** [comment]
I tried using both bananium ore and processed bananium.
