### ISSUE TITLE
Chemical payloads don't behave as intended

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39447]
Right now, chemical bomb payloads don't behave as intended:

They only ever accept a single beaker, no matter the `rating`.
https://github.com/tgstation/tgstation/blob/a3137f2690bcd86cf2d30a56ccb6c3428d2e2064/code/game/machinery/syndicatebomb.dm#L461
They also don't accept any type of grenade casing or slime core. This doesn't work no matter the grenade construction step or whether it's loaded/empty.

**Comment by AlexTheSysop42** [comment]
You need to craft it with the crafting menu

**Comment by 81Denton** [comment]
I misread the whole crafting prompt, thanks for the heads up.
