### ISSUE TITLE
Able to put Evidence Bag Box inside an evidence bag, which was inside that evidence bag box

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#39452]
Issue reported from  Round ID: 91734 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

As the title says, I accidentally put an evidence bag box into an evidence bag, which was in that box. This resulted in the box disappearing from my inventory.

**Comment by bgobandit** [comment]
related to this? https://github.com/tgstation/tgstation/issues/38629

**Comment by Hathkar** [comment]
Seems so. I don't know if that issue removes the body bag or backpack from existence though.

**Comment by cyclowns** [comment]
i'm sure spawning a singularity out of evidence bags won't have any adverse effects on balance

**Comment by Kagus** [comment]
Balance is for gymnasts. Spessmen automatically maintain an upright position even in zero gravity.

We have moved beyond mere balance.

**Comment by callanrocks** [comment]
> Seems so. I don't know if that issue removes the body bag or backpack from existence though.

It does but it doesn't, people in a bluespace bodybag will be able to resist out but anything else is trapped in nullspace forever.

**Comment by cacogen** [comment]
If the criminal uses an evidence bag, it needs to go into evidence

**Comment by kriskog** [comment]
Box drops on the floor now, the bags with the box in them don't actually contain the box but are stuck with the box overlay even if you empty them of the nothing. They can stil be reused.
