### ISSUE TITLE
All Fedoras Still Spawn With A Detective's Flask Inside

### ISSUE THREAD

**Issue by Kerbin-Fiber** [tgstation/tgstation#39458]
Round ID: Every round 
Server: Bagil

>Be Curator
>Goto CuraDrobe
>Get treasure hunter's fedora
>Find Detective's Flask in it
>Drink it and get drunk

Happens 24/7 in all vending machines and all fedoras that are spawned.

- Detective now has 5 flasks, what an alchoholic!

**Comment by SpaceManiac** [comment]
Duplicate of #39456
