### ISSUE TITLE
Non-Detective Fedoras still spawn detective's flasks

### ISSUE THREAD

**Issue by Kerbin-Fiber** [tgstation/tgstation#39456]
>Be Curator
>Goto CuraDrobe
>Get treasure hunter's fedora
>Find Detective's Flask in it
>Drink it and get drunk

Still happens.

![flask](https://user-images.githubusercontent.com/31713423/43370357-44349662-9343-11e8-8e1b-f278ef58c898.PNG)

**Comment by SpaceManiac** [comment]
\>no round ID

server is probably just out of date

**Comment by Kerbin-Fiber** [comment]
@SpaceManiac I'll edit this cuz it happens EVERY ROUND

**Comment by Kerbin-Fiber** [comment]
Done

**Comment by SpaceManiac** [comment]
A round ID is still useful even when something happens in multiple rounds. In this case, I can now confirm that the server just needs to be updated.
