### ISSUE TITLE
Twisted construction can be used on already-offered borgs

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#39464]
round 91757

1. Use twisted construction on borg, wait for dialog box to choose construct type
2. Have other cult member offer borg, creating a soulstone
3. Select a construct type from the twisted construction
4. You now have a soulless construct, which can then be sactificed itself for another shard

**Comment by CrazyClown12** [comment]
See this bug in action.

http://www.youtube.com/watch?v=IucMpuZQu-8&t=25m0s
