### ISSUE TITLE
Species not appearing in character menu

### ISSUE THREAD

**Issue by Bobbry** [tgstation/tgstation#39473]
My problem is that when I installed this game from github with the guide on TGStation wiki
my character creation menu doesn't show  catpeople, mothpeople, or fly people. Is they supposed to be there or not?

**Comment by SpaceManiac** [comment]
They need to be enabled in the config, the defaults are in `config/game_options.txt`. 
* moths: `ROUNDSTART_RACES moth`
* flys: `ROUNDSTART_RACES fly`
* cats: `JOIN_WITH_MUTANT_HUMANS`

**Comment by SpaceManiac** [comment]
Uncomment (or create) the relevant lines (listed above)

**Comment by Bobbry** [comment]
I already see the lines there

**Comment by SpaceManiac** [comment]
If they start with `#` you need to delete the `#`

**Comment by Bobbry** [comment]
Ok

**Comment by SpaceManiac** [comment]
Assuming you figured it out, feel free to post back if not
