### ISSUE TITLE
Revenants can bodyslam the SM endlessly when visible at no damage to themselves.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#39488]
If a revenant reveals itself and becomes solid, it can slam the SM shard hundreds of times by running into it which is very loud and text spammy.

**Comment by ExcessiveUseOfCobblestone** [comment]
Pretty sure it supercharges your engine too so it gives lots of power.

**Comment by 81Denton** [comment]
`power = 3240` yikes
