### ISSUE TITLE
Augmented chests cannot be repaired with welders/coils.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#39485]
All other limbs work as normal, but augmenting a chest both doesn't fix the damage from the procedure, or give it its damage reduction, or let you repair it with welders/coils (must use regular medicine like brute packs) or refer to it as a cyborg chest when struck/examined with a health analyzer.

**Comment by Cyprex** [comment]
That does sound like it doesn't actually change the chest limb.
