### ISSUE TITLE
Placing floor tiles on water tiles was a terrible mistake

### ISSUE THREAD

**Issue by kingoftheautism** [tgstation/tgstation#39503]
Apparently if you place floor tiles on water tiles something goes wrong

Reproduction: Go as Hotel Staff Ghost Spawner, rush for 1 piece of metal, craft 4 floor tiles, place on water tile
![ru tg yellow station bear course quebec 2018-08-01 203138](https://user-images.githubusercontent.com/40269243/43519402-454b9f58-95ca-11e8-9894-d78f20835b79.png)

**Comment by obscolene** [comment]
install counter strike source

**Comment by kingoftheautism** [comment]
nice meme

**Comment by kingoftheautism** [comment]
still wasn't fixed

**Comment by kriskog** [comment]
Fixed
