### ISSUE TITLE
The syndicate radio implant breaks using other radio channels

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#39518]
Reported by a player, haven't reproduced it myself

- Have a headset that has non-standard channels (IE sec radio, cargo radio, medbay radio, command radio, etc)
- Use the syndicate radio implant
- You will not be able to use the non-standard channels, only the traitor channel and common radio

**Comment by Jalleo** [comment]
See the first issue report linked to tge issue above its apparently intended. It may be easy to fix or a issue with the multiple radio methods avaliable on person at large.

**Comment by SpaceManiac** [comment]
Duplicate of #34136. I don't see why this should be intended but it might be annoying to fix
