### ISSUE TITLE
VR Holocalling

### ISSUE THREAD

**Issue by Kerbin-Fiber** [tgstation/tgstation#39516]
[Round ID]: 91910

[Reproduction]: Go into VR, call someone using a holopad, leave the call. Static.

![image](https://user-images.githubusercontent.com/31713423/43560841-fbdad054-95d9-11e8-8e1c-7ebc08fbac5f.png)

**Comment by ShizCalev** [comment]
@AnturK

**Comment by Bawhoppen** [comment]
Probably very related to: https://github.com/tgstation/tgstation/issues/39752

**Comment by Bawhoppen** [comment]
Matter of fact, it's probably so related it's a dupe.
