### ISSUE TITLE
Escape Pods don't reach CentCom Z level

### ISSUE THREAD

**Issue by Mark9013100** [tgstation/tgstation#39523]
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

Round ID: 91932

For the past day or so, escape pods don't reach the CentCom Z level, this results in being counted as marooned. I've seen this happen on Delta and Meta station, not sure of the other maps.

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

Use an escape pod instead of the shuttle.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 91932

Server revision compiled on: 2018-08-01

The following pull requests are currently test merged:
#39426: 'Rapid attacking simple animals.' by AnturK at commit 1b18a6cdd2

Based off origin/master commit: a0b1b82608

Revision: ae80ca5e14ce8a9bfca0560fa58cb885434f2aca

Server tools version: /tg/station 13 Server v3.2.2.0

**Comment by SpaceManiac** [comment]
@ninjanomnom I suspect #39219
```
## WARNING: couldn't find dock with id: pod_away in code/controllers/subsystem/shuttle.dm at line 165 src: Shuttle usr: .
[14:05:23] Runtime in docking.dm,5: Cannot execute null.get docked().
  proc name: initiate docking (/obj/docking_port/mobile/proc/initiate_docking)
  src: the escape pod (/obj/docking_port/mobile/pod)
  src.loc: the shuttle floor (48,16,3) (/turf/open/floor/mineral/titanium/blue)
  call stack:
  the escape pod (/obj/docking_port/mobile/pod): initiate docking(null, null, 0)
  the escape pod (/obj/docking_port/mobile/pod): on emergency dock()
  Box emergency shuttle (/obj/docking_port/mobile/emergency): check()
  Shuttle (/datum/controller/subsystem/shuttle): fire(0)
  Shuttle (/datum/controller/subsystem/shuttle): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
```

**Comment by ninjanomnom** [comment]
Only the first pod seems to break, other pods reach centcom fine
