### ISSUE TITLE
Can't smother people with the damp rag anymore

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#39527]
This worked about a month ago, not sure what changed

1. Grab a damp rag
2. Fill it with something
3. Harm intent, target mouth
4. "You splash the contents of the damp rag onto (mob)"
    "You start to wipe (mob) with the damp rag"

**Comment by DaxDupont** [comment]
good

**Comment by octareenroon91** [comment]
Probably due to addition of `.=..()` in `afterattack` from #38606
