### ISSUE TITLE
Honkbots disappear when turned off.

### ISSUE THREAD

**Issue by NotABeaver** [tgstation/tgstation#39524]
Issue reported from  Round ID: 91940 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Honkbots disappear and cannot be interacted with if turned off. You can still turn them on, and they will reappear, if you haven't closed the interaction window. Missing sprite, probably?

https://i.imgur.com/0UVyDZB.jpg

**Comment by bgobandit** [comment]
good riddance imo

**Comment by XDTM** [comment]
you can probably interact with alt click on the tile, if you need to
