### ISSUE TITLE
Off-station antagonists still have traits.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#39522]
This means if you're using something like a prosthetic limb, or are a pacifist, or are afraid of the dark, you'll have those as a wizard and *nuke op* which is probably going to be detrimental and not something you can do anything about. These should probably not have any traits that would be meant for your crewmember self.

**Comment by bgobandit** [comment]
If you don't want traits as an antag, disable antag or don't take traits. No one is forcing you to do either.

**Comment by XDTM** [comment]
@bgobandit Crippling traits are fun when part of the crew, but it sucks for the nuke op that keeps them as well as their team. 

And traits are meant to be tied to the character, not the player, so roles that spawn a separate character should not take them into account.

**Comment by Anonmare** [comment]
Being an antagonist should override pacifism. If it's not, that's a bug

**Comment by bgobandit** [comment]
But what if someone wants the challenge of playing a pacifist antag (personally that sounds interesting as fuck, trying to engineer a death without actually killing, basically being Batman)?

**Comment by lolman360** [comment]
race and name don't carry over when you roll wizard/newcop, so why should traits?

**Comment by kriskog** [comment]
#44781
