### ISSUE TITLE
wearing kitty ears as a catperson gives you double tail

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#39535]
it's only noticeable when one is wagging and the other isn't

**Comment by GunHog** [comment]
Well, I mean, it makes sense. You are physically wearing a tail toy along with your real tail!

**Comment by bgobandit** [comment]
feature

**Comment by Barhandar** [comment]
The real question is where the second tail gets attached on catpeople.

**Comment by nemvar** [comment]
feature
