### ISSUE TITLE
Stamped paper bugs out clipboards

### ISSUE THREAD

**Issue by Michael-Ashfield** [tgstation/tgstation#39539]
[Round ID]: #91985

The bug: If you stamp paper with the approved or denied stamps (other stamps not tested but likley share this bug) then put the paper on an empty clipboard, only the stamp is shown on the clipboard, the white of the paper is not shown.

To recreate:
1. Go to cargo and get an approved stamp
2. Get an empty clipboard
3. Stamp some paper
4. Put the stamped paper on the clipboard
5. Look at the clipboard, you will now see a stamp on brown clipboard.

**Comment by kriskog** [comment]
Can't reproduce
