### ISSUE TITLE
Meta station engineering lobby airlocks lack floor tiles.

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#39532]
@81Denton nice re-mapping nerd

Explicitly, it's the airlock that leads into the hallway and the airlock that leads into the shared engineering storage.

**Comment by 81Denton** [comment]
On most maps it's random if there are floortiles underneath airlocks or not. Probably because there aren't any design guidelines or anything. Let me check Meta real quick

**Comment by 81Denton** [comment]
Huh, so airlocks leading to maint have plating while the rest has floor tiles. I'll open a PR later.
