### ISSUE TITLE
Rogue pixel on the tail club.

### ISSUE THREAD

**Issue by tralezab** [tgstation/tgstation#39561]
Reporting client version: 512

![image](https://user-images.githubusercontent.com/40974010/43679571-ce5e6cfe-97db-11e8-87fb-db7f10638711.png)

**Comment by WJohn** [comment]
fuck this entire sprite is so ugly i'm getting angry looking at it.

**Comment by tralezab** [comment]
You might think the problem is the rogue pixel in the sprite, but it's the rogue sprite in the game.
