### ISSUE TITLE
Revenants can block the supply shuttle

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39560]
Revenants can sit on the supply shuttle while invisible, preventing it from leaving while cargo techs have no clue why.

**Comment by SpaceManiac** [comment]
shuttle won't leave, must be haunted

**Comment by Tlaltecuhtli** [comment]
can we do this but for the escape shuttle? would be cool that the escape shuttle wont leave because spooks onboard

**Comment by Dennok** [comment]
Interesting
