### ISSUE TITLE
Moodlet duration doesn't refresh while it's still active

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#39578]
Example: 
The moodlet for slipping has a 3 minutes duration
You slip at 0:00
You slip again at 2:30
Moodlet goes away at 3:00

@Qustinnus

**Comment by Qustinnus** [comment]
Mmh..Odd I don't remember this being a thig but I'll look into fixing it. I can see a possible cause.

**Comment by Mickyan** [comment]
I don't knowhow the code works exactly but my best guess would be the signal to clear the previous event goes through as normal once the time runs out regardless if that same type of event is triggered again.

I say this because I noticed consecutive triggers of the same event (within the first duration) will always cause it to time out 3 minutes later for each trigger. 
So if you slip at 1:00, 2:00 and 3:00 the moodlet will be cleared at 4:00, then 5:00 and 6:00

**Comment by Qustinnus** [comment]
no because if the same moodlet is invoked twice, it would use the same datum. This bug can be fixed by adding

```
	if(the_event.timeout)
		addtimer(CALLBACK(src, .proc/clear_event, category), the_event.timeout)

```
above of L203 (return 0) in https://github.com/tgstation/tgstation/blob/master/code/datums/components/mood.dm, I'll try to make a PR once I get home somewhere this week, or you can make the PR if you feel like it.

**Comment by Mickyan** [comment]
That didn't seem to work for me but it's entirely possible I messed something up  since I don't entirely get how it works, so I'll leave you to it

**Comment by Qustinnus** [comment]
I might also just be wrong. :P

**Comment by ExcessiveUseOfCobblestone** [comment]
Pretty simple: It's not coded to reset duration. It overrides or does nothing.

**Comment by Qustinnus** [comment]
thats what i posted above

**Comment by ExcessiveUseOfCobblestone** [comment]
Yes but adding comments to the PR makes it look more important on the tracker

**Comment by Qustinnus** [comment]
lol i forgot these arent unreal engine 4 timers my bad @Mickyan I'll PR a fix
