### ISSUE TITLE
Hierophant aggro triggers while standing one tile outside of the arena

### ISSUE THREAD

**Issue by Enzarel** [tgstation/tgstation#39589]
I ded

**Comment by AlexTheSysop42** [comment]
I've never had it aggro while it was offscreen, even in the arena. Did you do something that damaged it?

**Comment by Kagus** [comment]
Or, potentially, stand too near to some legions when it was going on another skullcrushing bender?

**Comment by ChangelingRain** [comment]
The most likely cause is that it was already aggroed and happened to swap target to you.

**Comment by Enzarel** [comment]
All i can tell you is that i was dragging an ore box around the arena, and from my knowledge i was completely alone

**Comment by Kagus** [comment]
You wouldn't happen to have the round number readily available, would you?

**Comment by Enzarel** [comment]
Sadly no. I don't even remember the day this happened on.

**Comment by kriskog** [comment]
Not seen, as mentioned previously it was probably already aggroed to something else that died.
