### ISSUE TITLE
particle rifle is so laggy it causes crash when used in  zoom mode

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#39585]
92123

**Comment by SpaceManiac** [comment]
client version was 512.1442

**Comment by SethLafuente** [comment]
This is an extremely old issue from 6 years ago, tested in local it dosen't cause the game to crash and it's no longer as laggy as it used to be.
![dreamseeker_gpBDtsRrxx](https://github.com/tgstation/tgstation/assets/84478872/2ec1e4fe-eaba-4e77-9339-2c61866012c7)
