### ISSUE TITLE
a null crate had an item (in the manifest) that wasnt in the crate (it was considered correct manifest)

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#39609]
[Round ID]: # 92201 bagil

the null crate said there was a "decoy nuke disk" but there were none in the box, when i denied the manifest it gave me - points bcs it said it wasnt wrong

**Comment by YPOQ** [comment]
Happens due to the station-loving component, I believe. Cargo items are created in nullspace then moved to the supply shuttle, both of which which will trigger a location reset.

**Comment by ExcessiveUseOfCobblestone** [comment]
why is the decoy nuke stationloving

**Comment by octareenroon91** [comment]
It's a child type of the real nuke disk, and the stationloving component was not suppressed.

````
/obj/item/disk/nuclear/ComponentInitialize()
        . = ..()
        AddComponent(/datum/component/stationloving, !fake)

````

I don't know what that `!fake` could hope to connect to.
