### ISSUE TITLE
RPDs cannot switch between categories

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#39626]
[Round ID]: 92244

[Testmerges]: #39304: 'Stamina rework electric boogaloo - Limb specific regen instead of mob combined regen, chest/head only limbs that count for full stun, other limbs get individually disabled.' by kevinz000 at commit c79512d0d2 
#39567: 'Refactor the map loader' by SpaceManiac at commit 3009fe2a23 
#39147: '[READY]Adds ability to give airlocks one-way unrestricted access' by zxaber at commit 4fc2fb6fef 

[Reproduction]: 
1. Grab RPD.
2. Try to switch category to "disposal pipes" or "transit tubes".
3. Cry as you are unable to construct infinite disposal/transit loops.

**Comment by zxaber** [comment]
Seems like it could be because 39147 modifies tgui. I might have messed something up compiling it.

**Comment by zxaber** [comment]
Updated PR 39147 with new tgui.js and tgui,css files. Seems to have fixed the issue.
