### ISSUE TITLE
Camera prompts appear twice for Resize View Width, Caption Photo.. everything

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#39627]
Issue reported from  Round ID: 92255 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

WHEN USING THE CAMERA, ALL THE PROMPTS IT OPENS APPEAR TWICE

**Comment by SpaceManiac** [comment]
Couldn't reproduce locally, did you perhaps print two photos?

**Comment by kriskog** [comment]
Cant reproduce
