### ISSUE TITLE
Tesla Balls Gib You If You Touch Them Telekinetically

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#39637]
[Round ID]: # 92279

[Reproduction]: Get telekinesis, and click on a tesla ball from any range. You are now gibbed.

Also, i ded

**Comment by XDTM** [comment]
make telekinesis fry your brain when doing this, like we did with the supermatter

**Comment by 81Denton** [comment]
could probably do the same for singulo, then it would pop out your brain if you tried to TK the tesla ball/narsie as well

**Comment by 81Denton** [comment]
https://github.com/tgstation/tgstation/blob/22cfc011bea64a32189d7f13b91f710e2ebb175f/code/modules/power/supermatter/supermatter.dm#L519-L524
