### ISSUE TITLE
Telekinesis cannot move items off of tables that are on the shuttle.

### ISSUE THREAD

**Issue by Qlonever** [tgstation/tgstation#39647]
[Round ID]: 92324

[Reproduction]: Put an item on a table on the shuttle and attempt to make it move through telekinesis. You will not be able to do it. I suspect this happens because of the code preventing items on top of tables from moving when the shuttle launches or stops.

**Comment by PKPenguin321** [comment]
Also noticed that throw mode for admin build mode seemingly doesn't work on the shuttle

**Comment by Dennok** [comment]
Still issue?
The tables magnetick field is disabled as i know, so this issue fixed and outdated.
