### ISSUE TITLE
Oil footprints on the same tile as blood footprints causes blood footprints to not stack properly

### ISSUE THREAD

**Issue by MrAlphonzo** [tgstation/tgstation#39648]
[Round ID]: # 92323 but it doesn't fucking matter.

When an oil footprint meets on the same tile as a blood footprint, the blood footprints lose their shit and do not stack properly, creating way too many instances.

This is borderline crashing the server pls fix fast.

![footprints are stacking](https://user-images.githubusercontent.com/16946008/43987585-ace517de-9cf0-11e8-8213-9edaa6ace699.png)

EDIT: I believe this is a result of the blood and oil footprints having the same shape, as it does not happen every time the two types of footprints meet, as seen here.

![fuck](https://user-images.githubusercontent.com/16946008/43987609-2b085d6a-9cf1-11e8-8476-e5958bdc2f97.png)

**Comment by YPOQ** [comment]
SpaceManiac posted the solution here https://github.com/tgstation/tgstation/pull/39550#issuecomment-410471946
