### ISSUE TITLE
Null rods wont show the menu to change null rod type

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#39645]
Issue reported from  Round ID: 92313 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Can't select holy weapon as chaplain.

**Comment by SpaceManiac** [comment]
No repro on 8ea486415f6d36617f8df4390c8e9634da42ae00.

**Comment by kriskog** [comment]
Also cant reproduce, works fine if you are a chaplain.
