### ISSUE TITLE
Unable to add messages to people with no messages

### ISSUE THREAD

**Issue by ThatLing** [tgstation/tgstation#39665]
Looks like https://github.com/tgstation/tgstation/pull/39009 broke this. More specifically ![here](https://github.com/tgstation/tgstation/blob/master/code/modules/admin/sql_message_system.dm#L312-L383). If they don't have any messages, target_key will be null and you will be unable to add any new messages since the href will be dead.

**Comment by MrStonedOne** [comment]
@Jordie0608

**Comment by ThatLing** [comment]
Same thing happens ![here](https://github.com/tgstation/tgstation/blob/master/code/modules/admin/sql_message_system.dm#L99-L125).

**Comment by Jordie0608** [comment]
Meanwhile until fix is merged, you can still add notes for players without any notes by doing so from the search index rather than the notes page for a player.
