### ISSUE TITLE
Generators cannot be attached directly to terminals.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#39669]
Not entirely sure if this is a bug, but you can't attach a generator *directly* onto a terminal. You MUST have it connect to a knot, which then goes to another knot into the terminal, and *then* you can power that APC or SMES or whatever. This really only serves to confuse and annoy people.

**Comment by kriskog** [comment]
With smart cables you only need one cable piece on the same tile. I feel thats reasonable.
