### ISSUE TITLE
Dragnets no longer teleport people to beacons

### ISSUE THREAD

**Issue by Wilchenx** [tgstation/tgstation#39671]
Dragnets no longer teleport people to beacons
They just randomly teleport people for up to 10 tiles
Setting the teleporters up does nothing

**Comment by AlexTheSysop42** [comment]
Did you try clicking the gun on the beacon?

**Comment by Wilchenx** [comment]
That was never merged and i've tried

**Comment by SpaceManiac** [comment]
You have to set the station teleporter to target the beacon in question

**Comment by kriskog** [comment]
Works off the teleporter as he said.
