### ISSUE TITLE
Disposal bins can place parcels below them

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39676]
![reeeee](https://user-images.githubusercontent.com/32391752/44014314-93285720-9ecb-11e8-9950-bb20469be6b2.png)

When disposal bins receive parcels, they sometimes fling the parcel onto their own tile - this places the parcel underneath them, making it invisible unless you use the context menu.

**Comment by Enzarel** [comment]
I vaguely recall this also happening to atmos things and hand-held oxygen tanks.

**Comment by Mooshimi** [comment]
I have never seen this, please @ me to reopen or reopen yourself if this is still happening
possible related area:
https://github.com/tgstation/tgstation/blob/06cd9086eb2f1d1927152d1ef441906b9665e538/code/modules/recycling/disposal/pipe.dm#L88-L115
