### ISSUE TITLE
Pirate cutter vault is rather small, could use milk

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39683]
![adsfdsaasdadsf](https://user-images.githubusercontent.com/32391752/44023675-60c37740-9eeb-11e8-842f-60ed4a15c232.PNG)

Considering that skeletons don't breathe or eat: The space occupied by the microwave, suit storage units and bathroom could probably be repurposed.

I also noticed that the cutter only has two jetpacks for three crewmembers.

**Comment by XDTM** [comment]
Skeletons do process reagents, they just can't inject them

**Comment by 81Denton** [comment]
Fixed by #39749
