### ISSUE TITLE
(Death) Nettles contain (fluoro)sulph. regardless of removing production gene

### ISSUE THREAD

**Issue by recurracy** [tgstation/tgstation#39682]
[Round ID]: Not entirely sure, but I think 92409, give or take 2. I play exclusively on Sybil.

[Testmerges]: Branch in use at Sybil at the time of writing

[Reproduction]:
- Grow death nettle
- Remove fluorosulphuric acid and sulphuric acid production
- Replace with anything (I believe I used morphine, coniine and cyanide)
- Plant the experimental death nettle 
- Harvest
- Grind the death nettle
- See the beaker contain fluorosulphuric acid and sulphuric acid

I'm not sure if this happens with regular nettles as well.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/e5e0459e334f2c71caf64f111cdd425f2991a89d/code/modules/hydroponics/grown/nettle.dm#L46

**Comment by ExcessiveUseOfCobblestone** [comment]
Nettles are also not typed the same as other growns which could be another problem.

**Comment by kriskog** [comment]
Probably related to Denton's comment. I have been unable to grow deathnettles with chemical contents. The seeds have the traits, but the plant itself does not contain the chems when you scan it with the plant analyzer, nor transfer any when you throw it at someone with hypo. So they are kinda non-functional, except as swords.

**Comment by ExcessiveUseOfCobblestone** [comment]
they really should be typed with other growns, I'm willing to bet that's the bulk of the problem.
