### ISSUE TITLE
You can make an unlimited ammount of walled mounted defibrillators.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#39704]
[Round ID]: 92499
[Reproduction]: 1) take a normal defibrillator.
2) print some defibrillator mounts from medical protolathe.
3) put defibrillator in the defibrillator mount.
4) take it from there.
5) place it in the second defibrillator mount.
6) repeat as many times as you want.
![1](https://user-images.githubusercontent.com/34580767/44090524-1fed0db0-9fd3-11e8-8d9c-f7b18eb403ba.png)
![2](https://user-images.githubusercontent.com/34580767/44090526-2029893e-9fd3-11e8-9bef-2f1f9bb9010c.png)
![3](https://user-images.githubusercontent.com/34580767/44090527-2060e8e8-9fd3-11e8-979e-633e519bf7bc.png)
![4](https://user-images.githubusercontent.com/34580767/44090528-209df4c2-9fd3-11e8-9cf7-0dc7f5c90cf9.png)

**Comment by ExcessiveUseOfCobblestone** [comment]
is this an icon bug, a 2 location 1 object bug, or a true dupe?

**Comment by IllotAFV** [comment]
you cant use that defibrillator, while you have it in your hands, but every mounted defibrillator can be used properly.

**Comment by Time-Green** [comment]
its a 2 location 1 object bug, wall mounts are very bugged and 9/10 times break

**Comment by Jared-Fogle** [comment]
walled defibs have never worked as far as im aware

**Comment by Barhandar** [comment]
Walled defibs worked just fine in spring. They're supposed to only give you the paddles on regular click on the wall mount, not the whole defib item. Right now they're giving paddles and moving defib to your tile (I bet it's the "item pickup animation" doing that), after which you can do whatever you want with the defib while it's still registered to the wallmount.
