### ISSUE TITLE
Server Stability is garbage

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#39701]
Issue reported from  Round ID: 92483 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

See title, server crashes roughly every 2-3 rounds at best.

**Comment by optimumtact** [comment]
this isn't useful as a report, we know the server is crashing, it's kind of hard to miss.

Unless you know why it's happening you're not offering anything of value to us.
