### ISSUE TITLE
Abductors can’t perform surgical operations through clothes. 

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#39706]
I am not sure about this one, but I can totally remember, that abductor could make surgeries without taking abductee’s clothes off. But now you have to waste your precious time to take abductee’s stuff off, make surgery and put it on, because taking stuff away is a bad move. But if you are wasting time on that upon every single operation, that fleshy mass can trigger itself right on abductors’ ship.

**Comment by XDTM** [comment]
It's the abductor surgery that ignores clothes, abductors themselves do not ignore clothing requirements

**Comment by IllotAFV** [comment]
Last time I was abductor, their surgery still required to take abductee’s clothes off.

**Comment by XDTM** [comment]
not a bug, clothes requirement depends on the surgery and not on the surgeon

**Comment by IllotAFV** [comment]
Yes, it actually works now somehow. Maybe I wasn’t too attentive with this one.
