### ISSUE TITLE
Mounted defribillators not working

### ISSUE THREAD

**Issue by MortoSasye** [tgstation/tgstation#39732]
[Reproduction]: When i tried to pick up a mounted defribillator, another one appears in front of it but on the floor. 

Paddles show the first time on your hands, the second time you try to use the mounted defribillator you just end up with a normal one in the floor where you're standing, rendering the mounted defribillator useless.

**Comment by Jared-Fogle** [comment]
This has been happening for as long as I've been playing

**Comment by wesoda25** [comment]
This has been going on for like a month now I think
