### ISSUE TITLE
Escape pod without destiny 

### ISSUE THREAD

**Issue by MortoSasye** [tgstation/tgstation#39733]
[Reproduction]: Simply just use the escape pod when the shuttle is called, instead of arriving at centcomm you get stuck in space. The console shows it's going to an unknown destination.

**Comment by SpaceManiac** [comment]
Cannot reproduce on a4cd70ba23f8f70cd3d7306c6a491587c91ea1ba. This bug was recently fixed by #39675 recently fixed this bug so make sure you're up to date (all the servers should have this fixed as of now).
