### ISSUE TITLE
Examining a brain examines that persons body instead

### ISSUE THREAD

**Issue by Enzarel** [tgstation/tgstation#39730]
Works only if said body is within default screen distance
Does not work with view-expanding things, such as sniper rifles
In fact, it stops working at all if you use a sniper scope at least once

Found while doing ghetto organ removal surgery on my private test server (now featuring up-to-date code) using admin-spawned, catatonic, naked humans

**Comment by ShizCalev** [comment]
#53232 duplicate issue
