### ISSUE TITLE
Lag during an embedded object falling out causes the human it is embedded in to become invisible

### ISSUE THREAD

**Issue by Enzarel** [tgstation/tgstation#39748]
I was pulling around mindless humans with embedded throwing things on my private test server, and the moment the thing falls out the human becomes invisible, only to reappear once said thing is within screen-range.
A possible cause might be lag, because the thing somehow fell out around 10 tiles behind me

**Comment by Tlaltecuhtli** [comment]
how can you lag in local

**Comment by Enzarel** [comment]
Magic

**Comment by kriskog** [comment]
Old, no repro
