### ISSUE TITLE
/obj/machinery/power/apc/cant_delet

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#39756]
Literally can't destroy or delete it.

![image](https://user-images.githubusercontent.com/38788538/44265219-5569ea00-a22e-11e8-8f1c-a9cd11ba8c75.png)

![image](https://user-images.githubusercontent.com/38788538/44265220-5ac73480-a22e-11e8-9b2e-9d79460ba4a3.png)

Either i am a total imbecile or this APC can't be fully constructed (i.e. power areas)

`while i was writing this issue the cargo APC finally disappeared and so did some others what i tried to delete, but not all. Doesn't seem like server lag, people weren't complaining and i could smash stuff with an energy axe`

**Comment by SpaceManiac** [comment]
Did you admin spawn the APC in originally? It seems like APCs don't correctly determine what area they're in if admin spawned, which causes them to not work and also runtime during `Destroy`, delaying their deletion.

**Comment by RedFoxIV** [comment]
Yep, admin-spawned.

**Comment by SpaceManiac** [comment]
I'll take this bug as a note that APCs do not work correctly when admin-spawned.

**Comment by Mooshimi** [comment]
Tested + it's true still, the empty apc is stuck at atom integrity = 0

**Comment by Jewelry-x** [comment]
According to PR https://github.com/tgstation/tgstation/pull/74918, the APC existing with 0 integrity is intended behaviour, and this issue should be closed.
