### ISSUE TITLE
Release Obj disappeared from rightclick for admins

### ISSUE THREAD

**Issue by Carbonhell** [tgstation/tgstation#39757]
[Reproduction]: Rightclick, release obj isn't there,you need to manually type it to release an obj

https://github.com/tgstation/tgstation/blob/master/code/modules/admin/verbs/possess.dm#L28
The obj/O in world argument being removed caused this, should be a simple fix.

**Comment by Tranquill6** [comment]
This seems to have been fixed a while ago, close this.

**Comment by SpaceManiac** [comment]
Considering this closed given it's been a while and this is just how this verb works now
