### ISSUE TITLE
I was a normal player who only saw through AI cameras

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#39752]
[Round ID]: # 92621

HOLY SHIT this is the biggest whopper ive ever seen. I was normal, had normal vision, and then at some point I could only view the world through AI cameras. I could normally interact with shit, just I couldn't see anything not in camera range (got the AI static). 

[Reproduction]: Might have been because I was calling people using holopads, and was disrupted.

![seeing through ai cameras](https://user-images.githubusercontent.com/37246588/44243040-ebeccb80-a19a-11e8-9c0d-04c5a79b9c2b.png)
![cameras](https://user-images.githubusercontent.com/37246588/44243045-f4dd9d00-a19a-11e8-9178-91fd0d734755.png)

**Comment by wesoda25** [comment]
Oh also I just noticed, seems I was constantly set on walk? I was going around at running speed.

**Comment by WJohn** [comment]
what the fuck???? how did this happen??????

**Comment by wesoda25** [comment]
Exact chain of events:
Walk into vault -> Get arrested -> Go free -> Call bridge from arrivals holopad, don’t answer -> Call brig, they answer -> Someone interacts with me and ends the call -> Call brig gear room, get disrupted again -> Walk into dorm room -> Entire area is just static (I can walk inside, however cannot examine static areas or pick anything up) -> Experiment with cutting AI cameras (when I cut a cam I still have full view of said area. Once I move completely out of the cameras vision radius, it updates and the area is now static).

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Similar thing happened on yogs, the AI stopped seeing static, and another guy started seeing it after messing around with holocalling

**Comment by SpaceManiac** [comment]
@cruix in case you happen to have an idea

**Comment by Cruix** [comment]
I could understand a person still seeing static after a holocall, but having an AI stop seeing static at the same time is strange.

**Comment by Jared-Fogle** [comment]
the simulation is failing

**Comment by Bawhoppen** [comment]
Had the same issue just a moment ago. Seems to happen every time you call someone on a holopad.

**Comment by Dman757** [comment]
Had this same issue today. Used a holopad and when I walked out of range of the pad, as the hologram, I couldn't see except camera vision.

Also of note I tried the OOC cancel camera view that didn't work. But reconnecting worked and fixed my vision.
