### ISSUE TITLE
Mediborg surgery sheets not working 

### ISSUE THREAD

**Issue by MortoSasye** [tgstation/tgstation#39769]
[Round ID]: # 92668

[Reproduction]: When i tried to do surgery on someone eyes using first the surgery sheets it didn't work. I had them on the table at robotics, with all accessories off his face, and when that failed i tried with my own roller bed to no success. No idea why it didn't work.

**Comment by ExcessiveUseOfCobblestone** [comment]
One thing I do know is that if there's another surgery not finished it just hits the individual. Your case needs reproducing but I think a sensible fix to the issue at large would be to provide feedback there's another surgery in progress.
