### ISSUE TITLE
Fulltile windows immune to atmos pressure/heat

### ISSUE THREAD

**Issue by Robustitron** [tgstation/tgstation#39766]
[Round ID]: # 92654 (all rounds really, it's been a thing for awhile)

[Reproduction]: Start a tritium fire in a room, directional windows smash almost immediately, firelocks and airlocks eventually break apart, all the room contents turn to ash, and yet fulltile windows stay in perfect condition, regardless of type as far as I know.

In the past I remember really hot fires breaking windows and spreading around, but now they kind of sit there contained because fulltile windows are apparently stronger than airlocks.

**Comment by octareenroon91** [comment]
Can confirm. Windows aren't effected by adjacent gases or something. Pressure seems unable to go past 4000 kPa for a reinforced window adjacent to a contained fire.

There was that recent issue about heatproof airlocks.
