### ISSUE TITLE
Skeleton crew geneticists have RnD+tech storage access

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39762]
Seems to be leftover from when genetics was a RnD department:

https://github.com/tgstation/tgstation/blob/bf8a18da7e700ee43b7faaa520c40798c7b58ea9/code/modules/jobs/job_types/medical.dm#L151

**Comment by ExcessiveUseOfCobblestone** [comment]
Geneticist is part scientist

**Comment by newfren** [comment]
Genetics also has a science headset because they are also part of the science department.

**Comment by 81Denton** [comment]
ahh my bad
