### ISSUE TITLE
TGS4 Roadmap: Data directory usage during initialization needs an audit

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#39770]
The way TGS4 watchdog works is it runs 2 servers in tandem, both symlinked to the same config/data directories.

The server that the players are not currently on will run freely until initializations are complete and then go to sleep until the other reboots/crashes or it is killed to be replaced by an updated code deployment (in which case it, again runs initializations and then sleeps until (recursion)).

I already asked @Jordie0608 to address the db issues this caused with #37665 but now we have fs issues

Data directory usage prior to the "Initializations complete!" message needs to be looked over to see if it's doing anything that could conflict with the "true" server or otherwise reliant on a launch serialization factor. If so, things will need to be refactored to be dependant on server ordering somehow.

I'm open to ideas on different ways to address this. The only restriction is both servers will need to use the same symlinks, generally config and data in our case. We can define these to be anything we want but they have to be shared with both.

@tgstation/commit-access @MrStonedOne

**Comment by SpaceManiac** [comment]
excited to finally see hot/cold

recommend some strace-equivalent to check what reads `data/`. minimap, persistence, ticker, title, mapping, assets at minimum

**Comment by MrStonedOne** [comment]
One issue is the instances getting stale.

If they sit around and wait for a reboot, 1 4 hour round latter and 60 million config changes still won't be in effect.

So to that measure we also need the config controller to load after going hot, but it's needed for initialization, so we would need the config controller to re-load after going hot.

Adding support for re-loading the config would actually be nice, it would just need a verb/proc and maybe some way for the config datums to disallow reload, as well as bind to a reload happening.

**Comment by MrStonedOne** [comment]
I figured you'd handle stale code state, its stale data directory shit I'm worried about.

This would also apply to things like the npc data files, that load on start and write on shutdown.

In fact you shouldn't be looking at the cold server's init as much as you should be looking at the hot server's shutdown. Things it writes has to be in effect on the cold server when it goes hot.

**Comment by Cyberboss** [comment]
Yeah, we might need to end up adding a second phase to SS init where it's
allowed to use the data directory. I might also work on a framework for
sending messages to a cold server so we can do stuff like load the map
after rotation.

**Comment by Cyberboss** [comment]
The experimental watchdog was scrapped
