### ISSUE TITLE
var/bayonet has no effect

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39774]
https://github.com/tgstation/tgstation/blob/f38493cade08106348c114f6fc96162404609c0d/code/game/objects/items/kitchen.dm#L74

You can attach knives with `var/bayonet = FALSE` to guns, for example envy's knife and bone daggers.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/936f8c2923740ff83012d61f0a58dae0f4c6784b/code/modules/projectiles/gun.dm#L302-L306

?

**Comment by ShizCalev** [comment]
Seems like someone intended for a proper bayonet system at one time. This can be removed I guess.
