### ISSUE TITLE
Hungry icon remains forever

### ISSUE THREAD

**Issue by TheRespectedMan** [tgstation/tgstation#39789]
This is not unique to the round, this has been happening more or less all week and i asked about it in OOC and im not the only one.

Here's a pic to elaborate: https://i.imgur.com/gtbUAGE.png
I've been well fed for several minutes, yet the hunger icon remains. I accidentally fed myself into lardass status a few times on accident because of it.

**Comment by SpaceManiac** [comment]
Caused by #39743 @Qustinnus

**Comment by Qustinnus** [comment]
ill be sure to fix it tommorow
