### ISSUE TITLE
Synths don't lose their skin

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/tgstation#39788]
Synths are meant to lose their human exterior at 25 or 50 damage: https://tgstation13.org/wiki/Synth#Synths

They do not, and there doesn't even seem to be a way to force it to happen.

**Comment by Rayisken** [comment]
Do they? unless you are referring to them dropping the disguise permanently? Ive been messing with them extensively for an event on Yogs and they do show damage, it's based on what limb has been damaged so wearing a suit or clothing will hide any signs of damage. Setting species twice using VV will set the sprite to the undisguised synth

**Comment by Stickymayhem** [comment]
I did hundreds of damage repeatedly to every limb and spread across their whole body and the disguise never dropped naturally. I'll try that force method though, thanks.

**Comment by timothymtorres** [comment]
Synths were removed.
