### ISSUE TITLE
the shuttle beacons u buy from express cargo console break when a crate is sent on top of it

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#39794]
they cost 5000 and have a durability of 2 crates before being qdel from the explosion

**Comment by AlexTheSysop42** [comment]
intentional, you need to have someone move the beacon after calling in the crate

**Comment by Tlaltecuhtli** [comment]
who tought thats a good idea

**Comment by MrDoomBringer** [comment]
@tlatecuhtli, it was intended to have one person running around with the beacon and another person manning the cargo console, to promote teamplay and shit

**Comment by kriskog** [comment]
Intended feature, also these are much cheaper now.
