### ISSUE TITLE
Suicide is faster for debraining

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/tgstation#39796]
Instead of doing the operation, roboticists ask their patients to kill themselves with a box to debrain them using the suicide verb. Not a bug, but it doesn't seem like intended gameplay

**Comment by AnturK** [comment]
Same thing with chopping off and smashing the head having no side-effects really.

**Comment by Tlaltecuhtli** [comment]
who would have wondered that time delays for the sake of time delays wont be circunvented

**Comment by octareenroon91** [comment]
Volunteering to be a cyborg already goes against immersion, but players do it all the time.
Box suicide streamlines borg construction and tends to get a few more live players wandering around robotics early in the round.
Organ manipulation (head cavity) still has uses. Roboticist surgical skills are in no danger of getting rusty.

Maybe I'll suggest/PR roundstart organ harvesters.
