### ISSUE TITLE
Puzzle smiting block icons are buggy

### ISSUE THREAD

**Issue by Carbonhell** [tgstation/tgstation#39801]
Happens on hippie, no code touched by us on the matter, you probably got this too
[Reproduction]: Smite someone with the "Puzzle option". The 3x3 block area will spawn, but the bodyparts icon don't appear on it. This is fixed by relogging, apparently, but it's still pretty ugly and i dunno why it happens.

**Comment by AnturK** [comment]
I heard this one before but i can't really reproduce this locally.

**Comment by octareenroon91** [comment]
Happens on my PC too, under WINE at least.

**Comment by Mooshimi** [comment]
Will cleanup tag since this hasn't been seen since 2018
