### ISSUE TITLE
APC's (and most likely other items like Air Alarms) can be interacted with by borgs when the AI wire is cut or pulsed

### ISSUE THREAD

**Issue by matkingos** [tgstation/tgstation#39811]
As stated in title, APC AI wire being pulsed does not affect borgs ability to manipulate the device, seems a bit of an unintended item.

**Comment by moonheart08** [comment]
Give borgs hands. Bug is now feature, problem solved.

**Comment by PKPenguin321** [comment]
I think borgs should still be able to use these machines when the wire is cut, just not at a range.

**Comment by AlinaStarkova** [comment]
this bug is no longer in existence, this can be closed
