### ISSUE TITLE
When you fire at the inside of a halfwindow with a honkstaff it gives the message ~1300 times.

### ISSUE THREAD

**Issue by nichlas0010** [tgstation/tgstation#39815]
Works with both regular and reinforced windows. Firing from any other side through the window doesn't matter, neither does firing at fulltile windows, to reproduce, do the following:

![image](https://user-images.githubusercontent.com/20558591/44342846-82b3d380-a48c-11e8-9a2a-59c8386c1197.png)
![image](https://user-images.githubusercontent.com/20558591/44342858-8cd5d200-a48c-11e8-8a81-aebe8a11d3b0.png)

**Comment by moonheart08** [comment]
If repeated messages didn't condense, this would be a hell of a bug.

**Comment by nichlas0010** [comment]
it still freezes you for several seconds

**Comment by kriskog** [comment]
Seems fixed
