### ISSUE TITLE
The beam rifle is UNGODLY LAGGY

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#39828]
JESUS FUCK IT'S SO BAD NOW WHAT BROKE IT AAAAAAAAAAAAAAAAAAAAAAA

**Comment by KrabSpider** [comment]
Please fix it. 

This shit will crash you to hell and back just for using the scope

**Comment by Borisvanmemes** [comment]
It doesn't seem to be as laggy anymore.
