### ISSUE TITLE
Hacked vending machines can throw stuff at hidden revenants, giving them away

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#39838]
![image](https://user-images.githubusercontent.com/38788538/44411107-7738d900-a56e-11e8-92d6-f811e6785308.png)
No, i wasn't using any abilities.

**Comment by ShizCalev** [comment]
probably also does it for jaunting wizards/constructs then

**Comment by SgtxRootbeer** [comment]
Not a bug, since most machines can 'see' revanents, such as prox sensors, motion detectors, ai turrets, etc.

**Comment by Kagus** [comment]
This also applies to other things people throw or shoot randomly. I wasn't aware that the living actually received the messages.

**Comment by zxaber** [comment]
Hidden revs don't get shot at by turrets though, right? I swear I've sent spooky messages to an AI without triggering the turrets before.

**Comment by Iatots** [comment]
If it's not a bug it must be an oversight, right? This can't be a deliberate feature.

**Comment by YakumoChen** [comment]
seems like it should be a feature, it encourages spooky things

**Comment by PKPenguin321** [comment]
yeah just close this and leave it in

**Comment by SpaceManiac** [comment]
canonizing that vending machines can detect ghosts
