### ISSUE TITLE
Bugged Metastation Disposal Pipe

### ISSUE THREAD

**Issue by ishitbyabullet** [tgstation/tgstation#39833]
Issue reported from  Round ID: 92794 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

When I first saw it, I thought it was just a funny thing where 2-3 bodies and 2 humans were stuck in it. I don't have the round ID for that. However, I saw this pipe have the exact same issue happen in the exact same spot except with only one human and a holoparasite this time. I think this disposal pipe is just fucking bugged. I'm the white ghost.
![image](https://user-images.githubusercontent.com/29403316/44394510-5a1bf000-a505-11e8-99f1-5b92edf6a7db.png)

There was another issue related to disposal loops eventually not moving anymore. It may be a general issue with disposals and not just a bug.

**Comment by 81Denton** [comment]
Woops, let me open a PR
