### ISSUE TITLE
a whole new level of adminbus

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#39846]
You can use buildmode's telekinesis to throw ghosts at stuff.
*And break stuff.*

**oh god no**

the saga of ghostbusting: https://imgur.com/a/rk5miaG
[~12mb and looks ugly af because of compression]

lite version of the gif above
![2018-08-22_00-28-05](https://user-images.githubusercontent.com/38788538/44432266-13340600-a5aa-11e8-9e74-90957c6807ce.gif)

~~this is too good to be fixed~~

**Comment by RedFoxIV** [comment]
some footage of me harassing RD
![2018-08-22_01-32-09](https://user-images.githubusercontent.com/38788538/44432584-517df500-a5ab-11e8-83a0-006c563b2458.gif)

**Comment by PKPenguin321** [comment]
not sure if you can even call this a bug, technically it's intended behavior just never normally possible

**Comment by Iamgoofball** [comment]
So i see someone finally reported the bug with admins smashing stuff and refusing to fess up. Time to fix this.

**Comment by ExcessiveUseOfCobblestone** [comment]
Seek help goofball, i'm getting concerned.

**Comment by ExcessiveUseOfCobblestone** [comment]
We don't typically make specific checks for abnormal admin tomfoolery

**Comment by Iamgoofball** [comment]
@ExcessiveUseOfCobblestone 
scared?

**Comment by ishitbyabullet** [comment]
@Iamgoofball I think it can only break windows. Nothing else.

I'm pretty sure no one uses buildmode for this anyways besides friends fucking around on a private server.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Iamgoofball yes, very
