### ISSUE TITLE
Power transmission circuits don't work on other circuits

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#39848]
[Round ID]: # 92829
{"assembly":{"type":"type-a electronic mechanism"},"components":[{"type":"power transmission circuit"},{"type":"power transmission circuit"},{"type":"power transmission circuit"},{"type":"power transmission circuit"},{"type":"tesla power relay"},{"type":"tesla power relay"},{"type":"tesla power relay"},{"type":"tesla power relay"},{"type":"tesla power relay"},{"type":"append circuit","inputs":[[1,0,["the type-b electronic assembly"]]]},{"type":"at circuit","inputs":[[1,0,["the type-b electronic assembly"]]]},{"type":"at circuit","inputs":[[1,0,["the type-b electronic assembly"]],[2,0,2]]},{"type":"at circuit","inputs":[[1,0,["the type-b electronic assembly"]],[2,0,3]]},{"type":"at circuit","inputs":[[1,0,["the type-b electronic assembly"]],[2,0,4]]},{"type":"list set circuit","inputs":[[1,0,["the type-b electronic assembly","the type-b electronic assembly"]]]},{"type":"fast ticker"},{"type":"toggle button"},{"type":"sensor"}],"wires":[[[1,"I",1],[11,"O",1]],[[1,"A",1],[16,"A",1]],[[1,"A",2],[2,"A",1]],[[2,"I",1],[12,"O",1]],[[2,"A",2],[3,"A",1]],[[3,"I",1],[13,"O",1]],[[3,"A",2],[4,"A",1]],[[4,"I",1],[14,"O",1]],[[10,"I",1],[15,"O",1]],[[10,"I",2],[18,"O",1]],[[10,"O",1],[15,"I",1]],[[10,"A",1],[18,"A",1]],[[10,"A",2],[14,"A",1]],[[10,"A",2],[12,"A",1]],[[10,"A",2],[13,"A",1]],[[10,"A",2],[11,"A",1]],[[10,"A",2],[15,"A",1]],[[11,"I",1],[15,"O",1]],[[12,"I",1],[15,"O",1]],[[13,"I",1],[15,"O",1]],[[14,"I",1],[15,"O",1]],[[16,"I",1],[17,"O",1]]]}

When transmit is pulsed, irrespective of position relative to the targetted circuit, the circuit is not charged by any amount, though power is still used by the charger.

**Comment by PKPenguin321** [comment]
Probably intentional

**Comment by Shdorsh** [comment]
I believe this was intentional, due to possible abuse.

**Comment by SpaceManiac** [comment]
Circuits have been removed.
