### ISSUE TITLE
Shunted AIs in APCs get spammed with no AI eye error messages

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#39854]
Round ID: 92835

![image](https://user-images.githubusercontent.com/12382984/44455672-86fc0000-a5f6-11e8-8353-e5d22c937773.png)

The AI also can't talk whilst in this state.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Cruix ai expert

**Comment by Anonmare** [comment]
Further details: This is a non-antag AI with a malf upgrade.

**Comment by kriskog** [comment]
This has been fixed.
