### ISSUE TITLE
Augmentation part replacement issues

### ISSUE THREAD

**Issue by Arkvold** [tgstation/tgstation#39858]
Issue reported from a personal server

Reporting client version: 512

Recent fixes implemented on Aug 18th have largely fixed issues with augmentation granting extra limbs, but there remains two issues - chest and head augmentation.

Augmenting the head does not replace the head at all.  The subject still has a flesh-and-blood head with no overt changes.

Augmenting the chest leave the flesh-and-blood chest in and creates an 'extra' chest - the cyborg torso - which causes problems.  Not only does the cyborg torso not take hits in direct combat, but if it does take damage (such as being outside during an ash-storm in lavaland), it cannot be repaired by any means since it cannot be targeted. 

You can test and reproduce these issues easily.  Below are steps:

**Unchanged Augmented Head**
1. Obtain cyborg head and patient with intact head
2. Successfully perform head augmentation surgery
3. Patient retains flesh-and-blood head and does not gain a cyborg head bodypart (viewable in admin show variables and by patient self-checking for injuries - both will show that the patient has a head and no cyborg head)
4. Patient should have lost the flesh-and-blood head object, and gained a cyborg head with all internal organs carried over from its organic predecessor

**Extra Cyborg Chest**
1. Obtain cyborg chest and patient with intact chest
2. Successfully perform chest augmentation surgery
3. Patient retains flesh-and-blood chest, as well as gaining a cyborg chest bodypart (viewable in admin show variables and by patient self-checking for injuries - both will show the Patient having a chest and a cyborg chest).
4. Patient should have lost the flesh and blood chest, and gained a cyborg chest with all internal organs carried over from its organic predecessor

**Augmented cyborg chest not taking hits in direct combat**
1. As a living, intact humanoid with an augmented chest, target your chest and punch yourself several times
2. Self-examine for injuries
3. Your chest will show bruising, but the cyborg torso will be unharmed.
4. Your chest should not exist anymore, as the augmentation surgery was supposed to replace that.  The brute damage should have been done to your cyborg torso instead.

**Augmented cyborg chest cannot be repaired**
1. As a living, intact humanoid with an augmented chest, step outside in lavaland during an ash storm in order to be set on fire
2. Put yourself out with a cold shower immediately
3. Self-examine for injuries - you should notice that your cyborg chest is scorched to some degree
4. Obtain a cable coil
5. Target your chest and in Help intent, click on yourself with the cable coil
6. You will strike yourself in the flesh-and-blood chest with the cable coil, instead of using it to repair burnt wiring in your cyborg chest.  This renders it impossible to conduct physical repairs on a damaged cyborg chest.
7. Again, the flesh-and-blood chest should not exist anymore, as the augmentation surgery was supposed to replace that.  The cable coil should have been applied to repair burnt wiring in your cyborg torso instead.

**Comment by XDTM** [comment]
it never ends

**Comment by Jord1081** [comment]
...Can you augment the chest a second time?

**Comment by SgtxRootbeer** [comment]
What does a med scanner say?

**Comment by XDTM** [comment]
No worries, it's good to know about a bug especially with such a detailed report.

I already found a fix with the chest bug, since it was coded to ignore the drop_limb proc even with replacement. 
On the other hand i'm having issues with the head augmentation bug; by reading the code involved it should technically remove the old head and insert the new one. I can't figure out where it's stopped.

**Comment by Arkvold** [comment]
I'll admit I'm terrible with code itself and haven't looked at the relevant code, but from seeing it in action in game, it seems like it never even gets to the step where the new cyborg head is added.  Not only is it not dropping the old head, but the new head isn't even added to the character.

Would I be correct to assume that adding the new head and copying over any sub-organs in the predecessor is the first step, followed by dropping the old, now-superfluous head to leave the cyborg head the only remaining one?  If so, then it's failing before that step; the cyborg head is never added to the body and it's never reaching the point where the old limb, now emptied-out, is to be dropped.

I'm going to keep poking at it myself, watching the bodypart variables change during the last step of the surgery.  If I notice anything odd that might clue you in to where in the code the implementation has gone wrong, I'll post back - watch this space for edits.

Is there anything specific you'd like me to try?

**Comment by XDTM** [comment]
It's supposed to remove the old head and insert the new one afterwards. Organs aren't affected as they're actually inside the mob and only moved to a limb after dismemberment, so we don't have to worry about those.

Something is preventing the proc from running altogether, or we'd either have no head or two heads; i'll figure out where eventually. Any more testing would require adding debug text to figure out exactly where it stops, but you don't need to go that far.

Thanks for all the info, i'll get a fix up asap.
