### ISSUE TITLE
omegastation is still in rotation

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#39855]
92841
for some reason it rolled omegastation on bagil maybe some new merge accidentally enabled it

**Comment by deranging** [comment]
![a98](https://user-images.githubusercontent.com/29786528/44473671-d21a1100-a5fe-11e8-87c6-1fbd6f094ed7.gif)

**Comment by BeeSting12** [comment]
Server config issue, not a bug.
