### ISSUE TITLE
Different emojis can stack together in OOC chat

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#39853]
it should look like this
![image](https://user-images.githubusercontent.com/38788538/44450020-83697880-a5f8-11e8-8443-9cf3d3331bbf.png)
But looks like this
![image](https://user-images.githubusercontent.com/38788538/44450026-87959600-a5f8-11e8-9a01-69ee076a2ee7.png)

**Comment by ExcessiveUseOfCobblestone** [comment]
Intents..

**Comment by ExcessiveUseOfCobblestone** [comment]
@Cyberboss @SpaceManiac I believe you guys worked on the HTML squashing

**Comment by SpaceManiac** [comment]
Easiest fix is probably to stuff the emoji's name inside its spritesheet span and make sure it isn't displayed visually

**Comment by dragomagol** [comment]
Seems to have been fixed (unable to reproduce).
