### ISSUE TITLE
rnd will keep getting research points even if round will never start

### ISSUE THREAD

**Issue by kingoftheautism** [tgstation/tgstation#39871]
Issue: If roundstart is somehow delayed (failed to initiate gamemode, admin delayed roundstart, etc) RnD will keep getting research points. Not critical since roundstart is barely delayed for more than few minutes. Mostly just oversight I guess. Maybe just rework it so RnD starts with 5000-10000 research points and will start getting them only after round start.

Reproduction: Start local tg server, delay round start for 10-20 minutes and go to toilet, drink beer or do whatever. Get your sweet points

**Comment by SpaceManiac** [comment]
easy fix, set `runlevels = RUNLEVEL_GAME` on SSresearch
