### ISSUE TITLE
Cloning pod cooldown is not visible

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39873]
It looks like `/obj/effect/countdown/clonepod` is supposed to show ghosts the cloning progress of clone pods - however, it's not visible.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/ace883a2d301152c0fd15eb56a379f5f65ede07b/code/game/machinery/cloning.dm#L44

change to `new(get_turf(src))` and see if that works

**Comment by ExcessiveUseOfCobblestone** [comment]
actually nvm one sec

**Comment by Mickyan** [comment]
The countdown does appear, it's just almost impossible to see

![countdown](https://user-images.githubusercontent.com/38563876/44542567-7e4a1d80-a70d-11e8-8b82-cdd111d18dc8.png)

**Comment by 81Denton** [comment]
Ohhh

**Comment by 81Denton** [comment]
Easy fix then
