### ISSUE TITLE
you can use VV to change taser's cell charge from whatever to a lot to crash your server

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#39878]
i just did it, what the fuck
![image](https://user-images.githubusercontent.com/38788538/44546752-8e6bf800-a721-11e8-835d-0b13b4c35935.png)
how does this even work

**Comment by XDTM** [comment]
There's a lot that you can vv to crash the game tbh, you're just not supposed to

**Comment by RedFoxIV** [comment]
I just don't really understand how overcharging one battery **makes the server ded**

**Comment by SpaceManiac** [comment]
![image](https://user-images.githubusercontent.com/222630/44556181-5fd42a00-a6ed-11e8-9d61-0aaf441aec99.png)
HMMMMMMMMMMMMM

**Comment by Jordie0608** [comment]
How much was 'a lot;?
