### ISSUE TITLE
players with traitor preference set to off can still get the role when population is low enough.

### ISSUE THREAD

**Issue by refticus** [tgstation/tgstation#39872]
Issue reported from  Round ID: 92891 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

![5c6a1727c7](https://user-images.githubusercontent.com/36165376/44522002-08be5d00-a6cd-11e8-92e3-ede3e86c4c07.png)

unsure if this was intentional when nobody else has traitor preference set to on.
player count at the time was 6, but only 3 players arrived.

reproduction should be as simple as running the secret gametype without having any traitor preferences set to true.

**Comment by AnturK** [comment]
Not a bug. It's bit confusing but gamemodes will pull people without preferences set if there's less than recommended enemies for the gamemode.

**Comment by Tlaltecuhtli** [comment]
wouldnt it be better if instead it ll wait for latejoins to give them the traitor status
