### ISSUE TITLE
Dirty tiles and plating sprite issue

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#39888]
[Round ID]: # about 92911 or so on bagil

doing it is simple as far as I can tell, just crowbar a dirty floor tile and it should pop up without the normal plate underneath it showing, I originally found out about it via incinerator/turbine
<img width="960" alt="dreamseeker_2018-08-23_14-10-10" src="https://user-images.githubusercontent.com/13891233/44564719-5fea1f00-a719-11e8-8fc6-542b6b80767e.png">

**Comment by SpaceManiac** [comment]
thanks for the report, I noticed this earlier today & just got the fix done at #39889
