### ISSUE TITLE
Creating golden bike horn does not consume regular bike horn

### ISSUE THREAD

**Issue by Arkvold** [tgstation/tgstation#39904]
Issue reported from a personal server.

Reporting client version: 512

If you use the crafting menu to create a Golden Bike Horn using a regular bike horn and 5 bananium, you also get a regular bike horn back as well as the Golden horn.  Apologies if this is intended (to ensure that the clown is never without a standard bike horn unless it's been taken from him) but it seems like it might be a bug for one bike horn to suddenly become two.

On the other hand, bananium's weird stuff.  Could be just considered a feature and I'd be totally okay with that - perhaps just include a line of dialogue text giving the indication that this is intended behavior (As a suggestion, "Honk! The bananium _senses_ the hilarity you're trying to pull off, and shapes itself into a new, golden bike horn to use alongside your trusty original one.")

### Reproduction Steps

1. Obtain 5 bananium and a bike horn
2. Open crafting menu
3. Create Golden Bike Horn
4. **Problem Behavior:** Your original bike horn is still present, even though it was an ingredient for the recipe

**Comment by XDTM** [comment]
The recipe lists `obj/item/bikehorn` instead of `obj/item/bikehorn = 1`, so it doesn't consume it; should be a simple fix
