### ISSUE TITLE
Items in right hand always appear over items in left hand

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#3990]
```
#define L_HAND_LAYER            3
#define R_HAND_LAYER            2
```

9 to 4000

**Comment by Cheridan** [comment]
...Is this actually relevant to anything? Just say that spacemen are right handed.

**Comment by Anonus** [comment]
It was a weird oddity and I wanted to see what #4000 was.

**Comment by KorPhaeron** [comment]
@Anonus 

So now that #4000 passed can this be closed?

**Comment by Anonus** [comment]
I mean, it is an issue but it probably could be unless someone was able to fix it.
