### ISSUE TITLE
sometimes the meteor shuttle takes three hours to show up, but still murders guys (with no blue circle indicators)

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#39917]
[Round ID]: # 93009

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

It was a high pop war ops round on Delta Station. Someone bought the meteor shuttle. It took ages to dock, and the blue circles warning it was about to appear were gone for a good 20 seconds before it showed up. In the meantime, people who walked unknowingly into the place it would dock were gibbed.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by SpaceManiac** [comment]
Best way to fix this would be to adjust how `remove_ripples` is called in `initiate_docking` - it should be called before each of the three the early `return`s and on successful docking the ripples should simply be left existing until they are squashed by the shuttle actually arriving.
