### ISSUE TITLE
NPC slime spoke in deadchat

### ISSUE THREAD

**Issue by TribeOfBeavers** [tgstation/tgstation#39913]
Issue reported from  Round ID: 92994 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

[2018-08-25 22:41:57.052] SAY: *no key*/(bluespace baby slime (78)) (DEAD) "Slime friend..." (Xenobiology Lab (166, 94, 2))

As far as I could tell, the slime had never been occupied by a player, but somehow still spoke in deadchat shortly after dying.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
this happens when a mob is about to say something but dies in the meantime, usually happens with bots saying things like "engaging patrol mode"

**Comment by SpaceManiac** [comment]
not a bug tbh

**Comment by coiax** [comment]
How is this not a bug? Non-player mobs shouldn't be talking in deadchat.

**Comment by SpaceManiac** [comment]
It's amusing mainly, especially if it only happens right as the mob dies
