### ISSUE TITLE
Immortality Talisman is immortal... at least as far as its own destruction is concerned.

### ISSUE THREAD

**Issue by Arkvold** [tgstation/tgstation#39938]
Issue reported from a round on a personal server

Reporting client version: 512

The Immortality Talisman, obtained from generic lavaland chests (Necropolis Tendril, Legion megafauna partial kill, etc.) cannot be deleted by any known means.  Throwing it through the recycler in disposals does nothing to it (and it'll get spaced soon after), no form of damage can destroy it, lava exposure doesn't do anything to it, and even hitting it with an admin's delete object command doesn't work.

### Reproduction Steps:

1. Obtain Immortality Talisman.
2. Throw Immortality Talisman into disposal bin.
3. Ensure that it reaches the recycler in maint by turning on the conveyor in Cargo's delivery office
4. **Problem Behavior:** _Recycler cannot destroy the Immortality Talisman.  It will continue down the conveyor past the recycler and be spaced via mass driver._
5. Retrieve the Immortality Talisman.
6. Go to the Mining Base EVA on Lavaland.
7. Toss Immortality Talisman out into lava.
8. Wait for ash storm.
9. **Problem Behavior:** _The lava and ash storm should at least deal damage to the talisman, if not reduce it to ash.  It doesn't.  The talisman is thoroughly immune to any form of heat._
10. Retrieve Immortality Talisman once storm concludes.
11. Obtain spray bottle filled with fluorosulphuric acid.
12. Place Immortality Talisman on floor.
13. Spray thoroughly with acid bottle.
14. **Problem Behavior:** _Fluorosulphuric Acid is what cleanbots use to destroy corpses, and it's known for its destructive properties.  It's not enough to reduce an Immortality Talisman to an acidic sludge pile, though - even when its obj_integrity variable hits zero, it remains, although it does leave a gooey gray mass that, on examine, says it was once an Immortality Talisman._
15. As an admin, right-click Immortality Talisman.
16. Choose "Delete" from the fly-out menu.
17. Note that the admin log will record a deletion of the object.
18. **Problem Behavior:** _Not even an admin delete command will get rid of the immortality talisman.  You're not left with an acid-soaked object that burns your hand to touch it and cannot be destroyed by even the most extreme measures!_

**Comment by XDTM** [comment]
Intended! The immortality talisman has tge same deletion immunity the nuke disk has, as a gimmick. Being immune to admin deletion is a bit much, but it shouldn't be disruptive.

**Comment by Arkvold** [comment]
Ah.  Well, the talisman certainly lives up to its name.  While being immune to admin-delete isn't terribly disruptive, it is a bit irritating.  I wound up littering the station with them when I decided to spawn a ton of necrotendril chests just to see what the loot pool looked like in practice.  I like being able to use delete to clean up my messes, though I'll readily admit that this situation's well outside the bounds of normal behavior for a round.

Though, there's a question - wouldn't losing obj_integrity from fluacid and leaving behind sludge be unintended behavior, then?  It also results in a permanently acid-coated talisman; since the acid has no more obj_integrity to eat, it remains on the talisman permanently and will burn the hands of anyone who touches it.

I'm going to keep futzing with it and see if there's any way I can cheat the system and cause it to get destroyed without resorting to admin commands.  Now that I know that it's indestructibility is by design, I know that I should be testing _against_ it.

**Comment by Poojawa** [comment]
hello, there is actually a bigger problem with this.

You can re-sell it over and over via cargo.
