### ISSUE TITLE
Logging for nanites "Forced Speech" program

### ISSUE THREAD

**Issue by Arianya** [tgstation/tgstation#39931]
Currently the Investigate log for Nanites shows that someone has uploaded a "Forced Speech" program to the cloud but doesn't log what speech was included as part of the program.

As there's no easy way to differentiate nanite speech from real speech in logs, this is fairly important to have amended.

**Comment by Arianya** [comment]
@Cyberboss since nanites was originally your project. Apologies if pinging you isn't appropriate.

**Comment by XDTM** [comment]
Alright, i'll see if i can make logs more specific

**Comment by Arianya** [comment]
Derp, sorry about that cyber, I get you two confused because of your avs.

**Comment by Cyberboss** [comment]
The irony of that statement is lost to the ages
