### ISSUE TITLE
Caks remove filling from jelly-filled donuts that they've frosted

### ISSUE THREAD

**Issue by Arkvold** [tgstation/tgstation#39939]
Issue reported from a round on a personal server

Reporting client version: 512

If you lay a jelly-filled donut next to a cak to be frosted, the cak will indeed frost the donut, but will also strip it of its jelly filling.  The item goes from being a jelly-filled donut to a frosted donut, despite the fact that frosted jelly-filled donuts are an item that exists.

Diabolical!  I _knew_ these feline confections were products of the culinary dark arts!

### Reproduction Steps:

1. Obtain unfrosted jelly-filled donut
2. Locate cak
3. Place unfrosted jelly-filled donut on the ground next to cak
4. Wait 1-5 seconds
5. **Problem Behavior:** _The jelly-filled donut becomes a frosted donut, instead of a frosted jelly-filled donut_

**EDIT:** Examining the problem further, I've noticed a couple things.  One; frosted donuts and frosted jelly donuts are not separate items from their normal counterparts, at least if the admin create item menu is to be believed.  Spawning any donut has a chance at random to produce the frosted variant instead of the normal one.

Interestingly, donuts that used to be jelly-filled prior to caks frosting them still have the description of "You jelly?" - which was their description as jelly donuts prior to frosting.  They stack, however, with normal frosted donuts if placed into a food cart, indicating that the game regards them as the same item.  Food carts track jelly donuts and frosted jelly donuts separately.

Examining the variables of jelly donuts that have been converted to unfilled frosted donuts, they actually retain the jelly reagent, and the jelly taste, and are still being defined as obj/item/reagent_containers/food/snacks/donut/jelly.  They're just using the standard frosted donut sprite and name, which seems to be what's causing them to both look like and stack with typical frosted donuts instead of their jelly-filled brethren.

**Comment by XDTM** [comment]
Frosting donuts, as you've noticed, is done by editing the donut's vars instead of creating a new forsted donut. In the cak's case, the varedit effectively overrides the donut's name with "frosted donut" regardless of its type, along with the icon, and adds some sprinkles in its reagents. Everything else is left as is, which means that description and extra reagents should stay the same.
