### ISSUE TITLE
TODO: Remove all map_change.dm files and refactor what they do into the map jsons

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation#39933]
Eventually we want to be able to load maps solely from the .json and .dmm at runtime alone

Will pay 10$USD if someone else does this

**Comment by pubby** [comment]
If omega goes there isn't a need for .dm map files anymore. PubbyStation is the only other map with one, and it's just for giving security officers cremator access (which can instead be done in the map file itself).

**Comment by Cyberboss** [comment]
I'd still like to maintain support for the multitude of things Omegastation
currently does. Ie changing spawn counts, default accesses, and other job
fields.

**Comment by spookydonut** [comment]
long since done, apparently

**Comment by spookydonut** [comment]
Nope I was lied to
