### ISSUE TITLE
Breaking down a bonfire doesn't always return the materials used to make it

### ISSUE THREAD

**Issue by Arkvold** [tgstation/tgstation#39945]
Issue reported from a round on a personal server.

Reporting client version: 512

If you construct a bonfire from Steelcap mushroom logs, but then break it back down to its components by clicking it with an empty hand, you'll get Tower Cap logs back.

### Reproduction Steps:

1. Obtain 5 steelcap logs
2. In your crafting menu, under the Tribal heading, construct a bonfire
3. With an empty hand, click the bonfire you just constructed
4. **Problem Behavior:** _You'll get 5 tower cap logs instead of the steelcap logs you used to make it._

Not sure if the problem here is a consistency issue (steelcaps go in on construction, steelcaps don't come back out on disassembly), or the fact that non-tower cap logs can be used for this in the first place.

**Comment by ExcessiveUseOfCobblestone** [comment]
Probably the latter

**Comment by octareenroon91** [comment]
Logs are deleted. Default tower-cap logs are spawned on teardown.

Please keep as is - this is a convenient way to get decent tower-cap seeds.

**Comment by kriskog** [comment]
Making a bonfire out of steel is dumb. Should probably restrict the bonfire crafting to tower caps only.
