### ISSUE TITLE
Gray crossbreed extracts refuse to be fed from xenobio bags

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#39948]
![image](https://user-images.githubusercontent.com/38788538/44674349-e6fb0800-aa35-11e8-97c6-a9209efcc036.png)
![image](https://user-images.githubusercontent.com/38788538/44674404-0b56e480-aa36-11e8-8ee7-2fb4651ca253.png)

i thought this was fixes ages ago
why

**Comment by ExcessiveUseOfCobblestone** [comment]
@fludd12

**Comment by fludd12** [comment]
Aaaaaa Kevin's just fixed this what the fuuuuck

**Comment by Angustmeta** [comment]
This works now and has been for some time. Issue can be closed.
