### ISSUE TITLE
Wizards don't spawn with equipment needed for objectives

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#39947]
Round ID: 93077
When you spawn as the wizard, you don't get any equipment except the default one and your family heritage, which means if you got near sightedness you don't get prescription glasses and if you got a nuke core or a supermatter sliver objective you do not get items needed to do those objective
Reproduction:
Become a wizard with one of those two objectives

**Comment by XDTM** [comment]
A nice twist on it would be giving the wiz specialized spells instead
