### ISSUE TITLE
Objective #1 Set to Nothing in Overthrow

### ISSUE THREAD

**Issue by Montyblancs** [tgstation/tgstation#39960]
[Round ID]: # 93096 (Bagil)

[Testmerges]: #39876 : '[READY] Overthrow gamemode'
#39556: 'Adds move force and move resist, movement/pushing/pulling tweaks'

[Reproduction]: On round start, I received the team name prompt after about 5-10 seconds. After naming (Team name was "Mean Lean Syndie Machine"), I received my objectives, and found that the first one was simply "Nothing." The first objective should be converting/exiling/killing the heads of staff.

I left the notes window open to keep an eye on the objectives, but I'm not sure if the objectives fixed themselves when I converted the AI as I didn't refresh the notes page. I think the objectives update to list the AI as a conspirator. An Admin replaced the first objective after being asked about it after this.

[Additional Details]: Byond ID : Montyblancs. Was playing a moth janitor named "Peach Fuzz"

**Comment by SpaceManiac** [comment]
@Carbonhell

**Comment by Carbonhell** [comment]
I tested the bug in local by starting as an overthrow agent and then later joining as captain on another account, and i could only reproduce it by leaving the note window open. But, if you close and reopen it, it updates correctly. have you tried to just close and reopen notes? Keep in mind the objective updates every 30 seconds.

**Comment by SpaceManiac** [comment]
@Carbonhell It might be advisable to give a descriptive message mentioning *future* heads of staff instead of simply "Nothing". I think most players don't expect their objectives to change w/o a chat message saying so.

**Comment by Carbonhell** [comment]
Done. Can be closed, thank you.
