### ISSUE TITLE
Pulling Someone and Flinging Them Sideways Will Phase Over Windoors

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#39961]
[Round ID]: 93101

[Testmerges]: 
#39876: '[READY] Overthrow gamemode' by Carbonhell at commit d5f38bc065 
#39556: 'Adds move force and move resist, movement/pushing/pulling tweaks' by kevinz000 at commit ba97ee29f4 

[Reproduction]: This is difficult to explain, and I suspect it will be difficult to replicate, but a player was pulling me inside the cargo office (conveyor belt room), and pulled me in such a manner that I was quickly transferred from south of the player to west of the player. This placed me inside of a windoor that was not opened.

Another player may have pushed us at the same time, it was difficult to discern as it was rather chaotic.

**Comment by kevinz000** [comment]
uyhhhhhhhhhhhhhhhhhhhhhhh

**Comment by msgerbs** [comment]
I see this still had needs reproducing, has anyone else seen this happen? I don't think I ever have.

**Comment by Sealed101** [comment]
i can't say i've witnessed anything close to this happen, could have just been a one-time oldbug
