### ISSUE TITLE
Lavaland puzzle ruin can spawn near lava, destroying part of it

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39963]
![xxxxxx](https://user-images.githubusercontent.com/32391752/44709254-71c91a80-aaa9-11e8-8df8-5cb99e2b265a.PNG)

**Comment by AnturK** [comment]
You sure it wasn't someone with lava staff getting angry ? Ruins should override whatever they're placed on top of anyway.

**Comment by 81Denton** [comment]
I can't actually say that. I think I'll close this until it happens again.
