### ISSUE TITLE
Industrial silver slime extracts can create invisible items

### ISSUE THREAD

**Issue by DfourC** [tgstation/tgstation#39974]
Round ID 93116, while injecting an industrial silver slime with plasma it occasionally created an item called "drink" or "soda can" with no sprite. Both have the description "yummy" and appear to be reagent containers. 

To replicate, I assume just inject an industrial silver slime extract and cross your fingers.

**Comment by ExcessiveUseOfCobblestone** [comment]
wonder if it's calling the base

@fludd12

**Comment by octareenroon91** [comment]
Looks like the following parent-types are likely to get picked atm:

````
/obj/item/reagent_containers/food/drinks/soda_cans
/obj/item/reagent_containers/food/drinks/bottle
````
