### ISSUE TITLE
Camera bugs do not work

### ISSUE THREAD

**Issue by ModDownloading** [tgstation/tgstation#39975]
Trying to use a camera bug opens up a blank window instead of a list of cameras or camera view as it should. The bug can still be used on security cameras and will display "Camera Bugged" when it is used, but interacting with the camera bug item still only shows a blank window.

**Comment by Angustmeta** [comment]
The camera bug seems to work now. At least it does on my private server.

**Comment by Angustmeta** [comment]
Okay so, camera bug works on private server but not on live servers, it seems.

**Comment by KetasDotepasto** [comment]
I tried to fix this as well, bug also doesn't manifest on my private server.

**Comment by Angustmeta** [comment]
Seems to work live now. At least on Terry. Someone else confirm please.

**Comment by SuperNovaa41** [comment]
I think it works...

**Comment by timothymtorres** [comment]
Alright so I tested this live with the help of admin AtexHoffman69 and there were no problems:

![yNJpjB5mSX](https://user-images.githubusercontent.com/5195984/146607718-df9a9076-38db-46ac-9076-6cde478b85c0.png)
