### ISSUE TITLE
All cyborg modules have footsteps

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#39970]
All cyborg modules have footsteps - whether they're hovering (medical, sec, syndie), on threads (engineering, mining) or wheels (janitor, peacekeeper, clown).

It only really makes sense for standard and service bots to have footsteps.

**Comment by Ratvar** [comment]
feet module

**Comment by 81Denton** [comment]
no fetish content

**Comment by octareenroon91** [comment]
This is kind of a sprites issue. The Kent model of the service borg also hovers, doesn't it?

**Comment by kriskog** [comment]
Fixed ages ago
