### ISSUE TITLE
Wet floor proceed been wet and slippery infinity

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#39978]
[Round ID]: # Round ID: 93121
[Round ID]: # Round ID: 93121
[Round ID]: # Round ID: 93121

[Reproduction]: # 
1. Wet floor with water or shower.
2.Wait.Wait.Wait.Wait.
3. Slip.
in addition i think its this code breaks all is new and problem doesnt appers yesterday but im not sure
https://github.com/tgstation/tgstation/commit/0943e56e0830dba1aeb6e7a7ceca8339387520aa#diff-e627ef703b98845c990169996cb24818

**Comment by octareenroon91** [comment]
Advised to tag PRs and not just commits.

 #39861 @vuonojenmustaturska

**Comment by octareenroon91** [comment]
Round ID 93157: 
Splashed the floor with water at round time 16 minutes.
Slip at round time 23 and 24 minutes - server time 12:13

**Comment by octareenroon91** [comment]
Also moodlets persist. An hour after I slip on these floors, I still have the "oops I slipped" moodlet.
