### ISSUE TITLE
Mech's camera for AI

### ISSUE THREAD

**Issue by Archemagus** [tgstation/tgstation#39980]
Hi there! I need camera in this big daddy, cause AI can control exosuit in maints, but can't see anything (and use middle-mouse (exo's action button) onto blind tiles, so no fire in the dark) 
![image](https://user-images.githubusercontent.com/32466328/44747792-ad4dfe00-ab16-11e8-8a9e-57453f9c1079.png)

**Comment by Anonmare** [comment]
Reconnect to fix the static. 

It's been a bug since forever, but mechs sorely need a camera cause if that bad boy is in static and you eject, it's gone forever as far as you're concerned

**Comment by Sealed101** [comment]
forgot to link this issue/request when i made #71392 lol whoops
