### ISSUE TITLE
Going through disposals with the stealth box enabled will kick you out of the tube when you hit a wall

### ISSUE THREAD

**Issue by TribeOfBeavers** [tgstation/tgstation#39984]
Round ID: 93151

Server revision compiled on: 2018-08-28

The following pull requests are currently test merged:
#39973: 'Comfy computer lighting and a vis_contents overlay system foundation' by ninjanomnom at commit 484fcf4e14
#39876: '[READY] Overthrow gamemode' by Carbonhell at commit d5f38bc065
#39556: 'Adds move force and move resist, movement/pushing/pulling tweaks' by kevinz000 at commit ba97ee29f4

Based off origin/master commit: d0c5ad6b6f

Revision: 9142996a2acde4a18f484abbfee408b90730ad28

Pretty much what it says. Upon "running into" a wall (trying to pass under it) while in disposals with the box enabled you will get dumped out on the floor above the pipe.

**Comment by octareenroon91** [comment]
I'm guessing this has to do with the stealth toggle. The box seems to drop the user to a turf and delete itself, which would get the user out of any `/obj/structure/disposalholder` they should be staying in.
