### ISSUE TITLE
Lava does not burn objects

### ISSUE THREAD

**Issue by frayedition** [tgstation/tgstation#39981]
I burn and things don't burn, like plasma and ore and stuff like that.

**Comment by frayedition** [comment]
fix this please

**Comment by kingoftheautism** [comment]
Just to let you know guys, we both playing on same /tg/ based server that wasn't merging for like month for specific reason (host isn't home so he cannot merge), and it's probably was neither already fixed or only our-side issue

**Comment by DfourC** [comment]
This is the same issue as #39066

**Comment by SpaceManiac** [comment]
Duplicate of #39066
