### ISSUE TITLE
Intelligence Potions don't always give ghosts notifications

### ISSUE THREAD

**Issue by AnActualDog** [tgstation/tgstation#39987]
Sometimes when you offer an intelligence potion from Xenobiology to a mob the ghosts, even though there are several around, don't recieve the notification. I didn't realize this until I myself was a ghost and watched, together with other ghosts, as a Xenobiologist tried to offer int pots to mobs but none of us got the notification. I then was able to reproduce that bug next shift, I asked the ghosts OOC if they get the notifications and they said no. Which explained a lot for me, since I was wondering why, during shifts where clearly there were many ghosts around noone wanted to accept the potions for whatever mob I tried.

The consequence is that Xenobiology loses its biggest "support factor", since being able to add very robust monsters to the staff (ideally tell them to act as security) can turn shifts around relatively easily. Not to mention that it allowes ghosts without (accessable) bodies to play again, saving them from boredom.

The problem is reproducing / working around the issue. I have no idea what causes it, but I did find some hints. It appears that if there is one ghost having this issue others usually have it as well. Using different mobs or a new potion doesn't seem to help either. But usually, if I wait a decent while, it suddenly starts working again during the same shift - I suspect that its because a new ghost appeared that doesn't have the issue, while the others still have it, though. Also, I of course double checked if I, as a ghost, just had the notification set to ignore, but this was not the case. I also checked if this problem also spreads to golems since maybe it's not just the int potion, but all mobs that need to be entered by ghosts, but they seem to be working as intended.

Sorry to bother you with this, I know it's not a whole lot of info to work with to solve this issue, but it really bugs me as it makes my currently favorite job much less efficient.

**Comment by XDTM** [comment]
Could be related to a gameplay preference

**Comment by AlexTheSysop42** [comment]
The pref is the same as for xenos (be xenomorph or something like that), turn that on and try again

**Comment by AnActualDog** [comment]
Whew. Thanks for telling me. But... Isn't it a little bit questionable that anyone who doesn't want to be a xenomorph can't play as a gold mob? It's not like they get forced when an int pot is offered. Could this be changed? Kinda sucks for anyone who doesn't know.

**Comment by XDTM** [comment]
Could probably use more clarity, but xenomorph is always optional in any case

**Comment by AnActualDog** [comment]
I don't criticize a lack of clarity, I'd say that's an integrated part of spessmans, many thing are not clearly spoonfed to the player and he just has to figure it out. I would draw a line at clearly misleading the player though. Unless I am onto some very dark conspiracy here, there is a difference between playing as a Xenomorph and playing as Ian with an Int-Potion. And last time I checked, Xenomorphs don't disguise themself as pets. Plus this "misunderstanding" directly affects the crews strength every shift so it's a balance issue, too. Maybe I'm being a bit nitpicky here, it's nothing gamebreaking, but I'd argue this could use a little fixing.

**Comment by XDTM** [comment]
This is exactly what i meant by clarity, i agree it's worth fixing
