### ISSUE TITLE
use launchpad as a ghost-repellent

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#39989]
Step one: get a BoH and wear it.
Step two. Use a launchpad.

Ghosts get teleported to where you should get without a bag of holding and you get teleported ~~into space~~ somewhere else

**Comment by ExcessiveUseOfCobblestone** [comment]
lol emergent gameplay to counter ghosting

**Comment by davethwave** [comment]
New stealth wizard tactics.

**Comment by 81Denton** [comment]
Iirc this also happens with hand teleporters

**Comment by Rhials** [comment]
![issue solved](https://github.com/tgstation/tgstation/assets/28870487/9ef29add-fd64-488d-83b7-96ee85d4c285)

Looks like this one has resolved itself.
