### ISSUE TITLE
why do explosions take a fucking year

### ISSUE THREAD

**Issue by AlcaroIsAFrick** [tgstation/tgstation#39999]
just do a explosion and see how fucking slow it is

**Comment by GunHog** [comment]
Explosions do a lot of things while processing, and it is done as a low priority. Previously, a large explosion *halted everything else*, so the game would essentially freeze until it completed.

**Comment by optimumtact** [comment]
useless report

**Comment by AlcaroIsAFrick** [comment]
are you fucking kidding me how is that a useless report explosions are supposed to be instant not take like a million years to copmlete how can't it be done

**Comment by optimumtact** [comment]
we are aware of the delays on explosions but we prefer to delay the explosion rather than all 60 people online.

This report offers no actionable data that can lead to improvements, it doesn't do anything other than criticising a decision made for good reasons without offering any alternative.

**Comment by AlcaroIsAFrick** [comment]
var/explosion_acts = 0
proc/explosion_delay()
        explosion_acts += 1
	if(explosion_acts > 6 || world.cpu > CPU_CHECK_MAX)
		sleep(world.tick_lag)
		explosion_acts = explosion_acts = 0

literally

just throw that in the code that does ex_act

**Comment by optimumtact** [comment]
https://github.com/tgstation/tgstation/blob/master/code/datums/explosion.dm
