### ISSUE TITLE
When the clown car released foam after getting hit, it gives an odd chat message

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#40001]
"The clown car spews out a ton of space lube!/span>/span>"

**Comment by optimumtact** [comment]
@Qustinnus

**Comment by ExcessiveUseOfCobblestone** [comment]
i was hoping it was going to be like the your belly is round message

**Comment by Qustinnus** [comment]
already fixed in my pr

**Comment by Qustinnus** [comment]
@optimumtact can be closed
