### ISSUE TITLE
I'm a dirty smelly hippie

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/tgstation#40000]
![https://i.imgur.com/U5CDbNd.png](https://i.imgur.com/U5CDbNd.png)

**Comment by AlcaroIsAFrick** [comment]
damn daniel

**Comment by praisenarsie** [comment]
Fight me.

I expected @Cyberboss to use a bot again, guess he didn't have anything in store.

**Comment by praisenarsie** [comment]
Fun fact, this is the only -0000 milestone that is an issue. The last three were PRs.

**Comment by Pacmandevil** [comment]
>white theme

**Comment by Cyberboss** [comment]
User was banned for this post

**Comment by alexkar598** [comment]
im important and part of history
