### ISSUE TITLE
Supermatter Doesn't Log Feeding it Effectively

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/tgstation#40013]
![image](https://user-images.githubusercontent.com/7583891/44859153-79382180-ac6b-11e8-9723-c2f9eaa7a676.png)

We encountered an issue today where it seems to me like someone may have intentionally detonated the supermatter, but neither Nervere nor myself had enough information to figure it out.

What we need is "the supermatter crystal has consumed the extended-capacity emergency oxygen tank, last touched by [ckey]

That way even after the item has been deleted, we can figure out who may have fed it and track it to their logs. Please fix.

**Comment by Tlaltecuhtli** [comment]
the supermatter ate the logs

**Comment by ExcessiveUseOfCobblestone** [comment]
Good first issue tbh
