### ISSUE TITLE
the bean rifle

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#40028]
![thunderdome-dudos](https://user-images.githubusercontent.com/38788538/44909722-160cc480-ad29-11e8-9510-3d86ad0121d8.gif)
it lags for everyone

nice job at creating the meme cannon

![fuck](https://user-images.githubusercontent.com/38788538/44909536-718a8280-ad28-11e8-81c2-d145620c5886.gif)
it can also open unlocked closets

**Comment by Poojawa** [comment]
@kevinz000 

FIX YOUR BROKE ASS SHIT

**Comment by ma44** [comment]
probably fixes #39828
