### ISSUE TITLE
Proxy-igniter and laser-igniter grenades do not function

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#40034]
Grenades made from a proximity sensor-igniter or a infrared laser-igniter assembly do not function properly and cannot be triggered by the expected means. These assemblies function fine when not in a grenade, and the laser grenade did not shine its laser even when set to visible.

**Comment by Vidiveni** [comment]
Also the infrared laser assembly can not be rotated after attached to an igniter, so it always points south.

**Comment by ShizCalev** [comment]
@AnturK

**Comment by WarRage333** [comment]
Cmon bruh prox nades been broken for years now

**Comment by TheBonded** [comment]
better documented in https://github.com/tgstation/tgstation/issues/63328
