### ISSUE TITLE
buttpics pop up window

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/tgstation#40032]
![image](https://user-images.githubusercontent.com/701959/44924960-47829180-ad23-11e8-8407-90bf4494438a.png)

----
----
----

![image](https://user-images.githubusercontent.com/701959/44924932-333e9480-ad23-11e8-8a9a-ca4b361a0877.png)

two things, first they open extremely tiny and I have to manually expand them, second, I don't have any option to actually close them

**Comment by RedFoxIV** [comment]
intended feature
you can't close a butt window unless it wants so.

**Comment by PKPenguin321** [comment]
happened to me too but didnt report it since i thought it was a one-off thing

**Comment by Ratvar** [comment]
"NIGHTMARES!!!"

**Comment by ShizCalev** [comment]
cannot repo, byond issue?

**Comment by ShizCalev** [comment]
![image](https://user-images.githubusercontent.com/6209658/46330179-a1ef6600-c5df-11e8-833d-532b7d4385eb.png)

**Comment by PKPenguin321** [comment]
I feel like kev fixed this but maybe forgot to autoclose this issue
@kevinz000 ? Pretty sure you PRed a fix

**Comment by ShizCalev** [comment]
fixed by #40041
