### ISSUE TITLE
vehiclecode + clown cars

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#40075]
yes I know I coded this stuff (not clown car but vehiclecode) and I can and should fix it but I'm putting it here while I'm still too busy.
1. people inside the clown car are apparently deleted when it breaks. 
2. clown car is able to freely spacepropel. thought that was left for speedbikes.
3. clown cars are environmentally exposed meaning it's very easy to camp airlocks and bring people outside to kill them. this may or may not be an actual bug, might be a feature? @Qustinnus 
4. clown cars are able to be hit from the inside. i do not think this is an intended feature, especially if 3 is deemed to be a feature. 
5. crash mechanics might need to be broadened from just walls.

**Comment by Qustinnus** [comment]
1. Should be fixed in new pr I hope?
2. How prevent? 
3.not intended but what do you think is better? The clown could always dump the people outside which might make it easier if it's not environmentally exposed 
4. Is fixed in my pr
5. Was originally in but people whined at i kept it at walls.

**Comment by ATH1909** [comment]
Wait, so clown cars don't crash when they hit an airlock?

**Comment by Iamgoofball** [comment]
>clown car is able to freely spacepropel

make sure this is behind a var lock so I can make space truckers someday
