### ISSUE TITLE
Legion core removes Depression from Traits

### ISSUE THREAD

**Issue by Mey-Ha-Zah** [tgstation/tgstation#40083]
Issue reported from  Round ID: 93408 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Tried out the depression Quirk and went mining, during which I got a booboo so I had to use a legion core to heal it. One heal up later, my guys face goes green, so I click it. Turns out, Legion core removed my depression, leaving my guy rather pleased.

**Comment by octareenroon91** [comment]
You're aware the sadness of depression comes and goes, right?

**Comment by Arianya** [comment]
This originates from the fact that a legion core is functionally an adminheal.

**Comment by Arkvold** [comment]
Adminheal/Legion Core also permanently removes the HULK SMASH! negative moodlet from Hulks.  Unlike Depression, the HULK SMASH! moodlet is not meant to go away unless you get rid of the mutation.

**Comment by SpaceManiac** [comment]
If the depression eventually comes back, I'm happy to consider this not a bug; adminheal and therefore legion core is intended to cure negative moodlets (however silly it may be for legion core to use adminheal).

**Comment by bgobandit** [comment]
just rewrite the text to make it say "you get a mood boost" and boom instant feature

**Comment by bgobandit** [comment]
also please send me some legion cores I could use this shit

**Comment by SpaceManiac** [comment]
As described in https://github.com/tgstation/tgstation/issues/40110#issuecomment-419602360, the depression moodlet comes and goes for the duration of the depression quirk. The adminheal does not actually permanently remove the moodlet, but only temporarily alleviate it, which is sensible, so this isn't a bug.
