### ISSUE TITLE
unconnected decal floor tile in meta mining dock

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#40098]
http://take.ms/aRHWv

**Comment by WJohn** [comment]
Not actually me, this occured on terry where the testmerge isn't happening. Just a regular mapping error.

![](https://i.imgur.com/05pHavh.png)

**Comment by miniusAreas** [comment]
Will attempt to fix in a pr fixing several map issues with meta. Hopefully.
