### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by KangTut** [tgstation/tgstation#40094]
[Round ID]: # 93435

[Reproduction]: # I noticed a missing texture tile in the circuit lab during the last few rounds I've played and just saw the clown ruin during the round listed.

![missingtexture](https://user-images.githubusercontent.com/40474088/45025198-78ebad80-b000-11e8-98e7-534a9fdb0cf9.png)

![missingtextures2](https://user-images.githubusercontent.com/40474088/45025204-7ab57100-b000-11e8-90de-4d59f8c31873.png)

Sorry if the format is wrong;  I  don't do these bug reports often.

**Comment by AnturK** [comment]
@WJohn

**Comment by WJohn** [comment]
These were using icon states for some fucking reason. My script didn't cover these, but I'll fix them up manually.

**Comment by SpaceManiac** [comment]
Caused by the #40065 testmerge, the issue has now been fixed in the PR
