### ISSUE TITLE
Alien screwdrivers don't appear on the toolbelt sprite when placed into a toolbelt

### ISSUE THREAD

**Issue by Arkvold** [tgstation/tgstation#40090]
Issue reported from a round on a personal server

Reporting client version: 512

Unlike all other screwdrivers, alien screwdrivers do not appear on a toolbelt's sprite when placed in a toolbelt.

### Reproduction Steps:

1. Obtain alien screwdriver and toolbelt
2. Place alien screwdriver into toolbelt
3. **Problem Behavior:** _alien screwdriver doesn't show up on the toolbelt's sprite_
4. Obtain any other screwdriver
5. Replace alien screwdriver in toolbelt with the screwdriver you just acquired
6. **Correct Behavior:** _the screwdriver appears on the toolbelt's sprite_

Toolbelt sprite with regular screwdriver:
![image](https://user-images.githubusercontent.com/27884105/45008645-d7e5fe00-afd1-11e8-9720-e4b3cc400e6f.png)

Toolbelt sprite with alien screwdriver:
![image](https://user-images.githubusercontent.com/27884105/45008749-5347af80-afd2-11e8-8d71-79ed07349b11.png)

**Comment by ATH1909** [comment]
Seems like more of an oversight to me, although I haven't checked the code.
