### ISSUE TITLE
Responding to "IRC ahelps" (ahelps sent via discord bot) isn't working

### ISSUE THREAD

**Issue by Arianya** [tgstation/tgstation#40093]
**Round ID:** #93433

**Issue:** Ahelps sent to players via the Discord bot cannot be replied to. They are treated as being "resolved" automatically, and thus block response.

**Reproduction:** 

- Utilizing one of the discord bots (Mr Bagil, Mrs Sybil, etc), send an ahelp to a player/deadminned admin via the `ahelp` command.
- Player should attempt to respond to it by clicking on the string of numbers where you would normally have an admin name

**Expected Outcome:** A textbox is prompted to fill in a response, and then when OK is hit the message is sent back to discord via the bot.

**Actual Outcome:** A textbox is not generated and a message is given to the player regarding the ticket being resolved and not open to further replies.

**Notes:** As this makes it impossible to deal with tickets/gameplay questions/etc from discord this is fairly high priority from an administrative point of view.

**Comment by BeeSting12** [comment]
lol log into the server

**Comment by dragomagol** [comment]
Appears to have been fixed
