### ISSUE TITLE
chemistry floor in meta is mapped wrong

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#40095]
http://take.ms/xEIW3

dont tell me its intended

**Comment by WJohn** [comment]
It's intended.
![](https://i.imgur.com/urVoP6x.png)

**Comment by Arkvold** [comment]
Someone stole your chem dispenser while you weren't looking.  Probably either the botanist or barman.

**Comment by SpaceManiac** [comment]
looks intended to me
