### ISSUE TITLE
Nanite cloud dun work

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#40104]
As title says, nanite cloud doesnt work, if you put a disk into cloud controller and press upload from disk, it makes a sound but the program does not appear on the list

**Comment by GuyonBroadway** [comment]
This is in spite of the supposed fix.

**Comment by GuyonBroadway** [comment]
Ok so I tried again live both hippie and tg and its fixed. Musta been some oddness going on.

**Comment by Tlaltecuhtli** [comment]
its the same effect as before but it happens less frequently

**Comment by XDTM** [comment]
i must've missed some add_program then

**Comment by XDTM** [comment]
Has this been reproduced again?

**Comment by Vidiveni** [comment]
Seems 20 is the max amount of programs you can upload to a cloud. Maybe it was that?
