### ISSUE TITLE
nanite cloud/public nanite issue

### ISSUE THREAD

**Issue by ahkent** [tgstation/tgstation#40108]
Issue reported from  Round ID: 93466 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

nanite cloud controller won't allow changes to backups, and public nanite chamber just doesn't function at all once built.

**Comment by XDTM** [comment]
was the public nanite chamber built under a glass window?

**Comment by ahkent** [comment]
it was one tile south of a glass window. the tile it was on had a floor,
other than the public chamber.

**Comment by XDTM** [comment]
Yeah, it's an issue with windows, they count two tile high objects as being underneath them even if their turf is one tile south

**Comment by XDTM** [comment]
I know about the issue, but i don't know what is causing it this time

**Comment by ahkent** [comment]
good luck
