### ISSUE TITLE
PDA messages do not respect if their target is on a comms-enabled z-level or not

### ISSUE THREAD

**Issue by cinder1992** [tgstation/tgstation#40101]
[Round ID]: # 93409 (I think, may have been the round before or after on Sybil)

[Reproduction]: # Send a message to a PDA on a z-level that has no relay, the message will be received by the target, but the target will not be able to reply.

**Comment by SuperNovaa41** [comment]
I'm like 99% certain this isn't an issue anymore. It just won't send the message.
