### ISSUE TITLE
Immortality Talisman can be resold over and over again for credits via cargo

### ISSUE THREAD

**Issue by Arkvold** [tgstation/tgstation#40115]
Issue reported from a round on a personal server

Reporting client version: 512

Related to #39938, with credit to @Poojawa for initially pointing it out.  I simply made this issue to get attention to the problem and provide detailed reproduction steps.

The Immortality Talisman, due to its coding that prevents its destruction by any known means, cannot be properly sold via Cargo like other Lavaland artifacts.  If sold, you will receive credits as normal, but the next time you call back the Cargo shuttle from CentCom, the Immortality Talisman will be on it, right where you left it, and it can be resold again and again, _ad infinitum_.

### Reproduction Steps:

1. Obtain an Immortality Talisman
2. Return the Immortality Talisman to the station proper
3. Use the Cargo Shuttle Console to request the delivery shuttle from CentCom
4. Wait for the delivery shuttle to arrive
5. Place the Immortality Talisman anywhere inside the delivery shuttle
6. Use the Cargo Shuttle Console to send the delivery shuttle back to CentCom
7. **Correct Behavior:** _Upon the delivery shuttle's arrival at CentCom, the Cargo Shuttle Console's CentCom message field will read as follows: "+x credits: Recieved 1 minor lava planet artifact" where X is a 4-5 digit number, likely near 10,000.  This amount is added to your current Cargo credits._
8. Use the Cargo Shuttle Console to request the delivery shuttle from CentCom again
9. Wait for the delivery shuttle to arrive
10. **Problem Behavior:** _When the delivery shuttle arrives, the Immortality Talisman you previously sold off to CentCom is still there.  You can repeat steps 6 through 10 unlimitedly for infinite credits._

**Here's a screenshot of an example shipment to CentCom:**
![image](https://user-images.githubusercontent.com/27884105/45093307-0523d080-b0e6-11e8-9461-735bef73fe10.png)

**Here's what the Cargo Shuttle Console has to say about it after I sent the shipment to them:**
![image](https://user-images.githubusercontent.com/27884105/45093458-6cda1b80-b0e6-11e8-8f3b-04fbb1aeb6bf.png)

**When I immediately recalled the Cargo shuttle, this is what came back with it:**
![image](https://user-images.githubusercontent.com/27884105/45093572-ca6e6800-b0e6-11e8-9ac7-5a78cdf63913.png)

**Comment by 81Denton** [comment]
Okay, that‘s pretty funny. Does anything speak against force deleting sold cargo shuttle objs?

**Comment by AnturK** [comment]
Yes, Destroy overrides shouldn't be used for IC indestructibility. Remove that instead.
