### ISSUE TITLE
Shield Generators cannot project shields while the device is off station, even when wired to power.

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#40111]
Sorry for no round ID, it's been persistent across multiple rounds in the last two weeks on Sybil.

To reproduce, get a shield generator from cargo, or secure storage in engineering, wrench it on a tile off station, like on the cooling loop, click on it, and watch as nothing happens. Wire it, and nothing happens. Bring it on station unwired, wrench it, and suddenly it works.

**Comment by Barhandar** [comment]
Sounds like someone made it use APC instead of wire network.

**Comment by kriskog** [comment]
Not a bug, uses apc for power like most other machinery.
