### ISSUE TITLE
Admin heal/Legion core use permanently removes special permanent negative moodlets

### ISSUE THREAD

**Issue by Arkvold** [tgstation/tgstation#40110]
Issue reported from a round on a personal server

Reporting client version: 512

There are special, permanent negative moodlets in the game.  Examples include the HULK SMASH! moodlet obtained from gaining the Hulk mutation, as well as the negative moodlet obtained from breaking your vow of silence as a Mime.  These moodlets, under normal circumstances, never go away and are intended to persist the rest of the round unless you become another character entirely (become a golem, etc.) or meet special criteria for their removal (re-swearing your vow of silence as a mime).

However, if you are admin healed or use a Legion core obtained from a defeated Legion, you're not only fully healed and satiated to neutral hunger, but also any negative moodlets affecting you are removed.  Since these permanent negative moodlets aren't meant to go away, and are only applied once when you meet the circumstances for obtaining them, their removal means they aren't ever coming back.  This lets you enjoy a normal emotional spectrum even when you shouldn't.

Possibly the same issue or related to #40083

### Reproduction Steps:

1. Obtain a permanent negative moodlet via some means (obtaining hulk mut, breaking mime vows, etc.)
2. Check mood - you should see the negative moodlet
3. Obtain and use a Legion Core
4. **Problem Behavior:** _Check mood - you should see that the negative moodlet is now gone._
5. Wait any length of time
6. **Problem Behavior:** _Check mood - no matter how long you waited, that negative moodlet is never coming back._

**Here's my moodlets upon using a Hulk DNA injector:**

![image](https://user-images.githubusercontent.com/27884105/45069754-17791c80-b09c-11e8-9467-675251a1aa9c.png)

**And this is what happens after I use a Legion Core while still a Hulk:**

![image](https://user-images.githubusercontent.com/27884105/45069828-78a0f000-b09c-11e8-8d17-ea74239aa36e.png)

**Here's the whole chatscreen so you can see I'm not skipping anything between the two:**

![image](https://user-images.githubusercontent.com/27884105/45069997-3e841e00-b09d-11e8-8d69-513b8cd08aec.png)

**Comment by Mickyan** [comment]
There's more moodlets that are affected by this other than hulk, broken mime vow and antag moodlets come to mind right now, requiring every moodlet to be constantly applied just for this would be pretty bad in the long run

Making adminheal only clear moodlets that have an automatic timeout should work, though having an item that calls admin commands seems like a bad idea to begin with

**Comment by Arkvold** [comment]
Given that this is so much broader of an issue, should I edit the title and reproduction steps to reflect it?

**Comment by XDTM** [comment]
Reason #100000 ingame items should not use adminheals

**Comment by ExcessiveUseOfCobblestone** [comment]
having a check for the moodlet constantly while on hulk seems wasteful compared to that of fixing the legion core to not adminheal.

**Comment by Arkvold** [comment]
Mickyan wrote:
> Making adminheal only clear moodlets that have an automatic timeout should work, though having an item that calls admin commands seems like a bad idea to begin with

ExcessiveUseOfCobblestone wrote:
> having a check for the moodlet constantly while on hulk seems wasteful compared to that of fixing the legion core to not adminheal.

Gotta agree with these.

The Legion core really should not be calling an admin command.  I'm okay with it providing a similar heal, and even clearing negative moodlets, but it needs its own effect that preserves existing game balance.

I know that Lavaland artifacts are meant to be a bit crazy, it's the reward for facing the volcanic hellscape that is Lavaland.  That said, Legions are literally the least-threatening enemy to exist out there.  They should not be dropping an item 100% of the time that calls an _admin command_ on the user at use.  

The Legion core needs its own effect so that admin-heal can retain its power, ensuring that the command can be used to get a character back to a known-good physical state _regardless_ of what's affecting them.  Compromising the potency of an admin command because of an in-game item's balance issues smells like terrible game design to me.

**Comment by XDTM** [comment]
That is true too

**Comment by Arianya** [comment]
Disagree on adminheal not doing it, since adminheal is generally only used in exceptional circumstances.

Agree that legion core needs fixing to not do this though.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm not sure I agree with that sentiment.

Adminheal should bring characters back to "just joined" status, a moodlet manager or VV should be used to edit their starting moodlets.

You don't use adminheal with the intention of wiping just a certain variant of quirks, so it seems odd to call that intended functionality.

**Comment by Arkvold** [comment]
So, in the end I guess it comes down to determining what an admin heal and a Legion core should and should _not_ be able to do.  The code's already prepared, or so it seems, to distinguish between the two.

By attaching different effects to that unused parameter, you can distinguish between the two without having to create an entirely new proc, if I understand things correctly, since `(admin_revive = 1)` is adminheal and `(admin_revive = 0)` is the Legion core or anything with a similar effect.

**Comment by Barhandar** [comment]
I think legion core should absolutely, completely heal (so removing any non-permanent moodlets like depression, but keeping hulking out and the like), but then add a negative moodlet to reflect the flavor text (that it's _disgusting_ to apply).

And then disable the bloody moodlets forever already.
