### ISSUE TITLE
Cloning the repo

### ISSUE THREAD

**Issue by DarkMukke** [tgstation/tgstation#40128]
When cloning the repo, you should use the option `--depth=1` to reduce the amount of download needed so the caveat in the `DOWNLOADING Option 2/3/4` is not that much of a caveat anymore

**Comment by Aranclanos** [comment]
how big is the download?

**Comment by Arkvold** [comment]
Getting a .zip clone of the repo weighs in at roughly 112 MB as of Sept 6th.

**Comment by LetterN** [comment]
if you're normally forking it using bash without fancy things, it seems to download the dependencies too

**Comment by SpaceManiac** [comment]
If you're cloning, clone once, just let it finish and in the future use `git pull` to update, and look into git worktrees if you really need multiple clones. The size of the repo can't be reduced without causing side problems

If you're downloading zip, it's faster the first couple of times, but cloning once and pulling each time will eventually be faster overall.

**Comment by ShizCalev** [comment]
issue????
