### ISSUE TITLE
Metastation Engineering missing floortile

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#40134]
Not sure who created this heinous sin. Should be a floortile under the airlock, it's a plating instead.

![>reading this](https://i.imgur.com/n5TuRKF.png)

**Comment by BeeSting12** [comment]
@WJohn 

Probably did it with the decal thing

**Comment by subject217** [comment]
Nah, I'm pretty sure my compile didn't have that commit in it. My guess is that Denton is to blame when he moved the engineering protolathe.
