### ISSUE TITLE
Public Nanite Chamber Placement Bug

### ISSUE THREAD

**Issue by Archemagus** [tgstation/tgstation#40138]
I didn't know why, but this shit is bot working, when there window near. I can not interact with chamber. Open, close, DECONSTRUCT. Nothing! Only break it by throwing items.
![image](https://user-images.githubusercontent.com/32466328/45146927-7d64c180-b1cc-11e8-87a1-28ad62ff0e14.png)
BUT! If i remove that window... All working fine...
![image](https://user-images.githubusercontent.com/32466328/45147019-aa18d900-b1cc-11e8-91d8-3153980f2451.png)
I HAVE NO IDEA, WHY?!
P.S. Maybe cause that shuttle zone near?

**Comment by XDTM** [comment]
It's a combination of window code and icon code, where icon code treats two tile high icons as being on the upper tile, and windows prevent interaction with icons layered under themselves. I'm looking for a way to refactor this without breaking stuff i don't know about.

**Comment by XDTM** [comment]
Or i could just go the cryotube way and layer it above windows
