### ISSUE TITLE
Ash storms might not work.

### ISSUE THREAD

**Issue by buildmaster668** [tgstation/tgstation#40130]
Round ID: 93501

Was playing Shaft Miner (well technically Assistant turned Shaft Miner, but that's not imporant). Generally I wait until an ash storm comes by to turn in my ores. 30 minutes pass and none show up. In the 5-10 minutes it took me to make a github account none have shown up. Might just be unlucky or maybe someone removed ash storms without be knowing but I thought it was worth reporting.

**Comment by Vidiveni** [comment]
I had ash storms as normal today on Bagil.

**Comment by Barhandar** [comment]
Ashstorms as normal on Sybil as well.

**Comment by RaveRadbury** [comment]
Ash storms have in fact been working. Maybe the real ash storm was inside us this whole time. Food for thought.
