### ISSUE TITLE
Emitters can be heard on separate Z Levels

### ISSUE THREAD

**Issue by TerraGS** [tgstation/tgstation#40131]
[Round ID]: 93504

Was ghosting at Charlie Station and from RnD I could hear emitters. An admin confirmed that I was at the same X and Y coordinates as the emitters on the main station Z level.

**Comment by vuonojenmustaturska** [comment]
Which round was this? ghosts had a z-tracking bug previously

**Comment by Arianya** [comment]
Issue seems to lie with the fact that very little is updating the `registered_z` variable.

A brief test showed that the following did not update them:

* Manual transistions (hitting the edge of a z)
* Jump to Area (ghost version)
* Follow (ghost version)
* Spawner Menu teleport
* Var editing `z`
* Jump to Area (admin version)

What did work was:

* Var editing `registered_z` (duh, I know)
* Spawning self as a human via ctrl + shift + click hotkey

Results seemed to only apply to ghosts, though I couldn't test all methods of z-transistion while a human.
