### ISSUE TITLE
Onetankbombs don't account for oxygen for detonation

### ISSUE THREAD

**Issue by Poojawa** [tgstation/tgstation#40143]
Heat up tank of only plasma to > 400K
> modified /datum/gas_mixture's temperature from 293.15 to 600

assemble one tank bomb
press button to detonate

ADMIN LOG: Explosion with size (0, 1, 3, 0) in Primary Tool Storage (57, 57, 2)

I realize that adding more oxygen of course will increase the bomb size, however being able to just heat a normal, full plasma tank up and fit common engineering supplies probably shouldn't force a bomb explosion, it should actually require the math at

https://github.com/tgstation/tgstation/blob/master/code/modules/assembly/bomb.dm#L147

![](https://i.gyazo.com/e9ad8ce4605da25c3ddf74c62ba4b51c.png)

**Comment by 81Denton** [comment]
Oh wait, could you add that they also don't account for tritium and other gases?

**Comment by vuonojenmustaturska** [comment]
they... work with tritium

**Comment by 81Denton** [comment]
okay scratch that

**Comment by deathride58** [comment]
Onetankbombs do not work with tritium currently. They only work with plasma. They are hardcoded to specifically only work with plasma and oxygen

**Comment by Shardj** [comment]
As far as I can tell, it's actually better with just plasma since the calculation is just plasma + oxygen/6. It doesn't care about ratios

**Comment by kriskog** [comment]
If you apply yourself, you can make a 3/5/8 from these. The still only count plasma and oxy moles though, but not a bug.

**Comment by Shardj** [comment]
How is this not a bug? A canister of only plasma gives the best results
