### ISSUE TITLE
giga shuttle brig has missing floor texture

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#40155]
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by BeeSting12** [comment]
@WJohn

**Comment by 81Denton** [comment]
What part of it is missing? The shuttle looks normal to me.

![gigapuddi](https://user-images.githubusercontent.com/32391752/45222997-4f5bac00-b2b6-11e8-9215-7571c97615f9.PNG)

**Comment by 81Denton** [comment]
Oddly enough, the texture error also shows in Dream Maker even though both turfs are `/turf/open/floor/mineral/plastitanium/red/brig`. Maybe it's because they have icon_state set to darkred/darkredfull?

**Comment by 81Denton** [comment]
I'll do a fix PR later today or tomorrow
