### ISSUE TITLE
Backup Human Name doesn't work

### ISSUE THREAD

**Issue by Birdspacito** [tgstation/tgstation#40162]
Issue reported from  Round ID: 93582 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

So I was playing a round as normal, with my character being a felinid (don't ask), and the backup human name that the game displayed when I became the Head of Shitcurity was meant to be Jaynie Morgan, which was the name I normally use for that character, and also as the backup human name, but my character's name wasn't even the designated backup human name.

**Comment by lolman360** [comment]
Backup Human Name only works when you join in as a head while on a nonhuman character. Works fine for plasmaman as far as I know.

**Comment by ShizCalev** [comment]
Not a bug.
