### ISSUE TITLE
Stealth Implants are broken

### ISSUE THREAD

**Issue by Suicidalpickles** [tgstation/tgstation#40178]
[Round ID]: 93619

[Reproduction]:
basically, had some nerd traitor purchase a stealth implant, implanted themself fine and dandy, but their action button for deploying the box was completely unresponsive. Tried this out personally in thunderdome, same result with no response upon clicking the activation.

![2](https://user-images.githubusercontent.com/32374784/45256929-49b3a400-b352-11e8-933d-d8cbc8604cc1.PNG)

**Comment by kriskog** [comment]
Clicking the button causes the following runtime:

```
Runtime in action.dm,512: Cannot execute null.drop location().
proc name: Trigger (/datum/action/item_action/agent_box/Trigger)
```
