### ISSUE TITLE
RPD missing flipped objects

### ISSUE THREAD

**Issue by Malkraz** [tgstation/tgstation#40171]
Issue reported from  Round ID: 93607 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

RPD cannot create flipped versions of the curved transit tubes, junctions, or disposal tubes.

**Comment by Sealed101** [comment]
- i can't find the exact PR that added those into the RPD's UI but we do have them. latest PRD UI as of #72957

![изображение](https://github.com/tgstation/tgstation/assets/75863639/ae983564-1c70-48e7-8d84-c3a1922bf9a8)

![изображение](https://github.com/tgstation/tgstation/assets/75863639/f0f796b9-e991-4252-9685-84388b140461)
