### ISSUE TITLE
Floor tile decals on damaged floor tiles looks off

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#40170]
Damage a floortile with a department color overlay. Rest of the tile gets twisted and blackened, the decal stays sqeaky clean.

![image](https://user-images.githubusercontent.com/33292112/45253660-21846f00-b36b-11e8-94f3-d7e7e1979d28.png)
![image](https://user-images.githubusercontent.com/33292112/45253676-601a2980-b36b-11e8-893b-0fb2aa493033.png)

**Comment by Barhandar** [comment]
It doesn't stay squeaky clean, it's just decal transparency issue.
