### ISSUE TITLE
Pirate deleted suddenly without warning.

### ISSUE THREAD

**Issue by MimicFaux** [tgstation/tgstation#40183]
Issue reported from  Round ID: 93618 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

Lone pirate raiding the station for loot and plunder. raided armoury, then science, killing a single scientist, grabbed the gold and ran back to ship. Loaded plunder onto the cargo teleporter, sent ship back to deep space to reload and rearm for a second pass at the station, suddenly was deleted with no body or ghost.

**Comment by MimicFaux** [comment]
Nevermind. IT WAS THE CARGO HOLD ITSELF THAT DID IT. 
+1000 credits: Received 1 hostage.
Might have had something to do with the pilfered ID

**Comment by Poojawa** [comment]
Yarr, we be our own hostage, what say you Station
