### ISSUE TITLE
honkerblast 5000 can knock you down even if you're in space

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#40192]
![image](https://user-images.githubusercontent.com/38788538/45262697-9cf62700-b424-11e8-96c0-5159085e8f4e.png)

**Comment by bgobandit** [comment]
feature

**Comment by ShizCalev** [comment]
Assuming this is in reference to the mech punching glove shooter?

**Comment by PKPenguin321** [comment]
no, the super loud horn that the clown mech has

there isnt sound in space you see

**Comment by ATH1909** [comment]
Well, we can already here each other speak in space, can't we?

I guess we're going by Star Wars logic in relation to sound and vacuums here.

**Comment by MrDoomBringer** [comment]
@ATH1909 you cant hear people in space tho
unless youre adjacent but thats because youre touching them and vibrations n stuff
