### ISSUE TITLE
Overthrow Upload Board doesn't work on Cyborgs

### ISSUE THREAD

**Issue by Ziiro** [tgstation/tgstation#40193]
[Round ID]: #93653
Round #93653
[Testmerges]: # 40172   40163

[Reproduction]: # Attempt to use the special Overthrow Law board on a cyborg upload console to change the laws of an unsynced borg. It does not change their laws.

Note: This is a borg that was synced to a converted AI, then desynced and had its laws fixed. It was still technically a traitor, but I could not get it off of Asimov.

**Comment by SpaceManiac** [comment]
@Carbonhell

**Comment by actioninja** [comment]
overthrow has been removed
