### ISSUE TITLE
wrong lighting

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#40209]
93705
http://take.ms/QYWfc

**Comment by SpaceManiac** [comment]
Looks like what would happen if whoever constructed the room didn't create an area

**Comment by davethwave** [comment]
Indeed.

**Comment by SpaceManiac** [comment]
For the record, space areas aren't dynamically lit by default, for performance reasons. The tiles which have lattices on them are given a separate area which is dynamically lit by default (under current server configuration). If you build a room in space and want it to look correct, you have to use the station blueprints or the Create Area command (it's one of the tiny buttons in the bottom-right of the UI).

**Comment by kriskog** [comment]
Not a bug
