### ISSUE TITLE
Stealth box and Clown Car have strange interactions.

### ISSUE THREAD

**Issue by JetBrody** [tgstation/tgstation#40202]
Issue reported from  Round ID: 93683 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

I got scooped up in a clown car and activated my stealth implant. This caused me to get inside the box outside the car and go about my merry way. Additionally, I could hit the "eject" button to resist out of the car, which caused me to teleport TO the car and eject everyone inside it.  Even later still I used my stealth implant again which teleported me back to the car, but not inside it.

**Comment by SpaceManiac** [comment]
`get_turf` is apparently widely misunderstood
