### ISSUE TITLE
Fireproof golems (plastitanium and hence titanium) burn their hands on lit wall lamps

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40214]
Issue reported from  Round ID: 93708 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

>can walk in lava and any kind of fire just fine  
>try to touch lamp, IT BURRRNNSSS USSSSSS

**Comment by 81Denton** [comment]
Needs to check for TRAIT_RESISTHEAT and TRAIT_RESISTHEATHANDS

https://github.com/tgstation/tgstation/blob/45f0d76553f099906801b82363bae24fc43e4dde/code/modules/power/lighting.dm#L593-L596
