### ISSUE TITLE
Centcom are crooks when it comes to adamantine bounty

### ISSUE THREAD

**Issue by DfourC** [tgstation/tgstation#40215]
When there is a bounty on 10 bars of adamantine, if all of the bars are together as one stack it will only count one towards the bounty. To properly fulfil the bounty, each of the bars needs to be on a different tile on the shuttle.

**Comment by RedFoxIV** [comment]
centcom is made of 100% quality cunts
~~intended
feature~~

**Comment by ExcessiveUseOfCobblestone** [comment]
Is this with all stack-bounties or just adamantine

**Comment by 81Denton** [comment]
Yikes

**Comment by 81Denton** [comment]
@ExcessiveUseOfCobblestone I'm assuming it's all of them, since adamantine is the only stack bounty with multiple required items.
