### ISSUE TITLE
play-internet-sound seems to just flat out not work sometimes.

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#40210]
[Round ID]:93706

[Testmerges]:#40195 and #40163

[Reproduction]:Toss a youtube link into play-internet-sound, it may or may not work, when it doesn't it throws out this GIANT error,

Youtube-dl URL retrieval FAILED:

ERROR: Signature extraction failed: Traceback (most recent call last):
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\youtube.py", line 1199, in _decrypt_signature
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\youtube.py", line 1110, in _extract_signature_function
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\youtube.py", line 1171, in _parse_sig_js
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\common.py", line 880, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Yeah youtube-dl is broken because youtube is making videos increasingly difficult to extract, just gotta wait for a fix. (Unless it's already fixed and just needs an update on the host)

**Comment by ExcessiveUseOfCobblestone** [comment]
I was able to play utube fine last night, this may have been fixed.

**Comment by bgobandit** [comment]
A similar issue happens with midis/oggs and I think it has to do with certain symbols being in the file name

**Comment by SpaceManiac** [comment]
Can you give an example of a link which doesn't work?

**Comment by Borisvanmemes** [comment]
Nevermind it seems it got fixed.
