### ISSUE TITLE
you can open gas canisters without notifying admins

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#40211]
Step 1: connect a tank to the target canister.
Step 2: open valve.
Step 3: pull the tank out without closing the valve.
Step 4:watch it burn
![image](https://user-images.githubusercontent.com/38788538/45302683-9ea31600-b51c-11e8-8c16-725ad1a35410.png)
step 5 (optional): enjoy the shitshow if you have access to asay/ahelp

**Comment by ExcessiveUseOfCobblestone** [comment]
do we really want a notification EVERY TIME a valve is opened though?

**Comment by GravitronBlue** [comment]
A notification if a tank is pulled while the canister valve is still open should be simple enough.

**Comment by granpawalton** [comment]
im having a hard time reproducing this, investigate_log(..., INVESTIGATE_ATMOS) gets proced when i do it can you be a little more descriptive on what you were doing when this occurred?
