### ISSUE TITLE
remember that one bug where you could throw ghosts via buildmode and break shit?

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#40229]
![2018-09-11_14-56-20](https://user-images.githubusercontent.com/38788538/45358720-fe5bf880-b5d2-11e8-9015-084b4c083de7.gif)

**Comment by SpaceManiac** [comment]
set `throwforce = 0` on revenants

**Comment by PKPenguin321** [comment]
still a non-issue. if admins want to grief (which is... ???) they can throw literally anything they want including items they make invisible and revenants will never get thrown in normal gameplay, so the "issue" never arises nor is it worth spending effort to fix

**Comment by PKPenguin321** [comment]
that said i'll take some free GBP
