### ISSUE TITLE
Weapon firing mechanism

### ISSUE THREAD

**Issue by Baby1991** [tgstation/tgstation#40228]
Issue reported from  Round ID: 93745 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

If you scrap the weapon firing mechanism with the integrated curcuit printer, the weapon inside gets deleted

**Comment by Tlaltecuhtli** [comment]
then dont scrap it

**Comment by Baby1991** [comment]
Its not a problem for me it just might fuck up someones day if they put an antique laser gun if for example

**Comment by Tlaltecuhtli** [comment]
ic issue

**Comment by XDTM** [comment]
i suppose this is closeable along with everything in the circuits milestone

**Comment by SpaceManiac** [comment]
Circuits have been removed.
