### ISSUE TITLE
MOnkey in clonepod

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#40230]
Issue reported from  Round ID: 93748 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Didn't have time to get much debug information myself @Thunder12345 but there was a monkey in a clonepod. Clonepod visually was empty. It was not processing anything and anyone attempting to be cloned had an initialization error.

**Comment by ShizCalev** [comment]
Seeing similar issue in the round mentioned in #40291

plenty of runtimes in the log for that round too.

**Comment by kriskog** [comment]
Closing in favor of #48247 since cloning has seen changes since.
