### ISSUE TITLE
Portable floodlight

### ISSUE THREAD

**Issue by Archemagus** [tgstation/tgstation#40234]
![image](https://user-images.githubusercontent.com/32466328/45375154-d1bcd680-b5fc-11e8-85e2-75f016cc2c9f.png)

1) Construct and turn on floodlight.
2) Cut wire, under floodlight. It still lights...
3) What if try to unwrech it....
4) Oh... It's brightest feature, that i have even see!

**Comment by JesterX666** [comment]
I would love to fix that one as I'm learning the source code.  Should be easy to do.  Please assign me!
