### ISSUE TITLE
Ghosts can indirectly interact with people

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#40248]
[Round ID]: #93801

I was a ghost, an admin was throwing me around, I hit a person and caused them to move.

**Comment by PKPenguin321** [comment]
admins throwing ghosts isnt a real issue! AAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Iamgoofball** [comment]
Wow it's almost like I blew the whistle on this being a problem ages ago

**Comment by SpaceManiac** [comment]
just ask the admins to stop doing this
