### ISSUE TITLE
BoxStation bombtest site observation screen thingy is layered under the glass and is therefore inaccessible without adjacency + alt-click

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40244]
Issue reported from  Round ID: 93787 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

**Comment by yoyobatty** [comment]
On hippie I set to 0.05+ above the layer and it fixed it

**Comment by 81Denton** [comment]
It might be worth changing layer of all telescreens to something like `ABOVE_WINDOW_LAYER`?

**Comment by miniusAreas** [comment]
This should be a easy fix, I may attempt this as a first issue.
