### ISSUE TITLE
Using a trashbag of holding on a pile of circuits that scan and force drop the bag makes both disappear

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#40259]
Issue reported from  Round ID: 93816 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

The bag "disappears" because the isdropped thing on the scanner component equals true, and an admin said that the trashbag with all the circuits still exists in my bag, but the bag cannot be emptied of it, and nothing shows up

**Comment by ATH1909** [comment]
So the bag is invisible?

Can you still put stuff in the bag?

Does this also happen with normal trashbags?

Is this the new anti-nukeops meta?

**Comment by SpaceManiac** [comment]
Circuits have been removed.
