### ISSUE TITLE
buildmote telekinesis doesn't work with tables correctly

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#40265]
Reproducing:
1)spawn a table
2)spawn anything you want
3)go into buildmode and throw the anything-you-want onto the table with telekinesis.
4)try throwing it away from the table. Fail miseralby.

**Comment by AnturK** [comment]
Was this on a shuttle ?

**Comment by RedFoxIV** [comment]
well, yes

**Comment by SpaceManiac** [comment]
In that case, intended functionality. Tables on shuttles (I forget the *exact* conditions) have "magnetic clamps" so items don't fly off when the shuttle moves, which basically means things can't be thrown off of them.

**Comment by ShizCalev** [comment]
intended
