### ISSUE TITLE
Cards against Spess is broken: The Squeakquel

### ISSUE THREAD

**Issue by MrAlphonzo** [tgstation/tgstation#40271]
[Round ID]: 93846 who cares

Attemping to grab a card from a CAS black/white deck will cause the card to fall to the ground below the player, and simultaneously create an invisble card, named "card", in their hand.

This was tested on both black and white CAS decks.

Syndicate cards and normal playing cards are functioning perfectly fine.

There is a single exception, blank CAS white cards do not have this issue.

**Comment by MrAlphonzo** [comment]
I good english

**Comment by SpaceManiac** [comment]
for the record, round ID is useful to check 1) version of the code that was running at the time and 2) if the logs contain any errors

**Comment by MrAlphonzo** [comment]
I'm sorry sir but it is admin policy to bully the coders at every opportunity.
Even if we're objectively wrong we just keep going anyways.

**Comment by bgobandit** [comment]
this is an old bug, basically what is happening is something is making null datum entries be produced, idk what though
