### ISSUE TITLE
Apparently that Config update for AI Multicam didn't actually work.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#40276]
[Round ID]: #93868

Well, uh, looks like that didn't work even after maintainers gave it the approval and merged it. Free GBP if someone knows configs better than me. 

Toggle button still says "This action is currently disabled. Contact an administrator to enable this feature." when pressed on Bagil.

**Comment by SpaceManiac** [comment]
The server is probably not updated yet, but I can't confirm without a round ID

**Comment by Potato-Masher** [comment]
@SpaceManiac #93868

**Comment by SpaceManiac** [comment]
Server is updated, I assume the headmins need to update the config

**Comment by SpaceManiac** [comment]
anyways, server issue
