### ISSUE TITLE
Borked screen overlay with Book Inventory Management Console

### ISSUE THREAD

**Issue by epochayur** [tgstation/tgstation#40275]
Round ID: 93865

![image](https://user-images.githubusercontent.com/32695675/45529901-a8d34780-b79c-11e8-8135-4a3807759689.png)

when printing stuff out, the display on the screen overlaps books and paper, it doesn't seem to work with other items, but I also haven't tried it on any other sort of computer

**Comment by SpaceManiac** [comment]
Duplicate of #40048
