### ISSUE TITLE
Capture the Flag - Flags returning to base

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#40288]
Issue reported from  Round ID: 93927 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

So in CTF, the flags will randomly return to base without any rhyme or reason. Reproduced several times across various CTF rounds.
@coiax

**Comment by octareenroon91** [comment]
Jump back on the floor, or while carried?

**Comment by Hathkar** [comment]
It returned to base while it was being carried in hand. It seems to be returning in 20 seconds regardless of being carried.
