### ISSUE TITLE
Disk Compartmentalizer (disk smart fridge) does not refresh UI when disk is put in, only when one is taken out

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40286]
Issue reported from  Round ID: 93922 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])  
Reporting client version: 512

It also doesn't have a slot in the UI for putting disks in and so require clicking on it in world.

**Comment by Sealed101** [comment]
doesn't seem to be the case anymore
