### ISSUE TITLE
Felinids don't have a laughing sound.

### ISSUE THREAD

**Issue by Wilchenx** [tgstation/tgstation#40298]
title.

**Comment by Barhandar** [comment]
inb4 opening an issue doesn't count for getting prior maintainer approval

**Comment by Wilchenx** [comment]
its a bug

**Comment by Iamgoofball** [comment]
Not a bug tho oranges declared it false

**Comment by Wilchenx** [comment]
>they had normal laugh before
>they don't have now due to oversight
>not a bug

🤔

**Comment by Tlaltecuhtli** [comment]
not an insect

**Comment by GuyonBroadway** [comment]
Catgirls do not deserve laughter.

**Comment by iskyp** [comment]
this is no laughing matter people, if i can't laugh as my catgirl character i cannot play this game

**Comment by GuyonBroadway** [comment]
Unironically tho, anyone who cannot play the game because thier catperson cannot laugh should stop playing the game.
