### ISSUE TITLE
Floor tile texture bug on pubby

### ISSUE THREAD

**Issue by Coconutwarrior97** [tgstation/tgstation#40307]
Server: Terry
[Round ID]: 9400
Client Version: 512
A floor tile next to the RnD lab on Pubby has a glitched texture. I'm not sure if it happens every round but I've definitely seen it before in the exact same spot.
![image](https://user-images.githubusercontent.com/40315842/45603184-0eb70d80-b9ef-11e8-87fd-e628e8ad030a.png)

**Comment by SpaceManiac** [comment]
whoever fixes this please notice that there is a second error in the RD office in the screenshot as well

**Comment by Barhandar** [comment]
They look like the same pink-edge-decal issue so fixing one would likely fix the other as well.
