### ISSUE TITLE
After using the holopad, it leaves static everywhere cameras can't see.

### ISSUE THREAD

**Issue by SkippuSetsuna** [tgstation/tgstation#40309]
[Round ID]: # 94005

[Reproduction]: # I used the holopad to call medbay cloning, and after I was done using it left nothing but static anywhere without a camera.

![image](https://user-images.githubusercontent.com/37200424/45605894-4b423380-ba06-11e8-8023-2d41fe3be863.png)

EVAC shuttle:
![image](https://user-images.githubusercontent.com/37200424/45606046-82fdab00-ba07-11e8-9852-a561483b0758.png)

**Comment by SpaceManiac** [comment]
Duplicate of #39752
