### ISSUE TITLE
locker staff causes extreme lag in certain occasions

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#40319]
http://take.ms/hxDlL

94030

i got shot by a locker staff and after 5 min from round end my chat is still catchin up over 5000 logs of like pic related

**Comment by Time-Green** [comment]
Theres a little infinite loop issue, since in some exotic cases the contents would drop, and then immediatly put back in. The loop probably expires if there aren’t too many mobs.

Anyway I fixed that in my PR

**Comment by Time-Green** [comment]
This is probably fixed now

**Comment by Qustinnus** [comment]
@ninjanomnom

**Comment by kriskog** [comment]
You also dont get locked in now so
