### ISSUE TITLE
Overthrow AI has to obey all syndicate agents instead of only its team.

### ISSUE THREAD

**Issue by fizzle7** [tgstation/tgstation#40336]
When subverting an AI with overthrow module, it gets syndicate Asimov + 4th law to hide syndicate activity and also gets the objective and team HUD, but not law to assist the team in their objectives. Since laws precede the objectives, AI has to obey all syndicates regardless of teams, which doesn't happen because people don't care, so AIs just break their laws constantly. Moreover, borgs don't even get objectives or a HUD and also break their laws constantly. Since this kind of shitstorm doesn't seem intended, it looks like a bug to me.

**Comment by ATH1909** [comment]
What should the lawset be changed to? Maybe add a "X team and people who they designate as syndicate agents are syndicate agents. No one else is a syndicate agent."

Should the AI be considered to be a syndicate agent too?

**Comment by actioninja** [comment]
overthrow has been removed
