### ISSUE TITLE
Fires no longer spread without surreal circumstances (Possibly issue with new atmos gasses and or heat transfer)

### ISSUE THREAD

**Issue by miniusAreas** [tgstation/tgstation#40342]
[Round ID]: # Null. Bug found on Hippiestation and Sunsetstation, then poked and re-produced using a local server running the latest version of /TG/.

[Testmerges]: # Surely not. Hippie and Sunset wouldnt be running a TG Testmerge.

[Reproduction]: # When starting fires, plasma will ignite on a single tile, but put itself out, and will not spread. A few rounds of hippie and SunsetStation, a branch of TGcode thats beng updated downstream, and testing on a local server bring me to this conclusion-

>Fires can no longer spread from other fires
>Flamethrowers cant spread their fire to other plasma moles.
>Igniters wont light or start fires
>The Atmospheric Burn holodeck Program no longer lights completely on fire, instead resulting in a ton of plasma in a room.
>Turbine works fine however, leading to a new conclusion.

That is, that the new Atmos gasses (Tritum, etc) for fusion are doing some weird shit with atmos that puts the plasma out due to temp or otherwise, and may be replacing all the o2 on a tile at once, or burning it all at once. Finding this was due to the turbine burning at max plasma temp in just a few seconds, even with the vents open. Fires cant procure enough o2 to even spread, meaning that my favorite Hijack method of running onto the station with a atmos firesuit, hauling several re-labled cans of plasma or o2/plas burnmix onto the shuttle is impossible. This is going into a seperate issue, but commented here due to the fact that they may be linked. 
Reproduction of the issue is simple.
Get plasma, throw welder into it.
Get plasma, throw igniter/timer assembly into it
Get plasma and a Flamethrower, shoot flamethrower into plasma
Have a AI turn the Atmospheric Burn on.
Turn the Turbine on with a 80o2/20p Mix with the vents open.

[For Admins]: # This issue makes the SM when delamming have a few issues. Namely, the fact that plasma wont be lit untill its heated to ludicistly high tempratures, meaning the sm can go from -1 to 4% integ a second to hitting -30 to 70% integ a second, making it a game of time and guessing before the SM can blow, removing the brave Engineers and Atmosians, and SEVERAL antag items, from the round.
It is possible that plasma is burning o2 faster than it's supposed to, as giving plasma a shitload of o2 and lighting it makes it work fine.

Also note - I AM a bannee of /TG/. I can not attest for the opinions and or whats happened in rounds and or announced via the servers media. The bug was found from testing and playing around on several TGcode servers, listed above, then formatting a formal investigation on a local server running the latest TGcode. Big plasma fires are super rare, so its easy to see how this could have been a oversight.

**Comment by miniusAreas** [comment]
Could also be linked with #40261's heat transfer.

**Comment by miniusAreas** [comment]
wait wut

**Comment by Vidiveni** [comment]
Also CLF3 in smoke or foam can not ignite plasma, unless the smoke/foam puts someone on fire who then in turn ignites the plasma.

**Comment by Poojawa** [comment]
It's not the heat transfer. the base wall transfer rates are 0.0.

**Comment by ExcessiveUseOfCobblestone** [comment]
Doesn't the trit reaction produce water vapor

**Comment by Poojawa** [comment]
![](https://i.gyazo.com/c48c78b4aeb3e64f11c4def51182c9ac.png)

**Comment by kingoftheautism** [comment]
Yeah, sometimes burning oxy+plasma mix barely igniting other tiles, sometimes it's fine, sometimes it doesn't.

**Comment by Potato-Masher** [comment]
Still happening, even in toxins burn chamber.

**Comment by kriskog** [comment]
Igniting atmos was fixed a while ago
