### ISSUE TITLE
GBS doesn't want to gib

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#40344]
[Round ID]: 94090

To reproduce infect someone with GBS and watch the stage tick up. Doesn't seem to do anything however it is able to scare the crew quite a bit. Though it could have been a fake one but I doubt it.
<img width="960" alt="dreamseeker_2018-09-18_15-23-29" src="https://user-images.githubusercontent.com/13891233/45720031-8d2ebf00-bb57-11e8-8f8a-045f999ff236.png">

**Comment by XDTM** [comment]
GBS is almost identical to normal GBS and it's available in the virus crate. It sounds likely that it was that.

**Comment by Jordie0608** [comment]
During the shown round no diseases were spawned; a virus crate was ordered and the path for fake gbs but not real shows up in qdel. I think it's fair to say this was fake GBS.

**Comment by davethwave** [comment]
Thanks for making sure.
