### ISSUE TITLE
Metastation's disposal stacker has redundant machinery - replace please.

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#40354]
[Round ID]: # 94117 (i noticed it but presumably its been the case for a while)

- I dont believe its made by a testmerge however new types of constructable stackers were produced for  #37607 & it is mentioned that the recycling uses it but not elaborated upon fully in #39118 

To reproduce, load a metastation map, throw anything in enough quantity within the recycler to be reclaimed and for a split second you'll see it before dissapearing into the stacker, which is then presumably added to the ore silo (i haven't checked). This appears to be the same exact type of stacker as the labour camp function, and cannot be deconstructed.

- Attempting to deconstruct the stacking machine will cause you to hit it, there is no recognition in the adjacent stacker console of held materials inside the stacker and the disposal loop back to metastation is also redundant other than a quick ride back when before it used to handle stacking feedback when released from the console.
___________________________________________________

Since this is not a _bug_, what i suggest is either map editing a constructable stacker to fufill its former function since materials can be reclaimed back into the ORM delivered back to cargo office  & added the silo network manually, **_or_** remapping Metastation disposals to make it more clear that this singular stacker is similar to the gulag stacker in central design.

> However a problem with that is that it makes it easy to sabotage since the gulag stacker cannot be rebuilt but can be destroyed. So long term a constructable stacker would be more maintainable.

**Comment by FantasticFwoosh** [comment]
Before _someone_ :tangerine: shoots me down i did originally write a bug report but changed it to the availible option of 'feature request'  after reconsidering how it might have been deliberately dealt by (39118) and what i had previously wrote overwriting the field when i came back to it. 

So I apologise if i didn't exactly see all the normal contributor pre-formatting, and id be fine re-editing it again to conform if someone would point it out.

**Comment by ExcessiveUseOfCobblestone** [comment]
no one cares since it's a mapping issue

**Comment by 81Denton** [comment]
I'll have a look once #40313 is merged
