### ISSUE TITLE
You can dig the same tile multiple times

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#40368]
#40312: '[PAID CODE] economy PR' by Iamgoofball at commit cf1d2f11fd
#40350: 'Radial RCD Menus' by AnturK at commit 81282c82e9
Server tools version: /tg/station 13 Server v3.2.5.1

[Reproduction]: Spam click a tile with dig results

**Comment by SpaceManiac** [comment]
Caused by #40264 @vuonojenmustaturska 

`dug` isn't checked between starting the `use_tool` and calling `getDug`
