### ISSUE TITLE
fire extinguishers most of the times  dont extinguish people 

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#40361]
i set myself on fire, grabbed and extinguisher and sprayed like 8 times before the fire actually ran out

**Comment by RedFoxIV** [comment]
I think is has to do with the way you're setting yourself on fire.
Like if an unfortunate ~~dumbass~ miner steps in lava he will need to roll on the ground / use a fire extinguisher several times before the fire dies.
Same with devil's fireball and some others sources of **OUCH**

**Comment by kriskog** [comment]
No, I've seen this myself. It seems harder to extinguish yourself the last few days.

**Comment by wesoda25** [comment]
It makes fighting drake while lagging really fucking annoying. It was definitely caused by something, prolly the PR.
