### ISSUE TITLE
[Thing on fire] starts to fall apart! x50 (fire damage ticks to items are each reporting in chat as "starts to fall apart")

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40366]
Issue reported from  Round ID: 94181 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
Reporting client version: 512

**Comment by ShizCalev** [comment]
but it's starting to fall apart

**Comment by ShizCalev** [comment]
#40348 takes a step towards making that message unneeded when it comes to fire, as it properly applies burning effects to your items.

**Comment by timothymtorres** [comment]
@ShizCalev is this still a thing?

**Comment by san7890** [comment]
![image](https://github.com/tgstation/tgstation/assets/34697715/527421dc-1bb6-4fa1-baa6-2f6dc665631f)

it only sends the message once now, let me know if there are still contexts where it spams
