### ISSUE TITLE
Dark Blue with Blue Slime crossbreed doesn't work

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#40375]
It's supposed to create a tankless air mask but it just makes the slime vanish and nothing happens.

**Comment by Tlaltecuhtli** [comment]
dark blue crossbreeds arent  coded yet :joy:

**Comment by YakumoChen** [comment]
they're on the wiki though?

**Comment by Barhandar** [comment]
You mean the one that greets you with the following?

_**This extract isn't in the game yet, but the code for it is done! Watch for it in the future.**_

**Comment by fludd12** [comment]
Dark Blue (Chilling) Crossbreeds are now in the game! Enjoy! The issue can now be closed.
