### ISSUE TITLE
It is possible to remove documents from the filing cabinet in the vault as a ghost

### ISSUE THREAD

**Issue by Gouty** [tgstation/tgstation#40378]
Issue reported from  Round ID: 94213 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

AS A GHOST

Click the filing cabinet and then clicking the documents in the resulting box allows you to remove the Top Secret documents from the filing cabinet.  Tested on metastation. Cannot do the same with the lawyers filing cabinet

**Comment by Gouty** [comment]
I am a chumbis. I forgot to write "as a ghost"

**Comment by BeeSting12** [comment]
Well edit the title you chumbis

**Comment by Gouty** [comment]
Couldn't see how to edit title on my phone.  Home now so updated

**Comment by Potato-Masher** [comment]
PARANORMAL ACTIVITY

The bugs are always amusing.

**Comment by obscolene** [comment]
This has been a bug for so many years it should be considered a feature by now.
