### ISSUE TITLE
Admin table ckey/byondkey consistency

### ISSUE THREAD

**Issue by nfreader** [tgstation/tgstation#40384]
Hi,

I've talked about this before, but it's still an issue. 

Right now, the `ss13admin` table's `ckey` column is composed of neither `ckey`s or `byondkey`s, it is a horrible mix of both that does not work.

`ckey` columns are expected to be `[a-zA-Z]+`, and `byondkey` columns should be whatever the player's unmodified Byond username is. 

The `ss13admin.ckey` table cannot be a mix of both. Right now I'm using RegEx in SQL to select against that table, which is not a solution.

@Jordie0608 I think this is still your baby.

**Comment by Jordie0608** [comment]
This isn't a codebase issue anymore; it was when the import script and rank system didn't convert to ckey values like they should've anyway for safety, but that's been fixed. There was no required update to existing incorrect rows in table because it's not a necessary change.
Basically while it was my error, I can't fix it because only MSO can =P

````
import MySQLdb
import argparse
import re
import string

parser = argparse.ArgumentParser()
parser.add_argument("address", help="MySQL server address (use localhost for the current computer)")
parser.add_argument("username", help="MySQL login username")
parser.add_argument("password", help="MySQL login username")
parser.add_argument("database", help="Database name")
parser.add_argument("admintable", help="Name of the current admin table (remember prefixes if you use them)")
parser.add_argument("rankstable", help="Name of the current admin ranks (remember prefixes)")
args = parser.parse_args()
db=MySQLdb.connect(host=args.address, user=args.username, passwd=args.password, db=args.database)
cursor=db.cursor()
ranks_table = args.rankstable
admin_table = args.admintable
ckeyExformat = re.sub("@|-|_", " ", string.punctuation)
ckeyformat = string.punctuation.replace("@", " ")
cursor.execute("SELECT rank FROM {0}".format(ranks_table))
rank_list = cursor.fetchall()
for rank in rank_list:
    new_rank = "".join((c for c in rank[0] if c not in ckeyExformat))
    cursor.execute("UPDATE {0} SET rank = '{1}' WHERE rank = '{2}'".format(ranks_table, new_rank, rank[0]))
cursor.execute("SELECT ckey FROM {0}".format(admin_table))
admin_list = cursor.fetchall()
for ckey in admin_list:
    new_ckey = "".join((c for c in ckey[0] if c not in ckeyformat)).lower()
    cursor.execute("UPDATE {0} SET ckey = '{1}' WHERE ckey = '{2}'".format(admin_table, new_ckey, ckey[0]))
db.commit()
cursor.close()
print("Complete.")
````

**Comment by MrStonedOne** [comment]
root@maria-db:~# python3 aussy_virus_3.py localhost root hunter2 tgstation13 ss13admin ss13admin_ranks
Complete.
root@maria-db:~#

**Comment by nfreader** [comment]
We're all good now, thanks!
