### ISSUE TITLE
Singularity Escaping Containment

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#40399]
Issue reported from  Round ID: 94245 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

I set up a singularity engine at Charlie Station, and the singularity simply moved on through the field generator containment shielding. The beams kept firing afterwards.

I think the issue is that when it grew to level 2, the size change put in contact with the field generator shielding?

Here's as screenshot for reference.
https://i.imgur.com/SdMKN9z.png

**Comment by ShizCalev** [comment]
that fps tho

**Comment by kingoftheautism** [comment]
Uhh, yeah, singulo normally supposed kind of bounce from containment fields, and if they are increasing in size - bounce from fields, but not sure how it escaped that field (also consumed it)

**Comment by Barhandar** [comment]
Have you considered setting up a 5x5 containment instead of 5x4?

**Comment by kriskog** [comment]
Likely same as #40399 where it eats the containment if it comes into contact with it on grow.

**Comment by msgerbs** [comment]
I'm assuming this can be closed as this no longer exists in the game.
