### ISSUE TITLE
Ghost roles can be made survivalists by summon magic/summon guns

### ISSUE THREAD

**Issue by harmonyn** [tgstation/tgstation#40404]
Which causes problems when they decide they can kill their fellow ghost roles (for instance fellow syndie base members), because after all, they're an antag now

**Comment by ATH1909** [comment]
I'd say that this is fine- just search for lavaland/space loot BEFORE trying to murder your rolemates for it. After all, killing them won't give you all of the guns and/or magic stuff you need, and they can help you find more.

**Comment by timothymtorres** [comment]
I don't see any problem with this.  Nobody is immune to magic and it travels through bluespace to affect all z-levels.
