### ISSUE TITLE
Exosuit-mounted syringe gun is not working as intended.

### ISSUE THREAD

**Issue by fen0s** [tgstation/tgstation#40412]
[Round ID]: # 94276

[Testmerges]: # The following pull requests are currently test merged:
#40312: '[READY][PAID CODE] economy PR' by Iamgoofball at commit 9be426bc1e
#40350: 'Radial RCD Menus' by AnturK at commit a3c6c77f28
#40296: '[READY] [Gamemode Bounty] Assimilation' by Kierany9 at commit f447fbce08

[Reproduction]: # 1. Build an Odyssey mech.
2. Get a exosuit-mounted syringe gun for it.
3. Try to shoot anyone with any reagent. (I believe it's a problem with any reagent, but I tried welding fuel)

It just throws syringes at people literally. It doesn't work like a syringe gun and doesn't inject people with actual chemical, and instead of that, it just throws syringes at them, that don't inject on hit.

**Comment by kriskog** [comment]
The syringes inject if you aim at people and they dont move to the side or further away than your target. Although this syringe gun is pretty shitty, not a bug. Just bad design. Drop a suggestion on the forums if you want a rework.
