### ISSUE TITLE
Payday messages get displayed to all mobs around

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#40439]
Issue reported from  Round ID: 94311 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Not sure if this is intended @Iamgoofball

**Comment by FantasticFwoosh** [comment]
Follow the formatting please, everyone knows what you're referring to with goof-economy but the context of it being bagil & testmerge does matter.

**Comment by DaxDupont** [comment]
@FantasticFwoosh it got merged

**Comment by Iamgoofball** [comment]
will fix, your furry avatar is still crap

**Comment by DaxDupont** [comment]
@Iamgoofball better than your code lmao
