### ISSUE TITLE
Vendors no longer display contents to admins

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#40436]
Issue reported from  Round ID: 94309 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

AIs are probably affected too
![p9jldrb 1](https://user-images.githubusercontent.com/17237624/45925424-1e65b300-bf15-11e8-993d-1a0094649a2a.png)

**Comment by DaxDupont** [comment]
@Iamgoofball

**Comment by 81Denton** [comment]
Ghosts too

**Comment by Iamgoofball** [comment]
Admins need to update the servers.

**Comment by DaxDupont** [comment]
@Iamgoofball only keyholders can

**Comment by Iamgoofball** [comment]
yes, I pinged them when things got merged, and they very clearly didn't listen, go whine at them to update

**Comment by AnturK** [comment]
Apparently fixed in latest.
