### ISSUE TITLE
People slip while riding borgs

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#40438]
Issue reported from  Round ID: 94311 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

People slip while riding borgs while they move over wet tiles

**Comment by AlexTheSysop42** [comment]
Are you sure it wasn't lube?

**Comment by DaxDupont** [comment]
Either way it shouldn't affect people riding borgs

**Comment by bgobandit** [comment]
Intentional, the average spessman is so tall that when riding borgs his feet touch the ground

**Comment by AlexTheSysop42** [comment]
Lube affects buckled people too, pretty sure it's intentional

**Comment by Qustinnus** [comment]
No its not its just that we don't check for buckled when crossed() is called

**Comment by ShizCalev** [comment]
Duplicate #23558
