### ISSUE TITLE
Vent Crawling Is Still Broken Badly (Abductor Fuckery)

### ISSUE THREAD

**Issue by Kerbin-Fiber** [tgstation/tgstation#40435]
[Server]: Basil
[Round ID]: 94309

[Reproduction]: Get abducted and have the Stretch Gland inserted into you. Start vent crawling and wait for 'your leg spasm!' and your screen will stop and freeze while you pop out from the pipe your on. You'll still be able to control your person while your screen is frozen.

Captain saw me pop out of a pipe and I vent crawled back into the vents but then he completely removed me from the round cuz of "Lings"

**Comment by XDTM** [comment]
oh boy, if the step proc can throw you out of pipes you can use mercury to force yourself out when ventcrawling

**Comment by Mooshimi** [comment]
wonder if this recent rework effected this #66709

**Comment by Sealed101** [comment]
the rework did not affect this - loaded up on mercury and got this wack shit to happen, only managed to fix with ghosting and returning to body

![image](https://user-images.githubusercontent.com/75863639/222814251-fa48fbf7-7339-4cd8-902a-11d88d739326.png)

**Comment by Sealed101** [comment]
fixed by #80586
