### ISSUE TITLE
Vendors don't see held IDs, only IDs in ID slots

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#40437]
Issue reported from  Round ID: 94309 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

1. Hold ID in hand
2. Click vendor and try to buy
3. Can't vend items

This is problematic if you don't have a uniform available.

**Comment by DaxDupont** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
Yeah, put it in an ID slot.

**Comment by DaxDupont** [comment]
>have to buy uniform
>can't buy without uniform

**Comment by Barhandar** [comment]
>week long testmerge
>PR existed for 6 days, at least 2 of which were spent finishing it

**Comment by XDTM** [comment]
>and it got merged already

**Comment by DaxDupont** [comment]
@iamgoofball I'm too busy working during the week, I have a life sorry.

**Comment by rustledjimm** [comment]
It was testmerged for about 2 days.

Also goof your past actions do enough to smear your image lmao.

good pr though, needs tweaking imo. I set up a thread in coding feedback forums.

**Comment by BeeSting12** [comment]
@Iamgoofball This is a bug.

**Comment by PKPenguin321** [comment]
>like wew if you had just taken this to the forums like a normal person I would of went and coded this feature 

no you wouldnt have, you would have just told them to fuck off there too
this is another dimension of feedback deflecting
