### ISSUE TITLE
Alt-click to copy obj/turf in buildmode adv. disappeared

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#40445]
![image](https://user-images.githubusercontent.com/38788538/45929659-863fec00-bf5d-11e8-994f-7e1d0da21935.png)
`(no alt click = copy obj/turf)`
A very useful buildmode function just vanished, is this intentional? If so, ~~reeeeeeeeeeeeeeeeeeeeeeee~~

**Comment by Barhandar** [comment]
Accidental due to upgraded buildmode overriding pick-atom, #40390
