### ISSUE TITLE
Service borg fabricator can't dispense any items

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#40446]
Server revision compiled on: 2018-09-23
Local commit: 5870c60779aeedc0a59a4d0d07adbc04ac33329e

Trying to dispense any items with the service borg's Rapid-Service-Fabricator (/obj/item/rsf) results in this error message: "The Rapid-Service-Fabricator doesn't have enough matter left."

@Iamgoofball

**Comment by KetasDotepasto** [comment]
I've taken a look at the code. Apparently, a service borgs RFS is not supposed to use matter, and doesn't consume it, but it must still pass a check that it has the matter.

Apparently, it used to be that the service borg's RSF got 30 matter for free, guranteing it passed the check. It seems that this somehow doesn't happen anymore.

I suggest changing the check for whether the SFR has enough matter to only happen if the user is not a borg. Does Byond have else statements? That would allow putting the "is matter left" check in the else of the "is user a cyborg" check, which should solve the problem.

**Comment by KetasDotepasto** [comment]
I implemented a fix and opened a pull request. This is my first pull request, so please bear with me.

**Comment by KetasDotepasto** [comment]
Service cyborgs can use the RSF again, so this issue should be closed.
