### ISSUE TITLE
Shuttle area overlaps pod loading bay 2 

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#40440]
Issue reported from  Round ID: 94311 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512
![emywkdd 1](https://user-images.githubusercontent.com/17237624/45925989-61785400-bf1e-11e8-92bd-f7e17ab69fb3.png)

@MrDoomBringer

**Comment by MrDoomBringer** [comment]
uuuuuuuh kk ill fix this tonight or tomo
