### ISSUE TITLE
VV icon weirdness

### ISSUE THREAD

**Issue by theOperand** [tgstation/tgstation#4047]
![2014-07-03 12_56_55-skeleton station fourteen](https://cloud.githubusercontent.com/assets/3975713/3469202/e5c6df4a-02aa-11e4-8d46-21bf9f30d9e3.png)

I know there was an issue for this before but it was closed and I can't find it.
Possibly a BYOND issue.

Please note that box does not contain a mint by default in the build I was testing, so it's not taking on the icon of something else on the station.

The mint is the first (and second) icon in economy.dmi

**Comment by Jalleo** [comment]
@Miauw62 has this occurred again?

**Comment by Dorsisdwarf** [comment]
This is a dupe hang on

**Comment by Dorsisdwarf** [comment]
This is a better report than it's dupe (*you* reopened the dupe too miauw)

**Comment by optimumtact** [comment]
old higgs bugson

**Comment by PKPenguin321** [comment]
This still happens with some stuff, like dismembered left arms appearing as the Christmas package wrapper

**Comment by Aranclanos** [comment]
oranges the mister said it still happens

**Comment by theOperand** [comment]
>This is a better report than it's dupe (you reopened the dupe too miauw)

more open issues = more feature freezes = less fun, it all makes sense tbh
