### ISSUE TITLE
Forcefield projector doesn't fit in toolbelt

### ISSUE THREAD

**Issue by Coconutwarrior97** [tgstation/tgstation#40473]
Server: Sybil
Round ID: 94414

The Forcefield projector does not fit in a toolbelt like the other two engineering holosign creators do, (atmos fan, and engineering holobarrier) .

![](https://i.gyazo.com/40067981f5c6c6c11e134e2b62098d3d.png)

**Comment by SpaceManiac** [comment]
It's a slightly different class of item than a holosign creator (notably, it is ranged), so I'm not sure this is a bug.

**Comment by TheDreamweaver** [comment]
@spacemaniac they're both direct children of item and both seem to have the same bitflags (other than the forcefield projector having the item_slot_ belt flag which we m ow wouldn't be presenting it because time also have this flag). Unless there's something you're seeing that I'm not.
