### ISSUE TITLE
Building (plasmarglass) directional windows in tiles with windoors is impossible regardless of facing

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40516]
Issue reported from  Round ID: 94488 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])  
Reporting client version: 512

It should check for windoor's position/direction, same as it does to block building stacked directional windows, instead.

**Comment by Sealed101** [comment]
building directional windows has its own check for windoors, and it even passes it all fine and dandy. it only gets stopped by the generic check later on

relevant code:

https://github.com/tgstation/tgstation/blob/30e2a94779a74265d61a8f60330127c2e2cf6766/code/__HELPERS/turfs.dm#L375-L394

___

https://github.com/tgstation/tgstation/blob/30e2a94779a74265d61a8f60330127c2e2cf6766/code/game/objects/items/stacks/stack.dm#L443-L454

_______

https://github.com/tgstation/tgstation/blob/30e2a94779a74265d61a8f60330127c2e2cf6766/code/game/objects/items/stacks/stack.dm#L474-L485

**Comment by Sealed101** [comment]
fixed by #86651
