### ISSUE TITLE
Slot Machines do not accept credits from ID Cards

### ISSUE THREAD

**Issue by Nickvr628** [tgstation/tgstation#40511]
Like title says, the slot machines do not accept credits from IDs, only coins, which means nobody can gamble in the bar unless they get coins from maint or mining.

**Comment by XDTM** [comment]
Will add holochip compatibility

**Comment by Hathkar** [comment]
Also, any winnings from the slot machines are worthless, since the payout is in coins.

**Comment by kriskog** [comment]
They now take holochips.
