### ISSUE TITLE
Security cameras can accept (and hence vanish) upgrades in wrong states of construction, such as before welding it to the wall

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40518]
Issue reported from  Round ID: 94488 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])  
Reporting client version: 512

Lathe a camera assembly. Stick it to the wall. Click on it with analyzer/plasma sheets/likely prox too and watch as they (entire stack, in case of plasma) vanish into the Ether.

It should only accept upgrades at the "only needs screwdriver to finish" stage.

**Comment by ExcessiveUseOfCobblestone** [comment]
or just not break the process lol

**Comment by ShizCalev** [comment]
the upgrades don't vanish, they went into the camera.
