### ISSUE TITLE
Holy Weapons don't protect against The Traps Wizard Spell

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#40515]
Issue reported from  Round ID: 94493 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

As the title says, holy weapons like the holy claymore or other nullrod variants don't protect against The Traps spell.

**Comment by ExcessiveUseOfCobblestone** [comment]
should they?

**Comment by Hathkar** [comment]
I don't see why not? The Null Rod already protects against pretty much every other spell in the game.

**Comment by ExcessiveUseOfCobblestone** [comment]
Is magic missile/disin/f2s null-rod immune?

I'm genuinely asking.

**Comment by Hathkar** [comment]
I'm PRETTY sure they are? I know null rod gives immunity to all cult spells, fireball, and distorted reality.

**Comment by ExcessiveUseOfCobblestone** [comment]
hmm neat.

should be an easy fix, just toss the magic immunity check prior to the naughty actions of the trap.

**Comment by ShizCalev** [comment]
Fixed by #40382

**Comment by ShizCalev** [comment]
Looking into this further, only 13 out of 59 anti_magic_checks check for Holy items, and all 13 of those are related to "scared/unholy" sort of magics/effects. Gonna close this under the pretense of it being a suggestion, in which case the forum would be a better for this.
