### ISSUE TITLE
Post-Holocredits, budget ID's do not accept space cash

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#40521]
[Round ID]: none particular, can't remember sorry. [will update as appropriate when next encountered]
[Testmerges]: see above

After the merge of #40462 to add the holochips as a replacement form of currency on the station, redundant 'space cash' paper notes that can still be accessed from space ruins and some other certain places like the mining vendor do not accept ID's to add to the value of the accounts.

- The only way to add space cash to cargo budget directly is through the bank machine in vault, i haven't tried inserting credit chips into the bank machine though to see if its backwards compatible that way.

- This was only tried on budget ID's particularly, the easiest test would be to spawn in as a QM, spawn in a 1000 space credit bill and attempt to insert into your cargo budget id.

**Comment by XDTM** [comment]
this isn't a bug, space cash is an obsolete standard

**Comment by nfreader** [comment]
You heard it here folks. Not a bug.
