### ISSUE TITLE
Orbiting changes break tesla's mini-balls off somehow, resulting in two dozen separate teslas that will gladly Syd the station if loose, aka: OH GOD ITS LOOSE CALL THE SHUTTLE

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40522]
Issue reported from  Round ID: 94497 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])  
Reporting client version: 512  
Testmerges: #40480: 'Makes the orbiter component less prone to failure' by ninjanomnom at commit 207a3044a0

![teslaballs](https://user-images.githubusercontent.com/2338212/46109904-77fa0600-c1d1-11e8-9af2-e7cbc48bcc70.PNG)
![tesloose](https://user-images.githubusercontent.com/2338212/46110243-8f85be80-c1d2-11e8-925c-552dcc541895.PNG)
![shitsfukt](https://user-images.githubusercontent.com/2338212/46110265-a0363480-c1d2-11e8-95d4-bae951796dd6.PNG)

**Comment by optimumtact** [comment]
@ninjanomnom oh my god dude

**Comment by ninjanomnom** [comment]
***feature***

**Comment by ninjanomnom** [comment]
Seems to be working fine https://puu.sh/BBFqi/51779d421f.mp4
I'm going to update sybil because I suspect the testmerge may be outdated

**Comment by kriskog** [comment]
From bagil round 94541.

This used to be one tesla. The balls dropped orbit and became their own teslas who again split and you get it.

![image](https://user-images.githubusercontent.com/33292112/46176272-26c04400-c2af-11e8-92d6-72962145c9b8.png)

![image](https://user-images.githubusercontent.com/33292112/46176363-6be47600-c2af-11e8-9dd3-c62149675965.png)

**Comment by ninjanomnom** [comment]
It's definitely happening but I have no clue what's causing it. A possible fix is on bagil atm
