### ISSUE TITLE
Fried space

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#40527]
[Round ID]: # 94501
situation in the picture
<img width="960" alt="dreamseeker_2018-09-26_16-24-05" src="https://user-images.githubusercontent.com/13891233/46115522-35720280-c1ac-11e8-931a-0b75e0d027f4.png">

**Comment by Arkvold** [comment]
Judging from the wreckage at the edges of the game window, this used to be the kitchen.  I'm guessing the space you're looking at used to be the deep frier.  Did it somehow deep-fry the entire tile it's on?

**Comment by davethwave** [comment]
What we guessed in ghost chat was that the vat full of frying oil burst when the singulo ate it, causing the entirety of the nearby area, it being space, being doused in oil, frying it.

**Comment by Arkvold** [comment]
Either way, holy crap.

<solid snake>But how does it _taste?_</solid snake>

**Comment by sagattyy** [comment]
thats intentional not a bug

**Comment by ishitbyabullet** [comment]
should've done a us marine events smh
