### ISSUE TITLE
you cant use laser pointers/ranged scanner circuits while inside of a bluespace bodybag

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#40539]
see title
1. get int obluespace bodybag
2. try to use laser pointer or ranged sensor circuit
3. cry as they are not used

**Comment by BebeYoshi** [comment]
Intended?

**Comment by SpaceManiac** [comment]
You basically can't do anything while in a bluespace bodybag, I suspect there would be powergaming trouble if this was possible anyway. Considering this intended.

**Comment by evsey9** [comment]
shidhed >:(
