### ISSUE TITLE
More orbit issues

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#40544]
Round 94525 and others

#40455: 'Fix for part of client drops. Maybe.' by AnturK at commit d7d9b15964
#40414: 'Replaces istypes with the proper tool_behaviour checks.' by ShizCalev at commit 5803feff71

Still a few more issues after #40433 and #40480.

- Wizard jaunting drops orbit.
- If you orbit a ghost and they orbit a new target, you sometimes fall off after you move
- You cannot re-orbit something you are already orbiting. Not huge, but used to make you restart your orbit so you could change position.

**Comment by Ispiria** [comment]
I noticed yesterday that I'd drop orbit if a wizard used rod form, as well. Maybe related?

**Comment by ninjanomnom** [comment]
Alright I found the issue with jaunting which was a problem in general with things moving in the same turf but into something else.

The only issue remaining here that I don't know about is ghosts occasionally falling off

**Comment by kriskog** [comment]
Also seem unable to orbit revenant, your orbit doesn't follow it.

**Comment by Barhandar** [comment]
Can confirm that revenants are completely impossible to orbit. I've also tried to orbit Legion and something shook me off of it.

**Comment by ninjanomnom** [comment]
I think I fixed the issue with the orbit dropping. Orbiting revenants are also fixed in the pr.

**Comment by kriskog** [comment]
Terry round 94690

- Orbiting nuke disk drops orbit when it is moved from ground to player.

**Comment by kriskog** [comment]
- Orbit target teleporting with cult teleport rune drops orbit.
- Teleport runes moves ghosts

Keeping them in the same issue for now, as number two might be the cause of number one.

**Comment by kriskog** [comment]
- Orbit target walking into wormhole drops orbit

**Comment by ninjanomnom** [comment]
Terry doesn't have any of the fixes
