### ISSUE TITLE
Lacking arms and trying to climb/get buckled to a borg gives erroneous feedback to people around

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40546]
Issue reported from  Round ID: 94524 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
Reporting client version: 512

`X can't climb onto Y because her hands are full!`
`Her left arm is missing!`
`Her right arm is missing!`

**Comment by 81Denton** [comment]
It looks like the code doesn't distinguish between having no empty hands and having no hands at all.
