### ISSUE TITLE
Monitoring nanites ignore z-level limitation of crew monitoring console

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40540]
Issue reported from  Round ID: 94520 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])  
Reporting client version: 512  
Testmerges: #40480: 'Makes the orbiter component less prone to failure' by ninjanomnom at commit 207a3044a0

https://github.com/tgstation/tgstation/blob/master/code/game/machinery/computer/crew.dm#L128

`if (target Z is same as user Z, or 0 AND they're wearing an uniform) OR (they have nanite sensors)`

**Comment by XDTM** [comment]
oops
