### ISSUE TITLE
PILES OF GORE with monitoring nanites (equal to maxed suit sensor for crew monitoring console) are not detected by crew pinpointer

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40541]
Issue reported from  Round ID: 94520 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])  
Reporting client version: 512  
Testmerges: #40480: 'Makes the orbiter component less prone to failure' by ninjanomnom at commit 207a3044a0

This makes them somewhat _utterly useless_ off-station because coordinates are no longer shown and pinpointer fails.

**EDIT:** Checked the round log, the miner in question _exploded on gibtonite_ with their corpse being gibbed, but the monitoring nanites kept broadcasting.

**Comment by SpaceManiac** [comment]
Do crew pinpointers need monitoring nanites now?

Shouldn't a gib render anything that used to be in the body moot?

**Comment by kriskog** [comment]
So in reality, the issue is that after being blown apart (not gibbed) the nanites still send health status but can't be pinpointed.

**Comment by MTandi** [comment]
I'm not sure if my fix will apply to a pile of gore, can someone try to reproduce this from my branch?
