### ISSUE TITLE
Circuits containing references to a self ref component will have those references wiped when the component is removed.

### ISSUE THREAD

**Issue by GLACoding** [tgstation/tgstation#40552]
Probably caused by #40129, so effects all self reference components.

Reproduction :
Make a bot with a pump + reagent storage
Link pump to reagent storage
take out reagent storage, pump will also lose its reference to the storage

This messes up any printed circuit using reagents with manually filled stores, as the pumps linked to those stores will all need to be relinked afterwards, which is tedious as hell.

**Comment by Shdorsh** [comment]
Was intended actually. Else, you can use the copy ref function included in the circuit debugger.

**Comment by GLACoding** [comment]
@Shdorsh But it makes outfitting a printed circuit much longer + more accident prone when you have to re link every pump and every store, which wasn't a problem with the old system.
Shouldn't it only overwrite when you link it rather than when its unlinked?

**Comment by Iamgoofball** [comment]
china will grow larger
