### ISSUE TITLE
ECONOMY: Clown and probably mime IDs display your main character name upon examine, not clown name

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#40560]
" That's Clunwe's ID Card (Clown)
A card used to provide ID and determine access across the station.
It is a tiny item.
The registered account belongs to 'Fortune Ray' and reports a balance of $972.
The Service Budget reports a balance of $12823.3."

@iamgoofball fix your shit

**Comment by TrustyGun** [comment]
also does it for the paystand description

**Comment by zeroisthebiggay** [comment]
sidenote but this also happens when using a backup human character
e.g. Is-The-Example the ligger decides to play HoS and is turned into Alex McGriff, examining his ID will still show it as the account being owned by Is-The-Example

**Comment by Iamgoofball** [comment]
@bgobandit No, it shows the name hooked to the account. This is more of an oversight, if anything.

**Comment by Iamgoofball** [comment]
The way the account name stuff works is it's assigned before your job is finalized, which is why backup-human and clown names aren't working.

**Comment by bgobandit** [comment]
it should match the name on the ID that it's attached to

**Comment by ExcessiveUseOfCobblestone** [comment]
Regardless of the semantics behind a bug and oversight, it's an issue that needs to be ratified...
