### ISSUE TITLE
Nuke op Spetsnaz bundle flamethrower does not ignite burnmix properly

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#40573]
The backpack flamethrower from the nuke op Spetsnaz bundle doesn't ignite the burnmix properly - you get maybe three tiles of fire and the rest is just plasma that dissipates after a few seconds.

**Comment by MrDoomBringer** [comment]
im pretty sure this is intentional but idk

**Comment by 81Denton** [comment]
I see now, it's kind of like the bioterror spray but not really useful. Not a bug, but could definitely use a rework.
