### ISSUE TITLE
Emitters not firing

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#40583]
Issue reported from  Round ID: 94622 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

When turning on the emitters, the emitters went green, there was power, all was dandy, yet they did not shoot. Had to resort to dumping items and people into the supermatter to keep the station powered. 0/10 would not reccomend.

**Comment by kriskog** [comment]
Likely cause is that the power that was in the network webt somewhere else before the emitters had their go. On metastation at least, the emitters are connected to the smes output side of the network, which means it shares power with all the APC's around the station.

As a note, emitters stay green even when they dont get enough power to fire.

**Comment by MrDoomBringer** [comment]
yea i would try reproducing in the same spot and checking the wire w a multitool

**Comment by 81Denton** [comment]
Imo it would be good if emitters had a destinct icon state or error desc if the available power is lower than their `active_power_usage`
