### ISSUE TITLE
*CC SAYS "MUH EXPENSES"* ERROR - SHUTTLES NOW IMPACT CC WITH MAXIMUM FORCE, REPLACING PART OF THE CC PODS.

### ISSUE THREAD

**Issue by miniusAreas** [tgstation/tgstation#40597]
Found during a Sunsetstation playtest, with the metastation evac shuttle.

Yeah, they delete part of the CC Supplypod bay, making shit fucked.

Pleas fix, this breaks muh immersion.

**Comment by SpaceManiac** [comment]
Duplicate of #40440
