### ISSUE TITLE
IDs cannot be put into PDAs that are in backpacks (or presumably other containers)

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40603]
Issue reported from  Round ID: 94671 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])  
Reporting client version: 512  
#40557: 'More orbit fixes' by ninjanomnom at commit 86399ffc06

**Comment by SpaceManiac** [comment]
Old issue, might even have been intentional at the time, easy fix

**Comment by Barhandar** [comment]
It would be intentional if you couldn't _pull IDs out_ in same conditions.

**Comment by SouDescolado** [comment]
Is this still the case? I am messing with PDA.DM, but the attackby() has no check to see if it is in a bag, just if it is being attacked by an id. Maybe this means that attackby do not trigger if it is inside a container and it should be something else?

**Comment by SpaceManiac** [comment]
This is still the case. The relevant code is here:
https://github.com/tgstation/tgstation/blob/e21e2b161e6329a9ee1c9a6b0fb27436f5c0d033/code/game/objects/items/devices/PDA/PDA.dm#L811-L812

**Comment by SpaceManiac** [comment]
Fixed by #45037.
