### ISSUE TITLE
Night shift event does not affect mining base APCs

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#40607]
The night shift event doesn't affect mining base APCs. 

This happens because mining base areas aren't included in `GLOB.the_station_areas` - just adding them to the list would cause issues for other things though, like emagged express consoles, blobs or anomaly spawning.

**Comment by Jalleo** [comment]
Intended. Its off statiion.

**Comment by SpaceManiac** [comment]
Mining base counts as off-station for obvious reasons, while I don't necessarily think it shouldn't have night shift it's easier and a little more consistent to keep things as they are.
