### ISSUE TITLE
spawning a template/creating a new area does not update SSmapping.areas_in_z

### ISSUE THREAD

**Issue by TMTIME** [tgstation/tgstation#40602]
[Round ID]: # Local server. 

[Reproduction]: # 
1 - Either:
- Spawn a new template with admin verbs ~~or code if you are a dirty downstream~~
- Use an item like a bluespace capsule
- Create a new area using a verb

2 - Check SSmapping. The new area is not included in areas_in_z

[Why is this an issue]: # Using SSmapping.areas_in_z lets us avoid running costly loops to get all areas in one z level. Anything that uses this may not return all the areas in that z level.

**Comment by SpaceManiac** [comment]
I can look into this, but what purpose are you hoping to use `areas_in_z` for?

**Comment by Qustinnus** [comment]
@SpaceManiac downstream we're using templates to spawn our entire map.

**Comment by SpaceManiac** [comment]
Yeah but what are you using `areas_in_z` for, tgcode uses it in one place for weather only

**Comment by Qustinnus** [comment]
We get all the Z levels with ZTRAIT_STATION, loop through all the areas in there, set the direction of our parallax (simulate ship movement) and update all mobs their parallax.

**Comment by Dennok** [comment]
The problem is deeper, The spawn areas not properly initialized, but say what it is initialized.
