### ISSUE TITLE
Marker beacons are not affected by nightmare light eater

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#40601]
Round: Any

Be nightmare. Make a marker beacon. Hit with light eater, takes four hits to destroy. As it is, it is faster to pick them up than try to destroy them.

**Comment by kriskog** [comment]
Same for camera lights, one hit should disable the light when on.

**Comment by Barhandar** [comment]
Finally, a use for prism stones that isn't spamming them over mining on station.
