### ISSUE TITLE
Deoxyribonucleic saboteur seems to be impossible to get.

### ISSUE THREAD

**Issue by Adanps** [tgstation/tgstation#40616]
Round ID: #94703

Reproduction: Use virus plasma on a virus to get level 6 symptoms, watch as you don't ever get DNA saboteur.

I haven't been able to get DNA saboteur several times even after using tons of virus plasma. Maybe I missed something but it looks like DNA saboteur is still in the code so I have no idea what's going on.

**Comment by YPOQ** [comment]
The code file was removed from tgstation.dme in #35988
I have no idea if it was intentional or not.

**Comment by Tacolizard** [comment]
1337 issues we've made it boys
