### ISSUE TITLE
Felinid mutant part and "x-derived mutant" issues

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#40619]
Roundstart Felinids that spawn in show up as "Felinid-derived mutant" when scanned with a health analyzer. I tested this with both the mutant parts on (cat ears and tail) and with them off (human ears and no tail). Felinids being able to appear functionally identical to humans should they choose so at roundstart is rather weird as well.

The weird thing is that I also tested it with set species and by spawning in Felinids via game panel, and they show up as "Felinid" on the health analyzer. So something about how they're spawned in on the arrivals shuttle is different.

**Comment by SpaceManiac** [comment]
the inconsistency between roundstart body creation and latejoin body creation is really unfortunate

**Comment by AnturK** [comment]
Caused by #40308, namely the move of features to after species setting.

**Comment by Mooshimi** [comment]
This is no longer an issue from what I've seen
