### ISSUE TITLE
The ash drake's new lava arena attack doesn't make safespots when you fight it in a mech

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#40621]
Title, :joy:

**Comment by GunHog** [comment]
What kind of mech do you even use to fight it now that the plasma cutter on a Ripley is no longer viable for combat?

**Comment by Borisvanmemes** [comment]
A firefighter with a plasma cutter, it still works just takes ages.

**Comment by Barhandar** [comment]
inb4 "reeeee intendedbalanced"

**Comment by Whoneedspacee** [comment]
My bad probably, could’ve sworn I tested that but I think it was most likely that now the code checks for living targets in the radius instead of just the singular target. Should be a fairly easy fix.
