### ISSUE TITLE
spraycan menu extremly loading heavy and closes itself 50% of the times

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#40638]
it takes 40s of freezing to open the menu and it also closes itself half the times 

i blame tgui why do we use it

**Comment by Tlaltecuhtli** [comment]
http://take.ms/o4an2 this is how it looks ingame

**Comment by Barhandar** [comment]
Scrubber air alarm menu on steroids?

**Comment by 81Denton** [comment]
>i blame tgui why do we use it

rampant masochism mostly

**Comment by kriskog** [comment]
Improved in #44561
