### ISSUE TITLE
Using Envy's Knife on (free) golems results in random human name instead of copying the golem's

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40635]
Issue reported from  Round ID: 94779 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE]) 
Reporting client version: 512
#40557: 'More orbit fixes' by ninjanomnom at commit 6d5e0da65a

Intended result: "Adamantine Bismuth"  
Actual result: "Julianna Martins", "Peyton Petrov" (dependent on the specific body used, adamantium and plastitanium respectively)

**Comment by Qustinnus** [comment]
@Barhandar do you asctually get their appearance
