### ISSUE TITLE
Syndrones cannot use Syndicate weapons from their uplink

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40658]
Issue reported from  Round ID: 94811 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])  
Reporting client version: 512  
#40557: 'More orbit fixes' by ninjanomnom at commit 6d5e0da65a

`IMPLANT CHECK FAILED.`

**Comment by MimicFaux** [comment]
Give'em the explosive implant like normal agents. More _bang for your buck._
