### ISSUE TITLE
Plasteel golems can't punch objects on harm intent

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40656]
Issue reported from  Round ID: 94811 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])  
Reporting client version: 512  
#40557: 'More orbit fixes' by ninjanomnom at commit 6d5e0da65a  

It makes them a _lot_ less useful than they could be if they would be a slower, worse Hulk.

**Comment by DaxDupont** [comment]
Feature request, please use forums
