### ISSUE TITLE
The nodrop implant gives the items in your hands nodrop rather then making the person that has it unable to drop items

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#40669]
Title, give someone the nodrop implant, put something in their hands, make them turn on the implant, cut off the hand with a item in it, pick up the item, you are unable to drop it, 
fuck i worded the name of this badly.

**Comment by Barhandar** [comment]
Better question: does it _remove_ nodrop from items that innately have it, like dark blessing, eye of god or Rod of Asclepius?

**Comment by AlexTheSysop42** [comment]
It does make them unable to drop them though, that's why you had to cut off their arm. It leaving nodrop on things that somehow do leave their hands is definitely a bug though

Also did you see what happened when they deactivated the implant while you were holding the item?

**Comment by yoyobatty** [comment]
Turn this on, cut your arm off, put it back on, pickup whatever robust item you had, murderbone without fear of slip and slide bowling

**Comment by AlexTheSysop42** [comment]
That's literally what the implant does, no arm removal needed
