### ISSUE TITLE
skeletons cant be hugged :(

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#40672]
how to reproduce:
1. find skeleton
2. try to hug skeleton
3. fail your veiled attempt at preforming CPR on them

**Comment by NotAFootFetishist** [comment]
kissy

**Comment by ExcessiveUseOfCobblestone** [comment]
@XDTM willing to bet this has something to do with pretend dead

**Comment by XDTM** [comment]
Yeah, it's because they're always FAKEDEAD so if they lie down they can pretend to be corpses. Maybe a check to see if they're lying down could fix this without disrupting that tactic.

**Comment by ATH1909** [comment]
We're so sorry skeletons
You're so misunderstood
You only want to socialize
But I don't think we should

I like XDTM's idea.
