### ISSUE TITLE
The Illusion of Choice 

### ISSUE THREAD

**Issue by NotAFootFetishist** [tgstation/tgstation#40670]
@Sybil
![image](https://user-images.githubusercontent.com/43799783/46384857-146b4f00-c68f-11e8-932b-f85a1979dd0e.png)
Digitigrade Legs do not change your ingame character appearance.
Clueless of which merge broke it, has been broken for a fair amount of days.

**Comment by bobbahbrown** [comment]
feature

**Comment by FantasticFwoosh** [comment]
Take off your jumpsuit and wear digitgrade friendly clothing, like skirts & kilts, those have code that don't restrict digitgrade legs wheras without that, the legs would overlap the long jumpsuit so you'd have the illusion four legs with only 2 feet ~~not for citadel downstream~~.

Uniforms being forced into restricted slots i think is seperate entirely, that lizard can take off those clothes to revert to normal and be unable to slot back in the shoes. Happens a lot with transformations into other races, humans into golems etc.

**Comment by Qustinnus** [comment]
feature

**Comment by bgobandit** [comment]
it's more than appearance, you can walk over sharp things and be fine

**Comment by deathride58** [comment]
Digitigrade legs only show with specific types of clothing, as TG lacks digitigrade-specific sprites. If you're naked or wearing only shorts, your digitigrade legs will show.
Mirroring Citadel-Station-13/Citadel-Station-13#7599 , Citadel-Station-13/Citadel-Station-13#7632 , and optionally Citadel-Station-13/Citadel-Station-13#7592 will fix this issue

**Comment by Poojawa** [comment]
the actual fix is included in #40514

**Comment by FantasticFwoosh** [comment]
Oh i thought skirts & kilts covered the field you were talking about @deathride58 , my mistake.

> Poojawa the actual fix is included in #40514

Hmm, dont think so little buddy, though you're free to try opening another PR again to see how far you get. :thinking: :thinking: :thinking:

**Comment by NotAFootFetishist** [comment]
Come on, I just wish for it to be how it used to, a terrible downgrade that you can toggle, not add specific clothing and _shoes_ to digitigrade.

**Comment by ExcessiveUseOfCobblestone** [comment]
@tgstation/issue-managers this might be fixed but now that I've looked at this issue I forget if it was since I don't lizard or dabble with ashies.

**Comment by Detective-Google** [comment]
Almost certain it is but I'll test it and close tonight

**Comment by kriskog** [comment]
Digitigrade lizards mains are all over terry. It's fixed.

**Comment by PKPenguin321** [comment]
It's fixed... but at what cost?

**Comment by ExcessiveUseOfCobblestone** [comment]
my sanity
