### ISSUE TITLE
Minor supply pod smite issues

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#40688]
1) Canceling smite -> supply pod (quick) with the cancel button gives a popup: `ERROR: NULL path given.`
2) Smite -> supply pod logs `ADMIN LOG: Ckey/(George Melons) punished *no key*/(Pete) with Supply Pod.` as soon as you click it - even if you close the window and don't actually smash someone with the pod.

**Comment by ExcessiveUseOfCobblestone** [comment]
1. https://github.com/tgstation/tgstation/blob/fc78bb3d8018623b39c7775b71d11c7823b86914/code/modules/admin/verbs/randomverbs.dm#L1286-L1288

This is the intended message? null = Cancel

2. Normal supply pod doesn't have a return value within the proc for canceling out the window (oh lovely tgui!) so the proc doesn't care if you cancel it out or not.

**Comment by SpaceManiac** [comment]
1. Written in the code != intended. If the admin clicked Cancel, they don't need to be told they clicked Cancel.
2. Admin log should only be issued if the action actually occurs.

@MrDoomBringer

**Comment by MrDoomBringer** [comment]
whups, @SpaceManiac is right
