### ISSUE TITLE
cryo sting makes flypeople vomit

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#40691]
not a bug code-wise but doesnt seem very intentional gameplay-wise, frost oil is a nutriment subtype and stuff

**Comment by ShizCalev** [comment]
Emergent gameplay.

**Comment by Time-Green** [comment]
intented

**Comment by DaxDupont** [comment]
Wait why the dick is it a nutriment subtype

**Comment by ATH1909** [comment]
Honestly, I can see this working lore-wise. I mean, isn't vomiting SUPPOSED to purge toxins and stuff? Maybe we should buff/nerf flypeople by making them vomit ALL chems, both harmful and beneficial. It might give them an identity beyond "a human reskin that takes longer to eat food".

Maybe add some fluff somewhere that the same chemical that lings use to cryosting people occurs naturally on the home planet of the flypeople (do they have one, or are they only created by teleporter accidents?), so their bodies have adapted to purge it from their bodies and turn it into food.

**Comment by OmegaShoots** [comment]
@DaxDupont because it's a food item weaponized by weird homocidal aliens

**Comment by JohnFulpWillard** [comment]
This was fixed when reagents were split into Stomach/Bloodstream
