### ISSUE TITLE
Overthrow's point system is broken.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#40705]
@Carbonhell 

Killing and exiling heads, sec, etc gives points to every team instead of the one that killed them. If all teams are rewarded, none are.

https://tgstation13.org/phpBB/viewtopic.php?f=10&t=19804&p=443157

**Comment by Carbonhell** [comment]
The gamemode isn't simply team against team like gangs. Teams can choose to cooperate against the crew, and exiling/killing heads will reward all the teams to help this. A team can, instead, convert a head to gain a small point boost. If nothing is done, the objective fails and the crew wins. Also, exiling gives more points than killing, for greentext purposes. If people decide to ignore greentexting it isn't the gamemode's fault imo.
The list of items a dude gets on conversion can be improved. It is all dealt with a list, just add the type of the object you wanna give to new overthrow agents, it's an one line change.
If pointd were tracked, you could easily metagame and see if another team is fucking with your heads or such. Dunno if it is a good idea.
Also if a team converts a head but someone else exiles said head, all teams get the point boost. There is a lot of fuckery and gimmicks you can do by deciding whether to help only your own team, all teams or the crew.

**Comment by ExcessiveUseOfCobblestone** [comment]
I've never understood this concept in terms of mechanics.

If only one team can win, then no they can't choose to cooperate without disadvantaging themselves from a mechanics standpoint. Each team has an obvious interest in converting heads to _their_ team.

Anyone can cooperate in the game, i'm not sure why it's brought up in this gamemode when the game only permits one winner.

**Comment by nemvar** [comment]
Technically 'fixed'
