### ISSUE TITLE
MMIs can hear guardian/holoparasite talk

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#40708]
[Round ID]:  94925

[Reproduction]: 
Reports by players that brains in MMIs can hear guardian-player chat like a ghost, despite not being dead

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/e5e0459e334f2c71caf64f111cdd425f2991a89d/code/modules/mob/living/simple_animal/guardian/guardian.dm#L392-L394

https://github.com/tgstation/tgstation/blob/e5e0459e334f2c71caf64f111cdd425f2991a89d/code/modules/mob/living/simple_animal/guardian/guardian.dm#L370-L372

**Comment by ShizCalev** [comment]
they should potentially be able to see cult communication as well

https://github.com/tgstation/tgstation/blob/08453ec3b27256f8afbb5074ac0f28531bdbb8fa/code/modules/antagonists/cult/cult_comms.dm#L40-L46

**Comment by ShizCalev** [comment]
Okay, so after testing it this seems to be working correctly. 

If the brain is damaged (damaged_brain = TRUE), the brain is still counted as a dead brain. They shouldn't be able to talk, can't have their MMI inserted into anything, and for all intents and purposes, are still dead.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/1b50671ca072dd646e98bee971a6d20d5c06a2de/code/modules/mob/living/brain/MMI.dm#L60-L63

**Comment by tralezab** [comment]
fixed by #45187
