### ISSUE TITLE
Possessed singularity drops ghosts that attempt to orbit it

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40714]
Issue reported from  Round ID: 94927 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])  
Reporting client version: 512  
#40348: 'Fire/Lava Fixes & Tweaks' by ShizCalev at commit 7cdd61c1ed  
#40665: 'Revert "Improve youtube-dl subsystem (#40396)"' by subject217 at commit e2d232b3a5  

Round-end slaughter, couldn't orbit the thing, it was just dropping ghosts.

**Comment by SpaceManiac** [comment]
@ninjanomnom

**Comment by ninjanomnom** [comment]
The situation is a bit difficult to replicate locally but I was able to. Orbiting seemed to work fine for orbiting possessed objects and the code for it also wouldn't indicate any problems. I need some more details on how exactly it was failing.

**Comment by Buggy123** [comment]
Isn't there a policy that goes something like "Never, ever, ever, ever, ever, ever, ever, EVER possess singularities. No, not even if it's funny. If you have to ask, the answer is no. If you don't have to ask, the answer is also no."

Technically, this is a bug, yes. But by my understanding it should never be a problem because this situation is _never_ supposed to happen.

**Comment by Barhandar** [comment]
>Isn't there a policy that goes something like

Round-end (shuttle docked and report is up) means all bets are off. And it can be applicable to _other_ possessed objects that don't cause massive mayhem.
>I need some more details on how exactly it was failing.

It was asteroid with engines and it was moving pretty fast + in lag. Maybe it requires said lag to start dropping ghosts? It had the typical "orbit failed" animation on trying to use the verb, that is, ghost starting to circle but then returning to stationary position.

**Comment by Barhandar** [comment]
No. Both shuttle and singularity were at centcomm, docked.
