### ISSUE TITLE
Gorillas, being simplemobs, are immune to stuns

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40712]
Issue reported from  Round ID: 94927 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
Reporting client version: 512  
#40348: 'Fire/Lava Fixes & Tweaks' by ShizCalev at commit 7cdd61c1ed  
#40665: 'Revert "Improve youtube-dl subsystem (#40396)"' by subject217 at commit e2d232b3a5  

They can hold items (including instastun items) and have a knockdown with default melee attack anyway. Add anything that can heal their 220-hp-and-presumably-no-lowhp-slowdown on the fly and it's _ridiculous_.

**Comment by ExcessiveUseOfCobblestone** [comment]
my favorite

all the best parts about carbons with all the best parts of simplemobs.

**Comment by ShizCalev** [comment]
Forums.
