### ISSUE TITLE
Hosting game in Runtime Station, After round start i spawn in space

### ISSUE THREAD

**Issue by AterSoul** [tgstation/tgstation#40722]
Um... this is my first time posting a bug so I don't know what any of the stuff I have to put as im not on a public server, im running my own. I have a problem on the map Runtime Station, basically when I spawn after round start I spawn in a corner in space and start to suffocate. Its also the same splash screen I see when I start the game. Again, sorry if I wrote this bug report wrong.

**Comment by SpaceManiac** [comment]
This usually means the map didn't load. Any error messages in the log?

**Comment by AterSoul** [comment]
> This usually means the map didn't load, probably as a result of misconfiguration. Any error messages in the log?

Nope, and when I compile it no errors or anything. I think its the map itself? Ive been playing on the map for a long while, from many different updates of the TG Branch, and Its done this for a long time.

**Comment by nfreader** [comment]
If you see this again feel free to reopen the issue.
