### ISSUE TITLE
Detomatrix explosions can gib people completely (not delimb), destroying their items

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40749]
Issue reported from  Round ID: 95030 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
Reporting client version: 512
#40348: 'Fire/Lava Fixes & Tweaks' by ShizCalev at commit 7cdd61c1ed
#40665: 'Revert "Improve youtube-dl subsystem (#40396)"' by subject217 at commit e2d232b3a5

I, and other people, are PRETTY SURE THIS IS NOT SUPPOSED TO HAPPEN.

**Comment by Supermichael777** [comment]
Were they coincidentally on top of something that might explode?
