### ISSUE TITLE
indirect agent id nerf by economy

### ISSUE THREAD

**Issue by HighImpactDolphin** [tgstation/tgstation#40745]
.[Round ID]: 95012

[Testmerges]: economy, except it's not really a test anymore

[Reproduction]: so the agent card, the synide item that costs 2tc that you can scan in access and edit its name and job at will, doesn't show any kind of attached blaance or anything when it's examined, when all other ids do. this is obviously a tiny thing but it renders the item essentially totally worthless once the general population learns about this. i have no proposed solution besides allow the syndie to edit the balance to be a fake and to show the department's actual budget on an examine.

agent id vs genuine id right now:
![image](https://user-images.githubusercontent.com/43486478/46568299-e93f6480-c907-11e8-928e-14692b3246b3.png)

sorry if this is the wrong place to post this

**Comment by MrDoomBringer** [comment]
silly goat, it does this because you haven't set the agent ID's account with alt+click
