### ISSUE TITLE
Double Esword causes Out-of-VR death when used for suicide in VR

### ISSUE THREAD

**Issue by Ziegemann** [tgstation/tgstation#40753]
Issue reported from  Round ID: 95044 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Sorry if this issue is kinda bad. I normally don't report bugs, but i found this one out

[Reproduction]; When you are in VR, suiciding with double esword wont boot you from vr, but will kill you and make you a ghost. I have done it multiple times now, and doesn't seem to be a one-time occurrence. I have not tried it  with other items with custom suicides, but it may have the same problem. Ill comment on this issue if i find more items that cause out-of-vr death when used in VR.

**Comment by plapatin** [comment]
you die in the game you die for real

**Comment by FantasticFwoosh** [comment]
Feature.

**Comment by ATH1909** [comment]
I mean, we have emagging for the "you die in the game, you die in real life" thing.

Still, if people want this to be kept in, I wouldn't oppose that. Maybe it'll lead to some plays where you convince your assassination target that committing suicide in VR with a desword doesn't kill you in real life by committing suicide in VR with something that WON'T kill you in real life.
