### ISSUE TITLE
Bugged research console

### ISSUE THREAD

**Issue by CrazyGamer313** [tgstation/tgstation#40768]
Issue reported from  Round ID: 95081 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

The research console only shows research under list view but not under other views as seen here 
![screenshot_1](https://user-images.githubusercontent.com/36242726/46581606-d7f77480-ca3b-11e8-952f-6c63d6164e41.png)
![screenshot_3](https://user-images.githubusercontent.com/36242726/46581607-d7f77480-ca3b-11e8-92ae-c1f33af1f8d6.png)
![screenshot_2](https://user-images.githubusercontent.com/36242726/46581608-d7f77480-ca3b-11e8-987a-8a327f6bf14b.png)

**Comment by Anonymous583** [comment]
Shit's still fucked
