### ISSUE TITLE
Becoming Unborgable After Meth Overdose

### ISSUE THREAD

**Issue by MetalLegs** [tgstation/tgstation#40771]
[Round ID]: #95100

[Reproduction]: After death from meth overdose, if the brain is put in an MMI, it registers as completely unresponsive and cannot be used to borg somebody. Also tested at centcom with Wubli

**Comment by Ratvar** [comment]
your brain died

**Comment by MetalLegs** [comment]
It did. Admin still told me to report on github though

**Comment by XDTM** [comment]
Coded brain damage, this is intended
