### ISSUE TITLE
Backpacks now melt off your back in in a fire, even while wearing full fire protection.

### ISSUE THREAD

**Issue by Robustitron** [tgstation/tgstation#40773]
Recently, maybe just this week, backpacks started melting off regardless of fire protection, so if you're using a flamethrower for anything (or everything), or just trying to put out fires, you're going to lose everything in your backpack when it suddenly disappears off your back.

[Round ID]: # 95105 (happened for a couple of days now but this is the round that got me to report it)

[Reproduction]:
1) Build flamethrower
2) Grab atmos firesuit, helmet & internals (full fire protection) 
3) Light a room on fire, with you in it
4) Wait maybe 10 seconds 
5) Oh shit your backpack melted off
6) Everything else you're wearing is fine.

**Comment by Barhandar** [comment]
Bugreports for testmerged PRs go into the PR's thread, specifically #40348

**Comment by Robustitron** [comment]
Didn't know this was related to a testmerge, I'll go comment there instead

**Comment by Ratvar** [comment]
liek irl

**Comment by ShizCalev** [comment]
Handling in the thread.
