### ISSUE TITLE
H.O.N.K. inteface has double text

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#40782]
![image](https://user-images.githubusercontent.com/222630/46640410-bcb26500-cb20-11e8-8fc4-5be2b5453027.png)

**Comment by AlexTheSysop42** [comment]
...where's the duped text?

**Comment by Daundra** [comment]
If you're referring to the "AirHONK pressure, AirHONK temperature, HONK pressure, HONK temperature", that's the mech's airtank pressure, temperature, and the mech cabin itself's pressure and temperature, respectively. these are both separate things.

**Comment by SpaceManiac** [comment]
not seeing what you're talking about

**Comment by Tlaltecuhtli** [comment]
the honk a doodle is supposed to replace the calibration message
