### ISSUE TITLE
Plasmaman tanks missing on spawn

### ISSUE THREAD

**Issue by Featherfield** [tgstation/tgstation#40784]
[Round ID]: 95134

[Reproduction]: Joining a game mid-round as a plasmaman tends to have your plasmatank missing on most if not all jobs.
Same seems to happen at 50% chance at roundstart sometimes you spawn with it and sometimes you just end up choking to death which makes playing plasmaman basically a suicide.

**Comment by Daundra** [comment]
I was an AI during a round this occured. I was able to buy replacement plasmaman tanks from cargo, but I could've sworn they could be printed from autolathes or protolathes. (Does it need tech? I didn't see it on either.)

regardless I can definitely confirm this happened

**Comment by Barhandar** [comment]
They can't be printed in the lathes, you're confusing them with jumpsuit refills. Plasmeme tanks are special-sprited plasma-containing tanks, not sure whether breathing from regular plasma tanks is possible through.

**Comment by AnturK** [comment]
Can't reproduce, what jobs. Round ID's too.

**Comment by nemvar** [comment]
Well, just make a new issue if this pops up again. Doesn't seem like there are any other reports of this.
