### ISSUE TITLE
error tech node

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#40783]
![image](https://user-images.githubusercontent.com/222630/46640521-698ce200-cb21-11e8-823c-36704d5c8d1a.png)

95133 bagil

**Comment by bruhlookatthisdood** [comment]
ive never seen this
probably dosent exist anymore?

**Comment by Sealed101** [comment]
it exists in the debug disk, probably a fallback node or something. never seen it in an actual round though
