### ISSUE TITLE
Setting custom location with white ship and launching does this ?

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#40797]
![image](https://user-images.githubusercontent.com/222630/46647387-84bd1900-cb44-11e8-9c9b-c57753c55571.png)

Ask Legoscape for details, no clue how this happened.

**Comment by ATH1909** [comment]
What round was this on? Did the missing chunk of the ship get left behind?

**Comment by Dennok** [comment]
Found this problem when rotate ship. When i try rotate ship on place, i get it half erased.

**Comment by kingoftheautism** [comment]
probably same shit with #39906 but less broken

**Comment by Dennok** [comment]
I find it.
`ADMIN LOG: A mobile dock in transit exited initiate_docking() with an error. This is most likely a mapping problem: Error: 8, (Salvage Ship) (the lavaland wastes(JMP) -> The custom location(JMP))`
JMP and i find " the custom location /obj/docking_port/stationary" in the wall of the ship.

**Comment by Dennok** [comment]
![runtime_shuttle](https://user-images.githubusercontent.com/7734424/46666692-06a65400-cbd0-11e8-80e5-f02024ecfaea.png)

**Comment by Dennok** [comment]
I find problem in designate a custom location above shuttle.

**Comment by BeeSting12** [comment]
Sorry for no round ID/server revision, the game crashed and I forgot about grabbing it.

**Comment by ninjanomnom** [comment]
Basicaly a dupe of #39906 and is caused by the same thing
