### ISSUE TITLE
Abducter mutation toxin aliens dont have mindlink

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#40792]
exactly what it says on tin, i dont know if its intended or not but its a dick, can we get a mindlink for toxin ayys

**Comment by ATH1909** [comment]
Can you get it by having your "tongue" surgically removed and then placed back into your throat?

**Comment by XDTM** [comment]
All nonantag abductors should share a channel in theory

**Comment by kriskog** [comment]
Can't reproduce, they get the mindlink now.
