### ISSUE TITLE
AI eye visible to ghosts is completely opaque, blocking doubleclick orbit on anything below it

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40813]
Issue reported from  Round ID: 95196 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
Reporting client version: 512
#40348: 'Fire/Lava Fixes & Tweaks' by ShizCalev at commit e02c04b10c

Combined with the fact AI eye, is top layer, and that it takes at most about three clicks to orbit through the verb (because AI is always first in the list and their eye is second), it's fairly annoying.

**Comment by ShizCalev** [comment]
#40759 already fixes this.
