### ISSUE TITLE
Non-operatives can use the shuttle navigation console but can't get out of it

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#40816]
[Round ID]: 95200
[Reproduction]: Click on the navigation console without proper access.

Maybe I'm dumb but when I clicked on the console I was taken into the camera for shuttle movement but had no hud elements nor could I back out of it. I didn't come out of it till an operative came over and shot me into crit.

**Comment by JetBrody** [comment]
I get this even on regular navigation consoles such as the white ship. I had to get an admin to get me out of the navigation. The only other method I've found that works is resting then getting back up.

**Comment by Sealed101** [comment]
doesn't seem to be an issue anymore, though non-ops should really not be able to interact with those consoles in the first place
