### ISSUE TITLE
most mobs can dump containers out

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#40811]
mobs like blob overminds, sentient diseases, revenants, just about every other non-observer mob can dump containers via click dragging it onto the ground

**Comment by MrDoomBringer** [comment]
![image](https://user-images.githubusercontent.com/29008542/46692168-95b56b00-cbd4-11e8-90e2-61e34ac8afc1.png)
have a suspicion like someone fucked up a parentheses or two
