### ISSUE TITLE
Reactive teleport armor jumps drop orbits.

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#40828]
@ninjanomnom 

1. Be a ghost orbiting someone with RTA.
2. They get hit by something and teleport.
3. Your orbit drops.

Nothing else to it.

**Comment by GunHog** [comment]
It is not limited to the RD's armor, I lost my orbit around a wizard that blinked.

**Comment by ShizCalev** [comment]
Tesla orbiting drops orbits constantly

**Comment by SpaceManiac** [comment]
@ninjanomnom

**Comment by subject217** [comment]
@ninjanomnom @ninjanomnom

**Comment by ninjanomnom** [comment]
lol you don't need to ping me so much, make a seperate issue for tesla orbiting @SpaceManiac that would be a separate issue

**Comment by ninjanomnom** [comment]
Works perfectly fine locally using both ghost orbiting and wisp orbiting

**Comment by fludd12** [comment]
I had a similar issue when someone teleported using a quantum pad. Is forcemove dropping orbits sometimes...?

**Comment by ninjanomnom** [comment]
If it's sometimes then no it's not forceMove's fault most likely. You can maybe blame lag and #40842 should help a bit with that.

**Comment by kriskog** [comment]
Can't reproduce
