### ISSUE TITLE
Scientist backpack has no inhand sprite

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#40830]
Zaracka says this is so, not tested however

**Comment by subject217** [comment]
What happened to zaracka? I know they left /tg/, where'd they go?

**Comment by SpaceManiac** [comment]
I feel like it used to

**Comment by nemvar** [comment]
Backpacks use a lot of item_states that don't actually exist. Send help.

**Comment by nemvar** [comment]
Closing in favour of #45385
