### ISSUE TITLE
Space Pirate Data Siphon does not empty when it dispenses credits.

### ISSUE THREAD

**Issue by penterwast** [tgstation/tgstation#40834]
Spam clicking an active data siphon will dispense 5 then 10 then 15 and so on credit chips, never resetting.  Pirates can get their objective in just a few minutes without leaving the ship.

[Reproduction]: 
1. Trigger Space Pirates event
2. Spawn as pirate, fly to station
3. Activate data siphon
4. Spam click data siphon
5. In a few minutes you will be making multiple 1000 credit chips per second.

**Comment by AnturK** [comment]
credit removal got cut off with change to holochips

**Comment by XDTM** [comment]
oh boy
