### ISSUE TITLE
able to see AI eye as a living human?

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#40837]
i was killing a malfunctioning AI, its eye object appeared over its core, i wasnt able to easily click the core because its eye was covering it. think it might not be correctly invisible to stuff like mesons? not sure. 

Important things that might be relevant:
AI was malfunctioning
I was wearing mesons
It was a traitor round, if AI multitool reveals the AI eye then that might be something
AI eye was directly over its core when I could see it, may have been visible elsewhere without me noticing

**Comment by Anonmare** [comment]
Could it be due to Meson Vision's See_Invisible_Living?

**Comment by ShizCalev** [comment]
AI detector is setting the AI's camera to INVISIBILITY = 0.

**Comment by wesoda25** [comment]
This happened for me too that round, I won’t swear by it but I’m 85% certain I wasn’t wearing mesons.

**Comment by MrDoomBringer** [comment]
![image](https://user-images.githubusercontent.com/29008542/46871700-1e641f00-ce00-11e8-9145-e836f982dbdf.png)
mesons unneeded

**Comment by Tlaltecuhtli** [comment]
@Not Pickles#1274
