### ISSUE TITLE
Players attack organ harvester when using screwdrivers on them

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#40841]
```
Fulcrifera Accurata has hit the organ harvester with the hand drill!
You open the maintenance hatch of the organ harvester.
```

When harvester is open, it also gives no indicator that you first need to close it if you want to unscrew the maintenance hatch.

**Comment by MimicFaux** [comment]
There's a couple machines like that in medical that have always needed to be closed first. Sleepers, and cryotubes come to mind.
