### ISSUE TITLE
Inhands stopped updating

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#40859]
Issue reported from  Round ID: 95275 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Happened for many people on the server. If you had an item in your hands and dropped it, the inhand icon would still be there. After that, picking up/dropping items wouldn't put on/take off the inhand icon overlay on you.

**Comment by PKPenguin321** [comment]
Seems to apply to clothing overlays as well

**Comment by Tlaltecuhtli** [comment]
im not sure if same but i had an inquisitor hat and tried wearing a mask but it wouldnt update my sprite , changing shoes worked

**Comment by Barhandar** [comment]
Can confirm, round 95257 was full of people with stuck in-hands.

**Comment by ShizCalev** [comment]
Likely due to the server running on the 512.1452

http://www.byond.com/forum/?post=2404218

**Comment by PKPenguin321** [comment]
Haven't seen this pop up again lately and we just updated to a new stable byond build, right? Closing this on that basis
