### ISSUE TITLE
Reconstructing N2O Supply Console makes for a BAD time

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#40858]
Round: 95274

Test merges:
#40747: 'Gives the curator EVA access' by vuonojenmustaturska at commit ac82a3f288
#40348: 'Fire/Lava Fixes & Tweaks' by ShizCalev at commit 8b5f4f7c42
#40821: 'Adjusts ignition snowflake in hotspot_expose to enable welders etc to start plasma fires again' by vuonojenmustaturska at commit 92f548efce
#40778: 'z_travel_pull_fix' by Dennok at commit 1d239c8cfa

N2O supply console got broken in an explosion, I replaced the glass and reconnected it to the N2O supply. It then began listing an ungodly number of gases and other stats, see gifv below.

[Imgur](https://i.imgur.com/0HvxwMX.gifv)

**Comment by imsxz** [comment]
ongoing round, wait for it to end etc etc. 

When bobbah had constructed the new console, it showed as just the base tank control computer on vv instead of the n2o control.

**Comment by Dennok** [comment]
Basical problem. Builded console show info from all sensors.

**Comment by 81Denton** [comment]
This can be fixed by giving each console subtype a unique circuit board that lets people rebuild it into the same console

**Comment by Dennok** [comment]
This way work, but what if you full lose consoles and circuits?

**Comment by 81Denton** [comment]
If that PR gets merged, I will make another one that adds it to the protolathe, tech storage or something.

**Comment by Dennok** [comment]
better fix reconnect button in console
it propper connect to injector and went
but it dont set right sensor id

**Comment by Dennok** [comment]
Or add reconect button for sensor, it seems like reconect reconnects only to vent and injector.
