### ISSUE TITLE
igniters in toxin no longer ignite

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#40867]
u cant ignite plasma with them

**Comment by HomocidlePancakes** [comment]
It just takes multiple tries

**Comment by 81Denton** [comment]
Has it been like this since the ancient atmos bug was fixed or is it a recent issue?

**Comment by subject217** [comment]
Pretty sure this was borked by https://github.com/tgstation/tgstation/pull/39128 or https://github.com/tgstation/tgstation/pull/38232. Probably the former if I had to guess as I swear this used to work. Igniters and sparks are super fucked right now but this is more of a really bad oversight than a bug. https://github.com/tgstation/tgstation/pull/40821 helped with this for most other hotspots but not sparks.

**Comment by subject217** [comment]
Has nothing to do with the atmos bug fix. It's https://github.com/tgstation/tgstation/pull/37426 that caused the problems in the first place and then the aforementioned PRs that attempted to fix these issues by modifying hotspot_expose values.

**Comment by JamesDenholm** [comment]
Yeah, I'm getting the same. Manually igniting with a hand-held igniter works, but the in-built igniters don't.

A simple fix to this might be just removing or reducing the cooldown on the button/igniters, to see if moar spam results in actual burning fire.

**Comment by 81Denton** [comment]
Tbh I'm for just reverting #37426 since it provides zero interesting gameplay interactions while creating a ton of annoying bugs, like this one.

**Comment by JamesDenholm** [comment]
That PR has been reverted already -- #38217 .

**Comment by 81Denton** [comment]
Actually it's been re-reverted, see #38232

**Comment by JamesDenholm** [comment]
Then revert that instead famalama

**Comment by JamesDenholm** [comment]
Actually, it might just be good enough to increase some of those calls (which is for sure the actual problem here) instead of re-re-reverting something this significant.

**Comment by subject217** [comment]
I'm sure Deathride is done arguing about it. No point in pinging them. If you PR a revert you should also revert all changes to hotspot_expose args since that PR was merged. Maintainers probably don't want to revert it, so you're likely better off finding a way to improve it, like Naksu did very recently.

**Comment by JamesDenholm** [comment]
Yeah, 's all good, I think I know how I want to take a crack at this.
