### ISSUE TITLE
Musician's beacon doesn't do anything on interact

### ISSUE THREAD

**Issue by HeddyLamarr** [tgstation/tgstation#40860]
[Round ID]: 95283

[Reproduction]: 
1. Choose Musician trait / quirk in character set-up
2. Enter game through round start or join in progress.
3. Interact with the express delivery beacon using Z key, clicking, alt-clicking, hitting yourself or dragging on to yourself.

If for some reason the beacon can be interacted by using some other dark ritual which isn't described here I recommend it's changed to something more sane.

**Comment by MrDoomBringer** [comment]
theres already a PR up that fixes this u square
#40820
