### ISSUE TITLE
Syndicate Hardsuit and Elite version use a helmet that otherwise doesn't exist the first time it's engaged

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#40874]
The first time you engage the helmet, it's a space proof version with no light, or what you'd otherwise get for any regular hardsuit. The combat mode toggles then allow you to switch to either the combat mode (fast, no light) or the space mode (spaceproof, light). 

This is why the hardsuits use the wrong icon when you first engage the helmet. The ideal fix would be revamping the combat mode code with a separate action button for engaging/disengaging the flashlight regardless of mode, and adding a 3rd helmet icon for these two. Which would also make https://github.com/tgstation/tgstation/issues/28339 super trivial to fix.

**Comment by ArcaneDefence** [comment]
This is still an issue.
![image](https://user-images.githubusercontent.com/51932756/114258371-4efe8280-9983-11eb-9741-6ee3fb2d7b60.png)
