### ISSUE TITLE
Permabrig sustenance vendor doesn't dispense things for people with prisoner IDs.

### ISSUE THREAD

**Issue by plapatin** [tgstation/tgstation#40889]
Issue reported from  Round ID: 95340 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

The sustenance vendor in perma has it's items listed for $0 instead of free, and because prisoner IDs don't have bank accounts associated with them, they can't actually get their free items from the vendor.

Steps to reproduce:
1. Obtain prisoner ID.
2. Attempt to vend thing from sustenance vendor.

**Comment by evsey9** [comment]
shouldn't have committed crime to get into permabrig in the first place, then

**Comment by bgobandit** [comment]
probably caused by https://github.com/tgstation/tgstation/pull/40449

@BeeSting12

**Comment by BeeSting12** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
this should of been fixed awhile ago, I tested it, has anyone touched the vending machine price stuff since?

**Comment by Iamgoofball** [comment]
wait which map is this, is the vendor on or off station

**Comment by Iamgoofball** [comment]
goddamn it, this means it isn't tripping the offstation freebies

i'll check it out

**Comment by timothymtorres** [comment]
@Iamgoofball were you ever able to test this?

**Comment by Sealed101** [comment]
labor camp sustenance vendor does in fact give freebies; it's the **_on-station permabrig_** vendors that are capitalist. at this point i'm not sure if that's intended or not
