### ISSUE TITLE
reflectors can make infinite loops

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#40881]
people keep (unintentionally) lagging the fuck out of the projectiles subsystem via emitters+reflector boxes infinitely making them bouncing back and forth. End up having to delete them and bwoink the creator every time. I don't think a cap to how many times an emitter can reflect would be too awful or change gameplay that much.

**Comment by Tlaltecuhtli** [comment]
intended

**Comment by evsey9** [comment]
looks like you'll have to optimize your code for once

**Comment by ma44** [comment]
https://github.com/tgstation/tgstation/pull/33126

**Comment by evsey9** [comment]
Which means it is a FEATURE

**Comment by imsxz** [comment]
i cant see a situation where an emitter beam would need to travel more than 256 tiles

@evsey9 i know thats a bait comment but im taking it anyways. thats like saying "just optimize ur code" when someone crashes the server via making 15 stage 6 singulos

**Comment by imsxz** [comment]
and yeah i realize its intended but it's such a simple way to lag out a rather important subsystem. im not saying autism emitter loops need to go, im saying they should be limited in some way to not cause 600ms delay in projectiles instead of the normal 0-3ms delay. I'm not a performance expert so my only suggestion would be to keep them limited in some way, as it'd probably have the least effect on gameplay as opposed to gimping how projectiles work. Surely there's a reasonable balance between "emitter fortress that crits people who run into it" and "1 guy sets up looping emitter beams for the lulz and now the entire station is in matrix mode where projectiles hang in the air for long periods of time"

**Comment by YakumoChen** [comment]
15 teslas is more likely then singulos, because I've done it multiple times

**Comment by ExcessiveUseOfCobblestone** [comment]
People who want it retained can optimize it, the immediate desire is to stop the crashing rather than thinking of a creative approach.

**Comment by Carbonhell** [comment]
Perhaps if two emitter beams touch, unify them and increase some sort of power variable? Could also make their icon bigger for memes.

**Comment by zamolxius** [comment]
just make the reflectors increase a heat value each time it reflects,  and if going over that cap melt down,  have the temperature cool down fast enough to guarantee a decent flow of beams just not too over the top

**Comment by davethwave** [comment]
Carbonhell's and Zamolxius's ideas seem fine, don't know which one would be easier to bring to reality though.
