### ISSUE TITLE
Observing people sometimes only shows the lighting layer

### ISSUE THREAD

**Issue by Metroidlover** [tgstation/tgstation#40899]
Round Id: 95381

So, I think it is caused when you observe an admin while they have an admin panel open, It has only happened on two occasions with IMSXZ, but it disappears moments before they respond to me. I have had confirmation from at least one other player that it isn't just a me thing and they got the bug too, but it has disappeared before any screenshots were taken.

**Comment by Barhandar** [comment]
Sounds like you're just lagging and it takes sweet time to load non-lightinglayer parts.
