### ISSUE TITLE
You no longer remain upright while buckled and resting/unconscious/dead

### ISSUE THREAD

**Issue by Daundra** [tgstation/tgstation#40891]
[Round ID]: 95347

probably as a result of the new crawling/slip rework.

Picture related (viewer discretion is advised):
![dreamseeker_2018-10-12_13-11-55](https://user-images.githubusercontent.com/5360736/46883679-d1dd0b80-ce20-11e8-9f2b-56ecdadd2641.png)

Reproduction is simple, have someone grab you aggressively, try to climb on them like normal, find that you can still rest while on their backs. Not sure if this is an intended mechanic but it looks silly. In my personal opinion, I hope this is not fixed but I was told it's probably a bug so I'm reporting it anyways.

(ADDENDUM: before people complain about rule 8, I was crawling around the station naked ever since the shift started. This was not in any way intended to be sexual.)

**Comment by ShizCalev** [comment]
lmao

**Comment by Ratvar** [comment]
same issue https://github.com/tgstation/tgstation/issues/40906 ?

**Comment by Iamgoofball** [comment]
Shut it down
