### ISSUE TITLE
Duplicate modes in the Command Report appear to reveal the mode

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#40895]
[Round ID]: #95365

Had 2 rounds where Revs showed up twice in the Command report, got 2 rev rounds. 

Then Nabski banned me when I told him I would post it as an issue on Github instead of telling him why I thought we might have Revs. What a great guy.

**Comment by imsxz** [comment]
might be coincidental? i'll check for it but there's 3 variants of revs(speedy, extended, normal). although only 1 is in rotation, all 3 can appear in the command report. All gamemodes can show up on the report if i'm not mistaken (I see sandbox, monkey, etc on it a lot), all 3 rev modes have the same command report so I'd figure it's pure coincidence.

**Comment by SpaceManiac** [comment]
If that is the case it's still a bug, the command report should not contain duplicates

**Comment by Robustin** [comment]
Are the variants truly their own mode though?

**Comment by PKPenguin321** [comment]
command report should just be fluff and the crew has no good reason to even have a hint as to what the mode should be, change my mind

**Comment by GunHog** [comment]
> command report should just be fluff and the crew has no good reason to even have a hint as to what the mode should be, change my mind

That is what I always assumed it was. Useless fluff that explains the type of rounds the server has in its code. I do not remember it ever being a 'hint' for the mode, but just to say what modes are *possible*.
