### ISSUE TITLE
Buckling horizontal (for example, dead) people to seats no longer makes them upright

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#40906]
Issue reported from  Round ID: 95391 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])  
Reporting client version: 512

This looks bad and prevents faking that someone is alive by buckling them, plsfix.

**Comment by Ratvar** [comment]
Same issue? https://github.com/tgstation/tgstation/issues/40891

**Comment by ShizCalev** [comment]
yeah same issue.
