### ISSUE TITLE
felinids are still in the game

### ISSUE THREAD

**Issue by evsey9** [tgstation/tgstation#40913]
[Round ID]: 95416

[Testmerges]: #40873: 'New sprites for gases' by nicbn at commit 6dbfd70f4e
#40876: '[DNM UNTIL 1453 IS LIVE ON SERVERS] Restores the hazy effect to the saboteur borg's chameleon module' by vuonojenmustaturska at commit 60b686994d
#40880: 'Nerfs crawling speed by 100%' by kevinz000 at commit 96f7a42aa7
[Reproduction]: 1. Launch SS13
2. Join the round as some role
3. Go to medbay
4. Ask to get healed
5. Watch in horror as a mutant that was supposed to be removed a day ago due to poll results says "Do you need helpies~?"

![default](https://user-images.githubusercontent.com/7791364/46910234-6434fa80-cf5a-11e8-9f53-533716541ad0.png)
![default](https://user-images.githubusercontent.com/7791364/46910262-c68dfb00-cf5a-11e8-9376-b28c4dc3df75.png)

I assume this is just a bug and will be fixed shortly to improve the ss13 experience

**Comment by evsey9** [comment]
related pr https://github.com/tgstation/tgstation/pull/40707

**Comment by AlexTheSysop42** [comment]
Did you check the vote that's actually being used for the decision? (The filtered one)

**Comment by evsey9** [comment]
which one is that

**Comment by Barhandar** [comment]
>https://atlantaned.space/statbus/round.php?round=95412
>[2018-10-13 19:29:09.272] SAY: Evsey9/(Bonzi Buddy) "Its all helpies" (AI Chamber (33, 138, 2))
>[2018-10-13 19:29:12.265] SAY: Evsey9/(Bonzi Buddy) "Helpies&#39; fault" (AI Chamber (33, 138, 2))
>[2018-10-13 19:29:43.271] SAY: Evsey9/(Bonzi Buddy) (priority announcement) "helpies is now illegal" (AI Chamber (33, 138, 2))

You seem to be a bit obsessed with helpies. All three mentions in the entire game.txt for the round.

**Comment by evsey9** [comment]
helpies IS catspeak

**Comment by Barhandar** [comment]
Surprising lack of any cats saying that.

**Comment by Cw3040** [comment]
statbus doesn't filter votes from players with less than 1 minute of playtime, last time we saw the filtered version it was about 190-100 in favor of keeping catpeople

**Comment by evsey9** [comment]
guess i'll die

**Comment by Cw3040** [comment]
man where's shezza to spam catgirls when you need him

**Comment by YakumoChen** [comment]
goof btfo once again
![laughingcheetah](https://user-images.githubusercontent.com/10399117/46912399-14f3c780-cf64-11e8-93ef-fcab14642edf.png)

**Comment by evsey9** [comment]
That's not even a cat that's a serval

**Comment by evsey9** [comment]
@YakumoChen get your animes straight

**Comment by Jordie0608** [comment]
![capture](https://user-images.githubusercontent.com/4343468/46913518-3099b500-cfda-11e8-9d34-689439661f57.PNG)

**Comment by evsey9** [comment]
Do I look like I'm a fucking biologist

**Comment by evsey9** [comment]
https://camo.githubusercontent.com/5e82c62488e91e27c66a7bec4909ca98add5f2ce/68747470733a2f2f66696c652e686f7573652f5336677a2e706e67 looks like the "no" votes won :^)

**Comment by Jordie0608** [comment]
There's no point in this being an open issue.
