### ISSUE TITLE
You may be able to burn away lava.

### ISSUE THREAD

**Issue by fludd12** [tgstation/tgstation#40912]
Reproduction: I was a lifebringer, trying to smelt some plasma popcorn style by throwing it onto lava. Apparently this is... not optimal. It made a massive plasma fire burst which nearly killed me, but notably also removed most of the lava nearby.

Round ID: #95410

**Comment by evsey9** [comment]
fight fire with fire

**Comment by kingoftheautism** [comment]
Tried to reproduce. Throwed 5-6 stacks of plasma (ore) on lava, it burned, but nothing happened. My repo is a bit outdated though, so it still might be possible

**Comment by Barhandar** [comment]
Round IDs please.

**Comment by fludd12** [comment]
The first round is oddly enough in my first post, but it... doesn't show up? Editing to put it elsewhere.

**Comment by fludd12** [comment]
I don't think so - I was caught in the fireball the first time, and didn't get any of the related flash or anything.

**Comment by Therapist1** [comment]
I’ve been using this to ford lava rivers for ages, I didn’t consider it much of a bug, though.

**Comment by Barhandar** [comment]
You can't popcorn smelt plasma; also the random lava rivers can be "cooled" this way but any of the mapped ones (gulag, xeno chamber, syndie base) cannot.

Sounds like something isn't setting turfs right!

**Comment by nfreader** [comment]
Wasn't able to reproduce this. Just caused a big ole fire that went out on its own pretty quick. Reopen if you see it again!
