### ISSUE TITLE
Lizard tails stick out of cryo pods

### ISSUE THREAD

**Issue by harmonyn** [tgstation/tgstation#40922]
![lizzer tail](https://i.imgur.com/55unXYR.png)

my liz build: Tail Light Tiger, Snout Sharp + Light, Horns Angeler Frills, Spines Short + Membrane, Body Markings Light Belly, Legs Digitigrade (but those don't work currently)

**Comment by Ratvar** [comment]
Yeah lizards shoulndn't fit in cryo, bug

**Comment by nicbn** [comment]
@optimumtact #44745 reverted the fix, please reopen this issue
