### ISSUE TITLE
pipes dont delete 0 mol gases

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#40921]
95452

http://take.ms/wmsTJ

**Comment by duncathan** [comment]
probably a visual thing rather than a failure to garbage collect but ill peep

**Comment by Dennok** [comment]
There is rounded export issue, it have a quant doles of moles and round down it to 0, but it cant remove it if it dont real 0.

**Comment by LemonInTheDark** [comment]
as dennok said, this is the result of QUANTIZE being too high. Not a whole lot we can do about it however, as we need the space to allow for fusion. Maybe if fusion temps bite the dust someday we'll be able to have sane gas removal. I can only dream.

**Comment by Dennok** [comment]
What about transfer fusion in machine?

**Comment by LemonInTheDark** [comment]
Fixed by #57634. I'm sorry dennok
