### ISSUE TITLE
Jani borg mop not wet

### ISSUE THREAD

**Issue by MegaEmpirical** [tgstation/tgstation#40924]
Prior to the janitor changes https://github.com/tgstation/tgstation/pull/40141 jani borg mop was always wet, now it's dry and requires a bucket that has been filled by someone with hands to use.

**Comment by ShizCalev** [comment]
Not seeing anything in #40141 that would've changed it. Will note that there is an upgrade for cyborgs that gives them the automatically refilling mop;

https://github.com/tgstation/tgstation/blob/b31b5a8db21f79cf33dd19a7fd020440799794fb/code/game/objects/items/robot/robot_upgrades.dm#L223-L249

**Comment by kriskog** [comment]
Janiborgs now have a bucket
