### ISSUE TITLE
Flora is growing on the asteroids in space

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#40930]
Round ID: 95488
Send help

![image](https://user-images.githubusercontent.com/12382984/46925090-07047c00-d022-11e8-9380-cc49ccc0a9ec.png)

**Comment by Iamgoofball** [comment]
life, uh, uh, finds a way

**Comment by kingoftheautism** [comment]
I heard microbes can survive in lava, so it make sense (though I'm still thinking "WTF") to, uh, uh, yeah, like Goof said above - for life to find a way.

**Comment by FantasticFwoosh** [comment]
This is slightly jarring but to counter-suggest, asteroids should have their own limited pool of plant types. 

Seeing a deep space cactus is a bit immersion breaking, its a plant and can't be waved away as adventurous mycellium carried into the atmosphere by mining shuttles.

**Comment by tralezab** [comment]
Asteroids are really empty right now and while i'm sure that seems about right maybe they should have silly plants

something something make some randomly generated plants stay on lavaland and some in space and some, both

**Comment by tralezab** [comment]
i'm gonna try something like this but i really can't sprite so
