### ISSUE TITLE
Digitigrade Legs option not working

### ISSUE THREAD

**Issue by ModDownloading** [tgstation/tgstation#40948]
[Reproduction]: Select Lizard in character creation, select Digitigrade Legs and save, try to join the game with this option enabled.

When I tried to do this, I still had normal legs as evidenced by the fact I was wearing shoes roundstart.

**Comment by CRTXBacon** [comment]
I get this too. I have my normal lizardman set to use digitigrade legs and always spawn with normal legs instead.

**Comment by Sealed101** [comment]
bless kapu for fixing digi legs (for sure this time)
