### ISSUE TITLE
Loudness Booster glitch

### ISSUE THREAD

**Issue by mk2999** [tgstation/tgstation#40949]
Issue reported from  Round ID: 95529 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

The loudness Booster for PAI's makes it so that you cant stop the music once you start it and if you try to load it up again it will start up a new loudness Booster tab, basically making it a new instrument, meaning you cant stop old songs but you can add more songs on, I havn't tested to see to how many song layers you can get going at once but im pretty sure its infinite.

**Comment by CRTXBacon** [comment]
Also multiple songs at once will, after a few seconds, interfere with eachother screwing with theirnotes and completely overriding all other game audio. Happens when two pAIs playin a recorder are nearby too.
