### ISSUE TITLE
Dying while the curse of mundanity is upon you will turn your ghost vision brighter then a scene from Cyberpunk 2077

### ISSUE THREAD

**Issue by plapatin** [tgstation/tgstation#40950]
Issue reported from  Round ID: 95529 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

You know that curse of mundanity thing that sometimes happens when you get too much brain damage?
If you die while that's active your lighting bugs the fuck out.

Steps to reproduce:
1. Get curse of mundanity via brain damage
2. Fucking die

**Comment by AnturK** [comment]
curse of mundanity is the default name for the status effect alert so you need some more detail which brain damage effect it was.

**Comment by XDTM** [comment]
oh shit i never made the hypnosis status effect icon

**Comment by XDTM** [comment]
probably the black and white filter during the hypnotic stupor status effect, should be able to reproduce the bug with the monochromatic quirk as well

**Comment by plapatin** [comment]
@XDTM Yeah, hypnotic stupor was the one. My bad.

**Comment by plapatin** [comment]
I should also mention there were quite a few glowshrooms around when I died, so that may have something to do with it.

**Comment by dragomagol** [comment]
Unable to replicate with monochromia, hypnotic stupor, and with glowshrooms.
