### ISSUE TITLE
OH GOD WHERE DOES THE NOSE GO WHEN YOU PUT UP THE HOOD

### ISSUE THREAD

**Issue by plapatin** [tgstation/tgstation#40964]
Reporting client version: 512

AAAAAAAA

![image](https://user-images.githubusercontent.com/43917079/47017108-40161c80-d106-11e8-82bf-eb7ca9f00954.png)

![image](https://user-images.githubusercontent.com/43917079/47017125-4c9a7500-d106-11e8-9b91-19e44073a1e7.png)

**Comment by ShizCalev** [comment]
HIDEFACE flags_inv memes.

https://github.com/tgstation/tgstation/blob/88a2408442ace013d47e166c30f29d1f324eca6f/code/modules/mob/living/carbon/human/species.dm#L544-L546

Would need a minor refactor to move it into another flag since HIDEFACE is also what makes you "Unknown"

**Comment by SgtxRootbeer** [comment]
Same things happens to lizard snoots with syndie hardsuit iirc

**Comment by ShizCalev** [comment]
it'll affect anything that has the HIDEFACE flag (such as syndie hardsuit helmets)
