### ISSUE TITLE
Mimes cannot use ventriloquist dummies

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#40969]
Round ID: 95563
Testmerges: None.

The mime cannot use the [ventriloquist dummy](https://github.com/tgstation/tgstation/blob/55a768fef109af873291a4383e1b735a5e5969c5/code/game/objects/items/toys.dm#L1376) because the mime cannot channel their voice through the doll without the speaking spell only availible on a 300/300 counter. All attempts to speak are stopped until the spell is used.

- As a side suggestion to this fix, add the channel description for the doll like any radio headset, as currently this is not explained at all and i only tangentally learned that it was :r or :l that activated it by doing some seriously heavy digging around sphaghetti code.

This stopped my 'The Stanley Parable' narrator doll gimmick, **_my dissapointment is immeasurable and my day is ruined_**.

**Comment by Barhandar** [comment]
~Realism~, you can't speak through the doll without actually speaking.

Also :r and :l aren't channels, they're "speak into thing in your right/left hand" binds.

**Comment by moonheart08** [comment]
Maybe add the a possessable doll instead somewhere on the station. It could be equally funny if you get a ghost who wants to cooperate.

**Comment by ExcessiveUseOfCobblestone** [comment]
This was already attempted but it would require a fun change to our say code which no one wants to touch.

**Comment by ExcessiveUseOfCobblestone** [comment]
Actually the above is only partially true, you could easily just create a button for the dummy with input box i guess but it would be only slightly less obnoxious than having to use *custom for emotes while muted.

**Comment by bgobandit** [comment]
lmao someone finally reported it 

this has been a bug ever since dummies were introduced I think, to the point where I thought it was intended behavior

**Comment by bgobandit** [comment]
also the stanley parable sucks

**Comment by timothymtorres** [comment]
Ventriloquism requires speaking, why is this even a debate?
