### ISSUE TITLE
Gas mixer is not working if one side is empty

### ISSUE THREAD

**Issue by Mongoon** [tgstation/tgstation#40960]
Issue reported from  Round ID: 95550 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

I know for a fact that before, gas mixer could pump if one of the nodes was set to 100% and was supplied for that node. It would pump from that node, while the other one could be empty, full, didn't matter. Now it seems gas mixer will not pump from a node set to 100%, if the other one is empty - which is dumb. It's not going to use the other node but still needs pressure in it to work. That breaks my ATMOS setups and is just dumb.

**Comment by ShizCalev** [comment]
@duncathan @vuonojenmustaturska @SpaceManiac didn't one of you guys fix this a while back?

**Comment by SpaceManiac** [comment]
Probably caused by #40525
