### ISSUE TITLE
Random advanced diseases are seemingly broken

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#40975]
Needs reproducing but I observed a dude get a random advanced disease from the outbreak event, it had stage speed 5, but he remained on stage 1 for the next 40 or so minutes. Random advanced diseases are a subtype of advanced diseases that get random symptoms from the pool. Either bugged or insane luck, worth looking into.

**Comment by XDTM** [comment]
The original target for this event is a carrier, meaning he's immune to the disease itself. It probably also skips stage processing because of that.

**Comment by kriskog** [comment]
This is intentional, as XDTM said. Initial host is a carrier, which makes it skip staging.
