### ISSUE TITLE
i cant play youtube sounds help

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#40979]
Youtube-dl URL retrieval FAILED:

ERROR: pRCIjgdnt2k: YouTube said: This video is unavailable.

**Comment by Iamgoofball** [comment]
Can someone close this, blatant shitposting on the repo

**Comment by AlexTheSysop42** [comment]
I can't access YouTube either (at all), pretty sure it's on their end

**Comment by optimumtact** [comment]
youtube is down

**Comment by PKPenguin321** [comment]
>tfw you have oggs and midis you can play instead

😎
