### ISSUE TITLE
No ability to deconstruct "Doors"

### ISSUE THREAD

**Issue by Zaffinomlb** [tgstation/tgstation#40971]
Issue reported from  Round ID: 95570 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Was on metastation and was trying to remove the wooden doors in the maintenance bar. Was not able to with any tool use or was I able to via how the wiki stated.

Tested further with Iron door and to the same effect.

**Comment by FantasticFwoosh** [comment]
Use a pickaxe, its very shoddy code but otherwise you will have to just smash it.

Metal crude doors melt down with a welder.
