### ISSUE TITLE
Layered piping extends past the tile they're on

### ISSUE THREAD

**Issue by nichlas0010** [tgstation/tgstation#40977]
Which means that if you have two tiles, both of which having a layered pipe on it but one being plating, and one having a proper floortile, it looks really really odd. This example has a door in it, which just makes it look even worse:
![image](https://user-images.githubusercontent.com/20558591/47053154-07c91980-d1ac-11e8-9b79-9cea4c5bea7e.png)
![image](https://user-images.githubusercontent.com/20558591/47053197-2f1fe680-d1ac-11e8-8752-48309942f5f5.png)

[Reproduction]: # Put layered piping on 2 tiles, then put a floortile over one but not the other. For even worse results, put a door on the plating tile

And yes I used the hidden subtype, not visible.

**Comment by kingoftheautism** [comment]
old bug

**Comment by SpaceManiac** [comment]
Fixable but would require giving layers their own sprites (for pipes and for the pipe overlays used by components) rather than just using pixel_x/pixel_y.
