### ISSUE TITLE
Proper typing of beacons that dispense items

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#40991]
`/obj/item/musicbeacon`
`/obj/item/herobeacon`
`/obj/item/holybeacon`

These all do literally the exact same thing in nearly the same way, certainly enough to require they be typed properly.

`obj/item/beacon` is already taken so may need to be typed to `/obj/item/choice_beacon` with each of these three a subtype

Putting this as an issue to remind myself and others should they want to do it for easy GBP.

**Comment by FantasticFwoosh** [comment]
Noted & seems agreeable, how high priority is this? Ill put it into my next hero beacon PR or find some time to sort it out as a PR as its own.

**Comment by ExcessiveUseOfCobblestone** [comment]
the chaplain one is slightly different/more "challenging" because it adds the decision to a global variable. You should have it otherwise be the same however.

It's meh priority right now, increasing the more you add because it becomes more of a pain.
