### ISSUE TITLE
The Head of Personnel job has no access

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#40996]
(Sybil round 95626)

The ID spawns with no access, setting the job to Head of Personnel in the console sets it to no access. how to reproduce: be HoP/spawn yourself in as HoP

maybe somehow related to this? https://github.com/tgstation/tgstation/pull/40892 @Cyberboss

**Comment by plapatin** [comment]
hahahaha what

**Comment by SpaceManiac** [comment]
Caused by the testmerge of #40907
