### ISSUE TITLE
Inconsistencies with Economy

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#41000]
We’ve converted to holo chips but maps need to be updated, or a new feature added. 

As far as I know, maps weren’t touched (at least box), and paper stacks still exist. Off the top of my head the bartender has some cash in their backroom on box. 

Similarly, numerous space ruins are home to paper bills (although this may be on purpose given the nature and lore of some of these ruins). Suggestion: exchange machine? 

If you’d like, tomorrow I could look for some spawns.

**Comment by 81Denton** [comment]
![lodsa emone](https://user-images.githubusercontent.com/32391752/47152058-d64f6b80-d2db-11e8-88c7-24a54f9c7bd3.JPG)

**Comment by Tlaltecuhtli** [comment]
another oversight is that the bank machine accepts credits instead of chips

**Comment by Iamgoofball** [comment]
You can still slam space cash into your ID card to convert it to money. At least, you should be able to. If it was removed I'll fix that.

**Comment by ShizCalev** [comment]
bring back the mint, 2018

**Comment by ShizCalev** [comment]
@Iamgoofball 
https://github.com/tgstation/tgstation/pull/40312/files#diff-e7dc214ac349749f475d0c9ff6fb7ba8R144

you never added it

you didn't even `return ..()` at the end of attackby lol

**Comment by Iamgoofball** [comment]
It probably got removed when the holochip thing was done.
