### ISSUE TITLE
Romerol zombies don't have claws in their hands when they first rise

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#41012]
## Reproduction:
Acquire a romerol tumor, die in any way, when you rise you don't have claws. Picking up and dropping an item will put a claw into your hand.

**Comment by ATH1909** [comment]
Hm.

I wonder what the best items to dual-wield as a zombie would be (if you knew that you could only have two non-claw items ever)? RCD and baton (dropping one of them after downing someone so you can claw them)?

**Comment by subject217** [comment]
The best combination is any stun weapon and a zombie claw. Theoretical best would be the ebow.
