### ISSUE TITLE
Penguin Butchering 

### ISSUE THREAD

**Issue by KangTut** [tgstation/tgstation#41026]
Issue reported from  Round ID: 95738 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Penguins are supposed to drop the source of their waddling, however, only baby penguins drop anything. Adult penguins don't even drop meat; they just explode into gibs when butchered.

Reporting client version: 512

**Comment by evsey9** [comment]
feature

**Comment by evsey9** [comment]
Feature, adult penguins are fitted with tactical microbombs that prevent waddle harvesting

**Comment by PKPenguin321** [comment]
😲

**Comment by MMMiracles** [comment]
There's a second butcher results list on emperor penguins that I didn't see when adding the results to base penguins, so that's why only babies are giving the stuff.
