### ISSUE TITLE
Bolted AI is thrown by shuttle

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#41030]
## Round ID:
95746

## Testmerges:
#40987: 'Makes looping sounds use client time' by ninjanomnom at commit 38fa012b25

## Reproduction:
Bring AI on shuttle, have it bolt. Watch it fly as shuttle launches.
Will also open doors if hit.

**Comment by AlexTheSysop42** [comment]
Probably because of move resist changes

**Comment by Dennok** [comment]
As i know now shuttls dont throw anything.

**Comment by kriskog** [comment]
They do when emagged.

**Comment by kriskog** [comment]
Still a thing
