### ISSUE TITLE
Borgs Don't Have a Resist Button

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#41039]
Borgs don't have a resist button, unless I've missed something critical (for unbuckling). This is unfortunate to cyborgs.

**Comment by PKPenguin321** [comment]
type it into the action bar

**Comment by Anonmare** [comment]
You can click the buckled notification to unbuckle. There's also the IC tab's resist, and you can type it in too.

**Comment by bobbahbrown** [comment]
sorry guys I'm blind please end this
