### ISSUE TITLE
derelict station has scrubber/air vents, despite having no pipes

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#41035]
<img width="960" alt="dreamseeker_2018-10-20_11-46-34" src="https://user-images.githubusercontent.com/13891233/47259594-2b1bef00-d460-11e8-859a-13debc21fffd.png">

**Comment by Barhandar** [comment]
Derelict has never _had_ pipes, it's DIY. What it needs is a RPD in the "atmos" and no vents/scrubbers.

**Comment by davethwave** [comment]
then I'll restate the question
