### ISSUE TITLE
Chat no longer gets interrupted when you are attacked

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#41037]
## Round ID: 
95777

## Testmerges: 
#40987 
#40928 

## Reproduction:

Type something
Get attacked
Get to send the complete message, never getting interrupted.

**Comment by SpaceManiac** [comment]
I mean, it's not like you couldn't just use the T hotkey to avoid this problem anyways

**Comment by PKPenguin321** [comment]
yeah, this has been a bit broken for a while now

**Comment by Garen7** [comment]
Is this the same as #8999?

**Comment by HideAndSeekLOGIC** [comment]
It works now, I sure as hell kept getting oofed
