### ISSUE TITLE
Supermatter shards can be hidden behind objects in high-traffic areas

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#41043]
## Round ID: 95788
To summarize what happened that round: Someone dragged a supermatter shard below a chair, 12 people ran in over the course of a 20 or so minutes until it was admin deleted. It was very difficult to see the shard, and the shard did not produce gases even after people ran in, which might be an unrelated bug. The supermatter shard in question was hidden behind the left chair in the picture.

I do not believe it should be possible to hide dangerous effects like Supermatter Shards that easily. 
I propose supermatter shards render above objects such as chairs, if this is technically possible without too much effort.

**Comment by PKPenguin321** [comment]
sounds hilarious tbh

**Comment by Potato-Masher** [comment]
Reminds me of the time where me and another slaved golem put a supermatter shard in the middle of the departures hall and at least 15+ different people ran into it and dusted themselves even with nothing hiding it. 

I agree that it should be above objects like chairs, but I think part of it may be that people are just moving too fast to notice anything.

**Comment by Seagleb** [comment]
https://github.com/tgstation/tgstation/pull/41107

**Comment by nicbn** [comment]
Reduce run speed when

**Comment by Seagleb** [comment]
Issue resolved, can be closed
