### ISSUE TITLE
lisa can have SEX with BABY IAN

### ISSUE THREAD

**Issue by plapatin** [tgstation/tgstation#41044]
Issue reported from  Round ID: 95794 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

if the title doesnt explain itself i don't know what will
reproduction:
1. drag lisa to ian while they're a corgi puppy
2. make them have babby

**Comment by Iamgoofball** [comment]
i'm going to remove all of the breeding shit from the game

**Comment by Anonmare** [comment]
https://www.youtube.com/watch?v=B14asZIPVP8

**Comment by bgobandit** [comment]
actually biologically accurate https://pets.thenest.com/old-puppies-become-sexually-active-12193.html

**Comment by plapatin** [comment]
jesus christ

**Comment by bgobandit** [comment]
in all seriousness though this is a bug, there are TWO separate checks for this but baby ian is a cosmetic sprite difference https://github.com/tgstation/tgstation/blob/5d8419541bd772026eeda71c41164383aadac085/code/modules/mob/living/simple_animal/simple_animal.dm#L370

**Comment by nemvar** [comment]
Dupe of #27550
