### ISSUE TITLE
Traitor icon bug midround

### ISSUE THREAD

**Issue by Malkraz** [tgstation/tgstation#41050]
Issue reported from  Round ID: 95813 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

If a traitor gets converted to clock cult, dies and is cloned, the traitor icon will appear next to their head as if it's roundend or overthrow.

**Comment by plapatin** [comment]
syndicate balloon hardcore mode

**Comment by kriskog** [comment]
clock gone
