### ISSUE TITLE
MK-Honk Prototype Shoes smelt bananium for free

### ISSUE THREAD

**Issue by MrDoomBringer** [tgstation/tgstation#41064]
Issue reported from  Round ID: 95850 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

put ore in shoes
take out smelted sheets of bananium
https://i.imgur.com/kvbSG1Q.gifv

**Comment by plapatin** [comment]
isnt this a feature? its an easy way to get bananium sheets from floor tiles

**Comment by Jordie0608** [comment]
Yeah this is fine. Pretend it's clown magic.
