### ISSUE TITLE
The Safe in the Vault Won't Open

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#41079]
Issue reported from  Round ID: 95893 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Even with the correct combination numbers, the safe won't open up. I tried going from positives to negatives, negatives to positives, and all the other kinds of ways you might be able to open a safe.

Unless the guide to opening the safe is wrong. But I don't recall seeing any PRs that affected the safe.
https://tgstation13.org/wiki/Safe#Safe

**Comment by wesoda25** [comment]
Its wrong. A while back vj linked me the real guide (just some reddit post) - and it worked. You have to go back in the original direction until you hear a specific noise.

**Comment by Hathkar** [comment]
> 
> 
> Unable to reproduce. I opened multiple vault safes by following the instructions on the wiki.



> 
> 
> Its wrong. A while back vj linked me the real guide (just some reddit post) - and it worked. You have to go back in the original direction until you hear a specific noise.

So which is it? Either the wiki is right or wrong.

**Comment by swindly** [comment]
The instructions on the wiki are correct.

t. wrote the instructions on the wiki

**Comment by plapatin** [comment]
you wait until you hear a tink/krink/plink not a krunk/plunk

**Comment by SouDescolado** [comment]
I checked the code and did some simulations on excel to check the logic. The logic is ok and it should work.
@ShizCalev Can you add a "Need reproducing" tag?

**Comment by nemvar** [comment]
Yeah no, this works fine.
