### ISSUE TITLE
Grounding rods dont work with supermatter electric arcs

### ISSUE THREAD

**Issue by dr-bee** [tgstation/tgstation#41075]
Title says it all, doing a controlled delam for anomalies grounding rods do jack shit to protect from the electric discharges the engine makes.

Round ID 95878

Testmerges:
#40928: '[Ready] Slime Crossbreeding - Chilling Extracts' by fludd12 at commit c1936dd096

To reproduce, simply surround a supermatter engine with grounding rods and set it for a high energy delam using CO2, watch in awe as the electric discharges ignore the grounding rods and go straight for any engineers.

**Comment by JAremko** [comment]
This is actually a big problem if you want to play fun SM setup by balancing it at the very edge of sanity.  Also if tesla coils and grounding rods worked with SM it would enable all new level of depth to the  possible setups. Like using all rad collectors for science while getting energy from lightnings.
