### ISSUE TITLE
Overthrow issues

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#41084]
@Carbonhell 

~~The mutineer team leader (the roundstart antag who chooses the team name) is supposed to get an uplink implant with 5 TC. This doesn't work, he instead gets a storage implant with a random piece of gear just like the people he converts.~~

The points system doesn't really work. The only thing that strongly differentiates one team from another is having the AI subverted at round end. This combined with the fact that every Overthrow team gets an AI module creates an experience where around ~30 minutes into a round of Overthrow the AI will repeatedly be subverted and re-subverted by multiple different teams all with AI uploads, and even the AI is confused about who he is supposed to help. The best way to win Overthrow rounds from what I've seen seems to be to convert at least one head of staff and then spam your AI module at an upload as the round is ending. The moment anyone spots a meta-tell for this mode they will also spam Purge + Asimov modules on the AI at around the same time. 

I'd like to see more objectives for the mode to make it a bit more interesting. I'm not sure if these would be for all teams like the heads and AI objective or randomly assigned like the extra objective but some stuff can easily be pulled from traitor. For example, escaping alive with everyone you convert or x number of teammates or something like that. 

The agents could use a bit more oomph as well, if that makes sense. I was thinking that the amount of TC that the lead agent gets (assuming that you fix that bug) could be doubled, and I could think up some revised, more powerful kits for the sleeper agents to get. I thought it'd be interesting if they were themed like the Syndicate Bundles, although with a lot less TC equivalent in gear.

Pretty scatter-brained post but hopefully that points you in the right direction. I think this mode has potential still.

**Comment by subject217** [comment]
I'd believe it but unless it's treated differently when they're spawned in (which it shouldn't, because you're still creating the team...right?) I can't reproduce it.

**Comment by Cyprex** [comment]
The flair text tells you your implanter only has two uses, while I've seen a round where the team leader implanted four people. I can dig it up in the logs if you want. Furthermore, converting a secondary AI with an enemy factions overthrow module adds them as a conspirator on the IC->Notes panel but doesn't greentext the objective. I am not sure if you get points for them.

**Comment by wesoda25** [comment]
You can buy more implants (unless you’re saying its an issue where after two uses the implanter appears empty, but still implants).

**Comment by nemvar** [comment]
Relevant code has been removed. I don't think there is a point in keeping this open.
