### ISSUE TITLE
Vault nuke exploding on nonstation Z prevents latejoining/observing

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#41095]
## Round ID:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 95924
BYOND Version: 512.1453
Server revision compiled on: 
The following pull requests are currently test merged:
#40907: 'This Halloween, a Zombie Map rises from the grave! (BirdBoat)' by Bawhoppen at commit f2494ccb28

No commit information
Server tools version: /tg/station 13 Server v3.2.5.3

## Testmerges:

The following pull requests are currently test merged:
#40907: 'This Halloween, a Zombie Map rises from the grave! (BirdBoat)' by Bawhoppen at commit f2494ccb28

## Reproduction:

Lone op spawns, grabs the nuke disk and starts the self-destruct nuke in the Vault, someone with two bags of holding came and bombed the vault, taking everything in the area to the CentCom Z. This resulted in the bomb damaging most of Z1, and causing a lockout on latejoining/observing from the start menu.

This however, does NOT end the round. The round can still end via the shuttle as normal.

**Comment by AnturK** [comment]
What do you mean by lockout.

**Comment by Barhandar** [comment]
@AnturK 
It doesn't reset `GLOB.enter_allowed` back to TRUE anywhere in the explosion code. It really should do that if it didn't end the round by exploding on station.

Admittedly it also shouldn't really explode on Z1 at all.

**Comment by AnturK** [comment]
That seems completely unnecessary to be set by nuke to be honest.

**Comment by Barhandar** [comment]
Locking the shuttle would either be anti-immersive (if it's docked) or detrimental to the gameplay (if it's in transit) due to occupying slots without letting joiners actually _play_.

**Comment by dragomagol** [comment]
No longer possible.
