### ISSUE TITLE
the station was as hot as the sun

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#41109]
Round ID:
95964

![image](https://user-images.githubusercontent.com/6209658/47404417-3b132780-d71b-11e8-8092-eee806c1ae2a.png)

speculation was that it was something related to heat exchangers. nobody could find the source, but the entire station died from it.

SM was also delamming, however it's cooling pipes were blue.

**Comment by kingoftheautism** [comment]
yeah atmos sometime (especially when sm delaminates) freaks out and spilling those numbers

**Comment by Barhandar** [comment]
Same thing happened back in 93829, though it was pubby.

**Comment by optimumtact** [comment]
We badly need an admin toggleable hud that shows

gas mixes
temperature across the station and in pipes

willing to pay someone for these

**Comment by LemonInTheDark** [comment]
This smells a lot like someone dumping fusion into the supermatter, or fusion flooding in general. Radiation logs back me up on this

**Comment by optimumtact** [comment]
you really just necro an issue from 2018?
