### ISSUE TITLE
Some machines can't be built/deconstructed

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#41116]
The following machines/structures can't be rebuilt:

- [ ] Anti-breach shielding generator
- [ ] Crematorium
- [ ] Field generator
- [ ] Morgue (tray)
- [ ] All particle accelerator parts
- [ ] Photocopier
- [ ] Pipe dispenser + Transit tube dispenser
- [ ] Requests console
- [ ] Shield wall generator
- [ ] Suit storage unit
- [ ] Tachyon-Doppler array
- [ ] Tank dispenser

Some of these can be ordered via cargo, but it would still be nice if you could properly deconstruct them and build new ones.

**Comment by Barhandar** [comment]
Don't touch PA, its whole point is cargo-only orderability same as the core generators. Buildable field generators have a lot of FUN potential. The only reason either of shield generators aren't buildable is building machinery didn't really exist when they got fixed.

And buildable pipe dispenser is basically wet dream of anyone who gets FPS cut in half by the RPD.

**Comment by Tlaltecuhtli** [comment]
some vendors

**Comment by Barhandar** [comment]
speaking of vendors, please override the cycling on vendor board into an actual menu because holy shit that is horrible

**Comment by SpaceManiac** [comment]
> speaking of vendors, please override the cycling on vendor board into an actual menu because holy shit that is horrible

radials would be perfect for this

**Comment by BootlegBow** [comment]
currently working on making the suit storage unit constructable
