### ISSUE TITLE
CNS rebooter implant doesn't work

### ISSUE THREAD

**Issue by JMoldy** [tgstation/tgstation#41125]
Issue reported from  Round ID: 95986 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Had the CNS Reboot implant along with the anti-stun surgery, anti drop implant, breathing tube, and no-drop implant. Died in space from pressure damage, CNS reboot didn't ever activate.

**Comment by Barhandar** [comment]
Not a bug; you're confusing CNS rebooter (which caps stun time) and reviver (which heals you up and halts heart attacks).
