### ISSUE TITLE
Destroyed drones can't move after being reactivated

### ISSUE THREAD

**Issue by Ispiria** [tgstation/tgstation#41120]
Issue reported from  Round ID: 95979 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

A destroyed drone, once repaired with a screwdriver, becomes unable to move. They can still turn around and communicate, can still be picked up by humanoids, but can't move at all. Tested with syndrone and syndrone/badass, the player helping me test reported it also happens to normal drones.

**Comment by delaron** [comment]
this relates to all sentient mobs as well it seems.
