### ISSUE TITLE
Hallucinations can potentially reveal nukeops/wizards before they come to station/get discovered

### ISSUE THREAD

**Issue by nervere** [tgstation/tgstation#41127]
Round ID: 95991 on Bagil
Testmerges: #41011 to buff nukeop shuttle was testmerged, not relevant to situation though.
http://puu.sh/BQjNp/9b699a7763.png 
Through hallucinations, it's possible for the randomly selected crewmember name that is picked for a hallucination is, for instance, the name of a nuclear operative. See above link for screenshot. Before the operatives were even off the syndicate base, the player was able to discover they existed due to a hallucination. It was rather obvious in this case because the operative name included the word "op", but it can also be revealing for other operative names, or potentially for wizard names.
Here's the relevant hallucination log:
`18:18:48 [mob_543] (113,144,2) || (censored) was afflicted with a hallucination of type /datum/hallucination/chat by hallucination status. Type: Radio, Source: Kennard Fagor Op, Message: [Common] Kennard Fagor Op exclaims, "Call the shuttle!"`

**Comment by sagattyy** [comment]
feature

**Comment by zamolxius** [comment]
precog visions.  feature

**Comment by XDTM** [comment]
maybe the mob check could be restricted to the station z_level, not perfect but better than nothing

**Comment by AnturK** [comment]
I'm pretty sure i left minority report joke in comments when i added this but that might have been lost somewhere.

**Comment by HideAndSeekLOGIC** [comment]
I vote feature
