### ISSUE TITLE
Some reagent containers behave oddly when filling certain structures

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#41123]
## Reproduction:
I'm assuming this is caused by #38606 and tangentially related to  #39527

1. Grab any reagent container (buckets, glasses, soda cans, syringes, anything works)
2. Try to fill certain structures that can contain reagents, it will succeed but you'll also smack the structure which also causes an attack delay and makes filling these containers take a very long time (happens with mop buckets, fermenting barrels and deep friers that I know of. For beer kegs and oil vats only happens with syringes).

**Comment by kriskog** [comment]
Still an issue.
