### ISSUE TITLE
supermatter slivers on tongs are literally an insta-dust for anything you click on no matter the range

### ISSUE THREAD

**Issue by zeroisthebiggay** [tgstation/tgstation#41136]
Use the supermatter scalpel on the crystal, pick up shard with tongs, click on anything on screen to instadust it. Happened on accident in a round live round, works just fine on private hosted servers.
![a74ba26769d1b1d4ac31b60004444134](https://user-images.githubusercontent.com/43571008/47485917-2b740b80-d80d-11e8-8698-80128395ede7.png)
![a0705862bdf80e8ae50d6d34dcc16471](https://user-images.githubusercontent.com/43571008/47485923-2e6efc00-d80d-11e8-9fa0-7aac7249b590.png)
bonus: it works through cameras

**Comment by kingoftheautism** [comment]
that's uhh, uhhhhh

well you have to get that sliver on tongs, plus have CE hardsuit or radiation suit to not die from throwing up because of radiation or getting random bad mutations, but yeah that's really FUCK issue (or maybe not)

**Comment by 81Denton** [comment]
Yeah that's uhhhhhh
man

**Comment by evsey9** [comment]
feature
supermatter slivers amplify your psychic abilities and let you focus it to force dust people from range

**Comment by zeroisthebiggay** [comment]
> that's uhh, uhhhhh
> 
> well you have to get that sliver on tongs, plus have CE hardsuit or radiation suit to not die from throwing up because of radiation or getting random bad mutations, but yeah that's really FUCK issue (or maybe not)

assuming that the thing of shaving multiple shards off of a single crystal is still a thing, you could (in theory), make a shit ton of slivers and using an autocloner to essentially dust everyone through a camera console IF you had **a lot** of fucking autism

**Comment by evsey9** [comment]
Supermatter slivers are the origin of energy swords and the force
Official lore
