### ISSUE TITLE
Destructive analyzer eat all stack and dont give materials on reclamation

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#41135]
## Round ID:
96012

## Reproduction:
1. Miners sucks and dont bring bluespace crystals.
2. Go to teleporter room.
3. Deconstruct teleporter. Grab artifical bluespace crystals stack.
4. Feed whole stack to Destructive analyzer.
5. It show that will give same amount of bluespace mesh as for one crystal(but i feed him with stack of 3 crystals).
6. Press Reclaim material.
7. Crystals gone and no materials was added anywhere.

**Comment by SpaceManiac** [comment]
how many different times am I going to have to fix this bug

**Comment by Barhandar** [comment]
Note that I'm not sure why you're sticking the crystals in the decon, as they can be put directly in the lathe.

**Comment by Sealed101** [comment]
does the d-analyzer even return materials when destroying an item anymore
