### ISSUE TITLE
The clockwork flooring in the Ratvar ruin is literally infinite

### ISSUE THREAD

**Issue by NopeDotWav** [tgstation/tgstation#41137]
Issue reported from  Round ID: 96023 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

Roughly 20 minutes into the round I realised I could infinitely crowbar the clockwork flooring in the ratvar ruin. You'll see a lot of crowbarring on the same tile (and it succeeding). I doubt this is intentional, and it's a super easy way to get an infinite amount of brass.

**Comment by Barhandar** [comment]
And brass is useful for?..

The only real use is the not-slowpoke golems, I think.

**Comment by kingoftheautism** [comment]
basically dublicate of issue #i forgot the number
