### ISSUE TITLE
Beer nuke doesn't get its code set by loneops spawn

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#41143]
Title. It would be more fun if you could trigger the beer nuke as loneop, effectively sabotaging the crew if they, for example, impulse-boh their own silo, and without being a dick to lowpop rounds.

**Comment by TheBonded** [comment]
this is more of a feature request, as they are different nukes and it makes sense for them to have different codes. same thing with the self destruct and normal nuke ops team codes, which are also both different.
