### ISSUE TITLE
Intercoms cannot be applied to the same wall a lamp is on, despite not visually conflicting

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#41145]
Issue reported from  Round ID: 96042 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
Reporting client version: 512
#41029: '[READY] Hilbert's Hotel' by TheDreamweaver at commit edfcd61e4e

They can be applied over an extinguisher closet; security cams can also be slapped onto a wall with a light on it.

**Comment by dragomagol** [comment]
Unable to reproduce
