### ISSUE TITLE
Admin Logging Does Not Show Enough Information For Antagonist-Setting

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#41149]
## Round ID:
92384

## Reproduction:
Currently, the logs do not show ckeys for players that are made into antagonists. This seems like an oversight, and could be problematic/annoying in situations like this...

![evidence!](https://i.imgur.com/ktP4DnL.png)

Of course, one could then correlate this with the roundend manifest or other information, but it would be nice to have the ckey logged at the time of event.

**Comment by ShizCalev** [comment]
relevant;
https://youtu.be/grFk1NFnrFY
