### ISSUE TITLE
revhead monkies can hide in vents all round and win

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#41154]
honk

**Comment by Iamgoofball** [comment]
I'll make the hiding head rev check beefier.

**Comment by Ratvar** [comment]
revhead revheads can hide in space room all round and win

**Comment by TheBonded** [comment]
this seems to be more of an administration or IC issue, as you could say the same thing for xeno larvae hiding and then becoming a new queen after the old one was killed, or for an assassination target hiding in vents to not get killed.
