### ISSUE TITLE
Officer Pingsky states, "Detaining level 10 scumbag <b>PLAYER NAME</b> in AI Chamber."

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#41177]
Issue reported from  Round ID: 96137 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
Reporting client version: 512
#41029: '[READY] Hilbert's Hotel' by TheDreamweaver at commit dbedcc1fe8

Instead of bolding it as it should, it's showing the bolding codes.

**Comment by jlsnow301** [comment]
Due to the age of this issue and my inability to reproduce it, I'm going to assume this is fixed
![Screenshot 2021-12-29 000501](https://user-images.githubusercontent.com/42397676/147640518-283c31bc-4d70-4dbe-ad4d-f5a2864fc9a4.png)
