### ISSUE TITLE
Suffocation moodlet doesn't work

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#41170]
## Reproduction:
1 .Throw yourself in space
2. Suffocate to death
3. Everything's fine, no moodlet

Here's the related code, it looks like it should work and I haven't been able to figure out what the issue is
https://github.com/tgstation/tgstation/blob/fe714bc8d4e9b69955f8e25672fa1aad3a380333/code/modules/mob/living/carbon/life.dm#L152-L173

**Comment by XDTM** [comment]
Humans do not use the carbon check_breath; instead they use their lungs' check_breath proc which seems to lack the moodlet adding proc.

**Comment by Mickyan** [comment]
Thanks, I thought that might be the case but I wasn't sure. I just figured out why I couldn't get it to work at first, there's different code whether there's only too little oxygen and when there's no atmosphere at all, had to add the signal call to both of those situations

I'll PR the fix soonish
