### ISSUE TITLE
Ash Drake STILL HAS NO COOLDOWN ON THE ARENA ATTACK

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#41178]
Issue reported from  Round ID: 96137 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
Reporting client version: 512
#41029: '[READY] Hilbert's Hotel' by TheDreamweaver at commit dbedcc1fe8

It's just as fucking terrible for players as the old swoop because the drake is still invulnerable during it and can still chain it.

**Comment by ShizCalev** [comment]
@Whoneedspacee

**Comment by Whoneedspacee** [comment]
https://github.com/tgstation/tgstation/blob/17dfb07f99612b6d7c92d928ec22694ef20eb328/code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm#L145

Yes he can chain it, aka use it subsequently. No it is not like it was before where there is no cooldown and you had no ability to attack it at all, I've fought it on public servers myself and you always have a pretty good amount of time to get some damage in.

**Comment by kriskog** [comment]
Changed in #42251
