### ISSUE TITLE
Monochromacy begins flashing colours when going to ghost mode

### ISSUE THREAD

**Issue by GLACoding** [tgstation/tgstation#41180]
Round ID: 96142

Reproduction:
1. Select monochromacy on your character quirks
2. Join game, die
3. Exit to ghost mode
4. Have an epileptic fit from the flashing colours

Reconnecting while in ghost mode fixes this, seems to be a problem when going from monochromancy to full colour.

**Comment by kriskog** [comment]
Can't reproduce this one, was this a thing that always happened?

**Comment by SuperNovaa41** [comment]
Probably not an issue anymore
