### ISSUE TITLE
narsie arm ending doesnt trigger

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#41197]
96184 bagil
there was only an admin spwaned dude as not cult yet no arm ending

**Comment by YakumoChen** [comment]
I saw it just yesterday?

**Comment by adamkad1** [comment]
i ddidnt

**Comment by adamkad1** [comment]
98186 round id, likely was going to be arm cinematic, yet i didnt see one, there was no cinematic, just normal screen but everything is frozen, i only ever see no arm cinematic

**Comment by kriskog** [comment]
Seems to play as normal now.
