### ISSUE TITLE
Techweb design in "initial" category are having their build_type's overriden after world finishes initializing. RD console gives you a construct at protolathe prompt for things that don't exist in it.

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#41199]
Master https://github.com/tgstation/tgstation/commit/1f805017d5d3ba2082905d1096b5f4bd3192c75d

Something down the chain after all the `/datum/techweb/specialized/autounlocking`'s proc and unlock all the designs in the `initial` category is overriding all initial designs' `build_type` var to `PROTOLATHE`

Example design:
https://github.com/tgstation/tgstation/blob/0af352927a0225f9e12ea5bf202c7f86d4be6581/code/modules/research/designs/autolathe_designs.dm#L482-L488

**Repo:**
Start server
Check SSresearch in MC, go to `techweb_designs`
Pull up `rubber shot`
Check `build_type`
Buildtype is 2, should be 4.
Open RD console interface
Pull up basic research tech node
Check rubber shot
See construction button, even though it can't be constructed at a protolathe
Click construction button, get a blank protolathe screen since it doesn't exist.

Can also be confirmed by checking output on the RD console screen
https://github.com/tgstation/tgstation/blob/4a2861b1c2883d5ba428766c99960adcb948ba4e/code/modules/research/rdconsole.dm#L760-L763
`to_chat(world, "protolathe TRUE, [selected_design] [selected_design.build_type] [PROTOLATHE] [AUTOLATHE]")`
![image](https://user-images.githubusercontent.com/6209658/47616254-b6186d00-da90-11e8-9e5d-325ef9f23cdf.png)
Define for `PROTOLATHE` is 2, the rubber shot design should be 4 / `AUTOLATHE`
![image](https://user-images.githubusercontent.com/6209658/47616323-a2b9d180-da91-11e8-82ca-70eedb4c3f03.png)
Shouldn't be seeing the protolathe icon nor the construct button in this pic.

**Comment by AlexTheSysop42** [comment]
Actually I'm pretty sure rubber shot can be made at a seclathe as well

**Comment by dragomagol** [comment]
I'm near certain this no longer applies
