### ISSUE TITLE
Communications Consoles Can Be Used Past Emergency Shuttle Launch

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#41201]
## Round ID:
late reported so I have no idea what the round id was

## Reproduction:
Open communications console prior to launch, keep window open, past shuttle launch you can continue to use it through the panel. Clicking on the console itself will tell you that you cannot interact with it past launch, however, as long as you keep the window open it'll let you.

**Comment by Sealed101** [comment]
i don't see any messages indicating that one can't use the console past shuttle arrival, departure and CC arrival. was this a thing back in the good old days(™️)?
