### ISSUE TITLE
Overthrow is a mistake, ai upload board is bugged.

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#41209]
When an ion random law event happens, the ai gets reverted back to asimov, but it gets better! Despite your laws being changed you will keep your objectives and continue to be updated on whoever is a part of said team, all future members of that team get that fun little T icon next to them too!

**Comment by SouDescolado** [comment]
@Carbonhell

**Comment by ExcessiveUseOfCobblestone** [comment]
The entire conversion process for AIs needs a look at, borgs don't get the hud despite being bound to the AI.

**Comment by actioninja** [comment]
overthrow has been removed
