### ISSUE TITLE
You cant buy the arena shuttle if medals are disabled

### ISSUE THREAD

**Issue by fluffe9911** [tgstation/tgstation#41218]
(TO REPRODUCE)

1.Have bubblegum killed
2.Get 10000 credits
3.Cry when it says you have not reached the criteria for buying the shuttle

**Comment by Barhandar** [comment]
It requires the medal proc, so if medals are disabled, you're out of luck. It's kinda dumb considering the only relevant part of the proc is checking whether the thing's adminspawned.

Otherwise it might be issues with how it appends stuff to list.

**Comment by fluffe9911** [comment]
Ah thats a bit silly but alright
