### ISSUE TITLE
Syndi thermal imaging goggles override welding/flash protections on helmets

### ISSUE THREAD

**Issue by MegaEmpirical** [tgstation/tgstation#41210]
Bought thermal imaging goggles as a traitor plasmaman. I had to remove them anytime I was welding something if I didn't want to take flash/weld damage. Even though my helmet provides that protection, just had to hold the glasses in hand. Did not care what their camo setting was (I tried welding goggle setting and others).

**Comment by kingoftheautism** [comment]
isnt like intended?

**Comment by MegaEmpirical** [comment]
They don't have an on/off but yes, I had to take them to not be blinded. Plasmaman helmet provides protection but the goggles were negating that protection for some reason.

**Comment by Barhandar** [comment]
I fail to see how that's a bug. You're trying to look at something really bright and hot through something that amplifies bright and hot things, of course your protection is going to be lacking.

**Comment by MegaEmpirical** [comment]
Because my protection is not lacking. I was wearing my plasmaman helmet which provides flash protection. Putting the goggles on negates that protection.

**Comment by kingoftheautism** [comment]
damn dude you just confusing me

It's INTENDED that thermals making you vurnerable for flashes. I though welding was still flashing you even when thermals were in your hands, not on your eye slots damn it

**Comment by MegaEmpirical** [comment]
I had to take them off to protect myself from the flash.

But I think understand your point of confusion. You're saying the thermal goggles make you more sensitive to light and so welding should blind you. 

I had not considered that. However, should they blind you through pre-existing cover? The helmet should still be blocking most of the light? Or maybe it's fine as is then.

**Comment by XDTM** [comment]
The way it works is that the helmet is giving you +2 protection, while the goggles are giving you a -1. If protection is 2 or more, you won't get blinded, but since the thermals are taking you below that threshold, you're no longer immune (although it should still protect you from flashes, like sunglasses).

**Comment by MegaEmpirical** [comment]
I see, fair enough. I'll close this up then. Thanks for explaining.
