### ISSUE TITLE
Autolathe no longer has any of the usual engineering/medical tools regardless of research

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#41213]
Issue reported from  Round ID: 96253 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
Reporting client version: 512
#41029: '[SUPER DUPER EXTRA READY] Hilbert's Hotel' by TheDreamweaver at commit 47b488e326

@Cyberboss @ShizCalev this is your fault because you two are the ones who were touching techwebs, though not 41092 as that's not on the server yet

**Comment by ShizCalev** [comment]
If the issue isn't with #41092, then the only changes I've made have been fixes for the RD console's UI.

Do note the bug report I made (#41199) yesterday, which involves something kicking things out of pool of designs compatible with autolathes. That'd likely be the reason things are going missing.

**Comment by ShizCalev** [comment]
Just to be clear however, which tools in specific are you referring to?

**Comment by Barhandar** [comment]
Wrench (and the rest of engie tools), **cable coil**,  multitool, analyzer;
Scalpel, surgical saw, surgical drill, hemostat, retractor, cautery.

Both could be built in the autolathes yesterday, both do not show up in the list at all today. Therefore some of the recent commits that affected designs on Sybil is to blame.

**Comment by ShizCalev** [comment]
#41092 is live on the server actually, looks like the changelog just failed to generate.

**Comment by Barhandar** [comment]
It _is_ a bug, because researching basic tools node doesn't make tools appear in the autolathes.

**Comment by ExcessiveUseOfCobblestone** [comment]
I know surgery tools are no longer available to the autolathe but are in the MedTechfab (They should be in both according to code)

**Comment by ShizCalev** [comment]
Researching something doesn't make it automatically appear in autolathes, you need to transfer it over using a design disk from what I'm seeing in the code.

**Comment by Barhandar** [comment]
That's bloody horrendous, at least they seemingly can have more than one blueprint on them. Please don't do _that_.

**Comment by ExcessiveUseOfCobblestone** [comment]
What PR stated that previously roundstart items from the autolathe now have to be transferred via disk? I'm certain that's not intended or at best an undocumented change somewhere.

**Comment by 81Denton** [comment]
Looks like this change will prevent free golems from building machinery, since they don't have cable coils available and no way to sync their lathe at roundstart.

**Comment by Barhandar** [comment]
It does, unless they get creative for getting cable.

**Comment by Cyprex** [comment]
Yes, this is a big issue for free golems. Please reconsider your stance on this.
