### ISSUE TITLE
Moths lose wing selection after cloning

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#41222]
This seems to be relatively new and the weirdest part is not only you lose wing customization, but so does your old corpse once you do something to update its sprite, like moving it or stripping it

## Reproduction:
1. Pick a non default wing type
2. Die, get cloned
3. Wings are now "Plain" type
4. Strip your old body and see its wings also have changed

**Comment by RedFoxIV** [comment]
feature, helps people understand why moths are a mistake
