### ISSUE TITLE
left left right right up down up down WARPSPEEEEEEEEEEEED

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#41235]
TG coding is a piece of art
![ffs-tg](https://user-images.githubusercontent.com/38788538/47718766-405ffd00-dc5a-11e8-8f39-735b4d897ae6.gif)

**Comment by AlexTheSysop42** [comment]
Same trick works (or worked) with normal boxes and the oddy mech

**Comment by ExcessiveUseOfCobblestone** [comment]
cheat code feature lol

**Comment by nemvar** [comment]
Fixed by #45274
