### ISSUE TITLE
adding new records in the security records is buggy

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#41234]
96301
the "add new record" is extremly buggy and doesnt worth 90% oh the time, 
- uploading a picture mutes sounds and goonchat gives the message "you are lagging or the connection is lost" until reconnect
- uploading a picture breaks the picture (turning it into a "blank" picture) and may cause it to upload a broken pic
- uploading a picture breaks the window and u cant open it anymore
- tgui 
- everything is buggy

**Comment by SuperNovaa41** [comment]
No longer an issue
