### ISSUE TITLE
Poly repeating say() messages with their span classes in them

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#41236]
master
https://github.com/tgstation/tgstation/blob/55a768fef109af873291a4383e1b735a5e5969c5/code/modules/shuttle/special.dm#L298

![image](https://user-images.githubusercontent.com/6209658/47725893-cca8fa80-dc2f-11e8-8fa3-4a29c864d6da.png)

**Comment by k-k-karma** [comment]
feature

**Comment by ExcessiveUseOfCobblestone** [comment]
is this a duplicate of #41177 ?

**Comment by Time-Green** [comment]
<span class='gitcomment'> yes</span

**Comment by Time-Green** [comment]
'<span class='gitcomment'> yes</span>'

**Comment by Time-Green** [comment]
<div size=100> yes </div>

**Comment by Time-Green** [comment]
<font size="60">yes</font>

**Comment by Time-Green** [comment]
**yes**

**Comment by Time-Green** [comment]
### **yes**
