### ISSUE TITLE
You get stuck in cryotubes forever if you have a damaged prosthetic limb

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#41246]
Master

It checks the mob's maxhealth against their current health, and since cryox doesn't heal damaged non-organic limbs, they'll just stay in the tube forever until they OD on cryox or are let out by a player.

**Comment by nicbn** [comment]
One way to solve all issues raised with cryo not turning off is to remove auto from cryo and make it never turn off at all. That way no one is going into cryos without having someone - probably a doctor - outside to help em getting out

**Comment by Barhandar** [comment]
That's not a solution and it raises other issues like making cryo fucking useless

**Comment by nicbn** [comment]
that doesn't even make sense
cryo is useful because it heals not because it opens automatically

**Comment by Barhandar** [comment]
Cryo is useful because it's a set and forget heal; if it requires cooperation you might just as well get something that _also_ requires cooperation but is much faster and one-timey, such as being scanned into cloning and dying, or asking a chemist for some meds.

**Comment by nicbn** [comment]
We can rework the entire med system then, but we gotta start from somewhere

**Comment by dragomagol** [comment]
Fixed in #51998
