### ISSUE TITLE
Storage Implant removal still destroys stored items

### ISSUE THREAD

**Issue by delaron** [tgstation/tgstation#41243]
When surgical removal of a storage implant takes place with a implant case in hand the items stored are still destroyed. The implant itself if safely stored in the container but there is no way to retrieve the items from your corpse if you were cloned.

**Comment by Cyprex** [comment]
What happens if you transfer your mind back into the corpse? I. e. get the corpse in a state that allows revival surgery and have someone transplant your brain into the corpse and revive it.

**Comment by kriskog** [comment]
Fixed in  #44154
