### ISSUE TITLE
 Navigational shuttle computers do not work if you're using 2x (64x64) sprite scaling

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation#41248]
Round ID: 96345
Server: Basil
Map: Metastation

Navigational shuttle computers do not work if you're using 2x (64x64) sprite scaling

The hud icons are off screen and you cannot view the entire view area.

**Comment by optimumtact** [comment]
Note that if you use stretch to fit, it appears to work fine

**Comment by Dennok** [comment]
Still issue?
If you set 2x (64x64) sprite scaling you need really BIG monitor.

**Comment by optimumtact** [comment]
as far as im aware it's still an issue, just not very high priority to fix right now

**Comment by Dennok** [comment]
I think this is byond side problem, it show to user map field bigger then it resolution can fit, and this cant be fixed by code.Only if you change client properties and forbid non scrench to fit icon settings.

**Comment by kriskog** [comment]
Can confirm, still happening.
