### ISSUE TITLE
Sparks do not create fires

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#41247]
Door shocks and APC overloads do not start plasma fires any longer, giving the AI very few options to set the station on fire in a plasma flood, or any other source of sparks for fire.

**Comment by Hanador** [comment]
Can confirm just attempted to kill a warden/hos locked in a brig full of plasma by overloading the lights and shocking the doors. Not even my borgs being beaten started the fires.

**Comment by Barhandar** [comment]
It was an ~acceptable downside~ to having sparks heat the turfs.

It's also known as: "ignite() heating the air was a massive mistake"

**Comment by YakumoChen** [comment]
half the point of light overloads was to set fires

**Comment by ExcessiveUseOfCobblestone** [comment]
call ignite on light overload then?

**Comment by YakumoChen** [comment]
same with doors, running into an electric shocked door is supposed to start a fire.

**Comment by Barhandar** [comment]
>call ignite on light overload then?

overload lights @ the room is now toasty 100C

Seriously, ignite heating air was a mistake, because it breaks fucking everything like this and doesn't provide any tangible benefit

**Comment by ExcessiveUseOfCobblestone** [comment]
I mean you could just add an argument to the ignite proc to not do the temperature increasing aspect barring fires lol
