### ISSUE TITLE
MMI are able to jaunt if they are also vampires. 

### ISSUE THREAD

**Issue by HydroFloric** [tgstation/tgstation#41244]
## Round ID:

**96319**

## Testmerges:
The following pull requests are currently test merged:
#41155: 'Adds three new .38 ammo types' by 81Denton at commit eb1ea872fa
#41099: 'New Map: Donutstation (WIP)' by MMMiracles at commit e0546d6bac

**Comment by ATH1909** [comment]
If you died as a bat, did you just return to being an MMI?
Could you immediately reenter bat form again?

**Comment by AlexTheSysop42** [comment]
Probably kills your brain

**Comment by HydroFloric** [comment]
@ATH1909 I never died in bat form but I would assume it kills me. Also I forgot to mention in the post, but after jaunting out of the backpack I was turned into a space bat. Once pressing the revert button I turned back into a mmi. So the main issue seems to be mmi's being able to become bats with the jaunting just being a byproduct of that to allow escape from backpacks aswell.

**Comment by AnturK** [comment]
Not a bug. Balance maybe.
