### ISSUE TITLE
Emags not opening lockers

### ISSUE THREAD

**Issue by JetBrody** [tgstation/tgstation#41249]
Issue reported from  Round ID: 96346 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Emags are not opening locked lockers, instead returning "Access Denied"

Spawned a few different lockers in the Thunderdome and all were the same.

**Comment by JetBrody** [comment]
A player informed me you may need to use it on harm intent, which I didn't check.

**Comment by ExcessiveUseOfCobblestone** [comment]
#40877 attempted to fix this but hasn't been reopened

**Comment by creeperparty568** [comment]
also happens with crates

**Comment by delaron** [comment]
harm intent with emag opens lockers

**Comment by nemvar** [comment]
Use harm intent.

**Comment by bgobandit** [comment]
having to use harm intent is idiotic, it's an emag, not a battering ram
