### ISSUE TITLE
Engineering console is giving the "You shouldn't see this. If you do, report it." on use.

### ISSUE THREAD

**Issue by Cekomen** [tgstation/tgstation#41251]
Issue reported from  Round ID: 96350 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

It happened while I was a ghost. The engineering console on delta station showed this upon clicking.

![resim](https://user-images.githubusercontent.com/32301647/47783751-9b562a80-dd14-11e8-830f-59ec83985aa8.png)

Other consoles on the department didn't have this problem, they just opened the computer window and didn't have the "you shouldn't see this" part of examination.

This was also a problem because the SM was generating no power, SMESs were empty and engineering APC had only enviroment on, so the computers were (supposed to be) turned off. (Unless ghosts have it different). They even had the blank screen sprites. 

On the next round, I tried the same thing, and it still gave me the "report this reee" text. This time the power was on. 
It works normally when it's turned on, so I assume it has something to do with having to turn it on first.

On both rounds, shift-clicking the computer examined it normally, giving only the first 2 lines.

**Comment by kriskog** [comment]
Modular computers have a processor object that handles user interaction instead of handling it itself. With inquisitiveness on, this causes the ghost to examine both the console and the processor object.
