### ISSUE TITLE
You can put things inside locked containers

### ISSUE THREAD

**Issue by Grazyn** [tgstation/tgstation#41259]
Go to dorms
Open one of the ID-locked lockers
Drag the bag/backpack inside the locker to you to open its inventory UI
Close the locker and lock it with your ID
Click on the open inventory UI with your ID in hand

congratulations, you've managed to lock your ID inside a locker that needs your ID to be opened, better hope there's still a HoP around

BYOND Version: 512.1453
Server revision compiled on: 
Master commit: 66d318e4b906407c6b16bc060582512f95dbe2cb
The following pull requests are currently test merged:
#41155: 'Adds three new .38 ammo types' by 81Denton at commit eb1ea872fa
#41099: 'New Map: Donutstation (WIP)' by MMMiracles at commit e0546d6bac

Local commit: 96e169bd28af22e66a6f08d746bae54f4e623b4b
Server tools version: /tg/station 13 Server v3.2.5.1

**Comment by ArcaneMusic** [comment]
Unable to reproduce as of current code, so I imagine one of the many storage component reworks probably fixed this. Comment if it springs back up.
