### ISSUE TITLE
Blood Brothers can have duplicate objectives

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#41272]
I'm not sure how this affects greentext but I saw a pair of blood brothers have an objective for a reflector vest twice. Now, I know more then one can be made but I don't know if this translates to being able to have the same unique objective twice (HoS gun for example) if having an item completes both objectives, or anything else could affect greentext, but it doesn't seem like they should both be getting the exact same objective.

**Comment by ShizCalev** [comment]
@AnturK
