### ISSUE TITLE
Reagents not dispensing from containers

### ISSUE THREAD

**Issue by JetBrody** [tgstation/tgstation#41283]
Issue reported from  Round ID: 96478 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

Multiple players reporting issues getting beakers and bottles to transfer their contents to hydroponics trays. Tried testing it myself and couldn't get it to work either, on multiple intents with several different reagents and bottle types. Changing the transfer amount didn't seem to affect things either 

Player reported that they could get it work occasionally then it would go back to being unable to transfer.

**Comment by JetBrody** [comment]
[22:34:54] Runtime in holder.dm, line 180: undefined proc or verb /datum/reagents/add hiddenprint(). 
proc name: trans to (/datum/reagents/proc/trans_to)
usr: K0r4y/(Joel Hoover)
usr.loc: (Hydroponics (138, 115, 2))
src: /datum/reagents (/datum/reagents)
call stack:
/datum/reagents (/datum/reagents): trans to(/datum/reagents (/datum/reagents), 5, 1, 1, 0, Joel Hoover (/mob/living/carbon/human))
the hydroponics tray (/obj/machinery/hydroponics/constructable): attackby(the large beaker (/obj/item/reagent_containers/glass/beaker/large), Joel Hoover (/mob/living/carbon/human), "icon-x=16;icon-y=7;left=1;scre...")
the hydroponics tray (/obj/machinery/hydroponics/constructable): attackby(the large beaker (/obj/item/reagent_containers/glass/beaker/large), Joel Hoover (/mob/living/carbon/human), "icon-x=16;icon-y=7;left=1;scre...")
the large beaker (/obj/item/reagent_containers/glass/beaker/large): melee attack chain(Joel Hoover (/mob/living/carbon/human), the hydroponics tray (/obj/machinery/hydroponics/constructable), "icon-x=16;icon-y=7;left=1;scre...")
Joel Hoover (/mob/living/carbon/human): ClickOn(the hydroponics tray (/obj/machinery/hydroponics/constructable), "icon-x=16;icon-y=7;left=1;scre...")
the hydroponics tray (/obj/machinery/hydroponics/constructable): Click(the floor (137,114,2) (/turf/open/floor/plasteel), "mapwindow.map", "icon-x=16;icon-y=7;left=1;scre...")
K0r4y (/client): Click(the hydroponics tray (/obj/machinery/hydroponics/constructable), the floor (137,114,2) (/turf/open/floor/plasteel), "mapwindow.map", "icon-x=16;icon-y=7;left=1;scre...")

**Comment by ShizCalev** [comment]
fuck

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/b1010505405e4398c4e9866d86672c44004c820a/code/modules/hydroponics/hydroponics.dm#L723-L726

some hacky ass code, S is supposed to be a mob, not a datum.

**Comment by ShizCalev** [comment]
Fixed by #41286
