### ISSUE TITLE
Botany Broken

### ISSUE THREAD

**Issue by DalandSoren** [tgstation/tgstation#41288]
Issue reported from  Round ID: 96485 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

Couldn't water or feed any of the hydro bins, would say i was dumping in nutrients/water and wasn't registering any change in level of nutrient or container. Tried with all the bottles from the venders, Diethylamine  from chem dispensers.

**Comment by AlexTheSysop42** [comment]
Dupe of #41285

**Comment by ShizCalev** [comment]
Dupe
