### ISSUE TITLE
Dio is disappointed

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#41289]
Okay, so, this Halloween, I learned something cool about vampires: if you shapeshift out of bat form while ventcrawling, you appear on the tile that covers wherever you happened to be when you shapeshifted out of bat form, no exit vent needed.

I also learned something uncool about vampires: If you perform that trick while you have a holoparasite in you, the holoparasite gets ghosted. I tested this with soulstones with a shade in them too, and sure enough, a shade that was walking (well, technically floating, I guess) and talking before I scooped it up and entered the vent went braindead after I exited the pipe by shapeshifting and dumped it out of the soulstone. Notably, this DIDN'T happen with my holoparasite when I exited ventcrawling "normally", nor when I just shapeshifting into and out of bat form.

**Comment by ATH1909** [comment]
I'm still salty that the admins wouldn't give me a TC refund (I *did* try the ghost reroll on the holoparasite, and it still appeared to remain braindead) for my holoparasite injector.

**Comment by AlexTheSysop42** [comment]
It's a bug, did you expect it to not cause problems or something?

**Comment by ATH1909** [comment]
Well, I didn't really think it *was* a bug at first. I mean, it seemed to me the most logical result of a character that is ventcrawling losing the ability to ventcrawl (other than letting them continue to ventcrawl until they leave a vent or having the pipe burst or something when they leave it).

**Comment by evsey9** [comment]
the most logical would be NOT being able to shapeshift while inside of a vent
