### ISSUE TITLE
Cult with no sec, captain, or chaplain can select someone who is already a cultist as the sacrifice target

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#41298]
Round ID: 96557

Cult sacrifice target selection cannot find an unconvertible target -> searches for a convertible target -> chooses someone who is already a cultist.

Solution: Make the search for a convertible target ignore people who have already been selected as cultists.

**Comment by subject217** [comment]
round not over i'm braindead

**Comment by Ratvar** [comment]
It's simplier to deconvert a cultist/let cultists be sacrificed if target then to find a miner, I would say

**Comment by AnturK** [comment]
From quick glance, team objectives are created before all members are assigned so it doesn't have full information.
