### ISSUE TITLE
Deltastation slime console area not properly zoned

### ISSUE THREAD

**Issue by TothBrush** [tgstation/tgstation#41297]
Issue reported from  Round ID: 96557 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

One of the 6 chambers for slimes is unusable because of the limited visibility.
https://imgur.com/a/EmBCsbd

**Comment by AlexTheSysop42** [comment]
The cam was one that failed roundstart
It's a feature, but an annoying one

**Comment by ShizCalev** [comment]
confirmed, just the camera starting off.
