### ISSUE TITLE
Hotkey Trouble - Can't use T and O

### ISSUE THREAD

**Issue by Smeller** [tgstation/tgstation#41309]
Issue reported from  Round ID: 96592 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

When using hotkey mode i can't use T and O to chat or use OOC. Other hotkeys are working just fine. It fixed itself once somehow, but then it happened again.

**Comment by AlexTheSysop42** [comment]
You might have a chat window already up

**Comment by ninjanomnom** [comment]
Do you have multiple monitors?

**Comment by BeeSting12** [comment]
Some guy was complaining about this in OOC on bagil too the other day but it worked fine for me. Think it was Friday or Saturday night.

**Comment by Smeller** [comment]
I think it was me complaining, i also said that somehow it fixed itself later, but just on terry, not on bagil, as i've had both servers opened. 

Just a single monitor.

**Comment by Smeller** [comment]
I think i've figured it out. When i launch the game with RU layout toggled on - those hotkeys are not working, but when i launch the game with EN layout toggled on - it works as good as it always did. Kinda weird but that's how it is.

**Comment by ninjanomnom** [comment]
Oh, yeah this is completely untested with anything besides EN keyboard layout. I'll see about testing some other layouts at some point and potentially fixing this.

**Comment by actioninja** [comment]
Now correctable with hotkey binding
