### ISSUE TITLE
Ash walker tendril can be moved.

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#41300]
## Round ID:96572

I pulled a body near the tendril to make eggs and it moved the tendril up a tile.

**Comment by RedFoxIV** [comment]
intended feature
goes best as a chasm in arrivals

**Comment by Barhandar** [comment]
Dupe as fuuuuck, use search function
#41067 40520 40595 40590 40080

**Comment by Cyprex** [comment]
I did search, and I believe this is a different cause.

**Comment by Cyprex** [comment]
Closing due to dupe
