### ISSUE TITLE
Explosive lance can get embedded inside you.

### ISSUE THREAD

**Issue by yoyobatty** [tgstation/tgstation#41317]
## Reproduction:

This issue has been around forever. Make explosive lance, throw at someone, has a chance of getting stuck inside you. Also you can make lances out of unfinished nades.

**Comment by Tlaltecuhtli** [comment]
feature

**Comment by zamolxius** [comment]
rolled a 1

**Comment by kriskog** [comment]
There don't explode on throw anymore.
