### ISSUE TITLE
Tesla energy ball has no sound

### ISSUE THREAD

**Issue by 00aquir** [tgstation/tgstation#41311]
Energy ball doesn't have a sound on station, except when you're tracking it as a ghost.

**Comment by kingoftheautism** [comment]
@00aquir It could be related to pressure, since you can't heat shit in depressurized areas. Though if you placed tesla in pressurized area (cargo, bar, engineering or something) and it still doesn't have sound then something is broken.

**Comment by Qustinnus** [comment]
cant be reproduced.
