### ISSUE TITLE
Somehow Land White Ship on Transit Z-Level (Metastation)

### ISSUE THREAD

**Issue by Steelpoint** [tgstation/tgstation#41329]
Issue reported from  Round ID: 96667 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

As stated above, I somehow was able to land the White Ship in the transit Z-Level, I landed just above the Arrivals Shuttle but when I exited the ship I was flung off akin to leaving a ship mid-transit.

Steps to reproduce/Exactly what I did

1: Land the ship on Lavaland
2: Take off via sending the ship to a "deep space" location
3: While mid-transit, enter the 'custom ship landing console' thing. From there I was able to set a location in the transit z-level
4: Set your ship to land somewhere in the Transit Z-Level
5: Profit

**Comment by ATH1909** [comment]
Can you use this to "dock with" (aka "park next to") the emergency shuttle after it's left the station?

**Comment by GravitronBlue** [comment]
I was curious myself, a bit of testing later and I was able to do this:
![space station 13 2018-11-07 231731](https://user-images.githubusercontent.com/17460297/48183419-700aa700-e2e3-11e8-9d68-2738c4b731f9.png)

**Comment by Steelpoint** [comment]
I was not able to park the ship directly on the arrivals ship but I could've landed directly next to it.

**Comment by SpaceManiac** [comment]
> 3: While mid-transit, enter the 'custom ship landing console' thing. From there I was able to set a location in the transit z-level

This is the real problem. The console needs to blacklist transit levels.

**Comment by Dennok** [comment]
Stil issue.
You can use another shuttles, from caravan, or etc.

**Comment by Dennok** [comment]
![abbordage in transit s](https://user-images.githubusercontent.com/7734424/48400885-4234c080-e730-11e8-886c-f64bf6f29186.png)
![abbordage in transit](https://user-images.githubusercontent.com/7734424/48400886-4234c080-e730-11e8-8720-683b3a3395f0.png)
