### ISSUE TITLE
Suit accessories with a storage component (ie pocket protectors) can no longer be accessed without first removing them from your uniform

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#41324]
Master

Repo:
Put pocket protector on your uniform
Try to click it
end up taking off your uniform

alt:
Put pocket protector on your uniform
Try to drag it to yourself
nothing happens

I have a couple features in the works that depends on this working, so tagging it as hinders improvements

**Comment by timothymtorres** [comment]
You should now be able to AltClick uniforms to remove the accessories.  Marking this as `Cleanup` that will autoclose in 7 days.
