### ISSUE TITLE
Spontaneous appendicitis can target golems, but it gets cured instantly

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#41334]
Issue reported from  Round ID: 96686 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
Reporting client version: 512

That, or "ghosts can orbit appendicitis" doesn't work correctly.
Golems do have an appendix, by the way.

**Comment by AlexTheSysop42** [comment]
Disease can't infect inorganics probably

**Comment by swindly** [comment]
The event tried to make the golem contract appendicitis, failed, but made the announcement anyway. Make appendicitis affect mobs of all types instead of only MOB_ORGANIC to be consistent with its bypassing immunity and with the selection process for the event.

**Comment by ExcessiveUseOfCobblestone** [comment]
Do golems have appendices lorewise? Just make it filter inorganics in the selection instead lol.

**Comment by swindly** [comment]
https://github.com/tgstation/tgstation/issues/37084
coiax says that golems feeling hunger is not a bug, but if that issue is resolved by giving golems NO_HUNGER, this issue should be fixed too.
