### ISSUE TITLE
Tactical atmos holobarriers

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#41348]
Round ID: 96742
Atmos holobarriers are layered above mobs, making it so you can't directly click them in order to melee.

Possible fixes include making the sprite smaller, or make it so it isn't layered above mobs.

Issue stems from a round where a group of players on the arrivals escape pod were able to hold out against a conventional invasion where ultimately I was unable to defeat them due being unable to click them with a stunprod due to hitting the holobarrier instead.
(alt clicking the turf would result in me getting disarmed and it isn't suitable for combat)

**Comment by GravitronBlue** [comment]
Atmos holobarriers were made to block gas flow and I imagine not have any practical application in combat, as in the original version they were simply a small holo fan on the floor. The sprite was updated later to a more quality icon but being able to be used as a shield sure seems like oversight.

I also don't see how being "outsmarted and outgeared" is relevant here or why you're saying that.

I was able to reach a point where combat was the most viable way for me to board the escape pod, (without having to smash my way in from space and likely result in everyone's death) only for a regenerating shield to completely stop me from clicking anyone under it and force me to stand close trying to open the alt-click menu and hit those in the way.

**Comment by ATH1909** [comment]
New anti-nukeop strat/meta.

**Comment by Barhandar** [comment]
Just throw the prod smh

>(without having to smash my way in from space and likely result in everyone's death) 

2 minutes is enough to break one of the corner walls and construct a chair out of its remains.

**Comment by ExcessiveUseOfCobblestone** [comment]
this is also true with PENLITEs although much harder since there's a long setup to spawn.
