### ISSUE TITLE
Local assistant discovers revolutionary new way of 'buying' things from vendors

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#41349]
![money](https://user-images.githubusercontent.com/17460297/48168333-a9bbbd80-e2a3-11e8-829e-5a4ae3ef7906.png)

Despite premium items showing up as costing their regular amount attempting to 'purchase' one will
still vend it to you for free.

[![IMoney](http://img.youtube.com/vi/Y90MYtGI-20/0.jpg)](http://www.youtube.com/watch?v=Y90MYtGI-20 "One thing's sure it's real you see when you got GOOFSPIRACY")

This is probably where it should be stated how to reproduce this, but as an assistant main maybe now isn't the time for [Goof's darkRP conspiracy](https://i.imgur.com/ILlaKuc.png) to come true or otherwise support [assistant oppression](https://i.imgur.com/PExkw8Q.png) because honestly [this.](https://i.redd.it/hhm8p0znhw3z.jpg)

EDIT: Secret has been spilled as stated by Swindly, lavaland and anywhere that isn't the station being the location where COMMUNISM still exists and basically every vendor is free while buying from them there. (Unlikely feature?)

**Comment by ShizCalev** [comment]
@Iamgoofball

**Comment by swindly** [comment]
Moving the vending machine to lavaland (or any z level besides the station) lets people get stuff for free.

**Comment by GravitronBlue** [comment]
Pretty much what you just said is correct, no point hiding it now any longer I guess, good while is lasted.

**Comment by Iamgoofball** [comment]
Oh well, time to remove vending machines being free on lavaland. Ghost roles will just have to make do.

**Comment by XDTM** [comment]
could be a map-editable variable

**Comment by SgtxRootbeer** [comment]
Should just be a mapedit-variable on the machine, what dink decided to put in a z-level check?

**Comment by evsey9** [comment]
if we remove economy then this bug will be fixed

**Comment by Potato-Masher** [comment]
economy was a mistake

**Comment by Iamgoofball** [comment]
@XDTM Then I have to manually edit like 50 maps then remind people to do the same edit. No thanks.

**Comment by XDTM** [comment]
Perhaps a mapload check then? If the vendor is maploaded in the lavaland z-level free items are applied, but building or moving it won't change anything

**Comment by Supermichael777** [comment]
>what is initialize

**Comment by Bawhoppen** [comment]
My guess is that from a code standards perspective, replacing all of the zlevel vendors with a proper free subtype is the right way to do it.

**Comment by XDTM** [comment]
That's a pretty copypastey solution, the proper method would be a generic z-level check for the base type.
A map-editable variable would be even better, but it does require modifying all existing instances first.

**Comment by 81Denton** [comment]
>Then I have to manually edit like 50 maps then remind people to do the same edit. No thanks.

So this is.... the power of paid PRs....
