### ISSUE TITLE
Players can emote without cooldown

### ISSUE THREAD

**Issue by miniusAreas** [tgstation/tgstation#41345]
Found via the TGbased Sunsetstation codebase, confirmed from there it was upstream issue.

Players, depending on how quick their ctrl-v skills, how fast they can type, or how smart at scriptkiddies they are, can spam alternating emotes with 0 cooldown to bypass chat stacking. Although its funny to hear and watch a clown honk, flip, and spin a million times a second, it can still cause major slowdowns and or freezings on low-end machines, as well as causing anything said in the chatpannel to wiz by faster than sonic on ss13 meth. Im also pretty sure spammings against rule 1 anyhow. Still, it helps to create a system to combat it, although im pretty sure one exsists allready that works 1% of the time.

Found while putting the clown in a cell for minor battery who then froze my game with me seeing him honkflipspin out of brig when i recovered.

**Comment by AlexTheSysop42** [comment]
People can also say without cooldown, or do a comm loop 
Rule issue, bean em for spam

**Comment by BeeSting12** [comment]
Should be handled by the admins on the server rather than by the code.

**Comment by miniusAreas** [comment]
@AlexTheSysop42 Fair, but its a oversight in the bot, non the less, as the bot detects radio and ooc floods, but not emotes.

**Comment by ShizCalev** [comment]
Spamming falls under rule 1. This is an administrative issue.
