### ISSUE TITLE
Antags sent to the ninja dojo "escape"

### ISSUE THREAD

**Issue by miniusAreas** [tgstation/tgstation#41355]
In the title, due to the way the centcom z-level works, a antag sent to the dojo will recive the "escaped out of custody" objective as completed. This is clearly not the case, as your stuck in a dojo, not on a ship.

Possible fix is changing the tiles to have a var much like the shuttlebrig tiles.

**Comment by ExcessiveUseOfCobblestone** [comment]
They "escaped" from centcomm custody, just as a Space Ninja pow instead lol

**Comment by tralezab** [comment]
The ninjas can be syndicate or nanotrasen, so...

**Comment by Shadowflame909** [comment]
@miniusAreas  There's no way to escape from ninja jail. But I believe it's lore-wise known that the ninjas will send you there, whilst their collectors (Either the syndicate or Nanotransen) come to pick there targets up. So it, in fact, does count as escaping.

**Comment by dragomagol** [comment]
Rip ninja jail
