### ISSUE TITLE
Play-internet-sound is yet again broken!

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#41353]
RoundID: 96765

Reproduction: Try to play something with it, for some links it works, other links won't, most won't.

also throws out this GIANT ERROR.

Youtube-dl URL retrieval FAILED:

ERROR: Signature extraction failed: Traceback (most recent call last):
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\youtube.py", line 1221, in _decrypt_signature
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\youtube.py", line 1130, in _extract_signature_function
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\youtube.py", line 1193, in _parse_sig_js
 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\common.py", line 977, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by SpaceManiac** [comment]
if updating youtube-dl isn't on a cronjob it should be

**Comment by Borisvanmemes** [comment]
Also hi should've linked this in the issue itself,
#40210

**Comment by Borisvanmemes** [comment]
It seems to work again, again.

**Comment by Borisvanmemes** [comment]
It is not in fact fixed.

**Comment by SpaceManiac** [comment]
could we get some examples of working/non-working URLs

**Comment by Borisvanmemes** [comment]
https://www.youtube.com/watch?v=0tdyU_gW6WE this one doesn't work, 
https://www.youtube.com/watch?v=XtAhISkoJZc this one also doesn't work, 
https://www.youtube.com/watch?v=dxNvFVI2G38 and this one,

https://www.youtube.com/watch?v=1WAlkyxz2mU this one works, 
https://www.youtube.com/watch?v=IAtnmKdhiDk this one also works, 
https://www.youtube.com/watch?v=lWoLVBNjjPo and this one works too.

**Comment by SpaceManiac** [comment]
tested locally, `youtube-dl` just needs to be updated @MrStonedOne

**Comment by Borisvanmemes** [comment]
It's been updated afaik.
