### ISSUE TITLE
Ninja APC drain prevents APC recharging

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#41354]
A ninja managed to drain a bunch of APCs but the APCs still thought they were fully charged and wouldn't update back to charging unless the charging was manually reset.

**Comment by ExcessiveUseOfCobblestone** [comment]
the gloves just subtract the charge from the cell of the APC rather than using the proper use proc

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/858878288d7ab0fd6ae78d642a265c69dd4a54df/code/modules/ninja/suit/ninjaDrainAct.dm#L47

just replacing with `cell.use(drain)` would prob fix
