### ISSUE TITLE
Manifest rune perma stuns the invoking cultist

### ISSUE THREAD

**Issue by GLACoding** [tgstation/tgstation#41365]
Round ID: 96796

Testmerges:
#41099: 'New Map: Donutstation (WIP)' by MMMiracles at commit d716cd1555
#41155: 'Adds three new .38 ammo types' by 81Denton at commit eb1ea872fa
#41313: 'Replaces the move fast traits with speed mods' by ninjanomnom at commit 59c8947cf8

Reproduction:
1. Become Cultist
2. Draw manifest rune and use "Summon Cult Ghost"
3. Become stuck on the rune, with no way to run off
4. Slowly die from brute damage

Apparently caused by #41068

**Comment by Sealed101** [comment]
can't reproduce anymore
