### ISSUE TITLE
spectral blade is a ghost trap

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#41379]
96837

ghosts after following the spectral blade will be teled back to it if they try to move away

**Comment by ShizCalev** [comment]
@ninjanomnom

**Comment by DaxDupont** [comment]
Feature

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=m9We2XsVZfc

**Comment by zamolxius** [comment]
feature

**Comment by kriskog** [comment]
This has since been fixed
