### ISSUE TITLE
Not so Explosive Lances

### ISSUE THREAD

**Issue by KangTut** [tgstation/tgstation#41372]
Issue reported from  Round ID: 96824 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Recently tried using explosive lances to see if the syndie minibomb lance still worked. Turns out that explosive lances aren't exploding at all. Tried it with a minibomb, frag grenade, flashbang and a water/pot grenade. None of them worked aside from being a more expensive spear.

**Comment by ShizCalev** [comment]
#41317

**Comment by k-k-karma** [comment]
not #41317 
explosive lances are meant to embed if not exploding

**Comment by ma44** [comment]
The lance could've been caught by the person that's the target; probably needs reproduction

**Comment by KangTut** [comment]
I was throwing it at catatonic bodies that I spawned in. Even when the lances didn't embed they just vanished with no explosion.

**Comment by Vidiveni** [comment]
I threw an explosive lance at a mech. It just caused sparks and angered the mech pilot further.

**Comment by subject217** [comment]
https://github.com/tgstation/tgstation/pull/41223

@MrDoomBringer 

alternatively, leave it this way because elances are awful
