### ISSUE TITLE
E-Bolas don't slow down anymore

### ISSUE THREAD

**Issue by Garen7** [tgstation/tgstation#41370]
## Testmerges:
Test merge active of PR #41099 commit 
Test merge active of PR #41155 commit 
Test merge active of PR #41269 commit 
Test merge active of PR #41313 commit 

## Reproduction:

Get hit by an E-Bola but run at full speed.

**Comment by Garen7** [comment]
related to #41332?

**Comment by Vidiveni** [comment]
Same with bear traps.

**Comment by Yenwodyah** [comment]
Also applies to snares from dragnets

**Comment by Garen7** [comment]
90% sure this isn't an issue anymore so I'm closing it.
