### ISSUE TITLE
Most objects with text have no literacy check

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#41396]
is_literate() checks only exist for A) reading papers and B) writing on some items.

Illiterate mobs/players can still read:
* Spellbooks
* Manuals (static and wiki)
* All TGUI and HTML interfaces, including consoles, newscasters, etc.
* Status displays

**Comment by ATH1909** [comment]
Sort of related to this: Should races that can't speak Common be able to read the names on ID cards or the text (well, the text written by people who are currently set to speak in Common) on paper? Are they already able to?

**Comment by timothymtorres** [comment]
This was fixed with #66648 since it added literacy checks to a bunch of stuff.
