### ISSUE TITLE
Musician supply pod being used offensively

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#41395]
The musician quirk supply pod can be used for a lot more than it is probably intended for now that it creates an explosion, it can be used to (safely) set off syndie bombs, welding fuel tanks, harm stunned people, etc. Is all this really needed for something that only makes an instrument appear? I didn't think it was a bug back when it was harmless but apparently it was, and shouldn't have been.

**Comment by Vidiveni** [comment]
I like it this way.

**Comment by YakumoChen** [comment]
Quirks shouldn't be giving people any sort of obvious and major advantage, not to mention it's a combat change.

**Comment by Robe21** [comment]
🤣

**Comment by Robe21** [comment]
😁
