### ISSUE TITLE
Gib list length mismatch!

### ISSUE THREAD

**Issue by k-k-karma** [tgstation/tgstation#41406]
during a round, you may occasionally see Gib list length mismatch! in the middle of it. unsure how to reproduce except join a regular round and observe. presumably caused by #41374

**Comment by ShizCalev** [comment]
round number?

**Comment by ShizCalev** [comment]
Not seeing anything about this in the logs.

**Comment by Jordie0608** [comment]
It's from a `to_chat()`, doesn't make any logs.
https://github.com/tgstation/tgstation/blob/8b2b59732411886be5869c520113b49f854e6fce/code/game/objects/effects/spawners/gibspawner.dm#L14

**Comment by Arianya** [comment]
Can confirm, just saw this on bagil during Round 96931

```Round ID: 96931
BYOND Version: 512.1453
Server revision compiled on: 
Master commit: 3ef4881b4d21078056aedfef649f5c5fd27dc8c8
The following pull requests are currently test merged:
#41313: 'Replaces the move fast traits with speed mods' by ninjanomnom at commit 59c8947cf8
#41269: '[s] ghosts one more time' by AnturK at commit 3a973a0a7b
#41155: 'Adds three new .38 ammo types' by 81Denton at commit eb1ea872fa
#41099: 'New Map: Donutstation (WIP)' by MMMiracles at commit d716cd1555
#41258: '[READY] Goon Genetics' by Time-Green at commit d50b3f9457```

**Comment by Barhandar** [comment]
Reproduction: sacrifice a body to ash walker tendril. It also leaves invisible objects.

**Comment by k-k-karma** [comment]
it's human gibs i believe yeah

**Comment by ShizCalev** [comment]
bodypartsless gibs. fix pr is already up.
