### ISSUE TITLE
Weird font issue?

### ISSUE THREAD

**Issue by Nippythewalrus** [tgstation/tgstation#41402]
## Round ID:
FIXED!! It was a font problem. Reinstalled default fonts and it fixed it.

Every single round I can remember.

## Reproduction:
So uhh my font looks really weird and it makes it so I am unable to play geneticist or even use remote signalers or secure briefcases, or anything with numbers. This is what it looks like https://i.imgur.com/udPMH1N.jpg
I've had this issue as long as I can remember and I even posted it on reddit no one has been able to help me fix it.

**Comment by Time-Green** [comment]
Try updating internet explorer

**Comment by optimumtact** [comment]
Are you using a non english locale on your computer?

**Comment by Nippythewalrus** [comment]
No @optimumtact  I am not, I'm using an english locale. I've tried uninstalling and reinstalling as well as clearing IE cache.

**Comment by Nippythewalrus** [comment]
@Time-Green I have the "automatically update" box checked on IE. This is really frustrating cause I have been dealing with this for quite a long time :/ I've heard that it could be a font issue but I have no idea how to check and fix that.
