### ISSUE TITLE
Simple Mobs actions disabled upon revival with a lazarus injector 

### ISSUE THREAD

**Issue by timothymtorres** [tgstation/tgstation#41408]
## Round ID: 

 96903

## Reproduction:

I saw a gorilla geneticist go on a 6 kill rampage as a gorilla.  Throughout his kill spree I constantly followed him and reported his killing over the radio.  Surprisingly he never attempted to kill me or harm me.  Security finally tracked him down and lethal'd him to death.  I had the brilliant idea of getting a Lazarus injector from mining and getting him revived.  I figured he could hunt megafauna for miners or something, and since he didn't have access to the shuttle console wouldn't be a threat to the main station.  Well it turns out he revived successfully, but he was super bugged.  The following problems experienced by the gorilla:

- He couldn't move
- He couldn't pickup objects
- Mobs and players were able to pass through his sprite

- He could talk and unbuckle himself from chairs
- He could attack adjacent objects

I ended up telling him I was going to give him to the clown as a pet.  It never happened though, the shuttle got called and emagged.  And no, he didn't kill anyone after he was revived fortunately.

**Comment by Euphausiacea** [comment]
Did some testing. Turns out that all simple_mobs lose all mobility flags when admin revived(the kind of revive the laz injector uses)

**Comment by ExcessiveUseOfCobblestone** [comment]
This is a dupe I think

**Comment by ATH1909** [comment]
Why hasn't this been fixed yet?

**Comment by ExcessiveUseOfCobblestone** [comment]
because no one here works for tg
