### ISSUE TITLE
Syndicate 50.cal Sniper rifle's zoom button missing.

### ISSUE THREAD

**Issue by InsaneKatrina** [tgstation/tgstation#41403]
From round ID 96901

As the title suggests, the HUD button to enable/disable the zoom function of the syndie's 50.cal is missing entirely. An additional note (Thanks Nervere), is that both the syndie and standard firing pin snipers have no access to the HUD key, though this is probably more of an issue to the gun itself than anything, perhaps worth mentioning regardless.

**Comment by Borisvanmemes** [comment]
Went and tested it in the thunderdome, the button is in fact gone.
