### ISSUE TITLE
Vent crawling extremely laggy

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#41433]
Vent crawling is often very slow, and if there is a bit of server load it lags out for a second or so every time you move. This makes moving around quite challenging.

I took a look at the code, vent crawling is removed and reapplied every time you move. This causes you to iterate through the entire list of pipes etc in the current pipeline, and remove, update and reapply the pipe images to the client view. In most cases, we are talking about a few thousand pipes in a pipeline. I assume this is what lags the client out.
It seems to be taxing on the server resources as well, topping out at about 25 cpu (up from ~5) according to MC tab on a fresh round on local server.

## Reproduction:
Go vent crawl with a bit of load. Harder to reproduce locally, recommend testing on live server.

Edit: Movespeed in vents matter. Go with higher movespeed to reproduce more reliably. Slimes are fast enough by default.

**Comment by Cyprex** [comment]
This is also a severe issue for me, I have to tap the key briefly, else the lag from moving a tile will make me move to the end of the pipe(in that direction).
