### ISSUE TITLE
Upgrade Camera Network now changes camera sprite

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#41436]
This is honestly a very terrible change that I have noticed recently, what was once one of the better ai upgrades to get for stealth reasons has been turned to shit, you used to get this ability and Enhanced Surveillance to be ablee to spy on the crew to see if anything fucky is going on, now the crew can just notice all of the different cameras everywhere and know you're malf, you may as well be putting blue apcs all over the station when you buy this now.

**Comment by optimumtact** [comment]
@ShizCalev this is a bug, or more accurately a regression, make the AI malf camera upgrade not trigger the icon state change.

**Comment by ShizCalev** [comment]
@optimumtact

How is it a consistency issue? You're asking to have an inconsistency put back in.

You can also tell by examining it, attacking it with an analyzer, deconstructing it and seeing it suddenly drops an analyzer, or screwdrivering it.

**Comment by ShizCalev** [comment]
Wrong button
