### ISSUE TITLE
Changelings that are beheaded twice are unable to revive.

### ISSUE THREAD

**Issue by penterwast** [tgstation/tgstation#41435]
Changelings that are beheaded twice have their mind transferred to their detached head and cannot revive.

I've seen it happen with box suicides and with decapitation by weapons.

Reproduction:

1. Be a changeling
2. Get decapitated (e.g. suicide with a box).  Your mind remains in the body.
3. Revive and regrow your head
4. Get decapitated again
5. Your mind is in the detached head, and you cannot revive again.

**Comment by k-k-karma** [comment]
not nice >:[

**Comment by evsey9** [comment]
then don't fucking get decapitated so much learn to play good
