### ISSUE TITLE
Weapons used to attack cyborgs with become bloody

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#41439]
Seems rather self explanatory. Attack a cyborg with a wrench or something and the wrench will become bloody despite the borg lacking any blood.

Issue reported from  Round ID: 96965 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/c7856d8e3ae7a2ddc2e5b174338bd0a25296eae8/code/game/atoms.dm#L347-L348

my meme backfired :(

**Comment by kriskog** [comment]
Can't reproduce with a wrench, but your clothes become bloody.
