### ISSUE TITLE
Giving a moth an alien mask force feeds him alien

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#41437]
probably because huggers are classified as clothing, which apparently counts as food...

**Comment by Tlaltecuhtli** [comment]
emergent gameplay

**Comment by HomocidlePancakes** [comment]
Finally some use for moths

**Comment by Anonmare** [comment]
Feature

**Comment by XDTM** [comment]
can't get infected if you chew it first

**Comment by ATH1909** [comment]
Does this work with Lamarr?

**Comment by YakumoChen** [comment]
eaten aliens don't infect, no.

**Comment by Shardj** [comment]
Fun fact, you can also use wrapping paper on facehuggers and post them

**Comment by kriskog** [comment]
Help intent  tries to feed the moth, harm applies mask as expected. It is a clothing object, moths eat clothing. /obj/item/clothing/mask/facehugger

**Comment by Shardj** [comment]
Sounds like a feature to me

**Comment by ArcaneDefence** [comment]
You no longer fail to put the facehugger on the moth while off combat mode.
