### ISSUE TITLE
[goon genetics] swedish mutation gives you not ascii chars

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#41453]
![image](https://user-images.githubusercontent.com/222630/48382676-fe41ad00-e696-11e8-8e2e-d76f849c34df.png)

**Comment by Time-Green** [comment]
hyper realistic

**Comment by Time-Green** [comment]
Also just post them on my PR, I’ll read it anyway

**Comment by Time-Green** [comment]
Also just post them on my PR, I’ll read them anyway
