### ISSUE TITLE
Who tf made this buildmode hud?

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#41473]
![image](https://user-images.githubusercontent.com/38788538/48412637-4c69b580-e756-11e8-9773-28d4613f344f.png)

Why can't we have 2 options for people who prefer this ~~bullsh~~ hud and who prefer to ~~use macr~~ just click on the icon?

**Comment by ExcessiveUseOfCobblestone** [comment]
1 click > slight move of mouse > 1 click vs many clicks not even including if you click too fast and miss?

It's fine.

**Comment by optimumtact** [comment]
this isn't an issue report
