### ISSUE TITLE
borgs can force ride humans and throw for stuns

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#41471]
the knockdown stun is long enough for default borgs to cuff, or otherwise do a task long enough to kill a human, and they can force humans to ride through grab and drag.

**Comment by Nickkoranda** [comment]
feature

**Comment by HydroFloric** [comment]
Feature

**Comment by HomocidlePancakes** [comment]
Intended. Git gut scrub

**Comment by Tlaltecuhtli** [comment]
feature

**Comment by improvedname** [comment]
Put a delay on piggybacking

**Comment by obscolene** [comment]
ided

**Comment by OmegaShoots** [comment]
literally ided

**Comment by zamolxius** [comment]
feature

**Comment by nemvar** [comment]
feature
