### ISSUE TITLE
Holodeck matchboxes drop matches on deletion

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#41485]
`/obj/item/storage/box/matches`

When holodeck matchboxes get deleted, they will drop their contents as regular items that are missing the `HOLOGRAM_1` flag.

**Comment by ShizCalev** [comment]
Appears to affect anything that uses COMSIG_TRY_STORAGE_FILL_TYPE (so matchboxes and snappop boxes atm)
