### ISSUE TITLE
Sentient Disease: No Symptoms on Spawn

### ISSUE THREAD

**Issue by KangTut** [tgstation/tgstation#41499]
Issue reported from  Round ID: 97088 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

A sentient disease randomly spawned during the round but they had no symptoms when they infected their first host. No cough on command or anything. They only had one evolution point which could not afford them anything. This made them nothing more than a spectator than an antag.

I spawned a sentient disease shortly after receiving the ahelp from the first one just to see if this wasn't some odd one time issue but it was consistent.

**Comment by ATH1909** [comment]
This is apparently already being worked on (but thanks for reporting it): https://github.com/tgstation/tgstation/pull/41490

**Comment by ExcessiveUseOfCobblestone** [comment]
heh
