### ISSUE TITLE
Irradiate projectiles (x-ray gun, fusion) ignore radiation protection

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#41502]
Issue reported from  Round ID: 97090 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
Reporting client version: 512

More specifically apply_effect(s) directly modifies radiation var on the hit living mob. No checks or anything, just flat rads no matter if you should be completely immune due to radsuit or not.

This is caused by radiation rework forgetting to update https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/damage_procs.dm#L104 to account for, you know, radiation (last actually meaningful change to the line was over 4 years ago).

Also you can't change it to rad_act because rad_act calls apply_effect(EFFECT_IRRADIATE) itself.

**Comment by ExcessiveUseOfCobblestone** [comment]
so why does radiation armor work with anything? What do other sources do different?

**Comment by Barhandar** [comment]
The other sources call rad_act instead of directly apply_effect(s), only projectiles do this and all other rads aren't projectiles.

**Comment by ExcessiveUseOfCobblestone** [comment]
you said `you can't change it to rad_act` though which is where i'm stumped. Just change whatever the `irradiate` var is dictated by to use rad_act instead lol

**Comment by kriskog** [comment]
Theres also a thing where even if you wear a full rad suit, your clothes and items get irradiated and will kill you if you take the radsuit off.

**Comment by pireamaineach** [comment]
@kriskog Radiation suits should protect the contents of them from radiation.

**Comment by kriskog** [comment]
Yes it should. But it doesnt. Thats for another issue though.
