### ISSUE TITLE
Ghosts are being informed when Minor Space Dust triggers

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#41506]
## Round ID: 97102

![image](https://user-images.githubusercontent.com/609465/48505988-4d771180-e840-11e8-8503-e6dfc5b84e15.png)

Minor Space Dust shouldn't be notifying ghosts, may be a regression caused by #40727? @MrDoomBringer

**Comment by Barhandar** [comment]
I don't remember any notifications on the random small meteors, and the meteor_wave (minor dust, major dust, meteors, meateors) event is _supposed_ to give notifications regardless of severity.

**Comment by ExcessiveUseOfCobblestone** [comment]
Yes.
