### ISSUE TITLE
Chem Reactions don't always trigger

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#41509]
Master

Repo:
Be virologist
put 1u of blood in a beaker
dropper 1u of plasma in
nothing happens
put 1u more of plasma
single reaction takes place
![image](https://user-images.githubusercontent.com/6209658/48513441-c6b73a00-e829-11e8-8d70-91584f02c4c0.png)

https://github.com/tgstation/tgstation/blob/70b623ea13b4d1e0bc1bf6636ad77ea18ad2be9f/code/modules/reagents/chemistry/recipes/others.dm#L213-L237

**Comment by Tlaltecuhtli** [comment]
shut it down

**Comment by AnturK** [comment]
From quick glance it's because reaction cache does not index catalysts.

**Comment by ShizCalev** [comment]
I've had it happen both ways, adding plasma first, adding blood first, ect.

**Comment by XDTM** [comment]
when it happened to me i usually saw one of the reagents was 0.999997 or something instead of 1, so it might be related to a rounding error (although the vv panel seems to indicate otherwise)

**Comment by nicbn** [comment]
Possible solution is to round reagents to the first or second decimal place in reaction checks

**Comment by timothymtorres** [comment]
> when it happened to me i usually saw one of the reagents was 0.999997 or something instead of 1, so it might be related to a rounding error (although the vv panel seems to indicate otherwise)

This is exactly the reason why this is happening.  I've seen this happen numerous times as a virologist over the ten years I've played and it's annoying.

**Comment by timothymtorres** [comment]
Duplicate of #31206
