### ISSUE TITLE
You can't remove the panel off the Vault Blast Door.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#41510]
Issue reported from  Round ID: 97109 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Not sure if this is the case with other blast doors, but the wire cover on the vault door is unable to be removed with a welder.

1. Screwdriver initial panel
2. Use welder to remove secure wire panel
3. 'This airlock doesn't need repairing!'

**Comment by YPOQ** [comment]
The vault doors are high-security instead of medium-security that you find in some other places.
https://tgstation13.org/wiki/Guide_to_hacking#Secure_airlocks
