### ISSUE TITLE
Spontaneous Appendicitis event has incorrect follow text

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#41525]
Round ID: 97136
![image](https://user-images.githubusercontent.com/609465/48551675-22d39a00-e8ce-11e8-9d9a-6059ce7e05ce.png)

The poor clown that's been infected (Squanker) hasn't been spawned by the event, merely their appendix has suddenly been inflamed.

@MrDoomBringer

**Comment by SpaceManiac** [comment]
already fixed
