### ISSUE TITLE
Linking a new ID (or ID with a custom title?) to a paystand does not alert the account holder of payment

### ISSUE THREAD

**Issue by Malkraz** [tgstation/tgstation#41567]
Was Clown, Captain gave me a new silver ID with some access on it and a custom title. Linked the ID to my bank account and used it to set up a paystand. Did not get alerts when people used the stand.

**Comment by ShizCalev** [comment]
@Iamgoofball

**Comment by jlsnow301** [comment]
no longer valid after #63889
