### ISSUE TITLE
High energy SM pulls you regardless of being a human

### ISSUE THREAD

**Issue by Unit2E** [tgstation/tgstation#41578]
## Issue:
The supermatter crystal, when highly charged, has a pulling effect on objects. However, the code for supermatter_pull suggests that it should not pull humans, and instead stun them. This is not the case, as currently, it both pulls humans and stuns them. The code includes two seperate if statements where it attempts to change the effects of the supermatter_pull proc depending on object status and human status, however, it fails.

## Reproduction:
Get the SM delamming with a ton of CO2 or plasma to get it to really high energy levels, and stand in the engine room. You'll be pulled towards the SM crystal, and stunned. Mag boots do not stop the pull nor the stun, same for insulated gloves.

**Comment by Barhandar** [comment]
Cannot reproduce on local. Are you sure it was the pull effect, and not errant gravitational anomaly or somesuch?

**Comment by Unit2E** [comment]
Hum, after more testing, it seems it might be grav anomalies, hah. I never realised they were so janky, teleporting you across rooms. Ah well, that resolves that, oops. Unrelated but related though, maybe some feedback on the SM stun and gravitational pull and stun would not be entirely out of place.
