### ISSUE TITLE
polymorphed xenos and antagonist status

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#41580]
polymorphed xenos get xeno antag status, and retain it even if they get morphed to a different form. this can cause issues for mulligan/roundend thresholds, alongside giving people "antag" status when most polymorphs are probably willing changes.

**Comment by WJohn** [comment]
Yeah, this happens with admin transformations too, when you do tests with it you stay on the antag panel even if you transform yourself back into a human.

**Comment by kriskog** [comment]
#45230
