### ISSUE TITLE
Hunger slowdown as ops

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#41591]
## Round ID: 97310

This round, I got hunger slowdown just 15 minutes into the round as nuke op. There is a single slice of pizza at the op base, as well as some donuts on the ship. Regardless, I think ops should start with a higher nutrition so you don't get this dumb shit because you forgot to eat or there was not enough food for everyone. The 20 minute war timer is important to keep in mind here as well.

Also, I ded.

**Comment by ma44** [comment]
20 minutes to eat food 🤔

**Comment by Tlaltecuhtli** [comment]
eat the carp

**Comment by nicbn** [comment]
Just make ops and deatshsquad spawn with a nutriment pipe, problem solved

**Comment by nemvar** [comment]
![FIXED](https://user-images.githubusercontent.com/47324920/61673699-cfcda480-acf0-11e9-8fe7-65ca56bb2554.PNG)
FIXED
