### ISSUE TITLE
The clown lavaland ruin is a joke again due to slip movement

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#41590]
since you can move while being slipped that more or less destroys the difficulty

**Comment by ShizCalev** [comment]
@optimumtact

**Comment by AlexTheSysop42** [comment]
Make lube use old stun

**Comment by Cyprex** [comment]
Agreed, you can just crawl and be done with it. Crawling was a mistake.

**Comment by duckay** [comment]
crawling was _THE_ mistake

**Comment by Daxxed** [comment]
Honk!!!
Once you have done it one time the difficulty is gone and the thing becomes just a waste of time.
Atleast right now people actually clear the ruin, occasionally.
