### ISSUE TITLE
Can't interact with anything around me during plasma flood hallucination

### ISSUE THREAD

**Issue by Syncronia** [tgstation/tgstation#41607]
Issue reported from  Round ID: 97377 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512
Can't pick up or interact with stuff during plasma flood hallucination

**Comment by ShizCalev** [comment]
Easy fix

**Comment by ArcaneDefence** [comment]
https://github.com/tgstation/tgstation/pull/49810
Pretty sure this issue can be closed now.

**Comment by Dennok** [comment]
> Easy fix

Be unfixed more than year.

**Comment by Dennok** [comment]
@maintainer
