### ISSUE TITLE
corgi hide aint not didnt sell for money

### ISSUE THREAD

**Issue by WaterStBlues** [tgstation/tgstation#41612]
Issue reported from  Round ID: 97390 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

couldn't sell my puppy skins for those sweet sweet capitalism credits

please fix (also buff, 200 is ridiculous for the work that goes into the illegal puppy trade)

**Comment by kingoftheautism** [comment]
you monster

**Comment by 81Denton** [comment]
Was the console hacked to enable contraband or emagged? Human/cat/animal skins only pay if you do that first
