### ISSUE TITLE
fire burning clothing behind fireproof clothes 2: electirc boogaloo 

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#41618]
>be op >elite hardsuit in combat mode >start fire >Your syndicate mask starts to fall apart! >die

**Comment by yoyobatty** [comment]
Doesn't it remove the hide mask and goggles flags?

**Comment by Electronics** [comment]
Ohhhhhhhh this is what happened with me with the Captain's hardsuit the other day as well. Reproducable as of yesterday.

**Comment by davethwave** [comment]
If your wearing the helmet thing, it shouldn't be able to burn the mask at least.

**Comment by AlexTheSysop42** [comment]
If your helmet's not sealed what did you expect

**Comment by ShizCalev** [comment]
Turning on combat mode makes the user's face/mask visible, hence it removing the HIDEMASK & HIDEGOGGLES flags. Working as intended
