### ISSUE TITLE
Purge modules can remove law 0 from a malf AI

### ISSUE THREAD

**Issue by Ulamate** [tgstation/tgstation#41625]
Issue reported from  Round ID: 97443 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Hey friends. I was adminning a usual traitor round with the AI being one of the traitor rounds. A fun gimmick was occurring, and the AI helped facilitate most of the gimmick. However halfway through this, an engineer was noticing that the AI was shutting down tcomms and decided to reset the AI using a purge module and then an asimov module. What SHOULD happen is that the AI simply gets all its laws removed (save the law 0) and then its laws are reapplied, basically doing nothing to it. However, this time what occurred was the AI losing its law 0, but still keeping its malf powers and functions. This made things slightly confusing as on one hand, they were still clearly malf. On the other hand, they now had a standard asimov set with no law zero. I myself on a later round recreated this and confirmed that you can lose your law zero with a purge, yet reapplying the traitor status will fix this from further purges.

**Comment by YakumoChen** [comment]
I've had this happen before due to ion laws or excessive law uploads. I believe the precedent was that "because I had antag status, I didn't truly need the law to do whatever I wanted", but I suppose that would remove one of the only real tells of malf AI.

Watch out though because I've had resetting my malf status screw with the amount of TC/Cycles/APC Points I've had before, limited to one bug I discovered where I was able to reset my malf status over and over, resulting in effectively infinite points.

**Comment by k-k-karma** [comment]
bug, you shouldnt lose law 0

**Comment by Cyprex** [comment]
Please edit the issue title to something more descriptive like. "Purge modules can remove law 0 from a malf AI"

**Comment by Anonmare** [comment]
`
/obj/item/aiModule/reset/purge/transmitInstructions(datum/ai_laws/law_datum, mob/sender, overflow)
	..()
	if(law_datum.owner)
		law_datum.owner.clear_inherent_laws()
		law_datum.owner.clear_zeroth_law(0)
		remove_antag_datums(law_datum)
	else
		law_datum.clear_inherent_laws()
		law_datum.clear_zeroth_law(0)

/obj/item/aiModule/reset/purge/proc/remove_antag_datums(datum/ai_laws/law_datum)
	if(istype(law_datum.owner, /mob/living/silicon/ai))
		var/mob/living/silicon/ai/AI = law_datum.owner
		AI.mind.remove_antag_datum(/datum/antagonist/overthrow)
`
Is this the problematic code?

**Comment by zxaber** [comment]
For what it's worth, when I heard of this particular incident mentioned in the Discord the other day, I downloaded a current copy of the code to test and could not reproduce. My steps were simply have a round-start Malf, and another character in the upload using purge/asimov boards, and I could not remove it. Even the One-Human board properly fails to replace law zero.

Were there any testmerges that could be causing this? Alternatively, was this a non-natural Malf?

**Comment by Ulamate** [comment]
The AI in question was indeed roundstart.

**Comment by Anonmare** [comment]
@zxaber Did you try testing it when the AI was piloting an AI shell?

**Comment by zxaber** [comment]
Oh nope, I didn't think of that. But yeah, that did it. Time to figure out a fix.

I assume there's been an admin ruling that if a bug removes Malf law zero, the AI gets to be antag still, right? If not, should a policy thread be made. For the record, in this particular instance, the AI keeps the Malfunction tab and abilities.
