### ISSUE TITLE
Feedback issues

### ISSUE THREAD

**Issue by nfreader** [tgstation/tgstation#41621]
Running issues found with the feedback table

- [ ] Changeling Powers feedback gives invalid JSON:

From: https://sb.atlantaned.space/rounds/97359/changeling_powers

```Error: Parse error on line 7:
...": 4,			"4": 4,			1: null,			1: null,
---------------------^
Expecting 'STRING', got 'NUMBER'```

**Comment by Jordie0608** [comment]
I'm gonna close this since you can still append it and otherwise it'd just never be closed.
