### ISSUE TITLE
New stuns are buggy when buckled to vehicles

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#41622]
Movement restricting stuns such as Immobilize() and Knockdown() allow you to keep moving as normal while buckled to a vehicle (I guess it's debatable whether this makes sense or not)

Item usage restricting stuns such as Stun() and Paralyze() will unbuckle you from the vehicle if you try to move, otherwise you will stay buckled

@kevinz000

**Comment by kriskog** [comment]
This has been fixed

**Comment by Mickyan** [comment]
Don't know how you got that impression but this isn't fixed

**Comment by kriskog** [comment]
I made some flawed assumptions of what kind of thing were vehicles. Reproduced, still a thing. Tested with wheelchair.
