### ISSUE TITLE
Chemical emergency showers aren't in the chemistry room on Metastation

### ISSUE THREAD

**Issue by MortimerMcMire** [tgstation/tgstation#41630]
## Reproduction: Start a fire in chemistry, attempt to run out of the room and be stopped by the fire doors. You shouldn't have to leave the room to be put out, and if the fire doors close you're screwed. Real life chemistry labs work this way and are mandated to have chemical showers within about 10 feet of a chemical hood.

**Comment by Nickkoranda** [comment]
The shower is right outside of chemistry

**Comment by MortimerMcMire** [comment]
Yep, and if something catches fire and triggers the fire doors it may as well be on the moon.

**Comment by Nickkoranda** [comment]
The fire alarm is inside of chemistry, deactivate it and open the door to the shower

**Comment by MortimerMcMire** [comment]
That's tough when you're on fire and every second counts

**Comment by Barhandar** [comment]
Real life chemistry labs are optimized to preserve life, not to be metal deathtraps like SS13 is. Git gud, grab a crowbar ahead of time.

Or, you know, use the extinguisher.

**Comment by MortimerMcMire** [comment]
why even have a chemical shower if the point is to make it hard to use? lol cmon folks

**Comment by Barhandar** [comment]
because it's not a chemical shower lol, it's just an emergency shower for anything, like plasmemes

**Comment by 81Denton** [comment]
It's a deathtrap masquerading as a space station, not an OSHA compliant workplace
