### ISSUE TITLE
Revenants can disable internals

### ISSUE THREAD

**Issue by Names-Are-Hard** [tgstation/tgstation#41639]
## Round ID:
Don't really remember because the round died before I could check

## Testmerges:

#41099: '[READY]New Map: Donutstation V.5 (GOLD) (Platinum Hits)' by MMMiracles at commit 615d6321f8
#40995: '[READY][VERYREADY][WILLSUCKDICKFORAMERGE] Adds a new race: Ethereal (also adds wrappers for nutrition adjustment)' by Qustinnus at commit 3329ce4e09

## Reproduction:
Be a revenant, drag click someone's sprite onto your own, click disable internals.

**Comment by nicbn** [comment]
Revenants can also take items out of pockets and remove embedded objects.
