### ISSUE TITLE
plasma flood hallucinations are too common

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#41641]
half the hallucinations i got were plasma flood, tbh the whole hallucinations from sm exploding should be toned down they get boring and stale really quick

**Comment by Cyprex** [comment]
The bigger issue I have with it is that the fake plasma is in the wrong layer, and prevents clicking stuff under it, like machines.

**Comment by improvedname** [comment]
Its the best hallucination

**Comment by XDTM** [comment]
by the way, layers aside, does it look realistic or does it need adjusting?

**Comment by Cyprex** [comment]
It does seem a bit quick, but I've gotten rather used to the hallucinations.

**Comment by kriskog** [comment]
Rng be like that some times. There seems to be a decent spread currently.
