### ISSUE TITLE
Toxins chamber fails to ignite anything with igniters.

### ISSUE THREAD

**Issue by Peeping-Peacock** [tgstation/tgstation#41647]
Round ID: 97518

Reproduction:

Put 100% o2 or anything else that would burn and hit the switch to flicker the igniters. Nothing happens.

People have taken to throwing welders in there or messing with the temps of gases to get a flame going.

**Comment by Tlaltecuhtli** [comment]
igniter change caused this because we had to keep the furfag shitcode about igniters heating up shit that broke everything and keep breaking stuff, just copypaste the delta floor igniters on all maps and remove the old igniter system that doesnt work anymore

**Comment by Barhandar** [comment]
Or revert the idiotic "hotspot_expose heats air" change.

**Comment by Cyprex** [comment]
Pure oxygen won't burn without something to burn, like plasma or tritium. I have not had any issues with ignition in the atmospherics incinerator.

**Comment by Barhandar** [comment]
>also pure oxygen should absolutely burn on its own

lol

**Comment by Peeping-Peacock** [comment]
> 
> 
> > also pure oxygen should absolutely burn on its own
> 
> lol

A quick google search later and I'm shown wrong. At least I learned something.

**Comment by HydroFloric** [comment]
Toxins should just get the chadder atmos igniter tbh.
