### ISSUE TITLE
Holy melons are too OP against wiz and cult

### ISSUE THREAD

**Issue by Eskjjlj** [tgstation/tgstation#41649]
It take less than 8 minutes to mass produce holy melons and they make all wizard and cult spells useless.
The best strategy at this point is to use your spells to get guns and other sec weapons to get the job done since using spells doesn't work.

What's the point of giving those antags spells then? Just go gun cult or gun wizard no need for ineffective trash spells lmao

**Comment by Therapist1** [comment]
i ded, also just print a bible, same protection.

**Comment by Eskjjlj** [comment]
the bible only has holy while the melon has both holy and anti magic

**Comment by Eskjjlj** [comment]
null rods and holy melons completely nullify all spells. The thing is you can make 5000 holy melons but there is only one null rod.

**Comment by Tlaltecuhtli** [comment]
just burn down botany lol

**Comment by ATH1909** [comment]
> This sounds like an awful idea to remove anti magic when I remember all the dumb shit that wizards have done to become absurdly op.
> 
> As far as I know, nothing on the station has anti magic. If the null rod does then it's complete shit at anti magic from what I've seen. If the holymelons have less or the same amount of anti-magic as the null rod then it seems like all is fine.

Make sure that you keep your null rod on your person but outside of a container- it won't work while in your backpack, but it WILL work while in your pocket.

**Comment by Potato-Masher** [comment]
>Make sure that you keep your null rod on your person but outside of a container- it won't work while in your backpack, but it WILL work while in your pocket.

Huh. That sounds like a bug to me, because afaik holy melons can be stuffed in your bag and still work.

**Comment by XDTM** [comment]
I'm surprised it took all this time for someone to notice this

Though them working from inside backpacks was unintended, they should only work in hand

**Comment by XDTM** [comment]
i meant for melons specifically; they were initially meant to be a meme spell resistance thing and not a serious strategy (hence my comment about cultists wrestling the melon out of someone clutching it)

**Comment by RobustAndrun** [comment]
I HAVE NO ROBUST AND I MUST NERF

**Comment by adamkad1** [comment]
Congratz, you made wizard completly uncounterable HOPE YOUR HAPPY WITH YOURSELF COZ I WANNA END YOU

**Comment by WaterStBlues** [comment]
Sep chems are gone and hypo prickles are shit now so don't y'all date change holy melons more

**Comment by nemvar** [comment]
This is not the correct place for this kind of discussion.
