### ISSUE TITLE
Proto Kinetic Crushers can delay attacks basically infinitely

### ISSUE THREAD

**Issue by Whoneedspacee** [tgstation/tgstation#41655]
## Reproduction:

https://github.com/tgstation/tgstation/blob/2e227d11ee7b375bba8abb023e4aa8fc89d4f23a/code/modules/mining/equipment/kinetic_crusher.dm#L236

This whole section should be setting ranged_cooldown not ranged_cooldown_time. It's setting the recovery cooldown time for some mobs to ridiculous amounts. For example.

https://github.com/tgstation/tgstation/blob/17dfb07f99612b6d7c92d928ec22694ef20eb328/code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm#L108

Literally just hit anything with the crusher with a watcher wing and it will do this. Except certain mobs that don't use ranged_cooldown_time like the colossus. Every other megafauna it just stops their attacks for minutes though.

**Comment by k-k-karma** [comment]
wow mining is a powergamer's  wet dream you're saying?

**Comment by Whoneedspacee** [comment]
No I’m saying that instead of increasing the current cooldown to the next attack, the crusher is increasing a variable that sets the cooldown of the attacks, and sets it to world.time. So the megafauna instead of adding 0.5 seconds to its cooldown, now has to wait world.time between attacks essentially which if you’re 5 minutes into the round then it won’t attack for 5 minutes.

**Comment by Barhandar** [comment]
Has already been discussed and this is the end result of nerf PRs. Also, aren't you banned on servers?

**Comment by Whoneedspacee** [comment]
It’s like barhander didn’t even read, this is a bug not any sort of buffed or nerfed shit. Also someone probably didn’t test this at all which is how this happened.

**Comment by ExcessiveUseOfCobblestone** [comment]
@ChangelingRain

**Comment by ExcessiveUseOfCobblestone** [comment]
@Barhandar this is not intended and you can view the original PR to see that the end result was intended to be you're not even suppose to get close to chain stunning. Can you point me to the discussion where this is supposedly intended?

#35588

#41132 was closed because it wasn't even a fix if you're getting information from there (if you did props to you, I couldn't get pass the pissing match)
