### ISSUE TITLE
Some issues with the E.X.P.E.R.I.M.E.N.T.O.R.

### ISSUE THREAD

**Issue by Isy232** [tgstation/tgstation#41658]
Server: Which server were you playing on? 
Basil however I believe it affects them all.

Revision: What revision was the server running? Type 'show-server-revision' ingame to find out.
Local commit: 31fa2a0bb5b11ec60275ebbb259253c9863ce3da
Server tools version: /tg/station 13 Server v3.2.5.1

Problem Description: What is the problem?
The E.X.P.E.R.I.M.E.N.T.O.R machine only sometimes seems to work with items. For example, if you put an RCD in the machine on the function irradiate, it will duplicate. However, sometimes it will never duplicate it and instead give failure messages. The way to fix this is to take the machine apart and put it back together again until it starts working.

What did you expect to happen: Why do you think this is a bug?
I think this is a bug because the same machine with the same tier parts either does not work or works which can be altered by disassembling and resembling the machine. I would expect a machine with the same tier parts to function to function the same as another of that same machine of the same tier parts.

What happened instead: How is what happened different from what you expected?
The E.X.P.E.R.I.M.E.N.T.O.R requires to be dissembled and resembled to work oftenly. I would expect the machine to function the same if it was of the same type with the same parts.

Why is this bad/What are the consequences: Why do you think this is an important issue?
I think it is mostly the reason nobody uses the E.X.P.E.R.I.M.E.N.T.O.R in most round. I have had to take around 20 tries sometimes to get it to duplicate RCD's.

Steps to reproduce the problem: The most important section. Review everything you did leading up to causing the issue.
1: Get an RCD (empty RCD is fine).
2: Go to the E.X.P.E.R.I.M.E.N.T.O.R and sync it to the nearest R&D console.
3: Insert the RCD and start spamming irradiate, either it will duplicate it or never will.
4: Dissemble and reassemble the machine until you get it to work or not work, whichever you are trying for.

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Anything else you can tell us.
This seems to have affected every round I have played and used the E.X.P.E.R.I.M.E.N.T.O.R. Sometimes you are lucky and the one at round start works, often it does not. I do not think the gamemode matters as the E.X.P.E.R.I.M.E.N.T.O.R has been doing this on every round I have used it.

**Comment by kingoftheautism** [comment]
experimentor always was a bit shit which no one used

**Comment by Isy232** [comment]
Its not really all that shit when it works, you can get items otherwise impossible to get, like void cores.

**Comment by imsxz** [comment]
it dupes it by itempath too, so if you get an rcd from engi vendor(starts fully charged) it will dupe it fully charged, as opposed to being empty from duping autolathe'd RCD's.  Duping only works on "critical items", which is a decent list of stuff, but not universal.

**Comment by Isy232** [comment]
Duping RCD's is easy and if you setup a recycler you can easily get >500 sheets of metal in 10 minutes. Anyways, thanks for telling me how it actually works or is intended to, I will check it out.

**Comment by nicbn** [comment]
Not a bug

**Comment by davethwave** [comment]
I can imagine it now, dupe a bunch of syndi pda's, hand a bunch over to some greifers, watch the chaos. Well that or hand a syndi pda to sec with a whole lot of tc in it and see what happens.

**Comment by AlexTheSysop42** [comment]
Those can't be duped, fortunately

**Comment by AlexTheSysop42** [comment]
@ShizCalev this isn't a bug and >issuecount
