### ISSUE TITLE
Slot machines only take coins.

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#41652]
title, doesn't take holochips and space cash, only coins.

**Comment by nicbn** [comment]
Working as intended
As IRL, retro machines won't accept credit cards and *almost* no machine at all will accept bills

**Comment by Time-Green** [comment]
we need to be able to gamble all our money away

**Comment by Potato-Masher** [comment]
This is why we need **SPACE** ATMs and not holochips.

**Comment by kriskog** [comment]
fixed in #42774
