### ISSUE TITLE
Nuke shows up as auth even when not authed

### ISSUE THREAD

**Issue by redmoogle** [tgstation/tgstation#41667]
![image](https://user-images.githubusercontent.com/20369082/48973817-6a68cd00-f016-11e8-8bee-b497ad8381c3.png)

The code for the nuke is not put in and shows authed

**Comment by AlexTheSysop42** [comment]
I think it means it's asking for authentication

**Comment by Anonmare** [comment]
It's asking for authentication

**Comment by SpaceManiac** [comment]
at worst, slightly confusing messaging on what is in-universe a terse and technical interface
