### ISSUE TITLE
Mining and tech issues

### ISSUE THREAD

**Issue by venomsnak** [tgstation/tgstation#41677]
-Mining kinetic accelerator sprite glitches with attached knife and seclite after seclite is turned on
-Eating leafless mushrooms show that you've smoked in moodlets
-Techfabs for each department have redundant tabs they never will use since a janitor will never get to use mining tech stuff in a service lathe.
-Lantern wisp sprite will get detached from user when holding spectral blade

**Comment by ExcessiveUseOfCobblestone** [comment]
leafless has nicotine I think

**Comment by kriskog** [comment]
First three are fixed, intended and not a bug. Last has its own issue now.
