### ISSUE TITLE
fake pipe in pubby sci toxin room

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#41675]
the output toxin pipe in the wall isnt real

97619

**Comment by 81Denton** [comment]
Which one of these?

![weed](https://user-images.githubusercontent.com/32391752/48983631-a886ef00-f0f1-11e8-851b-20f85439c69a.PNG)

**Comment by Tlaltecuhtli** [comment]
http://take.ms/dT7Wm
i wasnt unable to wrench unwrench it ( it was hitting instead) and the air wasnt moving trough it i had to break it with a welder and put a new pipe on the wall

**Comment by nicbn** [comment]
It is a real pipe
The pipenet "clogging" and making the pipes unable to be unwrenched is an old bug

**Comment by Potato-Masher** [comment]
This happened to me and another scientist a while back, basically the same thing that happened here.

**Comment by nicbn** [comment]
@SpaceManiac This is not a map issue, there's nothing wrong with the specific pipe, it's a bug that can happen with seemingly any pipenet

**Comment by 81Denton** [comment]
Like this one? #36642

**Comment by ShizCalev** [comment]
Duplicate of #36642
