### ISSUE TITLE
[:nut:station] toxin room problems:

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#41685]
the pipes need to be hidden or whatever  var makes them not care if you build more pipes on top of em
the burn room isnt standarized like every other map

**Comment by MMMiracles** [comment]
what the fuck is nut station

**Comment by nicbn** [comment]
Rooms not being stardanzied is not an issue
There's no var that makes you able to build pipes one over another

**Comment by SpaceManiac** [comment]
#41099

**Comment by AlexTheSysop42** [comment]
You need to do stuff with layering to do that
