### ISSUE TITLE
Holy Water slips, despite multiple places saying it does not.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#41691]
Issue reported from  Round ID: 97652 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Janitor experience ruined.

![dreamseeker_2018-11-26_01-06-57](https://user-images.githubusercontent.com/33107541/48996000-573e2600-f118-11e8-9664-d170be438991.png)
![dreamseeker_2018-11-26_01-06-54](https://user-images.githubusercontent.com/33107541/48996004-5c9b7080-f118-11e8-82af-47e0d0ad7fe3.png)
![dreamseeker_2018-11-26_01-07-07](https://user-images.githubusercontent.com/33107541/48996010-6329e800-f118-11e8-9067-d3e8c0d73b08.png)
![dreamseeker_2018-11-26_01-07-25](https://user-images.githubusercontent.com/33107541/48996029-72109a80-f118-11e8-9e4a-2e69903e84fb.png)
![dreamseeker_2018-11-26_01-07-33](https://user-images.githubusercontent.com/33107541/48996035-73da5e00-f118-11e8-9fd3-9bb7cc121708.png)
![dreamseeker_2018-11-26_01-07-42](https://user-images.githubusercontent.com/33107541/48996039-76d54e80-f118-11e8-907f-54de0993ab14.png)
![dreamseeker_2018-11-26_01-07-47](https://user-images.githubusercontent.com/33107541/48996041-79d03f00-f118-11e8-88f7-ae3df5d2d17b.png)
![dreamseeker_2018-11-26_01-07-53](https://user-images.githubusercontent.com/33107541/48996043-7ccb2f80-f118-11e8-8d3c-d06b2290d213.png)
![dreamseeker_2018-11-26_01-07-56](https://user-images.githubusercontent.com/33107541/48996045-7f2d8980-f118-11e8-9793-4debe13ba7b1.png)

**Comment by Tlaltecuhtli** [comment]
intended

**Comment by k-k-karma** [comment]
1) holy water used to not slip
2) sure it's holy water?

**Comment by Therapist1** [comment]
mop with vodka like tru slav, no slips and taking break easy

**Comment by nicbn** [comment]
Adding holy water to a water tank won't make all the water into holy water
You have to call chaplain to bless the tank it with a bible

**Comment by Barhandar** [comment]
Read better, he's not adding holy water to tank, he's taking water from tank with drinking glass to prove it's holy water. OP, next time: science goggles let you see specific reagents in containers.

**Comment by ExcessiveUseOfCobblestone** [comment]
> is there anywhere in-game that indicates holy water should not slip, or is it just the wiki?

**Comment by Potato-Masher** [comment]
https://tgstation13.org/wiki/Janitor#Cleaning_Without_Being_Lynched
![firefox_2018-11-27_17-49-21](https://user-images.githubusercontent.com/33107541/49116849-d2185580-f26c-11e8-884a-582365a2978a.png)
(The tip featured was added by Jordie0608 back in 2014; its been there ever since.)

http://www.ss13.eu/wiki/index.php/Guide_to_Awesome_Miscellaneous_Stuff#Chaplain
![firefox_2018-11-27_17-53-40](https://user-images.githubusercontent.com/33107541/49117007-6682b800-f26d-11e8-9e61-9e723cd503c9.png)
(Most recent revision on this page was Feb 2015, tip dates to late August 2013)

Only two places I can find as of now, I swear there was at least one other that mentioned this. Does anybody recall this being a feature at all? I swear some people other than me have mentioned this at one point in OOC or something.

**Comment by ExcessiveUseOfCobblestone** [comment]
if it's only with the wiki it seems sensible to just... well... edit the wiki?

**Comment by ExcessiveUseOfCobblestone** [comment]
Also it was slippery 4 years ago

https://github.com/tgstation/tgstation/blame/77febafb52f2cd46d8a93a541efdd97c3e53e93b/code/modules/reagents/Chemistry-Reagents/Other-Reagents.dm#L122

**Comment by Potato-Masher** [comment]
Alright, I'll just close this issue then and fix the wiki
