### ISSUE TITLE
Those without legs can't do certain actions, even when strapped to a chair

### ISSUE THREAD

**Issue by plapatin** [tgstation/tgstation#41703]
Issue reported from  Round ID: 97693 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Those without legs cannot do specific actions, even when buckled to chairs. Actions include, but are not limited to:
Using PDAs
Operating holopads
Opening/unlocking lockers
Pulling things
Stripping others, or removing handcuffs
Using specific consoles (things like comms console and gulag console)

**Comment by Jalleo** [comment]
Hinders improvement. I would suggest.

**Comment by CRTXBacon** [comment]
Just to add on, seemingly all alt-click functions are impossible to do

**Comment by MegaEmpirical** [comment]
Yeah, can't even remove the ID from the PDA.
