### ISSUE TITLE
Emergency reset board doesnt work on ai shells.

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#41702]
When done it leaves you with an empty robot that can't be used by anything and just sits there as decoration. This issue is probably going to be ignored like all of my ones about how fucked ai cameras are though so whatever.

**Comment by GunHog** [comment]
It does work, just slot the B.O.R.I.S. upgrade back into the body, or you can just deconstruct it if you want to insert a brain.

**Comment by Anonmare** [comment]
The BORIS module is treated as an upgrade so it gets spat out on a reset. Just get the roboticist to open the panel and slot it back in and it'll work again.

**Comment by ExcessiveUseOfCobblestone** [comment]
stop blaming others for not fixing your issues on an open source that you can equally contribute to.

**Comment by Dorsisdwarf** [comment]
Looks like this isnt actually an issue, just a misunderstanding of how BORIS shells work
