### ISSUE TITLE
PKA gets increased cooldown from an ebow in backpack

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#41728]
## Round ID: 97809

Same as having two PKA's

**Comment by ma44** [comment]
>tfw energy crossbows are still a child of PKAs

**Comment by ExcessiveUseOfCobblestone** [comment]
I have a fix for this coming soon

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/commit/325cd51508186b05622b35ed4583362325e46ebd

I accidentally automerged this hehe but if it needs to go to the PR process ill just make an actual PR
