### ISSUE TITLE
Teleporting doesn't work

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#41723]
Hand teles and wizard teleports seem to be bugging out

**Comment by KangTut** [comment]
Yeah the wizard can't use his scroll to teleport anywhere at the moment. Just pops smoke and says something is disrupting the magic.

**Comment by XDTM** [comment]
something went wrong with #41371

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/master/code/datums/helper_datums/teleport.dm#L61-L62

It will always successfully send the signal so the proc will always fail?

**Comment by XDTM** [comment]
i thought about that, but warp whistles apparently work and they use the same channel as teleportation scrolls, so i'm a bit stumped until i can test it by myself

**Comment by Time-Green** [comment]
May have something to do with teleportation being cast on the wizard shuttle wich has no_teleport enabled

**Comment by XDTM** [comment]
That would be caused by #41694 then good catch

**Comment by XDTM** [comment]
Well, that and the fact that it's become a do_teleport instead of a forceMove. Might as well remove the noteleport at that point though (and keep in on the rest of the zlevel), since the wizard is supposed to teleport there in the first place

**Comment by Time-Green** [comment]
That may cause issues with wizards returning to their lair to change their loadout, or players going there with stolen scrolls. Wheter thats actually a problem or not is not up to me

**Comment by ExcessiveUseOfCobblestone** [comment]
You can't tele back to wizard den since it's not a station Z anyways

**Comment by carshalash** [comment]
AI core cant be pushed through teleporters anymore either, its pretty fucking annoying.

**Comment by YakumoChen** [comment]
Was this fixed? I haven't had issues as often now.

**Comment by optimumtact** [comment]
believe to be fixed
