### ISSUE TITLE
Pacifists can use Krav Maga/martial arts to harm people

### ISSUE THREAD

**Issue by snekibreki** [tgstation/tgstation#41735]
## Round ID: 
97834

## Testmerges: 
https://www.github.com/tgstation/tgstation/pull/41099 DonutStation v5.0

## Reproduction: 
Equip Krav Maga gloves as a player mob with the pacifist trait on. Switch your intent to disarm and prepare a special attack before attacking someone else. The attack will deal brute damage and, given enough stacks, will allow you to kill someone.

**Comment by XDTM** [comment]
martial artists retain inner peace while fighting

**Comment by nemvar** [comment]
Closing this in favour of #42341
