### ISSUE TITLE
Etherals can create duplicate lightbulbs

### ISSUE THREAD

**Issue by Kartograaf** [tgstation/tgstation#41737]
Issue reported from  Round ID: 97842 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Etherals that channel energy from lights multiple times and then move away create additional light bulbs.

Recreation: 
start multiple channels on a single light
move away before any of them complete
you are left with the original light in your hands and multiple copies under the light fixture

The dupes can't be broken and using them on an empty socket causes them to disappear.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Qustinnus

**Comment by ExcessiveUseOfCobblestone** [comment]
Doubleloc memes....

**Comment by kriskog** [comment]
Cant reproduce
