### ISSUE TITLE
Camera static not clearing when new cameras are made

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#41747]
ROUND ID: 97880

![image](https://user-images.githubusercontent.com/12382984/49324280-99090b00-f522-11e8-88e3-fbe8ebb7392d.png)

**Comment by Anonmare** [comment]
There doesn't appear to be a rhyme or reason as to what static is cleared and what is not.

**Comment by Sealed101** [comment]
got fixed at _some point_ (plane cube most likely or its followups like https://github.com/tgstation/tgstation/pull/70235)
