### ISSUE TITLE
Issues with the E.X.P.E.R.I.M.E.N.T.O.R

### ISSUE THREAD

**Issue by Isy232** [tgstation/tgstation#41755]
I know I made a report on this before, but I was told that the functions are randomized each time the machine was made. So one time irradiate might duplicate an RCD while another time it may not do anything. However, after multiple times trying, this is untrue. Between me and another who have been over a few rounds trying to figure out how it works, we have found that the other functions still do nothing. I personally per an RCD in, and tried 20 times on each function with the EXPERIMENTOR having tier 4 parts. I did not get a single positive outcome. If someone could give a full explanation of how the machine definitely works or the code could be altered to make it easier to understand, it would be much appreciated.

**Comment by Tlaltecuhtli** [comment]
higher tier parts are worse as they lower your crit chance
how it works: when you build it chooses 1 random experiment that will work with 1 random critical item so if you want it to work with irradiate you can either cycle the critical items until you get it to work or rebuild every time it gives you a fail message

**Comment by Isy232** [comment]
Yes, but that does not work. I cannot get a positive output such as RCD's duping on anything but irradiate.

**Comment by Tlaltecuhtli** [comment]
rcd duping is an irradiate effect

**Comment by Tlaltecuhtli** [comment]
here i make u a picture to understand experimentor code
http://take.ms/HmfvS
