### ISSUE TITLE
cult floor speeds up narsie summon rune

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#41761]
which means its almost impossible to stop it as you have only 30s to physically move there

**Comment by evsey9** [comment]
That's probably intended

**Comment by ExcessiveUseOfCobblestone** [comment]
dookie feature

**Comment by Tlaltecuhtli** [comment]
its not a feature: the whole point of the summon rune is it takes long,  having a crappy pylon nearby makes it super ez to summon without any effort

**Comment by YakumoChen** [comment]
Yeah this shouldn't be intended for narsie rune in specific, if cult is summoning there's no need for stealth, given the global annoucement.

**Comment by kriskog** [comment]
fixed in #44495
