### ISSUE TITLE
You can feed infinite plasma into a plasma cutter even when it's full

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#41776]
## Reproduction:
1. Whip out a plasma cutter. Any charge works fine, can be either type as well.
2. Slam some plasma in there. Ore or mineral sheets, doesn't matter.
3. You will notice that you can do it even when it's at 100%, essentially creating a black hole of plasma and necessitating careful examination to avoid wasting it.

Ideally, the plasma cutter wouldn't let you stick in any extra plasma when it's full.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/83364d1e620637e8c7f7dd900a9d3eb194ae7b7f/code/modules/projectiles/guns/energy/special.dm#L147

```suggestion
if(istype(I, /obj/item/stack/sheet/mineral/plasma) && (cell.charge < cell.maxcharge))

**Comment by subject217** [comment]
>Good first issue

Cobblestone, this is far from my first issue...
