### ISSUE TITLE
Hypnoflash causes Curse of Mundanity status effect boxes to appear

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#41805]
Round ID: 98086

1) Hypnoflash someone who isn't hynotise vulnerable. They'll get the default "!" Curse of Mundanity status effect.

2) Hypnoflash someone who IS hypnotise vulnerable. Same Curse of Mundanity status effect popup box.

Not sure if you intended for status effect popup boxes or no, @XDTM

**Comment by XDTM** [comment]
oh goddammit i forgot to add the status effect popup alert again

**Comment by XDTM** [comment]
both for the pacification and the trance debuffs i suppose
