### ISSUE TITLE
Toxins igniters are still broken.

### ISSUE THREAD

**Issue by Isy232** [tgstation/tgstation#41815]
I heard the igniters finally got fixed, but this does not seem to be the case. The wall igniters in the toxins burn chamber still do not function. They make flames which move around the chamber more but they never stay to start a fire. I think the solution is that the wall igniters need to keep the tile they are igniting under constant ignition. The floor igniters work, or used to work unless they have been changed.

Edit: The easiest way to get toxins to work is to put candles in or get a lit welder in. Both of those objects work.

**Comment by ExcessiveUseOfCobblestone** [comment]
They were reverted to how they were before but how they were before did not accommodate for that major plasma change (the epic define one)

**Comment by 81Denton** [comment]
Would anything speak against adjusting the (now fixed) atmos values so that they result in the same effects the game had for 5+ years?

**Comment by ExcessiveUseOfCobblestone** [comment]
You mean reverting the define?

**Comment by 81Denton** [comment]
Not reverting it, just adjusting the values so the results are the same as before.

**Comment by Isy232** [comment]
Currently, I just toss candles from the chapel into the burn chamber, they work well so making the wall igniters do what candles do may work.

**Comment by MACIEKBAKI** [comment]
Or you know, replace the igniters in toxins with the one igniter that the turbine has.

**Comment by xeroxemnas** [comment]
Yeah this is still broken. Also, the turbine igniter doesn't seem to work either when it comes to starting fires. I usually have to throw a lit welder in which sucks since there's no atmosphere in the damn chamber.

**Comment by optimumtact** [comment]
is it really this hard to edit a ignitre object to make it hotter,s mh
