### ISSUE TITLE
Unable to reload improvied pneumatic cannons

### ISSUE THREAD

**Issue by Laggystein** [tgstation/tgstation#41810]
Crafted one, load two objects, attached a full sized 02 tank from the EVA dispenser. It fired the two objects just fine, but after that was unable to reload it. Attempted to reload by holding cannon in one hand, object in other. Clicked cannon with held object active, nothing occured. No messages were given.

**Comment by delaron** [comment]
You have to remove the old o2 tank with a screwdriver or maybe a wrench I think.

**Comment by Laggystein** [comment]
I attempted to use both on it, got nothing

**Comment by HomocidlePancakes** [comment]
Help intent you dumdum

**Comment by Laggystein** [comment]
I cant recall what intent i was using but trying this again with help intent let me load new things
