### ISSUE TITLE
Brain "dupe" from MMI using recycler

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#41824]
## Reproduction:
1. Join as Roboticist, ask some greytide for experimental borgofication. Do surgery.
2. Insert brain in MMI
3. Go to recycler.
4. Throw MMI with brain in recycler.
5. Got MMI with with brain (it looks like it) and normal brain of greytide.
5.1 Repeating step 4 don't dupe brain again.
5.2 Removing brain from MMI teleport brain in to your hand from floor.
5.3 "Soul" of greytide appears in brain and not in MMI (that looks like MMI with brain) and can talk and beep.
6. Insert MMI that (looks like with brain) in to a borg endoskeleton.
7. Borg happy roll out. You got greytide brain on table and it says it has no soul in it and you cant put it MMI.

**Comment by timothymtorres** [comment]
This appears to have been fixed with #48711
