### ISSUE TITLE
Lights are blowing out for no reason

### ISSUE THREAD

**Issue by elyina** [tgstation/tgstation#41844]
Keep seeing this on bagil, asked around and apparently I'm not just going crazy. Lights are breaking for seemingly no reason. It's incredibly annoying.

**Comment by WarRage333** [comment]
https://github.com/tgstation/tgstation/pull/41660

**Comment by elyina** [comment]
Since that bit is intended (even though I disagree with it and find it very annoying personally) I removed that from the report. 
@WarRage333 this isn't about the round start broken lights, I know about those and they've been around for years.  It's about lights just randomly blowing on their own in the middle of the round.  I've seen it happening myself and asked around to make sure I wasn't just seeing things.

**Comment by elyina** [comment]
Ok turns out that's intended as well it seems. I still think the sparking thing is pretty dumb/annoying but that's not a battle for a bug report

**Comment by subject217** [comment]
mfw lights randomly breaking predates the git history of /tg/ station with a dead end 404 link to google code from 8 years ago and elyina is trying to claim something has changed 

pure confirmation bias from broken lights being more obvious
