### ISSUE TITLE
Healing Sprays go through hardsuits

### ISSUE THREAD

**Issue by GhostEcho** [tgstation/tgstation#41859]
Yeah this really shouldn't be a thing, all things considered

**Comment by Vidiveni** [comment]
Intended. Medical sprays work same way as patches.

**Comment by Tlaltecuhtli** [comment]
intended

**Comment by Cyprex** [comment]
This issue can be closed.

**Comment by nicbn** [comment]
Actually that's a consistencty issue

**Comment by YakumoChen** [comment]
but it's not, since they're identical to patches.

**Comment by Cyprex** [comment]
Burn/Bruise packs need exposure, patches+and sprays always work. Can we not have a million issues open labeled "consistency issue"? This is just basic game mechanics.

**Comment by ATH1909** [comment]
Yeah, but it still doesn't make sense.

**Comment by Cyprex** [comment]
A lot of things in this and other games aren't realistic/don't make sense. Deal with it.

**Comment by nicbn** [comment]
It's a consistency issue with both patches and sprays. There are other medical items that require exposed flesh. It's not basic game mechanics, someone forgot to add a check probably.

**Comment by Cyprex** [comment]
No, not requiring exposed flesh is intended. How else would you apply medical items to people in hardsuits?

**Comment by nicbn** [comment]
Just take the hardsuit off wtf

**Comment by YakumoChen** [comment]
you apply it through a port obviously

**Comment by kriskog** [comment]
Same as patches, intended.
