### ISSUE TITLE
Drowsiness no longer causes slowdown

### ISSUE THREAD

**Issue by Vidiveni** [tgstation/tgstation#41875]
## Round ID:
Terry 2018-12-09 - Round ID only said "0" due to some bug. 

## Testmerges:

Don't know, but " Movement changes are coming into effect.  " are on. 

## Reproduction:
1. Drink haloperidol. 
2. Get foggy overlay but no speed reduction. Run off at full speed. 

Expected result: Instant slowdown. 

You will still fall asleep from drowsiness, but no slowdown.

**Comment by kriskog** [comment]
There is nothing in code that indicates drowsiness should slowdown. If it used to, it's probably been removed intentionally.
