### ISSUE TITLE
Teleporter Troubles

### ISSUE THREAD

**Issue by KangTut** [tgstation/tgstation#41871]
Issue reported from  Round ID: 98314 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Sorry if this is a dupe but none of the other issues seems to address these specific problems I've noticed in the last few days.

The teleporter station and hand teleporter have broken functions at the moment - the station more so than the hand tele. Right now you can't even use the tele station but it can still turn you into a fly and the hand tele's portals don't work unless you click them. Walking into portals just causes sparks to fly and nothing more.

**Comment by YakumoChen** [comment]
#41723

**Comment by kriskog** [comment]
Also some teleportation is blocked by bags of holding. I had to strip people before teleporting them with my support holoparasite yesterday.

**Comment by kingoftheautism** [comment]
Teleportation being messed up by BoHs is intended. They shouldn't block (at least how it was a while ago) tho

**Comment by Eskjjlj** [comment]
Cult TP runes are broken aswell. You can't use them to TP but you can use the TP spell to TP to them.

**Comment by optimumtact** [comment]
believe to be fixed
