### ISSUE TITLE
Admin-spawned puzzles display no icons

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#41872]
![image](https://user-images.githubusercontent.com/38788538/49697160-05d87100-fbc5-11e8-9bbf-13ace554e5f2.png)

**Comment by nicbn** [comment]
Steps to reproduce?
Did you (or the admin that spawned it) try to proc call update_icon?

**Comment by optimumtact** [comment]
no rounid, or steps to reproduce, closing
