### ISSUE TITLE
Ash Drake Arena can select inaccessible tiles as the safe tile

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#41887]
For example, if fighting the Ash Drake in the Heirophant Arena, the safe zone for the arena attack can be on one of the indestructible pillars.

**Comment by py01** [comment]
It appears that only one safe tile is ever selected

**Comment by optimumtact** [comment]
@Whoneedspacee

**Comment by Whoneedspacee** [comment]
Yeah not really sure why I didn’t think of this in foresight from its inability to destroy indestructible turfs. Also I wasn’t pinged by you @ing me for some reason hm.

Should be an easy fix.
