### ISSUE TITLE
Golems who bodyswap are counted as dead for Valentine's purposes (maybe others)

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#41889]
Issue reported from  Round ID: 98386 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Played a round as a Free Golem, and a radmin pressed the Valentine's Day button. During the round, I swapped to another golem body, and at the end of the round the report told me I had been killed (and redtexted the person assigned as my Valentine).

It's fringe, but I feel as though things like this could end up applying elsewhere if they share checks. Maybe that's just being overly concerned, though.

**Comment by optimumtact** [comment]
pretty sure it tracks them by bodies, not by minds, so if you bodyswap and your original body dies I think it will redtext you.
