### ISSUE TITLE
Antimagic component on gem encrusted hardsuit prevents wizards who buy it from using magic

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#41898]
Issue reported from  Round ID: 98429 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Tin.

**Comment by coiax** [comment]
@XDTM

**Comment by XDTM** [comment]
working on it, i'll add the fix to #41739

**Comment by k-k-karma** [comment]
why does antimagic even block magic now? doesnt this fuck over chaplain spellbook too

**Comment by Metroidlover** [comment]
It 100% does, but people don't really care from what I've seen

**Comment by ATH1909** [comment]
> It 100% does, but people don't really care from what I've seen

Wait, this is the first I'm hearing of this... and as a chaplain main, *I* care (not that that counts for much, but still).

**Comment by XDTM** [comment]
Chaplains still have spellbooks?

**Comment by coiax** [comment]
@XDTM Metastation, book of smoke.

**Comment by XDTM** [comment]
Chaplains can still put the rod in their backpack to cast, and if they take a nodrop variant they just miss out on the free rounds tart spell that they have for some reason.
