### ISSUE TITLE
RnD Servers do not generate heat.

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#41901]
RnD Servers do not produce heat. Specifically, produce_heat is never called. RefreshParts() is also broken, in that it repeatedly lowers the heat generation every time its called.
https://github.com/tgstation/tgstation/blob/master/code/modules/research/server.dm#L31-L35

**Comment by RedFoxIV** [comment]
**delet this issue this instant**

**Comment by XDTM** [comment]
wasn't it removed due to the atmos processing cost?

**Comment by Borisvanmemes** [comment]
It was disabled afaik alongside T-comms servers not generating heat.

**Comment by Cyprex** [comment]
Fair enough, I'll close this in that case.

**Comment by ExcessiveUseOfCobblestone** [comment]
The proc shouldn't exist if it's not doing anything though.
