### ISSUE TITLE
Zombie antagonists appear dead in the Admin Check Antagonists panel

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#41911]
Issue reported from  Round ID: 98458 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Someone got a bottle of Romerol in a cult round, and one of the admins thought that the whole cult were dead, but it turned out they were fine, just zombies.

**Comment by XDTM** [comment]
The check_antagonist proc checks for (stat == DEAD), which isn't affected by fakedeath. What did the admin see exactly?

**Comment by kriskog** [comment]
Can't reproduce locally. Sure they weren't just temporarily dead?
