### ISSUE TITLE
AI pda messages not showing ai name

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#41934]
Recently been noticing from observing in dead chat and checking pda for ai names that it has just been showing "AI" and not the actual name of the ai. This is going to be kind of retarded for rounds where there are multiple ais on station.

**Comment by carshalash** [comment]
![image](https://user-images.githubusercontent.com/16896032/50198799-fa413300-0398-11e9-9ffe-481a81682651.png)
Well would ya look at that.

**Comment by ShizCalev** [comment]
Duplicate #42413
