### ISSUE TITLE
Many sources of stamina damage are now broken

### ISSUE THREAD

**Issue by Kierany9** [tgstation/tgstation#41942]
#39304 split stamina damage and regen to work on a limb by limb basis, giving each limb its own regen rate and making it so that you can only stun by dealing 100 stamina damage to the head and chest. However, this change also broke a lot of chemicals and other items that use the adjustStaminaLoss proc(which spreads stamina damage evenly across limbs, four of which no longer contribute to the stun) by effectively sextupling the stamina regeneration rate and tripling the required damage to stun. Using it to heal damage still works fine(unaffected limbs aren't healed) but its damaging capacity is completely gimped.

## Reproduction:

1. Use chemical that deals stamina or experience [one of the many other forms of stamina damage that uses adjustStaminaLoss](https://github.com/tgstation/tgstation/search?q=adjustStaminaLoss&unscoped_q=adjustStaminaLoss).
1. Watch it not work.

**Comment by timothymtorres** [comment]
This was fixed with #42941 and #43966
