### ISSUE TITLE
Got cloned as the secondary personality of a person with split personality

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#41941]
1) Janitor got defibbed, gets Split Personality (played by me).
2) We get killed in the kitchen.
3) When cloned, it notifies me that my body has been put into the cloner.
4) I get cloned with full control of the body.

**Comment by coiax** [comment]
@XDTM

**Comment by XDTM** [comment]
Feature?

**Comment by XDTM** [comment]
Although the trauma is supposed to put the original back in on death, ill have to recheck that

**Comment by Shadowflame909** [comment]
This sounds like an interesting potential feature.

One Personality dominated the other.

**Comment by k-k-karma** [comment]
intentional, you can clone the brain twice for both people.

**Comment by XDTM** [comment]
not intentional, but if you can indeed make two people out of two personalities i'm definitely supporting that

**Comment by kriskog** [comment]
Before prescanning was removed so might be irrelevant now, I prescanned while in control. We died while the other guy was in control, I was cloned by the autocloning, he was not.
