### ISSUE TITLE
changeling strained muscles bug

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#41943]
someone said that they were too lazy to make a github report themselves so this is second hand information. allegedly strained muscles for changeling is just a free infinte speedboost at the moment when you use it, probably related to #41942

**Comment by Borisvanmemes** [comment]
hi yes i also ran into this as a xenoling and forgot to report it, TL:DR you turn it on and then when you turn it back off it doesn't remove the speedboost and it also doesn't knock you down.
