### ISSUE TITLE
If you admin heal a golem, it shits out 2 adamantine resonators (its mutant organ x2)

### ISSUE THREAD

**Issue by Qustinnus** [tgstation/tgstation#41949]
## Reproduction:
1. Heal a golem
2. 2 adamantine resonators (A golem custom organ) will spawn below the golem. One of which is the one that was originally inside of the golem.
3. The golem will have a new resonator inside of him. (Which is a different one than before)

**Comment by Qustinnus** [comment]
addenum: they also shit out organs you give them on their mutant_organs list.

**Comment by coiax** [comment]
When you say heal, do you mean the Heal button on the Player Panel?

**Comment by Qustinnus** [comment]
see title

**Comment by Qustinnus** [comment]
@dragomagol can you tag / explain why you close issues? It's a bit unhelpful to just close them without explaining why.



This doesn't happen on latest anymore
