### ISSUE TITLE
Various SM/Atmos bugs.

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#41954]
## Round ID: 98565
BYOND Version: 512.1453
Server revision compiled on: 
Master commit: a00beb3f69d0a5118cd47f6bcf1cf13bb7b89bdb
Only donutstation was testmerged.

Everyone was getting irradiated like crazy: 
>23:25:11 [0x203e0dd] (172,154,2) || the foamed metal has become contaminated with enough radiation to contaminate other objects. || Source: the supermatter crystal || Strength: 4.60506e+007

https://tgstation13.org/parsed-logs/sybil/data/logs/2018/12/13/round-98565/radiation.html
Various runtimes, some of them atmos related: https://tgstation13.org/parsed-logs/sybil/data/logs/2018/12/13/2018-12-13.runtime.condensed.txt

The SM did not seem to delaminate either, even though adjacent tiles were exposed to space.
Full VV of the SM before roundend: http://paste.debian.net/plain/1055773

![](https://my.mixtape.moe/zkafgb.png)
![](https://my.mixtape.moe/qssbzr.png)

**Comment by Cyprex** [comment]
Another round, another broken SM. This time on the menu: No sabotage, massive gas production, and what looks like an integer overflow on rad output?
Round ID: 98995 [Logs](https://tgstation13.org/parsed-logs/terry/data/logs/2018/12/21/round-98995/)
In this particular round the SM wasn't set up properly, the gas input pump wasn't set up to my knowledge. This time the SM produced ridiculous amounts of gases (I saw 87k mol of plasma at one point, in a single tile mind you.). This created a very hot plasma fire, into the million kelvins, and pressures into the billions. Curiously enough, the EER(rads+power output) according to the SM monitoring console jumped between 0 and several huge negative values, possibly an integer overflow? Everything got irradiated to shit. I varedited the SM integrity from 8% to ~40% twice to investigate, the bugs happened before that, and didn't really seem to get worse, so that wasn't the cause. I do not believe any harmful gases were pumped inside, not that you can get 9*80k moles of plasma anyway(The huge tank in atmos contains ~70k moles per tile). An analyzer did not indicate fusion reactions taking place, and the gases inside the SM are all fire products, so I do not believe fusion reactions are responsible here.
VV copypaste at different times:
http://paste.debian.net/plain/1057023
http://paste.debian.net/plain/1057024
![](https://my.mixtape.moe/cwhnbf.png)
![](https://my.mixtape.moe/xdzmqu.png)
![](https://my.mixtape.moe/nxsgvk.png)

**Comment by Cyprex** [comment]
SM Power calculation is fundamentally broken. There are 2 lines of code assigning a power value, using max(formula, 0) to ensure that it's not negative, and then: 
	power -= ((power/500)**3) * powerloss_inhibitor
Gas and rad production then scale with power.
https://www.desmos.com/calculator/de7keoqr1n

**Comment by 4dplanner** [comment]
Is this still an issue post fires fix?

**Comment by Cyprex** [comment]
I believe most of the issues listed here where from the broken fires, but negative amounts of rads(i. e. radiation_pulse being called with negative intensity values) is still a thing at high SM power levels, and as far as I understand, that's not intended. I'll close this and open a new issue for that.
