### ISSUE TITLE
Brains of suicides can be put into mechs.

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#41950]
## Round ID:98564

You cannot put the brain of someone that suicided into a borg shell, but you can put them into mechs.

**Comment by kriskog** [comment]
We have had some changes to suicide flags, this may have been fixed.

**Comment by Cyprex** [comment]
I've just tested this with Denton, and this is still a thing.

**Comment by 81Denton** [comment]
Round ID 113525
