### ISSUE TITLE
When an expand module is removed from a cyborg they are smaller than when it was installed, can be repeated infinitely making it smaller each time

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#41964]
While there is already an open issue similar to this it doesn't go into the fact that you can literally be invisible. You can just expand a borg, reset it, then expand it over and over and it keeps getting smaller

![image](https://user-images.githubusercontent.com/222630/50240460-b7239780-0379-11e9-8ca4-53b272347072.png)

Issue reported from  Round ID: 98629 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

**Comment by GunHog** [comment]
Behold, the prototypes of what we now call "nanites"!

**Comment by ATH1909** [comment]
Introducing the adventures of Antborg, the smallest sapient robotic spy in the galaxy.
