### ISSUE TITLE
Liquid Dark Matter pulls ghosts

### ISSUE THREAD

**Issue by BebeYoshi** [tgstation/tgstation#41960]
## Reproduction:
1. Be a ghost.
2. Get near someone who is about to mix Liquid Dark Matter
3. Wait until they mix the Liquid Dark Matter
4. Enjoy being pulled by it as a ghost.

**Comment by GhostEcho** [comment]
That seems hilarious, lets keep it

**Comment by wesoda25** [comment]
I feel as if this is going to get closed for the same reason that my ‘admin thrown ghosts can move people/things’ was. Its an intended feature I guess.

**Comment by kriskog** [comment]
Still an issue
