### ISSUE TITLE
Falling onto space turf deals damage

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#41966]
If you fall down a Z level onto space (/turf/open/space), you will take damage as if you fell down onto a solid floor. Probably also applies to similar turfs.

Mckenzie Fields falls through the open space!x2
Mckenzie Fields crashes into space!
Mckenzie Fields crashes into space with a sickening noise!

**Comment by Razharas** [comment]
The problem is the fact that you fall into space in the first place
Station creates artificial gravity to its lowest floor, you shouldnt even fall below that
