### ISSUE TITLE
Most antag statuses are not showing up on the adminhelp ? button

### ISSUE THREAD

**Issue by elyina** [tgstation/tgstation#41979]
When an adminhelp appears or someones name is mentioned, there will be a ? button you can press to quickly display that persons status, including their antagonist status. Currently is it not correctly displaying most antag statuses. This resulted in a rather annoying situation in which I used this button to check the status of someone who asked if it was OK for them to ghost to which I said yes as I saw no antagonist status, turned out they were a rev head and it ended the round instantly. I tested most of them, here's what I found:
**Correctly showing up:**
Traitor
Changeling
Space Ninja
**Not showing up:**
Cult
Rev
Wizard
Nuke Op
Devil

**Comment by Cyprex** [comment]
Half the ones showing up are team antags, what about blood brothers?

**Comment by elyina** [comment]
Blood brothers do show up
