### ISSUE TITLE
Fire burns mask through cap suit

### ISSUE THREAD

**Issue by Electronics** [tgstation/tgstation#42005]
Reference #41831 and #41618 for more details, but this is still a problem with the captain's hardsuit.

**Comment by Electronics** [comment]
Still an issue

**Comment by OmegaShoots** [comment]
can confirm still an issue as of round 111420, caused my death when i was caught in a plasmafire as captain and my breath mask burnt off and i had nowhere to go that wouldn't kill me

**Comment by OmegaShoots** [comment]
can confirm the issue is not specific to the captain's suit but even other suits that should normally protect the mask from burning, like firesuits and such

**Comment by Electronics** [comment]
Seeing as this was fixed by #46732 ...
