### ISSUE TITLE
Admin logs for the pods are strange

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#42001]
Issue reported from  Round ID: 98835 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

ADMIN LOG: DaxYeen/(Caroline Dupont) launched a pod*no key*/(NTCOS), . Boom=|5|10|20|20|] in nonexistent location.

(T) A special package is being launched at the station!

ADMIN LOG: DaxYeen/(Caroline Dupont) launched a podDarkness12344/(Trooper Ford Spinetwist), . Boom=|5|10|20|20|] in nonexistent location.

@MrDoomBringer formatting issue I think

**Comment by dragomagol** [comment]
Appears to have been fixed
