### ISSUE TITLE
Bank machines do not dispense money

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#42018]
Issue reported from  Round ID: 98885 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Siphoning credits removes money from the service account, but no actual holochips or w/e they're called appear at the machine.

**Comment by GravitronBlue** [comment]
Cash is released once the siphon is manually stopped or when cargo runs out of money, but otherwise it no longer dispenses 200 credit increments liked it used to.

**Comment by Tlaltecuhtli** [comment]
not sure but when i syphoned the money last time you had to wait like 10s and then it ll pop a a few thousands cash

**Comment by kriskog** [comment]
Its just how it works now with the holochips. Money pops out on end_syphon.
