### ISSUE TITLE
wizard mutate overlay issue (probably laser eyes)

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42029]
1. be wiz
2. buy mutate
3. use it 
4. rinse repeat a lot
5. look at the horror that is you

think its an issue with laser eyes, every time i popped mutate it gave me a random overlay, including random people/objects, and the overlays never went away so i had a bunch of shit stacked on me.

**Comment by Time-Green** [comment]
may be related to everyone that gets unmonkey'd having laser eyes

**Comment by kriskog** [comment]
This either got fixed or was a round-specific thing. Haven't seen it since.
