### ISSUE TITLE
Heirloom body bags stop being heirloom once used

### ISSUE THREAD

**Issue by Names-Are-Hard** [tgstation/tgstation#42023]
## Round ID:

Test server
## Testmerges:
None

## Reproduction:
Be a doctor with the heirloom trait, get body bag as your heirloom. Place body bag on the ground. Pick it up again, and it is no longer recognized as your heirloom.

![image](https://user-images.githubusercontent.com/35442306/50270923-fe487180-03e7-11e9-9349-3c06bd11849e.png)

**Comment by zxaber** [comment]
I wonder if the bag item is spawning the unfolded bag and then deleting itself?
If so, I suppose it should be an easy fix of passing on the heirloom variable.

Does a bodybag seem like a really weird heirloom to anyone else? Seems like a line of doctors would have like a family stethoscope or something.

**Comment by ExcessiveUseOfCobblestone** [comment]
Family Heirloom bodybag....

**Comment by Time-Green** [comment]
the better fix would be to store the object instead of deleting it
