### ISSUE TITLE
Pipe Layer Sprite Connectivity Broken

### ISSUE THREAD

**Issue by KomradeSpectre** [tgstation/tgstation#42039]
Issue reported from  Round ID: 99022 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Layered pipes are not connected visually to things like layer manifolds and stuff, but still work as if they are. In essence, to replicate, make a layer manifold, and connect pipes on different layers to it, you will see that they look like they are not connected to it as the sprite connectivity is currently broken.

**Comment by SpaceManiac** [comment]
The server did not have #42015 merged during that round. I believe the issue has been fixed by that PR. Please reply if it persists on an updated server.

**Comment by KomradeSpectre** [comment]
Layering Issue Persists, as seen in Round ID: 99091.

**Comment by Dennok** [comment]
![image](https://user-images.githubusercontent.com/7734424/50419535-ec2c6000-0839-11e9-85ed-7af3fa936fe4.png)
find it only on layer manifold
Round ID: 99196
Master commit: 3b6fd6a7175b0e9625d39666f85142e9fe3745f3
The following pull requests are currently test merged:
#40907: 'Readds Birdboatstation' by Bawhoppen at commit 24fc397e1a
