### ISSUE TITLE
VR Sleepers can be used to crash the server

### ISSUE THREAD

**Issue by Names-Are-Hard** [tgstation/tgstation#42037]
## Round ID:
Test Server

## Testmerges:
None

## Reproduction:
![image](https://user-images.githubusercontent.com/35442306/50370399-8ea6c380-055a-11e9-9148-b0b5872523be.png)
Have access to two VR sleepers.
![image](https://user-images.githubusercontent.com/35442306/50370402-9b2b1c00-055a-11e9-9fae-153b6c31ea92.png)
Go into the first one and activate it.
![image](https://user-images.githubusercontent.com/35442306/50370405-abdb9200-055a-11e9-8a50-2d0ce9181469.png)
Use the second sleeper with your VR mob.
![image](https://user-images.githubusercontent.com/35442306/50370407-b9911780-055a-11e9-8d84-eb4edbd808f1.png)
![image](https://user-images.githubusercontent.com/35442306/50370411-c9a8f700-055a-11e9-9d9a-0fa4840a583b.png)
Open the first sleeper.
![image](https://user-images.githubusercontent.com/35442306/50370417-daf20380-055a-11e9-8aad-a560831565db.png)
Delete virtual avatar.
![image](https://user-images.githubusercontent.com/35442306/50370419-e47b6b80-055a-11e9-9e28-9ace282ce5f3.png)
Delete virtual avatar on the second sleeper.
Watch as the server shits itself.

**Comment by optimumtact** [comment]
this is why we don't let virtual mobs go on the same location as the sleepers.

**Comment by nicbn** [comment]
Tried to reproduce. Server hanged for some time but didn't crash.

My mind got send to nullspace or something like that:
![image](https://user-images.githubusercontent.com/20824501/50702307-b5272d00-1037-11e9-931a-c9dd889650fe.png)
Ghostizing or quiting VR won't do anything.
Then the client, not the server, crashed.

Logs:
```
[15:40:59] Runtime in LINDA_turf_tile.dm,90: Cannot execute null.archive().
[15:40:59] Runtime in gas_mixture.dm,378: Cannot read null.gases
  <<THESE 2 ERRORS REPEATED A LOT OF TIMES>>
[15:43:02] Runtime in unsorted.dm,1173: Ghostize was called on a virtual reality mob
  usr: guest3737052053/(Braeden Price)
  usr.loc: (Snowdin Outpost (39, 221, 13))
[15:43:43] Runtime in unsorted.dm,1173: Ghostize was called on a virtual reality mob
  usr: guest3737052053/(Braeden Price)
  usr.loc: (Snowdin Outpost (38, 220, 13))
[15:43:56] Runtime in human.dm,318: Cannot read null.species
  usr: guest3737052053/(Braeden Price)
[15:43:56] Runtime in human_movement.dm,46: Cannot read null.mutations
  usr: guest3737052053/(Braeden Price)
  <<THIS ERROR REPEATED A LOT OF TIMES>>
  (This error will now be silenced for 10 minutes)
[15:44:11] Runtime in carbon.dm,580: Cannot execute null.update remote sight().
  usr: guest3737052053/(Braeden Price)
[15:44:11] Runtime in client_colour.dm,64: Cannot read null.len
  usr: guest3737052053/(Braeden Price)
[15:44:11] Runtime in human.dm,728: Cannot read null.species
  usr: guest3737052053/(Braeden Price)
[15:44:11] Runtime in unsorted.dm,1173: Ghostize was called on a virtual reality mob
  usr: *no key*/(Braeden Price)
  usr.loc: (Snowdin Outpost (39, 222, 13))
```

**Comment by Names-Are-Hard** [comment]
Someone told me it's possibly to find BoHs in Snowdin, which would, with some luck, allow this to happen without admin intervention.
