### ISSUE TITLE
Clown car can drag people from any distance after starting drag-in animation.

### ISSUE THREAD

**Issue by TorinoFermic** [tgstation/tgstation#42032]
Issue reported from  Round ID: 98984 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

The clown car can affect on resting mobs and start the drag-in animation and it can't be stopped up to crawling away as long the clown car does not move.

**Comment by evsey9** [comment]
Feature

**Comment by michnia** [comment]
😀

**Comment by YakumoChen** [comment]
dupe of #41392
