### ISSUE TITLE
bees don't make any attemt to retaliate or flee from people that cant be injected

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42047]
probably sorta intentional but its super lame having bees just bend over and do nothing when a dude in an emergency firesuit rolls up. it should check if it can inject the body part it stings when it attacks someone to try injecting, at least then theyd do minor brute damage to inject-proof people.

**Comment by YakumoChen** [comment]
that doesn't even make any sense for bee behavior, they tend to sting aggressively no matter how much padding someone has, but in game terms that's terrible for the AI since they can only aggro one at a time.

**Comment by optimumtact** [comment]
mob ai is garbage as per usual, not much we can do, someone could add a flee option, but this isn't a bug.
