### ISSUE TITLE
loneops can buy but not use borgs

### ISSUE THREAD

**Issue by zeroisthebiggay** [tgstation/tgstation#42042]
## Round ID: 
99028

## Testmerges:
#40907: 'Readds Birdboatstation' by Bawhoppen at commit 24fc397e1a

## Reproduction:
>be loneop
>see cyborg on discount
>buy it
>"The syndicate assault cyborg teleporter is out of range! It can only be used at your base!"
>cry because you just spent 24 tc on an item which you can't use

**Comment by HomocidlePancakes** [comment]
It's intended. Also you can just refund the thing for TC fyi

**Comment by zeroisthebiggay** [comment]
> It's intended. Also you can just refund the thing for TC fyi

i tried banging it against my uplink
i tried banging it _with_ my uplink
i was never given an option to

p sure you can only refund it if no ghosts accept the offer (which can't even be prompted to be done since you can never go to your base 'cuz you're a loneop)

**Comment by SpaceManiac** [comment]
Discounted items are non-refundable.

Lone op and nuclear uplinks are not currently distinguished.
