### ISSUE TITLE
Laser scalpel can't be interacted with

### ISSUE THREAD

**Issue by DfourC** [tgstation/tgstation#42055]
The laser scalpel (the upgraded scalpel/surgical saw combo) can't be interacted with properly while it is in scalpel mode. It can't be clicked on to pick it up or examine it unless you use the right-click menu. Once you use that to pick it up, you can then use it as normal for tasks, but you need to use the Object tab and use Activate Held Object to change it to saw mode. While it's in saw mode it can be used totally as normal, dropped and picked back up again, activated in-hand by clicking on it, all the usual stuff. Once you put it back into scalpel mode, it requires the right-click menu to interact with again. Neither the mechanical pinches (retractor/hemostat) or the searing tool (cautery/surgical drill) have this problem, it's just the laser scalpel. I printed out the laser scalpel from the Medical techfab as I would any other tool, it just doesn't behave properly.

**Comment by 4dplanner** [comment]
@Tlaltecuhtli

**Comment by Tlaltecuhtli** [comment]
works on my machine

**Comment by Coconutwarrior97** [comment]
Tested on my machine as well with no issues, going to close this in a bit unless more incidents of it come up.
