### ISSUE TITLE
Monthly report on just how awful ai static/cams are

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#42058]
Yeah I tell people about this constantly yet nothing is ever done so I made another compilation album, here we see me having fun looking at lavaland, before and after I got the ai camera upgrade for INFINITE light.

https://imgur.com/a/nwHEhCs

**Comment by carshalash** [comment]
So uh... When this happens when an ai is malf/has combat upgrade they can detonate things with overload machine regardless of if its on camms or not.

**Comment by Timonkeyn** [comment]
yea, Looking at lavaland is fun, but the ai isnt supposed to see whats not on the cams or else it would be hella op

**Comment by carshalash** [comment]
After a recent jimmy neutron brain blast that I experienced I may have finally been able to diagnose the source of this happening round start. Will have definite conclusion whether i'm right or not tonight.

**Comment by kriskog** [comment]
Uninformative title, no round id, no build or byond version info, barebones description and no reproduction steps. How do you expect someone to do anything about this?
