### ISSUE TITLE
Nuka Cola may or may not need scaling

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#42050]
So with movement speeds slowed, I believe nuka cola still gives the same speed it previously did. Meaning its even more impossible to stop now (disclaimer** i may be wrong, scanned code for it but don’t understand how movement speed modifiers worked, if im wrong just close sorry i don’t understand code). 

All Nuka Cola code included below for simplicity 
```
/datum/reagent/consumable/nuka_cola
	name = "Nuka Cola"
	id = "nuka_cola"
	description = "Cola, cola never changes."
	color = "#100800" // rgb: 16, 8, 0
	quality = DRINK_VERYGOOD
	taste_description = "the future"
	glass_icon_state = "nuka_colaglass"
	glass_name = "glass of Nuka Cola"
	glass_desc = "Don't cry, Don't raise your eye, It's only nuclear wasteland."

/datum/reagent/consumable/nuka_cola/on_mob_add(mob/living/L)
	..()
	L.add_movespeed_modifier(id, update=TRUE, priority=100, multiplicative_slowdown=-1, blacklisted_movetypes=(FLYING|FLOATING))

/datum/reagent/consumable/nuka_cola/on_mob_delete(mob/living/L)
	L.remove_movespeed_modifier(id)
	..()

/datum/reagent/consumable/nuka_cola/on_mob_life(mob/living/carbon/M)
	M.Jitter(20)
	M.set_drugginess(30)
	M.dizziness +=1.5
	M.drowsyness = 0
	M.AdjustSleeping(-40, FALSE)
	M.adjust_bodytemperature(-5 * TEMPERATURE_DAMAGE_COEFFICIENT, BODYTEMP_NORMAL)
	..()
	. = 1
```

**Comment by KomradeSpectre** [comment]
Don't quote me on this, but I believe this line right here will scale with the move_delay changes.

> L.add_movespeed_modifier(id, update=TRUE, priority=100, **multiplicative_slowdown=-1**, blacklisted_movetypes=(FLYING|FLOATING))

**Comment by wesoda25** [comment]
I saw that too but don’t know how it would actually affect speed. 

Its just even if I’m wrong and it’s scaled, nuka cola is just not fair given its better than lings strained muscles, for like $50. 

I’ve seen assistants, traitors, and security use it, and its really annoying and hard to deal with. Imagine flag robes but faster and no spiked damage.
