### ISSUE TITLE
Weird Parallax Behavior.

### ISSUE THREAD

**Issue by Kerbin-Fiber** [tgstation/tgstation#42069]
## Reproduction: 

- Open the Game Preferences Panel while in-game.
- Run around in space until the game gets laggy.
- Change your Parallax settings, up or down works perfectly fine.
- Result; Game looses all lag what-so-ever.

Really helps take out all that space-lag.

**Comment by ATH1909** [comment]
Thanks for the tip.

**Comment by DfourC** [comment]
lol 420 69

**Comment by Qustinnus** [comment]
i never lag with parallax, can this be reproduced?

**Comment by Iamgoofball** [comment]
nice

**Comment by interestingusernam3** [comment]
reddit issue

**Comment by bruhlookatthisdood** [comment]
i just came here to point out the funny number
