### ISSUE TITLE
Launching a supplypod that has a player inside of another object will nullspace the player.

### ISSUE THREAD

**Issue by Names-Are-Hard** [tgstation/tgstation#42079]
## Round ID:
99236

## Testmerges:
#40907: 'Readds Birdboatstation' by Bawhoppen at commit 24fc397e1a

## Reproduction:
>Spawn something that can contain a person in a supplypod bay (mechs, closets, etc.)
>Go into object
>Launch supplypod
>Be nullspaced
![image](https://user-images.githubusercontent.com/35442306/50431389-5d423680-087f-11e9-98da-3ac9761121c9.png)

**Comment by MrDoomBringer** [comment]
ah fuck
