### ISSUE TITLE
Toggle Midround Antagonist does not toggle candidacy for Wizard Diplomat

### ISSUE THREAD

**Issue by KomradeSpectre** [tgstation/tgstation#42070]
Issue reported from  Round ID: 99197 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

During an admin raging mages event, I attempted to opt out of wizard diplomat candidacy by changing my Game Preferences to disable wizard. That did not work, so I tried Toggling Midround Antagonist, which did not work at all for suppressing the prompt. In short, imagine about 20-40 minutes of constant **DONG DONG DONG DONG DONG DONG DONG DONG**

**Comment by optimumtact** [comment]
As far as I know, supressing midround antag does not prevent admin triggered event notifications.
