### ISSUE TITLE
spectral blade is fucked

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42078]
for starters, it traps ghosts. whenever the thing moves, it teleports back all the ghosts that have orbited it in the past. additionally, the ghosts dont remain visible much other than when they first start to orbit, and i dont think it even tracks them for the purposes of damage either. iirc this broke around the time the push/pull force changes were implemented but i might be wrong

**Comment by kriskog** [comment]
Orbit rework happened around the same time, potential candidate too.

**Comment by optimumtact** [comment]
no roundid, no reproduction steps, not clear how to retrigger.
