### ISSUE TITLE
AT processing doesn't take ATMOS_PASS_NO into account

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#42085]
Turfs that have `CanAtmosPass = ATMOS_PASS_NO` set and are connected to turfs with gas mix differences are recognized as active turfs by AT processing.

This currently throws "HEY LISTEN" warnings for the CentCom rift area, even through their gases don't interact with adjacent turfs due to ATMOS_PASS_NO.

![at](https://user-images.githubusercontent.com/32391752/50448231-31c35880-0920-11e9-8265-98819e6169f1.PNG)

**Comment by plapatin** [comment]
congratulations, you are open bug number 1500

**Comment by 81Denton** [comment]
![checkem](https://user-images.githubusercontent.com/32391752/50483649-fe023480-09ec-11e9-9302-b61f8536a1d7.jpg)

**Comment by MrStonedOne** [comment]
Atmos adjacency calculation is all fucked up and I don't know how it's been working at all.

Nothing checks that the turf can actually support atmos passing, just rather or not an atom on the turf is blocking it. And when turfs check neighboring turfs for atmos passing they add them to the list even if they themself do not support atmos passing.
