### ISSUE TITLE
Cyborgs can buckle people to chairs, but cannot unbuckle people from chairs

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#42093]
Round ID: 99318

1) Be borg.
2) Buckle a human to a chair.
3) Attempt to unbuckle.
4) Realise your only method of unbuckling is to deconstruct or destroy the chair.

**Comment by imsxz** [comment]
borgs don’t even got hands how are they buckling people lmao

**Comment by ShizCalev** [comment]
Duplicate of #37131
