### ISSUE TITLE
Beesplosion Doesn't Work in Grenade

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#42097]
Observed 4 months ago on bagil, and just now on private server.

The beesplosion works if mixed in beakers, but when put in a grenade they do not work. Only buzzkill grenade works, oddly enough. I can't tell via code why this is. 

If its worth anything, I had one beaker with 50 units of honey and radium, and another with 50 units of strange reagent.

**Comment by Tlaltecuhtli** [comment]
fixd the bug in local, will put a pr after i sleep and fix another runtime

**Comment by wesoda25** [comment]
ty

**Comment by wesoda25** [comment]
Guess this is resolved, I’ll close it now.

**Comment by Couls** [comment]
this was not resolved

**Comment by Sealed101** [comment]
this was resolved at some point, possibly by #63393; bees spawn normally
