### ISSUE TITLE
Defib nanites don't seem to work as intended / failed with only oxyloss

### ISSUE THREAD

**Issue by Vidiveni** [tgstation/tgstation#42108]
**Terry**

**Round ID:** 
99369

**Testmerges:**
#40907

**Reproduction:**
- Implanted myself and had 500 nanite volume. 
- Death Sensor sent code to Signal Repeater which sent code to Defib nanites after a 60 second timer. 
- Killed myself by setting emergency oxygen tank to 0 kpa and putting it on, enabling internals. 

![181228 1824 37 defib nanites not curing oxyloss](https://user-images.githubusercontent.com/19913451/50523173-e602e180-0ace-11e9-9fb0-5afe6de7aff5.jpg)

I entered my body when I got the ghost prompt, and stayed in my body until I had heard the defib fail sound.  

Result: I heard the "failed defib" sound and nothing happened. 
Expected result: I get revived and get some of my oxyloss healed? Not sure how normal defib works. 

Later I saw the same thing happen to another guy who was spaced. He had under 180 brute and burn but the defib fizzled.

**Comment by 4dplanner** [comment]
Not sure this isn't intended, there's a specific check in there to make sure you've been healed to above the death level.

**Comment by Vidiveni** [comment]
But oxyloss can't be healed after death.

**Comment by 4dplanner** [comment]
> I see, so that's what's going on. But oxyloss can't be healed after death. I'll test some more to see if I can make an actual successful defib happen.

I think the situation in which it'd work is something like you take 100 brute, 100 oxy. Nanites then heal you for 100 brute, leaving you revivable.

**Comment by Vidiveni** [comment]
Aight I've made them work. I still think they should do something about oxyloss though.
