### ISSUE TITLE
Mindcontrol Balance Problem

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#42104]
Despite mind control being so powerful, it doesn't seem to have a indicator that it's happening. For the hivemind, the only thing is that he goes catatonic for a second. While for the victim, he's doing whatever, the next second he's off the next airlock. Since it's so powerful shouldn't there at least be some text a few seconds before hand saying that you can feel a alien presence invading into your mind or something? Despite what people say, hivemind is a very overpowered antag. If your discovered, steal a ID and wear something that covers your face. That or just use mind control to strip a engineer of a hardsuit and throw said engineer out a airlock none the wiser. The only real way to combat them it feels like is to implant the entire crew and hope you get lucky. Don't forget that for only 3 implants it costs 4k points too.

**Comment by davethwave** [comment]
Yep... I ded

**Comment by kriskog** [comment]
This isnt really an issue, and assimilation have gone through some pretty big balance changes since.
