### ISSUE TITLE
singularity/proc/mezzer() procs on corpses

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#42117]
Singularity mezzer() procs on corpses, which leads to situations where corpses trigger "Cuban Pete stares blankly at the gravitational singularity!".

**Comment by tralezab** [comment]
https://github.com/tgstation/tgstation/blob/8b2b59732411886be5869c520113b49f854e6fce/code/modules/power/singularity/singularity.dm#L422-L424

yeah, stat for simplemobs is either alive or dead, so i'm assuming that's what is screwing with it
