### ISSUE TITLE
Fake handcuffs have disproportionately long unbuckle times

### ISSUE THREAD

**Issue by cookingboy3** [tgstation/tgstation#42125]
## Testmerges:
#40907 and #41994

## Reproduction:
1. Play a fun space arcade machine, win yourself a pair of fun fake handcuffs
2. Find someone you don't like, slap the handcuffs on them
3. Stick them in a chair, and buckle them in
4. Witness as it takes them a minute to resist out of the chair, followed by 1 whole second to get out of the cuffs themselves.

**Comment by DaxDupont** [comment]
feature

**Comment by adamkad1** [comment]
i guess the buckle time is the same for any cuffs
