### ISSUE TITLE
You cant remove embedded object from your body by yourself

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#42124]
## Testmerges:
#40907: 'Readds Birdboatstation' by Bawhoppen at commit 348e864820
#41994: 'UNSTOPPABLE flag is now checked every time something tries to pass something instead of just once in the Move() proc' by kevinz000 at commit 866deec6a3

## Reproduction:
1. Join round
2. Wild ninja throw star in you. It stuck in your body
3. No way to remove it by yourself
3.1 It was possible to remove object by clicking link after you examine yourself. 
4. Link don't work.
https://i.imgur.com/AjiwkZY.png
![throwing star](https://i.imgur.com/AjiwkZY.png)

**Comment by Tlaltecuhtli** [comment]
intended

**Comment by kopoba** [comment]
> intended

I don't see when/where it was introduced. Changelog dont mention this change.

**Comment by Tlaltecuhtli** [comment]
wait i read the isse as "can remove embeds" nvm

**Comment by HomocidlePancakes** [comment]
Isn't it weird that you yourself can remove embeds but noone else can (surgery doesn't count)

**Comment by Time-Green** [comment]
You need to click the big hud icon in the upper right of your screen

**Comment by SpaceManiac** [comment]
If the link doesn't work that's still a bug

**Comment by Shardj** [comment]
Also encountered this, the link to pull out embedded stuff has never worked for me

**Comment by kopoba** [comment]
Fixed somewhere and somehow. I don't encounter this long time.
