### ISSUE TITLE
storage implant removal is borked

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42136]
doesn’t eject the contents of it properly. 

To reproduce:
1. Get storage implanted
2. Put stuff into implant
3. Get implant removed (via surgery)
4. stuff you put in earlier doesn’t come out

**Comment by Tlaltecuhtli** [comment]
brain transfer someone into his body and take the gaming gear   ¯\_(ツ)_/¯

**Comment by Cyprex** [comment]
Did this ever work? Is it supposed to? Now, if you reanimate the body, possibly with a different brain, and the contents were gone that seems like a bug. Is there not an issue about this already?

**Comment by SpaceManiac** [comment]
The exact intended behavior is somewhat unclear, but notably even if you preserve the implant and inject it into someone else the items are still lost.
