### ISSUE TITLE
holoparasite interaction bug

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42137]
you can interact with your host while unmanifested.

uses include: dragging your host (breaks the grab of other people, incredibly abuseable in combat), spamming the attack noise from inside as a standard holoparasite, probably more shit

**Comment by k-k-karma** [comment]
first one's probably a good thing considering the meta of drag and beat which the holoparasite is unable to do anything about unless they're really good discouraging newbs

**Comment by wesoda25** [comment]
Nah, the drag from inside the person would logically make sense, but its not fair. 

Having a stand who knows how to do it is the difference between a 3 minute murderbone and a 20 minute. 

Imsxz you forgot about explosive stands priming lockers inside their host.

**Comment by optimumtact** [comment]
bugs

**Comment by Borisvanmemes** [comment]
explosive stands arming shit while in their host got fixed ages ago iirc
