### ISSUE TITLE
Making a Station-Wide Announcement as a Grey Alien (Ayyy) will instead send it to Ayyy Hivemind

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#42132]
As stated in title.

**Comment by wesoda25** [comment]
I think its for the best this is a feature. However aliens shouldn’t be able to send messages to other stations, as its an annoying loophole.

**Comment by kriskog** [comment]
Mimes with vow can send announcements

**Comment by kriskog** [comment]
This has been changed
