### ISSUE TITLE
Ai can see everything (no cameras)

### ISSUE THREAD

**Issue by Shardj** [tgstation/tgstation#42144]
Issue reported from  Round ID: 99497 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

I was able to view all parts of the station by going into multicam view and spamming between a few windows then exiting multicam view. I could exit this "view all" state by going in and out of multicam again.

**Comment by Shardj** [comment]
Worth noting, sometimes it took multiple attempts when I spammed between windows. Had to open and close up to 3 times at most

**Comment by Anonmare** [comment]
That bugs been hanging around for ages. It's a pain in the ass to play dumb about stuff I shouldn't be able to see

**Comment by DaxDupont** [comment]
@Arianya sounds like we should disable multicam in the config till this is fixed.

**Comment by optimumtact** [comment]
yeah carsh has reported thsi multiple times and nobody seems to want to fix it, or investigate the byond issue behind it.

**Comment by Shardj** [comment]
Worth disabling multicam just for this to be honest, its game breakingly overpowered if someone abuses it.

**Comment by Shardj** [comment]
Fair enough, that's just the way I found I suppose. Could you merge issues or mark as duplicate if there are others for the same issue

**Comment by actioninja** [comment]
Dupe issue of #38857
