### ISSUE TITLE
Human mobs have weird sprite issues

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#42154]
Issue reported from  Round ID: 0 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

![5hhbevb 1](https://user-images.githubusercontent.com/17237624/50561190-a0315d80-0d08-11e9-8235-72e23a893bdd.png)

**Comment by ShizCalev** [comment]
Dupe

**Comment by DaxDupont** [comment]
how the fuck did i miss the other issue report
