### ISSUE TITLE
Cloning doesn't work

### ISSUE THREAD

**Issue by Scinexx** [tgstation/tgstation#42150]
## Round ID: 35587

Plain and simple cloning does not work at all, the pod is broken

## Reproduction:

Scan someone in cloner, try and clone, doesn't do anything

**Comment by DaxDupont** [comment]
yeah it's breaking randomly. It works and then it doesn't.

Usually gets stuck on initialization failure even though fully upgraded and them being in the body.

Also autoprocess scans don't update old scans and thus it doesn't clone them. @4dplanner

**Comment by 4dplanner** [comment]
Looking into it.

**Comment by 4dplanner** [comment]
Confirmed that autoprocess scans update old scans.

**Comment by 4dplanner** [comment]
In what specific circumstances does it break? I don't want to suggest user error here, but I have seen quite a few people misusing it.

**Comment by DaxDupont** [comment]
Hard to say, it often seems to breaking later into the round.

**Comment by 4dplanner** [comment]
I'm also a little confused by the round ID, as we've been in the 90000s for a while now.

**Comment by 4dplanner** [comment]
@Scinexx, just checking - is this for a downstream?

**Comment by DaxDupont** [comment]
I've definitely seen it happen and checked the corpses out with vv and they were meeting all criteria at the time so it wasn't user error. They didn't have any of the no clone flags, they had a ghost in them, the weren't excessively damaged.

Also one it started happening NOBODY could be cloned. I'll try and get a round id next time it happens.

**Comment by k-k-karma** [comment]
oh hey thisis fucking us over majorly no-one can be cloned EVER

**Comment by optimumtact** [comment]
YOU NEED, TO GIVE ROUND IDS

**Comment by nicbn** [comment]
@optimumtact He did.

**Comment by yoyobatty** [comment]
How has this not been fixed? It's been almost 2 weeks.

**Comment by 4dplanner** [comment]
Not a single tgstation round ID has been posted, and the original reproduction steps are inadequate.

**Comment by yoyobatty** [comment]
Yeah and seeing this issue made me think it wasn't exclusive to our server, I guess not.

**Comment by 4dplanner** [comment]
I'll try to give hippie a look when I'm free to see if it's a more reproducible version of what Dax mentioned.
