### ISSUE TITLE
Xenos do not process reagents.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#42161]
If you inject a xeno with anything, they won't process the chems in them, meaning classic strategies like chloral/neurotoxin/beepsky smash outright do not function right now. The chems just idle in them and never go away, but also don't affect them.

**Comment by Cyprex** [comment]
I'm guessing this is due to their lack of a liver?

**Comment by Shardj** [comment]
This needs to be closed now surely?

**Comment by Shardj** [comment]
@ExcessiveUseOfCobblestone

**Comment by ExcessiveUseOfCobblestone** [comment]
no
