### ISSUE TITLE
Chasms that travel on the emergency shuttle don't actually send you to the shadow realm

### ISSUE THREAD

**Issue by plapatin** [tgstation/tgstation#42160]
Issue reported from  Round ID: 99543 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

![image](https://user-images.githubusercontent.com/222630/50575796-aaf7fb00-0db9-11e9-9d3e-973e9a6c7502.png)

But they work just fine on their home turf.
Take a wild guess as to how to reproduce this.

**Comment by k-k-karma** [comment]
its a fakechasm because admins are hugbox fagcoders

**Comment by plapatin** [comment]
it's not fake. this has happened before to me

**Comment by plapatin** [comment]
not to mention it wasn't fake before

**Comment by coiax** [comment]
They're not fake chasms. They're just not working for some reason.

**Comment by kriskog** [comment]
Seen these working lately, still an issue?
