### ISSUE TITLE
megafauna can be cheezed with cham projectors

### ISSUE THREAD

**Issue by Suicidalpickles** [tgstation/tgstation#42163]
Round ID:
#99551

Testmerges:
The following pull requests are currently test merged:
#41994: 'UNSTOPPABLE flag is now checked every time something tries to pass something instead of just once in the Move() proc' by kevinz000 at commit 866deec6a3

Reproduction:
title
basically, any traitor can buy a chameleon projector, aggro a megafauna towards them, cloak themself as an item and end up unable to be attacked by said megafauna. Eventually it will drop aggro after trying to attack the cloaked person a bit. Its been a trend of it being used to bait them to the station.

**Comment by k-k-karma** [comment]
you can literally just shoot them once and put a portal infront of them, this isnt an issue

**Comment by bigfatbananacyclops** [comment]
megafaunas are supposed to be stupid but aggressive beings, except bubblegum because he can sense blood.

**Comment by tuypo1** [comment]
It's almost like they're dumb animals

**Comment by YakumoChen** [comment]
I thought using carp against colossus blades made it charge you and fuck you up?

**Comment by optimumtact** [comment]
This isn't really a bug, just a function of poor mob ai.
