### ISSUE TITLE
Perma is a fucking joke

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#42168]
Perma is no longer useful to hold people, it's easy as fuck to just walk out into space after breaking a window and getting right back on station. Whatever nerf to space damage or whatever has made it easy to escape a part of brig that is generally supposed to require outside help to escape.

This is most relevant on Metastation but I've seen it happen pretty often on other maps too.

**Comment by optimumtact** [comment]
This is not a bug really

**Comment by YakumoChen** [comment]
Guess I'll just execute every time then? There's no point in putting people there if try can just walk out effortlessly

**Comment by optimumtact** [comment]
No I mean it's more of a design issue, so it should go on the forum, not that it's a not an issue at all.

**Comment by wesoda25** [comment]
Shutters exist. But shutters should also be provided for perma windows.
