### ISSUE TITLE
Arm implant radial menu has no icons

### ISSUE THREAD

**Issue by hazamaitsuru** [tgstation/tgstation#42164]
When activating an arm implant, none of the icons appear in the radial menu. Tested with toolset, combat, and surgery arms.

![image](https://user-images.githubusercontent.com/222630/50575789-8e5bc300-0db9-11e9-9a4a-899c206e9e7b.png)

**Comment by optimumtact** [comment]
@swindly

**Comment by swindly** [comment]
Unable to reproduce

![untitled](https://user-images.githubusercontent.com/22402048/50611264-a3c21180-0ecd-11e9-9667-6ad6d1892194.png)
![untitled](https://user-images.githubusercontent.com/22402048/50611274-ab81b600-0ecd-11e9-8e6b-2949bbd6c616.png)
![untitled](https://user-images.githubusercontent.com/22402048/50611308-c3593a00-0ecd-11e9-9cbd-b34fa80d1ec8.png)

**Comment by hazamaitsuru** [comment]
The toolset arm was emagged, giving it a knife.

The icons are appearing now. The only changes made were map edits, but am now back on standard. I'll have to run an edited map again to see if they break once more. Doubt that would cause the problem, though.

**Comment by PKPenguin321** [comment]
Since you were unable to reproduce this, it seems like it was possibly a one-off cache problem.
