### ISSUE TITLE
Forced into being an antagonist on lowpop, even with preferences not enabling the antagonist type.

### ISSUE THREAD

**Issue by FancyCyclops** [tgstation/tgstation#42171]
## Round ID:
99581

## Testmerges:
#41994: 'UNSTOPPABLE flag is now checked every time something tries to pass something instead of just once in the Move() proc' by kevinz000 at commit 866deec6a3
#42155: 'Fixes extraneous naked human icon appearing below all humans' by kevinz000 at commit fec5676ba4

## Reproduction:
I was readied for the round, with my antagonist settings disabled.
The population was very low. (Likely 4 crew?)
I do not actually know how to reproduce it. However, I have screenshots.
I am unsure if I am able to help much. Thank you for hearing me out.

**Comment by Cyprex** [comment]
I believe simply joining into an empty traitor round will give you antag. Is it an issue for you?

**Comment by Time-Green** [comment]
If there's not enough people for antag it will start forcing them regardless of preference

**Comment by FancyCyclops** [comment]
Oh. Well, sorry about that. It is somewhat of an issue, but I'll keep that in mind.
