### ISSUE TITLE
space makes miasma???

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42177]
![image](https://user-images.githubusercontent.com/222630/50575704-ef829700-0db7-11e9-8b1c-e054c0943ff9.png)

same tile, moments apart, 1x1 space tile with no dead bodies. does it on every space tile, go onto one and press view gases as a ghost for a bit.

**Comment by FloranOtten** [comment]
have you ever had a smell of space? not nice.

feature

**Comment by DaxDupont** [comment]
That sounds lag inducing as fuck

**Comment by imsxz** [comment]
update: cant use scrubberrs to get the magic space farts RIP

**Comment by Whoneedspacee** [comment]
I’ve talked to dunc about this, all space use the exact same gas mixture reference so it isn’t really laggy. It also doesn’t affect anything since immutable mixtures dont archive so they won’t transfer this at all.

It’s basically just a visual bug.
