### ISSUE TITLE
You can hear the sound of ash storms when in a bluespace survival pod in space

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#42179]
Round ID: 99592.

1) Deploy bluespace surival pod in space.
2) Be a ghost (maybe)
3) You can hear when lavaland is undergoing an ashstorm.

**Comment by kriskog** [comment]
Some other areas do this too, I believe in space ruins. I dont recall specifics currently.

**Comment by timothymtorres** [comment]
Duplicate of #58475
