### ISSUE TITLE
Nightmare Wizard Issue

### ISSUE THREAD

**Issue by Timonkeyn** [tgstation/tgstation#42174]
So, If a Nightmare Wizard Spawns Ghosts, the light they emit can literally kill you and/or reveal you which they really shouldnt. You guys removed Chair rotating and spooking so why not disable the ghost glow hurties to a nightmare?

**Comment by coiax** [comment]
Have you considered not both picking a nightmare species AND also making ghosts visible?

**Comment by Timonkeyn** [comment]
I have considered not using the mirror the last 3 times i played

**Comment by Timonkeyn** [comment]
despite that, i can affect other nightmares too

**Comment by DaxDupont** [comment]
feature

**Comment by coiax** [comment]
Literally a feature of emergent mechanics interacting.

**Comment by optimumtact** [comment]
Literally a feature of emergent mechanics interacting.
