### ISSUE TITLE
getting random job from antag bypasses jobbans

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42180]
kinda tough to reproduce but i got curator antag when im banned from curator, was rolling for security at the time.

**Comment by DaxDupont** [comment]
How do you get banned from curator?

Also if I remember correctly we made it ignore job bans for antags iirc

**Comment by tuypo1** [comment]
How many times would you have to read woodies got wood in a single shift to be banned from curator.

**Comment by optimumtact** [comment]
there's like zero chance anyone will reproduce this.
