### ISSUE TITLE
Genetic sequence scanner's sprite is invisible

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#42188]
![default](https://user-images.githubusercontent.com/38788538/50604029-a8d39080-0ece-11e9-9e95-e98bd03fd2ad.png)
![default](https://user-images.githubusercontent.com/38788538/50604033-abce8100-0ece-11e9-9457-850da0fbe822.png)

**Comment by kriskog** [comment]
This doesnt seem to be an issue anymore
