### ISSUE TITLE
Font of the message window keeps changing

### ISSUE THREAD

**Issue by Amalvi** [tgstation/tgstation#42198]
Issue reported from  Round ID: 99659 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Attached image, noticeable
![captura](https://user-images.githubusercontent.com/46332323/50617599-6326c000-0eee-11e9-8daa-fbd9bfefd01d.PNG)

This issue wasn't happening to me before

**Comment by Amalvi** [comment]
another pic from the same round, its more notable here
![captura](https://user-images.githubusercontent.com/46332323/50617874-a59ccc80-0eef-11e9-8412-9a228b5c4670.PNG)

**Comment by SpaceManiac** [comment]
Does your chat window have these icons in the top-right corner? 
![image](https://user-images.githubusercontent.com/222630/50619763-11f7db80-0eb0-11e9-9da7-c286c9a22542.png)

**Comment by Amalvi** [comment]
I must say that upon restarting the client the problem got fixed

To answer the question, yes, it does have such icons

**Comment by k-k-karma** [comment]
thats really creepy

**Comment by Amalvi** [comment]
Alright, it happened again, iIthink i figured something

It was brief, but when I opened the byond client, the font of the goonchat was once again being all random and changing, but I didn't have time because it only took a couple of second and when the changelog window appeared the fonts completely normalized

**Comment by nicbn** [comment]
that's probably because the goonchat was loading
is the issue gone?

**Comment by Amalvi** [comment]
![captura](https://user-images.githubusercontent.com/46332323/51142860-56d72700-184d-11e9-9a9f-3ed150138374.PNG)

**Comment by SpaceManiac** [comment]
Is your computer perhaps set to a Japanese locale?

**Comment by Amalvi** [comment]
> Is your computer perhaps set to a Japanese locale?
Indeed

![captura](https://user-images.githubusercontent.com/46332323/51173374-96395e00-18b5-11e9-99e1-b85dfb9cf922.PNG)

Dem hentai games, man...

**Comment by SpaceManiac** [comment]
BYOND is known to act strangely under non-English locales. I suggest using a locale emulator software one way or the other.

**Comment by Amalvi** [comment]
To be honest the goonchat going haywire never really bothered me, but I was told to talk about the issue on github by an admin

Being able to help with this issue was my motivation, so I hope this helped with improving the game now that the origin of the issue is known

**Comment by SpaceManiac** [comment]
Unfortunately, there is basically nothing we can do to solve this, given that it occurs only under known-bad conditions (non-English locale) which the BYOND engine is not designed to support.
