### ISSUE TITLE
Using Hilbert's Hotel from inside of a hotel room leaves you in a tiny room with no way out

### ISSUE THREAD

**Issue by LegendaryMister151** [tgstation/tgstation#42191]
Round ID: 99646 

Not exactly sure but when I entered a hotel room, the item stayed with me instead of dropping, making me unable to leave. By using it again to enter a new room, I left that room and was placed in a tiny room with no way out
![image](https://user-images.githubusercontent.com/46329759/50611123-4749fc80-0ea3-11e9-97f7-36e8ec88ce83.png)

**Comment by SpaceManiac** [comment]
@TheDreamweaver

**Comment by TheDreamweaver** [comment]
Hmm, the issue is with it staying with you. Any idea why it might have done that? Either way, I think I have a fix.
