### ISSUE TITLE
Supplypod cloning fails to clone showers properly.

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#42212]
Creating an /obj/machinery/shower in a supplypod bay and setting it a pod to clone instead of launching the real atoms created showers that could not be turned on on the centcomm Z-Level. Game Panel->Create Object creates working showers. I'm not sure if this is actually a bug or working as intended. 
@MrDoomBringer

**Comment by optimumtact** [comment]
actually probably more like @coiax

**Comment by coiax** [comment]
How so? This bug was present before I touched showercode

**Comment by MrDoomBringer** [comment]
This sounds like an issue with the DuplicateObject() proc, as thats what supplypods use to clone shit

**Comment by timothymtorres** [comment]
I can confirm that DuplicateObject is really old deprecated code from the build mode era.  It has been touched in years and when you try to use it the copies are usually broken.  There are several bug reports about this.
