### ISSUE TITLE
Runtime while showering with headset

### ISSUE THREAD

**Issue by hazamaitsuru** [tgstation/tgstation#42215]
`[17:50:55] Runtime in watercloset.dm,459: undefined variable`
`/obj/item/radio/headset/heads/captain/alt/var/clothing_flags`
`proc name: check clothes (/obj/machinery/shower/proc/check_clothes)`
`  usr: Hazama/(Felix Ivanov)`
`  usr.loc: (Research Division (181, 124, 2))`

Noticed this in my daemon window. I was naked except for a headset and science goggles when I hopped into the shower to wash away my funk. If it means anything, I was also a luminescent at the time.

**Comment by SpaceManiac** [comment]
caused by #41986 @Qustinnus

**Comment by Qustinnus** [comment]
>headsets arent clothing

ughhhhhh

**Comment by nemvar** [comment]
Stink overlay is no more and haven't been unable to reproduce.
