### ISSUE TITLE
Seclite teleports into 2.5 dimension upon being detached from accelerator in a bag

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#42210]
![default](https://user-images.githubusercontent.com/38788538/50650101-96219000-0f90-11e9-8856-e4398c55984f.png)

![default](https://user-images.githubusercontent.com/38788538/50650143-ae91aa80-0f90-11e9-8a13-998c82d15fb3.png)

**Comment by RedFoxIV** [comment]
oh god it's still there
![default](https://user-images.githubusercontent.com/38788538/50651141-8fe0e300-0f93-11e9-91e0-7aebdc0499ee.png)

**Comment by JenqaDev** [comment]
doesn't seem to be happening anymore
![image](https://user-images.githubusercontent.com/43709941/147887122-7b272bf2-6c3e-4f41-a9b8-bd693dc0161d.png)

![image](https://user-images.githubusercontent.com/43709941/147887128-4b89584a-0286-4781-bfc5-f94df23f3e07.png)

![image](https://user-images.githubusercontent.com/43709941/147887136-7fa8e55c-564f-4fc5-a679-0254ea0cf754.png)

works as intended
