### ISSUE TITLE
Inorganic Biology virus symptom doesn't seem to work

### ISSUE THREAD

**Issue by Vidiveni** [tgstation/tgstation#42222]
**Terry**

**Round ID:** 
99753

**Testmerges:**
#41994 #42155

**Reproduction:**
- Made a non-stealthy virus containing Inorganic Biology. 
- Made patches and pills. 

Asked a plasmaman to try it. He tried a patch and he did not get the virus, according to health hud. 
Asked a cloth golem to try it. He did and he did not get the virus, according to health hud. 

Expected result: Any non-simplemob with MOB_INORGANIC should be infectable with a virus containing the Inorganic Biology symptom. 

https://github.com/tgstation/tgstation/blob/master/code/datums/diseases/advance/symptoms/species.dm

**Comment by imsxz** [comment]
not a bug, blood cant infect bloodless species regardless of if theyre organic or not. typically inorganic mobs also dont breath no sneezing tends to not work either, meaning you'll need fluid contact+as the transmission vector for it to infect golems and such

**Comment by Vidiveni** [comment]
That makes sense, thanks. I'll try throwing some airborne virus beakers at them and then close this if it works.

**Comment by Vidiveni** [comment]
Alright tested it. Throwing a beaker at a plasmaman with touch-based virus did not work. But hugging him did. Nice.
