### ISSUE TITLE
Pirate shuttle turrets shoot hostages

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#42221]
>Be pirate
>Stun guy
>Cuff guy
>Drag to the shuttle
>Turrets shoot him (and end up hitting you most of the time because he is behind you)
>Die

Also getting hostages for ransom is simply not worth it. You get just 1k from it and you need to bring a space suit with you that doesn't even fit in you bag.

**Comment by nicbn** [comment]
Just ask your pirate buddy to disable the turrets.

**Comment by HomocidlePancakes** [comment]
*cough* slowdown *cough*

**Comment by HomocidlePancakes** [comment]
This just proves that getting hostages is too much of a hustle

**Comment by nicbn** [comment]
It's a trade-off. You get a slowdown, but more armor. Hostages may need a buff so that they give more money, but we don't need to make it easier - after all, it means removing someone from the game, it should be challenging.

**Comment by nicbn** [comment]
oh yeah forgot they aren't hardsuits
anyway it's a tradeoff, you get a slowdown but you get a hostage

**Comment by Tlaltecuhtli** [comment]
you get to remove people from the round

**Comment by MimicFaux** [comment]
1k still isn't enough for the effort however.
