### ISSUE TITLE
Using guns with TK fires the projectile from the user's location

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#42242]
If you TK grab a gun and fire it, the projectile gets launched from your position, not the gun's.

**Comment by Tlaltecuhtli** [comment]
wait tk makes you shoot the gun instead of trowing it?

**Comment by 81Denton** [comment]
Yeah, if you click on someone with it. Also works for magic wands

**Comment by SuperNovaa41** [comment]
I tested this a few months ago and it worked, now it doesn't. Now you can't shoot a gun with TK anymore, just toss the gun around.
