### ISSUE TITLE
Engines are weirdly positioned on the remapped battleship shuttle

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#42254]
Issue reported from  Round ID: 99851 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

![muf4pcl 1](https://user-images.githubusercontent.com/17237624/50739865-2e648280-11e6-11e9-91e6-cecc7dd4c3d6.png)
don't mind daddy farage
@WJohn

**Comment by WJohn** [comment]
Damn you, 2x2 objects. I don't think these rotate appropriately with the ship.

**Comment by Dennok** [comment]
I think this is code issue, not mapping if it brocken when ship rotating.

**Comment by SuperNovaa41** [comment]
can't find this, probably remapped by now
