### ISSUE TITLE
Destroying the AI Integrity Restorer Shunts You Back To Your Core

### ISSUE THREAD

**Issue by Crushtoe** [tgstation/tgstation#42262]
Issue reported from  Round ID: 99873 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Problem Description: I was an AI carded and placed in the AI Integrity Restorer after my core was destroyed and I was fully restored to 100% integrity. Plasma in the room caught fire and destroyed the console, and instead of dumping out my card, I was sent back to my core (though radio transmission was still disabled.) I was able to do all other AI functions though.

What did you expect to happen: I'd be dumped onto the floor.

What happened instead: I was sent back to my original core.

Steps to reproduce the problem: 
1. Be an AI.
2. Get destroyed, in my case by a bomb.
3. Get placed into an AI Integrity Restorer and get back up to 100% integrity.
4. Have something destroy the console with you still in it, in my case plasma fire.
5. Watch as you're sent back to your core automagically.

Possibly related stuff: There were 21 of us AI's so I don't know if that'd be related.

**Comment by GunHog** [comment]
Was your core dropped on the same tile as the console? If so, that is explained by the console dropping you onto the tile since you had no place else to go.

**Comment by zxaber** [comment]
For the record, there are two different AI restorer consoles. One of the two takes the card in (like a floppy drive or something), while the other actually uploads the AI into the console and the card is cleared. If you were in the second one, there might not have been a card to use.

**Comment by GunHog** [comment]
I believe you are referring to the dedicated console, and *not* the modular program.
