### ISSUE TITLE
Heat exchange pipes on layers other than 2 have their icons broken

### ISSUE THREAD

**Issue by Unit2E** [tgstation/tgstation#42278]
## Bug: 
As the title describes, certain heat exchange pipes have broken icons when they are on layers other than 2. All combinations of the basic "pipe" work, however, manifolds and 4 way manifolds don't line up with other pipes, or make no attempt to connect (visually) with adjacent pipes on the same layer. Oddly enough, layer 3 is somewhat more broken than layer 1. 4-way manifolds on layer 3 don't try to connect with other pipes at all, while layer 1 pipes just end up misaligned.

## Reproduction: 
Grab an RPD, switch to a layer other than 2, select a heat exchange manifold or heat exchange 4 way manifold, try to place a number of pipes.

## Images:
Layer 3 4-way manifolds, next to one another
![Layer 3 4-way](https://cdn.discordapp.com/attachments/315196159851495424/532185690059046962/unknown.png)
Layer 3 4-way manifold and normal manifold combination, misaligning
![Layer 3 combo](https://cdn.discordapp.com/attachments/315196159851495424/532186008146542592/unknown.png)
Layer 1 4-way manifold and normal manifold combination, misaligning, but differently
![Layer 1 combo](https://cdn.discordapp.com/attachments/315196159851495424/532186268675866635/unknown.png)

**Comment by nicbn** [comment]
oh no

**Comment by nicbn** [comment]
Thanks for your report.
