### ISSUE TITLE
Toxins Mixing Chamber Bug

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#42276]
Issue reported from  Round ID: 99925 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

In toxins, replaced the valves with pumps & connecting the input and output with another pump. 

For some reason, the canister and output pipes only ever had CO2 in them, and only 4500 kpa of it.

**Comment by SpaceManiac** [comment]
Map was MetaStation in case this is a map issue

**Comment by HideAndSeekLOGIC** [comment]
Did you change the scrubbed gases on the correct air alarm? That may be the problem.

**Comment by granpawalton** [comment]
i just checked the logs for that round ID, its what hideandseek said you never set the air alarm
