### ISSUE TITLE
Invisible Ethereal Augmentations

### ISSUE THREAD

**Issue by Bluedin01** [tgstation/tgstation#42282]
Issue reported from  Round ID: 99947 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Combining security painted augmentations on red colored ethereals causes the chest and head to be completely invisible (excluding eyes). Other manipulated augmentations were not tested in addition to other ethereal colors. 
![etherealaug](https://user-images.githubusercontent.com/46501078/50855158-18290480-1355-11e9-9152-b7057d0eba4e.PNG)

**Comment by ATH1909** [comment]
Time to become a stealthy ethereal boi.

Is there any way to move while having no arms or legs?

**Comment by ATH1909** [comment]
Does it display items that you're wearing?

Does it display the te;ekinesis head aura?

**Comment by Dennok** [comment]
about eyes, you can stay north or lay down.
Arm and legs can be prothesis too, and maby be unvisible too.
It display items if it have inhand sprite.
f you remove eyes it be black(maybe).
