### ISSUE TITLE
Mini egun flashlight icons are busted

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#42285]
basically when the light is off it's supposed to use the normal mini egun sprite and when the light is on it's supposed to use that with the mini-light sprite overlayed

but instead it's just using the default flight_on sprite overlayed when you turn it on and then it overlays flight when you turn the light off

pics because i'm such a dear

starting
![image](https://user-images.githubusercontent.com/38303698/50870255-20406e80-136c-11e9-8b31-516f085cb14c.png)
light on
![image](https://user-images.githubusercontent.com/38303698/50870269-29c9d680-136c-11e9-8ef4-a05f5a867d8f.png)
note that both the flight_on and the mini-light sprite are overlayed
light off
![image](https://user-images.githubusercontent.com/38303698/50870282-3817f280-136c-11e9-92dc-19cee9d1a11a.png)
flight overlay remains 

presumably when someone touched flashlights which i recall happening not too long ago they forgot to make it function with the mini egun, should be a quick fix

probably broken by https://github.com/tgstation/tgstation/pull/40998

**Comment by PKPenguin321** [comment]
how did you even notice this
