### ISSUE TITLE
New ling UI is a clusterfuck

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#42294]
![cancer](https://user-images.githubusercontent.com/35217076/50920567-c5377600-1456-11e9-8a84-d5b1368e6a11.PNG)

This is very much not okay. I would've just hid it, but there isn't a Changeling tab anymore.

**Comment by Cyprex** [comment]
How are action buttons better than verbs in the first place?

**Comment by ATH1909** [comment]
Wait, they removed the changeling tab?

Why not keep this AND the changeling tab, like we do for spells?

**Comment by MimicFaux** [comment]
Action buttons are nice, but also removing the tab is a mistake for people who like clean UIs
