### ISSUE TITLE
You can make infinite supermatter slivers

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#42301]
You can repeatedly take slivers off the SM without harming it, allowing you to make dozens or hundreds of slivers, which are highly radioactive and dust anyone who attempts to pick them up.

**Comment by wesoda25** [comment]
Think its a feature. Really not that hard to counter.

**Comment by 81Denton** [comment]
This was supposedly fixed by #34785 (but oh man the round where it happened was hilarious)

**Comment by 81Denton** [comment]
From testing:
- using the supermatter scalpel no longer decreases its `usesLeft`
- extraction increases the supermatter crystal's `matter_power` by 200, but this doesn't deal any damage to the crystal

**Comment by DaxDupont** [comment]
@ACCount12 broke it 
https://github.com/tgstation/tgstation/commit/100c4b6114fa3ce544063831349994544ea0df37#diff-efb741ea96810845b8b5a6e9ed572451
