### ISSUE TITLE
You can become a holodeck animal in a random intelligence event which is broken

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#42300]
You can't move and if you somehow leave the holodeck you get deleted.

**Comment by ExcessiveUseOfCobblestone** [comment]
the deletion upon leaving is intended, it even has extra flavortext for it.

**Comment by RedFoxIV** [comment]
Maybe cut holoanimals from possible candidates for this event then?

**Comment by ExcessiveUseOfCobblestone** [comment]
I forgot the rationale for leaving it in
