### ISSUE TITLE
Changing species cures all brain damage and traumas

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#42308]
Issue reported from  Round ID: 100048 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Changing someone's species, whether via Abductor change species gland, or via mutation toxin, will remove all traumas and all brain damage.

**Comment by ExcessiveUseOfCobblestone** [comment]
this should only be true if you go from nonhuman to human :^)

**Comment by ATH1909** [comment]
Don't staves of change and such also heal physical damage when they transform you, or am I misremembering things?

**Comment by Caiggas** [comment]
Commenting to find this later. I'll look into fixing this.
