### ISSUE TITLE
Xenos do not suffer slowdown when their queen is killed.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#42313]
When your queen is killed, you are supposed to suffer a slowdown, but at some point this stopped being the case because you move just as fast (though you still suffer from jittering and drunken movement and no hivemind).

Original intended effects are documented in #15766

**Comment by kriskog** [comment]
The original PR added 
```
owner.Stun(10) //Actually just slows them down a bit.
```

This is still in, closing
