### ISSUE TITLE
If ahelp tickets receive a reply that goes to IRC, all future text in the ticket is bolded

### ISSUE THREAD

**Issue by Arianya** [tgstation/tgstation#42319]
## Round ID:
0 (Round IDs are bugged)

## Testmerges:
None

## Reproduction:
Create a ticket (ahelp something)
Admin sends a response via "IRC" (Discord bots)
You respond to the admin, sending a response to "IRC"
Admin now logs on to the server and checks the ticket
All text after Step 3 becomes bolded, including the contents of your reply.

## Visual Aid
![image](https://user-images.githubusercontent.com/23403236/51034189-ccb56700-159d-11e9-8d92-d0efc6703ae3.png)

**Comment by PKPenguin321** [comment]
an unclosed bold tag?

**Comment by PKPenguin321** [comment]
Found it, it is indeed an enclosed bold tag:
https://github.com/tgstation/tgstation/blob/c4c32ab3306b91eeac6ce91f9f7aa8bc61655ee6/code/modules/admin/verbs/adminpm.dm#L149
