### ISSUE TITLE
antimagic doesnt protect from arcane bolts

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#42322]
had holymelons in pockets and it didnt protect me from arcane bolts
100087

**Comment by MimicFaux** [comment]
90% sure holy melons specifically were designed to be held to have the protection. To avoid pocket/backpack defense

**Comment by 81Denton** [comment]
Antimagic doesn't seem to work right now. I tried out an inquisitor's hardsuit, null rod, holymelon, absolutely nothing blocks magic (even when I hold it in my hand).

**Comment by 81Denton** [comment]
This is from when I tested it by giving a human simplemob a holymelon/null rod/inquisitor hardsuit. 
```
[22:53:02] Runtime in anti_magic.dm, line 38: Cannot execute null.Invoke().

proc name: protect (/datum/component/anti_magic/proc/protect)
usr: Denton-30/(Mckenzie Fields)
usr.loc: (Primary Tool Storage (57, 56, 2))
src: /datum/component/anti_magic (/datum/component/anti_magic)

call stack:
/datum/component/anti_magic (/datum/component/anti_magic): protect(Mckenzie Fields (/mob/living/carbon/human), Mckenzie Fields (/mob/living/carbon/human), 1, 0, 0, 1, /list (/list))
/datum/callback (/datum/callback): InvokeAsync(Mckenzie Fields (/mob/living/carbon/human), Mckenzie Fields (/mob/living/carbon/human), 1, 0, 0, 1, /list (/list))
Mckenzie Fields (/mob/living/carbon/human): SendSignal("mob_receive_magic", /list (/list))
Mckenzie Fields (/mob/living/carbon/human): anti magic check(1, 0, 0, 1)
Mckenzie Fields (/mob/living/carbon/human): anti magic check(1, 0, 0, 1)
the wand of healing (/obj/item/gun/magic/wand/resurrection/debug): afterattack(Cherry Heckendora (/mob/living/carbon/human/species/fly), Mckenzie Fields (/mob/living/carbon/human), 0, "icon-x=13;icon-y=15;left=1;scr...")
the wand of healing (/obj/item/gun/magic/wand/resurrection/debug): afterattack(Cherry Heckendora (/mob/living/carbon/human/species/fly), Mckenzie Fields (/mob/living/carbon/human), 0, "icon-x=13;icon-y=15;left=1;scr...")
Mckenzie Fields (/mob/living/carbon/human): ClickOn(Cherry Heckendora (/mob/living/carbon/human/species/fly), "icon-x=13;icon-y=15;left=1;scr...")
Cherry Heckendora (/mob/living/carbon/human/species/fly): Click(the floor (59,59,2) (/turf/open/floor/plasteel), "mapwindow.map", "icon-x=13;icon-y=15;left=1;scr...")
Denton-30 (/client): Click(Cherry Heckendora (/mob/living/carbon/human/species/fly), the floor (59,59,2) (/turf/open/floor/plasteel), "mapwindow.map", "icon-x=13;icon-y=15;left=1;scr...")
```

**Comment by ATH1909** [comment]
I've had issues with antimagic as well. I'm just gonna copy+paste a complaint that I sent to XDTM over discord here:
ATHATHYesterday at 1:33 AM
ATHATHYesterday at 1:33 AM
@XDTM more anti-magic problems
`Tzeentch Weatherwax says, "ONI SOMA"

Jack Jackson is hit by a bolt of fireball in the right leg!

Your eyes burn.

Tzeentch Weatherwax says something but you cannot hear him.

You can't hear yourself!x3

Young Oldman says something but you cannot hear him.`
I had a possessed blade (null rod variant) in my suit slot (I was wearing witchhunter gear, which lets me equip a null rod (or one of its variants) in my suit slot)
here's the code for a fireball projectile's effect on a direct hit
`/obj/item/projectile/magic/aoe/fireball/on_hit(target)
    . = ..()
    if(ismob(target))
        var/mob/living/M = target
        if(M.anti_magic_check())
            visible_message("<span class='warning'>[src] vanishes into smoke on contact with [target]!</span>")
            return
        M.take_overall_damage(0,10) //between this 10 burn, the 10 brute, the explosion brute, and the onfire burn, your at about 65 damage if you stop drop and roll immediately
    var/turf/T = get_turf(target)
    explosion(T, -1, exp_heavy, exp_light, exp_flash, 0, flame_range = exp_fire)`
it WAS a direct hit, as it hit me in the leg
and the explosion went off anyway
no text about it fizzling
and I DID take damage
