### ISSUE TITLE
Malf AI can run multiple Station Self Destructs and still Destroy the station if  carded or destroyed

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#42323]
Issue reported from  Round ID: 100094 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

As title says, a malf AI activated it's Doomsday Device 5 times in several seconds. AI was destroyed and carded, but only one countdown stopped. The other 4 countdowns went off, destroying all life on the station 4 times.

**Comment by Hathkar** [comment]
I also tried placing the AI back in its core once it was dead, and that didn't stop any of the additional countdowns.

**Comment by 81Denton** [comment]
This is what it looked like ingame

![doomed](https://user-images.githubusercontent.com/32391752/51051789-1bcabe80-15d5-11e9-8b27-f8d31e896124.jpg)
