### ISSUE TITLE
y o u r  m i n d  f e e l s  m o r e  c l e a r

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#42321]
![default](https://user-images.githubusercontent.com/38788538/51043342-824cde00-15cf-11e9-86e1-9ca1d2335139.png)

Other clients also see this after placing them in control of the mob.

**Comment by RedFoxIV** [comment]
Removing unintelligible DNA stopped this mess but the mutation is unremovable

**Comment by loserXD** [comment]
this happened to me before on tg and not on this blyat server, i think it was when i took mannitol when i was unintelligeble

**Comment by coiax** [comment]
Reproduced, it's real.
