### ISSUE TITLE
Lizards getting firebreath just by existing

### ISSUE THREAD

**Issue by BebeYoshi** [tgstation/tgstation#42333]
## Reproduction:
1. Be a Lizard
2. ?!?!?!
3. Breath fire even while cuffed

**Comment by Coconutwarrior97** [comment]
@Time-Green

**Comment by Time-Green** [comment]
On the plus side thus wasnt actually me for once

This was oranges making on_species_ loss call add_mutation for some reason

I’ll fix it as soon as I get to a computer
