### ISSUE TITLE
Jump boots cause you to go stupidly fast if you are in space and use them.

### ISSUE THREAD

**Issue by shellspeed1** [tgstation/tgstation#42330]
## Reproduction:

This bug occurs when you are in space only so far as I can tell. If you are moving through space and turn in a different direction then use jump boots, you will go insanely fast in that direction.

**Comment by ExcessiveUseOfCobblestone** [comment]
f-f-feature?

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/fe5acf25be49b7403bb6c74ba3a20e3240003537/code/modules/clothing/shoes/miscellaneous.dm#L211

I think this explains it well enough, I'd rather keep this interaction in so if any changes should be made let's just justify it with fluff.

**Comment by SpaceManiac** [comment]
the boots have a propulsion system, of course they work in space
