### ISSUE TITLE
Slime processor sucks slime trough a pane of glass

### ISSUE THREAD

**Issue by KetasDotepasto** [tgstation/tgstation#42334]
Issue reported from  Round ID: 100134 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Slimes were sucked into a processor through a pane of glass.

In the following setup, dead slimes are sucked into the processor through a pane of glass.
![tgbugbagilxenobio](https://user-images.githubusercontent.com/11960566/51073368-1f5f5380-1670-11e9-94ce-07dd9cc2ec02.png)

The slimes are placed in the tile that is exposed to space.

**Comment by ATH1909** [comment]
Huh, that's actually a pretty neat/cool setup; I might try to replicate it at some point.

Still, yeah, this is probably a bug.

Then again, the console teleports slimes... It wouldn't be much of a stretch to say that the processor teleports them too (although you should then change the flavor text for the sucking/teleporting of slimes done by the processor).

**Comment by bgobandit** [comment]
directional window memes again

**Comment by fludd12** [comment]
Personally, I feel this is more of an `accidental feature`, but I won't strongly oppose fixing it.

**Comment by Sealed101** [comment]
relevant code:
https://github.com/tgstation/tgstation/blob/aff9cf1b434c7a95d156ea20108d8b2bc015083d/code/modules/food_and_drinks/machinery/processor.dm#L205-L224

it doesn't check whether the slime can "step" onto the processor's tile

also if possible, it should probably not have to go over any slimes inside the processor at all; it's picking them up in `range()` and continuing over them, seems excessive
