### ISSUE TITLE
Oragami Folding Not Retained on Death

### ISSUE THREAD

**Issue by Hanador** [tgstation/tgstation#42331]
So uh took oragami as a meme. Got murdered in the halls after shredding the book in the recycler.
Got cloned. Didn't keep my paper folding skills and sent to perma. Is this working as intended? I thought all the stuff you learned from books was kept when you got cloned.

**Comment by coiax** [comment]
Definitely a bug. I'll look into it.

**Comment by dragomagol** [comment]
RIP cloning
