### ISSUE TITLE
Hypnotic Flash isn’t Balanced at All

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#42346]
Theres absolutely 0 point in buying the brainwashing surgery disk when you can just buy hypno flash for 2 more tc, and just brainwash half the station. Its unfair and unbalanced.

**Comment by PKPenguin321** [comment]
balance complaints do not go on github. they belong here: https://tgstation13.org/phpBB/viewforum.php?f=10

**Comment by wesoda25** [comment]
Scree
