### ISSUE TITLE
stamina damage stuns based off of your total damage rather than stamina

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42347]
if you're at 60 brute damage, get hit by a single disabler beam, you're stunned. didnt work like this in the past.

**Comment by PKPenguin321** [comment]
>didnt work like this in the past.

it literally has ever since we added disablers to sec

**Comment by k-k-karma** [comment]
it did work like this in the past you idiot

**Comment by BebeYoshi** [comment]
It does makes sense though, imagine someone all fucked and they get even more exhausted, they wouldn't be able to hand it and would fall. But again SS13 doesn't make sense at all so it may not be intented?

**Comment by nicbn** [comment]
Working as intended

**Comment by 81Denton** [comment]
Should be caused by this:

https://github.com/tgstation/tgstation/blob/94ad031c569dd57f8b47268cf9c59c78fa9633e1/code/modules/mob/living/carbon/carbon.dm#L547-L555

**Comment by ATH1909** [comment]
Why not just make stamina damage paralyze you only while your stamina damage+your normal damage is enough to put you into crit (and not for 10 seconds after that is no longer true)? Does that break stuff due to stamina regen being pretty fast or something?

**Comment by imsxz** [comment]
can’t recall it working like it ever before, guess I’ve only started noticing it recently with the other stamina issues
