### ISSUE TITLE
Snappop's (Clown Shuttle) Chasms are broken

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#42356]
Poor Snappop shuttle...

**Comment by ATH1909** [comment]
Would you mind elaborating on this a bit more?

**Comment by Shadowflame909** [comment]
Specifically, there you go.

**Comment by Shadowflame909** [comment]
Whatchu talkin bout Time-Green

**Comment by Time-Green** [comment]
the moment a shuttle arrives or leaves it instantly becomes a real chasm for one second and kills everyone on it

**Comment by Shadowflame909** [comment]
Epic Prank. But its a bug and is not what the shuttle is about

**Comment by MimicFaux** [comment]
They were originally real chasms. When was the _fun_ removed?

**Comment by Shadowflame909** [comment]
They still half-work. As Time-Green said, it's just buggy.

**Comment by kriskog** [comment]
Seen these working lately, still an issue?

**Comment by kriskog** [comment]
Actually, dupe of #42160
