### ISSUE TITLE
Pugs are classified as corgis when pet

### ISSUE THREAD

**Issue by zeroisthebiggay** [tgstation/tgstation#42361]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
>PET PUG
>[THIS HAPPENS](https://i.gyazo.com/f4e6d05767812a8bb517aeebe917a7a3.png)
>SCREAM BECAUSE PUGS ARE NOT CORGIS

**Comment by PKPenguin321** [comment]
Pugs shouldn't give the moodlet because they ugly
