### ISSUE TITLE
Extremely long ash storms

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#42367]
Issue reported from  Round ID: 100268 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Ash storm occured before the shuttle was called. By round end 15 minutes later it had not subsided.  This seems extremely long and and detrimental to enjoyable gamplay.

**Comment by SpaceManiac** [comment]
Nothing in the runtime log that is obviously related. The intended maximum duration of ash storms is 3 minutes (30s windup + 2m effect+ 30s wind-down).

**Comment by Dennok** [comment]
Still issue?
