### ISSUE TITLE
Lings get an instant revive

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#42360]
Repro steps:
- Become a ling
- Die
- Use reviving stasis
- When the stasis finishes, it BOTH changes your stasis button to the revive button AND revives you, letting you come back to life while keeping the revive button. *It should not be auto reviving you when the stasis finishes*
- You can now press the revive button at any time to instantly revive again

**Comment by GuyonBroadway** [comment]
Suggested fix. Delete lings and never look backml.

**Comment by ExcessiveUseOfCobblestone** [comment]
cursed creatures

**Comment by wesoda25** [comment]
Do the hippie fix on lings where they can’t revive

**Comment by GuyonBroadway** [comment]
Lings only cannot revive from fully dead but they can last resort so dying still has a penalty.


Also when bugs like this popped up we disabled lings because nobody will misd them.

**Comment by PKPenguin321** [comment]
Stop bullying lings right the fuck now

**Comment by GuyonBroadway** [comment]
Looks like we got ourselves a dang dirty ling apologist boys!

**Comment by ExcessiveUseOfCobblestone** [comment]
didn't we just add ling action buttons they have to stay now lol

**Comment by 0d0be32b607ee4ecbc2358f3dd4a27de** [comment]
sounds like runtime error

should be not happening
