### ISSUE TITLE
Shapeshift Healing Formula Can Result In Insta-Death

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#42362]
## Round ID:
100248

## Testmerges:
#42246: 'Lowers CO2 fusion power and slightly bumps up nitryl' by granpawalton at commit 702294acd3

## Reproduction:
1. Join miner
2. Find mirror
3. Choose vampire race
4. Fall in chasm get some damage
5. Almost insta transform in to space bat
6. Die in bat form

I remember some fixes about insta heal due transforming with wizard spell not sure this is the problem.
In the past you was able to transform in to bat form and fly to station now you can't sadly.
So now you need space suit to survive this event. And i not even sure suit will help.

**Comment by wesoda25** [comment]
Feature. Bats have hardly any health and aren’t space proof.

**Comment by ExcessiveUseOfCobblestone** [comment]
Pride Mirror: Magic Mirror but you can only choose the extremely powerful races to survive instead of tame changes.

🤔

Anyways should probably make sure this is exclusive to the chasm/mirror and not "take enough damage and switching = insta ko"

**Comment by Shadowflame909** [comment]
@wesoda25 

Vampires turn into SPACE BATS not regular bats.

They should be space-proof.

**Comment by ATH1909** [comment]
This should be fixed ASAP; I've already seen a DIO wizard die from shapechanging into a bat while not at full health.

Make the bat's health be proportional to your health before transforming; if you're at 50% health (not counting your crit health), the bat should be at 50% health, not dead because its max health is less than 50.

**Comment by ExcessiveUseOfCobblestone** [comment]
Simple fix:
https://github.com/tgstation/tgstation/blob/2d239fe867df9f113629a6ec62e72de310ba4197/code/modules/spells/spell_types/shapeshift.dm#L59

```DM
if(convert_damage && caster.health <= 0)
    to_chat(caster, "Oh no caster-chan, you will die if you shapeshift now uwu~~!")
    return
```

https://github.com/tgstation/tgstation/blob/2d239fe867df9f113629a6ec62e72de310ba4197/code/modules/spells/spell_types/shapeshift.dm#L106-L108

Then change maths here so it doesn't delete you on change

also https://github.com/tgstation/tgstation/blob/2d239fe867df9f113629a6ec62e72de310ba4197/code/modules/spells/spell_types/shapeshift.dm#L158-L159

wonder if this can heal you lol

**Comment by ATH1909** [comment]
> Simple fix:
> [tgstation/code/modules/spells/spell_types/shapeshift.dm](https://github.com/tgstation/tgstation/blob/2d239fe867df9f113629a6ec62e72de310ba4197/code/modules/spells/spell_types/shapeshift.dm#L59)
> 
> Line 59 in [2d239fe](/tgstation/tgstation/commit/2d239fe867df9f113629a6ec62e72de310ba4197)
> 
>   
> ```dm
> if(convert_damage && caster.health <= 0)
>     to_chat(caster, "Oh no caster-chan, you will die if you shapeshift now uwu~~!")
>     return
> ```
> 
> [tgstation/code/modules/spells/spell_types/shapeshift.dm](https://github.com/tgstation/tgstation/blob/2d239fe867df9f113629a6ec62e72de310ba4197/code/modules/spells/spell_types/shapeshift.dm#L106-L108)
> 
> Lines 106 to 108 in [2d239fe](/tgstation/tgstation/commit/2d239fe867df9f113629a6ec62e72de310ba4197)
> 
>  if(source.convert_damage) 
>  	var/damapply = (stored.maxHealth - (stored.health + stored.maxHealth)/2) //Carbons go from -100 to 100 naturally, while simplemobs only go from 0 to 100. Can't do a direct conversion. 
>  	shape.apply_damage(damapply, source.convert_damage_type) 
> Then change maths here so it doesn't delete you on change
> 
> also
> 
> [tgstation/code/modules/spells/spell_types/shapeshift.dm](https://github.com/tgstation/tgstation/blob/2d239fe867df9f113629a6ec62e72de310ba4197/code/modules/spells/spell_types/shapeshift.dm#L158-L159)
> 
> Lines 158 to 159 in [2d239fe](/tgstation/tgstation/commit/2d239fe867df9f113629a6ec62e72de310ba4197)
> 
>  var/damapply = (shape.maxHealth - 2*shape.health) //Since we halved incoming damage, double outgoing. 
>  stored.apply_damage(damapply, source.convert_damage_type) 
> wonder if this can heal you lol

Or, again, just make it proportional to your current and target forms' max healths (like how many people, including me, thought it worked before seeing this PR).

**Comment by ExcessiveUseOfCobblestone** [comment]
Humans don't use maxhealth right though, that's the entire issue and why the math is like that in the first place.

You HAVE to account for the -health possibility, but you don't have to account for it on the formula. A preliminary check to account for it means you can then make the formula as you mentioned.
