### ISSUE TITLE
Taking a picture of somebody on a meat hook turns them right-side up

### ISSUE THREAD

**Issue by Malkraz** [tgstation/tgstation#42369]
Issue reported from  Round ID: 100287 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

https://puu.sh/CwXfn/43b15589f3.png

**Comment by wesoda25** [comment]
Goes for anyone lying down. Makes taking pictures of bodies kinda hard.

**Comment by 81Denton** [comment]
is that the fabled meatspin

**Comment by bgobandit** [comment]
gotta pose man

**Comment by SuperNovaa41** [comment]
No longer an issue
