### ISSUE TITLE
Ethereal get burn damage insted of brute when fist fight

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#42371]
## Reproduction:
1. Join as Ethereal
2. Fist fight human
3. Get burn damage instead of brute

Not sure this is bug or not. But seems to be strange when you get brute from all other sources and burn from fistfight.

**Comment by erwgd** [comment]
Definitely a bug. Ethereals are meant to deal burn damage through punching, but what currently happens is the other way around:
* An ethereal deals brute damage when punching anyone other than an ethereal. 
* Anybody punches an ethereal to deal burn damage to them. 
* Ethereals may burn through punching only when they punch themselves. 

Someone commented in #40995 about this, see kriskog's comment [here](https://github.com/tgstation/tgstation/pull/40995/files#r236529396).

**Comment by SpaceManiac** [comment]
@Qustinnus
