### ISSUE TITLE
simple mobs window/grille/table destroy system

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/tgstation#4237]
if any simple mob is trying to attack someone, the mob will break any tables, windows and grilles. The intention of this is to grant the mob a path to get to their target.
Now, mobs can hit all these structures at the same time around them, at the same tick, spamming a lot and not making a lot of sense.
Structures that are not blocking their path towards their victim will also be destroyed if they are near the mob when the ticker of life() hits.
There are times when the mob is already attacking their victim and they will still try to destroy structures around them.

It makes less sense with ranged mobs, they start destroying windows around them in anger while shooting.

**Comment by Jalleo** [comment]
@phil235 didn't someone make a PR quite a while back which changed the behavior of this now?

**Comment by phil235** [comment]
I don't think so, the DestroySurroundings() proc hasn't been changed in years.

**Comment by ShizCalev** [comment]
Fixed.
