### ISSUE TITLE
Skewium and Rotatium bug?

### ISSUE THREAD

**Issue by bannerfag** [tgstation/tgstation#42374]
Issue reported from  Round ID: 100304 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

I'm not sure which of the two caused it, but some guy fed me 50 u of skewium and 20u of rotatium and killed me while in-effect. The effect persisted even as a ghost and it hasn't gone away since, even affecting ghost UI

**Comment by kriskog** [comment]
ouch
