### ISSUE TITLE
If someone selects the NEET quirk, every latejoin with the same job gets welfare

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#42387]
## Reproduction:
1. Spawn as NEET assistant: start with 25$ in account, 25$ payout
2. Respawn as assistant but without NEET: get 125$ in account, still get welfare

@Qustinnus is this some kind of social commentary

**Comment by Qustinnus** [comment]
ugh i hate goofconomy

**Comment by OverlyGeneric** [comment]
Consider it the invisible hand of NT paying you to stand around that walking biohazard.

a feature, not a bug.
