### ISSUE TITLE
cursed heart turns your screen red even after it's not in you

### ISSUE THREAD

**Issue by zeroisthebiggay** [tgstation/tgstation#42384]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
>eat cursed heart
>oh god oh fuck get it out
>get surgery
>take cursed heat out right as you need to pump it
>everything turns red
>cursed heart comes out
>still everything is red
>get new heart in
>r e d
>you now see permanently with a shade of red
>try to put cursed heart back in to pump it
>die suddenly

**Comment by OverlyGeneric** [comment]
the shade of red is the blood of your enemies or just tomato sauce.

however, the part where you put in your heart and immediately dying is an actual bug.

**Comment by Whoneedspacee** [comment]
Funnily enough if it’s set to some sort of timer that isn’t being reset wouldn’t putting it in someone else kill them instantly?

**Comment by zeroisthebiggay** [comment]
> Funnily enough if it’s set to some sort of timer that isn’t being reset wouldn’t putting it in someone else kill them instantly?

>get it out
>put it back in
>it goes in
>YOU DIE IF YOU DON'T PUM--
>die
>nanites defib me
>die
>get defibbed
>die
>get revival surgery
>die
>get defibbed
>die
>die while dead
>create a gravitational singularity due to dying while dead
