### ISSUE TITLE
dismembered felinid heads have no cat ears

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42397]
how can i immerse myself while doing gods work if the beheaded catpeople magically lose their ears?

**Comment by PKPenguin321** [comment]
genetically engineered catgirl ears are held up by contorted muscles in the arms. when the head is detached from the body, these horrifically grotesque mutant-muscles are severed, and the ears fall down flat. this is why they are not visible on the severed head; they are actually pressed up flatly against the top of it.

not a bug. please close

**Comment by Mooshimi** [comment]
Dupe of #32229
