### ISSUE TITLE
pirates showed up despite being paid off

### ISSUE THREAD

**Issue by zeroisthebiggay** [tgstation/tgstation#42398]
## Round ID:
#100392 (Sybil)

## Testmerges:
#42151: '[GOONETICS] Chromosomes' by Time-Green at commit 3ae4bb8bb3

## Reproduction:
The pirates did us a pirate and ran away with our money.
![image](https://user-images.githubusercontent.com/222630/51377414-b177b980-1abf-11e9-96ec-80fba6970d12.png)

**Comment by Therapist1** [comment]
Not a bug, they did what they wanted because pirates are free.

**Comment by Cyprex** [comment]
This is intended, if you wait too long with paying they will come no matter what.

**Comment by timothymtorres** [comment]
Looks intentional:

https://github.com/tgstation/tgstation/blob/ac6c89455dabbe759677a83f07e897dde6af22f8/code/modules/antagonists/pirate/pirate_event.dm#L50-L61
