### ISSUE TITLE
Unwrenched airtight flaps are invisible

### ISSUE THREAD

**Issue by JohnGinnane** [tgstation/tgstation#42400]
Issue reported from  Round ID: 100407 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

![image](https://user-images.githubusercontent.com/3355198/51341505-60e56980-1a89-11e9-9ec4-1f13ea397681.png)

**Comment by ShizCalev** [comment]
Ezfix

**Comment by SpaceManiac** [comment]
Duplicate of #42138
