### ISSUE TITLE
Rearranging of uplink removed the syndicate bundle from normal uplinks and popped it into the nuke exclusive category. Oops.

### ISSUE THREAD

**Issue by zeroisthebiggay** [tgstation/tgstation#42417]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
>get uplink
>look in badassery
>no syndicate bundle
>look in bundles
>no syndicate bundle
>aaaa
>look at code of recent rearrangement pr
>see that the syndicate bundle is now nukie exclusive (#42339)
>oops
@81Denton

**Comment by 81Denton** [comment]
I can confirm that it doesn't show up, I just have no idea why. After all, `/datum/uplink_item/bundles_TC` has no game mode restriction and `exclude_modes = list(/datum/game_mode/nuclear)` on the bundle itself means that it should show up in game modes that aren't nuclear emergency.

https://github.com/tgstation/tgstation/blob/9cf3c5bbf818c98d75f421a8980de0e16bd817fc/code/modules/uplink/uplink_items.dm#L176-L183

**Comment by SpaceManiac** [comment]
I made a mistake in my analysis. There are changes:

```diff
--- a   2019-01-19 16:32:16.324270200 -0800
+++ b   2019-01-19 16:32:32.784211600 -0800
@@ -1,8 +1,8 @@
 ---- parsing environment ----
-/datum/uplink_item/badass/bundle(17652)
+/datum/uplink_item/bundles_TC/bundle(17456)
 active_timers = null
 cant_discount = 1
-category = "(Pointless) Badassery"
+category = "Bundles and Telecrystals"
 comp_lookup = null
 cost = 20
 datum_components = null
@@ -11,7 +11,7 @@
 exclude_modes = list(/datum/game_mode/nuclear)
 gc_destroyed = null
 illegal_tech = 1
-include_modes = list()
+include_modes = list(/datum/game_mode/nuclear)
 item = /obj/item/storage/box/syndicate
 limited_stock = -1
 name = "Syndicate Bundle"
```

**Comment by 81Denton** [comment]
Now I feel dumb. Thanks for checking it out for me.
