### ISSUE TITLE
tgui broke

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#42418]
100443

![image](https://user-images.githubusercontent.com/222630/51412075-3940e080-1b1f-11e9-9bdb-20e51ed753fa.png)

**Comment by 81Denton** [comment]
I'm not getting any errors like that on revision b9f1ca56d43f21abf6172b99604d8b315a751474

**Comment by SpaceManiac** [comment]
Round 100443 was running 4de8066902e474cf38d62a5844925d5b48351d38, on which I was able to reproduce the problem. The fix was made in #42408. The servers just need to be updated.
