### ISSUE TITLE
Minor issue with coloring objects.

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#42416]
Issue reported from  Round ID: 100437 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

So, the ability to color objects with spraycans was just added to the game. Well, if you color a cable coil, and then place the cable coil(i.e. attempting to wire the solars or make cable art), it comes out as the original color instead of the altered one. I was told to make a bug report by one of the admins on the server after I adminhelped it in a blind fit of rage.

**Comment by Sealed101** [comment]
you were only wiring the coil stack item, not the resulting wire world object. that would be a separate feature. then again we've got like three wire colors and layers, and just spraycoating world object wires should work
