### ISSUE TITLE
Reflector/Emitter Relation

### ISSUE THREAD

**Issue by BlackyJacky** [tgstation/tgstation#42427]
Issue reported from  Round ID: 100471 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

Seems like the reflectors in the SM area on metastation are not willing to properly reflect the emitter beams 
and choose to get hit instead. I've encountered that bug thrice by now in 4 months of playtime, that's not a very high number but it usually ended by either a  restart vote or very early shuttle call.

**Comment by nicbn** [comment]
Did the problem happen in the round which ID was reported?

**Comment by BlackyJacky** [comment]
uh, what do you mean exactly?

**Comment by FloranOtten** [comment]
Instead of reflecting the emitter beams, the reflectors just get hit. It's the same as if the reflector was a closet.
