### ISSUE TITLE
Plasma Cutter - Single Block?

### ISSUE THREAD

**Issue by TrueWOPR** [tgstation/tgstation#42426]
Problem Description: Plasmacutter and Advanced plasma cutter only cut a single rock block at a time on Boxstation after the 1/18/19 update

What did you expect to happen: I expected the plasma cutter to cut 5 blocks, and the advanced to cut 10.

What happened instead: the plasmabolt stopped at the first block.

Why is this bad/What are the consequences: Makes deep-mining much more difficult to achieve.

Steps to reproduce the problem: It just seems to happen as if it was an unmarked update rather than a 'bug', it was affecting the other miners too.  Two games, three miners, 6 cutters used between us.

Server: /tg/Station 13 Bagil

Revision: Master commit: b9f1ca56d43f21abf6172b99604d8b315a751474
Local commit: d6b3dc5a3f7469cf31f9ca6a2f6c2e173c97196e
Server tools version: /tg/station 13 Server v3.2.5.1

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Antags were blobs if that makes a difference.  Again the station was BoxStation.

Thanks for helping us out!

**Comment by DaxDupont** [comment]
Can confirm this is a pretty big issue.

@Cyberboss can you pin this issue please

**Comment by 4dplanner** [comment]
@kevinz000

**Comment by FloranOtten** [comment]
This is a major issue. Mats are much harder to come by and plasmacutters are basically worthless now.

If this was an intentional update, 3 steps for the person who did this:

1. Undo this change
2. Put a pencil between your middle finger and the 2 fingers adjacent to it
3. Grab the 3 fingers and squeeze really hard

**Comment by Shadowflame909** [comment]
Rip Mats

**Comment by Angustmeta** [comment]
Tbh it's pretty fun to mine with KA cooldown+aoe mods instead, dual wielded with bugged plasma cutter.

**Comment by xeroxemnas** [comment]
How do you fuck up this badly reee.

**Comment by 4dplanner** [comment]
> How do you fuck up this badly reee.

t. no contribs

**Comment by Shardj** [comment]
Also affects emitters, causing reflectors to not work. I'm sure that's already known by most of you though
