### ISSUE TITLE
Projectile types that shatter mirror shields are inconsistent

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#42421]
Beanbag slug projectiles have damage = 5 and stamina = 80, and cannot shatter mirror shields.
Disabler projectiles have damage = 35 and damage_type = STAMINA, and can shatter mirror shields. 
(Projectiles need >30 damage to be able to shatter)

 The code issue seems to be due to there being two ways to specify stamina damage—which makes me think that this is an oversight.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/ccadcf61d3d383191d950a8ac5a350b0213ba9e9/code/modules/antagonists/cult/cult_items.dm#L931

Close, it's because it doesn't look at WHAT type of damage it does, just what the numerical value is.

**Comment by ExcessiveUseOfCobblestone** [comment]
Also really...

https://github.com/tgstation/tgstation/blob/ccadcf61d3d383191d950a8ac5a350b0213ba9e9/code/modules/antagonists/cult/cult_items.dm#L941-L942

**Comment by py01** [comment]
I can make a fix, though I'm not sure- Should beanbag slugs shatter, or disablers not shatter?

**Comment by ExcessiveUseOfCobblestone** [comment]
I would just add a secondary check to make sure the damage is brute/burn.

You can't asphyxiate a mirror, you can't poison a mirror, and you can't tire a mirror out.

**Comment by MASMC** [comment]
:floyddab:
