### ISSUE TITLE
Genetic sequence scanner has no sprite

### ISSUE THREAD

**Issue by Manu9123** [tgstation/tgstation#42438]
Geneticist's genetic sequence scanner has no sprite I can give an idea for the sprite actually lookin like an healh analyzer but screen colour blue dark

**Comment by Time-Green** [comment]
Same as #42188 
The sprite works just fine for me. Are you on a downstream that maybe removed the sprite while fixing conflicts or something?

**Comment by Manu9123** [comment]
idfk

**Comment by Time-Green** [comment]
thanks

**Comment by 4dplanner** [comment]
Ban downstreamers who make issue reports when

**Comment by SpaceManiac** [comment]
@Manu9123 what server were you playing on when this happened

**Comment by kriskog** [comment]
This doesnt seem to be an issue
