### ISSUE TITLE
Exosuit beacons disappear when ioned

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#42435]
Noticed during a mech rampage round that any form of ion effecting any of the exosuits will cause them to just disappear from existence.

**Comment by GunHog** [comment]
Responsible code below:
https://github.com/tgstation/tgstation/blob/caf4c27940d2cabd8b417dfb345f114168f1dd75/code/game/mecha/mecha_control_console.dm#L74-L77

**Comment by PKPenguin321** [comment]
in other words, this is intentional

**Comment by GunHog** [comment]
Well, beacons can generate EMPs themselves, when activated through the mecha console. That code is perhaps designed with that in mind, so that a beacon is single use. I cannot say if it was intended or not that beacons get destroyed by exterior EMPs.

**Comment by carshalash** [comment]
I was more reporting the exterior emp bit.

**Comment by kriskog** [comment]
beacon behaviour changed in  #44452
