### ISSUE TITLE
Clock Cultist Borgs that Cast Abscond Get a Permanent Purple Tint to Their Screen

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#42439]
As the title. It's really annoying, especially since it tints your screen a dark shade of purple that makes it quite hard to see.

Do note that I don't think that Reebe existed on/in the round that I (and others, IIRC) encountered this bug in.

**Comment by improvedname** [comment]
Reebe is disabled

**Comment by k-k-karma** [comment]
if Reebe is disabled and you try to teleport to it, the purple does not go away

**Comment by ATH1909** [comment]
> if Reebe is disabled and you try to teleport to it, the purple does not go away

This.

And yeah, I probably should have mentioned that abscond didn't actually take me anywhere when I cast it.

Maybe give clock cult borgs something else to replace it? Maybe something that lets them make conversion runes?

**Comment by necromanceranne** [comment]
It is the same with clock cultists casting abscond with no Reebe. Basically permanently turns your vision an A E S T H E T I C purple.

**Comment by SpaceManiac** [comment]
Round ID? If there's a runtime involved it'd make the fix easier to determine
