### ISSUE TITLE
Large amount of acid on screen caused client to slow down a lot

### ISSUE THREAD

**Issue by Gouty** [tgstation/tgstation#42454]
Issue reported from  Round ID: 100557 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512.1454

Acid causing a lot of client side lag

![image](https://user-images.githubusercontent.com/12712558/51440082-cf5d3e00-1cba-11e9-89de-7c97a4a44dd2.png)

When there were a large number of acid sprites in view it caused camera movements, sprite animations/movements to go very juddery and my CPU usage was increased significantly.

**Comment by DaxDupont** [comment]
I've reported this before, but they couldn't reproduce it

**Comment by bgobandit** [comment]
maybe don't throw acid at your screen then

**Comment by SpaceManiac** [comment]
Those acid sprites look unreasonably solid, are there like 100x stacked at each location?

**Comment by Gouty** [comment]
I couldn't tell if it was multiple stacks as I was AI so no way to more closely inspect.

**Comment by YakumoChen** [comment]
mass gibs is also laggy as shit

**Comment by CPTANT** [comment]
Just noticed this myself, it's pretty bad. I was AI, so that might have something to do with it?

**Comment by timothymtorres** [comment]
Tested this today.  The amount of overlays that are attached to an object when it gets covered with corrosive acid is just one now.  Not sure when this was fixed, but this issue is done.
