### ISSUE TITLE
Papers can be duplicated by folding them

### ISSUE THREAD

**Issue by Djauhne** [tgstation/tgstation#42468]
Issue reported from  Round ID: 100614 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Not sure how to report an issue and if it's something worth to be reported but here, I tried to search but I don't thing it was already signaled: 
If you alt+click on a paper quickly two (or more) time, it will result in two separate paper planes.
It works whether the paper is in hand, offhand, or on the ground. I asked to other players if they could see the duplicates, and yeah, it's not client-side.
Can be repeated indefinitly, both papers retain the original message once unfolded.

English is not my first language, I hope it's clear enough.

**Comment by ATH1909** [comment]
Forbidden APM techniques
