### ISSUE TITLE
Airlock at xenobio breakable

### ISSUE THREAD

**Issue by Shardj** [tgstation/tgstation#42466]
Found this last night, don't know the round id but it's easy enough to reproduce. If someone tries to cycle the locks on the xenobio doors while someone is standing in the open one, it breaks the airlock cycler effectively trapping those inside.

This was on metastation

**Comment by AnonymousNow** [comment]
Also likely applies to other cycling airlocks. Since we now have an airlock pairing system, it might be an idea to retire the cycling airlock panel, or better yet, set its functionality to enable lockdowns from within for self-quarantine situations.
