### ISSUE TITLE
Labor Camp Teleporter + Plasmeme = Death

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#42472]
When a plamaman is teleported to the gulag they're given the usual clothes, aka not an environment suit. They quickly burn to death after teleportation.

**Comment by tralezab** [comment]
feature, and also my favorite way to execute plasmamen

**Comment by Shadowflame909** [comment]
oversight?

**Comment by Trilbyspaceclone** [comment]
var/jumpsuit_type = /obj/item/clothing/under/rank/prisoner
	var/shoes_type = /obj/item/clothing/shoes/sneakers/orange
	var/obj/machinery/gulag_item_reclaimer/linked_reclaimer
	var/static/list/telegulag_required_items = typecacheof(list(
		/obj/item/implant,
		/obj/item/clothing/suit/space/eva/plasmaman,
		/obj/item/clothing/under/plasmaman,
		/obj/item/clothing/head/helmet/space/plasmaman,
		/obj/item/tank/internals,
		/obj/item/clothing/mask/breath,
		/obj/item/clothing/mask/gas))
Its a bug it seems

**Comment by SouDescolado** [comment]
```
/obj/machinery/gulag_teleporter/proc/strip_occupant()
	if(linked_reclaimer)
		linked_reclaimer.stored_items[occupant] = list()
	var/mob/living/mob_occupant = occupant
	for(var/obj/item/W in mob_occupant)
		if(!is_type_in_typecache(W, telegulag_required_items) && mob_occupant.temporarilyRemoveItemFromInventory(W))
			if(istype(W, /obj/item/restraints/handcuffs))
				W.forceMove(get_turf(src))
				continue
			if(linked_reclaimer)
				linked_reclaimer.stored_items[mob_occupant] += W
				linked_reclaimer.contents += W
				W.forceMove(linked_reclaimer)
			else
W.forceMove(src)
```
I think the problem may be on `&& mob_occupant.temporarilyRemoveItemFromInventory(W)`. I think it checks each item to check if it is on the list and then it sees if it succeeds to remove them(It won't trigger for things that cannot be removed, maybe things like barnyard?). I suppose this should be new If and not &&
