### ISSUE TITLE
Blood spears and mirror shields can be used by noncultists

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#42474]
These items have no code checks to apply penalties to noncult users.

**Comment by wesoda25** [comment]
Mirror shield penalty is that the hallucinations attack you

**Comment by ATH1909** [comment]
And blood spears don't harm cultists when thrown at them.

**Comment by wesoda25** [comment]
Yo what even are blood spears

**Comment by Angustmeta** [comment]
Blood spears are made with blood rites, costing 150 charge if I recall. They can be dual wielded like spears, dealing pretty low damage. They can also be thrown at enemies, stunning them a very short moment (like 2 seconds?). Stunning them deletes the spear.

**Comment by anconfuzedrock** [comment]
Culties can catch mirror shieldz too so
