### ISSUE TITLE
Instantly detonating ied

### ISSUE THREAD

**Issue by Shardj** [tgstation/tgstation#42483]
Issue reported from  Round ID: 100680 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

An ied went off as soon as i activated it in hand, zero second cooldown.

**Comment by Therapist1** [comment]
that’s the risk of using improvised explosives

**Comment by Shardj** [comment]
Oh this isn't a bug? The wiki said 3-8 seconds

**Comment by Shardj** [comment]
That's good to know for next time i guess, I had about 5 on me so they all blew up because of it
