### ISSUE TITLE
Bubblegum sprite covers the entire 3x3 area

### ISSUE THREAD

**Issue by 4dplanner** [tgstation/tgstation#42480]
This means you can't click on things in the squares surrounding him

**Comment by Whoneedspacee** [comment]
good

**Comment by 4dplanner** [comment]
>:( giant invisible blocker is not good

**Comment by Whoneedspacee** [comment]
he got them big arms

**Comment by 4dplanner** [comment]
![bubblebig](https://user-images.githubusercontent.com/26886304/51575516-499fe500-1eaa-11e9-8470-7192a3774c07.png)

**Comment by SpaceManiac** [comment]
intended
```dm
	mouse_opacity = MOUSE_OPACITY_OPAQUE // Easier to click on in melee, they're giant targets anyway
```
