### ISSUE TITLE
Escape on the shuttle or an escape pod alive and without being in custody is Successful even if in custody.

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#42485]
Issue reported from  Round ID: 100692 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

As the title says. Had a traitor cuffed and in a chair on the meta station escape shuttle. They got a Successful on their objective to escape without being in custody.

**Comment by SpaceManiac** [comment]
Had the floor perhaps been replaced with something other than standard red tiling?

Yes, this is actually how it works.

**Comment by Hathkar** [comment]
Seriously? 
I do think the floor tile had been replaced with a cult floor tile.

**Comment by zxaber** [comment]
Why not link it to whether the person is in handcuffs or otherwise bound?

**Comment by timothymtorres** [comment]
This no longer checks the tile directly and there is now a area subtype for shuttle brig.

```
	// In custody (shuttle brig) does not count as escaping
	if(!current_area || istype(current_area, /area/shuttle/escape/brig))
		return FALSE
```

@Sadboysuss you can close this

**Comment by Sadboysuss** [comment]
ok ig
