### ISSUE TITLE
White ship is unable to travel to the station's z-level on Donutstation.

### ISSUE THREAD

**Issue by LegendaryMister151** [tgstation/tgstation#42498]
The white ship is unable to dock at station or even travel to the station's z-level on Donutstation.

![image](https://user-images.githubusercontent.com/46329759/51653974-c5119d00-1f63-11e9-8721-10c23b060cde.png)

**Comment by ExcessiveUseOfCobblestone** [comment]
prob no docking ports

**Comment by daklaj** [comment]
why would any ship dock at that shithole

**Comment by 81Denton** [comment]
@MMMiracles If you don't mind, the station would benefit from a docking port for the white ship
