### ISSUE TITLE
Stealth Cats

### ISSUE THREAD

**Issue by Gouty** [tgstation/tgstation#42518]
Issue reported from  Round ID: 100835 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

People on medical records listed as Felinid but appearing human due to a lack of cat ears and tail

![image](https://user-images.githubusercontent.com/12712558/51754735-fe0d5700-20b4-11e9-9f69-f2a78051f299.png)

I have only seen it with one player, but on every shift I've seen them on this has been the case.

Sometimes the medical records have shown them with the tail and ears, but I have never seen them in game with them.

How am I supposed to know who to discriminate against?  You could be living next to a degenerate and not even know it

**Comment by FuryMcFlurry** [comment]
you can turn off your tail and ears within the character creation menu.

**Comment by Gouty** [comment]
Wew, not a bug then? seems like an oversight, Tails I can understand not having (Manx cats exist after all) but they should be made to have ears on round start

**Comment by HomocidlePancakes** [comment]
I actually saw that on sibil. Was warden on lowpop and perma'd an atmostech for stealing the spare.
When i checked his sec record it said he was a felenid and had a tail and ears on his picture but his charachter did not.

**Comment by necromanceranne** [comment]
I noticed that guy as the AI. He would have been very, VERY surprised had he drawn my ire.

Except he did because I was malf and he was my target.

**Comment by WaterStBlues** [comment]
Force all felinid traits on those who choose to sin in the first place

**Comment by optimumtact** [comment]
this isn't a bug
