### ISSUE TITLE
Permanently zoom out until you don't want to anymore.

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#42512]
Reporting client version: 512

1) move one of your icons on the top of the screen closer to the bottom
2) use the navigation console to place the ship somewhere, it zooms out and the moved icon moves even further towards the bottom of the screen
3)  move the icon back to its original spot and leave camera view

you are now zoomed out without being in the console view or using a sniper. Move the icon to its original place to end the effect. 100% reproduction rate.

![bug1](https://user-images.githubusercontent.com/46474741/51722640-e7122a80-200a-11e9-94c4-8c91642485a0.PNG)
Normal screen.
![bug2](https://user-images.githubusercontent.com/46474741/51722641-e7122a80-200a-11e9-9494-a113e0c9d800.PNG)
moved icon.
![bug3](https://user-images.githubusercontent.com/46474741/51722642-e7122a80-200a-11e9-8e51-6e7b5caef10b.PNG)
Zoom out. Circled the new position of the icon.
![bug4](https://user-images.githubusercontent.com/46474741/51722643-e7122a80-200a-11e9-97e7-e04fc287e368.PNG)
Put it back.
![bug5](https://user-images.githubusercontent.com/46474741/51722644-e7aac100-200a-11e9-8e09-b3ab7df227a9.PNG)
Still zoomed out! Icon is at the top of the screen now.

**Comment by Sealed101** [comment]
can no longer reproduce
