### ISSUE TITLE
Psychic Link gained after being implanted when linked to a hivemind does not do anything at all.

### ISSUE THREAD

**Issue by KomradeSpectre** [tgstation/tgstation#42514]
Issue reported from  Round ID: 100806 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

![image](https://user-images.githubusercontent.com/12734451/51724875-61ec3d00-202d-11e9-8599-497dccfdc3c6.png)

Before the screenshot was taken above, I had been mind-controlled by a hivemind and shot a load of dudes up during that. Immediately after being controlled, I ran to the brig for an implant, which gave me the 'Psychic Link' pinpointer that never once pointed in any direction despite the hivemind (which I found out the identity of from the end of round screen) being completely active the entire round and moving around. Now Hivemind has even LESS counterplay to it if you can't even have any indication of who is the hivemind since the pinpointer doesn't work at all! They can simply just break implants every now and then, and if you implant people more, just break even more and you won't know who did it at all now.

**Comment by Hathkar** [comment]
Can confirm I have the same issue. Pinpointer is just a ?

**Comment by imsxz** [comment]
@Kierany9 

pinpointer thingy doesnt really work at all. also my chat was getting spammed to hell with messages during both the "you detect an enemy hive using your body as a vessel" and "you feel yourself losing a vessel" or something. The number of vessels also didn't seem to lower despite being notified about losing one?

Finally, network invasion said that it detected other hiveguys, but it didn't say who and the pinpointer thing didn't update.

**Comment by Kierany9** [comment]
this is the last time i trust maintainer changes without testing them
