### ISSUE TITLE
Magical monkeys

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#42521]
Items snatched by monkeys seem to dissapear, sometimes. i once had a scanner snatched, tried to point it but im not pointing at anything

**Comment by adamkad1** [comment]
> Items snatched by monkeys seem to dissapear, sometimes. i once had a scanner snatched, tried to point it but im not pointing at anything.

**Comment by SpaceManiac** [comment]
Duplicate of #37645
