### ISSUE TITLE
Transcendant Olfaction makes you extremely grossed out

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#42547]
I got a bad smell, ran to a shower within a minute and was stuck chainvomiting for 10 minutes and being unable to move after having fully showered

**Comment by PKPenguin321** [comment]
You didn't run fast enough. Get clean as soon as you start seeing the messages
I could dial it back a bit, though

**Comment by Time-Green** [comment]
im cool with it fucking you up real fast but maybe an upper limit to how disgusted you can get might be nice so you dont end up chain vomitting for literally the whole round

**Comment by PKPenguin321** [comment]
It's definitely not literally the entire round (I tested this) but sure, I could put a soft cap on it
