### ISSUE TITLE
BarBug

### ISSUE THREAD

**Issue by AdamBlue9000** [tgstation/tgstation#42545]
Issue reported from  Round ID: 100931 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Basically, playing as bartender, I can only access my liquor machine once. All other machines work fine, it's just the liquor machine. I can access it again if I open and close the game window or 'reconnect', but it's literaly just the liquor machine. Thanks.

**Comment by wesoda25** [comment]
I feel this isn't exclusive to liquor machine, I get this shit often with chemistry related things. The pop ups are just shitty and break sometimes I guess.

**Comment by WaterStBlues** [comment]
Can confirm that this is just the shit nature of tgui

**Comment by YakumoChen** [comment]
just reset the connection through the file menu

**Comment by actioninja** [comment]
Not using the same ui system anymore, but potentially related to #47755 so closing as dupe and linking there
