### ISSUE TITLE
defective clones unable to talk or me?

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#42543]
Issue reported from  Round ID: 100927 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Yeah, I was defective cloned and couldnt me or speak. They tried surgery, genetics, and mutadone and nothing changed anything. Seems like a big issue, but I have no way to reproduce it that I know of.

**Comment by Gousaid67** [comment]
which Species were you?
