### ISSUE TITLE
suiciding with a soda can (and also presumably signallers) but not dying renders your brain and body unusable anyways

### ISSUE THREAD

**Issue by zeroisthebiggay** [tgstation/tgstation#42559]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
>be going to be borged or something that requires a functioning brain
>suicide with a soda on the way while being over the "boomer" age / eat a signaller
>S I P P / N O M
>don't die because of this
>get debrained
>your old body is now shown as a suicide and your brain is unusable despite not dying directly from the suicide

**Comment by DfourC** [comment]
That's just the sacrifice you make in exchange for taking the BIG SIPP

**Comment by nicbn** [comment]
Suiciding should make brains unusable anyway, if it means you don't want to be cloned it also means you don't want borging
