### ISSUE TITLE
every tgui window stopped working 

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#42566]
101003
http://take.ms/Hx90n
every tgui window would look like in screenshot

**Comment by wesoda25** [comment]
You have to just close the window/maybe reconnect when you get that issue. 

Works for me at least.

**Comment by Electronics** [comment]
^ or try and find different computer/machine which sometimes resets the issue for me.

**Comment by Dennok** [comment]
Still issue?

**Comment by jlsnow301** [comment]
Closing this due to 
- general inactivity 
- lack of specifics
- lack of reproduction
