### ISSUE TITLE
Push Cuffed People even on help intent

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#42570]
Round: 101005

I reported this before, but it couldn't be replicated and I didn't include a round ID so it was closed.

Anyways I was warden, had someone cuffed, I was on help intent, and yet I pushed them instead of swapping places.

**Comment by Gousaid67** [comment]
is it possible the prisoner was on an intent other than help? or does cuffing someone bypasses that normally?

**Comment by wesoda25** [comment]
It would be bypassed normally. I tried to ask them what intent they were on but they didn’t answer.

**Comment by Gousaid67** [comment]
its possible they have the physically obstructive quirk, il test it.

**Comment by Gousaid67** [comment]
can confirm a handcuffed mob with the Physically Obstructive Quirk will get pushed instead of swapped.

**Comment by wesoda25** [comment]
So is that a bug or not? Seems pretty broken to me.

**Comment by Gousaid67** [comment]
i would say so, though maybe it is intended. Im not sure really.

**Comment by Gousaid67** [comment]
pinged @coiax, the guy who made he quirk. confirmed this is unintended, il get a fix PR up later for this.
