### ISSUE TITLE
Two souls in a body

### ISSUE THREAD

**Issue by MortoSasye** [tgstation/tgstation#42573]
Issue reported from  Round ID: 101008 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

-Be admeme. Take control briefly of player X body to check if it's from their part that they can't move.

-Leave the body, put player back inside of it.

-Spawn yourself in CentComm to have your snowflake static name back. Find out you only see white shit everywhere, aghost. Notice the other ghost; surprise, it's the player X ghost as your static too, being removed from their body by force. 

-Wonder what the fuck is going on after putting them back once again in their body.

**Comment by Daxxed** [comment]
Protip: You can hit the “Restore ghost character” verb to get your currently selected character’s name back.

**Comment by Names-Are-Hard** [comment]
I've encountered the same issue, so here are some screenshots of it happening.
![0x9jo3eywk](https://user-images.githubusercontent.com/35442306/51954460-29fe4480-23f5-11e9-98c0-0965115a4225.png)
First, aghost.

![ysehfvzhwc](https://user-images.githubusercontent.com/35442306/51954461-29fe4480-23f5-11e9-98c7-d6e7e45d64fe.png)
Put another player into your body.

![odnfx2fb32](https://user-images.githubusercontent.com/35442306/51954462-29fe4480-23f5-11e9-8b25-b2cc30715cab.png)
Spawn yourself in again (human transform in player panel or select equipment).

![afwgou2cjv](https://user-images.githubusercontent.com/35442306/51954463-29fe4480-23f5-11e9-9d76-f5986ab39b36.png)
Watch as the player you put in your original body is transferred to your new body.

![rvxku39xny](https://user-images.githubusercontent.com/35442306/51954464-29fe4480-23f5-11e9-8ca3-92067bea8f14.png)

**Comment by Whoneedspacee** [comment]
hot
