### ISSUE TITLE
Bone golem's "Bone Chill" has no cooldown

### ISSUE THREAD

**Issue by Zoozele** [tgstation/tgstation#42578]
Issue reported from  Round ID: 101025 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Title says it all really, there's no cooldown on the 'Bone Chill' ability, allowing you to just mash the button endlessly
![bones rattled](https://user-images.githubusercontent.com/30756491/51882719-80ac4580-2345-11e9-9c9a-977183d81e0d.PNG)

**Comment by ATH1909** [comment]
Intended; this is to represent sans's attacks not giving you any mercy invincibility.

/s

**Comment by WaterStBlues** [comment]
I guess you could say that bone chill has no chill aha ha hahahaaaaa aaaaa

**Comment by actioninja** [comment]
Closed by #42661

**Comment by lordsaladin** [comment]
rip.
