### ISSUE TITLE
Borgs can ride wheelchairs for sanic speed

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#42593]
Courtesy of subject217 https://streamable.com/iycd9

Borgs don't even have hands, so I'd just prevent them from riding wheelchairs altogether

**Comment by tralezab** [comment]
Whoever fixes this better keep that as an admin variant where the wheelchair is all black with flames on it

**Comment by ATH1909** [comment]
I haven't looked at the wheelchair code, but maybe the three active module slots of a borg each count as an "arm", letting them move wheelchairs that they're in at the speed of a three-armed human?

**Comment by DaxDupont** [comment]
feature
