### ISSUE TITLE
throwing plasma onto lava makes land bridges

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42598]
not sure what part of this interaction results in the bridge creation but:
1. mine lotsa plasma
2. throw like 10 sheets of ore onto lava
3. lava smelts ore into plasma sheets
4. lava ignites plasma sheets
5. plasma fire
6. plasma fire vanishes, bridge forms
7. escape the gulag

**Comment by SpaceManiac** [comment]
I fear greatly that lava burns

**Comment by ATH1909** [comment]
20 pieces of ore was the needed amount, I believe.

**Comment by Whoneedspacee** [comment]
feature

**Comment by Shadowflame909** [comment]
If u survive the plasma fire the plasma ignites all the lava thus freeing you

**Comment by bgobandit** [comment]
I cannot reproduce this no matter how much plasma/ore I throw in @imsxz

**Comment by Dennok** [comment]
it can remove only lava from lava rivers and maeby created in another way.
Lava placed by map editor cant be removed in that way so gulag dont flee in that way.

**Comment by Cyprex** [comment]
Only Lava from lava rivers seems to work, in particular lava where the last entry in baseturfs is "/turf/open/floor/plating/asteroid/basalt/lava_land_surface". Most of the lava on lavaland outside of some rivers doesn't have this property.

**Comment by Dennok** [comment]
river generator dont change baseturf
