### ISSUE TITLE
God Hand and Cult spells invisible

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#42605]
Round ID: N/A
Testmerges: none
Reproduction:
1. Become Chaplain/Cultist
2. Get a Null Rod and change it to the God Hand/Use a spell like stun
3. While your hand should be glowing from the sprite, it's invisible which allows for stealth stuns and other spells or god hand attacks from nowhere since they don't show up on examine too.
(May also work for Wizard's disintegrate since I think that uses the glowing hand sprite, but the Geneticist's Shock Touch sprite works)

**Comment by Fikou** [comment]
okay i checked disintegrate works properly

**Comment by AnturK** [comment]
@PKPenguin321 You messed this up when moving touch spell icons.

**Comment by PKPenguin321** [comment]
frick. shouldn't be hard to fix
