### ISSUE TITLE
If you screwdriver a disk compartmentalizer, it becomes a smartfridge.

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#42626]
Issue reported from  Round ID: 101162 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

![bug6](https://user-images.githubusercontent.com/46474741/52094688-f3e7ce80-2574-11e9-897a-1a8afdc5e690.PNG)

Title. I unscrewed it and it changed sprites.

**Comment by datorangebottle** [comment]
This is mostly intentional- I was recently told that smartfridge and disk boards are the same thing, changed with screwdriver. But unscrewing the disk compartmentalizer still shouldn't give you a smartfridge...

**Comment by Tlaltecuhtli** [comment]
thats a missing sprite

**Comment by adamkad1** [comment]
smartfridge disk storage is cool tho
