### ISSUE TITLE
Wand of Door Creation doesn't unlock lockers

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#42629]
Issue reported from  Round ID: 101168 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

As title says. Not sure if intended or bug. Lockers are basically just doors that go into really small rooms.

**Comment by Hathkar** [comment]
It currently opens airlocks and bolted airlocks, and creates mineral doors on walls. It does open doors.

**Comment by adamkad1** [comment]
its a staff of door creations. it opens the doors you walk throught, not ones in lockers or whatnot

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/dad41cc934d1c59d2bcd0fb33675b91fc042c405/code/modules/projectiles/guns/magic/wand.dm#L184-L185

> This particular wand can create doors in any **wall**
