### ISSUE TITLE
vapes insta OD you on nicotine or any chems in it

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#42630]
take vape
put it in mouth
wait 5 seconds
you took too much nicotine

**Comment by DaxDupont** [comment]
feature

**Comment by adamkad1** [comment]
isnt it because of smoke mechanic? unless your talking about a nonoverloaded one

**Comment by kriskog** [comment]
If you vape for a few minutes, you'll get addicted then overdosed. If you overclock it, well what did you expect. Issue sounds like it was a much faster thing, if so thats not happening anymore.
