### ISSUE TITLE
genetic stability is broken af

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#42632]
I took mutadone after getting message that my dna is exploding. i lost my powers but still got hit with aftereffect (it happened to be spitting out organs)

**Comment by 4dplanner** [comment]
@Time-Green

**Comment by Time-Green** [comment]
I’ll check

**Comment by Time-Green** [comment]
I already fixed it in #42151 , I’m just waiting for that to get merged, can’t be long right?

Thanks for the report, sorry for your organs
