### ISSUE TITLE
Putting a hat on a corgi makes it count as a new corgi for moodlet purposes

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#42648]
From the same corgi you can get as many simultaneous positive moodlets as you have hats and/or time:

Ian is adorable! I can't stop petting it!
Ian the Clown is adorable! I can't stop petting it!
Segnor Ian is adorable! I can't stop petting it!
Captain Ian is adorable! I can't stop petting it!
Hoppy is adorable! I can't stop petting it!
Santa's Corgi Helper is adorable! I can't stop petting it!

...and so on, resulting in a ridiculous stacked boost.

**Comment by tralezab** [comment]
that's really my bad, sorry
