### ISSUE TITLE
Maps using the Job Selection of other Maps

### ISSUE THREAD

**Issue by fluffe9911** [tgstation/tgstation#42646]
## Reproduction:
Its a bit hard to explain this one but it seems sometimes maps will use the job selection of other maps instead of there job selection say for example you had a station where the only job was assistants and clowns sometimes it would use that job selections for other maps instead of the one its supposed to use

**Comment by Cyprex** [comment]
Any idea if this is limited to particular maps? What exactly are you experiencing? What jobs are available when this happens? Does this happen for latejoins, roundstart, or both?

**Comment by fluffe9911** [comment]
1. From my understanding it can happen to any map really its just since tg has all the same jobs available for all the maps its not noticeable 2. Pretty much say for example you were on meta station but when you opened the map selection menu you could only pick the jobs from say donut station (theres no job differences but you get the idea) 3. And it happens both late join and round start

**Comment by Cyprex** [comment]
Which downstream is having this issue?

**Comment by fluffe9911** [comment]
Yogstation mostly with the clown station map which had to be removed due to this issue although still happens where it chooses the job selection of the maps that dont got yogs jobs everynow and then

**Comment by SpaceManiac** [comment]
Closing as needs repro, I'm willing to bet it was a downstream problem
