### ISSUE TITLE
mmied hivemind hosts have some powers available

### ISSUE THREAD

**Issue by lordsaladin** [tgstation/tgstation#42660]
Issue reported from  Round ID: 101293 (/tg/Station Terry [EU] [100% LAG FREE])
step one mmi a hivemind host with at least 8+ assimilated hosts.
step 2 the host can still use some powers gained by unlocking.
Reporting client version: 512

**Comment by wesoda25** [comment]
Wouldn't this be a feature? All of their powers DO reside in the brain.

**Comment by ShizCalev** [comment]
emergent gameplay

**Comment by nemvar** [comment]
I turned a hivemind into a cak and they still had their powers. Honestly kinda like it.

**Comment by ATH1909** [comment]
> I turned a hivemind into a cak and they still had their powers. Honestly kinda like it.

That's amazing.

**Comment by lordsaladin** [comment]
@ATH1909  the basic  round start ones you can't, i'm flagging it up due to an admin's advice, it'd be nice to keep all the powers so a mmi host can help the crew,not tested it on borgs.

**Comment by ATH1909** [comment]
> @ATH1909 the basic round start ones you can't, i'm flagging it up due to an admin's advice, it'd be nice to keep all the powers so a mmi host can help the crew,not tested it on borgs.

Yeah, making this an intended feature would be nice.

Can you add people to your hivemind by using that power that lets you steal all of another hivemind hosts' hivemind members?

Should caks be allowed to keep their hivemind powers (if we make this an intended feature)? Should borgs?

**Comment by ATH1909** [comment]
Ah, I think that I see what's causing this.

/obj/effect/proc_holder/spell/target_hive (and /obj/effect/proc_holder/spell/self/hive_drain) (and thus spells based off of them) have the human_req variable set to 1, but the other hivemind host powers do not.

This means that the list of hivemind host powers that work while you're an MMI or a cak are as follows:
Induce Panic
Network Invasion
Mass Assimilation
Bruteforce (although there's not much point to casting it)
Telekinetic Field

Pet MMI or cak hiveminds are thus useful for testing who is or isn't in a hivemind/is a hivemind host, removing people from hiveminds (with Network Invasion), casting Induce Panic, and casting Telekinetic Field.

I'll keep this in mind next time that I'm a warden or something in a hivemind round.

I don't know if borgs can cast these spells/use these powers too.

**Comment by AlexTheSysop42** [comment]
Make assimilate and one mind not need to be human so you can get a borg assimilating everyone and using one mind to finally get them to stop harming each other

**Comment by Kierany9** [comment]
human_required being set to 0 on some abilities was an oversight on my part, it's fixed in #42607

**Comment by lordsaladin** [comment]
@Kierany9 a unexpected feature*

**Comment by Kierany9** [comment]
42607 has been merged, feel free to close this whenever
