### ISSUE TITLE
hypnosis minor issue

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42673]
hard to tell when hypnosis wears off, I was hypnotized recently and didn't realize until a bit after that it had already worn off a while ago. some sort of active indicator while hypnotized or bigger text when it wears off would go a long way.

**Comment by ATH1909** [comment]
Yeah, that'd be really nice.

What do you mean by "worn off", though? You got the brain trauma cured? You got cloned?

**Comment by daeds1dog** [comment]
How did you know it wore off?
