### ISSUE TITLE
AI/Initialize() failing to transfer client mind for roundstart AI's.

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#42678]
Cause of #42413

Also results in their notes not being properly stored, their role explanation stuff not being shown, and their laws not being displayed in chat.

**Comment by timothymtorres** [comment]
@ShizCalev did #42833 fix this issue?

**Comment by Sealed101** [comment]
looks like it did, that or the other preferences adjustments to ai initialize()
