### ISSUE TITLE
Tac reloading the double barrel doesn't allow it to shoot

### ISSUE THREAD

**Issue by InsaneKatrina** [tgstation/tgstation#42672]
Issue reported from  Round ID: 101360 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

The bartender's shotgun tacticool reload is now behaving in such a way that when inserting new shells to replace the spent ones does not allow it to fire. This may be a racking the gun sort of issue and on top of that, a loaded double barrel says it has three shells loaded instead of two. Further testing required

**Comment by actioninja** [comment]
@InsaneKatrina I didn't even know the double barrel was supposed to have a tacticool reload, going to need to investigate more into this.

**Comment by InsaneKatrina** [comment]
It was p much just replacing a spent shell with a fresh one in one of the barrels on the fly (I assume that stands for tac reloading at least), its been there for a pretty long time too

**Comment by Daxxed** [comment]
Improv shotties have the same issue.
