### ISSUE TITLE
Damp Rag doesn't transfer contents on touch

### ISSUE THREAD

**Issue by Nickkoranda** [tgstation/tgstation#42680]
Reagents will still be spent but the reagents themselves will not transfer to anybody you use it on.

**Comment by ShizCalev** [comment]
Working fine here, are you using it in harm intent?

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/49a4cb67694a1f36c36fa016c9686721d11b4075/code/modules/detectivework/footprints_and_rag.dm#L34-L43

**Comment by Nickkoranda** [comment]
Huh, retesting it seems to work but I swore I could've tried it on harm. Closing anyway, thank you!
