### ISSUE TITLE
donutstation has a floating rnd area near the engine

### ISSUE THREAD

**Issue by GenericDM** [tgstation/tgstation#42695]
![image](https://user-images.githubusercontent.com/34109002/52429501-0738f380-2ab9-11e9-8d27-32926a273088.png)
near the top left of the image.. this doesnt seem intentional. #42668 did this.

**Comment by ExcessiveUseOfCobblestone** [comment]
@MMMiracles

**Comment by PKPenguin321** [comment]
Bluespace experiment gone wrong

**Comment by ShizCalev** [comment]
Closed by #42689
