### ISSUE TITLE
poly machine broke

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42697]
`Engineering] Poly yells, "[00:09] <span class='game say'><span class='name'>The universal recorder</span> <span class='message'>says, "<span class='robot '>[00:06] <span class='game say'><span class='name'>Khloe Parker</span> <span class='message'>says, "<span class=''>Wowee</span>"</span></span></span>"</span></span>"`

**Comment by imsxz** [comment]
<Engineering] Poly yells, "[00:09] <span class='game say'><span class='name'>The universal recorder</span> <span class='message'>says, "<span class='robot '>[00:06] <span class='game say'><span class='name'>Khloe Parker</span> <span class='message'>says, "<span class=''>Wowee</span>"</span></span></span>"</span></span>">

**Comment by imsxz** [comment]
`Engineering] Poly yells, "[00:09] <span class='game say'><span class='name'>The universal recorder</span> <span class='message'>says, "<span class='robot '>[00:06] <span class='game say'><span class='name'>Khloe Parker</span> <span class='message'>says, "<span class=''>Wowee</span>"</span></span></span>"</span></span>"`

**Comment by wesoda25** [comment]
Feature

**Comment by ShizCalev** [comment]
Duplicate of #36758
