### ISSUE TITLE
Remaining gun issues

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#42718]
New bug compilation thread because oranges merged a PR that closed the last one.

Current known issues.
The L6 SAW claims in the examine text that you ctrl+click it to open the cover, but you actually alt click.

On the Uzi, an open-bolt gun, if you remove the magazine while the bolt is locked to the rear, you have to re-cock the weapon when you reinsert the magazine in order to fire it. The intended interaction would be that the weapon is ready to fire as soon as the magazine is inserted, without requiring you to re-cock the weapon, as it's still cocked. Additionally, if I remember correctly, the Uzi actually had a sprite for when the bolt is closed, which does not appear to be used here.
The same bug applies to the L6 SAW, so I presume it's an issue with any open bolt weapon.

Bulldog magazine overlay appears to be non-functional. It just uses the base sprite. Tried it with every different magazine to no avail.

@actioninja double ping because I want to make it clear that these issues are not resolved.

**Comment by yoyobatty** [comment]
Tac reloading doesn't call update icon on the mag that just came out of the gun, causing it to appear fully loaded when you examine it.

**Comment by subject217** [comment]
On pistols, the slide "locking back" icon change should happen on the last shot fired in the magazine. Instead, it happens when you try to fire the pistol when it's empty.

**Comment by actioninja** [comment]
working on these rn

**Comment by actioninja** [comment]
all of these are fixed now.

**Comment by actioninja** [comment]
all of these were fixed by #42722
