### ISSUE TITLE
tactical reload doesnt work

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#42710]
@actioninja

**Comment by actioninja** [comment]
Works on my machine.
What are you trying to tacload? The var is only enabled on the c20r and bulldog.

**Comment by Tlaltecuhtli** [comment]
sketchin

**Comment by Tlaltecuhtli** [comment]
why remove tacload from pistols wtf

**Comment by actioninja** [comment]
Yeah, intended functionality then.
