### ISSUE TITLE
Carp-Sie plushie non-functional for megacarp

### ISSUE THREAD

**Issue by brotherbotany** [tgstation/tgstation#42724]
Issue reported from  Round ID: 101579 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

When blessed by the Carp-Sie plushie (null rod variant), megacarp still attack you.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/1b50671ca072dd646e98bee971a6d20d5c06a2de/code/modules/mob/living/simple_animal/hostile/carp.dm#L36

**Comment by timothymtorres** [comment]
Fixed by #64038
