### ISSUE TITLE
Networked fiber blob cant move onto blobs

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#42734]
Not sure if a bug or a feature but it makes the blob so goddamn useless, unless you just moved your core, its a bad idea to move your core to spaces adjacent to your core because they usually are gonna be under fire, and it still makes it hard to properly reinforce your blob

**Comment by ATH1909** [comment]
What? Could you, uh, explain that better?

**Comment by adamkad1** [comment]
You got networked fibers blob. it moves its core when you expand next to it, but you cant expand on allready existing blob tiles, which makes it useless because your core is surrounded by strong blobs and if one is gone, moving there is likely a dumb idea

**Comment by YakumoChen** [comment]
I thought the point was to play snake with the blob? Instead of expanding normally it gains points when it could expand, meaning it's easier to do so when you have no tiles around the core.

**Comment by adamkad1** [comment]
well, do you really want to move your core right into the crew?

**Comment by imsxz** [comment]
alt click sells tiles dummy, just sell tiles to move onto them.

**Comment by kriskog** [comment]
Yes, hit alt to remove already placed tiles and expand onto the now empty space.
