### ISSUE TITLE
Presription glasses do not remove the vision blur.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#42742]
Presription glasses only remove the vision range restriction if your eyes are damaged. Looks like the guy who made the blur forgot to about glasses.

**Comment by wesoda25** [comment]
They aren't supposed to do it instantly, if thats your issue with it.

**Comment by ATH1909** [comment]
Aren't real life glasses supposed to let people with blurry vision see better, though?

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/a7ba0ad06df76f4f38e4ea0687a7c443d84141e9/code/modules/mob/living/carbon/human/inventory.dm#L104-L106

???

**Comment by ExcessiveUseOfCobblestone** [comment]
If you take any eye damage/healing while still above the threshold after putting them on you'll probably get the overlay again until you uneq/re-equip

**Comment by timothymtorres** [comment]
@ExcessiveUseOfCobblestone is this still a thing?
