### ISSUE TITLE
Antagonist and job preferences reset their time gates

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#42755]
Issue reported from  Round ID: 101723 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Was randomly tooling around in observe mode, and I hit my game preferences window and saw this under my job/antag preferences.
![bug7](https://user-images.githubusercontent.com/46474741/52661044-f243d200-2eb5-11e9-81ad-e581dfe81abe.png)
![bug8](https://user-images.githubusercontent.com/46474741/52661050-f53ec280-2eb5-11e9-9753-7f9c9a588054.png)

Relogging set them back to normal. It might just be a display issue, but it was very alarming.

Sadly, I have no way of reproducing this bug as I have no idea how it happened.

**Comment by datorangebottle** [comment]
Oh, and my job settings were still boned aside from the base crew ones. The fuck?

**Comment by DaxDupont** [comment]
That's usually when database connection drops

**Comment by kriskog** [comment]
All jobs locked, so caused by the database dropping.
