### ISSUE TITLE
space dragon command report issue

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#42779]
Reproduction:
1. The space dragon event triggers, randomly or admin triggered
2. Nobody accepts the ghost offer for it.
3. The command report sends anyways, even though there's no dragon coming.

Should be an easy fix. As an aside, this event could use a "send report?" option in the trigger events menu, like how rods work.

**Comment by IndieanaJones** [comment]
Will fix.

**Comment by SouDescolado** [comment]
Don't fix. Make it wait some time and send a new report "JUST A PRANK BRO"
