### ISSUE TITLE
Changeling perma speed boost

### ISSUE THREAD

**Issue by St4lkius** [tgstation/tgstation#42787]
If you take strained muscles as changeling and double click the icon you get the movement speed without any of the debuffs. Probably not intentional

**Comment by ATH1909** [comment]
What happens if you triple click it?

**Comment by St4lkius** [comment]
If you click for a third time you re activate the debuffs. But even if you wait 5 seconds before disabling it you still have move speed buff afterwards.

**Comment by HomocidlePancakes** [comment]
Iam suprsied it took 3 months for someone to report this and not a single coder or min noticed this

**Comment by St4lkius** [comment]
I'm good at finding bugs

**Comment by St4lkius** [comment]
I've noticed bug for a long time so it's like the best DNA strain to get for murder boning your targets because it reduces stun times too

**Comment by ATH1909** [comment]
I'm just wondering if there's a way to somehow self-stack this to become the Flash.

**Comment by St4lkius** [comment]
Take it. Use it. Restart your DNA sbilities take it again. You're welcome. Also you can just stack it with adrenaline rush

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=VTHsOSGJHN0

**Comment by ATH1909** [comment]
> Take it. Use it. Restart your DNA sbilities take it again. You're welcome. Also you can just stack it with adrenaline rush

Wait, do you have to reset your abilities after you put this bug into effect (after 2 clicks) or while it active (after 1 click)?

**Comment by St4lkius** [comment]
No you don't have to reset abilities. After two rapid clicks your speed is fast forever inlest in rested position or walking or leg damage

**Comment by ATH1909** [comment]
> No you don't have to reset abilities. After two rapid clicks your speed is fast forever inlest in rested position or walking or leg damage

No, I meant for the self-stacking with the resetting.

**Comment by St4lkius** [comment]
Should work. I'll test it

**Comment by HomocidlePancakes** [comment]
There is an issue with most (if not all) ling toggle abilities. If you reset your DNA while having it active, you will still have the effect. I've been able to pull it off with pheromone receptors, augmented eyesight and strainded muscles.

**Comment by ATH1909** [comment]
> There is an issue with most (if not all) ling toggle abilities. If you reset your DNA while having it active, you will still have the effect. I've been able to pull it off with pheromone receptors, augmented eyesight and strainded muscles.

Will you still have the drawbacks?

**Comment by py01** [comment]
dupe, #41943

**Comment by HomocidlePancakes** [comment]
It happened during the meme satchel era so I don't remember really.

**Comment by Cyprex** [comment]
This issue is a lot more detailed, #41943 should be closed in favor of this one.

**Comment by tralezab** [comment]
would the fix be as easy as putting a short cooldown on the action buttons and making sure the abilities turn off on removal?

**Comment by St4lkius** [comment]
That'd be a highly probable solution

**Comment by AnturK** [comment]
From quick glance at the code
https://github.com/tgstation/tgstation/blob/f088f3100b40bd28fe3c0a4d5264cbb724119194/code/modules/antagonists/changeling/powers/strained_muscles.dm#L21
Should be removal of the modifier because it makes no sense otherwise.

**Comment by St4lkius** [comment]
It looks like there is not turn off of the movements peed in the code

**Comment by St4lkius** [comment]
Looks like strained muscles only turns off if you overuse it and pass out

**Comment by St4lkius** [comment]
>Our muscles relax without the energy to strengthen them.</span>")
This is the only part of the code that actually turns off strained muscles

**Comment by ATH1909** [comment]
I see the problem here- manually turning off your speed boost adds ANOTHER speed boost (dunno if they stack, since they seem to have the same ID) instead of removing your speed boost.

**Comment by St4lkius** [comment]
They do not stack due to them having the same ID. It only makes your base speed faster to a point. so it stops you from being the flash.

**Comment by ATH1909** [comment]
Question here: If you have, say, the mimic voice power active and then reset your powers (to choose new ones), will you keep your chosen voice? More importantly, will you keep the penalty to chem regen rate that the mimic voice power gives you whenever you activate it (and then takes away when you disable it)?
