### ISSUE TITLE
The pills you get from the Junkie quirk don't help alleviate the addiction symptoms

### ISSUE THREAD

**Issue by ModDownloading** [tgstation/tgstation#42797]
From #42477 

When you start a round with the Junkie quirk, the pills you get from the pill bottle (7 0.5u pills according to the PR developer) do not help remove the "needs drug" effect that is given by the addiction. Additionally, dissolving the pills in liquid or grinding them up yields no chemicals, though an admin that I sent an adminhelp to about it was able to determine that the pills did still contain chemical, albeit a very small amount. The chemical I was using at the time was the Happiness drug, and the pills provided by the admin shortly after the test were able to qualify as taking the drug with regards to the addiction.

Edit: Apparently there was some testing on the main PR thread using the Happiness drug at 0.5u with mixed results. Perhaps it is because the drug is metabolizing too fast to register 0.5u, and that 1u pills would work instead? The 0.5u pills did not drop their reagents when ground up or dissolved, so that might be the issue.

Edit 2: Tested again with 0.5u and 1u pills of morphine, the 0.5u pills did not work but the 1u pills did, and even though they didn't last nearly long enough to get through a whole round, I suppose finding a way to secure your drug is part of the challenge with taking Junkie, so this seems like it should be a reasonable way to fix it.

**Comment by Angustmeta** [comment]
Do the 0.5u pills reset the actual addiction symptoms?

**Comment by ModDownloading** [comment]
The 0.5u pills had no effect when I tested them, they acted as though they functionally had no reagents in them at all.

**Comment by Angustmeta** [comment]
Seems those pills literally had no reagents in them.

**Comment by ExcessiveUseOfCobblestone** [comment]
dupe
