### ISSUE TITLE
DNA Console Runtimes

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#42796]
@Time-Green 

Taken from live server
https://pastebin.com/aQYAi1Dj

Seems to break injector printing and copying to disks indefinitely

Possibly unrelated, but the `Print Mutator` and activator buttons don't grey out when they are on cooldown for some reason

**Comment by PKPenguin321** [comment]
For some reason opening the scanner seems to fix the machines once they break?

**Comment by ShizCalev** [comment]
missing the actual runtime part of it.

**Comment by ShizCalev** [comment]
[2019-02-15 00:56:42.386] runtime error: bad arg name 'copymut'
