### ISSUE TITLE
On-Fire Sprites for clothing and Hood Toggle Stay on Fire

### ISSUE THREAD

**Issue by Zytolg** [tgstation/tgstation#42800]
## Round ID: 101883

Combat happened, someone caught on fire (gun), then I caught on fire (proximity). Took the necessary steps to rectify that but noticed my clothes were still showing that they were on fire. I took a shower but to no avail. The sprites appear to get stuck on their on-fire variants and it appears to extend to associated sprites as well (such as the hood toggle button for the HUD). This is the first time this has happened thus the bug report. 
Image Related:
![autism station fire fire fire](https://user-images.githubusercontent.com/33048583/52895098-95287480-3172-11e9-8582-c0abb143dbae.PNG)

The image doesn't show the HUD button on fire, but after I took the snapshot, it was. This might have occurred after a toggle.

**Comment by ATH1909** [comment]
I've seen this happen many times, but I had forgotten to report it.
