### ISSUE TITLE
COORD / AREACOORD reports coordinates of held objects as 0,0,0

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#42804]
## Round ID: 
101902 Bagil

## Reproduction:

`AREACOORD(bomb)` used in log_bomber() seems to always point to 0,0,0
Some examples:
```
ADMIN LOG: Denton-30/(Sombrero TX)(?) (FLW) at CentCom Docks (176, 111, 1) (JMP) triggered a PDA explosion on PDA-Xander Neely (Assistant) at Admin Prison (0, 0, 0) (JMP)
ADMIN LOG: CrabCakesMcgee/(Feathers McGraw)(?) (FLW) at Central Primary Hallway (88, 132, 2) (JMP) has primed a classic EMP grenade at Central Primary Hallway (0, 0, 0) (JMP) for detonation.
```

**Comment by ShizCalev** [comment]
0,0,0 means that the item was being held or contained in something since it's reporting x/y/z coordinates of an object in nullspace.

**Comment by san7890** [comment]
Fixed in https://github.com/tgstation/tgstation/pull/51742
