### ISSUE TITLE
Hallucinatory flames might be able burn off your clothes?

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#42810]
As the title.

Do note that I didn't witness this personally, but was told about it by someone in OOC chat after the bug affected them. It might need testing.

**Comment by ATH1909** [comment]
From a glance at the code, I don't see why this would happen. Maybe they were actually set on fire by something while they were hallucinating that they were on fire?

**Comment by 4dplanner** [comment]
round ID?

**Comment by ATH1909** [comment]
> round ID?

Don't have one.

I'm starting to doubt if this is an actual/real bug, but it'd still be nice if someone was able to test it.

I'll try to test it tonight with nanites.

**Comment by XDTM** [comment]
i doubt it's possible, hallucination flame code just deals stamina damage and applies an overlay, so it shouldn't trigger any part of fire code beyond having 0.1 fire stacks

**Comment by ATH1909** [comment]
> i doubt it's possible, hallucination flame code just deals stamina damage and applies an overlay, so it shouldn't trigger any part of fire code beyond having 0.1 fire stacks

That's what I'm thinking, too.

I didn't get a chance to test it out last night, so I'll try to test it tonight.

**Comment by ATH1909** [comment]
Just testing this, and yup, it's bogus.

As it turns out, though, a loop of making someone hallucinate that they're on fire every 10 seconds can actually easily put them deep into stamina crit after a minute or two. Dunno how effective it is if they're resting, though.
