### ISSUE TITLE
Genetics can't save mutations anymore

### ISSUE THREAD

**Issue by Kaptinalexander** [tgstation/tgstation#42816]
Issue reported from  Round ID: 101951 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

whats wrong:
Apparently genetics can't save mutations anymore. Once the subject in the scanner has their DNA scrambled you can't print activators or mutators, or save the mutation to disk. 

You can if the person in the scanner still has the fully solved mutation however.

loading the mutation from disk and then attempting to print an activator or mutator dosen't work, so you can't share work between the consoles anymore.

the person in the DNA scanner HAS to have the mutation fully solved.

**Comment by Time-Green** [comment]
You can only save activated mutations, even if they’re discovered.
I’ll go figure out why data disks suddenly crapped themselves

**Comment by Kaptinalexander** [comment]
Sorry guess I wasn't very clear, what I mean is after you've saved it, if the person in the genetics scanner loses the mutation (ie. you hit scramble DNA, or you replace one of the pairs with an X, or he just gets out of the scanner) you can't print activators or mutators anymore from it. In fact you can't even save it to disk. If by chance you saved the mutation to disk while he was in the scanner and everything was fine, after he loses the mutation, you still can't do anything by reuploading it.
