### ISSUE TITLE
heat_protection flag does not interact properly with FIRE_IMMUNITY_MAX_TEMP_PROTECT (or otherwise fire resist on armor)

### ISSUE THREAD

**Issue by Unit2E** [tgstation/tgstation#42839]
## Issue:
FIRE_IMMUNITY_MAX_TEMP_PROTECT is 35000K. Any gas you are in the environment of that is hotter than this will cause you to take damage, this is the very maximum an atmospherics protective suit is supposed to protect you to, such as the atmospherics hardsuit. Somewhat seperately, these same suits also have you be immune to fires, which does make sense. However, there is an odd interaction here. When you are on fire, FIRE_IMMUNITY_MAX_TEMP_PROTECT stops functioning practically entirely, and you become immune to gas of any temperature. Simply by being on fire, completely regardless of what's causing it, you can stand in gas of any temperature. You can survive a fusion fire so long as you are on fire, but if you're not on fire while being exposed to these kinds of temperatures, you will start taking damage.

## Reproduction:
Equip a suit that has heat protection, such as the atmopsherics hardsuit, CE's hardsuit, atmospherics firesuit and helmet, etc. Create a fusion fire and stand in it, take no damage. Heat exchange some random gas with the fusion levels of temperature (or just raise the temperature to a ways above 35000K), ensure you're not on fire, start taking damage from the gas' heat. Light yourself on fire in this same gas, don't take damage anymore.

## Vidya:

https://puu.sh/CO996/1c868f7fa7.mp4

**Comment by Whoneedspacee** [comment]
but i want my firefighting suit to be fusion fire immune
