### ISSUE TITLE
rockets cant be properly loaded

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42847]
cant chamber a round with it, using it in hand to "rack" it just ejects the rocket.

@actioninja

**Comment by actioninja** [comment]
Fuck, it worked the last time I tested it. More testing time I guess.

**Comment by actioninja** [comment]
Looking more at the code this is some major shitcode that isn't mine for once, working on a recode for it.

**Comment by actioninja** [comment]
Oh boy while attempting to fix this I discovered a brand new bug.
