### ISSUE TITLE
Power sinks can be placed under airlocks

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#42852]
Power sinks can be placed and activated under airlocks. Unlike false walls, this completely obscures them.

Imo a good solution to this would be preventing the airlock from closing, like scooters and other movable atoms do.

**Comment by Cyprex** [comment]
What about moving powersinks into a higher rendering plane?

**Comment by ExcessiveUseOfCobblestone** [comment]
just give it density on activate lol
