### ISSUE TITLE
AI swapping in and out shell causes a new name to be generated for the shell

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#42865]
Issue reported from  Round ID: 102169 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

![dreamseeker_2019-02-21_13-49-46](https://user-images.githubusercontent.com/17237624/53170162-b3152f80-35df-11e9-9b7c-cfe193eb3f70.png)

**Comment by ondrej008** [comment]
Give me all the shells!
