### ISSUE TITLE
space dragon becomes invisible after swooping

### ISSUE THREAD

**Issue by Nickkoranda** [tgstation/tgstation#42874]
pretty sure it's because of https://github.com/tgstation/tgstation/blob/e62d9505eb55e5309167ddf1a4f853343861c77c/code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm#L449
but basically after swooping the icon will become 'dragon' instead of 'spacedragon', thus turning invisible

**Comment by ATH1909** [comment]
Snake? Snake? SNAAAAAAAAAAKE!

(Get it? It's because dragons are (probably) reptiles and... I'll see myself out now.)

**Comment by tralezab** [comment]
something like 
`icon_state = initial(icon_state)`

**Comment by Whoneedspacee** [comment]
something something not my fault

**Comment by ATH1909** [comment]
> something like
> `icon_state = initial(icon_state)`

Would that mess with that action that you can perform as a dragon that shrinks your sprite (from your point of view) so that you'll accidentally click yourself less in melee?

**Comment by IndieanaJones** [comment]
...Is the space dragon currently swooping?
