### ISSUE TITLE
Rotatium only causes minor screen swinging

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#42878]
Tested on private server after I injected  someone with 15u rotatium on Bagil, who then reported in deadchat that it didn't work. 

#### Reproduction:
1. Beat Inspector Johnson's ass for trying to ruin your tests. 
2. Drink like 30u rotatium. 
3. Wait about 40 seconds. 

The screen starts swinging a tiny bit. Maybe 15-30ish pixels. Keep waiting and the swing range will keep slowly increasing over time, until the rotatium finishes metabolising which causes it to stop as expected. 

#### Expected result: 
Screen starts swinging with huge motions from left to right after 20 cycles ~~a couple of seconds after ingestion.~~

I also tested with skewium, which still seems to work somewhat the same as before but I'm not sure. ~~Skewium also has a strange delay of a few seconds before working, but it has had that for a while.~~

Edit: The delays are intended, but the weak motion can't be.

**Comment by Tlaltecuhtli** [comment]
intended? 
https://github.com/tgstation/tgstation/blob/d7931786797fa3e77a27eab08ff813430ebe254c/code/modules/reagents/chemistry/reagents/toxin_reagents.dm#L754

**Comment by kriskog** [comment]
Yeah, seems intentional from the original PR, #20707

>
>add: New toxin - Rotatium. It doesn't quite do what it does on other servers. Instead it rocks your game view back and forth while slowly doing toxin damage. The rocking gets more intense with time.

Thats not to say it doesn't deserve a buff, it is quite underwhelming.
