### ISSUE TITLE
If a revenant walks over a rubber ducky while on the ethereal plane, it still honks.

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#42885]
As the title.

**Comment by OverlyGeneric** [comment]
feature. all bikehorns are made from dead people. specifically, their funny bones and their laughbox.

**Comment by HomocidlePancakes** [comment]
Feature. Had a whole round as rev where there were no corpses so I tried to force people in to servitude of the GREAT RUBBER DUCKY. Was fun.

**Comment by DaxDupont** [comment]
Remember when pointing triggered honking, I miss that

**Comment by ShizCalev** [comment]
more than likely effects wizards, constructs, slaughter demons, ect, anything that'll be inside a holder item.

**Comment by zxaber** [comment]
We really ought to not fix this one.
