### ISSUE TITLE
Deca crate explodes anyway after unlocking it

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#42895]
If you discovered this issue from playing tgstation hosted servers:
[Round ID]: # (Terry, I forgot the round but it was today)
 Testmerges: Fusion

![image](https://user-images.githubusercontent.com/7501474/53305787-f8f32180-3885-11e9-8a3f-5c3f0e8842d4.png)

This only happened once and I have no idea why

**Comment by HomocidlePancakes** [comment]
You hit it with a multitool. Pretty dumb that they blow up from taking ANY damage but meh.

**Comment by Time-Green** [comment]
That’s a thing? Fuck me

**Comment by ShizCalev** [comment]
#

**Comment by ShizCalev** [comment]
#36206
