### ISSUE TITLE
Imaginary Friends die if they're out when the shuttle launches.

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#42893]
Issue reported from  Round ID: 102494 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Yeah. Easy to reproduce:
1) Get someone with an imaginary friend.
2) Call shuttle.
3) Have the imaginary friend sit next to their owner on the shuttle.
4) When the shuttle takes off, they get ghosted.

**Comment by Sealed101** [comment]
can't reproduce - the friend correctly jumped back to the host when out of the shuttle and did not go anywhere when on the shuttle
