### ISSUE TITLE
Brain Ailments Not Curable By Surgery

### ISSUE THREAD

**Issue by Zytolg** [tgstation/tgstation#42903]
## Round ID:102515

Whole station got Brain damages that required surgery. Surgery would not cure the various diseases. Ahelped the issue and admin was stumped as well. Bringing it here as it might be a possible bug. 

## Reproduction:

Acquire any brain trauma and attempt to cure it via surgery. Succeed in the surgery and frown when the patient still has schizophrenia/paranorma/blindness due to brain disease. 

There was a wizard so it is possible this could be solely magic related. Everyone on the station (that I saw) had some form of brain trauma.

**Comment by Time-Green** [comment]
You need a lobotomy to cure magic trauma’s

**Comment by Therapist1** [comment]
Curse of madness causes permanent trauma in those who get it, only thing I can think of to try would be a lobotomy.

**Comment by XDTM** [comment]
Can someone close this? Curse of madness traumas require lobotomy to cure

**Comment by tralezab** [comment]
^ intended
