### ISSUE TITLE
Limbs can sometimes take more than their damage cap

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#42909]
Reproduction steps:
1. Spawn human
2. Target left arm
3. Fire SAW twice.

Limb is left with 85 brute, when the damage cap on limbs is supposed to be 50. Also, damage to limbs that are already at or over the damage cap does zero damage. Not sure if intended, or if excess damage is supposed to redirect.

**Comment by WJohn** [comment]
I was able to deal 85 brute to the right arm there using an l6 saw, but only 70 burn with a laser. Also experienced the 10 damage 3rd shot. After these numbers were reached I was unable to do any further damage. I thought doing damage on the limbs past their max health would have that damage redirected to the chest?

**Comment by py01** [comment]
Damage over cap to limbs has dealt 0 damage for quite a while, though not sure if intended.

**Comment by py01** [comment]
Another issue that I believe is related: Penetrator sniper rounds deal vastly reduced damage if they hit limbs, dealing 10 to the limb instead of the expected 60
