### ISSUE TITLE
Blood trails look wrong on the horizontal.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#42918]
![](https://i.imgur.com/gx6gWJR.png)

Note the horizontal trail acting like it's trying to go up and down as well.

**Comment by ExcessiveUseOfCobblestone** [comment]
I guess you could say the horizontal trails are suppose to look right heheheehehehe

**Comment by WJohn** [comment]
This also happens with footprints, by the way. Presumably also with mulebot trails.

**Comment by Dennok** [comment]
Still
