### ISSUE TITLE
Softcrit health threshhold is at 120 damage taken, not 100.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#42915]
## Reproduction:

Spawn yourself in the thunderdome, deal 119 damage to yourself in the VV interface, notice how you haven't fallen into crit yet. Kind of a gigantic problem from a balance perspective that has likely only gone unnoticed because most of our common traitor/op weapons for critting someone take the same number of hits to crit you regardless. Revolvers still 2 shots, stetchkin, c20r, and esword still 4 shot, l6 saw still 3 shots, that sort of thing.

**Comment by ATH1909** [comment]
Was your mood/sanity high? IIRC, they modify the softcrit threshold.

**Comment by WJohn** [comment]
Seems being suicidal drops the threshhold down to 100, but shouldn't 100 be the *default?*, and then you drop to 80 when terribly sad?

**Comment by Tlaltecuhtli** [comment]
its handled here ?
https://github.com/tgstation/tgstation/blob/master/code/datums/components/mood.dm#L245

**Comment by ATH1909** [comment]
Did you edit your mood or your sanity?
