### ISSUE TITLE
Encryption keys in borgs only use their default channels

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#42919]
Steps to reproduce:
1. Acquire a captain's headset.
2. Turn all of its channels on.
3. Pop out the encryption key.
4. Put the encryption key in the borg.
5. The borg can only use/hear the common, security, and command channels (the same ones that are turned on in a captain's headset at roundstart).

This means that borgs can't listen to both the sec channel and the medbay channel at the same time (without a syndicate encryption key or the like), which saddens me.

**Comment by necromanceranne** [comment]
This seems recent. I've put the captain's encryption key into borgs before and it has allowed them to speak on all channels.

**Comment by ATH1909** [comment]
> This seems recent. I've put the captain's encryption key into borgs before and it has allowed them to speak on all channels.

How recently?

It should be noted that I encountered this bug with the captain's BOWMAN headset; I dunno if it still occurs with the captain's normal headset.

**Comment by VileBeggar** [comment]
can't borgs toggle the channels though? there's button on the bottom right corner that does that iirc

**Comment by Unit2E** [comment]
There is. I think this was just changed at some point, because it never seemed to need the switch before. Anyway, borgs can see and talk all channels on encryption keys if they go to their radio settings and turn them on and the such.

**Comment by ATH1909** [comment]
Oh.

**Comment by kriskog** [comment]
Same as putting caps bowman on, gotta turn the non default channels on to use them. Could maybe be more obvious for borgs.
