### ISSUE TITLE
The L6 Saw eats a bullet every time the magazine is re-inserted.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#42926]
The L6 saw spawns with only 49 bullets, and every time you pull the magazine out and put it back in, rather than chambering a round it actually just *eats* the bullet that would go there. You can pull it out and put it back and keep losing bullets this way, presumably where they fuck off into the ether or someplace.

As a result of this, the gun has a really confusing racking mechanic involving a disappearing bullet.

Also, you can't tell if a bullet is chambered because of this, there's no notification of whether or not it is chambered even after you rack the gun.

EDIT: Somewhat related, clicking on the gun in your active hand gives you a very unhelpful "the gun is ready to fire!" at all times, whether it has any ammunition or not, or if the cover is open, it'll tell you that. The only time you get a different message is when you rack the gun.

**Comment by ShizCalev** [comment]
@actioninja

**Comment by actioninja** [comment]
Either one of the procs is lying about what a parameter does, or I'm really bad at programming.
It's probably both.

**Comment by ShizCalev** [comment]
#42837 @MadmanMartian you perhaps?

**Comment by actioninja** [comment]
No, pretty sure this one is my fault.
