### ISSUE TITLE
AI's power loss procedure is unintuitive and buggy

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#42928]
whenever the AI loses power, it has to find the room's APC, hack it, and then force it to bring up the UI so the AI can change the APC settings.

This is pretty shit code.

For one, the AI only gets ONE chance to hack an APC per room it's in (it attempts when it enters a new room I believe, or maybe only once per power loss even), done automatically. Didn't work? Too bad. Should work now? Too bad, can't try again.
There is no button or command to attempt to run an APC finder again. Even if it should work.

Secondly is the problem with the UI. The UI will only pop up ONCE. If you close the window for whatever reason or have to relog, the UI is gone. There is no way to bring it back on screen, even if you were successful at hacking the APC.

Sometimes hacking just doesn't work, for whatever shitty reason. I had a round where I got a message that the APC just didn't exist, in a room it should have otherwise. I don't even know what causes this, but it's probably just shit AI code.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/bf6ee2a10511526d21a7db519c81721349e8f1ee/code/modules/mob/living/silicon/ai/life.dm#L97

relevant proc.

**Comment by YakumoChen** [comment]
I think I saw a PR that would have fixed this
