### ISSUE TITLE
buckle dragging yourself onto a chair/vehicle over a wormhole/teleporter is extremely fucky

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#42924]
you and your chair get teleported around in a really weird fashion that makes no sense.

**Comment by actioninja** [comment]
HAHA were you watching me fuck around with the janicart?

**Comment by ShizCalev** [comment]
no, but i was also a janitor and did this with the janicart just prior to opening the issue. :P

**Comment by kriskog** [comment]
Related to #42040. Soon as you try to move, the vehicle does and you get teleported to it.
