### ISSUE TITLE
Double-barrel shotty and Russian give inproper messages when unloading them

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#42934]
![bug5](https://user-images.githubusercontent.com/35217076/53430191-17305d00-39ff-11e9-8e2b-39c33ccb77f1.PNG)
![bug4](https://user-images.githubusercontent.com/35217076/53430398-742c1300-39ff-11e9-93e2-6e15d2d66f9f.PNG)

Gun has X ammo. I unload it. Get a message that I unloaded X+1 amount of ammo.

**Comment by ShizCalev** [comment]
@actioninja

**Comment by actioninja** [comment]
Aw what the fuck is this back? I thought I fixed this one in testing.

**Comment by ShizCalev** [comment]
#42837 @MadmanMartian you perhaps?

**Comment by actioninja** [comment]
I think I know what's wrong actually, let me test something.

**Comment by actioninja** [comment]
Yeah, I got it.
