### ISSUE TITLE
Setting stamina damage through VV deals only around 66% of requested damage.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#42941]
![](https://i.imgur.com/PVg95pt.png)

Setting 100 damage to stamina only deals 66.8, this occurs at other values like setting 40 resulting in 26.8 damage.

**Comment by OverlyGeneric** [comment]
This is a concern since we're moving closer to stamina-based combat.

Any clue what caused this?

**Comment by AnturK** [comment]
That's because that that silly damage to stamina coefficients on bodyparts that makes recieved and read damage completely unrelated. So if random limb pick chooses anything but head and chest it starts to get lower.

**Comment by Kierany9** [comment]
Stamina damage setting has been busted for a while now, and not just through VV, see #41942

**Comment by timothymtorres** [comment]
Fixed by #44671
