### ISSUE TITLE
Turbines generate no power

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#42943]
![](https://i.imgur.com/rY7oaGv.png)

This wasn't tested with station turbines, but lavaland's turbine generates no power at all right now, whether the door is open or not. Might have something to do with fusion?

**Comment by Unit2E** [comment]
I have noticed that when temperatures, or maybe moles, are too high that turbines lock up. I'm unsure if this a bug, though. It's also definitely not caused by fusion, even just burning tritium can cause the same lock up.

**Comment by MegaEmpirical** [comment]
I've seen that thing fail even when I just start it up. It's been a while but I've found it to be unreliable. Specifically the lavaland one.

**Comment by WJohn** [comment]
That might have been because gas miners frequently lock up until their tile is updated. Seen in #37064
