### ISSUE TITLE
Bronze Golems delete projectiles entirely.

### ISSUE THREAD

**Issue by KomradeSpectre** [tgstation/tgstation#42974]
Issue reported from  Round ID: 102864 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

I was a bronze golem, and upon getting shot initially with riot foam darts, I noticed they were not affecting me, and were actually deleting upon impact with me. I then had people around the station shoot at me with various guns to only find out that the projectiles are actually just deleting when they hit me. I think this is pretty priority critical.

**Comment by Tlaltecuhtli** [comment]
intended

**Comment by ShizCalev** [comment]
/datum/species/golem/clockwork

clockwork cult issue.

**Comment by ShizCalev** [comment]
What kind of projectiles? Were lasers hurting you at all?

clockwork golems are technically a type of robot, so they are by design immune to tasers/disables/ebows/ect.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/1b50671ca072dd646e98bee971a6d20d5c06a2de/code/modules/antagonists/clockcult/clock_structures/heralds_beacon.dm#L108

**Comment by KomradeSpectre** [comment]
Bronze Golems is what I meant, I will adjust the title accordingly, I know it was misleading now.

**Comment by ATH1909** [comment]
> Bronze Golems is what I meant, I will adjust the title accordingly, I know it was misleading now.
> Lasers didn't hurt me, disablers didn't affect me, HOS taser didn't do anything, a rocket didn't do anything, freeze beams did nothing, the bronze golem just deletes them when it procs the gong or something.

Wew.

https://m.youtube.com/watch?v=iO9usuZ9QzY
