### ISSUE TITLE
Xenobiology: Hungry or rabid slimes keep latching to and releasing bots

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#42992]
Tested on up-to-date local today.

#### Reproduction:
1. Spawn a bunch of slimes. 
2. Have Inspector Johnson drive by. 

Outcome: 
"sepia baby slime (532) has latched onto Inspector Johnson! "
"The sepia baby slime (532) has let go of Inspector Johnson! "
"sepia baby slime (532) has latched onto Inspector Johnson! "
"The sepia baby slime (532) has let go of Inspector Johnson! "

This repeats over and over again. Same thing with other bots.

**Comment by Time-Green** [comment]
Slimes can't eat bots, but they do target them so they get stuck trying to eat them
