### ISSUE TITLE
Buttons in the spawners menu don't do anything

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#43004]
Steps to reproduce:
1. Be a ghost (or an observer).
2. Open up the spawners menu (under the ghost tab).
3. Try to click "jump to" or "spawn" under one of the entries.
4. Observe that nothing seems to happen.

Do note that if you can find the physical location of a ghost spawner, you can still use it- you just can't just to it or spawn in it remotely with the spawners menu.

**Comment by DaxDupont** [comment]
Replicated

**Comment by Dennok** [comment]
Now it work. All buttons

**Comment by kriskog** [comment]
This is fixed
