### ISSUE TITLE
All cybernetic implants are broken

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43019]
## Round ID:
103038

## Testmerges:
https://github.com/tgstation/tgstation/pull/42958
https://github.com/tgstation/tgstation/pull/42930

## Reproduction:
Spawn any cybernetic implants, like a reviver or a laser gun, and examine it. It will say it is broken and also not work when surgically installed. This is also the case if it comes out of the exosuit fab. Strangely, the anti drop implant *does* work, even though it too says it is broken.

**Comment by SpaceManiac** [comment]
```
   var/broken_cyber_organ = TRUE //if the organ stopped working.
```

#42908 @ShizCalev looks like a pretty clear-cut mistake but lmk if something deeper is wrong

**Comment by ShizCalev** [comment]
oof yeah that's it.

**Comment by Fikou** [comment]
the same bug is with fleshy masses on pubby i think unless they are supposed to be broken
