### ISSUE TITLE
ED-209s can no longer be made because tazers have been replaced with disablers and require tazers to be made.

### ISSUE THREAD

**Issue by TothBrush** [tgstation/tgstation#43013]
## Reproduction:

Just try to make an ED-209. You can't because it requires tazers and doesn't accept disablers.

**Comment by ATH1909** [comment]
You can still make laser tag ED-209s, at least.

**Comment by anconfuzedrock** [comment]
Now a 209 uses the dragnet, so is fixed basically.

**Comment by Cyprex** [comment]
They require dragnets now, invalid issue.

**Comment by ExcessiveUseOfCobblestone** [comment]
Does the game imply that you're suppose to use a taser or can I close this?

**Comment by TothBrush** [comment]
What the fuck is a dragnet

**Comment by ExcessiveUseOfCobblestone** [comment]
@TothBrush kk ty
