### ISSUE TITLE
Mining sachel of holding full, destroying ore on "pickup"

### ISSUE THREAD

**Issue by TeoUltika** [tgstation/tgstation#43018]
Issue reported from  Round ID: 103031 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

For some reason, my mining sachel of holding says it is full. There is nothing in it. I still pick up ore from the ground, but it is instantly destroyed. I do not know what has caused this.

**Comment by TeoUltika** [comment]
Apparently my normal mining sachel is also full. It has nothing in it. The ore is also being destroyed when I pick it up.

**Comment by Angustmeta** [comment]
I recall having the same thing happen when carrying both a normal mining satchel and a SoH at the same time. Can't remember if they were in bag or pocket or both.

**Comment by ExcessiveUseOfCobblestone** [comment]
@kevinz000 storage?
