### ISSUE TITLE
snails can wear glasses

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#43032]
1. be snail
2. put on glasses

**Comment by Cyprex** [comment]
Problem?

**Comment by anconfuzedrock** [comment]
yeah pretty much

**Comment by ExcessiveUseOfCobblestone** [comment]
feature?

**Comment by tralezab** [comment]
the eyes are on the stalks so the glasses are just sitting on the snail's head, the fix is to offset the glasses to be on the stalks or just accept that it's pretty funny to see sunglasses and stalks
