### ISSUE TITLE
Mindshield implanters can break

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#43059]
The implant is consumed, but the implanter appears to be full still. You can still implant people, and it deconverts but doesn't transfer an implant, and gives a failure message. Happened twice, but I don't have reproduction steps. Seems to occur when using on a vessel/hivemind/rev/revhead

**Comment by Eskjjlj** [comment]
This isn't what happens. The implant fails on awakened vessels even if they have been freed it seems. But if you try to implant someone who is not a vessel it works.

**Comment by AnturK** [comment]
So is this specific to hiveminds or general ?

**Comment by HomocidlePancakes** [comment]
I always thought implant just doesn't get used up when you try to implant someone with resist

**Comment by Therapist1** [comment]
There are two types of ineffective implants: A. The person you’re implanting is a hivemind or a head of a revolution, this gives the ‘resists the implant’ message, and uses up the implant. B. The person you’re implanting already has one, this gives the ‘you fail to implant (x)!’. I’m thinking this is a case of B acting weird.

**Comment by davethwave** [comment]
Nanite mindshields also don't remove you from the hivemind which should be fixed. Not sure if they prevent you from being added to the hivemind though.

**Comment by py01** [comment]
I beleive the mindshield nanite program refuses to activate if you are in a hivemind, and it was intentionally done like that.

**Comment by davethwave** [comment]
I guess so. Makes sense. However it still shows that your mindshielded however.
