### ISSUE TITLE
turrets factions seem broke

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#43053]
they shoot at everyone by default (everything except attack mobs on)

**Comment by ExcessiveUseOfCobblestone** [comment]
which ones?

**Comment by Tlaltecuhtli** [comment]
the ones you build

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/90bda1452ba77412295cd43e341062a03bbb36af/code/game/machinery/porta_turret/portable_turret.dm#L67

https://github.com/tgstation/tgstation/blob/90bda1452ba77412295cd43e341062a03bbb36af/code/game/machinery/porta_turret/portable_turret.dm#L56-L61

https://github.com/tgstation/tgstation/blob/90bda1452ba77412295cd43e341062a03bbb36af/code/game/machinery/porta_turret/portable_turret_construct.dm#L146-L149

May have been it was just engaging something else

**Comment by Tlaltecuhtli** [comment]
nah it started shooting me as soon as i built it

**Comment by davethwave** [comment]
Were you set under arrest at the time when you built it? I think they automatically shoot at criminals as soon as they are built. However I could be wrong about that.
