### ISSUE TITLE
The HoP's cap is inconsistently off-center when worn by a standard borg

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#43056]
https://cdn.discordapp.com/attachments/411993431573790737/553356016226533408/offcenter.PNG
https://cdn.discordapp.com/attachments/411993431573790737/553356085717762058/offcenter2.PNG

It's on the right side of the borg (from their perspective) in the first image, but on the left side of the borg (from their perspective) in the second image.

Literally unplayable

**Comment by ATH1909** [comment]
Would stretching the hat (and its center stripe) by an extra pixel work, or would it look too weird?

**Comment by ShizCalev** [comment]
@ATH1909 it'd affect it on all humans and would probably look weird for it to be off center on them.

Borgs sadly aren't symmetrical, they all have 1 extra column of pixels.

**Comment by ShizCalev** [comment]
see #33399
