### ISSUE TITLE
all apcs broke and werent charging with power available

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#43064]
103192 bagil
all apcs werent able to charge from wires
it was so roundstart and kept happening the whole round

**Comment by Menshin** [comment]
Did cutting wires and relaying them fix the issue ?
Did reconstructing the APCs fix the issue ?
Were SMES also affected ?

**Comment by Tlaltecuhtli** [comment]
no

**Comment by Dennok** [comment]
Now apc charging as before, but can wait many time to start charging.

**Comment by kriskog** [comment]
Lots of power stuff has changed since, if this happens again open a new issue.
