### ISSUE TITLE
Mixing beer with other drinks breaks the sprite

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#43070]
## Reproduction:
1. Mix beer with the same quantity of any type of drink that has its own glass sprite (i.e. whiskey)
2. Take a sip if you're using the booze dispenser

![Screenshot_1](https://user-images.githubusercontent.com/38563876/54063538-3e600900-420d-11e9-951a-8137c76b2234.png)

**Comment by Whoneedspacee** [comment]
feature

**Comment by ExcessiveUseOfCobblestone** [comment]
> [tgstation/code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm](https://github.com/tgstation/tgstation/blob/a3fb736e89b5edd781ecb357259366c4291545be/code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm#L23-L28)
> 
> Lines 23 to 28 in [a3fb736](/tgstation/tgstation/commit/a3fb736e89b5edd781ecb357259366c4291545be)
> 
>  if(R.glass_icon_state) 
>  	icon_state = R.glass_icon_state 
>  else 
>  	var/mutable_appearance/reagent_overlay = mutable_appearance(icon, "glassoverlay") 
>  	reagent_overlay.color = mix_color_from_reagents(reagents.reagent_list) 
>  	add_overlay(reagent_overlay) 
> consider adding `icon_state = "glass_empty"` on 26 lol
