### ISSUE TITLE
pAIs in bots issues.

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#43081]
Issue reported from  Round ID: 103372 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

pAIs in firebots can't use their fire extinguisher.

pAIs in any bot don't have their pAI interface.

1) Build a firebot.
2) Get an active pAI.
3) Unlock the firebot's interface.
4) Install the pAI!
5) The pAI will lose its interface and be unable to extinguish anything.

**Comment by ShizCalev** [comment]
pAI not having their interface in bots is intentional as for all intents and purposes you've been transferred to the bot itself. 

firebot needs an UnarmedAttack() added to fix the extinguisher.
