### ISSUE TITLE
cult stun inhand is invisible

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#43085]
## Reproduction:

1.be cult
2.get stun
3.use stun

it had an inhand before I'm sure, I'm not sure what broke it, but I am sure that there shouldn't be what's completely comparable to stun gloves.

**Comment by SpaceManiac** [comment]
No round ID so I can't know if you were playing before or after #43067 was applied

**Comment by PKPenguin321** [comment]
Possible my PR didn't fix it... not sure
