### ISSUE TITLE
You can blind blind people with a flash

### ISSUE THREAD

**Issue by GuyonBroadway** [tgstation/tgstation#43098]
[Round ID]: 
I'll go one better and give you video evidence. https://youtu.be/S--3fMVBU7Q?t=585

## Testmerges: 
Not sure

## Reproduction: 
Give someone the blindness trauma and flash them.

Kinda makes no sense that you can blind a blinded person.

**Comment by ShizCalev** [comment]
lmao

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/05f2ac7317d3592e93c9e8e1fc41fa67fd276e95/code/modules/assembly/flash.dm#L118

Flashes intentionally bypass the blindness checks, otherwise you wouldn't be able to convert blind people. Same goes for cult stuns, kindled flames, and CQC granter books.

**Comment by GuyonBroadway** [comment]
Part of me agrees, and yet another part thinks that if the only way to powergame revs is to be blinded then that's also funny.


* flash *

"REVS BAR!"

"Who rev?"

"I dunno, I'm fucking blind."

**Comment by Nickkoranda** [comment]
Can't you stop flashes by using a blindfold? I thought that was the point of the old filepath, sunglasses/blindfold

**Comment by MegaEmpirical** [comment]
Typically blind people are not completely blind, and in our case this is most certainly true since they can see in about a half tile radius. So a flash could still potentially work for both stunning and converting.

**Comment by Barhandar** [comment]
This kinda "seeing" is just player assistance to be able to actually navigate. A simulation of your sense of touch, if you will. Blindfold does exactly the same thing despite completely blocking sight.

**Comment by MegaEmpirical** [comment]
Still, it can be used to argue that they have a very a basic amount of sight. It's just bad enough to be considered blind. The blindfold is obviously a crappy blindfold that let's you see through it.

**Comment by nemvar** [comment]
Feature.

**Comment by PKPenguin321** [comment]
No?

**Comment by MegaEmpirical** [comment]
Working on the blind wasn't inherently nonsense but working on people with no eyes would be fucked up.
