### ISSUE TITLE
Toolboxes made from an Autolathe are not able to be made into floorbots

### ISSUE THREAD

**Issue by conflictcode** [tgstation/tgstation#43109]
Problem Description: Tool box created in the autolathe is /obj/item/storage/toolbox and is unable to be made into floorbot.

What did you expect to happen: A floorbot assembly to appear.

What happened instead: Nothing

Why is this bad/What are the consequences: Have to manually collect toolboxes and empty them leading to a fuckton of tools all over the place

Steps to reproduce the problem: 

1. Construct a tool box in an Autolathe.

2. Click on constructed toolbox with 10 floor tiles.

3. Instead of a floorbot assembly being created, nothing happens.

**Comment by conflictcode** [comment]
fixed in PR #43110

**Comment by Cyprex** [comment]
I was under the impression this was intended
