### ISSUE TITLE
Consistency issue: Blind people can use some analysers but not others.

### ISSUE THREAD

**Issue by nemvar** [tgstation/tgstation#43119]
Blind people are able to use some analysers like the plant analyser and the chemical scanner from the health analyser but not other such as atmospheric analyers and the damage scanner of the health analyser.

ANALYSERS!!

**Comment by nicbn** [comment]
Btw I think they should be able to use any analyser (they could have braile, sound or whatever) because some jobs need them and all

**Comment by timothymtorres** [comment]
I tried fixing this with #66287 but maintainer ruling to not restrict blind people so I'm closing this.  I really feel like this is a bug though.
