### ISSUE TITLE
space dragons shoot fire through windows

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#43111]

**Comment by Whoneedspacee** [comment]
oops my bad

**Comment by IndieanaJones** [comment]
As of current, lesser ash drakes and regular ash drakes also shoot fire through windows.  Not sure if it's my place to fix, or if it should be discussed if any of the dragon subspecies should be able to shoot fire through windows.

**Comment by Whoneedspacee** [comment]
no it's just not taking into account the density i think. it definitely shouldn't check on atmosblock cause stuff like the holobarrier does it but i'd just check for density on open turfs i think.

**Comment by IndieanaJones** [comment]
This bug has been fixed as of the Space Dragon Rework.
