### ISSUE TITLE
Lone operatives can buy assault pod controls.

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#43118]
It's time to switch uplink lists from being linked to gamemodes directly to something freeform.

**Comment by MegaEmpirical** [comment]
... Does it work when they call it?

**Comment by AnturK** [comment]
The issue is they can't call it since controls and the pod itself are in syndie base.

**Comment by MegaEmpirical** [comment]
I thought the pod was launch specifically by controls bought via the uplink?

"This device allows you to aim and use the assault pod located to the east of the syndicate base."
From the wiki.

**Comment by YakumoChen** [comment]
you need the item to access the controls on the pod, but that doesn't imply the device itself is a remote control

**Comment by py01** [comment]
Lone ops can additionally buy cyborg summoners, which are also unusable by lone ops since they only work on the op base

**Comment by projectkepler-ru** [comment]
No longer applicable

**Comment by Sealed101** [comment]
closed by #84430
