### ISSUE TITLE
pka + mineral walls + teleport

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#43123]
103606
teleporting on a mineral wall with an hand tele makes it impossible to shoot around with a pka

**Comment by ExcessiveUseOfCobblestone** [comment]
can't you just shoot into the black area?

**Comment by Tlaltecuhtli** [comment]
i was shooting but nothing was being hit

**Comment by Tlaltecuhtli** [comment]
also is  mining walls being a teleportable tile even intended

**Comment by ExcessiveUseOfCobblestone** [comment]
"sure"

**Comment by kriskog** [comment]
If the portal is still up, the KPA projectile goes through it when shot. Wasn't able to reproduce it otherwise, gonna call this intended.
