### ISSUE TITLE
Sentient Disease Cough Not Infecting People

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#43133]
Issue reported from  Round ID: 103848 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

People next to / nearby the host aren't getting infected when I cough. Some had a different disease, others had internals on- but some had neither.

Steps:
1) Put a human next to a human with a sentient disease.
2) Have the disease cough.

**Comment by kriskog** [comment]
There are lots of reasons the cough might not have spread your disease, like if your host has covered their mouth, the one you are trying to infect isnt breathing, or has a stealth virus with much higher resistance. Sentient diseases seem to spread as they should currently, you may open a new issue if you observe this again.
