### ISSUE TITLE
stunbaton sprite is invisible but not inhands

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#43139]
YOU JUST HAD TO MAKE IT TWO WORDS DIDN'T YOU

**Comment by ShizCalev** [comment]
@anconfuzedrock the sprite wasn't touched at all??????

**Comment by anconfuzedrock** [comment]
#43140 *dabs in shizcalev*

**Comment by ShizCalev** [comment]
>using the name of the item to generate iconstate

g fucking g
