### ISSUE TITLE
Silicons can't talk on AI private if they try to use the P prefix

### ISSUE THREAD

**Issue by VileBeggar** [tgstation/tgstation#43130]
## Round ID: 
103577

## Reproduction:

Using the prefix p, which is the prefix for talking on the AI private channel, as an AI (or perhaps any type of silicon) will give you this error:
![image](https://user-images.githubusercontent.com/17518895/54389836-5b7b5880-46a1-11e9-9f45-b3f964b766cb.png)

**Comment by AnturK** [comment]
AI private is o, p is admin (why the hell is there admin radio shortcut)

**Comment by VileBeggar** [comment]
> 
> 
> AI private is o, p is admin (why the hell is there admin radio shortcut)

i woke up in the middle of night because of this but i'm confused by the admin shortcut as well
