### ISSUE TITLE
Missing Graphics.

### ISSUE THREAD

**Issue by Mrwiggles826** [tgstation/tgstation#43141]
Reporting client version: 512 90% of my graphics go missing on round start.

**Comment by PKPenguin321** [comment]
Screenshot? BYOND version?

**Comment by Cyprex** [comment]
We need the part after 512 too, For example 512.1464

**Comment by Dennok** [comment]
and meby you just need wait to download additional grafics

**Comment by jlsnow301** [comment]
Closing this due to:
- general inactivity
- inability to reproduce
- lack of specificity
