### ISSUE TITLE
Xenos do not turn into husks if they burn to death.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43149]
## Reproduction:
1. Spawn a xeno hunter in the thunderdome
2. Spawn a hotspot on the xeno
3. Watch as it dies, having taken 400 burn damage, and never husks.

I've seen xenos with upwards of _900_ burn damage from huge amounts of firestacks, and they don't husk either. I think it's safe to say it's broken.

**Comment by nemvar** [comment]
Xenos are supposed to husk?

**Comment by Ratvar** [comment]
Xenos are humanoids that can husk? I dooon't thiiink sooo

**Comment by WJohn** [comment]
They definitely used to husk in the past, and they have sprites for it.
