### ISSUE TITLE
Curator has reduced access during skeleton shifts.

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#43155]
Directly from tgstation/code/modules/jobs/job_types/curator.dm

	"access = list(ACCESS_LIBRARY)
	minimal_access = list(ACCESS_LIBRARY, ACCESS_CONSTRUCTION,ACCESS_MINING_STATION)"

This prevents Curator from accessing Construction and Mining Station basically reverting them back to Librarian access-wise. There's also a space missing between "ACCESS_CONSTRUCTION," and "ACCESS_MINING_STATION" but that probably doesn't matter. 

I feel bad for the low-pop Curator, though.

It should be:
	"access = list(ACCESS_LIBRARY, ACCESS_CONSTRUCTION, ACCESS_MINING_STATION)
	minimal_access = list(ACCESS_LIBRARY, ACCESS_CONSTRUCTION, ACCESS_MINING_STATION)"

**Comment by 81Denton** [comment]
Thanks for the detailed feedback, I'll open a PR for this soon

**Comment by Tlaltecuhtli** [comment]
isnt skeleton access considering the department? like if ther are no atmos engis get skeleton atmos access in what department is librarian?

**Comment by 81Denton** [comment]
Curator is in the civilian department

**Comment by Tlaltecuhtli** [comment]
so then how do they get skele access? lack of assistants?

**Comment by 81Denton** [comment]
If the player count is below the number in the config setting MINIMAL_ACCESS_THRESHOLD, it's skeleton shift

**Comment by davethwave** [comment]
Oh the irony.
