### ISSUE TITLE
Glitter looks terrible now.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43157]
## Round ID:
104016

## Reproduction:
Glitter uses atmos sprites, such as freon. Now that the atmos sprites have changed, glitter looks like it's made of gas and it not at all like glitter. Should probably be using its own sprites, or at least some of the old atmos sprites.

**Comment by SpaceManiac** [comment]
Kind of intended: #41644

Though if you have a concrete proposal feel free to duke it out in PRs

**Comment by Barhandar** [comment]
The point is to confuse people into thinking it's a gas flood; the joke doesn't work anymore with the new terrible gas sprites.
