### ISSUE TITLE
people who are grabbed while buckled move around in weird ways

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#43153]
repo:
buckle a dude
grab him
he starts facing you instead of maintaining his direction as was the normal/old behavior.

**Comment by 4dplanner** [comment]
Just tested on an old branch and this still occurs, are you sure this is my fault?

**Comment by ShizCalev** [comment]
@4dplanner Sorry, isn't related to you. Cause is #41768, which was merged while I was off on my 2 month vacation.
