### ISSUE TITLE
Goose Kills Allied Mobs

### ISSUE THREAD

**Issue by IndieanaJones** [tgstation/tgstation#43169]
## Reproduction:
1. Use gold slime cores
2. Goose spawns
3. Goose proceeds to kill other mobs

Not sure if this should actually be fixed, might be the nerf to gold slime cores a few people have wanted in an unexpected form.

**Comment by ShizCalev** [comment]
mad lads

**Comment by ShizCalev** [comment]
were you in harm intent by chance?

**Comment by PKPenguin321** [comment]
This is intentional, check their code. They have a 25% chance every so often to just attack the nearest mob at random

**Comment by ShizCalev** [comment]
oh yeah, attack_same is TRUE
