### ISSUE TITLE
Leg spasm can force you out of closed cryo cell(and possibly more things)

### ISSUE THREAD

**Issue by OmegaShoots** [tgstation/tgstation#43188]
Issue reported from  Round ID: 104086

Had leg spasm trauma from being cloned, was put in cryo that was set to manual so it didn't auto eject me, after my clone damage got healed I tried to resist out of the cell which takes 30 seconds but my trauma somehow forced me out early, duplicated my body, kept my camera stuck in the cell and let me move around outside.

**Comment by nicbn** [comment]
Legspasmed out of your own body

**Comment by PKPenguin321** [comment]
Can happen with genetic scanners too
