### ISSUE TITLE
AI law uploading's fucked

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#43197]
Issue reported from  Round ID: 104106 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
Reporting client version: 512
#43152: 'Panic bunker message is now a config.' by kevinz000 at commit f8777444d6
#42780: 'Automatic deadminning' by ShizCalev at commit aee9417772

Non-core freeform erases all other laws, reset board fails to set some laws up (it resulted in only laws 2 and 3 of asimov getting added to the AI), et cetera. Check logs of round 104102 for the freeform law issue.

**Comment by timothymtorres** [comment]
@Barhandar can you better identify the steps to reproduce this?  I tried to look at the logs but I wasn't able to find the round report for changes to the AI lawset unfortunately.
