### ISSUE TITLE
Lavaland hardsuits interfere with the magical lavaland loot

### ISSUE THREAD

**Issue by Daxxed** [tgstation/tgstation#43200]
## Reproduction:
Wear champions/inquisitor hardsuit
Grab honkmother's staff
>Something is interfering with the staff of the honkmother. 

I guess it has to do with the recent update that makes the wizard hardsuit antimagic ?
I know the weapons are magical but these are just ERT suits, not wizard.

**Comment by SpaceManiac** [comment]
Not related to the recent change, paranormal response team hardsuits were antimagic before the fix

**Comment by tralezab** [comment]
it kind of makes sense for the paranormal hardsuits to resist magic though, that should stay. I could totally see the removal of antimagic from the champion one

**Comment by Daxxed** [comment]
> 
> 
> Not related to the recent change, paranormal response team hardsuits were antimagic before the fix

Apologies, I forgot to keep track of changelog for a while it probably was something else.
I do not really care about the lore behind it but it seems stupid that a miner cannot use the items he finds in combination with eachother.

Perhaps we can replace both the hardsuits with ones that are not anti-magic ?

**Comment by ATH1909** [comment]
I vote for changing antimagic to not prevent you from producing magical effects from staves, wands, etc. (although it'd still block those magical effects if you got hit by them).

In other words, you should be able to use a wand of fireball or the like while wearing a champion's hardsuit, but you shouldn't be able to cast the fireball spell (directly). The champion's hardsuit would still block fireballs from a wand of fireball that were fired at you, of course (well, if they hit you directly; fireballs get around antimagic if a magic-proof thing doesn't get hit directly by one).

**Comment by Daxxed** [comment]
That would be a bit overpowered but it IS pretty rare to find both of those items together.

**Comment by ATH1909** [comment]
This'd also screw over adamantium golems that wanted to use cool magical lavaland loot as well.
