### ISSUE TITLE
It is not possible to disable generation of caves on asteroid turfs

### ISSUE THREAD

**Issue by CorruptComputer** [tgstation/tgstation#43207]
## Reproduction:
Create asteroid.
Caves generate.

There is currently no possible way to disable this behavior, and it causes issues as seen in #32728. This also limits mappers abilities to create locations which should not have caves generated. 

Proc in question:
```
/turf/open/floor/plating/asteroid/airless/cave/proc/produce_tunnel_from_data(tunnel_length, excluded_dir = -1)
```

I tried to fix it myself but I suck at DM code. Also a side note, it seems strange to me that this proc is included under floors when it effects walls. It also only runs at world start, so it could possibly be moved somewhere else or refactored to clean up that file a bit, but again I suck a DM code so there may be a specific reason as to why its there.

**Comment by Dennok** [comment]
This yes but as i know we have special asteroid/rock walls what unaffected by caves, or areas.
Another minor thing, cave generator lost asteroid toorfs on lavalend.

**Comment by CorruptComputer** [comment]
@Dennok I understand that, but some stations still use Asteroid turfs on them (including AsteroidStation, which I'm still maintaining). Really limits the ability of mappers to create areas with Asteroid walls which do not generate caves. I have tried every type of Asteroid wall, they all do it.

**Comment by Dennok** [comment]
![image](https://user-images.githubusercontent.com/7734424/59877853-8f0c0400-93af-11e9-9a6d-97a42d6d2b85.png)
here is spawning of spawner of cave

**Comment by Dennok** [comment]
/turf/closed/mineral dont have mineralSpawnChanceList so it dont generate caves and ores

**Comment by Dennok** [comment]
and you can modify it on map
![image](https://user-images.githubusercontent.com/7734424/59880483-cd0c2680-93b5-11e9-9e0f-d15543e7a2ee.png)

**Comment by CorruptComputer** [comment]
@Dennok Yes, but a mineral-less asteroid would be pretty boring to dig in, would it not? I think it would be better as a boolean such as `spawnCaves`.

**Comment by Dennok** [comment]
just
remove
caves spawner from SpawnChanceList in the map editor or create wall with no spawner in it.
NO any `spawnCaves` boolean

best way make it like rivers spawner that separate proc dont bound to the turf
