### ISSUE TITLE
Shitton of errors and runtimes when starting nightly 

### ISSUE THREAD

**Issue by davv1** [tgstation/tgstation#43216]
## Reproduction:

Just start latest nightly.

Gives a shitton of errors.

`[08:28:06] Runtime in ,: bad icon operation
  proc name: New (/icon/New)
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
  src: /icon (/icon)
  call stack:
  /icon (/icon): New('sound/effects/picaxe1.ogg', "catcher", null, null, null)
   (/obj/screen/click_catcher): UpdateGreed(15, 15)
  Davv1 (/client): apply clickcatcher()
  /datum/hud (/datum/hud): show hud(1, null)
  Davv1 (/mob/dead/new_player): Login()
  Davv1 (/mob/dead/new_player): Login()
  Davv1 (/client): New(null)
[08:28:07] Runtime in ,: bad icon operation
  proc name: New (/icon/New)
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
  src: /icon (/icon)
  call stack:
  /icon (/icon): New('sound/effects/picaxe1.ogg', "catcher", null, null, null)
   (/obj/screen/click_catcher): UpdateGreed(15, 15)
  Davv1 (/client): apply clickcatcher()
  Davv1 (/client): change view("15x15")
  Davv1 (/mob/dead/new_player): Login()
  Davv1 (/mob/dead/new_player): Login()
  Davv1 (/client): New(null)
[08:28:07] Runtime in ,: bad icon operation
  proc name: New (/icon/New)
  src: /icon (/icon)
  call stack:
  /icon (/icon): New('sound/effects/picaxe1.ogg', "catcher", null, null, null)
   (/obj/screen/click_catcher): UpdateGreed(15, 15)
  Davv1 (/client): apply clickcatcher()
  Davv1 (/client): New(null)
[08:28:27] Runtime in ,: bad icon operation
  proc name: New (/icon/New)
  usr: Viviana Russell () (/mob/living/carbon/human/dummy)
  src: /icon (/icon)
  call stack:
  /icon (/icon): New('sound/misc/desceration-03.ogg', null, null, null, null)
  Human (/datum/species/human): handle hair(Viviana Russell (/mob/living/carbon/human/dummy), null)
  Viviana Russell (/mob/living/carbon/human/dummy): update hair()
  the brain (/obj/item/organ/brain): Insert(Viviana Russell (/mob/living/carbon/human/dummy), 1, 1)
  Human (/datum/species/human): regenerate organs(Viviana Russell (/mob/living/carbon/human/dummy), Human (/datum/species/human), 1)
  Human (/datum/species/human): on species gain(Viviana Russell (/mob/living/carbon/human/dummy), Human (/datum/species/human))
  Human (/datum/species/human): on species gain(Viviana Russell (/mob/living/carbon/human/dummy), Human (/datum/species/human))
  Viviana Russell (/mob/living/carbon/human/dummy): set species(/datum/species/human (/datum/species/human), 1)
  Viviana Russell (/mob/living/carbon/human/dummy): set species(/datum/species/human (/datum/species/human), 1)
  Viviana Russell (/mob/living/carbon/human/dummy): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(Viviana Russell (/mob/living/carbon/human/dummy), /list (/list))
  Viviana Russell (/mob/living/carbon/human/dummy): New(1)
  generate or wait for human dummy("dummy_preference_preview")
  /datum/preferences (/datum/preferences): update preview icon()
  /datum/preferences (/datum/preferences): ShowChoices(Davv1 (/mob/dead/new_player))
  Davv1 (/mob/dead/new_player): Topic("src=\[mob_5];show_preferences=...", /list (/list))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
[08:28:27] Runtime in ,: bad icon operation
  proc name: New (/icon/New)
  usr: Viviana Russell () (/mob/living/carbon/human/dummy)
  src: /icon (/icon)
  call stack:
  /icon (/icon): New('sound/vox_fem/above.ogg', "static", null, null, null)
  Viviana Russell (/mob/living/carbon/human/dummy): generateStaticOverlay()
  Viviana Russell (/mob/living/carbon/human/dummy): Initialize(1)
  Viviana Russell (/mob/living/carbon/human/dummy): Initialize(1)
  Viviana Russell (/mob/living/carbon/human/dummy): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(Viviana Russell (/mob/living/carbon/human/dummy), /list (/list))
  Viviana Russell (/mob/living/carbon/human/dummy): New(1)
  generate or wait for human dummy("dummy_preference_preview")
  /datum/preferences (/datum/preferences): update preview icon()
  /datum/preferences (/datum/preferences): ShowChoices(Davv1 (/mob/dead/new_player))
  Davv1 (/mob/dead/new_player): Topic("src=\[mob_5];show_preferences=...", /list (/list))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
[08:28:27] Runtime in ,: bad icon operation
  proc name: New (/icon/New)
  usr: Viviana Russell () (/mob/living/carbon/human/dummy)
  src: /icon (/icon)
  call stack:
  /icon (/icon): New('sound/vox_fem/above.ogg', "blank", null, null, null)
  Viviana Russell (/mob/living/carbon/human/dummy): generateStaticOverlay()
  Viviana Russell (/mob/living/carbon/human/dummy): Initialize(1)
  Viviana Russell (/mob/living/carbon/human/dummy): Initialize(1)
  Viviana Russell (/mob/living/carbon/human/dummy): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(Viviana Russell (/mob/living/carbon/human/dummy), /list (/list))
  Viviana Russell (/mob/living/carbon/human/dummy): New(1)
  generate or wait for human dummy("dummy_preference_preview")
  /datum/preferences (/datum/preferences): update preview icon()
  /datum/preferences (/datum/preferences): ShowChoices(Davv1 (/mob/dead/new_player))
  Davv1 (/mob/dead/new_player): Topic("src=\[mob_5];show_preferences=...", /list (/list))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
[08:28:27] Runtime in ,: bad icon operation
  proc name: New (/icon/New)
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
  src: /icon (/icon)
  call stack:
  /icon (/icon): New('sound/machines/terminal_button...', "shirt_assblastusa", null, null, null)
  generate female clothing("shirt_assblastusa", "shirt_assblastusa", 'sound/machines/terminal_button...', null)
  wear female version("shirt_assblastusa", 'sound/machines/terminal_button...', 22, null)
  Human (/datum/species/human): handle body(Carolyn Robinson (/mob/living/carbon/human/dummy))
  Carolyn Robinson (/mob/living/carbon/human/dummy): update body()
  Carolyn Robinson (/mob/living/carbon/human/dummy): regenerate icons()
  the eyes (/obj/item/organ/eyes): Remove(Carolyn Robinson (/mob/living/carbon/human/dummy), 1)
  Human (/datum/species/human): regenerate organs(Carolyn Robinson (/mob/living/carbon/human/dummy), Human (/datum/species/human), 1)
  Human (/datum/species/human): on species gain(Carolyn Robinson (/mob/living/carbon/human/dummy), Human (/datum/species/human))
  Human (/datum/species/human): on species gain(Carolyn Robinson (/mob/living/carbon/human/dummy), Human (/datum/species/human))
  Carolyn Robinson (/mob/living/carbon/human/dummy): set species(/datum/species/human (/datum/species/human), 0)
  Carolyn Robinson (/mob/living/carbon/human/dummy): set species(/datum/species/human (/datum/species/human), 0)
  /datum/preferences (/datum/preferences): copy to(Carolyn Robinson (/mob/living/carbon/human/dummy), 1)
  /datum/preferences (/datum/preferences): update preview icon()
  /datum/preferences (/datum/preferences): ShowChoices(Davv1 (/mob/dead/new_player))
  Davv1 (/mob/dead/new_player): Topic("src=\[mob_5];show_preferences=...", /list (/list))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
[08:28:27] Runtime in ,: bad icon operation
  proc name: New (/icon/New)
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
  src: /icon (/icon)
  call stack:
  /icon (/icon): New('sound/effects/genetics.ogg', "female_top", null, null, null)
  generate female clothing("shirt_assblastusa", "shirt_assblastusa", 'sound/machines/terminal_button...', null)
  wear female version("shirt_assblastusa", 'sound/machines/terminal_button...', 22, null)
  Human (/datum/species/human): handle body(Carolyn Robinson (/mob/living/carbon/human/dummy))
  Carolyn Robinson (/mob/living/carbon/human/dummy): update body()
  Carolyn Robinson (/mob/living/carbon/human/dummy): regenerate icons()
  the eyes (/obj/item/organ/eyes): Remove(Carolyn Robinson (/mob/living/carbon/human/dummy), 1)
  Human (/datum/species/human): regenerate organs(Carolyn Robinson (/mob/living/carbon/human/dummy), Human (/datum/species/human), 1)
  Human (/datum/species/human): on species gain(Carolyn Robinson (/mob/living/carbon/human/dummy), Human (/datum/species/human))
  Human (/datum/species/human): on species gain(Carolyn Robinson (/mob/living/carbon/human/dummy), Human (/datum/species/human))
  Carolyn Robinson (/mob/living/carbon/human/dummy): set species(/datum/species/human (/datum/species/human), 0)
  Carolyn Robinson (/mob/living/carbon/human/dummy): set species(/datum/species/human (/datum/species/human), 0)
  /datum/preferences (/datum/preferences): copy to(Carolyn Robinson (/mob/living/carbon/human/dummy), 1)
  /datum/preferences (/datum/preferences): update preview icon()
  /datum/preferences (/datum/preferences): ShowChoices(Davv1 (/mob/dead/new_player))
  Davv1 (/mob/dead/new_player): Topic("src=\[mob_5];show_preferences=...", /list (/list))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
[08:28:27] Runtime in ,: bad icon operation
  proc name: Blend (/icon/proc/Blend)
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
  src: /icon (/icon)
  call stack:
  /icon (/icon): Blend(/icon (/icon), 2, 1, 1)
  generate female clothing("shirt_assblastusa", "shirt_assblastusa", 'sound/machines/terminal_button...', null)
  wear female version("shirt_assblastusa", 'sound/machines/terminal_button...', 22, null)
  Human (/datum/species/human): handle body(Carolyn Robinson (/mob/living/carbon/human/dummy))
  Carolyn Robinson (/mob/living/carbon/human/dummy): update body()
  Carolyn Robinson (/mob/living/carbon/human/dummy): regenerate icons()
  the eyes (/obj/item/organ/eyes): Remove(Carolyn Robinson (/mob/living/carbon/human/dummy), 1)
  Human (/datum/species/human): regenerate organs(Carolyn Robinson (/mob/living/carbon/human/dummy), Human (/datum/species/human), 1)
  Human (/datum/species/human): on species gain(Carolyn Robinson (/mob/living/carbon/human/dummy), Human (/datum/species/human))
  Human (/datum/species/human): on species gain(Carolyn Robinson (/mob/living/carbon/human/dummy), Human (/datum/species/human))
  Carolyn Robinson (/mob/living/carbon/human/dummy): set species(/datum/species/human (/datum/species/human), 0)
  Carolyn Robinson (/mob/living/carbon/human/dummy): set species(/datum/species/human (/datum/species/human), 0)
  /datum/preferences (/datum/preferences): copy to(Carolyn Robinson (/mob/living/carbon/human/dummy), 1)
  /datum/preferences (/datum/preferences): update preview icon()
  /datum/preferences (/datum/preferences): ShowChoices(Davv1 (/mob/dead/new_player))
  Davv1 (/mob/dead/new_player): Topic("src=\[mob_5];show_preferences=...", /list (/list))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
[08:28:27] Runtime in ,: bad icon operation
  proc name: New (/icon/New)
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
  src: /icon (/icon)
  call stack:
  /icon (/icon): New('sound/machines/terminal_button...', "shirt_assblastusa", null, null, null)
  generate female clothing("shirt_assblastusa", "shirt_assblastusa", 'sound/machines/terminal_button...', null)
  wear female version("shirt_assblastusa", 'sound/machines/terminal_button...', 22, null)
  Human (/datum/species/human): handle body(Carolyn Robinson (/mob/living/carbon/human/dummy))
  Carolyn Robinson (/mob/living/carbon/human/dummy): update body()
  /datum/preferences (/datum/preferences): copy to(Carolyn Robinson (/mob/living/carbon/human/dummy), 1)
  /datum/preferences (/datum/preferences): update preview icon()
  /datum/preferences (/datum/preferences): ShowChoices(Davv1 (/mob/dead/new_player))
  Davv1 (/mob/dead/new_player): Topic("src=\[mob_5];show_preferences=...", /list (/list))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
[08:28:27] Runtime in ,: bad icon operation
  proc name: New (/icon/New)
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
  src: /icon (/icon)
  call stack:
  /icon (/icon): New('sound/effects/genetics.ogg', "female_top", null, null, null)
  generate female clothing("shirt_assblastusa", "shirt_assblastusa", 'sound/machines/terminal_button...', null)
  wear female version("shirt_assblastusa", 'sound/machines/terminal_button...', 22, null)
  Human (/datum/species/human): handle body(Carolyn Robinson (/mob/living/carbon/human/dummy))
  Carolyn Robinson (/mob/living/carbon/human/dummy): update body()
  /datum/preferences (/datum/preferences): copy to(Carolyn Robinson (/mob/living/carbon/human/dummy), 1)
  /datum/preferences (/datum/preferences): update preview icon()
  /datum/preferences (/datum/preferences): ShowChoices(Davv1 (/mob/dead/new_player))
  Davv1 (/mob/dead/new_player): Topic("src=\[mob_5];show_preferences=...", /list (/list))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
[08:28:28] Runtime in ,: bad icon operation
  proc name: Blend (/icon/proc/Blend)
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
  src: /icon (/icon)
  call stack:
  /icon (/icon): Blend(/icon (/icon), 2, 1, 1)
  generate female clothing("shirt_assblastusa", "shirt_assblastusa", 'sound/machines/terminal_button...', null)
  wear female version("shirt_assblastusa", 'sound/machines/terminal_button...', 22, null)
  Human (/datum/species/human): handle body(Carolyn Robinson (/mob/living/carbon/human/dummy))
  Carolyn Robinson (/mob/living/carbon/human/dummy): update body()
  /datum/preferences (/datum/preferences): copy to(Carolyn Robinson (/mob/living/carbon/human/dummy), 1)
  /datum/preferences (/datum/preferences): update preview icon()
  /datum/preferences (/datum/preferences): ShowChoices(Davv1 (/mob/dead/new_player))
  Davv1 (/mob/dead/new_player): Topic("src=\[mob_5];show_preferences=...", /list (/list))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
[08:28:28] Runtime in ,: bad icon operation
  proc name: New (/icon/New)
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
  src: /icon (/icon)
  call stack:
  /icon (/icon): New('sound/vox_fem/above.ogg', "nothing", null, null, null)
  /datum/preferences (/datum/preferences): update preview icon()
  /datum/preferences (/datum/preferences): ShowChoices(Davv1 (/mob/dead/new_player))
  Davv1 (/mob/dead/new_player): Topic("src=\[mob_5];show_preferences=...", /list (/list))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
[08:28:28] Runtime in ,: bad icon operation
  proc name: New (/icon/New)
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
  src: /icon (/icon)
  call stack:
  /icon (/icon): New('sound/vox_fem/above.ogg', "nothing", null, null, null)
  getFlatIcon(Carolyn Robinson (/mob/living/carbon/human/dummy), null, null, null, null, 1, 0)
  /datum/preferences (/datum/preferences): update preview icon()
  /datum/preferences (/datum/preferences): ShowChoices(Davv1 (/mob/dead/new_player))
  Davv1 (/mob/dead/new_player): Topic("src=\[mob_5];show_preferences=...", /list (/list))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
  Davv1 (/client): Topic("src=\[mob_5];show_preferences=...", /list (/list), Davv1 (/mob/dead/new_player))
[08:28:28] Runtime in ,: bad icon operation
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
[08:28:28] Runtime in icons.dm,751: bad icon
  proc name: getFlatIcon (/proc/getFlatIcon)
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
[08:28:28] Runtime in icons.dm,874: Cannot execute null.Width().
  proc name: getFlatIcon (/proc/getFlatIcon)
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
[08:28:28] Runtime in ,: bad icon operation
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
[08:28:29] Runtime in ,: bad icon operation
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
[08:28:29] Runtime in ,: bad icon operation
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
[08:28:29] Runtime in icons.dm,751: bad icon
  proc name: getFlatIcon (/proc/getFlatIcon)
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
[08:28:29] Runtime in icons.dm,874: Cannot execute null.Width().
  proc name: getFlatIcon (/proc/getFlatIcon)
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
[08:28:29] Runtime in ,: bad icon operation
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
[08:28:29] Runtime in ,: bad icon operation
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
[08:28:29] Runtime in ,: bad icon operation
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
[08:28:29] Runtime in icons.dm,751: bad icon
  proc name: getFlatIcon (/proc/getFlatIcon)
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
[08:28:29] Runtime in icons.dm,874: Cannot execute null.Width().
  proc name: getFlatIcon (/proc/getFlatIcon)
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
[08:28:30] Runtime in ,: bad icon operation
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)
[08:28:30] Runtime in ,: bad icon operation
  usr: Davv1 (davv1) (/mob/dead/new_player)
  usr.loc: The plating (8,174,1) (/turf/open/floor/plating)`

**Comment by Cyprex** [comment]
You likely downloaded a broken build from somewhere, where are you getting this from?

**Comment by davv1** [comment]
From description of tgstation github, nightlies builds server.

**Comment by davv1** [comment]
It's not first time I try to download this, and it got shittons of bugs.

https://tgstation13.download/nightlies/ here's link

**Comment by AnturK** [comment]
I didn't even knew we had this, but from quick glance resources are corrupted. It's placing sound files where icons should be. Rebuilding rsc will most likely fix this.

**Comment by davv1** [comment]
Rebuilding resources are taking time, and nightlies were provided to reduce time which is required to download and compile from codebase, from what it seems.

**Comment by AnturK** [comment]
Oh, i don't disagree this is an issue, just not really to do with the code.
