### ISSUE TITLE
Cheesy way to get rid of clown car

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#43224]
>Traitor clown: gets clown car
Me: AI LAW 2 DISABLE GRAVITY THERE IS A CLOWN CAR
Traitor clown: *dies*

20TC item that can be 100% countered by something they can't control. N I C E

**Comment by Tlaltecuhtli** [comment]
dont buy it then lol

**Comment by HomocidlePancakes** [comment]
I don't even play clown you nerd.
