### ISSUE TITLE
Headless Spacemen Make for Terrible Devils

### ISSUE THREAD

**Issue by Myphicbowser** [tgstation/tgstation#43245]
Issue reported from  Round ID: 104272 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Simply said I was beheaded as a plasmaman after a TC trade so I could be a devil, said I was back alive and nothing happened when I rentered my corpse, nothing worked to bring me back

**Comment by bobbahbrown** [comment]
Could you clarify why you were beheaded, and what you meant by you were back alive and nothing happened when you re-entered the corpse? Do you mean you used the verb as a ghost to re-enter your corpse, and it didn't put you back in your body?

Player was Gold VII in this round.

https://tgstation13.org/parsed-logs/sybil/data/logs/2019/03/21/round-104272/
https://scrubby.melonmesa.com/round/104272

**Comment by Myphicbowser** [comment]
Yeah yeah aight, so someone behaeded me with a dual energy sword, after i died the "We arise again" showed up in my chat, indicating i should have revived, so I ahelped when it didnt work and the admin Plapatin told me to re-enter my body, which I did and after not reviving he told me to post a report

**Comment by davethwave** [comment]
Its not just plasmamen that has this problem. Beheading a devil in any way messes up their revival.

**Comment by MegaEmpirical** [comment]
I was perpetually on fire once as a plasmaman devil. That was 'fun'.

**Comment by Rayisken** [comment]
Related: https://github.com/yogstation13/Yogstation-TG/issues/4643
