### ISSUE TITLE
Moths immune too flashes

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#43240]
You can't flash them. Reproduced with no testmerges.

**Comment by ShizCalev** [comment]
intentional, moths have no eyes.

**Comment by Barhandar** [comment]
Lol _what_. Since when moths traded "eyes extra vulnerable to flashing" for "no eyes at all so immune to flashes but still can see"?

**Comment by ShizCalev** [comment]
when #43175 was fixed.

https://github.com/tgstation/tgstation/blob/9a621a03d2522d6ccaece280674934bd501a7a04/code/modules/mob/living/carbon/human/species_types/mothmen.dm#L6

**Comment by Barhandar** [comment]
And since a year ago, they both have and don't have eyes.
https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/carbon/human/species_types/mothmen.dm#L17
#34794

**Comment by adamkad1** [comment]
so how do they see
