### ISSUE TITLE
Species trait NOEYES and mutanteyes on same species coexist peacefully

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#43255]
Moths have both after #34794, and after #43175 their NOEYES trait makes them flashproof. I haven't tested yet whether flashproofing makes them also immune to eye damage from welding and sight loss from too much damage/eyes getting extracted. 
https://github.com/tgstation/tgstation/blob/3824a42cb85b0aac412e597b69de143911732de2/code/modules/mob/living/carbon/human/species_types/mothmen.dm#L1-L17

P.S. My PR doesn't close this because the core issue isn't affected.

**Comment by py01** [comment]
they can weld without goggles, yes

**Comment by ShizCalev** [comment]
Fix for this is to remove the NOEYES flag and make a proper iconstate for the moth eyes.

**Comment by tralezab** [comment]
NOEYES flag is NOMORE, fixed in that most recent reference
