### ISSUE TITLE
Dark Mode Makes BYOND Donor Icons Look Bad!!

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#43280]
## Round ID:
104424

## Testmerges:
#42958: '[READY] Disarm Rework: Shove that Dickhead' by actioninja at commit f0af0d0e86 
#43142: 'Don't use megafauna in events' by subject217 at commit 0ade2949ec 
#43145: 'Makes strong booze more dangerous' by Mickyan at commit 0770b4b59c 
#42879: '[Test Me :) ] The Virtual Reality Hub' by Whoneedspacee at commit eb0c65f858 

## Reproduction:
1) Be BYOND donor
2) Result: ![Bad](https://imgur.com/TS9u2dJ.png)

(Look at all the light mode bleeding out of the icon)

**Comment by Kmc2000** [comment]
F

**Comment by actioninja** [comment]
Holy shit, this fucking sucks

**Comment by optimumtact** [comment]
>Be BYOND donor
Hohoho

**Comment by ShizCalev** [comment]
Moved to #43242
