### ISSUE TITLE
Wizard's mutate spell causes random sprites to attach to the wiz

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#43294]
Issue reported from  Round ID: 104462 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
Reporting client version: 512

#42780: 'Automatic deadminning' by ShizCalev at commit aee9417772
#43263: 'Test merge change to see the performance impact of client/mousemove binds' by MrStonedOne at commit 76e673023b

In the round, it was green airlock lights (twice), a plasma ore sheet, a toner cartridge, some kinda green square, a random person with purple hair and without right leg (with rotation states!) and more!

**Comment by PKPenguin321** [comment]
Sounds like a corrupted BYOND cache on your end

**Comment by Barhandar** [comment]
Exactly same attached sprites were seen by multiple other people, including Cedarbridge, one of the admins.

**Comment by 4dplanner** [comment]
Have seen this happen before, not BYOND cache imo

**Comment by ShizCalev** [comment]
If anyone sees this again PM me immediately on discord so I can take a look.
