### ISSUE TITLE
Attacking someone holding a potted plant as a wraith didn't do anything

### ISSUE THREAD

**Issue by benjikz** [tgstation/tgstation#43290]
I was playing as a wraith construct in a cultist round and it wouldn't let me kill a dude inside a plant. I was clicking right on him for quite a while, until he killed me (somehow) by throwing the plant at me only three times. Not sure if this is a bug or intended, but it seems a bit broken

Issue reported from  Round ID: 104448 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

**Comment by ShizCalev** [comment]
Unable to repo wraith issue, throwing plants to harm people is intended however.
