### ISSUE TITLE
Dead guy using PDA to message people (me)

### ISSUE THREAD

**Issue by Timonkeyn** [tgstation/tgstation#43295]
## Round ID:104466

If you discovered this issue from playing tgstation hosted servers: Sybil
[Round ID]: 104466

## Testmerges:
 #42780: 'Automatic deadminning' by ShizCalev at commit aee9417772
#43263: 'Test merge change to see the performance impact of client/mousemove binds' by MrStonedOne at commit 76e673023b

## Reproduction:
i Suicided after Messaging everyone.(im the lawyer) i stayed in in my Body after suicide and could still interact with the PDA and even write Messages, and someone answered. I also was buckled to a Chair, so i could still interact with it.

**Comment by ShizCalev** [comment]
likely related to #42894's rewrite for update_mobility.

**Comment by ShizCalev** [comment]
yeah, 100% caused by that.

**Comment by ShizCalev** [comment]
@4dplanner

https://github.com/tgstation/tgstation/blob/2d94e83af007e92a7385696eb4ee2eb65106aa1d/code/game/objects/structures/beds_chairs/chair.dm#L8
buckle_laying can be 0, which means
https://github.com/tgstation/tgstation/blob/65a67058694149c4b3dd604f5054275cd6f08c9e/code/modules/mob/living/living.dm#L1086-L1091
this check is bypassed, and we go into this one
https://github.com/tgstation/tgstation/blob/65a67058694149c4b3dd604f5054275cd6f08c9e/code/modules/mob/living/living.dm#L1098-L1104
that doesn't check any stat stuff.

**Comment by ShizCalev** [comment]
this essentially means that anyone can use anything that uses canUseTopic() regardless if they're alive, stunned, unconscious, or dead, as long as they're buckled to a chair.

**Comment by 4dplanner** [comment]
Oof

**Comment by 4dplanner** [comment]
Will fix after dinner

**Comment by ATH1909** [comment]
Time to text people from beyond the grave.

**Comment by Addust** [comment]
this actually happened in yogstation too
