### ISSUE TITLE
Black-On-Black Is Not Okay in Darkmode Input Line

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#43297]
## Round ID:
104481

## Testmerges:
#42958: '[READY] Disarm Rework: Shove that Dickhead' by actioninja at commit f0af0d0e86 
#43142: 'Don't use megafauna in events' by subject217 at commit 0ade2949ec 
#43145: 'Makes strong booze more dangerous' by Mickyan at commit 0770b4b59c 
#42879: '[Test Me :) ] The Virtual Reality Hub' by Whoneedspacee at commit eb0c65f858 

## Reproduction:
1) Exist
2) Toggle dark-mode into light mode as soon as you join the server
3) The input bar is now always black
4) Consider the following:
    dark mode: ![ouch](https://imgur.com/oJY7kJ3.png)
    light mode: ![oof](https://imgur.com/RJBnCQ6.png)

What have we done to deserve this?

**Comment by bobbahbrown** [comment]
actually you know what I think this was fixed in https://github.com/tgstation/tgstation/pull/43275 but the only server that matters hasn't been updated yet

**Comment by ShizCalev** [comment]
Already fixed
