### ISSUE TITLE
[Boxstation] Toxins test site screen is not linked up to its camera.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43309]
The toxins test site telescreen has a network of "toxin" while the camera on the bombsat is "toxins".

Super easy fix.

**Comment by Barhandar** [comment]
Which map?

**Comment by WJohn** [comment]
Oh, whoops, boxstation! Haha.

Change the network on the screen from "toxin" to "toxins"

**Comment by nemvar** [comment]
It works on meta
