### ISSUE TITLE
headless ling bug

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#43313]
https://i.gyazo.com/f290951b299e8b8686cce8e641655333.png

revived headless, had no eyes ears tongue and i could still see ghosts. maybe some of this is intentional but surely seeing ghosts isn't.

**Comment by ShizCalev** [comment]
Duplicate of #27408

**Comment by imsxz** [comment]
@ShizCalev that issues from 2017 i dont think anyones gonna see it ever
