### ISSUE TITLE
AIs can take control of piloted mechs, breaking the pilots mob in the process.

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#43329]
## Round ID: 104627

If an AI clicks a mech with an exosuit ai control beacon(/obj/item/mecha_parts/mecha_tracking/ai_control) they get a link that allows them to take control of the mech. Clicking this link after another AI (or I'm guessing a human, though I haven't tested this) pilots the mech forces the user clicking the link in control of the mech. If the previous pilot was an AI another AI core gets created, which teleports to the mechs position whenever that AI tries to move.

It seems all that is necessary to fix this is to check if the mech is piloted when the link is clicked in addition to when the mech is examined(which produces a link).

**Comment by ATH1909** [comment]
What happens if that AI core then gets carded? Does the card teleport? If so, does the card bring any containers that it's in with it?

**Comment by ATH1909** [comment]
Do you need 2 AIs to perform this bug?

**Comment by Cyprex** [comment]
Probably not, I haven't tried it when the mech is piloted by a human.

**Comment by ATH1909** [comment]
> Probably not, I haven't tried it when the mech is piloted by a human.

But isn't the first AI to enter the mech the one that gets teleported around? If you only have one AI, a human would have to be able to enter the mech while the AI is piloting it, and as far as I know, humans can't use the examine link.

**Comment by ATH1909** [comment]
I just tried this in a round on bagil, and the two AIs and I were unable to replicate this bug. Do you have video proof of it?

**Comment by Cyprex** [comment]
1. click an unpiloted mech as an AI. Take note of the link that lets you take control of the mech.
2. Have the other AI take control of the mech.
3. Click the old link in chat.

**Comment by ATH1909** [comment]
I had them do exactly that, then had them try it again.

**Comment by zxaber** [comment]
For what it's worth, Malf AIs have special interactions with this sort of thing. I think it's supposed to be limited to when the Malf AI shunts into a mech as opposed to beacon control, but that might be related.

**Comment by Cyprex** [comment]
What exactly is the issue ATH1909? I was able to reproduce this reliably in thunderdome in the quoted round. No AIs were malf

**Comment by Cyprex** [comment]
This has since been resolved, I can no longer reproduce this. The pilot gets ejected normally now.
