### ISSUE TITLE
Renaming an area with blueprints erases its special properties (like having power without an APC)

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#43327]
Issue reported from  Round ID: 104622 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% FREE LAG])
Reporting client version: 512

#43263: 'Test merge change to see the performance impact of client/mousemove binds' by MrStonedOne at commit 76e673023b
#43301: 'Test merge pr to bypass the connection pop cap for byond members. (Note, living player cap still applies)' by MrStonedOne at commit d4612b3b7e

Be golem after other golems, find out ORM is not working (despite having "powered" visuals). Check with the blueprints, the main room is renamed to "Whatever man" and ORM works in other rooms that are still "Free Golem Ship". Renaming it back didn't work, obviously. Mysteriously, lights still worked.

At a guess it doesn't rename an area inasmuch as _recreate it whole_, hence why it lost power and only affected one room.

**Comment by kriskog** [comment]
The way areas and powering them works, the Whatever man area was brand new with no connection to or properties from the free golem ship area and would have needed an apc for power. 

You would have been able to expand the free golem ship area back by modifying the free golem ship area from within the new area, which should have restored power there.
