### ISSUE TITLE
Emags only work on closets if you're not on help intent.

### ISSUE THREAD

**Issue by nichlas0010** [tgstation/tgstation#43336]
https://github.com/tgstation/tgstation/blob/ad1f0fb81d53318a6c8a96e14bbb08f4716447b0/code/game/objects/structures/crates_lockers/closets.dm#L269

GetID returns src for /obj/item/card, and the emag is a subtype of that, so the proc tries to unlock the locker with the non-existant access on the Emag, rather than actually emag it.

**Comment by nichlas0010** [comment]
Easy solution would probably be to override GetID() for emags, making them return null instead of src.

**Comment by Barhandar** [comment]
Duplicate of #41249

**Comment by nichlas0010** [comment]
Oh right
