### ISSUE TITLE
Credits can be floating points

### ISSUE THREAD

**Issue by Michael-Ashfield** [tgstation/tgstation#43339]
Round ID: 104660
You can with withdraw 0.000000000001 of a credit, this is clearly not intended and credits should be integers.

To reproduce:

1. Have atleast 1 credit in your ID
2. Alt click your ID and withdraw 0.0000000001 (any floating point works)
2. You now have a 0.0000000001 credit in your hand

**Comment by PKPenguin321** [comment]
Bruh moment

**Comment by Michael-Ashfield** [comment]
> Bruh moment

it was a bruh moment when I was playing music and got tipped 1e-12 credits.

**Comment by Barhandar** [comment]
Byond's everything-is-floating-points strikes again!

**Comment by 4dplanner** [comment]
> > Bruh moment
> 
> it was a bruh moment when I was playing music and got tipped 1e-12 credits.

Lmao keep it in

**Comment by pigeonsk** [comment]
You can own 0.00000001 of a bitcoin
