### ISSUE TITLE
Spray Painting Blast Door Allows Vision Through It

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#43353]
## Round ID:
104739

## Testmerges:
#42958: '[READY] Disarm Rework: Shove that Dickhead' by actioninja at commit f0af0d0e86 
#42879: '[Test Me :) ] The Virtual Reality Hub' by Whoneedspacee at commit eb0c65f858 
#43326: 'Fixes an Ancient LINDA Bug' by Fox-McCloud at commit 96caf37f3f 

## Reproduction:
1) see blast door
2) blacked
3) can now see other side

**Comment by bobbahbrown** [comment]
you can also fire lasers through it

**Comment by Fox-McCloud** [comment]
This also means that spraypainting them will allow them/cause them to radiant and conduct heat too.
