### ISSUE TITLE
I seem to not be able to use the shuttle navigation console correctly

### ISSUE THREAD

**Issue by Timonkeyn** [tgstation/tgstation#43360]
## Round ID:  104796
[Round ID]: 104796 (Independent to round
## Testmerges:
#42958: '[READY] Disarm Rework: Shove that Dickhead' by actioninja at commit f0af0d0e86
#43326: 'Fixes an Ancient LINDA Bug' by Fox-McCloud at commit 96caf37f3f
## Reproduction:
Click Shuttle Navigation console

But for real, Imsxz told me to report this. i cant use the shuttle Navigation console properly. the Buttons are not there. i tried updating beyond but that didnt help.

**Comment by SpaceManiac** [comment]
Could you be more specific about what you mean? Which shuttle are you trying to control? Maybe a screenshot?

**Comment by Timonkeyn** [comment]
Will post a Screenshot in a couple of hours

**Comment by Timonkeyn** [comment]
![Test](https://user-images.githubusercontent.com/42039728/55170145-5674d980-5176-11e9-931b-8ea2cdf385d3.JPG)

**Comment by Timonkeyn** [comment]
thats what i see when i use the shuttle navigation console in the syndie base, same for the pirate ship

**Comment by SpaceManiac** [comment]
Make sure your icon scale is set to Auto and not 2x or otherwise when the view gets bigger, like it does when using these consoles, the edges (where the buttons are) will get hidden

**Comment by Timonkeyn** [comment]
> Make sure your icon scale is set to Auto and not 2x or otherwise when the view gets bigger, like it does when using these consoles, the edges (where the buttons are) will get hidden

It somehow fixed it after i went into the view, put it on 2x and on auto again. (it was on auto by default)
