### ISSUE TITLE
issue with mindshield implanting and hiveminds

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#43361]
not a dupe of #43059 this one has more info

mindshield implant goes into awoken vessel, doesnt give any feedback nor give them the flashy mindshielded HUD thing, implant still goes in and fails future mindshield attempts since they already have one.

@Kierany9

**Comment by Kierany9** [comment]
Just to clarify, is this awoken vessels only or all vessels?

**Comment by Kierany9** [comment]
Also, any round IDs or runtime logs? Tested locally and could not reproduce, so I suspect this is some weird edge case I forgot to account for runtiming.
