### ISSUE TITLE
Map spawned freezers break when reconstructed.

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#43366]
I've tested this mostly on Metastation.

> Go to toxins or the supermatter mix room, (or Atmos, I guess.)
> 
> Unscrew and crowbar the freezer/heater then rebuild. 
> 
> Notice how the pipe doesn't connect anymore. 
> Changing it's setting also reveals 0 temp 0 kpa.

You can even build a third set of pipes next to the two freezers in the SM and it won't connect up. 

It also seems like built freezers and heaters only work on layer 2 vertical pipes? Try making a connector port > Pipe > Pump > Port set up horizontally and vertically with freezers on the pipe section. See which ones report actually having any pressure or temperature in them.

**Comment by kriskog** [comment]
Can't reproduce. Did you turn it (screwdriver -> wrench x1-3 -> screwdriver) after finishing the construction?

As for layers, they do indeed only connect to layer 2 piping.

**Comment by RaveRadbury** [comment]
WHAT
