### ISSUE TITLE
If you shove the rolling bed into the teleporter with a person buckled to it, the patient will be left behind

### ISSUE THREAD

**Issue by InsaneHyena** [tgstation/tgstation#43378]

**Comment by MegaEmpirical** [comment]
There is a similar issue with wheelchairs and portal gun portals.... Though I think it left me behind and destroyed my wheelchair.

**Comment by timothymtorres** [comment]
I'm pretty sure this was fixed with #58230 and have seen no recent bug reports about this for several years.  Marking this as cleanup flagged that will cause it to close in 7 days.
