### ISSUE TITLE
CNS rebooter not functional

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#43374]
CNS rebooter should cap stuns to 4 seconds, but it appears to do nothing at the moment.

**Comment by Nickkoranda** [comment]
Is this stamina damage or other hard stuns (taser/stunbaton/stunprod)? If it's stamina damage you're talking about then CNS wouldn't work for it anyway.

**Comment by py01** [comment]
hard stuns, tested with stunbaton.

**Comment by PKPenguin321** [comment]
i have a hunch that this came about due to the changes to resting

**Comment by AnturK** [comment]
From quick glance the code is nonsense, signal is fired before stun is modified so callback can't check against current stun values.
