### ISSUE TITLE
Hiveminds can give other hiveminds heart attacks

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#43387]
If you add a hivemind to your own, you can still cast heart attack on them before they leave, which allows you to immediately reclaim them with little risk. Given that hiveminds were made immune to circadian to prevent the same thing with that ability, a change may need to be made.
@Kierany9

**Comment by Kierany9** [comment]
Originally intended but this was before the 2.0 PR that added reclaim/circadian, I'll consider it.
