### ISSUE TITLE
Mech (Firefighter?) construction messages are off by one

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#43393]
Issue reported from  Round ID: 104963 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% FREE LAG])
Reporting client version: 512

#43263: 'Test merge change to see the performance impact of client/mousemove binds' by MrStonedOne at commit 76e673023b
#43301: 'Test merge pr to bypass the connection pop cap for byond members. (Note, living player cap still applies)' by MrStonedOne at commit d4612b3b7e

For example, installing the second layer of armor (apply-wrench-weld) on Firefighter shows messages for welding internal, applying external, and wrenching it. Adding and securing the scanning thing also shows `You install the hand drill into the Firefighter chassis.` instead of the real name. I blame the MK-1 Ripley PR.

**Comment by zxaber** [comment]
Rip. Yeah, probably my fault.

**Comment by zxaber** [comment]
Actually, I think you want #42495. Step 11 on the Ripley is adding in the capacitor, right after securing the scanning module. On the Firefighter, this is step 12, with step 11 skipped entirely. These steps were altered when the cap and scanning modules were added to the non-combat mech construction steps.
