### ISSUE TITLE
R&D "Biological Technology" does not work at all

### ISSUE THREAD

**Issue by jaw-sh** [tgstation/tgstation#43391]
Issue reported from  Round ID: 104961 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 512

Biological Technology promises the following:
* Machine boards for chem heaters, chem masters, chem dispensers, sleepers, sleepers, soda dispenser, portable booze dispenser
* Computer boards for pandemics, operating computers
* Protolathing for defib, defib mount, health analyzer, medical spray, and gene analyzers

What is given:
* VR Sleeper Board

Everything else is completely missing. I've tested this on multiple rounds. Considering that 100 pop servers often have serious health problems, this complicates matters. My top priority would be getting more sleepers in but that's not possible at the moment.

**Comment by AnturK** [comment]
Were you trying to print these on medical/engineering lathes ? These designs are not printable in R&D.

**Comment by Barhandar** [comment]
Department lathes have a limited selection of items and boards, if you want defib etc you need medical lathe or omnilathe, and if you want boards you'll need the same or to go to engineering ~~or check the research board section.~~

**Comment by jaw-sh** [comment]
Oh wow what the fuck, it does work on the one in medical. Okay, my bad. I wish that was made clear somehow.
