### ISSUE TITLE
Morph gets choppy movement after unmorphing

### ISSUE THREAD

**Issue by AutomaticFrenzy** [tgstation/tgstation#43400]
## Reproduction:

Be morph, morph and unmorph, walk around, it will be as if you have the fps setting to 1 or step_x bug on the map

**Comment by KomradeSpectre** [comment]
It's one of the most hilariously unsettling bugs. Likely related to the movement delay changes as that is when I first noticed it appearing.

**Comment by kriskog** [comment]
Related to animate_movement, it isn't resetting properly last I looked at it.
