### ISSUE TITLE
Toggle darkness makes things brighter than they should be

### ISSUE THREAD

**Issue by Names-Are-Hard** [tgstation/tgstation#43401]
## Testmerges:
#43263 
#43293 
#43301 
#43349 

## Reproduction:
As a ghost, press toggle darkness until it's at the setting right before no darkness.

![image](https://user-images.githubusercontent.com/35442306/55262133-1707c500-522a-11e9-801a-da31103595c1.png)
Byond version 512.1466

![image](https://user-images.githubusercontent.com/35442306/55262155-2be45880-522a-11e9-84ee-968b69938397.png)
512.1464

**Comment by Angustmeta** [comment]
Same problem with meson scanners. Night vision-ish stuff seem ro make everything bright, and not just darkness. 

Also, on highest 'toggle darkness' level the extra brightness subsides and becomes normal.

**Comment by AnturK** [comment]
The one suspicious change is http://www.byond.com/forum/post/2429244 since it touches color matrices,

**Comment by gamefreak2998** [comment]
I can confirm this issue occurs with anything that works like night vision goggles, including ling vision. Really hurts my eyes so I hope this gets fixed soon X.x

**Comment by nfreader** [comment]
I believe this has been fixed?
