### ISSUE TITLE
Mass drivers launch ghosts while kicking them out of orbiting

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#43404]
Issue reported from  Round ID: 104997 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% FREE LAG])
Reporting client version: 512

#43263: 'Test merge change to see the performance impact of client/mousemove binds' by MrStonedOne at commit 76e673023b
#43301: 'Test merge pr to bypass the connection pop cap for byond members. (Note, living player cap still applies)' by MrStonedOne at commit d4612b3b7e

**Comment by ShizCalev** [comment]
lmfao
