### ISSUE TITLE
Bomb Test Site Monitor doesn't function

### ISSUE THREAD

**Issue by Spacebutterman** [tgstation/tgstation#43410]
Issue reported from  Round ID: 105016 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Using the Bomb Test Site monitor doesn't pull up an associated window and will not do anything.

**Comment by SpaceManiac** [comment]
Map was Box Station

**Comment by Barhandar** [comment]
Duplicate of #43309
