### ISSUE TITLE
Plasmaman curator helmet has no light

### ISSUE THREAD

**Issue by MegaEmpirical** [tgstation/tgstation#43417]
Nada, no light. No button. Makes me sad.

**Comment by bobbahbrown** [comment]
https://github.com/tgstation/tgstation/blob/master/code/modules/clothing/spacesuits/plasmamen.dm#L156

I believe this was an intended feature, not a consistency issue. The curator's suit is a prototype version.

**Comment by bobbahbrown** [comment]
Note this feature was originally added with the rest of the suits, it's not an issue of someone adding on top and messing up.

#43088

**Comment by ShizCalev** [comment]
seems legit.
