### ISSUE TITLE
Emagged Organ Harvesters Still Require Their Victims to Have No Items

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#43423]
https://github.com/tgstation/tgstation/blob/ccadcf61d3d383191d950a8ac5a350b0213ba9e9/code/game/machinery/harvester.dm

There's an "var/allow_clothing" in the code for organ harvesters, but it's set to FALSE by default and can't be changed to TRUE without admin intervention.

Also, I think the victim's head comes off before the organs are extracted from the chest of the victim. Please change the ordering of that; I want to listen to my victims' screams as a machine rips their heart out of their chest before their very eyes, but they can't really scream without a head.

**Comment by Sealed101** [comment]
- resolved by #76594
took you long enough lol
