### ISSUE TITLE
Radstorm with Radsuit turns flesh into acid

### ISSUE THREAD

**Issue by Electronics** [tgstation/tgstation#43425]
With full radsuit you still can mutate eg: acid flesh, not doing any damage to yourself but spills acid all over your clothing which eventually burns off.

```
You feel waves of heat wash over you! Find shelter!
You mutate!
A horrible burning sensation envelops you as your flesh turns to acid!
Your bubbling flesh pops! It burns!
```

```
Round ID: 105155
BYOND Version: 512.1453
Server revision compiled on: 
Master commit: 7b3175e833bff8741a10acc74ff4d90cdf34ca5a
The following pull requests are currently test merged:
#42958: '[READY] Disarm Rework: Shove that Dickhead' by actioninja at commit f0af0d0e86
#43263: 'Test merge change to see the performance impact of client/mousemove binds' by MrStonedOne at commit 76e673023b
#43301: 'Test merge pr to bypass the connection pop cap for byond members. (Note, living player cap still applies)' by MrStonedOne at commit d4612b3b7e

Local commit: 17a6d673d071322e092c8e529c0c9f2773852f6e
Server tools version: /tg/station 13 Server v3.2.5.1
```

**Comment by bobbahbrown** [comment]
This is not a bug, radsuits do not protect against radiation storms. The only checks performed on radiation storms are as to if the turf allows it, and then if the mob has the race trait `TRAIT_RADIMMUNE`.

**Comment by Barhandar** [comment]
It's absolutely a bug in that the (limited-quantity and restrictive) radsuits and the scant few other sources of 100 rad armor do not protect against radstorms.

**Comment by bobbahbrown** [comment]
actually you are 100% correct i misread the code one moment pr incoming

**Comment by bobbahbrown** [comment]
unable to reproduce on commit 71285cf7c485f5bf78b810c0c31ababcc4f171e8, may be a test merge or some other oddity

**Comment by SpaceManiac** [comment]
Totally unable to reproduce
