### ISSUE TITLE
Immovable rods can be stopped if they hit a puzzle.

### ISSUE THREAD

**Issue by Ordonis** [tgstation/tgstation#43436]
## Round ID:

Found during testing for additional alcohols PR; was trying to damage self as wizard to test healing of wiz fizz.

## Reproduction:

Create a mob, 
Smite mob with immovable rod. Shortly thereafter, smite mob with puzzle, such that immovable rod does not reach the mob before the puzzle takes effect.
Watch immovable rod hit puzzle and stop, thus becoming no longer immovable.

**Comment by nfreader** [comment]
Unable to reproduce. Feel free to reopen if you see this again.
