### ISSUE TITLE
Can no longer insert lungs as part of surgery; instead you feed them the lungs.

### ISSUE THREAD

**Issue by Shikarego** [tgstation/tgstation#43459]
## Reproduction:

I found this as a fully-augged scientist performing self-surgery. I openned myself up with tools, on a table in R&D, and inserted a nutriment pump plus. Then I replaced my liver with an upgraded cyber liver. I was doing the same for lungs, but when I tried to insert them into my chest I took a bite of em instead. Same thing happened when I tried with my old lungs. The roboticist in the room tried to help me and instead force-fed me the lungs.
I got cryo'd and dexalin'd and was able to mime out surgery to a doctor while giving them the lungs. I have been in surgery for like 15 minutes though, so I'm looking pretty fucked.
I think they're keeping me alive with lollipops, but very clearly cannot figure out how to insert my lungs.

**Comment by Barhandar** [comment]
Switch to edible happens if you attack with the organ (i.e. click not on help intent or surgery doesn't catch it for whatever reason. Feels like the issue is with lungs not getting extracted properly as opposed to not inserted properly, but needs testing.

**Comment by ExcessiveUseOfCobblestone** [comment]
> self-surgery

hmmm!

**Comment by ExcessiveUseOfCobblestone** [comment]
self-surgery is not an intended feature ergo not a bug.

If this is happening during normal surgery make a new issue.
