### ISSUE TITLE
adopting a code of conduct for tgstation

### ISSUE THREAD

**Issue by 123chess456** [tgstation/tgstation#43462]
Hi
great project!! I have one observation and a suggestion. I noticed you have rejected some pull requests to add some good tajaran species and that the people submitting those pull requests are POCs (People of Colour). As a suggestion I recommend adopting the Contributor Code of Conduct (http://contributor-covenant.org) to ensure everybody's contributions are accepted regarless of their sex, sexual orientation, skin color, religion, height, place of origin, etc, etc, etc. As a white straight male and lead of this trending repository, your adoption of this Code of Conduct will send a loud and clear message that inclusion is a primary objective of the tgstation community and of the software development community in general. D.

**Comment by plapatin** [comment]
why are you like this

**Comment by 123chess456** [comment]
You seem to have taken personal issue with well the issue :) I opened this issue not to attack you or your decisions,but to help improve a part of the project in which it seemed lacking. Most projects on Github have adopted the Contributor Covenant or a variant of it. It is a very straight forward document that protects all parties,I don't understand your negative attitude towards that philosophy. You may not be "white" [ in your profile picture you sure seem white :) ] but you are not a woman or a trans-gendered person so you can't possibly understand what they go through (harassment,exclusion,threats) and why a code of conduct is necessary. Even citadel station 13 has adopted one to protect it's future,for me it's very obvious ss13 related projects would naturally follow suite and adopt the same if not similar Code of Conducts. I urge you to reconsider for the good and future of this project :) Thank you

**Comment by cedarbridge** [comment]
April 1 is already passed.

**Comment by HomocidlePancakes** [comment]
ughhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh this hurts meeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by 81Denton** [comment]
🤔
