### ISSUE TITLE
One handed people can not remove magazines unless they are empty.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#43464]
See tittle

**Comment by ShizCalev** [comment]
relevant:
https://youtu.be/CC4EHHO00eo

**Comment by ShizCalev** [comment]
note; some weapons you can perform a tactical reload by just clicking the weapon with a magazine. could add this to `/obj/item/gun/ballistic/automatic/pistol` by adding `tac_reloads = TRUE`

**Comment by HomocidlePancakes** [comment]
No. You need to hold the gun in one hand and remove the mag with other but onehanded people kinda struggle with that for obvious reasons.

**Comment by Eskjjlj** [comment]
Yeah that's one change I criticized on the original PR. One armed people have to waste ammo if they want to get a fresh magazine. And it doesnt make sense how they are unable to remove the mag when loaded.

**Comment by ShizCalev** [comment]
#43466 kinda will help with this at least.
