### ISSUE TITLE
Singularity Crashing Server

### ISSUE THREAD

**Issue by legoscape** [tgstation/tgstation#43474]
Issue reported from  Round ID: 105347 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

I got a singularity and Particle accelerator up for shits and giggles to make more power and it crashed on me. After Ambassador Magikarp removed and replaced one of the shield generators and I got it working again. I started up the Accelerator. It ran on high power of 2 and the second It spawned the server crashed and it restarted.

Reporting client version: 512

**Comment by ExcessiveUseOfCobblestone** [comment]
Need to make sure it was actually the singularity and not a coincidence.

**Comment by legoscape** [comment]
I believe something might be wrong with the spawning of Teslas and Singularities them selves. As a traitor I filled the SM shard with co2 and incidentally I believe it spawned a tesla then the server crashed.

**Comment by ExcessiveUseOfCobblestone** [comment]
If you have the code open up any DM file then go to **run**(it's on the top bar) > **compile and run**

**Comment by msgerbs** [comment]
@legoscape Can we close this seeing as it was never reproduced and the PA and singulo generator are now gone?
