### ISSUE TITLE
Gas Mixer seemingly receiving gases from a remote source

### ISSUE THREAD

**Issue by TerraGS** [tgstation/tgstation#43470]
Issue reported from  Round ID: 105314 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Had A Gas Mixer on layer 3 connected to pipes filled with n2o and plasma. In addition to those were gases that shouldn't normally be there.
![gasy](https://user-images.githubusercontent.com/40574831/55439024-e3e66e00-5568-11e9-983a-9c38c752f030.PNG)

**Comment by Barhandar** [comment]
That looks like a connection to engine waste.

**Comment by ShizCalev** [comment]
metastation

**Comment by MegaEmpirical** [comment]
Waa the mixer built on top of anything? Like a pump on other layer?

**Comment by TerraGS** [comment]
There were no pipes under it. The n2o and plasma were coming directly from their respective atmos chambers.

**Comment by Angustmeta** [comment]
Had this happen too. Gases tend to teleport into your pipes from other layers.

**Comment by kriskog** [comment]
Gonna go with dirty connection somewhere, this isnt possible to reproduce without more info, and I havent experienced it in a couple hundred hours of atmos play.
