### ISSUE TITLE
Headrevs hiding in lockers (and maybe heads too) doesn't end the round.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#43479]
Had a horrible 2 hour rev round where every rev was deconverted by 40 minute mark and the last headrev was hiding. Turns out he was hiding in a locker that whole fucking time. Admin ended up launching a rod at him for that.

**Comment by Tlaltecuhtli** [comment]
best solution would be having headrevs in lockers have a chance to trigger rods

**Comment by ATH1909** [comment]
Maybe add a lone op-like antag that has a spawn chance based on how often the heads of staff and/or revheads move (or don't move, rather) instead of how often the nuke disk moves?

What if we made the emergency shuttle able to leave the station on rev rounds? That way, the heads of staff could just flee to Centcom if the revheads don't want to play ball.

**Comment by HomocidlePancakes** [comment]
Why do we need a loneop to be sent in if the least head/headrev is being a bitch? Iam pretty sure that heads/headrevs were supposed to be considered exiled aslong as they are in a locker.

**Comment by ATH1909** [comment]
They could easily just wall themselves into a secluded spot in maint instead, though.

Why not allow the emergency shuttle to leave the station during a rev round? If a head of staff makes it back to Centcom on the shuttle (or maybe on an escape pod, but that sounds kinda lame (but it'd also more intuitive than escape pods NOT working)), the round ends in a (minor?) crew victory. If no heads of staff make it back to Centcom, it's a (minor?) rev victory. Does this sound like a good idea? Would anyone be willing to code/PR it?

**Comment by OverlyGeneric** [comment]
Just steal Goon's revolution idea and have it end in a stalemate by gibbing everyone if the round goes on for too long.

**Comment by davethwave** [comment]
How about the idea of demotion due to cowardice or something similar?

**Comment by ExcessiveUseOfCobblestone** [comment]
There's so many ways to cheese this that I don't think it's viable to stop it codewise.

At best we could timelimit rev but that would probably just encourage people to hide (I can either lose or I can stay in maint and nab a draw). Pretty much this behavior needs to be ahelped if it occurs.

**Comment by Tlaltecuhtli** [comment]
maybe have the location of head revs/heads get automatically revhealed when one of the faction almost won (30 min + and 1 head rev with almost 0 revs or 80% crew is rev and 1 head left

**Comment by HomocidlePancakes** [comment]
So heres what I made up. Inbetween 30-40 minute centcomm announces that there is a revolution on the station. Each living head/headrev will recieve a pinpointer that they can set to track a specific head/headrev (this will also show their name)

**Comment by SpaceManiac** [comment]
I can't find evidence in the code that hiding in a locker is intended to end the round, if you provide more information this can be reopened else take it to the forums.

**Comment by HomocidlePancakes** [comment]
![image](https://user-images.githubusercontent.com/35217076/55680762-a39b3d00-5926-11e9-95c5-487472c7511e.png)

https://tgstation13.org/wiki/Revolution

I also have been noted on yogstation for metagaming because I was lockering revs. Pretty sure this was a thing at some point.

**Comment by HomocidlePancakes** [comment]
@SpaceManiac

**Comment by SpaceManiac** [comment]
The code hasn't checked for this since 2011: https://github.com/tgstation/tgstation/commit/17ed3899c4a#diff-99712f40286a18477ef285c6e009aa14

**Comment by HomocidlePancakes** [comment]
![2A3B9EBE-9214-4D91-BDAA-BC668242860D](https://user-images.githubusercontent.com/35217076/55698985-000f6280-59e2-11e9-92ae-233ee2481ec9.png)

Page was created in 2013.

**Comment by ExcessiveUseOfCobblestone** [comment]
I can write "(your username) is dumb" on the wiki, you should take everything you read there with a grain of salt.

Also the wiki is not a code source.

**Comment by HomocidlePancakes** [comment]
I guess you right. But we still need to do something about revs becoming hide ‘n’ seek. Maybe will take it to forums.

**Comment by davethwave** [comment]
If I remember right, the heads being considered dead if they're in a locker thing was removed incidentally since it was reported that the round would end if the last head was in a cryopod. consequently this was 'fixed' but it seems to also effect the dead if in locker thing as well.
