### ISSUE TITLE
Job specifix healing chems (Nothing for mime, banana juice for clown etc.) seem to be tied to a body instead of mind.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#43482]
Got a brain transplant as mime. Got hurt pretty badly so I took a sip from my trusty bottle of Nothing. Didn't heal. Tested again, but while scanning with a health anylyzer. It was in my blood stream but didn't heal me. Seems rather weird that you keep your mime spells but can't heal with nothing.

P.S. I haven't actually tested this with the other jobs but I assume it's like that.

**Comment by ATH1909** [comment]
InB4 powergamers kidnap and get their brains surgically swapped with mimes, sec officers, etc. in order to benefit from their job-exclusive healing chems.

If a normal mime dies and gets cloned, will their new body be able to healing with the nothing chem?

**Comment by OverlyGeneric** [comment]
Intended. It's meant to heal brute and burn but anything else is useless.

 Drink Nothing when you're in a bar fight or getting beaten to death for breaking your vow.

**Comment by HomocidlePancakes** [comment]
You can still heal with it after being cloned.

**Comment by ATH1909** [comment]
> Intended. It's meant to heal brute and burn but anything else is useless.
> 
> Drink Nothing when you're in a bar fight or getting beaten to death for breaking your vow.

???

I think you misread/misinterpreted what this issue is about.

**Comment by OverlyGeneric** [comment]
> You can still heal with it after being cloned.

It's still intended but apparently, the reagent heals all forms of damage but only the body parts.


`if((ishuman(M) && M.job == "Clown") \|\| ismonkey(M))
141 | M.heal_bodypart_damage(1,1, 0)
142 | . = 1
143 | ..()
144`

**Comment by ExcessiveUseOfCobblestone** [comment]
This is "intended" in the sense that the check is for the mob and not the mind.

However you could replace it with https://github.com/tgstation/tgstation/blob/1dbcaf78a153fce0a414b8430e3dab9d371efc9e/code/datums/mind.dm#L40

which would be a stricter check.

**Comment by JMoldy** [comment]
Couldnt you get a brain transplant in a deceased mime/sec off/clown's body and get revived via strange reagent/brain defib and get the benefits then?

**Comment by ExcessiveUseOfCobblestone** [comment]
currently: no

with my change: no(?)

**Comment by ExcessiveUseOfCobblestone** [comment]
I'ma close this under the idea that keeping it on the body ensures antagonists going the extra mile can protect against role-testing, either by taking the body and actually healing OR feigning that you had your brain transferred.

If there's any role where the role-restricted function is so powerful that this is an issue, it should be nerfed.
