### ISSUE TITLE
Slot machines can create zero credit holochips

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#43488]
Refunding the balance from a slot machine when it's already at zero will dispense a zero credit value holochip.
### Round ID: 105465

![Nomoney](https://user-images.githubusercontent.com/17460297/55578257-515de000-56ca-11e9-91ca-76dd2e9a54f0.PNG)

### Reproduction:
-Go to any slot machine that accepts holocredits
-Make sure the current credits in it is zero
-Press refund
-Enjoy your monopoly money

**Comment by SouDescolado** [comment]
I bet that stupid guy that makes webpr's introduced this bug on pr #42774
