### ISSUE TITLE
[tech debt] ghosts orbiting a mob are teled around after the mob is hit by teleport bolt

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#43480]
105369
it also makes smoke poddles where the ghosts are teled, ruining my immersions

**Comment by ATH1909** [comment]
Did you just discover ghost/magic-powered cluster smoke grenades?

**Comment by Tlaltecuhtli** [comment]
https://github.com/tgstation/tgstation/blob/ff34dc6cf9615553eeaaf3a1fca47a4c71688b8b/code/modules/projectiles/projectile/magic.dm#L68
