### ISSUE TITLE
Lavaproofing potion didn't work

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#43483]
I did this while sandboxing on a private server.

Put xenobio goo on Cap's Hardsuit. Fireproof potion said that the hardsuit was already fireproof. Charged Red Extract is supposed to lavaproof. Noticed that hardsuit helmets don't get the color change that the body does when goo is applied.

Walked into lava and burned up.

It seems to me that it's either because the helmet wasn't lavaproof (as one cannot hold the helmet in hand to apply it), or the potion in general doesn't work.

## Reproduction:

1. Put charged red extract goo on Cap's Hardsuit. 

2. Walk into lava and catch on fire.

**Comment by HomocidlePancakes** [comment]
You can apply it to helmet while it’s equiped.

**Comment by RaveRadbury** [comment]
I can apply the potion while it's equipped? I thought I had to have the potion and hardsuit in-hand.

**Comment by ExcessiveUseOfCobblestone** [comment]
yes unless there's something wrong here

https://github.com/tgstation/tgstation/blob/6d0c807c9367e2257655601be4a49c316ad6be65/code/modules/research/xenobiology/crossbreeding/_potions.dm#L156-L157

**Comment by ExcessiveUseOfCobblestone** [comment]
@RaveRadbury

**Comment by RaveRadbury** [comment]
The potion applies to the helmet slot. I didn't realize that they can be applied to worn equipment. Not a bug, it works like it should.

**Comment by ExcessiveUseOfCobblestone** [comment]
thanks
