### ISSUE TITLE
emitter shots get stuck mid-air

### ISSUE THREAD

**Issue by ernestget8thumb** [tgstation/tgstation#43499]
Issue reported from  Round ID: 105537 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% FREE LAG])

https://gyazo.com/2edd342797ee54779980b8f26a9956e6 this

Reporting client version: 512

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=HS3LH7n5xr8

**Comment by FloranOtten** [comment]
@SpaceManiac Pretty sure this got fixed. Had some !!fun!! times dealing with emitter-less SMs but I have not seen this since.

**Comment by SpaceManiac** [comment]
I'll take your word for it
