### ISSUE TITLE
Wrenched-down machine frames don't translate into correct state for emitters built out of them (you have to unwrench and rewrench them before you can weld them down)

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#43498]
Issue reported from  Round ID: 105519 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% FREE LAG])
Reporting client version: 512

#43263: 'Test merge change to see the performance impact of client/mousemove binds' by MrStonedOne at commit 76e673023b
```
 That's an emitter.
A heavy-duty industrial laser, often used in containment fields and power generation.
Alt-click to rotate it clockwise.
The status display reads: Emitting one beam each 4 seconds.
Power consumption at 150W.
>>>It is fastened to the floor!
You adjust the welding mask down.
You switch the experimental welding tool on.
>>>The emitter needs to be wrenched to the floor!
```

It's likely the same for manually built emitters, but these used upgraded RCD to build frames pre-wrenched and wired.

**Comment by SpaceManiac** [comment]
The emitter is keeping track of its anchored state in a different variable than standard `anchored`, which it should not be doing.

**Comment by gwhit94** [comment]
Replicated Issue with manually built emitter. On creation the emitter is anchored to the floor as any other machine frame would be when completed. Requires unwrenching and rewrenching before welding can be attempted. 

code/modules/power/singularity/emitter.dm
ln. 30
I'd imagine that simply changing this
`var/state = EMITTER_UNWRENCHED`
to
`var/state = EMITTER_WRENCHED`
Would cause the emitter to default to the wrenched and anchored state on creation. 
I'll probably test this once I figure out the basics of testing changes locally.
