### ISSUE TITLE
Darkmode ASAY still has black text.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43507]
## Round ID:
105557

## Reproduction:
Speak in ASAY in dark mode, see how it's still in black.

Obviously, not okay.

**Comment by Mooshimi** [comment]
guuuuh, cleanup issue moment

**Comment by Sealed101** [comment]
- resolved by #43422
![изображение](https://github.com/tgstation/tgstation/assets/75863639/f92b22b3-1b4d-4f13-8d5c-71cc663a0a51)
