### ISSUE TITLE
Sanity and hygiene accumulate rounding errors over time.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43504]
## Round ID:
105547

## Reproduction:
Check add_mood in view variables
Search for sanity
Watch it deviate over time.

![](https://i.imgur.com/WKt4oEL.png)

**Comment by SpaceManiac** [comment]
does this actually cause anything or does it just look unpretty in VV?

**Comment by WJohn** [comment]
Nutrition is directly influenced by your current sanity level so it likely causes rounding errors there too, though that's harder to measure because sanity is constantly fluctuating fluctuating up/down and ever so slightly changes how much nutrition you lose per tick.

**Comment by WJohn** [comment]
Also this happens for hygiene.

**Comment by Qustinnus** [comment]
resolved a while back
