### ISSUE TITLE
Canister sprites stay at yellow fullness display thing when emptied via connector until manually unwrenched

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#43500]
Issue reported from  Round ID: 105539 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Reproduction:
Step 1: Get full canister
Step 2: wrench onto connector
Step 3: use pump to drain canister via connector
Step 4: Watch as the indicator displays green, then yellow and then stays there
Step 5: unwrench and watch it magically empty

**Comment by willox** [comment]
This seems to have been caused by https://github.com/tgstation/tgstation/pull/43392. Perhaps an update_icon call can instead be placed in `/obj/machinery/portable_atmospherics/canister/process_atmos`?
