### ISSUE TITLE
_machinery.dm armor code is not working.

### ISSUE THREAD

**Issue by yoyobatty** [tgstation/tgstation#43510]
```dm
/obj/machinery/Initialize()
    if(!armor)
        armor = list("melee" = 25, "bullet" = 10, "laser" = 10, "energy" = 0, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 50, "acid" = 70)
```
This will not properly add armor in _machinery.dm. This is just a report of a code oversight.

**Comment by Tlaltecuhtli** [comment]
why is this a thing

**Comment by Tlaltecuhtli** [comment]
if i remember right you need armor.len to make it work right

**Comment by SpaceManiac** [comment]
It's not clear what you're talking about

**Comment by ExcessiveUseOfCobblestone** [comment]
Are you trying to say that after spawning in (machine) and VVing it, you noticed the armor value was still null?

**Comment by yoyobatty** [comment]
Sorry for not replying, this can stay closed as it wasn't an issue.
