### ISSUE TITLE
Augmenting torso/head on ethereals makes those bodyparts disappear.

### ISSUE THREAD

**Issue by Zenog400** [tgstation/tgstation#43515]
Basically the same issue as #24130, but only effects ethereals, and only their head/torso.

Issue reported from  Round ID: 105604 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512

**Comment by ATH1909** [comment]
I think someone already reported this- I had a great time as a near-invisible nugget ethereal with the flame breath and xray powers from genetics.

I think it only works with red ethereals? You might need to test it.

**Comment by dragomagol** [comment]
Looks like skeletons #54694 and plasmamen #53084 have this issue as well.
