### ISSUE TITLE
New gun sprites still use the old back icon when being worn

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#43517]
Title, new gun sprites brought in by #41804 and #43347 didn't include a change to the sprites when having a shotgun holstered on your back.
![Forgoteverything](https://user-images.githubusercontent.com/17460297/55673819-f5c65a80-5861-11e9-881d-fa3a82f205e5.PNG)
Combat shotgun on the left, riot shotgun in the middle, regular shotgun shown on the right for contrast.

-New combat shotgun doesn't match up with the old combat shotgun icon that has shells attached to it.
-Riot shotgun has wood parts that aren't part of the riot shotgun's old back sprite.

_(Presumably too late noticing this when those PRs were open, told to make this issue report instead.)_

**Comment by ExcessiveUseOfCobblestone** [comment]
@pireamaineach

**Comment by pireamaineach** [comment]
I mean.
This doesn't match the old sprites either but I'll get to it at some point, I guess.

**Comment by pireamaineach** [comment]
After I wrap up a P.R. I'm working on I'll resprite them.

**Comment by optimumtact** [comment]
@actioninja

**Comment by TheTeenyTiny** [comment]
Did this end up getting resolved?
