### ISSUE TITLE
Monkeys can sometimes avoid being facehugged.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43511]
## Round ID:
105579

## Reproduction:
1. Spawn a monkey and a facehugger.
2. Watch the monkey walk over the facehugger.
3. It sometimes immediately pulls the facehugger off its face at the same time as it goes unconscious.
4. Monkey avoids facehugging.

This doesn't happen every time, but it CAN do it.

![](https://i.imgur.com/HvQVau5.png)

**Comment by ATH1909** [comment]
Was this from that round with all of those xenos last night? And with that miner that received xeno organs and became a human xeno queen (because all of the numerous other queens got brutally killed), then got murdered by a hunter for "being a false queen"?

**Comment by WJohn** [comment]
Yes, though I replicated this in the thunderdome successfully on seeing that first monkey magically not be facehugged.
