### ISSUE TITLE
Persistent "Dark Rainbow" Shader Bug

### ISSUE THREAD

**Issue by shaderproblemguy** [tgstation/tgstation#43524]
Regardless of the SpaceStation13 server I join, what I assume is the shader leaves dark rainbow tiles that never move and cover anything underneath them.

Prior to the most recent update, this was not a problem. Shadows would come and go depending on the proximity of the player or light sources.

Instead, when the server is connected to and the game is loaded, the shader chooses the lighting for each tile and that lighting sticks throughout the entire game. No matter the light sources or player proximity, most tiles are covered in a dark rainbow shadow.

This makes the game unplayable, or at least far less enjoyable to play. I can't operate when I can't see the tiles around me, it's essentially playing blind.

I've updated to the latest version, the bug persists.
I've deleted my cache, the bug persists.
I've toggled the "Graphics Hardware for Displaying Maps" option in Preferences, the bug persists.
I've updated my DirectX, the bug persists.
I've installed a new 64 bit OS, the bug persists.

As an example, I'll join Beestation:

Round ID: 3199
BYOND Version: 512.1466
Server revision compiled on: 2019-04-05
Master commit: a7e2ca19c1093c4951b519128f863aec98d05297
Local commit: 90e0ef9baac0f960713ef533665e7b6bf22a801b

The instant I begin the game, the bug occurs:
![beestation](https://user-images.githubusercontent.com/49358355/55679539-6bbad800-58db-11e9-82a1-690ccb6048a6.png)

To show that these dark rainbow tiles cover anything under them despite lighting:
![beestation 2](https://user-images.githubusercontent.com/49358355/55679544-80976b80-58db-11e9-8bb6-a2c9cfe29b3d.png)

My CPU is an Intel E2220, from the Intel G33/G31 Express Chipset Family.
dxdiag says that I'm running DirectX11
I have no graphics card as far as I know.

**Comment by SpaceManiac** [comment]
The "dark rainbow shadow" is an internal lighting system graphic that becomes visible when hardware rendering isn't working. This is a BYOND problem and there is basically nothing we can do about it.

> Prior to the most recent update, this was not a problem. Shadows would come and go depending on the proximity of the player or light sources.

BYOND 512.1465 introduced a bug which is affecting the lighting system (see #43401); that may have made things worse. Downgrade to 1464 for now and post on the BYOND forums if issues persist after the recent bug is addressed.

**Comment by Mooshimi** [comment]
Please reopen if this is still an issue, I have never seen it in 2020+2021
