### ISSUE TITLE
Plasma men are still plasma men in VR

### ISSUE THREAD

**Issue by Michael-Ashfield** [tgstation/tgstation#43521]
If you are a plasma man, when you enter VR you remain as a plasma man but without  a plasma suit and plasma to breathe, you burn to death.

This makes VR a hellish death simulator where unknowing plasma men experience what it is like to burn and choke to death in toxic oxygen.

**Comment by MegaEmpirical** [comment]
Sounds like a medbay simulator.

**Comment by habader** [comment]
Fucking amazing
