### ISSUE TITLE
Moths are STILL flashproof

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#43530]
https://github.com/tgstation/tgstation/issues/43255

This issue was reported over _2 weeks_ ago, and has ruined numerous rev rounds since its creation. I'm saying this as a moth who called out two different revheads who tried and failed to flash me (resulting in their swift lynching) in a single rev round, by the way.

C'mon, guys.

**Comment by ATH1909** [comment]
https://github.com/tgstation/tgstation/pull/43261
Epic.

**Comment by ShizCalev** [comment]
first part of my move started yesterday, all my things (including my primary comp) will be in storage till i'm in a more permanent location later this month.

Code wise the fix was completed in that PR, so if someone wants to resurrect it with sprites, go ahead.

**Comment by ShizCalev** [comment]
Duplicate of #43255
