### ISSUE TITLE
CQC Disarms Twice

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#43531]
CQC disarms twice, under some conditions: https://github.com/tgstation/tgstation/blob/d728800fbb179a308ae602be4fc0412185b0d242/code/datums/martial/cqc.dm#L187

IF this check fails, then CQC's `disarm_act` returns `FALSE` which just tells the mob "hey, do your regular disarm instead!"

**Comment by ATH1909** [comment]
Wouldn't that result in a disarm and a shove with the new system (instead of two disarms?)? Might be intentional.

**Comment by Fox-McCloud** [comment]
CQC longggg predates the disarm rework. I doubt it's intentional.

**Comment by actioninja** [comment]
This is intentional.
