### ISSUE TITLE
inconsistency with paraplegic + robo limb

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#43534]
![image](https://user-images.githubusercontent.com/222630/55689851-ca656d80-593e-11e9-9e70-785ff1a6f379.png)

**Comment by Time-Green** [comment]
what's the inconsistency?

**Comment by Tlaltecuhtli** [comment]
the robo leg is limp and liveless

**Comment by MegaEmpirical** [comment]
As it should be. The paraplegic quirk is supposed to be neurological in origin so it gives no shits about your leg.

**Comment by SpaceManiac** [comment]
feature
