### ISSUE TITLE
Adminheal does not clear you of mutations.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43547]
## Round ID:
105738

## Reproduction:
1. Inject various admin syringe mutations in yourself.
2. Adminheal yourself.
3. Mutations remain.

We regenerate limbs and organs, why not DNA too?

**Comment by SuperNovaa41** [comment]
Still an issue

**Comment by GPeckman** [comment]
Just tested on a local on master, and this is still an issue. There is a flag for `revive` to heal negative mutations: 

https://github.com/tgstation/tgstation/blob/24a9519482856042cf0702c694479f8b74e8e991/code/__DEFINES/mobs.dm#L918-L919

But obviously it doesn't work. And this line is the reason _why_ it doesn't work:

https://github.com/tgstation/tgstation/blob/24a9519482856042cf0702c694479f8b74e8e991/code/modules/mob/living/carbon/human/human.dm#L688-L692

It's calling `dna.remove_mutation` with `existing_mutation.name` as the argument, when it should be `existing_mutation.type` or just `existing_mutation`.
