### ISSUE TITLE
Adminhealing a golem causes them to drop two adamantine resonators.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43548]
## Round ID:
105741

## Reproduction:
1. Spawn in golem
2. Adminheal them
3. See two adamantine resonators on the floor. (Ears for golems)

Happens with seemingly any golem.

**Comment by HomocidlePancakes** [comment]
Wat. This was fixed at some point.

**Comment by Daxxed** [comment]
Yep had this happen to me with sand golems aswell, which shouldn't even have the resonators.
I think all golem types have to be fixed individually ?

**Comment by tralezab** [comment]
dupe of #41949
