### ISSUE TITLE
Hulk adminspawn dna injector does not work.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43546]
## Round ID:
105738

## Reproduction:
1. Spawn dnainjector/hulkmut
2. Inject self with it.
3. No hulk mutation occurs.

Should test to see if more of these do not work.

**Comment by Time-Green** [comment]
Can't reproduce. Are you sure you were a human?

**Comment by dragomagol** [comment]
I also wasn't able to reproduce this.
