### ISSUE TITLE
CTF allows spawncamping.

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#43552]
Issue reported from /tg/Station Terry [EU] [100% LAG FREE] [New-Dedi]

Reporting client version: 512

Stand here
![image](https://user-images.githubusercontent.com/38219334/55735482-b21a4f00-5a21-11e9-9513-9a18820692e7.png)

You can now shoot through spawn protection and kill people that just spawned.

**Comment by HomocidlePancakes** [comment]
No you can’t. You can get 2 shots in max

**Comment by PKPenguin321** [comment]
Not a bug

**Comment by Teepeepee** [comment]
don't reveal the ctf meta bro, noobs will catch up

**Comment by PKPenguin321** [comment]
@ExcessiveUseOfCobblestone just close the issue
