### ISSUE TITLE
broken drink icons

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#43555]
![image](https://user-images.githubusercontent.com/222630/55776942-29b4a200-5a53-11e9-80cd-77c5d720ebba.png)

Round ID: 105684

it was called "glass of beer"

**Comment by ATH1909** [comment]
Yup, this has been reported before.

Still hasn't been fixed, though.

**Comment by ExcessiveUseOfCobblestone** [comment]
what's in it actually though?

**Comment by Mickyan** [comment]
duplicate of #43070

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/a3fb736e89b5edd781ecb357259366c4291545be/code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm#L23-L28

consider adding `icon_state = "glass_empty"` on 26 lol
