### ISSUE TITLE
Russian Revolver

### ISSUE THREAD

**Issue by gamefreak2998** [tgstation/tgstation#43563]
Issue reported from  Round ID: 105825 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512

The russian roulette revolver doesn't seemm to be working correctly, atleast the one that spawns in the bar. Anytime we try to use it it'll click the first time and so long as theyre is atleast one empty chamber it never seems to fire, upon attempting to use again it will ask us to spin it again thus continuing our issue indefinitely (Either we got ungodly good luck or this is bugged since we tested this in the bar for about an hour) The only time i've ever managed to get it to fire with this issue is when the gun is fully loaded. If I recall this has been an issue ever since the revolver was patched to only be used on yourself rather than other people or atleast soon after if that helps tracking down the cause at all.

**Comment by ATH1909** [comment]
How DO you spin the Russian revolver, anyway?

And yeah, I can confirm that I had to fully load the Russian revolver before I could lose my Russian revolver duel with the clown.

**Comment by HomocidlePancakes** [comment]
You have to click it after each shot

**Comment by actioninja** [comment]
#42837 broke this and I have been too lazy to figure out why.

**Comment by ExcessiveUseOfCobblestone** [comment]
droplist is used by ballistics as `TRUE` but revolver needs it to be `FALSE`
