### ISSUE TITLE
All suit jackets except red have missing worn icons.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43568]
## Reproduction:
The following suit_jacket uniforms do not have worn icons:

/obj/item/clothing/under/suit_jacket/really_black
/obj/item/clothing/under/suit_jacket/female
/obj/item/clothing/under/suit_jacket/green
/obj/item/clothing/under/suit_jacket/charcoal
/obj/item/clothing/under/suit_jacket/navy
/obj/item/clothing/under/suit_jacket/burgundy
/obj/item/clothing/under/suit_jacket/checkered
/obj/item/clothing/under/suit_jacket/tan
/obj/item/clothing/under/suit_jacket/white

Only this one actually works.
/obj/item/clothing/under/suit_jacket/red

**Comment by WJohn** [comment]
Magically only occurred on my local server for no discernible reason. Fresh from master and recompile magically fixed it.

**Comment by Rowelll** [comment]
I don't understand this type of shit too. On the local server, some outfits don't appear on my characters, I'll probably write something about it too.
