### ISSUE TITLE
pAI cards do not provide updates about available personalities when they are in player inventory

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#43562]
Taken from: tgstation/code/game/objects/items/devices/paicard.dm
> /obj/item/paicard/proc/alertUpdate()
	visible_message("<span class ='info'>[src] flashes a message across its screen, \"Additional personalities available for download.\"", "<span class='notice'>[src] bleeps electronically.</span>")

Is it supposed to give you an update in the chatbar? I've yet to see this happen, even when I'm holding the pAI card in-hand. I even set up a test server, the message didn't proc.

**Comment by ATH1909** [comment]
I've seen it as a ghost, but I don't remember if I've seen it before as a living humanoid.

**Comment by ShizCalev** [comment]
It does output to chat, and I have seen it working lately.

**Comment by RaveRadbury** [comment]
I ran a server with two clients on a local network in the same room and the pAI messsage did not proc on either clients' chat.

**Comment by Mickyan** [comment]
Some time ago it would only work if it was on the ground and not being held by someone, have you tried if it makes any difference?

**Comment by RaveRadbury** [comment]
Wow, @Mickyan it does proc on those conditions thank you for sharing that.

It seems pretty straightforward to me that a player would expect the pAI to give them that update from within a PDA, given that they can be stored there.

As it stands as a player if I want to be updated about a personality becoming available I need to have it in a static location that I am in at all times. Shouldn't pAI notification be more accessible than this?

**Comment by RaveRadbury** [comment]
Also tested for pAI's in backpacks and PDA slots. It only procs when it's not in anyway a part of a player's inventory.

**Comment by ATH1909** [comment]
Thanks for the great detective work, Mickyan and RaveRadbury. Let's hope that a coder sees this and cares enough to fix it.

**Comment by RaveRadbury** [comment]
I just took care of it. Changed "visual" to "audible"

#43587

**Comment by RaveRadbury** [comment]
@ShizCalev I have reached the source of the issue and released a PR to correct it.
