### ISSUE TITLE
Admin heal does not restore sanity.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43589]
## Round ID:
105987

## Reproduction:
1. Set sanity to very low or very high (found in add_mood in VV)
2. Admin heal
3. Sanity is not touched.

It should probably restore it to 100.
A little bit strange because it DOES clear moods, but it doesn't restore sanity.

**Comment by Ordonis** [comment]
You've just been fucked by psyops:
Because physical wounds heal.
