### ISSUE TITLE
Bolt of sapping runtime.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43588]
## Round ID:
105987

## Reproduction:
1. Spawn staff of sapping (/obj/item/gun/magic/staff/sapping)
2. Sap yourself (get some titanium wall to reflect it at yourself).
3. Wait for it to wear off.
4. Try checking your mood.

Runtimes in question:
https://pastebin.com/TkF7BmDq

**Comment by tralezab** [comment]
I got nothing, at no point do I mess with the description

**Comment by optimumtact** [comment]
could not reproduce, sapping move event cleared successfully.

Suspect some other underyling timers issue caused the mood event to not clear
