### ISSUE TITLE
OP shuttle turrets can end up shooting passengers/equipment in the shuttle

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#43594]
1)Get jetpack
2)Circle around OP shuttle while dodging bullets
3)Spam *giggle when you end destroying the shuttle console

**Comment by Barhandar** [comment]
Also known as "the turrets really should not be shooting through ANY walls".

**Comment by optimumtact** [comment]
not so much a bug as a design issue/oversight.
