### ISSUE TITLE
Various Science map issues.

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#43595]
-Metastation: Has a white locker in Toxins that contains 2 full science outfits, rather than having 2 sci lockers with one set in each.

-Boxstation: No spare sci equipment sets or lockers

-Pubbystation: No spare sci equipment sets or lockers

-Deltastation: Missing roundstart headset in robotics, no spare sci equipment sets or lockers

-Donutstation: No sci drobe, no spare sci equipment sets or lockers

**Comment by MegaEmpirical** [comment]
I know box used to have some lockers, not sure if they're still there.

**Comment by ExcessiveUseOfCobblestone** [comment]
Really we need a way to dupe keys so we aren't relying on maps to fix the issue of stolen/destroyed headsets.

**Comment by RaveRadbury** [comment]
Like making them on a lathe? It seems like it would be hard to balance security vs production.

**Comment by ExcessiveUseOfCobblestone** [comment]
dupe as in it required you to have the set (or _borrow_ someone else's) prior to production.

**Comment by Tlaltecuhtli** [comment]
there are drobe refills in cargo so it doesnt rely on "map"

**Comment by RaveRadbury** [comment]
@Tlaltecuhtli Good luck refilling Donut's non-existent SciDrobe.
