### ISSUE TITLE
Purple Bartender's Uniform pants are translucent

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#43596]
The Purple Bartender Uniform tints your legs purple rather than actually being purple pants.

This is very upsetting how am I to perform my old-school Joker gimmick without the proper attire?

**Comment by SouDescolado** [comment]
Feature

**Comment by Ordonis** [comment]
Looks like this time, the joke was on YOU!

**Comment by RaveRadbury** [comment]
I used to think my life was a tragedy, but now I realize...

It's a comedy

**Comment by bgobandit** [comment]
feature, you've just never been to the cool body paint bars
