### ISSUE TITLE
Mechs can spam flashbangs infinitely without visible cooldown

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#43605]
Your eyes sting a little.
Your ears start to ring badly!
You can't hear anything!
Arezoo Babak puts the stun baton into the satchel.
Your eyes sting a little.
Your ears start to ring badly!
Your eyes sting a little.
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your ears start to ring badly!
Your eyes sting a little.
Your ears start to ring badly!
Your eyes sting a little.
Your ears start to ring badly!
Your eyes sting a little.
Your ears start to ring badly!
Your eyes sting a little.
Your ears start to ring badly!
Your eyes sting a little.
Your ears start to ring badly!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your eyes are really starting to hurt. This can't be good for you!
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
Your ears start to ring badly!
You can't hear anything!
Your eyes sting a little.
You can't see anything!
Your ears start to ring badly!
You can't hear anything!
Your ears start to ring badly!
You can't hear anything!
Your ears start to ring badly!
You can't hear anything!
Your ears start to ring badly!
You can't hear anything!
Your ears start to ring badly!
You can't hear anything!
Your ears start to ring badly!
You can't hear anything!
Your ears start to ring badly!
You can't hear anything!
Your ears start to ring badly!
You can't hear anything!
You hear metal clanking.

**Comment by Whoneedspacee** [comment]
mechs can spam a lot of things infinitely

**Comment by Barhandar** [comment]
Yes, but not to the point where there's a 3x3 square of flashbangs about to go off, pretty sure every single other thing mechs have has a cooldown between firing.

**Comment by Whoneedspacee** [comment]
oh you changed the title

yeah they should have a cooldown i thought they did weird

**Comment by necromanceranne** [comment]
Are you sure it wasn't the cluster bang? That can seen like it rapid fired the flashbangs but in reality they just reloaded and kept firing more clusterbangs.

**Comment by Barhandar** [comment]
It might have, but that just means clusterbang is disgustingly overpowered, binary (protected = unaffected, unprotected = GUARANTEED HARD RANGED PERMANENT STUN) and should be yeeted

**Comment by necromanceranne** [comment]
It's power expensive and the people it doesn't affect are those metatrusted with the weapons to kill the mech. There are far more powerful, far more universal weaponry mechs can bring to bear. Clusterbang is basically just for shuttle griff.

**Comment by kriskog** [comment]
Highly like to be the clusterbang, its got a 9 second cooldown which is kinda silly. You can chain these for quite a while with a big cell.
