### ISSUE TITLE
Humanoid hostile mob corpse

### ISSUE THREAD

**Issue by paprka** [tgstation/tgstation#4360]
When the simple mobs die, they turn into 'corpse' mobs for looting, which is a problem because currently mobs have randomized skin color and underwear/hair. Thus, syndicate/pirate/etc humanoid mobs have basic 4 way directional bald sprites, where when they die they magically grow pink hair and shit.

Additionally, syndicate simple mobs have some broken sprites and need to be 'remade'.
- They have old armor sprites.
- They wear security backpacks instead of normal backpacks. The corpses of the mobs have normal backpacks.

**Comment by tedward1337** [comment]
Is this still an issue?

**Comment by ExcessiveUseOfCobblestone** [comment]
> Is this still an issue?

**Comment by Kromgar** [comment]
@optimumtact is this  still an issue?

**Comment by optimumtact** [comment]
@Kromgar is this still an issue?

**Comment by nicbn** [comment]
Wasn't this fixed?
