### ISSUE TITLE
Teleporting an exploding fueltank can keep it outside nullspace.

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#43613]
Title, pushing a fuel tank through a bluespace portal (Hand tele or bluespace hub) with plasma gas present will cause the tank to explode but remain as an invisible, unmovable, deleted object (until the garbage subsystem fully deletes it).

Tested locally using a version of TG just a few days old:
![Ghosttank](https://user-images.githubusercontent.com/17460297/56084270-b52c8b00-5de5-11e9-82c3-09824be7a2ed.PNG)

### Reproduction:
Get a plasma canister, fuel tank, and hand teleporter.
- Open the plasma canister and flood the area with plasma
- Make a hand teleporter portal in the plasma gas
- Push the fuel tank into the portal
-The fuel tank creates sparks as it goes through the portal, igniting the plasma there and burning gas will cause the tank to instantly explode, yet leaving behind a 'ghost' due to some odd behavior with the portal as it goes through.
...
Main priority for this issue is that on TG versions from several months old  the 'ghost' fueltank could explode itself, resulting in a recursive explosion that could crash the server. At some point the recursive explosion part of this bug was fixed but the 'ghost' tank wasn't.

Local testing from a TG version around last December:
![Explosionoof](https://user-images.githubusercontent.com/17460297/56084326-91b61000-5de6-11e9-8d26-bf22297f0c3b.PNG)

Though not yet as serious of a bug as it was previously, the possibility of someone eventually finding a new object that has the potential to repeatedly explode isn't something to be overlooked if such a method can be found.

**Comment by ATH1909** [comment]
A barrel of explosives or black powder, perhaps? A maxcap?

**Comment by SpaceManiac** [comment]
We should probably have `forceMove` cancel out if the atom is deleted during it

**Comment by GravitronBlue** [comment]
Obsolete report at this point, if someone finds a currently working recursive explosion method I'll leave it to them to make a specific bug report about it.
