### ISSUE TITLE
Energy sword throw speed reverts to 3 after thrown.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43621]
## Reproduction:
1. Spawn an energy sword /obj/item/melee/transforming/energy/sword/saber/red
2. Check its throw_speed while off, it will read 3.
3. Turn the energy sword on, it will change to 4.
4. Throw the energy sword, notice the throw_speed drops back to 3.
5. Be unable to embed because you are below threshold.

This is fixed in game by turning the sword off and on again to get the throw_speed back up to 4.
Bit of a problem because the energy sword is definitely supposed to embed given the increased embed chance.

EDIT: This happens for all transforming weapons. They return to their original throw speed value.

**Comment by adamkad1** [comment]
doesnt esword turn off when it leaves your hand?

**Comment by WJohn** [comment]
Nope, only the double esword does that. Inconsistency there, too.

**Comment by nemvar** [comment]
Desword kinda needs to turn itself off for balance reasons. Onehanded people can't pick up active deswords and this kind of weapon tends to create loads of these.

**Comment by nicbn** [comment]
Could make it so that one handed people are able to use deswords instead (but while two handeds still need both hands free)

**Comment by Barhandar** [comment]
Idea: can use desword one-handed but every swing you take there's a chance to cut off one of your other limbs, including head.
