### ISSUE TITLE
pAI radio system is all sorts of broken

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#43620]
Taken from ```tgstation/code/game/objects/items/devices/paicard.dm```
```
if(pai.radio)
			dat += "<b>Radio Uplink</b><br>"
			dat += "Transmit: <A href='byond://?src=[REF(src)];wires=[WIRE_TX]'>[(pai.radio.wires.is_cut(WIRE_TX)) ? "Disabled" : "Enabled"]</A><br>"
			dat += "Receive: <A href='byond://?src=[REF(src)];wires=[WIRE_RX]'>[(pai.radio.wires.is_cut(WIRE_RX)) ? "Disabled" : "Enabled"]</A><br>"
		else
```

This doesn't work at all. It just stays "Enabled" for both no matter how many times you click.

On the pAI side, going to "Radio Configuration" pops-up a station-bounced radio window where the microphone is disabled, the speaker enabled, and everything is grayed out and cannot be changed by pAI or master.

I don't know when this broke and I don't really know how to fix this but I might give it a shot since I'm working in this area. Anyone else would probably do a better job than me, though.

**Comment by RaveRadbury** [comment]
After further testing it seems that the pAI can access it's radio only when its in holochassis mode. Still not sure about what's going on for the owner side of things.

**Comment by ExcessiveUseOfCobblestone** [comment]
@RaveRadbury you can have issues close automatically on PR merge by saying `fix #issuenum` or `closes #issuenum` with nothing in between.
