### ISSUE TITLE
if server OOMs the verbs boo and possess become available

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#43638]
![image](https://user-images.githubusercontent.com/222630/56257350-ccd37000-6080-11e9-9636-a28796dfcf7e.png)

**Comment by ATH1909** [comment]
"OOMs"?

**Comment by Fikou** [comment]
feature

**Comment by SpaceManiac** [comment]
There is likely to be nothing we can do about this, and anyways if the server has crashed already who cares
