### ISSUE TITLE
You can put bots into cryo.

### ISSUE THREAD

**Issue by LegendaryMister151** [tgstation/tgstation#43641]
Issue reported from  Round ID: 106301 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512

![image](https://user-images.githubusercontent.com/46329759/56228655-32eed180-6046-11e9-826a-f376cc1f116b.png)
![image](https://user-images.githubusercontent.com/46329759/56228676-400bc080-6046-11e9-832e-6ece0c1836ae.png)
![image](https://user-images.githubusercontent.com/46329759/56228824-911bb480-6046-11e9-8c6a-d0964ae86398.png)
sleep tight cleanbot.

**Comment by RaveRadbury** [comment]
Feature

**Comment by GunHog** [comment]
Water cooling.

**Comment by RaveRadbury** [comment]
I dream of bot snoring.

**Comment by Jimmius** [comment]
do cleanbots dream of electric sheep?

**Comment by nicbn** [comment]
Lovely

**Comment by OverlyGeneric** [comment]
If you can put bots into cryo, can you put Ian into cryo? 🤔

**Comment by RaveRadbury** [comment]
@OverlyGeneric Cryo-Ian Confirmed.

**Comment by bgobandit** [comment]
the real problem is its sprite is popping out of the tube

**Comment by PKPenguin321** [comment]
>the real problem is its sprite is popping out of the tube

I don't think it's even doing that?

**Comment by LegendaryMister151** [comment]
just thought it wasn't intended for it to be able to be put in cryo & for it to start snoring, guess i should have elaborated a little.

**Comment by ExcessiveUseOfCobblestone** [comment]
twinkle twinkle little bot
how I wonder what you thought
located in the cryo tube
always useful, never rude
twinkle twinkle little bot
how I wonder what you thought

**Comment by ExcessiveUseOfCobblestone** [comment]
bots have snoring modules is now canon btw
