### ISSUE TITLE
Left active chainsaw inhand is backwards.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43640]
## Round ID:
106291

## Reproduction:
1. Spawn chainsaw /obj/item/twohanded/required/chainsaw
2. Hold with your LEFT hand and activate.
3. See how it shifts to practically behind you on the side sprite.

![](https://i.imgur.com/O8UAUoq.png)

**Comment by RaveRadbury** [comment]
Chainsaw tail augs when?

**Comment by ATH1909** [comment]
He's doing that edgy upside-down lightsaber wielding thing, but without the second lightsaber.
