### ISSUE TITLE
Hair Preview Error #43564

### ISSUE THREAD

**Issue by Okand37** [tgstation/tgstation#43649]
Round ID: 106370

When previewing the following hairs in the setup character menu, they showed up as bald on the character sprite with "ERROR" written in blue:
Cornrow Braid
Cornrow Tail
Dave
Mohawk (Unshaven)
Ponytail (Ziegler)
Scully

Unknown whether or not they show ingame. Can be reproduced by viewing the aforementioned hairs in the character menu:
![8m8BO0Q](https://user-images.githubusercontent.com/23388888/56321958-052c8a00-6125-11e9-9ef9-68f706026e67.png)

**Comment by Coconutwarrior97** [comment]
This is also produced in game. 
![image](https://user-images.githubusercontent.com/40315842/56337689-15b42300-616c-11e9-8ca9-5ce00567c25e.png)

**Comment by ExcessiveUseOfCobblestone** [comment]
@pireamaineach

**Comment by pireamaineach** [comment]
Well fuck.

**Comment by pireamaineach** [comment]
Probably mistyped icon states.
