### ISSUE TITLE
antimagic from chaplain's null rod not working again

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#43646]
had bo staff and got timestopped

**Comment by Daxxed** [comment]
I think it only protects when in hand, pocket, belt or back slot ( not inside your bag ).
Some xenobio crossbreed timestops might also not be consideed magic but I haven't bothered testing.

**Comment by ATH1909** [comment]
*sigh

**Comment by theXDkidoflol** [comment]
Timestop isn't considered magic for... SOME. Strange reason.

Nothing can save you from the bullshittery.


> I think it only protects when in hand, pocket, belt or back slot ( not inside your bag ).

it protects you as long as you have it on.

**Comment by Daxxed** [comment]
> 
> 
> Timestop isn't considered magic for... SOME. Strange reason.
> 
> Nothing can save you from the bullshittery.
> 
> > I think it only protects when in hand, pocket, belt or back slot ( not inside your bag ).
> 
> it protects you as long as you have it on your person, whether that's in your bag, waist, exosuit, whatever.

Both wrong
Wizard timestop is blocked by antimagic, null rods in backpacks do NOT work
Didnt bother testing xenobio crossbreed timestops though

**Comment by ATH1909** [comment]
Wait, was your bo staff the null rod kind or the other kind (the one from here: https://github.com/tgstation/tgstation/blob/e13330fa9565b5b391ddd451cb0782b472c65a21/code/datums/martial/sleeping_carp.dm)?

**Comment by Fikou** [comment]
had the same bug with a relic warhammer a month ago, was holding it in hand and dropped from timestop, maybe it just doesnt work if its in hand

**Comment by 81Denton** [comment]
What's the round ID? In what slot was it? Wizard or xenobio timestop?

**Comment by ATH1909** [comment]
All (or at least almost all) of the xenobio timestop effects ignore antimagic, as otherwise, you could cheese them and become immune to timestops that you're not supposed to be immune to by having a null rod on your person.
