### ISSUE TITLE
Broadcast Range: Russian Vending Machines!

### ISSUE THREAD

**Issue by gamefreak2998** [tgstation/tgstation#43652]
Feature requests are not handled in the repository. The best place to discuss these ideas would be on the /tg/station 13 forums here: https://tgstation13.org/phpBB/viewforum.php?f=9&sid=5153c1c704a4fb1006bf7a265e45e03f
The Russian Vending machine crate from the expanded broadcast range isnt too useful since boards don't exist for the machines. Any chance we could get them put in for this crate or have the ability to use the existing non russian version of these machines and restock them with the russian to convert them to their (SUPERIOR) soviet counterpart? Would be a great way to meme the station

**Comment by 81Denton** [comment]
For this, please open a thread in the Ideas forum: https://tgstation13.org/phpBB/viewforum.php?f=9

I have nothing against the idea per se, Github is just a bad place to track feature requests.
