### ISSUE TITLE
Podpersoning removes someones quirks

### ISSUE THREAD

**Issue by nemvar** [tgstation/tgstation#43655]
## Round ID:

106371

## Testmerges:

Whatever was testmerged on Terry at the time. Doubt it interfered with this.

## Reproduction:

I lost my quirks after getting revived as a podperson. Doesn't seem intended.

**Comment by Barhandar** [comment]
Doesn't cloning also keep doing this?

**Comment by AzureWildfire** [comment]
Yep cloning does the same thing

**Comment by optimumtact** [comment]
not all quirks are tied to the mind so they will be lost when a new mob body is created
