### ISSUE TITLE
donut station has no station blueprints (?)

### ISSUE THREAD

**Issue by zeroisthebiggay** [tgstation/tgstation#43663]
Issue reported from  Round ID: 106526 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1462

>be traitor
>have to steal blueprints
>go to ce's locker
>not there
>ask ce
>doesn't have them
>redtext

**Comment by Barhandar** [comment]
Donut's CE locker is exactly the same as meta's CE locker so most likely someone stole the blueprints before either you or CE got to them.

Do high-risk items have logging?

**Comment by MMMiracles** [comment]
CE's locker spawns blueprints when it's initial content is added, so someone definitely got to the locker first and stole it.

**Comment by 81Denton** [comment]
Donut spawns a regular locker, someone just took them first.
