### ISSUE TITLE
Strange plant producing chems non-obtainable by normal means

### ISSUE THREAD

**Issue by Toxici11i** [tgstation/tgstation#43668]
Server: Fulpstation(running nearly clean /tg/ source)
Round ID:560
Description: Strange Plants can contain liquid forms of chems that are not supposed to be able to be liquids (BZ, Nitryl, Nobilium). Also repored in #28865 but was only fixed by a patch unintentionally for reagent.
Reproduction: Roll RNG 24/7 on strange plants, you can get anything from Heparin to Nitryl
Suggestion: Stop admin only/debug/unobtainable chems from being rolled.

**Comment by actioninja** [comment]
This is intentional.

**Comment by Barhandar** [comment]
Admin only/debug chems (adminodrazine, for example) already cannot be rolled, the rest are intentional.

**Comment by 81Denton** [comment]
Debug or otherwise unbalanced chems are already prevented from appearing through the `can_synth` flag, the rest are intentional.
You could argue that gaseous reagents shouldn't be available as a liquid, but then again these are seeds that magically produce completely random reagents.
