### ISSUE TITLE
Failed summon item dupes certain item procs

### ISSUE THREAD

**Issue by Daxxed** [tgstation/tgstation#43660]
## Explanation
When a summon item fails because the item cannot be teleported there, the item still appears in your hand but dissapears upon interaction, this has some nasty side effects.
## Reproduction:
Acquire summon item spell
Mark nuclear authentication disk for recall
Go to lavaland or other zlevel
Summon item, item appears in your hand 
ADMIN LOG: The nuclear authentication disk has been moved out of bounds in nonexistent location. Moving it to Research Testing Range (143, 94, 2) (JMP).
Drop item, put in bag, switch hands 
ADMIN LOG: The nuclear authentication disk has been moved out of bounds in nonexistent location. Moving it to Fore Primary Hallway (106, 158, 2) (JMP).

One could already really fuck ops with just the spell, but being able to move it twice every summon is YIKES
#35757 Maybe relevant

**Comment by ExcessiveUseOfCobblestone** [comment]
in b4 transfertoloc proc with no conditional

**Comment by OverlyGeneric** [comment]
Good thing it's highly unlikely you would have this spell during Nuke Ops.

**Comment by ExcessiveUseOfCobblestone** [comment]
it's available as a tendy drop
