### ISSUE TITLE
Debug verb "Pump Random Event" does not work

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#43674]
Taken from `code\modules\admin\verbs\debug.dm`

`/client/proc/pump_random_event()`
`	set category = "Debug"`
`	set name = "Pump Random Event"`
`	set desc = "Schedules the event subsystem to fire a new random event immediately. Some events may fire without notification."`
`	if(!holder)`
`		return`
`	SSevents.scheduled = world.time`
`	message_admins("<span class='adminnotice'>[key_name_admin(src)] pumped a random event.</span>")`
`	SSblackbox.record_feedback("tally", "admin_verb", 1, "Pump Random Event")`
`	log_admin("[key_name(src)] pumped a random event.")`

This gives you the feedback saying you pumped, but never pumps. I did it 50 times in a row, nothing.

This is preventing #43666 the "Disaster" game mode I'm working on from starting correctly, as I seek to delay the round's first event with 
`/datum/game_mode/disaster/post_setup()`
`	SSevents.scheduled = world.time + 5 MINUTES` 
and the event still just procs roundstart.

**Comment by RaveRadbury** [comment]
@ExcessiveUseOfCobblestone

**Comment by RaveRadbury** [comment]
Whoops didn't realize that you had to enable debug-game first. Not a bug. Just not straightforward.

**Comment by ExcessiveUseOfCobblestone** [comment]
feel free to add a comment in the code if it's not clear.
