### ISSUE TITLE
 "Severe damage to brain language center"cerebral trauma broken and won't fix when a surgery is done.

### ISSUE THREAD

**Issue by PhantomEpicness** [tgstation/tgstation#43677]
Issue reported from  Round ID: 106628 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1466
After taking a ton of meth I died and was cloned with the defects still on me .Then I was put into surgery to fix it and it did not fix, though the others did. The trauma makes anyone in chat appear to speak gibberish so it you can't understand it.

**Comment by HomocidlePancakes** [comment]
Are you sure it wasn’t deep-rooted or permanent? The only way to cure deep-rooted traumas is lobotomy and permanet traumas are well... permanent.

**Comment by XDTM** [comment]
Languages are a bit fucky when mob changes are involved, so it's possible that cloning replaced the original copy of the known languages with the already-traumatized version

**Comment by coolguyethanw** [comment]
I had surgery to fix it and I appeared normal to health scans,but it stayed. I could talk to people normally but I could not understand them at all, however it did go away randomly after a long time.

**Comment by adamkad1** [comment]
The same applies to 'cant form complex sentences' trauma
