### ISSUE TITLE
E-dagger doesn’t imbed

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#43679]
I was told that it’s supposed to have 100% imbed chance but it never seems to imbed. Seems weird considering even e-swords can imbed. (Holy shit I used imbed 3 times over the span of 2 sentences it’s triggering me)

**Comment by Barhandar** [comment]
Because it's "embed" in modern times. And yes, it theoretically has 100% embed but practically some chumbis made it throwspeed 3 (which completely prevents embed from working), which I wasn't aware of when talking about its embed.
