### ISSUE TITLE
Swarmers can cause breaches by breaking directional windows.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#43686]
Swarmers can pretty much syphon box shuttle and kill everyone because it has directional windows at the south part.

**Comment by OverlyGeneric** [comment]
They can also kill the AI by teleporting it into space but that isn't a bug or a violation against swarmer lawsets. :moyai:

**Comment by HomocidlePancakes** [comment]
Wasn’t it ruled that swarmer laws are just fluff and they are allowed to kill via environment

**Comment by ExcessiveUseOfCobblestone** [comment]
i've never understood why the thrusters aren't blocking atmos. You would logically not just have flimsy glass as a safety measure of exposing the entire shuttle to space.

**Comment by 81Denton** [comment]
@ExcessiveUseOfCobblestone Ninja keeps arguing that it's a sprite issue

**Comment by ExcessiveUseOfCobblestone** [comment]
there should be walls or something under them in that case, or a variant which does block atmos.
