### ISSUE TITLE
Plasma Cutters are affected by EMP

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#43685]
They are recharged by plasma and not electricity. Seems silly that the loose all their charge from EMP

**Comment by Barhandar** [comment]
It's because they're a snowflake gun with internal "electric" cell that gets recharged by slapping the gun with plasma as opposed to sticking it in a charger.

**Comment by HomocidlePancakes** [comment]
If it's indeed an "electric" powercell then you should be ablt to recharge it via recharger

**Comment by Barhandar** [comment]
The quotes are because it's electric codewise only, and also recharging it like that caused a shitstorm and resulted in complete gimping of plasmacutters for combat, even the one you can't spam or recharge.

**Comment by Ratvar** [comment]
Not a bug

**Comment by ExcessiveUseOfCobblestone** [comment]
Have them explode when EMP'd because the heating mechanism goes haywire and heats up all the plasma at once.

> If it's indeed an "electric" powercell then you should be ablt to recharge it via recharger

not going to happen

**Comment by HomocidlePancakes** [comment]
>If it's indeed an "electric" powercell then you should be ablt to recharge it via recharger

It was deep lore I didn’t actually mean this reeeeeeee

**Comment by timothymtorres** [comment]
Someone can just make a new branch and reuse the code from #44019
