### ISSUE TITLE
VR Hub pacifism carries over in Snowdin

### ISSUE THREAD

**Issue by erwgd** [tgstation/tgstation#43690]
## Round ID:
106786

## Testmerges:

Server revision compiled on: 
Master commit: 5239d718d6f088e8f4270c02c643e59e993063ac
The following pull requests are currently test merged:
#43349: 'Handle OoM errors.' by MrStonedOne at commit caf2ef8729

## Reproduction:
Enter VR, notice you're pacifist in most of the hub. Most other VR locations lift pacifism when appropriate, but you'll remain pacifist in VR Snowdin.

**Comment by Whoneedspacee** [comment]
fuck me

**Comment by ATH1909** [comment]
I saw a guy fire deathsquad weapons in the main hub, so maybe going into the weapon testing simulation and exiting it again can remove your pacifism?

**Comment by Whoneedspacee** [comment]
it shouldnt. the pacifism is specifically area based to prevent stuff like that from happening.

**Comment by Whoneedspacee** [comment]
wait are you sure he wasnt shooting them off in the fighting room. in hindsight i probably shouldve made it harder to shoot projectiles back through the airlock but it shouldnt be that bad

**Comment by ATH1909** [comment]
> it shouldnt. the pacifism is specifically area based to prevent stuff like that from happening.
> 
> unless they somehow changed bodies with a non virtual mob i dont see how that couldve happened.

Well, they were somehow able to do it.

Maybe they briefcase launchpadded in from another sim?

**Comment by Whoneedspacee** [comment]
was he in the fighting room south or was he just running around and shooting.

**Comment by ATH1909** [comment]
He was in the hub itself, repeatedly spawnkilling me with deathsquad weaponry (which I'm not trying to whine about; it wasn't too bad).

**Comment by adamkad1** [comment]
the pacifism in lavaland hub is a bit anooying too cause you cant try out your guns

**Comment by adamkad1** [comment]
and also theres a shambling miner mod in final room of bossrush, which is also affected by pacifism
