### ISSUE TITLE
VR spawner has infinite respawns

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#43695]
Issue reported from  Round ID: 106849 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1462

You can infinitely respawn and ghost. I'll let the pictures speak for themselves.

![image](https://user-images.githubusercontent.com/38219334/56690817-ab0c6580-66de-11e9-933a-98c92e6df995.png)

![image](https://user-images.githubusercontent.com/38219334/56690827-b19add00-66de-11e9-9db5-8df9dc6a2148.png)

This congaline continued to the spawnpoint.

**Comment by ATH1909** [comment]
And this is a problem because...?

**Comment by PKPenguin321** [comment]
Lag, probably.

Could make dead/clientless VRpeople fade out and vanish

**Comment by Whoneedspacee** [comment]
yes and xenobiologists can make 10000000 monkeys

your point?

**Comment by RaveRadbury** [comment]
Monkey spawn is capped.

**Comment by HomocidlePancakes** [comment]
Step 1: Make monkeys until they cap
Step 2: Gib them with fields
Step 3: Go to step 1 until your game begins to crash when you are in proximity of gibs

**Comment by Barhandar** [comment]
Monkeys are capped, monkeymen are not. Also gibbing, yes.

**Comment by Daxxed** [comment]
You have a point, SSD/catatonic VR characters should be cleaned up to save performance.
Ballsy way to prove there is indeed an issue though, doing this on a live round.

**Comment by ExcessiveUseOfCobblestone** [comment]
epic
