### ISSUE TITLE
Zombies can't eat brains

### ISSUE THREAD

**Issue by Ispiria** [tgstation/tgstation#43702]
## Reproduction:

Be a zombie, romerol or otherwise
Acquire brain, soul-inhabitated or otherwise
Attempt to click on/eat brain
Fail

Clearly this is gamebreaking and of crucial importance to maintain muh immersions.

**Comment by ATH1909** [comment]
Real talk, though, this should actually be "fixed". It's lame that our zombies can't eat brains (without deep-frying them or the like).

**Comment by MegaEmpirical** [comment]
I've had zombies walk up to me as a chef and ask me to fry brains they'd collected. Both put of fear of being killed next and for amusement, I've complied.
