### ISSUE TITLE
Add a Syndicate item for internals

### ISSUE THREAD

**Issue by ajvsol** [tgstation/tgstation#43718]
There's Syndicate items for space suits and common kits like the toolbox, surgical or medical kit but nothing which can be used to replace the emergency internals kit you spawn with. 

Syndicate Internals Kit (1 TC):
- 2x Extended-capacity emergency oxygen tank
- Breath mask
- Salbutamol injector

Handy for when you're trapped in an area by the AI so need to create a hull breach and use with a space suit to escape.

**Comment by ExcessiveUseOfCobblestone** [comment]
Feature requests are not handled in the repository. The best place to discuss these ideas would be on the /tg/station 13 forums here: https://tgstation13.org/phpBB/viewforum.php?f=9&sid=5153c1c704a4fb1006bf7a265e45e03f
