### ISSUE TITLE
AI's bolting upon death

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#43717]
So for some reason AIs are immediately bolting upon death even if an ai unbolts themselves before hand, on top of this they're unable to be wrenched by borgs now so the only method of dealing with them is intellicard which is absolute bullshit.

**Comment by ExcessiveUseOfCobblestone** [comment]
Not sure if it was a balance decision, an oversight, or a bug so me just go with lesser of 3 evils

**Comment by ATH1909** [comment]
We should make it so that AIs UNbolt themselves when they die, even if they were bolted before.

... Maybe we should let wrenches unbolt even active AIs too?

**Comment by ExcessiveUseOfCobblestone** [comment]
I'll entertain unbolt on death but idk about force-unbolting at any time.

**Comment by carshalash** [comment]
Being rebolted upon death is extremely shitty and removes the possibility of anyone retrieving your core without an intellicard.

**Comment by YPOQ** [comment]
It is intended for them to auto-unbolt on death, but the code hasn't been updated to the move_resist system.
https://github.com/tgstation/tgstation/blob/1b426379ed178a63c0caf7cf787b4636be14a73a/code/modules/mob/living/silicon/ai/death.dm#L17

I'm not sure what would cause them to force-bolt on death and couldn't repro it on a local server.

**Comment by Barhandar** [comment]
Are AI cores with dead AIs in them destructible? If not, WALL OF AIS
