### ISSUE TITLE
Default cam on SS13 Network sends to vr

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#43719]
Pretty self explanatory, it should be obvious what the most worrisome about this is right now. Screenshot for evidence.

![image](https://user-images.githubusercontent.com/16896032/56808921-00c74600-6876-11e9-94fe-d99c2fe8bfb8.png)

**Comment by Whoneedspacee** [comment]
why are there so many of these coming out after there was already a testmerge just fucking end my life already

**Comment by ExcessiveUseOfCobblestone** [comment]
you can see ~~dead~~ vr people

**Comment by ExcessiveUseOfCobblestone** [comment]
can ayys jump to this area via cams by chance lol

**Comment by ATH1909** [comment]
> can ayys jump to this area via cams by chance lol

Time to banish my abductees into/trap my abductees in VR (and also learn spells and get nuke op gear, lol).

**Comment by ExcessiveUseOfCobblestone** [comment]
I was thinking abduct VR people to allow them infinite lives onstation in exchange for easy victories.

**Comment by carshalash** [comment]
Actually, while we're at it. The decoration borg you have there is automatically enslaved to the ai.

**Comment by ATH1909** [comment]
> Actually, while we're at it. The decoration borg you have there is automatically enslaved to the ai.

You can even deconstruct it, print new flashes for it in the operative simulation, smuggle the flashes and an uplink into the hub, buy a syndicate surgery kit, and borg a dead VR ghost role person.

**Comment by carshalash** [comment]
![image](https://user-images.githubusercontent.com/16896032/56850455-5408c980-6946-11e9-90cb-183872d0950d.png)
tfw you change from labor to ss13 and see the cargo tech that went missing 10 minutes ago drinking a beer.

**Comment by ShizCalev** [comment]
i have a solution in works for this. will pr it tomorrow.
