### ISSUE TITLE
Showers will continue playing sounds when off if turned on and off very quickly.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43725]
## Round ID:
107033

## Reproduction:
1. Spawn a shower /obj/machinery/shower
2. Turn it on and off in about under half a second, roughly.
3. Notice how it continues to play the shower sound effect. You can walk away, come back, it'll keep playing the sound as if it was on. You can reset this by turning the shower on and off again.

**Comment by GhostAvenger** [comment]
Pretty sure whenever you start a shower, it plays a block of audio, and the game checks if the shower is still on when the audio ends, and loops if it is still on, meaning the audio will not turn off.

**Comment by optimumtact** [comment]
not really a bug, factors of how limited the sound engine is in byond
