### ISSUE TITLE
Music mood bonus while being deaf.

### ISSUE THREAD

**Issue by Rowelll** [tgstation/tgstation#43720]
Issue reported from  Round ID: 106988 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1467

I was deaf (no ears), but I had a mood bonus for cool music.

lmao.

**Comment by SouDescolado** [comment]
I mean, deaf people go to concerts and everything where they feel the vibrations or whatever they feel.

**Comment by RaveRadbury** [comment]
You were picking up on those sweet bass vibrations.

**Comment by Rowelll** [comment]
~~then call it cool vibrations mood~~

**Comment by OverlyGeneric** [comment]
Deaf people literally feel good vibes, man. :moyai:

**Comment by Rowelll** [comment]
🗿
