### ISSUE TITLE
*dab oddities

### ISSUE THREAD

**Issue by zeroisthebiggay** [tgstation/tgstation#43736]
## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:

you can *dab while cloning
you can *dab while stunned (it won't display an emote but you'll still get the effects)
you can *dab while in handcuffs to drop them
you can probably *dab while asleep

**Comment by Barhandar** [comment]
Test merge issue.

**Comment by ATH1909** [comment]
You can also do this: https://www.reddit.com/r/SS13/comments/bh654h/local_lizardperson_dabs_over_200_times_and/
