### ISSUE TITLE
pAIs examining on shift click not working

### ISSUE THREAD

**Issue by Okshi91** [tgstation/tgstation#43730]
Issue reported from  Round ID: 107057 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1466

pAIs cannot examine with shift-click under any circumstances, however they can examine via the right click menu, though only in holoform. This started happening after the pAI HUD and newscaster update, and has happened on multiple rounds for multiple players.

To reproduce, get downloaded as pAI, then try to examine anything with shift-click.

**Comment by RaveRadbury** [comment]
Oof, this is my doing somehow. I'll try and figure it out.
