### ISSUE TITLE
super high temperatures not damaging stuff.

### ISSUE THREAD

**Issue by ghoststuff** [tgstation/tgstation#43733]
Problem Description: temperature over 2.2k*C and plasmafire not affecting aicore nor any walls in area.

What did you expect to happen:  at least stuff get damaged at some rate, since  highest commonly used metal aka titanium melts at 1.8k.

What happened instead: no damage vs slow or heavy damage.  while i understand why certain items should be fireproof, and why base parts should withstand alot of temperature/be immune to fire, above certain treshold (1.9k*C) most components and base should slowly or fastly disintegrate, leading to obvious breaches. and since space = vent = nothing burns , this would make mass plasma fire trick a bit harder to pulloff (requiring  need control of resulting temperature to be actually burning and not melting station and selfextenguish), 

Why is this bad/What are the consequences:  mass plasmafires are super effectrive, without any drawbacks, and by amount of them being used by trators, apparently also quite easy to pulloff.

Steps to reproduce the problem: well, burn stuff.

Revision:  latest.

**Comment by Barhandar** [comment]
Even a regular fire will be higher than that temperature. The point is to be good for gameplay, not realistic.

Also, hot enough fires _already_ burn through the floor.

**Comment by OverlyGeneric** [comment]
I'm unsure if this is feasible to code or even worth it.

Plasma fires are pretty easy to handle but holes venting the air from the station is a lot worse and more difficult to fix.

**Comment by Robustitron** [comment]
Full tile windows are also immune to temperature and pressure, even weak regular glass ones.

Light a hot fire and watch all the directional windows and airlocks melt, but not the full tiles.

**Comment by optimumtact** [comment]
this isn't so much a bug as a specific design decision/oversight

**Comment by LemonInTheDark** [comment]
Resolved? Kinda?
