### ISSUE TITLE
Sand and Glass Golems Absorb All Projectiles

### ISSUE THREAD

**Issue by YPOQ** [tgstation/tgstation#43737]
Local server 1b426379ed178a63c0caf7

#42974 might be related

For example sand are only supposed to absorb bullet and bomb projectiles
https://github.com/tgstation/tgstation/blob/4cf3ea152fff247bc53e5a182af01c316baeb479/code/modules/mob/living/carbon/human/species_types/golems.dm#L366-L373
but they are also unaffected by lasers.

This appears to be because returning any value in `species/bullet_act()` causes `human/bullet_act()` to early return
https://github.com/tgstation/tgstation/blob/4cf3ea152fff247bc53e5a182af01c316baeb479/code/modules/mob/living/carbon/human/human_defense.dm#L43-L47

**Comment by Barhandar** [comment]
The early return is (hopefully) irrelevant, it's just feedback that returns same values later. Something causes it to reach BULLET_ACT_BLOCK erroneously. Or otherwise mishandle it.

**Comment by YPOQ** [comment]
I didn't look too carefully but it looks like bullet_act on living is responsible for actually on_hit and the early return skips that.

**Comment by ATH1909** [comment]
https://i.kym-cdn.com/entries/icons/original/000/029/223/cover2.jpg

**Comment by 4dplanner** [comment]
OP is right, just needs to be changed to return ..()
