### ISSUE TITLE
Singletank bombs crash the server

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#43740]
Singletank bombs (which are already fucking awful because you can spam dozens of them) are causing servers to crash when people are going ham with them. They really need removed.

**Comment by carshalash** [comment]
Wait that's what's causing it?

**Comment by Whoneedspacee** [comment]
i dont know why but im doubting this and assume this is just some way to further convince people to get them removed

if explosions crashed the game we'd have way more fucking issues coming up lol

**Comment by Barhandar** [comment]
Which of the singletank bombs, the actual tritium ones, or the special snowflake decade-old-untouched-code ones that need a trigger?

**Comment by Daxxed** [comment]
No reproduction, no round, didnt happen
