### ISSUE TITLE
add_overlay()ing an atom or a mutable appearance with priority set to TRUE results in it being reapplied every time overlays are compiled/memory leak?

### ISSUE THREAD

**Issue by silicons** [tgstation/tgstation#43742]
## Round ID:
None, local testing
## Testmerges:
None
## Reproduction:
1. Mark an atom/mutable appearance
2. add_overlay(marked, 1)
3. Do this on a human mob, be that human mob, rapidly drop and equip/otherwise change an item's inventory slot a bit and you'll find your mob flooded with overlays.

**Comment by optimumtact** [comment]
priority overlays might be added every time? probably a bug

**Comment by optimumtact** [comment]
were you able to confirm this?

**Comment by optimumtact** [comment]
Oh this was fixed and also was the cause of the mining client slowdown lol
