### ISSUE TITLE
Walking by soap diagonally makes you slip

### ISSUE THREAD

**Issue by Couls** [tgstation/tgstation#43749]
Round ID: N/A Tested locally

Testmerges: N/A Tested locally

Reproduction: Run diagonal one tile above soap, tested locally with no test merges on local server. This only happens in two directions, northwest and southeast if you cross soap in either of these directions you will slip but if you cross one tile southwest or northeast you won't slip
![ezgif-5-23859519eb3a](https://user-images.githubusercontent.com/30060146/56871632-a00f4900-69ee-11e9-90ff-ede9caaf0ea8.gif)

**Comment by GunHog** [comment]
Your gif makes it look like you walked directly over it.

**Comment by HomocidlePancakes** [comment]
When you are running diagonally, you are actually switching from moving in two directions very fast (right and down in this case). It’s smoothed so you can’t see it. This isn’t a bug

**Comment by ATH1909** [comment]
> When you are running diagonally, you are actually switching from moving in two directions very fast (right and down in this case). It’s smoothed so you can’t see it. This isn’t a bug

> if you cross soap in either of these directions you will slip but if you cross one tile southwest or northeast you won't slip"

Are you SURE that this isn't a bug?

**Comment by HomocidlePancakes** [comment]
I literally just explained why this is not a bug. Try imagining his ACTUAL(not visual) pathing in the case where he slips and the two cases he doesn’t slip

**Comment by optimumtact** [comment]
it's nto a bug
