### ISSUE TITLE
The handle_cavity step is not repeatable

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#43753]
Unlike the manipulate_organs step from the organ manipulation surgery, the handle_cavity step from the cavity implant surgery doesn't have the "repeatable" variable set to true.

What this means is that if you accidentally implant the wrong thing in someone's chest with the handle_cavity step of the cavity implant surgery, you have to end and then redo the entire surgery to remove that item (instead of just pulling it out while the patient's chest is still open) and then end and then redo the entire surgery _again_ if you want to implant whatever item you had wanted to implant in there before.

**Comment by ATH1909** [comment]
The relevant pages of code, if you'd like to look at them yourself:
https://github.com/tgstation/tgstation/blob/ccadcf61d3d383191d950a8ac5a350b0213ba9e9/code/modules/surgery/organ_manipulation.dm
https://github.com/tgstation/tgstation/blob/ccadcf61d3d383191d950a8ac5a350b0213ba9e9/code/modules/surgery/cavity_implant.dm

**Comment by Cyprex** [comment]
Likely working as intended, PR a fix if you feel it shoudl be different.

**Comment by ATH1909** [comment]
> Likely working as intended, PR a fix if you feel it shoudl be different.

How could this possibly be working as intended? Both organ manipulation and cavity manipulation deal with stuffing things into or extracting things from someone's body surgically. Only cavity manipulation requires you to stitch someone's chest up and then reopen it again every time you want to interact (as in, insert _OR_ extract _ONE_ thing a _SINGLE_ time) with someone's chest cavity. In comparison, organ manipulation lets you extract and reinsert organs into someone as many times as you'd like while your patient has a giant hole open in them, without needing to stitch up and then reopen the hole for each organ insertion or extraction you'd like to perform.

**Comment by ExcessiveUseOfCobblestone** [comment]
At best this is an oversight from when organ manip was added but *shrug* it makes sense to be repeatable.
