### ISSUE TITLE
CTRL-Click on non-grab intent gives neckgrab timer but cannot upgrade grab

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#43759]
CTRL-Clicking someone in an aggressive grab or higher while not on grab intent tells you that you are tightening your grip on the target, but does not actually upgrade the grab if you stay still for the delay.

A related thing: If you start upgrading a grab on grab intent, but switch to another intent, you also fail to upgrade the grab. Likely a symptom of the above issue.

**Comment by HomocidlePancakes** [comment]
*shrug. This always seemed intended to me. Grab action requires grab intent. Same thing happens on martial arts and benos. It’s actually pretty consistent.

**Comment by py01** [comment]
If you shouldn't be able upgrade, you at least shouldn't get the delay bar appear from control clicking on an aggressive grab.

**Comment by HomocidlePancakes** [comment]
Why not? Switch to grab intent at the last second and you will be able to finish your action. I usually disarm people while upgrading my grab to secure it.

**Comment by py01** [comment]
at least have a message for why the grab upgrade failed, to prevent confusion on the mechanic

**Comment by HomocidlePancakes** [comment]
>At least have a message

1)This is a nitpick.
2)There is nothing confusing about having to use grab intent for a grab action.

**Comment by ATH1909** [comment]
> 2)There is nothing confusing about having to use grab intent for a grab action.

Uh, I'm pretty sure that it is, in fact, confusing. I remember struggling to figure out how to strangle people the first time that I was a xenoling and needing to ahelp to figure it out (thinking that grab intent was disarm intent and vice versa didn't help much, but still).

**Comment by py01** [comment]
its probably a one line change to add a message to the failure anyway, i'll pr it later

**Comment by HomocidlePancakes** [comment]
You were new and messed up grab and disarm intent ATH. This is somewhat unrelated to what we were talking about
