### ISSUE TITLE
Unable to import SQL schema into a database

### ISSUE THREAD

**Issue by tbcr** [tgstation/tgstation#43757]
## Reproduction: When attempting to import the tgstation_schema.sql file into a mariadb database, I receive the following error:

`CREATE TABLE `feedback` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `datetime` datetime NOT NULL,
  `round_id` int(11) unsigned NOT NULL,
  `key_name` varchar(32) NOT NULL,
  `key_type` enum('text', 'amount', 'tally', 'nested tally', 'associative') NOT NULL,
  `version` tinyint(3) unsigned NOT NULL,
  `json` json NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
/* SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1' at line 8 */
/* Affected rows: 0  Found rows: 0  Warnings: 0  Duration for 43 of 126 queries: 2.995 sec. */`

**Comment by Jordie0608** [comment]
Your MariaDB version is too old, json support was added in version 10.2.
