### ISSUE TITLE
A thing about vr bossrush

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#43788]
## Round ID: 107417

Final room of bossrush has a shambling miner mob in it, and its also affected by pacifism. good thing it can be solved by book of firebolt there (also firebolt is not affected by pacifism)

## Reproduction:

step 1-beat bossrush
step 2-get into final room
step 3- get constantly bashed by a mob and cant retaliate becausue pacifism (atleast untill you learn firebolt)

**Comment by ATH1909** [comment]
@Whoneedspacee

**Comment by Whoneedspacee** [comment]
whoops

**Comment by adamkad1** [comment]
on a side note, i dont like not being able to suicide in syndicate vr, you die when you leave it anyway, and that way you cant do those BISNASTY ROCKET JUMPS
