### ISSUE TITLE
Any beverage in soda cans gives you mood buff.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#43797]
Reproduction:
1) buy a drink from vending machine, I used star-kist as example.
2) open it and put it into the chem dispenser.
3) empty it there, mix any chemical you want inside that soda can.
4) drink the healing chemical alongside getting positive mood buff.
![333](https://user-images.githubusercontent.com/34580767/57069911-96cbf800-6cde-11e9-95bf-99820d2d0cf2.png)

**Comment by ATH1909** [comment]
Put spray tan in it and laugh as your character reacts with "That tasted horrible!" (or something like that) in the text log whenever you sip from your can of spray tan, yet still gets a positive mood buff from the sipping.

**Comment by 81Denton** [comment]
What if they just really like that soda can

**Comment by ATH1909** [comment]
> What if they just really like that soda can

Family heirloom soda cans when

**Comment by blessedmulligan** [comment]
might fix it tomorrow but I'm tired. the issue seems to be that soda cans are hardcoded with a food type regardless of contents; a starkist can is always SUGAR,FRUIT, and JUNKFOOD regardless of what you fill it with. 


> 
> 
> What if they just really like that soda can

this is correct

**Comment by OverlyGeneric** [comment]
I suppose this means I can have a smile on my face while drinking cyanide out of Starkist can.

**Comment by ExcessiveUseOfCobblestone** [comment]
handwave it by calling it brand loyalty.

**Comment by nemvar** [comment]
What cobby said.

**Comment by PKPenguin321** [comment]
I think that was a joke dude
