### ISSUE TITLE
Welcome screen text is too dark

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/tgstation#43809]
## Round ID: 107554

![image](https://user-images.githubusercontent.com/701959/57158036-bb949e00-6db8-11e9-826f-5e084066aea7.png)
The background is really dark, it makes the text hard to read

## Reproduction:
Just login and watch the chat

**Comment by Jalleo** [comment]
@Kmc2000

**Comment by actioninja** [comment]
This is a serverside issue.

**Comment by actioninja** [comment]
@excessiveuseofcobblestone fixed
