### ISSUE TITLE
the full medkits crates are missing (the not small version)

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#43808]
you can only buy the small crate types

**Comment by zxaber** [comment]
This was intentionally changed because I didn't really see much reason in having both; you can just buy three single medkits. I didn't add the extra cost per unit like I did with the single orders for guns

**Comment by Tlaltecuhtli** [comment]
if i want to buy mass medkits for the station now i have to click on a laggy interface 3x more 
single crates are already weird and bad as if someone is buying a locked single crate now everything else ordered gets locked in it

**Comment by ExcessiveUseOfCobblestone** [comment]
If the UI is laggy and it doesn't already exist make an issue for it.
