### ISSUE TITLE
Revenants can be hit by ranged weaponry while intangible.

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#43804]
Round ID:107506

## Testmerges:
#43682: '*dab' by actioninja at commit e8ed4cf46d

## Reproduction: Be revenant, get hit by shotgun bullets. Take damage while intangible. Get hit by lasers, take damage while intangible.

You can literally kill a revenant while it's in its unkillable mode.

**Comment by HomocidlePancakes** [comment]
Reproduction my ass.
Reproduction (fixed): Stand on the same tile as a human/mob. Have someone stand next to them and shoot them point blank with help intent. You will get hit instead.
Also I think it doesn’t actually damage you

**Comment by Shadowflame909** [comment]
It does. Also Im pretty sure I was on the same tile as a bean bag slug or laser. But not the person shooting it.

**Comment by Ratvar** [comment]
It does not damage you, merely absorbs shots, tested with blocking emmiter laser in singullo containment

**Comment by Shadowflame909** [comment]
I'll try it again. But I'm certain bean bag slugs brought my points down from 90 to 85 on Sybil.

**Comment by ATH1909** [comment]
Were they meteor slugs or something, by any chance?
