### ISSUE TITLE
Hivemind with implant

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#43813]
## Reproduction:
Not sure how to reproduce, this might need some log digging. I was a hivemind that round, after I went one mind a security man made me aware I had a mindshield implant. I was a lawyer, noone had attempted to mindshield me. There was talk about mindshield nanites, potential cause. I also accepted a devils deal for knowledge.

**Comment by davethwave** [comment]
It was probably nanites then, if you are a hiveming or revhead, you can fake having a implant via nanites. With how it works I wouldn't know if could consider it a bug or not. Best to ask the person who made the code.

**Comment by ATH1909** [comment]
```
/datum/nanite_program/mindshield
	name = "Mental Barrier"
	desc = "The nanites form a protective membrane around the host's brain, shielding them from abnormal influences while they're active."
	use_rate = 0.40
	rogue_types = list(/datum/nanite_program/brain_decay, /datum/nanite_program/brain_misfire)

/datum/nanite_program/mindshield/enable_passive_effect()
	. = ..()
	if(!host_mob.mind.has_antag_datum(/datum/antagonist/rev) && !is_hivemember(host_mob)) //won't work if on a rev, to avoid having implanted revs. same applies for hivemind members.
		ADD_TRAIT(host_mob, TRAIT_MINDSHIELD, "nanites")
		host_mob.sec_hud_set_implants()

/datum/nanite_program/mindshield/disable_passive_effect()
	. = ..()
	REMOVE_TRAIT(host_mob, TRAIT_MINDSHIELD, "nanites")
	host_mob.sec_hud_set_implants()
```
This definitely isn't intentional.

**Comment by adamkad1** [comment]
Well the problem with this is, nanites dont block any hivemind power. you can be assimilated throught them, you can be one minded, and all other things. im ssure they should block hivemind powers

**Comment by py01** [comment]
the mindshield nanites program isnt supposed to be able to activate if the host is a vessel or hivemind.

**Comment by adamkad1** [comment]
Well, either it doesnt work if you are implanted with actuall mindshield or it just doesnt work at all

**Comment by ATH1909** [comment]
> Well, either it doesnt work if you are implanted with actuall mindshield or it just doesnt work at all

It might be because the mindshield program only adds the mindshield trait when it's turned on (not every tick). Turning your mindshield program off and on again should give you a new mindshield.

**Comment by kriskog** [comment]
Note that I didnt actually go get nanites this round, nor did I do anything in relation to nanites. If this was caused by nanites, someone else spread them and activated them. I did confirm I had a mindshield according to the hud.

**Comment by vuonojenmustaturska** [comment]
the issue is that one mind is a different antag datum not checked by `is_hivemember()`, and revheads are a subtype of the rev member datum not checked by plain `has_antag_datum()`

**Comment by kriskog** [comment]
That might be part of it. I cant verify this, but I believe I might have had the implant before one minding. I was left alone for probably half an hour while they were agressively implanting the rest of the crew. Then again, in that case I'd expect the other hiveminds to have them too. Hm.
