### ISSUE TITLE
How do the different zlevels work?

### ISSUE THREAD

**Issue by Supercon22** [tgstation/tgstation#43819]
Hello

I'm trying to host my own server but I'm not sure what maps I need to complie - no matter what I try, I get some sort of error. For example, centcom doesn't exist, so I tick it in the compile and I can't call the emergency shuttle. Another example is I enable lavaland, but nothing spawns in it correctly. Could someone help me out?

**Comment by optimumtact** [comment]
You should join the tgstation discord https://tgstation13.org/phpBB/viewforum.php?f=60

or the coderbus discord https://discord.gg/Vh8TJp9 to get specific help, the issue tracker is for specific bug reports.
