### ISSUE TITLE
"You shouldn't have this spell" when clicking on gauntlet echo as ghost

### ISSUE THREAD

**Issue by Lobachevskiy** [tgstation/tgstation#43814]
Issue reported from  Round ID: 107632 (actually a number of rounds prior to this, but on the same day) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1467

> You shouldn't have this spell! Something's wrong.
> 
> Now orbiting the gauntlet echo.
> 
> You shouldn't have this spell! Something's wrong.

Happened when I clicked on gauntlet echo of juggernaut. I was the ghost of a wraith and had examine on click enabled.

**Comment by HomocidlePancakes** [comment]
Ghosts shouldn’t be able to see action buttons. This is weird

**Comment by Lobachevskiy** [comment]
There was no action button. I just clicked on the gauntlet echo that was on the map.

**Comment by tralezab** [comment]
https://github.com/tgstation/tgstation/blob/b2c3d11b9cecdb13a696b65981ffa8b3ca88af1d/code/modules/spells/spell_types/construct_spells.dm#L303-L309

the projectile is a spell itself. by double clicking to orbit, they are trying to cast or something like that.

**Comment by Lobachevskiy** [comment]
Wasn't just when I was double clicking to orbit, even single click worked (like I mentioned I had examine on click enabled).

**Comment by tralezab** [comment]
Well yeah, you double clicked to orbit in the opening post and got two cast messages, so any click is trying to cast

**Comment by ATH1909** [comment]
*golfclap*

**Comment by PKPenguin321** [comment]
>the projectile is a spell itself

holy shit lol, i'm shocked that this even worked in the first place

**Comment by tralezab** [comment]
i wonder if you are a wizard and you clicked on the projectile if you would take damage

**Comment by ATH1909** [comment]
> i wonder if you are a wizard and you clicked on the projectile if you would take damage

What if another juggernaut clicked on it? What if the juggernaut that cast the spell clicked on it?
