### ISSUE TITLE
changing det gun sprite is broke

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#43829]
http://take.ms/DF8tba

**Comment by kopoba** [comment]
works fine for me 
https://i.imgur.com/kJHwT06.png
https://i.imgur.com/IhfOxxF.png

**Comment by optimumtact** [comment]
no reproduction

**Comment by Tharcoonvagh** [comment]
Happened to me too with roundend report nook items and some examines too
