### ISSUE TITLE
Virus addaption menu not opening randoml;y

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#43830]
Round ID: 107757

As a sentient virus I was attempting to open my virus addaption menu for some sweet upgrades but it refused to open, I tried logging in and out, opening/closing byond as well as having an admin take over the disease to see if they could do anything. Unfortunately none of these fixed the issue.

**Comment by optimumtact** [comment]
This is unlikely to be resolved without reproduction steps, guessing a byond issue

**Comment by kriskog** [comment]
Lots of runtimes here, seems one of the mobs were nulled but still tried to be listed in the adaptation window. 
https://tgstation13.org/parsed-logs/sybil/data/logs/2019/05/06/round-107757/runtime.txt

**Comment by AnonymousNow** [comment]
Necroing this, as it just happened to me.

**Comment by adamkad1** [comment]
Yeah me too. I thinnk when it happens, the disease becomes unspreadable too

**Comment by Sealed101** [comment]
sentient disease has been retired as of #83453
