### ISSUE TITLE
Tinfoil hats can be removed by yourself

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#43839]
Title, tinfoil hats can be removed by click-dragging them into your hands.

### Reproduction:

- Get tinfoil hat
- Wear it
- Click on the tinfoil hat in your inventory and drag it into your hand slot
- The hat is now in your hands and you are no longer traumatized by living in a giant conspiracy

By default clicking the tinfoil hat in an attempt to remove it will deny your attempt and give you a message about not wanting to let go of the conspiracy world, forcing you to seek the help of someone else to remove it or find some other unconventional method like acid to get rid of it.

Can be used to escape security's attempt at fear mongering you into submission when forcing you to wear these.
(Unless you're restrained, in which case "Hey look a CENTCOM inspector")

Similar to #36318 and removing straight jackets.

> Batons and tasers may shock my nerves but words will never-
<b>CMO Announcement: Johnson Inspection Day</b>
*paniced screaming*

**Comment by Garen7** [comment]
probably affects the leg cuffs too
