### ISSUE TITLE
Disgruntled entrepreneur strikes back, stealing billions of credits worth of spacecoin

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#43842]
Title, Protocal-17 CRAB phones can be bought in the Syndicate VR trainer uplinks.
## Round ID: 107835

![MONEY](https://user-images.githubusercontent.com/17460297/57281637-3cc18e80-7060-11e9-8dd2-2e64e5e4a1f1.PNG)
![DUMPEET](https://user-images.githubusercontent.com/17460297/57286281-cc1f6f80-7069-11e9-88b0-a2eb0c7292cc.PNG)
## Reproduction:

- Go to syndicate trainer in virtual reality
- Open uplink and view devices menu
- > "Fudge what is this doing here?"
- Buy CRAB phones, cause repeated spacecoin market crashes until the system-wide market collapses
...
- Ruin another timeline as galactic civilization spirals into economic chaos
- We already know how this vicious cycle works
- You didn't listen
- You could have avoided this
- It's already too late
- it's happening
- Now we have to start over again.
...
[No.
FUN.
Allowed.](https://tgstation13.org/wiki/Stop)

Technically just another issue to be closed if #43832 is merged, though I don't enjoy providing another reason to have VR removed.

> LOOK SIR, FREE CRABS!

**Comment by Tlaltecuhtli** [comment]
is it supposed to stack tho?

**Comment by Jalleo** [comment]
Probably not.

**Comment by Repukan** [comment]
Funds are safu

**Comment by GravitronBlue** [comment]
Issue should be resolved with #43854 having been merged.
