### ISSUE TITLE
you can PDA people as a person that joined VR as a ghost

### ISSUE THREAD

**Issue by loserXD** [tgstation/tgstation#43852]
## Round ID: 
N/A

## Testmerges:
N/A

## Reproduction:
use the VR hub ghost spawner, goto the megafauna arena and use your PDA to message people on station

**Comment by Fikou** [comment]
pretty sure the pda messages dont get send or at least dont get notificated by other people, ive never seen anyone respond

**Comment by Whoneedspacee** [comment]
it probably doesn’t make it to the station since there’s no comms to handle it

anyways this is no different than any ghost role getting their hands on a pda so i don’t think it matters too much
