### ISSUE TITLE
Chem implant/implants do not work at all and are bugged out.

### ISSUE THREAD

**Issue by Bondle** [tgstation/tgstation#43861]
Chem implants do not work at all, specifically ones manufactured by the protolathe. There is no way to activate them. I tried dying, using the *deathgasp emote, and looking for the nonexistent button.

## Reproduction:

1. Create a 'Remote chemical' implant case and an implanter.
2. Inject chemicals into the implant case and then use the implanter to remove the implant from the case.
3. Inject the chem implant to anyone/yourself.
***Note that people do show up with a blue button on sechuds which shows that they're implanted.***
4. Watch as you can not activate the implant in any form or way. The button that is supposed to show up does not show up, you can not *deathgasp to activate it and even when you die it does not activate.

**Comment by Bondle** [comment]
You can activate it via the prisoner management console, but that isn't sufficient enough,

**Comment by YPOQ** [comment]
Self-activation was intentionally disabled for balance #36021
