### ISSUE TITLE
Jack olsen killed me with no reason

### ISSUE THREAD

**Issue by smilo98** [tgstation/tgstation#43889]
Issue reported from  Round ID: 908 (Fulpstation)

Reporting client version: 512.1466

**Comment by carshalash** [comment]
thanks

**Comment by HomocidlePancakes** [comment]
Gib Jack Olsen on spawn

**Comment by tralezab** [comment]
Fuck you Jack you're a real peice of piss for killing my man

Someone fix this issue before I take it into my own hands

**Comment by AnturK** [comment]
:thinking:
