### ISSUE TITLE
Multiple sentient disease issue

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#43892]
## Round ID: 107999

There was a sentient virus that spawned 30 or so minutes prior to me that had already been cured by quite a few people, those that had been cured by the prior virus were completely immune to me despite very different cures.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/99072e47e0b73b39276aaa26a08ecc69522758d9/code/modules/antagonists/disease/disease_disease.dm#L29-L34

weird

**Comment by adamkad1** [comment]
Sentient disease cure doesnt seem to change when you change symptoms, and sometimes you just cant open the adaptation menu

**Comment by 4dplanner** [comment]
lol

**Comment by adamkad1** [comment]
also, it would be cool if the disease could communicate with the infectees or something lul
