### ISSUE TITLE
Job preferences not working correctly

### ISSUE THREAD

**Issue by erwgd** [tgstation/tgstation#43901]
High jobs are set to never, while low prefs take priority over medium prefs.

## Round ID:

1. 108020

## Reproduction:

Have one job set to high. Save setup, click to other character and click back. Your high job is reset to never.

Additionally, while testing on localhost, low priority jobs take priority over medium jobs, so long as the latter isn't a head role.

**Comment by RaveRadbury** [comment]
Ah, I was experiencing this locally as well.
