### ISSUE TITLE
Certain worn items seem to burn much quicker now

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#43907]
Radios and glasses lose integrity rapidly while the wearer is on fire. To my knowledge, these items were not easily burnable before. This may have been an unintended side effect of something, or I'm just dumb and didn't notice them burning before.

**Comment by HomocidlePancakes** [comment]
Most of hats, shoes, masks and gloves always burned in fire. Never remember headsets burning though

**Comment by optimumtact** [comment]
This doesn't really seem like a bug honestly and how would you even prove that their integrity rate changed?

If you think it's a balance issue you could make a forum thread or a PR to change their integrity.
