### ISSUE TITLE
Exploding in the virtual reality ghost spawner

### ISSUE THREAD

**Issue by Amalvi** [tgstation/tgstation#43906]
Issue reported from  Round ID: 108038 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1448

So if you enter the virtual reality ghost spawner and go to the syndicate portal, then try to quit via the "Portal Recall" option you instead explode in gibs with no body to go back to. You can just use the spawner again, but I suppose this is not intended

**Comment by ATH1909** [comment]
No, it is intended- it's to keep you from smuggling out syndicate gear into the hub with a storage implant or the like.

You explode when trying to escape the syndicate simulation using a briefcase launchpad now as well.

**Comment by Tlaltecuhtli** [comment]
why not make the storage implant restricted instead which makes more sense

**Comment by optimumtact** [comment]
Not a bug, per ATH comment
