### ISSUE TITLE
Spiritual doesn't proc mood event

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#43900]
## Round ID:
Tested locally

## Reproduction:
  - Start as human with spiritual perk
  - Ghost and spawn in a chaplain
  - Return to your original human
  - Notice that the message doesn't show up in moodlets
  - Go into the code and edit out all the ifs for the event to proc
  - relgiously_comforted mood event never procs

I'm trying to rework this quirk anyway but I am still having difficulty getting this to proc, so any insight would be appreciated.

**Comment by optimumtact** [comment]
https://github.com/tgstation/tgstation/blob/8189c579b65ef83220748e5ec19bed6c4afc00fe/code/datums/traits/good.dm#L148-L157

**Comment by RaveRadbury** [comment]
Looks like it takes 2 accounts to test, never mind.
