### ISSUE TITLE
Disk Toaster/Compartmentalizer Disappears when used

### ISSUE THREAD

**Issue by cedarbridge** [tgstation/tgstation#43910]
## Round ID:
108074
## Testmerges:
#43148: '[s]Temp workaround for admins matching stickybans because of a byond bug.' by MrStonedOne at commit f34e61e42d
#43777: '[TESTMERGE READY] Gehennites [Moths Still In Version]' by Militaires at commit df5a659305

## Reproduction:
Upon adding a disk to the storage, the machine switches from disktoaster to disktoaster1 icon_state which does not exist.  This causes the toaster to visibly vanish from the world while remaining interactive via alt-click.

**Comment by kriskog** [comment]
#43807
@Mickyan This is a version of the smart fridge

**Comment by Mickyan** [comment]
shoot.

**Comment by Mickyan** [comment]
appreciate the detailed report by the way
