### ISSUE TITLE
AI sat constantly spawning 3 extra braindead ais

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#43911]
![image](https://user-images.githubusercontent.com/16896032/57516295-cec6e100-7357-11e9-9515-6dd3b4a5a937.png)

This is fucking obnoxious and makes synching borgs a pain in the ass

**Comment by Tlaltecuhtli** [comment]
which map is that

**Comment by carshalash** [comment]
Box, have witnessed it happen on meta too though.

**Comment by carshalash** [comment]
![image](https://user-images.githubusercontent.com/16896032/57523648-e064b480-7368-11e9-9887-78a643ee3c3e.png)
So now we also have this

**Comment by carshalash** [comment]
![image](https://user-images.githubusercontent.com/16896032/57523739-2588e680-7369-11e9-8851-f163f9207f99.png)
This is how the sat starts out each round, this is not normal.

**Comment by carshalash** [comment]
And on top of all of this fucking mess, the robotics control console is absolutely fucked to the point of nobody being able to view it.

This seems to be only happening on sybil for only god knows what reason.

**Comment by tralezab** [comment]
Testmerges?? Round id?? Hello?

**Comment by YPOQ** [comment]
From what I can tell this is because the character setup previews for silicons are spawning in the world.

**Comment by RaveRadbury** [comment]
Isn't triple AI an admin setting?
