### ISSUE TITLE
Rastacap is invisible

### ISSUE THREAD

**Issue by Farquaar** [tgstation/tgstation#43927]
## Round ID:
108207

## Reproduction:
1. Go to clothesmate or chaplain vendor.
2. Buy rastacap.
3. See invisibility.

I'll fix this ASAP

**Comment by Krysonism** [comment]
Speedfix please

I need rasta botanist in my life

**Comment by Farquaar** [comment]
Opened a PR that fixes the issue. It was a simple fix, should hopefully get merged soon.
