### ISSUE TITLE
Cannot seem to make nitryl

### ISSUE THREAD

**Issue by Daxxed** [tgstation/tgstation#43926]
## Reproduction:

Reactions.dm tells me this is what is needed for nitryl :
	min_requirements = list(
		/datum/gas/oxygen = 20,
		/datum/gas/nitrogen = 20,
		/datum/gas/nitrous_oxide = 5,
		"TEMP" = FIRE_MINIMUM_TEMPERATURE_TO_EXIST*60 ( 22000K )

When trying this, all n2o will decompose within seconds and there wont be enough catalyst (5 moles of n2o) to continue the nitryl formation.
I even tried adding lots of n2o ( 1000s of moles ) but it will all decompose before any significant amount of nitryl is made.

#43560 Is the cause
The PR said it was changed to consider fusion and nitryl requirements, but nitryl was changed between the creation and merge of this PR.
An easy fix would be changing the heat limit for n2o decomposition, or maybe a better solution would be that the decomposition always leaves atleast 5 moles of n2o.

I know you could still make nitryl with fusion levels of heat ( atleast 100000K afaik ), but I don't think a medium rarity gas with little benefits should require fusion to produce.

The nitryl req change was #43362

**Comment by optimumtact** [comment]
this isn't a bug so much as an oversight or unintended mistake, so please use the forum to discuss it instead.
