### ISSUE TITLE
Amber ERT's can C4 Centcom vault room to get pulse guns/mateba

### ISSUE THREAD

**Issue by Shapsy** [tgstation/tgstation#43937]
## Round ID:
108320

## Reproduction:

![image](https://user-images.githubusercontent.com/3589655/57577105-d52f8880-743d-11e9-90f1-d919b929d30a.png)

Amber ERT's get C4 which allows them to enter the Administrative Office room above their spawn gear room, then blast their way through the locked Vault door and get free shit like a Pulse Carbine, 3 packs of X4, and a Mateba autorevolver. ERT's probably shouldn't be encouraged to blast their way through centcom for loot, and pulse guns are kept to Red alert for a reason

**Comment by HomocidlePancakes** [comment]
And thats why admins drop pods on ERTs that do that.

**Comment by Tlaltecuhtli** [comment]
admin issue

**Comment by JusticeGoat** [comment]
Its a issue with admins not watching the ert leave command.

**Comment by Shapsy** [comment]
There's no indication that this is even a thing that admins need to watch for, usually I brief the team I spawn then ghost out once they're shuffling onto the shuttle to check on the situation I just sent them in to solve. I only was made aware of this because another admin chided me for spawning an Amber ERT during a blob, since pulse guns were too much. I told them Amber specifically didn't have pulse (and in fact the ERT had not looted it this time), they showed me this method. Nothing's lost by making the door invuln or moving the gear somewhere else, and consistency is gained
