### ISSUE TITLE
Tritium production oddity--is the supersaturation value as intended?

### ISSUE THREAD

**Issue by Putnam3145** [tgstation/tgstation#43949]
https://github.com/tgstation/tgstation/blob/2923d645ad4b5a75380441e6c99737bd0f569182/code/__DEFINES/reactions.dm#L23

Here one can see the supersaturation value is set to 96. This seems reasonable, the mix needs to be at least 96% oxygen, guides for tritium production assume this... except, no, that's not at all what's happening:

https://github.com/tgstation/tgstation/blob/a277e6db656fbebbba2bafe321e15652b836c2d3/code/modules/atmospherics/gasmixtures/reactions.dm#L213

It's not 96% oxygen, it's 96x as much oxygen as plasma. In other words, if you have a mix of nothing but oxygen and plasma, you need at least 98.97% (96/97) of your mix to be oxygen to make tritium. Of course, I could be simply misunderstanding the original intention, which isn't written anywhere in the commit that first added it (https://github.com/tgstation/tgstation/commit/43edaedc291da8d5ab41ea195faf8a580e41447e), but I figure oddities should be noted.

**Comment by Whoneedspacee** [comment]
guides for tritium production don't assume this (at least in experienced circles). it's been known for a long while that this is how it happens, it's just that 97/3 and stuff like that is fine because very quickly the rates will decrease due to the temperature increase.

it's really not anything worth complaining over and i'm not sure how you can tell if it's a bug or not.

**Comment by Putnam3145** [comment]
I can't, that's why I didn't label it as a bug.

If it's known and intended I'll probably just close this.

**Comment by Whoneedspacee** [comment]
If you want to think about it in a way that makes sense, gasses probably care more about how much of another gas there is compared to them, rather than the percentages.

**Comment by as334** [comment]
Intended behavior but I can see how it would appear confusing. I'll try to remember to add a comment explaining that it's a ratio next time I touch the defines stuff.
