### ISSUE TITLE
Fugitives is a mess

### ISSUE THREAD

**Issue by Jimmius** [tgstation/tgstation#43945]
## Reproduction: Spawn Fugitives and enjoy the ride.

Fugitives can spawn in space, where they die a slow and hilarious death as all the airlocks are closed to them (Check 108294). 
The hunters never spawn on their own even after an hour of waiting.
The capture pod is invisible. 

There's probably a few more minor issues too (such as Waldo being the only fugitive that spawns), but these are the main ones that make the event literally unplayable.

**Comment by optimumtact** [comment]
@tralezab

**Comment by tralezab** [comment]
all of these are fixed in my pr #43941

**Comment by Jimmius** [comment]
sweet, it's a cool event and it's been a shame that it's not worked out so far.

**Comment by tralezab** [comment]
I'm real sorry bout that, I couldn't test some of the most important parts.
