### ISSUE TITLE
Sleeping Carp got scuffed by disarm rework

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#43956]
Sleeping carp has two combos that utilize disarm (or push idc) intent - wrist wrench and elbow drop. Thanks to the disarm rework you will push your targets away from you while trying to execute said combos. This makes them unreliable to use, especially the elbow drop because of how long it is.

Having carp should change the functionality of disarm intent. For example give it a small slow comparable to what push has along with some minor damage, or maybe give it the actual disarm back.

**Comment by actioninja** [comment]
This wasn't unintentional. How good of a change it was is debatable, but I did this on purpose.

**Comment by HomocidlePancakes** [comment]
Pretty sure you said martial arts wouldn’t be affected by the rework.

**Comment by HomocidlePancakes** [comment]
Ok nevermind, you just said “it should be still good” and I understood it as “martial arts won’t be affected”. The issue still stands though.

**Comment by py01** [comment]
I don't believe it's too big of an issue, if you simultaneously press disarm and a movement key you keep with them and keep your mouse cursor on them.

**Comment by HomocidlePancakes** [comment]
What ping?
