### ISSUE TITLE
A duplicate pAI is formed when they change into a different form while being a hat

### ISSUE THREAD

**Issue by PhillipSF** [tgstation/tgstation#43972]

**Comment by RaveRadbury** [comment]
I've noticed this, too. There's also a problem with going into holochassis from inventory that leaves a ghostly pAI

**Comment by timothymtorres** [comment]
I tested this today on local and it appears to have been fixed at some point in the last two years.

**Comment by timothymtorres** [comment]
@RaveRadbury @PhillipSF if either of you have this bug appear again just ping me and I will reopen this.
