### ISSUE TITLE
Using cursed heart resulted in immediate death

### ISSUE THREAD

**Issue by gamefreak2998** [tgstation/tgstation#43977]
Round ID: 108441

I used the cursed heart and it resulted in me dying  immediately, it could of happened potentially due to a lag spike and me missing some seconds as a result but I didn't even have the chance to pump it before death came for me

**Comment by HomocidlePancakes** [comment]
What race were you playing?

**Comment by gamefreak2998** [comment]
Human I believe, I got the chance to try it again a few rounds later and it worked fine that time so I think it was due to the lag spike that occurred at the time I got it on myself it seems
