### ISSUE TITLE
stasis units can leave someone sleeping permanently

### ISSUE THREAD

**Issue by loserXD** [tgstation/tgstation#43974]
to reproduce, put zombie powder into someone and buckle them to a stasis unit

they are now sleeping forever

**Comment by Barhandar** [comment]
intended, feature

**Comment by 81Denton** [comment]
Sounds like a design flaw to me, even N2O has a short period where people wake up and aren't just taken out of the round completely

**Comment by AzureWildfire** [comment]
I mean not forever, just ghost, as you can't suicide and your suit sensors show you as healthy

**Comment by ExcessiveUseOfCobblestone** [comment]
If you see a random maint sleeper and a dead person on it don't you think that should raise some eyebrows lol

**Comment by ExcessiveUseOfCobblestone** [comment]
Also look we didn't remove sleepers, they're just do their job described in their name better :^)
