### ISSUE TITLE
Cursed revolver wasn't fixed.

### ISSUE THREAD

**Issue by gamefreak2998** [tgstation/tgstation#43976]
The previous bug with the russian revolver wasn't fixed on the cursed variant it seems.

**Comment by optimumtact** [comment]
You didn't explain what the bug is

**Comment by necromanceranne** [comment]
I'm pretty sure it's the offhand dual-wielding bug that allows you to fire infinite .357 bullets.

**Comment by gamefreak2998** [comment]
Nah its the bug that doesnt allow you to do anything with the gun really. Here's what happens. You try to use it, it asks you to spin, you spin and fire and the first click is always a dud unless it's fully loaded then it will ask you to spin it again thus repeating the bug.
