### ISSUE TITLE
Cursed Katana no longer 'cursed'

### ISSUE THREAD

**Issue by gamefreak2998** [tgstation/tgstation#43982]
The cursed katana that comes from the lavaland loot seems to act like a normal katana that is unsheathable. I can drop it like any normal item, throw it or stuff it in a bag of holding. Not sure if this chance was intentional or if this is just a bug that was introduced with one of the patches.

**Comment by 4dplanner** [comment]
Intentional, it's just meant to not go in the back/belt item slots

**Comment by Fikou** [comment]
> Intentional, it's just meant to not go in the back/belt item slots

cursed katana is supposed to be like every other cursed item, undroppable i thought

**Comment by gamefreak2998** [comment]
Yeah I figured the inability to sheath was intentional, but unless there is a normal katana in the tendril loot tables the 6 or so I got over the weeks have all been droppable/throwable

**Comment by WJohn** [comment]
Last I checked, the cursed katana is *only* unstoppable if assigned by a wizard.

**Comment by tralezab** [comment]
But why?

**Comment by gamefreak2998** [comment]
Ahhhhh, that makes some sense I guess? I guess that confused me given how magic inflicted curses work

**Comment by optimumtact** [comment]
The curse of this katana is you can't put it on yourself, not that you can't drop it.

it has no slot flags defined.
