### ISSUE TITLE
pAIs can't toggle radio channels

### ISSUE THREAD

**Issue by literallytrash0** [tgstation/tgstation#43981]
## Round ID:
108469

## Testmerges:
none

## Reproduction:
as a pAI, take the encryption keys module. Get someone to give you a key (captain's key is what I discovered this on) and then go to radio config to try and turn on the channels that aren't on by default. they aren't there.

**Comment by RaveRadbury** [comment]
Not quite sure why this doesn't work, I'll do some testing.

**Comment by DingleFlop** [comment]
Via testing I can't actually even access an interface that hints that a radio key has in fact been inserted.
The radio button brings up an entirely greyed out interface:
![image](https://user-images.githubusercontent.com/24946273/58528389-26a07d00-818b-11e9-88eb-5dbdea5edb01.png)

**Comment by DingleFlop** [comment]
I am not familiar enough with tgui to know why this might be happening. I figure it may a check that should be updated in the pAI version of the radio to keep the interface intractable and up to date.

**Comment by RaveRadbury** [comment]
The options are greyed out while you are in card form.

**Comment by DingleFlop** [comment]
@RaveRadbury This is actually a more complicated issue to track down. I switch between LLA/tg codebases often now, so this may be a weird thing but....
In live rounds, the majority of the time I am able to use my radio properly. When I boot up the codebase in a Dev environment though, it's almost always greyed out like this. I do not know how to track this one down, really... Maybe it has to do with how I am spawning the pAIs? (Spawning the card and assigning my ckey to the mob's variable, or assuming direct control on the card's mob)
