### ISSUE TITLE
AI controlled mech + 0 gravity = you are fucked

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#43985]
For some reason AI has to "exit" the mech instead of disconecting instantly. If you are in zero gravity you will end up exiting it and having the exit interrupted over and over. If you accidently space yourself while in a mech, you will end up stuck in it.

**Comment by PKPenguin321** [comment]
Don't space yourself then

**Comment by zxaber** [comment]
Why is there a timer on AIs "exiting" mechs?

**Comment by Barhandar** [comment]
Because a memetimer was added to exiting mechs for regular people and the PR maker presumably didn't think that AIs can control them too.

**Comment by YakumoChen** [comment]
Any gun on the mech can push you back via newtonian physics if you have at least one gun

**Comment by PKPenguin321** [comment]
"I get spaced when I walk into space"
"It hurts when I touch this hot stove"

**Comment by HomocidlePancakes** [comment]
1)Indeed it does hurt. 
2)It was an engineering FF with an RCD

**Comment by optimumtact** [comment]
This isn't really a bug, although I could still see someone changing it, but AI's are subject to very similar restrictions to people about entering/exiting mechs
