### ISSUE TITLE
Alt-clicking sleepers

### ISSUE THREAD

**Issue by nemvar** [tgstation/tgstation#43998]
## Round ID:

108530 Terry

## Testmerges:

None

## Reproduction:

Alt-clicking a sleeper will open/close it, regardless of distance or if the user is sleeping.

**Comment by HomocidlePancakes** [comment]
Sethtiders reporting muh secret robustin’ techniques :(

**Comment by nemvar** [comment]
How dare you assume I'm a ssethtider? I'm OFFENDED

**Comment by optimumtact** [comment]
Phew just as well we removed them

**Comment by kopoba** [comment]
Same with Lifeform Stasis Unit
