### ISSUE TITLE
Internal Antenna stops radio channel use

### ISSUE THREAD

**Issue by Michael-Ashfield** [tgstation/tgstation#43990]
## Round ID: 108493

Internal Antenna mutation seems to prevent the use of chat in any channel, regardless of encryption keys on any working worn radio.

What happened:
I died as HoP, was cloned and got Internal Antenna by chance. When I tried to tell command what happened to me, using the normal ".c" command channel, it made me speak in common. this was tested in all channels, on a new radio, after re-logging and removing my encryption key and putting it back in, before I deduced it was my internal antenna preventing me.
I could hear in command channel when the captain spoke, but I couldn't reply in command or any other channel.

To reproduce:
1. Get a radio with a channel key in it
2. Get internal antenna
3. try to speak in the channel
4. See that you speak in common

**Comment by Barhandar** [comment]
Same issue as syndie radio implant.
