### ISSUE TITLE
Chem Dispenser/Master windows are stuck to the bottom of the screen when moving.

### ISSUE THREAD

**Issue by stylemistake** [tgstation/tgstation#44038]
Not sure how to properly reproduce this, because this might be system configuration related, but here is a video showing it.

https://www.youtube.com/watch?v=8aaPYPmaJY4

## Reproduction:

- Use Windows 10
- Use Terry EU server
- Be chemist or have access to Chem Dispenser/Master 3000
- Open windows and try moving them

Windows show up normally, but when trying to move them, they get stuck to the bottom of the screen. Window is interactable, but it is very annoying.

**Comment by DaxDupont** [comment]
Sounds like a byond issue

**Comment by 81Denton** [comment]
I've had the same issue until I disabled fancy TGUI in the settings, but I can't say what the cause is.

**Comment by stylemistake** [comment]
Yes, can confirm, `tgui` with "No Frills" works great.

![image](https://user-images.githubusercontent.com/1516236/57981585-cfd7cc80-7a41-11e9-8cb8-c8daf6609027.png)

**Comment by AnturK** [comment]
Probably to do with the weird dragging/scaling libraries tgui uses.
