### ISSUE TITLE
Sometimes graffiti letters appear drastically beneath where they are drawn

### ISSUE THREAD

**Issue by harmonyn** [tgstation/tgstation#44031]
Hard to explain without a screenshot but basically it appears like:

```
M E S S...G E 
........A.......
```

No, it isn't an issue with the mouse, it happens too often for that and always in the same way. I haven't figured out a pattern to it.

**Comment by Mickyan** [comment]
could it be #38770

doesn't just apply to existing graffiti either, if you click on any object that isn't a turf (i.e. vents) it throws the pixel offset out the window

**Comment by timothymtorres** [comment]
I remember this happening a while ago, but I haven't seen it happen in the last year-ish.  I think whatever was causing this has been fixed since it seems to have gone away.
