### ISSUE TITLE
"time of death" memory doesnt make sense

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#44033]
![](https://api.monosnap.com/file/download?id=TIk5q6sNyIxqBmil06kksz4GDcQYvd)

**Comment by HomocidlePancakes** [comment]
Seems to show station time instead of round time for some reason

**Comment by 81Denton** [comment]
Yeah, currently it's station_time_timestamp() instead of gameTimestamp()

**Comment by kingofkosmos** [comment]
Should this be labeled as Good First PR and leave it for someone new?

**Comment by ExcessiveUseOfCobblestone** [comment]
> 54 minutes pass
> supposedly the guy died almost 2 hours ago

what lol
