### ISSUE TITLE
Between the Sheets Not Healing

### ISSUE THREAD

**Issue by BaronVonRabbitface** [tgstation/tgstation#44041]
Problem Description: The healing effect of the drink Between the Sheets doesn't seem to be working.

What did you expect to happen: The drink is supposed to heal brute and burn if you sleep with it in your system.

What happened instead: I tested it in several rounds on Basil and for a while a solo server, and I couldn't get it to heal any damage at all, no matter how much I drank or how many times I slept.

Why is this bad/What are the consequences: Was trying to be unconventionally robust with this one. Could have actually helped save me few times if it was working properly.

Steps to reproduce the problem: Make some Between the Sheets (1 part Rum, 1 part Triple Sec, 2 parts Cognac, 1 part lemon juice), take brute or burn damage, drink Between the Sheets, sleep. 

Server: Several rounds on Basil, then an hour or so of testing on a solo server.

Revision: a277e6db656fbebbba2bafe321e15652b836c2d3

**Comment by YakumoChen** [comment]
Were you sleeping on a bed with a blanket?

**Comment by BaronVonRabbitface** [comment]
> 
> 
> Were you sleeping on a bed with a blanket?

I don't recall ever seeing that as a requirement for the effect to activate, but I actually did try that just in case it was an unwritten condition, and it still didn't work.

**Comment by RaveRadbury** [comment]
```/datum/reagent/consumable/ethanol/between_the_sheets
	name = "Between the Sheets"
	id = "between_the_sheets"
	description = "A provocatively named classic. Funny enough, doctors recommend drinking it before taking a nap."
	color = "#F4C35A"
	boozepwr = 80
	quality = DRINK_GOOD
	taste_description = "seduction"
	glass_icon_state = "between_the_sheets"
	glass_name = "Between the Sheets"
	glass_desc = "The only drink that comes with a label reminding you of Nanotrasen's zero-tolerance promiscuity policy."

/datum/reagent/consumable/ethanol/between_the_sheets/on_mob_life(mob/living/L)
	..()
	if(L.IsSleeping())
		if(L.bruteloss && L.fireloss) //If you are damaged by both types, slightly increased healing but it only heals one. The more the merrier wink wink.
			if(prob(50))
				L.adjustBruteLoss(-0.25)
			else
				L.adjustFireLoss(-0.25)
		else if(L.bruteloss && !L.fireloss) //If you have only one, it still heals but not as well.
			L.adjustBruteLoss(-0.2)
		else if(!L.bruteloss && L.fireloss)
			L.adjustFireLoss(-0.2)
```
