### ISSUE TITLE
Placing a supermatter crystal in a wall prevents it producing gas and prevents it delaminating.

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#44046]
Noticed this on my test server and through several rounds on /tg/Terry.

## Reproduction:
1. Get supermatter engine
2. Place wall on supermatter crystal
3. Turn on the emitters
4. Watch as even without cooling gas and even without scrubbing capacity it works fine

**Comment by Whoneedspacee** [comment]
how did you even get a wall on the supermatter is my question

**Comment by FloranOtten** [comment]
Alt click+RCD

**Comment by Barhandar** [comment]
Does it, and not the wall, actually get hit by emitters?

**Comment by FloranOtten** [comment]
Yes and no. Yes, the emitter hits the wall. It also hits the SM. I'm unsure exactly how but it starts producing power all the same.

**Comment by yoyobatty** [comment]
It's interesting because iirc, walls actually contain gas, which imo should not be a thing due to extra Atmos processing but that's just me.

**Comment by Whoneedspacee** [comment]
walls contain gas because they need to when they are destroyed. they do not however share gas with surrounding turfs which is the majority of lag from atmospherics (literally 99%)

**Comment by OverlyGeneric** [comment]
> Yes and no. Yes, the emitter hits the wall. It also hits the SM. I'm unsure exactly how but it starts producing power all the same.

I'm assuming it's producing radiation from the emitter blasts but it produces piss-all power all the same.

**Comment by PKPenguin321** [comment]
le dangerous complicated engine
