### ISSUE TITLE
safe snow is not, in fact, safe

### ISSUE THREAD

**Issue by plapatin** [tgstation/tgstation#44042]
how to reproduce:
step 1: spawn safe snow
step 2: tile floor with safe snow
step 3: monitor air temperature

**Comment by Barhandar** [comment]
Mmmm ex nihilo atmosia.

**Comment by Daxxed** [comment]
This was changed recently I think.
Noticed I get the cold warning when inside the snowman ruin on lavaland too, that didn't happen before.

**Comment by timothymtorres** [comment]
Duplicate of #46696
