### ISSUE TITLE
CE Jumpsuit not providing radiation protection when adjusted

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#44049]
How to reproduce:

Wear CE jumpsuit, alt click to wear it more casually. Wear CE hardsuit, flip helmet up.
Stand near radioactive material.
Get irradiated despite wearing CE jumpsuit and CE hardsuit.

**Comment by evsey9** [comment]
what did you expect when not wearing the jumpsuit properly and standing near highly dangerous radioactive material

**Comment by Barhandar** [comment]
That explains why Syd got irradiated.

**Comment by RaveRadbury** [comment]
Not a bug, safety first!

**Comment by AnturK** [comment]
Not a bug
