### ISSUE TITLE
No hunters spawning for fugitives

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#44052]
## Reproduction:
Both of these rounds had no hunter spawning after fugitives popped. 108752 I can confirm had no ghost roll for hunter either, so its probably not a missing ghosts thing.

**Comment by kriskog** [comment]
@tralezab

**Comment by tralezab** [comment]
More bugs your grace?

Dont worry this was already reported and fixed in my latest pr, I just gotta finish ship movement and we're good

**Comment by AnturK** [comment]
Duplicate of #43945
