### ISSUE TITLE
Holopara's dont know the language of their host

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#44059]
This is usually not an issue because almost all species know galactic common, but in edge cases such as ash walkers the holoparasite and their host cannot communicate.

**Comment by nemvar** [comment]
I'm pretty sure that one verb always allows the user and the stand to communicate.

**Comment by ATH1909** [comment]
Also, ash walkers can speak both common and draconian.

Beach bums speak can't (normally) speak common though, IIRC.

**Comment by PKPenguin321** [comment]
?
