### ISSUE TITLE
Anatomic Panacea repairs brain damage but has no effect on traumas

### ISSUE THREAD

**Issue by Eaglendia** [tgstation/tgstation#44067]
I feel like this is an oversight just because changelings have remained mostly unchanged since the trauma system started to gain traction, and it feels just a little bit unusual that changelings (who are meant to be masters of biology capable of purging toxins and repairing physical, or even genomic defects basically at will) can get bonked on the head/irradiated/poisoned in a way that renders them permanently damaged unless someone goes and pokes their literally-vestigial brain in the correct way.

I'm wondering what the most elegant solution to this is, and whether changelings should remain brainwashable as well (which is lumped in with the things that are cured by brain surgery). If this is all important to feature balance I guess it can be left alone, though.

**Comment by HomocidlePancakes** [comment]
1)Cling brains are basicly duds and they can function without one
2)"Regenerate". This ability restores lost limbs, organs and heals eye/ear damage. You should make it heal brain damage too.

**Comment by Angustmeta** [comment]
An oversight from when neurine was added. Panacea adds:
`user.reagents.add_reagent("mutadone", 10)`
`user.reagents.add_reagent("pen_acid", 20)`
`user.reagents.add_reagent("antihol", 10)`
`user.reagents.add_reagent("mannitol", 25)`

No neurine.

**Comment by Firecage** [comment]
Neurine would only heal basic traumas though, which would not help to much.
