### ISSUE TITLE
Your account is not old enough for assistant

### ISSUE THREAD

**Issue by europaisch** [tgstation/tgstation#44069]
When trying to join on Terry earlier today I only saw the assistant as joinable, and on clicking it it said my account is not old enough for assistant. It was all ok on Sybil, though.

OOC recommended to reconnect, did not work.

**Comment by HomocidlePancakes** [comment]
Not a bug. Database shat itself for whatever reason. It's actually a pretty common issue, so just AH whenever that happens.

**Comment by optimumtact** [comment]
DB needs to be reconnected by an admin
