### ISSUE TITLE
Cooks can instantly aggressive grab with CQC anywhere

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#44074]
#### Round ID:
Localhost. 

#### Testmerges:
None. 

#### Reproduction:

1. Be cook. 
2. Be not in kitchen. 
3. Grab intent. 
4. Click someone once. 

> Gus Banner violently grabs Quinn Stainforth! 

As seen on Admiral Hippies latest SS13-video:
https://youtu.be/gXcACRcmUQQ?t=79

Starting to reinforce that grab will also perma-slow you, until you passive grab and release someone.

**Comment by py01** [comment]
grab part probably my fault in #43750, moves working outside of kitchen shouldn't have been affected by that PR
