### ISSUE TITLE
Training Bomb is Buggy 

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#44078]
Round ID: 108921

![bomb](https://user-images.githubusercontent.com/37246588/58129824-a907ca80-7be8-11e9-9e3a-267ce19d1685.png)

just randomly walked up, no one was touching it, it kept going and going

caused by: #43996 im sure

**Comment by wesoda25** [comment]
its literally getting defused every second

**Comment by wesoda25** [comment]
if you cut wires, whatever wires you had cut get reset every second as well, meaning you can't remove the payload to get it to stop

**Comment by wesoda25** [comment]
@Incoming5643

**Comment by Incoming5643** [comment]
looking into it
