### ISSUE TITLE
Throw mode makes you immune to Nar'Sien bolas

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#44076]
#### Round ID:
Localhost. 

#### Reproduction:

1. Activate throwmode as a human by pressing R. 
2. Spawn another human and possess it. 
3. Cult yourself and make or spawn a Nar'Sien bola. 
4. Throw the bola at the first human. 

Result: It bounces off with no message whatsoever. 
Expected result: Human 1 catches the bola and gets stunned for a moment for touching a cult bola.

**Comment by Daxxed** [comment]
If someone catches your bola they deserve to not be stunned
Reckon its intentional

**Comment by Angustmeta** [comment]
The problem is they can't catch it at all.

**Comment by HomocidlePancakes** [comment]
Non-cultists get legcuffed if they pick up cult bolas

**Comment by Tlaltecuhtli** [comment]
not a bug

**Comment by kriskog** [comment]
Could probably use some user feedback when it happens.

**Comment by kriskog** [comment]
Actually, this runtimes.
`runtime error: Maximum recursion level reached (perhaps there is an infinite loop)
To avoid this safety check, set world.loop_checks=0.
proc name: UnregisterSignal (/datum/proc/UnregisterSignal)
  usr: null
  src: /datum/component/forensics (/datum/component/forensics)
  call stack:
/datum/component/forensics (/datum/component/forensics): UnregisterSignal(the Nar\'Sien bola (/obj/item/restraints/legcuffs/bola/cult), /list (/list))
/datum/component/forensics (/datum/component/forensics): UnregisterFromParent()
/datum/component/forensics (/datum/component/forensics):  RemoveFromParent()
/datum/component/forensics (/datum/component/forensics): Destroy(0, 0)
qdel(/datum/component/forensics (/datum/component/forensics), 0)
the Nar\'Sien bola (/obj/item/restraints/legcuffs/bola/cult): AddComponent(the Nar\'Sien bola (/obj/item/restraints/legcuffs/bola/cult))
the Nar\'Sien bola (/obj/item/restraints/legcuffs/bola/cult): add fingerprint(Isaiah Semenov (/mob/living/carbon/human), 0)
the Nar\'Sien bola (/obj/item/restraints/legcuffs/bola/cult): attack hand(Isaiah Semenov (/mob/living/carbon/human))
the Nar\'Sien bola (/obj/item/restraints/legcuffs/bola/cult): attack hand(Isaiah Semenov (/mob/living/carbon/human))
the Nar\'Sien bola (/obj/item/restraints/legcuffs/bola/cult): attack hand(Isaiah Semenov (/mob/living/carbon/human))
...
Isaiah Semenov (/mob/living/carbon/human): hitby(the Nar\'Sien bola (/obj/item/restraints/legcuffs/bola/cult), 0, 0, 0, /datum/thrownthing (/datum/thrownthing))
the Nar\'Sien bola (/obj/item/restraints/legcuffs/bola/cult): throw impact(Isaiah Semenov (/mob/living/carbon/human), /datum/thrownthing (/datum/thrownthing))
the Nar\'Sien bola (/obj/item/restraints/legcuffs/bola/cult): throw impact(Isaiah Semenov (/mob/living/carbon/human), /datum/thrownthing (/datum/thrownthing))
/datum/thrownthing (/datum/thrownthing): hit atom(Isaiah Semenov (/mob/living/carbon/human))
the floor (104,115,2) (/turf/open/floor/plasteel): Enter(the Nar\'Sien bola (/obj/item/restraints/legcuffs/bola/cult), the floor (105,115,2) (/turf/open/floor/plasteel))
the Nar\'Sien bola (/obj/item/restraints/legcuffs/bola/cult): Move(the floor (104,115,2) (/turf/open/floor/plasteel), 8)
Throwing (/datum/controller/subsystem/throwing): fire(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): StartProcessing(0)

MC: SoftReset called, resetting MC queue state.
MC: SoftReset: Finished.`
