### ISSUE TITLE
Cannot forge agent ID as a nuclear agent/nuclear agent leader

### ISSUE THREAD

**Issue by Phaxaris** [tgstation/tgstation#44087]
## Bug:
Nuclear agents are unable to use the forge option on agent IDs while traitors are able to. This is likely due to a check with agent IDs that prevent non-traitors from using them.

## Round ID:
Localhost

## Reproduction:

1. Become any form of nuclear agent.
2. Activate the agent ID nuclear agents spawn with and notice the lack of a forge option.
3. Set role to traitor, and notice new forge option upon activating the agent ID.
4. Remove traitor role, and ability to forge cards will be gone.

**Comment by py01** [comment]
When you set yourself to nuke op with the traitor panel, the cards are nonfunctional, but if you roll nuke ops they are forgable.

**Comment by Phaxaris** [comment]
However, if you set yourself to traitor they work. Nuke op shouldn't be different. I haven't been able to forge the card in normal servers in normal circumstances.
