### ISSUE TITLE
You can name yourself working HTTP links

### ISSUE THREAD

**Issue by Shapsy** [tgstation/tgstation#44089]
## Round ID:
108956

## Reproduction:
This report is a mix of issues, so stick with me

ISSUE 1:
1. Name your character a URL in your character prefs, in this case "www.tgstation.org" (can't use digits!). For humans this will add a last name on automatically, but it will still work.
2. Die or observe
3. Speak in deadchat and notice your name is a clickable outside link 
https://i.imgur.com/bk1H5aG.png

ISSUE 2:
1. Be named something with a link 
2. Make an AI track you or anything else that involves a command where your name is used in a link
3. Make the AI/whatever else open a local link
https://imgur.com/a/iX2F1Iq

This was originally noticed on the clown named www.byond.com whose name I var-edited prior to finding the bug, but Eagleandia and I confirmed and reproduced it with stock character names from prefs

This report is probably not an exhaustive list of all the ways this can be abused, but it should be a good starting point.

Also as a side note, you can use forbidden characters like slashes and digits with the magic mirrors which are available in some parts of the game to players like the wiz den, in case you want to throw on file paths or a nice https:// as well.

**Comment by plapatin** [comment]
nice

**Comment by Time-Green** [comment]
Oh boi I cant wait to make people join vore station with my name

**Comment by RaveRadbury** [comment]
Is it within naming policy to name silicons this way? It should be.

**Comment by commandhat** [comment]
Didn't I note this literally years ago?

...

[Yes. Yes I did.](https://github.com/tgstation/tgstation/issues/1957#issuecomment-29764786) (Quoted post from a [ancient Facepunch thread.](https://forum.facepunch.com/games/uijt/Space-Station-13-v10-Griff-Another-Day/293/)

**Comment by commandhat** [comment]
For completeness: Basically a mirror of #1957 where names aren't properly escaped. The easiest, laziest fix for this would be to forbid special characters like < : and / being used in names.

**Comment by SpaceManiac** [comment]
Issue 1: #38693 fixed a lot of instances of this, but because deadchat *messages* are intended to be allowed to include links, deadchat names having links slipped through. `deadchat_broadcast` would need to be changed.

Issue 2: Looks like a simple mistake in `camera/camera.dm`:
```dm
to_chat(AI, "<b><a href='?src=[REF(AI)];track=[html_encode(U.name)]'>[U]</a></b> holds <a href='?_src_=usr;show_paper=1;'>\a [itemname]</a> up to one of your cameras ...")
```
Should be `url_encode` rather than `html_encode`
