### ISSUE TITLE
Agent IDs have a change chameleon option that seems to do nothing?

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#44086]
round id 108944

If you have an agent ID and you're entirely naked then you have a change ID appearance button which works as it should and a change chameleon outfit button which doesn't seem to do anything.

**Comment by Phaxaris** [comment]
The "Select Chameleon Outfit" button changes the appearance of all chameleon items you are wearing to the role you click. Ex. you click "Chemist" all your clothes will become the default chemist stuff. If you only have an agent ID, it will only change the look of the card. If you want to change the way you look, you need to buy a chameleon kit from the syndicate uplink.

**Comment by py01** [comment]
the chameleon change only affects the card color, for example captain disguise makes the ID gold. It doesn't change the job name though.

**Comment by Dorsisdwarf** [comment]
Comments indicate this doesnt seem to be a bug
