### ISSUE TITLE
Miner KA now shoots in random directions at times.

### ISSUE THREAD

**Issue by gamefreak2998** [tgstation/tgstation#44102]
## Reproduction: The issue began around the time I picked up my KA and used my gps, about the time I moved the GPS window out of the way the KA would just shoot in random directions (even behind me for some reason?) instead of the direction I wanted.

No  idea what could of caused this but I dont think I'll want to role miner for a while.

**Comment by gamefreak2998** [comment]
![image](https://user-images.githubusercontent.com/49456986/58219746-99b07c00-7cd1-11e9-8a70-b074621054b6.png)
 for context in the image i'm attempting to mine the rock directly infront of my character.

**Comment by kopoba** [comment]
This affects all shooting items tasers, laser guns, mateba ect.

**Comment by gamefreak2998** [comment]
Yep all ranged weapons even staves got it test it further. I can't aim left, down, or right. Down in particular shoots straight up.

**Comment by Markolie** [comment]
The new BYOND version resolves these issues: https://www.reddit.com/r/SS13/comments/bsl8x8/byond_development_news_52419/.

**Comment by AnturK** [comment]
Fixed in 1470
