### ISSUE TITLE
Abductors teleporter doesn't check for atomsphere

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#44101]
Issue reported from  Round ID: 109000 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1418

If an abductor uses the teleporter to send back a crew member after surgery, the subject is placed in a random location on the station, however this doesn't check for a breathable atmosphere, in conjunction with being asleep through the teleportation, subjects can be ejected into space through holes or just suffocate before they can do anything about it.

This basically means its a bit RTD when sending someone back and hoping they will live.

**Comment by HomocidlePancakes** [comment]
It’s not random you knob. Abductors manually choose where they want to drop off people.

**Comment by Dorsisdwarf** [comment]
Abductors probbably shouldn't be able to drop people into space but that's a design/balance issue, innit
