### ISSUE TITLE
beach bartender ghost role spawned me as sunglasses

### ISSUE THREAD

**Issue by leon2550** [tgstation/tgstation#44103]
## Round ID: 
109016

## Reproduction:
Wiz round, RPGloot, bartender spawned with sunglasses with the Tactical prefix.
![image](https://user-images.githubusercontent.com/43494490/58224446-da1cf380-7ceb-11e9-8bc1-4c85979448fe.png)

**Comment by ATH1909** [comment]
amazing

if you took the sunglasses off, what happened?

**Comment by py01** [comment]
Tactical prefix is supposed to make them act like bushes, though not sure if its intended to work while wearing.

**Comment by AnturK** [comment]
What's the problem exactly.

**Comment by py01** [comment]
Doesn’t appear to be an issue, just someone mistaking a new feature for a bug
