### ISSUE TITLE
Welding Tool bug, sprite not consistently showing when tool is on.

### ISSUE THREAD

**Issue by zombiegums** [tgstation/tgstation#44100]
Issue reported from  Round ID: 108997 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1464

I'm not sure why, or if this is just isolated to the integrated welding tool that cyborgs have (engineering borg module is where I encountered this problem), but there is an inconsistently occurring bug where the sprite of the welding tool does not correctly correspond to its current status. So, welding tools that are actually on are having their sprites show them as off. This then leads to accidental welder-bombing when trying to refuel the tool. 

I noticed that welding tools do not have flavour text that denotes whether they are on or off. I know that the visual sprite should be enough of an indicator because it's obvious, but maybe it'd be helpful to have flavour text just in case this glitch persists? I don't know what causes this bug, but I've had it happen to me before.

Edit: I know putting them in your borg inventory will automatically turn them off as well, so there's also that. But I still think this should be reported, since it shouldn't be happening.

**Comment by timothymtorres** [comment]
Issues #36936, #44100, #38820, and #37227 all seem to be related to a BYOND bug that was fixed at some point since there haven't been any recent issues involving overlays in the past few years.  

Going to go ahead and close them all.
