### ISSUE TITLE
Adding a fried item to a pizza drops the original

### ISSUE THREAD

**Issue by jegub** [tgstation/tgstation#44123]
## Round ID:
109119 (Sybil)

## Testmerges:
#43148, #43876, #44077

## Reproduction:
Credit to Mark Leech for noticing and testing this, looks to be similar to the basketballs of issue #39446.
Fry an item and add it to a pizza, the pizza will now list the fried item and the original item will drop at your feet.
Good for making Legion pizza and not exactly game breaking, but a bit confusing.

**Comment by AzureWildfire** [comment]
This happens with anything that can accept a fried item

**Comment by ATH1909** [comment]
Hey, is this a way to un-fry the items that have been fried by griefers without calling in an admin to help?

**Comment by ATH1909** [comment]
Could one combine this technique with the one described in #39446 to make as many basketballs as you have the time to make?

**Comment by AzureWildfire** [comment]
Nah only works with small enough items to fit in the bread, pizza, etc.

**Comment by AzureWildfire** [comment]
Something I haven't tried and I'm curious is, if you dry the nuke disk, it makes a new one(as like moving it of z level.) If it does then it means you can make real duplicates of the nuke disk
