### ISSUE TITLE
Mystery "body created" C4 event

### ISSUE THREAD

**Issue by Chocobro** [tgstation/tgstation#44126]
![mystery](https://user-images.githubusercontent.com/5677255/58353619-e37e9b00-7e66-11e9-99d1-4d653617092f.png)

this is probably an extremely edge case bug i have no idea what caused it just that it was very near the end of the round

**Comment by Barhandar** [comment]
The bug is that it always shows "BODY CREATED" in the title; it's intended to let you orbit the event of interest by clicking on the button in the UI.
