### ISSUE TITLE
Revenant the invisible protector

### ISSUE THREAD

**Issue by GhostAvenger** [tgstation/tgstation#44137]
## Reproduction:
>Be Revenant
>Body block projectiles
>Win

**Comment by GhostAvenger** [comment]
Less memey:
Revenenant can body block all kinds of projectiles even when in invulnerable state.

**Comment by HomocidlePancakes** [comment]
Dupe of #43804

**Comment by GhostAvenger** [comment]
Literally the opposite. In my case, you are immune to damage, but you can still block the projectiles

**Comment by GhostAvenger** [comment]
I manage to basically protect the Blob for a while with this when he holed up in AI sat. I could literally hold the choke point and they cannot do anything to stop me. They would have to approach the choke point and I would block Mech Missiles, Particle Laser, and other things that would definitely have affected the blob spread alot.

**Comment by HomocidlePancakes** [comment]
If you’ve actually read the comments you would notice that people discovered rev doesn’t take damage. 100% dupe.
