### ISSUE TITLE
Artificer magic missles only slip now

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#44138]
I dont see this anywhere in the changelog, so im guessing its unintended. Last Pr that touched the wizard spells was #43843

**Comment by AnturK** [comment]
What do you mean only slip. All magic missiles only knock you down.

**Comment by py01** [comment]
To clarify, are you saying it is intended for people to not be stunned by magic missles? I can’t find any PR that makes that change, and I’m pretty sure they used to stun
