### ISSUE TITLE
Deconverted cultists retain their halos

### ISSUE THREAD

**Issue by MortoSasye** [tgstation/tgstation#44148]
Issue reported from  Round ID: 109211 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1467

Steps:
1) Become cultist
2) Get to the red halo phase
3) Get deconverted
4) Retain shiny blood halo

**Comment by SuperNovaa41** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/43002
