### ISSUE TITLE
gloves of the north star have no maximum range

### ISSUE THREAD

**Issue by ahkent** [tgstation/tgstation#44159]
## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:

obtain gloves of the north star
set warcry to "*me"
put them on, set harm intent, walk up to someone and click them as many times as you'd like
each hit triggers a *me prompt, don't fill them out or anything
take the gloves off, put them in your bag or the disposals, whatever
walk to any distance and/or location you want (at least on the same z-level)
click cancel on every *me prompt for 1 attack per

**Comment by py01** [comment]
you can initiate these with help intent i assume

**Comment by ahkent** [comment]
only harm intent, but it gives no indication you've done so

**Comment by Tlaltecuhtli** [comment]
its the work of an enemy stand

**Comment by AnturK** [comment]
say needs to pass forced argument to emote calls, and emotes should check against it.

**Comment by 4dplanner** [comment]
lmao

**Comment by HomocidlePancakes** [comment]
Please don’t remove the ability to spam *flip and *clap while fixing it

**Comment by tralezab** [comment]
I wonder if this would be the same for standard holoparasites?

**Comment by py01** [comment]
tested, punch holopara's dont allow emotes

**Comment by ATH1909** [comment]
https://cdn.discordapp.com/attachments/326826573951008769/582857725277503488/gloves_of_the_north_star.PNG

what have you done

**Comment by OverlyGeneric** [comment]
> https://cdn.discordapp.com/attachments/326826573951008769/582857725277503488/gloves_of_the_north_star.PNG
> 
> what have you done

mmm, shame it is. martial art it should be. gay are gloves.

**Comment by ATH1909** [comment]
> > what have you done
> 
> mmm, shame it is. martial art it should be. bad are gloves.

But I like the GotNT+Sleeping Carp wombo-combo...

**Comment by ATH1909** [comment]
Speaking of martial arts, what happens if you take off your GotNS and replace them with boxing gloves before spamming "cancel"? Will the blows then be nonlethal? Will they be executed at a GotNS pace or at a standard pace?

**Comment by ahkent** [comment]
you dont have to be wearing the gloves when you cancel. i assume wearing boxing gloves would set your attacks to nonlethal. i tested by giving myself krav maga without the warden gloves, and i could do a single krav maga attack at the start of all the fotns attacks.

**Comment by ahkent** [comment]
they dont have to be removed just not delay their hit until after the emote

**Comment by py01** [comment]
Martial arts apply if they are active when you cancel

**Comment by ATH1909** [comment]
Can you attack less often if you're not wearing the gloves when you cancel-spam?

**Comment by ATH1909** [comment]
Ethereals could use this to instahusk someone from across the station, couldn't they?

**Comment by ahkent** [comment]
@ATH1909 yes if they do burn damage with their punches
also it doesnt matter whether youre wearing the gloves or not when you cancel, its the same speed/damage as if you are. your victim can be wearing the gloves if thats what floats your boat.
