### ISSUE TITLE
Bot Patrols tend to converge

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#44156]
Bots have a tendency to all gather into the same patrol, often leading to having all of the station's bots in one pile, patrolling on the same route. All the bots seem to calculate routes on the same ticks, but with different distances between navigation points, this invariably causes them to all converge into the same patrol route, which doesn't seem to differ at all between any of the bots.

More variance on route plotting is required, or and perhaps include a small chance each plot for them to reverse, so that bots seperate more often.

**Comment by trollbreeder** [comment]
![image](https://user-images.githubusercontent.com/25937686/66324064-1791be80-e925-11e9-8eac-eef0c0935a3a.png)
The ultimate lifeform
Inspector Sweepsky

**Comment by timothymtorres** [comment]
This is not a bug.  Sometimes the bots clump together and it's not that big of a deal nor does it always happen.  Someone could write in a PR so that bots can't be on the same tile but that is a feature request.
