### ISSUE TITLE
During repeatable surgery steps (organ manipulation) you use the item on the target in a non-surgical way

### ISSUE THREAD

**Issue by MCterra10** [tgstation/tgstation#44173]
When performing organ manipulation or any other surgery with a repeatable step, you use the item you are using on the target in addition to using it in surgery. This leads to huge issues that break self-surgery when you have augments, for example, as you take a bite out of the organ making it unable to be inserted. This happens even when wearing a mask, although it says you couldn't eat it, a bite is still taken and the surgery does not work.

## Reproduction:
Get augmented
Start organ manipulation on a body part
Remove an organ
Attempt to replace organ
Notice that you eat the organ and that it is not inserted

**Comment by MCterra10** [comment]
I first noticed this in robotics when borging. I noticed that I always hit them with the hemostat right after then brain was extracted. Later I got myself augmented and went to replace my organs with cybernetic versions, but took a bite out of the liver and couldn't insert it. Died of toxin damage. Fun times

**Comment by nicbn** [comment]
Self surgery shouldn't even be a thing

**Comment by MCterra10** [comment]
The bug doesn't just apply to self surgery

**Comment by Barhandar** [comment]
Also noticed that I sometimes get doubled-up actions, including during surgery.

**Comment by MCterra10** [comment]
I believe this issue started after #43904 was merged. Probably missing a return somewhere

**Comment by ATH1909** [comment]
@XDTM Hey, while you're fiddling with surgery, could you fix this bug? It's super annoying if you're trying to do self-surgery.

**Comment by MCterra10** [comment]
Epic
