### ISSUE TITLE
Atmos shenanigans

### ISSUE THREAD

**Issue by Ghilker** [tgstation/tgstation#44182]
Issue reported from  Round ID: 109433 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1470

The scrubbers allow infinite pressure in the pipes, the injector allows infinite pressure in the atmosphere, combined those make a room temperature canister hold infinite pressure
![Screenshot (3)](https://user-images.githubusercontent.com/42839747/58508561-95360880-8194-11e9-9d01-8ea2b3f43ae9.png)
![Screenshot (5)](https://user-images.githubusercontent.com/42839747/58508567-9830f900-8194-11e9-8810-71d421a830cf.png)

**Comment by Whoneedspacee** [comment]
oh that is hot

**Comment by Ghilker** [comment]
![tenor](https://user-images.githubusercontent.com/42839747/58512135-a125c880-819c-11e9-8223-53136adeeef7.gif)

**Comment by TheChosenEvilOne** [comment]
This is all because of the portable scrubber. (I discovered this "feature")

**Comment by 4dplanner** [comment]
lol

**Comment by Ghilker** [comment]
Thanks buddy
