### ISSUE TITLE
[Possible Duplicate] Darkmode chat MOTD unreadable

### ISSUE THREAD

**Issue by AffectedArc07** [tgstation/tgstation#44189]
## Round ID: 109473

The MOTD in the chat in darkmode, looks like this: 
![image](https://user-images.githubusercontent.com/25063394/58549408-5ab78480-8203-11e9-967f-649c4619a111.png)
Clearly this is unreadable to 99% of people

## Testmerges:
#43666: '[WIP] Game Mode - Natural Disaster' by RaveRadbury at commit 109bdcab52
#43693: '[READY] Smooth(er) Movement V2 (60 FPS fix)' by actioninja at commit ed05e69207

## Reproduction:
Log in
Enable darkmode chat
Read the MOTD

**Comment by ATH1909** [comment]
darkmode was a mistake

**Comment by AffectedArc07** [comment]
![image](https://user-images.githubusercontent.com/25063394/58576730-e6013c00-823c-11e9-8196-ecb68edaedea.png)

**Comment by actioninja** [comment]
There is another issue about this. It's not a code problem, it's a config issue. The motd is formatted by font and color tags instead of span like it should be.

**Comment by actioninja** [comment]
Yeah #43809
