### ISSUE TITLE
Trinary atmos components (mixer and filter) still get rotated 180 degrees instead of mirrored when you choose "Flip Pipe" verb

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#44219]
Their override code to make them actually flip, i.e. change `flipped` variable and adjust the dir so the throughput direction stays the same, seemingly doesn't function. This makes it more or less impossible to build/adjust them manually - only RPD can print them flipped.

**Comment by Sealed101** [comment]
the `Invert Pipe` verb for the RMB menu of a trinary device remains mostly unchanged through the years
https://github.com/tgstation/tgstation/blob/b832e2f47765ea321457221cc4e2a8ea64137555/code/game/machinery/pipe/construction.dm#L146-L154

https://github.com/tgstation/tgstation/blob/b832e2f47765ea321457221cc4e2a8ea64137555/code/game/machinery/pipe/construction.dm#L156-L161

`flipped` var gets properly inverted; visually the changes might be hard to notice, but the long main-output route gets inverted, the side node flips properly, and the entire device changes direction
|Initial|use `Invert Pipe` verb|
|-|-|
|![изображение](https://github.com/tgstation/tgstation/assets/75863639/ac873508-42b6-43ad-8059-502efccced57)|![изображение](https://github.com/tgstation/tgstation/assets/75863639/11899514-910b-4c95-8140-8f8cb2fa6e1e)|
