### ISSUE TITLE
vendors other than snack ones can accept custom inputs

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#44210]
![](https://api.monosnap.com/file/download?id=TciyZmv8Ye2j6VrT4PowGwbevbRs4J)

**Comment by RaveRadbury** [comment]
@ExcessiveUseOfCobblestone is this related to #43964?

**Comment by ExcessiveUseOfCobblestone** [comment]
Yes

**Comment by ExcessiveUseOfCobblestone** [comment]
@Tlaltecuhtli were you able to manually insert items into the vending machine or was it via bag?
