### ISSUE TITLE
stripping menu steals focus.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#44215]
Every time you finish an action initiated by crafting/stripping menu, they steal focus, causing some awkwardness from time to time. If closed they will reopen themselfs and steal focus regardless.

MAINTAINER EDIT: crafting menu now uses input passthrough as of 2020/1/3

**Comment by Barhandar** [comment]
Also autolathe.

**Comment by HomocidlePancakes** [comment]
Yeah. It's the same kind of menu. I just forgot that autholathe also used it

**Comment by nemvar** [comment]
Has been fixed for the crafting menu.
