### ISSUE TITLE
People with the paraplegic quirk examining the health doll get "Your left/right leg is OK."

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#44218]
Oversight, but not a great one, especially considering the health doll itself indicates those legs are non-functional.

**Comment by nemvar** [comment]
Well, your legs might be non-functional, but they still contribute to your overall health. It makes sense that you get a more accurate indication if they have damage or not.

**Comment by moonheart08** [comment]
"Your left/right leg is OK... But it's a tad stiff."
