### ISSUE TITLE
Silicons can no longer interface with sleepers.

### ISSUE THREAD

**Issue by zombiegums** [tgstation/tgstation#44224]
Issue reported from  Round ID: 109597 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Silicons can open and close them, but are unable to inject chemicals into the occupant. This was working previously, and broke within the last few days. 

Reporting client version: 512.1470

**Comment by Time-Green** [comment]
who’s gonna tell him?

**Comment by kopoba** [comment]
stasis beds was a mistake

**Comment by Barhandar** [comment]
Sleepers still exist in space and on escape shuttle, this a breakage regardless of stasisbed presence.

**Comment by HomocidlePancakes** [comment]
The PR that “fixed” being able to alt+click sleepers from any range borked it. Like shit. Someone even specifically mentioned this sideefect if the bug gets fixed in the bug report.

**Comment by Dorsisdwarf** [comment]
I love people who merge fixes that are known to cause more bugs

**Comment by kriskog** [comment]
Not sure what you are on about HomocidlePancakes, all the adjacency checks for injection is done by tgui, which my PR didn't touch - and there was nothing about this in the bug report. I was never able to reproduce this, still not.
