### ISSUE TITLE
Techweb RnD console items have wrong icons

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#44237]
Round ID: 109653
BYOND Version: 512.1467
Server revision compiled on: 
Master commit: f66769a1131f51c8b2fd11f2c304fcb799682937
The following pull requests are currently test merged:
#43693: '[READY] Smooth(er) Movement V2 (60 FPS fix)' by actioninja at commit 395f62c385
#43876: 'Kilo station' by Okand37 at commit 952992151d
#44155: 'Dragging prone mobs slows you down, fireman carrying' by actioninja at commit e3d9ea68ac
#43148: '[s]Temp workaround for admins matching stickybans because of a byond bug.' by MrStonedOne at commit f34e61e42d
#44166: 'Remove reagent ids and use typepaths where applicable' by vuonojenmustaturska at commit 7c938d69fd

Some techweb node previews in the RnD console show wrong icons - for example, engineering scanner goggles show the NVG icon, magnetic boots show as a genetics disk and welding gas mask shows as mesons.

![efwewweffweweffe](https://user-images.githubusercontent.com/32391752/58724322-93f71c80-83dc-11e9-88f2-1aac9ab88db3.png)

**Comment by FloranOtten** [comment]
![image](https://user-images.githubusercontent.com/38219334/58821272-fd716800-8634-11e9-8405-35aa069de572.png)

![image](https://user-images.githubusercontent.com/38219334/58821298-09f5c080-8635-11e9-86ea-f47def3cdaf7.png)

![image](https://user-images.githubusercontent.com/38219334/58821335-1b3ecd00-8635-11e9-88cd-eb30bb87f95d.png)

![image](https://user-images.githubusercontent.com/38219334/58821358-285bbc00-8635-11e9-98c1-d81555e837e3.png)


![image](https://user-images.githubusercontent.com/38219334/58821381-37426e80-8635-11e9-823b-254af0dad7a3.png)

**Comment by FloranOtten** [comment]
![image](https://user-images.githubusercontent.com/38219334/58821457-648f1c80-8635-11e9-96cf-07aa1adf7ab0.png)

![image](https://user-images.githubusercontent.com/38219334/58821480-707ade80-8635-11e9-807a-c47b9fcac0f2.png)

![image](https://user-images.githubusercontent.com/38219334/58821493-7a044680-8635-11e9-967f-224a17bace8c.png)

![image](https://user-images.githubusercontent.com/38219334/58821530-91dbca80-8635-11e9-9829-18b77891b31d.png)

**Comment by RaveRadbury** [comment]
Clown Goggles WHEN

**Comment by FloranOtten** [comment]
Honks when you look at something funny.
