### ISSUE TITLE
Pupper Ian does not eat food

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#44230]
Maximum priority this shit, Ian is a hungry boi

**Comment by BrandonCouts** [comment]
Ian already eats food, according to the code.

https://github.com/tgstation/tgstation/blame/master/code/modules/mob/living/simple_animal/friendly/dog.dm#L424

**Comment by YakumoChen** [comment]
@BrandonCouts This is for the puppy ian
