### ISSUE TITLE
Not Dropping Items in Crit

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#44248]
## Round ID: 109684
 
So I was hitting myself with an esword. First I cut off both my legs, then my arm. Then I kept attacking myself while still aiming at the arm I lost. I hit myself in to crit, (real crit), but I only dropped the esword upon succumbing.

**Comment by HomocidlePancakes** [comment]
Something something resting something something

**Comment by loserXD** [comment]
just had this happen a few rounds ago

**Comment by timothymtorres** [comment]
So I searched through all the open issues for drop/crit and I found nothing related to this issue.  Whatever was causing this apparently got fixed at some point.  Marking this as cleanup.
