### ISSUE TITLE
Chief Engineer's Hardsuit + Jumpsuit Still not proving 100% radiation protection

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#44249]
Issue reported from  Round ID: 109686 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1464

As title says, something isn't right with radiation protection stacking. The 10% jumpsuit + 90% hardsuit body doesn't seem to be stacking to be 100%. I had 1k or so rads despite wearing the hardsuit and jumpsuit the entire round.

Picture of my items being contaminated with radiation. Forgot to take one of my radiation level as well.

![image](https://user-images.githubusercontent.com/222630/58744429-c2362580-83f7-11e9-80aa-a98228f8f227.png)

**Comment by HomocidlePancakes** [comment]
You most likely irradiated yourself with your own contamination while eating/healing tbh.

**Comment by Tlaltecuhtli** [comment]
just make ce hardsuit 100 rad prot

**Comment by Barhandar** [comment]
Did you do fusion, perchance?

**Comment by Hathkar** [comment]
I didn't do any fusion. The only time I removed my helmet was to eat for 5 seconds.

**Comment by Barhandar** [comment]
That's enough to get irradiated. In testing on local, unadjusted jumpsuit + full hardsuit made me entirely radproof from sources that respect radiation protection.

**Comment by ShizCalev** [comment]
User error
