### ISSUE TITLE
Hallucinated secbots from drinking beepsky smash are visible to others.

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#44246]
## Round ID:
109665

## Testmerges:
Kilo Station, Stamina Changes

## Reproduction:
![image](https://user-images.githubusercontent.com/10399117/58739651-fd862380-83fa-11e9-8a86-983a6417b5d9.png)
Dead guy with invisible Pingsky after a suicide. It also yells in the chat so other people can hear it too, apparently, and doesn't go away (probably because the booze doesn't process since he's dead)

**Comment by 4dplanner** [comment]
lol

**Comment by XDTM** [comment]
FYI, only ghosts and the victim can see it with right click.
