### ISSUE TITLE
chem dispenser reagents aren't alphabetical anymore

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#44247]
nor are booze/soda dispenser reagents
they used to be alphabetical, but now they're in the order of the list in https://github.com/tgstation/tgstation/blob/master/code/modules/reagents/chemistry/machinery/chem_dispenser.dm#L36

round ID 109668
TMs #43693 #43876 #44155 #44166 

i think #44166 is probably what broke it

**Comment by ATH1909** [comment]
@vuonojenmustaturska

**Comment by Rayisken** [comment]
Welp, there goes my muscle memory

**Comment by loserXD** [comment]
fixed by #44386

**Comment by Dorsisdwarf** [comment]
Reported fixed.
