### ISSUE TITLE
Cannot Use Guidance or Speak in "Fugitives" game mode.

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#44250]
Issue reported from  Round ID: 109686 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1464

This is as the followers' divine. I cant seem to speak to my followers beyond using the "Divine Oration ability, so I am unable to communicate with them, only one sidedly. Additionally if I don't keep my camera on them constantly I lose them and since I can't use the "Guidance" ability I have issues finding them again.

**Comment by tralezab** [comment]
Did you try speaking normally? All of your followers hear that. I'll look into the guidance ability

**Comment by TheSilverNuke** [comment]
> 
> 
> Did you try speaking normally? All of your followers hear that. I'll look into the guidance ability

Yeah I wasn't able to speak at all unfortunately.
