### ISSUE TITLE
Several rare or expensive items should not be consumable

### ISSUE THREAD

**Issue by AWalton** [tgstation/tgstation#44266]
The first set is cybernetic organs. It's more realistic that they'd be too hard to be eaten, it'd be like eating a PDA. Taking a bite out of it ruins it for surgery so considering the materials cost as well this behaviour should be stopped. 

Secondly in an admeme event I got gifted a Changeling egg which I had no idea of how to use, ended up taking a bite of it before learning it needs to be inserted via surgery into my chest cavity. Never got round to actually getting another and getting it inserted because of other events that happened so it was disappointing that I accidentally ruined using this great item because it didn't come with an instruction manual.

**Comment by Barhandar** [comment]
Issue tracker is for issues, eating organs when not intending to is already reported, and the rest are feature suggestions - go to forums.

**Comment by HomocidlePancakes** [comment]
Ided

**Comment by SpaceManiac** [comment]
"Already reported" is meaningless without proof in the form of a ticket number

**Comment by kriskog** [comment]
On one hand we want organs to be consumable (maybe except for the cybernetic ones), on the other we need a way to figure out how to use them before trying to eat them. Maybe some examine text outlining its an organ and could be insterted into people?
