### ISSUE TITLE
quick draw from belt (shift+e) while incapacitated causes items to come out of the belt onto the floor

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#44275]
You probably shouldn't be able to shift+e while stunned, sleeping, ect.

**Comment by HomocidlePancakes** [comment]
Your hand spergs out when you reach for tools , so you drop them. Also why are you even trying to do this while stunned?

**Comment by Daxxed** [comment]
He is spamming it so he has the baton out as soon as he is up but instead he just donated it to his attacker.
Poor soul.

**Comment by HomocidlePancakes** [comment]
Lol. You can open containers by click dragging you nerd. Use that instead of ctrl+e

**Comment by Daxxed** [comment]
You already made it clear your powergame is weak but I will explain once again.
He is spamming ctrl+e to grab his baton while clicking his target’s sprite. Potentially getting a lifesaving stun if their target does not chain stun properly.

**Comment by py01** [comment]
It’s clearly a bug that you can draw items from your belt while sleeping anyway
