### ISSUE TITLE
Goofed Odyessus Chem Manufacture

### ISSUE THREAD

**Issue by AdamBlue9000** [tgstation/tgstation#44286]
Issue reported from  Round ID: 109789 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])
https://gyazo.com/8047869b4d759fc9c35bf3e9008440fb
Doesn't work when i press the button. Scans in fine, just won't produce.
Reporting client version: 512.1466

**Comment by ExcessiveUseOfCobblestone** [comment]
embed ur images reeee
