### ISSUE TITLE
Watcher sinew restraints not useable for crafting

### ISSUE THREAD

**Issue by Daxxed** [tgstation/tgstation#44309]
## Reproduction:
Sinew restraints can not be used for crafting recipes, thus ashlizards are forced to powergame cable coil from other ruins or the mining station in order to craft more spears or bolas.

**Comment by nemvar** [comment]
Bone spears are craftable without cable cuffs, but I agree, it's not pretty.

**Comment by Daxxed** [comment]
If the entire nest was emptied of spears you are not gonna craft a bone spear though.
Balance aside this should just work for consistency.
