### ISSUE TITLE
Guthen and Gubbuck Sometimes Don't Eat

### ISSUE THREAD

**Issue by Denthamos** [tgstation/tgstation#44307]
## Reproduction:

The ashwalkers Guthen and gubbuck does not produce milk at all, udder is always dry.  Fed the tendril over 20 bodies, 6 goliaths, 4 watchers corpses and nothing was made.

**Comment by nemvar** [comment]
They are supposed to do that?

**Comment by Denthamos** [comment]
@nemvar Are you sure your copy is updated?  We had 10+ ash walkers and none of us could milk the gubbuck or guthen.  Rslite and a few other admins were online that round too and can confirm it was not working either.

**Comment by Daxxed** [comment]
Can confirm they have been broken for a while.

**Comment by ExcessiveUseOfCobblestone** [comment]
"not working" = reagents but cannot milk, no reagents, ...?

Milkgeneration is a probability everytime the proc is called so it's possible you're just getting bullied by RNGesus

**Comment by ExcessiveUseOfCobblestone** [comment]
They also only eat the following (+subs)

`/obj/effect/decal/cleanable/xenoblood/xgibs, /obj/effect/decal/cleanable/blood/gibs/, /obj/item/organ` so if your mob doesn't produce any of these it will not generate milkies.

**Comment by Denthamos** [comment]
Not working as in, like I referenced in the opening comment on this issue.  All the message says is "the udder is dry".

In regards to mobs, in this particular round we fed the tendril goliaths, basalisks, goldgrubs, ashen skeletons, actual humanoid mobs dropped by legions, dead golems we killed, and dead miners we killed.  Nothing allowed the two to create milk.

**Comment by HomocidlePancakes** [comment]
Yeah they are scuffed. Usually dragging them for a bit fixes ‘em temporairly.

**Comment by Daxxed** [comment]
@nemvar 
I haven't been able to get any milk for the past 30 hours as ligger, can you tell me exactly how you got it to produce ?
They always had plenty of gibs and organs around, I tried petting, manual feeding, everything...

**Comment by ironsnake345** [comment]
Still going on, but I've got some more info on it. Gubbuck and Guthen only produce milk after slurping up food, and they only slurp up food when they've been hurt. So as it stands, to get grub milk from gubbuck and guthen, you first need to squash them a bit. Just a little, so they eat.

**Comment by ironsnake345** [comment]
Also, you're not able to feed them organs by hand. I tried that.
