### ISSUE TITLE
Brains can be damaged with items with 0 force and require mannitol to be restored

### ISSUE THREAD

**Issue by Nickkoranda** [tgstation/tgstation#44302]
Step 1. get brain
Step 2. hit brain with anything from a pen to a sombrero
Step 3. be required to use mannitol to fix it

**Comment by Whoneedspacee** [comment]
brain hurty

**Comment by Tlaltecuhtli** [comment]
stick a pen in your brain and see if you get brain damage

**Comment by MegaEmpirical** [comment]
Sounds like a feature.

**Comment by nfreader** [comment]
Is it a bug? Is it a consistency issue? Who knows! But I was able to reproduce it!

**Comment by kriskog** [comment]
Adding a force check and early return in /obj/item/organ/brain/attackby() should fix it.

**Comment by Coconutwarrior97** [comment]
Fixed by #45428.
