### ISSUE TITLE
gravitokinetic holoparasite effect lasts forever

### ISSUE THREAD

**Issue by zeroisthebiggay** [tgstation/tgstation#44326]
Issue reported from  Round ID: 109917 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1462

>be detective
>get smacked like six times by a gravitokinetic holoparasite
>stuck with slowdown and inability to pick up items for the rest of the round
>cry a river

>later on in the time line
>ahelp to get fixed
>an aheal and vv doesn't even work
>suicide via alcohol and get cloned and then it is finally gone

**Comment by HomocidlePancakes** [comment]
@tralezab fiiiiiiiiiiiiiiiiiiix yooooooooooooooooooooooour thiiiiiiiiiiiiiiiiing aaaaaaaaaaaaaa
