### ISSUE TITLE
Nullrod Hypertool Missing Sprite + Vanishing

### ISSUE THREAD

**Issue by TheShephard** [tgstation/tgstation#44325]

**Comment by francinum** [comment]
#44195 failed to actually add the iconstate to `devices.dmi`. @spessbro

**Comment by ATH1909** [comment]
Also, it *did* do damage- just not brute damage.

The hypertool actually does BRAIN damage (with a force of 18) instead of brute damage.

**Comment by Rowelll** [comment]
oof, it's VERY easy to abuse it before the fix

**Comment by nemvar** [comment]
It deals BRAIN damage? Holy fuck, that's broken

**Comment by Zenog400** [comment]
The "insuls" bible or whatever also spawns a pair of "insuls", and just deletes your bible's *sprite*, but not the bible itself. The insuls are just some fucking gloves, and they can't bless water. You have to use your now-invisible bible to do it.

**Comment by adamkad1** [comment]
Holy insulns when?

**Comment by ATH1909** [comment]
> It deals BRAIN damage? If the brain damage doesn't cap, that's pretty broken.

It doesn't have a cap, but it takes 12 hits with the hypertool to kill someone through brain damage (brains die at 200 brain damage, not 100 brain damage) and the hypertool doesn't count as a sharp item (meaning that you can't sharpen it with the chef's whetstone without admin intervention).

**Comment by ATH1909** [comment]
> The insuls are just some fucking gloves

I'll have you know that they're not just "some fucking gloves"!

```
if(icon_state == "insuls")
			var/mob/living/carbon/human/H =usr
			var/obj/item/clothing/gloves/color/fyellow/insuls = new
			insuls.name = "insuls"
			insuls.desc = "A mere copy of the true insuls."
			insuls.siemens_coefficient = 0.99999
			H.equip_to_slot(insuls, ITEM_SLOT_GLOVES)
```

As you can CLEARLY see here, the insuls give you a very, very tiny amount of resistance to electricity (the normal siemens_coeffecient of humans without gloves on is 1, IIRC).

**Comment by Nickkoranda** [comment]
Seems to have been fixed by https://github.com/tgstation/tgstation/pull/44432 as well
