### ISSUE TITLE
Fel, Finish Your Shit

### ISSUE THREAD

**Issue by fludd12** [tgstation/tgstation#44337]
I need to finally kick myself in the ass and finish crossbreeding. You all have permission to DM me on discord daily about finishing it until I'm finally done.

Roadmap to Completion:
- [x] Fix every current issue with xenobiology.
- [x] Finish the ideas spreadsheet.
- [ ] Code Warping extracts.
- [ ] Code Lengthened extracts.
- [ ] Code Destabilized extracts.
- [ ] Code Mutative extracts.
- [ ] Code Gentle extracts.
- [ ] Code Symbiont extracts.
- [ ] Code Detonating extracts.
- [ ] Code Transformative extracts.
- [ ] Code Loyal extracts.
- [ ] Code Crystalline extracts.
- [ ] Code Hyperchromatic extracts.
- [ ] Fix any issues that arise from the very definition of technical debt condensed into a project.
- [ ] Rework any extracts determined to be over/underpowered for their cost.
- [x] Cry a lot.

**Comment by fludd12** [comment]
Someone add the Slimes milestone to this, please.

**Comment by Tlaltecuhtli** [comment]
cannot reproduce

**Comment by RaveRadbury** [comment]
@Ty-the-Smonk

**Comment by adamkad1** [comment]
Stupid cat, get to work

**Comment by Wilchenx** [comment]
Fel, Finish Your Shit

**Comment by fludd12** [comment]
In related news, I have finally finished the [entire ideas list spreadsheet](https://docs.google.com/spreadsheets/d/1FhIHP_wEb1h1ir5if-k26ct9mnmcNgSaTSYy6nknoP4). I am also changing what the charged yellow extract does.

If I never have to have a new idea again, it'll be too soon.

...I say that, but I already have plans for botany.

**Comment by Wilchenx** [comment]
Fel, Finish Your Shit

**Comment by fludd12** [comment]
Update: A roadmap has been added to the body of this issue for what's needed to be done to finish.

**Comment by Wilchenx** [comment]
Fel, where are the catslimes

**Comment by Ty-the-Smonk** [comment]
Well I guess I'll see what I can do with symbionts, since I have 2 organs done so far (regeneration arm is weird)

**Comment by Qustinnus** [comment]
use milestones for this, dont bloat the tracker with it.

**Comment by Wilchenx** [comment]
Fel, finish your shit.

**Comment by interestingusernam3** [comment]
That just proves it
