### ISSUE TITLE
Lizards with fear of conspiracies keep stunning themselves

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#44357]
probally how the trauma works but its dumb that you stun yourself by seeing yourself every 10 seconds or so maybe adjust it racially or something?

**Comment by imsxz** [comment]
take psiodicdsicnsicsicne the chemical to ignore phobia it's a feature

**Comment by 81Denton** [comment]
On one hand lizards deserve it, on the other hand `phobia_species` should exclude the trauma victim's current race.

**Comment by HomocidlePancakes** [comment]
Just don’t wear timfoil hats?

**Comment by nemvar** [comment]
Feature

**Comment by 4dplanner** [comment]
lizards being scared of lizards is a feature, but it should exclude the trauma holding mob.
