### ISSUE TITLE
Singularity on lavaland

### ISSUE THREAD

**Issue by ilnor** [tgstation/tgstation#44368]
https://i.imgur.com/N3XgoY0.png

The singulo on lavaland breached containment when the tiles underneath the containment field get eaten.

Somehow when the tiles get turned into lava they remove the containment field and the singularity just keeps on cruisin, as you can see by the size of the hole it was a small singulo right on the cusp of stage 2 -> 3. My theory is when it upgrades to stage 3 the increased gravity pull lets it eat the tiles under the beam and that somehow is destroying the beam. 

I saw another post about this on delta station happening and it had the same look about it, the tiles underneath were missing and so was the containment beam, I'm guessing that it got a bandaid fix and the core problem still exists on lavaland somehow. 

Also don't ask me why I would do this, that's not important 

https://github.com/tgstation/tgstation/issues/40399 This is the other guy with the similar issue, I haven't had this issue on delta lately but the problem is quite similar looking

**Comment by Whoneedspacee** [comment]
i guess the turf got eaten and then just straight up deleted the contents which included the beam. is this a problem on station if there are turfs underneath the fields?

**Comment by ilnor** [comment]
Singularity up to stage 3 is safely contained by fields, unless they get deleted... in a bug.

**Comment by SpaceManiac** [comment]
>i guess the turf got eaten and then just straight up deleted the contents which included the beam.

This isn't supposed to happen.

**Comment by PKPenguin321** [comment]
we sure it's not the lava burning the beams?

**Comment by Dorsisdwarf** [comment]
Seems to be a specific case of #44379, closed for redundant
