### ISSUE TITLE
New Insul bible style problem. When Insul is selected the bible becomes invisible but still usable.

### ISSUE THREAD

**Issue by CrossbowDemon** [tgstation/tgstation#44370]
New Insul bible style problem. When Insul is selected the bible becomes invisible but still usable.

It's not supposed to do that, the bible is supposed to be removed and you get the gloves instead. But both the bible and gloves are present except the bible is invisible when in hand, inventory, or on the floor.

Issue reported from  Round ID: 110062 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1470

**Comment by AzureWildfire** [comment]
Yeah same with the hypertool null rod

**Comment by bgobandit** [comment]
this is because there are no sprites, or at least the sprites aren't in the right place/right name
@WJohn

**Comment by spessbro** [comment]
sorry am an idiot and not sure how to go around using git

**Comment by Nickkoranda** [comment]
Seems to have been fixed by https://github.com/tgstation/tgstation/pull/44432
