### ISSUE TITLE
Field Generators unable to contain singularity off the station Z-level

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#44379]
Issue reported from  Round ID: 110067 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1464

As the title says, field generator fields don't stop singularities that are level 2 or higher. The singularity just eats the field generator field and roams around.
I've reproduced this about three times, all with differing field generator placement to see if the area would make a difference.

https://i.imgur.com/G7C0Ljw.png
https://gyazo.com/49bb90869cee1412b7e6e803a9730377

**Comment by kopoba** [comment]
i was unable to reproduce this bug. But in my experiment singulo wasn't moving at all.
https://i.imgur.com/DgRUhsR.png

**Comment by 81Denton** [comment]
Just tested this on event hall, a stage 2 singulo casually ate through containment. I can't tell you the reason yet though.
https://i.imgur.com/jewlMv5.png

**Comment by kopoba** [comment]
I guess root of the problem is that you place floor under force field beams. So when Lord Singulo grows big he eat/move floor under beam WITH beam. So when you don't have floor under beam all works fine.

**Comment by kriskog** [comment]
I've not done singulo much, but fairly sure you need a 5x5 containment (inside the beams) to keep the higher stages singulos in. Try making it bigger, seems you are doing 4x4 and that might be causing the issue.

**Comment by Dennok** [comment]
As i know problem in jump from 1/1 singulo to 3/3, if it deal it near field some part of field be cowered by singulo and eated.

**Comment by kriskog** [comment]
Likely same as  #40399 where it eats containment if it comes into contact with it on grow.
