### ISSUE TITLE
If you secure a capacitor to a phazon suit it says that you secure a screwdriver.

### ISSUE THREAD

**Issue by Griffork** [tgstation/tgstation#44393]
Issue reported from  Round ID: 110122 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1467

```
You unsecure the capacitor from the Phazon chassis.

You secure the screwdriver.
```

**Comment by 4dplanner** [comment]
lol

**Comment by Barhandar** [comment]
Ditto regular ripleys.

**Comment by WJohn** [comment]
I'm uh, not getting this?
![image](https://user-images.githubusercontent.com/5988156/59719673-fd539980-91ea-11e9-8b54-5feb9f8e8174.png)
