### ISSUE TITLE
Mechs automatically select the first piece of equipment that is added

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#44395]
Issue reported from  Round ID: 110133 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1467

Step 1. Make mech
Step 2. Add equipment
Step 3. You have selected the first equipment that is added to the mech, but the button to switch shows you having none equipped
Step 4. Misclick, shoot a rocket at your feet and die because you can't be saved from inside a mech

**Comment by Tlaltecuhtli** [comment]
is this even an issue

**Comment by FloranOtten** [comment]
Every other settings starts at off. The icon itself starts at nothing selected.

**Comment by Tlaltecuhtli** [comment]
https://github.com/tgstation/tgstation/blob/7d9ea2f3f606aa88278bbd3e495f3ca536e354a8/code/game/mecha/equipment/mecha_equipment.dm#L124
