### ISSUE TITLE
Cult blood beam fires wrong directions

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#44413]
#### Round ID:
Up-to-date local and Byond. Also noticed on local a few weeks ago while still on Byond 512.1467 (the safe one, before the firing directions bug). 

#### Reproduction:
Get the blood rites spell. Fill it with 500+ blood. Cast blood beam and click north of you. 

Repeat a few times because the first time it cast somewhat in the aimed direction for me, but not on consecutive tests. 

Result: The beams generally fire another general direction than aimed at. I get very varied results and I can't find a pattern:

I aimed north and it fired west. Then I ran away to refill the beam and aimed south but it fired east. Then I aimed east and it fired east. Then west and it fired east. Ran away to refill. Aimed north, fired southwest. Aimed east, fired southwest. Aimed south, fired southwest. Ran to refill. Aimed north, fired west. Aimed east, fired west. I walked a step right and then left. Then aimed west, and it fired west. Refilled and walked back to exact same spot. Still only fired west. Walked to a completely different spot and aimed east, but fired west. 

Expected result: The blood beams focus on the the direction you aim at.

**Comment by ATH1909** [comment]
Is this related to that bug with firing guns with the newest version of byond?

**Comment by Angustmeta** [comment]
Probably not.

**Comment by py01** [comment]
Reproduced, blood beam appears to always shoot upward regardless of where you aim

**Comment by Angustmeta** [comment]
Tested again today and it's still bugged

**Comment by Angustmeta** [comment]
Still broken. Spent some more time on it but this is just way too complex for a non-coder. The proc `/proc/mouse_angle_from_client` somehow stops working or something. 

https://github.com/tgstation/tgstation/blob/8f66088b0fe5b6f795022847b02dcd6bc4158326/code/modules/antagonists/cult/cult_items.dm#L801

https://github.com/tgstation/tgstation/blob/39e8bd721fe545b4dad1e8dea7363701a7003a6e/code/__HELPERS/mouse_control.dm#L1

**Comment by Angustmeta** [comment]
Fixed by #56012.
