### ISSUE TITLE
His Grace seem to be unable to ascend

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#44417]
I fed around 50 corpses to the damn thing on the private server and it would still nom me regardless

**Comment by 4dplanner** [comment]
Looking at the code, ascending seems to only make his grace get hungry less quickly. Is this not intended?

**Comment by 4dplanner** [comment]
Further, he won't ascend on localhost because:
```
	for(var/mob/living/C in contents)
		if(C.mind)
			victims++
```
his grace only ascends from victims with minds.

**Comment by HomocidlePancakes** [comment]
Weird. I begun getting messages that his grace was getting less hungry after hitting 25 corpse mark butohwell.
