### ISSUE TITLE
Anti-magic might be broken again?

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#44410]
Issue reported from  Round ID: 110182 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1470

I had a null rod variant in-hand and was still hit with a cult spell for some reason. It was a holy claymore I got from lavaland but from what I can tell it's no different to the standard null rod version.

**Comment by Whoneedspacee** [comment]
not a bug

https://github.com/tgstation/tgstation/blob/b109515f64c2886b9f25e4e308cf225da1ba003f/code/modules/mob/living/simple_animal/hostile/skeleton.dm#L79

**Comment by necromanceranne** [comment]
Thank fuck
