### ISSUE TITLE
Emergency Shuttle Console cannot be normally deconstructed when emagged after a blob is selected, but before the blob is announced

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#44412]
Round ID 110188

Was escaping when the console was emagged, but there was a blob that had not been announced yet, so the "error shuttle launching" happened, but shuttle was delayed indefinitely. Blob was defeated, and the console looked rather greyed out. I attempted to deconstruct it with my power drill, and it did nothing. When I broke it with my crowbar, it dropped a stack of 10 or so unmarked ID cards, and nothing more. Really spooky

**Comment by DaxDupont** [comment]
What

**Comment by Shirbu** [comment]
I know

**Comment by Shirbu** [comment]
It was almost nauseating how weird that is

**Comment by Shirbu** [comment]
Edited my description

**Comment by SethLafuente** [comment]
You can't destroy the departures console anymore at least... I don't understand how any of that even happened and I don't think any one will figure it out after 3 years have passed
