### ISSUE TITLE
Shadowmen get Fat in Shadows

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#44421]
## Round ID: 110229

Shadowmen get fat really fast in shadows, but die if they leave them. So they can't lose weight. Eventually you go into a food coma, which you'll never wake from, since if you are in shadows you just keep getting fatter, and if in light you just die.

**Comment by 4dplanner** [comment]
lol

**Comment by plapatin** [comment]
lol

**Comment by kriskog** [comment]
feature

**Comment by Tlaltecuhtli** [comment]
there is nothing different than normal human species about nutrion ru sure it was because u were a shadowperson

**Comment by wesoda25** [comment]
yeah

**Comment by Qustinnus** [comment]
shadowpeople's nutrition isn't different based on light.
