### ISSUE TITLE
Chair Based Teleportation

### ISSUE THREAD

**Issue by Kirefire** [tgstation/tgstation#44423]
Issue reported from  Round ID: 110235 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1454
If you grab a chair, sit on it. unbuckle from it and then move away from it. any other player who grabs and pulls the chair will cause the original player to instantly teleport back to the chair.

**Comment by bgobandit** [comment]
maybe related to https://github.com/tgstation/tgstation/issues/44151

**Comment by wesoda25** [comment]
Seems very similar to what I experienced

**Comment by Kirefire** [comment]
Fixed
