### ISSUE TITLE
Bags of holding can warp items to adjacent cross z-level turfs

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#44435]
Title, bags of holding can teleport items to other z-levels using their ability to warp its contents to nearby turfs, in this case tiles directly above or below work since they're technically 'adjacent'.

(There's a very similar issue to this that was already fixed involving cross z-level interaction, can't find the number at this moment for it however.)
#### Round ID: 110250
Tested and confirmed from Centcom. (A nice thank you to WJohn for letting me test this)

#### Reproduction:

- Get a bag of holding
- Build a camera on the supply shuttle and launch it.
- Build a security camera console close to the same x and y coordinates of the camera
- Line yourself directly up under a visible turf on Centcom and use the security console to view the area.
- Click-drag the bag of holding onto a tile with the same x and y coordinate to teleport the bag's contents there.

(Local testing pictures)
![Eastereggbasketa](https://user-images.githubusercontent.com/17460297/59175237-b0e0cd80-8b09-11e9-9ba6-b7522710e532.PNG)
![NTtoysRus](https://user-images.githubusercontent.com/17460297/59175239-b2aa9100-8b09-11e9-8c43-288e5d02dc6f.PNG)

This also may work using the thunderdome cameras provided you can line up with their vision from an entertainment monitor from the station z-level, which may require much more effort to set up. (Meteorshot and hand-tele portals)

I imagine it's best if Centcom isn't overrun by squatters, looters, infiltrated by the Syndicate, or even thought about for too long.

> Centcom seems to be the last stop for everything, the crew, the shift, and the truth.
The truth is surely out there somewhere, but this place just seems more like a red herring for those seeking answers rather than just some high end equipment.

**Comment by AnturK** [comment]
Nothing to do with adjacency, it's just shitcode in boh.
