### ISSUE TITLE
pipes are visible in mining

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#44434]
![image](https://user-images.githubusercontent.com/222630/59299471-8db93980-8c41-11e9-8982-e02cf972fe26.png)

**Comment by WJohn** [comment]
Known issue of the pipe rework, it's already fixed, going to have it updated on the server just as soon as actioninja finishes up his bugfixes.

**Comment by SpaceManiac** [comment]
@WJohn What rework are you referring to? Is it merged or testmerged?

**Comment by Dennok** [comment]
now the T - manifolds dont visible by t-ray or blueprints (if i dont garble the build)

**Comment by kriskog** [comment]
Fixed
