### ISSUE TITLE
decapitated catgirls do not have the ears on the sprite

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#44445]
title

**Comment by wesoda25** [comment]
i want to be able to out catheads on spears now!!

**Comment by bgobandit** [comment]
dupe https://github.com/tgstation/tgstation/issues/42397

**Comment by imsxz** [comment]
well 6 months later and its not fixed

**Comment by wesoda25** [comment]
its because no one gives a shit enough to fix it

**Comment by Dorsisdwarf** [comment]
We cant close  old issues just for being old sadly, closed as dupe.
