### ISSUE TITLE
The Crossbreeding Error code is triggering for the Pink Love Potion

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#44451]
Just summarizing my issues with xenobio. I've wasted at least 200 slimes in total, by repeating the steps for these special crossbreeding extracts, and I've ended up with the slime boiling away into nothingness, as that's how the error code goes.

Send Help. I can't trust these crossbreeds anymore.

N/A to a /tg/ server, but a down-stream using its codebase with no variations.

**Comment by Tlaltecuhtli** [comment]
if it disapears it usually means that it isnt even in the game, which combination were you using

**Comment by fludd12** [comment]
@Shadowflame909 Please confirm which extracts you were using, and which adult slime you were using. Dark blue **extracts** produce chilling crossbreeds, so in order to obtain the `Lovecraftian Megaman` gun, you would insert ten dark blue extracts into an adult green slime.

**Comment by Shadowflame909** [comment]
Oh. I put 10 green into the Big dark blue guys.

Fuck. 

The Docile potion one for sure isn't working though.

**Comment by fludd12** [comment]
I was able to make the Charged Pink extract, which produces a love potion. This is done by feeding an adult pink slime 10 yellow extracts. Is that what you mean?

**Comment by Shadowflame909** [comment]
Ok I think I've just been doing things too one tracked and this issue is human error
