### ISSUE TITLE
Space Carp can't emote anymore [EDIT: maybe all simplemob emotes are bugged]

### ISSUE THREAD

**Issue by ishitbyabullet** [tgstation/tgstation#44455]
Issue reported from  Round ID: 110345 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1453

When an admin spawned me as a carp yesterday (as of writing this), I was able to emote.

I can no longer emote now (as of that round ID). This annoys me since it USED to work yet now it doesn't. I tried hotkeys, me ", and IC tab however none of them worked.

edit: okay apparently space carps, holocarps, and the normal clown simplemob can't emote anymore either.

**Comment by HomocidlePancakes** [comment]
I always thought this was intended
