### ISSUE TITLE
Ghosts don't orbit anymore

### ISSUE THREAD

**Issue by MortoSasye** [tgstation/tgstation#44454]
Issue reported from  Round ID: 110324 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1467

Steps:
1. Be ghost
2. Try to orbit that sweet antag murderboning
3. Realize your ghost is humping them
4. Oh god oh fuck
5. Realize it humps other ghosts too
6. _**Oh god oh fuck**_

[https://i.gyazo.com/0e5a1c9a575f6f1f979d3823d899ae88.mp4](url)

**Comment by AnturK** [comment]
Fixed in #44438
