### ISSUE TITLE
Ice cream cone names are their path

### ISSUE THREAD

**Issue by Arianya** [tgstation/tgstation#44462]
## Testmerges:

#43148: '[s]Temp workaround for admins matching stickybans because of a byond bug.' by MrStonedOne at commit f34e61e42d
#43666: '[WIP] Game Mode - Natural Disaster' by RaveRadbury at commit c435089168

## Reproduction:

![image](https://user-images.githubusercontent.com/23403236/59303927-2d50e900-8c8f-11e9-87f0-3bf2df59ff0c.png)

**Comment by 81Denton** [comment]
@vuonojenmustaturska

**Comment by Barhandar** [comment]
Unless it re-broke, update your server already because the fix got merged.

**Comment by ExcessiveUseOfCobblestone** [comment]
alternatively have icecream trigger tinfoil hat phobia

**Comment by SpaceManiac** [comment]
Round 110369 was running revision 893b02022869af6746384afe487f0749cb000fb5 which means it re-broke

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/d0e573645d2c3df82982c1de3c0dfee698d9fc02/code/game/objects/items/robot/robot_items.dm#L399

really easy fix, just replace this with "vanilla"

**Comment by Arianya** [comment]
This isn't my first issue Cobby >:(

**Comment by SpaceManiac** [comment]
Good first issue *for someone to fix*

**Comment by Arianya** [comment]
I swear to god Maniac I'll slap you with a fish if you get between me and cobby when we're fighting

**Comment by Suicidalpickles** [comment]
/datum/reagent/consumable/vanilla icecream is my favorite flavor

**Comment by wesoda25** [comment]
i like moose tracks

**Comment by ExcessiveUseOfCobblestone** [comment]
a lovers' quarrel?
