### ISSUE TITLE
AI's can't talk through the holopad anymore

### ISSUE THREAD

**Issue by MortoSasye** [tgstation/tgstation#44471]
Issue reported from  Round ID: 110385 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1467

**Reproduction**
1. Be an AI
2. Try to talk through the holopad with .h like always
3. See yourself talking but realize that no one is listening to you

**Comment by ATH1909** [comment]
Is this related to the new hearing changes?
