### ISSUE TITLE
Explosions crashing clients

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#44488]
## Round ID:
#110449

BYOND Version: 512.1467

## Testmerges:
#43693 
#44338 

## Reproduction:
title
sm explodes
client starts crashing repeatedly, as well as on trying to connect to the server
somebody else in ghostchat mentioned that they crashed too at the same time

edit:
Update on this, nuke going off seems to be causing crashes for people too. Syndiebombs seem to be fine though, so probably only huge booms.

**Comment by Tlaltecuhtli** [comment]
someone blew up 6 ttvs 1 sceen away and i crashed

**Comment by kriskog** [comment]
Got the same issue, explosions seem to trigger it, and end of round grief has me crashing a lot. Also gibtonite. Haven't been able to reproduce locally, and it doesnt always crash when something explodes.

Started happening sunday/monday, on terry. Previously, no crashes for weeks.

**Comment by FloranOtten** [comment]
Every end of round, the moment a maxcap happens I crash.

**Comment by daklj** [comment]
small explosions also do
just crashed due to gibtonite

**Comment by AnturK** [comment]
Fix in 512.1471.

**Comment by timothymtorres** [comment]
> This is byond animate issue. Fix in 512.1471. Will keep this report open until i'm sure the fix is stable.

Pretty sure this issue is resolved now.  Feel free to reopen this if it's not.
