### ISSUE TITLE
Directional windows block vision when they are painted black

### ISSUE THREAD

**Issue by MortoSasye** [tgstation/tgstation#44489]
Issue reported from  Round ID: 110449 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1467

This bug caused an enormous death trap that killed around 10 people because they didn't realize they were walking to one.

Reproduction:
1. Place directional windows facing the wall 
2. Use a spray can with the black color on them 
3. Field of vision is reduced but you can still walk through it

![1](https://user-images.githubusercontent.com/38175176/59392189-ff71b000-8d33-11e9-8b6e-67595e4d1805.png)
![2](https://user-images.githubusercontent.com/38175176/59392196-039dcd80-8d34-11e9-9f58-78436db60c08.png)

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=3iZ9JRVmJ5o

Here's the video of the death trap (courtesy of imsxz): https://www.youtube.com/watch?v=xmYmfy8siy8&feature=youtu.be

**Comment by kopoba** [comment]
> 
> 
> https://www.youtube.com/watch?v=3iZ9JRVmJ5o
> 
> Here's a video of the creation and usage of the death trap (courtesy of imsxz): https://www.youtube.com/watch?v=xmYmfy8siy8&feature=youtu.be

This is so good. Dont think its a bug.

**Comment by Daxxed** [comment]
Has been an intentional feature for ages wew do you people even make maint traps.

**Comment by nemvar** [comment]
Feature but doesn't mean the way directional windows block view like that isn't retarded.

**Comment by Daxxed** [comment]
I ded

**Comment by SpaceManiac** [comment]
There is no easy way to implement directional window blocking, either this is a feature or directional windows should not be spraypaintable.

**Comment by Daxxed** [comment]
I remember reading this as a strategy/tip to make maint traps on the wiki, like two years ago.
How is this not an intentional feature ?

**Comment by Dorsisdwarf** [comment]
It's clearly not an intentional feature you mong, it's an obvious bug.
