### ISSUE TITLE
Had internals on with Syndicate Mask and Extended Capacity tank, but suffocated anyway

### ISSUE THREAD

**Issue by SkatesMcGates** [tgstation/tgstation#44492]
Issue reported from  Round ID: 110461 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1441

![Screenshot (42)](https://user-images.githubusercontent.com/17814086/59396918-c13ab780-8d58-11e9-8b1b-b3d69d3a00a3.png)

**Comment by nemvar** [comment]
Did you mess up the release pressure of the tank? Because I have never experienced/heard of a bug like this.

**Comment by Whoneedspacee** [comment]
tank pressure 0

omegalul

**Comment by HomocidlePancakes** [comment]
And he didn’t switch to combat mode on station

omegalul X2

**Comment by ATH1909** [comment]
Your oxygen tank is empty, buddy.

If I had to guess, you drained most of its air while flying around with your hardsuit's jetpack on.
