### ISSUE TITLE
Can't differentiate falsewalls with mesons

### ISSUE THREAD

**Issue by Suicidalpickles** [tgstation/tgstation#44504]
## Round ID:
#110513

## Testmerges:
#44338

## Reproduction:
Falsewalls show up as any other wall now when wearing mesons, they used to have a blank space like airlocks would.

Falsewall closed:
![Capture](https://user-images.githubusercontent.com/32374784/59455917-077c2f00-8dca-11e9-9722-04b99a968b65.PNG)

Falsewall opened:
![Capture2](https://user-images.githubusercontent.com/32374784/59455920-08ad5c00-8dca-11e9-97be-7584fdc551cb.PNG)

Distance shot, the airlock goes blank spaced but falsewall doesn't.
![Capture3](https://user-images.githubusercontent.com/32374784/59455996-2f6b9280-8dca-11e9-9317-bdfa33b688a1.PNG)

**Comment by py01** [comment]
was it ever really intended for mesons to see falsewalls as invisible?

**Comment by Barhandar** [comment]
Yes, that's one of the points of mesons.

**Comment by XDTM** [comment]
I'd call this a feature

**Comment by Suicidalpickles** [comment]
> 
> 
> I'd call this a feature

last time falsewalls were touched, it was mentioned that mesons should still be able to see them tho.

#43724 for reference

**Comment by Dennok** [comment]
not a bug but a feature
but i think false wall just very small lighted, so you can see it, if you remove dark.

**Comment by Dennok** [comment]
![scrnshot2](https://user-images.githubusercontent.com/7734424/59776943-5b03e680-92bc-11e9-9e83-10d4be036db8.png)
![scrnshot1](https://user-images.githubusercontent.com/7734424/59776944-5b03e680-92bc-11e9-9dc4-ecedbedf1517.png)
all work

**Comment by Dorsisdwarf** [comment]
Seems to be working as intended according to coders
