### ISSUE TITLE
All mechs are immune to Lava, not just the Firefighter 

### ISSUE THREAD

**Issue by zxaber** [tgstation/tgstation#44508]
## Round ID:
None, found in a test server

## Testmerges:
Testing my combat mech nerf PR, but nothing that should affect this.

## Reproduction:
- Make either Ripley model.
- Walk through lava on Lavaland.
- Mech is perfectly fine.

I'm not sure if this is intentional, but I don't recall any recent PRs targeting this. I distinctly remember the first time I was given a Ripley by Robotics as a miner, and having it catch fire when I touched lava. This was over a year ago, though, and I haven't thought to try it since. For the record, the MK-I _does_ catch the pilot on fire, but the mech itself is fine.

**Comment by Barhandar** [comment]
Meanwhile MK2 makes the user lavaproof just like Firefighter, which is clearly not intended.

Mechs themselves being lavaproof might stay (they're clearly intended to, going by descriptions, and lava isn't as hot as plasmafires mechs burn in), but they should absolutely ignite and cook non-lavaproof pilots.

**Comment by ExcessiveUseOfCobblestone** [comment]
what about other mechs or is this just specific to the rip

**Comment by zxaber** [comment]
It seems all mechs are currently lavaproof. If you deem this a bug, I can look into fixing it. I just wanted to make sure it wasn't intended first.
