### ISSUE TITLE
Client Crashing Construction using Chutes

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#44518]
Issue reported from  Round ID: 110570 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1470

In the constructors own words:
"its just 4 chutes launching into each other in a circle. there's no outlet, so it's ejecting out of the trunk. absolutely clueless as to why that would cause a crash"

Here is a picture of it partially deconstructed. The pen is where there would be another chute outlet.
![pen for reference](https://user-images.githubusercontent.com/40847847/59515894-7d37e600-8f03-11e9-9951-69588846fc46.png)

**Comment by AnturK** [comment]
It's byond issue with animate calls, Fix in 512.1471. I'll keep this open for a while until we're sure it's stable.

**Comment by AnturK** [comment]
Duplicate of #44488
