### ISSUE TITLE
Gibtonite Explosions can insta-kill/destroy all items

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#44528]
Issue reported from  Round ID: 110606 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1464

As the title says, I shot gibtonite twice at point blank, and it instantly killed me and destroyed all the items I was wearing. In the past, I've done the same thing, and only been knocked into crit if I was already low on HP.

**Comment by YPOQ** [comment]
I imagine you probably moved into the epicenter turf before the explosion started processing, which is pretty unfortunate, but I don't think it can be fixed short of removing the sleeps from explosion code.

**Comment by Dawson1917** [comment]
I just gave this a test and firing two PKA/cutter projectiles point blank into gibtonite has a slightly random amount of damage dealt (75 damage with no limbloss, 90ish damage with limbloss, 80ish with limbloss) and can delete the cutters/PKAs you were holding in your hands, but never everything you're wearing.
Were you wearing your explorer's webbing when this happened? It provides minor explosion resistance. Barring that, I'd expect it's what YPOQ suggested

**Comment by Hathkar** [comment]
Yeah, I was wearing explorer's webbing as well. I think I also reinforced my explorer's suit with 3 plates of goliath hide.

**Comment by kriskog** [comment]
Explosions have a chance of deleting your stuff, even from inside your bag. Not a bug afaik, just unlucky.
