### ISSUE TITLE
Engineering Hardsuit Ghosting in Inventory?

### ISSUE THREAD

**Issue by Tyromaniac** [tgstation/tgstation#44536]
Issue reported from  Round ID: 110631 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1470

![image](https://user-images.githubusercontent.com/222630/59549225-4a93ea80-8f0f-11e9-829b-da82c1b89f81.png)

I died to radiation sickness and was defib'd back to life and thrown into cryo. I believe that my suit was taken off before cryo, and then it was put back on me while I was inside of the tube. The issues started when I realized the suit was in my hands and I could not drop it or put it on. It then kept reappearing in my hands over and over again, and then it started having the same behavior in my vest slot, as shown in picture. Currently it just flickered off again. I was able to confirm through OOC comms that when it was in my hands, my hands were empty and when it was on my vest, I wasn't wearing anything that could be grabbed.

**Comment by ATH1909** [comment]
Could you hit stuff with it?

**Comment by Tyromaniac** [comment]
I didn't test to determine that. I think the steps I gave leading up to it may reliably reproduce the bug should I be correct of the cause. It may also have to do with cult, but I don't see why it would.

**Comment by TheBonded** [comment]
cleanup flagged tag please work
