### ISSUE TITLE
Xenobio slimes won't feed after awhile

### ISSUE THREAD

**Issue by steampunch** [tgstation/tgstation#44538]
## Round ID:
#110636

## Testmerges:
#44427 

## Reproduction:
After feeding slimes for awhile, they will suddenly refuse to feed. They just sit there, with live monkeys nearby. I'm not sure what causes this to happen, but it doesn't immediately occur. You can get more than one generation in before it happens.

In this round I just fed each one like usual. Eventually all slimes present quit feeding across all different tiers. Moving slimes didn't help, nor did putting in new monkeys. I couldn't find a way to fix it, making xenobio impossible. All of the monkeys ended up being sick with miasma diseases because of how much miasma xenobio tends to produce.

**Comment by Ty-the-Smonk** [comment]
Ive had this happen to me before but I dont know what would cause it

**Comment by Angustmeta** [comment]
An old rumor said they can befriend monkeys.

**Comment by tanory07** [comment]
Had this happen aswell!

**Comment by knacker48** [comment]
I just had a slime I was using to make rainbows stop eating. It was at 82% instability. 

This is hell

**Comment by kriskog** [comment]
Yeah, happened to me to day as well. Had several refuse to eat, just sat around the monkeys looking dumb. All from different generations of slimes, even some from the same ones.

**Comment by fludd12** [comment]
If this happens again, ask an admin to call slime proc `CanFeedon` with one argument, mob reference to monkey. Also ask the admin to list their `friends` variable. I may have caused this inadvertently when fixing the slimes-feeding-on-robots issue.

**Comment by kriskog** [comment]
@fludd12 
I came across this locally. CanFeedon for the monkey next to the slime returned 1, the friends list is empty. Slime was starving at the time, starter grey one. Other two were working fine.

**Comment by fludd12** [comment]
Good to know I didn't directly cause it, at least. I'll look at this as soon as I'm not at risk of vomiting today.

**Comment by Memesaredreams** [comment]
Had this happen aswell, round ID 111232
