### ISSUE TITLE
[Clock Cult] The eminence can empty bags

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#44532]
Eminence can empty bags with drag click, if anyone even cares about the mode still.

**Comment by HomocidlePancakes** [comment]
All "eyes" can do that, escept for AI one

**Comment by HomocidlePancakes** [comment]
@py01 You should remove that Clock Cult tag

**Comment by wesoda25** [comment]
Don’t bother reporting it, no one is maintaining clockcult and its completely broken

**Comment by ATH1909** [comment]
What about Yalp Elor and (blood cult) dark spirits?

**Comment by YakumoChen** [comment]
dark spirits are treated as ghosts, not eyes.
