### ISSUE TITLE
Leaving/entering z-levels with a jetpack may crash your game whenever you are close to a large ruin/station.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#44546]
Reproduction: 
1)Get a big jetpack
2)Travel space for around 20 minutes to gurantee the bug to occure
3)Return to the station z-level
4)Suffer incredible lag that will most likely crash your game

This bug can be healed by closing the game and rejoining. Reconect doesn't work. It also has a weird side-effect of you being able to move at jetpack speed in 0-G even without a jetpack. That can be fixed using a slower jetpack, like the internal hardsuit one.

**Comment by Tlaltecuhtli** [comment]
>. It also has a weird side-effect of you being able to move at jetpack speed in 0-G even without a jetpack.
was this temporary or what?
i know that you can keep sanic speed until the no grav alert doesnt get removed from your screen

**Comment by HomocidlePancakes** [comment]
>That can be fixed using a slower jetpack, like the internal hardsuit one.

Can you read Tlalnerd?

**Comment by Tlaltecuhtli** [comment]
i mean were you able to speed up in not space while the no grav icon was up or not

**Comment by HomocidlePancakes** [comment]
>It also has a weird side-effect of you being able to move at jetpack speed in 0-G even without a jetpack.

Yes, I could run around in zero gravity, without a jetpack, not necesairly in space at meth speed.

**Comment by SpaceManiac** [comment]
What BYOND client version? Round ID?

**Comment by HomocidlePancakes** [comment]
1)512.1454
2)No round ID because I get it pretty much every time I go out and explore space

**Comment by SpaceManiac** [comment]
1) Does the problem persist if you update to 512.1471?
2) If something happens all the time, try to just give one round ID as an example, it's important for cross-referencing logs/version numbers/timestamps/etc. to narrow down plausible causes.

**Comment by HomocidlePancakes** [comment]
Will do I guess

**Comment by HomocidlePancakes** [comment]
Reproduced on yog with the newest byond. If you want I can do it on TG and post the round ID.

Also I thought up a better way of explaining it. It causes lag when you move, that lag freezes your screen and has your char move at the direction you were moving causing even more lag untill you either hit something and stop, or move off the z-level.

**Comment by SpaceManiac** [comment]
Sounds really similar to a BYOND bug that's been "fixed" three times already. Unfortunately it's not convenient for me to test it right now.

**Comment by kriskog** [comment]
Can confirm the lag happens like his last comment, although I usually only see it on station z. I also see it when max zoomed out ghost, and trying to place ships (pirate cutter, nukie shuttle) on station z. 
All the above might not be issues related to each other, but maybe helps in reproduction. Can confirm its a thing on 512.1471.

**Comment by HomocidlePancakes** [comment]
You sure it’s a 100% byond issue? Doesn’t make sense that you would be able to move at meth speed in 0 G just because of byond.

**Comment by SpaceManiac** [comment]
Maybe, and maybe going 2fast makes it worse, but the crash is definitely a BYOND issue

**Comment by Dennok** [comment]
About this crash, i got it when use camera console (shuttle random destination placer), on the 512.1471.
I downgrade BYOND to 512.1460 and this help with crash,
 but anyway i have laggs in some places like shuttle docks, especially when i try to place custom dock near escape shuttle, and some time microlaggs near docks.

**Comment by Mooshimi** [comment]
Cleanup due to us being on 514 now, and I haven't been able to reproduce at all.
