### ISSUE TITLE
Using Ctrl+"letter" to quicksearch may make you unable to move occasionaly

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#44545]
Weird bug. Happens around 1/3 of the time ctrl+"letter" is being used to search. Suprisingly enough gets fixed by pasting anything in to the chat box at the bottom of the screen with ctrl+c.

**Comment by SpaceManiac** [comment]
> Suprisingly enough gets fixed by pasting anything in to the chat box at the bottom of the screen with ctrl+c.

Probably the game just thinks Ctrl is stuck pressed down? When held Ctrl causes you to turn instead of move.

**Comment by HomocidlePancakes** [comment]
Wait fuck. This whole time I thought you needed ctrl+"letter" to quicksearch, but you need just the letter for that. This was a massive brainfart
