### ISSUE TITLE
non binary gender option makes your character show up as "unknown" when examined

### ISSUE THREAD

**Issue by vuonojenmustaturska** [tgstation/tgstation#44554]
21:24:23: Laserdog/(Chesse): i need to report a bug but oranges gitbanned me
21:58:44: Client disconnected.
22:03:11: Client reconnected.
22:11:47: PM From Naksuasdf/(blobbernaut (632)): which bug 
22:12:30: Reply PM from-Laserdog/(Chesse): using the non binary gender option makes your character show up as "unknown" when examined even if you have an id equipped and nothing covering your face

**Comment by Whoneedspacee** [comment]
feature nonbinary people are the new meta

**Comment by PKPenguin321** [comment]
this is actually social commentary about how nonbinary people are often regarded as unseen by society, feature

**Comment by wesoda25** [comment]
Shaps hates the non-binary!!!

**Comment by Tlaltecuhtli** [comment]
they are unknown until they specify their preferred pronoums

**Comment by Daxxed** [comment]
Literally who ?

**Comment by Shapsy** [comment]
what

can you be more specific with how this issue manifests? I've examined myself quite a lot with plural gender and I've never been unknown when I shouldn't be

**Comment by Timonkeyn** [comment]
not a bug
