### ISSUE TITLE
Female-unique jumpsuit sprites are broken.

### ISSUE THREAD

**Issue by nemvar** [tgstation/tgstation#44562]
#44530 broke this, probably.

Equip any jumpsuit with a female unique sprite as a woman and it's just invisible. Very cool.

https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/carbon/human/update_icons.dm#L129

I think that's probably the relevant code.

Examples of jumpsuits with female unique sprites would be the prisoner uniform or the formal assistant's uniform.

**Comment by Wilchenx** [comment]
this is what happens when you merge PR's without testing

**Comment by nemvar** [comment]
Apparently not all female jumpsuits are broken. The black jumpsuit works fine, even though it has a female sprite.

**Comment by FantasticFwoosh** [comment]
> this is what happens when you merge PR's without testing

Or draft/regular reviewing properly.

**Comment by optimumtact** [comment]
are you sure they're not just missing their sprites

**Comment by Shapsy** [comment]
Pretty sure agender didn't cause this, it would just default to male sprites as a result of line 130, this must have already been like this
