### ISSUE TITLE
Records list sex as "plural" for gender-neutral characters

### ISSUE THREAD

**Issue by erwgd** [tgstation/tgstation#44560]
## Round ID:
110689

## Testmerges:
#43148

## Reproduction:
Agender and gender-neutral characters use the plural gender, so their medical and security records have "plural" under sex. This is generated automatically and players cannot set a record's sex to anything other than male or female.

**Comment by 4dplanner** [comment]
lol

**Comment by HomocidlePancakes** [comment]
lol

**Comment by Whoneedspacee** [comment]
the amount of issues this pr has caused is ridiculous.

**Comment by optimumtact** [comment]
that is their gender, so this isn't a bug

**Comment by optimumtact** [comment]
oops missed the bit about the record

**Comment by Trazen4** [comment]
Seriously? This isn't the server for this. It's not a hugbox and people don't care about your pronouns.

**Comment by optimumtact** [comment]
fragile lmao

**Comment by MegaEmpirical** [comment]
Sex is binary, save for intersex which the game doesn't have. Sex and gender are not the same thing but are often used interchangeably even though they're different.

**Comment by optimumtact** [comment]
there are four, it's right there in the byond ref

**Comment by Shapsy** [comment]
I'm on it

**Comment by adamkad1** [comment]
herms when XD

**Comment by optimumtact** [comment]
wyci
