### ISSUE TITLE
pAI's can block bullets

### ISSUE THREAD

**Issue by OmegaShoots** [tgstation/tgstation#44578]
Round ID: 110773

pAI's can be used as free bullet sponges with no downside.

**Comment by kriskog** [comment]
The downside is they take damage and lose holochassis for a while.

**Comment by HomocidlePancakes** [comment]
Dupe of #44143

**Comment by OmegaShoots** [comment]
@kriskog that's not a downside that's just a timelimit on how much they can troll you and protect their master
They should not be able to interact with things physically, it's a reason why they can't drag

**Comment by Dorsisdwarf** [comment]
This is kind of a dupe, they're meant to be small objects but crawling ruined everything forever
