### ISSUE TITLE
contained teslas tend to fall from the cargo shuttle and get lost in space

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#44596]
110823

**Comment by ninjanomnom** [comment]
how many times must you be told to explain issues in detail

**Comment by necromanceranne** [comment]
I found that the tesla had fallen off the shuttle. It was contained inside the cargo shuttle but for some reason slipped off it without the barriers dropping or the shuttle breaking. It just ended up on a random z-level in space.
