### ISSUE TITLE
Hivemind's awakening vessels and objective giving is not logged

### ISSUE THREAD

**Issue by Arianya** [tgstation/tgstation#44603]
## Round ID:
110831

## Testmerges:
#43148: '[s]Temp workaround for admins matching stickybans because of a byond bug.' by MrStonedOne at commit 71196ecf2d

## Reproduction:
Have a hivmind create an awakened vessel, and give them an objective. There's an admin alert but no logging in game.log or attack.log for it.

**Comment by SpacePrius** [comment]
made a PR that fixes this bug.
