### ISSUE TITLE
You can change your ghost name at will.

### ISSUE THREAD

**Issue by nemvar** [tgstation/tgstation#44601]
## Reproduction:

Step 1: Die.
Step 2: Go into Preferences and change your name.
Step 3: Click "Restore character name" in the ghost tab.
Step 4: Profit.

Not really a bug or something, but I don't think that's what the restore character name verb is supposed to be used for. It's somewhat funny, so please no remove.
![ided1](https://user-images.githubusercontent.com/47324920/59627925-ae045f00-913f-11e9-9f54-879651387a77.PNG)
![ided2](https://user-images.githubusercontent.com/47324920/59627932-b0ff4f80-913f-11e9-8a63-478b8b843d87.PNG)
Sorry for the eye squinting >w<

**Comment by Dawson1917** [comment]
time to upset admins
![image](https://user-images.githubusercontent.com/51552884/59642742-703a2180-91a5-11e9-8e7d-da6e2d68488c.png)

**Comment by adamkad1** [comment]
why report if want no remove?

**Comment by YakumoChen** [comment]
this doesn't change your dsay name though

**Comment by Daxxed** [comment]
This has been a thing since forever.
People want to switch to their static while in deadchat, keep it.
