### ISSUE TITLE
Decapitated heads from any source can be used to clone suicides with roundstart parts/autoprocess

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#44614]
Its suicide, you shouldnt be cloneable

**Comment by HomocidlePancakes** [comment]
Max level cloner can revive suiciders and it’s a feature. Nerd.

**Comment by adamkad1** [comment]
i dunno, do we have max level cloner at roundstart?

**Comment by lordpidey** [comment]
Likely also exists for gas pump suicides, if they happen to shoot out your brain.

**Comment by Dorsisdwarf** [comment]
Updated title due to #44644
