### ISSUE TITLE
cult artificer heals purified constructs when hitting them

### ISSUE THREAD

**Issue by Teepeepee** [tgstation/tgstation#44622]
Issue reported from  Round ID: 110897 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])
#44473: '[TESTMERGE] Band-Aid Fix for fugitive shuttle movement' by tralezab at commit 2eb8fbc936
#44507: '[READY] Replaces mining points with money, adjusts gulag payout' by vuonojenmustaturska at commit 564c3f1e7d
#44338: '[TMC] experimental_dissection available at roundstart' by japisd at commit b3f1622c77
Reporting client version: 512.1471
just ruined my teammates' lives endlessly healing one of these lmao

**Comment by HomocidlePancakes** [comment]
Why are you trying to kill shit as an artificer?

**Comment by Teepeepee** [comment]
base was being raided and we had nowhere to run, would you stay put waiting for your turn to die or join the melee?

**Comment by HomocidlePancakes** [comment]
I would block off the hole and have other cultists kill shit. Your melee damage is laughable

**Comment by wesoda25** [comment]
Constructs not being able to kill other constructs is funny but not intentional.

**Comment by adamkad1** [comment]
> Constructs not being able to kill other constructs is funny but not intentional.

arent artificers repair only on constructs tho? making them not repair 'enemy constructs' requires bonus bullshit

**Comment by wesoda25** [comment]
> > Constructs not being able to kill other constructs is funny but not intentional.
> 
> arent artificers repair only on constructs tho? making them not repair 'enemy constructs' requires bonus bullshit

yeah which means id have to recode attack stuff to fix, which makes it a headache ughhh

putting a fix PR for some purified related stuff rn but i think thatll be seperate

**Comment by Dennok** [comment]
Maebe add hit ability to unpurifi constructs in attack?

**Comment by wesoda25** [comment]
@dennok super late response but im fixing it now, think thatd be a bit OP
