### ISSUE TITLE
Disabler stamina regeneration

### ISSUE THREAD

**Issue by bigfatbananacyclops** [tgstation/tgstation#44626]
this bug has been known since the new disabler/stamina change. It seems that when you are knocked down by disablers, you will stay down for 7 seconds or more until you regenerate your stamina to get up, apparently it instantly regenerates your stamina, as in, if you were disabled, then batonned constantly, you will get up as soon as the disabler stamina damage effects ends on you, it will ignore the previous stuns on you or any other stun, you just instantly regenerate. This has a big impact on combat.  I also believe the disabler/stamina PR somewhat messed with rubbershots making them way more weaker

**Comment by Fikou** [comment]
isnt it to prevent chainstunning with disable someone and then baton so they wont ever wake up

**Comment by SkeletalElite** [comment]
#44361 was supposed to fix this I thought.

**Comment by 4dplanner** [comment]
should be already fixed, are you sure the server was updated?

**Comment by 4dplanner** [comment]
>I also believe the disabler/stamina PR somewhat messed with rubbershots making them way more weaker

rubbershot was only buffed by my PR, I think you are thinking of #43572

**Comment by AnturK** [comment]
Ping if this happens again, going to assume it was already fixed.
