### ISSUE TITLE
Floor tiles can produce infinite air

### ISSUE THREAD

**Issue by OmegaShoots** [tgstation/tgstation#44623]
Round ID: 110897
Placing or crowbar'ing up floor tiles causes them to release air for some reason, and is repeatable infinitely.
This has actually been around for months but I just never got around to reporting it.

**Comment by SpaceManiac** [comment]
thought this was reported already. boy oh boy would I like to see this fixed

**Comment by vuonojenmustaturska** [comment]
Should be a fairly easy fix with the inherit air changeturf flag I added ages ago, I can take a look later today

**Comment by 81Denton** [comment]
Manipulating tiles with an RCD causes the same issue, it's especially noticable on lavaland or in space.

**Comment by MegaEmpirical** [comment]
I noticed this the other day when fixing a breach but wasn't sure what the hell was going on.

**Comment by Daxxed** [comment]
> 
> 
> Manipulating tiles with an RCD causes the same issue, it's especially noticable on lavaland or in space.

I ded

**Comment by kriskog** [comment]
If a room is plasma flooded, just remove the floortiles. It resets atmos above it to normal air. Then if any is left, replace the floortiles and it happens again.

**Comment by Daxxed** [comment]
This is the mechanic that causes you to move around during drake's lava arena too, as the floor/basalt is constantly replaced with lava and back, atmos changes and tries to push you around.

**Comment by Dennok** [comment]
Reopen it please @optimumtact .
