### ISSUE TITLE
Trying to dock whiteship while another shuttle is docked causes it to irreversibly become stuck

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#44637]
Issue reported from  Round ID: 110934 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1470

Tried to dock whiteship at the station, but hunter ship was already docked. This caused the whiteship to get stuck at deep space, listed as 'custom location'.  Pressing any travel destination displayed the departure message but nothing else happened. Shuttle manipulator displayed the ship to be in transit.

**Comment by kriskog** [comment]
Dupe of #44605

There is a more general shuttle bug going on, not related to the docked shuttle.

**Comment by FloranOtten** [comment]
Dupe
