### ISSUE TITLE
you can clone suicides by decapitating them, with any parts and if autoprocess is on or not

### ISSUE THREAD

**Issue by plapatin** [tgstation/tgstation#44644]
## Reproduction:
step 1: suicide (box suicide works for this)
step 2: decapitate
step 3: stick head in cloner (dont take out the brain)

**Comment by adamkad1** [comment]
i did dis https://github.com/tgstation/tgstation/issues/44614

**Comment by Dorsisdwarf** [comment]
Closed as duplicate issue.
