### ISSUE TITLE
Cable Layer Broken

### ISSUE THREAD

**Issue by halitosisman** [tgstation/tgstation#44649]
Issue reported from  Round ID: 110960 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

-Grabbed cable layer with both hands.
-Walked around.
-no cables placed.

**Comment by WJohn** [comment]
likely just smart cables PR. it's not intuitive that it's just for pipe cleaner stuff, it really should be moved to new cables and given a specific purpose there.

**Comment by Dennok** [comment]
i think this is brocken here https://github.com/tgstation/tgstation/commit/14e68bd66ab919c5b714b1c65c6499529e5e08b5#diff-318c6dc1b6d4c5efd2c0bbd522a42351
