### ISSUE TITLE
Abductors can only do basic surgery

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#44652]
## Testmerges:

Abductor scientists should be able to do the advanced surgeries, but are currently only able to do the basic ones. This may have happened in #43820.

**Comment by XDTM** [comment]
It's tied to the antag datum now; were you a normal abductor or one made artificially?

**Comment by kriskog** [comment]
I reproduced locally making myself scientist via TP. Surgery checks mob traits, antag datum gives trait to mind. Could be the cause of this, although someone else would have to verify.
