### ISSUE TITLE
Plasma fixation allows infinite healing without a liver

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#44650]
Issue reported from  Round ID: 110967 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1467

Get a plasma fixation virus with a buffed healing stat, and then remove your liver after downing some plasma. You now have infinite plasma fixation healing that is capable of outhealing the toxin damage from the lack of a liver, and will constantly be healing you due to the plasma in your system that will never metabolize because you do not have a liver. Seems unintentional, so I have reported it.

**Comment by Whoneedspacee** [comment]
more liver bugs yay

**Comment by granpawalton** [comment]
Would probably work with water and tissue hydration

**Comment by ATH1909** [comment]
> Would probably work with water and tissue hydration

Actually, it doesn't- tissue hydration removes water from your system even if you aren't metabolizing it.
