### ISSUE TITLE
Nanite Cloud Controller filling up despite removing programs.

### ISSUE THREAD

**Issue by robotv56** [tgstation/tgstation#44667]
So I guess you can't make mistakes with a nanite cloud, because if for example you install 15 programs, uninstall 5, and install another 5, you are full and you can't add more. I think when you uninstall a program it doesn't affect the internal count of programs or something. You are capped at 20 programs installed, regardless how many you uninstall.

I guess until this is fixed I just won't make ANY MISTAKES.

**Comment by ExcessiveUseOfCobblestone** [comment]
@XDTM

**Comment by robotv56** [comment]
Unless I'm mistaken I think this is a separate issue from the voice sensor not uninstalling.

**Comment by robotv56** [comment]
Interesting, I'll attempt to reproduce in the coming days, but for now my work week has started.

**Comment by ExcessiveUseOfCobblestone** [comment]
reopen issue if it's still going
