### ISSUE TITLE
Bonfires Can't Ignite

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#44674]
## Round ID: 111033

Welder and firebrand wouldnt ignite the fire on lavaland for ash lizards, admin dropped a fireball on it and that didnt do anything. Probably caused by @nemvar

**Comment by MegaEmpirical** [comment]
I thought I was an idiot who didn't know how to light them. This makes more sense now.

**Comment by nemvar** [comment]
Can not reproduce. I also didn't even touch the bonfire code.

**Comment by wesoda25** [comment]
Huh

**Comment by nfreader** [comment]
Reopen if you see this again
