### ISSUE TITLE
Soulstone shards can be purified multiple times. Results in another purified prefix being added to the shade

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#44678]
## Round ID: #111038
Can be easily reproduced by just spam clicking a bible onto a soulstone shard. I used the chaplains soulstone shard and it had a shade in it prior to purifying. End result was a Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Purified Shade

**Comment by wesoda25** [comment]
Thats funny I think I know how to fix ill try and get pr up later today

**Comment by ATH1909** [comment]
@wesoda25 Keep in mind that currently, you have to re-purify a soulstone to purify the sprite of the shade inside of it if you purify the soulstone before using it on a corpse/picking up a shade with it. Just thought that that'd be relevant for your upcoming PR.

**Comment by wesoda25** [comment]
Im aware of that too and plan to fix it

**Comment by Dennok** [comment]
just name it from name = "Purified [initial(name)]" not name = "Purified [name]"

**Comment by wesoda25** [comment]
I just made it only possible to purify once by using if(!SS.purified)
