### ISSUE TITLE
Gas mask dont filter gases.

### ISSUE THREAD

**Issue by Dennok** [tgstation/tgstation#44683]
## Round ID:
Test it on latest build on 44646 pr

## Reproduction:

Take gas mask up (with no tank) and walk to room with plasma or n2o.
Fall to sleep or be toxed.

**Comment by Tlaltecuhtli** [comment]
https://github.com/tgstation/tgstation/blob/74b7c45303597eedf8f3cdc0ecdd24b0cedca656/code/modules/clothing/masks/gasmask.dm#L9

no one said it 100% blocks

**Comment by Dennok** [comment]
#40940
#19339

**Comment by kriskog** [comment]
The description of the gas mask seems to indicate its not supposed to:
![image](https://user-images.githubusercontent.com/33292112/59843453-e337c980-9358-11e9-82e7-b4d7111132a8.png)

**Comment by Tlaltecuhtli** [comment]
placebo

**Comment by Akrilla** [comment]
The examine text literally says this lol

**Comment by Dennok** [comment]
> https://github.com/tgstation/tgstation/blob/74b7c45303597eedf8f3cdc0ecdd24b0cedca656/code/modules/clothing/masks/gasmask.dm#L9
> 
> no one said it 100% blocks

how to you do this?

**Comment by nfreader** [comment]
Neat! I never knew this!
