### ISSUE TITLE
Bugged Russian Helmet

### ISSUE THREAD

**Issue by AdamBlue9000** [tgstation/tgstation#44686]
Issue reported from  Round ID: 111053 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1466

https://gyazo.com/10e984eea6a26f36e524c553c03e5447

The Russian helmet cannot, in fact, hold a bottle of vodka.

**Comment by nfreader** [comment]
Looks like this got fixed!
