### ISSUE TITLE
Baseturf Editors aren't working.

### ISSUE THREAD

**Issue by ishitbyabullet** [tgstation/tgstation#44702]
Baseturf editors seem to not work as they will still blow up into space if an explosion occurs. The only exception I've cared to notice is beach/water plating tiles when it has the beach baseturf editor.
![dreammaker_2019-06-20_13-06-49](https://user-images.githubusercontent.com/29403316/59868370-c900ea00-935e-11e9-9d2d-c4c8c5bd7f02.png)
![dreamseeker_2019-06-20_13-06-39](https://user-images.githubusercontent.com/29403316/59868377-cb634400-935e-11e9-923b-540059e24ac0.png)

[Another example of it not working by Wjohnston](https://cdn.discordapp.com/attachments/326831214667235328/591314027003510794/unknown.png)

**Comment by WJohn** [comment]
this isn't specific to away missions for anyone wondering, i also saw this happening in the space bunker ruin (the one with a million beans and built into an asteroid).

**Comment by Dennok** [comment]
Lavalend have this problem too? or level baseturf owerride it?

**Comment by SpaceManiac** [comment]
> Lavalend have this problem too? or level baseturf override it?

Lavaland's z-level baseturf is set to lava, which means it should be safe from this problem.

**Comment by Dennok** [comment]
right, i check it now

**Comment by Dennok** [comment]
as i see only in syndi base Baseturf Editor propertly work

**Comment by Dennok** [comment]
i find problem, something lost /turf/baseturf_bottom on the 2 position in the baseturfs and this creates space instead of asterion what stay on 1
