### ISSUE TITLE
chasms spawing in bad places

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#44718]
Round ID: 111153

![image](https://user-images.githubusercontent.com/222630/60319146-59749700-992a-11e9-9771-aa3d79d98205.png)

**Comment by HomocidlePancakes** [comment]
I died to that too.

**Comment by nemvar** [comment]
![image](https://user-images.githubusercontent.com/47324920/59963924-267d6e00-94fa-11e9-8ba1-7e3afe73a9c8.png)

**Comment by Dennok** [comment]
It not a bug, But i think better to it take some walls too. To make integral pit
