### ISSUE TITLE
Syndicate ranged NPC’s broken and wild west lighting

### ISSUE THREAD

**Issue by bigfatbananacyclops** [tgstation/tgstation#44713]
right so, whenever one of the ranged npcs with smg or a pistol gets started, they will only fire at the northern direction, not at you. Happened to see this at the gateaway in wild west, the lightning is also messed up since i can pretty much see everything, im very sure it isn’t like this.

**Comment by Dennok** [comment]
I think here already fix for it #44700

**Comment by kriskog** [comment]
The aim is fixed, and wild west is just an outdated map. Has some broken guns and stuff too.

**Comment by timothymtorres** [comment]
The guns in the wild Wild West are supposed to fire blanks according to #52672

The lighting issues were affecting all the gateway away missions and should have been fixed.
