### ISSUE TITLE
Lighting bug

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#44724]
Became holopara, rerolled while disconnected, lighting was fucked, Not fixed by reconnecting, clearing cache, or reinstalling byond. It gets fixed if you become alive again.
![d748f4358850e827dccd5fbae3820e06](https://user-images.githubusercontent.com/28164826/59949501-7f80cf80-9430-11e9-92ed-663b32adf38a.png)

**Comment by Dennok** [comment]
Now last version of BYOND have problems and bugs.
Better use some downgraded version.
