### ISSUE TITLE
Easily Stolen Techfabs

### ISSUE THREAD

**Issue by Jessen21** [tgstation/tgstation#44732]
Issue reported from  Round ID: 111228 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471

It seems to be that techfabs are far too easy to steal, as someone just dominantly took ALL the techfabs they could get to, Plus the spares. We need ways to replace them.

**Comment by HomocidlePancakes** [comment]
Have you considered the option of looking after your job-critical equipment that is so much susceptible to theft by the crewmembers who aren't a part of your department? After all, if it's so important you, then why aren't you taking care of it?

**Comment by Tlaltecuhtli** [comment]
ic issue

**Comment by Jessen21** [comment]
thats the trouble, trying to keep them protected when a greytide hits, or they pick up an RCD? It would be nice if we just had some solution in case they DO grab every techfab we have. Admitedly this is a case of a group self-antaging.

**Comment by Rowelll** [comment]
Pray for techfab boards or next time learn to protect important equipment.

**Comment by HomocidlePancakes** [comment]
Wait a second... You say they can TEAM UP? WOW! If only that option was avaiable to you! Man, that would make dealing with them so much easier!

**Comment by Time-Green** [comment]
There’s spare techfabs in the head’s lockers

**Comment by HomocidlePancakes** [comment]
He managed to get the spares stolen too

**Comment by GravitronBlue** [comment]
Completing the tide-board challenge isn't too difficult when you've got all access, and the lathes on most stations are only behind a single door, heads also never seem to bother moving their spare boards from their locker unless its needed.
Overall I'm still curious to know just how this heist of stealing every lathe circuit happened.

For now there's still a few ways to can get another RnD set, though they require luck and some searching. In particular there's two space ruins being the Russian derelict and the ancient/charlie station, plus the liberator's legacy kit found in the free-golem ship's mining vendor. (Which includes a full set of RnD lab circuits and can be repeatedly bought)

Keep in mind that all three of those places give you an omni-lathe, which completely negates whatever purpose departmental lathes were meant for. They're also risk free to get if you want to avoid provoking security.
