### ISSUE TITLE
bad moodlet overlay

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#44731]
![1](https://user-images.githubusercontent.com/33834933/59960886-b2c66b80-94cf-11e9-8b86-fad0774b8d14.png)

moodlet was giving an orange color even if i was fine

111230

**Comment by HomocidlePancakes** [comment]
That means that it's slowly faltering you nerd.

**Comment by ATH1909** [comment]
The glow around the face shows your sanity, while the color of your face shows your mood. This is intended.

**Comment by nfreader** [comment]
Not a bug but thanks for the report!
