### ISSUE TITLE
When someone is in cryo the game lagged like shit

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#44734]
Issue reported from  Round ID: 111236 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471
When someone is in cryo the game lagged like shit, probably related to overlays.

@nicbn related to your PR?

**Comment by nfreader** [comment]
PR in question is #44281

**Comment by nicbn** [comment]
@nfreader OP reverted my PR in #44745, this should be fixed?

**Comment by nfreader** [comment]
Oh, yes! I misread all that. @DaxDupont please reopen if you see any more issues with lag near cryo pods
