### ISSUE TITLE
Posibrains don't have policy support

### ISSUE THREAD

**Issue by Shapsy** [tgstation/tgstation#44758]
## Reproduction:
Seems posibrains don't have a definition for get_policy_keywords that allows them to use the Show Policy verb since they have guiding flavortext 

![dreamseeker_2019-06-22_23-51-03.png](https://i.imgur.com/JnawTFH.png)

![dreamseeker_2019-06-22_23-56-25.png](https://i.imgur.com/xQlhfTD.png)

I feel like it probably should. If someone else confirms that they should, I'll work to add it tomorrow

**Comment by AnturK** [comment]
You'd need to check for container in brainmob get_policy_keywords, since posibrain itself is not the mob.

**Comment by Shapsy** [comment]
Correct, it's the brain thingy
