### ISSUE TITLE
Purified shades can be cultists

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#44751]
It seems that sharding a cultist with a purified shard makes a cult aligned purified shade

**Comment by ArcaneMusic** [comment]
On a similar note, they can't invoke runes but WERE summoned on cult leader's mass recall.

**Comment by ATH1909** [comment]
Did you purify the soulstone before or after you sharded the cultist (or both?)?

**Comment by py01** [comment]
purifying before sharding makes a cult shade, purifying after sharding makes a purified shade

**Comment by wesoda25** [comment]
should be easy enough to fix one sec
