### ISSUE TITLE
Dropper makes stuff disappear

### ISSUE THREAD

**Issue by Bidux27** [tgstation/tgstation#44765]
## Reproduction:
I was the virologist. I was trying to make stable uranium gel, so I grinded uranium and silver in different beakers and I was mixing them up in a different one with the dropper. 
After some time with no problems from the dropper at all, I set the dropper to one unit to take the liquid plasma, it took 1u and itdropped 0.7768something. This happened even with the silver, took 5u and dropped 4.854something.
I noticed that if I was to put the ridiculous amount back in the bottle and kept trying pouring 1u of plasma back in the beaker, the amount dropped began rising, from 0.77etc to 0.81etc and so on until it went back to one. The same happened with the silver, after some cycles it was back to normal.
For the uranium there was no problem at all and this issue was the same even after changing the dropper. When I fixed the problem for one dropper though, it was good for all the others too.

First time I report a bug, I hope I've been specific enough.
Cheers

**Comment by nfreader** [comment]
Dupe/continuation of #31206!

**Comment by nemvar** [comment]
Indeed a dupe
