### ISSUE TITLE
Clockwork Armor doesn't actually have armor

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#44763]
It seems to not be using the same shit for armor as literally anything else so it just has no armor. I'm not a coder so I can't really describe this in a sophisticated way just have a look int the variables and then compare it to like anything else and you'll see what I mean. 

I mean, clock is dead but still if we're gonna have it for admemery it would be worth fixing.

**Comment by Nickkoranda** [comment]
`Runtime in human_defense.dm, line 34: undefined proc or verb /list/getRating(). `

**Comment by py01** [comment]
are you sure you were looking at clockwork armor and not bronze armor? clockwork armor seems to have armor vals https://github.com/tgstation/tgstation/blob/fbaedee1501daa3ae79109ffb6d4bc53144f3d6d/code/modules/antagonists/clockcult/clock_items/clockwork_armor.dm

**Comment by ExcessiveUseOfCobblestone** [comment]
i don't think this is a GFI
