### ISSUE TITLE
new cable disconnect bug

### ISSUE THREAD

**Issue by Dennok** [tgstation/tgstation#44768]
Issue reported from  Round ID: 111364 (/tg/Station Sybil-2 [ENGLISH] [US-WEST] [LOWPOP] [100% LAG FREE])

Reporting client version: 512.1460

## Reproduction:
cut cable under terminal
terminal still connected

![image](https://user-images.githubusercontent.com/7734424/59979736-0f22ab80-95f4-11e9-8203-7339682e1c9e.png)

**Comment by actioninja** [comment]
You sure it wasn't just the icon being fucky?
This is probably an actual bug but I've seen this on old cables as well a few times

**Comment by Dennok** [comment]
Dont icon. It really charges. And first i find it on the cutted solar APC that discharged by powersink.

**Comment by actioninja** [comment]
Confirmed that this is in fact a bug with some varedit checking, and then immediately identified what was causing it and fixed it.
It'll be fixed in a PR I want to get up tonight but I am probably going to fall asleep again.
