### ISSUE TITLE
Fusion Canister Rolls Over to 2.7K

### ISSUE THREAD

**Issue by Underbaked** [tgstation/tgstation#44778]
## Reproduction:
Me and a borg created a fusion can by mixing cooled trit ~600 moles, with 50/50 plasma co2 at about 40 Kelvin. We patiently heated it using heat exchangers from the heat of the incinerator until it hit 10k Kelvin, unwrenched, and let it fuse. The can shot particles for about 10 seconds, and we measured about 500k Kelvin at one point. Suddenly, the temperature dropped to 2.7 Kelvin, the minimum, and stayed there. We repeated the fusion for the same can, and yielded the same result; fusion for a few seconds, and then 2.7 Kelvin. This is the fuse mix after we heated it up the second time; the rest of the logs were overwritten.

You use the analyzer on  the canister.

Results of analysis of  the canister.

Moles: 3532.29 mol

Volume: 1000 L

Pressure: 206791 kPa

Carbon Dioxide: 37.92 % (1339.31 mol)

Tritium: 13.98 % (493.9 mol)

Plasma: 46.67 % (1648.68 mol)

Oxygen: 0.37 % (13.18 mol)

Nitrous Oxide: 0.01 % (0.46 mol)

Water Vapor: 0 % (0.09 mol)

BZ: 0.36 % (12.72 mol)

Nitryl: 0.36 % (12.72 mol)

Nitrogen: 0.32 % (11.24 mol)

Temperature: 6771.73 °C (7044.88 K)

Large amounts of free neutrons detected in the air indicate that a fusion reaction took place.

Instability of the last fusion reaction: 5.76.

**Comment by Whoneedspacee** [comment]
temperature does not roll over, sometimes fusion reactions are endothermic (take in energy) and exothermic (release energy)

not a bug intended
