### ISSUE TITLE
You save the same cloning record infinite amount of times

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/tgstation#44782]
## Reproduction:
https://cdn.discordapp.com/attachments/484170915253321734/592605839639183400/itpKb77XM0.mp4

in this webm ended up saving two records with the same ID, but I couldnt save a third one until I opened the last one in the list

**Comment by Aranclanos** [comment]
let me know if I should upload the mp4 elsewhere, apparently its too high tech and can't upload it to github

**Comment by 4dplanner** [comment]
@XDTM
