### ISSUE TITLE
bio bags no longer feed repo slimes

### ISSUE THREAD

**Issue by knacker48** [tgstation/tgstation#44797]
## Round ID:
111453

## Reproduction: 
fill a bio bag with monkey cubes. Then click on a reproductive slime extract. You will find that you can only pick of slimes from it, but not feed it like you could before

**Comment by kriskog** [comment]
Caused by #44579

**Comment by optimumtact** [comment]
@ninjanomnom thoughts?

**Comment by ninjanomnom** [comment]
There's probably some callbacks being passed into a signal somewhere I missed. I'll check this later tonight.
