### ISSUE TITLE
All empty clones of a moth plus the orginal moth can loose their wings if any one of them are set on fire.

### ISSUE THREAD

**Issue by shellspeed1** [tgstation/tgstation#44799]
## Reproduction:

Make a brain dead clone of a moth. Set it on fire. Laugh as all versions of that moth lose their wings.

**Comment by ATH1909** [comment]
It's like a voodoo doll, but for moth wings. Nice.

**Comment by nfreader** [comment]
I tested this with buildmode copy+paste in the thunderdome and had the same results. Not sure if this is the same as clonining an empty clone though. Needs to be reproduced!

**Comment by shellspeed1** [comment]
I'll give it a try, to be fair I had teleported in about a solid 20-30 clones of myself and something else could have been fuckey.

**Comment by fludd12** [comment]
@nfreader Buildmode Copy/Paste notably retains all references the mob has - meaning its limbs will also share damage values. It's worth testing specifically with the cloning machine.

**Comment by nfreader** [comment]
That's what I figured :) I'll harass some moths I see online later today and see if I can replicate it.

**Comment by nfreader** [comment]
Hokay, so I was able to reproduce this in-game. 

Current revision: https://github.com/tgstation/tgstation/commit/a83087788b0e3d084984e65170a50b2f19a1bbf5

Did exactly what OP did, but the actual living moth in this case only lost their wings AFTER they put a hardsuit on. So this is definitely a thing.

**Comment by fludd12** [comment]
I'm at work at the moment, but I think I know the cause, if anyone's willing to take a look.
The moth's wings may be saved as a reference, and cloning, rather than making a new reference, just carries it over; basically, this makes all moths that are cloned have one set of wings shared between them.

The reason you lost your wings after you put a hardsuit on is because that likely is set to update the wings' icons.

**Comment by shellspeed1** [comment]
This issue actually has applied to someone doing some fuckery to their clone in genetics as a nonmoth. Maybe more widespread that thought previously.

**Comment by ExcessiveUseOfCobblestone** [comment]
fairly certain this is a reproduction of an issue (which is that DNA is not actually copied but shared between origin and empty clone)
