### ISSUE TITLE
Rad collectors sometimes don't connect to powernet

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#44805]
## Reproduction:
Build and wrench a machine frame. Finish building the rad collector. It will not connect to a powernet until you unwrench and wrench it again.

**Comment by Qydra** [comment]
This problem runs much deeper than OP reported.  SMES's, Solar devices, rad collectors, and wires all occasionally fail to connect to the powernet, as far as I can tell.  I just noticed this today, so I don't know if this is related or separate.

**Comment by kriskog** [comment]
That shouldn't be related to this, this is an issue of rad collectors not adding powernet when anchored before the machine is finished. You should make a new issue on your thing, and try to include round ID and some reproduction steps.
