### ISSUE TITLE
Reconnecting while the round is starting causes weird vision

### ISSUE THREAD

**Issue by interestingusernam3** [tgstation/tgstation#44809]
Issue reported from  Round ID: 111512 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471

Problem Description: I reconnected with "Ready" selected just before roundstart. I ended up spawning, but with the round lobby window still on the screen, blurred vision and space instead of black tiles. The problem (save for the lobby window) has persisted upon reconnecting, taking precsiption glasses off my character, restarting BYOND, updating BYOND and reinstalling BYOND. 
No admins were online at the time. The problem can be fixed by the death of the player character.

Steps to reproduce the problem: 
1. Wait unthil ~16 sec are left in lobby, send three OOC messages
2. Get connection problems (the messages must not appear)
3. Reconnect
4. Repeat unthil you end up with the problem described above I guess

**Comment by JJRcop** [comment]
Do ypu have reason to believe that connection problems are required to reproduce this bug?

**Comment by interestingusernam3** [comment]
I genuinly have no idea where the code breaks.

**Comment by interestingusernam3** [comment]
I have failed to encounter the bug since, let's just blame cosmic rays/BYOND.
