### ISSUE TITLE
Not All Wires Sucked in By Singulo

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#44818]
## Round ID: 111554

![image](https://user-images.githubusercontent.com/37246588/60141238-9867e880-9782-11e9-8d32-519d1de888eb.png)

Some wires get sucked in, others take longer. In the time it took to type this a few more were sucked in, but those close to it are still hanging on?

I say its a bug because shouldn't wires be deleted after their plating is ?

**Comment by actioninja** [comment]
I'm going to tentatively say this has been fixed, but it likely hasn't. Reply if you see it happen again.

**Comment by Eaglendia** [comment]
Still seems to be happening as of #113258. Looks like the smart cables in space are each spawning new cable pieces to be sucked into the singulo.

**Comment by actioninja** [comment]
I got it, the qdel was runtiming.
