### ISSUE TITLE
Throwing someone into the SM crystal through a disposals pipe still gives you radiation burns

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#44813]
Issue reported from  Round ID: 111535 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1470

**Reproduction**
1. Make disposals pipe from wherever (Engineering Lobby in my example but testing proves it happens even from Cargo
2. Throw someone into the chute
3. Watch as even though you are halfway across the station, you gain radiation burns as if you threw him in directly.

**Comment by shellspeed1** [comment]
just do it via jump pad.

**Comment by Coconutwarrior97** [comment]
I tested this myself and did not receive radiation burns of any kind, Ill close this in a bit if no more evidence of it us brought up.
