### ISSUE TITLE
Nuke-Ops teleprod base escape method

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#44837]
Title, teleprods can be crafted by Nuke-Ops while at their base and can use them to escape to Centcom.
### Reproduction:
- Be Nuke-Op
- Buy a briefcase launchpad and flamethrower
- Deploy the launchpad and then destroy it, collect the artificial bluespace crystal it drops.
- Disassemble the flamethrower with a screwdriver and wrench, collect the igniter
- Make a wired rod out of readily available materials on the base
- Craft a tele-prod and add a power cell found on the ship
- Poke yourself with the tele-prod while standing in the syndicate drop pod until you're in space
- Be free on the Centcom z-level
...
Stopping here is recommended
...
- Declare war on the station for extra juicy TC
- Find and start looting Centcom
- End up fighting a Deathsquad
- Win with eshields, hardsuit shielding, and superior armor-piercing ballistic ammo weaponry
- Loot Deathsquad
- Hijack Centcom and declare open war against Nanotrasen
- Fight a second wave of mechanized death-squad troopers that are now using marauder mechs.
- Score a second win with RPGs firing HEDP rockets
(two rockets or even sometimes just one will destroy a default loadout marauder, and hardsuit shields will stop heavy pulse beams, just beware of the mech missile launchers, a good counter is to use medical kits and stimulant syringes to deal with the damage and avoid being stun-KO'd by the explosion. (stimpacks in a combat hypo is also a good way to conserve stimulants))
- Watch Nanotrasen's navy show up on the front doorstep of your newly hijacked Centcom station
- Debate your null chance at withstanding direct BSA cannon fire
- Request assistance from the Syndicate fleet
- [???](https://i.imgur.com/TvMjcua.png) (WJohn project spoilers)
- BSA vs [REDACTED]
- Discover too late that combining the powers of bluespace and [REDACTED] actually results in a universe collapsing cascade effect.
![uhoh](https://user-images.githubusercontent.com/17460297/60209846-5a190a80-9810-11e9-8221-42eb99c26efe.gif)
- Forget about greentext
- Grab chrono suit and jump into some rift because "THERE NO TIME TO EXPLAIN"
- Pledge to reevaluate your life choices lest FUN occur
- Don't
- Destroy yet another timeline
- Conclude that The Syndicate and Nanotrasen being such close neighbors is either a terrible
 mistake, or some grand space-time distortion prank by the Wizard Federation.

> Should've taken a lesson from Bay before drawing two of the most powerful weapons against each other, maybe next time you'll know better and actually save something that isn't yourself.

**Comment by nfreader** [comment]
Hilarious. Can you get us a round #?

**Comment by GravitronBlue** [comment]
No specific round ID available but this was tested locally with the absolute latest version of TG.
The story mostly goes over an assumed IC response scenario instead of just being the more likely response of 'everyone involved being deleted from existence and banned' outcome.

**Comment by Dawson1917** [comment]
Feature, nuke ops not being brainlets is rare enough to reward with centcom loot

**Comment by GravitronBlue** [comment]
Should also mention that this is related to #31429

**Comment by py01** [comment]
fuck me this is such an extreme edge case, there really needs to be a teleport-halting component, or some central function that handles teleporting instead of having special z-level checks in every items that causes teleports

**Comment by PKPenguin321** [comment]
I cannot believe this

**Comment by PKPenguin321** [comment]
Teleprods seem to already use do_teleport, does that proc not already block teleporting on the centcomm z-level?

**Comment by GravitronBlue** [comment]
To my understanding #17276 was an attempt at stopping these sorts of teleports with a variable stored in the area type. This was given to the syndicate base area type but the but the syndicate infiltrator shuttle and assault drop pod at present don't have this.

**Comment by PKPenguin321** [comment]
So the problem isn't teleprods but a bad area var

**Comment by Dennok** [comment]
No, If you want ability to teleport from huke ops ship when it dont on base you need another way. The vaz, stored in area, keeps when shuttle moved.

**Comment by 81Denton** [comment]
Issue is that `/area/shuttle/assault_pod` doesn't have noteleport set to TRUE

**Comment by PKPenguin321** [comment]
Is there any reason to not just make do_teleport return false on the centcomm z-level?

**Comment by Mooshimi** [comment]
> Is there any reason to not just make do_teleport not run on the centcomm z-level?

This would probably fix #60968 and #31429 at the very least

**Comment by Addust** [comment]
Live testing at terry thunderdome has confirmed that bug is fixed at CC Z-level - admin unwilling to test on actual nukie base Z-level

**Comment by Addust** [comment]
FALSE ALARM. BUG WORKS AT NUKIE BASE.

**Comment by ZephyrTFA** [comment]
Well I mean sure you can use it inside a lazy tenplate, but you're stuck in an isolated z level with a high chance of landing on a cordon turf and getting dusted

**Comment by GravitronBlue** [comment]
#66149 overhaul should take care of this with a wider 'catch' region surrounding the shuttles and pod areas, if not my suggestion would be to point out space tiles that can still be reached over on that PR.

Should've perhaps consolidated this issue report with #31429 as well.

If there's still issues with teleportations on the Centcom z-level at this point it may be worthwhile to make a new report, as this one is rather stale and I'd rather not maintain it for another 5 years.
