### ISSUE TITLE
Between the Sheets not healing again.

### ISSUE THREAD

**Issue by BaronVonRabbitface** [tgstation/tgstation#44842]
## Round ID: 
111658

## Reproduction: 
Just take any amount of brute or burn damage, drink some Between the Sheets, sleep, then check your damage values. For whatever reason, it's suddenly not healing again. I even tested it on a private server just to be sure, and it's definitely not working.

**Comment by 4dplanner** [comment]
Round 2

**Comment by 4dplanner** [comment]
Could not reproduce

**Comment by BaronVonRabbitface** [comment]
Looks like it was actually a false positive, sorry about that.
