### ISSUE TITLE
Item attack sprites and speech bubbles don't disappear

### ISSUE THREAD

**Issue by Lett1** [tgstation/tgstation#44852]
![](https://i.imgur.com/U72pgsL.png)

## Round ID:
111702

## Testmerges:

BYOND Version: 512.1471
Server revision compiled on: 
Master commit: 2d235c1955114eb758c286f287fec983a91c7cf9
The following pull requests are currently test merged:
#44310: 'Removes Hygiene' by Garen7 at commit 3a37d0322c

## Reproduction:

Just say something or punch a thing with another item.

**Comment by kriskog** [comment]
I saw this in the same round, so its not a single client only thing.

**Comment by Tlaltecuhtli** [comment]
i have seen it too, these animations? sometimes they  would take 20-30 s to disappear

**Comment by py01** [comment]
seems to rarely affect specific rounds in my experience

**Comment by optimumtact** [comment]
Im not sure this is worth reporting, it's usually an indication that the SStimer subsystem has broken or the MC is misfiring

@MrStonedOne

**Comment by timothymtorres** [comment]
Haven't seen any recent issues regarding this, and it is fairly obvious, so there should be more bug reports if it was still happening.  I'm marking this as cleanup.
