### ISSUE TITLE
Spirit realm bug, cant move when being used

### ISSUE THREAD

**Issue by bigfatbananacyclops** [tgstation/tgstation#44859]
This bug has been here for a long while, whenever you summon a ghost from the spirit realm, you will not be able to move and you will be trapped until you lose alot of health and die. There is a solution for this which is remove the rune under you with the dagger, however it’s still stressful.

**Comment by ATH1909** [comment]
I thought that this was fully intentional. Is an inability to move off of the rune under your own power not intentional?

**Comment by YakumoChen** [comment]
Getting an extra friend who comes standard with a free sword and ranged stun and ally-free conversion that you can just re-summon when he dies ought to have a couple drawbacks.

**Comment by kriskog** [comment]
Nothing in the code seem to indicate it is intentional. Either way it gives no user feedback, if it stays it should have.

**Comment by ATH1909** [comment]
> also I think it was changed because ghosts would always constantly push you off the rune.

just rest lmao

(yes, I know that resting wasn't around when the rune was added, but that kind of ruins the joke)

**Comment by kriskog** [comment]
dupe of #41365
