### ISSUE TITLE
Spent Exosuit Ammunition can be Destructive-Analyzed for 100% material return

### ISSUE THREAD

**Issue by Nefarian78** [tgstation/tgstation#44864]
Issue reported from  Round ID: 111809 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 512.1471

You can reclaim all materials from an empty Exosuit ammunition box (FNX-99 Carabine Ammo, for example) From the Destructive Analyzer, making ammunition basically free

**Comment by HomocidlePancakes** [comment]
Pleb. Recycle it with the autholathe
