### ISSUE TITLE
DNA consoles have no cooldown

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#44867]
ok so i made a dna console (the genetics one, not cloning) in central hallway and loaded on laser eyes from the gateway mission and i was able to print them (along with other mutations from the gateway mission but they were xray and telekinesis). there was NO scanner machines which i assume is what caused it. I had 3 of the consoles next to each other.

**Comment by Time-Green** [comment]
if it worked perfectly fine, then how is it bugged?

**Comment by imsxz** [comment]
oh fuck me im  aretard i forgot to include that it had NO cooldown @Time-Green i could spam click it and get hundreds of each
