### ISSUE TITLE
Smart Cable incorrectly links AI sat to power grid roundstart

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#44862]
AI sats are now wired to the grid at roundstart, which leaves them vulnerable to power sinks. This is especially dangerous on Meta where telecomms becomes directly powered by the grid with no airlocking.

## Reproduction:
look at a map, like meta

**Comment by kriskog** [comment]
This is indeed a thing.
Meta engineering:
![image](https://user-images.githubusercontent.com/33292112/60332185-94acaf80-9996-11e9-8789-dd1de9dd4021.png)
AI sat:
![image](https://user-images.githubusercontent.com/33292112/60332233-ab530680-9996-11e9-804f-2e3198427220.png)

These were previously not connected.

**Comment by WJohn** [comment]
Could've sworn there was a cyan cable running down this that connected them?

**Comment by SpaceManiac** [comment]
@WJohn cables don't have colors anymore
