### ISSUE TITLE
Areas of the emergency shuttle no longer fly with use of the blueprints

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#44877]
Issue reported from  Round ID: 111918 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471
Not relevant to the round I was in at all, but if you use the station blueprints to designate a part of the shuttle as a new room and/or rename it (cannot quite remember how this is done) that section of the shuttle will no longer be recognized as a part of the shuttle, and will not fly to central command, effectively cutting an entire chunk out of the shuttle.

**Comment by PKPenguin321** [comment]
oh god not this bug again

**Comment by TheBonded** [comment]
I can't seem to replicate this, the blueprints say something along the lines of "this area is not suitable for renaming" or something of the sort.
However, if this bug has returned, does that mean it's possible to make different parts of the station (hallways, departments) leave with the shuttle by renaming them?

**Comment by Dennok** [comment]
No

**Comment by Dennok** [comment]
And this already fixed.

**Comment by dragomagol** [comment]
As mentioned, blueprints don't allow you to change shuttle area.
