### ISSUE TITLE
cyborgs do not have access to cloning panel controls

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#44871]
They cannot delete records and such. They can use the "normal" functions fine

**Comment by shellspeed1** [comment]
I'm not totally sure this is an issue.

**Comment by nfreader** [comment]
Looks like silicons are specifically restricted from deleting cloning records: https://github.com/tgstation/tgstation/blob/master/code/game/machinery/computer/cloning.dm#L390-L395

So working as intended. Could probably use some more feedback though.
