### ISSUE TITLE
you can spam purification on soulshards

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#44874]
Issue reported from  Round ID: 111905 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471

you can spam purification on soulshards

**Comment by DaxDupont** [comment]
IE: you can spam purification on soulshards.

**Comment by wesoda25** [comment]
Fix pr is already up plus duplicate issue

**Comment by nfreader** [comment]
Dupe of #44678
