### ISSUE TITLE
Accepting a sentience-potioned Queen Bee sends you back to the main menu.

### ISSUE THREAD

**Issue by Erik489** [tgstation/tgstation#44878]
## Reproduction: 
Step 1: Die or observe the current round and wait for a xenobiologist to produce Sentience potions.

Step 2. Accept the role of Queen Bee and move. The game will freeze, then kick you back out to the main menu where you can rejoin the game as a job.

**Comment by ATH1909** [comment]
... Even if you've already played in that round and weren't just observing?

Can this be used to "reincarnate" dead people?

**Comment by Erik489** [comment]
> ... Even if you've already played in that round and weren't just observing?
> 
> Can this be used to "reincarnate" dead people?

Yes, I was the clown in that round (Count Honkula), died, became an abductor, died again, and accepted the role of a queen bee. After being kicked out I ahelped the issue and respawned as Dennis Landrow.

**Comment by Time-Green** [comment]
this is what happens when even for a nanosecond your ckey is not assigned to anything

**Comment by Dorsisdwarf** [comment]
I wonder if this is related to those old bugs that happened from multiple people getting a ghost role at once

**Comment by tralezab** [comment]
definitely related to #45238. no doubt in my mind

**Comment by kriskog** [comment]
Closing in favor of #47720
