### ISSUE TITLE
Lavaland Shuttle Blocks Hunter Ship From Spawning

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#44888]
## Reproduction: Random round start Fugitive event spawns waldo, but not their hunter.
Its been suggested this is because of the new public lavaland shuttle on the auxilary airlock.
And to be honest I feel the lavaland public shuttle should probably have its own dock to avoid it being hit by retrieved white ships

EDIT: Its been tested that the lavaland shuttle does indeed prevent the white ship from landing, so this almost certainly stops the hunter ship from spawning as this is also where their ship spawns.

**Comment by FloranOtten** [comment]
I don't mean to be smug but

https://www.youtube.com/watch?v=SgpnrOUS2BE

**Comment by tralezab** [comment]
holy shit a fugitive bug that doesn't have to do with fugitives

**Comment by YakumoChen** [comment]
The whole lavaland base PR was a mistake

**Comment by kriskog** [comment]
@tralezab This is fixed right?

**Comment by msgerbs** [comment]
Don't know what fixed this but it's fixed. It spawns off in space somewhere and can then be moved to a docking port when it's available or just flown to a custom destination with the nav console.
