### ISSUE TITLE
OOC perfs arent saving

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#44887]
Issue reported from  Round ID: 111980 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471

OOC preferences are not saving like lobby music and tthe auto deadmin

**Comment by Nickkoranda** [comment]
Did you happen to set auto deadmin on by any chance? I've had the same issue when I turn it on.

**Comment by DaxDupont** [comment]
Yes @Nickkoranda it seems auto deadmin corrupts prefs.

**Comment by DaxDupont** [comment]
@ShizCalev
