### ISSUE TITLE
Bluespace body bag duping

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#44902]
https://cdn.discordapp.com/attachments/326826573951008769/595162747080015882/bluespacebodybags.PNG

Neither I nor the guy who performed the dupe know why or how this bug occurred (which is not much help, I know), but a doctor was able to drop as many bluespace body bags on the ground as he wished across Medbay without losing the one in his hand. These bluespace body bags could be zipped, unzipped, and picked up normally, but the ones that I tried to put in the box in my backpack disappeared (unfortunately, I didn't think to check to see what would happen if someone was inside of one of those bluespace body bags when I put them in that box or what would happen if I tried to deconstruct one of those bluespace body bags for materials).

This occurred on the EU Event Hall server with Garen's hygiene removal PR being testmerged at the time. The map that we were on was Metastation.

This bug may or may not be related to some of the other bugs that were being messed around with/interacted with that round, including:
https://github.com/tgstation/tgstation/issues/44867 (do note that the console was set up AFTER the body bags were duped, IIRC)
https://github.com/tgstation/tgstation/issues/44803 (I don't remember whether or not time was repeatedly King Crimson'd before, during, or after the duping, but I think it occurred pretty close to when the duping did)
https://github.com/tgstation/tgstation/issues/44884 (I don't remember whether or not the goose was found before, during, or after the duping)

I unfortunately do not have the round ID, but the screenshot shows the name of the station that round. The round took place at some point during the night between June 30th and July 1st (North American Central Time Zone time).

I know that this isn't much to go on/go off of, but maybe someone could do some detective work with the information that we do have? If I had to guess, I'd say that this is a lag-related bug.

**Comment by distributivgesetz** [comment]
Reproduction courtesy of #69952:

Have yourself folded into a bluespace body bag and dropped (folded).
While inside the folded body bag, pick up your folded body bag.
Have someone else let you out (or break out)
Your hand seems empty but if you left click on the floor you can dupe the bluespace body bag indefinately.
