### ISSUE TITLE
Can't load a map I am trying to make

### ISSUE THREAD

**Issue by ishitbyabullet** [tgstation/tgstation#44921]
I was told to try asking for help here by Spacemaniac since someone may know the answer.

I am unable to load an away mission map using "load away mission." I also can't get a good runtime log for it since it lags the server so much that it freezes dream daemon and technically the game. I can still KINDA move though. If I were to try and edit my variables during this immense lag then it will be logged in the runtime log however not the map loading.

I've tried deleting numerous things I have added. I tried checking for step_x, step_y, etc. I also tried map merger. None of them seem to have worked.

An example of what this looks like:
![2019-07-02_01-19-43](https://user-images.githubusercontent.com/29403316/60484403-75987100-9c67-11e9-80c8-2644b9927f2d.png)

**[If anyone is able to help then I would greatly appreciate it.](http://www.byond.com/forum/post/2482760)** I wasn't able to link the file itself so just click on the link in the first post at the top of the thread.

**Comment by ishitbyabullet** [comment]
Also if anyone looks at it then argues about the contents of the map then please note that it isn't finished. Thank you.

**Comment by ExcessiveUseOfCobblestone** [comment]
can you not load ANY mission or just the specific one?

**Comment by ishitbyabullet** [comment]
The specific one. The original version can be loaded just fine.

**Comment by Dennok** [comment]
your map is modded "wild west"?

**Comment by ishitbyabullet** [comment]
Modded wild west? No.

**Comment by SpaceManiac** [comment]
It's a modded wizard academy.

I am worried there is a bug in the map reader on non-TGM formatted files.

**Comment by Dennok** [comment]
Yes, the DD say it. 
But it easely can be lauched if add it just as standard to the roundstart map. Just include it.

**Comment by ishitbyabullet** [comment]
It's still an issue in theory, but why keep it open if it'll never get seen?
