### ISSUE TITLE
Solar panel computers wont sync with the solar panels.

### ISSUE THREAD

**Issue by severepwnage** [tgstation/tgstation#44929]
Its fucked. Fix it immediately, the station keeps running out of power five minutes into the shift and the AI dies.

**Comment by ExcessiveUseOfCobblestone** [comment]
most likely new wire related.

**Comment by recordcrash** [comment]
Can confirm the issue, this should be highest priority, no rounds can be completed.

**Comment by 007Axel** [comment]
Whoever thought the new wiring was a good idea probably forgot about "current" implementations..

**Comment by ExcessiveUseOfCobblestone** [comment]
@WJohn r u wireman
