### ISSUE TITLE
Major powergrid bugs: Almost NO machines connected roundstart!

### ISSUE THREAD

**Issue by CPTANT** [tgstation/tgstation#44936]
Almost all the APC's, Smesses,  solar trackers and more didn't connect to the power grid at roundstart! Replacing the wire underneath the structures fixed the issue for that particular machine.

round 112184

**Comment by recordcrash** [comment]
Confirming this is a major bug affecting the current build. Makes playing impossible.

**Comment by Putnam3145** [comment]
I would guess this is caused by https://github.com/tgstation/tgstation/pull/44899, since I successfully wired the solars and powered a station with smart wires two days ago.

**Comment by HomocidlePancakes** [comment]
If it's not broke, don't fix it, or this happens.

**Comment by actioninja** [comment]
Oh shit oh fuck oh god
