### ISSUE TITLE
Thermite Component Code Oddity

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#44944]
Let's play a game, kids:

https://github.com/tgstation/tgstation/blob/92e00cb544c3dc914f771ae638fa2d1aba0f8fc3/code/datums/components/thermite.dm#L54-L69

Can YOU figure out what's wrong with this section of code?

Answer:
```
    if(amount >= 50)
        var/burning_time = max(100, 100-amount)
```
(burning_time is always equal to 100 when it's created, regardless of the value of amount)

**Comment by CPTANT** [comment]
Ah the classic using min to compare 2 values puts a max on it while using max puts a minimum value on it.

**Comment by nemvar** [comment]
Also doesn't look like the thermite component gets deleted after burning up. Now that's epic.
