### ISSUE TITLE
Anomalous research point gain

### ISSUE THREAD

**Issue by Krysonism** [tgstation/tgstation#44943]
## Round ID:
112209

## Reproduction:

Everything in RND seemed normal at first but like 30min in the research points started to spike, i think it hit like 1 million before i researched everything and left the console alone.

I don't know how to reproduce this, i was mostly doing xenobio that round. I guess it is something to watch out for.

**Comment by YakumoChen** [comment]
did you check to see if there was anything else generating points? Engineering changing rad collectors to research mode perhaps?

**Comment by Krysonism** [comment]
> 
> 
> did you check to see if there was anything else generating points? Engineering changing rad collectors to research mode perhaps?

No i was antag so i didn't have time to investigate. It just suddenly started gainig research points way faster than i could spend it.

**Comment by fludd12** [comment]
I saw this happen once, too - There was no research point generating explosion from toxins, no engine modification that I know of, just a sudden point spike. It was admittedly an appreciated windfall, but I still don't know what happened.

**Comment by Tlaltecuhtli** [comment]
happened in 112308

**Comment by Mooshimi** [comment]
The engine rad collectors being changed to produce sci points was removed, just a note.
