### ISSUE TITLE
Can't put MMI into exosuit with DNA lock even if the brain in the MMI is from the one that locked it

### ISSUE THREAD

**Issue by Nefarian78** [tgstation/tgstation#44963]
## Round ID:

112251

## Reproduction:

As the title says, the creator of a DNA lock inside an MMI can't be put inside the exosuit with a DNA lock created by him

Dna lock an exosuit. Die and have your brain put into an MMI. Try having your MMI-brain placed into the exosuit DNA locked by you. Get locked out of it because the suit doesn't recognize the same DNA.

**Comment by fludd12** [comment]
Oddly enough, not a bug - Brains do not actually have DNA, only bodies. An IC justification for this, if you want one, is that the DNA scanner only works on skin cells, which MMIs lack.

**Comment by MegaEmpirical** [comment]
There is a similar issue with Changelings that take on someones form too I believe.
