### ISSUE TITLE
Medical Departmental Techfab produces wrong circuitboard for Cloning Computer Board

### ISSUE THREAD

**Issue by versacehhh** [tgstation/tgstation#44965]
## Round ID:
112262

## Reproduction:
Print the computer board for Cloning **computer**, Crew Monitoring board pops out.

**Comment by Shadark** [comment]
Can confirm, I also tried to print the Crew Monitoring console board and I got an empty circuit board.

**Comment by willox** [comment]
this was fixed by the pr ^
