### ISSUE TITLE
Modular Tablets Need a "Weapons" Recharging Platform

### ISSUE THREAD

**Issue by MystLeissa** [tgstation/tgstation#44978]
Problem Description: 

It's more of a balancing thing but weapons chargers (for security) are the only way to recharge a depleted tablet battery short of removing the power controller as a whole.

What did you expect to happen: 

There should be a dedicated charger for "Tools" like Tablets/Laptops/Etc Or just merge the Tablet Charging Code into the Power Cell Charger instead of the weapons one.

What happened instead:

Weapons Chargers are used to charge the Batteries of Tablets (how many times are you going to ask "What is the issue"?)

Why is this bad/What are the consequences:

Security Checkpoints and other high-security areas on most maps are the only place to charge tablets. Tablets are no hi-sec items and shouldn't need to expose normal everyday personnel to the security booth to recharge.

Steps to reproduce the problem: 

Placed a Tablet in a weapons recharger - really it's not a bug as much as a balance issue.

Server:

Mainly My own private server but I've also played on Terry

Revision: What revision was the server running? Type 'show-server-revision' ingame to find out.

Round ID: 38
BYOND Version: 512.1470
Server revision compiled on: 
No commit information

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
Enforce Continuous Rounds: 12 of 22 roundtypes
Allow Midround Antagonists: 7 of 22 roundtypes

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Anything else you can tell us.

N/A

Your welcome for the advice.

**Comment by Dennok** [comment]
cell from it cant be charged in cell charger?

**Comment by HomocidlePancakes** [comment]
Just remove the cell out of the tablet.

**Comment by Tlaltecuhtli** [comment]
holodeck has a charger

**Comment by ATH1909** [comment]
> holodeck has a charger

Still, not everyone knows that, and it makes sense for a civilian device to be recharged at a charged for civilian devices instead of a charger for energy weapons.

**Comment by HomocidlePancakes** [comment]
>Still, not everyone knows that, and it makes sense for a civilian device to be recharged at a charger for civilian devices instead of a charger for energy weapons

You are meant to take the cell out and recharge it. My god.

**Comment by JJRcop** [comment]
Please post ideas to the [Ideas subforum][1] on /tg/station's website.

[1]: https://tgstation13.org/phpBB/viewforum.php?f=9
