### ISSUE TITLE
Allow disablers to to fit into shoulder holsters

### ISSUE THREAD

**Issue by CrossbowDemon** [tgstation/tgstation#44977]
Allow disablers to to fit into shoulder holsters

Issue reported from Round ID: 112312 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1472

**Comment by CrossbowDemon** [comment]
Allow disablers to to fit into shoulder holsters

**Comment by PKPenguin321** [comment]
Dupe/Not a bug
