### ISSUE TITLE
Disablers do not fit into shoulder holsters ruining my cowboy dreams.

### ISSUE THREAD

**Issue by CrossbowDemon** [tgstation/tgstation#44974]
Disablers do not fit into shoulder holsters ruining my cowboy dreams.

Issue reported from  Round ID: 112312 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1472

**Comment by CrossbowDemon** [comment]
Disablers do not fit into shoulder holsters ruining my cowboy dreams.

**Comment by PKPenguin321** [comment]
Not a bug

**Comment by Dorsisdwarf** [comment]
shoulder holster is for the det's revolver, not disablers.
