### ISSUE TITLE
Attach seclites to Security Plasma Envirosuit Helmets.

### ISSUE THREAD

**Issue by CrossbowDemon** [tgstation/tgstation#44976]
Attach seclites to Security Plasma Envirosuit Helmets.

Issue reported from Round ID: 112312 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1472

**Comment by CrossbowDemon** [comment]
Attach seclites to Security Plasma Envirosuit Helmets.

**Comment by PKPenguin321** [comment]
Not a bug

**Comment by Dorsisdwarf** [comment]
stop posting everything twice
