### ISSUE TITLE
the newly added wires make SMES's bad

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#44970]
most of the SMES's on station (at least metastation) are wired to themselves which increases the total power and load in the network and generally confuses the hell out of newbie engineers, making them think theyve invented magic infinite power.

**Comment by actioninja** [comment]
Damn, I thought I fixed this.

**Comment by Dennok** [comment]
What you write has always been there. 
As I understand it, you mean that the correctly connected "SMES" does not separate the network,
and try to charge themselves, that creates ton of power and load in the network?
