### ISSUE TITLE
Seclites cannot be attached to Security Plasma Envirosuit Helmets.

### ISSUE THREAD

**Issue by CrossbowDemon** [tgstation/tgstation#44975]
Seclites cannot be attached to Security Plasma Envirosuit Helmets.

Issue reported from  Round ID: 112312 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1472

**Comment by CrossbowDemon** [comment]
Seclites cannot be attached to Security Plasma Envirosuit Helmets.

**Comment by PKPenguin321** [comment]
Dupe/Not a bug

**Comment by Fikou** [comment]
all envirosuit helmets except the curator one already have lights???

**Comment by HomocidlePancakes** [comment]
Attaching a flashlight to a flashlught 🤔

**Comment by ShizCalev** [comment]
Intended
