### ISSUE TITLE
Lizard spines disappear after admin heal

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#44981]
Issue reported from  Round ID: 112323 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1466

To reproduce:
1.  Make a lizard with some kind of spines (aquatic is what I used for testing)
2.  Adminheal your character or get the heal result from the die of fate
3.  Poof, no more spines.

Why this is important:  I can't be a special snowflake without them.

**Comment by wesoda25** [comment]
What the fuck are lizard spines

**Comment by actioninja** [comment]
They mean like the spines you can get along the crest for lizards.
For a second I thought this meant that adminhealing lizards literally removed their spinal cord and that would be way funnier

**Comment by Coconutwarrior97** [comment]
Reproduced this and ahealing does remove the spines.

![LizardSpines](https://user-images.githubusercontent.com/40315842/61856274-7055cd00-ae87-11e9-8db1-9dd8f6ca3d92.png)
![LizardNoSpines](https://user-images.githubusercontent.com/40315842/61856289-7481ea80-ae87-11e9-861a-41e4fdf7107c.png)
