### ISSUE TITLE
security can become obessed

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#45009]
They shouldnt be able to become that right?

**Comment by Electronics** [comment]
?

**Comment by nemvar** [comment]
Not a bug.

**Comment by kriskog** [comment]
@tralezab intentional?

**Comment by bgobandit** [comment]
does the name "Javert" ring any bells to you

**Comment by JJRcop** [comment]
The code has no indication of filtering out security or any roles at all aside from non-human (AI and Cyborg) roles

**Comment by adamkad1** [comment]
i would think that mindshields, being stuff that protect you from getting turned into a rev or a cult would prevent you from wanting to murder people

**Comment by kriskog** [comment]
Have you ever met a member of security?
