### ISSUE TITLE
Rewind Anomalous Crystal oddieties

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#45026]
1)Using a rewind on VoG that was bitten twice ended up getting it transformed in to appendix.
2)Trying to rewind a stack deletes it

**Comment by HomocidlePancakes** [comment]
I have made so many typos in this one report holy shit

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=2rnO3fU5Pf8

**Comment by JJRcop** [comment]
It's difficult to understand your reproduction steps. Please make a new issue and follow the bug report template. More context will help. https://github.com/tgstation/tgstation/issues/new?template=bug_report.md
