### ISSUE TITLE
Injecting a crossbreed or monkey cube with plasma spills plasma

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#45020]
#### Round ID:
112478 Terry
Also confirmed locally. 

#### Testmerges:
#43148

#### Reproduction:

1. Spawn a burning/yellow crossbreed or a monkey cube.
2. Inject it with plasma. 

Result:
Gas form plasma is instantly spilled into atmosphere. 

Expected result: 
No plasma leak.

**Comment by OmegaShoots** [comment]
Also saw this happen with the lethal injection syringes in a round I was emptying them into 50u beakers to fill with holy water. On injecting into the beaker the plasma spilled all over for some reason.

I did not however check to see if the plasma was actually transfered to the beaker, to see if it somehow duped the plasma by spilling but still transfering it.

**Comment by Ty-the-Smonk** [comment]
Happens with industrial extracts too, ill look into it when I update my branch

**Comment by knacker48** [comment]
I've seen this happen with pretty much any slime that I injected with plasma. Had to turn myself into a slimeperson so I didn't die (yes I could use internals but wheres the fun in that)
