### ISSUE TITLE
Camera Static Disappearing

### ISSUE THREAD

**Issue by SkeletalElite** [tgstation/tgstation#45035]
## Testmerges: #
44310: Removes Hygiene' by Garen7 at commit 3a37d0322c 
44945: Properly fixes smart cable lag issues and also fixes the awful connection issues.' by actioninja at commit ce0c4696c8 

## Reproduction: 

Unsure how to reproduce it, but I was AI and a couple times in the round the camera static disappeared allowing me to see anywhere, it was still dark as usual, it wasn't xray cameras as the static reappared and disappeared a few times. Someone said that they could see a through a wall on a non xray camera by looking in a camera console too, it actually got xenos killed because I could see their nest even though it was in maint. (didnt realise it was from the bug at the time)

**Comment by actioninja** [comment]
Dupe issue of #38857
