### ISSUE TITLE
Gravity stand effect doesn't expire

### ISSUE THREAD

**Issue by OmegaShoots** [tgstation/tgstation#45033]
Round ID: 112506

Got hit by a gravity stand and the high gravity effect stayed more than 10 minutes after and caused my death when I was unable to run from two traitors who shot me.

**Comment by JJRcop** [comment]
How long is this supposed to last?

**Comment by OmegaShoots** [comment]
Probably just a few seconds like all other stand effects.

It causes a you to have hardsuit slowdown, and a loading bar whenever you try to put an item into your hand.

**Comment by YPOQ** [comment]
@OmegaShoots Looking over the code the only issue I can find is that the effect essentially becomes permanent if the stand dies while you're under the effect. Is that possibly what happened to you?

**Comment by OmegaShoots** [comment]
Yes, I killed it while fighting it while it was attacking me.
