### ISSUE TITLE
Screwing open a Suit storage unit while it's decontaminating breaks it

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/tgstation#45036]
If the panel is still open and it's finished decontaminating, the storage unit automatically opens and trying to screw it close would attempt putting it in the auxiliary storage. effectively making you unable to screw it closed and trying to get whatever is inside the suit storage.

**Comment by nfreader** [comment]
Sounds like something easy enough to reproduce and fix!

**Comment by the-og-gear** [comment]
Will attempt to reproduce Wednesday (17 Jul, 2019), and attempt a fix.

- Gear
