### ISSUE TITLE
Vomit geese have no cooldown on text

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#45030]
Issue reported from  Round ID: 112499 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471

Birdboat refuses to eat the hotdog.x56

Adler Cloudbank gobbles the hotdog.

Birdboat refuses to eat the hotdog.x7

(F) Kobe Catster says, "YES"

Birdboat refuses to eat the hotdog.x77

Adler Cloudbank gobbles the hotdog.

(F) Edgar Pope says, "Just hop on the table and remove headgear and eyewear"

Birdboat refuses to eat the hotdog.x63

(F) Kaden Zaun says, "Good"

Birdboat refuses to eat the hotdog.x21

Adler Cloudbank examines himself.

Birdboat refuses to eat the hotdog.x70

(F) Edgar Pope says, "Yo"

**Comment by plapatin** [comment]
existence is pain

**Comment by Ty-the-Smonk** [comment]
I dont see the problem with this
