### ISSUE TITLE
Being a bit hungry is enough to drive you clinically insane.

### ISSUE THREAD

**Issue by Dawson1917** [tgstation/tgstation#45044]
[44800](https://github.com/tgstation/tgstation/pull/44800) buffed the mood drain of various negative moodlets and lowered the thresholds for negative mood tiers. Previously being hungry incurred a -8 penalty (buffed to -10) to mood and would place you on the first tier of negative mood. 44800 changes the second tier of negative mood to -7 (previously -12) causing hunger to lower your sanity at a far faster rate if you don't remove the moodlet or give yourself positive moodlets.
## Reproduction:
1. Spawn in, wait around until you get hungry, ensuring not to catch any other moodlets.
2. Watch as over the course of 5-10 minutes you receive a free ticket to the psych ward because not eating 4 donuts at roundstart just MAKES. YOU. SO. SAD.

![image](https://user-images.githubusercontent.com/51552884/60769748-ca7a3280-a112-11e9-8dfc-b897f32ade06.png)

**Comment by SpaceManiac** [comment]
@Qustinnus

**Comment by ATH1909** [comment]
Can confirm; this happened to me as a comms agent too.

**Comment by Nickkoranda** [comment]
Def an oversight but imo if you didn't eat for 24+ hours then you'd be pretty twitchy/upset/mental too.

**Comment by PKPenguin321** [comment]
>if you didn't eat for 24+ hours then you'd be pretty twitchy/upset/mental too.

No??? Have you never heard of fasting?

**Comment by granpawalton** [comment]
Should just revert 44800 , moodies were in a great place before it and I dont understand why the change was good for the game

**Comment by Putnam3145** [comment]
i also like how being "a bit hungry" is as bad for your mood as getting your leg cut off

**Comment by Garen7** [comment]
I haven't had a round where I don't go insane becauseI'm slightly hungry

**Comment by Dawson1917** [comment]
I haven't noticed this happening in the last month and I'm told Nemvar added in caps for sanity loss, so closing since this shouldn't happen under normal circumstances

**Comment by tralezab** [comment]
yeah it was fixed ty dawson
