### ISSUE TITLE
There appears to be a way to escape cooldown for the traps spell as a wizard

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#45069]
Issue reported from  Round ID: 112653 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471

![image](https://user-images.githubusercontent.com/38219334/60829667-b1768d80-a1b5-11e9-8a2d-7389152e4a3b.png)

![image](https://user-images.githubusercontent.com/38219334/60829858-3a8dc480-a1b6-11e9-911a-e706a17031e2.png)

![image](https://user-images.githubusercontent.com/38219334/60830039-9bb59800-a1b6-11e9-8879-f736b0794b38.png)

![image](https://user-images.githubusercontent.com/38219334/60830111-c6075580-a1b6-11e9-8f7e-82ecdc5104e5.png)

![image](https://user-images.githubusercontent.com/38219334/60830196-ef27e600-a1b6-11e9-9adb-bbe6e35fa617.png)

I don't know if this is a bug, or an intended feature, but this is fucking broken. The wizard can instantly kill people by just spawning a stuntrap on them then dragging them through the minefield. They also cast events twice, and have an area rearrange spell, so there's no way they just maxed out the spell. One laser down the escape corridor on Box froze my game for a solid 15 seconds.

also, traps are not gay.

**Comment by 81Denton** [comment]
5x The Traps!
1x Spacetime Distortion
2x Summon Events
= 10 points
Then this brought The Traps! to level 6:
`[2019-07-08 17:18:21.342] GAME: 17:18:21.342] GAME: Random Event triggering: Improved Casting (/datum/round_event/wizard/improvedcasting)`

**Comment by 81Denton** [comment]
**Losing is part of the game!**

Your issue has been determined by an administrator to be an in character issue and does NOT require administrator intervention at this time. For further resolution you should pursue options that are in character.

**Comment by loserXD** [comment]
tell me how this isn't a bug please

**Comment by FloranOtten** [comment]
'This is so rare, it will never happen again'

Happened again today. ID:113135. 

Even if this aint a code issue, it's a balance issue. It's basically a wizard instant win, because there is nothing you can do to counter it.

**Comment by 81Denton** [comment]
You could fix it by giving level 6 spells a .5 second cooldown, it would at least stop them from mashing buttons like it's cookie clicker.
