### ISSUE TITLE
The transit tube to telecomms on donut is non-functional

### ISSUE THREAD

**Issue by Putnam3145** [tgstation/tgstation#45077]
## Reproduction:

Watch the transit tube that should go to and from tcomms on donut. Notice how it never moves under any circumstance. Try to enter it and find yourself unable to.

**Comment by bobbahbrown** [comment]
![image](https://user-images.githubusercontent.com/10467687/61011170-c1c27000-a34f-11e9-81b8-18f9ee4d69fc.png)

Specifically this pipe, my immediate suspicion is that the transit tube that starts inside the pipe is in a transit state. Removing the tube with a crowbar seems to correct it to normal functionality.

**Comment by MMMiracles** [comment]
problem was the tube had it's dir set wrong, easy fix
