### ISSUE TITLE
Bad Moodlet Message

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#45078]
Not sure what triggered this
![image](https://user-images.githubusercontent.com/8345184/60851990-cbf73980-a1aa-11e9-8a02-09e346de9ca5.png)
`Your current mood
My mental status: AHAHAHAHAHAHAHAHAHAH!!
My current mood: I feel terrible...
Moodlets:
I'm getting a bit hungry.
fill this in in the areaI really didn't like that food.
I saw something gross.`
>fill this in in the areaI really didn't like that food.

Looks like a placeholder message was left in?

**Comment by kriskog** [comment]
This should be fixed in  #45043. Open a new issue if it happens after server update.
