### ISSUE TITLE
Mech teleporters can teleport directly to Centcom via cameras

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#45071]
Title, mech teleport equipment modules can cross z-levels while using them through cameras, allowing access to Centcom.

Did this once a while back after okaying it with admins during a long extended shift. I've forgotten the round ID however, so none is available.

## Reproduction:
- Play on metastation
- Wait until RnD researches exosuit teleportation modules
- Build a mech and attach a teleport module to it
- Go to the departures security checkpoint and stand next to the security monitor on the wall
- Eject from the mech, start climbing back into the mech and use the monitor before you finish climbing in (Entertainment/TV screens don't let you view them from inside a mech)
- Select any camera to gain vision of the Thunderdome and Centcom z-level
- Select the mech teleporter module, face east (or rotate randomly), and click anywhere you have vision.
- End up in the thunderdome, ~~interrupt~~ 'steal' whatever ~~ERP~~ 'fun' the admins were up to, and probably get something like [this](https://i.imgur.com/Lrzogne.png) shortly later

Security monitor used for this likely has the wrong network ID listed in its variables.
![oversight](https://user-images.githubusercontent.com/17460297/60831013-6042ab80-a16d-11e9-8883-2ac493627ed3.PNG)

A camera built on the cargo shuttle also works as a destination with the use of regular security camera monitors.
Untested but camera bugs with this method in might might let you rapidly teleport about nearly anywhere where there's an accessible camera.

> Really the exact nature of what makes bluespace effective for teleportation remains a mystery, the guidebook on it being a parallel universe of proportionate size to ours is one thing, the blue radiation that likely gives it its name is another.
The only worthwhile lead on this would be some bluespace scientist by the name of Hilbert who was undoubtedly the most far along at researching bluespace before his disappearance.
The only other speculation I can provide is just a possible relation to the Doppler blueshift effect and anomalous region Space Station 13 was built in.
Whatever's here Nanotrasen isn't the only one interested in it, and I'm not just talking about plasma.

**Comment by ATH1909** [comment]
I wonder how this interacts with holopads...

**Comment by actioninja** [comment]
now this is epic
