### ISSUE TITLE
Virus had a cure of tomato juice despite having a resistance of -1

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#45073]
It was quite odd. It showed up as having a cure of tomato juice (and having a resistance stat of -1) in the pandemic(,) and people were able to cure it with tomato juice (and presumably also learn that the cure was tomato juice with health analyzers, since all of the pandemics were sabotaged and the cure was learned before any new ones could be set up).

I'd rather not publicly post the details of my virus, but if it's absolutely necessary to finding out the source of this bug, I'll PM its details over Discordto people who ask for it (for the purposes of replicating the bug).

**Comment by kriskog** [comment]
I wasn't able to reproduce this locally, cure picked from tier 1 as expected. As for the crew finding out about the cure with health analyzers, thats working as expected for a non stealthy virus.

Keep this open for a while, in case someone can bring in reproduction steps.

**Comment by kriskog** [comment]
Havent seen any new reports of this, make a new issue if it happens again.
