### ISSUE TITLE
Removing a bola from someone will teleport it back to them once their own removal timer finishes.

### ISSUE THREAD

**Issue by Dawson1917** [tgstation/tgstation#45086]
As title said. Anyone legcuffed with a bola (specifically reinforced ones) has a fairly lengthy timer while they try to remove it. It's much quicker for someone else to take it off you. If you start the removal process on yourself and another person removes the bola from your leg before it ends, the bola will teleport back to where you're standing once your removal timer completes, even if they put the bola in a container.

## Reproduction:

1. Have a reinforced bola thrown at you.
2. Hit resist or click the alert to begin removing it.
3. Have someone nearby remove your legcuff and run off with the bola.
4. In 2-3 seconds, once your removal timer finishes, the bola will teleport to your feet.

**Comment by actioninja** [comment]
This normally just means that there's not the second check after the do_after to make sure the conditions are still valid.
