### ISSUE TITLE
Armor Slot Isn't Checked for Cult Magics

### ISSUE THREAD

**Issue by MoonFalcon** [tgstation/tgstation#45081]
It shows up in logs as "James Chad has stunned you with the stun baton!" but immediately after I was unable to talk. My null rod was the reaper scythe and it was sitting on my armor slot (I had holy robes on).

James Chad holds up his hand, which explodes in a flash of red light!
James Chad whispers, "Fuu ma'jin!"
James Chad has stunned you with the stun baton!
You find yourself unable to speak!

Issue reported from  Round ID: 112694 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1471

**Comment by Whoneedspacee** [comment]
https://github.com/tgstation/tgstation/blob/7d4e7ee985be512175d8c8f89c52bcbc43c78412/code/datums/components/anti_magic.dm#L13

does this not check when the component is first added if someone has already equipped it

**Comment by XDTM** [comment]
The slot defines seem to lack the armor inventory slot, so it gets skipped. Should be a simple fix

**Comment by kriskog** [comment]
Checked attack logs, the guy had a stun baton which he used to stun you after the cult spell. That text is unrelated to the cult spell issue.

**Comment by XDTM** [comment]
They were still silenced, plus they didnt get the spellblock message, so the bug stands.

**Comment by isaacsmothers** [comment]
He didn’t have a baton, not one I could see.

**Comment by ExcessiveUseOfCobblestone** [comment]
they're not related, there's no way for that to work outside of an admin varediting a baton to look like a cult stun paper.

**Comment by Dorsisdwarf** [comment]
It's still a bug if he used a baton to down you and the stun-mute to mute you

**Comment by kriskog** [comment]
The baton isnt part of the issue, cult spell working is. Ignore the baton, its unrelated. Attack logs showed him using the cult stun on the chaplain, then batoning.

**Comment by ExcessiveUseOfCobblestone** [comment]
> The slot defines seem to lack the armor inventory slot, so it gets skipped. Should be a simple fix
