### ISSUE TITLE
Deepfrying kitchen knives infinitely

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#45102]
Deepfrying a kitchen knife then putting it in a bowl to make a custom salad instantly spawns the un deepfried knife back under you, enabling people to make infinite knife salads as long as they have enough bowls

Step 1
Deepfry knife
Step 2
Put knife in bowl to make salad

**Comment by ATH1909** [comment]
https://github.com/tgstation/tgstation/issues/44123

**Comment by Qustinnus** [comment]
duplicate of above
