### ISSUE TITLE
Departmental IDs are Join-Bound Vs. In Lockers

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#45122]
Dept budgets can literally be btfo'd because a head didn't join the department. Basically this causes balance to be out of whack because you can't ALWAYS assume someone has access to the budget (lol).

_Originally posted by @ExcessiveUseOfCobblestone in https://github.com/tgstation/tgstation/pull/45089#issuecomment-509802651_

**Comment by Tlaltecuhtli** [comment]
put them in the vault

**Comment by Dawson1917** [comment]
put them in their lockers
