### ISSUE TITLE
There's no hivemind/assimilation ban

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#45123]
See title, self explanatory, I checked under both names.

**Comment by actioninja** [comment]
@Kierany9

**Comment by Whoneedspacee** [comment]
isnt this it https://github.com/tgstation/tgstation/blob/6e9915ff1860071fe43eeaee20b07306f10b04ce/code/modules/antagonists/hivemind/hivemind.dm#L5

**Comment by bgobandit** [comment]
it isn't in the banning panel

**Comment by Whoneedspacee** [comment]
im confused why thats not an auto generated thing for antagonist roles but yeah i guess it isnt
