### ISSUE TITLE
Last resort (ling ability) doesn't work

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#45125]
Issue reported from  Round ID: 112860 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

Bear in mind that this was done while I was in hand-cuffs and headless. this MAY influence how this ability works, seeing how I was able to see ghosts for some reason while headless as well. I used the last resort ability, and instead of turning me into a head-slug, I took damage and was told I was covered in a shower of blood as if I had been hit by the ability instead of actually using it, and I believe there was a small explosion. From what I could tell the borg carrying me wasn't affected, but it may have been.  I didn't try using this without being cuffed and having a head so that may be the issue - that or the borg riding?

**Comment by actioninja** [comment]
I don't think you're supposed to be able to use it while not "alive" but I'm not entirely sure on that.

**Comment by Jarektheraptor** [comment]
If it matters, when I regenerated my head, I lost the ability to see ghosts. Did not try last resorting after I regenerated my head, just in case the glitch happened because I was headless. Also, I was "alive" in the sense I was in control of my character my character wasn't dead or in critical. I was able to attempt to resist out of the borg buckle and such.

**Comment by YPOQ** [comment]
```
[2019-07-11 04:53:59.328] runtime error: Cannot execute null.applyOrganDamage().
 - proc name: sting action (/datum/action/changeling/headcrab/sting_action)
 -   source file: headcrab.dm,27
 -   usr: Odell Cromwell (/mob/living/carbon/human)
 -   src: Last Resort (/datum/action/changeling/headcrab)
 -   usr.loc: the floor (166,102,2) (/turf/open/floor/plasteel/white)
 -   call stack:
 - Last Resort (/datum/action/changeling/headcrab): sting action(Odell Cromwell (/mob/living/carbon/human), null)
```
Last resort runtimes if you or any human in range doesn't have eyes.

https://github.com/tgstation/tgstation/blob/55209907f79ec27a13ec5a0674d11dae88e817a5/code/modules/antagonists/changeling/powers/headcrab.dm#L27
