### ISSUE TITLE
Removing antag status from all members of a cult (clock or blood) doesn't remove the cults in end-of-round screen

### ISSUE THREAD

**Issue by Dawson1917** [tgstation/tgstation#45136]
There's no code to remove them that I'm aware of. This can cause a bit of confusion at end of round if admins removed a cult to manually alter the gamemode or decided to cult themselves to test things out in the thunderdome. Oversight?

![image](https://user-images.githubusercontent.com/51552884/61085865-8075b180-a470-11e9-8ca0-5c4101492402.png)

## Reproduction:

1. Turn yourself into a blood cultist or clock cultist.
2. Remove your cult/antagonist status in the traitor panel.
3. End round / wait for round end. The cult and its objectives will still be shown in the end of round screen despite having no members.

**Comment by JJRcop** [comment]
You can delete your testing teams using Check Antagonists when you're done to prevent them from showing up on the round end screen.

**Comment by Dawson1917** [comment]
> 
> 
> You can delete your testing teams using Check Antagonists when you're done to prevent them from showing up on the round end screen.

That works. Thank you
