### ISSUE TITLE
Oversight in sentient disease cures

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#45139]
https://www.reddit.com/r/SS13/comments/cbq4fv/uncurable_disease_on_tg/

tldr;

A sentient disease can roll two chems that react with each other as its cure, effectively making the sentient disease not HAVE a cure (well, maybe if you dripped the cures into them in sub-1u doses?). It could still be overwritten by another virus, of course, but still, this seems unintentional.

The example given in the thread was a sentient disease with a cure of phenol+lithium, which would react with each other in the bloodstream to form corazone.

**Comment by kriskog** [comment]
Ah, thats bad. Let me think about what to do about this.

**Comment by Dennok** [comment]
Only one that i see, make blacklist for reacting chems, it can be maked procedural genereting, basing of actual reactions.
After set one chem, on try to set 2 chem, check if it react or no.

**Comment by FloranOtten** [comment]
> Only one that i see, make blacklist for reacting chems, it can be maked procedural genereting, basing of actual reactions.
> After set one chem, on try to set 2 chem, check if it react or no.

...what?

**Comment by Dennok** [comment]
need, more, checks.
