### ISSUE TITLE
Brainwashing Surgery doesn't work.

### ISSUE THREAD

**Issue by Fishimun** [tgstation/tgstation#45140]
I discovered this issue while i was playing md, after buying the brainwashing disk, inserting it, updating console and trying to start the surgery by using drapes on the head. that the brainwashing surgery wasn't even an option despite it being in the console

**Comment by kriskog** [comment]
No advanced surgeries work either

**Comment by Dennok** [comment]
I think all problem in disk. Like with debug, it now brocken bit i make fix for it..

**Comment by Akrilla** [comment]
I got stuck with a deep-rooted trauma all game because couldn't do lobotomy

**Comment by RandolfTheMeh** [comment]
I recall a similar issue yesterday, where none of the experimental surgeries researched and synced onto an operating computer were available to the adjacent surgery table. Seems whatever linked the two isn't working.

**Comment by kriskog** [comment]
Closing in favor of #45163
