### ISSUE TITLE
VTEC & Disabler Cooling cyborg combat upgrade modules are completely nonfunctional

### ISSUE THREAD

**Issue by ynot01** [tgstation/tgstation#45143]
## Reproduction:
Place the upgrade modules in a borg and see if they work

>they don't

**Comment by nemvar** [comment]
I dived a bit into a cryborg upgrades recently, and it doesn't surprise me that they are broken. VTEC didn't catch the movespeed modifier train and disabler only works on secborgs.

Not even convinced it's worth fixing VTEC, the effect is really cancerous.
