### ISSUE TITLE
Smart Wires Don't Power Shield Wall Generators on Them

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#45151]
## Round ID: 112957

![image](https://user-images.githubusercontent.com/37246588/61144834-ffd0a880-a4a3-11e9-9955-591b546d3dee.png)

They are on wires, there is power, error message : needs to be on a wire

**Comment by actioninja** [comment]
so turns out shield wall generators aren't powered machines for whatever reason and completely re implement all the functionality of powered machines incorrectly.
