### ISSUE TITLE
Eternal Youth appears twice in the code for the purchasable abilities of sentient diseases

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#45150]
With two different prices, no less (one is priced as a medium non-healing symptom, while the other is priced as a strong healing(?!) symptom):

```
/datum/disease_ability/symptom/medium/youth
	symptoms = list(/datum/symptom/youth)
	short_desc = "Cause victims to become eternally young."
	long_desc = "Cause victims to become eternally young. Provides boosts to all stats except transmissibility."
```

```
/datum/disease_ability/symptom/powerful/heal/youth
	symptoms = list(/datum/symptom/youth)
```

Link to the page of code that I found these two abilities in: https://github.com/tgstation/tgstation/blob/master/code/modules/antagonists/disease/disease_abilities.dm

**Comment by py01** [comment]
each one has different costs though, and both can be purchased. Not sure if it was intentional, but some diseases want to purchase both to get certain stats.

**Comment by kriskog** [comment]
I would check the initial PR for whether its intentional or not, but its a good buff symptom so is handy for a second pickup I guess.

**Comment by ExcessiveUseOfCobblestone** [comment]
it wasn't
