### ISSUE TITLE
Fugitive hunter shuttle can't move to station z-level with its shuttle console

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#45156]
Issue reported from  Round ID: 112972 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1470

The fugitive hunter shuttle can't move to the station's z-level by using its shuttle console (shows up as locked). If you send it to Z level 2 with the shuttle manipulator, the option to send it to deep space appears on the console.

**Comment by kriskog** [comment]
Can you confirm this is not because the public mining shuttle is blocking it? Same happens to the whiteship if there is another shuttle at the dock.

**Comment by 81Denton** [comment]
I'll try to test it on a local server and give you an update.

**Comment by 81Denton** [comment]
The issue lies in the hunters' shuttle and navigation consoles: 
`possible_destinations = "huntership_away;huntership_home;huntership_custom"`

huntership_away is completely unused and should be replaced with a different dock, for example the white ship dock.
The navigation console is missing `jumpto_ports`; should be an easy fix.

**Comment by 81Denton** [comment]
I'll wait until #44802 is finished before I start working on it anyway.

**Comment by tralezab** [comment]
and i'll hurry up so you can work!
