### ISSUE TITLE
the coldroom's freezer makes the coldroom so cold that it damages human chefs

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#45165]
Why isn't the coldroom's freezer freezer's default target temperature set to 261.15K (1 degree above the temperature that the (SS13) human body start to take cold damage at) or something? I get that it's there for "muh flavor" purposes, but it's super annoying to deal with as a chef.

**Comment by kriskog** [comment]
It was intentional, wear a jacket when you go inside the coldroom which is also where the jackets are stored hmmm. Anyway #41799, I'll leave it open for a bit in case someone wants to change it.

**Comment by optimumtact** [comment]
trust in your self kriskog
