### ISSUE TITLE
Surgeries do not get updated

### ISSUE THREAD

**Issue by Hadzabadza** [tgstation/tgstation#45163]
It is not possible to do anything but basic surgeries even if you've researched everything and updated the computer. The options don't appear in the drape menu. 
## Reproduction:
Research advanced+ surgeries and try performing them on anyone. 

The tables and computers were all rebuilt, but connected.

**Comment by bobbahbrown** [comment]
Attempted to reproduce on https://github.com/tgstation/tgstation/commit/e7169d230c7dd9524a4327992c7e03ae583f7b85, couldn't.

**Comment by kriskog** [comment]
This is related to  #45140, same issue. Surgery table with computer isnt letting you do non-basic surgeries for some reason.
Reproduced on current master. Metastation surgery room, vv shows the computer linked to the table as expected.

Reproduction:
Research advanced surgeries
Update surgery computer
Attempt to drape someone, no advanced surgeries show up in the list

**Comment by bobbahbrown** [comment]
Clarified in discord, but yes this is reproducible. My working as intended was indeed not working as intended.

**Comment by CPTANT** [comment]
Confirming this is a thing. Seems to happen quite often.
