### ISSUE TITLE
Contract Kidnapped Plasma-Men lose their enviro-suit upon being sent to the syndicate holding facility

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#45175]
Issue reported from  Round ID: 113070 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

Title explains it all. If a plasma-man is sent via contractor pod their suit (or at least their helmet) will be taken from them and they will die very horribly. I don't think this is intended.

**Comment by actioninja** [comment]
feature

**Comment by Tlaltecuhtli** [comment]
dont get caught

**Comment by 81Denton** [comment]
The ninja holding facility on centcom has the same issue iirc
