### ISSUE TITLE
Stacked wires on charlie station.

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#45186]
![image](https://user-images.githubusercontent.com/4047233/61189131-4501ff80-a689-11e9-90c8-3c90e3c3d393.png)

**Comment by WJohn** [comment]
oops. easy fix.

**Comment by actioninja** [comment]
not a mapping issue, somehow this was placed, going to need to look into this.

**Comment by ShizCalev** [comment]
this was fixed at some point.
