### ISSUE TITLE
quin materials broke mech ammo printing

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#45195]
![nig1](https://user-images.githubusercontent.com/33834933/61208281-5681f080-a6f7-11e9-8cd5-651bea3711e1.jpg)
@Qustinnus

**Comment by Qustinnus** [comment]
ah I see what I fucked up. Ty

**Comment by optimumtact** [comment]
if it's a test merged bug please report it on the PR and then close the issue
