### ISSUE TITLE
Unable to Pull Resources out of Ore Silo Linked Machines

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#45194]
## Round ID:
113172 and 113176
## Reproduction:
Unable to pull resources out of machines connected to the ore silo. The one exception is the ORM. Additionally, robo fabricators do not list required resources for building an item.

**Comment by kriskog** [comment]
You should be including testmerges. In this case it is caused by one: #45118

**Comment by optimumtact** [comment]
if it's a test merged bug please report it on the PR and then close the issue

**Comment by Qustinnus** [comment]
fixed

**Comment by adamkad1** [comment]
its still like this on terry
