### ISSUE TITLE
Contractor extractor can take multiple people

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#45191]
if someone is on the tile the extractor lands on, when the target is inserted it takes everyone who was on that tile to the jail. Your tc gain is multiplied by the number of people sent up.
@Akrilla 

7/15 - It also appears you can drag anyone into the pod to send them. This removes the contract from the contractor's list.

**Comment by Akrilla** [comment]
EPIC

**Comment by Akrilla** [comment]
that's pretty major thanks for issue

**Comment by ATH1909** [comment]
Does this work with monkeymen? Because if so... Hoooooo boy.

**Comment by Akrilla** [comment]
Putting anyone in the pod isn't a bug, you just fail your contract and receive no pay.

**Comment by Akrilla** [comment]
And tbh I'm fine with it sending multiple people, but having it multiply your TC is *not intended*...

**Comment by JohnFulpWillard** [comment]
Fixed by contractor being removed
