### ISSUE TITLE
Dark energy sword null rod option is invisible

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#45206]
Choose the dark energy sword option when selecting a null rod, it has a sprite on your character when held but in your hand it is invisible and it will become invisible if dropped or equipped. Can be picked up still by right clicking/alt clicking on the tile its on

Issue reported from  Round ID: 113214 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

**Comment by nemvar** [comment]
My fault will fix.
