### ISSUE TITLE
The Drake "floor is lava" attack causes some annoying space wind

### ISSUE THREAD

**Issue by Jarektheraptor** [tgstation/tgstation#45209]
Issue reported from  Round ID: 113235 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471

This is a really small thing, but can, if you are unlucky, get you killed during the fight. When the drake does the attack that causes you to be trapped in a small little box, you have to dodge and stand on the green symbol to avoid being cooked in lava. After the first symbol comes and goes, you may occasionally get space wind which can and will be annoying and push you around. This can sometimes fuck you over enough to push you off the symbol you're supposed to be standing on and cause you some damage as it bumps you off the tile and into the lava.

**Comment by Dawson1917** [comment]
Related to [44623](https://github.com/tgstation/tgstation/issues/44623)? Someone mentions it happening during the drake fight in the comments. Very annoying bug

**Comment by ATH1909** [comment]
Just toggle on magboots when it uses that attack smh

/joke

**Comment by Dennok** [comment]
Just bucle to chair when it uses that attack smh

/joke

**Comment by kriskog** [comment]
Should be fixed by #44980

**Comment by Dennok** [comment]
Reopen it please @optimumtact .

**Comment by Cyprex** [comment]
Is this still an issue? #45701 Should have fixed this.
@Jarektheraptor

**Comment by kriskog** [comment]
Yeah, should be fixed
