### ISSUE TITLE
The harm intent punches of bananium golems always miss

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#45204]
Bananium golems have a punchdamagelow value of 0 and a punchdamagehigh value of 1.

Unfortunately, this means that they can never hit with their harm intent punches (not even to deal that single point of damage from punchdamagehigh) (code from: https://github.com/tgstation/tgstation/blob/c34fb454df3dee46c8922d9afb689080f61709d8/code/modules/mob/living/carbon/human/species.dm):

```
var/miss_chance = 100//calculate the odds that a punch misses entirely. considers stamina and brute damage of the puncher. punches miss by default to prevent weird cases
		if(user.dna.species.punchdamagelow)
			if(atk_verb == ATTACK_EFFECT_KICK) //kicks never miss (provided your species deals more than 0 damage)
				miss_chance = 0
			else
				miss_chance = min((user.dna.species.punchdamagehigh/user.dna.species.punchdamagelow) + user.getStaminaLoss() + (user.getBruteLoss()*0.5), 100) //old base chance for a miss + various damage. capped at 100 to prevent weirdness in prob()
```
Since their punchdamagelow value is 0, their miss_chance value remains at 100.

Also, I don't think that the basic_hit proc that's used by a few martial arts has been updated to reflect the new unarmed combat system: https://github.com/tgstation/tgstation/blob/e13330fa9565b5b391ddd451cb0782b472c65a21/code/datums/martial.dm

**Comment by ATH1909** [comment]
Note: this is purely codediving/speculation; I have not seen this in practice yet. A video or something demonstrating this issue would be nice.

**Comment by bobbahbrown** [comment]
Waiting for confirmation from Denton but I believe this is an intended feature.

**Comment by optimumtact** [comment]
since it's obviously not a bug it can be closed since that is really a forum or discord discussion about if it should be changed
