### ISSUE TITLE
Protolathe not showing material costs

### ISSUE THREAD

**Issue by RandolfTheMeh** [tgstation/tgstation#45207]
Issue reported from  Round ID: 113234 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
Synced research at a security protolathe and was greeted with this, not too many details to give unfortunately due to round circumstances.
![reporting_this](https://user-images.githubusercontent.com/20852857/61255846-fb202480-a72f-11e9-9333-99ba6ecf1ac0.png)

Reporting client version: 512.1471

**Comment by RandolfTheMeh** [comment]
Thought it fetched this too but current testmerge(s):
#45118: 'Floydmats (Datum materials) & custom toolboxes' by Qustinnus at commit 09f6ce0500

**Comment by ExcessiveUseOfCobblestone** [comment]
try to dispense some of the material while you're at it

**Comment by ExcessiveUseOfCobblestone** [comment]
dispense doesn't work either

**Comment by ExcessiveUseOfCobblestone** [comment]
Testmerge bug

**Comment by Qustinnus** [comment]
fixed
