### ISSUE TITLE
Arena Shuttle just dumps you in empty space

### ISSUE THREAD

**Issue by SpacePrius** [tgstation/tgstation#45219]
## Reproduction: Go into the front teleporter on the arena shuttle, welcome to empty space where you will inevitably die.

![image](https://user-images.githubusercontent.com/26174449/61270927-16f7ea80-a771-11e9-913d-a505415a6a4e.png)

**Comment by SpacePrius** [comment]
Something to note here, I did some scouting as a ghost, and the arena DOES SPAWN on the z level, but it seems to just dump you out in the middle of nowhere.

**Comment by Gamer025** [comment]
This just happened in round "117519" so clearly the bug is still present (referring to the Needs Reproducing" tag).
Maybe the shuttle should just be removed from buying until the teleportation into the arena is fixed.
