### ISSUE TITLE
backpack jetpack is slower than internals jetpack

### ISSUE THREAD

**Issue by actioninja** [tgstation/tgstation#45218]
#44777 fucked this up, backpack jetpack is supposed to be faster and it's not. Just chased down a bomber and assblasted him.

**Comment by actioninja** [comment]
@YakumoChen

**Comment by wesoda25** [comment]
Yeah I noticed this

**Comment by YakumoChen** [comment]
that doesn't make any sense. I tested this when I made the PR.

**Comment by YakumoChen** [comment]
The internals jetpack shouldn't even affect your space move speed, it should use your current space move speed.
