### ISSUE TITLE
Crusher mark does not detonate if it’s been placed by another crusher

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#45224]

**Comment by kriskog** [comment]
Follow the issue template, its there for a reason.

**Comment by HomocidlePancakes** [comment]
## Round ID: None

## Testmerges: None

## Reproduction:
Get two crushers, mark a target with one, hit with another. Mark won't detonate.

**Comment by TheBonded** [comment]
intended, marks are independant between crushers
