### ISSUE TITLE
notification for becoming an obsessed isn't very noticeable

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#45231]
I have seen both me and a traitorous clown not realize that we were obsesseds until we checked our moods (which had already gone to "suicidal").

The notification for becoming an obsessed should be altered to include really big text and preferably a distinctive sound.

**Comment by Akrilla** [comment]
Doesn't obsessed have the camera greet sound?

**Comment by tralezab** [comment]
it do but i agree with the big text
