### ISSUE TITLE
Voice of god permanently mutes people

### ISSUE THREAD

**Issue by MortoSasye** [tgstation/tgstation#45241]
Issue reported from  Round ID: : 113375 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1472

Had a curator say QUIET with voice of God after I gave them the trauma via lobotomy surgery, was permanently muted and the only way I got to be able to talk again was via an admin giving me mime spells, doing a vow of silence and breaking it shortly after.

**Comment by XDTM** [comment]
Curator has a x2 duration multiplier on the quiet command (because librarian). So from 30 ticks it becomes 60 ticks, which might be 120 seconds if it's life ticks, or more if they had other bonuses. 
Are you positive it was permanent and not just long?

**Comment by SuperNovaa41** [comment]
Probably not around
