### ISSUE TITLE
Neutral mood gives positive santity

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#45248]
1. Have 0 total mood
2. Sanity rises up to 125

Expected behavior is for sanity to stay level at 100

**Comment by YakumoChen** [comment]
I believe the default sanity gives you a very low mood boost over time.

**Comment by kriskog** [comment]
@Qustinnus Whats the intended behaviour here?

**Comment by Mickyan** [comment]
I checked with him before making the report
