### ISSUE TITLE
Wrong sanity icon at roundstart

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#45249]
As you spawn in the red sanity icon alerting you of negative sanity will be visible, although your sanity will be neutral if you check by clicking the mood icon. 
This persists until you reach a different sanity tier and the icon correctly updates.

Note that this will currently be automatically cleared by #45248 in most situations so it may be harder to debug until that's fixed.

**Comment by kriskog** [comment]
After just spawning in, clears after a few seconds.
![image](https://user-images.githubusercontent.com/33292112/61546278-83ad0680-aa49-11e9-9d99-20b998569c96.png)
