### ISSUE TITLE
Engi borg can't refill psuedocircuits

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#45251]
This has been an issue for awhile but I only just now got around to it. 

Psuedocircuits were originally made able to be refilled by using other random circuits on them or something, if I recall, but they can no longer be refilled, even via charger. Once they're gone, you have to fully reset the module to get more. This is a problem when borgs are tasked to (re)build APCs or air alarms, making you only able to build a few rooms worth of those, provided you made one of each (and you need one for the APC power cell)

**Comment by Dennok** [comment]
As i see in code, it able to recharge it by other circuits (firelock, airalarm, firealarm, apc) by attacking it by electroadaptive_pseudocircuit.
Maybe you try to recharge it by airlock circuits?
Electroadaptive_pseudocircuit recharge by recharger not intended.
Maybe add it, while we already have mats recharged by recharger.

**Comment by Dennok** [comment]
Great idea, to add link to ore silo to use mats from it.

**Comment by kriskog** [comment]
They get refilled by the same circuits they can replace, so apc, fire alarm, firelock and air alarm. This is intended.
If you want this changed, take it to the forums.
