### ISSUE TITLE
Stunrods aren't affected by EMPs

### ISSUE THREAD

**Issue by Difrit** [tgstation/tgstation#45269]
## Reproduction:

Stunrods aren't affected by EMPs from grenades or implants. Hit your EMP implant or grenade, watch it go off, and watch someone stun you down nonetheless.

**Comment by ATH1909** [comment]
I think they ARE affected, just not much.

Against stun batons, it usually just drains like 10-20% of their charge, in my experience.

**Comment by nemvar** [comment]
Not a bug.

**Comment by kriskog** [comment]
Loses cell charge, but not all at once. Not a bug.
