### ISSUE TITLE
Shuttles have no atmosphere

### ISSUE THREAD

**Issue by Timonkeyn** [tgstation/tgstation#45279]
Issue reported from  Round ID: 113532 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471

they dont have an atmosphere. its the same Thing on the 2 rounds before that.
you also cant create one if you vent canisters into them. the gas just disappears.

my assumption is that the shuttle tiles are somehow not replacing the space tiles when they arrive. ->no atmos

**Comment by kriskog** [comment]
Happens after #44980 got merged. See 45280

**Comment by ATH1909** [comment]
*golfclap*

**Comment by 81Denton** [comment]
time 2 test in production

![testing](https://user-images.githubusercontent.com/32391752/61580562-e8349800-ab13-11e9-8204-cadf83e5f80d.PNG)

**Comment by MCterra10** [comment]
orang man bad
