### ISSUE TITLE
Pubby map issues

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#45285]
Atmos has a head of security request console
![image](https://user-images.githubusercontent.com/33292112/61572398-175bf280-aa9d-11e9-8d7d-05a1d487cddf.png)

Still has a cakehat in the bar
![image](https://user-images.githubusercontent.com/33292112/61572410-496d5480-aa9d-11e9-84c2-9bc98acb389a.png)

Bar/kitchen backroom has a sink on top of a table, and a keycard authentication device on top of the techfab.
![image](https://user-images.githubusercontent.com/33292112/61572419-7e79a700-aa9d-11e9-8483-b155bfbeed9c.png)

**Comment by nemvar** [comment]
I will be honest, I forgot that pubby is a real map when making the cakehat PR.

**Comment by Putnam3145** [comment]
Also has no native nanite setup, though this is minor
