### ISSUE TITLE
Deoxyribonucleic Acid Saboteur leaves uncurable mutations

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#45287]
## Reproduction:
Get a disease with Deoxyribonucleic Acid Saboteur.
Wait for it to stage up to 5, and you get a mutation.
Cure the disease.
Watch the mutation stick around, despite not hitting the treshold for that.
Mutation is uncurable, both by mutadone and genetics scrambling.

I assume this is happening after the genetics rework, this was probably overlooked?

**Comment by Dawson1917** [comment]
Deoxyribonucleic acid saboteur is meant to leave the mutations even after curing the disease as one of its stat threshold upgrades. #45201 touched mutadone, could have something to do with why mutadone isn't curing the mutations anymore

**Comment by kriskog** [comment]
Tested on current master, other mutations are curing fine so its not a mutadone problem.

**Comment by kriskog** [comment]
#46347 should resolve this
