### ISSUE TITLE
Latejoin or midround traitors don't get the SM Sliver extraction kit

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#45296]
Latejoin traitors with the SM sliver objective apparently don't get the required kit. Round ID 113600 on Terry.
This happened during testing of the new dynamic gamemode, but according to the author is not a bug with dynamic gamemode.

**Comment by Cyprex** [comment]
No issues with the Nuke core kit, TheChosenEvilOne said he suspects that person simply had no space in their inventory. For what it's worth, I used SDQL2 in the original round and there were no SM sliver extraction kits in the world, so it's not like they accidently dropped it or something.

**Comment by ShizCalev** [comment]
Nuke core kit and supermatter kits are both coded the same way, so it is likely they just didn't have inventory space.

Should probably add a check for that and allow them to redeem the item from their uplink without (x) amount of time (preferably short, so they can't just spawn it once they finally get to the crystal or some shit like that), so they can recover it in the case of failure. (I would say just dropping it on the ground would be fine, but that'd likely blow the agent's cover if they were an assistant and spawned in a busy area or some shit.)

**Comment by SethLafuente** [comment]
Prog traitor killed this bug

**Comment by Sealed101** [comment]
traitors get their gear on request via uplink. this issue should be investigated further for antags that still get their toolset when joining the round (wizard, changeling(?), blood brothers)

**Comment by Sealed101** [comment]
still an issue in some capacity apparently as there was at least one report of this happening with a midround changeling

**Comment by distributivgesetz** [comment]
this is weird, they should get a fallback action that droppods the equipment in if it fails

**Comment by distributivgesetz** [comment]
Fixed in #60789
I tested getting the nuke core objective as a space changeling on local and I got the action to call in a droppod, so I'll close this issue as fixed for now
