### ISSUE TITLE
Cyborg Deconstruction is broken and dupes parts.

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#45301]
## Round ID:113622

Deconstructing a borg seems to yield a fully assembled cyborg shell as well as each cyborg part, without deleting the borg. However, I couldn't deconstruct twice.

**Comment by Cyprex** [comment]
Runtime:
proc name: deconstruct (/mob/living/silicon/robot/proc/deconstruct)
usr: booktower/(Mate Pulsarhook)
usr.loc: (Pirate Shuttle (56, 167, 11))
src: B.E.E.P (/mob/living/silicon/robot)
src.loc: the pod floor (56,166,11) (/turf/open/floor/pod/dark)
call stack:
B.E.E.P (/mob/living/silicon/robot): deconstruct()
B.E.E.P (/mob/living/silicon/robot): attackby(the wrench (/obj/item/wrench), Mate Pulsarhook (/mob/living/carbon/human), "icon-x=8;icon-y=5;left=1;scree...")
B.E.E.P (/mob/living/silicon/robot): attackby(the wrench (/obj/item/wrench), Mate Pulsarhook (/mob/living/carbon/human), "icon-x=8;icon-y=5;left=1;scree...")
the wrench (/obj/item/wrench): melee attack chain(Mate Pulsarhook (/mob/living/carbon/human), B.E.E.P (/mob/living/silicon/robot), "icon-x=8;icon-y=5;left=1;scree...")
Mate Pulsarhook (/mob/living/carbon/human): ClickOn(B.E.E.P (/mob/living/silicon/robot), "icon-x=8;icon-y=5;left=1;scree...")
B.E.E.P (/mob/living/silicon/robot): Click(the pod floor (56,166,11) (/turf/open/floor/pod/dark), "mapwindow.map", "icon-x=8;icon-y=5;left=1;scree...")

**Comment by Cyprex** [comment]
There's another runtime which I forgot to paste, TheChosenEvilOne mentioned that it runtimes when trying to remove the flash.

**Comment by Sealed101** [comment]
we've had a few borg shell fixes and cleanups and i don't think i've seen any dupes of parts or missing parts or anything.
