### ISSUE TITLE
Masterwork boots has an improper name

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#45311]
![image](https://user-images.githubusercontent.com/10399117/61586390-1c36aa00-ab62-11e9-8b9b-e748ea59e7f1.png)

**Comment by Krysonism** [comment]
Where these varedited? I thought i named them Hugs-The-Feet lizard skin boots

**Comment by nemvar** [comment]
Can't find anything that would causes this.

**Comment by kriskog** [comment]
They are indeed called Hugs-The-Feet lizard skin boots in  the code, I first assumed they took the name of whichever lizard previously owned the skin but I guess only meat keeps that info. Let's assume it was some mproper varediting?

**Comment by ATH1909** [comment]
*tips hat*
m'proper

**Comment by ATH1909** [comment]
maybe someone forgot the "i" in "improper"?

**Comment by ATH1909** [comment]
`	name = "\improper Hugs-The-Feet lizard skin boots"`
Hm, it doesn't look like they misspelled it...

**Comment by Akrilla** [comment]
Yeah basically 100% a varedit
