### ISSUE TITLE
Biogenerators Cannot Produce Products

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#45326]
## Round ID:
113687

## Testmerges:
#45280: 'Revert "Make ChangeTurf to keep air by default."' by Cyprex at commit f9a4af7493 
#45118: '[READY] Floydmats (Datum materials) & custom toolboxes' by Qustinnus at commit 98778b7276 

## Reproduction:
Produce biomatter, attempt to produce products. You will notice that all the products have a biomatter cost of zero. They will not produce. Allegedly does not throw runtimes.

**Comment by Qustinnus** [comment]
fixed in latest
