### ISSUE TITLE
Summon item spells (Wealth, lightning, etc) don't work

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#45335]
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 113704
BYOND Version: 512.1471
Server revision compiled on: 
Master commit: 95509c55baeb2601e134539d10b3a9e8cb5bd2f3
The following pull requests are currently test merged:
#44639: '[Ready] Ports dynamic gamemode from /vg/' by TheChosenEvilOne at commit c5bdf0e888
#43148: '[s]Temp workaround for admins matching stickybans because of a byond bug.' by MrStonedOne at commit e34fa30ce1

Local commit: 3a725c37b2eb8246485d07ccd6d3593cfcd94c4a
Server tools version: /tg/station 13 Server v3.2.6.2

Spells such as thrown lightning and summon wealth do not summon the proper items unless there's already an item in the user's hand, in which case it drops the item and puts the summoned item in their hand. Spells were given to people by a devil, but I took the spell away and gave it back just to see if it's an issue with the devil- it's still broken either way.

**Comment by BeeSting12** [comment]
Credit to BrotherBeyond for finding the bug and finding out how to make it work.

**Comment by necromanceranne** [comment]
I actually tried using these spells the other day for admemery but it wasn't working. I thought I somehow screwed up. Didn't realize they were broken.

**Comment by timothymtorres** [comment]
Devil was removed from the codebase a while back and I'm pretty sure these spells no longer exist.
