### ISSUE TITLE
TRAIT_NOMETABOLISM species can't heal cloneloss with meds

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#45378]
#44846 didn't account for cloneloss, which isn't that uncommon due to cloning, slimes, etc. The only way for them to even heal it is a slime extract, asklepius' rod or a slime cookie.

Since those three species are very rare, I think it would be a decent solution to make them immune to clone damage as well.

**Comment by ExcessiveUseOfCobblestone** [comment]
skeletons and androids don't have genetics anyways.
