### ISSUE TITLE
Backpacks are missing/using the wrong inhands.

### ISSUE THREAD

**Issue by nemvar** [tgstation/tgstation#45385]
The following issues exist with the item_state for the following items. Missing indicates that the relevant icon does not exist.

Explorers backpack, missing
Mime backpack, missing
Botany backpack, missing
Chemistry backpack, missing
Genetics backpack, missing
Science backpack, missing
Medical satchel, wrong one. Displays a backpack instead of the satchel
Viro satchel, missing
Chemistry satchel, missing
Genetics satchel, missing
Science satchel, missing

relevant files:
https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/storage/backpack.dm
https://github.com/tgstation/tgstation/blob/master/icons/mob/inhands/equipment/backpack_lefthand.dmi
https://github.com/tgstation/tgstation/blob/master/icons/mob/inhands/equipment/backpack_righthand.dmi

**Comment by py01** [comment]
there are no inhand sprites for those items in the relevant .dmi's, did they exist before and get removed somehow? or were they never sprited

**Comment by py01** [comment]
looks like these sprites have never existed

**Comment by py01** [comment]
No sprites have seperate backpack and satchel inhand sprites. I'm going to make .dmi states with a placeholder grey backpack for all of these things with no sprites then I'll poke a spriter
