### ISSUE TITLE
Mining base sec vendor has no access/cost requirements

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#45393]
Doesnt need access, also everything is free.

**Comment by Dawson1917** [comment]
Sends prisoner to gulag. 100 points, they'll be done in a hot minute.
Prisoner mines 10 tiles and harvests a 1-3 reaction gibtonite.
Beepsky dead, free baton.
Sec locker, free bowman, free sechuds, free sec clothes.
Vendor costs nothing, free heavy vest and helmet and 5 flashbangs and bolas and cuffs.
Breaks window and goes to station through public shuttle.

Yup, it's gamer time.

**Comment by GravitronBlue** [comment]
Hardly needs mentioning that anyone can take the public lavaland shuttle down to the mining outpost to loot the security post. The security bot doesn't even resist being dragged away from its post and into lava, making it a free baton with little risk of being caught.

Although Dawson you should double check the security closet, as I never recall finding a security bowman headset or radio in it, just sechuds, armor, jumpsuits, and seclite.

**Comment by SpacePrius** [comment]
i'm taking a look at the problem in question and I really am not seeing why the machine is letting anyone use it. Its probably not a map problem because the thing isn't reconfigured at all.
