### ISSUE TITLE
HOP line tickets lit with a lighter never actually burn up

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#45395]
they just stay on fire forever
@Kmc2000

**Comment by tralezab** [comment]
will burn from plasma fires, but not from the lighter.

**Comment by optimumtact** [comment]
Yeah I saw this in game, not sure what the heck is going on there :laughing:

**Comment by Kmc2000** [comment]
The hell?

Did I just invent a new element?
I need to sell these fire resistant tickets to the DMV
