### ISSUE TITLE
mood seems to be broken

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#45391]
113823

i was with low mood for most of the round (2 big negative events) but somehow i had maxed sanity

**Comment by actioninja** [comment]
@Qustinnus

**Comment by Qustinnus** [comment]
yeah it's a fuckie wuckie caused by me removing some shitcode from mood. sanity is uncapped so it just goes up infinitely if your mood is good.


i rate this bug not epic out of epic
