### ISSUE TITLE
You can be blood brothers with AI (AI doesn't get traitor laws)

### ISSUE THREAD

**Issue by InsaneHyena** [tgstation/tgstation#45405]
Round ID was 113908.

**Comment by nemvar** [comment]
I suspect this is because the round type wasn't actually traitorbro and admins spawned in the bloood brothers.

**Comment by nemvar** [comment]
Actually this is a bug with dynamic.

**Comment by kriskog** [comment]
Testmerge bugs go in the PR. Referenced  this there, closing this
