### ISSUE TITLE
Null Rods do not grant Magic Immunity

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#45400]
Issue reported from  Round ID: 113831 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

![null rod brokies again oh noes](https://user-images.githubusercontent.com/40847847/61696356-8b85e700-ad78-11e9-8a90-f60626de9d00.png)

Basically, the null rod does not grant antimagic whatsoever. Either in-hand, in suit storage, in pocket, or on your belt. Nothing.

It says the spells are stopped but it doesn't actually.

This might be the culprit: [#44606](https://github.com/tgstation/tgstation/pull/44606). It was the PR that most recently touched the nullrods antimagic properties as far as I can tell.

**Comment by py01** [comment]
anti_magic_check works fine, and certain spells are stopped. This appears to be an issue specifically with magic projectiles.

**Comment by tralezab** [comment]
Yeah, they don't return BULLET_ACT_BLOCK

**Comment by tralezab** [comment]
alright that sucked, anyone looking to fix this it's not the bullet act block, though maybe that should be added anyways. the antimagic block makes sure the effects don't happen but the damage still applies. setting nodamage = TRUE is a bandaid fix but there is surely something deeply wrong internally that is causing this

**Comment by py01** [comment]
alright it looks like antimagic isn't stopping the projectile damage from being applied

**Comment by py01** [comment]
properties from projectile.dm like damage and paralyze are not being stopped

**Comment by necromanceranne** [comment]
I said it was specifically magic immunity because what spurred me to check this is seemingly the null rod wasn't protecting me from wizard events that usually it should protect from. Arcane Barrage was a fairly straight-forward test. So maybe there is more than one bug going on at the moment with antimagic.

**Comment by py01** [comment]
due to the code structure, projectile/on_hit() gets called in projectile/magic/spell/on_hit()  even if antimagic_check() fails. Making a fix. Havent investigated the summon events behavior yet.

**Comment by tralezab** [comment]
should be fixed there
