### ISSUE TITLE
CE has no private RCD

### ISSUE THREAD

**Issue by Kaffe-work** [tgstation/tgstation#45412]
The CE on MetaStation has no RCD in their office, and has to compete with the rest of the engineers for the 3 in the vendomat, and while you /can/ make more, it is essential equipment for fixing station hull breaches and creating new areas, and the CE already has a Hardsuit (only 2 hardsuits for the other engineers). 

When you do need a RCD, you often need it on the spot, and if you don't have a RCD, it may take some time to get a new one.

**Comment by nemvar** [comment]
Not a bug, basically a feature request. 
Should either here: https://tgstation13.org/phpBB/viewforum.php?f=9
Or here: https://tgstation13.org/phpBB/viewforum.php?f=10
Alternatively you can add this yourself and/or get someone else to add this for you.
