### ISSUE TITLE
Mitosis and aggressive replication doesn't actually regenerate nanites

### ISSUE THREAD

**Issue by Putnam3145** [tgstation/tgstation#45419]
```
/datum/component/nanites/proc/adjust_nanites(datum/source, amount)
```

```nanites.adjust_nanites(rep_rate)```
```nanites.adjust_nanites(extra_regen)```
This makes them both pretty much completely worthless and actively detrimental. Add a null to these as the first argument like every other adjust_nanites call and it should work.

Mitosis is pretty much completely worthless anyway, since it ruins your nanites with no way to repair them (since there's no cloud sync on them) for little gain, but hey, might as well get them to work as intended.

**Comment by ATH1909** [comment]
Could the nanite-related virus symptoms also potentially have this bug?
