### ISSUE TITLE
Insulated Gloves + Riding Borg = Shocked

### ISSUE THREAD

**Issue by Malkraz** [tgstation/tgstation#45425]
Issue reported from  Round ID: 113963 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1471

If a borg walks into an electrified grille while you're riding it and have insuls equipped, you will be shocked and stunned but no damage will occur.

**Comment by PKPenguin321** [comment]
Probably to do with https://github.com/tgstation/tgstation/pull/45291 @nemvar
