### ISSUE TITLE
regen coma causes you to deathgasp, even if your virus doesn't have stealth 2+

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#45423]
I'd like to give credit to ylwrld for finding this bug and thank him for giving me permission to post about it here (and elsewhere).

```
/datum/symptom/heal/coma/proc/coma(mob/living/M)
	if(deathgasp)
		M.emote("deathgasp")
	M.fakedeath("regenerative_coma")
	M.update_stat()
	M.update_mobility()
	addtimer(CALLBACK(src, .proc/uncoma, M), 300)
```
```
/mob/living/proc/fakedeath(source, silent = FALSE)
	if(stat == DEAD)
		return
	if(!silent)
		emote("deathgasp")
	ADD_TRAIT(src, TRAIT_FAKEDEATH, source)
	ADD_TRAIT(src, TRAIT_DEATHCOMA, source)
	tod = station_time_timestamp()
	update_stat()
```

See the problem here?

The coma proc uses M.fakedeath("regenerative_coma") instead of M.fakedeath("regenerative_coma", FALSE), the fakedeath proc's "silent" variable remains FALSE, causing the fakedeath proc to cause the host to deathgasp.

If you wanted to get really fancy with a fix for this, you could replace this segment of code...:
```
	if(deathgasp)
		M.emote("deathgasp")
	M.fakedeath("regenerative_coma")
```
...with this segment of code:
```
	M.fakedeath("regenerative_coma", !deathgasp)
```

That SHOULD work/fix the problem, right?

EDIT: cobby reminded/told me that I need to use !deathgasp instead of just deathgasp.

**Comment by ATH1909** [comment]
Someone should test to see if stealth 2+ regen coma currently makes people deathgasp twice.

**Comment by XDTM** [comment]
I could've sworn I reworked it already when deathgasp was added to the fakedeath proc.
The way I want it to act is to only give the deathcoma trait without the stealth threshold, so without it there is no fakedeath at all, only unconsciousness.
