### ISSUE TITLE
Zombies infect and bolas trap even if the hit is blocked

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#45430]
[Round ID]: 113955/113958

I was hit by a zombie, parried it with my chainsaw, but I still got infected. This is pretty lame, gay, and dumb, so please quickfix. Don't know if it happens with riot shields katanas or w/e
![image](https://user-images.githubusercontent.com/53100513/61762800-8d1bd300-ada9-11e9-9b49-bf08d04472e8.png)

/
Forgot to make this issue and played another round. Just saw a traitor block a bola with a riot shield and still get trapped, which almost got him killed. Maybe something to look at, that nothing's getting blocked.
![image](https://user-images.githubusercontent.com/53100513/61765698-8e9ec880-adb4-11e9-9c48-ba03b63d17f4.png)

**Comment by carlarctg** [comment]
FUCK i accidentally deleted the round ids. they're like 11556 or something like that

**Comment by kriskog** [comment]
I remember there was something about embed running before catch on explosive lances back when they were thrown too. Probably related.

**Comment by timothymtorres** [comment]
This was fixed in #51827
