### ISSUE TITLE
Swarmers Can't Eat

### ISSUE THREAD

**Issue by cynic716** [tgstation/tgstation#45431]
## Testmerges:

#45353: 'Adds spam prevention to clients' by optimumtact at commit 78bce66be1
#45118: '[READY] Floydmats (Datum materials) & custom toolboxes' by Qustinnus at commit 43a586260a
#43148: '[s]Temp workaround for admins matching stickybans because of a byond bug.' by MrStonedOne at commit e34fa30ce1
#45354: 'Chat Subsystem ported from TerraGov-Marine-Corps' by tralezab at commit aecc90d55e

Swarmers get the "x is incompatible with our internal matter recycler" message when trying to consume materials. This includes basic ones like iron sheets, don't know what is and isn't edible for them currently

**Comment by Dorsisdwarf** [comment]
Almost certainly the datum materials one

**Comment by Qustinnus** [comment]
resolved
