### ISSUE TITLE
Dynamic mode can call conflicting team modes

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#45443]
## Testmerges:
#44639: '[Ready] Ports dynamic gamemode from /vg/' by TheChosenEvilOne at commit 5cb2150231

## Reproduction: With a high level threat (that round was forced set to 100 threat as requested for testing purposes), multiple team modes can be called at once, these traitor objectives are often massively conflicting.

Such as a onemind Hive mind objective of "Protect the one mind" and a cult objective of "raise narsie". Both hugely conflict each other given cult requires destruction of everyone and onemind required protection of everyone oneminded.

Maybe there should be a block on calling certain modes whilst others are active?

**Comment by Time-Green** [comment]
Conflicting objectives only make things spicier

**Comment by TheChosenEvilOne** [comment]
I'll add the functionality for this, but will not make cult and hivemind block each other (yet at least).

**Comment by kriskog** [comment]
#45316 should solve this if/when it gets merged

**Comment by TheChosenEvilOne** [comment]
> 
> 
> #45316 should solve this if/when it gets merged

this too

**Comment by peoplearestrange** [comment]
> #45316 should solve this if/when it gets merged

Nice ok, didn't realise that PR was on the table.

**Comment by carlarctg** [comment]
onemind can just... leave to the mining station, or even escape on the shuttle or pods if narsie is risen. this conflict only exists if you don't think outside the box

**Comment by PKPenguin321** [comment]
#45316 will solve this specific instance, yes, but I don't think there's any actual code issue here. What objectives you have to prioritize seems like it would fall under a policy ruling (although a code solution *could* be made; regardless, this isn't a bug).

With that in mind, and because this is a problem with a test merge, it should be fine to close this
