### ISSUE TITLE
Voice Nanites don't seem to trigger/send code.

### ISSUE THREAD

**Issue by PineappleWolf** [tgstation/tgstation#45455]
Specifically, I usually program my nanites with Voice sensors detecting a voice command to trigger Adrenaline or other features.

I've tested it out with multiple users and no one can trigger nanites by using any inclusive or exclusive voice command, but using the manual remote and setting it to transfer the trigger code manually works fine.

I.e.
1 Voice Nanite set to 15 on "Adrens"
Adrenals set to Trigger 15.
Say Adrens. Nothing happens.
Take nanite remote, set to 15, set to targeted signal --> Adrenals activate.

**Comment by SynnGraffkin** [comment]
Were the adrenals active as well, not just a trigger code set?

**Comment by SynnGraffkin** [comment]
![image](https://user-images.githubusercontent.com/6519623/61987510-2c78da00-afe5-11e9-9019-3066fc236c04.png)

Maybe you just setup your triggers and stuff wrong?

**Comment by Dennok** [comment]
Sometimes of lower/upepr case sensivity, i think.  If you make code like "adrens" and say "adrens", character say "Adrens" and it dont recognised as i see.
