### ISSUE TITLE
cyborg with "ai commands " tab

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#45482]
114122

![image](https://user-images.githubusercontent.com/40974010/61909725-c195a900-aee7-11e9-9a60-bcdd728a3500.png)

**Comment by tralezab** [comment]
![image](https://user-images.githubusercontent.com/40974010/61909725-c195a900-aee7-11e9-9a60-bcdd728a3500.png)

**Comment by Sealed101** [comment]
no longer applies as of #65755
