### ISSUE TITLE
AIs can't update security records - "Too far away"

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#45490]
## Testmerges:
#45354: 'Chat Subsystem ported from TerraGov-Marine-Corps' by tralezab at commit aecc90d55e 
#44639: '[Ready] Ports dynamic gamemode from /vg/' by TheChosenEvilOne at commit 5cb2150231 
#45457: 'Tend Wounds Now Is -2 Steps and Borg-Friendly!' by ExcessiveUseOfCobblestone at commit b253806759 

## Reproduction:
Be AI
Access security record console
Try to make an update to anything
Get told you can't because you're too far away

**Comment by RandolfTheMeh** [comment]
Dupe of #45004

**Comment by nemvar** [comment]
Indeed a dupe
