### ISSUE TITLE
Trophazole Beakers attached to IV drips have a visual glitch

### ISSUE THREAD

**Issue by Swiftkor** [tgstation/tgstation#45493]
## Round ID:
114159

## Reproduction:

1. Get a beaker with trophazole in it
2. Attach the beaker to an IV drip
3. Entire tile turns the color of trophazole

This may not be limited to trophazole, It was the only chemical I tested but this may be present with other chemicals in beakers that are attached to IV poles.
![what](https://user-images.githubusercontent.com/44842426/61931191-36df9900-af3d-11e9-8e0f-826a3f20128d.png)

**Comment by Krysonism** [comment]
The mixture in question, upon information and belief, was actually thializid / water.

Putting water in my IV bags seems to cause this issue. Not sure of the cause yet.

**Comment by Swiftkor** [comment]
Oh yeah, totally forgot to mention the solution was diluted, sorry about that
