### ISSUE TITLE
not round start machines that can be linked to ore silo cant eject minerals

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#45505]
114181
build new machine like a circuit printer, put glass in, try eject, cant eject
linking it to ore silo still makes it not work

**Comment by kriskog** [comment]
Fairly sure this is a circuit printer issue specifically, I have been unable to eject mats from the roundstart ones as well. Both the full one in engineering, and the department one in robo.

**Comment by Tlaltecuhtli** [comment]
it happened with the protolathe in charlie station too

**Comment by adamkad1** [comment]
works (or does not work) the same in protolathes too, also charlie machines have the issue too (can you update them to be operable from themselves and not the console anyway?)
