### ISSUE TITLE
Hardsuits not protecting from pressure damage

### ISSUE THREAD

**Issue by ReplicantTerry** [tgstation/tgstation#45514]
Tested with CE's hardsuit and an engineer's hardsuit, we experienced pressure damage while in a vented room. Did not go into space so unsure if thermal damage is affected by this bug. This is new and may be caused by the test merges but I wouldn't know how to identify which of the three merges this is caused by.

Issue reported from  Round ID: 114264 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1464

**Comment by Darkgenerallord** [comment]
I'm pretty sure this is caused by the hat throwing PR, because the list of items no longer protecting from space corresponds with the list of head items that can't be thrown off.

**Comment by nemvar** [comment]
Yes, probably caused by hat throwing.
