### ISSUE TITLE
SpaceCoin machine might not be disappearing after 8 minutes

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#45513]
Issue reported from  Round ID: 114223 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1471

Pretty much in the title. Early in the shift a person popped the crab phone. nearly 15 minutes later, people only just noticed it's still there and are beating it to death. After a certain while nobody was losing money but seemingly the machine was still on station.

**Comment by nemvar** [comment]
![floyd](https://user-images.githubusercontent.com/47324920/61994336-bd00fa00-b079-11e9-85e3-0b42a9eb87e2.PNG)
I'm not 100% sure why it's not deleting, from what I'm seeing here, it should get deleted around 8 times.
