### ISSUE TITLE
The lightning bolt spell hits yourself if you die as a lich and revive

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#45518]
## Reproduction:

Step one, be a wizard
Step two, get the lightning bolt spell
Step three, become a lich
Step four, die
Step five, revive
Step six, cast lightning bolt and have it arc to yourself which it didn't do before you died and revived

**Comment by MrMelbert** [comment]
Lightning bolt grants you `TRAIT_TESLA_SHOCKIMMUNE` on purchase. This only applies to the body which you purchased the spell at the time.
