### ISSUE TITLE
Can not make independent wiring node.

### ISSUE THREAD

**Issue by Zaffinomlb** [tgstation/tgstation#45517]
When trying to wire I can not make an independent wiring node on any tile that has a wire on a tile next to it. 

They seem to always automatically connect, and I can not seem to place a node on existing wires.

I must be doing it wrong and if so, how do I make a node on a wire line with the new minecraft wiring.

If not then its a bug please fix :(

**Comment by Time-Green** [comment]
You don't need nodes anymore. Just put run the wire under the thing you want to power/electrify and it'll work.

**Comment by nemvar** [comment]
Not a bug, just poor understanding of new mechanics on OPs part.
