### ISSUE TITLE
AI can see ghosts

### ISSUE THREAD

**Issue by SpacePrius** [tgstation/tgstation#45528]
## Testmerges: 
#45457: 'Tend Wounds Now Is -2 Steps and Borg-Friendly!' by ExcessiveUseOfCobblestone at commit b253806759

## Reproduction: Be an AI, you can now see ghosts
![image](https://user-images.githubusercontent.com/26174449/61997847-c2f4dc00-b075-11e9-8508-7484bbf6c7dc.png)

**Comment by nemvar** [comment]
I see dead people
![hqdefault](https://user-images.githubusercontent.com/47324920/61998668-b000fc80-b0b3-11e9-89b9-d01c331a2848.jpg)

**Comment by nemvar** [comment]
Wizround.
