### ISSUE TITLE
medborgs cant do revival

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#45532]
probally caused by #44819 ?

**Comment by nemvar** [comment]
Did you actually have access to a surgery computer and/or the surgical processor? At what step exactly did this fail? Did it generate any errors?

**Comment by adamkad1** [comment]
I literally just dont get the option to do revival, will add ss of head surgeries once im borg with surgery processor

**Comment by ExcessiveUseOfCobblestone** [comment]
#45457 probably fixed it (I didn't pay attention to it when testing for the tend wounds fix)
