### ISSUE TITLE
Manned machine gun turret not shooting the way you're clicking.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#45539]
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: 114376
BYOND Version: 512.1471
Server revision compiled on: 
Master commit: 6f9f1c61b1f9a4b016d3e503365d5b5745378eed
The following pull requests are currently test merged:
#44639: '[Ready] Ports dynamic gamemode from /vg/' by TheChosenEvilOne at commit fccb0c5b97
#45104: '[TMC] Defib Rework, Organ Damage Effects' by RandolfTheMeh at commit c5bd237103
#45457: 'Tend Wounds Now Is -2 Steps and Borg-Friendly!' by ExcessiveUseOfCobblestone at commit b253806759
#43148: '[s]Temp workaround for admins matching stickybans because of a byond bug.' by MrStonedOne at commit e34fa30ce1

Local commit: c266509d74897be99892e26ed9fe552e23403fe5
Server tools version: /tg/station 13 Server v3.2.6.2

Reproduce: Spawn manned turret, click in any direction. I've noticed that the projectiles tend to go to the bottom left diagonally.

**Comment by msgerbs** [comment]
When is this even used?

**Comment by BeeSting12** [comment]
When I spawn it in for events

**Comment by wesoda25** [comment]
yeah i accidentally mowed down some fellow death squad members this way once

**Comment by timothymtorres** [comment]
![Discord_luouqkWOpW](https://user-images.githubusercontent.com/5195984/222015469-69e68ad9-3308-41c8-a665-1de20b57e11f.png)
