### ISSUE TITLE
Syndicate balloon icon states are bugged

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#45544]
Syndicate balloon icon states are bugged - inhands and other states are invisible and round end screens dump a bunch of miscellaneous icons.

![hhhhhh](https://user-images.githubusercontent.com/32391752/62004407-05292680-b125-11e9-896e-b927db7deb63.png)

## Round ID: 
114397 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

## Testmerges:

#45457: 'Tend Wounds Now Is -2 Steps and Borg-Friendly!' by ExcessiveUseOfCobblestone at commit b253806759
#43148: '[s]Temp workaround for admins matching stickybans because of a byond bug.' by MrStonedOne at commit e34fa30ce1

**Comment by Akrilla** [comment]
:flushed:

**Comment by Time-Green** [comment]
That’s actually impressive

**Comment by Fikou** [comment]
pretty sure thats the entirety of the items and weapons dmi
probably caused by ians birthday pr that touched balloons
@tralezab h??

**Comment by tralezab** [comment]
It's very impressive the only Sprite I did not change broke...

**Comment by tralezab** [comment]
I got it
