### ISSUE TITLE
Issues with the ingame "Report Issue" function

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#45545]
1) .github/ISSUE_TEMPLATE.md doesn't get inserted into the message body.
2) Test merged PRs don't get inserted, only the round ID and client version.
3) Trying to view test merged PRs from inside the panel isn't possible as Github no longer supports IE.
4) The popup is too small by default and requires either resizing or scrolling.
![p1](https://user-images.githubusercontent.com/32391752/62004482-f7c06c00-b125-11e9-9c7e-89b2aca05685.PNG)

**Comment by dragomagol** [comment]
Fixed by #55135
