### ISSUE TITLE
Cryogenics cells don't put out people on fire

### ISSUE THREAD

**Issue by senjx** [tgstation/tgstation#45542]
## Round ID: 
114389

## Testmerges:
#45485: '[Test Mergeable] Infection Gamemode' by Whoneedspacee at commit 79cf8b8f47
#44639: '[Ready] Ports dynamic gamemode from /vg/' by TheChosenEvilOne at commit 9c3be66b44
#45457: 'Tend Wounds Now Is -2 Steps and Borg-Friendly!' by ExcessiveUseOfCobblestone at commit b253806759

## Reproduction: 

1. Set person X on fire.
2. Load person X on cryo cell.
3. Close cryo cell, then turn it on.
4. Person X will remain on fire.

It strikes me that this shouldn't be happening based on the fact that cryogenic cells are powered by frozen oxygen and a chemical suspension on some sort of liquid. Intended? Feature? You decide!

**Comment by nemvar** [comment]
Just FYI, nothing is stopping you from making a hot cryo chamber. Just put hot gas inside and it works fine. At best this is an oversight, at worst not even a bug.

**Comment by Borisvanmemes** [comment]
Theres even a reverse cryoxadone chem called pyroxadone which heals you if you're hot rather then cold.

**Comment by jlc1206** [comment]
Default cryo gas is o2 right? Could be burning so fast they can’t get below fire exist temp

**Comment by Putnam3145** [comment]
not just default, cryo doesn't work with any other gas

**Comment by jlc1206** [comment]
https://github.com/tgstation/tgstation/blob/6e44bd3a931238dc473cbed4afd6d11e0c55cbfd/code/modules/atmospherics/machinery/components/unary_devices/cryo.dm#L219

It appears the cryo pod is hard coded to expect only oxygen, and only processes oxygen interactions, ignoring all other gases in the lines. Not sure how intended this is. It does run temperature exchange on occupants but the fire probably heats them up faster than they cool off, which is sensible in the context of the game. I’m not sure but it doesnt look like the gas is actually simulated, just heat exchanged, so it shouldn’t be combusting?

I just got my test server setup, i will try to test this today

**Comment by Putnam3145** [comment]
i feel like it should at least let you use pluoxium, yeah, but the code says oxygen only

**Comment by Firecage** [comment]
Honestly, plasma gas could, hypothetically, also work. I mean, have we forgotten we are a Plasma Research Station?

**Comment by Mooshimi** [comment]
Tested, cryo cells do put people out now
