### ISSUE TITLE
Malf AI preference is broken

### ISSUE THREAD

**Issue by Michael-Ashfield** [tgstation/tgstation#45551]
## Round ID: 14409

Basically I have Malf AI pref disabled, and traitor enabled. I spawned in as an AI and was was malf,  despite opting to not be malf in my antag preferences.

**Comment by TheChosenEvilOne** [comment]
This is an issue with #44639.

**Comment by nemvar** [comment]
This is not a bug. Traitor role is used for rolling for 'malf' AI. Malf AI pref has been useless ever since the dedicated malf AI mode has been removed.

**Comment by nemvar** [comment]
Apparently this has been treated as a bug in the past. Also dupe of #39573
