### ISSUE TITLE
i some how created an infinite cyborg shell.

### ISSUE THREAD

**Issue by zeroisthebiggay** [tgstation/tgstation#45553]
Issue reported from  Round ID: 114415 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1472

>be mime
>make ai shell
>make a shell for a positronic brain (seperately from the ai's shell which got used up properly)
>insert the positronic brain
>empty shell drops at cyborg's feet
>insert boris modules in to the dropped shell
>the freshly created cyborgs all properly use up and then drop a shell at their feet but don't have power cells installed
>the shell un fucks it self automatically after being wrenched and then remade

**Comment by kriskog** [comment]
Might be related to #45301

**Comment by nemvar** [comment]
Definitly related. Closing because dupe.
