### ISSUE TITLE
Lockers are inescapable prisons (Also applies to crates and bodybags)

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#45559]
Lockers will appear to be always open once you have opened them the first time. Trying to shut one after will cause anything on the locker to be trapped inside until the locker is deconstructed or deleted.

To reproduce, get in a locker and close it. You are now trapped inside until someone helps you out.

Issue reported from  Round ID: 114439 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

**Comment by optimumtact** [comment]
fixed by server version downgrade
