### ISSUE TITLE
Sprites in vendors are gone (Also applies to RD Console)

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#45560]
Pretty self explanatory. The sprite showing what an item in a vendor looked like is now gone.

Issue reported from  Round ID: 114439 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

**Comment by wesoda25** [comment]
This goes for RD Console icons too, everything just looks like list view now since icons are gone

**Comment by optimumtact** [comment]
fixed by server version downgrade
