### ISSUE TITLE
Chem dispensers no longer work (Also applies to other dispensers)

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#45562]
Chem dispensers are unable to dispense any chemical. There are no buttons for the chemicals and beakers do not show up when placed in dispensers

Issue reported from  Round ID: 114439 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

**Comment by optimumtact** [comment]
fixed by server version downgrade
