### ISSUE TITLE
RPD doesnt create pipes, pipes cant be wrenched down

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#45563]
Its impossible to make new pipes. Using an RPD doesnt produce a pipe even though it says it is building a pipe, you cant wrench down pipes you unwrench. 

Issue reported from  Round ID: 114445 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

**Comment by optimumtact** [comment]
fixed by server version downgrade
