### ISSUE TITLE
All posters are "poster - random poster", new ones have the same problem

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#45561]
All posters at roundstart will be poster - random poster and have a checkerboard appearance. The name differs slightly depending on if its official or contraband but its still checkerboard for both. Printing out new ones at the library also yields the random poster

Issue reported from  Round ID: 114439 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

**Comment by optimumtact** [comment]
fixed by server version downgrade
