### ISSUE TITLE
ORM does not recognise mining ID card and refuse to dispense points

### ISSUE THREAD

**Issue by versacehhh** [tgstation/tgstation#45577]
## Reproduction:
Be miner
Mine
Put hard earned ores into ORM
Watch as it doesn't give you points when you put ID in
Watch as it refuses to dispense your card, so you have to alt+click it
It swallows up budget cards and you have to pry it open to get it back
![github_issue](https://user-images.githubusercontent.com/39391133/62029087-b38ea380-b1d9-11e9-953e-1a6f610a73d8.png)

It COULD be because we are on Donut, if you cannot reproduce it in any other maps.

**Comment by BeeSting12** [comment]
This happens on every map. Did #45522 break it

**Comment by nemvar** [comment]
@BeeSting12 
![hqdefault (1)](https://user-images.githubusercontent.com/47324920/62169544-cbc10880-b328-11e9-8bec-29219e19e770.jpg)

#45193 probably broke it.
