### ISSUE TITLE
Fusion projectile radiation not properly blocked by radsuit

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#45576]
## Round ID:
114455

## Reproduction:
Start fusion. Get hit by a fusion projectile. You will get a message saying your armor absorbed the blow, but if you scan yourself with a geiger counter you now have 5000 rads. 

Potentially caused by the projectile changes in #45484

**Comment by kriskog** [comment]
Might also be the case for xray bolts, if so thats easier to reproduce/test.

**Comment by Time-Green** [comment]
This has been like that forever, the general consensus is not to eat fusion particles

**Comment by kriskog** [comment]
No, it was changed recently. #44990

**Comment by nemvar** [comment]
This has been around since forever. The Irradiate var is ignoring rad armor, for whatever reason.

**Comment by kriskog** [comment]
Do you even read? It was changed to where radsuits entirely block the projectiles, and broken recently.
