### ISSUE TITLE
SM shutters are gone on Box Station during Infection

### ISSUE THREAD

**Issue by MacBlaze1** [tgstation/tgstation#45572]
Round ID: 114458
BYOND Version: 512.1471
The following pull requests are currently test merged:
#45457: 'Tend Wounds Now Is -2 Steps and Borg-Friendly!' by ExcessiveUseOfCobblestone at commit b253806759
#44639: '[Ready] Ports dynamic gamemode from /vg/' by TheChosenEvilOne at commit 9c3be66b44
#45485: '[Test Mergeable] Infection Gamemode' by Whoneedspacee at commit 79cf8b8f47
One shutter just disappeared at the beginning of the round when I closed the SM shutters, 5 were there, 1 was not. It was the left very bottom one.

**Comment by Whoneedspacee** [comment]
probably might have something to do with beacons ill take a look

**Comment by nemvar** [comment]
Looks like either a test merge bug or something that's a onetime fluke. Feel free to make another issue should this ever happen again.
