### ISSUE TITLE
Can't retrieve mining credits from Ore Redemption Machine.

### ISSUE THREAD

**Issue by Jaltsi** [tgstation/tgstation#45589]
Issue reported from  Round ID: 114528 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1475

ORM menu doesn't show the ID you put into it and you can't retrieve the credits from dumped ores.

**Comment by Naloacisamazing** [comment]
it also eats the id if another one is added before the last one was taken out

**Comment by bgobandit** [comment]
dupe https://github.com/tgstation/tgstation/issues/45577

**Comment by Coconutwarrior97** [comment]
This is a dupe so I'm closing it.
