### ISSUE TITLE
Ghosts can make mulebots buzz

### ISSUE THREAD

**Issue by zxaber** [tgstation/tgstation#45594]
## Testmerges:
#45457 
#44639 
#45485 

## Reproduction:
Ghosts can make mulebots buzz by dragging their own sprite onto the mulebot.

![image](https://user-images.githubusercontent.com/37497534/62092994-6556c000-b22c-11e9-82f1-6a143d3f14c4.png)

**Comment by trexter555** [comment]
same with id computer beeps

**Comment by Akrilla** [comment]
having 4 ghosts around a mule and scaring cargo techs is a feature prove me wrong
