### ISSUE TITLE
Split personalities and imaginary friends are bugged and happen WAY too commonly

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#45598]
imaginary friends and split personalities happen way, WAY too commonly. it's at least one of them every like 5 or 10 minutes, every single round, wizard to greenshift. it's really annoying having to click them away as a ghost

they can also pick monkeys and dead bodies??? what the fuck?

imo i think they're useless and not worth being in the game anyways so they should just be removed entirely

**Comment by Striders13** [comment]
It happens only because those monkeys and random soulless dead people can get these traumas. Anyway if that annoys you can just press the 'never for this round' button as a temporary solution.

**Comment by Dennok** [comment]
Or make check to soul?
Make soulless cant have split personalities and imaginary friends

**Comment by nemvar** [comment]
I think the feedback tag is correct for this. This isn't really a bug and seems to be caused by a lot of mindless mobs all getting brain damage from BZ or something like that.

**Comment by nemvar** [comment]
Alright, this is a bug my bad. Apparently I need to learn how to read the issue body correctly.
