### ISSUE TITLE
White Ship Navigation Computer Bugged

### ISSUE THREAD

**Issue by halitosisman** [tgstation/tgstation#45599]
Issue reported from  Round ID: 114559 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1472

The icons that are supposed to be in the upper left hand corner of the advanced navigation HUD do not appear. Resting to exit the HUD makes the icons appear briefly as my character exits the HUD.

**Comment by optimumtact** [comment]
you're zoomed out, or using a different view scale, that usually causes it

**Comment by halitosisman** [comment]
Setting my scaling to "stretch to fit" did fix the the issue.

**Comment by optimumtact** [comment]
we really need to fix this at some point.

basically the icons are there, but off screen

**Comment by Dennok** [comment]
As i know, BYOND on "stretch to fit" try to show anithyng , even if it out off screen, it try to change zoom and show it.
 some BYOND changes or icon update issue?
