### ISSUE TITLE
Neither ammonia nor diethylamine increase yield

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#45593]
Issue reported from  Round ID: 114551 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1471

If you have a yield 0 plant and try to use ammonia or diethylamine to increase its yield, neither chemical does anything and you will never be able to harvest something. The only way I could get the yield up was using unstable mutagen at a dose of 1u.

**Comment by Dennok** [comment]
Or use Floral Somatory. Or Z nutriments to get minimum growns.
The ammonia and diethylamine a nutrimens, it dont give stats directly, as i know.

**Comment by nemvar** [comment]
Relevant code
https://github.com/tgstation/tgstation/blob/master/code/modules/hydroponics/seeds.dm#L179
```
/obj/item/seeds/proc/adjust_yield(adjustamt)
	if(yield != -1) // Unharvestable shouldn't suddenly turn harvestable
		yield = CLAMP(yield + adjustamt, 0, 10)

		if(yield <= 0 && get_gene(/datum/plant_gene/trait/plant_type/fungal_metabolism))
			yield = 1 // Mushrooms always have a minimum yield of 1.
		var/datum/plant_gene/core/C = get_gene(/datum/plant_gene/core/yield)
		if(C)
			C.value = yield
```
and
https://github.com/tgstation/tgstation/blob/master/code/modules/hydroponics/hydroponics.dm#L615
```
	// Ammonia is bad ass.
	if(S.has_reagent(/datum/reagent/ammonia, 1))
		adjustHealth(round(S.get_reagent_amount(/datum/reagent/ammonia) * 0.5))
		adjustNutri(round(S.get_reagent_amount(/datum/reagent/ammonia) * 1))
		if(myseed)
			myseed.adjust_yield(round(S.get_reagent_amount(/datum/reagent/ammonia) * 0.01))
```
I don't see anything that would cause this unless yield mutated to -1 for some reason, in which case this is not a bug.

**Comment by cacogen** [comment]
When I scanned it the yield was 0

**Comment by YPOQ** [comment]
As per https://github.com/tgstation/tgstation/blob/30a8cca355e92eed703eb15daba96a9075d2d1e1/code/modules/hydroponics/hydroponics.dm#L620 you need to apply at least 100 units in one transfer to actually increase the yield (such as a full large beaker set to transfer 100 units). I don't think this is a very good design decision but not sure what to do short of simply nerfing the required amount.

**Comment by Dennok** [comment]
Also you can use bees, it increase yield too.

**Comment by ArcaneMusic** [comment]
As as result of #50001 changing how plants are affected by reagents, I believe this to have been fixed.

**Comment by cacogen** [comment]
I'm just going to assume it's fixed due to the changes
