### ISSUE TITLE
Taser bolts don't stun

### ISSUE THREAD

**Issue by Shapsy** [tgstation/tgstation#45601]
Issue reported from  Round ID: 114566 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
Master commit: 3cb79721d3d16510b368051935dadd78c279abfb 
Reporting client version: 512.1472
Server BYOND Version:  512.1475 

#45457: 'Tend Wounds Now Is -2 Steps and Borg-Friendly!' by ExcessiveUseOfCobblestone at commit b253806759 
#43148: '[s]Temp workaround for admins matching stickybans because of a byond bug.' by MrStonedOne at commit e34fa30ce1 

Taser bolts don't do anything when they hit humans, whether they're from the AI sat or the actual taser gun.

**Comment by py01** [comment]
my fault, will fix
