### ISSUE TITLE
Eating a goose causes slaughter demons to become stuck.

### ISSUE THREAD

**Issue by Ordonis** [tgstation/tgstation#45600]
## Round ID:
114565

## Testmerges:

#44639
#45457
#45485

## Reproduction:

Be slaughter demon. Eat birdboat. Become stuck, unable to move, heal, or act at all, with attempting to press bloodcrawl button leading to 'finish eating first!'

Min(NecromancerAnne, I think) ejected me from bloodpool, was still unable to move or attack.
Death by goose.

Fitting fate for one so hubris-filled as to assume that they could eat the eater of all things. 
Ree.

**Comment by nemvar** [comment]
Probably caused really odd moved() of the vomitgoose.

**Comment by bgobandit** [comment]
@plapatin

**Comment by plapatin** [comment]
what the fuck

**Comment by necromanceranne** [comment]
Plapatin please fix the goose already.

**Comment by YakumoChen** [comment]
Loose the goose

**Comment by tralezab** [comment]
confirmed fixed by my fix
