### ISSUE TITLE
Security record console ID Slot is unresponsive

### ISSUE THREAD

**Issue by Charmisokay** [tgstation/tgstation#45604]
## Reproduction: With your ID in your hand, you used to be able to click on the ID slot in security records consoles. That doesn't work anymore. It makes a 'computer noise' but your ID is not put into the console. You can, however, still access the console by clicking on the console itself. This image will clarify:
![image](https://user-images.githubusercontent.com/25822752/62107305-a04a0980-b2a7-11e9-9a7a-e799e0412367.png)

**Comment by Charmisokay** [comment]
Clarification, I meant Sybil, not bagil.

**Comment by nemvar** [comment]
Also happens with medical records.

**Comment by Coconutwarrior97** [comment]
This is true with all consoles which require an ID to log in.
