### ISSUE TITLE
alt-click on machines to rotate no longer works

### ISSUE THREAD

**Issue by dee-dubya** [tgstation/tgstation#45613]
## Reproduction:

Pretty simple. Unanchored machines can no longer be rotated, which seems to be part of a larger issue where alt-clicking ANY machine causes the "There's no ID card in the console!" message to appear.

**Comment by FloranOtten** [comment]
Alt clicking at all causes this. Pretty funny when the SM demands an ID

**Comment by pireamaineach** [comment]
https://github.com/tgstation/tgstation/pull/45193/files

**Comment by kingofkosmos** [comment]
My bad, I'll fix it.

**Comment by nemvar** [comment]
Can I assume this has been fixed?

**Comment by kriskog** [comment]
No you may not. Still broken.

**Comment by actioninja** [comment]
I'm going to fix this tonight.
