### ISSUE TITLE
cult can't complete their sacrifice

### ISSUE THREAD

**Issue by loserXD** [tgstation/tgstation#45615]
## Testmerges:
#44639: '[Ready] Ports dynamic gamemode from /vg/' by TheChosenEvilOne at commit fccb0c5b97
#45457: 'Tend Wounds Now Is -2 Steps and Borg-Friendly!' by ExcessiveUseOfCobblestone at commit b253806759

## Reproduction:
basically, cult on dynamic
Jack Breeg, the detective was our sacrifice, who was also in disguise of an assistant
we killed them on the offer rune and sacrificed them, but we got no soulstone and the sacrifice wasn't marked as complete so we couldn't summon

**Comment by Cyprex** [comment]
Some cultists had no objectives. Only one cult was ever ran, this was around 30 pops, I think the other antags were limited to a single traitor.
VV of one cult antag datum in question:
![Screenshot_20190730_145308](https://user-images.githubusercontent.com/35031555/62130990-8d046180-b2da-11e9-855c-847696f7d713.png)
@TheChosenEvilOne

**Comment by TheChosenEvilOne** [comment]
huh, this has never happened before in the few rounds of cult that has been lowpop.
