### ISSUE TITLE
Medical records can't be accessed

### ISSUE THREAD

**Issue by MortoSasye** [tgstation/tgstation#45620]
Issue reported from  Round ID: 114635 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 512.1472

Steps:
1. Try to use a medical laptop or medical records console.
2. Fail to put your id inside Confirm Identity.
3. Therefore, don't get access to the records.
3. Cry all night about not being able to spy on people or make them felinids.

**Comment by MortoSasye** [comment]
I think it's the same issue the security records are presenting like in: https://github.com/tgstation/tgstation/issues/45604

**Comment by nemvar** [comment]
Closing because this is very similar to the security records issue and they likely have the same cause. Thanks for reporting it.
