### ISSUE TITLE
Broken Jumpsuit, QM

### ISSUE THREAD

**Issue by CrossbowDemon** [tgstation/tgstation#45639]
Issue reported from  Round ID: 114733 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1475

The QM jumpsuit is invisible on my player, red text floats near head, suit icon in inventory is a broken jumpsuit with question marks all over it.
![Broken Jumpsuit](https://user-images.githubusercontent.com/12440200/62255935-67a45000-b3cd-11e9-9fc2-1deb17abbbe8.png)

**Comment by CameronWoof** [comment]
Closed by #45640
