### ISSUE TITLE
Default spawn medical doctor jumpsuit is calling an error

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#45636]
## Reproduction: 
Round start doctors have the "HONK" unknown jumpsuit instead of the actual doctors jumpsuit. Seen here: https://i.gyazo.com/758c79d3251c284f2670f0c41cd82c6a.png
And here: https://i.gyazo.com/7607438328d01d34c193049442efd3d6.png

Just be a medical doctor (male human) at round start.

**Comment by CameronWoof** [comment]
Closed by #45640
