### ISSUE TITLE
Some single pack crates can be ordered, and have the crate sent back at a profit.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#45637]
Take first aid kits for an example. Pay 250 credits for one and it comes in a crate. Send the crate back to Centcomm with a stamped manifest and you get 500 plus however much for manifest, allowing you to get a 250 credit profit on buying a first aid kit. This happens with other items as well.

**Comment by zxaber** [comment]
This was a bit of an oversight on my part when I made the small items PR. The intention was that small items would be bundled together in a single crate, and also allowing individuals to purchase a single health kit for whatever use they have without having to team up with others to share costs.

Not quite sure the best way to fix it, really. If I'm honest, I don't think crates should be worth $500 in the first place, but changing that now would throw off balance of many different things. I suppose I could introduce a plastic crate or something that is used if the total cost was under $500 (maybe a bit higher), that sell for a very small amount.

**Comment by Tlaltecuhtli** [comment]
use a cheaper crate type for singlepacks? like wooden is 250 and plastic is 100 ( i think)

**Comment by ATH1909** [comment]
Just add a "poorly-made crate" subtype of crates that doesn't sell for anything (or drop any mats) when you sell it.

**Comment by zxaber** [comment]
There's already an existing wood crate. I might make a subtype of the secure crate with a modified wood crate sprite. Ideally, the wood crate would only be used if the order is under like 600 credits, and I just need to figure out the sane way to change the crate for orders expensive enough to warrant a metal crate.

**Comment by bgobandit** [comment]
this would also mean different kinds of crate actually have a use

**Comment by TheBonded** [comment]
@zxaber I believe that single packs now come in nice breifcases and not crates, is this still an issue?
