### ISSUE TITLE
Alien queens can lay infinite eggs on a tile

### ISSUE THREAD

**Issue by Timonkeyn** [tgstation/tgstation#45649]
Issue reported from  Round ID: (does not matter)
Reporting client version: 512.1471

step 1: try to lay an egg on a vent/scrubber
Step 2: move a tile and click yes
Step 3: repeat with the same tile

sounds Pretty broken, eh?

**Comment by Fikou** [comment]
no it doesnt

**Comment by Timonkeyn** [comment]
how does it not sound broken

**Comment by PKPenguin321** [comment]
It's not hard to lay 1000 eggs either way
