### ISSUE TITLE
The Traps does not respect antimagic

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#45646]

**Comment by 81Denton** [comment]
It does have an anti magic check but will always trigger flare(), which makes the trap visible and disables it for a minute.

https://github.com/tgstation/tgstation/blob/5a6bbbefebddf06b41dff6d4c0384e5af1f73218/code/game/objects/structures/traps.dm#L63-L80

**Comment by YakumoChen** [comment]
I encountered it on a downstream and assumed it was an upstream issue, traps were doing their full effect on me in an inquisitor hardsuit (though I was immune to other magic as intended), might be better to test both code bases I guess.
