### ISSUE TITLE
Monkeys can survive just fine without a heart (or life support)

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#45654]
https://cdn.discordapp.com/attachments/326831214667235328/606414748963307520/monkeysdontneedhearts.PNG

https://cdn.discordapp.com/attachments/326831214667235328/606414864143089677/unknown.png

The first screenshot was taken by me and the second image was taken by Zxaber, but both of them are of the same incident/my hijinks.

After codediving for a bit while trying to devise a way to survive indefinitely with no organs, I noticed something peculiar: monkeys didn't seem to have any code that'd hurt them for not having a heart (apart from the inability of heartless monkeys to be defibbed). I tested it in an actual round, and sure enough, the monkey was just fine.

**Comment by optimumtact** [comment]
they're not a human mob so they don't inherit any of that behaviour.

I don't see this as a bug as they never had the ability to need a heart

**Comment by ATH1909** [comment]
But don't they still need their other organs, like their livers, lungs, etc. (I guess I'll have to look deeper into them too)? Why should hearts be any different?

**Comment by nemvar** [comment]
@optimumtact You are wrong on this. Heart attack code is on carbon level for a reason.

**Comment by Myoblongvagooglia** [comment]
you don't see any issue in a mammal surviving without a heart, at all? like, no issue whatsoever?

**Comment by nemvar** [comment]
Of course there is an issue. That's why it's literally called a Consistency Issue.

**Comment by PKPenguin321** [comment]
Might even call it an oversight since I'd bet the original creator didn't consider to test it with non-humans

**Comment by optimumtact** [comment]
Sure there's an issue with it, but the tracker is for tracking bugs
