### ISSUE TITLE
Some quirks transfer by cloning, when logically should not.

### ISSUE THREAD

**Issue by Dennok** [tgstation/tgstation#45653]
Running /tg/ revision: 2019-07-24
origin/master: 593631c
HEAD: f6cd3e0

## Reproduction:
Clone men with "Prosthetic Limb" quirk, and it keeps.

Maybe some other quirks must to be cleared by cloning or other way.

**Comment by nemvar** [comment]
Quirks should never get cleared imo. The reference to them can easily be handwaved as some leftover medical record from before cloning.

**Comment by PKPenguin321** [comment]
Prosthetic limb quirk should clone you with that limb *missing entirely*, not regrown or with a prosthetic already on
