### ISSUE TITLE
Access Control console can be operated without an ID

### ISSUE THREAD

**Issue by Ryll-Ryll** [tgstation/tgstation#45661]
Issue reported from  Round ID: 114825 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1472

#43148: '[s]Temp workaround for admins matching stickybans because of a byond bug.' by MrStonedOne at commit e34fa30ce1 
#45217: 'VV refactors 2 - Actually not indefinitely WIP' by kevinz000 at commit cbf7711e5a 

Step 1: Insert ID with ID console access into authorizing card slot and another ID into the target card slot
Step 2: Login
Step 3: You can now remove the authorizing ID and continue to change the access on the target card. In addition, you can remove the target card and replace it with a different target card and still modify them.

I'm not 100% sure if this is actually a bug? I've always assumed, like the player who reported this, that you had to actively have an authorizing ID in the machine to make changes to a target ID. Is it supposed to be something you have to manually log out of after you first log in, has it always been like this?

[![2019-08-01_20-39-17.png](https://i.imgur.com/kWWVruW.png)](https://i.imgur.com/kWWVruW.png)

I figured I'd be safe and report it since at the very least it's weird to have both a Log In and Log Out prompt on the same screen

**Comment by PKPenguin321** [comment]
May have been caused by https://github.com/tgstation/tgstation/pull/45193 but full disclosure I'm not sure if it's always been this way or not, I personally always kept the card in but it may have just been force of habit

**Comment by kingofkosmos** [comment]
That is indeed illogical. I'll make a fix PR so every time the authorizing ID is ejected, it'll automatically log the user out.

**Comment by Anonmare** [comment]
I definitely remember ejecting the card logging off the console

**Comment by kingofkosmos** [comment]
Apparently this is not a bug then but a new feature?

**Comment by PKPenguin321** [comment]
I'm not so sure about that...

**Comment by kopoba** [comment]
Also some PR break cool feature of ID console.
Previously when you insert ID with ID modification access it goes to authorization slot not to target slot.
Now console just ignore this and put ID in first open slot.

**Comment by PKPenguin321** [comment]
@ShizCalev I really wish you didn't close https://github.com/tgstation/tgstation/pull/45678
