### ISSUE TITLE
Fake names can contain ic banned words

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#45679]
## Reproduction:
Get agent ID and a gas mask. 
Name yourself something blocked in IC chat, like for tg "The OwO".
Enjoy people being unable to call out your fake name on comms.

Of course, this will rely on the config being set up with ic blocked words to reproduce.

**Comment by nemvar** [comment]
Wrong button

**Comment by SkeletalElite** [comment]
Is this really a bug though. An agent ID card is actual text and thus you could write whatever you wanted to on it (similar to a PDA) meaning netspeak is fine in that circumstance.

**Comment by PKPenguin321** [comment]
>Is this really a bug though

No, it's an
![image](https://user-images.githubusercontent.com/8345184/62409805-9ff48b80-b591-11e9-89f9-7a675659ad5f.png)

**Comment by tralezab** [comment]
was fixed
