### ISSUE TITLE
Left arm cant be implanted by toolset/Surgical Arm Implant

### ISSUE THREAD

**Issue by Dennok** [tgstation/tgstation#45674]
Round ID: 114876
BYOND Version: 512.1471
Server revision compiled on: 
Master commit: 3cb79721d3d16510b368051935dadd78c279abfb
The following pull requests are currently test merged:

Local commit: 3b7970e8720048a0db98e37f0410362c5feefd27
Server tools version: /tg/station 13 Server v3.2.6.2

##Reprodutcion.
Try to implant Surgical Arm Implant and Tool Arm Implant to one body.

**Comment by dr-bee** [comment]
did you try screwdriving it to change it to left hand mode?

**Comment by nemvar** [comment]
Yes, you need to screwdriver it. Worked last time I did this which was around a month ago.

**Comment by nemvar** [comment]
Relevant code. This looks fine to me.
```
/obj/item/organ/cyberimp/arm/proc/SetSlotFromZone()
	switch(zone)
		if(BODY_ZONE_L_ARM)
			slot = ORGAN_SLOT_LEFT_ARM_AUG
		if(BODY_ZONE_R_ARM)
			slot = ORGAN_SLOT_RIGHT_ARM_AUG
		else
			CRASH("Invalid zone for [type]")
```
and
```
/obj/item/organ/cyberimp/arm/screwdriver_act(mob/living/user, obj/item/I)
	. = ..()
	if(.)
		return TRUE
	I.play_tool_sound(src)
	if(zone == BODY_ZONE_R_ARM)
		zone = BODY_ZONE_L_ARM
	else
		zone = BODY_ZONE_R_ARM
	SetSlotFromZone()
	to_chat(user, "<span class='notice'>You modify [src] to be installed on the [zone == BODY_ZONE_R_ARM ? "right" : "left"] arm.</span>")
	update_icon()```

**Comment by Dennok** [comment]
ohh good yes! i forfot this. and confused by no space message!
