### ISSUE TITLE
New Shotgun Inhand Sprite Inconsistent

### ISSUE THREAD

**Issue by SkeletalElite** [tgstation/tgstation#45687]
Reproduction:

Pick up a shotgun, look at it and notice how you point it in the air and start facing different direction and realize that for some reason when looking to the right you point it down but when looking any other direction you point it up in there air.

**Comment by actioninja** [comment]
Not a bug. Intentional because if both shotguns pointed up/down from a side view they would overlap on one would not be visible if you were dual wielding.
