### ISSUE TITLE
ORM's got broken by the new ORM fix

### ISSUE THREAD

**Issue by Kingtrin** [tgstation/tgstation#45685]
Using a mining ID on an ORM gives the error "invalid ID" and points still cannot be accepted. The ORM has been broken in one form or another for the past 5 days and its getting tiresome. The previous fix is #45627 

I would sincerely appreciate anyone who could track this down so mining and free golems aren't completely fucked anymore.

## Testmerges: 
#45457 

## Reproduction:
Use any mining ID on an ORM and it now refuses to accept the ID altogether.

**Comment by SpaceDeku** [comment]
Interestingly prisoner ID's are accepted now in the ORM but you still aren't able to withdraw any of the point balance.

**Comment by actioninja** [comment]
Fixed
