### ISSUE TITLE
When dropped, bedsheets aren't at pixel_x and pixel_y = 0

### ISSUE THREAD

**Issue by ishitbyabullet** [tgstation/tgstation#45702]
Issue reported from  Round ID: 115066 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1472
![2019-08-04_03-39-10](https://user-images.githubusercontent.com/29403316/62422695-a152b080-b684-11e9-83a6-33595f8f4360.png)
I would like to be able to drop bedsheets (at pixel_x = 0 and pixel_y = 0) without looking like a dumbass again.

To replicate this issue, go on the main server right now and just drop a bedsheet while laying on a bed. See how long it takes until it looks good.

I don't think this is intended at all either.

**Comment by nemvar** [comment]
Bedsheets can be used on yourself to make them drop perfectly. While this is unintuitive, it is indeed the intended way to use this.

**Comment by nemvar** [comment]
Relevant code
```/obj/item/bedsheet/attack_self(mob/user)
	if(!user.CanReach(src))		//No telekenetic grabbing.
		return
	if(!user.dropItemToGround(src))
		return
	if(layer == initial(layer))
		layer = ABOVE_MOB_LAYER
		to_chat(user, "<span class='notice'>You cover yourself with [src].</span>")
		pixel_x = 0
		pixel_y = 0
	else
		layer = initial(layer)
		to_chat(user, "<span class='notice'>You smooth [src] out beneath you.</span>")
	add_fingerprint(user)
	return
```
Relevant commit.
https://github.com/tgstation/tgstation/pull/45155/commits/e885c92552515e589fce49c322f3739f2a9383b2

**Comment by nemvar** [comment]
Feel free to change this if you want.
If you want drop behaviour to mirror this, simply override the ``pixelOffset()`` proc for bedsheets

**Comment by ishitbyabullet** [comment]
Oh, alright.
