### ISSUE TITLE
Neutral mood gives positive santity: take two

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#45715]
Same as #45248 except sanity increases until it hits the cap at 150

1. Have 0 total mood
2. Sanity rises up to 150

**Comment by nemvar** [comment]
Neutral mood is supposed to increase sanity. The problem is that I was being silly about the exact caps.

**Comment by Mickyan** [comment]
if you mean neutral mood is supposed to give positive sanity that sounds like a pretty backward thing to do

**Comment by nemvar** [comment]
Well, I will probably remove it because people keep reporting it as a bug.
