### ISSUE TITLE
gorillas are broken

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#45727]
115150

when a gorilla has an item in hand it cant open crates and use similar verbs

gorillas cant switch intent with 1234 keys

gorillas cant drag

gorillas cant press "log in " in the comms console even with access

**Comment by PKPenguin321** [comment]
Is this really a bug or is this just simple mobs not having full functionality

**Comment by Tlaltecuhtli** [comment]
they were able to do these things

**Comment by Dawson1917** [comment]
Intent switching has been a bug with gorillas for a long time but they were able to drag things until recently

**Comment by fludd12** [comment]
Simplemobs with carbon functionalities was a mistake.

**Comment by bobbahbrown** [comment]
gorillas also don't have the ability to throw things

**Comment by ATH1909** [comment]
Also, gorillas can't punch down windows with their bare, meaty fists, even if they're on harm intent (they just politely knock on them instead, which feels a bit odd/weird).

**Comment by timothymtorres** [comment]
Gorillas are simple mobs.  None of this should be allowed.
