### ISSUE TITLE
new miner vendor may have some incompatiblity with nanite id or gorillas

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#45728]
i was a gorilla with subdermal ID nanite and had an legit id in hand when i clicked the miner vendor bottons to dispesne stuff i got:

Error: An ID with a registered account is required!

115150

**Comment by bobbahbrown** [comment]
i lied that doesn't actually close this issue it's a separate issue

**Comment by bobbahbrown** [comment]
oh wait yes it does, pranked!
