### ISSUE TITLE
C4 doesn't show up on mobs

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#45723]
Issue reported from  Round ID: 115138 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1471

I tried planting a C4 set to 60000 on both a human and a borg and neither showed up. I don't know if this is intentional, but I don't think it should be, as previously there was an overlay and now there's no indication someone has C4 on them.

**Comment by 81Denton** [comment]
Iirc it's a layer issue, C4 shows either below the mob or its clothes.
