### ISSUE TITLE
Tend Wounds adv not clearly combo.

### ISSUE THREAD

**Issue by Dennok** [tgstation/tgstation#45732]
BYOND Version: 512.1475
Server revision compiled on: 2019-08-05
Master commit: 7ead350057378af24248e8325b96fd28fd4af69b

![image](https://user-images.githubusercontent.com/7734424/62475280-65673a80-b7ad-11e9-8eee-24d01afcf798.png)

**Comment by ExcessiveUseOfCobblestone** [comment]
> The proper "fix" would be to convey this information in the surgery description since it's not otherwise known.

**Comment by Dennok** [comment]
Here stiil a issue ebout unability of get exp burn heal by researtch

**Comment by Dennok** [comment]
And basic variants don't disappear
