### ISSUE TITLE
misspelled signal name?

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#45745]
"COMSIG_MOB_APPLY_DAMGE" is a signal name used by a few things, but "COMSIG_MOB_APPLY_DAMAGE" is not. Is that spelling intentional?

**Comment by kriskog** [comment]
Its just a define, so it doesn't really matter so long as the defined spelling one is the one being used. Seems like a misspelling, feel free to replace all occurences if you can be bothered.

**Comment by SpaceManiac** [comment]
feel free to open a PR to fix it

**Comment by nemvar** [comment]
feel free to open a PR to fix it
