### ISSUE TITLE
ORM unlinkable to the Ore Silo 

### ISSUE THREAD

**Issue by LoGIRz** [tgstation/tgstation#45748]
After the recent changes you can't link the ORM to an Ore Silo. Linking the Silo to other machines still works as normal. 
The issue was present even before the latest fix to the ORM during the period you couldn't insert IDs into it, latest merge then was at about #45374

## Reproduction:
- Become free golem, get your R&D, create Ore Silo from the circuit
- Link that to your imprinter and the protolathe to see it works just fine
- Attempt linkage to the ORM only to find out you attack it with the multitool instead

**Comment by nemvar** [comment]
Someone messed up while resolving conflicts. REEEE
