### ISSUE TITLE
X4 on mobs is weird.

### ISSUE THREAD

**Issue by nemvar** [tgstation/tgstation#45756]
## Reproduction:

Attach X4 from the west to a mob.
Wait until it explodes.
See it explode in the room next door.

![bugged x4](https://user-images.githubusercontent.com/47324920/62558098-a5472400-b878-11e9-92b2-437259c0f27f.PNG)

This is probably caused because X4, unlike C4, is directional. Still is a bit silly that you barely take any damage if the X4 goes off directly on your person.

inb4 someone uses this to blow up other people that chase them while barely taking damage themselves.

**Comment by wesoda25** [comment]
Its supposed to do that though. Some damage to what its on, but a directional explosive designed to take out whatever is in front of it.

**Comment by nemvar** [comment]
The issue is that whoever got the explosive attached to them doesn't even take damage if they move away from the direction of the explosion, especially if it is laggy. It strikes me as extremely odd that you don't even take damage from a bomb that got planted ONTO you.

**Comment by jlc1206** [comment]
The actual explosion spawns centered 2 turfs away from the mob. Would a directional explosion proc be worth it? And should it be a box, cone, or parameterized shape?

**Comment by nemvar** [comment]
Explosions needs a complete rework. Meanwhile, you could always just flick on the full_mob_damage variable on the bomb.
