### ISSUE TITLE
OOC bans also apply a dead chat ban

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#45777]
##  Reproduction:
Banning anyone from OOC as an abstract role ban also bans them from deadchat.
As OOC is able to spoil the round and deadchat is not, it make more sense if they were separated.

I'm not sure if this is a long running bug or a carried over "feature" of old speech coding, so I wasn't sure whether to report it as a bug or request it as a feature on the forums.

**Comment by Jordie0608** [comment]
This was added way back in #16581

**Comment by 81Denton** [comment]
Cheridan's reasoning back then
>Kor's mergebegging at me, so I'm going to merge this on the basis that persistent OOC Bans are rare, and if you're that obnoxious then we probably don't want you ranting in deadchat either. I don't think we need separate bans for each and every little thing.

Just adding separate deadchat bans sounds fine to me

**Comment by ExcessiveUseOfCobblestone** [comment]
> IC in OOC is a server ban. OOC bans are for attention whores.
