### ISSUE TITLE
Firebreath isn't Lizard Exclusive

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#45770]
If you can get your hands on a dna mutation injector, not the activator, of firebreath, you can use it on literally anyone and give literally everyone fireball.

This works on everyone, regardless of species, so long as that species can be mutated.

**Comment by Time-Green** [comment]
This was intentional. This gives people a reason to capture lizards so they can get firebreath powers.

Hulk is human only because it fucks with sprites or something, I just didn't touch it.

**Comment by necromanceranne** [comment]
O-Oh.

Well then.

Good to know.
