### ISSUE TITLE
Admins can't change mobs names anymore through vv

### ISSUE THREAD

**Issue by MortoSasye** [tgstation/tgstation#45775]
Issue reported from  Round ID: 115341 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 512.1472

**Reproduction**:
1. Open a mob variables.
2. Click on their current name to the right of their sprite.
3. Start crying inside due to a lack of success

**Comment by peoplearestrange** [comment]
#45742 should have fixed this. About 9 hours again, try a hard restart when the next round ends

**Comment by nemvar** [comment]
I checked, this is fixed.
