### ISSUE TITLE
Chefs Can use the Blueprints to get CQC anywhere (one room at a time)

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#45771]
By using the blueprints, you can connect a current or new room to another room attached to that space. This allows you to turn rooms adjacent to the kitchen into the kitchen.

This allows anyone with the blueprints to increase the areas in which the chef is able to gain CQC by slowly expanding the kitchen one room at a time..

**Comment by nemvar** [comment]
feature

**Comment by Cyprex** [comment]
There is a limit to area size so this can't be done infintely.

**Comment by ATH1909** [comment]
> feature

This but unironically.

**Comment by dragomagol** [comment]
Still an issue

**Comment by necromanceranne** [comment]
Been about three years, guess this a feature now.
