### ISSUE TITLE
Sentience ballons are invisible now and can't be clicked to activate

### ISSUE THREAD

**Issue by MortoSasye** [tgstation/tgstation#45776]
Issue reported from  Round ID: 115341 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 512.1472

**Reproduction**:
1. Spawn sentience balloon.
2. Try to click it to no success.
3. Cry inside.

**Comment by ExcessiveUseOfCobblestone** [comment]
can you see it with right click?
