### ISSUE TITLE
Card Code is Bad

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#45781]
## Round ID: 115368

I had a deck of cards, kept shuffling it, every time I would draw a 2-3 ( we were playing texas holdem). Code isn't randomized enough.

**Comment by nemvar** [comment]
You were drawing cards when you tried to shuffle?
Or the shuffling wasn't randomizing the order?
I don't quite understand what the problem is.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/ddd107a5b5af71c8a5935059110ceb237ddf6853/code/game/objects/items/toys.dm#L743-L748

the cards are literally randomized via shuffle()

can't really make it more random than 100% random.

**Comment by ShizCalev** [comment]
tested, unable to repo. works fine here on master, and code checks out.

**Comment by wesoda25** [comment]
Guess i have some wack luck then

**Comment by wesoda25** [comment]
I figured out the issue, the sprite for 2 cards is always 2-3, you need to examine the cards
