### ISSUE TITLE
Toggling Buildmode via VV logs incorrectly

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#45787]
Toggling Buildmode of someone else via the VV Dropdown shows as "<Your ckey>" entered buildmode, rather than the person you toggled/no message being displayed.

**Comment by nemvar** [comment]
Can you add the exact wording for problems of this kind in the future? It makes finding the faulty piece of code a lot easier when you can just ctrl+f it.

**Comment by Cyprex** [comment]
Sorry, sure! should be this:
https://github.com/tgstation/tgstation/blob/6df78fc92a ebb55802858b59e63930334145b281/code/modules/buildmode/buildmode.dm#L145-L157

**Comment by Cyprex** [comment]
This is still an issue, toggling buildmode for someone else via VV notifes as "ADMIN LOG: <Your ckey rather than the target's> has entered build mode."

**Comment by Cyprex** [comment]
Still an issue
