### ISSUE TITLE
In-game combat log can show your own name as attacker, when attacked by someone else

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#45780]
#### Round ID:
Terry 115354

#### Testmerges:
#44639 
#45377 
#45719 

#### Reproduction:
A traitor started beating me with a toolbox. Log said I was hitting myself. Screenshot:

![190807 1903 55 attack log bug cropped](https://user-images.githubusercontent.com/46400996/62652075-c5e7aa80-b95a-11e9-98a3-63d658c60d64.png)
Attacker: Herbert Fink, with a toolbox. Not wearing disguise. Log turned out normal when he was hitting a scrubber. 
Me: Gus Banner, with a screwdriver. I never used a toolbox. 

Also I had to write this issue report twice because github deleted the first one when I accepted an opt-in.

**Comment by willox** [comment]
I am pretty sure that this is from the changes to item_attack.dm in https://github.com/tgstation/tgstation/pull/45631
