### ISSUE TITLE
Bubblegum can't be spawned with admin tools

### ISSUE THREAD

**Issue by Dawson1917** [tgstation/tgstation#45799]
This has been an issue for a fairly long time. At least 3 months? Before then he used to only spawn sometimes, with no clear indication as to why Bubblegum did/didn't.  This applies to Spawn, Podspawn, and Game Panel > Create Mob. 
No other megafauna have the same issue.
Trying to spawn on the mining Z-level, station, or Centcom all have the same result.

## Reproduction:

1. Decide to abuse your admin powers by spawning Bubblegum at Centcom or on top of cocky miners
2. You can't!

**Comment by nemvar** [comment]
![Icanspawnhiminperfectlyfine](https://user-images.githubusercontent.com/47324920/62703336-45bc5600-b9e9-11e9-8429-c663b556654e.PNG)
I can spawn him in perfectly fine.

**Comment by kriskog** [comment]
If there currently is one active, it doesnt seem to work through the game panel -> spawn mob window. You'll have issues spawning hierophant using the spawn mob window too, as he relies on the beacon.

**Comment by Qustinnus** [comment]
```
	for(var/mob/living/simple_animal/hostile/megafauna/bubblegum/B in GLOB.mob_list)
		if(B != src)
			qdel(src) //There can be only one
			return
```
seems like intended behavior but might be a small oversight.

**Comment by ExcessiveUseOfCobblestone** [comment]
j-j-just check for adminspawn

**Comment by Daxxed** [comment]
If he is already alive you want to use Get mob to teleport him to your "cocky miners"
There can be only one, back when he was easier to kill I would oftenly solve those lavaland sliding puzzles as they have a chance to spawn bubs too, but only if he's dead already!
