### ISSUE TITLE
Gibbering Language Brain Trauma Doesn't Remove Correctly

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#45790]
Issue reported from  Round ID: 115388 (/tg/Station Bagil)

Testmerges: #44639: '[Ready] Ports dynamic gamemode from /vg/' by TheChosenEvilOne at commit f8ebbe0f8f
#43148: '[s]Temp workaround for admins matching stickybans because of a byond bug.' by MrStonedOne at commit e34fa30ce1
#45377: '[TMC] Baton rework' by Akrilla at commit bffab9cd5a

Reporting on behalf of a player. A player said they received brain damage and then started gibbering, which in-game doctors said was a trauma. Doctors cured his trauma but he still had the gibbering language and couldn't speak regular Galactic Common. His brain had no traumas in VV.

Logs from player:
`:#Todd Coddler(?|F) completes the surgery on Ted(?|F) Baker's brain.##You feel smart again.##The pressure inside your head starts fading.##You feel in control of your hands again.##You no longer feel afraid of lizards.##You suddenly remember how languages work.##Todd Coddler puts the hemostat into the medical duffel bag.##Todd Coddler begins to mend the incision in Ted Baker's head.##Todd Coddler finishes.##Todd Coddler puts the cautery into the medical duffel bag. `

Could not reproduce with the VV Cure Brain Traumas command, maybe it only happens with surgery..?

**Comment by TheChosenEvilOne** [comment]
Doesn't that come from brain damage and not a trauma?

**Comment by PKPenguin321** [comment]
The trauma is called aphasia

**Comment by ExcessiveUseOfCobblestone** [comment]
Only thing I can think of is perhaps he got aphasia twice and it did some heckery there.

The code for aphasia doesn't look sus.

**Comment by PKPenguin321** [comment]
Anybody seen anything like this lately? I'm thinking it may have been a misunderstanding or a one-off

**Comment by ExcessiveUseOfCobblestone** [comment]
i have not seen this since

**Comment by PKPenguin321** [comment]
Closing due to no repro
