### ISSUE TITLE
Infinite credits from gulag ore machine

### ISSUE THREAD

**Issue by Shapsy** [tgstation/tgstation#45808]
## Reproduction:
[![dreamseeker_2019-08-08_22-48-11.png](https://i.imgur.com/GcrGcES.png)](https://i.imgur.com/GcrGcES.png)
The following setup allows you to generate infinite credits very quickly, I'm not 100% sure on how it works, but this is what I was told

1. Setup a lathe in the gulag shuttle that you can pull minerals out of as seen in above picture
2. Pull minerals out and let it flow to the stacker, which gives you points and goes to the ore silo
3. GOTO 1

I assume the fix would be to not give points for already processed minerals

**Comment by kriskog** [comment]
Yeah, basically ore just going back and forth to the ore silo. Gulag only has the manual smelter, so unless that is replaced/reworked just removing the reward for processed materials would break gulag. Should probably just give them an ORM already.

**Comment by NoxVS** [comment]
I was the guy who did this, made over a million credits. How it works is that gulag prisoners get credits when they retrieve their items, with the credits depending on how many points worth of ore you delivered. You deliver ore in the processed form so you can just get materials from the lathe to turn in to the gulag which is immediately added back into the ore silo. Really this would be easiest solved by no longer paying prisoners when they finish their sentence. Its prison, not a job

**Comment by Dennok** [comment]
Yes. Why prisoners get credits. Maximum what it must get, a points to retrieve its items.

**Comment by Tlaltecuhtli** [comment]
remove manual smelters

**Comment by Dennok** [comment]
> remove manual smelters

For what?

**Comment by wesoda25** [comment]
Ahahah this is funny as fuck

**Comment by 81Denton** [comment]
@vuonojenmustaturska

**Comment by bgobandit** [comment]
and yet people still whine that tiny gulag sentences are perma
