### ISSUE TITLE
Certain emoji can't be used at the start of messages

### ISSUE THREAD

**Issue by flufflycthu1u** [tgstation/tgstation#45801]
## Reproduction:

Some emoji will trigger error messages of either "Only administrators may use this command" or "You do not have sufficient rights..." when used at the start of a message.

It is caused by an emoji like :disk: triggering the :d for dead chat admin command, and something like :peel: triggering the :p admin chat command.

Its a minor issue but it can be confusing to think that some emoji are admin only.

**Comment by ExcessiveUseOfCobblestone** [comment]
MY EMOJIS WERE MADE BEFORE THE ADMIN COMMANDS
