### ISSUE TITLE
(RussStation) Virus has hidden symptom in P.A.N.D.E.M.I.C

### ISSUE THREAD

**Issue by jzburda** [tgstation/tgstation#45810]
## Description:

I have a Virus with /Sneezing/Self Respiration/Regenerative Coma/Eternal Youth and Headache and it seems to also have Hallucigen  on it
## Reproduction:

Create a virus with /Sneezing/Self Respiration/Regenerative Coma/Eternal Youth and Headache and the virus will also have Hallucigen hidden. RussStation's github maintainer reports that they're forking directly off of a very recent version.

**Comment by kriskog** [comment]
How do you know it has hallucigen? Did an admin varedit the disease to check? There are other sources of hallucinations I would suspect before a hidden virus symptom, which is why I ask.

**Comment by jzburda** [comment]
> 
> 
> How do you know it has a hidden symptom? Did an admin varedit the disease to check? There are other sources of hallucinations I would suspect before a hidden virus symptom, which is why I ask.

I have about a 50% certainty because curing the disease also immediately removed the hallucinations.

**Comment by jzburda** [comment]
Alright, I recreated the virus in a test server.
So, I didn't get the results I wanted. I'm in the final stage of the virus, there is no hallucinations, and I'm on the final stage of the virus. I cannot safely say this was a blunder on my part, but I'm going to close this for now.
