### ISSUE TITLE
Trying to varedit a list value runtimes

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#45811]
Happens after #45217, reverting makes it work again.
Local server, current master.

Attempting to edit a key value in a list produces this runtime:
[02:38:23] Runtime in modify_variables.dm,196: list index out of bounds
  proc name: mod list (/client/proc/mod_list)
  usr: Skoglol/(Scott Smith)
  usr.loc: (Arrival Shuttle Hallway (53, 131, 2))
  src: Skoglol (/client)
  call stack:
  Skoglol (/client): mod list(/list (/list), null, "list", "contents", 1, 0)
  Skoglol (/client): vv do list(/list (/list), /list (/list))
  Skoglol (/client): view var Topic("_src_=vars;admin_token=8755723...", /list (/list), null)
  Skoglol (/client): Topic("_src_=vars;admin_token=8755723...", /list (/list), null)

#Reproduction:
Probably affects most lists but heres what I tried to do:
Spawn gas canister
Open air contents
Open the gases -> /gas/yourgas list
Attempt to edit key of the first var
Runtime, nothing happens.

**Comment by Cyprex** [comment]
@kevinz000
