### ISSUE TITLE
the durand shield doesnt seem to prevent 100% of frontal damage

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#45814]
![wwe2](https://user-images.githubusercontent.com/33834933/62773070-824b8880-baa1-11e9-8f5c-169475c1c18a.jpg)

115513

**Comment by nemvar** [comment]
Intended. Colossus projectiles call ex_act on structures they hit and the shield isn't supposed to block bombs.

**Comment by nemvar** [comment]
Sorry that you can't cheese this boss. Really sorry.
