### ISSUE TITLE
bitcoin assasin pod location was "space"

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#45823]
115588

the pod spawned in xenobio

**Comment by Akrilla** [comment]
The dropoff location was space?

**Comment by nemvar** [comment]
So what is it? Did it spawn in xenobio or space? Those two things are not the same.

**Comment by Tlaltecuhtli** [comment]
the drop off place written in the ipad was "space" when the dude pressed to extract it sent a pod in xenobio ( metastation)

**Comment by nemvar** [comment]
alright thanks.
