### ISSUE TITLE
Swarmers can destroy ATMOS resin, opening up areas to space

### ISSUE THREAD

**Issue by harmonyn** [tgstation/tgstation#45835]
## Round ID: 115606

##Reproduction:

Be swarmer, attempt to consume a tile of ATMOS resin blocking off an area exposed to space. It will just destroy similar to how intercoms do, without being consumed, probably due to ex_act memery; the important thing is they are not stopped from creating breaches like they are in all other circumstances

**Comment by SuperNovaa41** [comment]
Swarmers have been removed. https://github.com/tgstation/tgstation/pull/63989
