### ISSUE TITLE
Can place chairs in space

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#45849]
Issue reported from  Round ID: 115635 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1471

1) Pick up chair by dragging it to your sprite
2) Go to a space tile
3) Use the chair inhand
4) Space chair

You can't build chairs in space.

**Comment by ExcessiveUseOfCobblestone** [comment]
emergent gameplay
