### ISSUE TITLE
The organ smartfridge drops the wrong circuitboard.

### ISSUE THREAD

**Issue by nemvar** [tgstation/tgstation#45846]
## Reproduction:

organ fridge drops the circuit for the normal smartfridge when deconstructed.

**Comment by RandolfTheMeh** [comment]
Not a bug. All smartfridges drop the "smartfridge" circuit board. You set which storage type by applying a screwdriver to it, as per the heater/cooler, but unfortunately with a longer list. Problem is not unique to the organ fridge.

**Comment by ExcessiveUseOfCobblestone** [comment]
They all use the same circuitboard, but having it set to the last machine would be a nice qol
