### ISSUE TITLE
xenos can stun borgs

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#45857]
## Reproduction: 1. spawn xeno 2. spawn borg 3. xeno tackle borg

![image](https://user-images.githubusercontent.com/53100513/62830632-3c4d0c80-bbe8-11e9-9ff3-2eb96a7af313.png)

who coded this

100% salt issue but xenos are broken in every single way and everyone knows it

**Comment by ATH1909** [comment]
Yo was that last night? Were you a syndicate saboteur borg? I think I might have been that hunter.

Yeah, I'm pretty sure that this is intended. Note that the disarm from a xeno only stuns you if you're holding nothing, so a robust borg can quickly reequip something else before the xeno attacks them again to avoid the stun.

**Comment by carlarctg** [comment]
die forever, but also i don't think stunlocking (let alone stunning) a cyborg as a xenomorph is a thing that should happen, bug or not

and sure, a robust borg COULD do that, but they're still basically trapped and unable to do any real damage since they'd be hyperfocused on keeping something in their active. plus you don't automatically reequip things you put in your hands, so the xeno wins ez since they only have to press a single button

**Comment by Rowelll** [comment]
not a bug, post it on forum instead

**Comment by tralezab** [comment]
not a bug, i was considering leaving this open because it's kind of a really shit thing in my opinion but it's not to the level where it should be an issue

**Comment by carlarctg** [comment]
oh, that makes sense
