### ISSUE TITLE
Insanity is guaranteed when you are "a little bit hungry" for too long."

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#45874]
Issue reported from  Round ID: 115794 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1477
Your current mood
My mental status: AHAHAHAHAHAHAHAHAHAH!!
My current mood: I feel very upset.
Moodlets:
I'm getting a bit hungry.

**Comment by Shirbu** [comment]
![wahhIneedasnaccguessIwillgoinsanethen](https://user-images.githubusercontent.com/23252965/62846955-81288000-bc88-11e9-994c-5da99c7d446d.PNG)

**Comment by kriskog** [comment]
#45757 is merged, but none of the servers have updated until today. Closing this for now, but feel free to make a new one in a few days if it does not improve markedly.
