### ISSUE TITLE
Cloth golems turned into zombies revive as catatonic upon dying as a zombie and losing their head.

### ISSUE THREAD

**Issue by interestingusernam3** [tgstation/tgstation#45881]
Issue reported from  Round ID: 115837 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471

Exactly the title. The revived catatonic body will then zombiefy again.

Full story:
I got attacked by a zombie as a bronze golem, got species changed into a cloth golem, succumbed upon going into crit, revived as a zombie, got killed by a zombie, got my head cut off by a human and when the pile of bandages revived the resulting mob was a catatonic cloth golem.

**Comment by tralezab** [comment]
crazy edge case, wow

**Comment by ExcessiveUseOfCobblestone** [comment]
should golems *really* be zombified?

**Comment by tralezab** [comment]
no
