### ISSUE TITLE
Why is this happening?

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#45892]
## Round ID: 115867

![image](https://user-images.githubusercontent.com/37246588/62912444-31b08580-bd56-11e9-9cc5-60ecb1a6b4a2.png)

You should not be taking any damage whatsoever upon spawning in. I've been killed so many times by shit like this. At this point I think'd it'd be preferable to just make shuttle turfs unable to lose atmosphere, because this is ridiculous.

**Comment by PKPenguin321** [comment]
The shuttle not returning will happen if somebody won't get off of it, and it can be damaged if it remains like that. I don't believe this is a bug
