### ISSUE TITLE
Duplicate Announcements of Arrival

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#45891]
Issue reported from  Round ID: 115868 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

![image](https://user-images.githubusercontent.com/10467687/62910444-e185f300-bd56-11e9-870e-2bef83c95bc1.png)
![image](https://user-images.githubusercontent.com/10467687/62910454-ecd91e80-bd56-11e9-9c71-ed21ae7f96f5.png)

Witnessed three announcements of arrival.

Reporting client version: 512.1472

**Comment by cacogen** [comment]
I don't know if it's true but someone said over Common that round that the Arrivals Announcement message had been changed to read that. There's no requirement to keep the name or job field.

**Comment by kriskog** [comment]
From log chatter it seems the CE changed the announcement, replacing the name var with Respii Varenos.
