### ISSUE TITLE
Purified Artificer still have Narsie description

### ISSUE THREAD

**Issue by Michael-Ashfield** [tgstation/tgstation#45899]
Round ID: Round ID bugged, Terry on 2019/08/13 18:40 (GBT)

Purified Artificers still have Narsie text when examined, I am not certain but I assume this is the same for other purified constructs.

_This is  Artificer (573)!
A bulbous construct dedicated to building and maintaining the Cult of Nar'Sie's armies._

## Reproduction:

1. Put a purified soulstone into an empty shell
2. Make it an Artificer
3. Examine it

**Comment by ExcessiveUseOfCobblestone** [comment]
@wesoda25

**Comment by wesoda25** [comment]
Fortunately its not a debilitating issue, I’ll get descriptions for all the purified constructs up once I get back to my computer on monday.

**Comment by wesoda25** [comment]
@wesoda25 stop forgetting to do this

**Comment by wesoda25** [comment]
ok im here
