### ISSUE TITLE
clumsy self batonning has an extremly long paralyze timer

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#45918]
https://github.com/tgstation/tgstation/blob/8ad3beaab6300f25b00406f829fa2c4ef96ece63/code/game/objects/items/stunbaton.dm#L118

thats a paralyze(420)

**Comment by ExcessiveUseOfCobblestone** [comment]
haha featore

**Comment by kriskog** [comment]
Doesn't really feel like an oversight at all. All the clumsy effects are extreme, although granted this is the only one I know of that is explicitly made longer.

**Comment by PKPenguin321** [comment]
Clumsiness misfires are intentionally absurd, make a forum thread if you died to it or whatever

**Comment by ExcessiveUseOfCobblestone** [comment]
Oh I thought this wasn' taccounted for in the rework.

Post-PR it was lowered to 300 (100x3), not 420 (140x3).
