### ISSUE TITLE
Medical scanner shows empty non-functional organs list

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#45919]
## Testmerges:
#45377: '[TMC] Baton rework' by Akrilla at commit bffab9cd5a

## Reproduction:
1. Botanist moth eat some shit
2. Liver failure
3. Replace with upgraded cybernetic liver
4. Med scanner shows empty non-funcional organ list
4.1 Expected not to see this list at all
![](https://i.imgur.com/j4Eo54j.png)

**Comment by ExcessiveUseOfCobblestone** [comment]
did you still have the stuff that KO'd your liver in you...?

I see the non-functional is empty but the majorly damaged isn't.

**Comment by RandolfTheMeh** [comment]
The intended behavior was to report all three rows if any one row had data. At a glance you can tell the damages because of where the organ's placed (in this case the middle), so it means you can work quicker since you don't actually have to read it.

**Comment by kopoba** [comment]
> 
> 
> did you still have the stuff that KO'd your liver in you...?
> 
> I see the non-functional is empty but the majorly damaged isn't.
Screenshot was taken after liver was replaced with upgraded cybernetic liver so its normal to not show its damage(because its not damaged).
Sadly i don't know what poor moth eat before liver died and replaced. And my live logs are gone(not even sure i checked whats in his blood).

**Comment by ExcessiveUseOfCobblestone** [comment]
would be nice if it was not blue text like the rest of the medical output tbh.

**Comment by kopoba** [comment]
> 
> 
> would be nice if it was not blue text like the rest of the medical output tbh since it's basically a summary of organ damage

I think ive seen only one 
Non-functional organs:
line after replacing liver without midly damaged and slightly damaged. But im not sure. Looks like its moth second visit on screen.
I will try to reproduce this later.
