### ISSUE TITLE
paying pirates spawns them anyway

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#45913]
115963

pirates got paid and they spawned

**Comment by AnturK** [comment]
From quick glance at the logs it was paid off too late, the cut-off is ~2 minutes. Should probably be clearer when it happens.

**Comment by kriskog** [comment]
Were they actually paid as well? If the time limit has passed, should it be possible to pay?
I have been thinking the event needs a longer cutoff, maybe 3 minutes. Scrambling money together and getting them in the cargo budget almost always seem to take longer than 2.
