### ISSUE TITLE
Vomitgoose locker interaction and bluespace bodybag dupe

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#45928]
## Reproduction:
Place birdboat on top of an open bluespace bodybag. Close it, watch it look closed but actually be open despite birdboat being locked in it. This step is the same for lockers as well.
Close it again to properly close it.
Pick the bodybag up by dragging it onto your sprite.
It is now on the floor as well as in your hand.
Place the one you have in your hand.
Watch the bag on the floor teleport to the new position.
You still have a bag in your hand, place it down.
The last bag you placed is now a brand new bodybag.

**Comment by PKPenguin321** [comment]
What in gods name did they do to this goose's movement code? This shit is practically arcane

**Comment by Akrilla** [comment]
How is a simplemob that vomits this buggy?????

**Comment by Difrit** [comment]
Any code regarding the goose is entirely intentional and anyone who says otherwise makes I ded PRs, prove me wrong

**Comment by FloranOtten** [comment]
First the bluespace vomitgoose teleport bug, now this? Did they make the code with Eye of Newt and Tear of Salamander?

**Comment by bgobandit** [comment]
@plapatin

**Comment by TheChosenEvilOne** [comment]
It is clearly a feature

**Comment by tralezab** [comment]
confirmed fixed by my fix
