### ISSUE TITLE
Plastitanium windows are unable to be decontructed

### ISSUE THREAD

**Issue by LegendaryMister151** [tgstation/tgstation#45926]
## Round ID: 116025

Went through every tool in the toolbox (including welder on harm intent) and was unable to deconstruct a plastitanium window.

**Comment by ExcessiveUseOfCobblestone** [comment]
what did the examine text say or is there none for those

**Comment by LegendaryMister151** [comment]
doesn't mention any steps like normal and reinforced windows do
![image](https://user-images.githubusercontent.com/46329759/63132830-79baec80-bf90-11e9-90ab-4d92378f606c.png)

**Comment by FancyCyclops** [comment]
GAY BABY JAIL

**Comment by ExcessiveUseOfCobblestone** [comment]
windowjannie :omegalul:
