### ISSUE TITLE
New Stun and No Gravity

### ISSUE THREAD

**Issue by Malkraz** [tgstation/tgstation#45924]
Issue reported from  Round ID: 116011 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1474

When getting hit by the new stun (e.g with a stun baton) while floating through a no gravity environment, you will come to a dead stop on the last tile you reached rather than momentum continuing to carry you.

**Comment by Dennok** [comment]
Stun baton can stun inertia.

**Comment by TheBonded** [comment]
pretty sure hardstuns have been removed, and replaced with stamina damage
