### ISSUE TITLE
CRAB-17 can spawn in bad locations

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#45920]
![KREB](https://user-images.githubusercontent.com/32391752/63057532-c3e99280-beea-11e9-867a-cdab93b1a669.png)

This needs a better check than `get_safe_random_station_turf()` so it doesn't spawn in any of the 2353445 bad locations like the engine chamber, the incinerator or near space.

`generate_station_area_list()` could also use improvement, since the only blacklisted areas are `/area/space, /area/mine, /area/ruin, /area/asteroid/nearstation`.

**Comment by Akrilla** [comment]
Valid_territory is a reasonable way of doing it. It’s what cult uses

**Comment by Fikou** [comment]
feature
