### ISSUE TITLE
VV name edit and CKEY edit STILL broken

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#45930]
## Round ID:
116057 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1471

## Reproduction: 
VV name changer doesn't stick. Similar to #45738 and should have been fixed with #45742 but was not.

See Gifs:
![Gif1](https://i.gyazo.com/ceda75ad666cb6d3459f7665e4e19344.gif)
![Gif2](https://i.gyazo.com/895a4c0872a709fde56eeb9aa785ac3c.gif)
Steps:
Open VV of player. 
Change name using name title.
Enter new name and hit "OK".
Name appears to have been changed.
Hit refresh or any way that would update the mob (i.e moving, using an item etc).
Name reverts to old name

**Comment by peoplearestrange** [comment]
Seems to work on borgs. But still doesn't change the "real_name" VV
![Img](https://i.imgur.com/UlxOeWC.png)

**Comment by spessbandit** [comment]
this seems to have been fixed @peoplearestrange

**Comment by peoplearestrange** [comment]
Yeah i'm not sure when or with what PR... but I noticed a few days ago it appears to be working fine.
