### ISSUE TITLE
Blood brother hud runtimes at roundstart

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#45935]
## Round ID: 116062
https://tgstation13.org/parsed-logs/terry/data/logs/2019/08/15/round-116062/runtime.txt

[2019-08-15 15:48:06.958] runtime error: bad index
 - proc name: add to single hud (/datum/atom_hud/proc/add_to_single_hud)
 -   source file: hud.dm,114
 -   usr: null
 -   src: /datum/atom_hud/antag/team (/datum/atom_hud/antag/team)
 -   call stack:
 - /datum/atom_hud/antag/team (/datum/atom_hud/antag/team): add to single hud(SoapDispenser (/mob/dead/new_player), SoapDispenser (/mob/dead/new_player))
 - /datum/atom_hud/antag/team (/datum/atom_hud/antag/team): add hud to(SoapDispenser (/mob/dead/new_player))
 - /datum/atom_hud/antag/team (/datum/atom_hud/antag/team): join hud(SoapDispenser (/mob/dead/new_player))
 - brotherhood (/datum/team/brother_team): add member(/datum/mind (/datum/mind))
 - Blood Brothers (/datum/dynamic_ruleset/roundstart/traitorbro): pre execute()
 - dynamic mode (/datum/game_mode/dynamic): picking roundstart rule(/list (/list), 0)
 - dynamic mode (/datum/game_mode/dynamic): roundstart()
 - dynamic mode (/datum/game_mode/dynamic): pre setup()
 - Ticker (/datum/controller/subsystem/ticker): setup()
 - Ticker (/datum/controller/subsystem/ticker): fire(0)
 - Ticker (/datum/controller/subsystem/ticker): ignite(0)

**Comment by tralezab** [comment]
dynamic gamemode bug
