### ISSUE TITLE
Air Injectors Require Power

### ISSUE THREAD

**Issue by Davidj361** [tgstation/tgstation#45942]
## Reproduction:

![](https://i.imgur.com/iZf6YMB.png)

Go on ~~metastation~~ pubbystation, go to toxins, create a fire in incineration chamber and try to eject the gas.

It won't eject because the air injector has no power in space. The injection unit outside can't be turned on/off or have the flow edited. In my opinion it shouldn't require power at all.

**Comment by tralezab** [comment]
i'm confused about this because there are no space air injectors for toxins on meta...?

**Comment by Davidj361** [comment]
> 
> 
> i'm confused about this because there are no space air injectors for toxins on meta...?

Added a screenshot

**Comment by tralezab** [comment]
perfect, thank you. i'll fix it

**Comment by tralezab** [comment]
aaah that's why i couldn't find it, it was on pubby
