### ISSUE TITLE
Using more than one display as an AI

### ISSUE THREAD

**Issue by JAremko** [tgstation/tgstation#45954]
When playing as an AI it could be extremely useful to display "Crew Monitor" at another display but for some reason I can't drag it there but it works with the "Crew Manifest".  I think it happens because  "Crew Manifest" is normal Windows Window and  "Crew Monitor" is "fancy" (has fancy border and top right buttons) 

I'm running Windows 10

- - - - - - - - -

I would much prefer if "Crew Monitor" was plain window but it could be dragged to another display. Also it would be epic if  I could sort crew by  Status or Vitals.

**Comment by Dennok** [comment]
You can set in config, window mode with no frills.
Game Prefences > tgui Style: No Frills
This return system borders to all windows.

**Comment by JAremko** [comment]
@Dennok  Hey it helped! Thanks. 

But I still would consider "with frills" to be bugged.

**Comment by Dennok** [comment]
I have problem with this frills when window appears partially over up of the screen, and i can't move or close it.

**Comment by dragomagol** [comment]
@Dennok if this is still an issue you might want to make another bug report. Otherwise this seems to have been resolved.
