### ISSUE TITLE
Standing next to a BoH bomb transports you to the shadow dimension

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#45956]
I have noticed this a couple times while BoH bombing. One round I BoH bombed the last head of staff during a rev round and found that they were reported to have survived but fled the station. Much more recent I BoH bombed a wizard who was right next to me, but the round didn't end. I went to orbit the wizard to see how they were still alive to find that it was impossible to orbit them. Their name was in the orbit list but when I selected them nothing happened. Eventually the wizard body ended up in the super secret room on the CentCom z-level and they died of their wounds there. I don't know if it naturally ended up there or if admin fuckery brought it there or what. I did some testing later with Virtual John and we couldn't figure out where the body was going. Like before you could find it in the orbit list but it couldn't actually be orbited, GPS signals on the body would vanish once they got bombed, somehow the body was gasping but we couldn't find it anywhere

Issue reported from  Round ID: 116098 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

**Comment by NoxVS** [comment]
Log diving after tests shows that the bodies end up in UNKNOWN (?, ?, ?)

**Comment by kriskog** [comment]
When you get eaten by the new boh singularity, you get forcemoved into it (now in the contents list) and ghosted. There's nothing killing you or deleting you, so this is expected behaviour. Should probably just kill people that get sucked in, and take care of reviving them in the retrieve proc instead.

**Comment by ExcessiveUseOfCobblestone** [comment]
the orbiting thing sounds like a bug though, it would be like not being able to orbit someone because they're in a locker.

**Comment by kriskog** [comment]
Sure, if you nullspace the locker first.

**Comment by ExcessiveUseOfCobblestone** [comment]
oh yeah the singulo disappears...

mega cringe...

**Comment by nemvar** [comment]
Nullspacing living mobs with client is a big nono. Don't do it idiot.

This is done every Life to make sure it doesn't happen.
```
	if (client)
		var/turf/T = get_turf(src)
		if(!T)
			for(var/obj/effect/landmark/error/E in GLOB.landmarks_list)
				forceMove(E.loc)
				break
```

**Comment by trollbreeder** [comment]
Looks like you're going into the shadow realm, jimbo.

**Comment by adamkad1** [comment]
i was pretty sure bohbombed mobs go into a locker for a while for admins to retrieve them if need be, if they dont they get deleted after a while
