### ISSUE TITLE
Emergency escape pod didn't launch when the shuttle did

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#45960]
https://cdn.discordapp.com/attachments/326826573951008769/611829561046597632/bug_report_1.PNG
https://cdn.discordapp.com/attachments/326826573951008769/611829643871387648/bug_report_2.PNG

When the shuttle left, the pod did not. We were counted as being marooned at the end of the round.

This might not be the cause of the issue, but earlier in the round, I was contractor podded out of that escape pod on its door tile. Perhaps that broke the pod's area or something?

I was also infected with Severe Anxiety, so perhaps the large number of butterflies in the pod kept it from launching?

**Comment by Dennok** [comment]
> ontractor podded out of that escape pod on its door tile

Think issue  in here. Contractor ruin the shuttle marker, that in door  tile, by teleport it.

**Comment by Dennok** [comment]
If it true, in this way can be destroyed all shuttles like arrival or escape.

**Comment by Dennok** [comment]
Nice, as i see carg pod return can steal all from turf. include shuttle docking markers.
https://github.com/tgstation/tgstation/blob/6a1aa46aa12294b0cbd7f7f940f375b3ccbaca2d/code/modules/cargo/supplypod.dm#L123-L126

**Comment by Akrilla** [comment]
h
