### ISSUE TITLE
Anti-magic does not prevent wizard event fuckery

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#45966]
Issue reported from  Round ID: 116143 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1477

Gained anti-magic through Curse of Madness trauma, but was effected by cursed items (from Summon Events) later in the round.

**Comment by Tlaltecuhtli** [comment]
being able to be events proof? hmmmmmmm

**Comment by PKPenguin321** [comment]
Not convinced that this is a bug, I don't believe this functionality was ever even considered

**Comment by necromanceranne** [comment]
It was a thing for a period. Whether it was intentional at the time or not is debatable but it was possible and now isn't.

**Comment by kriskog** [comment]
Fairly sure the null rod does (did?). Maybe its just cursed items.

**Comment by XDTM** [comment]
Any magical effect has to manually account for antimagic, and i only did spells and wand projectiles when i first added it. This is an oversight, not intentionally left out.

**Comment by PKPenguin321** [comment]
That's about what I thought. This issue is then a feature request/balance request, so take it to the forums if you're interested in pressing it further.

**Comment by XDTM** [comment]
that's kinda the opposite of what i said though

i forgot to account for magical events and miscellaneous artifacts when making the feature, so this is an oversight issue really
