### ISSUE TITLE
There is currently no method of deconstructing shuttle/pod airlocks without heavy weaponry.

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#45978]
Issue reported from  Round ID: 116169 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1477

To reproduce:

Attempt to use tools to cut all the wires in a door without dropping the bolts

Bolts drop even if power is cut first

bolts drop if power is cut second

pulsing a cut bolt wire does nothing

shuttles provide power from an infinite internal apc, so its impossible to turn off power to the door

get a gun and shoot the door to pieces instead

cry

**Comment by kriskog** [comment]
> 
> 
> Attempt to use tools to cut all the wires in a door without dropping the bolts
> 
Don't cut all the wires. You just need to cut power.

> Bolts drop even if power is cut first
> 
Don't cut the bolt wire

> bolts drop if power is cut second
>
Don't cut the bolt wire
 
> pulsing a cut bolt wire does nothing
> 
It does if you fix the wire, and ensure the door has power.
