### ISSUE TITLE
can't Alt+click on the SM

### ISSUE THREAD

**Issue by Ghilker** [tgstation/tgstation#45985]
Issue reported from  Round ID: 116206 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Like the title says, you cant alt+click on the SM crystal to open the floor menu which is used to safely remove the plating

Reporting client version: 512.1477

**Comment by nemvar** [comment]
Probably caused by all the people that touched alt-clicking for machines recently.

**Comment by nemvar** [comment]
Getting fixed by #45769
