### ISSUE TITLE
The Supermatter can just randomly get fusion temperatures.

### ISSUE THREAD

**Issue by CRITAWAKETS** [tgstation/tgstation#46006]
## Round ID:116406 (On Sybil)

The supermatter just instantly went to fusion temperatures without any tritium or plasma or CO2. Just pure N2 in there. The temperature then rapidly declined but still stayed at extremely high levels.

https://i.imgur.com/Qtwpv6Q.png

The odd thing is that this also happened on a round a few months ago where i was the CE but i didnt make an issue report just in case this was a one-off thing caused by something i ignored.
Im guessing this is an underflow issue, where the gas emitted by the SM is so cold that it just underflowed to ridiculous levels.
## Reproduction:

There are no reproduction steps i can discern.

**Comment by Ghilker** [comment]
ehhh in this round a fusion canister broke and the heat reached the SM, this is not a bug

**Comment by CRITAWAKETS** [comment]
The fusion did not even breach before the SM already went to thermonuclear levels, and the SM was hotter than the fusion.

**Comment by Tlaltecuhtli** [comment]
time to move atmos to double instead of floats

**Comment by nemvar** [comment]
I remember similar bugs with miasma production, I have seen them like two times and never after that.

They seems to be fairly hard to reproduce but randomly reaching infinite heat is a thing that just kinda tends to happen when atmos is fairly active.

**Comment by redmoogle** [comment]
can't wait to die from atmos code again

**Comment by wesoda25** [comment]
Oh DEAR

**Comment by Ghilker** [comment]
Ok it happened one more time during a round where fusion got released. Seems that when atmos code is very busy, SM goes bonkers and heat up.
Reproduced also in a private server. 
1 make a fusion canister
2 connect the canister to a pipe network
3 unwrench on of those pipe and release fusion
4 ???
5 profit with the SM going nuts

**Comment by CRITAWAKETS** [comment]
I FOUND OUT WHAT HAPPENS, ITS A DIFFERENT ISSUE.

FUSION CAN HEAT SPACE UP.

**Comment by Ghilker** [comment]
you wot mate?
FUSION CAN HEAT SPACE?? HOW IN THE HELL????
i guess that even space can't contain 1e30 °C of raw power

**Comment by Detective-Google** [comment]
Fusion doesn't heat space per se but what it does do is somehow heat the spaceloop, in other words, fusion can heat h/e pipes in space

**Comment by Detective-Google** [comment]
> Fusion doesn't heat space per se but what it does do is somehow heat the spaceloop, in other words, fusion can heat h/e pipes in space

I found this out through a lot of dumb engines going "unga bunga engine unsaveable" and then just cutting off the space loop and switching to freezers, the SM room temp was fine the space loop was just a bajillion degrees for whatever reason

**Comment by kriskog** [comment]
This was very likely the fusion heating space issue that was fixed. If it happens again, open a new issue.
