### ISSUE TITLE
Borgs cant walk through holo walk signs

### ISSUE THREAD

**Issue by Michael-Ashfield** [tgstation/tgstation#46010]
## Reproduction:
Become a janiborg
Use the custodial holobarrier projector to place down a wet floor holobarrier
Try to move through it
Fail to move through it because you're a borg who cant walk

**Comment by adamkad1** [comment]
its because borgs are too fasta

**Comment by zxaber** [comment]
Borgs can walk by holding Alt. Does that fix it?

**Comment by zxaber** [comment]
Borgs can walk by holding Alt. Does that fix it?

**Comment by adamkad1** [comment]
> Borgs can walk by holding Alt. Does that fix it?

Whaaaat

**Comment by Michael-Ashfield** [comment]
> Borgs can walk by holding Alt. Does that fix it?

I cant remember but I think I tested that and they still couldn't pass, I will have to double check.

**Comment by spessbandit** [comment]
the real question is, do we want borgs to be able to pass through holobarriers? if so, all of them, or just a few? does it make sense to have an anti-silicon version?
