### ISSUE TITLE
Scooters let you pass through timestop

### ISSUE THREAD

**Issue by ariever** [tgstation/tgstation#46012]
I saw someone pass through a wizard's time stop on a scooter one sybil round.

How to do it: 
Get on scooter. 
Have a wizard use time stop.
Run through the time stop area while on scooter, watch as your character gets time stopped but the scooter, unaffected by silly concepts like time and space, drags you along, letting you pass safely through the time stop area and continue on your journey.

**Comment by kriskog** [comment]
Nice

**Comment by kriskog** [comment]
I tested this real quick, can't reproduce. I expect they had some form of anti-magic, I have seen it some times invert your colors despite you being unaffected by timestop.

Just running into wizard timestop on a scooter will stun you and unbuckle you from the scooter.
