### ISSUE TITLE
APC placement does not respect placement direction

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#46021]
Or, the "Area" for an APC should be based on where its wire terminal would be rather than the area of the wall tile its self.

100% reproduction on Runtime station:
Grab gloves + welding mask (if you like) 
Go to the Central Primary Hallway and deconstruct the APC, including removing the frame.
Attempt to place the APC back on the wall
Experience the error "This area already has an APC!"

In fact, I'm not sure there's an available wall in primary corridor that will accept the APC.

To debug this issue I modified 
code/game/objects/items/apc_frame.dm line 97 to
to_chat(user, "<span class='warning'>This area [A.name] already has an APC!</span>")
which quickly revealed the problem, attempting to re place the APC where it was dismantled from produces:
"This area Science Division already has an APC!"
which it does.

I would suspect the problem originates from the fact a tile must be in a singular area and thus walls are inherently complex as they border two areas.

The best off hand solution would seem to be to figure out where the floor terminal would go (adjacent tile inside the area) and use that area instead.

This has happened a few times on Metastation with various APCs and often confused me as to why I can't re-place it, though often trying different sections of wall can help, runtime's central corridor appears to have no walls it actually owns, but building a wall from girders in the middle of the area suffices, and this is a usable although "unsightly" workaround in most game situations.

Thanks

**Comment by nemvar** [comment]
The fix is a oneliner.

**Comment by iprice** [comment]
Yeah, I think
code/game/objects/items/apc_frame.dm:123
to
var/area/A = get_area(user)

I was concerned about crossing areas with a diagonal placement, but this appears not to be allowed when I try this issue.  Someone who knows the code better would know better hopefully :)

**Comment by nemvar** [comment]
Correct

**Comment by iprice** [comment]
I made a pull request, my first for any project ever (not used to collaborating much)
https://github.com/tgstation/tgstation/pull/46023
Hopefully I did it right.
