### ISSUE TITLE
Charlie rework issues

### ISSUE THREAD

**Issue by LoGIRz** [tgstation/tgstation#46028]
## Charlie Station ruin problems as introduced by the rework (#45838)

- Two Charlie Station APCs: Kitchen and Engineering, start disconnected from the grid. It looks like an oversight rather than something that can be explained by the wear of the station since you have to pry up the floor tiles to fix it in an otherwise largely intact space and the APC terminals lacked wiring which may be easily overlooked on an overview
![image](https://user-images.githubusercontent.com/29038228/63291040-68911900-c2cb-11e9-9d27-74b32c298967.png) ![image](https://user-images.githubusercontent.com/29038228/63291084-89f20500-c2cb-11e9-8029-3eb91f0a392e.png)

- Two hivebots surrounding the weapons crate in Delta remain from the old iteration, their replacement with benos was presumably stated to be absolute.

- Speaking of benos, they are completely braindead. They didn't fight back against the hivebots' nor any attacks nor when they saw me and neither did they move at all from their spaces

- The three Delta Vault/AI doors past the airlock with double doors didn't have anything below them, the tile being completely open to space once they were opened.

- This wasn't a problem when the xenos weren't in the picture, but there's no welding fuel tanks in what's presumably the main engineering area when you may want to repair/tear down walls, attack downed aliens, weld vents shut or just clean up resin floors for aesthetic purposes

- May not be easy to fix, but since the Beta/Charlie/Delta complex lacks roundstart telecom machinery, the radio headsets in the two locked closets by you when you spawn are essentially unusable

**Comment by redmoogle** [comment]
fixing

**Comment by LoGIRz** [comment]
Oh right another minor thing that happened is the sprite for the jumpsuit on the Charlie engineer didn't appear like in #45909 and unequipping/reequipping didn't immediately resolve it. However it fixed itself somehow at some point, probably from wearing either the degrading body armor or the Voidsuit

**Comment by redmoogle** [comment]
> 
> 
> Oh right another minor thing that happened is the sprite for the jumpsuit on the Charlie engineer didn't appear like in #45909 and unequipping/reequipping didn't immediately resolve it. However it fixed itself somehow at some point, probably from wearing either the degrading body armor or the Voidsuit

thats another issue with jumpsuits being weird

**Comment by Tharcoonvagh** [comment]
Now you can not perform surgery on MOST of the xenos. Great.

**Comment by LoGIRz** [comment]
I assume whoever made that decision will revert it when the beno queen won't literally just stand there waiting for you to walk up and butcher her for the epic self-antagging memes

**Comment by adamkad1** [comment]
yeah, the goddamn benos are goddamn docile, couldnt you copy them from lavaland ruin or something

**Comment by redmoogle** [comment]
Doesn't work like that
