### ISSUE TITLE
Plasma Spears have no In-hand

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#46036]
Issue reported from  Round ID: 116520 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

Basically, they have no inhand sprites at all and don't even have a back sprite. They're completely invisible.

**Comment by nemvar** [comment]
Fairly certain plasma spear inhands actually exist.

**Comment by necromanceranne** [comment]
Weird. So I constructed one and it didn't have in-hand sprites whatsoever. I wasn't really sure what was happening or what might have caused that. Did you spawn this one in or did you actually construct it?

**Comment by nemvar** [comment]
Alright, I have this figured out. Only the right inhand is missing. The left one exists.
