### ISSUE TITLE
Mulebots don't change the pixel_y after the first time.

### ISSUE THREAD

**Issue by tralezab** [tgstation/tgstation#46030]
## Round ID:

local updated master

## Testmerges:
N/A

## Reproduction:

Get on a mulebot
Get off the mulebot
Get on the mulebot again, you will now not be raised up on the mulebot.
video: [here](https://youtu.be/F84tmdwir18)

**Comment by nemvar** [comment]
Do you get lowered after leaving the mulebot again?

**Comment by tralezab** [comment]
nope.

**Comment by persorkki** [comment]
it gets the riding component when player gets on it but it is never removed. nulling the components list for example fixes it (until you step off again). why it doesnt work when you're riding is still a mystery to me (been looking at this codebase only for a few days). it seems like that's not the way other vehicles are handled anyway
