### ISSUE TITLE
functioning MMIs can have brains in them that are "too damaged" to be put in a borg shell

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#46041]
Round ID in which this bug occurred in: 116552

Basically, I died in an away mission as a roundstart borg (who used a gateway to get to the away mission, of course). A warden and a sec officer who really, really needed a mediborg to treat their wounds deconstructed my dead body, bringing me back into the game as an MMI (which could talk, hear, be heard, etc.). They used their two flashed and the borg parts from the deconstructed borg body to make a new borg shell, then tried to put me in it... only to be told that my brain was "too damaged" to become a borg (even though it was still able to operate and speak through an MMI?). We didn't test to see what would happen if my brain was removed from and then placed back in the MMI. The warden and sec officer fell into crit and slowly died in front of me because I was unable to be re-borged.

**Comment by nemvar** [comment]
Probably my fault. Will look into it.
