### ISSUE TITLE
ghosts can still buzz mulebots DUMB IDIOT CODERS

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#46052]
you can still clickdrag living mobs and objects onto mulebots as a ghost.

**Comment by tralezab** [comment]
IMPOSSIBLE

**Comment by tralezab** [comment]
if(!istype(AM) || isdead(AM) || iscameramob(AM) || istype(AM, /obj/effect/dummy/phased_mob))

this is used on the mulebot check, my money is on the server not getting updated

**Comment by tralezab** [comment]
my good fella @kriskog tested this, it's real. aaaaaaah

**Comment by Akrilla** [comment]
checking for everything besides ghosts...

**Comment by Akrilla** [comment]
oh no wait it's because you don't check if the person putting the obj on is a valid person

**Comment by kriskog** [comment]
Its because (istype(L) && !(L.mobility_flags & MOBILITY_STAND)) returns false if user is not living - skipping the return.

**Comment by Akrilla** [comment]
oh kek
