### ISSUE TITLE
Some Escape Shuttle tiles are bugged

### ISSUE THREAD

**Issue by Alterist** [tgstation/tgstation#46059]
Issue reported from  Round ID: 116648 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1477

Some shuttle tiles can't be crowbar-ed, and instead spawns an infinite amount of tiles

![scrnshot1](https://user-images.githubusercontent.com/38592768/63423252-731fef80-c43e-11e9-905a-0b1281231bc1.png)

**Comment by msgerbs** [comment]
I believe this is resolved. I'm unable to reproduce this and I do remember a PR from a while back that dealt with an issue like this that I believe was related to baseturf runtimes so I'm going to call this fixed.
