### ISSUE TITLE
Plasma Fixation doesn't fully work. Bug report & feature request

### ISSUE THREAD

**Issue by glubtok** [tgstation/tgstation#46055]
I can't make a pull request, nor am I knowledgeable enough to solve this issue in its entirety, so I'll leave what little progress I made here for someone else to deal with. Currently, plasma fixation only heals when injected in reagent form. According to the wiki and what's implied in the code, it's also supposed to heal if you're standing in a visible amount of plasma gas. This has not worked for the few months I've played on tgstation-based servers.

So here's the fix, tested and working:

/code/datums/diseases/advance/symptoms/heal.dm

Change line 373 from:
`if(gases["plasma"] && gases["plasma"][MOLES] > gases["plasma"][GAS_META][META_GAS_MOLES_VISIBLE])`

to:

`if(gases[/datum/gas/plasma] && gases[/datum/gas/plasma][MOLES] > gases[/datum/gas/plasma][GAS_META][META_GAS_MOLES_VISIBLE])`

Probably a change to the data structures of gases broke this.
__________________________________________________________________________________

This is where the bug report ends, and the feature request/oversight fix begins. There's a case that seems very much like it should apply plasma fixation's healing, and that is **breathing** plasma from internals. Whether you're a plasmaman or human, breathing 100% 16 KPa plasma via internals does not proc the healing effects of plasma fixation. I've ripped my hair out trying to find any sort of documentation/variables regarding the contents of a breath, but it seems extremely convoluted with how it's handled. If there's anyone here who knows how to get that to work, could they please fix it? Thanks.

**Comment by ATH1909** [comment]
The problem with making plasma fixation heal you when you breathe in plasma is that it makes a plasma fixation+inorganic biology busted really, really strong for plasmamen.

Then again, plasmamen have a 1.5x weakness to brute and burn damage, so perhaps it's not so bad to throw plasmaman virologists a bone like this.

**Comment by glubtok** [comment]
> 
> 
> The problem with making plasma fixation heal you when you breathe in plasma is that it makes a plasma fixation+inorganic biology busted really, really strong for plasmamen.
> 
> Then again, plasmamen have a 1.5x weakness to brute and burn damage, so perhaps it's not so bad to throw plasmaman virologists a bone like this.

Plasmamen are already handicapped in terms of the level of healing they can get from diseases. Almost all healing symptoms need stage speed as a threshold. None of them provide a stat boost to it, and some actually have a penalty to it. Adding inorganic biology just so they can get the disease effectively takes up the place of a healing symptom, as it has a hefty stage speed penalty. With organics, you can stack any two fully buffed healing symptoms with decent stats.

**Comment by ATH1909** [comment]
You know what, I'll make a PR to implement your change (and buff plasma fixation slightly) now.

**Comment by timothymtorres** [comment]
This was fixed with #46151 however there are still some lingering plasmamen issues that are outlined in #61424.
