### ISSUE TITLE
Map vote fucked

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#46054]
## Round ID: most of the rounds

Okay, so this is not a bug. Most of the time, when we get any map by map rotation, some moron starts a vote, and because people who won't vote forgot/didn't care about the default map preferences in the settings, WE CAN NOT PLAY ON ANY OTHER MAP THAN META. I heard in OOC that TCHO tried to make it like maps will change after three rounds with the same map, it would be way better than currently. Please do something.

**Comment by kriskog** [comment]
Feature request, take it to the forums. 

Also I am fairly sure Nervere explicitly removed metastation from the default as map vote was added to prevent this.
