### ISSUE TITLE
Missing any limb overriddes full augmentation status

### ISSUE THREAD

**Issue by remuluson2** [tgstation/tgstation#46061]
Issue reported from  Round ID: 116658 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1466

Exactly what it says on the tin. Losing any part after getting fully augmented makes you lose that status and take fire and pressure damage.
I believe its just doesnt counts missing limbs as full auged.

**Comment by ATH1909** [comment]
In an ideal world, we should change it so that pressure and/or cold damage is checked (and applied to if that check fails) for each individual limb. In other words, if you're half-augged, we should make it so that  only your fleshy bits take damage from space and cold.

**Comment by ATH1909** [comment]
Is full augmentation status what lets you put stuff in your pockets without a jumpsuit as a fully-augged person? Does this mean that if you cut a fully-augged person's arm off while they're not wearing a jumpsuit, they'll drop everything in their pockets?

**Comment by tralezab** [comment]
i decree it should totally work

**Comment by nemvar** [comment]
I mean, you probably still have fleshy bits under the robotic limbs (you still bleed and stuff) so it kinda makes sense that you would take fire and pressure damage.

**Comment by TheBonded** [comment]
I'm fairly certain that right now, augged limbs just reduce the damage taken to that limb, and that a fullaugged status is no longer used
