### ISSUE TITLE
xenos on charlie

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#46066]
Benos on charlie are not mob xenos like the one on lavaland, they are REAL xenos. thats bad because of two things
1-they sit there and do nothing as you butcher them
2-you can brain transplant one of your buddies into queen to get a REAL beno queen. thats not good for obvious reasons

**Comment by Dorsisdwarf** [comment]
Actually the fix to this was merged a few hours ago, it should roll out onto the servers soon.

**Comment by adamkad1** [comment]
Dont forget about terry though
