### ISSUE TITLE
Aliens on Charlie station (Old Cryogenics Pod) are not hostile to players.

### ISSUE THREAD

**Issue by CrossbowDemon** [tgstation/tgstation#46087]
Issue reported from  Round ID: 116758 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1478

**Comment by Fikou** [comment]
the pr that fixes it is already merged terry just needs to update

**Comment by nemvar** [comment]
This has been fixed. Thanks for reporting it anyways.
