### ISSUE TITLE
Some bugs with the new C2 medicines

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#46094]
#### Round ID:
Locally, updated right after #45749. 

Bugs:
- Sanguibital has a typo in its in game name "Sanobital". 
- Multiver deals toxin damage instead of heals.  
- Aiuri causes permanent nearsightedness. Adminheal/oculine will cure the eye damage and blindness, but not the nearsightedness. Nearsightedness from screwdriver to eyes was still curable with adminheal. 
- Fiziver heals toxin damage extremely fast, like 40 per tick after a couple of seconds.

**Comment by Akrilla** [comment]
Multiver deals toxin damage instead of heals. :worry:

**Comment by ATH1909** [comment]
Why does Aiuri have these two variables?
	var/resetting_probability = 0
	var/message_cd = 0
I can't seem to figure out what's wrong with aiuri; maybe it's a problem with organ damage received from chems not updated an organ's state properly (perhaps it has something to do with that new liver issue?)?

**Comment by ExcessiveUseOfCobblestone** [comment]
neomycin sulfate (aiuri) used to induce vomit with frequency scaling with exposure.

**Comment by RandolfTheMeh** [comment]
The nearsightedness is an issue with how I coded the eye damage clearing, as it only clears the blindness overlay, and not any/all that have been passed, instead requiring eye surgery or oculine. I'll be addressing it soon, as part of a cleanup on the original PR, as I think having to have every heal effect that would restore eyes do so is asinine when it could just be part of the eye code, and there'd be no need to tack it on to each chem/heal/surgery.

**Comment by kriskog** [comment]
These are all fixed
