### ISSUE TITLE
Fiziver is bad.

### ISSUE THREAD

**Issue by nemvar** [tgstation/tgstation#46097]
## Reproduction:

Here's the issues with it
Number 1:
Stamina mod does not get reset.
Number 2:
The mods are getting modified with addition when all other (sane) sources of physiology mods use multiplication.
Number 3:
Purging Fiziver sets your damage mods to a minimum of 1, although values below 1 are perfectly valid.

**Comment by ATH1909** [comment]
Also, the mods START insanely high. The first tick will have it heal 5 tox damage, with that increasing even more on the second tick and beyond.

Basically, it's a near-instant tox damage heal.

**Comment by ATH1909** [comment]
#define FIZ_WEAKRATE	0.005

var/maths = FIZ_WEAKRATE * current_cycle
	reset_mods += maths

M.adjustToxLoss(round(reset_mods*-1000,0.01)) 


HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

**Comment by nemvar** [comment]
Yes, they pointed that out on le reddit because I literally said it in this PR.

**Comment by PKPenguin321** [comment]
Fixed in https://github.com/tgstation/tgstation/pull/46157 as far as I can tell
