### ISSUE TITLE
#45914 didn't get a changelog

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#46090]
## Round ID:
116773

## Reproduction:

1. Click Changelog
2. Ctrl+F text from #45914 changelog (e.g. "Hydroponics trays update their name")

**Comment by cacogen** [comment]
so if this isn't a bug, what did i do wrong?

**Comment by actioninja** [comment]
changelogs are generated by the server bot which was down while a couple of PRs were merged. Someone should probably manually generate them but it's not super important.
