### ISSUE TITLE
Mob overlay sprite issues master thread

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#46099]
**MAINTAINER NOTE: COMMENT ANY SPRITE ISSUES YOU NOTICE ON THIS ISSUE**

## Round ID:
116819

## Testmerges:
#46058: 'sound environments' by actioninja at commit e5f8027911
#45961: 'Obliterates item_color: new washing machine functionality edition' by actioninja at commit 869dfd1f13

## Reproduction:
1. Join as shaft miner
2. Put on explorer suit and toggle hood
3. You are bald now and without hood
https://i.imgur.com/wB5C2BY.jpg
https://i.imgur.com/953NZL8.jpg

**Comment by kopoba** [comment]
Some wired thingies hapening
1. player sprite goes above chairs
2. Hos suit have engi body and hos helmet
both you can see on screenshot
https://i.imgur.com/7kMug2U.png

**Comment by kopoba** [comment]
Hats and cloaks also affected
https://i.imgur.com/ku43Fjd.png

**Comment by actioninja** [comment]
I ended up going with a bit different of an approach that should be less prone to these issues

**Comment by PKPenguin321** [comment]
We had ought to have a specific tag for overarching issues like three

**Comment by kopoba** [comment]
ERT hardsuit got Engi helmet

**Comment by kopoba** [comment]
99% sure all fixed
