### ISSUE TITLE
Dullahan Heads are uninteractable, and dullahans cannot switch their race back using the magic mirror without breaking fully

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#46093]
Issue reported from  Round ID: 116804 AND 116805 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1478

To reproduce:

Use magic mirror to be dullahan

Be unable to wear wizard hat and ohfuckgoback to a regular race

find that you cannot pick up your head again, or pull it, or examine it with shift click

find that when you change races, you still have no head, and your outward appearance does not change, but you lose UI features to get back your head view

cry

**Comment by nemvar** [comment]
Halloween and Species milestone ahoy.

**Comment by ATH1909** [comment]
Can you turn into a slime person and regenerate your head?

**Comment by kriskog** [comment]
Just remove from magic mirror tbh

**Comment by dragomagol** [comment]
Appears to have been fixed
