### ISSUE TITLE
Blood Rites can absorb monkey blood, but only if used on a blood splatter.

### ISSUE THREAD

**Issue by blessedmulligan** [tgstation/tgstation#46104]
## Round ID: 
N/A, discovered during testing an unrelated feature

## Reproduction:

Be a blood cultist, prepare the blood rites spell. Beat a monkey to death, walk over one of its blood stains to track it on the floor/drag the monkey to leave a trail. Clicking on the footprints/trail with blood rites will not absorb the blood (human blood footprints/blood trails CAN be absorbed). However, clicking on a splatter WILL absorb that blood, as well as any nearby footprints/blood trails.

**Comment by Sealed101** [comment]
could not reproduce; footprints with even a small amount of blood in them (`bloodiness` var) did contribute to the final charges gained
also see #76852
