### ISSUE TITLE
You can make infinite gaseous plasma by drawing from and injecting a beaker of plasma repeatedly

### ISSUE THREAD

**Issue by Dawson1917** [tgstation/tgstation#46100]
## Reproduction:

1. Get a beaker with some ground up plasma inside.
2. Draw from the beaker with a syringe, then inject it back in.
3. Plasma will leak into the air but the full amount of plasma will be transferred into the beaker, allowing you to repeat the process forever.

You can fill a space the size of the thunderdome in 15 seconds of pumping and drawing. Good fun.

**Comment by kopoba** [comment]
Slime cores also affected by this bug

**Comment by kriskog** [comment]
Just to be clear, the bug is the plasma release on syringe injection. It's not supposed to do that.

**Comment by msgerbs** [comment]
> 
> 
> Just to be clear, the bug is the plasma release on syringe injection. It's not supposed to do that. Did someone change the reaction types of syringes in the last few months?

Maybe as part of the medical overhaul?

**Comment by msgerbs** [comment]
Looks like #44531 changes trans_to() such that if method is passed it triggers that reagents reaction. Plasma always creates plasma in the air when it reacts. And syringes use method=INJECT, causing the syringe to react.

**Comment by Angustmeta** [comment]
Probably related to #45020

**Comment by msgerbs** [comment]
Definitely. Anything where you inject syringes will cause it to do react_obj. I'm not really sure how to fix this without also fucking with medchems. Maybe @ExcessiveUseOfCobblestone can provide a suggestion since he wrote the code.

**Comment by Cyprex** [comment]
Cobby merged the linked PR, Krysonism wrote it.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Krysonism

**Comment by msgerbs** [comment]
Sorry, misread the commit log.

**Comment by Krysonism** [comment]
I think it makes sense that chems should react when transferred by default.

I don't remember how plasma reaction_obj works but if we can fix this issue there I think that would be the best solution.
