### ISSUE TITLE
Flashbanged in a crate

### ISSUE THREAD

**Issue by Ghilker** [tgstation/tgstation#46110]
Issue reported from  Round ID: 116856 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

You can get flashed by a flashbang when you are in a crate (don't know if is the same if you are into a cabinet)

Reporting client version: 512.1478

**Comment by PKPenguin321** [comment]
I'm pretty sure this isn't a bug, and is in fact intended as a way to get people out of lockers/crates without stepping into their melee range. Make a forum thread

**Comment by Ghilker** [comment]
but you dont get out of locker/crates when you get flashbanged, you just get the white screen and the noise

**Comment by PKPenguin321** [comment]
Yeah, it disables you so they can rush in while you're blind and deaf
