### ISSUE TITLE
chemist goggles

### ISSUE THREAD

**Issue by kingcet** [tgstation/tgstation#46120]
Issue reported from  Round ID: 116928 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471

i was gonna smoke a cigar i found so i went and got chemist goggle to see if the cigar had chems in it the goggles said nothing about the cigar and i went to smoke it and i exploded
im pretty sure you should be able to see the chems in a cigar or cigarette if you have the chemist goggles on

**Comment by kriskog** [comment]
Not a bug. They also cant see whats in a pill or a patch, which is much closer to their intentional use. Take it to the forums.
