### ISSUE TITLE
Automute bug 

### ISSUE THREAD

**Issue by KaNoSki** [tgstation/tgstation#46135]
I just got automute for spamming while I was muted by changeling mute sting.

Issue reported from  Round ID: 117029 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1472

I dont know if i sould add anything else here

![yea](https://user-images.githubusercontent.com/54511421/63654874-d8e2e300-c780-11e9-86e3-55b039c800df.png)

**Comment by KaNoSki** [comment]
also i should add that admin told me to report it

**Comment by nemvar** [comment]
Report it to github is the standard response of admins if you come to them with a code problem, hell, even if you have a design problem.

One could argue that you, as the player, aren't actually aware if you can talk before you try to do it. Therefore, the intent of trying to speak is actually the thing that matters in determining spam or not.

I, for one, don't see much of an issue with placing the spam filter at the beginning of the input chain before it gets determined if the player is capable of talking or not.

Will leave this open as it could be considered odd behaviour.

**Comment by SpaceManiac** [comment]
I was also hit on a downstream by `can_speak` performing the spam check, not sure about the design choice to make it have side-effects up to OOC punishment

**Comment by optimumtact** [comment]
@SpaceManiac what do you mean by ooc punishment? It mutes you from IC.

It is very hard to manually hit this limit. I do not consider it a bug that you are muted if you're spamming manual chat this fast

**Comment by SpaceManiac** [comment]
I meant "OOC punishment" as in the punishment itself is not IC. It doesn't actually really matter. Moreso `can_speak`'s name implies it is a passive check when in fact it is not.

The OP wasn't very specific so it's no problem closing this unless they can explain how this is actually a bug.
