### ISSUE TITLE
Weirdly anomalous shuttle atmos.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#46148]
This occurred in 117080 on Sybil.

For some unusual reason the shuttles were producing lavaland atmosphere and kept it set to that atmosphere.

I have no idea what happened but several people died and I didn't touch anything.

**Comment by nemvar** [comment]
Which shuttle? What base turfs?

**Comment by necromanceranne** [comment]
It was the emergency shuttle and pods. For the pods at least it was the standard shuttle plastitanium turf.

**Comment by kriskog** [comment]
Did I though? They claim it was normal shuttle floor. The OP is the one who made me aware of the problem with the other turfs in the first place, I'd assume she'd tell us if this was adminbuse.

**Comment by necromanceranne** [comment]
I didn't touch turfs this round nor did apparently the other admin who was online at the time, so I would assume this must have been happening from roundstart. I have no idea how it occurred, unless plap was straight up lying.

The following round nothing was anomalous with shuttle atmosphere, nor were the pods affected either. Straight up no clue what was up.

**Comment by necromanceranne** [comment]
Not seen this in literally a year so closing. Really weird though.
