### ISSUE TITLE
Map lorder is borked

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/tgstation#46141]
Making this an issue so hopefully someone will fix it
## Round ID: 
None, tested a bunch on private server.

## Testmerges:
None

## Reproduction:
Make a big map and try to load it, it fails.  Seems to work on small maps fine still.
I got a few different runtimes whenever I would load different maps.  Here's one from a recent 120x120 map that I tried loading.

```
Undefined model key in DMM: a
 - proc name:  load impl (/datum/parsed_map/proc/_load_impl)
 -   source file: reader.dm,185
 -   usr: Cole Beach (/mob/dead/observer)
 -   src: /datum/parsed_map (/datum/parsed_map)
 -   usr.loc: the plating (154,145,2) (/turf/open/floor/plating)
 -   call stack:
 - /datum/parsed_map (/datum/parsed_map):  load impl(94, 85, 2, 1, 0, -1e+031, 1e+031, -1e+031, 1e+031, 1)
 - /datum/parsed_map (/datum/parsed_map): load(94, 85, 2, 1, 0, null, null, null, null, 1)
 - MEME.dmm (/datum/map_template): load(the wall (94,85,2) (/turf/closed/wall), 1)
 - NikNakflak (/client): Map template - Place()
 - 

```

**Comment by Niknakflak** [comment]
https://file.house/Nkq8.dmm

map

**Comment by Cyprex** [comment]
@kevinz since he last worked on mapping I believe

**Comment by AnturK** [comment]
Does it work in tgm format ?

**Comment by Niknakflak** [comment]
@AnturK 
1. make any map
2. load it in, these maps are dmms.  40x40 maps, 200x200 maps, but small maps seem to work fine.
3. "failed to place map"

**Comment by spookydonut** [comment]
Are you running out of memory?
