### ISSUE TITLE
Setting off a BoH in a bluespace body bag will perma delete the nuke disk

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/tgstation#46159]
Issue reported from  Round ID: 117124 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1472

1. have nuke disk
2. be in bluespace body bag
3. have boh and put boh in boh

**Comment by Time-Green** [comment]
I'm pretty sure it just ends up in the nth dimension

**Comment by Tharcoonvagh** [comment]
feature, close issue
