### ISSUE TITLE
Clicking Recalibrate in Damaged Mech Does Nothing

### ISSUE THREAD

**Issue by Rockinrhino** [tgstation/tgstation#46154]
Issue reported from  Round ID: 117112 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1478

**Comment by nemvar** [comment]
My fault probably.

**Comment by nemvar** [comment]
Do you get a message or nothing? You have to stand still if you want it to work.
