### ISSUE TITLE
SPAGHETTI IS STRAIGHT FUCKED

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#46181]
## Round ID: 117179

Ok so I had like a shit ton of spaghetti noodles, I toss them into two seperate microwave ovens. This is like enough spaghetti to completely fill your bag, its a lot. Anyways later I notice two amalgams were formed: boiled spaghetti spaghetti. These cannot be crafted into different types of spaghetti like normal boiled spaghetti can. So like I try microwaving one again and that just breaks it. Then I EAT the other, just a few bites, and like 5 minutes later FUCKING SPAGHETTI COMES OUT OF ME?????

![image](https://user-images.githubusercontent.com/37246588/63794115-3b49f980-c8cf-11e9-869a-d5a67c5cad74.png)
so like now theres basically 6 fucking random ass spaghetti that came out of nowhere im not sure what is going on i might just be the God of noodles will keep you posted

**Comment by nemvar** [comment]
Sounds like admin fuckery? Doesn't sound like this is the right place for this. https://www.reddit.com/r/ss13 reddit is over here.

**Comment by nemvar** [comment]
In that case make a proper issue report that isn't an essay.
