### ISSUE TITLE
Nukie shuttle's Comms are broke

### ISSUE THREAD

**Issue by ariever** [tgstation/tgstation#46186]
## Reproduction:

1) Have it be the nukie round type (or dynamic with nukies in it)
2) Try to use syndicate comms
3) Cry, because they don't work :c

Morto you better be drinking some water for this

**Comment by JohnFulpWillard** [comment]
Is this still a problem?

**Comment by ariever** [comment]
Bro this bug was a whole 3 laptops ago for me, i dont even have byond
installed anymore

**Comment by SethLafuente** [comment]
This is no longer an issue I don't know how it wasent noticed more players would have complained about this major issue during Nukies
