### ISSUE TITLE
Cultist status HUD indicator not showing.

### ISSUE THREAD

**Issue by Jaltsi** [tgstation/tgstation#46208]
Issue reported from  Round ID: 117255 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1475

I got cloned as a cultist and my cult HUD marker stopped showing for other players and myself. I was still a cultist with objectives and saw other cultist HUD markers.

**Comment by Names-Are-Hard** [comment]
Looks like the same as #46427.
