### ISSUE TITLE
Wizards can use the rod form spell to escape the wizard den

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#46201]
... and to break into other areas in the centcomm z-level, such as the abductor pods, the nuke op ship/syndicate base, and even centcomm itself (including the places in centcomm where the spare ERT and deathsquad gear is (are?) kept).

**Comment by Learner10** [comment]
This just in, Wizard forgoes attacking useless station and targets Centcomm! In other news, aliens found robusted in tiny ship.

**Comment by tralezab** [comment]
should probably test this, i thought there was a check

**Comment by redmoogle** [comment]
""Feature""

**Comment by GravitronBlue** [comment]
I thought I tried this already since it at least gets you through the unbreakable walls, but not past the hyperspace that surrounds the den. Any idea if there's more to it than just turning into a rod?

**Comment by bgobandit** [comment]
just make it so you can't go rod in the wizard den and/or z-level
