### ISSUE TITLE
Chameleon Jumpsuits are literally just broken

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#46206]
Chameleon jumpsuits and any child of the chameleon jumpsuit no longer seems to use any worn icon, and spawns missing it's icons entirely. If changed via the action button, they will change the in-hand icon but still have no worn icon.

**Comment by kriskog** [comment]
Probably #46166

**Comment by cacogen** [comment]
i've noticed this with the captain's jumpsuit but not the captain's jumpskirt as well

**Comment by actioninja** [comment]
fixed by #46231
