### ISSUE TITLE
I became a headrev as a cyborg on a dynamic round

### ISSUE THREAD

**Issue by ReplicantTerry** [tgstation/tgstation#46218]
I was playing as a cyborg (I had been borged, I didn't start the round as a cyborg) and I suddenly got a blue R on my mob, and when I flashed people, they became revs. However, I had no text informing me "you are the head revolutionary" or anything similar. It really confused the crew!
Issue reported from  Round ID: 117284 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1477

**Comment by PKPenguin321** [comment]
I'd really like this to be a feature

**Comment by ReplicantTerry** [comment]
It was good fun. No one suspects a revborg.

**Comment by ATH1909** [comment]
Yeah, that sounds like a fun event that an admin could do in the future.

Did you count as being "dead" for the purposes of the roundend report screen and whether or not the revolution succeeded or failed?

**Comment by kriskog** [comment]
Dynamic picks its midround headrevs at roundstart. Should probably have some sanity check when the rule executes, for dead/borged/offstation headrevs.

**Comment by ReplicantTerry** [comment]
I counted as alive, ATH

**Comment by ATH1909** [comment]
> I counted as alive, ATH

Interesting. I wonder if you still would have counted as being alive if you had died and then been emergency reboot board-ed.

**Comment by TheChosenEvilOne** [comment]
The mode does not consider cyborgs as living revheads as it has a check if the revhead is a human or a monkey.
