### ISSUE TITLE
AIs can't use sec record consoles

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#46228]
> be AI
 > see catgirl harming humans
 > try to set her to arrest
 > "You are too fay away!"
 > get subverted and kill those pesky humans

Same with borgs, except that you need to be on a tile next to the console to use it

**Comment by Shirbu** [comment]
this one is super irritating

**Comment by ATH1909** [comment]
I thought that you could set them to arrest, but couldn't add a REASON for their arrest.

What happens if you core is directly adjacent to a sec console?

**Comment by Tharcoonvagh** [comment]
ATHATH then you can use it, probably just like with borgs
