### ISSUE TITLE
Ctrl+shift+clicking to jump inside an abandoned crate using the skittish perk causes it to explode

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#46239]
Issue reported from  Round ID: 117361 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1471

Maybe this is intentional? But I would've thought the lock would've stopped it first?

**Comment by PKPenguin321** [comment]
that's fuckign hilarious

**Comment by OverlyGeneric** [comment]
keep it in, it's uncommon enough to have the skittish perk and there's a limited supply of locked crates.

cargonian crate suicide bombers. absolutely terrifying.

**Comment by davethwave** [comment]
Also explodes if you scan it with the cargo scanner thing that tells you how expensive something is.

**Comment by mrhugo13** [comment]
Y'know what?


Let's keep this.

**Comment by nemvar** [comment]
filthy gamers deserve it for picking a combat quirk

**Comment by cacogen** [comment]
@qustinnus still an issue! very bad!

**Comment by Qustinnus** [comment]
I'll look into this

**Comment by actioninja** [comment]
featore

**Comment by Sealed101** [comment]
resolved in #56048 - ctrl-shift-click was removed and abandoned crates _should_ no longer accept skittish attempts
