### ISSUE TITLE
Changelings that absorb other lings get reset after re adapting 

### ISSUE THREAD

**Issue by Naloacisamazing** [tgstation/tgstation#46234]
Issue reported from  Round ID: 117344 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1475

If a ling absorbs other lings then readapts to get rid of one ability they will lose all extra genetic points they had and all the extra chemicals they got. They do keep the extra absorbed DNA that other lings extracted though.

**Comment by Mooshimi** [comment]
more detailed problem report made, so I'm closing this one
