### ISSUE TITLE
Replacing Ractive with a React-based renderer in TGUI

### ISSUE THREAD

**Issue by stylemistake** [tgstation/tgstation#46246]
> This is not a bug, but instead an "epic", for dumping my current thoughts and ideas on improving TGUI

So, it seems that everyone agrees, that nanoui was better than tgui. Here's a few reasons:

- Ractive performance is shit. [We can no longer render a window with 12+ scrubbers without BYOND crashing or window freezing for 5+ seconds.](https://cdn.discordapp.com/attachments/484170915253321734/597749964126552074/unknown.png)
- Templating syntax is worse in many cases, requires a lot of knowledge to use.
- Two-way data binding is a pain in the ass.

Now why I am not so hot about moving back to doT:

- While this template engine is capable of spitting out html strings with crazy fast speeds, assigning that string to innerHtml is quite slow in IE8. This limits the amount of updates we can have on such UI.
- This really feels like you are writing in a shitty decade-old template language, mixing an already ugly html with out-of-place doT control structures.

Why React is good:

- Industry standard, lots of people who work in the web know React.
- It does surgical DOM updates, which is extremely fast.
- You write everything in javascript and able to leverage IDE features, like autocompletion.
- Many implementations to choose from, for example Preact or Inferno, which are mostly compatible.

[Here's a page with benchmark results of different javascript frameworks.](https://krausest.github.io/js-framework-benchmark/current.html)

What is left to do, is to actually do it, and perhaps run a benchmark between React and (current) Ractive implementations of e.g. a ChemMaster 3000 window with 20 chemicals in a beaker. I really don't know how much better this will be, but I expect slightly faster load times and at least 2x faster UI updates.

More info soon.

**Comment by PKPenguin321** [comment]
Godspeed my dude

**Comment by kriskog** [comment]
If it doesn't slow the UI down over time, it's a big improvement. It's probably more of a bug/oversight, but if you dont know what I mean go open the cargo window. Now swap categories 20 times, and notice the UI getting slower and slower while your FPS also drops. Close the UI to mostly go back to normal.


> 
> 
> Godspeed my dude

**Comment by actioninja** [comment]
An important consideration is we don't need to target IE8, just support it. Poor performance on IE8 isn't a dealbreaker as long as it's still functional and not cripplingly poor performance.

**Comment by nicbn** [comment]
I'd rather replace tgui with in-game hud windows, would look way nicer and would be way faster, though more of a pain to program.

**Comment by stylemistake** [comment]
So, yesterday I researched what exact React implementation would be a good candidate for tgui.

- **React** itself is out of the question, because react-dom stopped supporting IE8 since version 15, they completely rewrote it from sceatch in 16, and knowing how much magic happens there, I would not even try running it.
- **Preact** - meh, no IE8 support, but less code == less surface area for compatibility errors to pop up. Supports hooks.
- **Inferno** - I know this library, and it's the primary candidate for using in tgui, because it is ridiculously simple at its core, and has a massive performance benefit of knowing what type of element it will render at *compile time* (similarly to Svelte). No direct IE8 support, but I'm pretty sure it will work. No hooks API, but that can be easily ported. Probably needs to be forked.
- **NervJS** is the only one claiming to fully support IE8 (yet some of the test suits fail!!), but it's written by chinese and there were reports in hackernews that it's pretty buggy. I don't trust this library, but still, it's well structured and has a lot of portable bits of source code. I had some good time reading it.

> I'd rather replace tgui with in-game hud windows, would look way nicer and would be way faster

@nicbn Only problem with that, is that it's nigh impossible to do.

**Comment by Cyprex** [comment]
It's worth noting that MSO was also working on dmtemplate at some point: https://github.com/MrStonedOne/dmtemplate

**Comment by bgobandit** [comment]
is there a reason we have to support ie8

**Comment by Cyprex** [comment]
Personally I use the game on Linux via wine, which only supports IE8.

**Comment by PKPenguin321** [comment]
i think it's because byond uses IE as a dependency or something

**Comment by optimumtact** [comment]
it's because of wine support, otherwise we could mandate at least ie11

**Comment by AWalton** [comment]
Unsure if BYOND [can be set](http://www.byond.com/forum/post/2178058) to use Microsoft Edge but [WINE supports it](https://appdb.winehq.org/objectManager.php?sClass=version&iId=38188) in it's latest incarnation built on top of Chromium.

**Comment by optimumtact** [comment]
I am not sure if that would work with the built in IE renderer views tbh.

We do mandate the latest possible UA via the html meta tags, but I don't know the specific semantics around the embedded webviews that win32 provides

**Comment by stylemistake** [comment]
Today I made some progress testing Inferno with the in-game IE, and so far everything works great! From simple functional components, fragments, to class-based lifecycle hooks and browser events, works quickly with no issues.

Only thing it is missing is the new Hooks API, and I couldn't code it overnight, because Inferno lacks any kind of extensibility to support it on a fundamental level. There is no other option, but to check out Inferno into tgstation, keep it near TGUI code and implement lifecycle hooks there. It's also quite annoying that it's written in TypeScript, and it is written in such a way that you can't use it as is, you have to use the TS compiler before importing the code.

Also, by looking at the vast amount of interfaces, I have just realised how much work it will take to rewrite them, even compared to the low-level tinkering with Inferno internals. I think I can realistically only make 1 or 2 interface rewrites in short term, and I just hope that development catches on.

I am slightly tempted to just ignore the new Hooks API and make a prototype interface with what we already got. Prioritize making a functional copy of an interface, and do performance testing, maybe refactor that code later. After all, what we've got is pretty damn good already.

**Comment by optimumtact** [comment]
![](https://file.house/KbGV.jpg)

**Comment by stylemistake** [comment]
> We do mandate the latest possible UA via the html meta tags

As I found out, this tag cannot really request an IE8 user agent, you still get an IE11 pretending to be IE8.

> Personally I use the game on Linux via wine, which only supports IE8.

@Cyprex I can't install anything it needs through winetricks. Which is very sad. It seems to be the only way to test IE8 compatibility.

**Comment by Cyprex** [comment]
The byond installer on lutris works well, see this script: https://lutris.net/games/install/10191/view
There are also IE 8 VMs available for free from Microsoft: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
Though I haven't been able to successfully run the game in these VMs with virtualbox(graphical glitches, I suspect it's GPU-related), YMMV

**Comment by stylemistake** [comment]
[Here is a working demo of an Air Alarm UI, completely rewritten with Inferno.](https://cdn.discordapp.com/attachments/326831214667235328/626653924975443968/2019-09-26_08-37-48.mp4)

My initial expectation was to have about 3-4x speed improvement, but the actual result is way faster, almost instantaneous. This is simply mindblowing, and this makes it possible to write a lot more complex UIs than before.

Now, there is still a lot of work remaining to do, because this is just one air alarm screen, and we have about 50 various interfaces to massively refactor in the same way.

<details>
<summary>Skippable rumble about technical details</summary>
<h3>Build pipeline changes</h3>

- Getting rid of **Gulp** in favor of **Webpack**. While there is no real reason to hate Gulp (I do hate it though), I decided to move to Webpack because it's a very robust tool with a very defined internal pipeline and lots of features out of the box.

  - One of its features is **code splitting**. Right now web client has to load and parse about 700KB of javascript, which takes quite a long time on IE. With code splitting, we can extract common code into a separate chunk (e.g. "vendor", which will contain external libraries), and further split the remaining code into individual interfaces which we have to render. Then, from the game code's perspective, we just have to specify which chunks we have to load (e.g. `/bundles/vendor.chunk.js` and `/bundles/airalarm.chunk.js`), and that's it!

- Getting rid of **Stylus** in favor of **SCSS**. SCSS is backwards compatible with plain CSS, and has a lot more intuitive syntax for normal folks. The plan is to use the minimum amount of features SCSS gives; write simple, flat CSS without deeply nested selectors, and use [BEM methodology](https://en.bem.info/methodology/quick-start/),

- Finally, we are using **Yarn** as an alternative to **npm**. There is only one real reason to use it - workspaces. Workspaces are necessary for having multiple packages in one project. Think of this project structure as of a normal Java project (yes, javascript is suddenly capable of what Java could do decades ago). This is a lot better than path aliasing, because you can manage external dependencies on package level, instead of managing them globally through a single `package.json` file.

  - I also plan on putting Inferno source code alongside tgui because I will be later adding support for new [Hooks API](https://reactjs.org/docs/hooks-reference.html), and with workspaces it will be well separated from the main tgui source code. This will be temporary though, because once Hooks API is stable, it will be merged upstream, and I will be able to safely delete the local copy of it.

- New "template" language (JSX) is pretty nice, mainly because it's an extension of javascript syntax. This HTML syntax is just a way of declaring Virtual DOM, and you can treat it as a normal javascript object. Components are also just pure functions which return Virtual DOM. No more ugly ractive control flow syntax!

  - [JSX example 1](https://media.discordapp.net/attachments/326831214667235328/626644753294950419/unknown.png)
  - [JSX example 2](https://media.discordapp.net/attachments/326831214667235328/626645617405329409/unknown.png) - notice how you can call `.map()` on a collection, and return Virtual DOM elements inside of it.
  - [JSX example 3](https://media.discordapp.net/attachments/326831214667235328/626645959455277066/unknown.png) - inline conditions
  - [JSX example 4](https://media.discordapp.net/attachments/326831214667235328/626646236354707466/unknown.png) - imperative conditions
</details>

---

Code for your judgement is located here: https://github.com/stylemistake/tgstation/tree/tgui-next/tgui-next

**Comment by PKPenguin321** [comment]
HOly shit you're a god, I love you

**Comment by stylemistake** [comment]
I have finished creating a development server for tgui. It's a lot more robust than `gulp watch` (because it only uses native Node APIs, and no hackery with bat files, so you can't break it in normal use), and it also remotely collects logs from the browser window, so you can see both server and browser logs in one console window. In short, VERY NEAT.

![image](https://user-images.githubusercontent.com/1516236/65734806-5d58b680-e0dd-11e9-95b7-d0de41cd43c7.png)

**Comment by stylemistake** [comment]
> if you dont know what I mean go open the cargo window. Now swap categories 20 times, and notice the UI getting slower and slower while your FPS also drops. Close the UI to mostly go back to normal.

I see now what you mean, this slowdown slowly starts to creep up. I'll try to figure out a solution this evening.

It seems as if CSS animations are the main cause, but could be something different. Inferno has a way to properly unmount the UI, forcing a GC call, perhaps that will fix the problem.
