### ISSUE TITLE
dynamic revs

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#46265]
dynamic
revs too
revheads die
other antags redtext

**Comment by Tharcoonvagh** [comment]
also borgs can be revheads

**Comment by Tlaltecuhtli** [comment]
117435 <- revhead borg round

**Comment by Tharcoonvagh** [comment]
borg started flashing people and noone thought that it was really a revhead
it was glorious

**Comment by adamkad1** [comment]
it would be cool if revs didnt end round like wizard does not now. I dunno, just make the game display a big text when one side wins and be done with that

**Comment by ExcessiveUseOfCobblestone** [comment]
revs doesn't work with dynamic since the gamemode relies on the round to end once the revheads die.

**Comment by Tharcoonvagh** [comment]
Guess I'll close this
