### ISSUE TITLE
Power cells can be endlessly removed from light fixtures

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#46268]
Remove the lightbulb from a light fixture, use a screwdriver on the light fixture repeatedly. You will close and open the fixture repeatedly and each time you do so a new power cell will end up on the floor

Issue reported from  Round ID: 117452 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

**Comment by ATH1909** [comment]
What happens if the power cell is your wizard phylactery? Can you just make an absolute shitton of power cell phylacteries and hide them throughout the station?

**Comment by ATH1909** [comment]
It looks like the cells produced are miniature ones, regardless of the quality of the cell that you put into the light bulb fixture.

Also, this only worked when I tried it on a lightbulb fixture, not a light TUBE one.
