### ISSUE TITLE
Mount and Blade: Butterlord

### ISSUE THREAD

**Issue by Difrit** [tgstation/tgstation#46278]
## Testmerges:

h

## Reproduction:

You can make infinite butter on a stick, as long as you cradle your butter in-hand while putting rods into it.

1. Pick up your butter.
2. Pick up your rods.
3. Infinitely jam the rods into your in-hand butter because it never disappears. Flood the station with butter. Create the kingdom of Swadia. Feast. Trazelab you bumbling buffoon what have you done

**Comment by Difrit** [comment]
[img]https://puu.sh/EbLEB/6356663a0e.png[/img]

**Comment by MACIEKBAKI** [comment]
Feature, not a bug.

**Comment by nemvar** [comment]
![newspic-67710](https://user-images.githubusercontent.com/47324920/64078352-f1e81880-ccd9-11e9-9c44-f593b29aaaf0.png)
