### ISSUE TITLE
Spray Bottles (and similar items) ignore any protections you have and inject chems

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#46275]
Not sure if this is a bug or intentional, but there is a real possibility to simply inject various chems into people with a spray bottle regardless of whatever protective measures you attempt to take and whether you have internals on or not. This bypasses even hardsuits sealed up with internals on.

We have a large variety of applicators that don't do this, so I'm pretty sure for the sake of consistency this seems to stand out rather strongly, especially given spray bottles are widely available in the service lathe.

This includes stuff like poisons (if it sprays enough), holy water, frost oil, mutation toxin (this is a hard stun by the way), cobbychems that hurties your organs, honey, nutrients, mint toxin, gluttony's blessing, baccus (it can set you on fire since it's touch applied too so look out for CLF3), advanced slime mutation toxin, frost oil (hardsuits are especially at risk for this).

Loads of nasty things honestly and this probably includes anything that is a subclass of sprayers.

**Comment by Krysonism** [comment]
Internals provides no protection from sprays by design.

Hardsuits should protect against the transfer of reagents.

**Comment by ATH1909** [comment]
Wait, by "inject", do you mean the INJECT reagent application method? The kind that syringes use?

Because if so...

https://www.youtube.com/watch?v=KnPM7I49fj8

**Comment by ATH1909** [comment]
Are the chems entering peoples' systems when applied via a spray bottle?

**Comment by ATH1909** [comment]
Are you talking about gel bottles here, or more about stuff like space cleaner sprayers?

**Comment by necromanceranne** [comment]
They're entering peoples systems for anything that uses sprays. This includes space cleaner bottles.

**Comment by necromanceranne** [comment]
Also I just finally got to watch that video and yes, ATHATH that's literally what this is. I've attempted to use zombie powder in a backpack water cannon and it works. It works terrifyingly well. It is EXACTLY like the supersoakers full of neuro-stun. I'm fully convinced if I just loaded it up with fiziver and tirizene you'd have it'd be about as effective as a disabler given how quick that shit will put you on the ground. The only downside to the janitor's backpack water sprayer is that it has slowdown. I don't know if the botanical version has that however.

**Comment by ATH1909** [comment]
> Also I just finally got to watch that video and yes, ATHATH that's literally what this is. I've attempted to use zombie powder in a backpack water cannon and it works. It works terrifyingly well. It is EXACTLY like the supersoakers full of neuro-stun. I'm fully convinced if I just loaded it up with fiziver and tirizene you'd have it'd be about as effective as a disabler given how quick that shit will put you on the ground. The only downside to the janitor's backpack water sprayer is that it has slowdown. I don't know if the botanical version has that however.

First off, thanks for actually watching the video. It's nice to know that someone actually watches the stuff that I post.

Second off... [holy _shit._](https://www.youtube.com/watch?v=SwveuIRWxBo) This is, uh, wow.

Can you delete people with black powder and clf3 in a sprayer?

**Comment by necromanceranne** [comment]
I see no reason why it wouldn't assuming you got the clf3 to the right temperature to not set the black powder off. If you have concerns I suppose you could just fill a spray bottle with the clf3 and alternate.

**Comment by ATH1909** [comment]
> I see no reason why it wouldn't assuming you got the clf3 to the right temperature to not set the black powder off. If you have concerns I suppose you could just fill a spray bottle with the clf3 and alternate.

Maybe use meth instead?

**Comment by adamkad1** [comment]
arent hardsuits supposed to protect you? and soft suits could too, since they cover your skin and what not
