### ISSUE TITLE
Clown car bugs

### ISSUE THREAD

**Issue by harmonyn** [tgstation/tgstation#46280]
## Reproduction: Be clown tator, get clown car, emag clown car, notice the following bugs:

1. When activating siege mode (the cannon) you are supposed to be unable to move, or at least the canmove variable is made False. But you can still move.
2. If you crash the clown car while it is in siege mode, your cursor is still the crosshairs. The only way I can find to get rid of it is to get back into the clown car.

**Comment by Sealed101** [comment]
both parts fixed as far back as https://github.com/tgstation/tgstation/pull/57628 probably, though the latter one is tricky to perform as siege mode does work as intended now and throwing the car in cannon mode doesn't leave the cursor on the cannon setting
