### ISSUE TITLE
Skeletons aren't healed by milk because they don't process reagents at all

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#46284]
See title
Milk has special code specifically for healing skeletons and that shit don't work

**Comment by XDTM** [comment]
I accounted for that in the PR by making species' handle_reagent work independently from the liver.
It worked when i first added it, so something broke it

**Comment by PepperPrepper** [comment]
@ATH1909 You fixed this one right?

**Comment by PepperPrepper** [comment]
@PKPenguin321 Fixed by #47084

**Comment by PKPenguin321** [comment]
Really? That PR seems to have nothing to do with skeletons

**Comment by PepperPrepper** [comment]
@PKPenguin321 ugh my I hit ctrl + v not ctrl + c because I was in the dark. My bad

fixed by #47375

**Comment by PKPenguin321** [comment]
Ah. Thanks
