### ISSUE TITLE
The Ents Are Going To War

### ISSUE THREAD

**Issue by Difrit** [tgstation/tgstation#46292]
## Round ID:

117612

## Testmerges:

h

## Reproduction:

If you get hit by a baton, when you fall over for the delayed hard stun you can pick a plantpot up which cancels the hard stun. If it hits you a second time, you cannot do this due to stamina damage. This means if you get hit you can pick up the plantpot to cancel the delayed hard stun, drop it again and continue fighting.

1. Be the plant man.
2. Get batoned by security girls with cat ears.
3. Pick up your plant pot, pick your favourite Treebeard quote, and smear the officer over the walls while they figure out what just happened.

**Comment by ATH1909** [comment]
... what the FUCK?

**Comment by bgobandit** [comment]
this will kill tactical plants

**Comment by kriskog** [comment]
It was changed from hard stun to knockdown a few days ago. You should be able to do this without picking up the plant too.

/obj/item/melee/baton/proc/apply_stun_effect_end(mob/living/target)
	var/trait_check = HAS_TRAIT(target, TRAIT_STUNRESISTANCE) //var since we check it in out to_chat as well as determine stun duration
	if(trait_check)
		target.Knockdown(stunforce * 0.1)
	else
		target.Knockdown(stunforce)
	if(!target.IsKnockdown())
		to_chat(target, "<span class='warning'>You muscles seize, making you collapse[trait_check ? ", but your body quickly recovers..." : "!"]</span>")
