### ISSUE TITLE
The Pet Park holodeck setting can be used to get infinite positive moodlets.

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#46291]
How to reproduce:

1. Go to holodeck
2. Load Pet Park
3. Pet all the animals, getting a separate positive moodie for each one
4. Load something else
5. Load Pet Park 
6. Repeat, you get new positive moodlets for each respawned pet

**Comment by Qustinnus** [comment]
should've been fixed by https://github.com/tgstation/tgstation/pull/43381
