### ISSUE TITLE
You cannot spawn condiments including ketchup

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#46304]
Try to buy, spawn, or otherwise create certain condiments; nothing results, not even an invisible sprite. Seems to only affect children of /obj/item/reagent_containers/food/condiment/pack.

Possibly caused by https://github.com/tgstation/tgstation/pull/46015.

**Comment by AnturK** [comment]
@cacogen

**Comment by cacogen** [comment]
@bgobandit which server? also sorry about this, i didn't touch packs, only bottles. should've made sure to test them too.
