### ISSUE TITLE
Explosions can destroy photos inside photo albums in your backpack.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#46309]
## Reproduction:
Carry a photo album with, in this case, 4 photos in it, get hit by an explosion, like a fireball. 
Look back at album, 2 photos out of 4 disappeared.
This screws up people's persistent photo albums a lot.

**Comment by nemvar** [comment]
This isn't a bug but it does sound pretty annoying.

**Comment by bgobandit** [comment]
I mean real life explosions can do this too

**Comment by Onule** [comment]
> 
> 
> This isn't a bug but it does sound pretty annoying.

How so? I never had any items get destroyed by one explosion that was inside my backpack, inside another container, and the fireball didn't hurt me that badly, just set me on fire and didn't knock me down.

**Comment by PKPenguin321** [comment]
Explosions do affect contents of items intentionally

**Comment by Mickyan** [comment]
I did some testing cause this is news to me and several explosions later none of the objects in my backpack lost any integrity so I dont know what everyone's going on about here

**Comment by PKPenguin321** [comment]
Really? It's possible that either I'm wrong and it changed, or it's broken and is applying inconsistently

**Comment by nemvar** [comment]
Contents explosion is definitly a thing that happens.

**Comment by Mickyan** [comment]
what are the steps to reproduce it cause being caught in explosions definitely isn't it

**Comment by nemvar** [comment]
in explosion.dm
```
		if(T == epicenter) // Ensures explosives detonating from bags trigger other explosives in that bag
			var/list/items = list()
			for(var/I in T)
				var/atom/A = I
				if (!A.prevent_content_explosion()) //The atom/contents_explosion() proc returns null if the contents ex_acting has been handled by the atom, and TRUE if it hasn't.
					items += A.GetAllContents()
			for(var/O in items)
				var/atom/A = O
				if(!QDELETED(A))
					A.ex_act(dist)
```
It only happens in the epicenter.

**Comment by nemvar** [comment]
Also see https://github.com/tgstation/tgstation/pull/31516/files

**Comment by nemvar** [comment]
Actually... this is a bug... kinda

https://github.com/tgstation/tgstation/pull/31516 doesn't mention anything about destroying all contents of the object. It was just supposed to blow up other explosives but its hackiness caused this.

**Comment by Mickyan** [comment]
I guess adding prevent_content_explosion() to albums would be harmless if a bit arbitrary but this whole thing is pretty dumb for how specific it is, doesn't really feel like a feature
