### ISSUE TITLE
Bolt of changed borgs still have a Robot Commands tab with Print Image

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#46316]
How to reproduce:

1) Be borgie
2) Get hit by bolt of change; I noticed this when turned into a human but probably applies to everything
3) You still have the Robot Commands tab with Print Image (everything else goes away). You can't use it because "insufficient toner" but it's there.

**Comment by nemvar** [comment]
Thanks for precise reproduction steps.

**Comment by PKPenguin321** [comment]
>You can't use it because "insufficient toner" but it's there.

That's not wrong
