### ISSUE TITLE
Cyborg Hypospray doesnt recharge a chemcial if you use all of that chemical

### ISSUE THREAD

**Issue by bluezorua** [tgstation/tgstation#46310]
## Reproduction: I use up all 30 units of a chemical in the hypospray and then it doesn't recharge if I use 25 out of the 30 and I still have 5 units, it recharges, but if I don't have 5 units remaining it doesn't. Or to put it simply, no more chemicals in hypo, no recharge in hypo.

##i would like to add that on the status page it says 2500/2500 chemicals

**Comment by ATH1909** [comment]
Does it recharge if you return to a borg charger?

**Comment by bluezorua** [comment]
Nope, not even charging

**Comment by ATH1909** [comment]
If you're a mediborg and inject a new chem into your empty hypospray with your syringe, does your hypospray start synthesizing that chem?

**Comment by bluezorua** [comment]
That's not how it works, the only way to get new chemicals is the expanded hypospray module and getting emmagged/illegal module

**Comment by ATH1909** [comment]
Well, I had heard of a bug that would let you dupe most kinds of chems by somehow getting them into a service borg's shaker, hence why I asked.

**Comment by Names-Are-Hard** [comment]
I just tried this and the chems seem to regenerate just fine.

**Comment by SuperNovaa41** [comment]
Yeah this is definitely not an issue anymore
