### ISSUE TITLE
AI cannot locate or track people

### ISSUE THREAD

**Issue by Archanial** [tgstation/tgstation#46327]
Issue reported from  Round ID: 117773 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471

I was unable to track anyone and the "track" button in sec console was inactive. After ahelping I was told it was reported some round before me and I was unable to track anyone for the rest of the round. Next round other AI said it could track people. Not sure if it's client version related but it was my first time experiencing this.

**Comment by nemvar** [comment]
feck
