### ISSUE TITLE
rhigoxane cools you down too much, deals burn damage

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#46336]
## Reproduction: 
1. be man in medbay
2. spray yourself at normal temp
3. get burn damage from too much cooldown

**Comment by nemvar** [comment]
The cooling does seem a tad high but if this chem gets combined with cryoxadone or something like it, it might just be worth it. Anyways this isn't the right place for this. https://tgstation13.org/phpBB/viewtopic.php?f=10&t=23712 the thread for cobby chems is over here or you could just make the PR yourself.
