### ISSUE TITLE
epic wishgranter moment

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#46348]
>Do the Wild West away mission.
>Get to the wishgranter.
>Wish to kill.
>Receive the hulk mutation (along with a few others).
>Also receive the shadowperson race.
>Realize that hulk does almost nothing for nonhumans, so all the hulk mutation really does for you (unless you turn yourself into a human somehow) is make your speech shout-y.
>this is so sad, wishgranter, play despacito

**Comment by nemvar** [comment]
proper solution is to remove the wishgranter

**Comment by Timonkeyn** [comment]
How does the wishgranter even work

**Comment by DingleFlop** [comment]
Introduces meme bugs repeatedly over the years for F.U.N.

**Comment by PepperPrepper** [comment]
@ATH1909 this should be closed as you fixed it. 

#47084
