### ISSUE TITLE
DNA console breaks after you spam the print adv. injector button

### ISSUE THREAD

**Issue by Trumpetplaya288** [tgstation/tgstation#46346]
## Reproduction:
Mash the print button and all of a sudden you can't open the console anymore
Apparently really common and admins cant do shit to fix it

**Comment by Time-Green** [comment]
Then don’t spam click the button

**Comment by Trumpetplaya288** [comment]
The new button lacks the same functionality that the regular print mutator/activator buttons do. When the adv. injector button doesn't gray out like the others, it implies that there isn't actually a cooldown and you can print as many as you like. Grr coders test your shit better.

**Comment by nemvar** [comment]
Coders don't need to test, that's what we have the players for.
