### ISSUE TITLE
Chameleon Kits contains a bag in a box AKA Exponential Bag Space

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#46345]
I wanted to bring it up since Google had PR'd a method for a crew available cham kit, since this has been an outstanding issue with the cham kit for a while that hasn't ever been brought up from what I could see.

**Essentially right now the chameleon bag inside of the chameleon kit can be accessed as any other bag.** The only thing is that the bag is actually inside of a box that can fit inside other bags. This means you can use this for considerably greater amounts of bag space so long as the bag never leaves the box.

**So what does this mean?** It means you can buy more kits/smuggler satchels for even further bag space by putting them into this bag in a box. This also means you can put this box into a storage implant for a bag in a box in a storage implant, completely negating the need for a bag in the first place by having all the functionality of one inside of a hidden compartment on your person, AND allows you to use very powerful weaponry normally only wearable on your back without sacrificing storage. That includes things like combat shotguns and elances.

**Comment by necromanceranne** [comment]
I'm sure you want some evidence of how this might be practical.

![unknown](https://user-images.githubusercontent.com/40847847/64305903-43432100-cfd4-11e9-9588-b7498be39445.png)

I had most of the armory in my bag too.

**Comment by ATH1909** [comment]
wew lad

nice
