### ISSUE TITLE
Novaflowers in a plant bag cannot be placed inside of an all-in-one grinder

### ISSUE THREAD

**Issue by felixtiger** [tgstation/tgstation#46356]
Issue reported from  Round ID: 117902 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1475

**Comment by ExcessiveUseOfCobblestone** [comment]
in b4 obj/item/grown vs obj/item/reagent_containers/food

**Comment by carlarctg** [comment]
happens with every bag being dumped into a grinder, does the message but doesnt dump items in
