### ISSUE TITLE
Winter theme warp crystal broken.

### ISSUE THREAD

**Issue by JusticeGoat** [tgstation/tgstation#46354]
Just use it and the temp goes to -90 c and thins the air. There is no reason for it to get that cold, below freezing is one thing but this is not epic. I suggest making it like -5 or something more reasonable.

**Comment by nemvar** [comment]
Not so much broken as unbalanced if I got this right? Adjust it yourself or find someone who does it for you. This is not the correct place for feature or balance suggestions.
I suggest this place https://tgstation13.org/phpBB/viewforum.php?f=10 for that kind of stuff.
