### ISSUE TITLE
Engiborg can't place r-glass when building an AI core

### ISSUE THREAD

**Issue by ReplicantTerry** [tgstation/tgstation#46368]
This may be a feature, but if it is, there isn't a message or anything indicating that your action failed.

To reproduce: Be engiborg, try to place r-glass on an incomplete AI core, fail miserably.

Issue reported from  Round ID: 117959 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1477

**Comment by ReplicantTerry** [comment]
edited for clarity

**Comment by Detective-Google** [comment]
just tested, can start the placing animation but no glass is inserted on finish
