### ISSUE TITLE
non-emagged recyclers kill borgs

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#46363]
## Reproduction: 
A non-emagged recycler kills borgs, the shell seems intact but you I got immediately ghosted out. I suspect it recycles the MMI inside the borg.

**Comment by nemvar** [comment]
Surprisingly enough, not a bug.

Recycler protection only extends to humans. Silicons aren't human, so they get murdered regardless of setting.

**Comment by nemvar** [comment]
You can even safely reenter your body after getting recycled.
