### ISSUE TITLE
Crafting Crab Rangoons causes item to load without sprite

### ISSUE THREAD

**Issue by somestupidfuck** [tgstation/tgstation#46360]
Problem Description: crafting crab rangoons creates an item lacking a sprite. Subsequent items (crab rangoon toast) will load correct sprite.

What did you expect to happen: I expected not to be haunted by the astral embodiment of crab rangoons and instead have delicious treats for the server.

What happened instead: instead of crafting a visible item I crafted the philosophical embodiment of said rangoons.

Why is this bad/What are the consequences: sprites not loading not good

Steps to reproduce the problem: craft delicious crab rangoon. 

Server: Which server were you playing on? Sybil-1 [Lowpop/US-West]

Revision: What revision was the server running? Server tools version: /tg/station 13 Server v3.2.6.2

![crab](https://user-images.githubusercontent.com/54972975/64402740-897f9b00-d03b-11e9-9e5d-42e171ef97b4.png)
![crab2](https://user-images.githubusercontent.com/54972975/64402741-897f9b00-d03b-11e9-8fad-ff474eb16ca9.png)

**Comment by ATH1909** [comment]
> What did you expect to happen: I expected not to be haunted by the astral embodiment of crab rangoons and instead have delicious treats for the server.

Ah, SS13 bugs, never change.
