### ISSUE TITLE
The Depressed Houdini (Straight Jackets can't be escaped from)

### ISSUE THREAD

**Issue by KomradeSpectre** [tgstation/tgstation#46379]
Issue reported from  Round ID: 117990 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1477

How to reproduce:
>Straightjacket someone.
>Watch as they are filled with the hope of escaping the straightjacket after a 5 minute long do-after.
>Watch as nothing happens when that do-after finishes.

**Comment by actioninja** [comment]
nice

**Comment by nemvar** [comment]
Handcuffs code is aids.
