### ISSUE TITLE
Ripely Doesn't Properly Load Ore

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#46377]
## Round ID: 
N/A

## Testmerges: 
N/A

## Reproduction:
Spawn in a RIPLEY and equip it with a mining drill, hydraulic clamp, and load up an ore box into it; go mine an asteroid/basalt or mining wall turf.

Take note that after you drill the turf or mining the basalt turf, the ore is just on the ground and is not picked up and put in the ore box. Likewise, walking over TOP of the ore does not pick it up either--it is only picked up if you move 1 tile in front of it.

What I expected to happen: ore to be picked up when I move directly over top of it (in a 3 tile line) AND before I approach it; likewise, I expect when I drill a turf that it will instantly place the ore in my mech's internal ore box.

**Comment by zxaber** [comment]
To be clear, this was a Ripley MK-I?

Just recently I went mining with the Firefighter (which is a child object of the Ripley) and it worked fine. I'll see if I can reproduce the issue.

**Comment by nemvar** [comment]
Worked fine for me.

Some of your expectations do not match what our features currently allow. I suggest adding them yourself if you want them.

**Comment by Fox-McCloud** [comment]
I'd implore you to look at this--and I assure you that the code is most up to date.

Try mining the turf in *front* of you (not the one you're standing on), and you'll see what I mean.

The 3 turfs in front of the mech will be mined (properly), but they will not be loaded into the ore box; if you move on top of the ore, it'll only collect the ore that is immediately at your location.

I believe this has been broken since: https://github.com/tgstation/tgstation/pull/27502

The logic was changed a bit, and as the PR description implies, it was meant to retain previous behavior in addition to picking up ore from the tile you're on.

**Comment by Fox-McCloud** [comment]
@nemvar
