### ISSUE TITLE
Incinerator burn chamber on Donut cannot be entered from the door.

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#46372]
Issue reported from  Round ID: 117967 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1479

There's a goddamn computer in the way.

How did this slip through the cracks?

![donutwhy](https://user-images.githubusercontent.com/23252965/64458498-588a7f00-d0aa-11e9-88c2-41762c7a768c.PNG)

**Comment by kriskog** [comment]
Um.. Yeah, woops.

**Comment by kriskog** [comment]
>
>How did this slip through the cracks?

The real question is, how did noone notice for 12 days.
