### ISSUE TITLE
you can put smuggler satchels in evidence bags WHICH ARE TINY ITEMS

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#46407]
how could you fuck up this hard

**Comment by nemvar** [comment]
Evidence bags take on the weight class of whatever you put into them.

The real fuck up here is that smugglers satchels can fit items of their own size.

**Comment by nemvar** [comment]
![dab](https://user-images.githubusercontent.com/47324920/64493290-93dda700-d27e-11e9-9658-dcbbb396b9e4.PNG)

The problem is that you can put this into another smugglers satchel.

**Comment by kriskog** [comment]
You are also able to put something into an evidence bag inside a box. So theres that.

**Comment by Tharcoonvagh** [comment]
Right

**Comment by kriskog** [comment]
#39452 touches on something related.

**Comment by Learner10** [comment]
Get nuke disk, stick in smuggler's satchel, stick in evidence bag, stick in box, stick in another smuggler's satchel, then stick in toilet or under a tile. Bonus points if you throw in bonus garbage in everything at all steps to slow them down.

**Comment by Tharcoonvagh** [comment]
I think it's fixed
