### ISSUE TITLE
Virus won't transmit via blood.

### ISSUE THREAD

**Issue by Bright0** [tgstation/tgstation#46408]
Issue reported from  Round ID: 118127 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

Made a 6 symptom beneficial virus with a resistance of 2, stealth of -3, stage speed of 9, and transmittability of 11. Airborne, so I gave it to my test monkies.

![image](https://user-images.githubusercontent.com/55061890/64492879-52290e00-d236-11e9-91a6-71bffcfb622d.png)

Made another 6 symptom virus, harmful this time, with the stats that theoretically should overtake the beneficial one. 14 resistance, -2 stealth, 9 stage speed, 5 transmittability.

![image](https://user-images.githubusercontent.com/55061890/64492899-869cca00-d236-11e9-94e0-231db7c7a061.png)

Theoretically speaking based on what's on the wiki, a virus with a higher transmission than the resistance of the virus it is overtaking will successfully transfer. Putting infected blood into the monkies via syringe, splashing it on them directly, and spraying with a spray bottle (both as a blood spot on the floor and directly) does not transfer the virus. Up until recently I swear I've been able to splash the same exact virus onto people and it functioned as expected, so maybe a recent change to splash/spray transfers could've done this?

**Comment by tralezab** [comment]
hey look a virus bug never seen that one before
