### ISSUE TITLE
Wizard robeless apprentice mindswap knocks caster out.

### ISSUE THREAD

**Issue by KetasDotepasto** [tgstation/tgstation#46409]
## Round ID:118136
[Round ID]:

## Reproduction:
The issue is that as a wizard's robeless apprentice, I attemted to mindswap into somebody, but the result was that after the spell, both me, now in my victim's body, and the victim, now in my old body, where knocked out. 

1. On a wizard round, the wizard summons a robeless apprentice
2. The robeless apprentice teleports to station.
3. A crewmember stuns the robeless apprentice.
4. The robeless apprentice mindswaps with his assailant
5. Both parties will be knocked out for the same ammount of time.

**Comment by kriskog** [comment]
This is intentional
