### ISSUE TITLE
Taking damage after dying prevents you from leaving your body after death.

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#46401]
If you keep taking damage after death, for example with a conveyor->shocked grille setup trying to move, even after a while, won't let you become a ghost. The ghost verb is unaffected, and is the only way to become a ghost at that point.

**Comment by nemvar** [comment]
Probably related to https://github.com/tgstation/tgstation/issues/42916

**Comment by Cyprex** [comment]
I see, I'd be in favor of closing that issue if it stems from the same cause, as this issue report is more general.

**Comment by nemvar** [comment]
This describes the source better. Closed the other one in favour for this.

**Comment by ATH1909** [comment]
Ah, _that's_ what causes that. How'd you figure out that it was the repeated post-death damage that was causing this?

**Comment by Cyprex** [comment]
A player ahelped if it was okay to make traps that prevent you from ghosting once dead(They weren't aware of the verb). I've seen conveyor->grille setups a bunch recently on terry so I already had an idea what he meant, and I just guessed that it was the damage. Lava, which doesn't move you, confirms this pretty much.

**Comment by nemvar** [comment]
It is likely that both issues have the same cause. It doesn't need to be damage, it could a whole number of things.
