### ISSUE TITLE
Embed bug

### ISSUE THREAD

**Issue by Timonkeyn** [tgstation/tgstation#46416]
Issue reported from  Round ID: 118200 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471
1. turn on the medieval mode on holodeck
2. get a holodeck spear embedded
3. turn off medieval mode

the spear couldnt be pulled out, was still doing Damage, making a moodlet and showing an Icon in the top Right. after a while it "fell out" (i got no message of that), the Icon and the moodlet was still there but the Damage was gone (i was kobe koster, the HoS)

**Comment by PKPenguin321** [comment]
Embedded objects getting deleted in general will likely cause this
