### ISSUE TITLE
Boh bombing blobs can cause stalemate

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#46420]
Also see #45956.
Anything living or object is forcemoved inside the singularity. This causes blobs from ever dying if core gets sucked in.

## Reproduction:
Put a bag of holding inside another bag of holding near blob core.
Hope it eats the blob core.
Blob is now unkillable, and will probably prevent shuttle leaving.

**Comment by zxaber** [comment]
Wew, we're back to this nonsense.

**Comment by ExcessiveUseOfCobblestone** [comment]
so dumb so dumb so dumb

**Comment by PKPenguin321** [comment]
blacklist on the boh singulo that just deletes specific paths instead of holding them?

**Comment by nemvar** [comment]
As I pointed out in https://github.com/tgstation/tgstation/issues/45956, the current implementation of the boh bomb is completely fucked.

**Comment by Timonkeyn** [comment]
It's probably because Muh grief restoration but to on tear
