### ISSUE TITLE
TESLA_IGNORE_1 (tesla immunity flag) doesn't have a source attributed to it

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#46449]
putting on reactive tesla armor gives you TESLA_IGNORE_1
removing the armor removes TESLA_IGNORE_1 

lighting bolt spell gives you TESLA_IGNORE_1 
refunding lighting bolt removes TESLA_IGNORE_1 

>get lighting bolt spell
>put on armor
>refund spell
>lose tesla immunity till you put it back on

>put on armor
>get spell
>take off armor
>lose your magically granted immunity

partially caused by #46436

**Comment by optimumtact** [comment]
it's a flag, not a trait, so has no source.

Fix is to use a trait to track the sources, and only remove the flag when they're all gone.

**Comment by optimumtact** [comment]
i would say convert it fully to a trait but it's likely in a very hot loop with the tesla code

**Comment by LemonInTheDark** [comment]
so uh.... Can I just add the mob casting the spell to the hit list, so you never get bolted by yourself? It removes immunity, but I'm not sure if that's good or bad.
