### ISSUE TITLE
Explosive lance creation bug

### ISSUE THREAD

**Issue by Moonman121** [tgstation/tgstation#46440]
Noticed on round 118310

Craft an explosive lance, it will create it on the floor and will show your character holding a regular spear that isn't actually there, but you can still attack with it and it disappears when dropped. Crafting another explosive lance while holding the one you just made gives you the invisible spear and drops a regular spear on the floor instead of an explosive lance.

**Comment by nemvar** [comment]
Did you hold the spear while crafting the item?
