### ISSUE TITLE
Voice of God Bug/ Auto-IC mute sensitivity 

### ISSUE THREAD

**Issue by BlessedHeretic** [tgstation/tgstation#46454]
Issue reported from  Round ID: 118361 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1478

Voice of God installment began to make the Auto-IC mute function seem to bug out and apply IC bans again and again, not even for talking but doing ANY action that would output the same result more than once. 

Example - Shooting a plasma cutter several times would trigger it, or sneezing.

I have noticed this issue in 3 rounds, each round I had voice of god. 

Witnessed Admins for these events include Goat(?) I believe, and Names.

**Comment by Misdoubtful** [comment]
Putting a mob with ventcrawling and voice of god into a pipenet can reproduce what I think you are describing here. It can have an existential crisis as a result.

**Comment by optimumtact** [comment]
wtf

**Comment by Krysonism** [comment]
Too powerful for mere mortals.
