### ISSUE TITLE
Scoping in with a sniper rifle causes visual glitches

### ISSUE THREAD

**Issue by Glassmanner** [tgstation/tgstation#46456]
## Round ID:118368

Issue: Used syndicate sniper rifle with a soporific magazine, zoomed in and everything glitched out. playing on the server became impossible due to a visual glitch. Tried reconnecting and clearing the byond cache but the issue didn't get solved until the round ended.

How to reproduce: Use sniper rifle and scope in, visuals become messed up

![](https://i.gyazo.com/4425cd7e4ff9e215f3a1b0b62acd46b7.png)

**Comment by Tharcoonvagh** [comment]
Worked fine for me

**Comment by ArcaneMusic** [comment]
Reoccured on round Id:142661.
Happened to me as lead op during nuke ops, I had the sniper rifle as well as X-ray vision implants, and the first click of my sniper rifle scope effectively removed me from the round as my viewport got dedatched from myself regardless of un-scoping, reconnecting in-client, and being ghosted in and out of my mob. only solution was a full client close and re-open.
