### ISSUE TITLE
AI upload turrets dont work on MetaStation

### ISSUE THREAD

**Issue by terranaut1** [tgstation/tgstation#46469]
This is the third occurrence of it I've noticed playing AI today and yesterday and it's likely consistent.
Whenever somebody enters the upload I use the turret controls to turn them back on they don't pop out of the covers to shoot at the intruder. I haven't tested it on other maps.
In a fourth round I was malfunctioning and an intruder on the satellite was stopped by its turrets; I haven't checked if turrets on the satellite function in general and are unrelated or if me being malfunctional somehow sprung the turrets to action.

**Comment by terranaut1** [comment]
Yesterday in 118436 the Captain entered the upload after deactivating the turrets. I ctrl-clicked the control panel while they take all the time in the world (well, they were in there for about 30 seconds I believe) to upload a law.

**Comment by ReplicantTerry** [comment]
Just saw this happen on the AI sat- captain was able to walk into my core and card me even though turrets were turned on. They didn't fire upon him or the HoP.

**Comment by ReplicantTerry** [comment]
Round id 119353

**Comment by Detective-Google** [comment]
Could be a problem with #46303 ?

**Comment by timothymtorres** [comment]
I'm pretty sure #46756 fixed this issue so I'm closing it.  If anyone has the same problem just ping me and I will reopen it.
