### ISSUE TITLE
Generating a cyborg spraypaint can with pyrite extract is one use only

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#46463]
Title, using it makes it instantly disappear and gives the message "how did you get this?" either fix it so it doesnt disappear on one use or disable it from spawning from pyrite extracts

**Comment by Ty-the-Smonk** [comment]
Since when did this spawn the cyborg module only item

**Comment by Dawson1917** [comment]
Looks like nobody blacklisted the cyborg subtype of spaycan from the spawn pool
