### ISSUE TITLE
You can get stuck moving in a direction via swaping in/out of hotkey mode via tab while moving in a direction.

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#46479]
## Reproduction:

Hold W, A S or D while in hotkey mode, really doesn't matter, hit tab to swap out of hotkey mode, hit tab to swap back into hotkey mode, get stuck moving in a direction unable to stop moving.

I most likely worded this like shit but it's almost 3AM so ehhhhhhh.

**Comment by ATH1909** [comment]
I've been experiencing something like this on occasion, although I don't think that I was swapping in and out of hotkey mode. It's quite annoying, but IIRC, a reconnect is able to fix the issue (until you somehow meet the conditions for triggering this bug again).

**Comment by Twaticus** [comment]
yeah i experienced this today as well. before you could run, tab to type something, tab again and you just had to press the key you used to run to stop. 
now it doesnt matter which key you press, youre stuck moving in that direction

**Comment by optimumtact** [comment]
not sure how we would fix this easily, maybe clear the keys array when swapping movement mode

**Comment by Electronics** [comment]
Normally you can stop the stuck key by pressing and releasing the correct movement direction in hotkey mode.

**Comment by Borisvanmemes** [comment]
@Electronics You used to be able to do that, and i have no idea why it doesn't work anymore.

**Comment by Kmc2000** [comment]
I've had this issue for years. I just spam the arrow keys until it calms down

**Comment by actioninja** [comment]
possible workaround: mash keys until you roll over the buffer

**Comment by optimumtact** [comment]
probably fixed by actions input changes

**Comment by Borisvanmemes** [comment]
Unless these said action input changes aren't on terry yet as of time of writing, this is not in fact fixed, mashing keys does in fact work though, so this can stay closed.

**Comment by Difrit** [comment]
How else am I supposed to autorun across Kalimdor to go toolbox a smerd?

**Comment by actioninja** [comment]
yeah u rite its a feature

**Comment by Borisvanmemes** [comment]
This is fixed.
