### ISSUE TITLE
Pubbystation chapel shuttle consoles don't work

### ISSUE THREAD

**Issue by Names-Are-Hard** [tgstation/tgstation#46470]
## Round ID:
118417

## Reproduction:
Use the chapel shuttle consoles in dorms or in the chapel. The console inside of the shuttle works fine, though.
![image](https://user-images.githubusercontent.com/35442306/64806572-4f852c00-d548-11e9-9a00-eba551ae6d5a.png)

**Comment by Detective-Google** [comment]
To add on this, if you decon and reinstall the console on the shuttle it also stops working
