### ISSUE TITLE
Duplicating foods with the All-In-One Grinder and the deep fryer

### ISSUE THREAD

**Issue by Sambug2000** [tgstation/tgstation#46484]
Issue reported from  Round ID: 118476 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1467

You can duplicate food with the grinder and deep fryer by first frying the said food once, then putting it in the grinder with a beaker loaded, then by selecting "Juice". IMMEDIATELY, the un-fried version of that food pops out, and after you eject the beaker after it is done juicing, the fried version pops out, you can repeat this by frying the un-fried version then repeating the juicing process, ad infinitum from my very limited experience. Only tested with liver and lungs, didn't want to go any further and accused of abusing a bug.

**Comment by ATH1909** [comment]
Are you only able to duplicate the fried versions of foods this way?

**Comment by sandshark808** [comment]
I'm relatively sure this works for all non-food items which have been fried and then subsequently are put through another "transformative" process.

You can do the same thing with a fried organ being placed into a sandwich, for example. Or a fried piece of glass, or a crayon. I would hazard a guess that any item that you can fit into a deep fryer can be duplicated this way, but ONLY fried. You'll get the original plus a fried copy every time, so it's not game-breaking duplication as far as I'm aware.

My guess is that this may have to do with the same piece of code that makes wrappers drop off of wrapped foods, or plates drop off of plated foods when they're consumed.

**Comment by kriskog** [comment]
Could also be related to  #44123

**Comment by PepperPrepper** [comment]
apparently fixed by #46593
