### ISSUE TITLE
Paystands won't notify you of payments if your card is muted

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#46487]
Instead of doing the sensible thing and just removing the constant message spam caused by automatic paychecks, #42849 made it so you have to decide whether you want to hear beeping every 5 minutes or be unable to ever tell if someone makes a payment

1. Mute your id card through preferences
2. set up paystand
3. make a payment to the paystand
4. ID card does not alert you of payment

**Comment by PKPenguin321** [comment]
This is a feature request. Muting your ID would sensibly mute paystand payments too. A separate mute option would be a new feature.

**Comment by Mickyan** [comment]
I didn't ask for a separate mute option, I said the mute had to be made in a way that didn't break all feedback from the paystand, which was _essential_ to its proper function

**Comment by Qustinnus** [comment]
valid point
