### ISSUE TITLE
miracle.dmm is missing from /_maps/RandomRuins/SpaceRuins

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#46494]

**Comment by nemvar** [comment]
tf is miracle.dmm?

**Comment by MMMiracles** [comment]
a small asteroid with that sign you click and it takes you back to arrivals

kor added it i think when space ruins were first added

**Comment by Fikou** [comment]
> a small asteroid with that sign you click and it takes you back to arrivals
> 
> kor added it i think when space ruins were first added

thats salvation

miracle.dmm is pulse rifle ruin
