### ISSUE TITLE
Blank "Non-Functional Organs" field when scanning a body

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#46491]
I'm not sure what the exact state of the guy was, but when I tried to defib him it said his heart was missing

![Screenshot_5](https://user-images.githubusercontent.com/38563876/64901445-96366b80-d699-11e9-8522-3b9c3eb37f96.png)

**Comment by kriskog** [comment]
They pop up whenever any organ is damaged afaik.

**Comment by kopoba** [comment]
Was it human or no? Some races have no heart like plasmamen.
 

> 
> 
> It pops up whenever any organ is damaged afaik.


 @kriskog not a bug https://github.com/tgstation/tgstation/issues/45919

**Comment by Mickyan** [comment]
Human, probably got disemboweled which would be covered by #46492

Seems like an odd thing to do but I guess so
