### ISSUE TITLE
Crossing people while wearing the clown PDA slips them.

### ISSUE THREAD

**Issue by nemvar** [tgstation/tgstation#46517]
## Reproduction:

Wear clown PDA.
Switch places with a guy while on help intent.
They get slipped.

Alternative reproduction.
Wear clown PDA.
Be prone
Someone walks over you
They get slipped.

Caused by https://github.com/tgstation/tgstation/pull/46301

**Comment by PKPenguin321** [comment]
holy moly

**Comment by PKPenguin321** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/46520
