### ISSUE TITLE
cats can reproduce with holographs

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#46529]
https://monosnap.com/file/ceQ2qRxwHm6iQxhD8csDtCYRm0zIIF

119291

**Comment by Learner10** [comment]
Is it just cats, or can other critters reproduce this way? This also opens up various questions of considerable scientific concern, and interesting uses of it.

**Comment by Qustinnus** [comment]
fuck this room and fuck its stupid variables we should just remove it. we need to add hologram checks everywhere for this dumb ass feature

**Comment by Tharcoonvagh** [comment]
>dedlink

**Comment by Firecage** [comment]
....Can we maybe keep this as a feature?

**Comment by Fhaxaris** [comment]
>fuck this room and fuck its stupid variables we should just remove it. we need to add hologram checks everywhere for this dumb ass feature

**Comment by Timonkeyn** [comment]
Improve not remove
