### ISSUE TITLE
Unable to use toolset arm and armblade at the same time.

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#46532]
Issue reported from  Round ID: 119298 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1464

I ate a nightmare's heart and grew an armblade on my right arm. I  had a toolset arm installed in my left, however when I tried to use the toolset I recieved the following message:

https://i.imgur.com/2Qg6xV4.png

Is this a bug or a feature and if a bug can it be fixed?

**Comment by nemvar** [comment]
Wrong, the bug that happens is that you are unable to use the toolset implant for the left arm. It always places stuff into the right hand.

**Comment by ShizCalev** [comment]
fixed via #46535
