### ISSUE TITLE
Radiation on Lavaland after update

### ISSUE THREAD

**Issue by BlessedHeretic** [tgstation/tgstation#46537]
Issue reported from  Round ID: 119351 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1479

No idea why, but mining is now radioactive since the test merge, I didn't see this prior, unsure if some weird coding has done it but it's consistent.

**Comment by Time-Green** [comment]
They were awere that it would happen. Is it that bad?

**Comment by BlessedHeretic** [comment]
Ah, so is this not a bug then? This might mean that miners need some sort of rad protection, a lot of players have ended up dying to rads because a previously safe material is now toxic as all hell. But if it's not a bug, think I'll close.

**Comment by Time-Green** [comment]
@Qustinnus The radiation might be a bit overwhelming

**Comment by Qustinnus** [comment]
its relatively low, and rad protection has gone up. I think addigg showers to mining is a good idea though

**Comment by necromanceranne** [comment]
@Qustinnus I'm hearing that satchels of holding aren't protecting miners from the radiation, this could be what's responsible. All that ore in the satchel is likely pulsing and irradiating the shit out of the miners unwittingly putting all of it into the bag.

**Comment by Qustinnus** [comment]
wtf how does that happend @ninjanomnom does radiation go through storage

**Comment by necromanceranne** [comment]
Dude, yes. How do you think the BRPED full of micro manipulator in the SM cheese works? It just sits in there irradiating the shit out of everything. Did you actually just assume it didn't?

Also uranium is killing people on-station even apparently from brief interaction so that's a problem. You might want to make a quick fix for this and yeet uranium's radioactivity.

**Comment by Qustinnus** [comment]
well its testmerge so just ask a keyholder to temporarily take it down.

**Comment by necromanceranne** [comment]
Oh right I forgot it was a testmerge. Phew.
