### ISSUE TITLE
cyborgs can't hit vending machines in melee

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#46531]
steps to reproduce:
1. be a standard cyborg
2. receive a law that says that capitalism is human harm
3. try to use your pickaxe (and other tools/weapons) to destroy vending machines
4. notice that nothing happens when you click on a vending machine with your pickaxe, wrench, etc. (I haven't tested to see if an engiborg can screwdriver->crowbar or wrench them yet)
5. cry

**Comment by nemvar** [comment]
What vending machines exactly? All of them?

**Comment by ATH1909** [comment]
> What vending machines exactly? All of them?

As far as I can tell, all of them (maybe the mining one might be different? I dunno). I tested this with both a drink vending machine (or was it a snack vending machine?) near Dorms and the YouTool vending machine in Primary Tool Storage.

**Comment by 81Denton** [comment]
Just tested and can confirm this

**Comment by Dawson1917** [comment]
i'm pretty sure this applies to everyone, not just borgs. you have to throw things at a vending machine to damage it because they can't be struck in melee
