### ISSUE TITLE
Saycode issue

### ISSUE THREAD

**Issue by themanofpie** [tgstation/tgstation#4654]
When speaking in /say chat, the message broadcasts over intercomms not once, but twice, even when not using the semicolon.

**Comment by d3athrow** [comment]
I know this is old but we've just recently ported this saycode and I can't reproduce the issue myself.

**Comment by Miauw62** [comment]
it's radio-code related. as i said, the signal datum is not having its done set properly.

**Comment by Miauw62** [comment]
i should probably try to reproduce this though

**Comment by Jalleo** [comment]
Bump is this still a issue Miauw?

**Comment by optimumtact** [comment]
probably was someone running around with a station bounced radio

**Comment by Miauw62** [comment]
nah, i have seen this happen.
just not consistently.

**Comment by Davidj361** [comment]
Isn't this caused by using .i/:i?

**Comment by ShizCalev** [comment]
Still an issue?
