### ISSUE TITLE
BoH bombing active nukes doesn't delete them properly

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#46556]
## Round ID: 
119403 Basil

## Testmerges:
#45485
#43148

## Reproduction:
When an active nuke gets BoH bombed, it doesn't get deleted properly; the timer doesn't get stopped, alarm level doesn't get reset, the nuke disk doesn't respawn etc.

In round 119403, the OOC muting part happened with no explosion, but the round did not end afterwards. I wasn't able to reproduce that part when testing locally.

**Comment by kriskog** [comment]
Related: #46420, #45956.

**Comment by nicbn** [comment]
whoops

**Comment by ExcessiveUseOfCobblestone** [comment]
just delete stuff instead of the dumb admin-undo mechanic.

call it emergent gameplay and move on, people hardly boh bomb in the year 2019 anyways
