### ISSUE TITLE
Nuke disks can be transported through gateways

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#46557]
Nuke disks can be transported through active gateways. Nuke ops hate it!

**Comment by ATH1909** [comment]
YIKES.

**Comment by InsaneKatrina** [comment]
OH GOD

OH FUCK

**Comment by ATH1909** [comment]
Wait, actually, how much of a yikes is this? You can't open the gateway before the 30 minute mark, right? Couldn't you have called the emergency escape shuttle to the station by that point?

**Comment by ATH1909** [comment]
You could then just early-launch the shuttle instead of faffing about with hiding the disk on the other side of the gateway...

**Comment by 81Denton** [comment]
You probably could, it's just bad since the nuke disk is supposed to always stay on the station's Z level. For example, take really slow ops or lone operatives.

**Comment by SuperNovaa41** [comment]
umm no
