### ISSUE TITLE
PDA servers can accept unsanitized text when setting new password

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#46553]
Title, PDA message monitor consoles accept unsanitized/bad characters which aren't accepted when used again in the console, which prevents setting a new password and be be directly outputted to paper by emagging a message monitor console.

### Reproduction:
- Aquire access to an emag, screwdriver, and message monitor console
- Get the PDA server key by emagging the monitor console, then fix it by disconnecting and reconnecting the monitor.
- Log into the console and change the password to something containing special characters such as "<>"

Attempting to change the password again with the same password will tell you the password is incorrect, you can still connect to the server with it, but are no longer able to change it.
(Attempts at reformatting a password like <><> using (without spaces) & l t ; & g t ; & l t ; & g t ; also fail to authenticate)

- Emag the console and get a security key paper containing the unsanitized text.

This would be incredibly dangerous right now were it not for the password character limit of 3 to 16, this does not exclude the possibility that there may be some way to escape or work within this limit using the right game mechanics or knowledge.

Here's an example showing some very minor results.
![Dailykey](https://user-images.githubusercontent.com/17460297/64947289-86e62800-d829-11e9-9ad4-4f7d08b8509d.PNG)

**Comment by ATH1909** [comment]
Yikes.

What exactly can you feed into this? Can you trigger an explosion or spawn an item, for example, or are your shenanigans really mostly just limited to making some BEEG TEXT or the like?

**Comment by GravitronBlue** [comment]
Worst case scenario this has the same potential as #9900, but that's only if the 16 character limit for the password is enough to do anything or some other way to add more is found.

**Comment by GravitronBlue** [comment]
I believe I have a working method that can allow a script payload to be assembled by utilizing the library's book press and uploading those books to a newcaster, which can then be printed to a newspaper. Which could be executed if someone reads the paper or looks at the nanotrasen book club newsfeed.

#### To reproduce
- Get two message monitor consoles
- Log into the PDA server with one which will be used to change the key repeatedly, the other will be used to print papers with an emag.
- Click the change password button repeatedly on the first console to que several prompts, copypaste the current code until you reach the prompts where your input will change the server key. This allows you to skip having to re-input the new key to change it, and otherwise avoid being locked out once you start inputting brackets '<>'.

For this next part emag the second console and then reassemble the console with a screwdriver for each segment, do not disassemble the first console or the qued prompts will be meaningless. You will want to organize the printed key papers for later.
As for payload assembly itself, I'll have to generalize due to my lack of specific knowledge.
- Begin with a <script> tag, followed by the start of a code comment (code) "
- Once you have several papers with the entire code, take each one to the book press until you have a book version of the whole script.
- Again with each book in order, go the book scanner in the curator's office and scan a book, go to the book management console and then upload it to the newscaster network, repeat until all books have been uploaded.
- Go to any newscaster either check out the Nanotrasen book club page, or print a newspaper and flip the page to whatever section containing all the uploaded books.
- [???](http://www.youtube.com/watch?v=XUKaZbVzFgk&t=1m9s)

>B&'d
