### ISSUE TITLE
Href abuse allows forbidden file interaction on modular computers

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#46559]
Title, forged hrefs can bypass restrictions on file actions, like renaming, cloning, and exporting files.
### Reproduction:
- Get a modular computer device
- Spend an annoying amount of time pulling href addresses from UI files due to TGUI being stingy about that kind of data with ingame windows.
- Forge mean hrefs to tell Byond
- Painstakingly "copy" the syndicate contractor program to another computer
- Realize contractor program doesn't work on other computers
- Mess with everything else instead out of spite

![Yarrr](https://user-images.githubusercontent.com/17460297/64950302-ddeefb80-d82f-11e9-976d-cd2455046d16.PNG)

> Former VR entrepreneur shifts to networking, defeats copy protection, realizes there's nothing really valuable to copy that's protected.

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=V4MF2s6MLxY

TBH, this is kind of in-flavor/in-lore for modular computers. Still, yeah, this should probably get fixed.

**Comment by PKPenguin321** [comment]
Paper was a mistake

**Comment by optimumtact** [comment]
it's stingy on purpose

**Comment by optimumtact** [comment]
also this isn't paper, it's topic calls in modular computers not doing validation

**Comment by ExcessiveUseOfCobblestone** [comment]
> href abuse is lore-friendly

lol'd

**Comment by JohnFulpWillard** [comment]
The instances reported have been fixed and I am not aware of any current ones, make a new issue report if it happens again.
