### ISSUE TITLE
Crowbars don't work on airlocks

### ISSUE THREAD

**Issue by Shapsy** [tgstation/tgstation#46567]
## Reproduction:
>Try to crowbar door, hacked or not
>Get nothing back. No message about motors, no opening, no nothin'

being on harm intent just whacks the airlock

**Comment by ATH1909** [comment]
UH OH

**Comment by Fhaxaris** [comment]
> merged:>2019-08-16 crowbar

alright who dunnit

**Comment by penterwast** [comment]
Seems to have been caused by #46332

**Comment by ATH1909** [comment]
@optimumtact I think that this (or the PR that caused this issue) deserves to be added to your list of biggest fuckups of the year: https://github.com/tgstation/tgstation/milestone/51?closed=1

**Comment by optimumtact** [comment]
I disagree
