### ISSUE TITLE
Cannot use any click functionality in a 90 degree arc of the screen

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#46571]
Issue reported from  Round ID: 119459 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1484

Happened over the course of two rounds, separated by restarting byond. My byond is up to date.

I cannot examine, point, shoot, throw, or otherwise interact with any element that is used in the upper left quadrant of the screen. 

This deadzone occurs in an arc from (if a straight line to the right is zero degrees, and going counterclockwise from there denotes a positive angle) 80 degrees to 170 degrees.

Wierdly, as a ghost, I can orbit the objects in this area, but not point at them.

Reconnecting does not help this.

**Comment by Shirbu** [comment]
I will test this again right now

**Comment by Shirbu** [comment]
It is still occurring.

**Comment by Shirbu** [comment]
It appears that I can still use clicks to pick up and pull items, so I will edit my description

**Comment by Tharcoonvagh** [comment]
HOW

**Comment by Detective-Google** [comment]
I've had this happen with right click menu items pretty commonly, especially as a ghost, but it covers the entire screen not just part of it
(Also as a ghost you can't point through walls so make sure it's not that)

**Comment by ShizCalev** [comment]
discord overlay memes?

**Comment by Shirbu** [comment]
Possible. It stopped happening to me today.

**Comment by Shirbu** [comment]
I have solved the problem. Shiz was very close.

**Comment by Shirbu** [comment]
It occurs with an application called "Team Speak," which leaves an overlay that constantly runs in the background of everything. Turning this off resolved the issue.
