### ISSUE TITLE
donut station floor apc

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#46595]
https://monosnap.com/file/RBZFMEDHeFmzs8vlR1ysyICDOKcMsp

**Comment by ShizCalev** [comment]
What?

**Comment by Tlaltecuhtli** [comment]
there is an apc on the floor instead of on a wall south east of vault

**Comment by ShizCalev** [comment]
all i see is a billion ghosts, mind pointing it out?

**Comment by Tlaltecuhtli** [comment]
https://monosnap.com/file/du064Ocq93YeqzbkFLbaR7gdPu9ksU

**Comment by Tharcoonvagh** [comment]
remov donut
