### ISSUE TITLE
Organ harvester doesnt resume operations after losing power

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#46606]
Issue reported from  Round ID: 119528 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1464

When an organ harvester loses power while harvesting you cant eject the body or resume operations. You cant even dismantle it. This is very problematic.

**Comment by ATH1909** [comment]
I believe that I've reported this before.

**Comment by ATH1909** [comment]
Ah, I reported it inside of a PR, not in a bug report:
https://github.com/tgstation/tgstation/pull/43428
