### ISSUE TITLE
Cyborgs still buckling on harm intent

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#46617]
#46364 seems to not be working for the no buckling aspect of harm intent. Click dragging on help intent will pull the target onto you while harm will do as it previously did before the change.

**Comment by kriskog** [comment]
Buckling on harm will both buckle and open their equipment window.
@ATH1909

**Comment by ATH1909** [comment]
Oh shidd oh fugg

**Comment by ATH1909** [comment]
```
/mob/living/silicon/robot/MouseDrop_T(mob/living/M, mob/living/user)
	. = ..()
	if(!(M in buckled_mobs) && isliving(M))
	if(!(M in buckled_mobs) && isliving(M) && ((user!=src)||(src.a_intent != INTENT_HARM)))
		buckle_mob(M)
```
I think this has something to do with the user!=src check, but I'm not sure. I also don't know how to fix this (without removing the ability for a non-borg to buckle themselves to a borg that's on harm intent). Does anyone here know how to fix this bug?

**Comment by ATH1909** [comment]
https://github.com/tgstation/tgstation/pull/46622 should fix this (if it gets merged).
