### ISSUE TITLE
Dying in bloodcrawl and getting ahealed removes bloodcrawl, making it impossible to leave.

### ISSUE THREAD

**Issue by AtlasRules** [tgstation/tgstation#46620]
I killed a slaughter demon, and ate the heart. I got hit with a saw, and started to bleed out during bloodcrawl. I got ahealed because the bartender didn't know I wasn't a demon, and I lost the ability to bloodcrawl.

**Comment by nemvar** [comment]
Probably related to https://github.com/tgstation/tgstation/issues/35539

What species were you?

**Comment by AtlasRules** [comment]
Normal ol' human

**Comment by Rockdtben** [comment]
in species.dm

//Will regenerate missing organs
/datum/species/proc/regenerate_organs(mob/living/carbon/C,datum/species/old_species,replace_current=TRUE)

**Comment by nemvar** [comment]
/datum/species/proc/regenerate_organs isn't called from spec_fully_heal().

It's called from /mob/living/carbon/regenerate_organs(), which is located in https://github.com/tgstation/tgstation/blob/master/code/modules/surgery/organs/organ_internal.dm

**Comment by Rockdtben** [comment]
Woops in human.dm it calls regenerate organs in the full_heal method.
