### ISSUE TITLE
Alphabetize sprites in sprite sheet 

### ISSUE THREAD

**Issue by TheTeenyTiny** [tgstation/tgstation#46639]
It's not a big deal, but if we could do this, it'd be a hell of a lot faster / easier to find sprites that need fixing. 

Currently looking into fixing the toolbelt request but in order to find it, I have to sift through all the sprites because they are not logically ordered. I sometimes wind up spending more time trying to find the sprite than it takes me to fix it. 

Additionally, difficulty finding said sprite leads to eventually abandoning wanting to fix an issue because I can't find it. 

![Sprite sheet example](https://user-images.githubusercontent.com/55539108/65284363-50e5c400-db07-11e9-8e4e-39bbe7631dbf.jpg)

**Comment by Qustinnus** [comment]
This has its own problems because sprites are currently grouped into relevant groups, alphabetic order destroys that. 

What would be better is the ability to search through Dmis
