### ISSUE TITLE
Contractor Tablet got bugged.

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#46645]
## Round ID: 
119671

## Testmerges: 
None

## Reproduction: 
I was a traitor who bought the contractor kit, and all went well until my second kidnapping which was the roboticist. They ended up dying in the scuffle(due to my support), but I still took them to the extraction point to be taken, and this is where the issue started. Immediately after they were extracted, my Contractor Tablet became bugged. I had it open at that time and noticed nothing worked when I pressed it, so I closed and re-opened it, and it went back to the screen which simply showed 'Assign' as if I didn't use it yet. And the big problem was, I couldn't re-use 'Assign' either. Hence, I was unable to do any more kidnappings since my Contractor Tablet became a complete bust.

The next round the roboticist, TheMidnightRose, told me that after they hit the DNR button after they died, and that was before I dragged them out of robotics. So I am unsure if that possibly caused the bug to occur. As an additional point, the extraction point was also in the recreation area of MetaStation on Bagil.

**Comment by kriskog** [comment]
Fixed
