### ISSUE TITLE
Table to strangle oversight

### ISSUE THREAD

**Issue by Fhaxaris** [tgstation/tgstation#46651]
Currently you can...
1. Table someone
2. While they are tabled neck grab and table again.
3. Grab up to an aggressive grab before the progress bar completes.
4. When they are neck grabbed, grab again.
5. Beat them into crit/full-strip while they only had a 5% to 15% chance to escape.

I know chain tabling exists, but this kills people much quicker and doesn't let them call for help.

**Comment by Ty-the-Smonk** [comment]
Chain grabbing in ss13 is a thing now

**Comment by Ty-the-Smonk** [comment]
This is probably due to aggro grabbing doesn’t have a bar and progress bars act of their own free will

**Comment by Fhaxaris** [comment]
Table slamming should stop the progress of the neck grab but doesn't if you use the same table because their position doesn't change.

**Comment by Fhaxaris** [comment]
This still works with #46383.
1. Table someone
2. While they are tabled neck grab and table again.
3. While the bar is filling up grab up to an aggressive grab.
4. Neck slam them.

**Comment by Fhaxaris** [comment]
if what you are pulling changes, it could break the do_after.
eg. when you table them you are no longer pulling them so it stops
