### ISSUE TITLE
Bartenders lose the ability to throw glasses without spilling during wiz events

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#46678]
The Round ID is 119279

## Testmerges:
N/a

## Reproduction:
Be bartender
Wiz event: Change Places happens
Go back to bar
Throw drink
Break glass
Cry

**Comment by nemvar** [comment]
Ability to throw drinks is tied to your glasses. I have no idea why this would be happening.

**Comment by nemvar** [comment]
Actually, looks like glasses are just broken in general.

**Comment by kriskog** [comment]
Can't reproduce, works fine as long as you got your beer goggles on.
