### ISSUE TITLE
crevice spike and fanciulli won't sober you up

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#46687]
There are two drinks in the game that have a negative boozepwr: crevice spike and fanciulli. They both have a boozepwr of -10 and, unlike most other subtypes of ethanol, are meant to sober you up instead of make you drunk.

Unfortunately, they don't actually affect your drunkenness value at all:
```
/datum/reagent/consumable/ethanol/on_mob_life(mob/living/carbon/C)
    if(C.drunkenness < volume * boozepwr * ALCOHOL_THRESHOLD_MODIFIER)
        var/booze_power = boozepwr
        if(HAS_TRAIT(C, TRAIT_ALCOHOL_TOLERANCE)) //we're an accomplished drinker
            booze_power *= 0.7
        if(HAS_TRAIT(C, TRAIT_LIGHT_DRINKER))
            booze_power *= 2
        C.drunkenness = max((C.drunkenness + (sqrt(volume) * booze_power * ALCOHOL_RATE)), 0) //Volume, power, and server alcohol rate effect how quickly one gets drunk
        var/obj/item/organ/liver/L = C.getorganslot(ORGAN_SLOT_LIVER)
        if (istype(L))
            L.applyOrganDamage(((max(sqrt(volume) * (boozepwr ** ALCOHOL_EXPONENT) * L.alcohol_tolerance, 0))/150))
    return ..()
```
ALCOHOL_THRESHOLD_MODIFIER is 1 by default, by the way.

"if(C.drunkenness < volume * boozepwr * ALCOHOL_THRESHOLD_MODIFIER)"
If boozepwr is negative, volume * boozepwr * ALCOHOL_THRESHOLD_MODIFIER will be negative as well. Therefore, unless your drunkenness value is somehow NEGATIVE, crevice spike and fanciulli will never affect your drunkenness value (or damage your liver).

Why is that check even there? volume * boozepwr will usually be incredibly high (even 1u of beepsky smash will still affect your drunkenness value if it's below 90), so it basically does nothing unless you're vaping drinks or something.

**Comment by nemvar** [comment]
The check is there because this gets the sqrt of (volume * booze_power * ALCOHOL_RATE) and that shit isn't allowed to be negative. The reason why it does ALCOHOL_THRESHOLD_MODIFIER instead of ALCOHOL_RATE in the smaller than check is because someone forgot to update defines, probably.

**Comment by nemvar** [comment]
Again math foils the plans of an ambitions coder.

**Comment by nemvar** [comment]
Well even if you remove the check, you still have to deal with (sqrt(volume) * booze_power * ALCOHOL_RATE) never returning negative values.

**Comment by ATH1909** [comment]
Oh yeah, that too.

**Comment by ATH1909** [comment]
> Well even if you remove the check, you still have to deal with (sqrt(volume) * booze_power * ALCOHOL_RATE) never returning negative values.

Wait, no, that shouldn't be an issue. What are you talking about?

Sure, it won't bring people to a negative drunkenness value, but I think that that's intentional.
