### ISSUE TITLE
some ERT members spawn with engineering hardsuit helmets

### ISSUE THREAD

**Issue by Detective-Google** [tgstation/tgstation#46685]
## Reproduction:
Spawn ERT
Their helmets are fucked up
![image](https://user-images.githubusercontent.com/48196179/65378603-5fa3b680-dc80-11e9-92e1-bfd5a61602d5.png)

![image](https://user-images.githubusercontent.com/48196179/65378658-43ece000-dc81-11e9-8498-567e9e44a866.png)

**Comment by nemvar** [comment]
tbh seems more like a sprite issue.

**Comment by nemvar** [comment]
@actioninja This is your fault
