### ISSUE TITLE
ED-209's have no sprite

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#46695]
Basically the title with this one. Because they lack a sprite they're unkillable without a diagnostic hud presumably.

![Screenshot 2019-09-22 22 44 58](https://user-images.githubusercontent.com/40847847/65387612-5738a200-dd8c-11e9-865b-471b53b3f03d.png)

**Comment by Swiftkor** [comment]
Has cloaking technology gone too far?
