### ISSUE TITLE
Advanced Mimery Glitch

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#46701]
Anyone who tries to use Advanced mimery books, even if they're not a mime and the books have already been read, get the ability to make or break a vow of silence.

**Comment by spessbandit** [comment]
not a glitch, deliberate https://github.com/tgstation/tgstation/pull/38474

**Comment by necromanceranne** [comment]
I think it's more that they can be reused, which is probably not intended.
