### ISSUE TITLE
Toxins Wall Mounted Igniters Broken - Box Station

### ISSUE THREAD

**Issue by BowNArrowPro20** [tgstation/tgstation#46700]
Problem Description: Toxins Igniter Broken

Round ID: NULL

What did you expect to happen: I expected igniters to ignite gas in chamber.

What happened instead: Nothing, doesn't spark.

Why is this bad/What are the consequences: Have to use unorthodox methods to create science bombs.

Steps to reproduce the problem: Broken at round start.

Server: Private/Personal

Recently a similar issue affected MetaStation, as seen here: https://github.com/tgstation/tgstation/issues/46630

**Comment by 81Denton** [comment]
I'll replace them with a floor mounted igniter as usual
