### ISSUE TITLE
Sacred flames didn't ignite user.

### ISSUE THREAD

**Issue by BlessedHeretic** [tgstation/tgstation#46714]
Issue reported from  Round ID: 119940 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1479

Was in a round where I was running around trying to force a call and murder a bunch of people, I was semi successful however, the spell that should have been igniting me and covering people around me in flammable liquids, didn't.

Unsure what caused this, it's usually reliable.

**Comment by BlessedHeretic** [comment]
No parasites. Was human (Angelic? I did have wings unsure if those technically make me another species), ash drake armor and general mining gear otherwise + a staff of storms.

**Comment by kriskog** [comment]
Drinking the flight potion as human or lizard makes you holy. Sacred flame has a check for holy, and wont work on holy people. Intended.
