### ISSUE TITLE
Clown bloodbro clumsy

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#46711]
Be BB
Be Clown
Be Clumsy
:thinking:

**Comment by ATH1909** [comment]
BB?

**Comment by PepperPrepper** [comment]
Blood Brother?

**Comment by Tharcoonvagh** [comment]
Blood brother indeed

**Comment by PepperPrepper** [comment]
Do Blood Brothers go through same system that sets people as antags? Which is where the clumsy trait would be removed (I think) 
This could be a design choice as from memory Blood Brothers are yet to be full syndies and as such lack training.

**Comment by Cyprex** [comment]
Round ID? Was this a dynamic gamemode round?

**Comment by Tharcoonvagh** [comment]
>Do Blood Brothers go through same system that sets people as antags? Which is where the clumsy trait would be removed (I think)
This could be a design choice as from memory Blood Brothers are yet to be full syndies and as such lack training.
dunno
>Round ID? Was this a dynamic gamemode round?
yep, on terry

**Comment by nemvar** [comment]
If you ask me, clown shouldn't lose clumsy just because he got antag.

**Comment by Ty-the-Smonk** [comment]
> If you ask me, clown shouldn't lose clumsy just because he got antag.

There is a special message for clowns that get antag that tells them they overcame their clownish ways

**Comment by PKPenguin321** [comment]
>If you ask me, clown shouldn't lose clumsy just because he got antag.

Make a forum thread

**Comment by optimumtact** [comment]
this is a bug

**Comment by timothymtorres** [comment]
This was fixed in https://github.com/tgstation/tgstation/pull/34236
