### ISSUE TITLE
unknown necromancer makes birdboat vomit and eat while dead

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#46724]
120002

![image](https://user-images.githubusercontent.com/222630/65650339-4cb21e80-dfbf-11e9-8881-0923c4821139.png)

**Comment by Tharcoonvagh** [comment]
round still going reeeeeee

**Comment by 81Denton** [comment]
This fucking bird is cursed

**Comment by ATH1909** [comment]
*while dead, not while UNdead

it's a bit of nitpick, but this change to the title helps clarify that the goose is SUPPOSED to be dead

**Comment by Tharcoonvagh** [comment]
plap what have you done

**Comment by OverlyGeneric** [comment]
ss13 is no longer ss13.

it's now untitled vomitgoose game.

**Comment by spessbandit** [comment]
@plapatin

**Comment by plapatin** [comment]
fun fact: i knew about this bug before the pr was made and left it in intentionally because i thought it was funny

**Comment by plapatin** [comment]
the vomit proc doesn't check if the goose is alive or not and after vomiting the icon_state is set back to the live goose state. its a really simple fix

**Comment by Ty-the-Smonk** [comment]
I N T E N D E D F E A T U R E

**Comment by fludd12** [comment]
@plapatin how did you manage to distill an eldritch abomination into a digital goose.
