### ISSUE TITLE
Exosuited MMIs can't change intent

### ISSUE THREAD

**Issue by nonnoanselmo** [tgstation/tgstation#46739]
MMIs that have been put inside of an exosuit canot change their intent in any way whatsoever due to the lack of a HUD. This makes it impossible to use the hydraulic clamp as a weapon, to gib lavaland monsters for materials like goliath plates and diamonds from watchers. Exosuited MMIs can't interact with consoles either, often remaining helpless inside of rooms unless they have a drill.

**Comment by Tharcoonvagh** [comment]
1 for help 2 for disarm 3 for grab 4 for harm
close issue

**Comment by nonnoanselmo** [comment]
doesn't work, you will push people away with the hydraulic clamp.

**Comment by nonnoanselmo** [comment]
An AIed exosuit retains the AI HUD and can interact remotely with doors, consoles and machines

**Comment by zxaber** [comment]
Just for the doors/consoles thing, you really ought to be making posis into AIs before putting them into a mech anyway.

Though I don't believe AIs can swap intents either, since that's how their anchor system works IIRC.

I'll give it some thought and see if I can come up with a proper fix for both AIs and MMIs.

**Comment by Ohagi-Chan** [comment]
Still Haven't heard anything about this and my mechs still can't use computers.
Can you look into why they can't self-eject either?  I haven't coded for Byond personally but I checked the logic path from mechs all the way back to living and brain; it looks like they are supposed to be able to self eject but somehow just aren't.

**Comment by TheBonded** [comment]
we don't have intents anymore, and pressing F now toggles between combat and non combat
