### ISSUE TITLE
It's not possible to make cyanide

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#46743]
## Round ID:
120068

## Testmerges:
#46566: 'Adds Glowing Crevice Ruin and Lavaland Elites' by IndieanaJones at commit 5275b0a0d5 

## Reproduction:
![image](https://user-images.githubusercontent.com/12382984/65624060-01990b00-dfc1-11e9-9d10-0aad2325ccd9.png)

**Comment by Anonmare** [comment]
This is pretty critical due to penetic acid being needed to make it, which is the only real treatment for severe rad poisoning

**Comment by DON-KARMA** [comment]
you're not trying hard enough

**Comment by Anonmare** [comment]
Those are the exact requirements to make cyanide. Anythign higher will make the oil into ash

**Comment by ATH1909** [comment]
Heat it up to 381K instead; sometimes, you have to heat chems up to a temperature 1K higher than the temperature that they're "supposed" to react at.

**Comment by ATH1909** [comment]
Oil's recipe requires a temperature of 480K; try heating your mixture up to 479K.

**Comment by Anonmare** [comment]
I already tried that, it didn't work

**Comment by Anonmare** [comment]
After re-testing on a new round, it works as normal. I have no idea what the fuck was happening with that round in particular but it *seems* to be resolved. Maybe it was a runtime with the beaker itself or some shit
