### ISSUE TITLE
floor bug nukie shuttle

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#46742]
![tgStation Terry  EU   100% LAG FREE   New-Dedi  Paranoia Space-hulk Two 2019-09-25 182115](https://user-images.githubusercontent.com/54288658/65621848-ce587b00-dfc4-11e9-8e4e-096dfdd7b2ea.png)
Round ID: 120071 on Terry, dynamic with nukies

**Comment by dragomagol** [comment]
Unable to reproduce this
