### ISSUE TITLE
Custom vendors don't serve anyone after encountering a poor person, also cannot be deconstructed.

### ISSUE THREAD

**Issue by Bright0** [tgstation/tgstation#46751]
Round ID: 120095

Reproduction:
Construct a vending machine with a custom board either by screwdrivering a board from a deconstructed vending machine or getting one from a vendomat, doesn't affect outcome. After it's built, it cannot be deconstructed with any tools, only shot until destroyed. Machine otherwise functions as expected when connected to an ID (put in price scanned items, owner takes them out for free, others pay and funds are transferred) until someone attempts to buy something they don't have enough money for. The owner of the machine can no longer pull out items at all, and nobody else can purchase anything either regardless of funds. _(My guess is aristocratic NT techs didn't consider the idea that someone would be unable to afford something.)_

**Comment by Tlaltecuhtli** [comment]
intended and fixed in new pr

**Comment by Jalleo** [comment]
@Tlaltecuhtli What was fixed and what is intended?
