### ISSUE TITLE
can't laugh as mime

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#46758]
Be mime
say *laugh
>Unusable emote 'laugh'. Say *help for a list.

**Comment by gwhit94** [comment]
You can't laugh silently anymore?

**Comment by Tharcoonvagh** [comment]
Guess I can't!
Also my mime mask was on, vow still active

**Comment by 81Denton** [comment]
The emote has `message_mime = "laughs silently!"`, so this looks like a bug

**Comment by Fhaxaris** [comment]
was just playing mime and I could *laugh, did you break your vow of silence or something

**Comment by ATH1909** [comment]
Sometimes I can laugh as a mime, sometimes I can't. It's a bit inconsistent.

You can still laugh (silently) as a mime by drinking the laughter chem, by the way.

**Comment by nemvar** [comment]
Well, if someone can tell me how to reproduce this, that would be cool. Because it works fine for me.

**Comment by Tharcoonvagh** [comment]
Yesterday the same happened with *flip, again, as a mime

**Comment by PKPenguin321** [comment]
I'm curious if you guys are using hotkey mode or non-hotkey mode, in case that may be impacting it somehow

**Comment by ATH1909** [comment]
> I'm curious if you guys are using hotkey mode or non-hotkey mode, in case that may be impacting it somehow

Who DOESN'T use hotkey mode?

**Comment by Fhaxaris** [comment]
> Who DOESN'T use hotkey mode?

ahh yes, today I am going to inconvenience myself for no reason by not using hotkey mode

**Comment by PKPenguin321** [comment]
hotkey mode is a misnomer, both modes have hotkeys, but "non-hotkey" mode has access to the command line

**Comment by Tharcoonvagh** [comment]
Hotkey mode

**Comment by Tharcoonvagh** [comment]
This might have been a problem on my end so closing now
