### ISSUE TITLE
You can use the Chameleon Projector on the Stealth Implant box, and become totally invisible.

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#46777]
To reproduce:

Buy chameleon projector

Buy stealth implant

Use stealth implant

use chameleon projector on the stealth implant cardboard box

turn the stealth implant off

Use chameleon projector, and be invisible and more or less untouchable.

**Comment by Shirbu** [comment]
Especially broken for nuclear operatives, because only one person needs to buy the implant.

**Comment by ATH1909** [comment]
Can you use other items while using a chameleon projector without breaking your disguise?

**Comment by Tharcoonvagh** [comment]
SNAKE!!

**Comment by Shirbu** [comment]
@ATH1909 You can use any item's inhand function, and can use any item on any other item you currently in your inventory.

So for example, sticking c4 onto a syndicate bomb core and dropping it on the ground right by the disk holder

**Comment by 81Denton** [comment]
Ok that's a good one

**Comment by nemvar** [comment]
There are a few of these. If memory serves me right, holosigns and some other stuff also had this issue.

**Comment by 81Denton** [comment]
I'll open a PR to fix both

**Comment by spessbandit** [comment]
also probably want to do mime stuff (chair, box, I don't think wall counts?)

**Comment by Shirbu** [comment]
Probably
