### ISSUE TITLE
Green beer cannot be made anymore, because crayons no longer have green crayon powder as a grind result reagent

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#46778]
Issue reported from  Round ID: 120241 (/tg/Station Sybil-2 [ENGLISH] [US-WEST] [LOWPOP] [100% LAG FREE])

Reporting client version: 512.1485

To reproduce:

Try to make green beer

Grind crayon

Get nutriment and nothing else

Cry

**Comment by kriskog** [comment]
The powder is a available in the rainbow flowers in botany. Wiki recipes might need an update to reflect this.

**Comment by Angustmeta** [comment]
Tested rainbow bunch/flower recently and they didn't have the color reagent. Maybe bug.

**Comment by nemvar** [comment]
This isn't a bug, rainbow flowers not having reagents is. Good catch.
