### ISSUE TITLE
Cia haircut seems to over power many hats.

### ISSUE THREAD

**Issue by Relyksboa** [tgstation/tgstation#46772]
Issue reported from  Round ID: 120212 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])
As seen here, the haircut bleeds through the hat.
![Capturee](https://user-images.githubusercontent.com/52992503/65802190-c701b080-e12f-11e9-99f8-8a4bbdc77a9c.PNG)

Reporting client version: 512.1474

**Comment by cacogen** [comment]
uhh `you don't get to wear hats`

**Comment by Tharcoonvagh** [comment]
This happened with some other haircuts too

**Comment by Anonmare** [comment]
If I pull that hat off, will you die?

**Comment by TheBonded** [comment]
I have not seen this happen anymore. marking this as cleanup flagged unless it is confirmed to still happen
