### ISSUE TITLE
krav maga ignores soft stuns

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#46781]
you can do cool karate moves while soft stunned and on the floor crawling

**Comment by nemvar** [comment]
Actually, is this even a consistency issue? You can also use the other martial arts while prone. The only one that's kinda weird is leg sweep but I guess that could be explained with some sick breakdancing moves.

**Comment by Tlaltecuhtli** [comment]
most github issue could be solved in the same way but people krav magain hardstuns when stunbatoned is really bad

**Comment by nemvar** [comment]
Well no, most of these issues are more technical. Rules are simple, balance shit doesn't belong here. If you don't like it, change it yourself or go to the forums.

**Comment by PKPenguin321** [comment]
for what it's worth i agree that being able to do thing while prone is real dumb, you should really make a forum thread
