### ISSUE TITLE
Silibinin entry is missing, but still referenced in other files

### ISSUE THREAD

**Issue by hydroponicsEnthusiast** [tgstation/tgstation#46785]
I'm not sure if silibinin (liver medicine) is supposed to be missing from the available chems or not, but it is still referenced in "tgstation-master\code\modules\hydroponics\grown\misc.dm" and in "tgstation-master\code\modules\reagents\chemistry\reagents\medicine_reagents.dm".
It has no recipie and no entry describing it's properties.

Growing galaxythistle and grinding it results in abstract reagent literally called "medicine" being added to the beaker.

Silibinin deletion is clearly incomplete, whether it was done deliberately or by mistake. I do hope it is the latter, because having a drug for liver restoration is quite useful.

**Comment by nemvar** [comment]
Alright, let me explain this problem as best as I can.
Let's imagine we have the following code.
```
1 /datum/medicine
2     name = "error"
3 
4 /datum/medicine/proc/do_stuff()
5 
6 /datum/medicine/med
7     name = "med"
8 
9 /datum/medicine/med/do_stuff()
10   // do_effect
```
If someone were to remove line 6 and 7, /datum/medicine/med would still be in the game but no longer have ``name=="med"`` and instead have ``name=="error"`` yet it would keep all the effects that the override in the subtype offers. It would not cause any errors during compile time.

This means: Someone didn't remove all the instances of the reagent, in case it should actually get removed.

I, for one, have no fucking idea what is going on with chems right now but this is a bug regardless of that.

**Comment by nemvar** [comment]
Disregard what I said. This got removed on accident
