### ISSUE TITLE
ORMs are deleting uranium ore

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#46796]
Free golem memes, had some uranium ore and put it in the golem orm, uranium in the orm remained zero. Had it linked to an ore silo which still had no uranium in it, if that makes any difference.
RoundID: 120315

**Comment by trexter555** [comment]
this also includes the station orm

**Comment by 81Denton** [comment]
This was caused due to a bug in #46525 and will be fixed once the test merge on Bagil gets updated.
