### ISSUE TITLE
!!!Claim points as borg to crash server!!!

### ISSUE THREAD

**Issue by Vanadiom** [tgstation/tgstation#46804]
## Testmerges:
#46745

## Reproduction:
Be Borg, claim points in ORM (when there are points in it, duh). Crash server.

**Comment by Vanadiom** [comment]
Fuck this is bad

**Comment by Arianya** [comment]
@Vanadiom Knowing what testmerges were on or not on is important, since something like the materials rework could very likely be related.

Can you just confirm what testmerges were or were not in place?

**Comment by Vanadiom** [comment]
Will do

**Comment by willox** [comment]
I can't reproduce this and the code looks completely sane. Are you sure this wasn't a coincidence?

**Comment by jdawg1290** [comment]
Reference says that that assignment wouldn't run, that said, I’m not sure what it would return to the enclosing if.

**Comment by optimumtact** [comment]
There were several DD crashes around that time with offsets in byondcore.dll

**Comment by Vanadiom** [comment]
Hmm, could be coincidence, did it twice in a row tho, will try again next round

**Comment by Vanadiom** [comment]
Just tried It again round ID: 120379
It crashed

**Comment by Vanadiom** [comment]
This is definitely reproducable

**Comment by willox** [comment]
Can be reproduced on byond 512.1484

**Comment by optimumtact** [comment]
core bug report http://www.byond.com/forum/post/2513020

**Comment by optimumtact** [comment]
| Resolved (512.1488)

**Comment by optimumtact** [comment]
anyone able to test new version?

**Comment by Jalleo** [comment]
I shall test it tomorrow morning or evening.

**Comment by willox** [comment]
Yes 1488 has fixed it
