### ISSUE TITLE
ORM does automatically accept ores, or produce credits, when brought to lavaland.

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#46812]
Issue reported from  Round ID: 120409 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1485

In this round, miners brought the ORM to lavaland.

After being wrenched, it did not accept ores automatically, though you could manually insert ores.

Credits could not be acquired from the ORM.

**Comment by Tlaltecuhtli** [comment]
was it rebuilt? maybe the dude changed the i/o directions accidentally

**Comment by Ty-the-Smonk** [comment]
Change the issue name
