### ISSUE TITLE
Emitters keep shooting security cameras

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#46810]
## Round ID:
Various

## Testmerges:
Not relevant

## Reproduction:
Place emitter and wire it
Put camera in firing path of emitter
Emitter laser hits camera and breaks it
Camera machine broke
Notable maps with this issue - Delta station and Pubby station (SM emitters always break a camera in their line of path)

**Comment by Dawson1917** [comment]
I'm fairly certain this is because emitter shots ignore passover for mobs and items (eg. hits resting people) and end up hitting security cameras in their path.

**Comment by Anonmare** [comment]
This seems relatively recent as you could rest to avoid being shot by emitters in the past

**Comment by nemvar** [comment]
Related to https://github.com/tgstation/tgstation/issues/44143

**Comment by kriskog** [comment]
Apparently fixed
