### ISSUE TITLE
Person with no legs/arms is able to use jetpack

### ISSUE THREAD

**Issue by bloons3** [tgstation/tgstation#46811]
Issue reported from  Round ID: 120399 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1464

Person with no legs/arms is able to use jetpack

During the round I had my limbs removed. Despite this, when the station lost gravity, I was able to fly around with a jetpack.

Not sure if this makes sense.
![image](https://user-images.githubusercontent.com/3241376/65849942-39ca8180-e312-11e9-9eea-222b29e82158.png)
![image](https://user-images.githubusercontent.com/3241376/65849946-3e8f3580-e312-11e9-803e-bcad31227b1e.png)

**Comment by Dawson1917** [comment]
Not a bug, but it is a bit silly

**Comment by bloons3** [comment]
I assume that the jetpack is controlled via mouth?

**Comment by Dawson1917** [comment]
Jetpacks just work by magic and don't require any extremities to control it

**Comment by bloons3** [comment]
what's stranger is that I can spacewalk (moving while next to a solid surface) with no limbs (and jetpack empty)

**Comment by AnonymousNow** [comment]
>Using a jetpack with no limbs
It'd make sense for a jetpack to be usable by leaning into the desired location with the torso, considering that these jetpacks are usable with items in each hand.
>Spacewalking around hull without limbs
Yeah, that's wonk as hell. Consistency issue.

**Comment by Learner10** [comment]
So rather then going through the trouble of giving them new limbs... it's just easier to cut off gravity so they can move again. Gotcha.
