### ISSUE TITLE
Machines are inconsistent (Which ones can be made and Sprite construction wise)

### ISSUE THREAD

**Issue by Jalleo** [tgstation/tgstation#4683]
Updated: 
There are two sections to this issue:

- [ ] Part 1:
The sprites for making machines are inconsistent and very basic and dont really make great sense e.g. put in board and a couple of vending parts and you get a bright shiny vendor....

- [ ] Part 2:
You cant make all machines take the vendors as prime example you can only make the generic vendors and the bartenders vendor.
The youtool, The Vendomat, Both botany vendors, All variants of the NanoMed Plus, Smart Virus storage, smart slime extract storage, the smartfridge, SecTech, (Sustenance Vendor possibly), EngiVend and Boda

**Comment by Dorsisdwarf** [comment]
@Jalleo This issue is one-part "muhrealisms" and one part complaining about balance. You're not supposed to be able to get more of most non-produce vending machines.
