### ISSUE TITLE
TGUI interfaces do not load for IE 8 clients

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#46847]
## Reproduction: tgui interfaces do not load. Using IE 8 on wine.

This is pretty recent, I suspect actionninja's changes?
![Screenshot_20191002_195858](https://user-images.githubusercontent.com/35031555/66069342-746d2d80-e54f-11e9-8714-b226ff40a82c.png)

**Comment by stylemistake** [comment]
I'll try bisecting actioninja's changes to see what caused it.
