### ISSUE TITLE
Crusher hiero trophy wall does not block ash drake fire attack

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#46855]
Not sure if intended or not, but the fire spray attack from drake goes through the hiero trophy wall which is supposed to be impassable for all except yourself.

**Comment by Dawson1917** [comment]
Ash drakes have a bug where their firebreath passes over things it really shouldn't, like through windows

**Comment by ExcessiveUseOfCobblestone** [comment]
what if their firebreath is said to pass through everything 😏

**Comment by Sealed101** [comment]
hiero trophy no longer makes a mary sue wall as of
- #66793
