### ISSUE TITLE
Birdboat spam. Birdboat refuses to eat the detective's flask.x101

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#46863]
## Reproduction:
Birdboat refuses to eat the gold cup.x22
Birdboat refuses to eat the gold cup.x41
Birdboat refuses to eat the gold cup.x21
Birdboat refuses to eat the gold cup.x12

**Comment by nemvar** [comment]
Cursed birb

**Comment by nemvar** [comment]
Dupe of https://github.com/tgstation/tgstation/issues/45030
