### ISSUE TITLE
Grab resist cooldown issue

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#46873]
You can attempt to resist out of grabs with the resist button, or by attempting to move. However, they appear to have separate cooldowns, allowing you to resist with twice the frequency if you both move and press resist.

To reproduce, get aggressive or higher grabbed, do both at once. You will get two resist attempts at once.

**Comment by ShizCalev** [comment]
relevant procs: `/client/proc/Process_Grab()`, `/mob/living/verb/resist()`, and `/mob/proc/resist_grab()`

**Comment by kingofkosmos** [comment]
Something that would check if a do_after or do_mob is already in progress, would be beneficial in other scenarios as well.

**Comment by SuperNovaa41** [comment]
I think this has been fixed
