### ISSUE TITLE
Can't perform dissection on simplemobs

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#46877]
## Testmerges:
#46764: 'tgui-next: Initial PR, speedy new Air Alarm interface.' by stylemistake at commit d8e48494db

## Reproduction:
1. Spawn lusty xenomorph maid with xenobio golden extract
2. Kill with hand drill
3. Lay on table or floor
4. Apply drape and choose dissection if lay on floor or experimental dissection on surgical table with computer.
5. Try all tools > yo just hitting poor dead maid with surgical tools both simple one and advanced
6. Operating computer shows no operations in progress

**Comment by Dorsisdwarf** [comment]
Doesnt it only work on carbon mobs?

**Comment by kopoba** [comment]
> 
> 
> Doesnt it only work on carbon mobs?

Well im not sure but dissection works on xenoqueen from lavaland ruins. I think they are same as maid simple_animal https://github.com/tgstation/tgstation/blob/df1fecc58c6d5ef3fdb5275264460c7b20b52bf1/code/modules/mob/living/simple_animal/hostile/alien.dm

**Comment by Ty-the-Smonk** [comment]
Maid isn’t a xeno, she’s just a simplemob

**Comment by kopoba** [comment]
> 
> 
> Maid isn’t a xeno, she’s just a simplemob

Maid is 
/mob/living/simple_animal/hostile/alien/maid
and Xenoqueen from lavaland ruins
/mob/living/simple_animal/hostile/alien/queen/large

**Comment by ExcessiveUseOfCobblestone** [comment]
I added support for living dissection but it seems like there wasn't support for living mob surgery to begin with :omegalol:

**Comment by Fikou** [comment]
> I added support for living dissection but it seems like there wasn't support for living mob surgery to begin with :omegalol:

dont slimes have surgery

**Comment by ExcessiveUseOfCobblestone** [comment]
yes but it's specific to slimes

**Comment by kopoba** [comment]
@ExcessiveUseOfCobblestone any progress?

**Comment by ExcessiveUseOfCobblestone** [comment]
havent ever gotten around to it 😟
