### ISSUE TITLE
Old tgui interfaces do not load properly for IE 8 clients.

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#46888]
## Round ID: 120705, Terry.

 Testmerges: #46764: 'tgui-next: Initial PR, speedy new Air Alarm interface.' by stylemistake at commit d8e48494db 

"Expected identifier, string or number (http://127.0.0.1:52085/tmp505/tgui.js line 1)"

For station intercoms, APCs and several other interfaces. I think all interfaces based on old tgui are affected. Plain HTML and tgui-next interfaces work.

**Comment by Cyprex** [comment]
I tested this locally without tgui-next by checking out a80f4bc (#46858). That made it stuck on loading... instead of the "Expected identifer..." stuff above.

**Comment by Cyprex** [comment]
Fixed as of b595da7 in tgui-next, testing on latest in tgui-next right now.

**Comment by optimumtact** [comment]
please report these on the test merge prin the future thanks
