### ISSUE TITLE
standing up in crates

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#46886]
You can stand up in crates
consistency

**Comment by kriskog** [comment]
You can also lie down in lockers.

**Comment by cacogen** [comment]
Bodies go into lockers. Would be neat if when closed, corpses changed to standing and when opened they fell down.

**Comment by Tharcoonvagh** [comment]
if someone makes a fix pr for this and it gets merged my life will be happier

**Comment by PKPenguin321** [comment]
I feel like this really isn't an issue

**Comment by Tharcoonvagh** [comment]
ok

**Comment by cacogen** [comment]
It's an inconsistency issue because to close them you need to be prone but then standing in them is possible without opening them

**Comment by Tharcoonvagh** [comment]
ok

**Comment by Tharcoonvagh** [comment]
Fixing it would require a discussion, closing
