### ISSUE TITLE
As a borg, cannot interact with silicon airlock gui

### ISSUE THREAD

**Issue by zkxs** [tgstation/tgstation#46894]
Issue reported from  Round ID: 120728 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1485

![image](https://user-images.githubusercontent.com/1807509/66249573-1a10d000-e6fb-11e9-870c-f32cda36284c.png)

The power status buttons work. Nothing in the Access & Door Control section works.

**Comment by Cyprex** [comment]
#46764 Possibly related, @actioninja

**Comment by stylemistake** [comment]
Oh yeah, this is an old UI with new backend format, no shit it doesn't work.

**Comment by angryisosceles** [comment]
I'd like to add that this bug happens to AIs as well, and that the door control button works (but none of the other access buttons)

**Comment by Cyprex** [comment]
Fixed by 
1a08139 I believe, which is live on terry, what server was this on angryisoceles?

**Comment by angryisosceles** [comment]
Sybil

**Comment by Cyprex** [comment]
The testmerge has since been updated, this should be fixed now.

**Comment by angryisosceles** [comment]
Sweet!
