### ISSUE TITLE
Getting cloned while Obsessed gives you a second, new obsession without clearing your old objectives

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#46890]
## Round ID:
120706

## Testmerges:
Can't tell cause THE SERVER WON'T STOP CRASHING ARRRRGH

## Reproduction:
Be Obsessed
Die
Get cloned
Cry when you get your new Obsession and all your progress up 'til now is invalidated

**Comment by Fikou** [comment]
@tralezab owo

**Comment by Dorsisdwarf** [comment]
should be a feature that you get an obsession with the first person you see tbh

**Comment by Detective-Google** [comment]
still a bug as of round 122363
