### ISSUE TITLE
Failing incision breaks tend wounds surgery

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#46920]
Testmerges:
#46640: 'Surgery now goes slower before failing' by PKPenguin321 at commit 5613476f27 
#46383: 'Tabling Rework' by actioninja at commit 94b776f043 
#46764: 'tgui-next: Initial PR, speedy new Air Alarm interface.' by stylemistake at commit ca0205ae25 

1. Do surgery on someone on the floor
2. Fail the scalpel step once
3. Succeeding afterwards won't advance the surgery to the next stage, doesn't give a success message, can't use neither scalper or hemostat to advance surgery, only mend with cautery.
Also worth nothing that failing this stage doesn't seem to do damage.

Bugged surgery: https://prnt.sc/pffd40
What it should look like: https://prnt.sc/pff9d8

**Comment by Time-Green** [comment]
This happened to me aswell yesterday, I kinda forgot about it

**Comment by ExcessiveUseOfCobblestone** [comment]
dunno if it's testmerge or not, I don't remember having this issue pre-testmerge but would like to doublecheck

**Comment by Mickyan** [comment]
I doublechecked on local it's not a testmerge bug

It probably just became a lot more obvious due to the missing surgery chance for stasis beds and floor surgery chances being rock bottom so it's happening very frequently

**Comment by Learner10** [comment]
Oh yea, I think I do remember something like this. It's happened from time to time when I've done it on stasis beds.
