### ISSUE TITLE
Simple mobs vore stuff they drop

### ISSUE THREAD

**Issue by Shapsy** [tgstation/tgstation#46932]
Round ID: 120871
BYOND Version: 512.1484
Server revision compiled on: 
Master commit: 88e618080c5c227dce5ad16269ef4efba57ebdfb
The following pull requests are currently test merged:
#46764: 'tgui-next: Initial PR, speedy new Air Alarm interface.' by stylemistake at commit d8e48494db

Local commit: 021ca04d4e0e06ade976231f39913276b0999ae6
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:

Dexterous simple mobs like dex stands and drones apparently consume anything they pick up and drop. The items disappear and cannot be interacted with, but they stay in the simple mob's contents and will continue following the mob around.

To reproduce:
1. Be a drone or dex stand or whatever else has hands
2. Pick things up
3. Put them down
4. Thing is now gone

**Comment by PKPenguin321** [comment]
Probably dropping to the item loc instead of the mob loc
