### ISSUE TITLE
Bubblegum doesnt naturally spawn on lavaland

### ISSUE THREAD

**Issue by FreshestSoup** [tgstation/tgstation#46943]
Bubblegum doesnt spawn roundstart on lavaland anymore. Every round ive played as miner for the past month, I haven't seen bubblegum, and others have also noted he isnt spawning. First time making an issue, sorry if I screw anything up.

## Reproduction:

1. Start a new round
2. Check a GPS and find there is no bloody signal, and no bubblegum on lavaland.

**Comment by Learner10** [comment]
This is mega important. We need our Arena shuttles.
