### ISSUE TITLE
Clowns are slippery

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#46969]
## Reproduction:
Kill a clown wearing the PDA
Walk over it
Slip

Also works if you fireman carry a clown, then swap places with people.

@Qustinnus probably another edge case of #46301, not caught by #46520

**Comment by Moonman121** [comment]
I thought it was a feature

**Comment by Qustinnus** [comment]
Intended

**Comment by Qustinnus** [comment]
Oh wait the fireman thing isn't but the rest is

**Comment by Qustinnus** [comment]
Edit the issue to only contain the actual bug so this isn't lost

**Comment by kriskog** [comment]
How is a resting clown being slippery intended? It's mega dumb.

**Comment by 81Denton** [comment]
Should have been caught by #46520, odd

**Comment by fludd12** [comment]
Clowns secrete banana extract when threatened

**Comment by Qustinnus** [comment]
You step on them and on what they're wearing
