### ISSUE TITLE
Atmospherics once again breaks the laws of physics with negative electricity

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#46962]
## Round ID:
120966

## Testmerges:
#46764: 'tgui-next: Initial PR, speedy new Air Alarm interface.' by stylemistake at commit 07cb01c340 

## Reproduction:
I wouldn't even know where to begin but I have this picture 
![image](https://user-images.githubusercontent.com/12382984/66387729-78b8a100-e9bc-11e9-87bd-5a41b24602b4.png)
All I know is, it broke powernets so badly that they couldn't even move power around and the white HTML text box was supposed to be a cannister

**Comment by Ghilker** [comment]
Hello again, i did the TEG, but i still dont understand very well why it happened
Ok so, i made a fusion canister 
![Cattura2](https://user-images.githubusercontent.com/42839747/66388001-7ad32d80-e9c5-11e9-94c0-81bd81190fcf.PNG)
The temperature is pretty high, near the maximum (e31) that the code allow
after i attached the canister to the teg setup 
![Cattura4](https://user-images.githubusercontent.com/42839747/66388140-cb4a8b00-e9c5-11e9-9750-f767d5298e28.PNG)
it instantly went bonkers 
![Cattura5](https://user-images.githubusercontent.com/42839747/66388165-d69db680-e9c5-11e9-96a7-71fd13463419.PNG)
and suddenly the power stopped in all the station as seen above
this is the pipe that did output from TEG 
![Cattura3](https://user-images.githubusercontent.com/42839747/66388264-01880a80-e9c6-11e9-9361-afe835121535.PNG)
this is the fusion canister after a while i connected it to the TEG 
![Cattura1](https://user-images.githubusercontent.com/42839747/66388292-11075380-e9c6-11e9-9d87-6bcaed91ccc1.PNG)
as you can see the canister says its full (the green dot on it) but in reality is empty
so this not only break power, but also gas code

**Comment by Ghilker** [comment]
Ok so i wanted to test the weird empty but full canister by breaking it, i made the room outside atmos safe for this kind of experiment and used a spear to break it
![Cattura7](https://user-images.githubusercontent.com/42839747/66389337-6fcdcc80-e9c8-11e9-82e6-a127a4b7f0ea.PNG)
This is the result of standing (and slipping) in the canister tile 
![Cattura6](https://user-images.githubusercontent.com/42839747/66389351-7e1be880-e9c8-11e9-8648-8101118aea47.PNG)
this is also not spreading further as is staying in its contained tile

**Comment by Ghilker** [comment]
After this i took a canister and hooked it to the layer manifold, filled it with the weird stuff and took it in the safe room 
![Cattura10](https://user-images.githubusercontent.com/42839747/66389816-950f0a80-e9c9-11e9-9618-530625622ae9.PNG)
after i opened it with the spear it instantly spread from the broken canister 
![Cattura8](https://user-images.githubusercontent.com/42839747/66389862-aa843480-e9c9-11e9-8fc9-b0e36cde270e.PNG)
and all tiles in the room where like this
![Cattura9](https://user-images.githubusercontent.com/42839747/66389955-df908700-e9c9-11e9-9684-195bf87dbaf9.PNG)

**Comment by stylemistake** [comment]
@Anonmare can you reliably reproduce this setup? I want to see how these numbers are being represented in JSON, because that white box is certainly a JSON parsing error. I can give you a special javascript file to swap in your BYOND cache to see more detailed logs.

**Comment by stylemistake** [comment]
And as of indeterminate numbers and NaNs, it's a problem with fusion in general, and it existed for a very long time.

**Comment by stylemistake** [comment]
Here's the file, unzip it, and place into `Documents/BYOND/cache/tmpXXXXX` folder, then try reopening the canister UI.
[tgui.bundle.js.zip](https://github.com/tgstation/tgstation/files/3702100/tgui.bundle.js.zip)

**Comment by 81Denton** [comment]
@as334 @cyclowns

**Comment by yoyobatty** [comment]
http://www.byond.com/forum/post/1973047 This may point you in the right direction

**Comment by cyclowns** [comment]
what in the hell

**Comment by 81Denton** [comment]
Thanks for checking

**Comment by Anonmare** [comment]
@stylemistake Not my set-up, I dsicovered it after the fact

**Comment by Ghilker** [comment]
my set-up

**Comment by stylemistake** [comment]
@Ghilker just copy and replace this js file in your BYOND cache which is located at `C:/Users/<user>/Documents/BYOND/tmpXXXXX`,once replaced, it will print a lot more debug data on error.

**Comment by TheVekter** [comment]
Here a bit late but is it possible it has something to do with him having some astronomically high pressure in that can or is that normal?

Also could be related to #47703

**Comment by stylemistake** [comment]
It's just an inherent problem with fusion, because it uses astronomical numbers which are at the limit of float precision, so you get infinities very quickly, and if you put this into a machine which does even more maths, you can get division by another infinity and get a NaN, which in turn poisons absolutely everything it touches.

So you should either live with this bug, or rework fusion (yet again), or add NaN safeguards to all atmos machinery (which is a lot of work).

As for tgui, 513 will feature a proper serialization of NaN and Infinity, and tgui will no longer break when parsing these numbers.

**Comment by AtlasRules** [comment]
what in the goddamn
