### ISSUE TITLE
Phobia quirk resets every round

### ISSUE THREAD

**Issue by YakiAttaki** [tgstation/tgstation#46960]
## Reproduction:
Chosen phobia in the phobia quirk resets basically every round.
Select phobia quirk, play one round, check on "Setup Character" in the next round, it will have reset to the original phobia, which I believe is "spiders".

**Comment by ATH1909** [comment]
I think this bug and the bug that I reported are related: https://github.com/tgstation/tgstation/issues/46914

**Comment by YakiAttaki** [comment]
> I think this bug and the bug that I reported are related: #46914

I have noticed that too, kinda frustrating that every round I have to fix my markings and my phobia

**Comment by RaveRadbury** [comment]
This is still an issue.
