### ISSUE TITLE
Dropping items as a drone disappears them

### ISSUE THREAD

**Issue by Albrektson** [tgstation/tgstation#46963]
Repro:
- spawn as derelict drone from spawners menu
- pick up an item in left or right hand
- drop it

The item will fail to be placed on the ground, but disappears from your inventory.
Testing with glowsticks or flashlights will keep their glow attached to you, but otherwise with the same results as above.

**Comment by nemvar** [comment]
Fixed in https://github.com/tgstation/tgstation/pull/46926. Just needs some time until it hits the servers
