### ISSUE TITLE
Slitting someone's throat prevents you from attacking them

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#46998]
with sharp weapons, on harm intent, even on targets other than the head. Other intents and non-sharp weapons work fine.

**Comment by PKPenguin321** [comment]
@Fhaxaris

**Comment by Fhaxaris** [comment]
god damnit i am not at my my computer right now

**Comment by Fhaxaris** [comment]
should probably return COMPONENT_ITEM_ATTACK at the end of the proc, i am the big stupid

**Comment by Fhaxaris** [comment]
@py01 Does it print anything in chat? Because then I think I know what the problem is

**Comment by cacogen** [comment]
seems fair
