### ISSUE TITLE
Material Datum has caused Catastrophic Game Balance

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#46991]
Issue reported from  Round ID: 121035 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1484

I'll put this into two easy to read sections for the sake of helping categorize just how poorly tested this change was.

Uranium:

Anything made from uranium inherits the uranium's radioactive properties based on how much uranium it took to craft that item. The more uranium, the more contamination the item has. This causes objects made from uranium sitting next to one another to start contaminating each other and eventually reach lethal levels of radiation. This includes things like spare parts, most advanced tools, most advanced weaponry out of the security protolathe, among other objects. This also includes all the miner upgrades and also, their nightvision goggles. This means you can be carrying objects that constantly spew radiation and many of these objects make next to no sense as to why they would do this in a processed state.

Plasma:

Most everything made from plasma is either quite flammable or a fucking bomb. This includes things like experimental welders, nightvision meson goggles, donksoft vendor refills (these are made from a significant amount of plasma and uranium so they're both very explosive and very radioactive), spare parts, plastitanium sheets (????) among other objects. This means you can have small to large scale explosives on you without even realizing because they just so happened to be printed with plasma. This means objects you wouldn't think to be volatile explosives are volatile explosives.

For those not in the know, this PR is the culprit: https://github.com/tgstation/tgstation/pull/46525

**Comment by kriskog** [comment]
....it actually makes stuff made out of uranium from the protolathe radioactive? Who thought that was a good idea.

**Comment by Ty-the-Smonk** [comment]
Uranium walls do the same thing

**Comment by necromanceranne** [comment]
Apparently @Qustinnus.

What did I tell you about radioactive contamination? And you went and added sizable amounts of radioactive contamination to every object made from uranium? I gave you that heads up a month in advance to be absolutely certain you didn't end up including means of spreading radioactive contamination because of objects made from uranium.

Lemme break this down for you so you can under what is happening in a practical sense. The round I have listed here had most of the station hit the late game and print their gamer gear and upgrades as standard. But then everyone. EVERYONE started dying of radiation. Because all that gear uses uranium. The roboticist made a durand and had 4000 rads out of the blue because his spare parts and the mech itself were made from radioactive material, and continued to be radioactive after construction. I then went to security and printed off an ion carbine, a energy crossbow and a x-ray rifle. They're all radioactive out the arse, especially the x-ray rifle. In addition to this, these objects sitting near each other increased their contamination. Two single sheets of uranium could increase up to lethal radioactive contamination and there are logs in this round to prove it. The durand chasis hit 500. A sheet of uranium his like 1.2k.

I then started testing out objects made from plasma and lo and behold they're explosive. If you didn't upgrade the lathe, they were even MORE explosive because they used more material. I used several donksoft vendor refills in one place and they ended up blowing equivalent to high explosive. No dev range thank goodness but it would have killed just about anyone in the vicinity not in a bomb suit (which I was, as the spec ops suit is a bomb suit). Platitanium sheets are for some reason also explosive.

This is why testing is important. Because in the span of one round we get a nice little snapshot of how devastatingly destructive this PR was implemented into the game. If this isn't the PR to absolutely be pushing for more scrupulous testing of large scale balance changing PR's, then I don't know what would be.

**Comment by FancyCyclops** [comment]
Jesus. Christ.

**Comment by Qustinnus** [comment]
The radioactivity on crafted items from the protolathe shouldn't be happening, it could potentially have to do with differen't sources of crafting I'll check up on that.

**Comment by Qustinnus** [comment]
@necromanceranne dont act in such bad faith. This is a bug not an intended feature, if you actually read anything I wrote you'd know that. I removed radioactivity from ore, I never intended protolathe / mech fab things to have the material effects. and ore literaly doesnt have radiation.

Can you not realize that things can be bugged?

**Comment by ExcessiveUseOfCobblestone** [comment]
It was tested for quite a while 😏

**Comment by 81Denton** [comment]
Fixed in #46994
