### ISSUE TITLE
No camera in surgery B

### ISSUE THREAD

**Issue by Archanial** [tgstation/tgstation#47002]
This area is kinda new and probably not having camera wasn't indended. I don't see point in not having it here.

**Comment by nemvar** [comment]
which map?

**Comment by Archanial** [comment]
Metastation

**Comment by Dorsisdwarf** [comment]
Eh, I didnt bother putting a camera in there because the station is pretty heavily surveiled anyway and you get a bit of coverage through the windows

**Comment by Archanial** [comment]
Just a bit isn't enough I think. I'm not sure you can even see the surgery table. I don't see reason to not put a cam here.

**Comment by nemvar** [comment]
Intended as per statement of the author. Feel free to change this or yell at someone long enough that they do it for you.
