### ISSUE TITLE
Putting floor tiles in a protolathe gives 2000 of that material instead of 500.

### ISSUE THREAD

**Issue by CRITAWAKETS** [tgstation/tgstation#47004]
## Reproduction:

Just take a sheet out of the protolathe, turn it into 4 floor tiles, put it back in the protolathe and watch as 3 extra sheets of material appear.

https://i.imgur.com/qmIU1W4.png

floydmats was well tested

**Comment by PKPenguin321** [comment]
@Qustinnus
