### ISSUE TITLE
Explosion logging is way too verbose

### ISSUE THREAD

**Issue by Shapsy** [tgstation/tgstation#47005]
## Round ID:
Round ID: 121074
BYOND Version: 512.1484
Server revision compiled on: 
Master commit: e49ebbbd8788896cbc9b8d8b79a440e471fe53e8
Local commit: b11d0a6c130b451b7ae9db1f9d6471b55cb27d12
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:

Explosion logs are acting really weird and I think are creating new lines for each tile affected by an explosion (note the somewhat iterative numbering on the coords mentioned)

Step 1: be admin
Step 2: thing explodes
Step 3: logs!
[![dreamseeker_2019-10-09_21-12-46.png](https://i.imgur.com/rS1Y4Eu.png)](https://i.imgur.com/rS1Y4Eu.png)

**Comment by Cyprex** [comment]
Floydmats is to blame, close and reopen if it keeps happening in a few days.

**Comment by ExcessiveUseOfCobblestone** [comment]
That's the only thing I can think off that may have touched explosions recently

**Comment by ExcessiveUseOfCobblestone** [comment]
@Qustinnus

**Comment by 81Denton** [comment]
Plastitanium and plasteel sheet explode as (0, 0, 0.008, 0), which explains the spam. Something destroys one of those walls, which then drop a sheet that explodes. 
You can also destroy stacks of both with a welder, which is a little silly.

**Comment by Shapsy** [comment]
honestly i don't think admins care about any explosion sub (0,0,1), would it be feasible to add a minimum to show up in logs?

**Comment by Cyprex** [comment]
I considered that as well but that seems like it'd just hide the bug.
