### ISSUE TITLE
Lots of techweb points suddenly

### ISSUE THREAD

**Issue by Couls** [tgstation/tgstation#47016]
## Reproduction: I have absolutely no clue but I was told it was better to report this anyway

![image](https://user-images.githubusercontent.com/30060146/66618192-423e7a00-eba6-11e9-9f17-161a3f79a6dc.png)

**Comment by Whoneedspacee** [comment]
it's probably more likely someone figured out how to break the supermatter engine point generation through radiation bullshit than something number wise went wrong here tbh

unless theres some other method of point gen that isnt capped

**Comment by Putnam3145** [comment]
Could just be chadmos making 3000 moles of hyper-noblium, since that only requires 60000 moles of nitrogen, 30000 moles of tritium and 6 terajoules of energy (which is trivial to get from fusion, actually).

**Comment by nemvar** [comment]
Yeah, this is probably some atmos fuckery. Someone should probably add logging to that.

**Comment by RaveRadbury** [comment]
NICE

**Comment by kriskog** [comment]
100% atmos memes
