### ISSUE TITLE
rechargers are very slow (?)

### ISSUE THREAD

**Issue by zeroisthebiggay** [tgstation/tgstation#47018]
Issue reported from  Round ID: 121148 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

Empty an energy gun and insert it into a disabler.
Notice a very long pause before it starts charging.
It recharges a little bit and then stops recharging.
Does this one or two times before recharging like normal. Not sure if bug.

**Comment by carlarctg** [comment]
probably time dilation

**Comment by zeroisthebiggay** [comment]
> probably time dilation

time dilation was low and the server wasn't lagging

**Comment by nemvar** [comment]
Potentially related to https://github.com/tgstation/tgstation/issues/47021

**Comment by TheBonded** [comment]
have not seen this happen, marking as cleanupflagged unless confirmed to still be an issue
