### ISSUE TITLE
Throwing an intravenous medicine bag full of reagents will spill it

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#47011]
## Round ID:
Various

## Testmerges:
N/a

## Reproduction:
Get an intravenous medicine bag
Fill with medicine
Yeet that sucker across the room
Laugh with tears of agony in your eyes as you watch your precious sryriniver go down the proverbial drain

**Comment by Anonmare** [comment]
Seeing as IV bags have the spillable flag se to FALSE, there's a bug here somewhere

**Comment by willox** [comment]
They're only able to be spilled until you seal them with alt-click

**Comment by nemvar** [comment]
k
