### ISSUE TITLE
Monkey cubes can be used twice via toilet

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#47013]
See title: two monkeys per cube via shitter magic.

## Reproduction:

1. Obtain monkey cube and go to dorms.
2. Dunk monkey cube in toilet.
3. The power of the poop water fills the monkey cube, creating a monkey without destroying the cube. The cube is considered 'full', and can't be used on toilets again.
4. Use cube on sink for second, less shitty monkey.

**Comment by nemvar** [comment]
Not this shit again.

**Comment by fludd12** [comment]
Stupid band-aid solution that might have some merit: Make monkey cubes have a maximum reagent capacity of 5u, and fill it with liquid gibs, for easy access to soaps.
