### ISSUE TITLE
blind spell perma blinds the target

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#47020]
eye healing chem wont work

**Comment by Tlaltecuhtli** [comment]
it seems it gives you the blind mutation instead of timed eyeblind like it did a while ago ?

**Comment by PKPenguin321** [comment]
Probably caused by https://github.com/tgstation/tgstation/pull/46729

@Couls

**Comment by Couls** [comment]
on it

**Comment by ATH1909** [comment]
> Probably caused by #46729
> 
> @Couls

Actually, I think that this issue/bug was caused by me: https://github.com/tgstation/tgstation/pull/46092

**Comment by Couls** [comment]
Yeah I guess the refactor of blindness actually uncovered that it was broken
