### ISSUE TITLE
Carrot Juice blinds you permanently.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#47022]
Issue reported from  Round ID: 121179 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1484

As the title. Apparently carrot juice is not very good for your eyes.

**Comment by Couls** [comment]
WHAT

**Comment by Couls** [comment]
my bad, I didn't know it didn't automatically close it if you listed multiple PRs
