### ISSUE TITLE
Mechs can't use multi-z stairs

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#47023]

**Comment by nicbn** [comment]
You mean ladders right?
It'd be a cool feature if mechas couldn't climb up ladders but could climb up stairs

**Comment by Cyprex** [comment]
No, stairs, a player said that on comms, I haven't actually tested this myself.

**Comment by optimumtact** [comment]
if you haven't tested it why did you file it

**Comment by Qustinnus** [comment]
@optimumtact Honestly, A lot of people refuse to report issues but just complain about it on Discord, and then some people are just actually pro-active enough to file it for them.
