### ISSUE TITLE
You can't arrest fugitive monkeys

### ISSUE THREAD

**Issue by Jimmius** [tgstation/tgstation#47047]
## Reproduction: try to put a fugitive monkey into the capture machine

Fugitives can turn themselves into monkeys via genetics, and this prevents the capture machine from arresting them, even though they're fugitives for all intents and purposes. I'm not sure if this is a bug or a feature, but it doesn't seem intentional, so I thought I'd report it. EDIT: fixed the formatting

**Comment by itseasytosee** [comment]
this is a feature this is the whole point of the lings lesser form which turns them into a monkey

**Comment by Jimmius** [comment]
i don't think you understand what the issue is. I'm talking about the midround antags called fugitives, and the very specific interaction between them and the "capture machine" that the fugitive hunters get. Read the bug report instead of making a guess based on the title

**Comment by itseasytosee** [comment]
that does make a lot more sense are they unable to see them as fugitives if they are monkeys?

**Comment by Jimmius** [comment]
they can see them, they have an orange badge. but if they stun them, cuff them, and drag them over to the machine, attempting to put the money into the machine will result in "you cannot put that in the capture machine!" or words to that effect. The monkey still has the fugitive status in their mind, and the other fugitives and hunters are able to see it. 
The only way to capture the monkey is to turn them human again, at which point the capture machine will accept them.

**Comment by Qustinnus** [comment]
monkeys are human now so this is fixed
