### ISSUE TITLE
Alien Alloy deconstruction no longer gives you the option to manufacture it

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#47044]
Title, as stated.

Previously it was possible to create alien alloy by deconstructing it using the destructive analyser, and then using a fairly hefty amount of materials to create sheets of the alloy. However, deconstruction of the alloy in a recent round did nothing, with no effects reported. IIRC it didn't even offer to reclaim materials.

Sybil, presumably ongoing.

EDIT: It's worth noting that you CAN get the research node required to make alien alloy from alien medical tools, but not alloy itself.

**Comment by nemvar** [comment]
Fairly certain you actually need to research the node you unlock before you can print it.

**Comment by AnonymousNow** [comment]
> 
> 
> Fairly certain you actually need to research the node you unlock before you can print it.

No such node is marked during deconstruction. Nothing was marked during deconstruction, actually.

**Comment by tralezab** [comment]
We need someone to test if this is actually a bug or a problem with poor feedback. either way, it should get some attention
