### ISSUE TITLE
Supply ordering window stuck open

### ISSUE THREAD

**Issue by Edesau** [tgstation/tgstation#47051]
I find that when I open the supply window (the ones in cargo bay), each subsequent time I open the window it makes its way further up the screen until I can't move it or close out of it anymore and am forced to walk around with it until it disappears. Eventually I can't even call the cargo shuttle or access the equipment it's migrated so far up.

**Comment by Iatots** [comment]
Might be related, for me the energy monitoring program (default program on engineering modular console) spawns too high up by default. Resizing it does not help, and dragging it around is impossible.

**Comment by actioninja** [comment]
Now clamped, shouldn't be an issue anymore
