### ISSUE TITLE
Plasteel Explodes (only a little), causing R-Walls to spam explosion logs when blown up

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#47063]
Blow up the supermatter while as an admin and see the fun for yourself. This is so severe that if it hits enough r-walls it can cause client crashing.

**Comment by necromanceranne** [comment]
This affects admins most severely, but any mass explosion will result in admins being hit with an absolutely insane amount of log spam, not to mention the test site also gets hit with log spam which sends a ridiculous amount of reports to the chat causing in-game spam on top of that.

@Qustinnus Please fix this one ASAP. It's because plasteel is made form plasma, no doubt.

**Comment by Qustinnus** [comment]
Dupe but I'll fix it today
