### ISSUE TITLE
Falling onto the SM crystal from above does not dust you.

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#47068]
## Reproduction: 
1. Go to the open space one Z level above the SME
2. Make a tile on the tile besides the one directly above the SME
3. Step onto the open space above the SME
4. You are now ontop of the SM crystal without being dusted.

![image](https://user-images.githubusercontent.com/38219334/66716517-cbd09080-edce-11e9-9450-f6c31694294e.png)

**Comment by TheChosenEvilOne** [comment]
this happens also when you use disposals to get objects on the same turf, they don't get dusted.
