### ISSUE TITLE
Objects placed on a wall will show up on the floor besides openspace one Z level above

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#47072]
## Reproduction:
1. Place air alarm
2. Make openspace above the tile the air alarm is 'placed on'
3. Go up one Z level
4. Go stand besides the tile you just placed.
5. Air alarm shows up on the floor

![image](https://user-images.githubusercontent.com/38219334/66719895-faae2d00-edf5-11e9-94c7-3da82cca35c7.png)

**Comment by Time-Green** [comment]
That’s a very nasty one to fix, since it’s a flaw in the basic way that the wall machinery works.

**Comment by Jalleo** [comment]
We need to rework how these items are done which means either looking at byond logic or having specific SS13 coding to resolve this.
Currently the items are just placed with a dir and a large offset to put them over the other tile.
