### ISSUE TITLE
Multi-Z issues

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#47075]
- Making a hole in an upper floor that has a lower open segment (i.e a room) only makes generic space. This requires you to make upper-floor baseturfs openspace and means players can't do any real room projects that span more than one floor in-game.
- No visual indicator of lower structures in space (i.e seeing the 'ceiling' of the lower level's floor/wall).
- Moving up/down as a non-ghost doesn't work anywhere (space, openspace, in no-grav, ect).
- Telecomms doesn't work on different floors without additional setups.

**Comment by FloranOtten** [comment]
>Can't build lattice over openspace.

Actually, you can. As shown here, we built a bunch of floors on top of the openspace above the bar.

![image](https://user-images.githubusercontent.com/38219334/66722153-787c3380-ee0a-11e9-8fc6-9d48d916894b.png)

**Comment by Dorsisdwarf** [comment]
>Making a hole in an upper floor that has a lower open segment (i.e a room) only makes generic space. This requires you to make upper-floor baseturfs openspace and means players can't do any real room projects that span more than one floor in-game.
 this is related to the fact that multiZ doesnt really have any concept of a ceiling yet, and the issue of "invisible atmos leak from above" hasnt been worked through yet

**Comment by timothymtorres** [comment]
> 1. Making a hole in an upper floor that has a lower open segment (i.e a room) only makes generic space. This requires you to make upper-floor baseturfs openspace and means players can't do any real room projects that span more than one floor in-game.
> 2. No visual indicator of lower structures in space (i.e seeing the 'ceiling' of the lower level's floor/wall).
> 3. Moving up/down as a non-ghost doesn't work anywhere (space, openspace, in no-grav, ect).
> 4. Telecomms doesn't work on different floors without additional setups.

How many of these still exist?
