### ISSUE TITLE
Purrbation is Purrmanent

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#47070]
Nya!

Basically the purrbation button doesn't reverse/remove turning you into a felinid. Or adding cat ears and tail. Nyoops!

**Comment by nemvar** [comment]
feature

**Comment by nicbn** [comment]
bruh just make the purrbation button permaban the admin without any chance for appealing

**Comment by py01** [comment]
where is the purrbation button? I'm assuming this is separate from mass purrbation, since that seems to work

**Comment by Tharcoonvagh** [comment]
just remove felinids already

**Comment by necromanceranne** [comment]
@py01 Purrbation is in View Variables's dropdown menu.

**Comment by PepperPrepper** [comment]
By the looks of things the actual code that handles singular purrbations is in felinid.dm. not in datums.dm

**Comment by TheVekter** [comment]
I can't reproduce this. Might've been fixed at some point.

**Comment by dragomagol** [comment]
Seems to have been fixed
