### ISSUE TITLE
Getting creampied twice makes you immune to further creampieing.

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#47106]
Reproduction:
Throw a cream pie at someone
Wait for them to get back up
Cream pie them again
Face cleans off, and further pies will not cream them
Shower to reset and lose the immunity

Something wonky with #46496?

**Comment by PKPenguin321** [comment]
My money's on the dupe mode of the component being wrong

**Comment by Tharcoonvagh** [comment]
( ͡° ͜ʖ ͡°)

**Comment by Krysonism** [comment]
I know from my research that this is not at all realistic.
