### ISSUE TITLE
swarmers not eating rods

### ISSUE THREAD

**Issue by Timonkeyn** [tgstation/tgstation#47108]
Reporting client version: 512.1485

some round on sybil like 5 Hours ago, swarmers couldnt eat metal rods, thats literally all i have to say. they cant eat metal rods

**Comment by Cyprex** [comment]
Round ID please.

**Comment by Timonkeyn** [comment]
i dont think that matters

**Comment by spessbandit** [comment]
this is probably due to swarmer ex_act runtimes

**Comment by Angustmeta** [comment]
Autolathe couldn't eat metal rods either

**Comment by CRITAWAKETS** [comment]
Its from material datums. Quist fixed that iron rods duplicated iron but also made them undeconnable by accident. I am not even sure how that did not get found while testing.
