### ISSUE TITLE
Rocks on the Z level below will spill over onto the one above

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#47102]
Reproduction:
1. Make a multi Z map
2. Make a lower Z level contain rocks
3. Place openspace above the rocks one Z level above
4. It will now spill over

![image](https://user-images.githubusercontent.com/38219334/66818535-c04fa780-ef3d-11e9-82e8-ae665e4a5211.png)

**Comment by Jalleo** [comment]
Related: https://github.com/tgstation/tgstation/issues/47072
