### ISSUE TITLE
artificial bluecrystals can no longer be turned into raw bluespace mineral

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#47104]
https://monosnap.com/file/cFxNRuE3Hbm5hDFIY7OEEzymOoluBN

121473
@Qustinnus

**Comment by Fikou** [comment]
**WALL
LIZARDS**

**Comment by Tlaltecuhtli** [comment]
yes it was intentional

**Comment by kriskog** [comment]
Not anymore its not

**Comment by Tharcoonvagh** [comment]
WAIT WHAT I ACTUALLY SAID THE LIZARD THING
[Common] Mathias Corvin says, "WE NEED TO BUILD A WALL
[Common] Mathias Corvin says," FROM THE MONEY OF LIZARDS
