### ISSUE TITLE
rods dont have material datum

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#47118]
The metal rod does not contain sufficient materials to be accepted by the autolathe.x7

@Qustinnus

**Comment by nemvar** [comment]
Dupe

**Comment by Timonkeyn** [comment]
Fr*ck you brick that was my issue I want my tendies back

**Comment by LetterN** [comment]
this might been fixed, pr: #47163

**Comment by Coconutwarrior97** [comment]
This bug no longer happens.
