### ISSUE TITLE
ORM and smelting machine void uranium, diamonds, bluespace crystals

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#47129]
## Testmerges:
The following pull requests are currently test merged:
#46968: 'Kilo Station' by Okand37 at commit 1e2a6f3d9f
#46887: 'fixes revs on dynamic not ending' by imsxz at commit 729702b8c7

## Reproduction:
1. Join as miner > mine
2. Dump ore to orm 
3. Ore disappeared no mats added to silo

**Comment by AnonymousNow** [comment]
Aha! I thought something happened. Was a free golem last round on Sybil (121556), and when I brought back a bunch of bluespace crystals in one mining round, they vanished and didn't take in the ORM. The ORM was linked via silo to a protolathe, if that's a factor, but still - absolutely zero bluespace crystals. Odd.

Only suggestions I have are that recently there seems to be a few issues with materials and machines - rods not having enough mats to fit into autolathes somehow, ash not being craftable into sandstone (a PR is up to fix this one etc.). Maybe there's some sort of cascading material error.

**Comment by nemvar** [comment]
We know pretty well what's going on with materials right now. The system is still in its baby shoes so some issues can be expected.
*Most* of them get fixed fairly quickly.

**Comment by TheMidnightRose** [comment]
Alright I have been poking at this for several hours now. Right now in small quantities and some times even the large quantities. The ores go into either a smelter or the ORM and vanish, they still however give points.

If you have a 50 stack of ore it works fine. Unaffected materials is Iron, glass, gold, silver. All others are affected by this, forcing Xenobio to have to produce plasma, and me to be the welding golem on sybil.

**Comment by TheMidnightRose** [comment]
This is also affecting Sybil, Terry, Bagil. I did not check Sybil 2, or either of the Event Halls

**Comment by AnonymousNow** [comment]
Thanks to the tireless efforts of a team of Free Golems working to better (and take over) the station, a workaround has been found.

Connecting an ore silo to the ORM and protolathe seems to allow all materials in all quantities to work as expected. Haven't yet tested if reconnecting the existing silo stationside works this way as well.

**Comment by kriskog** [comment]
This was fixed
