### ISSUE TITLE
Pipe fuckery

### ISSUE THREAD

**Issue by Ghilker** [tgstation/tgstation#47127]
Issue reported from  Round ID: 121557 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1488

![Cattura](https://user-images.githubusercontent.com/42839747/66938480-8667c980-f041-11e9-9006-5f77d9498012.PNG)

near the new chem factory zone

**Comment by nemvar** [comment]
Logs aren't out yet. Mind just telling me what map this is? I don't play.

**Comment by Ghilker** [comment]
meta, after the plumbing update

**Comment by Time-Green** [comment]
What the fuck

I’ll fix it this time tomorrow if no one beats me to it

**Comment by Ghilker** [comment]
@Time-Green also i think that there is a hole under a grille near this thing on the left

**Comment by kopoba** [comment]
![image](https://user-images.githubusercontent.com/5034345/66942379-04d06580-f05a-11e9-93de-c00f3c55deae.png)

**Comment by nemvar** [comment]
That hole is located where the soul used to be.
