### ISSUE TITLE
autolathe can print only 1 fluid pipe at time

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#47131]

**Comment by nemvar** [comment]
Feature request.

**Comment by Tlaltecuhtli** [comment]
time green said its a bug re open the case
https://monosnap.com/file/6gOaGdRLmZ7YESPP94aTSKz1hOB0uv

**Comment by Time-Green** [comment]
Yeah this is a bug. Or an oversight. Either way it's supposed to be printable in bulk
