### ISSUE TITLE
Cannot remove floor tiles in doorways

### ISSUE THREAD

**Issue by ReynTheLord** [tgstation/tgstation#47140]
## Testmerges: Master commit: 17ef8ffb63e1ad8b8feceabbd3d00e06a87531fa
The following pull requests are currently test merged:
#46968: 'Kilo Station' by Okand37 at commit 3fb67cb9a7
#47092: 'Da white kit nerf update: sutures and regen mesh.' by Krysonism at commit dc38ca2c67

**Comment by Dorsisdwarf** [comment]
Duplicate of #47139
