### ISSUE TITLE
Medical Maint Meta Tile is Missing

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#47167]
## Round ID: 121631

This might be as a result of a player but I've seen meta maint start breached for a few rounds and think this is the culprit. 

![image](https://user-images.githubusercontent.com/37246588/67043798-de153c00-f0f8-11e9-9ea1-b62810b720d6.png)

No tile under the grill.

**Comment by py01** [comment]
already fixed, #47134

**Comment by wesoda25** [comment]
I'm really too lazy to check if server was updated then, or to bother connecting now, so I'll just close and assume we're fine.
