### ISSUE TITLE
Apothecary shutters don't close properly

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#47160]
## Round ID:
121623

## Testmerges:
#46968: 'Kilo Station' by Okand37 at commit 3fb67cb9a7 
#47092: 'Da white kit nerf update: sutures and regen mesh.' by Krysonism at commit dc38ca2c67 

## Reproduction:
![image](https://user-images.githubusercontent.com/12382984/67024776-e2435880-f0fc-11e9-818a-b8a95afd87e4.png)

**Comment by tralezab** [comment]
i'd put good first issue too but nothing makes me want to leap into coding less than doing mapping work so i'll just leave it out

**Comment by Time-Green** [comment]
What’s wrong with them? They look closed to me

**Comment by Anonmare** [comment]
There's 6 shutters in that image that aren't closed but should be

**Comment by Time-Green** [comment]
oh, I didn’t know those existed
