### ISSUE TITLE
Pulse rifle has no on back sprite

### ISSUE THREAD

**Issue by PepperPrepper** [tgstation/tgstation#47173]
Tested with an offline build. Was a pulse rifle from an arcade machine if it matters

**Comment by TheVekter** [comment]
So that's the toy pulse you get out of the arcade, right? Can someone confirm if this happens with the one that spawns in the armory?

**Comment by ATH1909** [comment]
Wait a minute.

You actually WON A PULSE RIFLE FROM AN ARCADE MACHINE? You do realize that there is (only) an actual (as in, not exaggerated; this is _what's in the code_) one in a million chance to roll a pulse rifle as your prize from a vending machine, right?



> Can someone confirm if this happens with the one that spawns in the armory?

No pulse rifles spawn in the armory. Are you thinking of the ion rifle and/or the temperature gun?

**Comment by PepperPrepper** [comment]
@ATH1909 Haha what really? one in one million? I thought the chance was low but that low??? Ha well I guess it kinda sucks that I was just playing LAN with friends

**Comment by PepperPrepper** [comment]
I'm just thinking about all thing one in one million chance things I could have won in real life and it's really bumming me out

**Comment by optimumtact** [comment]
You've peaked my friend, it's all downhill from here

**Comment by necromanceranne** [comment]
You poor motherfucker.

**Comment by Shapsy** [comment]
f in chat

**Comment by PepperPrepper** [comment]
I might actually make the pulse rifle back sprites. It would be a fitting end to this sad tale

**Comment by PepperPrepper** [comment]
https://media.discordapp.net/attachments/326849939240124419/634743465359573023/bigpulse.png
Is this good enough or should I try again?

**Comment by Ty-the-Smonk** [comment]
I guess you got the jackpot medal now lol

**Comment by PepperPrepper** [comment]
I got it offline offline. so no hub

**Comment by Ty-the-Smonk** [comment]
Big F

**Comment by PepperPrepper** [comment]
#47195

**Comment by Magikarpet** [comment]
:joy:

**Comment by Grantteen** [comment]
congrats buddy you won the lottery now go do it for real 😄

**Comment by PepperPrepper** [comment]
> 
> 
> congrats buddy you won the lottery now go do it for real 😄

If only it was that easy
