### ISSUE TITLE
Cannot Retreive Sheets with Protolathe

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#47175]
## Reproduction:

Load up some materials in the protolathe, then go into its menu and try to eject the sheets; it won't happen.

The reason for this is some incorrect logic with retrieving materials that generates a runtime on something like this:

`cannot read "diamond".sheet_type`

**Comment by AnonymousNow** [comment]
Duplicate of #46170

I know, I did the same.

**Comment by kriskog** [comment]
@Qustinnus

**Comment by Detective-Google** [comment]
this only happens if you try and eject through the console if you use the machine directly it works as intended afaik
