### ISSUE TITLE
gun overlay didnt update

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#47185]
121683

click with laser 
*click*
icon is like fully charged

**Comment by nemvar** [comment]
Use! Full! Sentences! To! Explain! What! You! Are! Talking! About!

A! Precise! Description! Of! The! Problem! Tends! To! Make! It! Much! Easier! To! Fix!

Did the gun overlay ever update? Did you try recharging it? Did that change anything? Was the laser ever used before, if yes how? Was the gun put through any processes that appear unusual? Explosions maybe?
Or is this a general issue that applies to all lasers? If so, do you know if it also applies to other guns?

**Comment by Kaffe-work** [comment]
What laser is this about? did it have a light attached?

**Comment by Kaffe-work** [comment]
@Tlaltecuhtli more info needed please

**Comment by actioninja** [comment]
This is garbage and completely useless
