### ISSUE TITLE
You can no longer select body parts 

### ISSUE THREAD

**Issue by Moonman121** [tgstation/tgstation#47180]
## Round ID:
Round ID: 121677

## Testmerges:
#47092: 'Da white kit nerf update: sutures and regen mesh.' by Krysonism at commit c6a7a82214
#46968: 'Kilo Station' by Okand37 at commit 1e2a6f3d9f

## Reproduction:
Spawn in and try to select body parts other than the chest, clicking does nothing. It was also reported that using a defib while the chest was selected gave an error stating you need to aim at the chest to use it.

**Comment by necromanceranne** [comment]
This one causes a lot of the game to break down so holy fuck it needs a fix.

**Comment by FancyCyclops** [comment]
![image](https://user-images.githubusercontent.com/46296243/67094453-9e854780-f1ff-11e9-86b5-f2449d41b3c3.png)

**Comment by willox** [comment]
It's because `/obj/screen -> /var/datum/hud/hud` is never set for most screen objects (It's not really set for anything except hands and inventory bits.)

**Comment by ninjanomnom** [comment]
I'm working on a fix for this
