### ISSUE TITLE
Microwaves are broken again

### ISSUE THREAD

**Issue by Moonman121** [tgstation/tgstation#47181]
## Round ID:
Round ID: 121679

## Testmerges:
#47092: 'Da white kit nerf update: sutures and regen mesh.' by Krysonism at commit c6a7a82214
#46968: 'Kilo Station' by Okand37 at commit 1e2a6f3d9f

## Reproduction:
Place food in a microwave and turn it on, it will pop the cooked food out but the microwave doesn't turn off. 
Throws runtimes in microwave.dm line 312; cannot read null.len
Edit: placing a full box of donks in only returns a single cooked donk

**Comment by TheVekter** [comment]
Does this happen with any food or just Donk Pockets?

**Comment by Moonman121** [comment]
Tested with both donks and a meat slab, both broke it.
