### ISSUE TITLE
how to still get revived while shaded

### ISSUE THREAD

**Issue by Timonkeyn** [tgstation/tgstation#47201]
Issue reported from  Round ID: 121716 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1485

1. log off shortly before shaded
2. log in again after
3. tell your metabuddy to get head
4. get cloned, tell everyone Cult
5. profit

**Comment by Tharcoonvagh** [comment]
ho boy

**Comment by Kaffe-work** [comment]
o fug

**Comment by 81Denton** [comment]
fug

**Comment by 81Denton** [comment]
This seems to only really work if no ghosts sign up to play as a shade.

**Comment by kriskog** [comment]
Should make the mob uncloneable before the gibbing.

**Comment by mikaihl95** [comment]
Excellent
