### ISSUE TITLE
non-human mobs hit with a stun baton receive a confusion effect

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#47207]
"You muscles seize, making you collapse!" from related stun baton code gets triggered on mobs that this might not be intended on, giving movement confusion to mobs like holoparasites and xenos.

Doesn't necessarily need to be fixed, but probably wasn't intended.

**Comment by carlarctg** [comment]
flashes confuse holoparas too

**Comment by Timonkeyn** [comment]
Intended?

**Comment by kriskog** [comment]
Spoke with akrilla, intended. Text could be different but
