### ISSUE TITLE
Medbots in patrol mode tend to run away from patients after tending wounds 1 time

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#47214]
You have to chase after the medbot to get it to tend you wounds multiple times

**Comment by Timonkeyn** [comment]
Dupe

**Comment by Tharcoonvagh** [comment]
Dope

**Comment by kriskog** [comment]
I couldn't find a dupe?

**Comment by kopoba** [comment]
> 
> 
> I couldn't find a dupe?

https://github.com/tgstation/tgstation/issues/46919
