### ISSUE TITLE
one of the bible skins has no sprite in your inventory/is invisible

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#47217]
Round ID: 121742

I was a latejoin chaplain, and since we already had a chaplain in the round, my starting bible changed sprite to match theirs. I wasn't able to get the roundstart chaplain to tell me what skin they chose for their bible, but my bible's sprite in my inventory was invisible.

**Comment by kopoba** [comment]
also late join second chap have invisible bible admems confirmed that its also invisible for them Round ID: 141506
![Bible sprite bug](https://i.imgur.com/dglIH1N.png)

**Comment by timothymtorres** [comment]
Fixed by #54323
