### ISSUE TITLE
Cannot remove camera upgrades

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#47224]
# Reproduction:
Upgrade a camera with prox sensor or analyzer
Try to crow bar them out, fail

There is code for it in crowbar_act

**Comment by nemvar** [comment]
If there is code for it in crowbar_act I can't find it

**Comment by kriskog** [comment]
You know what, the code I saw is in camera_assembly's crowbar_act, and works until the final step. As soon as you finish it, it turns into a macinery/camera, and from then on does not work.
Anyway, since we can add these in the camera state being able to remove them would be sensible but maybe it isn't intentional?
