### ISSUE TITLE
Telekinesis leaves fingerprints

### ISSUE THREAD

**Issue by itseasytosee** [tgstation/tgstation#47239]
Interacting with objects (say an ai upload board) at long range with TK leaves fingerprints and glove fibers

**Comment by Tharcoonvagh** [comment]
And you get dusted when you touch the SM
Tk is inconsistent as fuck

**Comment by Teepeepee** [comment]
the SM fries your brain though, you don't get dusted (unless I'm misremembering)

**Comment by XDTM** [comment]
yeah tk with sm is intentional

**Comment by optimumtact** [comment]
prettu sure this is all intended

**Comment by kriskog** [comment]
Leaving glove fibers using tk doesnt seem intended.

**Comment by ATH1909** [comment]
Reminds me of the magical traces that mages can leave behind whenever they cast spells in Shadowrun.

**Comment by optimumtact** [comment]
im pretty sure it was a concession to the detective, I swear to god I remember this conversation in like 2013/2014

**Comment by spessbandit** [comment]
fortunately no one ever does detective work anymore

**Comment by MCterra10** [comment]
Please don't make TK + Camo more overpowered than it already is

**Comment by Learner10** [comment]
This kind of reminds me of Elfen Lied powers in that they were in a sense invisible hands. Seems interesting if they left handprints.

**Comment by itseasytosee** [comment]
but glove fibers?
