### ISSUE TITLE
Cremating a holoparasite kills the host but doesn't dust them

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#47238]
No description needed

Issue reported from  Round ID: 121813 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

**Comment by itseasytosee** [comment]
I don't see why it should dust them bust that seems like an unadded feature, not a bug

**Comment by PKPenguin321** [comment]
It's supposed to dust them

**Comment by itseasytosee** [comment]
is there code for it that is not working?

**Comment by PKPenguin321** [comment]
https://github.com/tgstation/tgstation/blob/c38a7a3bb59259953562de6a5e05d9d898941585/code/modules/mob/living/simple_animal/guardian/guardian.dm#L148
`/mob/living/simple_animal/hostile/guardian/Life() //Dies if the summoner dies`
...
`summoner.dust()`

**Comment by nemvar** [comment]
Yeah... summoner.dust() should probably be called from Death instead of Life...
