### ISSUE TITLE
breaking a wrenched canister causes it to stay there not existant for ever

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#47249]
121844

break a wrenched to port canister, watch bugs happen

**Comment by Qustinnus** [comment]
what the fuck tlalt

**Comment by Qustinnus** [comment]
`causes it to stay there not existant for ever`

does anyone here speak this foreign tongue?

**Comment by TheVekter** [comment]
Tlalt, can you please do everyone a favor and put forth some effort on your bug reports? Reproduce it, screenshot what's happening so we can better figure out what the problem is.

**Comment by TheVekter** [comment]
Tlalt can we get a screenshot or something please or some kind of effort so we can fix this

**Comment by Kylerace** [comment]
i havent seen this happen in the last year (actually ever)
