### ISSUE TITLE
Food Dupe Glitch

### ISSUE THREAD

**Issue by exvlusiv** [tgstation/tgstation#47258]
Issue reported from  Round ID: 121864 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1488
I was making Fish Fingers on the Whiteship. I only had 2 carp filets but could continue Crafting till i had about 5.
No idea how it happened it stopped at 5 Craftings.

**Comment by kriskog** [comment]
Can't reproduce this. Crafting UI also received a facelift, which might have alleviated some multicrafting issues related to lag.
