### ISSUE TITLE
Cargo supply console UI no longer works right, cant order crates

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#47266]
When you open a supply console, the list of things you can purchase quickly vanishes, leaving nothing but an empty screen under Catalog. Also affects the request console

Issue reported from  Round ID: 121879 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

**Comment by kriskog** [comment]
Same on local
