### ISSUE TITLE
Security helmets with an attached seclight still emit light when the seclight is turned off

### ISSUE THREAD

**Issue by Moonman121** [tgstation/tgstation#47270]
## Round ID:
Round ID: 121883

## Testmerges:
#46968: 'Kilo Station' by Okand37 at commit 1e2a6f3d9f
#47058: 'Adds achievement datums' by Qustinnus at commit bca7f8c270

## Reproduction:
Attach a seclight to a security helmet
Turn it on and off
Drop it on the floor to see it emit light

**Comment by HomocidlePancakes** [comment]
It’s like that with a lot of stuff. Hardsuits when they are on the ground but helmet is on, guns with lights on them, lights that are in bags and etc.

**Comment by ArcaneMusic** [comment]
After the lighting changes as of recent, it doesn't really seem like a bug at this point, especially now that they carry over directional lights onto the dropped object, as well.
![image](https://user-images.githubusercontent.com/41715314/99888734-e9e90100-2c1c-11eb-8e2b-0a4406f01002.png)
If I'm mistaken, feel free to comment and re-open.
