### ISSUE TITLE
Cargo console shows nothing in the catalog

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#47273]
## Testmerges:
#46968: 'Kilo Station' by Okand37 at commit 3fb67cb9a7

## Reproduction:

1. Try to use cargo computer
2. Fail miserably
3. Job change to Miner

The cargo computer is basically useless. Trying to use it shows the right menu for half a second before everything disappears from the catalog. I tried deconstructing and reconstructing the console, no dice. This happens with both the one in the cargo bay and the one in the lobby.
![M8ngPQrXls](https://user-images.githubusercontent.com/7019927/67184076-8997e800-f3a8-11e9-87a9-23717dcc167e.png)

**Comment by actioninja** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/47268 server need to update.
