### ISSUE TITLE
[!IMPORTANT!] cargo console ui broken [!IMPORTANT!] 

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#47275]
when you open the console  the  text disappear and all you can see is this 

https://monosnap.com/file/POb3XZ6lNJsWJ5lCbH1B9L2Pg5IQZP

121894

**Comment by Tharcoonvagh** [comment]
happens with some uis too like pandemics
This may be a dupe tho

**Comment by Tharcoonvagh** [comment]
Oh wait it's fixed nvm
