### ISSUE TITLE
Game can choose players that are not on station z-level as revheads

### ISSUE THREAD

**Issue by Archanial** [tgstation/tgstation#47283]
Issue reported from  Round ID:  121914 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Both revheads were miners on lavaland. Round ended instantly. Game should ignore people that are not on station when rolling revheads.

Reporting client version: 512.1471

**Comment by PKPenguin321** [comment]
Needs to check that they are on the station z-level here: https://github.com/tgstation/tgstation/blob/26801414e2ac6037d9b4d059d5eb2a589e408d97/code/modules/antagonists/revolution/revolution.dm#L290

**Comment by Tharcoonvagh** [comment]
Pepsiman0 was Johnny Joestar the Shaft Miner and survived while fleeing the station!

**Comment by kriskog** [comment]
> 
> 
> Needs to check that they are on the station z-level here:

This is a dynamic issue, where rev assignment is delayed. I have already added a check for this in  #47100, but in the case where all headrevs are ineligible it would just fail silently since the round no longer ends on rev death.

**Comment by Archanial** [comment]
> the round no longer ends on rev death

Isn't that a huge buff to revs?

**Comment by kriskog** [comment]
If they lose, the revolution is over. No coming back from that.

**Comment by PKPenguin321** [comment]
I had read the OP as this being a latejoin revhead problem (as new revheads are created if a head of staff latejoins, which would be the only way for a revhead to be created off-station in a normal rev round). If you're sure this is a dynamic issue then go for it I guess

**Comment by TheChosenEvilOne** [comment]
The game can't just ignore people not on station as the revolution ruleset is roundstart, which means the antagonists are chosen roundstart and not during the round (midround).
