### ISSUE TITLE
Destructive analyzer is unable to work

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#47296]
Items can be placed in the destructive analyzer and you can go to the analyzer from the RnD console but there is just a blank screen, meaning you cant analyze anything placed in it

Issue reported from  Round ID: 121940 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

**Comment by kriskog** [comment]
Works fine on my local.

**Comment by TheChosenEvilOne** [comment]
Only happens with items without materials because the UI is missing a check if custom_materials is null
