### ISSUE TITLE
Transformation sting is almost incurable

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#47297]
## Reproduction:
1. Be transform stung
2. Notice and fail to validhunt the stinger
3. Retreat to genetics to get a new UI+UE
4. Revert back to stung identity eventually (????)
5. Try to find other ways to cure, fail
I don't know for sure but the way the code works not even green slime transformation may be enough to cure it

![image](https://user-images.githubusercontent.com/53100513/67253411-e4374f80-f44d-11e9-86af-631c705c4ffa.png)
nothing here implies, to my mediocre code reading skills, that the sting must be incurable, so i feel it's a bug (and a really annoying one at that)

**Comment by carlarctg** [comment]
accidental 2 second ic oc no ban pls

**Comment by HomocidlePancakes** [comment]
Why should it be “curable”.? Just wait until next round to nya around, gee.

**Comment by Tharcoonvagh** [comment]
Ui+UE was hecked for me a few months ago, it reverted after 5 mins

**Comment by PKPenguin321** [comment]
Sounds like UI+UE injectors are temporary for some reason

**Comment by Time-Green** [comment]
They've always been temporary. Just step in the machine and ask someone else to apply it directly

**Comment by PKPenguin321** [comment]
That's an odd choice

**Comment by PKPenguin321** [comment]
Oh but that being said, this isn't a bug
