### ISSUE TITLE
Stasis beds do not halt Xeno impregnation

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#47304]
Seems like an oversight, but apparently being in a stasis bed doesn't do anything to halt the progress of Xenos gestation despite being in complete stasis. Could be due to balance reasons but I found this interesting enough to report it.

**Comment by TheVekter** [comment]
If this isn't actually a thing blame Pugie, he told me about it <.< >.>

**Comment by Ty-the-Smonk** [comment]
I’m pretty sure this was intended

**Comment by nemvar** [comment]
Probably my fault.

**Comment by HomocidlePancakes** [comment]
Makes sense to me. It’s a parasite, not an infection. And stasis kinda negates any danger of being hugged

**Comment by nemvar** [comment]
This is a bug.

**Comment by HomocidlePancakes** [comment]
Does it halt regular diseases then?

**Comment by nemvar** [comment]
Yes

**Comment by TheVekter** [comment]
Ayyy, I was useful. Thanks, nemvar.
