### ISSUE TITLE
Wraiths cannot walk z level down

### ISSUE THREAD

**Issue by Archanial** [tgstation/tgstation#47310]
Issue reported from  Round ID: 121978 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Not sure about other constructs, but I was stuck as a wraith.
https://imgur.com/a/JtddoM3

Reporting client version: 512.1471

**Comment by TheChosenEvilOne** [comment]
Pretty sure you can use the Move-Down verb (it is in the IC tab)
