### ISSUE TITLE
Antag Randomization still lets you lock features, so you can give yourself antag tells (also I think it makes you human)

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#47328]
You can make yourself obviously a roundstart antag by locking every feature except one feature, like hair colour, to give yourself a blatant antag tell. 

I feel like this is potentially a hilarious feature but it is also completely against the spirit of the antag randomization option, which is supposed to reduce metagaming people who roll antag a lot.

**Comment by kriskog** [comment]
It really shouldnt be able to make non-humans human, as it doesnt touch species stuff at all. I'll take a look later anyway.

As for locking, yes it is possible. Easy enough to disallow, although probably messy implementation.

**Comment by carlarctg** [comment]
i don't see how this is an issue

**Comment by wesoda25** [comment]
Basically its an issue cause I can be myself, but every time I am antag my hairstyle isn't bald. 

Its pretty metaey if people choose to "abuse" it that way, but any code solution would basically ruin the rest of the feature which is pretty lame. 

I think this would fall under administration.

**Comment by Twaticus** [comment]
i mean dont you have to go out of your way to do this? you only have yourself to blame if you get meta'd for this

**Comment by necromanceranne** [comment]
Yeah pretty much. Though that being said becoming human as antag is also possible this way so THAT is actually more of an issue. Nonhumans becoming humans literally only at its most convenient  (IE when you want to make demands of the silicons) has issues.

**Comment by carlarctg** [comment]
it's possible not guaranteed

**Comment by kriskog** [comment]
I dont see any way it would cause a species change.

**Comment by tralezab** [comment]
administration can handle people abusing this
