### ISSUE TITLE
Launchpads can move anchored AIs

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#47331]
Briefcase Launchpads are especially easy replication for this. Hover the targeting reticle over the AI you wish to have deleted. Press pull. The AI is now on your briefcase. Which likely will be in space and therefore leaving them without a power source.

This is supposedly meant to have been fixed in this PR. https://github.com/tgstation/tgstation/pull/46646

Maybe.

**Comment by Ty-the-Smonk** [comment]
AI is a mob so they probably weren't considered during that pr, and I think the AI anchor just makes them impassible

**Comment by GunHog** [comment]
The AI "anchor" just makes makes it harder to move. Relevant code:
https://github.com/tgstation/tgstation/blob/6b1161ecd91d5ee014ee6d9b39dac699cc284a9a/code/modules/mob/living/silicon/ai/ai.dm#L343-L347

**Comment by spessbandit** [comment]
the problem with going off move_resist is that there are many things that are at or above VERY_STRONG, some of which are "teleportable", namely:

- Goliaths
- Goliath/hivelord/general monster dens
- Statues
- Jungle seedlings
- Legionnaires
- Megafauna
- Revenants

**Comment by PKPenguin321** [comment]
Time for a MOVE_FORCE_IMMOVABLE flag that will inevitably be outclassed
