### ISSUE TITLE
Removing the last reagent from the reaction chamber reagent list fails

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#47338]
## Reproduction:
1. Make a reaction chamber
2. List reagents it needs to obtain
3. Remove all reagents
4. Try to add a new one
5. The last reagent you clicked remove on will not vanish, and adding a new one causes an error message saying it was attempting to unrender an unrendered object. Closing and reopening the menu before adding a new reagent causes the first one to vanish and prevents the error.

**Comment by Time-Green** [comment]
Known bug that I just don't know how to fix. It's complete and utter magic.

Why does it magically work when closing and reopening? Why does it not update on a button press? I have no idea and I'll probably fix it by just updating the UI to tgui-next.

The 'unrender' thing I have heard of before, but never experienced myself.

**Comment by stylemistake** [comment]
Did tgui-next fix the issue? If so, we can close this.

**Comment by stylemistake** [comment]
Got fixed recently.
