### ISSUE TITLE
fantasy component 's summoning suffix can choose carbon mobs

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#47335]
which dont spawn

**Comment by kriskog** [comment]
Follow the template. Round ID missing, its relevant.

**Comment by kriskog** [comment]
I couldnt see why that would be on first glance of the code, it should support spawning carbons. If you had a round ID at least we could check for runtimes, but alas. Closing this, if you can supply repro steps or a round ID open a new issue.
