### ISSUE TITLE
Damage zone doll strange behavior

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#47346]
## Testmerges:
#46968: 'Kilo Station' by Okand37 at commit 1e2a6f3d9f
#46887: 'fixes revs on dynamic not ending' by imsxz at commit 729702b8c7

## Reproduction:
1. Midround join
1.2 Dont touch damage zone doll or intent
2. Humanize monkey or just grab anybody
3. Place dummy on surgical table/stasis bed/floor
4. Try to apply drapes 
5. Guillermo Beedell slapped Jayson Heckendora in the chest with the surgical drapes!
6. Try use defibs defibs. They saying that you must target patient chest

Fix is easy change damage zone on doll to any parts and back to chest and all works fine
@ninjanomnom

**Comment by spessbandit** [comment]
this actually happens because apparently humans (or any mobs I guess) spawn with zone_selected as null, which means that things that target zones don't work. obviously this goes away if you select a zone

**Comment by spessbandit** [comment]
specifically, it is caused by https://github.com/tgstation/tgstation/pull/47094/files#diff-9f1c2867cbf3fde9361a7b20e3144523R552
