### ISSUE TITLE
Ethereals might be immune to mass mindswap?

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#47345]
Issue reported from  Round ID: 122051 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1484

What occured was a mass mindswap but I noticed among the crew all the the ethereals were still walking about completely unaffected. There was enough of them that they would have been swapped.

Can we kill this event yet? Thank you.

**Comment by carlarctg** [comment]
time to main ethereal because fuck mindswap

**Comment by Tharcoonvagh** [comment]
elektrysk is not a real first name

**Comment by kriskog** [comment]
Affected when testing, can't reproduce
