### ISSUE TITLE
If you have Game Preferences open when you roll a random body, it will set those current preferences as your current character options in wherever isn't locked

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#47358]
Say you have Randomization when Antag on, you have the game preferences open to your current character. Whoops, you rolled antag this round! Now your character's randomization have replaced your previous character options.

**Comment by kriskog** [comment]
I made it load the old prefs when you reopen the window, and it will also do so if click your slot button again. This also used to apply to setting always random body on before, always replacing the slot with the new random character (but not saving). 

I could make it refresh those right after making the bodies, but that would increase the workload on roundstart and it's just not worth it.

**Comment by kriskog** [comment]
I meant to close this
