### ISSUE TITLE
weird stuff is happening with custom viruses

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#47359]
I tested out a virus on Bagil last round. It had both necrotic metabolism and inorganic biology in it, as seen in this screenshot: https://cdn.discordapp.com/attachments/509932988688105482/636764128073220096/virology_bug_one.PNG

It infected skeletons (and maybe inorganics? I don't quite remember) just fine, but it wasn't able to infect any living organic creatures, even when injected.

EDIT: Scroll down to my comment below; it details the TRUE bug at work here (it has nothing to do with the inorganic biology symptom or the necrotic metabolism symptom).

EDIT EDIT: My comment below does not, in fact, detail the TRUE bug at work here.

**Comment by ATH1909** [comment]
Note that I killed the lizardperson by beheading them, which *might* have something to do with it not affecting them while they were dead? I'm pretty sure that I saw another issue that mentioned something like that happening, though.

**Comment by nemvar** [comment]
Necrotic Metabolism doesn't actually allow you to infect dead people. It allows dead people to spread the virus.

Critical difference.

**Comment by Detective-Google** [comment]
Necrotic metabolism isn't meant to make you unable to infect organics.

**Comment by ATH1909** [comment]
OH MY GOD I FOUND THE BUG

```
/datum/species/lizard
	// Reptilian humanoids with scaled skin and tails.
	name = "Lizardperson"
	id = "lizard"
	say_mod = "hisses"
	default_color = "00FF00"
	species_traits = list(MUTCOLORS,EYECOLOR,LIPS)
	inherent_biotypes = MOB_ORGANIC|MOB_HUMANOID|MOB_REPTILE
```
LIZARDPEOPLE HAVE THE MOB_REPTILE FLAG, WHICH MOST VIRUSES DON'T HAVE IN THEIR LIST OF INFECTABLE BIOTYPES

LIZARDPEOPLE HAVE BEEN IMMUNE TO VIRUSES FOR FUCKING AGES AND NOBODY'S NOTICED

THE _ABSOLUTE STATE_ OF /TG/ VIROLOGY

I had forgotten to mention in the OP that the virus was stealthy, which is why it appeared to not have infected anyone else. The only person whose blood I tested in the pandemic was an SSD lizardperson's, hence why I thought that all living organic creatures couldn't be infected by my virus.

**Comment by ATH1909** [comment]
SO ARE MOTHS, FUCK

**Comment by ATH1909** [comment]
Wait, no, I just misinterpreted how bitflags work (again).

DAMNIT, this wasn't the problem.

**Comment by ATH1909** [comment]
https://github.com/tgstation/tgstation/issues/46892
https://github.com/tgstation/tgstation/issues/46408

These might be related to this problem.

**Comment by ATH1909** [comment]
From the Reddit thread that I linked to above (https://www.reddit.com/r/SS13/comments/dp2iri/where_did_i_fuck_up_with_my_virus/):

> KylerAce
> 1 point
> ·
> 4 hours ago
> **Yeah I had neutered necrotic Metabolism**, I hope it isn’t bugged because I don’t think there’s a way to hit all of comas thresholds and have contact transmission without it.

**Comment by ATH1909** [comment]
> 
> level 9
> KylerAce
> 2 points
> ·
> 2 hours ago
> Yeah it seems like I should have been infected by that, it keeps getting weirder. For future reference **I was a human.** It had neutered necrotic Metabolism, as well as fever shivering sneezing disfiguration all neutered. The only uneutered symptom was coma. **And actually I just made the exact same virus in another round and it’s working fine, must have been a weird bug. Actually the new one didn’t have necrotic Metabolism neutered so maybe it was that for some reason.**
