### ISSUE TITLE
milk still isn't fixed

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#47361]
milk doesn't deplete in skeletons and it doesn't heal them

god fucking damnit

**Comment by PKPenguin321** [comment]
Still? Even after https://github.com/tgstation/tgstation/pull/47267?

**Comment by PKPenguin321** [comment]
Okay I just noticed you're the author of that PR so I'll take your word for it

**Comment by Ty-the-Smonk** [comment]
ATA1909, the failed milk necromancer
