### ISSUE TITLE
Descending to a lower z-level and dragging something breaks grab.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#47376]
Imagine, not testing the both ways. Honk

**Comment by PKPenguin321** [comment]
>Imagine, not testing the both ways. Honk

reading this is like witnessing a text-based seizure

**Comment by HomocidlePancakes** [comment]
>reading this is like witnessing a text-based seizure

Imagine, this being the intended effect.

**Comment by Ty-the-Smonk** [comment]
Imagine, throwing someone downstairs

**Comment by Dennok** [comment]
You use stairs? Ladders work, with crates 100%.
