### ISSUE TITLE
Various Mech Combat Problems

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#47373]
I'm gonna say this is more to highlight something fairly powerful about mechs that seemingly don't see a whole lot of discussion but probably should and put it forth as something that may or may not be intentional. 

**Point Blank Punchshot**
Effectively right now mechs can punch someone and shoot them while they're close by spam clicking them, since punches and shooting the gun are entirely independent cooldowns. For weapons like the scattershot, this could be very close to a one-shot into crit given most combat mechs do somewhere between 20-30 damage and scattershot is 24 brute per pellet of four pellets.

Given mech punches are also a disable, this is quite a bit of power. 

**Mech Guns have Independent Cooldowns**
Even guns that are the same kind of gun work on separate cooldowns. You can bypass cooldowns for mech weapons by swapping into a new gun and continue shooting. By loading three of a kind (forgoing all utility which in my opinion is bad), the standard for combat mechs, you can fire much faster. Not too difficult to achieve quick weapon swapping either by simply moving the action button over the top of your mech. You're never going to be clicking yourself after all. This works well with the previous technique that also works on independent cooldowns.

**Mech Punches make EMPs partially redundant**
Not entirely redundant as they're still really solid when used to ping down a mech from range with complete safety. But since mech punches are able to smash down walls not much stops the mech man from just juking in behind cover and beating his way out through a few rooms until his guns are back and he can return fire. Half of mech combat is using cover intelligently to not get shot as much as possible, One of those methods is legitimately to Kool-aid Man through a wall when they approach after you and punching them down. So in that scenario nothing can stop them if they're already on top of you and punching you to the floor.

**Maulers are Wall Sharks**
In relation to the above effect, there is a thing with mechs with wall autopunches/wall phasing that makes them able to move considerably faster if they move diagonally through walls. Maulers have the ability to leap through into further diagonal tiles like a knight out of chess if they move diagonally. This means you can have the big combat mech suddenly LEAP at you and slap you on the floor, as Maulers autopunch when you move into people with harm intent. This is obviously a problem with diagonal movement and likely the same problem that was being seen with cardboard boxes.

**Comment by Rowelll** [comment]
~~intented~~

**Comment by Repukan** [comment]
Just remove them.

Why would a (((plasma research station))) need to produce nuclear grade, military outfitted giant robots

**Comment by AnonymousNow** [comment]
Also an issue - mechs seem to be immune to lightbreaker blades from Nightmares.

**Comment by zxaber** [comment]
I didn't want to do anymore mecha nerfs soon after the two I did before (EMP changes and ammo boxes), but it's been long enough. Maybe I should look into flat out removal of mech melee (perhaps have an equipment for it)
