### ISSUE TITLE
ablative trenchcoat toggle hood breaks armor icon

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#47381]
![b8b533efe8eb8bc58ae5da9eb3a53a44](https://user-images.githubusercontent.com/28164826/67534731-aaa05780-f68c-11e9-8154-8b249a211cdd.png)

also the sec-hud that the hood will give you does not give the visual overlay. Probably need to call update_sight() on the wearer

**Comment by carlarctg** [comment]
FUCK
