### ISSUE TITLE
particle beam rifle turrets

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#47399]
I don't know how to reproduce it, but appearently turrets with beam rifles as their weapon will not damage anything at all. It will make the people they shoot at scream, but that's all.
Bug originally discovered by @imsxz 
Testmerges:
#46968: 'Kilo Station' by Okand37 at commit 9da473aecf
Round happened on Terry, gamemode dynamic

**Comment by kriskog** [comment]
Could you add "in turrets" to the title please.

**Comment by imsxz** [comment]
nothing special to reproduce, build a turret, inserting the kevinz meme gun for the relevant step.

**Comment by Time-Green** [comment]
I never really considered it a bug. It's caused by the beam rifle not being charged by turrets and thus shooting blanks. It's alot of fun just placing one in the hallway and giving people heart attacks

**Comment by projectkepler-ru** [comment]
@Time-Green  this is no longer relevanat as particle beam rifle no longer exist

**Comment by Time-Green** [comment]
Good point
