### ISSUE TITLE
the RCD ore silo link upgrade doesnt function

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#47401]
1) insert advanced rcd upgrade into rcd
2) toggle silo link
3) try to build wall
4) notice that nothing happens
5) disable silo link
6) observe that your RCD only functions when the silo link is disabled

**Comment by Time-Green** [comment]
You need to actually connect it to the silo first, like with new techfabs.

**Comment by Kaffe-work** [comment]
you need to link it to the ore silo, you might wanna look at #47396 that "reworks" this.

**Comment by kriskog** [comment]
WhatT-G said, link it to silo with a multitool like anything else.
