### ISSUE TITLE
Cannot set target in BSA

### ISSUE THREAD

**Issue by Electronics** [tgstation/tgstation#47402]
Assemble BSA, enable BSA through keycards. Try to target something by pushing the target button -> does nothing.

![image](https://user-images.githubusercontent.com/422393/67611091-08b56380-f78f-11e9-9a16-de817a80bfe3.png)

```
Round ID: 122205
BYOND Version: 512.1484
Server revision compiled on: 
Master commit: ac20a47ff97653748c8a46e951f5315bc7c82ff1
The following pull requests are currently test merged:
#46968: 'Kilo Station' by Okand37 at commit 9da473aecf

Local commit: 2dd01611fc063a280a51b66eb81895e6e0177da1
Server tools version: /tg/station 13 Server v3.2.6.2
```

**Comment by AnturK** [comment]
@actioninja

**Comment by actioninja** [comment]
are you kidding me I couldn't get it to stop letting you pick targets before, I'll look into this.
