### ISSUE TITLE
Move link forum account to special verbs tab

### ISSUE THREAD

**Issue by Kaffe-work** [tgstation/tgstation#47414]
The connect forum button is in a dumb tab.

## Reproduction:

look at ooc tab, "link forum account" is there. this should probably be in special verbs tab instead.

**Comment by YPOQ** [comment]
Just so no one wastes time searching for this code: It's part of the [Server-Side Code Modifications](https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm) and not this repository.

**Comment by san7890** [comment]
yeah this issue report was never supposed to be filed here, if this annoys you please ask the /tg/station hosts to change it at https://tgstation13.org/phpBB/viewforum.php?f=45 (that seems to be the most applicable spot anyways)

**Comment by san7890** [comment]
honestly it'd probably generate more complaint to change it after such a long time lmao
