### ISSUE TITLE
Cannot see any ingame chat except binary as silicon/borg

### ISSUE THREAD

**Issue by wuggymcwuggy** [tgstation/tgstation#47415]
## Reproduction:

Start round as cyborg. Realize that I cannot see any chat except for binary. Profit. 

Fix chat command and reloading does not fix it.

Admeme had to fix it manually apparently.

**Comment by FancyCyclops** [comment]
[AND THEY DON'T STOP COMING AND THEY DON'T STOP COMING AND THEY DON'T STOP COMING AND THEY DON'T STOP COMING AND THEY DON'T STOP COMING AND THEY DON'T STOP COMING AND THEY DON'T STOP COMING AND THEY DON'T STOP COMING AND THEY DON'T STOP COMING AND THEY DON'T STOP COMING AND THEY DON'T STOP COMING AND THEY DON'T STOP COMING](https://youtu.be/eT3BFzSD6YY)
