### ISSUE TITLE
Medical consoles and fridges missing close button in UI

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#47411]
## Testmerges:
The following pull requests are currently test merged:
#46968: 'Kilo Station' by Okand37 at commit 9da473aecf

## Reproduction:
1. Open operating computer console
2. Cant close popup. No button and even moving away from it doesn't close it.(managed to close it by screwing glass from console)
2.1 And you cant move this popup or resize
3. Same crew monitoring console(handle crew monitor) and fridges except moving from them them force them to close popup

**Comment by AnturK** [comment]
Already fixed, servers need to update
