### ISSUE TITLE
Abaltive ternchoat

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#47418]
Typo:
Experimental trenchcoat specially crafted to reflect and absorb laser and disabler shots. Don't expect it to do all that much against an _**ax**_ or a shotgun, however.

**Comment by terranaut1** [comment]
It's alternative spelling, not a typo.
https://en.wiktionary.org/wiki/ax

**Comment by Tharcoonvagh** [comment]
Okay then
