### ISSUE TITLE
Straight Jackets can't be resisted out of

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#47428]
## Reproduction: 
Put on straight jacket
try to resist out
wait 5 minutes for progress bar to complete
nothing happens once bar is complete

I tried this with both straight jacket and cuffs and just a straight jacket. Neither can actually be resisted out of even after waiting 5 mins

**Comment by Timonkeyn** [comment]
Is this how houdini died???

**Comment by Time-Green** [comment]
This broke about 8 times now?

**Comment by PKPenguin321** [comment]
Probably a dupe

**Comment by willox** [comment]
old dupe, but this was caused by https://github.com/tgstation/tgstation/pull/45127 only allowing leg/hand cuffs to be removed.

**Comment by kriskog** [comment]
dupe of  #46379
