### ISSUE TITLE
Bag of Holding Bomb teleported people into Hilbert's Hotel

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#47425]
Issue reported from  Round ID: 122280 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1484

So, not entirely certain as to why or what happened but two people caught in a BoH Bomb got teleported to Hilbert's Hotel.

I mean, it makes sense I guess. And it's actually kind of cool. But I'm pretty sure this isn't intentional.

**Comment by ATH1909** [comment]
Did they survive?

**Comment by Dennok** [comment]
Anyway this outdated since BoH no more teleports.
And this not HH issue. This old BoH bombing issue.
