### ISSUE TITLE
with full blood, examining myself shows that i have "pale skin"

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#47430]
https://prnt.sc/pon80w

unless thats a trait of the albino skin tone or something. happened several rounds.

**Comment by Timonkeyn** [comment]
Are you an albino? That's a trait of them

**Comment by necromanceranne** [comment]
Cracker

**Comment by spessbandit** [comment]
deliberate https://github.com/tgstation/tgstation/pull/47261
