### ISSUE TITLE
Boxes of hugs have bruise packs/ointment

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#47444]
@Krysonism 

It's a type of maint loot and gotten from hacked medical vendors.
*/obj/item/storage/box/hug/medical* 
in *code/game/objects/items/storage/boxes.dm*

**Comment by triplezeta** [comment]
Isn't this intentional?

**Comment by PKPenguin321** [comment]
Afaik we're phasing out bruise packs and ointment so it's an oversight really

**Comment by Krysonism** [comment]
I left this in internationally to spice up the maint loot a bit. 

I won't be upset if the maintainers want to replace this spawn as well.

**Comment by PKPenguin321** [comment]
Alright
