### ISSUE TITLE
Plants in earthsblood trays still get taken over by weeds

### ISSUE THREAD

**Issue by Edesau** [tgstation/tgstation#47445]
Plants in earthsblood-upgraded trays get taken over by weeds, but you still get the "This plant is devoid of weeds!" message when using the cultivator with the weed/pest light flashing.

**Comment by HomocidlePancakes** [comment]
I suppose you had weed growth at 10, which would instantly replace any plant there was w/o giving a chance for the earthsblood to kill the weeds. Not a bug

**Comment by kriskog** [comment]
Sounds like a bug to me
