### ISSUE TITLE
liver wont die??

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#47448]
https://prnt.sc/poy8ar

at the time of this image, he had a constant source of liver damage from a chemical, which he was still processing, and had been at 100 damage for several ticks. didnt start taking toxin damage.

**Comment by kriskog** [comment]
Can't runtime if they never die

**Comment by ATH1909** [comment]
heroes never die

**Comment by 4dplanner** [comment]
fuck

**Comment by 4dplanner** [comment]
did he have any organ damage healing sources? the prevdamage 99.9 is suspicious

**Comment by 4dplanner** [comment]
Also, which chemical? Musiver deals such low damage that's the organ's regen overrides it.

**Comment by imsxz** [comment]
200u itching powder(a toxin reagent). All he had was itching powder and histamine.

**Comment by nemvar** [comment]
nothing wrong with prevdamage (except the actual reason why it exists). This probably has something to do with organ_flags not getting set correctly.

**Comment by TheBonded** [comment]
fixed in https://github.com/tgstation/tgstation/pull/62100
