### ISSUE TITLE
Discount traitor and nukie items

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#47452]
There are no discount items in the nukie and traitor uplink. Not sure if I was extremely unlucky, please try to reproduce it by trying to open the discount item tab. 
Happened several times over the past few days
edit: I left out a word god damit

**Comment by Cyprex** [comment]
Consistently happens on IE 8, there are actual discount items present, they're just not in the UI.

**Comment by kriskog** [comment]
tgui-next issue? @actionninja @stylemistake

**Comment by stylemistake** [comment]
Git blame shows there is a recent change in uplink's `ui_data`. Could be related.

https://github.com/tgstation/tgstation/blame/master/code/datums/components/uplink.dm#L151-L165

**Comment by actioninja** [comment]
![image](https://user-images.githubusercontent.com/5194834/67734039-3ed82a80-f9bd-11e9-9821-858d863e5074.png)
fuck

**Comment by Tharcoonvagh** [comment]
Nice
