### ISSUE TITLE
TASERS

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#47454]
You can deconstruct ai turrets for a free taser 
GOD DAMN RANGED STUNS

**Comment by 4dplanner** [comment]
🐙

**Comment by Tlaltecuhtli** [comment]
they also shoot when hulk 😂 😂 👌 💯

**Comment by nemvar** [comment]
Tasers are the memes of the soul

**Comment by necromanceranne** [comment]
I mean imsxz explicitly said in the PR to fix deconstructing turrets this was possible.

**Comment by SkeletalElite** [comment]
Bruh momment

**Comment by ATH1909** [comment]
The solution to this problem is to make hybrid turret guns unable to be fired "by hand" (in that case, you might also wanna remove them from the Summon Guns pool), I think.

**Comment by Kaffe-work** [comment]
...wait this was not known?

**Comment by Learner10** [comment]
> The solution to this problem is to make hybrid turret guns unable to be fired "by hand"

I also remember saying something like this. You could probably do it by making it weapon with a trigger that does not fit any creature. (Except maybe monkey. Taser monkeys sound hilarious.)

**Comment by Tlaltecuhtli** [comment]
make it spawn without a cell and add a desc that it needs external power to work

**Comment by TheVekter** [comment]
This might be soft wet brain but is there no way to refactor them to use a different item that doesn't count as an actual taser?

**Comment by Tharcoonvagh** [comment]
Make it so mobs can't use em

**Comment by Tlaltecuhtli** [comment]
https://github.com/tgstation/tgstation/blob/eec16e75c0b6e14376da93406321d19361c91d3c/code/modules/mob/living/carbon/human/human_helpers.dm#L143


culprit here gonna make a pr later

**Comment by Tharcoonvagh** [comment]
Thank god

**Comment by Qustinnus** [comment]
@Tharcoonvagh heya don't worry about closing issues until they're fixed. We'll close them at that point (because tlalt never ended up fixing it)
