### ISSUE TITLE
Can't wash clothing items in the sink

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#47451]
Issue reported from  Round ID: 122378 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

I'm not really sure why, but when I try to wash my shoes or my clothes in a sink, nothing happens.

Reproduce:
* Get bloody clothes
* Wash in sink

What should happen:
* Squeeky clean

What happens:
* Nothing

E: Oh, and the only test merge is Kilo

**Comment by TheVekter** [comment]
Might have happened in #47320, @defiantGrace do you mind poking this?

**Comment by GravitronBlue** [comment]
Pretty sure this is related to being unable to activate monkey cubes using a sink as well.
