### ISSUE TITLE
Vampires who get borged still have bat form and can use it to move while locked

### ISSUE THREAD

**Issue by spessbandit** [tgstation/tgstation#47469]
issue report from reyn, sorry if he's like goofballed, also I swear this is a dupe but couldn't find it

"I don't have access to github at this moment, so would you mind making a report on github for me?

Server: Terry

Revision: Unknown, Round was 122417

Problem Description: Borged Vamps can still use bat form as a borg, and can use it to move while locked.

What did you expect to happen: I... Didn't think that you'd keep the ability as a borg

What happened instead: I saw that the bat form ability was still available, used it, And Behold, Borg became bat, bat went back to borg

Why is this bad/What are the consequences: It's more than slightly silly, although if you want it to, You can keep it around. It's hilarious, but it's a bug. It might also apply to AIs

Steps to reproduce the problem: Get killed and cloned as vampire, then get killed, debrained, and borged. Kill and clone step may not be necessary.

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Nothing that I can tell. I started off locked as a borg, so... Eh? I wasn't a roundstart borg, mind you. Also, THIS NOTE WAS WRITTEN BY REYNTIME13, WHO COULD NOT ACCESS GITHUB"

**Comment by MCterra10** [comment]
Feature

**Comment by davethwave** [comment]
So basically we have potential for a rouge AI that can move by itself into a safer space and even flee into space and inhabit a random z zone to continue trolling it's victims if needed?

**Comment by tralezab** [comment]
borgs can cast all spells as long as they don't need robes, this is a feature.
