### ISSUE TITLE
ID from PDA to computer interaction still busted

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#47465]
## Round ID: 
This has happened on like 20 different rounds, I'm not able to log in right now but I'll reproduce later if need be

## Testmerges: 
Kilo station

## Reproduction:

- Store ID in PDA
- Slap ID computer with PDA
- Eject ID from computer
- Try to put it back in your PDA

The PDA still thinks it has an ID in the slot, so until you manually eject it and put it back in, you can't use it. It doesn't actually _duplicate_ the ID, it more like creates a ghost copy that goes away when you eject the one in your PDA. I recall @Rohesie doing something to fix this but I can't find the PR to save my life.

**Comment by Rohesie** [comment]
Duplicate of #46156
Being fixed in #47387

**Comment by TheVekter** [comment]
My bad, I thought it was already merged.
