### ISSUE TITLE
Arena shuttle bugged

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#47473]
Apparently arena shuttle just teleports people to space, so when i bought it it got replaced with the ayy shuttle, pls fix the real game shuttle

**Comment by necromanceranne** [comment]
Could you please add a round for this? Thank you.

**Comment by trexter555** [comment]
cant find the round id, but it was around 12 est on the 29th

**Comment by trexter555** [comment]
RoundID 122638, arena shuttle was bought and docked, the portals just teleported people to space.

**Comment by capn-monkeypaw** [comment]
This just happened again during round 130758 on the Events Hall.

Killed an enormous number of the crew.

**Comment by kriskog** [comment]
130758 had shuttle related runtimes, go check them out.
[18:06:38] Runtime in shuttle.dm,776: list index out of bounds

**Comment by trexter555** [comment]
hey guys guess what its still broken
