### ISSUE TITLE
Openspace turf is layered on top of objects and areas in Dream Maker

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#47483]
In Dream Maker, `/turf/open/openspace` is layered on top of objects and areas, which obscures them and makes editing openspace tiles a pain.

![openspace](https://user-images.githubusercontent.com/32391752/67882860-4590aa00-fb43-11e9-8ce9-d1a2d8c59f94.png)

**Comment by SpaceManiac** [comment]
should be as simple as changing the compile-time value of `layer` and/or `plane`
