### ISSUE TITLE
Goliath Broodmother Elites cannot spawn children or Speak.

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#47503]
## Reproduction:
Simple, be a ghost controled Goliath Broodmother, attempt to summon children against the miner you are facing, die because you cannot summon goliaths for assitance, Get revived by the miner and not be able to speak AND not be able to summon goliath children.

**Comment by kriskog** [comment]
@IndieanaJones

**Comment by IndieanaJones** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/47493
