### ISSUE TITLE
Walking down stairs shows falling message

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#47505]
When people walk over openspace turf that has stairs underneath, zFall() triggers and shows a `[A] falls through [src]!` warning message, even though they take no damage from this.

**Comment by ATH1909** [comment]
I TOLD YOU MAN

I TOLD YOU ABOUT STAIRS!

Note: I actually had nothing to do with the discovery/reporting of this issue, and in fact didn't even know we had stairs in the game until this issue report mentioned them.
