### ISSUE TITLE
Vampires blood level resets after entering and exiting bat mode

### ISSUE THREAD

**Issue by Couls** [tgstation/tgstation#47512]
can be used to basically sidestep the fact that you need to drain blood to survive

**Comment by davethwave** [comment]
That and it turns any damage you had even tox into brute and puts it ALL on chest for easy healing.

**Comment by davethwave** [comment]
This also purges any kinda of chem that the person had so to easily survive any kind of poisons, can get out of cuffs by turning into a bat, and purges all your rads by doing so.

**Comment by Couls** [comment]
holy crap

**Comment by JDHoffmann3** [comment]
Working on it.
