### ISSUE TITLE
Ebows Nerfed by Mining Skill; Miners are Master Arbalists

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#47521]
Due to the new mining skill, ebows, being a child of the PKA, are now hit with the massive cooldown nerf for being unskilled at mining. This means just about everyone but miners are dreadful with ebows. Meanwhile, roundstart miners are only okayish with ebows.

This difference is such that your opponent has a several seconds grace period between shots instead of the twoish as per normal. As such, ebows are practically dead in the hands of anyone but miners.

Come later in the round after they've been mining all that time with plasma cutters or whatever, the miners become gods with the ebow. As in, they have really small cooldowns. They can hold their own much more readily with an ebow than they would before skills and gain what is close to a near semiautomatic ebow. It's not QUITE that fast but it is fast enough to shoot just after the person stands up from the first bolt rather than a much more noticeable pause before they can fire again as it would normally. This makes them very powerful with ebows. And makes dual-wielded ebows a genuinely good option rather than just meme material. Alternating ebows basically makes them potentially unmatched in a firefight. God forbid the miner gets the full sized ebows.

**Comment by Whoneedspacee** [comment]
mining skill was a mistake

**Comment by nemvar** [comment]
shoutout to https://github.com/tgstation/tgstation/pull/47299.

gone too soon :crying_cat_face:

**Comment by ExcessiveUseOfCobblestone** [comment]
Don't think it was intended

**Comment by Taylorkills2** [comment]
Using plasma cutters doesn't make you better at mining, don't know if it's intentional. In fact the mining skill is a massive mess right now and doesn't seem to work properly with other things.

**Comment by Tharcoonvagh** [comment]
> skilsl were a mistake

**Comment by Qustinnus** [comment]
its not supposed to work with the plasma cutter.

**Comment by Qustinnus** [comment]
@Taylorkills2 instead of saying its a massive mess try to list the actual other things it doesn't work with, the only one thats actually relevant is the crusher afaik.

**Comment by necromanceranne** [comment]
Okay I'm pretty sure you gain no benefit from the skill too the plasma cutter. But I suggested a miner using one the entire round because that is the primary tool for mining a lot of rock at once other than the hierophant club. When I asked you how to gained experience in mining you told me it was through breaking rock. I imagine breaking rock with a plasma cutter grants experience, no?

**Comment by Qustinnus** [comment]
I also said it doesn't apply to the plasma cutter.

**Comment by Qustinnus** [comment]
the plasma cutter is stupid.

**Comment by Taylorkills2** [comment]
If you have any level of skill you can destroy things only a master miner can by using a KPA. Meaning miners can get 10 adamantine at round start(I've done this before less than five minutes into a shift)

If you have any level of skill and check what level of skill you have it only lists a - mark, giving you no indication what level of skill you have.
Ebow stuff
Crusher stuff
 Plasma cutter stuff(or lack thereof)

Pretty certain there's one more thing I'm forgetting.

**Comment by necromanceranne** [comment]
@Qustinnus So the plasma cutter doesn't grant experience because you don't like the plasma cutter despite it being a tool most miners utilize to mine.

I'm not sure what to say dude other than that's really not good game design at all. Just get rid of the plasma cutter, don't punish people unwittingly for using something you don't agree with.

**Comment by Whoneedspacee** [comment]
mining skill entirely is stupid anyways because it's broken for using the pka as a weapon, at max skill with full cooldowns it fires like every half second.

why does it even exist in the first place, the gameplay changes are negligable, it's tedious to get up, and filled with bugs like using the hierophant club to get max mining skill in like a minute.

skill being tied to grinding just feels like such a not ss13 thing idk

**Comment by necromanceranne** [comment]
I took a spin at speed running it. With a sonic jackhammer you can hit max very very fast. At that point the PKA becomes stupidly fast firing and you are almost certainly better off with damage or damage range mix because the dps is already considerably higher.

And oh yes I was super justified in the concerns because even if the ebow is fixed the baseline PKA cooldown after grinding mining skill becomes quite fast and so a normalized pressure PKA is actually now quite scary.

**Comment by Potato-Masher** [comment]
Why can't everyone just have the default mining speed, and miners get a slight roundstart skill boost? No gaining skill, just set in stone advantages for starting as a miner. Nobody loses, miners gain a little bit and also don't have the potential for making their PKAs ghetto autorifles just by destroying a lot of rocks (however, having a **chest loot** upgrade module that makes PKAs into ghetto autorifles isn't that bad of an idea come to think of it).

**Comment by Whoneedspacee** [comment]
because why should a job have a literal natural buff no other job does

**Comment by 4dplanner** [comment]
funny how the ebow/pka thing keeps causing problems

**Comment by ExcessiveUseOfCobblestone** [comment]
we have a check for it but no one uses it til after the fact 😏
