### ISSUE TITLE
Laser pointers don't respect eye protection.

### ISSUE THREAD

**Issue by nemvar** [tgstation/tgstation#47520]
## Reproduction:

1. Wear sunglasses
2. Get laser pointered in the face.
3. Flash overlay.

**Comment by HomocidlePancakes** [comment]
Only upgraded pointers do that, so intended?

**Comment by nemvar** [comment]
Only upgraded pointers have a chance to blind in general. Doubt that's intended. Closed anyways due to ambiguity
