### ISSUE TITLE
tgui-next: Missing interfaces

### ISSUE THREAD

**Issue by AWalton** [tgstation/tgstation#47528]
Some interfaces are not listed on the [tgui-next project page](https://github.com/orgs/tgstation/projects/3):
- Banning Panel
- View Variables
- Create Object/Mob/Turf

I've been having bugs with them lately running them in WINE but the tgui-next interfaces all work well, so I think simply bundling them into the redesign project would eliminate the bugs they have. That and it would maintain style consistency, as well as gain the other benefits like performance, maintenance etc.

**Comment by Cyprex** [comment]
Could you report the bugs in particular? I'm a /tg/station admin on wine.

**Comment by optimumtact** [comment]
this isn't a bug
