### ISSUE TITLE
"You grab Pete by their hands"

### ISSUE THREAD

**Issue by Ohagi-Chan** [tgstation/tgstation#47548]
## Round ID:
Issue reported from Round ID: 2326 (AuStation 13 [AUSTRALIA/OCEANIA][100% FREE LAG])

## Testmerges:
https://github.com/tgstation/tgstation/pull/47406

## Reproduction:
Grabbing pete in help intent, targeting hands procs the message "You grab Pete by their hands".
Pete does not have hands and I suspect that the same message will proc for any other mob or player that does not have hands either.

**Comment by Moonman121** [comment]
Feature?
