### ISSUE TITLE
Play Internet Sound is broken

### ISSUE THREAD

**Issue by spessbandit** [tgstation/tgstation#47546]
Round: 122787

## Reproduction:

Try to play internet sound via YouTube URL, get this:

Get message: Youtube-dl URL retrieval FAILED:

ERROR: Unable to download webpage:  (caused by URLError(gaierror(11002, 'getaddrinfo failed'),))

Try SoundCloud, get this:

Youtube-dl URL retrieval FAILED:

WARNING: Unable to download JSON metadata: 
ERROR: Unable to download JSON metadata:  (caused by URLError(gaierror(11002, 'getaddrinfo failed'),))

critical bug please fix

**Comment by SpaceManiac** [comment]
probably a problem with the servers

**Comment by spessbandit** [comment]
yeah it works now
