### ISSUE TITLE
Multi-deck power adapter issues

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#47555]
1) When a power adapter gets destroyed, it doesn't interrupt the powernet connection for its Z level or for any other power adapters that are chained behind it.
2) multitool_act() on an adapter that has no powernet connection runtimes with "Cannot read null.powernet" at:
https://github.com/tgstation/tgstation/blob/c847e852a510fbf04e6490d79ade79682c797990/code/modules/power/multiz.dm#L37
3) Power adapters can't be rebuilt by players when destroyed. Instead of getting completely deleted, it would be better if they switched to a broken state where they have to be repaired before they're operational again.
4) Very minor, but using a multitool on an adapter attacks it with the multitool.

@Kmc2000 If you have spare time, it would be great if you could have a look at this.

**Comment by actioninja** [comment]
The way these work is really stupid. They should just act on cut and place instead of processing like they do. I only merged it because at the time a multiz map was being worked on and they needed something to at least test things.

**Comment by Kmc2000** [comment]
what el fuck

I think I fixed this over on NSV, if that's the case I'll port that over
