### ISSUE TITLE
The Holodeck with safeties engaged doesn't run programs

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#47552]
If you attempt to run a program with the safeties on, the holodeck doesn't run programs at all. This is apparently not the case while emagged/while the safeties are off.

**Comment by ike709** [comment]
One line fix: https://github.com/BeeStation/BeeStation-Hornet/pull/705

**Comment by kriskog** [comment]
> 
> 
> One line fix: [BeeStation/BeeStation-Hornet#705](https://github.com/BeeStation/BeeStation-Hornet/pull/705)

False. See #47272

**Comment by ike709** [comment]
@kriskog That's the PR that broke the holodeck computer loading non-emagged programs. Bee fixed it.

**Comment by kriskog** [comment]
No. If you revert that PR you still have the original issue, which is a list containing both safe and unsafe programs after re-enabling safeties. Hence, not the one-liner you suggested, and now presumably an issue again on bee.

**Comment by ike709** [comment]
I didn't revert that PR.

**Comment by kriskog** [comment]
You reverted the fix though. It fixed your problem, but reintroduced another. Go run an emagged program on beecode and you'll see.

**Comment by spessbandit** [comment]
this is my bad, that said, the non-existence of the typecache is 100% the reason why the list contains both safe and unsafe programs, because without the typecache, you're not mirroring the list but creating two pointers to it, and thus when you interact with it it ends up yeeting the unsafe programs into the safe list

**Comment by kriskog** [comment]
Just copy the list though, all good
