### ISSUE TITLE
gutlunches won't eat.

### ISSUE THREAD

**Issue by remuluson2** [tgstation/tgstation#47568]
## Reproduction:
Spawn in as an ashwalker.
Bring the corpse to tendril.
Watch as guthen and gutbuck refuse to eat the remains.
(This can be temporarily fixed by attacking them with disarm intent but it damages them.)

**Comment by Learner10** [comment]
If you drag gutlunch and hold them over the food as well, it makes them start eating as well.

**Comment by nemvar** [comment]
Feck.

**Comment by TheBonded** [comment]
They eat things to heal, which means they will not eat unless you damage them. Punch them or otherwise damage them to make them eat.

This is intended.
