### ISSUE TITLE
Walk button is now a toggle

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#47563]
#47003 probably changed this. @Couls 

If you press alt you change movement mode completely, instead of just when held down.

This causes issues with alt tabbing, and alt clicking. Especially alt clicking bags which happen all the time.

**Comment by Couls** [comment]
Easy fix, can get to this later today I think

**Comment by kriskog** [comment]
Some people might want a separate toggle if thats easily doable, I kinda do.
