### ISSUE TITLE
Half the shuttle goes off to Centcomm, leaving the bridge behind.

### ISSUE THREAD

**Issue by Learner10** [tgstation/tgstation#47574]
## Round ID: 
122903

## Testmerges:
#46968: 'Kilo Station' by Okand37 at commit 300b931a77
#47571: 'Revert "Port Custom hotkeys from TGMC"' by imsxz at commit f1055b3291

## Reproduction:
This is the first time I have seen such a thing. It basically looks like this... [https://i.imgur.com/iciZ1Ft.gifv](url)

**Comment by optimumtact** [comment]
https://i.imgur.com/iciZ1Ft.gifv

**Comment by necromanceranne** [comment]
Oh yeah I was there that round. Didn't see it again after that. Really weird!

**Comment by HomocidlePancakes** [comment]
That's dank

**Comment by Firecage** [comment]
This just happened on Event Hall. Little less than half of the shuttle launch and got send to Centcom, while more than half of it stayed behind.

Round ID: https://sb.atlantaned.space/rounds/124651

Station: Metastation

Shuttle: Metastation Escape Shuttle

Pic: 
![image](https://user-images.githubusercontent.com/4686269/69806396-6bb17480-11eb-11ea-85c4-814d276d312e.png)

**Comment by PKPenguin321** [comment]
Last time this cropped up it had to do with people changing the area name of the shuttle with the station blueprints

**Comment by dragomagol** [comment]
In only one of those two rounds were blueprints used, and it was in the SM chamber and not the Emergency Shuttle. Both rounds did have this identical runtime:

`[2019-11-28 12:21:38.945] runtime error: list index out of bounds
 - proc name: preflight check (/obj/docking_port/mobile/proc/preflight_check)
 -   source file: docking.dm,121
 -   usr: null
 -   src: Meta emergency shuttle (/obj/docking_port/mobile/emergency)
 -   src.loc: the shuttle floor (106,64,2) (/turf/open/floor/mineral/titanium/blue)
 -   call stack:
 - Meta emergency shuttle (/obj/docking_port/mobile/emergency): preflight check(/list (/list), /list (/list), /list (/list), 270)
 - Meta emergency shuttle (/obj/docking_port/mobile/emergency): initiate docking(Transit for emergency/Meta eme... (/obj/docking_port/stationary/transit), 2, 0)
 - Meta emergency shuttle (/obj/docking_port/mobile/emergency): enterTransit()
 - Meta emergency shuttle (/obj/docking_port/mobile/emergency): check()
 - Shuttle (/datum/controller/subsystem/shuttle): fire(0)
 - Shuttle (/datum/controller/subsystem/shuttle): ignite(0)
[2019-11-28 12:21:38.945] runtime error: list index out of bounds
 - proc name: preflight check (/obj/docking_port/mobile/proc/preflight_check)
 -   source file: docking.dm,121
 -   usr: null
 -   src: Meta emergency shuttle (/obj/docking_port/mobile/emergency)
 -   src.loc: the shuttle floor (106,64,2) (/turf/open/floor/mineral/titanium/blue)
 -   call stack:
 - Meta emergency shuttle (/obj/docking_port/mobile/emergency): preflight check(/list (/list), /list (/list), /list (/list), 270)
 - Meta emergency shuttle (/obj/docking_port/mobile/emergency): initiate docking(Transit for emergency/Meta eme... (/obj/docking_port/stationary/transit), 2, 0)
 - Meta emergency shuttle (/obj/docking_port/mobile/emergency): enterTransit()
 - Meta emergency shuttle (/obj/docking_port/mobile/emergency): check()
 - Shuttle (/datum/controller/subsystem/shuttle): fire(0)
 - Shuttle (/datum/controller/subsystem/shuttle): ignite(0)`

**Comment by tgsAvylaar** [comment]
I have seen this a plethora of times, on different maps with different shuttles. I'd have to plough through hundreds of screenshots, but I can attest to the fact that this bug is definitely still in-game.

**Comment by msgerbs** [comment]
Would love some more recent round IDs for this if anyone has seen it.

**Comment by jlsnow301** [comment]
#64764

likely fixed this
