### ISSUE TITLE
OOC and say hotkeys now open two tabs, one has no cancel or X button

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#47570]
Hit T and you will be given two tabs. One is a "Say" tab with only an OK button and the other is a "say 'text'" tab with the normal OK, cancel, and x buttons.

OOC is the same way. Opens an "OOC" tab like above and an "ooc 'text'" tab. The new "Say" and "OOC" tabs also cant exist at the same time and will wait until one is closed for the other one to finally open.

Issue reported from  Round ID: 122903 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

**Comment by Couls** [comment]
Looking into this

**Comment by optimumtact** [comment]
@NoxVS are you using the non standard controls pref in tg?

**Comment by optimumtact** [comment]
also any screenshots?

**Comment by Couls** [comment]
the first window popup is the one custom hotkeys should use, looks like the second popup is the T macro that was used before custom hotkeys

**Comment by optimumtact** [comment]
@Couls are you clearing the existing legacy macro set of the user before applying the new ones for hotkeys?

**Comment by Couls** [comment]
input subsystem should handle that already with the erase_all_macros proc

**Comment by Couls** [comment]
I figured it out
