### ISSUE TITLE
Toolbelts have 7 slots but only allow 6 items

### ISSUE THREAD

**Issue by Moonman121** [tgstation/tgstation#47587]
## Round ID:
Round ID: 122984

## Testmerges:
#46968: 'Kilo Station' by Okand37 at commit 300b931a77
#47571: 'Revert "Port Custom hotkeys from TGMC"' by imsxz at commit f1055b3291

## Reproduction:
Attempting to place another item into a toolbelt with 6 items tells you it is full despite there being a free slot.

**Comment by kriskog** [comment]
Can't reproduce this.

Where did you get the toolbelt?
What were you trying to put in?
What was already in the belt?

**Comment by ATH1909** [comment]
You weren't trying to use a normal belt (NOT a toolbelt), right (do normal belts have 6 slots or 7?)?

**Comment by Moonman121** [comment]
@kriskog Placing an RCD in a toolbelt doesn't allow the last slot to be used and says the belt is full, so that was the issue I was having. I haven't looked at the recent toolbelt PR that allowed RCD's and can't seem to find it so I'm not sure if it is intended, if it is I can close this.

**Comment by ninjanomnom** [comment]
Larger/Heavier things use more slots, this is intended
