### ISSUE TITLE
Reaction Chamber sometimes stops taking in chemicals

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#47583]
A simple way to reproduce: Add 10 units of cryoxadone in one intake, add 10 units of Cryoxadone in the other in take. Set reaction chamber to 5 blood, 1 cryoxadone. The result is that after one meat reaction, the chamber refuses to take in further materials. Plunging the reaction chamber reactivates it again, but after producing one more meat, it breaks once again.

I have also tested this with Plasma Solidification, same issue. Perhaps on_reagent_change is somehow not called in these reactions? That would explain why the Acclimator doesn't break while producing plastic, that one does not rely on this proc.

Quick setup I used:
![meat_factory](https://user-images.githubusercontent.com/2676196/68147858-3f337100-ff3b-11e9-851b-84229e7bcc31.png)

**Comment by kriskog** [comment]
@Time-Green

**Comment by Time-Green** [comment]
I’ll look into it
