### ISSUE TITLE
Goliaths won’t drop their hide if they were sacrificed to the ashwalker nest

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#47593]

**Comment by TheVekter** [comment]
I'm not sure this is unintended.

**Comment by HomocidlePancakes** [comment]
Why would it be intended?

**Comment by TheVekter** [comment]
Because getting plates is supposed to be a reward for killing them. This seems abuseable. I could be wrong.

**Comment by Dorsisdwarf** [comment]
Goliaths only drop hide when butchered, dont they? Does gibbing generally trigger butchery?
