### ISSUE TITLE
(multiz) mechs can't go down (stairs)

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#47604]
## Round ID:

 123028

## Testmerges:
#46968, #47571

## Reproduction:
Be a mech
try to go downstairs

it turns out mechs can basically fly over open spaces. this is bad for many reasons, and one is that since they also can't use ladders or hand tele portals there's no real way for a mech to go downward.

**Comment by wesoda25** [comment]
feature mech feet are too big for stairs

**Comment by HomocidlePancakes** [comment]
Anotha one

**Comment by Tharcoonvagh** [comment]
Move down IC tab?

**Comment by Ghommie** [comment]
That's because mechs are anchored, and anchored movables don't fall downstair.
I can see potential issues with thrown anchored objects (singularity pull, oingo boingo punch, meteorshot etcetera) floating over open spaces.
