### ISSUE TITLE
Saw Bug

### ISSUE THREAD

**Issue by kilmne** [tgstation/tgstation#47608]
Issue reported from  Round ID: 123042 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471
When using the SAW as a war-op was not able to reload, was unable to take the mag out of the saw untill empty of all ammo and was not able to put new ammo in.
the ammo i was trying to reload with was the AP ammo

**Comment by necromanceranne** [comment]
Did you:
Alt-click the gun in you active hand
Click the gun in your active empty hand to remove the box magazine
Then use the new magazine on the gun?

You can't currently rack the gun to empty the chamber. That I definitely can verify but I have definitely reloaded the weapon recently. So I'll try testing this out.

**Comment by kilmne** [comment]
i tried basically everything i could think of, i was running around like a chicken with its head cut off at the time trying not to die at the time, like i said i was able to remove the box but only after i had emptyed the gun of all ammo

**Comment by necromanceranne** [comment]
It could have been operatior error in this case. But we'll see.

**Comment by tralezab** [comment]
WE WILL SEE INDEED

**Comment by necromanceranne** [comment]
Yep, couldn't recreate it whatsoever. I could reload with ammo in the magazine, and could do it between AP and normal and vice versa. No problems, working as intended. I couldn't tactical reload but that's intended. If you attempted to tactical reload, sadly, you're out of luck.

**Comment by kriskog** [comment]
What is the in game feedback like for this? Worth clarifying?

**Comment by necromanceranne** [comment]
![Screenshot 2019-11-06 22 50 08](https://user-images.githubusercontent.com/40847847/68296344-7e52f500-00e8-11ea-8712-c141413a0409.png)

Here are all the various messages while using the weapon, each action directed to the chat.

**Comment by Repukan** [comment]
Did you do it while the magazine was half full of ap ammo as the OP said

**Comment by kilmne** [comment]
The main problem was that i wasnt able to open or close the cover, but i was able to take the (empty) mag out even without to cover being open, but not able to put the new mag in

**Comment by necromanceranne** [comment]
@Repukan Yes, I was opening and reloading and firing and at all stages I was able to reload the weapon regardless of ammo count.

@kilmne okay that's a bit unusual. I'll try emptying the gun completely and attempt to remove the magazine without opening the dust cover.

**Comment by kilmne** [comment]
if noone has been able to find the bug by now, its not a bug, i dont know how but i must have fucked up 20 times in a row. guess i had a stroke, sorry.
