### ISSUE TITLE
Shit is fucked, hotkeys why

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#47618]
No round id. 
Testmerge: kilostation by okand
Issue: You can't escape any chat window by pressing escape
This is annoying as fuck please fix.
edit: h won't stop pulling and you cant open more than one window

**Comment by Couls** [comment]
You can still click close and cancel yeah?

**Comment by Tharcoonvagh** [comment]
No close
And escape doesn't work

**Comment by Couls** [comment]
Need more info, are you getting two or only one chat window?

**Comment by Couls** [comment]
ask a headmin to update your server, the pulling bug has been fixed already

**Comment by Tharcoonvagh** [comment]
Uhuh

**Comment by kriskog** [comment]
While I didnt get two chat windows, I do get the one new one that cant be cancelled out of. I expect this will get fixed by an update.

**Comment by Couls** [comment]
yeah, the update will give you the cancel and x buttons

**Comment by kriskog** [comment]
Closing this then
