### ISSUE TITLE
Additional crafting recipes break TGUI Next's Crafting Menu

### ISSUE THREAD

**Issue by Farquaar** [tgstation/tgstation#47612]
## Bug:
![chefbug](https://user-images.githubusercontent.com/44147031/68276492-1e524500-003b-11ea-920d-6a22c27734a4.png)
Error message is as follows:
Permission denied (http://127.0.0.1:54319/tmp11204/tgui.bundle.js line 1) User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)

## Reproduction:
Start round, read "Cooking Desserts 101", try to open crafting menu.

**Comment by kriskog** [comment]
@actioninja

**Comment by actioninja** [comment]
Wew I really should just make it runtime if it detects this situation, this isn't actually an issue with the interface it's an issue with the recipes being added. If something gets added to a category with subcategories without a subcategory set it makes the whole interface explode. This isn't a valid situation so it shouldn't even be supported.

Also the Chocolate Lava Tart has actually been uncraftable up until this point. Good job whoever added it.

**Comment by necromanceranne** [comment]
Ouch!

**Comment by Iatots** [comment]
Wait, that 101 book unlocked recipies? I thought it was just a dessert guide like the normal cookbook is for basic recipies.

**Comment by Tharcoonvagh** [comment]
OH SHIT THE CLOWN HAS A KNIFE
