### ISSUE TITLE
Fire Instantly Melts Sec HUDS 

### ISSUE THREAD

**Issue by KangTut** [tgstation/tgstation#47610]
## Round ID: 123052

As the title says - being set on fire instantly destroys sec HUDs. I've had several rounds now where someone would hit me once with a flamethrower and I'd instantly lose my HUD.

**Comment by necromanceranne** [comment]
I not only tested this, I compared an admin spawned pair of night goggles (only made of glass) to one out of the lathe (made from gold and uranium)

Guess what, the lathe'd pair of goggles is much, much more resilient against burning up while the admin spawned one dusted as fast as the sec huds.

@Qustinnus I think I'm justified and this is a problem with material datum imparting durability of objects. I noticed this with a lot of stuff not printed out of a lathe, and most round start objects appear to be significantly more vulnerable to explosions and fires than any objects printed from a lathe.

**Comment by necromanceranne** [comment]
I also tested this against the base sechud out of the lathe. It's more durable than the crafted sechudglasses because when crafted, it reverts to only glass again and the sechud has iron, increasing it's durability.

Very nice.

**Comment by necromanceranne** [comment]
I'm making this into a separate issue this is almost definitely something with material datum and actually affects more than just sechuds

**Comment by FancyCyclops** [comment]
Speedmerges are a mistake.

**Comment by kriskog** [comment]
Closing in favor of #47611 then.

>
>
>Speedmerges are a mistake.

It wasn't a speedmerge you nerd.
