### ISSUE TITLE
Glass reduces object durability if it's the only material in the item; most roundstart/admin/crafted objects spawn with only glass even if they are normally constructed with more than just glass

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#47611]
There are a few ways I've managed to reproduce this and it's something that I was aware of the moment material datum hit the servers because I noticed it all the way back in my initial testing with material datum on day 1, but couldn't figure it out conclusively.

In this issue here: https://github.com/tgstation/tgstation/issues/47610
I found that the sechudglasses made from crafting, admin spawning and roundstart spawn all were only made out of glass. When set on fire, they burned away rapidly because their durability is reduced by the glass.

HOWEVER, sechuds printed from an protolathe use glass and iron, so they actually survived for a good amount of time in a fire as they should. They're not invulnerable but they can be rescued.

Admin-spawned sechud nightvision goggles (only glass) and protolathe printed sechud nightvision goggles (made from iron, glass, gold and uranium) showed these same properties.

This is a very easily produced demonstration that glass is affecting the durability of the objects where they are only made out of glass. The reason this is important is several.

**1. Roundstart objects are mostly made out of glass or glass and iron (even if normally lathed with more than just iron and glass) because they're just spawned in and impart only the glass datum. This is not the case with ALL objects, this is just MOST objects, which means some exceptions exist.**

Most of your roundstart gear is now extremely vulnerable to fires and explosions

**2. Powercells inside guns are only made out of glass and not glass and iron. Therefore, if an explosion is centered on the person, the glass power cell is destroyed.**

This is reproducable if you simply give a target dummy an admin spawned power cell and one you printed out of the lathe. I used a super cell in my test. If you shoot a fireball at the dummy, the one that is admin spawned will be deleted in their hand. The one that was lathed will survive the explosion.

This is why every single gun in your possession is bricked when you get hit with something like a fireball. The cell is now super fragile because it was spawned roundstart and didn't obtain iron as part of it's roundstart datum.

**Comment by necromanceranne** [comment]
I should also highlight that objects originally fairly durable against a variety of different conditions are now suddenly much more vulnerable to damage. I'm pretty before material datum, PKC's would not instantly delete to a single explosion. Now they do. I suspect it's the material datum again, which is weird since PKA's (although not their cells) are not vulnerable to this, nor are a few other objects in the miner's usual toolkit. I'd need to have another look at this when I next play shaft miner since the PKC is my standard loadout.

**Comment by actioninja** [comment]
@Qustinnus

**Comment by necromanceranne** [comment]
This got fixed a while ago
