### ISSUE TITLE
Reflector trenchcoat hood does not reflect energy projectiles

### ISSUE THREAD

**Issue by Pugie** [tgstation/tgstation#47625]
Replicate by equipping reflector trenchcoat and then toggling the hood, followed by aiming at the head. 0% reflect chance but it absorbs energy damage, probably not intended considering aiming anywhere else will have a chance to reflect.

**Comment by Couls** [comment]
@py01

**Comment by HomocidlePancakes** [comment]
*wheeze*

**Comment by carlarctg** [comment]
bruh
