### ISSUE TITLE
Gondola can buckle themselves into chairs despite not having arms

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#47622]
## Round ID:
123090

## Testmerges:
Kilo and the custom hotkey PR

## Reproduction:
- Become gondola
- Drag self to chair

Not sure if this is intended or not but how're they able to buckle in?

**Comment by 81Denton** [comment]
very carefully

**Comment by Tharcoonvagh** [comment]
all mobs can do that afaik

**Comment by PKPenguin321** [comment]
Not a bug
