### ISSUE TITLE
Ghosts are able to click-drag buckle mobs onto borgs.

### ISSUE THREAD

**Issue by capn-monkeypaw** [tgstation/tgstation#47629]
Round ID: 123122 on the Events Hall

## Reproduction:
During the round, ghost/observing player KiltinAction was able to demonstrate his ability to click-drag buckle living players onto borgs.

**Comment by ATH1909** [comment]
Was this caused by my borg buckling PR?

**Comment by JDHoffmann2** [comment]
#48199 fixes this.

**Comment by Tharcoonvagh** [comment]
Poltergeists.....

**Comment by carshalash** [comment]
This has been a thing for over half a year. christ.
