### ISSUE TITLE
Purge ai module removes hacked laws

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#47637]
Be ai
Traitor uploads hacked law, trying to do a gimmick
Captain suspicious after reports of shocked doors
Purge and asimov
Report said traitor
:(((((

**Comment by Pugie** [comment]
Your alternative is round removal if that suits you?? This doesn't seem like a bug.

**Comment by necromanceranne** [comment]
Completely intentional. The true issue likely arises from the ease of law uploads and purge availability.

**Comment by Tlaltecuhtli** [comment]
not a bug

**Comment by Pugie** [comment]
> Completely intentional. The true issue likely arises from the ease of law uploads and purge availability.

Yes AI law uploading is quasi available to entire crew with epic circuit imprinters.

**Comment by Tharcoonvagh** [comment]
Shouldn't it like be repairable in the ai integrity restorer?
