### ISSUE TITLE
New ORM Interface Won't Dispense Alloys

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#47649]
The new TGUI-next interface for the ORM is pretty, but doesn't allow any vending of alloys (materials made by smelting multiple ores together, such as plasteel or plastitanium) whatsoever.

**Comment by kriskog** [comment]
Can confirm. Would also be nice with a clamp to current max on the input.
![image](https://user-images.githubusercontent.com/33292112/68509868-568f9880-0272-11ea-87de-54b88ec5c2e3.png)

**Comment by kriskog** [comment]
@stylemistake

**Comment by stylemistake** [comment]
I'll add a fix to my current big sitting PR.
