### ISSUE TITLE
movement borked

### ISSUE THREAD

**Issue by Kaptinalexander** [tgstation/tgstation#47645]
Issue reported from  Round ID: 123187 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1496 & 512.1488

Issue: Can't use arrowkeys for movement, only WASD

Also can't seem to use the numpad to type in the chat bar, not sure if that was like that before or not.

Toggling the hotkeys doesn't seem to change anything, but I do remember being able to move using the arrow keys with it on. 

The arrow keys were working before on 11/6, and then didn't work on 11/7, tried updating to the beta version of beyond to see if that was my issue, but no change. 

Tested the keyboard on other games, still works, so that's fine.

**Comment by Couls** [comment]
You can rebind movement keys to arrow keys now in game preferences

**Comment by Kaptinalexander** [comment]
But doesn't that mean you'd not be able to ever turn off hotkey mode? Doesn't really address the fact that it's not working when hotkey mode isn't on.

**Comment by Couls** [comment]
I thought the issue was movement being broken? you can move with WASD and if you rebind it to arrow keys you can move with those too, hotkey mode always being on is a seperate thing and already reported here #47643

**Comment by Kaptinalexander** [comment]
Guess I should have been more specific in the title, but yeah, hotkeys are working fine, it's just that the arrow keys no longer work in anymode, and you have to specifically rebind them,

you used to have both options in when hotkey mode was active, meaning that you could use wasd and the arrow keys for movement while hotkey mode was on.
