### ISSUE TITLE
Custom hotkeys are sluggish and worse than their original version

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#47644]
Hotkeys, or specifically the say function, are far slower than the normal, even with the issue-resolving PR merged. There's a noticeable delay between pressing the hotkey to talk and actually having the window pop up. Also, if you have another popup on the screen at the same time, you're not able to open the say window, and you can't esc out of existing ones like you used to.

**Comment by Couls** [comment]
Are you sure that the server you’re in is updated?

**Comment by optimumtact** [comment]
this is absolutely never going to be reproduced or proven without any data
