### ISSUE TITLE
Alt-Clicking causes run-walk mode to toggle now, previously only switched modes while held.

### ISSUE THREAD

**Issue by ArcaneMusic** [tgstation/tgstation#47651]
## Round ID:
Found while testing on my private server, Bagil still has the hotkey revert testmerged.

## Testmerges:
None, just found while testing my branch of the Medical Kiosk Rework.

## Reproduction:
While using a machine with an alt-click, alt-click functionality with the machine is fine, however with the new hotkey changes, it toggles run-walk mode. It's not exclusive to machines however, it seems like now alt is a run-walk toggle now.

Previously, just holding alt would allow for you to swap between running and walking on the fly. It seems that the recent changes to hotkeys from #47003 may have caused this, but I'm not sure.

**Comment by Couls** [comment]
This has been fixed, is your private server up to date? there should be two keys for walk-run, one where you can hold it to swap and one that toggles it properly

**Comment by kriskog** [comment]
This is fixed on current master. Update your server.
