### ISSUE TITLE
AIs can not set their camera location hotkeys.

### ISSUE THREAD

**Issue by zxaber** [tgstation/tgstation#47659]
## Round ID:
123217 (Event Hall EU)

## Testmerges:
None

## Reproduction:
Pressing CTRL + [1-9] should result in the location of an AI's eye being saved to that number key, complete with a message indicating such. Then, when the key is pressed again (without CTRL), the eye jumps to that location.

Currently, on Event Hall at least, you cannot set the location. No message confirming it being set ever is given, and pressing the number afterwards does not move your eye.

**Comment by cacogen** [comment]
>Pressing CTRL + [1-9] should result in the location of an AI's eye being saved to that number key, complete with a message indicating such. Then, when the key is pressed again (without CTRL), the eye jumps to that location.

wait how long has this been a thing

**Comment by zxaber** [comment]
Since the end of March.
