### ISSUE TITLE
"Obvious" ghosts block clicks for the living.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#47660]
I don't think they should.

**Comment by AnonymousNow** [comment]
They only want to socialise.
No, wait, that's skeletons.

You have a point, though. They should be visible, but completely incorporeal for living mob purposes.

**Comment by kriskog** [comment]
The reason it wasn't done last time this came up is it requires some finesse to avoid making ghosts un-clickable all the time. Admins click-dragging ghosts and players pointing at ghosts when visible are examples of functionality we might want to preserve.

**Comment by Tlaltecuhtli** [comment]
cant they be like plastic flaps ?

**Comment by cacogen** [comment]
what does admins click-dragging ghosts do

**Comment by kriskog** [comment]
Puts the ghost in control of the mob

**Comment by TheVekter** [comment]
That behavior isn't _technically_ necessary, but it's certainly easier than the alternative of having to var edit and put someone's mind datum into the mob.

**Comment by Learner10** [comment]
One of the most noticeable examples of this happen during wizard rounds with demons and visible ghosts. The demons will inevitably gain a permanent following of ghosts, who will make clicking on people for them at least 40% less efficient.

**Comment by ATH1909** [comment]
feature

**Comment by optimumtact** [comment]
please dont' leave issues open if they're not bugs
