### ISSUE TITLE
Watcher corpses continually feed the ashwalker tendril

### ISSUE THREAD

**Issue by Moonman121** [tgstation/tgstation#47669]
## Round ID:

Round ID: 123245

## Testmerges:

#47284: 'Migrates most machinery update_icon procs' by ninjanomnom at commit bfe030481d
#46891: 'Generic Map Popups + spy glasses' by Pacmandevil at commit 6944bc0403
#46968: 'Kilo Station' by Okand37 at commit 5a7f5622ab

## Reproduction:

Place a watcher corpse at the ashwalker tendril, the corpse will not gib and will continue to feed it and produce eggs constantly.

**Comment by Tharcoonvagh** [comment]
Dupe and a fix is here

**Comment by Moonman121** [comment]
I'll go ahead and close this then and wait for the servers to update.
