### ISSUE TITLE
The cycle intent hotkey for cyborgs only sets you to harm

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#47672]
When I press 4 while on help intent as a cyborg I get set to harm intent, as is intended behavior. Hitting 4 while on harm does nothing.

Issue reported from  Round ID: 123254 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

**Comment by kriskog** [comment]
@Couls

**Comment by Couls** [comment]
fixed in #47670
