### ISSUE TITLE
You can infinitely butcher/gib simple animals.

### ISSUE THREAD

**Issue by spessbandit** [tgstation/tgstation#47676]
## Reproduction:

1. Be a simple mob with butchering results, like a corgi/cat/crab. The bug doesn't seem to happen on mobs without.
2. Be gibbed/butchered by some means: knife butchering, smite gib, gibself, all work.
3. The meat, hides, etc. appear, but the simple animal doesn't get deleted, and if they're still alive, doesn't die. You can thus produce infinite meat, hides, tails, etc.

**Comment by Tharcoonvagh** [comment]
Kind of a dupe

**Comment by kriskog** [comment]
Fixed in
