### ISSUE TITLE
Rev hud stays when deconverted

### ISSUE THREAD

**Issue by Toedstewie007** [tgstation/tgstation#47671]
## Reproduction: Get implanted. To be more specific, I was trapped by a energy snare, flashed, cuffed, and implanted in sec checkpoint maint.
![ohfuck pwrgame](https://user-images.githubusercontent.com/21698339/68519404-5ed9da80-0256-11ea-929e-f65933366d6d.PNG)

**Comment by Toedstewie007** [comment]
that shit was hilariously powergamey, I can see unknowns like that unlucky man as revs.

**Comment by Couls** [comment]
@SteelSlayer

**Comment by kriskog** [comment]
What's your character name or ckey so we can look you up in logs?
