### ISSUE TITLE
Slimes can't hit AIs.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#47684]
Round 123288
Played as red adult slime (85). Attempted to kill AI multiple times, but couldn't hit it.

**Comment by Neo-0** [comment]
How can a SLIME kill a machine?

**Comment by Learner10** [comment]
By smashing and shocking it to pieces.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/a148cae769d991e2786ac2277ec979cdf28014a8/code/modules/mob/living/silicon/ai/ai_defense.dm#L14-L15

Intentional.
