### ISSUE TITLE
strange reagent issue

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#47690]
When you splash strange reagent upon a creature that is eligible to be revived by it, it doesn't actually consume the strange reagent from whatever container you splashed it from until the creature that you splashed it upon is revived.

In other words, if you put 10u of strange reagent in a bottle and splash it on a monkey corpse that can be revived by strange reagent, the strange reagent in the bottle won't go away until the monkey finishes going through the somewhat lengthy revival process.

I was going to fix this in my recent PR that fixed another strange reagent-related bug, but my PR got merged before I could get around to fixing this bug as well.

**Comment by kriskog** [comment]
There is a sleep in the strange reagent reaction_mob. Everything after should probably just be on a timer instead to fix this.

**Comment by ATH1909** [comment]
> There is a sleep in the strange reagent reaction_mob. Everything after should probably just be on a timer instead to fix this.
> I bet you can reuse the beaker on other dead things before the contents disappear.

Aye, you can do exactly that, and that's how I noticed this bug.

And yes, the other creatures that you use it on before it disappears DO get revived too.
