### ISSUE TITLE
genetics handheld mutation / dna scanner does not label discovered mutations anymore

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#47697]
## Round ID: 
12336- and earlier on terry for the past week or so

## Testmerges: 
#46968: 'Kilo Station' by Okand37 at commit 5a7f5622ab was on for most of these I think

## Reproduction: 
discover mutations, start scanning people: none that you have discovered show up, most notably the monkey mutation that should be labeled as soon as a monkey is inserted in the machine.

**Comment by Pugie** [comment]
This isn't a bug you need to link the genetic sequence analyzer to the genetic database by clicking the dna console with it.

**Comment by kriskog** [comment]
You need to hit a console with it first, it will update the discovered mutations after that.

**Comment by Iatots** [comment]
I never did that and it always worked, weird.
