### ISSUE TITLE
Missing chat if I late join

### ISSUE THREAD

**Issue by zxaber** [tgstation/tgstation#47693]
## Round ID:
123352 (for the screenshot, but it is not round-dependent) 

## Testmerges:
#46968

## Reproduction:
So, if I join Bagil or Event Hall EU mid-round, my entire chat box stays blank forever. But it _seems_ that if I actually witness the server setup steps, then my chatbox will be populated and work the rest of the round. Nothing else seems to be broken; I can open windows for consoles and machines without issue.

I have tried manually clearing (deleting) my cache, as well as a full reinstall of Byond. The issue has been occurring all day today, not just in any single round.

I have high suspicions this is being caused by #47653. I was not getting the problem at all on my local server, but I can make that one-line change to my local files and cause the issue pretty reliably. I've tested going back and forth, and only with `flags = SS_TICKER` on the chat subsystem can I reproduce the issue locally.

Screenshot of the problem:
![image](https://user-images.githubusercontent.com/37497534/68543126-ea8f5c00-0367-11ea-9e1e-a72d6f1b80fc.png)

**Comment by Tharcoonvagh** [comment]
Oh god

**Comment by kriskog** [comment]
byond version etc?

**Comment by GravitronBlue** [comment]
Been having this same issue as well with Byond version 512.1488
Quick way that fixes it for me it just doing `>file>reconnect` found on the top left of the client.

**Comment by zxaber** [comment]
I'm now on the same version, 512.1488, but I was on an earlier version before updating Byond to try and fix it.

**Comment by tralezab** [comment]
it's not confirmed, but for the post part this should not be an issue with sschat

**Comment by optimumtact** [comment]
this is not actually fixed

**Comment by zxaber** [comment]
Recently (within the last day or so), old-chat has at least started working when goonchat does not.

Before (when my chat box was missing entirely), Fix-Chat did nothing. Now it seems to bring goonchat back as well. It seems like it's fixed for me, for the most part.

**Comment by zxaber** [comment]
Wow it's been like two years and I still had this tab open. Anyway, I haven't seen this in 5ever so it's probably fixed.
