### ISSUE TITLE
Stacking notifications show up with a line break

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#47708]
Very minor annoyance, but for the last day or so, the little "x2" thing when you get the same line in a row shows up on a new line instead of the same one.

![image](https://user-images.githubusercontent.com/7019927/68561610-d69d3600-040b-11ea-9ef6-081e56df2b9d.png)

Probably not that hard to fix but my Git is fucked right now.

**Comment by Tharcoonvagh** [comment]
Git gud

**Comment by kriskog** [comment]
possibly sschat related

**Comment by tralezab** [comment]
almost no doubt in my mind that it is

**Comment by AnturK** [comment]
Yes
https://github.com/tgstation/tgstation/blob/a66d42a0bd6cb2be8b90827978e67383c22a40dd/code/controllers/subsystem/chat.dm#L39

**Comment by TheVekter** [comment]
That'll do it. I feex.
