### ISSUE TITLE
chatting with your host as a split personality sends you to the main menu

### ISSUE THREAD

**Issue by loserXD** [tgstation/tgstation#47715]
## Round ID:
123458

## Testmerges:
#46968: 'Kilo Station' by Okand37 at commit 5a7f5622ab

## Reproduction:
- be a split personality
- chat with your host
- get disconnected and get sent to the main menu when you rejoin

or maybe i got control and that's what caused it

**Comment by bobbahbrown** [comment]
Checked, no runtime.

**Comment by kriskog** [comment]
Keeping open for a bit since talking to your other personality is new and could have issues.

**Comment by kriskog** [comment]
Should be an issue with the key transfer then. See #47720
