### ISSUE TITLE
Cursed heart is now the secret assassination method

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#47724]
Round ID:123477
 Testmerges: #46968: 'Kilo Station' by Okand37 at commit 300b931a77
Was CMO who received a cursed heart. Regretted it afterwords due to how annoying it was to use it. However after about 15-20 minutes after I got it I suddenly dropped dead for no apparent reason. After some investigation I noticed that my blood dropped below 20% which instant killed me. Think the heart protects you from ox damage for 6 seconds however depletes your blood to cause the suffocation the thing advertises to do on wiki. 

Probably due to this PR https://github.com/tgstation/tgstation/pull/38105

**Comment by kriskog** [comment]
Cursed heart makes you lose 100 blood every time you fail it, gaining some back every time you pump it in the right interval. Fail too many times in a short amount of time, and you die. More specifically, from full blood you die after failing five times. That's the intended interaction.

**Comment by davethwave** [comment]
Ah, someone needs to fix wiki them.

**Comment by davethwave** [comment]
Also the time for pump and mistake is within 2 seconds which is almost impossible to make unless you spam it. Just saying.

**Comment by kriskog** [comment]
It's a cursed heart, it exists to make you miserable. You get a three second window to pump it, as you can pump it one second early.

>
>
>Ah, someone needs to fix wiki them.

You can be our someone :ok_hand:

**Comment by davethwave** [comment]
Gave the cursed heart a better albeit longer description of what it does.
