### ISSUE TITLE
possible brain trauma+mutation toxin bug

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#47731]
https://cdn.discordapp.com/attachments/326826573951008769/643737815494033418/brain_damage_bug.PNG

I cloned the RD, and they had a lot of brain damage and multiple traumas, one of which kept them from speaking properly (I think it's the one that gives you the special brain damaged language and forces you to use (only) that language?). I later fed them podperson mutation toxin, which healed all of their organ damage (including their brain damage and their brain traumas, as indicated by the screenshot above). They were still just as unable to speak properly/Common as they were just after they were cloned. I forgot to ask them after the round if they were able to understand my speech (in Common).

Maybe the podperson mutation toxin destroyed the RD's brain traumas in a weird way, resulting in them not undoing their changes to his known languages?

**Comment by kriskog** [comment]
The trauma doesn't always reset the language, not quite sure why. Someone should check round logs for a runtime relating to language holder. I have seen it happen from normal brain surgery too, so mutation toxin should be unrelated.

**Comment by TheVekter** [comment]
HA. I knew it. I experienced something similar where someone did brain surgery on me and I still wasn't able to talk correctly.
