### ISSUE TITLE
TGUI crafting menu "tribal" subsection is broken.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#47737]
![image](https://user-images.githubusercontent.com/35217076/68679775-90fa7d80-0571-11ea-9fcb-c26486c01735.png)

Visited the elephant graveyard ruin and got additonal recepies from there. Later, tried to craft a shovel and a bone talisman. Had all the mats, but couldn't do it, most likely due to learning the recepies.

**Comment by HomocidlePancakes** [comment]
Ok, nevermind. After further testing I undderstood you just couldn't craft anything in the "tribal" subsection.

**Comment by necromanceranne** [comment]
Unusual, I was making stuff out of the tribal section today, so I feel like this is actually a result of having the recipe added rather than the tribal subsection being broken. Similar to https://github.com/tgstation/tgstation/issues/47612 I think.

**Comment by HomocidlePancakes** [comment]
No, I tried to craft a codpiece the next round and couldn't do it, even though I had all the ingridients. The other miner had the same issue.

**Comment by kriskog** [comment]
Should be fixed by #47730. @actioninja ?

**Comment by HomocidlePancakes** [comment]
Rounds 123517 and 123521 if that helps

**Comment by AnturK** [comment]
Yes that's the issue that PR fixes.

**Comment by HomocidlePancakes** [comment]
It was merged 8 hours ago. The issue came up 3 hours ago

**Comment by kriskog** [comment]
It was merged two hours ago.

**Comment by HomocidlePancakes** [comment]
Aw fuck. I've looked at the wrong number. Sorry
