### ISSUE TITLE
Can't craft picket signs

### ISSUE THREAD

**Issue by Tumesuo** [tgstation/tgstation#47739]
Issue reported from  Round ID: 123526 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1475

How to replicate: Have the materials in your hand or somewhere nearby, go to misc. tab and find out that you can't craft it.

**Comment by Tumesuo** [comment]
Can't craft anything else from the misc tab it seems. Didn't work for another player when I asked them to try crafting as well.

**Comment by kriskog** [comment]
#47730 fixes this, wait for server to update
