### ISSUE TITLE
New hotkeys don't respect if you're in chat mode

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#47733]
## Round ID:
Irrelevant

## Testmerges:
Irrelevant

## Reproduction:
Play in chatmode
Try to type
Get annoyed by the fact that all the hotkeys keep interrupting you trying to type or that you can't move and type or that the chatbar won't stay selected so you can type multiple messages one after the other

This exact issue affects TGMC and is why I don't play there anymore, I physically cannot play in hotkey mode.

**Comment by kriskog** [comment]
Not a bug, take it to the feedback thread: https://tgstation13.org/phpBB/viewtopic.php?f=10&t=24469

**Comment by Anonmare** [comment]
>Clearly breaks an existing feature with its functionality
>"not a bug"

Ok boomer

**Comment by kriskog** [comment]
Read the thread or the previous five issues on the topic.
