### ISSUE TITLE
Dynamic only looks for enemy roles among players eligible for playing as the antag

### ISSUE THREAD

**Issue by Putnam3145** [tgstation/tgstation#47734]
## Reproduction:

```for (var/mob/M in living_players)```

```living_players = trim_list(mode.current_players[CURRENT_LIVING_PLAYERS])```

trim_list removes all players from the list who: do not meet the required age **for the antag**, are jobbanned **from the antag**, have a role that is restricted **from the antag** (!!!!!! prevents most antags that require sec enemies from working completely!!) etc.

i'd make a PR but my local repo is busted due to being a defunct downstream and i can't particularly be assed to fix it

**Comment by carlarctg** [comment]
i don't get how this is an issue @Putnam3145 from what youre saying it works perfectly well

**Comment by kriskog** [comment]
Enemy roles is supposed to be the counter to rolling a million antags and zero sec. I'll take a look later.
