### ISSUE TITLE
Cult space base still possible.

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#47747]
## Round ID:

Round ID: 123542 (terry)
BYOND Version: 512.1484
Server revision compiled on: 
Master commit: ae5cd202052ab4c66c677cc10ebc132d6b3da932
The following pull requests are currently test merged:
#46968: 'Kilo Station' by Okand37 at commit 5a7f5622ab
Local commit: a66d42a0bd6cb2be8b90827978e67383c22a40dd

## Reproduction:
Didn't make it myself, the base was on station z-level. Pod is still part of the equation, but just as ez power source for ID, shuttle and upload consoles I think.
https://imgur.com/a/nCoXm41

**Comment by cacogen** [comment]
Don't these have built-in GPS

**Comment by necromanceranne** [comment]
They do but they're not supposed to be able to be used for cult bases at all. This PR (https://github.com/tgstation/tgstation/pull/47041) was meant to stop that, and it looks like they expanded the pod's area out to the new section they built, which is how this likely got past the change. While the pod itself is cultproof, the areas built from it and added to the pod area probably aren't.

@81Denton At a guess, this likely has something to do with some ongoing bugs with expanding areas, which includes stuff like this one.  (https://github.com/tgstation/tgstation/issues/45771)

**Comment by py01** [comment]
Runes appear to be correctly blocked in survival capsules, however, new areas created in "space" allow runes. The survival pod isn't actually relevant to this. I'm not sure if there's a sane way to prevent new rooms built in "space" from being cult-allowed without making all new rooms no-cult allowed

**Comment by Sealed101** [comment]
survival pods no longer accept cult runes as of #73757
newly created areas however can still be used, so long as they are on the station zlevel
