### ISSUE TITLE
Oldstation Ghostrole has Follicular Inconsistency

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#47752]
You can't normally make a woman with a beard in regular gameplay, but female survivors coming out of the oldstation ghostrole pods can and do frequently have full beards and moustaches.

I'm guessing that this is an oversight and not a brave and stunning example of trans inclusionism.

**Comment by fludd12** [comment]
Given the general reaction the last time inclusion was attempted, I think that's a safe assumption.

**Comment by cacogen** [comment]
side effect of longterm cryo

**Comment by 81Denton** [comment]
@fludd12 I think it was a goof PR, which probably didn't help

**Comment by 81Denton** [comment]
https://github.com/tgstation/tgstation/blob/98b0805b57d64399557385de84a32d64c547f3f2/code/modules/awaymissions/corpse.dm#L181-L184

Normally, random_facial_hairstyle(gender) should restrict beards to male mobs. I'm not sure how this happens.

**Comment by Firecage** [comment]
And yes, I did reproduce this on a local repo before I tested the fix.
