### ISSUE TITLE
Radio implant prevents using any other comms channels than syndicate

### ISSUE THREAD

**Issue by Glassmanner** [tgstation/tgstation#47760]
## Reproduction: Get radio implant as a traitor, try to use any other channel than traitor channel and you can't. The implant I had was on sale, no idea if that makes a difference.

I tried turning the radio implant and headset on and off but the issue persisted.
This bug has been a thing for at least 3 months, I don't remember the other round Id's where this happened but it has happened before too.

**Comment by Tharcoonvagh** [comment]
Can confirm
