### ISSUE TITLE
Erronous Emitter Admin Notices

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#4777]
ADMIN LOG: Emitter lost power in (104,57,1 - JMP)
ADMIN LOG: Emitter lost power in (122,57,1 - JMP)
ADMIN LOG: Emitter lost power in (122,65,1 - JMP)

These occasionally spam asay, but it's not true at all. Something else must be triggering these, because a lot of the time the emitters are perfectly fine when investigated.

**Comment by Shadowlight213** [comment]
Still a thing

**Comment by Bawhoppen** [comment]
Just make emitters have a small internal capacity or something
