### ISSUE TITLE
syndicate mech hijacker issue(s)

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#47798]
Syndicate mech pilots (simplemobs who can pilot mechs) can instantly(!) enter mechs, but cannot resist out of mechs (IIRC, they get a timer for resisting out, but nothing happens when the timer finishes). Presumably, this applies to nanotrasen mech pilots as well.

**Comment by ATH1909** [comment]
Also, they may or may not be able to bypass the melee attack cooldowns of mechs; I didn't look too closely at that while I was testing.

**Comment by Sealed101** [comment]
mech pilots were laid to rest in #71871
