### ISSUE TITLE
Metastation roundstart bar/armory throwing kit box has illegal tech

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#47792]
Syndicate boxes have illegal tech for some reason, it's likely a bad thing that illegal tech spawns roundstart on metastation

**Comment by TheVekter** [comment]
Where are these boxes located? I'm having trouble finding them.

**Comment by TheVekter** [comment]
Right, yeah. This was because some denthead put the syndicate throwing items bundle box in the drop table for gambling items.
