### ISSUE TITLE
Removing a firing pin from a gun creates a "ghost" gun

### ISSUE THREAD

**Issue by TheChosenEvilOne** [tgstation/tgstation#47801]
## Reproduction:

Remove a firing pin from a gun and now you will have a reference to a deleted gun (/obj/item/gun) in your hand.

**Comment by ATH1909** [comment]
Can you fire this "ghost gun" and/or use it to craft another item?

**Comment by TheChosenEvilOne** [comment]
> 
> 
> Can you fire this "ghost gun" and/or use it to craft another item?

You can try to fire it but it fails because it has no firing pin. But you can probably use it for crafting.

**Comment by ATH1909** [comment]
Can you put a new firing pin in it?

**Comment by Tlaltecuhtli** [comment]
this being a “crafting recipe” is retarded tbh, it should be like a screwdriver act to remove pin

**Comment by projectkepler-ru** [comment]
this is no longer applicable

**Comment by Sealed101** [comment]
^ confirmed to be true, can no longer reproduce
