### ISSUE TITLE
Tabbing into hotkey mode no longer works

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#47800]
For whatever reason, whenever I hit tab and try to move using WASD, nothing happens. It just types into the command box like I'd never hit tab. This doesn't seem to _directly_ be a keybind issue, as they keys are set properly in the settings, but it's still not working. Other keys (like O for OOC and T for Talk) also don't work. Reproduced by Equodox#7576 on Discord, they don't have a Github account so I'm posting this for them:

"Ok, so the character I play as on Sybil, Kaito Brute, seems to be having trouble moving around. I press WSAD and nothing seems to work. Inevitably its because I'm typing in the command box. As usual I would press TAB to get out of the command box and I go to move again. When I do though, all it does is type in the command box still, even when its white. Keybinds have absolutely nothing to do with it. I've clicked on the screen only to have my character look in the direction i click or perform an action, as well as turning the command box red again."

To clarify, we're both having the same issue.

**Comment by TheVekter** [comment]
Resetting hotkeys seems to fix it, which makes me think it _is_ hotkey related, though neither of us made any changes (aside from me setting *flip to a key). Still, easy personal fix or not, probably need a permanent fix for it.

**Comment by Couls** [comment]
has to do with savefiles not updating properly, newer people will not have this issue
