### ISSUE TITLE
Chat/certain popups relating to silicons are repeated.

### ISSUE THREAD

**Issue by Coconutwarrior97** [tgstation/tgstation#47805]
## Reproduction:

Speaking in binary leaves an extra blank line after the text and cyborg shell notifications are sent twice. Considering both are a form of duplication I'm assuming they are related somehow.

![image](https://user-images.githubusercontent.com/40315842/68941636-0fbb0a80-076c-11ea-8b50-dac2d48d64ee.png)

![image](https://user-images.githubusercontent.com/40315842/68941650-15185500-076c-11ea-9fc8-b7233db9d26a.png)

**Comment by TheVekter** [comment]
Related to #47708?
