### ISSUE TITLE
Keybind scream emote makes a real scream

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#47815]
The basic *scream was made to intentionally not make noise due to how annoying it is, but the scream emote you can keybind makes the full scream noise

**Comment by kriskog** [comment]
Now we just need farting

**Comment by Tharcoonvagh** [comment]
Thank god I'm offline

**Comment by ATH1909** [comment]
You can also use hotkeys to scream while muzzled, from what I saw in a Sybil last night.

**Comment by Potato-Masher** [comment]
Not a bug.

**Comment by py01** [comment]
this got fixed
