### ISSUE TITLE
Deconstructing a ORM destroys all resources within it

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#47814]
Deconstructing a ORM destroys the resources in it. It would probably be better to preserve resources on deconstruction, here and in general.

Though, This would mean that you can deconstruct the ORM to steal the resources... but you can just steal the whole thing in 5 seconds with a wrench either way.

## Reproduction:
1: Dump ore into a ore redemption machine
2: Screwdriver it
3: Crowbar it
4: Ding Dong Your Ore Is Dead

**Comment by SpaceManiac** [comment]
ORMs are connected to the ore silo, deconstructing it disconnects it. The ores are still in the silo. Use a multitool to reconnect it.

**Comment by Firecage** [comment]
As Spacey said. the resources are no longer located inside of the ORM. That was changed when the Ore Silo was introduced. When the miners put resources into the ORM, it sends it to the Ore Silo, from where any connected machine has access to the resources(the ORM, protolathes, circuit imprinters, etc.)

**Comment by kriskog** [comment]
Closing this then. Check the silo

**Comment by Buggy123** [comment]
Oh, whoops. My bad.
