### ISSUE TITLE
pAIs holoform gets separated from its main body

### ISSUE THREAD

**Issue by Archanial** [tgstation/tgstation#47825]
Issue reported from  Round ID: 123819 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471

Steps to reproduce: 
1. Start being scooped.
2. Be in someones hands as holoform.
3. Click: toggle holoform.
4. 2 pAIs???

Probably not intended but pretty epic. Could be changed slighty to become feature.
Oh also clown tried to delete pAI and while doing so I lost my encryption keys (shouldn't they pop out while doing so?).

**Comment by Coconutwarrior97** [comment]
Found a similar issue with fireworks going off while a pAI is in holoform on someone's head. (Likely if in hand as well). 

Steps to reproduce:

1. Place pAI holoform on head
2. Light firework and place below you.
3. Boom, 2 pAIs
![image](https://user-images.githubusercontent.com/40315842/73912289-bdc0e700-4879-11ea-9bb0-56bdb4c6b1db.png)
