### ISSUE TITLE
Silicon chat messages have an extra line after them

### ISSUE THREAD

**Issue by Lett1** [tgstation/tgstation#47822]
## Round ID: 

Doesn't matter

## Reproduction:

![](https://i.imgur.com/g5hs8HK.png)

Play borg or be a ghost and watch silicon messages be spaced out.

**Comment by kriskog** [comment]
Dupe of #47805

**Comment by cacogen** [comment]
No, this wasn't a dupe. It's still an issue. Saw it yesterday. 

![](https://i.imgur.com/LfcsbsR.png)

**Comment by kriskog** [comment]
Dupe chains some times get confusing, not sure why I closed the other one it was supposed to be a half-close sort of deal.

**Comment by dragomagol** [comment]
Appears to have been fixed.
