### ISSUE TITLE
Bluespace body bags can capture megafauna

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#47832]
If you quickly fold up the bluespace body bag with the megafauna in it, you can pokemon it and keep it in your backpack. Most megafauna have an ability that teleports them out of the bag, but some, like a colossus, can be kept permanently in your backpack then popped out later.

**Comment by MCterra10** [comment]
feature???

**Comment by mrhugo13** [comment]
The issue is that bluespace body bags allows `MOB_SIZE_LARGE` in, and megafaunas are in the `MOB_SIZE_LARGE` part of `MOB_SIZE`

**Comment by HomocidlePancakes** [comment]
Surprised you didn’t consider this a bug back when you could use the love potion on fauna.

**Comment by AnonymousNow** [comment]
Absolutely a feature.
