### ISSUE TITLE
Crashing clients and inducing lag with the new emotes (binding same key to emotes multiple times)

### ISSUE THREAD

**Issue by coolsurf6** [tgstation/tgstation#47831]
ISSUE:
It is possible to bind the same key to the same emotes as well as binding them to every emote possible. This can induce some heavy lag to the point of crashing the user's client as well as others around them. Depending on the number of binds, you can either tap fast or macro it. 
![image](https://user-images.githubusercontent.com/16472329/69002688-a3910000-093f-11ea-898f-ca037eaebeb9.png)

Possible fix:
Make emotes fall in line with how auto-clicking was stopped. Limit emotes if they are used 5 or more times a second for example. Servers, for now, are banning for it to deal with it but there should be some measures to prevent this kind of spam.

**Comment by ShizCalev** [comment]
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE
NEED A DISPENSER HERE

**Comment by Tharcoonvagh** [comment]
Stupid feature in the first place, make spamming emotes bannable
