### ISSUE TITLE
(Dubious) Summon Events ends when the wizard dies in wizard mode, but not in dynamic

### ISSUE THREAD

**Issue by Putnam3145** [tgstation/tgstation#47834]
Pretty much self-explanatory. Could be a feature, depending on how you look at it. The code looks more like an oversight to me, so it's worth pointing out.

**Comment by kriskog** [comment]
Dynamic doesnt end round on antagonist loss, this is intentional. Summon events should also be disabled in dynamic, outside admin shenanigans.

Summon spells no longer making round continuous in wizard mode is also intentional.

**Comment by Putnam3145** [comment]
Oh, y'all disabled summon events for dynamic? Huh. Didn't know that. No, I was pointing out that summon events is cleaned up in wizard mode, explicitly, while dynamic doesn't bother with it.

**Comment by kriskog** [comment]
See #47514 for the recent changes to wizard mode
