### ISSUE TITLE
Harvesters can be damaged by the limbs that they rip off of their victims

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#47842]
I'm talking about the cult construct here, not the machine.

In a similar vein, ash walkers can often get damaged by the limbs that fly everywhere when they sacrifice a humanoid corpse to their tendril.

**Comment by Tharcoonvagh** [comment]
It's the same with every mob, what is the issue here? Like I once died to a flying arm as a rev with an axe

**Comment by ATH1909** [comment]
Well, the whole gimmick (or, well, most of it) of harvesters is ripping off limbs, no?

Also, I'd like to be able to witness my sacrifices to the tendril as an ashwalker without taking damage.

**Comment by PKPenguin321** [comment]
Not a bug
