### ISSUE TITLE
a message is missing a "the"

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#47840]
![image](https://user-images.githubusercontent.com/222630/69020994-32ffd880-096b-11ea-994c-e867f4b381bc.png)

> You secure machine frame.

**Comment by Tharcoonvagh** [comment]
Unga

**Comment by HomocidlePancakes** [comment]
Grug secure

**Comment by TheVekter** [comment]
Grug fix.

**Comment by TheVekter** [comment]
Unga fix issue in #47860.
