### ISSUE TITLE
Got sent to Centcom in the supply shuttle and died at the end when it arrived.

### ISSUE THREAD

**Issue by Dimy003** [tgstation/tgstation#47848]
## Reproduction: Time of the round 20:46:25 search by “Dimy003” to find it, no idea how to reproduce it.

It’s my first bug report so sorry in advance if I didn’t do it correctly.

**Comment by PKPenguin321** [comment]
It killing you is working as intended, the bug is that it shouldn't allow the shuttle to be sent at all with a mob inside. You must have pushed a button to send the shuttle or been on the shuttle, can you give any more details?

**Comment by NoxVS** [comment]
All non machinery is deleted and sold when the shuttle docks. I know a way to bypass this deletion so if there is a bug that lets you get onto the shuttle when its sent then its currently possible to break into Central Command.

**Comment by TheVekter** [comment]
> All non machinery is deleted and sold when the shuttle docks. I know a way to bypass this deletion so if there is a bug that lets you get onto the shuttle when its sent then its currently possible to break into Central Command.

Not this shit again. 

DM the info to a maintainer so we can get it fixed, please.

**Comment by Dimy003** [comment]
I was arranging crates in the shuttle and someone else sent it, I didn’t do anything other that moving freight so I don’t know what triggered it to allow me to be sent.

**Comment by NoxVS** [comment]
> I was arranging crates in the shuttle and someone else sent it, I didn’t do anything other that moving freight so I don’t know what triggered it to allow me to be sent.
> The cargo logs say that I was sent with bounty items onboard so maybe it could be a cause?

Even with bounties it shouldnt allow the shuttle launch process to begin if there are organisms or nuclear things onboard and will cancel it if it reaches 0 and there are organisms or nuclear things on it.

**Comment by TheVekter** [comment]
Honestly makes me consider just having the cargo shuttle hang out somewhere that's not centcom while it's being filled

**Comment by Timonkeyn** [comment]
Maybe you can abuse the milliseconds that it takes to launch to get on similar to how much it takes for the meteor shuttle to land and you can move to wherever you want in the shuttle after the blue circles go away

**Comment by Timonkeyn** [comment]
Yall know what freight hopping is IRL? similar to that

**Comment by trollbreeder** [comment]
MAILING MYSELF TO CENTCOM CHALLENGE!!! 2019 [GONE WRONG]

**Comment by TheBonded** [comment]
There are ways to get to centcom via the supply shuttle- which is an issue on it's own -, but it killing you upon arrival is intended
