### ISSUE TITLE
Floortile Mat Dupe Glitch

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#47857]
## Problem Description:
There is a way to duplicate most mats the ORM can process. (Metal, Silver, Gold, Plasma, Uranium, Diamond, Titanium)

## What did you expect to happen:
I expected that removing sheets from a protolathe/techfab, converting them into floortiles, and inserting the floortiles back into the protolathe/techfab would produce no net change in the number of mats available.

## What happened instead:
Doing so resulted in a significant net increase in the number of mats available.

## Why this is bad/What are the consequences:
Most mats can be produced in massive amounts for trivial effort and no risk.
If glass and bluespace crystals didn't exist this would basically invalidate the miners contribution to the station beyond the first delivery of mats.

## Steps to reproduce the problem:
1. Remove mats that can be converted into floortiles from a protolathe/techfab as sheets.
2. Convert the sheets into floortiles via the sheet crafting menu. (Left-click a sheet, spam floortilesx4 until you run out of sheets)
3. Cram the floortiles back into the protolathe/techfab.
4. Notice you have more mats than you started with.
5. GOTO 1

## Server:
Bagil

## Revision:
Round ID:  123908 
BYOND Version:  512.1484 
Server revision compiled on:  
Master commit: 738bda22f382c2091e623708c204f5555f91bdaf 
The following pull requests are currently test merged: 
#47817: 'Smooth move rising: revengeance (60 fps DEFAULT)' by actioninja at commit f30b79b32b 
#47742: 'Removes the non bitflag slot defines' by ninjanomnom at commit 272812713d 

Local commit: 981ec061a769e9bfe0d9f95ea274a05b84cb58ee 
Server tools version: /tg/station 13 Server v3.2.6.2 

Current Informational Settings: 
Protect Authority Roles From Traitor: 1 
Protect Assistant Role From Traitor: 0 
Enforce Human Authority: 1 
Allow Latejoin Antagonists: 1 
Enforce Continuous Rounds: 10 of 20 roundtypes 
Allow Midround Antagonists: 5 of 20 roundtypes 
All Game Mode Odds: 
traitorbro 8.5% 
traitorchan 8.5% 
traitor 25.5% 
nuclear 8.5% 
cult 8.5% 
dynamic 8.5% 
extended 2.1% 
secret_extended 4.3% 
revolution 12.8% 
wizard 12.8%

## Possibly related stuff:
I specifically used the roundstart cargo protolathe/techfab.
The gold was depleted before I could get around to duping it.

**Comment by TheVekter** [comment]
#47856

**Comment by kriskog** [comment]
Closing in favor of #47856
