### ISSUE TITLE
Material Duplication Using Floor Tiles

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#47856]
## Testmerges: 
#47817
#47742

## Reproduction:
1. get 50 sheets of a material you can make floor tiles with
2. make all the sheets into floor tiles
3. put floor tiles into ore silo or a machine linked to the ore silo
4. profit -- while 50 sheets is worth 100,000 units of material in the lathes, 60 floor tiles is worth 120,000. with one stack of 50 sheets you can make several stacks of 60 floor tiles, thus duplicating materials

**Comment by TheVekter** [comment]
Oof.

Should be an easy fix. I'll take a look shortly.

**Comment by zxaber** [comment]
There's a separate (but related) issue where if you keep one sheet of the old stack left, its `custom_materials` list still has the same value the stack had when it was created. Ergo, if you have a stack of 50 sheets of metal, you can convert all but one stack to rods or something, that one sheet will still have 100000 units of iron in the `custom_materials` list and so will add 50 sheets to any machine you stick it in.

All of this is also different from the dupe bug where the `custom_materials` list is not updated when you split a stack, which I do have a fix for already PR'd.

**Comment by Paxilmaniac** [comment]
currently you can use this to get lots of cargo cash with plasma sheets, while bikes are fun, rip war ops

**Comment by optimumtact** [comment]
```
10:20 Gamer025:Yeah I just tested 47856 by crafting 50 metal sheets into floors and putting them into the ORM didn't result in more materials
10:20 Gamer025:So I guess that can be closed
```
