### ISSUE TITLE
Photocopiers only work for single copies

### ISSUE THREAD

**Issue by Teepeepee** [tgstation/tgstation#47853]
## Testmerges:
didn't check lol

## Reproduction:
put a paper inside a photocopier and try making it copy it more than once, only one copy will come out, if you hit copy again you get another copy, making it work but only one at a time, when you used to be able to make it make many copies without having to hit copy every time.

**Comment by kriskog** [comment]
#47634 replaced some sleeps with timers in the copier code. Since the timer doesnt stop the proc, it doesnt reset busy before next time it loops so never prints more than once.

@spookydonut
