### ISSUE TITLE
Cannot make nitroglycerin 

### ISSUE THREAD

**Issue by Moonman121** [tgstation/tgstation#47864]
## Round ID:
Round ID: 123921

## Reproduction:
Nitroglycerin does not form when the ingredients are placed in a beaker. First I tried making it with a debug chem machine and it didn't work, thinking it may have been a debug chem machine thing I VV'd the ingredients into separate small beakers then mixed them into a bluespace beaker, that didn't react either.

**Comment by kriskog** [comment]
Recipe changed in #47536. Now requires nitric acid instead of fluorosulphuric acid.
