### ISSUE TITLE
Keybinding ignore movement keys when you ctrl/shift click and some othere combination

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#47869]
## Reproduction:
Cause №1
1. Join game
2. Keybind you movement on arrows
3. Press move in any direction
4. Shift click to examine something on screen
5. You stop moving in direction you pressing arrow in step 3 all othere 3 direction keys working

Casue №2
Repeat 1-3
4. Ctrl click anywhere on screen
5. You stop moving in direction you pressing arrow and all movement keys not working

Cause №3
Repeat 1-3
4. Click airlock on your way
5. You stop moving even airlock is opened

Cause №4
Repeat 1-3 
3.1 Additional set END button to toggle throw mode like boomer
4. Pick something from backpack
5. Press END to activate throw mode
6. Click with mouse on screen
7. Object thrown and you stop moving even you proceed pressing moving key
Cause №5
Repeat 1-3
4. Move diagonally
5. Click with mouse on screen
6. You stop moving diagonally

My keybindings if it helps
![image](https://user-images.githubusercontent.com/5034345/69090868-9587d000-0a62-11ea-8b16-bbc8f0198618.png)

**Comment by kopoba** [comment]
@Couls no way to fix this?

**Comment by Couls** [comment]
Unsure yet, Ctrl is hardcoded to stop movement so facing works but if I remove it you won't be able to face directions because you'll just move can't really stop movement everytime you change directions either

**Comment by kopoba** [comment]
> 
> 
> Unsure yet, Ctrl is hardcoded to stop movement so facing works but if I remove it you won't be able to face directions because you'll just move can't really stop movement everytime you change directions either

its not just ctrl ctrl is less problem like you not always want pull things while run.
Running and shooting is worst scenario when you need to maneuver in maintenance with 2 directional keys and when you shoot you just stop running. ided

**Comment by Couls** [comment]
unless you're pressing ctrl before you shoot it shouldn't be stopping you

**Comment by kopoba** [comment]
> 
> 
> unless you're pressing ctrl before you shoot it shouldn't be stopping you

Reproduction in cause №5
get gun move in diagonal direction using 2 arrows in same time shoot! 
You stop moving in diagonal direction and will move only in last direction you pressed
It feels like new code prevent you from using 3 keys in same time and when you try to do this it will just drop first one.
Cause №4 is excellent example about my theory with 3 keys limit
1. Key you moving with
2. End to Toggle throw mode
3. Click with mouse(here we catch limit and you just stop moving)

**Comment by Couls** [comment]
Okay I see what you mean now let me do some testing

**Comment by kopoba** [comment]
okay can we reopen this problem is still persist

**Comment by kopoba** [comment]
@Mothblocks

**Comment by Mothblocks** [comment]
without testing i'll reopen it but i don't know if it's fixed in the new prefs menu

**Comment by TheBonded** [comment]
ctrl is set to stop movement by default, you can rebind it in preferences. this is no longer an issue, as far as I can tell.
