### ISSUE TITLE
RDX cannot exist in stable form

### ISSUE THREAD

**Issue by paulgatto** [tgstation/tgstation#47877]
RDX explodes upon mixing at 404K and cannot be stabilized, or exist as a chemical. This is contrary to what was written in the wiki - it seems to have two explosion possiblilities, one at 404K and one at 474K (the latter cannot be reached in most cases.)

Reproduction: Make RDX

**Comment by Tlaltecuhtli** [comment]
https://github.com/tgstation/tgstation/blob/6ee01f29779a01c584929e5fc1159dd775ec246c/code/modules/reagents/chemistry/recipes/pyrotechnics.dm#L56
https://github.com/tgstation/tgstation/blob/6ee01f29779a01c584929e5fc1159dd775ec246c/code/modules/reagents/chemistry/recipes/pyrotechnics.dm#L57

**Comment by TheVekter** [comment]
![image](https://user-images.githubusercontent.com/7019927/69171526-c21f0480-0ac1-11ea-8108-e6daf273525e.png)

Yeah, worked fine for me. Can't replicate.

**Comment by FloranOtten** [comment]
It's entirely doable to get stable, though in my experience it did blow up upon mixing when not in the presence of stabilizing agent.

**Comment by paulgatto** [comment]
This seems to be an issue with either my chemfactory setup, or a chemfactory bug - will update on further issue.
