### ISSUE TITLE
PARTICLE BEAM RIFLE has no back sprite

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#47882]
Not sure if I'd call it a bug, but someone should probably make one.

![image](https://user-images.githubusercontent.com/7019927/69144556-27a6cd00-0a91-11ea-95d6-b8221aca2504.png)

**Comment by Firecage** [comment]
Isn't that the beam rifle though?

**Comment by TheVekter** [comment]
It's the particle beam rifle, whatever it's called. It's a fucking railgun. It fires like a railgun, okay?
