### ISSUE TITLE
Pocket Extinguishers can be emptied from storage containers

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#47883]
Not sure if it was something specific I was doing but you can altclick pocket extinguishers to empty them inside of bags and the like.

I've not given this very proper testing but I've actually done this a few times without even realizing this wasn't intended behaviour because I only just found out that this wasn't supposed to be possible.

**Comment by kriskog** [comment]
Let them, but make the bag make squishing sounds after.

**Comment by necromanceranne** [comment]
FYI the intended behaviour is supposed to be that you can only do it in hand, so you can't do it from your back for stealth slips. More than a few times I've disarmed people without warning using this but since I only have pocket extinguishers on me for space efficiency, it never occurred to me what I was doing was unintended until I saw alt-click extinguishers being ported over to another branch and had the fix to stop bag extinguisher slips.

**Comment by kriskog** [comment]
They used to be put in pockets and used to slip without putting in hand first. The fix should have sorted the in bag usage too though, not sure whats happened.
#46398

**Comment by PepperPrepper** [comment]
Now I may be overthinking this but I thought I'd bring it up none the less. Is there any chance custom hotkeys broke alt clicking? It's is like the only thing I could think of that should be affecting this as 
`if(!user.is_holding(src))
		to_chat(user, "<span class='notice'>You must be holding the [src] in your hands do this!</span>")
		return`

seems right.

**Comment by PepperPrepper** [comment]
I tested this locally and was unable to empty extinguishers from my backpack and my pockets. I'm fairly sure the fix works as intended.

**Comment by necromanceranne** [comment]
This was something I observed before custom hotkeys so maybe something fixed it in the meantime? I'll have to give it more tests I suppose.
