### ISSUE TITLE
A Couple Bola Issues

### ISSUE THREAD

**Issue by Pugie** [tgstation/tgstation#47893]
My initial hunch would be that these issues are caused by https://github.com/tgstation/tgstation/pull/47847

First of all, energy bolas don't apply slowdown at all now, none.
Secondly, removing all other bolas does not reset the victim's speed back to normal. Instead they will walk at the speed as if they were bolad until they pick up an energy bola.

**Comment by kriskog** [comment]
Wasnt fixed by the recent bola slowdown fix PR

**Comment by ShizCalev** [comment]
server, server revision, ect please.

**Comment by ATH1909** [comment]
So, er, how does this trick work, exactly? I couldn't replicate it consistently, and some people reported it wearing off after a while?

**Comment by TheVekter** [comment]
Not sure but I was able to reproduce it on current build. I didn't try long enough to see if it wore off or not.

**Comment by ATH1909** [comment]
> Not sure but I was able to reproduce it on current build. I didn't try long enough to see if it wore off or not.

What were the exact steps that you took to reproduce it?

**Comment by TheVekter** [comment]
> > Not sure but I was able to reproduce it on current build. I didn't try long enough to see if it wore off or not.
> 
> What were the exact steps that you took to reproduce it?

1) Spawned in normal bola and energy bola
2) Threw energy bola at a dummy
3) Swapped to dummy's body by ghosting and dragging
4) Was able to walk without issue

Did basically the same steps with a reinforced bola and was still slowed after removing it until I picked up an energy bola.

**Comment by ATH1909** [comment]
> > > Not sure but I was able to reproduce it on current build. I didn't try long enough to see if it wore off or not.
> > 
> > 
> > What were the exact steps that you took to reproduce it?
> 
> 1. Spawned in normal bola and energy bola
> 2. Threw energy bola at a dummy
> 3. Swapped to dummy's body by ghosting and dragging
> 4. Was able to walk without issue
> 
> Did basically the same steps with a reinforced bola and was still slowed after removing it until I picked up an energy bola.

Did you try this with a normal bola? Did you try picking up [whichever kind of bola you were hit with] before picking up an energy bola?

Did you try having someone else remove the dummy's bola?

**Comment by Pugie** [comment]
It seems to be putting any item into your hand fixes the bola slowdown persisting, not just e-bolas.

**Comment by ATH1909** [comment]
> It seems to be putting any item into your hand fixes the bola slowdown persisting, not just e-bolas.

_Any_ item, not just bolas?

**Comment by TheVekter** [comment]
> Did you try this with a normal bola? Did you try picking up [whichever kind of bola you were hit with] before picking up an energy bola?

Pugie says picking anything up fixes it. I tried this with a PDA and it works.

> Did you try having someone else remove the dummy's bola?

No, I was the only one on the server.

**Comment by PKPenguin321** [comment]
Is this an issue with bolas or legcuffs in general

**Comment by Timonkeyn** [comment]
Maybe it's an issue with bolas ceasing to exist upon removal?
