### ISSUE TITLE
From-ghosts dynamic rulesets don't respect required_candidates

### ISSUE THREAD

**Issue by Putnam3145** [tgstation/tgstation#47896]
from_ghosts dynamic rulesets check if there are *any* candidates:

```
if(!candidates || candidates.len <= 0)```
And then check if there are *0* candidates again, later, 

```
/datum/dynamic_ruleset/midround/from_ghosts/proc/review_applications()
	for (var/i = 1, i <= required_candidates, i++)
		if(candidates.len <= 0)
			if(i == 1)
				// We have found no candidates so far and we are out of applicants.```

But never actually checks if there are *enough* (this is the only check on candidates being left and it only activates if i == 1, which is only on the first check), it only uses it as a guideline to set *maximum* candidates, which isn't... really what is wanted, I don't think.

**Comment by SuperNovaa41** [comment]
Yeah so dynamic has been fully reworked and redone so...
