### ISSUE TITLE
Back worn icons of energy guns not updating.

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#47901]
## Reproduction:
Basically, when you wear an energy gun on your back, for example an Ion Rifle, the icon doesn't get updated to show how much charge the weapon currently has left. So with the basic Ion Rifle back worn icon, it shows the gun at full charge. Even if you shoot the gun to half charge, or fully empty it, the gun will still show that it is fully charged while it is worn on the back. The same applies to Pulse Rifles(except that the basic back worn icon of it has no charge bar, so it just always shows a pulse rifle with no charge bar). I assume it would also be the same for Lasercannons, the only other energy gun with an icon for when worn on the back.

I encountered the issue when I attempted to get the empty back icon for an energy gun to work which I am PR'ing. After repeatedly failing, I decided to test if it even works with the other energy guns, and lo and behold, it didn't.

**Comment by ShizCalev** [comment]
Believe this was caused by #10628

The old system used to change the gun's iconstate to represent the charge level. Since that doesn't happen anymore as we use overlays for the charge meters, which isn't applied to the back.

**Comment by ShizCalev** [comment]
@Jordie0608

**Comment by Firecage** [comment]
@ShizCalev Actually, it appears to not just be energy guns, but ballistic guns to, but much less noticable. But it is likely due the same changes even if it was in a separate PR aimed at ballistic guns.

**Comment by ShizCalev** [comment]
Fixed
