### ISSUE TITLE
Retro laser gun and captain's laser don't use the empty overlay when it doesn't have enough charge to fire.

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#47908]
Master. Found during debugging. 

https://github.com/tgstation/tgstation/blob/f5bd6a381d18765624b81b4aca7fa4126b9dc2ca/code/modules/projectiles/guns/energy.dm#L133-L167

Think this line is to blame
https://github.com/tgstation/tgstation/blob/f5bd6a381d18765624b81b4aca7fa4126b9dc2ca/code/modules/projectiles/guns/energy.dm#L140-L141

**Comment by ShizCalev** [comment]
happens with captain's egun too.

likely #39885 ? @SpaceManiac 

both the captain's egun and the retro laser are returning here on the last shot without updating.
```
	if(ratio == old_ratio && !force_update)
		to_chat(world, "returned")
		return
```

on the last shot for the retrolaser, the gun has 4 charge remaining.

**Comment by SpaceManiac** [comment]
#39885 prevents the ratio from going below 0 or above 1 so kevinz can't crash the server by VVing one number, CEILING was already involved and it's that what's counting 4 charge as still having juice

**Comment by ShizCalev** [comment]
This was fixed before from the looks of it;
#5399
