### ISSUE TITLE
Kilostation still has budget cards

### ISSUE THREAD

**Issue by MCterra10** [tgstation/tgstation#47906]
## Reproduction
1. Play kilostation
2. Profit??

(get it? profit? I'll leave)

**Comment by Tharcoonvagh** [comment]
Kilo has circuitry too, ples fix

**Comment by kriskog** [comment]
I just looked through the file, and am unable to see any reference to the budget cards. Are you on current master?

**Comment by MCterra10** [comment]
Hmm I think this might have been an oversight on my part. Closing this
