### ISSUE TITLE
Splitting stacks and putting them back in makes negative materials

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#47910]
## Testmerges: 
#47817

## Reproduction:
1, Take a stack of materials and put it in a machine connected to the ore silo
2. Take that stack back out and split it
3. Put in the now split stacks, one will put negative materials into the lathe and the other will be normal.
4. Cry at your waste of materials.

**Comment by Couls** [comment]
@zxaber

**Comment by ShizCalev** [comment]
#47888 should fix this.
