### ISSUE TITLE
Chemical filter is broken 

### ISSUE THREAD

**Issue by Timonkeyn** [tgstation/tgstation#47924]
It has no hud(Terry)

**Comment by Time-Green** [comment]
Are you sure it wasnt just depowered?

**Comment by Tharcoonvagh** [comment]
Maybe byond issue
Round id please 
How to reproduce
>Are you sure it wasn't just depowered?
Have you tried it with other machines too?

**Comment by kriskog** [comment]
Fix merged #47930
