### ISSUE TITLE
You can put combat defib paddles in a bag of holding

### ISSUE THREAD

**Issue by DrSirKnight** [tgstation/tgstation#47925]
Doesn't work with normal bags, only bags of holding

## Reproduction:
Equip bag of holding and combat defib
Take paddles off the defib and proceed to put them in the bag of holding

**Comment by kriskog** [comment]
Doesnt really hurt much, but a bug is a bug. 

To fix, either make paddles snap back when not in hand slot or add a flag akin to ITEM_SLOT_DENYPOCKET but for backpack.
