### ISSUE TITLE
Chat considers all PDA emojis as the same message

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#47928]
So here is an example. Let’s say you do a “:1997: :up:”. Then right after you do a “:nya: :revolver: :up:”. Chat is going to consider these two as the same message, so the chat will end up removing the first message and showing “:nya: :revolver: :up: x2”, implying there wasn’t a message in chat inbetween.

**Comment by JohnFulpWillard** [comment]
![image](https://user-images.githubusercontent.com/53777086/196028651-ddda5eb4-5653-423b-8280-7f9abaf28fec.png)

Looks fixed now, no idea what fixed it. Sorry
