### ISSUE TITLE
instantaneous server crash when removing a floor tile without plating under it

### ISSUE THREAD

**Issue by Lz-erk** [tgstation/tgstation#47939]
Problem Description: This was on Sybil 2 and no one was operating any 200-generator teslas, nothing much was going on crash-wise that I know of. Only a few people were on the server.

**Steps to reproduce the problem:** I saw a tile of space on my mesons, inside a maint in the station. The maint was properly spaced, so I was expecting that, but when I got there, there was a tile of fairygrass over the space tile, which was new to me. I laid all the fairygrass myself without floorbots, so my guess is that the plating was somehow removed _after_ the fairygrass was placed. I hit it with my crowbar and the server shut down. I do not know how to reproduce this problem, although admin tools yeah good luck I'm sorry. There was no damage to the surrounding plating, so I'm at a loss to explain the space tile.

**Revision:** ["Type 'show-server-revision' ingame to find out."] I'm sorry, I'm still a bit new and I must be typing this in the wrong fields or something. This was after the server adopted the **21 November 2019** update with National Hot Dog Day. And are the broodmother tentacles not a design feature?! It's a portable mining machine! ... OK whatever.

**Comment by LemonInTheDark** [comment]
Do you remember the round id?

**Comment by SuperNovaa41** [comment]
This is a fairly old issue, and if it would've happened again I'm sure we would've known about it

**Comment by LemonInTheDark** [comment]
He did not remember the round id

**Comment by LemonInTheDark** [comment]
If it makes you feel any better, I'm pretty sure there was some stupid bug with fariygrass around this time. I've not seen it pop up anymore recently tho
