### ISSUE TITLE
You can sell borg modules on the pirate ship

### ISSUE THREAD

**Issue by DrSirKnight** [tgstation/tgstation#47941]
## Reproduction:

Go on a pirate ship as borg, stand on cargo hold pad, press send on the console and watch as your modules are sold.

![526d08d9fb0b929c7fe4083566af93b9](https://user-images.githubusercontent.com/54851612/69445553-3aecbd80-0d5b-11ea-827e-189208a91e6b.png)

**Comment by ATH1909** [comment]
Does this work for dead borgs?

**Comment by ATH1909** [comment]
Which borg sells for the most credits?

Also, are those that peacekeeper borg's radios that just got sold, there? Does it get them back if its module gets reset?

**Comment by DrSirKnight** [comment]
Those radios were somehow related to the borg, as nothing else was sold there.

**Comment by ATH1909** [comment]
> Those radios were somehow related to the borg, as nothing else was sold there.

Did you try resetting the borg's module, choosing a new one, and selling the borg's contents again? Could the borg use its radio(s) after it got sold? Could it use borg chat after its radios got sold?

**Comment by ArcaneMusic** [comment]
Could easily be reworked into a feature where you scrap/sell the borg, but for now that's pretty yikes

**Comment by MCterra10** [comment]
Feature
