### ISSUE TITLE
Ghost flip is broken

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#47940]
It doesn't flip properly, it only does three quarter rotations.
Has been broken since the angry shaking ghosts were fixed a while back, but I hadnt gotten around to reporting it.

![flip](https://user-images.githubusercontent.com/33292112/69445101-f0b30e80-0d51-11ea-8187-48d9116a2797.gif)

**Comment by ATH1909** [comment]
This is broken for certain mobs as well (pAI holoforms have this issue, IIRC).
