### ISSUE TITLE
ID Console accessible without Confirmation ID

### ISSUE THREAD

**Issue by SWSoftware1044** [tgstation/tgstation#47949]
## Round ID:
124247

## Preamble:
**Problem:** ID Console can be accessed without an ID in the 'Confirm Identity' slot.
**Expectation:** I would not be able to edit a 'Test' ID without a proper 'Confirm' ID, that is, one with the "ID Console" permission.
**Reality:** I was able to edit a 'Test' ID without a 'Confirm' ID in the console, or even on my person.
**Consequences:** Everyone will be able to edit IDs, when it should be restricted.
**Server:** Event Hall
**Revision/Master Commit:** 8986dffe3062187ab83cb255f2f1b61001a79aea
**Gamemode**: Revolution

## Reproduction proper:
As the Head of Personnel (and possibly other jobs) step up to an ID console. Insert an ID into the 'Target' slot. **Do not** insert an ID into the 'Confirm Identity' slot. Proceed to edit 'Target' ID freely.

**Comment by kriskog** [comment]
The console is logged in, log out and youll need the confirm ID back
