### ISSUE TITLE
library console can easily lag server

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#47948]
reproduction:
1. open library console
2. look at the window that has the search settings (it opens 2 windows at first, yes)
3. press start search without entering any parameters
4. ???
5. profit stuck

**Comment by ShizCalev** [comment]
@actioninja since you've been fixing these

**Comment by kriskog** [comment]
Dupe of  #45284
This is the visitors console only afaik, and it pulls the entire library.

**Comment by nemvar** [comment]
since it's a dupe
