### ISSUE TITLE
Boxstation detective does not have access to reach sec protolathe

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#47958]
The place where the det is supposed to print ammo for their gun

**Comment by kriskog** [comment]
Door needs an access update. Security office should have req_one_access_txt = "1;4"

**Comment by py01** [comment]
this also applies to kilostation actually

**Comment by kriskog** [comment]
@TheVekter

**Comment by TheVekter** [comment]
Good catch. I'll fix it there and check the others while I'm at it.
