### ISSUE TITLE
Cooking desserts Crafting recipe books STILL cause the TGUI crafting menu to bluescreen

### ISSUE THREAD

**Issue by Mick1299** [tgstation/tgstation#47952]
## Server:
Austation, up to date TG downstream

## Reproduction:
1. spawn in a:
/obj/item/book/granter/crafting_recipe/cooking_sweets_101
2. Read it
3. Open the crafting menu
4. Admire the shade of blue

The boneyard notes recipe book doesn't cause the issue, so its not an inherent problem with recipes and the UI. I'm not much of a coder, but the issues probably in the defining of recipes within the Dessert book.

Boneyard notes for reference: 
/obj/item/book/granter/crafting_recipe/boneyard_notes
--
![image](https://user-images.githubusercontent.com/54165560/69475856-77d1b680-0e26-11ea-8234-7b4088720219.png)

--

**Comment by stylemistake** [comment]
This is most probably due to a missing category field on a recipe, which creates a "null" key in assoc list, which in turn is badly serialized into JSON on the BYOND part.

Eventually, JSON serialization will be patched in 513, but this is still an error in the code.

**Comment by stylemistake** [comment]
Also your screenshot reminds me that we need to address high dpi support at some point.

**Comment by actioninja** [comment]
Cannot replicate.

**Comment by actioninja** [comment]
https://github.com/austation/austation/blob/ea5d91ff2d5bdf9a6c4d17820f2bc30cbce2ba37/code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm#L157

Downstream issue.

**Comment by Mick1299** [comment]
Ahh, perfect. Thanks for taking the time to find the specific issue with our downstream
