### ISSUE TITLE
AIs can shunt continuously during doomsday to become nigh unkillable

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#47956]
AI shunted to an APC, shunted away to a different APC once people arrived to kill it, and just repeated this continuously until timer hit 0 and they won

Issue reported from  Round ID: 124306 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

**Comment by Tharcoonvagh** [comment]
Is this a bug tho

**Comment by kriskog** [comment]
Not a bug. Kill the core, and the AI cant jump to a new APC since it needs the stopover in the core.
