### ISSUE TITLE
Taser turrets hit you through dir windows

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#47959]
## Reproduction:
Go inside the AI's window cage on box station. 
Get tased.

![taser](https://user-images.githubusercontent.com/33292112/69487227-38bb5980-0e56-11ea-96b0-0abd8ea0d8a3.gif)

Likely an issue with taser projectiles as a whole since dir windows are on the same turf as you. Afaik you also get stunned on top of fulltile windows, although that is a bit more of a rare situation to be in.

**Comment by py01** [comment]
#43324

**Comment by kriskog** [comment]
Oh heck
