### ISSUE TITLE
Library database not uploading.

### ISSUE THREAD

**Issue by randomcat666** [tgstation/tgstation#47960]
I’m not sure if this is the right spot to post this, but I’m having a huge problem with my server. So I have my database set up etc etc, but for some reason when people try and post books they’ve written to the database, it only allows one to be uploaded. As soon as another is uploaded it just gets an error saying it cannot connect to the database. I’ve had a look at the db and the only book is posted on id 0. If I renumber it to any other Id then people can upload again, but the moment they do it uploads to the 0 id and nothing else can be uploaded. Any ideas how I can fix this? Any help would be very welcome

**Comment by optimumtact** [comment]
look in the mysql error log, it might give you some pointers as to what is going wrong.

**Comment by Korywon** [comment]
You could check to see if the ID is set to auto-increment. It might be the case that the database is attempting to write to the first entry instead of adding a new one.

**Comment by kriskog** [comment]
Closing since not likely not a codebase bug, hope you got it working
