### ISSUE TITLE
I just wanna tase for gods sake

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#47970]
No round ID
Testmerge: kilo by okand
You can still use hybrid tasers from ai turrets
>b-but I thought ranged stuns were g-gone

**Comment by TheVekter** [comment]
FUCK tag, please.

Also Kilo is not test merged anymore.

**Comment by spessbro** [comment]
been a thing for a very long time :/

**Comment by kriskog** [comment]
>
>
> been a thing for a very long time :/

Someone fixed it earlier this week 😂

**Comment by kriskog** [comment]
Are we sure its not just outdated server? @Tharcoonvagh this is why we want round ID

**Comment by Tharcoonvagh** [comment]
Hmm, I noticed I some time after the official fix referenced in my previous issue, 
if someone could try to reproduce this by deconstructing an AI sat turret, I'd be glad.

**Comment by Tharcoonvagh** [comment]
Previous one: #47454

**Comment by Tharcoonvagh** [comment]
Tested on Terry today, can't use em anymore
Round id: 124443
