### ISSUE TITLE
Deep frying a intellicarded AI doesn't produce a death message in deadchat

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#47989]
Round ID: 124470

I honestly have no idea if this is a bug or not, or important or not, but it feels like one of those edge cases that could be causing other issues.

**Comment by PKPenguin321** [comment]
I'm guessing this is because the intellicard isn't a real mob for the purpose of the death message? Similar to brains. If you get your brain cut out you die and get a death message, but if your brain gets deleted I doubt it throws a message

**Comment by JohnFulpWillard** [comment]
Fixed when deepfrying was changed to no longer destroy the item

**Comment by Sealed101** [comment]
i'd argue that the issue jumped from the icard being fried to the icard being eaten, as that doesn't produce a death message too. but that's more of a problem with icard's destruction
