### ISSUE TITLE
JaniDrobe still costs after changing jobs to Janitor

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#47988]
## Round ID:
124470 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
512.1488

## Reproduction:

1. Spawn as an Assistant
2. Have nothing to do
3. Have HoP change your job to Janitor
4. Update your PDA to your new job title
5. JaniDrobe still wants money for standard equipment
6. You don't have enough money to buy what you need

**Comment by kriskog** [comment]
HoP pranked you and gave you a custom role named janitor instead of the preset. ¯\\\_(ツ)_/¯

Inclined to say emergent gameplay on this one as a simple job name change would otherwise let you bypass 90% of economy. Agent ID buff. Discuss
