### ISSUE TITLE
Golems can't wear cloaks.

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#47992]
As it says on the tin - golems can't wear cloaks. This is inconsistent from their ability to wear bedsheets as capes, as cloaks are also loose over-covers.

**Comment by HomocidlePancakes** [comment]
I guess you are referring to the goliath cloak. It’s closer to a trench coat than a cape.

**Comment by kriskog** [comment]
The goliath cloak goes in exosuit, intended.

**Comment by AnonymousNow** [comment]
That's a different kind of consistency issue, then.
