### ISSUE TITLE
lagspike when you first enter the game

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#48008]
either by roundstart or latejoin, you get like 10s of lagspike(ping goes to 900) as soon as you spawn in the game as not observer
its happening for at least a week?

last time this was caused by a bunch of duplicate icons being downloaded when you enter the station so i guess its something similar

other person's proof it happens on round id 124518:
![9999999999999](https://user-images.githubusercontent.com/33834933/69658112-dcd21a00-107b-11ea-8ead-5e56802736fc.JPG)

**Comment by optimumtact** [comment]
this almost certainly isn't duplicate icons, just the usual set of assets downloading.

I don't really know of a way to fix this, other than trying to further reduce the number of assets sent.

**Comment by optimumtact** [comment]
it could also indicate you missed the CDN and needed to fetch rsc files on demand

**Comment by HomocidlePancakes** [comment]
I’ve noticed this happening after updating to 513 if that helps.

**Comment by projectkepler-ru** [comment]
no longer applicable @Time-Green

**Comment by Time-Green** [comment]
I'm content in closing it, I haven't noticed it in forever
