### ISSUE TITLE
Arrhythmic knife can be used to constantly be at meth speeds

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#48009]
Anytime you pick the knife up, or change what your hands are holding, the speed the knife gives you changes. The knife can either speed you up or slow you down, so if you keep picking the knife up and dropping it eventually you will be at meth speeds until you next drop the knife or change what your other hand is holding.

Issue reported from  Round ID: 124525 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

**Comment by TheVekter** [comment]
If you drop the knife, does your speed go back to normal while it's not in your possession?

**Comment by NoxVS** [comment]
Yes

**Comment by kriskog** [comment]
What is the intended use of this one? Why is this bad?

**Comment by PKPenguin321** [comment]
It's supposed to alternate your speed from high to low on a rhythm with there being no net gain or loss in distance over time

**Comment by NoxVS** [comment]
> It's supposed to alternate your speed from high to low on a rhythm with there being no net gain or loss in distance over time
> 
> This is bad because bagging and redrawing the knife during the slow part skips it, which means you only have the fast part
> 
> Can be fixed by making it start on the slow part

You misunderstood what happens entirely.

The speed doesnt change while you are holding it. It changes whenever you pick the knife up or change your hands. Otherwise it doesn't change meaning if you pick it up and are fast and never pick anything else up or drop it then you will always have meth speed.

**Comment by TheVekter** [comment]
I'm taking a guess because I haven't looked at the code yet, but what's probably happening is the speed is stacking on itself when you pick it up and not resetting until you drop it or pick something else up. So you just switch it between your hands and go sanic fast all the time. Which is a problem for obvious reasons.

Expected is that it should... not do that.

**Comment by NoxVS** [comment]
> I'm taking a guess because I haven't looked at the code yet, but what's probably happening is the speed is stacking on itself when you pick it up and not resetting until you drop it or pick something else up. So you just switch it between your hands and go sanic fast all the time. Which is a problem for obvious reasons.
> 
> Expected is that it should... not do that.

Thats not how it works.

Each time your hands change (IE picking up the dagger, picking up/dropping something else) change the speed the dagger grants. This speed will never change until you either drop the dagger or drop/pick something else up with the other hand

If you pick up the dagger and are slow you will be slow until you change what you hold

If you pick up the dagger and are fast you will be fast until you change what you hold

**Comment by PKPenguin321** [comment]
Oh, so it's just completely broken

**Comment by NoxVS** [comment]
This ended up getting fixed some point in the past
