### ISSUE TITLE
Soulstones can Only Shard a Body with a Ckey still attached

### ISSUE THREAD

**Issue by Taylorkills2** [tgstation/tgstation#48018]
## Round ID:
Various, I have't used one for about a week so I can't add one personally.

## Testmerges:
Various as this is an ongoing issue for weeks/months.

## Reproduction:
1. Be in a body, die, use ghost function to prevent revival.
2. Inhabit a different body, use a soulstone on the corpse, it will not create a prompt for dead players nor give you the phrase there's no soul in the body and it's attempting to draw it back.

OR

1. Shard a roundstart corpse from morgue, a dead humanized monkey, any lavaland roundstart corpse(human, golem, etc)
2. Soulstone doesn't do anything, same outcome as first example.

I do not believe this is intentional as this https://github.com/tgstation/tgstation/pull/46881 PR was to stop soulstones from sharding Lichs, possibly skeletons, and people who sell their soul to the devil.
However when it was PRed it stoped any simplemob/roundstart humanoid corpse from being shardable, but you could still shard old corpses that had been cloned, or corpses that had a Ckey attached at one time.

And about 3/4 weeks ago Soulstones stopped sharding anything that didn't have an active Ckey attached to it. I have no idea what caused it.

**Comment by Taylorkills2** [comment]
Even if this is exactly how Soulstones are intended/desired to work now, I believe there is still Old Code somewhere for messages and processes for when a Soulstone fails to immediately shard a corpse and creates a ghost prompt for a dead player to become a shade.
Unless a Coder did a code cleanup and removed this code, which might explain why soulstones changed behavior about a month ago without a PR for it.

Either way, I would be fond of it's old, original intent, behavior to come back since it could get dead players back into the round easily without requiring the sharder to kill a player and prevent them from being cloned.
Now it kinda acts as a self antag trap and encourages valid hunting from nonantags so they can actually use it to get a pocket friend/assistant.

**Comment by kriskog** [comment]
When it gives you the message about attempting to draw it back it is polling ghosts for the role as a shade. If there are no takers, the body will not be sharded.
As of #47826 this is also the case for people who suicide, ghost or otherwise permanently lose ownership of their mind. There is no coming back from these things, and you also wont be forced back by soulstones. Sharding was a test case, and worked as expected.
