### ISSUE TITLE
Button to Bolt the Doors in Arrivals Bathroom Showers Doesn't Work On Metastation

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#48016]
The button to bolt the door in arrivals bathroom showers on meta station doesn't actually do anything 

## Reproduction: 
0. be on meta station
1. go to arrivals bathroom showers
2. press the button to bolt the door
3. door doesn't bolt
4. cry at your lack of shower privacy

**Comment by TheVekter** [comment]
Caaaaaaaaan you note what map this is happening on please

**Comment by TheVekter** [comment]
Yup, I can reproduce this. Should be a quick fix.

**Comment by Iatots** [comment]
Must be the same person that moved an APC next to a fire closet.
