### ISSUE TITLE
You can Old Man Henderson Narsie using a BoH Bomb

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#48012]
Issue reported from  Round ID: 124545 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1484

I would like to congratulate James Knox on having slain Nar'sie.

And that this is bad but also super fucking hilarious. it also doesn't stop the round from ending.

**Comment by PKPenguin321** [comment]
Not a bug
