### ISSUE TITLE
Phobias handle_hearing does not apply the span class properly on messsages that are heard.

### ISSUE THREAD

**Issue by GrayRachnid** [tgstation/tgstation#48028]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Get a phobia, you can do this quickly with `foilhat`, have someone spook you with your trigger words, watch as the trigger word does not glow in chat when it should.
![image](https://user-images.githubusercontent.com/6613514/69760706-39444080-1133-11ea-9ce9-0571ec5f8bad.png)

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/a3343c5a3ece5fd3156b9a6e5bc7d17780fb2e0c/code/datums/brain_damage/phobia.dm#L87-L89
