### ISSUE TITLE
Mind reading can give wrong real name

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#48023]
## Round ID:
124588 Events EU

## Reproduction:
With the genetics upgrade mind reading the subject "Niklas Biermann" (HoS), mind was read. This gave the answer that their 'true name' was "Ava Dennis". However according to the VV this was not true. The round contained NO lings, game mode was 'Traitor' as confirmed by the Round status panel.
I couldn't see anywhere where the name Ava was taken from. No other player had that name. The HoS's backup name was something else (Zayden Williamson), so its not getting it from that.
All in all this caused security to make the assumption that the HoS was a ling and therefore was cremated.
I'm not sure where mind reading gets its names from but its certainly wrong.

## Relevant info:

Mind reading text from Detective John Jonas:
You plunge into Niklas(?|F) Biermann's mind...#You catch some drifting memories of their past conversations...#"mhm if we have cargo lets sell it"#"good job grey(?|F) man"#"on anything, instead of making someone a cap"#You find that their intent is to help...#You uncover that his true identity is Ava Dennis. 

"Victim":
Niklas Biermann. Round Start HoS. Mindsheilded

Current Game Mode: traitor

**Comment by peoplearestrange** [comment]
Has happened again in this round with another player:

Info:
Player name: Billy Bob
Mind read name: Makenzie Bashline
Mind read text: You plunge into Billy(?|F) Bob's(?|F) mind...#You catch some drifting memories of their past conversations...#"recall y/n"#"its sugar i think"#"i am back"#You find that their intent is to disarm...#You uncover that his true identity is Makenzie Bashline. 

However this time there is a line with that name in their VV:
1[17:22:53] /(Billy Bob) (Cloning Lab (94, 94, 2)) = "Client /(Billy Bob) has taken ownership of mob Makenzie Bashline(/mob/living/carbon/human)"
2[17:22:53] *no key*/(Billy Bob) (Cloning Lab (94, 94, 2)) = "*no key*/(Billy Bob) is no longer owning mob Makenzie Bashline(/mob/living/carbon/human)"

It appears that this time it took the name from "Old names" rather than the characters "real name" Var
https://i.imgur.com/JV51DJ8.png

Though interestingly the original bug report person DIDN'T have that as their old name:
https://i.imgur.com/GOuyihT.png

**Comment by peoplearestrange** [comment]
Blue space had this to say on it as well:
"I was also affected by the mindread bug and killed because of it. I had been killed and cloned by security earlier in the round, and mind read said my true name was Mia Beck. This name has no relevance to me and is not on my profile anywhere.

I think what might be happening is a human is created when you're cloned, and before your name and values are applied to it, it defaults to a random name, which the game is considering your true name. "

**Comment by PKPenguin321** [comment]
If that's the case it sounds like an issue with cloning
iirc I made it get real name by locating DNA and pulling dna.realname

**Comment by kriskog** [comment]
This should probably just read off your minds real name anyhow.

**Comment by PKPenguin321** [comment]
Do minds and DNA have different real name values? Really stretching my memory but I think I only used DNA because there was no alternative

**Comment by kriskog** [comment]
Mind name should consistently be the one that you spawned in as, while dna unless changed with the rest of the appearance will have the new'ed humans first name. This is a cloning issue, sure, but mind should be accessible in anything you can use this on.
