### ISSUE TITLE
explosions on items like guns/stunbatons ex_act() theirs contents(cell) which when they delete it causes the item to be break forever

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#48020]
known effects:
-stunbaton with turned on icon, on examine says "it has no cell" , wont stun people and cant be screwdrived to replace the cell

-guns with overlays stuck that wont be able to fire #47185

should the ex_act() not iterate on all items inside or should it be a  feature and have interactions to fix the cell inside

**Comment by zxaber** [comment]
I bet this also affect borgs, which have a tendency to occasionally lose random tools after explosions.

**Comment by timothymtorres** [comment]
It appears #48108 and #48107 fixed this issue.
