### ISSUE TITLE
Soulshards can no longer absorb ambient souls from soulless bodies

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#48049]
To perform: apply soulshard (discovered originally with a purified soulshard, but with some admin-assisted testing discovered that it also applies to the other two types of soulshard, red and mysterious old red) to dead body that doesn't currently have a ghost assigned to it, either because its owner has logged/is in another body or the body never had a soul to begin with.

Intended behaviour: User sees this message - "Capture failed!: The soul has already fled its mortal frame. You attempt to bring it back... " - and an ambient soul is dragged into the shard (IIRC there was a prompt - "Do you want to play as Shade of X?"), who then becomes said shade or spirit.

Actual behaviour: Nothing. Literally nothing. No message for ghosts. No message for the user. 

This used to be a fun way of getting ghosts back into the round by being able to make a construct from bodies of people who've logged off, and the way of attaining souls that actually made sense for purified soul shard owners - but instead, the functionality is just dead. I just witnessed a round with one poor blue artificer begging the roboticist to use its shards on the pile of bodies nearby, and being able to do nothing while the wizard's red constructs swelled their numbers on enemy fallen.

Thanks to some testing, we were able to discern that it's not just blue shards, but red ones, too. It was likely broken sometime around the time that blue constructs became a thing in the first place, or when they were next tweaked. Pls fix.

**Comment by nemvar** [comment]
Please don't fix. This is a shit mechanic.

**Comment by AnonymousNow** [comment]
> 
> 
> Please don't fix. This is a shit mechanic.

???
This is a fun mechanic that doesn't pop up often and lets people get back into the round.

**Comment by kriskog** [comment]
```
[17:34:55] Runtime in soulstone.dm,82: Cannot read null.hasSoul
  proc name: attack (/obj/item/soulstone/attack)
  usr: Skoglol/(Scott Smith)
  usr.loc: (Central Primary Hallway (110, 115, 2))
  src: the soulstone shard (/obj/item/soulstone/anybody)
  src.loc: Emergency Response Team Comman... (/mob/living/carbon/human)
  call stack:
  the soulstone shard (/obj/item/soulstone/anybody): attack(Savannah Lee (/mob/living/carbon/human), Emergency Response Team Comman... (/mob/living/carbon/human))
  Savannah Lee (/mob/living/carbon/human): attackby(the soulstone shard (/obj/item/soulstone/anybody), Emergency Response Team Comman... (/mob/living/carbon/human), "icon-x=18;icon-y=17;vis-x=-15;...")
  Savannah Lee (/mob/living/carbon/human): attackby(the soulstone shard (/obj/item/soulstone/anybody), Emergency Response Team Comman... (/mob/living/carbon/human), "icon-x=18;icon-y=17;vis-x=-15;...")
  the soulstone shard (/obj/item/soulstone/anybody): melee attack chain(Emergency Response Team Comman... (/mob/living/carbon/human), Savannah Lee (/mob/living/carbon/human), "icon-x=18;icon-y=17;vis-x=-15;...")
  Emergency Response Team Comman... (/mob/living/carbon/human): ClickOn(Savannah Lee (/mob/living/carbon/human), "icon-x=18;icon-y=17;vis-x=-15;...")
  Savannah Lee (/mob/living/carbon/human): Click(the floor (111,116,2) (/turf/open/floor/plasteel), "mapwindow.map", "icon-x=18;icon-y=17;vis-x=-15;...")
  Skoglol (/client): Click(Savannah Lee (/mob/living/carbon/human), the floor (111,116,2) (/turf/open/floor/plasteel), "mapwindow.map", "icon-x=18;icon-y=17;vis-x=-15;...")
```

**Comment by kriskog** [comment]
#46881 added this
```
if(!M.mind.hasSoul || isdevil(M))
    to_chat(user, "<span class='warning'>This... thing has no soul! It's filled with evil!</span>")
    return
```
It needs to check if there is a mind attached before checking if it has a soul. Try
```if(!M.mind?.hasSoul || isdevil(M))```

**Comment by AnonymousNow** [comment]
Well, that's terrible. Looks like that PR was specifically to prevent those types of antagonists from having their souls removed, but stealthily removed the offering mechanic from bodies that would normally have a soul as well, with no message and a runtime to boot.

**Comment by kriskog** [comment]
The runtime is preventing you from sharding the body. It's just a bug, not a conspiracy to nerf cult.

**Comment by AnonymousNow** [comment]
> 
> 
> The runtime is preventing you from sharding the body. It's just a bug, not a conspiracy to nerf cult.

Ah, wasn't trying to imply it was. Guess I should've used a word other than "stealthily".

**Comment by nemvar** [comment]
As to this being a shit mechanic. It helps cult get their 9 guys required really easily. Just get a few ghosts and you can quickly assemble a large amount of constructs you can use to summon.

**Comment by AnonymousNow** [comment]
I think the degree to which it's slowed by acquiring shards, bodies & shells, plus the fact that you have specialised nonhumanoid cultists that dust on death, balances that out.

**Comment by necromanceranne** [comment]
nemvar, cult has several methods to do this, so at this point you might as well more finely curate exactly what counts as a cultist than what methods allow for the cult to bring in extra bodies. 

Right now cultists can use these things for all purposes involving cult stuff, including the final summon:
1. Shades
2. Constructs
3. Those very rare instances of a simple mob being a cultist
4. Spirit Realm Homunculi (those Cult Ghosts)

**Comment by Taylorkills2** [comment]
Glad someone who knows more about code decided to look into soulshards. They'll finally be more than self-antag traps and a validhunter tool.

Two different updates resulted in the current soulstone effects as mentioned in #48018 
I know the devil soul changes stopped simplemob corpses from being used, but another update stopped bodies that had been cloned from being used.
