### ISSUE TITLE
Codewords are no longer highlighted in chat

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#48042]
As per #44130, traitors _should_ be seeing codewords highlighted in chat. However, this isn't the case anymore. There was never any PR that removed it as far as I can tell, so it's a bug.

**Comment by kriskog** [comment]
Works on my local

**Comment by rdragan** [comment]
I can confirm, haven't seen codewords highlighted in a few days now.

**Comment by Tharcoonvagh** [comment]
Did you have your uplink on your person? If not I think it is not even supposed to highlight em

**Comment by AnturK** [comment]
From quick glance it only applies to first traitor body, so that might be your issue.

**Comment by Akrilla** [comment]
who broke me first pr

**Comment by actioninja** [comment]
I recently noticed this, first traitor body is likely the issue I noticed though.

**Comment by rdragan** [comment]
Just checked this pretty soon after round start, in my first body, and it didn't work.
Round ID: 124823
ckey: thebleh

**Comment by nemvar** [comment]
This happens even in your first body. Did pretty extensive testing for my standards.

This is the slightly modified code I was using for tests.
```
/datum/antagonist/traitor/proc/handle_hearing(datum/source, list/hearing_args)
	var/message = hearing_args[HEARING_MESSAGE]
	world.log << message
	message = GLOB.syndicate_code_phrase_regex.Replace(message, "<span class='blue'>$1</span>")
	message = GLOB.syndicate_code_response_regex.Replace(message, "<span class='red'>$1</span>")
	hearing_args[HEARING_MESSAGE] = message
	world.log << message
```
This is what I got in world.log
![returns](https://user-images.githubusercontent.com/47324920/69908777-4ccfff80-13f0-11ea-9368-e4b49b40c577.PNG)

This is what I've seen in chat
![returns1](https://user-images.githubusercontent.com/47324920/69908778-53f70d80-13f0-11ea-90fb-827593c216e5.PNG)

This VV call in the second imagine is done on one of the regex datums responsible for the highlighting. As you can see in the return, it did work there.

**Comment by AnturK** [comment]
Turn off global flag on the regex

**Comment by AnturK** [comment]
You want to change raw message instead of message there. Kinda ugly how it's used there.

**Comment by Akrilla** [comment]
yeah current implementation will actually highlight peoples' names if the codeword happens to have it as a word

**Comment by TheSilverNuke** [comment]
Still broken as of a month later
