### ISSUE TITLE
sentient gorillas are still polite

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#48045]
You can't break down windows, airlocks, tables, etc. with your bare hands, which is really disappointing. In fact, when you click on a window on harm intent, you just knock on it politely!

Also, some other stuff was mentioned in this other bug report, but I haven't check whether or not it's been fixed yet: https://github.com/tgstation/tgstation/issues/45727

The lazy solution to this problem would be to add a "monkey rage toggle" button or something for gorillas that'd let you either ignore or not ignore the fact that you have hands that can hold stuff when pressed. In other words, you could toggle being treated like any other simplemob and being treated like a simplemob with hands. That'd be really clunky, though.

**Comment by AnonymousNow** [comment]
Hi, I was the gorilla that brought this to light last night.
I could somehow punch myself on help intent, but no amount of picking up or dropping objects, toggling intents etc. could let me fuckin' hiT SOMETHINGARARRNARRRAR

**Comment by nemvar** [comment]
Not a bug. Gorillas are just really underimplemented. Should be changed though once someone has the mercy to fix these beautiful beasts. Since you already shouted this out in the gorilla thread I don't see a point in having this open.
