### ISSUE TITLE
Glitch when playing as holoparasite protector

### ISSUE THREAD

**Issue by TheInsanityDiver** [tgstation/tgstation#48055]
at the start of the round i went to observe to ghost around got notification for wizard parasite took it screen became a light map of sorts only showing me the active lights and nothing else was a protector at the time

![Screenshot (209)](https://user-images.githubusercontent.com/44751108/69895168-e065db00-12df-11ea-83e3-feb6b4ad9ccb.png)

**Comment by nemvar** [comment]
I have seen this bug before. Can't find an open issue with it though.

**Comment by PepperPrepper** [comment]
This looks similar to #46456

**Comment by TheBonded** [comment]
I have only ever seen this happen when the server crashes. marking as cleanup flagged unless someone confirms this still happens

**Comment by SuperNovaa41** [comment]
i trust you
