### ISSUE TITLE
Devilman upgrade from lizard man to civet

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#48054]
Round number 124776

#47817: '[ready] Smooth-ish move rising: revengeance' by actioninja at commit aef88bf7d9
#48010: 'tgui-next: useBackend edition' by stylemistake at commit 047c4fcc5a

Pretty much I tc traded to become a devilman and then after getting enough souls I became civet. However the problem is that my mind wasn't in the civet so my body was suffocating and I couldn't move because I was *buckled* to the civet. Eventually I was saved by a admin by ghosting and he had me control the civet.

**Comment by nemvar** [comment]
wtf is a civet? This isn't a furry server. Speak real words player!

**Comment by dragomagol** [comment]
Rip devil

**Comment by davethwave** [comment]
Rip indeed. Miss this role that will likely never make a return.
