### ISSUE TITLE
You can kill yourself as Revenant by using an ability w/o enough essense

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#48052]
If you use an ability via the Revenant tab and it just so happens you don’t have enough essence, the ability will go through and you’ll die.

**Comment by Neo-0** [comment]
not a bug
> Your maximum health is your Essence, and it will regenerate up to 75 by default. If your Essence hits zero, you die, leaving a pile of blue dust that you will revive from within a minute if not scattered.

**Comment by HomocidlePancakes** [comment]
You sure you are able to do so when using the action buttons?

**Comment by Neo-0** [comment]
What do you mean?
Using revenant abilities without enough essence will make him die

**Comment by nemvar** [comment]
Gonna keep this open for now. I think there are some abilities that can't be cast due to lack of essence.
Might be wrong on that though.

**Comment by ATH1909** [comment]
```
/obj/effect/proc_holder/spell/aoe_turf/revenant/can_cast(mob/living/simple_animal/revenant/user = usr)
	if(charge_counter < charge_max)
		return FALSE
	if(!istype(user)) //Badmins, no. Badmins, don't do it.
		return TRUE
	if(user.inhibited)
		return FALSE
	if(locked)
		if(user.essence_excess <= unlock_amount)
			return FALSE
	if(user.essence <= cast_amount)
		return FALSE
	return TRUE
```
This definitely isn't intentional, but I don't know what's causing this issue.
