### ISSUE TITLE
mediborgs use tend wounds on augmented limbs but don't heal them

### ISSUE THREAD

**Issue by CPTANT** [tgstation/tgstation#48064]
See title. The keep trying but don't do anything. They should either not attempt to heal augmented limbs or the surgery should heal them.

**Comment by cacogen** [comment]
## Round ID:
Round ID: 132239
BYOND Version: 513.1508

Server revision compiled on: 
Master commit: 6a599a213b447d2b063d9b7e3e4f98955e2a30b1
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm



Local commit: 14e141a5991084ebd09afca63e5cf9ac4bdab13e
Server tools version: /tg/station 13 Server v3.2.6.2


## Testmerges:

The following pull requests are currently test merged:
#49344: '[READY] Space Dragon Rework' by IndieanaJones at commit 8416daa7c4



## Reproduction:

1. Have damaged robotic limb
2. Attract attention of medibot
3. Be tended to for eternity

**Comment by timothymtorres** [comment]
This was fixed in #51998.  Medibots now check with `get_organic_health()` to ignore robotic limb damage.

https://github.com/tgstation/tgstation/blob/35485747e73f4991dbbb554abdd842680f5f2566/code/modules/mob/living/simple_animal/bot/medbot.dm#L545-L547
