### ISSUE TITLE
Light eater no longer fries borgs' lights

### ISSUE THREAD

**Issue by Eskjjlj** [tgstation/tgstation#48078]
## Round ID: 
124869

## Testmerges: 
None

## Reproduction:
Be a nightmare, hit a cyborg with your light eater and die because the borg's flashlight didn't fry. It used to work so why does it no longer work? 
In this case it happened with an AI shell.

**Comment by Eskjjlj** [comment]
I tested it on local and the borg's light got desactivated by the lighteater but it didn't happen on the live server and multiple players have witnessed the same bug happening so this may not be a simple to fix.

**Comment by Timonkeyn** [comment]
I noticed this one too some time ago, is this a problem with active ai shells?

**Comment by carshalash** [comment]
Noticed it happen yeaterday with a regular borg as well.

**Comment by PepperPrepper** [comment]
I tested this locally and was able to fry headlamps just fine. This could just be a feedback issue as there is currently no text indicating that you have broken the light.

**Comment by Eskjjlj** [comment]
Not a feedback issue since the borg still produces light. Sometimes it works sometimes it doesn't @PepperPrepper
