### ISSUE TITLE
Binding keys to `Ctrl + [Key]` does not work

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#48070]
## Reproduction:

Bind a key to `Ctrl + [Key]` where [Key] can be anything(? Only tested with they 1, 2, 3, 4 and E keys)
Push that key combination (IE, Ctrl + E)
Expected outcome: The action you bound that key combination to happens
Real outcome: Nothing happens, key press not recognized

**Comment by Couls** [comment]
potentially related to #47869
