### ISSUE TITLE
Anatomic Panacea not effecting Gondola virus

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#48071]
Steps to reproduce!
1: Be a Changeling
2: Have a guy poke you with funny food
3: Use Anatomic Panacea and scan yourself, see the disease is gone and kick back
4: Turn into a gondola anyway
5: Scream

**Comment by nemvar** [comment]
Can not reproduce.

**Comment by nemvar** [comment]
Alright no answer. No other people responded. Closing now.
