### ISSUE TITLE
Drop platform bugs

### ISSUE THREAD

**Issue by jbox144** [tgstation/tgstation#48080]
**Bug**: The drop platform is considered a ship even after it lands, despite there being no way to launch it
**Bug**: Ships can dock at the location where the drop platform normally resides if the platform is deployed, despite said location being inside the station.

**Comment by kriskog** [comment]
> Bug: Ships can dock at the location where the drop platform normally resides if the platform is deployed, despite said location being inside the station.

This is intentional

**Comment by Dorsisdwarf** [comment]
these arent really bugs, more weirdnesses that might cause a bug in the future

**Comment by kriskog** [comment]
On second thought
