### ISSUE TITLE
Nightmares are flashproof

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#48092]
Steps to replicate:
1: Flash a nightmare

**Comment by PepperPrepper** [comment]
Seems intended:

`inherent_traits = list(TRAIT_RADIMMUNE,TRAIT_VIRUSIMMUNE,TRAIT_NOBREATH, TRAIT_NOFLASH)`

**Comment by carshalash** [comment]
This, wasnt always a thing. Which melvin gave them noflash?

**Comment by PepperPrepper** [comment]
Yeah this is most likely intended as shadow-people/nightmares don't have eyes.

**Comment by carshalash** [comment]
You... literally extract their eyes for FREE night vision.

**Comment by PepperPrepper** [comment]
Yeah disregard my above post. My brains being slow today.

I'll do a smooth webedit fix. (It'll most likely be canned because antag freeze but eh)

**Comment by HomocidlePancakes** [comment]
This was a thing for half an year now. Real bruh times

**Comment by nemvar** [comment]
I thought this was intended
