### ISSUE TITLE
Lightgeist delete runtime

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#48105]
Spawn a lightgeist. Take control of it. Right click, delete it.

[19:48:08] Runtime in garbage.dm, line 322: /mob/living/simple_animal/hostile/lightgeist destroy proc was called multiple times, likely due to a qdel loop in the Destroy logic
proc name: qdel (/proc/qdel)
usr: skoglol/(Bura-Jasuda)
usr.loc: (Central Primary Hallway (88, 140, 2))
src: null
call stack:
qdel(the lightgeist (/mob/living/simple_animal/hostile/lightgeist), 0)
the lightgeist (/mob/living/simple_animal/hostile/lightgeist): death(null)
the lightgeist (/mob/living/simple_animal/hostile/lightgeist): death(null)
the lightgeist (/mob/living/simple_animal/hostile/lightgeist): ghostize()
the lightgeist (/mob/living/simple_animal/hostile/lightgeist): Destroy(0)
the lightgeist (/mob/living/simple_animal/hostile/lightgeist): Destroy(0)
the lightgeist (/mob/living/simple_animal/hostile/lightgeist): Destroy(0)
the lightgeist (/mob/living/simple_animal/hostile/lightgeist): Destroy(0)
qdel(the lightgeist (/mob/living/simple_animal/hostile/lightgeist), 0)
Skoglol (/client): admin delete(the lightgeist (/mob/living/simple_animal/hostile/lightgeist))
Skoglol (/client): Delete(the lightgeist (/mob/living/simple_animal/hostile/lightgeist))

**Comment by nemvar** [comment]
Not possible to fix without major refactor. Probably should just be silenced.
