### ISSUE TITLE
The "Signal Repeater" nanite program bugs out when you try to put two in the same cloud.

### ISSUE THREAD

**Issue by TheSmallBlue** [tgstation/tgstation#48109]
Before the neat nanite UI rework, you used to be able to put two different signal repeater programs in the same cloud, but now putting a program into the nanite cloud controller without even uploading it to the cloud influences the already uploaded program, which shouldn't happen. 
Here's a handy gif
![9jSUswpK6R](https://user-images.githubusercontent.com/24967815/70014093-7f950780-1558-11ea-8f6d-42b3684d9a03.gif)
Here are the steps that I do in the gif:

1. I modify a just-uploaded signal repeater programme to trigger with the code "123", to have a delay of 0 seconds and to send the code "321"
2. I upload this program to the only backup cloud in the nanite cloud controller, backup #1 
3. I grab the same disk and re-program it so that the trigger code is "123" and the sent code is "321", I also add a delay of 40 seconds.
4. I put this program inside the nanite cloud controller, without uploading

5. _What should happen:_ The already uploaded Signal Repeater doesn't change, and I am able to have two totally different programs in the same cloud
_What actually happens:_ The already uploaded Signal Repeater program automatically changes, without me uploading the program to the cloud, making the delay (which was previously 0) 40 seconds -the delay of the other not-uploaded program-, and changing the sent code (which was 123) to 321 -the sent code of the other not-uploaded program-.

Hope this can be resolved soon, if you need any more info from me I'll be around

**Comment by actioninja** [comment]
Really good report.
I'll look into this, this is definitely a weird one. Probably something to do with backend structuring.
