### ISSUE TITLE
Cyborg Sheet Snatcher Can't Pick Up Ratvarian Bronze (From Ruin)

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#48113]
As said on tin. 30 sheets of it spawn on the ruins of Ratvar on Lavaland, but can't be picked up by the Sheet Snatcher. Likely a side effect of excising Ratvarian cultists from the code, creates an odd inconsistency.

**Comment by nemvar** [comment]
Not related to cock cult removal

**Comment by TheVekter** [comment]
lol cock cult

Yeah no, this is probably an oversight from it not being added to the whitelist on the sheet snatcher. I'll look into it later tonight.

**Comment by TheVekter** [comment]
@AnonymousNow This item, right?
![image](https://user-images.githubusercontent.com/7019927/70303639-b6bc2080-17c5-11ea-84f0-a5610a79732b.png)

**Comment by AnonymousNow** [comment]
That's the one. Unless the remnant metal sheets from the ruin are different to the regular sheets somehow. Ta much.
