### ISSUE TITLE
Magboots slow you down while active even there is no gravity

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#48114]
## Reproduction:
1. Get magboots
2. Bomb gravgen
3. Activate magboots
4. You slow as hell
4.1 You expected to be same speed when you wear just shoes with gravity

Probably related pr https://github.com/tgstation/tgstation/pull/47782

> This means your inconvenient suit will slow you down in 0 gravity as long as you're using magboots

But you just using magboots without suit and you still slow

**Comment by nemvar** [comment]
Shoutout to magboots preventing pixel movement.

**Comment by Michael-Ashfield** [comment]
I thought this was a feature? Magboots allow you to resist space wind and let you walk freely during no gravity, but at a speed cost. I've never seen it as a bug, if you want full move speed while nograv then be a moth.

**Comment by kopoba** [comment]
> 
> 
> I thought this was a feature? Magboots allow you to resist space wind and let you walk freely during no gravity, but at a speed cost. I've never seen it as a bug, if you want full move speed while nograv then be a moth.



then sindicat magboots now also so useless =(
Probably CE magboots that was not affected by gravity during ON state now also affected.

**Comment by Firecage** [comment]
Makes sense though, since a magboots slowdown shouldn't really be different whether there is gravity or not.

**Comment by Dorsisdwarf** [comment]
Could have sworn this was an intentional change after a series of murder sprees where traitors would beeline all the magboots at roundstart, blow up the grav gen and then mass murder people who couldnt run away as fast as they could chase

**Comment by TheVekter** [comment]
Yeah, this sounds very much intentional. The benefit is that you don't have to throw things to get around, not that you move at normal speed.

**Comment by kopoba** [comment]
No way its intentional. Magboots is so slow now that there is no chance you will use them cause they sucks. Like yo fly without gravity faster then you walk with magboots i think.

**Comment by Pugie** [comment]
It isn't intentional. This is possibly related to a lot of other slowdown issues that appeared around the same time such as with bolas

**Comment by Michael-Ashfield** [comment]
Even if it is unintentional, could it be left in and just called a feature? It sort of balances itself, as long as syndie and CE magboots are normal speed, the normal ones would come with a slowdown tax.
There is no reason why people wouldn't rob all the magboots round start if they didn't have slowdown. Being able to dance around in the center of large rooms and not have to throw every two seconds is a pretty big advantage in nograv situations.

**Comment by Pugie** [comment]
> Even if it is unintentional, could it be left in and just called a feature? It sort of balances itself, as long as syndie and CE magboots are normal speed, the normal ones would come with a slowdown tax.
> There is no reason why people wouldn't rob all the magboots round start if they didn't have slowdown. Being able to dance around in the center of large rooms and not have to throw every two seconds is a pretty big advantage in nograv situations.

It's almost like disabling gravity and having anti-gravity gear is a large strategic advantage

**Comment by ATH1909** [comment]
> Even if it is unintentional, could it be left in and just called a feature? It sort of balances itself, as long as syndie and CE magboots are normal speed, the normal ones would come with a slowdown tax.
> There is no reason why people wouldn't rob all the magboots round start if they didn't have slowdown. Being able to dance around in the center of large rooms and not have to throw every two seconds is a pretty big advantage in nograv situations.

Make the non-syndicate/CE ones slow you SLIGHTLY, but not to the degree that they do now.

**Comment by necromanceranne** [comment]
Fix the bug then make balance changes.

**Comment by WarlockD** [comment]
I think there are more wrong than that.  I have found that disabling the boots keep me slow BUT if I remove the boots and put them back on the speed is fixed.

**Comment by CPTANT** [comment]
I don't care if it is intentional or not, the item has been nerfed into uselessness. You are now simply better off without them at all.

**Comment by Jalleo** [comment]
Wow that PR said that it got changed to this for balance abd you pretend its a bug?

**Comment by bobbahbrown** [comment]
https://github.com/tgstation/tgstation/pull/47782

This is a design decision, not a bug. Magboots slow you down, PR a change if you feel they should be rebalanced.

**Comment by ninjanomnom** [comment]
This was intentional, part of the slowdown is due to hardsuits contributing to slowdown while your magboots are on. Wearing a lighter suit should help or just turn them off to move faster and only have them on when you need to be safe.
