### ISSUE TITLE
You can't draw cult runes in library

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#48118]
#### Round ID:
124992 Sybil and confirmed locally. 

#### Reproduction:
* Be cultist. 
* Go to library and activate dagger in hand. 

Result:
![191203 1758 50](https://user-images.githubusercontent.com/46400996/70072076-97bb6400-15f6-11ea-9e17-c7b481092d79.png)

You're probably supposed to be able to draw runes in the library.

**Comment by kriskog** [comment]
```
/area/library
	name = "Library"
	icon_state = "library"
	flags_1 = NONE
```

Someone removed all the area flags from library, presumably to get rid of the CAN_BE_DIRTY_1 flag.

**Comment by TheVekter** [comment]
I'll fix this when I get a moment tonight.

**Comment by Pugie** [comment]
Isn't this a problem with a lot of other places too like atmospherics and virology, or were they fixed?

**Comment by Angustmeta** [comment]
Imma check. 

Also this isn't my first issue.

**Comment by tmtmtl30** [comment]
chapel makes sense, virology is out in space on meta, solars is out in space on all maps, but i don't know what's up with the others

**Comment by kriskog** [comment]
>
> 
> Also this isn't my first issue.

The good first issue label is used to mark less complex issues for new coders to try their hand at. 🙂 
But your issue was good too, have a gold star ⭐️
