### ISSUE TITLE
Greytide virus opens external airlock

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#48128]
## Reproduction:
When the Greytide virus event is triggered all doors in the station open apart from external airlocks as intended. EXCEPT in the perma brig where the outter airlock is open and bolted. This can cause the brig to depressurise. (see picture) https://i.imgur.com/BAI9KVU.png

Map was Metastation
Event was triggered by admin button.

**Comment by 81Denton** [comment]
External airlocks don't have `critical_machine` set to TRUE, so my best bet is that this is intentional. At least, there aren't any code comments that elaborate on it.

**Comment by ATH1909** [comment]
> External airlocks don't have `critical_machine` set to TRUE, so my best bet is that this is intentional. At least, there aren't any code comments that elaborate on it.

Then why don't the other external doors open?

**Comment by TheVekter** [comment]
Yeah, no, this doesn't sound intentional, especially since the implication is supposed to be that the virus is designed to break people out of perma.

I'll see if I can fix this later.

**Comment by HomocidlePancakes** [comment]
Greytide always opened external airlocks. Cargo always gets vented during greytide virus

**Comment by 81Denton** [comment]
https://github.com/tgstation/tgstation/blob/c30dcf7d613b093c9aadfd1001fdb404351f42bb/code/modules/events/prison_break.dm#L51-L55
@ATH1909 Other areas are surrounded by maintenance or hallway areas, which aren't affected by the event itself. The event only messes with machinery in the following areas and sub areas:
https://github.com/tgstation/tgstation/blob/c30dcf7d613b093c9aadfd1001fdb404351f42bb/code/modules/events/prison_break.dm#L11-L16

**Comment by 81Denton** [comment]
>especially since the implication is supposed to be that the virus is designed to break people out of perma.

Honestly I think the event would be better if it either affects all airlocks, or doesn't affect external airlock types at all.

**Comment by TheVekter** [comment]
> Honestly I think the event would be better if it either affects all airlocks, or doesn't affect external airlock types at all.

I prefer the latter. Only affecting internal airlocks that aren't tied to critical systems.

**Comment by Ratvar** [comment]
Why does this still have "not a bug" tag

**Comment by 81Denton** [comment]
Because it's not a bug
