### ISSUE TITLE
Admin spawned immovable rods fail to spawn

### ISSUE THREAD

**Issue by Moonman121** [tgstation/tgstation#48127]
I have noticed this happening for about 3-4 months now. Quite often when you force a rod the event pops up but a rod is never spawned, it can sometimes take two or three events before it actually sends anything.

**Comment by HomocidlePancakes** [comment]
Rod rolls shit trajectory and ends up leaving the station and despawning. I think. Maybe.

**Comment by Moonman121** [comment]
It doesn't spawn even if you aim it at the centre of the station.

**Comment by kriskog** [comment]
It might be a diagonal rod, they usually get knocked off course. Worth checking if there are no other obvious reasons.

**Comment by kriskog** [comment]
> 
> 
> It might be a diagonal rod, they usually get knocked off course. 

This isnt the thing, turns out the diagonal rods stop going diagonal when they hit the aimed x/y.
