### ISSUE TITLE
Heinous lag spikes every few minutes

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#48159]
Issue reported from  Round ID: 125292 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

Chem had a pretty serious factory going, so that might be causing it. Otherwise it was really, really bad. Locking up for a solid 30 seconds to a minute.

**Comment by kriskog** [comment]
Was this local or did the entire server experience them at the same time?

**Comment by TheVekter** [comment]
> Was this local or did the entire server experience them at the same time?

Server-wide. I wouldn't report it otherwise :p

**Comment by optimumtact** [comment]
there's absolutely no way this bug report will ever be followed up really
