### ISSUE TITLE
Non-event nightmares don't get jaunt.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#48168]
So this happened twice to me so far. One time when I TC traded to be a nightmare, and one time when getting transformed via magic mirror. Both times I did not have jaunt and had to ask admins for it.

**Comment by necromanceranne** [comment]
Not been able to replicate this myself. Not sure what resulted in this happening. Could you provide a round ID where this happened?

**Comment by HomocidlePancakes** [comment]
125352. Both times I was a ling when transformed. Maybe that's related? I also had cursed heart on my second time.

**Comment by necromanceranne** [comment]
I'll give it a try with ling tomorrow.
