### ISSUE TITLE
Reviving as a ling nightmare removed the light-eater.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#48169]
Probably because revive removes mutant organs and the blade is granted by the heart of darkness.

**Comment by spookydonut** [comment]
@HomocidlePancakes needs proper repo steps

**Comment by HomocidlePancakes** [comment]
>Be ling
>Be nightmare
>Revive
>Loose armblade

**Comment by dragomagol** [comment]
Appears to have been fixed
