### ISSUE TITLE
Detective gun preview sprites are broken

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#48162]
Issue reported from  Round ID: 125329 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488
only Fitz Special: 
Police Positive Special: 
work

this might've been already reported i'm in the middle of something

**Comment by kopoba** [comment]
Probably same issue its random and cant be reproduced i think
https://github.com/tgstation/tgstation/issues/43829

**Comment by cacogen** [comment]
what a pain, i get broken sprites on examine too
i have windows 10 and the latest version of byond

maybe it has something to do with ie
