### ISSUE TITLE
Monkey Cube Cloning

### ISSUE THREAD

**Issue by ShadowTheLion** [tgstation/tgstation#48160]
## Reproduction:If you use a dropper of water on a monkey cube you get both a monkey and another monkey cube that can be activated using a beaker of water making 2 monkeys.
![Monkey Cube Cloning The following image is from one box of monkey cubes ](https://user-images.githubusercontent.com/55414910/70380753-f857e300-190d-11ea-8be9-506e82342e63.PNG)

**Comment by Tharcoonvagh** [comment]
![monkie](https://user-images.githubusercontent.com/54288658/70381483-58b94580-194b-11ea-9228-79c489d98ef6.gif)
