### ISSUE TITLE
Apothecary - RC announcment access

### ISSUE THREAD

**Issue by Archemagus** [tgstation/tgstation#48166]
`code/__DEFINES/access.dm`
![image](https://user-images.githubusercontent.com/32466328/70387563-85a34200-19b7-11ea-9db7-21dab4e1c965.png)

Well... Does it mean, that chemists have RC access too?
And should then?

**Comment by kriskog** [comment]
Nice.
The ACCESS_APOTHECARY define should be moved to the bottom of the station access defines, which is 69 right now. Also needs to be replaced at all relevant doors on all maps.

**Comment by TheVekter** [comment]
Nice.

This is probably something I can do real quick tonight.
