### ISSUE TITLE
Affected by damage slowdown in space

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#48164]
Round: 125340
Got shot with penetrator rounds and was slowed by damage slowdown.

**Comment by HomocidlePancakes** [comment]
@spookydonut Take damage, or get cold, walk in to space and watch yourself still be slow. How does that "needs reproducing"?

**Comment by kriskog** [comment]
related to #48114

**Comment by Rohesie** [comment]
`/datum/movespeed_modifier/damage_slowdown_flying` exists and causes this

Should damage not affect movement without gravity?
The problem here is that we don't have a good momentum calculation, nor a clear differentiation between assisted and non-assisted movement, for movespeed modifiers.

**Comment by kriskog** [comment]
Intended behaviour then
