### ISSUE TITLE
Augmenting head/chest turns mob body parts invisible

### ISSUE THREAD

**Issue by Twaticus** [tgstation/tgstation#48178]
## Round ID:

125380

## Reproduction:

- Be ethereal (this could possibly be affecting any species, but it was only tested on an ethereal at the time)

- Get fully augmented

- Become floating arms and legs

  ![dreamseeker_mnbLmiZEtU](https://user-images.githubusercontent.com/46540570/70397854-bbf6b680-19e3-11ea-8090-4b7404c1669a.png)

**Comment by optimumtact** [comment]
@kriskog

**Comment by TheVekter** [comment]
Let me see if I can reproduce with other races.

**Comment by fludd12** [comment]
I did a full body augment over the weekend which didn't experience this bug, leading me to believe that unless something vital changed since then, this is only affecting ethereals.

**Comment by ATH1909** [comment]
This specifically happens with red ethereals, I believe.

There was a bug report that was made about it a while back; I had fun being an invisible quadriplegic for a round.

**Comment by kriskog** [comment]
At a cursory glance, unrelated to the limb updating PR since these are robotic parts and follow different logic to not update no matter what. Also reproduced on an ethereal.

**Comment by nemvar** [comment]
Dupe https://github.com/tgstation/tgstation/issues/43515
