### ISSUE TITLE
Nanite damage sensor programming interface

### ISSUE THREAD

**Issue by BartuMerkan** [tgstation/tgstation#48177]
Issue reported from  Round ID: 125379 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 512.1474

Nanite damage sensor has cannot be modified to change damage values as the UI is missing those elements

**Comment by optimumtact** [comment]
@actioninja

**Comment by actioninja** [comment]
Unsure what is causing this. Redownloading the same program seemed to fix it.

**Comment by actioninja** [comment]
found the issue.
