### ISSUE TITLE
Extended switchblade no longer fits in boots.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#48184]

**Comment by TheVekter** [comment]
You're gonna have to give more info than that, Cochise.

Which boots were you using? What message did you get? Do you mean you can't put it in while it's extended, which sounds like intended behavior?

**Comment by Tharcoonvagh** [comment]
I could do it loke a month or so ago, probably not intended

**Comment by HomocidlePancakes** [comment]
@TheVekter 
1)Any boots that allow to store items inside of them
2)”It’s too big” or something along those lines
3)It isn’t intended behavior, it used to fit in to the boots in both concealed and extended states.

**Comment by Daxxed** [comment]
This is an issue why ?

**Comment by bobbahbrown** [comment]
@HomocidlePancakes are concealed blades still able to be hidden in boots

**Comment by bobbahbrown** [comment]
so when you extend a switchblade it becomes normal weight class which means it doesn't fit in shoe storage component

not a bug

**Comment by PKPenguin321** [comment]
See above
