### ISSUE TITLE
Escape shuttle statistics include ghosts.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#48186]
This happens more-or-less every single round, because there's always at least a few ghosts on the shuttle, but here's a example of a round where Disco Inferno caught fire after a murderbone and every single person on the shuttle died.

![image](https://user-images.githubusercontent.com/16315400/70467883-06377080-1a94-11ea-9e7f-77fadd80d18b.png)

There weren't even 23 corpses.

**Comment by bobbahbrown** [comment]
good catch

**Comment by bobbahbrown** [comment]
so it kind of depends on what we want to see here, right now its just counting all the mobs on the emergency shuttle or elsewhere hence catching ghosts -- do we want to see dead mobs + living mobs, only living mobs, etc?

**Comment by cacogen** [comment]
only living...

**Comment by ATH1909** [comment]
Maybe even take it a step further and only have it count SAPIENT living mobs?
