### ISSUE TITLE
Timer subsystem has unreachable code due to CRASH calls

### ISSUE THREAD

**Issue by spookydonut** [tgstation/tgstation#48183]
https://github.com/tgstation/tgstation/blob/4d013693f06fabbd19a379fb65f1d4ae31a1a275/code/controllers/subsystem/timer.dm#L162

https://github.com/tgstation/tgstation/blob/4d013693f06fabbd19a379fb65f1d4ae31a1a275/code/controllers/subsystem/timer.dm#L174

```dm
			if (timer.timeToRun < head_offset)
				bucket_resolution = null //force bucket recreation
				CRASH("[i] Invalid timer state: Timer in long run queue with a time to run less then head_offset. [get_timer_debug_string(timer)] world.time: [world.time], head_offset: [head_offset], practical_offset: [practical_offset]")

				if (timer.callBack && !timer.spent)
					timer.callBack.InvokeAsync()
					spent += timer
					bucket_count++
				else if(!QDELETED(timer))
					qdel(timer)
				continue

			if (timer.timeToRun < head_offset + TICKS2DS(practical_offset-1))
				bucket_resolution = null //force bucket recreation
				CRASH("[i] Invalid timer state: Timer in long run queue that would require a backtrack to transfer to short run queue. [get_timer_debug_string(timer)] world.time: [world.time], head_offset: [head_offset], practical_offset: [practical_offset]")
				if (timer.callBack && !timer.spent)
					timer.callBack.InvokeAsync()
					spent += timer
					bucket_count++
				else if(!QDELETED(timer))
					qdel(timer)
				continue
```

**Comment by spookydonut** [comment]
Can someone check the logs for the last 2 years for this crash message

**Comment by spookydonut** [comment]
https://scrubby.melonmesa.com/round/113394/runtimes
https://scrubby.melonmesa.com/round/99668/runtimes
thanks @bobbahbrown for looking these up

**Comment by TheVekter** [comment]
So for someone who doesn't really understand the controller code, what's causing the unreachable code and what negative effect does this have on things? Purely asking for education's sake.

**Comment by CitrusGender** [comment]
@TheVekter A crash will end the proc. If there is any code after a crash, it is made in error since it would never be run. As it seems, the crash looks like it would leave some timers existing that should have been deleted with the qdel underneath them. It's overall just waste that is clogging up the code. 

I'm not too sure what causes the Crash but this is just a cursory perspective.

**Comment by bobbahbrown** [comment]
rare citrusgender comment

**Comment by TheVekter** [comment]
> @TheVekter A crash will end the proc. If there is any code after a crash, it is made in error since it would never be run. As it seems, the crash looks like it would leave some timers existing that should have been deleted with the qdel underneath them. It's overall just waste that is clogging up the code.
> 
> I'm not too sure what causes the Crash but this is just a cursory perspective.

So it's a garbage collector issue, basically. Okay. Thanks for the insight!
