### ISSUE TITLE
Crafting menu is unusable

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#48198]
Issue reported from  Round ID: 125496 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1488

Round ID: 125496
BYOND Version: 512.1484
Server revision compiled on: 
Master commit: 85228e0a6fd363a7c5f32b109fbe09c902c4a16c
Server tools version: /tg/station 13 Server v3.2.6.2

---

Opening the crafting menu ingame always results in an error screen.
Pinging @actioninja @stylemistake 

```
SyntaxError: Syntax error
   at Anonymous function (http://127.0.0.1:52459/tmp7668/tgui.bundle.js:1:81958)
   at window.initialize (http://127.0.0.1:52459/tmp7668/tgui.bundle.js:1:81804)
   at eval code (eval code:1:1)
```
---

![image](https://user-images.githubusercontent.com/32391752/70539462-0f900e00-1b64-11ea-901d-617e97048cad.png)

**Comment by Ty-the-Smonk** [comment]
Was everyone getting this error?

**Comment by ATH1909** [comment]
My medHUDglasses! NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO!

**Comment by stylemistake** [comment]
Strange, to say the least.

**Comment by stylemistake** [comment]
Problem at hand:

![image](https://user-images.githubusercontent.com/1516236/70583393-4565de80-1bc6-11ea-908c-9ba6fc0edff9.png)

I don't have much time to fix this, but it should be something as simple as adding a missing subcategory field.

Crafting backend code is pretty bad and someone has to eventually rework it.
