### ISSUE TITLE
Nar'sian bola both legcuffs and goes in hand when picked up by non-cultist

### ISSUE THREAD

**Issue by Yenwodyah** [tgstation/tgstation#48190]
The nar'sian bola is supposed to legcuff a non-cultist if they pick it up, but it goes in their hand too. if they drop it, they get un-legcuffed but the legcuff slowdown doesn't go away until their slowdown from inventory stuff is updated.

## Reproduction:

1. be non cultist
2. pick up cult bola
3. drop cult bola

**Comment by TheVekter** [comment]
For clarification, #48189 doesn't fix this?

**Comment by Yenwodyah** [comment]
Nope
I actually discovered that this was bugged while I was testing that pr

**Comment by ATH1909** [comment]
Can you then throw the nar'sian bola that you picked up?

**Comment by Yenwodyah** [comment]
Yeah. Throwing it does the same thing as dropping it.
