### ISSUE TITLE
Detective's Revolver Reskinning Previews Broken

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#48214]
![asdasd](https://user-images.githubusercontent.com/6266927/70617995-aebb1100-1c09-11ea-9add-36a39bd571ea.png)

Looks like the previews in-chat are broken. Reproduced several times in the next round (Thunderdome testing). 

Not sure if it's just me, but the default and Fitz Special look identical when they're actually made. Might be unrelated, or maybe intended with some small difference I'm missing.

**Comment by Jordie0608** [comment]
Related
#48162
#43829

**Comment by AnonymousNow** [comment]
Less related, more a straight-up dupe. But I won't close this, since the issue seems to be ongoing. I repeated it myself, and got the same result, but it seems that mileage varies. I'll ask others.

**Comment by Mooshimi** [comment]
Cleanup tagging this since the det reskins aren't shown in chat anymore
