### ISSUE TITLE
Suiciding as a silicon (via the verb) ghosts you and makes you unable to return to your body

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#48226]
## Round ID:
125648

## Testmerges:
None

## Reproduction:
Be a cyborg
Get a suicide law
Do so
Get repaired
Can't re-enter your body

**Comment by kriskog** [comment]
Suicide via the verb is permanent, this is intentional.
If you get a suicide law, look into other means of suicide if you would like to get back in. This borders more on a policy issue, but ic laws should not be able to force you to use the ooc verb to suicide.

**Comment by Anonmare** [comment]
That's honestly really fucking stupid and seems like a deliberate attempt to fuck over players both new and from other codebases where the suicide verb doesn't do that.

**Comment by kriskog** [comment]
Suicide is an ooc action that signifies "I dont want to be in this round anymore". Ghosting and DNR does the same thing. No take backs, this later change has merely gotten rid of an inconsistency that shouldnt have been there in the first place.
