### ISSUE TITLE
Unable to use medipens/legion cores while crawling.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#48230]
Reproduction:
1)Lay down
2)Use the medipen/core **in-hand**
3)”You can’t do that right now”.

**Comment by Tharcoonvagh** [comment]
You can't use a lot of things while prone either
Some examples:
Pda
Pen&paper
Tablet
Chairs (in hand) 
And a lot more
Also I don't think it's a bug

**Comment by nemvar** [comment]
Fixing this particular case would lead to more consistency issues. On the other hand you can do complex tasks like reloading a gun while crawling so it's already inconsistent.
Will leave open for now, maybe someone cares enough.

**Comment by HomocidlePancakes** [comment]
@nemvar No, you understood me wrong. What makes this one special out of all the cases is that you can still use them by clicking yourself.

**Comment by ArcaneMusic** [comment]
KylerAce has informed me this has been fixed, so I'm closing this.
