### ISSUE TITLE
Scuffed missing limbs.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#48233]
![Снимок](https://user-images.githubusercontent.com/35217076/70797442-97b92200-1db5-11ea-9fc8-99757174c8d8.PNG)
![Снимок1](https://user-images.githubusercontent.com/35217076/70797445-9a1b7c00-1db5-11ea-87c0-615559a76d0f.PNG)

I don't have arms on both pics. The fuck is this?

**Comment by Time-Green** [comment]
Ask a doctor for prosthetic replacement surgery

**Comment by HomocidlePancakes** [comment]
Yeah, I was talking about the weird red spots.

**Comment by PKPenguin321** [comment]
Fairly sure that this is an ancient dupe

**Comment by kriskog** [comment]
dupe of #32661
