### ISSUE TITLE
Revenants make noise while ghost walking over glass shards and old gibs / blood puddles

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#48249]
## Round ID:
125805

## Reproduction: 
Walk over glass shards / old blood puddles as human-ghost-stuffed-into-revenant by-drag-click and notice they play a sound. I don't know whether other people could hear them.

**Comment by nemvar** [comment]
Just change movetype to flying. Should fix it.

**Comment by Timonkeyn** [comment]
@nemvar its already flying
