### ISSUE TITLE
Cultists were unable to communicate with other cultists.

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#48240]
Issue reported from  Round ID: 125732 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

One cultist ahelped about not having the communicate spell to communicate with all the other cultists, then while helping him I noticed that none of the other cultists were communicating either. Had to manually remove and readd cult status to all of them to fix it. Not sure why it did this and it did not affect any converted cultists after this. It also did not give them any of the cult objectives.

**Comment by TheMidnightRose** [comment]
Did it again in a different cult round. This is what it looks like 
![image](https://user-images.githubusercontent.com/32805898/70850573-7443b500-1e51-11ea-816a-1962af4e5508.png)

**Comment by JohnFulpWillard** [comment]
Fixed
