### ISSUE TITLE
Power fist doesn't activate reactive teleport armor

### ISSUE THREAD

**Issue by EvilMelonTheSecond** [tgstation/tgstation#48248]
Issue reported from  Round ID: 125806 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 512.1474

Been the second time I got killed by a power fist when I had my teleport armor on as RD. Not sure if this was intended

**Comment by ATH1909** [comment]
Reactive teleport armor doesn't ALWAYS activate when you're hit, IIRC.

**Comment by ATH1909** [comment]
Yeah, the teleport only has a 50% chance to proc against a chest hit (and a 0% chance to proc against non-chest hits), assuming that it's not on cooldown.

**Comment by TheBonded** [comment]
yeah, teleport does not have a 100% chance to activate. you just got unlucky
