### ISSUE TITLE
Magic mirrors let you choose blank names

### ISSUE THREAD

**Issue by Twaticus** [tgstation/tgstation#48245]
## Round ID:

125774

## Reproduction:

- use magic mirror

- change your name

- use only spaces

![dreamseeker_tWfwZ1PxDF](https://user-images.githubusercontent.com/46540570/70848272-ed84dd00-1e3c-11ea-9460-80ba6cae4681.png)!

**Comment by kriskog** [comment]
duh its a space wizard

**Comment by Tharcoonvagh** [comment]
it's cuz cats r gae baes
