### ISSUE TITLE
attempting to clone a monkey breaks the cloner

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#48247]
round 125800, sybil.

in runtimes you'll see a cloning runtime. had to deconstruct the clone pod to pop the monkey out, after reconstructing the pod it worked fine. dunno how the monkey originally got cloned.

**Comment by nemvar** [comment]
hilarious bug

**Comment by kriskog** [comment]
Duplicate of #40230, but more recent with cloning changes since so closing that one.
