### ISSUE TITLE
AIs can listen to and speak over CTF radio during rounds

### ISSUE THREAD

**Issue by spessbandit** [tgstation/tgstation#48250]
Round ID: 125815, Sibyl

(F) [Security] G.O.D states, "I will now be killing myself"
(F) G.O.D states, "I will now be killing myself"
(F) [Blue Team] G.O.D states, "I will now be killing myself"
(F) [Blue Team] G.O.D states, "I will now be killing myself"
(F) [Red Team] G.O.D states, "I will now be killing myself"
(F) [Red Team] G.O.D states, "I will now be killing myself"

**Comment by ATH1909** [comment]
What're the hotkeys for those channels?

**Comment by LemonInTheDark** [comment]
Feature

**Comment by LemonInTheDark** [comment]
Also I assume it's because of the ai intercom and the disparage in the channel lists of a few different files

**Comment by jdawg1290** [comment]
The ai is king in cyberspace so I don’t see this as a problem, just an amusing oversight.

**Comment by nemvar** [comment]
I would consider this a bug. CTF are OOC channels and IC actors should not have access. Makes me wonder if syndi encryption also has access.

**Comment by timothymtorres** [comment]
Duplicate of #48267
