### ISSUE TITLE
Parts of the ratvar lavaland ruin were on fire near roundstart

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#48261]
<img width="879" alt="ratvar's on fire" src="https://user-images.githubusercontent.com/42606352/70861800-bd027900-1ef8-11ea-8c07-a6baffdb3056.PNG">

**Comment by Daxxed** [comment]
Lava lake going through it, and the stuff burning is the "loot"
I remember when that spear was actually good

Most ruins have a nice little border 1 tile wide on which lava lake cannot generate, or it is made into rock afterwards I honestly don't know
This ruin had this issue for ages, and I think if the rng is right it's possible to have a hierophant arena you cannot access without crossing lava too.

**Comment by nemvar** [comment]
I think this look cool...

**Comment by CAPTTLasky** [comment]
I could set the no lava area to anything with good loot and make sure that the pathing allows for you to get that loot but I agree this looks cool
