### ISSUE TITLE
Space after emoticons in chat

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#48266]
No round ID
there is a space in chat after you write an emoji and something else, I noticed it with another emoticon
To reproduce: ooc: :emoji:test:emoji:
Can't provide any pics right now
Also i can log dive if ya really need that id

**Comment by kriskog** [comment]
Works fine on my machine. Its probably something goonchat related, I also have the extra spaces from comms. If you could get a screenie and include byond version and OS you are running that would be great.

**Comment by Tharcoonvagh** [comment]
Sure, when I get near my pc

**Comment by Tharcoonvagh** [comment]
Apparently it's good now
