### ISSUE TITLE
Bees Can't Ventcrawl

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#48281]
Being some of the smallest creatures in SS13, you'd think they'd be able to slip into vents easily. But no, they can't.
Consistency issue.

**Comment by KangTut** [comment]
According to all known laws of vent crawling, there is no way that a bee should not be able to fit. Its wings and fat little body are small. The vent, of course, denies access anyways. Because vents don't care what bees think is impossible.

**Comment by AnonymousNow** [comment]
Fix PR is up now. Thanks for helping me with my emulsions, Ty.
