### ISSUE TITLE
Some Simplemobs Don't See Indicators for Local Conditions That Hurt Them

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#48280]
I have a specific example here: if you're a sentient bee, you're vulnerable to damage from high temperatures, but your HUD won't indicate any sort of temperature shift whatsoever. This can leave you guessing as to why you're taking damage from seemingly nothing.

Since simplemobs are vulnerable or immune to different things, like a need for oxygen, cold, heat, pressure, fire etc., and we've recently added a generic push-pull button, it'd be great to see such additions here. I imagine that this is an oversight, not an actual bug, but still. Simple UI elements - like the existing generic ones we have - would be greatly useful in this scenario. Ideally we'd have variant HUD elements for things that we could detect, but are not needed/effective - for example, something immune to pressure damage being able to see the pressure indicator, but in a different colour/with a different border indicating it's for informational purposes, and not indicating a threat, but that's by the by to the issue here.

**Comment by ShizCalev** [comment]
Duplicate of #37820
