### ISSUE TITLE
Atmos machine broke

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#48288]
See videos:

https://gfycat.com/closedbasicfluke

https://cdn.discordapp.com/attachments/326831214667235328/656472374803431424/final_5df8c91f12323b00144d68a3_519947.mp4

https://cdn.discordapp.com/attachments/326831214667235328/656477263616802841/final_5df8cd4935bf200014fc272b_114449.mp4

For some reason, atmos is stopping processing, cooling down very quickly, etc under some conditions.

**Comment by kopoba** [comment]
maybe its some endothermic reaction? Ive seen SM was on fire and then just stop fire and produce vapor.

**Comment by Buggy123** [comment]
Can't be; the only contents of the tile are plasma, oxygen, and CO2. The only reaction occurring should be plasma fire.

**Comment by kopoba** [comment]
> 
> 
> Can't be; the only contents of the tile are plasma, oxygen, and CO2. And it shouldn't be producing tritium. The only reaction occurring should be plasma fire.

Im sure its can produce water vapor atleast

**Comment by Buggy123** [comment]
To put it another way; if tritium was being created (which is required for fusion, which would be the only plausible endothermic reaction to be cooling it down) you would see either tritium in the gas mix, or water vapor (if the trit is being created and rapidly burned off).

But during the entire process the mix is being gas scanned once per tick, and it never shows anything other than plasma, oxygen, and carbon dioxide.

I've read through [reactions.dm](https://github.com/tgstation/tgstation/blob/master/code/modules/atmospherics/gasmixtures/reactions.dm) in the past when doing atmos, and I just read through it again; there are a grand total of 11 reactions, 4 of which are capable of being endothermic. **None** of these reactions are capable of occurring at temperatures these low. **None** of these reactions are capable of occurring with this gas mix. And **all** of these reactions produce byproducts which would not be consumed in this situation and so would show up in the continuous gas scans.

It is not a endothermic reaction. Atmos. Machine. Broke.

**Comment by Jalleo** [comment]
Its the CO2 percentage probably. That would absorb some of the temp and decrease the ability for the gas to burn as well. That would likely lower the temp of the fire. Especially since more plasma and O2 gets added which is coooler on its addition.

**Comment by Buggy123** [comment]
>Its the CO2 percentage probably. That would absorb some of the temp

No. [CO2](https://github.com/tgstation/tgstation/blob/master/code/modules/atmospherics/gasmixtures/gas_types.dm#L66) has less than one sixth of [plasma's](https://github.com/tgstation/tgstation/blob/master/code/modules/atmospherics/gasmixtures/gas_types.dm#L72) specific heat. Conversion to CO2 should increase temperature if it conserves thermal energy, and would not affect temperature if it doesn't.

> and decrease the ability for the gas to burn as well.


No. As you can see in the [plasma fire datum](https://github.com/tgstation/tgstation/blob/master/code/modules/atmospherics/gasmixtures/reactions.dm#L177), CO2 concentration is irrelevant; at no point does it check CO2 percentage and change the reaction speed in any way. Furthermore, unless otherwise specified reactions don't care about non-reacting gasses unless it affects a variable (pressure, total moles, etc) that it cares about. It primarily cares about the absolute quantity of moles of the reactants.


> That would likely lower the temp of the fire. Especially since more plasma and O2 gets added which is coooler on its addition.

No. If this was the case, we would not observe this same behavior in a isolated burnchamber with no gas addition/subtraction, as seen in the third video I posted. Furthermore, if you look closely you will notice that both the injector and scrubber inside of the turbine are completely deactivated and are not affecting the gas mix.

Finally, even if this was the case, why would this behavior (as seen in the third video) occur?
![image](https://user-images.githubusercontent.com/16315400/72221171-e62d1e00-3525-11ea-8824-d39cbce66cc2.png)
As you can see, this was a small burn chamber filled with a large quantity of burn mix. I removed all of the walls using a pulse gun. Not only did the gas not immediately flow out and burn the surroundings as soon as a hole was made, it remained like this for more than long enough for me to remove every wall.


**ATMOS. MACHINE. BROKE.**

**Comment by Mooshimi** [comment]
fixed by #25579 , or a related fastmos change
