### ISSUE TITLE
When detonated as a roundstart borg, the MMI's radio defaults to being off.

### ISSUE THREAD

**Issue by ReplicantTerry** [tgstation/tgstation#48284]
I've noticed this twice now, not sure if it's a bug or not. When playing as a roundstart cyborg, and then getting detonated, I can't talk on the radio.

Issue reported from  Round ID: 126007 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1488

**Comment by kriskog** [comment]
The explosion destroys the internal radio

**Comment by dragomagol** [comment]
Appears to have been fixed.
