### ISSUE TITLE
Golem Ghostrole Creation Notification Seems Buggy, Underpowered

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#48282]
I've had a few rounds recently where I, as a ghost, can be staring at a golem shell as it's being made and have had no notification whatsoever. I'd like to get some reproduction on this, since it seems bizarre.

That said, even before this was happening, golems had an inconsistent ghostrole notification. Posibrains get that loud bird-like noise every time one is activated, let alone made, and the closest comparable ghostrole, the swarmer, gets a unique clunking noise - golems seem to get nothing. Hell, my window doesn't even flash if it's not focused anymore.

Golem uptake has been really poor, even in rounds where ghosts have been sitting around twiddling their thumbs, and I can't help but feel that this is a factor. Being able to gently pulse a golem shell's usability every minute or two by poking it, like reactivating posibrains constantly currently does, would be rather nice, too.

**Comment by TheVekter** [comment]
I've been noticing that lag or something is causing them to hang out there even after someone's grabbed the shell, so it feels inconsistent.

**Comment by kriskog** [comment]
What do you expect us to do about this? You didnt include round ID for log diving, nor any reproduction steps. The rest of your issue is a feature request.

Follow the template.

**Comment by AnonymousNow** [comment]
Hurm. I'll have to try to reproduce it myself, then.
