### ISSUE TITLE
Unable To Use Mech Equipment As AI

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#48306]
## Round ID:
Round 126103

## Reproduction:

When inhabiting a mech as Malf AI via mech domination or as regular AI with an AI control beacon I am  unable to use its equipment or hit things or change intents. This has happened for at least two rounds that I am aware of. Image for reference: 

![](https://i.imgur.com/uVAN38t.png)

**Comment by Ty-the-Smonk** [comment]
Did you use the Hotkeys? or does it straight up not work?

**Comment by zxaber** [comment]
For the record, AIs are intended to use middle-click for mech equipment, as left-click is still reserved for AI functions.

**Comment by TheSilverNuke** [comment]
I didn't use middle-click, I actually didn't know I was supposed to do that. I ahelped it and a bug report was recommended. Uh as far as intents go I tried using hotkeys to switch intents but again didn't middle-click. That sounds like that was my issue. Thanks.
