### ISSUE TITLE
Lavaland Elites Deal 0 Damage to Mechs and can't use Abilities on Crew

### ISSUE THREAD

**Issue by MCterra10** [tgstation/tgstation#48302]
## Testmerges:
N/A (Downstream)

## Reproduction:
Be boosted lavaland elite broodmother, get revived by traitor with martyr, try to attack crew with tentacles to no effect, summoned brood don't aggro on crew even when attacked, can't damage mech even with direct melee hits either.
I think this is because obj_damage (set to 5) affects damage to mechs, and because of the neutral faction not aggroing the crew

**Comment by ExcessiveUseOfCobblestone** [comment]
other one is more active
