### ISSUE TITLE
Red alert alone

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#48303]
## Reproduction:
Get two head IDs
Go to a white confirmation thing, I forgot the  exact name
Commence the red alert process
Switch to the second id
Confirm it
Get lynched by an angry mob (???) 

E: or just use a hand teleporter, be a slimeman with two bodies, quantum pads etc

**Comment by kriskog** [comment]
Thanks

**Comment by TheVekter** [comment]
FUCK tag?

Should be easy enough to fix, put a cooldown on the thing longer than the duration to swipe another ID.

**Comment by kriskog** [comment]
Just dont allow swiping on the same authenticator. Thats whats intended anyway.

**Comment by AnonymousNow** [comment]
**FUCK**

WE DON'T NEED ANOTHER AVENUE FOR ENABLING STUBBED TOES

**Comment by Pugie** [comment]
The cultured way to solo red alert is woth hand tele and good timing

**Comment by Tharcoonvagh** [comment]
make it so the same ckey can't start the process and confirm it too

**Comment by rdragan** [comment]
@Tharcoonvagh I can't repro this locally, can't get the confirmation button to appear on the same device.
You did mean the same device, right? Did you do this more than once and are you sure no one else confirmed?

**Comment by Tharcoonvagh** [comment]
Hmm, Im unsure now
But you should still do this to avoid the things pugie mentioned:


> make it so the same ckey can't start the process and confirm it too

**Comment by Pugie** [comment]
wyci

**Comment by 4dplanner** [comment]
ckey based features are bad

**Comment by kriskog** [comment]
Cant see any way to reproduce this, if you get un-unsure @ me and I can reopen this.

**Comment by Tharcoonvagh** [comment]
Sure
