### ISSUE TITLE
Clowns/mimes get a regular pen put in to their bags when they receive traitor.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#48319]
This 100% occurs to roundstart mime/clown traitors. Probably due to them having crayons in PDAs, don’t really know the conditions for it.

**Comment by ATH1909** [comment]
This only happens if you have the "pen" uplink type selected in your preferences, right?

**Comment by Tharcoonvagh** [comment]
No, it's set to Pda and happened to me too
