### ISSUE TITLE
Ethereal Species doesn't have augmentation sprites.

### ISSUE THREAD

**Issue by Dustgold3062** [tgstation/tgstation#48327]
When an ethereal is augmented on the head or chest, the sprite for it doesn't appear; You can click right through it. The eyes are still there though, floating above the head.

**Comment by Tharcoonvagh** [comment]
Dupe

**Comment by Tharcoonvagh** [comment]
But this is a bit more informative, could you please include some pictures?

**Comment by Dustgold3062** [comment]
Pictures.
![bug](https://user-images.githubusercontent.com/49083241/71289170-0f48fd00-2332-11ea-8d63-6c36a638b0b8.PNG)
![bug2](https://user-images.githubusercontent.com/49083241/71289171-0f48fd00-2332-11ea-89c4-7fb25f6813dc.PNG)

**Comment by nemvar** [comment]
Duplicate:
https://github.com/tgstation/tgstation/issues/43515
https://github.com/tgstation/tgstation/issues/48178
https://github.com/tgstation/tgstation/issues/42282
