### ISSUE TITLE
Spawning as a Blob Overmind while observing someone off-station stops you from moving.

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#48339]
As said on tin, though notably the location was the emergency shuttle and it took admin intervention to fix.

**Comment by trollbreeder** [comment]
Round ID for logging?

**Comment by HomocidlePancakes** [comment]
Blob overmind eyes can't move over space when placing, probably related to that.

**Comment by HomocidlePancakes** [comment]
Oh, and they also spawn on the same tile as your ghost. I always thought it teleported you to station if you happen to be in space during spawn.

**Comment by AnonymousNow** [comment]
Dangit, I didn't think to get the round ID this time. My apologies.
But yes, I think HP has the issue nailed.
