### ISSUE TITLE
Most of the hotkeys are not working

### ISSUE THREAD

**Issue by CptnCapitalism** [tgstation/tgstation#48333]
Issue reported from  Round ID: 126223 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 512.1470

I tried changing the hotkey mode in Game Preferences, but the only thing that works now is "t" for talking and "e" for putting away stuff. I even tried to change the keyboard layout to english, but it didn't help. From the chat it seems like I'm not the only one.

**Comment by kriskog** [comment]
Haven't seen other reports of this, likely due to having to reset hotkeys for move keys?
Either way, hotkey stuff was updated, so lets hope this got fixed.
