### ISSUE TITLE
[READY] Fix for pacifist doctors not being able to revive patients

### ISSUE THREAD

**Issue by rekkter** [tgstation/tgstation#48331]
Hello! I made myself a character who is basically a doctor with the quirk "Pacifist".
But there is a problem. I can't defibrillate anyone because the character refuses to "harm" people.
Harming them by... not reviving them.

I have to repeatedly ask other doctors to revive people for me.
If there is no doctor around another station worker has to do the job for me.
It's a little annoying honestly.

There are more problems with the pacifist trait, but this one is especially annoying.

   :cl:
   Tweak: Characters with the "Pacifist" quirk are now allowed to revive people using the defibrillator.
   /:cl:

**Edit:** Note that this is supposed to work ONLY if your intent is set to "help" in order to avoid abuse.

**Comment by actioninja** [comment]
what

**Comment by Time-Green** [comment]
You need to put [READY] at the beginning of your title to get a maintainer to review it

**Comment by Tharcoonvagh** [comment]
Isn't this supposed to be a pull request

**Comment by trollbreeder** [comment]
Wrong place, this is the issues page, not the PRs page

**Comment by trollbreeder** [comment]
Unless you're disguising an issue as a PR, in that case, **BASED AND REDPILLED**

**Comment by nemvar** [comment]
speedmerge

**Comment by rekkter** [comment]
Isn't this an issue though? I think that this is creating gameplay problems and I would like this to be fixed! (I am sorry if I confused something, this is my first time making a report/request)

**Comment by Daxxed** [comment]
His innocence is too wholesome

On/off-topic also there are currently atleast 10 ways to harm a person and eventually kill, as pacifist.

**Comment by HomocidlePancakes** [comment]
God bless this newfriend.

**Comment by Daxxed** [comment]
Actually after some testing, it seems pacifists can use the defib just fine.
Make sure you are on help or grab intent, harm or disarm will not work.
Oh and target the chest.

Or if you wanted the defib to shock people as pacifist, which is not intended to work, you gotta EMP it first.

**Comment by JJRcop** [comment]
@rekkter You wrote your issue as if it was a PR. Changelogs are not for issues.

Please create a new issue using this link: https://github.com/tgstation/tgstation/issues/new?template=bug_report.md
