### ISSUE TITLE
Insuls grammar

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#48363]
No round id

That's some insulated gloves. 
These gloves will protect the wearer from electric shock. 
>grug protec u from bad electric

**Comment by SpaceManiac** [comment]
What do you propose instead?

**Comment by Tharcoonvagh** [comment]
Shocks

**Comment by Tharcoonvagh** [comment]
Plural because not only one shock but plenty
I guess

**Comment by Tharcoonvagh** [comment]
Wait lemme try to fix this myself

**Comment by Cyberboss** [comment]
Leave the issue open

**Comment by trollbreeder** [comment]
Seems like this is proper grammar. I don't see the issue.

**Comment by Bawhoppen** [comment]
this seems correct in my eyes too
it's saying that these gloves will protect the wearer from the state of electric shock

**Comment by Tharcoonvagh** [comment]
#48365
