### ISSUE TITLE
Xeno Larva Random Spawns Can Appear In The Thick of It

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#48369]
I've spawned in as a randomly spawning xenomorph larva in a few rounds in recent times, and I've noticed that several times it's put me right in a public place where I ought to be rumbled pretty much immediately. Notably this includes a brig cell and THE CENTRAL PRIMARY HALLWAY.

Xenomorphs are magikarp-power entities and need a degree of stealth to get started, or they'll be hobbled completely. Being put right in the most well-trodden thoroughfare of the station and hiding under a nearby table a split-second before the botanist comes into view is not very productive to a young, extremely vulnerable xenomorph.

I'm still not fond of the free infinite stuns, but that's another matter.

**Comment by kriskog** [comment]
These are spawn points that are explicitly placed on the maps, not something random. This is a balance discussion, not a bug.

**Comment by AnonymousNow** [comment]
Very odd. I'll take this to the forums.
