### ISSUE TITLE
Lesser Ash Drakes don't hear anything

### ISSUE THREAD

**Issue by Ryll-Ryll** [tgstation/tgstation#48372]
Issue reported from  Round ID: 126427 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1503

Step 1: Be a lesser ash drake, either by magicarp changing or being put into a freshly spawned simplemob, both work (or don't work rather)
Step 2: Say something or have someone around you say something
Step 3: Nothing comes up, not even a "you can't hear so-and-so" message, you may think you're mute if you're the one speaking

**Comment by kriskog** [comment]
Seems to be an issue with megafauna in general. They do speak like normal, they just cant tell or hear others speak.

**Comment by Coconutwarrior97** [comment]
I just tested this and I'm unable to speak as a megafauna either.

**Comment by trollbreeder** [comment]
Probably because megafauna weren't meant to be player controlled up until drake blood became a thing.
