### ISSUE TITLE
Santa can be female

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#48389]
![image](https://user-images.githubusercontent.com/35217076/71419530-ebaeeb00-2680-11ea-944d-193ba83a5a56.png)

**Comment by HomocidlePancakes** [comment]
I payed 200$ for this? NEETbucks are not infinite.

**Comment by Tharcoonvagh** [comment]
more info please

**Comment by HomocidlePancakes** [comment]
Santa is a woman.

**Comment by Tharcoonvagh** [comment]
God damn

**Comment by trollbreeder** [comment]
It's Mrs Claus, stop being so sexist!

**Comment by spessbandit** [comment]
not a bug

**Comment by RaveRadbury** [comment]
![image](https://user-images.githubusercontent.com/3204033/71748829-a16bfd80-2e28-11ea-891c-fa7289753741.png)

**Comment by OnlineGirlfriend** [comment]
Smh, next you’ll be saying god is a man.

**Comment by HomocidlePancakes** [comment]
I forgot to mention Santa can also be black.

**Comment by RaveRadbury** [comment]
In this day and age anyone can be santa. Not a bug.

**Comment by optimumtact** [comment]
not a bug, santa is a goatdemon and takes whatever form allures your more
