### ISSUE TITLE
Grinders do not auto-stop consuming resources when grinding mineral stacks

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#48387]
Grinders will automatically stop grinding items that contain reagents once they've filled their beaker, avoiding wasting them all if there are excess.

However, this does not work properly with mineral stacks, and a grinder will gleefully consume a entire 50 sheets of plasma or such even though the largest beakers can only hold a total of 15 sheets worth.

**Comment by Daxxed** [comment]
If you tell your coffee machine to serve you 10 cups of coffee, but you only put one cup under then guess what ? You just lost a bunch of coffee.
INTENTIONAL...FEATURE...
