### ISSUE TITLE
Voice of God/Divine vocal chords cause chat mute

### ISSUE THREAD

**Issue by Daxxed** [tgstation/tgstation#48393]
## Round ID:125101
and pretty much any recent round a miner got VoG and went mining afterwards

## Reproduction:
Kill colossus
**Get VoG implanted**
Use the voice ( Optional ??? )
Try to kill more (mega)fauna
You fire the PKA
**click x3** ( doesn't have to be PKA, anything that generates identical chat logs does the job )
WARNING: Too many messages, ignoring this warning will mute you
You will be fully muted shortly after

Have not been able to reproduce it on localhost but had it happen twice to myself and had reports of other miners experiencing the same issue.

Almost as if the mechanic that is trying to read your voice of god commands is now analyzing your PKA shots and turning them into chat messages ?
Just a wild theory by someone who does not code, though

**Comment by kriskog** [comment]
Unrelated to ka, happened to people setting up SM normally. Vog is a factor for sure though. Mute is ic chat.

**Comment by HomocidlePancakes** [comment]
Mute happens when you do the same action that results in chat messages multiple times in a row.

**Comment by tralezab** [comment]
i wouldn't be surprised if this was related to SSchat

**Comment by Daxxed** [comment]
> 
> 
> Unrelated to ka, happened to someone setting up SM normally. Vog is a factor for sure though. Mute is ic chat.

Obviously it's unrelated to the PKA which is why the issue report is called "Voice of God does X"
The PKA is probably the most common thing that will make people find out about this bug though.
Anything that generates a decent amount of chat logs will break it.

**Comment by HomocidlePancakes** [comment]
I should mention that removing the VoG does not fix this. You'll end up being muted anyway.

**Comment by ShizCalev** [comment]
i have a feeling this is a dupe
