### ISSUE TITLE
kilostation plus rods

### ISSUE THREAD

**Issue by gitbirb** [tgstation/tgstation#48396]
Kilostation has 2 Z levels supposedly, one is COMPLETELY empty, and all the immovable rod events (probably more events too, can't be for sure though) spawn on the empty Z level instead of hitting the station

**Comment by trollbreeder** [comment]
Wait, why does kilo have 2 Z-Levels?
Is that why kilo keeps crashing?

**Comment by WarlockD** [comment]
Not sure.  12 is not used for anything and shold be used for shuttle trasport but 13 is used instead.  In fact you sometimes see the white ship permently stuck in 13 for some reason.
