### ISSUE TITLE
Cloning People can get the teleport trauma and teleport out of the pod

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#48407]
Issue reported from  Round ID: 126659 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1488

Some dude was cloning, then he just disappears. then I saw some cata dude teleporting around, I assume the guy re-entered his body, and poof hes alive again but barely cloned. idk this might be a feature

**Comment by kriskog** [comment]
Emergent gameplay

**Comment by trollbreeder** [comment]
Another time (dont remember the round ID) i got acidic flesh and melted in the cloner. There was no one to babysit the pod.
I suggest some mutations get blacklisted from cloning to prevent shenanigans like these.

**Comment by ATH1909** [comment]
> Another time (dont remember the round ID) i got acidic flesh and melted in the cloner. There was no one to babysit the pod.
> I suggest some mutations get blacklisted from cloning to prevent shenanigans like these.

Or maybe just suppressed while you're cloning?

**Comment by trollbreeder** [comment]
> > Another time (dont remember the round ID) i got acidic flesh and melted in the cloner. There was no one to babysit the pod.
> > I suggest some mutations get blacklisted from cloning to prevent shenanigans like these.
> 
> Or maybe just suppressed while you're being cloned/in a cloning pod?

Good idea

**Comment by HomocidlePancakes** [comment]
I remember a wormhole spawning on top of cloner. The poor sod got yeeted out in to space without any limbs.

**Comment by kriskog** [comment]
Should probably be supressed while cloning

**Comment by MCterra10** [comment]
> 
> 
> I remember a wormhole spawning on top of cloner. The poor sod got yeeted out in to space without any limbs.

Impossible, wormholes only teleport you if you walk on top of them, not if they spawn under you. That's why you stand still during the event. You're full of shit
