### ISSUE TITLE
Spectral Swords force you to orbit forever

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#48408]
Issue reported from  Round ID: 126664 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

Have it in any round. Have your ghost orbit it, they will be stuck forever on the sword as attempting to orbit another person after that will just yank you back again.

**Comment by Electronics** [comment]
If you move off of the sword, and then try orbitting does it still happen?

**Comment by trollbreeder** [comment]
THE RIDE NEVER ENDS

**Comment by TheMidnightRose** [comment]
> If you move off of the sword, and then try orbitting does it still happen?

It will just yank you back to the sword within two seconds of you moving off it

**Comment by kriskog** [comment]
Im unable to replicate this. So far I have tried orbiting the sword holder and the sword, both before and after calling for help. Nothing has caused me to get pulled back so far, can you provide any more reproduction steps?

**Comment by TheMidnightRose** [comment]
No, thats usually how it would work, someone would call for help, then you would orbit them, then be stuck on the sword forever.

**Comment by Shadowflame909** [comment]
This has happened to me as well. No clue whats causing this

**Comment by MCterra10** [comment]
Happens downstream on austation to. The only way to free the captured soul is to convert them to a human (or other mob) and delete it

**Comment by TheMidnightRose** [comment]
> Happens downstream on austation too. The only way to free the captured soul is to convert them to a human (or other mob) and delete it

Easier way is to delete the sword. Giving the owner something else to replace it until we we figure out what causes this.

**Comment by Wayland-Smithy** [comment]
### Steps to reproduce:

1. Join a dev server with **three** clients, I used 2 ckeys and 1 guest. 1 spawn in and 2 observe (We will call them Ghost#1 and Ghost#2)
2. Spawn a `ghost_sword` for the living, and have them holding it (using it in hand to notify ghosts is not necessary) 
3. Orbit the holder with Ghost#1 and then Ghost#2
4. Move a tile in any direction as the holder
4. Stop orbiting the holder with Ghost#2
5. Now every time the sword moves Ghost#2 will be teleported to it, and does not count toward damage.
