### ISSUE TITLE
chainsaw oddity

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#48411]
Steps to reproduce:
1. Pick up a chainsaw.
2. Turn on the chainsaw.
3. Drop the chainsaw.
4. Pick up chainsaw again.
5. Hit something; notice that you're doing less damage than you "should" be doing, despite the chainsaw having its "on" sound effects and sprite.
6. Turn the chainsaw off and on again.
7. Hit something; notice that you're doing the damage that you "should" be doing now (in other words, the chainsaw is working properly again).

**Comment by HomocidlePancakes** [comment]
Not less damage - no damage.

**Comment by kriskog** [comment]
Likely wield resetting force or something. I fixed something along those lines with potted plants a while ago.

**Comment by jacklecroy** [comment]
unwield proc is called when you drop the chainsaw, this resets the force.

**Comment by Sealed101** [comment]
no longer an issue
