### ISSUE TITLE
Firing pins don't exist?

### ISSUE THREAD

**Issue by Ohagi-Chan** [tgstation/tgstation#48417]
## Round ID:

Round 2826 on AuStation

## Reproduction:

On two occasions I used pin removal to remove a firing pin from a roundstart riot shotgun only for my hand to be empty (the character sprite was holding the firing pin though).
When I dropped the first pin to the floor I could not find anything on the floor to pick up.
When I tried to insert the second pin into a weapon, I could not insert it into any of my weapons that had no firing pins, nor would my character pick up the weapons either.

**Comment by Ohagi-Chan** [comment]
More info:
After making this issue, I found that my second firing pin was no longer displaying on the character sprite any more.
I could perform the pin removal craft again, despite none of the guns around me containing a pin and got the following message
"The tesla gun can now fit a new pin, but the old one was destroyed in the process.
Pin Removal constructed."

I am still unable to do anything with the non-existent firing pin in my hand.

**Comment by wesoda25** [comment]
I am pretty sure this isn't a bug, and that it was done on purpose so that people (scientists) can't harvest firing pins from shit like KPA for their guns.

**Comment by ShizCalev** [comment]
It's a bug. It's because the loc of the weapon when it's held is technically in nullspace.
