### ISSUE TITLE
Any surgery step that heals damage dealt during surgery heals whatever limb was last damaged.

### ISSUE THREAD

**Issue by EmptyLullaby** [tgstation/tgstation#48432]
sigh, lets try this again

During any step, ie: clamping bleeders, ending the surgery via cautery, etc, that causes healing, if any brute damage is sustained after the damage but before the healing step, the damage last taken will be healed.

How to reproduce: punch somebody in the face and then clamp their bleeders or cauterize their surgery and watch as magically their chest is still sawn open but their face is good as new.

**Comment by Spaceinaba** [comment]
sometimes this doesnt occur but i cannot for the life of me figure out why

**Comment by AnonymousNow** [comment]
What's the extent of this? Does it heal said limb entirely if it received all its damage in that interstitial phase?

**Comment by Spaceinaba** [comment]
@AnonymousNow seems to be healing the damage it would have healed normally, in the case of organ manipulation being 45 damage, the most baffling part to me is for some reason if you hit them once, it always heals that limb, if you hit them multiple times occasionally it will heal them correctly.

**Comment by Whoneedspacee** [comment]
isn’t there a healing priority to certain limbs in some cases, might be related.
