### ISSUE TITLE
Long shuttle lands in xenobiology

### ISSUE THREAD

**Issue by DrLuke** [tgstation/tgstation#48438]
## Round ID:

Round ID: 126818

## Testmerges:

BYOND Version: 512.1484
Server revision compiled on: 
Master commit: 339a7b4772b464bcd64156a34707df3a0e6f3e04
Server tools version: /tg/station 13 Server v3.2.6.2

## Reproduction:

Order long shuttle (whatever it's called), it lands in xenobiology on Metastation

![grafik](https://user-images.githubusercontent.com/1679780/71550243-3b8efa00-2980-11ea-9426-cfedf9e4c3c6.png)

**Comment by kriskog** [comment]
Thats the pubby shuttle, and also xenobio not virology

**Comment by CAPTTLasky** [comment]
This is a feature, of course.

**Comment by cacogen** [comment]
I thought docking ports took width into consideration

**Comment by optimumtact** [comment]
yeah this isn't a bug
