### ISSUE TITLE
TGUI-Next vending machine repurchase issue

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#48431]
1. Be retarded bartender
2. Buy bandolier
3. Double click bandolier and accidentally put it in machine
4. Try to buy it back
5. Not showing up
6. Have to ahelp and beg for a bandolier

https://i.imgur.com/oJKm1lV.png

**Comment by kriskog** [comment]
@actioninja vending machine UI?

**Comment by dragomagol** [comment]
#49023
