### ISSUE TITLE
Legionnare  poor feedback.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#48436]
There is no way to know when his abilities are off cooldown, which results in a rather awkward gameplay. Also, all of the abilities require you to click on the screen, which is, again, confusing. Other Lavaland Elites most likely have the same issue.

Here is what I suggest for the legionare: All abilities except for the dash trigger on action button click. After that it should default to the dash.

**Comment by HomocidlePancakes** [comment]
Ok, after some testing I've noticed that using an ability with a cooldown will prevent you from using other abilities until it's cooldown is over. Very awkward and might be unintentional.

**Comment by HomocidlePancakes** [comment]
@IndieanaJones

**Comment by IndieanaJones** [comment]
Like most ranged simple mobs, Lavaland Elites use the built-in cooldown system that was originally used for ranged attacks.  Some of the megafauna also use this system as well.  If elites could spam all their attacks all of the time, they'd be very busted.

**Comment by HomocidlePancakes** [comment]
@IndieanaJones 
>If elites could spam all their attacks all of the time, they'd be very busted.

I’ve never said that they should have their CD changed. I was complaining about poor controls and the fact you don’t know when CD is over.

**Comment by IndieanaJones** [comment]
> that using an ability with a cooldown will prevent you from using other abilities until it's cooldown is over. Very awkward and might be unintentional.

This here is what I'm referring to.  If I could immediately chain attacks and each had their own cooldown, the fights would be very busted.  Legionnaire would be perhaps the least busted, but the rest of the elites would be very busted.

**Comment by TheBonded** [comment]
it seems like you choose which ability to be using, and you have a cooldown on attacking, which is intentional. can you imagine if the colossus could use all of it's attacks at once? that's why using one puts all on cooldown. probably intentional
