### ISSUE TITLE
Drinking water and potassium does not result in an explosion

### ISSUE THREAD

**Issue by SyruseEln** [tgstation/tgstation#48464]
## Reproduction: drink water and potassium, look at logs, proceed to not die

Virtual John got this log when I drank water and potassium.
Tyber Riers says, ">ADMIN LOG: Reagent explosion reaction occurred at Corporate Showroom (107, 119, 2) (JMP) inside Syruse Eln/(Bob Oakland)(?) (FLW). Last Fingerprint: Syruse Eln/(Bob Oakland)(?) (FLW)."

It also shows the "The solution violently explodes!" message in chat but nothing happens.

**Comment by HomocidlePancakes** [comment]
Bruh moment. 5u of water/potas won’t do shit.

**Comment by SyruseEln** [comment]
Cobby has fucked up chemistry so badly I dont know if its intended. Previously it would produce a 0,0,1 explosion on you and kill the drinker.

**Comment by ATH1909** [comment]
> Cobby has fucked up chemistry so badly I dont know if its intended. Previously it would produce a 0,0,1 explosion on you and kill the drinker.

The potass+water reaction's explosive power got nerfed a few weeks ago. It wasn't even cobby that made the explosive reactions update PR; don't blame him for everything chemistry change that you don't like.
