### ISSUE TITLE
Life bringers cant vend seeds, dont have money or ID card

### ISSUE THREAD

**Issue by Autisem** [tgstation/tgstation#48475]
## Reproduction: Play as a life bringer

The life bringer eco system on lavaland has a seed vendor, but these vendors need both valid ID card and money. As a life bringer you have neither so you cant vend seeds so you cant really do much

Maby add a ID card with money on request until this is fixed?

**Comment by HomocidlePancakes** [comment]
They don't need an ID to be operated.

**Comment by Autisem** [comment]
> 
> 
> They don't need an ID to be operated.

They do now due to the new GUI. They also have prices attached now

**Comment by trollbreeder** [comment]
Duplicate of https://github.com/tgstation/tgstation/issues/48437

**Comment by HomocidlePancakes** [comment]
They always had prices attached, even though it was free.

**Comment by Autisem** [comment]
> 
> 
> They always had prices attached, even though it was free.

Yeah but now they cost money, and ofcourse still the issue you need a card to use the GUI

**Comment by Autisem** [comment]
> 
> 
> Duplicate of #48437

Sorry didnt know it was there
