### ISSUE TITLE
new lifebringer vault has no tiny fans under the external airlocks

### ISSUE THREAD

**Issue by triplezeta** [tgstation/tgstation#48508]
## Round ID:
127063, Bagil

## Reproduction:
become lifebringer. open external airlocks. realize that there are no fans under said airlocks, causing the vault to vent a small amount of air every time you enter and exit.
Not a bug, but it's very annoying, especially with no way to replenish air in the vault.

**Comment by kriskog** [comment]
@CAPTTLasky
