### ISSUE TITLE
Homing spell cards don't home in on people anymore.

### ISSUE THREAD

**Issue by improvedname** [tgstation/tgstation#48510]
right what it says on the tin man, they don't home they just spread like a buckshot now and its kinda lame to invest points into it if you can barely pull 25 damage off

**Comment by TheBonded** [comment]
this is intentional, they do not home in anymore. they are really fast to use though. more of a novelty than a useful combat spell

Also I think it's the magic missile spell that homes now, so you may have been thinking of that instead?
