### ISSUE TITLE
Ghosts can use Tank Dispensers

### ISSUE THREAD

**Issue by Kerbin-Fiber** [tgstation/tgstation#48513]
## Round ID: 
Any round

## Testmerges:
N/A

## Reproduction:
Be ghost
Dispense tanks
Tell people who the traitor is by dispensing 3 oxygen tanks and 2 plasma tanks.

See: https://github.com/BeeStation/BeeStation-Hornet/issues/1054

![itworks](https://user-images.githubusercontent.com/31713423/71639434-b6cc0680-2c33-11ea-983b-011481747559.gif)

**Comment by trollbreeder** [comment]
I think we need to call in the ghost busters.
