### ISSUE TITLE
Emergency shuttle craft gets ash storms?

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#48516]
## Reproduction: 
Upon docking at central command the emergency shuttle seems to be in the lavaland area, this means ashstorms can be formed. Im not sure if it effects other shuttles or if its effecting else where, but it seems odd that an ash storm can form off the lavaland Z level at all.

**Comment by HomocidlePancakes** [comment]
Miner used a staff of storms.

**Comment by Iatots** [comment]
> [2020-01-01 14:18:02.035] GAME: 14:18:02.035] GAME: The round has ended.
> 
> [2020-01-01 14:18:06.122] GAME: 14:18:06.122] GAME: Blackbox sealed.
> 
> [2020-01-01 14:18:08.310] GAME: 14:18:08.310] GAME: Boris Mahnov (Livrah/(Boris Mahnov)) has summoned staff storm at Emergency Shuttle (209, 73, 1)

**Comment by Iatots** [comment]
also lol at all the 10min restarts on pubbystation sybil2.

**Comment by peoplearestrange** [comment]
> 
> edit: summoning an ash storms shows up in the game logs, but not the attack logs.

Ahhhh! That be why! Thank you <3
