### ISSUE TITLE
Xeno door opening inconsistency 

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#48515]
Xenos can only force open airlocks. They can’t force open anything else, like a windoor (which doesn’t really matter) or a depowered blastdoor.

**Comment by trollbreeder** [comment]
Fake wall meta is now in effect

**Comment by HomocidlePancakes** [comment]
@trollbreeder wat?

**Comment by trollbreeder** [comment]
Xenos can't do anything if they cant open my autism fort with a fake wall for an entrance

**Comment by HomocidlePancakes** [comment]
You do realize fake wallks can be broken with any blunt weapon?
