### ISSUE TITLE
Any firesuit or space suit heats up character to burn damage

### ISSUE THREAD

**Issue by Electronics** [tgstation/tgstation#48523]
## Testmerges:
```
BYOND Version: 512.1488
Server revision compiled on: 
Master commit: 4332f7ccf967f65ab84ebe870338428f95a98b74
Server tools version: /tg/station 13 Server v3.2.6.2
```
## Reproduction:
Put any firesuit on (emergency / atmos / CE hardsuit), wait. You heat up and start taking burn damage.
(Yes, surrounding air temperature was 20C as normal)

**Comment by kriskog** [comment]
#48519 was merged, fixes this. Will leave this open for now so we dont get too many duplicates.
