### ISSUE TITLE
hilbert's hotel has some dumb code that changes the secret room only once the paper saying which room it is has spawned

### ISSUE THREAD

**Issue by Qustinnus** [tgstation/tgstation#48527]
by default the secret room's number is 1337, this changes once the crumbled paper which would list the secret number spawns, but this means that 1. the code changes every time a paper spawns and 2. you could end up not getting a real secret code because the paper's init doesnt run.

**Comment by ATH1909** [comment]
"a paper" or "that specific kind of paper"

**Comment by Qustinnus** [comment]
the crumbled paper im not sure ive never seen hilberts hotel

**Comment by Qustinnus** [comment]
the one with el secret hexcode
