### ISSUE TITLE
Issue with cyborg movement

### ISSUE THREAD

**Issue by Flechercap** [tgstation/tgstation#48525]
Issue reported from  Round ID: 127141 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1505

If you presss alt as as cyborg it toggles to walk and you cant run unless you keep alt held and so far i think the only way to fix it is getting rebuilt

**Comment by rdragan** [comment]
I wasn't able to reproduce this. Could you make sure that you have Hotkey mode set to 'Hotkey' and do a reset of your keybinds, then try again?
