### ISSUE TITLE
Endless Space Does not Play

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#48534]
Endless Space, the new(est) roundstart/end track to be added, does not ever play. What gives?

**Comment by rdragan** [comment]
Looks like it needs to be added to `strings/round_start_sounds.txt`. I don't understand where The Room music is coming from though, and I'm sick of it.

**Comment by rdragan** [comment]
Closing this as it's a server config. I recommend taking it to Policy Discussion on the forums, where there's already a thread about removing the room song and adding this: https://tgstation13.org/phpBB/viewtopic.php?f=33&t=22929
