### ISSUE TITLE
Shadowshrooms are producing light

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#48535]
## Reproduction:

1.Plant Growshroom
2. Use mutagen on it and create shadowshroom.
3. Harvest, and watch it produce light.
4. Plant and it still produces light.
5. Cry as the shadowperson you are, forever cursed to maint.

Heres an image of this in action: 

![](https://i.gyazo.com/0dec56c27ed3a128f078aac3b57ca8fb.png)

**Comment by kriskog** [comment]
Sure its not shadowshrooms with no shadow emission and bioluminescence added?

**Comment by Shadowflame909** [comment]
That's literally just a regular shadowshroom from spawn.
