### ISSUE TITLE
The supermatter can produce negative heat.

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#48533]
Hello and welcome to hell.
The sm will occasionally report negative heat when configured with space tiles.

This number will on very rare occasion burst down into the high negatives, and output a fuckton of power for a second. I have seen this behavior cause the sm to instant delam, but that was on my personal branch with other related changes, so take it with a grain of salt.

The second two images are from master.
[salt 1](https://cdn.discordapp.com/attachments/458452245256601615/662112138822811648/unknown.png)
[salt 2](https://cdn.discordapp.com/attachments/458452245256601615/662112221286891520/unknown.png)
[not salt 1](https://media.discordapp.net/attachments/326831214667235328/662127525933219880/unknown.png?width=925&height=682)
[not salt 2](https://media.discordapp.net/attachments/458452245256601615/662164291574693898/unknown.png?width=1117&height=681)
## Reproduction:
Setup a chamber cooling loop, and optimize the flow of the outer loop. Note, I'm not sure if this is necessary, but to work with the gasses we are going to be working with, we need good cooling.

Take out the three leftmost floor panels fully, we want space there, I've had it work with the panels above and below the sm out too.

Set your filters to either o2, plasma, or bz. I've had the best luck with bz, but o2 and plasma seem to work as well.
Now, either a: wait, or b: attach a source of bz and wait for the kpa of the gas arround the sm to be around 0. -0 seems to work better.

Then flood the chamber with the gas, and look at the pretty negative numbers.
For some reason, with enough plasma in the chamber, if it ignites during this negative number process, the heat spikes negatively, and the power has a heart attack.

Here are the images of my setup.
[Left](https://media.discordapp.net/attachments/458452245256601615/662165434493173760/unknown.png?width=715&height=682)
[Right](https://cdn.discordapp.com/attachments/458452245256601615/662165921153941505/unknown.png)
The filter was set to plasma, and all freezers were fully upgraded.

**Comment by trollbreeder** [comment]
Recommended labels:
Priority: CRITICAL
FUCK
RED LABEL

**Comment by kriskog** [comment]
SM reacts to vaccuum as far as I know, but what exactly does it do? I guess you will find out

**Comment by HomocidlePancakes** [comment]
Vaccuum just damages SM, slowly.

**Comment by TheVekter** [comment]
Getting in an early candidate for fuckup of the year 2020

**Comment by LemonInTheDark** [comment]
> 
> 
> Recommended labels:
> Priority: CRITICAL
> FUCK
> RED LABEL

It's not really critical priority, it took me 2&1/2 hours to get an appreciable power spike, and that's with access to the game panel.
If I had to wait for t4 parts and all the bz I used, it would have taken me like 3&1/2 to 4 hours.

Now if some atmos tech figures out how to do this fast and to high levels, then it's critical. But so far as I know, we haven't reached that point yet

**Comment by LemonInTheDark** [comment]
> 
> 
> Vaccuum just damages SM, slowly.

It does. But that only happens when nothing gets removed, or the sm is actually in space.
This means if we have enough gas flow, we can get away with having a vacuum tile one space away from the sm.
I'll update with more pictures of the setup pressure and the like later, but I don't think that's what's going on here.

**Comment by LemonInTheDark** [comment]
[Anecdote](https://cdn.discordapp.com/attachments/458452245256601615/663610432728334336/unknown.png)
It seems like this can cause healing as well, I have a strong suspicion this has to do with space code.

**Comment by LemonInTheDark** [comment]
The issue is entirely with space, adding 6 nonfunctional if statements to procces_atmos() fixed it. I don't know why, and it's real hacky, so if there's a better way, we should go with that.

**Comment by LemonInTheDark** [comment]
I was wrong, as always, the low mol percent was causing jumps in gas percentage and thus heat.
No fucking clue what was causing negative heat, not sure I want to know. It's fixed in the pr tho.

**Comment by LemonInTheDark** [comment]
Investigate gas.remove() and negative pressure you boomer.

**Comment by LemonInTheDark** [comment]
> 
> 
> I was wrong, as always

You sure were, it's still here, fuck and also dammit.

**Comment by kriskog** [comment]
Want this reopened?

**Comment by LemonInTheDark** [comment]
yeah, life is still pain

**Comment by LemonInTheDark** [comment]
actually fixed now.
