### ISSUE TITLE
resonant shriek ignores ear protection

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#48545]
bottom text

**Comment by MCterra10** [comment]
Fairly sure it's intentional but I ain't complaining about a ling nerf ahahahahah

**Comment by HomocidlePancakes** [comment]
I doubt this is a bug, and even if it is, what would be the intended behavior? Full block? Block the deafness? Confuse? Maybe both?

**Comment by kriskog** [comment]
Gonna go with not a bug for this one, feel free to propose changes after the antag freeze
