### ISSUE TITLE
Damage Sensor nanite program does nothing

### ISSUE THREAD

**Issue by QuantumSeanyGlass** [tgstation/tgstation#48554]
Issue reported from  Round ID: 127330 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 513.1505

Title, basically. Put a damage sensor program in my nanites, told it to do forced speech if it went off, it never did forced speech. Sending the same code with a dermal button did do forced speech.

**Comment by kriskog** [comment]
What were the settings?

**Comment by WarlockD** [comment]
I don't know why this happens.  We find out about a bug for a while, I get around to look at it and bam, its opened.  I found it last night.
```
	if(damage_amt >= damage.get_value())
		if(check_above)
			reached_threshold = TRUE
	else if(!check_above)
		reached_threshold = TRUE
```
Going to make a pull request to fix it.  Also it doesn't make the rules right either.  Its all in the same file so shouldn't take 10 min.
