### ISSUE TITLE
the new genetics lab map change makes morgue stupidly big and removes the bepis machine and experimentor instead of moving them somewhere else

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#48555]
not sure why he removed the new machine (bepis) that is still getting updated instead of replacing the useless firing range with genetics

![Ni6y2n4](https://user-images.githubusercontent.com/33834933/71717369-269ae680-2e18-11ea-8176-a9c3cbe5e1df.png)

**Comment by kriskog** [comment]
Think of the dead people!
Bepis is in the aforementioned firing range. Not a bug either.
