### ISSUE TITLE
The telegulag kills plasmamen

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#48566]
## Round ID: 127351

Step one, be plasma man, step two, get Gulagged, step three, die

**Comment by HomocidlePancakes** [comment]
#42859 should’ve fixed it. Where did this happen?

**Comment by Pugie** [comment]
Comedy gold.

**Comment by SouDescolado** [comment]
Uh.. I am pretty sure my fix worked when it was implemented. And it was one of the rare cases where I tested my PR. Is this still happening?

**Comment by Borisvanmemes** [comment]
Went and tested if this was actually still happening, it doesn't seem to be.
