### ISSUE TITLE
IED causes permanent nudity

### ISSUE THREAD

**Issue by EOBGames** [tgstation/tgstation#48562]
## Round ID:
N/A (This was on local)

## Reproduction:
Step 1: Construct an IED.
Step 2: Light it.
Step 3: Let it explode in your hand.
Step 4: If your jumpsuit burns off, it disables the display of all jumpsuits on your character. This persists through death.
![Clothesmachinebroke](https://user-images.githubusercontent.com/58124831/71728707-b26f3b80-2e35-11ea-8f85-e3a70569ca23.PNG)
Relevant image: as you can see, I'm wearing a grey jumpsuit, but it isn't displaying. This also happened with the handful of other jumpsuits you can see littering the floor.
(Note: I had trouble reproducing this after the fact- I can say that it doesn't seem to occur due to other fire sources)

**Comment by HomocidlePancakes** [comment]
Is your character female? There was an issue with some jumpsuits not showing up on fem characters.

**Comment by EOBGames** [comment]
Yeah, character was female.

**Comment by Tlaltecuhtli** [comment]
the clothing sprites are glitchy in general, they appear and disappear randomly maybe it is specifically related to ieds (icon updates?)

**Comment by TheBonded** [comment]
this has (probably?) been fixed by now

**Comment by SuperNovaa41** [comment]
this should be tested

**Comment by TheBonded** [comment]
This hasn't been reproduced in nearly 2 years, are you sure this even happened in the first place?

**Comment by TheBonded** [comment]
@SuperNovaa41 
How are we supposed to test it if it was never reproduced in the first place? It's been nearly 2 years now.

**Comment by SuperNovaa41** [comment]
oh ididn't see that
