### ISSUE TITLE
Bepis reward request: Coldlight-Welder & Service Arm Augument

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/tgstation#48571]
> Feature requests are not handled in the repository.

Speaks the bore who wrote that warning in, I could not even if i wanted to. It would not be painful to be in my company to share a loose idea too good to keep to myself.

## Description
As is customary with what i've observed from afar of the Bepis's approach of 'throw money at it until it works' it still needs more designs.

**Coldlight Welder**: A colorful alternative to a welder, it is no stronger than a normal welder by comparison but has two fuel inputs of welding fuel and water which deplete equally so twice the capacity. Things in attack intent often cool and recieve burn damage if they are able to, including interactions with water, ability to frost up windows and it doesnt trigger plasma fires.

**Service Arm Augument**: Just like it promises, it is a integrated service borg's assortment of goodies, not least limited to a drink synthesizer, a zippo lighter attachment, retractable card & dice storage, a always availible fountain pen attachment and a voice recorder. Boring perhaps but for a bartender or party host, these little miscellaneous functions are indispensible.

## Why I think it should be added
You can't rush the Bepis's method of production and neither of these objects are poor rewards, perhaps individually not useful as some other things but flavorful additions that are welcome whenever they arrive (if they arrive) in a round

The Coldlight Welder has some opportunities for shenanigans or theming, a clown could freeze wet tiles to increase their slippyness, engineers can have it around as a spare welder and arguebly more useful defence against lizard muggers trying to disarm them for insulateds. Chemists can also freeze beakers full of reagents just the same way welders can heat them up if inclined.

The Service arm augument is a lot more boring, but i dont doubt that people will find niches to abuse it if additional emagged functions are availbile like spiking punch with the synthesizer, or using the inbuilt zippo lighter attachment to burn away the evidence of your misdeeds. Or if you felt inclined, just cheat at poker like a ordinary crook and stab their eyes out with the pointy end of the pen when they attack you after getting caught.

## Screenshots and concept art
Its much more vivid in my head i assure you; generic blue flame for the coldlight, like a emergency welder's blue stripes with much more pzazz.  The augumented arm looks like it was ripped right off a borg, with a chrome and brown finish.

**Comment by RaveRadbury** [comment]
Feature requests are not handled in the repository.
