### ISSUE TITLE
respawn time everybody

### ISSUE THREAD

**Issue by joybod** [tgstation/tgstation#48575]
Issue reported from  Round ID: 127394 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1503

i joined round normally at roundstart, normal shift stuff happened, i was killed at some point, left for a while(closed game), got back on just before round end, was prompted to become split personality, that person died, i reconnected and was put to lobby where i could join game. i then went to my corpse and it indeed was me as i had previously used the ghost role button return to body and it was the same one. started as engineer, respawned as medical doctor

**Comment by joybod** [comment]
username ingame is joybod

**Comment by trollbreeder** [comment]
Split personalities have been reported to be really fucky if your host dies while you're disconnected.

**Comment by kriskog** [comment]
Collection of similar issues here #48575
