### ISSUE TITLE
Cook's tray displaying collected items below itself

### ISSUE THREAD

**Issue by Tarasus** [tgstation/tgstation#48582]
Cook's tray displaying collected items below itself, when in hands or any slot

Issue reported from  Round ID: 0 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1488

**Comment by nemvar** [comment]
Ancient bug. Surprisingly enough this is the first report of it.

**Comment by nightred** [comment]
This bug is not reproducible any more.
Suggest closing.
