### ISSUE TITLE
Falling over while using Binoculars flips your character sprite upside-down

### ISSUE THREAD

**Issue by BowNArrowPro20** [tgstation/tgstation#48593]
### **Reproduction:**
Falling over while using the binoculars flips your character sprite. I've done it by being knocked over and flipping till I fall and it has worked every time.
![image](https://user-images.githubusercontent.com/22554437/71775192-8a253100-2f4a-11ea-8074-2ecf410e04e0.png)

**Comment by ATH1909** [comment]
Is this permanent?

Please, god, let this be permanent.

**Comment by ATH1909** [comment]
Can other people see this flipped sprite?

**Comment by CitrusGender** [comment]
Can someone check to see if this applies to all two-handed or just binoculars? If I had to guess, it could be related to the fact that it regenerates the icon twice at the base of two-handed.dm.

I'm at work right now so I can't verify though.

**Comment by cacogen** [comment]
This is caused by the mob's brain flipping the signals received from its eyes rightside up. When you fall over, the body needs to reorient itself to continue seeing properly.

**Comment by BowNArrowPro20** [comment]
Yes, everyone sees it as you being flipped over. I'll see about testing it with other 2-handed weapons right now. As far as I'm aware it lasts until end of round or you do it again to revert yourself back to normal.

**Comment by Sealed101** [comment]
can no longer reproduce
