### ISSUE TITLE
Call Shuttle button on Comms Console doesn't work on WINE

### ISSUE THREAD

**Issue by Victor239** [tgstation/tgstation#48598]
## Reproduction:
- Use [Lutris](https://lutris.net/games/byond/) to install BYOND 
- On tg try to call shuttle on the Comms Console
- Button doesn't do anything when clicked

**Comment by HomocidlePancakes** [comment]
What. Why?

**Comment by TheVekter** [comment]
Are... Are we even supporting Linux distros?

**Comment by AWalton** [comment]
I know oranges has said they use the IE version they do to maintain WINE support and there are a number of admins and players who use WINE exclusively to play as well (including myself).

**Comment by kriskog** [comment]
There is a minimum message length limit to shuttle calling, are you sure you entered a long enough message?

**Comment by AWalton** [comment]
Yeah, positive.

**Comment by jlsnow301** [comment]
Feel free to reopen this issue but I don't think Linux is officially supported, nor would the concern be valid post-TGUI

**Comment by Victor239** [comment]
Yeah WINE is no longer compatible due to TGUI, a VM like in [this method](https://www.reddit.com/r/SS13/comments/rmnaeb/guide_how_to_run_ss13_on_linux_by_using_vmware/) is the only working way atm to play on Linux.

**Comment by TheVekter** [comment]
This isn't necessarily true. Most TGUI functions work well in Wine.

**Comment by Victor239** [comment]
Well the entire right panel is TGUI so that's a pretty substantial part no longer working, I stopped trying even before that when I found other TGUI interfaces were incompatible.
