### ISSUE TITLE
Poly said something odd

### ISSUE THREAD

**Issue by ReplicantTerry** [tgstation/tgstation#48591]
Overheard Poly say this while playing as AI:

`[Engineering] Poly (Unknown) says, "[02:31] <span class='game say'><span class='name'>Flowunk</span> <span class='message'>flutters, "<span class=' '>Three tier of suit sensors</span>"</span></span>`

That is to say, it was left unformatted by my client

Issue reported from  Round ID: 127456 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1488

**Comment by spessbandit** [comment]
same issue as https://github.com/tgstation/tgstation/issues/36758

**Comment by PKPenguin321** [comment]
Dupe of #36758
