### ISSUE TITLE
You cannot directly add a 50 of tc to an ancient toolbox, but stacks combine in the toolbox anyway

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#48614]
If somehow you get 50 tc (actually not impossible because of contractors), then take your trusty ancient toolbox and try adding a stack of 50 telecrystals. It's too big.

Separate then into small amounts. Like 25. They fit! But moreso, they combined inside the toolbox into a stack of 50 anyway despite not being allowed to do so initially.

Not much more too this one, kind of just a silly oversight.

**Comment by GravitronBlue** [comment]
Sounds like a dupe of #37087
>This bug is at least as likely to annoy the user, since they will later pull out something that cannot be put back in directly.

**Comment by ATH1909** [comment]
This happens with mining bags and large stacks of ore too.

**Comment by kriskog** [comment]
Stacking should have a storage size check

**Comment by necromanceranne** [comment]
Closing this one in favour of the other report.
