### ISSUE TITLE
Broken chameleon hat sprite

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#48626]
## Reproduction:
-buy chameleon hat from black market thing 
-wear it
-wait for the broken sprites

Yeah it has some, the ones I noticed yesterday were the shrine maiden and chaplain cage

**Comment by kriskog** [comment]
Likely not a chameleon hat thing really, just missing sprites for some of the hats it cycles through.

**Comment by Coconutwarrior97** [comment]
Its not that they're missing but that they aren't fitting right on the head. 

![image](https://user-images.githubusercontent.com/40315842/73932379-d2b07100-489f-11ea-9b14-0dd0ceb29ca4.png)

**Comment by kriskog** [comment]
:thinking:

**Comment by Tharcoonvagh** [comment]
Pretty distracting

**Comment by Sealed101** [comment]
couldn't reproduce; both hat sprites mentioned did not have a wacky offset, nor did i see any broken to shit sprites for other hats
