### ISSUE TITLE
ignore_slowdown() doesn't do anything

### ISSUE THREAD

**Issue by knacker48** [tgstation/tgstation#48631]
## Reproduction:

- Create a Red stabilized slime

- Put it in your bag

- Wear bio suit or other equipment that slows you down

- Continue to be slow

Red stabilized slimes are suppose to make you ignore equipment slowdowns. As they are now they do nothing. I've tried this with multiple different equipment so I know its not specific to bio suits.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/1c3c76cafcdaf6933eafb85748e03501e3b42490/code/modules/mob/living/carbon/human/human_movement.dm#L1-L8

`IGNORE_NOSLOW` isn't actually implemented.

**Comment by knacker48** [comment]
Its weird since I've used it before and it definitely worked. Maybe someone changed it in a pr?
