### ISSUE TITLE
MULE bot tgui-next interface is broken

### ISSUE THREAD

**Issue by flufflycthu1u** [tgstation/tgstation#48662]
## Testmerges:

#48583 (don't think this is the issue)

## Reproduction:

Open the MULE bot interface (added in #48470 ), set a destination and hit go.
The mule bot will always buzz and say that it can't find a path to the destination.

Using the PDA bot connection interface it is possible to set a destination, hit go, and have it path normally. Part of it seems to be that changing the destination in the ui doesn't actually change the bot's destination.

When I tested it on a personal server this was also causing runtimes.
Additionally the power button in the top right doesn't seem to work.

**Comment by kriskog** [comment]
@actioninja
