### ISSUE TITLE
ALL character custom colors are forced to black

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#48666]
## Round ID:
127642 Manuel

## Reproduction:
>Game Preferences
> Character Settings
> select a character
> Change the color of ANYTHING (hair, beard, eyes)
> Press OK to set the color
> Color will turn to black no matter the color selected

You can also do this from Character Setup from the lobby as well with the same results.

Reproduced by a random player and myself.

**Comment by spessbandit** [comment]
06:11:36: Reply PM from-Jamarkus/(Michael Loginstin): got it. an easy way to fix it is to lock down literally everything except eye(?|F) colour, and keep hitting random until you get the desired colour.

**Comment by HomocidlePancakes** [comment]
Sorry, but I can't resist.

###  **BLACKED**

**Comment by Tharcoonvagh** [comment]
racism

**Comment by peoplearestrange** [comment]
Race jokes. Smart.

**Comment by AnturK** [comment]
@MrPerson looks related to the hex parsing changes.

**Comment by HomocidlePancakes** [comment]
Would you prefer me making a joke about your pfp? It surely warrants some.

**Comment by peoplearestrange** [comment]
> Would you prefer me making a joke about your pfp? It surely warrants some.

gee golly that would certainly be the first time anyones made a furry joke at me

**Comment by Tharcoonvagh** [comment]
people really are strange

**Comment by HomocidlePancakes** [comment]
>gee golly that would certainly be the first time anyones made a furry joke at me

I’ll take it as a yes.

So a furry and a brony walk in to a horse stable...
(CONTINUE? Y/N)

**Comment by peoplearestrange** [comment]
> So a furry and a brony walk in to a horse stable...
> (CONTINUE? Y/N)

Hahahahaha that actually made me laugh! Good job
You shouldn't know of such things.

Anyway I think we're getting a little off topic here.

**Comment by NanoCats** [comment]
Figures that this happens the one day I decide "You know what, I've been playing the same character for like 60 hours it's time to change it up"
