### ISSUE TITLE
Inertia flying consume jetpack air.

### ISSUE THREAD

**Issue by Dennok** [tgstation/tgstation#48661]
BYOND Version: 513.1505
Server revision compiled on: 2020-01-07
Master commit: e87033d792cf4834f4fc18b0e6a2c2057859ce89

## Reproduction:

Equip jetpack turn on (with no stabilization) and jump to graveless room. 
You see as you fly doing nothing you jetpack use air.

**Comment by kriskog** [comment]
Worse than that, fairly sure it consumes in gravity too :slightly_smiling_face:

**Comment by Fhaxaris** [comment]
```
RegisterSignal(user, COMSIG_MOVABLE_MOVED, .proc/move_react)

/obj/item/tank/jetpack/proc/move_react(mob/user)
	allow_thrust(0.01, user)

/obj/item/tank/jetpack/proc/allow_thrust(num, mob/living/user)
	var/datum/gas_mixture/removed = air_contents.remove(num)
```

The signal is registered when the jetpack is turned on, so any movement when it's on will use fuel.
