### ISSUE TITLE
Extra space after beginning and before ending quotation marks in speech

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#48688]
This has been around for a while now. I believe it's caused by Goonchat because they're not there when you switch to old chat. Also saving logs/screenshots with Goonchat sucks compared to old chat.

[Common] Mark Zuckerberg  says, " .a Dumb fucks. " 
The newscaster  beeps, " Breaking news from Fox and Friends! "
H.P. Lovecraft  says, " Damned dirty apes "

**Comment by kriskog** [comment]
Duplicate of #28876

**Comment by kriskog** [comment]
Gone for me after 513, are you still seeing this?

**Comment by cacogen** [comment]
Nope

**Comment by kriskog** [comment]
Good, thanks
