### ISSUE TITLE
Incorrect camera naming.

### ISSUE THREAD

**Issue by Something1sWrong** [tgstation/tgstation#48698]
Issue reported from  Round ID: 127787 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

There is a camera outside of armory with the name E.V.A. storage.

Reporting client version: 512.1488

**Comment by kriskog** [comment]
Which map? Was this in the camera console or in the world?

**Comment by Angustmeta** [comment]
Metastation. And the EVA camera is named armory - external iirc. Seen with camera console. Try to look at EVA camera with cam console and it takes you to armory instead.
