### ISSUE TITLE
Hypnotic Flash victims do not display this status under the Combo HUD, or in the Traitor panel

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#48707]
Issue reported from  Round ID: 127821 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

This makes adminning a lot of viewing variables and messing up when apparent nonantagonists kill their coworkers for no apparent reason.

**Comment by kriskog** [comment]
Should probably get an antag datum for easy tracking of players and objectives.

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/61077
