### ISSUE TITLE
Any shocks/EMP seem to remove nanites from a mob entirely

### ISSUE THREAD

**Issue by redta1l** [tgstation/tgstation#48704]
## Testmerges:
#48583: 'Don't recheck connected clients in isbanned() (and other isbanned() dos mitigations)' by MrStonedOne at commit 23fba6671c 
#48569: 'FIXED: Better species environment handlers, and custom race body temperature' by nightred at commit 76577a995d 

## Reproduction:

1. Get nanites, wait for volume to fill entirely.
2. Get shocked by a door, or a tesla revolver shot, or get hit by an EMP.
3. Scan yourself and realize that all your nanites are completely gone, no matter the strength of the shock/EMP.

**Comment by kriskog** [comment]
I seem to remember this being intentional. @XDTM?

**Comment by Fhaxaris** [comment]
The procs are triggered by COMSIG_LIVING_ELECTROCUTE_ACT and COMSIG_LIVING_MINOR_SHOCK respectively. `living_defense.dm` doesn't use the minor shock signal, and always sends an electrocute. I think living defense needs to be updated to choose between the minor and electrocute.

https://github.com/tgstation/tgstation/blob/aa982387a19ceea2995d6be96514dfd34cf92f90/code/datums/components/nanites.dm#L199-L210
https://github.com/tgstation/tgstation/blob/aa982387a19ceea2995d6be96514dfd34cf92f90/code/modules/mob/living/living_defense.dm#L342-L343

**Comment by XDTM** [comment]
No, minor shock is caused by specific sources like stunbatons and defibrillation which are not proper shocks. The way the mechanic works is that shocks first remove a percentage of all nanites, then remove a flat value, for a maximum total of 55% + 50 nanites in a single shock. If a full tank of nanites got killed in a single shock it's definitely a bug, unless it was multiple simultaneous shocks somehow.

**Comment by Fhaxaris** [comment]
https://github.com/tgstation/tgstation/blob/aa982387a19ceea2995d6be96514dfd34cf92f90/code/datums/components/nanites.dm#L200
![image](https://user-images.githubusercontent.com/13771064/72193866-fed7ef80-33d0-11ea-8578-981eb1a2f539.png)
[uh oh](https://secure.byond.com/docs/ref/index.html#/proc/rand)

**Comment by XDTM** [comment]
uh oh, good catch
