### ISSUE TITLE
Recycler is hilariously broken

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#48706]
In no particular order:

Putting in some ammo boxes does this:
![image](https://user-images.githubusercontent.com/16315400/72119764-7e0eea00-3323-11ea-8e0d-886b667f25db.png)

Recycling a MMI removes the brain from the MMI in a very broken way:
https://gfycat.com/animatedperiodiccuscus

Recycling a sentient posibrain just deletes it.

If it was slightly less broken, recycling anything filled with non-items (like projectiles inside of bullets, etc) would create 1 sound. Per non-item. Throw in a donksoft LMG or something and:
# BEEP

I could go on.

**Comment by kopoba** [comment]
MMI issue dupe https://github.com/tgstation/tgstation/issues/41824

**Comment by timothymtorres** [comment]
This appears to have been fixed with #48711
