### ISSUE TITLE
Lavaland mobs ignore Crusher Hiero Barriers, Blob walls fail to prevent laser fire.

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#48712]
Issue reported from  Round ID: 127833 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

Mining today, killed hiero per usual and grabbed the barrier trophy as its nice, decided to go kill Colossus on my way to the Drake. Imagine my immense surprise when I was instantly shotgunned THROUGH MY BARRIER and Colossus walks right through it as though it was not there at all.

Couple of the people who usually watch me crusher mine suggest that it is #48659 that lets this happen.

**Comment by TheMidnightRose** [comment]
Did some testing and it DOES contain Teslas with Field Generators, but Blob walls are able to be walked on and shot through like they are not there. Pulsing Tumor Barriers are also able to be walked through by the mobs inside of it, which is supposed to be impossible.

**Comment by kriskog** [comment]
Blob tiles also block nothing. People and lasers can move over them.

**Comment by ninjanomnom** [comment]
I'm unable to replicate walking through pulsing tumor barriers after dealing with some other fixes so I'll assume those got fixed incidentaly
