### ISSUE TITLE
Newly built stasis beds have no way of being linked to operating computers

### ISSUE THREAD

**Issue by spessbandit** [tgstation/tgstation#48724]
## Reproduction

Have a pre-existing operating computer, build a Lifeform Stasis Unit next to it. It won't be linked, there's no way of linking it. But build the stasis unit first and the operating computer second, and it's fine.

The reason:

This is where operating computers look for tables and stasis beds, which is only called when the operating computer is initialized: https://github.com/tgstation/tgstation/blob/b2be5e5dcab6fa3979b3c13cfa672eaec789b34e/code/game/machinery/computer/Operating.dm#L49

This is how operating tables do it, by manually setting the var instead (which, incidentally, why.):
https://github.com/tgstation/tgstation/blob/53024590decf7325d779d55b79b37424d730ea68/code/game/objects/structures/tables_racks.dm#L463

And this is the code for stasis beds, which are not children of operating tables and never link anywhere:

https://github.com/tgstation/tgstation/blob/4057c7b22c85a719cc65852fe54c1b6397fd1596/code/game/machinery/stasis.dm

Which means if the stasis bed is built after the computer, it will fail this:

https://github.com/tgstation/tgstation/blob/e4b6de4097026cea901ee483d8d6b362ef26ebcd/code/modules/surgery/surgery.dm#L75

High priority bug IMO especially if we're getting rid of cloning.

**Comment by AnonymousNow** [comment]
Good catch. Please fixu.

**Comment by spessbandit** [comment]
also, according to the player who brought this to my attention, apparently manually proc-calling find_tables on the computer doesn't update the UI, but I haven't tested that myself and there could be other factors

**Comment by BowNArrowPro20** [comment]
As far as I'm aware, you can simply unscrew the operating computer then screw it back, and the stasis beds will link properly.

**Comment by spessbandit** [comment]
yeah, that's a workaround (because it causes the operating computer to call initialize) but there shouldn't need to be one

**Comment by Archanial** [comment]
> 
> 
> As far as I'm aware, you can simply unscrew the operating computer then screw it back, and the stasis beds will link properly.

I just tested it on Manuel. Even after rebuilding computer with unlinked bed near it, computer's UI still doesn't update while bed is getting linked.

**Comment by 81Denton** [comment]
Going to pin this issue since it'll be important to fix before cloning removal.

**Comment by Neo-0** [comment]
what was supposed to be shown in the UI?
