### ISSUE TITLE
AI shells create a new "old name" every time they exit

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#48725]
### 
## Round ID:
127858 Manuel

## Reproduction:
Create AI
Create AI shell
Get AI to enter the shell
Get AI to exit the shell
Repeat

Each time the AI does this a new line will be added to the "old names" vv

This can be seen here:
https://i.imgur.com/2fQL7Pa.png

**Comment by TheMidnightRose** [comment]
From what I have experienced when using AI shells, the shells gain a name, not just an old name. The Shell will go from Engineering Shell - 553 to Engineering Shell -715 and etc, not sure why the game thinks that it is a new mob each time.
