### ISSUE TITLE
sentient spider mobs cant harm blobbernauts mobs

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#48736]
You bite the blobbernaut (384)!
The blobbernaut (384) looks unharmed!

**Comment by Whoneedspacee** [comment]
not a bug but possibly stupid

https://github.com/tgstation/tgstation/blob/7e78755bc35b3f63ed73aa6988dc62f34df596e4/code/_onclick/item_attack.dm#L113

https://github.com/tgstation/tgstation/blob/53024590decf7325d779d55b79b37424d730ea68/code/modules/antagonists/blob/blob_mobs.dm#L215

**Comment by IndieanaJones** [comment]
This "bug" is technically fixed as of the Spider Rework, with red spiders being able to deal 25 damage
