### ISSUE TITLE
Hotkey mode turning itself off/not working

### ISSUE THREAD

**Issue by luxidoptera** [tgstation/tgstation#48730]
I'm experiencing an issue with hotkey mode that seems to be fairly new; certainly wasn't a problem last time I was playing. I don't use most of the hotkeys so I can't confirm if they work or not, but I can say with certainty that using WASD to move with hotkey mode on is _certainly_ not working (simply types in the bottom bar with or without hotkey mode on). I imagine this is something similar to #48333 .

I also seem to be having an extension to this issue in that hotkey mode keeps arbitrarily turning itself off for seemingly no reason? Whenever I click on the screen with hotkey mode on, or when I press T to chat in hotkey mode, it turns itself off. (I'm also having to click in the text field for the chat window when I press T to chat, otherwise it types in that accursed bottom bar instead.)

Tried updating BYOND to see if that might help, it did not.
Round ID when I first started experiencing this was 127879 on Sybil. Client version 512.1488.

**Comment by TheMidnightRose** [comment]
The problem has been here since the start. Sometimes randomly it fails to remember your hotkey settings, which means you have to go reset it again to fix it.

**Comment by luxidoptera** [comment]
Ah, thanks for letting me know. That did, in fact, fix it.

Okay, so for those of you who are like me & always play with hotkey mode on that are experiencing this issue: in character setup, go to Custom Keybindings, click "Reset to default", and select whichever option you want. (I went with hotkey bindings of course.) That should fix the problem.
