### ISSUE TITLE
Vortex Talisman crusher trophy not working

### ISSUE THREAD

**Issue by onjec** [tgstation/tgstation#48751]
Issue reported from  Round ID: 128013 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

the barriers spawned by crusher with Vortex Talisman trophy are fully passable by hostile lavaland mobs including megafauna namely Blood drunk miner (didnt had chance to test on others since i died to the Blood drunk), watchers and goliaths

Reporting client version: 513.1505

**Comment by HomocidlePancakes** [comment]
Dupe

**Comment by onjec** [comment]
picture of goliath walking through a vortex barrier

**Comment by kriskog** [comment]
Duplicate of #48712
