### ISSUE TITLE
Ethereals can't safely discharge into an APC

### ISSUE THREAD

**Issue by Ohagi-Chan** [tgstation/tgstation#48769]
## Round ID:
Austation Round unknown (round count is bugged)

## Testmerges:
#924: '[TESTMERGE] Adds DroneStation map' by MCterra10 at commit b44725bc5f

## Reproduction:
> Suck on a lightbulb for a bit
> Get overcharged
> Warning Hud says to grab intent an APC to return to safe levels
> Spam this with both Ctrl-Click and Grab Intent
> APC Window opens
> Charge doesn't appear to go down
> Chat doesn't mention I am discharging safely

**Comment by HomocidlePancakes** [comment]
You sure APC wasn’t fully charged?

**Comment by kriskog** [comment]
#48550 adds the APC grabbing, but isnt merged yet. HUD is wrong for now.

**Comment by Ohagi-Chan** [comment]
I believe the APC was fully charged.
You might *consider* warning the player properly that the APC can't be fully charged if this will be the intended behavior after #48550

**Comment by wesoda25** [comment]
if the apc is full theres a message so dont worry
