### ISSUE TITLE
Capitalize Throws Runtimes on Zero-Length Strings

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#48762]
## Round ID:
128042

## Reproduction:
say ";"

![image](https://user-images.githubusercontent.com/10467687/72230809-49529b00-358e-11ea-8cf2-dcb16f00b73f.png)

**Comment by bobbahbrown** [comment]
This was caused by https://github.com/tgstation/tgstation/pull/48304, runtime only started appearing then

**Comment by nightred** [comment]
This has been fixed in #48697
Please close.
