### ISSUE TITLE
Nightmares can destroy hardsuit helmets permanently making them unusable

### ISSUE THREAD

**Issue by Couls** [tgstation/tgstation#48770]

**Comment by Fikou** [comment]
feature

**Comment by ATH1909** [comment]
Why not just have it break the hardsuit's light, with the light being replacable by, say, using a flashlight on it (sort of like how you can repair a borg's light by using a flashlight on them while their cover is open)?

**Comment by Couls** [comment]
wyci

**Comment by nemvar** [comment]
feature. this is multiple game mechanics working together in their respectively intended ways.
