### ISSUE TITLE
Obsessed death and/or clone completely breaks their objectives

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#48799]
RoundID 128194

got obsessed, died, got cloned, then objectives showed as this: 
Objective #1: Spend -758 seconds around Frenyan Nyaners while they're alive. Success!
Objective #2: Murder Jim Johnson, Kale IO's coworker. Success!
Objective #3: Take a photo with Frenyan Nyaners while they're alive. Fail. [did take a photo]
Objective #4: Murder Frenyan Nyaners, the Roboticist. Success!
Objective #5: Spend 2 minutes around Frenyan Nyaners while they're alive. Fail.
Objective #6: Hug Frenyan Nyaners 4 times while they're alive. Fail.
Objective #7: Murder Marc Quinn, Frenyan Nyaners's coworker. Success!
Objective #8: Murder Frenyan Nyaners, the Roboticist. Success!
The Obsessed spent a total of 12 seconds being near Unknown!
The Obsessed has failed!

bruh moment if i do say so mayself

**Comment by tralezab** [comment]
god dammit

**Comment by dragomagol** [comment]
RIP cloning
