### ISSUE TITLE
Box Chem Factory is irradiated by fusion next door

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#48792]
Because someone decided to place Box chem factory wall to wall with the incinerator, literally the burn chamber in which fusion occurs within, the resulting radiation leaking from the fusion burn will contaminate objects directly on the other side of the wall. Normally, because this incinerator would be in space and sealed with reinforced walls, it wouldn't normally cause issues. On Box, standing next to the chemistry equipment in the lab will give you a nice, lethal dosage of radiation if the atmos techs are at work.

**Comment by kriskog** [comment]
The chem dispenser also shares a wall with the incinerator burn chamber, so if you somehow survive whatever explosion you triggered you may have another surprise in store :grin:

**Comment by trollbreeder** [comment]
Whoever made boxstation chemistry... please explain yourself for this blunder.

**Comment by Jalleo** [comment]
Sounds like a suitable death trap.

**Comment by rdragan** [comment]
I was actually waiting for the other box map PR to resolve before moving the chem heater from that corner, since it exploded one round and completely ruined the incinerator. This is even worse as no one has to mess up to make the chemist's round very interesting. I guess it needs a bit more work than just moving the equipment. If anyone wants to fix it go ahead, it's a bit more mapping than I feel comfortable doing right now.

**Comment by HomocidlePancakes** [comment]
Box plumbing is the dumbest shit I’ve seen in 2019 mapping.

**Comment by necromanceranne** [comment]
I get why it has to be what it is but god I fucking hate the big empty space that is plumbing and I really wish plumping pipes fit under and around shit like atmos pipes do.

**Comment by cacogen** [comment]
>Box plumbing is the dumbest shit I’ve seen in 2019 mapping.

You haven't seen what they did to genetics? Or was that this year?

**Comment by 81Denton** [comment]
yeah not gonna lie, this is pretty terrible
R-walls only have `RAD_HEAVY_INSULATION` which (if I'm reading this right) means that it only blocks 40% of all incoming radiation

![hhhhhhhhhhhhhhhhhhhhhhh](https://user-images.githubusercontent.com/32391752/72454230-c5342980-37c0-11ea-8285-939008f72277.png)

**Comment by trollbreeder** [comment]
If this station were in real life, Nanotrasen would still be a megacorporation even after all the space OSHA violation fines.

**Comment by dablusniper** [comment]
Holy fuck boxstation is cursed
