### ISSUE TITLE
Pinpointers don't show arrows. 

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#48802]
## Round ID: 
R128136

## Testmerges: 
#48583: 'Don't recheck connected clients in isbanned() (and other isbanned() dos mitigations)' by MrStonedOne at commit 23fba6671c

## Reproduction:
Buy a pinpointer from the medivend. Turn it on and select a target. The pinpointer will click on but no arrow will display.

**Comment by HomocidlePancakes** [comment]
Actually, none of the pinpointers work, except for the proximity one.

**Comment by RaveRadbury** [comment]
I think this has been sorted out
