### ISSUE TITLE
Kilo VR sleepers

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#48818]
Round ID: irrelevant
Testmerges: irrelevant
Reporting client version: 512.1488
How to reproduce: 
>dont set power up
wait for the power alarms to reach the holodeck
wham:
![Képernyőfelvétel (1)_LI](https://user-images.githubusercontent.com/54288658/72465529-a2613f80-37d7-11ea-9523-caf6bef86449.jpg)

sorry for the shitty cropping im using windows photos

**Comment by cacogen** [comment]
i use sharex

**Comment by trollbreeder** [comment]
Misnamed area. Probably because kilo was made and removed in the ye olde times of virtual reality before being remade in 2019.

**Comment by uomo91** [comment]
@issue-manager
This appears completely resolved, the room which used to contain the VR sleepers now shares area tiling and an APC with the rest of recreation.

**Comment by uomo91** [comment]
@issue-managers
This appears completely resolved, the room which used to contain the VR sleepers now shares area tiling and an APC with the rest of recreation.
