### ISSUE TITLE
Contractor Tablet Reroll doesn't Generate New Contracts and Reputation Cannot normally be Spent

### ISSUE THREAD

**Issue by Taylorkills2** [tgstation/tgstation#48810]
## Testmerges:
None

## Reproduction:
When using the Contractor Tablet, complete some contracts then use the reroll feature, if you have completed all but two of your contracts, you will still only have two contracts available to you. The last time I used the Contractor Tablet, it would generate a whole new list, allowing you to complete more contracts.

When you attempt to spend Reputation, the majority of the time you can't and the tablet fails to recognize you have any. I managed to get it to work one time and bought a contractor pinpointer. I tried restarting the tablet, dropping and picking it up, put it in pocket and out, disconnecting and reconnecting, accessing it after completing a contract and none of these seemed to fix it. It's not fully impossible to spend reputation, but I have no idea causes it to fail/respond to it.

I believe the TGUI next update caused these changes/issues with the Contractor Tablet.

**Comment by kriskog** [comment]
The reroll part is intended, you are not supposed to get more contracts just different ones.

**Comment by Taylorkills2** [comment]
If the contracts are fully RNG, then it's intended that even if you complete all the contracts getting the full bonus, you might not get the TC you invested into it?
Why would abducting corpses(for a reduced reward[or even no reward]) have been made an option if it was intended for you to just reroll the contracts available  to you?

I could be wrong, but it doesn't sound intentional to me.

**Comment by kriskog** [comment]
You're wrong.

**Comment by Taylorkills2** [comment]
I see, you intentionally changed it with your PR. That's a shame. Glad it got fixed though.

**Comment by kriskog** [comment]
Its been that way since reroll was added afaik, if you want more targets buying another kit is the intended way.

**Comment by JohnFulpWillard** [comment]
Fixed by contractor being removed
