### ISSUE TITLE
Dead person icon

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#48822]
Issue reported from  Round ID: 128260 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1488

### Wha?
Dead people have the "un-defibbable" medhud icon regardless of the time of death
### Reproduction
-die/see person die
-have a medhud on
-notice the weird skull icon on the top right corner of their sprite

**Comment by ATH1909** [comment]
Are you sure that they actually died and didn't, say, enter a regenerative coma?

**Comment by Tharcoonvagh** [comment]
Yea

**Comment by kriskog** [comment]
Defib timer is gone, everyone is now defibbable if thei

**Comment by Tharcoonvagh** [comment]
Cool
