### ISSUE TITLE
A combat hacked AI downloaded into an APC cannot be downloaded into an intellicard

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#48825]
## Round ID:
128779

## Testmerges:
#48583: 'Don't recheck connected clients in isbanned() (and other isbanned() dos mitigations)' by MrStonedOne at commit 23fba6671c 
#48569: 'FIXED: Better species environment handlers, and custom race body temperature' by nightred at commit 76577a995d 

## Reproduction:
Be an AI
Get combat upgrade
Download to a hacked APC
Try to get your friend to download you
Don't even recieve the option to refuse to be downloaded - just auto-fail
Cry when they're forced to leave you behind

**Comment by 81Denton** [comment]
https://github.com/tgstation/tgstation/blob/f44c5e8d438354f520cc975f70845ca62d4afc85/code/modules/power/apc.dm#L1125

You should be able to transfer them, looks like a bug to me. Did any of you get any error messages?

**Comment by Anonmare** [comment]
No, nothing

**Comment by dragomagol** [comment]
Still an issue 
![image](https://user-images.githubusercontent.com/66640614/99918548-81595d00-2ccc-11eb-9661-3bf093b16302.png)
(top is using the intelliCard on the APC with the shunted AI, bottom is using intelliCard on AI core)

**Comment by Sealed101** [comment]
judging by the PR(#21068) that has implemented the intellicard AI transfer, it will stop if the AI in the APC isn't dead. not quite sure how would the AI die inside an APC unless that involves killing the APC, but i'm guessing this is intended?
https://github.com/tgstation/tgstation/blob/f86a8c247e8eaab48e158c9a859738ec5f876f0d/code/modules/power/apc.dm#L866-L887
