### ISSUE TITLE
Chat box is unselected after clicking in the chat log or verb panel

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#48832]
As the title says, clicking in the chat log or verb panel (the panel with the object tab, OOC tab, etc.) will deselect your chat box.  The next key press will clear whatever you have written in the chat box and activate any hotkeys bound to the key that you just pressed.  This is not only annoying when you need to rewrite whatever it is you just said, but also risky if you, for instance, press O and get banned for asking OOC an IC question.  
This seems to have been introduced with the hotkey update, it looks like at least one issue report was closed but the problem clearly hasn't been resolved.

Steps to reproduce:
1.  Click the chat button to the right of the chat box, note that Say" is automatically added after typing anything there.
2.  Click anywhere in the chat log or verb panel (except for the verb panel tabs)
3.  Type something that starts with the letter O and watch as your message intended for IC chat is broadcast over OOC instead.
4.  Get banned (optional).

Issue reported from  Round ID: 128298 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])
Reporting client version: 513.1506

**Comment by JJRcop** [comment]
Is this a bug, or intended?

**Comment by kriskog** [comment]
@Couls see above

**Comment by Couls** [comment]
This is intended, you need to click on the chat bar to focus it again if you're not in classic mode

**Comment by Hatfish** [comment]
Why is this a feature, what on earth is it intended to accomplish besides being annoying for anyone using the original keybinds?

**Comment by Couls** [comment]
It’s a byproduct of a hack used for classic players to keep their focus on the chat bar and not the game because that’s the control scheme they’re used to
