### ISSUE TITLE
Toxin chamber igniters don't work on donut

### ISSUE THREAD

**Issue by Archanial** [tgstation/tgstation#48848]
Round ID: any

Reproduction: fill chamber with oxygen mixed with plasma, press ignition switch - nothing happens.

Other stations use normal igniters instead of wall mounted igniters.

Also toxins on donut is a mess, why is there a pipe going under the setup?

**Comment by rdragan** [comment]
Wall mounted igniters stopped working months ago and all the other maps were changed to use the normal ones. except Donut. 

As for the distro pipe... it's Donut...
