### ISSUE TITLE
Maint loot spawned an invalid item.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#48849]
![image](https://user-images.githubusercontent.com/35217076/72623028-67851600-3955-11ea-9e8c-bc28325d9427.png)
![image](https://user-images.githubusercontent.com/35217076/72623105-913e3d00-3955-11ea-95ce-b3e2cf328fd7.png)

Round: 128377.

Found it in maint, on Donut in a locker.

**Comment by trollbreeder** [comment]
Had this happen to me on meta in the abandoned theater, a generic "item" (file path obj/item)
