### ISSUE TITLE
geneticists still show up as being "blue" (the color of Medbay roles) in the suit sensor console's interface

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#48865]
Also, I think they can start the round in cloning still on some maps? That might have just been because of fulp's weirdly high number of roundstart job slots for each job, though.

**Comment by kriskog** [comment]
Latejoin job window as well

**Comment by dragomagol** [comment]
Geneticists are now purple in crew monitor and in the sci section of the latejoin menu
