### ISSUE TITLE
Bugged Agent ID Cards

### ISSUE THREAD

**Issue by Eldeen** [tgstation/tgstation#48864]
Issue reported from  Round ID: 128428 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 512.1488

Agent ID cards no longer update name changes, only title changes. Also the Agent ID can no longer be placed within a Chameleon Kit PDA.

**Comment by kriskog** [comment]
Some issue with the sanitize text proc after the 513 changes, most likely.
The name isnt setting correctly, but not badly enough that it randomizes. Thats why the PDA doesnt work.

**Comment by jlsnow301** [comment]
if this isn't already fixed, it will be after #63354
