### ISSUE TITLE
Ninjas have difficulties pertaining to the hunger system

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#48868]
## Round ID:

https://sb.atlantaned.space/rounds/128436

## Testmerges:

I have no reason to believe this is related to a test merge, but:  
https://github.com/tgstation/tgstation/pull/48583

## Reproduction:

Earlier, I was playing on Manuel and was preparing to leave because I was tired, ghosted, was spectating, and the opportunity to become a space ninja came up! I thought this was cool but I encountered an issue

**Space ninjas cannot remove their headgear easily to eat and consequently encounter issues with the hunger system.** You can't take off your mask just to eat, or somehow consume through it, and being slow as shit is a real disadvantage if the round goes on for long enough.

I do not see why a ninja who would potentially go on a long-term mission would not have the ability to do basic things such as eating

While I realize that you CAN take off the entire suit, that seems kind of strange to me, as flipping down the hood should be as simple as it is with almost every other item with a "Built in helmet", like hardsuits.

And I was VERY worried that removing my whole suit would render me unable to put it back on. The text box for taking the suit off doesn't make it clear whether or not you can put your suit back ON if you take it off (Read: Take off your suit? This will take some time and remove your powers!).  Plus there's a good chance you won't be making nice with the crew so needing to take off your whole dang suit to raid a vending machine would really suck.

Simply ignoring hunger is an option, but I really noticed the slow down, ninjas really need that woosh to survive.

What I would suggest is that 

A: Ninjas can flip down the hood of their suit thing as one would a hardsuit, maybe clarify the wording to make it less worrying with regards to your ability to take your suit off/put it back on.

B: Just make it so ninjas don't have to eat maybe? Heck man I don't know maybe they have special training, or food pills dispensed by their mask, this game is deep enough into space magic™ that I'll believe they have a way to make a person not need food for a bit.

This is my first attempt to contribute to the Github in any way, so I was hesitant to lodge this as a bug, but I really don't think this is intentional is it?  If this is inappropriate feel free to simply close it. Please be gentle.

**Comment by HomocidlePancakes** [comment]
You do realize that you have to disable your suit to take off your mask and eat, right?

**Comment by Tharcoonvagh** [comment]
https://tgstation13.org/wiki/Space_Ninja

**Comment by Taylorkills2** [comment]
Ninjas are apparently old code, that isn't quite up to date, and coders dont' generally want to touch.. Also Antag freeze.

Also, I'm pretty sure there's a bug where you can take sometimes take off your mask without disabling the suit.

Only real way around is to force chemists to make nutriment patches or make them yourself.

**Comment by HomocidlePancakes** [comment]
>You do realize that you have to disable your suit to take off your mask and eat, right?

@Taylorkills2

**Comment by Taylorkills2** [comment]
> Also, I'm pretty sure there's a bug where you can take sometimes take off your mask without **disabling the suit**.
> 
> Only real way around is to force chemists to make nutriment **patches** or make them yourself.
@HomocidlePancakes

**Comment by HomocidlePancakes** [comment]
>Also, I'm pretty sure there's a bug where you can take sometimes take off your mask without disabling the suit.

>You do realize that you have to disable your suit to take off your mask

Can you read? Not being able to take off the mask is not a bug. You have to disable the suit first.
@Taylorkills2

**Comment by improvedname** [comment]
Attach a burger to a iv drip

**Comment by GravitronBlue** [comment]
From what I gathered Space ninja nutrion was originally solved by having a suit reagent system that could store nutriment and other healing chemicals that can be injected on demand by the user.

This feature was removed as of #30102 for what I presume was the total removal of the spiderOS menu. (Which is something that I personally miss along with its extra utilies and malf AI takeover. KAMIKAZE on the other hand was horrible and anyone who figured out the the clever UI passcode system to unlock it should feel bad for abusing it, myself included.)

**Comment by kriskog** [comment]
Gonna call it an oversight, althought there are some ways around it. Like patches of nutriment.

**Comment by NanoCats** [comment]
> Gonna call it an oversight, althought there are some ways around it. Like patches of nutriment.

Thanks! Yeah, but, generally speaking it's not super practical to take off your suit, or make nutrient patches, oftentimes the crew WILL want to kill you (I was even a "Friendly" ninja once on Manuel and got ass blasted by somebody)

Ninjas have a bit of a glass cannon issue plus according to Graviton there used to be a contingency, so I'm not the only one who noticed.

> Space ninja nutrion was originally solved by having a suit reagent system that could store nutriment and other healing chemicals that can be injected on demand

I think it'd also be a good idea to make it clear that if I take my suit off for food or medical care, that I _can_ in fact put it back on later.

**Comment by Sealed101** [comment]
![изображение](https://github.com/tgstation/tgstation/assets/75863639/50f176b8-34aa-4342-a5f7-a1860ebbbcbf)
