### ISSUE TITLE
Waddling with dwarfism (and likely any sprite altering effect) will cause your sprite to do...weird things

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#48869]
Recreating this is fairly straight forward for the most simple demonstration of the bug:

Step 1: get dwarfism
Step 2: Put on the clown shoes and waddle

Your are now normal sized. If you then remove dwarfism, you become a bean pole. Not sure if the sprite is fixed by waddling again, I didn't test that.

**Comment by ATH1909** [comment]
Can you stack this?

Can you make your sprite smaller than normal by using gigantism instead of dwarfism?

**Comment by nemvar** [comment]
matrix complicated. monky don't understand.

**Comment by PKPenguin321** [comment]
Sounds like a problem with waddling resetting your transform

**Comment by spessbandit** [comment]
solution: remove waddling

**Comment by PKPenguin321** [comment]
See https://github.com/tgstation/tgstation/issues/48904#issuecomment-576423038 for a likely cause

**Comment by Tharcoonvagh** [comment]
Probably byond related
Were you on 513 19 days ago?

**Comment by Dorsisdwarf** [comment]
Waddling component absolutely fucks with your transforms.  I tried to make a giant waddling corgi but it got small every time it moved

**Comment by necromanceranne** [comment]
Pretty sure this got fixed
