### ISSUE TITLE
GitHub actions broke again lol

### ISSUE THREAD

**Issue by MCterra10** [tgstation/tgstation#48866]
`fatal: unable to access 'https://Cyberboss:***@github.com/tgstation/tgstation.git/': Port number ended with 'M'`

**Comment by trollbreeder** [comment]
lmao

**Comment by ninjanomnom** [comment]
The tgui rebuild action hasn't worked yet and is still a WIP

**Comment by MCterra10** [comment]
just remove branch protection

**Comment by ninjanomnom** [comment]
no

**Comment by ShizCalev** [comment]
still an issue?

**Comment by timothymtorres** [comment]
@ninjanomnom Is it safe to close this?
