### ISSUE TITLE
513 Object Rotation Is Broken

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#48879]

**Comment by necromanceranne** [comment]
I just want to flip, gamers.

**Comment by AnturK** [comment]
Works fine for me. More detail.

**Comment by TheChosenEvilOne** [comment]
@Paxilmaniac what OS are you on? I think I am experiencing this issue and it might be a BYOND issue

**Comment by necromanceranne** [comment]
Yeah it's a byond issue. This is happening on other servers for me that aren't 513.

**Comment by MrPerson** [comment]
Is it everything with alt-click functionality or just some things?

**Comment by Paxilmaniac** [comment]
This seems to have been solved for a while
