### ISSUE TITLE
Can't do the new stomach pump surgery on abductors with a combat vest

### ISSUE THREAD

**Issue by Glassmanner** [tgstation/tgstation#48894]
## Round ID: 128538 on Manuel

Reproduction: Try to do the stomach pump surgery on an abductor with a combat vest and you can't. The vest can't be removed.
Other surgeries like experimental organ manipulation can be performed while the vest is on.
Yes the vest is not able to be removed even by other abductors.
Not sure if this is intended.

**Comment by kriskog** [comment]
The abductor heart replacement surgery is special in this sense, and wont require you to remove clothes to speed up abductions. Normal surgeries still require you to remove the clothes.
As for the vest it is locked (to prevent crew use I assume), but can be unlocked at the middle terminal in the abductor ship.
