### ISSUE TITLE
Photos are broken

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#48899]
## Round ID:
128562

## Reproduction:
Try taking a picture, you're given a black photograph that when examined produces a white box.

**Comment by RaveRadbury** [comment]
I've now had several rounds where this occurs, it's more likely to kick in later in the round.

**Comment by RaveRadbury** [comment]
This has been reproduced several times at this point.

**Comment by optimumtact** [comment]
Checked on the server, the photos are white squares, no data.

**Comment by optimumtact** [comment]
map was pubby, if this happens again please note the map

**Comment by cacogen** [comment]
the ones that spawn in maint are like this too

**Comment by optimumtact** [comment]
suspect this is more likely an indication the server is about to run out of memory due to memory leaks over the 3 round window.

Since this doesn't usually occur on the other servers

**Comment by TheBonded** [comment]
I cannot reproduce this and assume it has been fixed

**Comment by optimumtact** [comment]
from memory this was fixed a while back and was due to the photographs missing their background image, which made them tile a lot and usually run out of memory and crash the server.
