### ISSUE TITLE
Can't set pAI laws.

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#48900]
## Round ID:
128562

## Reproduction:
Click the additional directive in the pAI menu.
For some reason it sets to "1024"
If you try to click it again to reset it nothing happens.

**Comment by kriskog** [comment]
probably some 513 sanitize text stuff.

**Comment by Names-Are-Hard** [comment]
Looks like #48512 broke it. Forgot to add the user argument.
