### ISSUE TITLE
how to become literally unclickable

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#48904]
**1. Use botany to acquire some growth serum (fly amanitas have a growth serum production trait in them and can be bought from a hacked seed vendor).
2. Drink the growth serum.
3. Buckle yourself to a (working) stasis bed.
4. Unbuckle yourself from the stasis bed.
5. Repeat steps 3-4 until you literally can't click on your sprite to click+drag yourself back onto the stasis bed again.
6. Enjoy your invisibility and your unclickability.**
7. Cry because it's now a struggle to eat food.
8. Play a plasmaman next time instead to get around that.
9. Prank sec as an invisible "ghost".
10. Cosplay as Ant-Man (when I did this on fulpstation (I performed this trick (once) on both /tg/ and fulp), I even had gaseous decomposition+liquid contents+growth serum plants to throw as "embiggening grenades", to flex my full mastery of size manipulation).
10. Wish that you had made Pickle Rick jokes when other people had asked why they could hear you but not see you.

You can also do this with the red queen drink (and perform a growing version of this trick instead of a shrinking version), although it's much more finicky to do so due to the red queen drink's chaotic nature.

Image (unfortunately, that defib's kind of in the way, but I _think_ I was on its tile (I had basically no sprite, though, so I'm just judging by the center of the image):
https://cdn.discordapp.com/attachments/326826573951008769/668747429402902538/antman.PNG

**Comment by ATH1909** [comment]
By the way, this doesn't wear off when the growth serum leaves your system (in fact, when the growth serum leaves your system, you'll shrink an extra stage beyond being pixel-less because the growth serum will have stopped metabolizing), in case that wasn't clear.

**Comment by Tharcoonvagh** [comment]
fuck label please

**Comment by Tharcoonvagh** [comment]
Does alt clicking work during this?

**Comment by HomocidlePancakes** [comment]
Won’t save you from being shot.

**Comment by ATH1909** [comment]
> Won’t save you from being shot.

Yeah, you can still get shot. Still, this is pretty busted.

**Comment by PKPenguin321** [comment]
I think I've got it, for some reason anything that rotates your character undoes any resize transforms

**Comment by ATH1909** [comment]
> I think I've got it, for some reason anything that rotates your character undoes any resize transforms

Nah, this is because of on_mob_end_metabolize() shrinking you whenever it's called and stasis beds being able to call on_mob_end_metabolize() every time you buckle yourself to them.
