### ISSUE TITLE
pubbystation brig locker is wrong type

### ISSUE THREAD

**Issue by pubby** [tgstation/tgstation#48917]
Googles_Hands on the forums says about pubbystation:

> The biohazard locker in the brig equipment room is not of the security variant, it's the same biohazard locker that normal medbay gets.

**Comment by Tharcoonvagh** [comment]
Didn't you make the map?

**Comment by cacogen** [comment]
hey I like pubby 
one of the best maps
👏🏿

**Comment by pubby** [comment]
I like you too buddy
