### ISSUE TITLE
Nanite program hub and programmer can't be deconstructed

### ISSUE THREAD

**Issue by Bokkiewokkie** [tgstation/tgstation#48928]
Issue reported from  Round ID: 128671 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 513.1507

Was working alone in a nanite lab and wanted to deconstruct the second set of nanite machines to make space for a cool lounge, until I tried to screw open the nanite program hub and hit it instead. After this i tried to dismantle it multiple times with different tools and intents just to check everything but nothing except completely smashing the machine seemed to work. (I also checked if there wasn't a disk inside or anything else affecting it.)

**Comment by XDTM** [comment]
Odd, codewise it should have the same behaviour as all machines, and screwdriver plus crowbar should deconstruct it

**Comment by MTandi** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/51245
