### ISSUE TITLE
You can Houdini strip items off yourself

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#48936]
Title, forged hrefs allow removing items off yourself as if you were somebody else.
### Tested and confirmed locally, no round ID available.

![Escapeartist](https://user-images.githubusercontent.com/17460297/72877125-0b035d00-3cad-11ea-9030-397045c9a785.png)
### Reproduction:
- Pull open the strip menu on someone
- Copy and save hrefs for slots
- Find your mob ID (Not going to list where you can find this)
- Forge strip hrefs with your mob ID
- _Perform forbidden Houdini  arts_
- Escape from shackle shoes, tinfoil hats, and beartraps in record time, all by yourself.

Can also end up pulling up the strip menu on yourself by moving while stripping an item, allowing easy item removal.

> I CAN SLIP THESE CUFFS, HAAAAAAAAAAAOOOW

**Comment by ATH1909** [comment]
> Can also end up pulling up the strip menu on yourself by moving while stripping an item, allowing easy item removal.

Could you elaborate on this a bit?

**Comment by GravitronBlue** [comment]
@ATH1909 
The UI menu for stripping items can pop up if you start removing an item and then interupt the process by moving. This menu is normally meant to show the items of others and probably not yours, but can show items you're currently wearing anyway by first using a forged href to start stripping an item off yourself and then moving before it finishes.

Presumably causes a irregular UI update since this doesn't seem to happen if it goes uninterupted and since you're the target it opens it on yourself, but I've yet to code dive to find out exactly why.
Regardless AnturK's fix should resolve these issues.
