### ISSUE TITLE
Lizardpeople take heavy damage upon leaving Cryopods, or using Rhigoxane to regulate their temperature and soothe their burns.

### ISSUE THREAD

**Issue by TheObserver-sys** [tgstation/tgstation#48943]
No round ID, because this was tested locally, on the most recent version of the code.

Attempting to use the chem Rhigoxane will result in a temporary healing of burns, followed by most of your health being burnt away due to the lingering cold debuff.  Additionally, attempting to use Cryo will restore your health to 100%, and then gradually drop it down to 60-50% health over time, the cold ticks dealing way more damage than the Cryoxadone can heal effectively.

I am uncertain if this is intentional or not, but to err on the side of caution, I figured it's worth bringing to attention.

**Early Rhigoxane Ticks**
![Screenshot_314](https://user-images.githubusercontent.com/58029438/72916775-9e21ae80-3d10-11ea-891f-8e5229e1d1cc.png)

**End of Rhigoxane and Cold Ticks**
![Screenshot_315](https://user-images.githubusercontent.com/58029438/72916771-9c57eb00-3d10-11ea-831f-6db9c76bbac0.png)

**Post Cryo Health and Reagent Scan**
![Screenshot_317](https://user-images.githubusercontent.com/58029438/72916774-9e21ae80-3d10-11ea-9e35-35dc735e1ec4.png)
**Video of damage taken from entering and exiting Cryo**
[https://www.youtube.com/watch?v=wkbSI0qCO-0](url)

**Comment by trollbreeder** [comment]
I knew that closing the lizardpeople stabilization PR would've caused even more problems. What a jooooooooooooooke

**Comment by nightred** [comment]
Interesting thanks, I will do some tests on this.

**Comment by improvedname** [comment]
Feature imagine using cold on a cold blooded lizard

**Comment by Tlaltecuhtli** [comment]
gives more in deep mechanics to lizards good pr

**Comment by HomocidlePancakes** [comment]
That’s what are the showers for.

**Comment by timothymtorres** [comment]
@SuperNovaa41 how do you feel about this?  I'm leaning towards this being intended since lizards are supposed to take damage from the cold.

**Comment by nightred** [comment]
How is this not closed yet....?
Yes lizards are cold blooded, yes this is how i intended i to work when i made that change.
