### ISSUE TITLE
You can take off the Memento Mori with your own hands while it's active after getting hit by a bolt of resurrection.

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#48950]
Issue reported from  Round ID: 128733 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

Step one, put on a Memento Mori.
Step two, get hit by a bolt of resurrection.
Step three, see that the action button is gone.
Step four, take it off and instantly die.
I also had a stand if that helps, but I don't think that was it.

**Comment by XDTM** [comment]
Activating the memento mori removes the action button, and taking it off is supposed to instantly kill you. You're not forbidden from taking it off yourself, although it's unwise.

In theory the bolt of resurrection should have no effect on the whole process.

**Comment by HomocidlePancakes** [comment]
You can take it off regardless of being hit by a resurrection bolt or using it.

**Comment by PKPenguin321** [comment]
Just don't take it off
