### ISSUE TITLE
Crate's fail to update icon on changing from open/closed

### ISSUE THREAD

**Issue by Nabski89** [tgstation/tgstation#48951]
Reproduction:

On opening and closing crates, they don't change icons. Only tested on normal crates and engineering crates. Lockers seem to be fine.

Round 128744

I complained to "Headcoder" who was online at the time, he confirmed it, and told me to put in a help ticket as he was busy playing CCR and 12 hours of lawmower sounds.

**Comment by AnturK** [comment]
Base closet doesn't call parent and crates got split into update_overlays/icon_state

**Comment by Guestratem** [comment]
This was an issue with 513 versions prior to 1508 so I would update and see if the issue remains ill also test to see if its repeatable

**Comment by Coconutwarrior97** [comment]
Seems fixed since it is no longer reproduceable, gonna close this.
