### ISSUE TITLE
Revenant goals worded misleadingly

### ISSUE THREAD

**Issue by JAremko** [tgstation/tgstation#48968]
Instead of "Absorb [targetAmount] points of essence from humans" it should be "Accumulate [targetAmount] points of essence"  (if I understand correctly how revenant works) otherwise gamers will spend it all recklessly on making crew's life miserable and wonder why they red texted after slurping like 20 nerds. :thinking:

**Comment by nianjiilical** [comment]
tbh itd be better if it actually worked as "absorbed total" so revenants arent punished for using their abilities and doing spooky shit

**Comment by JAremko** [comment]
Yeah it would be.

**Comment by HomocidlePancakes** [comment]
What’s wrong with the current wording? It says “absorb X points” and you do just that. Spending essence does not affect this at all.

**Comment by kriskog** [comment]
Yeah the goal takes the total absorbed amount into account, so the wording is correct.

**Comment by JAremko** [comment]
@kriskog  Hmm. Maybe adding some kind of an indicator towards the goal could help?  Like in percentage or something.  It would also help to see how viable it is to vore corpses. I recently  had 2 runs were I sucked like 10+ corpses in the morgue and a bunch of crew members but no luck.  It's hard to tell how far am I from the wining condition.

**Comment by kriskog** [comment]
Its all listed in the status tab :slightly_smiling_face:

**Comment by JAremko** [comment]
@kriskog Ah yes. Now I remember. It is SS13 I am playing :stuck_out_tongue_closed_eyes:
