### ISSUE TITLE
Donut AI restorer

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#48963]
Issue reported from  Round ID: 128790 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507
![tgStation Terry  EU   100% LAG FREE   New-Dedi  Explosive Monitor Echo 2020-01-23 202828](https://user-images.githubusercontent.com/54288658/73017433-1e830500-3e20-11ea-92e0-11e66990ee26.png)

you cant access the integrity restorer without destroying the r-window
OOOR the drawer

**Comment by kriskog** [comment]
@MMMiracles

**Comment by MMMiracles** [comment]
oop
