### ISSUE TITLE
Donut AI shutters

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#48962]
Issue reported from  Round ID: irrelevant (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507
The shutters are in space instead of a reinforced door
![tgStation Terry  EU   100% LAG FREE   New-Dedi  Explosive Monitor Echo 2020-01-23 201910](https://user-images.githubusercontent.com/54288658/73015796-ffcf3f00-3e1c-11ea-9bdf-ebfe1d3db598.png)

**Comment by Tharcoonvagh** [comment]
Probably @MMMiracles

**Comment by MMMiracles** [comment]
oop
