### ISSUE TITLE
Empath trait doesn't catch deafness from ear damage

### ISSUE THREAD

**Issue by Ryll-Ryll** [tgstation/tgstation#48974]
No round ID information because I caught this while code diving for unrelated stuff. In the proc for examining humans, there are extra lines that show up if the examiner has the empath trait and subject is deaf or blind (not responding to sounds/staring off into space). I've seen the staring off into space message in game before, but never the deafness one, even when inspecting someone right after they've been bombed and are assuredly deaf.

I believe the issue is that eyes confer the TRAIT_BLIND trait with the source EYE_DAMAGE when damaged enough, but TRAIT_DEAF is not conferred by getting ear damage. Since empath only checks for these traits rather than whatever ears use for tracking deafness, this information falls on deaf ears (sorry!) 

For consistency, ears should confer TRAIT_DEAF when damaged

**Comment by trollbreeder** [comment]
Explosions/bangs dont cause ear damage for some reason, they only cause scripted, arbitrary deafness and ringing.
We need a refactor of loud bangs and ear damage.
