### ISSUE TITLE
Wallet's sprite doesn't update

### ISSUE THREAD

**Issue by Archanial** [tgstation/tgstation#48987]
Issue reported from  Round ID: 128855 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 513.1503

How to reproduce: 
1. Have wallet
2. Have ID
3. Put ID in wallet
4. Wallet doesn't update

**Comment by MrPerson** [comment]
What the shit, I specifically tested this exact thing
