### ISSUE TITLE
Stammering affects punctuation.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#48983]
It shouldn’t.

**Comment by XDTM** [comment]
how does it look?

**Comment by trollbreeder** [comment]
> how does it look?

H-h-hel-l-p-p-p!-!-!
S-s-s-hi-i-t-tse-c-c-c!-!

**Comment by HomocidlePancakes** [comment]
"Hello, my name is Danika"
![image](https://user-images.githubusercontent.com/35217076/73121328-1050f800-3f8a-11ea-9ad8-30643c73deb6.png)

"In China, a new strain of coronavirus infects more than a thousand people, killing at least forty-one."

![image](https://user-images.githubusercontent.com/35217076/73121428-1a272b00-3f8b-11ea-8a93-a69589d88033.png)

Commas look scuffed. Hyphens look extremly scuffed.

**Comment by HomocidlePancakes** [comment]
@XDTM

**Comment by trollbreeder** [comment]
that ----- spam at forty-one looks really bad
and the commas too
