### ISSUE TITLE
Cameras see past the illusion of openspace

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#48992]
![image](https://user-images.githubusercontent.com/9276171/73114052-82bbcc80-3ee5-11ea-8caf-188d9b0a74f8.png)

![image](https://user-images.githubusercontent.com/9276171/73114045-6ddf3900-3ee5-11ea-9f1d-49e59676f8fe.png)

very illegal

**Comment by trollbreeder** [comment]
https://www.youtube.com/watch?v=CQclh6JKIMU
