### ISSUE TITLE
Medbay RD access

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#49008]
Issue reported from  Round ID: 128926 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507

RD doesnt have access to medbay foyer on Delta

**Comment by kriskog** [comment]
RD isnt medical personell. This is intentional.

**Comment by Tharcoonvagh** [comment]
ah well i thought that heads are given basic access to all departments
