### ISSUE TITLE
Multi-z doesnt load default ZTRAITS_STATION traits due to how config_maps is coded

### ISSUE THREAD

**Issue by Jalleo** [tgstation/tgstation#49009]
What it says on the tin.
https://github.com/tgstation/tgstation/blob/master/code/datums/map_config.dm#L106
This line is the offending code. It will not actually add it for a proper list. I dont know if it would add it for a single trait loaded from a JSON.

This means that Multi-z Debug and any other Multi-z stations wont actually connect to the others by default as it will be set to no linkage unless defined in json as you must set up in JSON for the up and down.
Changing it slightly will probably fix it.
This is by going to multiz test station and enabling the debug verbs then going to mapping and looking at all the z_level traits
![tgstationmulti_zdebug](https://user-images.githubusercontent.com/4549053/73128369-722f5300-3fc6-11ea-8a92-90ca967a2e52.PNG)

**Comment by Jalleo** [comment]
In simple talk it means that the station has no z level edge to cross to other z levels.

**Comment by Jalleo** [comment]
`#define ZTRAIT_STATION "Station"
#define ZTRAITS_STATION list(ZTRAIT_LINKAGE = CROSSLINKED, ZTRAIT_STATION = TRUE)`
I just noticed this in regards to the issue as well today. I dont think its even pointing to the right define.

**Comment by Dennok** [comment]
Here we load station
https://github.com/tgstation/tgstation/blob/d1a6e075a5a8fafcee2c38515259e9fe53446476/code/controllers/subsystem/mapping.dm#L235
Here we place ZTRAITS_STATION to traits if config have no one.
https://github.com/tgstation/tgstation/blob/d1a6e075a5a8fafcee2c38515259e9fe53446476/code/controllers/subsystem/mapping.dm#L199-L201
But Multi Z map config has it own custom traits.

You need set `{"Linkage": "Cross"},` in `"traits":` part of your Multi Z map config.

Add it to one Z lvl.
Or add it on all Z lvls if you like non-euclidean geometry.

Flare brains to your spacemens that fly of station and arrive to station again just on another level.
Oh. This already appears, just with no lvl change.


PS. I see this only like safety to not have loaded station with no station trait.
[https://github.com/tgstation/tgstation/blob/master/code/datums/map_config.dm#L106](https://github.com/tgstation/tgstation/blob/master/code/datums/map_config.dm#L106)

**Comment by SpaceManiac** [comment]
The comment right there says that it's intentional.

If you're building a multi-Z station you need to be explicit about which level(s) cross-link.
