### ISSUE TITLE
reactive teleport armor works through no teleport zones

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#49000]
## Reproduction:

1. wear teleport armor
2. get to centcom in anyway you want
3. get hit by a monki you brought in a cube
4. get to thunderdome/centcom armory/syndie base/wizard den/abductor ship/holodeck/ert room/ctf

**Comment by Fikou** [comment]
also GET

**Comment by ArcaneMusic** [comment]
Damnit man you could have made it something COOL

**Comment by HomocidlePancakes** [comment]
A chad wouldn’t’ve reported this 😎

**Comment by ATH1909** [comment]
Oh, using a monkey from a monkey cube to trigger your reactive teleport armor is a much better idea than my idea of using a cyborg to do it. I'll remember that in case nobody bothers to fix this (haven't I already reported it/mentioned it before (I know I did in my ban appeal)?).

**Comment by dragomagol** [comment]
Closed by #54645
