### ISSUE TITLE
Engineering desk Windoor is inaccessible to engineers on Metatstation.

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#49015]
## Testmerges:
Server revision compiled on:  
Master commit: cb9c710b5d00014fc9a7334101cb90231e194618 
The following pull requests are currently test merged: 
#48901: 'Remove votebox temporarily' by optimumtact at commit c14f942739 

Local commit: 624f6e8d929c42d96c19c8d4a1eeffb5ed34ac75 
Server tools version: /tg/station 13 Server v3.2.6.2 

No reason to think this is the result of a test merge though

## Reproduction:

![image](https://user-images.githubusercontent.com/14065903/73126492-45a51800-3f81-11ea-90f1-3ad152bce7bf.png)
(See attached screenshot, the windoor to the left of this player character cannot be opened by somebody with engineering access, I believe I could in the past, besides it's in the ENGINEERING foyer so. 

PLEASE NOTE: I WAS DIRECTED HERE FROM THE DISCORD. I am sorry if this isn't the right place.

**Comment by kriskog** [comment]
Someone added atmos access to this a while ago, they may have used the wrong access list so you now need both.

**Comment by CRITAWAKETS** [comment]
The simple solution would just be to make it construction access.

**Comment by Jalleo** [comment]
That would cause certain people to meta and ask for construction access as a easy way to get inside the lobby at least.

**Comment by CRITAWAKETS** [comment]
Jalleo, the door to the lobby is construction access aswell.

**Comment by Jalleo** [comment]
I wasn't aware of that.
