### ISSUE TITLE
Plumbing Constructor Chemical Grinders Broken

### ISSUE THREAD

**Issue by halitosisman** [tgstation/tgstation#49026]
Issue reported from  Round ID: 128977 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

The setup is shown. When plants go in the disposals chute their chems should enter the plumbing system. Currently the plant just disappears. No chems appear in the plumbing network and no plants leave the disposals system.

![temp](https://user-images.githubusercontent.com/35907379/73141016-4a370280-404d-11ea-80c3-3dd0f2d4dee1.png)

**Comment by Tlaltecuhtli** [comment]
did the plant have nutriment gene 
https://github.com/tgstation/tgstation/blob/8358169b8e5a37508ae4f15ac1db007ef14a4a88/code/modules/hydroponics/grown.dm#L147-L153

or maybe plants use weird shit and need an 
	if(I.reagents)
I.reagents.trans_to(src, I.reagents.total_volume, transfered_by = src) 
at the end

**Comment by halitosisman** [comment]
At least some of the plants I tested did.

**Comment by Krysonism** [comment]
Sometimes you have to feed the grinder from the back.

**Comment by halitosisman** [comment]
By wrong side do you mean the direction of the trunk feeding it?
