### ISSUE TITLE
Holodeck Firing Range target stake doesn't work

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#49025]
Issue reported from  Round ID: 128971 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

To reproduce: 
Holodeck, turn on the firing range
go to the control panel
do as the instructions said
nothing happens?
![Képernyőfelvétel (10)](https://user-images.githubusercontent.com/54288658/73140044-c5f87580-4074-11ea-8aca-df05815ea3c1.png)

**Comment by cacogen** [comment]
that thing is so old

**Comment by Tharcoonvagh** [comment]
Weirdly enough it works now
