### ISSUE TITLE
Inserting items into vending machines often makes the item unable to be retrieved by players, and deletes its contents

### ISSUE THREAD

**Issue by spessbandit** [tgstation/tgstation#49023]
## Reproduction:

Insert an item into a vending machine that is compatible (i.e. the base item is something that is normally sold by it). The player who reported this did so with a full sec duffle bag and the SecDrobe. There is now no way to retrieve your item. 

Not only that, if you VV the machine, you will see that there is a copy of that item in the machine, but it has no contents, if it was originally a bag with contents. This is probably because only the name is checked in the code.

Almost certainly related to this https://github.com/tgstation/tgstation/blob/7bef84f009baaecdb58f1d18f8160f8ba5c9933e/code/modules/vending/_vending.dm#L561

**Comment by nemvar** [comment]
Pretty sure nuke disk can still be moved across z-levels by loading it into a vendor.

**Comment by Tharcoonvagh** [comment]
Wow

**Comment by timothymtorres** [comment]
We probably need to check if the object is a container and if it is then only allow it to be inserted if it’s empty

**Comment by timothymtorres** [comment]
> Pretty sure nuke disk can still be moved across z-levels by loading it into a vendor.

You are correct #56535 We should probably add checks to prevent station loving objects (phylactery included) from being inserted into the vendor.

**Comment by timothymtorres** [comment]
![dreamseeker_ZGQehatu50](https://user-images.githubusercontent.com/5195984/152704154-5000c962-c68c-40c5-be7d-d3e7e7f301d8.png)

I tested this just now with both a custom vending machine and the sec drobe.  Putting items into containers and then selling them via custom vending machine still has the items inside the containers.  However taking a container like the sec dufflebag, putting items inside it, and then reinserting it into the SecDrobe causes it to not appear in the menu anywhere.  Nor does the item quantity update properly.  So if there were 3 total sec dufflebags, you take one out and put stuff into it, then put it back into the SecDrobe there will be only 2 total sec dufflebags.  It's very strange behavior.

**Comment by Donpedrito** [comment]
Fixed by #64314

**Comment by Donpedrito** [comment]
Okay, Tested/Reproduced from 2 days ago gave me some pause, but I can personally confirm from ingame experience that this is fixed, so I'm closing it
