### ISSUE TITLE
Agent ID name change doesn't work

### ISSUE THREAD

**Issue by Archanial** [tgstation/tgstation#49022]
Issue reported from  Round ID: 128974 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 513.1503

Basically the title. It changes the job but doesn't change the name on the ID.

**Comment by Tharcoonvagh** [comment]
Dupe

**Comment by MrPerson** [comment]
I specifically tested this too wtf Now I'm getting pissed
