### ISSUE TITLE
Remove cloning disks and add genetics sequence analyzer to sci tech-fab

### ISSUE THREAD

**Issue by Something1sWrong** [tgstation/tgstation#49020]
Issue reported from  Round ID: 128962 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507

you can only get spare genetic sequence analyzers from medbay which is cringe
Also even though cloning is removed there are still cloning data disks

**Comment by trollbreeder** [comment]
When you code it!

**Comment by kriskog** [comment]
Cloning disks are rebranded to genetic disks in the (updated) PR, they can still store your identity in genetics. The other thing is already PR'd by someone. #48957
