### ISSUE TITLE
Non-malf AI being able to intermittently look into maint tunnels

### ISSUE THREAD

**Issue by ThePainkiller** [tgstation/tgstation#49049]
As the title says, I latejoined as AI on a round (my core spawned on top of another dead AI's core), and for brief moments I could stare into maint tunnels despite no borgs, shells, bots, nor cameras were present there.

[Screenshot of bug taking effect](https://prnt.sc/qtqq9k)

![image](https://user-images.githubusercontent.com/1294508/73222669-90ba5900-4142-11ea-9faa-7fa70c4a45f4.png)

[Screenshot of the bug subsiding on the very same round after jumping to another camera](https://prnt.sc/qtqrgu)

![image](https://user-images.githubusercontent.com/1294508/73222687-99ab2a80-4142-11ea-818e-f2ab2a6a20b4.png)

Issue reported from  Round ID: 129047 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1507 (Beta)

**Comment by Tharcoonvagh** [comment]
Dupe

**Comment by Taylorkills2** [comment]
Damn I should have known it was glitched, I was a posibrain turned into an AI, I could see everywhere on the z-level. Regardless of cameras. I even switched to a borg shell, shell couldn't see anywhere without cameras, but I could switch back to my core and have xray vision everywhere.
I was built in maint, an area without cameras. That might have something to do with it.

**Comment by HomocidlePancakes** [comment]
Wew. That’s an old one. Seems to be happening at random with no particular triggers and pretty often at that, regardless of you being a built, roundstart or latejoin AI.

**Comment by ShizCalev** [comment]
duplicate.
