### ISSUE TITLE
you can lag the server with the library visitor console

### ISSUE THREAD

**Issue by loserXD** [tgstation/tgstation#49041]
## Testmerges:
#48668 at fde6a50633
#48901 at c14f942739

## Reproduction:
1. goto the library
2. search for something common in the library like a space at the visitor console
3. click the search button multiple times

the only fix I can think of is limiting the amount of results to 30 or so

**Comment by Tharcoonvagh** [comment]
Dupe

**Comment by GravitronBlue** [comment]
#45284

**Comment by loserXD** [comment]
bruh there was an issue for this open for ages and nobody did anything??
