### ISSUE TITLE
Chemical Grinder works weirdly

### ISSUE THREAD

**Issue by HiKewne** [tgstation/tgstation#49068]
Issue reported from  Round ID: 129143 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 513.1508

Okay so i've encountered some problems with the chemical grinder, listed here:

>The "accessibility tile"  (the one that lets you get on top of the machine so you can drop the items that are going to be grinded) is, theoretically, on the opposite way the plumbing duct in the machine is pointing. Sometimes this changes depending how its oriented when wrenched down (ie when the duct is facing east, the "accessibility tile" is right next to the tube. When its facing south, the tile is on the opposite end of the duct.

>It won't grind or turn into chemicals the contents of plants that have been modified to have chemicals they usually don't (Ie: Wheat with 20% modified nutriment will be 'grinded' and will yield the equivalent to potency. Wheat with 15% omnizine, or 5% earthsblood won't).

**Comment by Tlaltecuhtli** [comment]
already prd

**Comment by HiKewne** [comment]
> already prd

Aight my bad
