### ISSUE TITLE
Unable to Mutate Cabbage into Replica Pods

### ISSUE THREAD

**Issue by SkeletalElite** [tgstation/tgstation#49073]
## Round ID:
Happened on a couple of rounds

## Testmerges:

#48668
#49065

## Reproduction: 
Pour hundreds and hundreds of units of mutagen on a cabbage.
Observe as nothing happens.
Pretty sure the cloning PR only removed them from the vendor and reduced the crate to 1 seed, but it did touch them so maybe something went wrong there.
Also kriskog mentioned on the PR that you should still be able to mutate the cabbages which leads me to believe this is unintentional

**Comment by kriskog** [comment]
The mutation hasnt been removed and I am able to mutate cabbages into replica pods on the servers with the testmerge. Make sure you are adding 5u mutagen to the tray when attempting to mutate the plant.

**Comment by SkeletalElite** [comment]
> The mutation hasnt been removed and I am able to mutate cabbages into replica pods on the servers with the testmerge. Make sure you are adding 5u mutagen to the tray when attempting to mutate the plant.

I'll give it a go again today, maybe I got really unlucky but on bagil I had tried to mutate cabages with a bucket (was 20 units at a time) and I ended using ~600 units of mutagen to no effect.

**Comment by kriskog** [comment]
Allright, let us know if this continues to be an issue and preferably a round ID and we can reopen.

**Comment by SkeletalElite** [comment]
@kriskog https://scrubby.melonmesa.com/round/129146/files?file=attack.txt
There's one of the rounds log files. Possible I was just unlucky I suppose but if you filter by cabbage you'll see that cabbage had an insane amount of mutagen poured on it.

**Comment by adamkad1** [comment]
20 units at a time is waaay excessive
