### ISSUE TITLE
Exotic Seeds Crate is missing seeds.

### ISSUE THREAD

**Issue by Fishimun** [tgstation/tgstation#49077]
Issue reported from  Round ID: 129215 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507

Exotic Seeds Crate description says fourteen seeds including 3 replica pod seeds and 2 strange seeds. but you only get 1 replica pod seed from the crate so the crate is missing 2 seeds from 14.

**Comment by SkeletalElite** [comment]
#48668 
changes this but doesn't change the description of the crate I guess

**Comment by kriskog** [comment]
Yeah, wrong description due to the testmerge of #48668. Fixed in the main PR.
