### ISSUE TITLE
Bodybags inside morgue trays are inescapable prisons

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#49080]
Place yourself a body bag

Have bodybag put in a morgue tray

Close morgue tray

The player inside is now unable to resist out or move to open the bag and tray

Issue reported from  Round ID: 129223 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

**Comment by ATH1909** [comment]
Yep, this is a known issue.

**Comment by Tlaltecuhtli** [comment]
dont get buried alive next time

**Comment by dragomagol** [comment]
Duplicate of #31656
