### ISSUE TITLE
Sanity is broken vol.3: never decreases if over 125

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#49091]
1. Set sanity to >125
2. Get mood to something very low (set nutrition to 0 for quick testing)
3. Sanity doesn't decrease, stay sane forever

Expected behavior: sanity evens out at 100 if at 0 mood

**Comment by HomocidlePancakes** [comment]
Fuck mood.

**Comment by Mickyan** [comment]
this isn't your blog I dont care

**Comment by ShizCalev** [comment]
relevant proc:
https://github.com/tgstation/tgstation/blob/030303d95207333090b0d8c85c1b9fa353abf2ec/code/datums/components/mood.dm#L194-L233

**Comment by kriskog** [comment]
Didnt we already read this chapter?
