### ISSUE TITLE
Floorbots can be used for unlimited metal

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49119]
Issue reported from  Round ID: 129394 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1508

1. Lock a couple of floorbots in a room with no tiles
2. They slowly replace the tiles
3. Pry the tiles up with a crowbar and use them for metal

In addition to this, for some reason tiles in this room (the small section of maintenance beneath robotics on MetaStation) during this round became bugged so that they could be pried up endlessly, creating infinite tiles and potentially infinite metal. The tile never disappeared. I don't know how to reproduce it outside of what I've described here.

**Comment by Jalleo** [comment]
Its been reported in another issue report on the latter part.

**Comment by cacogen** [comment]
Should I close this?

**Comment by trollbreeder** [comment]
![image](https://user-images.githubusercontent.com/25937686/73595987-67bd0e00-451e-11ea-989f-22913666a7e9.png)

**Comment by PKPenguin321** [comment]
https://github.com/tgstation/tgstation/issues/49153 has better reproduction steps
