### ISSUE TITLE
killing a morph doesn't reset its description

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#49114]
Round ID: 5584
Server: Fulpstation

<img width="176" alt="morph bug" src="https://user-images.githubusercontent.com/42606352/73589283-d6a45380-4499-11ea-93fb-ce8e12a76da6.PNG">

**Comment by ShizCalev** [comment]
Unable to reproduce on master.

**Comment by HomocidlePancakes** [comment]
@ShizCalev 
Transform in to an item, die while transformed.
