### ISSUE TITLE
Caks, and some other simple mobs (probably) can't un-drag items

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#49110]
## Testmerges:

https://github.com/tgstation/tgstation/pull/48668
https://github.com/tgstation/tgstation/pull/49065

## Reproduction:

When made into a Cak by a surgeon/chef/admin, if I drag an item, the health doll and Stop Dragging button appear in the same spot. 

This causes me to be unable to stop dragging the item. 

![image](https://user-images.githubusercontent.com/14065903/73582023-68d83780-4459-11ea-8648-3523c73d9d92.png)

This issue may affect other Simple mobs.

**Comment by ATH1909** [comment]
You can stop dragging it if you go into your IC menu, and I think there's a hotkey to stop pulling something as well.

Still, someone should make a PR to fix this.
