### ISSUE TITLE
Ejecting a beaker from an All-In-One Grinder as a cyborg causes it to disappear

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49117]
Issue reported from  Round ID: 129394 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1508

**Comment by kriskog** [comment]
Is this with alt click or the radial button? Both?

**Comment by kriskog** [comment]
Nevermind I found the issue.
