### ISSUE TITLE
AI upload counts as maintenance in radstorm - Boxstation

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#49121]
Issue reported from  Round ID: 129417 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

The AI upload below the bridge seems to count as a "maintenance" area during a radiation storm. Im not sure if this is intentional given no other large rooms count.

I've only checked this on BoxStation so far.

See picture:
https://i.imgur.com/5DFKXJ4.png

**Comment by trollbreeder** [comment]
Radiation storm protected areas:
https://github.com/tgstation/tgstation/blob/4fbf5b8118bc22496cfb6297d63ec65e5245169d/code/datums/weather/weather_types/radiation_storm.dm#L20-L21
Seems intentional.

**Comment by HomocidlePancakes** [comment]
All AI uploads on all maps are radproof

**Comment by ShizCalev** [comment]
Intended.
