### ISSUE TITLE
Angry Stickmen and Mjoll the Creative aren't aggressive

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#49134]
Issue reported from  Round ID: 129443 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507

They refused to attack me, so i just slaughtered em all

**Comment by Michael-Ashfield** [comment]
I've seen something similar before while as a traitor, were you also a traitor at the time?
