### ISSUE TITLE
You can break a diamond table with a glass spear

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49145]
Issue reported from  Round ID: 129466 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1508

maybe add a hardness scale to minerals that affects damage dealt and received

**Comment by Tharcoonvagh** [comment]
Intended, spears defy the laws of physics

**Comment by PKPenguin321** [comment]
Really doesn't sound like a bug
