### ISSUE TITLE
Plasmaman Contractor Target

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#49149]
Issue reported from  Round ID: 129470 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

When extracting a plasmaman as a contracting target, the plasmaman will arrive at the holding facility with no plasmaman enviromental suit. They will die. Let them keep the suit or have a special plasmaman room, or even just a shower.

**Comment by Akrilla** [comment]
Was fairly sure I added important for life fixes for this sort of thing, I'll try fix at some point

**Comment by dragomagol** [comment]
Still an issue

**Comment by EricZilla** [comment]
Two years later the skelemen still burn 😔

**Comment by JohnFulpWillard** [comment]
Fixed by contractor being removed
