### ISSUE TITLE
Smite and Flesh to Stone hand icons are invisible

### ISSUE THREAD

**Issue by trollbreeder** [tgstation/tgstation#49156]
## Reproduction:
Step 1: Be a wizard.
Step 2: Buy either Smite or Flesh to Stone with your spellbook.
Step 3: Activate either spell so that it gets channeled into your hand.
Step 4: Right click the hand with the spell. It's there, but invisible!
Step 5: Examine the spell. The examine icon is a syndicate balloon.

## The issue:
#45791 caused this by replacing the icon var to icons/obj/balloons.dmi. Balloons used to be in the icon file icons/obj/items_and_weapons.dmi, which is where the icons for the smite and stone hands currently are.
By setting the icon's file for the base touch spell item to balloons.dmi without setting the icon for ei nath and staun ei, the icon is invisible because there is no such icon_state called "disintegrate" or "fleshtostone" in balloons.dmi.

## Pictures and related code:
![image](https://user-images.githubusercontent.com/25937686/73611172-5ab42380-45df-11ea-85bb-5f7b34d904da.png)
Wizard with smite active, smite in his hand, examine text 

https://github.com/tgstation/tgstation/blob/10c6208c07afec369f338e65f00f467f9d75faeb/code/modules/spells/spell_types/godhand.dm#L7
Icon is set to balloons.dmi
https://github.com/tgstation/tgstation/blob/10c6208c07afec369f338e65f00f467f9d75faeb/code/modules/spells/spell_types/godhand.dm#L52-L53
But icon isn't set to items_and_weapons.dmi here, which calls a nonexistant icon_state.

**Comment by fengzhongbw** [comment]
I think there is something wrong.
