### ISSUE TITLE
"your MMI was unable to receive your mind"

### ISSUE THREAD

**Issue by Naevii** [tgstation/tgstation#49155]
So i was playing as the borg, and i suddenly got a message on chat "Your headlamp has been deactivated.
Oops! Something went very wrong, your MMI was unable to receive your mind. You have been ghosted. Please make a bug report so we can fix this bug."

and i blew up. 

the moment it happened i entered recharger. i also have to say that i was not listed as a player at the end of the round summary,

**Comment by PKPenguin321** [comment]
Round ID probably would have been useful

**Comment by zxaber** [comment]
My guess is someone triggered your detonation. Were you emagged at the time (or hacked by a malf AI or given an illegal upgrade)?

>i also have to say that i was not listed as a player at the end of the round summary,

Only borgs still in one piece will show on the round end screen. Deconstructed or blown borgs do not show up.

**Comment by ShizCalev** [comment]
looks to me like it was a self_destruct while emagged.
