### ISSUE TITLE
you can late join as a prisoner.

### ISSUE THREAD

**Issue by itseasytosee** [tgstation/tgstation#49160]
Easy to reproduce.
Who tested this?

**Comment by kriskog** [comment]
> Who tested this?

You did

**Comment by itseasytosee** [comment]
Correct 1000 points to kriskog

**Comment by trollbreeder** [comment]
YABBADABADOO
I LATEJOINED AS PRISONER
AND NOW IM LEADING SEC INTO A WILD GOOSE CHASE FOR MY ASS EVEN THOUGH IM AN ORANGE ASSISTANT AT THIS POINT

**Comment by Tharcoonvagh** [comment]
waht

**Comment by Tlaltecuhtli** [comment]
feature

**Comment by RaveRadbury** [comment]
I tested on local and was unable to join a round as prisoner.

When I requested a testmerge the PR got merged.

**Comment by Qbopper** [comment]
> When I requested a testmerge the PR got merged.

seriously??

**Comment by Shadowflame909** [comment]
bug is back on tramstation

Round ID: 186085
