### ISSUE TITLE
Health Doll Hud Overlaps the Pulling one

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#49163]
Issue reported from  Round ID: 129511 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1507

@tralezab 
![image](https://user-images.githubusercontent.com/37246588/73617101-4d9c3200-45e9-11ea-80ab-435862c98e2f.png)

**Comment by nemvar** [comment]
Dupe https://github.com/tgstation/tgstation/issues/49110
Also fix is already PRed

**Comment by wesoda25** [comment]
guess im stupid then
