### ISSUE TITLE
Donutstation: Harry Potter and the Paranormal Light Fixture of Experimentation

### ISSUE THREAD

**Issue by trollbreeder** [tgstation/tgstation#49174]
## Testmerges:

48668: 'Completely removes cloning' by kriskog at commit fde6a50633
49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:

Step 1: Be a scientist.
Step 2: Run to the experimentor/bepis room.
Step 3: Go into the room with the reinforced floor.
Step 4: Examine the light fixture. Something's not right.

## The issue:
The light fixture is detached from the wall. It's floating.
![image](https://user-images.githubusercontent.com/25937686/73664018-f35da880-469e-11ea-8ebf-b4eac676c8a6.png)

**Comment by Fikou** [comment]
nanotrasen experimented so much in that room that they created a floating light
feature

**Comment by kriskog** [comment]
Its roof mounted you nerds

**Comment by XDTM** [comment]
What's a roof

**Comment by trollbreeder** [comment]
> Its roof mounted you nerds

Where's the ceiling? I looked up and my eyes burned off.
