### ISSUE TITLE
Ai examine runtimes

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#49189]
No round id, Testmerges irrelevant
-be ai
-pan your camera to anywhere not near your core
-right click and examine
-Notice the scary text in the command bar

**Comment by Ewwmewgewd** [comment]
Couldn't reproduce this. You can't right-click examine as AI.

**Comment by SuperNovaa41** [comment]
Probably not an issue anymore

**Comment by timothymtorres** [comment]
I searched through closed and open issues to see if I could find matching issues and nothing.  I think this is safe to close now.
