### ISSUE TITLE
Attention, Mutiny Has Been Quelled, Alert can repeat infinitely

### ISSUE THREAD

**Issue by Taylorkills2** [tgstation/tgstation#49181]
## Testmerges:
#48668: 'Completely removes cloning' by kriskog at commit fde6a50633
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction: I don't honestly know how to, however the Head Revolutionist was killed far earlier into the round before the alert prompted. 
After around another 20 minutes after the head revolutionist died, we got the mutiny quelled message and Attention sound effect, and it kept repeating every 2/3 seconds until the round ended.

**Comment by SkeletalElite** [comment]
ATTENTION

**Comment by SkeletalElite** [comment]
`[2020-02-04 03:52:39.763] runtime error: Cannot execute null.getorganslot().
 - proc name: on removal (/datum/antagonist/rev/head/on_removal)
 -   source file: revolution.dm,161
 -   usr: null
 -   src: Head Revolutionary (/datum/antagonist/rev/head)
 -   call stack:
 - Head Revolutionary (/datum/antagonist/rev/head): on removal()
 - Kashindra Kalcronk (/datum/mind): remove antag datum(/datum/antagonist/rev/head (/datum/antagonist/rev/head))
 - Head Revolutionary (/datum/antagonist/rev/head): remove revolutionary(0, "gamemode")
 - Head Revolutionary (/datum/antagonist/rev/head): remove revolutionary(0, "gamemode")
 - Revolution (/datum/dynamic_ruleset/roundstart/revs): rule process()
 - dynamic mode (/datum/game_mode/dynamic): process(2)
 - Ticker (/datum/controller/subsystem/ticker): fire(0)
 - Ticker (/datum/controller/subsystem/ticker): ignite(0)
 - Master (/datum/controller/master): RunQueue()
 - Master (/datum/controller/master): Loop()
 - Master (/datum/controller/master): StartProcessing(0)
 - `

`[2020-02-04 03:53:03.055] runtime error: Cannot execute null.getorganslot().
 - proc name: on removal (/datum/antagonist/rev/head/on_removal)
 -   source file: revolution.dm,161
 -   usr: null
 -   src: Head Revolutionary (/datum/antagonist/rev/head)
 -   call stack:
 - Head Revolutionary (/datum/antagonist/rev/head): on removal()
 - Kashindra Kalcronk (/datum/mind): remove antag datum(/datum/antagonist/rev/head (/datum/antagonist/rev/head))
 - Head Revolutionary (/datum/antagonist/rev/head): remove revolutionary(0, "gamemode")
 - Head Revolutionary (/datum/antagonist/rev/head): remove revolutionary(0, "gamemode")
 - Revolution (/datum/dynamic_ruleset/roundstart/revs): rule process()
 - dynamic mode (/datum/game_mode/dynamic): process(2)
 - Ticker (/datum/controller/subsystem/ticker): fire(0)
 - Ticker (/datum/controller/subsystem/ticker): ignite(0)
 - Master (/datum/controller/master): RunQueue()
 - Master (/datum/controller/master): Loop()
 - Master (/datum/controller/master): StartProcessing(0)`

Might be related to these runtimes

**Comment by kriskog** [comment]
A headrev body was destroyed, preventing the gamemode from setting it unreviveable but never properly ending the gamemode when they lost.

**Comment by Taylorkills2** [comment]
To be fair, it was only there brain that was destroyed.
