### ISSUE TITLE
decon multi-z map floor, give true space instead of open space

### ISSUE THREAD

**Issue by minrun** [tgstation/tgstation#49187]
## Round ID:
personal server, downloaded as zip on 2/4/2020 at 12:08

## Reproduction:
Go to multi-Z debug map (only tested on this one)
grab a normal/admin RCD
go up a Z level
deconstruct ORIGINAL flooring => turf turns into "true" space

construct new floor
decon NEW floor => turf turns into open space

**Comment by Dennok** [comment]
construct new floor over open space
In this case work baseturf saving.

Seems like multi-Z debug map config dont have baseturf set to "open space"
