### ISSUE TITLE
Wand of Nothing conflicts with Pacifism

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#49199]
## Reproduction:
Spawn in on Donut as a pacifist and pick up the wand of nothing from the theater. You can fire it at yourself but if you try to fire it at anything else you are informed that the wand is _"lethally chambered"_. It's literally a wand that fires a projectile that does nothing.

**Comment by XDTM** [comment]
could give someone a heart attack from magic ptsd

**Comment by Mickyan** [comment]
This is easily fixed by adding `harmful = FALSE` to it but since the wand of nothing is the parent of all other wands, its children also need it overridden to TRUE where applicable

**Comment by XDTM** [comment]
this is why basetypes should be left as template-only

**Comment by Mickyan** [comment]
Yeah making a subtype for the fake wand instead of using the basetype would be more efficient

**Comment by cacogen** [comment]
maybe it kills mimes
