### ISSUE TITLE
You can't sing over comms.

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#49198]
## Reproduction:
Try to sing over comms
If you put the ; first it will print over comms with % as a part of the message
If you put the % first you will sing locally with ; as a part of the lyric

I know that we can stack comms and languages, I haven't checked for trying to sing with a language codec. Whatever is checking for comms and singing is conflicting.

**Comment by Tharcoonvagh** [comment]
You can sing over comms with an intercom

**Comment by cacogen** [comment]
You can get around it with an intercom, a station bounced radio or turning on the microphone on your headset, but that doesn't stop this from being an oversight.
