### ISSUE TITLE
can't take down the elephant graveyard's bone spears with an empty hand

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#49202]
If you click on one of the bone spears in the elephant graveyard with an empty hand, the game will tell you that you took the spear down, but the spear will remain in place (and not drop itself). You can try to take it down repeatedly, and it'll remain up. I believe that this is because the elephant graveyard's "head on spear except without the head" structures spawn with no actual bone spears in them.

**Comment by ShizCalev** [comment]
Fixed it.
