### ISSUE TITLE
bartender dispenser icon bug

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#49206]
it doenst update the icon on removal of beaker (both manually and by shortcut) and when you add a new beaker it adds a new one
![a](https://i.imgur.com/vUkSaiI.png)

**Comment by Tharcoonvagh** [comment]
Which one

**Comment by cacogen** [comment]
it would appear both that light placement is sinful even if technically on a wall

**Comment by Dennok** [comment]
This only for drink dispenser?
Chem dispenser dont have this problem?
