### ISSUE TITLE
“You have failed to qualify for any job you desired. “

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#49207]
Round: 129631

Had "Get random job if preferences unavailable" in prefs. Was kicked to lobby because there were no eligeble jobs for me, even though letejoin menu showed that there were still plenty of slots.

**Comment by kriskog** [comment]
More slots open up after roundstart, so open slots there doesnt necessarily indicate an issue. You should have been put in as an assistant though, unless you are assistant banned? Any other job bans?

**Comment by HomocidlePancakes** [comment]
I have a secban, but that's it. No assistant ban.

**Comment by Fikou** [comment]
theres bonus cargo tech, cook, botanist, janitor, atmos tech, doc, scientist slots after the round starts

**Comment by kriskog** [comment]
Sec ban might be the cause of it, worth looking at for whoever picks this up.

**Comment by HomocidlePancakes** [comment]
Round: 129681
Same thing again. Happened to some other lads too judging from OOC complaining.

![image](https://user-images.githubusercontent.com/35217076/73871256-97da1900-485e-11ea-95db-b526f6fcd9c8.png) 

Fairly certain there are always at least 2 janitors slots minimal, but I may be mistaken.

**Comment by CitrusGender** [comment]
Same thing happen to me but in real life 😢

**Comment by Fikou** [comment]
not a bug
