### ISSUE TITLE
Sol Dry cans don't have a crushed sprite.

### ISSUE THREAD

**Issue by Donpedrito** [tgstation/tgstation#49212]
## Round ID:
129692

## Testmerges:
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:
1. Buy Sol Dry from a Booze-o-Mat or drink vendor
2. Drink it all
3. On harm intent, hit yourself on the head with it
4. The crushed can is invisible, but can be picked up by right clicking.

**Comment by OnlineGirlfriend** [comment]
Whoops. Thanks for bringing this to my attention.
