### ISSUE TITLE
0g movement

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#49221]
No round id, Testmerges irrelevant
Not sure if this is a dupe or not, so here we go
For some reason, in zero g your speed is affected by the damage you have, even if you use a jetpack
Probably not intended as it defies the laws of physics

**Comment by Jalleo** [comment]
Its been changed to take in slowdown affects so this is likely a consequence of that.

**Comment by Tharcoonvagh** [comment]
Could you link the pr?

**Comment by HomocidlePancakes** [comment]
Dupe. tl;dr anything that should remove slowdown doesn’t work.

**Comment by HomocidlePancakes** [comment]
@Jalleo Wrong.

**Comment by bobbahbrown** [comment]
this is not a bug

**Comment by bobbahbrown** [comment]
this is possibly a bug

**Comment by PKPenguin321** [comment]
This is an old dupe, can't remember the issue number atm but I'm like 99% sure

**Comment by Tharcoonvagh** [comment]
Aight
