### ISSUE TITLE
update_ping error spam

### ISSUE THREAD

**Issue by Dennok** [tgstation/tgstation#49226]
Round ID: 129547
BYOND Version: 513.1507
Server revision compiled on: 
Master commit: fcc925b79bc8af19451e2bf7f3aa765f3e3cd2a5
The following pull requests are currently test merged:
#48668: 'Completely removes cloning' by kriskog at commit fde6a50633
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

Local commit: 3ae824415efd10890de2b2c6d5d01073febed688

On long rounds starts spam of

> Sorry, the following is not valid: 2.18407e
> usage: .update_ping number

message

Seems like `update_ping` error on large time

**Comment by Couls** [comment]
steps to reproduce please, where does this message get spammed?

**Comment by Dennok** [comment]
seems like after one dey of uptime

**Comment by Couls** [comment]
that doesn't answer any of my questions

**Comment by Dennok** [comment]
Join to Sybil 2 after 1-2 days of uptime and see spam of this messages.
You need have no goon chat. Old chat that appears on loading on login.
Or you can use fix chat button and disable anvanced chat.
