### ISSUE TITLE
Explosions damage atoms inside a container with PREVENT_CONTENTS_EXPLOSION_1 set while inside another atom.

### ISSUE THREAD

**Issue by bloons3** [tgstation/tgstation#49232]
Unconfigured Borgs that Suicide via the Robotics Console when locked inside of a security locker taken from Cargo in the middle of the Pubby Station Command Hallway do not produce an MMI. Instead, they produce a brain.

**Comment by Tharcoonvagh** [comment]
Oh god
Please change the title

**Comment by Fikou** [comment]
Unconfigured Borgs that Suicide via the Robotics Console when locked inside of a security locker taken from Cargo in the middle of the Pubby Station Command Hallway do not produce an MMI. Instead, they produce a brain.

**Comment by trollbreeder** [comment]
Is this the birth of a new copypasta?

**Comment by XDTM** [comment]
I want a Mad Libs of this

**Comment by ShizCalev** [comment]
Works fine here.

Did the borg have a mind?

**Comment by bloons3** [comment]
I was in the borg

**Comment by trollbreeder** [comment]
Were there any glass shards or metal sheets on the floor?

**Comment by bloons3** [comment]
There were miscellaneous items inside of the locker, though none were
present on the floor when the locker was dragged over it and placed into
position.

**Comment by trollbreeder** [comment]
Broken glass shards may indicate the MMI was damaged enough to break, which releases the brain inside.

**Comment by bloons3** [comment]
It would be interesting to see if the locker contained the explosion enough
to force all damage to MMI.

Iirc, nothing outside of the locker was damaged.

**Comment by ShizCalev** [comment]
@bloons3 The locker didn't contain the explosion in my test.

**Comment by ShizCalev** [comment]
May have been due to lag, ie the explosion was generated, but `stoplag()` delayed it from processing until after the mmi was already ejected, and the explosion damaged the locker & it's contents, ontop of the mmi, causing it to shatter.

**Comment by ShizCalev** [comment]
Actually yes, looking at my test scenario, the MMI did take 153 points of damage (leaving 47 out of 200 integrity) from the explosion while inside the locker.

**Comment by cacogen** [comment]
Someone locked an unconfigured cyborg in the security locker from PubbyStation's cargo. It blew itself via the robotics control console, producing a brain instead of an MMI.

What's an unconfigured cyborg?

**Comment by bloons3** [comment]
> So someone locked an unconfigured cyborg in the security locker from PubbyStation's cargo. It blew itself via the robotics control console, producing a brain instead of an MMI.
> 
> What's an unconfigured cyborg?

Consider a cyborg that has not chosen a module.

**Comment by ShizCalev** [comment]
@ypoq yeah that's it.

**Comment by bloons3** [comment]
@ShizCalev I liked my title better :V
It described the issue and all possible corner cases

**Comment by ATH1909** [comment]
> @ShizCalev I liked my title better :V
> It described the issue and all possible corner cases

But this title describes the actual root cause of this problem.

**Comment by ShizCalev** [comment]
Actually familiarizing myself with explosion code further, that's all functioning as intended. 

The issue does infact seem to just be that the explosion starts processing after the mmi is spawned.

Chain being
robot/self_destruct()
-explosion()
---stoplag() delays processing
-Mmi is forcemoved into the closet during the delay
---explosion() processes the closet as a valid target due to epicenter loc
-----ex_act() called on the locker
--------ex_act() calls contents_explosion()
------------closet/contents_explosion() calls ex_act() on all it's contents, including the mmi which has already been moved

**Comment by Mickyan** [comment]
I'm not sure if this is the exact same issue as #49986 but this looks relevant

> It seems like the flag is only checked on atoms that are directly affected, so if you get hit by an explosion while the album is in your inventory the flag is only checked on the mob itself
> 
> https://github.com/tgstation/tgstation/blob/6401ba57081efb3db2f39320eeefeb13c1be4d8c/code/datums/explosion.dm#L197-L206
