### ISSUE TITLE
Evidence bags are F U C K

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#49239]
## Reproduction:
Try and put armory in evidence bags. Cry.
[Hell](https://media.discordapp.net/attachments/458452245256601615/675476297161637948/unknown.png?width=1089&height=681)
Try and put armory in one box. Cry.
[Hell 2](https://cdn.discordapp.com/attachments/458452245256601615/675477754199801938/unknown.png)
[See above](https://media.discordapp.net/attachments/458452245256601615/675477836320079935/unknown.png?width=1089&height=681)

This is with the roundstart evidence boxes on box. With 2 more you could fit everything in one box.

**Comment by ExcessiveUseOfCobblestone** [comment]
got any evidence?

**Comment by LemonInTheDark** [comment]
Brah. I have more pics if you need em, we live in a timeline

**Comment by ExcessiveUseOfCobblestone** [comment]
no i was joking cuz it's evidence bags

**Comment by LemonInTheDark** [comment]
Do you have any evidence of that?

**Comment by ArcaneMusic** [comment]
I can throw together a bandaid fix, but really what evidence bags need is to be refactored into items with a storage component, so that they're affected by #48579

**Comment by cacogen** [comment]
how did we not know about this
oh it's because no one ever uses them

**Comment by Tlaltecuhtli** [comment]
nah i ve seen it for a few months its just that someone got found out doing it

**Comment by trollbreeder** [comment]
there's a reason putting a BoH into a BoH causes a lot of death and there's a reason you can't put a shulker box into a shulker box

**Comment by nemvar** [comment]
This has been fixed like 2 times already
At least supposedly
