### ISSUE TITLE
Swarmer barriers don't block anything at all

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#49231]
version: yes
round ID: A number

#48659 at it once again

**Comment by ArcaneMusic** [comment]
It also occured on round  # 129830 on Bagil just a few moments ago.

**Comment by Buggy123** [comment]
It occurs on all rounds because its a bug that is not round or map or situation-dependent. The only way to _not_ reproduce it is if some change to can_pass or related unexpectedly fixes it.

**Comment by Tharcoonvagh** [comment]
Close this?
