### ISSUE TITLE
Drink crafting tab infinite creations.

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#49273]
129956

## Reproduction:

1. Get the yummy liquid you want to make clones off that is used in the drink tab
2. Fill a nice big bottle from the barvend with your liquid of choice
3. Use the crafting recipe in that lovely crafting menu to make what you want
4. Notice that the bottle is still full and you have a new lovely sprited bottle in your hands that is also full
5. Place the bottle on a nearby table or counter, away from the original bottle.
6. Repeat step 4-5
7. Realize you're jesus christ who has made infinite amounts of alcohol out of nothing
8. Realize you can ruin round types with this and make an issue so that you don't get lynched.

**Comment by ATH1909** [comment]
This has already been reported as being possible with holy water bottles, but I haven't been able to replicate this trick myself.

**Comment by ATH1909** [comment]
https://github.com/tgstation/tgstation/issues/48526

**Comment by carshalash** [comment]
Leave it on the floor, don't do it in hand. Make sure the holy water is in a new bottle.

**Comment by trollbreeder** [comment]
The Kingdom of Swadia returns with an invitation for a great drinking party.

**Comment by Krysonism** [comment]
The problem is that the blank bottle is not is own subtype.

**Comment by SuperNovaa41** [comment]
can't reproduce

**Comment by Sealed101** [comment]
no longer possible.
e.g. holy water flasks - creates a holy water flask and fills it with that holy water nice and proper. this flask will block any further crafting from its holy water.
