### ISSUE TITLE
Fading into non-existence with someone on your shoulder causes your hand to remain in use

### ISSUE THREAD

**Issue by InhumanPwnage** [tgstation/tgstation#49275]
As title says.

Had brain trauma of fading into non-existence. Carried someone on my shoulder, I faded into non-existence, and I lost the ability to use the hand which carried them when I came back into existence. They weren't on my shoulders anymore.

Round ID: 129970
Station: Terry

**Comment by Dennok** [comment]
Where appears carried? Or it completely disappears?

**Comment by XDTM** [comment]
Did the carried person fade with you or did they just drop to the floor?

**Comment by InhumanPwnage** [comment]
@XDTM Drop to the floor.

@Dennok Does not dissappear, the person drops, but my hand is still in use when i fade out and in.

**Comment by XDTM** [comment]
The bug could probably occur on other forms on teleportation then, it could need some testing.

**Comment by ATH1909** [comment]
I can confirm that this bug happens in other situations involving fireman carrying as well, but I forget exactly which ones. You can free up your "occupied" hand by pressing "q" while it's selected; it's not permanently "gone".

**Comment by knacker48** [comment]
This also happens if you shoulder carry a corpse to the ashwalker tendril. Like ATH said you can just drop the nothing that you're holding and free up that hand

**Comment by Sealed101** [comment]
it's been a hot minute
can no longer reproduce, `TRAIT_NO_TRANSFORM` properly forces the `riding_offhand` item off the player's hand. that or  #82625 fixed it. or something else, it has been over 4 years c'mon now
