### ISSUE TITLE
Atmospheric technician's helmet doesn't protect against facehuggers.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#49282]
It should.

**Comment by trollbreeder** [comment]
My time coding a gas mask and looking into xeno code to check how facehuggers jump and impregnate comes in useful today.

https://github.com/tgstation/tgstation/blob/6a198781d25ee82b987b5388ca3f13dc8fb45393/code/modules/mob/living/carbon/alien/special/facehugger.dm#L162
This checks if something is covering the mouth, but it needs to be headgear. Welding helmets, riot helmets, hardsuit helmets, etc. Masks are covered on line 168.

Now, let's see if the atmos tech helmet covers the mouth.
https://github.com/tgstation/tgstation/blob/6a198781d25ee82b987b5388ca3f13dc8fb45393/code/modules/clothing/head/hardhat.dm#L87-L99
Oh look, it doesn't. Technically this is a hardhat with a different icon that hides most of your head.

Looks like an oversight. You can also eat pills with the atmos tech helmet on.
