### ISSUE TITLE
Statbus deathmaps still use old pre-cloning removal maps.

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#49288]
Out of game, consistency issue. Statbus map used to visualize where deaths occured on the station if out of date, and in some cases such as metastation's expanded morgue the room layout can be completely different.

https://sb.atlantaned.space/rounds/130000/map
![old](https://user-images.githubusercontent.com/17460297/74199555-5a3c0e00-4c19-11ea-846f-8f4e15ebe87d.PNG)

Map changed as of #48668.
I'm unsure if updating this is being held off for now until more polished maps are made, but in case this is being forgotten consider this issue report as a reminder.

**Comment by kriskog** [comment]
Closing since its not really a repo issue, statbus is a standalone entity. 
@nfreader

**Comment by GravitronBlue** [comment]
Fair enough, was wondering if there was a better place to have reported this at.

**Comment by kriskog** [comment]
I @-ed the statbus guy, he'll see it

**Comment by nfreader** [comment]
Statbus lives at nfreader/statbus.
