### ISSUE TITLE
Flyswatter can bypass pacifism

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#49291]
## Reproduction:
Be a pacifist with a flyswatter
Try and swat a bee, click repeatedly
The message about living beings will come up, then you will splat the bee

**Comment by Coconutwarrior97** [comment]
It looks like pacifism is just straight up broken at the moment. I can hit someone with a baseball bat with the pacifism quirk. 
![image](https://user-images.githubusercontent.com/40315842/74224695-ee8c8c00-4c7e-11ea-8607-8cd93d3b7792.png)

**Comment by Tlaltecuhtli** [comment]
https://github.com/tgstation/tgstation/blob/363627677b2d3609ab014a81639f54ef3846ab12/code/game/objects/items/weaponry.dm#L641-L651

this is called anyway either put a pacifist check here or move it to run on attack
