### ISSUE TITLE
how to achieve faster than human walkspeed with a janicart

### ISSUE THREAD

**Issue by Timonkeyn** [tgstation/tgstation#49306]
## Reproduction:

1. get the janicart
2. get a Body
3. push the Body infront of you while driving to gain speed
4. I am speed

**Comment by HomocidlePancakes** [comment]
Imagine reporting !FUN!

**Comment by ATH1909** [comment]
Does this work with other vehicles too? Say, cardboard boxes?

Does it work with other things that a janicart can't pass through, like canisters?

**Comment by Timonkeyn** [comment]
>Does it work with other things that a janicart can't pass through, like canisters?
no

**Comment by ExcessiveUseOfCobblestone** [comment]
no wonder people saw arms off for this thing

**Comment by Sealed101** [comment]
can't reproduce
