### ISSUE TITLE
Plasmaman and ninja holding facility

### ISSUE THREAD

**Issue by Ghilker** [tgstation/tgstation#49305]
Issue reported from  Round ID: 130038 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1511

Plasmamans get all items removed when going to the ninja holding facility and die in a few seconds because their helmets gets removed, the breathing mask too and the plasma tank
![aaaaaa](https://user-images.githubusercontent.com/42839747/74247741-d6e8ee00-4ce6-11ea-9d9e-3f4a3554976c.PNG)

**Comment by Couls** [comment]
Huh I thought this issue was fixed a while back

**Comment by kriskog** [comment]
This was supposedly fixed in #45179, seems its bugged.

**Comment by Fikou** [comment]
ninaja gbj sint a thing anymore

**Comment by kriskog** [comment]
What about contractor aductees?
