### ISSUE TITLE
Holodeck is a Nar'Sie summoning site but the veil is not weak enough to draw the rune

### ISSUE THREAD

**Issue by Tumesuo** [tgstation/tgstation#49318]
Issue reported from  Round ID: 130099 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 513.1510

Read title.

**Comment by Tlaltecuhtli** [comment]
did you try in the tiny room near the pc?

**Comment by Tumesuo** [comment]
Yes
