### ISSUE TITLE
Delta medic morgue access

### ISSUE THREAD

**Issue by catswerecatswerethecats** [tgstation/tgstation#49320]
Issue reported from  Round ID: 130110 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

http://prntscr.com/r1em9p
Tested for MD and Paramedic IDs, they can't get through the door connecting morgue with maint under chemistry, other doors around it work just fine

**Comment by kriskog** [comment]
Likely genetics access hanging about, should be replaced with medbay only.
