### ISSUE TITLE
Death sim nanites won't stop #2

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#49321]
Don't have a exact round number but it happened in bagil 2/11/20

Don't know the test merges but it likely doesn't matter considering this issue.

Pretty simply the issue is that if you set up the death sim program to deactivate after x amount of seconds the death sim nanites don't stop however instead their nanite upkeep disappeared so you can't just wait it out. I am afraid it may become a repeat of https://github.com/tgstation/tgstation/issues/42681
Funny though. I discovered both in the same way. Self experimentation on death sim nanites which forced me out of the round. At least this time I didn't screw over the crew by accident. I will experiment when I have time to see if the same bugginess happens with the armor values and stuff like it did in the mentioned issue I posted earlier.

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=dHFK7dlwFGM
