### ISSUE TITLE
BOOOO I'm a floating light!

### ISSUE THREAD

**Issue by Ghilker** [tgstation/tgstation#49328]
![welp](https://user-images.githubusercontent.com/42839747/74417849-b71d0b80-4e47-11ea-9152-931324913d07.PNG)
The map is delta

**Comment by ATH1909** [comment]
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by trollbreeder** [comment]
god fucking damnit i thought only donutstation was haunted by wizards

**Comment by trollbreeder** [comment]
also this is a table light

**Comment by Ghilker** [comment]
Ba Dum Tsss

**Comment by cacogen** [comment]
holy fuck there's a ghost

**Comment by pubby** [comment]
It's attached to the ceiling
