### ISSUE TITLE
Cargo shipments do not account the items inside the crates shipped to cetcomm

### ISSUE THREAD

**Issue by Amalvi** [tgstation/tgstation#49345]
## Round ID: 
130187

## Reproduction:
None of the crates sent in cargo to cetcomm acconted for the items inside
I filled a simple grey crate full of monkey organs and only gave the 500 credits for the crate. Earlier in the round the same happened for all the trash that were inside the random crates in cargo

**Comment by Donpedrito** [comment]
Did you check with an export scanner that the organs actually have a value?

**Comment by ArcaneMusic** [comment]
Were the organs for a bounty? If so, you needed to claim the bounty at the bounty console.

**Comment by Couls** [comment]
If you're referring to the bounty to collect trash you need to claim it at the console like arcane said

**Comment by Amalvi** [comment]
No, it wasn't for a bounty
It wasn't merely once or with just the monkey organs, every single crate sent didn't consider the items inside the crates

**Comment by Amalvi** [comment]
I just tried reproducing the bug, I entered bagil at zero pop and as a HoP I worked in cargo, filled crates with items and also killed a monkey for its organs.
Donpedrito was right, I passed the scanner over all the items and only those that gave a some value were detected while inside the crates. Apparently they removed the value of 99% of things (gas masks, cards, organs...) and we didn't know that in the round.
I remember organs clearly having a high price and now they are absolutely zero, not happy at all

**Comment by Donpedrito** [comment]
If you disassemble the supply console, multitool the console's board, and reassemble it, you can buy and sell some contraband, including organs if I recall correctly. That might be why you remember them having a value before.

**Comment by Couls** [comment]
Console needs to be hacked as of #46816 to get money from organs

**Comment by ArcaneMusic** [comment]
> Console needs to be hacked as of #46816 to get money from organs
...Accccccctualy, back up on that one. It looks like organs don't have a export datum at all. Even 46816 didn't assign organs as contraband, and the current master doesn't list them there either.

**Comment by Couls** [comment]
if organs weren't given an export datum I assume they're not meant to have a value outside of bounties?
