### ISSUE TITLE
TGUI Next Arcade boss health bar slider doesnt move.

### ISSUE THREAD

**Issue by Arturlang** [tgstation/tgstation#49354]
## Testmerges:#49042: 'Adds speech sounds' by kriskog at commit 9e77243306
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction: Look at the arcade program in a modular computer, notice the boss mob health bar doesnt actually move, nor is ever the maximum, its just the minium always.
![image](https://user-images.githubusercontent.com/24881678/74545495-a22c9f00-4f51-11ea-8e75-de42d6549ea5.png)

**Comment by ArcaneMusic** [comment]
Hmm. that's new. I'll take a look at this.
