### ISSUE TITLE
Supermatter sliver doesn't dust you when it's flying at you and hits you

### ISSUE THREAD

**Issue by Bokkiewokkie** [tgstation/tgstation#49357]
I was once again messing around with the supermatter sliver object and noticed that it doesn't dust you when it gets launched at you.

Of course it is very unlikely that this will happen since it requires a bit of careful positioning but I was also wondering if this was intentional or not (because the sliver falls out of the tongs when thrown so you can't used it as a ranged weapon on purpose).

## Reproduction:

1. Spawn a supermatter sliver.
2. Spawn any explosive with enough force to push items around.
3. Put the explosive next to the sliver and trigger it.
4. Stand in the direction the sliver will get tossed when the explosion occurs (for higher success chance equip magboots so you won't be thrown around because of the hole)
5. Wait for the explosion to happen
![image](https://user-images.githubusercontent.com/43698041/74570688-1c264d80-4f7d-11ea-9be7-e366cb48386b.png)

**Comment by cacogen** [comment]
probably an oversight

**Comment by spessbandit** [comment]
100% an oversight fuck this sliver

**Comment by Dennok** [comment]
What about airflow dragging?
What about launchers (chappel, trach) ?
What about disposal pipe, output?

**Comment by Dennok** [comment]
And related to SM shard but dont related to here.
TK grab don't interfere wits SM shard. Just no effect.
TK tongs attack dust you anyway. (place tongs, take it TK, wait until someone approximate to loot SM sard in tongs. Hit it by TK grabbed SM shard tongs.)
SM shard walk on?

**Comment by ShizCalev** [comment]
TK grab not working on slivers is intentional.

**Comment by Dennok** [comment]
> TK grab not working on slivers is intentional.

TK on SM core dust your brain.
TK on silvers must dust your brain or say that you try but cant TK interract with silvers.
I think, beter add some damage and knockdown on the TK silvers.
