### ISSUE TITLE
Lavaland Tunnels do not spawn, resulting in no roundstart Fauna, Tendrils or most Megafauna

### ISSUE THREAD

**Issue by Taylorkills2** [tgstation/tgstation#49367]
## Round ID: 
130257 among others

## Testmerges:
#49081: 'Fixes SM hell, makes some changes to how gas is handled in the SM' by LemonInTheDark at commit 81d30538f7
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:
Play a round on Bagil, wait for roundstart, no tendrils, bubblegum, ashdrakes, or Collosus.
Blood Drunk and some other ruins still spawn, those that don't require tunnels.

Likely broken by something in the Lavaland Gulag changes.

**Comment by bluetshirtguy** [comment]
It happened to me just now basically. no tendrils no tunnels. but some megafauna(blood drunk hiero legion) and a few ruins too.

**Comment by Buggy123** [comment]
fuck this might've been me in #49205

**Comment by tralezab** [comment]
it's absolutely that pr yeah

**Comment by Tlaltecuhtli** [comment]
the mining nerf we needed

**Comment by Tharcoonvagh** [comment]
And this, noone closed this
