### ISSUE TITLE
Wizard rituals now no longer have summon guns, summon events and a few others. Now only has two spells under rituals.

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#49363]
Issue reported from  Round ID: 130254 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1511

Spell book only has curse of madness and summon ghosts.

**Comment by cacogen** [comment]
is this a config thing?

**Comment by Taylorkills2** [comment]
It's a Dynamic mode thing, not a bug.

**Comment by Couls** [comment]
like the comment above stated the other events are disabled on dynamic mode
