### ISSUE TITLE
Donk Pocket pizza no longer craftable

### ISSUE THREAD

**Issue by CptnCapitalism** [tgstation/tgstation#49373]
It appears that with the additon of the many new kinds of donk pockets, it's not possible to craft this pizza, which is a shame, since it has pretty good stats. Could someone modify the recipie, so that it accepts any kind of warmed donk pocket?

Issue reported from  Round ID: 130276 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1511

**Comment by improvedname** [comment]
Not a bug you can make normal donk pockets as a chef

**Comment by improvedname** [comment]
![image](https://user-images.githubusercontent.com/24854897/74629191-ed180380-5157-11ea-89f3-6bb1c64369f6.png)

**Comment by CptnCapitalism** [comment]
Thank you guys for fixing this!
