### ISSUE TITLE
Typo in hardsuit thermoregulator battery charge text.

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#49371]
Issue reported from  Round ID: 130266 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1511

"The power _**meeter**_ shows 83% charge remaining."

**Comment by cacogen** [comment]
more half-assed merges

**Comment by nightred** [comment]
This was fixed in PR #49362
