### ISSUE TITLE
Ninjas freeze in space

### ISSUE THREAD

**Issue by Timonkeyn** [tgstation/tgstation#49381]
Issue reported from  Round ID: 130305 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507

1. get spawned as ninja and instantly freeze

**Comment by ATH1909** [comment]
Did you activate your suit?

**Comment by HomocidlePancakes** [comment]
Suit take around a minute to activate, bro.

**Comment by Tharcoonvagh** [comment]
NIGHTRED
