### ISSUE TITLE
RCDs can place multilayered machine frames.

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#49405]
So uh....
You know how rcds have that one upgrade that lets you place machine frames?
They don't check for things that are already there.
![Pain](https://cdn.discordapp.com/attachments/458452245256601615/676684505293258775/unknown.png)
![Pain](https://cdn.discordapp.com/attachments/458452245256601615/676684878817001483/unknown.png)

Engi players.

Not even once.

## Reproduction:
Do what you think.

**Comment by LemonInTheDark** [comment]
Round was a while back, was observing. If you need the round ID I can dive for it but it'll be a wait.

**Comment by Tlaltecuhtli** [comment]
is there a cheaper way instead of looping for /obj/machinery and /structure/frame in turf contents?

**Comment by GravitronBlue** [comment]
Really should have more checks during construction that looks for other existing buildings where something is being built at.

Doesn't this basically work using disposals as well?
![Cheekybreeki](https://user-images.githubusercontent.com/17460297/74644679-7fee7900-512b-11ea-8812-5d5932ff3288.PNG)

**Comment by Tlaltecuhtli** [comment]
frames prevent you from wrenching if something there exist

**Comment by trollbreeder** [comment]
but RCD'd machine frames are already wrenched and filled with cable

**Comment by ATH1909** [comment]
feature

**Comment by Tlaltecuhtli** [comment]
i m talking about other ways to stack machines like in the picture

**Comment by GravitronBlue** [comment]
Going to run a few tests then and make sure you still can't do this by wrenching down a mobile machine where something else already exists.

**Comment by Tlaltecuhtli** [comment]
well then, is there a less ugly way than sticking this in wrench act
	if(locate(/obj/structure/frame/machine) in src)
            return FALSE
	if(locate(/obj/machinery/) in src)
          return FALSE

**Comment by LemonInTheDark** [comment]
fuck 
![image](https://user-images.githubusercontent.com/58055496/87230250-8b08a680-c363-11ea-9eda-81bb9d031e62.png)

**Comment by LemonInTheDark** [comment]
oh I hate life
