### ISSUE TITLE
The Mafia Nickname Cards can allow for very, very, very long nicknames.

### ISSUE THREAD

**Issue by ArcaneMusic** [tgstation/tgstation#49403]
## Testmerges:
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45
#49081: 'Fixes SM hell, makes some changes to how gas is handled in the SM' by LemonInTheDark at commit 81d30538f7
#49370: 'Revert "Random mineral spawning (mostly) no longer change turfs"' by tralezab at commit 99a680ec41

## Reproduction:

Buy the crate, burn the card, and set a very, very, very long nickname. You can flood the entire chatbox just by saying one letter now that your name is 800 characters long.
Probably just needs a length limit like 50-120 characters or something.

**Comment by trollbreeder** [comment]
That's how mafia works.

**Comment by ArcaneMusic** [comment]
Should be closed with #49401, but if it's not I'll keep an eye out
