### ISSUE TITLE
Long-To-Short-Range-Bluespace-Transciever description misleading

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#49419]
## Reproduction:
Purchase the... oh fuck... LTSRBT crate
build the machine
try every possible interaction with it (tools, intents, special clicks etc)
nothing
put crates under and above it
nothing

what even is that thing? when was it added? it costs 10k cargo points and basically does nothing

**Comment by kriskog** [comment]
Its for the black market uplink, you cant use it for anything on its own.

**Comment by Dorsisdwarf** [comment]
Its possible that the crate should include a paper with usage instructions

**Comment by Dennok** [comment]
You need craft black market uplink
You can see it in crafting menu in misc 
When you purchase something in black market uplink, black market send it to random place on station, or to Long-To-Short-Range-Bluespace-Transciever

**Comment by HomocidlePancakes** [comment]
#48676

Friendly reminder that it’s still broken
