### ISSUE TITLE
Space ninjas dont get a space insulated suit and start dying 

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/tgstation#49415]
## Round ID:
130430

## Testmerges:

#48579: 'Port of Replays from Yogstation' by actioninja at commit 69e734d65e
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45
#49370: 'Revert "Random mineral spawning (mostly) no longer change turfs"' by tralezab at commit 99a680ec41
#49274: '[READY]The Families Gamemode. Home. At least it was 'till I fucked everything up.' by Iamgoofball at commit f320129d4e

## Reproduction:

Spawn in as a ninja in spess
Start dying to the cold

**Comment by Tharcoonvagh** [comment]
doop

**Comment by nightred** [comment]
oh um i will get this added to the fixes i have running.

**Comment by Couls** [comment]
dupe of #49381
