### ISSUE TITLE
Mood becoming super bad with tons of positive modifers

### ISSUE THREAD

**Issue by SkeletalElite** [tgstation/tgstation#49416]
## Round ID: 

130434

## Testmerges: 

#49065 #49081 #49370 

## Reproduction: 
Used the pet park holodeck for lots of modifiers with the hypersensitive quirk.
![ThatsaMood](https://user-images.githubusercontent.com/26270704/74685170-8cea8700-5182-11ea-99f0-bdca79793c56.PNG)

**Comment by nemvar** [comment]
Can not reproduce
![cannotreproduce](https://user-images.githubusercontent.com/47324920/74765240-7f68f600-5283-11ea-8c72-f232bab16ccd.PNG)

**Comment by nemvar** [comment]
Closing this now.

**Comment by Qustinnus** [comment]
Maybe a bug with hidden moodlets?
