### ISSUE TITLE
TGUI Next arcade ticket printing is wierd

### ISSUE THREAD

**Issue by Arturlang** [tgstation/tgstation#49428]
Reproduction: Attempt to print a ticket in the arcade program while you have zero tickets: It says it prints something, yet it does not.

**Comment by Arturlang** [comment]
Also, wierd stuff happens when you spam the buttons, wierd sound and cooldowns can break, making everything happen fast sometimes, and not consisently at all

**Comment by Sealed101** [comment]
can't reproduce
