### ISSUE TITLE
Admin updating/removing traits in VV doesn't change what you get examining yourself

### ISSUE THREAD

**Issue by spessbandit** [tgstation/tgstation#49420]
So if you VV someone to remove, say, Pacifist, and they examine themselves, they'll still see, for instance, "You have these quirks: Pacifist, Musician, Friendly."

**Comment by Couls** [comment]
you used the dropdown for remove trait yeah? just making sure, specifics steps of removing the trait through VV would be useful

**Comment by XDTM** [comment]
traits and quirks are not the same thing; if what you're removing is the pacifist trait the quirk is still there and providing the description

**Comment by nemvar** [comment]
Can not reproduce on local. The name of this implies that you probably used the "Remove Trait" option instead of the "Remove Quirk" one, in which case this is intended behaviour.

**Comment by nemvar** [comment]
![clown](https://user-images.githubusercontent.com/47324920/74766738-f1423f00-5285-11ea-88df-39a86fe0d117.PNG)
