### ISSUE TITLE
Recycler qdels ethereal jaunted wizard

### ISSUE THREAD

**Issue by BadSS13Player** [tgstation/tgstation#49435]
## Round ID: 130509
Wizard round.

## Reproduction:
Ethereal jaunt as wizard. Walk into recycler. Get qdel'd. Round doesn't end because you technically didn't die, you were just deleted from the game.

**Comment by ATH1909** [comment]
that's amazing

**Comment by ATH1909** [comment]
this is the true summon events x5 meta

cast summon events 5 times, go runic golem, then jaunt into a recycler

does the recycler have to be emagged?

**Comment by HomocidlePancakes** [comment]
Probably works with nightmares too.

**Comment by Tlaltecuhtli** [comment]
in the trash it goes

**Comment by ATH1909** [comment]
Do you become an observer when this happens, or do you just remain stuck in place in an ethereal state?

**Comment by BadSS13Player** [comment]
> Do you become an observer when this happens, or do you just remain stuck in place in an ethereal state?

You become an observer and I think your observer teleports to the arrivals shuttle. I think the wizard mob still exists, because an admin managed to bring it back and stuff the ghost back into it.

**Comment by Ty-the-Smonk** [comment]
Iirc if you jaunt you turn into what amounts to an item

**Comment by ATH1909** [comment]
By the way, that round wasn't a dynamic round, right? It's kind of odd that it didn't end when you got deleted.

**Comment by BadSS13Player** [comment]
> By the way, that round wasn't a dynamic round, right? It's kind of odd that it didn't end when you got deleted.

Wasn't the one who got deleted, I was observing the round. Round didn't end because the actual mob wasn't deleted, only the /obj/effect representing the jaunted wizard.
