### ISSUE TITLE
Trying to eat organs makes you hit yourself with them

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#49430]
## Testmerges:
Not a testmerge but likely caused by #48596 @Qustinnus 

## Reproduction:
* Get an organ
* Eat that organ
* Wait why is a do_after running
* Why did I just thump myself with a heart
* Bite the organ

**Comment by Donpedrito** [comment]
Does #49402 fix this?

**Comment by Qustinnus** [comment]
Yes

**Comment by itseasytosee** [comment]
Huge hit to ashlizards and stranded crewmen trying to make the most out of a body

**Comment by Donpedrito** [comment]
This is fixed now, right? #49402 was merged.

**Comment by cacogen** [comment]
Tried stomach, appendix, lungs, liver and heart as an ash walker on d3e066b17bfae0e85e80da018391d7c1fa7e96e0 and they all worked fine.
