### ISSUE TITLE
Walk mode randomly toggles

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#49445]
## Reproduction:
I really don't know, it can (seemingly) toggle out of the blue, and as a non-humanoid you can't toggle it again without changing the keyboard prefs (shift+alt). Annoying at best

**Comment by trollbreeder** [comment]
holding ALT toggles between run and walk mode for some reason

**Comment by Donpedrito** [comment]
I’ve had this as a borg many times, it seems to have something to do with alt-tabbing.

**Comment by Couls** [comment]
If you’re alt tabbing it’ll make you walk you can change the walk key from alt to prevent this

**Comment by ShizCalev** [comment]
Windows issue.
