### ISSUE TITLE
Ninja spawns in space, immediately freezes to death

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#49455]
Pretty self explanatory. I assume this is a consequence of the recent PR that updated spacesuits to have battery-powered heating systems. There was a button on my toolbar to activate it, but I was at half health before I realized what was happening, and clicking it didn't seem to stop me from freezing to death.

Testmerges: #49065

Reproduction:

1. Roll antag.
2. Spawn as a space ninja in space.
3. Freeze to death.

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=Ag1o3koTLWM

**Comment by Couls** [comment]
Still?

**Comment by Tharcoonvagh** [comment]
Dupe?

**Comment by Couls** [comment]
Technically but this is slightly different, if you're cold and turn on the suit then you'll keep freezing rather than your temperature regulating

**Comment by nightred** [comment]
I will review them again
