### ISSUE TITLE
Abductors can't retrieve marked targets when solo

### ISSUE THREAD

**Issue by Abductkaz** [tgstation/tgstation#49453]
[Round ID]: 130582 Bagil 
## Testmerges:
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:
Abductors if they are equipped to work solo (i.e agent suit, baton, science tool, return button, etc) cannot do the final step to retrieve the target they've marked.

1. Be the above solo agent/scientist combo abductor
2. Find target, stun, sleep, cuff, probe them, then get the science tool and mark them yourself
3. Hit the return crystal/button to go back to your ship
4. Attempt to retrieve the specimen via the camera console, realize it does literally nothing when you click retrieve
5. Redtext

Oddly, it seems to work just fine when the second agent does the stunning, sleeping, cuffing and probing. The 'solo' agent can then come down and mark them like a scientist and retrieve them just fine.

**Comment by kriskog** [comment]
Did you buckle them to something?

**Comment by itseasytosee** [comment]
Ah yes it appears the fixes to library machine have blocked the radio waves used for transporting people to the abductor ship.

**Comment by Abductkaz** [comment]
> Did you buckle them to something?

They were unbuckled, unless somehow the you can be buckled to something in the engineering gravity generator foyer, which is one of the instances where this happened among others.

**Comment by XDTM** [comment]
I think the science tool is usually linked to the console in some way, maybe whatever made you a solo abductor skipped that step, so marking targets didn't update the console

**Comment by Abductkaz** [comment]
> I think the science tool is usually linked to the console in some way, maybe whatever made you a solo abductor skipped that step, so marking targets didn't update the console

Possibly, but I also had a friend. The exact same science tool worked 100% fine when the other abductor did the stunning and cuffing. It just refused to transport if I was doing it solo.

**Comment by SouDescolado** [comment]
https://github.com/tgstation/tgstation/blob/b3660adb53a0f0fd63539d209e86db2df42c3faf/code/modules/antagonists/abductor/equipment/abduction_outfits.dm#L52

Maybe this part runs first and it doesn't continue to trigger the `link_to_console(H)`. Adding the command here should fix, but since I cannot test it I will avoid doing that

**Comment by SkeletalElite** [comment]
I was a solo abductor yesterday and did not have this issue
