### ISSUE TITLE
You can't gib mobs

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#49450]
Issue reported from  Round ID: 130558 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507

##Reproduction:
-try to gib goliath
-fail miserably and stab it instead
(harm intent with knife)

**Comment by nemvar** [comment]
What knife did you use?

**Comment by Tharcoonvagh** [comment]
survival knife attached to a pKA on harm intent

**Comment by Tharcoonvagh** [comment]
or a bone knife, i had two of em

**Comment by dragomagol** [comment]
Unable to reproduce
