### ISSUE TITLE
Deconstructing any smartfridge type gives you a board for the default smartfridge

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#49461]
So for example, if you deconstruct an organ smartfridge you get a board for a regular smartfridge

You can fix that by using a screwdriver on the board to change its type but it should really spawn a board with the proper setting

**Comment by Tharcoonvagh** [comment]
Is it the same with freezers?

**Comment by ShizCalev** [comment]
58d0f12c5c7d8b8a3bd15bd93a2c514dcfbddfee
