### ISSUE TITLE
no sawn off riot shottie inhands

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#49463]
Issue reported from  Round ID: 130619 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507

**Comment by ATH1909** [comment]
As in, the sprites that appear on your character, or the sprites that appear in your inventory/hand slots?

**Comment by Tharcoonvagh** [comment]
![tgStation Terry  EU   100% LAG FREE   New-Dedi  Hats Garden Upsilon 2020-02-20 185317](https://user-images.githubusercontent.com/54288658/74972299-be34b280-5421-11ea-8b7f-dff3627fc049.png)

**Comment by Bokkiewokkie** [comment]
another one to add to the missing inhands section on the missing sprites project I guess

**Comment by Tharcoonvagh** [comment]
It should be fixed as mentioned in #47007

**Comment by Tharcoonvagh** [comment]
Bam, #47019
