### ISSUE TITLE
hacked vendors with no contraband blank white

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#49467]
Issue reported from  Round ID: 130633 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507

-hack secdrobe
-click on it
-its blank white, can only close with alt f4

**Comment by Donpedrito** [comment]
I’ve noticed this happens with a lot of vendors, afaik it happens to vendors with no hacked items. Mending the contraband wire seems to fix it.
