### ISSUE TITLE
if you go through the recycler in a cardboard box you get fucking deleted

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#49464]
Issue reported from  Round ID: 130629 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507
To reproduce:
-go to disposals
-make a metal gear cardboard box
-turn on the conveyor belt
-enter the box
-step on the belt by accident because fuck life
-get deleted and teleport to the arrivals shuttle

**Comment by PKPenguin321** [comment]
Can this happen with lockers/bodybags/etc if you're put on a moving conveyor belt?

**Comment by ATH1909** [comment]
WIll people killed by this count as being dead for objectives?

**Comment by Tharcoonvagh** [comment]
probably @PKPenguin321 , i don't know. someone test it please
@ATH1909 don't think so, since something similar happened in #49435

**Comment by Tharcoonvagh** [comment]
#49473 is similar

**Comment by Ty-the-Smonk** [comment]
Does the recycler delete everything inside a cardboard box?

**Comment by Tharcoonvagh** [comment]
Yes
