### ISSUE TITLE
Chameleon projector can scan blood drops and grafitti

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#49479]
No way in hell this is intended.

## Reproduction:
1) Buy chameleon projector
2) Scan blood drops or grafitti
3) Click chameleon projector

**Comment by Tharcoonvagh** [comment]
Intended

**Comment by PKPenguin321** [comment]
It already defaults to a cigarette butt which is smaller than both of those things, I don't think this is an issue

**Comment by TheVekter** [comment]
You can pick up a cigarette butt. You can't pick up decals.

**Comment by necromanceranne** [comment]
@PKPenguin321 The chameleon projector is meant to explicitly prevent decals, as it is meant to be returning if you scan decals. It isn't. So no, this is actually a bug. 

Let's fix the bug before discussing balance.

**Comment by necromanceranne** [comment]
(also, this includes scanning graffiti, which can be spammed on the floor for literal invisibility while using the cham projector against the backdrop of the graffiti. We already killed off most of the means for camouflage using spray cans, so if anything, this is a problem with consistency on top of this. While on their own a drop of blood might be no less innocuous as a cigarette butt, it is impossible to distinguish against an entire room filled with blood, which is far more powerful than an object out of place.)

**Comment by bobbahbrown** [comment]
> @PKPenguin321 The chameleon projector is meant to explicitly prevent decals, as it is meant to be returning if you scan decals. It isn't. So no, this is actually a bug.
> 
> Let's fix the bug before discussing balance.

You're actually incorrect. The functionality you are incorrectly describing is that the scanner explicitly _allows_ decals, in fact its the only thing of the type /obj/effect that it allows.

https://github.com/tgstation/tgstation/blob/7ca9d39ebb148ca42079233beaa3f87256310706/code/game/objects/items/devices/chameleonproj.dm#L56-L58

**Comment by necromanceranne** [comment]
Please be patient, I have catbrain QwQ

**Comment by Tharcoonvagh** [comment]
ew
