### ISSUE TITLE
Phobia Quirk is randomizing on round start

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#49474]
## Reproduction:
* Take a phobia quirk
* Ready up on an online round with during med pop or higher
* Your quirk will be randomized
* ~~Also the triggering word is expunged but mentioned in the trigger message (Screenshots provided, phobia being ran was Strangers)~~ fixed

![image](https://user-images.githubusercontent.com/3204033/75008455-ee358300-542c-11ea-83c9-fcc203c4ac03.png)

![image](https://user-images.githubusercontent.com/3204033/75008468-f7265480-542c-11ea-9f6e-b3d7bea831b5.png)

I also had a round where I was getting fear of falling triggers like "slip"

**Comment by Pumpkinoe** [comment]
To add on, when I scanned Heart Emoji with my health scanner then terrorized them by saying 'Alien', it said their phobia was of aliens.

**Comment by XDTM** [comment]
I recently fixed the regex that detects the wording, but it's supposed to give it a black and red span, not remove it altogether.

**Comment by RaveRadbury** [comment]
Closed by #52374
