### ISSUE TITLE
Showering with a wig on changes its color.

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#49480]
## Reproduction:
* Get a wig from the costume drobe and equip it
* Go take a shower
* Wig in the equipment slot changes color but the wig on the mob doesn't update

I don't think it's intended but either way something here isn't working the way it should.

**Comment by Time-Green** [comment]
Haircolor should be atomcolor so it can’t be showered off and color changes should immediately update on the mob
