### ISSUE TITLE
rd doesnt have access to donut station ai upload windoors 

### ISSUE THREAD

**Issue by Kylerace** [tgstation/tgstation#49492]
Issue reported from  Round ID: 130715 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1511

**Comment by sultan8ap** [comment]
Yeah... Upload youtube video download option.... [Download ](https://www.youtube.com/channel/UCpLq7VEHvuck-4cIz9u0pzw)
