### ISSUE TITLE
Hygienebots can't be made and have some minor issues

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#49514]
### Stuff:
* You can't build a hygienebot since you can't make an incomplete hygienebot assembly, as far as I can tell. [FIXED]
* You can't disassemble an incomplete hygienebot assembly. 
* Hygienebot isn't in the crafting menu. 
* It eats an entire stack of fluid ducts on the last construction step (I think). [FIXED]
* You can open the hygienebot's panel with a screwdriver but it has no effect. Unlike the other bots you don't need to open the panel to emag it (consistency thing).

**Comment by RandolfTheMeh** [comment]
That fourth point goes for anything. It eats anything except the welder on the first step, meaning if you hit it with a welder again it'll eat your welder. If you try to rename it, it'll eat your pen. If you hit it with a stack of 25 pipes instead of 1, it'll eat the 25 pipes.
