### ISSUE TITLE
Microdosages of certain chems cause effects to never wear off

### ISSUE THREAD

**Issue by EOBGames** [tgstation/tgstation#49512]
## Round ID:
N/A (this was on local)

## Reproduction:
Apply a dosage of higadrite to yourself below the metabolism rate. Enjoy the infinite sturdy liver.
Best guess is that it metabolises without proccing the "on end metabolise" block, so the trait never gets cleared.

**Comment by ATH1909** [comment]
oh god oh fuck

the return of using bath salts to become stun immune forever

by "metabolism rate", do you mean 0.4u?

**Comment by ATH1909** [comment]
it looks like higadrite uses on_mob_**add** to apply its sturdy liver effect, but on_mob_end_**metabolize** to remove it; that could be the problem here

**Comment by EOBGames** [comment]
Yeah, you nailed the problem on the head right there- fix is switching over to the more sane method used on chems like pax. I'd call this an easy first issue for anyone looking to fix something.

**Comment by XDTM** [comment]
Simply replace on_mob_add with on_mob_metabolize, i made it for this exact purpose.
