### ISSUE TITLE
Brooms do not check if objects should be able to be pushed prior to pushing

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#49513]
## Round ID:
n/a

If a user tries to use a broom on items, they will attempt to move as long as they are not anchored. This may benefit from checks to see if they should be able to move.
## Reproduction:
1. have broom
2. push items

**Comment by cacogen** [comment]
as long as they are anchored?

**Comment by bobbahbrown** [comment]
> as long as they are anchored?

not*

**Comment by cacogen** [comment]
I'm not sure how I wasn't able to infer that

**Comment by dragomagol** [comment]
Appears to have been fixed
