### ISSUE TITLE
Broom unequips all items

### ISSUE THREAD

**Issue by alexsohn** [tgstation/tgstation#49519]
## Round ID:130777

If you discovered this issue from playing tgstation hosted servers:
[Round ID]: # 130777

## Reproduction:

If you wield a broom and then try to unwield it all of your items will drop on the tile in-front of you.

**Comment by ATH1909** [comment]
As in, everything you're wearing?

Can this be used to remove nodrop items?

**Comment by alexsohn** [comment]
Everything I'm wearing yes, wasn't able to try nodrop items

**Comment by trollbreeder** [comment]
This must be the fault of a runtime error, surely...

**Comment by bobbahbrown** [comment]
I've not experienced this issue with brooms, can anyone verify reproduction steps?

**Comment by Time-Green** [comment]
I got this too when trying to put a broom in my bag. It drops everything on the floor but I also keep it on so it glitches out

**Comment by Mickyan** [comment]
I've had this happen once. I can't reproduce it and I can't see any runtimes in the logs.

**Comment by Mickyan** [comment]
Found a way to reproduce this, click on your offhand while two handing. Lazy fix would be to only allow turfs to be targeted.

**Comment by bobbahbrown** [comment]
This is amazing, its because you can actually BRUSH OFF the items in your inventory and that you're currently wearing. Allows you to sweep away the off-hand sprite into the world and drag it around.

It becomes super messed up when someone picks up that offhand sprite and then you sweep it again, drops duplicated sprites with reference to same item of the person who picked up the offhand.

**Comment by XDTM** [comment]
Time to add a quantum broom that sweeps literally everything

**Comment by ATH1909** [comment]
> This is amazing, its because you can actually BRUSH OFF the items in your inventory and that you're currently wearing. Allows you to sweep away the off-hand sprite into the world and drag it around.
> 
> It becomes super messed up when someone picks up that offhand sprite and then you sweep it again, drops duplicated sprites with reference to same item of the person who picked up the offhand.

holy shit that's amazing

what can you do with these duplicated references to your offhand?

I wonder how this interacts with the ninja suit... I know that if you use instant summons to recall a battery in a ninja suit, then cut your arm off or something, you can give your ninja suit to someone else and they can remotely activate your ninja powers (from YOUR location) with it; I wonder if you could do something similar to that here.

**Comment by ATH1909** [comment]
Damn, if only I could get a third hand so I could sweep off abstract stuff like yeet hands...
