### ISSUE TITLE
typos in mood descriptions

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#49521]
> /datum/mood_event/badass_antag
> 	description = "<span class='greentext'>I'm a fucking badass and everyone around me knows it. Just look at them; they're all fucking shaking at the mere **thought of me around**.</span>\n"
> 	mood_change = 7
> 	hidden = TRUE
> 	special_screen_obj = "badass_sun"
> 	special_screen_replace = FALSE

> /datum/mood_event/pet_borg
> 	description = "<span class='nicegreen'>I just love my **robotical** friends!</span>\n"
> 	mood_change = 3
> 	timeout = 5 MINUTES

**Comment by RaveRadbury** [comment]
I'm actually not sure what the problem is with the first one, the second one sounds intentional, as robotic would be the correct word.
