### ISSUE TITLE
Crusher and Cleaving Saw not working properly on Goat King Mega Fauna

### ISSUE THREAD

**Issue by Megadeadly** [tgstation/tgstation#49522]
Issue reported from  Round ID: 130802 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1511

Crusher properly marks goat king for detonation, but heiro trophy fails to proc. Cleaver also appeared to fail to cause bleed, making battle nigh impossible to do using melee weapons. Not looked through code, but assuming and hope this is just an oversight.

**Comment by HomocidlePancakes** [comment]
>heiro trophy fails to proc

Intentional, but super fucking retarded. The lad who made goat king made it so the trophy couldn’t trigger in noteleport areas.

**Comment by Megadeadly** [comment]
Thanks for the reply, and that sucks to hear. Any idea why cleaver doesn't proc? Guy I was going with said bleed failed to apply.
