### ISSUE TITLE
the tango dress does not work on digilizards. (the dress is on pubby

### ISSUE THREAD

**Issue by MajorMeltdown** [tgstation/tgstation#49536]
## Round ID:
I got this on fulpstaion so ill put its round ID:5933

## Testmerges:
nope

## Reproduction:
1.grab dress
2.take off jumpsuit
3.put on
4.you are now naked with pockets and an ID slot

**Comment by cacogen** [comment]
seems intentional

**Comment by HomocidlePancakes** [comment]
Stop being a degen and play a human.

**Comment by dragomagol** [comment]
Appears to have been fixed
