### ISSUE TITLE
You can give yourself AA through the ID modification software on tablets

### ISSUE THREAD

**Issue by Canohaaaaaaa** [tgstation/tgstation#49530]
## Round ID: 
130828

## Testmerges:
#49233: 'Paintings icons and persistence.' by AnturK at commit 6042cba7c3
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45
#49111: '[READY]Arconomy: Sales Taggers, split profits on barcoded, sold items!' by ArcaneMusic at commit 50d52bd564

## Reproduction:

1.Download the ID modification software
2.Insert your ID and log in
3.Press "grant all"

You now have all access

**Comment by Tlaltecuhtli** [comment]
you need hop access on the id inside the table to download the job specific program if it didnt change recently

**Comment by Canohaaaaaaa** [comment]
Downloaded as CE

**Comment by Dorsisdwarf** [comment]
I bet this is related to heads of staff having their personal departmental ID consoles

**Comment by Tharcoonvagh** [comment]
###👀

**Comment by NanoCats** [comment]
Unsure why, but I can't replicate this 100% of the time, I tried it randomly as an engineer and the ID mod software was there, I downloaded it, I gave myself AA, I got lynched immediately for having AA.

But in a subsequent round the program wasn't there no matter what I did.
