### ISSUE TITLE
Snake Crates Nearly Disappear When Open

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#49535]
Issue reported from  Round ID: 130845 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1507

Closed Crate:
![Closed](https://user-images.githubusercontent.com/53582584/75122511-fa028e80-5652-11ea-8d55-67df35d053b1.PNG)
Open Crate:
![Open](https://user-images.githubusercontent.com/53582584/75122517-05ee5080-5653-11ea-8719-143b38979f54.PNG)
 1. Find a snake crate.
2. Open it.

**Comment by ATH1909** [comment]
insert metal gear solid joke here

**Comment by cacogen** [comment]
why i didn't think of it

**Comment by NanoCats** [comment]
FYI this is true of all "Pet delivery crates" rn, you saved me the trouble of making this exact PR, gg.
