### ISSUE TITLE
Blindfolds don't prevent visual phobia triggers from occuring.

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#49537]
## Reproduction:
* Roll space fear because phobias are broken and random now
* Think "I'll just birdbox this with a blindfold"
* Walk out onto main loop with your blindfold on
* Still be terrified of space
* Also be terrified of space when you're in crit and blacked out.

**Comment by cacogen** [comment]
The effects from phobias are too debilitating, and either your triggers aren't anywhere or they're everywhere.
