### ISSUE TITLE
Ghosts can move around separate of the camera while using Observe

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49547]
## Round ID:

Locally run code

## Testmerges:

n/a

## Reproduction:

1. Be a ghost
2. Orbit someone
3. Use Observe verb to Observe that same person
4. Use movement keys to move around your ghost or double-click to orbit other things

**Comment by Tharcoonvagh** [comment]
Intended (Unironically)

**Comment by nemvar** [comment]
Intended
