### ISSUE TITLE
APCs and keycard authentication devices aren't destroyed by bombs

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49546]
## Round ID:

Mucking around on locally run code

## Testmerges:

n/a

## Reproduction:

> ADMIN LOG:  Cacogen /(Razzle Dazzle) launched 5 pods towards  Cacogen /(Razzle Dazzle), Boom=|60|60|60|60| in Construction Area (39, 60, 2) ( JMP ). 
> ADMIN LOG:  Explosion with size (60, 60, 60, 60) in Construction Area (39, 61, 2) ( JMP ) 
> ADMIN LOG:  Explosion with size (60, 60, 60, 60) in Construction Area (38, 59, 2) ( JMP ) 
> ADMIN LOG:  Explosion with size (60, 60, 60, 60) in Construction Area (39, 61, 2) ( JMP ) 
> ADMIN LOG:  Explosion with size (60, 60, 60, 60) in Construction Area (38, 61, 2) ( JMP ) 
> ADMIN LOG:  Explosion with size (60, 60, 60, 60) in Construction Area (40, 59, 2) ( JMP ) 
> ADMIN LOG:  SMES deleted at Gravity Generator Room (55, 75, 2) ( JMP ) 
> The APC cover is knocked down! 
> ADMIN LOG:  The gravity generator was brought offline with no backup generator. Gravity Generator Room (60, 72, 2) ( JMP ) 
> Razzle Dazzle  has died at Space . 
> You feel slightly disoriented. That's normal when you're just a brain. 

![](https://i.imgur.com/3c8ZNHC.jpg)
![](https://i.imgur.com/1ybzVfX.jpg)

**Comment by Dennok** [comment]
Apc don't destroyed by burn too.

**Comment by Tlaltecuhtli** [comment]
apc are hardcoded to be only deconnable by deconstruction, maybe because powernets or old code shit

**Comment by Dennok** [comment]
What if we make destroying of apc destroy area?

**Comment by TheBonded** [comment]
I *think* this has been fixed

**Comment by SuperNovaa41** [comment]
Definitely has, it was runtiming recently from both explosions and fire, but these have been fixed and are properly destroyed now
