### ISSUE TITLE
Pacifists can crush cockroaches

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#49540]
## Testmerges:
Likely has something to do with #48836

## Reproduction:
* Be a pacifist
* Scrubber event
* Walk over cockroach
* Used to "carefully stepping over" the cockroach, instead, splats it.

**Comment by Fikou** [comment]
tbh even if i was a pacifist i would splat a cockroach

**Comment by cacogen** [comment]
yeah they're the worst
