### ISSUE TITLE
Donutstation overlapping layer 2 Distro and Turbine fuel manifolds

### ISSUE THREAD

**Issue by Atexhoffman** [tgstation/tgstation#49548]
## Round ID:
130883

## Reproduction:
As seen in the first image, the air supply manifold is sharing a tile and layer with the plasma tank's outlet in roundstart configuration.
![Distro 1](https://user-images.githubusercontent.com/61419551/75161117-ea06af80-5723-11ea-81fd-235236f45a6d.png)

 In the second image, after unwrenching the supply manifold, the whole distro pipenet is unable to be scanned via an analyzer or using the ghost gas scan.
![Distro 2](https://user-images.githubusercontent.com/61419551/75161188-0f93b900-5724-11ea-87bb-99a73712ddf0.png)

![Distro 3](https://user-images.githubusercontent.com/61419551/75161326-42d64800-5724-11ea-8e78-6ee11293ee19.png)

Local Host reproduction result: unwrenching the blue manifold below the beacon resulted in the grey manifold next to it becoming unwrenchable, however the distro pipenet was still functioning and scannable as intended.

**Comment by optimumtact** [comment]
![](https://file.house/lZWC.png)
