### ISSUE TITLE
Hardsuit description tries to get power cell charge without cell

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49564]
## Round ID:
Server revision compiled on:  
Master commit: 8d11e0ffa80e62104f3a3b4093f3e0cc75ef5c63 

## Testmerges:
The following pull requests are currently test merged: 
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45 

## Reproduction:
>

1. Remove cell from hardsuit (alt+click to open panel, ctrl+click to remove)
2. Examine hardsuit
3. "The power meter shows !invalid! charge remaining."

**Comment by Ty-the-Smonk** [comment]
Showing the power meter anyway seems intentional, could just be bad grammar
https://github.com/tgstation/tgstation/blob/a2ff959950a1f0e1b49dba7eb99082f14301a1d8/code/modules/clothing/spacesuits/_spacesuits.dm#L118-L130

**Comment by cacogen** [comment]
dumb but ok
