### ISSUE TITLE
losing a limb moodlet isnt removed if it gets attached 

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#49573]
it should clear on successful surgery and other ways of attach it

**Comment by trollbreeder** [comment]
It's not the not having the limb that makes you sad, it's the losing it in the first place that does. Not a bug.

**Comment by PKPenguin321** [comment]
I've got to agree with this not really being a bug. If the wording of the moodlet doesn't reflect that, just change it to something like "A limb was ripped off of my body... I can still feel the pain..." or something.

**Comment by cacogen** [comment]
people are not legomen tlal
