### ISSUE TITLE
Carp classic cigarettes do not contain carpotoxin

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#49588]
Issue reported from  Round ID: 130961 (/tg/Station Event Hall [ENGLISH] [US-West] [100% FREE LAG])

Reporting client version: 513.1511

Ran a local with the intent of mixing up some zombie powder, was checking cigarettes from every vending machine I could find with a signal ace 2 cartridge. The results from scanning said none of them contained the toxin, so I ground them all to verify, and did not receive any carpotoxin. Tested 132 cigarettes in this experiment.

![114 cigs](https://user-images.githubusercontent.com/51932756/75318404-94b3c680-5827-11ea-8202-8d4c491be681.png)

For the sake of being thorough I then hopped on sybil-2 to verify, and went through an additional 144 cigarettes, this time only checking them with the signal ace 2 cartridge, as I wasn't about to grind so many goddamn cigarettes again. 

![144](https://user-images.githubusercontent.com/51932756/75319890-bbbfc780-582a-11ea-94b6-12625762663d.png)

Not a single unit of carpotoxin in 276 attempts at a 5%? I can't believe I'm that unlucky.

**Comment by SkeletalElite** [comment]
Assuming you're not under any misconceptions about the probability. The chance of not having carpotoxin in 276 cigarettes is 7.1074704e-7 (.95^276). So no, youre probably not unlucky.

**Comment by Tlaltecuhtli** [comment]
try set it to prob 100 in your branch and then see if it work

**Comment by ArcaneDefence** [comment]
I have only the faintest clue what I'm doing here, so I'm not even sure if I'm doing it correctly, but changing this had no effect.

```/obj/item/clothing/mask/cigarette/carp
	desc = "A Carp Classic brand cigarette. A small label on its side indicates that it does NOT contain carpotoxin."

/obj/item/clothing/mask/cigarette/carp/Initialize()
	. = ..()
	if(prob(100))
		list_reagents = list(/datum/reagent/drug/nicotine = 15, /datum/reagent/toxin/carpotoxin = 3) //they lied

**Comment by Time-Green** [comment]
The prob check needs to be before the . = ..()
List reagents is a list of reagents to be added in Initialize, but if you do it after it’ll do absolutely nothing

**Comment by ArcaneDefence** [comment]
Yeah, that works. Thanks.
