### ISSUE TITLE
Ventriloquist Dummies require vow breaking for mimes to use

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#49582]
## Reproduction:
* Be mime
* Pick up dummy
* use the appropriate :r or :l 
* Be informed that you can't speak
* Break vow
* try again
* Dummy says: "Hi!"

I've seen people talk about how the mime should be able to use the ventriloquist dummy but given that the vow break moodlet is massively negative _and_ a mistype can cause you to not use the dummy and instead speak out loud, I feel like this is unintentional.

**Comment by kriskog** [comment]
Well if you want to be a talking mime, it only seems natural that you gotta break the vow.

Its a dupe though. #40969

@AnturK you made these right? Wanna weigh in?

**Comment by AnturK** [comment]
Fine by me to make this ignore the vow, saycode might be pretty hard to keep sane for this though.
