### ISSUE TITLE
infinite mats abuse

### ISSUE THREAD

**Issue by Ghilker** [tgstation/tgstation#49589]
step 1: have a recicler
step 2: be able to make 10mm ammunitions
step 3: feed them to the recicler
step 4:??
step 5: profit with infinite iron mats

**Comment by Tharcoonvagh** [comment]
![9lEROS0](https://user-images.githubusercontent.com/54288658/75343919-c796a280-5899-11ea-8bcc-038146e387c0.gif)

**Comment by HomocidlePancakes** [comment]
You don’t even need a recycler. You can dupe with a autholathe alone.

**Comment by kriskog** [comment]
The reason this works is you can print the bullet box for less than the material datum amount it will contain after printing. This should scale with the parts used to print it. I know the material datum prints do this, like the material toolboxes.

**Comment by benman347** [comment]
you can also use mech rcd to make infinite metal just build unweld repeat but its just metal so not worth doing anyway
