### ISSUE TITLE
Derelict Drones are unable to create the AI Core board.

### ISSUE THREAD

**Issue by CuteTuret** [tgstation/tgstation#49600]
Issue reported from  Round ID: 131052 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1508

Recently, the AI Core board requires a small amount of Bluespace crystals in order to get printed, the Derelict Vault does not contain any Bluespace crystals. I believe this is an issue as those drones are supposed to create AIs on the long term (the derelict has a drone speak book and Mother Drone AI law board)

**Comment by kriskog** [comment]
Yeah, very sad. I avoided giving drones bluespace and diamonds to prevent them from doing a lot of the shittier things on main station as well as partially limiting them to t3 parts. Some of thats been alleviated, but just adding an ai core board to the vault is an option.

**Comment by CuteTuret** [comment]
Off topic, but drones now get destroyed when leaving the derelict, if they are going to live in a spot of near total isolation, it might be a good idea to let them access T4 parts, every bit of rare metals saved is worth it.

**Comment by nemvar** [comment]
As sad as this is, it's not a bug.
