### ISSUE TITLE
attempting to put a broom inside a full backpack takes of all your clothes and puts them in a pile in front of you

### ISSUE THREAD

**Issue by Jimmius** [tgstation/tgstation#49627]
## Testmerges:  
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45
#49520: 'Codename Frosty Saviour- A New Medbay for Metastation' by EOBGames at commit 67b3db3c31

## Reproduction: basically what you do is:
1) have a broom
2) have a full bag
3) put broom into the bad
4) you are now nude, although it appears you are wearing a clone of your equipment, you can't actually interact with it until you pick it up off the floor

![image](https://user-images.githubusercontent.com/18462134/75588137-e9498280-5a6f-11ea-8ae8-7578fa2b3e97.png)

**Comment by PKPenguin321** [comment]
Related to https://github.com/tgstation/tgstation/issues/49519 or a dupe?

**Comment by Jimmius** [comment]
it must be related, i was able to unequip it without losing all my items, and was able to put the broom inside a non-full backpack successfully
