### ISSUE TITLE
Ghosts can use the debug chemical synthesizer

### ISSUE THREAD

**Issue by Pumpkinoe** [tgstation/tgstation#49633]
## Testmerges: #49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45
#49520: 'Codename Frosty Saviour- A New Medbay for Metastation' by EOBGames at commit 67b3db3c31

## Reproduction:

Be ghost
Click on debug chem machine
Use it despite being a spirit
Profit!
/yell at adminbus or something

**Comment by Ryll-Ryll** [comment]
I thought this was on purpose so you could mix stuff as a ghost while debugging. Is the debug chem synthesizer accessible normally with the new medbay?

**Comment by trollbreeder** [comment]
I think he was using the synthesizer in the thunderdome, ryll.
The thunderdome is an admin-only area for testing admin shenanigans and generally adminbussing around.

**Comment by nemvar** [comment]
I mean... it IS a debug machine right now. Don't test around on a live round. Start up your own local like a responsible jannie.
Feel free to change this as I don't think this was intended (machine originally wasn't meant as a debug tool) but currently this is only an issue if admins are adminbusing.
