### ISSUE TITLE
Box stations SM chamber is powered by MAGIC!

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#49641]
![image](https://user-images.githubusercontent.com/35217076/75610246-7ba95f00-5b20-11ea-8d40-c59ddcd1ae22.png)

Engineering is completly depowered but the SM chamber vents still have power.

**Comment by Tharcoonvagh** [comment]
hewry ur a weezurd

**Comment by GunHog** [comment]
The SM containment chambers are in a separate area. It is not controlled by the Engineering APC. This is also the case with Metastation. I do not know if these areas are controlled by an APC, or if they even need one.

**Comment by WarlockD** [comment]
I have been playing and bulding rooms for more than a year now and just noticed this in this issue.  There IS NO APC for the SM room, yet its powered.   The room must be set to a self powered turf for this to happen.  I bet if you install an APC next to the air alarm it will suddenly turn the vents off and need power then.

The question is if it should be fixed.  It would cause confusion if we wrap the existing SM room with enginering as you would have to hunt down the vents by number.  But putting an APC in there would require using a different witing layer to get to the station grid

**Comment by TemporalOroboros** [comment]
I'm pretty sure that the reason the SM room is always powered is to make sure that if the power goes out (such as with a powersink or lazy engineers) the SM doesn't enter an unrecoverable state where to turn it on you need the power for the scrubbers & vents but to get that power you need to turn it on.

**Comment by HomocidlePancakes** [comment]
>I'm pretty sure that the reason the SM room is always powered is to make sure that if the power goes out (such as with a powersink or lazy engineers) the SM doesn't enter an unrecoverable state where to turn it on you need the power for the scrubbers & vents but to get that power you need to turn it on.

You are wrong. There is no way an SM can enter a “unrecoverable state”. You can power it with solars, with a pacman or by throwing trash in to it if you are feeling dangerous.

**Comment by gonenoculer5** [comment]
Or shooting it with a gun!

**Comment by WarlockD** [comment]
I think it was more because in the long ago time, you couldn't route the wire in such a way to get an APC in there.  I get why its isolated, its so the Air Alarm only has those 3 vents and scrubbers in the list,  But to get an APC there you have to cross over the Radcollector lines.  Maybe it was to stop dumb antgs?  If you were to destroy that APC the vents and scrubbers die and you really don't have time to save the SM without it blowing.

**Comment by TheBonded** [comment]
fairly certain this was fixed
