### ISSUE TITLE
Gumballs cannot be placed on mask slots

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#49643]
## Reproduction:
With the addition of #49431 we now have gum that can be consumed like suckers by equipping them to the mask slot. However, this behavior has not been added to gumballs, you still have to eat them like normal food.

**Comment by ExcessiveUseOfCobblestone** [comment]
when is someone making everlasting bubble gum, the aesthetics of your character just popping bubbles while performing surgery is funny.
