### ISSUE TITLE
Heckzone Brewery not working

### ISSUE THREAD

**Issue by Silahnus** [tgstation/tgstation#49652]
## Round ID: 
13124

## Reproduction:
It occurs when going to the Heckzone Brewery. The hologrids work for the most part on the boxes, however after the fizzling animation finishes the locked box appears for a few frames before disappearing altogether without dropping anything (including the keycards). Also, when used the hologrids can be picked up & moved around but I've got no clue if that's intentional or not.
[https://i.imgur.com/W1jKxtn.png](url)

Another issue is with there not being enough grids to open up all of the boxes. I was told that there may be some in the Manager's Room, but upon closer inspection none can be found.
[https://i.imgur.com/78JHbE6.png](url)

Finally, in the freezer room there's a small section of space where a Pipe is, that doesn't freeze over. Consequently, it's an impassable location without breaking open the fridge or going to long way around and stepping on another mine.
[https://i.imgur.com/c2ZWt7f.png](url)

It looks like a really fun ruin to go through properly, but in its current state it's basically impossible to complete without blowing up walls.

**Comment by ArcaneMusic** [comment]
Well, answering some questions before testing locally,
A. You are right in that the grid should be anchored and unmovable, so I'm not sure how you managed to pick those up. It should be that you should move the boxes over the grid, box fizzles out, and it drops a reward with the hologrid changing sprite. None of those grids have the right icon_state assuming they were opened correctly.

B. There's one hidden grid in that image, in the top right of the office.

C. In the freezer room, there is a portion of the pipes that go through a wall as opposed to being on the floor, which means that they don't have contact with the cold watervapor, and don't freeze over. The challenge in the freezer room is working around both the freezing cold temperatures, ice, and simutaniously getting the 2 holoboxes out while dealing with the water vapor from the mines.

That said, I'll do some testing on my local to see if something's gone wonky.

**Comment by nemvar** [comment]
Sadly pictures are broken. You can embed images directly via github (usually by click-dragging) and that's preferable to something like imgur.
