### ISSUE TITLE
Flux anomaly cores can't be used to make phazons

### ISSUE THREAD

**Issue by Kaptinalexander** [tgstation/tgstation#49669]
Issue reported from  Round ID: 131353 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE]) 

^it was actually the round before this one

Reporting client version: 513.1507

Like the title says, I was attempting to make a phazon, got to the last step where you're supposed to insert the anomaly core. I go to put it in and nothing happens, the core doesn't do anything. 

I tried swapping my intents to harm and help to see if that changed anything, but nothing happened. I didn't even get the message that I hit the phazon with the core when I swapped to harm intent. 

I did notice though for the first time that it was attachable to things like signalers, not sure if that's new or it was part of the bug.

**Comment by GravitronBlue** [comment]
Blame #49448 as this is actually intentional.

> The Phazon now specifically requires a Bluespace anomaly core. This functions better with how the tech works in lore and also will cut down on the number of them built. Remember, they're supposed to be quite rare due to how good they are.

**Comment by nemvar** [comment]
As pointed out, this is intended although I don't really agree with it.
Cores being attachable to signalers is odd but not broken behaviour. They will essentially act like a signaler on a set frequency.
