### ISSUE TITLE
Fluid Ducts do not connect to other layers using the wrench.

### ISSUE THREAD

**Issue by WarlockD** [tgstation/tgstation#49660]
## Reproduction:
1. Place a flud duct on a tile
2. Place another fluid duct on a tile adjacent at a different duct layer.
3. With empty hands, click and drag between both ducts.  You will get a message saying you need a wrench.
4. Put a wrench in your hand and do it again.
5. Nothing happens.

Checked to see if they were connected but just not visually updated and nope, Having one side a Synthesizer and the other a tank, nothing was flowing though any of the pipes.

Be nice if this worked or if you could change the input/output layer on the plumbing devices.  Make it much easier to make smaller networks.

**Comment by Time-Green** [comment]
The click drag with a wrench was intended for different color pipes, the message is the bug.

I will probably let machines change layer at some point, but it’d require some reworking or really ugly code
