### ISSUE TITLE
Clicking on empty tiles around you with a lit welder expends fuel for every click

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#49664]
Issue reported from  Round ID: 131337 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1511

To replicate:

1. Turn on welder
2. Click an empty tile a bunch
3. Your welder is now empty

**Comment by ShizCalev** [comment]
don't do that then

**Comment by nemvar** [comment]
I mean... it could be argued this is a player feedback issue because the game probably assumes you are trying to repair the turf. Exact intended behaviour is not clearly defined.

**Comment by Tlaltecuhtli** [comment]
it nerfs welderfuckos so its good

**Comment by ATH1909** [comment]
> don't do that then

But what if you're trying to, say, fight a changeling or a blob with a welder?

**Comment by cacogen** [comment]
it's not unintended functionality, it's a feature

**Comment by timothymtorres** [comment]
@TheBonded this fix is a little more complicated but should be easy to knockout. Let me know if you need help.

**Comment by necromanceranne** [comment]
> What do you think @necromanceranne?

That seems like it'll work. Literally no reason for the proc to come before as far as I can tell rn. I'll give it a test tomorrow night. Next few days is a bit busy for me.
