### ISSUE TITLE
You can move upwards as a human onto catwalks

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#49667]
Move upwards verb ascends you magically to the catwalk above you (if there is one) on multi-z maps. This does not seem like intended behavior.

**Comment by nemvar** [comment]
This happens because catwalks are merely anchored structures and not turfs if someone wants to fix this.

**Comment by Dennok** [comment]
All spacemans on station passed a short course of agile movement. And are able to lift themselves by 3.5 meters

**Comment by Dennok** [comment]
oh, you can  do it withno catwalk. from arrival shuttle. Tested.

**Comment by Dennok** [comment]
#51155 dont fix this. Reopen please.
