### ISSUE TITLE
Holodeck blood unwashable

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#49673]
Issue reported from  Round ID: 131367 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

-activate winter wonderland module
-kill penguin for BLOOD
-become bloody
-shower and stay messy(soap works fine apparently)
-cry when your colleagues make fun of you

**Comment by optimumtact** [comment]
it's virtual blood you can't wash it off

**Comment by LemonInTheDark** [comment]
This doesn't replicate anymore, most likely was totally unrelated to holodecks
