### ISSUE TITLE
Spontanious Dezombification.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#49678]
Round: 131376
IC name: You Are Already Touhou

So this happened near the end of the round. Got bitten, died, became a zambie. Some time after end up going in to crit due to heat and succumb. My body turns back in to a human and I stop being a zombie.

**Comment by XDTM** [comment]
the zombie tumor reverts to the old species when destroyed, so maybe organ decay could have been the cause, or maybe the head got dusted if you were burning

**Comment by HomocidlePancakes** [comment]
I wasn't on fire, just hot.

**Comment by msgerbs** [comment]
I'm going to close this as a duplicate of #51330 even though it's the older issue just because that issue has more detail in it.
