### ISSUE TITLE
Geneticists have no access to bottom doors and maintenance on new multi-z Donutstation

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#49688]
## Round ID:
131402

## Testmerges: 
#49476 : 'Adds tackling (VIDEO INSIDE)' by Ryll-Ryll
#49579 : '[READY]Return of the dwarves Mk.2 : Oranges approved - ashlizards removed ' by EdgeLordExe, 
#49065 : 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction: 
Spawn in as Geneticist on new multi-z Donutstation, Try and walk into bottom door or the maintenance to your lab, you have no access and cannot get out, but you have access on the top doors.

**Comment by TheVekter** [comment]
I didn't do it.

No, for real, I didn't touch Genetics on Donutstation when I moved everything. I'll look at this in the morning if nobody else has touched it.

**Comment by redguy999** [comment]
i believe it was like this before it got updated

**Comment by Dennok** [comment]
As i memorize, here is no down door in genetics lab before multi z
