### ISSUE TITLE
Saying *beep while in a transit tube ejects you from it

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#49682]
Issue reported from  Round ID: 131397 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1508

Borg player reported and showed this to me over ahelp, pretty weird

**Comment by Ty-the-Smonk** [comment]
Does the same thing happen with simple mobs and carbons?

**Comment by 4dplanner** [comment]
lol

**Comment by wesoda25** [comment]
🤔

**Comment by redguy999** [comment]
also it seems to eject anyone else in the tube.

**Comment by XDTM** [comment]
only *beep or any emote?

**Comment by carshalash** [comment]
It didnt work, how do you get me excited for something that works as intended.

**Comment by redguy999** [comment]
only *beep

**Comment by HomocidlePancakes** [comment]
What. How?

**Comment by redguy999** [comment]
> Does the same thing happen with simple mobs and carbons?

yes, in fact, even if you arent suppose to be able to say it, you get ejected from the tube.
accidently did this as captain recently

**Comment by Akrilla** [comment]
Tested this today and couldn't reproduce, was it fixed?

**Comment by cacogen** [comment]
in a previous life i made an issue report saying clicking close on a certain menu toggled internals. turned out the close button was above the internals icon. this reminds me of that

**Comment by dragomagol** [comment]
Unable to reproduce.
