### ISSUE TITLE
Cutting out the floor beneath you doesn't drop you on multi-z

### ISSUE THREAD

**Issue by Ryll-Ryll** [tgstation/tgstation#49685]
## Testmerges:
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45
#49579: '[READY]Return of the dwarves Mk.2 : Oranges approved - ashlizards removed ' by EdgeLordExe at commit 1d517bd8b5
#49476: 'Adds tackling (VIDEO INSIDE)' by Ryll-Ryll at commit 32fad5b299

## Reproduction:
[![dreamseeker_2020-03-02_22-00-08.png](https://i.imgur.com/tljxMj0.png)](https://i.imgur.com/tljxMj0.png)
Step 1: Be on the not-first floor
Step 2: Remove the floor you're standing on (say, a catwalk)
Step 3: Hover as long as nothing moves you

**Comment by HomocidlePancakes** [comment]
This isn’t an issue exclusive to multi-z. If you stand on a plasmeme and take off his suit, you won’t be set on fire. Probably there are more cases that we don’t know about.

**Comment by Dennok** [comment]
Change head to "Cutting out the catwalk beneath you doesn't drop you on multi-z"
Or test it with RCD and real floor/plating.

**Comment by PKPenguin321** [comment]
Perhaps updating a turf should call Crossed() on its contents

**Comment by Dennok** [comment]
> Perhaps updating a turf should call Crossed() on its contents

I think yes.

**Comment by optimumtact** [comment]
I seem to remember we tried that, and it caused a bunch of bugs that just were not worth the hassle of fixing.

**Comment by PKPenguin321** [comment]
Crossed() might be too general then. Is there an individual proc that handles falling? Call that

**Comment by Ryll-Ryll** [comment]
Is there any reason you can't just call zFall() on the turf for each of the contents

**Comment by PKPenguin321** [comment]
Yeah, you get it

**Comment by cacogen** [comment]
@Dorsisdwarf you should add this one to the multi-z stations milestone instead

**Comment by projectkepler-ru** [comment]
@optimumtact  this is no longer applicable

**Comment by Sealed101** [comment]
^ tested, can no longer cosplay looney toons gravity
