### ISSUE TITLE
Donutstation Second floor has the basic space texture, no matter what your parallax setting is.

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#49687]
## Round ID:
131402

## Testmerges:
#49476 : 'Adds tackling (VIDEO INSIDE)' by Ryll-Ryll
#49579 : '[READY]Return of the dwarves Mk.2 : Oranges approved - ashlizards removed ' by EdgeLordExe, 
#49065 : 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:
On Donutstation, use verb move-upwards and go into space. The space texture is the generic no parallax texture, instead of what setting you have set.

**Comment by Dennok** [comment]
Same as #49668

**Comment by PKPenguin321** [comment]
Dupe
