### ISSUE TITLE
Surgery is completely fucked on Manuel

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#49691]
Confirmed on round #131411 but it's been on multiple rounds so far.

This is only happening on Manuel, which is currently on BYOND 513.1513. I cannot replicate this on local but can in-game. Using any surgery tool fails to actually do anything, it just says it's doing the step and no progress bar appears.

This should probably be red label since it's now relatively impossible to bring anyone back if they can't be defibbed.

**Comment by Tharcoonvagh** [comment]
You sure your intent wasnt on disarm?

**Comment by TheVekter** [comment]
100% sure, multiple people are reporting the same issue.

**Comment by Tharcoonvagh** [comment]
Aight

**Comment by Ty-the-Smonk** [comment]
I remember having this issue a while back with alien surgery tools

**Comment by TheVekter** [comment]
It's fixed. Some sort of BYOND issue
