### ISSUE TITLE
poly is dead and alive, unwrenched pipes are pointing multiple directions, and morphs are tranformed and not at the same time

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#49697]
Issue reported from  Round ID: 131452 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1511
medhub and examine poly say that they are dead, yet i see them flying in the air, and dead on the floor, both on the same tile, unwrench pipes appear to both be going north to south and east to west at the same tile, and morphs apear untransform and tranformed at the same time.
(hope this is correct)

**Comment by redguy999** [comment]
this appears to be a purely visual glitch, which is fine except for the morphs.
could also be a problem on my end, but disconnecting and reconnecting didnt work

**Comment by PKPenguin321** [comment]
Clear your BYOND cache: http://www.byond.com/forum/post/29715

**Comment by NoxVS** [comment]
its not a BYOND cache issue, everyone on Manuel is reporting it. It happens to everything. Its some overlay issue or something. Items are on top of your sprite despite clicking on them actually clicking on you. Its difficult to explain well

**Comment by Dorsisdwarf** [comment]
lots of bitching about whatever caused this

**Comment by willox** [comment]
happens for me since 1aeb72b
