### ISSUE TITLE
F.R.A.M.E. Cartridge needs fixin'

### ISSUE THREAD

**Issue by Vanadiom** [tgstation/tgstation#49705]
## Round ID: 
13145

## Testmerges:
#49579 
#49065 

## Issue:
So In round 13145 I was a traitor (Ceasar Tyrian) and framed my target (Maleena Kyriegala) to make her seem like traitor, for easy executing. I made another person check this and they noticed, that the (fake) uplink did not have access to the role restricted items that  she should have (for Paramedic). Secondly, getting it to open was another hard thing to achieve. I tried opening the uplink terminal in her PDA by using another virus file, which I did not know didn't work. After I searched through the logs to find the original code, ONLY that one worked. The second problem I might disregard as it would imply that changing this could really ~~fuck~~ mess with actual traitor PDAs.

## Reproduction:

~~Problem~~ Oddity 1:
1. Find person that would have role-restricted Items, if they were traitorous.
2. Frame them.
3. Take PDA and notice, ~~they MUST be framed,~~ that your own role restricted items appear.

Problem(?) 2:
1. Find person ~~that would have role-restricted Items, if they were traitorous.~~
2. Frame them.
3. Take PDA and close uplink.
4. Repeat step 2 until satisfied.
5. Look at PDA finding no uplink, not being able to open it with the codes that aren't the first one. ~~Cry.~~

**Comment by ArcaneDefence** [comment]
Uplinks do not show you the role restricted items of the person that owns the uplink, but instead shows you the role restricted items that you have access to yourself.
Here's pictures where the CMO is a traitor with a real uplink, buying a FRAME cartridge, infecting the clown, showing that the clown can buy clown items with the CMO uplink, and the CMO can see CMO items from the FRAME uplink.
![1](https://user-images.githubusercontent.com/51932756/75861210-4d46b080-5dba-11ea-821b-289cfe44df0d.png)
![2](https://user-images.githubusercontent.com/51932756/75861215-4f107400-5dba-11ea-9ffc-37a50edf21e3.png)

**Comment by Vanadiom** [comment]
Okay, did not know about the first one, also, the check would maybe cause the person owning the F.R.A.M.E Cartridge to know who is traitorbuddy, based on who cant receive a file.

**Comment by ArcaneDefence** [comment]
That's a concern, sure, but if the check's made in a way that just checks to see if you've already sent the virus to that PDA it shouldn't be a problem I'd imagine. So you'd be able to send the virus to a traitor uplink as you can now, but still prevent the user from dumping all five viral files into one PDA when four of them do literally nothing

**Comment by Angustmeta** [comment]
The framed uplink should become unlocked from the virus but I don't think it works. Pretty pointless to frame a fresh prisoner about to be searched if the uplink can't be found.

**Comment by lordpidey** [comment]
Hey, the things mentioned were intentional.

You can't have two unlock codes on the same PDA, that would require massive refactoring.

So what I did is if you attempt to frame a PDA that already has an uplink, it opens a temporary uplink, which goes away when closed, so the new passphrase won't work.

That said, just because this was intentional doesn't mean it's the best way, you bring up some good points.

**Comment by lordpidey** [comment]
I fixed this in #50248

Please close this issue.
