### ISSUE TITLE
Potted Plants Have the Random Potted Plant Sprite on Deltastation.

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#49701]
## Testmerges:
#49476 : 'Adds tackling (VIDEO INSIDE)' by Ryll-Ryll
#49579 : '[READY]Return of the dwarves Mk.2 : Oranges approved - ashlizards removed ' by EdgeLordExe,
#49065 : 'Disable library machine uis' by optimumtact

## Reproduction:
Spawn in on delta station, some potted plants have the sprite of the random potted plant sprite.

![image](https://user-images.githubusercontent.com/56656478/75830292-6c275180-5d7e-11ea-9a64-72e18671ad1c.png)

**Comment by NoxVS** [comment]
this is caused by the overlay problem lots of people are having I believe

**Comment by PKPenguin321** [comment]
Yes, likely part of https://github.com/tgstation/tgstation/issues/49697

**Comment by willox** [comment]
happens for me since https://github.com/tgstation/tgstation/commit/1aeb72b2a9c06c4d1d4d34351411714663bc2c51
