### ISSUE TITLE
hecksuit has thermoregulation

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#49716]
hecksuit has thermoregulation, doesnt seem like it should have it, looking at how its a primal suit of armor, that doesnt even function properly as a spacesuit

**Comment by HomocidlePancakes** [comment]
Hecksuit is DOOM MARINE armor. It’s not primal you nerd

**Comment by nemvar** [comment]
hecksuit is fucking lavaproof, not a strech to say that it can be frostproof.
