### ISSUE TITLE
Using the "Move Down" or "Move Upwards" verbs as a teleporting creature simplemob reveals you

### ISSUE THREAD

**Issue by catswerecatswerethecats** [tgstation/tgstation#49715]
Issue reported from  irrelevant
Reporting client version: 513.1511

title
You become revealed as if using your ability again, only without actually using it. Using the abilitiy again does nothing and you need to use it twice to go into your invisible jaunt form.

**Comment by ExcessiveUseOfCobblestone** [comment]
from jaunt or like revenant?

**Comment by HomocidlePancakes** [comment]
wat. Are you talking about revenants?

**Comment by tralezab** [comment]
He means nightmare jaunt.

**Comment by catswerecatswerethecats** [comment]
it's the creature (with the teleport ability) from xenobio, but other jaunts might be fucked as well, I haven't tested them though
