### ISSUE TITLE
Latejoining prisoners are back.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#49711]
Round: 131506

**Comment by Bokkiewokkie** [comment]
Maybe someone opened the job position on the HoP's id console

**Comment by Time-Green** [comment]
Can confirm, I was a late joining prisoner. It was marked green so it may've been HoP fuckening

**Comment by HomocidlePancakes** [comment]
There was only one prisoner on station and you have 2 slots by default, but it was probably HoP or the bureaucracy event.

**Comment by HomocidlePancakes** [comment]
@ShizCalev 
Here are possible reproduction methods:
1)Fucking with job slots as HoP.
2)Bureaucracy even fucking with job slots. 
3)The issue is exclusive to pubby station.
4)All of the above at the same time.

**Comment by kriskog** [comment]
#49886
