### ISSUE TITLE
Custom vendor will mark some items prices as 0 and not let you pull them out

### ISSUE THREAD

**Issue by MoonFalcon** [tgstation/tgstation#49723]
Issue reported from  Round ID: 131524 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1512

Not sure how it is caused / what triggers it, but I put Soylen Viridians and Hawaiian pizza in a custom vending machine and both showed up with a price of 0 and I could not interact with them at all after that point

**Comment by Tlaltecuhtli** [comment]
did you set the price to 0

**Comment by antropod** [comment]
Items that contain /proper and /improper text cause this bug, hopefully fixed in #60668
