### ISSUE TITLE
Synth banana and broom can drop "off hand" symbol

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#49722]
Issue reported from  Round ID: 131518 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

"OFF-HAND" symbol appears to be "drop-able" during certain conditions.

##Reproduction
Here is the method as given by the user it occurred too:
-Create synthetic banana skin from honkmother staff
-Dual wield the broom, so that it is in both hands
-Telepathically slip person who is dual wielding the broom
-When they slip they drop the broom AND the "OFF-HAND" symbol as well.

Pictures:
![Image of offhand](https://cdn.discordapp.com/attachments/585862469508005888/684873538309586954/unknown.png)

![Image of right click](https://cdn.discordapp.com/attachments/585862469508005888/684873577606283357/unknown.png)

**Comment by ATH1909** [comment]
telepathically or tele_kinetic_ally?

**Comment by ATH1909** [comment]
are you sure that this is tied to the bananium wand?

**Comment by ATH1909** [comment]
... what even IS a bananium wand?

**Comment by peoplearestrange** [comment]
> telepathically or telekinetically?
I mean technically telekinetically, but now you're being pedantic over my wording. "moving stuff with the genetics mind trait thing"

> are you sure that this is tied to the bananium wand?
> ... what even IS a bananium wand?
I put it in the report as the banana's used to slip the person were created USING the staff.
My mistake though its a staff "Staff of Honkmother"
obj/item/gun/magic/staff/honk

I'll edit the post

**Comment by NoxVS** [comment]
Staff doesnt make the  bananas you slip on, you can make them with bananium or the upgraded clown shoes fueled with bananium

**Comment by cacogen** [comment]
off-hand should be a poster or something

**Comment by nightred** [comment]
Interesting, i am looking into this.
