### ISSUE TITLE
Coal pile no sprite

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49721]
Issue reported from  Round ID: 131518 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1508
![](https://i.imgur.com/8cR97QJ.png)
![](https://i.imgur.com/Mjm7Mub.png)

**Comment by Bokkiewokkie** [comment]
Yeah was going to open a PR with some missing sprites including this one in it soon:tm:
![image](https://user-images.githubusercontent.com/43698041/75934969-3cf80980-5e7e-11ea-9773-9aa30c69b5c6.png)
