### ISSUE TITLE
Mafia names prevent accessing an individual's player panel from the player panel.

### ISSUE THREAD

**Issue by Dezupher** [tgstation/tgstation#49744]
Round ID: 131570

Reporting Client Version: 513.1513

## Reproduction:
Attempt to mouse over someones name on the player panel after they acquire a Mafia nickname.

## Pictures: 
![playerpanel](https://user-images.githubusercontent.com/61841247/76003675-3d63c500-5ebd-11ea-8a69-e65284380dcf.jpg)

![playerpanel2](https://user-images.githubusercontent.com/61841247/76003789-65ebbf00-5ebd-11ea-997c-dbe7e0ad4933.jpg)

**Comment by necromanceranne** [comment]
Becoming a mobster now protects you from administrative backlash.

**Comment by redguy999** [comment]
what went wrong in the code?
