### ISSUE TITLE
Loot spawner IED sprites don't show the can, only the wrap and the bubbles

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49754]

**Comment by Tlaltecuhtli** [comment]
this  happen 100% for mapped ones (missing icon since its from which soda can it was crafted with?) , does it happen for handmade ones too?

**Comment by ShizCalev** [comment]
handmade ones are fine, this is only for loot spawner ones.

**Comment by tralezab** [comment]
Yeah actually because this doesn't change anything dmi wise to fix

**Comment by ShizCalev** [comment]
![image](https://user-images.githubusercontent.com/6209658/76134381-cc6efb00-5feb-11ea-8a61-2b1f4f8e232e.png)
fix i have that works, but it seems really hacky and i'd like to see someone come up with something a little more elegant if possible. will open it as is if there isn't another fix in a couple days.

**Comment by cacogen** [comment]
I doubt there will be!
