### ISSUE TITLE
HARS mutation, despite description, is incurable.

### ISSUE THREAD

**Issue by Rasselbok** [tgstation/tgstation#49758]
## Round ID: 131607

I jabbed myself with a HARS injector, having read the description that it was curable (but might kill me in the process). I took mutadone, nothing happened. I had it removed in the mutation scanner. Nothing happened (and it came back spontaneously later). Even with the mutation 'gone' from the mutation scanner, i was still unable to get a new head via robotics, either.

The HARS was not, as far as I could tell, reinforced.

Being injected with HARS essentially permanently and incurably both blinds and deafens you and makes you unable to be rebodied or borged or possibly even revived due to no longer having a brain.

Even an aheal only restored sight and sound, but i still had no head and as such could not do things like wear a radio.

**Comment by PKPenguin321** [comment]
@tralezab

**Comment by Dennok** [comment]
Maybe magick (pride) mirror can help. 
Or slime/lizard or someother mutation.

**Comment by tralezab** [comment]
fix up very shortly
