### ISSUE TITLE
Prosthesis from Prosthetic Limb quirk starts disabled with no damage

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49763]
Issue reported from  Round ID: 131616 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1508

I have the trait that makes one of your limbs a prosthesis. Straight after spawning I got the "You look at your arm and sigh." message trying to use it. Switching to the other hand made the disabled icon appear on the prosthetic one.

**Comment by Tharcoonvagh** [comment]
Maybe intended? Not sure

**Comment by Dennok** [comment]
Not intended prothesis roundstart arm be inactive.

**Comment by CRITAWAKETS** [comment]
Also happens when augmenting arms. The only fix is to amputate the arm, then put another one back on.

**Comment by Timberpoes** [comment]
> Also happens when augmenting arms. The only fix is to amputate the arm, then put another one back on.

/code/modules/surgery/limb_augmentation.dm line 53 also interacts with the code changes in PR #49062 - I suspect this is a similar issue to my fix, where the person temporarily has an extra limb. My proposed fix won't solve this new issue, it only touches quirk prosthetics specifically. I'll see if I can dig further for an elegant solution.
