### ISSUE TITLE
You can attempt to climb up and down while dead

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#49761]
## Round ID

[Round ID] 131612

## Testmerges:

#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45
#49476: 'Adds tackling (VIDEO INSIDE)' by Ryll-Ryll at commit 32fad5b299

## Reproduction:

Attempt to climb up a wall while dead. Fall down. Spam this. Become the meatgrinder. Cry.

(Please don't shoot me bagilites, you'll have at least a couple hours with this.)

**Comment by Tharcoonvagh** [comment]
Climb up a wall? What do you mean

**Comment by trollbreeder** [comment]
Fuckup of the year 2020
