### ISSUE TITLE
Warm donk pockets don't cool

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49782]
Issue reported from  Round ID: 131669 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1508

Or at least their names don't lose the warm prefix

**Comment by HomocidlePancakes** [comment]
I thought it was just fluff.

**Comment by cacogen** [comment]
I thought they healed you if you ate them within seven minutes of heating, otherwise they cooled

**Comment by PKPenguin321** [comment]
You're a couple years outdated on that

**Comment by Dennok** [comment]
Why not fix it propertly cooling?

**Comment by PKPenguin321** [comment]
Feel free to, but it's not a bug
