### ISSUE TITLE
Survival knife and flashlight attached to a PKA rotate separately when thrown

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49783]
Issue reported from  Round ID: 131669 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1508

I'm guessing this happens with all sprite overlays.

https://i.imgur.com/b9sFjCK.gifv

**Comment by timothymtorres** [comment]
Duplicate of #37303
