### ISSUE TITLE
Xeno hunters cannot slash doors down.

### ISSUE THREAD

**Issue by KomradeSpectre** [tgstation/tgstation#49785]
Issue reported from  Round ID: 131681 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1511

Xenomorph Hunters cannot slash door down once it gets to the state where it is falling apart but not broken to the assembly. They are unable to interact with it at all.

**Comment by HomocidlePancakes** [comment]
Broken doors are still doors. They just have all the wires cut and a slightly different sprite. Also, due to the cut wires they are bolted.

**Comment by dragomagol** [comment]
Appears to have been fixed
