### ISSUE TITLE
Nightmares Spawning w/o Armblades

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#49786]
Issue reported from  Round ID: 131686 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

Had to manually give a nightmare a nightmare heart, because their light eater was not coming out.

**Comment by PKPenguin321** [comment]
It was spawned by the event?

**Comment by KomradeSpectre** [comment]
Can't reproduce it. 

- Tried triggering the event 5 different times, and the person that was assigned got the light eater. 
- Tried setting their race from human to nightmare and they got a light eater. 
- Tried spawning in a nightmare manually, and also tried spawning a shitload of them to see if it was one off.
- Tried the pride mirror nightmare transformation a few times.

None had the issue, so it's probably something specific to the round.

**Comment by Daxxed** [comment]
Could reproduce it perfectly in every single way you mentioned
Are you sure your files were up to date ?

**Comment by KomradeSpectre** [comment]
Positive, and I even had another person (@Armhulen ) testing with me. Do you have YOUR files up to date?

**Comment by Daxxed** [comment]
Yeah updated them just now after seeing a dupe of this PR and could not find a light eater in any possible way

**Comment by kriskog** [comment]
Not sure how you couldnt reproduce, but you were probably on outdated master. Definetely an issue, see #50064

**Comment by KomradeSpectre** [comment]
At the time of reporting my findings, it was not broken. @tralezab can attest to this. Regardless, if it's broken now then that's that.

**Comment by Daxxed** [comment]
The PR that broke it was merged 13 days ago while your post is only 10 days old but I'll give you both the benefit of the doubt and say another PR is the cause, have yet to find it though.

**Comment by ATH1909** [comment]
Reopen this, then.

**Comment by kriskog** [comment]
You dont need to post proof or anything, noone cares. New issue is still open, its tracked, everything is okay.
