### ISSUE TITLE
Container overlays on drink dispensers don't clear

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49780]
Issue reported from  Round ID: 131669 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

![](https://i.imgur.com/F9Pfdwz.png)

Reporting client version: 513.1508

**Comment by optimumtact** [comment]
this was probably broken during the vis overlays fucky wucky

**Comment by cacogen** [comment]
still broken my guy

**Comment by Dennok** [comment]
This only for drink dispenser?
Chem dispenser dont have this problem?
