### ISSUE TITLE
Gas overlays are layered incorrectly

### ISSUE THREAD

**Issue by Ghilker** [tgstation/tgstation#49797]
![ada](https://user-images.githubusercontent.com/42839747/76152453-13c6bb80-60c0-11ea-86b6-37ab0fddc511.PNG)

**Comment by LemonInTheDark** [comment]
I don't understand, pictures do not compile, and I do not play. Please explain this more clearly, preferably in hex to utf-8.

**Comment by Ghilker** [comment]
Uhh gas overlay are messed up, the canisters, the light, the camera and the black thingy are like floating over the gases. The same happens with some pipes (heat exchange pipes at least from what I saw)

**Comment by LemonInTheDark** [comment]
fucking mood, thank you for elaborating.

**Comment by SpaceManiac** [comment]
Please title your tickets descriptively
