### ISSUE TITLE
Nerf xenos

### ISSUE THREAD

**Issue by Something1sWrong** [tgstation/tgstation#49791]
Issue reported from  Round ID: 131712 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507

As of right now, Xenomorphs are super fast, acid-spitting, instant stun disarming, healing weed planting killing machines that are space proof, don't need oxygen and can extremely easily create many, many more human-controlled xenomorphs, even using monkeys or monkey men from genetics and viro. Please fix

**Comment by cacogen** [comment]
this except 7 years ago

**Comment by RaveRadbury** [comment]
This is not the area for balance discussion. Please move this discussion to the forums.
