### ISSUE TITLE
Beach bum grill has no fuel

### ISSUE THREAD

**Issue by Farquaar** [tgstation/tgstation#49801]
Doesn't spawn with fuel, and there's no fuel in the ruin to refill it.
![image](https://user-images.githubusercontent.com/44147031/76153454-27f7c200-609a-11ea-9c9e-b1d6439d2377.png)
I just want to grill for God's sake

**Comment by Fikou** [comment]
the drink vendor should have monkey energy for filling the grill

**Comment by Tharcoonvagh** [comment]
Theres a crate with some coal

**Comment by Dennok** [comment]
![coal](https://user-images.githubusercontent.com/7734424/76161675-47482b00-613e-11ea-892c-fdf985c8fb44.png)
![grill](https://user-images.githubusercontent.com/7734424/76161677-48795800-613e-11ea-9767-e2cf0f543716.png)
