### ISSUE TITLE
fake plasma flood from RDS(reality disassociation syndrome) blocks clicking on things

### ISSUE THREAD

**Issue by joybod** [tgstation/tgstation#49806]
Issue reported from  Round ID: 131738 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

**Comment by TemporalOroboros** [comment]
This is not unique to the reality disassociation syndrome. This happens with every plasma flood hallucination. I think it's putting an overlay on the turfs which is eating all the clicks and redirecting them to the turf.
