### ISSUE TITLE
ling headless revive bugged

### ISSUE THREAD

**Issue by Timonkeyn** [tgstation/tgstation#49802]
Issue reported from  Round ID: 131726 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1511

basically, i got decapitated as ling and my ghost was in my brain instead of my Body, making me unable to revive

**Comment by PKPenguin321** [comment]
HARS again if I had to bet

**Comment by redguy999** [comment]
HARS is bugged
