### ISSUE TITLE
H.A.R.S bug

### ISSUE THREAD

**Issue by Shiraizawa** [tgstation/tgstation#49816]

**Comment by Tharcoonvagh** [comment]
Dupe

**Comment by ATH1909** [comment]
Did you become a flyperson, by any chance?

**Comment by Shiraizawa** [comment]
I have no idea to be honest

**Comment by ATH1909** [comment]
Does this also happen with changelings who go through teleporters without their heads?

**Comment by kriskog** [comment]
@tralezab this is your thing yeah?

**Comment by ArcaneDefence** [comment]
![image](https://user-images.githubusercontent.com/51932756/100700089-e3affe80-3359-11eb-9c94-67c9e96a2c12.png)
@tralezab This is still an issue, and I figured you'd know better than me with this stuff
