### ISSUE TITLE
RCD silo link function should tell you it needs linking to a silo with a multitool

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49812]
Issue reported from  Round ID: 131760 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1508

Not a bug but in my opinion having to rely on other players' knowledge or looking at the code is not desirable

**Comment by Dennok** [comment]
Something go wrong and it just sailent when you try use unlinked RCD in link mode.

**Comment by cacogen** [comment]
actually this issue sucks

**Comment by PKPenguin321** [comment]
You're right though, player feedback good

**Comment by redguy999** [comment]
maybe just add a message that displays when you attempt to use it without it being linked that says "The RCD isn't linked to an ore silo"or something like that.
that's my 2 cents
