### ISSUE TITLE
Lavaland elites can't damage mechs

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#49814]
Round id: I forgot, but it was yesterday on manuel

I was a broodmother and killed my summoner, but then came along a mech who could not be damaged by me at all. All the normal stuff happened, it's just that they didn't take any damage at all. It was a gygax and they didn't have a repair droid

**Comment by Pumpkinoe** [comment]
Dupe of #48302 ?

**Comment by Time-Green** [comment]
Seems like it

**Comment by ATH1909** [comment]
Honestly, I know that lavaland elites were intentionally not given object damage in their original PR, but I think that it'd honestly be fine to give them a reasonable amount of object damage (enough to smash through doors?).

**Comment by Arturlang** [comment]
It was intentional for them to not get object damage so they couldnt damage the station, i do think. Should probably do something about them being unable to attack mechs though
