### ISSUE TITLE
CODEWORDS ARE BROKEN AS SHIT

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/tgstation#49824]
RoundID: 131774
## Testmerges:
-
## Reproduction:

Tot says a codeword
it comes out as blue'>codeword
laugh as someone gets exposed

**Comment by trollbreeder** [comment]
GOD FUCKING DAMNIT

**Comment by redguy999** [comment]
should the "FUCK" label get added?

**Comment by Pumpkinoe** [comment]
FUCK

**Comment by ATH1909** [comment]
FUCK

**Comment by TiviPlus** [comment]
Some extra notes before I forget:
ALL codewords did this, and yes I checked
I was wearing a voice changer and agent ID with the Agent ID set to (Alexa Ewing) Job: (Cargo Technician), which was my original IC name and job

**Comment by redguy999** [comment]
do the codewords do this if you are a traitor?

**Comment by boodaliboo** [comment]
this isnt a bug this is intended so other traitors can know you said them it is not highlighted for non traitors

**Comment by Gamer025** [comment]
Tested this and it works as intended like boodaliboo said.
Saying a codeword as traitor highlight it with blue or red for you and other traitors.
Non traitors see it as normal text.
Traitor chat:
![image](https://user-images.githubusercontent.com/33846895/76565251-76e29480-64aa-11ea-8f08-d441c51fc642.png)
Non traitor chat:
![image](https://user-images.githubusercontent.com/33846895/76565289-89f56480-64aa-11ea-9adb-d1b462bd1b7d.png)

**Comment by TiviPlus** [comment]
In that round instead of coming out in the color blue, which is what should happen, it came out as text output Random Tater says:"blue'>codeword", theres a difference
