### ISSUE TITLE
emagging a king goat plushie or an ascended king goat plushie LOWERS its throwforce

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#49826]
Emagging an angry goat plushie sets its throwforce to 20, but the king goat plushie and the ascended king goat plushie both already have throwforces that are greater than 20 (25 and 30, respectively).

Also, emagging a king goat plushie and then causing it to ascend unemags it (because the ascended king goat plushie is a new item).

Also, I think that the phrase "tasked to protect(ing) the king" in the descriptions of the guard goat plushie and the royal guard goat plushie should be changed to "tasked with protecting the king".

**Comment by ATH1909** [comment]
/obj/item/toy/plush/goatplushie/angry/guardgoat
	name = "guard goat plushie"
	desc = "A plushie depicting one of the King Goat's guards, **tasked to protect** the king at all costs."
	icon_state = "guardgoat"
	throwforce = 10

/obj/item/toy/plush/goatplushie/angry/guardgoat/masterguardgoat
	name = "royal guard goat plushie"
	desc = "A plushie depicting one of the royal King Goat's guards, **tasked to protecting** the king at all costs and training new goat guards."
	icon_state = "royalguardgoat"
	throwforce = 15

**Comment by PKPenguin321** [comment]
Emagging should check force before setting or add instead of set

**Comment by redguy999** [comment]
Best solution would probably be the one that is easiest to code

**Comment by ExcessiveUseOfCobblestone** [comment]
which would be adding instead of setting, although I'm not too fond of the ever elusive emag making a 45-50 throwforce weapon from a plushie...

**Comment by Daxxed** [comment]
Remove the random plushie from the toy crate?
The actual megafauna is pretty hard to defeat and the plushie could be thrown back when caught which sounds fair to me considering the risk.

**Comment by ATH1909** [comment]
I think the best solution would be to make the angry goat plushies not emaggable at all, since they appear to move because of magic instead of machinery (they don't react to EMPs). We could then give (ascended) king goat plushies the attack rate of emagged angry goat plushies by default.
