### ISSUE TITLE
regen coma + another virus = permasleep

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#49822]
## Round ID: 
quite awhile ago so im not sure, but it was manual

## Testmerges: 
don't remember.

## Reproduction:
(i think this is what happened)
1. get a virus with regen coma
2. fall into regen coma (although you may just need to be falling into it for it to work)
3. get a virus that doesn't have regen coma to override the regen coma virus
4. have admins do admin magic to fix it

This has only happened once as CE while i was fighting a blob with the crew, i was pulled away from the blob before falling into regen coma, and was stuck in it for at least 10 minutes with medical staff thinking i was dead. I notice either just before, (or while i cant remember) i fell into regen coma that messages for viruses symptoms that weren't part of the regen coma virus were occurring.
Not the only issue I've had with regen coma, but probably the worse as only admins can fix it.

**Comment by XDTM** [comment]
If you have other issues, make issue reports about it, or nobody will know they exist and fix them

**Comment by redguy999** [comment]
Will do! I didn’t report this earlier cause this occurred before I had a GitHub account.

**Comment by redguy999** [comment]
close this once the pull request gets merged or closed.
