### ISSUE TITLE
You can't suicide using soda cans (Pwr Game, Star-kist)

### ISSUE THREAD

**Issue by catswerecatswerethecats** [tgstation/tgstation#49843]
Issue reported from: irrelevant
Reporting client version: 513.1511

Suiciding with an open can just makes you take a big gulp, drop items in your hands and say boomer lines. Tested with 10/30/50u. Empty cans just disable your limbs without killing you as well.

**Comment by Bokkiewokkie** [comment]
It used to just make you say boomer quotes and then kill you if you were over thirty but someone made it nonlethal for some reason. Couldn't really find a reason for the change though since the PR is just titled "Fixes it" and doesn't have any other info in it.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Iamgoofball are you the boomer sipper maker?

**Comment by Iamgoofball** [comment]
No but I did make it so that boomers were powerful enough to survive. This ain't a bug, it's working as intended.

**Comment by Iamgoofball** [comment]
If you're under 30 it kills you, if you're over you survive

**Comment by LemonInTheDark** [comment]
based

**Comment by Tlaltecuhtli** [comment]
can i spam boomer quotes by suicide queueing
