### ISSUE TITLE
You can move upward into openspace and fall down repeatedly

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#49845]
## Reproduction:
Be on ground floor below openspace. Move upward. Fall down and hurt yourself. Keep doing it forever, even in death.

**Comment by Dennok** [comment]
Ups, mismatch in number of issue,
This seems be a dupe, no?

**Comment by LemonInTheDark** [comment]
Better description of #49761,

**Comment by ATH1909** [comment]
How do you move upwards in multi-z, anyway? Is it a button in the IC tab or something?

**Comment by Dennok** [comment]
Yes, button in the IC tab.

**Comment by Tlaltecuhtli** [comment]
jump botton

**Comment by Dennok** [comment]
related #49667
