### ISSUE TITLE
using a telekinesis syringe ability, i was able to pull a beaker out of the blender directly into my hand through a wall

### ISSUE THREAD

**Issue by joybod** [tgstation/tgstation#49856]
as title says, when i clicked on the blender with tele i was able to pull it to my hand.
Issue reported from  Round ID: 131898 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

**Comment by Tlaltecuhtli** [comment]
missing canusetopic on grinder?

**Comment by vpellen** [comment]
I had something similar to this happened to me as a Borg - I ejected the beaker from the chem dispenser and it landed below me, on the other side of the wall. May be related.

**Comment by cacogen** [comment]
If you aren't adjacent it should be moved to the same tile as the grinder

**Comment by kriskog** [comment]
Thought I covered this, oh well.

**Comment by kriskog** [comment]
Oh, not my fault.
