### ISSUE TITLE
Geiger counter bludgeons when scanning

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49853]
Issue reported from  Round ID: 131881 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1508

Doesn't do damage but shouldn't try to attack

**Comment by CRITAWAKETS** [comment]
use it on help intent you dip

**Comment by cacogen** [comment]
It bludgeons on help intent too. Things that scan shouldn't bludgeon what they're scanning. The health analyzer doesn't. I'm not sure what others do.

**Comment by ExcessiveUseOfCobblestone** [comment]
#49985

**Comment by cacogen** [comment]
The geiger counter bludgeoning and armour giving you an absorption message for attacks with no force are two separate issues.

**Comment by ExcessiveUseOfCobblestone** [comment]
it doesn't matter what intent because afterattack calls inher.
