### ISSUE TITLE
Families clutter traitor panel, all are uncategorized

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#49877]
This should probably be a nested option when setting leader/member status.
Also needs to be categorized.
![image](https://user-images.githubusercontent.com/33292112/76370785-41b63500-6338-11ea-89d7-1c3839ba8e0e.png)

**Comment by kriskog** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
Whoops, kinda forgot this thing existed. Will work on it.

**Comment by cacogen** [comment]
ah shit here we go again
