### ISSUE TITLE
Glitch when building tables with certain materials

### ISSUE THREAD

**Issue by JohnFuckingMooney** [tgstation/tgstation#49875]
Issue reported from  Round ID: 131953 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

I found that when some materials(i know that at least sandstone and bone) when built with metal table frame produce a metal table that when broken drops metal

**Comment by cacogen** [comment]
#49683

**Comment by kriskog** [comment]
dupe
