### ISSUE TITLE
Pacifists still can't use Wand of Nothing

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#49883]
## Reproduction:
#49240 should have fixed it yet when I'm on Donut and I try and use the wand of nothing as a pacifist I can't.

**Comment by cacogen** [comment]
you got the wand of nothing you shouldn't have (prototype object), /obj/item/gun/magic/wand/nothing works fine as a pacifist (source: tested just now on 70af31190957e2aed840ac37f7624e4b1e5d3b9e)
