### ISSUE TITLE
Cop sunglasses are not actual sunglasses and do not protect from flashes.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#49892]
How do you manage to fuck up sunglasses.

**Comment by Iamgoofball** [comment]
Odd, they're a subtype of normal sunglasses. I'll check it out.

**Comment by ShizCalev** [comment]
Which sunglasses specifically?

**Comment by ShizCalev** [comment]
/obj/item/clothing/glasses/hud/spacecop

oh those aren't a subtype at all.
