### ISSUE TITLE
Gangs: undercover cop possible bug

### ISSUE THREAD

**Issue by whatislostinthemines** [tgstation/tgstation#49898]
## Round ID: 
[132001](https://scrubby.melonmesa.com/round/132001)

## Testmerges: 
Server revision compiled on: 
Master commit: 58de3e70ff8456899171659a8faee681b25002b3
The following pull requests are currently test merged:
#49344: '[READY] Space Dragon Rework' by IndieanaJones at commit 8416daa7c4

## Reproduction: 
I started a gang round as an undercover cop, before trying to join a gang. I'm unsure whether this is intentional or not, but upon joining a gang, my status as a cop was completely erased after I used the gang induction book.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
Whoops, I must of forgot to commit blocking gang joins as a cop. My bad.

**Comment by TheBonded** [comment]
fairly certain this is no longer an issue
