### ISSUE TITLE
Slime commands dont work

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#49895]
Issue reported from  Round ID: [132001](https://scrubby.melonmesa.com/round/132001) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

say Attack (name) slimes
they say Hi... and do nothing

**Comment by dragomagol** [comment]
I'm willing to bet this was the same issue addressed in #55344 since it looks like you transformed yourself into a slimeperson that round.
