### ISSUE TITLE
Grapple Gloves work from cryo chamber & camera locks to cryo chamber

### ISSUE THREAD

**Issue by drakewill-CRL** [tgstation/tgstation#49901]
Issue reported from  Round ID: [132024](https://scrubby.melonmesa.com/round/132024) (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1505

Playing as clown using Gripper Gloves. While in a closed cryo chamber, with the 'throw' intent set, clicking on anything targetable allows me to jump out of the cryo tank. This also locks the camera position on the cryo chamber, while I can move around outside of it with the camera sitting still. Restarting the client resets the camera back to my avatar.

**Comment by ExcessiveUseOfCobblestone** [comment]
restraint checks?

**Comment by dragomagol** [comment]
Appears to have been fixed
