### ISSUE TITLE
partly readable papers show HTML tags

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#49902]
Issue reported from  Round ID: [132021](https://scrubby.melonmesa.com/round/132021) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

As an AI when looking at the monitor decryption key when not held up to a camera, i noticed i could see some of the HTML tags, but they were messed up by "*"s like the rest of the text.

![_tg_Station Manuel  ENGLISH   US-WEST   ROLEPLAY   99% LAG FREE _ Sudoku Square 13 3_11_2020 9_37_22 PM](https://user-images.githubusercontent.com/61719178/76479045-e724e380-63e0-11ea-9385-dcf799744813.png)

**Comment by ExcessiveUseOfCobblestone** [comment]
same will be true for burnt paper (if that's still a thing) given they use same jumble proc.

**Comment by redguy999** [comment]
This is probably a bug, right?

**Comment by redguy999** [comment]
Since nothing seems to be coming of this, i'll just close it until someone does something.

**Comment by Tharcoonvagh** [comment]
Reopen it, the tag has been added

**Comment by stylemistake** [comment]
Closed by #51125

**Comment by WarlockD** [comment]
Its because of the "stars" command.  If you cannot read or if its on fire, you do stars(text) and it makes it garbage, but it dosn't count the tags.  ITs been rewriten with the new papers comming in.
