### ISSUE TITLE
Wisdom cow spawned in space AND FUCKING DIED.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#49910]
![image](https://user-images.githubusercontent.com/35217076/76542540-3416c180-6496-11ea-85eb-7cd0055c94b2.png)

**Comment by ExcessiveUseOfCobblestone** [comment]
a cow has fallen into the river of bagil station

**Comment by actioninja** [comment]
Feature

**Comment by wesoda25** [comment]
hahaha whose wise now you dumb fucking bovine

**Comment by Qustinnus** [comment]
this teaches us that wisdom is not everything
