### ISSUE TITLE
Strange behaviours from "Voice Sensor" nanite program

### ISSUE THREAD

**Issue by Blevruz** [tgstation/tgstation#49911]
## Round ID:
[132061](https://scrubby.melonmesa.com/round/132061)

## Reproduction:
Adding the "Voice Sensor" nanite program to a nanite cloud causes the following issues:
-> If used in "Inclusive" mode: seems to trigger when a voiceline is heard regardless of whether or not it contains the specified sentence
-> If used in "Exclusive" mode: does not seem to trigger at all
("trigger" being used as in "sending the corresponding signal". tested with forced speech programs after having verified their validity with a nanite remote control)

**Comment by XDTM** [comment]
Thanks, this helps a lot
