### ISSUE TITLE
Nanite Health Scan does not show x-ray eyes under known implants

### ISSUE THREAD

**Issue by Taltarian** [tgstation/tgstation#49924]
Issue reported from  Round ID: [132095](https://scrubby.melonmesa.com/round/132095) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1511

**Comment by Dennok** [comment]
all Health Scans dont show standard organs (eyes, liver, heart), replaced or no.
It show only new inserted, thruster reviver, nutry, etc.
