### ISSUE TITLE
Families failed post_setup, stars missing

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#49935]
Round ID: [132122](https://scrubby.melonmesa.com/round/132122)

Runtime: 
```
[17:59:01] Runtime in gang.dm, line 131: undefined proc or verb /mob/dead/new_player/equip in one of slots(). 
proc name: post setup (/datum/game_mode/gang/post_setup)
src: Families (/datum/game_mode/gang)
call stack:
Families (/datum/game_mode/gang): post setup()
Ticker (/datum/controller/subsystem/ticker): PostSetup()
Ticker (/datum/controller/subsystem/ticker): setup()
Ticker (/datum/controller/subsystem/ticker): fire(0)
Ticker (/datum/controller/subsystem/ticker): ignite(0)
```

**Comment by kriskog** [comment]
@Iamgoofball

**Comment by kriskog** [comment]
Also prevented the round from actually ending, had to be done manually by admins.

**Comment by trollbreeder** [comment]
Effects:
Prevents families announcements (Los Spess radio and such)
Doesn't load in hud elements like the 5 star wanted level system
Prevents roundend
Does this to roundend screen:
![image](https://user-images.githubusercontent.com/25937686/76656715-81676180-6570-11ea-9608-8465e875f187.png)

**Comment by Iamgoofball** [comment]
What in the shit?

I actively filter out the antag candidates list for dead people or new mobs like, 3 fuckin times before getting to this code. This is weird.
