### ISSUE TITLE
using envy's knife on the corpse in the goat king ruin makes you look like someone with a name different to the one the corpse has

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#49930]
<img width="1240" alt="envy's knife bug" src="https://user-images.githubusercontent.com/42606352/76609169-ed9c8380-64e4-11ea-82cc-cc26c60dfa3b.PNG">

**Comment by ExcessiveUseOfCobblestone** [comment]
sounds like someone is changing name instead of real_name (or both)

**Comment by dragomagol** [comment]
Rip goat king
