### ISSUE TITLE
Donutstation Upper floor has wrong turf in maintaince

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#49938]
Issue reported from  Round ID: [132142](https://scrubby.melonmesa.com/round/132142) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

In the maintenance tunnel at 102,108,3 (just south of the pharmacy second floor) there are a few turfs under the catwalk, that are "space" rather than "open space". Meaning that the maintenance shaft there leaks air at round start and becomes depressurised. 

https://i.imgur.com/PzqDhDO.png

**Comment by redguy999** [comment]
probably should @ whoever made the second floor of donut

**Comment by cacogen** [comment]
mistakes into miracles @MMMiracles is the mastermind behind making donut actually desirable to play on by making it the first with multi-z
