### ISSUE TITLE
exiting chronowalk mode (as in, turning it off, not popping out of a chronowalk) makes your screen black until you relog, turn your suit's chronowalk mode back on, or fall unconscious

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#49945]
<img width="1309" alt="chronobugs" src="https://user-images.githubusercontent.com/42606352/76680677-87813080-65b8-11ea-80cd-2ce4ccf87973.PNG">

**Comment by ATH1909** [comment]
This was done on a test server, and I was able to reproduce this bug multiple times there.

**Comment by ATH1909** [comment]
I used chrono legionnaire gear that I spawned in via the debug menu (since there's no button in the traitor panel to make someone a chrono legionnaire (is there an ERT panel or something somewhere that that would be in?)) to do this testing, by the way.

**Comment by ATH1909** [comment]
Eye blurriness and flashes don't seem to be able to remove this black screen.

**Comment by Dennok** [comment]
Timeline Eradication Agent in "Select equipment" in right cick menu
