### ISSUE TITLE
mutagen bees can give skeletons mutations that they can't cure

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#49957]
<img width="311" alt="mutationbees" src="https://user-images.githubusercontent.com/42606352/76696944-e305f980-665e-11ea-9f17-49e45d5c05f3.PNG">

This mutagen bee gave me the blindness and firey sweat mutations as a skeleton.

You can't cure them with mutadone because skeletons can't metabolize reagents (I tried taking a mutadone pill anyway, of course), and you can't fix them with a genetics console/scanner because those don't work on skeletons.

This really put a damper on a fun gimmick antag round for me, and I really hope that someone will bother to find out why this is happening and fix it.

**Comment by nemvar** [comment]
Bees don't really have anything special relating to mutations. This is either a bug with skeletons no having NODNA or with unstable mutagen not respecting is.
Fix is probably very simple.
