### ISSUE TITLE
How Do I Switch Hands???! achievement unlocks repeatedly

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49958]
## Round ID:
Issue reported from  Round ID: 132239 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513
BYOND Version: 513.1508

Server revision compiled on: 
Master commit: 6a599a213b447d2b063d9b7e3e4f98955e2a30b1
Local commit: 14e141a5991084ebd09afca63e5cf9ac4bdab13e
Server tools version: /tg/station 13 Server v3.2.6.2

## Testmerges:
The following pull requests are currently test merged:
#49344: '[READY] Space Dragon Rework' by IndieanaJones at commit 8416daa7c4

## Reproduction:

> Achievement unlocked: How Do I Switch Hands???!
> You attacked yourself in the chest with the experimental welding tool
> x2

**Comment by HomocidlePancakes** [comment]
For as long as humanity persists, so shall it’s stupidity. Stupidity is as infinite as the universe itself, and for that reason, you can achieve it for as long as you live.

**Comment by trollbreeder** [comment]
Human stupidity is a universal constant that points to infinity of the highest order
