### ISSUE TITLE
Spraying a bloody toolbox with a bottle of space cleaner didn't clean it

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49967]
Issue reported from  Round ID: [132255](https://scrubby.melonmesa.com/round/132255) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

**Comment by RiskySikh** [comment]
> 
> 
> Issue reported from Round ID: [132255](https://scrubby.melonmesa.com/round/132255) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])
> 
> Reporting client version: 513.1513

Weird, I tested it out, and I was able to clean a bloodied toolbox with space cleaner.

**Comment by RiskySikh** [comment]
It seems that the bloodied toolboxes are able to be cleaned; however, for the red toolbox I am not sure since they are both the color. That the red toolbox has blood on it, but for the other toolboxes they are work fine.

**Comment by wesoda25** [comment]
Showering doesn’t clean you anymore, you have to individually remove each item

**Comment by Donkie** [comment]
This was probably fixed in my PR #52477

**Comment by dragomagol** [comment]
Appears to have been fixed
