### ISSUE TITLE
Can't fireman carry someone upstairs

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49968]
Issue reported from  Round ID: [132255](https://scrubby.melonmesa.com/round/132255) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

You leave them at the top of the stairs, but the offhand symbol remains in your hand slot until you drop it.

**Comment by dragomagol** [comment]
Also applies to ladders
