### ISSUE TITLE
Blood drip decal floating at top of staircase on second floor

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49969]
## Round ID:
Round ID: [132255](https://scrubby.melonmesa.com/round/132255)
BYOND Version: 513.1508
Master commit: 6a599a213b447d2b063d9b7e3e4f98955e2a30b1
Local commit: 14e141a5991084ebd09afca63e5cf9ac4bdab13e

## Testmerges:

The following pull requests are currently test merged:
#49344: '[READY] Space Dragon Rework' by IndieanaJones at commit 8416daa7c4

## Reproduction:

1. (Somehow) bleed at top of staircase while on second floor

No blood visible on first floor:
![](https://i.imgur.com/1M4EHGv.png)

Blood seen on second floor:
![](https://i.imgur.com/Bmxzs6k.png)

Spray cleaner can't clean it:
![](https://i.imgur.com/BQABWk7.png)

**Comment by cacogen** [comment]
Presumably happens with all decals.

**Comment by trollbreeder** [comment]
Needs pictures

**Comment by cacogen** [comment]
Actually yeah I was wrong the decals were downstairs, but were somehow above the "open space" unlike like other downstairs decals. But in testing it I discovered a different, somewhat related bug which I'll use this issue for.

**Comment by Dennok** [comment]
Again.
I remove inherit plane on all effects. 
Drips is effect.
Now you can clearly see blood effect over openspace backdrop.
