### ISSUE TITLE
Downstairs fire alarm overlay showed through floor

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49973]
## Round ID:
Round ID: [132255](https://scrubby.melonmesa.com/round/132255)
BYOND Version: 513.1508
Master commit: 6a599a213b447d2b063d9b7e3e4f98955e2a30b1

Local commit: 14e141a5991084ebd09afca63e5cf9ac4bdab13e
Server tools version: /tg/station 13 Server v3.2.6.2

## Testmerges:

#49344: '[READY] Space Dragon Rework' by IndieanaJones at commit 8416daa7c4

## Reproduction:
It's the green and blue lights beneath the railing in the top right:
![](https://i.imgur.com/0QlCLzI.png)

**Comment by Dennok** [comment]
I think it related to #49454 and i now have zero idea how to fix it.
