### ISSUE TITLE
Can try to tackle items you're wearing

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49974]
## Round ID:
**Reporting client version:** 513.1513

**Server-Side Code Modifications:** https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

**Round ID:** [132255](https://scrubby.melonmesa.com/round/132255) 
**BYOND Version:** 513.1508
**Master commit:** 6a599a213b447d2b063d9b7e3e4f98955e2a30b1

**Local commit:** 14e141a5991084ebd09afca63e5cf9ac4bdab13e
**Server tools version:** /tg/station 13 Server v3.2.6.2

## Testmerges:
**#49344:** '[READY] Space Dragon Rework' by IndieanaJones at commit 8416daa7c4

## Reproduction:

1. Equip improvised gripper gloves
2. Turn on throw
3. Click one of the items in your slots
4. Fall over

> You leap at the improvised gripper gloves!

#49476
@Ryll-Ryll

**Comment by ATH1909** [comment]
Which way do you go?

**Comment by cacogen** [comment]
You don't, you just fall over on the spot.

**Comment by ArcaneMusic** [comment]
So you probably need to exclude items within your own loc from being tackled in that case.

**Comment by nemvar** [comment]
Excluding items that aren't on a turf seems more sensible.
Otherwise you end up leaping at stuff inside boxes on the ground.
