### ISSUE TITLE
Second floor floating "islands"

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#49971]
## Round ID:
Round ID: 132255
BYOND Version: 513.1508
Master commit: 6a599a213b447d2b063d9b7e3e4f98955e2a30b1

Local commit: 14e141a5991084ebd09afca63e5cf9ac4bdab13e
Server tools version: /tg/station 13 Server v3.2.6.2

## Testmerges:
#49344: '[READY] Space Dragon Rework' by IndieanaJones at commit 8416daa7c4

## Reproduction:
1. Build a catwalk out into space that's at least two tiles long with metal rods by clicking once to make a lattice and then again to make the catwalk
2. Walk to the end of the catwalk
3. Snip the catwalk behind you with wirecutters to destroy it
4. You are now on a floating catwalk

You can also snip the catwalk underneath you and remain floating there unsupported but that's a separate issue: #49966

**Comment by cacogen** [comment]
@Time-Green 
what's the problem?

**Comment by Time-Green** [comment]
> @Time-Green
> what's the problem?

I like the bug

**Comment by cacogen** [comment]
I imagine it'll be difficult to fix so I'm guessing it'll remain in for some time

**Comment by trollbreeder** [comment]
It's like minecraft

**Comment by Dennok** [comment]
It anchored to ceiling, or bottom floor, or time-space, choice as you want.

**Comment by Dennok** [comment]
In any case, I can make him fall when the anchor is lost.

**Comment by Tlaltecuhtli** [comment]
there is no gravity u dumb stuff doesnt fall in space

**Comment by Dennok** [comment]
openspace is no space.

**Comment by interestingusernam3** [comment]
>openspace is no space and can has gravity

What?

**Comment by cacogen** [comment]
I think he meant that openspace isn't the same as space and can have gravity.
