### ISSUE TITLE
All Limbs just randomly died.

### ISSUE THREAD

**Issue by StormAGeddonz** [tgstation/tgstation#49972]
## Round ID: 
[132254](https://scrubby.melonmesa.com/round/132254)

## Reproduction:
I have no idea, I was just setting up the SM in full CE hardsuit so radiation didn't cause it. Went to walk over to the emitters and i just randomly fell down and my limbs all broke. I do have one proesthetic but I don't know if that one failing would cause all my other real limbs to die. I'm still alive with full health but can not move

**Comment by StormAGeddonz** [comment]
Appears to be random brain damage, no idea what caused it.

**Comment by HomocidlePancakes** [comment]
Random event honk. Unlucky as fuck
