### ISSUE TITLE
Dynamic spawned two sets of revolutionaries.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#49977]
Issue reported from  Round ID: [132262](https://scrubby.melonmesa.com/round/132262) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1511

As the title. There were revolutionaries spawned then provocateurs. So basically double the headrevs.

**Comment by kriskog** [comment]
Nice

**Comment by redguy999** [comment]
probably should check if this can also occur with blood cult
