### ISSUE TITLE
Spears, throwing stars, and other throwing weapons can embed into walls.

### ISSUE THREAD

**Issue by ArcaneMusic** [tgstation/tgstation#49989]
## Testmerges:

N/A, found on a local copy of the current master code.

## Reproduction:

1. Spawn or acquire a spear, or similar throwing weapon (For easier testing, spawn a box of throwing stars).
2. Throw weapon at wall. May take several attempts. Some objects will display the object on the sprite (Throwing stars, sticky items) while others won't (spears).

Found on a test server while working on something else, but that was a completely separate feature from embedding.
Turns out, embedded objects (Spears, throwing stars) or objects made embedded through tape can embed themselves into walls. I can imagine the tape part being intentional, but those thrown items are unrecoverable as far as I can tell. Deconstructing or Qdeleting the wall doesn't allow for you to recover the item in question, either. The object is still stored in the turf's contents, however.

Could either be fixed, or turned into a feature by allowing for a way to recover embedded items from a turf. Either way.

**Comment by Daxxed** [comment]
You can do it with with 100% accuracy if you aim for the exact middle of the wall sprite, the "same mechanic" is used to bounce back wizard spells on shuttle walls ( most wands, staves can bounce back if fired perfectly perpendicular )

**Comment by Daxxed** [comment]
You can also just examine the wall where it will give a pressable **Has the spear embedded into it!** which you can click to retrieve the weapon

**Comment by ATH1909** [comment]
Time to use this to hide the disk.

**Comment by ATH1909** [comment]
Wait, no, a much better thing to use this for would be hiding your phylactery as a wizard.

**Comment by Ryll-Ryll** [comment]
Weird, I imagine the issue with spears is that they have a different inhand sprite, but deleting walls should make the weapon retrievable. Maybe I should just axe turf embeds
