### ISSUE TITLE
OOC Preferences reset every round.

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#49988]
Issue reported from  Round ID: [132287](https://scrubby.melonmesa.com/round/132287) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

![qvDjdU5GxT](https://user-images.githubusercontent.com/32805898/76713536-4b9cb700-66ef-11ea-8a7c-734f400f5bb5.png)

Without fail, after turning off anything in this section of preferences. It will restore to default. And yes, I change the setting then hit save setup, it ignores this.

**Comment by kriskog** [comment]
Its the new play end of round sound setting. If you set it disabled, you will be able to save settings for now.
