### ISSUE TITLE
Manly Dorf cannot be made, period.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#49981]
Issue reported from  Round ID: [132269](https://scrubby.melonmesa.com/round/132269) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1511

As a consequence of this Bacchus Blessing cannot be made either. Beer and Ale don't mix into Manly Dorf.

**Comment by carshalash** [comment]
Thank god.

**Comment by ArcaneDefence** [comment]
I just updated my local, and cannot reproduce. 
Mind describing the situation in depth?

**Comment by kriskog** [comment]
Cant reproduce this on latest master either.

**Comment by redguy999** [comment]
maybe it was just some code decided not to work correctly?

**Comment by RiskySikh** [comment]
weird, I was able to make manly dorf

**Comment by necromanceranne** [comment]
I have no idea why it occurred if it can't be reproduced. I suppose I'll give it another attempt at reproducing later but straight up I couldn't get it to be created in the given round.

**Comment by kriskog** [comment]
Were you using the ingredients from the booze dispenser?

**Comment by necromanceranne** [comment]
I was using debug tools but someone in the game was using standard booze dispenser.

**Comment by necromanceranne** [comment]
@nemvar also this isn't my first issue what the hecc QwQ

**Comment by kriskog** [comment]
Issue jannie fell for the good first issue trap 🤡
![image](https://user-images.githubusercontent.com/33292112/76890259-51c59b80-6887-11ea-9d57-f8c6ebf0671c.png)

**Comment by lordpidey** [comment]
Is it possible you were trying to use the wrong type of beer as an ingredient?  Hacked service borgs can make a toxic beer that is very hard to distinguish between regular beer.

**Comment by nemvar** [comment]
I be closing this now
