### ISSUE TITLE
Watcher beams deal no damage

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#49999]
## Reproduction:
Well it's been common knowledge for a while that no one has reported, but after changes to body temperature regulation races like humans can tank multiple shots from a watcher without taking enough thermal damage to be slowed or take burn damage.
This leads to people just freely farming diamonds from any watcher tendril they find by standing still one tile away from them, plinking away with a pka.

**Comment by Daxxed** [comment]
Although humans do indeed not take any damage, one bolt will nearly kill an ashwalker if he doesn't have a legion core to reset his temperature

**Comment by ArcaneDefence** [comment]
https://streamable.com/u8xa35
Still present issue after body temp mechanics were changed again
