### ISSUE TITLE
Plumbing machines are slightly broken now

### ISSUE THREAD

**Issue by halitosisman** [tgstation/tgstation#50028]
Issue reported from  Round ID: [132377](https://scrubby.melonmesa.com/round/132377) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

Plumbing machines seem to unwrench and rotate themselves now. This bug did not appear in an earlier round today. Crowbarring floortiles out from under equipment changes the visual orientation of the machines. 

Also you can rotate machines while they are wrenched down now.

**Comment by Time-Green** [comment]
Oh, I probably forgot to set the dir to the machines direction when reapplying the overlays. It should be purely visual, I’ll have a fix up by the end of the day
