### ISSUE TITLE
Z-level change can cause you to end up on the second floor on donutstation

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#50027]
## Round ID:
recent manual or bagil

## Testmerges:
The space dragon rework

## Reproduction:
0. Be on donutstation map
1. get EVA suit
2. go to edge of Z-level
3. keep going to the edge until you end up on second floor of donut

**Comment by Fikou** [comment]
that doesnt seem like a bug, you travelled through space enough to find the second donut z level, the same way you can find the first one, seems like a good thing

**Comment by redguy999** [comment]
what i find the main issue is that you cant go back the way you came

**Comment by Dennok** [comment]
you can, just go back

**Comment by redguy999** [comment]
the z-level doesnt change when on the second floor, you just get stuck.
or at least, one of the edges wouldnt let me change z-level

**Comment by MMMiracles** [comment]
one does not simply escape donut

**Comment by timothymtorres** [comment]
Duplicate of #58436
