### ISSUE TITLE
Detective baton stamina damage can target limbs

### ISSUE THREAD

**Issue by Tumesuo** [tgstation/tgstation#50035]
Issue reported from  Round ID: [132405](https://scrubby.melonmesa.com/round/132405) (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 513.1512

You can disable limbs with one hit with the detective's baton, didn't use to be this way.

**Comment by necromanceranne** [comment]
I thought Cobby said this was fine when I asked him to include it in his baton fix. Turns out Cobby has lied to me and he actually mistook the clumsy check for the baton stamina hit.
