### ISSUE TITLE
Remove game chat auto scrolling in ghost mode

### ISSUE THREAD

**Issue by RavenDiesel** [tgstation/tgstation#50036]
https://streamable.com/cp763

As you can see here, ghost chat has a tendency to roll back to new messages, so you can't, for example, click a follow button near players' phrases. Or check what's going on generally. It can be quite annoying when there's a lot more text spam than shown on this video.
Granted, I didn't tested it out with a few or all ghost functions (ears, sight, radio etc) toggled off, but still it would be nice to slow down that pace for when all of those functions are enabled.

**Comment by Daxxed** [comment]
Not only global say but also global emotes are on yikes...
This isn't an issue for people who turn these to "nearest creatures only" aka everyone who doesn't want to go insane.
