### ISSUE TITLE
on_metabolization_end (or whatever) is not being called on sudden death

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#50037]
This means repeatedly dying will cause things like Brave Bull and Alexander to impart their benefits from metabolization permanently.

## Reproduction:

Get a riot shield, drink alexander, suicide, vv the shield, it now has +10 block permanently.

(this works with monkey humans just an FYI in case anyone thinks this is edge case)

**Comment by nemvar** [comment]
Looks easy enough to fix.

**Comment by nemvar** [comment]
Due to recent events on the discord I will remove the Good First Issue tag. I overestimated newcoders.

**Comment by TiviPlus** [comment]
Look at this duuuuude

**Comment by necromanceranne** [comment]
@nemvar stop bulli I'm trying to helpies qwq

**Comment by nemvar** [comment]
Not you. Talking about Bindy here.

**Comment by TiviPlus** [comment]
y u bully he, he's on the greatest redemption arc known to man
