### ISSUE TITLE
Box station is still in rotation for some reason

### ISSUE THREAD

**Issue by Tumesuo** [tgstation/tgstation#50058]
Issue reported from  Round ID: [132487](https://scrubby.melonmesa.com/round/132487) (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 513.1512

**Comment by ArcaneMusic** [comment]
Feature.

**Comment by TheVekter** [comment]
ided... kinda?

**Comment by TiviPlus** [comment]
broken  powernets mad

**Comment by HomocidlePancakes** [comment]
Yep, this is a serious issue. I think removing meta from the map pool would solve it.

**Comment by PKPenguin321** [comment]
I lost my issue jannie role because I was banned so I cant close this but just know that you are an amateur and a fool
