### ISSUE TITLE
Nightmare spawning without Light Eater

### ISSUE THREAD

**Issue by Vanadiom** [tgstation/tgstation#50064]
## Round ID:
[132491](https://scrubby.melonmesa.com/round/132491)

## Testmerges:
#49065 

## Reproduction:
Uhhh, spawn as midround nightmare ghost role (In dynamic). Don't have the Armblade of your darkest desires.

**Comment by Vanadiom** [comment]
I don't actually know if it belongs here, because I don't know if it is reproducable.

**Comment by Daxxed** [comment]
This is indeed the correct place but there was already an issue report for it, that has been closed without fixing the issue...

**Comment by kriskog** [comment]
They are getting a normal heart instead of the nightmare heart for some reason

**Comment by kriskog** [comment]
See #49786 for more stuff

**Comment by Vanadiom** [comment]
God damn it, guess I opened pandora's box.
Well I do have a knack for finding oddities in this game...

**Comment by spookydonut** [comment]
Fixed by #50174
