### ISSUE TITLE
Putting someone in zero-G into the Odysseus' mounted sleeper results in them floating when ejected in gravity

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#50078]
## Round ID:
**Server-Side Code Modifications:** https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

**Round ID:** 132538
**BYOND Version:** 513.1508
**Master commit:** 2368a8acc3d8a1d6bdfb5698e2bd7bb767c235e3

**Local commit:** ee81158ee1243d25af998738644b53af8f071980
**Server tools version:** /tg/station 13 Server v3.2.6.2

## Testmerges:
**#49344:** '[READY] Space Dragon Rework' by IndieanaJones at commit 6665b02929

**Comment by ATH1909** [comment]
How long do they stay floating for?

**Comment by cacogen** [comment]
I watched for maybe 15 seconds to see if it'd stop and it didn't.

**Comment by ATH1909** [comment]
Did you move?

**Comment by cacogen** [comment]
I moved the body into a stasis bed and I don't think it stopped

**Comment by Jacquerel** [comment]
This still happens but it seems to just be the animation persisting, they are actually under gravity but the animation fails to end if they are in an odysseus sleeper when the `animate` to remove it is called. Messed around with it a bit but I don't know enough about why that would happen to fix it.

**Comment by Sealed101** [comment]
related #75480
