### ISSUE TITLE
No proximity check for untying shoelaces

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#50077]
Issue reported from  Round ID: [132538](https://scrubby.melonmesa.com/round/132538) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

**Comment by nemvar** [comment]
#50048

**Comment by cacogen** [comment]
managed to report this after the pr fixing it
