### ISSUE TITLE
Shots pass over resting people

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#50076]
This was fixed over a year ago with #42241 but it recently broke again. Reporting before this cancer meta returns fully. 

Quote:
> This should make people Paralyze()d (hard stunned) not get hit, but getting just Stun()ed or Knockdown()ed still makes you bullet vulnerable, as Stun() makes you unable to use items but you are still standing . 

#### Reproduction:

1. Rest. 
2. Have someone else click behind you with an autorifle. 

Result: Shots will miss. I assume same happens over knockdowned. 
Intended result: Shots aimed behind someone should only pass over paralyzed/crit/sleeping/dead people. Knockdowned and crawling people should not require you to click directly on them.

**Comment by Daxxed** [comment]
Probably also to do with the refactor of CanPass #48659

**Comment by ATH1909** [comment]
Eh, I personally don't believe that the resting meta was all that cancerous, and it led to some cool moments like hitting the deck to avoid a wild spray of machine gun fire.

You can still hit resting people with bullets if you click on them directly, right?

Wait, with tackling and this, that means... *gasp* GET DOWN, MR. CAPTAIN!

**Comment by Learner10** [comment]
Aside from the stun issue, I don't think the rest of this sounds quite like a bug. It sounds essentially like the same as going prone, or tackling someone to get them onto the ground to avoid a barrage. Aiming at someone on the ground should be an intentional action by the shooter, because it means that those being shot at can do something to help themselves even a little.

**Comment by Angustmeta** [comment]
Having to click directly on a moving target makes it hard and tedious to lead shots. Back then We got entire nuke op teams crawling around murdering sec with ease while not risking friendly fire.

**Comment by ATH1909** [comment]
> Having to click directly on a moving target makes it hard and tedious to lead shots. Back then we got entire nuke op teams crawling around murdering sec with ease while not risking friendly fire.
> 
> I admit it was funny at first.

Hm.

Maybe make firing a shot make you lose your indirect shot immunity until you get up and go prone again? It sounds game-y, but it's the best solution I can think of on the spot.

**Comment by ATH1909** [comment]
Ooh, what if we made shots that pass over a resting (but not stunned or dead, so that people won't fill halls with dead monkeys for projectile immunity) person have a chance to pass over them instead of being guaranteed to?

**Comment by ATH1909** [comment]
Alternatively, what if we made firing a gun while prone have a massive accuracy penalty (like, "you can't hit the broad side of a barn"-level bad) unless you stayed still for a long time? You could have the accuracy penalty decrease over the course of, say, 7 seconds spent staying still, with it resetting if you move.

**Comment by ATH1909** [comment]
Alternatively alternatively, we could make being prone only give you a chance to dodge ranged projectiles if you're behind "cover"- in other words, if the projectile has to pass over things to get to you (like tables and maybe even other prone people) and you're prone, you have a chance to dodge it, but if you're prone and out in the open, it'll still hit you?

**Comment by redguy999** [comment]
i think the missing prone targets is only for physical bullets, could be mistake, probably am.

**Comment by redguy999** [comment]
> Alternatively alternatively, we could make being prone only give you a chance to dodge ranged projectiles if you're behind "cover"- in other words, if the projectile has to pass over things to get to you (like tables and maybe even other prone people) and you're prone, you'll have a chance to dodge it, but if you're prone and out in the open, it'll still hit you?

thats seems like too many checks for situations where is would be most often occuring (nuke op rounds)

>Alternatively, what if we made firing a gun while prone have a massive accuracy penalty (like, "you can't hit the broad side of a barn"-level bad) unless you stayed still for a long time? You could have the accuracy penalty decrease over the course of, say, 7 seconds spent staying still, with it resetting if you move.

where'd this come from?

**Comment by redguy999** [comment]
> > Having to click directly on a moving target makes it hard and tedious to lead shots. Back then we got entire nuke op teams crawling around murdering sec with ease while not risking friendly fire.
> > I admit it was funny at first.
> 
> Hm.
> 
> Maybe make firing a shot make you lose your indirect shot immunity until you get up and go prone again? It sounds game-y, but it's the best solution I can think of on the spot.

that doesn't make the most sense. maybe just make it so you can't rest while holding the gun, and if you try to use it while already on the ground, just make it not work.
2 guns i think that should apply to are the RPG and the LMG, mostly cause they're bulky.

**Comment by ATH1909** [comment]
> > > Having to click directly on a moving target makes it hard and tedious to lead shots. Back then we got entire nuke op teams crawling around murdering sec with ease while not risking friendly fire.
> > > I admit it was funny at first.
> > 
> > 
> > Hm.
> > Maybe make firing a shot make you lose your indirect shot immunity until you get up and go prone again? It sounds game-y, but it's the best solution I can think of on the spot.
> 
> that doesn't make the most sense. maybe just make it so you can't rest while holding the gun, and if you try to use it while already on the ground, just make it not work.
> 2 guns i think that should apply to are the RPG and the LMG, mostly cause they're bulky.

Nah, then people will just abuse the system with revolvers or something instead.

**Comment by redguy999** [comment]
>Nah, then people will just abuse the system with revolvers or something instead.

True.

**Comment by GLACoding** [comment]
How about making it so being prone means your shots will now hit prone people and hit standing people in the legs (possibly).
Easy counter to someone staying prone, but allows some tactical ducking if you can react to incoming rounds.

**Comment by Survivioboi** [comment]
If this is merged with original idea the GET DOWN MR CAPTAIN when somebody be shooting up the school will just be replaced with standing in front of the captain, which is way less humorous

**Comment by kriskog** [comment]
Works backwards, crit/stunned/dead people block bullets.

**Comment by Survivioboi** [comment]
> Works backwards, crit/stunned/dead people block bullets.

I have an idea I could use on a nukeops round.
