### ISSUE TITLE
Meta's virology scubber injector is not able to be interacted by borgs or AI

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#50081]
Issue reported from  Round ID: [132546](https://scrubby.melonmesa.com/round/132546)(actually the one before) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1514

The injector appeared off and i couldnt get the UI to appear.

**Comment by kriskog** [comment]
Likely missing an area with power on the turf its on

**Comment by redguy999** [comment]
Shouldn't be that hard of a fix.
