### ISSUE TITLE
Whiteship broke

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#50097]
Issue reported from  Round ID: [132588](https://scrubby.melonmesa.com/round/132588)(previous round) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1514
(this is meta's whiteship)
what i did:
1. sent the whiteship to a custom location near the derelict
2. rotate the whiteship 180 and move the new position of the custom location down a few tiles
3. launch
4. whiteship is now in pieces

**Comment by redguy999** [comment]
this appears to be the same thing as #39906, wait, HOW HAS THIS NOT BEEN FIXED

**Comment by Tharcoonvagh** [comment]
Dupe please close

**Comment by Dennok** [comment]
Wtf, why again. Or still.

**Comment by redguy999** [comment]
> Dupe please close

I'll close it if there's a pull request.

**Comment by Dennok** [comment]
This fixed for now.

**Comment by Dennok** [comment]
Fixed by #53631
