### ISSUE TITLE
Pirates can't actually speak pirates

### ISSUE THREAD

**Issue by Pumpkinoe** [tgstation/tgstation#50100]
## Round ID:
Any round with pirates

## Reproduction:
be pirate
check languages
pirates can only speak skellytan language, not pirate language

**Comment by nemvar** [comment]
I don't think this is a bug. Pirate language was implemented as a le epic meme with the pirate hat and has nothing to do with space pirates.
Consistency issue tho

**Comment by redguy999** [comment]
the text that shows up when you scroll over the tag make no sense for this issue.

**Comment by Pumpkinoe** [comment]
not a bug but muh Arr Speak

**Comment by nemvar** [comment]
I makes sense. Language and pirate game components collide. Their interaction, or rather, lack thereof is unexpected as shown by this issue.
