### ISSUE TITLE
Cybersun hardsuits have no cold protection

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#50117]
Issue reported from  Round ID: [132654](https://scrubby.melonmesa.com/round/132654) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507
and you can't turn on the temp stabilizer

**Comment by EgorDinamit** [comment]
Aye, it's fixed in #50120
