### ISSUE TITLE
Morphine gives you zoomies and the power to RUN FAST

### ISSUE THREAD

**Issue by Dezupher** [tgstation/tgstation#50110]
## Round ID: 
[132618](https://scrubby.melonmesa.com/round/132618)

 Byond Version: 
513.1508

## Reproduction: 
Take some morphine, acquire speed that's faster than meth. This affects survival medipens too, since there is a small amount of morphine in them.

## Video: 
https://streamable.com/v1pwe

**Comment by Tharcoonvagh** [comment]
huh
