### ISSUE TITLE
Phantom tanks and airpumps

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#50118]
If a plasma tank is left inside the air pump as it breaks, it creates a "phantom" tank which is invisible and if you drop it it disappears, tried right clicking it but nothing

**Comment by Pugie** [comment]
Mathias cannot make maxcaps.

**Comment by bobbahbrown** [comment]
@Tharcoonvagh please re-submit ``Also if left inside the air pump it creates a "phantom" tank which is invisible and if you drop it it disappears, tried right clicking it but nothing`` as a bug, the first thing you mention is intended functionality

sincerely,
bobbah 'bee 'brown

**Comment by LemonInTheDark** [comment]
He will not be allowed the opportunity

**Comment by Tharcoonvagh** [comment]
Dont at me bro, christ this was a long time ago

**Comment by LemonInTheDark** [comment]
Solved by #63162
