### ISSUE TITLE
Plastic flaps are invisible

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#50123]
## Reproduction:
This was roundstart, they showed up later in the round but I am uncertain as to when.
![image](https://user-images.githubusercontent.com/3204033/77209118-ad2b9f80-6aba-11ea-9b7b-6a197fc87eaf.png)

**Comment by RaveRadbury** [comment]
Later in the round they showed back up, but I have noticed this on multiple rounds.

**Comment by nemvar** [comment]
Probably related to overlay changes.

**Comment by RaveRadbury** [comment]
I haven't seen this issue pop up in a while.
