### ISSUE TITLE
Can rotate pews

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#50136]
## Round ID:
**Issue reported from Round ID:** [132730](https://scrubby.melonmesa.com/round/132730) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

**Master commit:** 93c24eca9f0ac3634ac6ee9e765e212e8ba0a39c

## Testmerges:
No

## Reproduction:

1. Alt-click pew

**Comment by Pumpkinoe** [comment]
how this a bug? pretty sure rotating most chairs are intentional

**Comment by cacogen** [comment]
It's not a bug it's an oversight
