### ISSUE TITLE
I ate a lot of warm donkpockets and died of burns

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#50131]
## Round ID:
**Round ID:** 132721 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])
**Reporting client version:** 513.1513
**BYOND Version:** 513.1508
**Master commit:** 699efe5875f317699600eaef96e9396057191f28
**Server tools version:** /tg/station 13 Server v3.2.6.2

## Testmerges:

None.

## Reproduction:

1. Eat a lot of donkpockets
2. Die of burns

Pretty sure this was caused by an omnizine overdose. I think this may have only changed recently though, given how often I've resorted to cooked donkpockets when starving and have never had this happen before. If it is a recent change, this might be an oversight.

https://github.com/tgstation/tgstation/blob/d518b50a2f8405b623d9fcd0fa36f55178d61c5f/code/modules/food_and_drinks/food/snacks_pastry.dm#L414-L422

https://github.com/tgstation/tgstation/blob/bce47ff94c32f1f56b65348c3f02295441c8933d/code/modules/reagents/chemistry/reagents/medicine_reagents.dm#L334-L341

**Comment by Tharcoonvagh** [comment]
Huh

**Comment by cacogen** [comment]
don't think it's a bug just an overdose of omnizine
