### ISSUE TITLE
Morphine pills don't speed you up like they are supposed to?

### ISSUE THREAD

**Issue by Something1sWrong** [tgstation/tgstation#50134]
Issue reported from  Round ID: [132729](https://scrubby.melonmesa.com/round/132729) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507

no idea why

**Comment by RiskySikh** [comment]
How many pills did you take?

**Comment by RiskySikh** [comment]
It got patched. https://github.com/tgstation/tgstation/pull/50095
