### ISSUE TITLE
You can't play instruments

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#50143]
Or, well, you at least can't play the electric guitar or the recorder. I think I was able to play the harmonica at one point, but that was a while ago.

Writing a song and then pressing "Play" does nothing; it doesn't even give people around you a moodlet if you have the Musician quirk.

**Comment by RiskySikh** [comment]
Weird, I was able to play the electric guitar and the recorder just fine.

**Comment by RiskySikh** [comment]
I know that when you play multiple instruments at the same time, it sometimes breaks the audio

**Comment by cacogen** [comment]
feature

**Comment by DranKof** [comment]
I think he's referring to the fact that when hosting a private server, instruments don't work, at all. The GUI opens, they seem to do everything that they should, they just don't make sound. I'm guessing the music files are .ignored and don't sync to the github or something, maybe.
