### ISSUE TITLE
You can stick bags of holding into bluespace bodybags

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#50151]
## Reproduction:

Stick boh in an open bluespace bodybag.
Close it.
Profit.

Is it a bug? Is it a feature? You decide.

**Comment by Dennok** [comment]
The bodybag with bog inserted in boh create boh_explode(singulo now) anyway.

**Comment by redguy999** [comment]
I say this is intended behavior, as long as the BOH explosion still works.

**Comment by timothymtorres** [comment]
> The bodybag with boh inserted in boh create boh_explode(singulo now) anyway.

I don't see a problem with this effect unless it's easy to mass produce the bluespace bodybags.

**Comment by LemonInTheDark** [comment]
honestly not an issue anymore, since bags of holding aren't nearly as easy to make
