### ISSUE TITLE
You can break the Luxurious Shuttle Paywalls/Scanner Gates.

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#50155]
## Round ID:
[132823](https://scrubby.melonmesa.com/round/132823)

## Testmerges:
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:
On any station, buy the Luxurious Shuttle and call it to the station. When it arrives, you can just smash/deconstruct the scanner gates, therefore not requiring money to get on the paid side of the shuttle.

**Comment by lordpidey** [comment]
Oh dear, are the peasants trying to break down the gates again?

What's that?  They've succeeded this time?  Send the hounds.

**Comment by cacogen** [comment]
You can also teleport into the luxury shuttle, which I believe can be fixed with an area var?

**Comment by redguy999** [comment]
> You can also teleport into the luxury shuttle, which I believe can be fixed with an area var?

what happens to the person who tries to teleport in, where would they go?
