### ISSUE TITLE
Multiple hygienebot issues

### ISSUE THREAD

**Issue by Bram961** [tgstation/tgstation#50159]
## Round ID: 
[132831](https://scrubby.melonmesa.com/round/132831)

## Reproduction:

Expanding on https://github.com/tgstation/tgstation/issues/49514

- hygienebots are named "cleanbot" in the AI's botcontrol menu.
- hygienebots will occasionally get stuck in their cleaning state causing them to spread water everywhere. This seems to happen when they attempt to clean someone and start their water animation but cannot get to the person to actually finish cleaning them.
- It does not seem possible to turn hygienebots off entirely.
- (consistency) hygiene bots, unlike most other bots that require atleast a proximity sensor and an arm, only require 2 metal and 1 chem pipe to be built. This allows the roboticist to essentially mass produce them.

**Comment by PKPenguin321** [comment]
@Qustinnus
