### ISSUE TITLE
After Space Dragons gets 3 Charged Rifts the resulting carps are not sentient, cannot be controlled and you cannot create more.

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#50160]
## Round ID:
[132841](https://scrubby.melonmesa.com/round/132841)

## Testmerges:
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:
As a Space Dragon, Charge 3 Rifts. The resulting "Carpocalypse" results in many nonsentient carp, but none that can be controlled, while the PR says they can be controlled. You cannot spawn more carp after the initial burst of carp as well.

> After the 3rd time, all the charged rifts can spawn infinite sentient carp

**Comment by kriskog** [comment]
@IndieanaJones

**Comment by IndieanaJones** [comment]
This has been fixed for quite a while now.  I forgot to tag it on said PR, but this is fixed.
