### ISSUE TITLE
KA AoE Mod from Mining vendors does not Mine AOE (3x3)

### ISSUE THREAD

**Issue by MadOnion83** [tgstation/tgstation#50181]
#46073  Round ID: [132931](https://scrubby.melonmesa.com/round/132931) (And others)

## Reproduction: I reproduced this issue on 3 different rounds.
By upgrading my Kinetic Accelerator with the AoE mod from the mining vending machine (costs 2000 mining points) I noticed that the AOE explosion does show up but i only mine 1x1 block instead of the expected 3x3 AoE mining.

**Comment by TemporalOroboros** [comment]
I believe the vendor version is the damage AoE instead of the mining AoE.
