### ISSUE TITLE
Can flap wings without wings

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [tgstation/tgstation#50187]
[Round ID]: #132591

## Reproduction:

T -> *aflap

**Comment by GunHog** [comment]
Pretend that your arms are wings.

**Comment by cacogen** [comment]
This one's a classic

**Comment by Survivioboi** [comment]
I dont see the issue

**Comment by trollbreeder** [comment]
You must flap your arms ANGRILY

**Comment by ATH1909** [comment]
You're flapping your arms.

**Comment by cacogen** [comment]
just add a check for wings and change it to arms if not
