### ISSUE TITLE
Upgrade error when using cyborg emergency reboot module, board drops beneath newly revived cyborg

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#50198]
## Round ID:
**Issue reported from  Round ID:** [132992](https://scrubby.melonmesa.com/round/132992) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

**Reporting client version:** 513.1513

**BYOND Version:** 513.1508
**Master commit:** 2be0f092bf4031c65cd4efd349aa2c5c8b41b6b4

**Local commit:** 1a40fbc57db8af1b4fc41af7a4f2582281c2a13d

## Testmerges:
**#49982:** 'Smart Asset Cache - no more resending assets on round restart.' by MrStonedOne at commit 920eaac0dc

## Reproduction:

1. Click open dead borg with cyborg emergency reboot module
2. "Upgrade error." appears in red text in chat window
3. Board drops beneath cyborg, cyborg is revived anyway

**Comment by ATH1909** [comment]
This is because the one_use that is set to TRUE for rename and cyborg emergency reboot upgrade modules doesn't actually do anything, and upgrade modules by default return that error when used on a dead borg, even if they don't actually care if the borg they're used on is dead.

**Comment by redguy999** [comment]
this is a bug?
