### ISSUE TITLE
Self-respiration virus, Choking moodlet and icon don't dissapear

### ISSUE THREAD

**Issue by Nikitaw99** [tgstation/tgstation#50199]
Issue reported from  Round ID: [132992](https://scrubby.melonmesa.com/round/132992) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

I walked into space while having a self-respiration virus. I was choking for a little, but then the virus properly kicked in. But the choking icon never vanished, and neither did the moodlet, even when I went back onto the station. This drove my character to insanity and I couldn't do anything about it.

![image](https://user-images.githubusercontent.com/16986290/77483785-6cc57c00-6e42-11ea-94f7-f67015bbed98.png)

**Comment by Mickyan** [comment]
So that's what it was about

Could probably fix this by adding a signal to clear the moodlet when self respiration kicks in

**Comment by Angustmeta** [comment]
The issue was originally fixed in early 2019

#42315

**Comment by dragomagol** [comment]
Fixed by #53715
