### ISSUE TITLE
Plumbing machine broke time AKA STOP ROTATING ALREADY!!

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#50190]
In particular every time I try to process chems in the acclimator it rotates. Any time I interact with it with a plunger, it rotates. As a result it is unable to move chems through to the storage or output gate. This had occurred in issue #50028 which there was supposed to be a fix for, but alas it is **STILL!! HAPPENING!!**

 _Images attached (Images may not be in chronological order)_

![2020-03-24 08_25_32-_tg_Station Event Hall_ Sseth overflow event   ENGLISH   EU   100% FREE LAG _ wq](https://user-images.githubusercontent.com/36066032/77436767-7ea71080-6da9-11ea-8795-e16103cceebb.png)

![2020-03-24 08_25_23-_tg_Station Event Hall_ Sseth overflow event   ENGLISH   EU   100% FREE LAG _ wq](https://user-images.githubusercontent.com/36066032/77436788-85ce1e80-6da9-11ea-9a35-1d8f06b96993.png)

![2020-03-24 08_31_36-_tg_Station Event Hall_ Sseth overflow event   ENGLISH   EU   100% FREE LAG _ wq](https://user-images.githubusercontent.com/36066032/77437142-ebbaa600-6da9-11ea-923a-81d4a4730dcd.png)

![2020-03-24 08_25_13-_tg_Station Event Hall_ Sseth overflow event   ENGLISH   EU   100% FREE LAG _ wq](https://user-images.githubusercontent.com/36066032/77436823-9088b380-6da9-11ea-8237-05cd4119e571.png)

![2020-03-24 08_26_03-_tg_Station Event Hall_ Sseth overflow event   ENGLISH   EU   100% FREE LAG _ wq](https://user-images.githubusercontent.com/36066032/77436835-92eb0d80-6da9-11ea-8570-efbc16b13b48.png)

Issue reported from  Round ID: [132969](https://scrubby.melonmesa.com/round/132969) (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 513.1517

**Comment by Time-Green** [comment]
It’s completely visual, because byond does not turn overlays by default. 

I’ll inquire further about a clean fix

**Comment by Time-Green** [comment]
I just took the liberty to test this in a few cases, and it cannot be reproduced on anything but plumbing machinery

**Comment by TheSilverNuke** [comment]
Thanks for looking into it so soon! I was concerned when it started flipping, if you're making a complex factory it can get confusing.

**Comment by Time-Green** [comment]
Eh, I was the idiot that let it pass the first time around. I'll look into it further once I got some free time (because quarantine = more work, ironically)
