### ISSUE TITLE
Admins cannot add Galactic Common to Xenomorphs

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#50204]
Issue reported from   (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

Simply go into the Player Panel of the xenomorph you want to edit the languages of and attempt to give them Galactic Common, be confused when it fails to apply.   Only making this report because sometimes we like to make tiny events involving xenomorphs that can speak or at least understand Galactic Common, neither of which is possible right now.

**Comment by ATH1909** [comment]
Can't xenos use their whisper ability to send messages to humans?

**Comment by ATH1909** [comment]
```
/obj/item/organ/tongue/alien
	name = "alien tongue"
	desc = "According to leading xenobiologists the evolutionary benefit of having a second mouth in your mouth is \"that it looks badass\"."
	icon_state = "tonguexeno"
	say_mod = "hisses"
	taste_sensitivity = 10 // LIZARDS ARE ALIENS CONFIRMED
	modifies_speech = TRUE // not really, they just hiss
	var/static/list/languages_possible_alien = typecacheof(list(
		/datum/language/xenocommon,
		/datum/language/common,
		/datum/language/draconic,
		/datum/language/monkey))
```
Common is on the list of languages that xeno tongues are physically able to speak, so that's not what's causing the problem here.

**Comment by TheMidnightRose** [comment]
They can do the whisper far as I am aware, the confusing part is that when doing a language add, you can tell it to add Common as understood, speech, or both it will then act like you did so for a moment then you look at their language its not there at all.
