### ISSUE TITLE
We need a way to remove something from a drone's internal storage

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#5020]
Feature Request
@RemieRichards 

So we can take back things it took from us if we manage to pick it up without having to smash it.

Please

**Comment by Shadowlight213** [comment]
@dorsisdwarf this can probably be closed.

**Comment by Shadowlight213** [comment]
Actually nevermind. This is still an issue but specific to drones that are "hiding"
@RemieRichards if you pick the drone up, it becomes an item. There actually doesn't seem to be any way to kill the drone without destroying its contents while it is in its item state, nor is there a way to force it out of an item state.
