### ISSUE TITLE
Hotkeys problem with AZERTY keyboard.

### ISSUE THREAD

**Issue by MaximeVignals** [tgstation/tgstation#50214]
Issue reported from  Round ID: [133068](https://scrubby.melonmesa.com/round/133068) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1514

Hello there. I'm playing from europe on a AZERTY keyboard and I can't bind the & and é keys. This makes it very annoying because I need to bind the 4 intents far away from the ZQSD keys that are used to move. Any way to fix this ?

**Comment by Couls** [comment]
I don't think the system supports non-english characters unfortunately, binding & should still work though

**Comment by cacogen** [comment]
as if being from europe wasn't enough

**Comment by tgsAvylaar** [comment]
I have the same issue, and I solved this by using autohotkey.
I just rebound my &é"' (1234) keys to the following:

#NoEnv
SendMode Input
SetKeyDelay, 0, 5

&::Send {Numpad1}
é::Send {Numpad2}
"::Send {Numpad3}
$'::
    send {' down}
    send {' up}
return

**Comment by SuperNovaa41** [comment]
https://github.com/tgstation/tgstation/issues/58875
