### ISSUE TITLE
Statis Bed Bed Overlay is on a layer thats too high.

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#50218]
## Round ID:
[133075](https://scrubby.melonmesa.com/round/133075)

## Testmerges:
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:
Put a locker with objects on top of statis bed, open the locker, the statis bed overlay will be on top.

![image](https://user-images.githubusercontent.com/56656478/77590356-ea7d9c00-6ec3-11ea-89c3-735d04f57ba7.png)

**Comment by cacogen** [comment]
It's an overlay, and it's on a layer that's too high
