### ISSUE TITLE
control+WASD still roots you in place, even if you've changed your bindings

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#50216]
Reproduction steps:
1. Bind both WASD and control+WASD to moving.
2. Bind both your arrow keys and control+arrow keys to rotating in place.
3. Press control while moving.
4. Notice that you're rooted in place (you won't rotate because you unbound control+WASD from rotating in place, so you'll instead just remain facing the direction you were moving in until you let go of control), so your cyborg-optimized keybind setup doesn't actually work.
5. Cry as you realize that you'll forever more have to stop in place to attempt to grab people or bolt doors behind you as a cyborg.

**Comment by MrStonedOne** [comment]
Likely some movement code is manually checking control, likely an easy fix

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/tgstation/blob/9b380e5cd92f5d5886759ddad2cdc2eafc090940/code/modules/keybindings/bindings_mob.dm#L61
