### ISSUE TITLE
Bluespace space floors can crash servers

### ISSUE THREAD

**Issue by ishitbyabullet** [tgstation/tgstation#50213]
https://i.imgur.com/vFwBk9F.png
## Reproduction:
1. Spawn a line of chasms infront of the pod doors at centcom docks
[This step may be unrelated however it is how I saw it first happen]
2. Spawn a decent size chunk of these tiles infront of the window
3. Walk into the bluespace tiles

You will begin to lag the server out incredibly. You COULD still restart it if fast enough however it is basically a super effective lagswitch.

EDIT: I AM NOT TALKING ABOUT THE SUPER FAST TILES. MY BAD.

**Comment by optimumtact** [comment]
this is strange, all the tile does is make you fast, are you able to run a profile or does the server completeyl hang?

I'd love to see what's taking up the profiler time.

Possibly collision handling against the wall super fast or something

**Comment by ishitbyabullet** [comment]
Results on what happens without any chasms involved
![image](https://user-images.githubusercontent.com/29403316/77579581-ee53f300-6eb0-11ea-869e-7bb4beb9f713.png)
also, no, i think it's just fucking electricity sparks

**Comment by optimumtact** [comment]
Oh this is the hilbert hotel bluespace tiles

They are definitely not designed to be used outside the hilbert hotel context.

If the teleporter target ball doesn't exist you will just generate huge amounts of sparks.

**Comment by optimumtact** [comment]
Solution: Do not spawn open/space/bluespace

Longer term fix: only spawn sparks if the teleporter ball exists, or, alternatively, just don't use sparks.

**Comment by ishitbyabullet** [comment]
It was a quick mistake I had made to try and save someone's tank from a chasm.

I deeply apologize.

**Comment by optimumtact** [comment]
Hey man, it's was the end of round anyway.
