### ISSUE TITLE
When you fire a pie cannon at the cutout something inexplicable happens

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [tgstation/tgstation#50238]
## Reproduction:

Fire a pie cannon at the cutout, result in hilarity:

![image](https://user-images.githubusercontent.com/17705613/77671076-bff91500-6f8f-11ea-9503-c9a018f01c95.png)

**Comment by Sealed101** [comment]
i have no idea what the hilarity is because no matter how much i tried i could not hit it with a pie cannon.
