### ISSUE TITLE
Job-Specific vendor not giving discounted prices for that job

### ISSUE THREAD

**Issue by BOBAMAx** [tgstation/tgstation#50242]
## Round ID:
[133162](https://scrubby.melonmesa.com/round/133162)

## Testmerges:
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:
As the Chaplain, I had to pay out of pocket for my armaments beacon and any other clothes that would normally be free for chaplains, probably related to #50142. This also probably is the case for other civilian/service jobs, not that I can be bothered to check.
![Untitled](https://user-images.githubusercontent.com/49925269/77704100-5a565a00-6f8a-11ea-913e-baffe10488a1.png)

**Comment by cacogen** [comment]
you were roundstart, right?

**Comment by BOBAMAx** [comment]
yes

**Comment by Fikou** [comment]
f*ck
