### ISSUE TITLE
Plasmaman cops don;t spawn with plasma equipment, dying instantly.

### ISSUE THREAD

**Issue by Thezipper100** [tgstation/tgstation#50258]
## Reproduction:

-Step one: Play the Gangs gamemode as a plasma man
-Step two: Die.
-Step 3: respawn as a cop
-Step 4: Die again because the don;t have any plasmaman equipment

**Comment by ATH1909** [comment]
@Iamgoofball

**Comment by Tharcoonvagh** [comment]
Skelecops

**Comment by HomocidlePancakes** [comment]
Goodball code - amazing ideas, half-arsed.

**Comment by Iamgoofball** [comment]
ughhhhhhhhh, I'll look into blacklisting plasma skeletons

**Comment by ATH1909** [comment]
> ughhhhhhhhh, I'll look into blacklisting plasma skeletons

Or you could just make a special cop uniform for plasmamen?

**Comment by Thezipper100** [comment]
> ughhhhhhhhh, I'll look into blacklisting plasma skeletons

> Or you could just make a special cop uniform for plasmamen that has an envirosuit, a helmet, gloves, a mask, and a plasma (internals) tank in it?

Yea, should just be a quick copy-paste, that's what all the other Jobs do for plasmamen. You can even just C+P it from Sec's, if ya don't feel like coloring the suits, since Sec can't be gang anyway.

**Comment by Iamgoofball** [comment]
@ATH1909 sprite it and sure, until then plasma skeletons are blacklisted from cops

**Comment by Iamgoofball** [comment]
@Thezipper100 security and the cops are completely separate entities and any visual overlap would be extremely problematic

**Comment by Thezipper100** [comment]
> @Thezipper100 security and the cops are completely separate entities and any visual overlap would be extremely problematic

Fair enough.

**Comment by Mooshimi** [comment]
How is this going @Iamgoofball

**Comment by Iamgoofball** [comment]
cops were removed
