### ISSUE TITLE
[URGENT!] YOU CAN'T PIGGYBACK CATGIRLS ANYMORE

### ISSUE THREAD

**Issue by Tumesuo** [tgstation/tgstation#50255]
Issue reported from  Round ID: [133206](https://scrubby.melonmesa.com/round/133206) (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 513.1512

YOU CAN'T PIGGYBACK OR GET PIGGYBACKED

**Comment by Tumesuo** [comment]
https://www.github.com/tgstation/tgstation/pull/49065 is testmerged

**Comment by Tumesuo** [comment]
![dreamseeker_KCGbEHn9LP](https://user-images.githubusercontent.com/15519576/77759367-49b2ec00-703d-11ea-9bdf-ec9028d5720b.png)

**Comment by Tumesuo** [comment]
master commit: https://github.com/tgstation/tgstation/commit/0a51f49c8919f299d260d3bea6308d946224ca11

**Comment by Tharcoonvagh** [comment]
not funny didnt laugh

**Comment by ATH1909** [comment]
> not funny didnt laugh

I laughed, though.
