### ISSUE TITLE
Standing in rad storms in CE's hardsuit prevents mutations, but still causes your appearance to change.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#50263]
## Round ID:
Figure this out awhile ago

## Testmerges:
no clue

## Reproduction:
1. get in CE's hardsuit and put helmet up
2. wait for rad storm
3. wait for it to pass
4. put down helmet to find your hair has changed (and maybe your gender)

you take no toxin damage, rads or contamination during the rad storm, which is probably not a bug, but the hair change probably is.

**Comment by Dennok** [comment]
As i memory, you need CE jumpsuit equipped too.

**Comment by necromanceranne** [comment]
That was changed, the suit is 100% rad proof now

**Comment by dragomagol** [comment]
Does appear to have been fixed.
