### ISSUE TITLE
Hardsuit charge doesn't work

### ISSUE THREAD

**Issue by Archanial** [tgstation/tgstation#50265]
You can't remove cell (it disappers).
Power meter stays at 0.1% always.
When there is no cell it shows
![obraz](https://user-images.githubusercontent.com/37456678/77795066-3ddf1e00-706d-11ea-9a32-b5c70499db1c.png)

**Comment by Akrilla** [comment]
I can reproduce the "power meter shows !invalid", but I can properly remove the cell, and it's 100% as expected. When I drain it down to 0% it acts as expected.

**Comment by Akrilla** [comment]
And the !invalid! is expected too, not a bug.

**Comment by Archanial** [comment]
Well I tried to remove and insert power cell a few times before power meter getting stuck, so that may broke it.

**Comment by Akrilla** [comment]
Looking at this again since others have been able to reproduce
