### ISSUE TITLE
Boxstation incinerator outlet pump is unpowered

### ISSUE THREAD

**Issue by SamuelRowe** [tgstation/tgstation#50274]

**Comment by ArcaneMusic** [comment]
Translating the issue over to icebox from spacebox, but the issue appears to have been fixed along the way. The outlet pump is once again powered, as well as the outlet node as well.
![image](https://user-images.githubusercontent.com/41715314/99876201-40c1ec80-2bc3-11eb-8a32-e84e85f1ace3.png)
