### ISSUE TITLE
shooting ontop handtele portals teleports your bullets too

### ISSUE THREAD

**Issue by zeroisthebiggay** [tgstation/tgstation#50289]
## Round ID:

NA

## Testmerges:

NA

## Reproduction:

go through a handtele portal
try and shoot
bullet goes through the portal rather than outwards
pretty disorientating and confusing

**Comment by TheVekter** [comment]
99% sure this is working as intended. Just so we're clear, you're saying if you fire through a portal, it teleports through it? I know it comes out the other side when you do this with the portal gun.

**Comment by tgsAvylaar** [comment]
I think this is working as intended. If you shoot through a portal, the laser or projectile teleports through as well?

**Comment by Neo-0** [comment]
I think he meant about being in the same tile as the portal and shooting

**Comment by timothymtorres** [comment]
Looks intended.
