### ISSUE TITLE
Reality Broke

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#50287]
## Round ID:
[133333](https://scrubby.melonmesa.com/round/133333)

## Reproduction:
I have literally no clue what happened, im sitting as HOS in the chair to the left of the shuttle console when captain comes up and tries to pin a award on my jumpsuit when the screen freezes, i attempt to reconnect using the button in game and the screen goes black, but otherwise nothing happens, check the server list, manual is broken.
Attempt to rejoin and find this:
![_tg_Station Manuel  ENGLISH   US-WEST   ROLEPLAY   99% LAG FREE _ John Madden 13 3_28_2020 10_25_21 PM](https://user-images.githubusercontent.com/61719178/77838637-e2339400-7143-11ea-8f4d-bb8c1b1e1188.png)

**Comment by redguy999** [comment]
the box in the top right was fine and so were the tabs, i have no clue what is happening

**Comment by Twaticus** [comment]
this just looks like a normal out-of-memory server crash?
