### ISSUE TITLE
Able to move while in stamina crit

### ISSUE THREAD

**Issue by Akrilla** [tgstation/tgstation#50296]
It's expected that the moment you're in stamina crit, you're not able to move.

## Reproduction:

Seen in event hall, tested on local, definitely an issue.

Hit with stun baton, see usual delayed knockdown and able to crawl etc.
Hit again after cooldown, see yourself in stamina crit, but still able to crawl away.

**Comment by ATH1909** [comment]
can we get a "FUCK" label for this?
