### ISSUE TITLE
"The Arena" shuttle just sends you to space

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#50298]
## Testmerges:

#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:

-kill bubblegum
-buy arena shuttle
-wait 50 minutes for it to come
-hell yeah deathmatch time
-go in
-ok im in space i guess time to die

**Comment by Mazzlul** [comment]
same

**Comment by Fikou** [comment]
same

**Comment by Glassmanner** [comment]
yeah all the crew who tried to get on the shuttle got teleported to space

**Comment by ShibaInuLord** [comment]
this has been broken for like 9 months now and no one's fixed it

**Comment by gitbirb** [comment]
hope this gets fixed because it ruins an otherwise fun-sounding shuttle

**Comment by Fikou** [comment]
the fix anturk told me to do didnt work >w<
