### ISSUE TITLE
hats thrown at you are unblockable for normal people

### ISSUE THREAD

**Issue by TheWiznard** [tgstation/tgstation#50291]

**Comment by Dennok** [comment]
## Round ID:
[133382](https://scrubby.melonmesa.com/round/133382)
## Testmerges:
#49065: 'Disable library machine uis' by optimumtact at commit [f261fc0](https://github.com/tgstation/tgstation/commit/f261fc0b456a340ce6bdc207f2213d292fe63fdb)
## Reproduction: 
take a hard hat throw it at anyone that's not the chaplain, no matter what they do they lose their hat and its replaced with a hard hat. I think its a cool feature but I also think it makes sense you can use the throw intent to catch it if its thrown at you but currently you can't and its basically unblockable unless you're the chaplain
