### ISSUE TITLE
unbolting nukes by removing floor tile under the nuke

### ISSUE THREAD

**Issue by gitbirb** [tgstation/tgstation#50305]
## Round ID: 
none specific really, it has happened a ton though and borgs love to abuse it.

## Reproduction:
remove the floor under a bolted nuke with a RCD and it becomes unbolted. I've seen people abuse this a lot to completely fuck over nukies.

heres how it would happen in a normal round:
1. nukie get disky, put in nuke, activate+bolt.
2. borg or someone finds nuke and is ANGRY they can't unbolt it because no disky inside nuke!
3. borg or person decides the only way to unbolt it is to remove the floor tile underneath the nuke which successfully unbolts the nuke. Done by a RCD usually but can probably be reproduced with other ways to remove floor.

(not part of bug but still important as to the importance of why this is a bad thing which is very obvious) 
4. borg or person spaces nuke and nukies basically lose.
-------
(note: I think this also works on bolted bombs (payload bombs/syndie bombs))

**Comment by Akrilla** [comment]
Floor tile, or removing the entire tile so it's just space?

**Comment by Dennok** [comment]
> Floor tile, or removing the entire floor so it's just space?

Removing the entire floor so it's just space.

**Comment by Akrilla** [comment]
Hard to know what a decent solution is then I guess, maybe having someone bolted disallows deconstruction with at least the RCD

**Comment by cacogen** [comment]
what's the proper counterplay at this point?

**Comment by Tumesuo** [comment]
That's kinda the only way to fuck over nukies now tbh, Why don't the gamers just wait until it has enough time not to be taken away before dragging it to the station/protect it/hide it.
