### ISSUE TITLE
genetics gamer trick

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#50311]
![image](https://user-images.githubusercontent.com/42606352/77957313-efae6280-7298-11ea-8b1d-b6f8ae9ab3ad.png)

Sorry, I had thought that this trick had already been reported.

Basically, turning someone into a monkey and then back into a human makes all of their mutations that normally would be scrambled and unreadable by the DNA console able to be read and discovered by the DNA console (I'm unsure how this interacts with, say, the chameleon changeling power's chameleon mutation or a clown's clumsiness mutation, which normally aren't even visible in the console). The primary use for this (that I've found) is to feed a monkeyman 10 or so microdoses of unstable mutagen (which has a 98% chance per dose to activate and scramble one of the monkeyman's **non-positive**, non-monkey mutations (the other 2% of the time, it tries to activate a positive mutation)), then monkify them, then unmonkify them. This (usually) lets you know discover all of their negative mutations (and very rarely one of their positive mutations) so that you can focus on getting their positive mutations.

Getting the mutagen usually takes a bit, though, and sometimes the other geneticists have discovered enough of the negative mutations by the time I get back to Genetics that the mutagen trick isn't even worth doing instead of normal genetics-work. IMO, it cuts out some of the tedium and disappointment of finally solving a tough to crack gene, only to find out that it's just chav or something. Still, I figured that I was kind of obligated to report this, so here we are.

**Comment by Timberpoes** [comment]
I'm going to look into this. I know why it happens.

Default mutation information is stored in the DNA's mutation_index assoc list. This isn't an index like in an array, but an index like in a book. The list's keys are of mutation type paths and the list contains 7 random mutations (the ones gained on init or gain when DNA is scrambled in the DNA Console/Scanner etc.) and returns the associated "live" gene sequence. It has no metadata.

Monkeys cannot have active mutations other than Monkified. When you mutagen a monkey, it fills out the gene sequence in (TG AC pairs) mutation_index to be complete but never actually creates an active mutation with all the relevant mutation metadata. This effectively creates a class of "dormant" mutation - One that has all TA GC pairs solved but is still inactive and has no metadata. In other words - Mutagen'ing a monkey doesn't create active, scrambled mutations, it creates dormant unscrambled mutations that are immediately activated on humanization.

When you humanize the monkey, it copies over the mutation_index as-is, including all those dormant mutations. As you can probably tell by now, this means that every mutation that the mutagen touched will now all activate (as the AT GC pairs are already solved) and even better, they won't be scrambled!

Even better - When going from human to monkey, no mutation metadata is saved. All your non-default mutations are removed. So you mutagen a humen and monkeyize it, and all their solved AT GC pairs from the mutagen are retained in mutation_index, but all their mutation metadata is discarded. Then you go to the monkey -> human step above and realise... They'll be transformed back with all their scrambled mutations activated and unscrambled.

I can only put forward one simple solution
Scramble AT GC sequences when going from human to monkey to human. What does this mean? If you get monkified, you will have lost all your active mutations when you're re-humanised and their AT-GC sequences will be scrambled up again.

An alternative solution could be storing the additional metadata in a new var/mutation_scrambled_index = list() and setting a scrambled flag as appropriate for each default mutation. To my understanding, mutation scrambling is permanent until "Nullify"'ed in a DNA Console so this would allow a persistent state to be kept across monkey/human transformations. It'd be kinda ugly and there'd be some legacy stuff leftover (would mutations need to still store their own .Scrambled state?)

As a side note, I BELIEVE those special mutations (like the Clown's clumsy) are infact "Traits" and not mutations, and don't utilise the mutation system at all. It's not that Clowns have the Clumsy mutation, but that the Clumsy mutation gives people the same traits that Clowns have (for example).

**Comment by Timberpoes** [comment]
The dna datum has a "scrambled" var.

`var/scrambled = FALSE //Did we take something like mutagen? In that case we cant get our genes scanned to instantly cheese all the powers.`

Fun fact? This functionality. Never implementd. There's possible state where the dna's scrambled status is set to TRUE.

Instead, individual mutations have their scrambled status set during easy_randmut.

I plan to implement the DNA scrambled status above the mutation scrambled status. This would mean a few FUN things where the following would scramble the person's DNA, making it unreadable in DNA Scanners/DNA Consoles:
https://github.com/tgstation/tgstation/search?q=%22easy_randmut%22&unscoped_q=%22easy_randmut%22

Radiation storms
A podperson being hit by /obj/projectile/energy/floramut
Diseases with genetic mutation symptoms
Monkeys and humans that get highly irradiated
Acquiring the bad_dna mutation
**Mutagen**

And the following methods will cure scrambled DNA:
https://github.com/tgstation/tgstation/search?q=remove_all_mutations&unscoped_q=remove_all_mutations

Diseases with genetic mutations symptoms "ending"
Genepurge implants
Accepting a ghost role question mark?
DNA Scanner/Console mutation scrambling
Using mutadone on a monkey to turn it into a human question mark?
Clearing mutations in VV
Becoming immune to radiation

**Comment by SuperNovaa41** [comment]
This does not happen anymore. Either that, or the reproduction steps are incorrect. Closing it.
