### ISSUE TITLE
Instantaneous Death Bug

### ISSUE THREAD

**Issue by steampunch** [tgstation/tgstation#50314]
## Round ID:
[133478](https://scrubby.melonmesa.com/round/133478)

## Reproduction:
As a geneticist I found and got hulk, TK, and X-ray vision, and had all three in me (no mutation OD because of stabilizer chromosome). I was minding my business wearing fireproof potion clothing, and a security officer accidentally punched me. I died instantly, with no indication of rising damage or anything, just instant death. After I got revived, I continued the shift until later when I got hit by objects from a grav anomaly. The amount of objects was not enough to kill anyone else, but I once again died instantly. There was no flavor text to indicate some unusual thing killed me, and I was able to be revived fairly easily.

**Comment by ATH1909** [comment]
You did, in fact, suffer a genetic meltdown.

```
			if(4)
				to_chat(src, "<span class='notice'>Oh, I actually feel quite alright!</span>") //you thought
				physiology.damage_resistance = -20000
```

**Comment by ATH1909** [comment]
Hulk+TK+x-ray will bring you to an instability value of 105, which should be enough for a meltdown to have occurred. Are you sure that you correctly applied your stabilizer chromosome? Did you lose all of your mutations suddenly after picking up your third one? If not, then something is very wrong here.

**Comment by steampunch** [comment]
Oh, I did OD on mutations before, but I had thought that you could tell if you have the genetics meltdown death disease from medical scanners. Guess it wasn't a bug. Thanks for clarifying.
