### ISSUE TITLE
You can engage in unarmed combat even when in stamcrit

### ISSUE THREAD

**Issue by Pugie** [tgstation/tgstation#50325]
Title: you can be in stamcrit and still be able to shove people and punch them. Makes arresting nigh on impossible and necessitates using lethal force, pretty bad.

**Comment by Akrilla** [comment]
This after or before #50297 ?

**Comment by Pugie** [comment]
After

**Comment by ExcessiveUseOfCobblestone** [comment]
post `see-server-revision` so we can see what commit the server you're running on is at.

**Comment by ExcessiveUseOfCobblestone** [comment]
copypasta `show-server-revision`

**Comment by ExcessiveUseOfCobblestone** [comment]
nvm i tested it on EH

**Comment by ExcessiveUseOfCobblestone** [comment]
when you're stamcritted you are not getting the trait for incapacitated.
