### ISSUE TITLE
Crawling under someone causes you to swap

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#50322]
## Reproduction:
The first time you get under someone, it swaps you. If you get up and swap with them again, the next time you crawl under them will swap again.

**Comment by Pugie** [comment]
I don't think it is recognised that you're resting at all. You can't fit in crates and if someone is on any intent bar friendly you cannot move past.

**Comment by Akrilla** [comment]
why are a ton of movement related things breaking

**Comment by kriskog** [comment]
Movement speed refactor following a canpass refactor a while ago, most likely

**Comment by Dennok** [comment]
i think this issue related to bullets and corpses and crawqlig people. Somewhere check inverted
