### ISSUE TITLE
you can't insert plasma into advanced welders

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#50329]
I can't find any way to get plasma into expanded capacity (80u) welders, even though they have a special interaction for if they have plasma in them. I haven't done much testing with 20u welders yet, but it looks like they also can't be filled with plasma in any (non-admin intervention-related) way.

**Comment by Dennok** [comment]
As i see code, you need unsecure welder by screwdriver and use beker on it,
empty welder before this.

**Comment by ATH1909** [comment]
ah, I see now, I was just being a dingus.
