### ISSUE TITLE
Flowers in hair dont work with cat ears :sob:

### ISSUE THREAD

**Issue by Tumesuo** [tgstation/tgstation#50328]
![dreamseeker_ugFxXGlhmA](https://user-images.githubusercontent.com/15519576/78065336-d17d5b00-739b-11ea-83fb-d6995a5c51ae.png)
![dreamseeker_uCGYTtYKUG](https://user-images.githubusercontent.com/15519576/78065339-d2ae8800-739b-11ea-83a2-2dd439cdb52e.png)
![dreamseeker_T5rGBFwdJs](https://user-images.githubusercontent.com/15519576/78065344-d2ae8800-739b-11ea-86aa-2224a5b5646c.png)

Issue reported from  Round ID: [133549](https://scrubby.melonmesa.com/round/133549) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1512

**Comment by ATH1909** [comment]
this is so sad, gamers

**Comment by GunHog** [comment]
There is a limit on how cute someone is allowed to be.

**Comment by PKPenguin321** [comment]
ears rendering below the flower might look weirder but idk

**Comment by Dennok** [comment]
flowers in cat ears

**Comment by Mooshimi** [comment]
Fixed by a PR
