### ISSUE TITLE
You cannot shoot any projectile over anyone lying down or dead.

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#50332]
## Round ID:
[133563](https://scrubby.melonmesa.com/round/133563)

## Testmerges:
#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:
Have anyone resting or dead ahead of you, try to shoot the tile behind it, the projectile hits the person resting or dead.

**Comment by Tharcoonvagh** [comment]
Doop
