### ISSUE TITLE
yet more issues with building hygienebots

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#50339]
1. I believe that this has already been reported before, but using a stack of fluid ducts when performing the final step of making a hygienebot consumes the entire stack, even though only one duct needs to be consumed for the recipe.
2. Clicking on a hygienebot assembly that is in its last stage before completion (in other words, it just needs piping) with any non-duct object seemingly deletes that object. I'm not sure if it goes into the hygienebot assembly, or what, but I kind of want to test to see what happens if you use a pAI or a brain (or a head) with this bug now.
3. When performing the final step of making a hygienebot, the fluid ducts you're applying to the hygienebot get deleted and a do_after starts. When the do_after ends, the hygienebot is created. I recently discovered, however, that that do_after doesn't have to end SUCCESSFULLY in order for the hygienebot to be created. In other words, hygienebot construction now has a speed tech: moving to the side immediately after starting that last do_after() to hasten the construction of the hygienebot.

**Comment by ATH1909** [comment]
Also, people are reporting that hygienebots might not be able to successfully clean people who are wearing hardsuits, and will thus follow them forever until they take off their hardsuit. I can't verify whether or not this bug is a actually a thing, but from what I've seen, it very well could be.

**Comment by cacogen** [comment]
yeah i reported that here https://github.com/tgstation/tgstation/issues/50191
