### ISSUE TITLE
paper hat doesnt appear on sprite for moths

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#50347]
Issue reported from  Round ID: [133659](https://scrubby.melonmesa.com/round/133659) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1514

**Comment by RiskySikh** [comment]
I tested it out, and it worked for me when I was moth.

**Comment by redguy999** [comment]
i think i just couldnt see it, closing
