### ISSUE TITLE
Plumbing machines and issues with wrenching/rotation

### ISSUE THREAD

**Issue by Akrilla** [tgstation/tgstation#50350]
![image](https://user-images.githubusercontent.com/18756865/78209578-556c3b80-749f-11ea-9970-4439ca830c65.png)

Blue/red pipes don't properly line up graphically with where the game thinks they are. They also don't seem to be able to be rotated at all, sometimes with the machine permanently being stuck in a certain direction, while graphically the pipes/sprite moves fine.

Synthesizers get stuck in directions with specific chemicals, and also have issues with resetting their location after any chem change.

Chem tanks randomly get stuck with blue on left and red on right, regardless of being rotated graphically.

Filters have their left and right switched sometimes.

**Comment by Time-Green** [comment]
Haha april fools, you guys thought I fixed the bug while in reality I made plumbing completely unusable

**Comment by tgsAvylaar** [comment]
@Time-Green 
Based expert Plumber
