### ISSUE TITLE
seeds from the seed vendor dont have their plant traits

### ISSUE THREAD

**Issue by triplezeta** [tgstation/tgstation#50366]
## Reproduction:

1. buy seed from seed vendor, preferably one with plant traits
2. plant plant
3. scan plant
4. notice how the plant doesn't have any of their innate traits

the wackiest part about this is when you get a plant graft from a plant, it WILL have the traits that plant is supposed to have, and you can graft that onto a plant and it will have the plant trait.

**Comment by Akrilla** [comment]
Fixed by #50369
