### ISSUE TITLE
so saltpetre is bugged too

### ISSUE THREAD

**Issue by triplezeta** [tgstation/tgstation#50368]
## Round ID: 
Localhosted with most recent code, after https://github.com/tgstation/tgstation/pull/50001 was merged.

## Testmerges:
https://github.com/tgstation/tgstation/pull/50001
## Reproduction:

1. pour in saltpetre
2. wait
3. notice that potency and production speed are not changing, at all. 

mm yes 5 potency ambrosia vulgaris yum

**Comment by cacogen** [comment]
great

**Comment by Akrilla** [comment]
Fixed by #50369
