### ISSUE TITLE
Plants have to be forcefully grafted to obtain traits that should be innate for themselves. No plants have innate traits whatso ever.

### ISSUE THREAD

**Issue by TheObserver-sys** [tgstation/tgstation#50367]
## Round ID:
No Round ID, Tested Locally.

## Testmerges:
https://github.com/tgstation/tgstation/pull/50001

## Reproduction:
Scan/Grow Apples, or Tomatoes, or Bananas, observe as they do not have any of their innate traits that they should have by default. Uncertain if this is intentional, but if so, this is going to double the time to get even basic plants online.

**Comment by Akrilla** [comment]
Fixed by #50369
