### ISSUE TITLE
Runtime on the PENLITE defibrillator mount

### ISSUE THREAD

**Issue by WarlockD** [tgstation/tgstation#50376]
## Round ID: [133857](https://scrubby.melonmesa.com/round/133857)
 [01:43:10] Cannot read null.cell

Basically there isn't a defib in the mount.
Found the line of code that does it
````
if(defib?.cell?.charge < defib.cell.maxcharge && is_operational())
    use_power(100)
    defib.cell.give(80)
    update_icon()
````

? has a higher priority than < so the defib.cell.maxcharge causes the issue

**Comment by Timberpoes** [comment]
I'll push a fix when I get out of bed. Runtimes are bad.

I can see what's happening here. If theres no defib it still tries the comparison anyway, equivalent to if(defib < defib.cell.charge.maxcharge ...) where defib is null.

I'll pull out a separate guard check before attempting the comparison so it just won't happen on null defibs or defibs with null cells. Should solve it.
