### ISSUE TITLE
More issues with New Botany.

### ISSUE THREAD

**Issue by TheObserver-sys** [tgstation/tgstation#50373]
## Round ID:
[133834](https://scrubby.melonmesa.com/round/133834), On Sybil

## Testmerges:
https://github.com/tgstation/tgstation/pull/50001
https://github.com/tgstation/tgstation/pull/50369

## Reproduction:
A list of issues from playing an hour+ long round of botany. Hopefully these aren't major breaks.
1. Instability isn't functioning at all. Tried it on watermelons and cherries, pushing their instabilities from 0 to every single threshold. Every threshold broken did not apply any stat changes to the plant, nor caused them to mutate into something else, regrettably. Neither through L4Z nor Mutagen.

2. Radium and Uranium do not function at all for plants, except as a powerful poison, when it should mess with stability as a worse alternative to mutagen.

3. Robust Harvest is for some reason, only buffing Potency, and not Yield, despite it supposed to be otherwise.

4. No plants traded chems, even when doing some cross pollination experiments to see if I could even move Corn Oil to a cherry.  

5. This one is a holdout from the first drop of the botany PR, but when I go for cuttings, half of them don't show up, which can be a pain when trying to figure out if you just got liquid contents, or perennial growth from a tomato plant.

**Comment by Angustmeta** [comment]
5. Yeah grafts turn invisible for me about half the time. 

I also wonder if you can remove genes from a plant somwhow. Hard to make specific creations if you can only add and never remove.

**Comment by ArcaneMusic** [comment]
Removing plant genes was a complete oversight and I'm shocked it didn't come up in the 3 weeks the PR was up. I'm working on an alternative right now, but I'm getting on these issues and the invisible grafts tonight.
