### ISSUE TITLE
Improvised jetpack doesn't work

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#50396]
Issue reported from  Round ID: [133905](https://scrubby.melonmesa.com/round/133905) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507

repro steps:
craft an impro jetpack
try to turn it on

**Comment by tgsAvylaar** [comment]
Is there air in it? Or Oxygen?

**Comment by Tharcoonvagh** [comment]
I used oxygen

**Comment by Hamcha** [comment]
I tried oxygen and CO2, neither worked. You get a button and it says "You turn the jetpack on" (never off) but it changes nothing. I also tried raising the pressure valve but nada
