### ISSUE TITLE
Screwdrivering Rechargers makes them uninteractable

### ISSUE THREAD

**Issue by tgsAvylaar** [tgstation/tgstation#50390]
## Reproduction: 

When you screwdriver a recharger, on station or in space, they become invisible and uninteractable. If it was wrenched, and thus on when you did it, you'll see the recharger's red light blinking, and if you right click it, you see that the texture changed to white/nothing. The recharger itself stays invisible.

You can never get the board out, as you can never interact with them with a crowbar.

Here you see an example of the right click invisible texture the recharger became.
And the red light of the recharger flickering.

![dreamseeker_yTP9LCFv4c](https://user-images.githubusercontent.com/63151598/78452440-8ad57c80-768b-11ea-8161-cbe7287a6847.png)
![dreamseeker_IWUPXRw4GD](https://user-images.githubusercontent.com/63151598/78452435-89a44f80-768b-11ea-8b3e-b6df5f7fa6b0.png)

**Comment by ATH1909** [comment]
Are you talking about gun rechargers or cell rechargers?

**Comment by zxaber** [comment]
Examine text hints at it being the gun recharger.

**Comment by tgsAvylaar** [comment]
@ATH1909 Gun rechargers, I haven't tested the cell rechargers.
These are handy to transport during blob rounds, or for space exploration.
