### ISSUE TITLE
Plumbing Machines Layout Misaligned / Visual Bug

### ISSUE THREAD

**Issue by tgsAvylaar** [tgstation/tgstation#50392]
## Reproduction:

If you edit any plumbing machine's ingame settings AFTER wrenching them down AFTER having turned them around by ALT-clicking them, the visual alignment of the machine resets to it's initial (north-facing) alignment. 
Functionally, the machine remains aligned as per how it was wrenched, but visually, the pipes don't match.
Your machine is then, visually misaligned. If you then forget how you placed it, it's trial and error to find the right connections.

This is easily reproduceable with eg. The synthesizers, heaters, mixers,...

I'll upload a picture once I can log on my home computer.

On the following picture, you can see half the structures misaligned - the synthesizers on top and east, the mixers, the heaters. The pipes only connect / attach to the structures if they are functionally connected.
To those interested, the misalignment I talk about is the small input / output pipes that come out of the structures, that visually reset to an earlier state after having turned them around.

![dreamseeker_sIDi9NtSqm](https://user-images.githubusercontent.com/63151598/78452147-de46cb00-7689-11ea-81b8-cfb5cf091937.png)

Here, the heaters are misaligned (round structures).
![FVw2ylf5tK](https://user-images.githubusercontent.com/63151598/78452109-a3dd2e00-7689-11ea-9203-1470076b7a29.png)

**Comment by Time-Green** [comment]
This was fixed yesterday and those images are four days old

Thanks for giving me a heart attack though

**Comment by Time-Green** [comment]
I cannot reproduce this on the most recent build

**Comment by tgsAvylaar** [comment]
Ah, thanks a lot for the good work!
Yeah, I've only gotten to this right now :).
