### ISSUE TITLE
Metastation CMO spawns without a stamp in his office.

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#50419]
## Round ID: NaN
(Did not discover this issue from playing a specific round on tgstation hosted servers)

## Testmerges:

#49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:

Join round as CMO, hark, there's no fucking stamp in your office as there should be, generally speaking all the heads are meant to have stamps AFAIK

![image](https://user-images.githubusercontent.com/14065903/78513092-37d8f380-7777-11ea-9d6c-491dfb28f497.png)

**Comment by Akrilla** [comment]
I swear they used to have one but I checked as well and they definitely don't have it
