### ISSUE TITLE
Prisoner latejoin FOR GODS SAKE

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#50416]
![Screenshot_20200405_214357_com android chrome](https://user-images.githubusercontent.com/54288658/78508384-c99c2d00-7786-11ea-865d-2e2ce1237784.jpg)

**Comment by kriskog** [comment]
Might be the bureacratic error event, and if it is its kinda funny.

**Comment by trollbreeder** [comment]
Cyborgs can also latejoin due to bureaucratic errors. Please do not fix that because cyborg latejoining is also really funny

**Comment by kriskog** [comment]
cyborg is intentional, only AI is excempt (because it didnt work out of the box)

**Comment by Googles-Hands** [comment]
This is an very easy config change, could you please take an look at it?

**Comment by kriskog** [comment]
Checked the log for the round
```[2020-04-05 16:07:14.357] GAME: Random Event triggering: Bureaucratic Error (/datum/round_event/bureaucratic_error)```
Its as I thought, not a bug.
