### ISSUE TITLE
Plant gene manipulator circuit boards still exist and are in the botany research node

### ISSUE THREAD

**Issue by trollbreeder** [tgstation/tgstation#50417]
## Testmerges:
49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:

Step 1. Go to science
Step 2. Research the nodes electromagnetic technology, industrial engineering, advanced engineering, and biological technology (optional)
Step 3. Look at the botanical engineering node.
![image](https://user-images.githubusercontent.com/25937686/78510072-ef2f3380-7792-11ea-97c9-4dd471c2f8fa.png)
Gosh darnit arcane, you weren't even trying
#bringbackplantgenemanipulator2020

**Comment by ArcaneMusic** [comment]
Fuck
