### ISSUE TITLE
Mad Scientist Special kit does not include a functioning Portal gun

### ISSUE THREAD

**Issue by ominousgrace** [tgstation/tgstation#50437]
Honestly, this is a complaint and not a bug report. The Portal gun was nerfed to require the loading of an anomaly core. This indirectly nerfed the Mad Scientist Syndie special kit. I believe that this portal gun should come pre-loaded and ready for use straight away. No Budget cuts for the syndicate!

**Comment by itseasytosee** [comment]
Seems like an oversight yeah

**Comment by TheVekter** [comment]
My bad on this one - I forgot that the kit came with one and didn't bother making a new variant. Mea culpa!

**Comment by wesoda25** [comment]
shit i thought this had been broken ever since i added it for a sec
