### ISSUE TITLE
Plasmamen cant wear the atmos helmet

### ISSUE THREAD

**Issue by Trumpetplaya288** [tgstation/tgstation#50451]
Seems like they should be able to considering that the helmet protects against pressure and they can already wear insulated gloves
lmk if the helmet is supposed to be sacred never-ever-take-off gear though

**Comment by itseasytosee** [comment]
You can here's a picture
![image](https://user-images.githubusercontent.com/55666666/78726072-ae502f80-78f6-11ea-87e3-1461be7c750a.png)

I believe all helmets with the THICKMATERIAL flag can be used to keep your plasma skin unburnt. The almost helm is not space proof and therefore does not have this flag.
This does not seem like an oversight to me

**Comment by Fikou** [comment]
heres how plasmaman code works:
if the currently worn suit is the plasmaman suit and the currently worn helmet is the plasmaman helmet you're ok
if you wear a pair of suit and helmet (for example hardsuit or atmos helmet with an atmos suit) that makes you immune to pressure damage you're ok
everything else is not ok

**Comment by necromanceranne** [comment]
I'm fairly sure the atmos firesuit helmet made you pressure proof before. I've seen plenty of plasmamen use it in the past and used it as a ghetto space suit a few times with cryox from maint.
