### ISSUE TITLE
Botanist Plant Bag Heirloom Spawns In Pockets, Causing it to drop upon spawning.

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#50472]
## Round ID:
[134230](https://scrubby.melonmesa.com/round/134230)

## Reproduction:
Either latejoin or roundstart join as botanist, watch as your plant bag heirloom drops to the ground as it spawns in your pockets, but now it cannot be in your pockets as it's size was changed to bulky by #50292.

**Comment by ATH1909** [comment]
okay, now this is epic
