### ISSUE TITLE
tgui: CSS fails to load properly

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#50480]
## Reproduction:

Formatting was busted on some interfaces. They were perfectly functional, they just didn't have any styling. This survived multiple reconnections, and round transition. It did not survive a full client restart.

1. Join the game
2. Open an affected interface
3. Behold

<details>
<summary>Affected GUIs: (This is a spoiler, click me for PNGs)</summary>

![TGUI is akdhgsdfkhas](https://user-images.githubusercontent.com/53582584/78840842-b2d91e80-79b0-11ea-95bd-a820fe1fb2da.PNG)
![APC GUI](https://user-images.githubusercontent.com/53582584/78840849-b8ceff80-79b0-11ea-8145-e479edacc128.PNG)
![vendor1](https://user-images.githubusercontent.com/53582584/78840854-ba002c80-79b0-11ea-8bf8-7789052a61b1.PNG)
![vendor2](https://user-images.githubusercontent.com/53582584/78840856-bbc9f000-79b0-11ea-8b27-8cb26f40e014.PNG)
![TGUI_is_broken](https://user-images.githubusercontent.com/53582584/78840863-bf5d7700-79b0-11ea-943f-4ec26182453c.PNG)
![PACMAN GUI](https://user-images.githubusercontent.com/53582584/78840947-ffbcf500-79b0-11ea-958b-e51b2f1dcf17.PNG)
![CANISTER GUI](https://user-images.githubusercontent.com/53582584/78840952-00ee2200-79b1-11ea-83c9-93ed09160e71.PNG)
![APC GUI2](https://user-images.githubusercontent.com/53582584/78840956-02b7e580-79b1-11ea-968b-ef77300b7135.PNG)
![ORM GUI](https://user-images.githubusercontent.com/53582584/78840963-051a3f80-79b1-11ea-8cf2-c82d8f2ac5c0.PNG)
![SUP REQ CON GUI](https://user-images.githubusercontent.com/53582584/78840965-06e40300-79b1-11ea-9c7d-a5cd14caa37e.PNG)
![intercom gui](https://user-images.githubusercontent.com/53582584/78840966-08adc680-79b1-11ea-904b-d00d4bc8c1c4.PNG)
![Disposal GUI](https://user-images.githubusercontent.com/53582584/78840969-09def380-79b1-11ea-8e96-b40c86366757.PNG)
![TGUI](https://user-images.githubusercontent.com/53582584/78840972-0ba8b700-79b1-11ea-98d5-8636b9346dae.PNG)
![Surgery GUI](https://user-images.githubusercontent.com/53582584/78840975-0cd9e400-79b1-11ea-9300-68f97e5f7438.PNG)
![GUI](https://user-images.githubusercontent.com/53582584/78841017-27ac5880-79b1-11ea-9bd9-93b4e5988127.PNG)
</details>

<details>
<summary>Unaffected GUIs: (This is another spoiler, click me for
PNGs) (Apparently all of these are HTML)</summary>

![Why are PDAs not](https://user-images.githubusercontent.com/53582584/78840919-e9af3480-79b0-11ea-8c21-8c4a46bc3b59.PNG)
![Why is this one fine](https://user-images.githubusercontent.com/53582584/78841008-1f541d80-79b1-11ea-9038-15260e60c7cb.PNG)
![survivor](https://user-images.githubusercontent.com/53582584/78841012-211de100-79b1-11ea-8d63-ff5e3d423ef0.jpg)
![Autolathe GUI](https://user-images.githubusercontent.com/53582584/78841029-2f6bfd00-79b1-11ea-9361-1c7e796df49b.PNG)
![Techfab GUI](https://user-images.githubusercontent.com/53582584/78841030-309d2a00-79b1-11ea-91c6-f29d9b701f52.PNG)
![AI Request GUI](https://user-images.githubusercontent.com/53582584/78841034-3266ed80-79b1-11ea-8060-db89ebc4ad0f.PNG)
![News GUI](https://user-images.githubusercontent.com/53582584/78841037-33981a80-79b1-11ea-87ff-fb977205279a.PNG)
![Strip GUI](https://user-images.githubusercontent.com/53582584/78841041-3561de00-79b1-11ea-8128-7800d974e8dc.PNG)
![Medical Records GUI](https://user-images.githubusercontent.com/53582584/78841048-385cce80-79b1-11ea-9115-a50ae0699874.PNG)
![Medibot GUI](https://user-images.githubusercontent.com/53582584/78841050-3a269200-79b1-11ea-9f74-c617790e3332.PNG)
</details>

**Comment by ArcaneMusic** [comment]
All the uneffected GUIs are HTML.

**Comment by trollbreeder** [comment]
congratulations you've unlocked nostaligia HTML mode

**Comment by Iamgoofball** [comment]
What is your windows version?

**Comment by TemporalOroboros** [comment]
OS Name: Microsoft Windows 10 Home
Version: 10.0.18362 Build 18362
