### ISSUE TITLE
You can't leave away missions

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#50498]
<img width="1437" alt="brokenawaymission" src="https://user-images.githubusercontent.com/42606352/79516365-cddf0a80-8010-11ea-846c-fe2b6ee465ae.PNG">
<img width="587" alt="gatewaybug2" src="https://user-images.githubusercontent.com/42606352/79516368-cfa8ce00-8010-11ea-9e36-2ef539c99014.PNG">
I suspect that https://github.com/tgstation/tgstation/pull/49868 is probably the cause of this.

This has been a consistent problem on Fulpstation, to the point where admins are now deleting the gateway portals at roundstart every round because people kept getting stuck in them.

@AnturK

**Comment by ATH1909** [comment]
Steps to reproduce:
1. Use the fancy console to open up the station's gateway portal.
2. Step inside, beat the away mission, get to the exit gateway.
3. Find that you are unable to open a portal out. An admin said that this happens because the station's gateway portal is already considered to be "in-use" (because it's active and pointing at the away mission; presumably, having someone close the station's gateway portal will allow you to escape), but I don't have any evidence that that claim is correct.

**Comment by Supercon22** [comment]
Gateways need reworking in general. I can't seem to load away missions at all. The readme is like 5 years old and every bit of information online is outdated.
