### ISSUE TITLE
Manuel almost consistently crashes when a round is close to 2 hours.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#50501]
## Round ID:

The last round in Manuel between 134910 and 134913, no logs saved because crashes.

## Testmerges:

#50484

## Reproduction:

Rounds in Manuel usually take longer than other servers, it will sometimes crash at random, but it's very usually that it happens once a round gets past the 1h40m mark, almost being a guarantee that it happens at the 2 hour mark.

**Comment by optimumtact** [comment]
Without more information from the keyholders about the kind of crashes experienced I can't adequately diagnose the issue.
