### ISSUE TITLE
Simple mobs continue to attack ling corpse after they enter revival stasis

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#50500]
## Round ID:
Don’t remember

## Reproduction:
1. Be ling
2. Get attacked by simple mobs
3. Enter revival stasis
4. Watch as they continue to beat you until you actually die.

**Comment by dragomagol** [comment]
Appears to have been fixed (tested with a horde of hostile simplemobs)

**Comment by redguy999** [comment]
> Appears to have been fixed (tested with a horde of hostile simplemobs)

Did you enter stasis before or after you died?

**Comment by dragomagol** [comment]
Before

**Comment by redguy999** [comment]
then this can stay closed.
