### ISSUE TITLE
Teslas blow up random shit in contaiment

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#50506]
Setting up a tesla in the delta containment will cause this. No idea what causes it, I assume it has to do with the singularity parent path. We shall see.

**Comment by kriskog** [comment]
Teslas will blow up unanchored machinery around containment

**Comment by LemonInTheDark** [comment]
You misunderstand. The things that are blowing don't seem to be the machines, it appears to be caused by the singulo consume parent proc. My current fix for this is to override consume at the tesla level, more details when I get the pr up.
