### ISSUE TITLE
You can double (and triple?) amount of materials from a single sheet via metalgen, breaking physics

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#50515]
![Image](https://cdn.discordapp.com/attachments/590051584495321100/700784009688383528/unknown.png)

![Image](https://cdn.discordapp.com/attachments/312999975674183683/700777354175316120/unknown.png)

Through some metalgen trickery (and a bug?) you can have a 50 sheet stack, that inserts 100 or 150 sheets into the Ore Silo.

## Reproduction:

1. Have two full stacks of metal (50 sheets iron, 50 sheets iron)
2. Turn one stack of metal into a material with metalgen (50 sheets iron, 50 sheets whatever)
3. Try to combine the two full stacks (click on the iron sheets with the metalgen sheets)
4. Your metalgen stack now inherits the iron material from the other stack while keeping its metalgen material
5. Inserting this into the Silo puts 50 iron sheets and 50 metalgen sheets into the silo, allowing you to repeat it indefinitely

**Comment by Kerbin-Fiber** [comment]
So you're saying that Stack #1 contains 50 Iron sheets and Stack #2 contains 50 Iron sheets and 50 Metalgen Sheets. So all you have to do is insert Stack #2 to duplicate materials.

**Comment by MrMelbert** [comment]
Yes - Though more accurately stack 2 contains 50 sheets total, with each sheet having double the value of a normal sheet

**Comment by nightred** [comment]
Metalgen was removed, and is now being re added with the expectation of creating mats with it.
