### ISSUE TITLE
Clicking "Issue Tracker" on the changelong opens Internet Explorer instead of your main browser

### ISSUE THREAD

**Issue by TheSmallBlue** [tgstation/tgstation#50517]
## Round ID:
N/A

## Testmerges:
#50484 

## Reproduction:

- Either join the server and wait until the changelong appears, or go to the OOC tab and click "Changelog"
- In the changelog, click the "Issue Tracker" hyperlink in the line that says "Have a bug to report? Visit our Issue Tracker." under the "Thanks to:" bit.
What should happen: github.com/tgstation/tgstation/issues should open on your main browser like all other hyperlinks.
What happens: The hyperlink opens the github.com/tgstation/tgstation/issues page on Internet Explorer.

![3I6xVl3Bu6](https://user-images.githubusercontent.com/24967815/79616200-d1d75f00-80da-11ea-9d39-229565373941.gif)
gif showing the bug

(I know its a way smaller issue compared to everything else you guys have to deal with at the moment, but I hate Internet Explorer with a burning passion for some reason)

**Comment by ShizCalev** [comment]
Pretty sure it's a byond issue.

**Comment by TheSmallBlue** [comment]
I didn't think it was because all other links sent anywhere else open in the users' main browser, this is the only one that doesn't as far as I know
