### ISSUE TITLE
Gases in new atmos canisters have no value when sold through Cargo

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#50527]
Not sure theres much to elaborate on. Sell gases through cargo, receive no money in exchange. Likely also means gas bounties are impossible to fulfill. 

Issue reported from  Round ID: [134996](https://scrubby.melonmesa.com/round/134996) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1511

**Comment by Tlaltecuhtli** [comment]
probably missing the export datum

**Comment by LemonInTheDark** [comment]
bettcha this has to do with typepath, this gonna be fun.

**Comment by Ghilker** [comment]
question, what kind of gas were you trying to sell?

**Comment by YPOQ** [comment]
Almost surely due to the following runtime from that round.
```
[2020-04-18 05:24:36.309] runtime error: cannot read from list
 - proc name: get cost (/datum/export/large/gas_canister/get_cost)
 -   source file: large_objects.dm,142
 -   usr: null
 -   src: /datum/export/large/gas_canist... (/datum/export/large/gas_canister)
 -   call stack:
 - /datum/export/large/gas_canist... (/datum/export/large/gas_canister): get cost(the miasma canister (/obj/machinery/portable_atmospherics/canister/tier_1), 1, 1)
 - /datum/export/large/gas_canist... (/datum/export/large/gas_canister): applies to(the miasma canister (/obj/machinery/portable_atmospherics/canister/tier_1), 1, 1)
 - export item and contents(the miasma canister (/obj/machinery/portable_atmospherics/canister/tier_1), 1, 1, 1, 0, /datum/export_report (/datum/export_report))
 - the supply shuttle (/obj/docking_port/mobile/supply): sell()
 - the supply shuttle (/obj/docking_port/mobile/supply): initiate docking(CentCom (/obj/docking_port/stationary), 1)
 - the supply shuttle (/obj/docking_port/mobile/supply): check()
 - Shuttle (/datum/controller/subsystem/shuttle): fire(0)
 - Shuttle (/datum/controller/subsystem/shuttle): ignite(0)
```

**Comment by Ghilker** [comment]
This is weird I can't replicate this on my local master, I can sell the canisters just fine

**Comment by LemonInTheDark** [comment]
What happens if you change the canister display type?

**Comment by LemonInTheDark** [comment]
to say Miasma

**Comment by Ghilker** [comment]
nothing, the gas is still sold normally. I still can't reproduce this issue

**Comment by TemporalOroboros** [comment]
This is still broken as of round 135568. I tried to sell a couple miasma/bz/plasma cans and got nothing for my trouble.

**Comment by timothymtorres** [comment]
There is also a runtime from this:

`Exception has occurred: Cannot create objects of type null.`

Located at: 

https://github.com/tgstation/tgstation/blob/5d6e93510fa04ad2948dc52a1ef3f4e1feafff84/code/modules/events/stray_cargo.dm#L39-L53

That calls the typepath like this:

`"/datum/supply_pack/materials/gas_canisters(Oxygen)"`

https://github.com/tgstation/tgstation/blob/54a9e47267043d086d0d31ef87abc1fbad364872/code/modules/cargo/packs.dm#L1111-L1147

It looks like the typepath isn't setup to handle the gas arguments properly or something...

**Comment by Sealed101** [comment]
can't reproduce
