### ISSUE TITLE
[GITHUB] Issue and PR searching/archiving seems broken

### ISSUE THREAD

**Issue by StonebayKyle** [tgstation/tgstation#50540]
Not sure if this is the right place to post this, but I may as well post it here.

## Issue:
Github PR/issue searching doesn't get all results.
This was likely caused by the ToS repo disable.

## Reproduction:

1. Go to github
2. Search for a PR or issue that you know exists
3. Notice that it has 0-very few results compared to what's expected.

Basic testing is inconsistent. Searching "can" brings up all the expected results posted or updated(commented on) between now and re-opening, but also an issue from 15 days ago (#50371). 

The "Similar issues" display (while I'm writing this issue) also may be affected as only recently posted/updated results are showing up.

**Comment by Kerbin-Fiber** [comment]
This is just how Github's search is shit, not a TG problem, report it to Github and not here.

Although this is just from my personal experience, so take it with a grain of salt.

**Comment by StonebayKyle** [comment]
I agree that it's a problem with github. However, IIRC, this wasn't an issue before the ToS shutdown, so the tg maintainers will likely have to deal with it themselves (possibly in conjunction with github? I have no idea)

**Comment by ShizCalev** [comment]
Github bug.
