### ISSUE TITLE
the special first aid kits that doctors start the round with are supposed to be able to hold bio bags, but can't anymore because bags are bulky now

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#50559]
this is so sad, gamers

**Comment by ATH1909** [comment]
![image](https://user-images.githubusercontent.com/42606352/79686495-5f639d80-8206-11ea-9883-a864f7438922.png)

**Comment by Mickyan** [comment]
not a bug

**Comment by ATH1909** [comment]
This also happens with medical belts and bio bags, sadly.

**Comment by kriskog** [comment]
The point of the satchel change was to make them unable to be carried around as easily. This is intended, but feel free to clean those references up.
