### ISSUE TITLE
MetaStation does not have a SciDrobe anywhere on the station at the start of the round.

### ISSUE THREAD

**Issue by Megarop** [tgstation/tgstation#50566]
## Reproduction:
Play on MetaStation.

**Comment by kriskog** [comment]
Used to be where genetics is now

**Comment by ivanmixo** [comment]
Guessing this got fixed at some point

**Comment by Maurukas** [comment]
This is fixed. There is SciDrobe in R&D next to the toolboxes.

**Comment by msgerbs** [comment]
@kriskog Can you close this?
