### ISSUE TITLE
Vending machines are a bit broken

### ISSUE THREAD

**Issue by CASHNOW** [tgstation/tgstation#50569]
## Reproduction: Create and interact with custom vending machine.

Custom vending machines have a few odd behaviours. They can not accept any of the common tools, screwdriver, wrench, multitool, welder ect. They also appear to not be able to be named. Third and most importantly not only can they not be stocked with a wrench, a wrench can't interact with it either. So an unwrenchable vending machine. A wall that can fall on you, truly terrifying.

**Comment by Tlaltecuhtli** [comment]
did you try pricetag the tools before inserting? being wrenchable has always been a thing not sure if something new  broke them  in the last week

**Comment by Vanadiom** [comment]
Pricetagging them doesn't change it, as they are following their "intended" behaviour.

**Comment by ArcaneMusic** [comment]
Checked today, and it looks like between the attack chain rework, the change to combat mode over intents, or the movement to have deconstruction over to right click in more cases, this is resolved.
![image](https://github.com/tgstation/tgstation/assets/41715314/08195a37-4ffe-42d3-81d4-8b8254ddca92)
![image](https://github.com/tgstation/tgstation/assets/41715314/575e7682-c3b3-488e-a302-1a72add3c277)
