### ISSUE TITLE
Honey Buns are uncraftable

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#50560]
Issue reported from  Round ID: [135083](https://scrubby.melonmesa.com/round/135083) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517

Testmerges: 

- #50510: 'Hydrogen Gas' by Ghilker at commit d80e0e519f
- #50484: 'Experimental tweak to demo recorder' by actioninja at commit dc509e175b

The damn things don't even show up in the crafting menu anymore. 

![image](https://user-images.githubusercontent.com/7019927/79687227-604afe00-820b-11ea-95fe-6db29b7286ff.png)

Should be where the red line is. I read the code for the crafting recipe and it looks fine to me.

**Comment by AnturK** [comment]
Messed up indentation cannoli
https://github.com/tgstation/tgstation/blob/master/code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm#L591

**Comment by TheVekter** [comment]
Well there's your problem.

**Comment by TheVekter** [comment]
I fixed this, Git's just being a whore about pushing it. I'll make the PR tonight when I wake up.
