### ISSUE TITLE
Wendigo butchering seems to be broken.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#50575]
Reproduction:
1. Kill wendigo.
2. Try butchering.
3. Progress bar shows up.
4. Get nothing.

Round ID: [135149](https://scrubby.melonmesa.com/round/135149)

Gibbing or calling the gib proc also seems to not work.

**Comment by optimumtact** [comment]
@Whoneedspacee

**Comment by optimumtact** [comment]
this is releated to a test merge #49680 and is not a bug with the servers

**Comment by Whoneedspacee** [comment]
fixed in recent update dont worry bout it
