### ISSUE TITLE
Cannot move before placing Blob core when chosen to be Blob from deadchat due to being locked onto shuttle

### ISSUE THREAD

**Issue by SkatesMcGates** [tgstation/tgstation#50574]
Issue reported from  Round ID: [135141](https://scrubby.melonmesa.com/round/135141) 
Reporting client version: 513.1508

Essentially, I was ghosted and due to a random event was selected to be a Blob. The problem is, before I spawned as Blob, I was looking at the Emergency shuttle which had docked onto the station. When I became the Blob, I could not move to look around the station to choose were to place my blob core.

**Comment by kriskog** [comment]
We should unlock the blob camera, so it can move across space before core is placed. A better solution to preventing space blobs is blacklisting areas for core placement.
