### ISSUE TITLE
mmi's can fuck over respawn antags

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#50570]
## Reproduction:

- be lich wizard/devil
- have special methods of being defeaten permanently with others supposed to fail
- lol nope time to put your brain in an mmi bye bye cuck

**Comment by ATH1909** [comment]
Can you stop this by using DNR?

**Comment by itseasytosee** [comment]
Should probably just give lich/devil vegital brain

**Comment by Vanadiom** [comment]
@ATH1909 You can, but then you do not revive... I mean, why should you be able to revive?
@itseasytosee That is broken too.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/6c01cc2c010c8dc15c5500434ae8e55261511781/code/modules/mob/living/brain/MMI.dm#L53-L103

Looks like a phylactery lich needs a SOULLESS trait added to it.  Then we need to check if the brain has that trait before insertion.

**Comment by Vanadiom** [comment]
Has this been fixed? It has been 2y after all.

**Comment by timothymtorres** [comment]
@Vanadiom would you be able to test my PR on a local server?  My laptop is broken and I'm using webedits from work to try and fix this.
