### ISSUE TITLE
Wall mounted picture frames always appear empty

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#50572]
If you insert a photo in a picture frame it will look empty, though you can still click on the frame to see the photo

**Comment by Fikou** [comment]
think this has been fixed?

**Comment by Mickyan** [comment]
Nope

![Screenshot_1](https://user-images.githubusercontent.com/38563876/83943583-92391380-a7fd-11ea-81b8-a99de4c9d5b1.png)

**Comment by Mickyan** [comment]
Reopen this @Fikou
