### ISSUE TITLE
You are unable to craft foodstuffs.

### ISSUE THREAD

**Issue by itseasytosee** [tgstation/tgstation#50582]
>try to craft something with menu
>button to craft does not appear
>???
>make shitty custom burgers,

**Comment by Vanadiom** [comment]
I tested it, and it only appeared with burgers for me, I didn't test food stuffs, without steak, could be steak related.

**Comment by Vanadiom** [comment]
Okay, I checked the Rice Pudding recipe, and it is broken as well, it only happened when i noticed that the UI for crafting updated and moved away from categories and sub categories. if anyone knows the merge that updated that, that may have broken it.

May be foodstuff related, as I could still craft a molotov.

**Comment by Vanadiom** [comment]
Copypasta is kill too, how can I a cook main, recover from this, AAAAAAAAAAAHHHHHHHHHH

**Comment by kriskog** [comment]
Closing in favor of #50590
