### ISSUE TITLE
nanite program hub machine broke

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#50588]
![image](https://user-images.githubusercontent.com/42606352/79822049-e70bf200-8355-11ea-947e-1d5667790c08.png)

**Comment by ATH1909** [comment]
![image](https://user-images.githubusercontent.com/42606352/79823454-7e267900-8359-11ea-8b6d-2661b52e171f.png)

Hm, this might need the [Needs Reproducing] tag.

**Comment by ATH1909** [comment]
> Inept the Map Gecko (EOBGames)Today at 10:40 PM
> god damn it windows vista
> Zack24Today at 10:40 PM
> i can't run a private server on ss13
> WilloxToday at 10:40 PM
> i had good times with vista
> Zack24Today at 10:40 PM
> crashes my computer
> no joke
> WilloxToday at 10:41 PM
> i recall my PC breaking and i was stuck with a vista laptop for a long time
> uomoToday at 10:41 PM
> Whenever menus mess up for me the first thing I try to fix anything is wiping IE's cache.
> stylemistakeToday at 10:41 PM
> when you erase program, it just overwrites program fields with empty strings
> uomoToday at 10:41 PM
> A lot of the time it helps.
> stylemistakeToday at 10:41 PM
> not a bug, but a cheap hack
> WilloxToday at 10:41 PM
> idk man it sounds like both
> Zack24Today at 10:41 PM
> i'll go check once the round starts
> also why does TGUI do a mini bluescreen
> WilloxToday at 10:42 PM
> this dude's on ie5 or something
> Zack24Today at 10:42 PM
> When i tried using a seed vendor it did a bluescreen
> stylemistakeToday at 10:44 PM
> what exactly did you do to the vendor
> Zack24Today at 10:44 PM
> i dunno
> i just pressed it
> I thought it was a feature
> is it not?
> stylemistakeToday at 10:45 PM
> it's both
> :smile:
> but yeah, bluescreen is not good
> WilloxToday at 10:46 PM
> it's a feature of errors
> technically
> stylemistakeToday at 10:46 PM
> i just pressed it
> pressed on the vendor to open it?
> WilloxToday at 10:46 PM
> he opened it and it broke because ie5
> stylemistakeToday at 10:46 PM
> or pressed a button?
> what version of IE is on your machine?
> Zack24Today at 10:47 PM
> uh
> How do i even check
> stylemistakeToday at 10:47 PM
> open IE
> go to menu -> about
> also
> WilloxToday at 10:48 PM
> it happened in a live round right? can't you grab the errors from that style?
> stylemistakeToday at 10:48 PM
> what server did you play on and when
> Zack24Today at 10:48 PM
> sybil
> and i don't remember the exact time
> WilloxToday at 10:49 PM
> was it recent?
> stylemistakeToday at 10:49 PM
> Sydney Mycelin (krypticdr3ams) using "main":
>  - rendering error TypeError: Unable to get property 'name' of undefined or null reference
> Zack24Today at 10:49 PM
> no
> stylemistakeToday at 10:49 PM
> Windows NT 6.2; WOW64; Trident/7.0
> WilloxToday at 10:49 PM
> we decided the useragents were bullshit didn't we
> stylemistakeToday at 10:49 PM
> we don't publish tgui logs
> also winnt 6.2 is probably windows 8
> and trident 7 is guaranteed ie 11
> WilloxToday at 10:50 PM
> oh right it's the other part of the user-agent that always says 7 for ie7
> msie 7.0

**Comment by stylemistake** [comment]
Ok, so he is using Windows Vista with IE10.

I should consider modifying the `IS_IE8` constant to include all versions up to IE10.
Or maybe I just need to polyfill the flexbox harder with `-ms-flexbox` CSS prefix. Not really sure.
