### ISSUE TITLE
Unable to craft with enough materials.

### ISSUE THREAD

**Issue by MiguelGuel** [tgstation/tgstation#50590]
Issue reported from  Round ID: [135221](https://scrubby.melonmesa.com/round/135221) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1513

As a shaft miner, killed an ash drake, butchered it but couldn't craft anything from the bones, sinew and hide it dropped. Tried separating ingredients in precise stacks for crafting but didn't work either.

**Comment by itseasytosee** [comment]
Related to #50582

**Comment by ArcaneMusic** [comment]
Appears to have been a legacy crafting bug, but checked against modern code, killing an ashdrake and butchering it is once again enabling crafting, even when stacks are moved and all adjacent. Comment in case this is still around.
![image](https://user-images.githubusercontent.com/41715314/99876017-00ae3a00-2bc2-11eb-9e0e-f05c2b0e64f0.png)
