### ISSUE TITLE
Virus isn't infecting

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#50607]
Issue reported from  Round ID: [135290](https://scrubby.melonmesa.com/round/135290) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1517

This is an iffy one. Sometimes it works and sometimes it doesn't. It feels like at least once every few rounds you get a virus that doesn't infect, and I'm unsure what causes it. In this case my virus doesn't infect after I drink. When testing try rebooting the server several times to see if you get the same results, as I said sometimes it works sometimes it doesn't.

![2020-04-21 18_53_19-Window](https://user-images.githubusercontent.com/36066032/79928959-9520a600-8401-11ea-8558-c9daadb00da3.png)
![2020-04-21 18_54_27-Window](https://user-images.githubusercontent.com/36066032/79928961-95b93c80-8401-11ea-9ce5-e775c36bab56.png)
![2020-04-21 18_54_07-Window](https://user-images.githubusercontent.com/36066032/79928965-98b42d00-8401-11ea-9dd9-71bcda05fc67.png)

I tried this with a slight variation to test to see if it infects but it does not. Not even some sniffles.

**Comment by XDTM** [comment]
i wonder if inorganic biology could be related to the issue

Were you human when you tested this?

**Comment by ATH1909** [comment]
This is a known Higgs-Bugson of virology, and it's incredibly annoying.

It has SOMETHING to do with necrotic metabolism and/or inorganic biology (all of the virus that I've seen that have run into this bug have had either necrotic metabolism, inorganic biology, or both). I also noticed during a fulpstation round that this seemingly-random immunity could be on a per-person basis, as a random human bartender and a human roboticist (neither of whom were bloodsuckers, who are immune to viruses on fulp) were both immune to my virus, even as everyone around them was being infected. I even had the bartender drink a sample of my virus directly, to no effect.

**Comment by ATH1909** [comment]
If ANYONE has ANY leads on what could be causing this bug, please let us know. We've tried to codedive to find the cause for quite a while, but can't for the life of us figure out WHY it happens. Our closest guess is that it might have something to do with the flags set by the necrotic metabolism and/or inorganic biology symptoms, and maybe something to do with the addition and removal of one of those two symptoms to a virus?

**Comment by ATH1909** [comment]
There have been other issue report threads about this bug, by the way, but because of the nuking of the repo, I can't use the search function to find them. Very sad; they had more cases that we could have analyzed.

**Comment by XDTM** [comment]
i think i might have something

The virus Copy() proc copies the symptoms directly, instead of using the AddSymptom proc that triggers the necrotic metabolism effect. Wouldn't explain why humans would be immune, but i could see that preventing necrotic metabolism taking place in certain circumstances

**Comment by ATH1909** [comment]
https://github.com/tgstation/tgstation/issues/50641

**Comment by TheSilverNuke** [comment]
Someone wanted me to specify how I create the virus on a regular basis. I'll go ahead and list my exact steps here.

I start with the Rhinovirus culture to get sneezing, afterwards I'll combine it and some virus food in a beaker to get fever. For this step and all following steps if I don't get the symptom I want I empty and eject the beaker.

Now that I have fever and sneezing I want to go for the next two symptoms. Both of these use weakened virus plasma so I do them together. I'll add wvp to a beaker combining the chem and the culture above until I get disfiguration and inorganic biology.

I have four traits now, so I'll now neuter disfiguration, sneezing, and fever by adding formaldehyde. When adding new symptoms past four it will sometimes delete a symptom so it doesn't always add up to five.

I'll then add mutagenic agar to the culture to get Virus Self-Adaptation. Sometimes it will delete one of the symptoms as I mentioned so if that happens combine the new culture with the old culture in a beaker until you have 5/6 symptoms.

Finally you get stable uranium gel and combine it in a beaker with the culture to get regenerative coma. Again combine the cultures if it deletes one of the symptoms. At this point the virus should look like the image above and be complete.

I test it by drinking the culture to see if I was infected. Wait a minute to let it tick and start the growth and then take a blood sample and put it into the PANDEMIC to see if you were infected. Most of the time it works, but there are many times when it doesn't.

**Comment by ATH1909** [comment]
"Most of the time it works, but there are many times when it doesn't."

Can you give an approximate ratio of "times it doesn't work":"times you tried to make this virus" for this?

**Comment by willox** [comment]
I followed the steps successfully 5 times (took me almost an hour) and wasn't able to reproduce it once.

**Comment by TheSilverNuke** [comment]
Yeah that sounds about right. If I had to say maybe 1 out of ten times it would break.

**Comment by emptyexpression** [comment]
Is this possibly related to the virus's Stealth value? The last time this bug happened to me, I remember being frustrated because I had a hard time figuring out whether the virus wasn't affecting me or if it was just the Stealth preventing me from scanning it properly. It was a virus with a stealth >= 2. I had to draw my blood in order to check for sure.

**Comment by TheSilverNuke** [comment]
Round 136914. Definitely an Inorganic Bio issue. Made a virus with

ARDS
Coughing
Sneezing
Fever
Inorganic Biology
Shivering (N)

Happened again.

**Comment by XDTM** [comment]
What i found out so far is that the OnAdd symptom proc is not called when copying viruses, which is kind of an issue, but is bypassed here due to the copy proc also copying the infectable_biotypes var.
Regardless of any addition or removal, though, i can't see anything that could cause the symptom to affect the MOB_ORGANIC flag as it seems to be happening here.

Until i'm able to properly test to check the actual flags ingame, my best guess so far is that the var copy process messes up somehow when dealing with bitflags, and manages to erase the default MOB_ORGANIC flag.
