### ISSUE TITLE
Policy.md example is not supporting the policy mechanic

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#50619]
The policy feature is meant to compound the relevant keywords, match keywords to policy.json, and print the relevant information. True support would mean that at anytime, a player can use the verb and have it print out the policy that's relevant to their character.

The to_chat example is actually a poor example because it only is done on login and cannot be re-read using the verb. This means that a user could accidentally go against policy because they missed the initial reading and did not see anything when wanting to check using the ingame tool (the verb).

A better example would be Ash Walkers using their antagonist datum to pull the "Ash Walkers" keyword, which then prints out any policy associated.

Therefore, the to_chat should be considered a nice QoL but not actual support of the mechanic.

Sorry I didn't catch this earlier (well I did read it but didn't realize it was an issue until I looked into it more).

**Comment by EgorDinamit** [comment]
Any ideas on how to improve it without giving everyone antag datum?

**Comment by optimumtact** [comment]
in the time spent typing this issue you could have just improved the wording

**Comment by ExcessiveUseOfCobblestone** [comment]
I tried and was having a brainfart
