### ISSUE TITLE
AI control beacon can be used to boot mech pilots

### ISSUE THREAD

**Issue by Tekkuni** [tgstation/tgstation#50639]
**Reproduction**:
1)  Build mech with AI control beacon
2) AI clicks on the mech, triggering the info about the mech's status and "take control?" button
3) Pilot goes in mech
4) AI presses take control
5) Free mech domination!

Seems very unintended, considering there's a malf module for doing this. Sounds to me like the mech's pilot status is sort of snapshot from the moment AI checks the mechs status instead of checking the pilot status at the moment of trying to drive the mech.

**Comment by itseasytosee** [comment]
The malf module lets you take control of mechs without a beacon.

**Comment by Tekkuni** [comment]
True, but if you click on a mech with an AI beacon and a pilot, you'll just get an error message there's already a pilot and you don't even get the status texts regarding the mech. This method circumvents that by getting the "take control?" button before the mech is unavailable. The amount of time spent between first clicking the mech and confirming the control seems to not matter, I stole a mech from a player who had been driving it for some good 5 minutes.

**Comment by itseasytosee** [comment]
Oh, I see the chat window. I did not properly understand.
