### ISSUE TITLE
Lings permanently die when beheaded.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#50633]
Basically, to replicate:

1.Find a ling.
2.Chop off it's head.

Congratulations, that ling is dead. From what I can tell, their previous body just doesn't count as a ling anymore, so likely they are being disconnected from their body when they shouldn't be when beheaded.

**Comment by Survivioboi** [comment]
The issue here?

**Comment by BeeSting12** [comment]
This just happened on Sybil. It appears the mind is disconnected from the body since the admin put me back in control of the body and I didn't have powers.

**Comment by itseasytosee** [comment]
Do lings not have veggie heads?

**Comment by Tharcoonvagh** [comment]
fuck tag pls
