### ISSUE TITLE
Pandemic virus culture functionally just Toxin

### ISSUE THREAD

**Issue by Shikarego** [tgstation/tgstation#50641]
Issue reported from  Round ID: [135428](https://scrubby.melonmesa.com/round/135428) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517

Some rounds, it seems that any culture the Pandemic prints is incapable of infecting humans or monkeys. I have tried pills, patches, dropper to the eye, syringe, drinking the culture, and spray. A health analyzer's chemical analysis shows x units of the chemical 'Toxin' in subject's bloodstream. I have tried reconstructing the pandemic, with no luck. I have not found any way to tell that this is going to happen in advance.

**Comment by Shikarego** [comment]
Just caught Silver reporting the same. This round my virus did have Inorganic Biology, but in the past I have had the problem persist with any virus I printed. This round I failed to test it without IB.

**Comment by TemporalOroboros** [comment]
Is this a blood type issue? Is the reason it's not infecting because the blood is converting into toxin the instant it enters the bloodstream because of conflicting blood types?

**Comment by ATH1909** [comment]
my god

finally another lead

**Comment by ATH1909** [comment]
https://github.com/tgstation/tgstation/issues/50607
