### ISSUE TITLE
Couldn't buy modules using new malf ai module menu

### ISSUE THREAD

**Issue by ReplicantTerry** [tgstation/tgstation#50659]
Issue reported from  Round ID: [135491](https://scrubby.melonmesa.com/round/135491) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507

I was playing as a malf AI and found that despite having enough points to buy a module, clicking on the button to buy it didn't give me the module.

**Comment by Tekkuni** [comment]
https://github.com/tgstation/tgstation/issues/50585
