### ISSUE TITLE
Rechargers turning invisible when opened

### ISSUE THREAD

**Issue by SppokiBoogi** [tgstation/tgstation#50666]
Issue reported from  Round ID: [135545](https://scrubby.melonmesa.com/round/135545) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1507

when screwdrivering open a recharger the frame becomes, invisible however the blinking light remains. You can right click to inspect it but are unable to interact with it in any other way that I could find.

**Comment by dragomagol** [comment]
Appears to have been fixed
