### ISSUE TITLE
Pandemic Culture Doesn't Infect Part 2

### ISSUE THREAD

**Issue by Shikarego** [tgstation/tgstation#50663]
Issue reported from  Round ID: [135531](https://scrubby.melonmesa.com/round/135531) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517

Okay this time I noted that I started by getting Inorganic Biology (IB) with rhino as base, then isolating IB. Then I built on that till I had my virus, all neutered and ready. 
Nothin.
Luckily I kept a culture where I lost IB, so I built on that one instead.
Drank it, no infection.

BUT.
I just put a drop of plasma into rhinovirus, giving it noct regen. I made a culture out of it from the Pandemic, drank it, Got Infected!!

So, viruses that came from the children of the isolated IB culture were unable to infect. But a new virus culture made from a new parent was perfectly fine.

**Comment by XDTM** [comment]
Were you a plasmaman while doing this?

**Comment by Shikarego** [comment]
> Were you a plasmaman while doing this? I'm trying to figure out if inorganic biology is simply not working as it should or actively preventing infection on normally infectable targets

No I was a human. The vast majority of my experiences with this bug have been as human.
