### ISSUE TITLE
Defib paddles do weird shit with telekinesis

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#50677]
Issue reported from  Round ID: [135566](https://scrubby.melonmesa.com/round/135566) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517

Putting a defibrillator in a wall socket, then removing the paddles using telekinesis causes some strange interactions. 

- Leaving the range of the defib doesn't cause them to snap back. 
- Wielding them then dropping the paddle causes the OFF-HAND item to get stuck in your hand. No way to remove it without admin intervention.
- Wielding them then clicking the defib again gives you a pair of paddles as well as leaving the OFF-HAND item in one hand.
- Most concerning, you can use the defib well out of the normal range allowed.

**Comment by SuperNovaa41** [comment]
None of these things happen anymore.
