### ISSUE TITLE
screwdriver in eye goes trough glasses and mask

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#50686]
135590
borg screwdrived my eyes while i was a hulk with mask and sunglasses

**Comment by itseasytosee** [comment]
#50556

**Comment by itseasytosee** [comment]
I can not reproduce this. I tried as a borg as well.

**Comment by Tlaltecuhtli** [comment]
[2020-04-25 18:29:22.272] ATTACK: Crimpf/(S.H.I.T.T.E.R.) has attacked Tlaltecuhtli/(Brick Carr) with automated screwdriver (INTENT: HELP) (DAMTYPE: BRUTE) (NEWHP: 75.5)  (Emergency Shuttle (204, 143, 2))

this line is where it happened, i had sec huds atmos gasmask and hulk and the screwdriver also gave me brain damage i think

**Comment by ATH1909** [comment]
Did it blur your eyes or anything?

The default attack message for screwdrivers is "stabbed"; maybe they just tried to hit you normally?

**Comment by Tlaltecuhtli** [comment]
they did blur

**Comment by ShizCalev** [comment]
Fixed via #58358
