### ISSUE TITLE
Sentient Diseases have an darkened screen.

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#50694]
## Round ID:
[135607](https://scrubby.melonmesa.com/round/135607)

## Testmerges:
#50608: '[Ready for Testing] Runechat: 'Runescape-like' Chat Message Overlays (It's back!) ' by bobbahbrown at commit 909e23d5b8

## Reproduction:
spawn in as sentient disease, all of your screen is darkened. @LemonInTheDark 
![image](https://user-images.githubusercontent.com/56656478/80292742-ba295780-8726-11ea-9762-555d0a08d4e1.png)
Probably because of hud layers being set to the wrong thing, as the same with #50444 .

**Comment by LemonInTheDark** [comment]
[Fix coming soon](https://www.youtube.com/watch?v=dv13gl0a-FA)
