### ISSUE TITLE
Watering hydroponics trays isn't blocked when the tray has full water level

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#50706]
### Reproduction:
Set beaker to 100u. Click a sink and click a tray. The tray accepts endless amounts of water, even if full. 

Makes it a bit harder to water multiple trays. 

Same thing with grafts really. Plants accept grafts even if they already have the grafted trait. 

I have another problem where several grafts stopped working after being put in a chemfridge for a while, but can't reproduce so no issue report yet.

**Comment by Tharcoonvagh** [comment]
Not a bug, iirc

**Comment by TemporalOroboros** [comment]
It will also eat all 500u from the botany mister when it has a capacity of 100u... Basically negating the entire purpose of the mister.

**Comment by ArcaneMusic** [comment]
Trays being able to accept water above their 100/100 cap is intended behavior, replacing the water in a tray is the best method of lowering tray toxicity.

Also intended behavior is plants being able to accept a graft while it has the grafted trait, grafts are able to share both specific traits via grafting, as well as shifting the graftee's stats by 2/3rds of the original plant's stats, specifically lifespan, endurance, production, yield, weed rate and weed chance.

So, all of this is not a bug.
That said, I would like to know about that chemfridge issue if you can reproduce it.

**Comment by Angustmeta** [comment]
Bug or not I think it's quite tedious.

Grafts stopping working happened again another time without fridge usage so don't know. Will let you know if I can reproduce.

**Comment by Angustmeta** [comment]
The mister issue is getting fixed so closing.
