### ISSUE TITLE
Bartender Vend-A-Tray broken

### ISSUE THREAD

**Issue by jwc1015** [tgstation/tgstation#50722]
Issue reported from (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1501

I swiped my ID as a bartender, and afterward swiping again (disarm) won't open it, it just says DENIED. Grab intent works fine.

**Comment by ArcaneMusic** [comment]
Should be fixed as of the above issue.
