### ISSUE TITLE
V-Sync / Screen Tearing / Stuttering

### ISSUE THREAD

**Issue by CrossbowDemon** [tgstation/tgstation#50724]
Is there any way to apply any form of V-Sync to reduce screen tearing and stuttering to SS13 / BYOND

Does anyone else experience screen tearing or stuttering?

Can Nvidia Control Panel to be used to force V-Sync in SS13 / BYOND?

What about limiting FPS with Riva Tuner Statistics Sever (RTSS) or other software?

Link to reddit post:
https://www.reddit.com/r/SS13/comments/g9d8n5/vsync_screen_tearing_stuttering/

Link to /tg/station forum post:
https://tgstation13.org/phpBB/viewtopic.php?f=2&t=26552&p=559592#p559592

**Comment by optimumtact** [comment]
there is not
