### ISSUE TITLE
glaring oversight with the airlock authentication override card PR

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#50731]
> desc = "A rengineered copy of Nanotrasen's standard jaws of life. Can be used to force open airlocks in **it's** crowbar configuration."

you used the wrong form of "its" smh my head my head

Also, based on a quick google search, I think you should have called it an "airlock **authorization** override card":
![image](https://user-images.githubusercontent.com/42606352/80465316-a2a5c680-8900-11ea-9bdd-763bd8854fc4.png)

**Comment by ATH1909** [comment]
@MrDoomBringer

**Comment by XDTM** [comment]
I'd say authentication makes more sense, since you're overriding the door's authentication protocol, not your own authorization method.

**Comment by MrDoomBringer** [comment]
^
ID cards = identification => authentication
also i still have no idea when to use its vs it's

**Comment by XDTM** [comment]
try looking at the sentence with the full 'it is' to see if it still makes sense

**Comment by zxaber** [comment]
> 
> also i still have no idea when to use its vs it's

When in doubt, think of Weird Al.
https://youtu.be/8Gv0H-vPoDc?t=81

**Comment by msgerbs** [comment]
Ugh this typo is in so many comments why did I start looking at this?
