### ISSUE TITLE
Bluespess Bodybag allows you to access containers while its folded up in your pocket.

### ISSUE THREAD

**Issue by SumFaggotPlayTester** [tgstation/tgstation#50737]
As the title says. Here are some steps, but I have yet to replicate it. Waiting to see if Vek finishes up replicating it atm.
I. Bluespess bodybag deployed
II. Container placed in it. Such as a backpack with a box in it.
III. Open that container's inventory & keep it open.
IV. Fold the bluespess bodybag up & place it in your pocket slot.
V. You can take items from the container screen still & deposit them as well.

Me & Vek both agreed this is not intended so this is its bug report.

Issue reported from  Round ID: [135824](https://scrubby.melonmesa.com/round/135824) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517

**Comment by TheVekter** [comment]
Able to reproduce on live.

**Comment by nemvar** [comment]
You can also put the bodybag into the open inventory which makes it disappear.
