### ISSUE TITLE
You can use an AI core like a ghetto jetpack

### ISSUE THREAD

**Issue by TheWiznard** [tgstation/tgstation#50732]
## Reproduction:
Step 1: be cyborg
Step 2: ai unbolts itself
Step 3: drag ai to space:
Step 4: put yourself behind the ai core and walk downwards with s or whatever direction, should look like this: s=space b=borg a=ai core
sbs
sas
sss

By doing this you move way faster and basically ignore space, almost like sort of having a jetpack not as fast, it's like not taking a step you just keep moving in the direction. This could probably work as a person but I don't exactly remember how pushing the ai core as a person works, I only know it works as cyborg. I was engiborg for reference.

**Comment by Tharcoonvagh** [comment]
Same with girders and other unanchored machinery

**Comment by Dennok** [comment]
omg, finally someone find this bug, in some strange way, and it don't understand in what core of bug.

**Comment by XDTM** [comment]
#39556 made it so when pushing something you automatically move to follow it (to avoid doing push->catch up->push->catch up). Apparently that in combination with no-grav movement ignoring delays (maybe only for borgs?) potentially lets you do this with probably any dense mob.

It would be interesting to test if you can zoom into space by pushing someone on a wheelchair, or a hulk.

**Comment by Dennok** [comment]
Oh ok. i say it. You can use any thing that you can use to pust from in zero grav(crate, box, canister, closet... etc) to fly at meth speed in space.

**Comment by TheBonded** [comment]
you can do this as a human with a pAI (as long as you are on harm intent) or any other pushable thing that you can push off of in no gravity

**Comment by projectkepler-ru** [comment]
This should be closed
