### ISSUE TITLE
you can make 2 modkits 3 if you click fast

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#50742]
Issue reported from  Round ID: [135851](https://scrubby.melonmesa.com/round/135851) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517

1. have a PKA
2. print 2 modkits
3. click quickly
4. you somehow put in 3

**Comment by Fikou** [comment]
that's a thing that happens with alt clicking and lag with stuff like borgs and mechs too, you put the part in something but then take it in your hand after you put it in

**Comment by Tlaltecuhtli** [comment]
its about clicking quickly and procs being slow, other example of similar behaviour is: 
machinery construction sometimes will have dupe parts be inserted "twice" needing less parts

**Comment by optimumtact** [comment]
the code is likely not using sleeps/doafter properly

**Comment by Kaffe-work** [comment]
shouldn't this use locks/guards rather than sleep in general for race conditions?

**Comment by Sealed101** [comment]
fixed by #83222
