### ISSUE TITLE
Horrible non existent framerate after mining

### ISSUE THREAD

**Issue by Vanadiom** [tgstation/tgstation#50747]
## Round ID:
[135863](https://scrubby.melonmesa.com/round/135863)

## Testmerges:
None?

## Reproduction:
So, it happened when I mined for a good 20 minutes with a PKA, having 3 cooldown reduction Upgrades on it, I became mining rank legendary, and on the way to it my framerate got worse and worse, I reconnected, restarted the client, even restarted the PC, but still, framerate stayed shitty.
I have no real knowledge of why this could have happened, but it is horrible.

**Comment by TemporalOroboros** [comment]
I've noticed this as well. It got bad pretty fast when I strip mined with two cooldown and a mining AOE. It might scale with the number of tiles mined?

**Comment by ATH1909** [comment]
this could have something to do with https://github.com/tgstation/tgstation/pull/50535 ?

**Comment by ATH1909** [comment]
wasn't there also a mining framerate bug that was related to hanging around megafauna?

**Comment by LemonInTheDark** [comment]
> 
> 
> this could have something to do with #50535 ?

That's highly unlikely. Whatever is causing this is most likely client side

**Comment by Vanadiom** [comment]
I noticed that it didn't feel like the framerate was that bad, when I didn't move for a while, other people started moving, more like they should.
Also, towards the end of the round, when I died, as a ghost my framerate was more... agreeable

**Comment by kriskog** [comment]
Likely having internals on and the status tab active. Try disabling internals or changing tabs and seeing if it helps.

Hard to say what causes it, as it's hard to reproduce locally.

**Comment by Vanadiom** [comment]
> wasn't there also a mining framerate bug that was related to hanging around megafauna?

Maybe there was, but that wasn't the case here ATH, because I am an unbased pleb, that cant survive near them.

**Comment by optimumtact** [comment]
is anything applying stacking overlays? in the skills or mining code?

**Comment by DAKKA-WAAAGH** [comment]
Same thing has been happening to me quite often too. I go out to skill up PKA proficiency, bag a lot of minerals, and find ruins. As the round progresses and I continue mining, my ping increases dramatically from around 40 to 130.

**Comment by optimumtact** [comment]
Only during mining?

What the hell

**Comment by optimumtact** [comment]
are you using mining scanners when this happens?

**Comment by Qustinnus** [comment]
@DAKKA-WAAAGH 

1. Are you using the mineral scanner?
2. At what level of mining does the lag start?
3. Is there a lot of mineral scanner visuals on screen when you lag?

**Comment by PKPenguin321** [comment]
another theory, completely off the top of my head: when you mine you create a large number of ore objects, maybe somehow those aren't getting moved cleanly to the ore satchel or whatever so they stack up on your client or something?

**Comment by necromanceranne** [comment]
Okay, seems like whatever it is, is attached to the PKA after a while. When I had my skill dropped to zero, the PKA being on screen caused the frames to drop. Whatever it is, it's related to something happening to the PKA.

**Comment by LemonInTheDark** [comment]
oh christ

**Comment by necromanceranne** [comment]
And specifically THAT PKA. Maybe it's whatever the skill is doing when interacting with the PKA. Could be related to the guns recharge overlays?

**Comment by DAKKA-WAAAGH** [comment]
So I know that the lag ramps up as the proficiency increases. I paid attention to my latency in a round while I mined with the KA, and each proficiency gain increases my latency by at least 10-15ms. Once capped, I'm standing around at 100-120ms latency and the occasional 1000+ms spike happens every minute or so. Ash storms and advanced mining scanners seem to accentuate this issue a little bit. I hope some of these details help out, I'm not a coderguy so this is the best I've got so far.

**Comment by optimumtact** [comment]
Something is stacking overlays on the KA
![image](https://user-images.githubusercontent.com/2544323/81037553-3e35c900-8ef7-11ea-9937-3191b95258fb.png)

**Comment by optimumtact** [comment]
okay the winning combination here is using a gunlight and then having your overlays update.

This causes the overlays to build upl.

Toggling the gunlight of resets the overlay states

**Comment by optimumtact** [comment]
note that it builds up if it's on or not.

**Comment by Qustinnus** [comment]
I experimented with this further, this isn't exclusive to the PKA and is directly related to gunlights, as they're flooding the overlays with null entries for some reason. My first guess would be that because the gunlight isn't making use of update_overlays its fucking up the system. Ninjanomnom would probably know how to fix this but I'll take a look at it myself too

**Comment by Qustinnus** [comment]
I found out whats causing it, the add_overlay argument "priority" is somehow doing it, setting those to default value (FALSE) fixes the issue. I'm not entirely sure how overlays work but this seems to be a bigger issue with how priority_overlays works. I'm going to run  some tests on other objects that have priority overlays and will then open a placeholder fix for the mining issue.

**Comment by optimumtact** [comment]
Just reposting here for clarity:
I firmly believe we should remove priority overlays.

Objects can now listen for signals from other objects, and hook their overlay updates proc.

The correct way to apply an overlay to another object and have it persist through the cut/build cycle is to listen for that signal instead.
