### ISSUE TITLE
Penetrator Rounds do not harm anyone except what you click directly

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#50762]
To reproduce:

1. Get your standard sniper rifle.
2. Line up some felinids.
3. Put penetrator rounds into your sniper rifle.
4. Shoot past the felinid pack.

The expected behaviour here is that every cat in line of the shot should be hit with the bullet.

What happens instead is that nobody is hit whatsoever unless you directly click one of them. This renders penetrators pretty weaker overall since they have a tendency to miss if you have to click directly onto the target.

**Comment by ATH1909** [comment]
Does this affect the syndicate mothership's turrets at all?

**Comment by necromanceranne** [comment]
Fairly sure those will hit their main target given testing. Anything else is debatable so this seems like an effective penetrator nerf while broke.

**Comment by ShibaInuLord** [comment]
This also affects every other projectile that can penetrate, such as Staff of the Honkmother shots.

**Comment by ArcaneDefence** [comment]
Fixed by kevinz
