### ISSUE TITLE
Action buttons misplaced when using non widescreen mode.

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#50760]
## Round ID:
[135915](https://scrubby.melonmesa.com/round/135915)

## Reproduction:
Spawn in as anything when not using widescreen mode, the create new button area, skills, and languages buttons are misplaced.

![image](https://user-images.githubusercontent.com/56656478/80633641-16da8a00-8a27-11ea-9a38-51bdca2cad19.png)

**Comment by LemonInTheDark** [comment]
can't seem to reproduce on a local

**Comment by ShibaInuLord** [comment]
hmmm, yeah it doesnt happen on my local as well, but it happens on the main servers still.

**Comment by LemonInTheDark** [comment]
fucking ahhhhhhhhhhhhhhhhhhhhhhhhhh
