### ISSUE TITLE
You are able to see people's players models and runescape text through walls when wearing meson goggles

### ISSUE THREAD

**Issue by ominousgrace** [tgstation/tgstation#50773]

**Comment by ATH1909** [comment]
oh god oh fuck

**Comment by MacBlaze1** [comment]
Deserving of a "FUCK" label?

**Comment by necromanceranne** [comment]
Engineering thermal goggles

**Comment by mikaihl95** [comment]
Good and great

**Comment by ivanmixo** [comment]
Can't reproduce this

**Comment by TheBonded** [comment]
Is this still an issue? I feel like this issue should be removed, it's almost been a year. ever wonder why we have 1.8k issues?

**Comment by SuperNovaa41** [comment]
Yeah no i can't reproduce this either
