### ISSUE TITLE
Mi-gos, surgery tables and transending physicality. 

### ISSUE THREAD

**Issue by DerpyMongoose** [tgstation/tgstation#50776]
Issue reported from  Round ID: [6953](https://scrubby.melonmesa.com/round/6953) (Fulpstation)

Reporting client version: 513.1517

Ghost roled sentient mi-go in medbay, when dragged to a surgery table by a mothman I lost the ability to walk and the ability to block people effectively letting people stand inside my sprite. I suppose this might apply to all sentient simple mobs when dragged?

**Comment by Archanial** [comment]
It's because simplemob is being set to resting and not being able to get up on their own.

**Comment by ATH1909** [comment]
> It's because simplemob is being set to resting and not being able to get up on their own.

You should still be able to get up on your own, just push the "rest" button in the IC tab (it should still be in your IC menu, even though it isn't on your HUD as a simplemob).

**Comment by XDTM** [comment]
i really thought rest was carbon-level

**Comment by PKPenguin321** [comment]
My gut instinct says non-carbons shouldn't be able to rest at all, ever

**Comment by Archanial** [comment]
> 
> 
> My gut instinct says non-carbons shouldn't be able to rest at all, ever

Cats can sit???

**Comment by gonenoculer5** [comment]
so can PAI's

**Comment by Sealed101** [comment]
mi-gos got basic mob'd and surgical tables have had a refactor - something or other fixed this
