### ISSUE TITLE
Frost Oil Does Not Metabolize

### ISSUE THREAD

**Issue by halitosisman** [tgstation/tgstation#50779]
Issue reported from  Round ID: [136006](https://scrubby.melonmesa.com/round/136006) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

I don't have hard numbers on this. I got injected with frost oil during a cryogenic blob round. The stuff never left my system in the time where it reasonably should have. My character also eventually went fat without ever eating any food in the course of the round.

**Comment by ATH1909** [comment]
What race were you?

**Comment by halitosisman** [comment]
human.

**Comment by interestingusernam3** [comment]
Hmmm yes today I, a tiny part of a dead star, will finish my 252936252 ly journey throughout the cosmos by making someone's videogame character fat.
