### ISSUE TITLE
attempting to spray a gang sign but failing because there's already another gang sign in the area still consumes a spray can charge

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#50799]
This becomes really annoying partway into a gangs round, where you're trying to spray random walls and such to see what turf hasn't already been claimed, then realize that your spray can has run out of juice before you've even managed to spray anything with it.

**Comment by Iamgoofball** [comment]
will look into it

**Comment by ATH1909** [comment]
thanks
