### ISSUE TITLE
Can't adjust suit sensors

### ISSUE THREAD

**Issue by AU518987077** [tgstation/tgstation#50791]
Issue reported from  Round ID: [136037](https://scrubby.melonmesa.com/round/136037) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1521

I right click suit, go to adjsut suit sensors, and no UI opens. worked before updating to latest beta today.

**Comment by ATH1909** [comment]
Was your jumpsuit damaged?

**Comment by AU518987077** [comment]
Nope, fresh suit start of round for multiple rounds

**Comment by nemvar** [comment]
What role were you playing?

**Comment by AU518987077** [comment]
> What role were you playing?

Paramedic but also happened with scientist

**Comment by ATH1909** [comment]
![image](https://user-images.githubusercontent.com/42606352/80891862-6a014680-8c8c-11ea-88fe-6a30fa8c3221.png)

A fulpstationer has also been encountering this bug.

**Comment by PKPenguin321** [comment]
Also happened to me yesterday, couldn't remove my pen from my PDA with right click or the Objects tab either (alt clicking it worked)

**Comment by PKPenguin321** [comment]
This has since stopped affecting me, not sure what caused or fixed it.

**Comment by SteelSlayer** [comment]
I've heard that byond .1521 causes right click menu verbs to simply do nothing when clicked, or just generally bug out. That may be the case here.

**Comment by AU518987077** [comment]
its not happening any more, i can use the context menus for suit sensors and other items

**Comment by MTandi** [comment]
I guess it was an issue related to context menus rather than suit sensors. We probably need a way to toggle suit sensors without relying on right click.

**Comment by TheBonded** [comment]
If this is still an issue, please mention me here and I will reopen the report. as of now, it seems to no longer occur
