### ISSUE TITLE
Using the "swap equipped item" button, it's possible to retain HUDs from eyewear that you've removed

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#50798]
<img width="1370" alt="doublehud" src="https://user-images.githubusercontent.com/42606352/80829326-86c64d00-8bac-11ea-95dc-035936dfe10e.PNG">

**Comment by ATH1909** [comment]
Reproduction steps:
1. Wear a medHUD in your glasses slot.
2. Hold a pair of secHUDglasses in your hand.
3. Press whatever key you've bound to the "swap equipped item" function.
4. After the swap, notice that you now have both medHUD-vision AND secHUD-vision.

I've reproduced this consistently in later rounds.

**Comment by ATH1909** [comment]
Someone DEFINITELY should test what happens if you try this with memento mori and, say, a bedsheet.

**Comment by SkeletalElite** [comment]
> Someone DEFINITELY should test what happens if you try this with memento mori and, say, a bedsheet.

Wonder if it works with night vision/thermal vision

**Comment by bluetshirtguy** [comment]
> Someone DEFINITELY should test what happens if you try this with memento mori and, say, a bedsheet.

It lets you keep the memento mori in hand  but if you drop it or move it to your backpack you still die.

**Comment by ATH1909** [comment]
> > Someone DEFINITELY should test what happens if you try this with memento mori and, say, a bedsheet.
> 
> It lets you keep the memento mori in hand but if you drop it or move it to your backpack you still die.

That might be good enough if you get a nodrop implant and that surgery that makes your limbs undismemberable...

**Comment by XDTM** [comment]
Fire is still gonna burn the limb off eventually

**Comment by Akrilla** [comment]
now this is a gamer moment
