### ISSUE TITLE
Duplicate unknowns in crew tracker

### ISSUE THREAD

**Issue by AU518987077** [tgstation/tgstation#50792]
Issue reported from  Round ID: [136037](https://scrubby.melonmesa.com/round/136037) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1521

Crew tracker has multiple identical unknowns with identical vitals and locations. these do not appear to other crew using the same crew tracker i am using
![Screenshot 2020-05-01 01 44 26](https://user-images.githubusercontent.com/24924661/80791200-1557b180-8b4e-11ea-949d-f1555b03d4d6.png)

**Comment by AU518987077** [comment]
as the round progresses more duplicates are showing up
![Screenshot 2020-05-01 02 20 50](https://user-images.githubusercontent.com/24924661/80792794-a0d34180-8b52-11ea-9bf8-14235cb1cd83.png)

**Comment by ATH1909** [comment]
Maybe this is related to https://github.com/tgstation/tgstation/issues/50798 ?

**Comment by AU518987077** [comment]
> Maybe this is related to #50798 ?

Does not look like that at all

**Comment by AU518987077** [comment]
Issue reported from  Round ID: 136095 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1521

new day, cleared my cache, its still happening

![Screenshot 2020-05-01 21 03 59](https://user-images.githubusercontent.com/24924661/80853654-a337a900-8bef-11ea-810c-6e09ce58a780.png)

**Comment by AU518987077** [comment]
having someoen else use it turned it form this mess back to a more normal display of just the crew, this got rid of all the unknowns but they got added quickly

![Screenshot 2020-05-01 22 08 16](https://user-images.githubusercontent.com/24924661/80855120-7f7a6000-8bfb-11ea-93e8-5ceb6df0d8f9.png)

**Comment by AU518987077** [comment]
![Screenshot 2020-05-01 22 34 25](https://user-images.githubusercontent.com/24924661/80855268-0e3bac80-8bfd-11ea-828e-9d5874a630cf.png)

**Comment by XDTM** [comment]
Potentially a nanite bug if it's somehow adding the same person to the tracking list multiple times without removing them

**Comment by WarlockD** [comment]
I think you are right, It was clear and blue on the last game I played till we added nanites.  I always throw monitoring in there and had a few unknowns show up.

**Comment by Ordonis** [comment]
Just reproduced this on a naniteless round, no. 136527

**Comment by AU518987077** [comment]
still happening
Issue reported from  Round ID: 136527 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1522

**Comment by AU518987077** [comment]
still happening and i just confimred another thing i was suspecting, that the crew monitor was also lying about thsoe that it was tracking round 136753

**Comment by NoooneyDude** [comment]
Can confirm @AU518987077's claim. Paramdedic found dead in surgery - his overlay was displaying the recently-dead lifesigns icon. I couldn't snag a screenshot of it before the round ended, unfortunately.

https://i.imgur.com/fyiwMn0.png

**Comment by WarlockD** [comment]
````
pos = H.z == 0 || (nanite_sensors || U.sensor_mode == SENSOR_COORDS) ? get_turf(H) : null
// Special case: If the mob is inside an object confirm the z-level on turf level.
if (H.z == 0 && (!pos || pos.z != z))
    continue
````
So what is "supposed" to happen is an unknown is someone who isn't wearing an id, that has either nanite sensors or suit sensors.  Simple enough.  But if someone is in a locker, box or some other container, their z level becomes 0.  So, that's fine, lets get the tile position then.  But what happens if your in 0 AND have nanites or somehow still wearing a uniform.?  You show up.  How does this happen?

Er not sure there is a bunch more code to check on that.  If your gibbed are you in 0?  I think the code needs to be refactored to be a bit more clear.  Atleast to log the error.  I would say it should be some kind of radio signal sent from the uniforms themselves.

**Comment by MacBlaze1** [comment]
https://github.com/tgstation/tgstation/blob/add74bee56cfde91602eb8ee28e3cae5959bc4f6/code/game/machinery/computer/crew.dm
broken file, proc update_data(z), line 142 is where the shit starts

**Comment by AU518987077** [comment]
request reopen, its still happening
Issue reported from  Round ID: 138172 (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1525
there were nanites thsi round
![Screenshot 2020-05-27 21 26 30](https://user-images.githubusercontent.com/24924661/83096362-b01ab180-a062-11ea-9db1-86b76a36179a.png)

**Comment by AU518987077** [comment]
Issue reported from Round ID: 138183 (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1525

there were no nanites and my crew tracker went blank after a few minutes
![Screenshot 2020-05-28 00 38 05](https://user-images.githubusercontent.com/24924661/83113554-0ef12280-a085-11ea-895d-0576c69fe941.png)

**Comment by AU518987077** [comment]
issue still persists no change, still get duplicates as early as the first minute and about 4 minutes in it goes blank

**Comment by AU518987077** [comment]
Issue reported from Round ID: 139103 (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1525

30 second webm video of the change of trackable crew including unknowns, and then to empty crew tracker at 5 minutes in

[dreamseeker.exe 2020.06.08 - 23.15.04.02a.zip](https://github.com/tgstation/tgstation/files/4750416/dreamseeker.exe.2020.06.08.-.23.15.04.02a.zip)

**Comment by AU518987077** [comment]
Issue reported from Round ID: 139103 (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1525

30 second webm video of the change of trackable crew including unknowns, and then to empty crew tracker at 5 minutes in

[dreamseeker.exe 2020.06.08 - 23.15.04.02a.zip](https://github.com/tgstation/tgstation/files/4762912/dreamseeker.exe.2020.06.08.-.23.15.04.02a.zip)
post remade because i uploaded a zip that had a randomly generated password

**Comment by AU518987077** [comment]
still seeing unknowns, the blanking seems to have stopped

**Comment by AU518987077** [comment]
I have upgraded my side monitor and its bearly enough to see this mess

![Screenshot 2020-07-16 21 40 54](https://user-images.githubusercontent.com/24924661/87746632-455a3c80-c7ae-11ea-8391-6d6e4446c3d6.png)

**Comment by MTandi** [comment]
This looks to be resolved.

**Comment by Mothblocks** [comment]
i havent seen this in a long itme
