### ISSUE TITLE
MMI had brain in it, but sprite was not updated to appear as such and you could not take it out.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#50804]
136081

Near the end of the round (which crashed by the way). There was a brain in an MMI (it was talking/confirmed with VV) but the sprite had the empty MMI sprite and using inhand just changed radio settings for the MMI. We assembled a borg and it could be put inside the borg. Unfortunately no further testing could take place because the round crashed. No reproduction steps as I never got the chance to ask how it happened.

**Comment by Dorsisdwarf** [comment]
Closed since #50908 is believed to be the same bug but described in excruciating detail
