### ISSUE TITLE
Exiting turfs is handled in /turf/Enter()

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/tgstation#5080]
There's a /turf/Exit() proc, Why don't we use it?

**Comment by tkdrg** [comment]
The byond beta has added a new argument for Exit()/Exited()
> The Exit() and Exited() procs now take a second argument that includes the new location. (This is redundant for Exited(), but is done for consistency.)

http://www.byond.com/docs/notes/507.html

**Comment by Jalleo** [comment]
VG has now rewritten their movement code to use cross and exit i will ask them how well it has worked sometime this week.

**Comment by Jalleo** [comment]
Update it appears to not be usable still in certain edgecase aspects as per http://www.byond.com/forum/?post=2079322 so might not be usable still for now. https://github.com/d3athrow/vgstation13/pull/8667 pull request for reference sakes.
