### ISSUE TITLE
Hardsuit power drains for no reason

### ISSUE THREAD

**Issue by Nikitaw99** [tgstation/tgstation#50820]
Issue reported from  Round ID: [136121](https://scrubby.melonmesa.com/round/136121) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

I got the champion's hardsuit from a lavaland tendril, though I never turned on the thermal regulation, and yet the power is just draining anyway for no reason. I don't think this should be happening
![image](https://user-images.githubusercontent.com/16986290/80865162-7b505000-8c98-11ea-9ffc-94d05969000e.png)

**Comment by Timberpoes** [comment]
That was my bad, totally owning up to it.

Thanks to your report I have a fix pushed now. Hopefully it gets merged soon!
