### ISSUE TITLE
Runechat messages not getting deleted and stacking

### ISSUE THREAD

**Issue by Archanial** [tgstation/tgstation#50828]
Issue reported from  Round ID: [136148](https://scrubby.melonmesa.com/round/136148) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1513

It also affects pointing arrows.
![obraz](https://user-images.githubusercontent.com/37456678/80892531-3396ec00-8ccb-11ea-9045-1d2351c84ac9.png)

Edit: it happens to all effects such as: 
![obraz](https://user-images.githubusercontent.com/37456678/80892719-90df6d00-8ccc-11ea-974e-3d977df4b8c5.png)

**Comment by bobbahbrown** [comment]
Timer subsystem failed, not related to runechat explicitly.

**Comment by actioninja** [comment]
Timer as failed in round, all kinds of unpredictable bugs when this occurs.
