### ISSUE TITLE
Protolathe broke

### ISSUE THREAD

**Issue by Archanial** [tgstation/tgstation#50829]
Issue reported from  Round ID: [136148](https://scrubby.melonmesa.com/round/136148) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1513
![obraz](https://user-images.githubusercontent.com/37456678/80892633-dc454b80-8ccb-11ea-9808-e9ad2f70e066.png)
Not sure if it has something to do with runechat messages getting bugged but it doesn't produce anything and then says "it's busy".

**Comment by bobbahbrown** [comment]
Timer subsystem failed, possibly related but not a bug as if the timer subsystem is burdened they won't be deleted.

**Comment by actioninja** [comment]
Timer SS failing can result in all kinds of strange unpredictable bugs.
