### ISSUE TITLE
Alt Click displays changing icon states in a really odd way

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#50838]
The alt click panel doesn't show changed icon states well, it does some really odd shit, seems like layering. I've had the same thing happen if I remove all the "Us" code around the behavior, so I suspect it's a byond issue with passing objects to statpanels

![image](https://user-images.githubusercontent.com/58055496/80907147-2547d080-8cc9-11ea-894f-b54386cdfc72.png)

The related code is in code/modules/mob/mob.dm on line 761

**Comment by actioninja** [comment]
Byond bug, nonrendering slates for some reason get rendered in the list.

**Comment by Couls** [comment]
No longer an issue now that we use a browser panel
