### ISSUE TITLE
Cameras don't work at all

### ISSUE THREAD

**Issue by Archanial** [tgstation/tgstation#50848]
Issue reported from  Round ID: [136209](https://scrubby.melonmesa.com/round/136209) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1513

All photos look dark on sprite and when you inspect them they just don't load.

Steps to reproduce:
1. Make photo of someone.
2. Done.

**Comment by SuperNovaa41** [comment]
not an issue
