### ISSUE TITLE
You can drag mobs attached to mulebots, letting you drag mulebots

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#50841]
Step one: Removing the loading safeties on mulebot
Step two: Attach mob to mulebot
Step three: Drag mob, dragging mulebot with it.
Step four: murder everyone with this one weird trick

Under normal circumstances you can't drag mulebots. So this is uh, pretty strong. Unsurprisingly.

Shout out to Tlal for pretending like he didn't do this when we were talking about how funny it was when he did this.

**Comment by ATH1909** [comment]
from what I heard in OOC chat, this does not only the "running over prone people" thing, but also the "hardstuns anyone the mulebot bumps into" thing
