### ISSUE TITLE
[missing sprites] plant growth stages

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#50866]
the code has 5 growth stages but people lazily made less than 5 sprites, which was fine until big ERROR appeared

**Comment by Angustmeta** [comment]
![200504 1449 21](https://user-images.githubusercontent.com/46400996/80967331-774a3c80-8e16-11ea-81de-f63ddff16ed3.png)

**Comment by Dorsisdwarf** [comment]
Cheers.
