### ISSUE TITLE
Supermatter causes things to explode... but not before nullspacing them.

### ISSUE THREAD

**Issue by haukeschuemann** [tgstation/tgstation#50861]
## Reproduction:

Shove anything explodey (for example grenades) into the supermatter. They will not explode anymore.
This used to be the case. Also causes canisters to runtime upon getting eaten but that's another piece of shitcode.

```
/obj/singularity_act()
    SSexplosions.highobj += src
    if(src && !QDELETED(src))
        qdel(src)
    return 2
```

Due to the way this queues things, the obj will first be moved to nullspace > then have ex_act called > then be deleted.

**Comment by XDTM** [comment]
kinda makes sense though

**Comment by nemvar** [comment]
I does not make sense for explosions to happen in nullspace.

**Comment by XDTM** [comment]
i just mean flavor-wise, it's still bad that it works like it does now

**Comment by ShizCalev** [comment]
Explosions kill singularities iirc, so it's kinda required.

**Comment by Sealed101** [comment]
could not reproduce; no explosions seem to go through on an item deleted by a supermatter (or a singularity, as the issue has the singulo proc)
also see #52894
