### ISSUE TITLE
Families -general confusion mode

### ISSUE THREAD

**Issue by Ikoden** [tgstation/tgstation#50873]
So I dont know if its being developed, but I would suggest:
1) give some kind of uplink to families, so they can get weapons like in gangs,
2) give some purpose for the families, i just didnt know what to do as a member,
3) involve somehow security in the game, maybe remove the police or somehow make it work with security.
In the state as it is, families is just a FULL CONFUSION FOR EVERYNOE MODE. Noone knows what to do.,
Just my 2 cents. If it isnt developed then nevermind.

**Comment by PKPenguin321** [comment]
Suggestions like this that aren't actual bugs go on our forums, not the issue tracker

**Comment by Ikoden** [comment]
Ok, my bad then.

**Comment by Iamgoofball** [comment]
regarding 2, have you tried reading the text that pops up when you join a family?

**Comment by Dorsisdwarf** [comment]
Feature requests are for the forums.

**Comment by Ikoden** [comment]
Regarding 2, I dont remember to be honest goof.  I played it once and I play like 10 hours per day so I dont remember it. All I remember that it wasnt clear enough for me.

**Comment by Ikoden** [comment]
Also, it seems I dont have permission to post on coding feedback forum..
And also as to 2 and goof, it was more clear when you were gangster:
1. you spray shit and destroy others sprayed shit
2. gangs gets more points 
3. kill other gangies and sec
4. you place dominator at the end
Everyone knew what they were doing. In case of families it's either 1) people are new to families and dont know what they have to do ant thus confused 2) the objective is not clear enough.

**Comment by davethwave** [comment]
Actually your not supposed to really kill sec unless they start things I believe.
