### ISSUE TITLE
Portable seed extractors can't extract seeds

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#50876]
Probably very old bug because I remember this from months back. 

#### Reproduction:
1. Put any plant into a portable seed extractor. 
2. Try to click it or interact with it any way you can think of. 

No seeds. 

I remember being able to extract seeds with it long ago. Currently Portable seed extractors seem to work as reskinned plant bags. Wiki says activate it but that just empties it.

**Comment by TemporalOroboros** [comment]
It's in the right-click context menu.

**Comment by Angustmeta** [comment]
What the hell. The only thing I didn't check. Imma add that to wiki.
