### ISSUE TITLE
Utility belt sprite broken

### ISSUE THREAD

**Issue by trerri** [tgstation/tgstation#50870]
Issue reported from  Round ID: [136271](https://scrubby.melonmesa.com/round/136271) (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 513.1520
![image](https://user-images.githubusercontent.com/63235460/80954801-5f66be80-8dfe-11ea-9da6-3d5e41592fab.png)
![image](https://user-images.githubusercontent.com/63235460/80954813-6392dc00-8dfe-11ea-96f2-b33136cc02f7.png)
![image](https://user-images.githubusercontent.com/63235460/80954823-68f02680-8dfe-11ea-8289-4d3cab687308.png)

**Comment by Dorsisdwarf** [comment]
Merging with #50895 for comprehensiveness.
