### ISSUE TITLE
Graphical issues

### ISSUE THREAD

**Issue by Kastovin** [tgstation/tgstation#50875]
Issue reported from  Round ID: [136286](https://scrubby.melonmesa.com/round/136286) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517

Pink clothing, Errors when planting seeds, generally not good at all.

**Comment by ArcaneMusic** [comment]
100% fixed by #51340
