### ISSUE TITLE
Add some more clear text to wizard's statue

### ISSUE THREAD

**Issue by Ikoden** [tgstation/tgstation#50874]
I got turned into a statue and to be honest the text didnt clearly say whether I should use the ultra speed, ultra damage to destroy stuff or just wait till i get unturned. I got confused. Am I to hepl the wiz, to keep helping the station, am i not to do anything and wait till i turn back to my old self?

**Comment by davethwave** [comment]
The general consensus is that if your turned into a statue by wiz non willingly your team wiz until you turn back into human which takes about 5ish minutes I think.

**Comment by ATH1909** [comment]
```
				if(L.mind)
					L.mind.transfer_to(S)
					if(owner)
						to_chat(S, "<span class='userdanger'>You are an animate statue. You cannot move when monitored, but are nearly invincible and deadly when unobserved! Do not harm [owner], your creator.</span>")
```

**Comment by Dorsisdwarf** [comment]
Feautre requests go on the appropriae forum area.

**Comment by Ikoden** [comment]
Ok, thanks for the feedback. I think Davethwave cleared the issue by stating the general consensus.
