### ISSUE TITLE
Changeling flesh disguise ID shows incorrect icon

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#50877]
This makes it impossible to impersonate living crew unless you manage to get a real copy of their ID. Many fun non-murder gimmicks that could have happened, gone. 

![200504 1737 06](https://user-images.githubusercontent.com/46400996/80984739-8b019d00-8e2e-11ea-9880-a83d8d338989.png)
Hmmm I really wonder which one the changeling is. 

Examining changeling (100% flesh disguise):
![200504 1736 29](https://user-images.githubusercontent.com/46400996/80984818-a8366b80-8e2e-11ea-8056-33f24a4a6276.png)

Examining real officer:
![200504 1736 47](https://user-images.githubusercontent.com/46400996/80984871-bab0a500-8e2e-11ea-8c6f-e463aca9cb6f.png)

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/pull/51597/files#diff-322a73d45bcad39b11a7545ac1519c5e

see this, the iconstates aren't copied over, likely the cause.
