### ISSUE TITLE
Removing a defibrillator from a wall mount with both hands full/occupied causes it to drop a duplicate defibrillator on the ground that can then be used on as many wall mounts as you want and allows you to use the paddles from the duplicated defib wall mounts anywhere in the map while losing a hand slot forever

### ISSUE THREAD

**Issue by WaterBuffal0** [tgstation/tgstation#50881]
## Round ID:
Reproducible in every round
Reporting client version: 513.1522

## Reproduction:
Spawn/print a defibrillator/compact defibrillator with a battery cell inserted (powered or unpowered doesn't matter)
Place an unhooked defibrillator mount on a wall
Place the defibrillator/compact defibrillator with the cell into the wall mount as usual
Pick up an item/items to occupy both hand slots
Alt-click the defibrillator wall mount with the unit loaded inside of it
The defibrillator will then drop onto the floor with the message "You need a free hand!" but there will still be a defibrillator in the wall mount causing there to be 2 defibrillators instead of 1 now
Place the duplicated defibrillator into as many other empty wall mounts as you want and it will still work , the duplicated mounts provide infinite-length paddles that work and also never unoccupy the other off-hand hand slot when you wield them with both hands and then unwield them 
Removing the defibrillator from each of the mounts will not cause it to duplicate the item but instead teleport the item back into either your hands (if you removed it with empty hands) or at your feet at the location of whichever mount you recently removed it from (if you attempted to remove it with both hands occupied again)

Additional notes of things that I found:
* The duplicated defibrillator is completely usable
* The defibrillator will disappear from wherever it physically is on the station whether Its in your hand/backpack/anywhere and return to Its original position if:
1) you remove the defibrillator from the mount with free hands
2) you try to remove the defibrillator from the mount with both hands occupied it will simply disappear from where it was before and instead spawn at your feet
* The duplicated defibrillator can occupy as many different defibrillator mounts as you put it in, it cannot be duplicated as a physical item but it can be in as many defibrillator mounts at once and still work
* the duplicated defibrillators that are currently in mounts allow the user to use the paddles from anywhere in the map while still displaying the message "The defibrillator's paddles overextend and come out of your hands!" when you walk away from the mount but the paddles in fact stay in your hands and are usable from anywhere in the map
* if you use the duplicated defibrillator's paddles and occupy both hand slots with them and later drop the paddles, the off-hand slot will stay occupied until you lose your hand and have it reattached.

**Comment by Timberpoes** [comment]
Excellent write-up. Detailed reproduction steps. I was the last person to touch this code, so following your steps I was able to fix the issue very easily when I identified what I'd done wrong.
