### ISSUE TITLE
Adding a defibrillator with no cell to an empty wall mount causes the defib to disappear from the hand and from the world until the wall mount is disassembled

### ISSUE THREAD

**Issue by WaterBuffal0** [tgstation/tgstation#50880]
## Round ID:
Reproducible in every round
Reporting client version: 513.1522

## Reproduction:
Spawn/print a defibrillator or a compact defibrillator without a battery cell inserted
Mount an unhooked defibrillator wall mount onto a wall
With the defibrillator/compact defibrillator in your hand press the empty defibrillator wall mount thats on the wall
The defibrillator/compact defibrillator disappears from your hand and a warning message is shown
"Only defibrilators containing a cell can be hooked up to the defibrillator mount!"
the wall mount still appears empty and when trying to alt-click it with an empty hand to remove the defibrillator you receive the message that it is empty
"It'd be hard to remove a defib unit from a mount that has none."
When using a wrench on the "empty" wall mount the wall mount will come off the wall as well as the defibrillator unit that supposedly disappeared.
Note that you are able to put as many defibrillator units with no battery cell loaded into the empty wall mounts as you want and they all return on disassembly
Also note that you are still able to place a defibrillator with a battery cell into the mount while one or multiple hidden defibrillators with no cells are inside of it

**Comment by Timberpoes** [comment]
Excellent write-up. Detailed reproduction steps. I was the last person to touch this code, so following your steps I was able to fix the issue very easily when I identified what I'd done wrong.

**Comment by WaterBuffal0** [comment]
> Excellent write-up. Detailed reproduction steps. I was the last person to touch this code, so following your steps I was able to fix the issue very easily when I identified what I'd done wrong.

Hey man thanks a lot, I really really appreciate it! Its my first time posting on Github and I created this account just to report on a couple of issues that affected me in the last couple of days, I really really appreciate the fast response!! few more bug reports will be coming from me soon!

**Comment by Dorsisdwarf** [comment]
help words
