### ISSUE TITLE
Setup Characeter bug

### ISSUE THREAD

**Issue by Huntgn** [tgstation/tgstation#50882]
Issue reported from  Round ID: [136299](https://scrubby.melonmesa.com/round/136299) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1518

I cannot use the Character Setup anymore, it just loads endlessly

**Comment by Dorsisdwarf** [comment]
@Huntgn Is this bug still affecting you, or was it a one-off?

**Comment by Huntgn** [comment]
No it has been gone since yesterday evening thanks
