### ISSUE TITLE
Duplicate asset caching is causing an overabundance of warnings.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#50887]
Private server testing unrelated code.
<details>
<summary>Server Revision:</summary>

BYOND Version: 513.1522
Server revision compiled on: 2020-05-04
Master commit: b11b3ae7a9ad91d6340f85c512662283d69f7a56
Local commit: c52c0df1e6478fc4a64b1667bdbd31b81d707d87

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1
Enforce Continuous Rounds: 10 of 22 roundtypes
Allow Midround Antagonists: 6 of 22 roundtypes
</details>

## Reproduction:

- Examine something more than once.
  - With some types this affects the entire type (ie: examining one plasteel floor will cause this with every other plasteel floor)
  - Some types only do this on a per-object basis (space, Robust Harvest bottles, etc.)
- Wait; the economics subsystems will cause this at payday (and might not distribute credits as a result? I didn't check).
EDIT: Credit to SpaceManiac for pointing out #50759 this is probably caused by that.

![BugFreezeFrame](https://user-images.githubusercontent.com/53582584/81008113-3696f700-8e07-11ea-8dc5-2740990432e3.PNG)
![AssetBug](https://user-images.githubusercontent.com/53582584/81008128-3eef3200-8e07-11ea-8f3e-ef576659dee0.PNG)
![Runtime](https://user-images.githubusercontent.com/53582584/81008017-0d766680-8e07-11ea-9b9e-45c88c141915.PNG)

<details>
<summary>Call Stack: (click me)</summary>

![BugCallStack](https://user-images.githubusercontent.com/53582584/81008040-19fabf00-8e07-11ea-85b5-dec80df2a079.PNG)
![CallStack1](https://user-images.githubusercontent.com/53582584/81008042-1bc48280-8e07-11ea-9cc6-6ef42988b24d.PNG)
![CallStack2](https://user-images.githubusercontent.com/53582584/81008049-1d8e4600-8e07-11ea-9b91-c6e9cfee4413.PNG)
![CallStack3](https://user-images.githubusercontent.com/53582584/81008054-1f580980-8e07-11ea-82ea-74975591ccf1.PNG)
![CallStack4](https://user-images.githubusercontent.com/53582584/81008059-20893680-8e07-11ea-8ebf-a6b4959d5f9f.PNG)
![CallStack5](https://user-images.githubusercontent.com/53582584/81008062-21ba6380-8e07-11ea-83c8-38529d4167de.PNG)
![CallStack6](https://user-images.githubusercontent.com/53582584/81008068-241cbd80-8e07-11ea-911b-7f91605d8004.PNG)
![CallStack7](https://user-images.githubusercontent.com/53582584/81008072-254dea80-8e07-11ea-862c-653504ddb44f.PNG)
![CallStack8](https://user-images.githubusercontent.com/53582584/81008078-25e68100-8e07-11ea-859e-27bf4750879b.PNG)
![CallStack9](https://user-images.githubusercontent.com/53582584/81008079-2717ae00-8e07-11ea-9e32-1b858ee38632.PNG)
![CallStack10](https://user-images.githubusercontent.com/53582584/81008081-2848db00-8e07-11ea-82a1-bc6dd9aeacd3.PNG)
![CallStack11](https://user-images.githubusercontent.com/53582584/81008085-28e17180-8e07-11ea-8355-e5c132e6229f.PNG)
![CallStack12](https://user-images.githubusercontent.com/53582584/81008090-2a129e80-8e07-11ea-925d-fc7b886a6504.PNG)
![CallStack13](https://user-images.githubusercontent.com/53582584/81008093-2b43cb80-8e07-11ea-9718-343bdd939c5e.PNG)
![CallStack14](https://user-images.githubusercontent.com/53582584/81008097-2da62580-8e07-11ea-891c-0e026cba7037.PNG)
![CallStack15](https://user-images.githubusercontent.com/53582584/81008100-2ed75280-8e07-11ea-8134-c00c1f4614d6.PNG)
</details>

**Comment by optimumtact** [comment]
these are just warnings though? they won't interrupt proc flow

**Comment by TemporalOroboros** [comment]
They might not be full runtimes, but they get annoying fast when you're using the VSCode debugger to check for runtimes.

**Comment by optimumtact** [comment]
I suppose so @SpaceManiac is there anyway to ignore stack traces conditionally,

@MrStonedOne any disagreement with changing it to a log message (loses stack info though)

**Comment by SpaceManiac** [comment]
Yes, the debugger could gain an option to not pause on a CRASH inside stack_trace or a proc like it.

Of course, if these are being spammed, the root cause should be fixed.

**Comment by TemporalOroboros** [comment]
Seems to be fixed on the latest version. I spent a while running around a local spamming examine with runtime breakpoints enabled and got nothing.
