### ISSUE TITLE
List of tools with missing sprites

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#50898]
Issue reported from  Round ID: [136312](https://scrubby.melonmesa.com/round/136312) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

Reproduction: I select equipmented as an atmos tech, took off the tool belt, and tried all the tools in my belt slot. I then did the same as a chief engineer.

/obj/item/analyzer

/obj/item/t_scanner

/obj/item/crowbar

/obj/item/wrench

/obj/item/weldingtool

--I'd imagine the upgraded industrial/the industrial welding tools both have missing sprites as well.--

/obj/item/weldingtool/experimental

/obj/item/crowbar/power

/obj/item/stack/cable_coil  (this one is red for some reason)

/obj/item/screwdriver/power

Not a tool but spawns with engineers: 

/obj/item/modular_computer/tablet/preset/advanced

**Comment by Fikou** [comment]
probably the red crowbar and medical wrench as well

**Comment by BeeSting12** [comment]
Yeah as a general rule if one item is messed up then its children are probably messed up too, although this is not always the case as /obj/item/storage/belt/military is broken but /obj/item/storage/belt/military/army is fine.
