### ISSUE TITLE
Beepsky's battery has a missing sprite.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#50900]
/obj/item/stock_parts/cell/potato

**Comment by TerraGS** [comment]
Narrowed it down to being related to the cell charge overlay but I can't see what it's doing different from non-potato cells which apply the overlay properly. Will continue to investigate.

**Comment by TerraGS** [comment]
Reviewing findings:
Tested a non-potato cell by changing the icon file to harvest.dmi and icon to potato and called update_icon() and was able to reproduce the visual bug.
