### ISSUE TITLE
Being force-transformed from a humanoid into a Cyborg by the Staff of Change and then being disassembled yields an empty MMI with no brain inside of it and no way to remove the brain, but the player is still physically bound to the MMI and able to speak and see

### ISSUE THREAD

**Issue by WaterBuffal0** [tgstation/tgstation#50908]
## Round ID:
Reproducible in every round
Reporting client version: 513.1522

## Reproduction:
I would like to note that this happened to me only once so I only have one data point to go over, I don't remember the round ID, but I will describe in detail exactly all that I did to reproduce this issue

Spawn staff of change (Wizard item)
Get a second player who's human (since I was a human at that time, CMO if it matters)
Cast change to cyborg on the human
As the borg, change yourself into a medborg (I did this before I got disassembled)
Open your cover and get another player to disassemble you (cut all of your wires)
The MMI that then results from the disassembly still has the human who got turned into a cyborg's brain bound to it, which means the player can speak from the MMI and view his surroundings from the MMI, but the MMI shows as the empty sprite and when attempting to remove the brain it fails as if the MMI is empty

I wouldn't say that the lack of a brain in the MMI is "magic" since I can still speak and view from the MMI, and I haven't tested this next part yet - but since the MMI is supposedly empty, you should be able to place a second brain in there and then have two players bound to the MMI, which is then classified clearly as a bug, so I think this better be fixed so that next time I can return myself to my human body and also avoid two players in one MMI

**Comment by nianjiilical** [comment]
i can confirm that using roburgers to change humanized monkeys into borgs and then disassembling them does not produce a brain, so it's probably true with roburgers too

**Comment by BeeSting12** [comment]
#50804 is probably the same as this. I would close #50804 though since this one is a better description.

**Comment by RaveRadbury** [comment]
The title of this report gives me anxiety every time I read it.

**Comment by MacBlaze1** [comment]
let me take a crack at this

**Comment by MacBlaze1** [comment]
yeah I need another human for this to work, when I changed a blank human into a cyborg they had no MMI.

**Comment by MacBlaze1** [comment]
https://github.com/tgstation/tgstation/blob/06e440ad32f83f78f84b1ec2c1b6b80af21894ac/code/modules/projectiles/projectile/magic.dm line 161, line 173

**Comment by MacBlaze1** [comment]
https://github.com/tgstation/tgstation/blob/01c19e22be59ebf7fc90be55f52ee26538068e02/code/modules/mob/living/silicon/robot/robot.dm line 158 
brain is null when you try to deconstruct an mmi in /obj/item/mmi/attack_self(mob/user)
	if(!brain)
		radio.on = !radio.on
		to_chat(user, "<span class='notice'>You toggle [src]'s radio system [radio.on==1 ? "on" : "off"].</span>")
	else
		eject_brain(user)
		update_icon()
		name = initial(name)
		to_chat(user, "<span class='notice'>You unlock and upend [src], spilling the brain onto the floor.</span>")

**Comment by Sealed101** [comment]
can no longer reproduce, both with roburgers and humanoid to borg wabbajack. hooray!
#80652 may have plugged the hole that was causing it, though that issue onl appeared at some other point in time. something somewhere deeper down the mind transfer pipeline may have changed? unsure but this is fixed
