### ISSUE TITLE
Warden office in metastation has no APC and machines are magically powered

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#50909]
Issue reported from  Round ID: [136335](https://scrubby.melonmesa.com/round/136335) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

![image](https://user-images.githubusercontent.com/32805898/81031914-9d420200-8e53-11ea-9488-749dd54ac051.png)

As the title says. Turning off Brig and Armory APC did not effect the Warden office. They are the only two APC nearby.

**Comment by EgorDinamit** [comment]
Warden's room is using equipment room APC.

**Comment by Cartographer-D** [comment]
If you give me a good place to put the Warden's APC I will fix it now.

Looks like before, Metastation used the same area for the warden's office and the gear room.

Having an APC dedicated to such a small room may be a predicament, I could have that entire U-shaped hallway also be connected.

**Comment by WarlockD** [comment]
What about swaping where the scrubber and disposal.  Move the AI screen to the block just above the side exit door and putting the apc there?

I mean, Its a very secured room and might be the only thing holding you back from zombies.  But if the APC is outside the room, they could destroy it and just crowbar the doors.

**Comment by Cartographer-D** [comment]
> 
> 
> What about swaping where the scrubber and disposal. Move the AI screen to the block just above the side exit door and putting the apc there?

That's not an AI screen, that's the brig cell's console.


> I mean, Its a very secured room and might be the only thing holding you back from zombies. But if the APC is outside the room, they could destroy it and just crowbar the doors.

I don't see why this vulnerability would be an issue.

**Comment by WarlockD** [comment]
If the APC is destroyed or turned off, it just takes a crowbar to open the door.  But then again I am kind of at a loss where to put it now.

**Comment by Cartographer-D** [comment]
@TheMidnightRose thoughts?

**Comment by msgerbs** [comment]
No air alarm either REEEEEE. If you're not particularly set on fixing this I'll take a look and see if this area can be remapped a little. It's quite small for everything the Warden is meant to have.
