### ISSUE TITLE
techpriest hood has a missing sprite, health icon shows as dead when at max health

### ISSUE THREAD

**Issue by Makuru-DD** [tgstation/tgstation#50920]
Issue reported from  Round ID: [136359](https://scrubby.melonmesa.com/round/136359) (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 513.1517

the techpriest hood causes an ERROR message in head
and sometimes it says im dead even though i am at max health and no virus or nanites

**Comment by ArcaneMusic** [comment]
Can you add any reproduction steps? Currently unable to reproduce and cannot find any issues with the  head sprite at the moment.

**Comment by Fikou** [comment]
this was solved already im pretty sure
