### ISSUE TITLE
Limb grower has no option to print organs

### ISSUE THREAD

**Issue by meep109** [tgstation/tgstation#50925]
Issue reported from  Round ID: [136389](https://scrubby.melonmesa.com/round/136389) (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 513.1522
I did not see it as an option anywhere on the limb grower

**Comment by Dorsisdwarf** [comment]
@Fikou thats your pr

**Comment by ivanmixo** [comment]
It is a LIMB grower, though.

**Comment by ArcaneMusic** [comment]
Appears to have been fixed, limb grower has all of it's available organs printable from the other menu.
![image](https://user-images.githubusercontent.com/41715314/99874492-61377a00-2bb6-11eb-8eac-cdf5bb0225a3.png)
