### ISSUE TITLE
All null rod variants (except the hanzo steel/katana) that can be equipped in the belt slot have a missing sprite

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#50929]
/obj/item/nullrod/claymore
/obj/item/nullrod/claymore/darkblade
/obj/item/nullrod/claymore/chainsaw_sword
/obj/item/nullrod/claymore/glowing
/obj/item/nullrod/claymore/multiverse
/obj/item/nullrod/claymore/saber
/obj/item/nullrod/claymore/saber/red
/obj/item/nullrod/claymore/saber/pirate
/obj/item/nullrod/sord
/obj/item/nullrod/scythe/talking/chainsword
/obj/item/nullrod/hammmer
/obj/item/nullrod/whip
/obj/item/nullrod/hypertool
/obj/item/nullrod/spear

**Comment by ShizCalev** [comment]
#51776
