### ISSUE TITLE
Wigs have pink underneath them

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#50936]
## Reproduction:
I did this with a natural wig set to "overeye long" but you should be able to do it with any style I think.

**Comment by Mickyan** [comment]
Likely caused by this mutable_appearance pointing to the wrong icon file

![Screenshot_5](https://user-images.githubusercontent.com/38563876/81455805-8facb500-9190-11ea-978d-72eed54a61fc.png)
