### ISSUE TITLE
baby goliath explosions throw you making it really hard to beat the broodmother

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#50931]
Issue reported from  Round ID: [136407](https://scrubby.melonmesa.com/round/136407) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1520

**Comment by Fikou** [comment]
git gud

**Comment by Tumesuo** [comment]
manuel moment

**Comment by redguy999** [comment]
Yes I know it’s not a bug.
Still an issue

**Comment by trollbreeder** [comment]
i ded
