### ISSUE TITLE
Equipment swapping makes changeling flesh disguise items get stuck in hand 

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#50943]
Pretty minor thing. 

#### Reproduction:

1. DNA sting someone who has a scientist labcoat. 
2. Get naked and transform into them. 
3. Pick up a real labcoat/overclothing item. Press the equipment swap hotkey. 

The flesh suit is now stuck in hand and can not be dropped, thrown or placed. Activating it in hand does nothing, but you can press the equip swap hotkey again to swap back. 

![200506 1608 01](https://user-images.githubusercontent.com/46400996/81187037-cf6a7580-8fb3-11ea-9ac1-b194de1b8870.png)

**Comment by nemvar** [comment]
Equipment swap hotkey is not respecting nodrop. Also not calling dropped().
If someone wants to fix this, please also take a look at https://github.com/tgstation/tgstation/issues/50798
