### ISSUE TITLE
when crowbarred up and replaced, floor tiles dissapear from hand but are not placed

### ISSUE THREAD

**Issue by joybod** [tgstation/tgstation#50958]
Issue reported from  Round ID: [136499](https://scrubby.melonmesa.com/round/136499) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

as title says, floor tiles that are crowbared and then replaced will disappear from hand and not be placed. does not occur if holding a stack of floor tiles before crowbaring or picking up a stack after crowbaring.

**Comment by willox** [comment]
this is fixed by https://github.com/tgstation/tgstation/pull/50950
