### ISSUE TITLE
Eye blurring does not affect open-space

### ISSUE THREAD

**Issue by AMonkeyThatCodes** [tgstation/tgstation#50972]
## Reproduction:
1. go to any map with multiz
2. get eye_blurry above 0 for whatever reason
3. Look down into openspace
4. notice you can see fine into whatever is below

plane master stuff, blurriness is handle only in the floor planemaster.

![image](https://user-images.githubusercontent.com/20987591/81329141-63187080-909e-11ea-8457-104b85becb79.png)

**Comment by nemvar** [comment]
Presumably openspace is on a different plane than the floor and walls.

**Comment by Qustinnus** [comment]
yes. check OP

**Comment by Qustinnus** [comment]
I think I fixed this with my planemaster rework.
