### ISSUE TITLE
Cult floor tiles fit in chests

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#50978]
## Testmerges:

- #50558 
- #50955 

## Reproduction:

- Acquire a chest from a necropolis tendril
- Locate the cult ruin on lavaland
- Use the chest to gather the cult items
- Notice that you are picking up the cult floors too

**Comment by Fikou** [comment]
lol is that why the wizard shuttle has an empty floor tile below the crate? the overlay cult flooring goes inside the crate

**Comment by Fikou** [comment]
duplicate of #47316
