### ISSUE TITLE
Monkey transformation clears stamina damage

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#50973]
#### Reproduction:
- Be ling. 
- Give yourself get 300 stamina damage. 
- Monkey. 

All stamina damage gone. No need to wait 10 seconds. 

Stuns, knockdowns, chems and all other damage types are retained when you go monkey, so I feel stamina damage should stay too for _consistency._ It also still clears dermal implants but you all knew that. 

![SMT](https://user-images.githubusercontent.com/46400996/81332869-0455f580-90a4-11ea-9039-1d2c0588612b.png)

**Comment by MacBlaze1** [comment]
found it, https://github.com/tgstation/tgstation/blob/06e440ad32f83f78f84b1ec2c1b6b80af21894ac/code/modules/antagonists/changeling/powers/lesserform.dm 
no TR_KEEP_STAMINA_DAMAGE

**Comment by Angustmeta** [comment]
Same with monkey from genetics injector.

**Comment by HomocidlePancakes** [comment]
Makes sense for the ling ability to reset stamina. Afterall, it is used as an escape ability pretty often.

**Comment by MacBlaze1** [comment]
@Dorsisdwarf is this a bug? Ive already written a fix for it, and it kinda doesn't make sense for lings to use this as an escape all.

**Comment by Angustmeta** [comment]
I'm mostly concerned about monkeys from DNA injectors.
