### ISSUE TITLE
The dead goats in the goat king ruin aren't.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#50980]
## Testmerges:

- #50558 
- #50955 

## Reproduction:

1. Find the lavaland goat king ruin.
2. Attempt to butcher the goat corpses.
3. Get attacked by the goat corpses.
  - This may aggro every goat corpse within viewing distance, I don't remember.

**Comment by ATH1909** [comment]
That is not dead which can eternal lie...
