### ISSUE TITLE
You can become a Jedi Master with a mere 2 portals.

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#50987]
## Testmerges:

#50955: 'Maybe fix bots' by MrStonedOne at commit 068ef0bdb4
#50558: '[WIP] Adds Medical Wounds: Bamboo Bones and the Skin of Your Teeth' by Ryll-Ryll at commit 7f5b545ffc
#50981: 'Completely disables papercode' by optimumtact at commit c21fde5f17

## Reproduction:

1. make a portal with hand tele or portal gun
2. stand on the portal tile
3. firecarry someone
4. you can now throw them around infinitely until you get stunned

**Comment by ATH1909** [comment]
the return of the fireman carry throw bug?

hell yeah, that bug was really cool.

**Comment by ArcaneDefence** [comment]
This also works by far simpler things.
Such as standing on a table while the person you are picking up is not on a table.
Or making a locker underneath yourself and not moving.
Anything that the body cannot enter the same tile as yourself with.
