### ISSUE TITLE
Barcodes Broken

### ISSUE THREAD

**Issue by Shikarego** [tgstation/tgstation#50998]
Issue reported from  Round ID: [136635](https://scrubby.melonmesa.com/round/136635) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517

Wrapped stacks of plasma to test this. (Regular package wrapping)
Package with barcode from laptop (tried with ID in and out while printing tag)
Package with barcode from sales tagger

All packages sold for full credits, no credits given to the person who printed the barcode.

**Comment by Krysonism** [comment]
I've also noticed this. I've personally put tagged crates on the shuttle and not received any money.
