### ISSUE TITLE
Holograms continue to stay still if their parent holopad moves

### ISSUE THREAD

**Issue by Urgon** [tgstation/tgstation#50994]
## Round ID:
[136626](https://scrubby.melonmesa.com/round/136626)

## Testmerges:
#50981: 'Completely disables papercode' by optimumtact at commit c21fde5

## Reproduction:
1. Find a holodisk
2. Insert the holodisk in a holopad
3. Record yourself
4. Stop the recording
5. Put the recording on loop
6. Unsecure the holopad
7. Move it around

**Comment by Angustmeta** [comment]
Dupe with #50937

**Comment by Urgon** [comment]
Dupe of #50937
