### ISSUE TITLE
Weird interactions with revolutionary/cultist statuses

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#51009]
136655

I was a roundstart cultist and I also became the head cultist. Later on I got converted by a head rev, so I had the rev/cult status at the same time. However, the revolutionary status apparently removed my cult HUD. I was later deconverted (not sure how) and I did not regain my cultHUD. Gamemode was dynamic.

**Comment by wesoda25** [comment]
I will make a PR, but would it be better to block a conversion if the target is with a team antag group, or to force them into the new one (and out of the old one) instead?

**Comment by Dennok** [comment]
Or make team hud toggleable.

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/62718
