### ISSUE TITLE
"Move Upwards" verb is really bad.

### ISSUE THREAD

**Issue by uomo91** [tgstation/tgstation#51006]
## Reproduction:

Play on a multi-z map, move to a spot with open space above you, click the IC tab, and click "move upwards".
You will magically levitate upwards and instantaneously fall back down.
You can use this verb repeatedly very fast, you can use it while stunned, and you can even use it while dead.

**Comment by LemonInTheDark** [comment]
Related to #49761

**Comment by Dorsisdwarf** [comment]
Jump

**Comment by LemonInTheDark** [comment]
See #49667 for more details, issue jannies cleanup on aisle 4
