### ISSUE TITLE
Pacifists can beat monkeys to death, but just bare-handed.

### ISSUE THREAD

**Issue by BangingDonk** [tgstation/tgstation#51012]
## Round ID: 
Manuel: R136678

## Reproduction:
Create a character with the pacifist trait. Switch to harm intent. Verify that your hand is empty. Click the monkey -- rather than getting the usual pacifism message, you will instead wail on the monkey as if you were completely fine with the idea. The second that you try to do it with any sort of damaging object in hand, you get the pacifist message as normal.

Issue discovered on Manuel, reproduced on a locally hosted instance of a server as well.

**Comment by ArcaneDefence** [comment]
This is no longer the case as monkeys are now a species.
