### ISSUE TITLE
Captain spawned as a traitor during a normal Bagil dynamic round

### ISSUE THREAD

**Issue by AnuvKH** [tgstation/tgstation#51025]
Round ID: [136724](https://scrubby.melonmesa.com/round/136724)
Server: Bagil

Revision: Master commit: 6386994061324f1f0a67154b09285a816f2315c2
The following pull requests are currently test merged:
#50955: 'Maybe fix bots' by MrStonedOne at commit 068ef0bdb4
#50558: '[WIP] Adds Medical Wounds: Bamboo Bones and the Skin of Your Teeth' by Ryll-Ryll at commit 7f5b545ffc
#50981: 'Completely disables papercode' by optimumtact at commit c21fde5f17

Problem Description: Captain became a roundstart traitor during dynamic
https://scrubby.melonmesa.com/round/136724?h=johonasmexicanjo

What did you expect to happen: Roundstart cap/sec shouldn't be able to become antag last I checked

What happened instead: Captain became traitor and apparently other roundstart sec can too right now (per admins on at the time)

Why is this bad/What are the consequences: A huge degree of crew dynamics and base trust relies upon sec/cap not being baddies

Steps to reproduce the problem: Unsure. 

Possibly related stuff: Unless this was some secret/very recent change to dynamic I didn't think this was the case.

**Comment by kriskog** [comment]
Its an order of operations thing, the restricted roles list is overwritten by the dynamic config. Ill look into fixing it tomorrow.

**Comment by ATH1909** [comment]
@kriskog do we know what broke it?

**Comment by kriskog** [comment]
??
> Its an order of operations thing, the restricted roles list is overwritten by the dynamic config.

**Comment by senjx** [comment]
![image](https://user-images.githubusercontent.com/52981310/81608555-7e3bf680-93a4-11ea-8378-0d9af98615ac.png)
