### ISSUE TITLE
Error setting up dynamic.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#51028]
Issue reported from  Round ID: [136735](https://scrubby.melonmesa.com/round/136735) (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1513

Starting game...
ADMIN LOG: Dynamic mode parameters for the round:
ADMIN LOG: Centre is 0, Width is 1.8, Forced extended is Disabled, No stacking is Enabled.
ADMIN LOG: Stacking limit is 90, Classic secret is Disabled, High population limit is 55.
Error setting up dynamic. Reverting to pre-game lobby.
Welcome to Mother's Warehouse Whiskey!

ROUND ID 136735

**Comment by Zytolg** [comment]
This just happened on Manuel Round ID: 136736
Only replace Dynamic with Secret.

**Comment by Zytolg** [comment]
Also happened on Manuel Round ID: 136737

**Comment by kriskog** [comment]
There was a config issue, should be okay now
