### ISSUE TITLE
Delta station bar disposal chute bug

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#51024]
## Round ID: 
Confirmed on local, forgot the round encountered on

## Reproduction:
It has no trunk under it, and so the chute does not connect to the disposal network, and will spit its contents out when it engages.
![image](https://user-images.githubusercontent.com/51932756/81488297-473ed700-9224-11ea-8792-a287a4a9b8bd.png)

**Comment by msgerbs** [comment]
Don't know when this was fixed but it appears to be fixed now.

**Comment by msgerbs** [comment]
This is fixed. Closing.
