### ISSUE TITLE
Fluiducts brick when "Too long"

### ISSUE THREAD

**Issue by Vanadiom** [tgstation/tgstation#51034]
## Round ID:
[136746](https://scrubby.melonmesa.com/round/136746)

## Testmerges:
#50981 
Mastercommit:
"6e77a5ac3a88eef7b89a795ba06d862fc3643bee"

## Reproduction:
1.Have a long fluiduct net on lavaland,
2. try to connect another long fluiduct net to it for that sweet sweet geyser stuff.
3. Get sad. 
(The fluiducts get problems showing a connection, and even if they do, achinery doesnt draw from the second fluinet.)

**Comment by Time-Green** [comment]
This happens around > 400-500 
Christ that’s a really long duct

**Comment by Sealed101** [comment]
could not reproduce this with a fluiduct net of of around 500 ducts combined. some production machines do get slowed down but never go out of commission completely

still not completely sure in the stability of this thing, so I'll let this issue hang

**Comment by Time-Green** [comment]
It’s been through some reworks and optimisations since, can probably kill the issue and see if a new one pops up 🙂

**Comment by Sealed101** [comment]
my man
