### ISSUE TITLE
Watchers are too easy now and no one talks about it.

### ISSUE THREAD

**Issue by Vanadiom** [tgstation/tgstation#51033]
## Round ID:
All of em

## Testmerges:
Doesnt matter, been like that for many months

## Reproduction:
Get shot by watcher Ice blast, notice nothing happening, carry on with your day.

**Comment by wesoda25** [comment]
unless ur a lizard

**Comment by ArcaneMusic** [comment]
This is a balance request if nothing else.

**Comment by Vanadiom** [comment]
It worked like once, last time, I just give up and will close it because I hate issue loitering.
