### ISSUE TITLE
Borgs and the *circle emote

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#51047]
Issue reported from  Round ID: [136769](https://scrubby.melonmesa.com/round/136769) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517

a circled hand drops when borgs say *circle

**Comment by CoffeeDragon16** [comment]
Just tested it on my updated local, doesn't look like cyborgs can do that anymore. Either that or I couldn't reproduce it, maybe close?

**Comment by dragomagol** [comment]
Unable to reproduce
