### ISSUE TITLE
Borg sensor augs show health and implants with suit sensors off

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#51046]
Issue reported from  Round ID: [136769](https://scrubby.melonmesa.com/round/136769) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517
to repro:
-be borg
-turn on sensor augs
-ask someone to turn their sensors off and/or get them mindshielded

**Comment by nemvar** [comment]
Doesn't sensor aug just give you med/sec/dia hud? In that case, isn't this just intended functionality?

**Comment by nemvar** [comment]
yeah this is intended.

**Comment by Tharcoonvagh** [comment]
Yeah, but it's only been like this for like two weeks
