### ISSUE TITLE
Can't help up fallen person if they're on fire

### ISSUE THREAD

**Issue by nwarz** [tgstation/tgstation#51053]
Issue reported from  Round ID: [136793](https://scrubby.melonmesa.com/round/136793) (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1512

When attempting to help someone up who had fallen down while they were on fire, I got a message "You can't put him out with just your bare hands!" It should probably still be possible to use the help intent to help a fallen player up, even if they are burning.

**Comment by HomocidlePancakes** [comment]
You need gloves.

**Comment by SkeletalElite** [comment]
You should catch on fire too if you help them up

**Comment by necromanceranne** [comment]
You need fireproof gloves to touch people on fire. This isn't a bug as far as I'm aware.
