### ISSUE TITLE
Abandoned cryopod ghost role poison strangeness

### ISSUE THREAD

**Issue by ftoxs** [tgstation/tgstation#51054]
Issue reported from  Round ID: [136778](https://scrubby.melonmesa.com/round/136778) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1521

Played abandoned cryopod ghost role. About the time I cleared out all the alien resin, 40 minutes or so into the shift, I started getting waves of dizziness. "You feel a wave of dizziness" messages in giant bold red letters. Rather than staying centered on my character, my view would jump a couple of times per wave, occasionally very dramatically. This lasted for about 20 minutes until an admin manually purged my guy.

Responding admin noted that it seemed to be poison, and anomalous enough that it was almost certainly a bug. The only thing that showed on their health scanners or the in-game ones were the pentetic acid I'd taken to try and fix it.

Worth noting that there were lots of giblets up there rotting while I was clearing resin, so maybe it was related to a disease or something? Though the health scanners showed no sign of disease. I also had to eat a ton of food in order to be sated; so much so I was sure the two things were related. I had handled uranium sheets slightly prior to this beginning, but I had also eaten 40u of pentetic before I ahelped. All alien corpses were dragged into small out-of-the-way rooms to generate miasma far away from me, so I don't think it was that. The alien queen did get a couple hits on me with their "neurotoxin" ranged attack, but I've never seen this happen because of that.

**Comment by XDTM** [comment]
"wave of dizziness" is only used in the dizziness disease symptom, so it was definitely a disease. As for the source of the disease, it's possible it simply spawned from a random event, if not from miasma. Health scans not reporting anything might be due to the disease having high stealth.

**Comment by Fikou** [comment]
miasma moment
