### ISSUE TITLE
Fake nuke disk on pubby can be used for illegal tech

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#51063]
Issue reported from  Round ID: [136849](https://scrubby.melonmesa.com/round/136849) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517

**Comment by Pugie** [comment]
Not as bad as using syndicate card deck
