### ISSUE TITLE
Changelings cannot revive if decaptiated 

### ISSUE THREAD

**Issue by MoonFalcon** [tgstation/tgstation#51086]
Issue reported from  Round ID: [136970](https://scrubby.melonmesa.com/round/136970) (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1522

Changelings cannot revive if decapitated. The player is stored in the brain and if the brain is removed they cannot revive.

**Comment by Qustinnus** [comment]
dupe issue
