### ISSUE TITLE
Potentially dynamic related problem with Check Antagonist panel

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#51083]
![dynamicrelatedbug](https://user-images.githubusercontent.com/22053757/81753172-33dc7780-9481-11ea-844f-a03b75e41e36.PNG)

Look at Living Players: It says 7 antagonists but there's really 15. Seems to only be counting the ops. Round ID 136960

**Comment by kriskog** [comment]
Check the next line
