### ISSUE TITLE
Holoparasite name during holoparasite comms is white against a white background when seen from deadchat.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#51080]
136953
![holoparaglitch](https://user-images.githubusercontent.com/22053757/81741632-dd653e00-946c-11ea-8960-b704e43b8a04.PNG)

**Comment by ArcaneDefence** [comment]
I think this also occurs when a stand is selected, spawns, picks their name and color, and then is reset and another player takes control of the stand.

**Comment by Fikou** [comment]
what was the holoparasite's color? the chat text is the same as the color of the guardian
