### ISSUE TITLE
Putting the nuclear disk into a display case makes the case invisible

### ISSUE THREAD

**Issue by spessman-007** [tgstation/tgstation#51098]
## Reproduction: Unlock captain's (or any other, probably) display case, put the nuclear disk in it, close it. 
![image](https://user-images.githubusercontent.com/62214048/81839635-7de05e80-9550-11ea-9fd2-5a91d226867a.png)
It's invisible, and not able to be examined either.

**Comment by spessman-007** [comment]
Albeit I do need to note that it can be broken.

**Comment by Tlaltecuhtli** [comment]
wow! no error sprite? why  did we merge that meme pr that broke all sprites for a week if it doesnt even do its job?

**Comment by spessman-007** [comment]
That is actually a wonderful question. @Iamgoofball

**Comment by Iamgoofball** [comment]
I didn't put it into every single dmi. I'll rectify this.

**Comment by wesoda25** [comment]
this isn't deserving of fuck up of the year

**Comment by davethwave** [comment]
The new anti nukie strategy.

**Comment by MrMelbert** [comment]
this isn't even unique to the nuke disk - put anything in the captain's display case after you open it, and it will do it. It's the same for Lamar's cage. I actually discovered this a while ago by accident
![image](https://user-images.githubusercontent.com/51863163/82376436-be742800-99e7-11ea-9c0f-01d71191402f.png)
