### ISSUE TITLE
Perpetually bloody shoes

### ISSUE THREAD

**Issue by jtroopa** [tgstation/tgstation#51103]
Issue reported from  Round ID: [137035](https://scrubby.melonmesa.com/round/137035) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507

_The blood of your heresy will stay your feet, and you shall be left behind._
It seems like certain items that can get blood on them will still have the bloody sprite on their item, despite the description saying they're clean and appearing to be clean when wearing them. I've only confirmed this with black shoes at the moment.

**Comment by ivanmixo** [comment]
Might've been a server issue, since I can't replicate it on a private server. If it happens again try reconnecting and if that doesn't work then try restarting your client.

**Comment by Donkie** [comment]
This was probably fixed in my PR #52477
