### ISSUE TITLE
Ash Drake can't be butchered

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#51102]
Issue reported from  Round ID: [137027](https://scrubby.melonmesa.com/round/137027) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

When attempting to butcher the ash drake, harm intent on, the bar will fill up and complete, but there will be no reaction. the body will stay in its spot and you can attempt to butcher over and over to no avail. the body can't be moved either.

**Comment by Cyprex** [comment]
Is this still an issue? I've seen ash drakes get butchered just fine recently

**Comment by dragomagol** [comment]
Appears to have been fixed
