### ISSUE TITLE
i have no idea how this happened

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#51111]
Issue reported from  Round ID: [137103](https://scrubby.melonmesa.com/round/137103) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517
honest
Just noticed this one while flying around
![tgStation Manuel  ENGLISH   US-WEST   ROLEPLAY   99% LAG FREE  Black Ishimura Hive Sixteen 2020-05-14 212137](https://user-images.githubusercontent.com/54288658/81977334-2b737080-962a-11ea-90f7-e3304ec6a85d.png)

**Comment by ATH1909** [comment]
yep, that's the yeet bug

didn't we fix it, though?

**Comment by Tharcoonvagh** [comment]
now you see that's the worrying part

**Comment by ArcaneMusic** [comment]
Could you elaborate?
So was it just a  ghost player that took the sprite of a circlehand, or was it just the item sitting on the ground?
The latter I feel like was fixed already, the former could still be an active issue, I just have no idea what this issue is based on the title.

**Comment by Tharcoonvagh** [comment]
Hi, I still have no idea how it happened

**Comment by dragomagol** [comment]
A little while ago ghosts could just fill the station with these, which got fixed. It's also possible for admins to spawn these which could have been the cause.

**Comment by ArcaneMusic** [comment]
Okay, so, there's no reproduction steps, the problem still isn't fully known, and from the sounds of it it may be currently fixed. Unless it comes back, closing this for now.
