### ISSUE TITLE
how to kill a man with a can (even as a pacifist)

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#51113]
1. Acquire a soda can.
2. Pop that can's lid open (use the can in hand).
3. Use a sharp object on the can.
4. Click on someone repeatedly.
5. Every click will deal 2 oxyloss damage to them, along with some losebreath, provided that the can still has reagents in it. Clicking on them enough will cause them to vomit (WITHOUT a stun, thankfully/sadly). This happens EVEN IF THEY HAVE FACIAL PROTECTION, and is in fact more effective against people with facial protection, since you won't have to move to dismiss the timers before they actually feed whatever chems you have in the can to your victim (the effect will happen after the timer either finishes or gets interrupted (or doesn't get started at all because your victim is wearing facial protection/something that'd block food/drink intake)).
6. Also, the rapid click cooldown thing that chugging a can is supposed to apply is applied to the person who's being forcefed the contents of the can, NOT the person who's actually doing the clicking. If you're, like, SUPER-coordinated with someone, you could probably use this to reset their click cooldown period(s) after they try to break out of cuffs, grab someone, spray a spray bottle, fire a gun, make a melee attack, or something. 
7. If you have a way to deal with the oxyloss and losebreath (like, say, atropine or something), you can also use this trick to rapidly purge your own chems/heal your tox damage, as you can just spam-click yourself with the can (with a rapid click speed because you're forcing yourself to chug the can, not someone else) to force yourself to rapidly vomit.
8. Pacifists can use this to kill people, by the way, although it takes ages to do so.

**Comment by msgerbs** [comment]
I was unable to reproduce this locally, and couldn't find anything in the code that would cause oxyless from soda cans. Was this already fixed?

**Comment by Fikou** [comment]
was removed
