### ISSUE TITLE
Foreigner trait blocks the book of babble from giving you galactic common.

### ISSUE THREAD

**Issue by SumFaggotPlayTester** [tgstation/tgstation#51114]
Issue reported from  Round ID: [137127] (https://scrubby.melonmesa.com/round/137127) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1524

As said having the trait foreigner seems to prevent the book of babble from giving you galactic common. I've yet to reported the bug but its simple.

1. Spawn a roundstart character with the foreign trait
2. Spawn in the book of babble & read it
3. Check language menu; you should not have galactic common unlocked

Edit
Tested this a it with TheMidnightRose & we found it works on round-start characters only. Spawning one in with the traits seems to make it work? But it is reproducible it seems with roundstart characters having the trait.

**Comment by Tharcoonvagh** [comment]
book of babble

**Comment by RaveRadbury** [comment]
This is because Galactic Common is blocked rather than removed. If I were to change it to removal then foreigner curators would still get galactic common. I suppose we could add a check to the book of babel to see if galcom is blocked and then unblock it.

**Comment by XDTM** [comment]
That'd be kind of a snowflake check. A better solution would be to block the quirk from curators in some way and handle it as removal insteal.

**Comment by kriskog** [comment]
Its due to how galcom gets blacklisted. It makes sense in some cases, not in others. Im probably reworking it somewhat, but for now the easy solution is to have the book of babel clear the mind language holders blacklist entirely.

**Comment by msgerbs** [comment]
> 
> 
> This is because Galactic Common is blocked rather than removed. If I were to change it to removal then foreigner curators would still get galactic common. I suppose we could add a check to the book of babel to see if galcom is blocked and then unblock it.

Would this not be intended though? Curators get all languages, a foreigner curator should be no different.
