### ISSUE TITLE
AI got some problems interacting with stuff.

### ISSUE THREAD

**Issue by Vanadiom** [tgstation/tgstation#51112]
## Round ID:
[137114](https://scrubby.melonmesa.com/round/137114)

## Testmerges:
#50981 
#50912 

## Reproduction:
1. Be AI.
2. Try to interact with one of the following: Holodeck console, robot controll console, camera console. (More that I cant remember.)
3. Notice that in the window the Eye is orange, as in, too far away to interact.
4. Cry as people call you Malf because you cant remove Holodeck safety.

**Comment by ATH1909** [comment]
Were they towards the right or left edges of your screen? Playing with widescreen mode on as a silicon is frustrating because you can see things that the game won't let you interact with until you move your viewpoint closer to them.

**Comment by Vanadiom** [comment]
@ATH1909 ATH1901 Center of screen, so no.

**Comment by GunHog** [comment]
Were you at any point in a mech or AI card (wireless enabled)? Also, did you ever move Z-levels? (Such as going to lavaland via shuttle or teleporter)

**Comment by Vanadiom** [comment]
@GunHog No, I only got carded later, but It was all still a problem directly after roundstart.

**Comment by stylemistake** [comment]
Got fixed by actioninja in the recent PR update.
