### ISSUE TITLE
Meat and Pizza sheets cannot be used for in-hand crafting

### ISSUE THREAD

**Issue by rdragan** [tgstation/tgstation#51119]
## Reproduction:

Meat sheets and Pizza sheets can't be used to make floor tiles or anything else using the inhand menu. Possibly others as well, I am not entirely sure which other sheets are supposed to allow this.

1. Acquire/Spawn some meat sheets
2. Use them inhand
![image](https://user-images.githubusercontent.com/43266738/82066233-cb3b0800-96d7-11ea-901d-d19cc14c0314.png)

**Comment by Qustinnus** [comment]
ugh this again
