### ISSUE TITLE
Surgery on Appendicitis is broken

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#51122]
## Testmerges:
#50981: 'Completely disables papercode' by optimumtact at commit c21fde5f17
#50558: '[REVIEW] Adds Medical Wounds: Bamboo Bones and the Skin of Your Teeth' by Ryll-Ryll at commit 4b836d6450

## Reproduction:
1. Get patient with Appendicitis
2. lay him naked on operation table
3. target groin
4. Drapes > organ manipualtion
5. Scalpel you making incision and nothing happens
You begin to make an incision in Romayne Goebbles's groin...
Blood pools around the incision in Romayne Goebbles's groin.
You begin to make an incision in Romayne Goebbles's groin...
Blood pools around the incision in Romayne Goebbles's groin.

operating computer says make incision and then it stop responding for me
and yeh i blame
#50558: '[REVIEW] Adds Medical Wounds: Bamboo Bones and the Skin of Your Teeth' by Ryll-Ryll at commit 4b836d6450
And its bad

**Comment by Ryll-Ryll** [comment]
Yep this one's mine, fixed in the latest commit of wounds
