### ISSUE TITLE
Low bodytemp can burn off clothes

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#51129]
## Round ID(s):

- [137202](https://scrubby.melonmesa.com/round/137202)
- [137219](https://scrubby.melonmesa.com/round/137219)

## Testmerges:

- #50981
- #50558 (@Ryll-Ryll I think this is yours)

## Reproduction:

- Round 1:
  1. Pick lizard as your starting species
  2. Latejoin as an assistant
  3. Put on an emergency firesuit because someone is plasmaflooding
  4. Head to escape
  5. Start to die because you are cold for some reason (possible breach?)
  6. Take extra damage because you are a lizard.
  7. Get the chest burnt off of your emergency firesuit because you are taking tons of burn damage... from low bodytemperature... as a lizard
  8. Server crash (probably not related)
- Round 2: 137219
  1. Spawn as lizard.
  2. Get thrown out an airlock.
  3, Die.
  4. As a ghost, watch the jumpsuit disintegrate off of your body because you are a exposed to space and a lizard.

## Expected behavior
 
I expected that my clothes would not "burn up" because I was slightly chilly.

**Comment by msgerbs** [comment]
I was unable to reproduce this no matter how I tried. @TemporalOroboros can you reproduce this again?

Also I am terrible sorry to the emergency firesuit, I have terribly underestimated how insanely durable and protective this thing is.

**Comment by TemporalOroboros** [comment]
I think this is fixed, I spent a while floating around space as a lizard on the latest version and couldn't reproduce this.
