### ISSUE TITLE
Inorganic Biology Virus Not Working 

### ISSUE THREAD

**Issue by Shikarego** [tgstation/tgstation#51128]
Issue reported from  Round ID: [137199](https://scrubby.melonmesa.com/round/137199) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517

This time IB was the last symptom I got, but it overrode one of my others. So I made a culture and added a drop from the old culture to get all 6 symptoms on there. The resulting virus was unable to infect anything. It worked when I replaced IB with sneezing.
I was human.

**Comment by LemonInTheDark** [comment]
I have been in this place before, flying down the street~

**Comment by nemvar** [comment]
Could not reproduce.
