### ISSUE TITLE
Ghosts can toggle gas injectors, filters, pumps, etc.

### ISSUE THREAD

**Issue by wayland-ss13** [tgstation/tgstation#51123]
## Round ID:
[137176](https://scrubby.melonmesa.com/round/137176)

## Testmerges:
#50981 #50558 

## Reproduction:
Control-Click on any injector to toggle its state. Confirmed it myself on Box see gif below.
![example gif](https://i.imgur.com/htfLclv.gif)

Credit to ckey: Thonk for pointing this out.

**Comment by ShibaInuLord** [comment]
this also happens with gas filters, tested on meta.

**Comment by LemonInTheDark** [comment]
GOD DAMNNIT AHHHHHHHHHHHHHHHHHH
Someone add a check for dead

**Comment by kriskog** [comment]
Guessing #50356 caused it

**Comment by ATH1909** [comment]
oh god oh fuck

~~how do I use this to kill people~~

**Comment by wayland-ss13** [comment]
> Guessing #50356 caused it

Yep. Add cryo cells power to the list.

**Comment by qwertyquerty** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/1819

**Comment by kriskog** [comment]
@qwertyquerty thanks, you guys may wanna add logging as well. See #51148
