### ISSUE TITLE
tgui: Fridge BSOD on accessing length on null

### ISSUE THREAD

**Issue by Vanadiom** [tgstation/tgstation#51126]
![Screenshot (155)](https://user-images.githubusercontent.com/55851108/82101964-47e8d900-970e-11ea-80b6-cf78b7f95fda.png)
(length value of NULL something, tech stuff)

## Round ID:
[137188](https://scrubby.melonmesa.com/round/137188)

## Testmerges:
#50912 
#50981 

## Reproduction:
1. Go to fridge.
2. Open fridge.
3. Go away from fridge.
4. Get a beautiful bluescreen that I kinda wanna keep.
5. You can no longer interact with fridge.

**Comment by ArcaneMusic** [comment]
Considering that this was a testmerge bug, and for a testmerge that didn't wind up being full merged, this feels appropriate to close. If I'm totally wrong, feel free to let me know and I can re-open this.
