### ISSUE TITLE
Most plant grafts runtime and don't work

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#51133]
Tested locally after noticing most grafts didn't work. 

#### Runtime 1:
- Graft any tomato plant. I use bluespace tomato here. 
- Use plant analyzer on it. Nothing happens in game. 

Result: 
`[13:14:02] Runtime in grafts.dm,55: Cannot execute /datum/plant_gene/trait/telepo... (/datum/plant_gene/trait/teleport).get name().
  usr: Angust/(Mouth Words)
  usr.loc: (Hydroponics (102, 143, 2))`

#### Runtime 2:
- Use the above plant graft on another plant. 

Result: 
![200516 1321 41](https://user-images.githubusercontent.com/46400996/82118525-45bb6480-9778-11ea-8ae6-b813f74fdc6d.png)

and

`[13:16:28] Runtime in seeds.dm,594: Cannot execute /datum/plant_gene/trait/telepo... (/datum/plant_gene/trait/teleport).can add().
  usr: Angust/(Mouth Words)
  usr.loc: (Hydroponics (102, 142, 2))`

I can't reproduce with grafts from any ambrosia species, but tomato and red-beet grafts stay broken. It doesn't seem to matter if the original grafted plant still exists or not.

**Comment by ArcaneMusic** [comment]
Should have been fixed by 51133 as far as I've noticed.
