### ISSUE TITLE
Zombie never revived.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#51130]
## Testmerges:

- #50981
- #50558

## Reproduction:

1. Get infected and killed by a zombie
2. Rez
3. Get critted and get thrown out of an airlock because zombie
  - Get whacked in the head a couple times, but not decapitated because you're in maint below robotics and the departures airlocks are _right there_.
4. Succumb because you are in a zombie, in crit, in space
5. Ghost by using arrow keys to move out of your body
6. Never rez, even though you waited 5+ minutes (at minimum the entire red-alert shuttle call).
7. Ghost health scan your body and notice that the romerol tumor isn't showing up and probably disappeared somewhere between steps 2 and 6.

**Comment by Time-Green** [comment]
That’s not how zombies work. They don’t die and revive, rather they cannot die at all and simply slowly regenerate. When you succumbed in crit you overwrote the “cant die” part and ended the zombie cycle

**Comment by TemporalOroboros** [comment]
Alright, I guess I thought it worked like an automatic ling stasis, since when you die the first time (when you turn into a zombie) is revives you.

**Comment by Time-Green** [comment]
I think it used to, but it got changed a while back

**Comment by HomocidlePancakes** [comment]
Dupe

**Comment by HomocidlePancakes** [comment]
#49678

**Comment by msgerbs** [comment]
Sounds like this is intended then? Can we close this?

**Comment by TheBonded** [comment]
> Sounds like this is intended then? Can we close this?

better late than never, I guess?
