### ISSUE TITLE
tgui: Security Camera Console is blank for all available cameras

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/tgstation#51131]
![image](https://user-images.githubusercontent.com/24631139/82115222-13b7fb80-9794-11ea-88e9-925602484d34.png)
All cameras i check on are all blank

**Comment by stylemistake** [comment]
Tgui has to allow ByondUi on IE10 or later.

**Comment by merklaw** [comment]
tgstation now requires IE11 or later

**Comment by stylemistake** [comment]
Fixed (i hope) in #52085
