### ISSUE TITLE
Cannot perform prosthetic replacement surgery

### ISSUE THREAD

**Issue by IanAbstract** [tgstation/tgstation#51137]
Issue reported from  Round ID: [137255](https://scrubby.melonmesa.com/round/137255) (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1522

After performing the incision step of prosthetic replacement, the surgery does not progress, stuck on that stage.

**Comment by Ryll-Ryll** [comment]
Same as #51122, fix is up

**Comment by Robustitron** [comment]
This also applied to limb reattachment

A lizard doctor spent ages trying to denugget me after a meth accident
