### ISSUE TITLE
breathing plasma doesnt flash the tox alert 

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#51138]
breathe in any amount plasma
wonder why you are taking damage as there is no tox alert flashing

**Comment by wesoda25** [comment]
I believe this is fixed. 
![dreamseeker_tXxhcwBYKw](https://user-images.githubusercontent.com/37246588/130305630-b0b12ca1-1776-4b26-9dd1-d7153ee4db92.png)

**Comment by jlsnow301** [comment]
closing this due to lack of interaction & inability to reproduce locally
![Screenshot 2021-12-28 212807](https://user-images.githubusercontent.com/42397676/147630207-56e90639-531d-465b-a632-2dae6bcc8291.png)
