### ISSUE TITLE
Novaflowers and deathnettles are broken.

### ISSUE THREAD

**Issue by Krysonism** [tgstation/tgstation#51143]
## Round ID:
Tested on live & local

## Reproduction:
Hit someone with a novaflower or deathnettle, be surprised when they don't get lit on fire / get blurry eyes like intended.

![image](https://user-images.githubusercontent.com/49783092/82147071-846f1e80-984d-11ea-9f08-d79217f97d99.png)

I think this super call might not return the correct value.

**Comment by timothymtorres** [comment]
Holy shit this issue is cursed.  4 PRs tried to fix this and none of them succeeded.

**Comment by MrMelbert** [comment]
fixed by #59107
