### ISSUE TITLE
KA, flashlight, knife

### ISSUE THREAD

**Issue by Ikoden** [tgstation/tgstation#51145]
This may be intended, but I kinda cannot make sense why. When you put knife on KA you can put flashlight, when you put flashlight first, then try to knife you can't. Kinda stupid.

**Comment by HomocidlePancakes** [comment]
Help intent. You need to be on help intent to put a knife on to a KA.

**Comment by Ikoden** [comment]
Yup. That works. Thanks mate.

**Comment by nemvar** [comment]
Guess this is resolved.
