### ISSUE TITLE
Surgery bug

### ISSUE THREAD

**Issue by Zenog400** [tgstation/tgstation#51140]
Issue reported from  Round ID: [137271](https://scrubby.melonmesa.com/round/137271) (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1507

Prosthetic replacement surgery is trapped on the "make an incision" step.

**Comment by Ryll-Ryll** [comment]
Same as #51122, fix is up
