### ISSUE TITLE
tgui dump

### ISSUE THREAD

**Issue by joybod** [tgstation/tgstation#51141]
i was told to report this stack trace
Error: Failed to suspend 'tgui-window-116'.
   at Anonymous function (http://127.0.0.1:65056/tmp24840/tgui.bundle.js:1:3044)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
Issue reported from  Round ID: [137280](https://scrubby.melonmesa.com/round/137280) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

**Comment by stylemistake** [comment]
PR was updated to no longer emit this error, manuel needs updating to the latest version.
