### ISSUE TITLE
pAI Loudness Booster does not work.

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#51151]
## Round ID:
[137360](https://scrubby.melonmesa.com/round/137360)

## Testmerges:
#51148: 'Fix ghosts alt/ctrl clicking atmos devices' by TetraK1 at commit 4dc245c054
#51071: 'Midrounds and latejoin rulesets now pre-execute' by kriskog at commit 0f2a994ffa
#50981: 'Completely disables papercode' by optimumtact at commit c21fde5f17
#50558: '[REVIEW] Adds Medical Wounds: Bamboo Bones and the Skin of Your Teeth' by Ryll-Ryll at commit 92ccf5e84e

## Reproduction:
be a pAI, download loudness booster app, click open synthesizer interface, nothing happens.

**Comment by uomo91** [comment]
Spam click it a few times and it should pop up.
Probably not going to see this one fixed until somebody does pAI TGUI.

**Comment by Zytolg** [comment]
Round ID: 155860 as well.

Fold up into PAI Padd, play some music until the TGUI interface freezes up.
Apparently this breaks the synth serverwide too, which is more alarming.
![Broke the Synthesizer Server Wide](https://user-images.githubusercontent.com/33048583/107139248-079e3c00-68d7-11eb-99ca-24e8fb130fe4.PNG)



To fix, redeploy your holochassis and it should open up again. That's what did it for me. 
(And then it proceeded to not work again but re-toggling the holochassis seemed to fix that)
