### ISSUE TITLE
Fat Speed Debuff is delayed

### ISSUE THREAD

**Issue by SkeletalElite** [tgstation/tgstation#51158]
Eat some food and get fat, walk around for a while without the debuff even though you're fat until it eventually kicks in. Then once you are no longer fat, it once again takes a long time for your speed to return to normal as the debuff will stay for some time after no longer being fat.

**Comment by HomocidlePancakes** [comment]
Seems intentional. It even sends a message in chat once the debuff kicks in/out.

**Comment by timothymtorres** [comment]
Marking this as not a bug and it will auto close the issue in 7 days.
