### ISSUE TITLE
meteor shuttle on delta is rotated? 

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#51166]
137442

shuttle is supposed to have this console EAST instead it was facing NORTH and was impossible to enter
![shuttle bug](https://user-images.githubusercontent.com/33834933/82298550-93bcac00-99b4-11ea-862f-fe93874e3b4e.png)

**Comment by kriskog** [comment]
Landed backwards on CC after a pubby round yesterday, which had the entrance correctly placed for pubby where departures is on the west side. It also did not leave station during transit, and only moved once the journey was over.
