### ISSUE TITLE
When both blind and nearsighted, player should spawn with a blindfold and not glasses

### ISSUE THREAD

**Issue by nwarz** [tgstation/tgstation#51165]
Issue reported from  Round ID: [137436](https://scrubby.melonmesa.com/round/137436) (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1512

Like it says in the title, when a player starts with both the blind and nearsighted quirks, they spawn with a pair of prescription glasses. They should start with a blindfold instead since blindness is the more disabling effect.

**Comment by Tlaltecuhtli** [comment]
you shouldnt have both in the first place

**Comment by nwarz** [comment]
I started the round with both quirks with a Hardcore Random character

**Comment by Pugie** [comment]
Go Stevie Wonder and give them sunglasses all sides are happy

**Comment by Trumpetplaya288** [comment]
blind people tend to have some residual sight
maybe make this combo make your screen completely black

**Comment by Cyberboss** [comment]
![image](https://user-images.githubusercontent.com/8171642/130360405-2fdaf17a-b9dd-4f57-9666-64f4f2d7da52.png)
