### ISSUE TITLE
chem acclimator could be optimized a bit

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#51167]
it doesnt stop heating after it reaches the "acceptable temp level" so it keeps heating while emptying which can cause random explosions even if you set it to eject at an acceptable temp level lower than the explosion temp

**Comment by TemporalOroboros** [comment]
I think it's intended to heat all the way up to the target temperature and just start emptying within the acceptable temperature range. If it's heating past the target temperature I'm pretty sure that's no intended.

**Comment by MacBlaze1** [comment]
stop posting suggestions

**Comment by MacBlaze1** [comment]
wait no Im retarded please format properly
