### ISSUE TITLE
A consistent way to access the Wishgranter

### ISSUE THREAD

**Issue by Drackzo** [tgstation/tgstation#51161]
![hack](https://user-images.githubusercontent.com/65568464/82257793-9a193c80-9950-11ea-8d1d-efce785a0037.png)

Reproduction: If you use a bluespace shelter capsule next to the Wishgranter Cube, it replaces the impossible to break walls with easy to break capsule walls. One can easily just break into the wishgranter from there by deconstructing one of the walls as demonstrated in the attached png. Bear in mind this was on Fulpstation so I don't know if it's been fixed or is due to the minor differences between tg Fulpcode.

**Comment by Drackzo** [comment]
It also was on the new Fulp specific map so again, unsure if it's a problem with tg as a whole, I'll test it out when I can.

**Comment by ATH1909** [comment]
wew

**Comment by Drackzo** [comment]
Tested it privately using TG code from a week ago and it worked thus I assume it works in the up to date version too.

**Comment by necromanceranne** [comment]
Thank goodness this is disabled in the config.

**Comment by GravitronBlue** [comment]
> Thank goodness this is disabled in the config.

Unfortunately a certain wizard den isn't so lucky against this kind of cheese, expect another issue report about this kind of cheese later.
