### ISSUE TITLE
Can't put items inside a medical belt when medical belt is inside a container.

### ISSUE THREAD

**Issue by Pugie** [tgstation/tgstation#51169]
What it says on the tin, this has been an issue for a while and makes medical belts really unintuitive to use when there is something else in your belt slot like a biobag & you want surgical tools in your belt.
Probably broken due to #46983

**Comment by Angustmeta** [comment]
Same with janibelts.

**Comment by ATH1909** [comment]
I can confirm that this happens to me with medibelts. Note that this DOESN'T happen with toolbelts.

**Comment by ATH1909** [comment]
Is this a side-effect of that PR that removed the ability of smuggler's satchels to go recursive/infinite?

**Comment by ArcaneDefence** [comment]
Failed to reproduce, was probably addressed and not linked in the PR.
