### ISSUE TITLE
You can weld using just shades.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#51173]
I'm not sure if there is a consistency thing happening here, but so long as you have any flash protection at all, you seemingly can weld using any kind of welder. 

You don't need a welder mask, and you don't need an experimental welder. Just get a welder, start welding.

This works specifically for welding a wall, and I found from welding glass.

**Comment by Pugie** [comment]
it's not just that it's to do with brightness protection in general -> you can have thermal vision and sunglasses and be flashproof for example.

**Comment by nemvar** [comment]
Thermal vision itself doesn't counteract flash protection but you are supposed to have at least two levels of flash protection to be safe when welding.

**Comment by ATH1909** [comment]
> Thermal vision itself doesn't counteract flash protection but you are supposed to have at least two levels of flash protection to be safe when welding.

As a moth main, I humbly request that you do NOT increase that required number of levels of flash protection to 2 levels, as that will make us burn our eyes out while welding WITH WELDING PROTECTION (as in, a proper welding helmet or something), as -1+2=1<2. In order to weld safely, we would have to completely blind ourselves or get our eyes entirely replaced.

**Comment by Fikou** [comment]
it does flash you once though, shades prevent continuous flashing from welding a wall but the first flash is still there

**Comment by necromanceranne** [comment]
Not even that. It doesn't even do eye damage.

**Comment by HomocidlePancakes** [comment]
Sunglasses always gave welding protection. What are you on about? Why the fuck is it labeled as a bug? You would just get the same amount of damage as a flash would do.

**Comment by JohnFulpWillard** [comment]
im gonna close this as not planned, if someone wants to open a balance pr that's fine but i dont consider it a problem.
