### ISSUE TITLE
no back sprite for singlo hammer

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#51178]
it doesnt even show the error black and pink sprite, was the whole point of the error sprite to show invisible things? why did it work for things that had sprites but not on things that dont have sprites?

**Comment by ArcaneMusic** [comment]
Backsprites for the singlo hammer were added in this PR: #53305
![image](https://user-images.githubusercontent.com/41715314/97795688-6d47a180-1bdf-11eb-8f8a-75220ce6e57b.png)
