### ISSUE TITLE
Lighting no longer updates properly

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#51188]
Ever since: https://github.com/tgstation/tgstation/pull/51004

Lighting no longer updates properly when entering new areas or opening/closing doors.

Noticed this over at Paradise when we ported the lighting performance improvements (Our lighting systems are identical).

Here's how lighting should work:

![img](https://i.gyazo.com/de6de33db30526d903383e35eff09764.gif)

Here's how it's working after the update: 

![img](https://i.gyazo.com/8cdcc79b824e10df94a98fb9c0b6e391.gif)

This is the same on TG as well:

![img](https://i.gyazo.com/caff96d75a186eb9a7e7d7266b4e29d6.gif)

**Comment by LemonInTheDark** [comment]
issue, not a new one tho. This is due to us running out of time, and being unable to process the lighting ss

**Comment by Fox-McCloud** [comment]
The above was done with a single client connected to the server with everything more or less at idle.

It has nothing to do with the tick overrunning or the SS pausing as there's *barely* load on the  controller (or any of them!)

You can revert the changes made in the aforementioned PR linked above and you'll see that the light will update when the door opens; apply the changes and you're suddenly left with lights that refuse to update again.

**Comment by LemonInTheDark** [comment]
ahhhhhhhh hell

**Comment by Dorsisdwarf** [comment]
good work hahaha

**Comment by AnturK** [comment]
From quick glance what changes is turfs with opaque atoms don't get added to affected turfs, but don't see exactly how that causes the above issue. @vuonojenmustaturska
