### ISSUE TITLE
Nukes don't play well with instant explosions.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#51191]
Freezes everything for a solid 10-15 seconds. Reboots seem to take longer after a nuking as well.

**Comment by Dorsisdwarf** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
What did you expect? I can make maxcaps instant but blowing up every station tile is hardly viable.

**Comment by Iamgoofball** [comment]
Reboot isn't related though.

**Comment by BeeSting12** [comment]
I expect nuke to not freeze the server. If they're not compatible with instant explosions then they should be reworked to kill everyone on the z-level or something idunno.

**Comment by BeeSting12** [comment]
The reboot is anecdotal, I didn't time it or anything but I'm pretty sure it takes longer and seems to coincide with the nuke going off.

**Comment by Iamgoofball** [comment]
I'll adjust how the nuke works.

**Comment by TemporalOroboros** [comment]
Just make it act like the rolling wave of death it used to be so it's blowing up only part of the station z-level at a time instead of the whole thing.

**Comment by Iamgoofball** [comment]
@TemporalOroboros The rolling death wave was because the explosion took 5 minutes to process in full.
