### ISSUE TITLE
Cables and Disposal tubes (and probably most other things) burn even with a floor over them

### ISSUE THREAD

**Issue by Ghilker** [tgstation/tgstation#51195]
## Reproduction:
Go to the incinerator, start a fire, get power for less than 30 seconds, wire burns down even under the reinforced floor

It could be related to the fire_act proc changes

**Comment by Time-Green** [comment]
May have something to do with #49644, tile hiding was reworked there and immunities from above tile exposure may have been cucked

**Comment by Ghilker** [comment]
Oh yeah could be that

**Comment by LemonInTheDark** [comment]
Time I'm having a heart attack why did you remove all the layer checks
