### ISSUE TITLE
Botany creates a ghost plant that can be harvested infinitely but has no stats - causing runtimes

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#51193]
## Round ID:
[137567](https://scrubby.melonmesa.com/round/137567)

## Testmerges:
#50981, #50963, #50912, #51148

## Information:
I'm not sure how the other botanist achieved this, but they created a plant that could be harvested a presumably infinite amount of times without needing to reset (yes I know perennial growth exists - the plants never reset after being harvested, no growth period). So, one could create as many plants as they could click with no time in between them. 

These plants that were harvested had no stats or chemical contents, and couldn't be turned into new seeds.

In the logged runtimes, there appears to be runtimes thrown by the Blumpkin Vines's harvest and copy procs. 

![image](https://user-images.githubusercontent.com/51863163/82508154-cf956580-9ac9-11ea-95f4-fcba7fba371c.png)

**Comment by ArcaneMusic** [comment]
This should be fixed by 51257 as far as I can see.
