### ISSUE TITLE
License Plate Presses Accept multiple blank plates but only ever print one completed License Plate

### ISSUE THREAD

**Issue by ThePyroTechnician** [tgstation/tgstation#51201]
Issue reported from  Round ID: [137642](https://scrubby.melonmesa.com/round/137642) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

Title says it all really. I put two or more blank plates into the press, the game lets me do thus, but no matter how many plates are in there only one completed plate is made. This could be fixed in two ways:
Either allow the presses to work up to a stack at a time, and output the correct number of plates, or
Make it so that the plate press only accepts one plate at a time and no more.
First issue report tell me if I fucked up somehow.

**Comment by Qustinnus** [comment]
oh yeah i still had to fix this
