### ISSUE TITLE
you can point gun at visible ghosts

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#51210]
aim mouth with grab intent or whatver does trigger it to a visible ghost with gun

find out it glitches so u cant do the thing anymore because it says " you are already pointing at someone else"

**Comment by ATH1909** [comment]
wew

**Comment by wayland-ss13** [comment]
Can confirm being able to hold-up ghosts, but it never becomes steady, and unless you stay in range every movement spews: _You are no longer pointing the [wielded gun] at [target ghost]_.

**Comment by MacBlaze1** [comment]
not following format
