### ISSUE TITLE
Revenant poltergeists

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#51214]
Round ID:[137713](https://scrubby.melonmesa.com/round/137713) I think

Testmerges: Don't really matter concerning the issue, it's been here for a while

Reproduction: Be revenant, empty box by dragging them onto the floor. Drag person into locker/crate to stuff people into locker/crate. Buckle people to chairs and borgs. Be the spooky ghost you are meant to be.

**Comment by ATH1909** [comment]
feature

**Comment by Sealed101** [comment]
this was fixed at some point in time by an unknown agent of virtue
