### ISSUE TITLE
Lavaland Mobs Attacking Same Faction Mobs.

### ISSUE THREAD

**Issue by tgsAvylaar** [tgstation/tgstation#51227]
Round ID: [137782](https://scrubby.melonmesa.com/round/137782)
Round ID: [137785]

During a routine hiero fight, it teleported away outside of the arena to kill a bunch of minor fauna. 
On the picture, you can see it killing a tendril + watchers.
Only when everything else was dead, and it aggro'd a drake, did I manage to regain aggression.

I've had this happen multiple times now.

![dreamseeker_BqUfMa1uRa](https://user-images.githubusercontent.com/63151598/82734363-de268b80-9d1a-11ea-91cd-817ab426324a.png)

Here you have goats attacking eachother, and even a mindless dead npc.
![dreamseeker_q6pLHCKF9O](https://user-images.githubusercontent.com/63151598/82744043-a0a21c80-9d73-11ea-82b7-667389c3c1e5.png)

![dreamseeker_oNIdY6l9oj](https://user-images.githubusercontent.com/63151598/82744033-8ff1a680-9d73-11ea-8f15-53325e391ba8.png)

**Comment by MacBlaze1** [comment]
faction = list("boss") //asteroid mobs? get that shit out of my beautiful square house
PogU?

**Comment by MacBlaze1** [comment]
This is probably an oversight
