### ISSUE TITLE
AI blood

### ISSUE THREAD

**Issue by trerri** [tgstation/tgstation#51223]
Issue reported from  Round ID: [137750](https://scrubby.melonmesa.com/round/137750) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1520

Hitting an AI core generates blood decals on mobs and objects

**Comment by HomocidlePancakes** [comment]
Same with silicons, but it does show up us “oil” iirc on the det scanner

**Comment by dragomagol** [comment]
Doesn't appear to bleed or produce oil anymore.
