### ISSUE TITLE
turbine will burn wires

### ISSUE THREAD

**Issue by Crosoak** [tgstation/tgstation#51228]
## Reproduction:
1. set up turbine
2. wires under turbine chamber's reinforced tiles leading to SMES will burn off
3. smes wont be charged due to broken wires

**Comment by nemvar** [comment]
State of the art design from certified NT engineers.

**Comment by nemvar** [comment]
Please say which map you are talking about, I'm not going to check them all.

**Comment by spookydonut** [comment]
dupe of #51195
