### ISSUE TITLE
Can't examine yourself for injuries/traits/etc. by clicking with help intent when handcuffed

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#51235]
It doesn't require the use of your hands.

Issue reported from  Round ID: [137817](https://scrubby.melonmesa.com/round/137817) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1513

**Comment by MacBlaze1** [comment]
follow the format please
