### ISSUE TITLE
Slamed and hited

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#51233]
>You're slamed by x with such inhuman strength that it sends you flying backwards!

>You're hited by x with such inhuman strength that it sends you flying backwards!

Couldn't find where these verbs are in the code with the GitHub search but they're spelled dumb

**Comment by willox** [comment]
It's from code like this which just adds "ed" to the end of a verb.

Potential verbs: "punch", "smash", "crack"
https://github.com/tgstation/tgstation/blob/c850cfe167e4b3c6437292c0129845cfaae57d84/code/datums/martial/mushpunch.dm#L13-L15



Potential verbs: "kick", "hit", "slam"
https://github.com/tgstation/tgstation/blob/c850cfe167e4b3c6437292c0129845cfaae57d84/code/datums/martial/psychotic_brawl.dm#L58

**Comment by spessbandit** [comment]
there is the lazy way and the real but maybe overkill way to fix this, the lazy way is to just pick non-irregular verbs, the real way is to implement or port a parser

**Comment by cacogen** [comment]
probably only i care
