### ISSUE TITLE
Severed head death messages are all fucked up

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#51237]
Issue reported from  Round ID: [137873](https://scrubby.melonmesa.com/round/137873) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1522

The death messages are all fucked up for severed heads, so they don't accurately report if the soul is still online or in the head. I look at my own severed head as a ghost and see the "muscles twitching" message, but from inside the head I see "it's completely lifeless".

**Comment by Sealed101** [comment]
can no longer reproduce; #79687 may have shuffled enough code around to make the checks work more reliably
https://github.com/tgstation/tgstation/blob/9849ce19534d28d2aea8813866b87f507a40c1e0/code/modules/surgery/bodyparts/head.dm#L111-L138
