### ISSUE TITLE
AIs have no way of interacting with the mining outpost or the gulag

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#51242]
Issue reported from  Round ID: [137888](https://scrubby.melonmesa.com/round/137888) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517

You can't jump to the cameras, and since the cam console change you can't just select one then hotkey a spot either

**Comment by nemvar** [comment]
This is intentional.

**Comment by redguy999** [comment]
fun fact, you can jump to the "mine" cam network by using the "jump to network" command under AI commands
\
