### ISSUE TITLE
borgs cannot make doors

### ISSUE THREAD

**Issue by trerri** [tgstation/tgstation#51241]
Issue reported from  Round ID: [137880](https://scrubby.melonmesa.com/round/137880) (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 513.1520

Electroadaptive pseudocircuit does not work

**Comment by Archanial** [comment]
It never worked

**Comment by wayland-ss13** [comment]
> It never worked

Is it a Bug or a Feature though?


also:
![borg](https://user-images.githubusercontent.com/64715958/82761216-e085f580-9dad-11ea-825e-24d031e478e2.gif)

**Comment by MacBlaze1** [comment]
It doesnt make doors, issue jannies please close

**Comment by zxaber** [comment]
Pseudo circuit has never been used for airlocks. Use the RCD on airlock mode.

Pseudo circuit is used for air alarms and APCs.

**Comment by MacBlaze1** [comment]
not a bug, intended behavior
