### ISSUE TITLE
Wizard den can be escaped from with shelter capsules

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#51256]
Title, mining shelter capsules can be brought to the wiz den and used to clear hyperspace tiles.

### Round ID: Not available. Local testing and confirmation done on the latest version of TG.
(Remember what I said about FUN?)

### Reproduction:

- Roll wizard.
- Buy a robeless spell apprentice (knock + fireball).
- Buy instant summons.
- Mark a small object and give it to your apprentice, have them  warp down to the mining lockers and open them with the knock spell
- Return them by having the apprentice drop the summon marked item in a locker, then also getting in the locker, when the recall spell is used it'll grab the whole locker with everything in it brought to you.
- Refund summon item and buy jaunt along with lesser summon guns or arcane barrage.
- Now with a shelter capsule use the magic mirror to turn yourself into an android (or any race that doesn't need air or pressure, but can still wear robes) and head to the south side of the den.
- Cast summon guns/barrage and fire at **all** the windows and engine parts until they're destroyed. 
- With the shelter capsule in hand, jaunt, then activate it and drop it during your jaunt on the space tiles where the den thrusters were. (Somehow the capsule drops outside your jaunt container)
![FREEWIZ2](https://user-images.githubusercontent.com/17460297/82766777-8b120e80-9dd6-11ea-8220-c317820295da.png)
- Use mutate spell's hulk to smash the capsule open.
- Reach ~~FREEDOM~~ the Badmin target test dummy firing range.

Slightly simliar to #51161 due to how shelter capsules are overriding indestructible wall turfs in cases they really shouldn't.

EDIT: This could have potential for nuke-ops if they brought one back, further testing should be done to check if this works from inside the syndicate base.

> I find recalling apprentices back to the station using instant summons to be a feature, not a bug.

"I find it FUN."

**Comment by LemonInTheDark** [comment]
Not again

**Comment by Fikou** [comment]
#48823 caused mining pods to override from not being able to be placed on closed turfs to just not be able to be placed on indestructible floors, causing all these fuckups

**Comment by ATH1909** [comment]
the king goat PR caused this?

holy shit wew

**Comment by Fikou** [comment]
what didnt it cause

**Comment by GravitronBlue** [comment]
Might still be worth making sure shelter capsules can't be used in the den, as there's enough room in the middle for one to deploy and that can change the area type, resulting in the use of spells that shouldn't be usable in the den.

**Comment by MacBlaze1** [comment]
Nice

**Comment by ATH1909** [comment]
> Might still be worth making sure shelter capsules can't be used in the den, as there's enough room in the middle for one to deploy and that can change the area type, resulting in the use of spells that shouldn't be usable in the den.
> 
> Should also evaluate whether recalling stuff back to the den should be viable, as there's almost no limitation to what can be brought back. (Currently thinking of xenobio machines and making slimes via staff of change to extract end-tier xenobiology cores.)

dude, if a wizard makes a fully-functional xenobio setup on his ship, let him use whatever xenobio core gimmick he has planned, he fuckin' earned it.

**Comment by TheVekter** [comment]
how the fuck does this keep happening

**Comment by BeeSting12** [comment]
Should just make shelter capsules unusable on the centcomm zlevel.

**Comment by Fikou** [comment]
should just remove king goat

**Comment by Shadowflame909** [comment]
is it possible to escape from the nukie z-level with a blue space capsule?

Might be even easier considering how much going forth and back they can do with the shuttle.
