### ISSUE TITLE
The latejoin/observe button is literally gone

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#51259]
## Reproduction:

Join the server.

That's it. You literally can't play your stuck in the lobby. That's the entire bug.

**Comment by Ryll-Ryll** [comment]
[2020-05-25 00:43:31.506] runtime error: Cannot execute null.resetToDefault().
 - proc name: Login (/mob/Login)
 -   source file: login.dm,77
 -   usr: (src)
 -   src: Someone12341 (/mob/dead/new_player)
 -   src.loc: the plating (8,174,1) (/turf/open/floor/plating)
 -   call stack:
 - ckey(/mob/dead/new_player): Login()
 - ckey(/mob/dead/new_player): Login()
 - ckey(/mob/dead/new_player): Login()

**Comment by LemonInTheDark** [comment]
TFW you do creation in client.new and assume that means client will always have it

**Comment by kriskog** [comment]
Its fixed
