### ISSUE TITLE
Space dragons can rift outside the station on ice box

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#51254]
## Round ID:
#137916

## Testmerges:
#51148: 'Fix ghosts alt/ctrl clicking atmos devices' by TetraK1 at commit 830e6e937a
#50963: 'Ports stat browser pane' by actioninja at commit 901b3dd491
#50981: 'Completely disables papercode' by optimumtact at commit c21fde5f17

## Reproduction:
Refer to title, they can place their rift outside the station; it won't give an actual location name either.

![Capture2](https://user-images.githubusercontent.com/32374784/82764806-834a6e00-9dc6-11ea-8fc1-f10b14eb486c.PNG)
![Capture](https://user-images.githubusercontent.com/32374784/82764807-85acc800-9dc6-11ea-973b-34f8d4446209.PNG)

**Comment by Sealed101** [comment]
#75607 made it so such areas won't be a rift target
