### ISSUE TITLE
Limb grower accepts bad hrefs when selecting category

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#51261]
Title, the limbgrower can accept non-standard href inputs, resulting in FUN potential.

### Reproduction:

- Build or find a limb grower (maybe some stations have one in medical)
- Open the interface
- Replace `category=human;menu=2` with `category=` `payload`
- Release a level FUN biohazard aboard the station, or just browse spesswebs.
![LimbgrowerFUN](https://user-images.githubusercontent.com/17460297/82771277-5743e280-9df0-11ea-938d-5f1743ce4a54.PNG)

Edit: I forgot and shoud've specified that these are unsanitized hrefs which can be delivered to whoever checks the menu.

>Every bored local assistant shift

**Comment by ATH1909** [comment]
nice

**Comment by msgerbs** [comment]
Why has nobody looked at this yet? Guess I'll figure out how to do input sanitizing next.

**Comment by msgerbs** [comment]
Weird, this didn't autoclose.
