### ISSUE TITLE
Plumbing glitch

### ISSUE THREAD

**Issue by bluejack1** [tgstation/tgstation#51272]
Issue reported from  Round ID: [137950](https://scrubby.melonmesa.com/round/137950) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1511

This happens quite often. If you unwrench a mixer it will sometimes stop filling when you attach it back and the sorrounding pipes remain blocked as if it was still secured. Only way to fix it is removing both the pipes and the mixing chamber and replacing them down. Also sometimes the mixer just stops working and doesnt fill for some reason. It's annoying and costs both time and resources

**Comment by Time-Green** [comment]
Cannot reproduce. 

I've tried two set-ups with chemical acclimators and kept constantly wrenching and unwrenching during both filling and emptying.

Could you describe what you did to step-by-step?

**Comment by bluejack1** [comment]
> Cannot reproduce.
> 
> I've tried two set-ups with chemical acclimators and kept constantly wrenching and unwrenching during both filling and emptying.
> 
> Could you describe what you did to step-by-step?

You couldn't replicate it because it happens with mixing chambers not acclimators. Mixing chamber is probably not the right term, but by that I mean the stucture that mixes reagents, not the one that heats or cools them.  I was just working on it but the reason I think this happens is the chamber only partially filling up but having one reagent missing, then being unwrenched. What happens is that the pipes around like if it wasn't unsecured and also from now on a mixing chamber in that particular spot will not fucking fill up past that certain point even if it is available. This blockage can also randomly happen but when it doesn't happen by unsecuring it can usually be fixed by emptying it out with a plumbing  s t i c k.

**Comment by Time-Green** [comment]
> > Cannot reproduce.
> > I've tried two set-ups with chemical acclimators and kept constantly wrenching and unwrenching during both filling and emptying.
> > Could you describe what you did to step-by-step?
> 
> You couldn't replicate it because it happens with mixing chambers not acclimators. Mixing chamber is probably not the right term, but by that I mean the stucture that mixes reagents, not the one that heats or cools them. I was just working on it but the reason I think this happens is the chamber only partially filling up but having one reagent missing, then being unwrenched. What happens is the pipes around the structure behave like if it wasn't unsecured and also from now on a mixing chamber in that particular spot will not fucking fill up past that certain point even if it is available. This blockage can also randomly happen but when it doesn't happen by unsecuring it can usually be fixed by emptying it out with a plumbing s t i c k.

I misspoke, I meant reaction chamber. I’ve also tried it with missing one reagent. 

The pipes becoming static when the chamber is unwrenched is strange. What exactly did you do? Can you describe it step by step? I cannot reproduce it going by your issue alone

**Comment by SuperNovaa41** [comment]
I've never experienced this and it seems the OP didn't want to give any more info
