### ISSUE TITLE
ORM deleting ores when you put them in.

### ISSUE THREAD

**Issue by henriquekill9576** [tgstation/tgstation#51287]
## Round ID:

#137998 on Manuel

## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/basil/server_side_modifications.dm

Round ID: [137999](https://scrubby.melonmesa.com/round/137999)
BYOND Version: 513.1522
Server revision compiled on: 
Master commit: 37788177dba86e20358c9ff4e3a80751edcf20d3
The following pull requests are currently test merged:
#50981: 'Completely disables papercode' by optimumtact at commit c21fde5f17

Local commit: f5651b81a6e7353896127dc9a262acbd78eef384
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.0

## Reproduction:

Simply get some raw ores, not refined ones and put them near the ORM, its supposed to automatically put the ores in and give you mining points, but instead it just deletes all the ores and gives the mining points.
Some notes aswell: You can go around that by putting the ores in by hand, although you won't be able to get any mining points
It seems like the only ores it doesn't delete are plasma, iron and glass

**Comment by LemonInTheDark** [comment]
should fix things #51288
