### ISSUE TITLE
Ice Box Station causing server to come to a crawl due to mob code

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#51282]
Issue reported from  Round ID: [137958](https://scrubby.melonmesa.com/round/137958) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1524

Rohesie was investigating this, but it looks like it's due to ListTargetsLazy running as often as it is with how many mobs are on this map.

**Comment by Rohesie** [comment]
![ElK0swD](https://user-images.githubusercontent.com/42041276/82797725-e4695480-9e4d-11ea-9ea7-f06b31e14e21.png)

This seems to be a mix of the mobs being unoptimized and spawning in excessive numbers.

**Comment by TheVekter** [comment]
Working on having the map removed from rotation for now.

**Comment by TheVekter** [comment]
@Whoneedspacee

**Comment by ATH1909** [comment]
oh god oh fuck

**Comment by MacBlaze1** [comment]
ahaha epic

**Comment by ExcessiveUseOfCobblestone** [comment]
@Whoneedspacee

**Comment by optimumtact** [comment]
Frankly the assertions made in this PR seem off base.

There are not that many calls to the proc in that profile, what is more obvious is that something is making ListTargetsLazy do an absolute tonne of work.

That to me implies that the clients_by_zlevel is incorrectly much larger than it should be.

I don't think icebox should have been disabled without more investigation, this response is disappointing.
