### ISSUE TITLE
Something is Erroneously Calling updatehealth every Few Seconds

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#51299]
Noticed then when glancing at cyborg code; how module unquipping is handled is in `updatehealth`: https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/silicon/robot/robot.dm#L706

This makes sense in the context of making something update the moment their health falls below a threshold.

That said, this made me raise an eyebrow; a long time ago @phil235 made `Life` conditionally update, so things like health overlays aren't reliant on a loop to function and only update when they need to.

Naturally this made me wonder "where's the code that handles when you re-equip an item to a slot on a borg? Does it just call `updatehealth` when it does so to make it unequip, or does it just not equip to begin with?

I couldn't find anything so I booted up to test; damaged myself as a borg until my modulde unequipped, then I re-equipped an item--after a bit of a delay it unequipped the item again.

After that I threw in some debugging text for `updatehealth` and rebooted---not shockingly, `updatehealth` was getting called roughly every 2 seconds, which is roughly how often `Life` takes place.

I have no idea if, for sure, it is `Life` or what is doing this, but the delay is roughly every 2 seconds.

This is an obvious performance problem, as this means that a lot of icons are being rendered (this is happening on every mob it seems) for no reason and is a violation of the system originally put into place.

**Comment by willox** [comment]
I used the debugger and stepped over a bunch of these calls and it seems to be where mobs have been spawned somewhere without an atmosphere so they're taking pressure damage. Like the clowns on the bananium ship.

**Comment by optimumtact** [comment]
people readding shit code, what a suprise

**Comment by Sealed101** [comment]
no longer seems to be the case? the thing causing updates for me was a legion tendril getting spawn camped by a wizard mob, but nothing else seemed to have caused any calls of `updatehealth()`?
no borg effects either, breaking and repairing item slots seemed to work just fine with no sudden changes to the item equipped
can't quite be sure but hopefully this has been fixed question mark? 😃 
also ouch that amount of legion corpses was so awful being near it caused immense lag
