### ISSUE TITLE
handheld crew monitor madness

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#51291]
Round ID:[138012](https://scrubby.melonmesa.com/round/138012) I believe

Test merges aren't important since this issue has been here for a while.

Pretty much once in a while a unknown suddenly gets copied vitals wise on the handheld crew monitor that eventually clutters it up so badly that it makes it unusable.

https://cdn.discordapp.com/attachments/652644737605566485/714630436222926859/tg_Station_Basil_ENGLISH_US-WEST_100_FREE_LAG__Box_Center_Psi_5_25_2020_3_09_33_PM.png

**Comment by wayland-ss13** [comment]
Duplicate of #50792

**Comment by davethwave** [comment]
Understood, closing the issue now.
