### ISSUE TITLE
Scooters prevent fire extinguishers from saving you

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#51317]
## Round ID: 
tested on local

## Reproduction:
Ride around in a scooter
Get set on fire
Bystander attempts to extinguish with a fire extinguisher
Scooter for some reason blocks the spray, and you remain on fire

**Comment by PKPenguin321** [comment]
Probably happens with any vehicle

**Comment by MacBlaze1** [comment]
^

**Comment by ArcaneDefence** [comment]
Fixed by someone or another.
