### ISSUE TITLE
Mining vendomat NTOS BSOD

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#51321]
## Testmerges:
#50981: 'Completely disables papercode' by optimumtact at commit c21fde5f17

## Reproduction:
Dont know how to reproduce
1. Click vendomat
2. See bluescreen of death
when i try to printscreen it print more text
![BSOD](https://i.imgur.com/IAZKSnT.png)

**Comment by ArcaneMusic** [comment]
As of current, mining vendors are vendering properly. TGUI bugs like this are common and are usually fixed easily. Unless there's more specific reproduction steps that caused this specific error, this is probably safe to close.
![image](https://user-images.githubusercontent.com/41715314/99874101-06505380-2bb3-11eb-906c-56bc48a21589.png)
