### ISSUE TITLE
When racking shotgun, you first spin it around your finger.

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#51339]
## Round ID:
[138167](https://scrubby.melonmesa.com/round/138167)

## Testmerges:
#50558: '[REVIEW] Adds Medical Wounds: Bamboo Bones and the Skin of Your Teeth' by Ryll-Ryll at commit e14a0f3f25
#50981: 'Completely disables papercode' by optimumtact at commit c21fde5f17

## Reproduction:
Get a shotgun, use it, first it says Deana Iwakura spins the the riot shotgun around their finger by the trigger. That’s pretty badass, then you have to use it again to rack the pump.

**Comment by LemonInTheDark** [comment]
obviously a feature

**Comment by ATH1909** [comment]
somethin' went wrong with the detective revolver spinning PR, I'd wager

**Comment by necromanceranne** [comment]
No it's working as intended, it's just fucking shit design. The spin overrides any other attackself effect for the gun so having a holster it fucks over not only racking the gun, but also pumping shotguns, emptying revolvers or pulling the bolt on mosins.

**Comment by itseasytosee** [comment]
Danm
