### ISSUE TITLE
Ice legion skull raises lavaland legions on contact with a dead body

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#51335]
![tgStation Terry  EU   100% LAG FREE   New-Dedi  Fatguy Warehouse Theta 2020-05-27 202629](https://user-images.githubusercontent.com/54288658/83062223-98412e80-a05e-11ea-890e-cd094d68f18c.png)
Issue reported from  Round ID: [138145](https://scrubby.melonmesa.com/round/138145) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1517

**Comment by dragomagol** [comment]
Appears to have been fixed
