### ISSUE TITLE
Crew not appearing on crew monitors 

### ISSUE THREAD

**Issue by Sandmoney** [tgstation/tgstation#51332]
(/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1524

Crew monitor is blank despite there being people with suit sensors on. Both handhelds and the computer version display the same results. Changing suit sensors to off and on again changed nothing either. Other medstaff reported the same issue, so it wasn't just me experiencing this.

**Comment by LoserWasTaken** [comment]
round id
