### ISSUE TITLE
Annoying UI issue

### ISSUE THREAD

**Issue by trerri** [tgstation/tgstation#51356]
Issue reported from  Round ID: [138204](https://scrubby.melonmesa.com/round/138204) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1520

Opening UI window popups sometimes makes them appear completely white and requires a reconnect and a reopen to access/close/minimize them

**Comment by Mick1299** [comment]
Hot tip, UIs automatically close of you get far enough away from the source. You can use this to close most bugged UI, saving you a logout

**Comment by Tharcoonvagh** [comment]
just click on it then press alt+f4
