### ISSUE TITLE
Crew Monitors and Handheld Crew Monitors malfunction

### ISSUE THREAD

**Issue by ThePainkiller** [tgstation/tgstation#51360]
Issue reported from  Round ID: [138228](https://scrubby.melonmesa.com/round/138228) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1524

Duplicate of [https://github.com/tgstation/tgstation/issues/51332](this)

Crew Monitor computers and Handheld Crew Monitors show no people on suit sensors a while after a shift, without any other interaction than building the machine or using the handheld in hand.

![image](https://user-images.githubusercontent.com/1294508/83204440-35b16680-a122-11ea-8d35-e9c55b653a8c.png)

**Comment by wabash1** [comment]
This issue still persists for both borg and human after a short amount of time, on round start it seems to work but then goes away. I have cleared my cache and restarted, no luck.
