### ISSUE TITLE
+potency anti-glow makes you glow

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#51367]
![image](https://user-images.githubusercontent.com/42606352/83242352-df641800-a161-11ea-9c17-ca0cd480738a.png)

test your PRs, nemvar

**Comment by ATH1909** [comment]
this isn't the best example, but even in maint tunnels with all of my lights off, I was actively emitting light, IIRC

**Comment by ArcaneDefence** [comment]
https://github.com/tgstation/tgstation/issues/51364
This was also posted literally 2 issues ago.

**Comment by Time-Green** [comment]
Duplicate of #51364
