### ISSUE TITLE
Glass Material Duplication: Infinite Glass

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#51368]
Issue reported from  Round ID:  (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

Have any amount of the following materials in a stack greater than one:  glass, reinforced, plasma, plastitanium, reinforced plasma, etc. 
Attempt to insert into a Techfab.
Fail to delete the material stack in your hand when inserting into a techfab BUT succeed to insert the material amount into said techfab.
Gain infinite resources as long as it is a glass variant.
Profit.

**Comment by TheVekter** [comment]
This is an old higgs-bugson I think, we've had it happen a few times but I don't think we ever really pinned down the cause.

**Comment by TheMidnightRose** [comment]
What I do remember is that I think I upgraded the engineering techfab. Not 100% sure on this.

**Comment by Shiraizawa** [comment]
#51516 It doesnt only work with glass mats, and I found how to recreate. Also a time when I had infinite reinforcedglass in hand and I died 4 stacks of 50 each were dropped on the floor
