### ISSUE TITLE
Wizard can mindswap into slaughter demon

### ISSUE THREAD

**Issue by collinlunn** [tgstation/tgstation#51362]
This allows them to become a demon with fireball, which is effectively unkillable.

**Comment by LemonInTheDark** [comment]
feature, not a bug

**Comment by Koshenko** [comment]
It required two ERTs to bring it down (one of which was a jannie ERT)

**Comment by Fikou** [comment]
![image](https://user-images.githubusercontent.com/23585223/83241210-ccba0500-a19a-11ea-9038-4ae447cb4252.png)

**Comment by ATH1909** [comment]
feature/cool gimmick

also, it requires the slaughter demon to try to melee the wizard before the station manages to kill it off

**Comment by necromanceranne** [comment]
Except mindswap is an instant pointed spell now, so don't even start that crap about it being a 'hard gimmick', ATHATH. The demon is not subject to the stun from mindswap. It's as simple as baiting the demon out and swapping and you can do it very reliably.
