### ISSUE TITLE
Screen freezes

### ISSUE THREAD

**Issue by Ikoden** [tgstation/tgstation#51373]
Round ID:[138276](https://scrubby.melonmesa.com/round/138276)

Lately I've had problems with many screen freezes. Reconnect doesn't help. You need to restart client. This did not happen in the past.

**Comment by rasonjj** [comment]
Round ID: 138428

I am experiencing this same issue, reinstalling byond didn't fix it. There doesn't seem to be a rhyme or reason why it happens. Any job, any zlevel, any time.

**Comment by timothymtorres** [comment]
After checking the issue tracking and discord, this appears to be related to BYOND stuff that /tg/ can't control or fix.  If you are still having this issue try updating to the newest stable BYOND release or try reverting to an older version.

**Comment by timothymtorres** [comment]
Duplicate of #2601
