### ISSUE TITLE
You cannot release-obj Officer Pingsky

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#51371]
Issue reported from  Round ID: [138265](https://scrubby.melonmesa.com/round/138265) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1517

1: Posess Pingsky
2: type release-obj
3: discover yourself in a lovely room with shiney gems and a wet, rocky floor.

**Comment by kriskog** [comment]
Pingsky is a mob, while possess is usually used on items. Does the same happen with any other mob?

**Comment by Jared-Fogle** [comment]
I dragged a random item and did Release-Obj and got sent to shiny gem world.

**Comment by kriskog** [comment]
He is an admin, they do unintended stuff some times.
Turns out admins can (attempt to) release-obj while in any mob, taking them to the gem area. He probably put himself in control of pingsky, then used this verb instead of aghosting.
