### ISSUE TITLE
Mice limit

### ISSUE THREAD

**Issue by Woldmord** [tgstation/tgstation#51381]
## Reproduction:

Regal rats can't spawn more mice if the ammount of mice/rats on the map is bigger than 64 the thing with this is that the game takes in to account dead rats effectively making regals rats unable to spawn mice if there are 64 dead rats on the map mice might also be unable to reproduce through eating cheese if they are 64 dead rats on the map instead hiding the cheese for themselfs

**Comment by ArcaneMusic** [comment]
Config option, not a bug.
If you think it's too low, pester headmins to change the config.
