### ISSUE TITLE
Collosus doesn't gib someone wearing memento mori

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#51400]
Issue reported from  Round ID: [138417](https://scrubby.melonmesa.com/round/138417) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1517

Just keeps shooting shards and slaughtering anything within the (quite large) projectile despawn range.

![image](https://user-images.githubusercontent.com/38219334/83351253-a636ce00-a342-11ea-9c9a-49f670854284.png)

**Comment by Sealed101** [comment]
can't reproduce
