### ISSUE TITLE
Config/Launch Supplypod menu does not support Custom Falling Sounds anymore

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#51405]
Issue reported from  Round ID:  (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

Attempt to use Custom Falling Sound.
Be sad because it doesnt even error message, just fails to open the selection box.
Every other sound however works.

**Comment by Fikou** [comment]
@MrDoomBringer 😭

**Comment by MrDoomBringer** [comment]
what da
