### ISSUE TITLE
Autolathe is destroying any non-stack item with custom-materials without gaining any materials

### ISSUE THREAD

**Issue by willox** [tgstation/tgstation#51406]
This is on master (currently 9768c09637ed4411d10094dc627433c753fdf87e)

## Reproduction:
Get a toolbox and put it in an autolathe. The autolathe consumes the toolbox but does not gain any materials.

## Why it happens

The code is currently written in such a way that any object with custom materials should be able to be inserted into an autolathe as the allowed_types param is set to null on its component: https://github.com/tgstation/tgstation/blob/9768c09637ed4411d10094dc627433c753fdf87e/code/game/machinery/autolathe.dm#L51

This results in mats from non-stack items not being inserted because:
1) The requested_amount var is always null for items that are not stacks here: https://github.com/tgstation/tgstation/blob/9768c09637ed4411d10094dc627433c753fdf87e/code/datums/components/material_container.dm#L83-L102
2) `/datum/component/material_container/proc/insert_item` was changed in https://github.com/tgstation/tgstation/pull/50951 to ignore any input where `amt` is falsey here: https://github.com/tgstation/tgstation/blob/9768c09637ed4411d10094dc627433c753fdf87e/code/datums/components/material_container.dm#L125-L126

**Comment by TerraGS** [comment]
Should definitely revert #50951. Some underlying issues with custom materials will need to be addressed before I can go about fixing the issues related to that PR.
