### ISSUE TITLE
Core R&D console makes game unplayable

### ISSUE THREAD

**Issue by trerri** [tgstation/tgstation#51411]
Issue reported from  Round ID: [138496](https://scrubby.melonmesa.com/round/138496) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1520

Clicking Core R&D sometimes makes all UI take eons to load which makes the game extremely hard to play

**Comment by Tharcoonvagh** [comment]
it's not just the core rnd console mate

**Comment by HomocidlePancakes** [comment]
At least it fucking loads now

**Comment by Angustmeta** [comment]
Now it takes like 30 secs to load, and then the console keeps reopening every few 30 secs or so, even if you only clicked once and walked away to other side of station. 

And then things like techfabs stop working until you relog.

**Comment by ArcaneMusic** [comment]
Due to Core RnD now being moved to a completely new tgui with the experisci changes, and with the several background changes, I'm going to close this pre-emptively. That said, if the issue persists with the new UI, ping me to re-open this.
