### ISSUE TITLE
Nightmare can spawn in atmos mix chamber

### ISSUE THREAD

**Issue by collinlunn** [tgstation/tgstation#51424]
Results in nightmare being stuck in box in space in possibly dangerous gas.

**Comment by Fikou** [comment]
related to #51377?

**Comment by wayland-ss13** [comment]
Don't know if the warp whistle and mare spawn use the same logic to pick a location, but the nightmare from the round this recently happened also lost limbs including the light eater due to burning and revived with just one arm. Hope the formatting nazis don't visit.

Round id: 138560

**Comment by LemonInTheDark** [comment]
feature

**Comment by Kaffe-work** [comment]
If changed, this would require a lot of rewrite for safe_teleport to "safely" ensure that it doesn't happen, or one could ensure that it doesn't happen "as often" by adding some stricter safeguards.

Not sure what is better
