### ISSUE TITLE
Moths have human blood

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#51422]
## Reproduction:
![image](https://user-images.githubusercontent.com/3204033/83473012-74566200-a43d-11ea-8140-e0182b5a496f.png)

**Comment by LemonInTheDark** [comment]
absolutely a feature

**Comment by ATH1909** [comment]
feature

and I'm a moth main, so you can trust me on this one

**Comment by Fikou** [comment]
no race except ethereals has special blood, how is this a bug

**Comment by kriskog** [comment]
Lizards have their own blood type as well. But this is a feature request, those go on the forums.
