### ISSUE TITLE
Item cloning

### ISSUE THREAD

**Issue by Ikoden** [tgstation/tgstation#51429]
Terry RID: 138583
With my backpack closed, I picked up an item from miner's locker and quickly used E hotkey to equip it. The item was cloned. It appeared in my inventory and was still in locker.

**Comment by Cyberboss** [comment]
What was the item?

It's possible this isn't a real dupe but just reference mishandling

**Comment by Cyberboss** [comment]
This is real and works with any item

**Comment by Cyberboss** [comment]
@tgstation/commit-access, I'm working and haven't been around since before storage components existed. Also I have no idea where the fuck to start looking.

**Comment by Ikoden** [comment]
Maybe start looking at the hotkey E (quick equip)? Just a thought

**Comment by nemvar** [comment]
I remember similar reports of desyncs when two people were accessing the same storage at the same time. I don't think that was ever fixed but the item did not actually get duplicated.
Can't seem to find the issue though.

**Comment by kriskog** [comment]
Probably #44762 @nemvar

**Comment by Ikoden** [comment]
Okay, so when that bug could be reproduced, the shuttle subsystem broke as the shuttle didn't arrive. The two things may be connected.

**Comment by ATH1909** [comment]
can you use this to dupe wizard spellbooks?

**Comment by PKPenguin321** [comment]
no because it's not a dupe, it's a desync

**Comment by ATH1909** [comment]
so what CAN it do?

if you do this with krav maga gloves, can both people know krav maga at the same time?

what about HUD eyewear?

**Comment by ATH1909** [comment]
if a storage container gets desynced, and someone puts an item into said storage container, can someone else with a desynced copy of that storage container pull out that item?

**Comment by ATH1909** [comment]
> This is real and works with any item. I checked the refs, they are all different.

also, we have this quote

**Comment by PKPenguin321** [comment]
oh, wack

**Comment by optimumtact** [comment]
there's absolutely no way it can be a clone, there's no new's in storage at all

**Comment by Ikoden** [comment]
There's absolutely no way? How about Cyberboss seeing me do it and seeing the clones?

**Comment by ExcessiveUseOfCobblestone** [comment]
Clone as in it made a complete duplicate of the old item.

It is likely to be the same item in 2 places at once. which isn't a true clone.

**Comment by Ikoden** [comment]
Shame we didn't test it during that round  to be sure.

**Comment by kopoba** [comment]
probably same issue https://github.com/tgstation/tgstation/issues/46737

**Comment by Cyberboss** [comment]
The refs at the objs I looked at were different, I can say that much

**Comment by Jalleo** [comment]
I have been unable to reproduce it locally. I know that the three landing designators are the ones that mining starts with. One in each locker. If there were MORE than three its likely legitimate.

**Comment by msgerbs** [comment]
Has anyone seen this since #52115 was merged?

**Comment by SpaceManiac** [comment]
Closing on the fingers-crossed that #52115 fixed it, reply here if you have evidence otherwise
