### ISSUE TITLE
TEGs cannot be built

### ISSUE THREAD

**Issue by trerri** [tgstation/tgstation#51442]
Issue reported from  Round ID: [138663](https://scrubby.melonmesa.com/round/138663) (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 513.1520

The "Flip" option on right click for the circulators does not work, as such the two circulators cannot be both correctly oriented and the TEG will never recognize them.

Please rework the TEGs and turbines they suck and are 2004 code

**Comment by TemporalOroboros** [comment]
The flip option is solely for orienting the inputs and outputs for the circulators. The TEG does not care about that, it only cares whether it has a hot circulator and a cold circulator. I believe you need to open the circulators with a screwdriver and use a multitool on them to change set them to hot or cold. Then, once the circulators are set, correctly oriented for the piping you are using, and anchored; you need to open the TEG and hit it with a multitool to get it to sync with the circulators and powernet.

**Comment by Fikou** [comment]
so this works correctly?

**Comment by ExcessiveUseOfCobblestone** [comment]
The only supported engines are the turbine and SM (and solars) so just remove it.

**Comment by ArcaneDefence** [comment]
![image](https://user-images.githubusercontent.com/51932756/83652507-f2b71f00-a577-11ea-83f9-948647e9f852.png)
Works just fine for me.

**Comment by Fikou** [comment]
brrrrrrrrrrrrrrrrrrrrrrrrrrrrr
