### ISSUE TITLE
Roundstart portable air tank bomb bug

### ISSUE THREAD

**Issue by wabash1** [tgstation/tgstation#51455]
## Testmerges:
 Fixes turf atmos getting deleted. by nemvar 
[REVIEW] Adds Medical Wounds: Bamboo Bones and the Skin of Your Teeth by Ryll-Ryll

## Reproduction:

I did the same thing yesterday and the below did not result in an explosion with my death.

Grab a large red o2 tank from the emergency locker, run to a portable air pump, set to in, turn it on, max the value on it, drag it around to suck up a bunch of air, by this time it should have at least 3000 pressure,  turn it off when you are past 3000, put an air tank in it, you now have a suicide bomb, turn on and create a large explosion at least 5x5 empty tiles. at about 2500 it will result in 30,000 in the air tank.

**Comment by ATH1909** [comment]
so, wait, is the bug that this DOES kill you, or is the bug that this DOESN'T kill you?

**Comment by wabash1** [comment]
The bug is in the 5x5 tile clearing or more (haven't tested) explosion upon
recreation of the bug. You will die once you fill the o2 tank. It's acting
like a really good TTV mix and all I need is an o2 tank and a portable air
pump.

**Comment by TemporalOroboros** [comment]
5x5 as in diameter or radius? One is a bad toxins bomb and the other is a maxcap.

**Comment by nemvar** [comment]
Has been resolved.

**Comment by nemvar** [comment]
https://github.com/tgstation/tgstation/pull/51453
