### ISSUE TITLE
Something is deleting turf air datums and it's killing the server

### ISSUE THREAD

**Issue by nemvar** [tgstation/tgstation#51452]
## Round ID:

[138752](https://scrubby.melonmesa.com/round/138752)
https://tgstation13.org/parsed-logs/manuel/data/logs/2020/06/04/round-138752/

## Testmerges:

Not relevant.

## Reproduction:

Something has deleted the air from these two turfs. Caused the entire server to stall.
![turfs](https://user-images.githubusercontent.com/47324920/83792238-0d35e900-a69b-11ea-8351-17892904b09c.PNG)

```
15:48:30 [0x200a618] (197,120,2) || the BZ canister was destroyed.
15:48:33 [0x2009213] (195,126,2) || the plasma canister was destroyed.
15:48:33 [0x20095f6] (196,126,2) || the plasma canister was destroyed.
```

Canisters were destroyed on these turfs.

Here is another round where something similar happened:
https://tgstation13.org/parsed-logs/terry/data/logs/2020/06/02/round-138583/runtime.txt

Note that it happened on Pubby both times, might be map related or just general canister nonesense.

**Comment by TemporalOroboros** [comment]
I think I might have found it.

When a canister processes and the valve is open it tries to make a reference to the tank it's holding. If it's not holding a tank it makes a reference to the air on the canisters turf. This reference gets stored in the passive gate used to handle the canister valve.
https://github.com/tgstation/tgstation/blob/efe101b052c452e986d294713ad11cc506b76438/code/modules/atmospherics/machinery/portable/canister.dm#L390-L416

When the canister is deleted it deletes the passive gate.
https://github.com/tgstation/tgstation/blob/efe101b052c452e986d294713ad11cc506b76438/code/modules/atmospherics/machinery/portable/canister.dm#L270-L273

The passive gate is a type of atmospherics machinery. When atmos machinery gets deleted it loops through all of the atmos nodes it has and attempts to handle garbage collection.
https://github.com/tgstation/tgstation/blob/efe101b052c452e986d294713ad11cc506b76438/code/modules/atmospherics/machinery/atmosmachinery.dm#L64-L78

The passive gate is a type of atmos component, which is a subtype of atmos machinery. Atmos components override the proc used to gc the atmos nodes and qdel the corresponding referenced gas mixture as part of their procedure.
https://github.com/tgstation/tgstation/blob/efe101b052c452e986d294713ad11cc506b76438/code/modules/atmospherics/machinery/components/components_base.dm#L74-L78

I think this might be what's happening. This would require that the passive gate is somehow getting something in the parents list and I don't see how that could be happening. Maybe I'm just overthinking things.
