### ISSUE TITLE
Exploding emergency oxygen tanks

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#51469]
Issue reported from  Round ID: [138856](https://scrubby.melonmesa.com/round/138856) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1517

When attempting to fill my oxy tank to 2500~ kpa it exploded with the power of several minibombs. Pure oxygen at room temperature. The process went like this:

1. Empty out the large o2 cans completely into a portable air pump. (in my case it was one from a fire locker)
2. Insert emergency can in your internals box into said pump
3. Set to max pressure.
4. Turn on pump.
5. Watch as you and several others get gibbed and a quarter of atmos and tech storage is removed from existence.

![2020-06-05 15_56_05-_tg_Station Basil  ENGLISH   US-WEST   100% FREE LAG _ fucking wizards again_](https://user-images.githubusercontent.com/36066032/83925720-1b404400-a745-11ea-8e20-62599734bd65.png)

Keep in mind this was room temperature gas 100% composed of o2. When I was watching the pressure gauge it skyrocketed into 50,000+ kpa and then everything went white.

**Comment by Fikou** [comment]
can't reproduce with steps given, you sure something else didn't cause the explosion?

**Comment by Fikou** [comment]
oh nevermind it was an issue with the testmerge of nemvar's pr and he fixed it already
