### ISSUE TITLE
bubblegum's hitbox prevents them from actually attacking melee

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#51465]
## Round ID:
private server

## Reproduction:
1. assume control of bubblegum
2. try to melee something
3. rend yourself

note: this also seems to work for the colossus

**Comment by redguy999** [comment]
this only works when trying to attack something to the left or right of you while as the large sprite.

**Comment by Fikou** [comment]
there is a reason why you have a spell to turn yourself small
