### ISSUE TITLE
Off-hand stuck

### ISSUE THREAD

**Issue by DanielFigueroa1** [tgstation/tgstation#51462]
Issue reported from  Round ID: [138815](https://scrubby.melonmesa.com/round/138815) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1525

I used the wall defibrillators in medbay but with telekinesis outside the room, when i dual welded them i could use them normally but even beyond its usual reach and then my off-hand became stuck and unusable, had to get admin help to fix it.

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=VqB1uoDTdKM

**Comment by nightred** [comment]
Actually the issue with the offhand was fixed.
The issue with the defib working at that range is an issue. it has range checks and should have snapped back as that is to far for the paddles. but the force move did not work.
