### ISSUE TITLE
WEIRD toxins explosion and spooky ghost tank!!

### ISSUE THREAD

**Issue by trerri** [tgstation/tgstation#51468]
Issue reported from  Round ID: [138852](https://scrubby.melonmesa.com/round/138852) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1520

(on Icebox if that somehow matters)
I was following the guide to toxins and I filled an empty oxytank with 850kPa of 43°K tritium and then went to the O2 portable pump to get my maxed fill of oxygen (also 43°K).
When I did that, an explosion with explosive power 0 happened. This explosion throws items in a 3x3 radius away from it with a throwforce of I presume 0, blinds people in that radius and destroys the tank.
However.
The tank still registers as being inside the pump; pulling it out will show you an inhand of the tank but no actual item. Dropping it will make it disappear. Interestingly enough, this tank still works perfectly inside a TTV, although I did not try pulling it out.
The bomb yielded about 6700 points, although that might've been because of the plasma tank being 1000ish short of 8000°K.

**Comment by Whoneedspacee** [comment]
This also occurs if a tank breaks due to being between 3500-4000 kpa or whatever. Pretty much if the tank is broken in any way the UI doesn’t update I assume.

**Comment by tralezab** [comment]
![image](https://user-images.githubusercontent.com/40974010/145169478-0056d7aa-f810-414c-9abc-c6054da70099.png)
