### ISSUE TITLE
Bucklecuffing with solely a grab

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#51475]
## Round ID: 
#138870

## Reproduction:
There's a case where if you buckle someone to anything while grabbing them (with aggro grab at most), resisting off the pipe/chair/etc that you're buckled to takes a full minute to escape as if you're bucklecuffed, despite having no restraint other than the aggro-grab. Someone ahelped about it so I went and managed to replicate it:
![Capture3](https://user-images.githubusercontent.com/32374784/83934453-04f6b000-a766-11ea-9cb8-fc7e1eac4964.PNG)
![Capture](https://user-images.githubusercontent.com/32374784/83934455-06c07380-a766-11ea-9455-99abbd776304.PNG)
![2](https://user-images.githubusercontent.com/32374784/83934456-0922cd80-a766-11ea-86bd-bd0a24925e02.PNG)

**Comment by ATH1909** [comment]
when you say "at most", does that mean that passive grabs work for this, or that neck grabs and the like work for this?

**Comment by nightred** [comment]
This is as intended.
So when you are still being held and have been buckled to an object you take a long time to get out.
If you are no longer being held but still buckled to the item you can unbuckle instantly.

https://github.com/tgstation/tgstation/blob/6995c36f0506fd3a8232194a2980325dede34746/code/modules/mob/living/carbon/carbon.dm#L172

This is as intended not an issue.
