### ISSUE TITLE
breath masks can burn through fireproof space proof armor

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#51479]
who tought breath masks needed to be burnable in the first place? fix your shit

**Comment by Fikou** [comment]
are you using cap swat suit? it doesnt cover your mouth which is why stuff burns through it, this is the reason why captain/atmos gas mask exists

**Comment by Tlaltecuhtli** [comment]
why does it no cover mouth? whats the point its freakin fire proof

**Comment by ATH1909** [comment]
idk, but they added the captain's gas mask to compensate for that

still dumb, imo

**Comment by nightred** [comment]
As the hardsuit does not cover mouth this is not a bug.
Changes to behavior can be submitted on this, closing the issue.
