### ISSUE TITLE
Solved: Cant access chat controls as well as many menu items such as achievements

### ISSUE THREAD

**Issue by CrossbowDemon** [tgstation/tgstation#51482]
EDIT:
Fixed.
Someone helped me in the Discord. The settings within Internet Explorer itself did not have JavaScript enabled.

Issue reported from  Round ID: [138906](https://scrubby.melonmesa.com/round/138906) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1525

OS: Windows 10 Home 64-Bit Version 10.0.19640
CPU: AMD FX-6300
GPU: GTX 960 2GB
RAM: 8GB DDR3
MB: MSI 760GMA-P34(FX)

I've un and re installed BYOND, Internet Explorer, and both 32 and 64 bit Java. I've used both the stable and beta versions of BYOND. I've deleted the entire BYOND folder from documents. I've updated windows, updated my graphics driver, restarted my computer, tried the Window's compatibility troubleshooter, and the in game Fix Chat command from the OOC tab.

Not a single one of the things I have tried have had any kind of effect on fixing the chat.

This is what the lobby screen looks like, notice the lack of buttons on the top right of the chat.

![BrokenChat1](https://user-images.githubusercontent.com/12440200/83946054-94d74100-a7dc-11ea-9d3e-49a57a7fd990.png)

When I click on Check Achievements in the OOC tab I get this message:

> _Javascript is required in order to use this interface._
> _Please enable Javascript and restart the game._

![BrokenChat2](https://user-images.githubusercontent.com/12440200/83946203-52623400-a7dd-11ea-92b3-bc8b1a8e712e.png)

If anyone can help me fix this without doing a full refresh on my computer that would be insanely helpful. Please suggest anything I might have not yet tried.

**Comment by Gamer025** [comment]
This is probably not the right place for this (this is more for code issues like game bugs etc) and you should probably use the TG forums or the Discord but I guess you could try:
Disabling any third party Antivirus just to test if that blocks anything or disabled JS in IE.
Disable any Add-Ins in IE (especially Add-Blockers)
Reset the settings in IE

**Comment by Fikou** [comment]
have you tried enabling javascript

**Comment by CrossbowDemon** [comment]
> have you tried enabling javascript

Fixed.
Someone helped me in the Discord. The settings within Internet Explorer itself did not have JavaScript enabled.
