### ISSUE TITLE
emagged meteor shields don't seem to increase the chance of meteors spawning

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#51484]
round ID was 138879

I, the mime (name: Acrobat) set up like 13 meteor shield satellites in space, activated them all, and emagged them all, which should have multiplied the chance for the meteors event to occur by something like 2^13.

However, as far as I'm aware, no meteors spawned that round (unless you count that space dust event (which didn't touch any of my satellite shields, by the way)?). This was very disappointing, as I had been focusing on this gimmick over having fun with my discounted explosive holoparasite that round.

**Comment by YPOQ** [comment]
https://github.com/tgstation/tgstation/blob/add74bee56cfde91602eb8ee28e3cae5959bc4f6/code/modules/station_goals/shield.dm#L170
This needs to be rewritten as a loop since there are multiple meteor_wave subtypes, and right now it's just arbitrarily picking one (major or minor space dust, probably).
