### ISSUE TITLE
smoke eats light bug

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#51483]
138910
chemical smoke makes light disappear once the smoke goes away leaving shit like this 
![smoke bug](https://user-images.githubusercontent.com/33834933/83948230-27e39b80-a81c-11ea-9c73-b71f58fd8150.png)

**Comment by ATH1909** [comment]
does this work with smoke machines?

is this "real" darkness for the purposes of nightmares, podpeople, and the like?

**Comment by AnturK** [comment]
Almost certainly same thing as #51188 , fix included.

**Comment by dragomagol** [comment]
Fixed by #51943
