### ISSUE TITLE
weird ping numbers

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#51489]
![float](https://user-images.githubusercontent.com/33834933/83967479-28367200-a8c2-11ea-9b5d-d0a0d5127701.PNG)
138972

**Comment by Fikou** [comment]
get a better pc

**Comment by ShizCalev** [comment]
Think that means their client completely lagged out or something, cause avgping is already rounded to the nearest whole number.

https://github.com/tgstation/tgstation/blame/add74bee56cfde91602eb8ee28e3cae5959bc4f6/code/modules/client/verbs/who.dm#L37-L51
