### ISSUE TITLE
suit sensor monitors are still borked

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#51496]
they'll (sometimes?) just break and not show any suit sensors at all.

**Comment by Jared-Fogle** [comment]
Notably, they work for a bit, and then break. I've been trying for a while to try and reproduce this on a private server.

**Comment by JenqaDev** [comment]
yes we are able to see them for a glance but then everyone on the list disappears

**Comment by Jared-Fogle** [comment]
Crew monitors worked in round 139160 which lasted over an hour, if I remember right.

**Comment by Jared-Fogle** [comment]
The crew monitor worked in round [139173](https://tgstation13.org/parsed-logs/basil/data/logs/2020/06/10/round-139173), which I believe lasted for over an hour.

**Comment by Jared-Fogle** [comment]
Worked with some admins in a round where it broke to figure it out, there were people with active nanite sensors that round, where in the round I say that CMCs worked, I heard there weren't nanites at all. Would be interested in test merging a PR to remove the Monitoring nanite to see if that's the cause of the issue.

**Comment by Jared-Fogle** [comment]
Also notable is that `update_data` returned `null` (which looks like it should be impossible!), and `GLOB.suit_sensors_list`, `GLOB.nanite_sensors_list`, and `SSnanites.nanite_monitored_mobs` all correctly showed the mobs they're meant to hold.

**Comment by Mothblocks** [comment]
this was fixed a while ago
