### ISSUE TITLE
Ash drake armour isn't properly temperature proof

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#51504]
## Reproduction:
1. Play on Icebox
2. Craft yourself some fine-ass ash drake armour
3. Once in a few minutes, get a smidge of damage and a blue temperature notification, which then instantly vanishes again

**Comment by timothymtorres** [comment]
https://github.com/tgstation/tgstation/blob/a45e8952613b4e609b16e3fd0c56974c455b78a9/code/modules/clothing/suits/cloaks.dm#L70-L83

It appears that ash drake armor only offers protection to fire and hot temperatures.  This seems intended.
