### ISSUE TITLE
The lava boat does not work on plasma lava

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#51505]
## Reproduction:
1. Play icebox
2. Kill portal for ship-in-bottle
3. Step in boat on plasma lava
4. Enjoy burning and being unable to move, as if you'd just step onto the lava without a boat.

**Comment by yorii** [comment]
Plasma tiles require plasma boats which have FREEZE_PROOF, lava boats provide LAVA_PROOF | FIRE_PROOF.

Dragon boat is a subtype of lava boat, but is it perhaps supposed to also have FREEZE_PROOF?

**Comment by Whoneedspacee** [comment]
not a bug, adding a way to make plasma boats on icebox soon
