### ISSUE TITLE
wizards in rod form deal much less damage to targets that aren't the first thing they hit

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#51506]
1. be a wizard
2. take rod form and upgrade it a few times
3. rod form and hit someone, notice that they take X amount of damage
4. place an airlock (or even another person) between yourself and a new target, then rod form
5. notice that the person who you hit after the airlock took considerably less damage than X

**Comment by Fikou** [comment]
it makes sense with physics idk bro

**Comment by Pugie** [comment]
> it makes sense with physics idk bro

It's an immovable rod...

**Comment by Fikou** [comment]
yeah and
