### ISSUE TITLE
Flag at CTF can be walled off

### ISSUE THREAD

**Issue by Jared-Fogle** [tgstation/tgstation#51510]
## Round ID: 

[139031](https://scrubby.melonmesa.com/round/139031)

## Details:

During a game of CTF, someone managed to build walls around the flag. There were no admins online that would've been able to give the metal. I have no idea how the metal was acquired or how to reproduce this.

![image](https://user-images.githubusercontent.com/35135081/84005346-dae9ed00-a921-11ea-9383-3a1a3e57da51.png)

**Comment by Tharcoonvagh** [comment]
Can you break the tables on the norhtern side of the arena? If so then 
![lzY8aSvh](https://user-images.githubusercontent.com/54288658/84194667-a9962c00-aa9d-11ea-8239-ab8a27c5a8b2.gif)

**Comment by Jared-Fogle** [comment]
@Tharcoonvagh Turns out you can! Though it gives metal rods and plasteel, not the metal needed to make the walls in the picture. Separate bug or am I missing something?
