### ISSUE TITLE
You can ollie through CTF spawn protection.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#51511]
## Testmerges:

- https://github.com/tgstation/tgstation/pull/50558

## Reproduction:

1. Join CTF
2. Using mystery metal sheets and rods sourced from who-knows where (https://github.com/tgstation/tgstation/issues/51510) build
  - A scooter frame
  - An improvised skateboard
3. Ride the skateboard
4. Attempt to ollie into the other teams spawn protection because you are out of ammo and will to live
5. Wind up in the other teams spawning room

**Comment by ATH1909** [comment]
holy shit that's amazing

**Comment by Fikou** [comment]
feature
