### ISSUE TITLE
The pirate cutter's SMES is fucked

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#51513]
See above. For whatever reason it won't put out power to the shuttle, so bullshit like coming back from raiding something and everything having no power for _reasons_ happens.

**Comment by msgerbs** [comment]
Is this fixed by #53132?

**Comment by msgerbs** [comment]
@TheVekter I don't ever do space exploration, can you confirm if this is still an issue?

**Comment by timothymtorres** [comment]
This might be related to #47148 and #39405

**Comment by Sealed101** [comment]
could not reproduce; no sudden power loss observed when moving/waiting/fucking around the cutter
likely fixed by #53132 or whatever the fuck 4 years have passed someone somewhere fixed those damn wires
