### ISSUE TITLE
[reported on fulpstation] welded vents still release fluids during a backpressure surge

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#51521]
![image](https://user-images.githubusercontent.com/42606352/84083040-7e7ce100-a9a6-11ea-9e3f-a10201ff57e8.png)

**Comment by ATH1909** [comment]
this is especially odd because there's a check in setup() to prevent this from happening:
```
/datum/round_event/vent_clog/setup()
	endWhen = rand(25, 100)
	for(var/obj/machinery/atmospherics/components/unary/vent_scrubber/temp_vent in GLOB.machines)
		var/turf/T = get_turf(temp_vent)
		if(T && is_station_level(T.z) && !temp_vent.welded)
			vents += temp_vent
	if(!vents.len)
		return kill()
```
perhaps this happens if a vent is welded between setup() and the actual releasing of the foam?

**Comment by ivanmixo** [comment]
Couldn't replicate on a private server, welded scrubbers don't spew chems if welded.

**Comment by Dorsisdwarf** [comment]
Tested and could not reproduce. @ATH1909 did the reporter accidentally weld the VENTS instead of the SCRUBBER?
