### ISSUE TITLE
[reported on fulpstation] more changeling lesser form jank

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#51520]
![image](https://user-images.githubusercontent.com/42606352/84079482-4a062680-a9a0-11ea-81b3-7b705b840dbe.png)

**Comment by timothymtorres** [comment]
@ATH1909 did you confirm this to exist on tg?  I talked to some of the maintainers on discord and a lot of the servers downstream have diverged their code bases significantly.   If this can't be replicated on tg, this should probably be closed.

**Comment by ATH1909** [comment]
> @ATH1909 did you confirm this to exist on tg? I talked to some of the maintainers on discord and a lot of the servers downstream have diverged their code bases significantly. If this can't be replicated on tg, this should probably be closed.

fulp hasn't touched changeling code, to my awareness, so this bug should also exist on /tg/ (unless it's been fixed in the year since this issue report was made). It's at least worth testing.

**Comment by timothymtorres** [comment]
I just tested this on local as a ling.  I had zero issue transforming into the selected human DNA and I did this several times with different DNA.  I'm going to mark this as closed since I don't see any matching issues having this same problem.
