### ISSUE TITLE
[reported on fulpstation] trying to perform (augged) self-surgery on your head can result in you eating what you're trying to implant in yourself

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#51522]
![image](https://user-images.githubusercontent.com/42606352/84083129-a9ffcb80-a9a6-11ea-9fe1-f7da1bf4a3ae.png)

**Comment by PKPenguin321** [comment]
don't think we have self surgery

**Comment by ATH1909** [comment]
> don't think we have self surgery

we do if you're augged

**Comment by Doosteroni** [comment]
I’ve never had this problem ever

**Comment by ATH1909** [comment]
> I’ve never had this problem ever

even with the dental implant surgery (y'know, the one where you put a pill in one of your teeth)?

**Comment by Fikou** [comment]
we dont have head implants

**Comment by ATH1909** [comment]
> we dont have head implants

we do: anti-drop, anti-stun, etc.

**Comment by Fikou** [comment]
those arent items you can eat and thats organ manipulation not implanting stuff like in chest

**Comment by Dorsisdwarf** [comment]
It's still technically a bug with our codebase even if we dont currently have a way of triggering the bug

**Comment by TheBonded** [comment]
this only happens if you are on the wrong step to insert the item inside, afaik
