### ISSUE TITLE
Gate inside a gateway is unable to be activated

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#51537]
Round ID: [139108](https://scrubby.melonmesa.com/round/139108)

says "Home gateway already in use!"
because of this, got stuck in gateway, not sure if its intended

**Comment by ATH1909** [comment]
IIRC, if someone on the station (say, the AI) shuts off the gateway on the station's end, you can use the gateway on the away mission's end to open up a stable two-way connection between the away mission's gateway and the station's gateway.

Still, this should definitely be patched/fixed.

**Comment by Sealed101** [comment]
link issues properly ath come on
https://github.com/tgstation/tgstation/pull/53058
