### ISSUE TITLE
Medibot panel interface doesn't open when being used

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/tgstation#51548]
Issue reported from  Round ID: [139150](https://scrubby.melonmesa.com/round/139150) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1507

Testmerge #50558 

Medibots do not let you interface their panel. You are able to ID unlock/lock but you cannot interface it's panel at all.

Reproduction:

1. Make medibot
2. Try to interface with empty hand
3. Doesn't open up any menu for it

**Comment by ATH1909** [comment]
I blame https://github.com/tgstation/tgstation/pull/51394.

**Comment by ExcessiveUseOfCobblestone** [comment]
I would be very interested to know how a PR that does not touch the UI or even change any functionality around that broke the ui anon...

**Comment by Kaffe-work** [comment]
I would more guess the PR that did small changes to ui

**Comment by ATH1909** [comment]
> I would be very interested to know how a PR that does not touch the UI or even change any functionality around that broke the ui anon...

Oh.

Maybe it was Ryll's PR (https://github.com/tgstation/tgstation/pull/51409), which was merged at around the same time that your PR was merged?

**Comment by ATH1909** [comment]
![image](https://user-images.githubusercontent.com/42606352/84213296-e48c6580-aa85-11ea-934d-70afd9960391.png)

he's referring to @Ryll-Ryll 's PR here
