### ISSUE TITLE
Unable to defibrilate bodies of any race

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#51559]
Issue reported from  Round ID: [139182](https://scrubby.melonmesa.com/round/139182) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1524

I have no clue how this ended up happening. Examining the player didn't show the message saying they're a suicide, but people trying to defib them got the message 'The cyborg defibrillator paddles (Wielded) buzzes: Resuscitation failed - No intelligence pattern can be detected in patient's brain. Further attempts futile.' Putting his brain in an MMI worked perfectly fine. I ended up having to aheal him.

Here's his examine:
![image](https://user-images.githubusercontent.com/7019927/84236137-c3933700-aabc-11ea-8c7a-971284c42fde.png)

Player was a moth but I don't think that matters in this case.

**Comment by Time-Green** [comment]
This isn’t suicide, it’s a missing brainmob. No idea how that happens though

**Comment by TheVekter** [comment]
This is _waaaaaaaay_ worse than I thought - defibbing is broken on bodies wholesale. It seems to always think there's no brainmob attached to the body.

**Comment by Jared-Fogle** [comment]
~~Worked on my machine~~ Should probably revert https://github.com/tgstation/tgstation/pull/51478 until I figure out what is going on.

**Comment by Jared-Fogle** [comment]
I've made two PRs: #51561 which is just a straight revert, intended for test merging, and #51562 which is my theory for solving the issue.
