### ISSUE TITLE
Obtain the Secret Documents held by another traitor objective does not work.

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#51569]
## Round ID:
[139224](https://scrubby.melonmesa.com/round/139224)

## Testmerges:
Not Valid.

## Reproduction:
Spawn in as traitor, get the Objective #1: Acquire the "Red" secret documents. held by Deana Iwakura, the Chemist and syndicate agent Objective, the other person does not have the documents, causing redtext.

**Comment by Fikou** [comment]
why do we even still have document objectives enabled
