### ISSUE TITLE
Indefinite Glove-Based Martial Arts.

### ISSUE THREAD

**Issue by Pugie** [tgstation/tgstation#51566]
Issues is a result of #50294 I believe.

How to replicate:

Step 1: Put on martial arts providing gloves (boxing gloves, krav maga gloves etc.
Step 2: Swap them out using the equipment swap keybind.
Step 3: Now you are able to box/use krav maga without needing the gloves, enabling the user to use them with gloves of the north star, for example.

**Comment by Fikou** [comment]
related issue: #50798

**Comment by nemvar** [comment]
Dupe of issue mentioned above
