### ISSUE TITLE
Connector port instead of injector in icebox xenobio secure chamber

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#51563]
Issue reported from  Round ID: [139208](https://scrubby.melonmesa.com/round/139208) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1517

**Comment by ivanmixo** [comment]
https://i.imgur.com/BCx0XkX.png

Don't think that's a connector

**Comment by Whoneedspacee** [comment]
you're wrong
