### ISSUE TITLE
posters being placed during shuttle movement end up in wrong place if the shuttle moves before finishing.

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#51577]
![image](https://user-images.githubusercontent.com/42606352/84356362-b132ff00-ab89-11ea-89f2-1f637111d1ef.png)

**Comment by ATH1909** [comment]
honestly, at this point, it might be nice to create/have a fulpstation tag or something

**Comment by Fikou** [comment]
why should we have a tag for reports from one codebase that you post issues from

**Comment by ATH1909** [comment]
> why should we have a tag for reports from one codebase that you post issues from

because a lot of fulp's bugs apply to us too, since our codebases are 99.99% the same

**Comment by LemonInTheDark** [comment]
ath, just test it yourself and if it's a problem report it as normal. If it isn't, ignore it, it's a them issue.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/76f8897d1fc329c4aff846b7f1f20eee7259b556/code/game/objects/effects/contraband.dm#L126-L167

**Comment by Dennok** [comment]
Problem in D.roll_and_drop(temp_loc) 
temp_loc is start place that losts in hyperspace/on shuttle base.
