### ISSUE TITLE
Medibots don't scan for any type of damage besides brute

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/tgstation#51588]
Issue reported from  Round ID: [139331](https://scrubby.melonmesa.com/round/139331) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1507
![image](https://user-images.githubusercontent.com/24631139/84455788-d1011a80-ac90-11ea-9606-ca90b6660be1.png)

**Comment by ATH1909** [comment]
goddamnit, cobby

**Comment by Time-Green** [comment]
@ExcessiveUseOfCobblestone

**Comment by ExcessiveUseOfCobblestone** [comment]
intended, I killed medibots ;)

**Comment by Time-Green** [comment]
Bababooey moment
