### ISSUE TITLE
Engineering tools and a couple other things are missing their mirrored sprites

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#51598]
@ArcaneMusic

#51328

You added a bunch of belt sprites but didn't make versions for them in the mirrored file (used by suit slots)
https://github.com/tgstation/tgstation/blob/master/icons/mob/clothing/belt_mirror.dmi

**Comment by ArcaneMusic** [comment]
Big sad, but thankfully an easy  fix.
