### ISSUE TITLE
Can't use any of the bar machines without reconnecting every single time

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#51617]
## Testmerges:
#51412 
#50981 

## Reproduction:
Click on soda dispenser, booze dispenser, or the booze vendor in bar. Close the window. Attempt to use said machine again, reconnect, and then use it and it works.

**Comment by ArcaneMusic** [comment]
Explain what you mean by "Can't use". Do you mean the UI doesn't open, or that it's providing the NTOS Bluescreen "Crash" window, OR do you mean the UI is opening, but it's not responding to buttons/inputs?
This almost certainly feels like a UI issue.

**Comment by VladinXXV** [comment]
UI wouldn't open. Sorry for not specifying.

**Comment by nightred** [comment]
Unable to reproduce.
Please add new steps for this issue if you are still having the issue.
