### ISSUE TITLE
Possible server crashing bug

### ISSUE THREAD

**Issue by wabash1** [tgstation/tgstation#51615]
## Testmerges:
#51412: 'Adds rotation support to the maploader ' by kevinz000 at commit be50d0d984
#50981: 'Completely disables papercode' by optimumtact at commit c21fde5f17

## Reproduction:

Put a synthesizer in someones hand, play music, walk up to them, when music ends it comes onto you to ask for a new song, you put song in, (Play? MAYBE walk away not sure on this step) close window, server crash

**Comment by ATH1909** [comment]
oh shit

**Comment by zxaber** [comment]
Could not reproduce crash. Instrument window does pop up after the song ends even when the synth is in the hands of another mob, and any attempts to re-play the current song or change the song work as long as you are right next to them with no crash. Any attempts to interact with the gui at all after walking away simply throw the "You're too far away!" message and fail as expected.

**Comment by wabash1** [comment]
> 
> 
> Could not reproduce crash. Instrument window does pop up after the song ends even when the synth is in the hands of another mob, and any attempts to re-play the current song or change the song work as long as you are right next to them with no crash. Any attempts to interact with the gui at all after walking away simply throw the "You're too far away!" message and fail as expected.

Thinking here... would it make a difference if it is a live person?

**Comment by WarlockD** [comment]
Does this have something to do with importing using that text box from byond?

**Comment by TheBonded** [comment]
> Could not reproduce crash. Instrument window does pop up after the song ends even when the synth is in the hands of another mob, and any attempts to re-play the current song or change the song work as long as you are right next to them with no crash. Any attempts to interact with the gui at all after walking away simply throw the "You're too far away!" message and fail as expected.

perhaps if the person holding it changes the song, and then you change the song while standing next to them?
