### ISSUE TITLE
Families on dynamic causes the game to think other antagonist kills as families gang kills, causing higher police level.

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#51614]
## Round ID:
[139403](https://scrubby.melonmesa.com/round/139403)

## Testmerges:
Not Applicable.

## Reproduction:
Be any antag, kill on a families dynamic round, watch as the police get mad that someone else murderboned. (Just revert dynamic families tbh)

**Comment by dragomagol** [comment]
Families isn't on dynamic anymore
