### ISSUE TITLE
Being in disposals under a shuttle when it arrives gibs you

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#51611]
## Testmerges:
#50981 
#51412 

## Reproduction:
1. Be in a disposals pipe under the space where a shuttle docks, like the cargo shuttle
2. Have said shuttle dock
3. Die

**Comment by Fikou** [comment]
feature

**Comment by Paxilmaniac** [comment]
no

**Comment by Dorsisdwarf** [comment]
Where did the edge case label go

**Comment by Dennok** [comment]
Shuttle annihilate pipe.

**Comment by Paxilmaniac** [comment]
> Not bug.
> Shuttle annihilate pipe.
> Or this multiZ under?

not related to multiZ, and in that case it should break the pipe, not just gib you and leave the pipe alone

**Comment by timothymtorres** [comment]
The shuttle deleted everything under it.  This is intended.
