### ISSUE TITLE
the new map rotation thing cant rotate the station floor name and gateway properly

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#51624]
![rotation bug](https://user-images.githubusercontent.com/33834933/84571982-51aa3e80-ad97-11ea-90aa-b207f126e356.PNG)
139464

**Comment by Tharcoonvagh** [comment]
fucking cursed

**Comment by kriskog** [comment]
its a testmerge, these issues are already reported in the PR
