### ISSUE TITLE
had all huds as a pAI

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#51622]
this screenshot was taken BEFORE I bought anything, and includes a diagHUD, which pAIs normally can't buy:
<img width="1440" alt="pAIhudsroundID139434bagil" src="https://user-images.githubusercontent.com/42606352/84564509-dc535500-ad27-11ea-8e65-7bc4cef130fd.PNG">

server was bagil, round ID was 139434

**Comment by GunHog** [comment]
Caused by: https://github.com/tgstation/tgstation/pull/51549

Someone should add the (Basic) Diagnostic HUD to the module store, though.

**Comment by ATH1909** [comment]
aw crap

**Comment by nightred** [comment]
This is resolved in pr #43741
