### ISSUE TITLE
jumpsuits won't fix no matter how much cloth you put into them, also jumpsuits can be eaten twice

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#51626]
Issue reported from  Round ID: [139470](https://scrubby.melonmesa.com/round/139470) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1525
(issue was first found earlier than this round)
Issue one: put at least 5 bed sheets worth of cloth into a sec jumpsuit, the damaged areas tag disappeared, but it still looked visibly torn.
(admin also tried to do admin magic on jumpsuit, jumpsuit still looked torn when worn again)
issue two: shredded jumpsuits can still be eaten by moths, meaning that you can eat them twice.

**Comment by Ryll-Ryll** [comment]
Assign me
