### ISSUE TITLE
Greentext (the book) doesn't give greentext (on round of end report)

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#51620]
## Testmerges:
#51412 
#50981 

## Reproduction:
A round on icebox with roundstart cult and traitors, and also a latejoin syndicate infiltrator. Cult succeeds, but Nar'Sie is killed. You are on the station level inside a miner shelter pod with the greentext in your hand when the round ends. Nothing about said greentext even appears on the round end screen. It was a real one for sure because holding it makes me green/dropping it makes me red and I get the chat messages about "As long as you escape with the greentext you'll be happy" and "You feel a sudden wave of failure"

**Comment by ATH1909** [comment]
the greentext was from the lust ruin, and the lust ruin greentext is a real one, so the greentext was definitely real

**Comment by JohnFulpWillard** [comment]
seems to be fixed now
![image](https://user-images.githubusercontent.com/53777086/154061216-5f850301-643f-473b-b4c8-8077804db54c.png)
