### ISSUE TITLE
Possible syndicate borg crash

### ISSUE THREAD

**Issue by Quietly12** [tgstation/tgstation#51646]
## Reproduction:

1). Hit by wizard staff of changing, resulted in my player character becoming a syndicate medical borg.
2). Attempted to use a borg charger on the station (out of habit) immediately server crashed on button press. Forgot my battery was already full/infinite.

 I assume it's an interaction between the near-infinite battery the borg already has and the station power grid.

**Comment by ivanmixo** [comment]
If you were playing on terry/eu event hall it was probably coincidental since it's been having stability issues for a couple days now.

**Comment by timothymtorres** [comment]
Pretty sure this was just a normal server crash and nothing to do with borg or syndicate code.  I don't see any similar issue report opened so I'm marking this as cleanup.
