### ISSUE TITLE
Didn't receive hardcore random points after surviving full round

### ISSUE THREAD

**Issue by nwarz** [tgstation/tgstation#51651]
Issue reported from  Round ID: [139573](https://scrubby.melonmesa.com/round/139573) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1512

I played a hardcore random character and survived the shuttle ride back to Centcom. When the round ended I was not listed as a surviving hardcore random character on the round end report. I readied up before the round started, didn't latejoin. I didn't die at any point during the round and ended it in the same body I started in. The only long-term changes to my character were using a hulk injector and gaining neural traumas from a brain tumor.

**Comment by ATH1909** [comment]
Were you in the red zone of the shuttle when it docked at centcomm?

**Comment by nwarz** [comment]
I was just in the passenger section. It looks like this is happening consistently, just survived and made it to Centcom as a hardcore random player in round 139599, no hardcore random points awarded.

**Comment by Michael-Ashfield** [comment]
Confirming this is still an issue as of round 142764 as the same thing has happened to me.

**Comment by spessbro** [comment]
yup still a thing
