### ISSUE TITLE
Heretics: Mansus Grasp and Blood siphon have no cooldown when used at range.

### ISSUE THREAD

**Issue by Dezupher** [tgstation/tgstation#51661]
## Reproduction: 
Be a heretic and attempt to use either the Mansus Grasp or Blood Siphon spells at range on the floor or a person. 

The spell will not go on cooldown, has a ton of range and can be used to damage and kill people as fast as you can click.

Video: https://streamable.com/zldydd

**Comment by ExcessiveUseOfCobblestone** [comment]
@EdgeLordExe

**Comment by Kaffe-work** [comment]
@EdgeLordExe why doesn't your names follow standards :(

**Comment by Tlaltecuhtli** [comment]
shouldnt these spells be child of
https://github.com/tgstation/tgstation/blob/add74bee56cfde91602eb8ee28e3cae5959bc4f6/code/modules/spells/spell_types/touch_attacks.dm#L1

if they are supposed to be a touch?

**Comment by ATH1909** [comment]
oh god oh fuck

**Comment by EdgeLordExe** [comment]
aaaaa pr should be open in 11 hours when u wakr up
