### ISSUE TITLE
Traitor panel heretic button does not spawn required items

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#51669]
## Reproduction:
Give someone the heretic antagonist via  their traitor panel, no items spawn. Should have Codex Cicatrix and Living Heart.

**Comment by kriskog** [comment]
@EdgeLordExe

**Comment by EdgeLordExe** [comment]
there is an equip button

**Comment by kriskog** [comment]
I have since been informed of the equip button, though this should just be moved into the assignment. Everything else does it, and you cant really be a heretic without the gear so its just an extra pointless click.

**Comment by Angustmeta** [comment]
Achshually cult doesn't autogive dagger and metal either

**Comment by kriskog** [comment]
Huh, you are right. With cult you are able to summon the dagger though, and metal isnt a hard requirement.

**Comment by tralezab** [comment]
it's a solo antag just give the goddamn items

**Comment by EdgeLordExe** [comment]
siemanko

**Comment by Dorsisdwarf** [comment]
Traitor panel make-antag buttons do not give you kit under any other circumstances as far as I'm aware, they always have a seperate button to equip the new antag
