### ISSUE TITLE
Manus Grasp (Heretic) does not stun players who are buckled into Janicarts, making players on vehicles functionally immune.

### ISSUE THREAD

**Issue by Quietly12** [tgstation/tgstation#51678]
Issue reported from  Round ID: [139705](https://scrubby.melonmesa.com/round/139705) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1524

**Comment by EdgeLordExe** [comment]
Mansus grasp causes severe stamina damage and knockdown, not the actual stun. If you are buckled into something you wont be knocked down (since you are buckled). but stamina damage is still applied
