### ISSUE TITLE
Ghost orbit UI lacks scroll feature

### ISSUE THREAD

**Issue by Kaffe-work** [tgstation/tgstation#51672]
## Round ID: [139670](https://scrubby.melonmesa.com/round/139670)

The ghosts orbit menu doesn't scroll if there are too many entries, here there are 87, and it is overflowing, essentially i cant see whoever is after a certain number due to lack of scaling/scroll feature.

To reproduce: be ghost on highpop server, caused by #51585

[Image](https://gyazo.com/67d20b76f87c50f992e00a8532191fab)

**Comment by Jared-Fogle** [comment]
Do you mean no scroll bar or you can't scroll at all?

If the former, true but that would be a problem with tgui in general. Not sure if any other tgui menus necessitated scrolling.

If the latter, then you're wrong.

![USqMPT1Hk2](https://user-images.githubusercontent.com/35135081/84734514-ed81a900-af55-11ea-8de0-4257e2bf7aeb.gif)

**Comment by Kaffe-work** [comment]
no scrollbar, my mouse wheel is disabled due to oversensitivity, can't use page up/down/arrows to scroll either

**Comment by Jared-Fogle** [comment]
Fair then--I can look into seeing how I'd add a scroll bar to tgui.
