### ISSUE TITLE
Stacked ore redemption machines multiply ore refining.

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#51671]
Title, ORMs on top of eachother can refine the same pile of ore individually, resulting in a multiplier for how many ORMs there are on the tile.
### Reproduction:
- Get several machine frames built on the same tile (Bluespace/other game mechanic gimmickery)
- Build ORMs out of all of them
- Dump a satchel/crate of ore on the input tile of all the ORMs (Do not directly add ore to an ORM, this might not work with ore crates either, only when picking up ore off the ground.)
- Every ORM now has its own stack of refined resources, enjoy being rich and going full cargonia

Linking them all to an ore silo is reccomended to save time.

> Superior communist machines vs the lowly upgraded capitalist systems.

**Comment by ShizCalev** [comment]
Thanks for the detailed report.
