### ISSUE TITLE
You can shortloop a stacking machine to create infinite resources and other oddities.

### ISSUE THREAD

**Issue by GravitronBlue** [tgstation/tgstation#51674]
Title, causing a stacking machine to output into itself can result in duplicated materials and other buggy behavior.

### Reproduction:
- Get a hand teleporter, bluespace beacon, and a stacking machine linked to a stacking console.
- place the bluespace beacon on the input tile of the stacking machine
- open a bluespace portal on the output (west) side of the stacking maching so that it connects directly to the input (east) side.
- Throw a full stack of 50 sheets of whatever into the output portal side so that it lands on input side.
- The stacking machine now has 700 (or more) sheets of whatever you threw in along with a qdeleted stack of what you threw in sitting on the input side. (You also get a sweet Runtime error too, neat!)

![RealityCasualty](https://user-images.githubusercontent.com/17460297/84724476-25302700-af3d-11ea-9b0f-a7036a2e2797.PNG)

```
runtime error: Maximum recursion level reached (perhaps there is an infinite loop)
To avoid this safety check, set world.loop_checks=0.
proc name: Destroy (/datum/timedevent/Destroy)
  usr: -SNIP- (/mob/living/carbon/human)
  src: Timer: -1 (\[0x210291e4]), TTR... (/datum/timedevent)
  usr.loc: the floor (111,141,2) (/turf/open/floor/plasteel)
  call stack:
Timer: -1 (\[0x210291e4]), TTR... (/datum/timedevent): Destroy(0)
qdel(Timer: -1 (\[0x210291e4]), TTR... (/datum/timedevent), 0)
the solid plasma (/obj/item/stack/sheet/mineral/plasma): Destroy(0)
the solid plasma (/obj/item/stack/sheet/mineral/plasma): Destroy(0)
the solid plasma (/obj/item/stack/sheet/mineral/plasma): Destroy(0)
the solid plasma (/obj/item/stack/sheet/mineral/plasma): Destroy(0)
the solid plasma (/obj/item/stack/sheet/mineral/plasma): Destroy(0)
the solid plasma (/obj/item/stack/sheet/mineral/plasma): Destroy(0)
the solid plasma (/obj/item/stack/sheet/mineral/plasma): Destroy(0)
the solid plasma (/obj/item/stack/sheet/mineral/plasma): Destroy(0)
...
the solid plasma (/obj/item/stack/sheet/mineral/plasma): doMove(the floor 
```
As for results, here's what throwing in most full sheet stacks from the 'every resource closet' looks like, also this resulted in a hefty amount of lag and slowdown, possibly a crash risk if enough was being looped.
(Which is a possible edge case issue with stacking machines feeding into eachother, though not normally possible outside of varedit or maybe a machine mapped to output on opposite sides.)

![MONEY](https://user-images.githubusercontent.com/17460297/84724643-83f5a080-af3d-11ea-9d53-737f10c47e73.PNG)

Breaking the machine afterwards results in sheet stacks well above the normal cap.

![Muchmoney](https://user-images.githubusercontent.com/17460297/84724657-8e179f00-af3d-11ea-81c9-e0d15c540439.PNG)

> And you thought infinite summon guns was just a spell for wizards.

**Comment by ShizCalev** [comment]
Thanks for the detailed report.
