### ISSUE TITLE
Unsynched borgs sometimes show up as synched even while they are not

### ISSUE THREAD

**Issue by Kaffe-work** [tgstation/tgstation#51682]
## Testmerges:
#51412: 'Adds rotation support to the maploader ' by kevinz000 at commit be50d0d984
#50981: 'Completely disables papercode' by optimumtact at commit c21fde5f17

## Reproduction:

no idea what occured here, my borgs seemed synched according to my status bar. then i got disconnected and beat up by a borg acting on asimov laws.

[Image](https://gyazo.com/b204283db5b797a44e6b98ac25b82e4f)

**Comment by Dorsisdwarf** [comment]
After reviewing the logs, I believe what happened here is that a particularly sneaky roboticist set the borg he made from an MMI up so that its AI-sync was on (So it seemed to be yours) but its LAW sync was _off_, so when you revealed your plan he told it to kill you.

**Comment by Kaffe-work** [comment]
ive had some more similar issues, (as both) but it might be the same.
