### ISSUE TITLE
You can move the heretic reality tears with telekenesis, hide them, space them

### ISSUE THREAD

**Issue by Robustitron** [tgstation/tgstation#51695]
## Testmerges:

#51412: 'Adds rotation support to the maploader ' by kevinz000 at commit be50d0d984
#51515: 'A New Medbay for Boxstation' by Maurukas at commit 987b7a9a22

## Reproduction:
1) get tk
2) find reality tear
3) grab with tk
4) throw it around like its a chair or something 
5) throw it right out into space

I don't think I was able to do this with my hands so I'm assuming this is a bug.

**Comment by kopoba** [comment]
you can also transport them with crate

**Comment by Doosteroni** [comment]
Feature everyone knows reality bends to genetics
