### ISSUE TITLE
Bags of Holding and Reaching Z-Level One

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#51711]
## Testmerges:
#51412 
#51515 

## Reproduction:
Done on Delta station,
1. put a teleporter beacon on the white ship, having the ship docked at the station
2. wear a bag of holding
3. go through a teleporter to the white ship, with the bag of holding on
4. somehow end up on z-level one, unable to escape

**Comment by ATH1909** [comment]
what is z-level 1?

**Comment by Paxilmaniac** [comment]
i think it's centcom, if i remember correctly

**Comment by Doosteroni** [comment]
If you go by the wiznerd ship some funhater put a hyperspace border there so being inescapable is inaccurate

**Comment by Paxilmaniac** [comment]
i was able to reproduce the bug easily, just teleport to a shuttle in motion while wearing a boh, and you will be teleported to places you arent supposed to go

**Comment by Paxilmaniac** [comment]
cv cvdbvbvbdvbfdb cd, v bbscsbddbdvbfscccfabbd. d cd vdbdfdbcbcbd vdvvdbccsvbd cdc d b sex dbbcbbvbd sf vbbv dbddfc d s a d decreed s dds!,;?:! d vf dc ccc ssd d ssd dvsbdnd sddd dds d cdc cdd dad dds f dad dad zac feed  cd ds ssd dad dvbcc db bb dec d d versed cdc dsv deed x frr sfc d cds dress ssd dad d dad dress dressed d cds decreed cdc d d c cdc decreed c dads ds dds c cds d decreed dads dress dress d d  dads drxxxdd BCZcnn

**Comment by GravitronBlue** [comment]
Possibly related to #45529

**Comment by Fikou** [comment]
Duplicate of #45529
