### ISSUE TITLE
Cats being automuted for ventcrawling

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#51712]
## Round ID:
#139826

## Testmerges:
#51412: 'Adds rotation support to the maploader ' by kevinz000 at commit be50d0d984
#51515: 'A New Medbay for Boxstation' by Maurukas at commit 987b7a9a22

## Reproduction:
Spawned in a player controlled cake cat, they crawled into a scrubber and then they got IC muted while crawling around, unmuting them just repeatedly muted them again.

**Comment by ivanmixo** [comment]
I can't replicate it on a private server, seems to be working fine. 

Just to clarify, you mean the /mob/living/simple_animal/cat/cak , right?

**Comment by optimumtact** [comment]
this is due to voice of god

**Comment by Mooshimi** [comment]
> this is due to voice of god

Supposedly fixed Jan 1st, 2020, which is before this issue was made by many months. What else is wrong with VoG?

**Comment by Sealed101** [comment]
tested with admin help on round 238858 (sobs in lack of public logs) and could not replicate; VoG or no VoG
also the round linked in the issue is a wack-ass 3-person-total round on a map called Ball Map. what?
