### ISSUE TITLE
blob cant hit people lying down

### ISSUE THREAD

**Issue by MichaelCSturm** [tgstation/tgstation#51724]
Issue reported from  Round ID: [139863](https://scrubby.melonmesa.com/round/139863) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1505

**Comment by Time-Green** [comment]
Tell the blob to stand-up. You generally can't attack others while lying down IIRC

**Comment by ivanmixo** [comment]
What do you mean? Do you mean it can't hit a human that's lying down (if so it's just plain out wrong since you can) or do you mean if the blob lies down(How the hell do you lay down as a blob?)

**Comment by Time-Green** [comment]
Make a new issue with a ‘steps-to-reproduce’ or at least a body
