### ISSUE TITLE
Heretics Summons Count as Alive if they Die and become a different Ghost Role

### ISSUE THREAD

**Issue by Taylorkills2** [tgstation/tgstation#51727]
## Reproduction:
Make a ghoul, kill them, have the ghoul player become another ghost role. You now cannot make any more ghouls unless the former ghoul player dies again.

Found this in a round where I was a heretic, made a xenobiologist a ghoul, he made golems, I killed the xenobiologist and they became a ghostrole golem aligned with me. The ability then told me I couldn't make any more ghouls since my ghoul was still alive, despite the fact I quite clearly gibbed them by sacrificing them with a living heart.

**Comment by ShizCalev** [comment]
@EdgeLordExe

**Comment by EdgeLordExe** [comment]
@ShizCalev https://github.com/tgstation/tgstation/pull/51676 a collection of bugfixes , also this one.
