### ISSUE TITLE
Surgery operating computers dont work on box

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#51722]
## Round ID:
#139858

## Testmerges:
#51412: 'Adds rotation support to the maploader ' by kevinz000 at commit be50d0d984
#51515: 'A New Medbay for Boxstation' by Maurukas at commit 987b7a9a22

## Reproduction:
See title, both surgery room consoles weren't detecting the corpse while it was on the surgery table. Nor did resetting the console with a screwdriver work either.
![Capture](https://user-images.githubusercontent.com/32374784/84999310-d681b900-b105-11ea-8855-85ceb5b878fb.PNG)

**Comment by Maurukas** [comment]
I'm not able to immediately reproduce this locally, but I will try again after I resolve the current merge conflicts.

**Comment by ShizCalev** [comment]
@Maurukas try with #51515 merged

**Comment by Maurukas** [comment]
@ShizCalev I am doing so, that is my PR.

**Comment by ShizCalev** [comment]
@Maurukas Er, sorry, meant #51412

**Comment by dragomagol** [comment]
Unable to reproduce.
