### ISSUE TITLE
Reagents not showing properly in plants when they react after harvest.

### ISSUE THREAD

**Issue by KathyRyals** [tgstation/tgstation#51725]
Issue reported from  Round ID: [139860](https://scrubby.melonmesa.com/round/139860) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1525

![image](https://user-images.githubusercontent.com/65850818/85016696-8983fe00-b16a-11ea-90bd-d7fb3d32febe.png)

**Comment by KathyRyals** [comment]
![image](https://user-images.githubusercontent.com/65850818/85016731-9a347400-b16a-11ea-91d7-d966c885ca46.png)
This is the seed used.

**Comment by ArcaneMusic** [comment]
Oversight which I was running into this week as well, the plant analyzer doesn't send to_chat the actual chemicals within the plant, but instead exclusively the chemicals from it's genes.
