### ISSUE TITLE
Holy Water Explosion Just Doesn't Work.

### ISSUE THREAD

**Issue by Pugie** [tgstation/tgstation#51748]
Title, tested recently and has been a bug for a while. Holy water explosion doesn't seem to be any bigger than regular potassium and water, also doesn't set cultists on fire or stun & reveal revenants.

**Comment by ArcaneDefence** [comment]
Seemed fully functional for me in using a reaction of 150/150 pot/holy water and a 300/300 one. 

The igniting cultists is a little delayed from `addtimer(CALLBACK(src, .proc/divine_explosion, round(created_volume/48,1),get_turf(holder.my_atom)), 2 SECONDS)`, but I noticed it quite clearly with the larger reaction by standing on the opposite side of a firelock to prevent the breaches from extinguishing me.

**Comment by ATH1909** [comment]
did you use enough holy water and/or potassium?
