### ISSUE TITLE
you can't sacrifice stuff on the sacrificial altars in the fountain of healing ruin

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#51746]
clicking on the altar unbuckles any mobs from it before it checks for any buckled mobs to sacrifice, so you can never sacrifice anything on the altars in that ruin

**Comment by Fikou** [comment]
there is no difference between those altars and altars on station

**Comment by ATH1909** [comment]
```
/obj/structure/sacrificealtar
	name = "sacrificial altar"
	desc = "An altar designed to perform blood sacrifice for a deity."
	icon = 'icons/obj/hand_of_god_structures.dmi'
	icon_state = "sacrificealtar"
	anchored = TRUE
	density = FALSE
	can_buckle = 1

/obj/structure/sacrificealtar/attack_hand(mob/living/user)
	. = ..()
	if(.)
		return
	if(!has_buckled_mobs())
		return
	var/mob/living/L = locate() in buckled_mobs
	if(!L)
		return
	to_chat(user, "<span class='notice'>You attempt to sacrifice [L] by invoking the sacrificial ritual.</span>")
	L.gib()
	message_admins("[ADMIN_LOOKUPFLW(user)] has sacrificed [key_name_admin(L)] on the sacrificial altar at [AREACOORD(src)].")
```

**Comment by ATH1909** [comment]
they use the same SPRITE, sure, but they're different structures

**Comment by ATH1909** [comment]
![image](https://user-images.githubusercontent.com/42606352/85460709-28dd3280-b569-11ea-9d82-b99c2ef67e76.png)

**Comment by ATH1909** [comment]
@Fikou i can't believe that you would make a claim without factchecking it first like that im literally shaking and crying right now

**Comment by ArcaneDefence** [comment]
You fixed this and didn't even close it
