### ISSUE TITLE
Hop console bug

### ISSUE THREAD

**Issue by Ikoden** [tgstation/tgstation#51759]
I get 404 website not found error a lot when I'm using hop console. It mainly happens when I put my ID in and log in.

**Comment by ATH1909** [comment]
can confirm that I get this a lot too

**Comment by Ikoden** [comment]
Also would like to say that I had this bug for like weeks, but somehow didn't think of reporting it because I got used to it so much.

**Comment by Kaffe-work** [comment]
same, just press F5

**Comment by Sealed101** [comment]
this wouldn't seem to be a specific issue on the code side but rather an issue on the user's side - tgui fucking up may have many causes and the best point to start is clicking the window that doesn't load and hitting f5 or alt + f4 if desperate. proceeding to clear byond and internet explorer cache would be the next two steps. any additional advanced methods would probably involve a more thorough cleaning or detailed software fixes which should be asked about on the discord at least.
