### ISSUE TITLE
Armanents beacon bug

### ISSUE THREAD

**Issue by Ikoden** [tgstation/tgstation#51756]
If you click armanents beacon on ChapDrobe it disappears completely.

**Comment by ivanmixo** [comment]
Hmmm, this also happens with all the wardrobes. I'll see if I can fix it.

**Comment by ATH1909** [comment]
UM

**Comment by ATH1909** [comment]
> Hmmm, this also happens with all the wardrobes. I'll see if I can fix it.

UM

please fix this before the ball, thank you

**Comment by ATH1909** [comment]
wait, ikoden, when you say "it", what are you referring to?

**Comment by Ikoden** [comment]
> 
> 
> wait, ikoden, when you say "it", what are you referring to?

I mean the armanents beacon.

**Comment by Fikou** [comment]
are you sure it didn't go in the part of the vendor that allows for reclamation of items

**Comment by Ikoden** [comment]
All I know is that the armanents beacon disapppeared and there wasn't any available one in ChapDrobe.

**Comment by timothymtorres** [comment]
Closing this since the behavior of the beacon deleting itself is intended.
