### ISSUE TITLE
Docker machine broke

### ISSUE THREAD

**Issue by Hamcha** [tgstation/tgstation#51752]
Dockerfile is broken because BSQL got bwoinked, also the BYOND version is way outdated.

[My fork](https://github.com/Hamcha/crstation) has a fixed version (along a docker-compose setup for having a SQL database running alongside it) but it relies on my own fork of [byond-docker](https://hub.docker.com/u/hamcha/byond-docker) since the `tgstation/byond` image has not been updated in a while, so I think it might be worth updating that image on the hub before making a PR or something.

Dunno how much you care about this, on the discord it seemed I was the only one who uses this setup.

**Comment by 81Denton** [comment]
@Cyberboss

**Comment by Cyberboss** [comment]
Yeah I need to make byond-docker auto-update
