### ISSUE TITLE
Chaplain's holy book does not heal various "new" medical statuses

### ISSUE THREAD

**Issue by Quietly12** [tgstation/tgstation#51768]
Issue reported from  Round ID: [139994](https://scrubby.melonmesa.com/round/139994) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])
Reporting client version: 513.1524

Expected behavior is for it to heal everything (its _holy magic_ aint gotta explain shit). Current behavior only seems to heal limb damage, and should be updated to resolve the many new types of medical damage that exist now as the book has not been updated since the game was only limb damage types.

Checking
`/code/game/objects/items/storage/book.dm`
the code
`var/heal_amt = 10
	var/list/hurt_limbs = H.get_damaged_bodyparts(1, 1, null, BODYPART_ORGANIC)

	if(hurt_limbs.len)
		for(var/X in hurt_limbs)
			var/obj/item/bodypart/affecting = X
			if(affecting.heal_damage(heal_amt, heal_amt, null, BODYPART_ORGANIC))
				H.update_damage_overlays()`

I'm not fully familiar with ss13 code yet, but this looks like it also was neglecting toxins, which have been in the game much longer.

**Comment by LemonInTheDark** [comment]
Not healing toxins is for sure intentional, I think healing wounds is an interesting idea, but it would have to be balanced against medical
