### ISSUE TITLE
paper fillable field do not save when the save button is clicked

### ISSUE THREAD

**Issue by joybod** [tgstation/tgstation#51774]
Issue reported from  Round ID: [140017](https://scrubby.melonmesa.com/round/140017) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

while I am not sure if this is intended or not, it feels like the save button should save edits made to fields filled out in the preview tab.

signed- a HoP dying of lack of ability to force the crew to do paperwork

**Comment by timothymtorres** [comment]
This may have been fixed with #54979 but I'm not sure

**Comment by joybod** [comment]
> This may have been fixed with #54979 but I'm not sure

A while ago, yes
