### ISSUE TITLE
List of items with missing icons when worn on belt, back, or suit

### ISSUE THREAD

**Issue by TaG2e** [tgstation/tgstation#51776]
As per request of @ShizCalev, here is a list of items that can be worn and are showing the missing icon sprite. Though note only the belt, back, and suit items were tracked. Inhands and other slots were not tracked, so it's possible there are other items missing sprites.

Also under belt_mirror, the /obj/item/melee/* is solely due to /obj/item/clothing/suit/captunic

This info is dated **6/28/2020** and was found by tracking:
slot_flags ITEM_SLOT_BELT and ITEM_SLOT_BACK
/obj/item/clothing/suit/*    allowed = list(...)

<details>
<summary>inhands</summary>

- [ ] /obj/item/gun/energy/lasercannon(0,1,2,3,4)
- [ ] /obj/item/gun/ballistic/shotgun/doublebarrel(dshotgun_sawn)
- [ ] /obj/item/gun/ballistic/shotgun/riot(riotshotgun_sawn)
- [ ] /obj/item/gun/ballistic/shotgun/doublebarrel/hook

</details>

<details>
<summary>neck.dmi</summary>

- [ ] /obj/item/clothing/neck/necklace/memento_mori

</details>

<details>
<summary>mask.dmi</summary>

- [ ] /obj/item/instrument/harmonica

</details>

<details>
<summary>back.dmi</summary>

- [ ] /obj/item/gun/energy/pulse(kill0,25,50,75,100 stun0,25,50,75,100)
- [ ] /obj/item/gun/ballistic/shotgun/doublebarrel/hook
- [ ] /obj/item/bikehorn
- [ ] /obj/item/bikehorn/airhorn
- [ ] /obj/item/bikehorn/golden
- [ ] /obj/item/bikehorn/rubberducky
- [ ] /obj/item/bikehorn/rubberducky/plasticducky
- [ ] /obj/item/nullrod/pride_hammer
- [ ] /obj/item/singularityhammer
- [ ] /obj/item/mjollnir
- [ ] /obj/item/kinetic_crusher
- [ ] /obj/item/gun/magic/staff 
- [ ] /obj/item/gun/magic/staff/locker
- [ ] /obj/item/gun/magic/staff/flying
- [ ] /obj/item/gun/magic/staff/sapping
- [ ] /obj/item/gun/magic/staff/necropotence
- [ ] /obj/item/gun/magic/staff/wipe
- [ ] /obj/item/shield/adamantineshield

</details>

<details>
<summary>belt.dmi</summary>

- [ ] /obj/item/gun/energy/ionrifle/carbine(0,25,50,75,100)
- [ ] /obj/item/gun/energy/pulse/carbine(DESTROY0,25,50,75,100 kill0,25,50,75,100 stun0,25,50,75,100)
- [ ] /obj/item/tank/internals/emergency_oxygen/double
- [ ] /obj/item/bikehorn
- [ ] /obj/item/bikehorn/airhorn
- [ ] /obj/item/bikehorn/golden
- [ ] /obj/item/bikehorn/rubberducky
- [ ] /obj/item/bikehorn/rubberducky/plasticducky
- [ ] /obj/item/airlock_painter
- [ ] /obj/item/airlock_painter/decal
- [ ] /obj/item/airlock_painter/decal/debug
- [ ] /obj/item/binoculars
- [ ] /obj/item/lighter
- [ ] /obj/item/lighter/greyscale
- [ ] /obj/item/lighter/slime
- [ ] /obj/item/flashlight
- [ ] /obj/item/flashlight/lamp
- [ ] /obj/item/flashlight/lamp/green
- [ ] /obj/item/flashlight/lamp/bananalamp
- [ ] /obj/item/flashlight/flare
- [ ] /obj/item/flashlight/latern
- [ ] /obj/item/flashlight/latern/heirloom_moth
- [ ] /obj/item/flashlight/latern/jade
- [ ] /obj/item/flashlight/latern/syndicate
- [ ] /obj/item/flashlight/slime
- [ ] /obj/item/flashlight/emp
- [ ] /obj/item/flashlight/emp/debug
- [ ] /obj/item/flashlight/glowstick
- [ ] /obj/item/flashlight/glowstick/red
- [ ] /obj/item/flashlight/glowstick/blue
- [ ] /obj/item/flashlight/glowstick/cyan
- [ ] /obj/item/flashlight/glowstick/orange
- [ ] /obj/item/flashlight/glowstick/yellow
- [ ] /obj/item/flashlight/glowstick/pink
- [ ] /obj/item/flashlight/flashdark
- [ ] /obj/item/flashlight/eyelight
- [ ] /obj/item/geiger_counter
- [ ] /obj/item/geiger_counter/cyborg
- [ ] /obj/item/lightreplacer
- [ ] /obj/item/lightreplacer/cyborg
- [ ] /obj/item/radio
- [ ] /obj/item/radio/off
- [ ] /obj/item/radio/borg
- [ ] /obj/item/radio/borg/syndicate
- [ ] /obj/item/nanite_scanner
- [ ] /obj/item/grenade
- [ ] /obj/item/grenade/antigravity
- [ ] /obj/item/grenade/barrier
- [ ] /obj/item/grenade/chem_grenade
- [ ] /obj/item/grenade/chem_grenade/*
- [ ] /obj/item/grenade/clusterbuster
- [ ] /obj/item/grenade/clusterbuster/*
- [ ] /obj/item/grenade/flashbang
- [ ] /obj/item/grenade/flashbang/cluster
- [ ] /obj/item/grenade/empgrenade
- [ ] /obj/item/grenade/firecracker
- [ ] /obj/item/grenade/stingbang
- [ ] /obj/item/grenade/stingbang/*
- [ ] /obj/item/grenade/primer
- [ ] /obj/item/grenade/primer/stingbang
- [ ] /obj/item/grenade/iedcasing
- [ ] /obj/item/grenade/iedcasing/spawned
- [ ] /obj/item/grenade/hypnotic
- [ ] /obj/item/grenade/c4
- [ ] /obj/item/grenade/c4/x4
- [ ] /obj/item/grenade/smokebomb
- [ ] /obj/item/grenade/spawnergrenade
- [ ] /obj/item/grenade/spawnergrenade/*
- [ ] /obj/item/grenade/syndieminibomb
- [ ] /obj/item/grenade/syndieminibomb/concussion
- [ ] /obj/item/grenade/frag
- [ ] /obj/item/grenade/frag/mega
- [ ] /obj/item/grenade/gluon
- [ ] /obj/item/nullrod/claymore/darkblade
- [ ] /obj/item/nullrod/claymore/chainsaw_sword
- [ ] /obj/item/nullrod/claymore/glowing
- [ ] /obj/item/nullrod/claymore/multiverse
- [ ] /obj/item/nullrod/claymore/saber
- [ ] /obj/item/nullrod/claymore/saber/red
- [ ] /obj/item/nullrod/claymore/saber/pirate
- [ ] /obj/item/nullrod/sord
- [ ] /obj/item/sord
- [ ] /obj/item/nullrod/scythe/talking/chainsword
- [ ] /obj/item/nullrod/hammmer
- [ ] /obj/item/nullrod/whip
- [ ] /obj/item/melee/curator_whip
- [ ] /obj/item/melee/chainofcommand
- [ ] /obj/item/melee/chainofcommand/tailwhip
- [ ] /obj/item/melee/chainofcommand/tailwhip/kitty
- [ ] /obj/item/key/lasso
- [ ] /obj/item/nullrod/hypertool
- [ ] /obj/item/nullrod/spear
- [ ] /obj/item/melee/classic_baton/telescopic
- [ ] /obj/item/melee/classic_baton/telescopic/contractor_baton
- [ ] /obj/item/melee/roastingstick
- [ ] /obj/item/melee/cleric_mace
- [ ] /obj/item/construction/rcd
- [ ] /obj/item/construction/rcd/*
- [ ] /obj/item/construction/rld
- [ ] /obj/item/construction/rld/mini
- [ ] /obj/item/pipe_dispenser
- [ ] /obj/item/storage/bag
- [ ] /obj/item/storage/bag/*
- [ ] /obj/item/storage/box/matches
- [ ] /obj/item/storage/fancy/candle_box
- [ ] /obj/item/storage/fancy/cigarettes
- [ ] /obj/item/storage/fancy/cigarettes/cigars
- [ ] /obj/item/storage/fancy/cigarettes/cigars/*
- [ ] /obj/item/storage/fancy/cigarettes/cigpack_*
- [ ] /obj/item/storage/fancy/cigarettes/dromedaryco
- [ ] /obj/item/banhammer
- [ ] /obj/item/soulstone
- [ ] /obj/item/soulstone/*
- [ ] /obj/item/secateurs
- [ ] /obj/item/geneshears
- [ ] /obj/item/shovel
- [ ] /obj/item/shovel/serrated
- [ ] /obj/item/shovel/spade
- [ ] /obj/item/melee/transforming/cleaving_saw
- [ ] /obj/item/melee/transforming/cleaving_saw/miner
- [ ] /obj/item/modular_computer/tablet
- [ ] /obj/item/modular_computer/tablet/*
- [ ] /obj/item/clipboard
- [ ] /obj/item/ammo_casing
- [ ] /obj/item/ammo_casing/*
- [ ] /obj/item/ammo_box
- [ ] /obj/item/ammo_box/*
- [ ] /obj/item/reagent_containers/hypospray
- [ ] /obj/item/reagent_containers/hypospray/medipen
- [ ] /obj/item/reagent_containers/hypospray/medipen/*
- [ ] /obj/item/reagent_containers/hypospray/combat
- [ ] /obj/item/reagent_containers/hypospray/combat/nanites
- [ ] /obj/item/reagent_containers/hypospray/combat/heresypurge
- [ ] /obj/item/reagent_containers/hypospray/CMO
- [ ] /obj/item/reagent_containers/medigel
- [ ] /obj/item/reagent_containers/medigel/*
- [ ] /obj/item/reagent_containers/spray
- [ ] /obj/item/reagent_containers/spray/*
- [ ] /obj/item/destTagger
- [ ] /obj/item/destTagger/borg
- [ ] /obj/item/sales_tagger
- [ ] /obj/item/uplink
- [ ] /obj/item/uplink/*

</details>

<details>
<summary>belt_mirror.dmi</summary>

- [ ] /obj/item/melee/baton/cattleprod
- [ ] /obj/item/gun/energy/lasercannon(0,25,50,75,100)
- [ ] /obj/item/gun/energy/ionrifle/carbine(0,25,50,75,100)
- [ ] /obj/item/gun/energy/pulse(DESTROY0,25,50,75,100 kill0,25,50,75,100 stun0,25,50,75,100)
- [ ] /obj/item/gun/energy/pulse/carbine(DESTROY0,25,50,75,100 kill0,25,50,75,100 stun0,25,50,75,100)
- [ ] /obj/item/gun/ballistic/rifle/boltaction
- [ ] /obj/item/gun/ballistic/automatic/surplus
- [ ] /obj/item/gun/ballistic/automatic/sniper_rifle
- [ ] /obj/item/tank/internals/emergency_oxygen/double
- [ ] /obj/item/crowbar
- [ ] /obj/item/nullrod/staff
- [ ] /obj/item/nullrod/claymore
- [ ] /obj/item/nullrod/scythe
- [ ] /obj/item/claymore
- [ ] /obj/item/pickaxe
- [ ] /obj/item/gun/ballistic/shotgun
- [ ] /obj/item/gun/ballistic/shotgun/*
- [ ] /obj/item/bikehorn
- [ ] /obj/item/bikehorn/airhorn
- [ ] /obj/item/bikehorn/golden
- [ ] /obj/item/bikehorn/rubberducky
- [ ] /obj/item/bikehorn/rubberducky/plasticducky
- [ ] /obj/item/instrument
- [ ] /obj/item/instrument/*
- [ ] /obj/item/reagent_containers/food/snacks/pie/cream
- [ ] /obj/item/reagent_containers/food/snacks/grown/banana
- [ ] /obj/item/grown/bananapeel
- [ ] /obj/item/megaphone/clown
- [ ] /obj/item/soap
- [ ] /obj/item/soap/*
- [ ] /obj/item/reagent_containers/food/drinks/soda_cans/canned_laughter
- [ ] /obj/item/toy/crayon
- [ ] /obj/item/toy/crayon/spraycan
- [ ] /obj/item/toy/crayon/spraycan/lubecan
- [ ] /obj/item/analyzer
- [ ] /obj/item/tank/internals/plasma
- [ ] /obj/item/storage/book/bible
- [ ] /obj/item/storage/book/bible/booze
- [ ] /obj/item/storage/book/bible/syndicate
- [ ] /obj/item/nullrod
- [ ] /obj/item/nullrod/* (w_class < 5 aka WEIGHT_CLASS_HUGE)
- [ ] /obj/item/reagent_containers/food/drinks/bottle/holywater
- [ ] /obj/item/reagent_containers/food/drinks/bottle/holywater/hell
- [ ] /obj/item/storage/fancy/candle_box
- [ ] /obj/item/candle
- [ ] /obj/item/candle/infinite
- [ ] /obj/item/flashlight
- [ ] /obj/item/flashlight/*
- [ ] /obj/item/tome
- [ ] /obj/item/melee/cultblade
- [ ] /obj/item/melee/cultblade/dagger
- [ ] /obj/item/melee/cultblade/ghost
- [ ] /obj/item/melee/sickly_blade
- [ ] /obj/item/melee/sickly_blade/*
- [ ] /obj/item/forbidden_book
- [ ] /obj/item/forbidden_book/debug
- [ ] /obj/item/construction/rcd
- [ ] /obj/item/pipe_dispenser
- [ ] /obj/item/resonator
- [ ] /obj/item/storage/bag/ore
- [ ] /obj/item/storage/bag/ore/*
- [ ] /obj/item/ammo_casing
- [ ] /obj/item/ammo_casing/*
- [ ] /obj/item/ammo_box
- [ ] /obj/item/ammo_box/*
- [ ] /obj/item/melee/transforming/energy/sword
- [ ] /obj/item/melee/transforming/energy/sword/*
- [ ] /obj/item/clothing/glasses/eyepatch
- [ ] /obj/item/reagent_containers/food/drinks/bottle/rum
- [ ] /obj/item/stack/spacecash
- [ ] /obj/item/stack/spacecash/*
- [ ] /obj/item/teleportation_scroll
- [ ] /obj/item/teleportation_scroll/apprentice
- [ ] /obj/item/storage/firstaid
- [ ] /obj/item/storage/firstaid/*
- [ ] /obj/item/stack/medical
- [ ] /obj/item/stack/medical/*
- [ ] /obj/item/circular_saw
- [ ] /obj/item/storage/box/pillbottles
- [ ] /obj/item/reagent_containers/pill
- [ ] /obj/item/reagent_containers/pill/*
- [ ] /obj/item/storage/pill_bottle
- [ ] /obj/item/storage/pill_bottle/*
- [ ] /obj/item/storage/bag/chemistry
- [ ] /obj/item/reagent_containers/glass/beaker
- [ ] /obj/item/reagent_containers/glass/beaker/*
- [ ] /obj/item/reagent_containers/glass/bottle
- [ ] /obj/item/reagent_containers/glass/bottle/*
- [ ] /obj/item/reagent_containers/glass/bucket
- [ ] /obj/item/reagent_containers/glass/bucket/*
- [ ] /obj/item/reagent_containers/dropper
- [ ] /obj/item/reagent_containers/syringe
- [ ] /obj/item/reagent_containers/syringe/*
- [ ] /obj/item/reagent_containers/hypospray
- [ ] /obj/item/reagent_containers/hypospray/*
- [ ] /obj/item/reagent_containers/spray/chemsprayer/janitor
- [ ] /obj/item/reagent_containers/spray/pestspray
- [ ] /obj/item/reagent_containers/spray/plantbgone
- [ ] /obj/item/kitchen/knife/combat
- [ ] /obj/item/kitchen/knife/combat/*
- [ ] /obj/item/multitool
- [ ] /obj/item/multitool/*
- [ ] /obj/item/storage/bag/trash
- [ ] /obj/item/storage/bag/trash/*
- [ ] /obj/item/melee/flyswatter
- [ ] /obj/item/mop
- [ ] /obj/item/mop/*
- [ ] /obj/item/holosign_creator
- [ ] /obj/item/holosign_creator/*
- [ ] /obj/item/pneumatic_cannon/speargun
- [ ] /obj/item/banner
- [ ] /obj/item/banner/*
- [ ] /obj/item/spear
- [ ] /obj/item/spear/*
- [ ] /obj/item/organ/regenerative_core/legion
- [ ] /obj/item/plant_analyzer
- [ ] /obj/item/seeds
- [ ] /obj/item/seeds/*
- [ ] /obj/item/cultivator
- [ ] /obj/item/cultivator/rake
- [ ] /obj/item/hatchet
- [ ] /obj/item/hatchet/*
- [ ] /obj/item/storage/bag/plants
- [ ] /obj/item/storage/bag/plants/portaseeder
- [ ] /obj/item/graft
- [ ] /obj/item/secateurs
- [ ] /obj/item/geneshears
- [ ] /obj/item/kitchen
- [ ] /obj/item/kitchen/*
- [ ] /obj/item/radio
- [ ] /obj/item/radio/*
- [ ] /obj/item/scalpel
- [ ] /obj/item/surgical_drapes
- [ ] /obj/item/cautery
- [ ] /obj/item/hemostat
- [ ] /obj/item/retractor
- [ ] /obj/item/melee/curator_whip
- [ ] /obj/item/paper
- [ ] /obj/item/paper/*
- [ ] /obj/item/melee/classic_baton/telescopic
- [ ] /obj/item/toy
- [ ] /obj/item/toy/*
- [ ] /obj/item/clothing/mask/facehugger/toy
- [ ] /obj/item/spellbook
- [ ] /obj/item/disk
- [ ] /obj/item/stamp
- [ ] /obj/item/reagent_containers/food/drinks/flask
- [ ] /obj/item/melee
- [ ] /obj/item/melee/* (w_class < 5 aka WEIGHT_CLASS_HUGE)
- [ ] /obj/item/storage/lockbox/medal
- [ ] /obj/item/storage/lockbox/medal/*
- [ ] /obj/item/assembly/flash/handheld
- [ ] /obj/item/storage/box/matches
- [ ] /obj/item/lighter
- [ ] /obj/item/lighter/greyscale
- [ ] /obj/item/lighter/slime
- [ ] /obj/item/clothing/mask/cigarette
- [ ] /obj/item/storage/fancy/cigarettes
- [ ] /obj/item/gun/* (w_class < 5 aka WEIGHT_CLASS_HUGE)

</details>

**Comment by trexter555** [comment]
memento mori sprite is also fucked up though its on neck

**Comment by TaG2e** [comment]
Ah yeah I see what you mean, nice catch. I added to the list.

**Comment by ShizCalev** [comment]
#52390

**Comment by LemonInTheDark** [comment]
calm before the storm

**Comment by ArcaneMusic** [comment]
If at all possible, can we re-check this list with the new, fixed sprites? Many of these had been hit but none have been checked off here.
