### ISSUE TITLE
Synthflesh and rezadone does not unhusk patients after refactor

### ISSUE THREAD

**Issue by antropod** [tgstation/tgstation#51799]
I had patient today who turned into husk on my very eyes
I applied 270 units of synthflesh, it didn't unhusk him
I applied rezadone, it didn't work

It worked a day ago, and only change is this code

_Originally posted by @antropod in https://github.com/tgstation/tgstation/pull/51396#issuecomment-647860094_

**Comment by antropod** [comment]
Tested it on local server -- synthflesh does not work.
Rezadone does not work.
Strange reagent does not work.

**Comment by Mycah142** [comment]
I stand as witness, I was in a live game next to them. We tried Strange Reagent on two different bodies to zero reaction.

A body husked in front of us, we tried for half an hour to figure out any method or reason it wouldn't unhusk. Synthflesh, rezadone, nothing garnered a reaction.

Only similarity is that they are reagents that traditionally also work after death (when reagents aren't usually processed.)

We tried on and off stasis beds, during and between surgeries, the like.

**Comment by TemporalOroboros** [comment]
Which round was it?

**Comment by antropod** [comment]
https://scrubby.melonmesa.com/round/140206

**Comment by LemonInTheDark** [comment]
got a strong feeling there's something like a callback or signal register onto a null object

**Comment by TemporalOroboros** [comment]
I think I found it. Something's passing a string instead of a reagent datum.

**Comment by antropod** [comment]
well, when you create dictionary in JS, it follows same logic
`{foo: "bar"}` is actually `{"foo": "bar"}`
unlike in Python, where you can use variable as a key, or have to use quotes
and BYOND list are used as dictionaries, so it makes sense

refactoring is actually hard when you don't have automatic tests

**Comment by coiax** [comment]
Oh, I've seen this runtime when doing some testing with smoking cigarettes.
