### ISSUE TITLE
Bugged virology, Unable to get infected with Blood type virus.

### ISSUE THREAD

**Issue by angy286** [tgstation/tgstation#51791]
Issue reported from  Round ID: [140158](https://scrubby.melonmesa.com/round/140158) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1525

Hello
Today I came across a bug with virology. It appears you are not able to get infected by ingesting or injecting viral culture. Happened twice so I am reporting it.

**Comment by XDTM** [comment]
Just to be sure, do you remember what the symptoms were and if you were a non-human species? This could happen if the virus was stealthy or if the species is not infectable.

**Comment by Angustmeta** [comment]
Reminds me I recently failed to infect myself and others with an airborne virus sprayed with spray bottle. Drinking it worked.

**Comment by ATH1909** [comment]
oh god

oh fuck

nonononononononononononononononotagainnotagainnotagainnotagainnotagainnotagainnotagainnotagainnotagainnotagainnotagainnotagain

**Comment by angy286** [comment]
No I was human, and symptoms were Nocturnal regeneration, Self-respiration,
Eternal Youth, Itching, Shivering and Fever. Last 3 neutered.
True, virus was steath i think 3 or 6. But it worked before 22nd of June.

Also Deadly virus based on Autophagocytosis Necrosis didnt work either.

ut 23. 6. 2020 o 1:39 ATH1909 <notifications@github.com> napísal(a):

**Comment by ShizCalev** [comment]
Likely fixed by #51801
