### ISSUE TITLE
Rebuilding Detdrobes causes them to explode on deletion.

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#51797]
Issue reported from  Round ID:  (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

Step one: screwdrive and crowbar a detdrobe open.
Step two: replace the board and refill unit. This will turn it into a custom vendor for some reason.
Step three: Delete it. It will then explode in a -1, 0, 3, 0 explosion. 

Unsure if any type of destruction/deletion effect causes the explosion or if it is limited to just admin deletions.
ADMIN LOG: TheMidnightRose/(Emerald Gleaner) deleted Custom Vendor at (170,50,1) (JMP)
ADMIN LOG: Explosion with size (-1, 0, 3, 0) in Thunderdome Arena (170, 50, 1) (JMP)

**Comment by Tlaltecuhtli** [comment]
Step two: replace the board and refill unit. This will turn it into a custom vendor for some reason.

thats the real bug not the OP title

**Comment by ATH1909** [comment]
excuse me what the fuck

**Comment by Firecage** [comment]
Well. Vending machine circuit boards are gotten by screwdrivering a custom vending board and selecting the 'brand', such as the Detdrobe. And of course, Custom vending machines themselves blow up if destroyed.

I guess the board defaulted the Custom when the Detdrobe was deconstructed?

**Comment by TheMidnightRose** [comment]
For some strange reason Detdrobes dont have their own board like the others do and just use a custom vendor board on decon.
