### ISSUE TITLE
Weeping avulsions are not being able to be repaired

### ISSUE THREAD

**Issue by bigfatbananacyclops** [tgstation/tgstation#51800]
round id: 140213

someone reported it that they wont fix and they said that when you try to fix it it will give you weeping avulsions, kinda strange.
give someone a weaping avulsion try to cauterize it. try to suture it, Try the surgery. nothing.
i asked them to give me a more specific reproduce of the bug but this is all i got.

''The type of wound is a bleeding arteryy called a wheaping avulsion. I did a whole surgery to fix it and it didn't do shit. I ended up cutting off the arm and I was given 3 wheaping avulsions that killed me. I think it's super bugged ''

**Comment by Ryll-Ryll** [comment]
Were they on a stasis bed?

**Comment by Jared-Fogle** [comment]
> 
> 
> Were they on a stasis bed?

This is most likely the case, but this issue slipping by both the person reporting and @bigfatbananacyclops shows that this behavior isn't intuitive, and anecdotally is something I've forgotten quite a lot. I like the way the rest of wounds are explained deliberately, perhaps you can do something similar to make sure that people aren't doing this by mistake?
