### ISSUE TITLE
Blood transfusions to characters does not work

### ISSUE THREAD

**Issue by tom13478** [tgstation/tgstation#51816]
## Round ID: [140287](https://scrubby.melonmesa.com/round/140287) 
Testing occured after adminhelp request to drain souless character.

## Reproduction:
Method Giving Blood - IV to patient
Attach IV with bloodbag to a character with low blood.  Note how blood level does not increase but blood is found in reagents.

Method Giving blood - Syring to patient
Draw blood from a character with blood and transfer to a character without blood.  Note have blood level does not increase and blood is found in reagents.

Note: Drawing blood from a patient via IV and syring appears to draw blood correctly.  Iron tablets work as expected.

**Comment by Time-Green** [comment]
It’s put in reagents and should then metabolize into their bloodstream, which seems to be broken then

**Comment by tom13478** [comment]
Should infused/injected blood be metabolized?

**Comment by ArcaneDefence** [comment]
Fails to reproduce on master.
