### ISSUE TITLE
Spraycans are broken YET AGAIN

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#51833]
![tgStation Terry  EU   100% LAG FREE   New-Dedi  Heresy Point Delta 2020-06-24 145226](https://user-images.githubusercontent.com/54288658/85566975-c5b6d300-b630-11ea-928d-2933fb506843.png)
Issue reported from  Round ID: [140331](https://scrubby.melonmesa.com/round/140331) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1517
no fun gang!

**Comment by Pugie** [comment]
Hahahahahahahahahahahahaha

**Comment by Fikou** [comment]
its people using the washing machine with a black crayon to replicate the old spraycans

**Comment by Pugie** [comment]
![image](https://user-images.githubusercontent.com/41806499/85795320-f7fb2a00-b72f-11ea-91d0-d9963bb600e7.png)
feature

**Comment by ATH1909** [comment]
![image](https://user-images.githubusercontent.com/42606352/85799355-b608be80-b704-11ea-8fb9-b2137c3e5bcb.png)

**Comment by Tharcoonvagh** [comment]
Okay apparently you can dye most items with a crayon and a washing machine, and the floor can easily be fucked with using the largebrush button on spraycans
