### ISSUE TITLE
Mimes cannot use heretic abilities

### ISSUE THREAD

**Issue by Quietly12** [tgstation/tgstation#51832]
Issue reported from  Round ID: [140328](https://scrubby.melonmesa.com/round/140328) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])
Reporting client version: 513.1524

A heretic mime casts an ability, then gets an error message stating they cannot get the words out. This is an oversight ,as all other magical abilities can be used as a mime, including cult abilities.

**Comment by ATH1909** [comment]
> as all other magical abilities can be used as a mime, including cult abilities.

Actually, mimes can't cast most wizard spells (without breaking their oath).

Still, yeah, someone should fix this.
