### ISSUE TITLE
blind people can read again thanks to new paper

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#51838]
## Round ID: 

#140354 but it probably doesn't matter

## Testmerges:

doesn't matter

## Reproduction:

- be blind (roundstart trait cause temporary blindness =/= roundstart blindness)
- read paper
- suddenly, you can read

blind people couldn't read old paper as of a few months ago thanks to a bug that was fixed but with new paper the bug is unfixed

![image](https://user-images.githubusercontent.com/51863163/85626352-87221800-b632-11ea-89d1-c0389c74e45b.png)

**Comment by ATH1909** [comment]
https://cdn.discordapp.com/attachments/401604300108857354/725161403941650472/image4.jpg

**Comment by MrMelbert** [comment]
okay so unblind people can "see" the paper (green eye)
![image](https://user-images.githubusercontent.com/51863163/85638878-bb0a3700-b64c-11ea-8a85-89931032aeb2.png)
while blind people cannot "see" the paper (orange eye)
![image](https://user-images.githubusercontent.com/51863163/85638907-ce1d0700-b64c-11ea-820f-535eb10cb300.png)
which means blind people can see the paper, attempt to edit it, mess around, and when they click save, it just deletes the text they added
