### ISSUE TITLE
clicking mafia game boards as a ghost makes ntos blue screens

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#51874]
## Round ID:
literally any round mafia has been test merged on, so probably only one

## Testmerges:
#51788 

## Reproduction:
be a ghost and click on the mafia game boards, in the corners of the mafia map:
![image](https://user-images.githubusercontent.com/57122098/85915041-e5005c80-b7f8-11ea-96d8-1ba02b67ffd3.png)

**Comment by tralezab** [comment]
Thank you for reporting, and thank god the game still runs fine and it just kinda screws ghosts up

**Comment by tralezab** [comment]
to be clear this is because of #51788

**Comment by stylemistake** [comment]
Is semmingly fixed on master.
