### ISSUE TITLE
medibots are broken AGAIN

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#51888]
<img width="1440" alt="broken medibot" src="https://user-images.githubusercontent.com/42606352/85935219-f8bcc900-b8b3-11ea-872b-d423118ed5c2.PNG">

this white medibot (assembled from one of the roundstart white kits in robotics) refused to heal this guy
it was on the proper settings and everything
and the guy had more than enough brute damage and was still alive

**Comment by msgerbs** [comment]
Also had this occur a few days ago. Somebody brought a medibot into Engineering and dragged me out to it. It started trying to heal me and failed because I had a hardsuit on, then it refused to acknowledge my existence for the rest of the shift.

**Comment by ZeroMODE0** [comment]
I always just thought medbots were racist and didn't like healing ~specific people/bipedal creatures.~ This happens enough for me to not rely on medbots.

**Comment by timothymtorres** [comment]
It looks like #52101 or #54907 fixed this.

> Also had this occur a few days ago. Somebody brought a medibot into Engineering and dragged me out to it. It started trying to heal me and failed because I had a hardsuit on, then it refused to acknowledge my existence for the rest of the shift.

Hardsuits blocking medibots is intended, just like how syringes are blocked.

If the medibot issue persists just ping me and I will reopen this.
