### ISSUE TITLE
Tracking with ai cams doesn't work roundstart, you have to have looked at a person to be able to track them

### ISSUE THREAD

**Issue by Kaffe-work** [tgstation/tgstation#51885]
## Reproduction:
untill you have seen a person by panning your AI eye around, you cannot use the chat to jump to their location, this leads to issues regarding opening doors, your primary function.

**Comment by zxaber** [comment]
This has been an issue for a while. It seems that *eventually*, camera net figures out what's what and you can track people you've not seen yet.

**Comment by Kaffe-work** [comment]
yep, it sure has, could probably do a hotfix by some "reset function" of camera net, just how that could help power issues on icebox a while back.

**Comment by AnturK** [comment]
View check probably returns false for uninitialized chunks.
