### ISSUE TITLE
pubby monkey shuttle has problem when rotated

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#51892]
![pubby monkey shuttle bug](https://user-images.githubusercontent.com/33834933/85945523-b42a3f80-b93e-11ea-8c8b-4b6fa65c2a94.PNG)

**Comment by Pumpkinoe** [comment]
dupe of #51795 that i made since i was angry about how 3x3 engines rotate
(grumble)

**Comment by Dennok** [comment]
Eh
