### ISSUE TITLE
Hairline fractures are impossible to heal alone despite claiming that they are.

### ISSUE THREAD

**Issue by Borisvanmemes** [tgstation/tgstation#51893]
Round ID: [140625](https://scrubby.melonmesa.com/round/140625)

Testmerges: None.

Reproduction: Get a hairline fracture, apply bone gel and surgical tape to where the hairline fracture is, have it never actually heal.
Getting it fixed by someone else via surgery still worked.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/b9e088ec4dcbdc4689f3eba98d3578a24f586f90/code/datums/wounds/bones.dm#L464-L493

**Comment by Sealed101** [comment]
healed fine in testing, can't repro
