### ISSUE TITLE
Freezers violate thermodynamics (thermomachine)

### ISSUE THREAD

**Issue by griffithlol** [tgstation/tgstation#51897]
I have been told that using the TEG and freezers you can create power, which is impossible. 
Looking at the code for freezers, it appears that the power draw is computed as 
`active_power_usage = (heat_capacity * temperature_delta) / 10 + idle_power_usage`
I cant claim to fully follow how `heat_capacity` is computed due to unfamiliarity with byond, but the energy required to change the temperature of an ideal gas is
![q=m c_p \Delta T](https://latex.codecogs.com/svg.latex?%5Cinline%20q%3Dm%20c_p%20%5CDelta%20T)
I dont understand the need for the division by 10, and I am not sure if the code accounts for the number of moles of gas properly. It is also strange to allow for a 100% efficient process, especially unupgraded, but this is secondary to the problem. Input from anyone with more insight into the problem would be appreciated.

**Comment by Jack7D1** [comment]
It is possible for infinite electricity using a single heater and cooler

**Comment by Tlaltecuhtli** [comment]
bro its a videogame

**Comment by LemonInTheDark** [comment]
> I have been told that using the TEG and freezers you can create power, which is impossible.

Nope, there's a good amount of stuff like that. There's a reason we don't have any power to money converters.
> Looking at the code for freezers, it appears that the power draw is computed as
> `active_power_usage = (heat_capacity * temperature_delta) / 10 + idle_power_usage`
> I cant claim to fully follow how `heat_capacity` is computed due to unfamiliarity with byond, but the energy required to change the temperature of an ideal gas is
> ![q=m c_p \Delta T](https://camo.githubusercontent.com/3fbf74b2a1631ba62116c55bcd1001bfb8bf9add/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f7376672e6c617465783f253543696e6c696e65253230712533446d253230635f7025323025354344656c746125323054)
> I dont understand the need for the division by 10, and I am not sure if the code accounts for the number of moles of gas properly. It is also strange to allow for a 100% efficient process, especially unupgraded, but this is secondary to the problem. Input from anyone with more insight into the problem would be appreciated.

Yeet.
Heat Capacity is a variable defined by gas types, in that case it was probably found be calling something like heatCapacity() on the gas mixture. It takes into account proportion and molar count.

The real issue with the TEG and freezers/heaters is the in order to balance the power output of the former, you'd need to massively increase the power cost of the latter. This would mean you couldn't use freezers or heaters for anything else sanely.

The solution to this is to either make freezers/heaters leak heat, or remove the teg. Check #50667 for more shit like this, same problem different source.

**Comment by Kaffe-work** [comment]
Freezers are objectivly better than space loop, even as t1 - more stable and higher cooling capacity.

**Comment by LemonInTheDark** [comment]
IIRC they're a bit slower and cool to a higher temp. might need more volume in your loop

**Comment by griffithlol** [comment]
Simulating heat loss is something that may become to computational expensive, so I was hoping to solve it by simply adding a constant modifier that addresses the fact that it is not a one to one conversion, ie no thermodynamic process is 100% efficient, there is always loss. Given how easy it is to make power, power cannot be used in the greater scope of the game as a balancing tool. Putting aside the sci-fi power generation tools available for now, no machine should be able to create more energy than it recieved. Work in must be greater than or at the very least equal to energy out. This is something that it simultaneously important from a game design perspective, and for basic coherence to the laws of physics, which is likely something to make the game as a whole more self-consistent and balanced, as referencing back to them is a lot easier than having no guiding principle at all.

@LemonInTheDark thanks for you input, I will check out the link you left. If you know anymore about `/datum/gas_mixture` I would appreciate your knowledge.

**Comment by LemonInTheDark** [comment]
No trouble. If you have more questions just ask for me in coding general, I'm around till about 11pm est

**Comment by Kaffe-work** [comment]
Slightly slower and can easily add more, is space-debris proof, and is by default on the other side of the filters (not cooling unneccessary gas)

**Comment by msgerbs** [comment]
This can be closed now yeah? Since TEG is gonzo...

**Comment by LemonInTheDark** [comment]
Fixed, at least for now due to #57831
