### ISSUE TITLE
[reported on fulpstation] your heirloom is no longer recognized as being yours when you respawn as a podperson

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#51908]
![image](https://user-images.githubusercontent.com/42606352/85975514-ec149f80-b99d-11ea-84ff-d2cff50decb8.png)

If I had to take a guess, this is because podpeople don't keep their old quirks, and nothing cleared the negative mood debuff from this guy's heirloom not being on his person.

Maybe clearing the positive/negative mood buffs/debuffs in on_remove() might work?

**Comment by Tlaltecuhtli** [comment]
wasnt this a problem when cloned? just copypaste the solution that was used in that case
