### ISSUE TITLE
Nuclear operative tablets are invisible

### ISSUE THREAD

**Issue by bigfatbananacyclops** [tgstation/tgstation#51909]
It's been pretty much showing like this every time there's nuke ops in a round for the whole day, when i use the admin command ''check content'' the players does have a tablet computer on them, but it's invisible, i tried spawning it in, it is completely invisible.

''obj/item/modular_computer/tablet/nukeops''

tbh its probably a icon name issue.

**Comment by zxaber** [comment]
Should be fixed per #51910.

**Comment by nightred** [comment]
Please close issue as it has been fixed.
