### ISSUE TITLE
having a large amount of scrubbers in one air alarm causes a large amount of (server?) lag when you open the ui

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#51927]
## Round ID: 

Discovered on a downstream, tested local

## Reproduction:

- put down 60 scrubbers in one area
- opened air alarm, started to lag, thought it was just client lag
- sever population (around 15 at the time) started to complain it was lagging
- closed air alarm
- client lag stopped, server lag stopped
- opened air alarm
- server lag seemed to start again

i don't know much about checking for lag/resource usage but when i was testing it local the tgui category spiked in the master controller tab

**Comment by LemonInTheDark** [comment]
yep, cause it's gotta load all that shit
