### ISSUE TITLE
With no objective to escape or survive, heretics greentext when they're dead if they met their objectives

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#51938]
The title. If you complete all your objectives as a heretic, you still greentext even if killed since you have no incentive to survive.

Feature? Or oversight? Personally, I think that if you have to die gloriously it should tell you, so I'll put this down to oversight.

**Comment by nightred** [comment]
Or they really only care about the objective, and do not care what happens to the heretic afterwards?

**Comment by Fikou** [comment]
heretic objectives suck anyway they are for obsessed
