### ISSUE TITLE
"Observe" verb glitch

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#51946]
## Reproduction:
Observe someone, then try to move away from them. Your ghost will leave their body but the camera will remain locked on the person you are observing. Bringing up the observe menu again cancels this.

**Comment by Wayland-Smithy** [comment]
Using the `observe` verb again to cancel if you don't select another target seems like intended behavior to me. Better than having another verb to cancel, or breaking the observation when you give a direction input IMO.

Did it lock your ghost to the target in the past? The camera decoupling does not seem to be a huge deal besides the fact the sounds you hear are relative to your ghost regardless of if you are observing or not.

Personally I think this is fine so I can park my ghost orbiting a malf AI and observe its AI Eye and can enjoy hearing the kitchen timer dings for hacked APCs.

**Comment by Tlaltecuhtli** [comment]
it has always been like this

**Comment by msgerbs** [comment]
Are you sure it has always worked this way? I thought your ghost used to disappear when you observed.

**Comment by TheBonded** [comment]
this happens if you have the mode that shows their inventory and such enabled, which allows you to see what they see. Disable the mode and observe anything from the observe menu to disable it. intended.
