### ISSUE TITLE
Condiment bottle naming is broken

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#51942]
#### Reproduction:
Make condiment bottles with a CondiMaster 3000. 

Only bottled reagents with snowflake names get properly named. 

![200630 2216 41](https://user-images.githubusercontent.com/46400996/86172953-79333200-bb1f-11ea-94fc-0551e531a55b.png)

Image shows:
* Water (name broken)
* Capsaicin oil (hotsauce)
* Frost oil (coldsauce)
* Omnizine (name broken)

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/dafbf749af2ea73b216634b0f4b17e046600f0a3/code/modules/food_and_drinks/food/condiment.dm#L48-L60

intentional

**Comment by Angustmeta** [comment]
But when you make them a popup asks you what you want to name the bottle.
