### ISSUE TITLE
Mobs Self Reference With Parallax, Preventing Garbage Collection

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#51950]
Mobs with a client have a hard reference, to themselves, that is never cleared on `Destroy`---the only way to clear it is by deleting the client associated with the mob:

![img](https://i.gyazo.com/0fd9e92ddabe21bbbdb821b13789696e.png)

This is obviously bad as a mob holding a reference....to itself is going to prevent garbage collection.

This is probably a big reason why the new player mobs are failing to GC.

**Comment by AnturK** [comment]
But qdeling a mob will always kick the client first ? Is this not updated properly on that ?

**Comment by Fox-McCloud** [comment]
qdelin'g a mob does not `qdel` the client--that'd result in some uhhhh *not great things*---namely if you suddenly got gibbed, you'd be kicked from the game (and back to lobby).

**Comment by AnturK** [comment]
By kick i mean transfer not deletion. As in there should be cleanup in Logout

**Comment by Fox-McCloud** [comment]
There's cleanup in client deletion, but not logout, specifically; for the most part, the way processing for parallax works handles that just fine; it's really only when something is deleted that it becomes an issue, AFAIK.
