### ISSUE TITLE
Survival medipens can be used instantly in non low pressure enviroments

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#51952]
starting the process of injecting yourself with the pen in a normal pressure area then moving will make it instantly inject you with the pen chems

**Comment by ATH1909** [comment]
pppft whahahahahahhe

**Comment by TemporalOroboros** [comment]
I sense a `!do_after(...)` not returning.

**Comment by ATH1909** [comment]
> I sense a `!do_after(...)` not returning.

it's actually because the proc ends with a "return ..()", I think.

**Comment by ExcessiveUseOfCobblestone** [comment]
dab

**Comment by bobbahbrown** [comment]
fixed in https://github.com/tgstation/tgstation/pull/52712/
