### ISSUE TITLE
Implosion compressor breaks after failed implosion

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#51978]
From local testing. 

#### Reproduction:

1. Insert raw anomaly core into implosion compressor. 
2. Insert TTV with non-working gas mix. 

"**The implosion compressor beeps**, "Transfer valve resulted in negligible explosive power. Items ejected."`

Try to reinsert the core. Result: 
![200702 1655 44](https://user-images.githubusercontent.com/46400996/86374529-f62bec00-bc84-11ea-88a8-fb27557fc84a.png)

Alt-clicking the compressor does nothing. It's permanently broken. Left-clicking it says: 

![200702 1657 22](https://user-images.githubusercontent.com/46400996/86374676-21164000-bc85-11ea-8fca-0e001e851bbc.png)

Edit: You also can't eject raw cores at all, even before failed tests.

**Comment by necromanceranne** [comment]
@silicons
