### ISSUE TITLE
Wizards can cast spells requiring evocation while being unable to speak

### ISSUE THREAD

**Issue by OmegaShoots** [tgstation/tgstation#51981]
round id 140971

Wizard mindswapped into a statue, something that is unable to speak, and was still able to cast fireball, a spell that needs to be spoken to be cast

**Comment by Angustmeta** [comment]
Mindswapping into statues was supposed to have been removed by #51480

**Comment by Kaffe-work** [comment]
not a big, wizards should be murder gods not Manuel ERP

**Comment by OmegaShoots** [comment]
It's a bug because you cannot cast fireball unless you can speak, and being a statue means you cannot speak
A wizard being muted in any way, shape, or form is supposed to stop them from being able to cast evoked spells

**Comment by Kaffe-work** [comment]
do they speak internally? abductor(golems) can also fireball.

**Comment by OmegaShoots** [comment]
No, I was the statue for a split second and tried speaking and got the "You are unable to speak" message. Also orbitting the wizard and saw him cast fireball twice with no chat message. I would assume they also would have gotten that message while casting it, but were still somehow able to use fireball.
