### ISSUE TITLE
Tranquility cannot be analyzed with an odysseus syringe gun

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#51988]
not sure if its intentional but just putting this here incase someone feels like changing it

**Comment by Tlaltecuhtli** [comment]
https://github.com/tgstation/tgstation/blob/dafbf749af2ea73b216634b0f4b17e046600f0a3/code/modules/reagents/chemistry/reagents/other_reagents.dm#L2113-L2118

intended, jannies close this
