### ISSUE TITLE
freeze rays don't work (very well)

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#51994]
1. Buy a water vapor canister.
2. Lower the temperature of its contents to 74 K, then I think later 43 K (I upgraded the freezer later).
3. Fill an empty plasma tank with this chilled water vapor, then set it to max release pressure.
4. Insert it into a flamethrower that's using a condenser instead of an igniter.
5. Use the flamethrower.
6. Cry as it just makes wet tiles instead of frozen ones.
7. Notice near the end of the round that it can sort of create a few frozen tiles, but only if you spam it repeatedly.
8. Cry some more.

```
/datum/gas_reaction/water_vapor/react(datum/gas_mixture/air, datum/holder)
	var/turf/open/location = isturf(holder) ? holder : null
	. = NO_REACTION
	if (air.temperature <= WATER_VAPOR_FREEZE)
		if(location && location.freon_gas_act())
			. = REACTING
	else if(air.temperature <= T20C + 10)
		if(location && location.water_vapor_gas_act())
			air.gases[/datum/gas/water_vapor][MOLES] -= MOLES_GAS_VISIBLE
			. = REACTING
```
I think that this is using the temperature of the entire air composition (or maybe gases in atmos don't retain their own temperatures, and just instantly average their temperatures with other gases in their tile, I'm not an atmosian), which the cold water vapor would be just a small proportion of, causing it to not be cold enough to freeze anything.

I, uh, guess that this wasn't really a bug, but it was still really disappointing, especially since I thought that the condenser was added for a purpose almost exactly like this one. I was gonna add a condenser flamethrower with some cold vapor vapor tanks to the Mr. Freeze syndi-kit, but I guess that that idea's a bust now.

**Comment by LemonInTheDark** [comment]
So two things here, first of all, it works wonders with a temp of 2.7, so you should use that for your mr freeze thing. It's actually kinda neat.

For the second, I'ma address this line
>I think that this is using the temperature of the entire air composition (or maybe gases in atmos don't retain their own temperatures, and just instantly average their temperatures with other gases in their tile, I'm not an atmosian),

Each type of gas has it's own heat capacity. It effects the amount of energy required to heat/cool the gas.
For instance, plasma has a heat cap of 200, and trit has a heat cap of 10. That's partly why running a trit engine is so hard.

In any case, h2o has a heat capacity of 40. You could mix it with another gas to raise the amount of energy in the mix, like maybe plasma at 200, or freon maybe at 600.

**Comment by ATH1909** [comment]
> So two things here, first of all, it works wonders with a temp of 2.7, so you should use that for your mr freeze thing. It's actually kinda neat.
> 
> For the second, I'ma address this line
> 
> > I think that this is using the temperature of the entire air composition (or maybe gases in atmos don't retain their own temperatures, and just instantly average their temperatures with other gases in their tile, I'm not an atmosian),
> 
> Each type of gas has it's own heat capacity. It effects the amount of energy required to heat/cool the gas.
> For instance, plasma has a heat cap of 200, and trit has a heat cap of 10. That's partly why running a trit engine is so hard.
> 
> In any case, h2o has a heat capacity of 40. You could mix it with another gas to raise the amount of energy in the mix, like maybe plasma at 200, or freon maybe at 600.

Ah, thanks.
