### ISSUE TITLE
Heater/Freezer are having a odd behavior when connected to a pipenet(in this case, toxins' mixing output pipenet)

### ISSUE THREAD

**Issue by JenqaDev** [tgstation/tgstation#51993]
## Round ID:
[140968](https://scrubby.melonmesa.com/round/140968) and many others after this one

## Testmerges:
#51412 #51912

## Reproduction:

In my toxins setup(think about this setup as in Delta's toxin room), I keep the input piping just the way it is, and the output piping differently: scrubber -> pipe - freezer on top of that pipe facing north(on Meta it faces west) -> **volumetric pump** -> connector.
The issue happens in the volumetric pump, the gas that gets stored in the node never goes under specifically 44.08K while the freezer is set to cool it to 43.15 like any regular T2 freezer on minimum. I even tried to upgrade it to T4 but even when setting the temperature to 3K or literally anything under 44.08K it won't lower, fucking up the gas mix for the bomb.
I came with an idea to bypass this but haven't tested yet: only add the volumetric pump after you have enough mols of tritium(what I want in that phase, I have a third piping for the plasma) and it's down to the right temperature. If this doesn't work then I guess I'll have to try with gas pumps, and maybe that may work fine since the gas is so cold that it can't clog.

**Comment by LemonInTheDark** [comment]
Can't reproduce, you sure it was the lower node causing ya trouble? 
![image](https://user-images.githubusercontent.com/58055496/86496678-4f525900-bd33-11ea-9414-9b746b5883d4.png)

**Comment by JenqaDev** [comment]
I did it in the toxins' mixing chamber, where i built a volumetric pump myself with the RPD. Try to do it there. Also the freezer itself is overlapping the pipe like this:
![image](https://user-images.githubusercontent.com/43709941/86497402-7e8bb900-bd79-11ea-8d37-8b84e30a0b86.png)

**Comment by JenqaDev** [comment]
I even talked with the admin Doctor Brutality in game to tell him about this issue, of course I also decided to create a new issue on GitHub so someone could actually fix it or at least see what's happening because this setup works 100% fine and efficiently for literally 3  50Ks if i do it right.

**Comment by LemonInTheDark** [comment]
I'm testing on my local, it shouldn't make a difference, there haven't been any massive atmos changes in the last few weeks. I'll test it with the sneaky overlay thing you're doing, it could just be bugged behavior cause that's not intended

**Comment by JenqaDev** [comment]
Yeah most likely, i just find it odd to see happen twice in terry. In my local a strange issue also happened: without compiling any changes i am working on, suddenly my build of tg decided to act super broken in gas meters and the space parallax. Of course it fixed itself by simply restarting.
I need to try it one more time next time I hop into Terry just to see if it keeps happening.

**Comment by LemonInTheDark** [comment]
Yeah you're trouble is the layering of machines and pipes like this isn't exactly intended behavior, and it's not behaving as you'd like cause of that

**Comment by LemonInTheDark** [comment]
I'd fix it, but it doesn't really matter, it's not like the rcd layering thing. As a solution to your troubles, face the freezer exit pipe backwards, that appears to fix it.

**Comment by JenqaDev** [comment]
Alright, but it has been working fine so far, that's why I'm wondering what's going on here. Of course this is just for the sake of a compact setup and I can always make it go further for the freezer to be in an actual proper spot. 
> face the freezer exit pipe backwards, that appears to fix it.
I tried this the first time I got told this technique by Trerri, and it didn't work, the gases wouldn't change the temperature at all.

**Comment by LemonInTheDark** [comment]
it's cause pipes aren't supposed to intersect like this. Try wrenching down a pipe below a horizontal freezer and you'll get what I mean. The trouble is freezer rotating doesn't obey this, so shit gets jank

**Comment by JenqaDev** [comment]
I get it, this isn't supposed to be even made, and we're supposed to expect some issues since I am playing around with some wacky compactiness. I can simply fix this by adding a small piping above that goes into the freezer on a proper spot outside the airlocks. I've got to try this as soon as i can.

**Comment by trerri** [comment]
Hello, I am the Trerri. This behavior is cursed knowledge and should be smited. It was a grave mistake on my side to disclose the Dark Secrets of atmos. May this be forever forgotten and treated as High Taboo.

**Comment by JenqaDev** [comment]
> Hello, I am the Trerri. This behavior is cursed knowledge and should be smited. It was a grave mistake on my side to disclose the Dark Secrets of atmos. May this be forever forgotten and treated as High Taboo.

It shall never be forgotten, I'll stick to the rest of my days trying to still overlap a freezer in a pipe or even 3 freezers in 3 layers on the same tile, who knows.
Anyways I already have a workaround to make this still nearly as compact but not so cursed, simply pipe it through the wall into a freezer like regular people do and it just works.
Looks like 3 50Ks is still on the menu boy. specially with the new "implosion compressor" shit that someone added that makes phazons and BoH absolute bs to work on unless you are the chad toxinman behind the entire scene.

**Comment by JenqaDev** [comment]
You think I should actually close the issue? (as it's based on gaining advantage from the weird behaviour from code)

**Comment by LemonInTheDark** [comment]
Rename it to something like overlapping pipenets causes odd behavior. It's useful to document, and might need changing/fixing in future.

**Comment by Electronics** [comment]
Isn't it that the freezer facing the pump doesn't see a pipenet connected to it (as the pump connects multiple different nets), therefore doesn't work but does work the other way around facing into a dumb pipe.

**Comment by JenqaDev** [comment]
> Isn't it that the freezer facing the pump doesn't see a pipenet connected to it (as the pump connects multiple different nets), therefore doesn't work but does work the other way around facing into a dumb pipe.

Most likely yes.

**Comment by JenqaDev** [comment]
Sorry this has to come active again, today I did a far different setup and the pipes still decided to not cool down to the right temperature. This easily is fixed by also putting the o2 on the same temperature and you still get those sweet 50K points. 
![image](https://user-images.githubusercontent.com/43709941/86539102-fc72d000-bef1-11ea-8a44-c1c02afa4979.png)
this time the temperature got stuck in 44.01K, even the RD that was looking at me do it(i was a greytider in this round so of course he wanted to watch me do it for precaution) but i managed to still achieve the points.

**Comment by LemonInTheDark** [comment]
so that upper net wasn't cooling past 44.01k? what was the freezer set to?

**Comment by JenqaDev** [comment]
was set to 43.15K(the tier 2 minimum)

**Comment by TemporalOroboros** [comment]
The freezer not cooling all the way down is annoying and has a really jank fix:
1. Keep the burn chamber scrubbers set to scrub trit.
2. Open the chamber vent.
3. Scrub the resulting vacuum.
4. Watch as the freezer magically cools the remaining ~1&deg;K.

I don't know why this works, it just does.

**Comment by JenqaDev** [comment]
Good idea, i need to try that ASAP

> Open the chamber vent

You mean the shutters right?

**Comment by TemporalOroboros** [comment]
Yes.

**Comment by LemonInTheDark** [comment]
Not again

**Comment by JenqaDev** [comment]
@TemporalOroboros another fix is by placing the freezer connected directly to a connector, that way the gas will cool to the correct temperature again.
