### ISSUE TITLE
Icebox Jacobs Ladder crashing down, crashing down, crashing down.

### ISSUE THREAD

**Issue by Firecage** [tgstation/tgstation#51996]
## Round ID:
https://sb.atlantaned.space/rounds/141060

## Reproduction:
1. Be certain the map is Icebox.
2. Obtain Jacob's Ladder.
3. Place down Jacob's Ladder where you are sure enough victims would gather.
4. Behold the beauty as when they climb down, they crash down to the bottem most icemoon Z-level.
5. Behold the utter horror as they keep crashing down in agonizing splats as they try to climb back up.

**Comment by Doosteroni** [comment]
Feature

**Comment by Dennok** [comment]
Great

**Comment by Firecage** [comment]
I wonder if this specifically has to do with chasms now that I think about it. Perhaps, just under the bar, where I had placed it, there was a chasm. Mmm...
