### ISSUE TITLE
Canister sprites are glitched

### ISSUE THREAD

**Issue by Trumpetplaya288** [tgstation/tgstation#52024]
Canister sprites sometimes break and look like this, I'm sure some of you have seen this it's a common bug.
![image](https://user-images.githubusercontent.com/54781382/86527820-79f5fc00-be70-11ea-9c5a-d671b0d2202d.png)

**Comment by LemonInTheDark** [comment]
may or may not have left a 90 degree rotated icon in for at least a month, the answer is shrouded in mystery
