### ISSUE TITLE
eye damage overlay persisted despite lack of eye damage

### ISSUE THREAD

**Issue by joybod** [tgstation/tgstation#52061]
Issue reported from  Round ID: [141309](https://scrubby.melonmesa.com/round/141309) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

IC name is Manuel Ackerley, I got ganked by a syndie critter and was dead for a while, then I got res'd and my organs replaced but despite haveing brand new eyes and a healthy blood level, I still had the eye damage overlay.

**Comment by ShizCalev** [comment]
Also happens when you heal a mob.
