### ISSUE TITLE
Catatonic humans spontaneously get split personalities

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#52063]
Round ID: [141320](https://scrubby.melonmesa.com/round/141320), but I've seen it twice before as well

Reproduction: Occasionally the game will poll ghosts to be the split personality of a catatonic human (usually in their home in genetics). Doesn't show an admin report of spontaneous brain damage, and the catatonics aren't being hit in the head.

**Comment by ATH1909** [comment]
Did the catatonics get and lose HARS? Maybe they got a head wound that's giving them brain traumas? Can the split personality trauma even be gotten from a head wound?

**Comment by dragomagol** [comment]
I have to admit I wasn't watching them beforehand, but when they get a split personality they do have a head. When I was one of the split personalities the two geneticists were sitting at their consoles, so I assumed they weren't interacting with the catatonics? Not sure about the head wound thing.
