### ISSUE TITLE
Blob can be grow offstation on Ice Box

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#52067]
Blobs can just put their core down in a remote area in the icemoon wastes and grow there, making it very difficult to find them. A fix would probably be to restrict initial core placement to station turfs.
@Whoneedspacee

**Comment by Whoneedspacee** [comment]
initial core placement is restricted to station turfs.

**Comment by Whoneedspacee** [comment]
let me know if they placed in a ruin or something weird, all icebox areas should have blob_allowed set to false but maybe its an obscure ruin or something.

**Comment by Wayland-Smithy** [comment]
Round ID is missing, but there was one recently with a Networked Fibers Blob spawning on station then immediately proceeding to snake out into the wastes while hiding its tracks. The ensuing blobbernaut army was a sight to behold.

**Comment by kriskog** [comment]
Blobs have been able to spawn in space areas on station, but the progress doesnt count. Could be the same thing.

**Comment by Kaffe-work** [comment]
> Round ID is missing, but there was one recently with a Networked Fibers Blob spawning on station then immediately proceeding to snake out into the wastes while hiding its tracks. The ensuing blobbernaut army was a sight to behold.

that gotta be one of the most stupid bad hilarious things I've heard of - things like this is the magic that makes this game great. 

Then again, if said blob was stalling the round (potentially forever without attempting to go critical, well, then it should probably be allowed. Perhaps ofstation tiles should give 0.25 growth?


if no one argues, I could implement that.

**Comment by Wayland-Smithy** [comment]
Yeah luckily the blob I saw do this was a good sport with full intentions of taking over the station, and it was a 15min spawn so the round still had a normal length even with some cheeky atmos pumping fusion into distro.

The round stalling issue could be avoided if a totally off-station blob can not delay the shuttle departure, but the one I saw never fell below 2/400 (legit station blobs) critical mass so I am afraid that fix would not be so easy to implement.

**Comment by nightred** [comment]
Confirmed that PR #52119 resolved the issue of placing core and other items off station.
Creep can grow off station but you cannot use that creep for anything other then tile count.
