### ISSUE TITLE
Glowshroom spread speed is reversed

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#52076]
#### Round ID:
[141363](https://scrubby.melonmesa.com/round/141363) Terry

#### Reproduction:
- Max stats for glowcap (100 potency, 10 yield, 1 production speed)
- Plant it on ground. 

**Result:** It spreads extremely slowly. 

I was told by Nicki Shazam it's because production speed has reversed effect on spread. The lower (better) production speed, the slower mushrooms will spread. Supposedly same problem applies to **kudzu** <s>but I haven't confirmed.  </s>

Edit: Tested varediting two kudzu seeds to production 1 and 10 but can't notice any difference in spread between the two. 
Edit 2: Nevermind I tested it wrong. The slower prod speed kudzu spreads much faster. 

![200707 1734 39](https://user-images.githubusercontent.com/46400996/86805991-b85e0780-c078-11ea-9609-52c2d0748790.png)
10~ minutes after planting 5 patches.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/0a8790d4d65dd3d3b422798ca45e00c44555c9ec/code/game/objects/effects/glowshroom.dm#L76

**Comment by Angustmeta** [comment]
Seems it was like that even before that glowshroom rework.

**Comment by kriskog** [comment]
Yeah, should be the same for kudzu. Seems intentional based on code comments, though its a bit silly.

**Comment by Angustmeta** [comment]
It doesn't seem intentional for the mushrooms though since it says `So the delay goes DOWN with better stats instead of up. :I`. Makes me think someone misunderstood prod speed and broke it in the past, thinking they were fixing it.
