### ISSUE TITLE
revenants can invisible own people with radiation

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/tgstation#52078]
## Round ID:
[141373](https://scrubby.melonmesa.com/round/141373)

## Testmerges:
#51912: 'Painting Cleanup V2' by AnturK at commit 3e9aad85cd

## Reproduction:

-be revenant
-be near supermatter
-become irradiated and able to irradiate others

might apply to slaughter demons as well. very much so not a fan of an antagonist where there is literally nothing you can do about them  until they attack but if they can irradiate themselves and passively hurt you then they can attack while being invincible

**Comment by LemonInTheDark** [comment]
This'll be hard to fix, the filter applies on top of alpha changes, so something like going invis is gonna make the overlay invisible. This is partially caused by the change I made that allowed mobs themselves to be irradiated. MM this might be a pain

**Comment by LemonInTheDark** [comment]
This'll be hard to fix, the filter applies on top of alpha changes, so something like going invis is gonna make the overlay invisible. This is partially caused by the change I made that allowed mobs themselves to be irradiated. MM this might be a pain

**Comment by Wayland-Smithy** [comment]
> This'll be hard to fix

That depends on the solution right? Messing with your fancy filter is just one. The way I see it right now there are at least 3:

1. Radioactive Revenants green glow can always be seen
2. Revenants take essence damage from their rads
3. Revenants can not become irradiated like ghosts

Keeping in mind if the rev dies somewhere private it will respawn, and should get notices alluding to the source of damage over time option 2 doesn't look bad at all.

**Comment by LemonInTheDark** [comment]
that could work, looks like they're simple mobs tho, so that might be painful to pull off

**Comment by LemonInTheDark** [comment]
wait radiation is already on living wtf

**Comment by LemonInTheDark** [comment]
AHHH IT'S THERE BUT IT RESETS WHYYYYYYYY

**Comment by Wayland-Smithy** [comment]
It is living up to its lore, both living and not at the same time. 🤣 
>You are not dead, not alive, but somewhere in between.

Simply making Revenant immune to gaining rads should be simple you would think but dmcode.

**Comment by LemonInTheDark** [comment]
Nah paradoxically that's easy, unless you wanna try and make it process rads properly I'll get to it

**Comment by Wayland-Smithy** [comment]
By all means do it. That would be the overall safest option as the essence decay idea still leaves a window for invisible Chernobyl shenanigans and we could always revert later if we want to make it into a proper feature.

**Comment by ATH1909** [comment]
just make them immune to rads, yeah
