### ISSUE TITLE
disco ball only plays caramel densenn

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#52070]
playing other tracks will give caramel densenn

**Comment by drIcepop** [comment]
Is that really an issue?

**Comment by Wayland-Smithy** [comment]
Can not reproduce the exact conditions without access to the media files, but I see no reason for the jukebox loading the wrong song, and I heard the radiant dance machine mark V play something different on Bagil today as a ghost. Strangely it continued playing the songs for me for a few sec after someone hit stop and everyone shouted their disapproval maybe a symptom of time dilation no clue.

**Comment by LemonInTheDark** [comment]
absolutely a feature, not a bug
