### ISSUE TITLE
Glowshrooms runtime when disappearing

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#52099]
Local testing. 

#### Reproduction:

- Spawn glowshroom. 
- Varedit its seed's production stat to 10 so it grows as fast as possible (because of #52076). 
- Plant it and wait like 6 minutes until mushrooms start disappearing from old age. 

`Runtime in glowshroom.dm,110: Cannot read null.potency`
`  proc name: Spread (/obj/structure/glowshroom/proc/Spread)`
`  usr: Angust/(Gus Banner)`
`  usr.loc: (Bar (127,136,2))`
`  src: the glowshroom (/obj/structure/glowshroom)`
`  src.loc: null`
`  call stack:`
`  the glowshroom (/obj/structure/glowshroom): Spread()`
`  /datum/callback (/datum/callback): Invoke()`
`  world: PushUsr(Gus Banner (/mob/living/carbon/human), /datum/callback (/datum/callback))`
`  /datum/callback (/datum/callback): InvokeAsync()`
`  Timer (/datum/controller/subsystem/timer): fire(0)`
`  Timer (/datum/controller/subsystem/timer): ignite(0)`
`  Master (/datum/controller/master): RunQueue()`
`  Master (/datum/controller/master): Loop()`
 ` Master (/datum/controller/master): StartProcessing(0)`
https://github.com/tgstation/tgstation/blob/9f27b575e46b76dd42450904b7399b3b3899f137/code/game/objects/effects/glowshroom.dm#L110

and

`Runtime in glowshroom.dm,150: Cannot read null.yield`
`  proc name: Spread (/obj/structure/glowshroom/proc/Spread)`
`  usr: Angust/(Gus Banner)`
`  usr.loc: (Bar (127,136,2))`
`  src: the glowshroom (/obj/structure/glowshroom)`
`  src.loc: null`
`  call stack:`
`  the glowshroom (/obj/structure/glowshroom): Spread()`
`  /datum/callback (/datum/callback): Invoke()`
`  world: PushUsr(Gus Banner (/mob/living/carbon/human), /datum/callback (/datum/callback))`
`  /datum/callback (/datum/callback): InvokeAsync()`
`  Timer (/datum/controller/subsystem/timer): fire(0)`
`  Timer (/datum/controller/subsystem/timer): ignite(0)`
`  Master (/datum/controller/master): RunQueue()`
`  Master (/datum/controller/master): Loop()`
`  Master (/datum/controller/master): StartProcessing(0)`

https://github.com/tgstation/tgstation/blob/9f27b575e46b76dd42450904b7399b3b3899f137/code/game/objects/effects/glowshroom.dm#L150

I'm planning to PR a fix for #52076 but I have no idea how to fix these unrelated runtimes. If it's super simple I'd gladly fix them at the same time but otherwise I'll just ignore them.

**Comment by kriskog** [comment]
Its trying to read off a deleted seed. When they make a new shroom patch, a reference to the planting seed is passed along, but when any shroom is deleted so is the seed. All the remaining shrooms now have a null seed. We could probably just not delete the seed here and hope GC takes care of it?

```
/obj/structure/glowshroom/Destroy()
	if(myseed)
		QDEL_NULL(myseed)
	return ..()
```

**Comment by Angustmeta** [comment]
Okay. First test I tried to simply remove the middle two lines:
```
[22:02:50] Runtime in unsorted.dm,1129: addtimer called with a callback assigned to a qdeleted object. In the future such timers will not be supported and may refuse to run or run with a 0 wait
  proc name: stack trace (/proc/stack_trace)
  usr.loc: (Central Primary Hallway (139,154,2))
  src: null
  call stack:
  stack trace("addtimer called with a callbac...")
  addtimer(/datum/callback (/datum/callback), 200, 0)
  the glowcap (/obj/structure/glowshroom/glowcap): Spread()
```

**Comment by kriskog** [comment]
Thats an unrelated issue. Basically, spread is run on a timer that isnt stopped when its decayed and deleted.

**Comment by Angustmeta** [comment]
Alright. I tried removing the whole

 ```
 /obj/structure/glowshroom/Destroy()
	if(myseed)
 		QDEL_NULL(myseed)
 	return ..()
```

It does remove the two runtimes described in this issue. Now to figure out how to get rid of the
```
Runtime in unsorted.dm,1129: addtimer called
```
because it's throwing them like crazy.
