### ISSUE TITLE
Exploding a person's torso or head with C4 will result in said body part being removed (but the person still lives).

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#52103]
## Round ID:
N/a.

## Reproduction:
![image](https://user-images.githubusercontent.com/68032262/86970445-4fa18880-c167-11ea-81f6-7698121e159e.png)
1 - Attach C4 with a timer to a cyborg torso or head.
2 - Augment the person using said torso or head.
3 - Wait until the C4 would have exploded.
![image](https://user-images.githubusercontent.com/68032262/86970578-7eb7fa00-c167-11ea-953d-0524ca1ac819.png)
4 - Watch as they have no head (or torso).

In this state, they cannot be hit in the removed body parts and unlike HARS, they still have organs in their missing 'head' so they can talk, hear and see.
Similar to #51231.
It may not visually update the fact that their head is missing.

**Comment by ATH1909** [comment]
what happens if you c4 ALL of a person's body parts?

**Comment by brotherbeyondd** [comment]
Sadly it removes arms and legs like normal :( BUT when they are nuggetted, they cant be hit.

**Comment by FloranOtten** [comment]
Feature.

**Comment by ShizCalev** [comment]
this will essentially happen if whenever a mob's bodyparts are deleted.
