### ISSUE TITLE
Strange behaviour with bluespace bodybags when attempting to place it inside of a container located inside of it.

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#52104]
## Round ID:
N/a.

## Reproduction:
1 - Open a backpack.
2 - Place backpack on the back of another person.
![image](https://user-images.githubusercontent.com/68032262/86971412-0baf8300-c169-11ea-9685-770e6325b3e9.png)
3 - Bluespace bodybag the person, then compress the bodybag.
![image](https://user-images.githubusercontent.com/68032262/86971457-1f5ae980-c169-11ea-8574-2c835d83142b.png)
4 - Place said bodybag into the backpack of the bodybag'd person.
![image](https://user-images.githubusercontent.com/68032262/86971505-37326d80-c169-11ea-99c4-08b7f223cba5.png)
5 - Watch as the bodybag disappears and the backpack remains open.

With a bit of testing I found out that the person remains 'attached' to you so if they are conscious and they do attempt to escape from the bodybag, they'll tear out atop of wherever you are currently.
After the bodybag disappears, the backpack functions as you'd expect, until you close it.
Gibbing the person that is outside the bodybag will release the person inside of it.

**Comment by Sealed101** [comment]
can't repro because you can't keep the inventory of the equipped bag open when equipping it to another player. which was an issue apparently
