### ISSUE TITLE
global radio and say have _different_ max message lenght for some reason

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#52110]
![chat bug](https://user-images.githubusercontent.com/33834933/87011128-cd957c00-c1c7-11ea-9ca4-5b12bd84f527.PNG)

shouldnt they be the same lenght?

**Comment by optimumtact** [comment]
no they shouldn't

**Comment by nightred** [comment]
if they should not have the same length, then can we close this issue?
