### ISSUE TITLE
spread rust on not normal floor (titanium etc) is glitchy

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#52113]
141521

![rust bug](https://user-images.githubusercontent.com/33834933/87029351-4f919f00-c1e0-11ea-8fd1-c5e0a3620442.PNG)

walls either disappear or turn into normal ones and floor isnt affected

**Comment by Fikou** [comment]
titanium doesnt rust

**Comment by nightred** [comment]
If the titanium does not rust then it should not convert to normal walls.
