### ISSUE TITLE
Mecha armour ignores what direction the mech is actually pointed at

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#52144]
Description: Mech armor is fixed to 3 positions of east/west, north and south and doesn't take the mech's rotation into account. Every attack from the east/west counts as a side hit, every downwards attack counts as a backstab, and every upwards attack is a front attack. 

[Round ID]: ALL

## Reproduction:

1. Build/spawn a mech, be it a durand, aplu, gygax, whatever.

2. Rotate the mech so that it faces a certain direction. (Let's say it's FRONT is facing the east/west)

3. Have a buddy/aghost and create a new person to shoot the mech on it's side toward it's front-facing sprite. Note the damage dealt is what you'd expect from a side-shot and not the frontal armour like you'd hope. 

Conclusion: You can gank mechs easily by luring them into a vertical hallway where they're on the bottom and take them out in a few shots (backstabs do double damage.) Even if the mecha has it's front facing northwards, shooting it from this angle will register as a backstab. Shooting (or using certain melees) it from the sides always counts as a side attack, and attacking from the south is always a frontal (the least damage dealt) attack.

**Comment by necromanceranne** [comment]
Yikes

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/586bc81b4a0326d6b8b35fa30a086496621d01f4/code/game/mecha/mecha_defense.dm#L46

https://github.com/tgstation/tgstation/blob/586bc81b4a0326d6b8b35fa30a086496621d01f4/code/game/mecha/mecha_defense.dm#L1-L9

**Comment by ATH1909** [comment]
alright, now this is epic

**Comment by LemonInTheDark** [comment]
AHHHHHHHHH WHYYYYYYYYYYYY

**Comment by Kaffe-work** [comment]
big brain programming at work here lads
