### ISSUE TITLE
Once again, crafting is kill :(

### ISSUE THREAD

**Issue by Vanadiom** [tgstation/tgstation#52190]
## Round ID:
[141791](https://scrubby.melonmesa.com/round/141791)

## Testmerges:
#52085 

## Reproduction:
1. Try crafting an improvised Jetpack (with all the resources and tools of course)
2. It dont work.
3. Asses situation, try crafting a rapide pipecleaner layer (with all the resources and tools of course)
4. It dont work.
5. Asses further, try crafting a wheelchair (with all the resources and tools of course)
6. It dont work
7. Post cringe bug report on github.

**Comment by kriskog** [comment]
Define "It dont work." Does anything happen, or does the UI button not work or what.

**Comment by Vanadiom** [comment]
Oh, yes sorry, that would be important:
It just doesn't give you the ability to click, the button stays grey.

**Comment by kriskog** [comment]
Okay. Could be an issue with #52085. @stylemistake

**Comment by kriskog** [comment]
Reproduced with tgui 4.0 testmerged, not without. Craft button does not activate except on the default tab.

**Comment by stylemistake** [comment]
Fixed this problem in the future commit.
