### ISSUE TITLE
Tgui suspension error

### ISSUE THREAD

**Issue by Kaffe-work** [tgstation/tgstation#52203]
## Testmerges:

#52085: 'tgui 4.0' by stylemistake at commit d7ca619a9a

## Reproduction:

Error: Failed to suspend 'tgui-window-1'.
   at Anonymous function (http://127.0.0.1:58318/tmp9096/tgui.bundle.js:1:2976)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729)

**Comment by stylemistake** [comment]
No longer applicable.
