### ISSUE TITLE
You can get stuffed into syndicate extraction pods and sent to nullspace

### ISSUE THREAD

**Issue by tralezab** [tgstation/tgstation#52218]
## Round ID:
[141871](https://scrubby.melonmesa.com/round/141871)

## Testmerges:

None

## Reproduction:

Stuff someone into a syndicate extraction pod, they get sent to the no-no gem room

**Comment by BOBAMAx** [comment]
I didn’t explain this well in the adminhelp when this happened to me, but I was originally sent to the correct location for a few minutes (ninja dojo), but instead of being returned to the warden’s office from which i was podded from, I got sent to the gem room.

**Comment by nightred** [comment]
This sounds related to Issue #52340

**Comment by nightred** [comment]
More activity on the other issue. Closing this one.
