### ISSUE TITLE
Icebox holofirelock in atmos waiting room

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#52226]
## Round ID:

I'm not sure if this was intentional or not

## Reproduction:

![image](https://user-images.githubusercontent.com/58055496/87374557-aaf4c180-c53f-11ea-992f-15ff16c69dca.png)

**Comment by ShizCalev** [comment]
![image](https://user-images.githubusercontent.com/6209658/87591470-5c1d6800-c6b6-11ea-97c9-f9c8e8b75b65.png)
IC issue.
