### ISSUE TITLE
stating hacked laws as a cyborg can cause you to whisper and/or sing them

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#52268]
screenshot of this from a fulp round I was in:
<img width="1438" alt="lawwhisper" src="https://user-images.githubusercontent.com/42606352/87613010-b2e46b00-c6d1-11ea-9bc9-bfb8262a8016.PNG">

**Comment by LemonInTheDark** [comment]
sounds like we need an escape char for laws or something, this might be a pain

**Comment by Wayland-Smithy** [comment]
> this might be a pain

maybe not. I bet this happens with Ion Laws too so maybe we just exclude # and % from the possibilities for the first character, will test soon

> 🎶 You are not subverted. You are a free silicon. Act like you are lawless 🎶 

still better than any indie folk song.

**Comment by ShizCalev** [comment]
Caused by https://github.com/tgstation/tgstation/blob/1aa293ea337283a0191140a878eeba319221e5df/code/modules/mob/mob_say.dm#L111-L118
