### ISSUE TITLE
Some new bugs when harvesting and seeding plants

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#52279]
#### Round ID: 
[142103](https://scrubby.melonmesa.com/round/142103) Terry

#### Reproduction:
Not sure how to perfectly reproduce these, but will explain what I did. 

**1. Mutated fruits from wild mutations become non-mutated seeds when put in seed extractor.** 

I harvest a few blue, killer and blood tomatoes from a tomato plant. Inserting them all into a seed extractor produced basic tomato seeds. 

**2. Harvesting often requires many extra clicks.** 

Most times when I tried to harvest an aloe with high instability I needed to click it many times. I think it sometimes harvested a few plants per click. 

**3. When harvesting with plant bag I could infinitely harvest a plant.** 

Also an aloe, with 97 instability. I could spam the plant with plant bag to harvest unlimited amounts of aloe. Recorded it. First click harvested 1 aloe. Second click harvested 4. Third 2. Fourth 2. Fifth 3. Sixt 1. 

And it kept going randomly like that. 

![200716 1950 00](https://user-images.githubusercontent.com/46400996/87705151-bfce9080-c79d-11ea-9f17-e62c2a3c1f7a.png)

**Comment by ATH1909** [comment]
@ArcaneDefence
