### ISSUE TITLE
You can tackle people from beyond the grave

### ISSUE THREAD

**Issue by Jimmius** [tgstation/tgstation#52300]
Issue reported from  Round ID: [142193](https://scrubby.melonmesa.com/round/142193) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1525

Basically if you die while wearing gripper gloves and you're buckled into a wheelchair or some other rideable thing, you can keep tackling even after you die. You can do this endlessly until someone unbuckles you from whatever you're riding. It's very funny but also seems unintentional.

**Comment by ATH1909** [comment]
nice

**Comment by ATH1909** [comment]
does this work with rolling chairs, or just vehicles?

**Comment by Jimmius** [comment]
yeah, it works on office chairs. I assume anything you can buckle yourself  to and still move, but I've not tested everything, just office chairs, scooters, skateboards, and office chairs
