### ISSUE TITLE
Mechs are nightmare proof.

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#52303]
Issue reported from  Round ID: [142202](https://scrubby.melonmesa.com/round/142202) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1526

1: Get nightmare
2: Face off against mech (odysseus, ripley, clarke, whatever)
3: Realize you cannot disable their light, unlike every other lightsource in the game.

**Comment by LemonInTheDark** [comment]
Mechcode moment

**Comment by ShizCalev** [comment]
to be fair, there's a bunch of things that were missed with it.
