### ISSUE TITLE
Police whistle on neck slot missing spirte.

### ISSUE THREAD

**Issue by Tumesuo** [tgstation/tgstation#52315]
Issue reported from  Round ID: [142261](https://scrubby.melonmesa.com/round/142261) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1515

![image](https://user-images.githubusercontent.com/15519576/87857105-c2abbb80-c92c-11ea-94e1-e76612cf9fcd.png)

**Comment by ShizCalev** [comment]
#51776
