### ISSUE TITLE
High Pop Bagil time dilation escalating very badly over time.

### ISSUE THREAD

**Issue by SkeletalElite** [tgstation/tgstation#52324]
## Round ID: 

Like every high pop bagil round

## Testmerges:
#51786: '[READY] Wounds part 2: Piercing wounds, dismemberment changes, housekeeping' by Ryll-Ryll at commit e60573245f

## Reproduction:
Just play a round on high pop bagil, the time dilation shoots up, it's obnoxiously laggy by around the 40 minute mark. Round 142293 had a singulo release and time dilation hit over 200% and stayed like that until the very end. The game time was around 1 hour, but the time on statbus is almost 2. It's happening every single round basically, not all of them get as bad as that, but there's clearly a problem.

**Comment by ShizCalev** [comment]
#52333 #52334 #52337

6k+ runtimes in 20 minute rounds, possible causes.

**Comment by Jared-Fogle** [comment]
Not sure that's related. Round in question did not have those.

![image](https://user-images.githubusercontent.com/35135081/87871347-6cf30580-c964-11ea-9e4d-8389021235fb.png)

**Comment by Tharcoonvagh** [comment]
>play on basil

**Comment by nightred** [comment]
Closing this as we have several issues open for run times happening during high time dilation.
