### ISSUE TITLE
metabolise addiction runtiming a few thousand times a round

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#52333]
runtiming a couple thousand times a round

```
[xx:xx:xxx] Runtime in holder.dm, line 384: Cannot create objects of type null.
 proc name: metabolize (/datum/reagents/proc/metabolize)
src: /datum/reagents (/datum/reagents)
call stack:
/datum/reagents (/datum/reagents): metabolize(xxxxxxx (/mob/living/carbon/human), 1, 0)
the liver (/obj/item/organ/liver): on life()
Kel Thuzad (/mob/living/carbon/human): handle organs()
Kel Thuzad (/mob/living/carbon/human): Life(2, 1662)
Kel Thuzad (/mob/living/carbon/human): Life(2, 1662)
Mobs (/datum/controller/subsystem/mobs): fire(1)
Mobs (/datum/controller/subsystem/mobs): ignite(1)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```

https://github.com/tgstation/tgstation/blob/0f9f74061fa896b819b05944d5fe6139b609f68f/code/modules/reagents/chemistry/holder.dm#L350-L390

**Comment by ShizCalev** [comment]
![image](https://user-images.githubusercontent.com/6209658/87870511-b1879c80-c976-11ea-8cf0-adfa47b27dee.png)

one of these are likely involved.

**Comment by ShizCalev** [comment]
note from player:
`all i can contribute is that it might have something to do with the party pod or the reagents it puts in you`

**Comment by Jared-Fogle** [comment]
Could reproduce. Once putting a human in a party pod and pressing the buttons, they stopped metabolizing. I'll submit a fix.

![image](https://user-images.githubusercontent.com/35135081/87870914-3962ac00-c961-11ea-8a44-36d712c8fc80.png)

**Comment by Jared-Fogle** [comment]
Making the PR soon, but I figured out the issue. `addiction_type` is set in `New`, but `colorful_reagent` overrides `New` and doesn't call its parent. I'm marking `/datum/reagent/New` as `SHOULD_CALL_PARENT(TRUE)` to resolve the issue.
