### ISSUE TITLE
Contractor return pod isnt working

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#52340]
## Round ID:
[142316](https://scrubby.melonmesa.com/round/142316)

## Reproduction:
Get kidnapped by a contractor and sent to ninja jail. Wait out the timer, once you are supposed to go back you instead get sent to the gem room due to being nullspaced. The items supposed to be sent on the same pod does show up on the turf.
See /datum/syndicate_contract/proc/returnVictim(var/mob/living/M)
The items that are sent home with you on the same pod somehow shows up at the destination.

Possibly related to pod rework @MrDoomBringer

**Comment by kriskog** [comment]
No relevant runtimes

**Comment by MrDoomBringer** [comment]
oh fug

**Comment by MrDoomBringer** [comment]
https://github.com/Fikou/tgstation/pull/1
this is the fix, #52346 will merge it in soonish I think
