### ISSUE TITLE
Weird cyborg vision bug

### ISSUE THREAD

**Issue by ReplicantTerry** [tgstation/tgstation#52349]
Issue reported from  Round ID: [142336](https://scrubby.melonmesa.com/round/142336) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

When I was borged, my vision became very fucky in that every tile I could see normally was a red square and every tile I couldn't see was space. I ghosted and my vision became normal, and when I was put back into my borg body by an admin, the vision glitch persisted.

![image](https://user-images.githubusercontent.com/53139748/87880751-1b8e5900-c9ec-11ea-82aa-718d6128dceb.png)

Image attached to describe what I mean.

Reporting client version: 513.1527

**Comment by Sealed101** [comment]
IIRC this was an issue on the verge of two byond versions that have involved rendering issues. also terry moments.

haven't seen em again since then.
