### ISSUE TITLE
Secret Sauce recipe not working

### ISSUE THREAD

**Issue by liamcchandler** [tgstation/tgstation#52352]
Issue reported from  Round ID: [142351](https://scrubby.melonmesa.com/round/142351) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1527

|•6u of Tea
|•3u of Space Lube
|•5u of Salicylic Acid
|•10u of Flour
|With following present: •1u of Carpotoxin
|Mix slowly in bucket above 243 degrees.

I have all the ingredients in a bucket from botany and heated above 243degrees
https://imgur.com/6w7kRXK
The recipe was found the previous round so I doubt it is out of date

**Comment by ShizCalev** [comment]
The ingredients are randomized every 7 days.

You'll have to find a paper with the secret recipe every round to learn what the new ingredients are (it's hidden on a space ruin, and an icemoon ruin.)

Good luck :)

**Comment by Iatots** [comment]
Smiley face at end of comment = you deserve to get rekt.

shiz status: rekt by AnturK
