### ISSUE TITLE
You can't throw hats onto heads

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#52372]
## Round ID:
[142394](https://scrubby.melonmesa.com/round/142394)

## Reproduction:
Pick up a hat and try to throw it on someone else, they get hit by it and it falls next to them.

**Comment by ATH1909** [comment]
Which hat(s) did you use for this?

**Comment by RaveRadbury** [comment]
> Which hat(s) did you use for this? Certain hats are specifically not able to be thrown onto other people's heads.

Breh, do you think I used a hat that I had never thrown on a head before? It was the beret, which I've thrown onto a head many times.
