### ISSUE TITLE
[found by Fulpstation][Reddit] The Syndicate mothership's turrets fire at clown op reinforcements

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#52386]
![image](https://user-images.githubusercontent.com/42606352/88016964-3f37c900-caea-11ea-9cc4-62d7f974f70e.png)

Clown ops get their own special reinforcements to buy (instead of normal nuke op reinforcements), and apparently, they don't get recognized as being operatives by the Syndicate mothership's turrets.

**Comment by LemonInTheDark** [comment]
have you tested it? This is reddit after all

**Comment by ATH1909** [comment]
Hugbug tested it: https://cdn.discordapp.com/attachments/326831214667235328/735059215734800394/unknown.png

**Comment by Fikou** [comment]
reddit

**Comment by Tlaltecuhtli** [comment]
can we add a reddit tag here?

**Comment by nightred** [comment]
This issue is not recreate able on TG code at this time.
![clownop turrets](https://user-images.githubusercontent.com/6491940/88204701-4dccd000-cc11-11ea-8f66-3deb8b39679d.png)

Please close issue.
