### ISSUE TITLE
Heretics are killed by their own ash ascension ability

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#52396]
#### Round ID:
[142442](https://scrubby.melonmesa.com/round/142442) Basil. 

#### Reproduction:

1. Observe Mitch Jones successfully ascend as ash heretic. 
2. He activates his fire aura and nearly instantly enters crit and dies. 

![200721 1311 12](https://user-images.githubusercontent.com/46400996/88048525-c705ed80-cb53-11ea-9241-bca2f3c5a6e4.png)

**Comment by ATH1909** [comment]
@EdgeLordExe

**Comment by EdgeLordExe** [comment]
oh shit

**Comment by TheSilverNuke** [comment]
Still occurring #142529
