### ISSUE TITLE
Ghosts can buckle people to cyborgs

### ISSUE THREAD

**Issue by CoffeeDragon16** [tgstation/tgstation#52404]
Issue reported from  Round ID: [142464](https://scrubby.melonmesa.com/round/142464) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1526
On shift 142457 Me and other people could buckle people to cyborgs as ghosts. I didn't get to test it but I could do it to a dead guy buckled into a stasis, onto a mediborg. I observed but a guy who died naturally could do it too. I'd include more images and stuff but it was in a previous shift. This could probably get abused pretty hard.

**Comment by ATH1909** [comment]
oh, that's still a thing?

**Comment by nightred** [comment]
This also opens the inventory of the dragged mob, now that is odd.

**Comment by MrMelbert** [comment]
https://github.com/tgstation/tgstation/issues/47629 lol
