### ISSUE TITLE
Standing on a Janitor Cart as a Engineering borg prevents you from using any of your tools.

### ISSUE THREAD

**Issue by legoscape** [tgstation/tgstation#52438]
>Become borg
>Stand on Janitor cart 
>Has a floor buffer for chadness
>breaks every tool in engineering borg slot.

**Comment by brotherbeyondd** [comment]
This happens when buckling to anything as a borg, you need to disable then re-enable your modules. As a sidenote, buckling borgs when fighting them is HIGHLY effective. The slots only break if they attempt to use them, though, I believe.

**Comment by MrMelbert** [comment]
this is actually intentional / not a bug
https://github.com/tgstation/tgstation/blob/372d9d7aeb94fa3ce321ebb92567cd3eb8b92dc3/code/_onclick/cyborg.dm#L63-L65

**Comment by legoscape** [comment]
After being unbuckled you are still incapacitated for a long period of time even if you are able to move around.
