### ISSUE TITLE
Disconnecting after taking holoparasite/guardian roll causes issues

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#52443]
## Round ID:
[142617](https://scrubby.melonmesa.com/round/142617)

## Reproduction:
Assume this was the cause. Inject holoparasites, roll for ghost role with second account. Disconnect second account. You should get the roll, but the owner should not get the guardian tab. 

```
[16:21:03] Runtime in guardian.dm, line 600: Cannot execute null.enslave mind to creator().
proc name: spawn guardian (/obj/item/guardiancreator/proc/spawn_guardian)
usr: Kieth4/(Lukas Beedell)
usr.loc: (Cargo Maintenance (164,156,2))
src: the holoparasite injector (/obj/item/guardiancreator/tech/choose/traitor)
src.loc: the satchel (/obj/item/storage/backpack/satchel)
call stack:
the holoparasite injector (/obj/item/guardiancreator/tech/choose/traitor): spawn guardian(Lukas Beedell (/mob/living/carbon/human), "PhillipF")
the holoparasite injector (/obj/item/guardiancreator/tech/choose/traitor): attack self(Lukas Beedell (/mob/living/carbon/human))
Lukas Beedell (/mob/living/carbon/human): Activate Held Object()
activate_inhand (/datum/keybinding/mob/activate_inhand): down(Kieth4 (/client))
Kieth4 (/client): keyDown("Z")
```

The rest of the runtimes this round happened after the holoparasite was offered to ghosts. May be related, may also need fixing.

**Comment by nightred** [comment]
Only happens if it is not a random guardian type.
The ghost role user has to disconnect while the type is being selected.

**Comment by kriskog** [comment]
Needs to recheck client etc after the input then
