### ISSUE TITLE
See runechat emotes preference does not work

### ISSUE THREAD

**Issue by Wayland-Smithy** [tgstation/tgstation#52449]
#### Round ID: All since introduction of the feature + Local Server
Running /tg/ revision: 2020-07-23
origin/master: cec6cbfa65034022a39c0653743baacc3cc0538a

## Reproduction:

- Toggle "See runechat emotes" to Disabled
- Proceed to still see emotes regardless.

Toggling "Show runechat.." altogether works fine and seems to take effect immediately. Even after clicking "Save Setup" the emote option does nothing.

![image](https://user-images.githubusercontent.com/64715958/88352504-d715fc80-cd0e-11ea-9ee1-34c33226b0d6.png)

**Comment by optimumtact** [comment]
simple fix remove the preference

**Comment by Wayland-Smithy** [comment]
@Rohesie Any ideas? My BYOND is v513.1528 and "Clear Cache" is of no help.
