### ISSUE TITLE
The ratvar ruin and the ashlizard home have unmixed gas on roundstart

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#52460]
Pls fix
![image](https://user-images.githubusercontent.com/58055496/88370850-ba49eb00-cd47-11ea-8408-741b472b3d26.png)

**Comment by kriskog** [comment]
Again?

**Comment by LemonInTheDark** [comment]
There's more, in this case it's mostly the fucking ratvar tiles

**Comment by LemonInTheDark** [comment]
more 
![image](https://user-images.githubusercontent.com/58055496/89113848-e988e800-d42a-11ea-9bd6-f74c12931fab.png)
