### ISSUE TITLE
Space vines with aggressive spreading deal friendly fire

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#52471]
#### Round ID:
Terry 142692. 

Reproduced locally. 

#### Reproduction:

- Plant kudzu. 
- Find kudzu with "aggressive spreading". 
- Spawn some podpeople and venus human traps in it. 
- Look at it. 

#### Result: 
The vines constantly circle-expand into neighbor tiles (including vined tiles), which explodes everything on them, podpeople and even venus human traps. 
![200724 2118 35](https://user-images.githubusercontent.com/46400996/88427490-4c5afd80-cdf3-11ea-921c-f3e73b67713e.png)

This is vines without the vine eater trait. Definitely not intended behavior. 

#### Expected result:
Vines don't try to spread to tiles that already have vines. Vines also shouldn't explode things from same faction, like podpeople or human traps. 

When venus human traps are killed this way I also get a runtime, which is probably unrelated:
```
[21:34:48] Runtime in unsorted.dm,1129: addtimer called with a callback assigned to a qdeleted object. In the future such timers will not be supported and may refuse to run or run with a 0 wait
  proc name: stack trace (/proc/stack_trace)
  src: null
  call stack:
  stack trace("addtimer called with a callbac...")
  addtimer(/datum/callback (/datum/callback), 10, 4)
  the venus human trap (/mob/living/simple_animal/hostile/venus_human_trap): clear fullscreen("brute", 10)
  the venus human trap (/mob/living/simple_animal/hostile/venus_human_trap): update health hud()
  the venus human trap (/mob/living/simple_animal/hostile/venus_human_trap): updatehealth()
  the venus human trap (/mob/living/simple_animal/hostile/venus_human_trap): adjustHealth(30, 1, 0)
  the venus human trap (/mob/living/simple_animal/hostile/venus_human_trap): adjustHealth(30, 1, 0)
  the venus human trap (/mob/living/simple_animal/hostile/venus_human_trap): adjustHealth(30, 1, 0)
  the venus human trap (/mob/living/simple_animal/hostile/venus_human_trap): adjustBruteLoss(30, 1, 0)
  the venus human trap (/mob/living/simple_animal/hostile/venus_human_trap): ex act(3, null, null)
  Explosions (/datum/controller/subsystem/explosions): fire(0)
  Explosions (/datum/controller/subsystem/explosions): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
```

**Comment by Angustmeta** [comment]
#18540 This PR added the immunity. 

```
/datum/spacevine_mutation/aggressive_spread/on_spread(obj/effect/spacevine/holder, turf/target)
target.ex_act(severity, src) // vine immunity handled at /mob/ex_act
```

This immunity mention has since been removed. Time to check git blame. 

Okay, it was changed by #50594. 

So here is the current problem. 
https://github.com/tgstation/tgstation/blob/2a0fa0d6bd789a6fd6642e9dac716b17e6a13712/code/modules/events/spacevine.dm#L148-L157

This has no immunity check at all. And it seems to explode entire turf instead of only exploding non-immune mobs. 

Maybe I can find some code to copy and add an !isvineimmune check there somewhere. And change it from hitting turf.

**Comment by ATH1909** [comment]
wew

**Comment by ATH1909** [comment]
So, how do we fix this?

**Comment by Angustmeta** [comment]
Considering copy pasting stuff from the burning oil crossbreed

**Comment by IndieanaJones** [comment]
Yikes!
