### ISSUE TITLE
Putting an ID in a civilian bounty terminal forcibly opens the UI for everyone standing next to it

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#52485]
Pretty explanatory. Put your ID in one of the consoles while someone stands next to it, UI is open for the other person as well as you.

Issue reported from  Round ID: [142716](https://scrubby.melonmesa.com/round/142716) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1526

**Comment by Iatots** [comment]
Also you hit the console with the id.
