### ISSUE TITLE
Multi-z Cable Layers cannot be deconstructed, and they also uproot any existing wires on the tile.

### ISSUE THREAD

**Issue by ArcaneMusic** [tgstation/tgstation#52490]
## Reproduction:

Multi-z cable layers, when constructed, cannot be removed by regular expected means (Wirecutters, crowbar, etc), and as a result,  can create a massive mess when built in high density areas like hallways, and especially on non-multiz maps. It will also actively uproot cables when built above the floor plating, resulting in just piles of wires and visual clutter everywhere with no way to remove any of it.

**Comment by Dennok** [comment]
Multi-z cable layers and Hub can be deconstructed when you remove flooring to pating. 
There is ability to craft it in hand instead of placing like cabble, that allow to bypass checkings for plating turf.
