### ISSUE TITLE
There is a way to destroy everyone's ears

### ISSUE THREAD

**Issue by trerri** [tgstation/tgstation#52505]
Issue reported from  Round ID: [142765](https://scrubby.melonmesa.com/round/142765) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1526

Some shitter was playing megalovania on piano on the shuttle and managed to play it at 100000 dB until the cacophony was unbearable. Sadly he had stealth armor and genetics shit, so nobody got him until the end of the ride. The worst part is the time dilation which made it even harder to kill him

**Comment by ATH1909** [comment]
based

**Comment by trollbreeder** [comment]
Give this the fuck tag please

**Comment by MrDoomBringer** [comment]
this is the funniest shit i've read in a while

**Comment by MrDoomBringer** [comment]
note that it's probably related to the #51459 testmerge

**Comment by Time-Green** [comment]
@silicons can you look at this? Baystruments was testmerged at the time. If it was that I'll close the issue

**Comment by legoscape** [comment]
The Baystruments have been having huge issues with even producing sound in game.

**Comment by optimumtact** [comment]
report on the PR instead pls
