### ISSUE TITLE
Vend-A-Tray Duplication

### ISSUE THREAD

**Issue by FinalBeatdown** [tgstation/tgstation#52504]
Issue reported from  Round ID: [142757](https://scrubby.melonmesa.com/round/142757) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1517

so i crafted a vend a tray from a machine frame but after screwdrivering it to create the machine the frame stayed behind. using the screwdriver again just creates a duplicate vend a tray each time you click the "finished" machine frame.

**Comment by ArcaneMusic** [comment]
Runtiming due to vend-a-trays not being native machines.
