### ISSUE TITLE
Tracking beacons can be added to piloted, locked, DNA-locked mechs

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#52500]
## Reproduction: Spawn/build a mecha, go inside it and both DNA lock and access modification lock it,  then turn maint protocols off. Have yourself or a buddy walk up and add a tracking beacon, somehow, through all that protection.

Conclusion: tracking beacons shouldn't be able to be just 'stuck' to the outside of the mech otherwise they'd probably stop working/fall off under stress like moving, being shot at, melted, etc. If it's going to be that easy to add a tracking beacon they should probably start with a irremovable one to begin with.

**Comment by Timberpoes** [comment]
Tracking beacons are external.

All the internal locks in the world do not phase the tracking beacon. It just gets permanently affixed to the outside of your mech.

**Comment by zxaber** [comment]
Back when I was in the business of mech nerfs, I actually did almost add pre-installed tracking beacons to all combat mechs. I ended up folding against the pushback and compromised with just making the EMP effects not destroy beacons (they used to be single-use for the EMP) and buffing EMP effects on mechs in general. A big part of that choice *was* because tracking beacons can just be duct taped onto a mech from the outside.

**Comment by githubuser4141** [comment]
> Tracking beacons are external.
> 
> All the internal locks in the world do not phase the tracking beacon. It just gets permanently affixed to the outside of your mech.

I guess, but wouldn't it need to be actually plugged into the mech to EMP it? And it'd need to be securely fastened so gunfire/movement + the duress of being attached to a _combat_ mech wouldn't make it fall off/break. Plus mechs are supposedly heatproof (a gygax is heatproof to all but concentrated plasmafires) and acid proof so it'd make sense that without maint. protocols on there's no actual place to put the beacon without it falling off. Plus it's a bit annoying that it requires 0 cooperation on the part of a traitor roboticist's part since you can just slap it on then EMP it to death via a console.

**Comment by ATH1909** [comment]
it'd also be nice if there was a way to remove them from your mech by, say, climbing out of your mech and prying the beacon(s) off with something.
