### ISSUE TITLE
Pulsing the power wire shocks you repeatedly unless you close tgui

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation#52538]
## Reproduction:
Open a door with screwdriver, find and pulse the power wire.

Watch as you get repeatedly shocked in a loop.

Close the tgui window, watch as the shocks stop

workarounds: Leave in game as a punishment for anyone who likes javascript?

**Comment by TemporalOroboros** [comment]
I'm pretty sure this is an _old_ one.

**Comment by Dennok** [comment]
For see weires you need insert your head in mschine.

**Comment by TemporalOroboros** [comment]
In that case, if the airlock opened while you were perusing the wires wouldn't it crush your skull or neck against the frame?

**Comment by KathyRyals** [comment]
I'm proud because I bonded over a shocked door with oranges. Truely a great moment.
