### ISSUE TITLE
i turned into a snail and noclipped through half the station

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#52537]
roundID 142890

so i injected myself with genes past 100 instability, and started turning into a snail
once the transformation was complete, i suddenly turned transparent, started moving left extremely fast and through all possible physical barriers including doors tables and walls, until i manually moved and stopped noclipping

i dont know

**Comment by optimumtact** [comment]
nevermidn apparently this isn't a bug, just one of the mutations can give you the go away status effect, which phases you in a random direction.
