### ISSUE TITLE
AIs cant regain control of their power APC if power is disabled.

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#52548]
Issue reported from  Round ID: [142937](https://scrubby.melonmesa.com/round/142937) (/tg/Station - Terry [EU] [100% FREE LAG])

Reporting client version: 513.1526

No test merges.

Have your power shut off at the APC with the on-->off as an AI.
Flavour text goes on for about 45 seconds and when the one saying ya have regained control (which is meant to open the APC menu) appears it... Just doesn't open.
![image](https://user-images.githubusercontent.com/68032262/88600072-3fdddb80-d065-11ea-9b90-e39312ee6146.png)

After that lovely flavourtext, nothin happens.

**Comment by Kaffe-work** [comment]
I blame #52085 but the code in  tgstation/code/modules/mob/living/silicon/ai/life.dm is horrendous. It has something to do with the override now checking if the user is able to open windows, but I'm not well versed in how tgui 4.0 works. @Ryll-Ryll
