### ISSUE TITLE
AI cyborg shell duping issue

### ISSUE THREAD

**Issue by ZeeTR** [tgstation/tgstation#52542]
Reporting client version: 513.1514

If you build a cyborg endoskeleton and do not complete it, you can remove the battery from the frame with a screwdriver. After this, when adding a BORIS module, it dupes a completely new, completed AI endoskeleton.

**Comment by TheMidnightRose** [comment]
I would also point out this might be due to an issue that has been prevalent for a while where dead AI shells cannot be reconnected to their AI when restored.
