### ISSUE TITLE
Being turned into a Ghoul/Brain Transfer/X-ray eyes" removes your ability as a heretic to see influences

### ISSUE THREAD

**Issue by NamelessFairy** [tgstation/tgstation#52554]
## Round ID: 
[142973](https://scrubby.melonmesa.com/round/142973)

## Reproduction:
During a round as a heretic I experienced; being turned into a Ghoul, a Brain Transfer and having X-ray eyes installed, one of these three events caused me to be unable to to see Influences. When right clicking on a location where an influence was I was still able to see them on the dropdown they just did not appear in game for me. I still had access to my Manus Grasp and I can only assume other heretic abilities although I did get a chance to test the passives.
I was turned into a ghoul by another heretic, after being revived I still retained my objectives in the notes tab. The body my brain was transferred was a humanized monkey from genetics using my DNA. the X-ray eyes were installed soon after.
In terms of reproduction all these events should be tried to confirm which caused it (I don't have the ability to test all of these myself). all 3 of these events should be simple to replicate, a second (flesh) heretic can ghoul the corpse of a heretic near a unused influence. A heretics brain can be transferred to a humanized genetics monkey to see if the heretic can see influences and installation of x-ray eyes follows the same method with just replacing a heretics eyes.
Apologizes in advanced for my inability to explain in more detail or test certain situations myself.

**Comment by ATH1909** [comment]
@EdgeLordExe
