### ISSUE TITLE
The ringing in your ears grows louder, blocking out any external noises for a moment.

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#52558]
![image](https://user-images.githubusercontent.com/20996272/88685215-a0186000-d0ed-11ea-98fb-8b9c553eee04.png)

with very large amounts of ear damage (boris gave me 5000), chat gets an ear-ringing message every life tick, just in case you forgot that your ears are ringing
![image](https://user-images.githubusercontent.com/20996272/88685650-12894000-d0ee-11ea-8361-ac34e104aa7a.png)
it's also very irritating to listen to

**Comment by ShizCalev** [comment]
tinnitus is a bitch.
