### ISSUE TITLE
IV sucker deleting contents in beaker.

### ISSUE THREAD

**Issue by legoscape** [tgstation/tgstation#52564]
I filled a beaker of Cryodoxadone and put it on a suck mode. I attached it to a monkey and it deleted all the contents in the beaker and replaced it with the blood it received from the monkey.

**Comment by ArcaneDefence** [comment]
Cryoxadone and blood react to make synthmeat. It will continue to fill the beaker in the IV with blood until it cannot make any more synthmeat. 
That synthmeat is put on the turf the IV stand is on. This is intended behavior.
