### ISSUE TITLE
Medibot made from adv medkit is not healing all type of damages

### ISSUE THREAD

**Issue by panvxv** [tgstation/tgstation#52560]
Issue reported from  Round ID: [142989](https://scrubby.melonmesa.com/round/142989) (/tg/Station - Terry [EU] [100% FREE LAG])

Reporting client version: 513.1527

As like in title:
Medibot made from advance medkit (red medkit that cost 1100) is healing only brute.
Also this medibot doesn't have diffrent sprite, it looks like normal one.
I tested now on solo server: medibot will not heal other type of damages if it is made from crafting menu.

**Comment by ATH1909** [comment]
what if you craft it without using the crafting menu?

**Comment by ATH1909** [comment]
@ExcessiveUseOfCobblestone

**Comment by ExcessiveUseOfCobblestone** [comment]
Known issue, Crafting menu doesn’t allow for post created modifications. The fix is prob just to remove the table recipe

**Comment by ShizCalev** [comment]
#51694

**Comment by timothymtorres** [comment]
I tested this on local.  I created an medibot with an advanced medkit and it healed all types of damage.  I'm pretty sure #54907 fixed this.
