### ISSUE TITLE
bounty station asks for burning things, despite not being fireproof.

### ISSUE THREAD

**Issue by jtroopa** [tgstation/tgstation#52581]
Issue reported from  Round ID: [143095](https://scrubby.melonmesa.com/round/143095) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

The bounty station in cargo called for five sets of lit bonfires. I managed to send two of them before the bounty pad was destroyed. Seems like an oversight; either the pad should be fireproof, or the station need not ask for things that can destroy it.

**Comment by nightred** [comment]
Did you light a fire under the bounty board?

**Comment by jtroopa** [comment]
lit the bonfire on top of the telepad.

**Comment by nightred** [comment]
Bring a fire extinguisher and move fast?
This is like cargo being asked for a tesla on the shuttle, it is hard might wreck up the joint, but is doable if you are willing to put in the effort.

**Comment by jtroopa** [comment]
That's a swell plan except it takes... what, 3-5 seconds for the teleporter to energize?
