### ISSUE TITLE
Layer 1 pump sprite off by one pixel

### ISSUE THREAD

**Issue by Helianthus00** [tgstation/tgstation#52609]
## Reproduction:
Place a direction 1/2 on pump on layer 1. It is off by one pixel to the right. This isn't present in directions 4/8. Nor is this present in game. Only viewable via dream maker or strongdmm.

**Comment by Donkie** [comment]
Cannot reproduce ingame nor DM's map editor
![image](https://user-images.githubusercontent.com/2332094/91082500-09d24e00-e649-11ea-9889-4f2d379d478f.png)
![dreamseeker_2020-08-24_20-24-32](https://user-images.githubusercontent.com/2332094/91082527-148ce300-e649-11ea-817c-26764f8cdcde.png)

**Comment by Helianthus00** [comment]
Funny, I can't reproduce it in strongdmm now either. Closing the issue.

**Comment by Helianthus00** [comment]
Well, I found it again. It's only the on the "on" pumps. Though this isn't reproducible in game. I really have no idea what is wrong, but it's reproducible in both strongdmm and dream maker, so it seems like a valid issue. 
![issue](https://user-images.githubusercontent.com/64755361/91119273-068e9080-e650-11ea-958c-64c21ee877fb.PNG)
![issue2](https://user-images.githubusercontent.com/64755361/91119275-08585400-e650-11ea-9b85-333334c16df4.PNG)
![issue3](https://user-images.githubusercontent.com/64755361/91119277-09898100-e650-11ea-8891-fed514921552.PNG)
