### ISSUE TITLE
Visual look of a cult tile can be put in a crate and moved

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#52623]
## Reproduction:

Make cult tile (The one from pylons, /turf/open/floor/engine/cult). You can grab their visual overlay with a crate and take it somewhere else. 

(Cult tiles have that overlay so they aren't visual on mesons)

**Comment by TemporalOroboros** [comment]
Dupe of #52557

**Comment by Time-Green** [comment]
Duplicate of #50978
