### ISSUE TITLE
xenomorphs can't bash doors down without acid

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#52645]
Using harm intent slashes on a door as a xeno will let you damage the door up to a certain point, then make you unable to damage it. The door won't be, well, open in this damaged state, so the only way you can damage it further is with acid. This doesn't seem intentional.

**Comment by ATH1909** [comment]
Oh, I see the problem now- xenos can't attack shocked doors. You don't receive any in-game indication that you're supposed to be shocked (or that that's why you're unable to attack the door), though... Are xenos immune to door shocks? If so, we could just remove the code that stops xenos from attacking shocked doors.

**Comment by SkeletalElite** [comment]
I don't think they are supposed to be immune to shocks, even if they currently are.

**Comment by GunHog** [comment]
Xenos should not be immune to shocks. They are weak to burn damage. The solution to an electrified airlock should be acid, cutting the power via APC destruction, or finding a different point on entry.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/263c51d2db3ff028abf5232b8414a6d7095a850c/code/game/machinery/doors/airlock.dm#L401-L417

https://github.com/tgstation/tgstation/blob/263c51d2db3ff028abf5232b8414a6d7095a850c/code/game/machinery/doors/airlock.dm#L1179-L1204

**Comment by GunHog** [comment]
That is an easy fix, at least.

**Comment by ATH1909** [comment]
Maybe we should make the check instead be if(isElectrified() && shock(user, 100))?
