### ISSUE TITLE
Ethereals turned into lizards still require charge

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#52658]
Issue reported from  Round ID: [143307](https://scrubby.melonmesa.com/round/143307) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1526

So I turned myself into a lizard using lizard mutation toxin from xenobio on round [143307](https://sb.atlantaned.space/rounds/143307)

I still had the icon for charge, and was slowly losing it. I also had to eat meat alongside of getting charged. Normal methods such as using a battery or touching a lightbulb failed due to my species change.

**Comment by TheSilverNuke** [comment]
Just learned this applies to any species an Ethereal changes into, not just specifically lizards.

**Comment by Kaffe-work** [comment]
lizard go bzzzzzt
