### ISSUE TITLE
You can delete small-sized items with the power of tray magic.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#52666]
Reproduction:
1) Get a proper tray from autolathe.
2) Place a small/tiny item on the tray.
3) Put the tray into the autolathe.
4) Go on deleting spree of valuable items like CMO's hypospray or Krav Maga gloves just because you can do that.
5) Probably deny some greentexts in the process, but who cares, deleting items is fun.

**Comment by TemporalOroboros** [comment]
Please tell me this doesn't work on the nuke disk.

**Comment by zxaber** [comment]
If the nuke disk is deleted, it automatically respawns.

**Comment by ArcaneDefence** [comment]
I fail to see how this is an issue when cremating, acid, explosions, fires, the recycler, and cooking oil all delete things rampantly.
