### ISSUE TITLE
If you use sticky tape multiple times very fast on an item, it will be wrapped multiple times

### ISSUE THREAD

**Issue by cyclowns** [tgstation/tgstation#52673]
## Round ID:
[143356](https://scrubby.melonmesa.com/round/143356)

## Reproduction:

1) Click on something a bunch of times with sticky tape without waiting
2) Wait for all of the progress bars to finish
3) See that the object is wrapped, like, 5 million times

The reason I'm pretty sure this is a bug is because you actually aren't allowed to wrap something in sticky tape if its already finished being wrapped. However, if you just start wrapping it a bunch and wait for them all to finish, it never checks if its already covered. 

![image](https://user-images.githubusercontent.com/19853115/89116918-2b775580-d44e-11ea-8856-b62fffb2b5a4.png)

don't fix this its funny

**Comment by optimumtact** [comment]
@Ryll-Ryll nice code you doughnut
