### ISSUE TITLE
Rust heretics can't rust 90% of the floor tile types in the game

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#52678]
## Round ID:
Doesn't apply

## Testmerges:
Also doesn't apply

## Reproduction:
Be rust heretic
Use the gamer hand on a floor tile that isn't snow, plating, or generic floor tile
Weep as it doesn't turn into rust

**Comment by Fikou** [comment]
will you encounter those other types anywhere in the game though

**Comment by Tharcoonvagh** [comment]
On the shuttle for example
Does this include uh reinforced plates or whatever theyre called

**Comment by Iatots** [comment]
shuttle is titanium and was made deliberately not to rust.
