### ISSUE TITLE
Runtime when uploading an AI back to a core from an intellicard.

### ISSUE THREAD

**Issue by KathyRyals** [tgstation/tgstation#52694]
## Round ID:
Discovered while testing locally.

## Reproduction:
Spawn as an AI, aghost, make a human, spawn an intellicard, card the AI and put it back. 
Runtime caused by `AI.battery = circuit.battery`, in the ai_core.dm file, line 323.
Error : `[extools] Runtime in /obj/structure/ai_core/transfer_ai: Cannot read null.battery`

I've tried to check the file a bit, but circuit is in scope and has a battery attribute so I can't see why it runtimed.

**Comment by ShizCalev** [comment]
circuit must've been null somehow

**Comment by ShizCalev** [comment]
does spawning an AI generate a circuit board?
