### ISSUE TITLE
AI shells unable to speak on all Communications channels despite hearing them all.

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#52698]
Issue reported from  Round ID:  (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1528

1) Be and AI.
2) Have a Shell.
3) Hear all comms but be unable to respond while in shell.

**Comment by san7890** [comment]
This same thing happened to me, but I know exactly why my shell couldn't respond over communication channels. Did your shell get EMP'd in any way? Shells are always meant to be able to have the same level of communication access their controller AI should, but getting EMP'd means your shell can hear, but not respond.

**Comment by TheMidnightRose** [comment]
No. Fresh shell. Tested across engineering and janitor varients that round. Only had access to the channels the type was supposed to have.

**Comment by Timberpoes** [comment]
This was probably caused by the PR that gave departmental cyborgs unique radio channels by default?

When working out the channels a cyborg can use, it doesn't make any checks to see if it's an AI or has an AI radio and only gives you the standard keys that shell would have if it were a normal cyborg.

**Comment by Mooshimi** [comment]
Give it a captain radio while ai is controlling it :)

**Comment by Sealed101** [comment]
can no longer reproduce; it's a bit janky to get the ai's radio channels to work on a shell with a selected module, but 
- fresh ai shell has access to all channels both for hearing and for speaking
- selecting a module does reset the channels, but you can't hear any department channels outside of that module's setting, i.e. command channel on an engineering shell
- reconnecting to the shell reintroduces the ai's channel list to the shell, enabling both speaking and hearing channels available to ai
