### ISSUE TITLE
Station budget can be drained directly via using B.E.P.I.S and a Departmental Card (Cargo Budget).

### ISSUE THREAD

**Issue by EddViBritannia** [tgstation/tgstation#52705]
143479 Round ID:

## Reproduction:
Station budget can be drained directly via using B.E.P.I.S and a Departmental Card (Cargo Budget). Click on B.E.P.I.S with the departmental card, then you can deposit as much credits as the station has. Afterwards click to withdraw the credits, this will come out as a credit chip, which can then be put onto any ID. This allows you to instantly drain the stations funds without alerting anyone.

**Comment by ATH1909** [comment]
*cargo's funds

**Comment by Tharcoonvagh** [comment]
Damn

**Comment by Tlaltecuhtli** [comment]
the bepis mechanics are really dumb anyway, why isnt it just a swipe to buy thing???

**Comment by ArcaneMusic** [comment]
> 
> 
> the bepis mechanics are really dumb anyway, why isnt it just a swipe to buy thing???

Because that is absolutely besides the point.


Also, as far as I'm concerned this is **not a bug**. You can link the cargo budget card to it if your keen on using cargo's funds to purchase BEPIS techs and rewards from it, otherwise I would have made it reject budget cards.
