### ISSUE TITLE
You can saw off shotguns with a syringe.

### ISSUE THREAD

**Issue by Pugie** [tgstation/tgstation#52715]
deranged

**Comment by necromanceranne** [comment]
That's a sharp needle.

**Comment by Kaffe-work** [comment]
regular syringes?

**Comment by Pugie** [comment]
regular syringes yes

**Comment by Tlaltecuhtli** [comment]
why are syringes sharp thats dumb as you can butcher with it

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/3d54be0e7dedeac5e1653254d900fc4c0429714d/code/modules/projectiles/guns/ballistic.dm#L467-L475

hm...

**Comment by ShizCalev** [comment]
oh. oh no.

**Comment by Kaffe-work** [comment]
ah, you saw that wonderful method too 🥇
