### ISSUE TITLE
You now slap people with surgical drapes when using them on someone

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#52735]
When using surgical drapes on someone, along with opening the menu, you will now also slap them with it. This kills my immersion, and didn't happen before.

Likely a result of #52295 .

**Comment by Timberpoes** [comment]
Yup. Component system is async.

It's a race condition.

**Comment by ArcaneMusic** [comment]
Was this fixed by the above PR?

**Comment by optimumtact** [comment]
No I don't believe so, it just makes issues easier to spot.

**Comment by SuperNovaa41** [comment]
Cannot reproduce, this probably no longer happens.
