### ISSUE TITLE
PDA traitor uplink is a black screen

### ISSUE THREAD

**Issue by Misha600** [tgstation/tgstation#52731]
Issue reported from  Round ID: [143550](https://scrubby.melonmesa.com/round/143550) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1528

Don't know how to reproduce it, and it's an absolute pain in the ass when you can't get your gamer gear.
https://gyazo.com/d16dc168f8e8b2a8434721eeff39b2dc

**Comment by Misha600** [comment]
Also i should note that the syndicate uplink part isn't the problem, the PDA just isn't accessible as traitor

**Comment by Misha600** [comment]
This might help: Admin PM from-CoffeeDragon16: yeah for some reason you weren't given an uplink thats odd.

**Comment by Misha600** [comment]
Actually, the PDA is broken for me even as a non antag.

**Comment by nightred** [comment]
What OS are you using?

**Comment by Misha600** [comment]
Windows 10
