### ISSUE TITLE
Invisible UI

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#52741]
For some gods forsaken reason, I got stuck with an invisible box over the game. That's the best and most concise way I can describe it. I have no idea what triggered it, It just happened.
Issue reported from  Round ID: [143613](https://scrubby.melonmesa.com/round/143613) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1528

**Comment by Time-Green** [comment]
Can you post a screenshot? That would help immensely

**Comment by unit0016** [comment]
![image](https://user-images.githubusercontent.com/50649185/89472125-b063b700-d74d-11ea-9b22-12115b2f01ed.png)
everything inside the box I cannot click.

**Comment by unit0016** [comment]
Update: Closing OVERWOLF of all things corrected the issue. As for why this happens, god only knows.
