### ISSUE TITLE
spooky summon ghost(s) stories from fulp

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#52747]
In a recent PR for Fulpstation, the Summon Ghosts ritual was disabled. In the replies for that PR, some issues were reported that I'd appreciate assistance in verifying (I am but one man, and by its very nature, Summon Ghosts bugs require multiple players to test):

1. **The Summon Ghosts ritual can cause runtimes and lag.** Do we have any error logs or reports of runtimes being caused by the Summon Ghosts ritual/large numbers of visible ghosts? If so, what interactions are causing them, and how can we fix them? Could the light emitted by visible ghosts be causing lag? Can visible ghosts even cause lag in 100+ player servers in the first place?
2. **There doesn't appear to be an easy way for admins to undo the effects of the Summon Ghosts ritual.** Do admins not have easy access to the set_observer_default_invisibility() proc? If so, we should give them an admin button or something that lets them toggle ghost visibility. Also, why does inputting 0 as a parameter for the set_observer_default_invisibility() proc make ghosts visible, while inputting a nonzero number as a parameter for the set_observer_default_invisibility() make ghosts invisible? Shouldn't it be the other way around?
3. **Visible ghosts can intercept clicks, essentially turning a ring of ghosts around a wizard into a minor anti-melee click shield.** This seems like the most concerning problem of the three, but I don't know how to easily test it on my own. Is there an easy way to set the click priority of ghosts so that they won't get in the way of normal clicks, but also won't become impossible to examine?

**Comment by Fikou** [comment]
[Reddit]

**Comment by ATH1909** [comment]
![image](https://user-images.githubusercontent.com/42606352/89561056-92de2e00-d7dd-11ea-9178-f9ca0ed5f7a8.png)
