### ISSUE TITLE
Civilian bounty console on ice box asks miners for mushrooms that do not grow in the ice caves

### ISSUE THREAD

**Issue by IanAbstract** [tgstation/tgstation#52742]
Issue reported from  Round ID: [143626](https://scrubby.melonmesa.com/round/143626) (/tg/Station - Terry [EU] [100% FREE LAG])

Reporting client version: 513.1528

Like I said in the title, the civilian bounty console will ask miners to bring it mushrooms that do not grow in the ice caves on ice box station.

**Comment by ArcaneMusic** [comment]
They can grow on icebox through the randomized terrain ruin still.
If you can't find them, it's possible to get them through xenobio and silver slimes.
If neither are available easily, you can always reroll the bounty after 5 minutes.
