### ISSUE TITLE
Golems are Immune to the Arm Rippies of Arnold Pizza. (also you can rename arnold pizza)

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#52756]
Golems can eat Arnold Pizza and be perfectly fine! This is criminal! At least, I think so anyway.

Also Arnold Pizza can be renamed and stuff. I think there was a big deal made about it being easy to identify.

**Comment by ATH1909** [comment]
intended; golems have TRAIT_NODISMEMBER.
