### ISSUE TITLE
Recyclers recycle their own mats when deconstructed

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#52779]
## Round ID:

143731 Sybil
## Testmerges:
N/A?

## Reproduction:
Create a recycler, have it be powered, then deconstruct it and it may eat its own materials including the board(?) I think it might technically still exist the exact moment it's deconstructed, leading to the mats being sizzled away and leaving the machine frame.

**Comment by Timberpoes** [comment]
Couldn't reproduce locally, however the board not appearing should be fixed by #52805 

What exactly do you mean by "eat its own materials" - As in, the matter bin and manipulator used in its construction?

**Comment by ZeroMODE0** [comment]
The matter bin and manipulator used in its construction disappear, and it made sizzling noises, so I assumed they were eaten by the recycler. Something to also note is that it was on a shuttle, I guess!

**Comment by tralezab** [comment]
Closed for the newer version of this issue
