### ISSUE TITLE
engis can roll tesla ball bounty on civvie bounty

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#52776]
the engi budget will never have enough cash to pay it maybe its time to make civvies bonty  its own list????

**Comment by Time-Green** [comment]
Also how are they gonna ship it? They’d have to build an entire containment zone and particle accelerator around the civilian bounty pad without destroying it

**Comment by Tharcoonvagh** [comment]
_well I mean if youre quick enough..._

**Comment by ArcaneMusic** [comment]
Intentionally left this in as more of a challenge than a bug.
That said, Tesla and singlo should probably be moved off of engineering bounties and into a special category instead, yeah.

**Comment by Winterous** [comment]
No longer the case since the bounty was removed with teslas.
