### ISSUE TITLE
managed to desync my camera from my body using a baseball bat and phase shift

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#52785]
Steps to reproduce:
1. Be a runic golem with a jetpack, roaming around in space on a test server.
2. Hit yourself with a baseball bat to go F A S T (I'm not sure if I got the faster baseball bat throwspeed or the slower one).
3. Jaunt (using the Phase Shift spell that runic golems innately get access to) to try to stop your momentum so you can go visit a space structure.
4. Realize that your camera has become desynced from your body.
5. A few seconds later, notice that your screen has become basically just black:
<img width="1440" alt="wizardbug2" src="https://user-images.githubusercontent.com/42606352/89696686-9e654e00-d8de-11ea-97aa-5ed2800e5793.PNG">
6. Fix the problem by reconnecting.

**Comment by Mooshimi** [comment]
you can fix this by hitting the "cancel camera view" verb top left of ooc tab

**Comment by Sealed101** [comment]
could not reproduce
neither does the bat have knockback capability, nor do runic golems exist; throwing a mob via build mode then using any cult phase spells given via VV did not cause this to happen during testing
