### ISSUE TITLE
Perpetual fire overlay

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#52791]
## Testmerges:
- #52458 

## Reproduction:

1. Acquire fire immunity (I used the chilling potion from xenobiology on an explorers suit, mask, jumpsuit, and NV mesons)
2. Acquire a large number of active fire stacks until you are completely engulfed in flames. (Fighting an ash drake at high ping will do)
3. Be extinguished (Use a fire extinguisher on yourself or have someone else do so for you)
4. Observe that, though you are no longer on fire, the fire overlay remains on you at the 'slightly burning' stage.
5. Continue to be doused by the guy with the fire extinguisher because it looks like you're still ablaze.

**Comment by nightred** [comment]
This is an interesting and long standing issue.
I will test further.
