### ISSUE TITLE
Blood-Drunk Miner couldn't move

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#52792]
## Testmerges:
- #52458 

## Reproduction:
1. Locate the blood drunk miner.
2. Carve out an expansive arena to fight them in.
3. Engage the blood drunk miner. (With a friend!)
4. Be confused when he wastes all of the time you spent carving out an arena by staying completely still, pursuing neither you, nor the person helping you.

##Expected Behavior:

I expected that the miner would charge me and/or teleport to me in an attempt to engage in melee. This did not happen.

**Comment by Sealed101** [comment]
still an issue

**Comment by Sealed101** [comment]
fixed by #83828
