### ISSUE TITLE
Cannot create Blackmarket Uplink after patch

### ISSUE THREAD

**Issue by WarlockD** [tgstation/tgstation#52803]
## Reproduction:
1. Stack all the parts on the floor to make the uplink.
2. Button to make it does not come up.

## More Info.
There was a pull to fix the uplink from eating your headset when you make it.  The pull put anything of subtype obj/item/radio in the blacklist.  Problem is that it also includes the type /obj/item/radio as that is the station radio.  This is not the REAL issue though.

The crafting menu only uses blacklist to check for requirements, NOT when building or deleting items.  because the blacklist is not checked when collecting the contents your headset comes up first on the list and that's what is deleted when making the uplink.  Trying to figure a simple way to fix it but might have to refactor part of the crafting system.

**Comment by WarlockD** [comment]
FUCK I HATE WHOEVER DID THIS 
```
/datum/component/personal_crafting/proc/get_environment(atom/a, list/blacklist = null, radius_range = 1)
    . = list()

    if(!isturf(a.loc))
        return

    for(var/atom/movable/AM in range(radius_range, a))
        if(AM.flags_1 & HOLOGRAM_1)
            continue
        . += AM
```
Why accept blacklist and NOT FUCKING USE IT ARRRR

**Comment by nightred** [comment]
Fixed in linked PR
