### ISSUE TITLE
Shuttle Wall Smoothing Is Fuck

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#52809]
## Round ID: 
I dunno like any round in the past few days

## Testmerges:
Doesn't matter

## Reproduction:
1. Have eyes
2. Locate shuttle
3. Use eyes on shuttle

![](https://cdn.discordapp.com/attachments/725529093746982933/741840896126877716/unknown.png)

![](https://cdn.discordapp.com/attachments/725529093746982933/741841013831892992/unknown.png)

**Comment by nightred** [comment]
The issue is with merging of areas and can smooth with lists.
