### ISSUE TITLE
Internal Martyrdom Mutation Doesn't work

### ISSUE THREAD

**Issue by halitosisman** [tgstation/tgstation#52822]
Issue reported from  Round ID: [143872](https://scrubby.melonmesa.com/round/143872) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1528

The thing it does doesn't happen.

**Comment by ATH1909** [comment]
I find it hilarious that the internal matyrdom mutation sucks so badly that nobody noticed that it was broken until now.

**Comment by ATH1909** [comment]
also, might be related to: https://github.com/tgstation/tgstation/pull/52810

**Comment by brotherbeyondd** [comment]
I feel like this is the first time it has ever been used.

**Comment by nightred** [comment]
I confirm this error, i had it done to me that round.
