### ISSUE TITLE
Suiciding with the moth plushie trapped my moth ghost in my moth body instead

### ISSUE THREAD

**Issue by Jared-Fogle** [tgstation/tgstation#52833]
## Round ID: [143907](https://scrubby.melonmesa.com/round/143907)

I suicided with the moth plushie and instead of being dusted like I usually do, my body was left behind. I couldn't move out of it, and typing Ghost and Suicide did nothing.

![dreamseeker_2020-08-09T20-29-50](https://user-images.githubusercontent.com/35135081/89750106-6b0df500-da7f-11ea-925b-0e7a6d299571.png)

Dead chat reported me as "(died as )".

![image](https://user-images.githubusercontent.com/35135081/89750076-444fbe80-da7f-11ea-8f99-e91ecaf52e8d.png)

The next person to suicide with this moth plush did, however, get dusted as normal.

**Comment by YPOQ** [comment]
similar runtime to #52801
```
[2020-08-10 03:29:11.658] runtime error: Cannot execute null.Cut().
 - proc name: Destroy (/mob/living/Destroy)
 -   source file: living.dm,36
 -   usr: (src)
 -   src: Mothblocks (/mob/living/carbon/human)
 -   src.loc: the floor (95,105,2) (/turf/open/floor/plasteel/white)
 -   call stack:
 - Mothblocks (/mob/living/carbon/human): Destroy(0)
 - Mothblocks (/mob/living/carbon/human): Destroy(0)
 - Mothblocks (/mob/living/carbon/human): Destroy(0)
 - qdel(Mothblocks (/mob/living/carbon/human), 0)
 - /datum/callback (/datum/callback): Invoke()
 - world: PushUsr(Mothblocks (/mob/living/carbon/human), /datum/callback (/datum/callback))
 - /datum/callback (/datum/callback): InvokeAsync()
 - Timer (/datum/controller/subsystem/timer): fire(0)
 - Timer (/datum/controller/subsystem/timer): ignite(0)
 - Master (/datum/controller/master): RunQueue()
 - Master (/datum/controller/master): Loop()
 - Master (/datum/controller/master): StartProcessing(0)
```

**Comment by Jared-Fogle** [comment]
Good eye. Yep, I do believe I had a disease.

**Comment by ATH1909** [comment]
the moth plushie consumed your soul

**Comment by ATH1909** [comment]
also, holy hell, this is a weird bug

can this go on that "top bugs of 2020" list?

**Comment by Jared-Fogle** [comment]
moths are already top bugs
