### ISSUE TITLE
Gun sprites are fucked

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#52838]
## Round ID:
No

## Testmerges:
Local

## Reproduction:
Spawn a gun that doesn't have a full sprite set

![image](https://user-images.githubusercontent.com/58055496/89763437-60675600-daa7-11ea-9918-41616a798148.png)
If it's got an external magazine and doesn't have the snowflake var set, each gun will need:
A mag icon
If it doesn't set the don't display ammo count var, each gun will also need a sprite for each of the 5 stages

go look at **`icons/obj/guns/projectile.dmi`** and cry

**Comment by timothymtorres** [comment]
Fixed by #52856

**Comment by LemonInTheDark** [comment]
Did that pr fix all of these? it didn't claim to

**Comment by timothymtorres** [comment]
That one plus some of these:

- #56754
- #58270
- #59580
- #60099

I double checked for recent bug reports for guns and sprites and my search came back empty.  Going to claim this as fixed unless there is definite proof of it still existing.
