### ISSUE TITLE
Issue: Freezer/Heater dismantlement 

### ISSUE THREAD

**Issue by SuspiciousMan** [tgstation/tgstation#52842]
Issue reported from  Round ID: [143954](https://scrubby.melonmesa.com/round/143954) (/tg/Station - Terry [EU] [100% FREE LAG])

Reporting client version: 513.1528

Usually when one  dismantles a machine, all of its parts will appear on the machine frame (such as: lasers, matter bins and circuit boards etc.) 
However, recently Freezers/Heaters when dismantled do NOT give the Circuit Board, as if its all of the sudden gone but do give the rest of the parts.

**Comment by nightred** [comment]
This was fixed by pr #52805
