### ISSUE TITLE
Multiple Tesla Coils In The Same Room Power Themselves Indefinitely

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#52851]
## Round ID:
Doesn't apply

## Testmerges:
Also doesn't apply

## Reproduction:
Make a room with several tesla coils in it, then use signallers and the like to pulse their wire repeatedly. 
The tesla bolts created by one will be collected by the other and turned into power, fill a room with tesla coils and now you have a room full of tesla coils that will never run out of power

**Comment by LemonInTheDark** [comment]
I swear to fucking

**Comment by LemonInTheDark** [comment]
How upgraded were they? I think I know this one

**Comment by Paxilmaniac** [comment]
t4

**Comment by Paxilmaniac** [comment]
upgraded stock parts were a mistake

**Comment by LemonInTheDark** [comment]
parts were a mistake. so were tesla coils.

Maxes out at 400%
![image](https://user-images.githubusercontent.com/58055496/89846500-46c11f80-db36-11ea-89ce-b6c50a339499.png)

**Comment by LemonInTheDark** [comment]
note to self, tesla guns need to be balanced similarly, and emitters need to have a **very** high power draw for using them.
