### ISSUE TITLE
[BASED ON A BAN APPEAL] Bluespace bodybags are fuck

### ISSUE THREAD

**Issue by Tharcoonvagh** [tgstation/tgstation#52854]
The appeal in question is [this one](https://tgstation13.org/phpBB/viewtopic.php?f=7&t=27267 ), keep in mind that its all hypothetical.
Currently I have no way of testing or reproducing it due to gpu issues with byond and stuff, someone else doing it for me would be much appreciated

Tl dr you can implant people in bs bodybags into other people via the cavity implant surgery and other than being wrong on SO MANY LEVELS it could break some stuff with teleporters for example
Sorry for the hazy writing Im about to die of sleep deprivaton rn

**Comment by Guestratem** [comment]
so, how you recreate it is to put a BlueSpace body bag containing someone. implant it into someone then teleport them.

**Comment by ATH1909** [comment]
Nah, that gimmick is amazing, and it doesn't really give a mechanical advantage (or, well, any more of a mechanical advantage than you'd get from just carrying a pAI on your person, and pAI cards are available in multiple public places at roundstart).

**Comment by antropod** [comment]
Do a matroska by implanting people with body bags containing other people that are impanted with body bags containing other people that are...

**Comment by Fikou** [comment]
emergent gameplay

**Comment by Time-Green** [comment]
The bug is that something breaks when teleporting with someone inside you? The matroshka spaceman isn't the issue

**Comment by Time-Green** [comment]
Right, this issue is in a weird place. I tried teleporting with someone inside and nothing happened. Please make a new issue when you know what the issue is

**Comment by Tharcoonvagh** [comment]
Cool
