### ISSUE TITLE
It is possible to construct an EXPERIMENTOR such that it cannot be easily dissassembled.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#52861]
## Reproduction:
1. Construct an EXPERIMENTOR from a machine frame to the immediate left of a fulltile window
2. Notice that the right bit of the experimentor is under the window rendering it impossible to interact with without removing the window.
3. Notice that this means that you cannot screwdriver-crowbar the EXPERIMENTOR to deconstruct it without removing the window.
4. Beat the EXPERIMENTOR to scrap with your toolbox because it takes less time than deconstructing or breaking a reinforced window.

**Comment by Winterous** [comment]
I thought that it only occupied a single tile, despite appearing to occupy two?

**Comment by TemporalOroboros** [comment]
While the hitbox does occupy the left tile of the sprite, apparently to interact with it (open the GUI, screwdriver it) you need to be able to interact with the _right_ tile of the sprite.... which can wind up in a window. I am unsure whether you need access to the right tile to destroy it via bludgeoning, but it is entirely possible that you do.

**Comment by XDTM** [comment]
this might be related to the nanite chamber bug that happened a while ago, where window code would prevent interaction with anything whose _icon_ was even partially under the window.

**Comment by timothymtorres** [comment]
So windows block a lot of interactions with structures and objects.  Notably pipes can be built on top of a window but they cannot be deconstructed unless the window is removed.  It’s a PIA but it’s intended to be this way.  Next time just pick a better spot.
