### ISSUE TITLE
Disassembling Booze-O-Mat yields no machine board

### ISSUE THREAD

**Issue by IanAbstract** [tgstation/tgstation#52877]
Issue reported from  Round ID: [144043](https://scrubby.melonmesa.com/round/144043) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1528

When dissasembling the booze-o-mat, no machine board drops when you use a crowbar on it so you cannot put it back together. Also, there is no booze-o-mat vending board in the service protolathe, which may be an oversight.

**Comment by TemporalOroboros** [comment]
This is an extension of #52860 and should be fixed by  #52871

**Comment by Time-Green** [comment]
Duplicate of #52860
