### ISSUE TITLE
Fire Drake gets gliched out on Unholy trap

### ISSUE THREAD

**Issue by WarlockD** [tgstation/tgstation#52878]
## Round ID:

[Round ID]: [144023](https://scrubby.melonmesa.com/round/144023) (Campbell)

## Reproduction:
1. Be on Ice Box
2. lure the fire drake into n unholy trap when the drake trys to do the lava trap
3. Be confused on why the drake's overlay is there

Not sure what else to say.  I am sure its a run time but I ran over the trap right when the drake was going to land on my position so not quite sure what attack he was going to do.  His overlay os there and I am shooting something but no other indicator.  Might try it localy but not sure other than this info.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/88d7dbfc105fbf40284d7b7c4587f8d23c0ac3ac/code/game/objects/structures/traps.dm#L233-L244

**Comment by Sealed101** [comment]
could not reproduce; no drake overlay stuck around when a cult trap was triggered
