### ISSUE TITLE
Dental implant pills can't be swallowed while in crit.

### ISSUE THREAD

**Issue by Winterous** [tgstation/tgstation#52870]
As the title says, implanted pills, which are a hands_free action, seemingly only restricting you to using it while conscious, cannot be activated while in crit.
But I'm not certain if this is intended, was inadvertently changed at some point, or whatever.

So; is this intended? It seems to me that the entire point of implanted pills is to help yourself out of crit, and I'm sure a lot of others would assume the same.

If it is intended, should we change it anyway? How often are you simply cuffed to a chair and really want some drugs? Of course as it stands it'd still be useful to take combat drugs while stunned, but that's about it.

**Comment by optimumtact** [comment]
they're meant to be useable while cuffed so you can commit suicide if you're captured, for RP, and or story purposes.
