### ISSUE TITLE
You can pull beakers into your hand from a ChemMaster through walls and windows.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#52882]
## Testmerges:
- #52771 
- #52681 

## Reproduction:
1. Find a ChemMaster with a beaker in it.
2. Use telekinesis to open the menu from the medbay lobby.
3. Eject the beaker.
4. Observe that the beaker is in your hand instead of the floor by the ChemMaster

**Comment by zxaber** [comment]
Similar happens when a borg ejects a beaker; it'll be at the borgs feet rather than on top of the machine, which seems inconsistant.

I have not tried ejecting a beaker as an AI. I wonder if it teleports it to the AI's core.

**Comment by zxaber** [comment]
Similar happens when a borg ejects a beaker; it'll be at the borgs feet rather than on top of the machine, which seems inconsistant.

I have not tried ejecting a beaker as an AI. I wonder if it teleports it to the AI's core.

**Comment by zxaber** [comment]
Similar happens when a borg ejects a beaker; it'll be at the borgs feet rather than on top of the machine, which seems inconsistant.

I have not tried ejecting a beaker as an AI. I wonder if it teleports it to the AI's core.

**Comment by JenqaDev** [comment]
> Tried it, AI can teleport beakers to itself.
i did this a few weeks ago, fun shit to steal chem's beakers
