### ISSUE TITLE
Languages are no longer showing their associated icon

### ISSUE THREAD

**Issue by Jared-Fogle** [tgstation/tgstation#52887]
I can't reproduce this on a local, but on Bagil when I speak moffic I don't see the wings icon. I don't see it when anyone else uses it either. This has been happening for the past few days in every round I've played.

I'm unsure if this is fixed with tgchat as it hasn't been test merged since I've had this issue.

**Comment by Jared-Fogle** [comment]
Reproduced on Sybil as well, which does not currently have the CDN test merge.

**Comment by Couls** [comment]
CDN has been full merged, which is probably why this is happening on all servers

**Comment by Jared-Fogle** [comment]
Emojis aren't showing either.

**Comment by stylemistake** [comment]
@Jared-Fogle tgchat is testmerged today on Bagil, check if issue persists.

**Comment by Jared-Fogle** [comment]
@stylemistake It doesn't seem to. Emojis worked.

**Comment by TheMidnightRose** [comment]
Could also be related to the bug report I opened a long while back, about Xenomorphs being unable to take most languages when admin added #50204

**Comment by Jared-Fogle** [comment]
*Probably* not. The languages work, it's just the icon doesn't show. I'm pretty sure it's related to the CDN changes in some way.

**Comment by RaveRadbury** [comment]
Icons are showing up for me. Is this fixed?

**Comment by Jared-Fogle** [comment]
Yes. tgchat fixed it.
