### ISSUE TITLE
High lag can make walking spam chat.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#52898]
## Testmerges:
- 52771
- 52886

## Reproduction:

1. Walk around during high lag.
2. Get spammed with "Your previous action was ignored because you've done too many in a second"

**Comment by nightred** [comment]
Do you have a lag point that causes this?

**Comment by TemporalOroboros** [comment]
I don't know exactly, but it was happening while I was walking around the inside of the asteroid shuttle on the linked round. I didn't note down the exact time dilation, but it was bad enough that there was several seconds between the shuttle gibbing people and the actual shuttle showing up.

**Comment by Cookhimself** [comment]
Something related to this, i play on fulp which has an action limit that you can do in 1 minute  before it locks you out until it ticks over to the next minute.
 After a huge tg merge about two weeks ago or so every movement you make counts as an action and combined with time dilation makes it easy to hit the action limit just from moving.
 I can say fulp has had the action limit for a long time but before the big merge you would never hit the action limit unless you had high apm doing genetics, something merged within the last 2 months made movement different.

**Comment by stylemistake** [comment]
Fixed in related PR.

**Comment by TemporalOroboros** [comment]
Thank you.
