### ISSUE TITLE
TG gui doesnt work on Windows 7

### ISSUE THREAD

**Issue by DrCrawler** [tgstation/tgstation#52908]
Issue reported from  Round ID: [144152](https://scrubby.melonmesa.com/round/144152) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1528

WHYYYYYYYYY WOULD YOU MAKE IT SO EVERY WINDOW IS TG GUI? Even all other GUIs doesnt work, they are eather absolutely fucked or wont open. PLEEEEEEASEEE MAKE TG GUI OPTIONAL.

Edit: its not the TG gui, its the chat. Also, this issue happened only to me. Seems like i will need to quit TG station. Say goodbye to: PAIN, Isaac Carmichael, Dr. Crawler, John Dough and a good man. Goodbye.

**Comment by kriskog** [comment]
Try updating your internet explorer

**Comment by stylemistake** [comment]
Would be nice if you attached screenshots or logs.

**Comment by Tharcoonvagh** [comment]
I mean, Microsoft stopped developing for windows 7 so its kinda full of security breaches
I would update to 10 or 8 if I were you

**Comment by notdonte** [comment]
> I mean, Microsoft stopped supporting windows 7 so its kinda full of security breaches
> I would update to 10 or 8 if I were you

No one asked.
On Win7 with updated IE, cannot repeat issue, tgui works just fine.

**Comment by DrCrawler** [comment]
Yeah umm... My Ckey: DrCrawler, my Discord: DrCrawler (#1733). Screenshots soon.

**Comment by DrCrawler** [comment]
![Shit](https://user-images.githubusercontent.com/62419802/90225155-0c5bc900-de3b-11ea-8b3e-7e87f833d960.png)
![Shit-er](https://user-images.githubusercontent.com/62419802/90225175-1251aa00-de3b-11ea-87a4-7108676160d3.png)
![Shit-er-er](https://user-images.githubusercontent.com/62419802/90225180-154c9a80-de3b-11ea-9d46-925fb5ac710a.png)
![Not shit](https://user-images.githubusercontent.com/62419802/90225191-1978b800-de3b-11ea-8912-2e1c78d64b63.png)


Here, screenshots with some markings and censorship (just to not spoil the IC experience i choose the least populated server, didnt join the round and something got cencored. Same with the screenshot on the CM-SS13.)
**Even the respawn and edit charactors tab doesnt work, not talking about the Player Polls and Crew manifest (Theese two wont open at all)**

**Comment by DrCrawler** [comment]
Also, my hardware doesnt support Win 8, Win 10. And im not on internet explorer or any other browser. Im using the BYOND engine directly in cause of in-browser not working.

**Comment by stylemistake** [comment]
BYOND uses Internet Explorer internally to draw windows, so Internet Explorer version installed in Windows is important. Make sure it is up to date (IE11).

If updating doesn't help, reset settings in "Internet Options", and clean all the caches. Defaults should work just fine.

![image](https://user-images.githubusercontent.com/1516236/90226781-2d60f180-de1c-11ea-81a0-431f84116d85.png)

**Comment by DrCrawler** [comment]
Seems like its cause of mine IE 8. My craptop cant update shit. Seems like i will need to wait till TG gui starts to work ssomehow diffrent..? I dunno, i cant update it anyways. :/ 
I will leave it open in case of _someone_ making TG gui to work with IE 8. Just in case...

**Comment by DrCrawler** [comment]
Oh wait, seems like i gotta close it if it works now... Yeah ill check it.

**Comment by DrCrawler** [comment]
Aight, now the issue is that new chat doesnt work. WOOOOOOOOOW. Seems like i didnt notice it from the start

**Comment by DrCrawler** [comment]
Edited. Please read the description of the issue. And goodbye.

**Comment by stylemistake** [comment]
@DrCrawler I have just fixed your issue, and you're quitting? smh.

**Comment by optimumtact** [comment]
Update your PC, this situation will only get worse I'm afraid.
