### ISSUE TITLE
Forcefield projector forcefields can be placed without delay

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#52933]
## Round ID:
Round ID: [144233](https://scrubby.melonmesa.com/round/144233) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1527

## Testmerges:
The following pull requests are currently test merged:
#52886: 'Fix cdn rsc' by MrStonedOne at commit e3e2fd8614

## Reproduction:

1. Get a forcefield projector through the engineering protolathe
2. Project force
3. Attack it with a high damage melee weapon (e.g. welding tool)
4. ~~Takes 250 damage to break~~ ~~https://github.com/tgstation/tgstation/blob/ecb1d499c25a41ddf59f22bbc3f3f581b7a85721/code/game/objects/items/devices/forcefieldprojector.dm#L15~~
no i'm told it's the device's charge that determines their health
5. It can't be walked through like holobarriers
6. They can be placed immediately (other dense hologram projectors have a delay, e.g. engineering holobarrier projector)
6. Can be placed up to six tiles ahead of you
7. You can get past the 3 portal limit by using more than one
8. They eventually disappear by themselves, but it takes a couple of minutes

**Comment by Angustmeta** [comment]
They also have long range and won't even break from EMPs. 

Could use a nerf or three.

**Comment by Winterous** [comment]
Pretty sure that the device's "charge" is what determines the field health. Damaging the field drains the charge, and it drains over charge. So once you break one, any new fields will have low energy unless you let it recharge.

That said, they're probably still in need of a nerf, as you could just alternate between 2-3 projectors.
