### ISSUE TITLE
Icebox not spawning mining enemies

### ISSUE THREAD

**Issue by DinkleNH** [tgstation/tgstation#52932]
Issue reported from  Round ID: [144234](https://scrubby.melonmesa.com/round/144234) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1528

Noticed this a couple of days ago, no mobs spawned on either floor, ruins spawned naturally but no mobs or enemy spawners could be found across both mining levels.

**Comment by Time-Green** [comment]
They were removed because they kept killing miners

**Comment by Whoneedspacee** [comment]
they simply dont fit the design direction of icebox or should i say stationbox where box is a planet in space

**Comment by DinkleNH** [comment]
we live in a stationbox
