### ISSUE TITLE
Swarmers are broken fix this please

### ISSUE THREAD

**Issue by 4310V343k** [tgstation/tgstation#52939]
## Round ID:
no

## Testmerges:
no

## Reproduction:
I can't imagine THIS working
![image](https://user-images.githubusercontent.com/56449763/90287914-7c8d3d80-de81-11ea-8a0a-44f65ad3c784.png)
![image](https://user-images.githubusercontent.com/56449763/90288029-ac3c4580-de81-11ea-9be2-5c9d7cc59afe.png)
also ctrlclick returns a target for prepare_target, but there are no checks for mob/living, what?

**Comment by IndieanaJones** [comment]
On it.
