### ISSUE TITLE
Achat in the new chat is being labeled "unsorted"

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#52943]
## Round ID:
[144271](https://scrubby.melonmesa.com/round/144271)

## Reproduction:
Try to filter for "Admin Chat" and watch how asay doesn't appear. Filter instead for "Unsorted" and there they are.

**Comment by nemvar** [comment]
Known issue. Most messages do not have the correct types.

**Comment by RaveRadbury** [comment]
Yeah it seems that there will be a few tweaks in the future for tgchat, but it's so amazing I can't believe it.
