### ISSUE TITLE
Juggernaut periodically went invisible.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#52953]
## Testmerges:
- #52426 

## Reproduction:
1. Enter a disposal chute, possibly while suffering a hallucination that changes what your body looks like.
2. Have a cult juggernaut simultaneously (or very nearly so) enter and destroy the disposal chute.
3. The juggernaut will now periodically drop in and out of visibility and complete invisibility.

I have no idea.

**Comment by timothymtorres** [comment]
So I took a peak at the hallucination code and it doesn’t appear that juggernauts can spawn from a hallucination.  Nor does it seem that there should be hallucination effects that make real mobs disappear.

**Comment by Sealed101** [comment]
could not reproduce any invisibility effects via chute destruction
