### ISSUE TITLE
Frost trap permanently immobilizes

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#52956]
## Testmerges:
#52886: 'Fix cdn rsc' by MrStonedOne at commit e3e2fd8614

## Reproduction:
Lay a frost trap. Walk into it. Get free, but be unable to move. Resolved upon removal of the immobilized trait.
![image](https://user-images.githubusercontent.com/33292112/90311262-5a370680-def9-11ea-9c61-e51471756904.png)

**Comment by Jared-Fogle** [comment]
intentional its chasm round removal for ice moon

**Comment by Jared-Fogle** [comment]
I WASNT SERIOUS

**Comment by kriskog** [comment]
The fix was merged

**Comment by Jared-Fogle** [comment]
phew
