### ISSUE TITLE
Active empty jetpack halts space momentum when pushing off of lattices.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#52973]
## Reproduction:
1. Wear a jetpack.
2. Turn on the jetpack.
3. Run out of gas.
4. Push yourself off of a lattice.
5. Come to a complete halt two tiles away from the lattice.

Notes:
- For some reason the jetpack does not interfere with the momentum from throwing objects in space, though that may be because I was no longer holding down any movement keys.
- I have not tested whether this requires the movement keys to be pressed or whether it happens when the jetpack is off, only when the jetpack is active, and then runs out of fuel.

**Comment by Time-Green** [comment]
Was jetpack stabilization enabled or disabled?

**Comment by TemporalOroboros** [comment]
I don't know. It was whatever it it by default when activated for the first time. The jetpack was one of the black ones from Megan's EVA.

**Comment by Guestratem** [comment]
I tried to recreate this, and I cant seem to recreate it. the black ones i assume you mean are the ones which use Co2 or am I mistaking them with other jetpacks. I also tried with stabilization enabled and it didn't change anything.

**Comment by LemonInTheDark** [comment]
The replication is empty the pack through other means, while it's on
