### ISSUE TITLE
Skull Echo Program can send un-sanitized text to anyone with nanites.

### ISSUE THREAD

**Issue by Fhaxaris** [tgstation/tgstation#52992]
## Reproduction:
1. Be weird and try to put HTML into the skull echo program.
2. Notice it doesn't really care and sends it to everybody with nanites
3. ~~Troll everyone on Bagil~~ report it like a responsible individual.
![image](https://user-images.githubusercontent.com/13771064/90347283-ebd76e80-dff4-11ea-8976-77a696105530.png)

**Comment by Jared-Fogle** [comment]
priority critical tbh

**Comment by ShibaInuLord** [comment]
based
