### ISSUE TITLE
Mysterious oxygen bursts inside of SM chamber.

### ISSUE THREAD

**Issue by Winterous** [tgstation/tgstation#53002]
[Round ID]: #144438

Testmerges: https://github.com/tgstation/tgstation/pull/52886

Reproduction:

So it was an 8 person round on Delta with only 1 traitor who didn't tamper with anything. They advised me to try a pure oxygen setup in the SM, so I followed their advice and hooked up some manifolds and stuff. Here's some diagrams showing where the manifolds were. The loop ones were just inside the walls where the pipe-cooling converter touches it normally. So I added 2 scrubbers to the chamber, extended the chamber pipes out a bit to make room for a manifold, and put that manifold inside the wall.

![Chamber](https://user-images.githubusercontent.com/38158801/90371930-01ab6900-e0b3-11ea-8f14-0ea89d6ea6f6.png)

![Loop](https://user-images.githubusercontent.com/38158801/90371935-02dc9600-e0b3-11ea-8465-86593c1263dd.png)

At some point during these events, I randomly acquired the "bluespace prophet" brain trauma, or whatever it's called. The one that makes portals appear that you can move though.

All the scrubbers were set to maximum scrub, all the vents were set to internal pressure 0 with external disabled.

I went to fetch a can of nitrogen to start the engine up, and when I got back I noticed the engine was a big fire, so I checked the monitor and it was like 90% oxygen in there. Some air HAD been brought in through the airlock as I went in to install scrubbers, but nothing else happened. No emitters or anything.

What followed was me trying to fix it, I wasn't watching the monitor program constantly, but when I did sometimes it seemed like there were HUGE influxes of oxygen from absolutely nowhere. I checked the piping and the atmos-engine pipe wasn't on at any point, all the manifolds I put in were BEFORE the gas filters, so even if they were letting in oxygen it should have been ejected out before going back in to the engine.

The only thing I can think is that maybe the bluespace prophet portals can transport gases, and that one of them ended up with one end inside the compressed oxygen container, and the other end inside the chamber.

This was completely bewildering, and the person who suggested I try, the traitor, says they have no idea why it was happening.

**Comment by Winterous** [comment]
After checking the bluespace prophet code, I'm confident that had nothing to do with it, they're just hallucinations you can interact with, no mention of atmos stuff at all.

**Comment by Ghilker** [comment]
This doesn't seem lika a bug, from what you said you started siphoning the chamber before adding the N2, this usually start the crystal production of O2 and Plasma and that's why there were peaks of O2 and fire in the chamber. The amounts were low (probably less than 50 moles each) but the monitor will only tell you about the % of each gas. Also if I'm not wrong you were filtering the O2 back in, correct?

**Comment by Winterous** [comment]
The oxygen was being vented into space after filtering. We had 2 cans of nitrogen in there at the end, and it was still like 60% oxygen I think.
I didn't know that siphoning started it up though, that explains things somewhat. I remember the pressure being quite high when I checked, but I wasn't paying attention to the temperature, so it may have just been because it was really hot in there.

**Comment by Ghilker** [comment]
Yeah the high fire temperature will always heighten the pressure. If you somehow manage to reproduce this and you have pics it would be great! But it most definitely won't be an issue since you started siphoning before putting in the n2
