### ISSUE TITLE
Swarmer Barriers do not stop anything.

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#53017]
Issue reported from  Round ID: [144465](https://scrubby.melonmesa.com/round/144465) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1528

Step 1: Be swarmer.
Step 2: Place barriers to slow organics from taking your Beacon.
Step 3: Watch them run through through it and kill your Beacon.

**Comment by ATH1909** [comment]
again?

**Comment by IndieanaJones** [comment]
I'll get on it.
