### ISSUE TITLE
Civilian bounty console can still operate even when it has no power

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#53022]
## Round ID:
[144468](https://scrubby.melonmesa.com/round/144468)

## Reproduction:
Situation: Civilian bounty console has no power, due to whatever. Clicking on it fails to open the UI, as expected.

...BUT... putting your ID into it, or alt-clicking to take your ID out will open the UI anyways, even if unpowered.
Opening the UI this way allows you to use the civilian bounty console as normal even when unpowered.  You can send bounties, get new ones, refresh bounties, etc.

**Comment by LemonInTheDark** [comment]
Apparently fixed by https://github.com/tgstation/tgstation/pull/53369
