### ISSUE TITLE
X4 doesn't work when planted on a card in a deck of cards

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#53029]
## Reproduction:
1. Buy X4 from your uplink (possibly also C4)
2. Set the X4 timer to 60000 seconds
3. Attach a signaler to one of the wires in the X4
4. Remove a playing card from a deck of playing cards.
5. Attach the X4 to the playing card.
6. Put the playing card back into the deck.
7. Activate the signaler.
8. Watch as the deck of playing cards utterly fails to explode.

This is probably a nullspace issue similar to #52247 and #52950

**Comment by LemonInTheDark** [comment]
![image](https://user-images.githubusercontent.com/58055496/91387567-6c168480-e7ea-11ea-929e-ce8c856b5567.png)
This is not a null-space issue, cardcode del's any cards added to a deck. Please kill it for me.

**Comment by timothymtorres** [comment]
So a couple of solutions:

- Anytime C4 gets attached to an object it increases the items weight
- C4 cannot be attached to tiny objects
- Disable inserting a card back into a deck if it has explosives attached

Personally I think disabling C4 for tiny objects makes the most sense and give it a proper weight restriction.

**Comment by LemonInTheDark** [comment]
Are tiny objects the issue here?

**Comment by timothymtorres** [comment]
> Are tiny objects the issue here?

It would fix it.  You then wouldn’t be able to place c4 on objects like cards, pens, cigarettes, etc.

**Comment by LemonInTheDark** [comment]
Yeah but c4 works fine on say pens or cigs, it just breaks down when dealing with the way card decks handle items, spawning and deleting them on insert/removal

**Comment by timothymtorres** [comment]
We could make a deck a storage container.  Each card would have to be initialized and inserted at roundstart though which might be quite laggy.  Alternatively we could set a spawn_cards boolean until a player picks up a deck or interacts with it to spawn the cards.  Thoughts?

**Comment by LemonInTheDark** [comment]
I don't think fully loading would add that much strain, given how comparatively few decks we have when compared to things like lockers and their contents. If that doesn't work lazyloading would be acceptable, though a bit jarring perhaps. 
What matters most is once a card exists, it stays that way until visibly destroyed.
