### ISSUE TITLE
Turning into lesser ashdrake during fulton instantly ghosts you with no body left behind.

### ISSUE THREAD

**Issue by Smoted** [tgstation/tgstation#53048]
## Round ID:
Manuel 144543

## Reproduction:
1. Have lesser ashdrake power
2. Fulton self in human form
3. While coming down from the fulton use the lesser ash drake button mid fall animation

**Comment by Fikou** [comment]
feature, you turn into a dragon and nanotrasen's megafauna eradication systems installed in the fulton kill you instantly

**Comment by Mooshimi** [comment]
> feature, you turn into a dragon and nanotrasen's megafauna eradication systems installed in the fulton kill you instantly

actual feature or shitpost?

**Comment by timothymtorres** [comment]
There are a lot of similar bugs involving shapeshifting and polymorph problems.  #52786, #55153, and #59127 might be related to this.

**Comment by Sealed101** [comment]
https://github.com/tgstation/tgstation/pull/77418 changed the way how spells interact with 'loc' of the caster; being in a temporary `effect`-type holder for the duration of the extraction is prevented, as it's not a valid `loc` to cast (at least the shapechange spell) from. it kinda feels like an accidental fix but it is what it is
