### ISSUE TITLE
Metastation's kitchen has no air alarm

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#53057]
## Round ID:

> Implying I play

## Testmerges:

^^

## Reproduction:

Look at this photo.
Go mad trying to figure out where it is
![image](https://user-images.githubusercontent.com/58055496/90597518-29c7c480-e1a6-11ea-8528-c14ba5965bae.png)

**Comment by brotherbeyondd** [comment]
Meta kitchen is proper shite now

**Comment by nightred** [comment]
Well would you look at that
