### ISSUE TITLE
Broken span class from fiery skin mutation

### ISSUE THREAD

**Issue by msgerbs** [tgstation/tgstation#53063]
## Reproduction: 
Get fiery skin mutation. Lose fiery skin mutation. Get broken span class tag in resulting message. MUH IMMERSION!

![2020-08-19 00_11_07-_tg_Station Sybil  ENGLISH   US-WEST   100% LAG FREE _ Rimward Monitor Zeta](https://user-images.githubusercontent.com/1313921/90655605-64157e00-e207-11ea-9983-83919f20523b.png)

**Comment by nightred** [comment]
Several locations have this issue.

**Comment by msgerbs** [comment]
Yep. I think I found them all and made a PR to fix it.
