### ISSUE TITLE
"Pill Press" printing pills infinitely after being disconnected from the chemistry plumbing network

### ISSUE THREAD

**Issue by TyrantCerberus** [tgstation/tgstation#53069]
Issue reported from  Round ID: [144620](https://scrubby.melonmesa.com/round/144620) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

In a round on Ice Box, I began my shift as chemist by setting up a basic (and ultimately flawed) chem factory for producing salicylic acid. It consisted in total of nine chemical synthesisers, two chemical tanks, one reaction chamber, and the aforementioned pill press, as well as uncoloured layer-1 piping connecting it all. The pill press was set to print the blue-green style pills, each containing 24u of salicylic acid, or 1u below the overdose threshold. 

I later discovered that, due to my flawed factory design, the pills did not in fact contain purely salicylic acid. In order to prevent the creation of any more pills, and in order to rectify my design, I disconnected four of the chemical synthesisers and then the pill press. However, to my surprise the pill press carried on printing pills despite no longer having an input. I left it alone for a while, presuming there to be an internal reservoir that still needed to deplete, but I'm now certain that isn't the case, as, after maybe fifteen or so minutes, it was still continuing to print (full) pills. I deconstructed the press at this point, but that also seemed not to work, as pills kept spawning where the machine last was. At which point I contacted the admin presently online (Dreathtil) who recommended making an issue report and cleared away the bulk of the pills. I believe no more have spawned in the time it has taken me to write this.

Apologies for the length of this, I have tried to include as much detail as possible to hopefully aid the expedient resolution of the issue. I have not attempted to reproduce the issue, as I was advised not to during the current round.

Thank you.

Reporting client version: 513.1528

**Comment by ATH1909** [comment]
> I believe no more have spawned in the time it has taken me to write this.

he made this issue report while the round was still ongoing ban he for out of game communication

/joke

**Comment by ATH1909** [comment]
Did those pills still have chems in them?

**Comment by TheBonded** [comment]
this is because the pill press stores pills, and only dispenses when there are less than 10 pills on it's own tile. it likely had a lot of pills stored in it at the time.
