### ISSUE TITLE
Glass shards still caltrop you while in zero-g

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#53081]
## Reproduction:
1. Kill the grav gen
2. Break a window
3. Remove shoes
4. Step on the glass shards
5. Crumple to the ground

**Comment by jjpark-kb** [comment]
https://gyazo.com/7e072b97f5a054996ebdbf2840ce9446

Im not able to reproduce this.

**Comment by SuperNovaa41** [comment]
Not an issue
