### ISSUE TITLE
Baisic cybernetic heart just shifted sprites with an organic heart

### ISSUE THREAD

**Issue by DrCrawler** [tgstation/tgstation#53086]
Issue reported from  Round ID: [144658](https://scrubby.melonmesa.com/round/144658) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1528

Step one: Get a suicided corpse.
Step two: Replace the patients heart with a cybernetic one.
Step three: Defib
Step four: Harvest the new kind of heart
![Heart bug 2](https://user-images.githubusercontent.com/62419802/90766325-8c8b9e00-e315-11ea-8f45-fa4d95e9a80b.png)

**Comment by dragomagol** [comment]
![image](https://user-images.githubusercontent.com/66640614/101839141-b2bc9000-3af6-11eb-8d76-a9a99e91ff7e.png)
Strangely it didn't show as an organic heart right away, only after I pulled it out from under the patient and then stopped pulling it.

**Comment by DrCrawler** [comment]
Hmm yes, strange stuff.

**Comment by DrCrawler** [comment]
I do not posess the software to continue testing the bug, if anyone finds this realy old issue, please try to fix it because i cannot dig in further, ill recess to just playing the game for now.

**Comment by ArcaneDefence** [comment]
I'd imagine it's related to the beating heart animation becoming a still heart.

**Comment by Sealed101** [comment]
can't reproduce, and i'd imagine a bunch of organ code refactors made it so
