### ISSUE TITLE
Augmenting plasmamen is weird

### ISSUE THREAD

**Issue by Vynncerus** [tgstation/tgstation#53084]
## Round ID:
[144643](https://scrubby.melonmesa.com/round/144643)

## Testmerges:
N/A

## Reproduction:
Augmented chest and head on a plasmaman are completely invisible, though arms and legs are fine
![Screenshot (119)](https://user-images.githubusercontent.com/33727132/90729222-3d515900-e294-11ea-8005-ba3bf13f893b.png)

Also, replacing plasmaman lungs with cybernetic ones that breath oxygen cause the "Toxin (not getting plasma)" warning to never go away.

Additionally, even after replacing all body parts and all organs with augmented or cybernetic ones, plasmamen still catch fire without their suit. Though this one may be intended, I don't know but I figured it was worth mentioning.

**Comment by ATH1909** [comment]
Do they suffocate with the cybernetic lungs?

**Comment by Vynncerus** [comment]
The cybernetic lungs function perfectly but the warning popup for not breathing any plasma just never goes away
