### ISSUE TITLE
tgui: Paper BSOD on IE8

### ISSUE THREAD

**Issue by RazorManager89** [tgstation/tgstation#53108]
`Exception thrown and not caught
   at http://127.0.0.1:49471/tmp179/tgui.bundle.js:1
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Trident/4.0; byond_5.0)

Object doesn't support this property or method
   at http://127.0.0.1:49471/tmp179/tgui-window-1.html:1
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Trident/4.0; byond_5.0)`

**Comment by SpaceManiac** [comment]
> The real question is why are you on IE8 in 2020?

Linux/Wine users are stuck on IE8
