### ISSUE TITLE
Contractor Uplink becomes unusable after transport pod gets stuck.

### ISSUE THREAD

**Issue by captainmexic0** [tgstation/tgstation#53118]
Issue reported from  Round ID: [144766](https://scrubby.melonmesa.com/round/144766) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1510

I used the contractor uplink to send a pod for my target, the pod got stuck in an airlock and I was unable to place my target inside. Unable to cancel the contract, I tried re-rolling, and that bugged the uplink. Future spawns of the uplink were bugged this way as well.

**Comment by JohnFulpWillard** [comment]
Fixed by contractor being removed
