### ISSUE TITLE
Nightmares cannot destroy gun-mounted lights.

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#53152]
## Round ID:

 [144853](https://scrubby.melonmesa.com/round/144853)

## Reproduction:

 Be nightmare, attack man with gunlight on his gun. Die because you cannot destroy that light.

**Comment by Shirbu** [comment]
noice

**Comment by ShizCalev** [comment]
@necromanceranne don't know which downstream you're referring to, but #53182 won't have that issue.

**Comment by ShizCalev** [comment]
https://github.com/Citadel-Station-13/Citadel-Station-13/blob/6eac8800b62958a9dc85909976490b888d0e883c/code/modules/mob/living/carbon/human/species_types/shadowpeople.dm#L215-L224

seems citadel did it, but they did it in a fucky way since qdeling the gunlight properly clears everything anyway.
