### ISSUE TITLE
Gamemode code is awful, hard to work with, hard to extend

### ISSUE THREAD

**Issue by MrPerson** [tgstation/tgstation#5315]
The gameticker code about picking a round needs a rewrite. The different kinds of antags should be separated out into datums and should require only a single proc call to make someone a traitor, rev head, wizard, etc. Antag selection should happen before jobs are picked.

The whole structure is just a pain in the ass and could be simplified greatly. Personally I think it should be something like this:

Gameticker notices that there's 45 players readied up. It chooses there to be 6 traitors, 4 changelings and a wizard, so it spawns 6 traitor datums, 4 changeling datums, and a wizard datum. Each datum picks a player, and then jobs are assigned. The wizard is given no job or a wizard job, maybe. The gameticker has all the antag datums assign their objectives after jobs are chosen. Then after the round begins the gameticker has each antag call a finalize() proc that equips the player with anything else they need (flash, talismen, etc), gives them special powers, adds extra UI elements, greets them, adds notes, gives the AI new laws, etc. As much as possible, this behavior should be in the base datum/antagonist rather than copy+pasted into every different type independently like now.

Another possibility is to have the antags be actual jobs that the job controller hands out in a special assignment phase at the gameticker's request.

**Comment by JJRcop** [comment]
Anything new about a rewrite of this? I heard from various sources that someone somewhere someday was sometimes working on something like this.

**Comment by Jalleo** [comment]
"That person is still working on it but that person is not me." - Owlman the slacker.

( incoming should still be working on it )
