### ISSUE TITLE
Cyborg advanced mops - applicable to non jani'borgs

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#53174]
## Reproduction:

1). Obtain a 'janitor cyborg advanced mop'. 
`/obj/item/borg/upgrade/amop`

2). Apply this upgrade board to any **NON** janitor cyborg module.

3). The upgrade board is rejected by the **NON** janitor cyborg module and dropped to the ground. 
`module_flags = BORG_MODULE_JANITOR`

4). _**The non janitor cyborg will obtain the advanced mop upgrade.**_

5). The board is now able to be used on other non janitor cyborgs to provide them with advanced mops.

**Comment by dragomagol** [comment]
I would prefer if this were left in if only for something to do while waiting around. I frequently get the mop upgrade as a mediborg for this reason.

**Comment by ATH1909** [comment]
Yoooo, this is really cool.
