### ISSUE TITLE
Ghost role spawners can keep the expanded view range from being a ghost

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#53184]
## Round ID:
reported on a downstream, reproduced on a local

## Reproduction:

- As a ghost, increase your viewrange as you normally would
- Then, take a ghost role spawner, such as free golems or comms agent. Your view range is reset to normal after spawning.
- Interact with an advanced camera console or a subtype of it (such as a xenobiology camera console)
- Leave the advanced camera console
- Result: You'll get the extended view range back from before you took the spawner (see picture below)

![image](https://user-images.githubusercontent.com/51863163/91100652-37a89a00-e62b-11ea-8b9d-d373a0dd9728.png)

Interesting thing to note while testing: Buckling to a skateboard and unbuckling restored normal vision range.

**Comment by LemonInTheDark** [comment]
AJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ

**Comment by LemonInTheDark** [comment]
I missed one, I hope, might be weird client things
