### ISSUE TITLE
Through the power of love, if you and someone else hold each others hands you will be able to negate gravity

### ISSUE THREAD

**Issue by Jared-Fogle** [tgstation/tgstation#53192]
## Reproduction:

1. Find a friend, and grab their hand (aim for arm, grab intent).
2. Have the friend grab your hand too. Aw.
3. Walk into space.
4. Watch as you are able to fly around as if you had a jetpack on.

**Comment by msgerbs** [comment]
Feature.

**Comment by Jared-Fogle** [comment]
Another quirk, when you hit the edge of space you will not transition.

![image](https://user-images.githubusercontent.com/35135081/91164164-7e29e300-e683-11ea-9dc8-0ccc828dccac.png)

**Comment by msgerbs** [comment]
I actually had the opposite issue of this as a borg. If I load somebody onto me, as soon as I don't have anything to push off of, I stop moving and get stranded. Probably should make a separate issue about that though.
