### ISSUE TITLE
Changling Reviving Stasis bug

### ISSUE THREAD

**Issue by Eldeen** [tgstation/tgstation#53191]
Issue reported from  Round ID: [144969](https://scrubby.melonmesa.com/round/144969) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1528

I was using reviving stasis to heal some wounds, I put myself in a locker to hide then used the ability. While in stasis I reset my genomes and it disabled my ability to actually revive. near as I can tell it "reset" the stasis ability preventing the revive option from triggering. I tried having the admin kill my guy then revive but that didnt break it either.

**Comment by Eldeen** [comment]
Found a "fix" while working with an admin, they can make a clone of your original body then slap you into it. You seem to keep most of your DNA and transformation disguises.

**Comment by ATH1909** [comment]
I've experienced this as a changeling as well.
