### ISSUE TITLE
Heroine Bud and Equipment Swap hotkey

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#53205]
Xenobio 'Heroine Bud' (Chilling Light Pink extract) a flower that pacifies whoever wears it on their head and can't be taken off by the wearer, but with new swap feature you can take it off with any other hat in hand.

**Comment by msgerbs** [comment]
Is there anything this function doesn't break?

**Comment by dragomagol** [comment]
Fixed by #55209
