### ISSUE TITLE
Item autoequip when transforming into a human doesn't update light.

### ISSUE THREAD

**Issue by phil235** [tgstation/tgstation#5320]
When humanizing a monkey (and maybe in other cases), it puts items that are on the tile on the human, but with light producing items, it doesn't update the light, e.g. you have a lit lantern on you but it produces no light.

**Comment by MrStonedOne** [comment]
Ok, so this is fucking odd, you are right.... but you shouldn't be... 

https://github.com/tgstation/-tg-station/blob/abb9f30031ddf07cc3927a300daa267dab3b2ebd/code/modules/mob/transform_procs.dm#L154

https://github.com/tgstation/-tg-station/blob/4dcc7cca8d63f69a9d803dea0fede35928526502/code/modules/mob/mob.dm#L305

https://github.com/tgstation/-tg-station/blob/4dcc7cca8d63f69a9d803dea0fede35928526502/code/modules/mob/mob.dm#L269

https://github.com/tgstation/-tg-station/blob/bde3995bc1bc9ee57eebd11fb802e35e7b9fe6a1/code/modules/mob/living/carbon/inventory.dm#L34


item.equipt gets called, so this SHOULDN'T be happening, but it is... is there another transform proc?

**Comment by phil235** [comment]
Still happening. Even stripping the mob from their flashlight do not update the flashlight's light and you end up with a lit flashlight on the floor, but not emitting any light.
