### ISSUE TITLE
Some initial bugs and feedback after testing cytology

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#53215]
Mostly minor things really. System seems functional and fun. 

### Bugs or other issues:

* You slap microscopes and plumbing structures (such as the growing vats) when adding stuff to them (or using plunger). This has always been a problem with plumbing input/output gates in particular. 
* Microscropes can be dragged around but can't be tabled (like microwaves can). 
* Swabs will swab boxes/containers instead of being put into them. 
* Since throwables can't be aimed, mending globules thrown by humans can only reliably heal chests.  
* Gelatinious Cube metabolic boost has a cooldown timer, which is nice. But the timer is under a layer and can barely be seen. 
* None of the new mobs regenerate health even after eating, if that's a problem. 

### Feature suggestions:
* Alt-click command to remove a petri dish from microscope. 
* Having ejected petri dish placed in your hand. 
* <s>A way to empty a petri dish. </s>
* Having petri dishes, biopsy tools and swabs fit in bio bags. 
* Moar swabables.

**Comment by ATH1909** [comment]
> Swabs will swab boxes/containers instead of being put into them.

I found that you could put them in a container by opening the container's inventory (with alt+click or the like) and putting them in that instead of clicking on the container itself.

**Comment by ATH1909** [comment]
> A way to empty a petri dish.

You're supposed to be able to wash petri dishes out by using them on a sink, although I haven't tried that yet.

**Comment by ATH1909** [comment]
> Moar swabables.

Adding the ability to swab humanoid species would be nice, as a way to create spare bodies for headswapping moths, lizards, and the like. Being able to vatgrow monkeys would also be neat, albeit probably inefficient.

Imagine if vatgrowing is the way that we bring back empty cloning...

**Comment by Angustmeta** [comment]
Too many points in one issue so no point in keeping open longer.
