### ISSUE TITLE
One roundstart cytology locker isn't enough

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#53212]
Unless you fucking RUSH that shit at roundstart, some chucklefuck will ALWAYS take everything important from it without telling anyone, and then you're kind of fucked.

Source: In my first round of trying to work with vatgrowing, someone took the ENTIRE GODDAMN LOCKER and moved it to the testing range (without telling anyone), resulting in me needing to spend the next 20 minutes trying to collect vatgrowing gear myself (which was difficult mostly because the RD (who didn't research biotech at any point during those 20 minutes) didn't like me being in R&D as a chaplain, despite receiving basic Science access from the captain). In my second round of vatgrowing, I unintentionally became that chucklefuck when I secured the science plumbing constructor at roundstart.

**Comment by Jared-Fogle** [comment]
Please use the forums for feature requests.
