### ISSUE TITLE
microscopes look like action figures, and they're separated from the cytology locker by a bolted door on Metastation

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#53211]
Please change their sprite(s) to look more distinctively like a microscope, even if it means sacrificing a bit of realism/consistency in perspective. Maybe turn them 90 degrees? Right now, microscopes blend in with the other clutter on the tables they spawn on.

Current sprite:
![image](https://user-images.githubusercontent.com/42606352/91194011-68d1aa80-e6bd-11ea-992a-f7203d01f75b.png)

The perspective I'm proposing that we use:
![image](https://user-images.githubusercontent.com/42606352/91194196-8dc61d80-e6bd-11ea-8a5e-d00f05579752.png)

**Comment by ATH1909** [comment]
Being able to construct microscopes instead of having to order them from cargo would also be nice.

**Comment by ATH1909** [comment]
It also doesn't help that on Metastation, the cytology locker is by the biosuits in the decontamination area, while the microscope is on a glass table on the upper edge of xenobio, meaning that they're often separated from each other by a locked door. Since literally every other piece of cytology equipment is in that locker, many people don't bother to check Xenobio proper/their surroundings for a microscope.

**Comment by nightred** [comment]
The microscope was designed with being on a table and it looks good on a table.

**Comment by Qustinnus** [comment]
use the forums for suggestions
