### ISSUE TITLE
Paraplegic trait bugged, the disabled can walk

### ISSUE THREAD

**Issue by Jolly-66** [tgstation/tgstation#53219]
## Round ID: 
[144976](https://scrubby.melonmesa.com/round/144976) and multiple others, possibly subsequent rounds after this.

## Reproduction:
Choose the paraplegic trait and unbuckle yourself from the wheelchair, should have full range of movement and not be impaired.

The trait itself wasn't bugged prior to the recent update yesterday, which resulted in the trait breaking.

**Comment by LemonInTheDark** [comment]
Most likely fallout of #52929

**Comment by Jared-Fogle** [comment]
Hallelujah!
