### ISSUE TITLE
The game rarely automatically reconnects anymore.

### ISSUE THREAD

**Issue by uomo91** [tgstation/tgstation#53213]
## Reproduction:

Be connected when a round ends, wait.
More times than not, it does not reconnect you automatically anymore. You have to do it manually.
Multiple people confirm the same is true for them.

Possibly related to TGChat?

**Comment by Angustmeta** [comment]
And even the manual reconnecting feels awful. Sometimes it doesn't work at all even after waiting a while. And when hard reconnecting by closing client it usually fails the first time.

**Comment by uomo91** [comment]
> And even the manual reconnecting feels awful. Sometimes it doesn't work at all even after waiting a while. And when hard reconnecting by closing client it usually fails the first time.

Yeah, I forgot to mention, same here. Even File->Reconnect basically never works for me right now.
It's quite annoying to have to close the game and open the server by hand, every time a round ends.

**Comment by ZeroMODE0** [comment]
I have the same issue, but it's usually intensified when me and someone else in the same house are both connected to the same server. (His reconnects, mine does not. I have to close and reopen tgstation)

**Comment by Valtosin** [comment]
Same thing. Still not fixed

**Comment by JamieD1** [comment]
Happens every round for us as well. Really needs looking into.

**Comment by AffectedArc07** [comment]
This happens if DD is hard restarted instead of being left open over rounds. The rounds until hard restart is probably set to 1 at this point to clear out DD each round, maybe, I aint the host. 

At para we hard restart after each round for that reason, so we did this https://github.com/ParadiseSS13/Paradise/pull/14246

Feel free to port

**Comment by JamieD1** [comment]
Now if someone could incorporate this into TGChat - Ahem

**Comment by LemonInTheDark** [comment]
Don't be rude

**Comment by Valtosin** [comment]
fix it and I'll be
