### ISSUE TITLE
Free golems have nothing to eat on Icebox

### ISSUE THREAD

**Issue by Mia-Polson** [tgstation/tgstation#53227]
Slight problem with initial spawn free golems, first i dont if golems need to eat normally but this represents a problem with the free golems, as especially on ice box its nigh impossible to get any food save for either going to the sstation which usually results in death or making a chem dispenser and eating sugar which is ridiculous and barely helps. The problem is lessened on other stations as goliaths and plants can be eaten but golems should still at least on ice box have easier access to food or not have the need to eat. I was told maybe something liek a prisoner food something or another be added to the ship  as a possibility. Sorry but this is the first time ive done this and im not exactly sure if this is how it goes.

**Comment by LemonInTheDark** [comment]
No need to be so worried, we aren't gonna bite your head off for reporting bugs, frankly I wish people did it more not less, despite the 1.6k we have already.

Looks like an oversight, either we give icebox more sources of ghetto food, or make golems not need to eat.

**Comment by msgerbs** [comment]
TIL golems need to eat. Where do they normally get food from on Lavaland?

**Comment by ArcaneDefence** [comment]
Lavaland golems regularly eat leafy mushrooms, cactus fruit, and goliath steaks.

**Comment by Fikou** [comment]
you can drink sugar from the chem dispenser cant you

**Comment by LemonInTheDark** [comment]
That's silly, if lavaland has ghetto food so should icebox. Least we can do for em is icefishing or something

**Comment by Fikou** [comment]
> That's silly, if lavaland has ghetto food so should icebox. Least we can do for em is icefishing or something

thats being worked on

**Comment by Whoneedspacee** [comment]
> > That's silly, if lavaland has ghetto food so should icebox. Least we can do for em is icefishing or something
> 
> mothblocks and aiia made fishing already, they just need the freeze to end

please for the love of god stop blocking ruins for icebox its the main complaint and this shit is so empty, it's not even off station content its literally content for the station thats why the top level exists
