### ISSUE TITLE
External Archive at "book inventory management console" is sorted differently on different pages

### ISSUE THREAD

**Issue by n00bllna** [tgstation/tgstation#53240]
Round ID:Any really...

Reproduction:You start as curator, try to find that lusty argonian maid book to read privately in your office. After few pages on external archives books are not sorted anymore by author name but by book name and it is confusing at best and annoying at worst.

**Comment by timothymtorres** [comment]
This smells like a feature request but if the old code allowed sorting by author name before then it should have the same behavior.

**Comment by JohnFulpWillard** [comment]
Should be closed by https://github.com/tgstation/tgstation/pull/65326
