### ISSUE TITLE
(Medical Cyborg) Organs kept in organ bag will be deleted when unmoduled

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#53248]
## Round ID:
Power went out right after I discovered this, so I don't know the round ID. (Further testing shows that it happens whenever I try to have it happen again)

## Reproduction:
As medical cyborg, use organ bag to pick up an organ. (Limbs, heads, brains, what have you) Then, get deconstructed; Have your module reset so you can pick another, get destroyed entirely, or be deconstructed- You will not drop the organ, it is just gone. Your beaker, however, does drop.

**Comment by zxaber** [comment]
I should probably just refractor the organ bag to be an apparatus like the beaker holder to be honest.

That said, you could probably figure out a way to hold the captain's brain hostage this way, which is really funny. But I don't know if anyone would play along.

**Comment by dragomagol** [comment]
Possibly related to #25625
