### ISSUE TITLE
It is possible to turn around in a shuttle seat.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#53247]
## Testmerges:
- #53112 

## Reproduction:
1. Buckle into a shuttle seat.
2. Spam the spin emote. (Using a keybind is useful)
3. While spamming the spin emote spam click and try to move in a direction other than the one the seat is facing in.
4. Stop spamming.
5. When you stop spinning you should be facing a direction other than the one the shuttle seat locks you into and you shouldn't be able to turn around. It may take a few tries.

**Comment by TheBonded** [comment]
you can use whichever keybind you have for blocking movement (defaults to ctrl or alt I believe? or maybe c? one of those three does it) to turn your character while buckled to anything, including shuttle seats. this is intentional.
