### ISSUE TITLE
Armless people can grab people.

### ISSUE THREAD

**Issue by uomo91** [tgstation/tgstation#53256]
## Reproduction:

Use VV modify bodypart, or surgically remove a mobs arms, then put your ckey in the mob.
Using ctrl + left click instead of grab intent + left click, you can grab, aggressively grab, and even strangle people still.

Related issue: https://github.com/tgstation/tgstation/issues/53257

**Comment by Fikou** [comment]
you choke them with your buttcheeks, not a bug

**Comment by dragomagol** [comment]
Appears to have been fixed (tested help intent ctrl left click, grab intent click, grab intent left click, and right click pull)
