### ISSUE TITLE
Cyborgs Can No Longer Deathgasp When Stunned

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#53259]
Issue reported from  Round ID: [145165](https://scrubby.melonmesa.com/round/145165) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1526

Get flashed/laserpointered/emp'd as a cyborg. Attempt to deathgasp. Fail.

I presume this is a bug and not a feature (I hope).

**Comment by ATH1909** [comment]
!!!

Oh, please let this return, playing possum is one of the few things us borgs can do while being flash 'n' bashed...

**Comment by carshalash** [comment]
Gotta love them stealth nerfs :)

**Comment by LemonInTheDark** [comment]
> nerf

Don't tempt me

**Comment by brotherbeyondd** [comment]
#52548 also was a stealth nerf to silicons. Currently, you can kill an AI by turning off their APC via another ai. VERY cringe.

**Comment by LemonInTheDark** [comment]
> stealth nerf

**Comment by LemonInTheDark** [comment]
```
Potato: @carshalash I'm too tired/anturk will kill me if I don't finish atmos code soon, I've tracked the bug down to say(), saycode checks to see if someone is unconscious, and if they are it doesn't try and emote, which is sane. I'm betting borgs didn't used to go unconscious when stunned, and now they do
Potato: go forth and fix it
```
