### ISSUE TITLE
runtime the cat's DF catsplosion reference is a bit too accurate

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#53260]
![image](https://user-images.githubusercontent.com/42606352/91513803-d4c53600-e8aa-11ea-847b-4137c9fb69bb.png)

**Comment by Cyprex** [comment]
Just mass delete them, SDQL can do it but I think there's a more performant option?

**Comment by TheVekter** [comment]
I haven't seen this happen yet so far. What round was this?

**Comment by TheBonded** [comment]
doesnt seem like this happens anymore
