### ISSUE TITLE
Borgs can eject AI card from AI Integrity Restorer - Doing so teleports the AI Card to the Borg's Position

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#53262]
Issue reported from  Round ID: [145171](https://scrubby.melonmesa.com/round/145171) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1526

See the title:

![2020-08-27 20_07_59-_tg_Station Basil  ENGLISH   US-WEST   100% FREE LAG _ Honey! It #39;s 4pm! Time](https://user-images.githubusercontent.com/36066032/91513253-236dd280-e8a1-11ea-8f5c-6fd1e0bf8979.png)

**Comment by AlinaStarkova** [comment]
was fixed in #60080
