### ISSUE TITLE
Using the swap equipment hotkey lets you carry things in suit storage you shouldn't be able to 

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#53268]
## Round ID:

reproduced on a local on the latest master, but did it in 143425

## Reproduction:
Using the swap equipment hotkey on a suit (harduits, eva suits, labcoats, aprons, etc) doesn't drop the item from suit storage, allowing you to carry things in suit storage you shouldn't be able to

here's a labcoat carrying a plant bag (which it can't normally)
![image](https://user-images.githubusercontent.com/51863163/91534813-ce997e80-e8d7-11ea-8ab6-4056f1cefb49.png)
here's an apron carrying a health analyzer (which it can't normally)
![image](https://user-images.githubusercontent.com/51863163/91534905-f4268800-e8d7-11ea-88fc-b5e6a89ff41b.png)

here I had a hardsuit on with a tank in the suit storage, quickswapped to a labcoat and the tank remained in the labcoat's suit storage slot + was usable  (it also glitched out my jumpsuit sprite and made it invisible)
![image](https://user-images.githubusercontent.com/51863163/91534679-8bd7a680-e8d7-11ea-882f-4611a069c73c.png)

![image](https://user-images.githubusercontent.com/51863163/91535554-f1786280-e8d8-11ea-9feb-89d175284e35.png)

to reproduce:

- Wear an armor/suit with something in its suit storage
- quick swap hotkey to another armor/suit
- the item stays in the suit storage/doesn't drop

**Comment by Jared-Fogle** [comment]
Can confirm. I end up accidentally using this frequently.

**Comment by msgerbs** [comment]
Swap equipment strikes again...
