### ISSUE TITLE
Showers fill you with reagents extremely fast

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#53271]
### Reproduction:
Stand in default shower a few seconds:
![200828 1230 04](https://user-images.githubusercontent.com/46400996/91551308-3bd5ff80-e92a-11ea-998a-047fc1d88559.png)
![200828 1229 55](https://user-images.githubusercontent.com/46400996/91551305-3aa4d280-e92a-11ea-91ab-d091a69b7879.png)

I love it, but I don't think normal reagents are supposed to enter bloodstream from showering.

**Comment by Jared-Fogle** [comment]
@ArcaneMusic

**Comment by TemporalOroboros** [comment]
I believe that this is a side effect of the showers using VAPOR instead of TOUCH.

**Comment by Qustinnus** [comment]
isnt the human body 70% water or something

**Comment by msgerbs** [comment]
I'm torn. On one hand, showers using VAPOR kind of makes sense and it does make them more useful to an extent. On the other hand, there are clearly major problems with putting that much reagent into somebody.

**Comment by nightred** [comment]
Solution add toxicity level to water, if water is more than 80% of max reagent vol do tox damage.

**Comment by Time-Green** [comment]
> Solution add toxicity level to water, if water is more than 80% of max reagent vol do tox damage.

Kill someone by putting them in a shower for 3 seconds

While a lot of fun, being able to multiply reagents by this much and this fast is horrible for balance. You could turn 10 reagents of RDX into 1000 in a few seconds (although it is stuck inside someone). 

Showers should just be TOUCH, people generally don't inhale liters of water while showering

**Comment by TemporalOroboros** [comment]
I suddenly want to make an amanitin shower.

**Comment by WarlockD** [comment]
Could just make TOUCH turn to vapor at a very small %.  Like how your skin gets all wrinkly because it absorbed to much.

**Comment by nightred** [comment]
vapor just gives to many reagents as is.

**Comment by Angustmeta** [comment]
In most scenarios vapor gives less reagents than used.

**Comment by Time-Green** [comment]
> Could just make TOUCH turn to vapor at a very small %. Like how your skin gets all wrinkly because it absorbed to much.

It’s actually a reaction to give your skin more grip, it’s not because the water gets absorbed

**Comment by Paxilmaniac** [comment]
You can use this with chems like sugar or mutagen to instantly dose them with 1000 units of them, which while funny, is definitely not intended.

**Comment by nightred** [comment]
That 1000u by vapor is going to be a bigger issue if the blood filter is merged.
