### ISSUE TITLE
Silicon : radio does not work.

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#53283]
## Round ID:
[145223](https://scrubby.melonmesa.com/round/145223)

## Reproduction:
Press T, ;hello crew, does not work. Turning your mic on for constant recording makes it work, however.
EDIT: We found out departmental radios do not work either. :s, :m, :c etc. We can read them, not speak to them.

**Comment by ZeroMODE0** [comment]
It was working just earlier today, but suddenly (this round ID) it didn't work anymore.

**Comment by brotherbeyondd** [comment]
I'm fairly certain you fecked with the chat filters so it doesnt show chat and that jazz. Or something like that, cos if you're the person I'm thinking about it didn't show examine or borg chat either, right?

**Comment by ZeroMODE0** [comment]
> 
> 
> I'm fairly certain you fecked with the chat filters so it doesnt show chat and that jazz. Or something like that, cos if you're the person I'm thinking about it didn't show examine or borg chat either, right?

It doesn't work for the AI or other borgs either. I see chat but ; does not chat, and we cannot use departmental radios. We have to use mic always-on to use commons.

**Comment by carshalash** [comment]
Its very fun and engaging to only be able to open doors

**Comment by ATH1909** [comment]
*scream
