### ISSUE TITLE
Puddles(such as the one the ash walkers use) are no longer infinite and don't regenerate water

### ISSUE THREAD

**Issue by Capsandi** [tgstation/tgstation#53290]
Issue reported from  Round ID: [145233](https://scrubby.melonmesa.com/round/145233) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1524

Puddles are no longer infinite and don't regenerate water. They currently hold a large beaker's worth of water and thats all you get. This is not enough water if you plan on growing multiple plants to maturity as a hermit/ashwalker.

Steps to reproduce:

1. Use 100u of water from a puddle

2. Realise it is now a limited source of water as of #52865

3. Watch as all your plants dry and die cause your an ashwalker and you have no other way to get water

**Comment by TemporalOroboros** [comment]
For a second I thought this was a pull request and was about to get _very loud_....

Nice catch, this should probably be fixed soon.

**Comment by Jack7D1** [comment]
ye
