### ISSUE TITLE
The alt-click menu no longer includes the turf.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#53298]
## Testmerges:
- #53263 

## Reproduction:
1. Alt click anything
2. Observe the alt-click menu in the upper right.
3. Realize that the turf isn't listed on it, making it anywhere between a pain(tables) to impossible (supermatter) to lay piping under objects and structures.

**Comment by jaw-sh** [comment]
This is a very urgent issue for me because alt+clicking the SM crystal is the only way to safely pipe heat exchanges under it.
