### ISSUE TITLE
Nightmares cannot dodge lasers, disablers, or any light emitting projectile.

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#53309]
How to replicate: Shoot in the general direction of a nightmare in the dark, and they will get hit 100% of the time.

Why this happens: lasers produce light not only on their own tile, but on tiles adjacent to them, which prevents nightmares from dodging as their tile is counted as lit up as the laser hits.

**Comment by Shirbu** [comment]
Why this should not be happening: 
Nightmares are supposed to dodge ranged weapons when in the dark. Almost all station ranged weaponry are laser-based. This makes any fight between a nightmare and a sec officer, or head of staff a four click affair for the attacking player, down hallways they cannot see down. 

In close-ranged combat, the only type available to the nightmare barring throwing items, dual-wielding makes nightmares a two-click affair, assuming the crewmember ran into the nightmare with no flashlight on their person. the nightmare cannot reliably run away, because the lasers each light up their position in a 3 tile diameter square, meaning that in close quarters, in complete darkness, the crewman with the eguns has complete advantage.

**Comment by Rohesie** [comment]
Balance concern. Projectiles have always had lights on them, but the old system was so slow that it didn't update in time, so this effect didn't show up. It would have if there was no time dilation, the rest of the game (atmosia, looking at you) didn't lag the hell out of it. Same as manifested ghosts with lights completely destroying nightmares without counterplay.

Feel free to fix this by making the laser light smaller or changing the nightmare's interaction with light now that the system is more responsive and it actually does what it meant to.

**Comment by Shirbu** [comment]
Understood.
