### ISSUE TITLE
Highly potent bio-luminescent plants don't have their lights centered on them, causing some oddities with pitch darkness/overlay lighting

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#53302]
## Reproduction:
![image](https://user-images.githubusercontent.com/51863163/91632926-f9540780-e9a9-11ea-8040-314c9a6667f6.png)
So here's a stack of 100 potency pink bio-luminescent poppies placed in the darkness of security. 
Immediately you'll notice a few things
1. the light isn't centered on the plants.
- High potent plants don't seem  to have their lights centered on the plant itself, instead up and to the right a bit.
2. the light cuts off into a wall of darkness
- Despite the light reaching into security, pitch darkness just begins abruptly, though it's clearly covered by the offcenter lights. if they were centered, this area would not be covered.
3. despite being dark down the hall, you can still see a bit into it
- Despite no light being cast by the off-center lights, you can still see into the darkness down the hall towards the bridge - this area would be reached and illuminated by the lights if they were centered.

![image](https://user-images.githubusercontent.com/51863163/91632985-6d8eab00-e9aa-11ea-8bed-be8eb9119362.png)
above is a worn flower, distinctly not centered
![image](https://user-images.githubusercontent.com/51863163/91632999-826b3e80-e9aa-11ea-9459-8bc4d57161ad.png)
above is a cherry bulb with centered lighting, it is less than 100 potency
![image](https://user-images.githubusercontent.com/51863163/91633057-e4c43f00-e9aa-11ea-99c2-dc3b5854337a.png)
above is a cherry bulb with offcenter lighting, it is 100 potency

**Comment by Timberpoes** [comment]
Was fixed by #53317 and can be closed.
