### ISSUE TITLE
Swarmers can destroy walls around the atmospherics tanks, causing massive plasma fires

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#53301]
This happened on Icebox so I'm not certain if it's just with how snowflake that map is or if they actually can do this on every map.

**Comment by TemporalOroboros** [comment]
Likely an icebox thing.

On other maps the atmos tanks are surrounded by space. Meaning that swarmers can't breach them and if they did the gases would just vent into space. Icebox has this problem because when the tanks are breached the gases are free to e x p a n d.

**Comment by Jack7D1** [comment]
I think this is relatively simple, just add atmos tanks to  the areas they cant destroy. Lets do this

**Comment by Jack7D1** [comment]
nope
