### ISSUE TITLE
UI and sprite issues with the Gygax

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#53327]
Issue reported from  Round ID: [145317](https://scrubby.melonmesa.com/round/145317) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1526

![2020-08-29 22_51_12-_tg_Station Basil  ENGLISH   US-WEST   100% FREE LAG _ Class Fortress Eight](https://user-images.githubusercontent.com/36066032/91651461-353ea980-ea4a-11ea-8b91-135f4b8fdf46.png)

As can be seen despite the presence of a pilot it shows as being open, and additionally has some funky stuff going on with the UI when opening the status panel.

**Comment by Lexbomb6464** [comment]
This seems to be happening for the medical mech too.

**Comment by Cluckster13** [comment]
This happens with ALL mechs. This is quite the issue as when using mechs I cannot see which way I am facing.
