### ISSUE TITLE
Opening server logs in game causes intense lag for the viewer upon any action with the data.

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#53326]
Round ID: [145314](https://scrubby.melonmesa.com/round/145314)

Round Time: 01:41:53

Time Dilation: 41% AVG:(40%, 40%, 40%)

How to reproduce: open say logs for the server in game after an hour or so of playtime on any server, and watch beyond start to scream incoherently. When it stabilizes, try ctrl f-ing something. Cry

**Comment by LemonInTheDark** [comment]
I don't know what to tell you man, downloading large files and trying to search through them in an already slow engine isn't fast.

**Comment by nightred** [comment]
Massive files viewed in IE or downloaded like this are just going to be bad for everyone.
Closing this as it is not actually a bug but just how large files react.
