### ISSUE TITLE
Cargo's Bounty tablet app won't print bounty papers

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#53322]
## Round ID: Multiple

Pressing the "Print Bounty" button on the Cargo bounty app doesn't do anything. Confirmed the tablet has a full stack of paper inside, still won't.

I asked @ArcaneMusic to fix this but he keeps ignoring me so.

**Comment by ArcaneMusic** [comment]
It's not that I'm ignoring you, it's that I'm busy and you should have made an issue about it in the first place.

**Comment by Jack7D1** [comment]
I've been delegated to the case!
