### ISSUE TITLE
Player preference to hide redundant whispers.

### ISSUE THREAD

**Issue by Gurkenglas** [tgstation/tgstation#53336]
When you speak to a radio channel, your log shows your whisper and the colored radio message. Especially as an AI, this clutters the log. There should be a preferences setting to hide whispers that are identical to what you hear on the radio, though it's fine if they still appear on runechat.

**Comment by Gurkenglas** [comment]
...though I suppose that, as an AI, you can simply put local in another fancychat tab.

**Comment by LemonInTheDark** [comment]
Feature request, not a bug

**Comment by Couls** [comment]
Issues aren't for feature requests. Please use the Forums, or alternatively PR the change you wish to see instead.
https://tgstation13.org/phpBB/viewforum.php?f=47
