### ISSUE TITLE
AI status tab not listing newly made cyborgs/shells

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#53330]
[Round ID]: [145314](https://scrubby.melonmesa.com/round/145314)

## Reproduction:
>Have Shell be made
>Realize it isn't showing up in cyborg tracking list in status tab
>Ahelp and request Shirbu creates a synched borg
>Continues not showing up in status tab, both creations show up in robotics console as synched and controllable however
>Make thread in github and include image of tab

![image](https://user-images.githubusercontent.com/16896032/91651945-f0f8eb00-ead5-11ea-88a7-4c527536ecbe.png)

**Comment by carshalash** [comment]
Round start cyborgs show up on the list it seems.

**Comment by Couls** [comment]
![image](https://user-images.githubusercontent.com/30060146/91654385-338adb00-ea76-11ea-89c7-56102eddfdb3.png)
can't reproduce on the latest master, I need more information you said admin spawned cyborgs didn't show up on the list?

**Comment by Couls** [comment]
![image](https://user-images.githubusercontent.com/30060146/91654564-dabc4200-ea77-11ea-8959-188385519689.png)
Bottom most borg was one I built in robotics and then connected with a second client and threw it into the shell I built, you can tell because of the higher cell capacity and the nominal status

**Comment by carshalash** [comment]
That's really odd.

**Comment by Couls** [comment]
mention me and let me know if this still happens, going to close for now since it hasn't been reproduced yet
