### ISSUE TITLE
Proper "AI" chat highlighting

### ISSUE THREAD

**Issue by Gurkenglas** [tgstation/tgstation#53337]
Highlighting "AI" also highlights any word including that character sequence. There should be a way to highlight only complete words equal to "AI".

**Comment by cacogen** [comment]
It would be good if it supported RegEx or something or simply using quotes to indicate you only want matches that fit that exact word

**Comment by Couls** [comment]
Issues aren't for feature requests. Please use the Forums, or alternatively PR the change you wish to see instead.
https://tgstation13.org/phpBB/viewforum.php?f=47
