### ISSUE TITLE
Pubby's escape pods maroon you.

### ISSUE THREAD

**Issue by sergeirocks100** [tgstation/tgstation#53341]
## Round ID: 
[145339](https://scrubby.melonmesa.com/round/145339), or any round on Pubby where people left on the escape pods, really.

## Reproduction:

Go on any one of Pubby's escape pods.

Evacuate the station on it.

Watch as it docks in the middle of space and maroons you.

**Comment by msgerbs** [comment]
I assume you mean the monastery shuttle? That's the only shuttle I can find on pubby that functions as an escape pod.
