### ISSUE TITLE
Rebalance buying spells multiple times

### ISSUE THREAD

**Issue by Gurkenglas** [tgstation/tgstation#53342]
It is generally not worth it to buy a spell twice for 20% cooldown reduction. It needs to be worth the money, either by reducing cooldowns or increasing potency. For example, Knock could have an increased range instead of a reduced cooldown, with a 5-point Knock playing the sound across the station and opening everything on it.

**Comment by ArcaneMusic** [comment]
Issues aren't for feature requests. Please use the Forums, or alternatively PR the change you wish to see instead.
https://tgstation13.org/phpBB/viewforum.php?f=47

**Comment by Gurkenglas** [comment]
Okay. Though when I click "New Issue", the two options shown are "Bug report" and "Feature request".

**Comment by Couls** [comment]
When you type in feature request the text arcane posted is what is auto filled into the body I don’t think we can remove the feature request button ourselves
