### ISSUE TITLE
Anti-Glow making you glow

### ISSUE THREAD

**Issue by onjec** [tgstation/tgstation#53345]
![Untitled](https://user-images.githubusercontent.com/59801464/91670167-47d4e380-eb1b-11ea-831d-0b7ec5ce2a53.png)
Issue reported from  Round ID: [145362](https://scrubby.melonmesa.com/round/145362) (/tg/Station - Terry [EU] [100% FREE LAG])

Reporting client version: 513.1528

**Comment by Sealed101** [comment]
could not reproduce; hopefully some of the lighting refactors over the years have managed to squash this completely
