### ISSUE TITLE
Some sinks don't regenerate water

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#53343]
## Round ID:
[145348](https://scrubby.melonmesa.com/round/145348) Terry.

## Reproduction:
* Use a large beaker set to 100u on a sink. This scoops up all 100u water. 

Result: The sink never regenerates the water, not even slowly. 

Expected result: Generation of about 2u water per second or so. 

Botany roundstart sinks on Metastation.

**Comment by brotherbeyondd** [comment]
Just use toilets 🤔

**Comment by MrMelbert** [comment]
I'm pretty sure I had the same with Icebox's botany sinks. I went back like 30 minutes later to get water and it was still 'dry'.

**Comment by nightred** [comment]
Also having issues reproducing this issue, items are currently refilling.

**Comment by Angustmeta** [comment]
I'll test again when I can.

**Comment by Angustmeta** [comment]
Can't reproduce anymore so guessing it's fixed.

**Comment by ArcaneMusic** [comment]
Hold up, re-open this one.
I'm not sure what the difference is, but I had a chance to play yesterday and it seems that mapped, static sinks from the beginning of the round totally don't refill, BUT NEWLY CONSTRUCTED ones work perfectly.
I'm not sure what the difference is but it's totally an issue on live.

**Comment by Angustmeta** [comment]
I had the leftmost metastation botany sink not refill, but the upper right did refill. Still not sure how to reproduce but I'll reopen the issue.

**Comment by MrMelbert** [comment]
no there is totally an issue somewhere with round start sinks, I had multiple prisoner rounds which all the sinks hit zero and never refilled. And i've definitely seen complaints by others that sinks aren't reclaiming at all.

**Comment by willox** [comment]
`/obj/structure/sink/proc/var/reclaiming` is never set back to false after `/obj/structure/sink/process` returns `PROCESS_KILL`.

This means that `/obj/structure/sink/proc/process_check` can never start the sick processing more than once.

Reproduction steps:
- use beaker to remove water from sink
- watch as sink refills back to full capaciity
- use bearker to remove water from sink
- watch as sink _doesn't_ refill

https://github.com/tgstation/tgstation/blob/9d1eb38f9d3103670a5aa6b2cf007c3c443819b8/code/game/objects/structures/watercloset.dm
