### ISSUE TITLE
Book heirloom stops being a heirloom after using wirecutters

### ISSUE THREAD

**Issue by Hamcha** [tgstation/tgstation#53359]
## Round ID: 
[145300](https://sb.atlantaned.space/rounds/145340)

## Reproduction:

- Spawn as chemist with Family Heirloom quirk, this will give you the Chemistry textbook heirloom.
- Use wirecutters on it
- Enjoy being sad for the rest of the round

My guess for this happening is that when books are hollowed they are merely replaced by a new book with matching title and icon and therefore don't carry heirloom status: https://github.com/tgstation/tgstation/blob/6de334414e7c15a92b7bb1a4dc000004d13e5ead/code/modules/library/lib_items.dm#L317-L324

**Comment by Mickyan** [comment]
I feel like this makes a lot of sense actually

**Comment by cacogen** [comment]
It would be better if the damage was done to the existing object instead of duplicating and deleting.

**Comment by Hamcha** [comment]
> I feel like this makes a lot of sense actually

It does and I found it funny but I wonder if it breaks anything, for example, making the "Steal heirloom" objective impossible for Obsessed people (but given you could probably destroy the heirloom in other ways maybe it's not so important)

**Comment by optimumtact** [comment]
it's not worth fixing as you would have to check every heirloom possible object for recreations and pass over the trait or flag or component or whatever it is

**Comment by Hamcha** [comment]
Is it always everything or nothing? I assume if some other case would be found out it'd get reported as well.

But I understand the current behavior is negligible.

**Comment by MrMelbert** [comment]
No longer an issue as storage subtype books no longer exist
