### ISSUE TITLE
Showers filled with chemicals that release atmos gasses produce way too many moles of gas.

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#53357]
Showers spill chems. Oxygen, nitrogen, nitrous oxide, and carbon dioxide (the chemicals, not the gasses), produce a shitton of gas when pumped into showers using plumbing, even with just one chem generator.

<b>How to reproduce:</b> Make a shower. Connect it with ducting to a chem generator from the plumbing rcd. Set the chem generator to oxygen. Turn on the shower. Die of overpressure.

<b>Shower Turbine:</b>
![shower air megawatt](https://user-images.githubusercontent.com/23252965/91733209-1d584a00-eb5e-11ea-9398-f4cfc0d1eb1a.PNG)

<b>Shower Oxygen Miner:</b>
![gas gas gas](https://user-images.githubusercontent.com/23252965/91733232-221cfe00-eb5e-11ea-92e3-d8a54e7e9b0c.PNG)

**Comment by Ghilker** [comment]
@LemonInTheDark  AHHHHHHHHHHHHHHHHH

**Comment by Ghilker** [comment]
plunbing was a mistake

**Comment by Shirbu** [comment]
In actuality, I think there is value in being able to produce certain gasses in reasonable quantities. These are not reasonable quantities.

**Comment by nightred** [comment]
The gasses should be a 1 for 1 conversion. that will debuff smoke nads and machine but this is so easy to abuse.

**Comment by cacogen** [comment]
Why is nothing ever tested nowadays

**Comment by Shirbu** [comment]
Not enough people have the powergaming shitter mindset that I do.

**Comment by ArcaneMusic** [comment]
Holy fuck what the hell

**Comment by ATH1909** [comment]
I briefly tested this out as a mime two days ago in the chapel.

Try putting 50 matter bins on the shower's tile and making four grilles around the shower so that the matter bins can't be pushed away. If my codediving is correct, this should make your gas miner approximately 51x more effective.

**Comment by cacogen** [comment]
What do matter bins do just sitting on the ground?

**Comment by TemporalOroboros** [comment]
The reagents create gas both on expose_obj and expose_turf so the gas reagents applied to the turf will create X times the applied volume of reagent in moles of gas _per object on the turf including the turf_. (where X is some constant that is dependent on the reagent)

**Comment by LemonInTheDark** [comment]
> 
> 
> plumbing was a mistake

Chemistry was a mistake

**Comment by Shirbu** [comment]
> Try putting 50 matter bins on the shower's tile and making four grilles around the shower so that the matter bins can't be pushed away.

Tested. Does in fact improve efficiency. Not sure if it does so by 51x but wouldn't be surprised.

**Comment by Shirbu** [comment]
![somuchshowergas](https://user-images.githubusercontent.com/23252965/91810410-afa23180-ebe2-11ea-89b3-85dfbc828fc0.PNG)
