### ISSUE TITLE
Chemicals do NOT react inside showers and sinks.

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#53358]
This means you can plumb potassium and water into a sink, and when someone tries to take water, they blow up.

<b>How to replicate:</b> Try to put two reactive chemicals in a sink. Watch them not react. Use your gamer flask to scoop them up. Watch them react in your hand.

**Comment by ATH1909** [comment]
oh no

**Comment by optimumtact** [comment]
feature lol

**Comment by ArcaneMusic** [comment]
Sinks were specifically written as no-react until reagents were dispensed. Mixing reagents that only react upon opening the tap was intended at the time, which is why it has the NOREACT label.
Showers however should totally be reacting internally. Can you reproduce?

**Comment by Shirbu** [comment]
I have tested this, and showers do let chemicals react prior to dispensing them. You are correct, and the issue can be closed.
