### ISSUE TITLE
Browser Status Panel issues: No inventory Object tab verbs or alt+click icons

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#53360]
## Round ID:
Round ID: 145409
BYOND Version: 513.1527
Master commit: 6c9d88a4cdf4df5539740557add7c385ab7f0682
Local commit: d0d81185f09ca30d3b0856d476544240dba0de53

## Testmerges:
The following pull requests are currently test merged:
#53329: 'testing smooth movement fixes' by actioninja at commit e52a1bd8dd

## Reproduction:

1. Object tab verbs from items in inventory (e.g. Adjust suit sensors) don't show up any more
2. Alt+click menu icons are broken

Issue created with change to browser status panels here: https://github.com/tgstation/tgstation/pull/53112

**Comment by Couls** [comment]
I'll leave this one open because alt click icons are still not going to consistently load quick. should be better since #53463 has been merged though

**Comment by Couls** [comment]
going to close in favor of #54132 as the object tab verbs problem has been fixed
