### ISSUE TITLE
one of the possible abductee objectives still mentions cloning

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#53364]
https://github.com/tgstation/tgstation/blob/master/strings/abductee_objectives.txt

"Don't allow anyone to be cloned."

**Comment by ATH1909** [comment]
Also, a clown can receive the abductee objective of "The clown is not funny. You can do better! Steal his audience and make the crew laugh!"

**Comment by Angustmeta** [comment]
Remove all abductee objectives tbh. They are just interfering with actual abductor brainwash memes.

**Comment by ATH1909** [comment]
> Remove all abductee objectives tbh. They are just interfering with actual abductor brainwash memes.

Nah, looking though this file, a lot of these objectives look really fun. I think the problem is just that there are some that are weighted much, much higher than the rest (such as "ignore objects in sets of [X]").

**Comment by ATH1909** [comment]
I wouldn't mind an toggleable option on the abductor teleporter or something to NOT give people abductor objectives, though. It is kind of annoying to have to put "Ignore your abductee objective." in each of my brainwashing surgery (gimmick) commands.
