### ISSUE TITLE
AI can't leave mechs after taking control of them with ai control beacon

### ISSUE THREAD

**Issue by ReplicantTerry** [tgstation/tgstation#53384]
Issue reported from  Round ID: [145480](https://scrubby.melonmesa.com/round/145480) (/tg/Station - Campbell [EU] [Roleplay] [TGS4/LINUX])

When you click eject after taking control of a mech with an ai control beacon (not as a malf ai), you get the message "You can't leave a mech after dominating it!."

There is also a typo in the message as it has an unneeded full stop.

The mech in question was a clarke.

Reporting client version: 513.1528

**Comment by optimumtact** [comment]
@TiviPlus maybe due to the mecha rework?

**Comment by carshalash** [comment]
Can confirm, While I was stuck in the mech I was also unable to use any of the equipment that was given to me. It was pretty painful.
