### ISSUE TITLE
Strange popup with new status panel + moving keys

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#53380]
## Reproduction:
1. Join game
2. Hold UP or DOWN arrow key in the same time press any button in status panel for example Status
3. Get strange popups say keyUP "text" keyDown "text"

![image](https://user-images.githubusercontent.com/5034345/91836369-bd47cd80-ec5b-11ea-9f53-38395ed3d6ba.png)

**Comment by Couls** [comment]
Fixed in #53369
