### ISSUE TITLE
Stat panel spuriously didnt work

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/tgstation#53381]
## Round ID:

Master, it worked when i compiled it before then stopped working

## Testmerges:
master

## Reproduction:

![image](https://user-images.githubusercontent.com/57223640/91841586-ea43b280-ec52-11ea-8f63-77d91ba2afbe.png)
![image](https://user-images.githubusercontent.com/57223640/91841846-50303a00-ec53-11ea-8f06-d6312c56a5c8.png)
![image](https://user-images.githubusercontent.com/57223640/91841869-59210b80-ec53-11ea-8aec-5a5fbf709f8a.png)
etc.
![image](https://user-images.githubusercontent.com/57223640/91841630-fc255580-ec52-11ea-9504-09080c4be515.png)

Compiled
tested some stuff
changed a var to !var in unrelated code
recompiled and didnt work
recompiling after also didnt fix it
recompiled again and it worked

@Couls

**Comment by Couls** [comment]
This is a stinky one

**Comment by Couls** [comment]
let me know if this one crops up again
