### ISSUE TITLE
Delta Medbay has no fire alarms in the main hallway

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#53395]
Why
![image](https://user-images.githubusercontent.com/58055496/91960562-e0579900-ecbe-11ea-9a81-2f987e0493ca.png)
Bonus, the CMO's office, despite having a fire alarm, has no firelocks
![image](https://user-images.githubusercontent.com/58055496/91960681-1006a100-ecbf-11ea-86ac-1521f6406235.png)

**Comment by nightred** [comment]
Meta also lacked fire locks on the CMO door.
