### ISSUE TITLE
Ice Watcher's Status Effect is Broken

### ISSUE THREAD

**Issue by IndieanaJones** [tgstation/tgstation#53398]
## Round ID:

Not applicable

## Testmerges:

None

## Reproduction:

1. Get an ice watcher to shoot you
2. You should be sealed into an ice cube for a short bit and be unable to move
3. You don't

**Comment by nightred** [comment]
![image](https://user-images.githubusercontent.com/6491940/92144717-bdbba200-eddc-11ea-97f8-63e0d21de0d8.png)
I am unable to reproduce the issue.

**Comment by IndieanaJones** [comment]
Hmm, interesting.  Seems this somehow got fixed between the live branch and the one I'm currently using.  Closing for now.
