### ISSUE TITLE
Mech pads do not work

### ISSUE THREAD

**Issue by Cluckster13** [tgstation/tgstation#53409]
Issue reported from  Round ID: [145568](https://scrubby.melonmesa.com/round/145568) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Tried with Clarke, Ripley, and Gygax, all do not seem to work. The sprite changes for the mech but does not actually send the mech through nor does it even lift into the air.

Reporting client version: 513.1528

**Comment by Dorsisdwarf** [comment]
In awe at the audacity of these lads
