### ISSUE TITLE
Quick chat emotes broken

### ISSUE THREAD

**Issue by JusticeGoat** [tgstation/tgstation#53406]
As of round 145560 you can no longer say *wave *nod ect to emote in chat.

**Comment by ATH1909** [comment]
Were you a mime?

Of course, being a mime shouldn't affect your ability to use *nod and such, but still, it's best to know as much as possible about what's causing this bug.

**Comment by JusticeGoat** [comment]
i was a sec officer, and emotes linked to hotkeys work but i cant use the typed ones now

**Comment by SpaceManiac** [comment]
Should be fixed as of https://github.com/tgstation/tgstation/pull/53389
