### ISSUE TITLE
Possible oversight- Borgs scream while being cooked in a suit storage unit.

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#53419]
## Reproduction:
As a borg, turn off suit storage unit safeties and stuff yourself into it. Then, decontaminate and listen to yourself scream in pain (panic?) as you're reduced to a very minimal amount of health by burns. Question your decisions leading up to that point.
Edit: Screams are not audible, they are *scream emote screams.

**Comment by nightred** [comment]
How is that a bug? or are you saying that borgs should not scream when being cooked alive?

**Comment by ZeroMODE0** [comment]
> 
> 
> How is that a bug? or are you saying that borgs should not scream when being cooked alive?

I mean that borgs usually don't scream while on fire or being hurt. They don't feel, they get damaged

**Comment by itseasytosee** [comment]
Yeah, that's probably not intended.
