### ISSUE TITLE
Ripleys explode when upgraded to MkII

### ISSUE THREAD

**Issue by Vynncerus** [tgstation/tgstation#53415]
## Round ID:
[145552](https://scrubby.melonmesa.com/round/145552)
145540
This happened to me on both of these rounds, but I also tested on a private server by myself to reproduce it

## Testmerges:
N/A

## Reproduction:
Build a Ripley MkI
Enter the Ripley
Enable maintenance protocols.
Exit the Ripley
Add a Ripley MkI to MkII upgrade module
Ripley explodes
why

**Comment by Vynncerus** [comment]
Also to add, the ripley does get upgraded. It just also explodes for no reason

**Comment by Tharcoonvagh** [comment]
Have you tried turning it off and on again

**Comment by Vynncerus** [comment]
Here's video evidence of the explosion
https://www.youtube.com/watch?v=rQzd0a08zCI

**Comment by Vynncerus** [comment]
This is closed by #53470 isn't it? I don't know how github works
