### ISSUE TITLE
tgui: Script Error (Mafia BSOD)

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#53445]
## Testmerges:
#53439: 'Fixes pills -- Revert "Makes the stomach important part of eating (#53228)"' by Jared-Fogle at commit 633e19a464 
#53329: 'testing smooth movement fixes' by actioninja at commit e52a1bd8dd 
#52493: 'LINDA Atmos: Reforged and associated fixes/changes' by LemonInTheDark at commit ba15206930 
#53441: 'Fix bicon(icon2html) showing full dmis, fix asset cache hashes being incorrect.' by MrStonedOne at commit 97c319b8bf 

## Reproduction:
1. play mafia
2. get mafia ui
3. after some time it fails
4. But can be restored by closing and calling it back but then again fails like after 3-10 seconds
![image](https://user-images.githubusercontent.com/5034345/92278632-b09ad200-ef06-11ea-8883-51382eb656a5.png)

**Comment by stylemistake** [comment]
Closing to consolidate this issue in #53997.
