### ISSUE TITLE
Delta arrivals appears to have no fire alarms

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#53462]
I'm hoping they were hanging on the walls I deconned here, but I don't think they were.

![image](https://user-images.githubusercontent.com/58055496/92301321-c82e8680-ef17-11ea-8b64-ca11ac719cf9.png)

**Comment by NanoCats** [comment]
Here's a better picture, you seem to be right. 
![image](https://user-images.githubusercontent.com/14065903/92313830-3027b000-ef9e-11ea-8aca-0a6f5a6ea976.png)


also here's a better, easier place to look at the maps to grab this kind of information
https://affectedarc07.github.io/SS13WebMap/TG/DeltaStation/

**Comment by LemonInTheDark** [comment]
I am beginning to doubt the state of deltastation 
![image](https://user-images.githubusercontent.com/58055496/92314904-36645f00-ef93-11ea-934a-fe7f8c63f6db.png)
![image](https://user-images.githubusercontent.com/58055496/92314912-47ad6b80-ef93-11ea-8db7-09abea46e83d.png)
