### ISSUE TITLE
Oversight: Improper reagent behavior.

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#53476]
## Round ID:

NaN (Tested in private)

## Testmerges:

This issue has been around long enough that I'm extremely confident it has nothing to do with any test merges

## Reproduction:

If you acquire an ATMOS Firefighter tank, Janitor sprayer tank, or Botany tank, (May work on other containers that can "Spray") and load it with certain reagents that should in theory do something interesting: IE filling a tank with blood or liquid gibs should make it spray blood all over the place, could theoretically be useful to like, a cultist or something (or anyone just wanting to make a big mess, honk!)? Just as an example. 

However that does NOT happen, what happens is that it simply treats the reagent as it would water. Worst case scenario it shouldn't work as blood and liquid gibs are _not_ water, but what I'd rather happen is yay blood everywhere.

On a similar note, injecting bluespace dust doesn't do anything, I feel it really should! I tested this by having an Odysseus fire a full bluespace syringe at another player; Nothing happened! (Similar effect to consuming it orally, maybe even stronger since it's going straight to your bloodstream?)

**Comment by Angustmeta** [comment]
Haven't tested bluespace dust recently but its effect is delayed 10 cycles and after that it's 15% RNG to do the shakey + teleport thing.

**Comment by nightred** [comment]
This issue will be resolved with PR #53491
