### ISSUE TITLE
Different types of meat can't be used in most recipes

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#53484]
## Round ID:
[145759](https://scrubby.melonmesa.com/round/145759)

## Testmerges:
#53441 
#53439 

## Reproduction:
Make synthmeat with cryo and blood.
Cook it into a steak.
Try to make a burger of any kind, then cry because the recipe isn't highlighted.

**Comment by Krysonism** [comment]
I think i know what is causing this. I will fix it once i get home from work.

**Comment by ArcaneDefence** [comment]
Was addressed in https://github.com/tgstation/tgstation/pull/53892
