### ISSUE TITLE
box of glowshrooms emit glow from toolbar

### ISSUE THREAD

**Issue by jtroopa** [tgstation/tgstation#53481]
Issue reported from  Round ID: [145754](https://scrubby.melonmesa.com/round/145754) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

I might be phrasing this wrong, I think pictures will better explain it. I took three different screenshots, all with a box containing glowshrooms in it. On the floor, the box emits the glow like it should...

![glowbox floor](https://user-images.githubusercontent.com/59320615/92315245-5baf9800-efa8-11ea-8e05-c34185a08db6.png)

But as I hold it in my hand, the glow seems to be coming from the box as it sits in the hand toolbar.
![glowbox hand](https://user-images.githubusercontent.com/59320615/92315251-5f431f00-efa8-11ea-813e-f48dd5d8aa77.png)

I'll stow the box in my bag and no glow is to be seen...
![glowbox bag closed](https://user-images.githubusercontent.com/59320615/92315273-c365e300-efa8-11ea-8e3b-29dfd2aab305.png)

But then I'll open the bag and the glow is coming from the box as it appears on the toolbar again.
![glowbox bag](https://user-images.githubusercontent.com/59320615/92315282-e1334800-efa8-11ea-9549-82926e423a22.png)

It doesn't appear to be visible to anyone else. It's still present after restarting the client as well.

**Comment by Dorsisdwarf** [comment]
Incredible

**Comment by Sealed101** [comment]
can no longer reproduce; god this bug just keeps popping up and then disappears with no trace huh
