### ISSUE TITLE
Synthflesh not healing

### ISSUE THREAD

**Issue by AdroitTheorist** [tgstation/tgstation#53496]
Issue reported from  Round ID: [145787](https://scrubby.melonmesa.com/round/145787) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1530

Tried applying synthflesh in patch form on self, a corpse, and living crewmate and it did not heal any brute or burn damage.
Tried applying synthflesh via splashing to self, other crewmember, and corpse and did not heal any brute or burn damage.
Tried splashing self with no clothing still did not heal any damage.

**Comment by nightred** [comment]
This will be resolved with PR #53491
