### ISSUE TITLE
Viruses not transmitting through blood

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#53493]
## Reproduction:

1). Make or obtain any type of virus.
2). Attempt to spread the virus through blood by any means: drinking the blood; injecting it, consuming it through pills, etc.
3). Virus will fail to transmit.

Viruses otherwise spread normally through their respective transmission means: airborne, contact, fluids.

**Comment by ATH1909** [comment]
Does this happen with every virus?

Also, how is that virus transmitting normally through other means if you can't infect someone with it with the initial blood sample? Is it sentient?

**Comment by emptyexpression** [comment]
Viruses seem broken atm. Tried making one on bagil just now
Self-Respiration
Sneeze(neutered)
Cough(neutered)
Fever(Neutered)
Shivering(Neutered)
Alopecia(neutered)

Resistance 9
Stage Speed 6
Transmission 8 (on contact)
Stealth -2

Drinking it, splashing it, eye-dropping it into my eyes, injecting with a syringe, none of these things managed to infect.

**Comment by Misdoubtful** [comment]
Tested with multiple viruses, including sentient.

There are a multitude of ways get a virus without using blood transmission. Miasma and admin given diseases being examples. Both of these examples were used for verifying this issue and both functioned as they should. All viruses transmitted correctly through airborne, contact, and fluid transmission as stated. Barring blood transmission.

The means to reproduction of the issue is listed, transmitting a virus via blood. The means to getting a disease isn't the issue here though.

**Comment by ATH1909** [comment]
https://github.com/tgstation/tgstation/pull/53491 might fix this.

**Comment by emptyexpression** [comment]
I can confirm that this bug is fixed after merging #53491.

**Comment by Misdoubtful** [comment]
Very cool!
