### ISSUE TITLE
Rolling AI from ghost offer doesn't give AI tab. 

### ISSUE THREAD

**Issue by Tumesuo** [tgstation/tgstation#53506]
## Reproduction:

Have an admin offer an AI to ghosts, roll that AI. 

![dreamseeker_A32XKiAJOM](https://user-images.githubusercontent.com/15519576/92335774-d9f06500-f0a2-11ea-9e28-9a1c1d8a79d5.png)

**Comment by Dorsisdwarf** [comment]
another example of this flawless change
