### ISSUE TITLE
Nars-Ian can consume other pets while dead

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#53517]
![image](https://user-images.githubusercontent.com/42606352/92355332-a107be80-f0a9-11ea-8959-1ee679df4a9c.png)
![image](https://user-images.githubusercontent.com/42606352/92355368-b11f9e00-f0a9-11ea-84d2-a4f9f30574dd.png)

**Comment by Tharcoonvagh** [comment]
Fucking cursed

**Comment by Orchian** [comment]
What if I made this into a feature, rather than a bug?

**Comment by Neonyxia** [comment]
That could actually work. Just add a few lines of dialogue acknowledging it and it would do nicely.

**Comment by timothymtorres** [comment]
Duplicate of #57372

**Comment by Sealed101** [comment]
this is not handled by AI, it's a `Life()` proc for him
i am turning this into a feature because butter dog pr clearly doesn't have enough
