### ISSUE TITLE
you can initiate an amputation surgery on your own robotic limb if you're laying down, but can't actually do any of the steps

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#53514]
interestingly, the option to do the amputation surgery (which is displayed alongside the option to do the robotic version of the organ manipulation surgery) isn't presented to you while you're standing up; you have to be resting to get it.

**Comment by SuperNovaa41** [comment]
This is in fact, not an issue. You're able to do robotic limb manipulation while standing, but not normal surgeries. If you test this on regular limbs, you only get the surgery choices while lying down.
