### ISSUE TITLE
Toolbelt sprites not updating

### ISSUE THREAD

**Issue by InvalidArgument3** [tgstation/tgstation#53513]
Issue reported from  Round ID: [145823](https://scrubby.melonmesa.com/round/145823) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1528

Toolbelt sprites don't seem to be updating when tools are placed in them. 
![dreamseeker_2020-09-06_22-32-34](https://user-images.githubusercontent.com/51190031/92345958-ee2b6680-f090-11ea-8886-362bbeb422b7.png)

**Comment by msgerbs** [comment]
Unable to reproduce this. Anyone else?

**Comment by Twaticus** [comment]
yeah i get this sometimes. dragging the toolbelt into your hand then re-equipping it usually fixes the sprite. no idea why it happens since it seems very random

**Comment by dragomagol** [comment]
The toolbelt sprite also doesn't update when click dragging it into another container (like a toolbox) until you either add or take out another tool

**Comment by Sealed101** [comment]
i am going to take a wild guess and say that the toolbelt was the EVA base storage belt item, which does not show the tools on its sprite. delta station no longer has this belt and even if it does show up in mapping again, i don't think it's intended for it to show items anyway
