### ISSUE TITLE
Metal foam makes more than one wall on each tile

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#53511]
Detonate metal foam, there are now 20+ walls of metal foam on each tile it covers.

Issue reported from  Round ID: [145817](https://scrubby.melonmesa.com/round/145817) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1526

**Comment by nightred** [comment]
What situation did this happen in?
I am unable to get the foam, smart, or resin to produce this effect.

**Comment by NoxVS** [comment]
Situation happened off screen, I only noticed when I was trying to break through metal foam that had been created by a plasma fire and realized it was taking a long ass time. Right clicked the foam and there were a ton of metal foam tiles. I assume it was an issue caused by the whole exposure thing, which has been fixed, so if you can't reproduce it I will just close it
