### ISSUE TITLE
Infinite gelatinous cube digestion/healing glitch

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#53512]
## Round ID: [145816](https://scrubby.melonmesa.com/round/145816)

1) Become a gelatinous cube
2) Vore the cargo sloth while it's buckled to a rolly chair
3) The sloth never dies and is never spit out, resulting in a loss of the ability to eat anything else and more importantly infinite nutritious/health regen, which is kind of boring

To be honest I don't know if this is a glitch with the sloth or a glitch with eating buckled mobs, but I assume it's the latter (fwiw I pulled the rolly chair sloth around a bit before eating it, and tried moving the chair and buckling myself to it to try and dislodge the sloth, but it never came out)

**Comment by Krysonism** [comment]
@Qustinnus REEE

**Comment by TheBonded** [comment]
tested and reproduced with a goldgrub.
