### ISSUE TITLE
blood beam kinda just... doesn't work?

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#53520]
it just fired off like one or two beams into the bottom left corner of my screen

note that I had started and canceled (by moving) the start up animation multiple times to test to see if it was possible to sound spam with it, but even if that's what caused this bug, that's still a pretty significant bug

also, blood rites could REALLY do with having a radial menu for choosing what to make with it

**Comment by Tumesuo** [comment]
This is an old old bug that was fixed at some point (I think) but then broke again with some different byond version.

**Comment by Tumesuo** [comment]
https://github.com/tgstation/tgstation/issues/44413

**Comment by Angustmeta** [comment]
It hasn't worked since I made that issue, I'm sure.

**Comment by TheBonded** [comment]
Fixed by #56012.
