### ISSUE TITLE
Shuttle replacement event triggers with BuildYourOwnShuttle

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#53524]
## Reproduction: 
Buy Build your own shuttle kit, trigger replacement shuttle event. It will replace the shuttle with new one even before shuttle call and remove every player on board from the game.

**Comment by Fikou** [comment]
@Armhulen

**Comment by Fikou** [comment]
@tralezab

**Comment by ArcaneMusic** [comment]
Damn, my dude.

**Comment by TheVekter** [comment]
FUCK tag?

**Comment by msgerbs** [comment]
Huh... This is supposed to already be accounted for in the code.

https://github.com/tgstation/tgstation/blob/fae1111335885aad16ea20a9a35c02bc0204ab04/code/modules/events/shuttle_catastrophe.dm#L7

**Comment by msgerbs** [comment]
I found the issue, fixing it now.
