### ISSUE TITLE
Radiation storm overlay interferes with runechat

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#53531]
Serb: Basil
Round ID: [145848](https://scrubby.melonmesa.com/round/145848)
BYOND Version: 513.1528
Server revision compiled on: 
Master commit: 998956ec632f2316cba475e208107259353c7f34
The following pull requests are currently test merged:
#53441: 'Fix bicon(icon2html) showing full dmis, fix asset cache hashes being incorrect.' by MrStonedOne at commit 97c319b8bf

Local commit: 2f7c2b65a1530b126983a972cd4738d0d4e3b126

## Reproduction:
The rad storm event overlay interferes with runechat. Probably also applies to lavaland ash storm; I haven't tested this though.

![image](https://user-images.githubusercontent.com/32391752/92412646-f0eb9180-f14c-11ea-8130-56cbaf869e34.png)

**Comment by Dennok** [comment]
While radstorm is bug, ash storm i preffer call a feature.

**Comment by Mooshimi** [comment]
layering oversight
