### ISSUE TITLE
Zombie/Ghoul Powder Fake Death Becomes Perma Death

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#53546]
## Reproduction:

1). Give some poor sod `/toxin/zombiepowder` or `/toxin/ghoulpowder`.
2). `Trait fake_death` and henceforth `trait death_coma` are applied.
3). Remove the reagent from their system through the miracles of modern medicine.
4). `Trait fake_death` and `trait death_coma` are retained.
5). They are now perma dead unless the traits are removed through admin means.

**Comment by itseasytosee** [comment]
By what manner are they being removed that causes this? stomach pump?

**Comment by Misdoubtful** [comment]
From what I've seen and done through testing, any manner. Including pump, removal of the reagent through admin tools, etc.

**Comment by itseasytosee** [comment]
Makes sense. The trait is removed upon end_metabolize 
`/datum/reagent/toxin/zombiepowder/on_mob_end_metabolize(mob/living/L)`
	`L.cure_fakedeath(type)`
	`..()`

**Comment by itseasytosee** [comment]
This also seems to be an issue with other regents like stimulants and changeling adrenaline who have a similar situation where traits are given on_mob_metabolize and taken away on_mob_end_metabolize

**Comment by itseasytosee** [comment]
My fix would be to also trigger the removal of such traits on_mob_delete but there may be a more elegant solution.

**Comment by msgerbs** [comment]
Does removing it via multiver and such not trigger end_metabolize?

**Comment by ATH1909** [comment]
> My fix would be to also trigger the removal of such traits on_mob_delete but there may be a more elegant solution.

Uh, correct me if I'm wrong, but on_mob_end_metabolize() should already trigger when the volume of a chem reaches 0 (or when a chem stops metabolizing).

I'll wager 10 credits that the stomach rework is the cause of this.

**Comment by Jared-Fogle** [comment]
on_mob_end_metabolize is in fact broken.
