### ISSUE TITLE
On Icebox, a cabin ruin spawned in the station port solars.

### ISSUE THREAD

**Issue by WarlockD** [tgstation/tgstation#53542]
## Round ID:[145875](https://scrubby.melonmesa.com/round/145875)

   
On Campbell Currently.  It might be meta but only me and no one else is on station and not sure if the shuttle won't be called soon or in a week.
   
Anyway. The cabin ruin, the one with the ladder that goes down to the ice rink to the Icebox crazy miner, spawned on the Port Quarter Solars with this giant ass hole all around it.  You can literally see the solar control and apc in the wall of the cabin and other things that were in the port hallways in the second zlevel down through the window.  Kind of weird.  The ladder is broken but everything else seems to work in the ruin.  Except for the walls and floors, the items don't seem affected even if they are on the wrong z-level.
  
One intresting game start message did pop up
```HEY! LISTEN! 4.7 seconds were wasted processing 4 turf(s) (connected to 57233 other turfs) with atmos differences at round start.```
   
Not sure if its important or not.  I will get video and dump a bunch of pictures.

**Comment by WarlockD** [comment]
https://www.youtube.com/watch?v=rNqX0mi8p6M
  Ok a video of it, eternally for all to see.

**Comment by msgerbs** [comment]
This might be due to the solars being surrounded by the area that allows ruins and there not being sufficient checking in the ruin spawning algorithm.
