### ISSUE TITLE
Sects seem to break Syndicate Bible healing

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#53551]
It's been a hot second since I tested this, but I suspect it's because the syndicate tome is kind of crap for how it works and is just giving it's user the Holy trait as a hacky way for it to work as a bible. 

Syndicate Bibles inherent the properties of the currently selected religious sect. If this is something like the tech religion, then they stop being able to heal living flesh.

Rare is this an issue, but this basically relegates their use to weapons because of something entirely unrelated to whatever weirdo religion the Syndicate pulled their tomes from.

I think the only way this is getting fixed is to entirely separate the tome from bibles and the user being holy or whatever horrendous shit tomes do.

@ExcessiveUseOfCobblestone

**Comment by ExcessiveUseOfCobblestone** [comment]
the intention of the tome is to be able to replicate chaplains so you can't be traitor tested, syndicate tomes are by design just bibles that allow you to posses the abilities of a normal chaplain.
