### ISSUE TITLE
Space was larger than usual and lavaland couldn't handle it.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#53562]
## Testmerges:
- #53441 

## Reproduction:
1. Take a GPS and a full space suit
2. Exit the station.
3. Notice that the Z-levels are around 380x380 rather than the normal 255x255.
4. Ghost and teleport to lavaland.
5. ...
![lavaland](https://user-images.githubusercontent.com/53582584/92540346-23eb5f00-f1f9-11ea-817d-26a58c0eea7c.jpg)
![legionspace](https://user-images.githubusercontent.com/53582584/92540350-28177c80-f1f9-11ea-8a25-18f9634e6343.jpg)

My bets are on this being adminry, but lavaland should be able to handle it without _that_ happening.

**Comment by LemonInTheDark** [comment]
GOD DAMNIT

**Comment by optimumtact** [comment]
This is not a lavaland issue afaik.
All z levels on a byond map must be the same width/height.

All z levels will be extended to account for a bigger single Z level and they will get space added to the edges.

**Comment by optimumtact** [comment]
@TemporalOroboros what map was loaded

**Comment by LemonInTheDark** [comment]
Scrubby says it was meta. I've seen it happen to almost the exact endpoint with icebox. On bagil if that matters, a few nights ago.

**Comment by TemporalOroboros** [comment]
It was meta. The next round was Brazil if that helps at all.

**Comment by LemonInTheDark** [comment]
Fuck atmos was having a heart attack that round

**Comment by TemporalOroboros** [comment]
All of lavaland draining into space was probably why.

**Comment by SpaceManiac** [comment]
likely the same bug as #53542
