### ISSUE TITLE
Panic siphon does not actually siphon

### ISSUE THREAD

**Issue by ReplicantTerry** [tgstation/tgstation#53576]
Issue reported from  Round ID: [145974](https://scrubby.melonmesa.com/round/145974) (/tg/Station - Terry [EU] [100% FREE LAG])

When you click "panic siphon" on an air alarm all the scrubbers get set to siphoning and extended, but they also all get turned off. So the panic siphon button doesn't work. Also the vents remain online.

Reporting client version: 513.1528

**Comment by msgerbs** [comment]
Huh, so it does. Who broke this?? We haven't had any PRs touching scrubbers or air alarms that I know of...

**Comment by msgerbs** [comment]
Oh. @nightred you broke it!

**Comment by nightred** [comment]
Really, ok i will look.

**Comment by msgerbs** [comment]
I got it don't worry about it, just giving you shit. Looks a copypaste gone wrong.

**Comment by nightred** [comment]
That was the exactly what i thought happened and you beat me to the fix thank you.
