### ISSUE TITLE
Xenos (and presumably other mobs) can dump out boxes even though they can't use them

### ISSUE THREAD

**Issue by msgerbs** [tgstation/tgstation#53571]
## Testmerges:
#53329 

## Reproduction:

1. Be a xeno
2. Attempt to use a monkey cube box, get a message saying "Your claws aren't capable of such fine manipulation!"
3. Click-drag to dump the box instead
4. (Optional) Break water tank on monkey cube pile for a bunch of free hosts

I'm not sure if this is intended or an oversight, but it seems like if I can't interact with boxes by clicking on them, I should not be able to interact by click-dragging either. I suspect this applies to any container and any mob that lacks the dexterity to use said container.

**Comment by Barhandar** [comment]
Should be able to destroy the box. Also, holding it upside-down and shaking is perfectly compatible with claws.

**Comment by msgerbs** [comment]
You know what, you've convinced me. Not a bug. Although maybe then they should default to dumping it out when they try to interact with it?
