### ISSUE TITLE
The action button for the Gygax's leg actuator mode doesn't reflect if it's on or not properly + Gygax infinite sprint bug

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#53582]
ROUND ID: 145976

## Testmerges: #53329 

Description: The Leg Actuator's button sprite isn't synced with if the actuators are actually on or off. Also, the Gygax's sprint is currently broken and doesn't consume any energy when on.

## Reproduction: Spawn/Build a Gygax with T4 parts for best results, climb in, click the 'toggle actuators' action button, notice it it becomes selected, but you can't sprint. Click it off again, now you can sprint. You will also notice that your sprint doesn't use any extra energy.

Explanation: The action button sprite for the Gygax's leg actuators doesn't properly sync to whether it's on/off, plus a gygax with T4 parts (easily obtainable within 30 mins to 1 hr) can sprint forever, as the sprint doesn't drain extra energy like it's supposed to. This probably isn't supposed to happen, right?

**Comment by msgerbs** [comment]
So the issue isn't the sprite at all, but that the state of the button doesn't match what the mech is actually doing? Am I understanding this right?

**Comment by githubuser4141** [comment]
> So the issue isn't the sprite at all, but that the state of the button doesn't match what the mech is actually doing? Am I understanding this right?

Yes, that's right. Also, the gygax has infinite sprint which I'm 99% sure is a bug, not a recent mech buff.

**Comment by msgerbs** [comment]
Alright. Can you edit the title to reflect that, just so nobody skips over this thinking it's a spriting issue?

**Comment by githubuser4141** [comment]
> Alright. Can you edit the title to reflect that, just so nobody skips over this thinking it's a spriting issue?

Okay, done.

**Comment by msgerbs** [comment]
Thanks!

**Comment by timothymtorres** [comment]
Looks like #71113 might have fixed this.  Then it seems like #73051 appeared as a result.
