### ISSUE TITLE
Heretic's cursed heart does not properly track the target when the target is in a container

### ISSUE THREAD

**Issue by Laz0rG** [tgstation/tgstation#53583]
## Reproduction: 
Have a target be picked by the cursed heart. Have the target enter a locker/morgue tray/crate/coffin, etc. the cursed heart will point you to the mining Z-level and lead you to a seemingly random spot in mining while the target is actually in a locker somewhere in the station z-level. This is an old issue that was around ever since heretic got merged.

**Comment by LemonInTheDark** [comment]
gotta love it

**Comment by Laz0rG** [comment]
> gotta love it

It is especially fun when someone decides to hide in a locker all round and play on another sever just to spite you and induce seething.
