### ISSUE TITLE
Syndicate infiltrator suit doesn't fit into it's own case

### ISSUE THREAD

**Issue by Relyksboa** [tgstation/tgstation#53592]
## Reproduction:
When you take the suit out of the case, it doesn't fit when you put it all in.

**Comment by itseasytosee** [comment]
It's a reskinned toolbox. this is applicable for a ton of different syndicate items, notably the tactical bundles.

**Comment by msgerbs** [comment]
Agreed, not a bug, although possibly a consistency issue? It would be a bit stronk if buying a syndi item gave you a supersized toolbox that could fit large items. A possible improvement would be a message when buying the item that it won't fit back in its container?

**Comment by TemporalOroboros** [comment]
Isn't there a way to override what can fit into a container? I think it's used for medical belts holding medical tools and such.

**Comment by TemporalOroboros** [comment]
Found it:

https://github.com/tgstation/tgstation/blob/134964a0a5173225a81f56100c4bdd4060fd395c/code/datums/components/storage/storage.dm#L13-L19

**Comment by msgerbs** [comment]
I guess we could do that, yeah. I think that's kind of powercreep though as it makes concealing bulky traitor items much easier.

**Comment by TemporalOroboros** [comment]
From the looks of it, the infiltrator case should be able to hold all of the items it contains individually, but it would need a total capacity of 15 to hold all of them at once. It currently has... 14 as far as I can tell.

**Comment by necromanceranne** [comment]
It's meant to hold the full set. I've just been lazy to fix it, so if someone wants to fix that, it'd be great. You're meant to be able to doff the suit and store it back into it's own case.
