### ISSUE TITLE
Spells take 10x longer to recharge.

### ISSUE THREAD

**Issue by Deltarin** [tgstation/tgstation#53595]
## Round ID:
[145982](https://scrubby.melonmesa.com/round/145982)

## Reproduction:
Spells seem to take around 10x longer to recharge, i noticed this during my wizard round and decided to test it out later in the thunderdome, fireball takes around 1 minute, jaunt takes around 5, and ei nath takes about 10.
You can reproduce this by just using any spell and looking at the time it takes to recharge.

**Comment by Timberpoes** [comment]
Thanks for the report! Fixed in the linked PR and I have included a VV workaround with screenshots in the meantime.
