### ISSUE TITLE
[missing sprite] atmos firetank backpack

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#53605]
taking the hand sprinkler from the backpack , changing configuration and putting it back makes the whole back sprite go missing

**Comment by msgerbs** [comment]
I'm not sure this is a sprite issue @nightred, it sounds like it may be using the wrong icon_state when put back in the backpack.

**Comment by nightred** [comment]
Sorry i thought you said that the icon does not show

**Comment by msgerbs** [comment]
I didn't make this, and OP did say the icon doesn't show but only after putting it back in. To me that points toward the icon_state being set wrong since it works when first spawned. I'll check it out.

**Comment by msgerbs** [comment]
I was unable to reproduce this or find anything that looked like it might cause this. @Tlaltecuhtli can you try it again, maybe make a video or screenshots or something?

**Comment by Tlaltecuhtli** [comment]
reproduced by spam clicking while pressing z repatively
![backpack bug](https://user-images.githubusercontent.com/33834933/92928369-453d8c80-f43f-11ea-953d-931384474a16.PNG)

**Comment by msgerbs** [comment]
I still can't make this happen. What were you clicking on specifically?

**Comment by Tlaltecuhtli** [comment]
pressing z and clicking floor

**Comment by msgerbs** [comment]
Adjacent to you or away from you?

**Comment by Tlaltecuhtli** [comment]
i dont think it makes a difference

**Comment by nightred** [comment]
looks like something is dysynced, does switching it again fix the issue?

**Comment by ArcaneMusic** [comment]
I am also unable to reproduce. Spamclicking and activating the nozzle doesn't seem to be changing much here, but I would have to imagine this is some kind of issue with the tank not updating.

**Comment by dragomagol** [comment]
Saw this again on Manuel today 
![image](https://user-images.githubusercontent.com/66640614/100298804-e7511900-2f46-11eb-8bf4-f124951ae010.png)

**Comment by ArcaneMusic** [comment]
We really just need someone to VV the backpack to see what icon_state it has when it's breaking, though.

**Comment by dragomagol** [comment]
I was able to reproduce it again on local (after a lot of clicking) and this is the VV for the tank's icon 
![image](https://user-images.githubusercontent.com/66640614/100315904-4c6c3500-2f6e-11eb-842f-ca8e14edce90.png)

**Comment by dragomagol** [comment]
Update: I figured out how to reproduce this quickly. Switch to the spray nozzle and spray the same tile that you're on and the sprite should vanish.

**Comment by dragomagol** [comment]
Should be fixed by #55705

**Comment by ArcaneMusic** [comment]
Ah, comment it on the actual PR if it's not merged yet
