### ISSUE TITLE
[bugged sprite] PJs

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#53630]
![erro pjs](https://user-images.githubusercontent.com/33834933/92927709-53d77400-f43e-11ea-9acd-94b1b8d8314f.PNG)

146088

not sure how it happened someone threw them on the floor

**Comment by itseasytosee** [comment]
These are normal PJs and not syndie ones, right? there are no references to icon change in the PJ code, this definitely needs reproducing.

**Comment by Twaticus** [comment]
seems to be a mapping issue on the alien z3ta emergency shuttle. it spawns /obj/item/clothing/under/misc/pj in the closet which doesnt actually have a sprite. /pj/red & /pj/blue are the ones with sprites.

**Comment by ArcaneMusic** [comment]
![image](https://user-images.githubusercontent.com/41715314/97795870-fd86e600-1be1-11eb-86d5-0d1b72464c9c.png)
Unable to reproduce as of current, the object path seems to have been changed to blue Pjs at some point, showing the correct sprites.

**Comment by EOBGames** [comment]
resolved as of #54187
