### ISSUE TITLE
Crystal event is ~~a meme~~ unbalanced and terrible

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#53634]
Round ID: [146100](https://scrubby.melonmesa.com/round/146100)

A horde of constantly respawning skeletons in multiple points on station, some of which can shock you, that you need to be protected from as you glacially slowly close a portal and then get to supermatter. Oh and you need active miners to do anything with it because it requires protolathe + silver + anomaly neutralizer. And the skeletons explode into opaque LEXORIN WHAT THE FUCK SERG clouds on death a-la blob but worse and dust you if they manage to kill you.

**Comment by ArcaneMusic** [comment]
Issues should not be used for balance concerns. A more reasonable place would be on the forums here:
https://tgstation13.org/phpBB/viewforum.php?f=10

**Comment by msgerbs** [comment]
If there are actual code issues with it please clarify them in your issue, otherwise I'm going to echo Arcane and say go to the forums.

**Comment by Qustinnus** [comment]
If you want to use issues for suggestions at least put some effort into typing something properly formatted and less salty rant. Use the forums instead.
