### ISSUE TITLE
Leaving the escape shuttle while in transit on icebox simply deposits you onto the ice moon.

### ISSUE THREAD

**Issue by itseasytosee** [tgstation/tgstation#53643]
Not really a bug but something to think about.
If you leave the escape shuttle you are simply teleported somewhere on the map, this can include inside walls and such.
You'd think falling from orbit would have bigger consequences.

**Comment by msgerbs** [comment]
I think falling out used to drop you on lavaland, I assume this is related although I'm not sure why this only happens on ice.

**Comment by Barhandar** [comment]
Falling out dropped you at random point in space, but icebox doesn't _have_ space, it has icemoon only. It never dropped players to lavaland as far as I know - however, there's an option to send _individual pods_ offstation and those DO drop to lavaland; or in icebox's case, to random point on any of icemoon's z-levels, including station's. Quite funny when the "escape pod" drops basically right next to where it started.

**Comment by msgerbs** [comment]
I'm not touching this one, somebody else can poke this rat's nest of consistency issues...

**Comment by itseasytosee** [comment]
It's only really one issue. I think the obvious solution would be just to splatter you against the floor falling from space and all that.

**Comment by msgerbs** [comment]
I would argue that escape pods landing 3 feet away from the place you're escaping from is also a consistency issue, but I guess that's for a different issue report.

**Comment by TheBonded** [comment]
doesn't it make sense to fall back onto the planet while you are leaving it? it's gravity would surely still affect you
