### ISSUE TITLE
metal hydrogen axe missing back sprite

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#53645]
## Testmerges:

#53627: 'Makes Ice Box Botany Cozy as Fuck ((MULTI-Z)) (((FUCK CABLE HUBS)))' by tralezab at commit 770a85a9f9

## Reproduction:
get metal hydrogen axe
put metal hydrogen axe on backpack slot
there is no sprite
![image](https://user-images.githubusercontent.com/34697715/92984147-5e593400-f465-11ea-9823-348667043789.png)
:(

**Comment by Tharcoonvagh** [comment]
>metal hydrogen axe
**W H A T**
