### ISSUE TITLE
Vend-a-trays? Vendor trays? I just want to sell food, for god's sake!

### ISSUE THREAD

**Issue by IcePacks** [tgstation/tgstation#53646]
[Round ID]: Literally any round you trontobringus

## Testmerges: 
I remember now why I hate making issue reports
## Reproduction:
1) Find a vending tray
2) Swipe your ID on it (thud)
3) Try to put a brainburger (your mother's recipe) or any food on it
4) The tray (display case) tells you to fuck off with that shit 

I should also note that you can't put food in the food cart either, making almost all of my food-based RP extremely difficult

**Comment by msgerbs** [comment]
Looks like this is because the new food uses a different typepath and the tray can only use one. It'll have to be refactored to use a list instead.

**Comment by Cyprex** [comment]
You can remove sections of the template if they're not relevant. Putting a round ID is usually a good idea in case there are runtime (logs).
