### ISSUE TITLE
Split personalities don't switch control

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#53644]
## Round ID:

Either 146113 or 146115 for someone else's account of it happening, don't remember what the round number was when it happened to me.

## Reproduction:
Decided to roll for someone's split personality near the end of a round (shuttle at about ETA: 3:00), didn't get control of their body at all between becoming their split personality and the round ending.

**Comment by itseasytosee** [comment]
Could just be bad rng, probably not a bug.

**Comment by msgerbs** [comment]
Not willing to call it Not A Bug yet but I would like to see some more thorough testing if someone thinks it's a bug.

**Comment by Time-Green** [comment]
I’ve gone five minutes without switching, it’s definitely just bad RNG
