### ISSUE TITLE
light fixtures for supermatter south wall are misplaced on metastation

### ISSUE THREAD

**Issue by UnlimitedVanillaWorks** [tgstation/tgstation#53654]
## Round ID:
n/a found locally

## Reproduction:
Walk to supermatter room. Locate light fixtures. be mildly annoyed
![image](https://user-images.githubusercontent.com/71117108/92992610-87de9200-f52f-11ea-85c0-c1feb239ff5a.png)

**Comment by nightred** [comment]
good eye
