### ISSUE TITLE
Changeling unable to absorb after being killed and drained

### ISSUE THREAD

**Issue by Tophwells** [tgstation/tgstation#5365]
As changeling, I was killed and drained by another ling. Later, genetics revived me. Any use of my Absorb DNA power or sting just produced an error message saying I already had the maximum number of stored genomes, although I only had one.

**Comment by Tenebrosity** [comment]
I encountered something similar recently. I was a changeling who got absorbed, so I simply regenerated. I regenerated looking like a husk, with no DNA, fair enough. I used absorb DNA sting on someone to get another body to transform into. When I transformed, I got the guy's voice but stayed husked. I tried to absorb DNA from other people, but it kept telling me I needed to transform before I could store more DNA, but the only person I could transform into was the guy I already was, and it didn't fix the problem.

**Comment by Cheridan** [comment]
The only bug here is that genetics cloned a husk

**Comment by Jalleo** [comment]
Husk cloning is prevented now i believe so its just the regenerating which should be a easy fix i might do it later this week.

**Comment by tedward1337** [comment]
Has this been fixed?

**Comment by Davidj361** [comment]
I don't see any issue as of now.
