### ISSUE TITLE
Atmospherics devices cannot have transfer rate set above half (200L/s) in the ui

### ISSUE THREAD

**Issue by UnlimitedVanillaWorks** [tgstation/tgstation#53659]
## Round ID:
[146148](https://scrubby.melonmesa.com/round/146148) but not relevant

## Testmerges:
none relevant

## Reproduction:
Volume based atmospheric devices were changed to have a maximum transfer rate of 400L/s in #52981. This is reflected in their values at roundstart/creation via rpd/alt+clicking or using the max button in their ui. However attempting to set values above 200 with the slider/ typing it in fails. Also applies to atmospherics supply tank consoles.

**Comment by msgerbs** [comment]
I had also noticed this and had not yet reported it. Thank you!
