### ISSUE TITLE
Snowlegions turn their victims into regular lavaland legions

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#53683]
Issue reported from  Round ID: [146229](https://scrubby.melonmesa.com/round/146229) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
Reporting client version: 513.1532

While it's very convenient for recovery of the dead, it's very MUH IMMERSHUN.

**Comment by dragomagol** [comment]
Appears to have been fixed
