### ISSUE TITLE
Space-related events and things don't function on Icebox

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#53689]
Issue reported from  Round ID: [146246](https://scrubby.melonmesa.com/round/146246) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
Reporting client version: 513.1532

For example, any kind of meteor wave events happen but do nothing, meteor shield station goal can't be completed (shields can only be deployed in space), aurora caelus miiiiight also happen unless map overrides config option, stuff like that.

**Comment by nightred** [comment]
space based goals and events should be disabled for planet based stations.

**Comment by Barhandar** [comment]
I'd prefer to have planet-based versions of the events instead, e.g. instead of meteors (sideways) you get bombardment (from above).

**Comment by Jacquerel** [comment]
This has been resolved since this issue was posted.
