### ISSUE TITLE
New Mech Issues related to Strafe Toggle

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#53708]
**Alt-Move swapping seems to proc a step regardless of whether you move or not into any different direction.**
So, when you hold Alt, the mech will attempt to swap direction to the one you choose as though you have strafe off. However, this seems to have no cooldown whatsoever, and actually doesn't care about whether or not a direction swap occured or a step for that matter. It will definitely swap directions, but it seems to actually be an entirely separate from whether or not a step occurred and seems to happen even if you don't move at all, but try to move (say, into a wall). This could actually be a problem with mechs themselves spending step power regardless of whether or not a step occurred, but I'd need to test that a bit more.

To recreate this:
A) Find a wall
B) Turn on strafe and hold down Alt.
B-b) Take out headphones, it's loud
C) Walk into wall
D) Drain your battery and hurt your ears if you didn't follow B-b

Shout out to @TiviPlus.

**Comment by msgerbs** [comment]
The strafe check is one of the last checks in the move proc. Maybe it should be first.

**Comment by TiviPlus** [comment]
Unable to reporoduce

Also unable to see why this would be happening as the first check in the move proc is

**Comment by msgerbs** [comment]
The only thing I can reproduce with this is that holding alt makes noise and uses power even if you didn't actually turn (because you were already facing that direction). I can't reproduce anything to do with walls.

**Comment by TheBonded** [comment]
As far as I know, this no longer happens
