### ISSUE TITLE
New Ice-botany's vendors are completely free for the botanists (even the stuff that shouldn't be free)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#53701]
## Round ID:

[146262](https://scrubby.melonmesa.com/round/146262)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/93042180-0876be80-f614-11ea-93a5-ada88fa78635.png)

![image](https://user-images.githubusercontent.com/51863163/93042200-13315380-f614-11ea-9f66-5a95cca1d800.png)

(but if you dont fix this bug i'd be okay with it)

**Comment by Time-Green** [comment]
There’s some code in-place to make off-station vendors free due to accountless ghost roles. I’m guessing that happened here

**Comment by Mickyan** [comment]
https://github.com/tgstation/tgstation/blob/de288cb657b163629b89bf58b011af85ef57fa0b/code/modules/vending/_vending.dm#L143-L150

**Comment by msgerbs** [comment]
Should the lower z of Ice be considered on-station? As we add more stuff to that z level, this may have unexpected affects on many other things too (captain goes down to botany basement? Byebye nuke disk! Drone goes downstairs? Byebye!)

**Comment by msgerbs** [comment]
The ideal long-term fix here is probably to convert this to be area-based and move all station-bound areas into a single parent type so that we can check istype(/area/station) rather than checking for z-level traits. This would also affect stationbound/stationstuck atoms getting teleported into rounds on the main ice box z-level when leaving the z-level.

**Comment by Barhandar** [comment]
That would have a pretty big side effect of said stuff vanishing if you walk/float a bit away from the station - that is, whenever you as much as touch area not designated as station.

I think it should be z-based with some area overrides, so you don't get screwed by invisible not-a-station areas but also can't hide stuff in what is effectively icy lavaland.

Admittedly watching nukies try and get to disk through a demonic miner would be funny.

**Comment by msgerbs** [comment]
Have a different space area for near-station space then, it could even cover the whole z-level if you really wanted, but I think it's not really in the spirit of stationstuck/stationloving to be off in a corner of the station z-level.
