### ISSUE TITLE
Ice-Botany is not wheelchair accessible

### ISSUE THREAD

**Issue by Jolly-66** [tgstation/tgstation#53713]
## Round ID:
Any round after the updated botany on Icebox

## Reproduction:
Not entirely sure if this would be a "bug", but more so an oversight. The new Ice-botany doesn't allow those in wheelchairs to access the bottom level, without painfully having to hurl themselves down the stairs, or having the engineers wire up a quantumpad. 
Honestly, this may not even be a super big issue considering how little others play with the paraplegic trait, at least, seriously, that is.

**Comment by msgerbs** [comment]
Do we need a space ADA law?

**Comment by Tlaltecuhtli** [comment]
the wall behind the stair causes this, @tralezab are you gonna fix  the map problems?????

**Comment by ArcaneMusic** [comment]
Straight up feature.

**Comment by nightred** [comment]
This sounds more like an issue with wheel chair movement, if the stairs work without that wall then this is not a map error.

**Comment by Jolly-66** [comment]
I should mention with further game play, players can go UP the stairs from the bottom level, but must unbuckle themselves. The chair will be teleported to the upper level but the player will remain (until they're unbuckled, of course).

It still beats flinging off the railing, yet people will continue to do it. Join the cripple club you guys!

**Comment by Jared-Fogle** [comment]
look i want accessibility features as much as the next game dev but...
