### ISSUE TITLE
oxygen/plasma tanks exploding inside atmospherics devices causes ui/sprite issues and runtime spam.

### ISSUE THREAD

**Issue by UnlimitedVanillaWorks** [tgstation/tgstation#53717]
## Round ID:
n/a local

## Testmerges:
n/a

## Reproduction:
Make a tank rupture/fragment (exceed 35/40 atmospheres) while it is inside a portable air pump/scrubber or canister.

These happen whenever atmos ticks so twice a second I think.
![image](https://user-images.githubusercontent.com/71117108/93105471-7691b300-f6f2-11ea-9072-02bfd4e65d6f.png)
![image](https://user-images.githubusercontent.com/71117108/93101690-ee111380-f6ed-11ea-9c21-d2a610caa058.png)
both images are after the tank has exploded
![image](https://user-images.githubusercontent.com/71117108/93103078-88258b80-f6ef-11ea-92e7-80b4f32d29be.png)
![image](https://user-images.githubusercontent.com/71117108/93103149-9f647900-f6ef-11ea-9f74-8a6cc1427868.png)

**Comment by msgerbs** [comment]
Oh joy, this one should be fun. Now that you mention it, I've also noticed a lot of weird behavior around exploding tanks in this same scenario.

**Comment by LemonInTheDark** [comment]
dupe? maybe of https://github.com/tgstation/tgstation/issues/51468

**Comment by UnlimitedVanillaWorks** [comment]
Ah ye pretty much. I did actually check if had been reported beforehand but must've missed that.
