### ISSUE TITLE
Player controlled lobstrosities can't charge.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#53726]
## Testmerges:
- #53463 
- #53596 

## Reproduction:
1. Have xenobiology create a lobstrosity
2. Have xenobiology sentience potion a lobstrosity
3. Accept the invitation
4. Notice that there is no action button, verb, or hotkey for charging

It's their main defining feature, they should be able to use it.

**Comment by TheBonded** [comment]
fixed by https://github.com/tgstation/tgstation/pull/58199 several months ago
