### ISSUE TITLE
Using the "Regenerate" ling ability removes the tied tongue trait

### ISSUE THREAD

**Issue by Catbugg4** [tgstation/tgstation#53723]
Issue reported from Round ID: [146304](https://scrubby.melonmesa.com/round/146304) (/tg/Station - Terry [EU] [100% FREE LAG])

Basically what the title says, the Tongue Tied trait is ironically, tied to the tongue organ. Using the regenerate ability removes said tongue and replaces it with a regular one

**Comment by msgerbs** [comment]
Is this a bug? Lings are supposed to recover from any negative effects when regenerating.

**Comment by itseasytosee** [comment]
It is. this really should be tied to the brain.

**Comment by nightred** [comment]
This is a round start quirk, and needs to be made in to a trait.

**Comment by Wallemations** [comment]
Fixed it

**Comment by msgerbs** [comment]
@Wallemations Which PR fixed it?

**Comment by Wallemations** [comment]
> @Wallemations Which PR fixed it?

#53890

**Comment by msgerbs** [comment]
Thanks. Fixed by #53890
