### ISSUE TITLE
Multiz piping missing directional sprites and has error tag

### ISSUE THREAD

**Issue by nightred** [tgstation/tgstation#53722]
The Multiz pipe `/obj/machinery/atmospherics/pipe/simple/multiz` does not render properly in an open air location.
There is also no directional connection sprites for the device. [E-W]

![image](https://user-images.githubusercontent.com/6491940/93125261-79f45280-f690-11ea-8107-d1a36d025e4e.png)

**Comment by Dennok** [comment]
As i see on MultiZ debug, it just has error message.
And it don't need to be over openspace to work.

**Comment by nightred** [comment]
I like the idea of an open pit wiring hub, but good to know.
