### ISSUE TITLE
Space dragon portals never fully charge and only spawn one sentient carp

### ISSUE THREAD

**Issue by Stewydeadmike** [tgstation/tgstation#53734]
## Round ID:
[146323](https://scrubby.melonmesa.com/round/146323) Manuel

## Testmerges:
#53329: 'testing smooth movement fixes'
#53596: 'Removes Admin Stickyban Exemption Workaround'

## Reproduction:
A space dragon spawned and dropped their rift and I took the carp spawn. After awhile the portal just got stuck at 99% and never finished charging, nor created any announcement. It also never created anymore sentient carp after the initial one. It did, however, start randomly spewing out non-sentient carps after it stopped charging for whatever reason.

**Comment by ATH1909** [comment]
@IndieanaJones

**Comment by IndieanaJones** [comment]
I assume this has to do with the delta time changes made not too long ago, probably broke space dragon's subsystems.  I'll take a look.
