### ISSUE TITLE
Romelor zombies can't succumb

### ISSUE THREAD

**Issue by Tumesuo** [tgstation/tgstation#53744]
Issue reported from  Round ID: [146363](https://scrubby.melonmesa.com/round/146363) (/tg/Station - Terry [EU] [100% FREE LAG])

Reporting client version: 513.1515

**Comment by Barhandar** [comment]
The consequence of succumbing clearing up the zombie tumor and coderbus deciding that preventing succumbing is a better option than fixing the error of it clearing the tumor. #52836

**Comment by nightred** [comment]
I am in agreement that this is a feature of the zombies and is working as intended.
Added a message if you are unable to succumb
