### ISSUE TITLE
Light overlay from luminescent eyes is not hidden from right click and alt click menus

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#53765]
## Reproduction

1. Get luminescent eyes
2. Turn 'em on
3. Right click the tiles in front of you. You will see "eye lighting".

![dreamseeker_2020-09-15T09-08-08](https://user-images.githubusercontent.com/35135081/93313769-bec9d780-f7bd-11ea-964d-481b62f9eaf1.png)

4. Alt click the tiles in front of you. You will see this.

![2020-09-15T09-08-00](https://user-images.githubusercontent.com/35135081/93313863-e0c35a00-f7bd-11ea-891d-cd5b0381cfda.gif)

**Comment by Tlaltecuhtli** [comment]
the icon dump on alt click happens regardless of having eye lights

**Comment by cacogen** [comment]
Haven't played since before this bug but maybe it shows the whole .dmi if an atom's icon is undefined?

**Comment by Jared-Fogle** [comment]
heh heh. oversight. cause its...forget it

**Comment by timothymtorres** [comment]
Duplicate of #53824

**Comment by Mothblocks** [comment]
i was so much funnier back in 2020

**Comment by Mothblocks** [comment]
...also my issue was newer

**Comment by timothymtorres** [comment]
Aye it was older but the other issue's title was better and it had more detailed information/troubleshooting.  Still, I liked the oversight joke!
