### ISSUE TITLE
Wheely heely blood overlay in the wrong spot

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#53762]
![image](https://user-images.githubusercontent.com/33292112/93286600-ecbc1580-f7d7-11ea-8ce4-6ba597ee3bf9.png)

Blood appears down left.

**Comment by Mickyan** [comment]
likely because they are big sprites to fit the wheels (64x64), no clue how to fix though

**Comment by Mickyan** [comment]
just to confirm this is a problem with all big sprites like the cage helmet
![Screenshot_13](https://user-images.githubusercontent.com/38563876/93721332-b7c11180-fb8f-11ea-923a-1832f94b6e36.png)
