### ISSUE TITLE
Unsecured chemical grenades use the wrong iconstate

### ISSUE THREAD

**Issue by msgerbs** [tgstation/tgstation#53792]
## Testmerges: 
#53761: 'completely normal delta station absolutely nothing was changed about it i swear' by Paxilmaniac at commit 63f4410097
#53596: 'Removes Admin Stickyban Exemption Workaround' by bobbahbrown at commit adbee092e4

## Reproduction: 

Make an secured chemical grenade. Observe that it flashes menacingly like an active chem grenade. PANIK.

**Comment by CoffeeDragon16** [comment]
I was unable to recreate this.

**Comment by ArcaneDefence** [comment]
Doesn't happen now unless you pulse the wire in an unsecured grenade casing before finishing assembling it, and once it is assembled it fixes itself.
