### ISSUE TITLE
Most subtypes of claymore null rods have the wrong belt sprite

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#53791]
The claymore null rod didn't have a belt sprite, and neither did most of the subtypes. When the claymore null rod was given a belt sprite, most of the subtypes got missed and now just inherit the claymore belt sprite.

/obj/item/nullrod/claymore/darkblade
/obj/item/nullrod/claymore/chainsaw_sword (Can use the same belt sprite that /obj/item/nullrod/scythe/talking/chainsword uses)
/obj/item/nullrod/claymore/glowing
/obj/item/nullrod/claymore/multiverse
/obj/item/nullrod/claymore/saber
/obj/item/nullrod/claymore/saber/red
/obj/item/nullrod/claymore/saber/pirate

Issue reported from  Round ID: [146457](https://scrubby.melonmesa.com/round/146457) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1526

**Comment by necromanceranne** [comment]
yeah the nullrods need a lot of icon work. Even normal claymores lack a belt sprite because I forgot. I'll fix that at some point!

**Comment by ArcaneMusic** [comment]
Necroanne did eventually fix it at some point (in #54235, #53804, and in some of my belt sprite PRs).
