### ISSUE TITLE
Entering odyseus mech while with an med hud implant removes the implant's ability after exiting the mech

### ISSUE THREAD

**Issue by scubbbles** [tgstation/tgstation#53808]
However, taking the implant out and putting it back in via surgery makes it so the implant works again.

Issue reported from  Round ID: [146501](https://scrubby.melonmesa.com/round/146501) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1530

**Comment by JenqaDev** [comment]
implant added
![image](https://user-images.githubusercontent.com/43709941/147887667-43bb5a6c-0f71-4a37-8d38-aeb8d2b1b7fa.png)

hud working in mech
![image](https://user-images.githubusercontent.com/43709941/147887683-e773919e-e031-47ff-bde7-7419934e612d.png)

implant's hud maintains after leaving the odysseus
![image](https://user-images.githubusercontent.com/43709941/147887693-5a7fa573-136e-4d1e-a7d4-23e416dd8ad0.png)

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/57964
