### ISSUE TITLE
Nutriment pump implant does not count as a stomach despite occupying stomach slot

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#53813]
Which means that its meager benefit of not needing to eat is negated by being completely unable to eat, including pills and drinks.

**Comment by TemporalOroboros** [comment]
I don't think it is intended to fit in the stomach slot. I think it's supposed to fit in the stomach auxiliary slot.

**Comment by Barhandar** [comment]
It has always required removing the real stomach, but it didn't have negative effects before the PR that made lacking stomach prevent eating.

**Comment by TemporalOroboros** [comment]
I have never had to remove the real stomach to insert a nutrient implant. I will test this and get back to you.

**Comment by Barhandar** [comment]
Nevermind it does occupy aux slot that doctor was just stupid
