### ISSUE TITLE
Butchering sometimes produces excessively long blood trails

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#53811]
Also known as: BLOOD METEORS
Issue reported from  Round ID: [146508](https://scrubby.melonmesa.com/round/146508) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
Reporting client version: 513.1532

(it stopped when it hit a rockwall on the other side of hiero arena)
![trail](https://user-images.githubusercontent.com/2338212/93541136-42222f00-f95e-11ea-9805-3aaef7f79607.PNG)

**Comment by TheBonded** [comment]
Feature
