### ISSUE TITLE
Lavaland ruins clockwork hulk..er..moved?

### ISSUE THREAD

**Issue by WarlockD** [tgstation/tgstation#53828]
## Round ID: [146546](https://scrubby.melonmesa.com/round/146546)

Not sure it can be reproduced because of the RNG, but I am sure there are some runtimes in there for it.  Currently this is Campbell and live as of 9/18.2020.  Not sure how but as you see from the pictures, the hulk is below where it should be.

Not sure if its a recent change or such.
![dreamseeker_8HtSXXwfSZ](https://user-images.githubusercontent.com/1102671/93638018-32393800-f9bc-11ea-9f8e-daef4ce23ab3.png)
![dreamseeker_9PEvl4Fn23](https://user-images.githubusercontent.com/1102671/93638024-349b9200-f9bc-11ea-9bb3-698e3ecd414c.png)
![dreamseeker_QCQykSFkg5](https://user-images.githubusercontent.com/1102671/93638036-38c7af80-f9bc-11ea-9eea-566818cc1953.png)

**Comment by Barhandar** [comment]
Two days ago Ratvar's corpse was in proper position on Sybil.

**Comment by ATH1909** [comment]
HE COMES

**Comment by TheBonded** [comment]
Probably fixed by https://github.com/tgstation/tgstation/pull/57233

I believe the issue that caused this was that goliaths could move the entire thing by walking into it, as they can with windows and other wrenched down objects.
