### ISSUE TITLE
Sleeping carp users can't heal their wounds using conventional methods

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#53843]
For some reason, https://github.com/tgstation/tgstation/pull/53307 only accounts for species with the TRAIT_PIERCEIMMUNE trait, not other sources of the TRAIT_PIERCEIMMUNE trait, like sleeping carp.

This means that sleeping carp users have very few options (other than cryo) for dealing with, say, broken legs.

**Comment by Tlaltecuhtli** [comment]
why does carp give pierce immunity in the first place?

**Comment by necromanceranne** [comment]
It's because originally the piercing immunity was a double edged sword to their resistances. Those got removed, this didn't. If you want an easy fix, given them back permanent deflection (a one line change) and remove this trait.
