### ISSUE TITLE
Move intent (walk/run) is cycled if pressing modifier + hotkey for "Hold to toggle move intent" 

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#53844]
Finally figured why walk mode is sometimes suddenly on. Only from local testing. 

## Reproduction:

1. Unbind **press to cycle move intent**. 
2. Bind **Hold to toggle move intent** to C (or whatever). 
3. Hold **shift+C**, **ctrl+C** or **alt+C**. Nothing happens. 
4. Release **shift+C**, **ctrl+C** or **alt+C**. You are now in walk mode. 

**Result:** You now permanently walk. Can be toggled back to "run" by pressing shift+C again. 

**Expected result:** Either nothing should happen when I press shift+C (since nothing is bound to it), or it should be in walk mode only while C is held.

**Comment by Couls** [comment]
This has to do with how keyUp works and how it doesn't take into account the modifiers
this is intended behaviour as written in the comment here
https://github.com/tgstation/tgstation/blob/4a949c2af8d3b5595ee905cc7610e3d4fe0fcca9/code/modules/keybindings/bindings_client.dm#L87
this can be changed to take in account all the modifiers(shift, ctrl, alt etc) and i'll leave this open for a bit if someone wants to do that but this isn't unintended behaviour
