### ISSUE TITLE
Icebox's ladders can be broken, but not rebuilt/cannot get out of the caves with station ladders broken

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#53853]
Issue reported from  Round ID: [146637](https://scrubby.melonmesa.com/round/146637) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
Reporting client version: 513.1532

**Comment by Zytolg** [comment]
This isn't a mapping issue, as we can't do anything to fix this (aside from adding more ladders which doesn't address the issue). This is an oversight.

**Comment by ArcaneMusic** [comment]
#54485 was good step to fixing this, effectively, but I imagine that we can't call this fixed as the crafted ladders don't connect to broken existing ladders, right? @wesoda25

**Comment by wesoda25** [comment]
@ArcaneMusic sorry just seeing this now, pings don't alert me. Ladders you craft can't be connected to existing ladders so yes, my PR doesn't fix this. It does provide a way to circumvent the issue by crafting a new set of ladders in the areas you want to get in and out of.

Honestly just close this.

**Comment by ArcaneMusic** [comment]
Sure thing.
