### ISSUE TITLE
Kudzu in icemoon wastes is pretty much unstoppable

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#53854]
Also known as: literally junglebox

Issue reported from  Round ID: [146637](https://scrubby.melonmesa.com/round/146637) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
Reporting client version: 513.1532

It can grow over them in all directions, and there's a lot of big open areas around icebox that allow it to spread MUCH faster than it can be dealt with.

Also, venus human traps are overpowered - RANGED HARDSTUN, 25 melee damage, 60 object damage, no damage from wrong atmos, and being a simplemob it's also effectively fireproof.

**Comment by ATH1909** [comment]
note that venus human traps CAN'T chainstun you with their ranged hardstun, and it stuns for a pretty short amount of time

they're also pretty much the only things making kudzu actually viable currently. wouldn't mind them becoming a default feature of kudzu, actually...

**Comment by Barhandar** [comment]
Multiple ones (3+) can chainstun and with how much damage they do combined with enough speed to cross the distance, the short length of the stun doesn't matter.

**Comment by ATH1909** [comment]
> Multiple ones (3+) can chainstun and with how much damage they do combined with enough speed to cross the distance, the short length of the stun doesn't matter.

So fight the kudzu in groups, then. The crew should outnumber the VHTs if they work together.

**Comment by nightred** [comment]
I am in the camp of kudzu growing in the wilds is a pain to deal with.
But this sounds like emergent game play on planet stations and is something new and interesting for people to deal with.

**Comment by ArcaneMusic** [comment]
Thoughts:
Perhaps kudzu should be growth-limited when growing on too hot/cold tiles?
It's interested to have that much kudzu out and around the station, but there's definitely a point where it's excessive and this is that point.

**Comment by Barhandar** [comment]
>and is something new and interesting for people to deal with.

There isn't any people REMAINING to deal with it due to kudzu killing them and there's a giant open space at escape that means the kudzu will likely be planted and spread there, preventing escaping due to horde of aggressive plants.

**Comment by ArcaneMusic** [comment]
I don't think this fixes the issue, as the vines themselves can still expand onto the ice tiles in every direction, correct?
