### ISSUE TITLE
Chaplain's Cage sprites

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#53860]
## Reproduction: get chaplain scholar kit, equip the cage.

Not bald.

![](https://i.imgur.com/0lqJcCi.png)

Bald.

![](https://i.imgur.com/OipYg6Y.png)

Unplayable.

**Comment by necromanceranne** [comment]
I think last time this was looked at people wanted to keep the bald sprites.

**Comment by ATH1909** [comment]
My eyes! MY EYES!!

**Comment by ArcaneDefence** [comment]
`flags_inv = HIDEHAIR //bald` makes it hide hair and whether or not you have glasses. Can set that to null like ordinary caps do or something.
