### ISSUE TITLE
Scooter frame constructs into the wrong skateboard

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#53865]
## Testmerges:
- #52493 
- #53596 

## Reproduction:
1. Construct a scooter frame (from the stack crafting menu for metal rods, it requires 10)
2. Add metal to the scooter frame to get a skateboard
3. Try everything you can think of to add handlebars to the skateboard
4. Code dive
5. Realize that adding wheels to the scooter frame gets you a `/obj/vehicle/ridden/scooter/skateboard` and that you need a `/obj/vehicle/ridden/scooter/skateboard/improvised` to construct a scooter.

@Mickyan

**Comment by Mickyan** [comment]
oopsie
