### ISSUE TITLE
you can no longer place scooped up mobs (mob_holder objs) into bags, hats, or storages

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#53872]
## Round ID:

local, latest master but has happened on live rounds

## Reproduction:

Scoop up a rat, try to put in chef hat, does not enter hat
Scoop up Ian, try to stash in bag, does not enter bag
Collect bees, try to hide in duffle bag, does not enter duffle bag

**Comment by msgerbs** [comment]
I think this was broken by #53305 changing clothing without an icon_state to have the ABSTRACT flag. mob_holders are clothing (don't ask me why) and they have no icon_state on init.
