### ISSUE TITLE
Hotkeys do not override

### ISSUE THREAD

**Issue by Zytolg** [tgstation/tgstation#53883]
Issue reported from  Round ID: [146753](https://scrubby.melonmesa.com/round/146753) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1532

It's been a while since I've played last, so this might be an issue dating futher back. 
Basically, Hotkeys that shared some buttons but had modifiers (such as WASD and then stuff that would use CTRL+WASD) would overrite the funtion of the base hotkeys. In my instance, I have WASD for movement, and then assigned CTRL+WASD to the Face-Direction hotkeys. In the current version, this hotkey overrite does not happen, and leads to both hotkey actions happening at the same time. This behavior is pretty bad since it's very useful to have multiple functions accessable via specific key index and its aumentation via modification, and having it dramatically reduces the amount of avaliable hotkey assignments in a game where there are a meriad of probable hotkey funtions to be assigned.

**Comment by ATH1909** [comment]
https://github.com/tgstation/tgstation/issues/50216
https://github.com/tgstation/tgstation/pull/53771

**Comment by Rohesie** [comment]
What key do you have assigned to stop-movement? Is it Ctrl as well?
Because face-direction does not really stop movement, you'd need to combine both.

**Comment by Couls** [comment]
face direction hotkeys can probably be dropped if #53871 is merged

**Comment by nightred** [comment]
Key press check for the movement keys without modifiers, only after applying next move does it check for modifiers.

https://github.com/tgstation/tgstation/blob/3c713ef2fee3d9236109eea8385dd6db79796363/code/modules/keybindings/bindings_client.dm#L49-L63

**Comment by Couls** [comment]
Closing because there's now a lock movement hotkey that allows you to combine movement with the lock direction hotkey to turn around on master
