### ISSUE TITLE
Can't craft burgers or bbq ribs

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#53895]
## Testmerges:

#53596: 'Removes Admin Stickyban Exemption Workaround' by bobbahbrown at commit adbee092e4

Can't get these two to craft for some reason. Tried it with both normal steaks and synthmeat steaks. Probably happens with other recipes but I cba to test them all.

**Comment by TheVekter** [comment]
Might have been #53433 that caused this. I'll poke around a bit later and see if I can figure it out.

**Comment by ArcaneDefence** [comment]
I'm not sure what might've been the problem with normal steaks, but synthmeat steaks are `/meat/steak/synth` and the recipe calls for `/meat/steak/plain`, which I've addressed by making synthmeat a subtype of normal steaks in https://github.com/tgstation/tgstation/pull/53892

**Comment by brotherbeyondd** [comment]
the issues progressed then cos before #53484 still allowed for regular meat to be used in burgers
