### ISSUE TITLE
Mechs can't move diagonally when strafing (Bug?)

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#53898]
## Description:

Most mechs can't move diagonally at all, not just combat mechs like the durand, so I'm not sure if this is an intentional balance change or not. For example, the RIPLEY can only move north/south or east/west making it far slower then mining manually. Combat mechs can be out-manoeuvred so easily they're a joke against anybody with a toolbox.

**Comment by msgerbs** [comment]
Did they used to be able to do this?

**Comment by gwhit94** [comment]
I believe that is working as intended.

**Comment by msgerbs** [comment]
I believe this is not a bug, there's no code or anything I can find that would imply mechs are supposed to be able to move diagonally, strafe just lets you move without changing your facing direction.

**Comment by githubuser4141** [comment]
> Did they used to be able to do this?

All of them used to be able to strage diagonally, yes. I can see why it might be intended for combat mechs but I don't know why a odysseus/Ripley would need to be locked to such stiff movement.

**Comment by TiviPlus** [comment]
Previously odys and gygaxes has snowflake code to move diagonally

I moved this feature into a bool variable on mech level

Working as intended
