### ISSUE TITLE
Scaling Weirdness on Crafting Menu

### ISSUE THREAD

**Issue by Pinkufeck** [tgstation/tgstation#53917]
## Testmerges:
 #53329: 'testing smooth movement fixes' 
#53596: 'Removes Admin Stickyban Exemption Workaround' 

## Reproduction:
Have a screen that is 18.5 by 30 cm, open crafting menu. The top of the crafting menu will be out of the screen and you won't be able to move the menu without reconnection

**Comment by msgerbs** [comment]
More info please: What screen resolution, DPI (scaling) setting in Windows?

**Comment by Pinkufeck** [comment]
1366x768, and i don't know how to see what DPI i have, sorry for the late answer by the way

**Comment by msgerbs** [comment]
On Windows 10: Go to Display Settings and scroll down to Scale and Layout.

**Comment by Pinkufeck** [comment]
100 pourcent

**Comment by Uninteliger** [comment]
![Captura de Tela (152)](https://user-images.githubusercontent.com/76968545/103570075-ce6d4900-4e9e-11eb-9034-0d48676ba0ea.png)
I belive it is the same problem i have, i only know how to temporarily correct it by doing {CTRL ALT [any arrow key except UP]} which exposes the top of the window for me to adjust the placement.
Windows 8.1

**Comment by jlsnow301** [comment]
Sorry I did not format my PR correctly. This can be closed
