### ISSUE TITLE
False Wall Sub-Types Animation Hitching

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#53923]
## Reproduction:

1). Create false wall sub-type.
2). Open or close this false wall sub-type.
3). Watch the animation hitch.

This issue does not seem to apply to standard falsewalls, but only sub-types.
`/obj/structure/falsewall`

This occured on a custom map for an event, but was verified as occuring on a standard map afterwards. 

This could range from the animation playing out twice, a few times, or even just getting stuck permanently as shown:

![false_wall_broken](https://user-images.githubusercontent.com/46318638/94074490-5f745480-fdc7-11ea-8964-39afda047e71.gif)

**Comment by ArcaneMusic** [comment]
Well, I think I know why this is, only the default walls open/close animations are set not to loop.
This is going to suck to fix by hand.
