### ISSUE TITLE
Q stopped acting as drop item and started acting as equip to suit storage.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#53933]
## Testmerges:
- #52493 
- #53816 
- #53596 

## Reproduction:
1. Press Q
2. Notice that you aren't dropping the item in your hand
3. Notice that the feedback in chat is implying that the hotkey is trying to equip the item in your hand to the suit storage slot.
4. Reset keybinds (still doesn't work)
5. Reconnect (now it works)

I have no idea what happened to break it and I also have no idea why reconnecting fixed it.

**Comment by ArcaneDefence** [comment]
It sounds like your shift key input got stuck somehow.

**Comment by interestingusernam3** [comment]
unbindall

**Comment by timothymtorres** [comment]
I tried searching the issue tracker for similar issues and there is nothing.  Marking this as `Cleanup` and it will auto-close in 7 days.
