### ISSUE TITLE
Explosions that take place inside a mob's stomach don't work.

### ISSUE THREAD

**Issue by Winterous** [tgstation/tgstation#53931]
## Reproduction:  During testing a bunch of random shit I was experimenting with exploding gunpowder inside someone by setting them on fire, and noticed that it didn't work when the gunpowder was taken orally. Turns out, when the reagents are inside the bloodstream it works just fine, since the reagent container is the mob themself; but if it's in their stomach, the stomach is stored in nullspace, and so the explosion happens in nullspace, not where the mob is.

I expect the same would be true of any similar chemical reactions, like EMPs or tesla zaps.

**Comment by TemporalOroboros** [comment]
Organs get nullspaced. This is basically the same issue as the machine parts and C4 one except with mobcode.

**Comment by nightred** [comment]
I am fixing organs to be in the body, this has fixed explosions and synth meat effects

**Comment by Winterous** [comment]
Wait, synth meat effects? What was broken with that?

**Comment by nightred** [comment]
it was a comment based on a discord discussion. The effect does not happen anymore everything is fine. (you could make synth meat in your stomach and turn in to a meat volcano.)

**Comment by Winterous** [comment]
Now that is erp.
