### ISSUE TITLE
Decal Elements changed Decal Color Intensity

### ISSUE THREAD

**Issue by Zytolg** [tgstation/tgstation#53948]
Issue reported from  Round ID: [147016](https://scrubby.melonmesa.com/round/147016) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1532

This is related to #53922

Turf Decals are Looking way more Saturated than they previously were. I'm assuing the change messed with the decal alpha levels somehow and now things are appearing much more intensely than previously before. 
See below image for comparison
![Decals are way broken SS13](https://user-images.githubusercontent.com/33048583/94228469-46989b80-feba-11ea-8569-e76a15c49905.PNG)

**Comment by Couls** [comment]
@TiviPlus

**Comment by Jared-Fogle** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/53954
