### ISSUE TITLE
Heretic assassinate and hijack objective code has unforgivable typos

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#53961]
In some places assassinate is spelled `assasinate`, and there's a couple of `hjiack`. 

https://github.com/tgstation/tgstation/blob/710c022f904ff2f9ecc264c445259b208103fdab/code/modules/antagonists/eldritch_cult/eldritch_antag.dm#L92-L124

Don't know if this breaks anything, but I think I've seen the assassinate objective succeed even if the target is alive (a few weeks ago).

**Comment by Barhandar** [comment]
I've seen assassinate objective on a _traitor_ succeed despite the target (another traitor) registering as "survived" in the report yesterday.

**Comment by Angustmeta** [comment]
Sounds like it's not a problem exclusive to heretics.

**Comment by SpaceManiac** [comment]
Judging by the code you linked, the worst the typos can cause is a heretic getting two distinct hijack objectives.

Murder objectives at large not checking correctly would be a separate issue.

**Comment by itseasytosee** [comment]
A note that there are intended edge cases in which the target will be counted as dead even if they are not. examples are if the client is disconnected, or the mob is exiled.
