### ISSUE TITLE
Exosuit Fab and Cargo console interface issues.

### ISSUE THREAD

**Issue by Zaffinomlb** [tgstation/tgstation#53968]
## Reproduction:

Having issues with the interface not populating correctly or the interface working at all. In example shown the only items that populate are the categories and the materials. When a category is selected it will not generate a new or additional menu with items in said category. I was told to make this to help trouble shoot the issue.
![problems](https://user-images.githubusercontent.com/35023009/94295794-674b0a80-ff27-11ea-855b-0330ef24d9ea.png)

**Comment by stylemistake** [comment]
Issue could be due to lack of support for flex layout, so this is an Internet Explorer 8-10.

Can you verify that this is still an issue?

**Comment by Sealed101** [comment]
there has been at least one mechfab ui refactor, and this issue could have been linked to the user's setup. probably safe to close
