### ISSUE TITLE
Issue for management of 3/4ths wall project with walls completed and walls to be completed.

### ISSUE THREAD

**Issue by ArcaneMusic** [tgstation/tgstation#53971]
This is 100% not a proper use of an issue, but fuck it.
_Specifications:_ New walls, doors and windows need to be 32x48, 
These can be built using the following image template for sprites:
![image](https://user-images.githubusercontent.com/41715314/94305576-63c37d80-ff3f-11ea-8fbd-2a9b2a1b51de.png)
Alternatively:
![image](https://user-images.githubusercontent.com/41715314/94305626-7938a780-ff3f-11ea-89d2-84b8617b3f0f.png)
Or lastly:
![image](https://user-images.githubusercontent.com/41715314/94305662-88b7f080-ff3f-11ea-9992-0528b4299e98.png)

3/4ths wall sprites to be completed:
- [ ] **Material Based:**

- [x] iron wall
- [x] material wall (plus material filters)
- [x] sandstone
- [x] clockwork
- [x] snow
- [ ] abductor
- [ ] wood wall
- [ ] bananium
- [ ] diamond 
- [ ] gold
- [ ] plastinum (old shuttle)
- [ ] plastitanium
- [ ] plasma wall
- [ ] silver
- [ ] uranium

- [ ] **Misc Walls**

- [x] bloodcult
- [x] iced metal
- [x] hotel wall
- [x] reinforced wall
- [ ] hierophant
- [ ] ice rock
- [ ] mountain wall
- [ ] riveted
- [ ] rock
- [ ] rusty reinforced
- [ ] rusty wall
- [ ] shuttle
- [ ] survival pod
- [ ] regular wall
- [ ] boss (lavaland)
- [ ] resin wall
- [ ] paper frame

- [ ] **Doors** 

- [ ] airlocks 
- [ ] fire doors
- [ ] shutters

- [ ] **Windows**

- [ ] Regular
- [ ] Reinforced
- [ ] Plasma
- [ ] Plastitanium
- [ ] Resin membrane 

- [ ] **Wall-Mounted Objects:**

- [x] Button Frames/Controllers
- [x] Fire Axe Cabinet
- [x] Air Alarm
- [x] Fire Alarm
- [x] Request Board
- [x] Newcaster
- [ ] Bounty Boards
- [ ] Light Fixtures (Large/Small)
- [ ] Cameras? (We may not even want to replace these, they're kinda perfect.)

**Comment by Tlaltecuhtli** [comment]
first looks too plain
second doesnt make sense (yellow)
third looks like dungeon walls

**Comment by ArcaneMusic** [comment]
In favor of the current progress document we have for the 3/4ths walls document, this issue is no longer needed. 😄
