### ISSUE TITLE
Lattices remain on re-plated explosion/floorbot holes on Icebox

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#53978]
Issue reported from  Round ID: [147056](https://scrubby.melonmesa.com/round/147056) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
Reporting client version: 513.1532

**Comment by ArcaneMusic** [comment]
It's my understanding that this was fixed in #53590. Comment if it pops back up.
