### ISSUE TITLE
Mech Problems Refactor Edition Part 2: The Clarke

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#53979]
**The Clarke (and all working mechs) cannot move diagonally.**
Because the Clarke can't move diagonally, it's operating on some pretty serious tank controls, which makes it's speed really awkward for mining through the often diagonal tunnels of lavaland and the extremely bendy, narrow tunnels of icemoon.

**The Clarke can strafe.**
The clarke was never meant to strafe, it's a mech with tracks. This is probably because it's inhereting a ton of features from the parent type of mech and none of it fits what the original clarke was meant to be doing.

**The Clarke has no working lights**
I don't know why this was a thing, but upon creation, the clarke lacked headlights.

Alerting Doctor @TiviPlus.

**Comment by Barhandar** [comment]
Clarke looks like the whole upper platform can rotate, which means it would be able to move sideways relative to where it's facing, which means until someone somehow implements that it should be able to strafe.

Also, a mining mech that can't strafe is kinda nonsensical given the usual modus operandi for plasmacutter mining (move sideways while carving out a huge swathe in front).

**Comment by necromanceranne** [comment]
Well it can't strafe but it also can't move diagonally, which makes argument rather moot. Diagonal movement is far more of a serious issue than whether the mech can strafe or not. It deliberately didn't have strafe because it's diagonal movement allowed for much smoother turns anyway.
