### ISSUE TITLE
Icebox map doesn't have properly hacked Supply terminals

### ISSUE THREAD

**Issue by zombiemimic** [tgstation/tgstation#53995]
## Reproduction:
When one disassembles a supply terminal on the Icebox station and uses a multitool on the computer chip, none of the items resulting from hacked supply terminals appear.

**Comment by brotherbeyondd** [comment]
You sure you're not mixing it up with emagged console?

**Comment by zombiemimic** [comment]
No, none of the surplus crates, contraband, biker kits, etc. are there.

**Comment by dragomagol** [comment]
Appears to have been fixed
