### ISSUE TITLE
PENLITE defibrillator mounts don't correctly update defib state with their recharge

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#53990]
Issue reported from  Round ID: [147098](https://scrubby.melonmesa.com/round/147098) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
Reporting client version: 513.1532

That is, you have to pop a defib that was inserted uncharged out and stick it back in (or toggle clamps, IIRC) for it to register as charged, otherwise it tells you it's out of juice (and shows "no power" sprite) even if the actual item is fully charged.

**Comment by Sealed101** [comment]
- fixed in #59366 altough i have a feeling it was still an issue after that then fixed by some other PR but i might be wrong. it's no longer the case either way
