### ISSUE TITLE
Every arcade machine on the map is nonfunctional.

### ISSUE THREAD

**Issue by Greataims** [tgstation/tgstation#54008]
Issue reported from  Round ID: [147171](https://scrubby.melonmesa.com/round/147171) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1501

Every arcade machine on every map is showing as "random arcade" and show no response when clicked on, until you unscrew and rescrew the machine itself.
![issue](https://user-images.githubusercontent.com/44904571/94367408-8c1cba80-00ac-11eb-9099-eff9460af3ce.png)

**Comment by Timberpoes** [comment]
Fixed by #53958
