### ISSUE TITLE
Some volcanic floor from colossus crystal is missing a sprite

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#54009]
Issue reported from  Round ID: [147176](https://scrubby.melonmesa.com/round/147176) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
Reporting client version: 513.1532

Is the black/purple checkerboard.

**Comment by ArcaneMusic** [comment]
I am relatively self assured this has been fixed as of the past few months with all the missing/fixed turfs. If I'm wrong, feel free to comment and I'll re-open.
