### ISSUE TITLE
Nuclear Authentication Disks disappear when you go down a flight of stairs on Ice Box

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#54023]
## Reproduction:
Hold nuke disk
Walk downstairs (like into Botany or Cargo) on Ice Box Station
Nuke Disk go bye bye to RNG teleportation
This is so sad

Is there a way this can be fixed, as losing your nuke disk every time you check out Xenobio or whatever's new cool shit, it's a real hassle to have lost your nuke disk when you haven't even "left" the station. Or, is this a "feature"?

**Comment by dragomagol** [comment]
Fixed by #54779
