### ISSUE TITLE
Removing KA upgrades as miner borg does not remove them from the upgrades list (likely oversight)

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#54038]
## Reproduction:
Go mining module, get upgrades for your KA, then prybar them out and see that the list does not delete previously-installed upgrades. This is probably an oversight and isn't game-breaking. 
![image](https://user-images.githubusercontent.com/62538745/94435069-491c1f00-0160-11eb-8c50-24b9b66e4de1.png)

**Comment by Barhandar** [comment]
More accurate title: removing removable borg upgrades such as KA ones doesn't remove them from the list

At a guess, the coder who did this thought no upgrade is removable without wiping the borg module entirely.
