### ISSUE TITLE
Nightmares have blocked jumpsuit slot and no integrated jumpsuit a-la golems, but not blocked jumpsuit-requiring slots

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#54039]
Means they have visibly available pockets, ID, and belt but can't put anything there.

**Comment by msgerbs** [comment]
This is a bug though, it's a bug that the status of the slots isn't updating.

**Comment by Mooshimi** [comment]
Isn't it intentional, otherwise species like all golems and such wouldn't be able to hold anything but a packpack, because belt also requires suit

**Comment by msgerbs** [comment]
Wow this is old, but the description to me seems to say that they visibly have the slots but can't put anything in them.

**Comment by Mooshimi** [comment]
> Wow this is old, but the description to me seems to say that they visibly have the slots but can't put anything in them.

true I misread, will see if the pockets thing is still fubbed
