### ISSUE TITLE
Data Disks impossible to fabricate?

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#54046]
I'm pretty sure Data Disks (to be used with computer-consoles and borgs now) cannot be fabricated, even when researched. I've checked all protolathes and when it's researched you cannot craft data disks. You can still buy the small ones at the computer vendors, however

**Comment by ZeroMODE0** [comment]
To confirm: I can print the miniprinter and others, but not the datadisks.

**Comment by Fikou** [comment]
they are in imprinter

**Comment by ZeroMODE0** [comment]
Ohh. Everybody I asked about it was certain they were made at a protolathe- Checking it on the research console shows it's crafted at a protolathe.
