### ISSUE TITLE
tgui, css for plain html fails to load via CDN.

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#54047]
## Testmerges: 
#53596: 'Removes Admin Stickyban Exemption Workaround' by bobbahbrown at commit adbee092e4
#53994: 'AIs can now select portraits as their display' by tralezab at commit 9ecdddfcaf

## Reproduction:
Alright, I created a new wine prefix for SS13. Initially plain html and tgui interfaces worked just fine, I reconnected multiple times.
The next day tgui interfaces are just blank white screens. Plain html interfaces seem to work fine but have a white background, see the screenshot below. 
I initially suspected that this was on my end and perhaps restarting the pager broke things. I've tried various ways of clearing the cache with no success. Curiously enough I cannot reproduce the issue on a rather old commit  on localhost. I asked an admin to disable CDN which fixed everything again.
It's possible this coincides with testmerging of the AI portrait PR, things are broken for me after(inclusive) 2020-09-27 09:53:42 Server Time.  See Scrubby for details on rounds I connected to: https://scrubby.melonmesa.com/ckey/booktower

**Edit:** Sybil has nothing testmerged right now but does not work. Campbell, which is on the same commit as Sybil, DOES however work. Very odd.

![Screenshot_20200927_143414](https://user-images.githubusercontent.com/35031555/94471340-47d30c80-01c9-11eb-8aa8-045752919838.png)

**Comment by Cyprex** [comment]
I haven't been able to find tgui logs in parsed logs, if they're in raw-logs this link should have them: https://tgstation13.org/raw-logs/terry/data/logs/2020/09/27/round-147167

**Comment by optimumtact** [comment]
also @MrStonedOne

**Comment by Cyprex** [comment]
Toggling CDN fixes things immediately without reconnecting.

**Comment by Cyprex** [comment]
I'd like to add that my testing on localhost was on a very old commit, that does however have stylemistake et al. tgui implementation

**Comment by Cyprex** [comment]
BYOND cache folder contains ~20 files prior to disabling CDN. A hundred or so, including images, after disabling it and closing+reopening html+tgui interfaces. Details: https://p.smx.lt/ygJMOzf

**Comment by optimumtact** [comment]
teh folder stuff is expected/irrelevant fyi, they're not cached locally because tehy come from the CDN and live in IE's own cache.

**Comment by optimumtact** [comment]
@MrStonedOne your cdn sux

**Comment by stylemistake** [comment]
Closing to consolidate the issue in #53997.
