### ISSUE TITLE
decals dont render at all on shuttles

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#54053]
## Reproduction:

be on shuttle with decals
theres no decals

**Comment by Fikou** [comment]
![image](https://user-images.githubusercontent.com/23585223/94498303-19215a00-01fa-11eb-85f2-0aba9b80c963.png)
![image](https://user-images.githubusercontent.com/23585223/94498335-29393980-01fa-11eb-9f73-b64fc432887c.png)

**Comment by Couls** [comment]
@TiviPlus

**Comment by Dennok** [comment]
Shuttle load_roundstart() issue
teplate placed shuttle has decals

**Comment by Fikou** [comment]
yooo i fixed this
