### ISSUE TITLE
Is is impossible to construct a south-edge railing if there's a railing on any other side of the turf.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#54067]
## Reproduction:
1. Construct a railing on the north, west, or east edges of a turf.
2. Attempt to construct a railing on the south edge of the turf.
3. Get blocked by the other railings.

This is inconsistent with the other directions only blocking construction if a railing exists on that edge, rather than any on the turf.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/247d70a4d8319cc22532d15adc9e1292a732a7a2/code/game/objects/items/stacks/rods.dm#L6

https://github.com/tgstation/tgstation/blob/48f01accc17f2c1aed44857cade46779a661cd20/code/__HELPERS/turfs.dm#L365-L384

**Comment by Sealed101** [comment]
- #74572 was introduced recently, and building railings on one tile gets blocked by each other completely now.

i think it's kinda weird that you can still just unwrench and wrench a railing down in a tile with a railing with no issue, but constructing two on one tile directly is prohibited. this should be as simple as adding `check_density = FALSE` in this line
https://github.com/tgstation/tgstation/blob/b832e2f47765ea321457221cc4e2a8ea64137555/code/game/objects/items/stacks/rods.dm#L6
as well as adding an `IGNORE_DENSITY` flag here
https://github.com/tgstation/tgstation/blob/b832e2f47765ea321457221cc4e2a8ea64137555/code/game/objects/structures/railings.dm#L7

**Comment by Sadboysuss** [comment]
This is still an issue

**Comment by Sealed101** [comment]
fixed by #86651

**Comment by Sadboysuss** [comment]
4 year old bug fixed
