### ISSUE TITLE
Doubled railings can't be climbed over.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#54066]
## Reproduction:
1. Acquire metal rods.
2. Construct two sets of railings back-to-back.
3. Attempt to climb over either of the railings.
4. Get blocked by the other railing.

**Comment by timothymtorres** [comment]
You shouldn't even be able to build double railings on the same tile.  Were both railings on the same dir?

**Comment by timothymtorres** [comment]
If that's the case then this really isn't a bug.  Should you be able to jump over the 2nd railing if a directional window was blocking the way?  You are wanting a way for someone to leap over two adjacent railings and this doesn't make sense.  Just deconstruct one of them or if this is a mapping issue that needs to be remapped... but for now I'm marking this as `Not a Bug`
