### ISSUE TITLE
Repeatedly using the slime processor puts the slimes underneath the floor tile

### ISSUE THREAD

**Issue by Jared-Fogle** [tgstation/tgstation#54061]
## Round ID: [147277](https://scrubby.melonmesa.com/round/147277)

> Dakota Stafford (as Alijah Endsley) meows, "Put one in, then triggered, then put another one in, and triggered"
    Dakota Stafford (as Alijah Endsley) meows, "In rapid succesion"
    Mothblocks flutters, "Heh"
    Dakota Stafford (as Alijah Endsley) meows, "I think just the process of triggering another grind while one is in there."

![dreamseeker_2020-09-28T18-38-28](https://user-images.githubusercontent.com/35135081/94503151-a6dd5500-01ba-11eb-882d-74847cf7d81f.png)

As you can see, the slime extracts are there but are not visible. You can pick them up normally through the right click menu. Crowbarring it up showed the extracts underneath.

**Comment by Timberpoes** [comment]
It's difficult to see but the slime extracts are actually being dropped under the reinforced window for some reason.

![image](https://user-images.githubusercontent.com/24975989/94562060-c3ca6480-025c-11eb-99b4-219b6ed8c1ea.png)

**Comment by nightred** [comment]
The next xeno PR #54024 for icebox moves the grinders, and no window shares the same tile any more.
![image](https://user-images.githubusercontent.com/6491940/94598377-79dd8080-0254-11eb-8f34-4bb0c606a270.png)

**Comment by Jared-Fogle** [comment]
lmao
