### ISSUE TITLE
you can make poly disappear by putting him in a suit storage unit

### ISSUE THREAD

**Issue by Timonkeyn** [tgstation/tgstation#54074]
Reporting client version: 513.1532

title, only tested on poly

**Comment by ATH1909** [comment]
what happens if you do this with a sapient poly?

**Comment by Timonkeyn** [comment]
havent tested that yet

**Comment by Timonkeyn** [comment]
disappear as in he can still talk, hes in the suit storage unit but doesnt come out when you open it again

**Comment by Barhandar** [comment]
Does he pop out if you depower the room?

**Comment by Timberpoes** [comment]
This should be fixed by https://github.com/tgstation/tgstation/pull/54072

Suit storage units have an unimplemented proc for dumping out their contents.
