### ISSUE TITLE
Items are not properly moved across z-levels when using the elevator

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#54089]
Issue reported from  Round ID: [147342](https://scrubby.melonmesa.com/round/147342) (/tg/Station Basil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1526

![2020-09-29 19_37_06-_tg_Station Basil  ENGLISH   US-WEST   100% LAG FREE _ Nettle Hive XCVII](https://user-images.githubusercontent.com/36066032/94633646-38b49300-028b-11eb-8d62-5afcf5c41399.png)

This air alarm is visible but otherwise unable to be interacted with.

**Comment by Dennok** [comment]
You sure that it not on bottom level?
