### ISSUE TITLE
Monkey cubes are too large for biobags

### ISSUE THREAD

**Issue by Owegno** [tgstation/tgstation#54094]
Spotted on round ID 147356

This is due to the new food rework as it gives the base food item a w_class of 3 which monkey cubes inherit. Prior to this they had a w_class of 1.

**Comment by Qustinnus** [comment]
will fix

**Comment by msgerbs** [comment]
Why did the food rework change the base w_class of food?

**Comment by brotherbeyondd** [comment]
That group of PRs feckered with everything. Very sad!

**Comment by nightred** [comment]
It looks like PR #54095 will fix this issue.

**Comment by Qustinnus** [comment]
@msgerbs food is literaly 10 typepaths deep code, it was moved to be like 3 typepaths deep so now all the random overrides that those types had arent set by default
