### ISSUE TITLE
Snowwalls cannot be destroyed without miner tools, rendering icebox explosion-holes inescapable

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#54106]
Issue reported from  Round ID: [147387](https://scrubby.melonmesa.com/round/147387) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
Reporting client version: 513.1532

Solution: don't fucking make open space with explosions on station Z

**Comment by Mooshimi** [comment]
Snow walls can actually be dug into with just your hands now, though it takes a long time.
