### ISSUE TITLE
Microwaves duplicate meat

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#54107]
## Round ID:
Reproduced on local

## Reproduction:
![image](https://user-images.githubusercontent.com/51932756/94724184-1f592880-0317-11eb-91b7-670573b9c53c.png)

put meat in microwave

turn microwave on

two meat per meat

wow

**Comment by BigGrease** [comment]
yes lol i have noticed this too they duplicate everything you can microwave and sometimes it also makes the microwave dirty fnr

**Comment by ArcaneDefence** [comment]
Failed to reproduce on local again, so someone probably fixed it without referencing this report.
