### ISSUE TITLE
Wall smoothing is busted

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#54109]
Issue reported from  Round ID: [147390](https://scrubby.melonmesa.com/round/147390) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
Reporting client version: 513.1532

![box](https://user-images.githubusercontent.com/2338212/94727635-b221b380-0367-11eb-9002-73e0abbeb1d0.PNG)
![hiero](https://user-images.githubusercontent.com/2338212/94747057-c1642980-0386-11eb-90ea-84d54e1d4732.PNG)

**Comment by Barhandar** [comment]
PR #54129 did not correct this issue as evidenced by #54204 that is created long enough after the merge for the servers to have gotten updated.

**Comment by Rohesie** [comment]
The first issue was fixed by that PR.
The second issue was fixed by #54231
