### ISSUE TITLE
Microwave Problems

### ISSUE THREAD

**Issue by BigGrease** [tgstation/tgstation#54114]
Issue reported from  Round ID: [147397](https://scrubby.melonmesa.com/round/147397) (/tg/Station Basil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1532

More kitchen/cook related bugs. Unable to microwave eggs. Usually, microwaving an egg produces "boiled eggs". In this round, I experienced eggs, even when microwaved alone, to turn into burned mess, and dirty the microwave. This is abnormal. Please amend this issue.

**Comment by BigGrease** [comment]
Oof, nevermind, it seems like microwave code is totally beaned, as even when i tried to cook goliath meat, it sometimes even still acted like this was something that was not supposed to be cooked, even when it did occasionally cook it properly. Other times, it splattered and produced burned mess. Confusing.

**Comment by BigGrease** [comment]
hahahahaha microwaves dupe meat bro 

bro

what

**Comment by BigGrease** [comment]
Just to be clear: I have realized that microwaving microwavable foods dupes them, by producing a cooked product while the raw component REMAINS. Also, microwaving sometimes produces burnt mess and dirties the microwave while cooking valid components for cooking WITHOUT! WITH! OUT! actually decreasing the number of items.

**Comment by BigGrease** [comment]
also it produced the boiled eggs (12) earlier as well but it kept the raw eggs (12) while sometimes dirtying the microwave for an unknown reason. no other items besides eggs or meat in the machine. this is very confusing overall

**Comment by BigGrease** [comment]
Sorry for all the comments, but I wanted to understand the issue to help you understand the issue, and that is why I have provided so much information. I think this sums up the issue now, so Im gonna leave it at this. Good luck

**Comment by BigGrease** [comment]
yes but you cant cook a steak with grill lines on it in a microwave irl. it'd probably look brown and sad and taste awful, but the microwave seems to be able to bake cakes and pizzas and bread and cook spaghetti in seconds so its really more like an instant toaster oven maybe i dunno

**Comment by nightred** [comment]
Looks like the food rework has broken the microwave.
