### ISSUE TITLE
Unable to hack Supply Console boards

### ISSUE THREAD

**Issue by TeddyTheBearBruh** [tgstation/tgstation#54111]
Issue reported from  Round ID: [147391](https://scrubby.melonmesa.com/round/147391) (/tg/Station Basil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1528

Followed instructions as listed on the wiki and as I have done before, set the boards to broad. However, I couldn't get the contraband crates to show up in the menu. Tried on both the shuttle and QM office consoles.

Thanks!

**Comment by Zenitheevee** [comment]
After doing a lot of digging (And by that, i mean opening fork, Reverting PR  after PR like i'm trying to find the fucking skyrim mod that broke the game), I've discovered there happens to be an issue within #52970 

I cannot identify exactly where in the PR that it goes wrong, But i theorize it might have to do something with the machine itself over-looking the variables of the circuitboard, Reading that it says "Supply console" And going with that.
