### ISSUE TITLE
trays cannot carry normal items 

### ISSUE THREAD

**Issue by BigGrease** [tgstation/tgstation#54113]
Issue reported from  Round ID: [147397](https://scrubby.melonmesa.com/round/147397) (/tg/Station Basil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1532

Trays cannot carry normal items anymore, when they could before. Things such as steaks, plates of food, or even EGGS. 1 egg is TOO BIG for a TRAY, that is a bulky item, to handle? Absurdity. I figured this must be another bug with trays.

**Comment by PKPenguin321** [comment]
Likely intentional

**Comment by Owai-Seek** [comment]
Probably linked to this issue. https://github.com/tgstation/tgstation/issues/54134
