### ISSUE TITLE
Organs Can Be Munched On Forever

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#54117]
## Reproduction:

I'm not invested enough at the moment to take a guess at what's causing this issue but:

1). Get an organ.
2). Eat it.
3). Eat it more.
4). Just keep going.
5). It never ends.
![MUNCH](https://user-images.githubusercontent.com/46318638/94757932-c36bbf80-0369-11eb-83f2-e2254183bef6.png)

**Comment by Misdoubtful** [comment]
Adding onto this with a runtime:

![MUNCHY MUNCH](https://user-images.githubusercontent.com/46318638/94759088-ff545400-036c-11eb-8945-4cb58e848896.png)

**Comment by dragomagol** [comment]
Appears to have been fixed.
