### ISSUE TITLE
Metal false walls instantly disappear when clicked, and cannot be closed unless you alt click

### ISSUE THREAD

**Issue by Jared-Fogle** [tgstation/tgstation#54110]
## Reproduction
1. Build a false wall.
2. Open it.

![2020-09-30T12-40-02](https://user-images.githubusercontent.com/35135081/94732230-d5724180-031a-11eb-89fc-18dba8da8cf5.gif)

This only seems to happen with metal.

![2020-09-30T12-42-57](https://user-images.githubusercontent.com/35135081/94732296-ea4ed500-031a-11eb-9604-1952fe94acee.gif)

**Comment by PKPenguin321** [comment]
Bad icon?

**Comment by PKPenguin321** [comment]
Yep, seems metal false wall icons were accidentally removed in https://github.com/tgstation/tgstation/commit/e461d7b777fc41963e9da8fa55065aa0d64142d7
