### ISSUE TITLE
Disposal pipes cannot be deconstructed or constructed

### ISSUE THREAD

**Issue by msgerbs** [tgstation/tgstation#54121]
## Testmerges:
#53596
#53994

## Reproduction:

1. Pry up a floor tile
2. Unweld a disposal pipe
3. Disposal pipe vanishes before you can unwrench it
4. Try to place another pipe on the same tile, get told told there's not enough room (because the old pipe was not unwrenched)
5. Try to place a new disposal pipe elsewhere, get told that it needs a trunk underneath it in order to work

![image](https://user-images.githubusercontent.com/1313921/94775460-7564b500-0385-11eb-84cf-9207db0e79bc.png)

I confirmed this locally and on a live server, disposal pipes are totally broken right now. There are no runtimes from this process. After unwelding a disposal pipe I get an invisible disposal pipe fitting that I can drag around but can't do anything else with. All types of disposal pipe do this. Same with saying they need a trunk underneath, every single type does that.

**Comment by msgerbs** [comment]
This seems to have been broken by #54013

**Comment by Ghommie** [comment]
Fixed by #54123. Someone close this thank you.

**Comment by msgerbs** [comment]
Thanks @Ghommie
