### ISSUE TITLE
The NT FRK doesn't do anything, meaning you can't revive AIs.

### ISSUE THREAD

**Issue by Hiynastrike** [tgstation/tgstation#54122]
Issue reported from  Round ID: [147423](https://scrubby.melonmesa.com/round/147423) (/tg/Station Basil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1528

https://i.imgur.com/mipwry9.png image of the issue in action

So basically NT FRK opens to a blank "screen" where you can only shut off the computer. You can unload an AI onto an intellicard, you can put it in the computer, you just can't restore it.

**Comment by zxaber** [comment]
I tested the app, and it seems to be working under normal circumstances.

However, the logs show that this line was runtiming in the round you referenced;
`data["laws"] = AI.laws.get_law_list(include_zeroth = TRUE, render_html = FALSE)`

`runtime error: Cannot execute null.get law list()`

Somehow the AI didn't have their laws datum. I'm not sure what would cause the datum to go missing.
