### ISSUE TITLE
Oversight: Borg tablets can get Lifeline

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#54138]
## Reproduction:
Have someone put a disk into your borg that has lifeline, poof, borg now has crew pinpointer without having crew pinpointer upgrades. This is... Probably unintentional/unwanted as the crew pinpointer is a mediborg upgrade and costs research/materials.

**Comment by ATH1909** [comment]
![image](https://user-images.githubusercontent.com/42606352/94891955-149eb080-0449-11eb-8b0f-594b44ec4e90.png)

**Comment by ATH1909** [comment]
mediborgs still get an advantage out of having the upgrade, as they can have their suit sensor monitoring stuff and another tablet program up at the same time

**Comment by zxaber** [comment]
The pinpointer upgrade is something a Roboticist can aquire and install, while getting LifeLine requires medical access. That's why I felt comfortable with allowing the app for borgs.
