### ISSUE TITLE
Plastitanium wall corner icon issue

### ISSUE THREAD

**Issue by Dennok** [tgstation/tgstation#54136]
BYOND Version: 513.1532
Server revision compiled on: 2020-10-01
Master commit: 456723c4dfc2d72a19898089257d3c0bb4c78364
Local commit: f312088079287dac692439707f478c4c5668632f

## Reproduction:

See on plastitanium wall with `icon_state = "plastitanium_wall-38"` and see this

![image](https://user-images.githubusercontent.com/7734424/94846670-2f156180-042a-11eb-9851-af206c3b620b.png)

**Comment by nightred** [comment]
@Rohesie would PR #54129 also fix this issue?

**Comment by Rohesie** [comment]
Yes

**Comment by Dennok** [comment]
@Rohesie i check it in #54129 with `icon_state = "plastitanium_wall-38"` and see space
