### ISSUE TITLE
you cant "accidentally" eat titanium or any material sheet

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#54144]
put titanium sheet in bread or cheese 
eat
nothing special happens

https://github.com/tgstation/tgstation/blob/0985032c4853428db7819adb071118b636fc607f/code/datums/materials/basemats.dm#L28  and similar dont trigger

**Comment by MrMelbert** [comment]
![image](https://user-images.githubusercontent.com/51863163/94959830-772e9580-04b7-11eb-89ec-b072a8423d77.png)
could not reproduce on the latest master, titanium did damage to the eater when it was bitten as intended

**Comment by Dorsisdwarf** [comment]
Could not reproduce IG
