### ISSUE TITLE
Vending machine UI error

### ISSUE THREAD

**Issue by Wolter-Lin** [tgstation/tgstation#54140]
Script error.
   at https://tgstation13.download/byond/assets/86/asset.861078f4f38eaaa01cdca1e8b9bf1bcd.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)

A fatal exception has occurred at 002B:C562F1B7 in TGUI.

**Comment by stylemistake** [comment]
Closing in favor of #53997 (duplicate).
