### ISSUE TITLE
Admin tabs disappears at round end

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#54148]
## Round ID:
[147500](https://scrubby.melonmesa.com/round/147500)

## Testmerges:
#53965: 'Tanks have tiers' by Ghilker at commit 8328b2ad36
#53596: 'Removes Admin Stickyban Exemption Workaround' by bobbahbrown at commit adbee092e4

## Reproduction:
End round, watch admin tabs disappear. Reload admins to make them reappear.
I think there are also some issues with tabs showing up on roundstart or connect, I have seen the ticket tab missing in the past.

**Comment by Couls** [comment]
fixed by #54211
