### ISSUE TITLE
Infinite floor panel 

### ISSUE THREAD

**Issue by Mia-Polson** [tgstation/tgstation#54159]
Issue reported from  Round ID: [147548](https://scrubby.melonmesa.com/round/147548) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1532

Delta station

Two panels down directly from the bottom robotics maint door is a floor panel that could be lifted infinite amount of times.

**Comment by TemporalOroboros** [comment]
It's baaaaaaaaaaack. Probably. I hope it's not the same glitch because I thought we killed this one.
- #47812 
- #37421 
- #49153 
- #49119

**Comment by Mia-Polson** [comment]
yes I believe floorbots were made that round.
