### ISSUE TITLE
Lost Ability to Move as Xenomorph From Reading Paper

### ISSUE THREAD

**Issue by IndieanaJones** [tgstation/tgstation#54169]
## Round ID:

[147589](https://scrubby.melonmesa.com/round/147589)

## Testmerges:

#53492: '[READY] Space Ninja Rework' by IndieanaJones at commit a22e4d86b2
#53596: 'Removes Admin Stickyban Exemption Workaround' by bobbahbrown at commit adbee092e4
#52493: 'LINDA Atmos: Reforged and associated fixes/changes' by LemonInTheDark at commit 420adb8314

## Reproduction:

1. Spawn in as xenobio xenomorph
2. Evolve to Alien Drone
3. Try to read paper
4. Lose control of all ability to move

I'm not sure if trying to read the paper did it, but it happened shortly afterwards.  I also tried resetting my controls, but no dice.

**Comment by ATH1909** [comment]
I ~~can~~ can't go anywhere
Friends to know
And ways to grow
A reading rainbow...

**Comment by Fikou** [comment]
The paper is arcane equipment, it broke the dumb xeno's brain and motor functions.
