### ISSUE TITLE
You can make a working supermatter setup out of things that radiate radiation such as uranium blocks.

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#54172]
This is cancer. This is cancer.
![image](https://user-images.githubusercontent.com/62538745/95007702-4d20c480-05d8-11eb-9454-edc4fe951e07.png)
This setup, unupgraded, makes 250kw or so. God save us all, this is by far my favorite oversight.

![image](https://user-images.githubusercontent.com/62538745/95007808-8443a580-05d9-11eb-979f-137419abd9a3.png)
(Missing a block, but:) This setup has potential to make 520kW.

![image](https://user-images.githubusercontent.com/62538745/95008074-1351bd00-05dc-11eb-9874-826fd80edf9c.png)
This setup makes roughly 560kW... And 580kW when the conveyors are on and turning. What?

**Comment by Dennok** [comment]
Power of art
![image](https://user-images.githubusercontent.com/7734424/95010390-ae28b680-0631-11eb-8968-05320123b15b.png)

**Comment by optimumtact** [comment]
There's a reason why I wish to move away from the radiation collectors and instead power things via the turbine fed from the SM

**Comment by Winterous** [comment]
Not a bug, basically an RTG.

**Comment by Barhandar** [comment]
Not a problem with uranium blocks, problem with radiation collectors being refluffed as collecting conventional (ionizing) radiation instead of Hawking radiation.

**Comment by LemonInTheDark** [comment]
resolved for now by #54178
