### ISSUE TITLE
Many action buttons don't work when buckled (turning on internals)

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#54199]
### Round ID:
[147690](https://scrubby.melonmesa.com/round/147690) Terry. 

### Reproduction:

1. Buckle to anything (janicart, chair etc). 
2. Try to turn on internals, adjust breathing mask or adjust welding goggles. 

**Result:** Most action buttons become red when buckled. Nothing happens when clicking them. The mind reader mutation still worked when buckled and did not turn red. 

**Expected result:** Being buckled should not prevent using common action buttons.

**Comment by Tlaltecuhtli** [comment]
https://github.com/tgstation/tgstation/blob/3cc7733f34c3fe7cb97ab41437fee4a494119127/code/datums/action.dm#L95-L110


this is the default check that all action bottons use

**Comment by Dennok** [comment]
https://github.com/tgstation/tgstation/blob/3cc7733f34c3fe7cb97ab41437fee4a494119127/code/datums/action.dm#L147-L152
Buckling give TRAIT_IMMOBILIZED trait.
https://github.com/tgstation/tgstation/blob/0bfb94746bf2b3585caa5b45ee62f061e9da8bb9/code/modules/mob/living/living.dm#L1651-L1674
