### ISSUE TITLE
You can give carbons a borgmodule-status bucket

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#54205]
## Reproduction:
As janitor borg, place your bucket on your head. Get reset, have someone pick the bucket up- It is now undroppable because it's a borgmodule bucket.

**Comment by ATH1909** [comment]
IMO, the part of this that should be fixed is the bucket still having nodrop when removed from the janiborg (and the janiborg not regenerating its bucket without a module reset if it does this, IIRC), not the ability of janiborgs to crown themselves. Heck, we could probably even port over the L'Eglise, c'est Moi! achievement from CKII for just such an achievement.

**Comment by zxaber** [comment]
The part that should be fixed is nodrop being ignored when placing an item on a borg.

Letting borgs give themselves hats is an argument for its own PR.

**Comment by ZeroMODE0** [comment]
@zxaber ON THIS NOTE, the roboticist could not place the bucket back on my borg head.
