### ISSUE TITLE
Tile smoothing is bjork, not updating when things get broken, mining only?

### ISSUE THREAD

**Issue by Winterous** [tgstation/tgstation#54204]
![(null)scrnshot1](https://user-images.githubusercontent.com/38158801/95145476-06dd8800-07c7-11eb-9066-27178303f776.png)
@Rohesie

**Comment by Dennok** [comment]
I see 2 problems, 
1. Hierofant walls smoothing with mineral walls.

2. Mineral wall turfs dont get updated on mining.

3. Gas visuals dont get update.

**Comment by Barhandar** [comment]
Gas visual updating lags behind mining, and has been lagging before the smoothing issue. The smoothing issue appeared slightly under a week ago while miasma taking its time to show up on mined tiles was around for the whole month.

**Comment by Dennok** [comment]
Omg. I find why Mineral wall turfs dont get updated on mining.
