### ISSUE TITLE
Meta cold rooms set off atmos alarms

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#54206]
## Testmerges:
- #53596 
- #53492 
- #54174 

## Reproduction:
1. Start on meta
2. Wait
3. Check a station alert console
4. Notice atmos alerts for the kitchen and medical cold rooms.

**Comment by msgerbs** [comment]
I swear to god this was fixed at least once before. Ugh.

**Comment by msgerbs** [comment]
For some godforsaken reason the kitchen cold room variant of the air alarm is set to -60C as the _high temp caution threshold_. Also the medical freezer has a normal air alarm. It looks the kitchen cold room was meant to start at -80C, but then @nightred changed it to be -10C again. Not sure why. I'll ask him and then either change the air alarm or change the tile type.

**Comment by msgerbs** [comment]
Also apparently Meta is the only map with freezers that are actually cold??
