### ISSUE TITLE
Borg Cameras do not store/print photos

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#54218]
## Reproduction:
Take picture, use robotact to try and view/print this picture, you cannot
you just cannot
![image](https://user-images.githubusercontent.com/62538745/95248896-8d04c900-07dd-11eb-8d13-56f02035753d.png)
This never changes from 0.

**Comment by Dorsisdwarf** [comment]
this may be linked to that feature where AIs are supposed to get a copy of their cyborgs photographs

**Comment by ZeroMODE0** [comment]
I'm pretty sure AI, as they used to, are able to view the gallery using the gallery button. Being lawsynced uploads photos to all silicon on that lawsync/master ai
