### ISSUE TITLE
HARS is incurable when dead.

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#54219]
## Reproduction:
Get HARS, die.
Trying to defib someone with HARS and dead is impossible, as their digestive system does not process mutadone and you cannot nullify it in the genetics tube. However- You can scramble their DNA completely and they'll be revivable because HARS gets nullified by doing this. I've never seen anyone be reviveable with HARS in the past

**Comment by dragomagol** [comment]
I wasn't able to cure HARS while the patient was dead, but reviving them didn't seem to be an issue. You can even give CPR to someone suffering from it.

**Comment by Sealed101** [comment]
curing hars is impossible without an active digestive system. that said, you can still revive dead hars patients when healed, the brain is in the body.
