### ISSUE TITLE
Paraplegics unable to interact with certain things (setting internals for example)

### ISSUE THREAD

**Issue by Jolly-66** [tgstation/tgstation#54238]
## Round ID: 
[147844](https://scrubby.melonmesa.com/round/147844)

## Reproduction:
Choose paraplegic and try to interact with certain things on your person.
Adjusting welder mask/goggles, setting internals, anything that can be toggled essentially.
The only thing that seems to work is enabling/disabling the PDA light.
The buttons are also red too.

**Comment by msgerbs** [comment]
Similar to #54199, probably the same cause.
