### ISSUE TITLE
asteroid shuttle only loaded half of it

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#54232]
![shuttle bug 4](https://user-images.githubusercontent.com/33834933/95348111-fc51ea00-08bd-11eb-8d10-c9821cfe41d7.PNG)
147829

**Comment by Tlaltecuhtli** [comment]
![shuttle bug 5](https://user-images.githubusercontent.com/33834933/95348898-ca8d5300-08be-11eb-8a27-d2a2d5bc1236.PNG)
this happened once it docket in centcomm

**Comment by Dennok** [comment]
Report please if this issue happens again.
