### ISSUE TITLE
Kilo arrivals shuttle causes OOM crash after landing about 16 or more times

### ISSUE THREAD

**Issue by Kylerace** [tgstation/tgstation#54240]
this is the reason why kilo always crashed. after about 15 or so landings the kilo arrivals shuttle borks the game, Shuttle SS reportedly exceeds 300% on the last landing before crash. Luckily there are no shuttles in the game that act like kilo's arrival shuttle here. 
![Screenshot_371](https://user-images.githubusercontent.com/15794172/95413998-ad1db080-08e1-11eb-9901-3bac08d1d809.png)
for example, kilo's arrival shuttle bay is filled with /plating/airless , these three tiles under the engines in the kilo arrivals shuttle also have /plating/airless. whenever the kilo shuttle docks/leaves those three airless tiles on the shuttle multiply each time until the game runs out of memory.

## Reproduction:
find a shuttle with a tile type in the landing zone that matches the tile type of the same tile on the shuttle. call that shuttle over and over again until byond cries and the game crashes.

**Comment by willox** [comment]
to reproduce reliably do it up to 20 times
