### ISSUE TITLE
You cannot reach Robotact when fully discharged as a borg.

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#54244]
## Reproduction:
Run out of power or have your cell removed, access tablet, you cannot click things on the tablet. This means you cannot access RoboTact, and further, your laws.
![image](https://user-images.githubusercontent.com/62538745/95415031-d136bd00-08f4-11eb-9a8f-4e1f9a9a2ffe.png)

**Comment by msgerbs** [comment]
You're a vastly more experienced silicon player than most, what would be your recommendation to fix this? Should the Borg tablet be accessible when the borg is out of power?

**Comment by ZeroMODE0** [comment]
I only play borg! But I'd say maybe make a separate robotact button, or have the rest of the programs be inaccessible to the tablet when depowered (somehow. I'm not saying this is easy aaaaa)

**Comment by Tlaltecuhtli** [comment]
isnt it a verb to state laws?

**Comment by zxaber** [comment]
This is a bug, I intended the tablet to be fully usable even when the borg has no power (the wireless connection dies, though, so you can't affect anything using an app that requires NTNet).

>isnt it a verb to state laws?

All borg verbs were removed in favor of the borg tablet and Robotact.

**Comment by Barhandar** [comment]
The recommendation to fix this is to not remove redundancies that are proven to function, i.e. restore the verbs.

**Comment by ZeroMODE0** [comment]
The verbs being re-added would be a nice failsafe/fallback incase the tablet for some reason isn't doing what the verbs should be, but if it gets fixed up so it works properly we don't really need that
