### ISSUE TITLE
All files in the sounds folder cause windows explorer to freak out

### ISSUE THREAD

**Issue by Qustinnus** [tgstation/tgstation#54265]
this isn't really an issue with the codebase specifically I suppose, but I checked up with a lot of people and apparently this happens to everyone: If you open any folder in tgstation/sound/ it will start slowly blanking out every file's name, and then suddenly re-load. This freezes up windows explorer too and happens almost every time I go check out sounds (And then once it does it once, stops for a while, not sure until I update or until I restart my pc)

**Comment by nicbn** [comment]
That's pretty much an issue with explorer, not with the codebase itself.

Go into folder properties and change the "optimize this folder for" from "Music" to "General" or something, for me it solves the issue.

**Comment by nicbn** [comment]
For some reason I can't edit my comment, you can do it recursively by going to the sound folder and selecting the recurse option below the dropbox on the same prop.

**Comment by msgerbs** [comment]
Nothing we can change, caused by how Windows Explorer is hot garbage at generating metadata for certain filetypes in certain views.
