### ISSUE TITLE
Hell factory void walls

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/tgstation#54272]
## Round ID:

[147967](https://scrubby.melonmesa.com/round/147967)

## Testmerges:

The following pull requests are currently test merged:
#54183: 'Mobility refactor: no more update_mobility()' by Rohesie at commit 9e625d60e9
#54073: '[WIP] Medium Roleplay Traitors (Lots of fluff, refreshing objectives on completion.)' by tralezab at commit 9708d06551
#53596: 'Removes Admin Stickyban Exemption Workaround' by bobbahbrown at commit adbee092e4

## Reproduction:
 That's a wall.

![image](https://user-images.githubusercontent.com/57223640/95615194-1b8c7b00-0a68-11eb-9c5b-6c761e85ebc2.png)

**Comment by Rohesie** [comment]
Var-edited walls. Eeeew!
