### ISSUE TITLE
You can no longer compost some food / snacks into hydroponics basins for nutriment

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#54279]
## Round ID:

[147983](https://scrubby.melonmesa.com/round/147983)

## Reproduction:

Old-food can still be composted, but new-food can no longer be spread into trays for composting.

**Comment by msgerbs** [comment]
What's this, bug 136 from the food refactor? Sigh.

**Comment by Qustinnus** [comment]
You try remaking 400 items and see if you get any bugs

**Comment by Qustinnus** [comment]
This just sounds like a dupe of every single tray issue that's on the github by now too

**Comment by msgerbs** [comment]
> 
> 
> This just sounds like a dupe of every single tray issue that's on the github by now too

In what way?
