### ISSUE TITLE
People who lie down involuntarily still take time to get back up

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#54293]
## Round ID:
///

## Reproduction:
Get shovestunned, then cry because now you have to wait another 2 seconds to get back up after the stun is over.
The same happens with aheals so they still have to get back up after they were healed from death.

**Comment by Rohesie** [comment]
This is more of a balance concern, really. If you get forced into the floor, getting up takes a bit, it makes no sense for you to take a long time if you decided to lay down but not if you were forced down.
On the other side of the coin, you no longer have to stay in place while getting up, you can move around and the action won't be interrupted, in both cases.

**Comment by brotherbeyondd** [comment]
Oh yeh but the issue with that is you made all knockdowns two seconds longer.

**Comment by Rohesie** [comment]
Yea, and also getting up an interruptible action.
Are there any particular knockdowns you feel concerning? Name them and I'll get to re-balancing them.

**Comment by brotherbeyondd** [comment]
Well shovestuns and aheals are the two big ones I can think of. There was never a getting up time when knocked down prior to this, it was only if you rested willingly.
