### ISSUE TITLE
You can attach c4 to c4, then attach c4 to c4, then attach c4 to c4.....

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#54299]
Basically, for the price of however many sticks of c4 you can get, you can get them all attached to one another and then attach them to your target. The explosions will obviously stack as a result.

If that target is some kind of signaller, then attach it to a grenade. Somehow....

Basically there is no level of sanity as to what you can attach c4 too, or even checks to see if the object you just attached this 4th dimensional stick of c4 too would be able to fit into whatever it is you attach that object too.

**Comment by brotherbeyondd** [comment]
feature

**Comment by ATH1909** [comment]
will the c4 pieces delete each other before they actually explode?

**Comment by cacogen** [comment]
I don't know if this is actually a viable solution but it'd be cool if attaching them to each other (or attaching objects to each other in general via some general method that that used) increased their volume accordingly, which I guess would just be adding the two w_classes to each other.

**Comment by msgerbs** [comment]
> 
> 
> feature

This but unironically. You can attach C4 to anything, why should you not be able to attack them to each other?

**Comment by Tlaltecuhtli** [comment]
where is the bug?

**Comment by itseasytosee** [comment]
probably should limit to small-sized items and above.

**Comment by SethLafuente** [comment]
I actually tried this the C4 explosion dosent stack at least not anymore as I stacked 14 C4 on each other to kill a traitor that had a lot of c4 the c4 that exploded destroyed the second C4 and since the other c4 were attached to it weren't attached they all also self deleted causing only the damage of a single c4 which didn't kill them and I had to throw a syndicate mini bomb to finish the job

**Comment by Sealed101** [comment]
tests show no stacking of explosions, be it in size, impact or multiple explosions on the same tile.
so there is no actual benefit to stacking c4 on a c4, or multiple c4s on a single object. which is funny but also inconsistent. but let's be honest c4s could just use a good refactor to properly balance out the shenanigans.

**Comment by msgerbs** [comment]
Yeah that was probably "fixed" by that change that nerfed C4 a while back.
