### ISSUE TITLE
Mech Issues...Some Number: Literal Invincibility Edition

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#54298]
While inside a mech, you can use objects on your mech. This allows you to use a welder on your mech from the inside, which allows you to repair your mech on the go.

It doesn't seem to work with inducers (thank fuck) but basically this means you can't ever kill a mech from health damage if the person inside has enough welders to keep their health up. This is entirely feasible given we have infinite welder fuel welders.

@TiviPlus

**Comment by ATH1909** [comment]
amazing

**Comment by necromanceranne** [comment]
This also lets you c4 your mech.....if you wanted to do that I suppose.
