### ISSUE TITLE
Crafting hooch doesn't use up the materials used in crafting it.

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#54300]
## Testmerges:

#54183: 'Mobility refactor: no more update_mobility()' by Rohesie at commit 9e625d60e9
#54073: '[WIP] Medium Roleplay Traitors (Lots of fluff, refreshing objectives on completion.)' by tralezab at commit 9708d06551
#53596: 'Removes Admin Stickyban Exemption Workaround' by bobbahbrown at commit adbee092e4

## Reproduction:

Craft a hooch bottle using 100 units of hooch (in a bottle, specifically item/reagent_containers/food/drinks/bottle) , a bottle, and a paper bag. The materials don't get expended so you can just keep doing it.

**Comment by Learner10** [comment]
Me and Timberpoes have more or less came to what exactly replicates the issue. From their explanation (at least from what I grabbed from it), it's trying to look for that specific reagent container, and fails to, leading to a runtime and no consumption of materials.

Basically... it's looking for an ordinary glass bottle, but gets unhappy if the glass bottle being crafted with is also the location of the reagents as well.

What's not listed here is what can also happen SHOULD the recipe pass, which is achieved by having the hooch in a separate container from the glass bottle. This recipe has another issue where it doesn't check for an empty bag upon completion, and will simply delete the bag and all contents of said bag should the ingredients be consumed, which can, and WILL lead to some other issues down the line.

**Comment by Timberpoes** [comment]
Thanks to Vek, Learner and Spookuni for dragging me onto Manuel at 11pm on a Saturday while I was almost catatonically drunk to diagnose and fix bugs.

Double thankies-thanks to Learner for understanding I was almost catatonically drunk and using very small words and short sentences so I could keep my attention span focused long enough to identify the issues and go to sleep.
