### ISSUE TITLE
2 escape shuttles arrived with some delay, the second one ended the round

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#54316]
## Round ID: 
#148075 [Round](https://sb.atlantaned.space/rounds/148075) 

## Reproduction:

A shuttle call happen, another shuttle was bought within about a minutes time, and then called later. The first one arrived, departed, and landed at centcom without ending the round, the second shuttle, which was the SSShuttles "emergency" shuttle, spawned after a delay, arrived, and ended the round.

**Comment by Dennok** [comment]
Don't see ability to bought  shuttle after call (admin call) but see where problem.

**Comment by wesoda25** [comment]
This just happened on bagil on round 149190. A shuttle was called, it was randomly replaced by the alien ship by an event, which did not recall but set the ETA to 0 (I think shuttle docked at this point, but not sure). Crew then called shuttle again, which resulted in a shuttle crush.
![image](https://user-images.githubusercontent.com/37246588/97359847-c75d0580-1873-11eb-8d0b-96d3b0428b43.png)
