### ISSUE TITLE
Ice Box Multi Z Departments Immune To Rad Storms

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#54313]
## Reproduction:

1). Rad storm
2). Any ice box multi z department
3). Does not get rad stormed
4). Uh
5). Yes

**Comment by msgerbs** [comment]
Is this in lower xenobio?

**Comment by msgerbs** [comment]
Looks like this is because the upper and low Z levels of Ice Box are not station z-levels and rad storms only affect station z-levels.

**Comment by Misdoubtful** [comment]
Yeah I failed to clarify, it encompasses both sections.

**Comment by msgerbs** [comment]
So you didn't get a radstorm in the xenobio area on the main z-level? That's bizarre. Yeah, I was able to reproduce that as well. I'm at a bit of a loss here but I'll keep losing.

**Comment by msgerbs** [comment]
Ugh this is so dumb. The lower Ice Box z-level is not set as a station z-level and the xenobio area is being considered as being on the lower z-level.

**Comment by MrMelbert** [comment]
upper and lower botany on icebox are also immune to rad storms.

**Comment by msgerbs** [comment]
Yeah, this likely affects any area which is on multiple z-levels.

**Comment by Whoneedspacee** [comment]
feature lower z levels are safe 😎

**Comment by dragomagol** [comment]
Fixed by #54779
