### ISSUE TITLE
Alt clicking the supermatter damage as ghost displays every icon in effects.dmi

### ISSUE THREAD

**Issue by Gamer025** [tgstation/tgstation#54329]
## Reproduction:
Move next to supermatter
Alt click it
Get this in status panel:
![image](https://user-images.githubusercontent.com/33846895/95685904-0dbb2f00-0bfb-11eb-944c-9873d7eb8536.png)

**Comment by Angustmeta** [comment]
Could have same cause as #53824.

**Comment by Gamer025** [comment]
> Could have same cause as #53824.

Hmm someone actually told me on Discord about decals behaving similar but I couldn't reproduce that behavior in the round I noticed the SM countdown behavior

**Comment by optimumtact** [comment]
@MrStonedOne is this related to the cdn transport?

**Comment by timothymtorres** [comment]
Duplicate of #53824
