### ISSUE TITLE
Nearsightedness affects augmented eyes

### ISSUE THREAD

**Issue by Sage1700** [tgstation/tgstation#54366]

**Comment by Winterous** [comment]
If it's genetic then it's not a problem with the eyes, it's a problem with your DNA. Something about your DNA prevents you focusing your eyes properly. (or in the case of the nearsighted quirk, it's a brain thing)
Yes robotic eyes should theoretically focus by themself, but yeah.

**Comment by Dennok** [comment]
Yes, think about this like brain problem. I dont fan of this but someone want make traits unhealable.

**Comment by msgerbs** [comment]
I agree with Dennok. This is working as designed, even though the design is IMO stupid.

**Comment by nightred** [comment]
No comments have been made to improve or counter this design.
Closing the issue as it is not a bug.
