### ISSUE TITLE
Rosewood double-barreled shotgun has no suit storage or back slot sprites.

### ISSUE THREAD

**Issue by Donpedrito** [tgstation/tgstation#54363]
## Reproduction: Grab the double-barreled shotgun from the bar backroom, alt click it to change it to Rosewood, and put it on your back or your armor vest's storage slot. 
The sprite is that default pink-and-black checkerboard pattern for objects with no sprite.
I imagine this happens for the other skins on the shotgun as well, but I can't test it because I don't have the files to set up a local server (not a coder, just reporting a bug I found).
Sorry for any formatting issues, I haven't made one of these in forever.

**Comment by Donpedrito** [comment]
To clarify, the shotgun had a sprite when it was equipped before I changed the skin.

**Comment by necromanceranne** [comment]
Probably the same stuff that's been plaguing bible resprites
