### ISSUE TITLE
Action button object icon is off-centre after object is picked up from table

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#54375]
## Round ID:

This was yesterday so I can't easily find out. Shouldn't be round-specific anyway

## Reproduction:
1. Put PDA on table
2. Pick PDA up
3. On the "toggle light" action button, the PDA's icon will be offset like it was on the table 

Though I didn't check I assume this is true of all objects.

**Comment by Angustmeta** [comment]
Had trouble clicking items on the floor numerous times today. Often had to alt-click to reach the item.

**Comment by Tlaltecuhtli** [comment]
i guess the icon generation is passing pixel offsets?

**Comment by msgerbs** [comment]
> 
> 
> Had trouble clicking items on the floor numerous times today. Often had to alt-click to reach the item.

This is quite possibly related. What have we changed regarding item icons?

**Comment by timothymtorres** [comment]
@cacogen Do you know if this ever got fixed?

**Comment by timothymtorres** [comment]
![dreamseeker_wMCrJlMvhU](https://user-images.githubusercontent.com/5195984/194872280-05735859-dd96-4f37-af67-95b8e145f083.png)

This still exists.
