### ISSUE TITLE
Weird turf or floor problems that result in lost click inputs or the floor taking priority over objects

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#54378]
This ones a difficult one for me to replicate since I've never had any consistency trying to work it out. But I can at least share some observations.

Essentially, something is causing floors to always take priority on a click in some instances, resulting in anything, including ui elements, becoming unclickable. IT even seems to affect when trying to shoot things directly with guns (resulting often in you shooting into completely different tiles), or just nothing happening.

1) The problem started roughly about two months ago.

2) It seems to happen almost every time you join a server for the first time. Try joining a server, click a vendor or some object, and find you can't click anything. This isn't reliable, just the moments when I notice it most.

3) The problem seems to be able to be circumvented when you use the altclick functionality to directly click objects on a turf. So this is clearly a priority problem, not just that these objects are unclickable.

4) It seems to result in things like ui elements becoming unclickable as well, resulting in you losing action button usage, even when a ghost

5) I should note, I am using the most up to date version of byond and still getting this problem.

Fikou also found this, in the following images. I notice personally that both those images have some kind of decal change on the turf. Footprints, blood, what have you. It leads me to haphazardly guess it's a decal problem, which makes sense given those were changed fairly recently and within the timeframe of this problem persisting. But I'm not sure if it explains why machinery might be interrupted.

![fikoufloorbug1](https://user-images.githubusercontent.com/40847847/95904139-d1e2be00-0de2-11eb-8ecb-f3f58b85a230.png)
![fikoufloorbug2](https://user-images.githubusercontent.com/40847847/95904151-d7400880-0de2-11eb-81f9-7c2d072608f6.png)

**Comment by Iamgoofball** [comment]
been having this issue, just ran into it last night in Robotics trying to pick up mecha weapons to slap onto my Gygax on Manuel.

**Comment by ATH1909** [comment]
I've run into this most when trying to treat people on stasis beds, which might be due to a blood decal or something...

**Comment by CRITAWAKETS** [comment]
This seems to be actually the hitboxes to pick things up being offset.

**Comment by Dennok** [comment]
Its  be on multiZ map?

**Comment by Tlaltecuhtli** [comment]
just had this issue in 148272, it was metastation not multi z

**Comment by necromanceranne** [comment]
![dmstotimber1](https://user-images.githubusercontent.com/40847847/95996391-58001280-0e7e-11eb-8546-cdd4e28d2c50.png)
![dmstotimber2](https://user-images.githubusercontent.com/40847847/95996404-59c9d600-0e7e-11eb-997d-454d79a8080d.png)
![dmstotimber3](https://user-images.githubusercontent.com/40847847/95996413-5c2c3000-0e7e-11eb-8d1d-19f5f9e9fdc4.png)

**Comment by nightred** [comment]
This looks like the new decal merging effect moving the tile to the top of the click stack.

**Comment by Timberpoes** [comment]
100% reproduction steps:

Implant self with toolset arm (any method. Syndie autosurgeon was what I used)
Spawn in empty /obj/item/storage/box
Hold box in the same hand the toolset is part of.
Select any tool.
This will immediately drop the box.
When you pick the box up, the turf you're stood on will duplicate exhibiting the same behaviour as this issue report.

**Comment by ZeroMODE0** [comment]
Round ID 149090 had many many many of these, it feels like this is getting worse for some reason. Almost every item pickup I have to context menu now, but only sometimes- If it's a huge issue in the beginning it's a consistent one all the way through. The biggest this is an issue is in areas with lots of items or in robotics. (Generally)

**Comment by necromanceranne** [comment]
I suspect this was a beyond issue that has now since cleared. I've not encountered it in several months.
