### ISSUE TITLE
ghosts can edit the names of the pills to be produced by a pill press, but not any of the other settings. the name will stick, but only on the ghost's screen until they close the pill press's window

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#54389]
![image](https://user-images.githubusercontent.com/42606352/95964859-e321cf80-0dce-11eb-8037-44bf3116bfe9.png)
![image](https://user-images.githubusercontent.com/42606352/95965069-2419e400-0dcf-11eb-924d-ea45a9d2a32d.png)
I doubt that it actually affects the names of the pills produced, but it seems odd that you're allowed to type in this field as a ghost at all.

**Comment by TheBonded** [comment]
just like how you can type in the tcomms hub name field as a ghost. doesn't let you actually change it, so this shouldn't be that much of a problem

**Comment by SkeletalElite** [comment]
The pressure dial of cannisters does a similar thing, it can be adjusted but it won't actually change it.

**Comment by gitbirb** [comment]
this happens with the jukebox too i believe (with changing the song as ghost), and it ends up in pretty buggy results.

**Comment by stylemistake** [comment]
This is a drawback of our implementation, but as it was said, it doesn't produce actions in the game if you're a ghost.
