### ISSUE TITLE
[CRITICAL] AI cannot spin/flip anymore

### ISSUE THREAD

**Issue by techno0** [tgstation/tgstation#54391]
AI needs to spin. Its a integral part of the gameplay for everyone on the station, this needs to be fixed asap.

#53981 broke this

**Comment by trerri** [comment]
I suggest we do what goon did and make AI cores scroll their display upwards when hitting the flip key, and make a beep-boop sound.

**Comment by ATH1909** [comment]
priority: critical

**Comment by TheBonded** [comment]
This is a critical oversight. AI is nigh unplayable in it's current state. This needs to be fixed ASAP

**Comment by actioninja** [comment]
Don't abuse the priority labels.

**Comment by Jared-Fogle** [comment]
@trerri show me what this looks like and i'll do it

**Comment by techno0** [comment]
AI still cant flip

**Comment by Jared-Fogle** [comment]
bro look Up
