### ISSUE TITLE
the status menu is, uh, w o n k y for sentient diseases

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#54390]
![image](https://user-images.githubusercontent.com/42606352/95968557-33029580-0dd3-11eb-9f12-a4b3fa79f950.png)

**Comment by trollbreeder** [comment]
God damnit, someone used vertical text in Excel!

**Comment by Couls** [comment]
`/mob/camera/disease/get_status_tab_items()
    ..() <-- replace with . = ..()
    if(freemove)
        . += "Host Selection Time: [round((freemove_end - world.time)/10)]s"
    else
        . += "Adaptation Points: [points]/[total_points]"
        . += "Hosts: [disease_instances.len]"
        var/adapt_ready = next_adaptation_time - world.time
        if(adapt_ready > 0)
            . += "Adaptation Ready: [round(adapt_ready/10, 0.1)]s"`
that should fix it
