### ISSUE TITLE
Smothering with rag is broken

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#54393]
## Round ID:
[148283](https://scrubby.melonmesa.com/round/148283) Terry. 

Reproduced locally. 

## Reproduction:
1. Put 5u reagents in a rag. 
2. Click someone else on harm intent (with mouth uncovered). 

**Result:** "You start to wipe down Ryker Magor with the damp rag..."
**Expected result:** You smother Ryker Magor. 

I did manage to smother myself once that round, but can't smother myself or anyone else on local testing.

**Comment by Pugie** [comment]
Do you remember what intent you were on?

**Comment by Angustmeta** [comment]
All of them.

**Comment by Pugie** [comment]
Maybe unrelated but another thing that relies on mouth targeting and is new (slapping) has been inconsistent and after a few successful slaps just does shoves instead for the rest of the round.

**Comment by Angustmeta** [comment]
Could be related yeah. 

For smothering it didn't matter before but I tried aiming at all different parts as well and it still didn't work.

**Comment by Quiteanything** [comment]
I tried this a couple days ago myself and was planning to make an issue report about it. Some times it works, sometimes it doesn't. When it worked for me (couldnt figure out why it did work, and then it stopped working again about 2 tries later), it seemed to transfer all the 5u units of Dr. Gibb I had in it to the person at the time.

**Comment by ATH1909** [comment]
maybe this has something to do with the .? PR? If you're getting a wipe down message, that means that the `if(iscarbon(A) && A.reagents?.total_volume)` message has to be failing...
