### ISSUE TITLE
Was pressing buttons on roulette, it crashed

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#54394]
I got dis https://i.imgur.com/bqokGHb.jpg

## Testmerges:

The following pull requests are currently test merged:
#54362: 'Audio falloff re-work, and increased audio range.' by Qustinnus at commit 779d09ed96
#53596: 'Removes Admin Stickyban Exemption Workaround' by bobbahbrown at commit adbee092e4

## Reproduction:
Press number buttons on roulette.

**Comment by Qustinnus** [comment]
i got this too

**Comment by ATH1909** [comment]
u got that
