### ISSUE TITLE
Silicons unable to make station announcements 

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#54405]
## Reproduction:
>Get begged by crew to make station announcements about suit sensors
>Go to comms console to do so
>No option present
>Get yelled at by CMO 
>*buzz

I think something was messed up with the tgui chnage for the consoles.

**Comment by TheBonded** [comment]
you don't make stationwide announcements on comms consoles. you use request consoles, the ones in the walls that say when mining brings in a new load of ores, that no one uses except Heads to make announcements. I'm pretty sure only the ones in the heads rooms work, as well as the AI's sat one, but I may be wrong. The comms console is only for captain announcements

**Comment by msgerbs** [comment]
Silicons normally have full access to machines including the comms console do they not?
