### ISSUE TITLE
New hijack system didn't work as blood brother

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#54407]
## Round ID:
[Round ID]: #148346

## Reproduction:
1. Be blood brother. 
2. Other blood brother is dead in space but I want to redirect shuttle anyway. 
3. Alt-clicked shuttle console 5 times before it departed. 
4. Trying a 6th time said "The emergency shuttle is already loaded with a corrupt navigational payload. What more do you want from it?", as expected. 

Shuttle arrived to Centcom instead of the syndie base. Hijack objective also failed, but don't know if you're meant to fail or not with only one BB on board.

**Comment by Angustmeta** [comment]
Can't edit my comment because giThUb, but round id was 148346 on Terry.

**Comment by Angustmeta** [comment]
Also I can see now the redtext with a BB left behind is intended, but I think it should still redirect.

**Comment by necromanceranne** [comment]
Yeah you would have greentexted, I checked. But it just isn't docking correctly. No stress, I fix.
