### ISSUE TITLE
The nanite suit sensor program breaks suit sensor monitors

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#54401]
Issue reported from  Round ID: [148303](https://scrubby.melonmesa.com/round/148303) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1534

When people have the nanite suit sensor program, it basically causes the monitor to break because it seems to constantly be readding the same entries into the list and causing it to incorrectly update and refresh. Once those are removed, it goes back to normal.

**Comment by XDTM** [comment]
By break what do you mean? Does it have incorrect information or does it runs slowly/not at all?

**Comment by necromanceranne** [comment]
@XDTM sorry for this delayed reply. You know how sometimes there is like several dozen enteries in thr crew monitor of the same entry? That is because the nanites broke them. They seem to prevent the open crew monitor window from properly updating normally and add a bunch of fake duplicates endlessly.

**Comment by XDTM** [comment]
I've been tring to reproduce this on a test server by repeatedly activating/deactivating both nanite and suit sensors on a couple of humans, with no success so far. If you notice any possible other factor that could be causing the bug, it would help a lot.

**Comment by MTandi** [comment]
I've been tackling the nanits and suit sensors, and didn't manage to reproduce this either
