### ISSUE TITLE
Agent ID loosing syndicate access after changing a job

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#54429]
## Reproduction: 
Get Agent ID from uplink, change job via HoP console. That round it was Nuclear OPs ID and job changed to Captain.

If this isnt a bug, oversight.

**Comment by msgerbs** [comment]
This is clearly not intended, but I am curious, what were you even trying to access that requires syndicate access?

**Comment by Livrah** [comment]
> This is clearly not intended, but I am curious, what were you even trying to access that requires syndicate access?

Doors at nuclear ops ship

**Comment by msgerbs** [comment]
> 
> 
> > This is clearly not intended, but I am curious, what were you even trying to access that requires syndicate access?
> 
> Doors at nuclear ops ship

Oh shit, yeah, I see now. That's definitely no bueno.

**Comment by OmegaShoots** [comment]
This can be remedied by just using the agent ID's built in function to scan the ID you want the access of.

**Comment by interestingusernam3** [comment]
>This can be remedied by just using the agent ID's built in function to scan the ID you want the access of.

But this also means ops get locked out of the ship if they try to give themsleves fake jobs for stealth ops.
