### ISSUE TITLE
Feeding an orange slime 10 rainbow cores does not produce a butterfly knife

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#54436]
Saw this specifically in 148434, but I've seen it in other rounds as well.

When you feed an orange slime one extract, and then the rest through a xeno bag, it just disappears, but doesnt spawn a butterfly knife.

**Comment by Angustmeta** [comment]
It's the other way around. Must feed 10 orange extracts

**Comment by Angustmeta** [comment]
You're probably meming though

**Comment by ATH1909** [comment]
![image](https://user-images.githubusercontent.com/42606352/96336519-086c4300-1046-11eb-9f58-400465d68bee.png)
![image](https://user-images.githubusercontent.com/42606352/96336523-0efaba80-1046-11eb-9952-148e23a874c8.png)
![image](https://user-images.githubusercontent.com/42606352/96336530-16ba5f00-1046-11eb-86ab-eeb1cb4e38f5.png)

This isn't a bug- you needed to feed 10 orange extracts to a rainbow slime, not 10 rainbow extracts to an orange slime.

**Comment by wesoda25** [comment]
> Nvm you're definitely meming

Haha yeah that’s definitely what this is
