### ISSUE TITLE
HoS does not have the credentials to download BotKeeper modular computer program

### ISSUE THREAD

**Issue by SkeletalElite** [tgstation/tgstation#54440]
## Reproduction:

Try to download the botkeeper program as HoS so you can command beepsky around like you can with the PDA. Realize you can't.

**Comment by 81Denton** [comment]
https://github.com/tgstation/tgstation/blob/a7fb749f00c71fa1ea99f97a8ea9fe7c998e0ffc/code/modules/modular_computers/file_system/programs/robocontrol.dm#L7
