### ISSUE TITLE
Resin floor can grow over open space

### ISSUE THREAD

**Issue by msgerbs** [tgstation/tgstation#54459]
## Reproduction:

1. Be xeno
2. Plant resin floor near open space
3. Resin grows over the open space, hiding it from view
4. Walk on the resin floor and fall through it
5. Laugh at people who fall through the now-hidden open space, and throw a facehugger at them.

![image](https://user-images.githubusercontent.com/1313921/96372955-1d70d100-112f-11eb-8836-8b0cfc723b8a.png)

**Comment by ATH1909** [comment]
just like 'nam...
