### ISSUE TITLE
Ice Box Xenobiology counts as maintenance for spicy air

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#54467]
## Testmerges:
#54338: '[s] Replace json_decode with one that validates through rust-g' by Jared-Fogle at commit 1e5b6ef680
#53596: 'Removes Admin Stickyban Exemption Workaround' by bobbahbrown at commit adbee092e4

## Reproduction:
It's probably somehow flagged as maint, but I cba to fix it, so.

**Comment by MrMelbert** [comment]
dupe of #54313 ?

**Comment by TheVekter** [comment]
YEAH.
