### ISSUE TITLE
You can place arm toolset implant tools into a toolbox

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#54464]
## Round ID:
Multiple

## Testmerges:
#54338: '[s] Replace json_decode with one that validates through rust-g' by Jared-Fogle at commit 1e5b6ef680
#53596: 'Removes Admin Stickyban Exemption Workaround' by bobbahbrown at commit adbee092e4

## Reproduction:
1) Get yourself implanted with a toolset implant (or VV it onto yourself, whatever, I'm not a cop).
2) Obtain toolbox
3) Pull out any of the tools from your implant
4) Put them in the toolbox

Once removed from the toolbox they function identically to their normal counterparts and cannot be placed back into the implant. Trying to access them like you normally would just does nothing.

This isn't like... game breaking, but it can be annoying to misclick somewhere and suddenly lose convenient access to your cool robot screwdriver.

**Comment by ATH1909** [comment]
oh god oh fuck

@zxaber

**Comment by zxaber** [comment]
Man, I thought COMSIG_DROPPED was supposed to catch shit like this.
