### ISSUE TITLE
Kinetic Accelerator cooldown counts all KAs on a person instead of just in their hands

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#54471]
Someone mentioned this in OOC and it doesn't look like the issue's been reported. 

From what I was told duel wielding KAs is supposed to increase the cooldown by the amount of KAs in your hand slots. But the proc used counts all KAs a person is holding rather than just the ones in their hand slots. Supposedly this is unintentional. The for loop that counts held KAs is here: https://github.com/tgstation/tgstation/blob/b4921765c751fb9febafb33d5fa2584143bbf4d2/code/modules/projectiles/guns/energy/kinetic_accelerator.dm#L128

**Comment by Dennok** [comment]
It's a shame it doesn't increase damage this way.

**Comment by Winterous** [comment]
I always thought it was deliberate, to discourage you carrying KAs with different setups for different purposes... For some reason.

**Comment by XDTM** [comment]
I think that might have been intentional as a result of people juggling KAs inside a backpack to fire faster

**Comment by Dennok** [comment]
I can't imagine how

**Comment by XDTM** [comment]
Probably with the help of hotkeys and/or macros, but even without those you could probably click the backpack slot to store the current PKA and click the new PKA faster than it would take to wait out the recharge

**Comment by necromanceranne** [comment]
Yeah PKA juggling is the reason. You can do it with ebows as well to get near full rate of fire if you hotkey well enough with ebows. PKAs would be no different.

This also checks for PKAs that are children of the parent. So ebows affects anywhere that unique_frequency is TRUE.

**Comment by cacogen** [comment]
It sounds like it is intentional then

**Comment by Dennok** [comment]
nope but who cares
