### ISSUE TITLE
You can't open ID locked doors while in a mech

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#54480]
## Round ID: 149636

Reproduction: Get access for a door (all access should work, but I only had access to specific IDs in a live round), hop into a mech, try to move into the door to open it.

Description: Trying to walk through a door whilst in a mech results in nothing happening. The access denied animation doesn't play either. Doors with no access requirements will open just fine, though.

**Comment by necromanceranne** [comment]
The reason for this is likely because you no longer have hand use, which is the pre-requisite for opening id locked doors. This was likely a bug introduced by this pr https://github.com/tgstation/tgstation/pull/54302

**Comment by Rohesie** [comment]
Mechs are a lovely bundle of little exceptions.
Tivi, can you handle this?
