### ISSUE TITLE
Stomachs can be used and abused for some pretty insane stuff with chem stacking and addictions

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#54497]
## Reproduction:

Okay, so the stomach and the bloodstream are two different reagent containers. Turns out, this is absolutely dangerous for chem balance, because you can double-dose on chems (gaining its effects twice on a single metabolism) and other miscellaneous effects.

You can not only dodge overdose thresholds by taking some of the chem via ingestion and some via patch/inject, but you can also double up on the effects. Yeah, you can just... metabolize Oxandrolone or Salicylic acid twice for 8 of their respective healing at once.

![image](https://user-images.githubusercontent.com/51863163/96573031-35616580-1293-11eb-8271-b0b41274178f.png)

start stacking chems and you can get up to, say... 12 brute / burn healing a tick while in crit. 

![image](https://user-images.githubusercontent.com/51863163/96573377-abfe6300-1293-11eb-9958-2addb382ba50.png)

why stop there? keep adding chems and we can get up to 20, 24, 28? brute / burn healing a tick. 16 oxy healing a tick. 

Bonus: you can be addicted to the same thing twice, once from the stomach and once from the blood. a nasty surprise for anyone.

![image](https://user-images.githubusercontent.com/51863163/96572662-ba984a80-1292-11eb-940b-c3a696997188.png)

**Comment by ATH1909** [comment]
gee it's almost like I predicted that this exact thing would happen

**Comment by ATH1909** [comment]
wait, my apologies, I can't find any posts of mine that explicitly predict this specific problem.

still, it should have been kind of obvious, no?

**Comment by msgerbs** [comment]
Stomach should send reagents to the bloodstream, not directly metabolize them.

**Comment by Winterous** [comment]
> 
> 
> Stomach should send reagents to the bloodstream, not directly metabolize them.

That's my thinking as well.

There could be different reagent effects for digestion and metabolisation; nutriment for example wouldn't do anything when metabolised, only when digested, and probably wouldn't transfer to the bloodstream.
Another example, sulphuric acid; if it ends up in your stomach it won't cause the body-wide toxin damage that it normally does, it'll just damage your stomach and cause burn wounds to your torso.

Could have interesting emergent properties, like higher-than-overdose pills which slowly release so as to avoid overdosing; simply being in your stomach isn't doing anything, or contributing to overdose or addiction thresholds, unless that reagent specifically has digestion effects.

**Comment by msgerbs** [comment]
Stomach-specific effects would need a whole lotta review to not be unbalanced I think. I think for now just making every reagent in the stomach pass into the bloodstream over time would be fine. I'll take a look at it this weekend if nobody else has done so.

**Comment by ExcessiveUseOfCobblestone** [comment]
@nightred this needs to be fixed or reverted.

**Comment by KathyRyals** [comment]
- Blood and stomach process chems separately. Double ticking, no reactions between the two.
- Addictions and OD are separate as well. You can be DOUBLE addicted.
- Most purger interactions only affects the blood. So you can have pentetic in the blood and misc chems in the stomach just fine.

**Comment by nightred** [comment]
> @nightred this needs to be fixed or reverted.

I have a plan, i will put something up that fixes this.

**Comment by Winterous** [comment]
>     * Most purger interactions only affects the blood. So you can have pentetic in the blood and misc chems in the stomach just fine.

This part I see as a feature.

**Comment by Jared-Fogle** [comment]
its intentional but its kinda lame. it doesnt add anything, it just means you make both patches and pills
