### ISSUE TITLE
It's no longer possible to dump the contents of a container onto a turf via clickdrag.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#54491]
Step one: Get box full of crayons.

Step two: Try and dump them onto the floor by click dragging from the box to the floor.

Step three: There is no step three as it fails to dump the contents after the do_after.

**Comment by Timberpoes** [comment]
![I8dZFSCt3j](https://user-images.githubusercontent.com/24975989/96538546-ad7a5c00-1290-11eb-91b8-eb1ac7cb7b46.gif)

**Comment by ATH1909** [comment]
what about other containers?

**Comment by necromanceranne** [comment]
bags, boxes, not sure about beakers when splashed. Don't think so since I've seen some people splashing thermite lately.
