### ISSUE TITLE
Cuffs cannot be removed by yourself

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#54494]
## Round ID: [148686](https://scrubby.melonmesa.com/round/148686)

Testmerges: https://github.com/tgstation/tgstation/pull/54403 (only thing that seems likely to cause this)

Reproduction: cuff someone or yourself, the instant you try and remove the cuffs yourself (eg resisting/clicking the alert) it fails.

Description: This has been happening for a few rounds now, but when you're cuffed, there is no way of getting cuffs off of yourself, not sure if the same problem happens for straight-jackets or similar, nor do I know what could be causing this, it might be related to the fact that you cannot get up off the ground without resting and unresting first, or if you're cuffed and grabbed you're permanently stuck crawling.

**Comment by msgerbs** [comment]
> you cannot get up off the ground without resting and unresting first, or if you're cuffed and grabbed you're permanently stuck crawling.

I don't recall seeing either of these issues reported, can you post a separate issue for those as well?

**Comment by Serxule** [comment]
https://youtu.be/8K1lEOOuEgo here's a video of me doing it and of the crawling bug, which I'll make a separate report for

**Comment by Yenwodyah** [comment]
Wasn't fixed. This is still happening.
