### ISSUE TITLE
Crawling and getting up is bugged.

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#54502]
## Round ID: [148686](https://scrubby.melonmesa.com/round/148686)

Testmerges: https://github.com/tgstation/tgstation/pull/54403 (only thing that seems likely)

Reproduction: get stunned into stamina crit and wait for it to go away, you wont get up first without resting and then unresting, not even being shaken up works. and if you're cuffed and on the floor you cant get up at all.

Description: cant be shaken up when laying down, you have to rest and unrest to get off the floor, oh and if you're cuffed and on the floor, man you basically have broken legs at that point, you cant get up at all, not even if you're shaken up, you have to be uncuffed then do the rest and unrest thing. you can see the cuff part in this video https://youtu.be/8K1lEOOuEgo sadly I don't have one of the uncuffed but you get it, probably.

**Comment by Serxule** [comment]
it seems that this only happens from stamina crit aswell, getting shove-stunned doesn't seem to cause it

**Comment by gitbirb** [comment]
Had this happen on manuel where that pull isn't testmerged, so its probably not that. Hope someone fixes it soon because this also makes it so you cant resist out of cuffs after being stamcritted and cuffed, and not even lets people resist out of rolling beds.
