### ISSUE TITLE
Vent-crawlers have no way to get into a vent if there's an object covering it

### ISSUE THREAD

**Issue by rmariani** [tgstation/tgstation#54500]
## Reproduction:

To reproduce, put a sufficiently large-sprited object over a vent and then become a vent-crawling creature. You will be unable to alt-click the vent, and therefore you can't crawl through it.

**Comment by nullAdept** [comment]
You can alt-click the tile and then alt-click the vent in the status panel

**Comment by msgerbs** [comment]
This is what alt-clicking tiles is for and applies to anything you interact with via mouseclick. Not a bug, just a fundamental limitation of a top-down view.
