### ISSUE TITLE
flypeople starve forever always

### ISSUE THREAD

**Issue by gitbirb** [tgstation/tgstation#54510]
## Round ID: 
I don't remember the round but i do remember that it consistently happens anytime someone becomes a flyperson on multiple rounds, so it's probably not necessary.

## Reproduction:

Become flyperson, eat food, you vomit out more nutrients then you eat. Whenever you suck up the vomit you either don't gain any nutrients or not enough nutrients to make up for the vomiting (its probably the former since it worked that way a while back). 

Ends up making you starve forever.

**Comment by ATH1909** [comment]
@nightred @Qustinnus

**Comment by nightred** [comment]
I found the issue and will be patching it soon.
