### ISSUE TITLE
Mechs do not play a turning sound

### ISSUE THREAD

**Issue by InvalidArgument3** [tgstation/tgstation#54519]
Issue reported from  Round ID: [148764](https://scrubby.melonmesa.com/round/148764) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1536

Mechs do not play a sound when turning. Step sounds are working fine, though.

**Comment by dragomagol** [comment]
Unable to reproduce on any common mech, seems to be fixed
