### ISSUE TITLE
If you block a body being thrown at you, you are still knocked down.

### ISSUE THREAD

**Issue by SkeletalElite** [tgstation/tgstation#54535]
## Reproduction:

Hold a shield, have a body thrown at you until you successfully block it. Get knocked down anyways.

**Comment by SuperNovaa41** [comment]
Do you really think you could block a 150 pound body being thrown at you by a flimsy little shield

**Comment by SkeletalElite** [comment]
> Do you really think you could block a 150 pound body being thrown at you by a flimsy little shield

Maybe the game shouldn't say in chat you've successfully blocked it then? Even if being unable to block it is intentional, the message saying you did block is successfully is an oversight at best.
