### ISSUE TITLE
Other shuttles were viewable while in transit, and some odd loading bugs

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#54537]
## Testmerges:
#54483 #54318 #54517

## Reproduction:

Ride a shuttle during the round
![image](https://user-images.githubusercontent.com/58055496/96834472-ecc2bd00-13f6-11eb-8747-33c8515bba61.png)
![image](https://user-images.githubusercontent.com/58055496/96834455-e6ccdc00-13f6-11eb-9764-1d1cdd948259.png)
![image](https://user-images.githubusercontent.com/58055496/96834438-e16f9180-13f6-11eb-9964-cbdac1515d85.png)

**Comment by TemporalOroboros** [comment]
I mean, it makes sense. They are all loaded into the same general area.

**Comment by Cyberboss** [comment]
Are they viewable from each other though? If so, we have a problem

**Comment by Dennok** [comment]
The shade of moved shuttle.

**Comment by LemonInTheDark** [comment]
> 
> 
> Are they viewable from each other though? If so, we have a problem

They were, yes

**Comment by LemonInTheDark** [comment]
Or whatever that non cleaned no vis blocking husk is

**Comment by Cyberboss** [comment]
Should be fixed with my latest push
