### ISSUE TITLE
Pocket Protector Hidden Camera Doesn't Attach to Uniforms

### ISSUE THREAD

**Issue by Pugie** [tgstation/tgstation#54541]
Could be intentional but having it be the sprite of something that's only ever attached to uniforms is misleading.

**Comment by msgerbs** [comment]
Honestly I kind of thought this was intended, I don't think it was meant to function as a real pocket protector. I could be wrong though, and it would be a fun addition to a fairly mediocre item.

**Comment by Pugie** [comment]
MWAH
