### ISSUE TITLE
Mining Ore Scanners Stopped Working

### ISSUE THREAD

**Issue by UltimateFluff** [tgstation/tgstation#54549]
## Testmerges: 
#54517 #54318 #54483 

## Reproduction: 
I rolled Miner for round 148877 on Manuel and shortly after, war ops got declared. I and the other miner decided that the best thing we could do would be to still gather materials, since it would be used to make guns or otherwise sold for money for Cargo to buy guns. When we got down to Lavaland, we started digging, and while I thought it was lag at first or poor luck, it became quickly apparent that ore wasn't popping up - even turning off and turning on the scanner didn't fix it. I figured it was just some weird bug on my end, until the other miner mentioned it, as well as a late-join miner some time later. We did what we could, but ultimately we weren't able to do anything worthwhile of mining. Then it gets to round 148881, and according to the miner the station had, the issue was present then. As this is my first time submitting _anything_ on Github to my knowledge, I don't know if the format's right, but it's becoming an issue that hopefully can get identified and resolved - chances are, if Manuel's dealing with it, then the other servers possibly are, too.

**Comment by TheBonded** [comment]
#54517 #54318 #54483
These were the test merges that round, @UltimateFluff please update the post and add them

**Comment by UltimateFluff** [comment]
And done. Sorry, didn't know I needed to include them, with how I read the thing it seemed to imply only including them if the bug seemed related to them.

**Comment by dragomagol** [comment]
Appears to have been fixed
