### ISSUE TITLE
Blindness + pain vignette + vision impairing effects do not work at all

### ISSUE THREAD

**Issue by gitbirb** [tgstation/tgstation#54561]
## Round ID:
/tg/Station Manuel 148903

(it keeps happening just about every round for everyone i speak to, alongside happening to myself, so roundID probably does not even matter.)

## Testmerges: 
https://github.com/tgstation/tgstation/pull/54552
https://github.com/tgstation/tgstation/pull/54318

## Reproduction:
become blind, in pain, or otherwise vision impaired

Able to see completely fine as if not vision impaired/blind, alongside no ill effects past maybe Monochrome vision if its blindness.

**Comment by msgerbs** [comment]
Related to #54551 and #52972
