### ISSUE TITLE
You cannot pick up the janitor's pet lizard

### ISSUE THREAD

**Issue by Quiteanything** [tgstation/tgstation#54577]
## Reproduction: 
Walk over to janitor's pet lizard, Wags-His-Tail or something, and try to pick him up by pulling him and dragging him to you. This doesn't seem to work. I am very triggered by this as you can pick up nearly every other pet in the game. Wheres my pocket lizard??

**Comment by actioninja** [comment]
Please don't clog the tracker with joke issue reports.

**Comment by Pugie** [comment]
It isn't a joke.
