### ISSUE TITLE
HE Piping Not Processing Atmos Correctly

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#54578]
## Reproduction:

This was what clued me in when someone had issues with using HE's on top of floor tiles in the incinerator:

1). Place a HE containing gas onto a floor tiling, or some other flooring.
2). Expose it to space via an adjacent space tile.
3). See no change (or minimal change) in gas temp.

Also got these:

![atmosssssssss](https://user-images.githubusercontent.com/46318638/97066742-df880880-1585-11eb-800c-0922cd839c53.png)
![atmosssss](https://user-images.githubusercontent.com/46318638/97066743-e0209f00-1585-11eb-880f-da197e9e4c68.png)
![Atmossssssssssssssssss](https://user-images.githubusercontent.com/46318638/97066959-bf0c7e00-1586-11eb-85ca-5841f83675b7.png)

**Comment by LemonInTheDark** [comment]
Do you have a round id/testmerges? A picture of the setup would also help a bit

**Comment by Misdoubtful** [comment]
Round ID: 148957

Setup is easy to replicate. Just a HE on flooring with space adjacent is what I did. But these runtimes also came up for the SM HE's as well.

**Comment by Misdoubtful** [comment]
#54520 and #54552 were the TM's but I don't think they are related.

**Comment by Dennok** [comment]
About first part "Expose it to space via an adjacent space tile. See no change (or minimal change) in gas temp."
Work as intended. Tile that has no air cant get any heat capacity.
Space cooling work only in space.

Second part is bug of not propertly initialised space tiles.
space/basic dont initialise self and dont get air.
it must be replaced to space on some stage of map initialization
