### ISSUE TITLE
If someone steals your clown shoes, you will be permanently slowed down until you hold them in your hand

### ISSUE THREAD

**Issue by Jared-Fogle** [tgstation/tgstation#54576]
## Reproduction:
1. Wear clown shoes
2. Have someone else steal them from you (leg intent grab)
3. Notice that you are slowed down, even though you don't have them on
4. Take your shoes back
5. Notice that you go normal speed

**Comment by msgerbs** [comment]
Feature.

**Comment by ATH1909** [comment]
does this effect get undone if they pick up any other item, like, say, an oxygen tank? or does the item they need to pick up need to interact with the slowdown system in some way? or does the item they need to pick up need to be of the same kind as the item that was stolen from their feet slot? or does the item they need to pick up need to be the EXACT item that got stolen from them?

**Comment by msgerbs** [comment]
Wait how does that close this?

**Comment by Jared-Fogle** [comment]
@msgerbs well, its one way to solve it

i would guess that this just doesn't work with normal shoe stealing (with the inventory menu)

**Comment by msgerbs** [comment]
I'll take your word for it then, because I don't see where the intent-based shoe stealing calls any procs any differently than normal shoe stealing and I don't feel like testing it right now.
