### ISSUE TITLE
INSTRUMENTS BROKEN! Music does not play further than the tile you are on

### ISSUE THREAD

**Issue by wabash1** [tgstation/tgstation#54586]
## Round ID:
[149001](https://scrubby.melonmesa.com/round/149001)

## Testmerges:
#54483: 'Shuttle Takeoff/Landing Animations' by Cyberboss at commit d41ff11e10
#54552: 'Revert "Out of repo maps part 1: JSON Improvements"' by optimumtact at commit 89a1bb6b5f

## Reproduction:
Play any song on any instrument, including the standalone piano, you cannot hear it if you move off the tile the instrument is on, which means you cannot ever hear the standalone piano.

**Comment by ATH1909** [comment]
Does this affect the buffs from the musician quirk?

**Comment by wabash1** [comment]
Quirk still works for both player and listener. no audio though for listener. only the player gets the audio.

**Comment by Mickyan** [comment]
I think you borked it with audio falloff @Qustinnus

**Comment by Qustinnus** [comment]
I'd be surprised if this was only found now if its falloff, but i'll take a look.

**Comment by wabash1** [comment]
Let me know if I can help test this bug @Qustinnus

**Comment by wabash1** [comment]
@ATH1909 
 sorry forgot to set reply on my previous response to you.

@Qustinnus
I'm no coder but I was looking through the code changes for instruments and it looked like there's null values for what appears to be the falloff of the instruments

**Comment by Qustinnus** [comment]
null means that it will take the default value of the proc which is 6
