### ISSUE TITLE
MULTIZ engraved floor not showing properly

### ISSUE THREAD

**Issue by nightred** [tgstation/tgstation#54581]
Cult engraved floor does not render properly from above.

![image](https://user-images.githubusercontent.com/6491940/97083132-cf971580-15d3-11eb-9cf1-ae03ab75abd9.png)
![image](https://user-images.githubusercontent.com/6491940/97083139-d9207d80-15d3-11eb-859d-3d3601c7af37.png)

**Comment by Fikou** [comment]
feature, cult majik hides from virgin eyes
