### ISSUE TITLE
Action button drifted

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#54599]
## Testmerges:
- #54483 
- #54552 

## Reproduction:
1. Put on internals (but do not turn them on)
2. Get knocked unconscious
3. Spam the unusable internals button so you can turn it on as soon as you wake up
4. ![ActionButtonDesync](https://user-images.githubusercontent.com/53582584/97099036-1f5ff600-1641-11eb-9322-b6db9b9ce3ed.PNG)

**Comment by Jared-Fogle** [comment]
are you sure you didnt just accidentally mouse drag it?

**Comment by TemporalOroboros** [comment]
Apparently this is a thing.

**Comment by Jared-Fogle** [comment]
This is something I removed from vg [a long while back](https://github.com/vgstation-coders/vgstation13/pull/17546), I should probably port it here.

**Comment by Jared-Fogle** [comment]
hey wait a minute you guys already took it

https://github.com/tgstation/tgstation/pull/44658
