### ISSUE TITLE
Glasses sometimes don't represent their most common reagent.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#54596]
## Testmerges:
- #54483 
- #54552 

## Reproduction:
1. Acquire a drink shaker
2. Acquire two glasses
3. Insert 40 units of atomic bomb and 60 units of whisky (in that order) into the shaker
4. Pour 50 units of the mixed drinks from the shaker into each of the glasses 10 units at a time.
5. Notice that the glasses are taking on the appearance of the atomic bomb rather than the whisky.
6. Get another two glasses
7. Repeat steps 3 and 4 reversing the order of the atomic bomb and whisky in step 3 (but not the amounts)
8. Notice that it is now taking the appearance of the whisky.
9. Theorize that the glass is just taking the appearance of the first drink
10. Pour 5 units of a random drink, 60 units of ale, and 30 units of beer into the shaker and pour.
11. Be confused when the glass correctly displays the manly dorf sprite.

**Comment by Sealed101** [comment]
![изображение](https://github.com/user-attachments/assets/7c94b174-606a-4e0a-a33d-0139dd5cdd62)
seems to have been fixed, possibly by the big #69081
