### ISSUE TITLE
The characters "<>/\\" cannot be used in the modular computer chat client.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#54598]
## Testmerges:
- #54483 
- #54552 

## Reproduction:
1. Acquire a modular computer (tablet, laptop, or console)
2. Download the chat client
3. Open a channel
4. Attempt to post a message in the channel containing one or more of the characters "<>/\\"
5. Notice that nothing is posted.

**Comment by Dorsisdwarf** [comment]
Probbably an anti-fuckery code sanitisation thing

**Comment by Jared-Fogle** [comment]
it's a DUMB anti-fuckery code sanitization thing--Inferno almost definitely escapes characters on its own.
