### ISSUE TITLE
Entertainment monitors don't work

### ISSUE THREAD

**Issue by Cenrus** [tgstation/tgstation#54607]
## Reproduction:

1. Cause an entertainment monitor to go live by activating a motion sensitive camera in the thunderdome arena.

2. Teleport to the station and try examining or clicking on an entertainment monitor.

3. You expect to be able to see through cameras within the arena, but nothing happens.

**Comment by msgerbs** [comment]
Can confirm. I looked at this but didn't get around to finishing up a fix. I'll try and look at this again soon.

**Comment by Jared-Fogle** [comment]
before we fix this can we please do what we should've done in the beginning and make it so admins specifically choose to show it to the entertainment monitor?

otherwise people are going to be conditioned to expect boring testing shit

**Comment by msgerbs** [comment]
> 
> 
> before we fix this can we please do what we should've done in the beginning and make it so admins specifically choose to show it to the entertainment monitor?
> 
> otherwise people are going to be conditioned to expect boring testing shit

So like have a Game Admin verb to turn on entertainment monitors?

**Comment by Jared-Fogle** [comment]
or just like a button like how theres one to open the shutters

**Comment by msgerbs** [comment]
> 
> 
> or just like a button like how theres one to open the shutters
> 
> if you dont want something physical, it should prob be in secrets like the reset thunderdome command

I think a button to do it would end up being awful and snowflaky but I'll experiment with it.

**Comment by Jared-Fogle** [comment]
up to you, i just dont want it to be on by default

**Comment by ArcaneDefence** [comment]
Please don't close issues until they're actually fixed.
The pr mentioned doesn't "fully work" as stated by the author, and a maintainer has comments in this issue that are relevant to whether or not they'd accept a fix

**Comment by Googles-Hands** [comment]
Stop blocking people from fixing this, I need to watch admins ERP
