### ISSUE TITLE
Butchering a lesser ash drake revives the human that turned into a drake.

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#54602]
## Reproduction:

1. Become an ash drake via Dragon's blood( /obj/item/dragons_blood )
2. Get killed while transformed as a drake.
3. Have someone butcher your corpse(Requires a sharp object I believe, a kinetic crusher or an energy axe definitely work)
4. You get revived in human form.

**Comment by ATH1909** [comment]
Can they turn back into a lesser ash drake again?
