### ISSUE TITLE
fraxinella's head sprite is broken, again (after being fixed once)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#54615]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/97139361-53faad00-1728-11eb-8427-25418f9bc1e7.png)

fraxinella got a sprite a few months ago and it has worked since then, but some recent PR seems to have undone that.

rainbow bunch flowers may be broken too, since both were fixed in the same PR

**Comment by ArcaneMusic** [comment]
I cannot reproduce this. Both rainbow and Fraxinella headsprites appear to be working correctly on my local.
