### ISSUE TITLE
You can ANNIHILATE people with black magic and 50 glass tables

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#54626]
1. make a table frame
2. make another table frame next to it
3. drag one table frame onto another
4. repeat steps two and three until you have 50 table frames on one tile
5. use alt click to put glass on every table frame
6. table someone on your hyperdense glass table, watching as they break 50 tables in quick succession, killing them in seconds
7. repeat until the blood gods are sated

**Comment by TheBonded** [comment]
Feature

**Comment by TemporalOroboros** [comment]
Huh, someone finally decided to report this one.

**Comment by LemonInTheDark** [comment]
AHHHHHHHHHHHHH

I really hate machine/structure stacking, but it's a bitch to fix. Someone do it so I don't have to.

**Comment by msgerbs** [comment]
Alternatively make it so you can only smash 1 table at a time?

**Comment by XDTM** [comment]
>Alternatively make it so you can only smash 1 table at a time?

this isn't the first issue related stacking dense constructables, so ideally we should solve the issue at its root and prevent all similar future issues instead of only solving this specific case
