### ISSUE TITLE
Quantum Spin Inverters enable permanent GBJing with disposals

### ISSUE THREAD

**Issue by Spookuni** [tgstation/tgstation#54639]
## Testmerges:
#54590: 'Families 3.0: More Gangs, More Problems' by Iamgoofball at commit e2ff880d34
#54483: 'Shuttle Takeoff/Landing Animations' by Cyberboss at commit 1baeff0998

## Reproduction:
1. Climb into a disposal net
2. Activate a linked quantum spin inverter while in the disposals pipes
3. You will be teleported to the turf where the other spin inverter is held
4. You are now stuck in the turf, any attempt to move will just repetitively make the disposals clanging sound, and the only way out I've found so far is admin teleportation.

This can also be used offensively on a handcuffed target to permanently GBJ them by shoving a spin inverter in their pocket and activating it after you push them into disposals, trapping them forever unless an admin takes pity on them and gets them out.

**Comment by msgerbs** [comment]
What is GBJ?

**Comment by Tlaltecuhtli** [comment]
g** baby jail

**Comment by ATH1909** [comment]
What if you do this the other way, by throwing a quantum spin inverter into a disposals loop and then swapping to it?

**Comment by XDTM** [comment]
>This can also be used offensively on a handcuffed target to permanently GBJ them by shoving a spin inverter in their pocket and activating it after you push them into disposals, trapping them forever unless an admin takes pity on them and gets them out.

I suppose this was meant to be putting the spare QSI into the disposal, otherwise it would most likely just port the prisoner back out of the disposal tube

**Comment by ATH1909** [comment]
> > This can also be used offensively on a handcuffed target to permanently GBJ them by shoving a spin inverter in their pocket and activating it after you push them into disposals, trapping them forever unless an admin takes pity on them and gets them out.
> 
> I suppose this was meant to be putting the spare QSI into the disposal, otherwise it would most likely just port the prisoner back out of the disposal tube

Nah, teleporting them back out of the disposal tube while keeping their inability to move is the point of that trick.
