### ISSUE TITLE
Afterattack effects appear to have completely broken on several objects.

### ISSUE THREAD

**Issue by ArcaneMusic** [tgstation/tgstation#54638]
## Testmerges:
(54161 and 54483 but I'm not linking them because I'm 99% sure that they're not connected)

## Reproduction:
Produce a chilled bluespace slime crossbreed.
Attack a target (any intent) that you want to add to your teleport list.
It doesn't add the target to the allies list. (Regardless of intent). It also refuses to give a message saying that it doesn't apply on after-attack.

Seems it's not even getting to the after-attack proc anymore, leaving it to just useless splash against it's target. Adding force to make it properly attack also doesn't cause the crossbreed to apply. (tested separately)

**Comment by ArcaneDefence** [comment]
Caused by https://github.com/tgstation/tgstation/pull/54475
Additional things that no longer work properly because of the changes are all regenerative crossbreeds, chilling sepia, fulton packs, and rainbow knives.
