### ISSUE TITLE
New shuttle animations obscure landing lights and result in death. A LOT

### ISSUE THREAD

**Issue by Scorch262** [tgstation/tgstation#54641]
## Round ID:
[149149](https://scrubby.melonmesa.com/round/149149)

## Reproduction:

Me and several others were killed by the shuttle landing on us
the landing lights are similar in color to the shuttle floor and its difficult to tell when the shuttle has actually landed

**Comment by msgerbs** [comment]
#54483 is still testmerged, so this should be posted there instead. I'll copy it over but feel free to add additional feedback.
