### ISSUE TITLE
Data Huds Shifted Down One Tile For Monkies

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#54648]
## Reproduction:

1). Just look its literally upside down lol.

Zero idea what caused this, but its been recurring for more than just a few days.

![MONKE](https://user-images.githubusercontent.com/46318638/97327218-26f2eb00-184b-11eb-8ebe-836987e2e61e.png)

EDIT: Not sure if this applies to anything else, if it does I haven't noticed.

**Comment by Misdoubtful** [comment]
Wasn't paying attention when I first saw this.

This isn't actually upside down, the entire data-hud is shifted down one tile.

**Comment by dragomagol** [comment]
Should be fixed by #55614
