### ISSUE TITLE
meat floor weirdness

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#54653]
## Testmerges: #54483: 'Shuttle Takeoff/Landing Animations' by Cyberboss at commit 1baeff0998

meat floors have several weird properties that may or may not be buggy:

1) crowbarring a meat floor tile produces a stack of 0 meat. this is true even if you directly replace the meat floor tile with another tile by holding a crowbar in your other hand. i assume it's meant to either not give any stacks back like wood floors, or give 1 meat back like normal floors
2) hitting somebody with a meat floor tile deletes the tile. again this might be intended since i would imagine using a meat floor tile as a weapon wouldn't be very efficient but i'm including it anyway
3) replacing the escape shuttle floors with meat floors causes them to transform into pseudo-meat-floors when the shuttle takes off, by which i mean they turn into red floor tiles that don't make the funny squelchy noise. it's possible to replace them with normal meat floors again so i assume this is caused by the shuttle moving z-levels and removing the unique meat properties

t. someone who has spent 5 rounds making a meat bar

**Comment by cacogen** [comment]
Couple of other things I noticed:

* Material tiles don't have the correct number of custom_materials (they have 500, not 500 * amount)
* Splitting 1 material tile from a stack results in a generic material tile instead of one with 500 of the custom_material

**Comment by TemporalOroboros** [comment]
@cacogen 

All of these are caused by mats_per_unit not being set.

As a bonus: material floor tiles of different materials can stack and remove all the custom materials from the remaining stack.

**Comment by cacogen** [comment]
I was wanting to fix this but I'm not sure how to set that when a stack is built so I'll leave it to somebody else.
