### ISSUE TITLE
Broken Roulette Wheel

### ISSUE THREAD

**Issue by ShadowTheLion** [tgstation/tgstation#54651]
Issue reported from  Round ID: [149184](https://scrubby.melonmesa.com/round/149184) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1528

"
![Broken Wheel](https://user-images.githubusercontent.com/55414910/97351097-aee6ee00-1867-11eb-8d5f-e109a25636ca.PNG)

**Comment by Jared-Fogle** [comment]
Does this happen every time? Seems more like the CDN failed.

**Comment by Qustinnus** [comment]
Happend to me every time too when I played a bit back, and heard more reports about it.

More accurate repro is that a few buttons specifically always cause this for me.

**Comment by Qustinnus** [comment]
https://github.com/tgstation/tgstation/issues/54394 reported here too
