### ISSUE TITLE
Bounty pads leave behind the contents of a machine when taking it.

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#54654]
## Round ID:
Local

## Testmerges:
N/A

## Reproduction:
1) Get a bounty that asks for a machine (Emitter in this case but I imagine it works with all of them)
2) Turn in the bounty

Expected: Complete machine including contents is removed
Actual: Leaves behind the circuit board and any components used in its construction

**Comment by ArcaneMusic** [comment]
Heh, whoops.
This is likely an issue with qdel and destroy, if I had to guess.
