### ISSUE TITLE
Birdboat immediately starts dying roundstart

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#54657]
What it says on the tin. It seems as though almost every round, birdboat just mysteriously dies. A few times I've walked into the roundstart maint bar to find him in the process of dying or dead literally no reason.

He might be choking to death on something. He might just keel over and perish for seemingly no reason.

**Comment by brotherbeyondd** [comment]
maybe its for the best

**Comment by Misdoubtful** [comment]
I'm fairly certain its just Birdboat choking and dying on something in the room.

**Comment by GunHog** [comment]
Birdboat chokes when he eats something with plastic in it, with a chance to vomit instead. Get to him quickly if you want him to live!

**Comment by ArcaneDefence** [comment]
Last I knew birdboat could eat the posters in the room.
