### ISSUE TITLE
at least one of the possible assistant roundstart spawn locations on pubby is in the center of the chapel satellite

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#54664]
<img width="1440" alt="vampinstadeath" src="https://user-images.githubusercontent.com/42606352/97433287-42153780-18eb-11eb-832d-a53e72c6a8bf.PNG">

This is bad for vampire assistants who don't batform ASAP.

**Comment by ATH1909** [comment]
<img width="1434" alt="vampinstadeath2" src="https://user-images.githubusercontent.com/42606352/97433688-e5fee300-18eb-11eb-9cf9-51d2549a77cd.PNG">

Bonus bug: For some reason, even though I had seen the ashes of a fire-cremated plasmaman in the previous round, my fire-cremation stopped after removing an arm and a leg and stayed at that "stage" for 20+ minutes (out of my 30+ minutes of being dead in the chapel (because that chaplain in the image AND a curator who walked by later AND the person who dragged me deeper into the chapel later to meatspike me ALL didn't bother trying to drag me to Medbay, or even report my death) before Exavere intervened).

<img width="394" alt="vampinstadeath3" src="https://user-images.githubusercontent.com/42606352/97433719-f2833b80-18eb-11eb-8155-1430d28fbf60.PNG">

I took some health readings of myself while I was in that "missing only two limbs" state, and I don't believe I noticed a damage jump between any of them.

**Comment by msgerbs** [comment]
I'm not familiar with vampires, why is this bad for them?

**Comment by TheBonded** [comment]
> I'm not familiar with vampires, why is this bad for them?

@msgerbs When vampires enter the chapel, they spontaneously combust and die pretty fast

**Comment by msgerbs** [comment]
Oh snap. Alright.

**Comment by msgerbs** [comment]
Wow, uh, Pubby sucks for vampires. The asteroid is a huge chunk of the station off-limits to them.

**Comment by Jared-Fogle** [comment]
lmao
