### ISSUE TITLE
Spamming the flashlight on and off crashes the game (client side)

### ISSUE THREAD

**Issue by TheBonded** [tgstation/tgstation#54669]
## Testmerges:
#54521 (merged)

## Reproduction:
1. Get flashlight
2. Turn it on and off
3. Wonder how fast you can make it do the clicky noise
4A. Set a macro to spam the Z key really fast
4B. (Optional alternative to 4A) Get good at pushing the Z key or clicking the flashlight fast
5. Hear the really fast clicky noise for a few seconds
6. Crash

**Comment by Mooshimi** [comment]
wha-

**Comment by san7890** [comment]
this isn't a BYOND issue at all, the client will get kicked (`qdel`'d) for flooding keysends in `keyDown()`

we might need to make the message more apparent but this is not a bug (not really sympathetic towards people to abuse macros like this).
