### ISSUE TITLE
pea soup does not need a bowl, but drops a bowl for trash (infinite bowwwwls!! the economy!!)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#54678]
## Round ID:

[149269](https://scrubby.melonmesa.com/round/149269)

## Reproduction:
![image](https://user-images.githubusercontent.com/51863163/97532422-4b9eae00-1984-11eb-8774-045f70d1a7b3.png)

Pea soup, when crafted, does not consume a bowl, but it is a soup, so by default it has trash of a bowl, creating INFINITE BOWLS.

**Comment by necromanceranne** [comment]
It's as simple as adding the bowl to the ingrediants. I'll tag @TheObserver-sys but honestly this is also an easy fix for someone else to do too.
