### ISSUE TITLE
nightmare lighteater not disabling lights on people

### ISSUE THREAD

**Issue by token-map** [tgstation/tgstation#54675]
## Round ID: 
[149265](https://scrubby.melonmesa.com/round/149265)

## Testmerges:
The following pull requests are currently test merged:
#54590: 'Families 3.0: More Gangs, More Problems' by Iamgoofball at commit e2ff880d34
#54483: 'Shuttle Takeoff/Landing Animations' by Cyberboss at commit 1baeff0998

## Reproduction:
title. as nightmare, hitting someone with lights on with the light eater will not disable their lights. possibly related to the lighting rework?

**Comment by ArcaneDefence** [comment]
This is a duplicate of this https://github.com/tgstation/tgstation/issues/54638

**Comment by ArcaneMusic** [comment]
Resolved.

**Comment by EOBGames** [comment]
taking arcane's word for it
