### ISSUE TITLE
Mech repair droids don't repair short circuit internal damage

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#54682]
## Description:

Short circuits aren't repairable by the mecha repair droids which are already very rare to find on a combat mech due to how little they actually repair (about 0.3% per tick for a 400 health durand, IIRC.). A balance would be if they only repaired short circuiting if the mech was manually or otherwise repaired to 90% or more of its health (which is unlikely during combat), so the problem wouldn't instantly go away if you had a droid.

## Reproduction:
Step 1: Spawn a mech, spawn one or two repair droids
Step 2: Induce a short circuit internal failure on the mech
Step 3: Hop inside, activate the repair droids
Step 4: Watch in despair as your battery power and hull integrity continue to drop until you explode and gib

**Comment by zxaber** [comment]
I don't think repair droids fix any of the random malfunction events. Pretty sure they're only for basic hull damage.

You fix short circuit by opening up the mech's power cell compartment and using a coil of wire.

**Comment by githubuser4141** [comment]
> I don't think repair droids fix any of the random malfunction events. Pretty sure they're only for basic hull damage.
> 
> You fix short circuit by opening up the mech's power cell compartment and using a coil of wire.

I mean, from the description: ""An automated repair droid for exosuits. Scans for damage and repairs it. Can fix almost all types of external or internal damage.""

I'm not sure, but I think it can repair faulty temperature controllers (?) and breached gas tanks, so I'm not sure why it couldn't fix a faulty wire.
