### ISSUE TITLE
Unable to examine anything as a dullahan head, additionally dullahans can't use headsets

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#54685]
## Reproduction:
Step 1: Spawn as a dullahan, you'll have two heads (?)
Step 2: Toggle the perspective button a few times, otherwise you won't have the dullahan nerf at all and can dispose of the heads
Step 3: Using your primary head (the other head doesn't do anything) try to shift click on something to examine it, nothing will happen. If you use your blind body to examine stuff, it will fail because you're technically blind.

**Comment by Tharcoonvagh** [comment]
Dullahans are fucking broken man
