### ISSUE TITLE
Roller shutters open for anyone who walks into them with a vehicle/mech

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#54686]
## Reproduction:
Step 1: Spawn a vehicle, such as a scooter or a mech.
Step 2: Drop your ID just for good measure
Step 3: Walk into a closed roller shutter, it should open right up for you even if you lack a proper ID which I'm pretty sure isn't supposed to happen.

## Description:
Button-controlled shutters can be magically opened by simply walking into them with anything from a mech to a common scooter.

EDIT: Also works like this for fire doors, not sure if that's intended or not.

**Comment by ATH1909** [comment]
looks like this is another way to get into that juicy, juicy deathsquad gear room as a lowly ERT member

**Comment by zxaber** [comment]
Hmm, possibly an unintended outcome of changing mechs to use bumpopen() rather than Bumped(). However, for airlocked, bumpopen() does an ID check before just opening, so I'm not sure why shutters just allow access.

**Comment by cacogen** [comment]
The problem is not that mechs aren't looking for access on shutters, the problem is that shutters don't have access themselves because they've never needed it before (this has been handled by the button),
