### ISSUE TITLE
Sealed mechs don't protect their passengers from snowstorms (Icebox)

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#54688]
## Reproduction:
Step 1: Spawn a sealed mech (Gygax, Durand, Ripley Mk II, etc)
Step 2: Make sure it's icebox and step outside in said sealed mech. Wait for a snowstorm...
Step 3: Turn your mech internals on knowing you're safe in your sealed life support pod. Actually die because of ??? reasons that sealed, pressurized mechs don't protect passengers from snowstorms.

## Description: 

Sealed mechs with onboard life support and pressurization don't do anything to protect their crew from snowstorms. This doesn't make sense that a pressurized mech can protect someone from a raging plasmafire but a snowstorm will kill them in minutes. It's a pressurized metal can with it's own internal air system, that probably shouldn't happen?

**Comment by Sealed101** [comment]
fixed in #76367
