### ISSUE TITLE
Vampire's bat form is unbalanced

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#54703]
## Description: 

Being able to join as a non-antag vampire is pretty horrifically unbalanced as the bat form allows you to bypass any airlocks or security measures (save for welding both scrubbers and vents shut) and immediately loot high-security areas with little risk. At the cost of having to drain a monkey (no, not even a monkey man) every hour or so, you get to: Ventcrawl to your heart's desires, wriggle out of stuns or handcuffs by turning into a bat, zip across the entire station in a few seconds in the vents or simply hide from antagonists/lynch mobs until the round is over. I'm sure a dedicated powergame could do a lot worse, but that's just what I've been able to do.

## Reproduction:
Step 1: Join as vampire on any halloween TG server
Step 2: Use bat form to immediately gain access to the cap's office and armory, loot them dry without anybody ever batting an eye
Step 3: Hide from the lynch mob in a vent somewhere until the round ends

**Comment by hermitec** [comment]
Agreed but I think nobody cares because it's only enabled for like 2 days a year

**Comment by Pugie** [comment]
hahaha
WEAK energy
Halloween is warden's idea of Christmas where all their presents are free valids in armoury.

**Comment by hermitec** [comment]
the problem here is playing warden

**Comment by necromanceranne** [comment]
The amount of bats popping in vents has been amazingly funny but fuck batform

**Comment by Tlaltecuhtli** [comment]
if bats are being a problem you can valid them and no admin will ever side with vampires

**Comment by Fikou** [comment]
cannot reproduce
