### ISSUE TITLE
Mech operators on the default keybind prefs cannot use alt in strafe mode to turn

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#54727]
## Round ID:
Tested on local

## Reproduction:
![image](https://user-images.githubusercontent.com/51932756/97793197-576db880-1bae-11eb-9322-eaccfd924ac5.png)

Reset your keybinds to default, which puts block movement on alt
Hop in a mech
toggle strafe mode, tooltip tells you to use alt to temporarily disable it
alt locks you in place because of blocked movement

**Comment by TiviPlus** [comment]
#notmyproblem blame whomever made alt the default movement block key instead of ctrl
