### ISSUE TITLE
mechs fly over open space

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#54722]
they dont fall down

**Comment by Dennok** [comment]
Omg. Mechas [`anchored = TRUE`](https://github.com/tgstation/tgstation/blob/515ea1b6b2563c45e8a922616ae54587233d52ae/code/modules/vehicles/mecha/_mecha.dm#L29) and it block it from falling.

**Comment by zxaber** [comment]
I can't believe the anchored flag survived the mech refactor.

**Comment by Ghommie** [comment]
Somebody must have readded the anchored var when they refactored mechs, cause I did recall fixing this issue long time ago already.
