### ISSUE TITLE
Bottlers Delete Chems

### ISSUE THREAD

**Issue by IcePacks** [tgstation/tgstation#54728]
If you discovered this issue from playing tgstation hosted servers:
[Round ID]:One of the handful of rounds an ancient chemical being creates a bottler

## Reproduction:

1. Create a bottler and understand how it works (there is literally zero instructions on how this works on the wiki, so good luck!)
1b. Kidding just leave a bunch of beakers on the opposite side of the input and it fills them
2. Click on the bottler when it has chems in it
3. Set it to 100 or something I dunno
4. My chems! They're gone!

This is an absolute bitch if you have a public bottler machine; if the dumbass moron crew isn't picking up the beaker feed to your bottler and trying to fill it (slowly) directly from the bottler you can be sure they'll be fiddling around with it, guaranteeing its non-productivity as long as anyone is around it

**Comment by Tlaltecuhtli** [comment]
thats intended behaviour but i can change it
