### ISSUE TITLE
You can use krav maga in mechs

### ISSUE THREAD

**Issue by Pugie** [tgstation/tgstation#54726]
title

**Comment by ArcaneDefence** [comment]
Mechs aren't respecting shift click or control click. They'll attack/fire when you intend to examine, bashing things while adjacent. If you don't use ctrl click it won't let you use the krav maga actions.

**Comment by necromanceranne** [comment]
This is basically a bug described here rearing it's ugly head once more. https://github.com/tgstation/tgstation/issues/47753

This needs to be fixed, at which point this is no longer possible.

**Comment by ATH1909** [comment]
I personally think that control+click activating krav maga moves is fine- the issue here seems to be that the control+click grab "attack" is working while you're in a mech.

**Comment by necromanceranne** [comment]
Wait hold on. If you can do this in a mech, that means you're using krav maga while you have the no handuse trait.

Oh boy. Time to go test shit

**Comment by Pugie** [comment]
This was fixed ages ago by the mech refactor
