### ISSUE TITLE
Seed vault vendors need money to get seeds and equipment

### ISSUE THREAD

**Issue by henriquekill9576** [tgstation/tgstation#54738]
## Round ID:

If you discovered this issue from playing tgstation hosted servers:
[Round ID]: [149478](https://scrubby.melonmesa.com/round/149478) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1536

## Reproduction:

1. Spawn in a seed vault;
2. Try to interact with the vendors;
3. Watch as it will require money that you don't have or can't get easily in order to get seed/equipment.

**Comment by ArcaneMusic** [comment]
This was on the lavaland seed vault, correct?
By default, vending machines don't cost money when interacted with off z-level, and for this reason this behavior is maintained.
I wonder if this has to do with that change to seed vendors on the second floor of Icebox?

**Comment by henriquekill9576** [comment]
Yep, this was on lavaland seed vault

**Comment by kriskog** [comment]
vendors should have an offstation variable that makes them free

**Comment by kriskog** [comment]
Current master has these working just fine, they are free as expected. The only conceivable way I can see of this happening is if someone deconstructed one and put it back together again as that clears the offstation var. If that cannot have been the case, let me know and I will reopen this.
