### ISSUE TITLE
Chaplain's null rod gets stuck permanently in belt slots

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#54746]
## Round ID:
Reproduced on local

## Testmerges:
None

## Reproduction:
Be a chaplain, choose a null rod variant that permanently attaches itself to your hand (armblade, god hand, chainsaw etc.). Have an empty belt slot. Hit the equip hotkey on it and have it attach itself permanently to your belt with a broken sprite.

**Comment by necromanceranne** [comment]
Yeah this is my fault. I'll fix it in a tick.

**Comment by TheBonded** [comment]
what happens if you take off your jumpsuit? that removes everything from your belt slot, what would happen? I know this is getting fixed but I'm still curious

**Comment by dragomagol** [comment]
It stays in your belt slot, even though you don't technically have a belt slot.
