### ISSUE TITLE
When you access a TGUI panel once, it can't be reopened once closed (not always but usually)

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#54754]
Basically, try to open up a TGUI panel like the crafting menu. Once you close it again, you can no longer open it again that round until you restart the entire game. There is no workaround except for a restart that I'm aware of and has no relation to https://github.com/tgstation/tgstation/issues/54378 as far as I can tell, so it's not a turf issue.

This affects only TGUI, as all other windows appear to appropriately open. This is especially true of the Orbit window, which is when I first noticed it and has always broken consistently every time I've used it.

I didn't think to report this until I heard other people say they've experienced it as well.

**Comment by Cyprex** [comment]
For UIs that you can force close by, e.g. walking away from a PDA or other such device, does this usually help where this is possible? If so, a verb could be added that force-closes the windows serverside could be added as a workaround.

**Comment by zxaber** [comment]
I have this exact same issue except with non-tgui screens. All tgui screens work fine, but most of the time I get to view one non-tgui screen once and then have to quit and rejoin to see it again. Until then, it's a blank white window.

**Comment by Cyprex** [comment]
That sounds crippling, how do you play like this?

**Comment by XDTM** [comment]
I wonder if it's in some way related to the fact that minimized windows stay minimized after closing/reopening them.

**Comment by necromanceranne** [comment]
pretty sure this isn't a problem currently
