### ISSUE TITLE
you can still make super stacked tables

### ISSUE THREAD

**Issue by TheBonded** [tgstation/tgstation#54761]
## Testmerges: 
#54702 #54666 

## Reproduction:
I didn't see how they did it, because this should have been fixed, but somehow zoey hayhurst made a stacked glass table in departures and almost instakilled the HoS. perhaps look at the .txt files to figure out what they did to do this

**Comment by LemonInTheDark** [comment]
AHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by ArcaneDefence** [comment]
![image](https://user-images.githubusercontent.com/51932756/97921183-d3374480-1d17-11eb-9d25-1bd33c23f75c.png)
All you gotta do is drag the table frame into a stack and then add the glass to the stacked frames. Not complicated in any way.

**Comment by YPOQ** [comment]
The linked round is on commit 583af81a  which is before the fix in 2a69506

**Comment by dragomagol** [comment]
I just tried it with up to date code and it doesn't seem to work. You can stack table frames, but when you try to build a second table on the same tile it tells you "There's already a table built here!"

**Comment by ATH1909** [comment]
> I just tried it with up to date code and it doesn't seem to work. You can stack table frames, but when you try to build a second table on the same tile it tells you "There's already a table built here!"

aw

**Comment by Fikou** [comment]
as YPOQ says, the pr was not in yet
