### ISSUE TITLE
directional lights will squeak things that normally squeak when stepped on, like rubber ducks

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#54777]
Recreation steps:

1) Get a rubber ducky. Quack.

2) Shine a torch on it.

3) Look away and then towards the duck. It'll quack.

**Comment by Ghommie** [comment]
That's one hell of a jumpscare sound. :clown_face:

**Comment by Fikou** [comment]
u can walk over a rubber duck as a slaughter demon when jaunting

**Comment by brotherbeyondd** [comment]
And mice!

**Comment by TheBonded** [comment]
Fun fact, this is ONLY activated by PDA lights.
