### ISSUE TITLE
Pda messages don't always send properly.

### ISSUE THREAD

**Issue by Boggart** [tgstation/tgstation#5478]
Sometimes you'll hit send on a pda message and you'll get: "Unable to reach recipient."
Then you try again and it works. It's annoying to lose longer messages and it seems to happen randomly. Nothing was wrong with telecomms at any of the points I've had this happen.

**Comment by Mervill** [comment]
@optimumtact closeable - https://www.youtube.com/watch?v=-abUtRbUS_U
