### ISSUE TITLE
No xray on new AI upgraded cams

### ISSUE THREAD

**Issue by Losenis** [tgstation/tgstation#54803]
Issue reported from  Round ID: [149686](https://scrubby.melonmesa.com/round/149686) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1536

Cams built after AI receives combat software upgrade don't inherit xray properties

**Comment by timothymtorres** [comment]
Pretty sure this was fixed by #64188
