### ISSUE TITLE
AI core deleted when AI-piloted mech dies.

### ISSUE THREAD

**Issue by Okshi91** [tgstation/tgstation#54819]
Issue reported from  Round ID: [149713](https://scrubby.melonmesa.com/round/149713) (/tg/Station Basil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1532

When an AI-piloted mech dies, the empty core at the AI's old position is deleted and the AI subsequently dies.

To reproduce:
1: Be AI
2: Enter a mech that has an AI control beacon.
3: Destroy the mech
4: Discover that you are dead and the place where your old core was is empty.

**Comment by brotherbeyondd** [comment]
I believe you can use an intellicard on the mech to recover it, no?

**Comment by brotherbeyondd** [comment]
Wait actually mechs are qdel'd when they break for some reason lol

**Comment by GunHog** [comment]
The AI was intended to die with the mech, and instead be recoverable from the wreck. The mecha refactor removed that feature, unfortunately. The bug here would then be the old core being deleted - it should just remain as a blank that can just be reloaded with a new brain.

**Comment by ATH1909** [comment]
> The AI was intended to die with the mech, and instead be recoverable from the wreck. The mecha refactor removed that feature, unfortunately. The bug here would then be the old core being deleted - it should just remain as a blank that can just be reloaded with a new brain.

I thought that that was just for dominated mechs? I wasn't too familiar with the feature, though.

**Comment by GunHog** [comment]
AIs using the Mech Domination power are locked into that mech and are intended to die with it (Unless it consents to being carded) - at the time, AI mech beacons were not a thing and Malf AI was still its own game mode. I imagined it as an alternative to shunting - it is cooler for the AI to take the fight to the crew in the Durand they built to kill it, rather than it hiding in an APC, waiting to be found.

AI Mech beacons were added later, and that feature is the one permits the AI to eject from the mech. AIs uploaded via card or hacking cannot return to the core, but ones uploaded via the AI beacon may eject at any time. This could do with some updating, though.

**TL;DR: Mech dies, AI dies. The only bug is the old core being deleted.**

**Comment by zxaber** [comment]
To make things more clear:

- Malf AIs can force-pilot a mech after obtaining the Mech Domination ability. This is a one-way trip and is presumably intended to act like the AI shunted into the mech.
- Normal AIs can pilot any mech that has an AI beacon and is empty. The AI can leave afterwards and thus presumably is intended to act like remote-controlling the mech.

This bug report mentions the beacon, so I don't think the AI is intended to be dying.

**Comment by GunHog** [comment]
> Normal AIs can pilot any mech that has an AI beacon and is empty. The AI can leave afterwards and thus presumably is intended to act like remote-controlling the mech.

The AI is uploaded into the mech's computer in all three cases (Transmitted to mech as malf, via the beacon, or directly loaded by card). Control is local. Not to be confused with AI shells, which are remote controlled. You can card an AI in all cases should the AI permit it by enabling maintenance mode, which is intended.

That being said, I agree with returning the AI to its core upon mech destruction due to the refactor removing generation of wreckage.

**Comment by Okshi91** [comment]
> Normal AIs can pilot any mech that has an AI beacon and is empty. The AI can leave afterwards and thus presumably is intended to act like remote-controlling the mech.

I would like to add that, when the AI dies, they receive the message "Returning to core", which also implies that the AI beacon is intended to act like remote control, at least in terms of what happens when the mech is destroyed. I should also mention that the message is displayed after the AIs death is broadcast to deadchat.

**Comment by GunHog** [comment]
> > Normal AIs can pilot any mech that has an AI beacon and is empty. The AI can leave afterwards and thus presumably is intended to act like remote-controlling the mech.
> 
> I would like to add that, when the AI dies, they receive the message "Returning to core", which also implies that the AI beacon is intended to act like remote control, at least in terms of what happens when the mech is destroyed. I should also mention that the message is displayed after the AIs death is broadcast to deadchat.

That behavior appears to be a minor oversight resulting from this: https://github.com/tgstation/tgstation/blob/a93200f577d27a0c46aee235346acdd46221dd17/code/modules/vehicles/mecha/_mecha.dm#L1083-L1084
and this:
https://github.com/tgstation/tgstation/blob/a93200f577d27a0c46aee235346acdd46221dd17/code/modules/vehicles/mecha/_mecha.dm#L202-L206
causing this to be called without first clearing the `linked_core` variable:
https://github.com/tgstation/tgstation/blob/a93200f577d27a0c46aee235346acdd46221dd17/code/modules/vehicles/mecha/_mecha.dm#L1037-L1062

`Mob_Exit()` gets triggered when the AI is killed (gibbed as of the refactor) with the mech, which is what is deleting the old core. The normal ejection process physically moves the AI mob back to the location of the duplicate "inactive" core created when the AI uploaded itself to the mech, then deletes the "inactive core". 

I believe this can be addressed by either:
Clearing `linked_core` from the AI before gibbing it or by returning the AI to its core once the mech is destroyed.

Mechanics/lore wise, the AI is considered to be running inside the mecha's computer system. The AI can be carded from the mech regardless of how it got there, and if the AI's core is destroyed, the AI will continue to function, as it is physically located in the mech; The AI simply maintains a data link to its old core should it need to return. This differs from AI shells, which are instead considered remote controlled.

**Comment by zxaber** [comment]
I think the main takeaway is that I should rewrite how AI beacons work.
