### ISSUE TITLE
mind swap mysteriously stops working mid-round

### ISSUE THREAD

**Issue by UzedPickle** [tgstation/tgstation#54828]
Issue reported from  Round ID: [149744](https://scrubby.melonmesa.com/round/149744) (/tg/Station Basil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1534

I was a wizard with mindswap and after mindswap working fine multiple times it activated but didn't actually swap me then after failing to swap again I was unable to cast it.

**Comment by timothymtorres** [comment]
Mindswapping into certain mobs breaks the spell.  I believe this also happens to mines since they need to verbally say the spell out loud.

From the logs it appears you had shapeshifter into a juggernaut.
