### ISSUE TITLE
Gondolapods seem to not send items correctly

### ISSUE THREAD

**Issue by MrDoomBringer** [tgstation/tgstation#54830]
Issue reported from  Round ID: [149750](https://scrubby.melonmesa.com/round/149750) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1536

MrAlphonzo brought this up with me during a round where he couldn't seem to launch crates with gondolapods. The other pod styles worked, however

**Comment by MrDoomBringer** [comment]
Testmerges:
#54379: '[WIP] Remove fusion from reactions, add hypertorus fusion machinery' by Ghilker at commit e10435e721
#54483: 'Shuttle Takeoff/Landing Animations' by Cyberboss at commit 02225b37e3
#54550: 'Humans have more complicated body temperatures' by nightred at commit 675dc6c59a

**Comment by Sealed101** [comment]
fixed by https://github.com/tgstation/tgstation/pull/78900 apparently
