### ISSUE TITLE
'AI Detector Eye' shows up on orbit list, can't actually be orbitted

### ISSUE THREAD

**Issue by MrDoomBringer** [tgstation/tgstation#54832]
Issue reported from  Round ID: [149750](https://scrubby.melonmesa.com/round/149750) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1536
my guess is the AI detection multitool makes a dummy AI eye that gets on the POI list but can't actually be orbitted
![image](https://user-images.githubusercontent.com/29008542/98307819-b52a4800-1f94-11eb-9540-df40bf712f21.png)

**Comment by Sealed101** [comment]
- the AI detector eye does not spawn in-game outside adminbus since #68301. the AI detector eye is still present in the code though but otherwise it doesn't appear anywhere

**Comment by MrDoomBringer** [comment]
we did it
