### ISSUE TITLE
Ninja suit permanent cooldown.

### ISSUE THREAD

**Issue by Winterous** [tgstation/tgstation#54859]
## Round ID: [149848](https://scrubby.melonmesa.com/round/149848)

Possibly related to https://github.com/tgstation/tgstation/pull/53492 @IndieanaJones 
I got hit by a disabler while cloaked, this put my suit on permanent cooldown. I disabled and reenabled the suit, I charged on apcs, I waited a long time, but every time I tried to use a suit ability it just said "suit on cooldown"; it was like 20 minutes I think from first having it disabled till I died.

**Comment by Dorsisdwarf** [comment]
pretty nasty bug, ouch

**Comment by Winterous** [comment]
How do you add tags like that by the way?

**Comment by IndieanaJones** [comment]
Bugfix shortly.
