### ISSUE TITLE
Extradimensional Blade, the null rod, works really poorly.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#54853]
Here is the relevant code:

```
/obj/item/nullrod/claymore/multiverse
	name = "extradimensional blade"
	desc = "Once the harbinger of an interdimensional war, its sharpness fluctuates wildly."
	icon_state = "multiverse"
	inhand_icon_state = "multiverse"
	worn_icon_state = "multiverse"
	slot_flags = ITEM_SLOT_BACK

/obj/item/nullrod/claymore/multiverse/attack(mob/living/carbon/M, mob/living/carbon/user)
	force = rand(1, 30)
	..()
```
As you can see, the extradimensional blade does a few things:

**1) It permanently changes the force of the sword.**

Every time the sword attacks, the force of the weapon is rolled between 1 and 30. This is as expected, but it isn't just for the sake of this attack. It actually permanently sets the force of the weapon. Normally, the weapon starts at 18, just like any other nullrod, but this is overwritten by the attack roll.

**2) This only rolls when you strike a carbon.**
Therefore it only rolls when you hit; monkeys, xenos, humans.

It does not roll when you hit silicons or structures, or simple animals.

**3) You can game the extradimensional blade by hitting monkeyhumans/corpses to get a high roll, and become a silicon/locker/airlock/corgi slaying beast.**

As a result of this, your nullrod becomes significantly more powerful if you make sure never to hit a carbon after you get your high roll. You can use this blade to tide practically anywhere with your new esword level weapon. you can put into suit storage.

**Comment by ATH1909** [comment]
It should be noted that atheist fedoras have a throwforce of 30 right off the bat (but a terrible normal force to compensate), so a null rod with the ability to deal 30 damage isn't TOO special.

However, yeah, this is an interesting/notable bug. Question, though- how do you tell when you've high-rolled? Do you just hit airlocks and stuff to check to see if you've passed their damage threshold(s)?

**Comment by Ghommie** [comment]
You are right, except `item/proc/attack()` is called for all living mobs, not just carbons.
