### ISSUE TITLE
vampire mimes can't shapeshift without breaking their vow

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#54862]
it's a species ability, why should it require the ability to speak?

**Comment by brotherbeyondd** [comment]
down with vampire mimes

**Comment by timothymtorres** [comment]
The spell for shapeshifting requires spoken words.  I wonder if this affects mimes involving all the wizards spells since they must be spoken.

**Comment by JohnFulpWillard** [comment]
This isn't a problem anymore since vampires don't have shapeshift anymore
