### ISSUE TITLE
Hijack announcements are not working properly

### ISSUE THREAD

**Issue by itseasytosee** [tgstation/tgstation#54871]
"< font color='red' >< b >SYSTEM OVERRIDE< /b >"
is part of the message that shows up instead of system override in red text.

msg = "<font color='red'><b>SYSTEM OVERRIDE</b></font> - Resetting course to \[[scramble_message_replace_chars("###########", 100)]\] \

I don't think announcements even support different colors of texts.

**Comment by msgerbs** [comment]
They do not. The entire message is html encoded before being announced. Additionally, the entire message gets passed into the scramble function, HTML and all, so even if it wasn't being escaped automatically, there's a chance the scrambling would just break the HTML anyway.

**Comment by Jared-Fogle** [comment]
i kinda figured this was intentional

**Comment by itseasytosee** [comment]
if it is it looks bad and is hard to read. If you want the text to be messed up you are better off using garbled characters and pound signs

**Comment by necromanceranne** [comment]
Biggest shrug, better to yell at @silicons about this one.
