### ISSUE TITLE
You can whisper into comms in crit.

### ISSUE THREAD

**Issue by Pugie** [tgstation/tgstation#54878]
Caused by https://github.com/tgstation/tgstation/pull/53117?

Dunno if this is intended or not.

**Comment by brotherbeyondd** [comment]
Oh it was due to a refactor? Of course it bloody was. Please say it's unintended since playing cult just means accidental murderbone since you cant just crit and convert.

**Comment by MrMelbert** [comment]
this wasn't caused by #53117, it was caused by #51790, it was discussed a bit in the discord back in July (that's how old this issue is) and the general consensus was it's fine-ish until it gets abused

**Comment by ATH1909** [comment]
> Oh it was due to a refactor? Of course it bloody was. Please say it's unintended since playing cult just means accidental murderbone since you cant just crit and convert.

bro just use the gamer hand

**Comment by brotherbeyondd** [comment]
Use the gamer hand but then you have to take headset off? hello? cant do that when dragging??

**Comment by necromanceranne** [comment]
Shadow shackles keeps them muted.

**Comment by cacogen** [comment]
But it should be.

**Comment by gitbirb** [comment]
This is HELL to deal with as any antagonist, as it is abused massively. Hope it gets fixed soon.

**Comment by wesoda25** [comment]
Personally love this, if it’s fixed maybe we can try a feature PR for it once November is over

**Comment by LemonInTheDark** [comment]
It was a side effect of my saycode refactor yeah, the maints at the time were alright with it so long as no major abuse goes down. might be worth making crit make messages more scattered or something.
