### ISSUE TITLE
Removable dish drive components

### ISSUE THREAD

**Issue by Losenis** [tgstation/tgstation#54884]
Issue reported from  Round ID: [149916](https://scrubby.melonmesa.com/round/149916) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1536

You can remove the glass, bins, manipulator, and even the board from a Dish Drive without it losing function by clicking it like how you'd remove plates.

**Comment by msgerbs** [comment]
Beautiful.

**Comment by cacogen** [comment]
The whole is greater than the sum of its parts
