### ISSUE TITLE
Invalid argument. at http://127.0.0.1:51420/tmp8080/browseroutput.html:1 ...

### ISSUE THREAD

**Issue by Theo1996** [tgstation/tgstation#54893]
## Round ID:

 80 kiwistation

## Reproduction:

Just installed byond ad opened kiwistation and the chat? NTOS? pops up with this error:

`
          _____            _____                  _______                  _____
         /\    \          /\    \                /::\    \                /\    \
        /::\____\        /::\    \              /::::\    \              /::\    \
       /::::|   |        \:::\    \            /::::::\    \            /::::\    \
      /:::::|   |         \:::\    \          /::::::::\    \          /::::::\    \
     /::::::|   |          \:::\    \        /:::/~~\:::\    \        /:::/\:::\    \
    /:::/|::|   |           \:::\    \      /:::/    \:::\    \      /:::/__\:::\    \
   /:::/ |::|   |           /::::\    \    /:::/    / \:::\    \     \:::\   \:::\    \
  /:::/  |::|   | _____    /::::::\    \  /:::/____/   \:::\____\  ___\:::\   \:::\    \
 /:::/   |::|   |/\    \  /:::/\:::\    \|:::|    |     |:::|    |/\   \:::\   \:::\    \
/:: /    |::|   /::\____\/:::/  \:::\____\:::|____|     |:::|    /::\   \:::\   \:::\____\
\::/    /|::|  /:::/    /:::/    \::/    /\:::\    \   /:::/    /\:::\   \:::\   \::/    /
 \/____/ |::| /:::/    /:::/    / \/____/  \:::\    \ /:::/    /  \:::\   \:::\   \/____/
         |::|/:::/    /:::/    /            \:::\    /:::/    /    \:::\   \:::\    \
         |::::::/    /:::/    /              \:::\__/:::/    /      \:::\   \:::\____\
         |:::::/    /\::/    /                \::::::::/    /        \:::\  /:::/    /
         |::::/    /  \/____/                  \::::::/    /          \:::\/:::/    /
         /:::/    /                             \::::/    /            \::::::/    /
        /:::/    /                               \::/____/              \::::/    /
        \::/    /                                                        \::/    /
         \/____/                                                          \/____/
 
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Please remain calm. Get to the nearest NTNet workstation and send the copy of the following stack trace to: www.github.com/tgstation/tgstation. Thank you for your cooperation.
 Invalid argument.
   at http://127.0.0.1:51420/tmp8080/browseroutput.html:1
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET4.0C; .NET4.0E; AskTbATU3/5.15.4.23821; Media Center PC 6.0; .NET CLR 3.5.30729; .NET CLR 3.0.30729)
State: {"ckey":"tio1996","window":{"fancy":0,"locked":0}} 
Nanotrasen (c) 2525-2559 `

**Comment by Dorsisdwarf** [comment]
Kiwistation runs a modified codebase, so this issue isn't appropriate to post here. I recommend advising the kiwistation team to update their config to point at their own github/gitlab et cetera.
