### ISSUE TITLE
datum material problem #4389349, 2 type of metal floor tile recipe exist in crafting menu

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#54898]
one is inherited by datum materials and is unusable in recipes and has different color  other is obj/item/stack/tile/plasteel which is usable in recipes

**Comment by cacogen** [comment]
Yeah I see this daily and didn't think to report it just unconsciously dismissing it as a lesser bug of this blessed system that won't get fixed

**Comment by ArcaneMusic** [comment]
Well, I don't think this is a bug, moreso a consistency issue. One is a roughly hewn plate of a full material, where the other is a crafted piece of flooring.
...That said, the generic named floor tiles should have a better stack-crafting name. It _is_ very difficult to tell which is which.

**Comment by cacogen** [comment]
Unless I'm mistaken the end goal is for the datum material objects to take the place of the current ones. But they don't yet all look the same or have the same functionality. So we get this misleading duplication.

**Comment by ArcaneMusic** [comment]
Closed by #56207.
