### ISSUE TITLE
You can trashbag of holding intercomms off the walls.

### ISSUE THREAD

**Issue by DemonOfHatred** [tgstation/tgstation#54908]

**Comment by dragomagol** [comment]
I'm not entirely sure this was meant for our server since our round numbers are in the 150000s. I was also unable to reproduce this on local.

**Comment by ArcaneMusic** [comment]
Same, can't reproduce locally. Are you sure this was on /tg/ and not like, fulp or bee?
![image](https://user-images.githubusercontent.com/41715314/98722641-4fa4d580-235f-11eb-90ea-ff603dedab15.png)

**Comment by BootlegBow** [comment]
wouldn't of been fulp, their round number are up past 10000

**Comment by Time-Green** [comment]
@DemonOfHatred We can't really do much with this. I recommend you issue it to the servers github or find a way to reproduce it on /tg/ and make a new issue
