### ISSUE TITLE
Old Medibot keep trying to heal toxin when it can't

### ISSUE THREAD

**Issue by Nikitaw99** [tgstation/tgstation#54904]
Issue reported from  Round ID: [149992](https://scrubby.melonmesa.com/round/149992) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1527

I was out exploring space. Stumbled upon this "Authorship" thing, it had an old medibot. It kept trying to heal me up for a few minutes but didn't seem to do anything. An admin told me that it was trying to heal my toxin damage, but could only heal brute.

![image](https://user-images.githubusercontent.com/16986290/98599446-67477400-22f5-11eb-98a5-2786d184999e.png)

**Comment by necromanceranne** [comment]
Memory of a time lost.
