### ISSUE TITLE
Datum material wood floor tiles lack wood texture 

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#54917]
## Round ID:
#150093

## Testmerges:
#54702 #54483 #54379

## Reproduction:

1. Unintentionally make datum material wood floor tiles instead of regular wood floor tiles in sheet construction menu for wood planks
2. Observe the different object sprite and turf sprite for them (plain brown)

**Comment by nullAdept** [comment]
same with tables and chairs

**Comment by dragomagol** [comment]
Textured wood tables would actually be pretty neat.
