### ISSUE TITLE
placing walls doesnt add the turf it was replacing to the baseturf list

### ISSUE THREAD

**Issue by Kylerace** [tgstation/tgstation#54918]
## Reproduction:
1. place wall on an open turf, like carpet
2. that turf might have a baseturf list that looks like 1 = baseturf_bottom 2= plating
3. placing the wall will not change the baseturf list at all, even though it should add the original turf to the new baseturf list
4. removing the wall will show that the turf that was originally on top is now deleted

**Comment by LemonInTheDark** [comment]
here we go again

**Comment by ATH1909** [comment]
> here we go again

on our own~

**Comment by Kylerace** [comment]
bug fixed somewhere along the line
