### ISSUE TITLE
Cell chargers, when they draw from APCs, do not actually update the APC that it needs to replenish power, so they brick them until the cell is replaced.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#54919]
~~@ATH1909  was completely right and charging cells in most rooms just guts a rooms charge. Even just normal high capacity cells. Most APCS just cannot handle charge values of higher cells, and they don't recharge from the power lines quick enough to actually reasonably keep up with the demand of the cell chargers.~~

~~Basically, revert https://github.com/tgstation/tgstation/pull/54886 and replace it with a direct wire connection for charging like emitters, or just wait until a complete power overhaul.~~

~~@ArcaneMusic this one is something you should be aware of. Not only is drain completely fucked, power distribution is too, and this problem likely isn't fixable during a feature freeze unless it's really goddamn critical.~~

All of the above is actually still true and the net isn't capable of properly handling cell drainage, but there is in fact a deeper issue at play here that is contributing.

Cell chargers are drawing from the APCS but never updating them, so unless something else significantly impacts the APC enough to force it to drain power and reduce the APC's charge, like a microwave or something, it won't ever update and is essentially bricked.

![apc full but not](https://user-images.githubusercontent.com/40847847/98873827-273ae980-24cd-11eb-9c6d-3893ddca3c21.png)

![bricked apc](https://user-images.githubusercontent.com/40847847/98873957-6bc68500-24cd-11eb-9f54-b17defb9eff1.png)

The last APC is completely bricked until the cell is replaced.

If it is replaced and something does actually force it to start recharging, you can actually cause it to infinitely recharge, and therefore be able to infinitely charge the cells you have in the cell charger.

![infinite recharge](https://user-images.githubusercontent.com/40847847/98874311-2060a680-24ce-11eb-9269-7e633de8753d.png)

**Comment by optimumtact** [comment]
suck it up and adjust

**Comment by necromanceranne** [comment]
There are ways around it but they're basically the exact same problem Arcane wanted to fix and not the actual method you're supposed to use to recharge power cells, and just using other machinery instead. They're also not difficult to pull off and don't sap APCs.

The problem might be that cell charger capacitor upgrades are demanding too much from the APC at once, since those I think are what determines how much the cell is charging by per drain.

**Comment by necromanceranne** [comment]
Nevermind the problem is deeper rooted. I've updated the body of this issue.

**Comment by cacogen** [comment]
Someone in OOC summed up the issue (minus the APC bricking) basically as: "Imagine taking a cell charger with a bluespace power cell from area to area and draining every APC." I don't know if there is a way to adapt to this without using other means that haven't been rebalanced to match to circumvent it.

**Comment by necromanceranne** [comment]
Anyway as another clarification on the cell drainage:

Since APCs are recharging at a 1% rate per second, which is a apparently the fixed rate cells in APCs will always charge by, and a high capacity cell (the ones you print roundstart) in an unupgraded cell charger drains 10% of a roundstart APC cell's capacity per second only to charge the cell by 25%, no APC on the station is even reasonably capable of dealing with the power demands of cells roundstart, and none are capable even if you upgraded the cells in the APC.

A roundstart APC cell has a maximum capacity of 2.5k, so we might as well not even consider that a factor as it's being recharged (if this was working properly) at a rate of 1% per tick or 25 watts per tick, and always being drained by an unupgraded cell charger at a rate of 250 watts (2.5% of a high capacity cell), nearly 10 times the demand on the cell. 

If we replace this cell with a high capacity, the cell charge rate is therefore 100, and now it's manageable. somewhat, This is also consistent when you upgrade the APC cell and the cell chargers to their tier 4. 

With a quadratic, the cell charge is at a rate of 1000 watts per tick (2.5% of our bluespaces 40k), and a bluespace cell charges at a rate of 400 per tick (1%). So you'll get roughly the consistent results if you were to charge a high capacity cell with a high capacity APC. However, if the APC cell is ever lower than the one you're charging, upgrades in the cell charger are almost always worse since it starts choking the APC more. It also takes a near equal amount of time waiting for the APC to replenish as it does to actually charge a single cell in a cell charger. You might actually be better off charging the cell in an APC, in fact, since you won't have as many issues with bottlenecking.

The amount of power in the grid never influences this APC charge rate, so all excess power goes entirely to waste.

More or less, the take away here is that the cell recharger PR does make sense only if the APC cells are of equal value to the cells being used to charge. Since that isn't the case, it breaks down significantly, and the bottlenecks in place for APCS can be abused to render sections of the station inoperable by placing cell chargers in them with roundstart upgrades.

If the high-capacity cell was the gold standard for the station's APCs, then this is probably not an issue, just kind of going to make cell charging reeeeeeally slow. And nothing that engineering can do will influence this whatsoever besides upgrading the cells whenever possible if it's in a room they're upgrading.

**Comment by carshalash** [comment]
This is, really easy to grief with. Holy fuck.

**Comment by Losenis** [comment]
There hasn't been a round I've played engi in that I've not gotten called over a blackout only to find someone tried to recharge a cell. It's getting ridiculous.

**Comment by Cyberboss** [comment]
I just looked at APC code and it is literally fucking stupid

**Comment by Donkie** [comment]
I have a pretty big power, apc and SMES refactoring and cleanup in the making in the power-update branch of my fork https://github.com/Donkie/tgstation 
What im trying to achieve:
- Fix issues like this, machinery should draw from grid first then apc
- Properly discern between power and energy (hint: they are not the same thing!)
- Properly utilize delta_time
- Get rid of the stupid CELLRATE constant and all confusion that stems from it

Been put on hold abit due to lazyness but if you guys think it looks promising i could finish it
