### ISSUE TITLE
Delta station has no Russian revolver

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#54920]
Literally unplayable.

**Comment by LemonInTheDark** [comment]
Feature request, and in a feature freeze none the less (Is this a feature? is it a mapping change? who knows!)

**Comment by redguy999** [comment]
if i had known about the feature freeze, i won't have done this, sorry.

**Comment by LemonInTheDark** [comment]
it's not a big deal, feel free to add it yourself in december, the mapping tool is easy enough to use for small stuff like this.
Ask in discord if ya need any pointers.
