### ISSUE TITLE
Cyborgs can't refill their materials from loose materials anymore

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#54931]
## Round ID:
Reproduced on local

## Reproduction:
Be a cyborg, place floortiles on plating, crowbar them up, find that you can't refill your floortiles with the ones you just placed by clicking on them with the floortile module. Same for cable coils, metal, and glass.

**Comment by TemporalOroboros** [comment]
I think this one's me, probably. I'll see what I can do.

**Comment by TemporalOroboros** [comment]
@dragomagol PR's up. It should be fixed when a maintainer deigns to merge it.
