### ISSUE TITLE
You cannot drop a picked-up snail backpack.

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#54933]
## Reproduction:
Have a snail person suicide, gibbing themself or whatever, and pick up their backpack. It will be stuck to your hand.
I haven't tried putting it on my backpack slot, (sounded like a BAD IDEA.) but hovering over it gave a green outline.

**Comment by Dorsisdwarf** [comment]
Looks like someone forgot to give snail backpacks that one flag that makes nodrop items delete themselves if forcibly dropped, like golem clothes
