### ISSUE TITLE
Pubby chemlab misplaced wall.

### ISSUE THREAD

**Issue by Winterous** [tgstation/tgstation#54955]
The front desks of chemlab in pubby, the east-most desk has a wall overlapping it.

**Comment by Winterous** [comment]
I still don't know how to apply labels to PRs and issues :(

**Comment by LemonInTheDark** [comment]
If you're an issue manager there's a wheel next to the labels tab on the right, click on the ones you want to apply.

Also lol.

**Comment by dragomagol** [comment]
Closed by #54588
