### ISSUE TITLE
(Regal)Rats Unaffected by Mouse Traps

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#54962]
## Reproduction:

1). Get a `/mob/living/simple_animal/hostile/rat` or `/mob/living/simple_animal/hostile/regalrat`
2). Get a `/obj/item/assembly/mousetrap/armed`
4). Cower in fear as the (regal)rat beats its arch nemesis, walking right over its certain doom unfazed.

Thats what I get for using mousetraps instead of rat-traps.

Haven't taken the time to look but, I wager the (regal)rat targeting of the triggering proc ain't working correctly.

**Comment by ArcaneMusic** [comment]
Funny enough, I added interactions for triggering mouse traps on mice, rats, and regal rats, but It turns out I wasn't checking for the on the mouse trap's trigger side.
Whoops!
