### ISSUE TITLE
Metallic hydrogen axes are missing right handed icons

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#54972]
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
Lmao, just put it in your right hand and it's invisible, because there's no `metalh2_axe0` or `metalh2_axe1` in axes_righthand.dmi and I'm not going to do it because I'd rather eat rocks than try to figure out how to draw something someone else made

**Comment by TheBonded** [comment]
just mirror the left hand sprite

**Comment by itseasytosee** [comment]
my bad ill take care of it.
