### ISSUE TITLE
Gunpowder grenades don't work

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#54986]
## Testmerges:
- #54804 
- #54702 
- #54632 

## Reproduction:
1. Fill two large beakers with gunpowder
2. Heat the beakers to 470&deg;K
3. Create a grenade using the two beakers.
4. Prime and throw the grenade.
5. Watch as the grenade disappears and there is a deafening lack of explosion

**Comment by ArcaneMusic** [comment]
That... doesn't seem inconsistent.
Gunpowder explodes at 474 kelvin, not 470.

**Comment by brotherbeyondd** [comment]
@ArcaneMusic no he's not wrong. The grenade increases the temperature slightly, even if it's not a thermal one.

ALSO I happened to try this not long ago and as gunpowder has a delayed explosion time, it explodes where the beaker is. And as the beaker isn't in existence when the grenade "explodes", it doesn't explode.

**Comment by Winterous** [comment]
Yeah I think this is because the grenade deletes itself upon detonation, deleting the temporary reagent container that the gunpowder is in. The same thing happens if you heat a bottle of gunpowder and it gets destroyed before exploding; it's just a callback attached to the reagent container.

**Comment by antropod** [comment]
normal grenade heats up reagents by 10K
