### ISSUE TITLE
Raw HTML in orbit menu entries

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#54985]
## Testmerges:
- #54804 
- #54702 
- #54632 

## Reproduction:
1. Have something you can orbit with a \<span\> in the name.
2. Open the orbit menu
3. ![html-in-orbit-menu](https://user-images.githubusercontent.com/53582584/99196959-42fbf500-2744-11eb-811b-4a09afda5aeb.PNG)

**Comment by ATH1909** [comment]
oh boy

now the question is

can you use this to display images?

**Comment by TheBonded** [comment]
> oh boy
> 
> now the question is
> 
> can you use this to display images?

please tell me you are planning on testing this

**Comment by Jared-Fogle** [comment]
@ATH1909 the answer is absolutely not because inferno requires an explicit unsafe setting to not encode html. this is because it is good

**Comment by SpaceManiac** [comment]
for anyone wanting to fix this in a real way, whatever code put HTML tags into the `name` variable is wrong. HTML tags **can't** go there, they will not and can never show correctly in the bottom-left status bar or in the right-click menu

**Comment by Jared-Fogle** [comment]
Honestly it's hard for me to even really say this is a bug, considering this was an admin intervention.

**Comment by SpaceManiac** [comment]
our game is not built to allow HTML in the name var and it would be a herculean effort to change that, admins put HTML there at their own risk
