### ISSUE TITLE
Emagged/hacked APCs might be immune to singularities

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#54984]
## Testmerges:
- #54804 
- #54702 
- #54632 

## Reproduction:
1. Singloose on the northern half of pubby
2. Watch the singulo pull in and consume several APCs
3. Watch some APCs be both unmoved and unscathed despite getting directly moved over by the black hole
4. Notice that the immune APCs all have dark blue screens.
![blue-singlo-apcs](https://user-images.githubusercontent.com/53582584/99197102-3b891b80-2745-11eb-93f7-e51999e402fe.PNG)

**Comment by ArcaneMusic** [comment]
Possible related issue:
#49546
