### ISSUE TITLE
APCs and other wall mounts can have the walls removed from beneath them and remain completely unaffected.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#54983]
## Testmerges:
- #54804 
- #54702 
- #54632 

## Reproduction:
1. Singloose
2. Watch the wall disintegrate from underneath an APC and absolutely nothing happen to the APC
3. Watch the APC get dragged across the plating hovering in mid-air

**Comment by BootlegBow** [comment]
This also happens when you dismantle or blow up walls, not just singulo

**Comment by Sealed101** [comment]
this needs to be decided upon whether it's a feature to make reconstructing efforts easier or a consistency issue

**Comment by Sealed101** [comment]
see
- #22283
- wall-nerds/wallening#90
