### ISSUE TITLE
Upgraded Cybernetic Stomachs make eating do nothing

### ISSUE THREAD

**Issue by Shikarego** [tgstation/tgstation#54995]
I suspect this is about new nutrition? Or rather, how things now move from the stomach to the bloodstream? Basically, I had two patients come in saying eating does nothing, they could eat the same piece of food forever and not get less hungry. In one case, a nutriment patch helped, in another case it did not. In the second case, I installed a Nutriment Pump PLUS and that fed them up.
Both patients had Upgraded Cybernetic Stomachs. For the first case, I tried swapping it for a newly printed Upgraded Cybernetic Stomach-- no effect.

Issue reported from  Round ID: [150397](https://scrubby.melonmesa.com/round/150397) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1534

**Comment by Shikarego** [comment]
So I just upgraded someone's stomach and tried to feed them potassium... The amount of potassium in the beaker never decreased.

**Comment by nightred** [comment]
I am looking in to this.

**Comment by brotherbeyondd** [comment]
hi looking into this im dad

**Comment by TheBonded** [comment]
> So I just upgraded someone's stomach and tried to feed them potassium... The amount of potassium in the beaker never decreased.

fill em up with 10000 units of stable TaTP and give 'em a beaker of superheated ClF3. suicide bombing at it's peak
