### ISSUE TITLE
Moths have teeth and so do flies.

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#55009]
## Round ID:
//////

## Testmerges:
//////

## Reproduction:
Shoot a moth or a fly with a pulse rifle.
Make them get a burn wound.
![image](https://user-images.githubusercontent.com/68032262/99369322-31395f80-28b4-11eb-9ee2-115878f8088c.png)
Why do they have teeth?

**Comment by Dorsisdwarf** [comment]
Tagged as a bug issue

**Comment by brotherbeyondd** [comment]
hah... bug...

**Comment by maxymax13** [comment]
![image](https://user-images.githubusercontent.com/38844529/99393251-d572d480-28bb-11eb-8ff7-64fcfdc58088.png)
feature

**Comment by ATH1909** [comment]
cursed

**Comment by hermitec** [comment]
> ![image](https://user-images.githubusercontent.com/38844529/99393251-d572d480-28bb-11eb-8ff7-64fcfdc58088.png)
> feature

good lord

**Comment by Dorsisdwarf** [comment]
Just discovered that moths are not actually bugs

**Comment by redguy999** [comment]
> Just discovered that moths are not actually bugs

then what the heck are they?

**Comment by brotherbeyondd** [comment]
@Dorsisdwarf arent flies bugs, though? Therefore this should have not a bug AND bug.
