### ISSUE TITLE
Xenomorphs resin is nonfunctional

### ISSUE THREAD

**Issue by rellyreri** [tgstation/tgstation#55006]
Issue reported from  Round ID: [150439](https://scrubby.melonmesa.com/round/150439) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1536

Xenomorphs do not heal or produce plasma when standing on resin

**Comment by Livrah** [comment]
Slow plasma regeneration without resin floor doesnt work too
