### ISSUE TITLE
if it ever becomes possible to uninstall individual KA upgrades from a PKA (instead of all of them at once), AoE upgrades could prove to be problematic

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#55004]
```
/obj/item/borg/upgrade/modkit/aoe/install(obj/item/gun/energy/kinetic_accelerator/KA, mob/user)
	. = ..()
	if(.)
		for(var/obj/item/borg/upgrade/modkit/aoe/AOE in KA.modkits) //make sure only one of the aoe modules has values if somebody has multiple
			if(AOE.stats_stolen || AOE == src)
				continue
			modifier += AOE.modifier //take its modifiers
			AOE.modifier = 0
			turf_aoe += AOE.turf_aoe
			AOE.turf_aoe = FALSE
			AOE.stats_stolen = TRUE

/obj/item/borg/upgrade/modkit/aoe/uninstall(obj/item/gun/energy/kinetic_accelerator/KA)
	..()
	modifier = initial(modifier) //get our modifiers back
	turf_aoe = initial(turf_aoe)
	stats_stolen = FALSE
```
basically, if at some point someone in the future adds a way to remove individual PKA upgrades (say, as a feature for cyborgs to pop out their own upgrades using their tablets or something), you could theoretically repeatedly install and uninstall an AoE upgrade into your PKA to add that PKA upgrade's stats (ASIDE from its cost) to the stats of all of the other AoE upgrades in that PKA, allowing you to achieve something absurd like a x1000 PKA AoE damage multiplier.

in short, this isn't a problem NOW, but it COULD become one in the FUTURE, and when that happens, I want to be able to link back to this issue and say "I called it!".

**Comment by ArcaneDefence** [comment]
> in short, this isn't a problem NOW, but it COULD become one in the FUTURE

So it's not an issue.

**Comment by TheBonded** [comment]
> > in short, this isn't a problem NOW, but it COULD become one in the FUTURE
> 
> So it's not an issue.

that's like saying "Smoking causes cancer, but that's not an issue because I don't have cancer yet."
why not fix this before it becomes an issue?

**Comment by BarrelOfNapkins** [comment]
Because smoking is an issue? A better hypothetical would be, "Being around vampires causes cancer, but that's not an issue because vampires don't exist"

**Comment by TheBonded** [comment]
> Because smoking is an issue? A better hypothetical would be, "Being around vampires causes cancer, but that's not an issue because vampires don't exist"

sure, but in that example while you don't smoke, you would get cancer if you started smoking, and while it doesn't exist for you at the time due to lack of smoking, You might start smoking in the future.

**Comment by LemonInTheDark** [comment]
If you want to refactor KA upgrades feel free, but potential code breakages are not bugs.
