### ISSUE TITLE
Stomach damage vomit chance includes stomach's food reagent.

### ISSUE THREAD

**Issue by Winterous** [tgstation/tgstation#55000]
## Round ID:
[150414](https://scrubby.melonmesa.com/round/150414)

I was fighting bubblegum and suddenly vomited, I hadn't eaten anything in quite some time, and the message connected to the vomit was "your stomach reels in pain as you fail to hold down all that food" or thereabouts.
Stomach should have been empty, therefore shouldn't have vomited, right?

@nightred

**Comment by brotherbeyondd** [comment]
Something similar happened to another person when also fighting megafauna. Did you happen to use a luxury medipen?

**Comment by Winterous** [comment]
Yes the penthrite is what was causing stomach damage.
