### ISSUE TITLE
grilling shorts damaged? icon is missing icon

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#55011]

**Comment by Dorsisdwarf** [comment]
I hate issues where you do this.

**Comment by brotherbeyondd** [comment]
![image](https://user-images.githubusercontent.com/68032262/99417997-72e8fb00-28f2-11eb-9521-4705ad51765e.png)

**Comment by brotherbeyondd** [comment]
![image](https://user-images.githubusercontent.com/68032262/100077622-7a505d00-2e3a-11eb-9df8-4344a3cb8af2.png)

**Comment by ArcaneDefence** [comment]
Follow the issue report format

**Comment by ArcaneDefence** [comment]
Finally found the actual issue, being that there's no alternate icon state for it being adjusted to be worn casually.
icon_state = "cookjorts_d"
