### ISSUE TITLE
Spaghetti is too large for the pockets

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#55015]
## Round ID:
/////

## Testmerges:
/////

## Reproduction:
Spaghetti is too large for pockets!!
It's normal sized and pockets are NOT normal sized!!!!
![image](https://user-images.githubusercontent.com/68032262/99414169-77abb000-28ee-11eb-8cda-2ae4bdb291be.png)
How can spaghetti fall out of our pockets if its too large to be inside of them??????
![image](https://user-images.githubusercontent.com/68032262/99414318-9ad65f80-28ee-11eb-9f5a-e437d267c29a.png)
They weep for their children; let them fall as all good things should.

**Comment by dragomagol** [comment]
Where will I put my spaghetti now?

**Comment by brotherbeyondd** [comment]
Not in your pockets!!!!!

**Comment by necromanceranne** [comment]
Just make them smaller

**Comment by brotherbeyondd** [comment]
thank you oh wise necromanceranne.

please someone do its actually a good idea ive been saying for a while they used to be tiny please coders

**Comment by Ghommie** [comment]
Did you actually reproduce this issue?
The pocket weight class checks can't be reached if the `ITEM_SLOT_POCKETS` bitflags are enabled in `item_flags` so, since the spill component enables those flags in `RegisterWithParent()`, this issue shouldn't subsist.
