### ISSUE TITLE
Welders fuel usage is massively inconsistent

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#55018]
This is partially related to this issue https://github.com/tgstation/tgstation/issues/49664

So while welders definitely expend fuel when you click on an open tile, even if they do nothing, it seems to not expend fuel when you;

Weld a wall
Weld airlocks
Weld lockers
Break things (sometimes)

And a few other minor instances.

It seems entirely inconsistent about this too. It seems to be spending fuel whenever you use them on open turfs or when heating beakers which might be hardcoded to expend fuel, but then several other interactions use no fuel at all.

**Comment by TheBonded** [comment]
what if they just used fuel when on? something like 1 fuel for every 3-10 seconds.

**Comment by Losenis** [comment]
Fuel usage per time rather than per use might fuck up [Balans] for some things, like welding multiple walls/reinforced glass at the same time or combat against blob where you're attacking near-constantly with multiple other people also doing the same thing.

**Comment by timothymtorres** [comment]
@TheBonded this might also be an easy issue to fix.
