### ISSUE TITLE
Runtime in /obj/machinery/power/apc/process: Cannot read null.requires_power

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#55019]
## Round ID:
Local testing

## Testmerges:
n/a

## Reproduction:

1. Admin spawn APC unintentionally in space
2. Watch as Visual Studio ruins your testing by continuously rehalting the game process each time this runtime is triggered, which happens faster than you can delete the APC causing it

The problem is here:
https://github.com/tgstation/tgstation/blob/48161ba1b24d39bd1b65d2119bc031ff3318da6d/code/modules/power/apc.dm#L1185-L1186

I think it just needs:
```
	if(area && !area.requires_power)
		return
```

**Comment by zxaber** [comment]
You'd want

`if(!area || !area.requires_power)
    return`

That is, if there's no area *or* the area doesn't require power, then return.
