### ISSUE TITLE
When an AI controls a mech using an AI control beacon, both left and middle clicking perform normal AI functions.

### ISSUE THREAD

**Issue by nikothedude** [tgstation/tgstation#55047]
## Round ID: 
[150564](https://scrubby.melonmesa.com/round/150564)

## Testmerges: 
Add debug info for client time timers #54702 Shuttle Takeoff/Landing Animations #54483 

## Reproduction:
Step 1: Build a mech.
Step 2: Add a laser gun or something.
Step 3: Attach an AI beacon.
Step 4: Somehow become an AI.
Step 5: Switch to the weapon and middle click on a firelock. Pout as the firelock closes and the xenomorph gutting the assistant in front of you is unharmed.

**Comment by Tlaltecuhtli** [comment]
ai in a mech having ai powers by middle click is intended
were you an ai or not?

**Comment by Dorsisdwarf** [comment]
What else would middle-click do? Dont you fire the mech guns with regular inputs?

**Comment by nikothedude** [comment]
Normally, middle click fires guns with middle click, with an AI beacon. It even appears in huge blue lettering that middle click are for mech functions. And no, even if that WAS the intention, Dorsis, it doesnt do that. BOTH left click and middle click do normal AI functions. In practice, this makes AI beacons mostly useless, because all the AI can do is use mech systems like the durand shield.

**Comment by nikothedude** [comment]
And yes, I was an AI. Again, both left and middle click perform standard AI actions.

**Comment by Dorsisdwarf** [comment]
Ah I see
