### ISSUE TITLE
Dish drive ejects contents when clicked

### ISSUE THREAD

**Issue by JoshAdamPowell** [tgstation/tgstation#55044]
Issue reported from  Round ID: [150553](https://scrubby.melonmesa.com/round/150553) (/tg/Station - Terry [EU] [100% LAG FREE])

Reporting client version: 513.1533

Build a dishdrive, click it, it will eject glass, the micro manipulators, the disk drive machine board and the matter bins. Allows you to duplicate them for free

**Comment by MrMelbert** [comment]
#54884 related issue
