### ISSUE TITLE
*point both points and tells you you can't point

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#55056]
## Testmerges:
- #54778 
- #54702 

## Reproduction:
1. *point
2. ![point glitch](https://user-images.githubusercontent.com/53582584/99741562-58e02180-2a86-11eb-9912-4c9d790ede5a.PNG)

**Comment by ATH1909** [comment]
schrodinger's point

**Comment by Jared-Fogle** [comment]
![image](https://user-images.githubusercontent.com/35135081/99870483-23236180-2b88-11eb-94fc-dce310a441d5.png)
