### ISSUE TITLE
You can't wear corgis as a hat [Consistency issue]

### ISSUE THREAD

**Issue by TheBonded** [tgstation/tgstation#55052]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
1. Find a corgi (Steal Ian, Buy a corgi crate, ask xenobio, use that strange object that spawns corgis, or bug the chemist into making you life)
2. Pull the corgi
3. Drag the corgi's sprite to your own while you have an open hand
4. Think you can wear it as a hat like pAI holochasis and try to put the corgi on your head
5. Be sad when you can't wear your corgi on your head
6. Be confused that you can wear pAIs but not corgis
7. Go to the bar and drink yourself to death because you are depressed you can't wear a corgi on your head

**Comment by TheBonded** [comment]
I guess this applies to all simplemob pets

**Comment by ArcaneMusic** [comment]
PAis are an exception, not a rule, since 99% of simplemobs wouldn't work as a hat.
The only thing even tangentially related is mice existing in chef's hats, but that's again, an exception, since it exists in storage.

**Comment by MimicFaux** [comment]
> The only thing even tangentially related is mice existing in chef's hats, but that's again, an exception, since it exists in storage.

TIL mice can be stored in the chef hat.

**Comment by LemonInTheDark** [comment]
Not a bug

**Comment by ATH1909** [comment]
> Not a bug

But this is still an issue.

**Comment by LemonInTheDark** [comment]
is it?

**Comment by ATH1909** [comment]
> is it?

I wanna wear a dog on my head, damnit.

**Comment by BootlegBow** [comment]
Yeah, why can't I wear a dog as a hat?

**Comment by LemonInTheDark** [comment]
Cause none's coded it yet, one of you should do it in december.

**Comment by MrDoomBringer** [comment]
does anyone know why we have 1.6K issues
