### ISSUE TITLE
Flavour is forever

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#55084]
## Round ID:
/////

## Testmerges:
/////

## Reproduction:
Eat any food then wait like, thirty minutes or whatever.
Eat a different piece of food and still taste the sweet flavour of the donut you ate roundstart.

Flavour doesn't disappear after the reagents in your stomach have gone, so you'll still get the flavourtext (heh) for a donut along side the watermelon you just ate.

**Comment by ATH1909** [comment]
damnit nightred

**Comment by Bawhoppen** [comment]
guess we need to add toothbrushes and mouthwash as the only possible fix

**Comment by TemporalOroboros** [comment]
My best guess it that the nutriment from the food and the nutriment from the stomach's edible component are merging and mixing the flavors and that's interfering with taste somehow.

This might be a red herring, but it's a decent enough place to start looking.

**Comment by BootlegBow** [comment]
"You eat the watermelon"
"You taste cheese, meat and a little sugar"

**Comment by Qustinnus** [comment]
this isn't newfood
