### ISSUE TITLE
Health Analyzers Don't Report Chems

### ISSUE THREAD

**Issue by sqnztb** [tgstation/tgstation#55085]
## Testmerges: 
Shuttle Takeoff/Landing Anims, assuming not relevant.

## Reproduction: 
Inject/ingest chems, scan with health analyzer. No chem content readouts, just the "You analyze Suchandsuch's vitals." Was using the standard health analyzer, not the advanced. Unsure if reproduced with the advanced.

Edit: This also seems to impact ghost chem scan.

https://i.gyazo.com/6b848181fb82bd0b75de244cfa1a5611.png

**Comment by TemporalOroboros** [comment]
@sqnztb The health analyzers functions were split into modes a while ago. Either use in it in hand or alt click it and it should switch the mode to health/reagent/wound scan.

**Comment by sqnztb** [comment]
Yep. I'm aware. Check the screenshot. I attempt to scan myself four times, get nothing. Switch to wounds, no wounds. Switch to physical health, get physical health readout. Switch to chem contents, get nothing.

**Comment by ATH1909** [comment]
damnit nightred
