### ISSUE TITLE
Elite Corpses can Immediately Disappear after Killed

### ISSUE THREAD

**Issue by Taylorkills2** [tgstation/tgstation#55093]
## Reproduction:
I made the elite sentient, it was a Herald. Fought it was normal, but instead used my katana to deal the final strike on the Herald killing it. It's death animation played however after it died the body disappeared. 
Perhaps the katana caused it, but it could be something else.

**Comment by ArcaneMusic** [comment]
Well, the big tell here is going to be what the icon state ended up as after being killed.

**Comment by Taylorkills2** [comment]
No idea, it just dissapeared.
Jones said it's probably something to do with the Katana.

**Comment by Fikou** [comment]
theres nothing special about that katana that would cause this

**Comment by TheBonded** [comment]
Unable to reproduce this, I don't think it happens anymore.
