### ISSUE TITLE
action buttons not working

### ISSUE THREAD

**Issue by rekuli** [tgstation/tgstation#55115]
only the 1st action button on top left works,any other doesnt work when i click on them. i have to move them somewhere else to get them to work.

here's a short video of it:
https://cdn.discordapp.com/attachments/543879244594413618/780148621974568980/actioniscoming.mp4
you can also find the video in the #help channel posted by neverendingdelusions

**Comment by Fikou** [comment]
this was an extremely laggy adminbus round, are you experiencing this in any other round?

**Comment by rekuli** [comment]
yes it doesnt change from server to server.
