### ISSUE TITLE
AmpCheck incompatible with all available computer parts

### ISSUE THREAD

**Issue by Mirino97** [tgstation/tgstation#55113]
Pretty simple issue: Laptops and Tablets can download but can't execute the AmpCheck program since it counts as Incompatible, even though it has the sensor package, and I tried every other part as well.
## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:

1: Open Tablet
2: Download AmpCheck with correct credentials
3: Receive error "The laptop flashes a "Hardware Error - Incompatible software" warning.
4: Try all other computer parts
5: Repeat

**Comment by stylemistake** [comment]
Not a bug, it must be a stationary console connected to the power grid in order to monitor power.

@zxaber

Closing in 2 days if nobody provides some input.

**Comment by Mirino97** [comment]
Oh, it MUST be a ground console, huh?
Kinda weird that'd it show on the list for downloads without any warnings with that, but I guess that's also a consistency thing or just a personal gripe. 
I'll close the issue and look into possibly adding a little more flavour text to the message stating that it needs to be on stationary consoles.
Thanks for your answer!

**Comment by zxaber** [comment]
The downloader is supposed to mention when programs are incompatible. It used to just not show them, but that was recently changed. Is AmpCheck the only program that's downloadable on incompatible devices?

**Comment by Mirino97** [comment]
It is not the only one that is incompatible and can be downloaded, no.
