### ISSUE TITLE
swapping items is eating things

### ISSUE THREAD

**Issue by joybod** [tgstation/tgstation#55112]
Issue reported from  Round ID: [150800](https://scrubby.melonmesa.com/round/150800) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1528

when I use the Equipment Swap command/hotkey, the original item disappears. this could prove disastrous for certain things where important items are lost unintentionally

**Comment by RaveRadbury** [comment]
I have assisted a player experiencing this bug, when I ran and sdql select for the lost object it was reported as being **inside** them and was able to be removed via VV `get`

**Comment by Eldeen** [comment]
Can confirm, this happened to me today, raveradbury teleported them out. Was trying to swap items and they vanished, im not sure if it was in my body cavity or just some weird space created for the items inside my body, round ended before I could test it.

**Comment by ArcaneMusic** [comment]
Had this happen on round 150815 on bagil. I swapped my backpack with a jetpack, and the backpack got deleted, while playing as Joey Quiver.

**Comment by Jared-Fogle** [comment]
for fucks sake

**Comment by Jared-Fogle** [comment]
> it was reported as being inside them and was able to be removed via VV get

i have made some bad assumptions

**Comment by ATH1909** [comment]
time to vore people

**Comment by MrDoomBringer** [comment]
god dammit i knew i wasn't crazy
