### ISSUE TITLE
Health is fuck (featuring people able to take more than 100 brute until crit!)

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#55128]
## Round ID:
/////

## Testmerges:
/////

## Reproduction:
Deal 100 damage to someone.
Watch as they don't fall into crit.
Deal another 20 damage to someone.
Watch as they NOW fall into crit (120 damage until crit).
Deal another 100 damage to bring up the total to 220 damage. watch as they STILL DONT FUCKING DIE.
Deal another 20 damage and watch as they FINALLY die.

Conclusion:
Wtf.

(I'm not retarded right, people arent meant to take more than 100 brute until crit?)
Another thing that is an offshoot of this is that the BSA smite no longer sets someone to one health.
#55103
More explained than the issue above.

**Comment by Dorsisdwarf** [comment]
I seem to recall that high mood/sanity was supposed to give you a very minor increase to how much damage you can sustain before crit, but this seems very much wrong.

**Comment by Tlaltecuhtli** [comment]
were you aiming a limb?

**Comment by brotherbeyondd** [comment]
@Tlaltecuhtli i tested it a variety of ways.

Firstly I damaged my right leg with a punch, and vv'd myself to 100 brute. Didn't go into crit.
Then gave myself 100 brute just via vv. Didn't go into crit.
THEN I hit myself all the way to 120 in which I finally went into crit (using 2 brute damage vvs).
Then I made an esword do 34 damage, which should be enough to crit someone in three hits, and aimed for the torso. Hit thrice and... Didn't go into crit. All hits landed on the torso and in total I had 100.7 brute.
Then I dealt 200 brute, and the person did not die. I also dealt another 20, did not die.
I had to deal 240 damage in total for the person (catgirl) to die.

**Comment by brotherbeyondd** [comment]
@Dorsisdwarf this was all on default :| mood catgirls spawned in (and the odd flyperson).

**Comment by brotherbeyondd** [comment]
More testing! The VV applies it to all limbs which'd explain why it wouldn't hit into crit exactly like that.

HOWEVER I did also aim at my chest once and it still didn't crit me, but I just tested it another time and it did. Despite both times hitting the chest. What the fuck is happening.

**Comment by Timberpoes** [comment]
This should be investigated alongside https://github.com/tgstation/tgstation/issues/55103 as I suspect they are linked.

**Comment by Fikou** [comment]
this is not an issue, #55103 is
this is how it worked forever
