### ISSUE TITLE
Simple Mobs Get Stuck On Broken Roller Tables

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#55133]
## Reproduction:

1). Make a `/obj/structure/table/rolling`
2). Put a simple mob on it. 
Verified with both  a `/mob/living/simple_animal/hostile/poison/giant_spider` and `/mob/living/simple_animal/pet/dog/corgi`
3). Break the table.
4). Take control of the mob and attempt to move.
5). The mob can not move.

**Comment by interestingusernam3** [comment]
Managed to reproduce locally with exotic corgis. Some interesting findings:
- The mob is already unable to move while the table still exists.
- Players phase through the mob once the table is broken
- If a rolling table phases through a mob affected by the bug, that mob is put on the table
- Above also occurs with any other dead corgi. This behavior also occurs with dead monkeys.
- bugged mobs are pulled at about the speed dead mobs are pulled
- bugged mobs can still die, stay bugged upon revival
- no runtime occurs
- Bug occurs if mob is placed on table with pull+help intent
- Bug does not occur if mob is placed on table with agressive grab
- Bug does not occur if table is spawned on top of mob
- Bugged mob will not talk or emote automatically (Stuff like "woof", "chases it's tail" etc.)

**Comment by interestingusernam3** [comment]
This is fixed.
