### ISSUE TITLE
Chameleon Projector cant scan most of containers

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#55143]
## Reproduction:

1. Get Chameleon Projector.
2. Fill any backpack completely.
3. Scan it with projector, works fine.
4. Fill any other container.
5. Get a phrase "Container is full, make some space!", cant be scanned.

**Comment by Sealed101** [comment]
oop the PR did not close the issue
fixed by https://github.com/tgstation/tgstation/pull/79263
