### ISSUE TITLE
Crafted food contains incorrect reagents

### ISSUE THREAD

**Issue by antropod** [tgstation/tgstation#55149]
I found that bug when I tried to grind mystery soup into reagents. Grinding mystery soup should result in nutriment, vitamin and one random reagent from list, but it results in nutriment, protein and water.
Bug happens only when you craft it in game, when you spawn it from debug menu it contains correct reagents.

Crafted:
![crafted](https://user-images.githubusercontent.com/7479888/100123818-f6bf5c00-2e8b-11eb-96e4-ebcd7f17b8ca.png)
Spawned:
![spawned](https://user-images.githubusercontent.com/7479888/100123999-279f9100-2e8c-11eb-878f-9342471b1c3e.png)

**Comment by antropod** [comment]
@Qustinnus can you look into this?

**Comment by Qustinnus** [comment]
will do

**Comment by Qustinnus** [comment]
@antropod can you check if its just this soup or all foods?

**Comment by antropod** [comment]
yeah

**Comment by antropod** [comment]
Chaos donuts are broken too. I think it's something about how random reagents are added

It seems like crafted or microwaved foods inherit reagents of what they were crafted from.
Also, amount of reagents of spawned and crafted food are different (crafted have only 0.7 of amount of spawned if you subtract reagents of source products)

boiled egg (made from raw egg):
spanwed - 3 protein, 1 vitamin
crafter - 2.1 protein, 0.7 vitamin, 4 egg yolk (raw egg contains 4 egg yolk)

monkey steak (made from monkey meat):
spawned - 8 protein, 1 vitamin
crafted - 11.6 protein, 2 cooking oil, 0.7 vitamin (raw meat contains 6 protein, 2 cooking oil)

bread (made from dough):
spawned - 10 nutriment
crafter - 13 nutriment (dough contains 6 nutriment)

**Comment by Qustinnus** [comment]
This is kind of a design-flaw that I haven't fully figured out how to solve yet: Old food had 2 lists; default reagents and bonus reagents. This existed to nerf pre-placed food, but this system had a massive overhead.

My solution however, as you can see, is not flawless as it depends on the ingredients used to have similar values when cooked. In your posted examples however, the crafted food always ends up with more reagents which is good, so it's not a huge issue.

I'd be open to any suggestions for this, however for now I'll focus on fixing the existing issue with the random foods.

**Comment by Qustinnus** [comment]
chaos donuts aren't newfood yet btw

**Comment by Qustinnus** [comment]
Found out why this happens, crafted and microwaved foods clear their reagents and re-apply them to get a clean slate. this is shit so I'll fix it.
