### ISSUE TITLE
Oversight? Space Ninja can hack dead cyborgs and have it count for objective

### ISSUE THREAD

**Issue by Mirino97** [tgstation/tgstation#55148]
Only making this since I couldn't get anyone to answer on Discord. 
Ninjas can convert any borg, as long as it was alive and controlled by a player at some point, and have it count for their objective. Is this an oversight?
## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:

1: Spawn in as Ninja
2: Find a dead borg that hasn't been rebooted yet
3: Use gloves and convert

**Comment by ATH1909** [comment]
does the borg get rezzed when you do this?

**Comment by ATH1909** [comment]
IMO, this should be a feature, as IIRC, you can emag dead borgs as well, no?

**Comment by Mirino97** [comment]
The borg does not get rezzed when emaged, no.
 I'd be fine with it being a feature. I guess it kinda helps since the borg one is IMO the hardest objective, but feels a little too easy. Ninja's objectives are too easy to finish as they stand, and since I'm new around here, I'm not sure if that's intended or even something I should worry about.

**Comment by dragomagol** [comment]
It makes sense that it be consistent with other objectives based around silicons (having 8 **active** borgs synced to a malf AI, stealing a **functional** AI...)

**Comment by dragomagol** [comment]
Author of the ninja rework says this is a feature

**Comment by Mirino97** [comment]
Ah, glad to know then! I'll be closing the issue report since it's acting like it should.
Thanks for looking it up @dragomagol !
