### ISSUE TITLE
The stabilized pink slime extract is.... inconsistent

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#55155]
## Testmerges:
- #55122 

## Reproduction:
1. Acquire a stabilized pink slime extract
2. Explore space
3. Enter the paper wizard ruin
4. ![BANG](https://user-images.githubusercontent.com/53582584/100194348-65131700-2eaa-11eb-8207-ea7d5e9b50ee.PNG)

**Comment by dragomagol** [comment]
For reference: Stabilized Pink - As long as no creature in sight is injured in your presence, they will not attack you. If the peace is broken, takes two minutes to restore.
