### ISSUE TITLE
Mechs Delete You If You Transform Inside Of Them

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#55153]
## Reproduction:

1). Get in a mech.
2). Have something that will cause you transform, in this specific case I witnessed someone with the gondola virus transform while inside of the mech.
3). For the sake of simplicity I called `Animalize(/mob/living/simple_animal/pet/cat)` while inside of a mech to verify the issue.
4). Get deleted.

Ouch, thats rough.

**Comment by dragomagol** [comment]
Possibly related to #54817 ?

**Comment by Misdoubtful** [comment]
I'm positive its related. I just tested dragon form shapeshift and got the same result, and same deletion.

**Comment by brotherbeyondd** [comment]
@Misdoubtful you dont get deleted, but I think you get stored in it? Since you're still alive in the mech. When the mech is destroyed, you're sent to the nono error room.

**Comment by Misdoubtful** [comment]
@brotherbeyondd I had to take a second look and this appears to be so. There was a deletion with the other method however.

**Comment by Sealed101** [comment]
during shapeshifting's `ForceMove`ing the player character to the polymorph mob, shapeshifting dumps the controller character out of mecha's `occupants` and contents, but the mob the character has shapeshifted into is skipped in the process. the mob doesn't enter `occupants` and is thus not dumped out. currently it doesn't delete either the mob or the character, but keeps the player in the polymorph mob in the mecha's contents.

**Comment by Sealed101** [comment]
no longer occurring for the same reason as https://github.com/tgstation/tgstation/issues/53048
