### ISSUE TITLE
gatfruit didnt spawn any revolver when eaten

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#55168]
150973

i plant gatfruit and grows fine, harvest once and the revolvers appears when eaten

then i plant a seed of the first one in a tray, i rename the tray with a pen twice

harvest a bunch of times

when i eat the fruits it says "there is nothing left" and no revolvers

**Comment by MrMelbert** [comment]
can't reproduce on the latest master, but tlal you know you can just use them in hand to get a gun you don't have to eat them right?

**Comment by Tlaltecuhtli** [comment]
i dropped 50 of them with people around and no one got revolver, not sure if renaming the tray broke it

**Comment by Fikou** [comment]
couldnt reproudce

**Comment by Fikou** [comment]
could reproduce

**Comment by ArcaneMusic** [comment]
10 bucks says this has to do with it becoming newfood
