### ISSUE TITLE
Zombies can't be sacrificed by heretics and their heads still seem to be tougher to remove

### ISSUE THREAD

**Issue by Sparkezel** [tgstation/tgstation#55161]
## Reproduction: 
Get a zombie picked as your sacrifice
Try to sacrifice the zombie because it deathgasped
Not be able to sacrifice the body because it still may revive

Also I suspect that zombie heads might be harder to remove again because I remember cleaving saw to be able to chop off limbs. Admin needed to remove festering ooze from the body so I could sacrifice it.

**Comment by brotherbeyondd** [comment]
I believe zombies cant actually succumb and since the target must be dead, they cant be sacrificed. Also yes the heads are harder to remove again cos of their base armour I think?

**Comment by wesoda25** [comment]
Heads def gotta be easier to hack off though. Currently people are just doing neck slicing + tabling to get them off and it’s a bit ridiculous

**Comment by Sparkezel** [comment]
Cleaving saw is a weapon that can cut off heads with 2-4 hits while unfolded, being unable to cut off zombie heads with it buffled me greatly, even heretic blade didn't work for that.

**Comment by Fikou** [comment]
just do ghetto surgery amputation

**Comment by Pugie** [comment]
HMM I THINK HEADS NOT BEING REMOVABLE IS DEFINITELY NOT "NOT A BUG"
