### ISSUE TITLE
Ageusia Appears Broken

### ISSUE THREAD

**Issue by UltimateFluff** [tgstation/tgstation#55182]
## Reproduction:

At some point, apparently the ageusia trait got broken, as foods that someone can or can't eat is treated as if they don't have ageusia (lizards with it can't eat non-meats, for example). I don't know what precisely is breaking it, but given there's been a lot of food reworking going on, I'm betting there.

**Comment by Tlaltecuhtli** [comment]
ageusia wont work if you eat toxic_food to your race, can you describe the issue more clearly

**Comment by UltimateFluff** [comment]
I play a lizardperson with it, and it just doesn't work at all. Anything it would let you eat (bread, for example) still makes you vomit, so anything you ate that wasn't toxic makes you vomit if it's not your race's preferred food.

**Comment by Tlaltecuhtli** [comment]
#54996 seems ageusia is checked but doesnt return early? @ArcaneMusic

**Comment by prodirus** [comment]
Don't want to return early either or you'll miss out on the breakfast foods check.

Maybe just wrap the liked/disliked section in a HAS_AGEUSIA check?
