### ISSUE TITLE
TP fails to remove Monkey antag status

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#55194]
## Reproduction:
1. Make yourself a Monkey Leader via TP
2. Remove Monkey Status via TP, hit yes when it prompts you to humanize
3. You might need to wait a bit for the disease to transform you back into a monkey, I'm not sure if this is actually necessary.

Result I got: Antag datum was not removed and I immediately turn back into a monkey.
Expected: Datum gets removed & I stay human.

**Comment by ArcaneMusic** [comment]
Okay but what is "TP"

**Comment by Cyprex** [comment]
Traitor Panel
