### ISSUE TITLE
Monkey Infection does not respect auto deadmin settings

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#55195]
## Round ID: [151045](https://scrubby.melonmesa.com/round/151045)

The monkey infection (via TP) deadminned me despite the following settings
![Screenshot_20201126_225900](https://user-images.githubusercontent.com/35031555/100393740-00d38d00-303b-11eb-987e-a4a1e51aadad.png)

**Comment by Sealed101** [comment]
- monky no longer go ape since #63763
