### ISSUE TITLE
You can't cut cakes with generally sharp items anymore

### ISSUE THREAD

**Issue by Jared-Fogle** [tgstation/tgstation#55208]
## Reproduction

1. Put a cake on a table, I had a brain cake.
2. Try to cut it with a circular saw.
3. Get the message that you can't fit a circular saw in a cake.
4. Try to cut it with a scalpel.
5. It puts the scalpel in the cake.

Intent doesn't matter. I don't know if this has always been the case, but I don't feel it has been.

CC @Qustinnus

**Comment by dragomagol** [comment]
Related to #55012 (I would guess this applies to all sliceable newfood)

**Comment by Qustinnus** [comment]
someone made a pr letting more tools cut food like this. If we want to make it so sharp tools automatically can cut, you can programatically add the knife tool behavior if a tool is sharp and has no other behavior.

**Comment by Qustinnus** [comment]
someone made a pr letting more tools cut food like this. If we want to make it so sharp tools automatically can cut, you can programatically add the knife tool behavior if a tool is sharp and has no other behavior.
