### ISSUE TITLE
Dead people don't take damage from fire

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#55206]
Means husking (350 burn?) and fire cremation (200 chest burn?) don't work unless you adjust fireloss. 

Probably due to #54550. 

## Reproduction:
1.  Keep human on fire. 
2. Wait 15 minutes or so. 

## Results:
![201127 1853 09](https://user-images.githubusercontent.com/46400996/100474956-21a2ed80-30e2-11eb-923c-66ca1d89bd89.png)

![201127 1853 19](https://user-images.githubusercontent.com/46400996/100474962-249dde00-30e2-11eb-878d-ec84f40999d3.png)

Did not get husked. No missing limbs. Stopped taking burn damage after death. Burn damage only happened one more tick after death. I tested putting an already dead body on fire and it only took burn damage 1 tick (6 burn damage). 

## Expected results:
Fire should do up to 600 burn (200 head, 200 chest, 50 per limb). Not sure if the high temperature is an issue or not since it doesn't seem to affect turfs anyway.

**Comment by ATH1909** [comment]
goddamnit nightred
