### ISSUE TITLE
Items that deal zero damage don't get an attack verb shown in chat.

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#55219]
## Round ID:
/////

## Testmerges:
/////

## Reproduction:

Get a bee plushie and smack your nearest moth with it.
See nothing appear in chat!
Give the bee plushie one (1) force.
See you begin to sting the helpless moth in chat!

I believe this is unintentional as why else would these plushies (and other items that deal 0 damage) have custom attack verbs, if not to be shown in chat?
I want to sting my moths god damn you!
![image](https://user-images.githubusercontent.com/68032262/100523805-2aabc180-31ab-11eb-801f-ab3414ea57c9.png)
That's it with 1 force. Without any force, it doesn't appear in chat.

**Comment by RaveRadbury** [comment]
I can't `touche` crew with baguettes. WHY LIVE!?

**Comment by brotherbeyondd** [comment]
where the fuck is the high priority label???
