### ISSUE TITLE
New food has a tide of weight class inconsistencies

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#55225]
## Round ID:
Tested on local

## Testmerges:
N/A

## Reproduction:
Chef's ingredients beacon contents that can't be put back into their box;
Sweets: chocolate bar
Fruity: watermelon
Italian: meatballs x3
Fiesta: tortilla
Exotic: carp fillet x2
Carnivore: bear meat, spider meat, spider eggs, carp fillet, xeno meat, corgi meat, meatball
American: meatball

Bubblegum is 4 pieces of normal sized gum in a tiny container

1 normal sized piece of meat cuts into 3 normal sized cutlets which can be processed into up to 12 normal sized pieces of bacon
1 normal sized piece of meat can be processed into 4 normal sized meatballs
1 normal sized piece of flat dough cuts into 3 small sized dough slices which can be processed into up to 12 normal sized raw spaghetti

Mints are normal sized (LOL?)

Paper sacks for making bagged lunches of any type are normal containers and cannot hold any normal sized food

Chicken nuggets (despite being made of any type of cutlet) are a normal sized item. BTFO kid's boxes of nuggies, can't fit in a box.

Rat kebabs (a tiny dead mouse and a tiny singular iron rod) make normal sized items
A fried egg (a tiny egg and TWO UNITS OF REAGENTS) make a normal sized item

**Comment by Qustinnus** [comment]
this is fixed now but it did basically reverse the problem where huge watermelons are now small. I'll close this though as its not a huge issue.
