### ISSUE TITLE
New food refactor broke plant composting

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#55226]
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
`/obj/item/food/grown` fails to be composted into hydroponic trays/plant soil to add their reagents to the tray/soil, instead smacking them with the item
This kills off ashwalker botany excluding destroying/rebuilding them

**Comment by MrMelbert** [comment]
#54279 related issue
