### ISSUE TITLE
Mitogen Metabolism Factor is not made when you consume probital

### ISSUE THREAD

**Issue by RafRoq** [tgstation/tgstation#55224]
this makes the peptides useless cause you cant make them eating nutriment or protein, probably a stomach thing no one thought about

**Comment by Angustmeta** [comment]
Maybe same cause as #54959.

**Comment by timothymtorres** [comment]
Tested and no problems:

![2cxXuEB0rj](https://user-images.githubusercontent.com/5195984/146619202-790b2782-47cd-4a84-8214-e1320625bde1.png)

![dreamseeker_x85DZrwx6u](https://user-images.githubusercontent.com/5195984/146619212-3b1614c8-8fd5-49dd-b233-eab835df47af.png)

I spawned a probital pill bottle and ingested it while eating a donk pocket. Mitogen Metabolism was made according to the chems.
