### ISSUE TITLE
Beeping as a borg kicks off riders.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#55236]
## Round ID:
None

## Testmerges:
Manual

## Reproduction:
-1. Set "*beep" to the "b" key
0. be a borg
1. get someone to ride you
2. press "b"
3. The rider will be kicked off

I have reported this before, however no one was able to reproduce it, so the issue was closed. 
Something else I have noticed about "*beep" is that when used while in a recharger, the sound will play but no emote in put in chat.

**Comment by dragomagol** [comment]
Is beep the only thing mapped to b?

**Comment by dragomagol** [comment]
Other *beep issue #49682

**Comment by dragomagol** [comment]
Other *beep issue #49682

**Comment by redguy999** [comment]
> EDIT: Resist is automatically mapped to B, which both unbuckles people from you as a borg and takes you out of the transit tube. I think this is probably a shared keybinding rather than something to do with the emote itself.

Yeah, thats the issue
