### ISSUE TITLE
chem addiction is not working

### ISSUE THREAD

**Issue by uBadush** [tgstation/tgstation#55245]
addiction is not working, was consuming tons of krokodil and never got addicted  even going above the addiction threshold, consuming more than 15 units and waiting for it all to be metabolized nothing happened, a bunch of chemicals arent working properly you guys need to fix it

**Comment by TemporalOroboros** [comment]
If you were eating it this is almost certainly due to the way stomachs work now. They drip-feed the chems into your blood. Injection and patches should work fine.

**Comment by uBadush** [comment]
still a bug

**Comment by RaveRadbury** [comment]
This is happening with patches and injections as well

**Comment by RaveRadbury** [comment]
Caused by #54797

**Comment by nightred** [comment]
Thanks Rave, you helped track this down.
Also you pointed out that patchs and injections also are failing as a major point here.
