### ISSUE TITLE
TGui Bluescreen while trying to choose AI Secure Portraits at Core Customization screens.

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#55247]
## Reproduction:

While trying to choose the "Secure Portraits" option as an AI trying to use a custom portrait for the AI Core Display, the following TGui bluescreen message comes up.

> A fatal exception has occurred at 002B:C562F1B7 in TGUI. 
> Script error.
>    at https://www.tgstation13.download/byond/assets/0f/asset.0fe95a6fc78bde1c374ffac7da51bc17.js:0
> User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; HCTE; Tablet PC 2.0)
> State: {"ckey":"san7890","interface":"PortraitPicker","window":{"key":"[0x21033595]-main","size":null,"fancy":1,"locked":1}}
>

**Comment by dragomagol** [comment]
@tralezab
