### ISSUE TITLE
Text related to The Protocol CRAB-17 Phone is unusual.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#55258]
## Round ID:
none

## Testmerges:
Manuel

## Reproduction:
1. have someone on the same server use the phone.
2. Attempt to take your credits out of your ID, get meet with symbols. (is it Japanese or Chinese?)
3. Use your ID on the machine that gets created, find that safe is misspelled as safu.

(i haven't been victim to this for awhile, but i believe both issues stated are correct)

**Comment by ArcaneDefence** [comment]
The entire thing is a biz meme.
https://www.youtube.com/watch?v=DelF6zEHXpE
https://github.com/tgstation/tgstation/blob/96597d31577c379507ac571edc11706358a152c7/code/game/objects/items/crab17.dm#L75
https://github.com/tgstation/tgstation/blob/74d5ffa6297a2f97875f9ddb27d48b735e12f838/code/game/objects/items/cards_ids.dm#L226

![image](https://user-images.githubusercontent.com/51932756/100675386-18a15e80-3324-11eb-9aad-c4d9a6db625a.png)

**Comment by redguy999** [comment]
Well then i guess this isn't an issue.
