### ISSUE TITLE
Borg modules are still broken.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#55257]
Reporting client version: 513.1536

## Round ID:
[151297](https://scrubby.melonmesa.com/round/151297)

## Testmerges:
Manuel
- [Small do-after refactor](https://www.github.com/tgstation/tgstation/pull/55172)
- [Filterrific!](https://www.github.com/tgstation/tgstation/pull/55246)

## Reproduction:
1. be a borg
2. become mediborg
3. get the crew monitor upgrade
4. be annoyed that you can't do your job because the button does nothing

Self-repair appears to also be broken in a similar manner.

@Timberpoes, You found a way to fix the broken monitor midround, think you can help us actually fix it?

**Comment by redguy999** [comment]
can someone please fix this?

**Comment by LemonInTheDark** [comment]
We'll get to it when we get to it, development is all volunteer, and some things take time. I expect this'll get some work done on it soon though.

**Comment by redguy999** [comment]
> We'll get to it when we get to it, development is all volunteer, and some things take time. I expect this'll get some work done on it soon though.

Was just making sure someone saw this.

**Comment by Timberpoes** [comment]
I fixed this mid round by doing an atom proc call to disable and active on the module.

I'll look into this when I get more free time unless someone else beats me to it.

**Comment by redguy999** [comment]
> I fixed this mid round by doing an atom proc call to disable and active on the module.
> 
> I'll look into this when I get more free time unless someone else beats me to it.

Thanks, now i know what to tell admins when i have issues.

**Comment by zxaber** [comment]
The underlying issue is that the action button datum isn't getting the borg as the owner. I haven't yet figured out why this is, but if you set the borg as the owner the button starts working again. The ERROR sprite is also related, because after fixing it I can hide and unhide the button and it'll have the correct sprite.
