### ISSUE TITLE
You can deepfry things you shouldn't be able to deepfry through the cooking oil chem reaction

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#55250]
## Reproduction:
Hmm, today I want some fried station blueprints. That traitor down in medbay said they needed them.
![image](https://user-images.githubusercontent.com/51863163/100586725-31bef680-32b5-11eb-9860-26a763ed4824.png)
Ah, darn, can't deepfry them. Unless...
![image](https://user-images.githubusercontent.com/51863163/100586695-28ce2500-32b5-11eb-9dfe-14d477ea5b49.png)
Ah, nothing like the taste of denied greentext for breakfast.
![image](https://user-images.githubusercontent.com/51863163/100586796-47ccb700-32b5-11eb-8ae6-8b8fc653121a.png)

(The deepfrier goes through and checks if the objects are indestructible / if they're in the blacklisted typecache / nodrop, etc. before starting to fry them. The expose procs of cooking oil does none of that and just fries it anyways.)

**Comment by Tlaltecuhtli** [comment]
does the important item disappear when you eat it? or just drop to the floor?

**Comment by prodirus** [comment]
> does the important item disappear when you eat it? or just drop to the floor?

Just tested, you just straight up consume it and it disappears.

**Comment by ATH1909** [comment]
hush ye

**Comment by TheBonded** [comment]
can you deepfry the nuke disk? it would respawn if you ate it I assume, but if you didn't eat it then nukies would have to find it twice

**Comment by prodirus** [comment]
> can you deepfry the nuke disk? it would respawn if you ate it I assume, but if you didn't eat it then nukies would have to find it twice

You actually can deepfry it, and it works exactly as you've described it.
