### ISSUE TITLE
Processable element on new food doesn't require a table like old food did

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#55263]
## Round ID:
Tested on local

## Testmerges:
N/A

## Reproduction:
New food doesn't require a table/tray to cut on, as the previous `reagent_containers/food` did, allowing you to flatten/cut dough slices and the like on the floor.

**Comment by Owai-Seek** [comment]
Another thing I've noticed when cutting foods as some don't immediately act as food items, and you'll bap yourself on the head with it a couple times.

**Comment by ArcaneDefence** [comment]
Someone made cutting foods scatter them around and I didn't notice. Pog.

**Comment by timothymtorres** [comment]
> Another thing I've noticed when cutting foods as some don't immediately act as food items, and you'll bap yourself on the head with it a couple times.

That’s in several other issues that is caused from any type of food having 0 reagents.
