### ISSUE TITLE
Mild fevers and shivering causes people to burn alive in their own skin

### ISSUE THREAD

**Issue by Maurukas** [tgstation/tgstation#55266]
## Testmerges:

#54093: 'Experi-Sci: Techweb nodes may now require you to perform "scientific" experiments' by Qustinnus at commit 09c2570ccc
#55244: 'Testmerge pr on the calendar for december' by tralezab at commit edb41be591

## Reproduction:

Acquire a virus with either fever or shivering, of any magnitude or severity. Your roundstart flu mutated once to acquire the symptom will do. Infect a carbon with the virus and it will begin to take continuous escalating burn damage, blistering out in second degree burn wounds, until it enters crit at about 2 minutes. The burn damage doesn't stop until the virus is cured. Stronger viruses appear to make this faster. In my tests locally I saw crit times as little as 1 minute after infection, and internal body temperatures of >200 degrees.

In 151312, a pair of miasma viruses wiped the station like a biblical plague. In 151316 an assistant broke into virology, got a WIP virus with a moderate fever symptom that critted him through 10u of oxandrolone and several burn patches.

**Comment by ArcaneDefence** [comment]
@nightred I'd imagine this isn't intended kinda stuff with body temps

**Comment by ATH1909** [comment]
damnit nightred

also, oooooh, time to speedrun making a deathplague

**Comment by nightred** [comment]
I seriously thought I had a cap on that so this wouldn't happen

**Comment by Maurukas** [comment]
After poking at the code, and testing a bit more, it looks like monkeys take a static amount of burn damage based on temp, but if the carbon has a species, it uses this:
https://github.com/tgstation/tgstation/blob/0eaab0bc542ddb081556e11dd9d8dee75d077bce/code/modules/mob/living/carbon/human/species.dm#L1776

However, core temperatures are getting to ridiculous levels:
![2020-12-02 18_04_49-Festive Array IV](https://user-images.githubusercontent.com/66576896/100950602-ecbfdd80-34c9-11eb-97b6-503003e796fe.png)

Weirdly, after testing a bit more, this does not affect lizards severely at all. Both fever and shivering drop their core temps by about 15 degrees and no burn damage occurs. It eats endotherms in minutes though.

**Comment by ATH1909** [comment]
lizard viro meta

**Comment by nightred** [comment]
> lizard viro meta

Fever and chills only effects your natural body stabilization, since lizards do not have that it does not cause any real effect to them.
