### ISSUE TITLE
Simple Mobs can't be hurt by melee weapons

### ISSUE THREAD

**Issue by Chanamo-8** [tgstation/tgstation#55260]
## Round ID: 
[151311](https://scrubby.melonmesa.com/round/151311)

## Testmerges: 
https://github.com/tgstation/tgstation/pull/55238

## Reproduction: 
1. Have a melee weapon (I had a circular saw)
2. Hit a simple mob with said melee weapon (I hit a corgi)
3. The simple mob should come out unharmed.
4. Hit the simple mob with your fist.
5. simple mob will be harmed.

**Comment by Qustinnus** [comment]
😰

**Comment by Qustinnus** [comment]
I couldn't reproduce this

**Comment by ArcaneDefence** [comment]
Happened for me with drakes/knives, and ian/a fucking chair.
Needed to throw items or something else instead of using a melee weapon.
Shit's fucked

**Comment by dragomagol** [comment]
I was able to do this as well. May be related to #55219

**Comment by bobbahbrown** [comment]
culprit: https://github.com/tgstation/tgstation/pull/55023

**Comment by ATH1909** [comment]
I'm working on it.
