### ISSUE TITLE
Tgchat panel freezes on reconnect

### ISSUE THREAD

**Issue by bobbahbrown** [tgstation/tgstation#55301]
Reporting client version: 513.1536

## Round ID:
[151375](https://scrubby.melonmesa.com/round/151375)

## Testmerges:
- [Creates Datumized AI and applies it to monkeys](https://www.github.com/tgstation/tgstation/pull/55238)

## Reproduction:
1. Wait for round to end while connected
2. Don't reconnect immediately
3. A few minutes later, connect, tgchat will remain the exact same as it was prior to reconnecting despite having successfully reconnected. No new messages are shown.

Reproduction is not consistent, seems rare. I've only just encountered this for the first time now. May be related to #54692.

The tgchat panel itself becomes non-responsive, with a loading icon shown on the cursor when the panel itself is moused over. No buttons can be pressed, no UI element on the tgchat window can be clicked on. No messages are added or removed, nothing is cleared, it just remains as it was prior to reconnecting.

![image](https://user-images.githubusercontent.com/10467687/100824206-1fb39400-342c-11eb-824c-303f71de2aae.png)

**Comment by Tlaltecuhtli** [comment]
#53213 dupe?

**Comment by bobbahbrown** [comment]
> #53213 dupe?

This is not the same issue as that. This is a successful reconnect wherein the tgchat panel freezes.
