### ISSUE TITLE
Space Dragon suddenly getting deleted

### ISSUE THREAD

**Issue by NamelessFairy** [tgstation/tgstation#55329]
## Round ID:
[151459](https://scrubby.melonmesa.com/round/151459)

## Testmerges:
Almost certainly unrelated but:
https://github.com/tgstation/tgstation/pull/54588

## Reproduction:
This issue did not happen to me but I did witness it and have discussed to situation with the person affected.

Unfortunately I can't reproduce it and the only unusual detail about this round from a gameplay perspective was that there were two dragons spawned. I can however provide video footage of it happening and some runtime details

The following runtime issue occurred at the same time as the dragon was deleted.
```
[2020-12-03 15:11:29.206] runtime error: Cannot execute null.set varspeed().
 - proc name: Destroy (/obj/structure/carp_rift/Destroy)
 -   source file: space_dragon.dm,554
 -   usr: null
 -   src: the carp rift (/obj/structure/carp_rift)
 -   src.loc: the floor (29,135,2) (/turf/open/floor/plasteel/dark)
 -   call stack:
 - the carp rift (/obj/structure/carp_rift): Destroy(0)
 - qdel(the carp rift (/obj/structure/carp_rift), 0)
 - Le Fishe (/mob/living/simple_animal/hostile/space_dragon): destroy rifts()
 - Le Fishe (/mob/living/simple_animal/hostile/space_dragon): Life(1098)
 - Mobs (/datum/controller/subsystem/mobs): fire(0)
 - Mobs (/datum/controller/subsystem/mobs): ignite(0)
 - Master (/datum/controller/master): RunQueue()
 - Master (/datum/controller/master): Loop()
 - Master (/datum/controller/master): StartProcessing(0)
```

A video showing the  dragon being deleted (in meme format) can be seen here:
https://youtu.be/vaxTUIiuPpQ
I've asked permission and have been requested to include to video for demonstration purposes.

**Comment by optimumtact** [comment]
this is not a bug, if the space dragon does not carry out it's assigned tasks it's get deleted there are warnings about this
