### ISSUE TITLE
Gloves given by tongue tied quirk are overridden by gloves given by job

### ISSUE THREAD

**Issue by Jared-Fogle** [tgstation/tgstation#55322]
Had a tongue-tied warden on a round of Bagil who had to ask me to spawn them in their gloves. This is presumably because the warden job overrides the gloves.

They were a late join, but tells me it happens either way.

**Comment by kesumod** [comment]
yeah, that was me. It didn't used to happen, and it was any job with gloves I believe. The job I usually play was Security officer, and that was the job I was playing.
