### ISSUE TITLE
[Oversight?] X-ray rifles fit in bags

### ISSUE THREAD

**Issue by Mirino97** [tgstation/tgstation#55321]
Is it supposed not to? Some time ago normal e-rifles and advanced rifles also fit in bags, but that was removed, and X-ray ones (possibly the most gamer-y of all) still fit in bags, allowing people to carry more than one.

## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:

1: Print x-ray gun
2: Shove in bag!

**Comment by Tlaltecuhtli** [comment]
well the reason for them to be bulky is so an assistant doesnt steal the whole armory by putting in bag, if you can print xrays you dont have that problem

**Comment by Mirino97** [comment]
Oh! I thought it was to stop the "Sec literally carrying an armory in their backpack" problem.
Altough I main security, I think that carrying 2 or 3 xrays guns is a little too OP and not fun for antags.

**Comment by Mirino97** [comment]
Waaaaaaaait, but adv. e-guns still can be printed and can't fit.
So if that's the reasoning behind it, it's a consistenty issue then?

**Comment by Jared-Fogle** [comment]
cc @Armhulen

**Comment by brotherbeyondd** [comment]
snitch...

**Comment by Mirino97** [comment]
kek
