### ISSUE TITLE
Missing limb mood debuff after getting a new limb

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#55348]
Reporting client version: 513.1536

## Round ID:
[151525](https://scrubby.melonmesa.com/round/151525)

## Testmerges:
- [Creates Datumized AI and applies it to monkeys](https://www.github.com/tgstation/tgstation/pull/55238)
- [Singularity component](https://www.github.com/tgstation/tgstation/pull/55096)

## Reproduction: dunno. lost my limb and then got a shitty prosthetic, but it the mood thing stucka round. 
![image](https://user-images.githubusercontent.com/37246588/101197817-9caf5b00-3630-11eb-8faf-77fecfbbb641.png)

**Comment by Jared-Fogle** [comment]
i'd be pretty sad if my arm was cut off too even after getting a new one idunno

doesn't look like there's any intent to make it get removed when the limb is placed back on, just an 8 minute timer:

```dm
/datum/mood_event/dismembered
	description = "<span class='boldwarning'>AHH! I WAS USING THAT LIMB!</span>\n"
	mood_change = -10
	timeout = 8 MINUTES
```
