### ISSUE TITLE
Moths no longer get nutrition from clothing

### ISSUE THREAD

**Issue by ChocolateBickie** [tgstation/tgstation#55347]
Reporting client version: 513.1536

## Round ID:
[151522](https://scrubby.melonmesa.com/round/151522)

## Testmerges:
- It happened after newfood was introduced https://github.com/tgstation/tgstation/pull/55160

## Reproduction:
I joined as a moth and got hungry. Decided to snack on some shoes as is the norm and found that it neither reduced my hunger nor seemed to cause me to get full. I finished an entire pair of shoes without becoming full. I also ate a watermelon which filled me up (and made me sick) so it only seems to be related to moths eating clothes.

Also, usually when eating clothing moths get messages saying you are eating the clothes, however the only messages that came up were for the clothes slowly becoming shredded.

Normal food makes moths vomit so they kinda need to eat shoes again.

Reproduce by becoming moth and eating clothing when hungry.

**Comment by dragomagol** [comment]
Moths should be able to eat vegetetables and dairy, just not meat and fruit

**Comment by Jared-Fogle** [comment]
> just not meat and fruit

Meat is toxic (I think?). Fruit just tastes bad.
