### ISSUE TITLE
Missing texture for icon mesh (sniper rifle with supressor) https://imgur.com/a/oao9QkO

### ISSUE THREAD

**Issue by DogetorDoge** [tgstation/tgstation#55351]
## Round ID: 
[51532](https://scrubby.melonmesa.com/round/51532)

## Reproduction:
https://imgur.com/a/oao9QkO

Attach a supressor to a (syndicate) sniper rifle. It displays some wierd mesh with no texture over the sniper rifle icon.
Alt-click to detach the supressor with (syndicate) sniper rifle in hand and reattach it. Issue persists. Obvious that this would happen.

**Comment by cacogen** [comment]
Presumably needs a suppressor overlay. I don't who decided to add all these pink "missing sprite" sprites instead of just allowing the missing sprites to remain invisible because it seems like most of the missing sprites are never going to be added.

**Comment by ArcaneMusic** [comment]
It was goof.
