### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by BorisVcBorison** [tgstation/tgstation#55355]
Reporting client version: 513.1536

## Round ID:
[151553](https://scrubby.melonmesa.com/round/151553)

## Testmerges:
- [Creates Datumized AI and applies it to monkeys](https://www.github.com/tgstation/tgstation/pull/55238)
- [Singularity component](https://www.github.com/tgstation/tgstation/pull/55096)

## Reproduction:
Through the placing of 2 disposal chutes facing each other, with reinforced floors under them, it seems to produce metal rods without actually damaging the floors, leading to infinite rods and by that infinite steel, the reinforced floors do not ever break

**Comment by dragomagol** [comment]
#27256

**Comment by Jared-Fogle** [comment]
Old duplicate. Also I understand that this is your first issue, in the future please try to give them a more descriptive title.
