### ISSUE TITLE
Mechs can still open blast doors by walking into them.

### ISSUE THREAD

**Issue by Mirino97** [tgstation/tgstation#55357]
Tested with the Ripley MK2 and the Durand. Both still open all blast doors just by bumping into them, even if you're just moving by a conveyor belt. Shutters are not affected by this behaviour though, like they did in the recent past.
## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:

1:Spawn in Mech
2: Walk into blast doors
3: Open-sesame!

**Comment by cacogen** [comment]
Blast doors and shutters are often assumed to be the same thing so I guess the fix was only done for one of them

**Comment by ArcaneDefence** [comment]
Still happens.
