### ISSUE TITLE
Health sensors are automatically off when attachable and cannot be turned on

### ISSUE THREAD

**Issue by GlueSniffer** [tgstation/tgstation#55369]
Reporting client version: 513.1536

## Round ID:
[151628](https://scrubby.melonmesa.com/round/151628)

## Testmerges:
- [Bring back Kilostation v3.0](https://www.github.com/tgstation/tgstation/pull/54588)

## Reproduction:

1. Turn on a health sensor, inspect to make sure it's on.
2. Screwdriver to make attachable.
3. Inspect again and find it is now off.
4. Activation in hand will say that you toggle it on, inspection still says its off.

First time reporting an issue, hopefully I didn't mess anything up.

**Comment by Tlaltecuhtli** [comment]
/obj/item/assembly/health/proc/toggle_scan()
	if(!secured)
		return 0


screwdrive it after turning it on

**Comment by GlueSniffer** [comment]
it seems to turn off when screwdrivered, even if on initially?

**Comment by Tlaltecuhtli** [comment]
no?
