### ISSUE TITLE
Icons on right-click menu miss-match

### ISSUE THREAD

**Issue by Mirino97** [tgstation/tgstation#55365]
Hi! As you can see in the picture, something happens, at some point, that messes with the icons show on the right-click menu, showing icons that are not representative of the item in the ground.
I have asked around OOC, and other people have this problem too, although not all. I also couldn't find a way to reproduce this in anyway, besides actually playing a full, on-line round that lasts for longer than 30 minutes on Manuel. 
I can't really attest to this 100%, but every shift starts fine, then after ~30 minutes, things get borked again.

![error](https://user-images.githubusercontent.com/52474532/101267059-ba191d80-3733-11eb-8faa-4b31b7693d97.png)

## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:

N/A

**Comment by dragomagol** [comment]
Same issue as #51898 but with different objects (this can likely happen to any object)
