### ISSUE TITLE
couldnt load apiary on mulebot

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#55361]
i could load myself but not the apiary (unwrenched)

**Comment by Ewwmewgewd** [comment]
You can load apiary onto hacked mulebot.
![image](https://user-images.githubusercontent.com/60656530/102695299-a935d500-4226-11eb-8a2c-9c58928c94a3.png)

**Comment by timothymtorres** [comment]
Marking this as `Not a bug` and it will autoclose in 7 days.

**Comment by Mooshimi** [comment]
cleanup flag is broken again it seems
