### ISSUE TITLE
cant eat slices of bread

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#55375]
you hit yourself with it instead of eating

**Comment by ArcaneDefence** [comment]
Seems likely related to reagents and how they're transferred.
Making a loaf of bread from flour produced 2 inedible bread slices, spawning a loaf of bread produced 3 inedible slices, and filling some bread dough with ketchup until it was full of ketchup made no inedible slices.

Salting any of the slices that failed to eat then allowed you to eat them normally.

**Comment by redguy999** [comment]
"How many slices of bread have you eaten in your life?"
"zero cause I just hit myself with the bread when I try to."

**Comment by ArcaneDefence** [comment]
Possibly relevant runtime's been showing up in the logs

[2020-12-30 08:19:40.839] runtime error: Cannot execute null.Copy().
 - proc name: edible ingredient added (/datum/component/edible/proc/edible_ingredient_added)
 -   source file: edible.dm,457
 -   usr: Nancy Rose (/mob/living/carbon/human)
 -   src: /datum/component/edible (/datum/component/edible)
 -   usr.loc: the floor (149,152,2) (/turf/open/floor/plasteel/white)
 -   call stack:
 - /datum/component/edible (/datum/component/edible): edible ingredient added(the small cheese wedge bread s... (/obj/item/food/breadslice/empty), /datum/component/edible (/datum/component/edible))
 - CallAsync(/datum/component/edible (/datum/component/edible), /datum/component/edible/proc/e... (/datum/component/edible/proc/edible_ingredient_added), /list (/list))
 - the small cheese wedge bread s... (/obj/item/food/breadslice/empty):  SendSignal("edible_ingredient_added", /list (/list))
 - /datum/component/edible (/datum/component/edible): used to customize(the cheese wedge (/obj/item/food/cheesewedge), the small cheese wedge bread s... (/obj/item/food/breadslice/empty))
 - CallAsync(/datum/component/edible (/datum/component/edible), /datum/component/edible/proc/u... (/datum/component/edible/proc/used_to_customize), /list (/list))
 - the cheese wedge (/obj/item/food/cheesewedge):  SendSignal("item_used_as_ingredient", /list (/list))
 - /datum/component/customizable_... (/datum/component/customizable_reagent_holder): add ingredient(the cheese wedge (/obj/item/food/cheesewedge))
 - /datum/component/customizable_... (/datum/component/customizable_reagent_holder): Initialize(null, 1, 1, 8, /list (/list))
 - /datum/component/customizable_... (/datum/component/customizable_reagent_holder): New(/list (/list))
 - the small cheese wedge bread s... (/obj/item/food/breadslice/empty):  AddComponent(/list (/list))
 - /datum/component/customizable_... (/datum/component/customizable_reagent_holder): on processed(the small cheese wedge bread (/obj/item/food/bread/empty), Nancy Rose (/mob/living/carbon/human), the kitchen knife (/obj/item/kitchen/knife), /list (/list))
 - CallAsync(/datum/component/customizable_... (/datum/component/customizable_reagent_holder), /datum/component/customizable_... (/datum/component/customizable_reagent_holder/proc/on_processed), /list (/list))
 - the small cheese wedge bread (/obj/item/food/bread/empty):  SendSignal("atom_processed", /list (/list))
 - the small cheese wedge bread (/obj/item/food/bread/empty): StartProcessingAtom(Nancy Rose (/mob/living/carbon/human), the kitchen knife (/obj/item/kitchen/knife), /list (/list))
 - the small cheese wedge bread (/obj/item/food/bread/empty): process recipes(Nancy Rose (/mob/living/carbon/human), the kitchen knife (/obj/item/kitchen/knife), /list (/list))
 - the small cheese wedge bread (/obj/item/food/bread/empty): tool act(Nancy Rose (/mob/living/carbon/human), the kitchen knife (/obj/item/kitchen/knife), "knife")
 - the kitchen knife (/obj/item/kitchen/knife): melee attack chain(Nancy Rose (/mob/living/carbon/human), the small cheese wedge bread (/obj/item/food/bread/empty), "icon-x=12;icon-y=18;left=1;scr...")
 - Nancy Rose (/mob/living/carbon/human): ClickOn(the small cheese wedge bread (/obj/item/food/bread/empty), "icon-x=12;icon-y=18;left=1;scr...")
 - the small cheese wedge bread (/obj/item/food/bread/empty): Click(the floor (150,152,2) (/turf/open/floor/plasteel), "mapwindow.map", "icon-x=12;icon-y=18;left=1;scr..."

**Comment by Sealed101** [comment]
this was fixed at some point an i think it was 
- #69733

cuz most of the food's intended reagents weren't spread over slices properly, ending up in 1 or 2 that were initialized first
