### ISSUE TITLE
Broken plants

### ISSUE THREAD

**Issue by TheLeopold** [tgstation/tgstation#55370]
Reporting client version: 513.1532

## Round ID:
[151631](https://scrubby.melonmesa.com/round/151631)

Bungo fruit do not contain pit.
Densified chemicals halves yield but do not doubles chemicals.
World peas cant be juiced.
Maybe something else?

Reproduce:
1. Use bungo fruit
2. ???
3. Juice World peas

**Comment by uBadush** [comment]
Densified chemicals never doubled the existing amounts of chemical, it doubles the amount of chemicals a plant can store

**Comment by spessbro** [comment]
would you please tell us the steps to reproduce the bungo fruit one
the world peas are not made to be juiced and densified chemicals are working as intended

**Comment by MrMelbert** [comment]
The bottom three have been fixed

The top one is a duplicate issue

This issue can be closed safely
