### ISSUE TITLE
Apparently the small backup centcom shuttle can happen sometimes?

### ISSUE THREAD

**Issue by MrDoomBringer** [tgstation/tgstation#55380]
Reporting client version: 513.1536

## Round ID:
[151684](https://scrubby.melonmesa.com/round/151684)

## Testmerges:
- [Remove SM from delta station atmos and put it in engi](https://www.github.com/tgstation/tgstation/pull/55285)
- [Filterrific!](https://www.github.com/tgstation/tgstation/pull/55246)
- [Bring back Kilostation v3.0](https://www.github.com/tgstation/tgstation/pull/54588)

## Reproduction:
No idea how to reproduce, just saw this happen and the only online admin confirmed they weren't the cause of it
![image](https://user-images.githubusercontent.com/29008542/101315302-46a50800-3828-11eb-8dcb-da423baf50e0.png)
![image](https://user-images.githubusercontent.com/29008542/101315320-4d337f80-3828-11eb-8ed5-989266fa52e4.png)
soon after like 5 crew got gibbed because the real shuttle came in and took it's place
![image](https://user-images.githubusercontent.com/29008542/101315365-6b997b00-3828-11eb-9e5b-bafd00b43307.png)
![image](https://user-images.githubusercontent.com/29008542/101315372-6e946b80-3828-11eb-891b-72b5cec9c155.png)
finally, we got a shuttle leave message without the train shuttle actually leaving (i guess it was attached to the backup shuttle somehow?) and the round ended soon after
![image](https://user-images.githubusercontent.com/29008542/101315503-aac7cc00-3828-11eb-93e7-9c1e1f67e737.png)

**Comment by MrDoomBringer** [comment]
"and mention that the shuttle was purchased at the same time the shuttle was called"
t. shaps

**Comment by msgerbs** [comment]
I was able to reproduce this and I'll take a shot at fixing it.

1. Call emergency shuttle
2. IMMEDIATELY afterward, purchase a shuttle (I used admin tools to call the shuttle so I could hit the 2 buttons very quickly here)
3. At this point, although shuttle manipulator shows the backup shuttle as being in flight, the rest of the game does not agree and it appears the shuttle is still docked at centcom
4. Call the shuttle _again_
5. At this point everything appears normal to the crew, in the shuttle manipulator you can see both shuttles are in route
6. The backup shuttle arrives and sends its arrival message, but the wall displays and status tab show the shuttle is still on the way
7. The purchased shuttle arrives on top of it, gibbing anyone aboard
8. The purchased shuttle leaves as normal (I'm assuming some of the other shuttle changes in the last 2 years fixed the shuttle never leaving, or it's random)

My guess is that the shuttle is not present when the shuttle actually tries to start moving, causing the backup to move instead but when the new shuttle loads up it resets the emergency shuttle status in SSShuttle, leaving the backup shuttle just kinda doing its own thing. Will definitely have to do some digging but it should be fixable.
