### ISSUE TITLE
sapient lesser ash drake (from a bolt of change) was moving reeeeeeaaaallly slowly

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#55381]
are we sure that some of the code from space dragons isn't affecting normal lesser ash drakes?

**Comment by IndieanaJones** [comment]
Space dragons and ash drakes don't share code anymore.  Space dragon is a branch of the hostile mob.

**Comment by TheBonded** [comment]
lesser ash drakes move slowly. they are not fast. it is possible you had walk enabled (shift + walk keybind toggles it)
