### ISSUE TITLE
Using radio prefixes (";" for example) will not talk to the radio while in critical.

### ISSUE THREAD

**Issue by 170141183460469231731687303715884105727** [tgstation/tgstation#55386]

**Comment by prodirus** [comment]
Not being able to talk into comms in crit is intended: #54970.

The semicolon showing up might be a legitimate issue, though.

**Comment by dragomagol** [comment]
It seems to keep the semicolon but not the other radio prefixes

**Comment by Dorsisdwarf** [comment]
Radio prefixes shouldn't show up if you try to send a radio message while not able to use the radio
