### ISSUE TITLE
The 'maid apron' accessory has side and back sprites for it's normal icon state

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#55393]
## Reproduction:

The maid apron in `icons/obj/clothing/accessories.dmi` has both sidesprites and a backsprite for what is supposed to be a normal object icon state. So dragging it around will make the sprite change directions even though it's a normal object. 

The on-mob sprite for it is identical, in that both have the same front sprite, side sprites, and back sprite. Makes me think someone didn't finish cleaning up their copy paste, or something.

**Comment by dragomagol** [comment]
This also applies to the pirate coat, so there's probably a whole bunch of them like this.
