### ISSUE TITLE
missing sprites: "used" facehugger in face and telebaton on armor slot

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#55405]

**Comment by dragomagol** [comment]
The used facehugger seems to have a proper face sprite.

**Comment by Tlaltecuhtli** [comment]
i saw a queen attack a dude with it and it turned into a missing sprite, maybe damage overlays?

**Comment by dragomagol** [comment]
Could be; for both was it the checkerboard texture or was it just invisible?

**Comment by Tlaltecuhtli** [comment]
it became the purple black goofball thing
