### ISSUE TITLE
Materials disappearing when connecting Ore Silo to ORM via bluetooth.

### ISSUE THREAD

**Issue by Taloman1** [tgstation/tgstation#55426]
After playing a Free Golem and gathering enough points to create R&D Computer and Protolathe, I used a Multitool to get the buffer from a built Ore Silo to link up the ore in the Ore Redemption Machine. After clicking on ORM to link, the ore in the ORM disappear permanently. This has happened twice. Easily recreated for testing.

**Comment by AnonymousNow** [comment]
Ah, good, I was looking to report this bug myself.
I've had it happen to me twice, both times in the Golem Shuttle. However, I've been unable to recreate it in testing (thanks to AaronTheIdiot for helping with that). I'm going to do a little more golemwork and see if it pops up again.

**Comment by TheBonded** [comment]
This happens if the free golem ORM is on icebox's middle level, as it spawns connected to the station silo. It connects to the station silo because the second level on icebox is considered a station z level.

**Comment by TheBonded** [comment]
better documented in #60944 and it's comments
