### ISSUE TITLE
auto drop n roll ???

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#55434]
151883

i was ling and set a can on fire while wearing fireproof suit, without touching any keyboard, my character started "drop n roll" in the fire, and once it ended it did it again multiple times until i got killed while stunlocked

**Comment by interestingusernam3** [comment]
Is your keyboard/mouse dying?

**Comment by SuperNovaa41** [comment]
i've never experienced this, you might've just had some weird key issues
