### ISSUE TITLE
The clownplanet clowns die at roundstart + some other stuff

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#55448]
![image](https://user-images.githubusercontent.com/58055496/101859176-08596280-3b20-11eb-9bdc-eaa043097c00.png)
![image](https://user-images.githubusercontent.com/58055496/101859221-1c9d5f80-3b20-11eb-8379-be2b98ba0d6d.png)
![image](https://user-images.githubusercontent.com/58055496/101859255-32128980-3b20-11eb-99aa-8b3c66f4cadc.png)
![image](https://user-images.githubusercontent.com/58055496/101859238-24f59a80-3b20-11eb-9757-d50d6463e83f.png)

This means there are no clowns to protect the ruin, and also causes some unwanted miasma generation.

**Comment by redguy999** [comment]
always thought that was intentional
