### ISSUE TITLE
Ice-land 'Lava' under rock mining, as well as chasms.

### ISSUE THREAD

**Issue by AdmiralYolo** [tgstation/tgstation#55459]
## Round ID: [151955](https://scrubby.melonmesa.com/round/151955)

If you discovered this issue from playing tgstation hosted servers: Manuel, Specifically the Icebox map.

## Reproduction: First, grab any mining tool
                             Second, mine any rock on below the station's Z-Level
                             Volia, you have a patch of lava if you're on the bottom Z-Level, or if you're on the middle Z-level, you get 
                             a chasm into the lower level.
Step 1:
![TestCase1](https://user-images.githubusercontent.com/75840371/101901333-dad9eb00-3beb-11eb-89f8-3758af268457.png)

Step2:
![TestCase2](https://user-images.githubusercontent.com/75840371/101901445-052ba880-3bec-11eb-98f7-5478d8355430.png)

**Comment by wesoda25** [comment]
Is this _any_ rock, or just some in that area you were mining?

**Comment by Qustinnus** [comment]
https://github.com/tgstation/tgstation/pull/55462 @wesoda25 a fix was merged a while ago
