### ISSUE TITLE
Lava can spawn under rock walls and vice versa

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#55452]
## Reproduction:
1. Mine
2. Catch fire
3. ![hidden_lava](https://user-images.githubusercontent.com/53582584/101893433-99006480-3b59-11eb-90bb-836064ef4d6a.png)

@Qustinnus

**Comment by AdmiralYolo** [comment]
This also can occur on the Icebox map. On almost every tile.

**Comment by Qustinnus** [comment]
😳

**Comment by AdmiralYolo** [comment]
Yep, i've posted my own report about it, but almost every tile that is mined is a lava-pool on the bottom level, or a chasm.

**Comment by iwishforducks** [comment]
This is a noob trap. There's already enough noob traps regarding mining.

**Comment by Qustinnus** [comment]
its not a "noob trap" its a bug

**Comment by Qustinnus** [comment]
D

**Comment by Qustinnus** [comment]
fixed in a pr

**Comment by iwishforducks** [comment]
i'm so stupid
