### ISSUE TITLE
Nightmare's attack deletes items

### ISSUE THREAD

**Issue by Losenis** [tgstation/tgstation#55464]
An attack by a nightmare will outright delete light-capable items rather than render them on a lightless broken state. This can be a nuisance at best and outright game-breaking at worst with limited items if not items that only exist once in the shift. This extends to items that are not yet producing light, even if you're inside a mech.

More specifically, in a situation where you're in a ripley, an attack by a nightmare will, all at the same time:

Destroy the Ripley's light.
Destroy your hardsuit's helmet (Engineering in the situation but will also extend to Atmos and Heads hardsuits, good luck if the SM goes kaput and you needed that rad + fire protection of the CE hardsuit or toxins is on fire and the atmos hardsuit is rendered useless.)
Destroy a welding hard hat, despite not causing light due to being inside a backpack. This may also extend to firefighter helmets and the sort, adding to the firefighting issue of above.
Destroy an experimental welding tool, despite being turned off and inside a belt.

Instances where the item (mech, hardsuit) is damaged rather than completely destroyed are to my knowledge unrepairable as of yet.

**Comment by timothymtorres** [comment]
This behavior is intended, see - #58000
