### ISSUE TITLE
Lasers pass through blob tiles

### ISSUE THREAD

**Issue by vkalls** [tgstation/tgstation#55472]
## Reproduction: 
1. Shoot laser at core surrounded by blob tiles
2. Blob go die

I think coderbus already knows about this, but making a report anyway.

**Comment by dragomagol** [comment]
You can also just walk right over blob tiles

**Comment by dragomagol** [comment]
Will be fixed by #55495

**Comment by ArcaneDefence** [comment]
Fixed by kevinz
