### ISSUE TITLE
Pods won't launch when Nar'sie gets summoned

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#55474]
Reporting client version: 513.1536

## Round ID:
[151994](https://scrubby.melonmesa.com/round/151994)

## Testmerges:
Manuel

## Reproduction:
0. Have Nar'sie get summoned
(next 2 can be done in any order)
1. Get to a pod
2. Wait for delta
3. press the launch button
4. cry as pod doesn't launch

When you first press the launch button, it counts down from 6. When it finishes, it gets stuck at 10 and the button can be spam clicked to spam messages, but it never launches.

**Comment by Googles-Hands** [comment]
Cry because this still hasnt been fixed

**Comment by gbfree** [comment]
Is it really a bug ?
narsie_start_destroy_station both raise the security level to delta and lockdown the shuttles (escape pods included).
https://github.com/tgstation/tgstation/blob/6c01cc2c010c8dc15c5500434ae8e55261511781/code/modules/power/singularity/narsie.dm#L240

**Comment by Googles-Hands** [comment]
@dragomagol Since you added the labels, any chance you know if this is a bug or not?

**Comment by Mooshimi** [comment]
> Is it really a bug ? narsie_start_destroy_station both raise the security level to delta and lockdown the shuttles (escape pods included).
> 
> https://github.com/tgstation/tgstation/blob/6c01cc2c010c8dc15c5500434ae8e55261511781/code/modules/power/singularity/narsie.dm#L240

After discussion with others, this line has shown that the pods not leaving after nar'sie has been summoned is intentional. Thanks for pointing this out.
