### ISSUE TITLE
Stripping log colours aren't consistent with other attack log colours

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#55489]
## Testmerges:
None

## Reproduction:
Someone being stripped of their belongings was red instead of orange and vice versa in player logs.

**Comment by LemonInTheDark** [comment]
This is my fault I see

**Comment by dragomagol** [comment]
Another issue I noticed with this is that the stripper and strippee get the same message written to their logs (instead of something like "has been stripped of X by Y" and "has stripped Z of X")
