### ISSUE TITLE
Icebox generation on top level is fuck

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#55493]
Reporting client version: 513.1526

## Round ID:
[152070](https://scrubby.melonmesa.com/round/152070)

## Testmerges:
None!

## Reproduction:
Top level of icebox rock just didn't spawn correctly.
It was completely empty apart from the thin formation surrounding the station and the various ruins.
Also this spawned.
![image](https://user-images.githubusercontent.com/68032262/102003127-4fe81600-3cfb-11eb-9667-4c1937526728.png)
Good luck with this one.

**Comment by ATH1909** [comment]
does this consistently happen on all icebox rounds, or just some of them?

**Comment by brotherbeyondd** [comment]
Only noticed it on that one, I try to play as few icebox rounds as possible.

**Comment by brotherbeyondd** [comment]
Can confirm it's every time.
