### ISSUE TITLE
Bite variables messed up for lots of botany food

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#55527]

**Comment by ArcaneDefence** [comment]
![image](https://user-images.githubusercontent.com/51932756/102115947-7c825780-3df9-11eb-8062-a4fc36093d0c.png)
lol

**Comment by MrMelbert** [comment]
expanding on this issue, you eat pretty much all grown botany food in one bit (even stuff like omegaweed)

in the past, only 2(?) plants could be eaten in one bite - apples and sweet potatoes - which was a unique feature about them botanists could use to consume a ton of reagents at once, but now everything can do it

**Comment by Qustinnus** [comment]
sounds like i fucked up some math
