### ISSUE TITLE
Private cargo orders don't work

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#55521]
Reporting client version: 513.1536

## Round ID:
[152141](https://scrubby.melonmesa.com/round/152141)

## Reproduction:

1. Order something privately
2. It appears under Current Cart
3. It never ends up in the shuttle and isn't cleared from Current Cart (can be cleared manually though)

**Comment by Tlaltecuhtli** [comment]
were you using the request console (the one outside) ? using main console to buy stuff works fine

**Comment by cacogen** [comment]
It's something I've noticed as cargo tech. Someone orders something privately and it sits in the Current Orders tab forever, never to be fulfilled.

**Comment by cacogen** [comment]
I think it probably has to do with whether their account has enough money or not
