### ISSUE TITLE
Briefcase Launchpad Bug

### ISSUE THREAD

**Issue by Eldeen** [tgstation/tgstation#55523]
Reporting client version: 513.1536

## Round ID:[152148](https://scrubby.melonmesa.com/round/152148)
152152

## Reproduction:
I was attempting to use a briefcase launchpad to steal an item for my objective, when I attempted to place the launchpad down it instead vanished without a trace, at first I assumed it was a bug with trying to using it in space but I had an admin attempt to use one in the admin area, same results.

1. Use the briefcase to turn it into launchpad mode.
2. It vanishes without a trace.

**Comment by XDTM** [comment]
Fixed by #55478 i presume

**Comment by Fikou** [comment]
fix merged
