### ISSUE TITLE
You don't know if there is plasma in the air

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#55530]
Reporting client version: 513.1536

## Round ID:
[152168](https://scrubby.melonmesa.com/round/152168)

## Reproduction:
 The alert just doesn't apear. You'll quietly take toxin damage

**Comment by Ghilker** [comment]
Both the too much toxin alert and the too much pressure alert are not working

**Comment by Pugie** [comment]
Feature

**Comment by dragomagol** [comment]
Reincarnation of #51138

**Comment by timothymtorres** [comment]
Duplicate of #51138
