### ISSUE TITLE
Monkeying people sometimes creates an invisible copy of them? 

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#55539]
## Testmerges:

I've observed this a few times today. Pretty sure this was one of the rounds. From what I can tell, when you inject someone with a monkifier mutation, it might create an invisible version of them? For the round in question, I turned bob oakland into a monkey, and at some point later when I was dead, I jumped to his mob. I ended up going to the roughly the place that I turned him into a monkey, but he was a monkey at the time and somewhere else completely. Later on other players noticed and made a big event out of it. 

I want to say it was caused by #55238 but idk

**Comment by dragomagol** [comment]
May be fixed by #55535

**Comment by wesoda25** [comment]
152205 Bagil

Happened in a DNA console this time.

It creates an invisible version of yourself, @Jared-Fogle  saw it too
