### ISSUE TITLE
Griddle and Bonfire Issues

### ISSUE THREAD

**Issue by Owai-Seek** [tgstation/tgstation#55543]
## Round ID: N/A, Local Test

Has happened several times on a downstream, went on my TG fork to test it out.

## Reproduction:

~After a round has gone on for `30-35 minutes, Griddles will cease functioning completely.~

Bacon burning to ashes on a griddle, will cause it to cease functioning.

Cannot deconstruct a griddle (in both its on, or off position.)

Destroying and reconstructing griddle seems to fix it.

Cannot cook any type of meat on a bonfire. Period. (Tested with Slabs, Patties, Meatballs, and Cutlets)

https://github.com/tgstation/tgstation/pull/55319

On an unrelated note, I can't make burgers in public botany anymore, and that makes me sad. Wish there was a ghetto way to food process stuff even if you get 1:1 instead of 1:3 meatballs.

**Comment by Qustinnus** [comment]
wtf weird

**Comment by Qustinnus** [comment]
and regarding the public botany thing: buy the grilling starter kit.

**Comment by Qustinnus** [comment]
I'll need some more proper repro on the 30-35 minute thing, if other people get it I'll look into it some more but I cant find anything related to it personally. Fixed the other things though.

**Comment by jacklecroy** [comment]
That's probably the null thing.

**Comment by wesoda25** [comment]
I had my griddle break like 10 minutes into a round today. Had to destroy and rebuild.

**Comment by Qustinnus** [comment]
@wesoda25 can you describe how it broke; what couldnt you do anymore?

**Comment by wesoda25** [comment]
Couldn’t cook anything. I could put things on fine, they just wouldn’t cook. Before I was grilling a bunch of meatballs and patties, and actually flattened (or at least tried to) a few meatballs while on the griddle.

**Comment by Qustinnus** [comment]
how did you put them on @wesoda25 i need more details

**Comment by TheRealDecoy** [comment]
I think I ran into this issue as well, but instead of the problem being related to round time it appears to occur after attempting to cook bacon on the griddle. So long as I do not attempt to cook bacon I am able to cook all other meats without issue for the entirety of a round. When cooking raw bacon it appears to cook as normal, but once ready it almost immediately bursts into fire and can no longer be interacted with. Eventually the bacon turns into ash and the griddle does not cook food afterwards.

**Comment by Owai-Seek** [comment]
Found the underlying issue.

Cooked 20 Cutlets, 20 Bacon. Both sets worked fine.
Burnt 3 Cooked Cutlets and 3 Cooked Bacon on each Grill.
Cooked Cutlets produced Burnt Mess. Bacon caught on fire, and turned to ashes.
Bacon Grill currently non-functional.
Cutlet Grill functional, was able to burn 7 additional cutlets.

Bacon burning into ashes while on the grill seems to be what causes it to get bricked.

**Comment by Owai-Seek** [comment]
Hopefully all of these issues were resolved with the merge of the above PR fix. If not, well, can always open a new issue.
