### ISSUE TITLE
Kinetic Accelerators dealing full damage in a pressurized enviroment

### ISSUE THREAD

**Issue by ChocolateBickie** [tgstation/tgstation#55550]
Reporting client version: 513.1538

## Round ID:
[152230](https://scrubby.melonmesa.com/round/152230)

## Reproduction:
Take a Kinetic Accelerator, go to the station, make sure pressure is normal e.g. not lavaland pressure. Fire KA on a mob. Watch as unarmored humanoids crit in two hits.
Basically it's like having the traitor 'Kinetic Accelerator Pressure Mod' except you don't need to be a traitor, it's always active and it uses no slots on your Kinetic Accelerator.

If this was a secret buff, why do you think miners needed buffs?
If this is a bug, which I think it is, miners now have a 50+ damage weapon round start.

**Comment by LemonInTheDark** [comment]
god damn it @silicons

**Comment by ATH1909** [comment]
miner borgs rise up

**Comment by ATH1909** [comment]
did https://github.com/tgstation/tgstation/pull/55495 fix this?

**Comment by LemonInTheDark** [comment]
it claims to, mind testing?

**Comment by Ewwmewgewd** [comment]
I did some testing and now it appears that KA deals way less damage in pressurized environment. Took me about 30 seconds to kill a monke on station and only about 5 seconds to kill monke on lavaland.

![image](https://user-images.githubusercontent.com/60656530/102678062-34bb5180-41a6-11eb-97e5-5bc75e077b38.png)
Rest in peace Pan Pan. He died in the name of science. o7

**Comment by LemonInTheDark** [comment]
Thank you dex
