### ISSUE TITLE
You can step on (and trip over) objects when two-handing push broom, if not wearing shoes.

### ISSUE THREAD

**Issue by Owai-Seek** [tgstation/tgstation#55567]
## Reproduction:

Wield broom in two hands, walk down hallway. Step on glass and light tubes because lizard. Cry.

**Comment by Losenis** [comment]
This also happens with banana peels. When you see a quadrillion peels on the hallway, the only way to swipe them is to crawl while wielding to avoid slipping.

**Comment by Owai-Seek** [comment]
I'm not much of a coder myself, but this was a PR that solved it over on Citadel. Granted, they had an older version of the broom.

https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13058
