### ISSUE TITLE
Fire Extinguishers clean floors faster than any janitorial implement

### ISSUE THREAD

**Issue by Capsandi** [tgstation/tgstation#55586]
## Round ID:

[Round ID]: # 152299 (not that it matters)

## Reproduction:

Take a fire extinguisher and spray down a dirty hallway.
Watch as the extinguisher cleans the entire hallway incredibly quickly
Realize that the common fire extinguisher cleans a 3 by 7 rectangle of flooring with only 5 units of water, without the inconveniences presented by foam or wet flooring.

The availability of fire extinguishers and their efficiency makes janitorial equipment and the janitors themselves useless. Even cleaner grenades work slower than these things.

**Comment by Capsandi** [comment]
oh fuck i did the thing where theres another issue which says the same thing ill close this

**Comment by Owai-Seek** [comment]
The other issue is this one for anyone curious.

https://github.com/tgstation/tgstation/issues/55498

**Comment by cacogen** [comment]
The issue we have at home: #55498
