### ISSUE TITLE
Prisons don't have griddles.

### ISSUE THREAD

**Issue by Owai-Seek** [tgstation/tgstation#55598]
## Reproduction:

They just, don't got em.

**Comment by Ewwmewgewd** [comment]
Is there a point in adding griddles if perma already has a microwave?

**Comment by Owai-Seek** [comment]
Can't microwave meat anymore, which means Griddle (or bonfire, once it's fixed) are the only ways to cook meat.

**Comment by ArcaneMusic** [comment]
As of #55830, i think we can say this is resolved since they no longer have meat anyway.
