### ISSUE TITLE
Jellyperson brain damage bug

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#55628]
## Reproduction:

>be slimeperson jelly type
>split to multiple bodies
>get enough brain damage on one of em
>healthy copies suddenly forgot galactic common

![Screenshot_45](https://user-images.githubusercontent.com/64209864/102685153-fad36500-4210-11eb-80ff-5394d67680d4.png)

**Comment by Sealed101** [comment]
can no longer reproduce - neither the brain damaged nor healthy bodies, when split, would create a body with no galactic common knowledge
