### ISSUE TITLE
New heretics via TP don't see influences created from previous influence generation

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#55635]
## Round ID:
Tested local

## Testmerges:
N/A

## Reproduction:
Start a round normally and use the TP to become a heretic, run `SELECT /obj/effect/reality_smash`, go find the 5 influences to see them normally.

Ghost, boot yourself to lobby, rejoin as someone new. Make them a heretic, run `SELECT /obj/effect/reality_smash`, **DO NOT AGHOST/JUMP TO THEM OR THE INFLUENCES WILL REVEAL TO YOU AS A SPECTATOR**, go to the previous 5 influence sites and fail to see them at all.
Go to the additional sites that were created from the second person becoming a heretic and see them normally.

This can be repeated several times over and have multiple generations of influences that a new heretic cannot see

**Comment by ArcaneDefence** [comment]
![image](https://user-images.githubusercontent.com/51932756/102698727-c655ae00-41fc-11eb-9750-1d48ba70a771.png)
The left side was heretic'd first.

![image](https://user-images.githubusercontent.com/51932756/102698752-f43af280-41fc-11eb-9f36-0c215dd55079.png)
Here you can see the first heretic seeing the second heretic's influence, but the second not being able to see the first.

**Comment by dragomagol** [comment]
Will be fixed by #55662
