### ISSUE TITLE
humanized monkeys still flee when beheaded

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#55638]
152473

**Comment by dragomagol** [comment]
Duplicate of #55544, although it looks like #55515 was supposed to fix this

**Comment by dragomagol** [comment]
Saw another dead (non-humanized) monkey fleeing yesterday, even when strapped to a roller bed

**Comment by spessbro** [comment]
i guess it's here to stay then

**Comment by Qustinnus** [comment]
i havn't heard of this bug in ages i think i fixed it a while ago
