### ISSUE TITLE
Crowbars disappear when used on griddles.

### ISSUE THREAD

**Issue by Ewwmewgewd** [tgstation/tgstation#55633]
## Round ID:
Locally tested.

## Reproduction:
1. Find a griddle.
2. Use a crowbar on it.

When you try using a crowbar on a griddle to take it apart, what happens is you get this message:
![image](https://user-images.githubusercontent.com/60656530/102697153-e359a380-4233-11eb-9310-a210cc9ffe15.png)
The griddle then gets taken apart, you get the machine frame, board and micro-laser, but no crowbar back.

**Comment by Ewwmewgewd** [comment]
I'm not sure if this should be reported as a separate issue, but when you try clicking with any item in hand on the griddle, you will hit the griddle and then place that item on top of it, regardless of intent.

**Comment by Qustinnus** [comment]
wtf

**Comment by ArcaneDefence** [comment]
It's putting the tool on the griddle and deconstructing it afterwards.
