### ISSUE TITLE
Recyclers Eat Dynamic Lighting

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#55643]
## Reproduction:

1). Get a recycler, doesn't matter if its normal or special.
`/obj/machinery/recycler`
2). Get a source of dynamic lighting, used a borg headlamp in this case
3). Go towards the recycler.
4). Have your dynamic light get eaten.
5). Enjoy having to reconnect to fix your lighting.

Maybe the same kind of thing that happened with uh, #55382 

But I haven't even looked at the code just a guess.

**Comment by Dorsisdwarf** [comment]
fixed by #55565
