### ISSUE TITLE
Monkeys Don't become human when fed mutadone.

### ISSUE THREAD

**Issue by vkalls** [tgstation/tgstation#55648]
## Testmerges:
#55614 

## Reproduction:
Make a monkey either by grabbing one roundstart or a monkey cube, feed them mutadone, watch as they stay the same. This is probably because they don't load with a completed monkified gene and you have to fix this by going into a genetic scanner and finishing and then cancelling the gene.

**Comment by dragomagol** [comment]
This is almost certainly caused by that test merge, so you should probably post this message in the PR's comments

**Comment by Winterous** [comment]
Honestly I think this should be a feature. Natural monkeys shouldn't only be monkeys because they HAVE a mutation, it should require a mutation to make them human, like it does to make a human into a monkey.

**Comment by Qustinnus** [comment]
fixes this hopefully
