### ISSUE TITLE
Regenerative cores from legions can be eaten

### ISSUE THREAD

**Issue by SmArtKar** [tgstation/tgstation#55647]
## Round ID:

<!--- **INCLUDE THE ROUND ID**
If you discovered this issue from playing tgstation hosted servers:
[Round ID]: #152546

## Testmerges:

#55614

## Reproduction:

Try to heal someone with legion core. They eat it. They don't heal and it's not applied, however, you are healed instead.

**Comment by CoffeeDragon16** [comment]
Looks like inherited behavior from its status as an organ.
