### ISSUE TITLE
Firing a mech's gun results in hitting your own mech if you're moving forwards

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#55641]
## Reproduction: 

Spawn a mech, add any common gun to it including the plasma cutter and fire whilst walking forwards. Your mech will most likely be hit.

## Description: 

Any mech, including durands which are incredibly slow will be whacked by their own projectile (even from plasma cutters) if they walk forward while firing. While this was a very rare occurrence before the latest projectile changes, now it's virtually a guarantee if you fire when walking forwards.

**Comment by necromanceranne** [comment]
@silicons more mech problems it seems
