### ISSUE TITLE
Pie'd AI's vision is blurry even after pie is washed off

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#55670]
## Round ID:
Reproduced on local

## Reproduction:
Throw a cream pie at an AI. Fail to wash it off with anything but a shower. Even when the pie is gone from the AI's sprite, the AI still has blurry vision. Only way I've found to fix it is to aheal.

**Comment by dragomagol** [comment]
![image](https://user-images.githubusercontent.com/66640614/102813522-cfba5400-437d-11eb-890a-897eb5a5d741.png)
![image](https://user-images.githubusercontent.com/66640614/102813557-de087000-437d-11eb-9250-49cb0cff1e48.png)
![image](https://user-images.githubusercontent.com/66640614/102813581-ec568c00-437d-11eb-83fc-fbda9b1dd120.png)

**Comment by Ewwmewgewd** [comment]
Should this effect even apply to AI in the first place considering AI is looking through the cameras?

**Comment by wesoda25** [comment]
Yes it’s funny

**Comment by Makarov22** [comment]
HONK!
