### ISSUE TITLE
Dream Daemon crashes when loading tgstation

### ISSUE THREAD

**Issue by norsvenska** [tgstation/tgstation#55686]
When loading any .dmb from the TG github, without edits, Dream Daemon crashes.

Steps to reproduce:
Download a fresh copy of the source code
Compile it and run Dream Daemon

**Comment by Ewwmewgewd** [comment]
This is an issue related to the latest BYOND update. You cant host the game without daemon crashing.

For now you can get some of the earlier versions from http://www.byond.com/download/build/513/
513.1536 works 100%

**Comment by willox** [comment]
Isn't it just because extools crashes on the latest version?

**Comment by LemonInTheDark** [comment]
Is this even an issue? Isn't it just "We tied ourselves to extools and it's not updating, so we're stuck?"

**Comment by celotajstg** [comment]
Everything works fine in 514.1552, but I do have to note it is without extools I think.
