### ISSUE TITLE
from what I can tell from the code, liches can be soulstoned again

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#55693]
https://github.com/tgstation/tgstation/pull/46881 made liches unable to be soulstoned, both for a balance reason (it's kind of a waste of 2 points if a chaplain can just run up to your corpse while you're rezzing and use their dusty old shard to permakill you/bypass the gimmick of Bind Soul) and for a logical reason (your soul is in your phylactery, not your body).

However, I believe that when all code related to devils was removed from the game, this hasSoul check/interaction was also removed, meaning that there's nothing stopping liches from being soulstoned now.

**Comment by ATH1909** [comment]
![image](https://user-images.githubusercontent.com/42606352/102935973-d1af1080-446c-11eb-9a67-2a15ae6eca15.png)
Yep, it was https://github.com/tgstation/tgstation/pull/53612 that did this.

@TiviPlus @Fikou

**Comment by timothymtorres** [comment]
This was fixed with #63540
