### ISSUE TITLE
the DIY dish drive kit doesn't contain a wrench

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#55700]
![image](https://user-images.githubusercontent.com/42606352/102986173-03a88d00-44d6-11eb-9d14-0b94012cdb08.png)
you can't anchor the machine frame, so you can't build the dish drive with the kit's contents alone.

**Comment by Qustinnus** [comment]
can this be even considered a bug? you dont get a full tool set for buying a bed at ikea either.

**Comment by Tlaltecuhtli** [comment]
ikea gives you tools, you can use the allen key as screwdriver, its just that everyone has an hand drill and use it instead

**Comment by ATH1909** [comment]
> can this be even considered a bug? you dont get a full tool set for buying a bed at ikea either.

but the kit contains a screwdriver

**Comment by Mickyan** [comment]
This isn't a bug and you don't need to anchor the frame to build the dish drive
