### ISSUE TITLE
you can make cult runes in custom areas on lavaland

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#55718]
step 1: be a cultist
step 2: go to the ash walker nest
step 3: notice that the game prevents you from carving runes inside of the tendril's chamber, but NOT in the custom area that the ashies made/designated (using the area management button near the langauge and skill tracking buttons) to keep the ash storms out of their base
step 4: make offer, empower, and teleport runes in the ash walker base and convert pretty much the entire ash walker tribe, including the new spawns/respawns from their stash of 24+ eggs
step 5: summon nar'sie

**Comment by Sealed101** [comment]
- #75589
