### ISSUE TITLE
Gas filter failed to filter gas

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#55714]
## Testmerges:
- #54462 

## Reproduction:
1. Hook up a feed of low pressure, low temperature gas to port 2 of a gas mixer (I was using tritium at 2.7K)
2. Hook up a feed of room temperature, high pressure gas to port 1 of a gas mixer (I was using a 50/50 mix of oxygen and nitrogen at 293.15K and 4500kPa)
3. Set the mixer to mix at a ratio of 75% port 1, 25% port 2.
4. Receive a mixture of 30% port 1, 70% port 2.

![Mixer Failure](https://user-images.githubusercontent.com/53582584/103082166-5ba2ca80-458e-11eb-9ed3-1e435d0e4b00.PNG)

**Comment by Dennok** [comment]
what does the filter have to do with it?

**Comment by TemporalOroboros** [comment]
Apparently it filters by pressure, not moles. My bad.
