### ISSUE TITLE
Paper wizard robe is just referred to as "robe" in messages to chat

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#55727]
## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/103107655-31d0be80-45f5-11eb-9968-02f10ad3a435.png)

**Comment by SpaceManiac** [comment]
Looks like a use of `\The` in a context where writing just `The` would have worked, should be an easy fix

https://github.com/tgstation/tgstation/blob/6e950daccc7420b80e52b6b4a36c1eae613a2cb0/code/modules/clothing/suits/wiz_robe.dm#L162-L180
