### ISSUE TITLE
You can't open a door while you're in a mech, again

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#55732]
Round ID: [152867](https://scrubby.melonmesa.com/round/152867)

## Reproduction:

Get all access and hop into a mech. Walk into a powered door, it doesn't open.

## Description:

Doors that you have access to and are powered won't open in a mech, so you have to exit the mech then open them. Very frustrating if you're chasing someone or you're moving through departments e.g. in a medical mech trying to rescue someone.

**Comment by dragomagol** [comment]
Will be fixed by #55748
