### ISSUE TITLE
Corpses no longer appear dead upon examination under certain conditions.

### ISSUE THREAD

**Issue by Togopalis** [tgstation/tgstation#55744]
## Round ID: 
[152920](https://scrubby.melonmesa.com/round/152920)

## Testmerges: 
#55604: 'LINDA Reforged' by LemonInTheDark at commit fade68433f
#55614: 'Refactors monkeys into a species' by Qustinnus at commit b2335f2b4f

## Reproduction:
 Die and examine your corpse as a ghost. It will not display 'They are limp and unresponsive, with no signs of life.' as it usually does. There are certain ways to see the text, such as when you are inside your body, but I've been notified that under certain conditions living players are not able to tell if dead players are dead either.

**Comment by dragomagol** [comment]
Will be fixed by #55743

**Comment by Togopalis** [comment]
Ah, sorry. I missed it

**Comment by dragomagol** [comment]
You're good! The PR isn't merged yet, just connecting them for then.
