### ISSUE TITLE
Disposals stacking machine console doesn't show stored materials

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#55740]
Reporting client version: 513.1539

## Round ID:
[152913](https://scrubby.melonmesa.com/round/152913)

## Testmerges:
- [Hark! The Medieval Reality Simulation Dome Emergency Shuttle! (+speech mutation, NOTELEPORT fixes and teambuilder improvements)](https://www.github.com/tgstation/tgstation/pull/55424)

## Reproduction:

1. Recycle something with the disposals recycler
2. Wait for the stacking machine to pick it up
3. Check the stacking machine console
4. 
![](https://i.imgur.com/WchcavX.png)
5. Deficit

**Comment by Arkatos1** [comment]
Not a bug. Stacking machine automatically transfers it's contents to it's linked ore silo. Only if there is no linked ore silo the contents will be stored inside the stacking machine and can therefore be manuály released.

**Comment by cacogen** [comment]
It would be nice if it said that it was linked to the ore silo in the UI.
