### ISSUE TITLE
Odysseus and (S)laughter demons both create "ghost" lighting after voring someone with directional lighting

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#55742]
## Round ID:
//////

## Testmerges:
//////

## Reproduction:
Demons-
Spawn an assistant in a dark room and turn their PDA light on.
Spawn a laughter demon and crit the assistant, then eat em.
Their directional lighting will remain wherever you ate them.

Odysseus-
Spawn an assistant in a dark room and turn their PDA light on.
Spawn an odysseus and equip it with the portable sleeper.
Collect the assistant with the sleeper and the directional lighting will remain until the assistant is later deposited (which causes the directional lighting to disappear).

**Comment by timothymtorres** [comment]
This looks related to #38109

**Comment by Sealed101** [comment]
can no longer reproduce; hopefully this bug stops popping up
