### ISSUE TITLE
You can't change your hair/beard with an electric razor in front of a mirror.

### ISSUE THREAD

**Issue by Makarov22** [tgstation/tgstation#55756]
You can't change your hair/beard with an electric razor in front of the bathroom mirrors.

## Round ID:

Round ID: [152958](https://scrubby.melonmesa.com/round/152958) (has been happening for a few days in different maps though)

## Reproduction:

Pick an electric razor
go in front of those mirrors in the public bathroom
"You need a mirror to properly style your own hair!"

**Comment by RaveRadbury** [comment]
You don't need a razor, you can just click the mirror directly.

**Comment by Pugie** [comment]
The "You need a mirror to properly style your own hair!" refers to just needing a mirror to change your own hair, no razor included.
You use razor to change hairstyles of other spacemen, target head or mouth on help intent for hair and beard respectively. Harm intent to make them bald.
