### ISSUE TITLE
Cannot cook Dough, Dough Slices, or Flat Dough on bonfires. (And probably more.)

### ISSUE THREAD

**Issue by Owai-Seek** [tgstation/tgstation#55757]
## Round ID: N/A. 

Found on downstream, but 99% certain it's an upstream issue. I can probably test later.

## Reproduction:

Try to bake bread on a fire and cry as it no longer works.

**Comment by Qustinnus** [comment]
man why do you like bonfires so much

**Comment by Pugie** [comment]
> man why do you like bonfires so much

Wait till someone makes them cook food instantly then they'll be godly for food plumbing

**Comment by Owai-Seek** [comment]
I like bonfires because I can slide food onto them with a tray instead of placing the items one by one on the grill, and also, because I like cooking food in the small botany room when chefs decide to only put out fried soda cans and paper scraps.

**Comment by Sealed101** [comment]
dough requires baking via an oven as of #60515, rendering open-fire/microwave baking obsolete
