### ISSUE TITLE
Addictions aren't triggering

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#55764]
## Round ID: 
[152988](https://scrubby.melonmesa.com/round/152988)

## Reproduction: 
I took two 10u happiness pills. I didn't get a happiness addiction. This worked like, last month. I added 19u in the thunderdome in the next round, still no addiction.

**Comment by necromanceranne** [comment]
Good time for bathsalts.

**Comment by necromanceranne** [comment]
@nightred Might be related to your stomach changes

**Comment by dragomagol** [comment]
Duplicate of #55245

**Comment by RaveRadbury** [comment]
Caused by #54797
