### ISSUE TITLE
Borged Heretics retain their "mist" ability.

### ISSUE THREAD

**Issue by AJHcHenry** [tgstation/tgstation#55781]
## Round ID: [33473](https://scrubby.melonmesa.com/round/33473)

 33473

## Reproduction:

 During a heretic round, a heretic was borged as a sec borg. They were then able (as a borg) to use Ashen Shift.

**Comment by ATH1909** [comment]
this is fine.

borged (or polymorphed) wizards can still cast their (non-robed) spells; why not borged heretics?

**Comment by dragomagol** [comment]
Not a bug
