### ISSUE TITLE
Station Time is ticking ridiculously fast

### ISSUE THREAD

**Issue by Crushtoe** [tgstation/tgstation#55780]
## Round ID: 
[153052](https://scrubby.melonmesa.com/round/153052)

## Testmerges:

#54462: 'The Great Radio Rework: NTNET Part 1 of many.' by WarlockD at commit 0aea50f0dd
#55444: 'Refactors how movetypes are added and removed, No timers this time.' by Ghommie at commit 388dace6ac

## Reproduction:

1. Log in
2. Check the status tab.
3. Observe the station time is ticking absurdly faster and in much larger increments than server time, round time, or any ETA.

Possibly related is that Basil has been crashing a lot recently in the past few hours?

Recording of the time being funky wunky: 

https://cdn.discordapp.com/attachments/477643046989725696/792983053961265213/time.webm

**Comment by Jared-Fogle** [comment]
This doesn't look like a bug--station time is not supposed to be in lockstep with real time. It is what correlates with the night lighting, and so can't be.

**Comment by Jared-Fogle** [comment]
![image](https://user-images.githubusercontent.com/35135081/103204914-38895b00-48ad-11eb-89b6-fdf50e6f73f8.png)

**Comment by Jared-Fogle** [comment]
I don't even know why we have station time, I don't think anyone uses it for roleplay (and in fact, everyone just says round time anyway--like "20 minute shuttle call"), but I digress.
