### ISSUE TITLE
clown cars wont work

### ISSUE THREAD

**Issue by raphael2033** [tgstation/tgstation#55797]
Reporting client version: 513.1536

## Round ID:
[153102](https://scrubby.melonmesa.com/round/153102)

## Testmerges:
- [Refactors monkeys into a species](https://www.github.com/tgstation/tgstation/pull/55614)
- [LINDA Reforged](https://www.github.com/tgstation/tgstation/pull/55604)

**Comment by Jared-Fogle** [comment]
Recent PR merge fixed this.
