### ISSUE TITLE
Stepping in blood, or blood trails, without shoes, covers your entire body in blood.

### ISSUE THREAD

**Issue by Owai-Seek** [tgstation/tgstation#55804]
## Reproduction:

![1mvjvyVpy4](https://user-images.githubusercontent.com/7543955/103264084-a4d09100-4977-11eb-8835-a7193dfe3c68.gif)

**Comment by Ewwmewgewd** [comment]
This is a known issue.
#53300

**Comment by ArcaneMusic** [comment]
duplicate issue of ^
