### ISSUE TITLE
Monkey lings can use EMPs from vents.

### ISSUE THREAD

**Issue by Pugie** [tgstation/tgstation#55809]
Maybe not the biggest deal in the world all the time and could be argued it's a feature but being able to kill ai and comms shift start and emp any area on station from impervious to damage vents is frustrating to be on the receiving end of.

**Comment by Tlaltecuhtli** [comment]
i can exit vent and emp ai before turrets shoot so its not any different

**Comment by brotherbeyondd** [comment]
emp monkey is honestly the worst thing ever created by man
