### ISSUE TITLE
Kitchen freezers don't require access to open

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#55816]
## Round ID:
[153155](https://scrubby.melonmesa.com/round/153155)

## Testmerges:
None

## Reproduction:

 Spawn `obj/structure/closet/secure_closet/freezer/fridge` and try to open it without access while it's locked, works fine.
Try to close it, it closes, but doesn't lock again, telling you access denied. 
Put an ID on with proper access, open and close it normally, and the freezer locks itself when closed.

**Comment by wesoda25** [comment]
Always liked this, it allowed me to whip up some food when no chefs are on the station.

**Comment by Ewwmewgewd** [comment]
Why do these fridges have a lock in the first place? Which guy out there is like "alright, lemme put a lock on my fridge"?

**Comment by ShibaInuLord** [comment]
> 
> 
> Why do these fridges have a lock in the first place? Which guy out there is like "alright, lemme put a lock on my fridge"?

me

**Comment by Owai-Seek** [comment]
I figured this was intentional so people could cook food when there's no chef, AFAIK there's two different fridges, one that's locked, and one that's not.

**Comment by Tlaltecuhtli** [comment]
being able to make an hamburger if there is no cook shouldnt require the captain to come open the fucking fridge

**Comment by ArcaneDefence** [comment]
This issue is entirely unrelated to if people should or should not need kitchen access to open the refridgerators in the kitchen.

`obj/structure/closet/secure_closet/freezer/fridge` isn't respecting access as it should. 
Put the `/open` subtype in kitchens if you want them to not use access at all.
