### ISSUE TITLE
Fire alarms are completely broken.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#55820]
Reporting client version: 513.1539

## Round ID:
[153158](https://scrubby.melonmesa.com/round/153158)

## Testmerges:
- [LINDA Reforged](https://www.github.com/tgstation/tgstation/pull/55604)

## Reproduction:
1. have fire alarm go off
2. turn fire alarm off
3. open fire alarm panel
4. remove the wires and the electronics
5. be confused as the fire alarm goes off again

Destroying the fire alarm doesn't seem to fix the issue.
Fire alarms are also overly sensitive to temperature changes, going in and out of telecoms can cause the temp to drop enough to trigger the alarms, and it seems that even if you fix the temp, they still go off. (I almost completely siphoned all the air out of a room and replaced it with normal temperature air, and the alarm went off again).

This makes ice box basically unplayable before it even reaches the one hour mark.

**Comment by wesoda25** [comment]
The ghost of Freddy Alarms haunts the station

**Comment by LemonInTheDark** [comment]
See https://github.com/tgstation/tgstation/pull/55604 for a reply, as to the oversensitiveity, fire alarms trigger based on the temp at which humans should start taking temp damage.
