### ISSUE TITLE
Tearing down cult walls creates a hull breach

### ISSUE THREAD

**Issue by iwishforducks** [tgstation/tgstation#55821]
## Round ID:

I can't name a cult round as of recently off the top of my head, but it's fairly easy to reproduce.

## Testmerges:

N/A because this bug has been going on for a few weeks with test merges going in and out

## Reproduction:

Become an artificer and put down cult walls to keep baddies from breaking down into the cult base. When someone destroys the cult wall (like a juggernaut), it spaces the tile, creating a hull breach where there used to be a solid floor. Congrats, now your cult base is no longer habitable.

**Comment by Ewwmewgewd** [comment]
I couldn't reproduce this. 
Both ``/turf/closed/wall/mineral/cult`` and ``/turf/closed/wall/mineral/cult/artificer`` have a plating under them after they get destroyed.

**Comment by Ewwmewgewd** [comment]
Ah, I managed to reproduce this.
![image](https://user-images.githubusercontent.com/60656530/103320406-7f09c180-4a35-11eb-9d9a-a31915358be1.png)
So apparently if the wall is placed on a regular floor tile it will spawn a plating when destroyed, but if the wall is placed on a plating, it will delete the plating after it gets destroyed and create a hull breach.

**Comment by CoffeeDragon16** [comment]
Looks like this issue pertains to all destruction of walls. I couldn't find exactly what caused it.

**Comment by TheGamerdk** [comment]
> Looks like this issue pertains to all destruction of walls. I couldn't find exactly what caused it.

I think it's because plating doesn't have itself as a base turf, and ChangeTurf doesn't re-add the plating as a baseturf when run, you'd need to supply the new baseturfs
