### ISSUE TITLE
Bagil crashed with a massive runtime log relating to directional lighting

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#55835]
## Round ID:
[153197](https://scrubby.melonmesa.com/round/153197)

## Testmerges:
#54462

## Reproduction:
Had ~8000 runtimes related to directional lighting, seemingly related to this single player's lights.
It's a 200k line log

Here's one of the first ones
[2020-12-30 08:35:05.913] runtime error: Cannot execute null.forceMove().
 - proc name: cast directional light (/datum/component/overlay_lighting/proc/cast_directional_light)
 -   source file: overlay_lighting.dm,425
 -   usr: Cherry Graves (/mob/living/carbon/human)
 -   src: /datum/component/overlay_light... (/datum/component/overlay_lighting)
 -   usr.loc: the floor (120,118,2) (/turf/open/floor/plasteel/grimy)
 -   call stack:
 - /datum/component/overlay_light... (/datum/component/overlay_lighting): cast directional light()
 - /datum/component/overlay_light... (/datum/component/overlay_lighting): make luminosity update()
 - /datum/component/overlay_light... (/datum/component/overlay_lighting): on holder moved(Cherry Graves (/mob/living/carbon/human), the floor (120,117,2) (/turf/open/floor/plasteel/grimy), 1, 0)
 - CallAsync(/datum/component/overlay_light... (/datum/component/overlay_lighting), /datum/component/overlay_light... (/datum/component/overlay_lighting/proc/on_holder_moved), /list (/list))
 - Cherry Graves (/mob/living/carbon/human):  SendSignal("movable_moved", /list (/list))
 - Cherry Graves (/mob/living/carbon/human): Moved(the floor (120,117,2) (/turf/open/floor/plasteel/grimy), 1, 0)
 - Cherry Graves (/mob/living/carbon/human): Moved(the floor (120,117,2) (/turf/open/floor/plasteel/grimy), 1)
 - Cherry Graves (/mob/living/carbon/human): Moved(the floor (120,117,2) (/turf/open/floor/plasteel/grimy), 1)
 - Cherry Graves (/mob/living/carbon/human): Move(the floor (120,118,2) (/turf/open/floor/plasteel/grimy), 1, 0)
 - Cherry Graves (/mob/living/carbon/human): Move(the floor (120,118,2) (/turf/open/floor/plasteel/grimy), 1, null)
 - Cherry Graves (/mob/living/carbon/human): Move(the floor (120,118,2) (/turf/open/floor/plasteel/grimy), 1)
 - Cherry Graves (/mob/living/carbon/human): Move(the floor (120,118,2) (/turf/open/floor/plasteel/grimy), 1)
 - Ouroborus113 (/client): Move(the floor (120,118,2) (/turf/open/floor/plasteel/grimy), 1)
 - Cherry Graves (/mob/living/carbon/human): keyLoop(Ouroborus113 (/client))
 - Ouroborus113 (/client): keyLoop()
 - Input (/datum/controller/subsystem/input): fire(0)
 - Input (/datum/controller/subsystem/input): ignite(0)
 - Master (/datum/controller/master): RunQueue()
 - Master (/datum/controller/master): Loop()
 - Master (/datum/controller/master): StartProcessing(0)

**Comment by Azarak** [comment]
https://github.com/tgstation/tgstation/pull/55565

**Comment by Azarak** [comment]
The runtimes are because something external deletes the abstract effect, which in practice, nothing should be interacting with abstract effects. This is an issue with some things just messing with effects indiscriminately, and then having the abstract handlers runtime and fail to do their operation. I doubt this is what caused the crash, it just fails to move a non existing entity, and thats it
