### ISSUE TITLE
heretic blade teleport should have a saner teleportation or location blacklist

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#55832]
![img](https://i.imgur.com/RN3hQVk.png)

**Comment by brotherbeyondd** [comment]
lol no its cringe to watch heretics make 8 blades so they can just zipzap about

its funny to watch them teleport into the sm chamber and dust themselves tho

**Comment by ArcaneDefence** [comment]
find_safe_turf is used for a bunch of things, I'm not sure if that'd be considered a problem with the other methods of its use though
