### ISSUE TITLE
smartfridge refuses everything bug

### ISSUE THREAD

**Issue by TyrianTyrell** [tgstation/tgstation#55831]
Reporting client version: 513.1536

So, I was playing around on my own- testing a mod, which wouldn't affect the smartfridge at all- and suddenly the smartfridge refused to accept anything and wouldn't open. I think alt-tabbing is part of the cause of it? I don't know all the details of what caused it.

**Comment by Tlaltecuhtli** [comment]
there are different types of fridges that look the same but accept different things

**Comment by TyrianTyrell** [comment]
It was the one in BoxStation- between Hydroponics and the kitchen. It should've accepted the stuff.

**Comment by Tlaltecuhtli** [comment]
if it doesnt open its just tgui being shit, you can open it by opening anoher tgui window and then click the one who doesnt want to open
