### ISSUE TITLE
Slippery Spraycan doesn't spray lube

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#55845]
## Round ID:
[153220](https://scrubby.melonmesa.com/round/153220)

## Testmerges:
#54462: 'The Great Radio Rework: NTNET Part 1 of many.' by WarlockD at commit 0aea50f0dd

## Reproduction:
get a slippery spraycan, spray it, no lube spawns.

**Comment by dragomagol** [comment]
Duplicate of #53350 (rip)

**Comment by ShibaInuLord** [comment]
wow i totally forgot i already made one
