### ISSUE TITLE
Dead rats summoned by the regal rat can't be picked up

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#55852]
## Reproduction:
Have a regal rat summon rats. Kill the rats summoned (or have them bite a wire). Realize you can't pick them up and have to drag them around.

**Comment by brotherbeyondd** [comment]
rats are different to mice and if they bite the wire they dont get fried, they chew that bitch

**Comment by dragomagol** [comment]
That could be, I just saw dead, not charred rats close to wires. They also couldn't be swept by a broom

**Comment by brotherbeyondd** [comment]
yeh cos they're regular corpses like a dead corgi for example
