### ISSUE TITLE
Sentient Crates can hold seemingly infinite items and lag the server

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#55850]
## Round ID:
153235

## Testmerges:
#54462: 'The Great Radio Rework: NTNET Part 1 of many.' by WarlockD at commit 0aea50f0dd

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/103387418-82925c80-4ab8-11eb-80d2-c9d4333a5598.png)
A player created a sentient crate via xenobio. The crate ate lots of slimes, mobs and items, and it seemed when it opened/closed it would lag the server.

When it was running around on the escape shuttle it seemed to be healing a lot as well, leaving clouds of "+"

**Comment by Jared-Fogle** [comment]
/obj/structure/closet (which correctly limits its items) and /mob/living/simple_animal/hostile/mimic/xenobio have separate insertion_allowed definitions. You will notice the closet one is more robust.

![image](https://user-images.githubusercontent.com/35135081/103405250-55bb6500-4b0b-11eb-8340-831edaf26039.png)
