### ISSUE TITLE
Sometimes Fried Food Can't Be Eaten

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#55855]
## Round ID:
/////////

## Testmerges:
//////////

## Reproduction:
Fry anything, and use it on yourself in help mode. sometimes you eat it, sometimes you just "use" it on yourself, which is an attack animation i think.

**Comment by dragomagol** [comment]
Fried items also have an error as their right click icon

**Comment by ArcaneMusic** [comment]
What species were you eating it as? I wonder if it's related to the above issue. @ShibaInuLord

**Comment by ShibaInuLord** [comment]
I was human.

**Comment by timothymtorres** [comment]
Duplicate of #55375
