### ISSUE TITLE
Digitigrade lizard preferences are broken

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#55851]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/103390304-576c3500-4ad9-11eb-8a56-c36f2124070e.png)

Selecting digi will not give you digi legs when you spawn in. You even spawn in with shoes. Despite showing up as digitigrade in preferences, it is instead plantigrade in the preview and in game.

**Comment by RaveRadbury** [comment]
Likely caused by #55614
![image](https://user-images.githubusercontent.com/3204033/103424282-e37d6b80-4b70-11eb-9124-e5987d379a2b.png)
could also be
![image](https://user-images.githubusercontent.com/3204033/103424303-fc861c80-4b70-11eb-86a3-f0bf57a42df7.png)
