### ISSUE TITLE
Sticky Tape can only be printed one at a time in autolathe

### ISSUE THREAD

**Issue by Pugie** [tgstation/tgstation#55882]
This is AWFUL and SLOW

**Comment by ArcaneMusic** [comment]
Is this a dupe of #55528?

**Comment by Tlaltecuhtli** [comment]
no

**Comment by Pugie** [comment]
![image](https://user-images.githubusercontent.com/41806499/104194129-d25a1780-5418-11eb-9871-8faa717e21a9.png)
how is this not a bug dragomagol can you explain?
