### ISSUE TITLE
You can't eat Salami

### ISSUE THREAD

**Issue by Cowbin** [tgstation/tgstation#55888]

**Comment by dragomagol** [comment]
I wasn't able to reproduce this on local but I did notice this as a moth unable to eat a janitor's hat (instead just hitting myself with it) the other day.

**Comment by Cowbin** [comment]
I was on help intent, a second lizard who was there was also unable to consume the salami slice.  I was just hitting myself with the salami.

**Comment by ShibaInuLord** [comment]
might be the same type of issue as #55855

**Comment by ArcaneDefence** [comment]
This is a duplicate of https://github.com/tgstation/tgstation/issues/55375

You can reproduce this by making a raw sausage with the monkey meat that starts in the freezer, cooking it, and cutting it. You get two slices of salami that have reagents that can be eaten and four that cannot until further reagents are added.
