### ISSUE TITLE
Fancy chat string highlighting skips every second string

### ISSUE THREAD

**Issue by mudzbe** [tgstation/tgstation#55900]
The string highlighting for the fancy chat whatever only highlights every even string, whilst every odd string is highlighted normally. This issue is regardless of capitalization or whether the strings have spaces. This bug has been successfully reproduced on Austation, Bee and Tg.

### Reproduction
In the highlight box type a series of strings separated by commas. For example: "Jamal,Mcterra,SS13" Jamal and SS13 will be highlighted, whilst Mcterra isn't.

**Comment by dragomagol** [comment]
Fixed by #60146
