### ISSUE TITLE
Lings using lesser form no longer drop cuffs. 

### ISSUE THREAD

**Issue by Tumesuo** [tgstation/tgstation#55914]
Reporting client version: 513.1515

## Round ID:
[153448](https://scrubby.melonmesa.com/round/153448)

## Testmerges:
- [[DNM] Revert move type refactor, fixing the constant server crashes](https://www.github.com/tgstation/tgstation/pull/55913)

## Reproduction:
 
 1. be ling
 2. get cuffed
 3. return to monke
 4. cuffs don't drop as advertised anymore.
 
![vlc_NUy6TuWhFo](https://user-images.githubusercontent.com/15519576/103469872-4ccccc80-4d73-11eb-9df2-84958cb34c2f.png)

**Comment by interestingusernam3** [comment]
Seems to be caused by changes to monkeyize proc done in monkey refactor PR.
![Screenshot_2021-01-06 Refactors monkeys into a species by Qustinnus · Pull Request #55614 · tgstation tgstation(1)](https://user-images.githubusercontent.com/51925758/103802117-f4d1e680-504e-11eb-9e8a-60d2038fce38.png)

**Comment by interestingusernam3** [comment]
I managed to reproduce this succesfully.
