### ISSUE TITLE
locker problem

### ISSUE THREAD

**Issue by doguinh0** [tgstation/tgstation#55911]
Reporting client version: 513.1539 

## Round ID:
[153440](https://scrubby.melonmesa.com/round/153440)

## Reproduction:

if you wrap a locker with someone inside it the person inside gets permanently "stunlocked" (cannot exit or move), pretty op

**Comment by ShibaInuLord** [comment]
cant you just resist out

**Comment by interestingusernam3** [comment]
I tested it locally and you can, it only takes a few seconds.

**Comment by Dorsisdwarf** [comment]
Tested and this is working fine. Just press the resist button and wait a few seconds. Even works while being dragged, unlike handcuffs.
