### ISSUE TITLE
Duffel Curse can give incorrect messages to ghosts

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#55931]
## Round ID:
[153486](https://scrubby.melonmesa.com/round/153486)

## Testmerges:

While an observer, it is possible to receive the  "A stinky duffel bag appears on you" message when curse of duffel bags is being spammed. This is obviously incorrect functionality

**Comment by Pugie** [comment]
This happens whenever the duffel appearance text cue is used. Even when it's people around you who are a victim to the spell or you block the spell with antimagic.

**Comment by Tlaltecuhtli** [comment]
target.visible_message("<span class='danger'>A stinky duffel bag appears on you!</span>", \

should be a to_chat
