### ISSUE TITLE
SM Infinite Radiation Bug

### ISSUE THREAD

**Issue by JackTMannJr** [tgstation/tgstation#55959]
## Round ID: 
Round ID: [153637](https://scrubby.melonmesa.com/round/153637)

## Reproduction:
The Supermatter crystal was broken in such a way that it threw off infinite radiation without ever exploding at 0%. Please take a look at the moment when Carl Kofstri and Kevin Calf are setting up the SM -- the valves are activated and the air alarm is configured. Those are the only steps taken and the SM proceeds to generate radiation infinitely.

**Comment by Jared-Fogle** [comment]
#55960
