### ISSUE TITLE
Shelled botany food is hard-deleting

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#55969]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/103707988-460da780-4f75-11eb-957b-d105c4570e1f.png)

Likely the source of #55168 . Grown food that you can shell (Egg-plants, bungo fruit, and gatfruit) are failing to be deleted, probably in the food trash element.

The first grown food that gets harddel'd causes all future types of that food to fail to function correctly. 
- Unshelling gatfruit means all future gatfruit no longer gives guns but bungo and egg-plants will continue give pits and eggs - they still get harddel'd, but they won't break.
- Unshelling bungo fruit means all future bungo no longer gives pits but gatfruit and egg-plants will continue giving guns and eggs.
etc, etc.

**Comment by interestingusernam3** [comment]
Managed to reproduce locally. Seemed to work fine with just shelling and only start with the harddels after consumption of a shellable item and subsequent shelling of a shellable of the same type in my case.
