### ISSUE TITLE
Every now and then, borgs have to right-click to open lockers

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#55975]
## Reproduction:
I'm honestly not sure what causes it, but it's happened mostly as a roundstart cyborg. You can't use the alt-click "Floor" tab menu to click on them to get them open; You can use Alt-click to lock them, but must right click and click the locker tab's Toggle Open option.
After having my body deleted and a new one spawned, I was able to open lockers as per usual again. Reconnecting does not fix it.

**Comment by Manybones** [comment]
I have trouble reproducing this bug, please be more concrete about the situation. Does it hapens with a specific cyborg type? Did you have a tool in hand when you tried to open the locker? Any special conditions you noted? Try to post a screenshot if you can

**Comment by ZeroMODE0** [comment]
> I have trouble reproducing this bug, please be more concrete about the situation. Does it hapens with a specific cyborg type? Did you have a tool in hand when you tried to open the locker? Any special conditions you noted? Try to post a screenshot if you can

I main medical borg (on Manuel) if that helps, but this just randomly seems to happen to me and a few other borgs. I know not to use tools when clicking on lockers- And there's nothing noteable to screenshot as it looks completely fine until you go to click on it.
I'll try to keep a lookout for rounds this happens in the future and link them in this thread.

Spawning a new body completely fixes it, and it might be related to roundstart borgs.
