### ISSUE TITLE
Cakehat candle is DIRECTIONAL

### ISSUE THREAD

**Issue by Pugie** [tgstation/tgstation#55985]
**WHAT THE FUCK**

**Comment by brotherbeyondd** [comment]
WHAT THE FUCK

this is probably intentional by the anti cakehat coder cabal (ACCCtually)

**Comment by Pugie** [comment]
Over 1500 other open issues: sitting unanswered for months/years.
1 cakehat issue open for less than 24 hours: 2 pull requests and tagged as Priority: High

**Comment by Jared-Fogle** [comment]
please dont abuse priority labels
