### ISSUE TITLE
+206 credits: Received 1 of metallic hydrogen cm3 of developer's tears. Please, report this on github.

### ISSUE THREAD

**Issue by esainane** [tgstation/tgstation#55980]
## Reproduction:

Obtain metal hydrogen, either through testing controlled HFR meltdowns or through `spawn /obj/item/stack/sheet/mineral/metal_hydrogen`.

Call the cargo shuttle. Drop one on the cargo shuttle. Send the cargo shuttle. Observe an amusing message and a tragically small payout for your efforts.

![metal-hydrogen-developers-tears](https://user-images.githubusercontent.com/14355175/103733997-e1734b00-504f-11eb-843c-60f4d874aac6.png)

**Comment by interestingusernam3** [comment]
The small payout seems to be working as intended, the value of metalic hydrogen is CARGO_CRATE_VALUE*1.05
