### ISSUE TITLE
Monkeys cannot be transformed into humans (genetics console AND mutadone)

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#55997]
Reporting client version: 513.1533

## Round ID:
[153698](https://scrubby.melonmesa.com/round/153698)

## Testmerges:
- [[DNM] Revert move type refactor, fixing the constant server crashes](https://www.github.com/tgstation/tgstation/pull/55913)

## Reproduction:
Put a monkey in a genetics console, press scramble DNA. The console says transforming but the monkey doesn't transform.

Discover monkified and change one of the letters to something invalid. The console says transforming but the monkey doesn't transform.

Inject monkey with mutadone. The monkey -> human animation plays, but after it finishes the monkey falls over, still a monkey. The animation plays over and over while it still has mutadone in its system.

**Comment by dragomagol** [comment]
Likely caused by #55844

**Comment by necromanceranne** [comment]
It was. I'm stuck without proper internet access at the moment, so if someone wants to make a prompt fix for it, check for !ismonkey before setting the original_species var. It's some initialization stuff.

**Comment by necromanceranne** [comment]
My internet service activated way sooner than anticipated so I did the line change
