### ISSUE TITLE
Identified bug with heretic mask

### ISSUE THREAD

**Issue by JackTMannJr** [tgstation/tgstation#56006]
## Round ID: 
[153725](https://scrubby.melonmesa.com/round/153725)

## Reproduction:
During the round, the heretic mask was able to stunlock players through infinite feedback of its spreading and stacking. Notice in medbay like 14 players all stuck laughing in critical condition.

**Comment by necromanceranne** [comment]
It's not a bug, it's just poorly designed.

![if athath tells you there are abuse cases, it's a good idea to pay attention](https://user-images.githubusercontent.com/40847847/103856613-0b3c7880-5109-11eb-8b65-42d5067fe078.png)

@EdgeLordExe Please resolve this.

**Comment by MrMelbert** [comment]
- the stamina damage isn't capped so it gives infinite stamcrit
- the hallucinations it gives isn't capped so it gives like 500 hallucination stat

**Comment by EdgeLordExe** [comment]
I will be adressing this in the upcomming heretic megabalancing patch
