### ISSUE TITLE
The Pod Window Spawner Is A LIE AND A SHAM

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#56005]
## Reproduction:

Make a map and use the pod window spawner, as so:
![image](https://user-images.githubusercontent.com/57122098/103845788-a1ad6300-5051-11eb-8f04-4ea83e24c1f7.png)

Expecting it to spawn a full pod window, as this is right next to space and very crucial.

Instead, cry and weep as the map loads with no atmos, because it produced THIS:
![image](https://user-images.githubusercontent.com/57122098/103845844-c275b880-5051-11eb-9053-f1e0da783537.png)

**Comment by EgorDinamit** [comment]
I wouldn't say it's really a bug, there is just no fulltile windows.
If you want one - consider using **/obj/effect/spawner/structure/window/hollow/survival_pod**
Otherwise, someone could sprite a fulltile survival window.

**Comment by Paxilmaniac** [comment]
But we do have a fulltile pod window and it's already sprited, literally just look at the first image

**Comment by EgorDinamit** [comment]
Yeah, just found it - **/obj/structure/window/shuttle/survival_pod**
![image](https://user-images.githubusercontent.com/53223414/104021100-a69c1f00-51d7-11eb-8b21-bf1b44163800.png)

Is it the right one? I can PR a fix right now.

**Comment by Paxilmaniac** [comment]
Yes that looks to be the right one

**Comment by EgorDinamit** [comment]
Done. I wonder if it was always like this, or some recent change renamed fulltile window path.
