### ISSUE TITLE
Chilly Pepper Bounty Being Broken

### ISSUE THREAD

**Issue by GoldenAlpharex** [tgstation/tgstation#56013]
## Reproduction:
Basically the Chilly Pepper bounty is broken and it doesn't accept chilly pepper. @spessbro is already going to look into it, I'm just putting this here at his request so he doesn't forget about it.

**Comment by Tlaltecuhtli** [comment]
doesnt seem broken, did this happen on a server where the last bounty bug isnt present?
https://github.com/tgstation/tgstation/blob/03062afb21db9d188e10fdd2fa2689dca73c1590/code/modules/cargo/bounties/botany.dm#L101-L105

https://github.com/tgstation/tgstation/blob/ca66ac7ffc63e629068b7d0031d081bec937b273/code/modules/hydroponics/grown/chili.dm#L37-L38

**Comment by GoldenAlpharex** [comment]
> doesnt seem broken, did this happen on a server where the last bounty bug isnt present?
> https://github.com/tgstation/tgstation/blob/03062afb21db9d188e10fdd2fa2689dca73c1590/code/modules/cargo/bounties/botany.dm#L101-L105
> 
> https://github.com/tgstation/tgstation/blob/ca66ac7ffc63e629068b7d0031d081bec937b273/code/modules/hydroponics/grown/chili.dm#L37-L38

I'm not sure, I suppose I'll have to look into it. I think they're like, three days behind.

**Comment by Tlaltecuhtli** [comment]
the  bounty name for normal peppers is similar to the ice one "Chili Peppers" vs "Chilly Peppers" maybe u misread it

**Comment by ArcaneMusic** [comment]
Sat down and tested, and I can confirm that this is currently fixed, on both chilli and chilly peppers.
