### ISSUE TITLE
Jaunt is horrificly broken

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#56026]
## Reproduction:
Wizard hits jaunt, halfway through he suddenly disappears. You right click where he should be, nothing. The only way I found him was because he prayed to me. Ahelps didn't work (would just show up blank). Anyone who orbited him had their ghosts fucked up (stuck in orbiting animation when not orbiting anything, stuck horizontal). When he eventually ghosted, his ghost didn't have a mind. I had to put him inside a new human to get him working again, and his ghost just stayed in the place it had been. Player was GarfieldLives/Snood.

**Comment by wesoda25** [comment]
Ideal way of fixing it when it happens is to just use Get

**Comment by ATH1909** [comment]
the beast is not dead, this happened to me again as an artificer on sybil

**Comment by ATH1909** [comment]
round id 154074

**Comment by Rohesie** [comment]
Wait a bit more for the servers to update.

**Comment by LemonInTheDark** [comment]
does it replicate?
