### ISSUE TITLE
By now, all light bulbs should be LED, how can you burn your hand when touching one?

### ISSUE THREAD

**Issue by JackTMannJr** [tgstation/tgstation#56036]
## Round ID:
[153820](https://scrubby.melonmesa.com/round/153820)

## Reproduction:
Touch a lightbulb while it's on and your hand burns! Silly! All bulbs on the station should be LED to reduce cost.

**Comment by cacogen** [comment]
Tonto?

**Comment by Fikou** [comment]
not funny
