### ISSUE TITLE
Things phase through simplemobs if they are placed on tables using help intent and subsequently removed from said tables. Those simplemobs also become unable to move on their own and are pulled at about the same speed as prone/dead humans.

### ISSUE THREAD

**Issue by interestingusernam3** [tgstation/tgstation#56034]
## Testmerges:
none (tested locally)

## Reproduction:
1. Find a simplemob that things shouldn't phase through (for example a cow or a corgi)
2. Pull it on help intent
3. Click a table
4. Wait for the progress bar to finish
5. Remove it from the table by destroying it or pulling it off the table
6. Walk through it (you phase through)
7. Throw something at it (it phases through)
8. Put your mind in the simplemob
9. Try to move (you can't, but you can rotate yourself)
10. Pull the mob (you will be slowed even if pulling the mob doesn't normally slow you down)

Possibly related to https://github.com/tgstation/tgstation/issues/44884? (edit: it's not)
https://github.com/tgstation/tgstation/issues/55133 is an issue about a specific situation in which this bug manifests

**Comment by Tlaltecuhtli** [comment]
tabling in help intent set carbons to rest mode, which simplemobs arent intended to do and dont have a way to control, aka being unable to move, either give simplemobs rest controls or have a carbon check in the tabling code
https://github.com/tgstation/tgstation/blob/5ae6adaedd39138b3395441d1735f65fe815c294/code/game/objects/structures/tables_racks.dm#L118

**Comment by ATH1909** [comment]
> tabling in help intent set carbons to rest mode, which simplemobs arent intended to do and dont have a way to control, aka being unable to move, either give simplemobs rest controls or have a carbon check in the tabling code
> https://github.com/tgstation/tgstation/blob/5ae6adaedd39138b3395441d1735f65fe815c294/code/game/objects/structures/tables_racks.dm#L118

is there a hotkey for resting? does pressing it work if you're a simplemob?

**Comment by interestingusernam3** [comment]
>is there a hotkey for resting? does pressing it work if you're a simplemob?

It's U but most simplemobs don't have proper visuals for resting and won't automatically get up so it's not really relevant.
