### ISSUE TITLE
Walking over oil stains with riot armor on bloodies it

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#56057]
## Description:

Keeping your set of riot armor shiny and clean is very difficult as walking over _oil_ stains (even when wearing footwear) will cause the armor to become bloodied.

**Comment by Tlaltecuhtli** [comment]
step 1 cover yourself in oil

**Comment by interestingusernam3** [comment]
Failed to reproduce with riot suit from armory, roundstart sec jackboots and all types of CLEANABLE/oil.

**Comment by interestingusernam3** [comment]
Forgot to mention: those were oil bootprints.

**Comment by TheBonded** [comment]
fixed by https://github.com/tgstation/tgstation/pull/57085, probably
