### ISSUE TITLE
Yellow swarmers won't pass through swarmer barriers

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#56050]
## Reproduction:
Be a swarmer, make a couple of new yellow swarmers. Make a barrier. Pass through the barrier, see that your backup doesn't come with you.

**Comment by interestingusernam3** [comment]
After reading the code, a stupid attempt at fixing this and reading the code again, I think I found a probable cause - drones seem to use generic simplemob AI to target stuff (see drone definition in swarmer.dm) and step_to to follow the master swarmer (see Move() in swarmer.dm). Step_to is a builtin BYON proc while the proc used to make swarmers move through barrier is CanAllowThrough, which isn't a builtin BYOND proc, so step_to probably doesn't consider CanAllowThrough.

**Comment by itseasytosee** [comment]
They PHYSICALLY can move through barricades but they AI tells them that they are unable to so they treat them like a wall.

**Comment by SuperNovaa41** [comment]
Swarmers have been removed. https://github.com/tgstation/tgstation/pull/63989
