### ISSUE TITLE
gubbucks and guthins have stopped eating stuff again

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#56059]
![image](https://user-images.githubusercontent.com/42606352/104088269-20a9c380-522b-11eb-93b1-d5c49c9402b2.png)

**Comment by cacogen** [comment]
Did you try attacking them to get them to eat?

**Comment by RaveRadbury** [comment]
Should probably add hand-feeding like with cows

**Comment by Potato-Masher** [comment]
The other day I was able to get them to eat once I dragged them a bit closer to the organ pile. Seems they only start once interacted with?

**Comment by ATH1909** [comment]
> The other day I was able to get them to eat once I dragged them a bit closer to the organ pile. Seems they only start once interacted with?

I tried dragging one of them closer to the organs, but that didn't seem to help.

**Comment by timothymtorres** [comment]
Duplicate of #47568
