### ISSUE TITLE
extreme fast cold lag and crash

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#56066]
153901 round was more laggy than usual then i see water vapour INSTANTLY freeze on the whole sci maint  because solars doors was open, it reached to botany maint so fast i thought an admin was griefing by terraforming all tiles to ice, then before shuttle arrives in escape a similar situation where i see a door open to space everyone fine then instantly everyone start dying of cold.  server also crashed

**Comment by bigfatbananacyclops** [comment]
could this be related to https://github.com/tgstation/tgstation/pull/55604

**Comment by LemonInTheDark** [comment]
Feature, not a bug. I can do some things to help tho, keep an eye out.

**Comment by Pugie** [comment]
Haha yes having to get wintercoats to not die every round and also 5 fps and crashing is a feature and intended.

What the fuck happened to your brain lemon what's the major malfunction???
