### ISSUE TITLE
More ling lesser form / monkey issues

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#56069]
## Reproduction:

all testing done on latest master.

-Using lesser form with a flesh disguise doesn't unequip your flesh disguise clothes
![image](https://user-images.githubusercontent.com/51863163/104109690-2e486300-5296-11eb-9d73-e64368c5b7cf.png)
(this works for stuff like chitinous armor too)
![image](https://user-images.githubusercontent.com/51863163/104109854-964b7900-5297-11eb-99e3-32996902e0fc.png)

-Abilities that "cannot be used in lesser form" are usable in lesser form
![image](https://user-images.githubusercontent.com/51863163/104109735-6ea7e100-5296-11eb-9a82-17abd55217c0.png)
(this means you can have an armblade while ventcrawling)

-Monkeys can be absorbed for DNA and count like humans, works cellular emporium re-adaptions, disguise, etc
![image](https://user-images.githubusercontent.com/51863163/104109771-b75f9a00-5296-11eb-8558-a6d63a88f3e5.png)
(choosing to transform into a monkey DNA will turn you into a monkey, then into a monkified human.)

-transforming from lesser form into a dna you have and back causes some fucky things (you transform back into a monkey-thing or something)

**Comment by dragomagol** [comment]
Amazing, this is probably what was plaguing #56401

**Comment by dragomagol** [comment]
Amazing, this is probably what was plaguing #56041

**Comment by necromanceranne** [comment]
This is likely just a huge quantity of missing ismonkey early returns.
