### ISSUE TITLE
Modified det revolver on malfunction shoots the user.

### ISSUE THREAD

**Issue by Pugie** [tgstation/tgstation#56073]
Is this intentional and made as shitsec bait?? 60 brute and dropping the gun is the antonym of kosher!

To clarify I mean actually being shot. By a .357 bullet.

**Comment by kopoba** [comment]
Yes its  intentional. Not a bug

**Comment by Pugie** [comment]
> Yes its intentional. Not a bug

Ok, I think I missed the PR that changed this reason I made the issue was there was problems with other items leading to shooting oneself when I asked arcanedefence about it.
Do you have a link to the PR?

**Comment by kopoba** [comment]
> 
> 
> > Yes its intentional. Not a bug
> 
> Ok, I think I missed the PR that changed this reason I made the issue was there was problems with other items leading to shooting oneself when I asked arcanedefence about it.
> Do you have a link to the PR?

It was never changed it was like this from the beginning of time i think. Atleast 5 years now. https://github.com/phil235/-tg-station/blob/9ab8a8cbd3e49b522b63ff2c4bf4225115ac019f/code/modules/projectiles/guns/ballistic/revolver.dm#L110

**Comment by Pugie** [comment]
No what used to happen is you drop the gun and take 20 burn damage, that's it.
Now you ACTUALLY shoot yourself.

**Comment by Pugie** [comment]
If I was going to make a guess as to what went wrong I'd say that https://github.com/tgstation/tgstation/pull/53107 made it so misfiring the revolver makes the bullet actually discharge when it misfires, then something else along the way broke it to make the bullet that misfires actually shoot you.

**Comment by Dorsisdwarf** [comment]
https://github.com/tgstation/tgstation/pull/53107/files#diff-5ac83fc677416637c47410836df32aad740b3ef8dc59f9fe1205c839a964126dR101 
#53107 is definitely intended to make it so that you shoot yourself in the arm with a misfire. It checks which hand you fired with then calls process_fire with the target of the user and the forced location of that arm.

**Comment by Dorsisdwarf** [comment]
After some looking around the only reason I can see where you get shot AND take the 20 burn damage is if it goes off while you're modifying it. 
When the detective gun rolls the dice for using 357 according to the current code it is dropped on the floor and then deleted after dealing that damage. I'm not sure how you are getting shot in the current code.

**Comment by cacogen** [comment]
I remember KorTM made it so that it shot .357 bullets briefly in 2012 and that was quickly reverted anyway I can't remember if it was possible to modify it beforehand or if that was added as a compromise afterward either way good shit OP

**Comment by kopoba** [comment]
I was unable to reproduce 20 burn damage bug. All other mechanics works as intended. .357 will shoot you in arm during miss fire dealing 50 brute(that's strange since 357 is 60 brute damage) in that arm. Modifying with live bullets in gun will shoot you with that bullet in targeted zone.

**Comment by Pugie** [comment]
It's because limbs only have 50hp

**Comment by kopoba** [comment]
its not a bug @Dorsisdwarf is wrong

**Comment by Pugie** [comment]
> its not a bug @Dorsisdwarf is wrong

uh huh that is why it was undocumented in the change that caused misfire to discharge, it didn't cause you to shoot yourself then and only seemed to do so after a refactor which apparently caused other guns to result in shooting oneself. Sure.

**Comment by Dorsisdwarf** [comment]
After reading the actual current code it appears that I overthought this and the behaviour in #53107 (misfires make you shoot yourself in the arm and drop the gun) is the current behaviour. Whether it is _balanced_ behaviour is not really in the scope of this issue.

**Comment by kopoba** [comment]
> 
> 
> > its not a bug @Dorsisdwarf is wrong
> 
> uh huh that is why it was undocumented in the change that caused misfire to discharge, it didn't cause you to shoot yourself then and only seemed to do so after a refactor which apparently caused other guns to result in shooting oneself. Sure.

There was no change it was always like this.

**Comment by Pugie** [comment]
god i love kat green
