### ISSUE TITLE
All forms of trauma paralysis are non-functional BESIDES NORMAL LEG paralysis (also digitigrades are immune to leg paralysis)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#56076]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/104113858-7e89ea00-52c3-11eb-8cd5-0452185952c6.png)

Having either arm disabled due to the paralysis brain trauma fails to actually disabled the arm. In addition, if you are digitigrade, having left or right legs paralyzed does nothing (INCLUDING from the roundstart quirk). The only limbs affected by paralysis are NORMAL left and right legs.

**Comment by Manybones** [comment]
Bug reproduced, on my way to fixing it. I will make a PR soon
