### ISSUE TITLE
Weirdness with datum tiles

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#56096]
## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/104136221-ade33a00-5349-11eb-994c-0369ac81e3b5.png)
Datum tiles on Multi-z show the z-level below them (see the snow walls, wolf, tree).

![image](https://user-images.githubusercontent.com/66640614/104136172-69f03500-5349-11eb-852c-1dd2ef0d437f.png)
Newly-placed datum tiles hide gases; the plasmaman could still breathe and not combust while standing on the new tiles.

![image](https://user-images.githubusercontent.com/66640614/104136519-9311c500-534b-11eb-8562-0dd3bdb74059.png)
After buildmoding more plating underneath to test visibility again, the tiles on the floor above appeared to produce plasma. On examination, it just _looked_ like plasma, but with no actual effects. Right clicking the floor showed mobs/items underneath it.

**Comment by Qustinnus** [comment]
now this is epic

**Comment by Sealed101** [comment]
no longer occurs; transparency issues possibly fixed by plane cube, however the fuck would this be connected to it
gas 'producing' issues fixed by some custom mats refactor; also buildmoding these tiles produces an empty `turf/floor/open/material` tile
