### ISSUE TITLE
Becoming a pod-person results in negative moodlet for missing heirloom, despite having heirloom.

### ISSUE THREAD

**Issue by octothorpe93** [tgstation/tgstation#56097]
Reporting client version: 513.1530

## Round ID:
[153967](https://scrubby.melonmesa.com/round/153967)

## Testmerges:
- [[DNM] Revert move type refactor, fixing the constant server crashes](https://www.github.com/tgstation/tgstation/pull/55913)
- [15.ai VOX: Say the pickle rick meme, but as any voice!](https://www.github.com/tgstation/tgstation/pull/55626)

## Reproduction:

1) Die with the family heirloom trait
2) Get replica-pod cloned
3) Pick up heirloom from previous incarnation

![image](https://user-images.githubusercontent.com/71497331/104136922-6911d000-5356-11eb-82d0-4df89d434ce1.png)

I was killed and had to be podcloned due to my head being missing. The rest of my corpse was found, and was used to inject the seed packet. Upon being revived, though, I was suffering the negative moodlet for my heirloom being missing, despite said heirloom still existing and being picked up. I suspect this is due to being a new "brain", but it's confusing, and it would be nice to have an RP-link to my old corpse other than "oh that's my corpse WHAT AM I".

**Comment by Manybones** [comment]
I may have a fix on this, but since heirloom code interacts with pod replicas very weirdly It would be a spaguetti fix. I will try to work in a more elegant solution

**Comment by Sealed101** [comment]
well apparently nowadays this method of revival will not transfer the quirk to the new body, completely freeing the podperson from the mood buff/debuff of the heirloom. fixed?
