### ISSUE TITLE
Being a held MMI causes your camera to jump from turf to turf abruptly when the holding mob moves

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#56099]
## Reproduction:

1. Be a brain in an MMI
2. Get a player to walk around with you
3. Experience the displeasure

It's like your client's eye updates location from turf to turf instead of staying at the mob. I've also experienced this with observing people.

**Comment by cacogen** [comment]
Seeing as this hasn't gotten any labels like it isn't a real issue let me clarify: Eye movement as an MMI never used to be jerky and unpleasant it motion tweened like the rest of movement so it's like the camera updates location to the holder's turf every time they move. Try it yourself, it's borderline unplayable.

**Comment by Sealed101** [comment]
can no longer reproduce on local
