### ISSUE TITLE
Vending machines are being hacked round start

### ISSUE THREAD

**Issue by Jared-Fogle** [tgstation/tgstation#56101]
Has been happening consistently on Bagil, vending machines will show their hacked/premium items round start.

**Comment by TemporalOroboros** [comment]
I mean, It's _Bagil_. Are you certain that this is a code issue?

**Comment by Jared-Fogle** [comment]
Only like 90%.

**Comment by interestingusernam3** [comment]
Bagil speedrunner vs 5 admins

**Comment by ATH1909** [comment]
> Bagil speedrunner vs 5 admins

"Hey shitass, wanna see me speedhack?"

**Comment by kopoba** [comment]
i can bet there was pr that made this. Well food vendors for sure
