### ISSUE TITLE
Asteroid touching the Derelict Station causes weird Asteroid Sand

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#56112]
## Round ID: 
[154006](https://scrubby.melonmesa.com/round/154006)

## Testmerges:
#55956: revolutionary victory change
#55626: ai Vox change
Neither seem related to a tile bug but here they are anyway.

## Reproduction:
Placing lattices on some derelict station space tiles creates asteroid sand, unsure about the reasoning behind some rooms having this happen and some not. This only seemed to happen when one of the prefabs that spawn inside of an asteroid generated so close to the derelict station that the asteroid rock was literally touching the station's arrivals airlocks.
![image](https://user-images.githubusercontent.com/76874615/104172108-62459480-540c-11eb-8495-b79ba4962d9d.png)
(didn't think to grab a picture of the actual contact point in the moment, whoops)
This might just be one of those situational one time bugs but I thought it was worth posting about.

**Comment by ArcaneMusic** [comment]
Oh, that's bizzare. I wonder if the baseturf of some of the asteroid ruin was superimposed onto the derelict space tiles. Still, that's strange that it wouldn't just fully replace parts of the derelict then if it just kept the asteroid sand baseturf.

**Comment by san7890** [comment]
Is this still an issue in a post- #66045 world? It's probably some baseturf weirdness, just want to see if anyone knows.

**Comment by AdipemDragon** [comment]
well, seeing as how rare two ruins touching in space in the first place Is. I. Doubt there's gonna be a way to naturally force an asteroid to intersect the derelict again, all for the sake of testing with the derelict edit pr merged
I am genuinely just willing to close this and chalk it up to extreme chance, because between intersecting ruins and someone actually playing the derelict? I dunno...

**Comment by Sealed101** [comment]
no related runtimes in the round logs from what i can see (at the time of writing this the servers are down and all log publications are unavailable, so i can't really check `map_errors.txt`)

manually placing an asteroid template then placing a space ruin with a different baseturf nowadays works on a first-come-first-served basis - the asteroid turf remained and was not overridden by a space turf; placing lattices worked as expected
![изображение](https://github.com/user-attachments/assets/867ea10a-b709-4d48-bb78-cbaf3d49de85)

ideally would be great to catch an instance of these ruins overlapping by generation and not by admeme commands as it was in my testing but how likely is that to happen

**Comment by san7890** [comment]
this is almost definitely fixed in the post-#66045 world because that's the last big change to how baseturfs worked for this ruin
