### ISSUE TITLE
cant eat runtime meat

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#56126]
butcher runtime
try eat meat
slap face with meat

**Comment by Pugie** [comment]
This is part of an issue with all food I think, if you have a mask on you straight up can't eat meat even when your mask is pulled down, and if you fail to eat a piece of food this way even if you take the mask off it will be totally inedible.

I had this issue with bread slices yesterday on Terry.

**Comment by cacogen** [comment]
I wanted to try to fix this but couldn't figure it out. 

Meat that is the result of the butchering component's butcher proc doesn't have the edible component. Meat spawned by that proc does have the mob_meat material applied, but I assume it isn't calling its parent's (meat's) on_applied_obj() which calls make_edible() and adds the component.

@Qustinnus could fix this

**Comment by SuperNovaa41** [comment]
No longer an issue
