### ISSUE TITLE
plushies in exosuit slot is missing sprite

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#56127]

**Comment by interestingusernam3** [comment]
What

**Comment by dragomagol** [comment]
I'm surprised plushes fit in exosuits at all. Which exosuit was this with?

**Comment by Tlaltecuhtli** [comment]
https://github.com/tgstation/tgstation/blob/710faeac5a285be2f603ec886ffc18d0bff5b06c/code/modules/clothing/suits/miscellaneous.dm#L635

plushies are child of /obj/item/toy
