### ISSUE TITLE
You can dupe wood by making and breaking tables

### ISSUE THREAD

**Issue by maxymax13** [tgstation/tgstation#56152]
## Round ID:
Local server

## Testmerges:

No

## Reproduction:

step one: make a table frame
step two: make it a table (costs 1 wood)
step three: wrench that table (gives you 2 wood)
step four: ![profit](https://user-images.githubusercontent.com/38844529/104484003-85587b80-55a7-11eb-8088-fcab061a5245.mp4)

**Comment by interestingusernam3** [comment]
Succesfully reproduced on up-to-date local server. Some interesting results:

- Bug does not occur with admin spawn/roundstart tables (screwdriver: 1 plank + frame, wrench: 3 planks) 
- Player-constructed tables always leave a table frame regardless of deconstruction method (screwdriver: 2 frames, 0 planks (!!), wrench: 1 frame, 2 planks). 
- Bug occurs consistently with both deconstruction methods.

**Comment by interestingusernam3** [comment]
This failed to close when the PR was merged, someone close plz
