### ISSUE TITLE
Cell chargers cannot be bolted to tables.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#56158]
**To reproduce:**

1.Take a cell charger.
2.Drag it to a table and put it on top of the table.
3.Try to wrench it down.

It doesn't work!

This works fine for weapon rechargers.

**Comment by necromanceranne** [comment]
![zero please](https://user-images.githubusercontent.com/40847847/104565472-70134800-56a0-11eb-9038-558ea7b18784.png)

This also affects grinders but actually provides feedback. Likely something is intercepting the attackby.

**Comment by necromanceranne** [comment]
![grinder bugs](https://user-images.githubusercontent.com/40847847/104565971-2a0ab400-56a1-11eb-9cf5-c5bfc6943a77.png)

Grinders appear to be also doing it but provide some feedback

**Comment by TheBonded** [comment]
Did you try screwdriving them first to open their part containers? you'll have to take any beakers out of the grinder as well to screwdrive it open

**Comment by necromanceranne** [comment]
This was an empty grinder. This was also all wrenchable on the floor, so this is explicitly only being blocked on tables. And yes, I tried screwdriving them open, that actually didn't help either.

**Comment by iwishforducks** [comment]
Additionally, hydroponic trays can no longer be bolted down when there is a directional glass on it. (I'm assuming this is caused by the same thing)

**Comment by CoffeeDragon16** [comment]
Looks like the issue is with the can_be_unfasten_wrench proc. When default_unfasten_wrench runs, it checks that there's nothing dense on the turf. Tables are dense, so it fails.
