### ISSUE TITLE
Changeling regeneration doesn't fix leg paralysis without amputation.

### ISSUE THREAD

**Issue by KingPhilipIII** [tgstation/tgstation#56172]
## Reproduction:

Upon crushing myself repeatedly with a vending machine as a changeling, I got permanent leg paralysis. (Where it says my legs are limp and lifeless) When I attempted to regenerate from the damage (Using first flesh mend, then regenerate, then regenerative stasis), none of the abilities cured my paralysis.

Manually chopping my own legs off with an armblade and then regrowing them produced a healthy and functional set of legs however.

**Comment by Sealed101** [comment]
vendor-induced paraplegia is a brain trauma, and the way it's applied in the code doesn't state a severity (resistance) of the trauma, thus it defaults to a permanent one. neither flesh mend, regenerate, regen coma or the brain damage fixing anatomic panacea are intended to heal permanent brain traumas. additionally, amptutating the disabled limbs then regenerating them did not heal the trauma, so the legs are still non-functional. seems to be working as intended, though there's a case for the balancing of this vendor trauma being permanent. 

https://github.com/tgstation/tgstation/blob/3ab970329867c340ba19c1caf4cc7559308ac317/code/modules/antagonists/changeling/powers/panacea.dm#L36-L38

https://github.com/tgstation/tgstation/blob/3ab970329867c340ba19c1caf4cc7559308ac317/code/modules/vending/_vending.dm#L1030-L1037

https://github.com/tgstation/tgstation/blob/3ab970329867c340ba19c1caf4cc7559308ac317/code/modules/mob/living/brain/brain_item.dm#L524-L551
