### ISSUE TITLE
Icebox has prisoner latejoin slots open from round start

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#56191]
154327

## Reproduction:
3 minutes into the round:
![image](https://user-images.githubusercontent.com/51863163/104793598-06ab3c00-5769-11eb-81fc-977456341234.png)
Round log (No results for bureaucratic error) 
![image](https://user-images.githubusercontent.com/51863163/104794997-e0899a00-5770-11eb-9ca3-a9e209b6eabf.png)

**Comment by ArcaneDefence** [comment]
Isn't this a supported feature with station traits now?

**Comment by MrMelbert** [comment]
Uh... seeing as this issue was prevalent far before station traits I imagine it's not a "feature :tm: "now
