### ISSUE TITLE
Malf AI converts a human to traitor and NOT THE AI

### ISSUE THREAD

**Issue by Jared-Fogle** [tgstation/tgstation#56192]
## Round ID: [154330](https://scrubby.melonmesa.com/round/154330)

![image](https://user-images.githubusercontent.com/35135081/104794464-926a9b80-575c-11eb-935e-b38242af0567.png)

Oingo Boingo is a human, the AI did not have traitor laws, I had to give it to them manually.

@Fikou Why

**Comment by Jared-Fogle** [comment]
#56090

**Comment by Jared-Fogle** [comment]
IT DOESNT EVEN HAVE AN ANTAG_CAP
![image](https://user-images.githubusercontent.com/35135081/104798021-ecc52580-5777-11eb-8433-71c6e05dbfc2.png)

**Comment by Fikou** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
