### ISSUE TITLE
spellbook didn't recognize me as owner when litched

### ISSUE THREAD

**Issue by c420-o** [tgstation/tgstation#56216]
Reporting client version: 513.1536

## Round ID:
[154402](https://scrubby.melonmesa.com/round/154402)

## Testmerges:
- [Re-PR of #55457 ([Port] Atmos components now nullifies node properly)](https://www.github.com/tgstation/tgstation/pull/56202)

## Reproduction:

died, then bind soul revived me, tried to use spellbook but it didn't recognize me as owner

**Comment by interestingusernam3** [comment]
Possibly related to #56097.

**Comment by ATH1909** [comment]
*liched

**Comment by timothymtorres** [comment]
Fixed by #67844
