### ISSUE TITLE
Powerfist is "out of gas" despite having a full 1000-2000kpa tank inside.

### ISSUE THREAD

**Issue by Robustitron** [tgstation/tgstation#56213]
## Round ID:
This happened on 154387 where it got me killed, I then tested offline with a 16 day old version of the game and reproduced it there too.

## Testmerges:
None of these probably matter because I reproduced it in a 16 day old version of the game.
#55534: '/mob/living/proc/Life(delta_time)' by TemporalOroboros at commit 64722d2fea
#56061: 'Modernizes Admin Only Wizard Event, Department Revolt' by tralezab at commit 7d16921164

## Reproduction:
1) Get a powerfist, set it to any power level
2) Fill a large oxygen tank with an air pump (or a can, or just its default pressure)
3) Apply powerfist to someone with any intent.
4) Based on RNG, you will either hit, or receive the message "The power-fist's piston-ram lets out a weak hiss, it needs more gas!"
5) The powerfist will complain about no gas at 2000kpa, 1400kpa, 900kpa, etc, regardless of power setting.

Even with a airpump filled (approx 2000kpa) tank freshly put in the powerfist, I've had to punch someone 5 times (4 no gas messages) to get an actual powerfist attack to trigger.

Other times its the opposite, i can get 4 real hits in, then the 5'th will fail from no gas, I take the tank out to inspect, and it's still at 1400kpa.

**Comment by LemonInTheDark** [comment]
Does not reproduce. Could you provide more details on the gasmixture used, the molar amount inside the tank, and the power you have the fist set to?

**Comment by Robustitron** [comment]
The gas was a mix of oxygen and station air.

Specifically, I took large oxygen tanks from lockers (both blue and red from fire lockers), put them in an air pump thats full of the local air, and pressurized the tanks to the maximum, which was 2000something kpa.

I've had this happen on power setting 1 and 3, never bothered with 2.

**Comment by RandomGamer123** [comment]
This seems to be caused by QUANTIZE being called on the amount of gas removed, which is why this only happens with gas mixtures (like that of normal air) and is often quite random on when it triggers (took me two tries to reproduce)
