### ISSUE TITLE
Rats are not used up when crafting double rat kebabs

### ISSUE THREAD

**Issue by CoffeeDragon16** [tgstation/tgstation#56219]
Reporting client version: 513.1536

## Round ID:
[154404](https://scrubby.melonmesa.com/round/154404)

## Testmerges:
- [/mob/living/proc/Life(delta_time)](https://www.github.com/tgstation/tgstation/pull/55534)
- [Modernizes Admin Only Wizard Event, Department Revolt](https://www.github.com/tgstation/tgstation/pull/56061)

## Reproduction:
 Open crafting menu, kill two rats and craft it. The two dead rats don't get used up in the process. Note that I myself was unable to recreate this, but the person who reported it could.

**Comment by ArcaneMusic** [comment]
Can't reproduce on local, there's probably more reproduction steps required to make this work.

**Comment by interestingusernam3** [comment]
How many times was this repeated? Was it possible to reproduce in a different location? Could be a few rats somewhere nearby getting consumed without the player noticing.

**Comment by projectkepler-ru** [comment]
no longer applicable

**Comment by Sealed101** [comment]
can't reproduce; we've also had some food crafting overhauls that may or may have not covered this up neatly
