### ISSUE TITLE
Ash Drakes are able to use their swoop attack to get on station

### ISSUE THREAD

**Issue by iwishforducks** [tgstation/tgstation#56244]
Ash drakes are able to get on station by using their "Swoop" attack. This means if they're on lava land, and their target teleports to the station through using a jacob's ladder, futons, or other similar teleportation devices, then they will use their swoop attack to get to their target, following them onto the station. There have already been extensive measures put in to stop players from getting megafaunas on station, and I don't see how this is any different.

**Comment by projectkepler-ru** [comment]
this is the same as the bubblegum teleport
im not sure if it still occur
