### ISSUE TITLE
Thermomachines work in space and don't need power

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#56257]
## Reproduction:
1). Get/build a thermomachine
2). Build it in space on some plating
3). Turn it on and watch it work like magic haha
4). They don't even require an APC or power from an APC

![thermo go brrrrrrrrrr](https://user-images.githubusercontent.com/46318638/104877477-ed042300-5927-11eb-9c8b-f6691f7b2cdb.png)

**Comment by LemonInTheDark** [comment]
Thermomachines don't use any power if they aren't cooling something to a significant degree, is this accounted for in your testcase?
