### ISSUE TITLE
a fulpstation player reported that their pda uplink somehow got pda bombed, which shouldn't be possible

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#56276]
![image](https://user-images.githubusercontent.com/42606352/105089073-4a03f400-5a62-11eb-9d1e-fe8707aefa7a.png)
![image](https://user-images.githubusercontent.com/42606352/105089901-550b5400-5a63-11eb-9735-62717f83b0b6.png)
![image](https://user-images.githubusercontent.com/42606352/105089213-70c22a80-5a62-11eb-9589-b6bd6f4704c8.png)
And before the inevitable "who cares about fulp gottem lmao" comment gets posted, I'd like to point out that Fulpstation's detomatix code is essentially the same as ours from last July (when they last resynced to us), and I don't see any changes that we've made since then that should have affected this. We should do some testing to check to see if this feature is bugged on /tg/ as well- perhaps this has something to do with the uplink that was detonated being an IAA one?

**Comment by dragomagol** [comment]
I have PDA bombed another traitor on our codebase (when we had the red/blue documents objective, about a half year ago). Presumably that's still around.

**Comment by LemonInTheDark** [comment]
@ATH1909 could you test if this reproduces? If we don't know how it happens and we don't know if it even exists we're in kinda a pickle. It'd be more workable if fulp had public logs since you could check the Topic() input, but they don't.

**Comment by Fikou** [comment]
this has no reproduction steps or attempts, no round id, is practically just hearsay and fulp doesnt have any public logs so we cant check

**Comment by Qustinnus** [comment]
lol stop reporting fulp players being dumb
