### ISSUE TITLE
Raw crab meat is error

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#56272]
## Round ID:
Reproduced on local

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/105082574-a3f7c000-5a48-11eb-997d-6ede9e40cda3.png)

**Comment by ArcaneMusic** [comment]
Is this spawned crab meat, butchered crab meat, or both?
In addition, can you VV the meat to see what the current Icon_State is on the error meat?

**Comment by dragomagol** [comment]
Both butchered and spawned. 

![image](https://user-images.githubusercontent.com/66640614/105085408-8b89a480-5a4c-11eb-9230-1d7e971f9593.png)

It looks like it's making the meat/rawcrab (which shows the error) instead of the meat/slab/rawcrab, which has an icon.
