### ISSUE TITLE
Emergency Shuttle Camera Consoles don't show any cameras

### ISSUE THREAD

**Issue by CoffeeDragon16** [tgstation/tgstation#56283]
Reporting client version: 513.1536

## Round ID:
[154609](https://scrubby.melonmesa.com/round/154609)

## Testmerges:
- [/mob/living/proc/Life(delta_time)](https://www.github.com/tgstation/tgstation/pull/55534)
- [Modernizes Admin Only Wizard Event, Department Revolt](https://www.github.com/tgstation/tgstation/pull/56061)

## Reproduction:

Call in any emergency escape shuttle with a security camera console, (like the meta shuttle) and check the camera console. No cameras, empty camera net.

**Comment by timothymtorres** [comment]
Do shuttles even have cameras in them?  This seems like it is intended if that’s the case.

**Comment by Mooshimi** [comment]
> Do shuttles even have cameras in them? This seems like it is intended if that’s the case.

why have the console then
