### ISSUE TITLE
Timer SS mishandles secondary queue during MC Init

### ISSUE THREAD

**Issue by fira** [tgstation/tgstation#56292]
## Issue
`SStimer` internally uses the `TIMER_MAX` macro to decide whether to place timers in the secondary queue. It is computed using among others `world.time` and `SStimer.head_offset`. 
The offset is updated by the controller during firing, either directly, or as part of `reset_buckets`.

Due to the nature of map loading, `world.time` is not constant. Furthermore, the controller is not ticking during this. This means that `TIMER_MAX` lags behind becoming obsolete, whereas it is not normally a problem during regular runtime. 

This especially becomes a problem for **deleting timers** as it is also inferred in the same way. If the time that SStimer believes is setup for, is not the same as actual `world.time`, it will end up wrongly inferring this. This is an issue because while for insertion it'd be no big deal (although technically exists too), for deletion it prevents its removal from secondary queue, leaving a QDELETED `/datum/timedevent` eventually crashing in `bucketJoin` next controller firing.

## Illustrated example
This shows as a runtime error at very start of `bucketJoin` as setting the name fails due to lack of a `callBack`. 

Here's homebrewed debug output demonstrating (all part of a MC/SS init sequence, on CM13 codebase as an illustration only):

```
 (JOIN) id=-1 ([0x21009a90]), init_time:382.5, previous_bucket:, gc_destroyed=, callBack:[0x21009a8f], current_time:382.5, tick_lag:0.5, TTR: 982.5, TIMER_MAX:982, wait:600, head_offset:0, Flags: , source: code/game/objects/effects/decals/cleanable/blood/blood.dm:39
 (EJECT) id=-1 ([0x21009a90]), ACTION=standard, init_time:382.5, previous_bucket:secondqueue, gc_destroyed=-2, callBack:NONE, current_time:400, tick_lag:0.5, TTR: 982.5, TIMER_MAX:999.5, wait:600, head_offset:0, Flags: , source: code/game/objects/effects/decals/cleanable/blood/blood.dm:39"
 (JOIN) id=-1 ([0x21009a90]), init_time:382.5, previous_bucket:secondqueue, gc_destroyed=400, callBack:NONE, current_time:417.5, tick_lag:0.5, TTR: 982.5, TIMER_MAX:1017, wait:600, head_offset:0, Flags: , source: code/game/objects/effects/decals/cleanable/blood/blood.dm:39
 ```
 
 ### Line 1 - Initial Insert
 * Timer was created at 382.5
 * It is set to run for 600, so TTR is 982.5
 * Due to rounding, `TIMER_MAX` is 982, less than TTR, so this goes to the secondary queue
 
### LIne 2 - Deletion
 * The timer was indeed put into secondary queue
 * It is being deleted, right now, as evidenced by `gc_destroyed=-2`
 * The callBack is already null'ed
 * `world.time` moved forward +17.5, 382.5 -> 400 
 * as a result `TIMER_MAX` increased aswell because `head_offset` did not follow
 * but the TTR is still same, and now this is Ejected as if in standard queue
 * during usual runtime the timer would have been moved there at controller firing rebuilding buckets, or been ejected correctly due to updated `head_offset` every time as it runs with `SS_TICKER` and `wait = 1`

### Line 3
 * Timer was entierly QDELETED but is still being processed 
 * `SStimer` found it in this mess and tries to add it back into buckets when it is now invalid

## Reproduction 
Kinda hectic due to the fact it depends on exact setup. Took me a while even understanding what happened overall to properly isolate out of CM13 code, then reproduce on /tg/ too.

Initially encountered this during dynamic map loading, here's a breakdown of what would happen:
 * Static init happens, MC New, including `SStimer.PreInit`
 * `/world/New` and `MC.Initialize` starts
 * `SSmapping` handles regular map loading
 * `SSatoms` performs regular atoms initialization
 * Homebrew Dynamic Mapping Subsystem loads in extra `map_template`s
 * `map_template`s pauses Init during MapLoad
 * This used TGMC's `map_template` implementation, which additionally gives option to delete back previous contents
 * Part of deleted contents are CM13 blood decals, which just happened to usually make 60 seconds timers matching issue
 * The timer and callback are deleted alongside the decal
 * `SStimer` attempts to remove these timers, but because `head_offset` drifted as it's not firing, and `world.time` kept going, it tries to remove from `bucket_list` instead of `second_queue`
 * Subsystems Init completes
 * Subsystems starts firing
 * `SStimer` rebuilds buckets, stumbles on the `QDELETED` timer, and throws a runtime error as `callBack` is missing

Here's a matching minimal reproduction case using `map_template`s, suitable for /tg/, with following (not all needed): 
 * Tested in `LOWMEMORYMODE` to shorten init time and reproduce without needing to alter `world.tick_lag`
 * Testing `blank.dmm` map template is just a 5x5 map patch with an `/obj/tester` inside
 * This occurs more often as timers cross around the secondary queue boundary, by default 1 minute
 * Example uses a regular `CALLBACK` as varset variation is just a macro for `GLOBAL_PROC` and therefore not deleted auto

This example reproduces consistently for me on 2 machines but YMMV...

```
/obj/tester/proc/pong()
/obj/tester/Initialize(mapload, ...)
	. = ..()
	addtimer(CALLBACK(src, .proc/pong), 601) // 601 = BUCKET_LEN*tick_lag+1. Not a VARSET_CALLBACK

SUBSYSTEM_DEF(testinsert)
	name = "TestInsert"
	flags = SS_NO_FIRE
	init_order = INIT_ORDER_ATOMS - 10 // After Atoms Init for map_template test case
/datum/controller/subsystem/testinsert/Initialize(timeofday)
	. = ..()
	var/datum/map_template/MT = new("_maps/map_files/debug/blank.dmm")
	MT.load(locate(1, 1, 1)) // Load map template, drifting SStimer.head_offset from world.time
	for(var/obj/tester/O in world)
		qdel(O) // Request timer deletion by freeing the parent datum
```

## Fixes
  From @MrStonedOne : 
![image](https://user-images.githubusercontent.com/604624/105138315-fe4e5a80-5af4-11eb-8f0e-06f19c01b5bd.png)

Makes sense to me. Technically the reverse issue can also happen that timers are misplaced on inset,in which case there's nothing to rely upon - unless making some assumption pre-init during timer ops that the head is always `world.time`

I'd propose a PR but didn't get to finish and time spent understanding all of the above dictates i shall CRASH(bed) for now

**Comment by fira** [comment]
Different example, self contained. No maploading, no atoms. Just funny datums and controller init. It might still be time dependent in reproduction, the cornerstone here is that shit happens between both controller initializing (notably regular game mapload), so time passes while SStimer doesn't fire. 

```
/// Values that stay cool for 60 seconds only
/datum/coolvalues
	var/iscool = TRUE
	var/value
/datum/coolvalues/New(val)
	. = ..()
	value = val
	// Equivalent solution to not doing it if(mapload) for atoms
	// if(!Master.init_time) return
	// Should /datum/coolvalues care ?
	addtimer(CALLBACK(src, .proc/warm), 60 SECONDS)
/datum/coolvalues/proc/warm()
	iscool = FALSE

/// Fridge, stores cool values
/datum/fridge
	var/list/datum/coolvalues = list()
/datum/fridge/New()
	stash("drinks")
	stash("ice")
/datum/fridge/proc/stash(value)
	coolvalues.Add(new /datum/coolvalues(value))
/datum/fridge/proc/warm()
	for(var/datum/coolvalues/V in coolvalues)
		if(prob(60))
			V.warm()

/// Generic Disaster
/datum/disaster
	var/name
	var/chance
/datum/disaster/proc/apply()
	return

/// Heatwave disaster, warms up cool objects
/datum/disaster/heatwave
	name = "Heat Wave"
/datum/disaster/heatwave/apply()
	for(var/datum/fridge/F in SScoolobjects.fridgelist)
		F.warm()

/// Spontaneous combustion disaster, anything warm combusts
/datum/disaster/kaboom
	name = "Spontaneous Combustion"
/datum/disaster/kaboom/apply()
	for(var/datum/fridge/F in SScoolobjects.fridgelist)
		for(var/datum/coolvalues/V in F.coolvalues)
			if(!V.iscool) qdel(V)

/// Create default cool objects
SUBSYSTEM_DEF(coolobjects)
	name = "Cool Objects"
	flags = SS_NO_FIRE
	init_order = 80
	var/list/datum/fridge/fridgelist = list()
/datum/controller/subsystem/coolobjects/Initialize(timeofday)
	. = ..()
	var/guests = rand(30, 50)
	var/needed_fridges = round(guests/4)
	while(needed_fridges--)
		var/datum/fridge/F = new()
		fridgelist += F

/// Init and apply all disasters
SUBSYSTEM_DEF(disasters)
	name = "Disasters"
	flags = SS_NO_FIRE
	init_order = -10
/datum/controller/subsystem/disasters/Initialize(timeofday)
	. = ..()
	for(var/disaster in typecacheof(/datum/disaster, ignore_root_path = TRUE))
		var/datum/disaster/D = new disaster
		D.apply()
```

**Comment by semoro** [comment]
#63427 Will not help here much, since aim there was to fix situation when during reset_buckets with change of BUCKET_LEN to downsize might resulted in timers being placed to second queue with already present `next` and `prev` values, which, then resulted in infinty loop in bucket processing, since re-adding such timers to main buckets will cause infinity linked lists in bucket

**Comment by semoro** [comment]
To fix that particular issue I propose to use 
```patch
+ else if(bucket_joined)
- else if(timeToRun < TIMER_MAX(timer_subsystem))
```
Here https://github.com/tgstation/tgstation/blob/c664e9453105ed723e985fe6eb96344beefe78a0/code/controllers/subsystem/timer.dm#L469

As it is more apporiate flag to determine if timer already went to main buckets

**Comment by timothymtorres** [comment]
Linking these all together since they seem possibly related or dupes: 

#56292 
#42741
#54881
#51164
#48484
#30423

**Comment by semoro** [comment]
Our test merge seems fine

**Comment by timothymtorres** [comment]
@semoro do you know if that fixes any of the listed issues?

**Comment by semoro** [comment]
It is hard to predict, but should at least fix original issue, as code doesn't relies on `TIMER_MAX (world.time)` anymore
