### ISSUE TITLE
Game breaking heretic bug

### ISSUE THREAD

**Issue by mike88511** [tgstation/tgstation#56305]
Reporting client version: 513.1507

## Round ID:
[154666](https://scrubby.melonmesa.com/round/154666)

## Testmerges:
- [Revives old Mafia PR adding security, a mind bogglingly large amount of refactors, some documentation, and other niceities](https://www.github.com/tgstation/tgstation/pull/56199)

## Reproduction:
Game breaking heretic bug - you are able to max out all paths without properly spending points by leaving the dialog open on the codex and maxing/unlocking all paths.

**Comment by SppokiBoogi** [comment]
Tested in thunderdome after mike ahelped it and it is easily repeatable.

**Comment by Googles-Hands** [comment]
In round #154665 I was an void heretic and it seems as though the one starting charge on the manus didnt get spent as I bought the all the t1 spells (or whatever they are called)

**Comment by saprasam** [comment]
![image](https://user-images.githubusercontent.com/62454517/105256456-a6d2dd80-5b3a-11eb-8b6d-fcb56aefc34c.png)
jajajajajajaja ez ez ez

**Comment by ExcessiveUseOfCobblestone** [comment]
@EdgeLordExe
