### ISSUE TITLE
Mog Aggro/Group Aggro/Shared Aggro

### ISSUE THREAD

**Issue by mixzombie** [tgstation/tgstation#56316]
Issue With Current Version.

A Goliath For example. Once Aggro'ed, All Goliath's are also in Aggro Mode. If you for example run into a Goliath, It takes a few seconds for it to lock onto you and begin fighting. But If you are already in combat with a different Goliath and run into line of sight of another, their is zero build up no wait time. The new Goliath previously not involved instantly locks on and fires off a tentacle. 

Though I believe this to be a design flaw, this may have been done to lesson the load on the system. Tying all of the mobs to one on off switch instead of individually could save some resources.

**Comment by SuperNovaa41** [comment]
i.. don't think this is actually a thing
