### ISSUE TITLE
Space Dragon falling down icebox chasms

### ISSUE THREAD

**Issue by jwc1015** [tgstation/tgstation#56333]
## Reproduction:
I was a space dragon, on Icebox, and fell down a chasm, despite space dragons being (as far as I know) flying. Way to reproduce: Space dragon on icebox, fly over a chasm to see if the dragon falls down. I'm presuming this is a bug since carp and dragons both count as flying (like watchers).

**Comment by interestingusernam3** [comment]
Were you somehow stunned or prone? I saw a dragon fly over a chasm yesterday.

**Comment by jwc1015** [comment]
More specifically, I was moving around in the dark, trying to find the station, and then I suddenly fall down a chasm (spinning fall animation, I think) and spend a while making my way back to the station.

**Comment by ATH1909** [comment]
I think that a PR that gives space dragons is_flying_animal = TRUE should work, no?
