### ISSUE TITLE
You can find out if nuke ops spawn by staying in the start menu

### ISSUE THREAD

**Issue by TJatPBnJ** [tgstation/tgstation#56332]
## Round ID:
[154740](https://scrubby.melonmesa.com/round/154740)

## Testmerges:
#55534 
#56221 

## Reproduction:

Stay in the start menu when the round starts, and listen for the lead op being given his paper when the ops are given their equipment.

**Comment by Jared-Fogle** [comment]
perhaps just do this again https://github.com/tgstation/tgstation/pull/53392
