### ISSUE TITLE
suiciding with a PDA only records the message in your chat log and your PDA's message log

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#56331]
```
/obj/item/pda/suicide_act(mob/living/carbon/user)
	var/deathMessage = msg_input(user)
	if (!deathMessage)
		deathMessage = "i ded"
	user.visible_message("<span class='suicide'>[user] is sending a message to the Grim Reaper! It looks like [user.p_theyre()] trying to commit suicide!</span>")
	tnote += "<i><b>&rarr; To The Grim Reaper:</b></i><br>[deathMessage]<br>"//records a message in their PDA as being sent to the grim reaper
	return BRUTELOSS
```
We should let ghosts and the PDA message monitoring console see it too.

Perhaps we could even add an easter egg for if someone's PDA's registered name/account is synced to the "Thirteen (Reaper)" ID card?

**Comment by cacogen** [comment]
Would be nice if you could send a message to someone as you suicided, like a "you're tearing me apart Lisa/I'm fed up with this world" type of thing. Or if it sent it to a random person if you didn't choose a recipient. Sending it to The Grim Reaper is dumb and doesn't make any sense.
