### ISSUE TITLE
the fake pocket protector that's linked to the spy glasses can't be attached to jumpsuits like a real pocket protector can

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#56340]
it's also WEIGHT_CLASS_NORMAL, which makes it as large as a box.

also, it'd be nice if it had an integrated station-bounced radio or something so that you could actually use it as a listening bug (to, say, monitor a released prisoner) instead of just as tool to check to see if the HoS has been ganked in maint yet.

**Comment by Pugie** [comment]
dupe of https://github.com/tgstation/tgstation/issues/54541

**Comment by necromanceranne** [comment]
Closing because it's a dupe. Make it small and it will work.
