### ISSUE TITLE
there's no way to buy a mounted laser implant that corresponds to the non-default arm

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#56366]
they each cost 10 TC, so it seems natural to want to buy two and implant one in each arm. however, in order to switch the arm that the implant is supposed to go into, you have to screwdriver it, which requires taking it out of the autosurgeon it comes in and then having someone install it via normal surgery.

**Comment by itseasytosee** [comment]
I'm pretty sure this was mentioned as intended in the original PR which is wild to me.

**Comment by SuperNovaa41** [comment]
intended then...
