### ISSUE TITLE
crowbarring a vendor circuit doesnt produce a machine frame but its component

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#56371]
154840
crow bar vendor circ
get metal and cable instead of machine frame

**Comment by Tlaltecuhtli** [comment]
for some reasons other machines are having this effect , but not every machine, like the holopad yelds machine frame and DNA vault doesnt

**Comment by TemporalOroboros** [comment]
Can confirm. I had this happen with the toxins heater yesterday.

**Comment by RaveRadbury** [comment]
So #56287 was merged, which caused this, because it's stated dependency, #56282 has not yet been merged. Once the second PR is merged this should sort out.

**Comment by Timberpoes** [comment]
Scratch that. I realised that I never pushed any additional changes to #56282, so #56287 included all of #56282's changes and its own.

I'll be PRing a fix shortly. Issue is that machines that are dense can block their own frames from spawning.
