### ISSUE TITLE
Built griddle was unanchored and unanchorable

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#56388]
## Round ID:

Not sure

## Testmerges:

Not sure

## Reproduction:

Happened on Manuel last night. Kitchen was destroyed by a vortex anomaly. Someone else rebuilt the griddle. You could push it around and cook on it, and any attempt at wrenching it just put the wrench on the griddle or attacked it. I assume this happens with any built griddle. It's a problem only because sometimes you bump it and move it without wanting to.

**Comment by Qustinnus** [comment]
If you know who made the bug tag them so they can be assigned

**Comment by SuperNovaa41** [comment]
Fixed
