### ISSUE TITLE
New keybinds shriek that they need updating, even if they are not automatically bound to anything.

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#56382]
![image](https://user-images.githubusercontent.com/35135081/105612523-9a849580-5d71-11eb-9178-31e16628dc49.png)

**Comment by cacogen** [comment]
Happened with noogie too

**Comment by RaveRadbury** [comment]
Quick fix: go into the options, hit the keybind for the emote, press escape. It won't bother you anymore.

**Comment by cacogen** [comment]
It only says this the round when they're new but it either shouldn't tell you about new emotes without bindings or it shouldn't tell you this loudly.

**Comment by RaveRadbury** [comment]
I had noogie coming up repeatedly.
