### ISSUE TITLE
You forget how to permamently anchor a paradoxical object

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#56385]
![image](https://user-images.githubusercontent.com/22849149/105619632-3a661180-5dba-11eb-98c7-c595ece88d61.png)

permamently

**Comment by cacogen** [comment]
Why does it even tell you this to begin with

**Comment by Low3** [comment]
> Why does it even tell you this to begin with

RD skillchip for suplexing nullrods i guess.
