### ISSUE TITLE
blob can spawn when it shouldnt aka when shuttle is unrecallable

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#56383]
154857

https://github.com/tgstation/tgstation/pull/53488

[2021-01-23 18:13:51.329] SHUTTLE: Goodoldtimes/(Boris Mahnov) has called the emergency shuttle.

[2021-01-23 18:22:04.591] GAME: 18:22:04.591] GAME: DYNAMIC: Polling 13 players to apply for the Blob ruleset. 

there is a 8 min difference, shuttle cant be recalled after 5 min so this isnt working right

**Comment by dragomagol** [comment]
Was it blue alert?

**Comment by MrMelbert** [comment]
Looks like while the blob EVENT is unable to fire after `EMERGENCY_PAST_POINT_OF_NO_RETURN`,
...the dynamic ruleset does not abide by the same check and can be selected afterwards

**Comment by timothymtorres** [comment]
Looks like #65997 fixed this
