### ISSUE TITLE
Using the alt+click menu to place things on a griddle results in them disappearing

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#56389]
## Round ID:
154888

## Testmerges:
55534 

## Reproduction:

I used the alt+click menu to speed up the cooking process by stacking the griddle as much as possible. Later I discovered that the patties disappear. I guess they're ending up in the griddle? That or their location is set to null. They're not on the tile. I assume it has to do with pixel placement and  the alt+click menu's lack of support for it.

**Comment by Qustinnus** [comment]
I'm pretty sure this was fixed ages ago

**Comment by Qustinnus** [comment]
It was
