### ISSUE TITLE
Skyburger flattened into singularity

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#56390]
## Round ID:
154888

## Testmerges:
55534

## Reproduction:

1. Get a bunch of patties, cheese, whatever goes on a burger
2. Get a burger bun
3. Add enough of the aforementioned items to get it screen length
4. Watch as every overlay but the bottom bun disappears, thus nullifying your hard culinary work 
5. Attempt to show people your accomplishment and have them not understand and show complete disinterest in such an uninteresting single bun "burger", despite its name and description betraying its true nature

**Comment by TemporalOroboros** [comment]
It sounds like you ran into the overlay limit. Nice.

**Comment by LemonInTheDark** [comment]
there should be a Burger Limit Top or BLT, if you attempt to surpass it your burger should fall to the ground and break apart into component burgers

**Comment by Sealed101** [comment]
```
[2021-01-24 05:37:11.822] runtime error: Too many overlays on /obj/item/food/burger/empty - 100, refusing to update and cutting
 - proc name: stack trace (/datum/proc/stack_trace)
 -   source file: unsorted.dm,1065
 -   usr: null
 -   src: Overlay (/datum/controller/subsystem/overlays)
 -   call stack:
 - Overlay (/datum/controller/subsystem/overlays): stack trace("Too many overlays on /obj/item...")
 - Overlay (/datum/controller/subsystem/overlays): fire(0, 1)
 - Overlay (/datum/controller/subsystem/overlays): ignite(0)
 - Master (/datum/controller/master): RunQueue()
 - Master (/datum/controller/master): Loop()
 - Master (/datum/controller/master): StartProcessing(0)
```

- in any case #68205 culled the max ingredients to 100-3
