### ISSUE TITLE
Twisted Conversion instantly deletes cores when used on AI shells

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#56391]
## Round ID:
[154888](https://scrubby.melonmesa.com/round/154888)

## Testmerges:
#55534

## Reproduction:

>Try to do something against robustins bloated roundtype
>Get emped from their meme spell
>Have instant cast twisted conversion used on me
>Unable to re-enter body (the core) and see my shell become a free construct body
>Wonder why this round type still exists while writing a passive aggressive reproduction.

**Comment by ATH1909** [comment]
how is twisted conversion converting you instantly?

**Comment by AlinaStarkova** [comment]
reference of this added, as AI shell i killed 2 cultists as medborg, as one was in soft crit it instant converted me to a construct (i know it was instant as i was moving the whole time, it just happened) and boom, i ghosted, despite having a healthy core, an admin threw me back into my core for me, but this shouldnt normally happen

![image](https://user-images.githubusercontent.com/40489693/112590024-893f2000-8dd8-11eb-82cc-60dff8dadb3f.png)
