### ISSUE TITLE
spiders don't slip

### ISSUE THREAD

**Issue by c420-o** [tgstation/tgstation#56406]
Reporting client version: 513.1536

## Round ID:
[154942](https://scrubby.melonmesa.com/round/154942)

## Testmerges:
- [/mob/living/proc/Life(delta_time)](https://www.github.com/tgstation/tgstation/pull/55534)

## Reproduction:

someone opened a water vapor canister in the hallway and the broodmother spider didn't slip

**Comment by Pumpkinoe** [comment]
simplemobs aren't supposed to slip? this isn't a bug

**Comment by optimumtact** [comment]
![imfine](https://user-images.githubusercontent.com/2544323/105649615-cc366180-5f15-11eb-9598-fc3c09c271f4.jpg)

**Comment by itseasytosee** [comment]
@Pumpkinoe spiders are bugs
