### ISSUE TITLE
Meat from a butchered bear cannot be eaten

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#56405]
## Reproduction:
Spawn bear
Kill Bear
Butcher bear
Pick up meat
Try to eat
Slap yourself with the bear meat

**Comment by MrMelbert** [comment]
![image](https://user-images.githubusercontent.com/51863163/105652450-e40ed680-5e7e-11eb-9b3a-a6d27a807923.png)
looks like meat from butchering stuff doesn't get the edible component at all

**Comment by Pugie** [comment]
https://github.com/tgstation/tgstation/issues/56126
Probably related

**Comment by SuperNovaa41** [comment]
No longer an issue
