### ISSUE TITLE
Runtime in unsorted.dm, line 1065: atom_attack_hand overridden when opening crate

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#56418]
**Reporting client version:** 513.1539

## Round ID:

Local

**Master commit:** 18c003ab5ace4b214395218a01f19f54348f4769

## Reproduction:

Runtime in unsorted.dm, line 1065: atom_attack_hand overridden. Use override = TRUE to suppress this warning

**Comment by necromanceranne** [comment]
Oh I fixed this already whoops.
