### ISSUE TITLE
Killing a giant spider made it turn invisible

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#56411]
Reporting client version: 513.1539

## Round ID:
[154954](https://scrubby.melonmesa.com/round/154954)

## Testmerges:
- [/mob/living/proc/Life(delta_time)](https://www.github.com/tgstation/tgstation/pull/55534)

## Reproduction:

1. I used a fire extinguisher to kill a giant spider
2. It turned invisible

**Comment by ArcaneDefence** [comment]
Presumably fixed by https://github.com/tgstation/tgstation/pull/56484
