### ISSUE TITLE
Human burgers don't get named after the human anymore

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#56421]
## Round ID:

Various

## Testmerges:

Unrelated

## Reproduction:

1. Get human meat
2. Grind it into a meat ball
3. Flatten it into a patty
4. Cook the patty on the griddle
5. Use the crafting menu to make it into a human burger
6. Isn't named after the human used to make it anymore (or their job title) which is still in the code

Another issue is that lizards get named human burgers and if I remember correctly spider meat becomes strange meat which also becomes human burgers.

**Comment by SuperNovaa41** [comment]
Fixed by YOU https://github.com/tgstation/tgstation/pull/59286

**Comment by cacogen** [comment]
This seems like three separate issues that I should've made three separate reports for. However, now that I no longer care, I will not make issues for the other two things.
