### ISSUE TITLE
Shipping manifests have an empty bullet point at the top

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#56423]
Reporting client version: 513.1539

## Round ID:
[154994](https://scrubby.melonmesa.com/round/154994)

## Testmerges:
- [/mob/living/proc/Life(delta_time)](https://www.github.com/tgstation/tgstation/pull/55534)

## Reproduction:

1. Order something
2. Examine the manifest
3. List of items starts with an empty bullet point

**Comment by Mooshimi** [comment]
This seems to no longer be the case 
![image](https://user-images.githubusercontent.com/85910816/170622447-d9c9b06f-6266-4173-8bed-bd6e77dc8dbe.png)

**Comment by cacogen** [comment]
should've posted a screenshot to prove it was actually happening but glad to hear it's no longer the case
