### ISSUE TITLE
SKELETON KEYS Are Hurting Miners

### ISSUE THREAD

**Issue by mixzombie** [tgstation/tgstation#56425]
No seriously Let me explain. Necropolis chests are rewards for a Time Sink. Just like Shock Touch and Hulk are rewards for Geneticist Time Sink.  To add another level to acquire rewards from Necropolis Chests, Is Taking away from a delicate balance.

If timed and done well a Miner can acheive 2k points in the first 20 minutes of the shift. Keep in mind that this time is spent NOT "rushing" Tendrils. Enough points to Either Upgrade your KPA OR A luxury Medi pens and a Adv Mining Scanner. To Add a requirement to open the chest, Is taking away from the base Miner upgrade loop. Instead of a constant ramp up in ability and strength to hopefully take down lavaland boss mobs, Lets spend our hard earned points on keys for our lootboxes! 

Necropolis Chests are The Only rewards new miners can enjoy and not without trouble. Compared to someone who has several hundred hours of mining Necropolis chests are very hard to get. Ive seen Long time miners get destroyed by Legion Tendrils, but as we all know Watcher tendrils are Basically taking candy from a baby. Goliath tentacles have taken down every single miner at some point or another, And if that happens next to a tendril that's a Game Over. 

It was a Nice thought, maybe even good intentions but this is not the way anyone wants to see the game evolve or grow. Maybe instead of having to purchase our "keys" from a vendor we could have a certain number of mobs come out of the tendril before its beaten, Instead of it just spawning an endless supply of bones, meant, sinew, diamonds, and legion cores. Maybe each tendril has a max amount to spawn or maybe they spawn an amount of mobs relative to the reward. So if this tendril has Champions Armor or Strange Potion, Have it spawn a higher number of mobs before the tendril gives out and is "defeated".

**Comment by timothymtorres** [comment]
Unfortunately the issue tracker is only for bug reports.  Conversation about balance changes should be moved to the discord or forums.
