### ISSUE TITLE
Bodybags cannot be folded

### ISSUE THREAD

**Issue by Sparkezel** [tgstation/tgstation#56457]
## Round ID: [155076](https://scrubby.melonmesa.com/round/155076)
rather irrevelant 

## Testmerges:
https://github.com/tgstation/tgstation/pull/56019 https://github.com/tgstation/tgstation/pull/55645 https://github.com/tgstation/tgstation/pull/56221

## Reproduction:
Get a body bag
Unfold
open and close
try to fold it, doesnt fold
contemplate your life without bodybags

**Comment by kopoba** [comment]
>There are too many things inside of the body bag to fold it up!

**Comment by Sparkezel** [comment]
yup! even when empty!

**Comment by ATH1909** [comment]
Is it counting those invisible lighting objects?

**Comment by Sparkezel** [comment]
I have no goddamn idea :(

**Comment by antropod** [comment]
![bodybag](https://user-images.githubusercontent.com/7479888/106406592-cf1bdf80-644a-11eb-84c6-78744615c131.png)

**Comment by kopoba** [comment]
fixed with https://github.com/tgstation/tgstation/pull/56496

**Comment by necromanceranne** [comment]
If this is fixed I'll close it.
