### ISSUE TITLE
Can place human beings within a grill

### ISSUE THREAD

**Issue by BorisVcBorison** [tgstation/tgstation#56475]
Reporting client version: 513.1536

## Round ID:
[155148](https://scrubby.melonmesa.com/round/155148)

## Testmerges:
- [Dynamic 2021](https://www.github.com/tgstation/tgstation/pull/56221)

## Reproduction: 
Using the alt click, going into status, and clicking on a grill with any object, including pets or pick-uppable humans, allows you to trap them within the grill, until they move.

**Comment by maxymax13** [comment]
you're going to the grill dimension

**Comment by Tulenich** [comment]
Based

**Comment by LemonInTheDark** [comment]
It's not just ian who can be sent to the girdle dimension, works with lots of things

**Comment by interestingusernam3** [comment]
New nukeops gamemode crew strat.

**Comment by necromanceranne** [comment]
I just want to grill in the void for god's sake.

**Comment by LemonInTheDark** [comment]
Good news, the portal to the grill dimension has been sealed. See #56557 for more details
![image](https://user-images.githubusercontent.com/58055496/109097811-ed38d080-76d4-11eb-9b88-d0e66d4a9cec.png)
