### ISSUE TITLE
you can scoop up people

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#56473]
attempt to fireman carry
they go into your hand
what

**Comment by trexter555** [comment]
it also suffocates them as if they're in a bluespace bodybag

**Comment by TemporalOroboros** [comment]
How

**Comment by notfrying1pans** [comment]
can you put someone into your bag

**Comment by MrMelbert** [comment]
do you have a round ID for this? Admins can VV people to be scoop up-able, so knowing if this was done or not would be helpful

**Comment by notfrying1pans** [comment]
i want to fucking put someone into the destructive analyzer and destroy them

**Comment by trexter555** [comment]
apologies i have autism, it was an admin event

**Comment by ShibaInuLord** [comment]
lol
