### ISSUE TITLE
Hauntium is Unobtainable

### ISSUE THREAD

**Issue by Y0SH1M4S73R** [tgstation/tgstation#56477]
## Round ID: 
[155156](https://scrubby.melonmesa.com/round/155156)

## Testmerges: 
None

## Reproduction: 
Another player and I took photos with ghosts in them. We were unable to obtain hauntium from them. We tried the sheetmeister, the autolathe, and the destructive analyser. According to the other player, the science goggles said the photos didn't have any mats in them.

**Comment by Qustinnus** [comment]
fixed
