### ISSUE TITLE
RoboTact Logs are blank

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#56494]
Reporting client version: 513.1533

## Round ID:
[155220](https://scrubby.melonmesa.com/round/155220)

## Testmerges:
- [Dynamic 2021](https://www.github.com/tgstation/tgstation/pull/56221)

## Reproduction:
Be a cyborg or AI in a shell. Notice your logs are always empty.

**Comment by dragomagol** [comment]
More context, was latejoin assistant who got borged. Also had this as a latejoin AI with shell.

**Comment by zxaber** [comment]
I forgot this was reported to me. I'll look into it when I can.
