### ISSUE TITLE
Canisters do not seem to function as reaction chambers anymore

### ISSUE THREAD

**Issue by esainane** [tgstation/tgstation#56499]
## Reproduction:

- `spawn /obj/machinery/portable_atmospherics/canister/toxins`
- `spawn /obj/machinery/portable_atmospherics/canister/nitrous_oxide`
- RPD in three connectors around a gas mixer; set the gas mixer to 65% plasma, 35% N2O. Turn it on.
- Wrench in the source canisters.
- `spawn /obj/machinery/portable_atmospherics/canister/tier_2`
- Wrench in the output canister.

- Use an analyzer on the output canister, observe >10 moles of N2O and Plasma at 25kPa, but no BZ being produced.

- Admin proc call `react()` on the destination canister's `air_contents`, receive a result of `1` to indicate that reactions did and should be occurring.

- Use an analyzer to confirm that one step happened.
- Use the analyzer again repeatedly to confirm that nothing aside from that one step happened or will ever happen.

- `say *cry`

No runtimes in server logs.

Possibly related to entities being too eager to go to sleep in #56297, probably related to the recent atmos rework.

**Comment by nightred** [comment]
@Ghommie has the new reaction machine removed canisters as a reaction point?

**Comment by vincentiusvin** [comment]
Could not reproduce
![image](https://user-images.githubusercontent.com/54709710/106317770-5af20800-62a1-11eb-9075-f470c87febeb.png)
Was the canister unwrenched?

**Comment by esainane** [comment]
You are right, I don't know why I expected a canister's gas_mixture to process atmos while wrenched

**Comment by Ghommie** [comment]
> 
> 
> @Ghommie has the new reaction machine removed canisters as a reaction point?

Sorry for being so late in this reply, but I don't recall having anything to do with atmospheric reactions in the past few months.
Also glad this turned out to be a non-issue.
