### ISSUE TITLE
crafting a full tile window from craft menu is likely to stuck you in it

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#56502]
https://github.com/tgstation/tgstation/blob/03cf049f331725f231bf9886d60a98ce0b5739db/code/game/objects/structures/window.dm#L100-L106
this?

**Comment by Sparkezel** [comment]
Possible reproduction
1. Make a fulltile window/teleport inside one
2. For some reason you canot move down, sometimes in any direction at all
3.Cry because you are GBJ'd

**Comment by Sealed101** [comment]
can not reproduce
