### ISSUE TITLE
Monkey Martial Arts broken

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#56513]
## Round ID: [155266](https://scrubby.melonmesa.com/round/155266)
 #56397 broke monkey's combos from #55583 
 
 Chimp Quarter Combat is the best thing that happened to this game, please fix.

**Comment by LemonInTheDark** [comment]
What does broke mean, gib replication steps god damn it

**Comment by Livrah** [comment]
> What does broke mean, gib replication steps god damn it

>Monkey
>Sleeping Carp
>No martial art attacks, standart monke bite/shove instead. Sleeping Carp tab showing at status panel.

![Screenshot_119](https://user-images.githubusercontent.com/64209864/106352780-67fe0e00-6318-11eb-877f-6702c9884f43.png)

Before #56397 sleeping carp monke worked fine.

**Comment by jacklecroy** [comment]
Ugh monkeys are humans now so the check for both to be human passes and so apply_martial_art proc doesn't do anything.

**Comment by Serxule** [comment]
its because monkeys use bite attacks, not punches, this is most likely intended

**Comment by Serxule** [comment]
> its because monkeys use bite attacks, not punches, this is most likely intended

i realized I'm semi-wrong but it also got merged out of nowhere so it was probably never done correctly

**Comment by jacklecroy** [comment]
I will try to fix this soon

**Comment by jacklecroy** [comment]
I'm going to wait on #56601

**Comment by Qustinnus** [comment]
cheers

**Comment by ATH1909** [comment]
> I'm going to wait on #56601

@jacklecroy okay #56601 is merged now please fix this
