### ISSUE TITLE
Custom job name dialog appears under window

### ISSUE THREAD

**Issue by maxymax13** [tgstation/tgstation#56521]
## Round ID:
Local server built from clean git reset --hard

## Testmerges:
No

## Reproduction:
Go to an identification console, click custom job name button. The page just refreshes, and then you realize the custom job name pop-up appears behind the window.

https://user-images.githubusercontent.com/38844529/106369959-9c7fc300-6334-11eb-90d6-9fbee1094b8e.mp4

**Comment by maxymax13** [comment]
I appear to be unable to change the issue name.

**Comment by SuperNovaa41** [comment]
old ui, this has been fixed
