### ISSUE TITLE
Evil Nanomeds (the ones that crush people) are invincible and can crush people in a 5x5 area

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#56546]
Round ID: [155406](https://scrubby.melonmesa.com/round/155406)

Reproduction:
make evil nanomed (whatever the fuck these are or what causes them), watch hundreds of people unable to kill it and have it crush people 2 tiles away from it in every direction, it can also change its direction to somewhere different than where it was aiming.

**Comment by Tlaltecuhtli** [comment]
does  this
 armor = list(MELEE = 100, BULLET = 100, LASER = 100, ENERGY = 100, BOMB = 0, BIO = 0, RAD = 0, FIRE = 100, ACID = 50) cause the mob to have these funny values too?

**Comment by TemporalOroboros** [comment]
Probably.
From the looks of things I recommend explosives.

**Comment by Sparkezel** [comment]
You also cannot decostruct YouTools at all, but you can deconstruct Nanomeds, thats very important during brand intelligance

**Comment by Qustinnus** [comment]
its not the mob its the same vendor

**Comment by Qustinnus** [comment]
`have it crush people 2 tiles away from it in every direction, it can also change its direction to somewhere different than where it was aiming.`

i cant reproduce this at all so you'll need to show me a vid of this.

**Comment by Serxule** [comment]
> `have it crush people 2 tiles away from it in every direction, it can also change its direction to somewhere different than where it was aiming.`
> 
> i cant reproduce this at all so you'll need to show me a vid of this.

can you tell me how to make the evil nanomeds? if so I can try to do it, last time it was during a fight with spiders so I'm not sure if that would change anything

**Comment by Qustinnus** [comment]
either trigger the brand intelligence event or var edit, use the drop down, give it an AI controller, make it the vending ai
