### ISSUE TITLE
Making custom foods while holding the ingredients in hand puts the food in your mob

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#56544]
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
Hold a bowl
Hold a food item to make a salad out of too
click on bowl with food
it goes into your contents.

Works with burgers and such too.

![image](https://user-images.githubusercontent.com/51932756/106396057-e44d2b80-63c2-11eb-8057-ba82d1a5ba0f.png)

**Comment by interestingusernam3** [comment]
feature

**Comment by swindly** [comment]
The problem is that the customizable_reagent_holder component currently places the replacement item (the salad bowl with salad in it) in the current parent's (the empty salad bowl's) loc, which is the person holding the current parent.

**Comment by Yenwodyah** [comment]
Also happens if it's in your pockets

**Comment by ArcaneDefence** [comment]
This no longer reproduces.
