### ISSUE TITLE
Humonkeys (and maybe monkeys) now teleport out of the genetics scanner (even locked) and run away

### ISSUE THREAD

**Issue by Robustitron** [tgstation/tgstation#56559]
## Round ID:
155424 on basil

## Testmerges:
#56221: 'Dynamic 2021' by Jared-Fogle at commit ee9f714058

## Reproduction:

1) Obtain a monkey or humonkey

2) Get them in a state where they are running towards something. Give them 5 minutes of existence and they'll probably be in this state, because they're attracted to some tile or object. You could also slap it and itl be in a permanent state of running to and attacking you.

3) Try putting them in the genetics scanner

4) They immediately teleport out of the scanner and continue running to wherever they want to be, the scanner still appears closed with a person inside, but it's actually empty, the scanner computer says no one is inside. Locking wont keep them in, they'll just teleport out of the scanner magically.

This is very shitty to deal with since all the humonkeys now end up falling in love with some floor tile/object, or aggro against someone permanently, and become impossible to scan because of their new teleporting powers.

This is a fairly recent bug that I noticed for the first time yesterday, before that, humonkeys could never leave the scanner themselves, even if it was unlocked.

**Comment by kopoba** [comment]
some relevant comments and experiments can be found here https://github.com/tgstation/tgstation/issues/55776#issuecomment-751964961

**Comment by Robustitron** [comment]
It's also worth pointing out that this basically shuts down Genetics if the monkeys ever aggros to a geneticist (I accidentally disarm shoved one, and they stay triggered for the whole round), even if you wrangle every humonkey into the glass cage, the one in the scanner will always teleport back out to go attack you.

From then on you're limited to testing on living or SSD humans, or the geneticist retires and someone (non targeted) takes their place.

**Comment by Qustinnus** [comment]
fixed
