### ISSUE TITLE
Throwing a held mob crashes the game

### ISSUE THREAD

**Issue by c420-o** [tgstation/tgstation#56551]
## Reproduction:
held a corgi puppy and tried to throw it.

the crashlog said an exception occured at if(QDELETED(src)) in /atom/movable/proc/throw_at

**Comment by ArcaneDefence** [comment]
[2021-01-31 22:54:22.051] runtime error: Qdeleted thing being thrown around.
 - proc name: throw at (/atom/movable/proc/throw_at)
 -   source file: atoms_movable.dm,670
 -   usr: Sybil McShain (/mob/living/carbon/human)
 -   src: Ian (/obj/item/clothing/head/mob_holder)
 -   usr.loc: the carpet (96,132,2) (/turf/open/floor/carpet)
 -   src.loc: null
 -   call stack:
 - Ian (/obj/item/clothing/head/mob_holder): throw at(the carpet (91,132,2) (/turf/open/floor/carpet), 7, 2, Sybil McShain (/mob/living/carbon/human), 1, 0, /datum/callback (/datum/callback), 1000, 0, 1)
 - Ian (/obj/item/clothing/head/mob_holder): throw at(the carpet (91,132,2) (/turf/open/floor/carpet), 7, 2, Sybil McShain (/mob/living/carbon/human), 1, 0, /datum/callback (/datum/callback), 1000, 0, 1)
 - Ian (/obj/item/clothing/head/mob_holder): throw at(the carpet (91,132,2) (/turf/open/floor/carpet), 7, 2, Sybil McShain (/mob/living/carbon/human), 1, 0, /datum/callback (/datum/callback), 1000, 0, 1)
 - Ian (/obj/item/clothing/head/mob_holder): safe throw at(the carpet (91,132,2) (/turf/open/floor/carpet), 7, 2, Sybil McShain (/mob/living/carbon/human), 1, 0, null, 1000, 0)
 - Sybil McShain (/mob/living/carbon/human): throw item(the carpet (91,132,2) (/turf/open/floor/carpet))
 - Sybil McShain (/mob/living/carbon/human): ClickOn(the carpet (91,132,2) (/turf/open/floor/carpet), "icon-x=5;icon-y=24;left=1;scre...")
 - the carpet (91,132,2) (/turf/open/floor/carpet): Click(the carpet (91,132,2) (/turf/open/floor/carpet), "mapwindow.map", "icon-x=5;icon-y=24;left=1;scre...")
 - Guest-1920900955 (/client): Click(the carpet (91,132,2) (/turf/open/floor/carpet), the carpet (91,132,2) (/turf/open/floor/carpet), "mapwindow.map", "icon-x=5;icon-y=24;left=1;scre...")
 
 Just looks like a runtime

**Comment by MrMelbert** [comment]
same runtime reported here #53218

**Comment by ArcaneDefence** [comment]
then we can just close it as duplicate.
