### ISSUE TITLE
Make The Swarmer AI Teleport Players After Putting Them In Stamina Crit

### ISSUE THREAD

**Issue by NaturesMayhem** [tgstation/tgstation#56558]
The replicated swarmers that are controlled by AI will continue to hit a player forever till someone decides to save them or a player controlled swarmer teleports them. I think a quick change to their AI to make them teleport the player after they fall into stamina crit would be best. 

This should be added because it's not fun for players to be stuck in stamina crit.

**Comment by interestingusernam3** [comment]
Feature requests are not handled in the repository. The best place to discuss these ideas would be on the /tg/station 13 forums here: https://tgstation13.org/phpBB/viewforum.php?f=9&sid=5153c1c704a4fb1006bf7a265e45e03f
