### ISSUE TITLE
Round start mice spawn inside electrified grilles adjacent to space

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#56553]
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
![image](https://user-images.githubusercontent.com/51932756/106401326-ba0a6680-63e0-11eb-902c-09d099ec2e46.png)
Look pa, I got a twofer!

**Comment by dragomagol** [comment]
Fixed by #56512
