### ISSUE TITLE
Spacevine controller doesn't have STAMINA

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#56552]
## Reproduction:

1. Trigger space vines
2. Watch them
3. They will die out on their own
4. They will die faster than they spread
5. They will just die period
6. Its very sad

This does not occur with kudzu seeds that are planted, only the actual spacevines event.

This might have something to do with the spacevine controller.

Its also kinda funny that the VV dropdown options for spacevines are buried in the actual controller but thats besides the point.

**Comment by ArcaneDefence** [comment]
What were the conditions in this particular situation? Just yeeting the event at meta at shift start and doing nothing had these results
![image](https://user-images.githubusercontent.com/51932756/106401451-677d7a00-63e1-11eb-8ab9-bf2cb71daa57.png)
![image](https://user-images.githubusercontent.com/51932756/106401475-824fee80-63e1-11eb-9ece-ed3603c3b104.png)

**Comment by Misdoubtful** [comment]
Not really anything out of the ordinary. The event will trigger or be triggered, then vines will spread but others get hit by deletion, so it fizzles out. 

Reproduced multiple times during a round and seen it happen across rounds.

**Comment by MrMelbert** [comment]
I believe this has something to do with the atmos changes

If you notice, whenever vines spawn near scrubbers or vents, they tend to die before they can spread.

You can replicate this by getting a pack of kuzdu seeds and tossing it near vents or scrubbers. They'll die almost immediately

Space vines are atmos sensitive so it probably has something to do with that.

**Comment by Misdoubtful** [comment]
Yeah I have a feeling this is due to the bit from the LINDA Reforged PR.
