### ISSUE TITLE
Open grav gen through wall

### ISSUE THREAD

**Issue by RokutheBasiliskTamer** [tgstation/tgstation#56564]
Reporting client version: 513.1542

## Round ID:
[155431](https://scrubby.melonmesa.com/round/155431)

## Testmerges:
- [Tramstation: choo choo MORE MAP COMIN' THROUH](https://www.github.com/tgstation/tgstation/pull/56509)
- [Dynamic 2021](https://www.github.com/tgstation/tgstation/pull/56221)
- [Adds station traits: Small modifiers that can randomly be chosen each round](https://www.github.com/tgstation/tgstation/pull/56309)

## Reproduction:

From above grav gen in  the tram tunnel above the radiation sign during rad storm was able to access the grav gen interface through the wall

**Comment by dragomagol** [comment]
Appears to have been fixed
