### ISSUE TITLE
Nanites and viruses not working on monkeys

### ISSUE THREAD

**Issue by Lyude75** [tgstation/tgstation#56569]
I have discovered during a few rounds as Virologist and Scientific that viruses don't infect monkeys (no hud and no impact whatsoever, even on humanized monkeys). The same goes for nanites, that don't work on monkeys either.
I think it is a big that needs fixing.

On nanites, I have the feeling that the hallucination "plasma flood" doesn't work by the way, but I am not sure of it.
Thanks a lot guys!

**Comment by MTandi** [comment]
I didn't have any issues with Nanites in monkeys. Can you provide more information on what exactly doesn't work.

As for viruses, I believe this should be linked: https://github.com/tgstation/tgstation/pull/56585
