### ISSUE TITLE
AI can blow up air-pipes with overload electronics

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#56581]
Round ID: [155485](https://scrubby.melonmesa.com/round/155485)

Reproduction:
well basically the title, the AI can blow up air pipes with overload electronic whatever, admin confirmed it was a code issue, I cant code so here's a bug report.
have an image too https://imgur.com/a/ZgLqd6d

**Comment by saprasam** [comment]
sounds like a skill issue to me

**Comment by Serxule** [comment]
i have been notified this is a problem with all air pipes, that's even worse

**Comment by LemonInTheDark** [comment]
Fun fact, all atmos components including pipes are machines. Should prob have a define that blacklists atmos pipes or something for this sort of thing
