### ISSUE TITLE
Issue with metastation's new xenobio

### ISSUE THREAD

**Issue by kinneb** [tgstation/tgstation#56590]
## Round ID:
[155527](https://scrubby.melonmesa.com/round/155527)

## Testmerges: 
#56509 #56221 

## Reproduction:
 When using the xenobio terminals on metastation's new xenobio (#56354) , there is a wall preventing me from dumping dead slimes picked up into the slime processor, right here, where the firelocks are: 
![issue1](https://user-images.githubusercontent.com/75904284/106595681-d24ac480-654b-11eb-908a-bdd6f1d9b234.PNG)
There is also an issue with the terminals not being linked automatically like all other xenobios are.
![image](https://user-images.githubusercontent.com/75904284/106595751-ec84a280-654b-11eb-9691-2287810def4d.png)
This is really annoying.

**Comment by Zytolg** [comment]
This issue have been resolved by #56908
