### ISSUE TITLE
Wizards can jaunt out of the wizard ship and onto the CentCom z-level.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#56603]
## Reproduction:
1. Become a space wizard
2. Jaunt
3. Unjaunt
4. Teleport to somewhere on the CentCom z-level.

https://user-images.githubusercontent.com/53582584/106683945-56b43c00-657a-11eb-8ce7-6bbe54eb0a7f.mp4

@tralezab

**Comment by ShibaInuLord** [comment]
its always right there at ctf, tested myself earlier

**Comment by TemporalOroboros** [comment]
I've managed to get the escape shuttle and the walls between the holodeck templates myself. They're just smaller so they're less likely.

**Comment by interestingusernam3** [comment]
https://media.tenor.com/images/62c5487526c00818c56c67f4b5397e29/tenor.gif
