### ISSUE TITLE
Pancake Batter not making pancakes on griddles.

### ISSUE THREAD

**Issue by jwc1015** [tgstation/tgstation#56629]
Reporting client version: 513.1527

## Round ID:
[155633](https://scrubby.melonmesa.com/round/155633)

## Testmerges:
- [Dynamic 2021](https://www.github.com/tgstation/tgstation/pull/56221)
- [Tramstation: choo choo MORE MAP COMIN' THROUH](https://www.github.com/tgstation/tgstation/pull/56509)

## Reproduction:
I made pancake batter, poured out 5u into a beaker, and then splashed the griddle with the batter (harm intent). The 'raw' pancakes did not appear.

**Comment by itseasytosee** [comment]
I'm not super familiar with pancake mechanics but I'd recon you need to use help intent.

**Comment by jwc1015** [comment]
> 
> 
> I'm not super familiar with pancake mechanics but I'd reckon you need to use help intent.

If you do that you just place the beaker on the griddle; you need to splash the batter on the griddle for the pancakes, as far as I know.

**Comment by interestingusernam3** [comment]
I think it might need more than 5u

**Comment by interestingusernam3** [comment]
Was there anything else on the griddle? Pancake creation will fail if there is too much stuff on the griddle already.

**Comment by jwc1015** [comment]
The griddle was completely empty beforehand; also, I've tried it before with (I think) around 30u, and it didn't work then either. Also, to the best of my knowledge the pancake griddle PR says 5u per pancake.
