### ISSUE TITLE
dna scanners will eject their board and parts randomly

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#56632]
this may have something to do with monke, but ive noticed some rounds where a dna scanner or two in genetics will just drop its board and parts while still being completely functional, basically duping its internals onto the ground. no idea how to reproduce

![image](https://user-images.githubusercontent.com/22849149/106838822-9eae8e00-6662-11eb-8cbd-aea6133771f2.png)
an example ( the not visible one on the top was fine)

**Comment by Jared-Fogle** [comment]
@Timberpoes a thousand bucks says its the components in machine thing again

**Comment by kinneb** [comment]
This happened with a gibber recently too, where it dropped its board randomly after use.

**Comment by dragomagol** [comment]
Does it only happen to machines with monkeys?
