### ISSUE TITLE
after combat mode there is no more right click to show tile content 

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#56642]
with either combat mode or not you can no longer use right click to see tile content, which is game breaking as alt click barely works and no one fixed any of the bugs like missing icons, unresponsive clicking on mobs, wrong icons and it dumping  the whole sprite set when blood is on the tile

neither ghosts and mob with no combat mode can right click

**Comment by Fikou** [comment]
shift right click
