### ISSUE TITLE
[s] funny xss id console

### ISSUE THREAD

**Issue by Fhaxaris** [tgstation/tgstation#56653]
put html in modular id console custom job thing and poof

![image](https://user-images.githubusercontent.com/13771064/106931388-28e70880-66dc-11eb-88b4-2e624b08812f.png)

*sigh*

in this spot right here

![image](https://user-images.githubusercontent.com/13771064/106932115-f38eea80-66dc-11eb-954e-743472de32f0.png)

**Comment by cacogen** [comment]
feature

**Comment by optimumtact** [comment]
I am once again asking FOR PEOPLE TO SANITIZE THEIR FUCKING USER INPUTS

**Comment by TheVekter** [comment]
Fucking Christ, again?
