### ISSUE TITLE
The autolathe won't accept plastic.

### ISSUE THREAD

**Issue by dondonpow** [tgstation/tgstation#56655]
## Reproduction: try to put plastic sheets in an autolathe

**Comment by swindly** [comment]
Unable to reproduce

![Capture](https://user-images.githubusercontent.com/22402048/107978972-9be26000-6fb5-11eb-9c70-5e896df6d4d9.PNG)

**Comment by dondonpow** [comment]
It was already fixed. I just forgot to close the issue.
https://github.com/tgstation/tgstation/pull/56692
