### ISSUE TITLE
Walking into MULEbots crushed me

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#56652]
Reporting client version: 513.1539

## Round ID:
[155676](https://scrubby.melonmesa.com/round/155676)

## Testmerges:
- [Dynamic 2021](https://www.github.com/tgstation/tgstation/pull/56221)

## Reproduction:

1. Unintentionally walked into two stationary MULEbots in their bays in cargo (I assumed they were hacked, but perhaps not)
2. Got run over twice

**Comment by nightred** [comment]
I want to believe this is intended

**Comment by MrMelbert** [comment]
this might've been fixed by #56638 , since I assume the issue was swapping places with stationary mulebots, I suggest trying to replicate it now

**Comment by ArcaneDefence** [comment]
Definitely not fixed right now.

**Comment by Fmk89** [comment]
Still bugged.

**Comment by ArcaneDefence** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/57378
