### ISSUE TITLE
Chemicals reacting togething when placed seperately in a grenade casing

### ISSUE THREAD

**Issue by ViralOstrich** [tgstation/tgstation#56659]
Reporting client version: 513.1541

## Round ID:
[155686](https://scrubby.melonmesa.com/round/155686)

## Testmerges:
- [Dynamic 2021](https://www.github.com/tgstation/tgstation/pull/56221)

## Reproduction:

I made RDX and Teslium in two seperate beakers. When i place the beakers into the grenade casing it exploded in my hands.

**Comment by LemonInTheDark** [comment]
Do you have any further replication information?

**Comment by necromanceranne** [comment]
I've been noticing some weirdness with click priority as of late. Stuff like the contents of somes turfs intercepting click priority, among other things. Separate from this https://github.com/tgstation/tgstation/issues/54378, which I haven't seen in some time and was clearly a Byond bug.

Potentially, it might be related and what happened is that he poured teslium into the beaker of RDX despite the beaker being inside the grenade casing, meaning the beaker intercepted the click somehow.

**Comment by ViralOstrich** [comment]
thank you for explaining that a bit better. I just play the game lol. I understand very little of how things work so its possible I did something wrong as well


________________________________

**Comment by SuperNovaa41** [comment]
Uhhh this doesn't happen anymore
