### ISSUE TITLE
kilostation: crew monitor says dead body is in brig control, is actually in interrogation

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#56660]
Reporting client version: 513.1536

## Round ID:
[155683](https://scrubby.melonmesa.com/round/155683)

## Testmerges:
- [Dynamic 2021](https://www.github.com/tgstation/tgstation/pull/56221)
- [Tramstation: choo choo MORE MAP COMIN' THROUH](https://www.github.com/tgstation/tgstation/pull/56509)

## Reproduction:
1. see that someone is dead in brig control
2. try to find them in brig control, fail.
3. die and see they're in interrogation.

**Comment by BlueMemesauce** [comment]
Interrogation doesn't have its own room in the map. Its combined with other rooms. Its very inconsistent what room its combined with. Its different on literally every map.
Boxstation its prison.
Metastation its brig.
Kilostation its brig control.
Deltastation its in security office.
![image](https://user-images.githubusercontent.com/47338680/107137633-674b1600-68dc-11eb-9740-ad6c586bcb8c.png)
