### ISSUE TITLE
custom server won't build

### ISSUE THREAD

**Issue by Tulenich** [tgstation/tgstation#56676]
## Testmerges:

#55373 - Common Build Tooling

## Reproduction:

1. Run Build.bat
2. It works fine
3. Get this shit in cmd: 
![image](https://user-images.githubusercontent.com/77988543/107027322-02e56500-67bd-11eb-952e-e5a86b9f0132.png)
Or this shit in VSCode: 
![image](https://user-images.githubusercontent.com/77988543/107027379-1db7d980-67bd-11eb-8267-eeaf7089c3ee.png)
4. Cry because no one knows the solution

**Comment by optimumtact** [comment]
why is your system so cursed wtf

**Comment by Tulenich** [comment]
Probably because of encoding, if you remove few lines all that cursed stuff will change to sth like "Program [path] terminated with error code 1"
