### ISSUE TITLE
Can't only put gun a mouth with combat mode

### ISSUE THREAD

**Issue by CoffeeDragon16** [tgstation/tgstation#56680]
## Testmerges:
Tramstation (CHOO CHOO)

## Reproduction:

Get a gun you can jam in someone's mouth for execution. Go on combat mode, left click with mouth target. It both physically hits them with the gun, and puts the gun in their mouth. That wasn't happening before so I assume it's unintended behavior.

**Comment by nicbn** [comment]
Did you try doing it outside combat mode?

**Comment by itseasytosee** [comment]
![image](https://user-images.githubusercontent.com/55666666/108150223-f3f29280-7099-11eb-93dc-72f01cc9c7fa.png)
Intended

**Comment by CoffeeDragon16** [comment]
That's not the issue, the issue is that you BOTH put it in their mouth and slap them with the gun.

**Comment by SuperNovaa41** [comment]
Fixed
