### ISSUE TITLE
spider eggs and webbing vanishing for no reason

### ISSUE THREAD

**Issue by rellyreri** [tgstation/tgstation#56689]
Reporting client version: 513.1536

## Round ID:
[155777](https://scrubby.melonmesa.com/round/155777)

## Testmerges:
- [Tramstation: choo choo MORE MAP COMIN' THROUH](https://www.github.com/tgstation/tgstation/pull/56509)
- [Dynamic 2021](https://www.github.com/tgstation/tgstation/pull/56221)

## Reproduction:
make eggs and lots of webbing as spider. see it vanish suddenly for no reason after a few minutes
note that the spiders were completely fine and there were no breaches

**Comment by Pugie** [comment]
BZ is an invisible gas and it deletes webs and eggs... really unfun, unbalanced & overall stupid but not a bug.

**Comment by RaveRadbury** [comment]
Also temperature fluctuations can kill webs and eggs

**Comment by rellyreri** [comment]
ok ive found out that this isnt an issue, spiders just suck
hopefully someone makes a balance pr
