### ISSUE TITLE
hauntium is still broke/unobtainable

### ISSUE THREAD

**Issue by trexter555** [tgstation/tgstation#56690]
sheetifier wont accept photos with ghosts on them, autolathe wont either.

**Comment by trexter555** [comment]
also cant actually make anything with the sheets other than toolboxes when put in an autolathe

**Comment by RandomGamer123** [comment]
Autolathe accepts hauntium now, but not the sheetifier, and the autolathe still has the issue of only being able to make toolboxes.
![ThingAN898](https://user-images.githubusercontent.com/31096837/115129354-1843f000-9fb3-11eb-8d26-6a0dd7f4ddcd.png)
