### ISSUE TITLE
[BUG] Icebox has unintended interactions with Medieval Simulation Shuttle

### ISSUE THREAD

**Issue by Yawet330** [tgstation/tgstation#56695]
## Reproduction:
>spawn in as knight as a ghost
>walk over to a chasm
>its icebox
>fall down
![image](https://user-images.githubusercontent.com/65188584/107110437-a5dec300-683f-11eb-9076-34239c204c24.png)

**Comment by ATH1909** [comment]
FREEDOOOOOOOOOOOOM

**Comment by Yawet330** [comment]
> FREEDOOOOOOOOOOOOM

They cant teleport all of us, friend

**Comment by Yawet330** [comment]
This also works whenever the shuttle is first bought, as the CTF spawn beacons dont actually check if its docked with the station yet. Gamer.
