### ISSUE TITLE
Liquid Plasma makes you invisible.

### ISSUE THREAD

**Issue by CRITAWAKETS** [tgstation/tgstation#56691]
## Reproduction:
How to **Invisible**

Step 1: Find some plasma lava.
![finding the plasma](https://i.imgur.com/rY8qwWW.png)
Step 2: Step in the plasma lava for some odd reason.
![stepping in plasma](https://i.imgur.com/Fn9Ov1F.png)
Step 3: Step out of the lava and live somehow. 
Step 4: Become THE INVISIBLE MAN
![the last image your brain sees before you die, is this god???](https://i.imgur.com/20YkVWw.png)

Step 5: Realize this sucks because the only way you can heal is surgery or aheals.

**Comment by trexter555** [comment]
liquid plasma turns you limb by limb into a plasmaman so probably something with the icons something

**Comment by ATH1909** [comment]
how long did you stay in the lava for?

were you a plasmaman after emerging?

**Comment by CRITAWAKETS** [comment]
> how long did you stay in the lava for?
> 
> were you a plasmaman after emerging?

About a few seconds.

I didnt check if i was a plasmaman for the full transformation, partial transformation i wasnt a plasmaman.
