### ISSUE TITLE
You can hold yourself up (this results in a lot of runtimes)

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#56709]
### Reproduction

Step 1
Right click yourself with a gun

Step 2
![BptVE1JIEAAA3dT](https://user-images.githubusercontent.com/40847847/107124983-0979f680-68fb-11eb-8f10-fbdcd98c9637.jpg)

**Comment by necromanceranne** [comment]
Real talk this ends up doing some nasty shit and doesnt even seem to acknowledge the fact you dropped your gun. It never seems to properly clear and even pursists when the shooter holds someone else up.

You can have a multiperson holdup situation since the component both never checks for who the target is, whether they're holding someone up or potentially if they are held up already. The component may have been broken long before even combat mode, since I think I've done this in the past.

It likely hasn't been noticed because it has no real practical purpose up until recently, mostly because it isnt exactly easy to pull off under normal circumetances. where as now it is the default functionality for right clicking with a gun and the malfunctioning component is likely to start causing more issues.

@Ryll-Ryll since you likely would want to see.

**Comment by TheBonded** [comment]
fix the runtimes keep as feature
