### ISSUE TITLE
Shots pass over robots unless you click directly on them

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#56734]
Local testing. 

## Reproduction:
1. Shoot behind Beepsky or Scrubs with lasers. 

**Result:**
Shots pass over without hitting the robot, unless you click directly on it. Combat mode doesn't matter. 

**Expected result:**
Shots should hit robots. Needing to click small moving targets directly doesn't seem intended but let me know if I'm wrong. Can't find any PR with a change like that. 

![210207 1326 28](https://user-images.githubusercontent.com/46400996/107146377-1ffa6f00-6948-11eb-85ed-7c9200c381a8.png)

**Comment by necromanceranne** [comment]
This has actually always been the case, because bots have no density. This allows them to pass one another on their path, as well as allow you to walk over them.

This also means they can't be shot unless you directly click on them. You can check this by comparing ED-209's with other mobs, which are a subtype of beepsky.

**Comment by Angustmeta** [comment]
No, this has not always been the case. When breaking into armory you didn't need to click directly on the securitron rushing towards you.

**Comment by cacogen** [comment]
Unless it was changed and then changed back at some point that I'm not aware of (which I doubt) this has always been the case

**Comment by Angustmeta** [comment]
![2020-05-29](https://user-images.githubusercontent.com/46400996/107155469-e130dd00-6978-11eb-9e7f-8654a756925a.gif)

**Comment by trexter555** [comment]
> ![2020-05-29](https://user-images.githubusercontent.com/46400996/107155469-e130dd00-6978-11eb-9e7f-8654a756925a.gif)
> I know there has been a few "shots not passing over" and "shots passing over" bugs 2020 but I felt the need to post this to prove I'm not crazy. From May 2020.

i think beepsky was killed in that because the reflected lasers hit him

**Comment by Angustmeta** [comment]
![210208 Version from 2020-07 Definite PROOF](https://user-images.githubusercontent.com/46400996/107193755-78387c00-69ef-11eb-9000-2f3c76b33b5f.gif)

July 2020 version.

**Comment by necromanceranne** [comment]
Huh, alright, there is something wrong going on then.

**Comment by Angustmeta** [comment]
#55495 Did this on purpose it seems.

**Comment by cacogen** [comment]
I see, they were absorbing bullets meant for other targets and presumably becoming aggro against friendly laser security
