### ISSUE TITLE
Gamer Cloak failed to spawn

### ISSUE THREAD

**Issue by Megamaw** [tgstation/tgstation#56731]
Reporting client version: 513.1536

## Round ID:
[155860](https://scrubby.melonmesa.com/round/155860)

## Testmerges:
- [Tramstation: choo choo MORE MAP COMIN' THROUH](https://www.github.com/tgstation/tgstation/pull/56509)

## Reproduction:

Uh. Last round, I achieved 'legendary gamer status', and hit the button on my PDA. Apparently I was supposed to get a drop pod with a cloak. I didn't.

An admin had to manually spawn one for me. They were confused, but apparently one never spawned. Despite this, I was told immediately after pressing the button I was going to receive something.

I'm. . . really not sure what caused this? Sorry, wish I had more repro info. Feel free to ask me any questions.

**Comment by necromanceranne** [comment]
Can I get an F for our veterans?

**Comment by JohnFulpWillard** [comment]
I don't think this is a problem anymore? I don't know what might've caused it, but if it happens again then we can re-open this.
Since this issue was opened, getting the cloak was moved from the PDA to the Tablet, so I don't think we can reproduce this anyways.
