### ISSUE TITLE
Blob Spores don't rally

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#56742]
## Reproduction:
Be blob
Spawn spores
Middle-click
"Your spores are rallied!"
Spores don't move

**Comment by TemporalOroboros** [comment]
I'm reasonably sure this is because someone broke pathing for blob spores.

**Comment by dragomagol** [comment]
Related to #56051

**Comment by Arkatos1** [comment]
Rally ability does actually work, problem is that spores wont plan path through blob tiles, which in practice means they dont get much anywhere.

Caused by #55495, the very first line. There was even a comment about it that this exact thing will happen.

**Comment by TheMidnightRose** [comment]
Has this been looked into at all? It is still an issue as blob spores are still unable to pass blob tiles, but do respond to all other rally requests so long as a blob tile does not block them.
