### ISSUE TITLE
Overlays are bugged

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#56765]
Reporting client version: 513.1539

## Round ID:
[155975](https://scrubby.melonmesa.com/round/155975)

## Testmerges:
- [update_appearance](https://www.github.com/tgstation/tgstation/pull/55468)

## Reproduction:
![dreamseeker_ya7CbGMmu5](https://user-images.githubusercontent.com/37246588/107285653-7a213000-6a2d-11eb-821d-7a3cadc37773.png)
from roundstart, nothing in those rechargers

**Comment by TemporalOroboros** [comment]
Fixed

**Comment by wesoda25** [comment]
Looks like it
