### ISSUE TITLE
Combat Mode Pushing Oddities

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#56764]
Combat Mode has a number of oddities with pushing people around; behavior is not 100% consistent with before. @Qustinnus 

- A mob NOT in combat mode can mob-swap past a person that IS in combat mode
- If the person pulling the dense object is IN combat mode and the person not pulling is NOT in combat mode, it results in this very strange behavior:
https://i.gyazo.com/dca3cefad8a66f316e57448f19208fbb.mp4

## Reproduction:

Spawn in two mobs, adjust their combat modes, and try various pushing/pulling circumstanes involving other mobs/dense objects or by thesmelves.

**Comment by Qustinnus** [comment]
I thought I fixed the first, I'll investigate both.

**Comment by Qustinnus** [comment]
can't repro and pretty sure this was fixed already so I'm just closing it.
