### ISSUE TITLE
Energy katanas can only dash one tile at a time, still has the now unused dash action

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#56795]
Reporting client version: 513.1537

## Round ID:
[156038](https://scrubby.melonmesa.com/round/156038)

## Testmerges:
- [Upgrade marked to 2.0.0, along with the other deps](https://www.github.com/tgstation/tgstation/pull/56767)

## Reproduction:
Katana now works on right click, right clicking more than one tile away fails. It only dashes if you choose a tile right next to you. The button that would normally activate or deactivate the katana still exists, but is unused as it is now always on.

**Comment by Jared-Fogle** [comment]
> The button that would normally activate or deactivate the katana still exists, but is unused as it is now always on.

That button actually just made you dash. 

I'll look into this though, I have a feeling I know what this is.
