### ISSUE TITLE
RPEDs are broken, BRPEDs are effectively broken

### ISSUE THREAD

**Issue by Cavoglave** [tgstation/tgstation#56791]
Reporting client version: 513.1542

## Round ID:
[156038](https://scrubby.melonmesa.com/round/156038)

## Testmerges:
- [Upgrade marked to 2.0.0, along with the other deps](https://www.github.com/tgstation/tgstation/pull/56767)

## Reproduction:

If you print an RPED or BRPED as usual from a techfab or protolathe, it will not pick up items from the floor. They can only manually be loaded by clicking on them with a single part in hand at a time.
In addition, attacking a finished machine with an RPED will not give you a part readout, and attacking a screwed machine with a loaded RPED will not upgrade its parts.

The BRPED, on the contrary, will successfully poll and upgrade machines. However, it inherits its inability to mass collect parts from the floor from the RPED.

**Comment by steampunch** [comment]
Not only RPEDs, but also pickup bags in general. I'm guessing just about anything that clicks to pick up a ton of stuff is affected.
