### ISSUE TITLE
Chemical Plumbing, Reagent Tanks, and Medipen Refiller

### ISSUE THREAD

**Issue by BongoDongo2000** [tgstation/tgstation#56802]
Was giving Plumbing a try and ran into a couple issues with it.

1. Reagent Tanks. So, if you add a sheet of metal to a water tank it becomes a reagent tank. These can be hooked up to a plumbing system.  However, there is nothing on them in the wiki and I could not get one to fill up with chemicals. I had a setup with a reaction chamber outputting Space Lube. The output went to a Reagent tank, wrenched down, completely surrounded by duct to ensure it was hooked up. The tank was completely emptied out first. It would not fill. I put a Chemical Press down in the same spot and it correctly began to manufacture Space Lube.

2. [Medipen Refiller Wiki page](https://tgstation13.org/wiki/Machines#Medipen_Refiller). 
![image](https://user-images.githubusercontent.com/78820256/107451801-e6b73000-6afc-11eb-83b1-6d5df275928e.png)
Same as above, had a setup, put the Medipen Refiller on it. Now as you can see in the picture, the Medipen Refiller DID fill up with the chemicals from the Chemical Press. However, trying to refill a used epinephrine medipen with it gave the above message. I couldn't find in the tech tree any research to make empty ones, nor was there an option in the medical fab or the auto lathe to make one. Nothing in the wiki either that I could find.

**Comment by TheBonded** [comment]
Having plumbing around the tank means it takes in chemicals, but outputs them immediately back into the loop

**Comment by BongoDongo2000** [comment]
I tried it both with it around and not around. The reagent tank only has one input, it does not have an output if that makes sense. There was also no where for it to empty out to.

**Comment by Pugie** [comment]
You can only refill medipens with their specific chem list that they start with. Epipen medipens are really snowflake and start with about 3 different reagents and some aren't able to be made.

**Comment by BongoDongo2000** [comment]
See theres god damm nothing that says anything about that in the wiki. If thats the case, then hooking up a medipen dispenser to plumbing serves no purpose
