### ISSUE TITLE
Plasmaman helmet light not lighting up

### ISSUE THREAD

**Issue by SamDDBS** [tgstation/tgstation#56806]
## Round ID:
[156054](https://scrubby.melonmesa.com/round/156054)

## Reproduction:
plasmaman helmet light would not show light, despite being on and the light var being on

**Comment by rdragan** [comment]
Could not repro this on either local, nor live.

**Comment by SamDDBS** [comment]
> Could you give more details on what you did during the round before trying to use the flashlight? What job were you?
I was a station engineer space walking with a an eva suit on (the one you find in the emergency eva storage)
> Did your suit take damage from any sources?
My helmet hadnt taken any damage, neither had my suit

**Comment by SamDDBS** [comment]
its been fixed or was a one time thing
