### ISSUE TITLE
Mining resonators didn't do anything

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#56801]
Reporting client version: 513.1539

## Round ID:
[156050](https://scrubby.melonmesa.com/round/156050)

## Testmerges:
- [update_appearance](https://www.github.com/tgstation/tgstation/pull/55468)

## Reproduction:
1. Tried left-clicking and right-clicking with both an upgraded resonator and regular resonator (found on floor in Free Golem Ship) with combat mode both on and off on both rock and the ship's floor
2. Nothing

**Comment by SuperNovaa41** [comment]
Doesn't seem to be an issue anymore.
