### ISSUE TITLE
"Show server last round" verb hasn't ever showed up as a usable verb (either in the OOC tab or via command bar)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#56805]
![image](https://user-images.githubusercontent.com/51863163/107459629-38bb7e00-6b1c-11eb-8f14-142755fc8826.png)

## Reproduction:

"Show server's last round", added by https://github.com/tgstation/tgstation/pull/55646 , has literally never shown up to me in OOC tab a single time in the month it has been merged. It's in the code, the verb still exists, but you can't ever use it on live.

**Comment by rdragan** [comment]
Can't even invoke this directly through the command bar:
![image](https://user-images.githubusercontent.com/43266738/107493361-2f6ef780-6b96-11eb-832f-080647803352.png)

**Comment by wesoda25** [comment]
@MrDoomBringer

**Comment by MrDoomBringer** [comment]
oh god what the fuck
