### ISSUE TITLE
Sprite Issues

### ISSUE THREAD

**Issue by Ainulan** [tgstation/tgstation#56809]
Reporting client version: 513.1541

## Round ID:
[156058](https://scrubby.melonmesa.com/round/156058)

## Testmerges:
- [update_appearance](https://www.github.com/tgstation/tgstation/pull/55468)

## Reproduction:

Hello! Just to list sprites that I have noticed that have been odd-ball like after the latest merge:

The Tablets for Syndicate operatives is invisible upon spawning in while in pocket, when thrown on the ground only the screen is visible.

The sprite of Alien face huggers is has the default purple/black square texture most notably on monkies.

**Comment by Ainulan** [comment]
In addition to these is also the Detectives holster, with the same Purple and black square texture as is present with the aformention facehugger issue.

**Comment by necromanceranne** [comment]
@TemporalOroboros I last touched facehuggers but when I did it seemed to be working as intended. So I don't know if this is on me or your testmerge.

**Comment by TemporalOroboros** [comment]
Thanks! I should be able to get working on these soon.

**Comment by TemporalOroboros** [comment]
I was unable to reproduce the facehugger or detectives holster issues.

**Comment by Time-Green** [comment]
Seems to have been fixed, can't reproduce
