### ISSUE TITLE
Ambience in lobby

### ISSUE THREAD

**Issue by Colovorat** [tgstation/tgstation#56815]
Reporting client version: 513.1536

## Round ID:
[156070](https://scrubby.melonmesa.com/round/156070)

## Testmerges:
- [space is more realistic, exchangers unchanged](https://www.github.com/tgstation/tgstation/pull/56571)

## Reproduction:

Ambience being played even in lobby, and i'm not even joined the game

**Comment by Jared-Fogle** [comment]
@Qustinnus

**Comment by SuperNovaa41** [comment]
Like 99% sure this is no longer an issue
