### ISSUE TITLE
Wrapping crates and lockers make you pull them faster

### ISSUE THREAD

**Issue by TheBonded** [tgstation/tgstation#56828]
## Round ID: 
N/A
Has been happening for a long time

## Testmerges:
N/A

## Reproduction:
1. Get locker
2. Put things you want to transport in locker
3. Close locker and start pulling
4. Be annoyed by the slow moving speed while pulling the locker
5. Go to cargo and grab wrapping paper
6. Wrap the locker
7. Pull the locker at normal movement speeds

Honestly this isn't huge, a good fix would be to remove the slowdown on pulling normal lockers, or make it scale with what's inside it.

**Comment by RaveRadbury** [comment]
I wonder if this is decent? You still have to unwrap the crates and lockers, you also have to keep a tube of packaging paper on you.

**Comment by ATH1909** [comment]
feature

**Comment by ATH1909** [comment]
remember, you can still drag around crates and stuff at full speed, even without wrapping paper

**Comment by TheBonded** [comment]
> I wonder if this is decent? You still have to unwrap the crates and lockers, you also have to keep a tube of packaging paper on you.

It is a really useful thing, but it doesn't make all that much sense. A locker with 50 metric tonnes of gold shouldn't be able to be pulled like it's weightless just because you wrapped it up using the small item taking up almost no space backpack.

**Comment by Tlaltecuhtli** [comment]
the paper works a lubricant , like railroads etc
