### ISSUE TITLE
1 click Martial Arts combo

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#56826]
## Reproduction:
 It was 1 rightclick non combat mode on the target that I probably hit a 5+ minutes ago. Worst possible timing (lets not talk about antag check).
 https://www.youtube.com/watch?v=kG9P7000BWA
 @Qustinnus

**Comment by Qustinnus** [comment]
your url doesn't work for me for some reason but I think this has to do with the martial arts changes, not with my code.

@jacklecroy

**Comment by Qustinnus** [comment]
I'll look into it as well though because i'm not 100% certain

**Comment by Livrah** [comment]
> your url doesn't work for me for some reason but I think this has to do with the martial arts changes, not with my code.

try it now

**Comment by Qustinnus** [comment]
hmm yeah i see, I'm not sure what that is, I think its the martial arts stuff.

**Comment by necromanceranne** [comment]
Looks like it might be because someone ELSE shoved them? But that's a bit weird since combos are tracked on the martial artist and not the target.

You didn't hug that guy beforehand did you?

**Comment by necromanceranne** [comment]
I've not been able to recreate this on just my own, but I've noticed that I wasn't getting any of the attack text whenever I used one of the combos.  Entirely separate issue I guess.

**Comment by Livrah** [comment]
> You didn't hug that guy beforehand did you?
Doublechecked, only pointed on target in last minute

**Comment by ATH1909** [comment]
> > You didn't hug that guy beforehand did you?
> 
> Doublechecked, only pointed on target in last minute

yo, if that means what I think it means...

**Comment by rdragan** [comment]
According to logs, you punched them 5 minutes before this:
![image](https://user-images.githubusercontent.com/43266738/107584145-ae027e00-6c04-11eb-8e7d-db2fdc924efc.png)

https://scrubby-dev-sql.melonmesa.com/round/156094/files?file=attack.txt&file=game.txt
query: "livrah.+goodoldtimes|shove me"

**Comment by necromanceranne** [comment]
Ah yeah so there isn't a timer on that at all. I'll remark this as more of a consistency issue. 

That said, the dude who came after him copy pasted the kick message like 5 times lol.

**Comment by rdragan** [comment]
Maybe there should be a way to voluntarily disable martial arts...

**Comment by jacklecroy** [comment]
The combo meter goes away after two seconds, but your combo may last longer depending on the martial art.
