### ISSUE TITLE
Build tool sometimes doesn't compile DM code if changes are small

### ISSUE THREAD

**Issue by TBleader** [tgstation/tgstation#56821]
Sometimes when I have been making relatively small changes to the code, the build script does not properly run. It will just claim that the dm is up to date. This happens often when the changes I am making are pretty small, few lines or less. If I change enough, or add a new file, or something then it'll start working. Also deleting the dmb file will force it to compile since the dmb file doesn't exist anymore.

## Reproduction:
Make small code changes (<5 lines edited, single value change etc)
Run the build script (either CMD/PS or using the vs code shortcut)
Scratch your head when it says "Skipping 'dm' (up to date)" even though you just changed something

**Comment by stylemistake** [comment]
Which files in particular?

**Comment by TBleader** [comment]
I've mostly been working on code in my fork's code folder as I am trying to not touch the upstream code as much as possible, but it does also happen if I slightly edit code files in the normal code folders too.

**Comment by stylemistake** [comment]
**Which files**? I need details.

**Comment by TBleader** [comment]
Yes, it was outside of `/code`. I was not aware you had to add the folder as a dependency as it seemed to compile code most of the time provided the changes made were "significant" enough, it never completely ignored the folder. It generally worked except for when making minor changes. Guess that is my ignorance on the build process requirements. After adding it to that file, it will reliably recompile no matter the change for any code file (even in `/code`)

Closing issue because it's not a real bug I'm just dumb. Thanks for your help with this.
