### ISSUE TITLE
Plantbag click plants to pick up broke

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#56824]
## Testmerges:
BYOND Version: 513.1536
Server revision compiled on: 
Master commit: e3f80621bd3a61c2fb626975b8b6efffebc1c6ea
The following pull requests are currently test merged:
#56571: 'space is more realistic, exchangers unchanged' by Sparkezel at commit cdf456051b
#56797: 'Simplified Node Bootstrap mk. II' by stylemistake at commit 514cf0b48f

Local commit: e5d1eac44790151008f75a2f7790032de0f51eac
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
Enforce Continuous Rounds: 10 of 21 roundtypes
Allow Midround Antagonists: 5 of 21 roundtypes
Game Mode Odds for current round:
traitorbro 7.3%
traitorchan 7.3%
traitor 21.8%
nuclear 7.3%
cult 7.3%
dynamic 21.8%
extended 1.8%
secret_extended 3.6%
revolution 10.9%
wizard 10.9%
All Game Mode Odds:
traitorbro 7.3%
traitorchan 7.3%
traitor 21.8%
nuclear 7.3%
cult 7.3%
dynamic 21.8%
extended 1.8%
secret_extended 3.6%
revolution 10.9%
wizard 10.9%

## Reproduction:

Get plantbag. Click plant on ground with plantbag. Suffer becaause it doesnt work

**Comment by Sparkezel** [comment]
https://github.com/tgstation/tgstation/pull/56798
