### ISSUE TITLE
Nanite defib doesn't work under some circumstances

### ISSUE THREAD

**Issue by TheBonded** [tgstation/tgstation#56831]
## Round ID:
N/A
Was on a tg branch server, branched about september 2020

## Testmerges:
N/A

## Reproduction:
0. Start as moff (might not be required)
1. Get a necrotic metabolism + self respiration + mind restoration virus
2. Get muscled veins + grounded nerves
3. Get fullaugged
4. Get nanites (mechanical repair, blood purification on a >1 toxin rule, both with >10% nanite amount rule + death sensor that activates a health sensor that activates defib when health is >0% (99 damage total))
5. Get advanced cybernetic organs, welding eyes, anti drop implant, cns rebooter inplant, nutrient implant plus
6. Die
7. Have your nanites try to revive you, move your ghost into your body, then make the fail noise
8. Have the paramedic onsite defib you just fine with a backpack defib

Tested this with the nanites defibbing at >-50% health and it still didn't defib me, but I could be defibbed by the backpack version fine

After being defibbed the third time I tested after changing the health sensor, the mechanical repair part of the nanites stopped working, even though I was at 500/500 nanites, and I when I removed everything in the nanites and reinserted the mechanical repair it still refused to heal me.

**Comment by CRITAWAKETS** [comment]
were your nanites actually still working, like on the proper cloud instead of cloud 0.

**Comment by TheBonded** [comment]
> were your nanites actually still working, like on the proper cloud instead of cloud 0.

they were on cloud 41

**Comment by Mothblocks** [comment]
can you actually reproduce this on the latest tg?
