### ISSUE TITLE
Bounty cubes supposedly pay out 50x now

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#56842]
![Discord 2021-02-11 17-43-09.png](https://i.imgur.com/nh6nOkJ.png)
![Discord 2021-02-11 17-42-55.png](https://i.imgur.com/mq2sF9l.png)
![Discord 2021-02-11 17-42-13.png](https://i.imgur.com/o20FBlK.png)

Maybe I'm missing something obvious but looking back over the code and retesting it I haven't been able to reproduce this, so I thought I'd make an issue report in case someone else knows.

## Round ID:
@Timberpoes 

## Testmerges:
Unsure

## Reproduction:
Unsure

**Comment by Tlaltecuhtli** [comment]
are there round logs or anything? didnt see this happening

**Comment by cacogen** [comment]
Dunno and @Timberpoes hasn't responded. Starting to think they made it up.

**Comment by cacogen** [comment]
So I was wrong, he wasn't making it up.

I was playing today, sold 200 sheets of plasma and inadvertently got 320,000 cr. Turns out the problem wasn't the bounty cubes, but the barcodes. 

We sold all the minerals in the ore silo just as the shuttle was docking and even bought 20 syndicate briefcases but we still couldn't afford the bicycle at 1,000,000 cr.
