### ISSUE TITLE
Right click menu can't be used to pick things up

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#56875]
Reporting client version: 513.1533

## Round ID:
[156200](https://scrubby.melonmesa.com/round/156200)

## Reproduction:
Reported by a player, reproduced.
Shift + right click to look at the items on a tile. Click "pick up." Fail to pick anything up.

**Comment by rdragan** [comment]
#56848 ?

**Comment by dragomagol** [comment]
Augh duplicate
