### ISSUE TITLE
scope zoom doesn't check that gun is in hand

### ISSUE THREAD

**Issue by bloons3** [tgstation/tgstation#56898]
https://github.com/tgstation/tgstation/blob/42ef7decf8e0b7843dfced0eac753ba47add6a4d/code/modules/projectiles/gun.dm#L671

![image](https://user-images.githubusercontent.com/3241376/107845206-7ed44400-6d9f-11eb-93f2-3f9b6b480c5b.png)

**Comment by ATH1909** [comment]
uh, that doesn't look like it's from /tg/station.

**Comment by TheBonded** [comment]
> uh, that doesn't look like it's from /tg/station.

Pretty sure @bloons3 is a beestation admin (don't quote me on that) so maybe they meant to put this in their github?

**Comment by bloons3** [comment]
repro on TG
![image](https://user-images.githubusercontent.com/3241376/108129316-a400d500-7073-11eb-93d6-7aa1f3351898.png)

Also caused something weird when I ghosted out of the body while zoomed in I couldn't see my ghost.

**Comment by bloons3** [comment]
ghost became invisible when I ghosted out of the body while scoped/zoomed in 
![image](https://user-images.githubusercontent.com/3241376/108129430-cf83bf80-7073-11eb-9061-124808312952.png)

**Comment by bloons3** [comment]
@ATH1909 repro'ed on TG Sybil
