### ISSUE TITLE
Papers on a notice board cannot be read/written on until removed

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#56929]
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
Have a `/obj/structure/noticeboard`. 
Have a paper.
Put paper on board.
Open board's UI.
Click paper's title.
Get examine text in the chat box, but the paper's popup doesn't come up so you can't actually read it.
Get frustrated, rip off the paper, throw it on the floor next to you and examine it again.
The paper's popup works fine. 
Put paper back on notice board.
Try to write with your hand, forgetting your pen.
Get told you'll need something to write with.
Take out your pen and stare at the board in confusion as you mash the write button with no results

**Comment by maxymax13** [comment]
same thing with clipboards, which is amazing because they spawn basically everywhere. has nobody ever tried actually using them?

**Comment by mozi-h** [comment]
A simple UI update won't cut it, I'm afraid. We / I could make it fancy TGUI similar to folders, but the overall issue with notice boards is, that they're completely useless as a concept.
If you want others to notice something, you'll want to pin it onto airlocks as they are more looked at, and you can easily see the attached item.
Notice boards would need some new functionality to make them worthwhile. Maybe a global notice board, so you'll pin an item onto all boards on the station at once? Perhaps a better visual indicator?
