### ISSUE TITLE
Plants no longer respect can_synth (OH GOD, OH FUCK, BOTANY ADMINORDRAZINE)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#56935]
## Round ID:

[156399](https://scrubby.melonmesa.com/round/156399)

## Testmerges:
![image](https://user-images.githubusercontent.com/51863163/107914454-15cc0800-6f28-11eb-836c-d6e1f4dc3b42.png)

**Comment by spessbro** [comment]
oh shid oh fug
