### ISSUE TITLE
Engineering SM emitters won't work ever again once apc is down, even after the recharge of APC

### ISSUE THREAD

**Issue by AndroidMK2** [tgstation/tgstation#56938]
## Round ID: 

Round ID: [156418](https://scrubby.melonmesa.com/round/156418)

## Reproduction:

The bug consits of the engineering emitters not working at all even with the APC fully charged with all the power channels on. Emitters will work just fine unless the apc runs out of power on it's own, then like they normally should the emitters won't be powered, however even when the apc is repowered and emitters should recieve electricty they will forever remain in their
"no power" mode. Moving or turning on and off does not fix the problem. The bug happend on metastation, don't know if it appears on other stations but most likely too. The emitters were not interfered by the admins in any way.

**Comment by TemporalOroboros** [comment]
Emitters don't draw power from the local APC, they are purely powered off of whatever wire they are attached to.

**Comment by Paxilmaniac** [comment]
> Emitters don't draw power from the local APC, they are purely powered off of whatever wire they are attached to.

What they said, emitters have literally nothing to do with the apc

**Comment by LemonInTheDark** [comment]
I'm glad you bothered to report it, better wrong then an issue go unnoted, but this is the intended behavior isn't it?

**Comment by ArcaneDefence** [comment]
Use a pacman generator or jumpstart the SM by having it dust things/shooting it with an energy gun to get power on the wire network that the emitters are on, or hotwire the engine to the station powergrid and use power from solars.

Emitters do not operate off APC power. Reduce the number of emitters on the powernet if there's not enough energy available to fire them simultaneously, and consider possibly upgrading them to reduce their power need more going forward.
