### ISSUE TITLE
Can't put pet collars on monkeys any more

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#56952]
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
Get a collar
Get a monkey
try to pineapple pen that shit
Doesn't work. Thanks, now-officially-human monkeys

Weep as you may never put pun pun's collar on now.

**Comment by ShizCalev** [comment]
@Qustinnus

**Comment by Qustinnus** [comment]
feature
