### ISSUE TITLE
if i wasnt lied to, fermichem now allows every syringe to be a cryo syringe

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#56965]
## Reproduction:
1. fermichem stops all reactions below 100k (or so im told)
2. fill syringe with two chems that would normally react and explode, but don’t because step one
3. load into syringe gun and find victims 
4. 

![](https://cdn.discordapp.com/attachments/624008915582976013/811226759348748349/image0.png)

**Comment by cacogen** [comment]
What happens to the temperature of the reagents on injection?

**Comment by Paxilmaniac** [comment]
> What happens to the temperature of the reagents on injection?

don’t quote me on this but i believe chems slowly equalise with body temp

**Comment by itseasytosee** [comment]
I've seen this in action, some cultist wiped out like half the station with his makeshift insta-kill rifle

**Comment by necromanceranne** [comment]
@Thalpy might wanna address this.

**Comment by Thalpy** [comment]
Ah, panic. I'm on the case!
