### ISSUE TITLE
Light eater does not consoome lights

### ISSUE THREAD

**Issue by Colovorat** [tgstation/tgstation#56967]
## Reproduction:

Got turned into nightmare, light eater was not destroying light sources.

**Comment by TemporalOroboros** [comment]
@Colovorat Are you saying that the light eater wasn't destroying the lights or that it wasn't even turning them off? One of these is a much larger issue than the other.

**Comment by davethwave** [comment]
likely due to the combat PR

**Comment by Colovorat** [comment]
@TemporalOroboros i got attacked by a man with flashlights, hitted him, he was still with lights. There was flashlight laying on the ground, i tried to attack it, and nothing happened

**Comment by TemporalOroboros** [comment]
I have not been able to replicate this on a local. Please tell me if you manage to do so.

**Comment by rdragan** [comment]
@TemporalOroboros It doesn't seem to be eating lights that are carried by mobs:


https://user-images.githubusercontent.com/43266738/108501810-83768c00-72ba-11eb-8db1-b0a918aba301.mp4

**Comment by Taylorkills2** [comment]
In addition, if you smash a powered light bulb as Nightmare, it will continue producing light.
However it was unpowered first and in emergency lighting/red and you smash it, then you can destroy the light.
