### ISSUE TITLE
you can mind transfer into someone who has antimagic by targeting their holoparasite

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#56962]
https://github.com/tgstation/tgstation/blob/master/code/modules/spells/spell_types/pointed/mind_transfer.dm

```
	var/mob/living/victim = targets[1] //The target of the spell whos body will be transferred to.
	var/datum/mind/VM = victim.mind
	if(victim.anti_magic_check(TRUE, FALSE) || VM.has_antag_datum(/datum/antagonist/wizard) || VM.has_antag_datum(/datum/antagonist/cult) || VM.has_antag_datum(/datum/antagonist/changeling) || VM.has_antag_datum(/datum/antagonist/rev) || victim.key[1] == "@")
		if(!silent)
			to_chat(user, "<span class='warning'>[victim.p_their(TRUE)] mind is resisting your spell!</span>")
		return FALSE
	if(istype(victim, /mob/living/simple_animal/hostile/guardian))
		var/mob/living/simple_animal/hostile/guardian/stand = victim
		if(stand.summoner)
			victim = stand.summoner
```

this is due to the positionings of these checks.

this also lets you mind transfer into changelings, cultists, revs, other wizards, megafauna, mindless creatures (this gets around the can_target() check of the spell too), and other things you couldn't normally target (aside from demons, things that aren't creatures, and yourself)... if they somehow have a holoparasite.

**Comment by ATH1909** [comment]
also, why did we make wizards, cultists, and revs immune to mind transfer again? IIRC, changeling code is pretty fucky, which is probably why they're excluded, but this can serve as an antag check for the cultists and revs, and I don't particularly see why wizards (or cultists or revs, for that matter) should be immune (unless it's to stop apprentice shenanigans?).

**Comment by ArcaneDefence** [comment]
> 
> 
> but this can serve as an antag check

Where the fuck are you going to get a wizard with a specific spell to check for revs/cultists instead of using mind shields/holy water?

**Comment by ATH1909** [comment]
> > but this can serve as an antag check
> 
> Where the fuck are you going to get a wizard with a specific spell to check for revs/cultists instead of using mind shields/holy water?

a friendly wizard during dynamic

**Comment by ShibaInuLord** [comment]
> 
> 
> > > but this can serve as an antag check
> > 
> > 
> > Where the fuck are you going to get a wizard with a specific spell to check for revs/cultists instead of using mind shields/holy water?
> 
> a friendly wizard during dynamic
> 
> one of the optional challenges for wizards that tralezab is going to add creates a friendly wizard to oppose you and defend the station, so friendly wizards might become more common in the near future

if i remember that page is just fluff
