### ISSUE TITLE
Cigarette box turned invisible when reclosed

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#56963]
Reporting client version: 513.1539

## Round ID:
[156485](https://scrubby.melonmesa.com/round/156485)

## Testmerges:
- [update_appearance](https://www.github.com/tgstation/tgstation/pull/55468)

## Reproduction:

1. Use cigarette carton in hand
2. Turns invisible

**Comment by ArcaneDefence** [comment]
Couldn't reproduce, could you provide any more details?

**Comment by cacogen** [comment]
Was probably fixed

**Comment by Twaticus** [comment]
tested on live, fixed
