### ISSUE TITLE
Going through a hand tele portal to a location that you slip on leaves items in hand at the original portal

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#56976]
## Round ID:
[156510](https://scrubby.melonmesa.com/round/156510)

## Testmerges:
None

## Reproduction:
Set a teleporter to a beacon
Flood the area around the beacon with cold water vapor so it all ices over
Use a hand tele to make a portal to that beacon
Keep the hand tele in your hand as you go through it
You end up at the frozen destination, hand tele is on the floor on top of the portal you went through.

Get cucked because you can't bring anything in hand through the portal

**Comment by Dorsisdwarf** [comment]
Is it actually being left behind or is it going back thru the portal

**Comment by ArcaneDefence** [comment]
I didn't code dive to figure out the exact series of occurrences, as it all happens at once on the player's perspective. 
Last I knew teleporting to a spot like that didn't even slip, but I don't think I've kept much of a record for that claim anyway.

**Comment by SuperNovaa41** [comment]
> Is it actually being left behind or is it going back thru the portal

Yeah it's almost definitely this
