### ISSUE TITLE
PKAs with mounted seclite do not produce light while turned on

### ISSUE THREAD

**Issue by SamDDBS** [tgstation/tgstation#56986]
## Round ID:
[156533](https://scrubby.melonmesa.com/round/156533)

## Reproduction:
Any Proto Kinetic Accelerators spawned by normal means (e.g spawning on map generation, spawning from vendor) that also have a seclite attached will not produce light when the mounted seclite is turned on; this applies to lavaland and the station, I am unsure if it affects other z levels.
Normal seclites still work as they should.
Image of ghost me observing a PKA with a turned on seclite not producing light during the round
![image](https://user-images.githubusercontent.com/72839318/108153635-65c5de80-7090-11eb-9ac6-44dfbd9de0b7.png)

**Comment by necromanceranne** [comment]
It seems seclites, in their entirety, are not producing lights when attached for some reason.

**Comment by rdragan** [comment]
Probably related to #55551
@TemporalOroboros

**Comment by Sparkezel** [comment]
Anything that produces light and can be attached to anything else fucks up because light seems to be created somewhere in the nullspace or is parented to the MOB not the ITEM, I have no fucking idea how light works though

**Comment by rdragan** [comment]
Fixed by #57058
