### ISSUE TITLE
the ion storm event uses see_in_dark to determine if it can affect an AI

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#56982]
![image](https://user-images.githubusercontent.com/42606352/108143332-234ed280-708d-11eb-8cc8-08c47a56b817.png)
![image](https://user-images.githubusercontent.com/42606352/108143342-28ac1d00-708d-11eb-8c20-e1fb53eda69e.png)

https://github.com/tgstation/tgstation/blob/master/code/modules/events/ion_storm.dm

why, god, why

**Comment by LemonInTheDark** [comment]
it appears to be a holdover from an admin proc that sets the ai's laws, if see_in_dark was set to 0 the code assumed the ai was depowered, and thus shouldn't be lawified.

Suffering.

https://github.com/tgstation/tgstation/blob/fd0f845868066be0427ad7115d041435808d7553/code/modules/admin/verbs/randomverbs.dm#L338
