### ISSUE TITLE
monkeys appearing as catatonic and loads of other human monkey jank

### ISSUE THREAD

**Issue by itseasytosee** [tgstation/tgstation#56985]
This is of course because monkeys are humans now.

## Reproduction:

Monkeys and humanized monkeys maintain their monkey AI all a
The solution to this seems to be to check if a human has an AI controller before classifying them as catatonic for the purposes of examination as well as a message reading "She doesn't appear to be herself."
![image](https://user-images.githubusercontent.com/55666666/108151313-08d02580-709c-11eb-9ddc-5d20e91df303.png)

Also, I discovered while testing that humans with monkey controllers will use items on people if they are picked up, such as trying to begin a surgery if you hand them some surgical drapes. This also works with syringes, EpiPens, and sutures.
![image](https://user-images.githubusercontent.com/55666666/108151546-93188980-709c-11eb-9c30-11597b276c12.png)
monkey man patching me up after I shoved him

**Comment by ATH1909** [comment]
> Also, I discovered while testing that humans with monkey controllers will use items on people if they are picked up, such as trying to begin a surgery if you hand them some surgical drapes. This also works with syringes, EpiPens, and sutures.
> ![image](https://user-images.githubusercontent.com/55666666/108151546-93188980-709c-11eb-9c30-11597b276c12.png)
> monkey man patching me up after I shoved him

yo holy shit can you give a monkey a hemostat so that he can work on tend wounds surgeries (that you'd started with a bedsheet) for you

**Comment by itseasytosee** [comment]
You can also have them feed you burgers.

**Comment by necromanceranne** [comment]
Aggressively healing you through sheer monkey spite.

**Comment by necromanceranne** [comment]
In addition to this, monkey AI does not at all respect either restraints, physical barriers, or any impairments when doing their specific monkey AI actions. The AI is seemingly riddled with a lack of checks for status or other important checks, and probably is ignoring normal click limitations or movement limitations.

This includes snatching objects through walls so long as they have proximity to their target.

**Comment by TheBonded** [comment]
> In addition to this, monkey AI does not at all respect either restraints, physical barriers, or any impairments when doing their specific monkey AI actions. The AI is seemingly riddled with a lack of checks for status or other important checks, and probably is ignoring normal click limitations or movement limitations.
> 
> This includes snatching objects through walls so long as they have proximity to their target.

Does this include sleeping monkeys snatching things?

**Comment by Time-Green** [comment]
I can't let mind-magnified monkeys do brain surgery on me, but normal monkeys can????????????? Wha ntthe is thsi shrit

**Comment by optimumtact** [comment]
switching monkeys to /human paths was just silly imo

**Comment by itseasytosee** [comment]
I can say that monkeys are in such a state now that this issue can be considered closed
