### ISSUE TITLE
Race change into abductor randomizes your name/appearance

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#57003]
## Reproduction: 
I became an abductor via Icebox Magic Pool and its randomized the character (changing into other races doesnt do that). Had a same results by hitting lavaland 'alien' corpse with Envy's Knife.

**Comment by nullAdept** [comment]
It used to randomize your everything when it changed you into other races. If it doesn't do that then that is the bug probably.

**Comment by necromanceranne** [comment]
Yeah this isn't a bug the pool is literally hitting you with the polymorph effect. It's just...not great.
