### ISSUE TITLE
Can't click Buckled to unbuckle

### ISSUE THREAD

**Issue by FreshwaterShrimp** [tgstation/tgstation#57015]
Reporting client version: 513.1542

## Round ID:
[156615](https://scrubby.melonmesa.com/round/156615)

## Reproduction:
The issue is I can't unbuckle from things by clicking the Buckled moodlet in the top right, I'm still able to use resist to get out, but I thought it was good to let you guys know.

**Comment by necromanceranne** [comment]
you can click the object you are buckled too as well.

**Comment by ATH1909** [comment]
might be related to https://github.com/tgstation/tgstation/pull/56972 ?
