### ISSUE TITLE
Double-Barrel Shotgun Alternate Skins showing error in suit storage slot

### ISSUE THREAD

**Issue by jwc1015** [tgstation/tgstation#57022]
Reporting client version: 513.1527

## Round ID:
[156645](https://scrubby.melonmesa.com/round/156645)

## Testmerges:
- [/mob/living/proc/Life(delta_time)](https://www.github.com/tgstation/tgstation/pull/55534)

## Reproduction:
If I wear the double-barrel shotgun with an alternate skin, in the exosuit/suit storage slot, it just has the error skin. This could probably be quite easily fixed, since the sprites already exist (the suit storage sprite should be same as back sprite, but it's not)

**Comment by jwc1015** [comment]
Presumably you could fix it in the same manner as the PR which fixed the BACK slots did. (Not really sure how though)

**Comment by dragomagol** [comment]
The problem with the back slot sprites was that the name in code didn't match the name of the actual sprite

**Comment by necromanceranne** [comment]
You'll need individual sprites for all the recolours

**Comment by jwc1015** [comment]
> 
> 
> You'll need individual sprites for all the recolours

Ah, sorry - what I meant is, the exosuit slot sprite for the normal double-barrel is the same as the back sprite - presumably, the sprites could simply be copied from the back sprites.
