### ISSUE TITLE
Plumbing Grinders are broken

### ISSUE THREAD

**Issue by oklews** [tgstation/tgstation#57021]
## Round ID: [156642](https://scrubby.melonmesa.com/round/156642)
[Round ID]: # 156642
## Testmerges: 
55534: '/mob/living/proc/Life(delta_time)' by TemporalOroboros at commit bac0e3e205

## Reproduction:
Place grinder, attempt to slap item into it and fail. Look at wiki and use a conveyor, still fail.

**Comment by Tlaltecuhtli** [comment]
did u set conveyor in right side

**Comment by oklews** [comment]
I did every side, and tested every angle on a local server, still broke.

If you're asking if they were pointed to the grinder, yes.

**Comment by HumanNugget** [comment]
It works very retarded 
but it works
grinder consumes items on the tile
so you have to drag and empty a bag ontop of a tile the grinder is sitting on

**Comment by Pugie** [comment]
> It works very retarded
> but it works
> grinder consumes items on the tile
> so you have to drag and empty a bag ontop of a tile the grinder is sitting on

Just. Use. A. **Conveyor.**

**Comment by Tlaltecuhtli** [comment]
or throw it

**Comment by oklews** [comment]
I haven't tried anything but pressing it directly and conveyor, but the fact the object is obstructive would seem to prevent both those from working.

**Comment by TheBonded** [comment]
Items can only move through the grinder if you make the conveyor move towards the output pipe on the grinder. In any other direction the grinder acts as a wall and doesn't let things go through. It's stupid but that's how it works. 

For example, if your grinder outputs to it's west side, you have to make the conveyors move items east into the grinder's west(left) side.

**Comment by TheBonded** [comment]
> I haven't tried anything but pressing it directly and conveyor, but the fact the object is obstructive would seem to prevent both those from working.

Obstructive from all sides except the output side

**Comment by msgerbs** [comment]
Seems like this is working as intended?
