### ISSUE TITLE
Unable to wash creampies off my body

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#57039]
## Round ID:
Round ID: [156699](https://scrubby.melonmesa.com/round/156699)

## Testmerges:

Master commit: c71f1c6993b3abc72a508e6f5be9fed5bfd2e4f4
The following pull requests are currently test merged:
#56509: 'Tramstation: choo choo MORE MAP COMIN' THROUH' by MMMiracles at commit 4bd9e58a81

## Reproduction:

1. Get creampied by handsome catgirl.
2. Click face
3. Click sink
4. You get a you clean your face message but creampie stays visible.

if I call the clean up proc on the component it cleans it up but sinks and other things no longer work
Showers still clean.

**Comment by Pugie** [comment]
God bless creampies & God bless America.

**Comment by ilikesaying** [comment]
no context~
