### ISSUE TITLE
plumbing no longer works

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#57045]
156708

machines are connected but no chem is flowing to reagent chambers

**Comment by Time-Green** [comment]
It's just reagent chambers you baby

**Comment by Thalpy** [comment]
It wasn't the recent 2.1 or 2.2 merge - I was playing before that and was having trouble.

**Comment by oklews** [comment]
> It's just reagent chambers you baby

That's like saying it's just the SM you baby, the reaction chamber is critical to plumbing

**Comment by oklews** [comment]
if it's still an issue, why is this closed?

**Comment by Time-Green** [comment]
> if it's still an issue, why is this closed?

Issues get closed when they are fixed, and it was fixed in #57050
