### ISSUE TITLE
Non-combat mech punches do no damage but seem like they do

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#57066]
## Round ID:
Local

## Testmerges:
n/a 

## Reproduction:

1. Attack a mob with a mech with nothing equipped
2. Does no damage

When you hit mobs it makes a sound and gives a message that suggests it's doing damage (which you'd logically expect it to) but doesn't actually do anything. Dents walls, too.

Good way to get killed if you don't know any better, and the game doesn't tell you. They should either do an intuitive amount of damage or not seem like they do.

**Comment by Dorsisdwarf** [comment]
mech punches probbably got broke by combat mode

**Comment by rdragan** [comment]
This only seems to affect non-combat mechs (clarke, ripley, ody, etc).
I've also tested it on a month old build with the same results, so this was not introduced by CBT mode.

@cacogen 
Are we sure their punches are supposed to do damage? What is this based on?

**Comment by necromanceranne** [comment]
oh non-combat mechs? Those are meant to have really really piddly punches. It's probably because their force is 0 now instead of like, 5 or something.

This title seems to be somewhat misleading.

**Comment by cacogen** [comment]
@rdragan 

My assumption is it was nerfed at some point but the sound and attack message weren't updated.
