### ISSUE TITLE
Directional lighting can be caught in a crate again

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#57062]
Reporting client version: 513.1538

## Round ID:
[156737](https://scrubby.melonmesa.com/round/156737)

## Testmerges:
- [Tramstation: choo choo MORE MAP COMIN' THROUH](https://www.github.com/tgstation/tgstation/pull/56509)

## Reproduction:
Casually approach crate
Turn on PDA light
Open and close crate
Light go brrrrrrrrrrrrrrrrrrrrr.....

![image](https://user-images.githubusercontent.com/51932756/108583703-b3448480-72f8-11eb-8398-e7beb6b3d4a7.png)

**Comment by LemonInTheDark** [comment]
god fucking damnit

**Comment by TemporalOroboros** [comment]
Again?
