### ISSUE TITLE
Lavaland Ruin Ungenerated Turf

### ISSUE THREAD

**Issue by jwc1015** [tgstation/tgstation#57060]
Reporting client version: 514.1547

## Round ID:
[156729](https://scrubby.melonmesa.com/round/156729)

## Testmerges:
- [Tramstation: choo choo MORE MAP COMIN' THROUH](https://www.github.com/tgstation/tgstation/pull/56509)

## Reproduction:
Surrounding the ruin containing a ripley labeled APLU "Miner" on Lavaland, there were 3 tiles of genturf visible. I will also provide an image.

![genturfbugreport](https://user-images.githubusercontent.com/64438862/108578387-71174500-72f0-11eb-8963-70aebde90648.JPG)

**Comment by LemonInTheDark** [comment]
god damn it

**Comment by Qustinnus** [comment]
this is an issue with ruins that dont correctly use the passthrough areas when they do use passthrough turfs.

**Comment by Qustinnus** [comment]
aka: mapper pls use the correct areas
