### ISSUE TITLE
Hulks can Phase Through Walls?

### ISSUE THREAD

**Issue by Taylorkills2** [tgstation/tgstation#57072]
## Reproduction:
Well Brick Carr was smashing down reinforced walls at the AI sat. About halfway through the third wall they suddenly flew through a wall to their right and continued flying through walls through the AI sat. They started taking damage once their flight began and continued until they reached crit. Should be noted damage stopped once reach crit and they stopped moving once in crit. This "flight" also took them through space.
They also had space adaptation and no disease so they weren't taking damage from space.
They also flew too fast for the AI turrents to shoot them.
Map was MetaStation.
Otherwise I have no idea.
I wish I recorded it, it was bizarre.

**Comment by Angustmeta** [comment]
That's one of the random things that can happen from having 100 genetic instability.

**Comment by ArcaneDefence** [comment]
https://github.com/tgstation/tgstation/blob/690d26004d3a6f2ae551dc93f01931915770f3d8/code/datums/status_effects/debuffs.dm#L808-L829
Yeah, that sounds about right.
