### ISSUE TITLE
dragging the laser pointer causes the game window to freeze

### ISSUE THREAD

**Issue by c420-o** [tgstation/tgstation#57082]
Reporting client version: 513.1541

## Round ID:
[156788](https://scrubby.melonmesa.com/round/156788)

## Testmerges:
- [Tramstation: choo choo MORE MAP COMIN' THROUH](https://www.github.com/tgstation/tgstation/pull/56509)

## Reproduction:
activate the laser pointer, then dragged it on the ground. chat worked fine, but game window was completely frozen. opening and closing the server fixed it

**Comment by rdragan** [comment]
This needs more details on the steps, I can't repro on local.
How many times did this happen? Are you 100% sure it was the laser pointer? And what do you mean by opening and closing the server?

**Comment by c420-o** [comment]
> This needs more details on the steps, I can't repro on local.
> How many times did this happen? Are you 100% sure it was the laser pointer? And what do you mean by opening and closing the server?

Well I mean it happened once, and it seems to be the laser pointer, since that's all I did

**Comment by Sealed101** [comment]
i don't think we can feasibly reproduce this, some kind of byond finicky interaction with lag or something?
