### ISSUE TITLE
Runtime when interacting with modular computers related to update icon

### ISSUE THREAD

**Issue by TBleader** [tgstation/tgstation#57087]
Seems that something is wrong with modular computers and update icon. They don't change their screens as well. I attached a full stack trace from the dream daemon log. Noticed this after pulling all the recent changes. Before that pull I was running code before the ID console changes. Not sure if relevant, just the only thing I remembered that was related to modular computers lately. I'm like.. 70% sure it isn't something fucky with just my byond or the local server I've been running.. but there is always the chance it's something weird I did somehow because I am dumb. 
[message.txt](https://github.com/tgstation/tgstation/files/6016921/message.txt)

## Reproduction:
Interact with a modular computer, immediately get runtimes in the log. 
Shut down the computer, notice the icon doesn't change. 
Start a program, icon also doesn't change. 
Still get tons of runtimes in log.

**Comment by TBleader** [comment]
also
![image](https://user-images.githubusercontent.com/5839706/108612386-3cad9280-739d-11eb-9702-6b93ce5c31f6.png)

**Comment by TemporalOroboros** [comment]
On it.
