### ISSUE TITLE
Space Dragon Stuns itself when using TailWhip

### ISSUE THREAD

**Issue by Taylorkills2** [tgstation/tgstation#57097]
## Round ID:

[156855](https://scrubby.melonmesa.com/round/156855) and many others

## Reproduction:

Use your tail whip as space dragon, notice how your stunned the entire length of the stun, leaving you vulnerable to anyone who wasn't hit with your tail.
Notice how everyone else is stunned an identical length of time making your move almost useless if not suicidal.

**Comment by Pugie** [comment]
The duration of the self stun from gust attack is affected by how much you use it.
It takes about 30 seconds to reduce the penalty of one gust attack, how much were you spamming the attack?

**Comment by Taylorkills2** [comment]
Wasn't me. I've seen space dragon use the attack plenty of times, so far every time it's been identical to everyone else's stun time.
I just haven't bothered reporting it till now.
