### ISSUE TITLE
dna scanner pops their content when used

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#57099]
156861

put chimp in machine
transform into humie
dna scanner board and parts poop out

**Comment by rdragan** [comment]
Dupe of #56632 but I'm gonna keep this one since these are the actual repro steps.

**Comment by rdragan** [comment]
For anyone else looking into this, it seems that the monkey AI is picking up the scanner's internal parts and randomly dropping them. I'm giving up for now.
![image](https://user-images.githubusercontent.com/43266738/108869833-4125b580-7600-11eb-94ad-68826633af4a.png)

**Comment by ArcaneDefence** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/57149
