### ISSUE TITLE
Tramstation: One of the medical treatment center doors doesn't have a firelock

### ISSUE THREAD

**Issue by warden-aW** [tgstation/tgstation#57107]
## Details:

As Shown in this image, one of the Medbay treatment center doors do not have a firelock (circled in RED), although there is one on the other door (circled in BLUE.)

![image](https://user-images.githubusercontent.com/68418447/108643214-91254080-7477-11eb-8372-088f1e100176.png)

**Comment by dragomagol** [comment]
Appears to have been fixed
