### ISSUE TITLE
Bloody hands with amputated arms

### ISSUE THREAD

**Issue by Michael-Ashfield** [tgstation/tgstation#57102]
## Reproduction:

After having my arms amputated, I noticed that I still got bloody hand overlays above my missing hands, the blood icon floating in mid air.
My arms were clean before the surgical amputation and the blood was applied by walking over a bloody tile, I was not wearing gloves or a uniform at the time.

![image](https://user-images.githubusercontent.com/22640529/108638948-c0dd4400-7489-11eb-88e8-40c883cac832.png)

**Comment by ATH1909** [comment]
spooky

**Comment by TemporalOroboros** [comment]
On it.
