### ISSUE TITLE
Borg medical module can rightclick-shove simplemobs.

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#57113]
## Round ID:
[156891](https://scrubby.melonmesa.com/round/156891)

## Reproduction:
 Medical loadout
 Hugging module
 Rightclick Ian
>
![image](https://user-images.githubusercontent.com/62538745/108671495-27705b00-74a6-11eb-94c1-ace7239e3236.png)

![image](https://user-images.githubusercontent.com/62538745/108671710-774f2200-74a6-11eb-80fc-fb2c0fd80046.png)

Testing done indicates that I cannot aggro grab anything, and trying to shove simplemobs into carbons doesn't knock carbons over. Trying to shove carbons just hugs them.

**Comment by ZeroMODE0** [comment]
Update: You can tip and right medibots.
![image](https://user-images.githubusercontent.com/62538745/108673052-9f3f8500-74a8-11eb-8d4b-e6213aa1d2e3.png)
![image](https://user-images.githubusercontent.com/62538745/108673058-a1a1df00-74a8-11eb-8d77-d7bf5e4402eb.png)

Establish dominance.

**Comment by ATH1909** [comment]
feature

**Comment by TheBonded** [comment]
Just say no to blobbernauts and spiders, they legally cannot harm you

**Comment by ATH1909** [comment]
the important question is: can they punch simplemobs by left clicking in combat mode?

**Comment by ZeroMODE0** [comment]
![image](https://user-images.githubusercontent.com/62538745/109060203-c1085a00-76aa-11eb-9716-2c0226ec5ba1.png)


> 
> 
> the important question is (other than the medibot tipping thing, of course): can they punch simplemobs by left clicking in combat mode?
