### ISSUE TITLE
Ice is instantly melting into water

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#57110]
## Round ID:
[156878](https://scrubby.melonmesa.com/round/156878)

## Testmerges:
#56509 

## Reproduction:
Attempt to dispense ice into a glass to make a drink on the rocks, notice that 5u quickly turns to water when I switch to the boozevend.

![image](https://user-images.githubusercontent.com/16896032/108647419-5a493c00-7504-11eb-910c-c2cc0548aa6c.png)

**Comment by necromanceranne** [comment]
@Thalpy another bug, when you can address.

**Comment by Thalpy** [comment]
I'm on the case!

**Comment by Ghommie** [comment]
Solved by #57144. Please close this.
