### ISSUE TITLE
Re-entered brain in MMI, non-functional and "unresponsive".

### ISSUE THREAD

**Issue by Malkraz** [tgstation/tgstation#57118]
Reporting client version: 513.1539

## Round ID:
[156912](https://scrubby.melonmesa.com/round/156912)

## Testmerges:
- [Experi-Sci: Techweb nodes may now require you to perform "scientific" experiments](https://www.github.com/tgstation/tgstation/pull/54093)
- [Tramstation: choo choo MORE MAP COMIN' THROUH](https://www.github.com/tgstation/tgstation/pull/56509)

## Reproduction:
Died, brain got put in an MMI.
Got the prompt to re-enter it and I did.
Lost ghost vision as if I was alive again, but still had ghost chat.
Examined my MMI and it said "The Man-Machine Interface: Rock Steel indicates that the brain is completely unresponsive."
Was able to move out of the MMI and regain ghost vision, but could not re-enter it again.

**Comment by ATH1909** [comment]
was your brain too damaged?

**Comment by SuperNovaa41** [comment]
This happens when you have brain damage, it can be fixed with mannitol, but there's no way to tell as the ghost other than typing and seeing if your message goes to dchat or regular chat.
