### ISSUE TITLE
Rouge vending machines can squish revenants inside walls

### ISSUE THREAD

**Issue by JusticeGoat** [tgstation/tgstation#57122]
Tested again today on 156921 and vending machines can target them inside of walls and while hidden.

**Comment by ATH1909** [comment]
can they succeed in squishing them?

**Comment by dragomagol** [comment]
They make a "pained noise," forgot to check if they took damage

**Comment by Wayland-Smithy** [comment]
Not just inside walls, anywhere adjacent they do, and it does hurt the revenant.
