### ISSUE TITLE
Couldn't eat hot-cross bun

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#57135]
Reporting client version: 513.1539

## Round ID:
[156963](https://scrubby.melonmesa.com/round/156963)

## Testmerges:
- [Tramstation: choo choo MORE MAP COMIN' THROUH](https://www.github.com/tgstation/tgstation/pull/56509)
- [Experi-Sci: Techweb nodes may now require you to perform "scientific" experiments](https://www.github.com/tgstation/tgstation/pull/54093)

## Reproduction:
1. Click self with hot-cross bun
2. Hit self with hot-cross bun

Other food items were fine

**Comment by dragomagol** [comment]
Probably related to #56126 (and the other sporadic "can't eat food"s)
