### ISSUE TITLE
Papers on doors didn't look written on

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#57138]
Reporting client version: 513.1539

## Round ID:
[156963](https://scrubby.melonmesa.com/round/156963)

## Testmerges:
- [Tramstation: choo choo MORE MAP COMIN' THROUH](https://www.github.com/tgstation/tgstation/pull/56509)
- [Experi-Sci: Techweb nodes may now require you to perform "scientific" experiments](https://www.github.com/tgstation/tgstation/pull/54093)

## Reproduction:

1. Put written on paper on door
2. Looks blank

**Comment by TheBonded** [comment]
this is normal behavior
