### ISSUE TITLE
Using a multitool or screwdriver on the dancefloors on NTSS Independence did nothing

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#57141]
Reporting client version: 513.1539

## Round ID:
[156963](https://scrubby.melonmesa.com/round/156963)

## Testmerges:
- [Tramstation: choo choo MORE MAP COMIN' THROUH](https://www.github.com/tgstation/tgstation/pull/56509)
- [Experi-Sci: Techweb nodes may now require you to perform "scientific" experiments](https://www.github.com/tgstation/tgstation/pull/54093)

## Reproduction:
1. Use a multitool or screwdriver on the light floors on NTSS Independence
2. Don't change colour or turn off

Not sure if this is an issue with all light floors or just these ones

**Comment by Tlaltecuhtli** [comment]
those probably use the special subtype

**Comment by Ewwmewgewd** [comment]
NTSS shuttle has `/turf/open/floor/light/colour_cycle`, it's supposed to cycle all colors over time but from my test that's not the case. I think they misspelled the icon name.
