### ISSUE TITLE
Clown cars can't drag people into them

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#57155]
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
Ascend to the ultimate clown form
Buy gamer car
Slip that FUGGIN' HORN IN IT
Go high speed low drag up to a guy on the floor
lmb/rmb drag, with combat mode on or off
Nothing ever happens
Be utterly defeated with no attempt to counter someone just lying still on the floor.
RIP gamerclown

**Comment by SuperNovaa41** [comment]
#57169
