### ISSUE TITLE
Deleting /obj/item/modular_computer/tablet/preset/advanced leaves a standard battery behind

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#57161]
## Round ID:
Local

## Testmerges:
Local

## Reproduction:
1. Spawn the aforementioned tablet
2. Shift+right-click -> Delete
3. Standard battery left behind

Noticeable if you change outfits and had this tablet type on you. Doesn't happen with /obj/item/modular_computer/tablet/preset

**Comment by Mothblocks** [comment]
le side effects on destroy meme

**Comment by Gurkenglas** [comment]
A relevant stack trace:
```
/obj/item/computer_hardware/battery/try_eject (g:\ss13\code\modules\modular_computers\hardware\battery_module.dm:52)
/obj/item/computer_hardware/on_remove (g:\ss13\code\modules\modular_computers\hardware\_hardware.dm:97)
/obj/item/modular_computer/Destroy (g:\ss13\code\modules\modular_computers\computers\item\computer.dm:74)
/qdel (g:\ss13\code\controllers\subsystem\garbage.dm:297)
/client/admin_delete (g:\ss13\code\modules\admin\view_variables\admin_delete.dm:22)
/client/cmd_admin_delete (g:\ss13\code\modules\admin\verbs\randomverbs.dm:595)
```

**Comment by Mothblocks** [comment]
yes

**Comment by Mothblocks** [comment]
to be clear, Destroy should mean DESTROY. there should be nothing left. if you want to perform effects like leaving parts or whatever, thats `deconstruct`, but `qdel` should leave nothing behind.
