### ISSUE TITLE
you're

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#57164]
![image](https://user-images.githubusercontent.com/42606352/108971845-5c1c1800-7648-11eb-96d5-8505341dd3a9.png)
This message was produced by a roboticist accidentally attacking me, a living MMI'd brain, with a surgical tool. Their name was a normal one, not "You're" or the like.

**Comment by ArcaneDefence** [comment]
The title of this report makes it impossible to search.
Make better reports.
