### ISSUE TITLE
metastation wayfinding pinpointer

### ISSUE THREAD

**Issue by Megamaw** [tgstation/tgstation#57182]
okay so i have the directionally challenged pinpointer because i am in fact directionally challenged irl.

lot of locations just straight up on metastation are not listed, like the custodial closet

this is a map issue iirc, so uh, it'd be nice if y'all could like. add all of the rooms to metastation.

**Comment by LemonInTheDark** [comment]
It's not so much rooms, the wayfinding pinpointer uses navbeacons for wayfinding, the same things used by robots like beepsky and the mulebots. They aren't placed everywhere on meta, so different rooms aren't showing up in the pinpointer.

**Comment by cacogen** [comment]
I wish wayfinding drew a path on the floor to the area you want through airlocks you have access to. If I weren't babby, it would.

At the moment you need to use those navbeacons LemonInTheDark describes. They go under the floor, ideally under entry airlocks. They need the correct vars set for them to show up on the pinpointer. Don't know why MetaStation doesn't have the same ones other maps do.

**Comment by san7890** [comment]
I don't think this is an issue in a post #65906 world.

**Comment by LemonInTheDark** [comment]
Did he add new landmarks to places that didn't have them?

**Comment by san7890** [comment]
@cacogen

**Comment by cacogen** [comment]
Someone just needs to add more of the navigate destination landmarks to MetaStation.

**Comment by msgerbs** [comment]
Aaaaaah you didn't close this issue.

Fixed by #66319
