### ISSUE TITLE
Chaplain armour + android conversion creates insane brute resistance

### ISSUE THREAD

**Issue by SuperNovaa41** [tgstation/tgstation#57193]
## Testmerges:

Not sure these play into effect but:
#57080 
#57010 
#57187 

## Reproduction:

Tried to kill a chaplain with android conversion + armour, harmbatonned him and attacked him with fire extinguisher at least 10+ times, and didn't do a single point of brute damage.

1. be chaplain
2. become android through the altar
3. wear forgotten armour
4. become god

Not sure if this is an issue, if its not a nerf on this defence should HEAVILY be considered.

**Comment by ArcaneDefence** [comment]
Androids have the same brute reduction that augmented limbs have, and chaplain's armor is just a zero slowdown riot suit.
So they have 50 melee armor, and anything below 5 damage is completely negated. 

A stun baton and an extinguisher do 10 brute. This isn't in any way a surprise that you did nothing as they have no armor pen.
They're not good melee weapons to begin with, so you should be leveraging the crowd control they provide instead.

**Comment by necromanceranne** [comment]
Since this isn't a bug and intended functionality I'll close it for now.

**Comment by ATH1909** [comment]
use a laser or the like; chaplain armor is basically reskinned riot gear
