### ISSUE TITLE
It is Incredibly Difficult to Become Fat

### ISSUE THREAD

**Issue by Taylorkills2** [tgstation/tgstation#57201]
## Round ID: 157130
Though I failed to become fat in this one, despite an admin spawn super burger.

## Reproduction:
I know there's been some reworks to stomach/bloodstream/satiation, so I have zero idea what's causing it or maybe it's a dozen different things, but it's impossible to become fat by standard gameplay.
Unless your using the quirk? or are specifically going out of your way to become fat for 15-30 minutes, you won't become fat, due to the 15+ minute process for becoming fat.

I remember how becoming fat was a real concern in the past maybe 6+ months ago, but now there's no concern about it at all. Maybe the easiest way is to use nutriment patches or some custom food from the chef.

**Comment by rdragan** [comment]
Ask the botanists for some potency 100 watermelons.

**Comment by Shadowflame909** [comment]
this bug is back. where did the fat mechanic go

**Comment by Mooshimi** [comment]
If you eat something with huge satiety like giant watermelons or corn, you will become fat very easily. I became fat on Sybil earlier today from a big piece of corn... :(

**Comment by timothymtorres** [comment]
@Taylorkills2 i do believe some species had the NO HUNGER trait that might have affected this.  It happens to plasmamen and ethereals.  What mob type was your character?

**Comment by projectkepler-ru** [comment]
No longer applicable as of 2024

**Comment by Sealed101** [comment]
^ tested by eating two big bite burgers from a slightly hungry state; fat status was acquired a few minutes later
