### ISSUE TITLE
Cult changelings lose their halo and glowy eyes when they transform

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#57204]
## Round ID:
#157131

## Reproduction:

When a cultist changeling transforms, they lose their halo and eyes. When they transform from a cultist dna to a noncultist dna back to a cultist dna, they don't seem to regain their eyes or halos.

**Comment by TheBonded** [comment]
This happens with any species change and any type of cybernetic or other type of eyes. If you are a slimeperson with x ray eyes and you change subspecies you lose the x ray eyes.

Please update the pr to include all species changes + all eye organ replacements
