### ISSUE TITLE
Positronic brains become blind and deaf and unable to speak forever if the mech they are in gets destroyed

### ISSUE THREAD

**Issue by TheBonded** [tgstation/tgstation#57217]
## Round ID: N/A
This has been happening for a few months, I just never remembered to make a bug report when I went on github. Last tested last night

## Reproduction:
1. Become posibrain
2. Get put into a mech
3. Get destroyed in combat
4. Be blind and deaf and unable to suicide until you are put into another borg/mech or until they throw you into lava

**Comment by GunHog** [comment]
Did you try ghosting instead of suicide? The advantage of ghosting is that you can immediately hop back into the same posibrain so long as no one else yoinks it from you.

**Comment by Crushtoe** [comment]
Still a problem in a recent round, client rev 513.1542, round ID 165584

**Comment by timothymtorres** [comment]
The traits for the MMI probably aren't being reset after the mech gets destroyed.

**Comment by OHJ4Y** [comment]
Sorry for necroposting but this bug is still in the game. Round ID 193061, not fun. Antithesis of fun, dare I say.

**Comment by timothymtorres** [comment]
If you want help attempting to fix it, you can ping me on discord (TimT) otherwise you will just have to hope some lucky developer will try to fix it in the future.

**Comment by Feasel** [comment]
It's basically that force sleep/unconsious state being applied to a mob that cannot be slept/unconsious. So it just can't wake up because there's no system to wake them up.
