### ISSUE TITLE
round start get stuck on 'soon' for 2 whole minutes

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#57222]
its starting to happen every round

157192

**Comment by LemonInTheDark** [comment]
Ahhhh god fucking damn it

**Comment by ATH1909** [comment]
Soon(TM)

**Comment by LemonInTheDark** [comment]
Please update this issue to match the format

**Comment by SuperNovaa41** [comment]
Doesn't happen anymore

**Comment by LemonInTheDark** [comment]
this kinda still happens, it's just 30 seconds instead of 20 minutes. Caused by getflaticons in spawning code most likely
