### ISSUE TITLE
[BUG][DOWNSTREAM]Emagging escape pods doesnt work

### ISSUE THREAD

**Issue by Yawet330** [tgstation/tgstation#57223]
## Reproduction:
Steps are as follows:
1) Emag escape pod
2) Be confused as to why the UI wont work.

My belief is that while the code for emagging pods still works; the TGUI-Next interface for it doesnt actually have the programming to check for the EMAGGED flag, so you cant interact with it; despite it adding lavaland to the list of valid options.

**Comment by Yawet330** [comment]
From my limited understanding of ReactJS, it does seem to be an issue with the UI not having authorization_required (line 151) and locked (also 151) being changed upon emagging.

**Comment by Yawet330** [comment]
Yeah, after forcefully varediting locked to 0 on a test pod,
![image](https://user-images.githubusercontent.com/65188584/109351175-b7c8ea00-7870-11eb-8a26-4a756752d1d6.png)
UI worked just fine.
Compare this to a regular pod (emagged of course) without the varedit
![image](https://user-images.githubusercontent.com/65188584/109351207-ca432380-7870-11eb-8cde-cbc936fdaaa6.png)

**Comment by LemonInTheDark** [comment]
Does this replicate on our codebase? I'd assume so, but I'd like to make sure

**Comment by Yawet330** [comment]
> Does this replicate on our codebase? I'd assume so, but I'd like to make sure

It should; based on how we fixed it and looking over your code, the exact same issue presents itself, LOCKED is never set to 0/false even after emagging, and the TGUI component doesnt check for emagged.
