### ISSUE TITLE
Blood filter surgery always uses "you're" even when you're not the one being operated on.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#57226]

**Comment by ArcaneDefence** [comment]
Can't reproduce anything to do with "you're", however, there is a redundant the. 
Additionally, `/datum/surgery_step/filter_blood/failure` has misspellings of bruising. 


As operator:
You begin filtering Kellen Summy's blood...
The the blood filter pings as it finishes filtering Kellen Summy's blood.

As patient:
Madison Wells uses the the blood filter on Kellen Summy's chest.
The the blood filter pings as it stops pumping.

and as observer there was no visible message.
