### ISSUE TITLE
M1911 magazine cant be ejected

### ISSUE THREAD

**Issue by SamDDBS** [tgstation/tgstation#57244]
## Round ID:
[157220](https://scrubby.melonmesa.com/round/157220)

## Testmerges:
#57080 #56509 

## Reproduction:
Go to space
Find ruin full of those green monster things and the green resin walls
There is 2 M1911s in the ruin
Try everything you can to try and unload the magazine
Realize it won't eject the magazine therefore you can not put bullets in it
Massively disappointed and now you have a threatening looking bag weight

**Comment by necromanceranne** [comment]
Did you put a magazine in? Because they don't spawn with any magazines.

**Comment by SamDDBS** [comment]
as a regular crewmember that round i didnt have access to pistol magazines, i guess i now know that it doesnt come with a magazine for some odd reason, even though the previous owners of the guns must have used a magazine to fire those bullets on the ground
