### ISSUE TITLE
if you move when memento mori action botton do_after happens it glitches

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#57249]
157233

**Comment by ArcaneDefence** [comment]
What's the glitch, exactly?
This report sucks.

**Comment by Tlaltecuhtli** [comment]
you cant click it anymore and the botton becomes missingo

**Comment by LemonInTheDark** [comment]
Follow the issue formatting, or I'll close this issue. It exists for a reason.

**Comment by Mothblocks** [comment]
we have 1.7k issues its alright if we close the shitty ones right away 🙂
