### ISSUE TITLE
Nuke ops ship has no roof

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#57240]
## Reproduction:
>Be crew
>nukies land on lower z level
>???
>fly over them and meme on them
![image](https://user-images.githubusercontent.com/51863163/109376319-48132900-7889-11eb-88f9-7990bce87f2b.png)

**Comment by ZeroMODE0** [comment]
![image](https://user-images.githubusercontent.com/62538745/109383340-8f121600-78ab-11eb-86f9-5bf860887176.png)
If we so rich...

**Comment by maxymax13** [comment]
tactical anvil dropping

**Comment by SuperNovaa41** [comment]
Duplicate of https://github.com/tgstation/tgstation/issues/57240

**Comment by SuperNovaa41** [comment]
wrong issue :)
