### ISSUE TITLE
The source code fails to compile because of missing TGUI components.

### ISSUE THREAD

**Issue by sergeirocks100** [tgstation/tgstation#57250]
## Round ID: 

none

## Testmerges:

none

## Reproduction:

Download the source code.

Try to compile it in Dream Maker.

Watch as it fails miserably because it's missing TGUI components.

`loading tgstation.dme
loading interface\skin.dmf
code\modules\asset_cache\asset_list_items.dm:6:error: 'tgui/public/tgui-common.bundle.js': cannot find file
code\modules\asset_cache\asset_list_items.dm:12:error: 'tgui/public/tgui.bundle.js': cannot find file
code\modules\asset_cache\asset_list_items.dm:13:error: 'tgui/public/tgui.bundle.css': cannot find file
code\modules\asset_cache\asset_list_items.dm:19:error: 'tgui/public/tgui-panel.bundle.js': cannot find file
code\modules\asset_cache\asset_list_items.dm:20:error: 'tgui/public/tgui-panel.bundle.css': cannot find file
tgstation.dmb - 5 errors, 0 warnings (2/27/21 7:56 am)
`

**Comment by Ewwmewgewd** [comment]
Don't use dream maker to compile. There is a Build.bat file now that you run to compile. Read: https://tgstation13.org/wiki/Downloading_the_source_code

**Comment by sergeirocks100** [comment]
It fucks up with what appears to be the same error when i use build.bat.

` => Starting 'tgui'
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 237ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 3 packages were already cached, 827 had to be fetched
➤ YN0000: └ Completed in 4m 43s
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 5s 117ms
➤ YN0000: Done in 4m 49s
assets by path *.js 1.04 MiB
  asset tgui.bundle.js 662 KiB [emitted] [minimized] (name: tgui)
  asset tgui-common.bundle.js 349 KiB [emitted] [minimized] (name: tgui-common) (id hint: vendors)
  asset tgui-panel.bundle.js 55.8 KiB [emitted] [minimized] (name: tgui-panel)
assets by path *.css 255 KiB
  asset tgui.bundle.css 163 KiB [emitted] (name: tgui)
  asset tgui-panel.bundle.css 91.8 KiB [emitted] (name: tgui-panel)
Entrypoint tgui 1.15 MiB = tgui-common.bundle.js 349 KiB tgui.bundle.css 163 KiB tgui.bundle.js 662 KiB
Entrypoint tgui-panel 496 KiB = tgui-common.bundle.js 349 KiB tgui-panel.bundle.css 91.8 KiB tgui-panel.bundle.js 55.8 KiB
2021-02-27 09:30:20: webpack 5.23.0 compiled successfully in 45622 ms
 => Finished 'tgui' in 346.915s
 => Starting 'dm'
DM compiler version 513.1542
loading tgstation.dme
loading interface\skin.dmf
BUG: The file C:\cygwin64\home\sergei\Github\tgstation\tgstation.rsc is locked up!
code\modules\asset_cache\asset_list_items.dm:6:error: 'tgui/public/tgui-common.bundle.js': cannot find file
BUG: The file C:\cygwin64\home\sergei\Github\tgstation\tgstation.rsc is locked up!
code\modules\asset_cache\asset_list_items.dm:12:error: 'tgui/public/tgui.bundle.js': cannot find file
BUG: The file C:\cygwin64\home\sergei\Github\tgstation\tgstation.rsc is locked up!
code\modules\asset_cache\asset_list_items.dm:13:error: 'tgui/public/tgui.bundle.css': cannot find file
BUG: The file C:\cygwin64\home\sergei\Github\tgstation\tgstation.rsc is locked up!
code\modules\asset_cache\asset_list_items.dm:19:error: 'tgui/public/tgui-panel.bundle.js': cannot find file
BUG: The file C:\cygwin64\home\sergei\Github\tgstation\tgstation.rsc is locked up!
code\modules\asset_cache\asset_list_items.dm:20:error: 'tgui/public/tgui-panel.bundle.css': cannot find file
tgstation.dmb - 5 errors, 0 warnings (2/27/21 9:31 am)
Total time: 0:58
ExitError: Process exited with code: 4294967295
    at ChildProcess.<anonymous> (C:\cygwin64\home\sergei\Github\tgstation\tools\build\cbt\process.js:91:23)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12) {
  code: 4294967295
}
Press any key to continue . . .`

**Comment by sergeirocks100** [comment]
I deleted the RSC and tried again, and it appears to have compiled successfully, so i think i can close this issue.
