### ISSUE TITLE
Hulks cant shove in combat mode

### ISSUE THREAD

**Issue by Deltarin** [tgstation/tgstation#57259]
## Reproduction:
Try to shove in combat mode as hulk, it doesnt work. It works just fine in non combat mode.

**Comment by necromanceranne** [comment]
by doesn't work can you clarify exactly what it DOES do?

**Comment by Deltarin** [comment]
Instead of shoving it just does a normal hulk punch.

**Comment by necromanceranne** [comment]
@Qustinnus any input on this?

**Comment by Ryll-Ryll** [comment]
I gotcha
