### ISSUE TITLE
[Oversight] The RPD unwrenching upgrade doesn't work like RCD upgrades for borgs

### ISSUE THREAD

**Issue by Cavoglave** [tgstation/tgstation#57267]
Reporting client version: 514.1548

## Round ID:
[157277](https://scrubby.melonmesa.com/round/157277)

## Testmerges:
- [Fully implements the ID Card design document](https://www.github.com/tgstation/tgstation/pull/56910)

## Reproduction:
You know how RCD upgrades can be applied by attack_by-ing the disk with an RCD?
This doesn't work with the RPD unwrenching upgrade. You can't apply the upgrade by clicking on it with the RPD "in hand", it can only be applied by clicking on the RPD with the disk in hand. this isn't a problem for humans, but for borgs it means the upgrade is impossible to apply to an engineering borg's RPD module.
Since RCD upgrades work for borgs via this special method, I doubt this is intentional, as opposed to an oversight by whoever coded the RPD upgrade.

**Comment by jlsnow301** [comment]
author requested close as these could not be reproduced & significant refactors applied. feel free to reopen this issue if it persists
