### ISSUE TITLE
If moved by explosion while you can't move with no gravity, you do not recover the ability to move, while a mob

### ISSUE THREAD

**Issue by Jhyrachy** [tgstation/tgstation#57262]
## Testmerges: The following pull requests are currently test merged:
#57080: 'Makes most obtainable lasers (normal laser, disabler, xray, scatter, hellfire) hitscan!' by Sparkezel at commit a60d24359e

## Reproduction: Being an Adult Pink Slime (maybe happens with others mobs), with no gravity, suspended in a tile with nothing near (can't move). 
Being pushed to a wall with an explosion.  
Now, in theory you should be able to move. 
In practice, you cannot and are still stuck.

**Comment by Sealed101** [comment]
can no longer reproduce; we've had a recent-ish spacemove refactor (#84869) but i have a suspicion that this had been fixed before it
