### ISSUE TITLE
Possibly infinite regenerative mesh

### ISSUE THREAD

**Issue by SuperNovaa41** [tgstation/tgstation#57296]
## Round ID:
157312

## Testmerges:

New ID changes
Hitscan lasers

## Reproduction:

After being wounded on the head by hellfire lasers, applied regenerative mesh to heal the wound. I still had damage after running out of mesh, however after the item had run out and had disappeared from my hand I continued to apply mesh until I fully healed the burn damage and healed the wound.

**Comment by SuperNovaa41** [comment]
> 
> ## Round ID:
> 157312
> 
> 
> 
> ## Testmerges:
> 
> ID change
> Hitscan lasers
> 
> 
> 
> ## Reproduction:
> 
> After being wounded on the head by hellfire lasers, applied regenerative mesh to heal the wound. I still had damage after running out of mesh, however after the item had run out and had disappeared from my hand I continued to apply mesh until I fully healed the burn damage and healed the wound.
> 
> 
> 
> 
>

**Comment by Fhaxaris** [comment]
I had something similar happen while healing someone before. I think put the mesh into a box while I was healing them.

**Comment by SuperNovaa41** [comment]
![image](https://user-images.githubusercontent.com/16159590/115098512-6e0a9080-9efe-11eb-8dac-3a04217e036c.png)
 Didn't manage to get OBS open in time but i managed to recreate this issue again. It seems to only happen on wounds. Aswell both instances have been on the head.
