### ISSUE TITLE
juice boxes transmogrify into paper cups

### ISSUE THREAD

**Issue by maxymax13** [tgstation/tgstation#57292]
## Round ID:
no

## Testmerges:
no

## Reproduction:
step 1. make some juice box cartons with cardboard (through the crafting menu, not the stack construction menu?)
step 2. put your misc. gamer juice in them (i used coffee latte but it doesn't really matter)
step 3. watch as they magically turn into a paper cup because they're a subtype of paper cups for some reason
step 4. watch as they magically turn back into a carton when depleted of their fluids
![dreamseeker_R2kMWpFmGj](https://user-images.githubusercontent.com/38844529/109436205-3a7eb000-79fd-11eb-8647-dd6283589216.png)

**Comment by TemporalOroboros** [comment]
Yeah. I think I figured out what's happening. The carton's only overriding the parent update_icon_state when it contains a specific set of reagents or it's empty. I'll fix it sometime when I'm not completely swamped by classwork.
