### ISSUE TITLE
manifolds icon is messed up on layers other than default

### ISSUE THREAD

**Issue by Ghilker** [tgstation/tgstation#57301]
## Reproduction:
![image](https://user-images.githubusercontent.com/42839747/109481171-bbc95780-7a7c-11eb-8651-b2449570e41d.png)
place manifolds on any layer, look as they are badly messed up
this issue is for all pipe manifolds and H/E and also multiz adaptors

**Comment by Mooshimi** [comment]
Fixed by #60981 among other prs
