### ISSUE TITLE
Putting a brain into an MMI may make it invalid for the escape objective, even after removing it

### ISSUE THREAD

**Issue by Skasi** [tgstation/tgstation#5731]
Soo today my objective was to steal the brain of a braindead roboticist. Was super easy after getting the proper access. Anyway, to be less suspicious I put the brain into an MMI. Before escaping **I removed the brain from the MMI** and put it in my backpack just to make sure the syndicate wont lynch me for not getting the brain alone.

Turns out they still did.
![brainbug2](https://cloud.githubusercontent.com/assets/132906/4954205/e801b8e6-6689-11e4-9c94-f54596da7eb2.png)

Now I'm not certain if putting the brain into the MMI somehow messed with the brain item's variables after retrieving it again, or if there's some other bug. Anyway I'm pretty sure this is not a case of #1760, since the brain was removed from an alive-but-braindead roboticist.

**Comment by optimumtact** [comment]
old with no repro
