### ISSUE TITLE
weird fermichem bug

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#57316]
was making some libitard + yuri  and the machine stopped responding while the energy level started rising to overflow levels
![bug](https://i.imgur.com/7VgC35L.png)
157379

**Comment by Time-Green** [comment]
Use the issue format that git gives to you so the gitbot can create the proper round references

**Comment by Tlaltecuhtli** [comment]
what

**Comment by TheBonded** [comment]
> what

Instead of deleting the format that is specifically there for you to use when you make a new issue report, just put in the information the format asks for, so the github bot can correctly link the round number and such.

**Comment by Tlaltecuhtli** [comment]
https://scrubby.melonmesa.com/round/157379

**Comment by TheBonded** [comment]
> https://scrubby.melonmesa.com/round/157379

Have you reproduced this yet?

**Comment by Thalpy** [comment]
This is really strange for sure.

**Comment by Sealed101** [comment]
>libitard

been a few years and we haven't seen this bug occur since, no dupe issues or discord discussion, and no useful reproduction steps. closing this
