### ISSUE TITLE
Ethereal Crystalisation Bug - Stuck in your body

### ISSUE THREAD

**Issue by ShizzleG** [tgstation/tgstation#57327]
Reporting client version: 513.1542

## Round ID:
[157394](https://scrubby.melonmesa.com/round/157394)

## Testmerges:
- [Fully implements the ID Card design document](https://www.github.com/tgstation/tgstation/pull/56910)
- [Makes most obtainable lasers (normal laser, disabler, xray, scatter, hellfire) hitscan!](https://www.github.com/tgstation/tgstation/pull/57080)
- [Crystallizer Hotfix (mistakes were made)](https://www.github.com/tgstation/tgstation/pull/57256)

## Reproduction:
Basically, it's an issue with the newly added crystalisation revival for Ethereals. I was playing the round as a Clown. I wanted to test the revive so I killed myself, with the help of others. They accidentally disturbed the Crystalisation and made it not activate, and so this caused me to be unable to leave my body. I pressed the "Ghost" button in OOC and typed Ghost in the commands box and it didn't work. I even tried "Suicide" and it confirmed, I was dead already. So yeah, it broke and I was unable to do anything. I had to be revived to actually you know, do anything, so this could be a problem if I were killed by a traitor or something like that, as I'd physically be stuck in my body and I'd probably have to be dusted/gibbed to be let out, or revived as mentioned. Basically: Die as Ethereal, be disturbed/have crystals broken. You are now stuck in your body. I'm unsure if this was a one off though.

**Comment by Qustinnus** [comment]
i fixed this
