### ISSUE TITLE
Getting your body deleted then entering recrystallization causes you to get sent back to lobby

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#57337]
## Round ID:

#157412

## Reproduction:

An ethereal, Atlas Y, took the staff of asclepius. 

They died, and their body was deleted and they became a snake. Then, recrystallization began.

Their body was deleted but not fully deleted and their POV was a black screen / empty space. They were stuck like this until their body was hard-deleted, and they were replaced with a new player mob -> could rejoin or observe.

We managed to replicate it in the thunderdome following it happening in the round.

![image](https://user-images.githubusercontent.com/51863163/109607840-76457280-7aee-11eb-822d-dd8445d92bfa.png)

![image](https://user-images.githubusercontent.com/51863163/109608575-b0fbda80-7aef-11eb-9dd7-c0c26b0081a3.png)

![image](https://user-images.githubusercontent.com/51863163/109608611-bbb66f80-7aef-11eb-88b6-99c27d1c671d.png)

![image](https://user-images.githubusercontent.com/51863163/109608486-93c70c00-7aef-11eb-9a60-d4d878266d92.png)

**Comment by TheBonded** [comment]
so they can change characters midgame?

**Comment by necromanceranne** [comment]
@Qustinnus

**Comment by dragomagol** [comment]
Apparently falling down a chasm as an ethereal also sends you back to the lobby

**Comment by Qustinnus** [comment]
i fixed this
