### ISSUE TITLE
Slime races can become unrevivable due to negative blood values

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#57336]
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
Spawn a slime person
Spawn a medbot
Varedit medbot to heal toxin
Inject slime person with pentetic acid
Buckle them to stasis when the medbot starts to deal toxin damage to them, reducing their blood level in the process
Try to revive them after they've died in stasis from blood loss
Watch as they revive to instantly die, and their blood level goes into even further negative values
Realize the only way to treat this is to bludgeon/burn their corpse and apply synthflesh to deal instant toxin damage to a corpse to restore their blood to a level that they won't instantly die from negative blood values
![image](https://user-images.githubusercontent.com/51932756/109608424-15ff0280-7ae7-11eb-9862-9d34994f0641.png)

**Comment by ATH1909** [comment]
Do they still die even while strapped to the stasis bed?

**Comment by prodirus** [comment]
> Do they still die even while strapped to the stasis bed?

They'll die as usual when they hit 200 total damage.
