### ISSUE TITLE
Ghosts don't have minds or something I don't know

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#57366]
## Reproduction:

1). Uhhhhhhhhhhhhhhhh
2). Spawn in as a ghost
3). Look at your sweet player panel
4). You have no mind
5). Head empty

I don't know if this is actually tracked or already being fixed I just work here hi

**Comment by TheBonded** [comment]
What?

**Comment by timothymtorres** [comment]
Observers don't have bodies.  Closing since the reported problem is vague.
