### ISSUE TITLE
Reinforced glass tables make iron tables

### ISSUE THREAD

**Issue by mozi-h** [tgstation/tgstation#57362]
## Testmerges:
- `#57305`
- `#57298`

## Reproduction:
Make a table using *reinforced* glass
![grafik](https://user-images.githubusercontent.com/19172408/109702936-2e2d5b00-7b95-11eb-8465-47e5b15fc32f.png)
`A square piece of iron standing on four metal legs.`

**Comment by TheBonded** [comment]
Transmute glass into iron

**Comment by Sealed101** [comment]
#61153
