### ISSUE TITLE
Anything that requires javascript is not loading.

### ISSUE THREAD

**Issue by dondonpow** [tgstation/tgstation#57377]
If you discovered this issue from playing tgstation hosted servers:

[Round ID]: #157469 
## Testmerges:
Dog  AI 2.0

## Reproduction:
I'm not sure that'd be possible. All I need to to to experience is it is to connect to the server.

Most things that require javascript also say this line:
"Javascript is required in order to use this interface.
Please enable Javascript and restart the game."
Ok, I should probably say this first. YES, I did enable javascript in internet explorer. And just to make sure, I enabled EVERY OTHER OPTION TOO in IE. I've uninstalled/reinstalled byond, uninstalled/reinstalled internet explorer, updated java, restarted my computer a couple of times, and nothing has helped. I'm actually pretty sure I had this same issue a while, ago, but I forgot the solution. 
I'm running byond version 513.1542 one windows 10

**Comment by dondonpow** [comment]
some examples of the issue:
https://files.catbox.moe/s8aapn.PNG
https://files.catbox.moe/57tbff.PNG
https://files.catbox.moe/3yr15d.PNG

**Comment by mozi-h** [comment]
Sometimes, for some people, BYOND versions past 513.1536 break some things (for some reason).
It's probably worth a shot to see if downgrading helps.
http://www.byond.com/download/build/513/

**Comment by Ewwmewgewd** [comment]
Don't use latest BYOND version. Get 513.1536 or something around that. Even the servers don't use the latest version. 
![image](https://user-images.githubusercontent.com/60656530/109987323-d0b91b80-7d06-11eb-8d28-eabbd1bacd4f.png)

**Comment by dondonpow** [comment]
ok, i'll try both of these.

**Comment by dondonpow** [comment]
I tried 513.1536, 513.1490, 513.1539 and 513.1534. Though, I did not uninstall byond each time, so that might've created an issue.

**Comment by mozi-h** [comment]
I assume you did the first time with 1536? Can rule version-problems out then.

Perhaps @stylemistake (tgui code owner) can help. (Please tell me if I ping you too much, I feel guilty)
There's also been someone with icon weirdness in Discord today. Doubt it's related, but you never know.

**Comment by stylemistake** [comment]
This is definitely something environment related. Can you check if same is happening on other servers (non-tg)?

**Comment by dondonpow** [comment]
just checked goonstation, the menu isn't loading there either. I'll see what i can do about the anit-malware software.

**Comment by dondonpow** [comment]
I did some fiddling with my antivirus, and it's still not loading anything that requires javascript. 
Good lord I can't wait until ss14 is done. I don't want to have to deal with anything like this again.

**Comment by stylemistake** [comment]
Is javascript working in normal IE11 browser at least?

**Comment by stylemistake** [comment]
I'll probably repeat something you've already done, but do the following:

https://support.microsoft.com/en-us/topic/change-or-reset-internet-explorer-settings-2d4bac50-5762-91c5-a057-a922533f77d5

https://community.spiceworks.com/topic/131967-delete-internet-explorer-profile

**Comment by dondonpow** [comment]
I'm not actually sure where I'd check if it's working on IE11. Should i go to a specific website to check it?

**Comment by stylemistake** [comment]
Check its user agent, you can press F12 and type navigator.userAgent. If it says Trident/7.0, it's IE11.

**Comment by dondonpow** [comment]
the console spat out "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0;" and some other stuff. I'd post the rest of it, but i have no idea what it means, so I'll just keep it to myself unless you need it.

**Comment by stylemistake** [comment]
So it does contain Trident/7.0, therefore it's IE 11.

**Comment by dondonpow** [comment]
When you say, "It's IE11", you mean it's the issue? If so, I'll try to check the setting again.

**Comment by stylemistake** [comment]
It isn't the issue, IE11 is required for the game, and you have it.

**Comment by dondonpow** [comment]
Ah, well thanks.

**Comment by dondonpow** [comment]
OH MY GOD. IT JUST STARTED WORKING AGAIN AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA. GOD I HATE WINDOWS 10

**Comment by dondonpow** [comment]
oh btw thank you @stylemistake this probably wouldn't of been fixed without you

**Comment by stylemistake** [comment]
So what did you do? Any ideas?

**Comment by dondonpow** [comment]
what happened was i fiddled around with some firewall settings, checked again to see that it still wasn't working, and then i reset them. after a couple of hours i decided to play an assistant round, since that doesn't require you to interact with consoles/vending machines that much, and it just worked.

**Comment by dondonpow** [comment]
IT'S BROKEN AGAIN AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
