### ISSUE TITLE
Monkeys continue to move in order to chase mobs, even while dead.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#57372]
Reporting client version: 513.1536

## Round ID:
[157468](https://scrubby.melonmesa.com/round/157468)

## Testmerges:
- [Chef Produce Console, for cases where there are no botanists](https://www.github.com/tgstation/tgstation/pull/57298)
- [Japanese Tourists! Oh, and beef stroganoff, I guess!](https://www.github.com/tgstation/tgstation/pull/57305)

## Reproduction:
1. have monkey chase someone trying to kill them
2. kill monkey
3. watch monkey continue to chase

(this accorded at about 40 minutes into the round, if the logs will be of any help)

**Comment by redguy999** [comment]
I'm 75% sure this issue is related to why the catatonic monkey humans still move.

**Comment by dragomagol** [comment]
Return of #55544

**Comment by Mooshimi** [comment]
This also happened in round 166818 to me, for reference.

**Comment by redguy999** [comment]
seems to have stop happening, not sure what fixed it, though.
