### ISSUE TITLE
Kilo hydroponics has not one, not two, but THREE air alarms

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#57373]
![image](https://user-images.githubusercontent.com/51863163/109752818-b7995900-7ba6-11eb-9b51-491c9e2e317d.png)

**Comment by MrMelbert** [comment]
bonus meme
![image](https://user-images.githubusercontent.com/51863163/109753302-a13fcd00-7ba7-11eb-8352-486183a76ccc.png)

**Comment by LemonInTheDark** [comment]
I mean
