### ISSUE TITLE
SMESes only use the yellow (second layer) wires, and no other layers.

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#57376]
As stated in the title, SMESes will not take or give wires to or from red or blue wires on the floor. Hitting Z with a wire in hand will allow you to select different layers (colors); However, you could also do something utterly fucking stupid but otherwise logically sound.

What works for me: (for bridging wires without connecting them into a plus shape)
Start with a multilayer hub (with yellow and red enabled) and put red on one side, yellow on the other.
Travel with red; then stop and make another multilayer with yellow connecting to the SMES input. Since it's ""converted"" back into a yellow wire, it'll work like normal.

**Comment by ZeroMODE0** [comment]
I've had trouble finding another report about this... But I think that might be because SMESes automatically don't loop into themselves, and multiple wire layers is pretty much unused.

**Comment by redguy999** [comment]
theres a thing that connects didn't wire layers, putting that on the SMES tile will fix the problem.

**Comment by LemonInTheDark** [comment]
I think? this is intended, honestly it's hard to tell since very few people use wire layers

**Comment by ZeroMODE0** [comment]
I can confirm that you can make layer hubs that enable machines, just that either you do this for one thing or give in and use yellow wires for a bunch of things
Layer hubs are kind of expensive to make so doing something like emitters or solars with the hubs can be painful. One SMES (Like for a solars kit to the AI core smes without breaking r walls or linking AI core to grid, or icebox tcomms input) is completely okay though.

The only uses I've found for it is making multiple independent wires in a small amount of space, or triple ensuring a smes output is not linked to grid.
Wire solars with yellow, convert to red and travel, machine layer hub to smes input!
