### ISSUE TITLE
Cult unable to make runes in maint

### ISSUE THREAD

**Issue by steppecist** [tgstation/tgstation#57390]
Reporting client version: 513.1542

## Round ID:
[157498](https://scrubby.melonmesa.com/round/157498)

## Testmerges:
- [Makes most obtainable lasers (normal laser, disabler, xray, scatter, hellfire) hitscan!](https://www.github.com/tgstation/tgstation/pull/57080)

## Reproduction:
During a cult round i and all the other members were incapable of making runes inside maintenance, all of us tried in multiple different spot but every time we were given the message that is given when you are trying to make a base in lavaland or in space 'the veil is not weak enough here' or something like that. Obviously the cult lost due to this. Reproducing it was done numerous times as mentioned, just go into maint and try and make runes, i have absolutely no explanation for why or how this happened as, atleast according to an admin, maint was considered to be on the station.

**Comment by Fakka6969** [comment]
have you tried clicking harder

**Comment by Sparkezel** [comment]
Fikou forgot to add CULT_PERIMTTED to maintenance and few other areas + blobbo can't make his core in many locations, funny!

**Comment by steppecist** [comment]
> have you tried clicking harder

Yes, didnt work

**Comment by Taylorkills2** [comment]
Yeah it's alot of areas don't have permission for cult construction. I imagine every map's off-station areas don't have perms.
