### ISSUE TITLE
The foam finger launcher has 5,000 rockets inside it - racking the slide releases ALL OF THEM

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#57413]
## Reproduction:
* Spawn in a foam finger
* Pick it up
* Press Z

Expected: Nothing
Happens: 5,000 rockets rack out of the finger and cause a monumental amount of lag

(Originally found by Pumpo)

**Comment by TheBonded** [comment]
Feature

**Comment by LemonInTheDark** [comment]
I blame the admin team

**Comment by coiax** [comment]
I blame which ever dipshit originally merged this feature. 🙃
