### ISSUE TITLE
reaction chamber ph limits are messy

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#57459]
they accept any value even negative

**Comment by Time-Green** [comment]
Negative pH is 1000000% a thing, so I see no reason not to support it

**Comment by Tlaltecuhtli** [comment]
ph goes to 1 to 14

**Comment by Ghilker** [comment]
> ph goes to 1 to 14

https://pubs.acs.org/doi/pdf/10.1021/ed083p1465 it can be negative
