### ISSUE TITLE
Fever and Shiver deal 0 damage

### ISSUE THREAD

**Issue by FalkKeegan** [tgstation/tgstation#57468]
## Reproduction:

Create virus with fever or shiver as only harmful, active symptom, maximize stats accordingly (resistance or speed in case of shiver), inject a monkey or yourself with it. No damage done, just annoying messages.

For reference my test virus was: Sneezing, Cough, Itching (Neutered), Fever (Neutered), Shivering, Viral evolutionary acceleration. Totally harmless.

**Comment by EnPeignoir** [comment]
¨It's probably because it's normal, imagine receiving "damage" in real life because you sneeze or shiver :/

**Comment by FalkKeegan** [comment]
A strong enough fever can and will kill you.

**Comment by EnPeignoir** [comment]
Interesting pov, maybe coding differents severity of fever is maybe a good idea, maybe a courageous maintainer up to a such task ?

**Comment by Pugie** [comment]
> Interesting pov, maybe coding differents severity of fever is maybe a good idea, maybe a courageous maintainer up to a such task ?

realism isn't always a good excuse for things, especially in cartoon 2d spessmen game. 
Different severity is already a thing and is the reason this issue even exists, you have to reach high enough stat thresholds to get a damaging fever/shivering symptom and supposedly this is bugged and not doing damage right now.

**Comment by KathyRyals** [comment]
After testing on local, I do take burn damage from a maxed out fever symptom. 
![image](https://user-images.githubusercontent.com/65850818/110242635-3a2f6900-7f57-11eb-9911-14930d82d721.png)

**Comment by KathyRyals** [comment]
![image](https://user-images.githubusercontent.com/65850818/110242653-4d423900-7f57-11eb-8e03-0f1578e3e849.png)

**Comment by KathyRyals** [comment]
Shiver doesn't seem to work, however. 
![image](https://user-images.githubusercontent.com/65850818/110242855-2a645480-7f58-11eb-8786-9b4348bed58a.png)

**Comment by nightred** [comment]
I will have to look this over and fix up shivers.

**Comment by FalkKeegan** [comment]
Maybe adjust the thresholds in the description for fever to reflect the actualy value too. Because at the given Resistance 10, no damage is being dealt.

**Comment by KathyRyals** [comment]
Fever definitely hurts though. Unless damage scales with resistance ?

**Comment by FalkKeegan** [comment]
A resistance 15 Fever does not harm me. Round ID 157791.

**Comment by EnPeignoir** [comment]
- [Round 157791 logs](https://tgstation13.org/parsed-logs/sybil/data/logs/2021/03/08/round-157791/)
- [Round 157791 virus.txt logs](https://tgstation13.org/parsed-logs/sybil/data/logs/2021/03/08/round-157791/virus.txt)


All i can see is that your virus has spread all around the station and that you weren't a antag 😄

**Comment by nightred** [comment]
fever was burning people alive before now it is not stronk enough. HA.

**Comment by Adanps** [comment]
While on local I found something unusual. A disease containing Sneezing, Chills, Fever, Hallucigen, Eternal Youth and Disfiguration did no damage to a nude human. However, putting a pair of guerilla gloves from deathsquad units on the same nude human caused them to quickly take large amounts of burn damage from the disease. I cannot even begin to fathom why.

**Comment by nightred** [comment]
Fever and chills only hurt because they change how the body temperature is
regulated.

Fever causes you to over heat taking damage because of over heating.
Chills cause damage by causing you to be to cold.
If you increase the temperature that you are targeting by +50 and -50 that
is a 0 point change.

This is also why fever and chills do not work on lizards, they have no self
regulation of body temperature.

**Comment by nightred** [comment]
For the body temp changes this is what fever does
https://github.com/tgstation/tgstation/blob/55b92786dcf0f9c5172efd111a6ecbf83ec0dae2/code/datums/diseases/advance/symptoms/fever.dm#L69

When the body self regulates temperature it gets the body temp normal
https://github.com/tgstation/tgstation/blob/d0fd64e7c50be4555b2c65b80e310beadecb44d9/code/modules/mob/living/carbon/human/species.dm#L1610-L1612

The body temp normal is computed based on the changes applied from the fever or chills.
https://github.com/tgstation/tgstation/blob/7c22e67bfb343c1436fbae024697604a7d6a16ff/code/modules/mob/living/carbon/human/life.dm#L150-L153

And the total change is the total of all changes applied
https://github.com/tgstation/tgstation/blob/c52022a476d6409ad09f5df622f5acf46cfcd614/code/modules/mob/living/living.dm#L1735-L1740

**Comment by Adanps** [comment]
Ah, so rather than increasing or decreasing the body temperature the virus symptoms instead change the temperature that the body tries to maintain. Thanks for explaining that! Still leaves the question of what was happening with the gloves...

Anyway, don't expect a disease with fever and chills to ever do damage, gotcha.

**Comment by nightred** [comment]
Gloves provide insulation and this helps the body maintain and achieve self regulation faster.
Here you can see that the `/datum/species/proc/body_temperature_skin()` gets the insulation.
https://github.com/tgstation/tgstation/blob/d0fd64e7c50be4555b2c65b80e310beadecb44d9/code/modules/mob/living/carbon/human/species.dm#L1638-L1639

And here you can see how that protection is used to keep and speed up body temp changes.
https://github.com/tgstation/tgstation/blob/d0fd64e7c50be4555b2c65b80e310beadecb44d9/code/modules/mob/living/carbon/human/species.dm#L1650-L1658

**Comment by Adanps** [comment]
I think I get the gist of it after staring the code. It's still a bit beyond me to understand the exact process, but thanks for the info! Anyway, I tried to recreate the gloves oddity to no success, so now I really don't know what the heck happened the first time. I'm just going to chalk it up to some extra factor I missed before.

Also I tried out a fever virus, and then a shivering/chills virus. Both viruses met the thresholds, changed body temperature, and dealt burn damage on a clothed and unclothed infected. It seems this bug has currently been resolved, unless I was just lucky or something.

**Comment by timothymtorres** [comment]
The shivering and fever temperature effects were cancelling each other out.  That's why there was no damage.

**Comment by timothymtorres** [comment]
@nightred @Adanps 

https://github.com/tgstation/tgstation/blob/55b92786dcf0f9c5172efd111a6ecbf83ec0dae2/code/datums/diseases/advance/symptoms/chills.dm#L66-L68

The shivering effect was renamed to the chills effect.  I'm closing this since it doesn't appear to be a bug.
