### ISSUE TITLE
Sculpted spiders have the spider walking animation

### ISSUE THREAD

**Issue by joookschad** [tgstation/tgstation#57464]
## Reproduction:
sculp a spider, drag the statue around
https://www.youtube.com/watch?v=0rjLDtS-7F8

**Comment by TemporalOroboros** [comment]
I think it was decided that this was a feature when statues were being made.

**Comment by dragomagol** [comment]
It's the same with other mobs too, like frogs. And statues of people with basketballs will dribble, smokers' statues will smoke, etc

**Comment by cacogen** [comment]
I could be wrong but someone sculpted a tourist and I felt like them dragging it made the rolling noise they make

**Comment by Serxule** [comment]
this is a feature (yes an actual one)

**Comment by ATH1909** [comment]
feature
