### ISSUE TITLE
When producing helgrasp (the inverted helbital) you will get a chat message talking about the name of it in the code

### ISSUE THREAD

**Issue by gallywix4** [tgstation/tgstation#57502]
## Reproduction:
Make the inverted chem of helbital (helgrasp) and when you finish the mix you will receive a message saying you produced /datum/ chem/helgrasp (i believe that was the message however i can't find the logs for chemicals) while the expected result was to just say helgrasp.

**Comment by Serxule** [comment]
yeah that's being fixed
