### ISSUE TITLE
Food carts can call destory on their contents twice

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#57507]
Deleting some part of the cart causes the cart to properly delete its subportions. Doing this sends a signal that makes the cart delete its sub-portions again
QDELETING() will help out here
![image](https://user-images.githubusercontent.com/58055496/110229988-4e755680-7ec2-11eb-911f-9a83f883e8c5.png)

**Comment by Dorsisdwarf** [comment]
Destroy

**Comment by LemonInTheDark** [comment]
de-story

**Comment by LemonInTheDark** [comment]
I fixed this myself in #59612
Fucking food
