### ISSUE TITLE
if you make a new id you wont able to do cargo bounties

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#57516]
lose id
make new one and add new account and trim and access etc
you cant press new bounty botton as it says it lacks job assignment

**Comment by KathyRyals** [comment]
Tried to replicate this issue by making a new ID card on a private server and couldn't replicate it. Can you please try and explain the events leading up to it ?

**Comment by Tlaltecuhtli** [comment]
added bank account
added trim
added access

**Comment by Timberpoes** [comment]
```
	if(!pot_acc.account_job)
		to_chat(usr, "<span class='warning'>The console smartly rejects your ID card, as it lacks a job assignment!</span>")
		return FALSE
```

The bounty console uses the card's linked bank account's job datum.

A fresh ID card with a newly created bank account from the HoP's accounting machine probably lacks a job datum and thus is - According to the machine's logic - not viable to receive bounties.

Looks like this was specifically intended behaviour, so possibly not a bug at all.

**Comment by ATH1909** [comment]
> ```
> 	if(!pot_acc.account_job)
> 		to_chat(usr, "<span class='warning'>The console smartly rejects your ID card, as it lacks a job assignment!</span>")
> 		return FALSE
> ```
> 
> The bounty console uses the card's linked bank account's job datum.
> 
> A fresh ID card with a newly created bank account from the HoP's accounting machine probably lacks a job datum and thus is - According to the machine's logic - not viable to receive bounties.
> 
> Looks like this was specifically intended behaviour, so possibly not a bug at all.

well, the way I'd fix this would be to make bounties be tracked per bank account, instead of per ID card. they'd still be GENERATED according to the job of the ID card that's in the console when the "generate bounty" button is pressed, though.

**Comment by ArcaneMusic** [comment]
Bounty choices in the UI are made based off the job datum in order to pick a job-specific bounty.
Still, you should be able to get a blank ID card, add an account, and then add a job assignment to get that job's bounties.

**Comment by Sealed101** [comment]
[see this comment on some other issue](https://github.com/tgstation/tgstation/issues/61216#issuecomment-2353329017)
