### ISSUE TITLE
plasma overlay stuck in space?

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#57513]
https://i.imgur.com/PUqCWIZ.png

there was a passive vent putting plasma in space south of it 

https://scrubby.melonmesa.com/round/157729

**Comment by LemonInTheDark** [comment]
are you referring to 
![image](https://user-images.githubusercontent.com/58055496/110236144-103f5d80-7ee9-11eb-86bd-1e0483b99be6.png)?

**Comment by Tlaltecuhtli** [comment]
https://i.imgur.com/807cRJO.png

**Comment by LemonInTheDark** [comment]
Was there plasma on the cargo shuttle or something? I know there's an issue with overlays not updating introduced in my sleeping rework, but I don't know where it is

**Comment by Tlaltecuhtli** [comment]
there was a passive vent pumping plasma on top of lattice in the space area  the shuttle was away for 10 min

**Comment by timothymtorres** [comment]
Just to clarify from those images - there appears to be plasma in those space tiles when space should automatically delete/vent any gas.  I think what happened is the shuttle deleted the the tile the vent is on.  The plasma still lingers on the space tile?

**Comment by LemonInTheDark** [comment]
Potentially linked to https://github.com/tgstation/tgstation/pull/59817. I'd like to see a recent replication of this
