### ISSUE TITLE
You thought you were done with autolathe material bugs? Think again.

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#57548]
## Reproduction:
1. Build a three tile long conveyor belt
2. Put an autolathe with t3 parts on one end
3. Put a recycler with t3 parts on the other end
4. Activate the conveyor belt
5. Print foam riot dart boxes
6. :trollface:

**Comment by ArcaneMusic** [comment]
So do boxes of foam darts need the same material content folding that ammo boxes got in #55095?

**Comment by Qustinnus** [comment]
we need to remove parts from anything doing with multiplying output of machines like recyclers, autolathes, processors and gibbers it's been a problem since I've started coding here.

**Comment by Kylerace** [comment]
> 
> 
> we need to remove parts from anything doing with multiplying output of machines like recyclers, autolathes, processors and gibbers it's been a problem since I've started coding here.

not the issue, autolathes only have the material cost of the actual item it makes subtracted from it even if it populates its contents with items that recycle into materials, but the recycler eats everything in contents. both the autolathe and recycler max out at 100% efficiency
