### ISSUE TITLE
Tranquility can be synthed (You can get it in BOTANY, AGAIN, OH GOD)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#57556]
## Round ID:

[157833](https://scrubby.melonmesa.com/round/157833)

![image](https://user-images.githubusercontent.com/51863163/110395466-cd3dd100-8033-11eb-8f82-f40d69f45764.png)

https://github.com/tgstation/tgstation/blob/e3d689344f83652f4c17ea0476d5ea126cfdf8d2/code/modules/reagents/chemistry/reagents/other_reagents.dm#L2362-L2368

**Comment by Timberpoes** [comment]
Likely as a result of https://github.com/tgstation/tgstation/pull/56891

Anyone looking to fix this may also find it worthwhile scanning through that PR to make sure we didn't flag any other bad chems for synth.

**Comment by cacogen** [comment]
>Better to curate chems by requiring the flag than otherwise. That's less prone to errors, or at least the errors are less likely to be catastrophic.

**Comment by prodirus** [comment]
Did a quick scan of all the chems, didn't seem like there are any more bad chems that weren't already fixed by previous PRs.
