### ISSUE TITLE
(Ice box) Paramedics don't have access to cargo roundstart

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#57586]
Reporting client version: 513.1536

## Round ID:
irreverent

## Testmerges:
- [Rule Botannia: British Bots for the Restaurant](https://www.github.com/tgstation/tgstation/pull/57542)
- [Status Bar: Reloaded: Revengeance - Back to Perfection](https://www.github.com/tgstation/tgstation/pull/57531)

## Reproduction:
1. be a paramedic
2. be on ice box
3. try to enter cargo
4. fail.

**Comment by Zytolg** [comment]
I should mention that Paramedics were able to access Cargo from maintenance last time I tested this. It's still a consistency issue but the problem should only apply to the main cargo doors on Icebox.

**Comment by TheBonded** [comment]
Something to note, they do have access to the windoor on the counter. Another thing is, giving people cargo access on meta (or was it delta? the one with cargo on the north west corner) will give them access to the windoors but not the doors. indeed odd

**Comment by msgerbs** [comment]
The cargo doors on Ice are set as Mailroom access, and Meta's mailroom doors are set as Cargo/Mining access while the windoors are properly set as mailroom.
