### ISSUE TITLE
An oddity in a round end report

### ISSUE THREAD

**Issue by GlueSniffer** [tgstation/tgstation#57584]
Reporting client version: 513.1542

## Round ID:
[157862](https://scrubby.melonmesa.com/round/157862)

## Testmerges:
Use better layout for verbs in stat panel by stylemistake
(doubt the testmerge is related to the oddity in the round end report)

## Reproduction:
Not sure if this is exactly a way to reproduce it, but here is what happened:

I was a heretic with the objectives of protecting both a scientist and engineer on the station, I discovered that the engineer whom I was protecting was a traitor so we worked together to complete our objectives. After completing our objectives (and me doing a rust ascension) the three of us escaped together on the escape shuttle. Despite being all alive and on the shuttle when the round end report showed up, the round end report stated simultaneously that I did not survive the events on the station, that I had failed to protect the traitor engineer, and that the traitor engineer survived.

I'm not sure what caused the strange round end report but if anyone has any questions about the round, I  would be happy to answer.

**Comment by Dorsisdwarf** [comment]
Weird

**Comment by Mooshimi** [comment]
Protection objectives seem to just be broken from what I've been seeing

**Comment by timothymtorres** [comment]
This was fixed with #61037
