### ISSUE TITLE
CQC grab does not check range

### ISSUE THREAD

**Issue by rdragan** [tgstation/tgstation#57582]
Reporting client version: 513.1542

## Round ID:
[157888](https://scrubby.melonmesa.com/round/157888)

## Reproduction:
1. Join as Cook 
2. Go to the Kitchen
3. Ctrl-Click anyone outside of melee range

https://user-images.githubusercontent.com/43266738/110544283-24c36600-8134-11eb-9e20-ba04ffb8834a.mp4

**Comment by ShizCalev** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/blob/7ebf3a128e33fb1bedc5b5cabe3cc181af98ecea/code/_onclick/click.dm#L452-L459
https://github.com/tgstation/tgstation/blob/cf0f215469ba1ee99961c51ad5e687a18a49e630/code/modules/mob/living/carbon/human/species.dm#L1323-L1333
https://github.com/tgstation/tgstation/blob/c122589940e03cc796456563c4238a40f6b3cfad/code/datums/martial/cqc.dm#L123-L139

the first Adjacent check shouldn't be passing in click.dm

**Comment by rdragan** [comment]
Nevermind, apparently this happens with any CQC. Yes, nukies can grab people through their shuttle's camera console. Yes.

**Comment by ATH1909** [comment]
> Nevermind, apparently this happens with any CQC. Yes, nukies can grab people through their shuttle's camera console. Yes.

you can also neck grab them or table slam them onto a table next to you to teleport them to you, even if you're on an entirely different z-level than them

**Comment by ATH1909** [comment]
when you do fix this, please don't accidentally remove extendo-hand cqc'ing/extendo-hand 3 tile suplexing, okay?

**Comment by Y0SH1M4S73R** [comment]
I didn't know chefs were Melee Marth.

**Comment by ArcaneDefence** [comment]
> 
> the first Adjacent check in click.dm shouldn't be passing

'cause it isn't lmao. 
https://github.com/tgstation/tgstation/blob/ecb00114fb510abc11522aecea7ee5a6f8133e84/code/_onclick/click.dm#L329-L334
https://github.com/tgstation/tgstation/pull/57131

**Comment by ATH1909** [comment]
also, according to some testing that spark did, instantly aggro grabbing someone using the STRONG_GRABBER trait won't trigger this bug (if you don't have CQC)

**Comment by necromanceranne** [comment]
> also, according to some testing that spark did, instantly aggro grabbing someone using the STRONG_GRABBER trait (from, say, being a leather golem) won't trigger this bug (if you don't have CQC)

So it's probably the line you posted. Alrighty.

**Comment by maxymax13** [comment]
assistants peacefully doing nothing in dorms? sounds like you're just a fucking greytider, come over here

**Comment by TheVekter** [comment]
I heard about this but didn't see it in action, this is way, way worse than I had imagined.
