### ISSUE TITLE
Chemical Plumbing: Connecting ducts in alternate layers to the default duct layer doesn't work

### ISSUE THREAD

**Issue by Kulik242** [tgstation/tgstation#57600]
Found this experimenting on my private server:

When placing ducts on different layers, wiki reads ''You can force two different colors to connect by click dragging them to each other while holding a wrench.'' This does work for the colored ducts. It doesn't work if one of those ducts is in the default grey layer.
Shown here:
https://ibb.co/KFTmZ1V

**Comment by Time-Green** [comment]
It's the layer, you can't force connect those (I tried to make it work, but it wasn't worth it). 
When looking at that image, you could've changed the input machines layer to the second layer with a plunger on alt-click or used a plumbing RCD. I'll add a section to the wiki about this because it's obviously still confusing for people

**Comment by Kulik242** [comment]
I've tried, alt-clicking on the plunger lets me select a layer. I can set it to Alternate Layer, but clicking on the input gate with it will still only plunge it and not change its layer. I tried it on both, secured and unsecured input gate. Please explain it a little better.

https://ibb.co/6J745MN

**Comment by Time-Green** [comment]
> I've tried, alt-clicking on the plunger lets me select a layer. I can set it to Alternate Layer, but clicking on the input gate with it will still only plunge it and not change its layer. I tried it on both, secured and unsecured input gate. Please explain it a little better.
> 
> https://ibb.co/6J745MN
> 
> I've messed with it some more and figured it out. Clicking a plunger (no ALT) changes it from plunge to layer mode, but it seems that it only works on the reaction chamber not the input gate.
> 
> I've also found that if I change the layer of the reaction chamber, I can't change it back.
> 
> AND, There is the issue that when you trying to connect reaction chamber in which you mixing a buffer to the reaction chamber in which the buffer needs to be used, how to connect the alternate layer yelow tube with the main port of the buffer mixing chamber? Like in the following picture, buffer is mixed in the chamber above me, and I need to connect it to the chamber bellow into the yelow port. The yelow-yelow connection below fits cause I've changed the layer, the yelow duct wont hovewer fit the main red port of the buffer mixing chamber.
> 
> https://ibb.co/4dtgFmh

There’s a multi-layer duct to connect those. It’s super crap, but there’s a PR up fixing some of the issues with layers. It should become easier to use then, because right now there isn’t a good way to connect across layers

**Comment by SuperNovaa41** [comment]
Not really a bug, moreso a quirk of the plumbing system. Also this has been vastly improved
