### ISSUE TITLE
Not choosing one of the three bounties and returning later to get a new one results in a negative cooldown message

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#57616]
![image](https://user-images.githubusercontent.com/51863163/110720272-e67d8380-81d3-11eb-90ca-71d182a7d42e.png)

- Go insert your ID and check your 3 bounty options.
- Be dis-satisfied with all three choices and take your ID out without choosing any of them.
- Return in over 5 minutes to grab a new bounty.
- Get told that you need to wait negative time to pick up a bounty. It will not let you choose a new bounty until you choose an old one, only then can you refresh your bounties.

**Comment by TheBonded** [comment]
Yeah, when you're dissatisfied, just choose one and come back to refresh later
