### ISSUE TITLE
can't grab pets

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#57618]
Reporting client version: 513.1542

## Round ID:
[157977](https://scrubby.melonmesa.com/round/157977)

## Reproduction:

can't grab pets, probably applies to all simple mobs but I couldn't check

**Comment by SuperNovaa41** [comment]
It's all simple mobs. including bots n shit

**Comment by WlarusFromDaSpace** [comment]
I would like to add that this only seems to be a problem with the Ctrl+click shortcut and not the Shift+rclick menu.

**Comment by prodirus** [comment]
There is an open PR that *should* fix this here: #57617
