### ISSUE TITLE
Grilled Cheese Sandwich is named in code as "cheese sandwich" and is not, in fact, grilled.

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#57637]
## Reproduction:
<s>If you put a cheese sandwich on a griddle it sets the sandwich on fire and burns it. Putting the same sandwich in the microwave also seems to make a burned mess.
Expected behavior: a grilled cheese sandwich naturally results from grilling a cheese sandwich</s>

The item in sandwich code as /grilledcheesesandwich is in fact the "cheese sandwich" and is not made using the griddle, it is table crafted.

**Comment by ArcaneDefence** [comment]
Truly the most grievous of offenses.

**Comment by maxymax13** [comment]
literally unplayable

**Comment by YakumoChen** [comment]
Upon reviewing the relevant code I have discovered a problem even more heinous than this tragedy.
