### ISSUE TITLE
Nicotine is completely nonaddictive

### ISSUE THREAD

**Issue by AdmiralPancakes1** [tgstation/tgstation#57631]
## Round ID:

Any

## Testmerges:

Doesn't matter

## Reproduction:

Take smoker quirk. Suffer absolutely no withdrawal symptoms. Enjoy your four free quirk points.

**Comment by prodirus** [comment]
https://github.com/tgstation/tgstation/blob/3324a707845757bffa6ce163713efab9ff654776/code/modules/reagents/chemistry/reagents/drug_reagents.dm#L37-L47

Needs `addiction_type` set to one of the addictions defined in `generic_addictions.dm`, most likely to `stimulants` (or a new addiction type altogether?).
