### ISSUE TITLE
Apparently, plasmamen that spawn hungover don't spawn with internals active

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#57642]
## Round ID:

#158023

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/110853973-e46e0000-8279-11eb-96de-0a462a9988ae.png)

![image](https://user-images.githubusercontent.com/51863163/110853960-de781f00-8279-11eb-975b-aa7f831a23f5.png)

**Comment by Bluedazzled** [comment]
I would like to add on to this with the paraplegic trait not spawning you with a wheelchair
