### ISSUE TITLE
Taking things out of nested containers does not properly unset IN_STORAGE flag

### ISSUE THREAD

**Issue by maxymax13** [tgstation/tgstation#57648]
## Round ID:
no

## Testmerges:
no

## Reproduction:
~~Put stuff in a box. Put that box in your bag. Drag the box from your bag onto a floor tile. The items on the floor will have tooltips as if they were in a slot. Doesn't happen if the box is in your hand.~~
Put a box in your bag. Put something in the box. Take something out of the box and drop it.
![image](https://user-images.githubusercontent.com/38844529/110885002-d1cce880-82c4-11eb-8a87-da7aada223e3.png)

**Comment by SuperNovaa41** [comment]
No longer an issue
