### ISSUE TITLE
Character will not update time played

### ISSUE THREAD

**Issue by Visorak06** [tgstation/tgstation#57650]

**Comment by LemonInTheDark** [comment]
This is an issue with the /tg/station servers, and not our code. It's being worked on, but there's nothing we can do to fix it.

**Comment by Visorak06** [comment]
Well that's disappointing. I assume there's no timetable on it, so is there anything I can do to get slightly more role access or am I just stuck playing basic crew roles until that's resolved? Can I make another character and it'll fix itself or is it account based issues? Thanks for your time regardless.

**Comment by dragomagol** [comment]
You can ahelp and an admin will be able to remove the time locks for certain jobs.

**Comment by Visorak06** [comment]
Thank you, I'll do that.
