### ISSUE TITLE
Contractor tablet bugs out if you cant get to the pod in time

### ISSUE THREAD

**Issue by Sevaaas1** [tgstation/tgstation#57655]
Round ID:[158040](https://scrubby.melonmesa.com/round/158040)

 Reproduction:

1) Get your target and go to the point
2) Call the pod
3) Fail to kidnap the target for whatever reason
4) The pod gets automatically destroyed and the button to call another one is greyed out

I tried rerolling targets, but even with that i was still stuck with the same contract unable to call the pod (This was gonna be the second kidnapping)

**Comment by SuperNovaa41** [comment]
why would you call the pod before kidnapping the target?
