### ISSUE TITLE
Overflow bureacracy mistake makes anyone who has any level of the affected job enabled, be that job (also there's a typo in its name)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#57662]
## Reproduction:

If Overflow bureaucracy mistake triggers, anyone who was any level of the selected overflow job are thrown into that job. For example, having chef on "LOW" and having overflow bureaucracy trigger on chefs forces you into the chef job, causing a ton of people to get jobs they don't expect to get at all.

Also, it's titled "Overflow bureacracy mistake" in game - bureaucracy is spelt wrong.

**Comment by Paxilmaniac** [comment]
the first part probably happens because it sets the job to a yes/no option, which overrides all other jobs

**Comment by SuperNovaa41** [comment]
That is infact, the entire point of that station quirk
