### ISSUE TITLE
Borgs cannot properly close most morgue trays. (Cannot click on the tray of the tray)

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#57676]
## Reproduction:
![image](https://user-images.githubusercontent.com/62538745/111011852-6173a500-8360-11eb-8513-b07393e062a0.png)
Three morgue trays are in a row, against a wall. You can open them, but you can only close the ones on the end as you're unable to click the trays themselves. This typically leaves the middle-ones closed, since you cannot click on the morguetray-machine to get it to close without closing yourself into it.

The trays themselves don't seem to be operable to sillycon anymore!

**Comment by ATH1909** [comment]
I think this happens for 'umies too, but I could be wrong.

**Comment by ZeroMODE0** [comment]
Clicking on trays as Humies works just fine, luckily!
![image](https://user-images.githubusercontent.com/62538745/111012722-9a147e00-8362-11eb-96ea-07c3a9700baf.png)
![image](https://user-images.githubusercontent.com/62538745/111012730-9e409b80-8362-11eb-8aa8-0f5a7203c7bd.png)

**Comment by ATH1909** [comment]
hm, interesting

**Comment by SuperNovaa41** [comment]
I know this used to be broken, but it's fixed now!
