### ISSUE TITLE
Another food issue

### ISSUE THREAD

**Issue by Mrfilms** [tgstation/tgstation#57675]
Reporting client version: 513.1541

## Round ID:
[158088](https://scrubby.melonmesa.com/round/158088)

## Testmerges:
- [tram hotfix hopefully maybe](https://www.github.com/tgstation/tgstation/pull/57646)

## Reproduction:

It would seem that fried foods are not edible - tested with burrito, egg wrap, cutlet and bun - none were edible after frying.
I would assume it's another issue related to the food rework.

**Comment by SuperNovaa41** [comment]
I believe these have been fixed.
