### ISSUE TITLE
Clown cars opening airlocks with a passenger's access doesn't update airlock icon right

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#57697]
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
https://streamable.com/g079mn
Yoink some dude
Try to open an airlock that ain't in your own ID
Airlock does the funny

**Comment by dragomagol** [comment]
Probably the same as #56420

**Comment by Sealed101** [comment]
can no longer reproduce, probably fixed by #83952 as it was aiminig for a similar issue with fireman carrying and bumping airlocks
