### ISSUE TITLE
something's funky with the junkie quirk and addictions

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#57695]
![image](https://user-images.githubusercontent.com/42606352/111053909-939f0880-842d-11eb-8aae-7f31fabf0f02.png)

I coulda sworn that this had already been reported (since it sounded familiar), but I couldn't find another issue report about it on Github, so I made this one.

**Comment by Ryll-Ryll** [comment]
#57705 is a better version of this issue report
