### ISSUE TITLE
Smoking cigarettes never gives you enough nicotine to stop the effects of addiction

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#57699]
## Round ID:

[158167](https://scrubby.melonmesa.com/round/158167)

## Reproduction:

Because smoking only gives you a tiny amount of nicotine per tick / per smoke, the only way to get enough nicotine to stave off the effects of addiction is by drinking 2+ units of liquid nicotine. This means smokers (who spawn addicted) have no way to prevent the addiction effects, and chainsmokers gain tons of points without being able to stop it.

**Comment by Ryll-Ryll** [comment]
I know this came first but I already closed another issue report in favor of #57705 and that one has a picture and a comment so I'm gonna close this as well
