### ISSUE TITLE
Something is very wrong with smoker perk / nicotine addiction

### ISSUE THREAD

**Issue by CASHNOW** [tgstation/tgstation#57705]
## Round ID:
[158174](https://scrubby.melonmesa.com/round/158174)

## Reproduction:

Joined late to the round. In the time it took to travel to the shuttle down the halls to my department I had became massively withdrawn from nicotine. I had 3 nicotine related moodlets. Even consuming directly 50 units of liquid nicotine did nothing to satiate. Later, I asked an admin to spawn me in at centcom with some smokes and a grinder so I could collect some info. With a timer up I got about 50 seconds in before I was massively withdrawn from nicotine. Yet again I tried liquid nicotine, I even got the moodlet message that I had overdosed on nicotine, yet the withdrawal did not go down.

A picture of the triple whammy of a negative moodlet after 50 seconds.
![bGxKMmB](https://user-images.githubusercontent.com/36146531/111059774-35c5ed00-843c-11eb-8783-81cb697196a6.png)qa

**Comment by prodirus** [comment]
oh god oh fuck, working on a fix now

**Comment by dragomagol** [comment]
Hopefully fixed by #57826

**Comment by tralezab** [comment]
i'll mark it
