### ISSUE TITLE
The Sekrit Admin Button To Change Everyone's Race Actually Just Turns Everyone Into A Traitor

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#57702]
## Reproduction:
1. Enter the secrets panel
2. Go to the "only fun for you" section
3. See the button to change everyone's race
4. Click it and see that it asks you for an objective
5. Enter an objective and hit ok
6. Everyone is now a traitor, and still their same race
7. :trollface:
8. Not only has the button made everyone an antag, you didn't even get to turn everyone into an abductor

**Comment by Mothblocks** [comment]
i do like that u saw that it asked for an objective and just thought "well this is probably normal"

**Comment by Mothblocks** [comment]
@tralezab

**Comment by ATH1909** [comment]
can we get this added to the fuckup of the year 2021 list
