### ISSUE TITLE
Tram left behind its control console after getting bombed, but still could move back and forth

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#57708]
## Round ID:

[158180](https://scrubby.melonmesa.com/round/158180)

## Testmerges

Tram fix pr was testmerged

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/111061396-d6320680-8468-11eb-920c-6ebf2cac0830.png)
The tram was hit with the outskirts of an explosion which shattered the console but didn't completely break it. Re-applying the glass and re-screwing the console finished the tram console, and the tram console worked, and the tram worked, but the tram console did not follow the tram.

**Comment by TheBonded** [comment]
This is because anything created on the tram is considered not on the tram unless it it pulled onto the tram. This happens with spawning syndie bombs on the tram as well, also wil placing folded wheelchairs, body bags, or skateboards.

**Comment by SuperNovaa41** [comment]
Fairly certain this doesn't actually happen anymore
