### ISSUE TITLE
Tram lit anyone who stepped onto it on fire after it was nearly bombed

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#57709]
## Round ID:

[158180](https://scrubby.melonmesa.com/round/158180)

## Testmerges:

Tram fix PR was testmerged

## Reproduction:

Tram got hit with the outskirts of a bomb. What followed was the tram became the hell tram. Stepping on any of the tram tiles lit you on fire. 

https://user-images.githubusercontent.com/51863163/111063112-e521b480-847a-11eb-9a6d-9b0ae14bf7b5.mp4

**Comment by Dorsisdwarf** [comment]
Tram bugs never get old

**Comment by timothymtorres** [comment]
@MrMelbert Im assuming this is no longer happening?

**Comment by MrMelbert** [comment]
probably not an issue anymore
