### ISSUE TITLE
Voluntary scream emote not working

### ISSUE THREAD

**Issue by ModDownloading** [tgstation/tgstation#57719]
Trying to use the *scream emote doesn't actually cause you to make a scream sound, only involuntary screams seem to produce sound. When I was testing my lizard scream PR I was using syndicate paper airplanes to make the subjects scream so I didn't notice this issue at first.

The good news is it doesn't look like my PR (#57549)  caused an issue with the scream code, since when I loaded up tgstation source code from before my PR was merged the issue was still there. The bad news is that I have no clue what is causing voluntary screams to not produce sound.

Not sure if this is just a client-side issue or server-side, but if it's the former I tried this on both the stable and beta versions of BYOND and it's still there.

EDIT: After testing this on Sybil with Boris, it looks like this is indeed a server-side not client-side issue, and also does not extend to any involuntary screams, as lopping off limbs still produces a scream sound. On top of this, it appears that the issue is present in all races' screams (or at least humans/felinids, lizards, moths, monkeys and presumably ethereals since they're the only ones with screams). This makes it seem that the issue is somewhere in the scream emote code itself.

EDIT 2: The message "[player] screams!" still prints after using *scream, only the sound is missing. Maybe this has something to do with people getting the simplemob version of the scream instead of the player version when they put in *scream but not when a command runs emote("scream") directly?

**Comment by RaveRadbury** [comment]
AFAIK this is intentional, as scream spamming is annoying.

Other codebases have done something like screams causing oxyloss and only being able to scream above certain oxyloss thresholds.

🤷

**Comment by Mothblocks** [comment]
This is intentional, yeah.

**Comment by ModDownloading** [comment]
@RaveRadbury @Mothblocks If I were to PR something to merge the oxyloss screams instead, would you be willing to at least consider it?

**Comment by Mothblocks** [comment]
I'd personally say no, I'm already a bit jaded by how often emotes are abused presently.
