### ISSUE TITLE
Kisses Can Remove Shields, Damage Space Suits, Remove Adbuctor Disguises, and More

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#57723]
Kisses are a projectile, and as such they can trigger a number off odd things; they can drop an abductor disguise, remove shielded hardsuit charges, break changeling shields, make riot shield strobes go off, set off reactive teleport armor, drop ninja stealth, and break the fragile space suit.

Love is powerful and this is utterly hilarious, but this probably shouldn't happen for a lot of these things.

## Reproduction:

Blow a kiss at someone with a shielded hardsuit or anything above (or anything that as a `hit_reaction` in general) and observe 🎶the power of love🎶

**Comment by ModDownloading** [comment]
When this gets fixed, make sure the changes are applied only if it isn't Valentines Day.

**Comment by ATH1909** [comment]
feature

**Comment by ATH1909** [comment]
note that the *kiss emote has the default emote cooldown of 0.8 seconds (to be contrasted with the normal 0.4 second click cooldown from shooting a gun). for most of these effects, you're better off using even a laser tag gun.

**Comment by Fox-McCloud** [comment]
>note that the *kiss emote has the default emote cooldown of 0.8 seconds (to be contrasted with the normal 0.4 second click cooldown from shooting a gun). for most of these effects, you're better off using even a laser tag gun.

The CD is 3 seconds now,  but still..

Not everyone has access to a laser tag gun though; they're still fairly limited.

A small group people spamming kiss in a particular direction is something that's unlimited, has no need to be recharge, and can't really be disarmed either (aside from killing the user). As funny as it would be to have assistants lining up in kiss squads to take out nukie shields, I don't think this is a good gameplay loop---it also doesn't prevent the use of a gun either, so you can easily use it on the fly in one hand and a gun in another.

This also plays into how *kiss works; you can pre-charge it, with one in each hand, and the cooldown expired, so you can quickly get a 3-burst kiss off; enough to completely remove the shield from a hardsuit; this would actually be *more* effective than a lasertag gun in some circumstances.

**Comment by ATH1909** [comment]
> A small group people spamming kiss in a particular direction is something that's unlimited, has no need to be recharge, and can't really be disarmed either (aside from killing the user). 

Just prying up and throwing floor tiles should be able to do most of this too, though.

> As funny as it would be to have assistants lining up in kiss squads to take out nukie shields, I don't think this is a good gameplay loop---it also doesn't prevent the use of a gun either, so you can easily use it on the fly in one hand and a gun in another.

Note that kissers aren't gun subtypes, so you can't use dual-wielding to fire them at the same time that you fire another gun.

> This also plays into how *kiss works; you can pre-charge it, with one in each hand, and the cooldown expired, so you can quickly get a 3-burst kiss off; enough to completely remove the shield from a hardsuit; this would actually be _more_ effective than a lasertag gun in some circumstances.

Honestly, if you can find a situation that *kiss is actually viable to use in and remember that it exists, you deserve to get rid of that nukie shield or whatever. I personally like the idea of *kiss being added to the unarmed viber's toolkit as a "weapon" that doesn't require you to go out and tide for something, but is only useful against specific types of enemies/equipment setups.

**Comment by necromanceranne** [comment]
I brought this up to ryll day one, by the by.

**Comment by Mothblocks** [comment]
> I personally like the idea of *kiss being added to the unarmed viber's toolkit as a "weapon" that doesn't require you to go out and tide for something, but is only useful against specific types of enemies/equipment setups.

he wrote this seriously

**Comment by ATH1909** [comment]
> > I personally like the idea of *kiss being added to the unarmed viber's toolkit as a "weapon" that doesn't require you to go out and tide for something, but is only useful against specific types of enemies/equipment setups.
> 
> he wrote this in earnest

It's a nifty piece of knowledge that you can use in niche situations to make people go "wow, I never thought of that" that doesn't tip the scales too far in your favor. I like it.

**Comment by Ryll-Ryll** [comment]
I was gonna fix this by making shielded suits ignore nodamage projectiles but they're implemented in two different places for shielded hardsuits and shielded cult robes. The real solution is to make a shielded component, but I haven't gotten around to it yet because it requires icon messiness. I'll probably do it this week

**Comment by TheBonded** [comment]
I like the idea of abductors getting undisguised by kisses, like how syndie borgs get undisguised by pats. Shields are an issue, though
