### ISSUE TITLE
Getting addicted on nicotine sends you into an unescapable death loop

### ISSUE THREAD

**Issue by maxymax13** [tgstation/tgstation#57739]
## Round ID:
[158228](https://scrubby.melonmesa.com/round/158228)

## Testmerges:
#57646 
#57605 

## Reproduction:
step 1. get addicted on nicotine
step 2. voices in head ask for more nicotine
step 3. consume more nicotine, still have negative moodlets, wtf
step 4. spend rest of round simultaneously having withdrawals on and overdosing on nicotine, something about not getting enough of the reagent at once
![dreamseeker_G4vI6FYilD](https://user-images.githubusercontent.com/38844529/111114875-a5260480-8542-11eb-91fc-75ed196b2833.png)
![unknown-144](https://user-images.githubusercontent.com/38844529/111114891-aa834f00-8542-11eb-8a91-f4ccd9d50eed.png)

**Comment by ArcaneDefence** [comment]
Presumably fixed by https://github.com/tgstation/tgstation/pull/58170
