### ISSUE TITLE
Bath Salts stun immune inconstancy

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#57747]
## Reproduction:
Bathsalt doesnt give you stun immunity for first ~3 seconds when used and doesnt remove already applyed stuns. I thought it was a problem of time dilation but stun immunity is a part of Martial Art.

**Comment by SuperNovaa41** [comment]
No Chem will remove an already applied stun fully just because they're immune to stuns, you need Stam Regen (bathsalts does have this, but that still doesn't provide an instant recover from stuns).

As for the no stun immunity for 3 seconds that may be an actual issue

**Comment by SuperNovaa41** [comment]
I'm fairly certain this is just a matter of how you consumed the reagant + the time it takes to metabolise it. Testing on local and on live doesn't result in anything other than what should be expected
