### ISSUE TITLE
Roundstart vents/airpipes pressure

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#57748]
## Reproduction:

Roundstart vents have too high pressure and airpipes have too low pressure and no breathable air, which makes impossible to play as monkey/slime.

**Comment by LemonInTheDark** [comment]
I'm confused, is the issue that airpipes aren't breathable at roundstart? what's the problem here

**Comment by Livrah** [comment]
I remember pipes was fine to ventcrawl as a monkey.

**Comment by LemonInTheDark** [comment]
This isn't an issue. I'm also not really sure what you're complaining about, someone most likely over-pressurized distro
