### ISSUE TITLE
welding masks dont protect moths from flashes/welding now

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#57754]
## Reproduction: try to weld/flash with welding mask as a moth, still get blinded.

**Comment by TheBonded** [comment]
Did you put the welding mask down?

**Comment by Serxule** [comment]
> Did you put the welding mask down?

yes, I'm not stupid.

**Comment by ATH1909** [comment]
oh no

**Comment by Time-Green** [comment]
Wasn’t this a feature where moths had sensitive eyes and needed two layers of welding protection?

**Comment by TheBonded** [comment]
> Wasn’t this a feature where moths had sensitive eyes and needed two layers of welding protection?

Doesn't putting two layers of protection make you blind while you have them both? (ie wearing a welding helmet and sunglasses at the same time makes you get the blind popup in the top right of the screen)

**Comment by TheBonded** [comment]
> Wasn’t this a feature where moths had sensitive eyes and needed two layers of welding protection?

Doesn't putting two layers of protection make you blind while you have them both? (ie wearing a welding helmet and sunglasses at the same time makes you get be blind popup in the top right of the screen)

**Comment by TheBonded** [comment]
> Wasn’t this a feature where moths had sensitive eyes and needed two layers of welding protection?

Doesn't putting two layers of protection make you blind while you have them both? (ie wearing a welding helmet and sunglasses at the same time makes you get the blind popup in the top right of the screen)

**Comment by TheBonded** [comment]
> Wasn’t this a feature where moths had sensitive eyes and needed two layers of welding protection?

Doesn't putting two layers of protection make you blind while you have them both? (ie wearing a welding helmet and sunglasses at the same time makes you get be blind popup in the top right of the screen)

**Comment by Time-Green** [comment]
You okay there man?

**Comment by Serxule** [comment]
> Wasn’t this a feature where moths had sensitive eyes and needed two layers of welding protection?

no, its just that normal sunglasses etc don't work, but welding protection does

**Comment by dragomagol** [comment]
I thought this was always the case, unless you're saying they go blind immediately?

**Comment by TheBonded** [comment]
> You okay there man?

Data bad, sent the same comment thrice

**Comment by TheBonded** [comment]
> I thought this was always the case, unless you're saying they go blind immediately?

Normally, when moths wear a welding helmet, or sunglasses, they become immune to flashes

**Comment by Mothblocks** [comment]
Sunglasses do not protect moths from flashes nor welding. What has historically protected moths is welding masks.

**Comment by Mothblocks** [comment]
![image](https://user-images.githubusercontent.com/35135081/111420058-c3594500-86a7-11eb-8809-fb1da3023d0e.png)

Works fine for me. Are you sure your eyes were working?
