### ISSUE TITLE
Turning tram into yeet machine

### ISSUE THREAD

**Issue by Low3** [tgstation/tgstation#57768]
## Reproduction:
1. Get into tram and call it to other station.
2. Without closing tram window get back to where it left from.
3. Press the button to call it and wait for it to arrive and enter it.
4. If you haven't closed tram interface you can see now that it shows tram being on another station.
5. Send tram to place its at.
6. Get yeeted.

GIF is recorded on skyrat, but this bug was reproduced on TG too (aslo streamable is banned in my country, so enjoy GDrive)
https://drive.google.com/file/d/1_FgRMRHd65-7Y2g1wc5rxJ6ZsVpVE-lL/view

**Comment by tralezab** [comment]
fixed by #57646

**Comment by MMMiracles** [comment]
This has been fixed, should be closed.
