### ISSUE TITLE
Sillicons cannot interact with electronics that do not have shortcuts.

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#57760]
## Round ID:
[158315](https://scrubby.melonmesa.com/round/158315)

## Reproduction:
(This has happened four rounds in a row)
Be sillicon
Cannot click on anything
![image](https://user-images.githubusercontent.com/62538745/111273203-85a1e100-8601-11eb-919b-b3822fdaf619.png)
literally a door opener
borgs can't recharge either

**Comment by LemonInTheDark** [comment]
Linked pr is merged

**Comment by ZeroMODE0** [comment]
^ Yeah, it fixed this.
