### ISSUE TITLE
highlight chat doesn't work with more than one word

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#57782]
I can't seem to make chat highlight work. The only thing that seems to do anything is a comma after the first word making the first word work (as stated by the feature) but no amount of spacing or commas after that point seems to make the second or any thereafter word highlight

## Reproduction:
![image](https://user-images.githubusercontent.com/10399117/111428297-35a14800-86ef-11eb-8068-6052a8588c39.png)

**Comment by JJRcop** [comment]
From #52426
> If using the highlighting feature, it highlights the whole message as well as the matching word.

Matching each word is not intended behavior.

**Comment by YakumoChen** [comment]
@JJRcop that's not the issue, it's not hilighting words outside of the first input word

**Comment by JJRcop** [comment]
> @JJRcop that's not the issue, it's not hilighting input words outside of the first input word. You can see there that "help" is not hilighted despite it being an input word and in the message screenshot

That is exactly what I mean, but I wasn't specific enough. This feature was not designed to do this, so this isn't a bug, just a design decision.

@stylemistake ?

**Comment by stylemistake** [comment]
It's a bug.

**Comment by TheBonded** [comment]
Yeah, it's bugged and only accepts every other word. For example: [Michael, Ian, Scofield, Renault], would highlight Michael and Scofield. It would not highlight Ian, or Renault, though. So just type in every word you want to highlight twice, so [Michael, Scofield] would become [Michael, Michael, Scofield, Scofield] to work @YakumoChen

**Comment by stylemistake** [comment]
Place to fix if anyone wants:

https://github.com/tgstation/tgstation/blob/master/tgui/packages/tgui-panel/chat/renderer.js#L195

This is a global regex instance with a /g flag, which gets reused a lot, and that causes problems.

Or it could be mishandling of that regex in replaceTextInNode.js (in the same folder). Global regex cursor must be reset back to 0 between function calls.
