### ISSUE TITLE
Creating or loading custom equipment for TGUI Select Equipment doesn't update the Custom tab

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#57792]
Reporting client version: 513.1537

## Round ID:
[158417](https://scrubby.melonmesa.com/round/158417)

## Testmerges:
- [Remove no tick check flag from SSshuttle](https://www.github.com/tgstation/tgstation/pull/57605)

## Reproduction:
Sorry if that title is a massive clusterfuck.

Open the new TGUI Select Equipment, go to the Custom tab
Hit "Create a custom outfit"
The Outfit Manager tab opens, and allows you to either create a new outfit or load one from file
Creating or loading in a custom outfit doesn't update the Select Equipment tab, which requires you to either close and reopen or hit "Create a custom outfit" again to update

**Comment by stylemistake** [comment]
@TriggeredBoi

**Comment by stylemistake** [comment]
I think this is by design, UI doesn't get any external update because that window is outside of tgui's domain, and autoupdate is disabled.

**Comment by TriggeredBoi** [comment]
Ah yeah, I both noticed this and found a (very ugly) way to make the Outfit Manager update the UI, but apparently my dumb ass forgot to implement it in the final thing
