### ISSUE TITLE
tgstation issue

### ISSUE THREAD

**Issue by Dencoop** [tgstation/tgstation#57802]
I have a problem with Dream Maker. It is written there
tgstation.dmb - 8 errors, 0 warnings (3/18/21 7:12 pm)
Because of this, no dmb file is created. I do not know what caused the problem, please help.
![Error](https://user-images.githubusercontent.com/28538571/111641530-11dd1f80-881f-11eb-80df-08d12be26982.png)
Can't upload game files, they are too big. I downloaded from this link https://github.com/tgstation/tgstation
![image](https://user-images.githubusercontent.com/28538571/111642468-ef97d180-881f-11eb-8a62-1f0dcb7be3f2.png)

**Comment by Serxule** [comment]
you need to run build.bat which will download the stuff you need for it to run correctly

**Comment by rdragan** [comment]
This is not a support forum.

If you're having trouble setting up a dev environment you should go ask on discord in the coding channel or on the tgstation forums.

**Comment by Dencoop** [comment]
> you need to run build.bat which will download the stuff you need for it to run correctly

Well i ran build.bat but it didn't help anyway. build.bat doesn't create dmb file cause of 7 total errors.
