### ISSUE TITLE
Directional windows don't count as "airtight" despite the fact that they certainly are

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#57816]
## Reproduction:

1. Create a room using directional glass panes insulating your room from space
2. Observe the station blueprints refuse to acknowledge that your airtight room is airtight

Furthermore, I discovered that if you manage to make a window without plating under it it refuses to acknowledge it as an airtight room, this might be an "oh well", but I felt it worth mentioning, the directional glass thing DEFINITELY should be fixarinoed.

**Comment by Sealed101** [comment]
unless there was a missed step in constructing/mooring the window panes down to the plating/ground, i see no reason why this would fail; testing does not reproduce this issue.
