### ISSUE TITLE
Letting a monkey pick up a mind magnification helmet spams ghost polling and destroys the helmet

### ISSUE THREAD

**Issue by Y0SH1M4S73R** [tgstation/tgstation#57821]
If you let a monkey pick up a mind magnification helmet of their own volition, something about monkey AI causes ghosts to be polled twice a second, and the helmet gets destroyed the second time the ghosts are polled this way.

JFC monkey AI isn't just spaghetti code, it's nuclear spaghetti code.

**Comment by TheBonded** [comment]
does this happen if you force one into their hands?

**Comment by timothymtorres** [comment]
Both this issue and #67799 were fixed by: #58394 but the author never finished his PR.  I'm going to mark this as Good First Issue since the solution is already there.

**Comment by Sealed101** [comment]
monkeys have lost interest in both picking up and wearing/activating those helmets. perhaps it's for the best
