### ISSUE TITLE
Tendril Chest Voodoo Doll Bug

### ISSUE THREAD

**Issue by D34DLord** [tgstation/tgstation#57840]
Reporting client version: 513.1542

## Round ID:
[158543](https://scrubby.melonmesa.com/round/158543)

**Comment by Serxule** [comment]
wow, dipshit "me delete" coders made a bug with a rushed delete, how unsurprising

**Comment by SuperNovaa41** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/57839
