### ISSUE TITLE
Mobs that have loc=null found in mob list

### ISSUE THREAD

**Issue by Alek2ander** [tgstation/tgstation#5785]
This causes a bunch of runtimes all over the place. I added debug output to get_turf to report such events and got 3 kinds of mobs that this happens to. All 3 are connected to objects that can be qdelled.

```
 ## WARNING: mob with loc = null. Name:Killer Tomato; Type:/mob/living/simple_animal/hostile/killertomato; In mob list:YES
 ## WARNING: mob with loc = null. Name:Touka Kirishima; Type:/mob/living/carbon/brain; In mob list:YES
 ## WARNING: mob with loc = null. Name:Drone (959); Type:/mob/living/simple_animal/drone; In mob list:YES
```

Also walking mushrooms

**Comment by Miauw62** [comment]
this should probably be open for a while.

**Comment by phil235** [comment]
Any new occurences of this happening?
