### ISSUE TITLE
Errornously denied manifests are worth more than correctly approved manifests (and other oddities)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#57862]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/111886585-bdf84500-899c-11eb-88bb-7c670961498c.png)

A manifest that is correct and stamped correctly is worth 80 credits
A manifest that is correct but stamped incorrectly is worth `CARGO_CRATE_VALUE - order_cost` credits, which apparently is often more than 80 credits thanks to economics?
A manifest that is incorrect and stamped correctly is worth 0 credits (it's not even registered)
A manifest that is incorrect and stamped incorrectly is worth 0 credits (it's not even registered)

This actually means you can order a bunch of crates, deny all the manifests, and ship them back and make money.

**Comment by NanoCats** [comment]
Shit I've been stamping them with the QM stamp because I thought that was okay...

**Comment by ATH1909** [comment]
so you should stamp all of them using a denied stamp, regardless of whether or not they're right or wrong?

**Comment by NanoCats** [comment]
I don't know where, but there should be some kind of mini-guide on the stamps somewhere, maybe if you inspect a manifest or something? Make the computer complain if you the shuttle comes back without manifests on it?

I had no idea you were supposed to what, check them for accuracy then stamp _accordingly_? I didn't even know they existed for the longest time, then some rando cargo player taught me.

**Comment by MrMelbert** [comment]
there's a 5% chance that a crate arrives with an error
if the crate has an error...
- there's a 1% chance the destination station is wrong
- there's a 2% chance the listed contents are wrong
- there's a 4% chance the contained contents are wrong

If the manifest has any of the above errors, you are expected to use the deny stamp to deny the manifest and ship it back
if the manifest has no error, you can use ANY stamp to stamp it and it is valid

**Comment by NanoCats** [comment]
> there's a 5% chance that a crate arrives with an error
> if the crate has an error...
> 
> * there's a 1% chance the destination station is wrong (it will display a random station name instead of your station)
> * there's a 2% chance the listed contents are wrong (there may be addition items or missing items in the list)
> * there's a 4% chance the contained contents are wrong (the crate itself may be missing things)
> 
> If the manifest has any of the above errors, you are expected to use the deny stamp to deny the manifest and ship it back
> if the manifest has no error, you can use ANY stamp to stamp it and it is valid

Bloody hell I wish that was written somewhere, it's rare enough that I doubt many people know that. 

I didn't know I was meant to be playing _Papers Please_ when playing cargo department. And might I remark that it is _highly irritating_ the one or two times it's happened when ordering something that is both critical and expensive (BSA parts missing one board so you have to order a whole new lot)

**Comment by Dorsisdwarf** [comment]
There are cargo players who dont know you're supposed to be keeping an eye out for shoddy crates to refund/deny manifest?

**Comment by NanoCats** [comment]
> There are cargo players who dont know you're supposed to be keeping an eye out for shoddy crates to refund/deny manifest?

I mean, how the hell am I supposed to figure this out besides osmosis from another cargo tech?

A lot of people I see burn the forms or just ignore them like any other trash item.
