### ISSUE TITLE
Select equipment menu should not call equipped and friends

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#57865]
With the new select equipment menu, we have dummy humans who equip the items to show off in the UI. This is nice, but it calls `equipped`, which requires code like this:

https://github.com/tgstation/tgstation/pull/57824/files#diff-d29b0e337c650b0b115c8d9e07502af6f0d87017b9fef48b56dff58fcc1bdf0fR417

**Comment by TriggeredBoi** [comment]
It calls `get_flat_human_icon`, which calls [equipOutfit with visualsOnly = TRUE](https://github.com/tgstation/tgstation/blob/24efbd65255377da0c5484f31936e77596382243/code/__HELPERS/icons.dm#L1060).

Ideally visualsOnly should be passed to `/obj/item/clothing/equipped`, no?
