### ISSUE TITLE
Oversight: Shitters can claim as many wardrobes/personal lockers as they please

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#57883]
## Reproduction:

1. Play a round, Ideally latejoin
2. Notice some asshole has claimed all the personal lockers on the station for himself for no reason
3. Scream, because there's no way to release them, even if you beat the perpetrator into submission you can't un-claim the lockers, nor can you force _them_ to.

My personal opinion is that you should only be allowed one locker, and one wardrobe, generously leaving you with 2 lockable containers. Attempting to claim an additional container would warn you that you may only claim one locker/wardrobe at a time, and that you may claim the current one but it will release their other claim (Just in case your locker gets stolen/spaced/etc).

Believe it or not some of us actually _do_ use personal lockups for uh, definitely not crimes nope, legitimate business.

And it's not super important but I wish we could just alt click these things like departmental lockers :v

**Comment by spessbro** [comment]
hop has access to personal lockers

**Comment by NanoCats** [comment]
> hop has access to personal lockers

The hop can't release their claim on the locker as far as I know, just open it.

**Comment by spessbro** [comment]
also this would be a rule 0 break though it would be neat to have an admen secret to open all locked lockers

**Comment by ninjanomnom** [comment]
Feature requests don't belong on the issue tracker, that's what the forums are for.
