### ISSUE TITLE
thrown objects will dissapear and appear back in your hand or beneath you 

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#57885]

**Comment by TheVekter** [comment]
What object were you throwing?

**Comment by ATH1909** [comment]
> What object were you throwing?

~~a boomerang, why?~~

**Comment by zxaber** [comment]
If you're playing warden, HoP, or happened to have a dog near you, this happened because the dog fetched the item and brought it back.

**Comment by TheBonded** [comment]
like zxaber said, this is because you threw it near a dog.

**Comment by Serxule** [comment]
> What object were you throwing?

it was a spear, also i was in maints with no animal near me, not sure what happened but it seems to have stopped now

**Comment by Sealed101** [comment]
some server fluke maybe? who knows by this point
