### ISSUE TITLE
Odysseus Medihud stays after exiting

### ISSUE THREAD

**Issue by MarshyMansSock** [tgstation/tgstation#57904]
Reporting client version: 513.1542

## Round ID:
[158754](https://scrubby.melonmesa.com/round/158754)

## Reproduction:
Make Odysseus
Don't wear medihud
Get in
Get out

**Comment by TheBonded** [comment]
Nooo why did you have to report this?

**Comment by SuperNovaa41** [comment]
Still can't reproduce. Closing.
