### ISSUE TITLE
tram cargo shuttle wall lighting bug

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#57930]
Round ID: any round i think

## Reproduction: this
![image](https://user-images.githubusercontent.com/64584757/112237175-5b52b380-8bff-11eb-87d4-01765281b2ad.png)

**Comment by LemonInTheDark** [comment]
please update your title to better reflect the issue

**Comment by SuperNovaa41** [comment]
Fairly certain this isn't an issue anymore
