### ISSUE TITLE
Subdermal ID saved ID is gone when you die

### ISSUE THREAD

**Issue by Colovorat** [tgstation/tgstation#57947]
## Reproduction:

1. Save some ID
2. Die
3. Get revived
4. Saved ID gone
5. Cry about captain id that you stole and saved

**Comment by ATH1909** [comment]
did you get batonned at all?

**Comment by Colovorat** [comment]
I don't think so? Batong disables nanites or what? Died to welder and punches

**Comment by moocowswag** [comment]
shocks in general can trigger and toggle programs off/on, how were you revived?

Batons definitely count as a shock and can cause this sort of behavior, im not so sure about medical defibs though.

**Comment by Colovorat** [comment]
well i was defibed, and person that defibed me was grabbing me, so he got shocked, but i made restart time on programm 1 second

**Comment by Colovorat** [comment]
Okay i think i was shock from defib, still stupid
