### ISSUE TITLE
Deltastation: Distro and waste are connected at round start

### ISSUE THREAD

**Issue by Bram961** [tgstation/tgstation#57958]
## Map:
Deltastation

## Issue:

toxins mixing in science and the supermatter coolers have layer adapters that cross both distro and waste connecting the two at round start until someone removes tiles and cuts them out.

![Supermatter coolers layer adapter](https://i.imgur.com/600Y6ED.png)
![Toxins](https://i.imgur.com/EGuTHIB.png)

**Comment by rdragan** [comment]
Different layered distro/waste was a mistake.
