### ISSUE TITLE
Wizards spawned by a die of fate don't have a spellbook.

### ISSUE THREAD

**Issue by JoshAdamPowell** [tgstation/tgstation#57953]
Reporting client version: 513.1539

## Round ID:
[158946](https://scrubby.melonmesa.com/round/158946)

## Reproduction:

Player rolled a die of fate (admin spawned) which gave a d20. Sent them to the wizard ship with a wizard outfit but without a spellbook.

**Comment by ATH1909** [comment]
did they get a scroll of teleportation?

**Comment by SmArtKar** [comment]
That's odd. I don't see anything that can prevent them from getting a book. Checked that on a local server and it worked fine.

**Comment by timothymtorres** [comment]
This was fixed with https://github.com/tgstation/tgstation/pull/60506
