### ISSUE TITLE
Players cannot start a restart vote

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#57968]
## Round ID:
[158993](https://scrubby.melonmesa.com/round/158993)

## Testmerges:
none

## Reproduction:
![image](https://user-images.githubusercontent.com/51932756/112680746-5ece8080-8e33-11eb-85b3-c6413b279fd9.png)
OOC > vote
Guess they don't have perms for it or something

**Comment by Livrah** [comment]
Same with map vote

**Comment by Serxule** [comment]
yeah the new vote menu is fucked and doesn't give the option to make a vote, only to choose vote options

**Comment by jlsnow301** [comment]
I will fix this later tonight

**Comment by jlsnow301** [comment]
resolved in #58489
