### ISSUE TITLE
Full-auto weapons can be fired while in crit

### ISSUE THREAD

**Issue by thespitfire24** [tgstation/tgstation#57963]
## Reproduction: 
1. Get L6/Tesla Cannon/laser minigun, and an antidrop implant.
2. Get put into crit for whatever reason
3. Gun down your attacker while they scream.
4. For extra salt, if you die while firing the full-auto weapon, you can continue firing while dead until you run out of ammunition.

**Comment by thespitfire24** [comment]
oop, opened this too early.

**Comment by thespitfire24** [comment]
the round in question's over now, so this is getting reopened

**Comment by TheVekter** [comment]
Someone add it to the list.

**Comment by interestingusernam3** [comment]
This is what happens when you use full auto in a building.

**Comment by necromanceranne** [comment]
Dead man's trigger finger.

**Comment by Serxule** [comment]
feature

**Comment by OmegaShoots** [comment]
From my cold, dead hands
