### ISSUE TITLE
Nightmare's Lighteater doesnt delete lights on humans

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#57988]
## Reproduction: 
Attack someone who has light source equipped, no effect. Also light objects on the ground turning off on attack instead of deleting (or was it nerfed?)

**Comment by TemporalOroboros** [comment]
I think I know what's happening. I can probably fix this in a few minutes.

**Comment by TemporalOroboros** [comment]
@Livrah Sorry, that was more than a few minutes.
> Also light objects on the ground turning off on attack instead of deleting
Yeah, that was changed. Now the light eater just turns the light off and prevents it from turning back on again. I'm sure this has balance implications but I honestly didn't bother to check what they could be when I made the PR.
