### ISSUE TITLE
heretic gets targets on arrivals shuttle

### ISSUE THREAD

**Issue by arnociiroc** [tgstation/tgstation#57983]
Reporting client version: 514.1552

## Round ID:
https://sb.atlantaned.space/rounds/159043
>be me
>heretic, less go
>get target on arrivals shuttle...?
>huh???

## Reproduction:

 be heretic, put someone on arrivals shuttle, select target, profit.

**Comment by Dorsisdwarf** [comment]
Can you elaborate on what the issue you're reporting actually is?

**Comment by arnociiroc** [comment]
was playing as heretic, I selected an assistant as a target. after spam searching every z level imaginable on icebox I couldn't get a signal. ahelped, got told they were on a shuttle and completely braindead. I'm not too sure on how they were stuck on the shuttle, maybe they dced while flying in.

**Comment by Dorsisdwarf** [comment]
Ahh, I see.
