### ISSUE TITLE
Xenomorphs can't strip humans

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#57996]
## Reproduction:

Be xeno. Try to strip human. Fail. More specifically, the menu appears, but xenos seemingly can't interact with it at all.

This is almost assuredly an unintentional side effect of #57889, but it's a pretty big problem for xenos who can't remove their victims headsets anymore.

**Comment by Mothblocks** [comment]
Can you detail the repro steps better?  What does "Fail" mean? Does the menu not show up at all? Does it show, but you can't interact?

**Comment by Mothblocks** [comment]
It's an orange eye, it's because they're not an advanced tool user, which tgui unfortunately blocks. Will take a bit of a specialized solution.

**Comment by nianjiilical** [comment]
yeah my bad, made it a bit more clear

**Comment by Mothblocks** [comment]
ok so this is a problem with the assumption the living's "can use ui" implementation makes, as it seems to believe tgui will only be used for physical object

```dm
/mob/living/default_can_use_topic(src_object)
	. = shared_ui_interaction(src_object)
	if(. > UI_CLOSE && loc) //must not be in nullspace.
		. = min(., shared_living_ui_distance(src_object)) // Check the distance...
	if(. == UI_INTERACTIVE && !ISADVANCEDTOOLUSER(src)) // unhandy living mobs can only look, not touch.
		return UI_UPDATE
```

it's the ISADVANCEDTOOLUSER check that's failing us
