### ISSUE TITLE
TGUI and powercells/cell chargers

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#58009]
## Round ID: [159099](https://scrubby.melonmesa.com/round/159099)

Reproduction: 1. tgui menus were _INCREDIBLY_ laggy and froze everytime upon opening (other players had this issue too, and it was so bad with the science console it gave me the "you are disconnected/afk" message multiple times), 2. power cells were not charging despite there being power, (an issue that existed before but has come back).

**Comment by Mothblocks** [comment]
Keep it to one bug per issue report, split this into two with *proper* reproduction steps for both.
