### ISSUE TITLE
You can bypass stack storage restrictions by inserting stacks in boxes piecemeal

### ISSUE THREAD

**Issue by Ryll-Ryll** [tgstation/tgstation#58008]
Reporting client version: 513.1536

## Round ID:
[159100](https://scrubby.melonmesa.com/round/159100)

## Reproduction:
Take a stackable item that gets bigger the more you have, like rods, and a storage item that only accepts items of a certain size and below, like a box. You can't insert 50 rods at once into the box because 50 rods is a normal sized stack, while boxes only fit small items. What you can do, however, is insert 15 rods at a time, which allows you to fit all 50 rods in one slot despite being too big normally

**Comment by Seris02** [comment]
Damn, I've been abusing this bug for a long time, gonna go fix it now.
