### ISSUE TITLE
The toxin`s implosion compressor deleting gasses from ttvs

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#58005]
### Reproduction: Fit a hot plasma tank and a cold oxygen tank onto a ttv then try to refine a raw anomaly core with the compressor. It will spit out the ttv with the gasses inside of the tanks emptied.

Im not sure if there was a change to the requirements for a successful anomaly core (ive looked) but Ive never had it spit out a ttv AND empty both of the tanks in it before which is why I think its buggy and I`m not even sure if its testing my mixes in the first place and is instead just deleting the gasses before the test is called.

**Comment by TemporalOroboros** [comment]
@moocowswag 
Yeah, the way the compressor was calculating blast strengths was copying the gas mixtures and then calculating the bombs strength of of the copied mixtures. It was also doubling the apparent power of any TTV you put into it. This was changed to use the actual gas from the TTV so it actually empties the thing now. If the power is too low to refine the core it will give you the TTV back without the gases now.

**Comment by moocowswag** [comment]
Oh, I couldnt find any prs related to the implosion compressor that were recent.
