### ISSUE TITLE
TGUI menus laggy

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#58023]
Round ID: https://scrubby.melonmesa.com/round/159099

Reproduction: tgui menus were INCREDIBLY laggy and froze everytime upon opening, the only thing I can think that has caused this (this has been happening every round so far, and other players notice it too) is that possibly a runtime happened, since this same round had cells not charging with power

**Comment by LemonInTheDark** [comment]
It's not related to runtimes. There is massive hitching when doing things like scrolling or spawning a new window, it doesn't appear to be server side, but it's hard to tell when testing locally

**Comment by stylemistake** [comment]
Haven't noticed anything weird in the logs, all default tgui settings, just generic wire cutting and roboticist gameplay. UI might lag if server is under a heavy load. Did wires load quickly?

I noticed that "suspend tgui window" messages are sent twice for some reason.

**Comment by ArcaneDefence** [comment]
I have absolutely no problem reproducing this by just trying to navigate the R&D console without unlocking anything.
https://streamable.com/ucs5je

I even had the interface lock up, close, and then it wouldn't come back up from me clicking on the console until I went to view runtimes. It was the worst when clicking on the future tab.

**Comment by ChocolateBickie** [comment]
This issue gets worse either the longer the round goes on or the more times you look at a menu. In the beginning the ORM window opened immediately but after 15 minutes and several laggy uses of the RnD console it completely freezes the game for 10 - 30 seconds.

It forces scientists and Shaft Miners to stare at frozen screens for a good few minutes every round and generally sucks the fun out of the game, not to mention occasionally crashing you.
