### ISSUE TITLE
Station traits(?) cause players to spawn on the centcom z-level

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#58024]
## Round ID: [159158](https://scrubby.melonmesa.com/round/159158)

Start of the round, 3 engineers and the detective spawned in space, near the hyperspace area. Apparently it may have been caused by station traits, since everybody spawned in random places, and people on bus told me to make an issue for it.

**Comment by LemonInTheDark** [comment]
Scratch that, I was wrong about station traits, had things mixed up. No fucking clue what causes this tho

**Comment by LemonInTheDark** [comment]
Wait no, ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh maybe it was that

**Comment by Qustinnus** [comment]
ive heard this before so it probably is.

**Comment by Qustinnus** [comment]
it should only be picking from station areas so its a consistency issue with those, unless im wrong.
