### ISSUE TITLE
protection objective's suicide clause looks like it can be broken if you don't have a brain left?

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#58037]
```
/datum/objective/protect/check_completion()
	var/obj/item/organ/brain/brain_target
	if(human_check)
		brain_target = target.current.getorganslot(ORGAN_SLOT_BRAIN)
	//Protect will always suceed when someone suicides
	return !target || considered_alive(target, enforce_human = human_check) || (human_check == TRUE && brain_target) ? brain_target.suicided : FALSE
```
The protect objective (used by heretics and the like) has a clause to still count as being successful if you protection target suicides, since that'd be kind of a cheap way to redtext. However, this appears to be tied to checking the target's brain for the suicided variable, which could mean that a target that suicides and then gets dusted (from, say, the medical wrench suicide) can end up bypassing this clause and causing the protect objective to fail instead of succeed.

**Comment by Mooshimi** [comment]
#57584 protect obj is also just somewhat borked

**Comment by timothymtorres** [comment]
This was somewhat reworked with #61037 but this doesn't fix the main issue.  If a player is deadset on screwing the protect objective they can just space themselves at anytime, have the chef gib them, etc.  You can still suicide without the using the verb quite easily.
