### ISSUE TITLE
looking between z-levels is grey and ugly

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#58047]
## Reproduction: look at an ice chasm on icebox for example, and you see this, it also hides any UI features that are on it
![image](https://user-images.githubusercontent.com/64584757/112892096-c2ec8100-908d-11eb-8ae9-8b6f4608bb33.png)

**Comment by Serxule** [comment]
jesus christ this is even worse on tram

**Comment by ArcaneDefence** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/58020
