### ISSUE TITLE
Attempting to call robots as an AI isn't working

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#58048]
Reporting client version: 513.1536

## Round ID:
N/A

## Testmerges:
- [Sec officers now only get PDA'd if the new member is of the same department](https://www.github.com/tgstation/tgstation/pull/57877)

manuel
## Reproduction:
1. use the "access robot Control" verb
2. attempt to move pingskys into your camber
3. fail
4. repeat 2-4 until you realize you can't get pingsky to move with the call function at all.
this works with any bot.

**Comment by dragomagol** [comment]
Should be fixed by #58064
