### ISSUE TITLE
Behind sprite for poison moth wings still has limb-shaped holes.

### ISSUE THREAD

**Issue by PetMudstone** [tgstation/tgstation#58057]
## Round ID:
N/A, tested locally.

## Testmerges:
N/A

## Reproduction:
Get a moth with poison wings, amputate their limbs, notice that there are gaps in their wings' behind sprite. This does not appear on other kinds of moth wings as they were fixed in #53969.

![moth](https://user-images.githubusercontent.com/38266309/112908042-a3605300-90a3-11eb-8ed5-fbbe72f2ab2d.png)
![moth2](https://user-images.githubusercontent.com/38266309/112908619-ad368600-90a4-11eb-9d2c-b099fb5c3a43.png)

**Comment by ArcaneDefence** [comment]
I have no mouth and I must scream
