### ISSUE TITLE
Motorized Wheelchairs cannot build certain items.

### ISSUE THREAD

**Issue by biffbuttcus** [tgstation/tgstation#58062]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Motorized wheelchairs cannot build certain items like wall girders, airlocks, computer frames, etc. Trying to gives a message that the Motorized Wheelchair is in the way and it can't be done.
Regular Wheelchairs do not have this issue. This appears to be an oversight of Motorized Wheelchairs.
I believe this is a side effect of trying to prevent machine stacking.
Motorized Wheelchairs should be treated the same as regular Wheelchairs and shouldn't have this issue.

**Comment by timothymtorres** [comment]
Fixed according to Profakos.
