### ISSUE TITLE
Vehicles open blast doors when bumping into them

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#58063]
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
Hop onto any scooter or scooter-like item, and go into one and it opens magically.
This issue is probably the same thing https://github.com/tgstation/tgstation/issues/55357

https://streamable.com/1d86rf

**Comment by Serxule** [comment]
there was a fix that was merged a while ago, but it got removed for some reason, (although mechs should be able to open blast doors if they can punch down walls eh?)

**Comment by ArcaneDefence** [comment]
Mechs work by just walking into them again, and I am aware of the last attempt to fix this, being https://github.com/tgstation/tgstation/pull/54851

**Comment by zxaber** [comment]
Why do people undo my fixes?

**Comment by Serxule** [comment]
> Why do people undo my fixes?

I think it was due to mechs not being able to interact with any type of door and there was no fix for it, that was an issue at some point anyways, might be 2 different things
