### ISSUE TITLE
open space is grey fog.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#58072]
Reporting client version: 513.1536

## Round ID:
irrelevant

## Testmerges:
Manuel
- [reverts map_format changes](https://www.github.com/tgstation/tgstation/pull/58051)
- [Fixes incorrect params passed into callback function causing server crashing numbers of runtimes.](https://www.github.com/tgstation/tgstation/pull/58020)

## Reproduction:
1. play on tramstation
2. have open space be weird grey tiles that cover the HUD

**Comment by Serxule** [comment]
fixed by https://github.com/tgstation/tgstation/pull/58073
