### ISSUE TITLE
hypno grenades dont work

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#58092]
## Reproduction: used grenade, they got flashed, but they were completely unaffected.

**Comment by ArcaneDefence** [comment]
Do you know if they had eye protection or not? Were they adjacent to the flashbang?
If so, they wouldn't enter the trance, and if they were adjacent to it they'd still get knocked down.

If they were deaf beforehand, you could induce the trance state but they'd be incapable of hearing any phrase for it to trigger, and the effect would expire shortly.

Additionally, ear protection will prevent the trance state on a single hypnobang unless they are already vulnerable to hypnosis, and mindshields prevent the trance state altogether.

Gonna need more information to have any idea if the mechanics are working as intended.

**Comment by Serxule** [comment]
> Do you know if they had eye protection or not? Were they adjacent to the flashbang?
> If so, they wouldn't enter the trance, and if they were adjacent to it they'd still get knocked down.

 considering there were about 4 or so non-sec (atmos, assistants, chef) and they all had protection that would be dumb as hell

**Comment by rdragan** [comment]
> > Do you know if they had eye protection or not? Were they adjacent to the flashbang?
> > If so, they wouldn't enter the trance, and if they were adjacent to it they'd still get knocked down.
> 
> considering there were about 4 or so non-sec (atmos, assistants, chef) and they all had protection that would be dumb as hell

It's unlikely but not impossible.

**Comment by Swiftfeather** [comment]
> It's unlikely but not impossible.

This is an issue we've had downstream, hypno flashes and grenades work, and they get logged to admins, but the trauma doesn't apply and people don't get the message. May be unrelated to the issue this bug experienced.

**Comment by rdragan** [comment]
Could not reproduce this on live.
 
> This is an issue we've had downstream, hypno flashes and grenades work, and they get logged to admins, but the trauma doesn't apply and victims don't get the message. May be unrelated to the issue this report experienced.

What's the downstream and do you have a report?

**Comment by Swiftfeather** [comment]
> What's the downstream and do you have a report?

@rdragan 
https://github.com/Skyrat-SS13/Skyrat-tg/pull/4548

**Comment by SuperNovaa41** [comment]
Gonna cleanup flagged because of serxule's issue history + it's always worked for me
