### ISSUE TITLE
ED-209s are aware of attacks that happen while they are off.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#58099]
Reporting client version: 514.1551

## Round ID:
[159360](https://scrubby.melonmesa.com/round/159360)

## Testmerges:
- [reverts map_format changes](https://www.github.com/tgstation/tgstation/pull/58051)

## Reproduction:
1. Construct or otherwise acquire an ED-209.
2. Swipe a card with sufficient access on the ED-209 to unlock its controls.
3. Turn the ED-209 off through the control GUI.
4. Open the maintenance panel of the ED-209 with a screwdriver.
5. Attempt to insert a power cell and smack the bot instead.
6. Close the maintenance panel of the ED-209 with a screwdriver.
7. Turn the ED-209 back on through the control GUI.
8. Get instantly stunbatonned by an irate ED-209.

**Comment by TheBonded** [comment]
Security bots are omnipotent. Beepsky is eternal. you cannot hide your actions from THE LAW

**Comment by zxaber** [comment]
Fool that you are, you trust the robot to tell you that it is off.
