### ISSUE TITLE
Green slimes don't produce enough mutation toxin

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#58102]
## Round ID: [159371](https://scrubby.melonmesa.com/round/159371)

159271

## Testmerges:

The following pull requests are currently test merged:
#58051: 'reverts map_format changes' by Fikou at commit 39c28248f2
#58096: '[15.ai] [April Fools] The Nanotrasen Voice Module subscription has expired.' by Iamgoofball at commit 7a192b7550

## Reproduction:

Inject 5u of plasma into a green slime. Draw out 3.75u mutation toxin. Likely related to the toxins chem overhaul.

**Comment by Livrah** [comment]
Same with Adv mutation toxin from Black Slimes.

**Comment by ArcaneDefence** [comment]
Using 20u of plasma injected at once with a bluespace syringe creates 15u toxin.
https://github.com/tgstation/tgstation/blob/15f14ce48abefc88cb4f0da5085bf281afa94f29/code/modules/reagents/chemistry/recipes/slime_extracts.dm#L48-L52
Clearly isn't intended.

**Comment by Thalpy** [comment]
I see whats causing it, I'l have a fix up soon!
