### ISSUE TITLE
Dark gygaxes have the wrong sprite and wrong equipment

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#58106]
## Round ID:
tested locally

## Testmerges:
N/A

## Reproduction:
The scattershot isn't the incin carbine, they don't have a flashbang launcher, and the mech doesn't use the proper icon until it's destroyed
![image](https://user-images.githubusercontent.com/51932756/113337740-6c797f80-92e5-11eb-948a-520dfbb5a23f.png)

**Comment by MrMelbert** [comment]
Dark HONK mech sprites might be wonky as well.

**Comment by necromanceranne** [comment]
The equipment is actually correct, I just forgot to update the actual uplink description. 

It was one of my first prs, please no blamies QwQ
