### ISSUE TITLE
Reaction Chambers do not accept pH buffers

### ISSUE THREAD

**Issue by Maurukas** [tgstation/tgstation#58119]
## Testmerges:

#57405 : 'Being shot into space by the mass driver now reconnects you to Terry (SHOULD WORK NOW)' by Ryll-Ryll at commit 1eb7b0169c
## Reproduction:

Assemble a chemical factory such that you are supplying acidic and basic buffer on layer 2, yellow and green pipes respectively, and set a reaction chamber with an appropriate pH range to produce a chemical like Libital. The reaction chamber will accept pH buffer once, and only once after being constructed (you will see a message in chat from it). Thereafter the reaction chamber will not take any buffer from the green and yellow duct networks, but the chamber will continue to cycle without adjusting its pH.

Unanchoring and re-anchoring the reactor does not restore the behavior, nor does plungering it.

In the screenshot below I would expect the reaction chamber to keep the contents within a range of 9-10 for the libital reaction. Instead it plunges to 1. Changing the values in the limits appears to have no impact on the pH of the reaction or the purity of the products.

![image](https://user-images.githubusercontent.com/66576896/113451758-85eafc00-93b7-11eb-813e-5c9e9aabf5aa.png)![image](https://user-images.githubusercontent.com/66576896/113451716-72d82c00-93b7-11eb-96da-da90c833dd2d.png)

**Comment by Technoturnovers** [comment]
I can confirm this issue, it basically breaks chem factories on a *fundamental* level.
