### ISSUE TITLE
The "Emergency Meeting" April Fools feature summons literally every mob

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#58131]
And I do mean _every mob_.

![image](https://user-images.githubusercontent.com/7019927/113476939-40284500-9444-11eb-886a-0f4ecc667566.png)

Tested this on Icebox but it apparently works on other stations, which means it also summons all the Megafauna.

I don't know if we're allowed to report bugs for April Fools shit but this was too damn funny to not post.

E: https://www.youtube.com/watch?v=6jQmdDnqK5o Video from InsaneRed

**Comment by Iamgoofball** [comment]
bubblegum looking sus

**Comment by ArcaneDefence** [comment]
> 
> I don't know if we're allowed to report bugs for April Fools shit

This is a merged feature in the events ss, and will be recurring every year. Yes, you can report issues with it.

**Comment by TheBonded** [comment]
feature, lock this behind emagging the console

**Comment by Serxule** [comment]
feature

**Comment by TheVekter** [comment]
#58133 supposedly fixed this so I'm closing
