### ISSUE TITLE
Signaller Suicided Ethereals can be revived via crystal

### ISSUE THREAD

**Issue by kinneb** [tgstation/tgstation#58151]
## Round ID:
[159595](https://scrubby.melonmesa.com/round/159595)

## Testmerges:
#58038 #58096 #58136 

## Reproduction:
1 - suicide with a signaller in-hand as an ethereal
2 - use a different signaller to kill yourself
3 - die
4 - get revived via crystal
5 - be able to fully rejoin the game

**Comment by ArcaneDefence** [comment]
The issue here is that it kills the user before marking them as having committed suicide, so the crystallization process doesn't get interrupted
