### ISSUE TITLE
BARRIER RUNES DON'T BLOCK ANYTHING

### ISSUE THREAD

**Issue by Sparkezel** [tgstation/tgstation#58157]
## Reproduction:
>Be summoning Nar'Sie
>draw and use barrier rune, so security needs to break it before they flood in
>they just walk over the barrier even without a nullrod
>get owned

**Comment by necromanceranne** [comment]
Did you activate the rune?

**Comment by SuperNovaa41** [comment]
they might've had holy melons? i'm not sure if that allows poeple to walk over barrier runes but uhh that could be what happened

**Comment by Sparkezel** [comment]
alright, you want a video?

**Comment by necromanceranne** [comment]
yeah sure

**Comment by rdragan** [comment]
> alright, you want a video?

Yes, I was not able to repro on local. Are you sure you activated the rune? Did the glowing shield effect appear?

**Comment by Sparkezel** [comment]
So I tried it out on sybil with Nianjiilical and it seems that you can't walk over the barrier runes even with a nullrod or holymelon

https://user-images.githubusercontent.com/53384660/113567724-70700f00-960f-11eb-8cd3-a8fef7a8ef55.mp4

**Comment by Sparkezel** [comment]
I swear I saw people walk over them though, maybe its just rare, or needs more runtimes

**Comment by TemporalOroboros** [comment]
I think I walked through a set of active barrier runes as a chestburster yesterday. I don't know if that's related... Please tell be the runes aren't `PASS_TABLE`

**Comment by Serxule** [comment]
> I think I walked through a set of active barrier runes as a chestburster yesterday. I don't know if that's related... Please tell me the runes aren't `PASS_TABLE`

if you did then that's the problem, barrier runes are listed as a table, meaning dwarves an etc can go through it

**Comment by ArcaneDefence** [comment]
"dwarves an ect" cannot go through barrier runes.
https://streamable.com/ikjpva

**Comment by timothymtorres** [comment]
> So I tried it out on sybil with Nianjiilical and it seems that you can't walk over the barrier runes even with a nullrod or holymelon

I think this only works with wizard's forcefields.
