### ISSUE TITLE
Temperature control units don't recognize piping as suitable if plugged via layer adapter

### ISSUE THREAD

**Issue by Akride** [tgstation/tgstation#58154]
## Round ID:
Discovered on fulp.

## Testmerges:
58154

## Reproduction:
Plug a h/c to wastes via a layer adapter (because most h/cs are layer 3 by default and wastes is layer 2). h/c won't read wastes as suitable environment and won't work unless you use environmental heat. Now tweak the board to layer 2 and plug it to wastes normaly : it reads wastes as suitable and will work like normal.

**Comment by Ghilker** [comment]
Cannot reproduce, probably a downstream bug, did the waste pipe had any gas in it?
![image](https://user-images.githubusercontent.com/42839747/113521860-809ad680-959c-11eb-8cf2-824adf11da84.png)
![af](https://user-images.githubusercontent.com/42839747/113521863-84c6f400-959c-11eb-8f42-d596f88adb9f.PNG)

**Comment by Ghilker** [comment]
also that TM is for experisci

**Comment by Akride** [comment]
Huh weird.

Either i was faster than atmos and waste still wasnt up or some shit, or i'm just very unlucky. (Or you're very lucky). 
Have you tried it in toxins ? 

Also fuck shit wrong TM indeed.

**Comment by Ghilker** [comment]
Tried everything, on delta toxins is connected to a pipe before the manifold and it still worked.

I think your waste pipe didn't have enough gas and by the time you changed everything it got filled a bit

**Comment by Akride** [comment]
Alright well thanks for checking
