### ISSUE TITLE
You hit portable airpumps and canisters once more when you click them with tanks

### ISSUE THREAD

**Issue by Sparkezel** [tgstation/tgstation#58152]
## Reproduction:
print 30 air tanks
start filling them with mix of your choice from airpump
each time you insert a tank you damage the airpump + hear the awful sound of tank hitting a pump/canister
halfway trough you actually destroy the airpump by intense tank smashing and refilling
cry as your hardly worked gasmix spews out of broken airpump, as your effort is now wasted and room is probably on fire

someone deleted the CANCEL ATTACK CHAIN in the pumps again probably

**Comment by SuperNovaa41** [comment]
this applies to airpumps, canisers and scrubbers

**Comment by MrStonedOne** [comment]
??? @MrMelbert
