### ISSUE TITLE
NT CIMS showing more than 1 plasma gasses

### ISSUE THREAD

**Issue by Pickle-Coding** [tgstation/tgstation#58153]

**Comment by zxaber** [comment]
![image](https://user-images.githubusercontent.com/37497534/113518937-3125bd80-953e-11eb-8f65-a35a933a0e63.png)

Image uploaded for easier viewing.

**Comment by projectkepler-ru** [comment]
N/A

**Comment by Sealed101** [comment]
i am a little vary of closing this but this may have been fixed by #69240 via changing how the interface collects and calculates gases to display
