### ISSUE TITLE
random viruses are still extremely strong

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#58163]
Round ID: any

Reproduction: viruses are still stupidly overpowered despite being random ones, for example, this time it was an itching (brute) death virus, with the cure aranesp, THIS WAS A RANDOM VIRUS. holy fucking shit miasma diseases were never death viruses, please fucking fix it

**Comment by Mothblocks** [comment]
not a bug, just a balance problem

**Comment by Mothblocks** [comment]
personally i agree that the diseases are too much from the rounds ive played, but issues are for bugs only
