### ISSUE TITLE
Monkeys can teleport you into disposal bins

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#58174]
## Round ID: [159663](https://scrubby.melonmesa.com/round/159663)

I was a paraplegic and got surrounded by 10 monkeys for a while, so I risked it and pushed a monkey away. Anyway so now I'm in crit, clown drags me out into the hallway and now I am in the kitchen disposal bin? There was a lot of monkeys and the clown trying to pull me, so that might've confused them and caused them to teleport me.

**Comment by rdragan** [comment]
@Qustinnus ?

**Comment by timothymtorres** [comment]
From the attack logs that round:

```12:35:50 | ATTACK | *no key*/(monkey (881)) has stuffed Time-Green/(Jared Robertson) into the disposal unit (NEWHP: -19.1)
-- | -- | --```

Looks like the monkeys and another player kept grabbing you back and forth, until that one monkey stuffed you in disposals.

What was the main problem?  Was your mob teleporter to the monkeys after clown dragged you away?

**Comment by timothymtorres** [comment]
I do recall this being the behavior for the old grab + disposals code back in the day.  A player could be half a screen away and still get teleported to the disposals chute.

**Comment by Time-Green** [comment]
> What was the main problem? Was your mob teleporter to the monkeys after clown dragged you away?

Yeah that was the problem. I'm willing to bet it's fixed with all the reworks
