### ISSUE TITLE
pulling slippery items no longer makes people slip

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#58182]
## Testmerges:
https://github.com/tgstation/tgstation/pull/58130
## Reproduction:
drag banana peel, soap, etc, watch as no one slips to it except yourself

**Comment by Serxule** [comment]
woops round isnt over

**Comment by Serxule** [comment]
round is now over

**Comment by ArcaneDefence** [comment]
Can you give any more information to reproduce this? It's already annoying to use multiple clients when debugging, even more so when you have no idea what you're fucking looking for, specifically.

**Comment by SuperNovaa41** [comment]
i haven't found this to be an issue, are you sure the person wasn't wearing no slips?

**Comment by Serxule** [comment]
> i haven't found this to be an issue, are you sure the person wasn't wearing no slips?

if 5 people including sec all had no-slips that'd be weird

**Comment by Serxule** [comment]
https://www.youtube.com/watch?v=i_ux_qSt5-Q&ab_channel=Serxule video done

**Comment by SuperNovaa41** [comment]
They need to be moving themselves, dragging something slippery under a person standing still doesn't work. As for them moving when you pass through them, I genuinely can't recall if that ever worked.

**Comment by Serxule** [comment]
> They need to be moving themselves, dragging something slippery under a person standing still doesn't work. As for them moving when you pass through them, I genuinely can't recall if that ever worked.

I'm fairly sure it used to work even a few days ago

**Comment by Serxule** [comment]
turns out this is an issue with all items, dragging plushies no longer makes the sound either

**Comment by ATH1909** [comment]
> turns out this is an issue with all items, dragging plushies no longer makes the sound either

THIS ISSUE NEEDS THE PRIORITY: CRITICAL TAG NOW NOW NOW

**Comment by interestingusernam3** [comment]
>They need to be moving themselves, dragging something slippery under a person standing still doesn't work. As for them moving when you pass through them, I genuinely can't recall if that ever worked.

It used to work

**Comment by Sadboysuss** [comment]
doesn't happen anymore
