### ISSUE TITLE
People can get to centcom on the cargo shuttle, then they get deleted

### ISSUE THREAD

**Issue by JoshAdamPowell** [tgstation/tgstation#58203]
## Testmerges:
https://github.com/tgstation/tgstation/pull/58155

## Reproduction:

People stand on the supply shuttle. It gets sent away. They end up at centcom but the second they get there they are deleted. Both of these rounds were on Delta station.

**Comment by ArcaneDefence** [comment]
Should be fixed by https://github.com/tgstation/tgstation/pull/58201

**Comment by TheBonded** [comment]
Hide in a bolted down locker to not get deleted!
