### ISSUE TITLE
Converoli is Uncreatable

### ISSUE THREAD

**Issue by RandomGamer123** [tgstation/tgstation#58218]
## Round ID:

[159754](https://scrubby.melonmesa.com/round/159754) (Actually irrelevant)

## Testmerges:

[#58155: Fixes some map exclusions](https://github.com/tgstation/tgstation/pull/58155) (Actually irrelevant)

## Reproduction:

Converoli is actually uncreatable. It is intended to be created by the inverse reaction of convermol, but the inverse percentage there is equal to the failure percentage of 40%, so either you make low-mid purity convermol, or you make the failure product, the insolvent medicinal precipitate.
(Can be seen from code, or from chem dispenser's reagent searcher)
![ThingAN845](https://user-images.githubusercontent.com/31096837/113789434-1786a080-970d-11eb-89c4-207ad6032f80.png)

**Comment by Thalpy** [comment]
Oops, Thanks for pointing it out! I'll have a fix up soon!
