### ISSUE TITLE
MapMerge: value assigned to free_keys is never used

### ISSUE THREAD

**Issue by ZeWaka** [tgstation/tgstation#58216]
## Round ID: ni
 
Title, it's never used.
Like, if you want to just call the method, just call it?

https://github.com/tgstation/tgstation/blob/77a052876063ef1e4139319458e8e54a2c426c81/tools/mapmerge2/dmm.py#L60-L67
@SpaceManiac ?

**Comment by SpaceManiac** [comment]
The variable was used prior to https://github.com/tgstation/tgstation/commit/be987fc6675d94914a0b236132e81cb83e8637bf
