### ISSUE TITLE
Mop buckets clean the tile under them on the same click when you fill them

### ISSUE THREAD

**Issue by maxymax13** [tgstation/tgstation#58225]
## Reproduction:
step 1. obtain a mop bucket from maintenance (do not confuse with the janicart, they're the old yellow ones with no slots for tools)
step 2. fill it with water
step 3. try wetting a mop in it
step 4, the mop will be cleaned but on the same click it will wet the tile the mop bucket is on

**Comment by Mooshimi** [comment]
https://github.com/tgstation/tgstation/blob/6c01cc2c010c8dc15c5500434ae8e55261511781/code/game/objects/structures/mop_bucket.dm#L14-L25 no cancel for the attack so it cleans the floor

**Comment by timothymtorres** [comment]
This was fixed by #63549
