### ISSUE TITLE
PAIs magicaly duplicate when their holloform is shot with a staff of change

### ISSUE THREAD

**Issue by UzedPickle** [tgstation/tgstation#58258]

**Comment by ATH1909** [comment]
this has been a thing for aaaaaaaaages.

it's how I got my first ever wizard greentext, actually- I staff of changed a steady stream of pAI holoforms and told them to go murderbone with their newfound powers. there's more to the story, of course, but I doubt that anybody else cares to hear it.

note that each new pAI will need like 20-30 seconds or so to charge up their holoform projectors before they can project a holoform for you to polymorph, so there is a limit to how quickly your minions can "respawn".

this also works with icebox's change spring, IIRC, but it's REALLY hard to get ghosts on board with it.
