### ISSUE TITLE
Now that Dynamic controls random events, Lone Operatives basically never spawn

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#58265]
I have regularly seen the weight for Lone Ops go into the 100s, or 200s. However, when it tries to spawn, Dynamic performs the routine random event handling, and often denies it.

I think part of this is the numbers I chose were too large a timeframe, it's been rare that I see a random midround event at all as of recent, but more importantly I think maybe Lone Ops should just ignore the Dynamic handling if their weight is past a certain amount.

**Comment by Serxule** [comment]
i didn't even realize that i've seen mid-round wizard more than I've seen loneop
