### ISSUE TITLE
PAIs can strip?!?! ?!?!?!?1

### ISSUE THREAD

**Issue by maxymax13** [tgstation/tgstation#58260]
## Round ID:
159886

## Testmerges:
#58188 

## Reproduction:
![image](https://user-images.githubusercontent.com/38844529/114107452-0bcae380-989f-11eb-98cb-0a10fb12201d.png)
![image](https://user-images.githubusercontent.com/38844529/114107476-15ece200-989f-11eb-8306-381c11bb9409.png)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Kylerace** [comment]
as designed

**Comment by Mothblocks** [comment]
i remember seeing pais tie your shoes before my changes, i wonder if they were somehow hard coded to just do that

**Comment by maxymax13** [comment]
pais are completely barred from interacting with objects in even the most minor ways, it doesn't make sense for them to be able to take items and armor off

**Comment by Mothblocks** [comment]
makes sense, too bad there's no non-shitcodey way to make it so they can tie your shoes :pensive:

**Comment by ATH1909** [comment]
as a pAI player, I can confirm that I don't remember being able to strip things while not inside of a bot.

**Comment by ArcaneDefence** [comment]
The issue may be a bit further up, as swarmers/ian/a fucking pet lizard can strip people

**Comment by Mothblocks** [comment]
Could easily just add a trait that determines whether or not a mob can strip, then just put it on carbons.
