### ISSUE TITLE
You cant chain flash a borgs

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#58274]
## Reproduction:

-Flash a borg, success. 
-Flash a stunned borg, fail. 

Without chain-stun emagged engiborg becomes the ultimate unit.

**Comment by Serxule** [comment]
oh yeah, this has happened where i've flashed a borg but it runs away, so I can confirm

**Comment by rdragan** [comment]
This explains quite a few things...

**Comment by necromanceranne** [comment]
Sure is a shame that borg balance hinges on the viability of a hyperspecific tool being usable against them, couldn't possibly have foreseen this one coming.

**Comment by redguy999** [comment]
The game probably considers flashed borgs "blind" and since you can't use a flash on a blind person, it doesn't stun them.
