### ISSUE TITLE
Override mobs are hostile to the AI that spawned them.

### ISSUE THREAD

**Issue by ChocolateBickie** [tgstation/tgstation#58273]
## Round ID:
[159917](https://scrubby.melonmesa.com/round/159917)

## Reproduction:
I was a rogue AI, the HOS was attacking my satellite. I responded by using Marine Override on scrubbers and consoles in my satellite. They immediately became hostile to the satellites turrets, then to me, with one successfully killing me.

Steps to reproduce;
1.Spawn as malf AI
2.Use Machine Override on nearby machine
3.Die

This behavior goes completely against the description of machine override and AI malf powers in general, as the description suggest 'machines' aren't targeted by the mobs, but the AI is.

**Comment by ChocolateBickie** [comment]
![image](https://user-images.githubusercontent.com/73966686/114191560-76822a80-9944-11eb-9ba4-b0f32bea61b4.png)

Here is some proof for the round.

**Comment by techno0** [comment]
I was the hos. Get ownd nerd
