### ISSUE TITLE
Monkeys can pilot mechs

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#58278]
## Round ID:
tested locally

## Testmerges:
N/A

## Reproduction:
Spawn a monkey
Spawn a mech
UGH-!
Mech pilot monkey!

![image](https://user-images.githubusercontent.com/51932756/114230882-e8ec0e00-9936-11eb-9d68-ee7f42189a18.png)

**Comment by Serxule** [comment]
i think any sentient mob with hands can pilot mechs

**Comment by ArcaneDefence** [comment]
> 
> 
> i think any sentient mob with hands can pilot mechs

https://github.com/tgstation/tgstation/blob/725017a5340d55ee809f6653fbad500e69c6eefe/code/modules/vehicles/mecha/_mecha.dm#L892-L916
No.

**Comment by Y0SH1M4S73R** [comment]
Another edge case introduced by the refactor of monkeys into a human species rather than a separate mob type.

**Comment by Serxule** [comment]
> Another edge case introduced by the refactor of monkeys into a human species rather than a separate mob type.

yeah that's definitely what it is, its probably classed as human subtype instead of  "primitive"

**Comment by ArcaneDefence** [comment]
> 
>probably classed as human subtype

`/mob/living/carbon/human/species/monkey`

![image](https://user-images.githubusercontent.com/51932756/114252483-beb04580-9962-11eb-8682-a9612bfa4d99.png)

**Comment by necromanceranne** [comment]
> > Another edge case introduced by the refactor of monkeys into a human species rather than a separate mob type.
> 
> yeah that's definitely what it is, its probably classed as human subtype instead of "primitive"

that's not quite the full picture. Primitive is specifically a trait that ashlizards have, which could be added to monkeys too to prevent a similar problem here.

**Comment by Serxule** [comment]
> that's not quite the full picture. Primitive is specifically a trait that ashlizards have, which could be added to monkeys too to prevent a similar problem here.

i mean yeah that's kinda what I meant, when it was changed the trait probably wasn't carried over

**Comment by Iamgoofball** [comment]
this is not technically a bug, closing

**Comment by Fikou** [comment]
its an oversight that should be fixed, closing it obfuscates a problem with the game
