### ISSUE TITLE
Cult round with player count less than 29

### ISSUE THREAD

**Issue by Nexofas** [tgstation/tgstation#58281]
![tg error cult lowpop](https://user-images.githubusercontent.com/68472117/114253510-2aba9a00-99b3-11eb-8e85-2879110bf299.png)
Reporting client version: 513.1542

Cult rounds need at least 29 players and 4 enemies of cult. This was a bizarre round.
## Round ID:
[159962](https://scrubby.melonmesa.com/round/159962)

## Testmerges:
- [[GHILKER APPROVED] [TGSTATION13 ORIGINAL] Fixes some map exclusions](https://www.github.com/tgstation/tgstation/pull/58155)

**Comment by Nexofas** [comment]
Also one station engineer says he couldnt be converted despite two cultists and offer rune being present.

**Comment by SuperNovaa41** [comment]
There is no minimum player requirement for blood cult.
