### ISSUE TITLE
slot machine trying to do terminal overlays

### ISSUE THREAD

**Issue by maxymax13** [tgstation/tgstation#58286]
## Reproduction:
did you know the slot machine was trying to get computer overlays and failing all along? now it has a default icon state so now you know. epic game
![image](https://user-images.githubusercontent.com/38844529/114259282-c12e9180-999a-11eb-8c66-cf215eb58832.png)

**Comment by ArcaneMusic** [comment]
Something tells me this has to do with emissive layers
