### ISSUE TITLE
Shutters and blast doors infinite airlock electronics and more

### ISSUE THREAD

**Issue by panvxv** [tgstation/tgstation#58294]
## Round ID:
#159985

## Testmerges:
N/A

## Reproduction:
Screwdrive shutter or blast door, crowbar it to take airlock electronics and do it again and do it again and...

Map like meta station have buttons in HoP office set to kitchen access-you need ID with kitchen access to use them.

When building shutters and blast doors you need airlock electronics and setting them with accesses don't save it so anyone can screw open and change ID channel with multitool making buttons that should open and close them not working.

You can use wirecutters on opened with screwdriver shutters and blast doors and this do nothing or this reset ID channel (sorry, downloading new update made for me problem with starting private game so someone need to test it or I will update this report after some time).

You can't insert back airlock electronics to shutters and blast doors.

**Comment by SuperNovaa41** [comment]
You should seperate each issue into its own report.

**Comment by Sealed101** [comment]
electronics dupe fixed by #58231

**Comment by SuperNovaa41** [comment]
These are all fixed, also the last one is not an issue
