### ISSUE TITLE
Not Exactly Sure, but i believe Exosuit Wormhole is crashing the server.

### ISSUE THREAD

**Issue by Aylwarded** [tgstation/tgstation#58312]
Like the title says, im not sure and i went to sleep so i couldnt replicate again. But two rounds in a row the server crashed the exact moment i was having fun with the Exosuit Wormhole Projector on a CLARKE.

I believe both the RoundID were 160041-160042

**Comment by Mothblocks** [comment]
Correlation, not causation, etc.

It was actually this: https://github.com/tgstation/tgstation/pull/58313
