### ISSUE TITLE
Examining a Nukie's Agent ID card as a ghost caused an error report

### ISSUE THREAD

**Issue by Cactus2388** [tgstation/tgstation#58329]
Round ID: [160078](https://scrubby.melonmesa.com/round/160078)

## Testmerges:
The following pull requests are currently test merged:
#58313: '[DNM] Revert "Advanced Greyscale Sprite Generation", potentially fix constant server crashing' by Mothblocks at commit 62b4f8bb6a

## Reproduction:
Was watching a nukie and decided to click on his ID and the TGUI associated with it popped up with this error
![ntosbroken](https://user-images.githubusercontent.com/27895840/114314854-0d282600-9ac2-11eb-99a3-398836eba3d1.PNG)

**Comment by SuperNovaa41** [comment]
this doesn't look like an issue to me anymore
