### ISSUE TITLE
Xeno Combat mode Disarm: Perform slash+stun

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#58322]
## Testmerges:
#58313 

## Reproduction:

Be beno hunter
Right flick the hos with combat mode on so I can steal his shoes
Steal shoes and prepare to run off
See him death gasp
Realize I somehow performed slashes and stuns in a single click repeatedly
Disarm his corpse again first without combat mode and then again with it
![image](https://user-images.githubusercontent.com/16896032/114301153-d0325280-9b06-11eb-91d7-8b936a33e226.png)

Feel bad for killing him in a scummy way by accident.

**Comment by Serxule** [comment]
wait this isnt intended? its been a thing since combat mode was added, I thought it was intentional
