### ISSUE TITLE
The nuke op shuttle doesn't have a roof

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#58347]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Load up tramstation
Send the nukie shuttle to the lower z level
Put on a jetpack
Fly over top of the shuttle and be met with literally no resistance 
Descend down and do whatever you want while inside
Fly back out and go do whatever you want outside
https://streamable.com/kon190

**Comment by Serxule** [comment]
reported in https://github.com/tgstation/tgstation/issues/57240 too

**Comment by ArcaneDefence** [comment]
>using the word ship not shuttle

![image](https://user-images.githubusercontent.com/51932756/114365233-80b84a80-9b37-11eb-8949-9228b307f31d.png)
