### ISSUE TITLE
Eyes sprites are completely missing

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#58356]
Reporting client version: 513.1536

## Round ID:
[160130](https://scrubby.melonmesa.com/round/160130)

## Testmerges:
- [Makes the GAS system only update the icon when it has changed](https://www.github.com/tgstation/tgstation/pull/58337)

## Reproduction:

As the title states, eye sprites appear to be not rendering (at least for humans). So nobody has any eyes.

Not sure if this is affecting nonhumans or cultists with red eyes. Probably is.

**Comment by ArcaneDefence** [comment]
This will be fixed by https://github.com/tgstation/tgstation/pull/58339
