### ISSUE TITLE
Robotics unable to create useful bots.

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#58368]
Reporting client version: 513.1538

## Testmerges:
- [Makes the GAS system only update the icon when it has changed](https://www.github.com/tgstation/tgstation/pull/58337)

## Reproduction:
Be a Roboticist and create any little robot, be sad that it refuses to patrol, clean, heal, or detain.
This also affects any robots created other than roundstart, even admin created bots.

**Comment by ATH1909** [comment]
oh shit, my omnibots! noooooooo!

**Comment by carshalash** [comment]
@Ryll-Ryll
