### ISSUE TITLE
Slot machines say "FUCK" on them

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#58370]
Reporting client version: 513.1536

## Round ID:
[160164](https://scrubby.melonmesa.com/round/160164)

## Testmerges:
Manuel
- [[DNM] Revert "Advanced Greyscale Sprite Generation", potentially fix constant server crashing](https://www.github.com/tgstation/tgstation/pull/58313)

## Reproduction:
title says it all, slot machines say FUCK on their sprite currently for some reason.

**Comment by dragomagol** [comment]
Duplicate of #58286
