### ISSUE TITLE
Ghost polling for mid-round Fugitive spawns appears to be linked to having traitor enabled rather than mid-round antagonist in preferences.

### ISSUE THREAD

**Issue by Gristlebee** [tgstation/tgstation#58388]
## Reproduction:
1. Have mid-round antag enabled in preferences, and traitor off
2. Spawn Fugitives
3. Don't get the prompt to sign up for fugitives.

**Comment by SuperNovaa41** [comment]
Were you inside your body?

**Comment by Gristlebee** [comment]
I wasn't inside a body and was a ghost at the time.

**Comment by Mooshimi** [comment]
cc @Mothblocks is this still the case with the rework?

**Comment by Mothblocks** [comment]
Probably since fugitives aren't their own preference but they shouldn't be on "midround antagonist", since that was a completely separate option

**Comment by Mooshimi** [comment]
im told this doesnt apply anymore
