### ISSUE TITLE
Ahealing someone with Corazargh in them deletes their heart and causes runtimes

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#58401]
## Round ID:

Found on local

## Reproduction:

1. add any amount of corazargh into someone, enough for the cursed heart effect to trigger
2. aheal them (wand of healing, staff of healing, aheal button)
3. immediately they collapse into a heart attack, lacking a heart, and the corazargh is not removed

![image](https://user-images.githubusercontent.com/51863163/114598845-fc111d80-9c57-11eb-9a0b-e8e4c51d442e.png)

swapping out their heart for a cursed heart is very janky for ensuring nothing can screw with it, manual blood pumping should probably be a component like manual blinking and breathing instead of this.

**Comment by Ghilker** [comment]
![image](https://user-images.githubusercontent.com/42839747/114600366-8b3c2680-9c94-11eb-8d42-854d3bb634b0.png)
