### ISSUE TITLE
Derelict Drone's purpose becomes unacheivable as of PR #58249

### ISSUE THREAD

**Issue by SamDDBS** [tgstation/tgstation#58409]
## Round ID: 
[160228](https://scrubby.melonmesa.com/round/160228)

## Testmerges:
#58313 

## Reproduction:
Be derelict drone ( you know, the ones in space that spawn naturally roundstart )
Realize you cant interact with any of the machines, even the apcs
Be upset at new drone update for not leaving derelict drones as they were

**Comment by SamDDBS** [comment]
Round ID: 160228
BYOND Version: 513.1536
Server revision compiled on: 
Master commit: cf5e3f5585a41f6b3dfd7c4ca74f25effcc512b4
The following pull requests are currently test merged:
#58313: '[DNM] Revert "Advanced Greyscale Sprite Generation", potentially fix constant server crashing' by Mothblocks at commit 62b4f8bb6a

Local commit: 507a82660466fb329ad07a63f6a77fd11abc22d8
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

**Comment by ATH1909** [comment]
@JJRcop
