### ISSUE TITLE
the maintenance god doesn't accept dead mice as valid sacrifices

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#58417]
dead mice are /obj/item/food/deadmouse, but the maintenance god checks for subtypes of /obj/item/reagent_containers, so you have to grind up *you can't just syringe the chems out of them, it seems) each slurry-filled mouse (or south bronx paradise bar) you use or something instead of sacrificing them directly. this could be intentional, but sadly, I can't ask armhulen for clarification on this, as he's blocked me.

**Comment by ArcaneDefence** [comment]
![image](https://user-images.githubusercontent.com/51932756/114758407-2b885e80-9d1a-11eb-9897-81353b6c52ff.png)
This isn't a problem, as dipping dead mice into containers of welding fuel is how you get yuck, but it transforms the welding fuel in the container, with nothing remaining in the dead mouse.

**Comment by ATH1909** [comment]
> ![image](https://user-images.githubusercontent.com/51932756/114758407-2b885e80-9d1a-11eb-9897-81353b6c52ff.png)
> This isn't a problem, as dipping dead mice into containers of welding fuel is how you get yuck, but it transforms the welding fuel in the container, with nothing remaining in the dead mouse.

... huh. I'll be damned, I always thought it was the mouse than ended up holding the yuck, what with the reaction requiring a mouse container and all.

**Comment by Fikou** [comment]
closing as it works correctly
