### ISSUE TITLE
explosive holoparasites can't set bombs anymore

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#58415]
Round ID: [160254](https://scrubby.melonmesa.com/round/160254)
Server: Sybil

![image](https://user-images.githubusercontent.com/42606352/114687665-99f8fc80-9cd9-11eb-97b2-25d87f7eb905.png)

**Comment by ArcaneDefence** [comment]
Failed to reproduce on local

**Comment by Sealed101** [comment]
it just works
