### ISSUE TITLE
Invers chemical's name does not appear to show up on the chemical analyzer properly, just description

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#58410]
## Reproduction:

I made some inverse ephedrine, Corazargh, and ran through the HPLC and isolated it into chem form. show below: no name, juist description. 
![image](https://user-images.githubusercontent.com/51863163/114635789-19abaa80-9c8b-11eb-9787-ed5b99a4cd0f.png)
(Bottle)
![image](https://user-images.githubusercontent.com/51863163/114636418-98edae00-9c8c-11eb-9222-b52eaf3fea30.png)

In comparison, this is the bottle, pre HPLC - Corazaragh, in the ephedrine inverse form
![image](https://user-images.githubusercontent.com/51863163/114635993-9f2f5a80-9c8b-11eb-8cc2-00f9c76042a0.png)
(Botte)
![image](https://user-images.githubusercontent.com/51863163/114636433-a4d97000-9c8c-11eb-83b2-338b8cfe92cf.png)

**Comment by Thalpy** [comment]
Huh that's strange. I should probably go over how purity is handled anyways since it's differed since it's initial conception. Thanks for pointing this out and I hope to have a fix up for it in a few days!
