### ISSUE TITLE
cleaning with a damp rag doesn't give cleaning exp

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#58416]
sad!

**Comment by YakumoChen** [comment]
![image](https://user-images.githubusercontent.com/10399117/114822383-7e612500-9db1-11eb-9cef-85474b376853.png)

not a bug

**Comment by RaveRadbury** [comment]
Given that the rag never runs out, seems like a balance decision to exempt it from cleaning xp *and* cleaning speed bonus.
