### ISSUE TITLE
Heretic target is on a different Z level, but isn't.

### ISSUE THREAD

**Issue by ChocolateBickie** [tgstation/tgstation#58435]
## Round ID:
[160278](https://scrubby.melonmesa.com/round/160278)

## Reproduction:
Well I was a heretic on Tram and chose Tooles-Poochooles, the assistant as my target. Use heart, on different z level. No problem, go to lower z level on Tram station, still diff z level. Must be on lavaland. Nope. Eventually die and observe to see where he was. This is what I find:
![image](https://user-images.githubusercontent.com/73966686/114760277-0c5bf200-9d57-11eb-9d91-d42a069090f6.png)

I don't know if this is a tram bug, cabinet bug or general heretic bug but I couldn't progress since there's no way to re-roll targets if their alive.

**Comment by MrMelbert** [comment]
Being inside a locker = not being in the same z level, same issue with olfaction mutaiton. Not a bug with tram or heretics.

**Comment by Mothblocks** [comment]
TBF, it's an oversight at least. We can check `get_turf` z level.

**Comment by SuperNovaa41** [comment]
This happens with anyone being inside of a container, that being said it the two levels of tram also effect it

**Comment by exymian** [comment]
If you get in a locker and use the heart, it then points where he is at.
