### ISSUE TITLE
Space travel (going away from the station) does not work on tramstation

### ISSUE THREAD

**Issue by celotajstg** [tgstation/tgstation#58436]
Reporting client version: 514.1552

## Round ID:
[160282](https://scrubby.melonmesa.com/round/160282)

## Testmerges: (irrelevant)
- [[DNM] Revert "Advanced Greyscale Sprite Generation", potentially fix constant server crashing](https://www.github.com/tgstation/tgstation/pull/58313)
- [Prevent flashing tabs issue](https://www.github.com/tgstation/tgstation/pull/58397)

## Reproduction:

try to go to the edge of the map

**Comment by dragomagol** [comment]
Was also an issue with Donut #50027

**Comment by InsaneRed** [comment]
you need to be on the lower z-level

**Comment by TheBonded** [comment]
This only happens on the upper Z, and you can do the "move down" verb in the IC tab. Also, nukie ships can only land on the bottom Z, so you can jist drop down inside it

**Comment by Sealed101** [comment]
works fine now and probably has been working fine fora good bit now
