### ISSUE TITLE
the bonus for turning in a bounty cube on time is much lower than it's probably intended to be

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#58431]
```
    ///Multiplier for the bounty payout received by the Supply budget if the cube is sent without having to nag.
    var/speed_bonus = 0.2
```

```
/datum/export/bounty_box/get_cost(obj/item/bounty_cube/cube, apply_elastic)
    return cube.bounty_value + (cube.bounty_value * (cube.speed_bonus / 100))
```
0.2/100 = 0.002, or a 0.2% bonus. I'd imagine that the bonus was intended to be a 20% one.

**Comment by maxymax13** [comment]
bounty cubes are fucked in general, i can get like a 600 credit one and put it on the cargo shuttle IMMEDIATELY and all i get is like 200 credits

**Comment by JosephJomama** [comment]
Made a very simple tweak to this in PR https://github.com/tgstation/tgstation/pull/58434

**Comment by cacogen** [comment]
whoops also this can be closed now
