### ISSUE TITLE
Issue with being able to pass through certain dense border objects like windoors and railings

### ISSUE THREAD

**Issue by SteelSlayer** [tgstation/tgstation#58447]
## Round ID:
N/A. Issue discovered while testing locally.

## Testmerges:
N/A. Issue discovered while testing locally.

## Reproduction:
1) Locate a windoor
2) Make the turf its sitting on change two times (by crowbarring the floor tile up and replacing it for example)
3) Walk through the interior side of the windoor

![Nosd6Pb](https://user-images.githubusercontent.com/42044220/114796310-41b41000-9d56-11eb-9ac6-26b088ccf256.gif)

I believe this is an issue on all objects that are currently making use of the `/datum/element/connect_loc` element.

**Comment by SuperNovaa41** [comment]
Possibly linked to https://github.com/tgstation/tgstation/issues/58235
