### ISSUE TITLE
sentient disease can re-infect someone who was cured of it.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#58446]
Reporting client version: 513.1536

## Round ID:
[160295](https://scrubby.melonmesa.com/round/160295) (this has happened in some earlier shifts)

## Testmerges:
Manuel
- [Insulating gloves gives chunky fingers trait](https://www.github.com/tgstation/tgstation/pull/58407)

## Reproduction:
1. Get sick from a sentient disease
2. get cured and make a vaccine from your blood.
3. Get sick again from it some time later
also i think i got sick from the disease again, despite the disease having been cured from everyone, so the person controlling it got ghosted, but i still got sick from the disease.

**Comment by ArcaneDefence** [comment]
A way to reproduce this is to spawn in yourself, a second human, and a disease.
Infect both mobs with the disease, cure one, and store a blood sample from the infected person.
You can inject yourself with the blood sample to verify that the cure prevented you from being infected further.
After that, vaccinate the second person, this defeats the active sentient virus.
From there you can then inject yourself with the sample you have stored, which will infect you again.

**Comment by Seris02** [comment]
BYOND is crashing every time I start a test server, but the reason for this bug is because of the sentient disease's disease's GetDiseaseID proc, since the overmind gets removed after it's defeated, it returns a different disease ID, and so can infect people once again.
