### ISSUE TITLE
Ice cream vat is conjugating chocolate cones like they are proper nouns.

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#58450]
## Reproduction:
- Approach the ice cream vat
- Dispense chocolate cone
![image](https://user-images.githubusercontent.com/3204033/114814229-5fdf3780-9d79-11eb-80dd-ae1cd637b4e1.png)

**Comment by interestingusernam3** [comment]
the

/datum/reagent/consumable/vanilla icecream
