### ISSUE TITLE
Addiction withdrawals continue to progress after death

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#58463]
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
Spawn in with smoker or junkie
Kill yourself
Stay in your body
Lose your grip on reality as your mood plummets despite your death
![image](https://user-images.githubusercontent.com/51932756/114946297-299cc900-9e08-11eb-810a-45798cda3c3d.png)

Probably doesn't impact most players outside of ethereals during their revival crystal

**Comment by RaveRadbury** [comment]
Sanity in general is affected by moodlets while dead, we need that whole thing frozen.
