### ISSUE TITLE
Ethereals, Plasmamen and many other races cannot use the strip menu

### ISSUE THREAD

**Issue by rdragan** [tgstation/tgstation#58495]
## Reproduction:

1. Be any of the mentioned races
2. Open a strip menu
3. Notice that the buttons are grayed out and the strip window icon is orange

Reproduced on local and live with the following races: Ethereal, Plasmaman, Golems, Nightmare, Abductor, Skeleton and other less common races.  
![image](https://user-images.githubusercontent.com/43266738/115097518-73ce9900-9f33-11eb-9796-e7d5e2816304.png)

**Comment by Mothblocks** [comment]
being a moth really lucked me out here huh

**Comment by InsaneRed** [comment]
you cant strip as ash ligger as well

**Comment by Mothblocks** [comment]
fixed by the same pr
