### ISSUE TITLE
Railings around the suppermatter sometimes don't stop you from running in and dusting yourself

### ISSUE THREAD

**Issue by Toparai** [tgstation/tgstation#58508]

**Comment by rdragan** [comment]
Good.

**Comment by Toparai** [comment]
based.

**Comment by TemporalOroboros** [comment]
Same thing happened to me months ago. I couldn't reproduce it on local after some minimal testing. Looks like I need to give it another shot.

**Comment by projectkepler-ru** [comment]
For some reason some railing are really weird
i've no idea why
