### ISSUE TITLE
Multiple hits by same projectile x175

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#58513]
## Reproduction:

That doesnt seem right.
https://youtu.be/oJvGnFbthWo
![Screenshot_88](https://user-images.githubusercontent.com/64209864/115124169-14cc5b00-9feb-11eb-893d-7c1eb488293f.png)

**Comment by necromanceranne** [comment]
I wonder how this performs with penetrators. I'm gonna go test that and find out.

**Comment by necromanceranne** [comment]
Actually I can't replicate this for some reason.

**Comment by newfren** [comment]
I saw this happening with the banana staff on manuel yesterday.

**Comment by Sealed101** [comment]
can no longer reproduce
