### ISSUE TITLE
Instant Changeling DNA Extract

### ISSUE THREAD

**Issue by SuperNovaa41** [tgstation/tgstation#58520]
## Reproduction:

1. Be changeling, neck grab someone
2. Press absorb DNA, get the message saying you need a tighter grip
3. Grab again, and begin to absorb.
4. The DNA is immediately transferred into you and the body isn't husked. Can't absorb them since you have their DNA already.

I was able to get this glitch twice in a row, however after that it didn't happen again. Both of those were with recently deceased players. The following body that stopped the glitch was a monkey.

**Comment by ATH1909** [comment]
did you get the mulligan from the absorption?

**Comment by SuperNovaa41** [comment]
> 
> 
> did you get the mulligan from the absorption?

yeah

**Comment by SuperNovaa41** [comment]
I haven't seen this since
