### ISSUE TITLE
Tram noclips through the BSA

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#58521]
## Reproduction:
1. Construct a BSA on the tram.
2. Send the tram towards, away, or across the BSA.
3. Notice that the tram and everything on it noclips straight through the BSA.

**Comment by SuperNovaa41** [comment]
The tram no clips through pretty much everything

**Comment by SuperNovaa41** [comment]
idk this is a weird void issue and im going to close it because wtf else would we do???
