### ISSUE TITLE
Syringes can't inject into head with spacesuit on

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#58541]
Suppose you have any helmet+spacesuit combo on.
Injecting with a syringe doesn't work on any bodypart (good).
If you take off the helmet, but keep the suit on, you actually still can't inject into your head (even though the head has no covering).
If you take off the spacesuit, but keep on the helmet, you _can_ inject into your head (even though the head has a helmet).

Ideally you shouldn't be able to inject a syringe through a helmet, and you should be able to inject a syringe into your head with no helmet, regardless of the suit.

**Comment by Djvarik** [comment]
You can inject someone in a suit without a helmet if you're targeting their head, but you get a message if you try injecting any other part that there's no exposed flesh or thin material on that part.

**Comment by SuperNovaa41** [comment]
No longer an issue.
