### ISSUE TITLE
Clicking on the tile below a door doesn't work on tiles that are on shuttles.

### ISSUE THREAD

**Issue by notfrying1pans** [tgstation/tgstation#58544]
## Reproduction: 
Click on a floor tile below a door on a shuttle. It won't close.
[Video of this in action.](https://user-images.githubusercontent.com/49667761/115275177-7b4a9980-a10f-11eb-8802-76bd913127e5.mp4)

**Comment by notfrying1pans** [comment]
I've recorded a video of this on the current round so I will wait until it is over to post it.

**Comment by notfrying1pans** [comment]
Video
https://user-images.githubusercontent.com/49667761/115274750-ffe8e800-a10e-11eb-8fd0-65daae537d55.mp4

**Comment by notfrying1pans** [comment]
Video of the bug in action
https://user-images.githubusercontent.com/49667761/115275177-7b4a9980-a10f-11eb-8802-76bd913127e5.mp4

**Comment by ATH1909** [comment]
huh, didn't know that that was even a feature

**Comment by notfrying1pans** [comment]
> 
> 
> huh, didn't know that that was even a feature

It was added 2 days ago I think

**Comment by Mooshimi** [comment]
This may have to do with the base case you used, the red airlocks, just being plating and not having tiles under them at all?

**Comment by distributivgesetz** [comment]
Tested on local, can confirm that this is no longer an issue
@Sealed101
