### ISSUE TITLE
Coniine breath loss lasts too long

### ISSUE THREAD

**Issue by mskinner5278** [tgstation/tgstation#58552]
Reporting client version: 513.1542

## Round ID:
[160612](https://scrubby.melonmesa.com/round/160612)

## Testmerges:
- [[DNM] doubles all turf decals to test whether they actually affect maptick at all under live conditions](https://www.github.com/tgstation/tgstation/pull/58496)

## Reproduction:
Coniine seems to have extremely long lasting loss of breath, despite the description suggesting it should last 5 seconds since the last tick of reagent. Even if the Coniine is purged and the lungs are replaced, the victim continues to gasp and suffocate.

**Comment by TemporalOroboros** [comment]
Currently it just inflicts 5 seconds of suffocation... Every second... And it stacks with itself... Yeah, this probably needs to get whacked with the balance hammer.

**Comment by Ghommie** [comment]
Fixed by #59455.
