### ISSUE TITLE
Inconsistency with borg modules

### ISSUE THREAD

**Issue by Intigracy** [tgstation/tgstation#5855]
You cannot turn on a flashlight (all borgs) and then store it to keep it on.

You can turn on a material scanner (minerborg) and store it and it will stay on (and continue draining power).

You can turn on a T-Ray scanner (engiborg) and store it and it will keep the on sprite (and drain power? not sure), but it does not actually work unless it's in your active modules.

Some consistency would be nice.

**Comment by PKPenguin321** [comment]
>You cannot turn on a flashlight (all borgs) and then store it to keep it on.

Flashlights are built in now, I don't know about the other two things
