### ISSUE TITLE
Canisters connected to the N2 or O2 to pure pipenets (including those separated by pumps) can not be interacted with anymore.

### ISSUE THREAD

**Issue by 170141183460469231731687303715884105727** [tgstation/tgstation#58572]
## Reproduction:MetaStation: Replace either the N2 to pure pump or O2 to pure pump with a layer adapter. Place an L shaped contraption on layer 2 behind the inner pipe access with a connector port connected to either N2 to pure or O2 to pure pipenets. The connector port can be separated with a pump and the issue will still persist. Connect the canister to the port, and the canister can no longer be interacted with, and won't appear in the alt-click menu.

Delta Station: Same shit but L-shape in inner access with the plasma pipes instead.

**Comment by InsaneRed** [comment]
can you send some pictures i cant seem to reproduce this

**Comment by 170141183460469231731687303715884105727** [comment]
I was able to reproduce after InsaneRed asked, but now I am no longer able to reduce this.
