### ISSUE TITLE
Adding a reagent to the reaction chamber increase the UI width beyond the size of the window

### ISSUE THREAD

**Issue by SuperNovaa41** [tgstation/tgstation#58574]
## Reproduction:

Adding a reagent to the reaction chamber increase the UI width beyond the size of the window
![image](https://user-images.githubusercontent.com/16159590/115440244-8966eb80-a1dd-11eb-83e0-ae24fc2df649.png)
![image](https://user-images.githubusercontent.com/16159590/115440293-9552ad80-a1dd-11eb-943c-5cc2b6c4cb6d.png)

**Comment by Time-Green** [comment]
I accidentally introduced that bug because I have absolutely no idea how tgui works, and I couldn't begin to attempt to fix it

**Comment by SuperNovaa41** [comment]
> 
> 
> I accidentally introduced that bug because I have absolutely no idea how tgui works, and I couldn't begin to attempt to fix it

The textbox is increasing in size when you add a reagent... if you can stop it from doing that itll solve the issue

**Comment by Time-Green** [comment]
> > I accidentally introduced that bug because I have absolutely no idea how tgui works, and I couldn't begin to attempt to fix it
> 
> The textbox is increasing in size when you add a reagent... if you can stop it from doing that itll solve the issue (i think)

i mean yes fixing the bug fixes the bug, but the problem is i am clueless when it comes to tgui
