### ISSUE TITLE
No/unnoticeable popup for becoming a heretic's servant

### ISSUE THREAD

**Issue by Cactus2388** [tgstation/tgstation#58580]
## Round ID: 
[160679](https://scrubby.melonmesa.com/round/160679)
## Reproduction: 
Get killed by flesh heretic, get revived in medbay lookin' fucked up, didnt get a popup or anything saying I was a ghoul so I assumed it was just something else, kill heretic guy and realize midway by looking at my notes tab that I'm slaved to him.
## Potential Fix:
Make it so it's more noticeable/add a popup notifying the player they're your master.

**Comment by ArcaneDefence** [comment]
Did these not communicate it enough?
https://github.com/tgstation/tgstation/blob/4e2a36fe7e56fad93495adf01c697f4b5de04e90/code/modules/antagonists/eldritch_cult/eldritch_monster_antag.dm#L18-L20

https://github.com/tgstation/tgstation/blob/4e2a36fe7e56fad93495adf01c697f4b5de04e90/code/modules/antagonists/eldritch_cult/eldritch_monster_antag.dm#L28-L37

**Comment by Time-Green** [comment]
According to logs 

> ## Round ID:
> [160679](https://scrubby.melonmesa.com/round/160679)
> 
> ## Reproduction:
> Get killed by flesh heretic, get revived in medbay lookin' fucked up, didnt get a popup or anything saying I was a ghoul so I assumed it was just something else, kill heretic guy and realize midway by looking at my notes tab that I'm slaved to him.
> 
> ## Potential Fix:
> Make it so it's more noticeable/add a popup notifying the player they're your master.

You were revived in medbay BY A HERETIC, which is a pretty important detail. 

I can't find anything to explain why you weren't warned, it might be that one bug again where to_chat messages are still sometimes dropped, although the only time I ever notice is when I say something in OOC, see no text from me and someone else still responds.

![image](https://user-images.githubusercontent.com/7501474/115526634-85e06c80-a290-11eb-84fb-c5dfef5c46cf.png)
