### ISSUE TITLE
Dog necromancy

### ISSUE THREAD

**Issue by maxymax13** [tgstation/tgstation#58590]
## Reproduction:
befriend ian
kill ian (:cry:)
give him commands
![image](https://user-images.githubusercontent.com/38844529/115590658-38b7c700-a29f-11eb-85e2-d0b11e9c51f2.png)

![dreamseeker_9YOSRVw6oS](https://user-images.githubusercontent.com/38844529/115590675-3f463e80-a29f-11eb-9934-864de423e06c.png)

**Comment by D4C-420** [comment]
dogromancy. The question now is if it works for slimes.

**Comment by ATH1909** [comment]
feature
