### ISSUE TITLE
coffee bar has an empty laptop frame instead of a real one

### ISSUE THREAD

**Issue by maxymax13** [tgstation/tgstation#58592]
## Reproduction:
the coffee bars have a useless empty laptop frame (/obj/item/modular_computer/laptop) instead of the civilian laptop like in engineering lobby (/obj/item/modular_computer/laptop/preset/civilian) which was presumably the intended result
![image](https://user-images.githubusercontent.com/38844529/115598828-d237a680-a2a8-11eb-87f8-5a7f4c8d6f97.png)
happens on kilostation and metastation, presumably on the other maps where this area was copy pasted onto
![image](https://user-images.githubusercontent.com/38844529/115599053-1d51b980-a2a9-11eb-8914-63346c33f488.png)
for the longest time i thought it was intentional but i realized that 1. what the fuck is the point of leaving an empty laptop frame as a bizarre taunt to anyone that dares explore the content in this area and 2. modular computers aren't really useful enough to the average assistant that loots this place to be worth locking behind asking engineers to fill it with parts and 3. the typepath implies that they just typed in laptop and didn't bother to check and see if it turned on

**Comment by nightred** [comment]
this is correct, i did not think to test the laptop ever. my bad.
