### ISSUE TITLE
removing HARS doesn't un-suppress telekinesis

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#58596]
The telekinesis mutation has `limb_req = BODY_ZONE_HEAD`, so receiving HARS suppresses it (or maybe removes it, I'm not sure). This is fine. However, if you then lose HARS, the telekinesis mutation doesn't reactivate.

I'm gonna be doing some testing with this bug soon to learn more information about it, but it'll be a bit of a pain to test it properly in the way I want to.

**Comment by redguy999** [comment]
If you used mutadone to get rid of the HARS it would also get rid of the telekinesis.

**Comment by ArcaneMusic** [comment]
> when someone is dismembered, it checks for limb conflicts (aka you need this limb to have this power) and it force removes the mutation if you no longer have the limb needed.
While not a bug, this is absolutely something in need of feedback to make it explained in-game.
