### ISSUE TITLE
strange reagent can create undead frogs

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#58600]
<img width="1074" alt="strangereagentbug" src="https://user-images.githubusercontent.com/42606352/115619110-1e8ae280-a2b9-11eb-9d8e-db0b1d979105.PNG">
I splashed a dead frog with strange reagent. Even though it remained dead, its sprite still changed from its dead sprite to its living sprite.

**Comment by Sealed101** [comment]
fixed by #71430 (or some other pr, frogs resurrect just fine with strange reagent now)
