### ISSUE TITLE
[found on Fulpstation] IAA agents can end the round multiple copies of DAGD, and can sometimes spawn with the wrong uplink type

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#58610]
![image](https://user-images.githubusercontent.com/42606352/115695933-d060f800-a327-11eb-87b0-d7b46ea86711.png)
My guess is that this guy was the last agent remaining, then some other agent got revived and died repeatedly.

Also, I was forced to start with an uplink implant instead of a pen uplink that round (starting me with only 16 TC instead of 20), and yet it seems that other traitors were able to start with non-uplink implants. I double-checked my preferences, and I still have a pen uplink as my preferred uplink type.

**Comment by SmArtKar** [comment]
PR it to Fulp's github, not to ours

**Comment by ATH1909** [comment]
> PR it to Fulp's github, not to ours

the issue is with the upstream branch (us), not something fulp has edited. due to how IAA as a gamemode works, this is very hard to test and confirm on a private server.

**Comment by maxymax13** [comment]
> PR it to Fulp's github, not to ours

isnt fulp a perpetually updating leech downstream with modular code like skyrat now?

**Comment by BootlegBow** [comment]
> > PR it to Fulp's github, not to ours
> 
> 
> 
> isnt fulp a perpetually updating leech downstream with modular code like skyrat now?

always was, they just didn't update for like ten months
