### ISSUE TITLE
Quirk pinpointer caused null species runtime when trying to equip to AI mob

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#58626]
## Round ID:

Local

## Testmerges:

Local

## Reproduction:

1. Have the Navigationally Challenged quirk
2. Spawn as AI
3. Cause null species runtime (didn't get a copy of it)

**Comment by SuperNovaa41** [comment]
This doesnt apply to the quirk

I get this everytime I spawn as AI or Cyborg on a local
