### ISSUE TITLE
having more than 2 connected stationary plumbing tanks mapped breaks roundstart

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#58623]
Running /tg/ revision: 2021-04-22
HEAD: c751a790c16350517fed9851fa96346751c25192
BYOND version: 513.1536

[Pastebin with initial runtime](https://pastebin.com/6bfRkrqA)

If you have at least 2 separate duct networks with their own stationary tanks mapped in, it hits with this recursive error after the Restaurant subsystem. It'll pass this eventually and after it passes the Weather subsystem it just sorta crescendos into tons of runtimes related to initializing atmos, leaving everything airless and sad and broken.

I can reliably repeat this and it only happens when the tanks are connected to a duct network.
`

**Comment by Time-Green** [comment]
God bless you for including the runtime log, I’ll try to get this fixed ASAP (a day max?)
