### ISSUE TITLE
Cant eat cooked food

### ISSUE THREAD

**Issue by BumkenBoy** [tgstation/tgstation#58635]
## Round ID:

[160850](https://scrubby.melonmesa.com/round/160850)

## Reproduction:

Cook food
Try to eat
Punch yourself with food

Nothing else i really know, maybe when cutting up bread and making slices of bread makes some of them not work?

**Comment by dragomagol** [comment]
Were you on combat mode?

**Comment by ArcaneDefence** [comment]
Duplicate of https://github.com/tgstation/tgstation/issues/55375
