### ISSUE TITLE
AI can't tell which doors are shocked without opening their menus

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#5863]
If an AI is subverted, shocks a lot of doors, and is then fixed, it's hard to then unelectrify all those doors. There's no exterior indicator to an AI if a door is electrified, so it has to click every door in an area it's electrified to see if it's electrified. This takes awhile, especially with lag making you wonder if the window has refreshed to reflect the new airlock you've clicked or not and having to stop and follow laws. It's easy to forget which areas you've shocked or miss a door, which leads to further harm or deaths, which leads to further accusations the AI is rogue. If the AI had a way to alt+click doors and know whether or not they've been electrified or unelectrified (such as a message in the chat box) it'd make the process much simpler.

**Comment by astralenigma** [comment]
The only problem that could arise from this is that then the AI could find doors sabotaged by traitors.

**Comment by nullbear** [comment]
I'd consider that a feature, Astral. The ai is kinda hooked into the stations systems anyways, it would make sense for it to notice when somethings been messed with quite quickly.
