### ISSUE TITLE
Can push unanchored directional windows through grilles

### ISSUE THREAD

**Issue by SuperNovaa41** [tgstation/tgstation#58647]
## Reproduction:

https://streamable.com/5r7s3y

Place an unanchored directional window alongside a grille (i believe these were made with an RCD)
Push it through the grille
rejoice at issue no. 9872 for directional windows

**Comment by jlsnow301** [comment]
author requested close as these could not be reproduced & significant refactors applied. feel free to reopen this issue if it persists
