### ISSUE TITLE
AI is continuously disconnected from shell while in emergency shuttle

### ISSUE THREAD

**Issue by Djvarik** [tgstation/tgstation#58646]
## Round ID:
[160874](https://scrubby.melonmesa.com/round/160874)

## Testmerges:
#58607: 'icon2html optimization stuff' by LemonInTheDark at commit ffff04eefe
#58608: 'Fixes a bunch of invalid icon states' by LemonInTheDark at commit 7530aa502c
#58496: '[DNM] doubles all turf decals to test whether they actually affect maptick at all under live conditions' by Kylerace at commit cb934f94dd
#58340: '(code bounty) refactors all uses of Crossed() and Uncrossed() into signals sent to loc, tracked by connect_loc' by Kylerace at commit 4031e5509c

## Reproduction:
1. Be AI, core is somewhere on the emergency shuttle even before departure. (I don't know if this happens with BYOS.)
2. Try to connect to shell and move around a bit, get disconnected after a short arbitrary time

I don't think this has anything to do with the testmerges since it has happened in previous rounds a while back.

**Comment by Sealed101** [comment]
can't reproduce; was not disconnected from the shell at any point during testing
