### ISSUE TITLE
Amanitin (Destroying Angel toxin) dealing much lower damage than expected

### ISSUE THREAD

**Issue by mskinner5278** [tgstation/tgstation#58654]
Reporting client version: 513.1542

## Round ID:
[160901](https://scrubby.melonmesa.com/round/160901)

## Testmerges:
- [Switches required version to 514](https://www.github.com/tgstation/tgstation/pull/58639)
- [Fixes ?. nonsense.](https://www.github.com/tgstation/tgstation/pull/58630)

## Reproduction:
Amanitin is dealing much lower than expected damage. 
Toxin processing rate for Amanitin is listed at 0.2u per tick, or 5 ticks per unit. At 3 damage per tick, this should result in 15 damage per unit. Actual damage is less than half that even accounting for the liver processing the last 3u quickly. 

A 15u syringe should hardcrit someone, but it deals only 75 toxin damage. 30u should be doing over 400 toxin damage, but is around 190 damage. It's a very unique poison and it would be interesting to be able to use, it currently requires an entire sleepy pen or three syringes to be lethal.

**Comment by LemonInTheDark** [comment]
Well that makes sense, since amanitin is having the reagent effects multiplier applied to it, which just about halves the output

![image](https://user-images.githubusercontent.com/58055496/116497397-1bb16400-a85c-11eb-9a1c-fcc8f9edfa8a.png)

I assume this was an oversight from #55534
