### ISSUE TITLE
Revs can flash convert blind people

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#58663]
## Reproduction:

I spawned with blindness as a plasmaman. I took off the blind fold because I didnt like it. I got flashed by a revhead and somehow got converted, even though I was blind. I did not have my shield down or have any eye protection, but you'd think that being blind prevents the rev flash from working

**Comment by MrMelbert** [comment]
For the record being blind =/= flash protection, the blindfold is what gives the flash protection. `get_eye_protection()` only checks if you don't have eyes or if you're wearing flash protection. Similarly, `get_ear_protection()` doesn't check if you're deaf. Whether this is 'realistic' or not, I don't know.
