### ISSUE TITLE
Void jaunting while having a bluespace body bag deletes the bag, and sends anyone inside to the lobby.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#58667]
Reporting client version: 513.1536

## Round ID:
[160939](https://scrubby.melonmesa.com/round/160939)

## Testmerges:
- [Switches required version to 514](https://www.github.com/tgstation/tgstation/pull/58639)
- [Fixes ?. nonsense.](https://www.github.com/tgstation/tgstation/pull/58630)

## Reproduction:
1. Get void jaunt by being a heretic.
2. Put someone in a BS body bag (in the case where this happened, it was a borg)
3. void jaunt.
I didn't actually witness this myself, but still, this most certainly isn't suppose to happen.

**Comment by MrMelbert** [comment]
Do you mean "ash jaunt" or "void blink"? Void doesn't get a jaunt.

**Comment by redguy999** [comment]
probably void blink.

**Comment by Serxule** [comment]
i feel like this could be a feature, because trying to teleport while in the bluespace realm things can get funky, so maybe it teleports you somewhere random, with a chance of a random z-level?

**Comment by redguy999** [comment]
> i feel like this could be a feature, because trying to teleport while in the bluespace realm things can get funky, so maybe it teleports you somewhere random, with a chance of a random z-level?

maybe, but it is most certainly not suppose to send you to the title screen.

**Comment by Serxule** [comment]
> maybe, but it is most certainly not suppose to send you to the title screen.

no yeah, i think the issue is that when you do it it treats it as an "illegal" action and doesn't know what to do with you so it just deletes you instead

**Comment by redguy999** [comment]
> no yeah, i think the issue is that when you do it it treats it as an "illegal" action and doesn't know what to do with you so it just deletes you instead

I believe there is a specific room that the game is suppose to send you to if it doesn’t know where to put you, so that might be what is bugged.

**Comment by Serxule** [comment]
> I believe there is a specific room that the game is suppose to send you to if it doesn’t know where to put you, so that might be what is bugged.

oh yeah that one room with plastic gems, I think it should but maybe it isn't coded, an oversight maybe?

**Comment by redguy999** [comment]
gonna close this, since nothing has been heard.
