### ISSUE TITLE
Explosions don't explode

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#58717]
Reporting client version: 513.1533

## Round ID:
[161007](https://scrubby.melonmesa.com/round/161007)

## Testmerges:
- [Makes the explosive compressor and blastcannon actually use the TTVs they're given + the explosion changes to support that.](https://www.github.com/tgstation/tgstation/pull/58015)

## Reproduction:
Cover yourself in X4, drop a badmin bomb, hit gibtonite... Nothing explodes.

**Comment by dragomagol** [comment]
I'm guessing this is from #58015

**Comment by ATH1909** [comment]
![image](https://user-images.githubusercontent.com/42606352/116076771-4a5fec80-a65a-11eb-8ad4-a3bda9450373.png)

**Comment by ATH1909** [comment]
~~and yes, I know that's the c4 sprite, but I couldn't find an x4 sprite on the wiki~~

**Comment by TemporalOroboros** [comment]
Runtime because named args. I'll fix it.
