### ISSUE TITLE
Pipes are broke on camera console

### ISSUE THREAD

**Issue by Djvarik** [tgstation/tgstation#58713]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Go onto a camera console and look on any cam in a room with exposed pipes like atmospherics.
![campipes](https://user-images.githubusercontent.com/25336158/116008738-aa637e00-a5db-11eb-8390-4d52a83d59d7.png)

**Comment by norill** [comment]
also occurs when seeing pipes on a z-level below current one

**Comment by timothymtorres** [comment]
I tested this today using cameras on ice and the pipes display correctly both on the same z-level and on bottom z-levels.  Marking this as `Cleanup` and it will auto-close in 7 days.
