### ISSUE TITLE
Wizards, Nukies, and other Non-crew forces can receive mail.

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#58714]
## Round ID:
N/A, Local Branch

## Testmerges:
N/A, Local Branch

## Reproduction:
Be Wizard.
Set your name up to something stupid, "BALLS MCGEE" or whatever.
Wait for cargo to receive it's first batch of mail.
You will have Mail from cargo.
As will the loneop that just spawned.
As will the guys playing charlie station.
As will the free golems, as will.. Do y'get the point?

**Comment by Time-Green** [comment]
Hardcore mail delivery. Imagine being the man having to deliver mail to the wizard slaughtering the crew

**Comment by ATH1909** [comment]
> Hardcore mail delivery. Imagine being the man having to deliver mail to the wizard slaughtering the crew

The Krusty Krab pizza is the pizza for you a- *gibbed*
