### ISSUE TITLE
Marisa magic shoes are missing an icon

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#58722]
Reporting client version: 513.1533

## Round ID:
[161013](https://scrubby.melonmesa.com/round/161013)

## Testmerges:
- [Makes the explosive compressor and blastcannon actually use the TTVs they're given + the explosion changes to support that.](https://www.github.com/tgstation/tgstation/pull/58015)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/116020448-1f927b80-a5fb-11eb-8bb0-bba82469b5c5.png)

**Comment by maxymax13** [comment]
caused by #58514
