### ISSUE TITLE
wigs can be used as anti-b*ldie inquisition tools

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#58725]
You can attack someone with a wig to make the wig copy their hairstyle (if their hairstyle isn't "bald). This is a good feature.

However, if you try to copy the hairstyle of someone who is wearing a wig, your wig will attempt to copy their TRUE hairstyle, not the hairstyle of their worn wig. This means that you can bop random people with wigs to sniff out b*ldies who are trying to infiltrate haired society.

The appropriate fix for this would be to make wigs prioritize copying the hairstyle of a worn wig over someone's true hairstyle if they're wearing a wig. If you hate fun, you could also make wigs unable to copy hair that's been concealed under a helmet or another piece of clothing with the HIDEHAIR flag.

**Comment by maxymax13** [comment]
completely unplayable
