### ISSUE TITLE
Rat King's domain ability has no cooldown. and both abilities work when dead

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#58737]
## Reproduction:

1. Be rat king.
2. Push the button to make vomit/oil/dirt and miasma.
3. Keep pushing the button.
4. Keep pushing the button until there is vomit and oil and miasma everywhere.
5. Get shot for filling the station with vomit and oil and miasma.
6. Keep pushing the button until they desperately cremate you to stop the vomit and oil and miasma pouring out of your corpse.

**Comment by ZeroMODE0** [comment]
I think I've encountered this, it's a pain in my ass and explains a lot.

**Comment by Serxule** [comment]
honestly, this might be intended
