### ISSUE TITLE
Removing an unrelated object from a wallet also temporarily resets your access

### ISSUE THREAD

**Issue by maxymax13** [tgstation/tgstation#58745]
## Reproduction:
step 1: put an id and something else, anything, like a coin or lighter or another id in a wallet
step 2: go to a door that the first ID has access to
step 3: take out the second object
step 4: even though the wallet is still showing the first id and the first id is still in the storage object, you can't open that door anymore until you take the first id in and out or put the 2nd object back in
![image](https://user-images.githubusercontent.com/38844529/116168346-28a14c80-a6d0-11eb-855a-69a5969cb3e8.png)
![image](https://user-images.githubusercontent.com/38844529/116168355-3060f100-a6d0-11eb-8c0c-e397763909b0.png)
![image](https://user-images.githubusercontent.com/38844529/116168370-39ea5900-a6d0-11eb-821a-f60c4a1c6081.png)
if i take out the debug id and put it back in, or put the lighter in i can open the door again

**Comment by timothymtorres** [comment]
I tested this out, and it appears to happen at roundstart as well.  I don't think the access gets setup properly because I had to remove an object from my wallet before I could properly access doors.
