### ISSUE TITLE
Shuttle Catastrophe appears to only choose Disco Inferno

### ISSUE THREAD

**Issue by Ryll-Ryll** [tgstation/tgstation#58754]
I've heard reports from a few admins and players that Disco Inferno has been appearing a lot lately as the escape shuttle for something that can't normally be bought, and their theory is that Shuttle Catastrophe seems to exclusively pick it for the new shuttle when the event is triggered. Opening this issue now so I remember to look into it in a few days

**Comment by ATH1909** [comment]
nice

~~feature~~
