### ISSUE TITLE
Can still see even while sleeping

### ISSUE THREAD

**Issue by CinzaFalso** [tgstation/tgstation#58786]
Round ID: [161161](https://scrubby.melonmesa.com/round/161161)

I got drunk to sleep and could still see, aside from the grey filter on the sight, probably because of my engineering scanner goggles set to mesons

I also noticed that using the engineering scanner goggles makes every tile that I can see because of it have maximum brightness, the file attached explains it better
![image_2021-04-28_050903](https://user-images.githubusercontent.com/50470024/116369521-d94a4180-a7df-11eb-84d6-bd162fe139f8.png)

**Comment by MrMelbert** [comment]
This is the exact same byond bug that lets blind people see, it's already reported

**Comment by CinzaFalso** [comment]
> This is the exact same byond bug that lets blind people (or people with a welding helmet, or people in crit, or unconscious people) see perfectly fine, it's already reported

I'll remove the issue then

**Comment by ArcaneDefence** [comment]
Presumably related to https://github.com/tgstation/tgstation/issues/52972
