### ISSUE TITLE
GAGS jumpsuits and shoes broke chameleon shoes/jumpsuit sprites

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#58782]
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
![image](https://user-images.githubusercontent.com/51932756/116343265-586c5500-a7a1-11eb-97cd-0cbdb0ac829d.png)
I am physically incapable of escaping this hell

**Comment by dragomagol** [comment]
To add to this: 
![image](https://user-images.githubusercontent.com/66640614/116345283-af236000-a79c-11eb-97c7-5c18ec938d46.png)

**Comment by maxymax13** [comment]
breaking everything vaguely related to shoes is just a small price to pay for having like 5 less sprites in the game guys

**Comment by LemonInTheDark** [comment]
breaking everything vaguely related to shoes is just a small price to pay for having like 5 less sprites in the game
