### ISSUE TITLE
Corazargh death glitch

### ISSUE THREAD

**Issue by fmakrid** [tgstation/tgstation#58800]
Reporting client version: 513.1542

## Round ID:
[161213](https://scrubby.melonmesa.com/round/161213)

## Reproduction: Apply Corazargh on you, drink some multiver and don't pump your heart, instead of expected instant death, your health will very slowly decline until you go into critical and die.
1) Apply Corazargh on you
2) Drink Multiver
3) Don't pump your heart
4) Instead of dying after the effect ends, you will notice that you didn't instantly die as expected, instead you slowly fall into critical and die eventually.

**Comment by D4C-420** [comment]
failing to pump your heart with corazargh reduces the amount of blood in you by 100. you at base have 560. You start taking oxygen damage at about 70-80% blood. With a recent merge corazagh has metabolism rate of  1u per cycle or in other words very high. combined with the drinking of multiriver which purges 3 u of non medicines means it just all left your system before you lost so much blood that you just plainly die.

**Comment by ATH1909** [comment]
were you an ethereal, by any chance?

**Comment by noobas32** [comment]
> failing to pump your heart with corazargh reduces the amount of blood in you by 100. you at base have 560. You start taking oxygen damage at about 70-80% blood. With a recent merge corazagh has metabolism rate of 1u per cycle or in other words very high. combined with the drinking of multiriver which purges 3 u of non medicines means it just all left your system before you lost so much blood that you just plainly die.

I kept losing blood after Corazargh was "purged" from my system, cmo who healed me kept asking where did all my blood go everytime you kept pumping more in me. It shouldn't be the case since i survived Corazargh effects.

**Comment by noobas32** [comment]
> were you a plasmaman or a jellyperson, by any chance?

I was a human
