### ISSUE TITLE
Revenants can join a team on the Medieval Simulation shuttle

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#58804]
Reporting client version: 513.1533

## Round ID:
[161245](https://scrubby.melonmesa.com/round/161245)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/116598169-5f977e00-a8db-11eb-8762-0b47e1b3c5db.png)

**Comment by ATH1909** [comment]
feature
