### ISSUE TITLE
Drinking glass.dm overlay issues

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#58833]
## Testmerges:
#58631 

## Reproduction:

Basically, whenever a glass is emptied due to drinking/spilling this ugly grey overlay will persist on the glass, there is no way to get rid of it and I kinda just ignored it for the last few months. Here is an image to show fresh glasses next to those with the odd overlay. 

![image](https://user-images.githubusercontent.com/16896032/116769148-6f4ec800-aa7d-11eb-8caf-61c18dcfa7fb.png)

**Comment by Twaticus** [comment]
fixed in #62920
