### ISSUE TITLE
Corgi swapped places with me diagonally between tables

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#58847]
Reporting client version: 514.1554

## Round ID:
[161393](https://scrubby.melonmesa.com/round/161393)

## Reproduction:

1. Set up the test chamber like this (the dogs on the tables presumably aren't necessary)
![](https://i.imgur.com/zSW9ZfI.png)
2. Eventually the dog on the other side of the tables will defy the rules and swap places with you

They can move you into a space you couldn't normally reach. Maybe this could be used to break into Centcom? Probably not.

**Comment by maxymax13** [comment]
> They can move you into a space you couldn't normally reach. Maybe this could be used to break into Centcom? Probably not.
if a mob can 4 dimensionally shift into another z level we've got a different problem

**Comment by ATH1909** [comment]
what if you replace one or both of those tables with walls?

are the corgis on those tables necessary?

**Comment by cacogen** [comment]
1. I'm not sure, didn't test it
2. Doubt it

**Comment by SuperNovaa41** [comment]
I believe this was fixed, cannot reproduce after 15+ minutes of sitting there.
