### ISSUE TITLE
PDAs can't be painted to "standard" aka assistant's PDAs

### ISSUE THREAD

**Issue by panvxv** [tgstation/tgstation#58842]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Insert PDA to PDA and ID painter and choose standard PDA. Remove PDA from machine and PDA is still the same as before.

**Comment by necromanceranne** [comment]
good

**Comment by Fikou** [comment]
not funny

**Comment by necromanceranne** [comment]
I was joking and re-read the issue. Yeah no this is a bug oops

**Comment by Greniza** [comment]
You're certain that the bug did not originate from attempting to repaint a head's PDA, which are not repaintable?
