### ISSUE TITLE
wooden drying racks require and consume power

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#58850]
it's literally a wooden construct (with no wiring whatsoever; ash walkers can craft it out of just wooden planks) that serves as a place for meat to dry out, how the fuck does it use or even RECEIVE power

**Comment by LemonInTheDark** [comment]
it's got a furnace, where do you think the heat comes from?

**Comment by necromanceranne** [comment]
but you build it entirely out of wood

**Comment by ArcaneDefence** [comment]
I literally pointed you to where it was changed and when

**Comment by LemonInTheDark** [comment]
> 
> 
> but you build it entirely out of wood

something something wooden wires

**Comment by ATH1909** [comment]
> I literally pointed you to where it was changed and when

yeah, but I couldn't find an explanation of WHY it was changed

**Comment by interestingusernam3** [comment]
Appears intentional, there is code to change how much power it uses and stuff.

**Comment by Mothblocks** [comment]
The code makes this seem intentional
