### ISSUE TITLE
All crew should spawn with a crowbar

### ISSUE THREAD

**Issue by Shellton123** [tgstation/tgstation#58862]
Can we make it so that all crew spawns with a crowbar so I dont get spawn camped by firelocks everytime someone blows up arrivals. Otherwise everytime I am spawn camped I must a help to get the firelock banned for no harm of own.

**Comment by interestingusernam3** [comment]
Why is this still open?

**Comment by Greniza** [comment]
you know, you can usually grab them from fire cabinets.

**Comment by SuperNovaa41** [comment]
Any feature requests should be put on the forums: https://tgstation13.org/phpBB/viewforum.php?f=9
