### ISSUE TITLE
Beating yourself with deeply fried objects leads to an error sprite

### ISSUE THREAD

**Issue by celotajstg** [tgstation/tgstation#58861]
## Reproduction:

1. Put anything in deep frier
2. Grab it from the deep frier
3. Switch to harm intent, attack self or someone/something
4. See this:
![image](https://user-images.githubusercontent.com/81999976/116826189-74099e00-ab9b-11eb-88e7-d0d8c7644ba2.png)

**Comment by dragomagol** [comment]
Duplicate of #58058
