### ISSUE TITLE
Wormhole Jaunters dont work

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#58889]
## Reproduction: 
Use a jaunter
Walk thru a wormhole without any effect
https://www.youtube.com/watch?v=MvFnGoX--sw

**Comment by rdragan** [comment]
Very likely caused by #58340 which was testmerged at the time.

**Comment by Livrah** [comment]
Same issue with hand tele portals.

**Comment by LemonInTheDark** [comment]
Pr's merged, so one would hope this isn't a thing anymore
