### ISSUE TITLE
you are unable to save any mutation from a disk to a console

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#58888]
Round ID: [161581](https://scrubby.melonmesa.com/round/161581)
BYOND Version: 513.1536
Server revision compiled on: 
Master commit: ae43a12d79e719751a8d0f0065d719385fa22c49
The following pull requests are currently test merged:
#58631: 'Adds new wrinkles to monkey brains' by ninjanomnom at commit 854d15a772

Repro: save a mutation to a disk
attempt to save this mutation to another computer
DNA Console beeps, "ERROR: This mutation is anomalous, and cannot be saved."

You can still save mutations from monkeymen to computers, it's just impossible to transfer them.

I looked in the code a little and it seems like a) you're prevented from saving any mutation with MUT_OTHER and b) every single mutation has MUT_OTHER in its little file

Except you're totally allowed to save them from monkeys to consoles, just not from disks to consoles.

@tralezab this seems like it's your fault and also that maybe #58815 might not stop you from saving special mutations to consoles

**Comment by ATH1909** [comment]
told ya so
