### ISSUE TITLE
felinids don't dislike gross and/or raw food

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#58887]
EDIT: https://github.com/tgstation/tgstation/pull/58110 made felinids not dislike gross and/or raw food like humans do, which may or may not be a feature, depending on how you look at it (felinids now don't dislike eating dead mice, for example).

**Comment by necromanceranne** [comment]
Oh shit, I don't have to take Deviant Tastes to enjoy mice anymore? 

Fucking FEATURE.

**Comment by ATH1909** [comment]
> Oh shit, I don't have to take Deviant Tastes to enjoy mice anymore?

Well, you technically just don't dislike them, as felinids don't explicitly have MEAT, GROSS, or RAW in their liked_food list (they're just not in their disliked_food list).

**Comment by ArcaneDefence** [comment]
https://github.com/tgstation/tgstation/blob/53353e5d3267eca8ae22b9444fde863905c0cf88/code/modules/mob/living/carbon/human/species_types/flypeople.dm#L1-L14

The first complaint isn't present in the repo, and no, I wasn't deliberately allowing for felinids to eat gross things.

**Comment by ATH1909** [comment]
> https://github.com/tgstation/tgstation/blob/53353e5d3267eca8ae22b9444fde863905c0cf88/code/modules/mob/living/carbon/human/species_types/flypeople.dm#L1-L14
> 
> The first complaint isn't present in the repo, and no, I wasn't deliberately allowing for felinids to eat gross things.

Huh, you're right, https://github.com/tgstation/tgstation/pull/58414 fixed it. I'll update the name of this issue, then.
