### ISSUE TITLE
flypeople dislike eating moffins

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#58893]
moffins are the ONLY food in the game (aside from clothes, which flypeople physically cannot eat) that flypeople disike eating, and it's not very clear why. they're a species that literally eats trash, for god's sake.

**Comment by ArcaneDefence** [comment]
It's funny to me that a race that regularly eats things so that they can vomit and then eat the puke would be disgusted by eating cloth.

**Comment by Time-Green** [comment]
I think it's because CLOTH is a new foodtype and flypeople weren't adjusted to tolerate it
