### ISSUE TITLE
Rust Heretic's mansus grasps bypasses a Durand's energy shield and can one-shot Nukie/CentCom Mechs

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#58909]
## Reproduction:

1. Spawn/Build a Durand
2. Spawn/Guide a Rust-Heretic to the Durand, ask the pilot to turn their energy shield on
3. Attack the Durand's shield with your mansus grasp, the Durand is instantly obliterated
4. Additionally, spawn a Nuke/CentCom Mech (Marauder/Dark Gygax/Mauler) and watch a 140 TC Mech get one-shot by a early-game Heretic. 

## Description: 

The Rust Heretic's attack can completely bypass a Durand's energy shield which doesn't make a whole heap of sense ICly; an energy shield can't _rust_ unlike the metal frame and components of a mech, and balance-wise the Durand's shield can be dodged fairly easily if it's in the open (especially as Durands have tank controls and can't move diagonally) or whittled down with other weaponry if it's hunkered down in a maintenance corridor. 

Also, Nukie/Deathsquad Mechs can be instantly destroyed by the Rust Heretic's mansus grasp which seems a little too much considering it's a infinite recharging spell bought pretty early on by heretics. Maybe the Grasp should abide by Melee/Energy armor values so while it'd still be an extremely powerful anti-silicon/Mech weapon, it wouldn't let you instantly win with no drawback every time.

**Comment by Serxule** [comment]
this is definitely not intended since I've killed rust heretics in a _ripley_ before, and their grasp usually did next to nothing. unless there was a rust heretic buff that i didn't hear of

**Comment by ATH1909** [comment]
> this is definitely not intended since I've killed rust heretics in a _ripley_ before, and their grasp usually did next to nothing. unless there was a rust heretic buff that i didn't hear of

are you sure you were fighting a heretic whose initial path was the rust path (and who didn't just tech over to the rust features from another path?)

**Comment by Serxule** [comment]
> are you sure you were fighting a heretic whose initial path was the rust path (and who didn't just tech over to the rust features from another path)?

are you talking about an ascended rust heretic? because i was fighting a non-ascended one (he was rust path, only had rust abilites)

**Comment by D4C-420** [comment]
the rust heretic's manses grasp does like what 500 damage to non-organic matter (ie silicon's, objects, structures.) I have had a few mechs completely broken by a rust heretic before I'm pretty sure its intended because breaking stuff apart is kind of the rust heretics thing.

**Comment by necromanceranne** [comment]
> this is definitely not intended since I've killed rust heretics in a _ripley_ before, and their grasp usually did next to nothing. unless there was a rust heretic buff that i didn't hear of

It's probably because it was deflected.
