### ISSUE TITLE
PDA continue to stay red even if you put an ID in them.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#58913]
Reporting client version: 513.1536

## Round ID:
[161684](https://scrubby.melonmesa.com/round/161684) (Started before this round)

## Testmerges:
Manuel

## Reproduction:
Title says it all.

**Comment by MrMelbert** [comment]
Same issue as #58913 i'd bet

**Comment by tf-4** [comment]
should be fixed with https://github.com/tgstation/tgstation/pull/58892
