### ISSUE TITLE
Changeling stings can be done from any range

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#58925]
## Round ID:
Reproduced on local

## Reproduction:
All changeling stings can be done from any visible range

**Comment by Serxule** [comment]
doesnt this mean it would work over cameras

**Comment by dragomagol** [comment]
Yes

**Comment by TheBonded** [comment]
Feature

**Comment by ATH1909** [comment]
I'm now imagining a changeling gamer just sitting in front of a camera console in a corner of maint, sipping changeling sting and turning everyone into catgirls through the cameras
