### ISSUE TITLE
Issue with the derilect drones and the station drones

### ISSUE THREAD

**Issue by Jamarkus127** [tgstation/tgstation#58927]
Reporting client version: 514.1552

## Round ID:
[161755](https://scrubby.melonmesa.com/round/161755)

## Reproduction:

The new change drone change  completely messed up the derelict drone functionality. I cannot interact with any objects and instead of being able to repair the station and give it power and atoms and all the other good stuff,  it becomes a game of patch the holes and that's it. they should be separate from the station drones and be the same as the old drones, since they worked just fine beforehand

**Comment by timothymtorres** [comment]
This strikes me as more a feature/rebalance request than a bug report.
