### ISSUE TITLE
Tramstation: Nuke Disc lost upon Z-Level change

### ISSUE THREAD

**Issue by Farquaar** [tgstation/tgstation#58921]
## Reproduction: 

1. Take dat fukken disk
2. Drop down into the lower Z-level
3. Realize that the disk is gone
4. Go back to Captain's office to find the respawned disk

I haven't taken steps to verify whether this was only a one time thing, but me and the other nukie grabbed the disk, went to the lower Z-level, escaped the station through maint, and realized when we got to the ship that the disk had reset. (We raided the station again and grabbed the disk from the captain's office, which worked. I wasn't carrying the disk that time though)

**Comment by TheBonded** [comment]
The disk respawned in the captain's room? that's surprising, since it should spawn in a random room anywhere on the station

**Comment by Farquaar** [comment]
> 
> 
> The disk respawned in the captain's room? that's surprising, since it should spawn in a random room anywhere on the station

That's where we found it. I wasn't the one who picked it up, but me and my partner ran into the cap's office guns blazing, and my partner grabbed the disk while I covered them.

**Comment by SuperNovaa41** [comment]
This isn't really a bug.. but definitely one of the many things we need to fix with multi-z

**Comment by Wayland-Smithy** [comment]
can't reproduce, stationloving component's `is_station_level()` check is passing when I use the stairs:

![AKmbEhI2Mv](https://user-images.githubusercontent.com/64715958/124487228-4c81ae00-dd63-11eb-8327-a5dd06e9d37f.gif)

**Comment by Farquaar** [comment]
> 
> 
> can't reproduce, stationloving component's `is_station_level()` check is passing when I use the stairs:
> 
> ![AKmbEhI2Mv](https://user-images.githubusercontent.com/64715958/124487228-4c81ae00-dd63-11eb-8327-a5dd06e9d37f.gif)

I believe we used a ladder. Maybe we jumped off a ledge. Definitely didn't use the stairs.

**Comment by Wayland-Smithy** [comment]
Same story there too, the checks happen when I change levels and they pass:
![aRMrpQybqG](https://user-images.githubusercontent.com/64715958/126913982-ab6c5354-6b08-47bd-a46a-a80a019eeb26.gif)
![ERvz1lpEph](https://user-images.githubusercontent.com/64715958/126913984-b72669c4-96e2-4daf-9155-a90ca0a35528.gif)
I can only guess that TramStation had not properly defined the "station z-levels" in the past, but it does now.

**Comment by Farquaar** [comment]
> 
> 
> I can only guess that TramStation had not properly defined the "station z-levels" in the past, but it does now.
Fingers crossed. Might also just have been a one-off fluke.

**Comment by timothymtorres** [comment]
This could be related to #54779

**Comment by timothymtorres** [comment]
I tried to replicate this and couldn't.  Was it ever possible to jump to the bottom z-level from outside the station?
