### ISSUE TITLE
CRAB-17s can be instantly destroyed upon landing, do not unlock credit withdrawal even after being destroyed

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#58933]
Reporting client version: 513.1537

## Round ID:
[161760](https://scrubby.melonmesa.com/round/161760)

## Reproduction:
I saw the CRAB-17 drop pod location after hearing the noise, so I put a crate down under it. I also hit it with my ID the moment it dropped. No clue which of the two caused it to instantly explode.

Afterwards I was unable to withdraw any credits and any attempts brought up the chinese(?) text that happens when you try taking your credits out while there is an active CRAB-17

**Comment by NanoCats** [comment]
I can confirm this bug has happened to me. It'd be cool if somebody made it a feature that something good happens for you if you are the first one to bonk a landed crab machine with your ID.
