### ISSUE TITLE
Blind people can use the SecurEye app on modular computers

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#58936]
## Reproduction: Use the SecurEye app while blind 
![image](https://user-images.githubusercontent.com/54517726/117504334-48e2ce00-af50-11eb-995a-abe54e124dc5.png)

**Comment by itseasytosee** [comment]
Ooh, also the detective's spy bug.

**Comment by interestingusernam3** [comment]
JUSTICE is blind

**Comment by timothymtorres** [comment]
I tried fixing this with #66285 but maintainer ruling to not restrict blind people so I'm closing this.  I really feel like this is a bug though.
