### ISSUE TITLE
Explode is written as Expldoe in a code comment

### ISSUE THREAD

**Issue by NamelessFairy** [tgstation/tgstation#58949]
## Reproduction:

tgstation/code/datums/components/explodable.dm features the word "expldoe" in its comments, this is a clear spelling error and reduces code comment readability very slightly

**Comment by ArcaneDefence** [comment]
https://github.com/tgstation/tgstation/blob/82a429ef8233c6660efdcd794faf0725a4b1943e/code/datums/components/explodable.dm#L127
Suffering

**Comment by Qustinnus** [comment]
![image](https://user-images.githubusercontent.com/20987591/117893293-6d290c80-b2ba-11eb-8618-090997197a25.png)
what did he mean by this
