### ISSUE TITLE
Build.Bat error

### ISSUE THREAD

**Issue by mr0wnpie** [tgstation/tgstation#58970]
Build.bat is experiencing an error when building the server

Using vendored Node v12.20.0
Starting CBT in Standard Build mode.
 => Skipping 'yarn' (up to date)
 => Skipping 'tgfont' (up to date)
 => Skipping 'tgui' (up to date)
 => Starting 'dm'
Error: spawn dm.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn dm.exe',
  path: 'dm.exe',
  spawnargs: [ 'tgstation.mdme' ]
}
killed child process
Press any key to continue . . .

I cant for the life of me even begin to understand this as im so new to codeing. Ive redownloaded multiple times and The .BAT cant work when run as administrator. Im not sure what step to take next as I cant find any other posts online with this issue

UPDATE:
The nice people on the TG station discord, mainly KylerAce#5627,
told me I should use byond version 1536, and it solved all my issues. thanks!

**Comment by dragomagol** [comment]
Resolved
