### ISSUE TITLE
Cant Roll things and cut things as the cook

### ISSUE THREAD

**Issue by Peenler** [tgstation/tgstation#58982]
Reporting client version: 513.1542

**Comment by SethLafuente** [comment]
No longer a bug as shown here probably for a while cooks have been able to do this I have seen
![zPjiIUZ](https://github.com/tgstation/tgstation/assets/84478872/e9973cfa-9584-49b9-b724-937737c50281)


Using a knife to cut and rolling dough are pretty standards
