### ISSUE TITLE
Blob Spores ignore Rally attempts

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#58999]
Reporting client version: 513.1542

## Round ID:
[161941](https://scrubby.melonmesa.com/round/161941)

## Reproduction:
Drop a factory down as a blob and attempt to rally your spores. 
Be sad that your spores ignore every attempt to rally so long as they are on a blob tile.
Remove blob tiles just to order your spores.

**Comment by RaveRadbury** [comment]
duplicate of #56742
