### ISSUE TITLE
Coniine is broken

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#59013]
Reporting client version: 513.1536

## Round ID:
(Don't have it with me)

## Testmerges:
- [Removes bad return from processables that broke cooking ðŸ€](https://www.github.com/tgstation/tgstation/pull/58983)

## Reproduction:
Coniine seems to cause anyone that has it to suffocate forever, even after it gets out of their system.

**Comment by Iamgoofball** [comment]
i will need to check the old goon chemistry stats to see if I botched it or if I did it correctly
