### ISSUE TITLE
Bike horns do not honk

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#59016]
## Reproduction:

1. Be clown (optional but ideal)
2. Attempt to Honk by use of your trusty bike horn
3. [Notice glaring lack of honk]
4. I have no bike horn and I must honk

**Comment by NanoCats** [comment]
> priority: critical

unironically yes

**Comment by ATH1909** [comment]
> > priority: critical
> 
> unironically yes

same

**Comment by SuperNovaa41** [comment]
Did you have ingame instruments/some other sound setting turned off?

**Comment by NanoCats** [comment]
> Did you have ingame instruments/some other sound setting turned off?

I do not.

**Comment by Kylerace** [comment]
most likely another connect_loc bug (number 11 or 12 by my count), ill look into it
