### ISSUE TITLE
Blind people can see heads on spears

### ISSUE THREAD

**Issue by rageguy505** [tgstation/tgstation#59037]
## Reproduction:  Be blind and look at a head on a spear

![image](https://user-images.githubusercontent.com/54517726/117757614-6765f500-b1ee-11eb-8922-82cb4fe64080.png)

**Comment by ATH1909** [comment]
ominous

**Comment by ATH1909** [comment]
can you shoot at and/or TK them?

**Comment by Baskett55** [comment]
im pretty sure you can manipulate objects/shoot by just clicking while blind. blindness isnt like the fog of war.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/79b0e91f6cc015af484069ff19cfadb7c3a90eb4/code/game/objects/structures/headpike.dm#L46-L54
