### ISSUE TITLE
stuff in seethrough pods/item attack animations are black

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#59040]
## Reproduction:

spawn seethrough supply pod with an item
item is full black until it lands

attack someone with item
item is full black on the animation

**Comment by Sealed101** [comment]
excuse the fucked up export but
seems to have been fixed

https://github.com/user-attachments/assets/72317cc1-8201-4f07-90d2-13c55a7f24b0

relevant code doesn't seem to have changed, The Plane Cube could have fixed it
https://github.com/tgstation/tgstation/blob/f3f13d35b1ae2eb4b9c91e4918d3e27d34c41d30/code/modules/cargo/supplypod.dm#L197-L207
