### ISSUE TITLE
Janicart Refill Strike

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#59072]
## Round ID: [162111](https://scrubby.melonmesa.com/round/162111)
162111

## Reproduction:

Take a filled bucket and try refilling your janicart. It fills, but also applies the combat smack sound, animation and extra-long hit delay. Very annoying.

**Comment by rdragan** [comment]
Not sure when or what exactly changed in the attack chain, but there's actually a bunch of these affecting random objects, I think it mostly happens when it's being handled in the object being hit.

**Comment by maxymax13** [comment]
same with non-cart mop bucket

**Comment by ShizCalev** [comment]
fixed by #64818
