### ISSUE TITLE
Bloodsuckers get stuck at level 7

### ISSUE THREAD

**Issue by JohnFulpWillard** [tgstation/tgstation#59085]
## Testmerges:

TGU - Gamemode removal, GAGS & More #159

## Reproduction:

Get to level 7
Close a coffin
Rank up to level 7 again
Enter Sol
Rank up to level 7 again
It's level 7 Bloodsucker hell.

If anyone can fix this, be my guest. I haven't looked into it yet but I'm putting this issue up so I don't forget about it.

**Comment by ArcaneDefence** [comment]
![image](https://user-images.githubusercontent.com/51932756/118086875-e2134980-b381-11eb-87d4-34366ec8aa6c.png)

**Comment by JohnFulpWillard** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/51932756/118086875-e2134980-b381-11eb-87d4-34366ec8aa6c.png)

oh fuck's sake wrong codebase
