### ISSUE TITLE
A regal rat test can fail spontaneously

### ISSUE THREAD

**Issue by interestingusernam3** [tgstation/tgstation#59086]
## Round ID:
N/A - this is an integration test bug. The fail occurs here: https://github.com/tgstation/tgstation/runs/2573850974

## Testmerges:
N/A

## Reproduction:
1. Don't touch anything related to regal rats
2. Make PR
3. Get unlucky
4. It fails integration tests related to regal rats
5. Push empty commit
6. Now it doesn't fail

**Comment by dragomagol** [comment]
Should be fixed by #59061
