### ISSUE TITLE
Golems cannot process mutation toxin

### ISSUE THREAD

**Issue by GoblinBackwards** [tgstation/tgstation#59111]
## Reproduction:
Be golem
Drink mutation toxin (only tested with stable but may happen with other types)
Scan your chems
Wait
Scan your chems again and see the mutation toxin is doing nothing

**Comment by MrMelbert** [comment]
![image](https://user-images.githubusercontent.com/51863163/118343848-e9a53080-b4f0-11eb-8e5f-9e000b0de671.png)
This is intentional afaik, only organic carbons can process mutation toxin (only wood golems are organic)
