### ISSUE TITLE
Tramstation Aux Base Construction Drone turned into Advanced Security Camera

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#59119]
Reporting client version: 513.1542

## Testmerges:
- [Fix issues I created where dynamic gives out multiple incorrect antag datums to ineligible people and gives 1 too many traitor objectives.](https://www.github.com/tgstation/tgstation/pull/59099)

## Reproduction:
Join tramstation.
Go to Aux Construction and see the construction drone outside of the construction site.
Use the console to attempt to place, walls, turrets, tiny fans, windows, doors.
Fail to see any option to construct or deconstruct.
Take the drone on an adventure outside of the base since it seemingly has infinite range and vision wherever cameras are.

**Comment by TheBonded** [comment]
~~Feature~~

Also, the console on the wall inside is placed on the tile south of it, so you can't walk in that location. had to have an admin move the console down with Translate -30 Y-axis. this might also happen on icebox, since that's a multiz station too

**Comment by TheMidnightRose** [comment]
The console itself was down a tile, the sprite of the console was on the wall as it should. The Translate I did moved the sprite properly over where it actually way, then I moved it back onto the wall.

**Comment by TheBonded** [comment]
it seems like the console being down a tile is consistent with other maps, as the console itself spawns either above or below the wall, whereas the sprite spawns on the wall
