### ISSUE TITLE
gorilla wizards can't use teleportation scrolls

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#59128]
if you use your magic mirror as a wizard to become a monkey, then have an apprentice use that mirror to become a uranium golem, then have your apprentice punch you a LOT while you stand next to a medibot, then wait for a while (the length you need to wait is RNG-dependent), you can become a gorilla wizard (without using a staff of change or the like). unfortunately, you can't use a teleportation scroll as a gorilla wizard, which is very disappointing.

this can also softlock you, because not only will your spellbook not recognize your gorilla form as being you, but even if you did somehow get an unbound spellbook, gorillas (and monkeys, it appears) can't actually buy spells from it. very sad!

**Comment by timothymtorres** [comment]
I lol'd at this issue.  You really like to try and break the code as much as possible eh?

**Comment by TheBonded** [comment]
why is this not closed yet, if it's not a bug
