### ISSUE TITLE
wizard sandals have laces, apparently

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#59126]
and you can tie them together

**Comment by TheBonded** [comment]
Feature

Seriously, what's the issue here? Working as intended

**Comment by ATH1909** [comment]
what kind of sandals (let alone wooden ones) have laces???

**Comment by TheBonded** [comment]
> what kind of sandals (let alone wooden ones) have laces???

Velcro

**Comment by TheBonded** [comment]
also they are magic, do you really think wizards would wear normal sandals?

**Comment by interestingusernam3** [comment]
Failed to reproduce, and sandals have can_be_tied = FALSE in the code.

**Comment by ATH1909** [comment]
> Failed to reproduce, and sandals have can_be_tied = FALSE in the code.

Weird, I was able to do this while I was testing some things with Shadok.

**Comment by interestingusernam3** [comment]
I tested it on a braindead human wizard and there was no button for untying shoestrings on sandals.
