### ISSUE TITLE
Sentience Fun Balloons do not activate

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#59136]
Reporting client version: 513.1542

## Round ID:
[162315](https://scrubby.melonmesa.com/round/162315)

## Testmerges:
- [Toggles harddel searching for use on live [DNM]](https://www.github.com/tgstation/tgstation/pull/59118)

## Reproduction:
Make some mobs at the docks for after round chaos as an admin.
Drop a Sentience Fun Balloon for offering them all to ghosts.
Complete the TGUI checklist it gives, notice that you cannot change the range.
Attempt to activate and be sad that it never does.

**Comment by dragomagol** [comment]
It works half the time and I don't know why. I'll dig into this.

**Comment by dragomagol** [comment]
I'm still working on a solution, but to get it to work in the meantime you have to either be next to the balloon as a ghost or have AI interact on.
