### ISSUE TITLE
Bloody footprints can spam the runtime log.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#59137]
## Testmerges:
- #59002 
- #59099 
(Neither should be applicable to this since it showed up on a local)

## Reproduction:
1. Start bleeding
2. Walk over the resulting bloodsplatter
3. Walk around to create bloody footprints
4. Walk over more bloodsplatter
5. Walk over the previous bloody footprints
6. `Attempted to add a new component of type [/datum/component/forensics] to a qdeleting parent of type [/obj/effect/decal/cleanable/blood/footprints]!`

With enough players and enough blood this can cram the runtime log with several hundred instances of the warning.

**Comment by interestingusernam3** [comment]
Possibly caused by #58918

**Comment by Sealed101** [comment]
doesn't seem to be the case now
