### ISSUE TITLE
Wiki page for mophs outdated and possible slurred speech bug

### ISSUE THREAD

**Issue by panvxv** [tgstation/tgstation#59134]
## Round ID:
[162309](https://scrubby.melonmesa.com/round/162309)

## Reproduction:
Wiki page on morphs is outdated- morphs deal 20 damage not 30(but from my round experience they should as putting someone to crit in 5-6 hits as slow as fuck mob is hard). It also seems that morphs no longer have slurred speech as wiki says.

**Comment by Mothblocks** [comment]
If the problem is the wiki is *outdated*, then you just fix it yourself--this repo is not in control of the wiki.

If the problem is the wiki is *correct*, but the code regressed, then an issue is warranted.

**Comment by panvxv** [comment]
Myself I can't find anything about slurring but checking races like lizardpeople I couldn't either so I just don't know where to find it. So this can be a bug.

I have done some testing and found new bug: everytime you attack as morph you receive message "You're already in your normal form!". It just spam your chat with this message.

**Comment by Mothblocks** [comment]
Can you file that bug individually? Bug reports should be for one bug each, that way we can close them individually.

**Comment by panvxv** [comment]
I will
