### ISSUE TITLE
Genetics console bluescreened for everyone.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#59153]
Reporting client version: 513.1536

## Round ID:
[162370](https://scrubby.melonmesa.com/round/162370)

## Testmerges:
- [Fixes sound loops not well, stopping. ](https://www.github.com/tgstation/tgstation/pull/59138)
- [Popper Tooltips 2 (they don't crash this time)](https://www.github.com/tgstation/tgstation/pull/58980)

## Reproduction:
one of the genetics consoles decided to show up as a bluescreen for everyone, making the mutations on it inaccessible and making genetics a bit of a pain.

**Comment by dragomagol** [comment]
Closing this issue since the duplicate has a picture of the error
