### ISSUE TITLE
Bureaucratic Error causes all job slots except assistant and the error job to completely close

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#59159]
Reporting client version: 513.1536

## Round ID:
N/A

## Testmerges:
- [Fixes sound loops not well, stopping. ](https://www.github.com/tgstation/tgstation/pull/59138)
- [Popper Tooltips 2 (they don't crash this time)](https://www.github.com/tgstation/tgstation/pull/58980)

## Reproduction:
I've seen this more than once, so something is causing this, even if it isn't Bureaucratic Error.

**Comment by MrMelbert** [comment]
This is intentional / not a bug, it's how bureaucratic error works

**Comment by TheBonded** [comment]
Everyone must be assistant. Greytide stationwide

**Comment by redguy999** [comment]
> This is intentional / not a bug, it's how bureaucratic error works
For various reasons, this seems like a bad idea.
This would also close the AI slot if there was no AI, no?

**Comment by TheBonded** [comment]
> > This is intentional / not a bug, it's how bureaucratic error works
> 
> For various reasons, this seems like a bad idea.
> This would also close the AI slot if there was no AI, no?

It does not close the AI slot, I have seen this happen
