### ISSUE TITLE
Malf AI roundstart ruleset can cause two AIs to spawn

### ISSUE THREAD

**Issue by BlueMemesauce** [tgstation/tgstation#59157]
Reporting client version: 513.1536

## Round ID:
[162385](https://scrubby.melonmesa.com/round/162385)

## Testmerges:
- [Lighting list cleanup.](https://www.github.com/tgstation/tgstation/pull/59002)
- [Fixes sound loops not well, stopping. ](https://www.github.com/tgstation/tgstation/pull/59138)

## Reproduction:

- Malf AI roundstart ruleset chosen from those with the antag preference enabled
- Normal AI chosen from those with the job preference enabled
- There are now two AIs, a malf AI and a normal AI
- The AIs will spawn in separate spots in the AI chamber 

Most likely caused by the PR that moved malf AI to its own ruleset: https://github.com/tgstation/tgstation/pull/59064

**Comment by Timberpoes** [comment]
Thanks for the report. I grabbed all the info I needed to confirm the issue from the round ID's logs and have put a fix up.
