### ISSUE TITLE
Metallic Hydrogen Golems not spaceproof

### ISSUE THREAD

**Issue by NoelleDay247** [tgstation/tgstation#59151]
## Round ID:
[162370](https://scrubby.melonmesa.com/round/162370)

## Reproduction:
Golems made of Metallic Hydrogen are not immune to pressure (and/or temperature) damage from space exposure. 
This may be an issue specific to Metallic Hydrogen golems created through Pride's Mirror. Issue was found immediately after the transformation, since the mirror teleports you into space as it transforms you.

**Comment by Ghilker** [comment]
The golems are purposely not space proof and can take cold damage, so this is not a bug
