### ISSUE TITLE
Wonky Admin Pod Launcher UI Bluescreen

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#59162]
## Testmerges:

#58980

## Reproduction:

Happens whenever anything is hovered over. Probably caused by the tooltip TM.

![image](https://user-images.githubusercontent.com/51863163/118429830-38d99580-b698-11eb-8a42-f87a1f20c492.png)

**Comment by Mothblocks** [comment]
This happened with the last popper tooltips, I don't remember how but I remember podlaunchers having weird tooltips that I didn't find automatically.

**Comment by MrMelbert** [comment]
mfw I report a testmerge bug and it gets merged anyways
🥴

**Comment by Mothblocks** [comment]
well i didnt see it
