### ISSUE TITLE
Genetics consoles bluescreen when trying the adv injector button is pressed.

### ISSUE THREAD

**Issue by RyanleeThompson** [tgstation/tgstation#59173]
## Round ID: [162444](https://scrubby.melonmesa.com/round/162444)

Genetics consoles bluescreen when trying to create advanced injectors, making the console unusable for the rest of the round as well as not being able to create advanced injectors. This isn't the first round this has happened but I'm just now reporting it. 

![image](https://user-images.githubusercontent.com/57112359/118577535-333f8680-b750-11eb-9817-7003cf8b5ff7.png)

## Testmerges:

#59138: 'Fixes sound loops not well, stopping. ' by LemonInTheDark at commit d9ffe9985d
#59118: 'Toggles harddel searching for use on live [DNM]' by LemonInTheDark at commit 550d20f8c8

## Reproduction:

Simply try to use the advanced injector button on genetics consoles.

**Comment by RyanleeThompson** [comment]
Report #59153 details the same issue

**Comment by dragomagol** [comment]
Seems to be the same error message as #59161

**Comment by NanoCats** [comment]
This issue also afflicts the HOP console, just fyi.

**Comment by Eggbertx** [comment]
Does BYOND have any way to use source maps? I'm not really familiar with /tg/station's codebase, but source maps would make it a lot easier to debug the stack trace, and I know that Webpack can use them.
