### ISSUE TITLE
AI can Delta from card (and apparently, pinpointers don't point to it?)

### ISSUE THREAD

**Issue by Mirino97** [tgstation/tgstation#59177]
Yeah, really title says it all. This GOTTA be a bug.

## Round ID:
[162452](https://scrubby.melonmesa.com/round/162452)

## Testmerges:

N/A

## Reproduction:

1: Be Malf
2: Harvest 120 points
3: Be carded first
4: Activate Delta 
5: Tell your borg to kill the person who carded you
6: The corpse is now your own mobile core, as long as you tell your borg to carry the corpse around
7: ???
8: Profit!

**Comment by InsaneRed** [comment]
5: Tell your borg to kill the person who carded you why would you even do this, just get carded by a traitor and let them run around (borg can be exploded to stop you and you will probably die to from the borg blowing up) and i think you being able to use mafl abilities is intended (in card form)

**Comment by Mirino97** [comment]
I wouldn't mind if it's intended, actually. This Issue is more like a reflex of a round that happened yesterday BUT at least they should be trackable by pinpointer or it's really OP.

**Comment by ATH1909** [comment]
you can end the delta from this by coring and then re-carding the AI who's delta'ing; I did that in an IAA round on fulp.

**Comment by Mirino97** [comment]
That is true, but that is IF if you find the Traitor, who's carrying the carded AI, which will be very hard, since you can't pinpoint to it.

**Comment by zxaber** [comment]
Issue is mostly caused by the fact that doomsday just checks for shunt. These ought to be replaced with checks on if the AI is sitting on the floor.
