### ISSUE TITLE
Cannot Disable Ambient Occlusion

### ISSUE THREAD

**Issue by Malkraz** [tgstation/tgstation#59181]
Reporting client version: 513.1539

## Round ID:
[162461](https://scrubby.melonmesa.com/round/162461)

## Testmerges:
- [Fixes sound loops not well, stopping. ](https://www.github.com/tgstation/tgstation/pull/59138)
- [Turns lighting objects into a datum, makes all lighting be performed with an underlay. big maptick fix very good!](https://www.github.com/tgstation/tgstation/pull/58991)

## Reproduction:
Attempt to disable Ambient Occlusion

**Comment by LemonInTheDark** [comment]
What exactly do you mean? this is very vague

**Comment by Qustinnus** [comment]
it is very vague what im guessing he means is that he tried disabling ambient occlusion in prefs and the filter isn't removed. this might be caused by my plane master changes.

good luck.

**Comment by Qustinnus** [comment]
it is very vague what im guessing he means is that he tried disabling ambient occlusion in prefs and the filter isn't removed. this might be caused by my plane master changes.

good luck.
