### ISSUE TITLE
Changeling Monkey Power - Flesh Suit Interaction

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#59182]
## Round ID: 
[162483](https://scrubby.melonmesa.com/round/162483)

## Reproduction:

Changelings that have a flesh clothes disguise (So any changeling basically) that turn into monkeys do not remove those nodrop clothes, leaving a changeling unable to hide/use vent crawl. Probbably related to that PR that refactored monkeys not considering all powers/interactions with monkeys

**Comment by MrMelbert** [comment]
Related issue: #56069
