### ISSUE TITLE
If a AI gets pied the screen goes blurry but the blurr isnt removed when the AI core is cleaned

### ISSUE THREAD

**Issue by techno0** [tgstation/tgstation#59197]
If a AI gets pied the screen goes blurry but the blurr isnt removed when the AI core is cleaned. This is a shitty effect because it gives me and other a headache looking at this shitty blurr effect even when you got someone to clean the core.

**Comment by TheBonded** [comment]
I'm pretty sure this is intended (and funny)

**Comment by TheBonded** [comment]
> How can this be intended, this is like getting your eyes damaged and the screen going dark but they screen never returns to normal after the eyes are being healed.

Well, it's a well known thing that happens, and if it was a bug it'd've been reported and squashed by now

**Comment by dragomagol** [comment]
It was reported in #55670 and apparently fixed, but something must have broken it again

**Comment by ATH1909** [comment]
Here we go agaaaaain (I kinda wanna be more than frieeends)
