### ISSUE TITLE
Corgis can fetch any pullable object

### ISSUE THREAD

**Issue by SgtHunk** [tgstation/tgstation#59202]
## Round ID:

[Round ID]: N/A

## Reproduction:
Reported on Fulpstation running on TG PR https://github.com/tgstation/tgstation/pull/58822 as latest.

Corgis can fetch anything that can be pulled like lockers and IV drips, and ignore directional windows, so they can fetch through walls as long as the item is adjacent.
This is both hilarious and game-breaking once you realize Ian can get a clown car in his mouth and make everyone in the car suffocate because of it

![unknown-32.png](https://user-images.githubusercontent.com/68669754/118903415-bf36e700-b8e5-11eb-8610-4f39ab6faa2c.png)
![unknown-39.png](https://user-images.githubusercontent.com/68669754/118903459-d4ac1100-b8e5-11eb-8d19-e7a4bce6bc1e.png)

**Comment by TheBonded** [comment]
Feature

**Comment by maxymax13** [comment]
ian fetch me that SM shard

**Comment by maxymax13** [comment]
> 
> 
> > Feature
> > damn right
> > ![unknown-40.png](https://user-images.githubusercontent.com/68669754/119010508-1ed2d800-b962-11eb-9763-2b6e69b08c21.png)

\>newfriends all calling ian "the dog"
sure is fulp alright

**Comment by ATH1909** [comment]
amazing

can Ian fetch something that he's inside of?
