### ISSUE TITLE
PDAs can have a spinning E overlay

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#59211]
Reporting client version: 513.1533

## Round ID:
[162598](https://scrubby.melonmesa.com/round/162598)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/119021244-0d82cf00-b954-11eb-8919-0a572539b630.png)

No clue what causes this, but it was only on some PDAs

**Comment by NoxVS** [comment]
I saw the same thing happen to someone else, reportedly caused by a multitool, but I couldn't reproduce it after I saw it.

**Comment by KubeRoot** [comment]
Mine have it whenever I have an unread message. The weird e also briefly appeared on my character, seemingly at random, when moving items around.

**Comment by TheBonded** [comment]
> Mine have it whenever I have an unread message. The weird e also briefly appeared on my character, seemingly at random, when moving items around.

it also appears on the same frame it would be perfectly flat if you are holding a screwdriver

**Comment by maxymax13** [comment]
which one of you coders did this, it's like the clothing error sprites except even less helpful

**Comment by dragomagol** [comment]
> 
> 
> Mine have it whenever I have an unread message. The weird e also briefly appeared on my character, seemingly at random, when moving items around.

That's a likely cause, seems to be related to messaging.

**Comment by maxymax13** [comment]
i saw it when a do_after bar tried to show up when i was building a dish drive a few days ago

**Comment by dragomagol** [comment]
Appears to have been fixed
