### ISSUE TITLE
Can't move one tile away from person you are aiming at with gun without breaking aim

### ISSUE THREAD

**Issue by panvxv** [tgstation/tgstation#59227]
## Round ID:
Tested locally

## Reproduction:
Have a gun and be next to someone. Right click him to aim. Try to move one tile away from him and realise you broke aim.

In code of gunpoint is:

/// How many tiles around the target the shooter can roam without losing their shot
#define GUNPOINT_SHOOTER_STRAY_RANGE 2

**Comment by Sealed101** [comment]
works fine ever since #74036 if not earlier
