### ISSUE TITLE
Ian's hat stuck on his head

### ISSUE THREAD

**Issue by Verril** [tgstation/tgstation#59224]
Reporting client version: 513.1542

## Reproduction:

I really don't know how to reproduce it, as it's just something that's happened, essentially, I have an Ian that I made sentient via slime sentience potion,  (could be what's causing it)  and his hat is unremovable, and I have confirmed it's not an issue unique to me, as another player was unable to remove it either, my best guess is that it's a result of using a sentience potion while Ian has a hat.

**Comment by Verril** [comment]
(For clarification, it was a standard HoP hat)

**Comment by Mooshimi** [comment]
I got a science beret stuck on a not sentient Ian, had to be admin deleted.

**Comment by Sealed101** [comment]
fixed in #62318 i think

**Comment by Sealed101** [comment]
the hats can be taken off freely, but the corgi's sprite doesn't update the lack of a hat.
