### ISSUE TITLE
"Escaped the station" without escaping the station during Dynamic Nuclear Explosion

### ISSUE THREAD

**Issue by Pandarsenic** [tgstation/tgstation#59237]
## Round ID:

If you discovered this issue from playing tgstation hosted servers:
[Round ID]: # 162665

## Reproduction:

Be a traitor with 2 kills and 1 escape during a nuclear emergency.

Kill your 2 targets? Disclaimer, I have no idea if that actually happened, but that shouldn't be the important part.

Nuclear Operatives obtain Syndicate Major Victory

For exact status, I was in a disposals can on the station, but according to Discord, it should have happened anyway.

Objective #3: Escape on the shuttle or an escape pod alive and without being in custody. Success!

**Comment by RandomGamer123** [comment]
If the nuke goes off I believe it automatically gives you the "escape" part

**Comment by Pandarsenic** [comment]
It seems so - got it again as a ling in 162679

**Comment by Mooshimi** [comment]
Yes, this is so solo antag don't get messed over by midround/group antags. You can close this issue.
