### ISSUE TITLE
Members of the Cult of the Rat God cannot tend wounds

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#59236]
Reporting client version: 514.1552

## Round ID:
- 162665

## Testmerges:
- [[The reconnect bug is fixed] Queue stat panel commands, ideally fixing another source of the reconnect bug](https://www.github.com/tgstation/tgstation/pull/59228)

## Reproduction:
1. Be converted to the cult of the Rat God by the chaplain.
2. Attempt to tend someone's wounds.
3. Fail at the first surgical step because the you can't attack the innocent in a righteous crusade against evil.

**Comment by RandomGamer123** [comment]
Same issue as #58371 probably

**Comment by TemporalOroboros** [comment]
Yeah. Looks like this is a dupe.
