### ISSUE TITLE
Grey Jumpsuit looked like a prisoner's jumpsuit.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#59235]
## Round ID:
- 162662

## Testmerges:
- #59228 

## Reproduction:
1. Latejoin as an assistant
2. Spawn with a grey jumpsuit
3. Notice that it looks orange on the mob sprite
4. Get arrested because sec thinks you're an escapee.

**Comment by Pandarsenic** [comment]
I've gotten this as a roundstart assistant twice, most recently in Round 162672 where it appeared as a white jumpsuit.
