### ISSUE TITLE
Monkies can steal your shit through d-glass walls.

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#59244]
![image](https://user-images.githubusercontent.com/14065903/119209494-e96adf00-ba74-11eb-85ce-d6bc544f6358.png)

In the picture above, the monkeys in the chamber can steal your in-hand item if you come within a block of the glass.  I know they were buffed not so long ago but this is ridiculous.

**Comment by Mothblocks** [comment]
border objects moment @ninjanomnom

**Comment by InsaneRed** [comment]
feature

**Comment by maxymax13** [comment]
theyre psychically fighting against your torture

**Comment by interestingusernam3** [comment]
Some old testing on what seems to be the same bug in comments here: https://github.com/tgstation/tgstation/issues/55776.
