### ISSUE TITLE
Mutation sometimes won't unlock even when complete

### ISSUE THREAD

**Issue by Djvarik** [tgstation/tgstation#59254]
Reporting client version: 514.1554

## Round ID:
[162693](https://scrubby.melonmesa.com/round/162693)

## Testmerges:
- [Lowers the cold temperature activation threshold for fire alarms/firelocks](https://www.github.com/tgstation/tgstation/pull/59205)
- [[The reconnect bug is maybe fixed] Queue stat panel commands, ideally fixing another source of the reconnect bug](https://www.github.com/tgstation/tgstation/pull/59228)

## Reproduction:
No idea how this mutation differed from the others but when I completed it the gold boxes around the originally unsolved DNA bases like the mutation usually does when unlocking. The mutation however did not unlock and stayed as mutation #, and when I scanned myself with the genetic analyzer it also showed up as mutation #. I am also 100% sure the DNA strand was completely correct. I tried another mutation after scrambling and it unlocked fine.
I came upon the same mutation later in the round and it unlocked just fine.
![clip](https://user-images.githubusercontent.com/25336158/119217090-6dd15800-ba9d-11eb-8720-a4fd8e0e978c.png)

**Comment by Fikou** [comment]
are you sure it was completely correct

**Comment by Time-Green** [comment]
Did the subject have any other mutations? There’s a few mutations, like dwarfism and gigantism, that block each other from activating

**Comment by Djvarik** [comment]
@Fikou 

Completely, I used the genetic analyzer which gave me all of the missing DNA bases in the strain.

@Time-Green 
That might have been the problem, I don't completely remember but I think mutation 10 ended up being dwarfism and the subject might have had gigantism at the time. Thinking on it, that was probably the problem, so I'll close the issue.

**Comment by Time-Green** [comment]
Thank you for your report anyway, because there’s obviously a lack of feedback on that
