### ISSUE TITLE
Explosions that occur due to chemicals reacting in the stomach rather than the bloostream happen in a nonexistant location

### ISSUE THREAD

**Issue by FernandoJ8** [tgstation/tgstation#59257]
## Round ID:

N/A, done on a private server

## Reproduction:

How to create explosions in the void in 3 easy steps:
- Make a 50u water pill
- Make a 50u potassium pill
- Take both in quick succession

Congratulations, the contents of your stomach have now reacted to form an explosion at a nonexistent location. Have fun as the admins scratch their head wondering what the fuck just happened, knowing only that it was you who did it.
![Screenshot 2021-05-22 114602](https://user-images.githubusercontent.com/80640114/119222266-b9aeec00-baf3-11eb-80a2-baa49d6fe0fd.png)

**Comment by FernandoJ8** [comment]
stupid formatting grumble grumble grumble

**Comment by vincentiusvin** [comment]
#53931

**Comment by FernandoJ8** [comment]
_oh_
