### ISSUE TITLE
Bio-Bag monkey cubes can't be used on Reproductive Extracts please, please fix

### ISSUE THREAD

**Issue by Comxy** [tgstation/tgstation#59265]
## Round ID: 
[162734](https://scrubby.melonmesa.com/round/162734)

## Reproduction: 
You grab a bio bag from xeno biology, then put monkey cubes in the bio bag. Then you try to feed a reproductive slime extract, doesn't matter which type. Then you won't be able to feed the reproductive slime extract when you normally could.

I think this is a bug but if it for some reason isn't let me explain why this is a problem. When doing xeno, a relatively late game job, I would like for my hands to stay healthy. When I use the bio bag my mouse doesn't leave its position. Whenever I need to feed the reproductive slime extracts monkey cubes now I need to keep changing positions with my mouse for every monkey cube two times, once to grab and the other to put it in the extract. Now imagine having 50 cubes. One you would waste time on something which is not only not fun to do, but something that also destroys your hand.

Someone told me that this might be re-balancing on the coders part. But how is this re-balancing when it just prevents you from doing xeno-biology from how it was intended to be in the first place. If you want to balance xeno-biology you would have to review individual parts. Starting to destroy mechanics in a job doesn't solve anything, it just puts people off from doing xeno-biology. What people might think as broken will also not disappear since xeno-biology being playable and xeno-biology being broken are two different things.

**Comment by JustANormalHooman** [comment]
I do think this is a bug. I tested it on a private server and couldn't get it to work either. I also searched all pull requests and couldn't find any mention of reproductive slime extracts being nerfed in this specific way.

**Comment by Sealed101** [comment]
fixed by #60345

**Comment by AlinaStarkova** [comment]
this was fixed, @timothymtorres  you can close this issue
