### ISSUE TITLE
Jumpskirts in-hand makes you into an e.

### ISSUE THREAD

**Issue by BebeYoshi** [tgstation/tgstation#59268]
## Reproduction: 
1. Hold a greyjumpskirt or any variation in hand.

2. Enjoy being an e.

**Comment by ATH1909** [comment]
e

**Comment by SuperNovaa41** [comment]
Related to https://github.com/tgstation/tgstation/issues/59211

**Comment by dragomagol** [comment]
Appears to have been fixed
