### ISSUE TITLE
Being contracted deletes your storage implant if you have one, and drops its contents on the ground.

### ISSUE THREAD

**Issue by Valorium-RB** [tgstation/tgstation#59272]
## Round ID:
[162749](https://scrubby.melonmesa.com/round/162749)
## Reproduction:
As a traitor, bought a storage implant, placed two items inside it. Was contracted, upon being placed in a pod and sent off, storage implant was deleted, stored items were dropped on the ground. Ahelped about the issue, was told it was definitely not an intended function.

**Comment by Mooshimi** [comment]
#52853 seems related

**Comment by timothymtorres** [comment]
Contractors were removed so I'm closing this.

**Comment by Mooshimi** [comment]
> Contractors were removed so I'm closing this.

Did they have a snowflake transport or will the same problem pop up with the ninja kidnap
