### ISSUE TITLE
Game thinks the chapel is somehow space

### ISSUE THREAD

**Issue by Imaginos16** [tgstation/tgstation#59289]
## Testmerges:
#59205 
#59232 

## Reproduction: 
Use funny Crab-17 Phone, have the thing drop on the chapel, get this message (Tram Station)
![image](https://user-images.githubusercontent.com/77556824/119280781-38e21400-bc09-11eb-9db0-70e6de0ff7ee.png)
?????????????????????????

**Comment by dragomagol** [comment]
Which station was this?

**Comment by Imaginos16** [comment]
> Which station was this?

This was Tram Station, thought I specified it, whoops.

**Comment by Mothblocks** [comment]
I *think* it's related to the fucked circuits room on Tram, that put an APC in space by mistake.

**Comment by Maurukas** [comment]
I'll try to look at this today and see what happened. I had at least one map merge moment over the weekend.

**Comment by Mothblocks** [comment]
Can you double check that this is still a thing?

**Comment by Maurukas** [comment]
I added commits to the circuit PR which fix the area on the circuit lab. Still not 100% sure this is related.

**Comment by Mothblocks** [comment]
I might have been thinking of Kilo.

**Comment by dragomagol** [comment]
Appears to have been fixed

**Comment by dragomagol** [comment]
![image](https://user-images.githubusercontent.com/66640614/128217959-37e4f7fd-ad61-426e-ab56-702b5692e84c.png)
