### ISSUE TITLE
Greyscale (I think) and rainbow crayon turns you into an e that changes back and forth

### ISSUE THREAD

**Issue by ShibaInuLord** [tgstation/tgstation#59282]
## Round ID:
[162743](https://scrubby.melonmesa.com/round/162743)

## Testmerges:
N/A

## Reproduction:
Spawn in as clown, get the green sombrero and poncho from the vendor, eat your rainbow crayon for rainbow clothing, turn into an e every like half a second, turn back, and then back again

**Comment by SuperNovaa41** [comment]
Related to https://github.com/tgstation/tgstation/issues/59268

**Comment by SuperNovaa41** [comment]
also related to https://github.com/tgstation/tgstation/issues/59211

**Comment by ninjanomnom** [comment]
The E error isnt even a thing anymore and the regular error sprite is used instead. This was likely fixed along with the others but should be reported again if not.
