### ISSUE TITLE
Chaplain Maintenance Sect "Adapted Eyes" from Rites are too vulnerable and inconsistent.

### ISSUE THREAD

**Issue by Learner10** [tgstation/tgstation#59285]
## Round ID: 
[162799](https://scrubby.melonmesa.com/round/162799)

## Testmerges:
#59205: 'Lowers the cold temperature activation threshold for fire alarms/firelocks' by Yenwodyah at commit dac69ce8e9
#59232: 'Integrated Circuits (Wiremod)' by Watermelon914 at commit 7cfa773c2c

## Reproduction:
Pick and choose Maintenance Sect as the Chaplain, build favor until you can achieve Adapted Eyes, then become blind from standing close to an APC.

The Adapted Eyes have an issue where having blindness caused by worn objects provide no protection from anything remotely lit. Even wearing a blindfold will cause your eyes to burn simply for standing next to a monitor, let alone being in a closet surrounded by walls. If light shines on the closet, your eyes burn.
On top of that, the eyes make no difference between a lighter, and a floodlight. If it's light, you go blind, regardless if you can even see it. This all adds to to a very punishing experience at the end of the day.

**Comment by ATH1909** [comment]
do your eyes still not unblind you properly once you get back to darkness for a while?

**Comment by Mooshimi** [comment]
> do your eyes still not unblind you properly once you get back into darkness for a while?

I saw a chaplain around and they had to go onto the ice wastes to regain sight, breaking the lights on station wasn't enough of a full darkness for them to heal.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/e59e14a739ba244fc9140d5c86a20c231d514075/code/modules/surgery/organs/eyes.dm#L490-L499

To fix this we need to do the following:

```dm
// isturf is used to check if we are in a locker or container
if(!HAS_TRAIT(owner, TRAIT_BLIND) && isturf(owner.loc) && owner.has_light_nearby(light_amount=0.5))
  //do damage calculations
```
