### ISSUE TITLE
GAGS custom sombrero flashing and error symbol

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#59298]
Reporting client version: 514.1554

## Round ID:
[162861](https://scrubby.melonmesa.com/round/162861)

## Testmerges:
- [Integrated Circuits (Wiremod)](https://www.github.com/tgstation/tgstation/pull/59232)
- [Lowers the cold temperature activation threshold for fire alarms/firelocks](https://www.github.com/tgstation/tgstation/pull/59205)

## Reproduction:

Made a custom cargo sombrero but the effect was kind of ruined.

![](https://i.imgur.com/5Davyjl.gif)

**Comment by MrMelbert** [comment]
All the GAGS stuff is flashing error signs now

**Comment by maxymax13** [comment]
can confirm happens for screwdrivers i hit myself while building thindows :(

**Comment by Serxule** [comment]
yeah a shit ton of stuff is either just a solid error or flashing error, le epic coders breaking the same

**Comment by cacogen** [comment]
it's not fixed
