### ISSUE TITLE
Camera Eyes fall through open space

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#59319]
## Reproduction:
use xenobiology console on tramstation or icebox
move camera over open space
camera will fall in
attempting to move up floors will instantly cause it to fall down again

this issue also applies for abductor consoles, though i'm unsure if it applies to AI as well.

**Comment by maxymax13** [comment]
i told you bro, i WARNED the camera system about stairs

**Comment by Gboster-0** [comment]
the cameras are officially counted as disabled machines.
