### ISSUE TITLE
Wiremod: And Gates on the integrated circuits doesn't behave as intended

### ISSUE THREAD

**Issue by Lauwma** [tgstation/tgstation#59336]
## Reproduction:

And Gates with two inputs will always return true. I have a quick setup if you wanna see it by yourself it needs a compact remote to work but you can use a radio signal too.

![image](https://user-images.githubusercontent.com/32490372/119737348-6e903280-be7f-11eb-8284-73ae4e24c366.png)

(This setup will return True while it should be false.)

**Comment by Mothblocks** [comment]
CC @Watermelon914

**Comment by Qustinnus** [comment]
this happens because

**Comment by Qustinnus** [comment]
also OP's example is weird, the signal shouldn't be going into the AND gate anyways. the result should.

**Comment by Mothblocks** [comment]
Actually, this doesn't make sense to me.

True/False are signals. What happens if you just pipe result in?

Also, it could be that the signal is firing everything at the same time, but components have a small delay--it's a race condition. Move the signal on compact remote -> compare somewhere else. Maybe we could have a component that waits until all signals passed to it are fired before firing itself? Or we should implement that overheating thing ninja said so we can have all circuits run right away without delays...

**Comment by Mothblocks** [comment]
It would probably make sense to block signals from "any", since I feel this could be a common trap.

**Comment by Lauwma** [comment]
I think the input is any because string = 1 any number > 0 = 1 ect...
I don't see why my example doesn't work if we make a traduction from UML to any text language it would be
if 1 == 1 and 0 == 1:
   return(True)
else:
   return(False
   
I can come up with a lot of examples where AND gates behaved like that, it's just the smallest setup I could make since we don't have variable components. 

For example I tried the same setup with ram components. I verified the ram correctly saved the correct input (1,NULL) and ran two rams in an AND gate. I had slightly different result. Instead of being always true the gates behaved like an OR gate and returned True if they had at least one of their input on True

**Comment by Mothblocks** [comment]
The input being any is sane, but I don't see any reason why a signal should be able to fit into any, since it just seems confusing.

**Comment by Lauwma** [comment]
There's situations where I want a signal to fit in any, for example I wanted to make a rock paper scissor game with two remotes and you need to use a radio to send the informations to the central hub, the only informations you can carry are signals. Most of the inputs are signals.
I believe signals are 1 when triggered then quickly returns to 0, that's why I store them into ram to have a constant 1

**Comment by Qustinnus** [comment]
that should not be how problems like that are tackled and assuming that's the only way to do that (Which I doubt) then we should have another way of doing it.

**Comment by Lauwma** [comment]
First thing first, are we agreeing on the fact that end gates don't behave like they are intended to ?

**Comment by Qustinnus** [comment]
I can't say if its the case unless I see a reproduction of the bug that isn't using signals like this. Use literal values and try again and see if it actually happens.

**Comment by Qustinnus** [comment]
I can't say if its the case unless I see a reproduction of the bug that isn't using signals like this. Use literal values and try again and see if it actually happens.

**Comment by Lauwma** [comment]
This setup indeed works correctly and proves that results in AND gates works well
![image](https://user-images.githubusercontent.com/32490372/119834957-b1461f00-bf00-11eb-96a4-83af6cb91c54.png)

Though, signals still don't work properly in AND gates, even with RAM giving a constant output. (This setup acts as an OR gate, when on of the input are true, the controller states True, when both are True, the controller states True, when none are True, the controller states false.)
![image](https://user-images.githubusercontent.com/32490372/119836301-ebfc8700-bf01-11eb-97dc-99137938c326.png)

One solution would be to bypass this issue and somehow convert signals into results in game, but I think it would be very cool if you didn't have to do such thing.
In my opinion the AND gates don't work as intended

**Comment by Watermelon914** [comment]
Signals will always return 1 my dude.

**Comment by Watermelon914** [comment]
And you're hitting a race condition. It is comparing before the values get there because of how you've laid your triggers out, it doesn't wait for the comparisons to finish first.

**Comment by Watermelon914** [comment]
Result is also actually updated independently of the Compare signal. Compare is only for triggering the true/false signals.

**Comment by Lauwma** [comment]
But when there's no signals the signals should be NULL, no ?

**Comment by Watermelon914** [comment]
No. they're always set to 1 because they're a trigger. Outputs retain their values and update the connected inputs whenever their values update. There's no reason for them to go back to 0.

**Comment by Lauwma** [comment]
How are we supposed to compare inputs then if we cannot use signals in AND gates ? 
For the example of the Rock Paper Scissor, if all your inputs are signals, how are you comparing which scenario it is ? (rock vs rock, rock vs paper, ect...)

**Comment by Watermelon914** [comment]
why would you compare inputs, they're a trigger, you don't need to compare anything.

**Comment by Lauwma** [comment]
So I tried, as you said, to not input signals, the AND gate still acts like an OR gate for me.
![image](https://user-images.githubusercontent.com/32490372/119839836-c0c76700-bf04-11eb-998c-2b33dde159bf.png)

**Comment by Watermelon914** [comment]
they're both set to one??

**Comment by Lauwma** [comment]
Only signal has been pressed and it returns True but it started as false before I pressed anything. When I pressed extra signal it was still True. Once I pressed alternate it returned to false

**Comment by Watermelon914** [comment]
I'll file a quick PR to fix the fringe cases where you might have a null, connected port and it being disregarded

**Comment by Watermelon914** [comment]
It's intentional for it to be ignored if the input is null, but not if it is connected to a port.

**Comment by Lauwma** [comment]
Sorry for my misunderstanding of what signals really where but at least we figured out another issue anyway. Thank you for your help y'all, much appreciated.

**Comment by Watermelon914** [comment]
Also by the way, RAM components probably won't be needed for what you're trying to make because the outputs don't get removed unless a new input is received that may require the output to be changed.

**Comment by Lauwma** [comment]
Oh uh I use ram components because I want the controllers to be able to choose only one imput. What I do is clearing all the ram of the controller then storing the one input the user choosed last. It worked well for the rock paper scissor game I tried to make. My only issue were thoses AND gates
