### ISSUE TITLE
Cigarette Knockoff

### ISSUE THREAD

**Issue by jwc1015** [tgstation/tgstation#59342]
Reporting client version: 513.1542

## Round ID:
[162989](https://scrubby.melonmesa.com/round/162989)

## Testmerges:
- [Lowers the cold temperature activation threshold for fire alarms/firelocks](https://www.github.com/tgstation/tgstation/pull/59205)

## Reproduction:
I put a cigarette in my mouth (bartender with smoker trait), and then it got knocked out of my mouth. (nobody was nearby, standing completely still) This happened _constantly._

**Comment by maxymax13** [comment]
game is telling u smoking is bad

**Comment by Mothblocks** [comment]
CC @Mickyan

**Comment by Mickyan** [comment]
This appears to only be happening to lit cigarettes, specifically shortly after they process reagents into the mob

Considering the component is just listening for the knockdown signal I have absolutely no clue what could possibly be causing this. 
As much as I feel responsible to fix my own messes this is a rabbit hole I don't have time to delve into at the moment so feel free to revert this if nobody else can be bothered to fix it

But if you do figure it out might as well fix the grammar on the visible messages also, I missed that one
![Screenshot_1](https://user-images.githubusercontent.com/38563876/119819179-615f5c00-bef0-11eb-9b84-22f950f5db44.png)

**Comment by Pugie** [comment]
Did you have head?

**Comment by Mickyan** [comment]
Just so I have proof that this isn't my own personal fuck up: smoking makes spaghetti spill out of your pockets

![Screenshot_2](https://user-images.githubusercontent.com/38563876/119868154-fd07c100-bf1e-11eb-9387-6a17e7744612.png)

**Comment by maxymax13** [comment]
> 
> 
> This appears to only be happening to lit cigarettes, specifically shortly after they process reagents into the mob
> 
> Considering the component is just listening for the knockdown signal I have absolutely no clue what could possibly be causing this.
> As much as I feel responsible to fix my own messes this is a rabbit hole I don't have time to delve into at the moment so feel free to revert this if nobody else can be bothered to figure out what the hell is going on
> 
> But if you do figure it out might as well fix the grammar on the visible messages also, I missed that one
> ![Screenshot_1](https://user-images.githubusercontent.com/38563876/119819179-615f5c00-bef0-11eb-9b84-22f950f5db44.png)

your the
