### ISSUE TITLE
Wizard mindswap and circuits wierdness

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#59340]
## Reproduction: Wizard mindswapped into a circuits drone that can move. Wizard was a monkey at the time and the circuit drone thing already was possessed via admemery. When wizard mindswapped into the circuit device named vibebot it caused it to fall into a sleep condition that the swap thing does except it didn't end. We managed to wake up the wizard but it couldn't cast magic and was still blind. I believe what happened is similar in what happened in this bug report relating to nanites. https://github.com/tgstation/tgstation/issues/42681 
Pretty much I think the bug is that the mindswap added a few values that it doesn't cancel due to the circuit mob. The way we woke it most likely didn't remove the fact that the game thought he was still asleep and thus can still move but not able to cast magic or see.

**Comment by TheBonded** [comment]
Same thing happens if you mindswap into a pAI holochassis

**Comment by Watermelon914** [comment]
this issue is related to admin shenanigans, not really a bug.

**Comment by TheBonded** [comment]
> this issue is related to admin shenanigans, not really a bug since no one should be able to be these circuit drones yet.

still applies to pAI holochassis

**Comment by timothymtorres** [comment]
I'm linking the pAI mindswap issue here - #56861

**Comment by Mooshimi** [comment]
> this issue is related to admin shenanigans, not really a bug since no one should be able to be these circuit drones yet.

ok its the cleanup for me then
