### ISSUE TITLE
Thermomachines are borked

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#59353]
## Reproduction:
* Turn on roundstart thermomachine
* 
![image](https://user-images.githubusercontent.com/3204033/119899336-9b3c5c80-bf08-11eb-9dd4-a0d52d1d2e08.png)
* Rebuild thermomachine
* It keeps happening

**Comment by InsaneRed** [comment]
i think this is a problem of them not actually working untill both inputs have gas

**Comment by RaveRadbury** [comment]
> i think this is a problem of them not actually working untill both inputs have gas

So has it always been this way and we're just now seeing it with the new UI?

**Comment by InsaneRed** [comment]
> > i think this is a problem of them not actually working untill both inputs have gas
> 
> So has it always been this way and we're just now seeing it with the new UI?

no clue however i know since the new ui they havent been working or showing that error untill both inputs have gas

**Comment by RaveRadbury** [comment]
I just need my freezer to have some sort of gas in it roundstart 😭

**Comment by SuperNovaa41** [comment]
Doubt it
