### ISSUE TITLE
funny double bar stool in delta

### ISSUE THREAD

**Issue by maxymax13** [tgstation/tgstation#59357]
## Round ID:
[163048](https://scrubby.melonmesa.com/round/163048)

## Testmerges:
#58991

## Reproduction:
hey this stool looks kinda sus
![dreamseeker_LN32xa6HLZ](https://user-images.githubusercontent.com/38844529/119922245-6dbdd600-bf3d-11eb-8b05-701513f543b5.png)
imposter found
![dreamseeker_GKTdt0SwpI](https://user-images.githubusercontent.com/38844529/119922262-76aea780-bf3d-11eb-8564-063caf4c149c.png)

**Comment by notfrying1pans** [comment]
![image](https://user-images.githubusercontent.com/49667761/120072743-524ceb00-c063-11eb-8801-7a3a19d264b7.png)
