### ISSUE TITLE
Players become DNR / Unable to reenter body for no reason

### ISSUE THREAD

**Issue by GoblinBackwards** [tgstation/tgstation#59364]
## Round ID:
[163075](https://scrubby.melonmesa.com/round/163075) , 163078

## Testmerges:
#59118 #59002 

## Reproduction:
Be dead. You will we be unable to reenter you body without anything happening to actually make you unrevivable. Your body only sometimes shows up as unrevivable on medhuds, and will sometimes stay revivable . However, it is impossible to reenter your body atall, and when you are revived the body will be catatonic with no way for you to reenter that body outside of admin intervention.

**Comment by InsaneRed** [comment]
can confirm this hpapend to me on terry

**Comment by InsaneRed** [comment]
twice

**Comment by GoblinBackwards** [comment]
This also happens to borgs

**Comment by LemonInTheDark** [comment]
Do you get any feedback? Something like "You have no body"?

**Comment by GoblinBackwards** [comment]
> Do you get any feedback? Something like "You have no body"?

Yeah, you get the message saying you have no body

**Comment by LemonInTheDark** [comment]
Aight, should be fixed post this commit https://github.com/tgstation/tgstation/pull/59118/commits/9f9e520d2f826be94f1c8ddf53a605e2037ee977

Lemme know if this kind of thing crops up again, I am touching a pretty base part of the game, and it's not very good
