### ISSUE TITLE
Plastic knives count as full on knives for heretic sickle creation

### ISSUE THREAD

**Issue by aztectornado** [tgstation/tgstation#59369]
## Reproduction:

Unsure if this is a bug or intended feature on TG's end, but I just had a game on a high RP downstream (Skyrat, specifically) where a permanently imprisoned heretic was able to produce their sickle from one of the prison's plastic knives. Considering that heretics use transmutation circles, the law of equivalent exchange should logically apply here, and soft plastic cutlery should probably not produce an iron blade capable of dismembering armed guards, regardless of the magic pumped into it.

**Comment by maxymax13** [comment]
feature

**Comment by rdragan** [comment]
This is intended behaviour.
