### ISSUE TITLE
Tram teleports ghots that orbit the tram back to the original orbiting position

### ISSUE THREAD

**Issue by Jamarkus127** [tgstation/tgstation#59376]
Reporting client version: 514.1554

## Round ID:
[163111](https://scrubby.melonmesa.com/round/163111)

## Testmerges:
- [Lowers the cold temperature activation threshold for fire alarms/firelocks](https://www.github.com/tgstation/tgstation/pull/59205)
- [Fixes cigarettes making you so lame that they spill the spaghetti from your pockets (and also keep falling off)](https://www.github.com/tgstation/tgstation/pull/59352)

## Reproduction:

If you orbit the tram or anyone or thing on the tram at the time, when the tram begins to move you are teleported to the last position you were orbiting on the tram. The fix is easy, just orbit something off of the tram, but can be annoying orbiting someone on the tram at that moment.

Basic steps: 
1. orbit stationary/moving tram
2. wait for someone to use the tram
3. be unable to move away from the tram until the tram stops
4.  as long as you dont orbit anything else, you will be teleported to the original orbit position every time the tram is moved.

**Comment by TheBonded** [comment]
feature, the tram requires an audience for it's sacrifices
