### ISSUE TITLE
Bag of Holding interferes with Reality Phase teleport

### ISSUE THREAD

**Issue by thespitfire24** [tgstation/tgstation#59394]
## Testmerges:
#59205: 'Lowers the cold temperature activation threshold for fire alarms/firelocks' by Yenwodyah at commit dac69ce8e9
#59374: 'Wrapping Paper GAGS' by RaveRadbury at commit 8b1662f1fe

## Reproduction:
1. Get a bag of holding.
2. Use the reality phase teleport spell.
3. Get your teleport interfered with; try to teleport into the armory and end up in space!

**Comment by RaveRadbury** [comment]
Isn't this expected behavior? BoH is meant to interfere with all TP attempts due to bluespace interference

**Comment by MrMelbert** [comment]
> 
> 
> Isn't this expected behavior? BoH is meant to interfere with all TP attempts due to bluespace interference

BoH only interferes with `TELEPORT_CHANNEL_BLUESPACE` methods of teleportation, such as the hand teleporter. It's not supposed to interfere with other methods like `TELEPORT_CHANNEL_MAGIC`, but void phase appears to use the default teleport channel (which is bluespace) even though it's not bluespace related.
