### ISSUE TITLE
Starlight Condensation Threshold Bonuses Not Applying

### ISSUE THREAD

**Issue by peetrj** [tgstation/tgstation#59395]
Reporting client version: 514.1554

## Round ID:
[163196](https://scrubby.melonmesa.com/round/163196)

## Testmerges:
- [[READY] Lighting list cleanup.](https://www.github.com/tgstation/tgstation/pull/59002)
- [Toggles harddel searching for use on live [DNM]](https://www.github.com/tgstation/tgstation/pull/59118)

## Reproduction:
Create an advanced virus with starlight condensation with transmission 6 and stage speed 6 so that the conditions for starlight condensation are met. From my understanding the transmission being 6 should "remove the penalty from being near space" (pulled from the wiki https://tgstation13.org/wiki/Infections#Symptoms_Table), so if you don't have say a space "tile" on screen you would still get healed. From my experience in this round that doesn't happen, I also include stage speed as that also didn't seem to have any affect when near space but I can't 100% confirm this, the implication being that neither threshold is working.

**Comment by RandomGamer123** [comment]
Well as the person who coded the starlight condensation fixes, starlight condensation still only works if you have a space tile near you (defined as within 2 tiles, and some finnicky stuff for z-levels) to begin with. Transmission 6 should "remove the penalty from *only* being near space". Without transmission 6, there are different healing rates if you are in space versus if you are near space.

**Comment by dragomagol** [comment]
Sounds like this is a case of the wiki being out of date.
