### ISSUE TITLE
The Iron Grip Bug. ( H.A.U.L Gauntlets)

### ISSUE THREAD

**Issue by legoscape** [tgstation/tgstation#59396]
ROUND ID 163201
![image](https://user-images.githubusercontent.com/16533746/120115732-12653100-c153-11eb-8a8c-e30f08b79141.png)

Replication. Get some H.A.U.L Gauntlets and drag a closed crate
During the drag take off the Gauntlets.
Boom. The crate is stuck shut. Even when you stop pulling it.

**Comment by TheBonded** [comment]
does grabbing the crate with haul gauntlets fix this, or does the crate become broken forever?

**Comment by legoscape** [comment]
If you re-grab the crate with the haul gauntlets it does fix the crate. But I'm not sure if it's specific to the user or the gloves fixing the crate. 

I've yet to test this with two people with haul gauntlets.

**Comment by ATH1909** [comment]
can you pop open the crate using eigenstasium?
