### ISSUE TITLE
Phantom banana peels can trancend space and time.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#59410]
Reporting client version: 514.1552

## Round ID:
[163233](https://scrubby.melonmesa.com/round/163233)

## Testmerges:
- [Turns lighting objects into a datum, makes all lighting be performed with an underlay. big maptick fix very good!](https://www.github.com/tgstation/tgstation/pull/58991)
- [Lowers the cold temperature activation threshold for fire alarms/firelocks](https://www.github.com/tgstation/tgstation/pull/59205)

## Reproduction:
1. Accumulate a large number of banana peels in a public walkway (such as the departures hallway).
2. Use a broom to sweep the banana peels out of the way.
3. Stand up.
4. Walk over an empty turf.
5. Get slipped by a banana peel from the past and (presumably) presently disposals.
6. Walk over a banana peel that was swept.
7. Somehow don't get slipped.

**Comment by interestingusernam3** [comment]
Crossed moment.
