### ISSUE TITLE
Shuttle was bought after shuttle call, resulting in two shuttles, the second crushing those on the first, the first leaving but not the second

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#59429]
Reporting client version: 514.1555

## Round ID:
[163276](https://scrubby.melonmesa.com/round/163276)

## Testmerges:
- [Lowers the cold temperature activation threshold for fire alarms/firelocks](https://www.github.com/tgstation/tgstation/pull/59205)
- [Lizard Food: a Taste of the Homeworld](https://www.github.com/tgstation/tgstation/pull/59412)

## Reproduction:
![](https://i.imgur.com/op6l9NT.png)
![](https://i.imgur.com/IKI7F5H.png)
![](https://i.imgur.com/7pnGr2y.png)
![](https://i.imgur.com/dqTSDTJ.png)
![](https://i.imgur.com/YFEOqR3.png)
![](https://i.imgur.com/xgNgSH9.png)
![](https://i.imgur.com/8Zcy8jq.png)
![](https://i.imgur.com/oKLqenB.png)
![](https://i.imgur.com/rywZtra.png)
![](https://i.imgur.com/lvnMCaS.png)
![](https://i.imgur.com/avKD9hn.png)

**Comment by Serxule** [comment]
this has happened before believe it or not, i don't think they ever figured out why or bothered to fix it, obviously

**Comment by msgerbs** [comment]
Related to #54316 and #32419. Something must have changed though because last time I looked at the escape shuttle code there was a check to stop you buying a shuttle after one was called.
