### ISSUE TITLE
many bad del runtimes related to monkey species

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#59428]
## Round ID:
[163276](https://scrubby.melonmesa.com/round/163276)

## Testmerges:
- [Lowers the cold temperature activation threshold for fire alarms/firelocks](https://www.github.com/tgstation/tgstation/pull/59205)
- [Lizard Food: a Taste of the Homeworld](https://www.github.com/tgstation/tgstation/pull/59412)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/120263971-66ab0680-c262-11eb-9f07-bf8b6e8d8b9c.png)

 ```
[2021-06-01 03:08:02.927] runtime error: bad del
 - proc name: qdel (/proc/qdel)
 -   source file: garbage.dm,282
 -   usr: Unknown (/mob/living/carbon/human/species/monkey)
 -   src: null
 -   usr.loc: the floor (151,113,2) (/turf/open/floor/iron)
 -   call stack:
 - qdel(null, 0)
 - Unknown (/mob/living/carbon/human/species/monkey): Destroy(0)
 - Unknown (/mob/living/carbon/human/species/monkey): Destroy(0)
 - Unknown (/mob/living/carbon/human/species/monkey): Destroy(0)
 - Unknown (/mob/living/carbon/human/species/monkey): Destroy(0)
 - Unknown (/mob/living/carbon/human/species/monkey): Destroy(0)
 - Unknown (/mob/living/carbon/human/species/monkey): Destroy(0)
 - Unknown (/mob/living/carbon/human/species/monkey): Destroy(0)
 - qdel(Unknown (/mob/living/carbon/human/species/monkey), 0)
 - Atoms (/datum/controller/subsystem/atoms): InitAtom(Unknown (/mob/living/carbon/human/species/monkey), 0, /list (/list))
 - ...
 ```

**Comment by LemonInTheDark** [comment]
![image](https://user-images.githubusercontent.com/58055496/120422435-16dd4580-c31d-11eb-8adf-9e180b9ef002.png)
This is another bad one from the same round

**Comment by JohnFulpWillard** [comment]
is this still an issue? If not, maybe https://github.com/tgstation/tgstation/pull/62121 could be related to it being fixed.

**Comment by MrMelbert** [comment]
Not seen this
