### ISSUE TITLE
Grills don't always make "real" food

### ISSUE THREAD

**Issue by Meatstuff882** [tgstation/tgstation#59423]
Reporting client version: 513.1542

## Testmerges:
- [Lowers the cold temperature activation threshold for fire alarms/firelocks](https://www.github.com/tgstation/tgstation/pull/59205)

## Reproduction:
Occasionally, the grills will start producing inedible food. Using it on yourself simply results in your character hitting themselves with it. I have not been able to reproduce this bug, but I have seen it across multiple rounds. it seems to happen after a certain amount of time has elapsed in a round however.

**Comment by SmArtKar** [comment]
Are you sure that their combat mode is off? Because it looks like they just forgot to turn it off before eating

**Comment by TheBonded** [comment]
I have seen this as well, with combat mode on or off you cannot eat the food.

**Comment by Yawet330** [comment]
This involves the food itself having 0 reagents upon creation IIRC, resulting in the Edible component going "Fuck this", and deleting itself from the entity.

**Comment by timothymtorres** [comment]
> This involves the food itself having 0 reagents upon creation IIRC, resulting in the Edible component going "Fuck this", and deleting itself from the entity.

Should probably spawn it as a burned mess then

**Comment by timothymtorres** [comment]
Duplicate of #55375
