### ISSUE TITLE
MMIs can move mechs after they eject themselves

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#59449]
## Reproduction:
1. Be MMI
2. Be put in mech
3. Eject
4. Move around, the mech will still move around and push people. You can't however, use your equipment.

**Comment by ATH1909** [comment]
What happens if the MMI is then put in a cyborg or an AI?

**Comment by JohnFulpWillard** [comment]
I can't reproduce this, is it still a problem @Mothblocks?

**Comment by Mothblocks** [comment]
No idea let's just close it
