### ISSUE TITLE
Nar'sie and Nuke Ops End Screens not showing after win event

### ISSUE THREAD

**Issue by legoscape** [tgstation/tgstation#59440]
https://github.com/tgstation/tgstation/pull/52464

Previously fixed broken again some how...Dunno why. 
![image](https://user-images.githubusercontent.com/16533746/120404818-2f496200-c315-11eb-9ec3-4aa6af1a374e.png)
These are my options I'm running if that matters.

**Comment by SuperNovaa41** [comment]
Fairly certain this is a BYOND bug, not gonna label it just in case it's not.
