### ISSUE TITLE
Orbiting someone who crosses z-level will unorbit them and teleport you somewhere else

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#59473]
1. Orbit someone
2. Have that someone go off z-level
3. You will unorbit them, and teleport somewhere else. The place you teleport isn't consistent, When orbiting someone going through the CentCom transit ship (z-level 2), I unorbited and teleported to (247, 100, 6), despite not being anywhere near that when orbiting.

**Comment by Wayland-Smithy** [comment]
Caused by `/turf/open/space/transit/Entered()` being called for ghosts from orbiter component `forceMove()ing` them while shuttle code uses `abstract_move()` to send everything else to the transit z-level.
