### ISSUE TITLE
Error with chat and loading other html elements within game

### ISSUE THREAD

**Issue by AngeryFrog** [tgstation/tgstation#59476]
## Round ID:
Tested and found in multiple rounds 

## Reproduction:

Logging into any tg codebase server as of today (was not an issue last I played 01/06/2021) will cause fancy chat too fail too load and refuse too allow usage of chat, upon trying too reload fancy chat the error written is emitted
```
Error: Access is denied.

   at isStyleSheetLoaded (http://127.0.0.1:61020/tmp948/browseroutput.html:198:7)
   at node.onload (http://127.0.0.1:61020/tmp948/browseroutput.html:291:9)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
```

This error also comes up when loading guis for other objects

**Comment by redguy999** [comment]
Tgui is broken and can't be fixed since the solution to the problem opens a confirmation box that requires tgui to load.

**Comment by newfren** [comment]
important note this is immediately after a ddos attack that required mso to move manuel's port

**Comment by AngeryFrog** [comment]
Ah I will remeber that and check later too see if the issue persists

**Comment by AngeryFrog** [comment]
issue has resolved self, likely related too the ddos mentioned by newfren
