### ISSUE TITLE
Nyctophobias negative effects dont disapear

### ISSUE THREAD

**Issue by Edelor68** [tgstation/tgstation#59485]
## Reproduction:
Traits: Nyctophobia & Night Vision

Once you get slowed when entering a dark area the slow never disappears no matter the light level. It even carries over rounds so that you are slowed as soon as you arrive if it happened last round.

**Comment by Djvarik** [comment]
Nyctophobia just toggles your move intent so you end up walking instead of running. Have you tried toggling back to running or is it not letting you run again?

**Comment by Edelor68** [comment]
Alrighty, it looks like I'm just an idiot. It was, as you said, just the move intent toggled. Sorry about this!
