### ISSUE TITLE
Latices on multi-floor maps

### ISSUE THREAD

**Issue by Edelor68** [tgstation/tgstation#59484]
## Round ID:
Any

## Reproduction:
On maps where it is possible to view the z-level below you when there is no floor, it is impossible to place latices if the floor on the level below has something blocking it from view (wall, grill, etc.). It is also not possible to view objects via alt-clicking and get around the problem that way, as the menu just doesn't appear if you try.

**Comment by remove32** [comment]
I was able to replicate this easily on Ice Box in the botany area. It looks like it's connected with the bit of code that pulls objects up a level for visibility purposes. Left clicking in the open space should override but it isn't.

**Comment by remove32** [comment]
When clicking on a nutrimax from above like in this pic 
![image](https://user-images.githubusercontent.com/27014495/120880748-c589bc00-c591-11eb-9156-49e2c5fff5f6.png)
it seems that the code here ![image](https://user-images.githubusercontent.com/27014495/120880735-adb23800-c591-11eb-95c7-fbb6949846ed.png)
isn't getting everything it needs. `var/list/checking` is setup as though `ultimate_target` was more than one item. 
`CanReach` gets the `ultimate_target` param from here 
![image](https://user-images.githubusercontent.com/27014495/120881149-d5ef6600-c594-11eb-90ec-6f5fdcf33af9.png)
`src` in this case is the nutrimax vendor and `location` is the openspace turf above it.
