### ISSUE TITLE
Beepskies hardstun and it makes my blood boil

### ISSUE THREAD

**Issue by Sheits** [tgstation/tgstation#59498]
I really don't think there's much to explain, currently beepsky just immediately hardstuns you, which gives you absolutely no chance to counter. If it used the current baton system instead of the old, you could maybe throw an EMP or ion rifle it in the tiny window you get before the second stun. I'd code it myself but im fucking retarded l ol

**Comment by TheBonded** [comment]
Beepsky is just better, simple as that.

**Comment by SuperNovaa41** [comment]
I'm like 99% sure no ones going to let you change beepsky stuns

**Comment by Sheits** [comment]
masochists

**Comment by SuperNovaa41** [comment]
> masochists

Its oranges mainly

**Comment by Sheits** [comment]
well i mainly made this to stir up converstation, also coulda sworn this was a feature request

**Comment by RaveRadbury** [comment]
this is not the place for feature requests, please use https://tgstation13.org/phpBB/viewforum.php?f=5
