### ISSUE TITLE
The TEG circuitboard on the derelict is useless

### ISSUE THREAD

**Issue by WlarusFromDaSpace** [tgstation/tgstation#59502]
## Reproduction:
* Become a derelict drone
* Get the TEG circuitboard from the vault
* Build the TEG
* Notice that there are no circulators
* Build the Circuit imprinter
* Notice that you can't print circulator circuits
* Get annoyed

**Comment by WlarusFromDaSpace** [comment]
Sorry about the double issue, I accidentally posted it before it was ready and for some reason I couldn't edit it afterwards.

**Comment by RandomGamer123** [comment]
There is another way to get power on the derelict right?

**Comment by TheBonded** [comment]
> There is another way to get power on the derelict right?

solars.

**Comment by RandomGamer123** [comment]
like i guess derelict having a teg wont break anything although the teg is *supposed* to be removed by now so

**Comment by RandomGamer123** [comment]
or we could just give derelict a sm shard

**Comment by TheBonded** [comment]
Giving derelict an sm shard could work, but it would just make it a discount charliestation

**Comment by D4C-420** [comment]
> Giving derelict an sm shard could work, but it would just make it a discount charliestation

I think the closest thing to a TEG is a turbine so that could be done as a replace meant? 

> or we could just give derelict a sm shard

I think thats a bad idea as the derelict has GPS's on it and is by all accounts a space ruin and that seems loot a bit too gamer. charlie gets away with it by having no GPS's last I checked.

**Comment by TheBonded** [comment]
@D4C-420 since when does the derelict have GPSs on it?

**Comment by D4C-420** [comment]
> @D4C-420 since when does the derelict have GPSs on it?

I'm pretty sure in the chapel like area it has one. Then again I might be misremembering it.

**Comment by TheBonded** [comment]
> > @D4C-420 since when does the derelict have GPSs on it?
> 
> I'm pretty sure in the chapel like area it has one. Then again I might be misremembering it.

fairly certain it doesn't, though it is massive so it's easy enough to find anyways

**Comment by D4C-420** [comment]
> fairly certain it doesn't, though it is massive so it's easy enough to find anyways

That too. I still think a turbine is the way to go though or if you really want to get wacky a terrible idea is let them make a HFR. Its atmos SM .

**Comment by TheBonded** [comment]
> > fairly certain it doesn't, though it is massive so it's easy enough to find anyways
> 
> That too. I still think a turbine is the way to go though or if you really want to get wacky a terrible idea is let them make a HFR. Its atmos SM .

or you could give them more solars. that could work too. they need something more I think, to make people want to choose them more

**Comment by WlarusFromDaSpace** [comment]
>Giving derelict an sm shard could work, but it would just make it a discount charliestation.

If I remember correctly there was discussion on why the derelict has the TEG sometime ago ~1 year and it was explicitly decided that it would't have a SM shard and would have the TEG instead.

**Comment by RandomGamer123** [comment]
There is no way a PR giving derelict the TEG without rebalancing the TEG entirely will get merged, and the latter is well.... complicated.
Argubly the turbine is even more broken than the TEG (makes power by moving gas vs makes power from heat) but well what can you do
