### ISSUE TITLE
Pop-ups steal focus, leading to many accidental ghost roles

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#59517]
## Reproduction:
Be in the middle of typing something as an observer. 
Have a ghost role prompt pop up. 
Hit space because you're in the middle of typing. 
Accidentally hit "yes" and get the ghost role you didn't want. 
Suffer.

**Comment by Mothblocks** [comment]
im pinning this because its FUCKING ANNOYING

**Comment by Mooshimi** [comment]
This has reverted into an issue again recently

**Comment by san7890** [comment]
there's been many notable changes to how ghosts are offered roles (#80283 being the latest) and also we have a toggle to turn off ghost roles completely (as added in #68102)
