### ISSUE TITLE
The chameleon Optical Meson Scanner found in the Chameleon kit is not working

### ISSUE THREAD

**Issue by Gorax** [tgstation/tgstation#59527]
Reporting client version: 513.1542

### Reproduction:

When you equip the the chameleon Optical Meson Scanner found in the Chameleon kit, it doesn't work as a meson scanner, you can't see rooms through walls.

**Comment by newfren** [comment]
isn't this intentional? It's not a meson scanner it's a pair of chameleon glasses.

**Comment by Gorax** [comment]
It might be intentional but I find it weird as Thermal Imaging Glasses that also have the chameleon ability spawn as thermal glasses. If the chameleon glasses in the chameleon kit are supposed to be just chameleon glasses, they should have a default skin that would not imply that they have other abilities in my opinion.

**Comment by TemporalOroboros** [comment]
I thought that was a set of thermals, not mesons.
