### ISSUE TITLE
Adding, removing and re-adding traitor status via admin tools can result in an unusable pda uplink.

### ISSUE THREAD

**Issue by Boggart** [tgstation/tgstation#5953]
Making someone a traitor as an admin then removing and re-adding their traitor status can result in their pda losing it's uplink ability. The admin was unable to fix the uplink and we finally worked around it by me dropping my pda so that the next toggle of traitor status gave me the radio uplink.

**Comment by tedward1337** [comment]
This isn't a bug, admins need to regive an uplink via the antag panel for it to work
