### ISSUE TITLE
Can't eat meat

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#59549]
## Reproduction:
Chop something up, make a steak- you can't eat it
Make some bacon- you can't eat it
Pretty sure cutlets are having the issue, too
This is also happening with deep-fried meat unless you overfry it

**Comment by legoscape** [comment]
Cook up a slab of meat and you just cannot chew it or eat it for some reason. Easily Testable and reproducable.

**Comment by Stickymayhem** [comment]
based

**Comment by Dmeto** [comment]
This also seems to stop carp taming for carps.

**Comment by dragomagol** [comment]
Was supposed to be fixed by #59855 but appears to still be broken.
![image](https://user-images.githubusercontent.com/66640614/123718288-9cc4b180-d833-11eb-8985-fd596c8fec13.png)
(Grilled xeno steak on the left, spawned-in xeno steak on the right)

**Comment by dragomagol** [comment]
Fixed by #59855
