### ISSUE TITLE
Infinite Dankpizza glitch

### ISSUE THREAD

**Issue by LordQuailius** [tgstation/tgstation#59552]
Reporting client version: 513.1542

## Round ID:
[163678](https://scrubby.melonmesa.com/round/163678)

## Testmerges:
- [Fixes OOC heart commendations](https://www.github.com/tgstation/tgstation/pull/59543)
- [Lowers the cold temperature activation threshold for fire alarms/firelocks](https://www.github.com/tgstation/tgstation/pull/59205)
- [2FA for Admins](https://www.github.com/tgstation/tgstation/pull/59467)
- [Lizard Food: a Taste of the Homeworld](https://www.github.com/tgstation/tgstation/pull/59412)

## Reproduction:
The pizza box comes from the ordered pizza crate from cargo.
It must be a box containing a dankpizza, does not work with other types of pizza.
When the empty dankpizza box is used in hand while it is closed, the box simply opens with another dankpizza inside. It does not turn into a stack of cardboard like other normal pizza boxes do.

**Comment by Y0SH1M4S73R** [comment]
SCP-458, but everybody prefers dankpizza.

**Comment by LordQuailius** [comment]
oh I had no idea that existed, sorry
