### ISSUE TITLE
Alt clicking to open a container is weird sometimes

### ISSUE THREAD

**Issue by TheBonded** [tgstation/tgstation#59566]
## Reproduction:
1. find a box or satchel or some other container on the ground
2. alt click on it to open it
3. an object panel appears where you statuspanel is, this doesn't matter because you are looking in the storage of the container you just opened
4. walk away without changing your statuspanel (so it still shows the object panel for the tile you alt clicked)
5. the objectpanel will disappear and go back to the statuspanel as you walk away from the tile it was centered on, but 30-60% of the time it will continue to spam opening and closing, quickly switching between the object panel and status panel, which is really annoying and distracting.

 I have found that to stop it, sometimes just clicking on one of the other options like the admin or preferences panel will work, but other times it will continue switching between the object and current panel and to fix that you have to alt click a tile again, then click one of the panel options to fix it.

**Comment by SuperNovaa41** [comment]
pretty sure this was fixed
