### ISSUE TITLE
Durathread Invisible to Third Parties

### ISSUE THREAD

**Issue by sixrocket** [tgstation/tgstation#59569]
## Reproduction:
Durathread choking fibers as produced by Golems are unable to be seen by third parties: this means that medical staff, first aid, etc attempting to revive you after you've gone down to a magical choking fiber are unable to remove/assist you in any way. The fibers, simultaneously, appear to keep you in a state of permanent crit/near crit unconsciousness without killing you from O2 starvation.

**Comment by ATH1909** [comment]
the emperor's new garotte
