### ISSUE TITLE
SM delam moodlet isn't activating

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#59571]
## Reproduction:
* delam the SM
* don't receive a negative moodlet about those "goddamn engineers not doing their job right"

**Comment by Thunder12345** [comment]
You get the moodlet if you stand out in the open, so this may be intentional since being in a locker protects you from the other effects of delams

**Comment by RaveRadbury** [comment]
> You get the moodlet if you stand out in the open, so this may be intentional since being in a locker protects you from the other effects of delams

I stood out in the open for it and it didn't happen, which is why I'm reporting it.

**Comment by Thunder12345** [comment]
Were you on the same z-level, what was the map, were there any testmerges?

**Comment by TheBonded** [comment]
do engineers get a moodlet for it too? something like "it's beautiful" with a positive moodlet? or when singulord/teslord appears, do they get a "All hail lord singuloth/teslord!"?

**Comment by RaveRadbury** [comment]
> Were you on the same z-level, what was the map, were there any testmerges?

Are you saying that you've been able to replicate my experience?

**Comment by vincentiusvin** [comment]
Could not reproduce as of 6deb867f827a3d7c3ce88bbee89c4afe9ad8a82d
![image](https://user-images.githubusercontent.com/54709710/121759545-60653600-cb50-11eb-94cd-14a9d96600b9.png)

**Comment by RaveRadbury** [comment]
I think it happened to me on meta around the abandoned commissary. I'll keep an eye out and maybe try to replicate it on live and check local with various maps.

**Comment by Sadboysuss** [comment]
could not reproduce
