### ISSUE TITLE
AI buttons stopped working after reset

### ISSUE THREAD

**Issue by Hiynastrike** [tgstation/tgstation#59589]
Reporting client version: 514.1549

## Round ID:
[163831](https://scrubby.melonmesa.com/round/163831)
## Testmerges:
- [2FA for Admins](https://www.github.com/tgstation/tgstation/pull/59467)
- [[READY] Lighting list cleanup.](https://www.github.com/tgstation/tgstation/pull/59002)
- [Lowers the cold temperature activation threshold for fire alarms/firelocks](https://www.github.com/tgstation/tgstation/pull/59205)
- [Fixes OOC heart commendations](https://www.github.com/tgstation/tgstation/pull/59543)

## Reproduction:

Potentially using a reset module on an AI. All I know is that at some point all my onsceen AI buttons stopped working.

**Comment by Sealed101** [comment]
could not reproduce, also don't see anything in the runtime logs to indicate a problem with the AI HUD; logged runtimes are signal overrides warning for the ai's deploy to shell action
