### ISSUE TITLE
hypnoflash doesn't work

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#59595]
round ID: 163871

 Reproduction:

hypno flash a knocked out person
speak command
doesn't work

hypnoflash a critted person
speak command
doesn't work

hypnoflash a person with space drugs in their system
speak command 
doesn't work

**Comment by RandomGamer123** [comment]
It should only work if they are sleeping, hallucinating, dumb, or under low sanity, and space drugs doesn't hallucinate until overdose, so this seems to be intended

**Comment by private-tristan** [comment]
wait sleeping is different from knocked out meaning i need to get people to use SLEEP instead of morphining them?

**Comment by ATH1909** [comment]
> wait sleeping is different from knocked out

Yes, but...

> meaning i need to get people to use SLEEP instead of morphining them?

Morphine is supposed to cause the sleep condition, so this IS actually a bug.

**Comment by ATH1909** [comment]
I've also heard reports of other people being unable to hypnoflash sleeping people, so this is worth looking into.

**Comment by TemporalOroboros** [comment]
It might be the sleep blinding them so the flash doesn't work.

**Comment by RaveRadbury** [comment]
#58741 is related
