### ISSUE TITLE
Undocumented Range Limit on Direction Component

### ISSUE THREAD

**Issue by halitosisman** [tgstation/tgstation#59619]
Reporting client version: 513.1542

## Round ID:
[163934](https://scrubby.melonmesa.com/round/163934)

## Reproduction:
Set up a circuit to say an entity's direction. After getting more than 7ish tiles away from the entity, the direction component becomes inactive. If this is intended it may be a good idea to add that property to the description.

**Comment by Watermelon914** [comment]
Intentional but I'll look at adding a more detailed view on components.
