### ISSUE TITLE
Carbon Roses can mutate into Carbon Roses

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#59626]
## Reproduction:
1. Mutate a rose into a carbon rose
2. Continue feeding the carbon rose Left-4-Zed
3. Observe the carbon rose mutate... into the carbon rose.

**Comment by MrMelbert** [comment]
https://github.com/tgstation/tgstation/blob/2031288fc878dbb6342808d091163845c4197bf2/code/modules/hydroponics/grown/flowers.dm#L335-L355

Whoops.
