### ISSUE TITLE
Multiple Departmental Security Officers possible

### ISSUE THREAD

**Issue by Googles-Hands** [tgstation/tgstation#59631]
## Reproduction:

1. variant is that multiple people select security officer as their job with the same department they'd like to be posted in, instead of only allowing one officer per department and once they are all filled just assigning them the generic officer slots, multiple people can be staffed as guards in the same department, I had the joy of three people spawning as medical officers in the checkpoint

2.  variant is that there is already a guard for a certain department (for example let's say science), so you already have one or more (see first variant) departmental guards, then another player joins as an officer with science as their department of choice and they also get assigned as science

**Comment by SkeletalElite** [comment]
This is intentional

In order to promote officers sticking and working together, officers are put in groups of 2 or 3 and will not leave an officer without a group unless there is only one officer.

**Comment by Mothblocks** [comment]
https://github.com/tgstation/tgstation/pull/57685
