### ISSUE TITLE
Contractor Tablet Register button not working

### ISSUE THREAD

**Issue by CinzaFalso** [tgstation/tgstation#59630]
## Round ID:

[163983](https://scrubby.melonmesa.com/round/163983)

## Reproduction:

I bought a contractor kit, registered on it and opened the target list. After that, I bought an empty tablet, and proceeded to transfer all the contractor's tablet parts to the new one, to make it 'stealthy'. After putting all parts on and turning on the tablet, I couldn't press the 'Register' button that appears when first getting the tablet (When you press it, comes some flavor text and a cool sound effect), meaning I clicked on the 'Register' button but absolutely nothing happened. Me and an admin tried to work around it by buying the kit again twice after transferring the internal tablet parts back to the old one, but nothing solved it and therefore I couldn't do contracting at all that shift, which ended in a refund, but I digress.

**Comment by MrMelbert** [comment]
I'm pretty sure the bug is from people cryoing.
