### ISSUE TITLE
Cyborg upgrade vanishing when disassembled

### ISSUE THREAD

**Issue by deusmacha** [tgstation/tgstation#59647]
Reporting client version: 513.1542

## Round ID:
[164057](https://scrubby.melonmesa.com/round/164057)

## Testmerges:
- [Adds Neon Carpet](https://www.github.com/tgstation/tgstation/pull/59140)

## Reproduction:

Medical cyborg, unsycned to AI from roundstart
upgraded with self-repair, defibrillator (from medical lathe, not cyborg upgrade), crew pinpointer upgrade, expanded hypospray
headlamp broken by nightmare
disassembled and reassembled to fix headlamp
Hypospray upgrade appears to have vanished upon being disassembled

**Comment by AlinaStarkova** [comment]
from my own experience last year, its very specifically the upgrades you have in your active module slots that vanish when your dissasembled (complete dissasembly will make you lose all your upgrades, but cutting wires to lock the borg with make active upgrade modules vanish)

**Comment by Mooshimi** [comment]
https://github.com/tgstation/tgstation/blob/76c94d3fc24d9cad80d7fd046cb9941097715b99/code/modules/mob/living/silicon/robot/robot.dm#L456-L498

guh.....

**Comment by Sealed101** [comment]
the funny part is that upgrades drop to the floor when a model is reset, but not when the borg is disassembled (L734-735)

https://github.com/tgstation/tgstation/blob/d901e0e412cde55f88d1c7789bb514dc72f610fb/code/modules/mob/living/silicon/robot/robot.dm#L713-L740
