### ISSUE TITLE
Wigs only appear on head when held

### ISSUE THREAD

**Issue by Ed640** [tgstation/tgstation#59653]
Reporting client version: 513.1542

## Round ID:
[164079](https://scrubby.melonmesa.com/round/164079)

## Reproduction:
Start a round with the Smooth-Headed quirk. 
While the wig is on the head slot it will be invisible, but holding it in either hand will show it being worn but will still give the negative bald moodlet.

**Comment by TemporalOroboros** [comment]
Whoops. I added an early return to wigs and it appears that I didn't actually flip the check. Easy fix.

**Comment by RaveRadbury** [comment]
Literally unplayable. 😭

**Comment by dragomagol** [comment]
Will be fixed by #59661
