### ISSUE TITLE
Ling breaks Communion ability

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#59666]
Reporting client version: 513.1542

## Round ID:
[164135](https://scrubby.melonmesa.com/round/164135)

## Reproduction:
As ling, noticed I had the Communion skill on the top left greyed out after teleporting to dorms bathroom, stunned someone standing there with the Stun prepared beforehand, and was stunned by sec. Noticed while I was cuffed and being dragged to sec that I had lost the skill.

**Comment by necromanceranne** [comment]
No BZ in the air?

**Comment by Mooshimi** [comment]
How would I check this for the round and area after hand?

**Comment by Mooshimi** [comment]
Unable to reproduce and not sufficient details.
