### ISSUE TITLE
Monkey Person Revival: 'Working as intended'

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#59669]
## Round ID:
[164144](https://scrubby.melonmesa.com/round/164144)

## Testmerges:
#59543 
#59661 

## Reproduction:
It's, literally just the usual process for being revived with a monkey person body, this was the proposed replacement for cloning.

Since #55614 there have been a lot of issues with monkey code that were said to be fixed eventually, one of the biggest issues is what has happened to monkey people. They inherit all of the behaviour of monkey code, even when a human/player head is placed onto them. One of the most annoying behaviors of this is the trip code that was added to monkeys, attempting to switch places with other places/npcs will cause the revived player to trip as if they were playing brawl.
![image](https://user-images.githubusercontent.com/16896032/121988704-2a3ce600-cdde-11eb-9b08-572d80d9d2c3.png)

Another MASSIVE issue that takes place with the new monkey code takes place whenever a player disconnects, they will completely inherit the monkey. When a monkey is injured it will be hostile and attack anything that harmed them in the past, this includes the head removal/revival surgery. I was in the thunderdome and had someone perform both surgeries, I logged out for approximately a minute. This immediately happened.

![image](https://user-images.githubusercontent.com/16896032/121989346-55740500-cddf-11eb-884e-7783b50b1567.png)
![image](https://user-images.githubusercontent.com/16896032/121989353-59078c00-cddf-11eb-84fb-8d97d87338b9.png)

The monkey AI code isn't really being maintained anymore outside of just adding more interactions for the sole purpose of being funny. This has been really shitty, we still have two antags whose only method of revival is this surgery (Heretic and xenos), being reduced to being barely functional.

**Comment by optimumtact** [comment]
we don't actually care though

**Comment by ATH1909** [comment]
> we don't actually care though

YOU don't, but some of the rest of us do

**Comment by LemonInTheDark** [comment]
Was it the proposed replacement for cloning? I thought the secret monkey technique was a joke.
Can't you use podcloning for this?

**Comment by optimumtact** [comment]
@ATH1909 and none of them are headcoders, so it's not a problem

**Comment by carshalash** [comment]
> Was it the proposed replacement for cloning? I thought the secret monkey technique was a joke.
> Can't you use podcloning for this?

Can't syringe heads. Doing so will just remove all organs from the head.

**Comment by EricZilla** [comment]
> Can't syringe heads. Doing so will just remove all organs from the head.
That kinda sucks, can you not blend up the brain to make goop that would work for pods?

Glad to see this being taken care of though, I've been roundended by internet interruptions and my monkey body going berserk

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/60139
