### ISSUE TITLE
Wheelchair FREE using the power of the prosthetic quirk

### ISSUE THREAD

**Issue by oklews** [tgstation/tgstation#59671]
## Round ID:
[164151](https://scrubby.melonmesa.com/round/164151)

## Testmerges:
None

## Reproduction:
Become wheelchair bound, and hope for a cool robot arm. Get robot leg and score neither.

**Comment by Time-Green** [comment]
Not a bug. Prosthethics override paralyzes, so you’d have one working leg in this case. I’m a bit biased so I’ll let someone else label this
