### ISSUE TITLE
Statues can push the SM when they run into it

### ISSUE THREAD

**Issue by JoshAdamPowell** [tgstation/tgstation#59695]
## Testmerges:

#59676: 'Refactors dbcore and limits the maximum amount of concurrent async queries to a variable amount' by Watermelon914 at commit 1c26efb103
#59650: 'Revert "Prevent SSinput from constantly requesting moving in-place"' by brotherbeyondd at commit 88d53885b4
## Reproduction:

Create a statue, this happened naturally by wizard but verified with admin tools, spawn a `/obj/machinery/power/supermatter_crystal` and a `/mob/living/simple_animal/hostile/statue`

Take control of the statue and walk into the SM. You'll get dusted but it will move the SM one tile.

**Comment by Time-Green** [comment]
Move force moment

**Comment by ATH1909** [comment]
feature
