### ISSUE TITLE
RD's preset modular console can't edit IDs

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#59722]
## Testmerges:
#59661: 'Fixes wigs' by TemporalOroboros at commit d222e286bf

## Reproduction:
1) Download the ID edit program on the RD's computer.
2) Insert ID.
3) Click on program.

Clicking on it shows a warning saying you can't use the program without an ID slot, but the computer already has one installed. RD's tablet works fine so this isn't a huge deal but should still be fixed.

This happened on Tram but it also happened when I spawned the console in manually.

**Comment by zxaber** [comment]
I believe the actual issue is that preset RD consoles don't have a secondary card slot. ID editing requires two ID card slots, and you can switch the hardware item between primary and secondary with a screwdriver.
