### ISSUE TITLE
The Black Square.

### ISSUE THREAD

**Issue by legoscape** [tgstation/tgstation#59738]
This bug is very interesting and very wacky. I originally found it on Direlect Z-level as a drone. I've seen it spawn everywhere in space before and is kinda funk. Its messes with building lattaces in space and can even duplicate "space" around it if attempted to be built upon. If anyone can provide a round where these black cubes have spawned please comment below.

**Comment by Serxule** [comment]
sounds like you need to clear your byond cache

**Comment by legoscape** [comment]
No no, These Black cubes are interactable. They are an in-game occurrence that causes funky stuff. I have managed to duplicate space with them. It's weird!

**Comment by TheBonded** [comment]
I have seen these. they spawn in space in random spots.

**Comment by Serxule** [comment]
i've only seem them due to cache issues, try to get a video of it so its easier to see
