### ISSUE TITLE
bluespace body bags become bulky even if theres nothing in them.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#59747]
Reporting client version: 514.1554

## Round ID:
[164406](https://scrubby.melonmesa.com/round/164406)

## Testmerges:
- [Fixes wigs](https://www.github.com/tgstation/tgstation/pull/59661)

## Reproduction:
1. make a bluespace body bag (it will be a small item)
2. put down the bag on the floor, then pick it up without having anything be in the bag
3. pick up the bag (it will now suddenly be a bulky item)

**Comment by TemporalOroboros** [comment]
Same issue as #59704, different symptoms.
