### ISSUE TITLE
Prisoners can be interns

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#59753]
## Reproduction:

A bureacracry error caused a bunch of weird stuff, and among them was a new player signing up as an Intern Prisoner. Intern is used for new players, but I'm not sure why someone would ever want to intern as a prisoner

![image](https://user-images.githubusercontent.com/7501474/122669285-e6225a80-d1bc-11eb-8bf0-7b60b85a8d14.png)

**Comment by maxymax13** [comment]
his spear crafting career has just started

**Comment by Time-Green** [comment]
> his spear crafting career has just started

Assuming he can finish his internship and get a passing grade on his scripture

**Comment by RandomGamer123** [comment]
So there are two questions here:
Should prisoners be allowed to latejoin at all?
Should prisoners be allowed to have the intern prefix?

**Comment by optimumtact** [comment]
not a bug

**Comment by Time-Green** [comment]
Kinda glad this has been marked a feature, because being an Intern Prisoner is such a stupid concept that it’s funny

**Comment by optimumtact** [comment]
im sure it will make good roleplay
