### ISSUE TITLE
Tiles become slippery from synth banana peels, banana peels become non-slippery

### ISSUE THREAD

**Issue by Agux909** [tgstation/tgstation#59769]
## Round ID:
[164493](https://scrubby.melonmesa.com/round/164493)

## Reproduction:

This is a recurring issue and not exclusive to this round.
Synthetic banana peels when placed on the floor lose their slippery attribute and the tile below them "inherits" it. Peels may be taken away or picked up, but the tile will remain slippery and give the respective message as if the peel was still there, effectively creating the illusion of an "invisible banana peel".
Removing and putting back the tiles removes their slippery attribute. Peels losing their attribute in this manner can no longer slip either.

**Comment by Agux909** [comment]
Update:
Removing and putting back the floor tiles no longer removes the slippery turf in that specific location.

**Comment by AnonymousNow** [comment]
Experiencing something similar with bananium ore in the ice caves.

**Comment by SuperNovaa41** [comment]
Not an issue anymore
