### ISSUE TITLE
Hulks can punch the supermatter crystal without dusting

### ISSUE THREAD

**Issue by Urumasi** [tgstation/tgstation#59781]
## Round ID:

Done on a locally built version of the server

## Reproduction:

* Spawn yourself next to any supermatter crystal
* Give yourself the hulk mutation
* Enable combat mode
* Punch the supermatter crystal to everyone's horror
* Survive

**Comment by necromanceranne** [comment]
Too angry to dust.

**Comment by InsaneRed** [comment]
feature

**Comment by Theta0006** [comment]
Hulk op please nerf
