### ISSUE TITLE
Nanite research web

### ISSUE THREAD

**Issue by Wozzy09** [tgstation/tgstation#59799]
## Reproduction:nanite technology requires non-existent technology to research
![Снимок экрана (2)](https://user-images.githubusercontent.com/32817214/123260249-03796080-d4fe-11eb-82ef-e8549d451b02.png)

**Comment by SmArtKar** [comment]
@Wozzy09 It requires hidden illegal tech that can be aquired by deconstructing uplink shit like C4s and such. Close this PR

**Comment by DamnedDog** [comment]
Then maybe someone should add a hidden node thing to the details screen so players don't get confused?
