### ISSUE TITLE
/obj/machinery/vending/custom broken after an item is put in

### ISSUE THREAD

**Issue by 3D-Bat** [tgstation/tgstation#59800]
## Round ID:

n/a

## Testmerges:

n/a

## Reproduction:

have a /obj/machinery/vending/custom, add item, cry because the machine is broken.

![dreamseeker_dVKxhZxyCw](https://user-images.githubusercontent.com/77534246/123265748-a41a5100-d4fb-11eb-9abf-fadfa9ad531b.jpg)

This is a new error message compared to the older issues. If closed I’ll add a comment to the active issue about this.

**Comment by dragomagol** [comment]
It's definitely appears to be a different (though potentially related?) issue than #59445
