### ISSUE TITLE
Water Bottles/soda-cans/colo cups are unable to be used in grenade casings

### ISSUE THREAD

**Issue by tohg7** [tgstation/tgstation#59815]
## Round ID: [164735](https://scrubby.melonmesa.com/round/164735)
It's come to my attention that soda cans, water bottles or the large bottle variant cannot be used in unsecured chemical grenade casings. So to explain what happened, first, i get plastic from disassembling one of cargo's plastic flaps, then i craft a large water bottle, wire up a grenade casing, head to plumbing, fill the bottle with water. Once i tried putting the large water bottle in the grenade, i noticed something amiss, so i put the cap on the bottle and try to put the bottle in the grenade again, i get the message "You must remove the cap before you can do that". When that happened, that's when i found out that water bottles are supposed to be able to be used in grenades, but sadly are bugged, when i try putting the soda can into the grenade, the soda can wouldn't be added to the grenade either, that's when i assumed that colo cups wouldn't work with grenades either.        Which is why i say, if soda cans, colo cups and water bottles could be used as ghetto beakers in grenades, i think it would give more variety to the game in-terms of Ghetto Chemistry and would also buff Medbay so that if the Medbay protolathe is out of glass, all it would take is one Chemist building a plastic factory, then Medbay would be able to use water bottles in replacement of beakers until the protolathe has enough glass for beakers.

If these bugs were fixed, i'm sure that most Chemists mains would appreciate it. Thank you for hearing me out

**Comment by LemonInTheDark** [comment]
This is a feature, not a bug. Regardless of the points you made, this isn't the place to discuss it. You should bring it up on the forums, or make a pr
