### ISSUE TITLE
06/05/2021 Update - Using Items on Backpacks Request

### ISSUE THREAD

**Issue by Ouroborus113** [tgstation/tgstation#59827]
Reporting client version: 513.1507

As per the June 5th, 2021 changelog entry by Timberpoes, if it is not already in the works, I would like it if hand labellers and spraycans would work on backpacks.

**Comment by Colovorat** [comment]
Also fireproof potions for xenobio. Or I remember I needed to fill backpack to use some xenobio potion on it

**Comment by LemonInTheDark** [comment]
This isn't the place for feature requests, if you have an idea you should mention it on the forums
