### ISSUE TITLE
The admin verify cache doesn't seem to be working

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#59823]
i've had multiple reports of admins not being able to verify because of the database connection being down, but then having it auto-verify once it comes back, this suggests that they were still using a verified cid and ip, and the cache file that should be serving as backup is not correctly working to verify them while the db is down.

adminbus leaks on the topic: 
![image](https://user-images.githubusercontent.com/7069733/123485597-418a8900-d5bf-11eb-81f3-0a27c4908236.png)

**Comment by san7890** [comment]
@MrStonedOne do you think this is resolved in a post-#81891 world? i'm just insistent about it because it's literally the only issue open with the "Security" tag so it'd be nice to get it finally cleared up if your refactor suitably addressed the concerns you had in 2021

**Comment by MrStonedOne** [comment]
I confirmed the edge case it was broken on (where the cid wasn't the same cid as the last time they connected, such as using a laptop when you normally use a desktop) works while the db is down.
