### ISSUE TITLE
Genturf spawning when syndicate lavaland base explodes

### ISSUE THREAD

**Issue by brotherbeyondd** [tgstation/tgstation#59833]
## Round ID:
[164830](https://scrubby.melonmesa.com/round/164830)

## Testmerges:
#59750 

## Reproduction:
Explode the lavaland base.
![image](https://user-images.githubusercontent.com/68032262/123516950-9cdb7a80-d696-11eb-87c9-a6ac1992440d.png)

**Comment by dragomagol** [comment]
Duplicate of #57449
