### ISSUE TITLE
Welding Helmets do not block vison

### ISSUE THREAD

**Issue by Gorionus** [tgstation/tgstation#59856]
## Reproduction: use welding helmet, it does not block vision
toggle it off then on, stays the same
spent rest of round wondering if this was caused by previous round transform staff abuse...
no idea what caused it
![tgStation - Terry  EU   CRASHES FIXED  Pride Crypt Papa 2021-06-27 193426](https://user-images.githubusercontent.com/86571339/123556314-d097cc80-d78a-11eb-9b3a-f8591f8e591e.png)
![tgStation - Terry  EU   CRASHES FIXED  Pride Crypt Papa 2021-06-27 193435](https://user-images.githubusercontent.com/86571339/123556315-d392bd00-d78a-11eb-93a9-5b21f004c506.png)

**Comment by MrMelbert** [comment]
Byond bug / dupe issue of blind overlays just not working

**Comment by Gorionus** [comment]
> 
> 
> Byond bug / dupe issue of blind overlays just not working

i hope that the issue was client side, it caused lot of confusion
lets see if clearing cache worked

**Comment by Gorionus** [comment]
clearing cache worked
