### ISSUE TITLE
Using .j to chat in character as an admin messes up some characters

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#59859]
## Round ID:

[164943](https://scrubby.melonmesa.com/round/164943)

## Reproduction:

Speaking through .j
![image](https://user-images.githubusercontent.com/51863163/123581247-211a2480-d7a1-11eb-962f-94c4adc6c6c9.png)

Speaking in character
![image](https://user-images.githubusercontent.com/51863163/123581272-2b3c2300-d7a1-11eb-8224-ddeea02e577d.png)

**Comment by maxymax13** [comment]
nothing like some good ol apostrophe escaping failures, same thing happens with desk announcements

**Comment by Wayland-Smithy** [comment]
caused by a double sanitize happening to the message from 2 `say()` procs
