### ISSUE TITLE
Hallucination-induced fake chasms are not displayed/rendered

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#59862]
Reporting client version: 514.1557

## Round ID:
[164948](https://scrubby.melonmesa.com/round/164948)

## Testmerges:
- [Adds configs to disable laggy hard deletes](https://www.github.com/tgstation/tgstation/pull/59750)
- [Fixes projectile runtime](https://www.github.com/tgstation/tgstation/pull/59824)

## Reproduction:
1. Hallucinate
2. Wander around
3. Fall into a chasm you can't see

**Comment by newfren** [comment]
is this strictly speaking a bug? hallucination tricks you into seeing something that isn't there?

**Comment by TemporalOroboros** [comment]
One of the possible hallucinations picks a random nearby turf and marks it as a chasm. When you step on it you "fall" into the fake chasm and get momentarily hardstunned. The hallucination is supposed to make the turf _look_ like a chasm before you fall into it. I think it's to make it so you can actually not walk into it if you're paying attention. It's not doing that so it's basically turning random turfs into invisible hardstun landmines.

**Comment by rdragan** [comment]
The title is a bit vague, maybe you could edit it to something like "Hallucination-induced fake chasms are not displayed/rendered"
