### ISSUE TITLE
Preferences tab fails to fully load in the lobby

### ISSUE THREAD

**Issue by Wayland-Smithy** [tgstation/tgstation#59912]
## Reproduction:

Happens on my machine v514.1557 and server also v514.1557

1. Join a prod server and click the Preferences tab:
![image](https://user-images.githubusercontent.com/64715958/124029876-770de880-d9aa-11eb-9f2e-5fbc6f478d46.png)
2. Get frustrated when your prefs get wiped and you need to click through 3 screens just to `Stop Sounds` the lobby music
3. Load up a local server to try and solve the issue only to be unable to reproduce it even with localhost admin disabled:
![image](https://user-images.githubusercontent.com/64715958/124030184-cbb16380-d9aa-11eb-9e3d-d6e42d79353f.png)
4. Cry

**Comment by LemonInTheDark** [comment]
Something is strange here, and I'm not sure what's causing it. Holding out for a hero who knows how the stat panel works

**Comment by Wayland-Smithy** [comment]
The issue continues to evolve. Now sometimes they load fine in the lobby, but seem to break when reconnecting as an observer.
