### ISSUE TITLE
White Backgrond, Black Sprites error

### ISSUE THREAD

**Issue by jwc1015** [tgstation/tgstation#59945]
Reporting client version: 514.1557

## Round ID:
[165161](https://scrubby.melonmesa.com/round/165161)

## Reproduction:
I was a posibrain, went AFK to reboot my computer (a process was using a lot of memory) and when I got back I was dead, and everything was black & white. I tried to reconnect, it didn't work. I restarted dreammaker, it didn't work. I restarted BYOND entirely, it didn't work. I had just updated BYOND to the same version as the server, 514.1557; the server also displayed a pop-up telling me to update to 514. 

## Image of the error:
![Capture](https://user-images.githubusercontent.com/64438862/124196507-95eba800-da9a-11eb-9146-1694dc3ca96b.PNG)

**Comment by TemporalOroboros** [comment]
@jwc1015 

This is a server crash, specifically an Out Of Memory (OOM) crash. What you're seeing is the lighting (shadow) and emissive (glowy computer bits and things that block the glowy computer bits) planes without the filters that make them function like they're supposed to.
