### ISSUE TITLE
Combining stacks inside a box lets you bypass the boxes size

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#59951]
## Round ID:
[165179](https://scrubby.melonmesa.com/round/165179), performed with glass, but discovered in two older rounds and reproduced trivially.

## Reproduction:

- Take a stack of metal, glass, rods, etc., too large to fit in a pocket.
- Right click, split into two box-sized stacks (25/25 or 30/30)
- Put one box-sized stack in a box
- Put the other stack in. The stacks now consolidate.
- This can be repeated as long as you have one extra box space, allowing you to overfill your box.

**Comment by Mooshimi** [comment]
repost of #58008
