### ISSUE TITLE
AI's still unable to command bots

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#59973]
165236

## Testmerges:

None

## Reproduction:

>Try to make a bot move A SINGLE TILE to its left
Officer Beepsky called to Starboard Primary Hallway. 1 meters to destination.
Officer Beepsky failed to reach waypoint.

I genuinely don't remember if it has ever worked at this point after the pathing reworking.

**Comment by dragomagol** [comment]
I don't think it has, but duplicate of #58368

**Comment by carshalash** [comment]
@Ryll-Ryll
