### ISSUE TITLE
Cannot place Integrated Circuit into circuit airlock

### ISSUE THREAD

**Issue by rtizzy** [tgstation/tgstation#59992]
Reporting client version: 513.1542

## Reproduction:

1. Print a Circuit airlock.
2. Grab a completed IC
3. Complete the Circuit Airlock (Left click with screwdriver)
4. Click the Circuit Airlock again to undo the hatch
5. Attempt to place the IC

This seems to work with all the other shells so far but I cannot manage to get a circuit inside of a circuit airlock. Somewhat certain this is a bug.

**Comment by Mothblocks** [comment]
CC @Watermelon914

**Comment by Watermelon914** [comment]
Harm intent

**Comment by Mothblocks** [comment]
Is the problem that it just tries to open the airlock? Could we make right-click work as well?

**Comment by Watermelon914** [comment]
> Is the problem that it just tries to open the airlock? Could we make right-click work as well?

it's just how airlocks work, they probably override attackby and it doesn't call parent if you're not on combat intent. You'd have to probably change how airlocks work.

**Comment by timothymtorres** [comment]
This was fixed with #63914
