### ISSUE TITLE
using Sentience Potion on a mob thats sitting/sleeping makes the sentient mob unable to move

### ISSUE THREAD

**Issue by AlinaStarkova** [tgstation/tgstation#60005]
## Reproduction: 
(i did check open issues before posting, didnt see something about this, so if there is an old issue for it apologies)

as a Xenobiologist an early dragon on icebox broke into xenobio, which killed all my slimes, so with the spare gold and light pink extracts i made a sentient cat. however the ghost took the role when the cat layed down, and since players cannot control a simplemobs stance such as stand back up, he was stuck laying down, and hence physically could not move, i ended up putting him inside my backpack but he soon ghosted because thats not really fun lets be real

not sure how i can test this exact scenario on a personal server if i have to use the potion while being a ghost to get the popup, but i did test by force controlling a sleeping cat and i indeed couldnt move

![image](https://user-images.githubusercontent.com/40489693/124371853-dc383700-dc53-11eb-803b-1ab41b53a277.png)
![image](https://user-images.githubusercontent.com/40489693/124371862-e9edbc80-dc53-11eb-9f80-9cc64cdad78d.png)

**Comment by interestingusernam3** [comment]
#56034: cat edition

**Comment by TheBonded** [comment]
If they press the "u" key they unrest.

**Comment by AlinaStarkova** [comment]
> 
> 
> If they press the "u" key they unrest.

if thats true it should be something that happens automatically if the player tries to move as well, very few people know obscure keybinds let alone simplemob keybinds. if the player tries to move it should unrest and move

**Comment by Mooshimi** [comment]
Under IC tab they also have the rest/unrest verb to hit.

**Comment by TheBonded** [comment]
> > If they press the "u" key they unrest.
> 
> if thats true it should be something that happens automatically if the player tries to move as well, very few people know obscure keybinds let alone simplemob keybinds. if the player tries to move it should unrest and move

It's not a simplemob keybind, u is the rest keybind for every creature, including players. It's a main keybind

**Comment by AlinaStarkova** [comment]
> 
> 
> > > If they press the "u" key they unrest.
> > 
> > 
> > if thats true it should be something that happens automatically if the player tries to move as well, very few people know obscure keybinds let alone simplemob keybinds. if the player tries to move it should unrest and move
> 
> It's not a simplemob keybind, u is the rest keybind for every creature, including players. It's a main keybind. If it automatically proc'd every time someone moved you would stand up every time you tried to move while resting.

sure, but my point is that this isnt obvious to most players, if a simplemob can rest and unrest they should maybe have a visual indicator that they can do so rather than just assume they cant move. the vast majority of players dont use the IC tab verbs

**Comment by Mooshimi** [comment]
I'll make it like this so maybe we can get some resting ui button

**Comment by Sealed101** [comment]
simple mobs get the funny immobilize
https://github.com/tgstation/tgstation/blob/bcc2bbd76c4a1d3380d35b3a9a81829177e26c49/code/modules/mob/living/simple_animal/simple_animal.dm#L440-L445
and basic mobs have no such thing. thus the cure is basic mobbing. which the cats have received and i'm halfway sure there are zero other simple mobs that could actually rest. issue fixed? though the rest button is still not available for cats for example, so uhh yeah i dunno
