### ISSUE TITLE
Venus Human Traps aren't numbered

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#60020]
## Round ID:
[165319](https://scrubby.melonmesa.com/round/165319)

## Reproduction:
![image](https://user-images.githubusercontent.com/3204033/124392143-b0e83300-dcb9-11eb-9dea-18895e8f29f3.png)

This is terrible for logs and ahelps as people can't report the number of the mob, which I'm pretty sure is part of why we number spiders, monkeys, and blobbernauts.

**Comment by interestingusernam3** [comment]
Same with rift-spawned space carp.

**Comment by dragomagol** [comment]
Appears to be the case with swarmers as well
