### ISSUE TITLE
lobstrosities can finish charging even while dead

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#60035]
a lobstrosity started its charge wind-up period, died, and then hit me while dead.
<img width="960" alt="lobstrositybug" src="https://user-images.githubusercontent.com/42606352/124447493-0a4a7380-dd47-11eb-8dfc-9c21a0d55f47.PNG">

**Comment by RaveRadbury** [comment]
That's kinda cool though. Species feature.

**Comment by ATH1909** [comment]
> That's kinda cool though. Species feature.

if we want to promote this into being a feature, we should give it a special message or something

**Comment by RaveRadbury** [comment]
> if we want to promote this into being a feature, we should give it a special message or something

"In the throes of death the dread lobstrosity charges towards you!!"

Like they wound up all that energy and its just biomechanics playing out.
