### ISSUE TITLE
unarmed right click attacks outside of combat mode don't proc check_shields

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#60045]
```
/datum/species/proc/spec_attack_hand(mob/living/carbon/human/M, mob/living/carbon/human/H, datum/martial_art/attacker_style, modifiers)
    if(!istype(M))
        return
    CHECK_DNA_AND_SPECIES(M)
    CHECK_DNA_AND_SPECIES(H)

    if(!istype(M)) //sanity check for drones.
        return
    if(M.mind)
        attacker_style = M.mind.martial_art
    if((M != H) && M.combat_mode && H.check_shields(M, 0, M.name, attack_type = UNARMED_ATTACK))
        log_combat(M, H, "attempted to touch")
        H.visible_message(span_warning("[M] attempts to touch [H]!"), \
                        span_danger("[M] attempts to touch you!"), span_hear("You hear a swoosh!"), COMBAT_MESSAGE_RANGE, M)
        to_chat(M, span_warning("You attempt to touch [H]!"))
        return

    SEND_SIGNAL(M, COMSIG_MOB_ATTACK_HAND, M, H, attacker_style)

    if(LAZYACCESS(modifiers, RIGHT_CLICK))
        disarm(M, H, attacker_style)
        return // dont attack after
    if(M.combat_mode)
        harm(M, H, attacker_style)
    else
        help(M, H, attacker_style)
```

`if((M != H) && M.combat_mode && H.check_shields(M, 0, M.name, attack_type = UNARMED_ATTACK))` won't reach check_shields() if the attacker isn't on combat mode, even though you can still shove while not in combat mode. idk if this works with martial arts like krav maga or psychotic brawling.

**Comment by Mooshimi** [comment]
I looked at this area, so I will respond here. There are two procs relevant. Above this one is the proc for right click, which does check block. Only right click can shove now.
![image](https://user-images.githubusercontent.com/85910816/170693237-3d57de6e-673b-4064-9b90-3bc41d0b6576.png)
This proc only triggers on right click and the one you showed will trigger on left click. This is the reason the bottom of yours show disarm, harm, and help. The disarm is that punch that smacks the weapon out of your opponent's hand.

**Comment by Mooshimi** [comment]
Please hold, stupid loading....

**Comment by MrMelbert** [comment]
#79233
