### ISSUE TITLE
Null value in crusher trophy list, causing runtimes / projectiles to get stuck

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#60047]
## Round ID:

[165421](https://scrubby.melonmesa.com/round/165421)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/124547098-3ae6e780-ddf1-11eb-9fba-6469b3f93fd0.png)

A null value entered the crusher's list of trophies, causing a plethora of runtimes as it was attempted to call various trophy effects on a null entry.

**Comment by wulfenbach-jpg** [comment]
Trophies on fire when being added to the crusher remain in the list of trophies but become deleted.
![image](https://user-images.githubusercontent.com/53832839/216857375-b169e30d-1b08-46fe-9eac-671994b2fd1d.png)
Reproduceable, however the period after which the trophy is deleted before the list has a entry that says `= null` and the projectiles stalling is considerable.
