### ISSUE TITLE
Changling absorbed Ethereals can regenerate 

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#60059]
## Round ID:
[165469](https://scrubby.melonmesa.com/round/165469)

## Reproduction:

- Be a changeling.
- Kill an ethereal.
- Give them the absorb suck -> husk.
- Wait a bit.
- Ethereal regenerates as if nothing happened.

Given the absorb husk is supposed to be "ya done" this is kind of absurd.

**Comment by Iamgoofball** [comment]
ruled not a bug by @SuperNovaa41
