### ISSUE TITLE
tgui: Unhandled Rejection: Failed to open IDB: UnknownError

### ISSUE THREAD

**Issue by mrcheese113** [tgstation/tgstation#60054]
## Reproduction: My entire text box has a fatal error and keeps reproducing the same error, including a screenshot.

user ID is mrcheese113, playing on BeeStation Sage
 
![error](https://user-images.githubusercontent.com/87030351/124632060-d8193e80-de38-11eb-99ce-51cb52d9a899.png)

**Comment by jlsnow301** [comment]
I think this issue should be submitted to beestation if you received it there. They are likely using an outdated version of tgui
