### ISSUE TITLE
Custom Vendor Bluescreen, also custom vendors explode when you try to delete them

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#60071]
## Reproduction:
![image](https://user-images.githubusercontent.com/3204033/124822880-23654700-df36-11eb-962a-06cf84ea1b25.png)
This happens when anything is put into a custom vendor
Then the guy who ahelped it asks you to delete it, you delete it and suddenly it explodes? What?

**Comment by dragomagol** [comment]
Duplicate of #59445

**Comment by dragomagol** [comment]
I'll leave this one open since its title is more descriptive than the original report

**Comment by necromanceranne** [comment]
This was, in fact, not actually fixed.
