### ISSUE TITLE
Egun sprites are broken (uses weird map editor version ingame)

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#60077]
![image](https://user-images.githubusercontent.com/6510293/124844433-dbf0b200-df59-11eb-9f1c-2531cae92d26.png)

Server revision compiled on: 
Master commit: c1034abd474f4c52b0a4996949c87f3bd6e6e188

Happens across all rounds, roundstart and new eguns, seems to be visible to everyone

Not sure which PR caused it after a quick skim

**Comment by TheBonded** [comment]
cute epistols
