### ISSUE TITLE
borgs, unlike humans, can be pushed even if they're in combat mode

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#60076]
![image](https://user-images.githubusercontent.com/42606352/124844361-b19ef480-df59-11eb-89a2-9d6376c4ae10.png)
idk if this is intentional or not.

if someone wants to make a PR to correct this, make sure that there's a stat check or something in there so that borgs who died while in combat mode won't become blockades.

**Comment by AlinaStarkova** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/42606352/124844361-b19ef480-df59-11eb-89a2-9d6376c4ae10.png)
> idk if this is intentional or not.
> 
> if someone wants to make a PR to correct this, make sure that there's a stat check or something in there so that borgs who died while in combat mode won't become blockades.

pretty sure borgs, like people, drop combat mode when they die, combat mode has an unconcious check, similar to how AIs unbolt automatically when they die
