### ISSUE TITLE
AIs can be moved while they're anchored down

### ISSUE THREAD

**Issue by godspeedfunnyman** [tgstation/tgstation#60083]
## Reproduction:
Get an AI, walk into them and they'll move even if they're anchored (Not sure if this requires combat mode to be on)

**Comment by godspeedfunnyman** [comment]
Could be the same problem as this issue #60076 ?

**Comment by dragomagol** [comment]
It might be related; recently I was unable to push an AI as a borg on combat mode as long as I was pulling (when I stopped pulling them I was able to push)

**Comment by godspeedfunnyman** [comment]
Ah, found why it did it

Apparently if you turn off combat mode as an AI you can be pushed while anchored, is this still considered a bug or should I close it?

**Comment by dragomagol** [comment]
It seems like an oversight that AI would have combat mode and that they would be pushable while anchored at all, I think you should leave it open.
