### ISSUE TITLE
Getting caltropped reads out the turf below the item instead of the actual item

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#60097]
## Round ID:
[165594](https://scrubby.melonmesa.com/round/165594)

## Reproduction:

- Have no shoes
- Step on glass
- 
![image](https://user-images.githubusercontent.com/51863163/125019276-4f6af000-e03c-11eb-8ba2-167a05f6a78a.png)

**Comment by ArcaneMusic** [comment]
Also occurs as well most commonly when stepping on ants. Primarily a feedback issue with the caltrop component so it should be fairly simple to get fixed.
