### ISSUE TITLE
Non-human Species Cosmetic features will layer over some mask items oddly.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#60098]
## Round ID:
[165601](https://scrubby.melonmesa.com/round/165601)

## Reproduction:

With the latest change to special species organs, it seems that some parts like lizard horns and frills will layer over some masks oddly, when before it would layer over these parts. 

It's fairly obvious here with the tiki mask.

![image](https://user-images.githubusercontent.com/33107541/125027478-4dad2680-e054-11eb-9242-f612b1b18e87.png)

**Comment by MrMelbert** [comment]
I mentioned it [here](https://github.com/tgstation/tgstation/issues/60092#issuecomment-876922513), too, but snouts, frills and horns are all layering incorrectly, likely due to the species organ PR.

**Comment by Time-Green** [comment]
100000% my fault. Although the tiki mask looks fine to me

I’ll just go ahead and visit some live servers and check what expected behaviour should be
