### ISSUE TITLE
moths have no wings anymore, and probably some other issues.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#60092]
## Round ID:
irrelevant

## Testmerges:
Manuel

## Reproduction
@Mothblocks what the fuck did you do?
moths can not customize there wings or antenna anymore (option is missing from the customize menu).
Lizards apparently have no nose customize option anymore (haven't checked myself, however).
also some moths have literally just have no wings anymore cause of this issue.

**Comment by RaveRadbury** [comment]
Likely related to #59981 @Time-Green

**Comment by Mothblocks** [comment]
@Mothblocks what the fuck did you do?

**Comment by redguy999** [comment]
> @Mothblocks what the fuck did you do?

oh wait you didn't make the PR my mistake.

**Comment by Mothblocks** [comment]
one time i made a pr that didnt actually work for any species other than humans and moths because i only have a moth character on local, you can trust me that i wouldve noticed that quite soon

**Comment by redguy999** [comment]
ok, figured something out, the wings only disappear when you have anything in the exosuit slot.

**Comment by redguy999** [comment]
the condition for having wings disappear is flipped. It is also applied to normal moth wings, although that second part may not be a bug.

**Comment by MrMelbert** [comment]
#58641 Appears to also have been accidentally regressed by the same PR.

**Comment by Time-Green** [comment]
Yeah yeah yeah
Also preferences broke? That’s a new one

**Comment by redguy999** [comment]
> Also preferences broke? That’s a new one

here's how prefs for moths look now:
![_tg_Station Manuel  ENGLISH   US-WEST   ROLEPLAY   99% LAG FREE _ Carp Crypt Twenty 7_9_2021 3_51_13 PM](https://user-images.githubusercontent.com/61719178/125129915-1e3b0000-e0ce-11eb-9d23-d4df48ac89e8.png)

**Comment by Mothblocks** [comment]
can you file a separate bug report for that, my pr fixes *this* issue but probably not that one

**Comment by Time-Green** [comment]
> > Also preferences broke? That’s a new one
> 
> here's how prefs for moths look now:
> ![_tg_Station Manuel ENGLISH US-WEST ROLEPLAY 99% LAG FREE _ Carp Crypt Twenty 7_9_2021 3_51_13 PM](https://user-images.githubusercontent.com/61719178/125129915-1e3b0000-e0ce-11eb-9d23-d4df48ac89e8.png)

Really weird. Maybe some unlucky runtime could’ve done that? I haven’t touched preference code at all, but I’ll look at it tomorrow

**Comment by redguy999** [comment]
> can you file a separate bug report for that, my pr fixes _this_ issue but probably not that one

i shall do that now.

**Comment by redguy999** [comment]
> Really weird. Maybe some unlucky runtime could’ve done that? **I haven’t touched preference code at all,** but I’ll look at it tomorrow

Since you changed what the moth wings are, but not what the prefs are looking for when making the boxes, the prefs might be looking for something that no longer exists when trying to creating them. This also explains why the markings are still working, since they aren't an organ.
