### ISSUE TITLE
the movement of the crab-17 checkout machine interrupts the do_after() for cashing out with it

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#60118]
so you can basically only cash out if you've somehow pinned it into a single-tile space despite it moving like twice every second.

this is bad because it discourages actually interacting with the checkout machine the intended way (by making it an absolute bitch to do), which indirectly encourages just unga dunga bashing the checkout machine with a stick.

**Comment by ATH1909** [comment]
also, the check_if_finished() proc seems kind of pointless, since it'll only return TRUE if ALL of the bank accounts that were being dumped (so basically all of them except for the account of the person who used the suspicious phone and accounts that were created after the usage of the suspicious phone) have been saved via interaction with the checkout machine. that proc is called whenever someone tries to use an item on the machine (regardless of whether or not it's an ID card) and whenever someone successfully cashes out, and it iterates through every bank account in the game until it either finds one that's still being dumped or manages to check all of them.

**Comment by Mothblocks** [comment]
> this is bad because it discourages actually interacting with the checkout machine the intended way (by making it an absolute bitch to do), which indirectly encourages just unga dunga bashing the checkout machine with a stick.

on my todo:

> crab 17 invincible and when you attacxk it it says “your [weapon] gets stuck in the id slot” and youre stunned for a bit so you read the damn chat

i dont consider this a bug
