### ISSUE TITLE
Some non-human prefs are missing

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#60117]
## Round ID:
irrelevant

## Testmerges:
Manuel

## Reproduction:
![_tg_Station Manuel  ENGLISH   US-WEST   ROLEPLAY   99% LAG FREE _ Carp Crypt Twenty 7_9_2021 3_51_13 PM](https://user-images.githubusercontent.com/61719178/125146761-92d56500-e0f5-11eb-9b5f-7014bfc8dd3f.png)

**Comment by MrMelbert** [comment]
Lizards are missing an entire column. This is live:
![image](https://user-images.githubusercontent.com/51863163/125148842-bbac2900-e0fa-11eb-89ec-878fb01ad888.png)
This is past:
![image](https://user-images.githubusercontent.com/51863163/125148852-cb2b7200-e0fa-11eb-9269-2c2388a48c35.png)
