### ISSUE TITLE
Rust heretics don't spread rust

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#60121]
## Round ID:

#165656

## Testmerges:
#60066 

## Reproduction:

>use any of my multiple rust abilities
>Floors just get the green rune and don't rust

It's, straight up caused by this. #59977

**Comment by MrMelbert** [comment]
More accurately, rust heretic acting upon walls will apply the rust component, but will not always update the wall's icon to be rusted.

Additionally, the rusty floor type simply does not exist anymore, so rust heretics can't get healed from rusty floors.
 
Additionally additionally, floors can't even be rusted, period. Attempting to apply the rust component to floor plating doesn't work. Even if you spawn the preset rusted floor plating, it doesn't apply the component.

**Comment by ZephyrTFA** [comment]
> 
> 
> More accurately, rust heretic acting upon walls WILL apply the rust component, but WILL NOT always update the wall's icon to be rusted.
> 
> Additionally, the rusty floor type simply does not exist anymore, so rust heretics can't get healed from rusty floors. The following code snippet cannot run since it's based on a component and the turf type does not exist anymore.
> 
> https://github.com/tgstation/tgstation/blob/99dc0fe5f6f70e3279c345b000d492b175365b9a/code/modules/antagonists/eldritch_cult/knowledge/rust_lore.dm#L82
> 
> Additionally additionally, floors can't even be rusted, period. Attempting to apply the rust component to floor plating doesn't work. Even if you spawn the preset rusted floor plating, it doesn't apply the component.

I'll look into it
