### ISSUE TITLE
statues from the icebox spring don't get their spells

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#60134]
```
/mob/living/simple_animal/hostile/statue/Initialize(mapload, mob/living/creator)
	. = ..()
	// Give spells
	LAZYINITLIST(mob_spell_list)
	mob_spell_list += new /obj/effect/proc_holder/spell/aoe_turf/flicker_lights(src)
	mob_spell_list += new /obj/effect/proc_holder/spell/aoe_turf/blindness(src)
	mob_spell_list += new /obj/effect/proc_holder/spell/targeted/night_vision(src)

	// Set creator
	if(creator)
		src.creator = creator
```
They're supposed to receive three spells (which are critical for statue gameplay that isn't just "attack people who're in the dark without a PDA light on for some reason" or "stand still (and mute) forever because people won't stop looking at you") in Initialize().

I got none of them:
<img width="960" alt="nospells" src="https://user-images.githubusercontent.com/42606352/125153547-0d17e080-e11a-11eb-9b83-bb46c211b39d.PNG">

**Comment by ATH1909** [comment]
Also, I was unable to deal any damage by running into airlocks or walls, even though I could still push windows

**Comment by Mooshimi** [comment]
I actually encountered a statue from the pond who went on to murderbone on station, and they used the blindness spell fine.

**Comment by timothymtorres** [comment]
> From you having that tab I'm fairly sure you did get the spells, just not the funny top left buttons. So no ui for them besides the tab verbs.

When you’ve played SS13 so long that you remember when there wasn’t fancy UI buttons… heh.

**Comment by Sealed101** [comment]
the round has no runtimes that would point to the lack of buttons or spells
can't reproduce either, let's hope basicmobbing back in https://github.com/tgstation/tgstation/pull/73086 cleaned this up good
