### ISSUE TITLE
Malfunctioning AI appears to not be showing up as frequently, or ever.

### ISSUE THREAD

**Issue by duckay** [tgstation/tgstation#60133]
I've sifted through the rounds and through a binary search it turned out that R164589 may have been the last malf, which may suggest that #59765 is the source of the issue, after that, there are no, or at least very sparse amount of malf AI that which I haven't found past R164589

Doesn't feel like a coincidence at all, I don't have a way to reproduce this.

**Comment by Mothblocks** [comment]
dynamic can no longer create malf humans (because it doesnt make malf ais either)

**Comment by Mothblocks** [comment]
CC @YakumoChen @Timberpoes

**Comment by Mothblocks** [comment]
gonna put needs reproducing until we're confident its not just luck, theres very little chance it is but want to be sure

**Comment by Mothblocks** [comment]
![image](https://user-images.githubusercontent.com/35135081/125161057-ec10b900-e134-11eb-8154-97390355d3bd.png)

it would appear you're wrong

**Comment by Mothblocks** [comment]
https://tgstation13.org/parsed-logs/manuel/data/logs/2021/07/07/round-165480/dynamic.json

**Comment by duckay** [comment]
Either it's really shit luck or I imagine there shouldn't be 200 round gaps for AI malfs

**Comment by Mothblocks** [comment]
Probably because the bug that was forcing it on people who had AI off was fixed 🙂
