### ISSUE TITLE
plumbing grinder didn't extract any reagents from dead holobees

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#60141]
I originally tried to make the factory that I mentioned in the comments of https://github.com/tgstation/tgstation/pull/60138 with a plumbing grinder instead of a manual one, but the plumbing grinder would just absorb the dead bees (which are items, btw) that I threw into it and not extract any reagents from them.

**Comment by ATH1909** [comment]
also, I'm fairly certain that you can use plumbing grinders as one-way blockades. dunno if that's a feature or not or if it works with projectiles.

**Comment by TheBonded** [comment]
aren't holobees specifically set not to leave reagents so you can't abuse it to get free poisons?

**Comment by ATH1909** [comment]
> aren't holobees specifically set not to leave reagents so you can't abuse it to get free poisons?

nope

**Comment by TheBonded** [comment]
> > aren't holobees specifically set not to leave reagents so you can't abuse it to get free poisons?
> 
> nope, grinding their corpses up with a manual grinder worked

that might be an oversight then

**Comment by TheBonded** [comment]
this was fixed by https://github.com/tgstation/tgstation/pull/60138, let's try to crack down on some of the 1.8k issue reports
