### ISSUE TITLE
Malfunctioning customers are malfunctioning

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#60145]
## Round ID: [165674](https://scrubby.melonmesa.com/round/165674)

A malfunctioning customer bot ordered acidic buffer, which spammed runtimes and made him not leave.

![image](https://user-images.githubusercontent.com/35135081/125158176-1ad26380-e124-11eb-85eb-f6745db94bdd.png)

**Comment by Kylerace** [comment]
>be malfunctioning bot
>malfunction
>spam the fuck out of runtimes
>dont leave

**Comment by Nobelium-XVIII** [comment]
feature

**Comment by KittyNoodle** [comment]
feature

**Comment by Mooshimi** [comment]
fixed by #61514
