### ISSUE TITLE
monkey meat doesn't have any protein in it

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#60148]
Round ID: [165678](https://scrubby.melonmesa.com/round/165678)
BYOND Version: 514.1556
Server revision compiled on: 
Master commit: 99dc0fe5f6f70e3279c345b000d492b175365b9a
The following pull requests are currently test merged:
#60066: 'fucking SEXTUPLES ALL TURF DECALS to test for if they affect maptick (like what i did before but more)' by Kylerace at commit 3aa910c8d8

step 1 grind monkey meat
step 2 there's no protein in it
step 3 cry in cytology tears

**Comment by ATH1909** [comment]
for now, it looks like you might be able to get around this by turning those slabs into patties

**Comment by ATH1909** [comment]
@AMonkeyThatCodes

**Comment by ArcaneMusic** [comment]
So, current understanding of this is that the monkey meat SHOULD be assigning all of it's base reagents, as killing a regular cubed monkey does drop everything correctly, and the reagent list is correct, however, once butchered it's reagents gets transformed to only contain cooking oil and nutriment. Looking deeper into it now.
![image](https://user-images.githubusercontent.com/41715314/128095447-3dafedad-ac37-4ebd-bce5-242274c34018.png)

**Comment by AMonkeyThatCodes** [comment]
might be datum material issue, @TemporalOroboros

**Comment by ArcaneMusic** [comment]
Can confirm, it's a material issue, it's creating the reagents based on the meat material datum after the food edible component. Materials should probably not be overwriting the base food's reagents in the first place, all things considered.
