### ISSUE TITLE
Job Selection Bug

### ISSUE THREAD

**Issue by jwc1015** [tgstation/tgstation#60167]
Reporting client version: 513.1542

## Round ID:
[165709](https://scrubby.melonmesa.com/round/165709)

## Testmerges:
- [fucking SEXTUPLES ALL TURF DECALS to test for if they affect maptick (like what i did before but more)](https://www.github.com/tgstation/tgstation/pull/60066)

## Reproduction:
I had assistant set to off, return to lobby on, and janitor set to high; I was set as assistant anyway. (without being antag either)

**Comment by TheBonded** [comment]
this might be an automatic anti antag rolling measure

**Comment by jwc1015** [comment]
> this might be an automatic anti antag rolling measure

Erm, small problem - I had no antag prefs turned on except for nuke ops. (I did have janitor set to high) If it was set to return to lobby then how would I be able to use that for _antag rolling?_ I'm honestly kinda confused.

**Comment by TheBonded** [comment]
> > this might be an automatic anti antag rolling measure
> 
> Erm, small problem - I had no antag prefs turned on except for nuke ops. The nuke ops was just for lone op while observing so I could actually see the popup. (I did have janitor set to high) If it was set to return to lobby then how would I be able to use that for _antag rolling?_ I'm honestly kinda confused.

I don't know the exact specifications for the anti antag rolling measures in place (if there even are any), I was just giving a suggestion for a possible reason.

**Comment by jwc1015** [comment]
> > > this might be an automatic anti antag rolling measure
> > 
> > 
> > Erm, small problem - I had no antag prefs turned on except for nuke ops. The nuke ops was just for lone op while observing so I could actually see the popup. (I did have janitor set to high) If it was set to return to lobby then how would I be able to use that for _antag rolling?_ I'm honestly kinda confused.
> 
> I don't know the exact specifications for the anti antag rolling measures in place (if there even are any), I was just giving a suggestion for a possible reason.

ah, ok! Sorry, was just a bit confused
