### ISSUE TITLE
Obsessed hug objective fails despite obsessed hugging obsession a shitton of times

### ISSUE THREAD

**Issue by interestingusernam3** [tgstation/tgstation#60177]
## Round ID: 
[165702](https://scrubby.melonmesa.com/round/165702)

## Testmerges: 
https://github.com/tgstation/tgstation/pull/59914

## Reproduction:
1. Wait for it to obsessed
2. Cover obsession in hugs
3. Fail hug objective at roundend

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/64701
