### ISSUE TITLE
Bubblegum hits multiple times in a row during a single charge, which causes instant-death or near instant death when hit.

### ISSUE THREAD

**Issue by JebHawkins** [tgstation/tgstation#60195]
## Reproduction

1. Go to lavaland
2. Fight Bubblegum
3. Get hit by any one of his charges and get sent to the space gods.
![image](https://user-images.githubusercontent.com/60949371/125341722-90535500-e319-11eb-9375-abc7c51a3e69.png)

**Comment by Mooshimi** [comment]
Skill issue, as they say. Legionnaire also hits you multiple times if you are hit by the charge.
