### ISSUE TITLE
Wormhole Jaunter doesn't save from chasms

### ISSUE THREAD

**Issue by rasepretep** [tgstation/tgstation#60196]
## Reproduction:
Wear a Wormhole Jaunter on your belt, step on a chasm. It will create a wormhole, but not teleport you. If at that point you move, you fall into the chasm. If you move toward the wormhole, you still die, but your ghost does get teleported to the station.

**Comment by timothymtorres** [comment]
Relevant code details:

https://github.com/tgstation/tgstation/blob/96cc4a72601bd9d8316e4943a0954e8edf550a40/code/datums/components/chasm.dm#L68-L92

https://github.com/tgstation/tgstation/blob/55b92786dcf0f9c5172efd111a6ecbf83ec0dae2/code/modules/mining/equipment/wormhole_jaunter.dm#L73-L79

**Comment by rasepretep** [comment]
I have a feeling that rather than those two files, the underlying issue is gonna be somewhere else.

When you step on a chasm, the jaunter still works and creates a wormhole on the tile that you are on, you just don't get teleported. And if you move back and try to step into the wormhole, you get chasm'd, but your ghost gets teleported to the station.

I wonder if this has anything to do with the current bug where if you step on glass/cactus/banana peel/lube/etc, you get a message "You step on the floor!" instead of naming the item you stepped on.

**Comment by timothymtorres** [comment]
@rasepretep can you make a small code change at:

 ```dm
/obj/item/wormhole_jaunter/proc/chasm_react(mob/user) 
 	if(user.get_item_by_slot(ITEM_SLOT_BELT) == src) 
 		to_chat(user, span_notice("Your [name] activates, saving you from the chasm!")) 
 		SSblackbox.record_feedback("tally", "jaunter", 1, "Chasm") // chasm automatic activation 
 		activate(user, FALSE)
```

Change `activate(user, FALSE)` to `activate(user, TRUE)` and then test it over a chasm and let me know what happens.  I would test this myself but I won't have an opportunity for a few days.  It looks like this small change should fix it.

**Comment by rasepretep** [comment]
@timothymtorres

Tested it just now, unfortunately it's not the culprit. I've been looking into the code before, the TRUE/FALSE flag only determines whether the wormhole appears on the tile the user is standing on, or on a tile adjacent to them.

	/obj/item/wormhole_jaunter/proc/activate(mob/user, adjacent)

Presumably, the way it worked previously was that the wormhole appeared in the user's tile and that triggered going through it right away. That doesn't happen anymore, if a wormhole appears on the tile you're standing on, you have to either click on it, or move away and then move into it again. But on the other hand, when the wormholes station event happens, and one of the random wormholes appears on the tile you're standing on, you're also not teleported, that's how it's always been - hence why everyone is always urged to stand still.

One thing I remember is that when this issue was brought up before in OOC, someone mentioned there was a Jaunter rework for mechs and that it broke things, so the likeliest scenario is that there was a rework of the code back then that didn't take into account that summoning a wormhole on the tile you're standing on does not make you automatically go through it.

I have been trying to figure out how to rework the "chasm-triggered wormhole" code to skip creating the wormhole and instead execute the "teleport to random station beacon" step instead, but I've so little experience that I haven't been able to figure that out yet.

**Comment by timothymtorres** [comment]
@rasepretep thanks for testing this for me.  I will attempt to fix this later this week if it's not too complicated for me to handle.

**Comment by Kylerace** [comment]
@rasepretep dont close issues yourself. if a pr fixes it the issue will be closed automatically

**Comment by rasepretep** [comment]
@Kylerace Oops, I'm sorry. First time and all.
