### ISSUE TITLE
The Reformatted Technology Disks from the B.E.P.I.S. create reality-halting gigalag

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#60193]
## Round ID:
[165811](https://scrubby.melonmesa.com/round/165811) on manual and a bunch of others prior

## Reproduction:
1. Get the B.E.P.I.S.
2. Spend money to get diskies
3. Put diskies in R&D console
4. Press load tech from disk to web
5. Experience some lag
6. Press load tech from web to disk
7. Experience painful lag
8. Repeat step 4 to experience +10% time dilation, and a 5 second freeze, more or less
9. Spam step 8

## Why it prally happens:
Disky has some tech on it
loading from server to disk puts even more tech on it
loading an entire RnD server worth of text into the server makes it shit the bed.

**Comment by ArcaneMusic** [comment]
Part of a larger issue with tech disks, causing them to nearly completely halt the server.
Performance from the UI to the player/server is critically awful and may result in us either needing to gut the science tgui window, or really figure out asset delivery on the current window UI.

**Comment by JohnFulpWillard** [comment]
Wasn't linked in the new PR but this was closed by https://github.com/tgstation/tgstation/pull/61343
