### ISSUE TITLE
Titanium walls are not actually titanium walls, according to the experi-scanner

### ISSUE THREAD

**Issue by TheSmallBlue** [tgstation/tgstation#60216]
## Reproduction:
1. Get an experiment that makes you scan a titanium wall
2. Build a titanium wall (girder out of metal, wrench, put the titanium on top of it)
3. Try to scan it with a Experi-Scanner
4. Disappointment
https://youtu.be/ds1_qFeGfs8

**Comment by TheBonded** [comment]
You can't expiri scan false walls. Stop unwrenching the girder

**Comment by TheSmallBlue** [comment]
The girder is wrenched, what are you talking about

**Comment by TheSmallBlue** [comment]
Nevermind.
