### ISSUE TITLE
reading the code for herald projectiles causes me physical pain

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#60225]
```
/obj/projectile/herald
	name ="death bolt"
	icon_state= "chronobolt"
	damage = 20
	armour_penetration = 60
	speed = 2
	eyeblur = 0
	damage_type = BRUTE
	pass_flags = PASSTABLE

/obj/projectile/herald/teleshot
	name ="golden bolt"
	damage = 0
	color = rgb(255,255,102)

/obj/projectile/herald/on_hit(atom/target, blocked = FALSE)
	. = ..()
	if(ismineralturf(target))
		var/turf/closed/mineral/M = target
		M.gets_drilled()
		return
	else if(isliving(target))
		var/mob/living/L = target
		var/mob/living/F = firer
		if(F != null && istype(F, /mob/living/simple_animal/hostile/asteroid/elite) && F.faction_check_mob(L))
			L.heal_overall_damage(damage)
```
Instead of just making herald projectiles not damage allies, whoever coded herald projectiles decided to instead make them damage allies, then heal them for the base damage of the bolt that hit them.

This causes numerous bugs:
1. If you have more than 60 bullet armor, death bolts from an allied herald will heal you more than they'll harm you.
2. If you have a brute damage multiplier that's <1, death bolts from an allied herald will heal you more than they'll harm you.
3. If you have a brute damage multiplier that's >1, death bolts from an allied herald will harm you more than they'll heal you.
4. If you're at very low health, I think that an allied herald's death bolt might be able to damage you enough to kill you, then heal some of your damage after you're dead (when it's too late).

Also, because heralds have the "boss" faction until someone tumor shards them or otherwise modifies their faction list, free heralds (who won their tumor fight) cannot deal net damage to bosses with their projectiles (unless there's a boss somewhere that has a >1 brute damage multiplier).

**Comment by CRITAWAKETS** [comment]
Augmented limbs also always get healed because they have a flat damage reduction on all damage.

**Comment by KittyNoodle** [comment]
This is fucking horrifying
