### ISSUE TITLE
Auto-Observe breaking ghost vision

### ISSUE THREAD

**Issue by SmArtKar** [tgstation/tgstation#60221]
## Round ID:
Can be viewed in any round

## Reproduction:

1. Toggle Auto-Observe (That small button near Refresh in observe menu)
2. Orbit someone
3. Wait till they enter a mech or ventcrawl
4. See those funky visual glitches like black lines appearing and your camera moving north

**Comment by Wayland-Smithy** [comment]
Probably related to a byond bug fixed in 1558 http://www.byond.com/forum/post/2693839

Looks good at time of posting on 1561
![Ve73kcxIue](https://user-images.githubusercontent.com/64715958/126940406-dbcac496-63da-4578-90c8-90043ad6ade4.gif)

**Comment by Wayland-Smithy** [comment]
Probably related to a byond bug fixed in 1558 http://www.byond.com/forum/post/2693839

Looks good at time of posting on 1561
![F42nD4yFOG](https://user-images.githubusercontent.com/64715958/126940889-99d22dec-1fb4-4b70-9c85-ff96a061b3f2.gif)

**Comment by timothymtorres** [comment]
This appears to be fixed.  Ping me if the problem happens again and I will reopen this.
