### ISSUE TITLE
lizard "organs" like snouts/frills have buggy sprites/names when you scalpel/saw a decapitated lizard head open

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#60234]
## Testmerges: 
#60190: '[DNM] Use rust-g to url_encode (and other builtin overrides)' by Mothblocks at commit 2b9bda2c6f
#59996: 'Harddel Searching: We're doing it live' by LemonInTheDark at commit ae97991c81

## Reproduction:

1. obtain lizard head
2. apply scalpel/saw
3. this happens

![](https://i.imgur.com/Ta6JmxQ.png)

tagging #59981 since its related

**Comment by Fikou** [comment]
@Time-Green

**Comment by Time-Green** [comment]
You guys are always so extremely dramatic with “the feature broke!!” It’s just using dirs when it shouldn’t. I’ll look into it

**Comment by Time-Green** [comment]
You can actually stick them into people to give them those features! Also don’t be so dramatic with “break”, the issue here is that organs have a flag to make them unremovable, but obviously that’s not adhered to everywhere
