### ISSUE TITLE
lizards can't receive advanced upgrade surgeries like vein threading

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#60235]
## Testmerges:
#60190: '[DNM] Use rust-g to url_encode (and other builtin overrides)' by Mothblocks at commit 2b9bda2
#59996: 'Harddel Searching: We're doing it live' by LemonInTheDark at commit ae97991

## Reproduction:

1. be a lizard
2. be on an operating table with all surgeries unlocked
3. observe certain chest/head surgeries not appear when someone tries to start them (in the 'select surgery' menu from the drapes)

this is possibly related to #59981 but i'm not entirely sure

**Comment by ATH1909** [comment]
were you able to perform them on a human?

**Comment by nianjiilical** [comment]
> were you able to perform them on a human?

yeah forgot to mention sorry, they seemed to show up fine when used on a human according to the guy who was ahelping it

**Comment by AlinaStarkova** [comment]
iirc you cant do the advanced surgeries unless its on an operating table that has the computer next to it updated to the latest procedures, or are a medborg with your surgical processor linked to an updated surgerical computer

this may need reproducing to ensure that it wasnt just forgetting to update the surgical computer in that instance?

**Comment by KubeRoot** [comment]
You didn't already have one of the surgeries done, right? The experimental surgeries come in mutually exclusive pairs, and you can only do one of each pair.

**Comment by Donpedrito** [comment]
Tested on local, I was able to perform the experimental upgrade surgeries on a lizard.
