### ISSUE TITLE
The Hat Store Hats don't spawn on CTF Downtown

### ISSUE THREAD

**Issue by NamelessFairy** [tgstation/tgstation#60247]
## Reproduction:

The hats are still in the map file but when the map is loaded ingame none of the hats are present

**Comment by Thunder12345** [comment]
Issue is due to /obj/machinery/capture_the_flag/proc/reset_the_arena() deleting unwanted objects on starting a CTF match, and catching mapped in items in the process

**Comment by Bawhoppen** [comment]
I almost cannot believe how ornate our issues have become

**Comment by NamelessFairy** [comment]
This is fixed
