### ISSUE TITLE
Sentient Disease is inconsistent about what it can "hear" or not.

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#60245]
Reporting client version: 513.1542

## Round ID:
[165992](https://scrubby.melonmesa.com/round/165992)

## Testmerges:
- [fucking SEXTUPLES ALL TURF DECALS to test for if they affect maptick (like what i did before but more)](https://www.github.com/tgstation/tgstation/pull/60066)

## Reproduction:
Spawn in as a sentient disease
Pick host
Revel in your inability to "hear" your host at all:
![image](https://user-images.githubusercontent.com/76874615/125790648-c1b07959-18ee-4103-bf96-4cefb2cb421b.png)
Flipflop hosts when you finally infect someone else just to see you can "hear" your initial infected how:
![image](https://user-images.githubusercontent.com/76874615/125790810-b43b4937-dfcc-4ccf-a174-1fe8b2617287.png)
Infect more, catch a changeling, notice that you can't "hear" them say anything, no matter how hard you try.
![image](https://user-images.githubusercontent.com/76874615/125795907-28449fb4-26e9-4ffb-be82-97929dd52e73.png)
Notice that there doesn't seem to be a real rhyme or reason as to what you can or can't hear, as shown here by this very one sided conversation (there's another person within earshot but they're just Not Audible)
![image](https://user-images.githubusercontent.com/76874615/125797084-ecd7a121-deb4-4e42-905a-8b6efae9ab81.png)
Wonder just what gossip you missed about yourself.

**Comment by TheBonded** [comment]
Parqo is top tier virus btw

**Comment by ATH1909** [comment]
> Parqo is top tier virus btw

do people have sentient virus staticnames????

**Comment by Sealed101** [comment]
sentient disease has been retired as of #83453
