### ISSUE TITLE
Space carp garble names when then gnash at someone

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#60253]
## Round ID:
166031

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/125892164-03a6955b-d063-40f6-aae3-c99bf466ee74.png)

**Comment by AlinaStarkova** [comment]
this is actually just pretty funny, let it be a feature: "carp due to their smaller brains are unable to grasp what it is they even bite"

**Comment by InsaneRed** [comment]
![image](https://user-images.githubusercontent.com/47158596/125900462-e633108e-ee7d-476c-a26c-ef8e3532984e.png)
![image](https://user-images.githubusercontent.com/47158596/125900477-d445ee87-f3ee-45ea-9b5b-a621cdbac745.png)

**Comment by dragomagol** [comment]
Maybe try with a single name? I know it's happened with this name a fair few times, but not all the time

**Comment by InsaneRed** [comment]
![image](https://user-images.githubusercontent.com/47158596/125902849-a4f72307-426f-490f-bf87-97a975111027.png)
![image](https://user-images.githubusercontent.com/47158596/125902876-59c5223d-3f01-448f-907c-2942ace7f0ad.png)
maybe too short?

**Comment by AlinaStarkova** [comment]
> 
> 
> Maybe try with a single name? I know it's happened with this name a fair few times, but not all the time.
> 
> Edit: just peeked at the logs for this round, it called me both "Moherilian" and "Mohimilian"

did you perhaps have a quirk or brain damage or just, whatever, that made you have difficulty recognizing names (they do exist iirc)

**Comment by InsaneRed** [comment]
![image](https://user-images.githubusercontent.com/47158596/125903668-41f6db67-03c7-4750-9530-8881b3a09b2c.png)
![image](https://user-images.githubusercontent.com/47158596/125903691-bf4a84ed-2401-4bb6-86e6-7955f4d2c47d.png)
well this is weird

**Comment by InsaneRed** [comment]
testing it as the same name gave some results but nothing else has done that 
![image](https://user-images.githubusercontent.com/47158596/125903728-69fca2c3-e557-4863-b96e-798cd78e157b.png)

**Comment by dragomagol** [comment]
> 
> 
> > Maybe try with a single name? I know it's happened with this name a fair few times, but not all the time.
> > Edit: just peeked at the logs for this round, it called me both "Moherilian" and "Mohimilian"
> 
> did you perhaps have a quirk or brain damage or just, whatever, that made you have difficulty recognizing names (they do exist iirc)
Nope! This is directly from the logs: https://tgstation13.org/parsed-logs/sybil/data/logs/2021/07/16/round-166031/game.html
![image](https://user-images.githubusercontent.com/66640614/125903901-42ae2a9a-6243-46e5-a737-b91beea9a728.png)

**Comment by ATH1909** [comment]
![image](https://user-images.githubusercontent.com/42606352/125907741-4e45a88c-9b9e-4ef9-8694-b0e3baa19432.png)
![image](https://user-images.githubusercontent.com/42606352/125907772-4dd602bb-d81e-4f20-b395-56222c046b21.png)
fuckup of the year candidate? this is pretty funny.

**Comment by Watermelon914** [comment]
lmao, I thought this was related to the carp pr I did
