### ISSUE TITLE
Slimes don't eat monkeys

### ISSUE THREAD

**Issue by SmArtKar** [tgstation/tgstation#60262]
## Round ID:

[166044](https://scrubby.melonmesa.com/round/166044)

## Testmerges:

#60240 #60190 #59629 #60187 

## Reproduction:

Try feeding slimes some monkeys. Find out that slimes don't want to eat. Xenobio is useless

**Comment by ATH1909** [comment]
uh oh

**Comment by AlinaStarkova** [comment]
can this be reproduced? i see xenobio breed slimes every shift. or does this only apply to some slimes and not all of them?

**Comment by SmArtKar** [comment]
> can this be reproduced? i see xenobio breed slimes every shift. or does this only apply to some slimes and not all of them?

This just happens time to time on live servers(never caught it on local), can't figure out whats causing it

**Comment by AlinaStarkova** [comment]
> 
> 
> > can this be reproduced? i see xenobio breed slimes every shift. or does this only apply to some slimes and not all of them?
> 
> This just happens time to time on live servers(never caught it on local), can't figure out whats causing it

if it only randomly happens i would assume its just the slimes not feeling hungry? slimes arent coded to eat 24/7 iirc, they technically do have a feeling of hunger and wont eat if they dont feel the need to eat, though they do appear to always want to eat nonstop

**Comment by interestingusernam3** [comment]
cannot reproduce
