### ISSUE TITLE
bottlers look like they're able to add chems to things that you're not supposed to be able to refill

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#60264]
https://github.com/tgstation/tgstation/blob/master/code/modules/plumbing/plumbers/bottler.dm

... provided that they're not medipens, of course.

This could probably be easily tested using a pill.

**Comment by timothymtorres** [comment]
https://github.com/tgstation/tgstation/blob/a7f77e024e738b19c09de58c108501005cbae570/code/modules/plumbing/plumbers/bottler.dm#L64-L68

I don't do chemistry or plumbing but this line looks like it's checking certain objects.  Can you think of any specific objects that shouldn't be refilled?
