### ISSUE TITLE
Universal Enzyme is not consumed in cheese reaction

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#60273]
## Round ID:
Reproduced on local

## Reproduction:
Add 5u enzyme to a bowl. 
Add 40u milk to a bowl. 
See cheese is created, but the bowl still has 5u enzyme.

**Comment by 1393F** [comment]
enzyme is a catalyst in the reaction, its not supposed to consume it

**Comment by Time-Green** [comment]
No idea if there's a 24 hour rule or something for issues, but enzymes arent supposed to be consumed as stated by @1393F  

I'll close this, but thank you for making an issue report 💪

**Comment by dragomagol** [comment]
Good to know! Thanks!
