### ISSUE TITLE
fireman carry is broken

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#60275]
Reporting client version: 514.1554

## Round ID:
[166088](https://scrubby.melonmesa.com/round/166088)

## Testmerges:
- [Job refactor: strings to references and typepaths](https://www.github.com/tgstation/tgstation/pull/59841)
- [fucking SEXTUPLES ALL TURF DECALS to test for if they affect maptick (like what i did before but more)](https://www.github.com/tgstation/tgstation/pull/60066)
- [Adds the bare minimum admin components and allows admins to define list literals.](https://www.github.com/tgstation/tgstation/pull/60240)

## Reproduction:
1. grab someone twice
2. drag them to you to try to fireman carry them
3. have the bar appear
4. have the bar complete, and the bar stay on the floor.

**Comment by Mooshimi** [comment]
Piggybacking as also broken. This is when someone aggressive grabs you and you drag yourself onto them. can only think these are connected. If they broke at the same time.

**Comment by InsaneRed** [comment]
theres a pr up for this

**Comment by dragomagol** [comment]
Will be closed by #60272
