### ISSUE TITLE
Prisoner & Syndicate EPBs unable to seal captives in

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#60282]
Reporting client version: 513.1542

## Round ID:
[166106](https://scrubby.melonmesa.com/round/166106)

## Testmerges:
- [Use rust-g to url_encode (and other builtin overrides)](https://www.github.com/tgstation/tgstation/pull/60190)
- [tgui test merge for profiling](https://www.github.com/tgstation/tgstation/pull/60187)

## Reproduction:
Prisoner & Syndicate Prisoner Transport EPBs are unable properly seal, unsealing themselves immediately after attempting to close them.

1. Procure a prisoner/syndicate EPB and deploy it.
2. Stuff something in or leave it empty.
3. Right click and wait to seal it.
4. Notice that it immediately unseals after finishing the windup.
5. Fail to transport/kidnap people.

Another bug that I noticed: If you are the one being strapped into a bag, chat messages make it seem like you are strapping yourself into the bag.

**Comment by AlinaStarkova** [comment]
@Greniza related to your code. maybe you know the fix

**Comment by Greniza** [comment]
> @Greniza related to your code. maybe you know the fix

thanks for pinging me, I never would've seen it otherwise.

**Comment by Greniza** [comment]
Alright, I've looked over my code again. The issue in question should be in `/obj/structure/closet/body_bag/environmental/prisoner/togglelock` (a proc). However, my best explanation for why it immediately clicked back open is that togglelock was called _twice_, which wouldn't make sense unless you right-clicked the bag twice, and even then I'm not certain it wouldn't be interrupted by the do_after check anyway. @Derpguy3, do you have any further information on this?

**Comment by Derpguy3** [comment]
@Greniza 
I've gone ahead and re-tested to make certain that I didn't double click the bags, and it produces the same result.
Besides the earlier stuff about it immediately uncinching after finishing the wind up and sealing, it seems to only seal proper if you put something too large to hold over it, cinch, and close it on something.

Besides this, I don't have any other info.

**Comment by Greniza** [comment]
> @Greniza
> I've gone ahead and re-tested to make certain that I didn't double click the bags, and it produces the same result.
> Besides the earlier stuff about it immediately uncinching after finishing the wind up and sealing, it seems to only seal proper if you put something too large to hold over it, cinch, and close it on something.
> 
> Besides this, I don't have any other info.

That's _very_ strange, given that, aside from messaging people inside the bag, it shouldn't... hmmm. @Derpguy3, we should talk over discord.

**Comment by Derpguy3** [comment]
@Greniza 
I'm available to chat at the moment, Feel free to message me on discord.

**Comment by Greniza** [comment]
> @Greniza
> I'm available to chat at the moment, Feel free to message me on discord.

what's your thing? I'm Greniza, with my same PFP, on the /tg/ discord.

**Comment by Derpguy3** [comment]
Derpguy #7937
