### ISSUE TITLE
Xenobiology biobags do not make proper use of signals

### ISSUE THREAD

**Issue by JustANormalHooman** [tgstation/tgstation#60309]
## Round ID: N/A, bug found on private test server
Server revision is as follows:
BYOND Version: 514.1557
Server revision compiled on: 2021-07-18
Master commit: 73bdfd312fdd2bb9b49ee3e2b7b40bbd9cea72fb

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1

## Reproduction:
Xenobiology biobags do not feed slime extracts directly, instead requiring the user to take a monkey cube out of the bag manually. I believe this is because the biobag definition within bags.dm does not have any proc to handle the signal from the reproductive extract, it only has the storage component with no proc. I would code it myself but I don't know how to handle signals in DM.

**Comment by interestingusernam3** [comment]
Reproduced on terry during round 166372, which had the following testmerges: #60327 #60190 #60285.

**Comment by AlinaStarkova** [comment]
will be fixed by #60345
