### ISSUE TITLE
making seeds out of plants with injected reagents does not keep injected reagents

### ISSUE THREAD

**Issue by tohg7** [tgstation/tgstation#60312]
Hello, i've noticed a possible bug relating to botany, seeds made out of plants that have injected reagents seem to not keep the reagents, i'm not sure if this is intentional or not, but i would appreciate it if you fixed this. I was testing some things on a private server in botany by injecting chems into a harvested plant and putting it in the seed extractor, before i put the death nettle in the seed extractor after injecting coniine into the death nettle, the coniine showed on a Right-click plant analyzer scan, once i put the death nettle into the seed extractor after i injected it with coniine, i scanned the seeds and noticed that they do not have coniine in them, i find this strange because seeds are supposed to keep injected reagents. Again, i would appreciate if you fixed this bug, thank you for your time.

**Comment by MrMelbert** [comment]
This is not a bug / intentional, you cannot give plants genes by injecting them with chemicals via syringe.
