### ISSUE TITLE
exosuit mounted sleeper duplication glitch

### ISSUE THREAD

**Issue by InvalidArgument3** [tgstation/tgstation#60343]
Reporting client version: 514.1557

## Round ID:
[166296](https://scrubby.melonmesa.com/round/166296)

## Testmerges:
- [[DNM] Makes everything sec and sec related blue to see what happens](https://www.github.com/tgstation/tgstation/pull/60315)
- [Fixes a runtime that would leave everyone naked](https://www.github.com/tgstation/tgstation/pull/60327)
- [Use rust-g to url_encode (and other builtin overrides)](https://www.github.com/tgstation/tgstation/pull/60190)
- [managed_overlays no longer stores as a list for singletons](https://www.github.com/tgstation/tgstation/pull/60320)

## Reproduction:

1. build odysseus, build exosuit mounted sleeper and syringe gun and equip odysseus
2. use syringe gun to analyze liquid electricity
3. pick up a monkey with the sleeper, inject with liquid electricity
4. when the monkey gets shocked it will fall out of the mech while still inside the sleeper, this duplicated sleeper can be picked up and added to others
5. the original mech's sleeper seems to bug out, become unusable, and cannot detach

**Comment by Sealed101** [comment]
patients no longer drop out of the sleeper when they are electrocuted or seemingly in general from what i've been able to test; so, could not reproduce
