### ISSUE TITLE
Stack of 0 iron sheets

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#60340]
Reporting client version: 514.1557

## Testmerges:
- [managed_overlays no longer stores as a list for singletons](https://www.github.com/tgstation/tgstation/pull/60320)
- [Use rust-g to url_encode (and other builtin overrides)](https://www.github.com/tgstation/tgstation/pull/60190)
- [Fixes a runtime that would leave everyone naked](https://www.github.com/tgstation/tgstation/pull/60327)
- [[DNM] Makes everything sec and sec related blue to see what happens](https://www.github.com/tgstation/tgstation/pull/60315)

I disassembled some tables and a chair in the chap`s office in kilo along with shuffling a few stacks of iron (I got confused as to why the stacks of iron in my pocket kept getting pulled into my hand) The end result was a leftover stack of iron that had 0 stacks to it, it could be picked up and examined and activated but there were zero sheets in the stack.

I`m not exactly sure which caused it, it might have been the chair that left behind the stack of 0 iron sheets, I also found another stack of 0 iron sheets in the middle of the hallway.

**Comment by NanoCats** [comment]
Damn, you shoulda tried to make a table or something with it, get negative iron, INT_OVERFLOW iron.

**Comment by moocowswag** [comment]
I also tried using it on an autolathe and it said it had insufficient materials.

**Comment by Sealed101** [comment]
this will pop up eventually maybe probably but not today
