### ISSUE TITLE
Wizards / Nukies get quirks when they shouldn't 

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#60354]
## Reproduction:

Wizards and nukies get their roundstart quirks on spawn when in the past all of their quirks were cleared.

**Comment by Sealed101** [comment]
paraplegic ops

**Comment by necromanceranne** [comment]
I wish it was a feature

**Comment by TemporalOroboros** [comment]
This should probably be a quirk in and of itself.

**Comment by NanoCats** [comment]
a while back I had nuke ops with bad aim when it was still fucked and made you completely blind, wheeee

**Comment by Sealed101** [comment]
this is actually real and i can now snap a photo of my static being deep undercover as a nuke op and put it in my family photo album please don't fix
