### ISSUE TITLE
Butchering carbons with reagents in their bloodstream doesn't put the reagents in the meat.

### ISSUE THREAD

**Issue by tohg7** [tgstation/tgstation#60352]
I've noticed that whenever you gib any carbon with reagents or chems in their bloodstream or stomach via butchering, the chems are not put into the meat when you butcher that carbon. I'm not sure if this is a bug or if this is intentional, but i think this might be a bug, i put penthrite in the monkey's bloodstream before butchering it. When i butchered the monkey with penthrite in it's system via combat knife, it didn't transfer reagents, but when i put the monkey in the gibber, it transfered the reagents.

**Comment by necromanceranne** [comment]
It's probably been broken ever since changes with how chems are processed happened.
