### ISSUE TITLE
Security newscaster in tramstation psychology

### ISSUE THREAD

**Issue by JohnFuckingMooney** [tgstation/tgstation#60376]
Reporting client version: 514.1557

## Round ID:
[166394](https://scrubby.melonmesa.com/round/166394)

## Testmerges:
- [Fixes a runtime that would leave everyone naked](https://www.github.com/tgstation/tgstation/pull/60327)
- [fucking SEXTUPLES ALL TURF DECALS to test for if they affect maptick (like what i did before but more)](https://www.github.com/tgstation/tgstation/pull/60066)

## Reproduction:
In the tramstation psychologist's office there is a newscaster that is marked as security rather than a normal one, this gives it access to printing wanted posters and such.

![image](https://user-images.githubusercontent.com/33187585/126577056-609a8265-64de-4aea-b44d-08be265f55e4.png)

**Comment by godspeedfunnyman** [comment]
It appears that EVERY newscaster is a security newscaster on tramstation

![image](https://user-images.githubusercontent.com/79808856/126606593-6588d661-b4f1-4b36-a187-9787502e8d40.png)
