### ISSUE TITLE
Wallets don't show IDs in order.

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#60378]
Reporting client version: 514.1557

## Round ID:
[166397](https://scrubby.melonmesa.com/round/166397)

## Testmerges:
- [tgui test merge for profiling](https://www.github.com/tgstation/tgstation/pull/60187)

**Comment by TemporalOroboros** [comment]
This is apparently intended to make it harder to hide useful ID cards.

**Comment by Mooshimi** [comment]
But if it's a physical wallet it shouldn't work that way??
