### ISSUE TITLE
Client crashes when you see a large canister

### ISSUE THREAD

**Issue by PsychoSon77** [tgstation/tgstation#60374]

**Comment by TemporalOroboros** [comment]
View as in open the UI or view as in enter the same room?

**Comment by PsychoSon77** [comment]
> 
> 
> View as in open the UI or view as in enter the same room?

Whenever you enter the same room, ghost or alive.. if at any point you see one, it just crashes. I assume it's the canisters, because I always crash upon entering toxins, atmospherics, the N20 in the brig, the cryo area, and the ancient station atmos.. any time they come on screen, it just crashes.

**Comment by PsychoSon77** [comment]
The oxygen canisters on the syndicate infiltrator don't cause the crash for some reason.

**Comment by ATH1909** [comment]
do you crash when you come back if the canister is still in the same room as you? this seems like a pretty big deal, especially for admins.

**Comment by PsychoSon77** [comment]
> 
> 
> do you crash when you come back if the canister is still in the same room as you? this seems like a pretty big deal, especially for admins.

The issue seems fixed with the new byond beta version. I haven't had a crash since.
To answer your question: Yes, you'd be stuck in a complete crash loop, unless your ghost was lucky enough to drift away from the canister when you come back.
