### ISSUE TITLE
hitting shit with flashlights or guns with flashlights attached creates a white sphere around it

### ISSUE THREAD

**Issue by bastardblasted** [tgstation/tgstation#60377]
## Reproduction:
1) hit something with a flashlight, a flashlight mounted egun or flashlight mounted PKA
2)obscure everything in a 3 by 3 tile square around the target with a white sphere
3) leTroll

![lightbug](https://user-images.githubusercontent.com/76170211/126583604-938609eb-a07e-4ac8-ac8a-1e8de6005efb.png)

**Comment by bastardblasted** [comment]
![lightbug](https://user-images.githubusercontent.com/76170211/126583551-ee60e68f-87a2-4e40-834f-0859c03a44e0.png)

**Comment by TemporalOroboros** [comment]
The attack image being used is including the emissive overlays. Both the light overlay and the emissive blocker from the looks of it.
