### ISSUE TITLE
Riding on tram as a paraplegic will cause you to be slammed by it.

### ISSUE THREAD

**Issue by notfrying1pans** [tgstation/tgstation#60375]
## Reproduction:
Be paraplegic. Go onto tram. Once done, you will fall off your wheelchair (this happened before), be hit by the tram, and then have face/eyewear fall through the tram itself.

**Comment by notfrying1pans** [comment]
Please note that you would just fall off your wheelchair, I have no idea when the rest of the things started.

**Comment by NanoCats** [comment]
Note: Seats on the tram are broken in general, if you are buckled to ANY seat you get jerked off it.
