### ISSUE TITLE
Engi Plasmaman spawns without plasma tank when the drunk spawning trait happens

### ISSUE THREAD

**Issue by SamDDBS** [tgstation/tgstation#60382]
## Round ID:
[166146](https://scrubby.melonmesa.com/round/166146)

## Testmerges:
#60187 

## Reproduction:
Spawn as engi plasmaman with drunk spawning trait or whatever its called
where everyone on the station spawns in the halls carrying beer and surrounded by beer
Pretty funny that you dont spawn with your plasma tank, but couldve called for an ahelp if i didnt know there was a spare in my box

**Comment by NanoCats** [comment]
I'd like to note that I've had the station trait event happen where everyone is manually added with the arrivals shuttle and I saw a plasma man drop his tank on the floor and I couldn't find him after that.

I think he didn't notice he dropped it?
