### ISSUE TITLE
Whiteship navigation computer can't move between Zs

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#60394]
Player reported. 

## Reproduction:
Previously, you could navigate across Z levels using the whiteship navigation computer by moving the target destination towards and past the Z level boundary. Now whiteships can only travel on Z levels where they have preset destinations. 

Potentially caused by #59326

**Comment by Y0SH1M4S73R** [comment]
I thought the point was that you needed to place gigabeacons on the z-levels you want to be able to travel to via shuttles.

**Comment by moocowswag** [comment]
Isnt the gigabeacon just for landing on lavaland?

**Comment by InsaneRed** [comment]
And im almost certain in the past the shuttle could move freely between most space z levels without use of a beacon.

this is correct its bugged recently you never neede dbeacons

**Comment by TheBonded** [comment]
@InsaneRed you always used to need beacons, only a few months ago they changed it to not need beacons, which may have been a bug in and of itself.

**Comment by timothymtorres** [comment]
![4F6513FB-70BF-4DAE-A1D1-3165DB087A14](https://user-images.githubusercontent.com/5195984/130353293-8a3f10ae-01e2-4bed-b3a5-f164d7c206f7.jpeg)


According to the maintainer this is intended.
