### ISSUE TITLE
Sleepy pens can't refill

### ISSUE THREAD

**Issue by blehpendea** [tgstation/tgstation#60402]

**Comment by TemporalOroboros** [comment]
You don't need a syringe. A beaker will do.

**Comment by blehpendea** [comment]
No it doesn't work with a beaker either.

**Comment by godspeedfunnyman** [comment]
It isn't used like a syringe, just use a beaker or a syringe to inject into it

AKA just click on the pen while holding a beaker or syringe

**Comment by blehpendea** [comment]
Thanks.
