### ISSUE TITLE
Carving isn't animated anymore

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#60418]
Reporting client version: 514.1557

## Round ID:
[166528](https://scrubby.melonmesa.com/round/166528)

## Testmerges:
- [tgui test merge for profiling](https://www.github.com/tgstation/tgstation/pull/60187)

## Reproduction:
Previously there was a slow reveal of the object you were carving, now it's just a block until you're finished.

**Comment by dragomagol** [comment]
I think this uses the same system as the bread smite, which also doesn't do the gradual change anymore.

**Comment by newfren** [comment]
this has also been happening to me

**Comment by timothymtorres** [comment]
This appears to have been fixed.
