### ISSUE TITLE
When using the To String component with the Voice Activator entity output and a radio, it'll not output the entity's name.

### ISSUE THREAD

**Issue by TheSmallBlue** [tgstation/tgstation#60426]
## Reproduction:
1. Grab any circuit shell with an integrated circuit inside it
2. Put in a Voice Activator component and a To String component
3. Talk near the shell to test it, then click on the To String output. You should see your own name. This is it working as intended.
4. Place the shell near a radio (Either a wall-mounted one or any one with the speaker activated)
5. Either wait for anyone to talk over comms, or go to a different room and talk over comms yourself
6. Click on the To String output. Instead of saying the entity name, it'll just say "entity"

https://user-images.githubusercontent.com/24967815/126881970-e948eacf-89ae-4500-9c29-436c35465226.mp4

**Comment by Mothblocks** [comment]
CC @Watermelon914, though this bug is known.

The problem is that they're "virtual speakers", I believe he already knows a potential workaround to it.

**Comment by Watermelon914** [comment]
Not necessarily a bug, it's because the entity output will output the speaking entity.
This means that voices from a radio will actually get the radio entity and not the guy speaking over radio.

**Comment by TheBonded** [comment]
is this still an issue? it seems to work for me in my testing now

**Comment by Watermelon914** [comment]
Yes, this still exists.

If you hear someone over the radio, the radio will be the entity who is speaking.

**Comment by TheBonded** [comment]
> Yes, this still exists.
> 
> If you hear someone over the radio, the radio will be the entity who is speaking.

try with a delay component between the voice and speech to give the to-string a second to process it? I don't know if that would work, but I swear I've seen @MrMelbert make a radio based "probability of survival" circuit that worked over the radio and said their name
