### ISSUE TITLE
RPD pipes with only one direction are invisible and unwrenchable

### ISSUE THREAD

**Issue by Aed0s** [tgstation/tgstation#60422]
Reporting client version: 514.1557

## Round ID:
[166546](https://scrubby.melonmesa.com/round/166546)

## Testmerges:
- [Use rust-g to url_encode (and other builtin overrides)](https://www.github.com/tgstation/tgstation/pull/60190)
- [[DNM] Make getFlatIcon more readable, and maybe faster?](https://www.github.com/tgstation/tgstation/pull/60285)

## Reproduction:
Using the RPD to create a pipe with only one direction allowed to connect creates an invisible pipe on the tile that cannot be unwrenched. Happens with all layers and pipe colors, as long as only one direction is selected. In the image below, all six floorless tiles have a pipe on them that can be examined but not interacted with.
![image](https://user-images.githubusercontent.com/66479044/126868422-99a17572-02ab-49b8-8239-7765e5cc2abf.png)

**Comment by AlinaStarkova** [comment]
did you mean to close this?
