### ISSUE TITLE
Light splotches stuck on screen

### ISSUE THREAD

**Issue by Watermelon914** [tgstation/tgstation#60438]
## Testmerges:

#60190: 'Use rust-g to url_encode (and other builtin overrides)' by Mothblocks at commit 9f430435ca
#60285: 'Make getFlatIcon more readable, and maybe faster?' by Mothblocks at commit db568c9b23

## Reproduction:

Lighting can sometimes bug out on my mob where I just see splotches of lights around me that follow me at an offset. No one else is able to see these splotches of light.

During the time it happened, I was wearing mesons and I had a flashlight on me. I had taken my clothes off, causing my flashlight to drop to the ground because I was on fire. This is around about the time it happened.
When I died and ghosted, the splotches of light were no longer there for me.

In this screenshot, you can see the splotches of light. No lights on me are currently active.
![image](https://user-images.githubusercontent.com/37270891/126896456-c92feb6a-2bbe-4a2f-8311-e7f0440b01c4.png)

**Comment by notfrying1pans** [comment]
When mining, this appears in a diagonal direction I'm facing when I turn on a flashlight/take out pka with seclight
