### ISSUE TITLE
donutstation whiteship breaks if you try to repair it

### ISSUE THREAD

**Issue by oilysnake** [tgstation/tgstation#60445]
## Round ID:

private server

## Reproduction:

https://github.com/tgstation/tgstation/pull/55262 the pacman added only accepts plasma sheets.. but uranium sheets were added.

the apc frame added is given a console board that doesn't work with it, it's the wrong board. placing the APC frame down drains all the power from the invisible apc and makes piloting the ship impossible unless you have a spare, REAL apc board

overall wtf lol

**Comment by newfren** [comment]
the reason the apc drain happens is it has magic shuttle power before you place the apc. agreed that it's mad annoying that there's an air alarm board instead of an apc board
