### ISSUE TITLE
Carving beepsky will cause weird artifacts to appear on the carving.

### ISSUE THREAD

**Issue by notfrying1pans** [tgstation/tgstation#60464]
## Round ID:
[166673](https://scrubby.melonmesa.com/round/166673)

## Testmerges:

#60066

## Reproduction:

I carved beepsky using snow spawned via the mutation and this happened. Also, most carvings are pitch black for some reason. Probably a GAGS related issue?
![image](https://user-images.githubusercontent.com/49667761/127038913-e69ff81c-c092-4342-87df-9233c0b19f51.png)

**Comment by TemporalOroboros** [comment]
It looks like the carving is including the emissive blockers and overlay lighting in the appearance.

**Comment by notfrying1pans** [comment]
> 
> 
> It looks like the carving is including the emissive blockers and overlay lighting in the appearance.

I carved *a lot* that round and this is the only time either of these things happened

**Comment by ATH1909** [comment]
who's that bot?

iiiiiiit's beepsky!

**Comment by timothymtorres** [comment]
![dreamseeker_qBjCV2Dlf7](https://user-images.githubusercontent.com/5195984/211920380-b03caa53-7c5c-4939-a4bd-d8423334d55f.png)

The black void on carving appears to have been fixed at some point.  Feel free to ping me to reopen this if you encounter it again.
