### ISSUE TITLE
You can do unspeakable things to cows

### ISSUE THREAD

**Issue by notfrying1pans** [tgstation/tgstation#60463]
## Round ID:
[166673](https://scrubby.melonmesa.com/round/166673)

## Testmerges:

#60066

## Reproduction: 
Sometimes cows get into a weird glitched state where their sprites become uncentered, walking into walls does.... this

https://user-images.githubusercontent.com/49667761/127038213-b25e8f4d-0ef8-4f13-a6e7-4b191e71321c.mp4

**Comment by Spookuni** [comment]
oh no

**Comment by notfrying1pans** [comment]
@Kylerace FUCK couldn't be more accurate.

**Comment by notfrying1pans** [comment]
Just a sidenote, this is what I mean by a properly centered cow. This image was taken 47 minutes before the video was, and the bug didn't happen while the cow was centered.
![image](https://user-images.githubusercontent.com/49667761/127082679-ef0c770b-7c3e-4e71-a0e0-4136ca5b48f5.png)

**Comment by rdragan** [comment]
It's a feature.

**Comment by interestingusernam3** [comment]
Slap slap slap

**Comment by notfrying1pans** [comment]
"needs reproducing" OH FUCK OFF LMAO

**Comment by notfrying1pans** [comment]
BTW the cow was killed and resurrected via lazarus injector, not sure if that effects anything

**Comment by IndieanaJones** [comment]
You can do this to cyborgs too if you hold your "don't move but turn around" button, while holding it and a movement key, your riding offset is removed, allowing for similar results.

**Comment by notfrying1pans** [comment]
> 
> 
> You can do this to cyborgs too if you hold your "don't move but turn around" button, while holding it and a movement key, your riding offset is removed, allowing for similar results.

oh no....

**Comment by notfrying1pans** [comment]
I FOUND OUT HOW TO DO THIS!
Grab the cow while riding it!

**Comment by notfrying1pans** [comment]
please remove the needs reproducing label i think mating season's over

**Comment by TheVekter** [comment]
Something something goat something edge of a cliff
