### ISSUE TITLE
Got assistant with it on no 

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#60499]
Reporting client version: 514.1561

## Round ID:
[166766](https://scrubby.melonmesa.com/round/166766)

## Testmerges:
- [Drugs of the 26th century. Three new hella rad drugs, one less lame drug and more!](https://www.github.com/tgstation/tgstation/pull/60432)
- [[s]Improve admin messages around players with the same ip or cid](https://www.github.com/tgstation/tgstation/pull/60488)

## Reproduction:
![cvx1JDX3zm](https://user-images.githubusercontent.com/37246588/127260087-93279a7d-d849-42e4-bb36-9a89c51ba636.png)

Previous round I set it to high with station trait. My avatar in settings was assistant despite being on no. I assume the preference from the previous round persisted, even though it shouldn't have.

**Comment by godspeedfunnyman** [comment]
Same as #60167

**Comment by Mothblocks** [comment]
Maybe related to job refactor, CC @Rohesie ?

**Comment by Rohesie** [comment]
> 
> 
> Maybe related to job refactor, CC @Rohesie ?

The refactor didn't touch on the job selection loop, though that's something I have planned for the future, as I don't like it forcing jobs such as the command ones when you have them in `MED` or `LOW` and you have different ones with `HIGH`.

**Comment by conk444** [comment]
This stuff just happens when you have nothing on high. You either get picked as a lawyer or an assistant if you have "random job" on and nothing set to high, because nobody wants to be a lawyer and there is no limit to how many assistants can exist per round.

**Comment by Rohesie** [comment]
This is probably not a new bug at all.

**Comment by AlinaStarkova** [comment]
you can technically still get assistant as that random job noted at the bottom even if you disabled it if the jobs you have selected are all taken. pure random chance as if your jobs you selected are taken it will select a random job with no weight iirc so your equally likely to get assistant as anything else. even if assistant is set to no

**Comment by TheBonded** [comment]
so random job should have something that prevents assistant from being chosen, then

**Comment by Mothblocks** [comment]
it already does

```dm
/datum/controller/subsystem/job/proc/GiveRandomJob(mob/dead/new_player/player)
	JobDebug("GRJ Giving random job, Player: [player]")
	. = FALSE
	for(var/datum/job/job as anything in shuffle(joinable_occupations))

		if(istype(job, GetJobType(overflow_role))) // We don't want to give him assistant, that's boring!
			continue
```

**Comment by Rohesie** [comment]
> 
> 
> it already does
> 
> ```dm
> /datum/controller/subsystem/job/proc/GiveRandomJob(mob/dead/new_player/player)
> 	JobDebug("GRJ Giving random job, Player: [player]")
> 	. = FALSE
> 	for(var/datum/job/job as anything in shuffle(joinable_occupations))
> 
> 		if(istype(job, GetJobType(overflow_role))) // We don't want to give him assistant, that's boring!
> 			continue
> ```

Hmm, shouldn't this be `if(istype(job, overflow_role))` ?
`overflow_role` is now a type path, there's no need to grab the singleton instance.
I guess this one is on me.
