### ISSUE TITLE
Radio Components do not make a signal on recieving.

### ISSUE THREAD

**Issue by CRITAWAKETS** [tgstation/tgstation#60495]
## Reproduction: ![https://i.imgur.com/MwgAMGy.png](https://i.imgur.com/MwgAMGy.png)
![https://i.imgur.com/MrdX5kl.png](https://i.imgur.com/MrdX5kl.png)

The Triggered on a radio component doesnt do anything. And no, using a different remote for recieving does not fix the bug.

**Comment by CRITAWAKETS** [comment]
update, it actually works if you use a signaller, but not being signalled by another circuit.

**Comment by Mothblocks** [comment]
CC @Watermelon914

**Comment by MrMelbert** [comment]
Weird, I've signaled a radio component on circuit with another circuit in order to send speech to an intercom and it'd usually output a signal and the speech, did it break?

**Comment by Watermelon914** [comment]
No, it should work perfectly fine.
Please also show your other circuit

**Comment by Watermelon914** [comment]
this isn't a bug lol, you're sending the signal and then immediately receiving it and then trying to say something after the circuit has already said something, even though there's a cooldown on saying things for circuits for a reason.

**Comment by Watermelon914** [comment]
![image](https://user-images.githubusercontent.com/37270891/127291308-cad4143d-99de-408f-b91f-657402cfae93.png)
![image](https://user-images.githubusercontent.com/37270891/127291333-15eb5ad2-ac10-4173-af7a-9dda83b9f494.png)
