### ISSUE TITLE
Munchies are completely unrealistic as of right now

### ISSUE THREAD

**Issue by conk444** [tgstation/tgstation#60510]
## Round ID:
166789

## Reproduction:
1. Smoke weed every day
2. Get the appetite for something good at the kitchen
3. Eat two full boxes of donk pockets in the span of around five minutes
4. Just barely become able to no longer experience the hunger from hell
5. Post it on GitHub screaming at the coders to fix the munchies

**Comment by Time-Green** [comment]
> I don't know how to write the round ID down but it's 166789

Check the first line of your issue, that’s where it goes, that way the bot knows where to link the round id

Not sure about what you experienced, but that doesn’t seem right. You did microwave them right?

**Comment by Yawet330** [comment]
> > I don't know how to write the round ID down but it's 166789
> 
> Check the first line of your issue, that’s where it goes, that way the bot knows where to link the round id
> 
> Not sure about what you experienced, but that doesn’t seem right. You did microwave them right? Edit: nvm microwaving just adds omnizine

Its the funny hunger chem being far too effective, you can still genocide moods and movement speeds with it.
