### ISSUE TITLE
grilles are electrified when there floor is tiled

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#60541]
grilles are electrified even when theres a tile on them, this isnt the intended function and they are only supposed to be electrified when theres no tile on them

**Comment by Serxule** [comment]
pretty sure this isnt a bug since this is how its always been

**Comment by PKPenguin321** [comment]
correct, not a bug

**Comment by jughu** [comment]
Its litteraly not supposed to be electrified when theres a tile under it im 500% sure i played this game since 2011 and it never worked like that

**Comment by 1393F** [comment]
> 
> 
> Its litteraly not supposed to be electrified when theres a tile under it im 500% sure i played this game since 2011 and it never worked like that

https://github.com/tgstation/tgstation/pull/44265 changed that

**Comment by jughu** [comment]
Thats kinda lame yo now you can set up an absolute death trap without even using any tools in the progress

**Comment by AlinaStarkova** [comment]
yes grilles arent supposed to be electrified when a tile is under it, its why we still map map windows without tiles under it, so we can place wires to electrify them. the tile is meant to act as a barrier between the wire and the grille.

this bug actually causes you to be electrified on your own grilles you build in the halls during nukies which is useless as nukies have insuls
