### ISSUE TITLE
Make circuit save/load avaible for mortals.

### ISSUE THREAD

**Issue by Archemagus** [tgstation/tgstation#60542]
Yeah i know, forum. But c'mon, that's not so hard.

**Comment by Mothblocks** [comment]
FUUUUUCK no

**Comment by Gurkenglas** [comment]
you could write a pr so they can close it. you could restrict the datatype whitelist for mortal save/load of modules to numbers and signals. and make it work via a vendor in the library that only the curator can add to. and in every round where your module is bought, if a ghost rages about the module, its price increases permanently.

**Comment by Mothblocks** [comment]
![image](https://user-images.githubusercontent.com/35135081/127555624-131d22e1-b7d5-4b75-a177-c49161d6d37c.png)

**Comment by Mothblocks** [comment]
it will not exist in any player accessible form, ever

**Comment by Gurkenglas** [comment]
module jsons have advantages and disadvantages. you can get some of the advantages with fewer of the disadvantages.

**Comment by Mothblocks** [comment]
no

**Comment by Mothblocks** [comment]
it will never happen as long as i live
