### ISSUE TITLE
ash drake shapeshifting does not convert health when transforming back

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#60567]
#41638

**Comment by SmArtKar** [comment]
Intended

**Comment by jughu** [comment]
I don't see why miners should get any special treatment.
Wizards got this change because the few mob they could select were super strong, and they could just keep transforming forth and back for a full health bar.
Why should miners get a special treatment?

**Comment by Serxule** [comment]
> Why should miners get a special treatment?

probably because they went through the work of killing a megafauna for it, while wizards are just buying it from their spell catalogue

**Comment by jughu** [comment]
gee they followed a megaman battle pattern taking megafauna litteraly takes no skill

**Comment by jughu** [comment]
wizard has mobs thats litteraly two shot and then its still converted meanwhile miners have 300 different tools with the shapeshift

**Comment by Serxule** [comment]
> wizard has mobs thats litteraly two shot and then its still converted meanwhile miners have 300 different tools with the shapeshift

miners arent an antag unlike a wizard, while miners _can_ be an antag, the job is not based on being an antag

**Comment by jughu** [comment]
yes but shapeshift should still be balanced around you and not be a literal second healthbar

**Comment by bastardblasted** [comment]
there's a long cooldown in between form shifts, and dragon form is big and slow as fuck while also being squishy. you'll get gunned down by literally one laser guns before you can switch back if you're using it recklessly.

**Comment by jughu** [comment]
doesn't matter wizard plays super fragile mobs too which are even weaker then the ash drake, miner powercrepe needs to die besides if you get 0'd on your healthpool you deserve the dead then poofing back to 100% health with your epic miner loot available at hand like epic jaunt hiero staff and epic lava staff n shit

**Comment by Serxule** [comment]
don't mean to be rude but it _really_ just sounds like skill issue

**Comment by jughu** [comment]
its unconsisty between shapeshifting many of the antags dont have a real way to truely combat a ash drake, so if a traitor manages to get the drake low the miner just reverts back to miner to have a 100% HP bar and with whatever gear they have on person its kinda lame, and shapeshifting is supposed to convert health to balance this
