### ISSUE TITLE
Bananium tile functionality.

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#60573]
Look, I'm not sure if this is a bug, or an oversight, or an intended functionality, if a coder sees this and it's working as intended, just close it, but this is something important to me that I feel could stand to be rectified.

Long ago, we had only bananium tiles, before the introduction of the generic "material floor tiles" we see today that can be made from almost any material (the wood ones are fucking hideous btw)

These bananium tiles honk when walked on

Later, we were graced with "[Material] floor tiles", Materia floor tiles would squeak and SLIP anyone who walked on them, these were a blessing from the clown gods on the rare chance that a clown actually meets bananium. I would consider this an ideal state of affairs as you can choose  Honk + no slip or Squeak + slip.

At some point, I don't know when exactly, the function of these tiles changed and I do not know when or why.

Now both kinds of tiles slip, and this is a problem, "But you're a clown, you love slipping people, how is this a problem?"

Why I'll tell you, I'm not a _shitter_ clown, and sometimes I want to use them as non-slippery decor, but now they're going to get torn up because clown-slip-lynch-he no matter where I put them.

Please fix my fun, exceedingly rare floor tiles :(

**Comment by Ghommie** [comment]
Well, you make a fine point. Normal bananium tiles slipping people is the byproduct of material datums feature, like iron making iron chairs and iron tables (the latter got fixed). It's cool but also annoying.
