### ISSUE TITLE
Janicart is busted

### ISSUE THREAD

**Issue by CourageTheCat** [tgstation/tgstation#60577]
Reporting client version: 514.1557

## Round ID:
[166934](https://scrubby.melonmesa.com/round/166934)

## Reproduction:

1. try to get on janicart by dragging sprite to it with key in.
2. It doesn't do anything.

**Comment by AlinaStarkova** [comment]
according to other users, all ridables are busted atm, cant ride ATVs nor scooters nor skateboards or the security mobile thingy, forget what its called

**Comment by AlinaStarkova** [comment]
oh also this is a duplicate of #60547 @dragomagol (your the only issuejani i know kek)
