### ISSUE TITLE
Space beer bottles can't be smashed on heads

### ISSUE THREAD

**Issue by tohg7** [tgstation/tgstation#60594]
When testing if space beer can be smashed on my own head, i noticed that it wasn't counted as a glass bottle, when as before a certain update, it counted as a glass bottle and thus could be smashed on heads.

**Comment by Mothblocks** [comment]
did you right click

**Comment by Serxule** [comment]
> did you right click

no i've always had this issue long before combat update, it always just tries and makes people drink it, not smash it

**Comment by jughu** [comment]
Can only smash with the big bottles

**Comment by Ghommie** [comment]
This is because beer and ale bottles are not a subtype of `/obj/item/reagent_containers/food/drinks/bottle`
