### ISSUE TITLE
Corpses that are dismembered and become "Unknown" still have their old name shown when you hold shift

### ISSUE THREAD

**Issue by tralezab** [tgstation/tgstation#60617]
## Round ID: 
#166997

## Testmerges:

The following pull requests are currently test merged:
#60432: 'Drugs of the 26th century. Three new hella rad drugs, one less lame drug and more!' by Krysonism at commit dd61a63621
#60569: 'Adds a button that lets you see the name of any visible mob on your screen.' by AMonkeyThatCodes at commit 4ad8bb7448

## Reproduction:

Hold shift. It says "Mothblocks" as your name.
Get your head dismembered, examine the body. It says "Unknown"
Hold shift. Your body still shows to you and others as "Mothblocks

**Comment by Mothblocks** [comment]
when you hold shit

**Comment by tralezab** [comment]
what do you mean??

**Comment by Mothblocks** [comment]
Test merge was closed.
