### ISSUE TITLE
Simplemobs are capable of moving anchored AI cores

### ISSUE THREAD

**Issue by interestingusernam3** [tgstation/tgstation#60638]
## Round ID:
[166979](https://scrubby.melonmesa.com/round/166979)

## Testmerges:
none

## Reproduction:
1(?). Scoop up Renault
2(?). Place Renault
3. Build an AI core
4. Wait unthil Renault swaps places with it

**Comment by Serxule** [comment]
this is a problem with all simplemobs fyi

**Comment by SuperNovaa41** [comment]
I agree
