### ISSUE TITLE
Reinforced walls don't merge together

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#60630]
Round ID: [167017](https://scrubby.melonmesa.com/round/167017)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 8861b6fa250d69566dbba5723b4b2debc1fb0548
The following pull requests are currently test merged:
#60611: 'Disable ALL slips until they are fixed AND admin tool shortcomings get resolved.' by MrStonedOne at commit 6a3fc716ad

https://puu.sh/I0GdX/120f8019f7.png

**Comment by newfren** [comment]
https://puu.sh/I0GvZ/6f9d6f7844.png

all the walls are doing this woops

**Comment by Fikou** [comment]
i explain this in greater depth in #60652
