### ISSUE TITLE
Revivable Med HUD Status icon missing

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#60648]
Reporting client version: 513.1542

## Round ID:
[167058](https://scrubby.melonmesa.com/round/167058)

## Testmerges:
- [Disable ALL slips until they are fixed AND admin tool shortcomings get resolved.](https://www.github.com/tgstation/tgstation/pull/60611)

## Reproduction:
1. Wear Medical HUDs.
2. Kill something/somebody that can be revived.
3. Revivable HUD icon is missing.

**Comment by Mothblocks** [comment]
i wonder if i accidentally removed it with the nanites pr

**Comment by Mothblocks** [comment]
yep lol

![image](https://user-images.githubusercontent.com/35135081/127792531-02db54c5-bb8b-4a34-86be-62144538c702.png)
