### ISSUE TITLE
Borgs can interact with pipes through cameras

### ISSUE THREAD

**Issue by JohnFulpWillard** [tgstation/tgstation#60643]
## Reproduction:

1) Be a Borg
2) Use a camera console
3) Use Ctrl/Alt to interact with pipes
Works for Nukie borgs too.

https://cdn.discordapp.com/attachments/279359975250198528/871469823870263396/busteromoment.mp4

People are trying to get it fixed now but I want to make the issue anyways in case it doesn't work out, and just for documentation.

**Comment by InsaneRed** [comment]
isnt this intended?

**Comment by JohnFulpWillard** [comment]
> 
> 
> isnt this intended?

Potato said it isnt, it should act the same as doors, which doesnt allow for it.
