### ISSUE TITLE
You can toggle the rad collector lock whether or not you have access or the rad collectors say that you don't have access even if you do. It's one of the two and I'm not sure which but I have a hunch that it's the former. 

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#60645]
## Reproduction:
1. Be a paramedic (possibly on skeleton crew).
2. Approach one of the rad collectors installed around the meta SME.
3. Insert a plasma tank into the rad collector and turn it on.
4. Use your ID card on a rad collector.
5. Be informed that you both do not have the access necessary to lock/unlock the rad collector and that the rad collectors lock has been toggled.
6. Attempt to turn the rad collector off and be informed that it is locked.

Given that I was incapable of locking the emitters I belive that the rad collectors are simply ignoring the access check. This is probably just a case of a missing early return.

**Comment by AlinaStarkova** [comment]
that name tho
