### ISSUE TITLE
rust component sucks (rwalls not merging)

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#60652]
the rust component completely broke rwall smoothing with this
```
/turf/closed/wall/r_wall/rust
    //SDMM supports colors, this is simply for easier mapping
    //and should be removed on initialize
    color = COLOR_ORANGE_BROWN

/turf/closed/wall/r_wall/Initialize(mapload)
    . = ..()
    color = null

/turf/closed/wall/r_wall/ComponentInitialize()
    . = ..()
    AddElement(/datum/element/rust)
```

so every r wall is a rusted r wall
but this means that every rusted r wall, or everything with rust element, doesnt smooth correctly
also actual rusted walls, literally just dont show up, the rust sprite doesnt show up on them, they are just unsmoothed walls

also #60576

**Comment by interestingusernam3** [comment]
pain
