### ISSUE TITLE
You can cut beef wellington slices to make more slices infinitely.

### ISSUE THREAD

**Issue by Gristlebee** [tgstation/tgstation#60655]
Reporting client version: 514.1556

## Round ID:
[167070](https://scrubby.melonmesa.com/round/167070)

## Testmerges:
- [Disable ALL slips until they are fixed AND admin tool shortcomings get resolved.](https://www.github.com/tgstation/tgstation/pull/60611)

## Reproduction:
1. Make beef wellington
2. Cut it into slices.
3. Cut the slices, and make even more slices
4. Keep cutting your infinite slices and scoff at the conservation of mass.

**Comment by TemporalOroboros** [comment]
![image](https://user-images.githubusercontent.com/53582584/127826338-8f73e2f1-1754-4a90-b1a0-f69ef39566a3.png)
