### ISSUE TITLE
Cannons are broken

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#60666]
## Round ID:
[167066](https://scrubby.melonmesa.com/round/167066)

## Testmerges:

#60611

## Reproduction:

Get a regular or trash cannon, load it with ammo, try to fuel it with gunpowder or welding fuel. 
It'll say it's been loaded at first, but trying to fire it brings up a warning that it needs 15u of charge.
Try to fuel it, says that it's full.
Not able to fire it because of it.

The cannon load procedure is ammo > gunpowder or weld. fuel > fire from an item (lighter, torch, welding torch).

**Comment by Time-Green** [comment]
@tralezab think this one is for you
