### ISSUE TITLE
Corgi of the North Star

### ISSUE THREAD

**Issue by Blevruz** [tgstation/tgstation#60672]
## Testmerges:

"The following pull requests are currently test merged:
#60432: 'Drugs of the 26th century. Three new hella rad drugs, one less lame drug and more!' by Krysonism at commit dd61a63621
#60611: 'Disable ALL slips until they are fixed AND admin tool shortcomings get resolved.' by MrStonedOne at commit 6a3fc716ad"

## Reproduction:

Step 1: Tame corgi by petting
Step 2: Say "Attack"
Step 3: Point at something near the corgi that it can attack (i.e. tables or mobs, not walls)

You should observe your corgi devour its target in a matter of seconds.
Bonus points if you're using the void corgi in the petting zoo of Metastation, which lets you channel the energy of another anime classic.

**Comment by Mothblocks** [comment]
fixed by https://github.com/tgstation/tgstation/pull/60579

**Comment by maxymax13** [comment]
why close it if it's not merged yet 🤨

**Comment by Mothblocks** [comment]
it will be
