### ISSUE TITLE
tgchat and tgui are extremely laggy on byond 514

### ISSUE THREAD

**Issue by JenqaDev** [tgstation/tgstation#60681]
likely to be a BYOND issue

## Reproduction:

Step 1: install byond 514, any of the most recent versions work, but 1561 is the worst one even though it fixes all the random crashes and makes the camera movement way smoother

Step 2: have a below average computer

Step 3: gargle as anything from opening tgui windows to interact or SCROLLING tgchat is extremely slow and unstable (seeming like input lag).
examples of this are when there's the space dragon event and you try to press the carp rift to get to be a carp, which by the time the popup appears on your screen (to help that, the buttons only appear after the window's contents), someone has claimed it already. i bypass this by spam clicking it, because yes, i almost have to spam click stuff every time to interact (514 only), and have the popup loaded and waiting for the next spawn opportunity so that i can spam click the yes button right ahead.
another example is literally any midround injection popup that asks if i want to play thing X, i hear the sound but it takes several seconds for it to appear, and only then the buttons appear, which pressing wont do shit until i spam them

by the way, this also worsens #54692

i obviously regressed and use byond 513 since, besides movement being a little stuttery for me, everything else works fine. but i don't know how much longer i can be on it since soon the servers will refuse 513 connections because of the client-side particles. with this i'm afraid that until this issue is improved/fixed, i won't be able to play here at all

**Comment by Watermelon914** [comment]
1556 is the most stable I think

**Comment by JenqaDev** [comment]
> Step 1: install byond 514, any of the most recent versions work, but 1561 is the worst one

my bad, perhaps i didnt word it properly, but 1556 is part of the updates with extreme input lag also for garbage pcs like mine. i mean it's not full garbage this handles skyrim LE fairly well but you get it

**Comment by JenqaDev** [comment]
nonetheless the issue remains for low end machines on UI specially

**Comment by SuperNovaa41** [comment]
Safe to say this is probably not an issue, we're past that version anyways
