### ISSUE TITLE
Unlimited Pizza Works

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#60682]
Be me

cargo tech

watch my QM order pizza

QM removes pizza from box

QM removes pizza from box

QM removes pizza from box

(This goes on for some time)

station now has unlimited pizza 

station is consumed by n̶u̶k̶i̶e̶s̶  an unstoppable pizza flood (Dramatization)

This occurred on round ID: 167124 and I'm not sure how to do it exactly.

**Comment by ArcaneMusic** [comment]
Not a bug.
There is a rare, random spawn from the pizza crate that can potentially have an infinity quantity of pizzas come from it.
