### ISSUE TITLE
Dead broodmother spiders can still give directives

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#60699]
Reporting client version: 514.1557

## Round ID:
[167189](https://scrubby.melonmesa.com/round/167189)

## Testmerges:
- [Disable ALL slips until they are fixed AND admin tool shortcomings get resolved.](https://www.github.com/tgstation/tgstation/pull/60611)

## Reproduction:
(And potentially wrap bodies from beyond the grave, as the button wasn't grayed out)

**Comment by Fikou** [comment]
@IndieanaJones

**Comment by dragomagol** [comment]
Worth noting as well that a nurse spider was able to heal me, so I was both 100% healthy and also dead.
