### ISSUE TITLE
MMI-piloted mechs cannot be given access.

### ISSUE THREAD

**Issue by tohg7** [tgstation/tgstation#60692]
Recently, when i tried out MMI Ripley MK1 again, i had the roboticist change my access via id upload panel. When it was changed, despite me having science keycodes, i couldn't access any doors. so i had to drill my way through the station, i would appreciate if you fixed this so i wouldn't have to be forced to drill through the station to get to places of interest i don't have access to, like Cargo and Mining.

**Comment by timothymtorres** [comment]
The new ID system probably broke this.

**Comment by TheBonded** [comment]
afaik the 'giving access' to mechs isn't actually putting access on the mech, it just makes the mech require that access to be entered. I do have a memory far in my mind that makes me thing you used to be able to give mechs access, but I might be misremembering or thinking of a feature from another tg based server

**Comment by Sealed101** [comment]
fixed in #69556
