### ISSUE TITLE
Icebox service issues

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#60700]
- This APC is a ghost looking at it from above for some reason (multiz issue?)
![image](https://user-images.githubusercontent.com/51863163/128121796-3704291f-0a62-483a-841c-aeeab69bdec5.png)
- This fire alarm is also a ghost looking at it from above for some reason (multiz issue?)
![image](https://user-images.githubusercontent.com/51863163/128121840-17978acf-8add-4ef2-990c-3aae7f338c60.png)
- This door is titled incorrectly
![image](https://user-images.githubusercontent.com/51863163/128122056-4b2b4658-9974-4c2e-9d6b-b04f42dad230.png)
- Botany's apiary starts spawning bees without putting any queen bee inside, and hydroponics no longer spawns with a bee-keeping suit so you can't really stop them. In the past, the apiary was empty, and the queen bee was set aside in a separate crate so you can start them if you wanted 
![image](https://user-images.githubusercontent.com/51863163/128122183-7c186d53-fc62-4616-94f4-28b6b9b4fb6b.png)
- Botany lost a few buckets from the old botany (1, from 3)
- Disposals in the bar / hydroponics / service hall area don't work correctly, just dumps into the bar / 
- Disposals loop
![image](https://user-images.githubusercontent.com/51863163/128123915-168acb64-3e5d-470a-95bc-6146050a3d43.png)

**Comment by Zytolg** [comment]
-I'll look into disposals tomorrow
-I've a fix up for Botany Now, as well as some other misc mapping things I spotted.
-I've not a clue about the ghosting of the APCs and other mounts. I'd keep this issue open for those since that's not (or shouldn't be) a mapping issue.

**Comment by necromanceranne** [comment]
My recklessness got me caught in that loop, so you're welcome.

![unnamed](https://user-images.githubusercontent.com/40847847/128132440-1fe64112-aa79-4c30-a9ee-f9baa58933db.png)
