### ISSUE TITLE
possessed blades cannot awaken a spirit

### ISSUE THREAD

**Issue by JohnFulpWillard** [tgstation/tgstation#60712]
## Round ID: Tested locally on TG master

[Round ID]: # 

## Reproduction:

1) Take a possessed blade
2) Use it in hand
3) Notice it doesn't work at all

I've been trying to get this to work and it just doesn't, it started from I assume #60614 

Giving this component to any item (except the possessed blade) works, it only doesn't work specifically on the possessed blade (from my testing), and I don't know why.
I've even tried removing the component from the blade and giving it via VV, and that hasn't worked either.

From what I see, the posessed blade registers the signals, but using in hand, and only using in hand, is the only thing that doesn't work. If you try to use it in hand, it does literally nothing. Examining it does work however.

**Comment by 81Denton** [comment]
@tralezab wowww

**Comment by tralezab** [comment]
keep this open
ia have itpo ofiixi tit
