### ISSUE TITLE
facehugger spriting artifact when held

### ISSUE THREAD

**Issue by AlinaStarkova** [tgstation/tgstation#60714]
## Reproduction:
if you hold a facehugger, and face either south, or east, you see artifacts from the sprite, my best guess is your seeing where you would see things if you had the big queen sprite shown, however this should hide for you as well if you also make yourself small on your end

https://user-images.githubusercontent.com/40489693/128310917-71f394b2-586d-460b-8ac6-26d89f320e2c.mp4

**Comment by Sealed101** [comment]
small sprites for big mobs are obsolete as of https://github.com/tgstation/tgstation/pull/77361 and thus this issue can't really pop up outside of admemery question mark?
