### ISSUE TITLE
Rev Redesign/removal with another gamemode to replace it like nations

### ISSUE THREAD

**Issue by Shellton123** [tgstation/tgstation#60723]
I think revs is a poorly designed gamemode (Especially at high pops) for multiple reasons. But if this is too long I would sum it up like this. Revs are more likely to win due to the fact get jump on team heads and they can scale up a lot faster than them as well due to just one head rev going around flashing all of medbay in 5mins as opposed to team head that need to A: Find out it is revs before they start converting B: Mindshields cost money which makes them a lot more limited than a simple flash or 2 and C: They need to find out its revs before revs convert too many people which revs can do a lot easier as the pop goes higher. It is also a problem that the last head only option is to go into hiding as they can't killed the whole crew by themselves. I oppose solutions to most of these problems but I also think replacing it with nations for a bit may be a good idea as well.

1. Your the last one complete the mission - When you are the last head standing your only option is to hide in maints to even have a chance especially at high pops as you can't 1v70 the crew and this just leads to people getting bored and waiting till next round if the head is good at hiding. Admins know this as sometimes they Intervene when this is the case by putting gps trackers on the head in question. 

Solation: Give the final head standing a buff that makes them a GOD. If I was doing this I would give them immunity to all stuns inless its magical based (cult stun, heretic stun, arcane missles etc.) 10-15% damage resistant since they are the last man standing  and the ability to fight even in crit. It might be best to scale the damage resis up based on the pop. But in return the head will have a big glowy aura that says "HEY KILL ME ASSHOLES" and the revs. I would even maybe have a pod drop in containing a random robust level melee weapon and an energy gun at their location once the next last head dies. 

2. Whos friend or Foe - Revs have a lot clearer time seeing who is a friend or foe as its based on who has a big R on their head and if you want you can even put on sec huds to see whos mindshielded or not. Heads on the otherhand only have the abitity to see whos mindshielded using sec huds and if you cant get some sec huds especially as a head your own option is to risk getting a sec hud implant from roboticts which may or may not be reved yet. As well it is possible using a gas mask or a space suit and a heads id to pretend to be a head and trick people into thinking you are on their side when you aren't because most heads dont start mindshielded for some weird reason and sec doesnt mindshield them because they cant be reved anyways.

Solation: Make heads start mindshielded. This means they cant be turned into cult I know and might make it so they cant be antags altogether but sec shouldn't have to waste mindshield which are limited in supply for reasons I go into later. (I say might because all the mindshielded roles dont have antag options) As a player you could ask roboticts to make sec hud implants then implant people at sec but this make cause a large backlog of people waiting for huds while revs reach far beyond crit mass and wipe out sec.

3. REVS CONFIRMED TAKE OVER CARGO - Theres a reason why sec takes over cargo first. Its their only way to convert people while revs only limitations is that they need a flash, the person must not be mindshielded or have sunglasses on and they must be a head rev. But my main problem with mindshields is that they cost money. How does cargo get money, through bounties and donations. Who does the bounties and gives donations the crew. Heads can give money to cargo and they can do bounties but the problem with that is they may be left a lone and easy prey for the angry mob of people. As well this means every sec officer that gets killed is less gear you have as to kill revs as 1 person having a gun does not equal to the man power of 3 other crew mates. This just means you always dump your money into mindshields with no thought into other options because they aren't any. As well revs scale a lot faster than heads due to mindshields costing money and time. One head rev can just run around medbay flashing all the crew at round start and boom most of the time they will already have more people that is reved than sec does to help as heads only start converting once revs are confirmed and it may already be too late. 

Solation: I don't have one sadly this just how the game mode is. Although maybe once 5 mindshield crates are ordered the captain can request that centcom start mindshielding new recruits before they arrive which would help but the number of crates ordered must cost enough for cargo to only do this once revs are confirmed or every shift people will just order x number of crates even if it isn't revs. 

4. Fun over time to go home - Nearly after every rev shift once a side has won the shuttle is always already there or the shuttle is going to be called because rev shifts just take over the round and make it a bloodbath and at the end you either don't have the heads/sec to operate anymore or if heads win there are too many crew members dead to operate anymore. 

Solation: Just make the round end once a side wins. But if you are going to do this make it so other antags do not spawn during rev shifts to avoid someones antag round to be ruined/taken over by revs.

I think replacing revs with nations is a good idea because nations solve a lot of problems rev rounds have and I think it gives people the ability to see what they can do as an antag more often. Although I may be wrong on this just due to the fact I dont play nations enough and if I was going to put nations in I would make it so 30mins in the shuttle arrives regardless of if someone calls it or not. This may cause everyone to fight to get on the shuttle in a king of the hill style with the department with the most staff on it wins. People on pods wouldn't count.

**Comment by dragomagol** [comment]
This isn't really the place for something like this; you should take it to https://tgstation13.org/phpBB/viewforum.php?f=47 or make something like a hackMD.
