### ISSUE TITLE
Regular gloves can replace translator gloves for some reason

### ISSUE THREAD

**Issue by KittyNoodle** [tgstation/tgstation#60727]
Reporting client version: 514.1561

## Round ID:
[167301](https://scrubby.melonmesa.com/round/167301)

## Testmerges:
- [Disable ALL slips until they are fixed AND admin tool shortcomings get resolved.](https://www.github.com/tgstation/tgstation/pull/60611)
- [Fixes circuit component options](https://www.github.com/tgstation/tgstation/pull/60718)

## Reproduction:

Pick the tongue tied trait and take off your gloves, then put on any other gloves, notice you can sign perfectly.

**Comment by SmArtKar** [comment]
Intended, translator gloves are only required to speak in radio channels

**Comment by Time-Green** [comment]
> Intended, translator gloves are only required to speak in radio channels

Like he said, this isn't a bug. Still glad that you reported it, better to not take any chances. Will close in 24 hours (i will forget but im sure someone else wont)

**Comment by KittyNoodle** [comment]
Also perfect signing also happens randomly without gloves too

**Comment by Time-Green** [comment]
Signing is completely seperate from wearing gloves. It's like actual signing. The translator gloves just let you talk on radio

Also yeah it might seem confusing but literally everyone can understand sign language but it was added like that so w/e

**Comment by Couls** [comment]
> Like he said, this isn't a bug. Still glad that you reported it, better to not take any chances. Will close in 24 hours (i will forget but im sure someone else wont)

I got you
