### ISSUE TITLE
build.bat in tools\build double clicking does not keep command prompt open

### ISSUE THREAD

**Issue by BurgerLUA** [tgstation/tgstation#60729]
Not a DM bug so if you're confused that's why.

The readme says that double clicking the .bat file will keep it open. It does not. A workaround is just launching command prompt and just changing the directory like an adult and running the bat through there.

**Comment by ProfessorSniff** [comment]
this looks like it's intended, the readme says that only the batch file in the root directory is supposed to remain open.
>- Windows:
  a) Double-click `BUILD.bat` in the repository root to build (will wait for a key press before it closes).
  b) Double-click `tools/build/build.bat` to build (will exit as soon as it finishes building).

this is probably so the file can be used in automation. to be fair the readme probably needs its formatting fixed.

**Comment by BurgerLUA** [comment]
your mum lol
