### ISSUE TITLE
Security Officers assigned to Science are not always given appropriate permissions

### ISSUE THREAD

**Issue by QuantumSeanyGlass** [tgstation/tgstation#60731]
## Reproduction:
Spawn on Selene Station (or others, needs additional testing) as Security, get assigned to science, attempt to enter science, or leave if you spawned there. Access to the main corridors and protolathe seems ideal, but if these permissions are intended behaviour, than the sec office spawn locations need to be disabled, as it's impossible to leave without help.

**Comment by dragomagol** [comment]
I'm not sure what server you're from, but we don't have a Selene Station on /tg/.

**Comment by QuantumSeanyGlass** [comment]
I'm on fulpstation which I thought was 100% a pull of /tg/. I have also had this issue on /tg/, but I would be happy to close this and reopen when I can figure out why it happened.

**Comment by dragomagol** [comment]
Ah yeah, Fulp has some maps we don't have. If you figure out which of our maps have this issue feel free make a new one 👍

**Comment by QuantumSeanyGlass** [comment]
Aight, closing, expecting to reopen soon.
