### ISSUE TITLE
New players always spawn facing right

### ISSUE THREAD

**Issue by notfrying1pans** [tgstation/tgstation#60742]
## Round ID:
Doesn't matter, has been happening for the past few days.

## Reproduction:

Join the game. face right.

**Comment by rasepretep** [comment]
Probably related to this: if you drag your sprite onto an adjacent chair to buckle to it, your sprite will be facing whichever way it was moved towards, not whichever way the chair is facing.

**Comment by Mooshimi** [comment]
#60816 fixed this
