### ISSUE TITLE
Borg *spin while buckled does not launch target in direction facing

### ISSUE THREAD

**Issue by Reco201** [tgstation/tgstation#60741]
## Round ID:
Found on downstream

## Testmerges:
N/A

## Reproduction:
Become borg
Buckle human to self
Face direction of launching
*spin
Target goes the wrong way

**Comment by dragomagol** [comment]
Which way do they go? Is it consistent or random?

**Comment by timothymtorres** [comment]
This seems intended.

https://github.com/tgstation/tgstation/blob/b435a17da3993895b57324cbe84c2626770009d0/code/datums/components/riding/riding_mob.dm#L101-L129
