### ISSUE TITLE
Player controlled simplemobs attacking objects is unlogged

### ISSUE THREAD

**Issue by NamelessFairy** [tgstation/tgstation#60759]
## Testmerges:
#60678: 'Refactors connect_loc_behalf into a component' by Watermelon914 at commit 064fa82c70
#60611: 'Disable ALL slips until they are fixed AND admin tool shortcomings get resolved.' by MrStonedOne at commit 6a3fc716ad
#60718: 'Fixes circuit component options' by Watermelon914 at commit 1f09ff72f8

## Reproduction:

Simplemobs attacking objects, in this example a goat spawned in thunderdome attacking a directional window have no logs of doing so in the attack logs, airlocks and regular windows are also effected by this and I suspect all objects.

**Comment by Mothblocks** [comment]
#63272 is the same thing except he wrote more words
