### ISSUE TITLE
Cyborgs can sometimes end up in some weird laying-down state, fixable by reconstruction

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#60752]
## Round ID:
167363

## Reproduction:
At some point I noticed people were walking through me, and I was unable to left click lockers to toggle them, only use the context menu. I could pass through people, but people didn't need to pass through me to walk over me, even on harm intent. Being rebuilt at robotics solved this. 
Maybe it has something to do with being laid down when borged, or roundstart borgs in general?

**Comment by ZeroMODE0** [comment]
This is an issue that comes and goes as it pleases, and first showed up when simplemobs and borgs were able to lay down/stand up with the U key.

https://github.com/tgstation/tgstation/pull/56089 It was fixed for a while, but I took a break from ss13 and it seems to be back- but I can't press U to solve it so it might be unrelated.

**Comment by ZeroMODE0** [comment]
came back in round 167398 as a roundstart borg

**Comment by interestingusernam3** [comment]
Was the hangover trait active?

**Comment by ZeroMODE0** [comment]
@interestingusernam3 I don't think so. I haven't heard anyone complain about it ingame and looking over it I can't find anything about a hangover station thing

**Comment by interestingusernam3** [comment]
@ZeroMODE0 Hangover is the trait added in #57525. One of the things it does is making people rest.

**Comment by ZeroMODE0** [comment]
@interestingusernam3 Happens at random points in rounds, but I haven't had the chance to be a roundstart borg while paying attention and also have station hangover yet so I'm not sure if this would do it
Just at any random point in a round i'll become the limbo that is borgs laying down, look entirely the same, and be completely unable to stand up which affects:
* left clicking any containers (rmb still unlocks, so you can use the context menu to open them afterwards)
* dragging most things
* people can walk through you, but when you walk through them you swap tiles (Note: when they walk through you, you do not swap tiles, it's like you're not even there and you share the same tile)
I've had admins/robotics fix this and then it happen less than four minutes later so many times that I just stop asking for help

**Comment by interestingusernam3** [comment]
oh no
