### ISSUE TITLE
Geneticist is under "Medical" instead of "Science" when joining the game.

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#60769]
## Testmerges:
The following pull requests are currently test merged:
#60611: 'Disable ALL slips until they are fixed AND admin tool shortcomings get resolved.' by MrStonedOne at commit 6a3fc716ad
#60317: 'large refactor of machine/power code to cut down on processing time and wasted lists' by Kylerace at commit 7e4829934d

## Reproduction:

https://puu.sh/I2lAS/ddb34d7a9d.png
genetics hasn't been in medbay for years

**Comment by Fikou** [comment]
@Rohesie

**Comment by Rohesie** [comment]
The geneticist job was in the science positions list, but with the medical department flag before the refactor:
```dm
GLOBAL_LIST_INIT(science_positions, list(
	"Research Director",
	"Scientist",
	"Geneticist",
	"Roboticist"))
```
```dm
/datum/job/geneticist
	departments = DEPARTMENT_MEDICAL
```
That's the source of this mix-up.

I'll make a PR to fix it.
