### ISSUE TITLE
Circuit admin panel require the circuit be in view or admin ai interact be enabled to work

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#60776]
Clicking into any circuit in the view all circuits admin panel requires the circuit be in view or admin ai interact be enabled to work.

@Mothblocks requested ping. 

I haven't actually tested or verified that that is why it doesn't work, but it's the consensus in the coderbus thread on the issue.

**Comment by Mothblocks** [comment]
#60775 Beat you to it 😉
