### ISSUE TITLE
Eye of god is a bit broken

### ISSUE THREAD

**Issue by D4C-420** [tgstation/tgstation#60781]
## Testmerges:
#60317: 'large refactor of machine/power code to cut down on processing time and wasted lists' by Kylerace at commit 7e4829934d

## Reproduction:

A Lot of mining loot was reworked in https://github.com/tgstation/tgstation/pull/60516 . In the change log for the PR it says that eye of god should only have lost its x-ray and not its thermal vision. I'm not sure if this is intentional or if it just never had thermal in the first place and just was using x-ray but I'm not sure. 

The other issue I had was with the scan ability's just breaking all of a sudden. I would give steps but it just stopped working and did not work for the rest of the round. I tried to reconnect but that did not fix the issue for me. No idea what caused it.

**Comment by necromanceranne** [comment]
I am pretty sure it never had thermal to begin with.

**Comment by D4C-420** [comment]
> I am pretty sure it never had thermal to begin with.

Yea I’m not sure if it was just x-ray or if it had thermals either but meh. Might as well bring it up incase.

**Comment by rasepretep** [comment]
> I am pretty sure it never had thermal to begin with.

It did. Eye of God used to allow you to see every tile, item and player/mob even behind walls, it was the ultimate combination of vision augments.

**Comment by dragomagol** [comment]
@Fikou

**Comment by Fikou** [comment]
i dont understand what you mean by the first thing, xray is basically like meson + thermal + object vision. now you just get meson vision.

and for the second one i cant do much if you dont put reproduction steps and theres no runtimes

**Comment by D4C-420** [comment]
> i dont understand what you mean by the first thing, xray is basically like meson + thermal + object vision. now you just get meson vision.

Yeah I always thought x-ray didn’t include thermals and they were two separate things that one is on me. I just assumed it was an over sight. 


> and for the second one i cant do much if you dont put reproduction steps and theres no runtimes

as far as I know during the round I noticed it stopped working after I got hit by an explosion by gibonite. I also had a power miner (the flame one) if that helps. But the action button at the top of the screen just would not work. It was on cool down at the time I got hit and I noticed that by then I should have been able to use it again.

**Comment by timothymtorres** [comment]
> Yeah I always thought x-ray didn’t include thermals and they were two separate things that one is on me. I just assumed it was an over sight.

I think it's safe to say that this is intended.
 
> as far as I know during the round I noticed it stopped working after I got hit by an explosion by gibonite. I also had a power miner (the flame one) if that helps. But the action button at the top of the screen just would not work. It was on cool down at the time I got hit and I noticed that by then I should have been able to use it again.

This should probably be in a separate bug report with an appropriate title.  I recall encounterubg strange behavior with the mining scanner over a year ago where it quit working but I don't remember the steps to reproduce what happened.

**Comment by Ghommie** [comment]
@timothymtorres, the github actions bot did something suspicious there. :eyes:

**Comment by timothymtorres** [comment]
> @timothymtorres, the github actions bot did something sus there. 👀

Very strange.  If you see something like that happen again please notify the maintainers.
