### ISSUE TITLE
Android wings (maybe skeleton, maybe angel) are invisible but still function

### ISSUE THREAD

**Issue by Cookhimself** [tgstation/tgstation#60782]
## Round ID:
Tested downstream on Fulpstation

## Reproduction:
Become android usually through magic mirror

Drink wing potion and notice invisible but functioning wings

BONUS: Putting on a heck suit does not give you the normal message of your wings being covered and still function, and allowed me to freely move around in space. This wasn't tested with the new heck suit but it probably still works the same

**Comment by Time-Green** [comment]
Probably my fault, will look into it in a few hours

**Comment by Mooshimi** [comment]
@Time-Green Do you still plan on fixing this?

**Comment by Time-Green** [comment]
I already did but the fix was auto-closed, and I can’t really spare the time right now

**Comment by Mooshimi** [comment]
> I already did but the fix was auto-closed, and I can’t really spare the time right now

You mean it's completed, or you can't spare the time to finish it? I can reopen and give it an antistale tag
