### ISSUE TITLE
Strange Plants no longer produce reagents.

### ISSUE THREAD

**Issue by dondonpow** [tgstation/tgstation#60803]
## Round ID:
167570

## Reproduction:
Harvest strange seeds, and then try to grind/eat the resulting strange plant.

**Comment by MrMelbert** [comment]
Did the strange plant have any reagents or traits on it? They're not guaranteed to spawn without chemicals, and even if they had chemicals / traits they could react to lose them somehow on harvest

**Comment by MrMelbert** [comment]
attempted to reproduce on latest master, got reagents:
![image](https://user-images.githubusercontent.com/51863163/129114972-b0b50d8d-9400-4227-91d3-9ae003f5c2d8.png)
![image](https://user-images.githubusercontent.com/51863163/129114991-14526176-4057-47d2-8e00-67dce1b18700.png)
![image](https://user-images.githubusercontent.com/51863163/129114984-5c89e687-6414-4c4d-9c8b-906311a64769.png)

**Comment by dondonpow** [comment]
>They're not guaranteed to spawn with chemicals
I may just be insanely unlucky then, since the past 4or 5 times I've tried to harvest a strange seed, all it has had was a unique trait.

**Comment by MrMelbert** [comment]
Remember you can right click a strange seed packet with the plant analyzer to see if they have any chemicals before planting them.

**Comment by dondonpow** [comment]
Just tried it again, no dice. Could you try to reproduce on a live server?

**Comment by MrMelbert** [comment]
works on live, I think you're just unlucky, or need to provide more in depth reproduction steps

**Comment by dondonpow** [comment]
Ok, I just got some reagents in a strange plant. I guess I was just really unlucky.
