### ISSUE TITLE
Syndicate Encryption Keys don't work in Cyborgs

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#6080]
So I was a traitorous RD and there weren't any roboticists, so when some assistant came looking to be borg'd I subverted him. After that I had a cool idea, so I bought two syndicate encryption keys, and put one of them in the borg. The problem is that the cyborg couldn't hear any of the other channels.

**Comment by tedward1337** [comment]
Has this been fixed?

**Comment by coiax** [comment]
This isn't a bug, this is just a consequence of our radios being complicated. Having turn on subspace for the radio channels to work is... normal I think?
