### ISSUE TITLE
mothra wings are invisible while retracted

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#60810]
![image](https://user-images.githubusercontent.com/42606352/128965173-bdd56102-9aa6-4d46-b5a3-8202ea77fdc7.png)
![image](https://user-images.githubusercontent.com/42606352/128965188-ed8b8686-d397-4cb6-8701-50709460357a.png)

cursed

**Comment by redguy999** [comment]
same with the other moth wings.

**Comment by redguy999** [comment]
@Time-Green you're working on this stuff, right?

**Comment by Time-Green** [comment]
Weird, I saw it work perfectly fine the day before yesterday
