### ISSUE TITLE
Cursed Springs Can Turn People Into Statues (The mob that is really dangerous)

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#60824]
## Round ID: 
[167642](https://scrubby.melonmesa.com/round/167642)

## Testmerges:
#60317 
#60694 

## Reproduction:
A random player stepped into the cursed spring (honestly this thing sucks and causes so many problems), which teleported them back on station as a statue, an unkillable monster that can annihilate people in seconds.

**Comment by jughu** [comment]
Not a unkillable monster just lot of health

**Comment by jughu** [comment]
They just have 50k

**Comment by SmArtKar** [comment]
> They just have 50k

50k is still like 5 times more than all lavaland megafauna combined

**Comment by jughu** [comment]
There used to be 100 bonus damage fron pickaxes but got removed

**Comment by ArcaneDefence** [comment]
The spring uses `wabbajack()`, which is also used in polymorph wands/staves.

Working as intended, but could be asked if it should be kept that way

**Comment by ATH1909** [comment]
"an unkillable monster that can annihilate people in seconds."

this is a bit misleading, as weeping angels are kind of shit currently. they can't move or attack while being "watched", which is defined by the game as the weeping angel being in the sight range of a non-silicon, non-blinded player while the weeping angel is not in darkness.

**Comment by TheBonded** [comment]
if this isn't a bug, why is it still open?
