### ISSUE TITLE
GLOB.roundstart_races is only populated when SSjob is initialized, so appearance randomization runtimes if done before then

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#60823]
## Reproduction:

For some reason the list of config enabled roundstart races is populated by Initialize in SSjob (`generate_selectable_species`)
https://github.com/tgstation/tgstation/blob/badc431a9c9a27c351b5d4e70826eaa8dee6f2f8/code/controllers/subsystem/job.dm#L71-L79

Meaning, if a fresh player connects before SSjobs is done initializing, this bit of randomization runtime errors, as it is trying to pick from an empty list. This can happen semi-often since `/datum/preferences/New()` calls `randomise_appearance_prefs`, and new preferences are made when fresh players connect (example: guest accounts).
https://github.com/tgstation/tgstation/blob/badc431a9c9a27c351b5d4e70826eaa8dee6f2f8/code/modules/mob/dead/new_player/preferences_setup.dm#L10-L12

![image](https://user-images.githubusercontent.com/51863163/129116399-582398a2-18ec-49ea-9647-4f794c2abd32.png)

### Potentially fixed by new preferences menu, leaving this open for tracking purposes.

**Comment by Mothblocks** [comment]
> Potentially fixed by new preferences menu, leaving this open for tracking purposes.

it is but it'll be a bit
