### ISSUE TITLE
non mask items that go on mask slot runtime and break breathing

### ISSUE THREAD

**Issue by aaaa1023** [tgstation/tgstation#60837]
## Round ID:

 Reproduced locally

## Reproduction:

 
Give self oxyloss by any means
equip a rose or harmonica on mask slot
game will start runtiming and you won't regain the oxyloss damage you took.
the runtimes point to some code about mask filters in lungs.dm so maybe it was broken by #58529?

**Comment by aaaa1023** [comment]
![image](https://user-images.githubusercontent.com/74441292/129357988-94044ad0-788b-4007-bd4b-681f8bbb5642.png)

this is the exact runtime message

**Comment by ATH1909** [comment]
ghilkeeeeeeeeeeer

**Comment by timothymtorres** [comment]
This is pretty hilarious and one _could_ argue that it's a feature since any object that gets in the way of your mouth would impair your breathing.  I do think it should be fixed though.
