### ISSUE TITLE
Random event: Alien Infestation seems to runtime

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#60836]
## Round ID:

[167712](https://scrubby.melonmesa.com/round/167712)

## Reproduction:

Alien Infestation random event seems to runtime due to mobs being passed in as candidates instead of clients.
![image](https://user-images.githubusercontent.com/51863163/129304335-f90f93aa-dd0c-49c3-8a8e-5ea21f647fd1.png)
![image](https://user-images.githubusercontent.com/51863163/129304338-83497f9d-b09b-489a-ad17-de895c148966.png)

**Comment by TheVekter** [comment]
This is still happening, @Ghommie Did you ever manage to fix this?

**Comment by Ghommie** [comment]
As you can see for yourself, the PR meant to fix it went stale and was autoclosed. I may try to give it another shot later though.

**Comment by Mothblocks** [comment]
https://github.com/tgstation/tgstation/blob/cb5fb1df2de5a2dc91bd803f72ceb76717ea8e02/code/modules/events/alien_infestation.dm#L70-L71

The type is wrong--this is a mob, not a client.
