### ISSUE TITLE
directional lights are clingy

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#60830]
sometimes they'll just... stick around

![image](https://user-images.githubusercontent.com/42606352/129174461-57032b00-63e1-475c-a9f4-66a29fe518b8.png)

their direction gets stuck as well, and they'll follow you

makes hiding in the dark very hard sometimes

**Comment by ATH1909** [comment]
this might be related to moving a light source between inventory slots? idk, this bug has been kind of inconsistent during testing

**Comment by Couls** [comment]
I do think this is related to the inventory slot bug, should be fixed by #60756

**Comment by Couls** [comment]
closing as #60756 is merged, if you still see the issue after the servers have updated make a post here and I'll re-open
