### ISSUE TITLE
Autophagocytosis Necrosis' Stage Speed 7 Threshold Synthesizes Impure Heparin and Lipolicide

### ISSUE THREAD

**Issue by Adanps** [tgstation/tgstation#60832]
## Round ID:
[167676](https://scrubby.melonmesa.com/round/167676)
## Testmerges:
#60317 
#60694
This bug was also found testing locally on a build from 6 days ago, so these are probably ignore-able.
## Reproduction:
Create a disease with Autophagocytosis Necrosis and a stage speed of 7 or higher. Scan the chemicals synthesized in the infected.

https://github.com/tgstation/tgstation/blob/55b92786dcf0f9c5172efd111a6ecbf83ec0dae2/code/datums/diseases/advance/symptoms/flesh_eating.dm

Autophagocytosis Necrosis' speed threshold used to synthesize large amounts of pure Heparin and Lipolicide into the victim. Now, it mainly creates Chemical Isomers and Ipecacide, while the amount of Heparin and Lipolicide is small enough that they quickly metabolize out of the infected's blood.
![image](https://user-images.githubusercontent.com/32281090/129212575-a8d381aa-38aa-4031-a5e0-3f330fa0fbd9.png)
 Presumably, after the PH change to chemistry this threshold began to synthesize impure chemicals, thus greatly reducing the efficacy of this threshold (Which was already greatly weakened due to Heparin no longer causing incredible amounts of bleeding on its own.) This threshold doesn't work as it should, and is kinda just sad compared to how it once was.

**Comment by Adanps** [comment]
On a side note, ARDS's stage speed threshold still seems to still synthesize pure Pancuronium and Sodium Thiopental. I haven't checked to see if Alkali Perspiration's Transmission threshold synthesizes correctly or not.

**Comment by ATH1909** [comment]
fun fact: even before fermihem, autophago's chem production threshold would apply its doses in volumes that could easily be purged by the host's liver, making it nigh-useless

**Comment by ATH1909** [comment]
the impure lipolicide production here is actually a buff to that chem production threshold, as impure lipolicide applies a big burst of disgust.

**Comment by Adanps** [comment]
That is actually interesting, and goes to show that lipolicide isn't a very dangerous chem. Years ago when I last messed around with the symptom it was always the heparin I cared about, since at the time it made the infected bleed severely, and thus made the symptom much harder to treat. That being said I don't really know what would be the best outcome here, but I think having the description of the threshold differ from the in-game result is problematic.

**Comment by ATH1909** [comment]
... actually, if you roll enough threes for the symptom cooldown, it might be possible for lipolicide and/or heparin to breach the ~3u threshold and start accumulating.

**Comment by Sealed101** [comment]
seems to be working as expected nowadays, i think
![изображение](https://github.com/user-attachments/assets/3d777055-5a91-41c1-a1ad-26eb61c69b25)
