### ISSUE TITLE
Heal through character panel(or how it called) do not removes mutations

### ISSUE THREAD

**Issue by Colovorat** [tgstation/tgstation#60844]
## Reproduction:

open character panel through right click, press Heal at top right, you still have H.A.R.S

**Comment by ArcaneDefence** [comment]
It's not meant to. 
For mutations you `view variables`, and use this drop down menu option.
![image](https://user-images.githubusercontent.com/51932756/129432037-4b7d0e0b-612f-4a8d-837c-b52500144c29.png)

It gives you this menu where you can be specific or general.
![image](https://user-images.githubusercontent.com/51932756/129432052-fb163b30-defa-466a-bc56-568dc86b66c6.png)
