### ISSUE TITLE
Traitors sometimes get one or even no objectives

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#60866]
## Round ID:
[167811](https://scrubby.melonmesa.com/round/167811)

## Testmerges:
- [Fixes TP assigned_role change, adds safety check](https://www.github.com/tgstation/tgstation/pull/60814)

## Reproduction:

I've seen multiple times across the last week or so traitors have been only getting assigned one or even no objectives.
![image](https://user-images.githubusercontent.com/51863163/129462181-ebf9a98f-05e3-4341-8d42-cc644811ab7a.png)

**Comment by TheMidnightRose** [comment]
Adding to this with new information. 
Traitors sometimes get objectives HOWEVER the game refuses to tell them their objectives. 
It also will assign an uplink to them but not tell them their codes for it even though it shows up in memories.

**Comment by itseasytosee** [comment]
Should be fixed by Biddle traitors. Whatever the hell a Biddle is.

**Comment by JohnFulpWillard** [comment]
Biddle traitors fixed this, but i believe the original cause was some faction only giving you one objective, or something like that.
