### ISSUE TITLE
repairing tattered jumpsuit doesnt change tattered sprite

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#60861]
## Reproduction: https://streamable.com/9c659o

Repairing a tattered jumpsuit with cloth doesn't change the sprite from being tattered even if you put it on and off again, throw it etc.

**Comment by Murphy-ZJ** [comment]
Does leaving the game and re-entering fix the issue?

**Comment by GreatKingWombat** [comment]
Does leaving the game and re-entering change the sprite?

**Comment by TheBonded** [comment]
alt click on the jumpsuit to change it to casual mode, this will reset the sprite and you can change it back safely to fix the sprite
