### ISSUE TITLE
Wallet station trait doesn't give departmental security IDs

### ISSUE THREAD

**Issue by vkalls** [tgstation/tgstation#60880]
## Reproduction:
Have the wallet station trait happen, sign up as security, no specialized security ID. Medsec, Engisec, etc.

**Comment by vkalls** [comment]
why the fuck did I type crate

**Comment by Mooshimi** [comment]
So can I get more details on this? You were notified you got assigned to a department? No?

**Comment by Xander3359** [comment]
I have been unable to reproduce this
![image](https://user-images.githubusercontent.com/66163761/216792639-e7d43c37-8503-4add-af9d-d10f18f78eaf.png)
Should the bug arise again, open a new report.
