### ISSUE TITLE
Invisible Personalized Items From Invalid Hex Numbers

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#60882]
Reporting client version: 514.1561

## Round ID:
[167882](https://scrubby.melonmesa.com/round/167882)

## Testmerges:
- [Added component manipulation on objects](https://www.github.com/tgstation/tgstation/pull/60771)
- [Changes the input list in VV add component to tgui_input_list()](https://www.github.com/tgstation/tgstation/pull/60755)

## Reproduction:
When setting hex number values for the colors of custom items, setting invalid numbers creates invisible items. Specifically on this round, I set the values for all colors on the Tailored Winter Coat to 000000 (as opposed to the proper entry of #0 0 0 0 0 0) and it was completely invisible, with the exception of the hood, which does not get a custom color. Setting all values to #uuuuuu produced the same effect. Inhand sprite is unaffected and is identical to standard winter jacket, but worn and inventory sprites are invisible.

**Comment by Sealed101** [comment]
could not reproduce
