### ISSUE TITLE
You can ollie with no skateboard on tram

### ISSUE THREAD

**Issue by KittyNoodle** [tgstation/tgstation#60898]
Reporting client version: 514.1561

## Round ID:
[167916](https://scrubby.melonmesa.com/round/167916)

## Testmerges:
- [Added component manipulation on objects](https://www.github.com/tgstation/tgstation/pull/60771)
- [Changes the input list in VV add component to tgui_input_list()](https://www.github.com/tgstation/tgstation/pull/60755)

## Reproduction:

1. Make skateboard
2. Skate on the tram rail and stop moving with arrows
3. Skateboard starts floating
4. Buckle yourself to said skateboard, and get instantly sent down a z-level
5. Notice you still have the ollie ability
6. oh god

**Comment by KittyNoodle** [comment]
ok you can teleport with this apparently
what the fuck

**Comment by TemporalOroboros** [comment]
Is this related to buckling onto chairs on the tram while it's moving dumping you off of the tram?

**Comment by KittyNoodle** [comment]
could be similar, skateboard ends up floating in mid air, leading to you falling as soon as you buckle borking the game hard

**Comment by Ghommie** [comment]
It's an issue with multi z movement code, not the skateboard itself.

**Comment by Sealed101** [comment]
neither tram rails nor slippery turfs cause ghost driving of the skateboard. can't find the fix PR but it's related to movement and gravity in general, as it seems to be handled better before the user gets buckled to the vehicle
