### ISSUE TITLE
Stacks do not respect the concept of item slots

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#60901]
Stacks do not respect item slots. So if you have say, 10 sheets of metal in a pocket, and you pick up 5 more, you now have 15 sheets of metal in your hand. This can also lead to stupid fucking errors with things that attempt to put say 10 sheets of x in your right pocket, and then 10 sheets of x in your left.

They should not do this. Each slot should be considered independently. But that's hell. I don't know what to do about this honestly, but I know something should be done.

**Comment by TemporalOroboros** [comment]
Alright. Who wants to refactor the concepts of position and movement?
