### ISSUE TITLE
Tramstaion railing bug

### ISSUE THREAD

**Issue by Crus0** [tgstation/tgstation#60916]
Round ID: unknown 

Reproduction: fill in the empty space of the tram line with flooring. Then, climb over a railing.

Issue: while as a cyborg, I filled the empty space of the tram line with floor tiles. However, climbing over a railing will cause the effect of falling down.            (similar to an EMP for borgs), despite not actually falling due to the inserted floor. This happened south to north and north to south.

**Comment by Crus0** [comment]
I only saw it with the ones that were already there

**Comment by dragomagol** [comment]
This looks like it's not a bug. Humans get stunned temporarily when they climb onto railings like when they climb onto tables. When borgs climb onto tables and railings they get stunned as well.
