### ISSUE TITLE
Can't view player's traitor objectives in TP

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#60924]
Reporting client version: 514.1557

## Round ID:
[168025](https://scrubby.melonmesa.com/round/168025)

## Testmerges:
- [Added component manipulation on objects](https://www.github.com/tgstation/tgstation/pull/60771)
- [All AI datum behaviors are now added using a wrapper](https://www.github.com/tgstation/tgstation/pull/60667)
- [[READY] Adds memory system, and engraving walls with chisels](https://www.github.com/tgstation/tgstation/pull/60302)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/129916839-6b93eb87-d71a-458c-84e2-fe53813ec5cd.png)

![image](https://user-images.githubusercontent.com/66640614/129917672-2634f20b-8fde-48ac-97a9-a063b20fbab1.png)

**Comment by dragomagol** [comment]
Turns out this was unrelated to the testmerge

**Comment by Timberpoes** [comment]
![image](https://user-images.githubusercontent.com/24975989/130338563-903eb92e-99e8-4203-a944-20000f9c0ba1.png)
Null entries sneaking their way into the objectives list for the /datum/antagonist/traitor.

**Comment by tralezab** [comment]
I found it, that's on me, i'll fix it in a little.

**Comment by JohnFulpWillard** [comment]
closed by https://github.com/tgstation/tgstation/pull/60993
