### ISSUE TITLE
stairs look like GEN TURF through mesons when on the other side of a wall

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#60935]
https://puu.sh/I53Ff/f531d9ba9e.png

**Comment by timothymtorres** [comment]
This looks like maybe it could be a mapping issue?  What map/spot did this happen on @newfren

**Comment by newfren** [comment]
this was on boxstation, in the downstairs bar area but all around service it was happening

**Comment by timothymtorres** [comment]
This seems like it is related to #53783

**Comment by newfren** [comment]
I was on the same z-level as the bottom of these stairs, for what it's worth.

**Comment by san7890** [comment]
Actually, this is more of an issue with how mappers should be placing stairs over gen_turfs. As of #67252, the codebase now actively lints against this behavior.
