### ISSUE TITLE
Tramstation White Ship can (will always?) spawn in hyperspace

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#60959]
## Testmerges: The following pull requests are currently test merged:
#60771: 'Added component manipulation on objects' by Watermelon914 at commit fcdde790ac
#60755: 'Changes the input list in VV add component to tgui_input_list()' by Thunder12345 at commit cf62458dfa

## Reproduction:
The tram whiteship spawned in hyperspace this round. I don't know if it always does this but I haven't seen a distant signal in hyperspace for a while. Might be only this model?
https://puu.sh/I5qr0/a20f81e0ca.png

I further explored the z-level it was on and saw the arrivals shuttle flying through it, so it is in hyperspace and not just the last z-level or whatever. I explore space semi-frequently, and have never seen the tramstation white ship.

**Comment by dragomagol** [comment]
I believe this is also the case for the Kilo Whiteship

**Comment by newfren** [comment]
yeah, I just didn't have any evidence for that.

**Comment by Mooshimi** [comment]
I've actually been seeing a lot of runtime recently about white ships not being able to dock round start due to height issues.

**Comment by thgvr** [comment]
this is still happening, can't normally find kilo or tram white ships

**Comment by Addust** [comment]
![image](https://user-images.githubusercontent.com/80979251/145303104-d4f89a56-1f22-49bf-8e8b-298062f74284.png)
:)

**Comment by Addust** [comment]
Also this doesn't mention the same bug occurs with kilo whiteship, my issue report for that got closed so ye
