### ISSUE TITLE
Engineer deployable turret turns invis

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#60956]
Step 1 buy toolbox
step 2 deploy
step 3 buy agent id
step 4 turn turret off
step 5 turret is now invis and can't be interacted with

**Comment by timothymtorres** [comment]
This looks like it might be something from #60554.  @Paxilmaniac can you take a look at this?

**Comment by timothymtorres** [comment]
Also this might be a dupe of #53032 but I'm not sure

**Comment by projectkepler-ru** [comment]
N/A @timothymtorres

**Comment by Sealed101** [comment]
can no longer reproduce; turrets are still decrepit code though sadly
