### ISSUE TITLE
Admin prisoned players with Telekinesis can access visible consoles

### ISSUE THREAD

**Issue by NamelessFairy** [tgstation/tgstation#60967]
## Reproduction:

If a player with Telekinesis is put into the admin prison they can interact with various consoles in their view range, one of these includes a security record console which they can use to alter security records and/or purge them, which is something we ideally don't want admin prisoned players doing

**Comment by Timberpoes** [comment]
My proposed half-assed hacky as shit solution to this was to load up a bunch of traits when players enter the aprison area. No teleport, no interacting with computers, stuff like that. They can be removed when the player leaves the aprison area.

Someone else may have better ideas.

**Comment by tralezab** [comment]
Alternatively, we could put dummy computers in there, but I get why you want to solve the problem permanently

**Comment by NamelessFairy** [comment]
> Alternatively, we could put dummy computers in there, but I get why you want to solve the problem permanently

For reference, the thing that sparked this issue report was a player with telekinesis purging the entire security record while in prison.
