### ISSUE TITLE
Cult teleport working inside admin prison

### ISSUE THREAD

**Issue by SweetDaytona** [tgstation/tgstation#60968]
## Round ID:
[168225](https://scrubby.melonmesa.com/round/168225)

## Reproduction:

Player was able to escape admin prison via some method of cult teleport. They then rejoined the shift and continued to play as normal.

**Comment by Timberpoes** [comment]
Linked with #60967 under a broad heading of "things players shouldn't be able to do in aprison"

**Comment by timothymtorres** [comment]
When a player gets tp'd to admin prison they should inherit some kind of NO_TELEPORT trait temporarily

**Comment by Livrah** [comment]
Feature.

**Comment by Redrover1760** [comment]
> Feature.

LMAO
