### ISSUE TITLE
Smart pipes get blocked by other smart pipes unless restricted, even in unconnected directions

### ISSUE THREAD

**Issue by esainane** [tgstation/tgstation#60978]
Attempting to recreate the first [BASIC PIPING GIFS](https://imgur.com/a/BDueHKa) setup with current master (156fecb326) results in the following sadness:

![unsmart-pipes-master](https://user-images.githubusercontent.com/14355175/130340861-880f6430-8a52-4623-bbf6-3b7cb92e32ab.png)

Merging PR #60804 slightly improves the situation, but not by much:

![unsmart-pipes-60804](https://user-images.githubusercontent.com/14355175/130340865-cd41e298-cf70-4c21-8307-f3b4e02a0977.png)

The main atmospherics area still uses restricted 2-way and 3-way "oldpipe-style" pipes, where smart piping works as expected:

![smart-pipes-no-block](https://user-images.githubusercontent.com/14355175/130340999-3fd4ebb7-6966-4e76-9dbf-7bcfe421674e.png)

However, virtually everywhere else uses all-way smart pipes, leaving placement sad:

![smart-pipes-4-block](https://user-images.githubusercontent.com/14355175/130341015-c02eace7-3564-45a4-a055-194673892d8f.png)

Replacing gas pumps in the atmospherics Incinerator with another device, such as a manual valve, is a complete headache requiring ripping up the reinforced floor, removing the underlying smart pipe, sticking down a restricted 2-way smart pipe in its place, putting the reinforced floor back (technically not required if you're a shameless angerphile), and finally placing the device.

Most of the other examples in the BASIC PIPING GIFS gif also do not work, which may or may not be related

## Reproduction:

 - Build five all-way cyan smart pipes to form a W-S corner
 - Build five all-way black smart pipes to form a N-E corner overlapping the first five pipes
 - Observe how the result is very sad, and not at all like the first BASIC PIPING GIFS gif: https://imgur.com/a/BDueHKa

**Comment by timothymtorres** [comment]
So I know @Ghilker had done PR #60400 that changed how pipes are mapped since a lot of players were having issues with SM and atmos setups pipes that would contaminate different pipenets.  I'll let him decide if this is intended, a mapping issue, or a bug since he is the creator of smart pipes.

**Comment by 170141183460469231731687303715884105727** [comment]
Not sure how to fix the smart pipe not automatically turning into a bridge pipe, but placing bridge pipes should work normally after the PR gets merged.
