### ISSUE TITLE
Pandemic bluescreens when clicking on a virus symptom

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#60977]
Reporting client version: 514.1557

## Round ID:
[168242](https://scrubby.melonmesa.com/round/168242)

## Testmerges:
- [Enable strictNullChecks on tgui](https://www.github.com/tgstation/tgstation/pull/60961)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/130343773-afdc721d-2a37-4bc4-9808-d68efd6eb9c8.png)

**Comment by Alexjbd** [comment]
![image](https://user-images.githubusercontent.com/89334189/130346177-62e4b7a6-02ac-4acb-a218-cb913c2acde2.png)
same
