### ISSUE TITLE
Sholean grapes can't eat leading them to die inevitably

### ISSUE THREAD

**Issue by ANAME593** [tgstation/tgstation#60973]
## Reproduction: Not 100% sure what went wrong with the code

 Basically a Slime makeable via cytology (sholean grapes) requires  nutrition to survive however there seems to be a bug where the sholean grapes can't eat food from what i've heard from other people i don't exactly know what went wrong with the code or anything but i do know this is a bug and that is why i made this report

**Comment by ANAME593** [comment]
is this gonna go Stale without anybody expect 1 person seeing this Oof

**Comment by LemonInTheDark** [comment]
Issue reports can't go stale, and we don't have enough people working on basic bugfixes to chew through em all as they're created. they serve as records more then anything else, when someone decides to try and fix something

Still very helpful, just less immediate action

**Comment by ANAME593** [comment]
Temporary solution for anybody who tries to make these: you can inject pure nutriment into them via a syringe Grind food preferably raw meat slabs and get the pure nutriment  it should around 30u or so to put them back at full nutriment

**Comment by Yawet330** [comment]
I know what causes this, and for some reason its the 'consume' action button (consume a held mob) does not pass down from its 'owner' (Gelatinous Slime Cube) to the Sholean grapes, rendering it unable to eat unintentionally


Also sholean grape code is sus as fuck and needs a rework. It uses several (now deprecated) methods in it.

**Comment by ANAME593** [comment]
i don't speak coder can you explain?

**Comment by Sealed101** [comment]
fixed in #61029 though the oozes could really use an uplift to basicmobs
