### ISSUE TITLE
Fridges being wierd

### ISSUE THREAD

**Issue by sirnat** [tgstation/tgstation#60991]
Reporting client version: 514.1561

## Round ID:[168274](https://scrubby.melonmesa.com/round/168274)
168274
 

## Testmerges:
- [Enable strictNullChecks on tgui](https://www.github.com/tgstation/tgstation/pull/60961)

## Reproduction:
When you open med fridges like virology's or chems it says theres items inside, but nothing is there. When you click one or many, nothing happens either.

https://gyazo.com/19967e098fc86ee3f573a4cae2d56cb1

https://gyazo.com/198171dfe42f67460e27cbeb1509a619

**Comment by Mothblocks** [comment]
It's a bug I already fixed, Sybil is just not updated.
