### ISSUE TITLE
NTNet output type is string and not changing

### ISSUE THREAD

**Issue by TheLeopold** [tgstation/tgstation#61009]
Here you can see that it connects to string input and not connects to number
![изображение_2021-08-24_124824](https://user-images.githubusercontent.com/62264115/130557354-87eb307d-ede1-4409-a0c7-e637762d795d.png)

## Reproduction:
connect NTNet receiver to any non-string input

**Comment by TheLeopold** [comment]
Really? Are there "To entity" converter?

**Comment by SmArtKar** [comment]
> Really? Are there "To Entity" converter?

dunno, probably
