### ISSUE TITLE
Debugging no longer works, presumably because tgstation.m.dmb is deleted before Dream Daemon/Seeker starts

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#61004]
I pressed F5 and got this notice.

![image](https://user-images.githubusercontent.com/35135081/130524103-4cf471f5-e4bb-4499-889a-27a59842f9f6.png)

CC @stylemistake

**Comment by AMonkeyThatCodes** [comment]
piece of shit file made me have to re-dl the entire repo already once

**Comment by Mothblocks** [comment]
It seems that cancelling bin/tgui --dev that I had open before fixed it, but I would like to see if there was a better notice.

**Comment by Mothblocks** [comment]
Pressing F5 a second time for this log:

![image](https://user-images.githubusercontent.com/35135081/130526672-a3650b89-83f9-4e89-8a3e-e0695875cb72.png)

...gets the error again, even if with no bin/tgui --dev

**Comment by SuperNovaa41** [comment]
umm i can debug still. probably got fixed
