### ISSUE TITLE
Grey Jumpskirt sprite showing up when Black Jumpskirt is worn. 

### ISSUE THREAD

**Issue by Pinkufeck** [tgstation/tgstation#61012]
## Testmerges: 
#60961: 'Enable strictNullChecks on tgui' by Mothblocks at commit 93b42c5d48

## Reproduction:

Wear black jumpskirt
Appears grey unless rolled down.

**Comment by Shroopy** [comment]
This seems to be affecting all jumpskirts, they all turn grey when worn, sometimes even when rolled down.

**Comment by Shroopy** [comment]
Not only does this affect all colored jumpskirts, it also seems to be based on which jumpskirt is worn first. For example, putting on a blue jumpskirt then a gray one makes the gray one look blue.

**Comment by Shroopy** [comment]
This only happens with characters with the female body type.
