### ISSUE TITLE
there's a fire alarm in kilo's monkey pen

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#61047]
a redundant one, at that

and yes, the monkeys inside the pen can and will pull it

![Screenshot (203)](https://user-images.githubusercontent.com/42606352/130925089-a3b60522-fc1e-4746-8a3b-e7dce50f93c2.png)

**Comment by newfren** [comment]
they can also, it's important to note, pull it through a sheet of reinforced glass, as can a player.

**Comment by Thunder12345** [comment]
> 
> 
> they can also, it's important to note, pull it through a sheet of reinforced glass, as can a player.

Further evidence that directional windows are ass
