### ISSUE TITLE
New main menu blocks important title screen elements

### ISSUE THREAD

**Issue by Pumpkinoe** [tgstation/tgstation#61061]
Because the new main menu is a static collection of sprites instead of a moveable GUI element, it blocks a good portion of the title screen. I was unsure whether to make this an issue report or not, but I suppose this is technically a consistency issue.

As seen in the image, it completely blocks 'Space Station 13' of one of the main title screens: Turning it into 'SPI 13'. 

![image](https://user-images.githubusercontent.com/61306435/131053456-9603af05-5ea5-499e-86f8-66b6b6604df6.png)

**Comment by Time-Green** [comment]
@AMonkeyThatCodes

**Comment by AMonkeyThatCodes** [comment]
This is not really a bug. Our splash screens are not widescreen either even though it's how our game defaults. The space station 13 in that screen is not meant to be a title bar for us it's just a detail they put in.
