### ISSUE TITLE
Trying to eject someone from a Odysseus sleeper deleted the person in the sleeper. (maybe)

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#61060]
## Round ID:
[168514](https://scrubby.melonmesa.com/round/168514)

## Reproduction:
1. put a person in an Odysseus sleeper.
2. use the menu to eject them.
3. have them disappear.
I couldn't get a clear answer from the admin (RaveRadbury) about exactly what happened to the person, and the other person wasn't connected at the time. Don't know if this was a one time issue, or an actually problem with Odysseus sleepers.

**Comment by timothymtorres** [comment]
I wonder if the sleeper is inheriting the behavior of the afk sleepers in dorms.  When a person disconnects it removes their mob from the game.

**Comment by Ghommie** [comment]
> 
> 
> I wonder if the sleeper is inheriting the behavior of the afk sleepers in dorms. When a person disconnects it removes their mob from the game.

No, they are different types. `/obj/machinery/cryopod` is for the afk sleepers; `/obj/machinery/sleeper` for medbay ones; `/obj/item/mecha_parts/mecha_equipment/medical/sleeper` for mechas.

**Comment by Colovorat** [comment]
https://user-images.githubusercontent.com/35225170/131240802-1bc69b95-0709-433e-a153-e28aece4851c.mp4

i dunno i tried worked OK

**Comment by Fikou** [comment]
cannot reproduce
