### ISSUE TITLE
a bar bot continued to brutalize its victim's corpse after its victim's death

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#61065]
![Screenshot (205)](https://user-images.githubusercontent.com/42606352/131112407-3f5a9cfd-488a-453b-bbdd-54ea26ea49e2.png)
![Screenshot (206)](https://user-images.githubusercontent.com/42606352/131112409-af68de3b-386c-4162-9002-4bf547f497a1.png)

**Comment by timothymtorres** [comment]
I believe simple mobs do this.  Narsie Ian and monkeys would keep chasing and attacking dead mobs.  I think it has something to do with the AI behavior.
