### ISSUE TITLE
Jaunter's wormholes can move in zero gravity

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#61075]
## Reproduction:
-Use the Jaunter in space
-Move
> https://youtu.be/OUZQuVio1SA

Idk what isnt broken anymore.

**Comment by rasepretep** [comment]
@timothymtorres Tagging you just in case it's relevant to recent changes.

**Comment by timothymtorres** [comment]
Yea my PR hasn't been merged yet so whatever happening is something else.  The bug is hilarious though and potentially very hazardous.  Imagine doing this when the grav gen is disabled on the station.  Bouncing wormholes that are OP.
