### ISSUE TITLE
Odysseusussues are fucked up

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#61086]
Currently, Odysseusses, Odyssei, Whatever, say "will synthesize first 3.5 reagents" or was it 2.5? whatever

The point is it claims that it's going to synthesize half of one kind or reagent or something, it should be a whole number.

Listen, this bug has been around for like, AGES and I just now realized it was never actually reported.

**Comment by YakumoChen** [comment]
chemical synthing is also very buggy in general, you can't stop synthsizing until it's all the way full.

**Comment by timothymtorres** [comment]
This seems related to #31206

**Comment by interestingusernam3** [comment]
When the odysseus us sus

**Comment by TheBonded** [comment]
> chemical synthing is also very buggy in general, you can't stop synthsizing until it's all the way full.

@YakumoChen you can, it's just difficult. You have to uncheck the chemicals you want to stop synthesizing and then click apply changes before the next synthesis cycle when it resets to what the setting are currently set to. Generally you have to disable only 1-2 chemicals at a time, and you have to have quick timing.

**Comment by YakumoChen** [comment]
I could point out that doesn't at all sound like intended behavior

**Comment by TheBonded** [comment]
> 
> 
> I could point out that doesn't at all sound like intended behavior

oh, not at all likely, I assume the check boxes shouldn't reset to the currently set setting every single time it synthesizes chemicals (usually once per 2 seconds).

**Comment by Sealed101** [comment]
amended by #82286 - that phrase was removed (and it was kinda wrong anyway)
