### ISSUE TITLE
Slimes unable to move in pipes after take 1 damage from atmosphere inside the pipe

### ISSUE THREAD

**Issue by techno0** [tgstation/tgstation#61097]
## Reproduction: 

- Become a slime
- Go inside pipe
- Take 1 damage from low temps in pipe
- Loose all mobilty and die alone knowing nobody loves you

An admin confirmed beeing able to replicate this issue.

[https://atlantaned.space/banbus/ticket/483da978bcd4032e](url)

**Comment by LemonInTheDark** [comment]
This is intended behavior, see https://github.com/tgstation/tgstation/blob/c94c9ed8b03ae10ff2e1fd68717510067fa9b841/code/modules/mob/living/simple_animal/slime/life.dm#L131-L143
