### ISSUE TITLE
Generate Documentation is Broken

### ISSUE THREAD

**Issue by ORCACommander** [tgstation/tgstation#61106]
First PR to show up with the issue is https://github.com/tgstation/tgstation/pull/60905

## Reproduction:
https://github.com/tgstation/tgstation/actions/workflows/generate_documentation.yml

**Comment by timothymtorres** [comment]
This issue is too vague and needs to be updated with more information.

**Comment by ORCACommander** [comment]
fixed in https://github.com/tgstation/tgstation/actions/runs/1217861635
