### ISSUE TITLE
Cannot access toilet cistern without bashing it

### ISSUE THREAD

**Issue by JetBrody** [tgstation/tgstation#61125]
## Round ID:
[168755](https://scrubby.melonmesa.com/round/168755), will work on any round

## Reproduction:

Attempting to open a toilet cistern with a crowbar results in smacking it regardless of input method used.

Tested both left and right click in and out of combat mode.

1. Obtain crowbar or crowbar substitute
2. Use your chosen tool on the toilet
3. Witness the smacking

**Comment by oklews** [comment]
This seems like a design choice, tampering with it would reasonably damage it.

**Comment by newfren** [comment]
it definitely did not use to do this and there is already a loud sound when you open it

**Comment by TemporalOroboros** [comment]
> 
> 
> This seems like a design choice, tampering with it would reasonably damage it.

The cistern on toilets is meant to open for maintenance. There is no reason for it to be damaged beyond user error.
