### ISSUE TITLE
Cigars do not satiate nicotine cravings

### ISSUE THREAD

**Issue by JetBrody** [tgstation/tgstation#61124]
## Round ID:
[168751](https://scrubby.melonmesa.com/round/168751), tested in thunderdome but is round independent.

## Reproduction:

Smoking a cigar for an extended amount of time will cause you to crave nicotine at such a rate that the cigar itself will not satiate it, leading to withdrawal symptoms.

This happens even in the span of a singular cigar, before it has completed being smoked.

Step 1. Obtain Cigar
Step 2. Light
Step 3. Place into mouth
Step 4. Wait

Eventually withdrawls will kick in and you'll begin shaking and craving nicotine despite actively smoking.

Probably beyond the scope of this issue, but cigars also shouldn't *technically* cause lung damage as you do not inhale the smoke into your lungs.

**Comment by timothymtorres** [comment]
The code for normal cigs

https://github.com/tgstation/tgstation/blob/dffa8af41e964662e62044c375a12cbc56dd79ef/code/game/objects/items/cigs_lighters.dm#L127-L161

The code for cigars

https://github.com/tgstation/tgstation/blob/dffa8af41e964662e62044c375a12cbc56dd79ef/code/game/objects/items/cigs_lighters.dm#L501-L532

It appears the `smoketime` affects the `reagents` distribution.  This is the breakdown:

| Type  | Time | Nicotine | Nicotine ingested per min |
| ------ | ----- | --------- | ------------------- |
| Cigarette  | 6 mins | 15 | 5 |
| Premium Cigar | 11 mins | 25 | 2 |
| Cohiba Cigar | 20 mins | 40 | 2 | 
| Havannah Cigar | 30 mins | 15 | 0.5 | 

It looks like whoever determined the math for the reagent amount and smoketime messed up.

**Comment by necromanceranne** [comment]
this ones a little pesky because it's entirely due to how the addiction system currently works. constant exposure to nicotine will inevitably cause you to start craving it, regardless of how much is being injected per exposure, but it makes next to no sense that you'd become addicted to nicotine if you're puffing on a cigar due to how you actually use a cigar.

Basically, I think cigars shouldn't inject chems into you, that's the only reasonable solution to this beyond making a new reagent in place of nicotine or something.

**Comment by timothymtorres** [comment]
> Basically, I think cigars shouldn't inject chems into you, that's the only reasonable solution to this beyond making a new reagent in place of nicotine or something with a lower addiction rate. Which might be the only solution

I think that is overkill.  All we need to do is increase the nicotine amount in cigars so that there aren't withdrawal symptoms.

**Comment by timothymtorres** [comment]
I did some testing and code diving for this.  If `smokeall` isn't set to true then the default amount smoked is `REAGENTS_METABOLISM` which is 0.2

The drag rate is every 10 seconds.  So the math results in:

1 minute = 1.2 reagents ingested

The Havannah cigar runs out of nicotine before it is finished smoking.  The two other cigars have enough nicotine in them to last their entire duration.  This is a simple fix, just need to bump up the nicotine amount for the Havannah cigar and it solves the problem.
