### ISSUE TITLE
13 Loko is even more unhealthy than it should be.

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#61140]
Reproduction:

1. Take ONE SIP of 13 loko
2. it knocks you the fuck out

It didn't always used to be like this and this makes it basically invalid as a drink, I have the heavy drinker quirk on most of my characters too.  I used to like drinking the stuff occasionally but it just KOs you too much to be worth it.

**Comment by ATH1909** [comment]
did it INSTANTLY knock you out?

are you sure what you drank was 100% thirteenloko? it looks like the code for thirteenloko makes you recover from being unconscious faster, which is literally the opposite effect from knocking you out.

**Comment by NanoCats** [comment]
> did it INSTANTLY knock you out?
> 
> are you sure what you drank was 100% thirteenloko? it looks like the code for thirteenloko makes you recover from being unconscious faster, which is literally the opposite effect from knocking you out.

Behavior seems inconsistent, I signed on to test it and I drank some, nothing happened, but I did get knocked out (and get back up immediately) a couple times

**Comment by NanoCats** [comment]
EDIT: I have further tested it, this glitch is REAL

I've tried drinking one sip of 13 loko, and entire cans 


One sip sometimes knocks you out for a short period of time, but it does


also drinking one can is enough to damage your liver, interestingly. For the record I have both of the pro-drinker perks (heavy drinker and alcohol healing)
