### ISSUE TITLE
Bluespace trauma portals can be accessed via telekinesis

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#61145]
Reporting client version: 514.1561

## Round ID:
[168793](https://scrubby.melonmesa.com/round/168793)

## Testmerges:
- [[TESTMERGE ONLY UNTIL FREEZE ENDS]FAMILIES 4.0: "fuck it, MRP only this time"](https://www.github.com/tgstation/tgstation/pull/61123)
- [Downgrade Juke to 0.8.1](https://www.github.com/tgstation/tgstation/pull/61110)

## Reproduction:

Step one: subject yourself to something that might cause a trauma and gain access to the bluespace trauma

Step two: get telekinesis in some fashion

Step three: click on a portal that springs up from your trauma

Step four: gain even greater teleportation powers than the trauma normally allows.

**Comment by timothymtorres** [comment]
Can you describe the "gain even greater teleportation powers" that happens?

**Comment by TheBonded** [comment]
> Can you describe the "gain even greater teleportation powers" that happens?   

@timothymtorres The brain trauma they are referring to creates "portals", tears in reality that only the person with the brain trauma can see. They appear in random positions nearby you and spawn in pairs. Clicking on one will take you to the other one, which would be the teleportation powers. Generally you have to be next to them to interact with them, but telekinesis allows you to do it at any range, increasing the power of the teleportation abilities as you no longer need to reach the portals to see them.

**Comment by timothymtorres** [comment]
> > Can you describe the "gain even greater teleportation powers" that happens?
> 
> @timothymtorres The brain trauma they are referring to creates "portals", tears in reality that only the person with the brain trauma can see. They appear in random positions nearby you and spawn in pairs. Clicking on one will take you to the other one, which would be the teleportation powers. Generally you have to be next to them to interact with them, but telekinesis allows you to do it at any range, increasing the power of the teleportation abilities as you no longer need to be next to the portals to interact with them.

Thanks for the rundown.  Sounds like this needs a telekensis interact check for the portals to return false.  I'll take a look at this later tonight and see if I can find the relevant code procs needed.

**Comment by timothymtorres** [comment]
Here is the relevant code:

https://github.com/tgstation/tgstation/blob/a64b2599a572ebad15b02842a56a537f1be674c7/code/datums/brain_damage/special.dm#L111-L126

Looks like we need to add something like:

https://github.com/tgstation/tgstation/blob/d4fe4cf6d0156d5198ecbb1cdc8b28db9fe0aa76/code/modules/ruins/spaceruin_code/hilbertshotel.dm#L47-L49

And this should fix it.
