### ISSUE TITLE
Admin AI Interact Not working

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#61149]
Reporting client version: 514.1561

## Round ID:
[168806](https://scrubby.melonmesa.com/round/168806)

## Reproduction:

Not in build mode. Yes I'm in AI Interact Mode. I tried reconnecting and it didn't work. I also tried it on multiple doors. 
![VsDVFryTeZ](https://user-images.githubusercontent.com/37246588/131598737-97385056-5479-495a-a6a0-87c5db719d95.gif)

**Comment by LemonInTheDark** [comment]
Fixed by #61211 (Least I hope)
