### ISSUE TITLE
Layer adapters broke

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#61148]
## Round ID:
[168805](https://scrubby.melonmesa.com/round/168805)

## Reproduction:
See title.

**Comment by Ghilker** [comment]
Edit this to give more informations/pictures/reproduction steps or I'll close it

**Comment by LemonInTheDark** [comment]
Testmerge issue of #61141, fixed now.
Remember to link the involved testmerges in the right category, it makes this sort of issue sane to handle
