### ISSUE TITLE
suit sensor window is broken

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#61173]
## Round ID:
[168842](https://scrubby.melonmesa.com/round/168842)

## Testmerges:
#61123 #61141 

## Reproduction:
be someone who opens a suit sensor monitor console, window opens for a split second and dissapears into nothing
reconnecting fixes it only for it to dissapear once more

**Comment by timothymtorres** [comment]
@AlinaStarkova could this be related to #60693

**Comment by AlinaStarkova** [comment]
> @AlinaStarkova could this be related to #60693

*sigh* no. thats one of the windows ive tested and used multiple times. without issue. many other people are also fully capable of using it still as well. this sounds like an issue on his end

**Comment by AlinaStarkova** [comment]
> 
> 
> @AlinaStarkova could this be related to #60693

works fine as i said, its a problem on his end


https://user-images.githubusercontent.com/40489693/132343489-dcebc7b2-dbfe-4c1c-b50a-f47ab5f1e1a0.mp4

**Comment by FlamingCheese** [comment]
the issue has been resolved by some automatic update, i have tested on older versions and the console worked (before it was automatically fixed)
