### ISSUE TITLE
Slime management console hotkeys don't work

### ISSUE THREAD

**Issue by NamelessFairy** [tgstation/tgstation#61176]
## Reproduction: 
Go to xenobio, use a Slime management console, try one of the hotkeys, example used in this test was "Ctrl-click a slime to scan it.", Currently theres no output.

**Comment by kopoba** [comment]
From my investigation ctrl+click hotkeys dosent work but it work when you try using them near character. Wise coder from discord says its cause of this pr https://github.com/tgstation/tgstation/pull/60693 can you take a look @AlinaStarkova  ?

**Comment by AlinaStarkova** [comment]
> 
> 
> From my investigation ctrl+click hotkeys dosent work but it work when you try using them near character. Wise coder from discord says its cause of this pr #60693 can you take a look @AlinaStarkova ?

which discord? would be easier to discuss this there, however for reference, ive spoken to a maint with the details of the code, and my can_interact() refactor is not at fault

here is the AltClick proc for the xeno console
note how it sends a signal before calling the parent (the parent has the can interact proc, but thats irrelevent as the signal for the xeno console proc was already sent, that wont stop it)
```
/mob/living/simple_animal/slime/AltClick(mob/user)
    SEND_SIGNAL(user, COMSIG_XENO_SLIME_CLICK_ALT, src)
    ..()
```

and here is the proc the signal initiates, notice again, that it doesnt do a can_interact() check
```
/obj/machinery/computer/camera_advanced/xenobio/proc/XenoSlimeClickAlt(mob/living/user, mob/living/simple_animal/slime/S)
    SIGNAL_HANDLER
    if(!GLOB.cameranet.checkTurfVis(S.loc))
        to_chat(user, span_warning("Target is not near a camera. Cannot proceed."))
        return
    var/mob/living/C = user
    var/mob/camera/ai_eye/remote/xenobio/E = C.remote_control
    var/obj/machinery/computer/camera_advanced/xenobio/X = E.origin
    var/area/mobarea = get_area(S.loc)
    if(QDELETED(X.current_potion))
        to_chat(C, span_warning("No potion loaded."))
        return
    if(mobarea.name == E.allowed_area || (mobarea.area_flags & XENOBIOLOGY_COMPATIBLE))
        INVOKE_ASYNC(X.current_potion, /obj/item/slimepotion/slime.proc/attack, S, C)
```

**Comment by kopoba** [comment]
> which discord?
https://tgstation13.org/phpBB/viewforum.php?f=60

**Comment by AlinaStarkova** [comment]
> > which discord?
> https://tgstation13.org/phpBB/viewforum.php?f=60

i fixed the issue in the above linked PR already

just know: my can_interact() refactor had nothing to do with it. anturk was just talking crap without bothering to actually look at the code, it took me and and Lemons like 5 seconds of looking at the consoles code to know the issue

for reference: that one specific ctrl click hotkey actually never worked, for 3 years. lmao

**Comment by kopoba** [comment]
> 
> 
> > > which discord?
> > > https://tgstation13.org/phpBB/viewforum.php?f=60
> 
> i fixed the issue in the above linked PR already
> 
> just know: my can_interact() refactor had nothing to do with it. anturk was just talking crap without bothering to actually look at the code, it took me and and Lemons like 5 seconds of looking at the consoles code to know the issue
> 
> for reference: that one specific ctrl click hotkey actually never worked, for 3 years. lmao
Well its kinda strange ctrl click was working recently so i went down to see what pr touches xenocameras console and that road leads me to anturk and you and both was a mistake.
Excellent job in fixing this issue thank for help!
