### ISSUE TITLE
ants have outevolved chickens

### ISSUE THREAD

**Issue by maxymax13** [tgstation/tgstation#61188]
## Reproduction:
![image](https://user-images.githubusercontent.com/38844529/131782298-27b527a7-29ea-4b14-b89a-8f95bbf4172e.png)
laid eggs shouldnt decay, its almost impossible to have a chicken coop now since it just turns into an ant minefield

**Comment by Wallemations** [comment]
Yikes, I didn't think about this one. If the problem is the ants killing the chickens, it looks like someone else has that covered for me.

**Comment by maxymax13** [comment]
the problem is laid eggs decomposing and rotting before they can even hatch

**Comment by Wallemations** [comment]
> the problem is laid eggs decomposing and rotting before they can even hatch

Eggs can hatch? I've never farmed chickens in the game, I didn't have a clue. Would making eggs need to be picked up by a player before they begin to decompose fix the problem?
