### ISSUE TITLE
Slimes ventcrawling sends you to gem room

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#61187]
1. Spawn a slime. I spawned the random subtype
2. Drag yourself into it, and ventcrawl
3. Move around
4. After about a second, you'll teleport to the gem room

**Comment by Y0SH1M4S73R** [comment]
https://github.com/tgstation/tgstation/pull/61141#issuecomment-909821992

Issue probably stems from a TM'ed PR (You didn't mention which PR's were TM'ed in the issue body)

**Comment by Mothblocks** [comment]
Good catch--round #168865, and yes it had that test merge.

**Comment by MrMelbert** [comment]
Happens to any ventcrawlers. Extra mention to xenos, which spawn in vents, so spawn in the error room. Kyler said it was a bug of his TM when he was around.

**Comment by Timberpoes** [comment]
This PR has been un-TMed and doesn't look set for a full merge.
