### ISSUE TITLE
Dragging your sprite onto a stasis bed gives a 1-3 chance of you dropping slowly onto it

### ISSUE THREAD

**Issue by AlinaStarkova** [tgstation/tgstation#61197]
## Round ID:
found in local testing

## Reproduction:
just drag yourslf onto stasis, 1 in 3 times you will drop onto it slowly
its random, i could see it as a feature if it always occured, but it does it randomly, and im unsure of why

https://user-images.githubusercontent.com/40489693/131805176-43f7b523-2a2a-44a3-a807-50e8e43d046a.mp4

**Comment by ArcaneDefence** [comment]
This made me physically uncomfortable.

**Comment by remuluson2** [comment]
Looking through the possible causes now and it seems like its a problem with the drag behavior and holllly I wanted to fix this but drag mouse code is too much for me.
