### ISSUE TITLE
Ever since the transforming component refactor, e-swords are now invisible

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#61193]
Whether they're turned on or off, e-swords (including the chaplain's) are invisible.

**Comment by MrMelbert** [comment]
![image](https://user-images.githubusercontent.com/51863163/131793380-cd06caff-3636-41cf-abe8-f8c89b80cac0.png)
![image](https://user-images.githubusercontent.com/51863163/131793442-fd120a4d-623d-4c96-9612-a2490ff71949.png)
![image](https://user-images.githubusercontent.com/51863163/131793636-52ebd9be-8ca3-4ff7-8efa-5dc7683b7a73.png)

I can't seem to reproduce the invisible eswords, but you are right about the chaplain's, I forgot to update their icon states

**Comment by Mothblocks** [comment]
Strange, I must have been thinking of a weird subtype.

**Comment by necromanceranne** [comment]
I'll close this since the pr was merged
