### ISSUE TITLE
Toxins Airlock Freezes game

### ISSUE THREAD

**Issue by CourageTheCat** [tgstation/tgstation#61208]
## Reproduction:
1. Click on toxins airlock control
2. Everything becomes impossible to interact with, forcing me to restart the game.

**Comment by CourageTheCat** [comment]
This has happened on both tramstation, icebox, and metastation

**Comment by timothymtorres** [comment]
I know they gutted toxins and replaced it with ordnance labs now.  I haven't seen any other issue reports regarding this so whatever was causing it is likely gone.
