### ISSUE TITLE
Holoparasite scout mode takes lava damage

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#61212]
Reporting client version: 514.1561

## Round ID:
168918

## Testmerges:
- [Ports pollution from Skyrat (Ported by Gandalf2k15 from Horizon (Made by Azarak))](https://www.github.com/tgstation/tgstation/pull/61154)

## Reproduction:
1) Get a ranged holoparasite.
2) Go to lavaland in mining gear.
3) Have the holoparasite wander over lava a few times.
4) Take lots of damage and probably die.
This seems like unintended behavior, as the scout form is supposed to be able to invisibly and nonharmfully move around like a ghost.

**Comment by timothymtorres** [comment]
https://github.com/tgstation/tgstation/blob/213e84f091ccc06ede88b9020d918d0968f4e8d9/code/game/turfs/open/lava.dm#L49-L51

https://github.com/tgstation/tgstation/blob/213e84f091ccc06ede88b9020d918d0968f4e8d9/code/game/turfs/open/lava.dm#L135-L150

**Comment by SuperNovaa41** [comment]
thanks homie
