### ISSUE TITLE
The meteorgun has no effect on carbon mobs

### ISSUE THREAD

**Issue by NamelessFairy** [tgstation/tgstation#61244]
## Testmerges: 
#61205

## Reproduction:

spawn in /obj/item/gun/energy/meteorgun
shoot someone with it
It'll inflict no damage
I'm not sure if this is an issue with all meteor's or just the ones this gun fires

**Comment by necromanceranne** [comment]
I see what happened. When goof refactored explosions, he forgot to have a check for living mobs.
