### ISSUE TITLE
auxiliary base console shows only black even adding extra cameras will not change it

### ISSUE THREAD

**Issue by benman347** [tgstation/tgstation#61241]
## Round ID:
168994

## Reproduction:
use the generic base construction console
even if you add aditional cameras the cams view only shows black and its impossible to build with it

**Comment by TheBonded** [comment]
This round was on tramstation, which has a broken base construction console.

**Comment by benman347** [comment]
it happened on multiple rounds and stations for me ill check it now on meta.

**Comment by benman347** [comment]
169054 delta happened as well
![glitch_tg3](https://user-images.githubusercontent.com/62154137/132128802-90c3d2cb-cd5b-4de3-9d09-4e71b0e29491.PNG)

**Comment by benman347** [comment]
delta again ID 169056
