### ISSUE TITLE
A darkened window cannot be undarkened

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#61251]
## Reproduction:
1. Spray paint a window black. You won't see through it.
2. Spray paint a window white. You still won't be able to see through it.

**Comment by ArcaneDefence** [comment]
https://github.com/tgstation/tgstation/blob/060042feeef5af5300741c992931c3f30041dda7/code/game/objects/structures/window.dm#L308-L314

ADMIN LOG: is_dark_color: the reinforced window
lol

**Comment by Mothblocks** [comment]
lol

**Comment by Mothblocks** [comment]
that dm-lua check if first argument is source thing would come in handy right about now

**Comment by Mothblocks** [comment]
@Time-Green What do you mean not a good first issue? It's literally one extra argument and it's done

**Comment by Time-Green** [comment]
I thought the “good first issue” was meant for someones first issue, figured it was a mistake

**Comment by Mothblocks** [comment]
No worries!

**Comment by ATH1909** [comment]
did you try cleaning them instead of spray painting them a second time

**Comment by Mothblocks** [comment]
no but the lighter spray  can should clear it up
