### ISSUE TITLE
Arcade Game Dupe

### ISSUE THREAD

**Issue by AxolotlGod** [tgstation/tgstation#61290]
Reporting client version: 514.1557

## Round ID:
[169203](https://scrubby.melonmesa.com/round/169203)

## Reproduction:
Essentially, if you click on the Orion Trail arcade game win screen fast enough you can dupe arcade loot. This could only really be done with an auto clicker consistently. I found it out due to my mouse having a double click issue.

**Comment by TheBonded** [comment]
Duplicate of https://github.com/tgstation/tgstation/issues/59677#issuecomment-864160453
