### ISSUE TITLE
Discussions about the development process Improve the bureaucracy system #61323 

### ISSUE THREAD

**Issue by twilightwanderer** [tgstation/tgstation#61325]
This question is open to discuss a number of issues that arise during the development of this PR #61323.
At this point, the questions are as follows:

- [ ] List of forms

I suggest using forms like this (I look forward to your suggestions):
**Command**
	NT-CMD-JA Job application
	NT-CMD-JT Job termination
	NT-CMD-JR Job reassignment
	NT-CMD-C Complaint form
	NT-CMD-O Order form
	NT-CMD-PH Permit to perform hazardous work
**Security**
	NT-SCR-W Warrant 
	NT-SCR-SW Search warrant 
	NT-SCR-IR Interrogation Report
	NT-SCR-SR Security Report 
	NT-SCR-TR Trial report
	NT-SCR-EO Execution order
	NT-SCR-PP Permission to possess
**Engineering**
	NT-ENG-PW Permission to perform non-standard work
	NT-ENG-PE Permit for the issuance of engineering equipment
**Research**
	NT-RSH-PR Permission to perform non-standard research
	NT-RSH-PE Permit for the issuance of research equipment
**Medical**
	NT-MDC-MP Medical prescription
	NT-MDC-AR Autopsy report
	NT-MDC-DC Death Certificate
**Supply**
	NT-SPL-PO Permission to execute a non-standard order
**Other**
	NT-LB Lunch bill
	NT-PS Provision of paid services

- [ ] Ability to use graphics in the forms. 

The <img> tag allows you to use all possible graphics to increase interactivity. You can put logos, maps and other things in it.

**Comment by Fikou** [comment]
move this to the pr itself, issues are not for feature requests/discussions
