### ISSUE TITLE
Atmostechs do not have access to atmos on icebox

### ISSUE THREAD

**Issue by Edelor68** [tgstation/tgstation#61339]
As the title says: Atmostechs cant get into the main atmos area. Every other area, like incinerator, works just fine.

**Comment by AlinaStarkova** [comment]
atmostechs have access to literally every door on icebox that is their atmos room, the only door they lack access is this one maint door you can get in from every other door

![image](https://user-images.githubusercontent.com/40489693/132899268-ebf38b0a-9922-4afc-9fe4-ad39f062f874.png)
