### ISSUE TITLE
Spawning a map in causes the area filled to be pitch black

### ISSUE THREAD

**Issue by Seris02** [tgstation/tgstation#61349]
## Reproduction:

1. (unsure if it's just with uploaded maps or with all maps) Use the debug verb "Map Template - Upload" to upload a map
2. Use the "Map template - Place" verb to place the map
3. Everything in the area that the map covers will now be pitch black (ie, no lighting.)

**Comment by Mooshimi** [comment]
#61730 was merged, so this can be closed now
