### ISSUE TITLE
lighting is weird in certain areas

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#61340]
## Round ID:
[169303](https://scrubby.melonmesa.com/round/169303)

## Testmerges:
#61246 

## Reproduction:
holodeck, hyperspace and shuttles like the white ship all have bugged out lighting and lights inside them do not work
asteroid rock on kilo might also be affected by this bug
![bugged lighting](https://user-images.githubusercontent.com/75639936/132760023-dc7c1ae0-2d65-47a5-b049-46334bf4e9c1.PNG)

**Comment by Mooshimi** [comment]
seems related to #61349

**Comment by timothymtorres** [comment]
@FlamingCheese are you sure this isn't ghost vision?  Your SS doesn't reveal any problems that I can see.  When you say that lighting doesn't work, do you mean for items?  How did you test this?

**Comment by FlamingCheese** [comment]
> 
> 
> @FlamingCheese are you sure this isn't ghost vision? Your SS doesn't reveal any problems that I can see. When you say that lighting doesn't work, do you mean for items? How did you test this?

the last time i saw the unlit holodeck was on the kilostation round that was listed in the round id
otherwise if you where to build mode and remove a wall in a fullbright area like the thunderdome the tile the wall was on would not be lit

**Comment by Mooshimi** [comment]
> @FlamingCheese are you sure this isn't ghost vision?  Your SS doesn't reveal any problems that I can see.  When you say that lighting doesn't work, do you mean for items?  How did you test this?

Holodeck is unlit every round on Sybil after you choose a map for it.
