### ISSUE TITLE
Headslugs that take over monkey humans, get randomized names upon transforming to stored dna

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#61342]
Reporting client version: 514.1561

## Round ID:
[169312](https://scrubby.melonmesa.com/round/169312)

## Testmerges: 61246
- [Adds an admin signal handler circuit component](https://www.github.com/tgstation/tgstation/pull/61246)

## Reproduction:
1. Become headslug
2. Lay egg in monkey human
3. Come out, turn into a monkey upon coming back to life and die for no reason whatsoever
4. Turn to human form
5. try and transform
6. you now have a random name, but simular appearance to the dna you absorbed, if you have a real id it will now read the random names name, somehow.

**Comment by necromanceranne** [comment]
That last bit suggests jank, so this is definitely bugged.

**Comment by Sealed101** [comment]
could not reproduce
