### ISSUE TITLE
yet another way to create a one-shot bullet

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#61357]
from gunpoint code:
```
	if(weapon.chambered && weapon.chambered.loaded_projectile)
		weapon.chambered.loaded_projectile.damage *= damage_mult
		if(weapon.chambered.loaded_projectile.wound_bonus != CANT_WOUND)
			weapon.chambered.loaded_projectile.wound_bonus += damage_mult * GUNPOINT_BASE_WOUND_BONUS
			weapon.chambered.loaded_projectile.bare_wound_bonus += damage_mult * GUNPOINT_BASE_WOUND_BONUS

	if(weapon.check_botched(shooter))
		return

	var/fired = weapon.process_fire(target, shooter)
	if(!fired && weapon.chambered?.loaded_projectile)
		weapon.chambered.loaded_projectile.damage /= damage_mult
		if(weapon.chambered.loaded_projectile.wound_bonus != CANT_WOUND)
			weapon.chambered.loaded_projectile.wound_bonus -= damage_mult * GUNPOINT_BASE_WOUND_BONUS
			weapon.chambered.loaded_projectile.bare_wound_bonus -= damage_mult * GUNPOINT_BASE_WOUND_BONUS
```
```
/obj/item/gun/proc/check_botched(mob/living/user, params)
	if(clumsy_check)
		if(istype(user))
			if(HAS_TRAIT(user, TRAIT_CLUMSY) && prob(40))
				to_chat(user, span_userdanger("You shoot yourself in the foot with [src]!"))
				var/shot_leg = pick(BODY_ZONE_L_LEG, BODY_ZONE_R_LEG)
				process_fire(user, user, FALSE, params, shot_leg)
				SEND_SIGNAL(user, COMSIG_MOB_CLUMSY_SHOOT_FOOT)
				user.dropItemToGround(src, TRUE)
				return TRUE
```
🤔

**Comment by TemporalOroboros** [comment]
Ah. Donksoft tasers.

**Comment by timothymtorres** [comment]
what is the problem?

**Comment by ATH1909** [comment]
> what is the problem? Is the one-shot bullet like an instant kill? I looked at the code you showed but I don't really see what is supposed to be a bug

basically, from what I can tell, if a clumsy person rolls that 40% chance to shoot themself in the foot while holding someone at gunpoint but fails to actually fire the gun at their foot due to something like pacifism, the projectile currently loaded in the gun will keep the gunpoint multipliers. said pacifist clown can then hand the gun off to someone who can properly use it or try to roll again for a bigger modifier.

**Comment by tralezab** [comment]
check botched isn't the problem because both the botch and the fire proc shoot the gun. the problem would be pacifism cancelling the shot after the buff.

Also for some reason I wasn't even unable to start a holdup so someone's gotta figure that bug out before we can even try with this

**Comment by TheBonded** [comment]
Doesn't the traitor chef's meathook reuse the projectile?

> It looks like the only way this could work is with reusable projectiles. Both code paths fire the weapon. Fortunately the reusable projectiles (foam darts and arrows) technically re-create the casing instead of recycling the old one so they shouldn't accumulate damage.

**Comment by SuperNovaa41** [comment]
Just tested, this actually does not happen. After shooting my self in the foot while having pacifism, the resulting bullet was NOT in fact a one shot bullet.

**Comment by timothymtorres** [comment]
> Just tested, this actually does not happen. After shooting my self in the foot while having pacifism, the resulting bullet was NOT in fact a one shot bullet.

I think the way it's worded, you need to attempt to shoot somebody else while having the clown clumsy trait and pacifism and the gun won't fire.  This then gives a big damage boost to the next shot fired when the gun is handed over to another person to use it.  I'd recommend double checking this @SuperNovaa41 and comparing the damage values.  Someone also mentioned it's not always a guaranteed chance, so you might have to do test it several times to be sure.
