### ISSUE TITLE
Door Id's misslabeled?

### ISSUE THREAD

**Issue by Eldeen** [tgstation/tgstation#61364]
Reporting client version: 514.1557

## Round ID:
[169352](https://scrubby.melonmesa.com/round/169352)

## Reproduction:
I was floating around as a ghost on delta when I clicked on the brig door: "Its maintenance panel is screwed in place."
"This airlock cycles on ID: brig-entrence." Seems like the airlock id is misspelled entrence when it should be entrance. Other doors on the station had the same problem:

This airlock cycles on ID: perma-entrence.
This airlock cycles on ID: sci-entrence.

Probably just a misspelling somewhere in the code so I imagine it will affect the other stations as well.

**Comment by AlinaStarkova** [comment]
my mispelling yes cuz not a native english speaker, but for clarification, these IDs are internal, all the code is checking is that it matches the string with another airlock, the spelling therefore doesnt matter, you can actually build these airlocks in game with an RCD set to cycle on ID "asfgbh22AJAbf92" if you REALLY want to, as long as it matches with another airlock

the reason i made this internal ID visible on examine is so engineers can fix airlocks that cycle in game by making a new airlock set to the same string
