### ISSUE TITLE
Replacing a roundstart surplus prosthetic limb with a robotic one can have the sprite changed back upon removing your jumpsuit

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#61386]
## Reproduction:

Bit of a long one I know, but I have pictures to explain.

My character has the trait that randomly replaces a limb with a surplus prosthetic limb. I usually get this replaced at robotics at some point in the round, but I've noticed that removing/wearing a jumpsuit seems to reset the sprite back to looking like a surplus limb. As far as I can tell, it functions normally as a robotic limb, so it might just be a visual error? Witnessed this over multiple rounds.

Replaced limb:
![dreamseeker_rsZZz6sy0v](https://user-images.githubusercontent.com/33107541/132939783-4200de3c-d4a6-4cd8-8db5-daf935366631.png)![dreamseeker_Xr5N3DPfPS](https://user-images.githubusercontent.com/33107541/132939786-03d1f683-fc82-46f1-95b3-6fdc9d044672.png)
After removing the jumpsuit:
![dreamseeker_rYlezDy3R6](https://user-images.githubusercontent.com/33107541/132939797-cba7e88f-0c53-4a5e-aa74-54ff20699b82.png)![dreamseeker_q0mTs1yEAU](https://user-images.githubusercontent.com/33107541/132939798-299d367f-3a51-4df5-811e-3dca35c00242.png)

EDIT: And yes, it persists after re-equiping the jumpsuit.

Really is a shame, the robotic one looks much cooler, especially on the back.

**Comment by Sealed101** [comment]
can no longer reproduce after multiple dressup sessions
