### ISSUE TITLE
0 hours players with no entry in the database cannot connect to fill out a panic bunker interview

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#61383]
## Reproduction:

A 0 hour player with a database entry (someone who connected, but has 0 hours played, or nothing tracked, or something of that variety?) can connect to a server with panic bunker enabled and fill out an interview just fine.

A 0 hour player who has never connected to the servers before (and has no database entry) cannot connect to a server with panic bunker enabled to fill out an interview. They are kicked by the panic bunker before they get the option to complete an interview to bypass the bunker. Kind a a bummer, eh?

**Comment by timothymtorres** [comment]
This appears intended.

https://github.com/tgstation/tgstation/blob/3f13258e1fed4aa1ecf18b105538d36a60ac6dbc/config/config.txt#L360-L373

**Comment by MrMelbert** [comment]
I'm relatively certain this is not intended because it's set to 0 on /tg/ servers, and yet 0 hours players cannot join.

**Comment by Mooshimi** [comment]
> This appears intended.
> 
> https://github.com/tgstation/tgstation/blob/3f13258e1fed4aa1ecf18b105538d36a60ac6dbc/config/config.txt#L360-L373

I was told that the config in the code files doesn't necessarily match what's in the server config
