### ISSUE TITLE
Viruses that spread via touch can be spread through a full Plasmaman Envirosuit

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#61423]
## Reproduction:

Playing as a plasmaman virologist, and I gave myself an Inorganic Biology virus allowing the effects of the virus to effect me. Transmission stat was at 8, allowing the virus to spread via touch.

Upon grabbing a monkey, I noticed via the Health HUD that the monkey was instantly infected, despite my plasmaman wearing a full envirosuit (helmet, gloves, suit) which is supposedly fully sealed as to not cause a fire/leak of plasma from the suit. So how exactly does this make sense?

I haven't played around with touch viruses as a human to notice this, but either this is just an issue regarding viral protection from plasmamen gear, or maybe this issue affects every instance with protective clothing. Dunno. I'll either update this issue or make a new one if I find out.

**Comment by timothymtorres** [comment]
So after code diving I found the following:

https://github.com/tgstation/tgstation/blob/c9f2a80205c11ee72b456545b0c5cf49cdba082c/code/game/objects/items.dm#L116-L117

https://github.com/tgstation/tgstation/blob/78ddc220374aedfe542c1c6d5fcbb24c49797fed/code/modules/clothing/gloves/plasmaman.dm#L1-L12

https://github.com/tgstation/tgstation/blob/4e2a36fe7e56fad93495adf01c697f4b5de04e90/code/datums/diseases/_MobProcs.dm#L148-L149

All touch based diseases use the `permeability_coefficient` variable to determine spread.  Airborne diseases use the `armor = list(BIO = 100)` variable to determine spread.

It appears that a plasmaman's envirsuit does not have `permeability_coefficient` set and this only applies for their gloves.
