### ISSUE TITLE
Goldgrubs can fly

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#61425]
## Testmerges:
The following pull requests are currently test merged:
#61123: 'FAMILIES 4.0: "fuck it, MRP only this time"' by Iamgoofball at commit 5c69a20cbd

## Reproduction: 
https://puu.sh/IaLZP/4afcb2b517.png

Found this goldgrub while I was flying around. Possible it was spawned here? No idea! Definitely should be falling down, though.

**Comment by TemporalOroboros** [comment]
Not a bug. The turf below it is a solid ice/rock wall and you can stand on those.

**Comment by ATH1909** [comment]
they fly now?

they fly now.

**Comment by Time-Green** [comment]
thanks for the report and keep up the good work, but it's not a bug (sadly no flying goldgrub)

**Comment by TheBonded** [comment]
if this is marked as not a bug, sadly, why is it still open? we have so many open issue reports, no need to have non bugs clogging it up

**Comment by Time-Green** [comment]
I thought I closed it, oops
