### ISSUE TITLE
Autolathes can't print plates.

### ISSUE THREAD

**Issue by EuSouAFazer** [tgstation/tgstation#61431]
Issue found by Jim Yanggao on the manueldiscord, who "will just bitch about it and not sign up for another thing to forget passwords to" when asked if they've opened an issue report about it.

Reasoning:
">autolathe can't print plates
>only bowls and every other kind of cookery"

You're welcome Jim.

**Comment by LemonInTheDark** [comment]
Tell jim to nut up and make a github account, or otherwise to stop complaining. Telephone issues like this are ok for small things, but are totally non functional for issues of any level of complexity.
