### ISSUE TITLE
You can teleport with skateboard multi-z bug 

### ISSUE THREAD

**Issue by KittyNoodle** [tgstation/tgstation#61436]
## Reproduction:

1.
Get a skateboard over a multi-z hole(best done with tram rail), note that you must fall off, the best way to do this is to Ollie unto the tram rail and fall off from the stam damage. 

2.
Go back to the now levitating skateboard and buckle yourself to it again(if you cannot the main glitch has already occurred, however you should probable know that already).

3.
You will now fall down, but you will have the ability to Ollie, with no board(at first I thought this was some harmless thing, but then)

4.
Now, pull(DO NOT OICK UP THE BOARD, doing so will break the glitch, making the Ollie ability do nothing) the board to a non hole area(if you attempt to ride the board at any point you will notice you are unable too, this is because the game thinks you are on the board, leading to the following insanity).

5.
Finally, all you need to do is press the ollie ability button and voila, you are teleported to the skateboard’s location for the low price of 30 stamina damage.

**Comment by Sealed101** [comment]
no longer reproduceable by the virtue of better movement handling; no actual buckling is made and no actions end up being granted
