### ISSUE TITLE
stamcritting yourself with rocket gloves can make you permanently slow without admin intervention

### ISSUE THREAD

**Issue by Kylerace** [tgstation/tgstation#61449]
## Round ID:
[169575](https://scrubby.melonmesa.com/round/169575)

## Testmerges:
#61419
#61316
#61313 

## Reproduction:
landing a rocket gloves tackle and stamcritting yourself at the same time can somehow keep the aggressive grab movespeed modifier on indefinitely

**Comment by necromanceranne** [comment]
@Ryll-Ryll Any ideas why?
