### ISSUE TITLE
harmbaton doesnt stun

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#61458]
Round ID: 169349, but all rounds now

Testmerges: Pretty sure it started after this update:
https://i.imgur.com/QFPIOXw.png

Reproduction: https://streamable.com/06joab

Harmbaton no longer stuns, it only beats. Ordinarily harmbaton is supposed to stun on the same cooldown as normal baton, but allow you to also use it as a beatstick in between the cooldown.

**Comment by Jamarkus127** [comment]
sounds like the game balanced itself.

**Comment by TheBonded** [comment]
a pr fix is already up at https://github.com/tgstation/tgstation/pull/61418 as of 4 days ago, 3 days before this issue report was posted

**Comment by SinfulBliss** [comment]
> a pr fix is already up at #61418 as of 4 days ago, 3 days before this issue report was posted

oh ok. i posted the bug in the discord like 4 days ago but forgot to make the bug report so went ahead and made one for good measure

**Comment by TheBonded** [comment]
> > a pr fix is already up at #61418 as of 4 days ago, 3 days before this issue report was posted
> 
> oh ok. i posted the bug in the discord like 4 days ago but forgot to make the bug report so went ahead and made one for good measure

it's always good to keep bugs documented on github, so it's good that you did that. I was just making sure it's known that this bug is being fixed so it doesn't end up just like all the other old issue reports than are fixed but never get closed
