### ISSUE TITLE
The character setup menu will sometimes bluescreen, and all your preferences will be reset, including ooc color and keybinds

### ISSUE THREAD

**Issue by o0cyann0o** [tgstation/tgstation#61459]
## Round ID:
[169622](https://scrubby.melonmesa.com/round/169622)

## Testmerges:
#61316 
#61419 

## Reproduction:
Seemingly at random, for some people **all** preferences will be deleted and they will be unable to open up their character setup menu entirely. Joining the round anyways will force you to play as a randomname. The round after I experienced this bug, I (and some others) had their prefs restored, but others suddenly encountered the same issue.

**Comment by Yenwodyah** [comment]
#61313

**Comment by Mothblocks** [comment]
Your savefiles still exist and nothing is being reset. That's the problem.

There's a few of these from separate files. As you can see the error behind them is completely fucking useless.

![image](https://user-images.githubusercontent.com/35135081/133363867-9948a6b4-6c3b-47ff-9696-5e45e8c3be5e.png)

However, the lines all of them point to are in the form of `new /savefile(path)`.

`path` is correct--I've confirmed this through VV. However, for whatever reason, it is refusing to actually *read* them. This is doubly confirmed by the fact the last updated times for the preferences are from *before* the bug happened.

I suspect something on the actual server boxes are causing problems, and I contacted @MrStonedOne about it, but they are presently offline. It doesn't make sense that the new preferences menu wouldn't be involved, but I genuinely cannot find anything that points to it. 

Compound this with the fact the CDN is now constantly failing, with Manuel saying that it's not even *enabled*, when preferences menu didn't touch this code at all.

**Comment by Mothblocks** [comment]
![image](https://user-images.githubusercontent.com/35135081/133369985-31a5c528-9b6a-4120-8552-fcfdacc8ddc2.png)

More confirmation to me that this is just horrifically bad timing--for whatever reason the server can't actually access the files it needs to.

**Comment by MrStonedOne** [comment]
The cdn is not in fact enabled. It was disabled during the random forum/website downtime we had a month ago and i never re-enabled it.

The save file bug might be with the files not getting closed properly, i'll go check the code for this to see if you accidentally removed a critical line in the refactor,

**Comment by Mothblocks** [comment]
Should be fixed by #61469
