### ISSUE TITLE
Preferences machine broke

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#61466]
![image](https://user-images.githubusercontent.com/14065903/133374021-588026ad-2e35-42b8-949e-1100d650df05.png)

**Comment by NanoCats** [comment]
I was on the main menu!

**Comment by LemonInTheDark** [comment]
Issue with the cdn. Not an us problem

**Comment by NanoCats** [comment]
> Issue with the cdn. Not an us problem (Maybe. could be moth fucked something up. I can't tell, too much shit breaking)


People are always like "POST YOURE ISSUE ON THE GITHUB" there is literally no winning

**Comment by LemonInTheDark** [comment]
Nah it's worth documenting. I say that just because we've been getting hit by a lot of "prefs menu broke everything forever" and I'm trying to keep moth from burning out

**Comment by Mothblocks** [comment]
Should be fixed by #61469
