### ISSUE TITLE
Cannot bind keys to "CTRL" with the new preferences menu

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#61463]
## Reproduction:

My keybinds got reset, and it changes my block movement key (CTRL) back to (ALT). Now, whenever I try to swap it BACK to (CTRL), it doesn't set - it highlights green, then returns to the previous bind when clicked off

**Comment by Mothblocks** [comment]
This one's a legitimate oversight.

**Comment by Mothblocks** [comment]
It's because I forgot these keys can be bound on their own, so I made it so they only work as modifiers.
