### ISSUE TITLE
Air injectors don't check for distance when you alt-click or ctrl-click them.

### ISSUE THREAD

**Issue by Pickle-Coding** [tgstation/tgstation#61462]
## Round ID:
N/A

## Reproduction:
Look for an air injector, or place and secure one, then ctrl-click or alt-click to toggle it.

**Comment by timothymtorres** [comment]
Have you tested this with the other pipe items like pumps, valves, etc?

**Comment by timothymtorres** [comment]
This was fixed with #61211.  Apparently `can_interact()` was refactored recently and introduced this bug to a lot of machinery that let someone use it from far away.
