### ISSUE TITLE
As of the new preferences menu the TGUI pinpointer thing appears where it shouldn't

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#61465]
![image](https://user-images.githubusercontent.com/14065903/133367712-4ca13389-0eaa-4dc3-b0a7-62b32a64dafb.png)

![image](https://user-images.githubusercontent.com/14065903/133367724-2c30e581-d574-407f-8829-8e952b19221b.png)

UPDATE: 

I figured it out
the crosshair shows up wherever a ) is meant to

**Comment by Mothblocks** [comment]
It's basically assuredly a CDN bug, which is confusing considering Manuel didn't even report the CDN as *on*.

**Comment by Mooshimi** [comment]
> It's basically assuredly a CDN bug, which is confusing considering Manuel didn't even report the CDN as _on_.

This is fixed now, right?

**Comment by Mothblocks** [comment]
yes i just keep forgetting about this
