### ISSUE TITLE
ninjas aren't immune to their own emps

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#61485]
![image](https://user-images.githubusercontent.com/42606352/133507419-676cc217-f349-40b2-aa5b-d0d93cff28d9.png)

**Comment by IndieanaJones** [comment]
That's probably not what's happening here.  This is an old bug with the suit getting a perm cooldown which was supposed to be fixed.

**Comment by Fikou** [comment]
this is intended
