### ISSUE TITLE
Ambience / Ship Ambience toggle was not respected in game when toggled midround

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#61495]
Reporting client version: 514.1557

## Round ID:
[Round ID]: #169672

## Testmerges:
- [Disable lobby music until sound preferences are re-added to the top bar menu.](https://www.github.com/tgstation/tgstation/pull/61467)
- [Cache savefiles just for a tick, likely fixing savefile misses](https://www.github.com/tgstation/tgstation/pull/61469)

## Reproduction:

My ambience and ship ambience toggles were toggled on due to the save file errors, so I turned them back off. But, even after toggling both off again, I still continued to hear ambience.

**Comment by timothymtorres** [comment]
Could it be that the ambience was still playing the rest of the song?  Maybe it just disables new ambience sounds from playing but the current one must finish.
