### ISSUE TITLE
Ghosts can force people to ready up/observe

### ISSUE THREAD

**Issue by JohnFulpWillard** [tgstation/tgstation#61508]
## Reproduction:

Observe a round
Observe a player with auto-observe on (to see their ui)
click Ready/Not ready/Observe and it'll affect them.

https://user-images.githubusercontent.com/53777086/133661299-62e3e046-a915-4c3d-9fce-2a4bc15506fe.mp4

**Comment by TheBonded** [comment]
can you change their character as well?

**Comment by Mooshimi** [comment]
> ## Round ID: Locally tested
> ## Testmerges:
> ## Reproduction:
> Observe a round
> Observe a player with auto-observe on (to see their ui)
> click Ready/Not ready/Observe and it'll affect them.
> 
>  Untitled.mp4

have you tested this outside of being adminned

**Comment by interestingusernam3** [comment]
Hackerman

**Comment by Mooshimi** [comment]
fixed by #61509
