### ISSUE TITLE
Midround Wizard antagonist preference unable to be selected

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#61533]
Reporting client version: 514.1557

## Round ID:
[169790](https://scrubby.melonmesa.com/round/169790)

## Testmerges:
- [[TM Candidate] Overhauls orbit and POI code to fix part of issue #61508 where players could observe /mob/living/new_player on the lobby.](https://www.github.com/tgstation/tgstation/pull/61509)
- [Disable lobby music until sound preferences are re-added to the top bar menu.](https://www.github.com/tgstation/tgstation/pull/61467)

## Reproduction:

- Midround Wizard shows up as toggled off. 
- Opt into midround wizard. It appears toggled on.
- Press [x] close the window.
- Re-open preferences. Midround Wizard still shows up as toggled off.

https://user-images.githubusercontent.com/51863163/133866845-65c731d2-1446-422e-a7e7-f20d5ff504e4.mp4

**Comment by newfren** [comment]
just checked and you also cannot turn it off

**Comment by newfren** [comment]
Also a problem for:
Midround:
Abductor, Blob, Xenomorph, Revenant, Space Ninja
Roundstart:
Traitor, Blood Brother, Changeling, Cultist, Malf AI, Monkey, Nuke Op, Wizard
Latejoin:
All seem to work

**Comment by Mothblocks** [comment]
i've checked all the roundstarts before and they worked, wonder what regressed

**Comment by Mothblocks** [comment]
Yeah I'm able to set traitor and such just fine, though not midround wizard.
