### ISSUE TITLE
Lighting bug on beach away mission

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#61558]
Reporting client version: 514.1561

## Round ID:
[169848](https://scrubby.melonmesa.com/round/169848)

## Testmerges:
- [[TM Candidate] Overhauls orbit and POI code to fix part of issue #61508 where players could observe /mob/living/new_player on the lobby.](https://www.github.com/tgstation/tgstation/pull/61509)
- [Test merge pr to disable admin profiler access](https://www.github.com/tgstation/tgstation/pull/60583)

## Reproduction:

Beach gateway mission loaded on Basil. The away mission for players was not lit.

**Comment by ProfessorSniff** [comment]
i think i tested away missions on local once, and they all had broken lighting

**Comment by Mooshimi** [comment]
Can we have someone see if away mission lighting is also fixed?

**Comment by ProfessorSniff** [comment]
Tested on local, away mission lighting does not appear to be fixed.
