### ISSUE TITLE
RMB with crowbar opens and closes a firelock in quick succession

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#61555]
## Reproduction:
Have a closed firelock -> Apply crowbar with right click -> Firelock opens and immediately closes instead of opening.

**Comment by LemonInTheDark** [comment]
Man this is stupid. Wonder if we even need the right click functionality anymore. ahhhhhh

**Comment by panvxv** [comment]
Seems more like a feature than a bug. This can help when you want to crush someone with firelock, way better than left spam click on firelock.

**Comment by vincentiusvin** [comment]
Its intentional #57943

**Comment by LemonInTheDark** [comment]
is it? the old behavior was tied to a 8 second process loop, and this is close to instant

**Comment by vincentiusvin** [comment]
Apologies, I hopped into this report too quickly without properly reading and testing it.
Problem related to the secondary attack not cancelling the attack chain and calling the primary attack. #61038
