### ISSUE TITLE
Analyzer always shows plasma

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#61559]
## Round ID:
Not relevant

## Reproduction:
Activate analyzer in hand.
It shows plasma, none in the air in the stats, but showing it seems unintended? 
![image](https://user-images.githubusercontent.com/85910816/133912263-8e8f5cfb-916b-43e8-92cb-e64c8802c0af.png)

**Comment by Mooshimi** [comment]
Now that I look at it, this may also be the case for CO2

**Comment by LemonInTheDark** [comment]
Where was this?

**Comment by LemonInTheDark** [comment]
Ah right this is how this works

**Comment by Mothblocks** [comment]
intentional, ever since https://github.com/tgstation/tgstation/pull/16401

**Comment by LemonInTheDark** [comment]
Technically intended, if very weird. See https://github.com/tgstation/tgstation/blame/e53061ae54d0f4783210ad768bf5fff38e95143a/code/game/objects/items/devices/scanners.dm#L593

It's partially a side effect of how gases used to work, see GLOB.hardcoded there. Partially just weird behavior that we keep around for reasons

Damn it mothblocks
