### ISSUE TITLE
Intelligence Potion ghost role menu not popping up for some players.

### ISSUE THREAD

**Issue by Thunderfleece** [tgstation/tgstation#61561]
Reporting client version: 514.1561

## Round ID:
 [169861](https://scrubby.melonmesa.com/round/169861)

## Reproduction:
Several people in deadchat noticed that when the xenobiologist was offering intelligence potions, several members of the ghosts never got a notice to become the intelligent mob.
Mr. Melbert tried to intelligence potion cats in the Thunderdome to test after this was noticed and several ghosts did not get a message.
We were getting notifications for other ghost roles such as ashlander eggs and positronic brains.

Only thing we could think of is preferences being bugged somehow since I know I hit 'not for this round' on anomaly slimes a day or two prior. And maybe that just, never retoggled?

**Comment by ANAME593** [comment]
i believe this is a preference issue basically preferences were reworked and sentience potion spawn doesn't come up for you to enable this round i had 2 sentient mobs, maybe whoever reworked preferences should add the sentience potion spawn in the antag menu

**Comment by newfren** [comment]
the preferences update might have set this to off? I noticed in my ghost preferences that it was the only thing switched off where I've had it on before.

**Comment by TheBonded** [comment]
Could this have something to do with https://github.com/tgstation/tgstation/issues/38315?
