### ISSUE TITLE
Explosive lances wrong sprite when dual wielded

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#61560]
Reporting client version: 514.1561

## Round ID:
[169860](https://scrubby.melonmesa.com/round/169860)

## Testmerges:
- [[TM Candidate] Overhauls orbit and POI code to fix part of issue #61508 where players could observe /mob/living/new_player on the lobby.](https://www.github.com/tgstation/tgstation/pull/61509)
- [Change preference cache from addtimer to spawn, ideally preventing the savefile bug from happening pre-init](https://www.github.com/tgstation/tgstation/pull/61536)

## Reproduction:
Hold an explosive lance. See c4 on lance. Dual wield. See it is now gone. Drop on ground and it is still gone. It doesn't go back to correct until you un-dual-wield the lance.

**Comment by itseasytosee** [comment]
Still an issue, only happens with crafted explosive lances rather than admin spawned ones for some god forsaken reason.

**Comment by Sealed101** [comment]
you can no longer craft an explosive lance as of #71256 and adminspawnned lances seem to have no sprite issues described in the issue
