### ISSUE TITLE
Tramstation Bar is completely Exposed to station depressurization events. 

### ISSUE THREAD

**Issue by Zytolg** [tgstation/tgstation#61577]
## Reproduction:

Basically, punch a hole that breaches the West Section of Tramstation. Watch as significant areas w/o firelocks are depressurized. 
This is a quick and easy fix for those who might want to dive into mapping. Open up your editor of choice, and add firelocks making sure to close off areas that multi-z exposes to the elements.

**Comment by KittyCatMeowMeow** [comment]
Could you possible add a picture to which areas that will get depressurized? Or just say which large areas if you can.

**Comment by san7890** [comment]
I don't know if this is still an issue in a post #63492 world.

**Comment by san7890** [comment]
oh thank fuck it's finally dead
