### ISSUE TITLE
Chat tabs sometimes reset

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#61575]
See title, my OOC chat tab has dissapeared several times this day, resetting the main chat tab to default.

**Comment by Mothblocks** [comment]
not a new bug but i've been getting this a lot as well, especially recently when i wasnt getting it before

**Comment by Mooshimi** [comment]
same

> not a new bug but i've been getting this a lot as well, especially recently when i wasnt getting it before

**Comment by TiviPlus** [comment]
Can confirm happens on tgmc too usually after I try to run a tg server locally in the background while being connected to tgmc

**Comment by Sealed101** [comment]
dupe of #52997 actually honk honk

**Comment by Mooshimi** [comment]
> dupe of #52997 actually honk honk

ok

**Comment by Mooshimi** [comment]
Duplicate of #52997
