### ISSUE TITLE
Throwing Champagne Corks Breaks Things

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#61572]
Reporting client version: 514.1561

## Round ID:
[169893](https://scrubby.melonmesa.com/round/169893)

## Testmerges:
- [[TM Candidate] Overhauls orbit and POI code to fix part of issue #61508 where players could observe /mob/living/new_player on the lobby.](https://www.github.com/tgstation/tgstation/pull/61509)
- [Disable lobby music until sound preferences are re-added to the top bar menu.](https://www.github.com/tgstation/tgstation/pull/61467)
- [Adds a second Detective slot.](https://www.github.com/tgstation/tgstation/pull/61400)

## Reproduction:
Opening a champagne bottle shoots the cork out, knocking people down and breaking things. This is expected. Throwing that same cork by hand knocks people down and breaks things. This is probably not intended

**Comment by timothymtorres** [comment]
The cork should be treated like a bean-bag bullet projectile for the shotgun.  Once it's fired off, it no longer exists as an object.

**Comment by ATH1909** [comment]
I mentioned this a few weeks ago on discord:
![image](https://user-images.githubusercontent.com/42606352/134503873-5a82e754-7d22-4942-b9f2-58447f34223e.png)
![image](https://user-images.githubusercontent.com/42606352/134503928-ce1e37be-65ab-4c3c-90f3-955dda107f00.png)

**Comment by necromanceranne** [comment]
It's probably easier to turn this into a projectile, yeah.
