### ISSUE TITLE
Can't click-insert RCDs into storages, have to drag-insert

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#61576]
## Reproduction:

Probably caused by #61310 . 

You can't click on a storage item with the RCD to insert it into the storage, as you would with any other item. If you want to put an RCD into a bag or belt, you have to click-drag the RCD into the storage item.

**Comment by NanoCats** [comment]
you can also open the belt and click the empty spot with RCD in hand, it's what I've been doing, this is highly irritating but I can confirm this happens.

**Comment by SyncIt21** [comment]
This issue was also resolved at some point in time. Someone should close this
