### ISSUE TITLE
imaginary friend has no vision or hearing

### ISSUE THREAD

**Issue by Tanden22** [tgstation/tgstation#61585]
## Round ID:
[169906](https://scrubby.melonmesa.com/round/169906)

## Testmerges:
#61509: '[TM Candidate] Overhauls orbit and POI code to fix part of issue #61508 where players could observe /mob/living/new_player on the lobby.' by Timberpoes at commit 2c4ba30d32
#61467: 'Disable lobby music until sound preferences are re-added to the top bar menu.' by MrStonedOne at commit 6cb5dd1fee
#61400: 'Adds a second Detective slot.' by Iamgoofball at commit 85f60a731c

## Reproduction:
1. Be randomly selected for imaginary friend
2. Expect to be able to see, move and hear
3. Learn you cannot do any of the above

**Comment by LemonInTheDark** [comment]
Yep. Known issue, fixed by #61538
