### ISSUE TITLE
Memories broke Changeling antag UI

### ISSUE THREAD

**Issue by JohnFulpWillard** [tgstation/tgstation#61596]
## Reproduction:

1) Be a changeling
2) Absorb someone with memories (All crewmembers have 1 by default, their bank account)
3) Try to open your Changeling UI to see your objectives, and see a big NtOS sign instead.

Absorbing someone without memories looks bad already, though not entirely broken.
![image](https://user-images.githubusercontent.com/53777086/134053160-ef48535a-ad6c-41b5-ab20-30fc699ce596.png)

But if you absorb someone with memories, then it breaks everything.
![image](https://user-images.githubusercontent.com/53777086/134053198-53a13631-2071-4fb3-a318-215c6342660e.png)
![image](https://user-images.githubusercontent.com/53777086/134054649-8c419544-c4d1-4df2-bc5d-9e5211555f08.png)

**Comment by timothymtorres** [comment]
I wonder if #60302 is causing this.
