### ISSUE TITLE
if a sm delams in a ripley it becomes invisible and dusts people

### ISSUE THREAD

**Issue by KittyNoodle** [tgstation/tgstation#61600]
## Reproduction:

1.delam a sm shard.
2.put it in a ripley
3.mark down where it explodes
4. walk into that place
5. turn to dust

**Comment by TheBonded** [comment]
Feature, if you get dusted by this that's just a skill issue

**Comment by timothymtorres** [comment]
Why is it even possible to pickup a SM shard with a ripley?

**Comment by NanoCats** [comment]
> > Why is it even possible to pickup a SM shard with a ripley?
> 
> you can pick up anything pullable, from lockers, canisters, unwrenched machines, to even an SM shard

I feel like if it's not in a box it should absolutely just dust the ripley.

**Comment by Sealed101** [comment]
can no longer reproduce; delam blew up the mech and the crystal with it; no magic death tile appeared
