### ISSUE TITLE
Revolution-banned player did not get offered up to ghosts after being converted to revolution, could continue to play

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#61611]
Reporting client version: 514.1557

## Round ID:
[169970](https://scrubby.melonmesa.com/round/169970)

## Testmerges:
- [[TM Candidate] Overhauls orbit and POI code to fix part of issue #61508 where players could observe /mob/living/new_player on the lobby.](https://www.github.com/tgstation/tgstation/pull/61509)
- [Disable lobby music until sound preferences are re-added to the top bar menu.](https://www.github.com/tgstation/tgstation/pull/61467)

## Reproduction:

```
[2021-09-21 01:46:09.300] GAME: Catgod/(Wallace Webb) has gained antag datum Revolutionary(/datum/antagonist/rev)
...
[2021-09-21 01:48:45.977] SAY: Catgod/(Wallace Webb) "I&#39;m so confused" (Cargo Bay (82,122,4))
...
[2021-09-21 01:48:59.640] SAY: Catgod/(Wallace Webb) "But I&#39;m supposed to be antag banned" (Cargo Bay (82,122,4))
```
Catgod, who was banned from revolution at the time, was converted to a revolutionary as normal. But, instead of being offered to ghosts like antag-banned players normally are, there was no offer and they continued to exist in their body as a revolutionary.

**Comment by timothymtorres** [comment]
This might be related to #61561

**Comment by Mothblocks** [comment]
i kinda doubt it, antag bans check your bans and not your prefs, and i didn't change the antag flag of the revolutionary

**Comment by necromanceranne** [comment]
This is possibly not the reason why, but was this a provocateur (latejoin rev)?

**Comment by MrMelbert** [comment]
The headrev was a latejoin provocateur, but the converted player was not the initial headrev, they got converted like normal.

**Comment by Mooshimi** [comment]
#55197

**Comment by Mooshimi** [comment]
#40442

**Comment by SuperNovaa41** [comment]
They should be offered up, and i mean it's code enforced. I'm just going to label this as cleanup

**Comment by Mothblocks** [comment]
?

The bug is they're *not* being automatically offered up, which they're supposed to be

**Comment by JohnFulpWillard** [comment]
I didn’t notice this issue but I should’ve fixed this with https://github.com/tgstation/tgstation/pull/64068 - unrelated note, when is it too late to ask for High Priority GBP?

**Comment by dragomagol** [comment]
Happened again in Manuel round 192681

**Comment by TheVekter** [comment]
This is still happening. Round 204902, happened to ckey Dwezeldorf (it's a self-requested ban so I'm posting their ckey).

**Comment by iprice** [comment]
had two of these today, for those with ticket access round 205606 ticket 2 and 205628 ticket 1.

Of note, I thought these things conventionally triggered the "is offering up to replace a job banned player" type admin message but i didn't see any of those, at the very least be good to ensure some visibility of the internal process is shown to admins and perhaps the player so we can report if it made any progress in the process (and if it already does contain such reports, i didn't find them either time today)

**Comment by TheVekter** [comment]
This oddly enough actually worked today on round 207995 if you want to compare that to a previous round. Player who was cult banned got replaced as intended.

**Comment by TheVekter** [comment]
This is continuing to happen as of today, going to add a $20 bounty to getting this fixed payable once merged.

**Comment by mc-oofert** [comment]
its possible for polling to not occur if theyre already the target of another poll

**Comment by Singul0** [comment]
HOW HAS THIS NOT BEEN FIXED
