### ISSUE TITLE
Lavaproof tracks module for mining borgs not working

### ISSUE THREAD

**Issue by hyphenationc** [tgstation/tgstation#61613]
Round ID: [169981](https://scrubby.melonmesa.com/round/169981)

Reproduction: Lavaproof tracks on a mining borg, step on lava, die.
I don't think this is a testmerge issue, I think this has been in place for a while but I've only now noticed it. A while ago, when I can confirm lavaproof tracks worked as intended, mining borgs also didn't take any damage from the freezing ray attack from Watchers. That changed a while ago, and only now have I actually made use of lavaproof tracks and found this.

I believe whatever made Watchers capable of damaging borgs may be related to this issue.

**Comment by timothymtorres** [comment]
Might be caused from https://github.com/tgstation/tgstation/pull/61003
