### ISSUE TITLE
Personal photo album doesn't save pictures

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#61628]
I've made several photos and tried to put them in the album over several different rounds, but all of them appear as blank photos on the next shift, while the older ones persist. 
# Reproduction:
Have the Photographer quirk and try to add a new photo in your album. Survive until the end and join the next shift. Find the new photo to be blank. Grieve for the loss of Harambe the fugu-glanded gorilla as the sole evidence of his existence is no more.

**Comment by Mooshimi** [comment]
They may have assumed the reason was the shuttle but looks very related #46541

**Comment by Mothblocks** [comment]
My new photos aren't saving either, this is what's in photo_album.json

![image](https://user-images.githubusercontent.com/35135081/135021824-2db52088-59b9-4b39-9d71-85714449dc4b.png)

**Comment by Mothblocks** [comment]
Note that only that new photo is showing as black, my older ones still work.

**Comment by Mothblocks** [comment]
Oddly enough, new photos DO have their /datum/picture id set.

The only PR within the last year that touches any of this is https://github.com/tgstation/tgstation/pull/60911, but I'm not sure why it would be causing this.

**Comment by Mooshimi** [comment]
> Oddly enough, new photos DO have their /datum/picture id set.
> 
> The only PR within the last year that touches any of this is #60911, but I'm not sure why it would be causing this.

It probably is #60911 because I got to take a few pics with it working before it stopped some time in august.

**Comment by Mothblocks** [comment]
It just makes no sense since the metadata is saving fine... 😕 

![image](https://user-images.githubusercontent.com/35135081/135054080-d7eb4bbe-7655-4de2-9777-931c80b5dc50.png)

**Comment by Mothblocks** [comment]
Found the bug--this is deserializing twice

![image](https://user-images.githubusercontent.com/35135081/135059419-a50aad8f-0515-4fc8-965c-a29a2ee58156.png)
