### ISSUE TITLE
Show Camera List broken

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#61630]
Reporting client version: 514.1561

## Round ID:
[170019](https://scrubby.melonmesa.com/round/170019)

## Testmerges:
- [[TM Candidate] Overhauls orbit and POI code to fix part of issue #61508 where players could observe /mob/living/new_player on the lobby.](https://www.github.com/tgstation/tgstation/pull/61509)
- [_machinery.dm hotfix](https://www.github.com/tgstation/tgstation/pull/61618)

## Reproduction:
The "Show Camera List" ui button was broken in that it only showed one camera, when I had many more cameras working, shown in one of the alert camera menus.
http://prntscr.com/1t5x7tl
http://prntscr.com/1t5xi6v
Unsure of reproduction, but I was ghosted into the role because the AI left or something. I only noticed because I was looking for telecomms.

**Comment by jlsnow301** [comment]
it is very likely that this issue has been fixed after #63398 and or #63394
