### ISSUE TITLE
Tramstation - service-sec swap issues

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#61647]
## Reproduction:

None of the signage or the tram console were updated for the move
![image](https://user-images.githubusercontent.com/51863163/134440687-74210030-c2ce-4820-93bd-b42f8d58bba9.png)

**Comment by MrMelbert** [comment]
![image](https://user-images.githubusercontent.com/51863163/134448765-1ec51990-784f-4fad-ab78-a24953116da0.png)
Also this

**Comment by Potato-Masher** [comment]
Is everything in this issue fixed? The related fix PR was merged.

**Comment by Maurukas** [comment]
Closing this per #61781. If new problems are found, please create a new issue.
