### ISSUE TITLE
infinite ambient occlusion

### ISSUE THREAD

**Issue by InvalidArgument3** [tgstation/tgstation#61649]
Reporting client version: 514.1557

## Round ID:
[170086](https://scrubby.melonmesa.com/round/170086)

## Testmerges:
- [Fix quirks being automatically removed](https://www.github.com/tgstation/tgstation/pull/61631)
- [_machinery.dm hotfix](https://www.github.com/tgstation/tgstation/pull/61618)
- [Rendering refactor P1: Plane unification and render relaying (pictures and video included)](https://www.github.com/tgstation/tgstation/pull/61286)

## Reproduction:

1. toggle ambient occlusion in game options
2. https://i.imgur.com/71syUJ6.png

**Comment by wesoda25** [comment]
![dreamseeker_HQpDLvZSgJ](https://user-images.githubusercontent.com/37246588/134568774-e474aca6-ae94-4cc7-a16d-7cc3cacf4247.png)

![dreamseeker_rs4eMKrPm9](https://user-images.githubusercontent.com/37246588/134568714-9fce3332-a6e9-40e8-863d-6cea0a04b412.png)
)
related I think?

**Comment by TiviPlus** [comment]
Preferences issue

**Comment by TiviPlus** [comment]
cc @Mothblocks

**Comment by Mothblocks** [comment]
ya

**Comment by InvalidArgument3** [comment]
this was fixed a few days after i posted it
