### ISSUE TITLE
Tattoo kits don't work

### ISSUE THREAD

**Issue by tralezab** [tgstation/tgstation#61645]
Reporting client version: 514.1557

## Round ID:
[170072](https://scrubby.melonmesa.com/round/170072)

## Testmerges:
- [_machinery.dm hotfix](https://www.github.com/tgstation/tgstation/pull/61618)
- [[TM Candidate] Overhauls orbit and POI code to fix part of issue #61508 where players could observe /mob/living/new_player on the lobby.](https://www.github.com/tgstation/tgstation/pull/61509)

## Reproduction:

Have a tattoo kit

attack someone

it doesn't do anything

**Comment by LemonInTheDark** [comment]
big rip

**Comment by JohnFulpWillard** [comment]
![image](https://user-images.githubusercontent.com/53777086/146965254-a35191b3-7ec0-4dc2-a8b4-8fedc23ef3a6.png)

this is kinda weird
It requires the person you're tattooing to have a mind
You to not be in combat mode
Then it checks the limb you're tattooing, if it has any tattoos already, if it cant be tattoo'd
Then finally it checks if you're besides them, actually have a memory to give, and if you're targetting the bodypart.
