### ISSUE TITLE
Stack of medibots is the only selectable mediborg skin

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#61648]
Reporting client version: 514.1561

## Round ID:
170081

## Testmerges:
- [Fix quirks being automatically removed](https://www.github.com/tgstation/tgstation/pull/61631)
- [_machinery.dm hotfix](https://www.github.com/tgstation/tgstation/pull/61618)
- [Rendering refactor P1: Plane unification and render relaying (pictures and video included)](https://www.github.com/tgstation/tgstation/pull/61286)

## Reproduction:
1. Be a cyborg
2. Try to select the mediborg module
3. You can only be a stack of medibots in a trenchcoat. Astounding!
![borg1](https://user-images.githubusercontent.com/46474741/134446564-648ee761-56c2-488b-b6c3-25c1e560dca0.PNG)

**Comment by SuperNovaa41** [comment]
No longer a problem
