### ISSUE TITLE
Observer spawn menu not letting you Jump to or Spawn

### ISSUE THREAD

**Issue by Ed640** [tgstation/tgstation#61654]
Reporting client version: 514.1566

## Round ID:
[170098](https://scrubby.melonmesa.com/round/170098)

## Testmerges:
- [Disable lobby music until sound preferences are re-added to the top bar menu.](https://www.github.com/tgstation/tgstation/pull/61467)
- [Adds a second Detective slot.](https://www.github.com/tgstation/tgstation/pull/61400)

## Reproduction:
The spawn menu buttons (Jump,Spawn) don't seem to do anything, but you can still use orbit to jump to the various spawn points and play them.

**Comment by Mothblocks** [comment]
CC @Timberpoes

**Comment by Mooshimi** [comment]
also round [https://scrubby.melonmesa.com/round/170173](170173) and this is the mentioned menu for funsies
![image](https://user-images.githubusercontent.com/85910816/134716442-e75fa75a-9055-41e8-a33a-e7fef62b137f.png)
![image](https://user-images.githubusercontent.com/85910816/134716492-b2947458-8a70-4953-bae2-b1f789b26c59.png)
