### ISSUE TITLE
Pai left a shadow pai on my screen when it deployed to its shell from my bag

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#61658]
## Testmerges:
The following pull requests are currently test merged:
#61467: 'Disable lobby music until sound preferences are re-added to the top bar menu.' by MrStonedOne at commit 6cb5dd1fee
#61400: 'Adds a second Detective slot.' by Iamgoofball at commit 85f60a731c

## Reproduction:
https://puu.sh/IdnJL/78ccaa08a4.png

get a live pai
put it in your bag
have your bag open
the pai deploys into a shell, leaving your bag, but keeping its little face just above your hands the entire shift

**Comment by TheBonded** [comment]
Sometimes it seems like you can see their runescape text over the ghost pAI card as well

**Comment by newfren** [comment]
oh, this disappeared at some point, but the shift was 5 hours long so who knows why.

**Comment by timothymtorres** [comment]
@GoldenAlpharex do you think this might have something to do with #61112

**Comment by GoldenAlpharex** [comment]
> @GoldenAlpharex do you think this might have something to do with #61112

No, I haven't touched code handling getting them out of the bag or updating their appearance. However, looking at this screenshot, it's clearly not the only thing wrong. Everything has absolutely no shadow, and unless that's a pref I don't know about, that just seems like a bug bigger than just this.

What I'd like to know is, is it 100% reproducible?
Does it get fixed when it turns off its holochassis?
If not, does it get fixed when you put it in your bag again after it has folded said holochassis?
This isn't something I've ever seen before, so I really can't say too much about it right this moment.

**Comment by Sealed101** [comment]
god bless puush deleting old images now we will never know what the hell was the issue
most likely fixed by https://github.com/tgstation/tgstation/pull/68241
if the issue was the pai card not disappearing when deployed to holoform, it doesn't do that anymore (the pai card doesn't move)
