### ISSUE TITLE
Being converted to a virus immune species does not fix a virus

### ISSUE THREAD

**Issue by KittyNoodle** [tgstation/tgstation#61651]
Reporting client version: 514.1566

## Round ID:
[170089](https://scrubby.melonmesa.com/round/170089)

## Testmerges:
- [Disable lobby music until sound preferences are re-added to the top bar menu.](https://www.github.com/tgstation/tgstation/pull/61467)
- [Adds a second Detective slot.](https://www.github.com/tgstation/tgstation/pull/61400)

## Reproduction:

1. get a virus
2. change your species to a virus immune species(eg: nightmare, shadowperson, android)

**Comment by lizardqueenlexi** [comment]
It doesn't look like this happens anymore.
