### ISSUE TITLE
Metalgen recipe is changing too fast

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#61661]
OK!

so on the manuel discord the metalgen recipe is often shared in #medical class, just whenever a miner or space explorer finds it or whatever.

There has been an update on metalgen:
Yesterday, 6pm aest
Today, 11:50pm aest
Today, 6pm aest

I attempted to make the 6pm recipe at around 9pm (not certain of the exact time, but it was in the very next round (170103)) and it did not work - double checked the container, the temperature, each reagent, all correct, no reaction. I can't tell if this is because the reaction isn't working, or if the recipe changed from the previous round.

Should be changing "every 3 days" according to the wiki (I have the chemistry page open and I haven't reloaded it since they were taken down).

**Comment by Time-Green** [comment]
@AnturK you added random recipy’s, do you have any insight?
