### ISSUE TITLE
Drowsiness Needs to be "automatically" capped

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#61666]
ANYTIME you are having to touch drowsiness, it requires a clamp so usually the code is

`Mob.drowsiness = max(mob.drowsiness + effect, 0)`

This is because negative values will cause semi-permanent drowsiness, and has resulted in a non-zero amount of bugs (#61396 for example).

What i would like is to have a proc that handles this on the mob similar to other values such as sleepiness and damage.

The code then will likely look like

`Mob.AdjustDrowsiness(effect)`

This will need to be changed for any part of the code that touches drowsiness.

**Comment by ExcessiveUseOfCobblestone** [comment]
trips

**Comment by LemonInTheDark** [comment]
bastard
