### ISSUE TITLE
Xenomorphs evolving leave a copy of the older xenomorph

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#61675]
Reporting client version: 514.1556

## Round ID:
[170140](https://scrubby.melonmesa.com/round/170140)

## Reproduction:
1. Be a drone
2. Evolve into prat. You'll leave a drone behind.
3. Evolve into queen. You'll leave a prat behind.

**Comment by JohnFulpWillard** [comment]
https://github.com/tgstation/tgstation/pull/61549
https://github.com/tgstation/tgstation/pull/62020

one of these fixed it... i cannot pinpoint which one, but I just tested on latest master and it works fine
![image](https://user-images.githubusercontent.com/53777086/146964707-29db1ef8-51ad-4813-93b9-343741a56106.png)
