### ISSUE TITLE
Invisible thing (?) left over after sharding

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#61686]
Reporting client version: 514.1561

## Round ID:
[170182](https://scrubby.melonmesa.com/round/170182)

## Testmerges:
- [Festival Sect, a revival of an unfinished Music-based sect by cobby](https://www.github.com/tgstation/tgstation/pull/61629)
- [species changes part 1: lizards](https://www.github.com/tgstation/tgstation/pull/61440)

## Reproduction:
-shard a horizontal person with only oxygen damage(not sure if relevant)
![image](https://user-images.githubusercontent.com/85910816/134738528-bfad0c8d-7eca-4f30-8cb0-5110ed89bb00.png)
-sharded person put into the construct and clearly active, but invisible mob left behind which eventually dies because it was already mostly suffocated. (or it starts dead if sharded person was dead)
![image](https://user-images.githubusercontent.com/85910816/134738789-dec66568-c372-4921-8bde-b62eaa83c6dd.png)
There were three in the same area, they can't be pointed to by ghosts or examined.
![image](https://user-images.githubusercontent.com/85910816/134738933-5627e4ba-0d73-4edf-9d23-1d17cd44392d.png)
They are also not shown in the alt click tab, only shift right click.
![image](https://user-images.githubusercontent.com/85910816/134739039-44ffd767-70de-4969-95af-2961ea51ed63.png)

**Comment by Sealed101** [comment]
![image](https://user-images.githubusercontent.com/75863639/134774915-acbf0798-7019-4015-9f97-2eee4cfb3556.png)
just happened on 170227 with cap's body. funny thing is he had the nuke disk implanted and to get it out admins have had to throw the body off zlevel

**Comment by Mooshimi** [comment]
![image](https://user-images.githubusercontent.com/85910816/136651370-1f09e37d-aa17-4682-ab89-1e2777ad0aac.png)
just happened in 171001
