### ISSUE TITLE
If the species list gets too long, it will make the entire preferences window scroll

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#61697]
Skyrat is having this problem, but we're going to have this problem on Halloween. If there are too many available races, then it doesn't make just the species list scrollable.

**Comment by JohnFulpWillard** [comment]
seems it was fixed at some point, is this good to close?

![image](https://user-images.githubusercontent.com/53777086/148327908-753e1984-e036-49e1-a8d9-e92f192aec0a.png)

**Comment by Mothblocks** [comment]
Yeah I fixed this a bit ago, just forgot
