### ISSUE TITLE
Occasionally, contractors are unable to stuff targets into their extraction droppod, unless they clickdrag the target to the debris directly UNDER the pod.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#61695]
## Reproduction:
**EDIT: Alright, turns out you sometimes can't click drag people onto the pod itself, as if it isn't targetable. You can however click drag the target to the debris UNDER the pod, and that will count.**

I've seen this over multiple rounds, and others have attested to this. Sometimes it seems that when you try to put your contract target into their pod, nothing happens. No progress bar, no nothing.  You are now stuck as the target can't be submitted and you can't cancel a contract. No more contracting for you.

In my most recent attempt, I was able to start the progress bar, but had to move away to avoid an attacker. After returning to the pod, I was unable to put the target in the pod, despite it seeming to work about 2 minutes before.

**Comment by necromanceranne** [comment]
It's entirely possible that the issue is that interrupting the do_after makes it impossible to complete the contract, if that is what is happening.

**Comment by Potato-Masher** [comment]
### I'm gonna keep logging everytime this happens here, since it happens so god damn often.

Not me this time, but I witnessed it as a contractor. I met another friendly contractor in the middle of an extraction.
He called in the pod, and attempted the shove the target in. They never went in, no prior interaction with the pod.
An admin was called down once again to check what the hell was going on, but they determined that it was broken and refunded the contractor.
![dreamseeker_fP5b32Zn3O](https://user-images.githubusercontent.com/33107541/134799665-b2dfcc95-2044-4a2b-86c7-6a1b956d5627.png)

**Comment by FlamingCheese** [comment]
I have encountered this issue before and from what I can gather, the pod hitbox is different from the sprite (you can drag a person into the pod if you find just the right place on the right side of the pod where the debris is)

**Comment by Potato-Masher** [comment]
That's it @FlamingCheese , I just tried it myself. The pod itself isn't targetable by click dragging for what ever reason, but click dragging the target to the derbies below the pod itself works.
