### ISSUE TITLE
You can use sentient mobs to cheeze megafauna

### ISSUE THREAD

**Issue by KittyNoodle** [tgstation/tgstation#61702]
Reporting client version: 514.1566

## Round ID:
[170247](https://scrubby.melonmesa.com/round/170247)

## Testmerges:
- [species changes part 1: lizards](https://www.github.com/tgstation/tgstation/pull/61440)
- [Adds a second Detective slot.](https://www.github.com/tgstation/tgstation/pull/61400)
- [Disable lobby music until sound preferences are re-added to the top bar menu.](https://www.github.com/tgstation/tgstation/pull/61467)
- [tgui: Flex basis should be zero if grow is used](https://www.github.com/tgstation/tgstation/pull/61499)

## Reproduction:

1.make a sentient fauna
2. sick it at the megafauna
3. the megafauna will not aggro on fauna
4. win

**Comment by Sealed101** [comment]
could not reproduce
