### ISSUE TITLE
Health Seems to be calculated incorrectly

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#61701]
## Reproduction: Deal 126 brute damage, notice they have 1% Health still. Note I observed them and they didn't have determination active.
![Capture](https://user-images.githubusercontent.com/4716493/134784968-db9fd169-636c-47d4-a7ee-463ff58f0593.PNG)

<!-- **For Admins:** Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them. --

>

**Comment by TemporalOroboros** [comment]
I'm pretty sure that limbs have a multiplier for how much damage they count as. If that's right the math should put it at around 75%.

**Comment by necromanceranne** [comment]
Yeah this is working as intended. Limbs aren't fully considered for core health. The issue is more with health analyser readouts not clarifying this fact.
