### ISSUE TITLE
You can open the emergency space suits locker by right-clicking on it, despite alert level

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#61710]
![image](https://user-images.githubusercontent.com/35135081/134794396-0eee788f-facf-4198-9a8a-50d4ed28e0eb.png)

These, found primarily in the pods, are usually only unlocked during red/delta alert. You can right-click on them to open them at any alert, and take the items, including flash proof helmets.

**Comment by MrMelbert** [comment]
dupe of #60057
