### ISSUE TITLE
tgui windows are scaled improperly

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#61721]
## Round ID:
[170286](https://scrubby.melonmesa.com/round/170286)

## Testmerges:
#61440 #61400 #61467 #61499 (< im guessing this is the pr that broke tgui )

## Reproduction:
windows like the circuit menu, medical kiosk, borg robotact app,orion trail and maybe more have improper scaling between the sub windows this makes said windows hard to read or use

![brokeui1](https://user-images.githubusercontent.com/75639936/134816762-cbfd3666-4015-4b8f-bf94-b0f37e263b22.PNG)

**Comment by Jcarr0ndo** [comment]
Guess this would be the correct place to put this then, better examples of the issue:

![Screenshot_2](https://user-images.githubusercontent.com/8581687/134925167-beed3e9a-96dd-4644-9799-a505a2d03d1d.png)

![Screenshot_3](https://user-images.githubusercontent.com/8581687/134925938-fd49b29e-4702-45d8-8786-52d6739436a2.png)

**Comment by Watermelon914** [comment]
Tested every UI you said, most are confirmed except orion trail. I could not find any UI problems with orion trail.

**Comment by FlamingCheese** [comment]
> 
> 
> Tested every UI you said, most are confirmed except orion trail. I could not find any UI problems with orion trail.

the tutorial section of orion trial is broken, forgot to clarify that

**Comment by stylemistake** [comment]
Flex was bugfixed at some point.
