### ISSUE TITLE
Gases have no visible overlay/sprite

### ISSUE THREAD

**Issue by kopoba** [tgstation/tgstation#61731]
## Testmerges:
The following pull requests are currently test merged:
#61714: 'Fix word bounds on filters, where they would only be applied at the beginning' by Mothblocks at commit 79f25e73fb

## Reproduction:
Join as engi/atmosian
Go to atmos
Look at gas storages
Gases have no overlay(sprite)

![image](https://user-images.githubusercontent.com/5034345/134891267-2661497b-ff12-4a40-bed9-8eba4ea44a19.png)

i checked my local version and overlay works there but its month old so problem seems to be new.

**Comment by TemporalOroboros** [comment]
Is this only the tanks or does it include spilled gasses?

**Comment by Ghilker** [comment]
> Is this only the tanks or does it include spilled gasses?

everything
