### ISSUE TITLE
Database normalizion issues

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#6174]
Simply put, the ban table of the database violates part of the first rule of database normalization:

No duplicated information that could be inferred or calculated from 2 or more fields of the same row.

The ban database stores two fields relating to ban time:
* duration
* expiration_time

The first is only used when showing ban times to the user.
The second is used when checking if a ban is still active in isbanned() and showing when a ban expires to a user

If code wants to change the length of a ban, it has to change two fields for the ban time. (**coders changing bandb stuff may not know this and only change one**)

The proposed solution (that will try to code here soon) is to remove the duration field.

Why the duration field and not the expiration_time field? Because rewriting the ban check to calculate the expire time from every ban every time someone connects would lead to much higher loads on the bandb and the game server. Having it calculate the ban duriation from the bantime and expire time only when showing user friendly information on ban times would not.

There is also the issue that some asshat managed to change every duration in the database to 1 minute some time in April.

**Comment by tkdrg** [comment]
@MrStonedOne is this still an issue?

**Comment by Jordie0608** [comment]
The code for it hasn't changed much since so yeah
