### ISSUE TITLE
Obscured areas can sometimes look like open space (v2)

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#61756]
## Round ID:
[170378](https://scrubby.melonmesa.com/round/170378)

## Testmerges:
#61694 #61440 #61286

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/135116936-00b5ff59-d87b-4b07-932a-f5af2c182079.png)

**Comment by Mothblocks** [comment]
CC @TiviPlus TM fault?

**Comment by TiviPlus** [comment]
I need reproduction steps for this

**Comment by Mothblocks** [comment]
use a flashlight and look at some empty space iirc

**Comment by wesoda25** [comment]
Related? #61649

**Comment by Mothblocks** [comment]
Maybeeee, the bug with that is (and I realized it was the fault of the new refactor), it's creating a new plane for the game world every time `backdrop()` is called.

**Comment by TiviPlus** [comment]
Not related
The issue here is lighting is multiplying over the darkness plane and piercing it

**Comment by TiviPlus** [comment]
This is extremely likely a byond issue and lummox has been difficult to work with so I'm not going to continue trying to fix this
