### ISSUE TITLE
Random spawn station trait on Kilo is bad

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#61760]
## Reproduction:

https://youtu.be/qnC_O2fTSSo

Assistant should have played around that but still looks like a oversight.

**Comment by NanoCats** [comment]
Damn he got **OUTPLAYED**

**Comment by Mooshimi** [comment]
#61118 similar to this but different map

**Comment by Dmeto** [comment]
> #61118 similar to this but different map

I was hoping this was an an Icebox exclusive problem due to map changes ... I was wrong, now i wait to see if someone spawns in a atmos gas reservoir.
