### ISSUE TITLE
The nuke disk now teleports away when entering hyperspace (such as on the emergency shuttle)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#61782]
## Round ID:

[170474](https://scrubby.melonmesa.com/round/170474)

## Reproduction:

Possibly caused by #61335 . 

In the past, the nuke disk could ride the escape shuttle (hyperspace) to central command
Now, the nuke disk teleports away when entering hyperspace, making it impossible for the crew to take the nuke disk home

(Meaning the crew can't major victory on nuke ops, traitors can't greentext the nuke disk steal objective, etc...)

![image](https://user-images.githubusercontent.com/51863163/135372315-b3471038-eccb-461d-9ab5-a8ce76ba0436.png)

**Comment by LemonManDerpy** [comment]
I redtexted a tot round yesterday because of this, please fix
