### ISSUE TITLE
Voice of God "Dance" command does not force other players to dance

### ISSUE THREAD

**Issue by plutori** [tgstation/tgstation#61794]
## Reproduction: The "Dance" command from using the Voice of God does not work on Sybil due to the fact that it looks like although it displays "DANCE" in the chat box (or it should, anyway, this is what it does on downstreams like fulp) the actual command given is "xdance", which triggers the chat filter due to "xd" being a banned emoticon. UPDATE: Per testing on Sybil per round 17506, Voice of God now does in fact say "DANCE" in the big red letters like it is supposed to, but now it does not compel others to dance like it is supposed to. Reproduction steps (very minorly) updated.

1. Kill the Colossus
2. Obtain the Voice of God 
3. Implant the Voice of God into your mouth using an organ manipulation surgery on your mouth
4. Type "dance" into the command box for the Voice of God while nearby other players

**Comment by Sealed101** [comment]
since VoG commands have .x prefix to trigger i'd reckon any other words starting with a letter that might be a part of an emoticon would also be unavailable unless you type it from chat as _.x blah_
but if you use the button it'd filter out

**Comment by Mothblocks** [comment]
really wish we had that round ID because i very likely have already fixed this

**Comment by Mothblocks** [comment]
https://scrubby.melonmesa.com/ckey/putyourckeyhere

**Comment by plutori** [comment]
Per round 17506, it now displays "DANCE" in the chat box, but it no longer compels others to dance. Will update main body to reflect updated information momentarily.

**Comment by Mothblocks** [comment]
It's very unlikely this is a chat filter problem at this point--can you update the title to reflect what the problem *is* directly?

**Comment by plutori** [comment]
> It's very unlikely this is a chat filter problem at this point--can you update the title to reflect what the problem _is_ directly?

Title updated

**Comment by Sealed101** [comment]
can not replicate; what is this round ID anyway
