### ISSUE TITLE
Alternate Human Names do not implement 

### ISSUE THREAD

**Issue by jeanlafite** [tgstation/tgstation#61792]
## Round ID: 
[170485](https://scrubby.melonmesa.com/round/170485)

## Reproduction:
When selecting a Head of Staff position; Captain, CE, HOP, etc; from a lizard character alternate human name will not apply. Game instead gives lizard or other nonhuman name to the human mob.

**Comment by Mooshimi** [comment]
Yes, I've seen this with plasmamen as well

**Comment by dragomagol** [comment]
Duplicate of #60795
