### ISSUE TITLE
Cable restraints aren't rendering in the crafting menu

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#61790]
## Round ID: [170484](https://scrubby.melonmesa.com/round/170484)

CC @TiviPlus , your fault? 🙂 
![dreamseeker_2021-09-29T23-02-34](https://user-images.githubusercontent.com/35135081/135396753-8ab3dbb2-8553-44b9-87cc-92a42fc84937.png)

**Comment by TiviPlus** [comment]
```
@wobbly (mothblocks) 
restraints_icon = image(icon = 'icons/obj/items_and_weapons.dmi', icon_state = "cuff")

but theres no cuff icon state 
```

**Comment by Mothblocks** [comment]
lmao
