### ISSUE TITLE
Space Dragon spawned without Wing Gust move.

### ISSUE THREAD

**Issue by redsunoverparadise** [tgstation/tgstation#61798]
## Reproduction:
Accept space dragon role midgame
Notice you don't have one if your strongest abilities
Win anyways

**Comment by Sealed101** [comment]
its rebinded to right click but it should probably be more visible to players that there is an ability on right click

**Comment by redsunoverparadise** [comment]
> its rebinded to right click but it should probably be more visible to players that there is an ability on right click

Oh bruh
