### ISSUE TITLE
The blur from aiuri lets you see through lavaland to space around ruins

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#61824]
## Testmerges:
The following pull requests are currently test merged:
#61499: 'tgui: Flex basis should be zero if grow is used' by stylemistake at commit 7f52aae508
#61467: 'Disable lobby music until sound preferences are re-added to the top bar menu.' by MrStonedOne at commit 6cb5dd1fee
#61400: 'Adds a second Detective slot.' by Iamgoofball at commit 85f60a731c
#61440: 'species changes part 1: lizards' by Fikou at commit b9dfdd9f52
#61711: 'Buffs eye contact, adds "Shifty Eyes" quirk' by Ryll-Ryll at commit b2a33de31c
#61816: '[DNM] [TM Candidate] Infuses certain vents with an aroma of garlic, repelling bat form vampires.' by Timberpoes at commit f9a6d7f555

## Reproduction:
Take aiuri (like from the starting survival pen)
move about near a ruin to see it more clearly but:
https://puu.sh/Ifh9C/d80a7b9249.png
still visible when stationary.

**Comment by newfren** [comment]
update: this also works on station.
https://puu.sh/IgasR/86a2e4da26.png

**Comment by TheBonded** [comment]
I believe this is an extension/duplication of https://github.com/tgstation/tgstation/issues/61756

**Comment by SuperNovaa41** [comment]
Yeah looks like it to me
