### ISSUE TITLE
Deactivated HFR floods chat trying to automatically refresh the deactivated interface

### ISSUE THREAD

**Issue by esainane** [tgstation/tgstation#61850]
## Reproduction:

Have the HFR UI open, then C4 (or del) one of the other components.

![activate](https://user-images.githubusercontent.com/14355175/135711640-7be48d88-8092-4b94-81a8-4ecd4d124237.png)

I'm not sure what the best approach is here. Forcibly closing the window seems like a bit of hack, but I'm not sure of a way to cleanly suspend automatic updating, if that's even a good thing to do.

**Comment by Watermelon914** [comment]
HFR is supposed to be indestructible

**Comment by esainane** [comment]
If that's the case, then there's something more seriously broken. You can't deconstruct the machine unless it's off and has no active fusion reaction. However, an explosion at maximum intensity on a tile with one of the machines is enough to destroy a piece, and more generally shut down the machine.

In the guide I wrote at the start of the year, I even suggested a bomb as a means of avoiding a worst case scenario. I think this is still in the wiki guide. This can sometimes even happen from an internal explosion during a pressure spill, if intense enough.

...yeah, thinking about it, I can see how using explosions to cheese your way out of a meltdown is troublesome.

**Comment by timothymtorres** [comment]
This was fixed apparently with #62164.  The HFR is immune to explosions now.
