### ISSUE TITLE
Formatting issue in changeling traitor panel

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#61864]
## Round ID:
170624

Master commit: ecbe3706c22cb4aa8f54def072f8f30d319a7076
The following pull requests are currently test merged:
#61835: 'Fix old photos being lost(?)' by Mothblocks at commit dce78735de
#61851: 'Fixed animating filters with circuits and added special signal ports for instant circuit execution.' by Watermelon914 at commit 5b03487926

## Reproduction:

Text in the changeling's traitor objectives / information is overlapping and overwriting its self, for example see https://gyazo.com/009ed8251e280a105fa06862dbe53dc8 or spawn in thunderdrome, changeling yourself and click that first button on their actions panel.

**Comment by Watermelon914** [comment]
Likely related to the flex-basis changes done by stylemistake.
