### ISSUE TITLE
Surgically implanted zombie oozes do not always zombify

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#61867]
Reporting client version: 514.1561

## Round ID:
[170619](https://scrubby.melonmesa.com/round/170619)

## Testmerges:
- [Fix old photos being lost(?)](https://www.github.com/tgstation/tgstation/pull/61835)
- [Buffs eye contact, adds "Shifty Eyes" quirk](https://www.github.com/tgstation/tgstation/pull/61711)
- [Adds a second Detective slot.](https://www.github.com/tgstation/tgstation/pull/61400)
- [Disable lobby music until sound preferences are re-added to the top bar menu.](https://www.github.com/tgstation/tgstation/pull/61467)
- [(Maybe) fixes panic-bunker rejecting people it shouldn't when interviews is enabled](https://www.github.com/tgstation/tgstation/pull/61837)

## Reproduction:
I created a festering ooze from the necrotic revival surgery, which was successful at reanimating the dead person. The ooze was removed to be used later. Someone else was killed via removal of their brain, the ooze was placed in their head, and then the brain was put back. After around 8 minutes the ooze had not revived them, so I removed the ooze and put it back in their head. This achieved nothing, and they spent the rest of the round in this state.

**Comment by Mooshimi** [comment]
Has this worked in the past? I think the intent is to perform the revival surgery on each person

**Comment by NoxVS** [comment]
It is the nature of zombies, they can't really exist without a tumor. This should work even if the tumor is naturally created too, not just through necrotic revival.

**Comment by necromanceranne** [comment]
this has worked in the past, fyi. I used to do it a few times just to show off braindead zombies using it.

**Comment by Sealed101** [comment]
seems to be working fine; unless you somehow managed to miss the window of revival while replacing the brain, i can't see why would this fail. no runtimes in the logs for the ooze either

**Comment by NoxVS** [comment]
> seems to be working fine; unless you somehow managed to miss the window of revival while replacing the brain, i can't see why would this fail. no runtimes in the logs for the ooze either

I forgot I even had this issue open, I think I may have actually narrowed it down more at one point. Do necrotic revival surgery, remove the ooze before it converts the corpse, put it in a new body, and it shouldn't work. I'll try and recreate it and make a new issue if it still exists
