### ISSUE TITLE
Space Visible Through Interior Walls

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#61874]
Reporting client version: 514.1561

## Round ID:
[170639](https://scrubby.melonmesa.com/round/170639)

## Testmerges:
- [Fix old photos being lost(?)](https://www.github.com/tgstation/tgstation/pull/61835)
- [Buffs eye contact, adds "Shifty Eyes" quirk](https://www.github.com/tgstation/tgstation/pull/61711)
- [Adds a second Detective slot.](https://www.github.com/tgstation/tgstation/pull/61400)
- [Disable lobby music until sound preferences are re-added to the top bar menu.](https://www.github.com/tgstation/tgstation/pull/61467)
- [(Maybe) fixes panic-bunker rejecting people it shouldn't when interviews is enabled](https://www.github.com/tgstation/tgstation/pull/61837)

## Reproduction:
Standing against and facing an interior wall, darkened window, or closed door (basically anything that blocks line of sight) while wearing or holding a light source that would extend over the space covered by the wall lights up and makes visible the open space that would be visible if you were to remove the flooring entirely - IE while on station, the meteor and lavaland are visible if they would be visible from where you're standing without the station in the way. Confirmed that another person could see the same, they had to remove mesons to do so

**Comment by Mooshimi** [comment]
![image](https://user-images.githubusercontent.com/85910816/135778344-033106ce-96b2-4379-91c0-390b60ec40bb.png)
seems to be a related visual bug. round 170690

**Comment by adamkad1** [comment]
Its not that space is visible, just space is for some reason the new 'stuff you cant see' instead of just pitch blackness

**Comment by Zytolg** [comment]
I've been seeing this in all of my rounds and private test servers on various versions of /tg/ code since Saturday.

**Comment by ProfessorSniff** [comment]
#61756 dupe
