### ISSUE TITLE
Defibrillating an admin who has aghosted forcibly returns them to their body

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#61870]
Reporting client version: 514.1561

## Round ID:
[170629](https://scrubby.melonmesa.com/round/170629)

## Testmerges:
- [Fix old photos being lost(?)](https://www.github.com/tgstation/tgstation/pull/61835)
- [Buffs eye contact, adds "Shifty Eyes" quirk](https://www.github.com/tgstation/tgstation/pull/61711)
- [Adds a second Detective slot.](https://www.github.com/tgstation/tgstation/pull/61400)
- [Disable lobby music until sound preferences are re-added to the top bar menu.](https://www.github.com/tgstation/tgstation/pull/61467)
- [(Maybe) fixes panic-bunker rejecting people it shouldn't when interviews is enabled](https://www.github.com/tgstation/tgstation/pull/61837)

## Reproduction:
Aghost from your body, have someone defib it (may need to be a combat defib to allow for it to be used on someone living), it will return them to their body forcibly, presumably as part of the process to normally return a ghost to their body right before it is brought back to life.

**Comment by newfren** [comment]
Does this work on regular players who ghosted?

**Comment by NoxVS** [comment]
> Does this work on regular players who ghosted?

Regular ghosted players go catatonic. Admin ghosting leaves your body SSD, and can be returned to at any time.

**Comment by OceanFish1** [comment]
New game troll the admin before they ban you :trollface:
