### ISSUE TITLE
bluespace anomalies can apparently teleport the xenobiology computer's camera/crosshair, making them unusable

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#61884]
## Testmerges:
#61440: 'species changes part 1: lizards' by Fikou at commit b9dfdd9f52
#61835: 'Fix old photos being lost(?)' by Mothblocks at commit dce78735de

apparently bluespace anomalies can teleport away the blue crosshair that lets xenobiologists look around xenobio, which results in the computer effectively being unusable since the crosshair cant be moved if it isnt in xenobio

**Comment by LemonInTheDark** [comment]
Amazing
