### ISSUE TITLE
Holding people up can give infinite chat message and other broken stuff.

### ISSUE THREAD

**Issue by itseasytosee** [tgstation/tgstation#61883]
## Round ID: 
Tested Localy

## Testmerges:
N/A 

## Reproduction:
First: hold someone up.
Second: Click on anything
If the thing you clicked on is a mob you will fire at that mob and hold them up again at the same time.
If the thing you clicked on is a decal or object you will aim at that object forever, saying that you have stopped aiming at that object every time you take a step, even if you put away the gun. Pretty much gimping your chat for the rest of the round.

Almost certainly caused by #61848

![image](https://user-images.githubusercontent.com/55666666/135755424-28ac9e07-f1e1-4225-a040-e4471dc862f9.png)

fuck

**Comment by Mooshimi** [comment]
@tralezab look related to you?

**Comment by optimumtact** [comment]
hopefully fixed now
