### ISSUE TITLE
Chat formatting doesn't work properly in runechat/radio

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#61888]
So you can format your chat messages with _'s for underline, +'s for bold

IE you've got to be +fucking+ kidding me

I've noticed this doesn't work properly on Runechat, or the radios for some reason 
![image](https://user-images.githubusercontent.com/14065903/135761238-6cdc5522-c78d-4f5e-9fc1-c69ac8207496.png)

okay it KINDA works on runechat, sometimes...
![image](https://user-images.githubusercontent.com/14065903/135761254-12903aef-f07a-4c95-a34d-b2b059079a6f.png)
![image](https://user-images.githubusercontent.com/14065903/135761270-a6bcf0fb-3f0b-4fc1-a05e-24a7aa52d22e.png)

**Comment by NanoCats** [comment]
Update: Also afflicts big voice (Makes you talk small on the radio and the formatting doesn't work)

**Comment by Mooshimi** [comment]
I believe this works fine now.
