### ISSUE TITLE
Rolling table shuttle teleport

### ISSUE THREAD

**Issue by RigglePrime** [tgstation/tgstation#61897]
## Round ID:

[170685](https://scrubby.melonmesa.com/round/170685)
[170696](https://scrubby.melonmesa.com/round/170696)

## Testmerges: 

#61835, #61851 on Terry
#61440, #61835 on Sybil

## Reproduction:

1. Hop in a shuttle (tested both times with the punlic mining shuttle)
2. Spawn in a `/obj/structure/table/rolling`
3. Lie on the table
4. Tell the shuttle to depart
5. Be amazed as you are teleported into space

**Comment by NanoCats** [comment]
Tacking onto this, if you pick up a rollertable with a Ripley, when you eject it, you are also ejected from the mech for some reason.

If a coder wants me to split this into another issue I can, but I sense they're related somehow.

**Comment by Sealed101** [comment]
fixed by https://github.com/tgstation/tgstation/pull/79490
