### ISSUE TITLE
rod gets deleted by transit tubes

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#61891]
## Round ID:
Heard it in dchat once, reproduced on local

## Reproduction:
get a immovable rod, make a transit tube dispenser facing the rod, enjoy a rod free station

**Comment by KittyNoodle** [comment]
Oh my god I was the person who discovered this, was trying to get rid of a looping rod without an rd. Started fucking around with stuff that moves items like disposals and transport tubes, I then went to get stuff for a teleporter to see if that would work. I came back and the rod was gone.
