### ISSUE TITLE
Guns hold up everything, bluespace oresatchels stop working randomly

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#61906]
## Testmerges:

#61835: 'Fix old photos being lost(?)' by Mothblocks at commit dce78735de
#61856: 'Refactors the list datatype to support composite lists. Adapts a lot of circuits to be able to properly use composite lists. Adds the dispenser shell' by Watermelon914 at commit e5791986c4
## Reproduction:

Get plasma cutter, point at rock, I'm friggin holding up this rock yo. Also idk about bluespace oresatchels but they just randomly stop picking up ore you walk over

**Comment by itseasytosee** [comment]
This will be fixed when #61900 gets merged

**Comment by oklews** [comment]
Should be a feature tbh

**Comment by itseasytosee** [comment]
It breaks a hell of a lot of shit, like more than you could imagine.

**Comment by Mooshimi** [comment]
#61900 is now merged
