### ISSUE TITLE
Monkies are (allegedly) too powerful according to the bluespace labels

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#61918]
![image](https://user-images.githubusercontent.com/14065903/135988272-c7643cf4-54a4-4c39-bf07-90845b101097.png)

I really truly fear the monkey that takes 80 shots to kill with a bulldog shotgun.

**Comment by TemporalOroboros** [comment]
<https://github.com/tgstation/tgstation/blob/0626f561179fbb387048269c941c18c56ef6159c/code/datums/elements/weapon_description.dm#L1>

The macro used to calculate the number of shots it takes doesn't guard against complex args. As such this should affect any ammo type with multiple pellets.
