### ISSUE TITLE
Picking up and dropping the greentext says you feel great/shitty, but doesn't do anything to your mood

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#61952]
https://puu.sh/IgA2w/4506d81517.png

I went and found the code and it says like "as long as you leave with this you know you'll be happy" which, fair cop, you haven't left yet so maybe no mood bonus. But when you drop it it says "a sudden wave of failure washes over you" which doesn't actually do anything. Not a bug but it should probably make you sad.

**Comment by Mothblocks** [comment]
Feature requests should go on the forums (or in a pull request), the issue tracker is for bugs

@Mooshimi In the future, please close anything you tag "Not a bug"
