### ISSUE TITLE
Tramstation hydroponics disconnected from powernet & disposals break nearby

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#61954]
Reporting client version: 514.1561

## Round ID:
170880

## Testmerges:
- [species changes part 1: lizards](https://www.github.com/tgstation/tgstation/pull/61440)

## Reproduction:
1. Start the engine on tram.
2. Fix any wires cut by mice.
3. Go to botany.
4. Notice it isn't charging.
5. Check its APC wires using a t-ray scanner and see that the APC isn't connected to the powernet.
6. Flush anything down the disposals in the kitchen.
7. Watch it come flying out the disposal pipe in front of the other botany door.
Seems like this was caused by the PR that swapped the bridge and service.

![image](https://user-images.githubusercontent.com/46474741/136324462-d6f722c9-ad3a-4765-82bb-c5f15269cbc5.png)
An easy fix for the power would be to add a cable at the blue circle, which is where most players who fix the issue place it. The red circle appears to be where the break in the disposals line is.

**Comment by MMMiracles** [comment]
this has been fixed for awhile
