### ISSUE TITLE
Camera Bug on Detective's Spyglasses (i am under the water edition)

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#61998]
## Reproduction:
Replace station tiles with glass tiles
Utilize detective's spyglass kit
Put pocket protector on subject
Put subject on the glass tile
They appear to be under the glass tiles on the spyglass window

![image](https://user-images.githubusercontent.com/34697715/136645642-3a5a7690-f061-4ba3-bdd0-1acfd0695909.png)

[Related video](https://www.youtube.com/watch?v=Bu8bH2P37kY)

**Comment by necromanceranne** [comment]
I think Ive seen this before Tivi's changes so it's not actually his fault I think.

**Comment by timothymtorres** [comment]
It appears that whatever is causing this that the turf and the mobs are on the same plane in the camera window.

**Comment by Sealed101** [comment]
got fixed at some point in time by an agent of virtue (read: most likely lemon and his layer/plane shenanigans)
or #72703 

![изображение](https://github.com/user-attachments/assets/b767e591-f973-4100-ae35-3fae4a851875)
![изображение](https://github.com/user-attachments/assets/5fab5205-844f-4165-8f3a-49dbd36badcf)

**Comment by LemonInTheDark** [comment]
This was likely plane cube
