### ISSUE TITLE
clicking on a door in the alt-click menu shows the ai interface

### ISSUE THREAD

**Issue by KittyNoodle** [tgstation/tgstation#61997]
## Reproduction:

alt click on floor under door.
click on door in menu.
become door god

**Comment by SuperNovaa41** [comment]
Can you give some more info? What type of door, what access did you have, etc etc. I could not recreate this.

**Comment by KittyNoodle** [comment]
I was doing some stuff with the sm room as an engineer with access and learned about this. Just to be clear, you don’t alt click the door, you open up the alt click menu by clicking the floor, then press the door in the menu

**Comment by KittyNoodle** [comment]
weird

**Comment by KittyNoodle** [comment]
okay i forgot a step, the wire panel has to be open for it to work

**Comment by TheBonded** [comment]
okay I managed to reproduce this when the wire panel was open, can't access any of the options, but it's certainly not intentional

**Comment by dragomagol** [comment]
I wasn't able to reproduce this by opening up the wire panel and alt clicking the floor of the open airlock

**Comment by NanoCats** [comment]
I can confirm this is a thing if you click on doors in a couple ways, although I can't remember any of them off the top.

**Comment by dragomagol** [comment]
> after alt clicking the floor, did you click on the door with an empty hand in the status panel where the alt click menu appears? @dragomagol

I was able to reproduce it by clicking on the door in the alt click menu

**Comment by Sealed101** [comment]
#82656 refactored how that menu works and it also seems to have squashed this bug along the way; can no longer reproduce
