### ISSUE TITLE
Objectives screen gets smashed together sometimes, making objectives illegible.

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#62018]
Reporting client version: 514.1561

## Round ID:
171029

## Reproduction:
Not sure if this is a changeling-specific glitch, but:
1. Make yourself into/start as a changeling with random objectives.
2. Open your objectives menu using the button into the top-left.
3. See the following.
![image](https://user-images.githubusercontent.com/46474741/136672399-36269b6d-5874-4b31-94a1-edb3de211f6c.png)
My screen resolution is 1280x720, I don't think it should end up squashed like this.

**Comment by Mooshimi** [comment]
Fixed by... something
