### ISSUE TITLE
McGriff (and other simplemobs) enjoy being jabbed

### ISSUE THREAD

**Issue by TheBonded** [tgstation/tgstation#62014]
## Reproduction:
Get krav mega gloves
Jab McGriff
"McGriff Woofs Happily"
works with any of the other krav mega abilities like lung punch and leg sweep.

![McGriff](https://user-images.githubusercontent.com/58570888/136671008-7f7e68fa-3fb2-40b4-b3cb-c288dec3b1f5.PNG)

**Comment by KittyNoodle** [comment]
kinky

**Comment by ArcaneDefence** [comment]
based
