### ISSUE TITLE
split personality does not like antag status

### ISSUE THREAD

**Issue by KittyNoodle** [tgstation/tgstation#62023]
## Round ID:

so this is a interesting bug. i got locked out of my body by a diffrent split personality bug, but i happened to be a cultist.
So i was put back in my body only to discover that i was in a pseudo cultist state, i had all the spells and shit but i was not healed by pylons and damaged by holy water, i also could not use runes. so the admins gave me cult. however this duplicated the spells. the real problem here being that the split personality breaks antag status

## Reproduction:

give yourself an antag(preferably cult or heretic so you can easily check if the game thinks you are an antag)
give yourself split personality
while the split personality is in control cure the split personality.
put yourself back in your body. 
weird shit starts happening

**Comment by Mooshimi** [comment]
related: #33623

**Comment by Mooshimi** [comment]
Merged with #41601
