### ISSUE TITLE
Nuke does not gib while doomsday device does.

### ISSUE THREAD

**Issue by KittyNoodle** [tgstation/tgstation#62021]
## Round ID:

For some reason the nuke going off does not gib you while the doomsday device does.

## Reproduction:

Detonate nuke.
Notice that you are fine.

**Comment by JohnFulpWillard** [comment]
seems to be closed by https://github.com/tgstation/tgstation/pull/62807 ?
Nuke kills everyone now, just doesnt disintegrate them.
