### ISSUE TITLE
Things taking damage with <= 0 integrity

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#62037]
## Round ID:
[171086](https://scrubby.melonmesa.com/round/171086)
## Reproduction:
![image](https://user-images.githubusercontent.com/85910816/136707302-1239f347-62e4-4b10-908c-caf6b911b68a.png)
![image](https://user-images.githubusercontent.com/85910816/136707391-e354db9a-2444-491d-bed1-368d157be64f.png)

**Comment by Mooshimi** [comment]
![image](https://user-images.githubusercontent.com/85910816/137567742-c6ff7f0d-828b-4abf-9733-428efd19c857.png)

**Comment by SuperNovaa41** [comment]
Closed by https://github.com/tgstation/tgstation/pull/63244
(there might be some that still runtime, feel free to make another issue report about that specific atom)
