### ISSUE TITLE
Some airlocks cant be deconstructed as swarmer's that would not cause a hull breach

### ISSUE THREAD

**Issue by benman347** [tgstation/tgstation#62043]
## Round ID:
[171100](https://scrubby.melonmesa.com/round/171100)

## Reproduction:
on Icebox try to deconstruct the "maintenance access" airlock that leads to the airlocks outside the station below science.
you will get the message: "Destroying this object has the potential to cause a hull breach. Aborting." even though destroying it would not cause a breach.
My guess is that its a small mapping mistake and I am not sure if even other such airlocks exist beside this one.
Searching for more is also quite hard since swarmer's are rare

**Comment by SuperNovaa41** [comment]
Swarmers have been removed. https://github.com/tgstation/tgstation/pull/63989
