### ISSUE TITLE
Multi lavaland tumor combat

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#62065]
## Reproduction: 
You can activate multiple lavaland tumors, which will result in you being teleported back and forth at regular intervals
step 1-activate one lavaland tumor with sentient elite
step 2- activate another lavaland tumor before the first elite comes in
step 3-DOUBLE COMBAT WITH CONSTANT WARPING
And it doesn't stop after dying. The arena does not go away, meaning two sentient lavaland elites are stuck in their respective arenas with a corpse blinking back and forth

**Comment by IndieanaJones** [comment]
Neat.  I'll look into fixing this soon.

**Comment by IndieanaJones** [comment]
I tested this bug locally and I can't reproduce it.  Did the miner perhaps have a memento mori?
