### ISSUE TITLE
Imaginary friend event bugged

### ISSUE THREAD

**Issue by xprtdrt** [tgstation/tgstation#62064]
Reporting client version: 514.1566

## Round ID:
[171137](https://scrubby.melonmesa.com/round/171137)

## Testmerges:
- [Undoes "Removes CHECK_TICK from overlays, following the same theory as instant explosions" (#58382)](https://www.github.com/tgstation/tgstation/pull/61919)

## Reproduction:
im not entirely sure how to reproduce it, judging by an admin's input, it seems random since they experienced both having their own cone of vision, and being shackled to a host. i just became an imaginary friend after death, and i was stuck to my host's field of vision, had no hearing (aside from people speaking), and couldnt shift+left click to examine things, i was forced to shift+right click to pull up the box of options to examine. then at random it swapped to me being able to shift+l-click and not shift+r-click to examine. its very bizzare. Not sure if these were intentional, but i could only sometimes hear comms, and i couldnt point. i also didnt seem to be able to be heard by my host when not in a physical form near him, though that one wasnt confirmed
![imaginaryfriend](https://user-images.githubusercontent.com/91600393/136845757-5d1b735f-494b-4191-abda-a0dd36f64b28.png)

**Comment by Sealed101** [comment]
we've had a refactor and a fix in #71058 and #86863 respectively so hopefully whatever the fuck caused this got chewed up in the refactor woodchipper
