### ISSUE TITLE
MMI Mechs are unable to access airlocks even when given proper ID keycodes for that door.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#62153]
Reporting client version: 514.1568

## Round ID:
[171389](https://scrubby.melonmesa.com/round/171389)

## Testmerges:
- [Undoes "Removes CHECK_TICK from overlays, following the same theory as instant explosions" (#58382)](https://www.github.com/tgstation/tgstation/pull/61919)

## Reproduction:
Prior incidents and being a cripple got my brain placed into an MMI and into a Clark mech. Later in the round the Captain wished to give me access to cargo in order to assist with the lack of mining going on. Both the Captain and a Miner confirmed that the access was added to the mech, but I couldn't access anything even if it was added to the mech. 

An admin confirmed it wasn't just a mapping error, and told me to make an issue report about it since it seems like a bug more likely than not.

**Comment by Potato-Masher** [comment]
The wiki claims that adding the access ID locks the mech, but also adds the access to the mech so at least when the wiki was written it probably worked? I swear this was a thing at one point as well.

**Comment by JohnKiwols** [comment]
I can confirm that swiping the mech with your card was how it previously worked. That being said, I imagine MMI and posibrain's ought to have full access: they just as easily could have been put in a borg or AI core.  They dont have laws though.. hmm.  Regardless of what they're intended to have, would my observation in  #69085 be why they currently don't? I'm quite curious if I was on the right track.
