### ISSUE TITLE
Possible bug with accounting debug machine (/obj/machinery/accounting) and vendors.

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#62167]
## Round ID:
[171436](https://scrubby.melonmesa.com/round/171436)

## Testmerges:
Reproduced on private server with
Master commit: a28030ee3a2f1ef4b81e31c0f66cd26ebef42d1f

## Reproduction:

Spawn in at thunderdrome (or whatever)
Spawn in a vending machine e.g. /obj/machinery/vending/cola
Set Outfit yourself to Assistant
Spawn in /obj/machinery/accounting
Insert your ID card into the machine, remove it, reinsert it into your ID card slot
Open the vendor
Get NtOS error

 
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 TypeError: Unable to get property 'Space Cola' of undefined or null reference
   at Anonymous function (http://127.0.0.1:63771/tmp25860/tgui.bundle.js:1:1466513)
   at Anonymous function (http://127.0.0.1:63771/tmp25860/tgui.bundle.js:1:41117)
   at map (http://127.0.0.1:63771/tmp25860/tgui.bundle.js:1:90918)
   at t.Vending (http://127.0.0.1:63771/tmp25860/tgui.bundle.js:1:1465567)
   at Ie (http://127.0.0.1:63771/tmp25860/tgui.bundle.js:1:179481)
   at Anonymous function (http://127.0.0.1:63771/tmp25860/tgui.bundle.js:1:179749)
   at Le (http://127.0.0.1:63771/tmp25860/tgui.bundle.js:1:179727)
   at Anonymous function (http://127.0.0.1:63771/tmp25860/tgui.bundle.js:1:181344)
   at Pe (http://127.0.0.1:63771/tmp25860/tgui.bundle.js:1:181213)
   at Fe (http://127.0.0.1:63771/tmp25860/tgui.bundle.js:1:186478)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"iain0","interface":"Vending","window":{"key":"[0x201121f]-main","size":null,"fancy":1,"locked":1}}

Nanotrasen (c) 2525-2561 

If additionally you delete your mob, return to lobby, join as assistant, TP back to your vendor, then the interface will work normally.

Also, if you drop the ID card, the interface opens, but without the ability to buy anything of course.

Console dumped the following runtimes too:

[02:34:04] Runtime in _vending.dm,790: Cannot read /datum/job/assistant (/datum/job/assistant).title
  proc name: ui data (/obj/machinery/vending/ui_data)
  usr: iain0/(Bob Stange)
  usr.loc: (Thunderdome Arena (167,50,1))
  src: the Robust Softdrinks (/obj/machinery/vending/cola)
  src.loc: the floor (167,51,1) (/turf/open/floor/iron)
  call stack:
  the Robust Softdrinks (/obj/machinery/vending/cola): ui data(Bob Stange (/mob/living/carbon/human))
  /datum/tgui (/datum/tgui): get payload(null, 1, 1)
  /datum/tgui (/datum/tgui): open()
  the Robust Softdrinks (/obj/machinery/vending/cola): ui interact(Bob Stange (/mob/living/carbon/human), /datum/tgui (/datum/tgui))
  the Robust Softdrinks (/obj/machinery/vending/cola): interact(Bob Stange (/mob/living/carbon/human), null)
  the Robust Softdrinks (/obj/machinery/vending/cola): interact(Bob Stange (/mob/living/carbon/human), null)
  the Robust Softdrinks (/obj/machinery/vending/cola):  try interact(Bob Stange (/mob/living/carbon/human))
  the Robust Softdrinks (/obj/machinery/vending/cola):  try interact(Bob Stange (/mob/living/carbon/human))
  the Robust Softdrinks (/obj/machinery/vending/cola):  try interact(Bob Stange (/mob/living/carbon/human))
  the Robust Softdrinks (/obj/machinery/vending/cola): attack hand(Bob Stange (/mob/living/carbon/human), /list (/list))
  the Robust Softdrinks (/obj/machinery/vending/cola): attack hand(Bob Stange (/mob/living/carbon/human), /list (/list))
  Bob Stange (/mob/living/carbon/human): UnarmedAttack(the Robust Softdrinks (/obj/machinery/vending/cola), 1, /list (/list))
  Bob Stange (/mob/living/carbon/human): ClickOn(the Robust Softdrinks (/obj/machinery/vending/cola), "icon-x=18;icon-y=18;left=1;scr...")
  the Robust Softdrinks (/obj/machinery/vending/cola): Click(the floor (167,51,1) (/turf/open/floor/iron), "mapwindow.map", "icon-x=18;icon-y=18;left=1;scr...")
  Iain0 (/client): Click(the Robust Softdrinks (/obj/machinery/vending/cola), the floor (167,51,1) (/turf/open/floor/iron), "mapwindow.map", "icon-x=18;icon-y=18;left=1;scr...")
[02:36:21] Runtime in economy.dm,75: Cannot read /datum/job/assistant (/datum/job/assistant).paycheck
  proc name: fire (/datum/controller/subsystem/economy/fire)
  src: Economy (/datum/controller/subsystem/economy)
  call stack:
  Economy (/datum/controller/subsystem/economy): fire(0)
  Economy (/datum/controller/subsystem/economy): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)

**Comment by ArcaneMusic** [comment]
The Accounting machine was removed last month, forgot to check for related issues. Should have been fixed as well by having a default bank account on all ID cards too.
