### ISSUE TITLE
Experiments that were not completet will not be removed from the Experi-Scanner after the tech was researched

### ISSUE THREAD

**Issue by techno0** [tgstation/tgstation#62175]
## Reproduction: 
Research Advanced Electromagnetic Theory for example. Then look at the Experi-Scanner, the experiment will still be there.

https://i.imgur.com/8s3SlJJ.png

**Comment by Sealed101** [comment]
not really a bug IMO, there are discount experiments that are used by more than one node. 
i guess it could be helpful if the discount experiment was showing the nodes it affects in the experiment handler UI, so you could see whether the nodes were researched or not?
