### ISSUE TITLE
Android's wings missing a sprite

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#62187]
## Reproduction:

Be android
Drink flight potion
No sprites
![Screenshot_138](https://user-images.githubusercontent.com/64209864/137767720-53dbe88c-dd4a-4f95-90e2-18a152717cc6.png)

**Comment by mozi-h** [comment]
Could not reproduce. The wings are invisible, but the character itself is fine. Organ has been granted and works as intended.

![](https://i.imgur.com/cZez0gP.png)

**Comment by itseasytosee** [comment]
I just sifted through this hell and have concluded that in fact, it was not a Good First Issue.
