### ISSUE TITLE
Power consuming devices glitch

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#62182]
## Round ID: [171490](https://scrubby.melonmesa.com/round/171490)

![image](https://user-images.githubusercontent.com/14065903/137650803-ac366d61-ea55-4ce2-aec6-53b1cd5269c9.png)

For some reason, cell chargers wouldn't work in this room I made, it was designated with blueprints, had its own APC, and most of the equipment worked fine, but a cell charger in that room was just like "nah I'm not feeling it"

I tried a load of shit, nothing worked, I settled on just having to charge my batteries outside an bring them in, shrug.

**Comment by newfren** [comment]
I noticed this not working when I added an apc to the ufo white ship too.

**Comment by NanoCats** [comment]
> were the cell chargers anchored and were their panels closed?

Yes, you can't put the battery in if this is not the case, and it just sat there flashing the red light (0-10% charge)

**Comment by TheBonded** [comment]
this one, I assume https://github.com/tgstation/tgstation/pull/54989

**Comment by Sealed101** [comment]
can't reproduce; a powercell in a newly created and APC-kitted area correctly draws power from the powernet with no problem

https://github.com/tgstation/tgstation/pull/82565 or https://github.com/tgstation/tgstation/pull/54989 may have done something. that or some other powernet refactor
