### ISSUE TITLE
AutoDrobe and ClothesMate missing items clearly designated to be in there

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#62213]
## Round ID:
N/A

## Testmerges:
N/A (?)

## Reproduction:
Walk up to a vendor and open the menu. Scroll a bit and get mad.
Examples include:
- Cyborg suit in AutoDrobe (Cyborg Visor sits in there alone, only known appearance of the proper set is MetaStation maintenance garden for some reason)
- Eyepatch from the pirate sets in AutoDrobe (appears properly when the costumes spawn randomly on the station)
- Lobster mask from the animal mask collection in AutoDrobe (only spawns in theatre backstage on Kilo)
- Beige suit & fedora (?) [only spawns randomly (MetaStation dorms rack), while other sets of this kind are available from the ClothesMate too]

**Comment by TheBonded** [comment]
> Lobster mask from the animal mask collection in AutoDrobe (only spawns in theatre backstage on Kilo)

This was a pain to find because as it turns out it's not considered a mask, but a costume hat, so it wasn't with the other animal masks in the code. I also went to the liberty of adding the costume included with it.

**Comment by Mooshimi** [comment]
https://github.com/tgstation/tgstation/pull/62272#issuecomment-949003315 The discussed in the pr but this isn't considered an issue apparently, but by design.
