### ISSUE TITLE
Hierophant club doesnt recharge

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#62283]
## Reproduction:
Get hierophant club
Use blink once
It was the last time you used it, no recharge and icon stay the same.

**Comment by tgsAvylaar** [comment]
Correct, this CAN happen at any given point after using it. Once the issue occurs, I believe the hiero club never recharges.

**Comment by rasepretep** [comment]
Issue still happens, seemingly at random. Last time I had it happen was round 177042 on Manuel.

**Comment by JohnFulpWillard** [comment]
I think it has something to do with dropping the beacon/putting it in your bag, while its trying to recharge.
