### ISSUE TITLE
The message explaining why you can't purchase a shuttle is cut off.

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#62336]
## Testmerges:
The following pull requests are currently test merged:
#61919: 'Undoes "Removes CHECK_TICK from overlays, following the same theory as instant explosions" (#58382)' by LemonInTheDark at commit d84750d4f6

## Reproduction:
Get the shuttle insurance event (maybe? there was an intern and no clear way to pay insurance if it had occured)
Hover over the purchase shuttle button.
The pop up that explains why it's greyed out appears to the right of the button, showing just a few letters before it's cut off by the edge of the window. Expanding the window just expands the length of the button. Sorry I had a screenshot but then I copied the test merges so now it's gone woops.

**Comment by Sealed101** [comment]
fixed by #67935 probably
![изображение](https://github.com/user-attachments/assets/f017a538-3384-491f-b705-9e308eb17c85)
