### ISSUE TITLE
You can't sentience potion hauberoaches or cows

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#62333]
## Testmerges:
The following pull requests are currently test merged:
#61919: 'Undoes "Removes CHECK_TICK from overlays, following the same theory as instant explosions" (#58382)' by LemonInTheDark at commit d84750d4f6

## Reproduction:
use an intelligence potion on a hauberoach
The hauberoach is already too intelligent for this to work!

tried on a couple different roaches

**Comment by tralezab** [comment]
fixed with #63116
