### ISSUE TITLE
Ethereal ethereal_light is null

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#62355]
## Reproduction:
![image](https://user-images.githubusercontent.com/85910816/138879004-61795ca8-65fa-409a-bcb1-178b71dad639.png)
![image](https://user-images.githubusercontent.com/85910816/138879211-4de22d60-a151-4f65-8efe-4d02b2db3d2c.png)

**Comment by KittyNoodle** [comment]
This seems to be fixed by the dna fix, @Mooshimi could you close this?

**Comment by Mooshimi** [comment]
> This seems to be fixed by the dna fix, @Mooshimi could you close this?

Yes
