### ISSUE TITLE
Dullahans' heads have different names than their bodies

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#62411]
Reporting client version: 514.1568

## Round ID:
[172065](https://scrubby.melonmesa.com/round/172065)

## Testmerges:
- [Vampire and Dullahan can be config enabled](https://www.github.com/tgstation/tgstation/pull/62357)
- [[DNM] [TM Candidate] Infuses certain vents with an aroma of garlic, repelling bat form vampires.](https://www.github.com/tgstation/tgstation/pull/61816)
- [Fixes issue with VALUE_MODE_FLAG config entries trying to parse values from keys.](https://www.github.com/tgstation/tgstation/pull/62359)

## Reproduction:
Be a Dullahan (player name was **Edgarius The Third**).
Examine your head. 
See head has a different name (head name was **Cruz Shick's head**)

**Comment by JohnFulpWillard** [comment]
This is only a problem for roundstart dullahans, I am assuming dullahan's on_species_gain is running before the dullahan even has a name, as 'owner' in the head's drop_limb proc is null on roundstart dullahan.
