### ISSUE TITLE
Items with no FLAMMABLE resistance flag will not have a fire overlay despite taking damage from being on fire

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#62420]
See #59597 and #62146
https://github.com/tgstation/tgstation/blob/a78f35ad927be5888bef23a0e9664a7baa9db204/code/game/objects/obj_defense.dm#L127-L139
https://github.com/tgstation/tgstation/blob/a78f35ad927be5888bef23a0e9664a7baa9db204/code/game/objects/objs.dm#L388-L391

**Comment by LemonInTheDark** [comment]
Why is this a bug?
