### ISSUE TITLE
Fear of greytide includes security and explorer gas masks

### ISSUE THREAD

**Issue by TheBonded** [tgstation/tgstation#62452]
Reporting client version: 514.1569

## Round ID:
[172166](https://scrubby.melonmesa.com/round/172166)

## Testmerges:
- [Undoes "Removes CHECK_TICK from overlays, following the same theory as instant explosions" (#58382)](https://www.github.com/tgstation/tgstation/pull/61919)
- [Fixes halloween roundstart species](https://www.github.com/tgstation/tgstation/pull/62427)

## Reproduction:
Get fear of greytide phobia
Die because you get scared of a security gas mask

**Comment by KittyNoodle** [comment]
also happens with the captain's gas mask.

**Comment by phasenoisepon** [comment]
Probably because the phobia checks the mask and all subtypes of

**Comment by phasenoisepon** [comment]
```
/datum/brain_trauma/mild/phobia/greytide
	phobia_type = "greytide"
	random_gain = FALSE
```

```
	"greytide" = typecacheof(list(/obj/item/clothing/under/color/grey, /obj/item/melee/baton/security/cattleprod,
		/obj/item/spear, /obj/item/clothing/mask/gas, /obj/item/toy/figure/assistant,
		/obj/structure/statue/sandstone/assistant
	)),
```
