### ISSUE TITLE
Ahealing deletes all restraints in pockets

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#62459]
Reporting client version: 514.1557

## Round ID:
[172178](https://scrubby.melonmesa.com/round/172178)

## Testmerges:
- [Undoes "Removes CHECK_TICK from overlays, following the same theory as instant explosions" (#58382)](https://www.github.com/tgstation/tgstation/pull/61919)
- [Fixes halloween roundstart species](https://www.github.com/tgstation/tgstation/pull/62427)

## Reproduction:
Not related to current round, just completely forgot about it. Put cuffs in pocket, aheal yourself with admin powers, observe how the cuffs disappear. I know it's intended to remove cuffs when wearing them, but not from the pocket.

**Comment by phasenoisepon** [comment]
Appears intentional?

https://github.com/tgstation/tgstation/blob/f03fd9dd8ab697a3653e7945c156e23d637218a8/code/modules/mob/living/carbon/carbon.dm#L832
