### ISSUE TITLE
Mind transferring into the ghost of Poly makes you invicible

### ISSUE THREAD

**Issue by NoobTart** [tgstation/tgstation#62465]
## Testmerges:
#62427 
#61919 
#61816 

## Reproduction:
Take a xenobiology mind transference potion that can be made by injecting blood into a rainbow slime core.
Use it on the ghost of Poly and become them.
Kill people, megafauna and other mobs without being able to be killed.

**Comment by Qydra** [comment]
I fail to see the problem. #HailPoly

**Comment by TheBonded** [comment]
give it a fugu gland to allow you to just up and murder anything, including every megafauna

**Comment by TheBonded** [comment]
this isn't a bug, as it's intentional for the ghost of poly to be invincible and it's intentional to be able to mindswap into simplemobs. just slap the same check that goes on megafauna to prevent them from being sentient and you'll be fine
