### ISSUE TITLE
Teslium activation is broken.

### ISSUE THREAD

**Issue by Nebulacrity** [tgstation/tgstation#62461]
## Reproduction:
I have put a beaker with 50u of Teslium and a beaker with 50u of Water into my custom grenade. I have made 3 such grenades in total. When the grenades activated, nothing happened all 3 times, only the electricity noise & particles appeared.

There should've been 2 Tesla bolts spawned every time one of these grenades were activated, as the amount of Teslium participating in the reaction was greater than 40u.

**Comment by necromanceranne** [comment]
have you tried this with more than 50u of each reagent? Say, 100u of teslium and 100u of water?

**Comment by Nebulacrity** [comment]
Nope.

**Comment by LemonInTheDark** [comment]
those grenades stick around post trigger right?

**Comment by Nebulacrity** [comment]
> those grenades stick around post trigger right?

Yes. I triggered them, threw them, and they activated after the set 3 seconds, yielding naught but spark particles.

**Comment by TemporalOroboros** [comment]
Same issue as gunpowder. The effect is on a delay so the grenade deletes itself before the effect occurs.
