### ISSUE TITLE
Using a bluespace body bag inhand causes the user to be put inside the bag, even while its open.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#62478]
Reporting client version: 514.1568

## Round ID:
[172218](https://scrubby.melonmesa.com/round/172218)

## Testmerges:
- [Fixes halloween roundstart species](https://www.github.com/tgstation/tgstation/pull/62427)
- [Undoes "Removes CHECK_TICK from overlays, following the same theory as instant explosions" (#58382)](https://www.github.com/tgstation/tgstation/pull/61919)
- [[DNM] [TM Candidate] Infuses certain vents with an aroma of garlic, repelling bat form vampires.](https://www.github.com/tgstation/tgstation/pull/61816)

## Reproduction:
1. print body bag
2. use it in hand to place it
3. get unexpectedly put inside the bag, even while it is visibly open on the floor.
During the round, I also ended up stuck inside the bag  (attempting to move or resist out of the bag wasn't doing anything) while this happened. Closing and opening the bag a couple times fixes it until it is picked up and placed again.

**Comment by TemporalOroboros** [comment]
Sounds like the bodybag is running the mapload proc when it's placed down.

**Comment by redguy999** [comment]
nevermind its not happening anymore
