### ISSUE TITLE
lighting creating blobs of light in areas you can't see

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#62470]
## Round ID:
[172205](https://scrubby.melonmesa.com/round/172205)

## Testmerges:
#62427 #61816 #61919 

## Reproduction:
Get a light producer, throw it somewhere where you can see the light producer but not see where it projects the light, get a big glob of whiteness
![lights](https://user-images.githubusercontent.com/75639936/139541620-21385624-ab3a-4745-8118-1cb00426b177.PNG)

**Comment by timothymtorres** [comment]
This was probably fixed with https://github.com/tgstation/tgstation/pull/62902
