### ISSUE TITLE
Heretic Mask of madness stacking.

### ISSUE THREAD

**Issue by Jelibeen** [tgstation/tgstation#62485]
## Reproduction:
Mask of Madness effect stacks with more than one mask wearer on screen. This is being used by heretics fireman carrying a cuffed person with a mask forced on them while the heretic also has one. The rate of stamina damage in this situation seems way more than intended. I watched this being used to give people 90% fatigue damage in the time it takes to pass them in the halls. Fighting this is almost impossible. You have less than five seconds after being on screen with the 2 mask wearers before falling into stamina crit that is impossible recover from unless they are no longer on screen.

**Comment by theta006** [comment]
this isnt a bug

**Comment by Jelibeen** [comment]
oh it's not?! cool then I will use it every heretic round until everyone is screaming for a nerf. I find it hard to believe that is intended. Only real counter to it is to rush as a hulk, not even sure how much that would help.

**Comment by theta006** [comment]
> oh it's not?! cool then I will use it every heretic round until everyone is screaming for a nerf. I find it hard to believe that is intended. Only real counter to it is to rush as a hulk, not even sure how much that would help.

go for it you can say that with anything oh delaming the SM isn't a bug? I will use it every round until everyone is screaming for a fix

**Comment by TheBonded** [comment]
> > oh it's not?! cool then I will use it every heretic round until everyone is screaming for a nerf. I find it hard to believe that is intended. Only real counter to it is to rush as a hulk, not even sure how much that would help.
> 
> go for it you can say that with anything oh delaming the SM isn't a bug? I will use it every round until everyone is screaming for a fix

Its an oversight, not a bug. remember when chemists would make corazargh every shift and just kill everyone they wanted since it was super powerful (it still is but shhh). or when people would abuse having a telebaton and stun baton to bypass the cooldown?

Also, xenobiology stable extracts don't stack. because if they did it would be really powerful. I agree with @Jelibeen here. even though heretic is disabled on mrp, I can't imagine this being fun at all on lrp.

**Comment by Jelibeen** [comment]
> > > oh it's not?! cool then I will use it every heretic round until everyone is screaming for a nerf. I find it hard to believe that is intended. Only real counter to it is to rush as a hulk, not even sure how much that would help.
> > 
> > 
> > go for it you can say that with anything oh delaming the SM isn't a bug? I will use it every round until everyone is screaming for a fix
> 
> Its an oversight, not a bug. remember when chemists would make corazargh every shift and just kill everyone they wanted since it was super powerful (it still is but shhh). or when people would abuse having a telebaton and stun baton to bypass the cooldown?
> 
> Also, xenobiology stable extracts don't stack. because if they did it would be really powerful. I agree with @Jelibeen here. even though heretic is disabled on mrp, I can't imagine this being fun at all on lrp.

Yeah I found a way to do it with 3 masks at once. No way in hell this is intended. Either it gets patched or my next heretic round is gonna be very annoying.

**Comment by TheBonded** [comment]
> > > > oh it's not?! cool then I will use it every heretic round until everyone is screaming for a nerf. I find it hard to believe that is intended. Only real counter to it is to rush as a hulk, not even sure how much that would help.
> > > 
> > > 
> > > go for it you can say that with anything oh delaming the SM isn't a bug? I will use it every round until everyone is screaming for a fix
> > 
> > 
> > Its an oversight, not a bug. remember when chemists would make corazargh every shift and just kill everyone they wanted since it was super powerful (it still is but shhh). or when people would abuse having a telebaton and stun baton to bypass the cooldown?
> > Also, xenobiology stable extracts don't stack. because if they did it would be really powerful. I agree with @Jelibeen here. even though heretic is disabled on mrp, I can't imagine this being fun at all on lrp.
> 
> Yeah I found a way to do it with 3 masks at once. No way in hell this is intended. Either it gets patched or my next heretic round is gonna be very annoying.

how powerful is 3 masks at once?

**Comment by ATH1909** [comment]
> how powerful is 3 masks at once?

each mask seems to have around a 30% chance per second to deal 10 stamina damage

**Comment by necromanceranne** [comment]
It's a permastun after enough masks. Yes, this apparently is intended. Yes it's dumb.

**Comment by Jelibeen** [comment]
Intended? Time to use a bag full of bluespace body bags with full of masked dead guys along with one on my shoulder and another being dragged. Either this complete joke of a balanced game mechanic gets changed because it is obviously dumb or I will force it.

**Comment by TheBonded** [comment]
> Intended? Time to use a bag full of bluespace body bags with full of masked dead guys along with one on my shoulder and another being dragged. Either this complete joke of a balanced game mechanic gets changed because it is obviously dumb or I will force it.

have you ever heard of the telescience clause?

**Comment by Jelibeen** [comment]
> have you ever heard of the telescience clause?
No but let me guess, some kind of rule to stop people abusing obviously broken OP game mechanics. I argue that if you need a rule to stop something being used to ruin the round it is too powerful and shouldn't exist.

**Comment by TheBonded** [comment]
> > have you ever heard of the telescience clause?
> 
> No but let me guess, some kind of rule to stop people abusing obviously broken OP game mechanics. I argue that if you need a rule to stop something being used to its full potential from ruining rounds it is too powerful and it shouldn't exist.
> 
> simple fix : add diminishing returns to mask stacking, or even better make them not stack at all.

It's not a rule in place by the admins or host or anything like that. Telescience was an old part of science that was removed ages ago because people abused the hell out of it. Since then the players have bound together and decided that if they ever come across a super powerful feature they won't abuse the shit out of it like they did with telescience, forming the telescience clause.

**Comment by Jelibeen** [comment]
Sounds like the prisoner's dilemma to me haha. That always ends up playing out the same way. All it would take it one to ruin it for everyone. Would be better if that kind of gentlemen's agreement wasn't necessary. I don't see the benefit at all of leaving things so brokenly powerful in the game.

**Comment by TheBonded** [comment]
> 
> 
> Sounds like the prisoner's dilemma to me haha. That always ends up playing out the same way. All it would take is one to ruin it for everyone. Would be better if that kind of gentlemen's agreement wasn't necessary. I don't see the benefit at all of leaving things so brokenly powerful in the game.

because the time spent fixing this could be better used on other issues that are caused by faulty code or otherwise messes up gameplay without needing someone to be abusing it. This is an open source codebase, and if players agree to not abuse bugs then the coders can spend their time on adding new features like MODsuits instead of wasting time cleaning up after the playerbase

**Comment by Jelibeen** [comment]
I see. Thanks for explaining that. I didn't understand but that makes perfect sense. it's about limited available development work hours and how they could best be used. Okay I agree to the telescience clause. You will see no 30 masked bodies in a backpack from me.
