### ISSUE TITLE
rust heretic can be stuned on rust 

### ISSUE THREAD

**Issue by theta006** [tgstation/tgstation#62480]
Reporting client version: 514.1569

## Round ID:
[172229](https://scrubby.melonmesa.com/round/172229)

## Testmerges:
- [Fixes halloween roundstart species](https://www.github.com/tgstation/tgstation/pull/62427)
- [[DNM] [TM Candidate] Infuses certain vents with an aroma of garlic, repelling bat form vampires.](https://www.github.com/tgstation/tgstation/pull/61816)

## Reproduction: be rust heretic on a rust floor with the path thing that makes you stun proof on rust get hit by dets baton and you get stuned 

you get stuned with dets baton while on rust this shouldnt happen

**Comment by SuperNovaa41** [comment]
https://github.com/tgstation/tgstation/pull/58060
Only with leeching walk, you sure you were powerful enough?

**Comment by D4C-420** [comment]
that said an ascended heretic on rust tiles can still be stun locked by armsky (and probably beepsky) like what happened to me in round 171895. not sure if thats intentional or not.

**Comment by theta006** [comment]
> #58060 Only with leeching walk, you sure you were powerful enough?

yes i was right before dets i face tanked a stun emag and a few stun batons

**Comment by MrMelbert** [comment]
stun resistance =/= stun immunity 

stun resistances gives you resistance to the knockdown of a stun baton but it can still stamcrit you

> ascended heretic on rust tiles can still be stun locked by armsky

Unfortunately it gives stamina regen and stun resistance but armsky/beepsky hardstun so it doesn't come into play

**Comment by theta006** [comment]
> stun resistance =/= stun immunity
> 
> stun resistances gives you resistance to the knockdown of a stun baton but it can still stamcrit you
> 
> if you were ascended, it _might_ be a bug with the traits it applies

i was stam crit from taking a egun to the face and a few batons why can dets baton stun me and not the others?

**Comment by KittyNoodle** [comment]
Because det batons and telebatons work differently than regular batons

**Comment by timothymtorres** [comment]
I'm going to label this `Not a Bug` and it will auto-close in 7 days unless someone can convince me otherwise.  If I'm not mistaken det baton and telebatons cause KNOCKDOWN, which isn't the same thing as STUN or STAM CRIT.  This smells like a balance issue if anything.

**Comment by SuperNovaa41** [comment]
> I'm going to label this `Not a Bug` and it will auto-close in 7 days unless someone can convince me otherwise. If I'm not mistaken det baton and telebatons cause KNOCKDOWN, which isn't the same thing as STUN or STAM CRIT. This smells like a balance issue if anything.

Yeah those batons cause knockdown. I know STUN_IMMUNITY gives protection from knockdown but idk about STUN_RESISTANCE.
