### ISSUE TITLE
ethereals do not regenerate blood

### ISSUE THREAD

**Issue by KittyNoodle** [tgstation/tgstation#62492]
## Reproduction:

Loose blood as an ethereal, wait for regen, it never happens.

**Comment by theta006** [comment]
dont they regen blood when they eat the high power thing in food venders

**Comment by KittyNoodle** [comment]
That is because the chemical in there gives them blood, more like iron then the normal passive blood regen that everyone else has

**Comment by LemonInTheDark** [comment]
isn't this intended?

**Comment by KittyNoodle** [comment]
If it is it is a massive balance issue as ethereals die from a minor cut.

**Comment by timothymtorres** [comment]
I'm linking #52270 and #60927 to this since it is related.

**Comment by LemonInTheDark** [comment]
Not a bug
