### ISSUE TITLE
shucking gatfruits puts the .357 in your OTHER hand

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#62514]
Shucking a gatfruit will put the .357 in it in your off hand, not the hand that the gatfruit was in. If your off hand was occupied, the .357 will just be dropped on the ground.

That isn't how this used to work, and it makes dual-wielding (and even just normal combat) with gatfruits really fiddly and annoying.

**Comment by timothymtorres** [comment]
Shucking?

**Comment by TheBonded** [comment]
> Shucking?

you can use a gatfruit in hand to remove the gun from the inside. this works as well with bananas and their subtypes to get the banana peel, you're effectively peeling the fruit to get whatever non food item it gives you.
