### ISSUE TITLE
I cannot give people maint access anymore.

### ISSUE THREAD

**Issue by KittyNoodle** [tgstation/tgstation#62521]
## Reproduction:

1. attempt to give someone who does not normally have maint access maint access.
2. fail

**Comment by Timberpoes** [comment]
![lJP6qu4Ngs](https://user-images.githubusercontent.com/24975989/139778861-5b78baa5-d002-4ac0-84f1-668a8cc36c0b.gif)

![skill-issue-roblox](https://user-images.githubusercontent.com/24975989/139778851-0bb5a481-dc49-4d8b-a46c-1a4059c1e193.gif)

**Comment by timothymtorres** [comment]
We need more step-by-step information on what happened to replicate it.

**Comment by TheBonded** [comment]
> We need more step-by-step information on what happened to replicate it.

@timothymtorres As far as I can tell, the step-by-step instructions for this would be

Step 1: Insert a HoP or captain ID into the login ID slot on a modular computer access manager
Step 2: Insert any ID without maintenance access into the target ID slot on the same computer
Step 3: Attempt add maintenance access to the ID by clicking on the check mark box next to the maintenance access under common>engineering
Step 4: It unchecks the check box immediately, making it impossible to add maintenance access to the ID

This is what I could transcribe from the first gif posted in Timberpoes comment, I don't know if this is what happens in game, but it does seem to be what happens in that gif.

**Comment by KittyNoodle** [comment]
what seems to be happening with me is that when i go to "common" access it does not have any tabs other than general, preventing me from giving maint access

**Comment by TheBonded** [comment]
that's probably what happened, since it's hard to be 100% sure I understand Timberpoes properly

**Comment by Timberpoes** [comment]
> 
> 
> What I said was probably wrong then, since it's hard to be 100% sure I understand Timberpoes properly

Oh yeah. I was just spamclicking the maint access button. Giving the card access worked just fine.

**Comment by Timberpoes** [comment]
What would be useful to know is > What ID card did you use - HoP, Cap's Spare, other Head of Staff ID, normal job ID? What machine did you use to change the access? Mod computer? Laptop? Tablet? Was this on our servers or another server?

Those sorts of details help it actually be replicated.

What it SOUNDS like is you used an ID without the ACCESS_CHANGE_IDS/ID Console access on it - Like a modified HoP ID with that removed for example, or another Head of Staff ID that wasn't CE.

If I had the round number it happened in, all ID card access changes are logged and I'd be able to tell better.

**Comment by TheBonded** [comment]
> 
> 
> > What I said was probably wrong then, since it's hard to be 100% sure I understand Timberpoes properly
> 
> Oh yeah. I was just spamclicking the maint access button. Giving the card access worked just fine.

oh im just blind then

**Comment by KittyNoodle** [comment]
> What would be useful to know is > What ID card did you use - HoP, Cap's Spare, other Head of Staff ID, normal job ID? What machine did you use to change the access? Mod computer? Laptop? Tablet? Was this on our servers or another server?
> 
> Those sorts of details help it actually be replicated.
> 
> What it SOUNDS like is you used an ID without the ACCESS_CHANGE_IDS/ID Console access on it - Like a modified HoP ID with that removed for example, or another Head of Staff ID that wasn't CE.
> 
> If I had the round number it happened in, all ID card access changes are logged and I'd be able to tell better.

i did it with the captain's id

**Comment by timothymtorres** [comment]
> oh im just blind then

Yea I couldn't understand timberpoes that well either.  I assumed it was sarcasm but wasn't 100% certain.

> i did it with the captain's id

Did you make this bug report immediately during/after the round this happened?  What was your player name and byond account?  We should be able to dig up the logs based off this.

**Comment by KittyNoodle** [comment]
I updated my testing branch and it went away, seems to have been fixed
