### ISSUE TITLE
`\improper` in area names is fucking up security camera monitor networks

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#62528]
## the gist of it
newly built cameras and the autoname camera subtype get their c_tag from the area's name. some areas have `\improper` in their name while others don't. cameras in those areas that don't have the `\improper` in their name work fine and show up on the computer screen as intended. cameras in those areas that do have the `\improper` in their name show up as static, while also disabling the buttons on the top right of the UI
code for switching to the cameras:
https://github.com/tgstation/tgstation/blob/1ac8af780bd2d391acbae40b94e295695f66ab74/code/game/machinery/computer/camera.dm#L122-L134
## all available cameras
spot the ugly duckling and receive a cookie (shipment fees applicable)
![image](https://user-images.githubusercontent.com/75863639/139819642-84c885fe-cd45-4a52-9d7b-54c83202c31a.png)
### `\improper` fan
![image](https://user-images.githubusercontent.com/75863639/139820688-48baed09-ccf6-4843-b4da-7e5c1ddce901.png)

![image](https://user-images.githubusercontent.com/75863639/139819611-987a2195-c847-4dc1-aae3-3e27f38f58ea.png)
![image](https://user-images.githubusercontent.com/75863639/139819729-0b4f030c-245c-446a-a075-bb145a88f8c9.png)
### no `\improper` enjoyer
![image](https://user-images.githubusercontent.com/75863639/139820639-29c5725b-7202-4e7e-9cc6-27ed8f93bb80.png)

![image](https://user-images.githubusercontent.com/75863639/139819353-02beb9db-e907-49f0-8e96-133db53b101a.png)
![image](https://user-images.githubusercontent.com/75863639/139819490-9012b0e5-101c-46ac-940f-aac55407bba2.png)

**Comment by Sealed101** [comment]
its uh probably a good idea to mention that pretty much everything that uses `\improper` has weird symbols before it's name in the small examine pop-up we have in the bottom left of the screen. it's been an issue for quite a while now and i am very sure it appeared after a byond update, but i can't really put a finger on when exactly did it start.

**Comment by timothymtorres** [comment]
@Sealed101 good code diving.  This should fix a lot of the camera static issues.

**Comment by Sealed101** [comment]
is still an issue
