### ISSUE TITLE
Diagnostic huds don't detect launchpad location

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#62543]
Reporting client version: 514.1557

## Round ID:
[172406](https://scrubby.melonmesa.com/round/172406)

## Testmerges:
- [Fixes halloween roundstart species](https://www.github.com/tgstation/tgstation/pull/62427)
- [Undoes "Removes CHECK_TICK from overlays, following the same theory as instant explosions" (#58382)](https://www.github.com/tgstation/tgstation/pull/61919)
- [[DNM] [TM Candidate] Infuses certain vents with an aroma of garlic, repelling bat form vampires.](https://www.github.com/tgstation/tgstation/pull/61816)

## Reproduction:
get diagnostic hud, get launchpad set up and move the cursor any direction, wear diagnostic hud and look for the cursor, don't find it, cry. also it seems to work through the camera though, but not in person.

**Comment by moocowswag** [comment]
Can confirm it works through camera console but not in person.

**Comment by etherware-novice** [comment]
@ShizCalev hi this issue wasnt closed after the related issue was
