### ISSUE TITLE
The default Tramstation configuration melts the portable scrubbers.

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#62566]
I hope this is ok to submit as an issue but if I connect the scrubbers up to their designated ports, they just sizzle and get destroyed (melted??)  This was near the start of a shift so I don't think this is thermomachine related.

![image](https://user-images.githubusercontent.com/14065903/140261943-a80b56bb-69f5-4694-8b37-2d3cad087bd0.png)

**Comment by Paxilmaniac** [comment]
I think what's happening here is that they are probably connected directly to the scrubbers network, which especially near the start of the round will be unreasonably hot due to thermomachines literally anywhere. Ghilker atmos working as intended as always.

**Comment by NanoCats** [comment]
> I think what's happening here is that they are probably connected directly to the scrubbers network, which especially near the start of the round will be unreasonably hot due to thermomachines literally anywhere. Ghilker atmos working as intended as always.

![image](https://user-images.githubusercontent.com/14065903/140571432-1047384d-82a4-4ac4-a8c2-59574c3b6899.png)

**Comment by Paxilmaniac** [comment]
![image](https://user-images.githubusercontent.com/82386923/140571658-132d7332-8dd2-4631-9e01-11bd38aa066a.png)

It's hard to tell here, but yes the main atmos scrubbers line seems to (accidentally?) cross paths with the line from the small scrubbers outside.
