### ISSUE TITLE
Overflow bureacracy mistake on the shift report uses the code for the job instead of its name

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#62569]
## Testmerges:
The following pull requests are currently test merged:
#62558: 'Revert "Locker based combat, evolved. (#60000)"' by ArcaneMusic at commit 982e6abbeb

## Reproduction:
https://puu.sh/ImX9C/a62a3220e9.png
I hope you like /datum/job/cargo_technicians.

**Comment by JohnFulpWillard** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/63205 it appears
