### ISSUE TITLE
Spirits can drag crew, and they keep their usual VERY VERY fast speed. 

### ISSUE THREAD

**Issue by tobjv** [tgstation/tgstation#62573]
## Reproduction: grab crew as a spirit(shade) drag them around. no speed penalty.

If it matters, [https://github.com/Skyrat-SS13/Skyrat-tg/issues/9181](url)

**Comment by TheBonded** [comment]
I'm fairly certain this is intended, and not a bug, especially since shades have extremely low health and are only seen on cult rounds/wizard rounds/the occasional metastation round.

**Comment by SuperNovaa41** [comment]
This is intended

**Comment by tobjv** [comment]
thanks letting me know as it got reported as bug.
