### ISSUE TITLE
You can just stab the credit machine in the vault, destroying it forever

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#62577]
## Round ID: Manuel: R172463

I discovered that an angry cargo tech (or anyone else) can just kinda, stab the credit machine in the vault, destroying all trace of it forever, it has no circuit board, isn't a "real" computer, and can't be remantled in any way, this is unfair to antagonist roles, or anyone else who may need to interface with the machine. 

More of an oversight than a bug but somebody told me I might as well make an issue report.

**Comment by SuperNovaa41** [comment]
This isn't a bug. This computer is not required for any antagonist objective, thus it shouldn't have a snowflake protection. Breaking it fucks over cargo, so only antagonists should be breaking this anyways.

**Comment by NanoCats** [comment]
it doesn't even help cargo, antags might wanna rob the vault because y'know, they're the bad guys.
 it only HELPS cargo, as they can put money in through the dept budget card. It's pretty lame that it doesn't have a circuit board or anything and it's just _gone_ forever.

**Comment by EricZilla** [comment]
Its unmovable so you cant just take it to space and rob the station blind, I agree it should be invulnerable like the tram console just to keep things more interesting

**Comment by TheBonded** [comment]
or perhaps they could give it a GPS signal and require it to be on the same Z level as the departmental budget card, like how AI uploads work needing to be on the same Z level as the AI and also giving off a GPS signal.

**Comment by SuperNovaa41** [comment]
> it doesn't even help cargo, antags might wanna rob the vault because y'know, they're the bad guys. it only HELPS cargo, as they can put money in through the dept budget card. It's pretty lame that it doesn't have a circuit board or anything and it's just _gone_ forever.

> it doesn't help cargo

It keeps their budget. If its gone, so it cargos ability to order things

> antags might want to rob the vault

Good for them? Doesnt mean it gets special protection

**Comment by TheBonded** [comment]
> 
> 
> > it doesn't even help cargo, antags might wanna rob the vault because y'know, they're the bad guys. it only HELPS cargo, as they can put money in through the dept budget card. It's pretty lame that it doesn't have a circuit board or anything and it's just _gone_ forever.
> 
> > it doesn't help cargo
> 
> It keeps their budget. If its gone, so is cargos ability to order things

I am almost certain that they can still order things just fine without it

**Comment by SuperNovaa41** [comment]
> I am almost certain that they can still order things just fine without it

Are you sure? I swear it wrecks the budget

If thats true, that gives this machine even less incentive to get more protection lol

**Comment by TheBonded** [comment]
> 
> 
> > I am almost certain that they can still order things just fine without it
> 
> Are you sure? I swear it wrecks the budget
> 
> If thats true, that gives this machine even less incentive to get more protection lol

pretty sure, I can test in game for you if you need though

**Comment by NanoCats** [comment]
> > > I am almost certain that they can still order things just fine without it
> > 
> > 
> > Are you sure? I swear it wrecks the budget
> > If thats true, that gives this machine even less incentive to get more protection lol
> 
> pretty sure, I can test in game for you if you need though

Just tested, even Runtime station, which lacks a vault, still has it.

**Comment by timothymtorres** [comment]
So from my understanding the credit machine's only purpose is for antags to steal the budget? Honestly sounds like it needs to be made invulnerable like the station nuke terminal.

**Comment by SuperNovaa41** [comment]
> So from my understanding the credit machine's only purpose is for antags to steal the budget? Honestly sounds like it needs to be made invulnerable like the station nuke terminal.

This makes literally no sense. Things should only get snowflake protection if they are required for greentexts. Besides, its also for the QM and Captain to get credits

**Comment by timothymtorres** [comment]
> This makes literally no sense. Things should only get snowflake protection if they are required for greentexts. Besides, its also for the QM and Captain to get credits

The crew has a strong incentive to sabotage the credit machine to prevent antags accessing it.

**Comment by SuperNovaa41** [comment]
> > This makes literally no sense. Things should only get snowflake protection if they are required for greentexts. Besides, its also for the QM and Captain to get credits
> 
> The crew has a strong incentive to sabotage the credit machine to prevent antags accessing it.

They don't because you will get in trouble for doing that as a non antag
