### ISSUE TITLE
Kilos northern kitchen shutters are not working

### ISSUE THREAD

**Issue by Googles-Hands** [tgstation/tgstation#62570]
## Reproduction:
The shutters on Kilo Station on the north part of the kitchen are not connected to the button which is supposed to control them.
In addition the button is behind a random poster each round, which makes it's existence a easter egg and it's also labelled "door button".

![Kilo Shutters](https://user-images.githubusercontent.com/59937074/140332022-51e4f037-ab7d-486b-b1c0-66943a983a90.png)

**Comment by Timberpoes** [comment]
Fixed in https://github.com/tgstation/tgstation/pull/62848
