### ISSUE TITLE
Brain surgery doesn't tell when brain can be fixed more

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#62576]
Reporting client version: 514.1557

## Round ID:
[172494](https://scrubby.melonmesa.com/round/172494)

## Testmerges:
- [Revert "Locker based combat, evolved. (#60000)"](https://www.github.com/tgstation/tgstation/pull/62558)

## Reproduction:
get brain damaged person around 150 or so, do brain surgery, notice how it doesn't notify you when there's more to fix

**Comment by JohnFulpWillard** [comment]
![image](https://user-images.githubusercontent.com/53777086/146960062-2f606bcf-6e93-463f-a656-252dc16922de.png)
![image](https://user-images.githubusercontent.com/53777086/146960076-955e6683-151b-4e1a-a4df-badfb8118ebb.png)

Booted up Master, seems to work for me, odd.

It is part of 'Unsorted' chat tab though, so you might've had that turned off?
