### ISSUE TITLE
Catwalks don't work properly, again (they don't display their underneath)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#62582]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/140420176-504ce680-3922-432b-80a5-9906f73e4ce8.png)

- Build catwalk
- Put over pipe or cable
- No see pipe or cable

**Comment by OrionTheFox** [comment]
I believe #62331 caused this
The catwalk tiles USED to be fake-seethru, using `intact = false` to show whats below them. Issue is, `intact` as a variable was removed. And the catwalks never got `underfloor_accessibility` applied in its place

**Comment by OrionTheFox** [comment]
> I believe #62331 caused this The catwalk tiles USED to be fake-seethru, using `intact = false` to show whats below them. Issue is, `intact` as a variable was removed. And the catwalks never got `underfloor_accessibility` applied in its place

![image](https://user-images.githubusercontent.com/76465278/142758109-0f963ff8-50f2-40d5-8dad-68225db1d4be.png)
confirmed to be the issue
