### ISSUE TITLE
Adding a function

### ISSUE THREAD

**Issue by MrArvest** [tgstation/tgstation#62580]
Good afternoon
I recently started using the BYOND application and encountered a not very convenient access to the server. In order to log on to a specific server, you need to open the site in the browser every time, which is not particularly convenient. Based on this, I would like to suggest making a separate window with the server selection in the application itself, which will allow you to switch between servers without opening the browser every time.

**Comment by TheBonded** [comment]
Judging by the way you used the term "separate window *within the server selection in the application itself*" I assume you mean the BYOND launcher, and not the server. tgstation coders (or coders from any ss13 server for that matter) do not control BYOND and how they regulate their launcher, so we have no way of adding this feature.

**Comment by SuperNovaa41** [comment]
> you need to open the site in the browser every time

No you don't lmao
