### ISSUE TITLE
aggressively grabbing a body in space makes you move faster than passively grabbing them

### ISSUE THREAD

**Issue by Hates-The-Felinids** [tgstation/tgstation#62600]
Reproduction:
has to be next to walls
grab a body in space passively, you are moving slowly as intended, grab a body in space aggressively, you will now move faster.

**Comment by timothymtorres** [comment]
This looks related to #62600

**Comment by SuperNovaa41** [comment]
> This looks related to #62600

I would certainly hope so.

**Comment by timothymtorres** [comment]
I dun goofed.  I meant it's related to #21406

**Comment by JohnFulpWillard** [comment]
> I dun goofed. I meant it's related to #21406

That one is pushing off of people to propel yourself (which I think is fixed now?), this one is aggro grabbing someone in space to negate the slowdown you get from grabbing someone

**Comment by LemonInTheDark** [comment]
aggressive dragging not slowing you down in space is intentional 
![image](https://user-images.githubusercontent.com/58055496/166203011-c89caa09-7c59-4564-a072-1d8aa358e5da.png)
The issue here is bulky dragging and aggressive dragging being inconsistent with each other
