### ISSUE TITLE
Going to the lavaland base during AI's delta counts as escaped

### ISSUE THREAD

**Issue by Googles-Hands** [tgstation/tgstation#62606]
## Reproduction:
During the round there was a malf AI that went delta, the traitor "Garrett Kelley" was on the public mining shuttle on it's way to the lavaland base, which I think arrived BEFORE the round ended, his "escape on the shuttle or an escape pod alive" objective was counted as completed.
This seems to be a bug because last I checked the only way to count as escaped during a delta alert is if you go to lavaland via an escape pod and stay in it until the round ends.

**Comment by TheBonded** [comment]
as far as I know, being on lavaland at all after a delta alert ends the round counts as escaped

**Comment by timothymtorres** [comment]
> as far as I know, being on lavaland at all after a delta alert ends the round counts as escaped

I do believe this is intended as well.  Now if this was happening if there wasn't a delta alert, it'd be a legit bug.

**Comment by SuperNovaa41** [comment]
Yeah, the message you get is: You escaped, but are marooned on lavaland...
Or something to that effect

**Comment by TheBonded** [comment]
> 
> 
> Yeah, the message you get is: You escaped, but are marooned on lavaland... Or something to that effect

pretty sure that only happens when the shuttle leaves, and it just says "you survived, but were marooned on [station name]". when a delta alert happens, if you are alive on lavaland when it goes off (and ends the round), you get the normal green escaped message. this is so delta alerts don't mess up escape alive objectives for antags during dynamic rounds.

**Comment by SuperNovaa41** [comment]
> > Yeah, the message you get is: You escaped, but are marooned on lavaland... Or something to that effect
> 
> pretty sure that only happens when the shuttle leaves, and it just says "you survived, but were marooned on [station name]". when a delta alert happens, if you are alive on lavaland when it goes off (and ends the round), you get the normal green escaped message. this is so delta alerts don't mess up escape alive objectives for antags during dynamic rounds.

Oh right, my bad

**Comment by Googles-Hands** [comment]
Right, well I assumed that it was a bug due to reading this on the wiki page (https://tgstation13.org/wiki/Traitor#Escape_alive_and_without_being_in_custody): "Sending your escape pod to Lavaland will count as you escaping alive without being in custody only IF the station does end up exploding from the Delta crisis, AND you stay in the pod until the round ends."

**Comment by timothymtorres** [comment]
It was probably changed at some point and the wiki was never updated accordingly.
