### ISSUE TITLE
Permanent Berserker Mode

### ISSUE THREAD

**Issue by Mey-Ha-Zah** [tgstation/tgstation#62607]

**Comment by TheBonded** [comment]
Are you able to give more details on what you were doing directly before and just as you activated it? where you were, what was happening, etc. That way it's slightly easier to troubleshoot what caused this

**Comment by Mey-Ha-Zah** [comment]
Just activated it after charging it Did a follow up in thunderdome.

**Comment by Mey-Ha-Zah** [comment]
Bugged even in thunderdome.
