### ISSUE TITLE
You can draw out reagents from medipens

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#62619]
## Round ID:
[172587](https://scrubby.melonmesa.com/round/172587)

## Testmerges:
#60000 
#62558 

## Reproduction:
get a medipen and a syringe, right click medipen with syringe, draw reagents out of the medipen.
i see this as a oversight but it can be abused due to miners getting powerful medipens (you can bypass the interact timer with just a syringe)

**Comment by SuperNovaa41** [comment]
The interact timer on a syringe is the same for miner pens, unless you're on the station

**Comment by FlamingCheese** [comment]
> The interact timer on a syringe is the same for miner pens, unless you're on the station

Using a syringe on yourself is instant while miner medipens have a long interact timer if used in full pressure areas

**Comment by InsaneRed** [comment]
i feel like while that miner pen part is obviously a bit overpowered, being able to draw directly out of medipens seems like a fun feature

**Comment by SuperNovaa41** [comment]
I think this is intended? This seems more like a balance issue than anything

**Comment by necromanceranne** [comment]
This is intended
https://github.com/tgstation/tgstation/blob/f7545e0026b49131e518c7427f7046807b311209/code/modules/reagents/reagent_containers/hypospray.dm#L114
