### ISSUE TITLE
ship navigation computer doesn't show ship outline

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#62635]
Reporting client version: 514.1557

## Round ID:
[172626](https://scrubby.melonmesa.com/round/172626)

## Testmerges:
- [Revert "Locker based combat, evolved. (#60000)"](https://www.github.com/tgstation/tgstation/pull/62558)

## Reproduction:
get the pirate ship from trade route, go to navigation computer, use it and observe how you can't see the outline of where the ship is going to land

**Comment by Addust** [comment]
This happens to all other shuttles too, not just the pirate cutter

**Comment by Googles-Hands** [comment]
This really needs a fix, it makes pirates/nukies way less effective

**Comment by SuperNovaa41** [comment]
Duplicate of #https://github.com/tgstation/tgstation/issues/62635
