### ISSUE TITLE
Quantum Pads broken

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#62634]
Reporting client version: 514.1557

## Round ID:
[172620](https://scrubby.melonmesa.com/round/172620)

## Testmerges:
- [Revert "Locker based combat, evolved. (#60000)"](https://www.github.com/tgstation/tgstation/pull/62558)

## Reproduction:
make a quantum pad on station, make one in space on another z level, link them both and try to use them, you won't go anywhere. it lets you go between them as a ghost, but won't actually teleport people for some reason

**Comment by timothymtorres** [comment]
https://github.com/tgstation/tgstation/blob/a28030ee3a2f1ef4b81e31c0f66cd26ebef42d1f/code/game/machinery/quantum_pad.dm#L171-L187

It seems there was an intended restriction on teleporting ghosts for some reason? I didn't see any restriction on z-level teleporting for the code so this seems like a bug.  Just to double check, are  you sure both quantum pads were fully setup?  Maybe the area was unpowered?

**Comment by Rustybuckets6601** [comment]
> https://github.com/tgstation/tgstation/blob/a28030ee3a2f1ef4b81e31c0f66cd26ebef42d1f/code/game/machinery/quantum_pad.dm#L171-L187
> 
> It seems there was an intended restriction on teleporting ghosts for some reason? I didn't see any restriction on z-level teleporting for the code so this seems like a bug. Just to double check, are you sure both quantum pads were fully setup? Maybe the area was unpowered?

Both were definitely powered, they even did the little spark effect when activated.

**Comment by ATH1909** [comment]
it looks like the check to make sure that ghosts aren't teleported is actually ensuring that ONLY ghosts and living creatures can be teleported (and not unattended items).
