### ISSUE TITLE
augmented humans scream in pain during surgery

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#62637]
Reporting client version: 514.1557

## Round ID:
[172626](https://scrubby.melonmesa.com/round/172626)

## Testmerges:
- [Revert "Locker based combat, evolved. (#60000)"](https://www.github.com/tgstation/tgstation/pull/62558)

## Reproduction:
give yourself cyborg torso, do self surgery, notice the flavortext that mentions you go numb in that area, remove or add an organ and notice how you scream in pain anyways

**Comment by timothymtorres** [comment]
The flavortext isn't always accurate and it doesn't make any sense that you wouldn't feel ANY pain whatsoever especially when you are ripping out your own organs without anesthesia.

**Comment by Rustybuckets6601** [comment]
> The flavortext isn't always accurate and it doesn't make any sense that you wouldn't feel ANY pain whatsoever especially when you are ripping out your own organs without anesthesia.

I'd assume there's no pain due to self surgery being possible, but you're the boss
