### ISSUE TITLE
AI can't change holodeck safeties

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#62641]
Reporting client version: 514.1561

## Round ID:
[172637](https://scrubby.melonmesa.com/round/172637)

## Testmerges:
- [Revert "Locker based combat, evolved. (#60000)"](https://www.github.com/tgstation/tgstation/pull/62558)
- [Fixes Massive Radio Overtime, Implements a Spatial Grid System for Faster Searching Over Areas](https://www.github.com/tgstation/tgstation/pull/61422)

## Reproduction:
1. Be the station's AI.
2. Move your camera to the holodeck.
3. Try to turn off the safeties on the holodeck console. You cannot.
4. (optional) attempt to change the holodeck sim to any of the normally available ones. You can!

**Comment by zkxs** [comment]
I'm also able to reproduce this.

Round ID: 173049

Test merges:
#62727: 'Departmental Security Rework Option 1: Department First, Security Second' by Iamgoofball at commit 029f550f7e
#62711: 'Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins' by Watermelon914 at commit 5dcc0b783d

Also, I ahelped about it and Timberpoes acknowledges that it's a bug.

**Comment by Redrover1760** [comment]
I have encountered the same bug playing ai, as well. Does this still need reproducing?

**Comment by carshalash** [comment]
Cn confirm, can't touch the holodeck safeties at all.

**Comment by msgerbs** [comment]
It's probably related to this PR, nothing else seems to have touched holodeck safeties: #62563

Does anyone know if the AI is considered silicon?
