### ISSUE TITLE
Abandoned satellite windows can be glitched through

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#62647]
Reporting client version: 514.1561

## Round ID:
[172647](https://scrubby.melonmesa.com/round/172647)

## Testmerges:
- [Move refactor](https://www.github.com/tgstation/tgstation/pull/62605)
This one is applicable
## Reproduction:

Head into the abandoned satellite expecting to get syndicate tools
Walk into the window while moving down
Be trapped in a tiny box until adminbus arrives to get you out or you shoot out a window

## Picture:
![image](https://user-images.githubusercontent.com/80979251/140641368-a8613e01-2ffc-49d3-8da3-08f0a6f9b9e3.png)

**Comment by SuperNovaa41** [comment]
Directional windows need to be removed

**Comment by timothymtorres** [comment]
Pretty sure this is related to the test merge for #62605.  There is a similar movement/window issue for #62658.

**Comment by BraveMole** [comment]
fixed

**Comment by timothymtorres** [comment]
Fixed with https://github.com/tgstation/tgstation/pull/62605/commits/7a9914f4fb4603350395617490127fca2ef0bd23
