### ISSUE TITLE
Exporting Machines give 0 profit to Cargo.

### ISSUE THREAD

**Issue by Feasel** [tgstation/tgstation#62644]
## Reproduction:

1. Create machine. 
2. Put machine on cargo shuttle.
3. Scan machine for value (Emitters - 540)
4. Send machine off.
5. Recieve no money.

![dreamseeker_TQZTu5YYt1](https://user-images.githubusercontent.com/47361856/140638202-1558f25c-9987-4c05-802b-9a969eae5838.png)
![qFMKpIOTw0](https://user-images.githubusercontent.com/47361856/140638205-d691cee6-6dc7-4085-a40c-773a174a0682.png)

In the picture is after calling shuttle back and the cargo screen showing that it was not counted.

**Comment by SuperNovaa41** [comment]
Did it send fully made emitters back as half made machine frames?
