### ISSUE TITLE
Mime can use Cultist commune silently, alongside runes, due to vow of silence.

### ISSUE THREAD

**Issue by daplanman12** [tgstation/tgstation#62646]
Reporting client version: 514.1568

## Round ID:
[172645](https://scrubby.melonmesa.com/round/172645)

## Testmerges:
- [Revert "Locker based combat, evolved. (#60000)"](https://www.github.com/tgstation/tgstation/pull/62558)

## Reproduction:

Mime under vow of silence will not talk when he uses commune or runes, but will still activate them, leading to mime being able to use cult chat silently without any obvious signs such as cult gibbering.

**Comment by Time-Green** [comment]
Mimes can always invoke whisper spells, including cult ones. Someone else can correct me, but this has been a feature for about 10 years

**Comment by daplanman12** [comment]
Yes, but there's literally no sound, which seems like it's unintended that Mime can literally use cult stuff without any drawbacks, especially when accompanied by multiple "your vow of silence prevents speech" notices.

**Comment by necromanceranne** [comment]
> Yes, but there's literally no sound, which seems like it's unintended that Mime can literally use cult stuff without any drawbacks, especially when accompanied by multiple "your vow of silence prevents speech" notices.

Still, not a bug, and not an oversight, so I think this isn't worth keeping open. If for some reason you believe mime cultists shouldn't be able to use cult runes and spells, make a PR for it with good justifications.
