### ISSUE TITLE
Whitespaces at the start and the end of a message are filtered by the word filter

### ISSUE THREAD

**Issue by GoldenAlpharex** [tgstation/tgstation#62655]
## Reproduction:
1. Press your OOC keybind / type OOC " in the chatbar.
2. Try to enter an empty message
3. ![image](https://user-images.githubusercontent.com/58045821/140659678-93bd3ed4-5684-45de-8eb8-c58da25b0f27.png)
4. Try to enter just a space.
5. ![image](https://user-images.githubusercontent.com/58045821/140659692-32d803a5-8428-4d31-a975-85babd0e7f29.png)
6. Try to start a message with a space (i.e.: ` Ah.`)
7. ![image](https://user-images.githubusercontent.com/58045821/140659702-380774a1-c56b-47d5-a845-44ca34af292c.png)
8. Try to end a message with a space (i.e.: `Ah. `)
9. ![image](https://user-images.githubusercontent.com/58045821/140659712-9f24ee2d-bc3b-4845-b206-bdea9e6195ce.png)

You can do the same thing in Say, as the messages are not sanitized before being inputed in the regex (I tested it, the issue seems to be fixed when the filtering is done after the sanitizing and early return in `living_say.dm`, line `95`, within the `say()` proc.) The result should be similar to this, based on the config:  
![image](https://user-images.githubusercontent.com/58045821/140659868-9a24d299-d103-4736-9ab6-54db3675b2bc.png)

However, it is to note that it's not an issue with PDAs, which seem to sanitize the input before letting in through the filter.

Filled at Mothblocks' request, I would've tried to fix it, but I'm not confident enough with RegEx yet to say that I won't fuck shit up by accident.

**Comment by Mothblocks** [comment]
Can't reproduce on prod

![image](https://user-images.githubusercontent.com/35135081/140814459-81774e33-b74a-44ba-b4db-f07057df2efb.png)

**Comment by Tastyfish** [comment]
This happens on a clean, unconfigured copy of the codebase.

**Comment by Mothblocks** [comment]
Bug identified: it happens when you have no non-alphanumerics.

`((?:(?:^|\s+)()(?:$|\s+))|(\b(cargonia|pogchamp|lol|omg|wtf)\b))` was generated from the words only seen on the right.
