### ISSUE TITLE
Away mission can still be accessed when ended

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#62651]
Reporting client version: 514.1561

## Round ID:
[172663](https://scrubby.melonmesa.com/round/172663)

## Testmerges:
Not applicable

## Reproduction:

Go to gateway after away mission ends
Reactivate portal
Step through
(Step 2 tiles north of where you entered the mission and you should return)

**Comment by timothymtorres** [comment]
Is this normal behavior for the gateway?  I never knew away missions were supposed to end or have a finish line.

**Comment by Serxule** [comment]
gateway missions don't have an end, they're just loot ruins (but the teleporting back after going through is a bug)

**Comment by SuperNovaa41** [comment]
> (Step 2 tiles north of where you entered the mission and you should return)

Return to the away mission?
They don't end.
