### ISSUE TITLE
You can walk thru directional windows + objects push

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#62658]
## Reproduction:

See horisontal window - go thru (working only from one side)
Also lockers/crates wierdly moving if walking nearby.
https://youtu.be/9LpGs4XrNAw

**Comment by Googles-Hands** [comment]
saw this also happen multiple times with slimes and monkeys in xenobiology on maps where the cages are only split via directional windows

**Comment by Pickle-Coding** [comment]
Got spaced out of the shuttle like 2 Terry rounds ago because of it. Also works on directional windoors. Happens when moving diagonally towards something, and continue moving until you phase through the directional shit.

**Comment by timothymtorres** [comment]
Pretty sure this is related to the test merge for #62605.  There is a similar movement/window issue for #62647.

**Comment by Sealed101** [comment]
the weird locker movement is somewhat consistent, it's just you pushing the locker diagonally as you move near it

**Comment by BraveMole** [comment]
both fixed

**Comment by timothymtorres** [comment]
Fixed with https://github.com/tgstation/tgstation/pull/62605/commits/7a9914f4fb4603350395617490127fca2ef0bd23
