### ISSUE TITLE
"Spicy Air" issue afflicts public Deltastation scrubbers

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#62660]
![image](https://user-images.githubusercontent.com/14065903/140667184-0dca170e-c475-49a3-9d11-3102cc092ed1.png)

Very similar issue to one I reported not long ago, plugging scrubbers in causes them to sizzle and be destroyed something something thermomachines, probably.

**Comment by timothymtorres** [comment]
Related to #62566

**Comment by NanoCats** [comment]
> Related to #62566

you know I should probably just check every map at this point

**Comment by Likteer** [comment]
I do wonder what are the conditions for their destruction that aren't blunt force.

**Comment by NanoCats** [comment]
> I do wonder what are the conditions for their destruction that aren't blunt force.

I'm not Jimmy Neutron here but I assume it's just "gas above a particular temperature" (When I connect it to the port, it gets some gas inside it and sizzles before vanishing)



I'm confounded by the fact that it goes _into_ the scrubber though, like, scrubbers connected to ports should be output-only, right?

**Comment by Paxilmaniac** [comment]
its because gas ports just share the gas between the line and the connected thing by default, meaning whatever is in distro goes into the scrubber, which can be remedied with a single gas pump i'm sure, ill take a look
