### ISSUE TITLE
Radio emotes break on binary

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#62666]
Reporting client version: 514.1568

## Round ID:
Reproduced on local

## Reproduction:
Try to use radio emotes on binary, but without any text (i.e. .b coughs!*) 
Your message is replaced with 
![image](https://user-images.githubusercontent.com/66640614/140688666-7c0ef50e-bb18-4c0b-9b5b-fcc640717435.png)

**Comment by SuperNovaa41** [comment]
Robots can't cough

**Comment by dragomagol** [comment]
Anything can happen in space

**Comment by etherware-novice** [comment]
will work on

**Comment by etherware-novice** [comment]
i hate code now

**Comment by Mooshimi** [comment]
https://github.com/tgstation/tgstation/blob/ccef887efec2cb3025228210bcb134700aac5175/code/modules/mob/mob_say.dm#L160-L171

https://github.com/tgstation/tgstation/blob/ccef887efec2cb3025228210bcb134700aac5175/code/game/objects/items/devices/radio/radio.dm#L349-L366
