### ISSUE TITLE
Petting a Monkey will cause it to get Triggered, writing a lengthy Twitter Post about you while beating you to shit and then Disposaling You

### ISSUE THREAD

**Issue by Zytolg** [tgstation/tgstation#62669]
## Reproduction:

Either Pun-Pun and his kind hate being pet, or Monkies have always bitten the arms off their handlers, and I'm not too sure the later was a case earlier this year. 

Pet a monkey and find out. 

Got FlamingCheese to replicate it on #172719
Hulk Hogan would be proud (of the monkey).

**Comment by timothymtorres** [comment]
Has this happened in multiple rounds?

**Comment by Zytolg** [comment]
> Has this happened in multiple rounds?

I've heard about it happening to others. This behavior can also occur in monkified humans for some reason. In a previous shift, a ling had been stinging and transforming monkies, and 1 hug was all it took for a monkey lizard to murder a crew member.

**Comment by newfren** [comment]
I can confirm that monkeys get fucking pissed whenever you hug them
