### ISSUE TITLE
Eigenstasium overdose removes implants

### ISSUE THREAD

**Issue by antropod** [tgstation/tgstation#62661]
## Reproduction:
Implant yourself with any implant.
Overdose yourself on eigenstasium, wait for it to start teleporting your items (around 10 minutes, or cycle 50 of eigenstasium status effect (it starts at -250)), lose all your implants when your items teleport away.

I think bug is in the code for picking items to teleport away from you:
https://github.com/tgstation/tgstation/blob/6fe8e8d76c7143a4cbfb57e2e19dc74994b1b09f/code/datums/status_effects/neutral.dm#L351

**Comment by timothymtorres** [comment]
https://github.com/tgstation/tgstation/blob/6fe8e8d76c7143a4cbfb57e2e19dc74994b1b09f/code/datums/status_effects/neutral.dm#L421-L450

It appears this is intended.  See the PR that created Eigenstasium at #56918.  The final phase spawns a new randomized mob so you lose your implants since the old body is deleted.

**Comment by antropod** [comment]
Okay I'm using this next time to delete implants from abductors

**Comment by antropod** [comment]
Can you point at line of code where old mob is deleted? All I see is quirks reroll and appearance update, old mob is not deleted

**Comment by antropod** [comment]
@Thalpy is this intended?

**Comment by timothymtorres** [comment]
After a 2nd lookthrough it seems

>Stage 4 - replaces your character with an alternative reality version of yourself.

Doesn't mean the original mob actually got deleted.  Just the appearance, mood, and quirks were randomized.  None of these should have affected implants from the original mob, at least not from what I can tell.

**Comment by antropod** [comment]
Mob cloning is not affecting implants, stage 2 of addiction is what affecting them. When it picks random item to teleport away, it looks into mob .contents and picks random item. Implants are stored in mob .contents as well, so it has chance to teleport implant away. This also reproduces with items like armblades on nightmares, or other items that can't be dropped normally.

**Comment by tralezab** [comment]
eigenstasium needs to remove items that it should not teleport
