### ISSUE TITLE
Plasma-injected cells auto-explode in APCs despite no power

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#62679]
## Reproduction:
(I would like someone else to test this, since I'm still not 100% sure, might have been lag or something)
1. Decide to play a funny prank on a botanist for being a prick
2. ~~Severely underestimate explosion power~~
3. Inject a cell with plasma, unlock the panel, disengage the cover lock and turn off main power
4. Do a switcharoo of the ce-
![obraz](https://user-images.githubusercontent.com/68878861/140790684-c6e809a6-fa1b-4d87-9ba2-01e79fbc634c.png)

**Comment by timothymtorres** [comment]
https://github.com/tgstation/tgstation/blob/5c3330f8c64edb19bd24961cf1fcf053125c5bb5/code/modules/power/apc.dm#L604-L618

I don't see anything indicating that the main power should be reset when a new cell is inserted.  Are you sure it was turned off before you inserted the cell?

**Comment by Likteer** [comment]
@timothymtorres Not sure, I want others to reproduce it. It may be that the cell doesn't check for power flow anymore and that's why it insta-explodes. Or maybe tis' I a dofus?

**Comment by SuperNovaa41** [comment]
Did you have any cables cut? That can flip the power

**Comment by oklews** [comment]
I know exactly why it exploded here, it explodes the moment it tries to change the power, you forgot to turn off the charging (default it’s set to auto, you can set it to off). When it tried to charge, it exploded.

**Comment by timothymtorres** [comment]
> I know exactly why it exploded here, it explodes the moment it tries to change the power, you forgot to turn off the charging (default it’s set to auto, you can set it to off). When it tried to charge, it exploded.

I suspected as much.

**Comment by Likteer** [comment]
@oklews A bit late "thank you"!
