### ISSUE TITLE
AI Monkeys/Humans Can Hyjack Cyborg Movement

### ISSUE THREAD

**Issue by IndieanaJones** [tgstation/tgstation#62673]
Currently, there is a bug in the game that if you have an AI monkey strapped to a cyborg, the monkey will force the cyborg to move unwillingly in the direction the monkey wants to move.  Likely an extension of the issue seen present in #56586.

## Reproduction:

1. Grab an AI monkey
2. Mount the monkey onto a cyborg
3. Punch the monkey
4. Watch as the monkey forces the cyborg to do its bidding

**Comment by NanoCats** [comment]
Feature

**Comment by SuperNovaa41** [comment]
Forcemove moment

**Comment by Vexylius** [comment]
Also applies if someone fireman carries said monkey.

**Comment by ArcaneMusic** [comment]
Verified by @dragomagol that this is no longer an issue on local master.
