### ISSUE TITLE
Reject button on cross sector messages not working

### ISSUE THREAD

**Issue by Burgermancoding** [tgstation/tgstation#62674]
## Round ID:

Round ID: [172712](https://scrubby.melonmesa.com/round/172712) , Terry

## Reproduction:
I pressed the button to reject two cross server messages from being sent and they both sent anyway
![image](https://user-images.githubusercontent.com/79515258/140764156-9a28c137-f7a3-419d-8900-4f86cf9fb8e7.png)

**Comment by Mothblocks** [comment]
There's a few reject buttons here, this is for sending right? Not receiving?

**Comment by Mothblocks** [comment]
Have been able to reproduce rejecting the send one not working, though it works on local. Yipes!
