### ISSUE TITLE
There are 3 fire alarms in the middle level of icebox mining that have no firelocks or breaks between them.

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#62698]
![fire alarms](https://user-images.githubusercontent.com/12635164/140892212-c2d21fd2-11c8-4e25-8ae5-1a54f109cffe.png)

these all trigger in the same not very big room and as soon as it's breached basically all of them will go off at once due to how speedy atmos is

it's really annoying if you want to disable the fire alarms in this area cause you need to get all three of these (and one downstairs but it is actually seperated by firelocks so it's fine)

**Comment by Zytolg** [comment]
Intentional. 
The main reason for the placement of these alarms is to allow players to temporarily lift the firelocks without needing a crowbar. Proximity to rooms actually allows players to make it through before the firelocks slam shut again.

**Comment by newfren** [comment]
That makes sense I guess.
