### ISSUE TITLE
Prides Mirror and Subsequently Gluttonys Ruin

### ISSUE THREAD

**Issue by mixzombie** [tgstation/tgstation#62691]
Server: Bagil

Revision: 56Bf775

Problem Description: Break down of Lavaland Structures, Prides Mirror No longer works, Doesn't race change, Doesn't shunt user to space. Gluttonies Ruin also Is effectively Ruined by new radiation, Basically cannot enter without having an item to teleport back to station for immediate medical treatment. Which anyone who has been their and used it, Knows you need Alot of time to get fat enough to use it.

What did you expect to happen: As far as Prides mirror goes, Honestly no clue. Gluttonies Ruin though its pretty obvious that its the new Radiation.

What happened instead: Prides Mirror Nothing happens. Gluttonies Ruin you die of mutations or toxin damage.

Why is this bad/What are the consequences: Miners have been losing alot lately, After defeating hierophant using Prides Mirror to change to shadowling is the Only way outside of xenbio to gain passive healing. Still Very sad a Certain Someone took out Nanites.

Steps to reproduce the problem: Try to use Prides Mirror and it wont work. Traditionally you have to make your way back to the station before you use Gluttonies Syringe and without a way to teleport you basically cannot make it.

**Comment by ATH1909** [comment]
what does gluttony's ruin have to do with radiation??

**Comment by mixzombie** [comment]
The Green walls man the green walls,  Fairly certain they are Uranium walls and every Item on the floor Glows green. If you dont believe me jump on Bagil and ghost over.

**Comment by ATH1909** [comment]
```
"R" = (
/turf/closed/indestructible/riveted/uranium,
/area/ruin/powered/gluttony)
"S" = (
/obj/machinery/door/airlock/uranium,
/obj/structure/fans/tiny/invisible,
/turf/open/floor/iron/freezer,
/area/ruin/powered/gluttony)
```
huh, you're right

**Comment by Mothblocks** [comment]
they should just not be uranium

**Comment by ATH1909** [comment]
> The Green walls man the green walls, Fairly certain they are Uranium walls and every Item on the floor Glows green. If you dont believe me jump on Bagil and ghost over.

have you tried actually doing the ruin, or have you just observed it as a ghost? the number of irradiated items inside shouldn't make it more deadly, IIRC, just the things that are actually made of uranium.

**Comment by Mothblocks** [comment]
irradiated items do not do anything, they just signify radiation is near, but you can definitely be irradiated inside

**Comment by ATH1909** [comment]
wait, the indestructible uranium walls shouldn't even be radioactive

```
/turf/closed/indestructible/riveted/uranium
	icon = 'icons/turf/walls/uranium_wall.dmi'
	icon_state = "uranium_wall-0"
	base_icon_state = "uranium_wall"
	smoothing_flags = SMOOTH_BITMASK
```

I think it's JUST the uranium doors that are to blame here

**Comment by ATH1909** [comment]
and re: pride's mirror: did you try canceling the normal mirror menu without walking away from it? for some reason, pride's mirror brings up the normal mirror menu first and you have to dismiss it to actually get to the good stuff.

**Comment by TheBonded** [comment]
are you sure it was the real pride's mirror? afaik, there's a broken one that sometimes spawn

**Comment by ATH1909** [comment]
https://github.com/tgstation/tgstation/pull/62692

**Comment by ATH1909** [comment]
> are you sure it was the real pride's mirror? afaik, there's a broken one that sometimes spawn

that... seems to be a lie. only the primary mirror is magical, though- the other ones in the ruin are normal.

**Comment by TheBonded** [comment]
> 
> 
> > are you sure it was the real pride's mirror? afaik, there's a broken one that sometimes spawn
> 
> that... seems to be a lie. only the primary mirror is magical, though- the other ones in the ruin are normal.

I swear I've seen two versions of it, one of them is darker and the mirror at the end is shattered. Then again, I don't do enough mining or exploring lavaland to know if that's not just a different variant of the pride's mirror

**Comment by Serxule** [comment]
> I swear I've seen two versions of it, one of them is darker and the mirror at the end is shattered. Then again, I don't do enough mining or exploring lavaland to know if that's not just a different variant of the pride's mirror

thats envy's ruin with the shattered mirror, gives a blade that attacking people with turns you into them

**Comment by Iplayforss13** [comment]
I've noticed that race changing wont work, but changing facial features and stuff works and shunts you into space

**Comment by TheBonded** [comment]
> 
> 
> > I swear I've seen two versions of it, one of them is darker and the mirror at the end is shattered. Then again, I don't do enough mining or exploring lavaland to know if that's not just a different variant of the pride's mirror
> 
> thats envy's ruin with the shattered mirror, gives a blade that attacking people with turns you into them

oh, that makes sense. sorry for the confusion, I really should play miner more

**Comment by mixzombie** [comment]
I never use it to change facial features or hair, Just for the race change. And ive tried over several shifts with no effect.  Im fairly sure I dont look away from mirror while im using the menu. But i cant say with that 100% certainty,

**Comment by mixzombie** [comment]
Cool, Thanks guys. I appreciate the hard work to resolve my little lavaland issues.
