### ISSUE TITLE
party pods drop all components when exited and let you hear things you should be unable to

### ISSUE THREAD

**Issue by nogoodidea** [tgstation/tgstation#62693]
Round ID: [172738](https://scrubby.melonmesa.com/round/172738)
Testmerges: #62558 
Reproduction:
1. enter party pod
2. inject regents
3. exit party pod

party pods drop all of there components when exited by a player and after exiting the party pod i found that i was able to hear intermittent attacks,emotes and comms messages that where not happing around my charictor location, ei hearing combat when your space exploreing.
the party pods where var edited if that helps.

**Comment by nianjiilical** [comment]
to add to this, i varedited the party pod's name, description, chemicals and chem_buttons

**Comment by timothymtorres** [comment]
So this is a dupe of #60719 and #62636.  It was fixed with PR #62632 and was merged 3 hours ago.  So when you reported the issue the fix hadn't been applied yet.  Can you retest this and report back?

**Comment by nogoodidea** [comment]
unable to reproduce on the latest git build. closeing issue

**Comment by timothymtorres** [comment]
Thanks for retesting this!
