### ISSUE TITLE
Hatched Xenomorph eggs display the "grown egg" sprite

### ISSUE THREAD

**Issue by Googles-Hands** [tgstation/tgstation#62708]
## Reproduction:
When an alien egg grows and get's opened it plays the hatching animation but instead of remaining open, at the end of the animation they revert to the "grown egg" sprite and look closed which results in the facehuggers to be either mostly hidden behind the egg or just infront of it.
![Xeno bug](https://user-images.githubusercontent.com/59937074/140992160-0ff0cbe0-76dd-4cad-b163-95ef8ef32afe.png)
![Xeno bug 2](https://user-images.githubusercontent.com/59937074/140992279-961bdf14-14a1-4511-9363-3e823ba50b59.png)

You can still clear the egg like you would a normal hatched one.

**Comment by TheBonded** [comment]
possibly caused by https://github.com/tgstation/tgstation/pull/62597
