### ISSUE TITLE
Uplinks don't check to see if the user's job matches up to the job required to buy a specific item.

### ISSUE THREAD

**Issue by CocaColaTastesGood** [tgstation/tgstation#62713]
## Reproduction:
User with any job, for example assistant, tries to purchase an uplink item that should be job-locked(Clown car, pie cannon, etc), it works.

**Comment by newfren** [comment]
The items don't show up unless you're the job required to purchase them though?

**Comment by CocaColaTastesGood** [comment]
> The items don't show up unless you're the job required to purchase them though?

Yes. Users can send any action regardless of if they show or not, however.
