### ISSUE TITLE
Players can buy a crate of syndi-gear from the cargo console

### ISSUE THREAD

**Issue by CocaColaTastesGood** [tgstation/tgstation#62719]
## Round ID:
[0](https://scrubby.melonmesa.com/round/0)

## Reproduction:
Title might be slightly misleading. When you buy things from cargo, it doesn't seem to properly check to see if the a supply pack is special before buying it, so a player can purchase the path "/datum/supply_pack/misc/syndicate" (Random event crate) and get one crate of traitor items. Weirdly, it seems like it only works once before the bought crate spawns empty, even when spawning it from the admin panel. I plan to fix both issues I've posted.

**Comment by ATH1909** [comment]
do you have a round ID or reproduction steps?

**Comment by CocaColaTastesGood** [comment]
> do you have a round ID or reproduction steps?
Not related to a specific round. And the information I provided is enough to reproduce it.
