### ISSUE TITLE
Yellow Swarmers Target Bar Robots 

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#62737]
## Reproduction: 

Yellow swarmers will attack bar robots which are unteleportable and unkillable by swarmers effectible locking them such a waste of 180 materials
![image](https://user-images.githubusercontent.com/84478872/141215307-271eb48b-36e3-4e0d-9a98-e7526a6b6027.png)

**Comment by SuperNovaa41** [comment]
At least it didn't crush them into dust

**Comment by DeveloperLoser** [comment]
They target all things such as mice and MULE's to

**Comment by itseasytosee** [comment]
SWARMERS ARE DEAD LONG LIVE SWARMERS
