### ISSUE TITLE
Icebox Lower Service Floor Door to the Outside does not follow proper convention for going outside, and does not signpost that it goes outside at all

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#62756]
![Discord_jvYhdPVdV9](https://user-images.githubusercontent.com/4081722/141341073-45f3513d-ca07-4249-b157-e7370f6ff3eb.png)
People die all the time because they go through this thinking it's a normal internal airlock and then accidentally let 15 wolves and other assorted megafauna into the hallway.

**Comment by timothymtorres** [comment]
It's just a prank bro

**Comment by san7890** [comment]
![image](https://user-images.githubusercontent.com/34697715/149613557-4229423a-c0bf-4aef-99ff-b8f3afd04473.png)

I'm not exactly sure when, but this issue seems to have been resolved.

**Comment by Iamgoofball** [comment]
Those still aren't exterior access airlocks
