### ISSUE TITLE
Air alarms are offset improperly

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#62752]
Reporting client version: 514.1569

## Round ID:
[172873](https://scrubby.melonmesa.com/round/172873)

## Testmerges:
N/A

## Reproduction:

Reproduces itself as it is related to the offset of air alarms.

![image](https://user-images.githubusercontent.com/80979251/141329527-32a77168-cc4a-4636-abd5-b5ef7d88500c.png)

**Comment by timothymtorres** [comment]
What station was this?

**Comment by Addust** [comment]
The wall of text should have made that clear, but it was on charlie station
