### ISSUE TITLE
Revs unable to see fellow rev antag huds

### ISSUE THREAD

**Issue by Ryll-Ryll** [tgstation/tgstation#62770]
Reporting client version: 514.1557

## Round ID:
[172905](https://scrubby.melonmesa.com/round/172905)

## Testmerges:
- [Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins](https://www.github.com/tgstation/tgstation/pull/62711)
- [Departmental Security Rework Option #1: Department First, Security Second](https://www.github.com/tgstation/tgstation/pull/62727)
- [Fixes Massive Radio Overtime, Implements a Spatial Grid System for Faster Searching Over Areas](https://www.github.com/tgstation/tgstation/pull/61422)
- [Antag HUDs will now animate if you have multiple antagonists, and will no longer clear on deconversion](https://www.github.com/tgstation/tgstation/pull/62718)

## Reproduction:
No hard, fast information about this one. Had a player who was converted to the revolution who was able to see their own rev R over their head, but was unable to see it on other people. Tried observing them, and I was still able to see the R's over other rev's heads (though now that I think about it, I did have admin combo hud on at the time, so i probably wouldn't have been able to tell anyway, woops!)

[![2021-11-12_00-00-39.png](https://i.imgur.com/F0vuYwnl.jpg)](https://i.imgur.com/F0vuYwn.png)

He seemed to be able to see some rev icons but not others after I unrev'd and re-rev'd him (which was done before the message where I asked "how about now"). This seems to be rare, but a few others players said they were affected by it after the round ended.

**Comment by Mothblocks** [comment]
One hundred percent related to #62718

**Comment by Mothblocks** [comment]
Old team antags can see new ones, not other way around.

**Comment by Mothblocks** [comment]
- A gets converted
- B gets converted (A sees B, B does not see A)
- A gets deconverted
- A still sees B's HUD, including when they get deconverted 😰

**Comment by Toastgoats** [comment]
I was revhead twice today and never noticed a missing rev hud for my teammates, but both rounds I had revs not seeing my hud. I was the first headrev both times.

Not sure this helps but I hope it does.

**Comment by Toastgoats** [comment]
Oh I didn't notice the pr fuck
