### ISSUE TITLE
Uses telekinesis to cut cloth with a sharp object telepots the cloth to you

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#62780]
## Round ID:
[172946](https://scrubby.melonmesa.com/round/172946)

## Reproduction:

- Drop gauze and a scalpel on the ground.
- Walk away a bit.
- Use telekinesis to grab the scalpel and cut the gauze with it telekinetically. 
- Watch as the cloth cut from the gauze teleports to your feet.

**Comment by ArcaneDefence** [comment]
tk is a blight on the codebase :))

**Comment by necromanceranne** [comment]
It really fucking is holy shit

**Comment by MrMelbert** [comment]
Addendum: Using wirecutters to telekinetically remove paper from a door also teleports the paper to your feet.
