### ISSUE TITLE
Escape alive triggers when the nuke goes off even if you're just sorta standing around in maint

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#62788]
## Testmerges:

The following pull requests are currently test merged:
#62771: 'Fix team antag HUDs displaying when they shouldn't, and the other way around' by Mothblocks at commit de9a58ae25
#62711: 'Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins' by Watermelon914 at commit 288695b981
#62727: 'Departmental Security Rework Option #1: Department First, Security Second' by Iamgoofball at commit 029f550f7e

## Reproduction:

Fart around all shift not doing much traitoring because you're tired as shit
Captain tucks disky into bed instead of trying to secure it in any way
Solo Op blows the station
Just sorta sit around in maint waiting for your end
Objective #3: Escape on the shuttle or an escape pod alive and without being in custody. Success!

**Comment by itseasytosee** [comment]
This is intended but super dumb, I think there's a thread on the form about it.
