### ISSUE TITLE
AIs can't play Orion trail.

### ISSUE THREAD

**Issue by Gristlebee** [tgstation/tgstation#62785]
## Testmerges:
#62771: 'Fix team antag HUDs displaying when they shouldn't, and the other way around' by Mothblocks at commit de9a58ae25
#62711: 'Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins' by Watermelon914 at commit 288695b981
#62727: 'Departmental Security Rework Option #1: Department First, Security Second' by Iamgoofball at commit 029f550f7e

## Reproduction:
1. Be AI.
2. See an Orion Trail arcade machine.
3. Open up the arcade menu and be unable to use any of the options.

**Comment by timothymtorres** [comment]
Technically the AI is already playing Orion trail with the crew on the station.

**Comment by datorangebottle** [comment]
> Technically the AI is already playing Orion trail with the crew on the station.

*spams the 'kill' button until nobody else is left*

**Comment by SuperNovaa41** [comment]
hmm other arcade games work

**Comment by timothymtorres** [comment]
> hmm other arcade games work

It appears that the default arcade game uses old boomer code while Orion uses tgui.

Anyway, I found the problem.  Looks like a simple fix.

https://github.com/tgstation/tgstation/blob/243cd2bfa55bbe757dc5b5a051d5711a1dfd143a/code/game/machinery/computer/arcade/orion.dm#L188-L195
