### ISSUE TITLE
You can become obsessed with the AI

### ISSUE THREAD

**Issue by itseasytosee** [tgstation/tgstation#62791]
## Round ID:
[172986](https://scrubby.melonmesa.com/round/172986)

## Testmerges:
 Fixes Massive Radio Overtime, Implements a Spatial Grid System for Faster Searching Over Areas by Kylerace
 Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins by Watermelon914
 Fix team antag HUDs displaying when they shouldn't, and the other way around, fix round end antag HUDs by Mothblocks

## Reproduction:
While comical, this is almost certainly not intended.
![image](https://user-images.githubusercontent.com/55666666/141654666-f4c45754-6be6-4163-8b35-0903b28bdfb1.png)

**Comment by NanoCats** [comment]
Feature.

**Comment by ATH1909** [comment]
https://en.wikipedia.org/wiki/Her_(film)

**Comment by itseasytosee** [comment]
I mean with a bit of work and maybe some custom objectives it could be really cool, but right now it sucks pretty bad.

**Comment by SuperNovaa41** [comment]
Hmmm
https://github.com/tgstation/tgstation/blob/abc5afe8c2f65079a0b0aaa5072bb898091cd0b9/code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm#L848-L852

**Comment by SuperNovaa41** [comment]
Oh, i see the problem now. They were originally human ("Murder Emily Blyant, Ay-Lo-Tree's coworker"). They must've been borged.
