### ISSUE TITLE
Catwalk Tiles placed on the lower level of tram appear to be on the upper level

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#62794]
> Be me, poor unfortunate soul trapped in the hell that is tramstation
> attempt to walk over the tram chasm
> it turns out the tile that I thought was bridged, isn't, because somebody put catwalk tiles on the lower level 
_†catwalk tiles as in the ones made of rods, NOT the ones you can build on empty space_
> break legs
> curse whoever designed tramstation

**Comment by timothymtorres** [comment]
Can you provide a screenshot the location this is happening?

**Comment by NanoCats** [comment]
> Can you provide a screenshot of the location this is happening at?

Literally anywhere there's a z-level difference

![image](https://user-images.githubusercontent.com/14065903/141850640-30bef599-1b83-4f1a-8036-adb6f8562d34.png)

Can you tell which of these catwalk tiles are really on the upper level, and which ones aren't? (No, you can't, a random assortment are actually on the undertram!)


As you can see here, the catwalk tiles have a subtle shadow so you can at least _sorta_ tell, the catwalk floor (Not sure what to call them to distinguish them from the other kind of catwalks)

**Comment by timothymtorres** [comment]
Wow this is god awful.  Thank you for providing a SS, I'll try to tackle this myself.

**Comment by timothymtorres** [comment]
This is from the map file on the upper level:

![StrongDMM_SmoFQcpVw3](https://user-images.githubusercontent.com/5195984/141923529-c4dccf3e-955a-4770-804c-6f4daa6529f0.png)

And this is from loaded map in game:

![dreamseeker_ocnJO7GFFE](https://user-images.githubusercontent.com/5195984/141923586-fe471e04-ea11-4c9f-a941-a19c570f6304.png)

**Comment by timothymtorres** [comment]
The glass tiles will require a code fix but the lattices should be a mapping fix.

**Comment by timothymtorres** [comment]
@NanoCats has the glass floor always done this or did this just recently start happening?

**Comment by NanoCats** [comment]
> @NanoCats has the glass floor always done this or did this just recently start happening?

The glass floors have literally always done this (†as far as I can remember). The catwalk tiles you can craft out of rods are however, new features.

Also can I just note that these glass floors look superior to other glass tiles and I can't seem to make them?

**Comment by timothymtorres** [comment]
Ok after tinkering with the code I believe the reason that the catwalks are overlapping the upper z level has something to do with the overlay for the catwalk changing the plane/layer of the turf.  I did fix the glass issue in #62875 but I need to do more testing.  Hopefully I can get this all resolved before December arrives.

**Comment by timothymtorres** [comment]
After working on this for 2 weeks my PR is finally done. ✅
