### ISSUE TITLE
Alt Click both rotates and changes the layers on pipes

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#62809]
## Testmerges:
The following pull requests are currently test merged:
#62771: 'Fix team antag HUDs displaying when they shouldn't, and the other way around' by Mothblocks at commit de9a58ae25
#62711: 'Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins' by Watermelon914 at commit 288695b981
#62727: 'Departmental Security Rework Option #1: Department First, Security Second' by Iamgoofball at commit 029f550f7e

## Reproduction:
try and rotate a pipe with alt click
it changes its layer too
be sad

**Comment by jacklecroy** [comment]
Maybe right click with a wrenching tool can change the layer instead?

**Comment by redguy999** [comment]
> Maybe right click with a wrenching tool can change the layer instead?

the issue here is that alt clicking changes both the rotation and the layer.
