### ISSUE TITLE
Hair gradient preference shows for species that don't have hair

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#62801]
Moths have the option to change their hair gradient, but don't have hair.

Just like how hair options are hidden, it should be hidden from species that do not have hair, and moved from non contextual preferences to secondary features.

**Comment by RuneQuester** [comment]
Mothblocks...giving their own issue....the "Good first issue" label.

**Comment by Mothblocks** [comment]
![image](https://user-images.githubusercontent.com/35135081/141704261-d0ba4b23-c595-4684-8588-5ea6d3a5e03b.png)
