### ISSUE TITLE
Time dilation seems to affect how much damage you get

### ISSUE THREAD

**Issue by Colovorat** [tgstation/tgstation#62812]
## Reproduction:

it was the end of the round so really shitty time dilation and i survived in space for so fucking long, while was exposed both to cold and pressure

**Comment by SuperNovaa41** [comment]
Yes that is in fact how time dilation works. (It slows down the tickrate, meaning you will take damage far slower)

**Comment by Colovorat** [comment]
> Yes that is in fact how time dilation works. (It slows down the tickrate, meaning you will take damage far slower)

well but i moved pretty long distance, with normal time dilation i would be already dead, so desync, and i consider that a bug

**Comment by LemonInTheDark** [comment]
we don't attempt to "catch up" for lost time in subsystems for separate reasons, so this is less a bug and more an inevitability of our processing model
