### ISSUE TITLE
Delta Teleporter shutters are not working correctly

### ISSUE THREAD

**Issue by Googles-Hands** [tgstation/tgstation#62815]
## Reproduction:
The Delta Teleporter room has two shutters, one shutter that opens the entire room to the public and one shutter that only opens the teleporting area itself, so people can walk in without being able to change the settings. The button for the second shutters is connected to the big shutters.
![delta shutters](https://user-images.githubusercontent.com/59937074/141698167-bcbc1640-9725-4f62-a922-39307f076bd2.png)

The button above that security officer is supposed to control the small shutters but it doesn't, picture for visualisation.

**Comment by Timberpoes** [comment]
Fixed in https://github.com/tgstation/tgstation/pull/62848
