### ISSUE TITLE
Chemical Grinder does not work

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#62822]
## Reproduction:

Chemical grinder does not suck up plants near it, nor does it accept plants from a plant bag.

**Comment by timothymtorres** [comment]
I've never heard of the grinder sucking up nearby plants but you should be able to dump plants from a plant bag into it.  I wonder if you had too many plants inside the grinder.  Once it gets full, I don't remember what happens but I think either the plants get blocked from being inserted into the grinder or they get dumped to the tile the grinder is on.

Can you retest this with the above information?

**Comment by TheBonded** [comment]
> I've never heard of the grinder sucking up nearby plants but you should be able to dump plants from a plant bag into it. I wonder if you had too many plants inside the grinder. Once it gets full, I don't remember what happens but I think either the plants get blocked from being inserted into the grinder or they get dumped to the tile the grinder is on.
> 
> Can you retest this with the above information?

Hi! The grinder they are referring to is the plumbing variant. It only accepts chemicals from the direction that the output pipe is facing. This means that you have to have the conveyor push the plants through the same side that the chemical pipe is connected. It should collect them from any direction, so this is a consistency issue.

**Comment by TheBonded** [comment]
Also, it only accepts plants being pushed into it, either with a conveyor or a pushbroom. Most of the time a 2x2 or 1x2 conveyor loop is made to keep feeding it plants placed on the conveyor.

**Comment by timothymtorres** [comment]
> Hi! The grinder they are referring to is the plumbing variant. It only accepts chemicals from the direction that the output pipe is facing. This means that you have to have the conveyor push the plants through the same side that the chemical pipe is connected. It should collect them from any direction, so this is a consistency issue.

Good to know.  I don't ever play chemistry so this is beyond my ability to troubleshoot.
