### ISSUE TITLE
Syndicate comm Agents, and Lifebringers cannot use their vending machine.

### ISSUE THREAD

**Issue by FreeGolem** [tgstation/tgstation#62827]
## Round ID: 

If you discovered this issue from playing tgstation hosted servers:
[Round ID]: [173063](https://scrubby.melonmesa.com/round/173063) (Happens on all rounds at the moment)

## Testmerges:

N/A, I don't think it's affected by testmerge. I think it's oversight.

## Reproduction:

 Observe Round, take a ghost role of either a Lifebringer (podmen) or a Syndicate Comm Agent/Bioweapon. You'll then find vending machines that you'll have to interface. For Syndicate Comm agents, this doesn't really sting as they're all just food/cosmetics/whatsnot. But for Lifebringers, this is extremely fatal, as they cannot get seeds needed to do lavaland foresting.

![SyndicateBUgs](https://user-images.githubusercontent.com/94327141/141703409-15a6eb57-4f19-461f-adc0-0648a37c981a.png)

**Comment by timothymtorres** [comment]
Maybe this is because you don't have any credits to buy stuff.

**Comment by MrMelbert** [comment]
> 
> 
> Maybe this is because you don't have any credits to buy stuff.

All the vendors off station are tagged such that everything in them are free
The credit amounts are still there but anyone can (could) buy anything

**Comment by tralezab** [comment]
I... wasn't able to reproduce this?

![image](https://user-images.githubusercontent.com/40974010/144549600-ce9b9045-0242-4172-8032-3fb6222f6240.png)

**Comment by jlsnow301** [comment]
![1](https://user-images.githubusercontent.com/42397676/146263436-d9bf287e-adb0-4860-8674-b0e6dbbba357.png)
#62863 should have fixed this. I cannot reproduce it either.
