### ISSUE TITLE
Clown mobs that drop banana peels don't stop dropping them when inside bluespace bodybags

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#62828]
Reporting client version: 514.1568

## Round ID:
[173061](https://scrubby.melonmesa.com/round/173061)

## Reproduction:

- Create one of many eldritch clown demons that passively spawn banana peels below or around them. 
- Place said clown demon into a bluespace bodybag and walk around the station.
- Banana peels will follow you in your wake, with no clear cause. Confuse and annoy everyone.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/3c4196e9600c625c1d5080e56365d5f19f61f21e/code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm#L51-L57
