### ISSUE TITLE
Cargo drone console "remove item" buttons are unaligned 

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#62838]
## Round ID:

[173080](https://scrubby.melonmesa.com/round/173080)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/141734568-36a8ae1f-edbf-480a-b49d-15b53c7ee729.png)

**Comment by timothymtorres** [comment]
Looks like it might have something to do with the TGUI menu

**Comment by redguy999** [comment]
where is the code/markup for all the panels anyway?
