### ISSUE TITLE
New Cargo console pain.

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#62834]
Whoever wrote this cargo rework did NOT test it thoroughly enough! 

ISSUES:

- Clowns cannot order anything despite belonging to service!
- Setting the console to "broad" was not accounted for! it just does this 
![image](https://user-images.githubusercontent.com/14065903/141709447-10df38c1-ed23-45a8-9a44-a1299464aa03.png)
- I don't like that you are STRICTLY limited to things "relevant" to your department, Engineering can't buy pizza :(

**Comment by Mooshimi** [comment]
Can clowns still not order things? I know things have been changed around with this console

**Comment by JohnFulpWillard** [comment]
This is fixed eventually
