### ISSUE TITLE
Radios don't turn off their speakers.

### ISSUE THREAD

**Issue by oklews** [tgstation/tgstation#62835]
## Testmerges: 
#62711: 'Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins' by Watermelon914 at commit 5f7baa8772
#61422: 'Fixes Massive Radio Overtime, Implements a Spatial Grid System for Faster Searching Over Areas' by Kylerace at commit ea8697be8a

## Reproduction:
Grab a station bound radio
turn on the microphone
turn off the speaker
find that the microphone is a speaker
(Derpman3 was toying with it with me, it wasn't my headset, it wasn't wires, it was just the radio being bugged)

**Comment by timothymtorres** [comment]
@Kylerace This looks like a TMB from #61422

**Comment by NanoCats** [comment]
Technically, a microphone and speaker are the same devices working in reverse \s

**Comment by Kylerace** [comment]
> 
> 
> @Kylerace This looks like a TMB from #61422

yep

**Comment by oklews** [comment]
To verify, using the microphone causes the message to be heard by you on the channel, I’m not certain if it works for other channels though.

**Comment by Kylerace** [comment]
i cant replicate this at all

**Comment by oklews** [comment]
Grab a radio and set it to 148.1, turn off speaker and turn on mic, it'll work. I wonder if it's not a test merge bug and instead a confession booth bug.

**Comment by oklews** [comment]
still not working, just tested it, still sends out sound despite being off

**Comment by LemonInTheDark** [comment]
@Kylerace

**Comment by Kylerace** [comment]
once again completely unable to replicate this

**Comment by oklews** [comment]
After testing it, it seems fixed!
