### ISSUE TITLE
The auxiliary base management console spits raw HTML

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#62859]
Reporting client version: 514.1569

## Round ID:
[173123](https://scrubby.melonmesa.com/round/173123)

## Testmerges:
- [Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins](https://www.github.com/tgstation/tgstation/pull/62711)

## Reproduction:
`"The auxiliary base management console beeps, "<span class='danger'>Launch sequence activated! Prepare for drop!!</span>""`
not sure whats wrong, but its not suppose to do that.

**Comment by Mothblocks** [comment]
please make your titles useful

**Comment by redguy999** [comment]
My apologies, @Mothblocks, it was late when i made this.

**Comment by TheBoondock** [comment]
This should already be fixed in pr #66323
