### ISSUE TITLE
Unnecessary firelock on metastation near cargo's warehouse

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#62856]
## Round ID:
[173121](https://scrubby.melonmesa.com/round/173121)

## Testmerges:
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 8a2a144a1eb1cead518d6d902c98f5ab0e23a873
The following pull requests are currently test merged:
#62711: 'Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins' by Watermelon914 at commit 5f7baa8772

Local commit: dc3151a41fdc89fe1e476d99cb12883d66f021ac
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:
Go to Metastation's warehouse above cargo. See an unnecessary firelock in a wall. In the picture it is immediately to the right of my ghost.
![firelock](https://user-images.githubusercontent.com/22053757/141872937-e2f2013b-9c95-4315-89e8-091195cc6832.PNG)
.

**Comment by newfren** [comment]
I believe this happens because that door has a chance to be replaced by a wall, or bolted with bolt lights off, or welded shut at round start, like most maint doors. I have no idea why that's applied to these cargo airlocks too.

**Comment by BlueMemesauce** [comment]
i fixed it
