### ISSUE TITLE
Borgs can notice their skin is covered in fresh radiation burns

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#62869]
I didn't grab the round id because I'm dumb!

https://puu.sh/Ipwlh/9cf3cc730b.png

This message shouldn't show up for robots

**Comment by ATH1909** [comment]
does this cause burn damage to them?

**Comment by newfren** [comment]
this message doesn't cause burn damage to anyone, this is just the message that happens when someone's dusted on the sm
