### ISSUE TITLE
Hover Camera sees all your sins

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#62879]
## Testmerges:

BYOND Version: 514.1557
Server revision compiled on: 2021-11-15
Master commit: 28259261fa975a007afd0f9714cd71e52fbb4239

## Reproduction:

1. Load tramstaiton (unsure if this is just on tram)
2. Cameras anomalously float in mid air
3. Profit! (Not really)
![image](https://user-images.githubusercontent.com/14065903/142064879-ec6b1834-501a-4daf-87a8-5c44dfc3ec2c.png)

**Comment by redguy999** [comment]
ice box has one like this outside RnD

**Comment by dragomagol** [comment]
Fixed by a couple of mass repathing PRs.
