### ISSUE TITLE
ethereals with dangerously high charge levels can't discharge their energy into full APCs

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#62884]
```
/atom/movable/screen/alert/ethereal_overcharge
	name = "Blood Overcharge"
	desc = "Your charge is running dangerously high, find an outlet for your energy! Right click an APC while not in combat mode."
	icon_state = "cell_overcharge"
```
Oh no, I stood in a fully upgraded cyborg recharger for a second too long, and now I'm dangerously overcharged! I guess I should do what this alert says and try to channel my energy into an APC.
```
if(cell.charge >= cell.maxcharge - APC_POWER_GAIN)
	to_chat(H, span_warning("The APC can't receive anymore power!"))
	return
```
Guess I'll (contract a heart attack and) die.

The only way I know of to discharge energy in this state is to either risk a heart attack from those random bolts of electricity or replace an APC's cell with an empty one and then quickly drain the APC before the power grid returns it to 100% power. You can't channel energy into a cell directly, you can only drain it (or put it in an APC and THEN channel energy into it).

**Comment by LemonInTheDark** [comment]
This isn't a bug

**Comment by SuperNovaa41** [comment]
This is literally intended. Why would you be able to put all your energy into in APC? then IT would be dangerously overloaded

**Comment by ATH1909** [comment]
> This is literally intended. Why would you be able to put all your energy into a full APC? then IT would be dangerously overloaded

okay but you literally don't have any other method to discharge yourself

like, I'm not doing this to recharge the apc, I'm doing it to waste power. I could be channeling into a chair for all I care.

**Comment by LemonInTheDark** [comment]
Don't get overcharged. Or hell get permission to make something that acts as more of a powersink. But this isn't a bug, it's a feature request
