### ISSUE TITLE
Floorbots have lost their zest for life

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#62880]
## Testmerges: 
BYOND Version: 514.1557
Server revision compiled on: 2021-11-15
Master commit: 28259261fa975a007afd0f9714cd71e52fbb4239

## Reproduction:

1. Make a floorbot by any means necessary.
2. It stubbornly refuses to do anything aside from wander the station uselessly, all the floorbots in this picture are active and should be doing... something (There are nice, tasty barren floors to tile over!).   I messed with them plenty, but I cannot convince the floorbots to do anything barring aimless wandering.
3. 
![image](https://user-images.githubusercontent.com/14065903/142066309-d8d43aa4-14f3-4555-9cc4-b3b9c4a50fb8.png)

Furthermore, you can't load it with retextured "standard" iron tiles, it will merely declare the floorbot can make those, even if I want dark textured tile number four or whatever.  Furthermore I would suggest replacing the term "Place custom" with "REplace with custom" because one of the chief uses of floorbots is automatic decoration 

P.S what the fuck does having the maintenance door open do?

**Comment by SuperNovaa41** [comment]
The maintenance door probably lets you dissasemble it + insert a PAI in it

**Comment by Donpedrito** [comment]
As I recall it, you only need to unlock it with an ID to insert a pAI, but you need to unlock, then screwdriver open the maintenance door to repair it with a welder. Unsure about deconstruction.

**Comment by TheBonded** [comment]
Supposedly fixed by https://github.com/tgstation/tgstation/pull/62878, I'll close this now.

**Comment by NanoCats** [comment]
> Supposedly fixed by #62878, I'll close this now.

Test commander Blu here, nope I'm afraid not!

![image](https://user-images.githubusercontent.com/14065903/142343373-db386d37-56b8-417f-85b5-d8a605e72146.png)

†Master commit: 9ace5b7b705050d834993491430b246664e89a70! (Two hours ago)

**Comment by NanoCats** [comment]
![image](https://user-images.githubusercontent.com/14065903/142344510-3e8dd70b-7c86-4f4b-b3a7-90c132ca0c51.png)

Even threats of destruction are not enough to force the floorbot into action.
