### ISSUE TITLE
Building or reassembling a hydroponics tray creates plumbing graphic

### ISSUE THREAD

**Issue by BangingDonk** [tgstation/tgstation#62895]
## Reproduction: The creation of new hydroponics trays also creates a plumbing tube with them. The plumbing tube can be rotated, but not hidden as it normally appears on naturally-spawned hydroponics trays. If there is a way to disable this plumbing from appearing, it is not made clear in the object description.

![Hydroponics Red Pipe 2021-11-16](https://user-images.githubusercontent.com/16439557/142139717-ad843e78-d128-4781-834d-8233426f4c22.PNG)

**Comment by Time-Green** [comment]
Assuming you wrenched it down on an unplated tile and then put a tile over it?

**Comment by BangingDonk** [comment]
> Assuming you wrenched it down on an unplated tile and then put a tile over it?

Sorry for the delay, it's been an interesting few days as of late. I just booted up a local instance which I can't guarantee is the EXACT same state as the reported conditions, but should be close enough for this niche case scenario.

Deconstructing and reconstructing a tray on a plated surface displays the pipe as reported. Deconstructing and reconstructing a tray on an unplated surface displays the pipe as intended.

The instance of the pipe appearing on plated surfaces can be fixed by removing the plating with a crowbar and reapplying it. Which is a little awkward, but better than nothing.

**Comment by Time-Green** [comment]
No problem at al! Quick responses with issues like these really dont matter

Also, do you have a suggestion of how it should work? All plumbing machinery (including the hydrobeds) use this system, aswell as atmospherics. The issue here is that hydrobeds aren't plumbing connected that much, so it stands out when the pipes appear

**Comment by BangingDonk** [comment]
If it's just how plumbed machinery works re: showing piping on construction regardless of tiling underneath it, we can go ahead and call this closed as not-a-bug. In a perfect world, the piping would only show if the machinery were constructed on a tile that's not plated, but this is seeming like a very niche case scenario that I'm running into and am willing to accept it as such.
