### ISSUE TITLE
PDA messages are fubar.

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#62897]
## Round ID: Manuel: R173173

 <html>
<body>

Testmerges: #62711
--

</body>
</html>

## Reproduction:

1. Click "messages" on your pda
2. unable to view message history as nothing happens :) 
![image](https://user-images.githubusercontent.com/14065903/142142349-fd0b4576-b5a5-45be-8151-1d5f40667ef5.png)

noticed because I keep my PDA in my bag to avoid having all my fucking limbs blown off, heard my PDA go "beep" and then nothing happened when I went to check my messages.

**Comment by SuperNovaa41** [comment]
Does the messages screen pop up? Or are you just stuck on the contact list

**Comment by NanoCats** [comment]
> Does the messages screen pop up with no messages? Or are you just stuck on the contact list

Can't open "messages" at all.
