### ISSUE TITLE
Charlie Station can't buy their own dinnerware

### ISSUE THREAD

**Issue by BangingDonk** [tgstation/tgstation#62896]
## Reproduction: Following changes to vendor costs and job access, Charlie Station's Plasteel Chef's Dinnerware Vendor costs credits to use. As Charlie Station IDs don't have credits, that means they cannot purchase any of their kitchen equipment. This makes Charlie's food situation, already hampered by a lack of oven and griddle, even worse. Ideally, Charlie Station IDs would come with money or the vendor would be set to give items for free.

![Chef Money 2021-11-16](https://user-images.githubusercontent.com/16439557/142140481-8db05e1e-042a-433c-81f2-a7b47ae22227.PNG)

**Comment by NanoCats** [comment]
This should be a simple mapping change yeah? There are already vendors set up to give free shit.

**Comment by TheBonded** [comment]
> This should be a simple mapping change yeah? There are already vendors set up to give free shit.

It seems like all of the vendors that give free items are bugged, as this is the second issue report describing this issue, the first being for the lavaland syndies. It's possible that you need to have an ID with an account to use them, or that the vendors themselves are bugged

**Comment by NanoCats** [comment]
> > This should be a simple mapping change yeah? There are already vendors set up to give free shit.
> 
> It seems like all of the vendors that give free items are bugged, as this is the second issue report describing this issue, the first being for the lavaland syndies. It's possible that you need to have an ID with an account to use them, or that the vendors themselves are bugged

Would it be a bad idea to suggest that more people (or, should I say roles?) get bank accounts? I thought it was kind of silly that any time I spawn in as anything but a normal station crewmate I have no bank account.  The closest you can do is if you're a ghost role, you can metagame remembering your human bank account ID lol.

**Comment by TheBonded** [comment]
> > > This should be a simple mapping change yeah? There are already vendors set up to give free shit.
> > 
> > 
> > It seems like all of the vendors that give free items are bugged, as this is the second issue report describing this issue, the first being for the lavaland syndies. It's possible that you need to have an ID with an account to use them, or that the vendors themselves are bugged
> 
> Would it be a bad idea to suggest that more people (or, should I say roles?) get bank accounts? I thought it was kind of silly that any time I spawn in as anything but a normal station crewmate I have no bank account. The closest you can do is if you're a ghost role, you can metagame remembering your human bank account ID lol.

I think they don't have bank accounts because it wouldn't make sense for Syndicate scientists, hundred year old Nanotrasen research crew, or other non-modern/non-Nanotrasen people to have bank accounts that use Nanotrasen credits. 

That is, assuming these credits are Nanotrasen specific, which I think would make sense considering the supposed currency of the Syndicate are telecrystals, and how much money is included in the 1TC cash briefcase, which implies that the credits are of very little worth to the Syndicate.

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/62863
