### ISSUE TITLE
Drone repair prompt incorrect.

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#62906]
Reporting client version: 514.1569

## Round ID:
[173208](https://scrubby.melonmesa.com/round/173208)

## Testmerges:
- [Move refactor](https://www.github.com/tgstation/tgstation/pull/62605)
- [Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins](https://www.github.com/tgstation/tgstation/pull/62711)

## Reproduction:
As a drone, get repaired by someone else.
![2021-11-17 12_57_52-Window](https://user-images.githubusercontent.com/36066032/142273362-5c6deb0d-ed72-4c94-8550-0fa6136823c7.png)

**Comment by jlsnow301** [comment]
Looks like this was improperly linked in #62979
