### ISSUE TITLE
Lavaland ash storms no longer replenish ash on the ground

### ISSUE THREAD

**Issue by TheBonded** [tgstation/tgstation#62912]
## Reproduction:
1. Dig up some ash from the ground on lavaland, using a shovel, drill, pickaxe, or your other preferred mining tool
2. Wait for an ash storm
3. Read "The emberfall slows, stops. Another layer of hardened soot to the basalt beneath your feet." in chat when it ends
4. Be unable to dig up more ash on the same spots you had dug it up before. I'm pretty sure this used to work.

relevant code: https://github.com/tgstation/tgstation/blob/master/code/datums/weather/weather_types/ash_storm.dm

**Comment by Ghommie** [comment]
Did they actually replenish ash turfs to start with?

**Comment by TheBonded** [comment]
> Did they actually replenish ash turfs to start with?

I do remember them doing it at some point, sometime last year, yeah.

**Comment by Ghommie** [comment]
Okay dokay then.
