### ISSUE TITLE
Saved outfits don't copy everything they should 

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#62924]
## Testmerges:

BYOND Version: 514.1557
Server revision compiled on: 2021-11-15
Master commit: 9ace5b7b705050d834993491430b246664e89a70
Local commit: 28259261fa975a007afd0f9714cd71e52fbb4239

## Reproduction:

1. Make an outfit for a custom purpose that you want to use later by right clicking yourself (with all the goodies the outfit is supposed to have) and going View Variables > dropdown menu > copy outfit
2. Later on, go to the "select equipment" panel, apply your loadout
3. Sigh with immense disappointment that it failed to copy _everything_ as you had it, realizing that you're suck with the "basic" state of these items and that this feature's possibilities are limited

My example in point is as follows

1. I make an outfit, call it "Alpha Test Commander" for playing with things to reproduce bugs, try things out, and so on
2. I say, give myself a toolbelt, but I custom load it with the tools I use instead of the default 
![image](https://user-images.githubusercontent.com/14065903/142339305-f9e0f6f4-d60f-4e7c-a5a2-cfd652485b74.png)
3. I save the outfit to a file, or to the server, whatever
4. I load the outfit
5. The belt is stocked with its "default" items instead when loaded :(!
![image](https://user-images.githubusercontent.com/14065903/142339347-c986d752-609a-4c93-8bd4-da1e0b28a89c.png)

This has significant implications if someone, say, an actual admin of the real servers, wanted to make an outfit and have a select-equipment outfit with special quirks, for example:
- A loadout that gives the individual a bottle of custom pills in their backpack
- an air tank with custom contents to the tune of Air + Stimulum 
- a gun modified to do an insane/no amount of damage (deathsquad clown but it's OK because his weapons all do one damage, honk!)

I'm sure that _technically_ if I really knew what I'm doing, I could modify the JSON file to have all this extra stuff manually, but that would take a long time, and be really annoying, plus, the VV  > copy outfit command should probably just be well crafted enough to do this by itself.

**Comment by FlamingCheese** [comment]
If you save an outfit with /cyberimp inside the mob, they won't be applied unless you have the cyberimp included in the loadout (in a bag, there is also issues with it showing action buttons if a cyberimp is loaded from a outfit)

**Comment by Mothblocks** [comment]
Saved outfits are just JSON files with typepaths. You can't specify variables.

You wouldn't want to either. Proper serialization of this stuff is *really* finnicky, especially since we reserve the right to change variables and whatnot.

I'm going to close this as, with what I know about custom outfits, this would be an extreme burden to support and maintain.

**Comment by Mothblocks** [comment]
As an example, how would you specify the serialization of belt contents?

It's not just a variable. Those are individual objects, unless we would be saving *every single object in the belt* (it's not trivial to know what should actually be saved and what shouldn't be without us specifying `tmp` everywhere)? You would need some custom (bespoke) solution, likely of just typepaths, but then what if you want to change the variables inside those too?
