### ISSUE TITLE
Sometimes you just... can't hear borgs

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#62938]
## Round ID:
[173276](https://scrubby.melonmesa.com/round/173276) 

## Testmerges:
#62711 #61422

## Reproduction:
No idea what caused it unfortunately, but I've heard of this happening twice now. Was able to see myself as a medborg talking in chat and above my head, but the person I was talking to didn't receive any of it. 
They were also reportedly unable to see themselves speak while buckled to me.

**Comment by LemonInTheDark** [comment]
@Kylerace

**Comment by SuperNovaa41** [comment]
good

**Comment by Kylerace** [comment]
another one of these 😔

**Comment by LemonInTheDark** [comment]
Sometimes... EVERYTHING EXPLODES (Only like 1/10 times hey guess what it's somehow related to dynamic)

**Comment by Kylerace** [comment]
im not entirely sure why this would happen with the version of the tm you played but i added nullchecking to the one area that might cause it so i should be able to see it happen
