### ISSUE TITLE
Abandoned crates will delete their contents when exploded, including humans

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#62945]
## Testmerges:

BYOND Version: 514.1557
Server revision compiled on: 
Master commit: a41c00426dbb63f1e88b512fd9270b29ff1e4926
The following pull requests are currently test merged:
#62711: 'Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins' by Watermelon914 at commit dc963ca82a

Local commit: 46c7e5c4f6d3f0b859b9fdd5dbf315382e8a8ecd
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:

1. Locate an abandoned crate
2. Use elite problem solving skills to open it 
3. Stuff a hostage into the crate
4. Right click it again to lock it
5. wait for somebody to attempt to liberate your captive (Or do it yourself if you don't mind exploding)
6. Watch as your victim, disappears! (Abra Kedabra!)
7. in addition to the hilarious explosion, discover that whatever (or whoever) was in the crate is **literally fucking qdel'd** (Dchat at the time theorized that it was because the crates are programmed to destroy their contents as an anti-cheese mechanism where you just blow it on purpose and take the loot from the wreckage)

![image](https://user-images.githubusercontent.com/14065903/142580547-cda1a642-8dae-45fc-8e84-d58c7732f955.png)

I was asked "not to make a habit of this" but I still really want to do this, I'm hoping that whoever fixes this makes it so that you can still do this, but that if you open and re-close a crate, it doesn't _erase_ things inside, just a normal 'splode.

**Comment by tohg7** [comment]
"Looks like you're going to the shadow Realm, Jimbo"

**Comment by Mothblocks** [comment]
Please make your titles more useful to people trying to fix them.

**Comment by SuperNovaa41** [comment]
Ok now put the nuke disk in it

**Comment by NanoCats** [comment]
> Ok now put the nuke disk in it

Certain items cannot be erased this way, the pinpointer, the disc, etc, in the wreckage of the crate the pinpointer and hand tele were the only things left.
