### ISSUE TITLE
Issue with numpad keys not registering/functioning properly for keybinds

### ISSUE THREAD

**Issue by Laz0rG** [tgstation/tgstation#62959]
## Round ID: 
irrelevent

## Testmerges: 
irrelevent

## Reproduction:

Attempt to bind a function in the key bindings menu with the numpad with numlock enabled, and you are given a corresponding non-numpad number. Do it without the numpad and you're given an orientation input which conflict with arrow key movement

Despite this, old pre-existing NUMPAD bindings work as intended (as long as numlock is enabled), which are displayed as "Numpad#"

**Comment by LemonInTheDark** [comment]
The detection method for numpad keys has changed? The old method was based on the keycode, this new one is using the key event's location. It's strange, since it ought to work. Wonder if this is an ie thing?
