### ISSUE TITLE
You can't light a bonfire with a body in fire, in my case plasmeme

### ISSUE THREAD

**Issue by Colovorat** [tgstation/tgstation#62963]
Reporting client version: 514.1568

## Round ID:
[173326](https://scrubby.melonmesa.com/round/173326)

## Testmerges:
- [Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins](https://www.github.com/tgstation/tgstation/pull/62711)

## Reproduction:

remove helmet as plasmeme, thinking you will light bonfire.
despair

**Comment by ShizCalev** [comment]
lmao

**Comment by ShizCalev** [comment]
were you standing right on top of it when it happened or did you move onto it after
