### ISSUE TITLE
Nuclear Operatives unable to hear station communications

### ISSUE THREAD

**Issue by SppokiBoogi** [tgstation/tgstation#62962]
Reporting client version: 514.1557

## Round ID:
[173327](https://scrubby.melonmesa.com/round/173327)

## Testmerges:
- [Fixes Massive Radio Overtime, Implements a Spatial Grid System for Faster Searching Over Areas](https://www.github.com/tgstation/tgstation/pull/61422)
- [Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins](https://www.github.com/tgstation/tgstation/pull/62711)
- [[DNM] Log zero pickweights, fix current consumers](https://www.github.com/tgstation/tgstation/pull/62940)
- [Fixing parallax plane above blackness ](https://www.github.com/tgstation/tgstation/pull/62902)

## Reproduction:

Currently nuclear operatives are unable to hear radio chatter from the station while inside of their starting area. Nukies were still able to hear syndicate comms as normal.

The issue is present at round start and should be repeatable by having round start nukies.

 Attempted to fix the issue by giving the nukies new headsets, including centcom headsets and none worked. 

Was informed the issue was due to the current Radio TM and told to report it here.

**Comment by LemonInTheDark** [comment]
#61422 @Kylerace

**Comment by Kylerace** [comment]
fixed as of latest version
