### ISSUE TITLE
You can buckle to things on tiles with dense atoms that you can't stand on

### ISSUE THREAD

**Issue by Ryll-Ryll** [tgstation/tgstation#62974]
Reporting client version: 514.1557

## Round ID:
[173390](https://scrubby.melonmesa.com/round/173390)

## Testmerges:
- [Fixing parallax plane above blackness ](https://www.github.com/tgstation/tgstation/pull/62902)
- [[DNM] Log zero pickweights, fix current consumers](https://www.github.com/tgstation/tgstation/pull/62940)
- [Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins](https://www.github.com/tgstation/tgstation/pull/62711)
- [Fixes Massive Radio Overtime, Implements a Spatial Grid System for Faster Searching Over Areas](https://www.github.com/tgstation/tgstation/pull/61422)

Basically, you can buckle to atoms on tiles with other dense atoms that would prevent you from actually moving to said tile

## Reproduction:
[![dreamseeker_2021-11-20_20-53-19.png](https://i.imgur.com/hcn7cZIl.jpg)](https://i.imgur.com/hcn7cZI.png)

I was able to buckle myself to the chair in the above picture, which shouldn't happen. I still counted as being on the tile I'm shown on.

[![dreamseeker_2021-11-20_20-53-51.png](https://i.imgur.com/zHc7C4kl.jpg)](https://i.imgur.com/zHc7C4k.png)

Still able to pull the chair out of it though, at which point the buckled person follows with it correctly, even if I pull it to the opposite side of the dense atom, making the buckled person phase through it

[![dreamseeker_2021-11-20_20-57-38.png](https://i.imgur.com/Jl2H8e5l.jpg)](https://i.imgur.com/Jl2H8e5.png)

Notably, I was unable to buckle either myself or my doppleganger to the chair when there was an actual dense turf on it.

**Comment by SuperNovaa41** [comment]
man i swear i fixed this issue like a year ago

**Comment by SuperNovaa41** [comment]
https://github.com/tgstation/tgstation/pull/58230 ok i definitely DID fix this issue, some mf broke it again

**Comment by TheBonded** [comment]
looks like it was broken over the course of a few prs, but also looks like your fix had made it unable to buckle to vehicles.

**Comment by SuperNovaa41** [comment]
Closed by https://github.com/tgstation/tgstation/pull/63277
