### ISSUE TITLE
Snowed over tile inside bar

### ISSUE THREAD

**Issue by Ed640** [tgstation/tgstation#62986]
Reporting client version: 514.1569

## Round ID:
[173408](https://scrubby.melonmesa.com/round/173408)

## Testmerges:
- [Revert "Fixes emptied shot glasses having the drinking glass filling icon."](https://www.github.com/tgstation/tgstation/pull/62975)

## Reproduction:
![scrnshotSnowedoverPlatingCrop](https://user-images.githubusercontent.com/16868239/142755058-62b422d6-f44e-45b3-a195-bbd50cb784d8.png)
This tile underneath the red light was a snowed over plating, freezing the bar at roundstart. An admin fixed it and said to report it.

**Comment by MrMelbert** [comment]
![image](https://user-images.githubusercontent.com/51863163/142781808-c5e4e429-70b9-4bab-807d-0e8f0acdc00e.png)
Might've been the result of a merge conflict, oops
