### ISSUE TITLE
Roller Beds are immune to falling

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#62980]
Reporting client version: 514.1567

## Round ID:
[173394](https://scrubby.melonmesa.com/round/173394)

## Testmerges:
- [Fixes Massive Radio Overtime, Implements a Spatial Grid System for Faster Searching Over Areas](https://www.github.com/tgstation/tgstation/pull/61422)
- [[DNM] Log zero pickweights, fix current consumers](https://www.github.com/tgstation/tgstation/pull/62940)
- [Fixing parallax plane above blackness ](https://www.github.com/tgstation/tgstation/pull/62902)
- [Revert "Fixes emptied shot glasses having the drinking glass filling icon."](https://www.github.com/tgstation/tgstation/pull/62975)
(Though I highly doubt it was caused by any of these testmerges)

## Reproduction:
- Go next to a chasm that leads to a z-level below;
- Get a roller bed and buckle something to it;
- Try to push the roller bed off the chasm;
- Roller bed goes BRRRRRRRR

![image](https://user-images.githubusercontent.com/42555530/142748514-f3fff92a-7e59-444f-85f9-b61014b3c993.png)

https://user-images.githubusercontent.com/42555530/142748498-f9ed34ec-d7b8-43d7-9055-ede1d54efb2f.mp4

**Comment by optimumtact** [comment]
simple solution they're hoverbeds

**Comment by LemonInTheDark** [comment]
They need little jets

**Comment by interestingusernam3** [comment]
Incredible
