### ISSUE TITLE
attempting to use the Nar'Sie rune in the rage cage of the abandoned gambling den fails

### ISSUE THREAD

**Issue by castawaynont** [tgstation/tgstation#62984]
## Reproduction:
Sac cult target, roll abandoned gambling den as your summon area. Attempt to draw the rune in the middle of the rage cage, fail

**Comment by SuperNovaa41** [comment]
What was the message? was it the veil is not weak enough here thing? I think theres been an issue with any maint based summon for a while

**Comment by MrMelbert** [comment]
Not a bug, just an oversight with the name of some areas.

Deltastation has 2 abandoned gambling dens in maintenance, both use the same area name, but there's no way to differentiate in game.

Same problem is evident with the "Customs" area.
