### ISSUE TITLE
Holy shit we keep catching on fire

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#62992]
Reporting client version: 514.1569

## Round ID:
[173425](https://scrubby.melonmesa.com/round/173425)

## Testmerges:
- [Revert "Fixes emptied shot glasses having the drinking glass filling icon."](https://www.github.com/tgstation/tgstation/pull/62975)
- [Move refactor](https://www.github.com/tgstation/tgstation/pull/62605)
- [Prevents failrp from missing ! and hitting ~](https://www.github.com/tgstation/tgstation/pull/62921)
- [Revert "Replacing more C-style for loops with the faster, traditional](https://www.github.com/tgstation/tgstation/pull/62991)

## Reproduction:

Go on terry
Holy shit we keep catching fire

this is against god, nature, the universe, physics, and everything fucking else

**Comment by SuperNovaa41** [comment]
Can you give more info? This doesn't give us anything

**Comment by Addust** [comment]
People keep completely randomly catching on fire. Purely RNG. Terry is a good example of this right now, go observer there and you'll see a shitton of random combustions

**Comment by itseasytosee** [comment]
Is this a thing that has happened over the course of more than one round?

**Comment by Addust** [comment]
Yes. Like most of terry's rounds today

**Comment by Addust** [comment]
Might have begun being fixed though

**Comment by LemonInTheDark** [comment]
This was the move refactor. Connect loc is the worst

**Comment by TemporalOroboros** [comment]
> This was the move refactor. Connect loc is the worst

How?

**Comment by LemonInTheDark** [comment]
I don't really want to know, I think it was fire detaching from the source of the fire or something. Should be fixed? now

**Comment by interestingusernam3** [comment]
We do a substantial amount of trolling

**Comment by ATH1909** [comment]
pffffffft

**Comment by TheBonded** [comment]
to be fair terry was already a few fires short of hell so this didn't really change much

**Comment by LemonInTheDark** [comment]
Related pr is closed, 🤞 this should be fixed 👊🪵
