### ISSUE TITLE
Bizarre lighting bug on half dark floor tiles.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#63005]
This is something I noticed while doing a remap of meta station's atmos. 

I have these half dark tiles running down the center of the room to visually section it off. I noticed the lighting was slightly weird around these tiles, and after removing some lights it got even weirder with some darkness involved. Even in this image, there's still odd lighting at the bottom of the image.

![dreamseeker_pRrXybZFoD](https://user-images.githubusercontent.com/33107541/142822029-68c5dff5-8308-4a4f-91e7-32e5e03bc15b.png)

After replacing the tiles with normal grey floor tiles it all looks as expected for a darkened spot:

![dreamseeker_JjvjeNhKDk](https://user-images.githubusercontent.com/33107541/142822209-91e09651-d139-4659-aa65-757e6d85ba94.png)

I've tried a wide variety of floor tile types and skins and I didn't find any other tiles that produced this odd lighting, so I'm thinking it's only happening with the half dark grey floor tiles...?

**Comment by LemonInTheDark** [comment]
You can't have a testmerge bug on a local

**Comment by Zytolg** [comment]
It might be worth noting that I've observed the lighting bug several times in Away Missions

**Comment by Kylerace** [comment]
this is just like what happened with openspace tiles. those turfs most likely use the icon_state "dark" which is the same name as the one underlays use even if that icon_state isnt being used to the underlay currently applied to the turf
