### ISSUE TITLE
Mime and Clown fan huds no longer show up

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63003]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/142800435-a04fcbe8-a941-4c17-a529-972b2401ae13.png)

- Be mime fan or clown fan
- Put pin on chest
- No hud.

 Likely has to do with the recent HUD refactorings, so I'm tagging @JohnFulpWillard .

**Comment by JohnFulpWillard** [comment]
![image](https://user-images.githubusercontent.com/53777086/142802474-071c766b-a669-4114-ac6e-f24a2184cd70.png)
IT WORKS FUCK YOU

**Comment by MrMelbert** [comment]
I'll assume the servers weren't updated in time, then
