### ISSUE TITLE
Pumps and other atmos devices named in a map editor don't retain their name in game.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#63006]
Something I've noticed for a while ever since smartpipes, and most noticeably while mapping a new meta atmos.

Pumps and valves in most atmos setups are named in the editor to provide identification and helps with understanding where the pumps are sending gas. However, starting when I'm assuming smartpipes were added, these names don't seem to transfer over in game.
![dreamseeker_H04nlP2Kjp](https://user-images.githubusercontent.com/33107541/142835186-9faea355-7af7-4656-8891-155030e3d2b0.png)

In SDMM:
![image](https://user-images.githubusercontent.com/33107541/142835312-91fbe446-e654-469f-8d47-cf7043303bb8.png)

In game:
![dreamseeker_J9XREXA0mW](https://user-images.githubusercontent.com/33107541/142835348-39469355-e548-4603-999f-b89e409dc251.png)

**Comment by Mothblocks** [comment]
sourced from my todo:

![image](https://user-images.githubusercontent.com/35135081/142945008-940871b0-a9a8-42b5-8022-662b35415b97.png)

**Comment by LemonInTheDark** [comment]
#62782 appears to have halfway done it, but it's not using mapload

**Comment by ShizCalev** [comment]
62782 should have resolved this for everything but vents and scrubbers. Will hit those in the afternoon myself.

**Comment by LemonInTheDark** [comment]
will initial() respect map edits?

**Comment by Mothblocks** [comment]
No--that's the problem. They're using `initial(name)` now, but what we really want is to save the name on map init, and reference that var.
