### ISSUE TITLE
Vending machine says I don't have enough money even though I do.

### ISSUE THREAD

**Issue by Edelor68** [tgstation/tgstation#63020]
## Reproduction:
Refer to title
![SS13BugMoneee173534](https://user-images.githubusercontent.com/85312201/143023930-105457fb-a9b3-49cf-b13d-548d8c19f13b.png)

**Comment by Burgermancoding** [comment]
Where did you have the card, in the ID slot, in your hand?

**Comment by Edelor68** [comment]
I tried both

**Comment by HarseTheef** [comment]
What event was occurring to bring the prices as low as they are in the provided screenshot?

**Comment by Edelor68** [comment]
None as far as I know. Could it just be the price reduction I get as engineer?

**Comment by jlsnow301** [comment]
This was fixed with #63039, sorry, premium products (like gloves) were not eligible for discount, therefore the incorrect price was shown.
