### ISSUE TITLE
Upgrading MediBorg's Hypospray twice breaks it

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#63031]
## Testmerges:
- [Revert "Fixes emptied shot glasses having the drinking glass filling icon."](https://www.github.com/tgstation/tgstation/pull/62975)

## Reproduction:
- Be a Mediborg;
- Get the expanded hypospray upgrade (the one where your hypospray gets advanced chems);
- Get it again.

If you do this, on your Robotact, you will see you have this same upgrade twice, but, besides that, when you try to select any advanced chemical (oxandrolone, mutadone, etc.), you don't get any selection message, but you are redirected to a mode that doesn't inject anything but gives you the injection message and doesn't seem to regenerate the "chemical" (I hope it makes sense). You can select any base hypospray chemical (such as Aiuri, Libital, etc.) and they'll work normally. Why is it even possible to insert the same upgrade in a borg twice?

**Comment by Sealed101** [comment]
fixed by https://github.com/tgstation/tgstation/pull/83116
