### ISSUE TITLE
No feedback or re-dos for "bad names" as mid-rounds

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#63040]
## Round ID:

Downstream

## Reproduction:
I rolled Sentient Virus. I attempted to name myself a typical Virologist produced virus name to blend in "SelfResp++/Noct++"

There was no feedback from choosing my name, which the game had rejected due to having funny characters in it. Instead I was named the default "Sentient Virus" and found and cured within 5 minutes. Had I known I had a default name I likely wouldn't even have had a chance to rename myself outside of an ahelp, since the prompt for a name doesn't return either.

I imagine this is the case for other nameable mid-round antags such as Space Dragon or Wizard, although I haven't tested it.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/4292f4388c037af678a800e24fcff7bc8b30f7b2/code/modules/antagonists/disease/disease_mob.dm#L163-L185

Looks like the code prevents you from setting your name to common diseases.  I'm not sure if this applies to custom named diseases though.  Also I think certain characters are sanitized by input.

**Comment by YakumoChen** [comment]
Intended behavior should be to throw an error in chat and force you to try again, I would think.

**Comment by SuperNovaa41** [comment]
> I imagine this is the case for other nameable mid-round antags such as Space Dragon or Wizard

it is yes, but there is a set of premade names that it randomly chooses from

**Comment by SuperNovaa41** [comment]
This is a feature report
