### ISSUE TITLE
Heretic invisible cloak and the items in its storage slot are visible in strip searches. Also, sprites are broken.

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#63044]
## Round ID:
[173582](https://scrubby.melonmesa.com/round/173582)

## Reproduction:

- Wear the heretic void cloak.
- Put your knife in your suit slot.
- Have someone else open your strip menu.
- They can see the purportedly invisible cloak as a broken sprite, the hood, and anything in the suit slot of the cloak.

- ALSO, they can see the void knife as a broken sprite on your character. Other knives aren't broken, but do show up on your character sprite. None of them show up on examine.

![image](https://user-images.githubusercontent.com/46474741/143195737-5464d380-fbad-4b62-9fb2-ef2933142156.png)
Notice the purple and black on the heretic's belt.

Someone used this to check if I was a heretic while I was breaking into the morgue back room, without any tells other than they were standing there silently looking at me. So yes, this is partially an ided report. But **this item is broken.**
The wiki says that the cloak is supposed to be invisible in strip searches. Also, the knives shouldn't show up if you're putting them inside of a supposedly invisible cloak- they don't show up on examine but they show up on the sprite and in strip searches.

Screenshot is from round [173585](https://scrubby.melonmesa.com/round/173585) where the admins helped me do some testing.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/7ca9018354d21a804fa3de28dd6c4777ebe381a0/code/modules/antagonists/eldritch_cult/eldritch_effects.dm#L139-L160

Looks like it just needs to use the `isopenturf` proc helper and it should be good.

**Comment by datorangebottle** [comment]
Did you post this in the wrong PR? I know I posted two heretic related PRs really close to eachother. This code doesn't seem relevant to the void cloak's many issues.

**Comment by timothymtorres** [comment]
> Did you post this in the wrong issue? I know I posted two heretic related issues really close to eachother. This code doesn't seem relevant to the void cloak's many problems.

Moved my post to the other issue.  Thanks for pointing it out.
