### ISSUE TITLE
Heretic influences can spawn above open space

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#63043]
Reporting client version: 514.1561

## Round ID:
[173582](https://scrubby.melonmesa.com/round/173582)

## Testmerges:
- [Tramstation Perma Genpop](https://www.github.com/tgstation/tgstation/pull/62966)
- [Fixing parallax plane above blackness ](https://www.github.com/tgstation/tgstation/pull/62902)

## Reproduction:
Start the game on icebox. Walk to the bar. See an influence above the bar stairs.
![image](https://user-images.githubusercontent.com/46474741/143188507-950e4081-5abc-45a1-bbb3-7bb2a3bbcdfb.png)
Thankfully this one happened to spawn in a reachable spot and wasn't a big issue, but what happens if one spawns in the air in the tram hallway on Tramstation, as an example?

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/7ca9018354d21a804fa3de28dd6c4777ebe381a0/code/modules/antagonists/eldritch_cult/eldritch_effects.dm#L144-L160

Looks like it just needs to use the `isopenturf` proc helper and it should be good.
