### ISSUE TITLE
Metalfoam-Grenades don't do what they are supposed to.

### ISSUE THREAD

**Issue by Edelor68** [tgstation/tgstation#63050]
## Reproduction:

Throw the grenade into a space that has been blown up --> It covers everything in walls and does nothing else.
It used to place metal foam flooring if the floor was missing and only placed walls where there used to be any.
If this was an intended change that I just didn't catch I'm going to be very sad.

**Comment by SuperNovaa41** [comment]
It always placed walls everywhere. As for the floors, it doesn't place any at all? it has to be a floor exposed to space

**Comment by Edelor68** [comment]
Yes, and it doesn't place any on floors exposed to space.

**Comment by SuperNovaa41** [comment]
![unknown](https://user-images.githubusercontent.com/16159590/143301209-8ad350d5-a1bc-47af-ae96-1ad3e39e43e0.png)

I think i see the issue. Metalfoam grenades don't fill in holes, they just leave foam literally everywhere. However, _smart metal foam_ fills in holes, and fills in holes in the walls.
