### ISSUE TITLE
Tram Security Bugs

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#63054]
Feel free to post any you find

![dreamseeker_6qvQ5QfguS](https://user-images.githubusercontent.com/37246588/143311653-17706b4e-a5fd-4443-aeff-fcf6cedee2f8.png)
rwall below external airlock in security office room
![dreamseeker_gsfK4VigjX](https://user-images.githubusercontent.com/37246588/143311782-04ea6277-a21c-431e-8e91-34250ab09eb8.png)
entrance doors aren't linked and don't close when both are open
![dreamseeker_MwVhNc2PhK](https://user-images.githubusercontent.com/37246588/143311839-90540b1d-b5ff-4936-9fef-8f2258b37d53.png)
plumbing pipe just chilling in perma bathroom?
![dreamseeker_y3coorvnAh](https://user-images.githubusercontent.com/37246588/143311872-3a1e3ce3-64dd-4042-bdad-1d59e236c35c.png)
no basketball in the court!

**Comment by SinfulBliss** [comment]
The power cables going into brig (on the right side) are disconnected shiftstart, which means brig has no power shiftstart until wires are placed to connect it. Definitely the most problematic of these bugs.
![tram brig power](https://user-images.githubusercontent.com/16496315/146637658-93463712-9eb3-4053-b693-068228308128.png)

**Comment by Mooshimi** [comment]
> The power cables going into brig (on the right side) are disconnected shiftstart, which means brig has no power shiftstart until wires are placed to connect it. Definitely the most problematic of these bugs. ![tram brig power](https://user-images.githubusercontent.com/16496315/146637658-93463712-9eb3-4053-b693-068228308128.png)

This is actually caused by misalligned ladders and wire hubs nearby, will pr in a sec.
