### ISSUE TITLE
Repairing a damaged hardsuit does not repair its helmet, leading to the helmet becoming unusable.

### ISSUE THREAD

**Issue by tf-4** [tgstation/tgstation#63056]
## Reproduction:

A hardsuit + helmet both get damaged to become "shredded", but repairing the hardsuit will ONLY repair the hardsuit - meaning the helmet is still shredded inside.
As you can't wear shredded clothing, obviously, the helmet can then no longer be toggled on, and there's no other way to access it to repair it making the hardsuit unusable.

Saw this happen on a blood-red hardsuit. Which was bad.

Relevant: `code/modules/clothing/clothing.dm` `ln 163: /obj/item/clothing/proc/repair(mob/user, params)`

**Comment by NanoCats** [comment]
Since when can hardsuits be shredded oh god oh fuck
