### ISSUE TITLE
Lavaland syndicate self destruct easy access issues

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#63057]
[Round ID]: # 173642

Pretty much the self destruct it way too easily accessible for miners to open up. One gibonite and the station goes boom, should be more in the middle on the station rather than having only one wall in the way for the miners to destroy a somewhat popular ghost spawner. The destruction that follows doesn't even really destroy much anyways. Leaves way too much loot for the miners to pick through rather than an actual total destruction a self destruct device should give. The wall doesn't even have a turret to keep the area safe and is a blind spot for the areas where the syndicate crew can't protect at all. As long as you have a boat it's pretty much just a free sniper and syndi gear spot for valid hunter miners.

**Comment by davethwave** [comment]
Thanks, was probably a mistake on my part for the round id. Though I do think that the self destruct should either be moved toward the center of the base or have some turret to protect it from miners. There's currently nothing people can do from preventing a miner to just place some gibonite down and destroy the whole base for some easy loot. I believe the base used to have more turrets but they agro'd the fauna and megafauna causing them to be removed. But they didn't change anything to make the base itself more secure in other ways.

**Comment by timothymtorres** [comment]
> This seems to be more of a feature request rather than an issue report.

Agreed.  

@davethwave I'd recommend you look at implementing this yourself with mapping or checking out the mapper discord channel if you need help.
