### ISSUE TITLE
Circuit guns start without firing pins

### ISSUE THREAD

**Issue by TheBonded** [tgstation/tgstation#63052]
## Reproduction:
1. Use circuits to create a medical scanner
2. Print a circuit gun and hook it up so the entity hit has it's health displayed
3. Realise the circuit gun comes with no firing pin and thus cannot be fired without recieving one from the HoS

**Comment by TheBonded** [comment]
@Fikou is the one who added them, so it's possible they always started without one, but I'm pretty sure they used to

**Comment by moocowswag** [comment]
The current "workaround" is to just not to screwdriver the shell, its apparently a redundant step for circuit gun shells and they can work without doing so.

**Comment by TheBonded** [comment]
> The current "workaround" is to just not screwdriver the gun shell, its apparently a redundant step for circuit gun shells and they can work without doing so.
> 
> Using a screwdriver to "complete" the shell instead probably just takes out whatever magic firing pin comes with it.
> 
> So in essence they DO start with a "firing pin" and work just fine in the state that they are in when originally printed, there is just little clarity in what using a screwdriver on it is actually doing.

Ah, so when it's initially created it doesn't require you to screwdrive it to assemble it? Which means I probably just removed the firing pin without thinking and assumed I'd assembled it. Makes sense, thanks for clarification

**Comment by TheBonded** [comment]
I'll mark this as cleanup flagged and I'll close it whenever I remember tomorrow, just in case anyone else has any relevant information

**Comment by TheBonded** [comment]
I have bad memory
