### ISSUE TITLE
Safety Moth Posters are Black and Purple

### ISSUE THREAD

**Issue by DRD21** [tgstation/tgstation#63066]
Reporting client version: 514.1568

## Round ID:
[173668](https://scrubby.melonmesa.com/round/173668)

## Reproduction:
Look at a safety moth poster
![image](https://user-images.githubusercontent.com/95049670/143490867-868b900a-22bb-49ac-96c6-136b32192182.png)

**Comment by SuperNovaa41** [comment]
Good

**Comment by Mothblocks** [comment]
Server hasn't been updated https://github.com/tgstation/tgstation/pull/63037
