### ISSUE TITLE
Phylactery does not respawn you when playing as a wizard

### ISSUE THREAD

**Issue by DoggotheSpessman** [tgstation/tgstation#63065]
## Round ID:
[173666](https://scrubby.melonmesa.com/round/173666)
## Reproduction:
Simply spawn in as a wizard, bind yourself to an item using bind soul, and kill yourself, for some reason on round 173666 it did not respawn the wizard after dying.

**Comment by TheBonded** [comment]
duplicate of https://github.com/tgstation/tgstation/issues/62507

**Comment by Mothblocks** [comment]
@TheBonded please dont leave duplicates up 😛

**Comment by TheBonded** [comment]
> @TheBonded please dont leave duplicates up 😛

sorry, forgot I had the power to close prs
