### ISSUE TITLE
Pride mirror race change is broken

### ISSUE THREAD

**Issue by Spaghetterr** [tgstation/tgstation#63064]
Reporting client version: 514.1568

## Round ID:
[173666](https://scrubby.melonmesa.com/round/173666)

## Reproduction:

Pride mirror does not work for changing race anymore and has been for a while. After choosing the race it just closes the prompt and does nothing. The other options seems to still work properly.

**Comment by TheBonded** [comment]
originally documented in https://github.com/tgstation/tgstation/issues/62691, will be fixed by https://github.com/tgstation/tgstation/pull/62696.
