### ISSUE TITLE
Twisted construction instantly converts AI shells

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#63060]
## Testmerges:

#62132 

## Reproduction:

Have AI shell
Get slapped by a cultist with twisted construction
Sigh as the shell becomes an empty construct

**Comment by timothymtorres** [comment]
This is from the wiki:

> Twisted Construction: A sinister spell used to convert:
> Plasteel into Runed Metal.
> 50 Metal into a Construct Shell.
> Cyborgs directly into Constructs.
> Cyborg shells into construct shells.

If cyborg shells get converted to construct shells, I think it makes sense that an AI shell would as well.

**Comment by SuperNovaa41** [comment]
yeah what, @carshalash did you mean something more specific? otherwise this is just normal behaviour

**Comment by carshalash** [comment]
> yeah what, @carshalash did you mean something more specific? otherwise this is just normal behaviour

It's an instant cast when used on AI shells, even when they're currently being used by the AI. When it is used on a normal cyborg it will have a cast time, normally as long as the average cyborg stun. This BUG bypasses the need to immobilize the 'borg' at all and can turn it into an empty cult construct.
