### ISSUE TITLE
Tend wounds surgery missing.

### ISSUE THREAD

**Issue by TattoMoon** [tgstation/tgstation#63077]
## Reproduction: 

![unknown (7)](https://user-images.githubusercontent.com/94944115/143542328-05b36056-9009-40d9-a23e-6e9201f63aed.png)
Attempting to open the surgeries tab while a patient is off of a surgical table, does not display tend wounds surgeries. Once a patient is on a surgical table with upgraded tend wounds surgeries, it will allow it then. The victim had not been operated on recently, and its most likely due to the addition of the dissection surgery.

**Comment by Mothblocks** [comment]
My money is me replacing `return .` with just `return FALSE`

![image](https://user-images.githubusercontent.com/35135081/143550306-8078be52-2aad-4faa-9e83-91e6ff138c4b.png)

**Comment by Mothblocks** [comment]
@LemonInTheDark The first regression is different (and worse), and already had a unit test 😄

**Comment by Mothblocks** [comment]
That being said, I'm a little surprised if that's the case, since it would likely have broken the other surgeries as well. Looking into it.

**Comment by LemonInTheDark** [comment]
> @LemonInTheDark The first regression is different (and worse), and already had a unit test 😄

😭

**Comment by Mothblocks** [comment]
I was already adding another 💃
