### ISSUE TITLE
Gradiant hair dye can work at range

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#63075]
Reporting client version: 514.1566

## Round ID:
[173697](https://scrubby.melonmesa.com/round/173697)

## Testmerges:
- [Tramstation Perma Genpop](https://www.github.com/tgstation/tgstation/pull/62966)
- [Fixing parallax plane above blackness ](https://www.github.com/tgstation/tgstation/pull/62902)

## Reproduction:
1. Click on someone with hair dye
2. Toss the hair dye across the room
3. Walk into a different room than the person getting their hair dyed
4. Choose what style/color to dye their hair
5. Hold still and hope your target also holds still

**Comment by SuperNovaa41** [comment]
fixed https://github.com/tgstation/tgstation/pull/62996
