### ISSUE TITLE
The mood events from the icebox plasma facility ruins don't have working spans

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63093]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/143666047-ab252f72-6866-4f74-b8e7-a379a0399f77.png)

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/89c08256313435579439462348632353db0ce3cc/code/game/area/areas/ruins/icemoon.dm#L25-L30
