### ISSUE TITLE
Shoving bugs - Diagonal shoving, fireman carrying/piggyback riding shoves

### ISSUE THREAD

**Issue by bdudy** [tgstation/tgstation#63096]
## Reproduction:
Video: https://streamable.com/ilo0ri
It's no longer possible to shove people into corners, or diagonally into other people. 
Shoving someone who is fireman carrying/giving a piggyback ride will immediately knock them down and onto their side.

**Comment by LemonInTheDark** [comment]
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by LemonInTheDark** [comment]
@Mothblocks you were right

**Comment by Mothblocks** [comment]
You'll have to be more specific

**Comment by LemonInTheDark** [comment]
You were just right ok?
