### ISSUE TITLE
Pref for sentience potion spawn is missing

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#63092]
Reporting client version: 514.1568

## Round ID:
[173747](https://scrubby.melonmesa.com/round/173747)

## Testmerges:
- [Fixes tend wounds being inacessible without an operating table + computer](https://www.github.com/tgstation/tgstation/pull/63079)

## Reproduction:
Had someone trying to sentience potion mobs, noticed others (and myself) weren't getting popups for them.
I remember it was a pref in the old prefs menu, there's no sentience potion spawn pref in the new prefs menu.

**Comment by dragomagol** [comment]
cc @Mothblocks

**Comment by NotZang** [comment]
I beg, someone. Please fix this. And any other preferences that have a similar issue.

**Comment by Mothblocks** [comment]
#69569
