### ISSUE TITLE
it's not possible to put pai into newly created bots

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#63101]
observed over 2 rounds

for one thing, there's no button in the interface to control the pai lock at all

there's a little thing that says "no pai inserted" but clicking it does nothing

We WERE able to the pai into exactly inspector johnson, once, but all other attempts to get them into bots have failed. Maintenance panel open or shut, bot off or on, airplane mode, you name it, we tried it.

**Comment by timothymtorres** [comment]
I believe pAIs are disabled from being placed into beepsky bots due to balance.  All the other bots should be fair game.  Which ones did you try?

**Comment by newfren** [comment]
medibots, both white and red, cleanbots, floorbots, firebots. The red and white medibots I built, the cleanbot/floorbot/firebot hates spawned in.

**Comment by Summoners** [comment]
Yep checked it myself it prevents pAIs from entering _any_ bot.
