### ISSUE TITLE
Every Tending Wounds Surgery possible is now displayed

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#63109]
## Round ID:
[173787](https://scrubby.melonmesa.com/round/173787)

## Reproduction:
- Put someone on a surgery table with an updated operating console;
- Use drapes on their chest;
- Realize you have multiple possibilities for 'Tend Wounds', including the least optimal ones.

Before, when you started doing surgery on someone who was on a surgery table with better Tend Wounds surgeries, only the most optimal one(s) would show up. Now, all of them do.

![image](https://user-images.githubusercontent.com/42555530/143720839-24ecef28-2a3b-45d7-ae7d-4119ca253b72.png)

**Comment by Mothblocks** [comment]
ghbahbahahah

**Comment by Mothblocks** [comment]
yeah probably

**Comment by Mothblocks** [comment]
oh wait this is less funny than i was hoping for, you still need to research the surgeries right
