### ISSUE TITLE
Drones can red alert

### ISSUE THREAD

**Issue by vincentiusvin** [tgstation/tgstation#63119]
## Round ID: [173820](https://scrubby.melonmesa.com/round/173820)
Master commit: e326e492dc1446baed06726e8f68307c94e82610

## Reproduction:
1) Play drone
2) Walk to the authentication machine
![image](https://user-images.githubusercontent.com/54709710/143740582-0daafcbd-3797-4481-956c-0e596f582ae2.png)

**Comment by NanoCats** [comment]
Question, can the drone also authorize the BSA? I assume if it can auth red alert it can.

**Comment by Jolly-66** [comment]
Drone pal, we need you to red alert for us.

What the drone heara: Xi the zay be ke

**Comment by vincentiusvin** [comment]
> Question, can the drone also authorize the BSA? I assume if it can auth red alert it can.

Yes currently but a fix is on the way
