### ISSUE TITLE
Mulebots & Bots hacking & control panels missing/broken.

### ISSUE THREAD

**Issue by Summoners** [tgstation/tgstation#63133]
## Round ID:
[Round ID]: 173866

## Testmerges:
#61422, #63098 

## Reproduction:

For Mulebots:
1. Find mulebot.
2. Unlock mulebot.
3. Screwdriver mulebot.
4. Use a wirecutter or multitool on the mulebot
5. Nothing happens. (Except sometimes the main panel appears and it seems to be possibly overlapping)

For Bots:
1. Find and unlock bot.
2. Stick a pAI in them.
3. Turn them off and on repeatly.
4. Congratulations, they are forever turned off as the control panel will stop updating. (This also works on mulebots).

**Comment by Summoners** [comment]
The issues might be totally unrelated but I have a VERY high suspicion that they are both related to #62748

**Comment by JohnFulpWillard** [comment]
Looking into this now.
