### ISSUE TITLE
RCDs with the silo link upgrade can randomly brick themselves

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#63149]
## Testmerges:

NaN

## Reproduction:

1. Create RCD
2. Add Silo link upgrade (and the others, just in case it's related!)
3. Link to silo
4. Something weird happens and the RCD will say "low ammo light!" when there is either material in itself or the silo, I think it has something to do with the silo being low, this persists even if the RCD is full and you disable the silo uplink
5. You can't do ANYTHING with this RCD

Also worth noting I've ahelped over this in the past and had the admin turn up only for the god damn thing to start working again????

**Comment by timothymtorres** [comment]
@NanoCats you made the same bug report twice?!  Have you been drinking son

**Comment by NanoCats** [comment]
> @NanoCats you made the same bug report twice?! Have you been drinking son

Yes but I don't see how it's relevant sorry

**Comment by SyncIt21** [comment]
This is no longer an issue and was resolved somewhere, sometime. Should be closed now

**Comment by dragomagol** [comment]
https://github.com/tgstation/tgstation/pull/73719#issuecomment-1449800443
