### ISSUE TITLE
Premade Viruses crash the PanD.E.M.I.C

### ISSUE THREAD

**Issue by Tanden22** [tgstation/tgstation#63155]
Reporting client version: 514.1557

## Round ID:
[173918](https://scrubby.melonmesa.com/round/173918)

## Testmerges:
- [Families Bugfixes + Tweaks: Even Distribution of Leaders, Fixes HoS-Family-Leaders, Adds Admin Tool to make Leaders](https://www.github.com/tgstation/tgstation/pull/63115)

## Reproduction:
-buy a virus crate
-put a premade virus (Beesease, Magnitis, etc.) into the PanD.E.M.I.C
-bluescreen

**Comment by ATH1909** [comment]
what happens if a blood sample that has both a premade virus and a custom virus in it is put into the pandemic?

**Comment by Tanden22** [comment]
@ATH1909 I can't seem to get my local test server updated, or I'd try that. Git keeps giving me a version from September 22nd

**Comment by Tanden22** [comment]
@ATH1909 it only shows the custom one.

**Comment by jlsnow301** [comment]
will look into this shortly

**Comment by timothymtorres** [comment]
Seems that the PR attempt to fix this didn't work.  Reopening this issue for whoever else wants to try and fix it.

**Comment by timothymtorres** [comment]
Correction - after some hunting the PR that fixed it was never merged into the server when the new issue was opened.  I'm closing this since the issue was tested on a local machine and it was reported as working.
