### ISSUE TITLE
Red Jumpsuit appears white

### ISSUE THREAD

**Issue by Tanden22** [tgstation/tgstation#63150]
Reporting client version: 514.1557

## Round ID:
[173908](https://scrubby.melonmesa.com/round/173908)

## Testmerges:
- [Families Bugfixes + Tweaks: Even Distribution of Leaders, Fixes HoS-Family-Leaders, Adds Admin Tool to make Leaders](https://www.github.com/tgstation/tgstation/pull/63115)

## Reproduction:
-wear/spawn in with a red jumpsuit
-notice it's pure white while equipped
note: alt-clikcing it shows it as red, but having it up shows it as white
[https://imgur.com/a/vbPrzB0](url)

**Comment by TheBonded** [comment]
Seems like https://github.com/tgstation/tgstation/issues/59297 and https://github.com/tgstation/tgstation/issues/61012 are coming back. @Shroopy fixed this a while back, maybe something more recent broke that?

**Comment by Sealed101** [comment]
some sort of greyscale bug that was hopefully fixed
https://github.com/tgstation/tgstation/pull/76384 perhaps? or some underlying greyscale _enrobustment_(patent pending) PR
