### ISSUE TITLE
unlike the other roundstart races, ethereals lack a corresponding mutation toxin

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#63186]
very sad!

**Comment by MrMelbert** [comment]
https://github.com/tgstation/tgstation/pull/50720#issuecomment-620252496
![image](https://user-images.githubusercontent.com/51863163/144165761-f913cab5-5d41-45c0-b865-2a8b7309d217.png)

**Comment by SuperNovaa41** [comment]
Feature request also what mr melbert said
