### ISSUE TITLE
Bedsheets don't orientate themselves correctly

### ISSUE THREAD

**Issue by BoneSeer** [tgstation/tgstation#63194]
Reporting client version: 514.1557

## Round ID:
[174014](https://scrubby.melonmesa.com/round/174014)

## Testmerges:
- [Fixes tend wounds being inacessible without an operating table + computer](https://www.github.com/tgstation/tgstation/pull/63079)
- [Mouse Entered Profiling](https://www.github.com/tgstation/tgstation/pull/63098)

## Reproduction:
I made a bed and put a sheet on it but the sheet is covering the pillow and not covering the foot of the bed so if you lay in bed and put a sheet on your feet get cold and you can't breathe. 
![image](https://user-images.githubusercontent.com/87043270/144312338-b0c1f044-3d7d-4123-bf1a-a24639e8900a.png)

![image](https://user-images.githubusercontent.com/87043270/144312373-74d5d154-2658-48bd-b9d0-52ceaec69f57.png)

**Comment by Mooshimi** [comment]
This is solved by throwing the bedsheet at the bed or ground, it lands in different directions depending on where you're facing.

**Comment by TheBonded** [comment]
fixed by some pr or another I dont know the exact code
