### ISSUE TITLE
Random anomalies don't spawn?

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#63191]
on manuel?

maybe?

I haven't seen one in the last week or so and maybe even further back than that. thgvr seems to think random vines don't spawn either.

**Comment by thgvr** [comment]
purely anecdotal but I play a massive amount and have not seen a single anomaly in months

**Comment by Sealed101** [comment]
havent seen either vines or anomalies spawn in the last week on terry either

**Comment by JohnFulpWillard** [comment]
I havent seen an anomaly spawn in at least the last month on fulp, either.

**Comment by TheBonded** [comment]
Now that you mention it, it has been a while since I've seen any anomolies, vines, or greytide door virus events.

**Comment by Korusho** [comment]
It has been a very long time since I've seen the grey tide virus.. or vines.. or anomalies. They might have been accidentally disabled. THOUGH a bluespace translocation event occurred recently and THAT I hadn't seen in a very long time.

**Comment by dragomagol** [comment]
Could have been admin triggered, I think I triggered a bluespace anomaly on Manuel the other week.

**Comment by Pickle-Coding** [comment]
Also haven't seen wormholes for a while.
