### ISSUE TITLE
Outgoing messages to other stations don't seem to be subject to IC chat filters

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#63206]
Reporting client version: 514.1561

## Round ID:
[174046](https://scrubby.melonmesa.com/round/174046)

## Reproduction:

IC chat filters don't seem to be applied to messages sent to other servers. Seems like an oversight. Probably applies to other types of announcement as well.

I censored the image so I don't get banned by GitHub for the slur but you can probably guess what it is. This was sent on [Terry](https://scrubby.melonmesa.com/round/174046/files?file=game.txt#undefined-3313).

![](https://i.imgur.com/5KVGoAy.png)

**Comment by SuperNovaa41** [comment]
I don't think the captains announcement does either, which should probably be included

**Comment by ATH1909** [comment]
terry moment

**Comment by Hafahya** [comment]
>Its a complaint about cooders
>Yeah lets fix it being able to be said
Coder moment

**Comment by cacogen** [comment]
i don't think terry players should get to say it
