### ISSUE TITLE
Z-Level transitions blend when viewed from a zlevel above (icebox).

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#63202]
This really is only noticeable on icebox since it has 3 z levels. If you're looking down from a third level, levels 2 and one will appear to be on the same level, until you fall down both at the same time of course.
Observe the chaplain mass driver hole:
(This is top level to bottom)
![dreamseeker_fPj3x78p9b](https://user-images.githubusercontent.com/33107541/144345336-f5f8a4a5-c7cc-4e5d-9309-0bc625bbecb1.png)
![dreamseeker_FeqRr21DV0](https://user-images.githubusercontent.com/33107541/144345354-29ac0fd2-368b-442f-acbd-af29ff5d3e90.png)
![dreamseeker_Z7BHBWCssN](https://user-images.githubusercontent.com/33107541/144345377-dfb180d7-584d-4f41-b539-bf6e9e0b9d11.png)

**Comment by LemonInTheDark** [comment]
There's very few good ways to fix this

**Comment by LemonInTheDark** [comment]
Other noted issue, visible here.
lighting is yorked when viewing through mutliz

**Comment by LemonInTheDark** [comment]
Closed by #69115
