### ISSUE TITLE
Simple robots cannot path around railings good

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63228]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/144581878-1faa3a5e-e4a5-45e9-9050-37f2cf67072f.png)

Simple robots, such as beepsky or medbots, when patrolling between points on a station, will get trapped by railings, unable to path adjacent or past them (even if they're completely able to do so). This is evident in Deltastation's Service.

**Comment by LemonInTheDark** [comment]
JPS moment

**Comment by Sealed101** [comment]
a common occurence in the undertram

**Comment by NanoCats** [comment]
Simple bots are a bug goldmine,
