### ISSUE TITLE
Peacekeeper cyborg's Hyperkinetic Dampening projector doesn't project a (visible?) energy field

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#63223]
Peacekeepers are supposed to be able to summon a big blue square field that weakens projectiles that pass through it or something like that, but activating the projector no longer seems to activate anything, nothing visible at least. Been having this issue over a number of rounds.

![image](https://user-images.githubusercontent.com/33107541/144536665-efe5e09b-02a9-4377-be5b-4836b134686a.png)
![dreamseeker_GAeoWoVBvS](https://user-images.githubusercontent.com/33107541/144536679-e0e67b9d-7d91-449d-a50d-c0f486f18711.png)
(activated, no field)

**Comment by Sealed101** [comment]
seems to be working fine, the effect was reworked in #67131
![image](https://user-images.githubusercontent.com/75863639/223841063-83a64bbc-b4d0-4c85-957d-5ae594fe1b57.png)
