### ISSUE TITLE
Random species in character preferences doesn't work.

### ISSUE THREAD

**Issue by Traysoul** [tgstation/tgstation#63236]
Reporting client version: 514.1566
## Round ID:
[174128](https://scrubby.melonmesa.com/round/174128)

## Reproduction:
Click "Always randomize" on Random species and join the round.

**Comment by Mooshimi** [comment]
Happen to know if this worked before the prefs merge?

**Comment by Mothblocks** [comment]
It works but, I'm assuming it's the same bug where sometimes prefs get to look like this that I have to fix sometimes
![image](https://user-images.githubusercontent.com/35135081/144965442-113c5d8a-08e2-4d98-b451-af6a4af049a5.png)

**Comment by Mothblocks** [comment]
Least it worked when I made it 🤷

**Comment by JohnFulpWillard** [comment]
Is this an issue or not?

**Comment by Mothblocks** [comment]
I fixed that thing I'm talking about I'm pretty sure so I'll close unless this happens to someone else
