### ISSUE TITLE
Delta Station Xenobio Kill Room Vents have a really long name

### ISSUE THREAD

**Issue by Tanden22** [tgstation/tgstation#63234]
Reporting client version: 514.1557

## Round ID:
[174129](https://scrubby.melonmesa.com/round/174129)

## Testmerges:
- [Families Bugfixes + Tweaks: Even Distribution of Leaders, Fixes HoS-Family-Leaders, Adds Admin Tool to make Leaders](https://www.github.com/tgstation/tgstation/pull/63115)

## Reproduction:
-Go to xenobio
-examine the vents in the kill room
-note that they say "That's Xenobiology Lab Xenobiology Lab Xenobiology Lab Xenobiology Lab Xenobiology Lab Xenobiology Lab Xenobiology Lab Xenobiology Lab Xenobiology Lab server vent YSTAd YSTAd YSTAd YSTAd YSTAd YSTAd YSTAd YSTAd YSTAd."

**Comment by RandomGamer123** [comment]
Fixed by #63061 which has been merged but the servers have not deployed it yet
