### ISSUE TITLE
You can hook food onto an IV drop

### ISSUE THREAD

**Issue by JohnFulpWillard** [tgstation/tgstation#63249]
## Reproduction:

Take some food (I used a lollipop and a cross bun in my case) and click an IV drip with it.
You can attach it onto you and it will transfer the reagents from the food into you.

**Comment by MrMelbert** [comment]
#58354 Newfriends outing themselves

**Comment by JohnFulpWillard** [comment]
> #58354 Newfriends outing themselves

why
