### ISSUE TITLE
Tram's maint is broken yet again

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#63256]
Screenies taken with me not moving at all except up and down the z-level

![image](https://user-images.githubusercontent.com/75863639/144722132-31daeef4-971c-4063-aa66-d5d4c2a13a57.png)

![image](https://user-images.githubusercontent.com/75863639/144722152-9223bbc9-4470-4389-92a7-f895c52efc84.png)

**Comment by Potato-Masher** [comment]
I assume that's just the zlevels not lining up correctly?

**Comment by Sealed101** [comment]
no that is just brig maint and its recent changes that made a woopsie other ladders are fine

**Comment by MMMiracles** [comment]
i'd pr a fix for it but there's another pr up already splitting the map into 2 files and i'd rather not deal with that until afterwards

**Comment by Mooshimi** [comment]
> 

I know you say this but I'm going to fix this since it's actually breaking the power net for security if you notice. it's the only in line coming up from engi
