### ISSUE TITLE
Simple robot control locks can be disabled without the proper ID access

### ISSUE THREAD

**Issue by Gristlebee** [tgstation/tgstation#63259]
Reporting client version: 514.1556

## Round ID:
[174195](https://scrubby.melonmesa.com/round/174195)

## Testmerges:
- [Families Bugfixes + Tweaks: Even Distribution of Leaders, Fixes HoS-Family-Leaders, Adds Admin Tool to make Leaders](https://www.github.com/tgstation/tgstation/pull/63115)

## Reproduction:
Find a simple bot(Cleanbot, secbot, etc).
Click on it and open the settings panel.
Disable the controls lock without the proper ID.

**Comment by TheBonded** [comment]
(possibly) relavent code:
https://github.com/tgstation/tgstation/blob/aa326101d6207ad5ce3e65cef2a173c539f143fa/tgui/packages/tgui/interfaces/SimpleBot.tsx#L61-L80
looks like it has no check for access here, it just unlocks/locks it when you click the button.

**Comment by NanoCats** [comment]
aw man I actually kinda liked this, robots having access requirements is actually a significant pain sometimes, like if I put a medibot together as a clown. The only one that should really need one is like, beepsky lol

**Comment by jlsnow301** [comment]
> (possibly) relavent code:
> 
> https://github.com/tgstation/tgstation/blob/aa326101d6207ad5ce3e65cef2a173c539f143fa/tgui/packages/tgui/interfaces/SimpleBot.tsx#L61-L80
> 
> looks like it has no check for access here, it just unlocks/locks it when you click the button.

This is handled (or was) in backend bot.dm's ui_act, however if a fix is not done I can also add a check for access
@JohnFulpWillard is working on these also, see #62671
