### ISSUE TITLE
Food crafting reagent conservation is not mentioned on the wiki.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#63252]
Reporting client version: 514.1566

## Round ID:
[174170](https://scrubby.melonmesa.com/round/174170)

## Testmerges:
- [Fixes Massive Radio Overtime, Implements a Spatial Grid System for Faster Searching Over Areas](https://www.github.com/tgstation/tgstation/pull/61422)

## Reproduction:
1. Bake a plain bread (10u Nutriment)
2. Bake three banana-nut breads (20u Nutriment + 20u Banana Juice) x3
3. Insert the banana-nut breads into the plain bread (Theoretically 70u Nutriment + 60u Banana Juice)
4. Grind the stuffed bread. Receive ~80u total reagents including:
  - 26.35u Nutriment
  - 23.21 Banana JReporting client version: 514.1566

## Round ID:
[174170](https://scrubby.melonmesa.com/round/174170)

## Testmerges:
- [Fixes Massive Radio Overtime, Implements a Spatial Grid System for Faster Searching Over Areas](https://www.github.com/tgstation/tgstation/pull/61422)

## Reproduction:
1. Bake a banana bread. These are listed as 20u Nutriment + 20u Banana Juice on the wiki.
2. Grind the banana bread. Receive,
  - 20u Nutriment
  - 18u Banana Juice
  - 3.15u Protein
  - 2.55u Vitamin
  - 3u Egg Yolk
  - 3u Egg White
  - 4u Potassium
  - 5u Milk

It appears that the crafting recipe for banana-nut bread is transferring the reagents from the ingredients to the final product. While this is usually desired it is not mentioned on the wiki. As a result, it should either be added to the wiki or made somewhat more intelligent. (Baked goods should probably selectively ignore some ingredient reagents so we don't end up with raw egg in baked breads for example.)

**Comment by SuperNovaa41** [comment]
This isn't the wiki codebase
