### ISSUE TITLE
Head revolutionary antag gain message: "You are Head Revolutionary."

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#63257]
Round ID: [174091](https://scrubby.melonmesa.com/round/174091)

![image](https://user-images.githubusercontent.com/33107541/144726563-0c566115-64ca-4105-87a4-271ee0001f8e.png)

**Comment by MrMelbert** [comment]
This actually goes for most antag gain messages now -

Traitor says `You are Traitor.`, for example.
