### ISSUE TITLE
You can use an RCD to endlessly build "floors" on lattices

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#63260]
Reporting client version: 514.1557

## Round ID:
[174202](https://scrubby.melonmesa.com/round/174202)

## Testmerges:
- [Families Bugfixes + Tweaks: Even Distribution of Leaders, Fixes HoS-Family-Leaders, Adds Admin Tool to make Leaders](https://www.github.com/tgstation/tgstation/pull/63115)

## Reproduction:

1. Construct lattice
2. Acquire RCD
3. attempt to build a floor with the rcd by clicking the lattice's metal and NOT the gaps in it
4. it says "You build a floor" even if you didn't really 
5. it just wastes the materials and nothing happens

If anyone cares about my feedback I feel like the construction of a floor should be two stage, you click empty space and it makes a very fast crawlacross to make the latice, and automatically starts a second stage to actually build the floor (still very fast, only slightly slower than the way it is now)

**Comment by dragomagol** [comment]
https://github.com/tgstation/tgstation/pull/73719#issuecomment-1449800443
