### ISSUE TITLE
Custom say Emoting through holopads and binary doesn't work

### ISSUE THREAD

**Issue by Sightld2** [tgstation/tgstation#63273]
## Round ID:[174283](https://scrubby.melonmesa.com/round/174283)

Whenever you try and speak a custom say emote over a holopad or binary comms, instead your text is replaced with "An interesting thing to say"

## Reproduction:
Join the game as an Ai. Say "tests the emote feature*" over binary and/or over a holopad.

**Comment by SuperNovaa41** [comment]
Duplicate of #https://github.com/tgstation/tgstation/issues/62666
