### ISSUE TITLE
Mesons didn't light up turfs

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#63286]
## Testmerges:
The following pull requests are currently test merged:
#63115: 'Families Bugfixes + Tweaks: Even Distribution of Leaders, Fixes HoS-Family-Leaders, Adds Admin Tool to make Leaders' by Iamgoofball at commit fa4714dacc

## Reproduction:
![image](https://user-images.githubusercontent.com/12635164/144998397-139f11bc-c6bc-46e7-b917-c232baa895cb.png)
I should be able to see turfs here if not what's on them but it's entirely dark. Weird!

**Comment by newfren** [comment]
this fixed itself later in the round! very weird

**Comment by LemonInTheDark** [comment]
![image](https://user-images.githubusercontent.com/58055496/145165708-bb4fab5a-3ea1-45c0-b4be-9d89906f0f6e.png)

**Comment by LemonInTheDark** [comment]
![image](https://user-images.githubusercontent.com/58055496/145165846-394a4d60-dd75-44d2-9207-d5b1ffd65efa.png)
Tint code makes the assumption that all things in the mask slot are masks. It is wrong

**Comment by Sealed101** [comment]
this was fixed at some point by a tint refactor or somesuch, yeah?
