### ISSUE TITLE
Bronze Suit/Hat has very strange damage resistances

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#63280]
## Testmerges:
The following pull requests are currently test merged:
#63115: 'Families Bugfixes + Tweaks: Even Distribution of Leaders, Fixes HoS-Family-Leaders, Adds Admin Tool to make Leaders' by Iamgoofball at commit fa4714dacc

## Reproduction:
https://puu.sh/IuoNX/ed5c414e20.png
examine the bronze suit or hat
click the tag that explains its armour
it has explosive I and melee I (fine) but also just "energy" and "laser"
why

**Comment by SuperNovaa41** [comment]
it's because it has negative protection values for those
