### ISSUE TITLE
Infinite Super Melatonin injections from limited chemicals

### ISSUE THREAD

**Issue by CinzaFalso** [tgstation/tgstation#63284]
## Round ID:
[174331](https://scrubby.melonmesa.com/round/174331)

## Reproduction:
I put up 5u Super Melatonin on a normal 15u syringe and injected myself with it, after the injection, which was successful, the 5u super melatonin remained on the syringe while I had 5u on my system. I also tested a 15u injection, the problem remained, the syringe was still full and I got 15u of Super Melatonin on my system

**Comment by MrMelbert** [comment]
This may be a bug with syringes in general instead of just Super Melatonin.

**Comment by SuperNovaa41** [comment]
Duplicate of https://github.com/tgstation/tgstation/issues/63301
the other one has a better name
