### ISSUE TITLE
PDA Bomb Loggin is Confusing

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63281]
## Round ID:
[174325](https://scrubby.melonmesa.com/round/174325)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/144945492-16c7891b-7e9f-4429-b23f-1a543f729d01.png)

An antag sends a PDA bomb, and a non-antag responds to it, and triggers the PDA bomb. The resulting log says the PDA bomb was "triggered by a non-antagonist", which leads you to believe a non-antagonist *sent* the bomb, when in reality a non-antagonist was *hit* by the bomb.

**Comment by Razharas** [comment]
pda bombing is a horrible horrible code which will hopefully be removed

**Comment by JohnFulpWillard** [comment]
I've seen this as well and it confused me the first time I saw it, I wish PDA's would be killed already.

**Comment by JohnFulpWillard** [comment]
Actually now that I think about it, this is probably consistency issue.

**Comment by ShizCalev** [comment]
@Ghommie added via #62494

**Comment by Ghommie** [comment]
uh, i'll fix that asap.
