### ISSUE TITLE
Cant choose a job, just like in real life-

### ISSUE THREAD

**Issue by Lukasaurus8** [tgstation/tgstation#63298]
Reporting client version: 514.1571

## Round ID:
[174373](https://scrubby.melonmesa.com/round/174373)

## Reproduction:
![image](https://user-images.githubusercontent.com/95721787/145113577-1c80a936-a04f-4b61-9de9-f9e2273caf1d.png)
it seems that anytime i adtempt to boot up the job menu i get this wonderful middle finger from nanotrans- 
in more seriousness it seems to just be a issue with my setup, but i might as well go here beacuse i tried rebooting and that didnt work so yeah, i apologize if this is really inconcequnsual (i cant spell) but i might as well ask here for some help, cant wait to found out if im a dumbass or not~

**Comment by Lukasaurus8** [comment]
to rub it in even further, it now works now that a game has started

**Comment by Mothblocks** [comment]
Clear your cache, you might have the old one cached, and it's expecting data that has since been removed from the server.

**Comment by jlsnow301** [comment]
Marking for cleanup due to issue inactivity & inability to reproduce
