### ISSUE TITLE
Department Order consoles and department budget orders through tablets are unable to order gas canisters.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#63299]
Observed over multiple rounds.

Attempting to order a gas canister with the engineering order console (probably including any other console that can order gas canisters) simply results in the console saying "Something went wrong!" Nothing further happens. All other items can be ordered without issue.

Attempting to order a gas canister from the NT IRN tablet program with a head of staff ID inserted to use the department budget (for example the Chief Engineer's card) will result in nothing happening. No canister order request will show up in the tab.

The unifying issue seems to be that gas canisters don't like being ordered in locked crates, as normally I don't think they come off the cargo shuttle in normal metal crates, but rather temporary wooden boxes that are pryed open.

**Comment by newfren** [comment]
I have successfully ordered firefighting foam through the order console in engineering which comes in the same sort of box, although there was no clue as to who ordered it on the box itself.

**Comment by SuperNovaa41** [comment]
cc @tralezab i think this is you

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/62829
