### ISSUE TITLE
10 Gorilla-related Compilation Errors (/mob/living/simple_animal/hostile/gorilla missing?)

### ISSUE THREAD

**Issue by Redtrogdor** [tgstation/tgstation#63297]
## Round ID:
None (compile error)

## Testmerges:
Did not occur during a round. Checked the pull request tab, and I could not find any PR mentioning a removal of gorillas as simple_animals.

## Reproduction:

0. BYOND version is 514.1571, codebase version is most recent at time of writing (12/7/2021 1:19PM PST)
1. Open tgstation.dme in DreamMaker
2. Receive several warning pop-ups stating that /mob/living/simple_animal/hostile/gorilla does not exist and will be removed
3. Close DreamMaker and run BUILD.cmd
4. Close the command prompt window after receiving the following 10 errors:

```
code\datums\holocall.dm:374:error: /mob/living/simple_animal/hostile/gorilla: undefined type path
code\datums\memory\memory.dm:59:error: /mob/living/simple_animal/hostile/gorilla: undefined type path
code\modules\mob\living\living.dm:1285:error: /mob/living/simple_animal/hostile/gorilla: undefined type path
code\game\objects\items\food\meat.dm:435:error: /mob/living/simple_animal/hostile/gorilla: undefined type path
code\modules\mob\transform_procs.dm:285:error: new_gorilla.set_combat_mode: undefined type: new_gorilla.set_combat_mode
code\modules\mob\transform_procs.dm:287:error: new_gorilla: undefined type: new_gorilla
code\modules\mob\transform_procs.dm:289:error: new_gorilla.key: undefined type: new_gorilla.key
code\modules\mob\transform_procs.dm:290:error: new_gorilla: undefined type: new_gorilla
code\modules\mob\transform_procs.dm:291:error: new_gorilla: undefined type: new_gorilla
code\modules\mob\transform_procs.dm:284:error: new_gorilla: unknown variable type
tgstation.m.dmb - 10 errors, 0 warnings (12/7/21 1:06 pm)
```
Apologies for any issues with my formatting, this is my first time opening an issue for tgstation

**Comment by timothymtorres** [comment]
![image](https://user-images.githubusercontent.com/5195984/145114269-dcc691a7-a942-4ebb-915a-7be0f3819061.png)

Make sure the gorilla dm file has a check mark on it and then try rebuilding.  This error happens for when a file in DM has its checks mark removed.

**Comment by Redtrogdor** [comment]
Thank you. I'd been having previous issues with compilation (I had an archive version of BYOND instead of one installed to Program Files) and being unable to compile my own private server was a bit frustrating.
