### ISSUE TITLE
Antag Panel lost, upon switching to another Golem body (and considered dead for others)

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#63303]
## Round ID: 
[174379](https://scrubby.melonmesa.com/round/174379)

## Testmerges: 
None

## Reproduction: 

> Turn yourself into a Luminescent with Xeno bio
> Consume Adamantite Extract as major to turn yourself into a golem
> Build a runic golem shell and switch to it
> Cry because you just lost your antag panel and your uplink code with it

Memories were still kept, like Account ID

Also you are considered dead for the others, even if you are still running around with your new body

![Screenshot_2](https://user-images.githubusercontent.com/95751821/145202991-a918cb30-3996-4ad2-8054-68d12d7e2375.png)

**Comment by SuperNovaa41** [comment]
That's what you get for playing as a golem

**Comment by JohnFulpWillard** [comment]
> That's what you get for playing as a golem

SO TRUE

But in seriousness, the antag panel is given to the player's mob, rather than their mind, so the antag ui button isn't persistent through bodies.
IT ALSO MEANS THAT ANYONE'S BRAIN TRANSPLANTED INTO YOUR BODY WILL GET *YOUR* UI WITH *YOUR* OBJECTIVES ON IT.

**Comment by SuperNovaa41** [comment]
wow thats cringe we should change that
