### ISSUE TITLE
Infinite 5u syringe

### ISSUE THREAD

**Issue by Amrabol** [tgstation/tgstation#63301]
## Reproduction:
Made oculater. Got syringe. Walked around asking people if they want to try bad chem. Notice tha syringe never ends if injected

**Comment by SuperNovaa41** [comment]
Duplicate of https://github.com/tgstation/tgstation/issues/63284

**Comment by SuperNovaa41** [comment]
This has a better name

**Comment by ATH1909** [comment]
lmao

**Comment by SuperNovaa41** [comment]
This applies to all methods of consumption (eye dropper, syringe, in food, etc) and also is apparently happening to only inverse chems. 

https://github.com/tgstation/tgstation/issues/63167
