### ISSUE TITLE
Opening emergency suit storage while not on red alert.

### ISSUE THREAD

**Issue by TattoMoon** [tgstation/tgstation#63316]
## Round ID:

174468

## Reproduction:

Right clicking on an emergency suit storage safe with an item allows you to bypass the alert lock and open it.

![unknown (8)](https://user-images.githubusercontent.com/94944115/145368927-cc84da76-a99d-4cf6-906b-0d1b29276caa.png)

**Comment by TheBonded** [comment]
during this round, was the alert level ever set to red alert? the pod storages do not relock after the alert level lowers

**Comment by TattoMoon** [comment]
I dont think the alert level ever reached red at all. Left licking on the storage units prevented me from opening them, giving me the warning that the alert level needed to be Red. Right clicking with an item opened them, as if trying to let me stuff it inside, and popped open the menu.

**Comment by TattoMoon** [comment]
Just tested it in round, right clicked on the safe with wire cutters without alert level ever changing and it opened it.

**Comment by Dmeto** [comment]
I swore this was fixed in #61855

**Comment by TheBonded** [comment]
> I swore this was fixed in #61855

I tested it over the weekend and it did work so it must have been broken again
