### ISSUE TITLE
You can toggle the power/max the output rate of atmos injectors through directional windows.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#63318]
Reporting client version: 514.1566

## Round ID:
[174462](https://scrubby.melonmesa.com/round/174462)

## Testmerges:
- [Speeds up the preference menu, significantly. Adds object pooling, other stuff too](https://www.github.com/tgstation/tgstation/pull/63225)
- [Adds Datum Tagging for admins](https://www.github.com/tgstation/tgstation/pull/62982)

## Reproduction:
1. Dispense/construct an atmos injector and attached pipe in an area with power.
2. On each of the open turfs adjacent to the atmos injector place a directional window facing the atmos injector.
3. Stand on one of the adjacent open turfs.
4. Ctrl-left-click or alt-left-click the atmos injector.

**Comment by Sealed101** [comment]
fixed by attack chain refactors and/or https://github.com/tgstation/tgstation/pull/83784 / https://github.com/tgstation/tgstation/pull/82656
