### ISSUE TITLE
Operating Computer that is required for Biotech, is locked behind Biotech

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#63326]
## Round ID: 
N/A

## Testmerges:
N/A

## Reproduction:

Possible Oversight in #63033

In the (unlikely) Event that the operating computer boards are gone, you are unable to complete the biotech experiment for more boards or anything that is locked behind that

Ghost Roles (for example Golem) suffer from that, since they have no way to complete that experiment by themselves

![Screenshot_1](https://user-images.githubusercontent.com/95751821/145481978-4d425a84-eb08-4cd1-befc-597a188dc850.png)

**Comment by timothymtorres** [comment]
Fixed by #67012
