### ISSUE TITLE
Cannot combine items with Sec Helmets anymore

### ISSUE THREAD

**Issue by VanDarkholme6969** [tgstation/tgstation#63329]
Reporting client version: 514.1569

## Round ID:
[174501](https://scrubby.melonmesa.com/round/174501)

## Testmerges:
- [Speeds up the preference menu, significantly. Adds object pooling, other stuff too](https://www.github.com/tgstation/tgstation/pull/63225)
- [Adds Datum Tagging for admins](https://www.github.com/tgstation/tgstation/pull/62982)

**Comment by TheBonded** [comment]
Tested, could not reproduce. Clicking on the helmet with a flashlight put it on as usual.

**Comment by SuperNovaa41** [comment]
People report this **all** the time and it's usually just a case of terminal stupidity.

**Comment by D4C-420** [comment]
any chance you were on combat mode? Thing's don't combine when your on combat mode (see also affixing bayonets')

**Comment by VanDarkholme6969** [comment]
Wasn't on Combat Mode. In fact, an admin (That Engineer) spent about 10 minutes fucking with it *right in front of me* and also could not get it to work. I see that it works now, but I have absolutely no idea what the issue was.

**Comment by SuperNovaa41** [comment]
I'll be honest, there could be something wrong with it due to the fact that apparently this happens to loads of people. However, the code looks pretty solid... i don't see any reason as to WHY it might be doing that. I'll just leave it closed for now.

**Comment by VanDarkholme6969** [comment]
OKAY. It's the fucking helmets on the rack in Deltastation's armory. THOSE do not work with flashlights/remote signallers.

**Comment by VanDarkholme6969** [comment]
I should specify, it's not the riot/bulletproof helmets I'm referring to, either. It's just the straight up, default-ass helmets that are just called "Helmet"

**Comment by TheBonded** [comment]
> I should specify, it's not the riot/bulletproof helmets I'm referring to, either. It's just the straight up, default-ass helmets that are just called "Helmet"

that's... really weird. since when did deltastation's armoury have normal helmets?

**Comment by TheBonded** [comment]
huh, guess it does have em. classic delta

**Comment by SuperNovaa41** [comment]
Congratulations, this bug is probably very old lmao

**Comment by VanDarkholme6969** [comment]
Let it be known that everybody who's bitched about this interaction aren't fucking insane
