### ISSUE TITLE
Liberty Caps drug you so hard, that they can crash the game (also good mood forever)

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#63322]
## Round ID:
[174426](https://scrubby.melonmesa.com/round/174426)

## Testmerges:
None

## Reproduction:

> Eat Liberty Cap (Mushroom Hallucinogen)
> Enjoy the Time till it ends
> Get stuck in an endless sub 20 FPS Hell, which gets worse over time
> (Optional) Crash the Game

Not really sure why it happens but i saw it in 3 different rounds now , all on campbell
Relogging resets the "Hell", but it can start again

Also the positive moodlet never disappears

![Screenshot_2](https://user-images.githubusercontent.com/95751821/145468253-a2d2feaf-f54c-4a42-976d-bd310c60be8a.png)

**Comment by SuperNovaa41** [comment]
the hallucination definitely goes away, but the mood event is not being removed. 
Related code:
https://github.com/tgstation/tgstation/blob/f6d15afaa1afe5f60697e68782b79b5dbdcc50e5/code/modules/reagents/chemistry/reagents/drug_reagents.dm#L7-L9
is not removing the mood event `/datum/mood_event/high`
