### ISSUE TITLE
opening a body bag on yourself sends you to the shadow realm

### ISSUE THREAD

**Issue by castawaynont** [tgstation/tgstation#63343]
## Round ID:

Round ID: [174567](https://scrubby.melonmesa.com/round/174567)

## Reproduction:
open a body bag on yourself
bodybag deploys on yourself open
you get sucked into it
you cannot move out of it, you need to click on the bodybag to close it in order to free yourself

![shadowrealm](https://user-images.githubusercontent.com/76170211/145660098-dc7ab13b-9391-46a4-a6d1-39edda9843f4.PNG)
(there's a guy stuck inside the bodybag there)

**Comment by interestingusernam3** [comment]
And then he turned himself into a body bag, funniest shit I've ever seen

**Comment by necromanceranne** [comment]
Can't seem to replicate. Is there more too this? Maybe there is something else happening at the time but yeah I think this one is just anomalous weirdness. Can't replicate it.
