### ISSUE TITLE
Spiders are now temperature-immune? 

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#63349]
Reporting client version: 514.1568

## Round ID:
[174576](https://scrubby.melonmesa.com/round/174576)

## Testmerges:
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)

## Reproduction:
Spiders no longer appear to be affected by extreme cold or extreme heat.

**Comment by TemporalOroboros** [comment]
I was a spider that round and I was absolutely taking environmental damage. Might have been O2, but I'm pretty sure it was thermal.

**Comment by dragomagol** [comment]
Hmm, maybe because it's not as drastic as before?
