### ISSUE TITLE
TGUI Input lists do not let you use the arrow keys to move up and down

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#63344]
Regression from older lists, important for a11y. 

Pressing up/down should move the cursor up and down, currently it does nothing..

**Comment by LemonInTheDark** [comment]
muh workflow

**Comment by Mothblocks** [comment]
It's accessibility silly

**Comment by jlsnow301** [comment]
I will be doing an entire rewrite of input list (=> sfc in es6/typescript) which will presumably fix this. 

I had this done but accidentally ~ deleted the file ~ by not stashing
