### ISSUE TITLE
Job changes don't update bounties or vendor prices

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#63342]
## Round ID:

[174565](https://scrubby.melonmesa.com/round/174565)

## Testmerges:

N/A

## Reproduction:

Having your job changed at the moment will only change your access, you will have the former jobs bounties as well as vending machine discounts.

**Comment by san7890** [comment]
Should have been fixed with #66677.

**Comment by Sealed101** [comment]
same as #67009 and #57516 basically
