### ISSUE TITLE
Icebox RD Office APC cant be seen by AI

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#63367]
## Round ID: 
N/A

## Testmerges:
N/A

## Reproduction:

> Try to reboot/disable APC in RD Office
> Fail because someone put a poster up in another room

Normal View :
![Screenshot_1](https://user-images.githubusercontent.com/95751821/145693550-cbe7dd9f-4f02-40c3-88fe-7cfc5c48c77f.png)

AI View:
![Screenshot_2](https://user-images.githubusercontent.com/95751821/145693551-478e4b0c-81d1-4648-af41-6923492c3b82.png)

**Comment by MrMelbert** [comment]
damn you, posters

**Comment by LemonInTheDark** [comment]
lol
