### ISSUE TITLE
Teleporting on tramstation seems to send you somewhere random.

### ISSUE THREAD

**Issue by oether-ch4** [tgstation/tgstation#63368]
Reporting client version: 514.1568

## Round ID:
[174629](https://scrubby.melonmesa.com/round/174629)

## Testmerges:
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)
- [documents important MC vars and procs and adds tracking of tick usage when the mc first wakes up](https://www.github.com/tgstation/tgstation/pull/63355)

## Reproduction:
Step 1 : teleport on tramstation

Teleporting on tramstation sends you to somewhere (apparently) random on the same z-level, only the hierophant recall seemed to work. Here's a [video](https://www.youtube.com/watch?v=gCB31XjqVwk) showing what I mean.

**Comment by MrMelbert** [comment]
You were wearing a bag of holding and using bluespace teleportation - BoH messes with bluespace teleportation (portals, hand tele)

Look in the chat, you see: "The bluespace interface on your bag of holding interferes with the teleport!" This is intended

**Comment by oether-ch4** [comment]
Oh... I don't know how I didn't see that chat message up until you mentioned it. Thanks for the info.

**Comment by oether-ch4** [comment]
Guess I am just an illiterate dumbass
