### ISSUE TITLE
Cat ears flicker between disappearing and appearing on any input change in char preview menu

### ISSUE THREAD

**Issue by Razharas** [tgstation/tgstation#63360]
Round ID: [174606](https://scrubby.melonmesa.com/round/174606)

Local commit: 2f61f8eddbd75a589f16d010fc81fac476327e1e
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Open char preferences
Select being a felinid with cat ears
Change any of the button inputs in there
The ears disappear/reappear
![example](https://user-images.githubusercontent.com/5615294/145681339-a1178f1c-0d00-439f-9c59-52e97d080db5.gif)

**Comment by Fikou** [comment]
@Mothblocks

**Comment by LemonInTheDark** [comment]
How

**Comment by Mothblocks** [comment]
Didnt this end up being your fault I was skimming coding general

**Comment by LemonInTheDark** [comment]
yeah this is my fault, I'll clean it up
Cat ears being enabled are stored as a part of the dna features list, so when we say, remove cat ears before felinid on_species_gain gets a chance to run, we make the next run have no cat ears. s dumb

Not sure how I'm gonna fix it, need to think about it
