### ISSUE TITLE
Coronary bypass doesn't check for presence of a heart

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#63380]
Reporting client version: 514.1571

## Round ID:
[174694](https://scrubby.melonmesa.com/round/174694)

## Testmerges:
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)

## Reproduction:

I was doing a corony bypass because I'd replaced a patient's organs with the only ones I could find and the heart I'd used was too damaged. When I sawed open the chest cavity all the organs spilled out (not sure why).

The organs falling out didn't affect the surgery and I was able to complete it but I soon discovered the heart was one of the organs that had fallen out. The surgery didn't fix it (as you might expect).

The surgery shouldn't continue if the heart is missing. It describes you grafting a corony bypass to a heart that isn't there.

**Comment by Sealed101** [comment]
while the heart graft step should probably have a check to see whether there actually is a heart, organs falling out is normal behaviour. doing the saw step applies brute damage to the target area, and if the patient has sustained enough damage to the chest previously, they're eligible to having their guts spill out.

**Comment by Justice12354** [comment]
@cacogen 
> I was doing a corony bypass because I'd replaced a patient's organs with the only ones I could find and the heart I'd used was too damaged. When I sawed open the chest cavity all the organs spilled out (not sure why).

If your target has a hairline fracture wound on their chest, when using the sawing step (either for coronary bypass, organ manipulation, etc.), all of their organs will be spilt out. I am fairly sure this is an intended feature.

> The surgery shouldn't continue if the heart is missing. It describes you grafting a corony bypass to a heart that isn't there.

This does make sense lol

@Sealed101 
> doing the saw step applies brute damage to the target area, and if the patient has sustained enough damage to the chest previously, they're eligible to having their guts spill out.

I'm fairly sure this is not how it actually happens. I'm pretty sure the organs only spill out if the area you're doing the sawing step on has a hairline fracture (for head and brain, and possibly the other limbs too, for implants). From experience, the target having insane damage on the chest did not affect this.

------
<h3>To conclude, I'm nearly sure this is intended and your target had a hairline fracture on the chest :P</h3>
<h4>Pro Tip: fix hairlines first if you wanna do some experimental, organ manipulation or organ healing surgery!!</h4>

**Comment by Mooshimi** [comment]
The bug here is the surgery continuing with no heart in the chest anymore. Would you mind retitling this for accuracy?
