### ISSUE TITLE
Creating a rough iron false wall requires 5 rods despite previously requiring 2

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#63386]
## Testmerges:
The following pull requests are currently test merged:
#63331: 'Revert "Require Node 16"' by MrStonedOne at commit 3bccf7f8c1

## Reproduction:
Weld down a rough wall (such as in the deep storage ruin in space) and it will provide you 2 iron rods
previously you could then unwrench the girder and reapply those same 2 iron rods to the wall to create a false wall
now, using those 2 iron rods on the wall gives you the message "You need at least two rods to create a false wall!"
you are unable to actually construct the false wall until you get at least 5 iron rods

**Comment by vincentiusvin** [comment]
Seems like my fault, will look into this.

**Comment by newfren** [comment]
I am dead certain it only dropped 2 because I tried to use the exact rod pile that welding down the wall gave me to remake the false wall.

**Comment by newfren** [comment]
Also, it definitely used to only take 2 rods to create these walls.

**Comment by vincentiusvin** [comment]
Yeah the 2->5 is intentional, the previous change was just implemented wrongly. So the two rods come from non false walls then, ill make it five.
