### ISSUE TITLE
Dynamic: Families failed to exectute, and refunded, but families still spawned

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63399]
Reporting client version: 514.1568

## Round ID:
[174751](https://scrubby.melonmesa.com/round/174751)

## Reproduction:
![image](https://user-images.githubusercontent.com/51863163/145929353-0e209ebf-a279-4983-b1af-187ab395b759.png)

The ganghandler runtimed when setting up (see the runtime logs) and caused families to fail to execute, but it continued to spawn the families anyways.

**Comment by MrMelbert** [comment]
@Iamgoofball

**Comment by MrMelbert** [comment]
![image](https://user-images.githubusercontent.com/51863163/146109641-c60c7e54-d8d0-4d1c-833c-b642f1470b2d.png)

**Comment by Iamgoofball** [comment]
Odd, this wasn't occuring during testing. Is this a thing in every single run of Families, or just this match?
