### ISSUE TITLE
Deltastation has 2 areas called "Customs"

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#63409]
## Testmerges:
The following pull requests are currently test merged:
#63331: 'Revert "Require Node 16"' by MrStonedOne at commit 3bccf7f8c1
#63397: 'Revert "Gasmaks tint and tint calculation update (Oranges approved edition)"' by optimumtact at commit f9b0531fda
#61422: 'Fixes Massive Radio Overtime, Implements a Spatial Grid System for Faster Searching Over Areas' by Kylerace at commit 53720e0fe9

## Reproduction:
did you know "unstable bluespace anomaly in customs" can send you to either the extreme north or extreme south of the station and you just have to guess which one it is

**Comment by TheBonded** [comment]
### Central Command Report
(other customs guys)

**Comment by NanoCats** [comment]
Honestly this one is just funny.
