### ISSUE TITLE
Character appearing ABOVE smoke?

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63402]
## Round ID:
[174757](https://scrubby.melonmesa.com/round/174757)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/145937759-80fb7467-0d13-4b37-8c67-fa84b44ae1c6.png)

- Made gaseous decomposition + carpet plants
- Threw them around to spread the carpet
- Realize that instead of being hidden in smoke, I was floating above the smoke

**Comment by LemonInTheDark** [comment]
Very likely related to https://github.com/tgstation/tgstation/pull/63312

**Comment by LemonInTheDark** [comment]
related to https://github.com/tgstation/tgstation/issues/63407
