### ISSUE TITLE
Aiuri blur doesn't effect mobs

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#63407]
## Testmerges:
The following pull requests are currently test merged:
#63331: 'Revert "Require Node 16"' by MrStonedOne at commit 3bccf7f8c1
#63397: 'Revert "Gasmaks tint and tint calculation update (Oranges approved edition)"' by optimumtact at commit f9b0531fda
#61422: 'Fixes Massive Radio Overtime, Implements a Spatial Grid System for Faster Searching Over Areas' by Kylerace at commit 53720e0fe9

## Reproduction:
https://puu.sh/Iwb9n/76fc009f76.png

**Comment by LemonInTheDark** [comment]
https://github.com/tgstation/tgstation/pull/63312 didn't add the new gameplane fov blocker to the filter list, so we aren't filtering it.

I wonder if maybe `GAME_PLANE_FOV_HIDDEN` should render onto the game plane? Bit of a spitball though, rendering isn't my strongest suit, so I'm not sure that would fix related layering issues
