### ISSUE TITLE
Navigation Computer Outlines are Missing

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#63413]
## Round ID:
N/A, Local Branch

## Testmerges:
N/A

## Reproduction:
Byond Version: 514.1568

When using navigation computers, the green outline of the shuttle is completely missing, as is the blue outline of a marked location. This makes precise navigation rather obtuse. (Especially with smaller shuttles, like the trade route syndicate cutter)

**Comment by SuperNovaa41** [comment]
Duplicate of https://github.com/tgstation/tgstation/issues/62099

**Comment by unit0016** [comment]
Hell, searched "Navigation Computer" and didn't see that issue. My bad.
