### ISSUE TITLE
Opening the BEPIS's maintenance panel makes it disappear.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#63411]
Reporting client version: 514.1566

## Round ID:
[174782](https://scrubby.melonmesa.com/round/174782)

## Testmerges:
- [creates SSspeech_controller so the MC can control say() execution](https://www.github.com/tgstation/tgstation/pull/63118)
- [[s] [dnm] Adds browser id to chat telemetry](https://www.github.com/tgstation/tgstation/pull/63403)

## Reproduction:
1. Observe the BEPIS.
2. Approach the BEPIS with a screwdriver.
3. Apply the screwdriver to the BEPIS.
4. Stop observing at the BEPIS as it is now invisible.

**Comment by Mooshimi** [comment]
First thought is, it doesn't have a sprite for being open?

**Comment by JohnFulpWillard** [comment]
> First thought is, it doesn't have a sprite for being open?

As someone whose been using bepis for experisci for a while, it had one a while ago.

**Comment by JohnFulpWillard** [comment]
booted up latest master, appears to work?
![image](https://user-images.githubusercontent.com/53777086/146632192-12f9e222-e40d-4637-aeac-1f2929734dc5.png)

**Comment by Mooshimi** [comment]
Cleanup since this doesn't seem to be reproducible.

**Comment by tralezab** [comment]
i am ruling right now that this is not against god and nature, you must be wise with that label
