### ISSUE TITLE
Giving an AI an (ion?) law with an asterisk in it breaks the sayverb

### ISSUE THREAD

**Issue by Ryll-Ryll** [tgstation/tgstation#63422]
Reporting client version: 514.1557

## Round ID:
[174818](https://scrubby.melonmesa.com/round/174818)

## Testmerges:
- [creates SSspeech_controller so the MC can control say() execution](https://www.github.com/tgstation/tgstation/pull/63118)
- [[s] [dnm] Adds browser id to chat telemetry](https://www.github.com/tgstation/tgstation/pull/63403)

## Reproduction:
Unfortunately I'm not gonna be able to do my usual deep diving on this one, so I'll just lay out what I know about how I caused this issue

1. I gave the AI an ion law saying "F*CK"
2. AI states the laws for the crew
3. As shown in image below, the asterisk seems to break the sayverb parsing. 

[![dreamseeker_2021-12-15_01-29-37.png](https://i.imgur.com/YWdhhqSl.jpg)](https://i.imgur.com/YWdhhqS.png)

Instead of `Architect states, "(ion garbles). F*CK"`, it replaced the sayverb the ion garbles and the text before the * as shown above. This happens both when they state the laws locally, as well as over the radio

[![dreamseeker_2021-12-15_01-33-29.png](https://i.imgur.com/DeDhaLLl.jpg)](https://i.imgur.com/DeDhaLL.png)

I assume this has something to do with #62130, and not being able to differentiate between normal player speech which probably would use the asterisk intentionally to modify the sayverb, and forced speech for things like AI laws which may legitimately have asterisks in them. 

I don't know what a good fix for this would look like, or if maybe it's not an issue at all and people just shouldn't use asterisks in AI laws (i assume this would happen if a random event or player-uploaded law had an asterisk in it), but it felt worth bringing up

**Comment by dragomagol** [comment]
This also happens when Poly tries to say things that are obscured by asterisks
