### ISSUE TITLE
Energy axe left hand face left / face right inhands are backwards

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63423]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/146154338-4e1ce0f0-4a27-4b38-a76f-3f9e666da6ff.png)

![image](https://user-images.githubusercontent.com/51863163/146154320-b0f85ec2-a046-49df-b610-477697a4cb5a.png)

**Comment by ShizCalev** [comment]
riot
