### ISSUE TITLE
Previous action detector has gone FUCKING INSANE

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#63432]
Reporting client version: 514.1569

## Round ID:
[174853](https://scrubby.melonmesa.com/round/174853)

## Testmerges:
- [documents important MC vars and procs and adds tracking of tick usage when the mc first wakes up and other stats](https://www.github.com/tgstation/tgstation/pull/63355)
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)

## Reproduction:

It's best encountered as an asteroid comms agent using the PDA console.
Usually this happens.
![image](https://user-images.githubusercontent.com/80979251/146272061-b683dcc6-35c4-4981-83ed-79d7c9090df1.png)
Someone please figure it out

**Comment by jlsnow301** [comment]
Fixed in #63395
