### ISSUE TITLE
clown mob spawners not working

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#63444]
Reporting client version: 514.1571

## Round ID:
[174927](https://scrubby.melonmesa.com/round/174927)

## Testmerges:
- [[DNM] Reference Tracking on Live Again Again](https://www.github.com/tgstation/tgstation/pull/63388)

## Reproduction: 
/obj/effect/mob_spawn/human/clown/corpse spawns this:

![image](https://user-images.githubusercontent.com/37246588/146488442-e5278721-a510-4a11-b775-869c6febf257.png)

... as opposed to a real corpse. it was discovered after a clown bomb was used

**Comment by Mooshimi** [comment]
@tralezab

**Comment by ArcaneMusic** [comment]
Most likely related to #63279.

**Comment by SuperNovaa41** [comment]
No longer an issue
