### ISSUE TITLE
Ninjas can call reinforcements even if the comms console is depowered

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#63445]
## Round ID: 
[174921](https://scrubby.melonmesa.com/round/174921)

## Testmerges:
#63331 #63439

## Reproduction:
See title: ninja was able to call in pirates, despite the bridge and consoles being depowered

**Comment by SuperNovaa41** [comment]
lmfao

**Comment by jlsnow301** [comment]
feature 100%

**Comment by NanoCats** [comment]
Ninja is the most valid motherfucker ever to live, give the guy a break.
