### ISSUE TITLE
Nameless, Unselectable Golems

### ISSUE THREAD

**Issue by Cirrial** [tgstation/tgstation#63443]
Reporting client version: 514.1571

## Round ID:
[174913](https://scrubby.melonmesa.com/round/174913)

## Testmerges:
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)

## Reproduction:

As a golem shell spawn, you have no name and do not show up on the right click drop down menu of the tile you currently occupy.

Originally I observed in the round and then spawned in as a venus man trap, and then after dying I chose to spawn as a xenobio golem, and found the weirdness with my name. Reported my situation to an admin, who then respawned me, and I spawned in as a xenobio golem again. Same problem.

Steps to reproduce:

1. Start the round through observe, or otherwise become a ghost.
1. Respawn as a golem from a standard inert golem shell.
2. Observe that, when speaking, your name is "Previous Name (as Unknown)" when speaking, and completely blank when emoting.
3. You do not show up in the right click drop down menu for any user, admin or otherwise.

**Comment by TheBonded** [comment]
seen this happen in multiple rounds

**Comment by necromanceranne** [comment]
Quantum Golems

**Comment by Mooshimi** [comment]
Probably due to #63279 which touched the golem file. @tralezab thoughts?

**Comment by Mooshimi** [comment]
maybe has something to do with this deleted thing from their pr? 
![image](https://user-images.githubusercontent.com/85910816/146618848-6e19bba5-8370-43b2-b944-38dcd9cfdb06.png)
