### ISSUE TITLE
MMI'd headrev at the time of a revolutionary defeat still gets a pod with a banner

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63463]
## Round ID:

[174977](https://scrubby.melonmesa.com/round/174977)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/146627331-a46c3ce4-daee-473e-b872-609069962906.png)
![image](https://user-images.githubusercontent.com/51863163/146627313-dd365f86-29ec-45b7-a08e-d4042499196f.png)

Speaks-Her-Mind, head revolutionary, lost the revolution... but still got a banner at their location at the end of it all.

**Comment by interestingusernam3** [comment]
Maybe the real revolution was the friends we made along the way
