### ISSUE TITLE
Putting on captain's headset resets what channels it has enabled to default, meaning captain will be unable to listen to any comms other than security or command

### ISSUE THREAD

**Issue by itseasytosee** [tgstation/tgstation#63483]
Tested localy

## Reproduction:
Have captains headset
Try to change what comms it has enabled
Put the headset on
Be unable to speak on comms you enabled because they were reset.
Cry, because the captain's headset chip is no more valuable than the hos' chip.

**Comment by newfren** [comment]
Can you open the menu, equip the headset, then change the channels that are enabled?

**Comment by itseasytosee** [comment]
> Can you open the menu, equip the headset, then change the channels that are enabled?

I tried, don't think it works, so my reasoning is probably wrong.

**Comment by lessthnthree** [comment]
> Can you open the menu, equip the headset, then change the channels that are enabled?

Yes. The channels are reset on the action of placing/removing it from the ear.
Opening the menu, putting on the headset, and then setting the channels will stick. (Or enable the channels using VV)
