### ISSUE TITLE
Syndicate masks are affected by FOV (oversight?)

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#63488]
Supposedly these masks were exempt from the prior gas mask tint, but as of now are affected by FOV. This _might_ be an oversight, but I have no idea if that's true or not.
![image](https://user-images.githubusercontent.com/33107541/146658618-eb349695-c1b9-484d-9c8a-484e995a9c46.png)

**Comment by SuperNovaa41** [comment]
this was intended, this is a balance issue
