### ISSUE TITLE
Spooky Skeleton not actually spawning as a skeleton

### ISSUE THREAD

**Issue by Pieniadz9** [tgstation/tgstation#63482]
Reporting client version: 514.1569

## Round ID:
[175026](https://scrubby.melonmesa.com/round/175026)

## Testmerges:
- [[DNM] Reference Tracking on Live Again Again](https://www.github.com/tgstation/tgstation/pull/63388)

## Reproduction:
Spawning in as a skeleton will sometimes just spawn you as a normal human

**Comment by Donpedrito** [comment]
Fixed by #64518.

**Comment by TheBonded** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/64518.
