### ISSUE TITLE
Sec air masks (hailers?) obscuring vision, despite not covering or protecting eyes

### ISSUE THREAD

**Issue by Robustitron** [tgstation/tgstation#63489]
## Testmerges:

#62055: 'Moves atmos checking from Fire Alarms to Fire Locks, Fire Locks now close on their own rather than area-based, a bunch of related stuff.' by zxaber at commit 613bfeb30d

## Reproduction:

1: Put on sec air mask, either on your mouth or off to the side
2: You can't see behind yourself, despite not having your eyes covered or protected by anything.

TL;DR once again sec air masks are covering or obscuring eyes somehow, despite being a mouth air mask that does not protect or cover the eyes.

This leads to the usual routine of sec dropping their sec masks on the floor, and finding the nearest air mask out of a locker, which also covers the mouth, but without obscuring vision.

**Comment by SuperNovaa41** [comment]
This is a balance issue not a bug
