### ISSUE TITLE
FOV appears to be broken (?)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63494]
## Round ID:
[175034](https://scrubby.melonmesa.com/round/175034)

## Testmerges:
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)
- [test disables ai static to see if it helps maptick enough to justify a refactor of how it works](https://www.github.com/tgstation/tgstation/pull/63439)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/146658119-a8977d24-c260-4458-b0d4-dc19c8c9b5ff.png)

- Put on gas mask
- Turn around
- See people in full vision behind you

**Comment by necromanceranne** [comment]
They haven't entered **_STEALTH MODE_**, and thus aren't even TRYING to hide. Pathetic.

**Comment by necromanceranne** [comment]
My justification is that maybe there is more to this. Last time I messed with FoV, it was assuredly working, unless a recent PR has changed this.

**Comment by MrMelbert** [comment]
It's either a test-merge bug, a very recent bug, or (heavens forbid) a byond bug, because i'm able to consistently do it across rounds

**Comment by Jackraxxus** [comment]
Amazing
<img src="https://i.ibb.co/vDVFLL7/BugTest.png" alt="BugTest" border="0">
