### ISSUE TITLE
Checking your mood with TK gives you a balloon alert that it's out of reach 

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63493]
Reporting client version: 514.1568

## Round ID:
[175034](https://scrubby.melonmesa.com/round/175034)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/146660161-e8d1f8fd-170f-428b-98e5-b39d685018bd.png)

![image](https://user-images.githubusercontent.com/51863163/146660157-ade25c25-6f63-4eee-87a0-7a78ac87f1ad.png)

**Comment by necromanceranne** [comment]
I could reproduce this, so yes, this is accurate, it's also really silly that TK is apparently interacting with HUD elements like this.

**Comment by jlsnow301** [comment]
with telekinesis, everything is in reach _except for your own sanity_

**Comment by iwishforducks** [comment]
I always thought this was just a permanent mood debuff given by TK. TIL
