### ISSUE TITLE
The dog in security plays fetch even when it's buckled

### ISSUE THREAD

**Issue by jacklecroy** [tgstation/tgstation#63491]
Buckle the dog to a dog bed and it plays fetch and drags the bed with it.

**Comment by SuperNovaa41** [comment]
https://github.com/tgstation/tgstation/pull/58686
That's weird. This was supposed to be fixed.

**Comment by Mooshimi** [comment]
@tralezab This worked as intended before 
![image](https://user-images.githubusercontent.com/85910816/146995066-ff29e520-f6af-4dd9-9337-5b2516224bdf.png)
(whose github is now deleted or something) switched it to wrappers four months later?
![brave_BloixSfRFm](https://user-images.githubusercontent.com/85910816/146995133-ce940c43-2241-4188-9800-f6f787ae1ee7.png)

**Comment by jacklecroy** [comment]
> @tralezab This worked as intended before ![image](https://user-images.githubusercontent.com/85910816/146995066-ff29e520-f6af-4dd9-9337-5b2516224bdf.png) (whose github is now deleted or something) switched it to wrappers four months later? ![brave_BloixSfRFm](https://user-images.githubusercontent.com/85910816/146995133-ce940c43-2241-4188-9800-f6f787ae1ee7.png)

So then either there is something wrong with the buckled check or the resist action.
