### ISSUE TITLE
The exoscanner array control console's UI scaling is  incredibly wonky

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63498]
Reporting client version: 514.1568

## Round ID:
[175051](https://scrubby.melonmesa.com/round/175051)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/146668410-177f346d-febb-43ef-9683-7185cb61c2e5.png)

The UI for the scanner array control console scales incredibly wonky, and seems to be a different size every time you open the UI.

No image editing is done in that above screenshot. It was only cropped. It genuinely looks like that.

**Comment by jlsnow301** [comment]
Will get to this later today

**Comment by jlsnow301** [comment]
(Without looking) it looks like the window height is just not set at all
