### ISSUE TITLE
Delta Station Expansion AI pathing issues

### ISSUE THREAD

**Issue by jlsnow301** [tgstation/tgstation#63502]
## Round ID:
Current

## Testmerges:
N/A

## Reproduction:
Bot pathing gets bots stuck on the rails near kitchen/bar.
Noticed beepsky stuck without voicing any error lines. Dragged it, and it went back to the same rail.
It looks like they try to veer Northeast but can't complete the path.
Presumably, this could be fixed by making the nav beacon directly north to avoid clipping into the rail.

**Comment by MrMelbert** [comment]
I made an issue about this, #63228 , says it was fixed, still not?

**Comment by jlsnow301** [comment]
> I made an issue about this, #63228 , says it was fixed, still not?

Beepsky was indeed stuck on a rail, so this is still an issue

**Comment by Seris02** [comment]
I just noticed this downstream too, so, I don't know how this is happening anymore, I definitely fixed what I thought was the issue, and that fixed at the very least a fair bit of the issues that I was seeing happening
