### ISSUE TITLE
37 runtimes + another mob living happily in null

### ISSUE THREAD

**Issue by Alek2ander** [tgstation/tgstation#6351]
f9cf4f233d9d61bd5f631df7a49cd9611d6a0427

I won't make a separate report for each because this is how aran likes it.  
~~http://pastebin.com/5sCupYUb~~ (old link)
http://pastebin.com/Je5adeD1  
- [x] 1: Mimic in null
- [x] 2: Is space broken? (runtime error: undefined variable /turf/space/var/broken)
- [ ] 3: Air injector deconstruction (runtime error: Cannot modify null.loc.)
- [ ] 4: Dragonsbreath burining null (runtime error: Cannot execute null.hotspot expose().)
- [x] 5: Facehugging oreboxes (runtime error: undefined variable /obj/structure/ore_box/var/stat)
- [x] 6: Solars powernets (runtime error: Cannot read null.powernet)
- [x] 7: ??? (runtime error: Cannot read ... (/obj/item/weapon/circuitboard/arcade/battle).build_path)
- [ ] 8: !!! (runtime error: undefined proc or verb /matrix/react().)
- [ ] 9: DNA scanner damage coefficient (runtime error: Cannot read null.damage_coeff)
- [ ] 10: Potatoes use nothing (runtime error: Cannot execute null.use().)
- [ ] 11: Pipes without air (runtime error: Cannot read null.air)
- [ ] 12: Mindless transformation (runtime error: Cannot read null.mind)
- [x] 13: Flashes without a user (runtime error: Cannot execute null.visible message().)
- [x] 14: Loc of a path (runtime error: Cannot modify /obj/item/weapon/circuitboard/arcade/orion_trail.loc.)
- [ ] 15: area/Adjacent() (runtime error: Call to /area/Adjacent(), unimplemented proc)
- [ ] 16: Plating is a wall (runtime error: undefined proc or verb /turf/simulated/floor/plating/try destroy().)
- [x] 17:Antag HUD for null (runtime error: Cannot read null.antag_hud)
- [X] 18: Disposals expel null (runtime error: Cannot create objects of type null.)
- [X] 19: Disposals again (runtime error: undefined proc or verb /turf/simulated/floor/engine/transfer().)
- [x] 20: Borgs with glasses! (runtime error: undefined variable /mob/living/silicon/robot/var/glasses)
- [x] 21: Something weird with freezers (runtime error: Cannot read null.other_atmosmch)
- [x] 22: Something weird with freezers: revengeance (runtime error: Cannot read null.other_airs)
- [ ] 23: Examining your nonexistant self?! (runtime error: Cannot execute null.examine().)
- [x] 24: Monkeys with glasses!! (runtime error: undefined variable /mob/living/carbon/monkey/var/glasses)
- [ ] 25: Is nothing a disease? (runtime error: Cannot execute null.IsSame().)
- [ ] 26: PDA messages from hell (runtime error: Cannot read null.z)
- [ ] 27: Clicking nonexistant bombs (runtime error: Cannot execute null.attack self().)
- [ ] 28: Fleshmending nobody (runtime error: Cannot execute null.adjustBruteLoss().)
- [ ] 29: Nothing's encrypted (runtime error: Cannot read null.decryptkey)
- [x] 30: ARGH SCRIPTS (runtime error: Cannot read null.value)
- [ ] 31: Gas reagents. (runtime error: undefined proc or verb /datum/gas_mixture/get reagent amount().)
- [ ] 32: Division by zero! (runtime error: Division by zero)
- [ ] 33: Nonexistant bombs exploding (runtime error: Cannot execute null.release().)
- [ ] 34:Is this the appendix in mechfabs? (runtime error: list index out of bounds)
- [ ] 35: Stinging with nothing (runtime error: Cannot modify null.remaining_uses.)
- [ ] 36: Corrupting a nonexistant cell (runtime error: Cannot read null.charge)
- [ ] 37: Narsie save me (runtime error: type mismatch: += "blood")
- [x] 38: Null with glasses? (runtime error: Cannot read null.glasses)

**Comment by Miauw62** [comment]
I added another funtime.

**Comment by duncathan** [comment]
How many of these are still present?

**Comment by Dorsisdwarf** [comment]
See the checkboxes on the left?

That many.

**Comment by CyberbossJHCB** [comment]
Can't repro 10, might've been fixed

**Comment by Iamgoofball** [comment]
there's no way any of these are even still active

**Comment by Cyberboss** [comment]
Lets get this closed

**Comment by Cheridan** [comment]
k
