### ISSUE TITLE
you cannot combine items while on combat mode

### ISSUE THREAD

**Issue by redsunoverparadise** [tgstation/tgstation#63511]
## Round ID:
N/A

## Reproduction:
Hold 2 combinable items, toggle combat mode on, attempt to put them together, resulting in nothing

**Comment by SuperNovaa41** [comment]
every item is defined differently lol have fun whoever fixes this

**Comment by JohnFulpWillard** [comment]
can you give an example of this?

**Comment by SuperNovaa41** [comment]
> can you give an example of this?

can't combine (mosin or ka) with combat knife on combat mode

**Comment by SuperNovaa41** [comment]
![image](https://user-images.githubusercontent.com/16159590/146979150-4471aaeb-c113-4fe8-8316-20f36c607748.png)
The thing is.. this is very much intended.
I'm just going to close this
