### ISSUE TITLE
Buckled Objects + Disposals Bugs

### ISSUE THREAD

**Issue by jlsnow301** [tgstation/tgstation#63517]
## Round ID:

current
## Testmerges:
current

## Reproduction:
- Be pushed into disposals while buckled to an object (via chute) 
- The object will disappear, but you are still buckled to it and cannot move
- If the object exits, you will teleport onto it (no matter the time difference)
- If you pull the buckled mob, it rips the bucklee (chair/whatever) out of disposals

**Comment by msgerbs** [comment]
Do you know if this used to work in the past?

**Comment by jlsnow301** [comment]
I don't think I've ever tried it previously - so no

**Comment by timothymtorres** [comment]
Duplicate of #42040
