### ISSUE TITLE
Select Equipment runtiming with Hardsuit Shaft Miner

### ISSUE THREAD

**Issue by SuperNovaa41** [tgstation/tgstation#63525]
Under Jobs -> select `Shaft Miner (Equipment + Hardsuit)`
and it will runtime with the error
![unknown](https://user-images.githubusercontent.com/16159590/146861122-2e36c3bc-879b-445c-86b3-4d731327be0c.png)

**Comment by necromanceranne** [comment]
Tried to do this, can't replicate now, so probably safe to close
