### ISSUE TITLE
Security Gasmasks Trigger the FOV

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#63531]
## Reproduction:
Wear Security Gas Mask
All of a sudden you are in a negative cone
this is so sad

![image](https://user-images.githubusercontent.com/34697715/146878301-9045ea04-0232-4969-82c1-81b37cbadb2e.png)

**Comment by tralezab** [comment]
>Round ID: Irrevelvant

**Comment by san7890** [comment]
> > Round ID: Irrevelvant
> 
> wooooow

fixed

**Comment by Mooshimi** [comment]
Isn't this intended?

**Comment by SuperNovaa41** [comment]
@Mooshimi No it's not
