### ISSUE TITLE
Custom Vendors are bluescreening again

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#63546]
Reporting client version: 514.1561

## Round ID:
[175187](https://scrubby.melonmesa.com/round/175187)

## Testmerges:
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)
- [test disables ai static to see if it helps maptick enough to justify a refactor of how it works](https://www.github.com/tgstation/tgstation/pull/63439)

## Reproduction:

1. Build a custom vendor.
2. Put in a priced item.
3. Oh no, it broke.

It worked until I placed an item into the vendor, at which point, it broke! The items in question were 1 bulletproof vest, two mosins and three mosin stripper clips.

**Comment by Mooshimi** [comment]
Merging with #63307

**Comment by necromanceranne** [comment]
oops, good call I tried searching for it and got nothing
