### ISSUE TITLE
A couple strips of turfs in meta sci have openspace base turfs.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#63548]
Reporting client version: 514.1566

## Testmerges:
- #63393

## Reproduction:
1. Spam high devastation missiles at metastations science area.
2. Notice that a couple strips of plating appear to be indestructible.
3. Debug.
4. Find that they have openspace base turfs and are reverting to plating whenever they are destroyed.

![ImmuneToExplosions](https://user-images.githubusercontent.com/53582584/146996978-bed54d9f-53b3-4207-90d8-c81d53b20317.png)
Coordinates in the image are (123, 95)

**Comment by LemonInTheDark** [comment]
?????????????????????????

**Comment by TemporalOroboros** [comment]
This is contributing to #65348.
If the openspace base turfs in metastation's science department are broken they create openspace turfs.
When something tries to move over the resulting turf it tries to make the thing fall into the next z down.
Since there is no 'down' on meta this early returns without ever unmarking the thing for falling.
Since the z-level transitions ignore things that are falling whatever crossed the openspace can no longer use the map edge z-level transitions.
In the case of projectiles this lets them hit the edge of the map and delete themselves.
