### ISSUE TITLE
Security cameras with upgrades placed in them during construction lose them upon completion

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#63552]
Reporting client version: 514.1571

## Round ID:
[175200](https://scrubby.melonmesa.com/round/175200)

## Testmerges:
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)
- [test disables ai static to see if it helps maptick enough to justify a refactor of how it works](https://www.github.com/tgstation/tgstation/pull/63439)

## Reproduction:

1. Put gas analyzer into a security camera while you're building it
2. The finished camera will not be upgraded and you will have lost the analyser

**Comment by Mooshimi** [comment]
This looks like the relevant code https://github.com/tgstation/tgstation/blob/3418cd7aaf852faed9240169e009e68b1eeaff58/code/game/machinery/camera/camera_assembly.dm#L214-L241

**Comment by timothymtorres** [comment]
Nice catch @Mooshimi but I’m also going to add this too:

https://github.com/tgstation/tgstation/blob/3418cd7aaf852faed9240169e009e68b1eeaff58/code/game/machinery/camera/camera_assembly.dm#L66-L69

The screwdriver verb initializes the camera but the upgrade modules are not properly applied.  Should be an easy fix for someone to add.

**Comment by timothymtorres** [comment]
Duplicate of #38591
