### ISSUE TITLE
Concrete game abstractions spawning in inconvenient places.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#63555]
Reporting client version: 514.1566

## Round ID:
[175203](https://scrubby.melonmesa.com/round/175203)

## Testmerges:
- [Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)
- [Moves atmos checking from Fire Alarms to Fire Locks, Fire Locks now close on their own rather than area-based, a bunch of related stuff.](https://www.github.com/tgstation/tgstation/pull/62055)
- [Adds Datum Tagging for admins](https://www.github.com/tgstation/tgstation/pull/62982)
- [Tgui list input hotfix + changes](https://www.github.com/tgstation/tgstation/pull/63515)

## Reproduction:
1. Enter the lavaland clown ruin with nothing impeding your path.
2. Complete the clown ruin and move your loot to the entrance.
3. Attempt to leave.
4. ![MobSpawner](https://user-images.githubusercontent.com/53582584/147016305-0d16a95a-9918-4916-8300-f8e02c311088.png)
5. Realize that this... thing is both impassible and indestructible. Also you don't have the necessary tools to deconstruct the walls.
6. Ask the space gods for help.

**Comment by LemonInTheDark** [comment]
brother why are spawners alive at that stage

**Comment by LemonInTheDark** [comment]
![image](https://user-images.githubusercontent.com/58055496/147043873-7b18c492-a4b0-4963-b0de-eb2d9a0562af.png)
bro

**Comment by Mooshimi** [comment]
Related: #63279 @tralezab

**Comment by Sealed101** [comment]
i don't think this occurs anymore and i have no fucking clue how would a mob spawner even end up in that particular spot outside of an actual fucking miracle
