### ISSUE TITLE
You can become a traitor as a space pirate and have no way to access your uplink

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#63564]
## Testmerges:
https://github.com/tgstation/tgstation/pull/63515
https://github.com/tgstation/tgstation/pull/62055
https://github.com/tgstation/tgstation/pull/63500
https://github.com/tgstation/tgstation/pull/62284

## Reproduction:
1 Be space pirate
2 Roll midround traitor
![image](https://user-images.githubusercontent.com/62126254/147151752-19a500f7-a90c-47e9-8d4f-601c7d451660.png)

Since space pirates have no PDA but they have a radio that cannot have its channel custom set you will get an uplink that you cannot get access to.

According to an admin that was online this was a dynamic midround sleeper agent roll which for some reason can target space pirates.

**Comment by MrMelbert** [comment]
I believe the real bug here is that space pirates can be targeted by sleeper agent, which is probably caused by the fact that space pirates aren't getting their pirate antag datums right now
