### ISSUE TITLE
AI Eye Meets Tram, Can't Lay Gaze Off It

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#63569]
Reporting client version: 514.1568

## Round ID:
[175259](https://scrubby.melonmesa.com/round/175259)

## Testmerges:
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)
- [test disables ai static to see if it helps maptick enough to justify a refactor of how it works](https://www.github.com/tgstation/tgstation/pull/63439)

## Reproduction:
Melbert volunteered to post some of the relevant round information and technical info as to what happened, but the gist of it is my eye got stuck on the Tramstation Tram. It kept being snapped back to the tram every time it moved, no matter where it placed.
For obvious reasons this completely halted my ability to actually play AI until admin help resolved the issue.

I /suspect/ - and I know I've been saying this a lot, because haha funny bug button when I could actually be contributing instead - this is due to me changing z-levels up onto the tram, but can't be certain.

I need to stop running into bugs man, my wordbank isn't robust enough for this

**Comment by MrMelbert** [comment]
When I checked, the AI's eye was still in the tram's loaded items, even if it left. So every time the tram moved, it moved the ai's eye.

It's quite possible their idea (changing z-levels on the tram) caused it, as moving vertically didn't count for moving off the tram.

**Comment by LemonInTheDark** [comment]
:sadkirby:

**Comment by TheBonded** [comment]
didn't this happen to ghosts too?

**Comment by LemonInTheDark** [comment]
Yes, it was an issue with how movement procs sent signals. I wonder if something similar is going on here

**Comment by TheBonded** [comment]
Wouldn't surprise me

**Comment by Justice12354** [comment]
Today, on Round ID 178917, something incredibly similar happened to the AI (P.A.P.A). I will provide a screenshot marking the exact spot where they were being pulled back to every time the Tram moved, in case it's useful. https://imgur.com/a/91hqlvX

**Comment by TheSilverNuke** [comment]
Replicated on round 180277

**Comment by zkxs** [comment]
Reproduced again.

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: 184733
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [d377eb2d1d6a0b83ca61b717b3854d9f19edde58](https://www.github.com/tgstation/tgstation/commit/d377eb2d1d6a0b83ca61b717b3854d9f19edde58)
The following pull requests are currently test merged:
[#67083: 'Completely removes `proc_holders` from existence. Refactors all wizard, xeno, spider, and genetics powers to be actions. Also refactors and sorts ton of accompanying code. ' by MrMelbert at commit b637e0b8ea](https://www.github.com/tgstation/tgstation/pull/67083)
[#65791: 'Optimizes Runechat' by Kylerace at commit 775d002c97](https://www.github.com/tgstation/tgstation/pull/65791)
[#67615: 'Fix Dynamic midrounds spawning heavies significantly earlier than they're supposed to' by Mothblocks at commit 28b5169054](https://www.github.com/tgstation/tgstation/pull/67615)
[#67669: 'Lemon attempts to optimize lighting [TM]' by LemonInTheDark at commit 9913284f94](https://www.github.com/tgstation/tgstation/pull/67669)
[#67116: 'TGUI Say: Upgrades chat input with modern features' by jlsnow301 at commit 8a34109f76](https://www.github.com/tgstation/tgstation/pull/67116)

Local commit: 531a8f9fe1bbf69300ac55a204bddffd1ee10e1c
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1

**Comment by LemonInTheDark** [comment]
@Kylerace

**Comment by Kylerace** [comment]
@LemonInTheDark it was fixed on the tram pr
