### ISSUE TITLE
Pyro anomalies don't make reactive incendiary armor

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#63578]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Put a pyro anomaly core into a reactive armor shell
Get stealth armor ????

I know it's been this way for a while but I was complaining about how reactive incendiary armor has existed for ages and just doesn't get used where it makes perfect sense to be used and someone told me to make an issue report so here were are.
![image](https://user-images.githubusercontent.com/44104681/147263881-e0a01134-3801-4f10-8823-d3fb29911e96.png)

**Comment by SuperNovaa41** [comment]
This is intended because the incendiary armour is awful

**Comment by TheBonded** [comment]
this was removed in https://github.com/tgstation/tgstation/pull/38370 in 2018, after some digging.
