### ISSUE TITLE
Cultists unable to view current status of cult

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#63597]
Reporting client version: 514.1569

## Round ID:
[175341](https://scrubby.melonmesa.com/round/175341)

## Testmerges:
- [Fix IPs in telemetry_connections not being unsigned](https://www.github.com/tgstation/tgstation/pull/63573)
- [Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)
- [Moves atmos checking from Fire Alarms to Fire Locks, Fire Locks now close on their own rather than area-based, a bunch of related stuff.](https://www.github.com/tgstation/tgstation/pull/62055)
- [Tgui list input hotfix + changes](https://www.github.com/tgstation/tgstation/pull/63515)
- [Move MouseEntered to a queue, such that only the most recently hovered atom will be processed](https://www.github.com/tgstation/tgstation/pull/63567)
- [Amortize the cost of creating preference assets by caching them per git revision on production, reducing best case init times by ~20 seconds](https://www.github.com/tgstation/tgstation/pull/63503)

## Reproduction:

Cultists are not able to view number of members currently alive. This results in a premature summons if they lack the numbers, even if halos are achieved. It does not show in either the antagonist panel or in the personal memories of the cultist. I've not tested this but I assume it's the same for revolutionaries. In the previous IC notes system it would show the status of the cult and revolution however it seems to be lacking here.

**Comment by JohnFulpWillard** [comment]
Not sure if this something I'd like to see brought back, Cultists/Revs innately knowing who their allies are is a pretty large advantage and I find it goes against the limitation of information meant to make SS13 a paranoia laden deathtrap.
