### ISSUE TITLE
Player who was denied via interview, proceeded to join and observe anyways

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63595]
## Round ID:

[175330](https://scrubby.melonmesa.com/round/175330)

## Reproduction:

- A player entered an interview featuring no responses. The admins online denied the interview, due to having no responses entered.
- After being denied, the player managed to observe the round anyways, bypassing the interview.

**Comment by bobbahbrown** [comment]
my initial guess is that this is related to #60953. i'll look into this more in a bit when i have some time this evening.

**Comment by Watermelon914** [comment]
they can also join as ghost roles

**Comment by Watermelon914** [comment]
@bobbahbrown this is still an issue by the way, had it happen on a recent terry round (round 184221)
