### ISSUE TITLE
Chemistry ducts layer above catwalks if you attempt cover them

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63590]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/147315121-862c3c53-bcf9-484a-8c2f-72f2165f180d.png)
![image](https://user-images.githubusercontent.com/51863163/147315250-e06e1511-918e-420f-91a6-5b19be3fe3b4.png)

- Have open plating.
- Place ducts.
- Place catwalks over the ducts.
- The ducts will appear over the catwalk anyways.

Chemistry ducts, which normally can under-tile like pipes or cables, don't layer underneath catwalks - they float above even if the catwalk is placed on top.

**Comment by timothymtorres** [comment]
My changes in #62875 might fix this.

**Comment by timothymtorres** [comment]
@MrMelbert can you retest this.  My changes should have been merged by now and I won’t have a home computer for another month.
