### ISSUE TITLE
Security Cam Inconsistency

### ISSUE THREAD

**Issue by jlsnow301** [tgstation/tgstation#63607]
## Round ID:
Current

## Testmerges:
Current

## Reproduction:
Adjacency checks for security cams (introduced by me in #63451) cause borgs to be unable to view cams from a distance.
It also does not apply to secureye, the tablet program.
Thx @SpookyTheFox for this bug report.

**Comment by LemonInTheDark** [comment]
Was this even really a bug? Seeing the content isn't a problem I wouldn't think, that's how all uis work. If there was a bug there it would be in interaction, but that doesn't seem to be the case anymore, and if it was it would be inside the ui state datums, rather then the console itself

@Mothblocks Am I missing some context here?

**Comment by jlsnow301** [comment]
(as we spoke previously) the primary issue is how ui_data is handled, normally things do not update at significant range but cameras are the exception as they use an overlay regardless
just adding this all for records keeping purposes
this is without a state check
![1](https://user-images.githubusercontent.com/42397676/147727275-b4821bc5-bb4a-48b4-ba8c-0660ecb669b4.png)
