### ISSUE TITLE
AIs in MODsuits can't use the abilities

### ISSUE THREAD

**Issue by Valenta019** [tgstation/tgstation#63608]
## Round ID: 
[175366](https://scrubby.melonmesa.com/round/175366)

## Testmerges:
https://github.com/tgstation/tgstation/pull/63573

## Reproduction:
I became a positronic brain, inserted into a shell. Laws got changed so only the one person was human. Then I got popped into an intelliCard. Inserted into a MODsuit. 
4 new ability buttons showed up, yet they did nothing. No chat responses, just nothing. They did however gray out when the person get horizontal.
I could however move with the uncounscious body, that worked.
I still had access to usual AI abilities, but anything camera related did not work. 
Also the suit doesn't provide vision so I was blind on the shuttle

**Comment by ZeroMODE0** [comment]
Temporary workaround: Have the suit on the ground first before putting the AI in, then you can open the modsuit interface and have partial functionality! When they put you on, you won't be able to press any buttons again, so don't close it out.
