### ISSUE TITLE
MODsuit bricked after being stripped

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#63617]
Reporting client version: 514.1571

## Round ID:
[175401](https://scrubby.melonmesa.com/round/175401)

## Testmerges:
- [test disables ai static to see if it helps maptick enough to justify a refactor of how it works](https://www.github.com/tgstation/tgstation/pull/63439)
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)
- [Untested: Fix outfit equipping not working](https://www.github.com/tgstation/tgstation/pull/63606)

## Reproduction:
![](https://i.imgur.com/k9V2tG4.png)

**Comment by jacklecroy** [comment]
Needs to deactivate when stripped or be able to deactivate without the parts equipped.
