### ISSUE TITLE
Modsuit Circuit Adaptor Module Circuit cannot be edited (as if its always out of range?)

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#63612]
Reporting client version: 514.1569

## Round ID:
[175390](https://scrubby.melonmesa.com/round/175390)

## Testmerges:
- [Moves atmos checking from Fire Alarms to Fire Locks, Fire Locks now close on their own rather than area-based, a bunch of related stuff.](https://www.github.com/tgstation/tgstation/pull/62055)
- [Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)
- [Tgui list input hotfix + changes](https://www.github.com/tgstation/tgstation/pull/63515)
- [Amortize the cost of creating preference assets by caching them per git revision on production, reducing best case init times by ~20 seconds](https://www.github.com/tgstation/tgstation/pull/63503)
- [[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety](https://www.github.com/tgstation/tgstation/pull/63588)

## Reproduction:
1. Print Modsuit Circuit Adaptor Module (Comes with builtin circuit that you cannot take out)
2. Use circuit Multi tool on the Modsuit Circuit Adaptor to access the circuit
3. The breadboard is completely greyed out and cannot be edited and if you happen to have telekinesis your chat will be spammed with "Your mind cannot reach that far" until you close the breadboard menu, regardless of the Adaptor being in your hand or directly next to you.

Another thing I`ve noticed is you can insert a bci action button circuit module into the adaptor and if you hold the adaptor in your hand the button will show up on your HUD, not sure if this is intended since it seems like something that should only show up when the adaptor is installed in a suit that you are wearing.

**Comment by WarlockD** [comment]
Yea replicated this in Campbell.  I motioned myself printed everything new and still did the same thing.  Going to try to look into it if somone else doesn't push it sooner.
