### ISSUE TITLE
Cardborg helmet sprites broke

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#63610]
Reporting client version: 514.1568

## Round ID:
[175374](https://scrubby.melonmesa.com/round/175374)

## Testmerges:
- [Moves atmos checking from Fire Alarms to Fire Locks, Fire Locks now close on their own rather than area-based, a bunch of related stuff.](https://www.github.com/tgstation/tgstation/pull/62055)
- [Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)
- [Tgui list input hotfix + changes](https://www.github.com/tgstation/tgstation/pull/63515)
- [Amortize the cost of creating preference assets by caching them per git revision on production, reducing best case init times by ~20 seconds](https://www.github.com/tgstation/tgstation/pull/63503)
- [[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety](https://www.github.com/tgstation/tgstation/pull/63588)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/147374277-112c952e-aefe-4189-aec8-1b5958fc775c.png)
![image](https://user-images.githubusercontent.com/66640614/147374287-7cbd80f0-2b31-4f66-a781-7a270d6a9cf8.png)

**Comment by necromanceranne** [comment]
I think they got deleted in https://github.com/tgstation/tgstation/pull/59109

**Comment by dragomagol** [comment]
Will be fixed by #63613
