### ISSUE TITLE
MODSUITS LEAVE MINERS IN THE DUST

### ISSUE THREAD

**Issue by mixzombie** [tgstation/tgstation#63631]
Are you really telling me it was intended that Miners would lose access to ther hardsuits with High Defense? 

This update Removes Access from Miners to the suits previously available. 

Every Other Department Does Not Lose Access to their suits why only miners?

**Comment by tralezab** [comment]
Who mined with hardsuits in the year of our lord and savior plus 2021. Either way, this is more feedback and less "bug or oversight". Take it to the feedback thread: https://tgstation13.org/phpBB/viewtopic.php?p=623101#p623101
