### ISSUE TITLE
MODsuit stabilised red interaction broken (possibly all stabilised slime cores)

### ISSUE THREAD

**Issue by tf-4** [tgstation/tgstation#63634]
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
Get stabilized red. Put in modsuit storage,
Stabilized red does not give you the slowdown removal when in the storage of a modsuit. Probably all stabilized cores are broken in there.

**Comment by Sealed101** [comment]
the xenobio nerf we've all been waiting for

**Comment by newfren** [comment]
I noticed my stabilised pink wouldn't work unless I was holding it when I had a modsuit earlier

**Comment by SuperNovaa41** [comment]
![2021-12-26_15:41:07_%](https://user-images.githubusercontent.com/16159590/147419549-44e8bfd3-3070-4fd2-84d3-c7f7539b4a42.png)

**Comment by Fikou** [comment]
> ![2021-12-26_15:41:07_%](https://user-images.githubusercontent.com/16159590/147419549-44e8bfd3-3070-4fd2-84d3-c7f7539b4a42.png)

thats speed potion interaction, stabilised red is a consequence of how storage items work, i think stabilised extracts look for your first layer of storage, modsuits use a storage component of another item (the storage module), so technically they are a second layer of storage

**Comment by TheSilverNuke** [comment]
Temporary workaround is to just put it in your pocket, since it is a part of that first layer.
