### ISSUE TITLE
Song editor runtime

### ISSUE THREAD

**Issue by jlsnow301** [tgstation/tgstation#63646]
## Round ID:

Local
## Testmerges:
Local

## Reproduction:
Editing any of the values in the song editor runtimes at asset_transport.dm. Null client.
It should be of note that I encountered this runtime and switched to plain inputs instead of TGUI, which also runtime.

**Comment by timothymtorres** [comment]
Is this for the musical instruments or the admin command to play midis?

**Comment by jlsnow301** [comment]
musical instruments, just tried changing a setting on the space piano,
```Debug Server: "Pausing execution (reason: Runtime(\"Invalid argument: client: ``\"))"```
