### ISSUE TITLE
Implanted Cult Sacrifice doesnt get sharded

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#63642]
## Round ID:
[175503](https://scrubby.melonmesa.com/round/175503)

## Testmerges:

#63588

## Reproduction:

Observed:

- Implanted Person got killed and Sacrificed (Exploded)
- The Brain still had their Soul and the Shard was dead
- They were able to get revived with a head transplant

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/6a8ad0ccd38b569d9f8d1158a1debdd374b33401/code/modules/antagonists/cult/runes.dm#L339-L348

https://github.com/tgstation/tgstation/blob/4dbe04013fdd31f711d5d4e41beb31f5e1f8ab9a/code/modules/antagonists/wizard/equipment/soulstone.dm#L255-L276

**Comment by timothymtorres** [comment]
So after code diving the mind implanted mob gets dusted first to make the soul stone shade and their soul is transferred.  However, their (nonexistent) body then gets gibbed, creating organs and the brain.  

Since gibbed() is called, their mind gets transferred to the brain.
