### ISSUE TITLE
Tend wounds surgery can be initiated on healable mobs but can't be continued

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#63649]
local testing done after a recent round in which i was a sad hurt magicarp

## Reproduction:
Trying to start a surgery on a simple mob that has the `healable` var set to TRUE will let you place the drapes on the mob, but trying to make an incision will result in you stabbing the mob.

**Comment by JohnFulpWillard** [comment]
I thought surgeries on simplemobs were just to do core removal surgery on slimes, does that work?

**Comment by Sealed101** [comment]
slime core removal works fine

**Comment by Sealed101** [comment]
clearly the modsuits are at fault

**Comment by SuperNovaa41** [comment]
Cannot reproduce
