### ISSUE TITLE
Some MODsuit pieces make you appear as if you aren't wearing certain clothes

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63659]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/147514330-0b8172c7-5cef-49d6-b9ed-0724a73cca1f.png)

- Be a nuke op, wearing combat gloves and boots. 
- Equip your blood red MODsuit, OVER your gloves and boots. (Don't activate it - just deploy the parts)
- It now looks like you're wearing no shoes and no gloves. 

![image](https://user-images.githubusercontent.com/51863163/147514617-b61a5922-91e5-419f-ace8-7f21e2204a77.png)

- Activate the MODsuit now and toggle armor boosters.
- Now, it looks as if you've got no gloves.

![image](https://user-images.githubusercontent.com/51863163/147514415-8eeca809-83d8-4eca-81e0-7e2335fff779.png)

- Purchase an elite MODsuit instead.
- Equip the elite MODsuit, OVER your gloves. (Don't activate it)
- It now appears as if you are not wearing gloves at all, despite previously wearing combat gloves

![image](https://user-images.githubusercontent.com/51863163/147514695-13992ed5-0ed3-42de-bf4e-341d314be0ca.png)

- Activate the MODsuit now and toggle armor boosters.
- Now, it looks as if you've got no gloves, and a lil' lacking in the pants department.

**Comment by Fikou** [comment]
thats intended to show the modsuits losing their spaceproofness, unless someone makes a better looking sprite i dont know what you want me to do
