### ISSUE TITLE
The mod suit announcement in chat upon joining a server is doubled.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#63657]
Reporting client version: 514.1566

## Round ID:
[175555](https://scrubby.melonmesa.com/round/175555)

## Testmerges:
- [TGUI list conversions + bug fixes](https://www.github.com/tgstation/tgstation/pull/63354)
- [Amortize the cost of creating preference assets by caching them per git revision on production, reducing best case init times by ~20 seconds](https://www.github.com/tgstation/tgstation/pull/63503)
- [Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)
- [Moves atmos checking from Fire Alarms to Fire Locks, Fire Locks now close on their own rather than area-based, a bunch of related stuff.](https://www.github.com/tgstation/tgstation/pull/62055)

## Reproduction:
1. Log onto server.
2. Look at chat.
3. Notice two modsuit announcements bracketing the "servers are on fire" message.

**Comment by LemonInTheDark** [comment]
admin issue I think, depends on how they setup the messages

**Comment by dragomagol** [comment]
This was a config issue yeah. I believe I fixed this today, so let me know if it's still there.

**Comment by Mooshimi** [comment]
![image](https://user-images.githubusercontent.com/85910816/147591819-0ab550df-4778-4d5c-b31a-f4fff28233b2.png)
