### ISSUE TITLE
Statues of light sources can emit light.

### ISSUE THREAD

**Issue by neopythagorean** [tgstation/tgstation#63653]
![statues_two](https://user-images.githubusercontent.com/12129109/147500593-7a1d8b59-86a1-4365-8a4f-f50323d61857.PNG)

(Pictured: three statues, two of a person wearing a light source, one of a PDA with its flashlight on)

## Reproduction:

1. Turn on a light source (can even be a person wearing a light).
2. Create a statue with the light source as the target.
3. The statue emits bugged light.

**Comment by timothymtorres** [comment]
Tested this just now and can confirm it still exists.  The statues appearance shows the light overlay, but it doesn't actually emit light.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/423404b31e36c4605faacec881b324db8997b0a6/code/modules/art/statues.dm#L537-L570

What's strange to me is that this should have been fixed via #66003 and the flashlight lighting overlay is from the `O_LIGHTING_VISUAL_PLANE` which should have been removed:


https://github.com/tgstation/tgstation/blob/57755aa276db870119a4a2efffdfb8d41a97fc23/code/datums/components/overlay_lighting.dm#L74-L96
