### ISSUE TITLE
Communnications console tooltips are cut off

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63663]
Reporting client version: 514.1568

## Round ID:
[175568](https://scrubby.melonmesa.com/round/175568)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/147519719-ab0c10a1-fdb5-4c0c-b56a-bd8eb8b28140.png)

- Try to see why you can't buy a shuttle
- Tooltip explaining why is cut off and can't be seen

**Comment by newfren** [comment]
dupe of #62336
