### ISSUE TITLE
Service bots at bar won't take the drinks I serve them

### ISSUE THREAD

**Issue by Gamerwithfries** [tgstation/tgstation#63667]
## Round ID:
[175582](https://scrubby.melonmesa.com/round/175582)

## Reproduction:
When I give the service bots the drinks they want, they won't drink them and I had the same thing happen another round where I played chef. I don't know why it does this because it worked fine last round and turning the service portal on and off doesn't fix it.

**Comment by Mooshimi** [comment]
Could we have some details like: How many u were in the glasses, what type of container did you use?

**Comment by Sealed101** [comment]
a) no reproduction details
b) https://github.com/tgstation/tgstation/pull/78611 would have probably straightened out the customer bots enough
