### ISSUE TITLE
Ablative Coat straight up gives no sechud now, it seems

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63668]
Reporting client version: 514.1568

## Round ID:
[175581](https://scrubby.melonmesa.com/round/175581)

## Reproduction:

probably, related to #63524 .
![image](https://user-images.githubusercontent.com/51863163/147541484-5dd53733-ec09-419d-bd7d-8bbae7292a3c.png)
![image](https://user-images.githubusercontent.com/51863163/147541498-19a5fdc1-e774-4edb-9567-3802003ca868.png)

**Comment by SuperNovaa41** [comment]
worked perfectly on my local... did you get this by just putting the hood on @MrMelbert ?

**Comment by SuperNovaa41** [comment]
nvm
