### ISSUE TITLE
You can remove the gas mask nerf with recharging stations

### ISSUE THREAD

**Issue by Valenta019** [tgstation/tgstation#63677]
Reporting client version: 514.1568

## Round ID:
[175612](https://scrubby.melonmesa.com/round/175612)

## Testmerges:
- [[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety](https://www.github.com/tgstation/tgstation/pull/63588)

## Reproduction:
You know the latest nerf to the gas masks which makes you unable to look behind you?
Just enter a recharging station and exit it, this removes the limitation!

**Comment by Livrah** [comment]
Feature.
