### ISSUE TITLE
Kilo lets carp spawn in asteroid tiles if they're in space

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#63673]
Reporting client version: 514.1569

## Round ID:
[175605](https://scrubby.melonmesa.com/round/175605)

## Testmerges:
- [[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety](https://www.github.com/tgstation/tgstation/pull/63588)

## Reproduction:

1. spam spawn the carp event
2. this will happen eventually

![image](https://user-images.githubusercontent.com/80979251/147591444-faa97a42-6a34-4b25-b0b8-dc98be75bb4d.png)

**Comment by IndieanaJones** [comment]
Considering carp only spawn on invisible markers that the map maker has to manually place out in space, chances are there's a marker erroneously placed under that rock.

**Comment by EOBGames** [comment]
Having taken a look at that location (which was _really_ hard based on trying to find a collection of 16 tiles, please provide a larger screenshot with more context in future), I can't see a carp spawnpoint on that tile. Additionally looking at the code I can't see any reason it would be spawning there.

**Comment by Mooshimi** [comment]
https://github.com/tgstation/tgstation/blob/06cd9086eb2f1d1927152d1ef441906b9665e538/code/modules/events/carp_migration.dm#L32-L40
<details><summary>Relevant mapping locations on kilo:</summary>
<img src="https://user-images.githubusercontent.com/85910816/183345019-9ebbeb33-8749-413b-8ba0-110d3a21aadb.png">
<img src="https://user-images.githubusercontent.com/85910816/183345055-ef22db4e-2742-4534-9e93-f74a530a3ca2.png">
<img src="https://user-images.githubusercontent.com/85910816/183345076-bf69a806-874a-437e-958e-3312cbb1d46a.png">
<img src="https://user-images.githubusercontent.com/85910816/183345099-23dc4b92-ef17-4c96-a764-fe907cdf7378.png">
</details>
