### ISSUE TITLE
Modsuit Malfunctioning circumvented through HUD button

### ISSUE THREAD

**Issue by metalyc** [tgstation/tgstation#63709]
## Round ID:
N/A, testing in private server

## Reproduction:
Cut or pulse the malfunctioning wire (red light) to be off (default: blinking).  Interface will show "Status: Malfunctioning" and no longer activate through "MOD Interface Panel", giving "button malfuctions".  

However this doesn't effect the HUD button "Activate MODsuit".  

I believe the "Activate MODsuit" HUD button should match the "MOD Interface Panel" button; not function when status is "Malfunctioning"

**Comment by tralezab** [comment]
confirmed to be an oversight by fik
