### ISSUE TITLE
Double Nar'Sie

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#63724]
Reporting client version: 514.1569

## Round ID:
175755

## Testmerges:
- [Amortize the cost of creating preference assets by caching them per git revision on production, reducing best case init times by ~20 seconds](https://www.github.com/tgstation/tgstation/pull/63503)
- [Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)
- [TGUI list conversions + bug fixes](https://www.github.com/tgstation/tgstation/pull/63354)

## Reproduction:

Creating two Nar'Sie runes at the same time and then summoning with enough members on both runes creates two incarnations of Nar'Sie:

![2021-12-31 13_25_39-](https://user-images.githubusercontent.com/36066032/147838287-6b1510dc-1afd-4431-8f7c-5c0755cb4d95.png)

**Comment by SuperNovaa41** [comment]
how have we gone this long

**Comment by JohnFulpWillard** [comment]
Without removing cult? I don’t know but it’s surprising.

**Comment by TheSilverNuke** [comment]
Here's a video of the process in question. Thanks Carl!

https://www.youtube.com/watch?v=BmCszMXWoDM

**Comment by Mooshimi** [comment]
This is a feature now isn't it.... it's a beloved thing...

**Comment by Mothblocks** [comment]
make it an achievement
