### ISSUE TITLE
SM to waste is sometimes bad and sometimes unusable

### ISSUE THREAD

**Issue by Edelor68** [tgstation/tgstation#63725]
How it is on round start Icebox
![SMtoWasteOld2](https://user-images.githubusercontent.com/85312201/147837502-c233aab9-5e24-40ae-a7f3-559ade295700.png)
How it should be
![SMtoWasteNew2](https://user-images.githubusercontent.com/85312201/147837504-4d999ad7-94f8-453c-a878-8728237953a8.png)
^This is the setup on icebox and at the moment what happens is when you open that valve is that you dump all of waste outside.
What it should do is pipe the usable gases into waste for repurposing and if the pressure is too high open the valve to release pressure, which you use the reversed pressure gate for NOT the temperature gate.

Round start Delta
![SMtoWasteOld](https://user-images.githubusercontent.com/85312201/147837506-71003cda-564d-4f77-a977-a682be07f201.png)
This setup is not wrong just not optimal. The pressure gate is not a pump so it won't do anything because the pressure in waste is nearly always higher than the pressure in the SM waste so we need a second pump behind it or just a pump. The digital valve has to be manually opened when the SM fails and a reversed pressure gate is just much more practical here.
Improved
![SMtoWasteNew](https://user-images.githubusercontent.com/85312201/147837507-a027be2d-2ddf-42b9-a579-db7b3bd0e925.png)

**Comment by SuperNovaa41** [comment]
Yes the initial setups are always poor to incentivize engineers to do their job.
