### ISSUE TITLE
(Some) cleaner grenades seem to no longer react

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63733]
## Round ID:
[175768](https://scrubby.melonmesa.com/round/175768)

## Reproduction:

Some cleaning grenades will occasionally be primed, but not do anything, and simply un-prime instead of detonating.

**Comment by TemporalOroboros** [comment]
Grenades no longer delete themselves on use. You might have picked up a used one.

**Comment by LemonInTheDark** [comment]
They should prob have a tell for that then, least I'd think

**Comment by MrMelbert** [comment]
Ahh, yeah they probably shouldn't look like normal grenades after use then

**Comment by LemonInTheDark** [comment]
@MrMelbert I think it's still an issue, just not the one you reported.
