### ISSUE TITLE
Juggernauts don't fall

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#63737]
Reporting client version: 514.1569

## Round ID:
[175786](https://scrubby.melonmesa.com/round/175786)

## Reproduction:

Juggernauts don't fall down z-levels. Not sure if oversight or bug.
![2022-01-01 01_06_03-Window](https://user-images.githubusercontent.com/36066032/147846639-e56398dd-9fd1-4fe6-ac41-99377d1723df.png)

**Comment by Sealed101** [comment]
every cult construct is flying and thus ignore gravity, this is fine
