### ISSUE TITLE
Ghosts are able to tamper with MOD suits

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#63736]
Reporting client version: 514.1569

## Round ID:
[175783](https://scrubby.melonmesa.com/round/175783)

## Reproduction:

Observe person with suit, drag suit off of back into hand, laugh as they experience hearing loss. Alternatively if the suit isn't active and just present on their back you can put it in their hand.

**Comment by cocothegogo** [comment]
ok this is epic
