### ISSUE TITLE
Sentient Disease isn't doing the Voluntary Coughing right

### ISSUE THREAD

**Issue by DragonTrance** [tgstation/tgstation#63764]
Round ID: [175821](https://scrubby.melonmesa.com/round/175821)

## Reproduction:
I infected a person with a cigar, I couldn't use Voluntary Coughing. I don't know if this is specifically because of the cigar in their mouth or that sentient disease just doesn't work all the sudden

**Comment by EricZilla** [comment]
Can confirm, rolled sentient disease in round 176048 and couldn't cough so I was stuck in gay baby jail for the entire round

**Comment by dragomagol** [comment]
Still an issue
