### ISSUE TITLE
Kilostation Space had an edge to it

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#63773]
## Testmerges:
The following pull requests are currently test merged:
#63666: 'makes ai static into images added to obscured turfs to save on maptick' by Kylerace at commit ca921c5324
#63331: 'Revert "Require Node 16"' by MrStonedOne at commit 3bccf7f8c1
#63750: 'lowers kilo's bombcap multiplier' by Fikou at commit 16e2d0383d

## Reproduction:
https://puu.sh/IA0wy/236c3f8c7b.png
fly to the edge of space in kilostation on this particular shift
????????
even if there were no z-levels left-right or up-down there still shouldn't have been a corner

teleporting to the abandoned teleporter worked, and space travel between z-levels from that starting location worked, but not on the station z-level.

**Comment by Maurukas** [comment]
Fixed in #65183 - This should have handled all linkage issues on Kilo.
