### ISSUE TITLE
Rat King abilities dont work

### ISSUE THREAD

**Issue by Hafahya** [tgstation/tgstation#63779]
## Round ID:[175880](https://scrubby.melonmesa.com/round/175880)
Terry

## Reproduction:
Rat king abilities dont work, became a rat via changepool, was used royal cheese on , became a king, abilities appeared. When pressed they do nothing. While ahelping talked to a played that changepool'ed into a dragon, who said they also were a ratking sometime ago, and that their abilities also didnt work

**Comment by SuperNovaa41** [comment]
Duplicate of https://github.com/tgstation/tgstation/issues/63758
