### ISSUE TITLE
Objects on Lower Z level appearing on top Z level

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#63770]
## Testmerges:
The following pull requests are currently test merged:
#63666: 'makes ai static into images added to obscured turfs to save on maptick' by Kylerace at commit ca921c5324
#63331: 'Revert "Require Node 16"' by MrStonedOne at commit 3bccf7f8c1
#63750: 'lowers kilo's bombcap multiplier' by Fikou at commit 16e2d0383d

## Reproduction:
https://puu.sh/IzZsI/c660dbfe94.png
be in tram's cargo bay
what are these funny things doing here

**Comment by timothymtorres** [comment]
This might be related to #62875.  I suspect that the wall-mounted objects on the lower z-level are being drawn on the top portion.

**Comment by timothymtorres** [comment]
@newfren Can you rename the title to be "Objects on Lower Z level appearing on top Z level" 

I have a feeling there will be many more bug reports related to this that will be duplicates until I can get this fixed.
