### ISSUE TITLE
Ghost bobbing up and down animation is missing

### ISSUE THREAD

**Issue by coldud13** [tgstation/tgstation#63792]
Reporting client version: 514.1570

## Round ID:
[175918](https://scrubby.melonmesa.com/round/175918)

## Testmerges:
- [[DNM] Reference Tracking on Live Again Again](https://www.github.com/tgstation/tgstation/pull/63388)
- [lowers kilo's bombcap multiplier](https://www.github.com/tgstation/tgstation/pull/63750)

## Reproduction:
As a ghost, the bobbing up and down animation only plays once, it doesn't repeat.

You can see this upon initially observing, or by double clicking an object (to orbit it), then exit that orbit. The ghost will bob upwards for a few pixels and then stop.

**Comment by SuperNovaa41** [comment]
Related to https://github.com/tgstation/tgstation/issues/61718
