### ISSUE TITLE
Clicking cancel on TGUI succumb kills you anyways

### ISSUE THREAD

**Issue by SuperNovaa41** [tgstation/tgstation#63802]
## Round ID: 
local

## Testmerges:
n/a

## Reproduction:
1. Be in crit
2. Click deathgasp
3. Change your mind, and click cancel
4. succumb anyways

**Comment by JenqaDev** [comment]
![image](https://user-images.githubusercontent.com/43709941/147975494-020972f5-7509-49ad-8304-7a10fd366286.png)
