### ISSUE TITLE
Lizards cannot use DNA injectors

### ISSUE THREAD

**Issue by DragonTrance** [tgstation/tgstation#63818]
## Round ID: [175967](https://scrubby.melonmesa.com/round/175967)

I was wondering why I wasn't getting any messages from using DNA injectors. I used Insulated on myself then stuck something small into a light fixture, and I got shocked from it.

![image](https://user-images.githubusercontent.com/26515331/148000516-97fa0756-7c03-4967-a400-54d1ca45d8e4.png)
![image](https://user-images.githubusercontent.com/26515331/148000547-9783613a-a1ca-4638-aeb3-5a0e93d64829.png)
![image](https://user-images.githubusercontent.com/26515331/148000568-5bd7c7aa-2f3e-42bd-a369-4d4b1bfa5214.png)

![image](https://user-images.githubusercontent.com/26515331/148000815-04ec3004-a435-427d-83b1-6da444a25e69.png)

**Comment by moocowswag** [comment]
Did you have insulated as an actavate-able mutation in you?

**Comment by DragonTrance** [comment]
Im being smoothbrained as shit rn
I played genetics a lot and didnt bother checking if I had been using the activators or mutators because I hadnt been doing genetics recently
