### ISSUE TITLE
Player that entered a disposals pipe got deleted

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#63815]
Reporting client version: 514.1575

## Round ID:
[175960](https://scrubby.melonmesa.com/round/175960)

## Testmerges:
- [Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)
- [Adds two new Service jobs to the game: The Barber and The Tailor](https://www.github.com/tgstation/tgstation/pull/63800)

## Reproduction:
From a player: 
So I went into the chute in permabrig that's used to throw in prisoners without needing to walk in. The exit tube had already been eaten by the blob. I stopped where the exit was briefly and was then immediately ghosted. No body at all.
Possibly from #63500

**Comment by Robustitron** [comment]
This just happened to me in round 176743 on sybil.

I got stuck in a disposal trap, when the captain welded the pipe to get me out, I was deleted and became a ghost.

**Comment by Kylerace** [comment]
that round of sybil didnt appear to have this tm so most likely from something else

**Comment by LemonInTheDark** [comment]
Fixed in all forms now.
