### ISSUE TITLE
Psychologist Consistency Error

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#63853]
Reporting client version: 514.1571

## Round ID:
[176038](https://scrubby.melonmesa.com/round/176038)

## Testmerges:
- [lowers kilo's bombcap multiplier](https://www.github.com/tgstation/tgstation/pull/63750)
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)
- [makes ai static into images added to obscured turfs to save on maptick](https://www.github.com/tgstation/tgstation/pull/63666)

## Reproduction:
All the medicines the psychologist spawns with come at 100% purity EXCEPT for the Mindbreaker Toxin, which comes in at 75% purity. Whether all the others are reduced to 75% or the Mindbreaker is brought up to 100%, I think all the chems they spawn with should be the same quality. To reproduce, join as Psychologist. If you get a Chemistry Analyser, you can scan the pills you spawn with directly to check the purity of their contents. In the bottle labeled "mindbreaker toxin pills", the pills labeled "antipsychotic pill (5u)" should report 75% pure Mindbreaker Toxin.

**Comment by SuperNovaa41** [comment]
balance
