### ISSUE TITLE
Unable to use "Cough" as sentient disease

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#63857]
## Round ID:
[176059](https://scrubby.melonmesa.com/round/176059)

## Testmerges:
#63750
#63331
#63666

## Reproduction:

> Be disease and choose your target
> Realize the Button to Cough does nothing
> Be salty in D-Chat

**Comment by SuperNovaa41** [comment]
Duplicate of https://github.com/tgstation/tgstation/issues/63764
