### ISSUE TITLE
Glass floors have openspace set as their baseturf, even if the map isn't multi-z / openspace does not function

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63868]
## Round ID:

[176080](https://scrubby.melonmesa.com/round/176080)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/148299786-0f183915-7cdf-443c-a0d5-14e4bb054569.png)

The baseturf for glass floors and reinforced glass floors is `/turf/open/openspace`. 
This is logical for multi-z maps - removing a glass floor results in a hole. 
This is not as logical for non-multi-z maps - removing a glass floor _should_ logically result in space, but instead results in open-space, which is non-functional if the map is not multi-z. (It does not vent the room due to a breach, people do not fall stepping over it, it cannot be examined.)

Related issue: #63548.

**Comment by timothymtorres** [comment]
Pretty sure this was caused by my PR in #63770
