### ISSUE TITLE
Revenant telepath messages doesn't work

### ISSUE THREAD

**Issue by Amrabol** [tgstation/tgstation#63874]
## Reproduction:
So i got revenant for exchange of sentient disease(that is broken currently too). Tried to make some chaos by sending mean messages to people. After selecting target no other window appears. Admin confirmed that no messages was showing for that person. Told to disable tgui. That did not worked either

**Comment by Ryusenshu** [comment]
Can Confirm
Round: 176097
I was unable to write a message after selecting a target

**Comment by MrDoomBringer** [comment]
This also seems to be affecting the 'Telepathy' mutation or whathaveyou
