### ISSUE TITLE
Checking your mood with TK STILL gives you a balloon alert that you can't reach it

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63873]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/148320317-699f250e-d140-4c14-8bca-dbaa061e5430.png)

After #63493

**Comment by SuperNovaa41** [comment]
what the FUCK

**Comment by SuperNovaa41** [comment]
i literally tested it

**Comment by SuperNovaa41** [comment]
nvm
