### ISSUE TITLE
Taking off a medhud (item) doesn't remove the HUD (screen element)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63872]
Reporting client version: 514.1568

## Round ID:
[176088](https://scrubby.melonmesa.com/round/176088)

## Testmerges:
- [[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety](https://www.github.com/tgstation/tgstation/pull/63588)
- [makes hud images only show to mobs on the same z level to save on maptick](https://www.github.com/tgstation/tgstation/pull/63558)

## Reproduction:

- Equip medical hud
- Change z levels
- Remove medical hud
- Still have the health bar above your head

![image](https://user-images.githubusercontent.com/51863163/148313382-79faaf37-0b6d-469c-885d-0d190cfd4684.png)

**Comment by MrMelbert** [comment]
possibly caused by #63558 since it touches huds?

**Comment by LemonInTheDark** [comment]
@Kylerace

**Comment by Kylerace** [comment]
cant replicate this

**Comment by Kylerace** [comment]
nm you need to move z levels for it to break

**Comment by Kylerace** [comment]
should be fixed
