### ISSUE TITLE
Anyone can lock/unlock a medbot

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#63894]
Reporting client version: 514.1575

## Round ID:
[176154](https://scrubby.melonmesa.com/round/176154) 

## Testmerges:
- [[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety](https://www.github.com/tgstation/tgstation/pull/63588)
- [Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)
- [Ports flying bloodsplatters from Hippie for Wounds](https://www.github.com/tgstation/tgstation/pull/63140)

## Reproduction:
Before, only roboticists (and the RD) could lock or unlock a medbot. Now it seems like anyone can.

**Comment by SuperNovaa41** [comment]
Probably caused by https://github.com/tgstation/tgstation/pull/62748

**Comment by SuperNovaa41** [comment]
Okay so a little testing, i could unlock it as: a doctor, CMO, a scientist, robo, geneticist and RD. None of the other jobs i tested could unlock them

**Comment by SuperNovaa41** [comment]
Seems to be working perfectly fine. I imagine this is just a quirk of the ID system as regular scientists have `ACCESS_ROBOTICS` listed under extra access. Aswell... all people in med have `ACCESS_MEDICAL` which is all thats added extra into medbots.
