### ISSUE TITLE
Flashbangs stun you in the void where there is no sound

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#63893]
Reporting client version: 514.1569

## Round ID:
[176154](https://scrubby.melonmesa.com/round/176154)

## Testmerges:
- [[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety](https://www.github.com/tgstation/tgstation/pull/63588)
- [Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)
- [Ports flying bloodsplatters from Hippie for Wounds](https://www.github.com/tgstation/tgstation/pull/63140)

## Reproduction:

Trigger flashbang in space, get stunned despite being nowhere near.

**Comment by SuperNovaa41** [comment]
This would be very easy to implement, however sound is currently not intended to deaden in space.

**Comment by Kylerace** [comment]
valid issue
