### ISSUE TITLE
Issue with the terminals

### ISSUE THREAD

**Issue by Wolfiesty** [tgstation/tgstation#63907]
Whenever I try to access an item that uses nanotrasen, it gives me an error. To be exact, it says

"A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation."

It also does not provide any stack trace to send. I'm using the program through Wine on Ubuntu, so if that's the main issue then please let me know how to go about fixing it. Thank you.

**Comment by SuperNovaa41** [comment]
It's probably just due to the fact you're using Wine. TGUI has massive issues when using wine, and as of now im fairly certain theres nothing you or we can do to fix it.

**Comment by Wolfiesty** [comment]
Ah okay. Thank you very much.
