### ISSUE TITLE
Antag huds consistently don't work

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#63901]
## Round ID:

[176166](https://scrubby.melonmesa.com/round/176166)
Most recent Manuel rounds?

## Testmerges:

- [makes hud images only show to mobs on the same z level to save on maptick](https://www.github.com/tgstation/tgstation/pull/63558)

## Reproduction:

All antag huds consistently don't work.
Admin antag hud shows no antagonists - no traitors, revolutionaries, cultists, changelings, nothing
Team antag huds don't show any team-members for anyone involved, causing a large amount of confusion (especially on revolutionary rounds)
 
This has happened on both multi-z maps (icebox) and non-multi-z maps (deltastation)

**Comment by MrMelbert** [comment]
Labeling test merge issue as it may be caused by the hud image testmerge

**Comment by Kylerace** [comment]
should be fixed

**Comment by MrMelbert** [comment]
(it's not)
