### ISSUE TITLE
MOD Eating Apparatus Doesn't Work

### ISSUE THREAD

**Issue by SkeletalElite** [tgstation/tgstation#63904]
Reporting client version: 514.1575

## Round ID:
[176175](https://scrubby.melonmesa.com/round/176175)

## Testmerges:
- [[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety](https://www.github.com/tgstation/tgstation/pull/63588)
- [Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)
- [Ports flying bloodsplatters from Hippie for Wounds](https://www.github.com/tgstation/tgstation/pull/63140)

## Reproduction:
You cannot eat in a modsuit with this module installed that is supposed to let you eat in the mod suit

**Comment by SuperNovaa41** [comment]
Fixed in https://github.com/tgstation/tgstation/pull/63836, server probably just hasn't updated
