### ISSUE TITLE
External organs falling out of non-humans 

### ISSUE THREAD

**Issue by TattoMoon** [tgstation/tgstation#63915]
## Reproduction:

Non-Human characters like moth people and lizard people will lose their wings, horns, frills, and spines upon certain body parts spilling organs. For moth people, should the chest take enough damage to spill out organs it will also spill out the external organ, or the wings. For lizard people, should the head be removed and opened, the frills and horns vanish, and if the chest spills organs, the spines will also spill. In most situations, you can shift+right to pick up the organ, which has no visual icon. If the target is gibbed or heretic sacrificed, the external organs in the chest are deleted. 

![unknown (12)](https://user-images.githubusercontent.com/94944115/148625958-78269197-bff8-4923-a419-3d23fad4cd67.png)

**Comment by TattoMoon** [comment]
I was incorrect for the lizard part, it would appear. The only time an external organ will fall out of them is when they mutate H.A.R.S. In which case, the frills, and horns will vanish, and the organ will be deleted.

**Comment by Time-Green** [comment]
This was fixed since they got their own icons
