### ISSUE TITLE
pressure resistance genetic power + a spacesuit results in no pressure resistance

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#63924]
## Testmerges:
The following pull requests are currently test merged:
#63331: 'Revert "Require Node 16"' by MrStonedOne at commit 3bccf7f8c1
#63750: 'lowers kilo's bombcap multiplier' by Fikou at commit 16e2d0383d
#63558: 'makes hud images only show to mobs on the same z level to save on maptick' by Kylerace at commit 00169e3269

## Reproduction:
Give yourself pressure resistance (I did it while wearing the spacesuit, via injection into my head)
enter space wearing a space suit
take brute damage
be very mad

I tried without the space helmet with the suit and that took damage, but just the mutation + coffee took no damage

**Comment by SuperNovaa41** [comment]
Could not reproduce. Are you sure you didn't have temperature resistance?

**Comment by newfren** [comment]
yes, without coffee I would get cold immediately in space.

**Comment by newfren** [comment]
Also, if I had temperature resistance I would not take damage from wearing an eva suit while in space, nor would I avoid pressure damage from entering space with no suit.

**Comment by SuperNovaa41** [comment]
ok, lmk if this happens again to you ill take off the cleanup flagged.
