### ISSUE TITLE
cant make money with cargo

### ISSUE THREAD

**Issue by tgent007** [tgstation/tgstation#63921]
## Round ID:
[176217](https://scrubby.melonmesa.com/round/176217)

## Testmerges:
- [[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety](https://www.github.com/tgstation/tgstation/pull/63588)
- [Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)
- [Ports flying bloodsplatters from Hippie for Wounds](https://www.github.com/tgstation/tgstation/pull/63140)

## Reproduction:

Scan a bounty cube with an export scanner and send it, no money is earned you ALSO do not get a cut from a sales tagger anymore.

**Comment by ArcaneMusic** [comment]
Could use a more descriptive title and definition, but I've been hearing this quite a bit as well.
Diagnosing the issue to determine what change broke this seems like it's either rooted to:
A. The Pricetag component (seems slightly more unlikely)
B. The Shuttle itself (My current bet)

**Comment by tgent007** [comment]
> Could use a more descriptive title and definition, but I've been hearing this quite a bit as well. Diagnosing the issue to determine what change broke this seems like it's either rooted to: A. The Pricetag component (seems slightly more unlikely) B. The Shuttle itself (My current bet)

Heh sorry, my first issue report so its a bit choppy.

**Comment by SuperNovaa41** [comment]
![image](https://user-images.githubusercontent.com/16159590/148654884-f8c3fac6-6685-4b93-a0b9-8fffc251b408.png)
![image](https://user-images.githubusercontent.com/16159590/148654887-b2a3f152-727f-4e16-9f75-0f131acb4067.png)
Seems to work fine for me. Please post here again if you encounter this issue again.

**Comment by tgent007** [comment]
> ![image](https://user-images.githubusercontent.com/16159590/148654884-f8c3fac6-6685-4b93-a0b9-8fffc251b408.png) ![image](https://user-images.githubusercontent.com/16159590/148654887-b2a3f152-727f-4e16-9f75-0f131acb4067.png) Seems to work fine for me. Please post here again if you encounter this issue again.

well.... it seems to work for me as well all of the sudden as a techie, ill open it again if it stops working again as an assistant.

**Comment by tgent007** [comment]
re-opening this as I tested it on Bagil that didn't have any testmerges and it worked and then tried on sybil where it didn't work, still broken.

**Comment by MrMelbert** [comment]
![image](https://user-images.githubusercontent.com/51863163/148668451-126291a4-788c-4591-b0b9-535e551b3012.png)

caused by progression traitors
