### ISSUE TITLE
Airlocks Made Pre-Area Define Don't Reassign Themselves To The Newly Created Area

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#63928]
Reporting client version: 514.1568

## Round ID:
[176138](https://scrubby.melonmesa.com/round/176138)

## Testmerges:
N/A (Campbell Station)

## Reproduction:
Constructing airlocks before you define an area (through the button or the blueprints) will have them fail to properly link to the new area, including (and most importantly) it's APC when that's built. Shafts construction slightly.

This kinda shafts the aux base /hard/, considering it's entire point was to allow colonizing lavaland with STEEL RAIN.

**Comment by Ryusenshu** [comment]
I did have that issue on Tram on Manuel a few days back when i was trying to power up the maints between Center and port.
They acted the same way, i had to destroy and rebuilt them and after that they worked

**Comment by Capsandi** [comment]
I had this issue a few weeks ago on campbell while making a satellite(space). Building airlocks in an unpowered area and overwriting it seems to make the airlocks ignore the new area and remain unpowered

**Comment by Mooshimi** [comment]
Can confirm, building airlocks before creating the apc will brick the doors. You have to destroy and rebuild them afterwards if you did it in this order.

**Comment by SyncIt21** [comment]
@ZephyrTFA #73850 fixed this, please close
