### ISSUE TITLE
I am unable to neither implant nor remove eyes from people

### ISSUE THREAD

**Issue by karenstarbuckseaterofsouls** [tgstation/tgstation#63927]
Reporting client version: 514.1571

## Round ID:
[176240](https://scrubby.melonmesa.com/round/176240)

## Testmerges:
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)
- [lowers kilo's bombcap multiplier](https://www.github.com/tgstation/tgstation/pull/63750)
- [makes hud images only show to mobs on the same z level to save on maptick](https://www.github.com/tgstation/tgstation/pull/63558)

**Comment by SuperNovaa41** [comment]
![image](https://user-images.githubusercontent.com/16159590/148651450-70d8e783-617e-4a12-a00c-303351aebcb5.png)
![image](https://user-images.githubusercontent.com/16159590/148651494-c186dda8-76ee-40be-9343-2dfbf81105f9.png)
chances are, you were doing something wrong
