### ISSUE TITLE
Social anxiety speech and lizard accents are broken

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#63935]
## Testmerges:

#63331: 'Revert "Require Node 16"' by MrStonedOne at commit 3bccf7f8c1
#63750: 'lowers kilo's bombcap multiplier' by Fikou at commit 16e2d0383d
#63558: 'makes hud images only show to mobs on the same z level to save on maptick' by Kylerace at commit 58446d9dc9

## Reproduction:

Play a lizard, use words with 'x' or 's' in them, have social anxiety and try speaking (no stutter)

**Comment by MrMelbert** [comment]
Caused by #63696

**Comment by dragomagol** [comment]
Will be fixed by #63939
