### ISSUE TITLE
Command Reports missing from chat

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#63932]
Reporting client version: 514.1575

## Round ID:
[176263](https://scrubby.melonmesa.com/round/176263)

## Testmerges:
- [makes ai static into images added to obscured turfs to save on maptick](https://www.github.com/tgstation/tgstation/pull/63666)
- [[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety](https://www.github.com/tgstation/tgstation/pull/63588)

## Reproduction:

CentCom messages are not relaying into main chat ; this includes (seen as examples) "end of revolution" messages, "nuclear war declared" messages and also "create command report" announced messages.

**Comment by MrMelbert** [comment]
Caused by progression traitors it seems

**Comment by Capsandi** [comment]
May also be related to #54692

**Comment by SuperNovaa41** [comment]
Fixed.
