### ISSUE TITLE
AI Announcement Visible from Lobby

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#63941]
Reporting client version: 514.1571

## Round ID:
[176272](https://scrubby.melonmesa.com/round/176272)

## Testmerges:
- [makes hud images only show to mobs on the same z level to save on maptick](https://www.github.com/tgstation/tgstation/pull/63558)
- [lowers kilo's bombcap multiplier](https://www.github.com/tgstation/tgstation/pull/63750)
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)
- [[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety](https://www.github.com/tgstation/tgstation/pull/63588)

## Reproduction:
Be in lobby.
AI announces.
???????
Success!
![image](https://user-images.githubusercontent.com/44104681/148665422-0b31a352-e769-447f-93f6-43e06b310636.png)

**Comment by VladinXXV** [comment]
As a note: this wasn't a one-time thing. Moments later the AI made ANOTHER announcement, which I saw. Still from lobby.

**Comment by VladinXXV** [comment]
Addendum 2: other players reporting the same phenomenon

**Comment by SuperNovaa41** [comment]
Probably prog traitors

**Comment by SuperNovaa41** [comment]
Fixed.
