### ISSUE TITLE
AIs can not announce laws past 3

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#63948]
## Testmerges:

#63558: 'makes hud images only show to mobs on the same z level to save on maptick' by Kylerace at commit 58446d9dc9
#63750: 'lowers kilo's bombcap multiplier' by Fikou at commit 16e2d0383d
#63331: 'Revert "Require Node 16"' by MrStonedOne at commit 3bccf7f8c1
#63588: '[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety' by Watermelon914 at commit b9fdbd265a

## Reproduction:

Give AI a 4th law
Try to announce it
They can't

**Comment by SuperNovaa41** [comment]
Probably prog traitors

**Comment by SuperNovaa41** [comment]
Fixed.

**Comment by SuperNovaa41** [comment]
nvm

**Comment by Iamgoofball** [comment]
If this is reproducible we need to fix this immediately or there's about to be some very banned silicon mains

**Comment by SuperNovaa41** [comment]
![image](https://user-images.githubusercontent.com/16159590/149670611-190ef679-522c-4aaa-be43-c6dbcabb4171.png)
Something broke, i will try to fix it
