### ISSUE TITLE
virus plasma + synaptizine = plasma gas and synaptizine

### ISSUE THREAD

**Issue by the-orange-cow** [tgstation/tgstation#63944]
## Round ID:
Round ID: 176275
BYOND Version: 514.1561
Server revision compiled on: 
Master commit: 5375ac5113f34a74b09ddfad1ba33ec3a19b97ed

##Testmerges:

The following pull requests are currently test merged:
#63140: 'Ports flying bloodsplatters from Hippie for Wounds' by Ryll-Ryll at commit 814b860e2a
#63500: 'Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time' by Kylerace at commit a739bed138
#63588: '[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety' by Watermelon914 at commit b9fdbd265a

## Reproduction:

I was goofing around in the lavaland syndie ghost role, playing with viruses.  I tried to create weakened virus plasma by mixing virus plasma with synaptizine.  Instead of creating weakened virus plasma, it released plasma gas into the air and some leftover synaptizine remained in the beaker.

I tried this numerous times, to the same effect.  After a couple times of this happening, I used the chemmaster to double check the reagents were virus plasma and synaptizine, which they were.  I tried mixing them together in the chemmaster, with the same result.

**Comment by TemporalOroboros** [comment]
What temperature was the synaptizine? If it was too hot the plasma was probably boiling off.

**Comment by TemporalOroboros** [comment]
I think I found it. Virus plasma and weakened virus plasma are both subtypes of plasma. As a result, they are supposed to boil when they hit 323.15K. The recipe for making them does not override how much heat it produces. As a result, the virus plasma technically comes into existence at ~350K. It's stable until something updates the temperature of the mixture, like mixing in synaptizine at a different temperature. Then it realizes that it should be boiling and evaporates.

**Comment by timothymtorres** [comment]
@TemporalOroboros so all we need to do is jack up the boil temperature to like 450K?

**Comment by TemporalOroboros** [comment]
> @TemporalOroboros so all we need to do is jack up the boil temperature to like 450K?

Either that or lower the temperature change on the virus plasma and weakened virus plasma recipes.
