### ISSUE TITLE
Space Barkeep is rendered unusable.

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#63959]
Reporting client version: 514.1571

## Reproduction:
Hop onto a map that has Lavaland
Hope that Lavaland spawns a Beach, to enjoy some relaxing solo barkeeping with none of the station exploding shenanig-
Discover the barkeep, pre-loaded and dead on the floor, never touched by anyone.
![image](https://user-images.githubusercontent.com/76874615/148689036-98f3e893-c71b-4c1d-9768-29a11710a33d.png)

The first time I've seen this happen I thought it was someone just hopping in and like, instasuiciding the 'keep just to remove the one nice thing about the beach, but it seems that is not the case, as it's been consistently happening for a while, and everytime it's the same.
Weirdest part is that if you just put down the spawner manually, it works just fine, it gets appended to the end of the list of ghostroles, you can take it to get another random 'keep, it's all good.
![image](https://user-images.githubusercontent.com/76874615/148689446-e1819b96-51c3-49ff-aae7-65978a13ddd1.png)
Genuinely no idea how it only happens to the barkeep, the other two ghostroles on this location are unchanged.

**Comment by SuperNovaa41** [comment]
@tralezab

**Comment by jughu** [comment]
Im laughing

**Comment by timothymtorres** [comment]
Relevant code:

This is the bartender related things

https://github.com/tgstation/tgstation/blob/975830a242ca554138d6a3f1821e886aca7e62ef/code/modules/mob_spawn/ghost_roles/mining_roles.dm#L113-L121

https://github.com/tgstation/tgstation/blob/4c21166e4ff69221fa3b0aa3225baddaf83518b8/code/modules/jobs/job_types/spawner/space_bartender.dm#L1-L3

And this is the beach bum:

https://github.com/tgstation/tgstation/blob/975830a242ca554138d6a3f1821e886aca7e62ef/code/modules/mob_spawn/ghost_roles/mining_roles.dm#L73-L81

https://github.com/tgstation/tgstation/blob/4c21166e4ff69221fa3b0aa3225baddaf83518b8/code/modules/jobs/job_types/spawner/beach_bum.dm#L1-L3

**Comment by AdipemDragon** [comment]
Hold the phone, there might be something wrong with the whole prefab itself that makes the barkeep do that. 
I've Literally spawned in the Beach Biodome by itself and it just _instantly_ kills them.
![image](https://user-images.githubusercontent.com/76874615/149619447-98d45cf6-1a0b-48ac-9735-1147a184136b.png)
