### ISSUE TITLE
New icebox medbay issues

### ISSUE THREAD

**Issue by mozi-h** [tgstation/tgstation#63968]
## Round ID:

[176325](https://scrubby.melonmesa.com/round/176325)

## Reproduction:

Play new icebox medbay, after #63804 (props by the way) was merged

### Wrong icebox medbay cargo console 

Full supply request console, instead of the medical cargo console was placed in medbay.
![](https://i.imgur.com/qYnWdgW.png)

### Exposed wires / missing floor tile

There are exposed wires in and around cryo (left, north and ~~freezer~~)
![](https://i.imgur.com/Ett9QZd.png)

### Door opener doesn't work

The security post's door opener button doesn't open the door. Also tried pressing with full access.
![](https://i.imgur.com/Q2sqUfN.png)

### CMO table unreachable

The top left table with the paper is unreachable in CMO's office.
![](https://i.imgur.com/6HOjH3P.png)

**Comment by AlinaStarkova** [comment]
ah, some of these must have broke back with the map merge conflict, darn, ill fix em

**Comment by the-orange-cow** [comment]
The viro lab doesn't have a basic virus food dispenser.
