### ISSUE TITLE
You can't get wet

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#63966]
Local testing. 

Negative firestacks (wetness) was a thing. It doesn't work anymore. You can't get firestacks under 0. 

## Reproduction:

1. Splash yourself with water or stand under a shower. 
2. Examine yourself. It says nothing about being wet. 
3. Check firestacks. It doesn't go below 0. 

This breaks the alkali perspiration symptom (tested) which would make you explode if wet.

**Comment by Potato-Masher** [comment]
I think the Tissue Hydration virus symptom is also affected by this issue, as supposedly it's supposed to take both consumed water and being wet into consideration for it's healing. I tried it out myself before and ran into this same issue of never getting wet.
