### ISSUE TITLE
Unable to repair bots

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#63969]
Reporting client version: 514.1575

## Round ID:
[176324](https://scrubby.melonmesa.com/round/176324)

## Testmerges:
- [makes ai static into images added to obscured turfs to save on maptick](https://www.github.com/tgstation/tgstation/pull/63666)
- [[MDB IGNORE] Adds progression traitors. Refactors uplink code in its entirety](https://www.github.com/tgstation/tgstation/pull/63588)

## Reproduction:

Noticed a player just chatting about bots (they were a medibot) being unrepairable, which was new to me, I figured some mistake over the maintenance panel usage but....

Spawned a floor bot, unlocked the controls, flipped the maintenance switch (which tooltips to say it unlocks healing mode too), and poked it with a welder, on and off combat mode, left and right clicks, all simply cause it more damage.

**Comment by TheBonded** [comment]
did you unscrew it first? you have to unscrew the maintenance hatch to heal it

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/64301
