### ISSUE TITLE
Open airlocks with pinned paper let it float

### ISSUE THREAD

**Issue by mozi-h** [tgstation/tgstation#63979]
## Round ID:

None, seen on-server, reproduced locally

## Reproduction:

1. pin paper / photo to airlock
3. open it
3. floating paper
7. get burned as a witch

![](https://i.imgur.com/Lqbn0vb.png)

**Comment by timothymtorres** [comment]
Eyeballs PR #63783 suspiciously

**Comment by MrMelbert** [comment]
definitely was a bug prior to that PR
