### ISSUE TITLE
Cheese wheel counts as a slice/wedge for recipes

### ISSUE THREAD

**Issue by jacklecroy** [tgstation/tgstation#63998]
An entire cheese wheel (which is like 6 wedges or something) counts as one wedge in recipes. One problem with this is that you can put the nuclear authentication disk inside of a cheese wheel and then put it in nachos, or worse, an Arnold Pizza.

**Comment by SuperNovaa41** [comment]
The issue here is that `/obj/item/food/cheese` is the slice, and it's child `/obj/item/food/cheese/wheel` is the whole piece, meaning that it can be used. These should probably be swapped.
