### ISSUE TITLE
Maint Loot doesnt spawn in crates

### ISSUE THREAD

**Issue by SamDDBS** [tgstation/tgstation#63990]
## Round ID:
[176378](https://scrubby.melonmesa.com/round/176378)

## Testmerges:
#63588 #63939 #63750 

## Reproduction:
Generate map, open crates in maint, most will be empty

**Comment by SamDDBS** [comment]
PS i saw this on metastation, if that has anything to do with it

**Comment by TheBonded** [comment]
@SamDDBS this is a station trait that causes less loot to spawn in maints. there is also a trait that causes far more loot to spawn in maints.

**Comment by SuperNovaa41** [comment]
@SamDDBS was there ANY loot at all in maints?

**Comment by SamDDBS** [comment]
There was no maint loot in the crates, however there was some present in the closets and some on the racks

**Comment by SuperNovaa41** [comment]
ok im starting to think this was just the station trait. Ill test it out in a bit.

**Comment by SuperNovaa41** [comment]
got this with the station trait, and nothing else

**Comment by SamDDBS** [comment]
well, i guess that explains it
the trait did seem rather extreme though with there being nearly nothing in maint

**Comment by TheBonded** [comment]
that's why it's a rarer stationtrait, afaik
