### ISSUE TITLE
Missing Fire Alarm in MetaStation Arrivals

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#64012]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Only way to leave the area is by going through space

![Screenshot_1](https://user-images.githubusercontent.com/95751821/149040094-8700a01f-0fd8-478a-8bdb-af9a09f623fa.png)

**Comment by SuperNovaa41** [comment]
This may actually have been intended, there are a few places with no fire alarm. (it should definitely be changed though)
