### ISSUE TITLE
Ninja Spider Charge doesnt complete the objective to explode

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#64010]
## Round ID:
[176430](https://scrubby.melonmesa.com/round/176430)

## Testmerges:

Unsure

## Reproduction:

>Use the Charge on the Location
>It blew up
>Not completed

![Ninja Win 2 (bomb bugged)](https://user-images.githubusercontent.com/95751821/149035013-a8745211-4ccf-4f15-abb4-8f3e7115c85d.png)

**Comment by SuperNovaa41** [comment]
`detonator` is setting to null for some god damned reason. I think it has to do with the weakref
