### ISSUE TITLE
Springlock MOD module kills you even when you have Memento Mori necklace

### ISSUE THREAD

**Issue by panvxv** [tgstation/tgstation#64029]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Put a Springlock MOD module inside of MOD control unit, have on your neck slot a Memento Mori that is active. Power your MOD suit and turn on a smoke machine with reagants. Have a horrible death.

**Comment by Time-Green** [comment]
Springlock intentionally ignores all death protections. 
https://github.com/tgstation/tgstation/blob/5c672028b09a41fb323d143b46689f58343ae417/code/modules/mod/modules/modules_maint.dm#L52
@Fikou
