### ISSUE TITLE
Ritual wine traitor objective completed by splashing it

### ISSUE THREAD

**Issue by kawoppi** [tgstation/tgstation#64040]
## Round ID:
[176480](https://scrubby.melonmesa.com/round/176480)

## Testmerges:
None as far as I could tell?

## Reproduction:
- Take the objective for getting the ritual wine from the cargo office and exporting it
- Go to the cargo office and get the ritual wine
- Try to put it in your backpack but accidentally splash the wine on it instead
- The objective is now complete despite spilling the wine and not even having exported the empty bottle

**Comment by Angustmeta** [comment]
Can confirm as I just tested it as well. Emptying the ritual wine into another beaker completed the objective.
