### ISSUE TITLE
You can't take cards out of nonstandard card decks (tarots, wizoff)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#64062]
Reporting client version: 514.1568

## Round ID:
[176500](https://scrubby.melonmesa.com/round/176500)

## Reproduction:

- Attempt to remove a card from a tarot deck or a wizoff deck
- The card is stuck to the deck
- Attempt to remove a card from a normal deck
- The card relinquishes

**Comment by timothymtorres** [comment]
@SuperNovaa41

**Comment by Angustmeta** [comment]
This throws runtimes.

**Comment by SuperNovaa41** [comment]
:(
