### ISSUE TITLE
Shooting range duplicating windoor. (report from down stream)

### ISSUE THREAD

**Issue by tobjv** [tgstation/tgstation#64069]
## Reproduction: Metastation Interesting bug. It's possible to duplicate windoor assemblies and airlock electronics as many times as you want if you just repeatedly crowbar the electronics out.
I went to the sec firing range, and went to disassemble the windoor. I opened it, screwed the panel open, and then crowbarred it. That ended up dropping airlock assemblies and creating a duplicate windoor assembly on the same tile as the shooting range door. Crowbarring the shooting range door made more airlock electronics and windoor assemblies.

It only seems to work with that one particular shooting range windoor, however, and presumably any other windoor that spawns at roundstart.

**Comment by TheBonded** [comment]
possibly related to https://github.com/tgstation/tgstation/issues/58294
