### ISSUE TITLE
Kudzu / space vines stop spreading a few seconds after planted (with runtimes!)

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#64080]
Observed on Terry today, and reproduced locally. 

![220114 0006 45](https://user-images.githubusercontent.com/46400996/149423317-297c7d74-3df9-4c6b-8d48-9fd592aa8511.png)

## Reproduction:
1. Plant a kudzu seed on ground. 

**Result:** It stops spreading after a few moments. If you destroy the borders it regrows only what you destroyed. Then it starts throwing runtimes every couple of seconds (see runtime 2 below). 

This could NOT be reproduced on my build from Jan 12, 2022, where #63812 was merged, so that PR is likely NOT to blame. Kudzu did still throw other runtimes on that build however, after mutating. 

This non-spread bug could be reproduced after updating late Jan 13, 2022. Meaning the problem is likely caused by a very recent merge. 

## Runtimes:

<details>
  <summary>Runtime 1 - Some time after planting</summary>
[00:07:51] Runtime in spacevine.dm,569: Cannot execute null.Enter().

  proc name: spread (/obj/structure/spacevine/proc/spread)
  src: the space vine (/obj/structure/spacevine)
  src.loc: null
  call stack:
  the space vine (/obj/structure/spacevine): spread()
  /datum/spacevine_controller (/datum/spacevine_controller): process(2)
  Objects (/datum/controller/subsystem/processing/obj): fire(0)
  Objects (/datum/controller/subsystem/processing/obj): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)

</details>

<details>
  <summary>Runtime 2 - Spams after destroying all kudzu except one tile, I think</summary>
00:13:13] Runtime in spacevine.dm,517: Cannot read null.mutations

</details>

<details>
  <summary>Another error, also seen on the build from January 12, 2022. </summary>

TESTING: GC: -- [0x2005bcb] | /obj/structure/spacevine was unable to be GC'd --

</details>

**Comment by the-orange-cow** [comment]
Saw this same thing happen just now on Round # 176551.

**Comment by LemonInTheDark** [comment]
likely my fault somehow

**Comment by ShizCalev** [comment]
@LemonInTheDark Yup. The process block is runtiming if vine in growth_queue is being QDEL'd
https://github.com/tgstation/tgstation/pull/63877/files#diff-918db9eb6b54e91a2ea210af60b5c2409f1eda6459a54ce60b814fe74d1c1b79

**Comment by LemonInTheDark** [comment]
Oh fuck I see
