### ISSUE TITLE
Adv Cam Console, Nav Console (and maybe Xeno) are missing an exit button

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#64103]
## Round ID:
[176570](https://scrubby.melonmesa.com/round/176570)

## Testmerges:
#63666

## Reproduction:
>Use a Nav Console on a Whiteship
>Cant exit it

Also the Jump to Cam Button keeps duplicating

(In another Round as Pirate i had this issue as well)

**Comment by AnturK** [comment]
@LemonInTheDark This was part of the hard-del fixes i believe.

**Comment by MrMelbert** [comment]
Fixed by #64051 already, the servers just haven't updated
