### ISSUE TITLE
Ai in mech cannot use weapons

### ISSUE THREAD

**Issue by Kubisopplay** [tgstation/tgstation#64112]
Reporting client version: 514.1568

## Round ID:
[176600](https://scrubby.melonmesa.com/round/176600)

## Reproduction:
1. Get midround malf
2. Try possesing a mauler that a good jannie spawned to make it more interesting
3. realise you cannot use any weapons cause middle click does nothing
4. Cry while breaking through walls using autohit

**Comment by Donpedrito** [comment]
Can corroborate, AI-controlled Odysseus was unable to use the medibeam, as the designated button for using modules, middle click, simply tracks the clicked person on cameras, like it does when not controlling a mech.

**Comment by Dorsisdwarf** [comment]
Seems to be #38178 coming back with a vengeance?
