### ISSUE TITLE
Possible issue with ranged guns not targeting correctly

### ISSUE THREAD

**Issue by Ryll-Ryll** [tgstation/tgstation#64129]
Reporting client version: 514.1557

## Round ID:
[176622](https://scrubby.melonmesa.com/round/176622)

## Reproduction:
Unlike most of my issue reports, this one doesn't have much hard data, and is based on 2 independent events I've handled today on sybil, which has been on [this commit.](https://github.com/tgstation/tgstation/commit/59c12a08b283f712264ec6f3fc809817bad6366e) There appear to be cases where, whether the user is firing a handheld gun such as a PKA, or in a clarke shooting a PKA, that shooting directly down may cause the target to be an entirely different tile, often in a different direction. I'm making this issue early on to provide a central place for people to post other examples of the issue to help cross reference what specifically the issue is

**Comment by LemonInTheDark** [comment]
Related to #64130

**Comment by newfren** [comment]
I have had this issue recently when targetting my pka past a drake that was above me - it would fire to the left consistently. Targetting between us shot directly at it, as I was aiming.

**Comment by SuperNovaa41** [comment]
Possibly caused by https://github.com/tgstation/tgstation/pull/64015

**Comment by Ryll-Ryll** [comment]
fixed at some point
