### ISSUE TITLE
Aiming is screwed up with the rotational math 

### ISSUE THREAD

**Issue by CCC23** [tgstation/tgstation#64130]
Round ID:[176625](https://scrubby.melonmesa.com/round/176625)

If you discovered this issue from playing tgstation hosted servers:

## Reproduction:

Rotation is bugged in a way that fucks with aiming HEAVILY if you aim at obscured tiles it makes your aim heavily off making you shoot wildly either behind you to the side or directly up. 
It happens when you click darkness, something about the rotation is fucked" 
We believe it might have something to do with the rotational math or something with the sniper range merge 

Check your rotation math thats most likely were the issue is

**Comment by TemporalOroboros** [comment]
This is on me for testing with x-ray on.

**Comment by TemporalOroboros** [comment]
Found it. The click catcher is setting the target as the turf you clicked over, but it's passing the pixel_x and pixel_y values based on the click catcher instead of the turf you clicked over.
