### ISSUE TITLE
Lavaland Bar spawned on Icebox (Deepest Mining)

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#64134]
## Round ID:
[176630](https://scrubby.melonmesa.com/round/176630)

## Testmerges:
N/A

## Reproduction:
The Lavaland Tiles were Atmos Tiles

![Screenshot_1](https://user-images.githubusercontent.com/95751821/149624644-e10ccb62-682a-4812-b019-abb8ca8f8ba5.png)

**Comment by AdipemDragon** [comment]
![image](https://user-images.githubusercontent.com/76874615/149634973-bf1b94e3-481c-4b83-a231-bbac5a048c8b.png)
That's on me, should've probably cleared it up when I was done

**Comment by Ryusenshu** [comment]
Oh alright, gonna close it
