### ISSUE TITLE
4 random Icebox Medical Issues 

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#64149]
## Round ID:
[176657](https://scrubby.melonmesa.com/round/176657)

## Testmerges:
N/A

## Reproduction:
**1:**
> Find a suicide victim
> Cant set them as deceased without asking CMO

Only CMO and Psychology have a records computer, but there is none for medbay itself

(There is one in the Sec Booth for some reason)

**2:**

Weird Cam placement

![Screenshot_1](https://user-images.githubusercontent.com/95751821/149644189-d38a770e-10e8-43a2-8793-877455e780a9.png)

**3:**

Either im blind or the drone factory is gone
![Screenshot_2](https://user-images.githubusercontent.com/95751821/149644264-8a14cdae-e212-43d3-91f6-9fd880fa7c12.png)

**4:**

From a round a few days back:
I remember that i used to be able to go through the maint, between medical and science, as a roboticist.
That doesnt seem to be possible anymore

**Comment by MrMelbert** [comment]
bonus one I found: In the surgery hallway, there's a tank holder (with extinguisher) on top of a disposals bin
