### ISSUE TITLE
Destroyed Floorbots creating infinite tools

### ISSUE THREAD

**Issue by jwc1015** [tgstation/tgstation#64155]
## Reproduction:
The destruction of a Floorbot made with an empty toolbox produced a toolbox full of tools; this could be repeated multiple times. I asked around and was told to make the bug report up here specifically.

**Comment by dragomagol** [comment]
I've heard similar reports about medbots

**Comment by SuperNovaa41** [comment]
i couldnt reproduce the medbots dropping that, but if it does happen my fix will stop that
