### ISSUE TITLE
Stuff in pipes not shooting out properly if the end is just a pipe

### ISSUE THREAD

**Issue by BongoDongo2000** [tgstation/tgstation#64179]
## Round ID:
[Round ID]: #176739, then tested more on #176473

Currently it seems anything going into a disposal pipe network won't exit if the last step is a disposal pipe. 

## Reproduction:

1. Built trunk and chute. Testing throwing things in. Things would get shot out in random directions.
2.  Added a disposal pipe section. Threw in a tile. Tile did not shoot out
3. Cover that pipe in tile. Threw in a tile. Tile did not shoot out. The tile above the pipe did not pop off. This is important as part of the code that handles the pipe shooting stuff out does a check for that and will pop the tile off if its there. For following steps i tested with and without a tile on.
4. Added a junction to the pipe. Chute > Pipe > Junction. Threw tile in. Tile did not shoot out
5. Removed junction. Proper noise played, items previously thrown came out as they should.
6. Added a sort junction. Chute > Pipe > Sort Junction. Threw tile in. Tile did not shoot out.
7. Removed sort junction. Proper noise played, items previously thrown came out as they should.
8. Added trunk. Chute > Pipe > Trunk. Threw tile in. Tile did not shoot out.
9. Put Outlet on top of the trunk. Chute > Pipe > Outlet. Proper sounds played, tiles shot out.

I then tried a new section and tested Bins

1. Bin > Pipe. Flushed tile. Tile did not shoot out.
2. Added trunk. Flushed tile. Tile did not shoot out.
3. Added bin. Bin > Pipe > Bin. Flushed tile. Tile shot out other side, proper sound played.

I stopped after that. Also I'm unsure if this has always been a thing or not but a Bin that is bolted but not welded is rotated 90 degrees to the left. May or may not be related

https://i.imgur.com/WOKD3jO.png

From the above testing it seems its not doing the check for shooting stuff out of pipes for whatever reason, If someone is in there they are just stopped at the end, like if you get looped and it finally stops looping you. A borg who got caught in this by accident was able to bash his way out like normal. 

Only noticed this today, unsure if its been a longer issue.

**Comment by Shadowflame909** [comment]
Yeah disposals in general are broken. I got stuck in a bombed disposals loop, and I kept thunking in the last non-broken pipe instead of just shooting out.

**Comment by SuperNovaa41** [comment]
Were there any testmerges? That's kind of important for this since there is a big pr open that messes with disposals
what server were you on?

**Comment by BongoDongo2000** [comment]
Server was Sybil. I checked and the only test merge listed was the mod suit Kinesis one

https://github.com/tgstation/tgstation/pull/64151
