### ISSUE TITLE
Inventory issue: Phantom internals tank

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#64180]
## Reproduction:

Try to enable internals from an airtank in my pocket
Internals lights up and gives me oxygen for a few seconds.
Try to take oxygen tank out of my pocket to see whats wrong
All clicks on it don't work, unable to put anything else in that slot

**Comment by Jackraxxus** [comment]
Might have something to do with #64095 and picking up items from nullspace/inventory?

**Comment by LemonInTheDark** [comment]
Unlikely, but possible

**Comment by timothymtorres** [comment]
This could be a related issue that is happening to lots of items: #64190

**Comment by timothymtorres** [comment]
On second thought I see other bug reports relating to #64190 so I'm going to close this as a dupe.
