### ISSUE TITLE
bubblegum's attack patterns are completely borked

### ISSUE THREAD

**Issue by the-orange-cow** [tgstation/tgstation#64198]
## Round ID:

[Round ID]: # 176788

## Testmerges:

BYOND Version: 514.1561
Server revision compiled on: 
Master commit: 2adbc72d92240dd55fe62813ab4a7d0489483cc6
The following pull requests are currently test merged:
#64151: 'Kinesis Module' by Fikou at commit a57df5a859
#64144: 'Adds Thieves, a very low level antagonist.' by tralezab at commit 7536af8f51

Local commit: bfe49127ef288389812b3f57217c8dd83e61679d
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:

Bubblegum's movement is messed up.  This is somewhat noticeable prior to 50% health, but mostly fine, other than instances of https://github.com/tgstation/tgstation/issues/63886.  Once he loses enough health to start using phase two abilities(i.e. clone spam), things go utterly off the rails, with constant clone spam and completely disjointed movement.

Possibly related, Hierophant was moving very slowly during the same round.

**Comment by Shadowflame909** [comment]
legions are moving weird too. I think something borked AI code.

I would send a video but my video capturing software does not like ss13

**Comment by tgsAvylaar** [comment]
It's ridiculously noticeable on hiero.
