### ISSUE TITLE
Broken cameras on meta and icebox stations

### ISSUE THREAD

**Issue by exymian** [tgstation/tgstation#64229]
## Round ID: 
[176846](https://scrubby.melonmesa.com/round/176846)

## Reproduction: 
Go to a security camera console and start going through(or go directly) cameras, when you reach "Library #1,2,3,4" in metastation the camera gets weird, its static as if the camera was cut, name of the camera goes away and you cant go to the previous or the next camera. Its not selected on the list as well. There are some set bugged cameras on both of these stations.

Ex;
-Library, labour camp cameras are broken in meta station
-Library, RD's office's camera is bugged on icebox

**Comment by Sealed101** [comment]
#62528 is at fault here, but just replacing these cameras with a proper type would fix these cams being fucky.

**Comment by SuperNovaa41** [comment]
Reportedly still an issue
