### ISSUE TITLE
Syndicate Bombs don't damage Gygaxes

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#64220]
Reporting client version: 514.1569

## Round ID:
[176840](https://scrubby.melonmesa.com/round/176840)

## Testmerges:
- [Adds Thieves, a very low level antagonist.](https://www.github.com/tgstation/tgstation/pull/64144)

## Reproduction:

So two syndicate bombs went off point blank next to a Gygax and did less than 20% damage to it, if that. Inside was the RD in their prototype modsuit. What I SUSPECT may be the cause is the bomb resistance from the suit expanding to the Gygax, but I can't say for certain as I haven't looked at the code.

**Comment by techno0** [comment]
Syndicate Bombs or Maxcaps often fail to damage a mech even at very close range.

**Comment by TiviPlus** [comment]
This is a feature, mechs have a % chance to completely ignore explosions, and a chance to completely ignore taken damage
