### ISSUE TITLE
 Plumbing machines can't have their orientation changed by alt-clicking when unpowered.

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#64231]
Reporting client version: 514.1569

## Round ID:
[176850](https://scrubby.melonmesa.com/round/176850)

## Testmerges:
- [Adds Thieves, a very low level antagonist.](https://www.github.com/tgstation/tgstation/pull/64144)

## Reproduction:

Plumbing machines can't have their orientation changed by alt-clicking when unpowered. Basically let an APC drain so that equipment is off and then you'll be unable to rotate the items after placement.

**Comment by timothymtorres** [comment]
Plumbing is considered machinery and has power requirements to function.  I'm surprised that the rotation isn't handled by a wrench.  What plumbing type is this happening to?

**Comment by vincentiusvin** [comment]
Related to #61852

**Comment by timothymtorres** [comment]
Duplicate of #61852
