### ISSUE TITLE
SecHUD's dissapear when you override(?) them

### ISSUE THREAD

**Issue by exymian** [tgstation/tgstation#64230]
## Round ID: 
[176846](https://scrubby.melonmesa.com/round/176846)

## Reproduction:
 Wear Security HUD glasses, hold the reflective trenchcoat.
 When you do that, you will notice that the security HUD disappears as if you took off the glasses. Rewearing the glasses fixes this issue.

**Comment by timothymtorres** [comment]
https://github.com/tgstation/tgstation/blob/879f835c7e6f2900bf505289fbb1ed51d83de1c0/code/modules/clothing/glasses/hud.dm#L10-L18

https://github.com/tgstation/tgstation/blob/0265f334ad23da3c8e67630fd756458ab1fb1f0c/code/modules/clothing/suits/ablativecoat.dm#L47-L55

Hey @SuperNovaa41 I know you messed touched trenchcoat code recently in #63524 but it appears that the trenchcoat removal is deleting the huds even if the trait is still present.  We should check for the trait before removing the hud.
