### ISSUE TITLE
Borgs are stuck upside down after a complex weave of tipping, untipping, and relogging

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#64232]
Reporting client version: 514.1569

## Round ID:
[176854](https://scrubby.melonmesa.com/round/176854)

## Testmerges:
- [Adds Thieves, a very low level antagonist.](https://www.github.com/tgstation/tgstation/pull/64144)

## Reproduction:

Essentially I was playing Jubilant Triumph an engiborg and was flashed several times by Brick and Axle testing the new system. During this process of tipping and untipping I was rendered immobile. I suspect that at some point during the process it trigged the lock despite me being upright. I did try relogging and when logged back in I was upside down but able to move.
![2022-01-18 19_25_23-Window](https://user-images.githubusercontent.com/36066032/150052527-40ca096e-aefe-41e4-a300-3db82133d3fc.png)

**Comment by tgsAvylaar** [comment]
Link to video with a moving tipped borg. [https://files.catbox.moe/ojoy1v.mp4](url)

**Comment by MrMelbert** [comment]
Okay so the problem happens when two people start a tip at the same time

To fix, make it so only one person can tip something at once
