### ISSUE TITLE
Bluespace Cells sometimes just won't go into modsuits

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#64234]
Reporting client version: 514.1575

## Round ID:
[176851](https://scrubby.melonmesa.com/round/176851)

## Testmerges:
- [Adds Thieves, a very low level antagonist.](https://www.github.com/tgstation/tgstation/pull/64144)

## Reproduction:

Trying to put a charged Bluespace PowerCell into my Modsuit resulted in it just constantly getting put into storage instead. When I tried removing the storage module to avoid that it just ate the cell completely. Using a Super Cell seemed to work just fine without any issues however.

**Comment by Fikou** [comment]
it was fixed by next round
