### ISSUE TITLE
item rendering and spess movement buggery

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#64247]
Reporting client version: 514.1575

## Round ID:
[176883](https://scrubby.melonmesa.com/round/176883)

## Reproduction:

ok so:
1. Items appear to render on the floor when held.
2. Occasionally shit just freezes at random
3. Spess movement is now erratic

**Comment by LemonInTheDark** [comment]
I've got a solution for 1, but >Occasionally shit just freezes at random is not something I was aware of. Examples?
