### ISSUE TITLE
Cannot smuggle the prototype dart pistol (the traitor item you are supposed to smuggle)

### ISSUE THREAD

**Issue by exymian** [tgstation/tgstation#64248]
## Round ID:
[176759](https://scrubby.melonmesa.com/round/176759)

## Reproduction: 
Get the objective to smuggle this item and try to send the shuttle only to be faced with the message you get when you try to send a tracker beacon.

I couldn't send the shuttle when i had the objective on delta station, i emptied out the shuttle as well to make sure. There were no active admins so i couldn't ahelp it. My point is, it was a one time incident so im not totally sure if it really is a bug.

**Comment by MrMelbert** [comment]
I was able to smuggle the dart pistol out successfully yesterday

**Comment by exymian** [comment]
> I was able to smuggle the dart pistol out successfully yesterday - Might've broken in the past 8 hours? I'll tag it as such

thank you, i doubt its a thing but i wanted to report it just in case.

**Comment by JohnFulpWillard** [comment]
Was there a crate of mail under the shuttle's flaps?
