### ISSUE TITLE
Pillow update broke git hooks

### ISSUE THREAD

**Issue by SuperNovaa41** [tgstation/tgstation#64243]
https://github.com/tgstation/tgstation/pull/64226
this broke git hooks, i cannot commit, nor can i even uninstall git hooks
![image](https://user-images.githubusercontent.com/16159590/150154699-47854644-2c56-4c81-8c7d-756e41e2e8f1.png)
I get the same error when trying to uninstall the hooks aswell

**Comment by SuperNovaa41** [comment]
(forcing the version back to 8.3.2 fixes it temporarily)

**Comment by AnturK** [comment]
Pillow bumped requirements on wheels to 3.7 in 9.0.0.
