### ISSUE TITLE
An already animating mob will cause any item they draw to have a phantom object fall to the floor

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#64249]
## Reproduction:

The easiest method to reproduce this bug is to the go drift about in space. Any object you pull out will go through the new interaction animation, but something must malfunction (probably something breaking with loc) and it will leave a 'phantom' object behind where the animation concluded (and not where it was drawn). This object can be interacted with and picked up, but it isn't permanent, as putting it into your bag will store it as normal.

Things especially get fucky when you pick up the item. It's possible it can occupy two hands at once.

Almost certainly caused by https://github.com/tgstation/tgstation/pull/64095 as this is the animation breaking.

**Comment by LemonInTheDark** [comment]
I can assign myself thank you very much. Prichiate the ping tho, based
Alt of #64190 with slightly more context, thank you
