### ISSUE TITLE
Jetpacks (Especially ion jetpacks) in Space / nograv are very choppy now

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#64255]
## Reproduction:

Using a jetpack to fly around space now exhibits a great deal of choppiness and jumpiness. 

https://user-images.githubusercontent.com/51863163/150236040-e5468385-6039-4a5c-9cf2-ff206c62f378.mp4

https://user-images.githubusercontent.com/51863163/150237016-5feecf36-fd2c-4850-82b8-9cb7536bdb32.mp4

https://user-images.githubusercontent.com/51863163/150237101-7aca2b72-fbdb-4dc3-9e99-0bd2ef6a36c9.mp4

Prior, jetpacks would be a lot smoother when traversing no gravity.

**Comment by LemonInTheDark** [comment]
Likely consequence of making spacedrift smoother in #62567

**Comment by thgvr** [comment]
This only happens with jetpack stabilization off. Additionally, it seems to spawn a ghost item of things you take out of your inventory if you're moving in space at all.

**Comment by LemonInTheDark** [comment]
The ghost item behavior ought to be fixed on latest master
