### ISSUE TITLE
Couldn't clean toolbox with soap

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#64258]
Reporting client version: 514.1571

## Round ID:
[176902](https://scrubby.melonmesa.com/round/176902)

## Testmerges:
- [Adds Thieves, a very low level antagonist.](https://www.github.com/tgstation/tgstation/pull/64144)

## Reproduction:

1. Left and right-click on a toolbox with combat mode both on and off
2. Soap either goes into the toolbox or the toolbox's storage is opened

**Comment by etherware-novice** [comment]
ill work on this
