### ISSUE TITLE
Plants don't look their correct size when picked up / put down

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#64266]
Reporting client version: 514.1568

## Round ID:
[176910](https://scrubby.melonmesa.com/round/176910)

## Reproduction:

Grow a max potency plant. Should be very large. 
![image](https://user-images.githubusercontent.com/51863163/150252127-266356ce-6b9d-4274-b6d0-d179f1dce3e1.png)

Pick it up. Drop it. The plant shrinks.

![image](https://user-images.githubusercontent.com/51863163/150252248-4d8cbb3a-a5c8-401b-82ea-f9205c6cdf52.png)

Harvest a max potency plant via bag.

![image](https://user-images.githubusercontent.com/51863163/150252435-9da46dd2-8a1d-4bf7-8cfc-712062faf4e1.png)

Take it out by hand. The plant shrinks.

![image](https://user-images.githubusercontent.com/51863163/150252530-e5659123-6f16-49ed-8f4f-40fa2039f002.png)

**Comment by MrMelbert** [comment]
@LemonInTheDark Pick up animation issue maybe?

**Comment by LemonInTheDark** [comment]
Drop animation actually, but yes. Fix is easy
