### ISSUE TITLE
Can't sheet craft while drifting in space

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#64260]
Reporting client version: 514.1571

## Round ID:
[176902](https://scrubby.melonmesa.com/round/176902)

## Testmerges:
- [Adds Thieves, a very low level antagonist.](https://www.github.com/tgstation/tgstation/pull/64144)

## Reproduction:

1. Open build window for metal sheets
2. Eye in top right is orange, window is greyed out, can't interact with it

You used to be able to build things while space drifting, which was very useful for saving yourself from space.

**Comment by LemonInTheDark** [comment]
This is likely linked to/fixed by #64263, since items pulled from your backpack were being placed in space, rather then in you.

**Comment by LemonInTheDark** [comment]
Very very likely fixed by 64263
