### ISSUE TITLE
Illegal tech is unobtainable, as Research is initialized before Uplink Items

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#64284]
## Reproduction:

The list of boostable items for Illegal Technology (`syndicate_basic`) is populated in `New()`. 

Unfortunately, the list of Uplink Items was changed from a global list to a list on a subsystem with prog traitors - `SStraitor`. 

Illegal Tech iterates over the list of Uplink Items in `SStraitor` to determine which items are valid for illegal tech. But it's empty when this is done. 

The uplink list is initialized when the uplink asset sheet is created - this creates a problem, as the order they're initialized is `Research -> Traitor -> Assets`. Research is initialized far before Traitor is made, and even further before the uplink list is filled for the first time. 

This causes Illegal Tech to be unobtainable due to there being no uplink items when it is initialized.

**Comment by ArcaneMusic** [comment]
Top kek

**Comment by Swiftkor** [comment]
Even without this it was already practically unobtainable with the ridiculous experisci+point requirements
