### ISSUE TITLE
SecHuds won't show some all ID types

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#64287]
## Reproduction: 

Have a sec hud and look at any one with a syndicate ID or nanotrasen ID or other less common ID's like pirate ones and it will only show a black box which is kind of lame they should have some Icon on them 

I'm sure nanotrasen ahs the syndicate and the ID's of there own high command on there data base

**Comment by DrDiasyl** [comment]
The thing is, they don't have icons fully, why is this a issue?

**Comment by DrDiasyl** [comment]
Well anyway, I can do that
