### ISSUE TITLE
Access issue with tramstations returning gulag survivors

### ISSUE THREAD

**Issue by exymian** [tgstation/tgstation#64295]
## Round ID: 
[176696](https://scrubby.melonmesa.com/round/176696)

## Reproduction:

Be a prisoner sent to gulag, do your job and return with the ship. The airlock(s) after the ship one cannot be opened due to access. These doors should be opened and the prisoner would normally have access to the doors to let himself out of brig, let alone labor camp shuttle area.

![image](https://user-images.githubusercontent.com/66227760/150460061-70f22fef-7212-4fe8-a33f-88b60710a1d2.png)

i hope this helps somehow ? The issue is better recreated as i am not sure if it is intended or something..might be a one time issue as well.

**Comment by Thunder12345** [comment]
Access oversights by beloved...
