### ISSUE TITLE
".i" Intercom shortcut is not working

### ISSUE THREAD

**Issue by jeanlafite** [tgstation/tgstation#64290]
## Reproduction: 
the ".i" shortcut is supposed to allow you to use a wall intercom without interacting with it to speak on the channel it is set to: Simply stand near a wall intercom and place .i before what you want to say.Using it now results in a whisper of what you wanted to say but no transmission over the intercom.

**Comment by Serxule** [comment]
i can confirm this too, i use :i but it does the same.

**Comment by TheBonded** [comment]
You can use . in the place of : when speaking on any comms channel, it's nice because you don't accidentally speak on common

**Comment by Mothblocks** [comment]
@Kylerace your bug?

**Comment by Kylerace** [comment]
seems to work for me

**Comment by necromanceranne** [comment]
No elaboration on this so
