### ISSUE TITLE
Clicking to open a windoor while holding an item causes a delayed attack after the windoor opens

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#64315]
Reporting client version: 514.1568

## Round ID:
[177042](https://scrubby.melonmesa.com/round/177042)

## Reproduction:

-  Be holding any time. A tool, a beaker, a spear.
- Click on a windoor to open it up.
- The windoor slowly open up like expected...
- But after the opening animation is done, the item smacks the windoor.
   - The attack goes through at any distance, too.

**Comment by LemonInTheDark** [comment]
lmao

**Comment by willox** [comment]
Caused by https://github.com/tgstation/tgstation/pull/63914.
`/obj/machinery/door/attackby` now calls its parent, even when a windoor has been opened.
