### ISSUE TITLE
Rolled both thief and traitor midround

### ISSUE THREAD

**Issue by SnoopCooper** [tgstation/tgstation#64320]
Reporting client version: 514.1569

## Round ID:
[177053](https://scrubby.melonmesa.com/round/177053)

## Reproduction:
Became a thief while already being a traitor. Rolled traitor midround, then later on rolled midround thief too. I don't think you are supposed to be both types of antag at once.

**Comment by SuperNovaa41** [comment]
From the creator:
![2022-01-22_14:35:24_%](https://user-images.githubusercontent.com/16159590/150653071-3c6372d4-a4f3-4db0-85b0-8d532d3ccad5.png)

**Comment by JohnFulpWillard** [comment]
![](https://cdn.discordapp.com/attachments/279359975250198528/938572742570147861/unknown.png)

Help

**Comment by Mothblocks** [comment]
Thieves are gone
