### ISSUE TITLE
Nuke op infiltrator lost all air instantly when parking in space near Tramstation

### ISSUE THREAD

**Issue by Robustitron** [tgstation/tgstation#64341]
## Testmerges:
#63889: 'Refactors pay stands + custom vendors' by jlsnow301 at commit 3e481c7e39

## Reproduction:
1) Be a nukie during tramstation
2) Move nukie shuttle to space northeast of tramstation (lower zlevel iirc)
3) Suddenly zero pressure, start taking pressure damage, entire shuttle is spaced
4) Scramble to put on a modsuit, almost die waiting for it to activate

**Comment by Serxule** [comment]
oh, is because the lower levels actually have a ceiling, but the nukie shuttle does not come with one, as far as i know, so all the air just gets sucked out

**Comment by Sealed101** [comment]
syndies are too broke to afford a ceiling

**Comment by Valtosin** [comment]
Code from #63920 adds ceiling for multiz shuttles, use it

**Comment by Likteer** [comment]
> oh, is because the lower levels actually have a ceiling, but the nukie shuttle does not come with one, as far as i know, so all the air just gets sucked out

Can confirm, one time it was partially parked under the evac shuttle.
Of course, people broke a window, jumped down into the cockpit and died of depressurisation.

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/64493
