### ISSUE TITLE
Hostile mobs are moving twice as fast as they should

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#64349]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
I AM A FOOL

#64270 WAS A MISTAKE

players were complaining about lavaland mobs moving too slow. I thought I got the delay on my pr wrong.
I think instead what was bothering them was the gliding, since despite byond's reference, the delay argument of walk is not in ticks, but in fucking deciseconds

WHYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY

**Comment by MetalClone** [comment]
I can confirm this is a massive issue, polar bears and goliaths are moon walking 2 tiles instantly to hit me before I can even click their sprites.
