### ISSUE TITLE
AI's can't undo fire alarms.

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#64367]
## Round ID:
[177168](https://scrubby.melonmesa.com/round/177168)

## Testmerges:
#64353

## Reproduction:

Accidentally press fire alarm while jumping around with cameras as an ai
Press the fire alarm again to try to disable it
Nothing happens

**Comment by Mothblocks** [comment]
What does right-clicking it do

**Comment by Mothblocks** [comment]
@zxaber

**Comment by carshalash** [comment]
euuuuuuuuuuuuuuuuuuuuuuuuuuuuugh nevermind

**Comment by Mothblocks** [comment]
i dont blame you

**Comment by TheVekter** [comment]
KEKW

**Comment by Mothblocks** [comment]
fire alarms are the biggest reason i need to finihs contextual screentips
