### ISSUE TITLE
Firelocks no longer raise by themselves

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#64372]
## Reproduction:

Firelocks used to raise themselves when the temperature on the tiles of all the fire alarms in the area returned to normal. Now, you need to manually deactivate the fire alarm at a fire alarm panel and hope the temperature at the firelocks is enough for them to stay up. 

I assume this is because they look at the temperature on their own turf to know whether to stay active, and when the firelock is down the atmosphere on that turf can't mix with adjacent turfs so the temperature never changes. If this is true, they would be a lot easier to work with if they looked at the open turfs adjacent to them instead.

**Comment by LemonInTheDark** [comment]
This is not a bug, and more of a feature request.
It is a known downside of non area based firelocks, and while not having it bugs me too, implementing it killed the 3 attempts before what is now in the game.

Feel free to give it a shot, I may give it a go once I have more time on my hands

**Comment by cacogen** [comment]
How hard can it be for firelocks to just look at the open turfs beside them instead of underneath them to know whether to remain active?

**Comment by LemonInTheDark** [comment]
It's difficult to manage updating that, even more so when "open" has a kinda strange definition. Not impossible, just hard

**Comment by cacogen** [comment]
I just don't see how, if fire alarms used to activate based on the temperature of their tile, it's harder to have firelocks look at the turfs adjacent to them, ignore any that aren't /turf/open or maybe /turf/open/floor, and activate based on the temperatures of those.
