### ISSUE TITLE
Being Paraplegic stops you from getting skill chips inserted/removed. Downstream report

### ISSUE THREAD

**Issue by tobjv** [tgstation/tgstation#64387]

**Comment by magatsuchi** [comment]
tgui in general is definitely very fucky when it comes to paraplegics. for anyone interested, the proc that handles whether or not someone can interact with the ui is /datum/proc/ui_status(mob/user, datum/ui_state/state)

**Comment by dalmationer** [comment]
This is also the case for upstream on standard tgstation! I want to give my funny catgirl the kiss skillchip!
