### ISSUE TITLE
Drones cannot put boards into frames

### ISSUE THREAD

**Issue by MatthewW7** [tgstation/tgstation#64380]
Reporting client version: 514.1569

## Round ID:
[177187](https://scrubby.melonmesa.com/round/177187)

## Testmerges:
- [Refactors pay stands + custom vendors](https://www.github.com/tgstation/tgstation/pull/63889)

## Reproduction:

Drones cannot put computer boards or machine boards into computer frames or machine frames, it deletes the board

**Comment by MatthewW7** [comment]
it also eats machine board components (matter bins etc.)

**Comment by MatthewW7** [comment]
it ALSO eats cyborg limbs on a cyborg endoskeleton! basically whenever a drone tries to put a thing onto a thing, it deletes that thing

**Comment by Ryusenshu** [comment]
Happened to me me a while back
I wanted to build an APC and the Power Cell, i inserted, vanished

Also not sure if related, but i was unable to properly remove broken APCs (nightmare got em)
