### ISSUE TITLE
Being monkified doesn't remove modsuit parts

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#64411]
Reporting client version: 514.1568

## Round ID:
[177236](https://scrubby.melonmesa.com/round/177236)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/150914432-25ff4f8d-9120-43ce-a013-6a99a0388cb8.png)

Not sure if this one's intended or not. I'll leave it up to Fikou.

**Comment by necromanceranne** [comment]
MONKsuit

**Comment by NanoCats** [comment]
FEATURE

**Comment by Moltovz** [comment]
this is a feature
