### ISSUE TITLE
Canary False Fire Alarm Reports 

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#64431]
## Reproduction: Have a canary a few minutes after round start 

![image](https://user-images.githubusercontent.com/84478872/151086179-ec4cbfed-73bb-4047-ba48-aa71036c224a.png)

10 Minutes into the shift all this alarms went on about the same time when I chekced the locations the atmos was fine and there were no fire alarms triggered 

This is really annoying if there is an actual fire

**Comment by NanoCats** [comment]
Alarms are super fucky imho, especially when you visualize them with Canary. 

I can enter a room, the alarm is yellow light !-ing at me and nothing is wrong, it's pressurized with ideal air mix at a good temp. And yet "area atmosphere alarm!"  that I can't clear

**Comment by cacogen** [comment]
#64335

**Comment by timothymtorres** [comment]
Duplicate of #59043
