### ISSUE TITLE
Skittish perk lets you dive into burial mounds, which you can't get out of (quickly) without a shovel

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#64454]
Reporting client version: 514.1571

## Round ID:
[177319](https://scrubby.melonmesa.com/round/177319)

## Testmerges:
- [Revert "Make more use of <tool>_act"](https://www.github.com/tgstation/tgstation/pull/64449)
- [Subsystems now track their avg and last tick allocations](https://www.github.com/tgstation/tgstation/pull/64448)

## Reproduction:

1. Have Skittish perk
2. Walk into burial mound, you dive in and it locks behind you
3. Try to get out, it will tell you you need a shovel
4. Resist and wait 1:30 to get out of it
5. (Optional) Die when your oxygen tank runs out while alt+tabbed out of the game waiting for the resist to finish

**Comment by ATH1909** [comment]
![image](https://user-images.githubusercontent.com/42606352/151202184-6c7c7940-28ee-497e-bcfb-478a70c7db64.png)

**Comment by Bawhoppen** [comment]
This seems too funny to be a bug

**Comment by SomeDongus** [comment]
im just imagining imagining some felinid suffocating in a burial tomb after being trapped for an hour because they thought the skittish quirk would make them cute or some shit

**Comment by SuperNovaa41** [comment]
You are weird

**Comment by cacogen** [comment]
>This seems too funny to be a bug

It's similar to the bug that existed with Skittish that caused people to jump into abandoned crates, which then exploded

**Comment by interestingusernam3** [comment]
@SomeDongus 
![11fb316ea314132d049292ff9995cfd77be97a0c_orig](https://user-images.githubusercontent.com/51925758/151554688-f8381a51-b267-4096-90e1-190410cde3ea.jpeg)
