### ISSUE TITLE
You Can Not Become A Roundstart AI

### ISSUE THREAD

**Issue by SomeDongus** [tgstation/tgstation#64456]
## Round ID:
[177276](https://scrubby.melonmesa.com/round/177276)

## Reproduction:
Set AI to high, set every other job to none. Upon roundstart, you will spawn either as an Assistant, a random job, (Or be booted back to menu if that's your preference? Haven't test this.) depending on your preferences. You might be thinking that someone else got AI instead of you, but you'd be mistaken. Checking your PDA shows that there is infact no AI on station. You **CAN** become a late-join AI, which is why I'm suspecting this has gone unnoticed for a while. 

_Round ID might not be correct, this happened over multiple rounds yesterday, so I'm unsure. This could've been a fever dream for all I know. Test it out for yourself._

**Comment by Kubisopplay** [comment]
I didnt change too much in logic of that proc, so this shouldnt be cause by me. It you can reproduce it in any way i could try to help but...

**Comment by SuperNovaa41** [comment]
I get AI on local all the time, it may just be because of bagils lowpop, different roles get different weights. I'll see if i can get AI on latest

**Comment by zxaber** [comment]
https://tgstation13.org/parsed-logs/basil/data/logs/2022/01/25/round-177276/manifest.txt

Logs from that round show an AI roundstart. If your only method to check was PDA, it's possible the AI disabled their messenger to hide from PDA lists. Alternatively, there *are* some AI-related runtimes at the roundstart that may have resulted in a missing messenger.

**Comment by SomeDongus** [comment]
> https://tgstation13.org/parsed-logs/basil/data/logs/2022/01/25/round-177276/manifest.txt
> 
> Logs from that round show an AI roundstart. If your only method to check was PDA, it's possible the AI disabled their messenger to hide from PDA lists. Alternatively, there _are_ some AI-related runtimes at the roundstart that may have resulted in a missing messenger.

Right, it seems I was mistaken then.
