### ISSUE TITLE
Modsuit Anomoly Teleporter module flattens you

### ISSUE THREAD

**Issue by Nush-Kajul** [tgstation/tgstation#64458]
## Round ID:
[18595](https://scrubby.melonmesa.com/round/18595) (discovered on Fulpstation)

## Reproduction:
1: enable modsuit with teleport module installed
2: start to teleport
3: get stunned during the animation
4: become flat

## Evidence of the bug:
![image](https://user-images.githubusercontent.com/83676900/151206062-ecd2c619-8a4e-4d23-99a0-4408413b7251.png)
(its hard to see but im the very thin line going across the captains face)

https://user-images.githubusercontent.com/83676900/151213201-7950c4f9-eccd-49d0-ae6c-29781e8ecc8f.mp4

(I created a TGstation Private server of the most recent code from 26/01/2022 and recreated the bug)

**Comment by ATH1909** [comment]
if this gets patched out, we should at least add some kind of (less extreme) flattening/shrinking modsuit module, it'd be funny

**Comment by Nush-Kajul** [comment]
i agree its funny however the bug currently is permanent

**Comment by Serxule** [comment]
> i agree its funny however the bug currently is permanent

i mean its literally just a combat buff, you become extremely hard to click
