### ISSUE TITLE
Monkeys who lose their tail organ still appear to have a tail

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#64466]
Reporting client version: 514.1575

## Round ID:
[177356](https://scrubby.melonmesa.com/round/177356)

## Testmerges:
- [Refactors pay stands + custom vendors](https://www.github.com/tgstation/tgstation/pull/63889)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/151286996-27dd8f32-da39-4bdc-8282-6b1f3a9d674f.png)

**Comment by IndieanaJones** [comment]
Monkeys are really fucky with their visuals.  When you turn someone into a monkey, any items that don't get unequiped (ex. backpacks) become invisible until taken off and re-worn.
