### ISSUE TITLE
Landing in a closed turf using the wizard's rod form causes you to gib, even though the turf is destroyed

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#64468]
## Round ID:
[177355](https://scrubby.melonmesa.com/round/177355)

## Reproduction:

- Use Rod Form
- Land exactly on a closed turf
  - By "Land" I mean land the max range of the rod exactly on the turf.
- Gib, immediately
- The turf is destroyed anyways

I THINK this is because Rods cause a highturf explosion on the turf and something was refactored with explosions recently. 
![image](https://user-images.githubusercontent.com/51863163/151289248-041179b9-273c-4e77-b043-114d748f792f.png)

**Comment by jacklecroy** [comment]
Might as well get rid of the gib altogether.
