### ISSUE TITLE
Sneakers and Other Items Are Broken for Mapping

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#64470]
## Reproduction:

Boot up SDMM
Try to spawn in any set of sneakers (excluding the rainbow ones)
See below

![image](https://user-images.githubusercontent.com/34697715/151308478-12470541-7b21-4999-a1ba-0561c974ff07.png)

I don't know GAGS well enough (right now) to know how to fix this, but I'm putting it here because it just recently showed up.

**Comment by timothymtorres** [comment]
This happens because whenever icons get converted to GAGS they lose their mapping icons since instead they get generated during game.

**Comment by san7890** [comment]
This was fixed in #71469.
