### ISSUE TITLE
Drones delete circuits trying to put them into machines

### ISSUE THREAD

**Issue by Kubisopplay** [tgstation/tgstation#64508]
Reporting client version: 514.1568

## Round ID:
[177436](https://scrubby.melonmesa.com/round/177436)

## Testmerges:
- [Subsystems now track their avg and last tick allocations](https://www.github.com/tgstation/tgstation/pull/64448)

## Reproduction:
Be a drone
Put circuit into machine
Realize something is not as it should be, because the circuit disappeared.
Same for airlock circuits

**Comment by SuperNovaa41** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/64455
