### ISSUE TITLE
Exploding a disposals loop straight up deletes people.

### ISSUE THREAD

**Issue by oklews** [tgstation/tgstation#64515]
## Testmerges:
Not important

## Reproduction:

Cause disposals loop until multiple folk get stuck, create heavy explosion, watch as there's only one survivor. Crash the server looking at linear runtimes.

**Comment by Mooshimi** [comment]
Any gibs? Strong explosions on the same tile as/next to players can just splat them into goop.

**Comment by Mooshimi** [comment]
Unknown if related to #26512

**Comment by timothymtorres** [comment]
This should have been fixed with #63694 

> Any gibs? Strong explosions on the same tile as/next to players can just splat them into goop.

I think that's what happened as well.  Any mobs on the same tile for a strong explosion get instagibbed.  They all probably were in the same pipe segment.
