### ISSUE TITLE
Goliaths don't move after you shoot them

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#64510]
## Testmerges:
#64448: 'Subsystems now track their avg and last tick allocations' by MrStonedOne at commit 2b60f7c0e9
#64280: 'Ballistic to Energy: Autorifles for Thermal Pistols' by necromanceranne at commit 0b61cefe06

## Reproduction:
watch a goliath from far enough away to avoid aggro
it ambles about slowly as expected
shoot it
it stops moving, only doing its tendril attack
even if you're hit by its tendril attack it won't move towards you

**Comment by timothymtorres** [comment]
Related to #64198 and #63886
