### ISSUE TITLE
Ethereal , various problems

### ISSUE THREAD

**Issue by Djaub** [tgstation/tgstation#64517]
Reporting client version: 514.1575

## Round ID:
[177452](https://scrubby.melonmesa.com/round/177452)

## Testmerges:
- [Subsystems now track their avg and last tick allocations](https://www.github.com/tgstation/tgstation/pull/64448)

## Reproduction:

Mainly two problems since yesterday/today:
- I got blood Overcharge (charged too long in a cyborg charger) but the moodlet didn't actualize in time: I've gone to the sad face when you need to eat, at the smiling face when it was too late. Similar, clicking on the mental status should say negative things about the blood overcharge but I have the standard "I feel the power in my veins".
To clarify, I don't know if the Blood Overcharge hud icon wasn't supposed to happen, or if the mental status wasn't updated.

- Right Click on an APC should allow an Ethereal to "eat" electricity out of it. But since at least yesterday, it only lock/unlock/access denied. Non-fighting intent right click/left click does the same thing. Ethereal can't feed on APC anymore. I suppose that a bug.

EDIT: Second problem seems to be a byproduct of #64352 and mentioned in #64485 too.

**Comment by oklews** [comment]
the second part is intentional, otherwise you'd have a race of power sinks

**Comment by Djaub** [comment]
Well, it wasn't a problem until a few days ago and it's definitely not balanced around this change;
- lights are way too slow to feed off (you need to do it multiple times in a row and you have a action bar that's pretty slow too),
- Borg charger can't be accessed freely, except for the dorm one, if it isn't destroyed.

I truly hope it wasn't intentional...

**Comment by ATH1909** [comment]
there's a bunch of weirdness around the overcharged/undercharged warnings, IIRC

**Comment by Amrabol** [comment]
@oklews ethereals were able to eat power from apc for a long time ago. They were not able to eat from APC's with power below 50% to not act like powersinks. That APC change made ethereals eating even worse than normal. Previously it would take a min or two to get back to being "I feel the power in my veins". Now as its not possible it gets kidna harder. Lightbults gives a little. Cells give 3% but at the same time getting bigger cells is harder as you can empty small cells in like 4-5 eats. There is only one public borg charger that is not upgraded and not a lot of people knew about it. Fully upgraded chargers are also a bane for ethereals as being one sec too long will make you take constant toxin damage for some time with also chance to shoot bolt that hacks nearby machines and hurts others. If you want to see how bad ethereal power is try playing with base metabolic boost virus
