### ISSUE TITLE
Xeno Tail Going through solid objects 

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#64534]
Reporting client version: 514.1578

## Round ID:
[177476](https://scrubby.melonmesa.com/round/177476)

## Testmerges:
- [Refactors pay stands + custom vendors](https://www.github.com/tgstation/tgstation/pull/63889)
- [Fix the mc getting completely fucked in the brain due to background ticker subsystems](https://www.github.com/tgstation/tgstation/pull/64500)

## Reproduction:
I was fitting a xeno queen all fine in space then when it was one shoot away from being death it did a tail whip and I though well im behind a solid sturdy metal girder no way it ca.... it whooped my ass into the ground stam critted and so I died

Not sure if this is intentional but I dont see why a physical attack should go through solid objects
![image](https://user-images.githubusercontent.com/84478872/151650085-661f8d8e-ce88-4cba-b92d-74023eaa009e.png)

**Comment by Mooshimi** [comment]
ided...

**Comment by SethLafuente** [comment]
> ided...

very ded....

**Comment by timothymtorres** [comment]
A girder is not the same thing as a wall, there are gaps and openings inside it.  The xeno tail is an AoE spell so I don't think this is a bug @Mooshimi
