### ISSUE TITLE
Icebox evac will sometimes leave without sections

### ISSUE THREAD

**Issue by jlsnow301** [tgstation/tgstation#64546]
## Round ID:
 This happened on 177517 and other prior times

## Testmerges:
Current

## Reproduction:
So I had moved to the bottom left corner of Icebox evac, waiting for the shuttle to take off. When it did, the entire room, along with everyone in it, remained attached to the station. The rest of the shuttle(presumably) took off.

This problem also occurs when you replace floors on the shuttle before it leaves.

I don't think it registers what's connected to the shuttle as much as it is just an initial area, or initial tiles, and anything else is just left behind.

**Comment by MrMelbert** [comment]
Happened on 177524, relevant runtime

![image](https://user-images.githubusercontent.com/51863163/151686064-53a05df0-7ebc-402c-8305-95a8c2250c6e.png)

**Comment by Mothblocks** [comment]
@MrMelbert That's because whoever wrote that code doesn't know how lists work.

"old_contents" is not the old contents. It's the current contents. Whenever the contents update, that list updates too, and we're using outdated values on it.

**Comment by Mothblocks** [comment]
Using `for (var/atom/movable/moving_atom in oldT.contents)` would fix this because that copies the entire list internally
