### ISSUE TITLE
Plasmaman modsuits dont need to be enabled

### ISSUE THREAD

**Issue by Nush-Kajul** [tgstation/tgstation#64543]
## Round ID:
 tested on a private server

## Reproduction:
1: Spawn as plasmaman
2: ask robotics to provide a plasma stabilizer modsuit module
3: equip it to your suit and place it on your back
4: become immune to spontaneous combustion from atmosphere 

## Evidence:

https://user-images.githubusercontent.com/83676900/151679744-d1f861b3-4c26-4b93-aea7-f8e1ef333c15.mp4

**Comment by Fikou** [comment]
intended
