### ISSUE TITLE
Infinite Pizza Bug

### ISSUE THREAD

**Issue by MrNihil** [tgstation/tgstation#64563]
## Testmerges:

Round ID: [177547](https://scrubby.melonmesa.com/round/177547)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: 935497a893364cfcb9f120e507dfc9ae8f09497d
The following pull requests are currently test merged:
#64280: 'Ballistic to Energy: Autorifles for Thermal Pistols' by necromanceranne at commit 0b61cefe06
#64448: 'Subsystems now track their avg and last tick allocations' by MrStonedOne at commit 2b60f7c0e9
#64500: 'Fix the mc getting completely fucked in the brain due to background ticker subsystems' by MrStonedOne at commit 21edc2e412

Local commit: 1f475ef74f23c46febb488ce74cc9b546fe04431
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:

1. Order pizza from console
2. Receive pizza
3. Open box (I used default Z button) and get out pizza
4. Close the box (dont scrap it) (again, I used Z button)
5. return to step 3

Video: https://youtu.be/9oXcnDVqQXo

**Comment by AdipemDragon** [comment]
That's.... genuinely just the anomalous pizza box, isn't it.

**Comment by davethwave** [comment]
Probably. Don't think this is a bug.

**Comment by Mooshimi** [comment]
> Probably. Don't think this is a bug.

Then admins don't know about it anymore, since I got this twice and ahelped, both said "oh, that's a weird bug, funky. Enjoy the free pizza!"

**Comment by Sealed101** [comment]
this isn't a bug but a random chance of an anomalous pizza box. it's even logged as such. this is just sad

![image](https://user-images.githubusercontent.com/75863639/151714589-0481e4b5-35ee-4837-b357-3682c29a44ba.png)

**Comment by timothymtorres** [comment]
Free bluespace pizza for everyone!

**Comment by NanoCats** [comment]
> That's.... genuinely just the anomalous pizza box, isn't it.

I feel like there should be some kind of indication that this shit isn't a bug because guess what? I too reported this as a bug once because I had no reason to believe I had become the owner of a magic box of pizza. 

Something like a description that says "Another pizza immediately appears in the box, what the hell?" or an alteration to the description.

I got randomly hit with the nanomachine pizza and I thought I'd been griefed, an admin didn't know how the fuck someone got nanomachine reagents, and they changed me back to human before anyone figured it out.

**Comment by timothymtorres** [comment]
> Something like a description that says "Another pizza immediately appears in the box, what the hell?" or an alteration to the description.

Feel free to add a `to_chat(user, span_notice("Insert pizza message here"))` in a PR to rectify this.  It shouldn't take more than a couple of minutes.

https://github.com/tgstation/tgstation/blob/1e7e4f58d022b2c29c69a8bd23c0cc6cf29a4b99/code/modules/food_and_drinks/pizzabox.dm#L363-L366

**Comment by NanoCats** [comment]
> > Something like a description that says "Another pizza immediately appears in the box, what the hell?" or an alteration to the description.
> 
> Feel free to add a `to_chat(user, span_notice("Insert pizza message here"))` in a PR to rectify this. It shouldn't take more than a couple of minutes.
> 
> https://github.com/tgstation/tgstation/blob/1e7e4f58d022b2c29c69a8bd23c0cc6cf29a4b99/code/modules/food_and_drinks/pizzabox.dm#L363-L366

**attune** to the pizza

**Comment by AdipemDragon** [comment]
>I feel like there should be some kind of indication that this shit isn't a bug

Oh no yeah I fully agree that it's not fully conveyed to the player itself that that specific pizza box Is infinite.
Literally the only other tell, other than the infinizza itself, is that there's an automatic CC message printed from communication consoles that's like "hey, there's an anomalous object, send it back through cargo", which _doesn't even say what the object is_ and is _Limited To Command_, which usually has better things to do than hunt down the chef nullifier pizza box

**Comment by timothymtorres** [comment]
https://user-images.githubusercontent.com/5195984/151853891-42c718b2-0df6-4288-940a-f4a9ae2c01a0.mp4

Guys it took me a shorter amount of time to fix this than the time it took to create and discuss this bug report, lol.  If you need help doing things like this in the future you can ask for help in the coder discord.  Simple `to_chat` or `log()` messages can easily be done with web edits on Github.

**Comment by NanoCats** [comment]
> Guys it took me a shorter amount of time to fix this than the time it took to create and discuss this bug report, lol. If you need help doing things like this in the future you can ask for help in the coder discord. Simple `to_chat` or `log()` messages can easily be done with web edits on Github.

Won't the coders complain if you publish a PR you made exclusively on the web without testing it in game? Caught in 4k /s


also I'm just here to provide unwanted feedback so the maintainers can ignore it from their ivory towers and also report bugs, I don't write code.

**Comment by timothymtorres** [comment]
For normal code changes yes.  For spelling, grammar, and logging messages it shouldn't be a big deal.

I'm just showing how easy it is to make these small fixes.  You just need a GitHub account and know how to search the code for information.

**Comment by optimumtact** [comment]
webeidtor

**Comment by JohnFulpWillard** [comment]
There's a centcom report when this happens so I don't see it as a problem.
https://github.com/tgstation/tgstation/blob/1e7e4f58d022b2c29c69a8bd23c0cc6cf29a4b99/code/modules/cargo/packs.dm#L1954

**Comment by timothymtorres** [comment]
> There's a centcom report when this happens so I don't see it as a problem.

That was pointed out in the PR but only command staff have access to that.
