### ISSUE TITLE
`get_chem_id` always gives fakebeer when the input is `beer`

### ISSUE THREAD

**Issue by SuperNovaa41** [tgstation/tgstation#64569]
Tested locally

This is an issue because the debug chem synthesizer, and more importantly the reaction chamber, uses this for their main function. So you aren't actually able to print out real beer with the synthesizer, or accept real beer with the reaction chamber.

https://github.com/tgstation/tgstation/blob/0da87768eacb94185780033554f7c5b838ca0ff8/code/__HELPERS/reagents.dm#L193-L197

the name of fakebeer is the same as beer

**Comment by timothymtorres** [comment]
Unreleated but fakebeer should just be regular beer diluted with a bunch of water.

**Comment by SuperNovaa41** [comment]
no fakebeer is a poison

**Comment by Donpedrito** [comment]
For context, fake beer is the instant knockout chem that as far as I know is only available on an illegal module for service cyborgs. It's intentionally named "beer" in order to fool unsuspecting victims, which is probably what causes this bug.
