### ISSUE TITLE
Thieves can roll to steal an heirloom while running the heirloom quirk

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#64568]
Reporting client version: 514.1571

## Round ID:
[177556](https://scrubby.melonmesa.com/round/177556)

## Testmerges:
Didn't seem to touch the antag so I didn't link em

## Reproduction:
![image](https://user-images.githubusercontent.com/76874615/151705817-b8a25407-da85-4876-aac9-878c4b78b80a.png)
I dunno, but this seems like an oversight; if antags aren't allowed, mechanically, to just steal something from their own department and call it a day (like that recent "HoP thieves not allowed to steal a hand tele" pr), I feel like this kind of situation should be avoided too.

**Comment by SuperNovaa41** [comment]
did you actually get the greentext for it or are you just assuming you would?

**Comment by SuperNovaa41** [comment]
https://github.com/tgstation/tgstation/blob/0da87768eacb94185780033554f7c5b838ca0ff8/code/modules/antagonists/thief/thief_objectives.dm#L98-L111

https://github.com/tgstation/tgstation/blob/0da87768eacb94185780033554f7c5b838ca0ff8/code/modules/antagonists/thief/thief_objectives.dm#L109

you just guessed

**Comment by AdipemDragon** [comment]
No yeah that's fair, I _did_ assume, the circumstances of the shift didn't allow to see if that person Would greentext that specific situation so I just sent this to be sure.
