### ISSUE TITLE
Buckling to operating table doesn't update your sprite to lying position

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#64575]
Reporting client version: 514.1571

## Round ID:

I noticed this while working on a PR locally, don't know which commit I was on

## Reproduction:

1. Buckle to an operating table (you may need a handcuffed mob to do it, or change the table's var to allow buckling without handcuffs)
2. You are visually standing up
3. For all intents and purposes, you are lying down (when you unbuckle and crawl onto an adjacent tile, your sprite will immediately update to be lying down)

**Comment by Sealed101** [comment]
can no longer reproduce; there's https://github.com/tgstation/tgstation/pull/75840 but i have a feeling this was fixed elsewhere
