### ISSUE TITLE
PR updates cannot be toggled in the chat tab 

### ISSUE THREAD

**Issue by NanoCats** [tgstation/tgstation#64573]
## Reproduction:

PRs show up in chat now when they are posted, Great! Problem though, I see this as a bit of an oversight because they don't get their own tickbox in the chat controller for tabs, so I can't make a "Just PRs" tab for example, (they get lumped in with "info" if I recall correclty)

**Comment by SuperNovaa41** [comment]
![image](https://user-images.githubusercontent.com/16159590/151844158-a0138dde-fd20-48cb-b09f-772135149548.png)

**Comment by NanoCats** [comment]
> ![image](https://user-images.githubusercontent.com/16159590/151844158-a0138dde-fd20-48cb-b09f-772135149548.png)

![image](https://user-images.githubusercontent.com/14065903/151871727-8d2f4021-7563-4efb-9ea6-4e6dbea0c1bb.png)
Yes but what you've failed to realize is that they are shunted into the "Info" tab, the info tab also houses critical game information.


This means I'm unable to say,  make one tab that's just "PRs" or "News" or whatever.
