### ISSUE TITLE
Tramstation robotics disposals is broken

### ISSUE THREAD

**Issue by Donpedrito** [tgstation/tgstation#64570]
## Round ID:
Irrelevant, I've noticed this on several different rounds, often roundstart.

## Testmerges:
#64448 

## Reproduction:
Place something in the robotics disposal bin. In the image, the thing placed is that glass. It will launch out of the floor, causing that floor tile to be removed like it was crowbarred. If you replace the tile, it gets removed again once something else is sent through the bin.
![image](https://user-images.githubusercontent.com/22182585/151720274-69c6e011-212e-44b9-a75a-220407e1cc0f.png)

**Comment by Donpedrito** [comment]
Update: This occurred in the same spot, with objects from an unknown disposals bin. No idea what's going on with the pipes here, I don't know disposals.
![image](https://user-images.githubusercontent.com/22182585/151720411-c1f44530-b685-4e4b-b053-b0647f546108.png)

**Comment by Donpedrito** [comment]
Sorry to like, triple post but it seems the issue is misaligned pipes.
![image](https://user-images.githubusercontent.com/22182585/151721232-dec55793-e74e-4cd1-a167-d7559245073c.png)

**Comment by timothymtorres** [comment]
@Donpedrito good detective work!  Thanks for providing a SS.

**Comment by Donpedrito** [comment]
This is now fixed by #64584.
