### ISSUE TITLE
Mobs appear in front of things they should be behind

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#64576]
Reporting client version: 514.1571

## Round ID:
[177583](https://scrubby.melonmesa.com/round/177583)

## Testmerges:
- [Subsystems now track their avg and last tick allocations](https://www.github.com/tgstation/tgstation/pull/64448)
- [Ballistic to Energy: Autorifles for Thermal Pistols](https://www.github.com/tgstation/tgstation/pull/64280)

## Reproduction:

1. Slide under AI
2. When you stand up, you are in front of the AI
3. Buckle onto north facing chair
4. You are on top of the chair
5. Walk behind cryo tube or Christmas tree
6. You are in front of the tree

**Comment by Donpedrito** [comment]
Can corroborate, this happened when trying to use the hide button to hide behind a table as an alien larva.

**Comment by Likteer** [comment]
#64078

**Comment by cacogen** [comment]
I did search for a duplicate but none of the terms I used brought your issue up
