### ISSUE TITLE
Sentient disease host jump VS. World border void

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#64585]
Reporting client version: 514.1571

## Round ID:
[177606](https://scrubby.melonmesa.com/round/177606)

## Testmerges:
Seemingly irrelevant

## Reproduction:
Be a sentient disease (yay)
Have several hosts
One gets sick of the shift and trails off of the map to log off, hitting the edge of the world in the process.
![image](https://user-images.githubusercontent.com/76874615/151819464-9ec4c01e-bd19-4bb1-a7c7-6b4f0ac0d2ba.png)
Enjoy being unable to press the direction the void is in to switch hosts when observing this specific corpse.

**Comment by Sealed101** [comment]
sentient disease has been retired as of #83453
