### ISSUE TITLE
Manually turning off firealarms causes the light tubes to burn out

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#64591]
## Round ID:
[177628](https://scrubby.melonmesa.com/round/177628)

## Reproduction:
Right click an active firealarm.

**Comment by timothymtorres** [comment]
I tested this right now on local and was unable to reproduce.  Are you sure that fire didn't burn the APC or destroy the lights?

**Comment by MrMelbert** [comment]
There;s definitely to something to this. 

I had an Icebox round which had (cold air) airlock problems in the hallway.
Every time the firelocks fell and raised all of the light fixtures in the main hall burnt out. I replaced like 60 over the entire round.

**Comment by LemonInTheDark** [comment]
What does burn out mean?

**Comment by Donpedrito** [comment]
> What does burn out mean?

When it's too hot in an area, light tubes/bulbs will burn out. This does almost exactly the same thing breaking a light does, and it's fixed the same way, with a new tube/bulb or a light replacer. The only differences are the sprite and (I think) burned out lights don't spark.

**Comment by Serxule** [comment]
i thought burnt out lights was just a light dying, as i've only ever seen heat break lights

**Comment by Likteer** [comment]
> I tested this right now on local and was unable to reproduce. Are you sure that fire didn't burn the APC or destroy the lights?

@timothymtorres I am certain. The atmos (not even heat iirc) was strong enough to turn the firealarm on, but not to burn out the lights. 

It was easy to assume more of the hazardous air flew, but as I (and Melbert) observed, it happened immediately upon manual alarm release every single time, when the light tubes were supposed to switch from emergency red to normal hue.

Also, it only happened when the firelocks were auto-toogled, but released manually via right click on a fire alarm.

**Comment by Inari-Whitebear** [comment]
Well, there is a burnout that happens if you flip them too often or the like... but it's meant to reset when you replace the light

**Comment by MacBlaze1** [comment]
> > I tested this right now on local and was unable to reproduce. Are you sure that fire didn't burn the APC or destroy the lights?
> 
> @timothymtorres I am certain. The atmos (not even heat iirc) was strong enough to turn the firealarm on, but not to burn out the lights.
> 
> It was easy to assume more of the hazardous air flew, but as I (and Melbert) observed, it happened immediately upon manual alarm release every single time, when the light tubes were supposed to switch from emergency red to normal hue.
> 
> Also, it only happened when the firelocks were auto-toogled, but released manually via right click on a fire alarm.

you're saying this has been reproduced?

**Comment by Likteer** [comment]
I don't think this happens anymore
