### ISSUE TITLE
Aggrograbs and Neckgrabs are inescapable

### ISSUE THREAD

**Issue by Rustybuckets6601** [tgstation/tgstation#64597]
Reporting client version: 514.1575

## Round ID:
[177641](https://scrubby.melonmesa.com/round/177641)

## Testmerges:
- [Subsystems now track their avg and last tick allocations](https://www.github.com/tgstation/tgstation/pull/64448)
- [Ballistic to Energy: Autorifles for Thermal Pistols](https://www.github.com/tgstation/tgstation/pull/64280)

## Reproduction:
Get two carbons, neckgrab one, have the other try to escape. No resist message or stamina damage.

**Comment by GoblinBackwards** [comment]
This is happening with any kind of aggro grab, not just neckgrabs.

**Comment by Rustybuckets6601** [comment]
> This is happening with any kind of aggro grab, not just neckgrabs.

Damn you right

**Comment by Fhaxaris** [comment]
Happens to me aswell.

**Comment by SethLafuente** [comment]
this should have a more urgent title is literary game braking

**Comment by Rustybuckets6601** [comment]
> this should have a more urgent title is literary game braking

I dunno what else to call it lol, I'm surprised it hasn't been fixed yet too. Maybe I'll edit the name to include aggro grabs.
