### ISSUE TITLE
Ice Box's Clear Skies

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#64607]
## Round ID:
[177673](https://scrubby.melonmesa.com/round/177673) but its been seen in previous ones too

## Testmerges:
Not relevant to mapping 

## Reproduction:
![snow](https://user-images.githubusercontent.com/76874615/152020130-9dfac4ce-1080-40a6-828f-caa84b17f887.gif)
(I can only guess that it's been a thing since the Icebox Labor Camp Remapping)

**Comment by san7890** [comment]
This has probably always been a thing because of how snow generates in certain areas on IceBox, and I don't think that there was a specific PR that fixed it. That being said, I'll probably look into changing how this all works and making sure I don't break anything along the way.
