### ISSUE TITLE
Hoverboards are slow as shit

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#64603]
## Testmerges:
#64541: 'Adds basic list manipulation and fixes some performance issues with lists' by Watermelon914 at commit eebe0c5936
#64448: 'Subsystems now track their avg and last tick allocations' by MrStonedOne at commit 2b60f7c0e9
#64564: 'Improves proccall admin circuit component. Adds the option to not resolve weakrefs for set variables and proccall admin circuit components.' by Watermelon914 at commit f16b41a33e

## Reproduction:
 Hoverboards are slower than just walking. Not how it used to be and pretty lame for a thousand+ credit item to be worse than heelies

**Comment by itseasytosee** [comment]
From what I understand they are the exact same speed as heelies. They are better because they take less stamina damage while grinding and stuff. Not intended to be faster.

**Comment by Dorsisdwarf** [comment]
> From what I understand they are the exact same speed as heelies. They are better because they take less stamina damage while grinding and stuff. Not intended to be faster.

Heelies have no vehicle slowdown, hoverboards have vehicle slowdown 1.5, which I guess now makes them slower than walking

**Comment by optimumtact** [comment]
this isn't a bug
