### ISSUE TITLE
Map population limits are being ignored/non-functioning

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#64618]
Reporting client version: 514.1561

## Round ID:
[177701](https://scrubby.melonmesa.com/round/177701)

## Testmerges:
- [Improves proccall admin circuit component. Adds the option to not resolve weakrefs for set variables and proccall admin circuit components.](https://www.github.com/tgstation/tgstation/pull/64564)
- [Adds moveloop bucketing, uses queues for the singulo rather then sleeps](https://www.github.com/tgstation/tgstation/pull/64418)

## Reproduction:
* Get over 40 people on the server
* Have them vote for a map
* Kilo is still on the list despite being disabled at higher populations

@Mothblocks says the variable is set, it just... doesn't work, for some reason. This should probably get fixed since high population on Kilo is absolute fucking hell.

**Comment by dragomagol** [comment]
https://tgstation13.org/phpBB/viewtopic.php?p=624292#p624292
