### ISSUE TITLE
Hair Above headwear 

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#64621]
Very Simple hair especially hair styles that are bigger than most hats sticks out of hats examples are, fedoras, top hats and berets and literary every other hat that is smaller than the hair sprites you have is a clear visual bug that annoys me a lot and probably others.

**Comment by Donpedrito** [comment]
Which hairstyle is it? IIRC the CIA hair used to have this issue but I think it was fixed a while back.

**Comment by SethLafuente** [comment]
> Which hairstyle is it? IIRC the CIA hair used to have this issue but I think it was fixed a while back.

I specifically said Wisp Hair in the post  I can highlight it

**Comment by timothymtorres** [comment]
Kapu claims this isn't a bug.  Can you add a screenshot to see if this is intended or not.

**Comment by Mooshimi** [comment]
the spiky ponytail also does this, but there would be no real way to change this besides going back to it making hair gone with any hats

**Comment by Kapu1178** [comment]
> Kapu claims this isn't a bug. Can you add a screenshot to see if this is intended or not.

It's not a bug, its a product of how hair works.
Hats are over the hair layer, and hats can have a flag that says "don't hide the hair" so that the normal person non-tumblr hairstyles look nice.

If what you're layering over is larger than the layer on top, it's gonna poke out. That's just how images work.

**Comment by SethLafuente** [comment]
Yes it is use a detective hat with the wisp hairstyle

**Comment by Kapu1178** [comment]
> Yes it is use a detective hat with the wisp hairstyle

I just explained how its not a bug.

**Comment by SethLafuente** [comment]
Im kind of confused you made a or 9 days ago referencing my issue fixing it and you are saying it isn't a bug I don't think wisp haircut is meant to go over the top of the detective hat

**Comment by Kapu1178** [comment]
> Im kind of confused you made a or 9 days ago referencing my issue fixing it and you are saying it isn't a bug I don't think wisp haircut is meant to go over the top of the detective hat

![image](https://user-images.githubusercontent.com/75460809/185259152-74160ac9-dd82-4985-8736-5bd343c6e75a.png)

**Comment by SethLafuente** [comment]
Im returning to this because is simply ridiculous that we are arguing about this clear issue alright clear everything we said before

As of now right now if you have hats such as HoS hat detective hat etc literary any hat your hair sprites incorrectly go over the hat
this shouldnt be happening plus something else that happens with mask if their sprite overlay is bigger than a head mask you were they pick through making it look bad too
Some examples
![image](https://user-images.githubusercontent.com/84478872/194720944-0136f16e-8316-4daf-a489-fd4413e7e24b.png)
![image](https://user-images.githubusercontent.com/84478872/194720954-f4d7d0f4-bad0-409b-ae42-4109b0127944.png)
![image](https://user-images.githubusercontent.com/84478872/194720958-bb5533ce-3056-4d46-a425-a3fed6490cd2.png)
![image](https://user-images.githubusercontent.com/84478872/194720964-67600f63-e2ac-4788-ad6e-eb3e189b3364.png)

This isn't unique to this haircut this happens with every haircut that is bigger than the hat you wear

**Comment by Kapu1178** [comment]
This is NOT a bug. FFS. This is just a consequence of how layers work. Either hats "cover" (read: hide completely) hair, or they dont do anything at all.
