### ISSUE TITLE
Bluespace bodybags delete you

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#64631]
## Testmerges:
#64280 #64448 

## Reproduction:

https://user-images.githubusercontent.com/75639936/152258117-36a5822d-3cf3-4882-92a4-b4d8cf297f00.mp4

**Comment by necromanceranne** [comment]
Maybe related to this https://github.com/tgstation/tgstation/issues/63343

Hmm...bad bug to say the least.

**Comment by Mothblocks** [comment]
:wave:

**Comment by optimumtact** [comment]
feature

**Comment by Shadowflame909** [comment]
Bluespace is very delicate and unknown technology.

It was discoveries like this that leads future nanotransen to develop their chrono legionnaires.

**Comment by timothymtorres** [comment]
Fixed by #69529
