### ISSUE TITLE
Recyclers recycle their own stock parts and board when deconstructed, in one final act of defiance.

### ISSUE THREAD

**Issue by Donpedrito** [tgstation/tgstation#64632]
## Round ID:
177745

## Testmerges:
N/A

## Reproduction:
I built a recycler as a drone on KS13. When I screwdrivered, then crowbarred it in order to move it (I know now that you can just wrench them) it made a recycling sound, and the board, the matter bin, and the micro-manipulator I had used to build it were gone.

**Comment by SuperNovaa41** [comment]
Can confirm, this happened to me a shitload while i was testing recycler fixes, somehow i forgot to report it

**Comment by Donpedrito** [comment]
Ah I forgot to mention, #52779 mentioned a similar issue, but it's very old and wasn't reproduced so I decided to make a new report; if this issue's fixed that one should be too.

**Comment by tgsAvylaar** [comment]
I can confirm this aswell, and throughout the years this has always been the case for me.
