### ISSUE TITLE
Spamming grenades without a payload floods admin chat with messages and can crash them. 

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#64640]
## Reproduction:
Step one make a non explosive grenade.
Step two spam activate it. (Although thats not how this incident happened its roughly the same steps)

Step three....

![sentientgrenadesp2](https://user-images.githubusercontent.com/62126254/152287365-94e524bd-dea7-4e29-98b0-9537e3e6f99a.png)
![sentientgrenadesp1](https://user-images.githubusercontent.com/62126254/152287374-4c05b5a8-3014-4cc4-88fe-e28d6890c8d8.png)

I`m not sure if i should include this in the same issue report but I wasnt actually the one triggering the circuit grenades, I was turning posibrains into sentient plushies by putting them into an assembly circuit and then attaching them to a grenade and giving those grenades a nonlethal payload that they could activate, what ended up happening was the posibrain players used their payload on the evac shuttle then got bored and started spamming the detonate key and then I got bwoinked.

Considering that just a player spamming a keypress can be enough to crash the admins, you could very easily outdo that 100x and make an admin ddos machine by binding 2 circuit radio modules to eachother in a loop and having their outputs activate a grenade which I would assume would be pretty bad so I would say that a fix for this should be high priority.

**Comment by moocowswag** [comment]
Oh and https://github.com/tgstation/tgstation/pull/63393 I think made this possible.

**Comment by TemporalOroboros** [comment]
Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by TheVekter** [comment]
![image](https://user-images.githubusercontent.com/7019927/152405177-f46498b2-3af6-4b3b-83b4-c1a8f692c6dc.png)

FYI
