### ISSUE TITLE
Bullets log twice in attack logs

### ISSUE THREAD

**Issue by Timberpoes** [tgstation/tgstation#64659]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Players hitting other players with bullets double-logs in the attack logs, making it look like someone has shot twice as much as they actually have.

**Comment by Ryll-Ryll** [comment]
#64164 caused this by making living/bullet_act call parent so that it could send the COMSIG_ATOM_BULLET_ACT. Unfortunately, it also calls the projectile's on_hit, resulting in it being called twice on living mobs
