### ISSUE TITLE
An immortal shade is made if the sentient sword nullrod on lavaland is swapped out for a different type after being activated?

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#64679]
Reporting client version: 514.1569

## Reproduction:
I dont know all of the steps of what caused it, I clicked yes on a prompt as a ghost to become a spirit of a sword (chap nullrod)
Then it put me here
![image](https://user-images.githubusercontent.com/62126254/152630558-8c26a861-1db9-49b5-98d4-6e2cf3db828d.png)
I found the person who activated the sword to trigger the ghost poll. they had two god hands and said that it was a lavaland nullrod that they swapped out. (I don`t have much experience with lavaland content so)

**Comment by kopoba** [comment]
looks like dupe https://github.com/tgstation/tgstation/issues/61935

**Comment by moocowswag** [comment]
> looks like dupe #61935

thanks
