### ISSUE TITLE
Tramstation genpop's prison gate scanner can be bypassed easily by being inside a large cardboard box.

### ISSUE THREAD

**Issue by OneAsianTortoise** [tgstation/tgstation#64686]
## Round ID:
I don't have round ID, but I reproduced it yesterday.

## Reproduction:
Tramstation genpop's prison gate scanner can be bypassed easily by being inside a large cardboard box. Reproduction done yesterday, and it can be easily reproduced.

https://user-images.githubusercontent.com/64306407/152636675-a2aa5404-a0d6-446e-92a8-b6aef6bbfbc9.mp4

**Comment by MrMelbert** [comment]
![titlescreenbox](https://user-images.githubusercontent.com/51863163/152638151-4d150e07-a3c5-4c8c-a14b-9831a8e49f2b.png)

**Comment by ANAME593** [comment]
its funny don't fix it
