### ISSUE TITLE
The QM's Loader MODsuit has nothing in its description to let the player know it isn't spaceworthy.

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#64681]
As a player who didn't already know, I had no reason whatsoever to believe it wasn't spaceworthy.

Non-loader modsuits are all spaceworthy.

Modsuits replaced hardsuits, which were all spaceworthy.

Only this one isn't. Just this one kind.  And its description leaves out that little detail.  In fact, it says, "Protects you from various environments."  How would someone not think that includes space?

A user should not have to learn these things only by word of mouth or trial and error. It should be documented.

FIX:

Write that it's not spaceworthy in its description, preferably in all caps.

**Comment by Sealed101** [comment]
i mean uh isnt the loader suit visibly not airtight
otherwise yeah that would make sense

**Comment by Serxule** [comment]
> i mean uh isnt the loader suit visibly not airtight otherwise yeah that would make sense

not really, i always thought it looked like a full suit

**Comment by Sealed101** [comment]
i mean

![image](https://user-images.githubusercontent.com/75863639/152677632-1b7087df-a828-4d60-89e9-a4ae92c7e545.png)

**Comment by Qydra** [comment]
> i mean
> 
Keep in mind that that image is displaying that sprite at two to four times the size many players will see it as.
