### ISSUE TITLE
Locker Staff can be used to permanently roundremove players.

### ISSUE THREAD

**Issue by Bytesol** [tgstation/tgstation#64692]
## Round ID:
N/A (Bug found from a private server using TG code)

## Reproduction:
When a locker made from the staff is unwelded and opened it will eventually fade away.
As the locker is about to fade away close it on any player, item, or mob that you want to delete.
When the locker finishes fading it will permanently delete its contents, roundremoving anyone who was inside.

**Comment by Time-Green** [comment]
Immersive Gameplay
Maybe don't enter magical lockers that are being sent to the shadow realm?
