### ISSUE TITLE
Mobs are on a plane higher than objects

### ISSUE THREAD

**Issue by SmArtKar** [tgstation/tgstation#64710]
## Reproduction:

Spawn an object with layer set to ABOVE_MOB_LAYER. Spawn a mob. Find out that mobs show above object no matter their layer because they are on a higher plane.

Fuck around and find out, gentelmen.

This issue is caused because whoever made FOV had to make a different layer for some reason and now you can't have objects above mobs, even if you are laying on the floor.
`#define GAME_PLANE -4` - Object plane
`#define GAME_PLANE_FOV_HIDDEN -3`  - Mob(maybe human only?) plane right now

**Comment by Fikou** [comment]
thats not a bug
