### ISSUE TITLE
You can't rotate recyclers

### ISSUE THREAD

**Issue by JohnFulpWillard** [tgstation/tgstation#64715]
## Reproduction:

1) Open StrongDMM
2) You cant rotate recyclers in your maps.
3) Realize every single map has always used recyclers facing left and nothing else

Alternatively:
1) Go in-game
2) Screwdriver and wrench a recycler, it just unwrenches it, as there's no way to change its direction

**Comment by JohnFulpWillard** [comment]
removing the self-consuming part because https://github.com/tgstation/tgstation/issues/64632 reported it already

**Comment by Serxule** [comment]
yeah its always been this way, i have no idea why, probably just sprites or something

**Comment by Shadow-Quill** [comment]
Fixed by #78323
