### ISSUE TITLE
Used grenades are unable to have their trigger reset via screwdriver

### ISSUE THREAD

**Issue by tohg7** [tgstation/tgstation#64728]
Hello, i've been having problems with reusing grenades with the new mechanic, when i use a grenade of any kind, use wirecutters on it, then use a screwdriver on it, it says it's "Resetting the trigger" but when the progress bar completes, the trigger isn't reset and i am unable to recomplete the grenade. So i have to throw the used grenade away. I would appreciate it if you found what was causing this and fixed it.

**Comment by TemporalOroboros** [comment]
Forgot a `~`. Hold on.
