### ISSUE TITLE
Overlays for an AI viewing the Cryo Cells Are Busted

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#64737]
Reporting client version: 514.1572

## Round ID:
[177979](https://scrubby.melonmesa.com/round/177979)

## Testmerges:
- [Fixes layering issues brought by the FoV PR.](https://www.github.com/tgstation/tgstation/pull/63903)

## Reproduction:

Be an AI.
Put someone in a cryo cell.

The following will happen:
![image](https://user-images.githubusercontent.com/34697715/152728100-dce3a47d-3f7a-4df1-b098-8be183730796.png)

**Comment by timothymtorres** [comment]
This may be related to the test merge #63903
