### ISSUE TITLE
Mime can't speak through the ventriloquist dummy without breaking silence vows

### ISSUE THREAD

**Issue by tohg7** [tgstation/tgstation#64736]
Hello, this bug has been troubling me numerous times whenever i tried using the ventriloquist dummy as mime, when i try to use the ventriloquist dummy, i can't speak through it without breaking my vow of silence, hopefully, someone can fix this. This bug has been going on for a long time and it would do a service to mime mains for it to be fixed.

**Comment by timothymtorres** [comment]
This is intended #49582

**Comment by SuperNovaa41** [comment]
https://github.com/tgstation/tgstation/issues/49582#issuecomment-592409242
We should do it anyways

**Comment by Ryll-Ryll** [comment]
> [#49582 (comment)](https://github.com/tgstation/tgstation/issues/49582#issuecomment-592409242) We should do it anyways

you're welcome to PR a change to it. Honestly it seems kinda pointless to give the mime a doll and then force them to lose their powers and possibly make themselves valid to use it, but making it also a easy roundabout to the limitations of the role kinda sucks too. At least with a PR we can mount a discussion
