### ISSUE TITLE
Blindness seems to obscure HUDs

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#64751]
Reporting client version: 514.1578

## Round ID:
[178013](https://scrubby.melonmesa.com/round/178013)

## Testmerges:
- [Improves proccall admin circuit component. Adds the option to not resolve weakrefs for set variables and proccall admin circuit components.](https://www.github.com/tgstation/tgstation/pull/64564)
- [Changes how robotics control console works](https://www.github.com/tgstation/tgstation/pull/64608)
- [Changes what appears for urgent ahelps to supportmins.](https://www.github.com/tgstation/tgstation/pull/64748)

## Reproduction:

Spawn in thunderdome, VV modify organs and remove your eyes.  Notice your health marker, hands HUD etc are no longer visible, everything's black except the tiny space in the center.

**Comment by Ryusenshu** [comment]
Can confirm, 
Not the blindness though, but it also happens with damage.
The red at the border is in front of the ui, making it very hard to see

**Comment by Mothblocks** [comment]
Gonna take #64753 instead because it has a picture
