### ISSUE TITLE
Obscured vision hides the UI

### ISSUE THREAD

**Issue by horsebeater** [tgstation/tgstation#64753]
Reporting client version: 514.1557

## Round ID:
[178014](https://scrubby.melonmesa.com/round/178014)

## Testmerges:
- [Refactor: make SSrunechat to be subsystem of SStimer](https://www.github.com/tgstation/tgstation/pull/64366)
- [Changes what appears for urgent ahelps to supportmins.](https://www.github.com/tgstation/tgstation/pull/64748)

## Reproduction:

1. Have your vision obscured by sleep, a welding helmet, etc.
2. Your entire UI should now be invisible, except for the icons of the items you're holding/wearing, the chat, and the status panel.
3. Reconnecting or changing your UI style doesn't fix this.

![screenshot](https://user-images.githubusercontent.com/99220987/152883386-81fffd35-617f-4a4c-9723-7da7a184eb5a.png)

**Comment by Serxule** [comment]
happens with damage too

**Comment by Mothblocks** [comment]
Fixed by #64746
