### ISSUE TITLE
Inventory layering is funky

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#64762]
Reporting client version: 514.1575

## Round ID:
[178025](https://scrubby.melonmesa.com/round/178025)

## Testmerges:
- [Improves proccall admin circuit component. Adds the option to not resolve weakrefs for set variables and proccall admin circuit components.](https://www.github.com/tgstation/tgstation/pull/64564)
- [Changes how robotics control console works](https://www.github.com/tgstation/tgstation/pull/64608)
- [Changes what appears for urgent ahelps to supportmins.](https://www.github.com/tgstation/tgstation/pull/64748)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/152911498-13ec6529-9dcf-45b7-897b-f7236dbab8fb.png)

**Comment by Mothblocks** [comment]
This has already been fixed, but the servers are being brats when I try to update them.

Gonna force update any that are still behind.
