### ISSUE TITLE
SSUs have an error icon when you open them

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#64769]
## Testmerges:
The following pull requests are currently test merged:
[#64748: 'Changes what appears for urgent ahelps to supportmins.' by Watermelon914 at commit 182f038629](https://www.github.com/tgstation/tgstation/pull/64748)
[#64366: 'Refactor: make SSrunechat to be subsystem of SStimer' by Bizzonium at commit bd6a9a1645](https://www.github.com/tgstation/tgstation/pull/64366)

## Reproduction:
https://puu.sh/IHMgH/267c93e4f6.png
where the modsuit icon should be
there's error icon
fikou please explain this

**Comment by MacBlaze1** [comment]
I can conifrm that this is a real issue, I had this happen to me several times
