### ISSUE TITLE
Warden Job Icon not appearing on SecHUDs.

### ISSUE THREAD

**Issue by CMDR-Gungnir** [tgstation/tgstation#64777]
Reporting client version: 514.1568

## Round ID:
[178073](https://scrubby.melonmesa.com/round/178073)

## Testmerges:
- [Changes what appears for urgent ahelps to supportmins.](https://www.github.com/tgstation/tgstation/pull/64748)
- [Refactor: make SSrunechat to be subsystem of SStimer](https://www.github.com/tgstation/tgstation/pull/64366)

## Reproduction:
Join station as Warden
Notice that your job has no icon on your SecHUDs.

I ahelped it to see if it was known first and an admin suggested it could be caused by https://github.com/tgstation/tgstation/pull/64596

**Comment by MrMelbert** [comment]
@Rohesie 
![image](https://user-images.githubusercontent.com/51863163/153103880-fb353c9c-65d1-459d-9067-bb7bb3e54514.png)

**Comment by Rohesie** [comment]
Copypaste gone wrong, that's on me.
Good catch!
