### ISSUE TITLE
Pulling buckled people up ladders freezes them in place

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#64778]
Reporting client version: 514.1578

## Round ID:
[178073](https://scrubby.melonmesa.com/round/178073)

## Testmerges:
- [Changes what appears for urgent ahelps to supportmins.](https://www.github.com/tgstation/tgstation/pull/64748)
- [Refactor: make SSrunechat to be subsystem of SStimer](https://www.github.com/tgstation/tgstation/pull/64366)

## Reproduction:

During this round of icebox I found an SSD engineer dying in the lower levels sat down at one of the chairs, when I dragged them up the ladder they were sat next to they appear to be completely frozen in place. Dragging, shoving and even trying to unbuckle the chair they came from doesn't seem to fix said issue

The Area they were dragged up from
https://gyazo.com/61e674662f653274428609d760f400a6

Where they ended up frozen in place
https://gyazo.com/a59e9dfa43a6ec7a5a627cec245c4705

**Comment by Sadboysuss** [comment]
couldn't reproduce on latest version of master
