### ISSUE TITLE
abductors can stealthily mark you somehow + modsuits power down if you lose a limb

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#64809]
![image](https://user-images.githubusercontent.com/42606352/153163936-4b70a38b-848e-4aad-9c5c-a183a7dc1dca.png)
![image](https://user-images.githubusercontent.com/42606352/153163964-6a7d0590-0dae-4d61-ad9b-912f38415a85.png)

if I had to wager, the first issue probably has something to do with the instant marking code for abducting cows or something.

according to kat, this happened just a few shifts ago, so it's a recent bug. I'd tell them to make this issue report themself, but oranges apparently banned them from the repo for something, so here I am.

**Comment by Fikou** [comment]
dont make multi unrelated issues
