### ISSUE TITLE
Species-Restricted uplink items don't appear

### ISSUE THREAD

**Issue by Zonespace27** [tgstation/tgstation#64806]
## Reproduction:

1. Play moth
2. Get a traitor uplink
3. Search for the category and fail
4. Search for it in the search bar and fail
5. Scream for you lack the power of the **lämp**

The species-restricted category doesn't appear and neither does the lamp in the search bar
![image](https://user-images.githubusercontent.com/41448081/153139112-84bd0909-3265-425a-9af7-73c15db0f7ab.png)

**Comment by unit0016** [comment]
This might be the same for Role-Restricted as well? Maybe? Couldn't find the category when I was fucking with uplink code a sometime last month, hell if I know when though.
