### ISSUE TITLE
keeping sleeper effects outside of an odysseus

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#64829]
1. get scooped up by an odysseus's mounted sleeper
2. teleport out using something like bluespace powder or a bluespace crystal
3. retain the stun recovery, oxyloss recovery, and epinephrine refill effects of the sleeper until the mech runs out of power or scoops up someone else

![image](https://user-images.githubusercontent.com/42606352/153330537-36a57110-28ab-4143-9e7e-974035ec3120.png)
you get the above every tick of process(). this isn't, like, TOO relevant in today's combat meta, since it does nothing for stamina recovery, provides faster stun recovery instead of stun immunity (so you still drop what you're holding and need to wait for a process() tick), and is somewhat redundant with a tier 3 mechanical heart (which also can automatically give you epinephrine), but it's pretty neat and helps with climbing tables and stuff, I guess. it's probably also good against cult funny hands, but good luck teching up to an odysseus in a cult round.

I remember testing to see whether or not this'd also let you receive odysseus chem injections remotely, but I genuinely do not remember the results of that testing (sorry).

**Comment by ArcaneDefence** [comment]
You typed more to make this report than I typed to fix it lol

**Comment by ATH1909** [comment]
wew
