### ISSUE TITLE
a microdose of saturn x will permanently remove a monkey's NOBLOODOVERLAY trait

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#64840]
presumably, this will allow weird floating blood overlays to appear or something

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/7844b34a5fc507a3fd53ed2fc9eea690e9c1f0c7/code/modules/reagents/chemistry/reagents/drug_reagents.dm#L676-L718

https://github.com/tgstation/tgstation/blob/3a555d2cd663ba67e23a7e9c2fe066fe51991549/code/modules/mob/living/carbon/human/species_types/monkeys.dm#L1-L25

Wehn `NOBLOODOVERLAY` gets added by the drug it needs to be a different trait source.  Should be a simple fix.

**Comment by Skeleton-In-Disguise** [comment]
This is fixed as of [#76297](https://github.com/tgstation/tgstation/pull/76297). good job team

**Comment by Sealed101** [comment]
it do be fixed, trait are safu
