### ISSUE TITLE
Greentext (book) spamming logs

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#64844]
## Round ID:
[148157](https://scrubby.melonmesa.com/round/148157)

## Reproduction:
throw the greentext book in the sm
i love indestructible items
![image](https://user-images.githubusercontent.com/75639936/153434286-0ee6f829-c3a6-44b4-9118-70a826681042.png)

**Comment by Mothblocks** [comment]
These things being indestructible is so stupid, a lot of really old lavaland stuff has it. Kill all of it honestly (or put it on destruct/damage/whatever)

**Comment by JohnFulpWillard** [comment]
is this still a problem now after my greentext code improvement? I didn't even notice this label lol

**Comment by Mothblocks** [comment]
No
