### ISSUE TITLE
some sudden impromptu heretic bugtesting 

### ISSUE THREAD

**Issue by Lukasaurus8** [tgstation/tgstation#64865]
Reporting client version: 514.1571

## Round ID:
[178249](https://scrubby.melonmesa.com/round/178249)

## Testmerges:
- [Improves proccall admin circuit component. Adds the option to not resolve weakrefs for set variables and proccall admin circuit components.](https://www.github.com/tgstation/tgstation/pull/64564)
- [Changes what appears for urgent ahelps to supportmins.](https://www.github.com/tgstation/tgstation/pull/64748)

## Reproduction:
well, this was all done in the thunder dome, after some boredom and getting rousted by the mime instantly as a sentient (long unrelated story) I found some admeme thunder dome schinangens, it turned into messing with new heretic, and while doing so we found some notable bugs with rituals and items, also that the brazil thing they added is weaksauce as shit but yeah, I wrote down the bugs we found on paper, but alas I lost the snip of it so ill have to type em.
1: curse of corrosion does not cause vomiting or organ damage, making it entirely not function
2. ashen eyes cannot be examined properly by heretics
3. amber focusses can be examined properly by non heretics
4. the carving knife's ritual makes your path blade instead of the carving knife, making the carving knife impossible to make
and that's all we could find before the round ended
 for more details you can talk to the admin candidate Justice12354 who I was testing with, toodalo!

**Comment by MrMelbert** [comment]
2: Could not reproduce / needs more information 
3: Could not reproduce / needs more information 
4: Carving Knife's ritual is very similar to that of the blade ritual, but it shouldn't be impossible to make - clean off your rune before trying to make it _(also the number of blades you can make is limited so you should be able to make one EVENTUALLY)_

**Comment by timothymtorres** [comment]
@Lukasaurus8 can you clarify the above points Melbert made?  This issue was marked with the `Cleanup Flagged` label and will auto close in 7 days unless you can give more information.
