### ISSUE TITLE
Mining modsuit exploded

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#64886]
Round ID: [178300](https://scrubby.melonmesa.com/round/178300)

Shot a watcher with one of the mining explosives in ball mode. It shot the bomb midflight with an ice ray and the bomb exploded exploded causing all my stuff to scatter and be destroyed. Destroyed my pka, ID, modsuit, and whatever was in my inventory.

**Comment by davethwave** [comment]
At least this is what I assumed what happened, I was in ball mode and such. Perhaps the watcher digged up a piece of gibonite and the bomb exploded that.

**Comment by necromanceranne** [comment]
Watcher makes an absolutely INSANE trickshot and OWNS that fucking miner.

Also, this seems like something that needs reproduction.

**Comment by ArcaneDefence** [comment]
God, I fucking couldn't have imagined such a powerful watcher when I buffed them last. 11/10, dabs on a miner- what a hero

**Comment by davethwave** [comment]
Found out the exact cause. Since mining modsuits are powered via raw plasma. I normally have it in a pocket. Apparently when you carry raw plasma in your pocket and get it by a freezing watcher beam the pocket plasma explodes. Killing the miner or if they survive. Incinerating all of their possessions including ID backpack contents, and jumpsuit.

**Comment by necromanceranne** [comment]
Okay so, this is probably something bugged with plasma datum then. Because, surprise, plasma ore/sheets shouldn't be exploding. And I've definitely run into that myself.

I've also noticed something similar where there is a coin toss effect between whether or not plasma ore/sheets explode or create fire. But I've not heard of it occurring from shooting while it is in your pocket. That's new.

**Comment by davethwave** [comment]
I'll do a bit more testing and see this is only effects raw ore or not.

**Comment by davethwave** [comment]
Did a bit more testing. Plasma sheets also explode in pocket. They also generally explode with the use of lasers guns but not normal projectiles. I'll open up another issue.
