### ISSUE TITLE
Kudzu overlay oversight 

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#64892]
Reporting client version: 514.1578

## Round ID:
[178309](https://scrubby.melonmesa.com/round/178309)

## Testmerges:
- [Starts Valentine's Holiday one day earlier](https://www.github.com/tgstation/tgstation/pull/64852)
- [Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)
- [Changes what appears for urgent ahelps to supportmins.](https://www.github.com/tgstation/tgstation/pull/64748)

## Reproduction: 
Kudzu venus human traps needs to be added into the ghost roles menu like spider eggs and such since now kudzu finally works in overlay and it hides things below it becoming a venus human trap that spawn in kudzu is now impossible 

![image](https://user-images.githubusercontent.com/84478872/153736100-b5e9aaca-1a13-432c-b874-dce0209b32ba.png)

**Comment by timothymtorres** [comment]
Someone probably just needs to set the mob layer for venus flytraps to a slightly higher layer than whatever layer the vines are on.

**Comment by SethLafuente** [comment]
> Someone probably just needs to set the mob layer for venus flytraps to a slightly higher layer than whatever layer the vines are on.

Then that gives an advantage to players since they get a layer of protection from kudzu and Venus plants don’t I think adding them to the ghost roles menu like spider eggs is the best choice

**Comment by timothymtorres** [comment]
How would adding them to ghost roles fix this?  Wouldn't both the Venus flytraps and player mobs would still be hidden?

**Comment by SethLafuente** [comment]
> How would adding them to ghost roles fix this? Wouldn't both the Venus flytraps and player mobs would still be hidden?

It will let you like spiders press orbit or literary spawn as the thing by pressing a button without having to press on the actual plant that below kudzu is a very straight forwards fix
