### ISSUE TITLE
Move Fast in Low Gravity with This One Easy Trick!

### ISSUE THREAD

**Issue by IcePacks** [tgstation/tgstation#64914]
## Round ID:
[Round ID]: # Every round where I wound up in low gravity and wanted to be somewhere fast
## Testmerges:

Dunno I'm on my tablet on above average dose of melatonin 
## Reproduction:
Step by step:
1) Wind up in low gravity so you drift when you try to move through empty spaces
2) Find a solid, movable object like a welding tank or a nuke with the disk in it being guarded by an overconfident nukie
3) Position yourself on the opposite side of the object from the direction you want to move in (e.g. if you want to run west with the nuke you stole, be on the eastern side of it)
4) Run in the direction you want to move; do not stop moving or the object will drift away
5) You are no longer drifting slowly but in fact running at normal speed in space

##Stuff Worth Noting
Obviously, this doesn't really work if you're not drifting (e.g. magboots). If you run to the sides while pushing the object through space, you push off of it in the opposite direction so you drift apart from one another. I haven't tested this with simplemobs but I'm assuming that, as long as you're a mob beholden to gravity who can push things, it should work.

**Comment by Shadowflame909** [comment]
This has existed for so long I thought it was intended
