### ISSUE TITLE
Action buttons block view of screentips

### ISSUE THREAD

**Issue by kawoppi** [tgstation/tgstation#64925]
## Round ID:
[178406](https://scrubby.melonmesa.com/round/178406)
 This problem has been there for as long as I can remember. For some reason I never thought to check if there was a bug report on it and it looks like there isn't one. :(

## Testmerges:
#64564: 'Improves proccall admin circuit component. Adds the option to not resolve weakrefs for set variables and proccall admin circuit components.' by Watermelon914 at commit 44ff1164bf
#64748: 'Changes what appears for urgent ahelps to supportmins.' by Watermelon914 at commit 2d2c5b4ba3

## Reproduction:
Get action buttons until they start overlapping the screentip. You can reliably do this by cramming an air tank into every slot you can. It doesn't usually get this bad except for antagonists who can get abilities/implants and an antag panel that all take up space up there.
![example](https://user-images.githubusercontent.com/94711066/153936468-515239c0-0d7b-46ba-9c4e-831657ffa312.png)

**Comment by apynnonen** [comment]
I'm new to coding but I'd like to try and fix this bug as my first issue. Would the desired behavior be for the action buttons to always go into another row after a set number (say 5 or 6)?

**Comment by apynnonen** [comment]
In the video in the PR it looks like it still covers the screentip. I received feedback on discord to try and just layer the screentip above the actions, so I think I'll actually try that instead.
