### ISSUE TITLE
how to rip a spell from a wizard's mind

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#64927]
1. have a wizard and a normal guy.
2. bind your spellbook to yourself and buy some spells from it as the wizard.
3. mind transfer into the normal guy.
4. the normal guy can now buy spells from your spellbook using your remaining wizard points, since the spellbook is bound to your body, not your mind. I don't think that this is a bug, since wizard holoparasites also stick with your old body when you mind transfer into someone else, but opinions may vary on that.
5. there is something that's definitely a bug, though: if the normal guy buys (NOT refunds, you can't do that outside of the wizard ship) a spell that the original wizard already knows, the original wizard immediately loses access to that spell (but NOT their other spells, unless the normal guy buys copies of them too).

discovered by some testing on private servers with livrah.

**Comment by Serxule** [comment]
why would you not max out spells before mindswapping though? (this is just an oversight though)

**Comment by ATH1909** [comment]
> why would you not max out spells before mindswapping though? (this is just an oversight though)

to teach your friends some wizard spells
