### ISSUE TITLE
Unable to knock Glasses and Cigarettes off of people's face

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#64938]
Reporting client version: 514.1566
## Round ID:
[178432](https://scrubby.melonmesa.com/round/178432)
## Testmerges:
- [makes vent scrubbers only activate if a gas they filter is on their tile](https://www.github.com/tgstation/tgstation/pull/64664)
## Reproduction:
Shove some nerd with glasses and/or tobacco addict over
Their glasses do not fall off so you can step on them
Very unfortunate for people like me who use nearsighted as it is less funny

**Comment by timothymtorres** [comment]
This smells like a feature request.

**Comment by timothymtorres** [comment]
> Are you certain? I was thinking of #59006

I was not aware that it was already coded in as a feature.  Have you tested this enough to be sure it's not just the RNG being fickle?

**Comment by thgvr** [comment]
I play almost exclusively with nearsighted and I can't remember a time in the past few weeks where my glasses were knocked off. I had a few people tell me the same thing about cigarettes when I brought it up to them.

I did have someone shove me into a wall for about 5 and a half minutes and my glasses didn't fall off once. They *did* used to fall off all the time, though

**Comment by necromanceranne** [comment]
This keeps breaking every couple of months before someone remembers it exists.

**Comment by dragomagol** [comment]
Fixed by #67720
