### ISSUE TITLE
Kilo whiteship still fucked

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#64945]
Reporting client version: 514.1575

## Round ID:
[178463](https://scrubby.melonmesa.com/round/178463)

## Reproduction:

Loading kilo whiteship does this again.

![image](https://user-images.githubusercontent.com/80979251/154114955-f5e95bfc-02ca-4f59-a706-5801845c2c15.png)

The last PR to fix this has not done it, as this encounters the union issues on spawn instead of on movement.

**Comment by Zytolg** [comment]
I need you to tell me what "Does this again" means. "This" isn't exactly descriptive and aside from the blast doors looking very off, I'm not sure if that's the problem with this issue. For all I know, this is a coding issue.
