### ISSUE TITLE
Exploding pocket plasma

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#64958]
Reporting client version 514.1578

## Reproduction:

holding plasma in terms of raw or in sheet form explode while in pocket if hit by laser, or even by watcher beam despite as state by Lemon, should be a protected area.

**Comment by ATH1909** [comment]
wait how the fuck did this even happen

**Comment by LemonInTheDark** [comment]
It exploding at all isn't a bug, plasma sheets do do that.  How much you died is also kinda out of scope of the issue report.
What's interesting is it blowing up in your pocket, since that's meant to be a protected area in terms of zone ignition.

If that is what's going on, please fix your report contents to actually match the guidelines. This is also not the appropriate place for balance memes, and it's not like we need convincing that it's an issue to some extent, you don't need to discuss how much exactly you got owned

**Comment by davethwave** [comment]
Redid the issue, sorry if I didn't follow proper guidelines.

**Comment by ArcaneDefence** [comment]
based incident.
Watchers blowing up miners for smuggling plasma stacks is kinda a big wot.

**Comment by ArcaneDefence** [comment]
![image](https://user-images.githubusercontent.com/51932756/154356651-6268b914-57a6-4bdb-9ee7-f2e99d3a7d1d.png)
Funniest shit I ever saw, blew up several times before destroying itself even

**Comment by TemporalOroboros** [comment]
I'm pretty certain that the reason it isn't deleting itself is to prevent the explosion from negating the sublimation/gas release effect.
I feel like there should be a better way to go about that but signals are unordered.

**Comment by ATH1909** [comment]
wait so what pr even added the ability to hit plasma in someone's pocket, and for shot plasma to explode? I'm having trouble finding the code for that.

**Comment by necromanceranne** [comment]
Plasma material datum is what causes objects to explode, but it wasn't supposed to do that with sheets/ores because they had a bespoke effect when ignited (they release a gout of hot plasma).

Something broke along the way here.

**Comment by LemonInTheDark** [comment]
> It wouldn't surprise me that plasma datum doesn't have a check whatsoever for where the plasma object is.

The explodable component only checks if **something** is in a slot that could be hit by a burn attack, not that it is
Suffering

**Comment by Dorsisdwarf** [comment]
> wait so what pr even added the ability to hit plasma in someone's pocket, and for shot plasma to explode? I'm having trouble finding the code for that.

I bet it's to do with grenades in pockets exploding when shot
