### ISSUE TITLE
cooking holy water's deconversion effect

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#64980]
since holy water's deconversion effect is tied to a data["misc"] the reagent and isn't reset upon the reagent changing containers, I believe that you can feed it to a monkey, wait, then kill the monkey and extract the holy water from its remains. the time the holy water spent in the monkey should then be subtracted from the time it will take to deconvert a cultist with that holy water. alternatively, a pride hammer transfer should be able to cut out the monkey step. timing will be crucial, as holy water deletes itself from your system regardless of its quantity after data["misc"] hits the cultist deconversion threshold, even if you're not a cultist.

an easy fix for this would simply be to reset data["misc"] when holy water enters your system, I believe.

this bug hasn't been tested/confirmed and I don't particularly feel like booting up a private server to test it, but I'd catch so much flak if I didn't report this, so here you go.

**Comment by GoblinBackwards** [comment]
was able to reproduce this
