### ISSUE TITLE
Trying to complete a wall using reinforced glass makes a normal wall.

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#64998]
Reporting client version: 514.1566

## Round ID:
[178613](https://scrubby.melonmesa.com/round/178613)

## Testmerges:
- [Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)

## Reproduction:
1. Place down an anchored girder using iron.
2. Use reinforced glass on the girder.
3. Observe as it produces an unexpectedly normal wall.
4. Bonus: deconstruct the wall and get nothing back.

**Comment by Likteer** [comment]
It actually has an ucannily seperate model from iron walls. Same happens when finishing a girder with sandbags.

**Comment by timothymtorres** [comment]
This was fixed by #65063 I believe
