### ISSUE TITLE
Instrument Linear Sustain dont play nice with decimal numbers

### ISSUE THREAD

**Issue by Jamarkus127** [tgstation/tgstation#64992]
Reporting client version: 514.1577

## Round ID:
[178602](https://scrubby.melonmesa.com/round/178602)

## Testmerges:
- [makes vent scrubbers only activate if a gas they filter is on their tile](https://www.github.com/tgstation/tgstation/pull/64664)

## Reproduction:

You take an instrument, you click on linear sustain to change it, and if you type in a decimal and press enter, it ignores the decimal and turns it into a whole number relative to what you typed.

Ex. I want a .5 sustain, so I type in 0.5, and instead it gives me 5 seconds.

I want a .2 sustain, so I type in 0.2, and it gives me 2 seconds. 

it seems to be deleting the decimal, and reading the number as though it is a whole one. 0.5 become 05, which is 5.

Strangely, it does default to .5 until you touch the linear sustain. Testing was done with the synth mostly.

Exponential sustain is just as strange, but I didn't mess with it much. this is more about the linear sustain.

**Comment by timothymtorres** [comment]
This has been a bug for a while.

**Comment by Jamarkus127** [comment]
@MrMelbert reopen this. its STILL broken.

**Comment by Redrover1760** [comment]
@MrMelbert ITS STILL BROKEN AAAAAAAAAAAA

**Comment by Acer202** [comment]
Here's something to note: This is not limited to instruments. If you try to input a decimal value for ANYTHING, the issue occurs. Something like a reflector angle, for instance. You used to be able to enter positive and negative numbers down to four decimal points of precision for setting, but now it only takes positive whole numbers. It's as if the decimal and the negative are ignored entirely.
