### ISSUE TITLE
De-orbiting don't seem to stop the orbit animation consistently 

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#65011]
## Round ID:

[178642](https://scrubby.melonmesa.com/round/178642)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/154779647-1fff6343-5a73-49bb-a87f-8a27e699ed19.png)

I noticed a few people enter and exit and orbit and be stuck orbiting afterwards. 
They would be able to float around like normal but would continue circling. 
When checking their vars, it didn't seem like there were any orbiting vars leftover.
This didn't seem to be a byond bug or anything - Multiple people noticed the orbiting animation was still playing despite de-orbiting. 
Orbiting something again seemed to fix it.

**Comment by MrMelbert** [comment]
Potentially caused by #64891

**Comment by davethwave** [comment]
Can confirm this happens on sybil.
