### ISSUE TITLE
defibs can revive suiciders if they have HARS

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#65010]
```
	// Carbons with HARS do not need a brain
	if (!dna?.check_mutation(/datum/mutation/human/headless))
		var/obj/item/organ/brain/BR = getorgan(/obj/item/organ/brain)

		if (QDELETED(BR))
			return DEFIB_FAIL_NO_BRAIN

		if (BR.organ_flags & ORGAN_FAILING)
			return DEFIB_FAIL_FAILING_BRAIN

		if (BR.suicided || BR.brainmob?.suiciding)
			return DEFIB_FAIL_NO_INTELLIGENCE
```

'course, the revived person will then be catatonic, since suiciders get disassociated from their old bodies (and won't be able to return to them, even if they get rezzed).

**Comment by ATH1909** [comment]
say, I bet you could give a monkeyman HARS, remove its brain, revive it, and then remove its hars to create a living, brainless body that you could just slot a dead brain i- never mind, HARS regenerates your brain when you remove it, so that'd only work for people who already had chest-brains before dying

**Comment by Mooshimi** [comment]
Have you done this in game on a person you know suicided with HARS?
