### ISSUE TITLE
Space Dragon has no cooldown on gust

### ISSUE THREAD

**Issue by NoobTart** [tgstation/tgstation#65030]
## Round ID: 
[178693](https://scrubby.melonmesa.com/round/178693)

## Testmerges:
#64664

## Reproduction:
1. Use RMB on an empty tile to use your gust ability.
2. Click it again right after finishing your first gust.
3. Repeat as many times as you like to stun-lock someone into a corner until it bugs out and stun-locks you instead.

**Comment by IndieanaJones** [comment]
This isn't a bug.  Space Dragon's Gust can be spammed to your heart's content, but it's recovery time increases with repeated use.  Over time the recovery time decreases back to the original value.
