### ISSUE TITLE
Multiple mech bugs: Z level moving and strafe.

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#65032]
## Testmerges:
#64664

## Reproduction:

>Buy mauler as nuke up on tram
>Try to move up a z-level as you're stuck on the bottom level
>I get ejected from the mech
>Groan in frustration as shit is busted
>Clober my way onto the station slowly since god damn this mech is slow and ROCKS are everywhere
>Turn on strafe mode as it is necessary to use mechs
>Hold alt to soft cancel it so I can turn around
>IT doesn't work
>Bludgen my head against my deck since I just wasted TC on this broken mech.

**Comment by ArcaneDefence** [comment]
https://github.com/tgstation/tgstation/issues/54727

Putting multiple issues into one report sucks, and is made worse in that it's duplicate too.

**Comment by Sealed101** [comment]
strafing fixed as of https://github.com/tgstation/tgstation/pull/79749
moving up/down the zlevels works fine #84869 perhaps or whatever made the buttons for zlevel change
