### ISSUE TITLE
Armor doesn't work VS projectiles

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#65034]
Tested by shooting a greyshirt locally vs shooting a guy in addy armor, and a guy in a bullet proof vest with ballistics and energy

All 3 took the exact same amount damage. Projectile armor appears to be hosed.

**Comment by SpaceVampire** [comment]
I noticed this as an issue on the downstream, but I did a test locally just to confirm that it was an issue here and that very much seems to be the case. Based on the timeline of events my guess is that https://github.com/tgstation/tgstation/pull/64683 caused this bug, but I am not good enough with the code to say for sure. Melee armor still works correctly, just to be clear.
