### ISSUE TITLE
Ling code is Broken and Old and Broken

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#65037]
Reporting client version: 514.1578

## Round ID:
[178712](https://scrubby.melonmesa.com/round/178712)

This is gona be a list of ling bugs I encounter in a single round that fucked me over and generally just ruined my experience
## Testmerges:
- [Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)

## Reproduction:
First off all headslug putted my eggs into a humanized monkey corpses when I came back I couldnt see my chemical level and my lesser form and button to turn into a human were gone monkey forever 
![image](https://user-images.githubusercontent.com/84478872/154829413-c20232e5-d791-44b2-be87-987dceb4a6d2.png)

Second I pressed the button that gives you back your original ghost chracter name since I had some random one this did not let me return to my ling body so I was perma death then admins putted my body there
![image](https://user-images.githubusercontent.com/84478872/154829560-c12946d2-cdf8-444d-a289-8e4cb7fb1cbe.png)
it had the antag pannel still but for some reason all my abilities were missing then admins gave me back ling status but the revival button didnt ever activate after using it

This are the major ones that happened in this round

The other tree are as follows 

1. Sometimes when you transform while holding any kind of light on the light will stay on you at all times and is irremovable

2. Sometimes if you transform while burning you will forever have the burning tempeture you had when you transform while not being in fire so it constantly gives you third degree burns and rapidly kills you 

3. When you turn into a human after being a monkey even if is a moth you will just turn into some generic bald guy with your original underwear on 

Ling code is broken VERY VERY broken I'm sure paradise station ling code and TG ling code are literary the same thing it needs a rework

**Comment by MrMelbert** [comment]
I think some of these are dupe issues of #56314 but idk, you aren't wrong though ling code is bad

**Comment by Serxule** [comment]
>Sometimes when you transform while holding any kind of light on the light will stay on you at all times and is irremovable

this isnt ling only, this is a common bug recently.

**Comment by msgerbs** [comment]
Ling code being bad is a staple of the TG experience. And yes, pretty much all Paradise antag code is the same as TG, although idk what that has to do with this issue.

**Comment by SethLafuente** [comment]
> Ling code being bad is a staple of the TG experience. And yes, pretty much all Paradise antag code is the same as TG, although idk what that has to do with this issue.

That this code is so ancient it dosent work properly with the current build of the game

**Comment by msgerbs** [comment]
> > Ling code being bad is a staple of the TG experience. And yes, pretty much all Paradise antag code is the same as TG, although idk what that has to do with this issue.

> That this code is so ancient it dosent work properly with the current build of the game

It never did lol, I fixed derpyness with the ling vision code like 3 years ago because it didn't do what it says it would at all.

**Comment by timothymtorres** [comment]
The polymorph code for ling is ancient and fucked.  TG right now has half a dozen different transform procs that handles mob changes.  They should all be refactored into a single proc to check for crazy edge cases like someone being on fire, shapeshifting, etc.

**Comment by Mooshimi** [comment]
Please leave a comment on if this pr addressed all these issues you had.
