### ISSUE TITLE
Infinite Chests From Lavaland Chests

### ISSUE THREAD

**Issue by Cheshify** [tgstation/tgstation#65048]
## Round ID:
[178750](https://scrubby.melonmesa.com/round/178750)

## Testmerges:
[#64664: 'makes vent scrubbers only activate if a gas they filter is on their tile' by Kylerace at commit b58e7db9c2](https://www.github.com/tgstation/tgstation/pull/64664)

## Reproduction:
A miner spawned an elite fauna with a mind on lavaland, the Herald fell into a nearby chasm during the fight, the tumor kept spawning chests until an admin deleted it.
![image](https://user-images.githubusercontent.com/73589390/154861654-d8796110-6cc4-4ff6-be2b-0da88400ae46.png)

**Comment by ATH1909** [comment]
> the Herald fell into a nearby chasm during the fight

lmao owned

**Comment by JohnFulpWillard** [comment]
This is weird, I can't replace it for some odd reason
