### ISSUE TITLE
Tramstation has a golden wheelchair mapped in, which is meant to be hardcore player exclusive

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#65045]
What it says on the tin. Normally, hardcore players with sufficient hardcore points are the only means by which you should be able to acquire a golden wheelchair, but currently there is one mapped into the tramstation asteroid for some reason.

It isn't anything special on its own, but it grossly defeats the purpose of the hardcore system to just give it's end reward out as map loot.

https://github.com/tgstation/tgstation/blob/8422041a076698c63ec6b2237d32221528eefed0/_maps/map_files/tramstation/tramstation.dmm#L30418-L30421
```
"jwL" = (
/obj/item/wheelchair/gold,
/turf/open/floor/plating/asteroid/airless,
/area/mine/explored)
```

**Comment by MMMiracles** [comment]
that thing has been there since the first test merge why do you hate blinged out cripples

**Comment by necromanceranne** [comment]
I'm sorry I don't know your own map down to the smallest detail. That doesn't change the fact that it's a hardcore perk.

**Comment by Mothblocks** [comment]
Closing as this isn't a bug, but feel free to file a PR
