### ISSUE TITLE
PANDEMIC Machine throwing bluescreen when one virus cured/one virus uncured blood is inserted.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#65047]
Reporting client version: 514.1578

Round ID:
[178695](https://scrubby.melonmesa.com/round/178695)

Testmerges:
[Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)
Reproduction:
Silkie made virus, someone comes in with the virus Silkie made and also common cold. Silkie cures common cold, but Silkie's virus is still alive and well. The PANDEMIC machine, when the blood of someone with one cured virus and one active virus is inserted, shows a bluescreen error, which is posted below.

A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation.
TypeError: Unable to get property 'symptoms' of undefined or null reference
at s (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:1109138)
at Ie (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179474)
at Anonymous function (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179742)
at Le (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179720)
at Te (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:180573)
at Le (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179584)
at Anonymous function (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179742)
at Le (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:179720)
at De (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:180768)
at Te (http://127.0.0.1:53905/tmp14704/tgui.bundle.js:1:180607)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {"ckey":"stiix","interface":"Pandemic","window":{"key":"[0x200b111]-main","size":null,"fancy":1,"locked":1}}

Nanotrasen (c) 2525-2562

@tgstation/commit-access 
@tgstation/issue-managers 
https://github.com/tgstation/tgstation/issues/65028#issuecomment-1046298555

**Comment by necromanceranne** [comment]
Um why did you redo the entire issue exactly?

Then @ the issue managers? What exactly does this issue add that the other doesn't elaborate upon?

**Comment by MrStonedOne** [comment]
> What exactly does this issue add that the other doesn't elaborate upon?

It has the original text visible to everybody instead of just org members

**Comment by JohnFulpWillard** [comment]
> It has the original text visible to everybody instead of just org members

I don’t know about desktop users but I can see it on mobile without being logged in

![4472023E-1520-47B4-A924-15360B657BD8](https://user-images.githubusercontent.com/53777086/154860434-ab1ddd79-4d46-42c2-98a8-cb698269c202.jpeg)

**Comment by necromanceranne** [comment]
> > What exactly does this issue add that the other doesn't elaborate upon?
> 
> It has the original text visible to everybody instead of just org members

I'll be honest that isn't a very solid justification for both pinging all issue managers or really making a new issue at all. Again, the original issue with edited text is good enough. If you want to perserve the original text, put it in a comment at least. Walter is within his rights to edit the body of the issue, and there was in fact confusion generated from the issue report, so it already has proven to make communicating issues more difficult that necessary.

**Comment by MrStonedOne** [comment]
>  No need for further over complication of language (especially if it might make for more difficult parsing).

I was thinking more along the lines of no need to force the users reporting bugs to cater to the lack of reading comprehension on a part of issue jannies.

>  Lemon is within his rights to edit the body of the issue

No, no he fucking isn't.

When ever I have done such clarifications, I have put the revised version in a comment and left the original to stand, even when I had jannie status here.

about the only kind of edit that is reasonable to do, is to remove rule breaking content, or add newlines to walls of text.

Anything that *changes* or *adds* to what somebody appears to be saying is not a good faith edit. There is no need to be putting words into peoples mouths.

@LemonInTheDark

**Comment by necromanceranne** [comment]
Obviously they were free to re-edit to make it more their own but lemon still clarified in the comments section about said alteration.

I think it is entirely a common sense stance that we would prefer as much clarity as to what is being reported as possible. This is also why we started swatting extremely short issues without elaboration. We need these things to be as clear as possible to help contributors find, reproduce and fix problems.

**Comment by optimumtact** [comment]
> >  Lemon is within his rights to edit the body of the issue

> No, no he fucking isn't.

He absolutely is, and there is no guarantee offered that the content of any issue is not going to change at any time, there has **NEVER** been a policy on the github to respect the sanctity of comments or issues, and frankly would make our job exceedingly hard.

If you need that in writing I am happy to deliver an update, but don't try to change the rules post hoc to justify this behaviour.

**Comment by jlsnow301** [comment]
I have added some checks in #65050. I've tried reproducing this issue fully (cured viruses and all) but still can't. The reason why I'm not linking this to the PR is that I'm not sure if it will fix the issue. If this remains quiet afterwards, it can be safely closed

**Comment by LemonInTheDark** [comment]
> > No need for further over complication of language (especially if it might make for more difficult parsing).
> 
> I was thinking more along the lines of no need to force the users reporting bugs to cater to the lack of reading comprehension on a part of issue jannies.
> 
> > Lemon is within his rights to edit the body of the issue
> 
> No, no he fucking isn't.
> 
> When ever I have done such clarifications, I have put the revised version in a comment and left the original to stand, even when I had jannie status here.
> 
> about the only kind of edit that is reasonable to do, is to remove rule breaking content, or add newlines to walls of text.
> 
> Anything that _changes_ or _adds_ to what somebody appears to be saying is not a good faith edit. There is no need to be putting words into peoples mouths.
> 
> @LemonInTheDark

Morning.

I edited the post because speaking in the third person was making it harder for the issue team to do their job. Was the case with the author's other open issue too. It's totally within my rights, and it doesn't destroy information, so it's something I'm comfortable doing.

If github didn't show the edit history of comments to everyone it wouldn't be something I'd do quite so comfortably. When I say, add extra context to merge commits I'll clearly separate my voice from the authors, since I think it's important to not put words in their mouth. But github does that for me, so I don't worry about it.

I get the feeling this started with you getting annoyed because of a misunderstanding of how history works. I can understand that, but I can't agree with how you've gone about this. I'm not gonna apologize for making the lives of our issue managers/coders who care about fixes easier. 

Honestly most of the issue with that issue (ha) was how the sentence about the blood was structured. The third vs first person stuff wasn't helping, but I think that was most of what was tripping people up.

**Comment by MrStonedOne** [comment]
Except i can understand your version less.

>The PANDEMIC machine, when the blood of someone with one cured virus and one active virus is inserted, shows a bluescreen error, which is posted below.

This sentence, from the original version, should have been left in as is.

**Comment by LemonInTheDark** [comment]
~~User error~~

It's unclear about who someone is, and messes with with what I think is the logical through-line quite a bit. 
We go from the machine, to what caused the error, to the fact an error occurred, to where the error is posted.

Those two combined make it harder then it should be to parse IMO.
