### ISSUE TITLE
permanent invisibility from shadow cloaking devices

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#65052]
1. acquire the chameleon mutation
2. wait until you're completely invisible
3. activate your cloaker belt
4. lose the chameleon mutation
5. deactivate your cloaker belt, resetting your alpha to the value it was at when you activated the cloaker belt: 0

(un)fortunately, this will almost never come up, because the shadow cloaking device is currently only available via admin intervention or as maint oddity loot (and even when it does spawn as maint oddity loot, it looks like a toolbelt, so it's likely to be overlooked).

**Comment by necromanceranne** [comment]
I suspect you could probably pull this off maybe with other alpha adjusting methods too, I wouldn't discount this as a problem solely with shadow cloak.

**Comment by TheBonded** [comment]
possibly with the modsuit cloaking device as well?
