### ISSUE TITLE
Borgs hacked by a Malf Ai can be locked, and cannot be unlocked by a Malf AI.

### ISSUE THREAD

**Issue by tgsAvylaar** [tgstation/tgstation#65072]
## Round ID:

https://www.youtube.com/watch?v=0-xWkSAkKcw - 25m:50s - 26m:50s (HD quality is processing at the time of this bug report).

## Testmerges:

https://github.com/tgstation/tgstation/pull/64608 - Changes how robotics control console works

## Issue:
Borgs which have been hacked by a malfunctional AI can be locked down completely, even if they have been Emagged (Hacked by a malfunctional ai). I believe this to be an oversight.

These borgs do not have any kind of locking-protection from their emagged state.
Said Malfunctional AI can not unlock these borgs whatsoever.

As borgs can be locked by not only robotics consoles, which can be built, but also through multiple shift-start available tablets, this causes a malfunctioning ai's borg factory strategy to be completely unviable.
The software can be downloaded, and borgs can be locked by anyone with upload access (which can be granted to silver ID cards by the HOP).

I propose emagged borgs be made not lockable once they have been subverted; making it very blatant if the console gets checked.
Or, with the plausible excuse that a borg is not synched.

This has nothing to do with a borg's stunarm costing 20-25% of a default batteries' power.

Kind regards,

**Comment by carshalash** [comment]
Lockdowns are permanent now and can only be lifted if the RD/Captain feels like doing it.

Enjoy this great pro-silicon feature.

**Comment by Kubisopplay** [comment]
Lockdowns caused by a human need a human to be lifted. It's intended behavior, and improvement over previous policy of "just explode that fucker". If you want to change it again talk with KylerAce, or PR your interpretation and wait for review
