### ISSUE TITLE
Slipping off from a skateboard may magically bind your soul to it

### ISSUE THREAD

**Issue by Annihilit** [tgstation/tgstation#65070]
## Round ID:
[80651368](https://scrubby.melonmesa.com/round/80651368)

## Reproduction:
Play icebox and slip on a patch of ice while on a skateboard. Notice that the "ollie" ability didnt disappear. Realise that using the ollie instantly teleports you back to the skateboard. Realise that moving said skateboard by pulling it doesn't break your newfound bond. Become able to instantly recall to a designated spot with zero cooldown or indication where you went. Use your newfound power for evil by robbing the armory and teleporting back to your hideout with the loot.

**Comment by Annihilit** [comment]
<img width="881" alt="Phylactery" src="https://user-images.githubusercontent.com/100165104/155025114-81330d51-08e3-49aa-a320-4955c7787dd0.PNG">
Here's a screenshot i took after the skateboard got lost and my power to teleport stopped working (i suspect that someone else riding it broke the bond). I also realised that while buckled to a stasis bed or right by my skateboard, spamming ollie caused me to spin extremely fast and scream constantly. I had some fun with trying to convince the crew that an invisible monster was chasing and forcibly teleporting me, but alas, this hidden power is too great to leave unfixed.

**Comment by ATH1909** [comment]
nice

**Comment by Annihilit** [comment]
Necroing this since i figured out exactly what causes it. It's not slipping off that does it, but rather trying to mount the skateboard again while it is on an ice tile. This causes you to slip off the instant you mount it, which i guess breaks the check it does for when you get off?

**Comment by ZAMODA** [comment]
You know this seems like a good idea for a magical item

**Comment by Sealed101** [comment]
can no longer reproduce as the buckling process now correctly fails when on a slippery tile
