### ISSUE TITLE
Telescreens in brig on DeltaStation show no cameras.

### ISSUE THREAD

**Issue by derekhearst** [tgstation/tgstation#65074]
Reporting client version: 514.1575

## Round ID:
[178814](https://scrubby.melonmesa.com/round/178814)

## Testmerges:
- [makes vent scrubbers only activate if a gas they filter is on their tile](https://www.github.com/tgstation/tgstation/pull/64664)

## Reproduction:

The prisoner telescreens in brig on Delta Station show no cameras listed. Cameras were all functional in the brig itself. All telescreens tested.
![image](https://user-images.githubusercontent.com/12779264/155032651-e9a9ef65-6511-40c7-8357-cd712b2ad301.png)

**Comment by timothymtorres** [comment]
This might be due to the camera network not being matched correctly.  Probably a mapping issue.

**Comment by ErdinyoBarboza** [comment]
I have checked to recreate this. Seems everything is working fine @timothymtorres

**Comment by Jolly-66** [comment]
Map seems to be good as well.
Monitors have the "prison" network set, and the cameras inside have the network as well.

**Comment by timothymtorres** [comment]
Thanks for checking guys.  Closing this issue then.
