### ISSUE TITLE
Mac 'n' cheese recipe calls for "1 food"

### ISSUE THREAD

**Issue by Numax17** [tgstation/tgstation#65096]
Reporting client version: 514.1578

## Round ID:
[178872](https://scrubby.melonmesa.com/round/178872)

## Testmerges:
- [makes vent scrubbers only activate if a gas they filter is on their tile](https://www.github.com/tgstation/tgstation/pull/64664)
- [Armor Rework: New Vegas Damage Threshold System](https://www.github.com/tgstation/tgstation/pull/65053)

## Reproduction:
In the crafting menu under "spaghettis", the crafting recipe for mac 'n' cheese calls for "1 food" instead of one slice of bread.

**Comment by Serxule** [comment]
oh yeah i remember seeing this, pretty funny
