### ISSUE TITLE
Armor vests breaking digitigrade sprites

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#65094]
Reporting client version: 514.1566

## Round ID:
[178869](https://scrubby.melonmesa.com/round/178869)

## Testmerges:
- [makes vent scrubbers only activate if a gas they filter is on their tile](https://www.github.com/tgstation/tgstation/pull/64664)
- [Armor Rework: New Vegas Damage Threshold System](https://www.github.com/tgstation/tgstation/pull/65053)

## Reproduction:

Anything that covers legs breaks the sprite, including most every Families-related outfit (this was true before the armor testmerge)
Simply equip an armor vest with digitigrade legs and it will break, even though legs are not covered at all. I was under the impression the leg clipping or whatever was for jumpsuits and such.
![image](https://user-images.githubusercontent.com/81882910/155216447-eeebf219-969e-40ce-920c-b7dfc2a93a35.png)

**Comment by thgvr** [comment]
Testmerge bug btw

**Comment by Iamgoofball** [comment]
digitigrade code dot txt

**Comment by SuperNovaa41** [comment]
The PR in question is closed + this should be reported on the PR itself
