### ISSUE TITLE
Pipes sometimes vanish while ventcrawling

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#65115]
Reporting client version: 514.1566

## Round ID:
[178895](https://scrubby.melonmesa.com/round/178895)

## Testmerges:
- [Armor Rework: New Vegas Damage Threshold System](https://www.github.com/tgstation/tgstation/pull/65053)
- [Nullspaces Some Undertile Objects (gas pipes/wires/disposals pipes) To Save On Maptick. For Real This Time](https://www.github.com/tgstation/tgstation/pull/63500)

## Reproduction:
1. Be a lightgeist.
2. Jump into a vent.
3. Travel a substantial distance(usually a screen or two)
4. Notice that you can't see the atmos pipe layout anymore.
5. Weep.
Image below shows what the effect looks like. "Circle" is where the lightgeist is.
![image](https://user-images.githubusercontent.com/46474741/155269332-2f6cdd31-81ec-41be-b781-3d841f8e8512.png)

**Comment by timothymtorres** [comment]
I believe this has been happening for a long time.

**Comment by Mooshimi** [comment]
Same issue as #52948

**Comment by timothymtorres** [comment]
Nice catch!
