### ISSUE TITLE
X-ray beams (from the x-ray energy gun) are blocked by `TOX` armor (which doesn't exist)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#65122]
## Reproduction:

X-ray beams:
```
/obj/projectile/beam/xray
	name = "\improper X-ray beam"
	icon_state = "xray"
	flag = TOX
	damage = 15
	range = 15
```
It's damage type, inherited from parent:
```
/obj/projectile/beam
	damage_type = BURN
```

The `flag` variable:
```
	///Defines what armor to use when it hits things.  Must be set to bullet, laser, energy, or bomb
	var/flag = BULLET
```

X-ray beams do burn damage but are blocked by TOX armor which doesn't exist.

**Comment by Mothblocks** [comment]
What a silly variable name

**Comment by timothymtorres** [comment]
X-ray guns are very old used to do toxin damage.  Basically boomer code.  You used to be able to print them from R&D if you hit the higher tiers of research before the new techwebs.

**Comment by Mothblocks** [comment]
It's because they used to do rad damage and I was replacing RAD with TOX to get things to compile
