### ISSUE TITLE
Monkeys can transfer heart disease by biting others

### ISSUE THREAD

**Issue by aaaa1023** [tgstation/tgstation#65134]
## Round ID:

 Tested locally

## Reproduction:

-Spawn self in as monkey
-Spawn humans in
-Infect self with heart failure
-Bite humans and scan them to see that they too are now having a heart attack

I tested this with a few other simple viruses: adrenal crisis, slime transform, gondola transform, rev blight, robot transform and they all also transferred on monkey bite.
If the monkey bite misses the disease isn't transferred, only if the monkey successfully bites the target.

**Comment by Cheshify** [comment]
Linked PR fixes this
