### ISSUE TITLE
Can't right click to remove beaker from chem master/chem heater

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#65149]
Reporting client version: 514.1566

## Round ID:
[178985](https://scrubby.melonmesa.com/round/178985)

## Testmerges:
- [makes vent scrubbers only activate if a gas they filter is on their tile](https://www.github.com/tgstation/tgstation/pull/64664)
- [Armor Rework: New Vegas Damage Threshold System](https://www.github.com/tgstation/tgstation/pull/65053)

## Reproduction:
What it says on the tin
https://github.com/tgstation/tgstation/pull/64939 Seems like an oversight?

**Comment by timothymtorres** [comment]
https://github.com/timothymtorres/tgstation/blob/cf0d1c9a9ea23f6730e6a40027fbd1ee7a55b0ac/code/modules/reagents/chemistry/machinery/chem_dispenser.dm#L435-L445

I can retest it when I get home but this should work with any chem dispenser. (including booze ones)  Did you see the changelog present in the server when you tested this?  Sometimes a server won't update to master for a few days.

**Comment by Mothblocks** [comment]
@timothymtorres You can check the commit from the round ID they gave

**Comment by thgvr** [comment]
@timothymtorres no, the server was up to date. No functionality was changed for chem masters or chem heaters in the PR linked. This information is also in the issue title
