### ISSUE TITLE
Moth food (or at least pizza) recipes require an entire wheel of firm cheese

### ISSUE THREAD

**Issue by Googles-Hands** [tgstation/tgstation#65159]
Try to make moth pizza with firm cheese, which already is a pain to make, cut the firm cheese wheel up, realize you can't use firm cheese slices for the recipe, cry.

**Comment by BallastMonster** [comment]
close please?

**Comment by SuperNovaa41** [comment]
Dupe of https://github.com/tgstation/tgstation/issues/63998
