### ISSUE TITLE
Circle/slapper in evidence bag.

### ISSUE THREAD

**Issue by bruhlookatthisdood** [tgstation/tgstation#65168]
## Round ID:

[Round ID]: Terry #179041

## Testmerges:

It wouldnt let me view them, but im certain it wasnt any of those.

## Reproduction:
1. Get evidence bag
2. Put slapper/circle in bag (*slap/*circle)
3. Ascend by putting a slapper or circle in a evidence bag
4. Take them out, notice that the bag is now unusable
5. Game is unplayable

**Comment by TheBonded** [comment]
you dont have to specify terry (or any of the servers for that matter) in the round ID, and in fact not doing so will allow the bot to edit a link to the scrubby page for the round in question which allows access to logs and any test merges during that round

**Comment by bruhlookatthisdood** [comment]
> 

my bad

**Comment by TheBonded** [comment]
no worries, the link to the round will be [here](https://scrubby.melonmesa.com/round/179041) when the rounds logs are added to scrubby (within the hour)
