### ISSUE TITLE
Round start cells in Eva storage have 0.7% charge

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#65176]
Reporting client version: 514.1569

## Round ID: [179061](https://scrubby.melonmesa.com/round/179061)

The round reported was on tram station but its not unique to tram and I`ve seen it on multiple maps. (The picture is of meta eva storage)

## Reproduction:
Go to eva storage
see that the cells have a yellow light instead of green
examine them
0.7% charge.

![evacell](https://user-images.githubusercontent.com/62126254/155830315-4796a7ed-b0fd-4389-b026-789ae8b0a435.png)

**Comment by Cheshify** [comment]
Linked PR resolves this, literally no idea why this choice was made

**Comment by JohnFulpWillard** [comment]
![image](https://user-images.githubusercontent.com/53777086/162565388-26cad45a-2274-4fe5-bc42-dc8367ad9b69.png)

idk what fixed it but its fixed
