### ISSUE TITLE
Thieves don't give double random hardcore points

### ISSUE THREAD

**Issue by B00tz** [tgstation/tgstation#65187]
I've noticed that with thieves aswell as prog tators if you greentext you won't get double hardcore random points even though it says you will at the start of the shift. You will be giving the same amount as you would've normally on the end of round report.

## Testmerges:

[#65178: 'Adds a seperate pick proc to work on lists' by LemonInTheDark at commit adecf8d103](https://www.github.com/tgstation/tgstation/pull/65178)
[#65053: 'Armor Rework: New Vegas Damage Threshold System' by Iamgoofball at commit 377b7f4555](https://www.github.com/tgstation/tgstation/pull/65053)
[#65177: '[update tgs:DMAPI] Fix git commit detection, fix runtimes when starting tgs on a fresh repo reclone' by MrStonedOne at commit d6f5183852](https://www.github.com/tgstation/tgstation/pull/65177)

## Reproduction:
Be thief, get greentext, don't get bonus points.

**Comment by Time-Green** [comment]
May be better since they're not really antags and would kinda dilute the value. Revs and cult also don't give double points

**Comment by Time-Green** [comment]
> > May be better since they're not really antags and would kinda dilute the value. Revs and cult also don't give double points
> 
> But aren't thieves basically a weaker version of traitors? (like bloodbrothers)

That's my point. Why do they deserve the same payout if they're just lesser traitors with objectives that hardly ever get you killed? It's a save way to farm large amounts of hardcore random points. And trust me, the hardcore random point grind is hateful, violent and unforgiving.
