### ISSUE TITLE
Multiple crates in one tile with loader suit

### ISSUE THREAD

**Issue by bruhlookatthisdood** [tgstation/tgstation#65192]
## Round ID: [179112](https://scrubby.melonmesa.com/round/179112)

(Round is ongoing as the time of making this.)

## Reproduction:
1. Loader suit
2. Magnet module
3. Pick up crate with magnet and throw it at another crate on the same tile.
4. https://i.imgur.com/QuHbQiB.gif

**Comment by Fikou** [comment]
crates let flying objects pass through them, thrown objects are flying objects, this doesnt seem like a bug

**Comment by LemonInTheDark** [comment]
> The test merged things wouldnt affest this

This isn't a decision for you to make. Please include testmerges in issue reports

**Comment by bruhlookatthisdood** [comment]
> crates let flying objects pass through them, thrown objects are flying objects, this doesnt seem like a bug

ok


> > The test merged things wouldnt affest this
> 
> This isn't a decision for you to make. Please include testmerges in issue reports Also wait for rounds to finish before reporting related issues, it makes the admins upset, not sure why

sorry

**Comment by LemonInTheDark** [comment]
S alright, it's just useful for people trying to solve the issue.
Not a huge issue, just thought it was worth mentioning

**Comment by TheBonded** [comment]
generally bugs can be reported during a round so long as the information to reproduce the bug wouldnt be helpful to anyone else in the round. if it can be said in ooc, it can be reported here.
