### ISSUE TITLE
You can teleport a activated modsuit core to your hands and drop it using Instant Summons and retain your modsuit

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#65226]
## Reproduction:

Step One: Get Instant Summons, the wizard spell (miners can get this so it's possible for this to occur in a regular round)

Step Two: Either mark the modsuit core unit as your item, or put an item that is marked into the modsuit core storage unit.

Step Three: Summon the core to your hand. Your modsuit will still be functioning and deployed, but you no longer have the core unit on your back, allowing you to put anything you want there.

We love magic.

**Comment by JohnFulpWillard** [comment]
https://user-images.githubusercontent.com/53777086/156867791-9a037cc2-e4ab-4d01-b32e-d186c46081b0.mp4
