### ISSUE TITLE
You're am Organ Market Collector

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#65235]
Reporting client version: 514.1571

## Testmerges:
- [Armor Rework: New Vegas Damage Threshold System](https://www.github.com/tgstation/tgstation/pull/65053)

## Reproduction:
![](https://i.imgur.com/qTqHVq1.png)

Why not just Organ Harvester?

**Comment by TheBonded** [comment]
N key being next to the M key has troubled coders for years
