### ISSUE TITLE
Vaccines are not able to be moved into Chem Master buffers

### ISSUE THREAD

**Issue by plutori** [tgstation/tgstation#65231]
Reporting client version: 514.1575

## Round ID:
[179254](https://scrubby.melonmesa.com/round/179254)

## Reproduction:

1. Cure a virus
2. Obtain cured blood
3. place blood in a beaker or similar container, place that beaker into the virology pandemic machine
4. Use the pandemic machine to create a bottle of vaccine
5. Place the bottle of vaccine liquid into the ChemMaster 3000 (Note: you can move the liquid out of the bottle into another container such as a beaker and place that in the ChemMaster 3000 instead, the end result is the same)
6. Try to move the liquid vaccine out of the original container into the buffer for the ChemMaster 3000 by pressing any of the transfer buttons, i.e - 1,5,10, etc. and nothing will happen. It will not move the liquid into the buffer.

This is a serious issue because you cannot make 0.1u vaccine pills like this. Issue tested with other players and with different containers while ingame in an ahelp with gamemaster Wubli, same results. Unknown if this is due to a test merge or anything.

**Comment by Mothblocks** [comment]
Couldn't replicate with either a custom virus nor the cold

**Comment by Mothblocks** [comment]
![image](https://user-images.githubusercontent.com/35135081/156291641-02dbe080-e946-4b98-bfb7-b3ad846e7ac4.png)

One of the first things checked for in chem masters is `name2reagent[id]`. On the round I mentioned this is what vaccine resolved to.

**Comment by Mothblocks** [comment]
I figured it out and this is the coolest bug I've seen in a while, wait for the write up
