### ISSUE TITLE
Reduced Maxcap not used by Mother of God experiment (cannot complete on Kilo)

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#65255]
Kilo reduces the max bombcap. However, the maxcap experiment "Mother of God" does not factor that into its requirements, leading to the experiment not being able to be completed on Kilo Station.

## Reproduction:

- Play Kilo
- Unlock Mother of God experiment (will say it needs 20/10/5)
- Try to complete Mother of God experiment
- Can only get 14/7/3.5

## Code

https://github.com/tgstation/tgstation/blob/974b578511f32d7ca6a1185973a397620761b73e/code/modules/experisci/experiment/experiments.dm#L74-L77
Doesn't use the bombcap multiplier.

https://github.com/tgstation/tgstation/blob/974b578511f32d7ca6a1185973a397620761b73e/code/controllers/subsystem/explosions.dm#L305-L309
However does use it.

**Comment by RandomGamer123** [comment]
Bug no longer exists with new toxins.
