### ISSUE TITLE
Explosions instakilling without dealing enough damage to put into crit

### ISSUE THREAD

**Issue by Kubisopplay** [tgstation/tgstation#65273]
Reporting client version: 514.1568

## Round ID:
[179356](https://scrubby.melonmesa.com/round/179356)

## Testmerges:
- [Armor Rework: New Vegas Damage Threshold System](https://www.github.com/tgstation/tgstation/pull/65053)

## Reproduction:
- Cause an explosion
- stand in light damage range
- realise you suddenly see ghosts
- check the damage on your body, seeing 50 brute and 50 burn

Multiple people reported it too, but this is the moment i have seen it on me. A maxcap detonated in the middle of icebox shuttle killed me instantly when i was outside of it

**Comment by ATH1909** [comment]
https://youtu.be/FkXlKQS5Elo?t=38

me when
when explosion

**Comment by Kubisopplay** [comment]
This but without ability to come back

**Comment by Serxule** [comment]
its due to how explosions work, etc being in the non-lethal range of a syndibomb will crit you, maybe send off a limb, but the crit will go away and you'll get back up, being mostly fine, so this is likely an oversight

**Comment by Pinkufeck** [comment]
it's not that, explosions recently started dealing a lot more damage than before, even outside of the heavy range, unarmored, you'll die, instantly, with full health.

**Comment by Pinkufeck** [comment]
I think it's linked to #65275

**Comment by Kubisopplay** [comment]
Goof was informed of the issue, and it appears he knows of it. Don't know when he will resolve it tho, so I would leave it open

**Comment by optimumtact** [comment]
please report these on the PR's instead.
