### ISSUE TITLE
Silent revert of c

### ISSUE THREAD

**Issue by Archie700** [tgstation/tgstation#65288]
## Round ID:
[179407](https://scrubby.melonmesa.com/round/179407)

## Testmerges:
[#65053](https://www.github.com/tgstation/tgstation/pull/65053)
[#65223](https://www.github.com/tgstation/tgstation/pull/65223)

## Reproduction:
Basically, #62284 has been silently reverted. Tech such as Advanced Cybernetic Implants and Upgraded Cybernetic Organs are no longer gated behind gas experiments and the NT Frontier is not able to be downloaded.

![dreamseeker_7IyDEHJFvv](https://user-images.githubusercontent.com/17823321/156812508-d94689f7-132a-404d-b198-48213418a2cf.png)
![dreamseeker_AYwp9Zc9NQ](https://user-images.githubusercontent.com/17823321/156812567-19e8487c-d76f-44ef-9b1b-0d20cf2a1065.png)
![dreamseeker_vL30YAvPA0](https://user-images.githubusercontent.com/17823321/156812642-cd4337b7-4f67-47ed-b56b-9ccc268fce9e.png)

**Comment by Mothblocks** [comment]
Judging by your round ID, the server has not been updated yet.
