### ISSUE TITLE
Plumbing liquid pumps don't work on geysers.

### ISSUE THREAD

**Issue by tgent007** [tgstation/tgstation#65285]
Reporting client version: 514.1575

## Round ID:
[179387](https://scrubby.melonmesa.com/round/179387)

## Testmerges:
- [Armor Rework: New Vegas Damage Threshold System](https://www.github.com/tgstation/tgstation/pull/65053)
- [Overhauls heretic rituals slightly for better user feedback (and to help locate a bug)](https://www.github.com/tgstation/tgstation/pull/65223)

## Reproduction:

Place a chemistry plumbing liquid pump on a discovered geyser and attempt to pump things from it, TADA nothing happens.

**Comment by newfren** [comment]
Did you plunger the geyser first?

**Comment by Time-Green** [comment]
He did not plunger the geyser

Keeping this open because this keeps happening and apparently people don't read guides anymore and I should just remove it

**Comment by tgent007** [comment]
In my 600 hours I have never been this stupid.
