### ISSUE TITLE
Curator has "on/off" preferences, while assistant is ranked high-low pref

### ISSUE THREAD

**Issue by Farquaar** [tgstation/tgstation#65294]
## Reproduction:

![image](https://user-images.githubusercontent.com/44147031/156851492-3ae1f2fa-a0db-47c6-912f-cb3f0fe1fcbd.png)

**Comment by Ryusenshu** [comment]
Not a bug, its overflow
A station Trait

**Comment by ArcaneDefence** [comment]
https://github.com/tgstation/tgstation/blob/1346c973c29143b2bb6a36a80eb564be9259429d/code/datums/station_traits/negative_traits.dm#L100

Literally a feature

**Comment by Farquaar** [comment]
Huh, didn't know that.
