### ISSUE TITLE
Pizza Statues ruined, I am devastated, there is nothing sacred and unbroken left in sculpture making

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#65302]
## Round ID:
[179573](https://scrubby.melonmesa.com/round/179573)

## Reproduction:

- Bake a pizza, slice it up neatly, then roll the resulting pieces with a rolling pin.
- Make a sculpture of a humanoid since it's one of the only things that don't turn out as black void upon finishing.
- Everything but the pedestal looks like molten cheese left to set instead of the regular pizza pattern.
![obraz](https://user-images.githubusercontent.com/68878861/156896547-82b91a1b-8d6a-4b73-bffb-d9c41dc7c01e.png)

**Comment by timothymtorres** [comment]
Can you confirm the pizza pattern appears with other objects besides floor tiles?

**Comment by Likteer** [comment]
@timothymtorres There are 2 pizza walls behind it and it's standing on a pizza table. I can also confirm it worked properly on a server with modified older /tg/ (which doesn't have the aforementioned black void bug either).

**Comment by timothymtorres** [comment]
Black void bug mentioned is related to #61228

**Comment by timothymtorres** [comment]
![dreamseeker_HnXYEzh67e](https://user-images.githubusercontent.com/5195984/211922914-833f99ae-5120-4440-8bec-2a2b99317b25.png)

The black void bug was apparently fixed at some point.  Also I'm not able to replicate the problems outlined in this issue.  I think the GAGS problems with materials fixed it.

Feel free to ping me to reopen if this is still a problem.
