### ISSUE TITLE
BSA built in unpowered area will not update to powered when the area is changed and power is introduced

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#65310]
## Reproduction:
build the bsa in the icemoon wastes
surround it in walls, define an area
build an apc, power it
the bsa cannot be repowered, even if the computer is disassembled and reassembled, and will not respect your mortal laws

we checked that the area itself was powered (via the lathe in the screenshot) and it was

https://puu.sh/IN87V/0fd585fa37.png

**Comment by moocowswag** [comment]
I also experienced this bug when I built a circuit airlock in a room after claiming it but before I built an apc.

I`ve also seen computers and machines do this to.

**Comment by newfren** [comment]
it's especially bad for the bsa because you cannot deconstruct it but I'm not shocked that it would effect other machines

**Comment by Sealed101** [comment]
it's pretty wild that you can use the console in an undefined area in the first place
but no, can't reproduce. was able to build it in an unpowered area (tested in space/lavaland/icebox wastes), then complete the assembly, then create and power an area, then successfully fire on signals. guess the way the power networks update has changed but i fail to find the PR for it
