### ISSUE TITLE
Borg fell into emagged recycler and deleted its brain (but still alive)

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#65316]
## Round ID:
[179522](https://scrubby.melonmesa.com/round/179522)

## Testmerges:

N/A
## Reproduction:
> Borg fell into emagged recycler
> Got repaired right after
> Complains about not working Modules
> Got Reset , but the form still stayed the same
> Got disassembled
> Brain Gone

**Comment by GoblinBackwards** [comment]
This happens because borgs have have all this stuff in their contents list, which emagged recyclers qdel everything from.
![image](https://user-images.githubusercontent.com/22856555/159097634-3e43af99-75a3-42ba-990c-bb4be4b085ae.png)
