### ISSUE TITLE
You can hear emotes while blind and deaf

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#65336]
## Reproduction:be blind and deaf and listen to a emote, 
![unknown](https://user-images.githubusercontent.com/54517726/157157559-84d80704-55cd-4e1f-8277-c57f51c55626.png)

**Comment by MrMelbert** [comment]
Not really a bug, you're intended to be able to see / hear emotes you shouldn't be able to see / hear, and we don't fully support being blind and deaf

**Comment by SuperNovaa41** [comment]
If we don't support it I would argue its an oversight then, no?

**Comment by TheBonded** [comment]
I agree with nova here, this definitely seems like an oversight

**Comment by Mothblocks** [comment]
im also confused @MrMelbert
