### ISSUE TITLE
Forced DNR Ethereals (head revolutionaries on loss) can revive via crystal

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#65337]
## Round ID:
[179608](https://scrubby.melonmesa.com/round/179608)

## Reproduction:

Ethereals who are forced to DNR (in this case, a head revolutionary losing the revolution) can revive via crystal as normal. 

(Crystal reviving was a mistake)

**Comment by MacBlaze1** [comment]
etherealbros...we got too cocky

**Comment by JohnFulpWillard** [comment]
They aren't DNR'ed, they are just blacklisted from NT records, which includes their defibs. Alternative methods of revival should is still possible. Saying this as the author of https://github.com/tgstation/tgstation/pull/63466 but @Mothblocks can correct me if they think it should work otherwise.

**Comment by Mothblocks** [comment]
I'm gonna call this not a bug since the point of the anti-revival thing is to stop people from killing heads of staff then immediately reviving them--the crystals are completely independent and do not allow a second player to intervene, other than to stop it.

**Comment by Mothblocks** [comment]
That being said this should maybe be commented somewhere as intentional since I agree it is not intuitive
