### ISSUE TITLE
Wizard Rod Form in Hyperspace deletes the body

### ISSUE THREAD

**Issue by CMDR-Gungnir** [tgstation/tgstation#65340]
Reporting client version: 514.1568

## Round ID:
[179622](https://scrubby.melonmesa.com/round/179622)

## Reproduction:

Step 1) Be a Wizard
Step 2) Be fighting some people on the shuttle
Step 3) Decide it'll be funny to rodform knowing you'll launch yourself into Hyperspace
Step 4) Die literally instantly, and don't even have a body to enter

It was very funny, but I don't think it's an intentional interaction, so it's worth looking into.

**Comment by Timberpoes** [comment]
Without looking at the code, my assumption is that wizard rod form simply needs to have the vars set that let it force loop. By default rods qdel on z level change.

This would let wizards rod across z level boundaries and be teleported off the z level while rodding without being deleted.

**Comment by Spookuni** [comment]
this kills the wizard
