### ISSUE TITLE
Projectiles will occasionally fail to respect space z-level transitions.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#65348]
## Reproduction:
1. Give a projectile PoI status, sets its range arbitrarily high, make it penetrate/phase through everything, fire it in a random direction.
2. Orbit it.
3. Observe it completely ignore the z-level transition, run into the map border, and delete itself on a random loop.

I understand it deleting itself when it hits the edge of the z-level. What I don't understand is how it's ignoring the z-transition buffer. It should be shifting to the linked z, but it just doesn't. It also doesn't throw runtimes.

**Comment by LemonInTheDark** [comment]
What station were you on?

**Comment by TemporalOroboros** [comment]
> What station were you on?

Metastation. I was testing firing the blastcannon diagonally. The shot looped a few times and then ran into this bug around x = 190 with plenty of oomph left. The only modifications I had were making blastcannon shots registered by the PoI and Augery subsystems and stack tracing if it deleted with remaining range. The stack trace indicates that the qdel was the one in pixel_move which runs if the target move loc is not a turf. This makes sense as I actually saw it ram into the map boundary and it would have been attempting to step off the map. The strange bit is that it got to the map boundary in the first place. It somehow bypassed the edge buffer and I don't understand how.

**Comment by timothymtorres** [comment]
@Sealed101 you can close this issue.

This was fixed in #66301

Baseturfs were changed from openspace to:

`baseturfs = /turf/baseturf_bottom`

**Comment by Sealed101** [comment]
shore
