### ISSUE TITLE
Reinforcement in airlocks can' be removed

### ISSUE THREAD

**Issue by ChocolateBickie** [tgstation/tgstation#65391]
## Round ID:
[179768](https://scrubby.melonmesa.com/round/179768) 

## Reproduction:

Metal and plasteel reinforcement in airlocks cannot be removed.

Find airlock. Screw open panel. Add metal sheets. Try to remove meal sheets using tools. No combination of tool, right click, left click or intent will allow you to remove the metal. This applies to plasteel too.

A quick glance at airlock code indicates that screwing open the panel should make welding cut through the reinforcement, but this does not happen (Check if this is true).

Could be related to; https://github.com/tgstation/tgstation/pull/64375

This bug allows anyone with metal to permanently lock out hackers. Engie borgs can now secure the entire station! Assistants weep for your time is over.

**Comment by lewcc** [comment]
Big if true for malf AI

Yeah it's almost certainly from that or #64428. I'll take a good look

**Comment by lewcc** [comment]
Yeah, dammit. There's always something. I missed 
https://github.com/tgstation/tgstation/blob/dac4255c0196e5c247cfeeac36df9aebad38b7b2/code/game/machinery/doors/airlock.dm#L881-L895

And 

https://github.com/tgstation/tgstation/blob/dac4255c0196e5c247cfeeac36df9aebad38b7b2/code/game/machinery/doors/airlock.dm#L897-L911

for each type of shielding. I'll try to fix that up tonight.

**Comment by MacBlaze1** [comment]
Im not sure if this is a bug

**Comment by MacBlaze1** [comment]
I confirmed that this is an oversight that is incredibly recent, that tools rework PR is absolutely the top culprit

**Comment by Likteer** [comment]
I'd like to add: I observed I was able to reinforce airlocks with plasteel while the maintenance panel is closed, which doesn't do anything (though you cannot repeatedly waste plasteel on it and you can still reinforce the door normally).
