### ISSUE TITLE
Making Singularity in 3 clicks | Feature™ | Soul Tap is so bad edition

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#65395]
## Reproduction:
-Wizard
-Rod Form
-Soul Tap
-Use Soul Tap and Rod again while in Rod Form
-2 Rods on the same tile

**Comment by ATH1909** [comment]
on a private test server, I was able to unleash multiple singulos as a lich wizard, but sadly, lichdom seemed to bug out and not work when livrah tried to do that on an actual server. very sad!

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/cfa2c0a888f591cae34c937ac7c5fd09ab5d9f0b/code/modules/events/immovable_rod.dm#L202-L221

**Comment by Arturlang** [comment]
I'd just make soul tap unusable while in a container or in a rod
