### ISSUE TITLE
Engineering Cyborgs can't place APC or Air alarm frames on walls anymore

### ISSUE THREAD

**Issue by Vekzie** [tgstation/tgstation#65393]
## Round ID: 
Round ID's: 179779/179780

## Testmerges: 
I'm not sure if it's from any of the test merges or not, sorry! I don't think there's one on Manuel though.

## Reproduction: 
The issue is, as an engineering cyborg, you can't place APC / Air alarm frames. Im not sure if other things are affected, those are the two I tested. I suspect anything else that gets placed on the wall like those two can't be used either. What you used to be able to do is:
Create the frame from iron sheets -> face the wall you want to place it on, standing on top of the frame -> Use a screwdriver on the frame, and it will place on the wall
That no longer works, neither in an existing area, nor in a completely new area. Specifically, using the screwdriver on the frame will not place it. Tested on round  179780 with the GameAdmin FlamingCheese, and was suggested to make a report.

**Comment by dragomagol** [comment]
Looks like there's no testmerges on Manuel at the moment.
