### ISSUE TITLE
Instrument beacon drop pod plays glass shattering sound instead of pod landing sound

### ISSUE THREAD

**Issue by kawoppi** [tgstation/tgstation#65426]
## Round ID:
[179843](https://scrubby.melonmesa.com/round/179843)
179799
179794

## Testmerges:
Round 179843 had no test merges.
Round 179799 and round 179794 had the action button rework (praise be) test merged.

## Reproduction:

1. Play as a character with the musician trait.
2. Use the instrument beacon you spawn with and select an instrument of your choosing.
3. Wait for the pod to land and listen to the sound it makes when it does.

**Comment by moocowswag** [comment]
Can confirm it happens when I use it to.

**Comment by bruhlookatthisdood** [comment]
Using the pod spawn admin debug command pod will also make a glass shatter noise on contact with the groudn

**Comment by timothymtorres** [comment]
This was fixed by #65460
