### ISSUE TITLE
Human staff can have non-human security records

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#65428]
Reporting client version: 514.1581

## Round ID:
[179853](https://scrubby.melonmesa.com/round/179853)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/158038707-04ce615a-6b66-46bc-8a77-c526a7bf21b1.png)

Choose lizard character. Roll Head of Staff. Look at your security records.

**Comment by necromanceranne** [comment]
Reptoid conspiracy revealed.
