### ISSUE TITLE
Mafia continues even after only one person remains

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#65430]
Reporting client version: 514.1569

## Testmerges:
- [Action button refactor/rework: Enhanced Dragging](https://www.github.com/tgstation/tgstation/pull/65180)

## Reproduction:
play mafia
someone is the last one remaining
the days/nights still cycle on as the blast doors open/close

![image](https://user-images.githubusercontent.com/62126254/158042814-a4caf673-1094-43ab-a5ca-0131bf553a87.png)

The remaining person did turn into their changeling look early long before everyone else died so im wondering if that had anything to do with it??

**Comment by dragomagol** [comment]
@tralezab

**Comment by Googles-Hands** [comment]
Still an issue.

**Comment by JohnFulpWillard** [comment]
Should be fixed by https://github.com/tgstation/tgstation/pull/74974
