### ISSUE TITLE
Engineer cyborgs cannot use screwdrivers on wall-attachment frames like APC/Fire alarm frames

### ISSUE THREAD

**Issue by Solbusaur** [tgstation/tgstation#65447]
As an engineer cyborg, I've been unable to replace broken APCs (such as in the gravity generator) or build new ones in rooms I have created using a screwdriver. Normally you are supposed to occupy the same tile, face the target wall and click on the device with your screwdriver equipped.
It didn't happen this time, and there was no indicator in the text window to suggest why it failed. There was no 'room undefined' nor 'there is already an item on this wall'.
Just to check, I also tried to attach a fire alarm frame to the wall in the central primary hallway with also no result.
## Reproduction:
- Choose engineer module as a cyborg
- Find a blank wall or make your own
- Use metal crafting tab to build an air alarm frame/fire alarm frame or use an autolathe to get a security camera frame/intercom
- Try to use your screwdriver on the frame while facing the empty wall

**Comment by MacBlaze1** [comment]
did https://github.com/tgstation/tgstation/pull/65408 not fix this?

**Comment by MacBlaze1** [comment]
@AlinaStarkova did you test this on your branch?

**Comment by MacBlaze1** [comment]
gonna mark this as just a delay in updating servers

**Comment by Ryll-Ryll** [comment]
When you get a chance, see if this is still the case. If so, include the server's revision commit (OOC tab -> Show Server Revision -> copypaste it in here so we know what version of the code it was using). If it isn't still the case, it was fixed by #65408 which was merged when the issue was put up but may have not been updated onto the live server

**Comment by AlinaStarkova** [comment]
> @AlinaStarkova did you test this on your branch?

i did indeed test it on my branch and this fixed it, if it stopped working again then someone messed with screwdriver code again (iirc the guy who refractored tools had a PR or two up to fix other bugs with the tools)

**Comment by AlinaStarkova** [comment]
@Ryll-Ryll @MacBlaze1

![IMG_20220313_230556.jpg](https://user-images.githubusercontent.com/40489693/158097943-770da7e3-8835-491c-9dc2-ad1c1474d672.jpg)

**Comment by MacBlaze1** [comment]
Im going to close this then
