### ISSUE TITLE
explosions sound and feel like they're directly ontop of you

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#65448]

**Comment by MacBlaze1** [comment]
I made this priority high because I dont want anymore trauma than I already do from hearing random explosions go off

**Comment by MrMelbert** [comment]
Issue one:

![image](https://user-images.githubusercontent.com/51863163/158113095-d4e8f72f-569f-4e7c-953a-4f74bb845f83.png)

Issue two:

![image](https://user-images.githubusercontent.com/51863163/158113135-a495f9c6-5a94-47bf-b178-579aa13ffadc.png)

**Comment by SuperNovaa41** [comment]
> Issue two:
> All instances of "explosion" were replaced with SFX_SHATTER instead of SFX_EXPLOSION

Yeah i thought that was weird in the PR but no one mentioned it so i figured no one cared

**Comment by LemonInTheDark** [comment]
Fixed
