### ISSUE TITLE
Interacting with a death nettle with telekinesis hurts you as if you had just picked up the nettle without gloves.

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#65454]
## Testmerges:
https://github.com/tgstation/tgstation/pull/65180

## Reproduction:
1. Get a nettle. High-potency Deathnettles were specifically used in this instance.
2. Get telekinesis.
3. "pick up" the deathnettle with telekinesis.
4. Try to attack anything with the nettle.
5. Observe as your arm is nearly burned off by powerful nettle acid.

**Comment by Djvarik** [comment]
I touched the SM through a cam with TK once and got dusted. I was told it was intended, so I would assume the same in this case

**Comment by TemporalOroboros** [comment]
> I touched the SM through a cam with TK once and got dusted. I was told it was intended, so I would assume the same in this case

I don't think it is in this case. The SM, singulo, and tesla are special cases. The former because we don't want people throwing it around the station.

**Comment by timothymtorres** [comment]
@datorangebottle can you test my PR and let me know if it works.  I'm unable to test code directly for the next month or two so I'm relying on volunteers to bugtest my PRs.
