### ISSUE TITLE
You hit a blast door anytime you change its ID

### ISSUE THREAD

**Issue by Djvarik** [tgstation/tgstation#65453]
Reporting client version: 514.1581

## Round ID:
[179922](https://scrubby.melonmesa.com/round/179922)

## Reproduction:
Very minor but I think unintended bug.
1. Create a blast door
2. Change its ID with a multitool
3. After you click OK, you hit the blast door

**Comment by lewcc** [comment]
This looks to be a multitool_act() issue, and one that actually predates the tool_act refactors.

https://github.com/tgstation/tgstation/blob/695fe9182b410197dccdf394491cf1fcd4f7a6fc/code/game/machinery/doors/poddoor.dm#L28-L42

The proc should be returning TOOL_ACT_TOOLTYPE_SUCCESS for it to not hit the door.
