### ISSUE TITLE
Plastitanium is deleted when placed into airlock assembly

### ISSUE THREAD

**Issue by Djvarik** [tgstation/tgstation#65452]
Reporting client version: 514.1581

## Round ID:
[179922](https://scrubby.melonmesa.com/round/179922)

## Reproduction:
1. Create an standard airlock assembly
2. Place plastitanium in as a material cover
3. Plastitanium is deleted, from stack 
I assume this is because there is no plastitanium airlock

**Comment by unit0016** [comment]
Intentional behavior, this actually just gives the airlock more health

**Comment by Likteer** [comment]
@unit0016 I think you got it wrong. It looks as if he describes being able to put plastitanium as an airlock window material, which consumes it and does nothing.

What increases airlock hp is putting a wire cover on a finished one, which only accepts plasteel (plasma+iron) or regular iron.

**Comment by unit0016** [comment]
Had to test in-game, as this is on of those things I've done before and it worked out swell. Guess whatever my head is mixed with how many server's I'm on led to another lapse in judgement.

Oh well.

Here's the runtime, and it's as OP suspects
```[12:24:11] Runtime in door_assembly.dm,218: Cannot create objects of type null.
  proc name: attackby (/obj/structure/door_assembly/attackby)
  usr: BluBerry016/(Conner Easter)
  usr.loc: (Central Primary Hallway (127,141,4))
  src: the airlock assembly (/obj/structure/door_assembly/door_assembly_public)
  src.loc: the floor (128,141,4) (/turf/open/floor/iron)
  call stack:
  the airlock assembly (/obj/structure/door_assembly/door_assembly_public): attackby(the plastitanium (/obj/item/stack/sheet/mineral/plastitanium), Conner Easter (/mob/living/carbon/human), "icon-x=22;icon-y=14;left=1;scr...")
  the plastitanium (/obj/item/stack/sheet/mineral/plastitanium): melee attack chain(Conner Easter (/mob/living/carbon/human), the airlock assembly (/obj/structure/door_assembly/door_assembly_public), "icon-x=22;icon-y=14;left=1;scr...")
  Conner Easter (/mob/living/carbon/human): ClickOn(the airlock assembly (/obj/structure/door_assembly/door_assembly_public), "icon-x=22;icon-y=14;left=1;scr...")
  the airlock assembly (/obj/structure/door_assembly/door_assembly_public): Click(the floor (128,141,4) (/turf/open/floor/iron), "mapwindow.map", "icon-x=22;icon-y=14;left=1;scr...")```
