### ISSUE TITLE
Placing material other than plasteel on reinforced girder unreinforces the girder

### ISSUE THREAD

**Issue by Djvarik** [tgstation/tgstation#65451]
Reporting client version: 514.1581

## Round ID:
[179922](https://scrubby.melonmesa.com/round/179922)

## Reproduction:
This was done with plastitanium, unsure about other materials
1. Create a reinforced girder
2. Place other material on it to create wall
3. Once wall is made, weld wall
4. Girder is regular, the plasteel is lost to time.

**Comment by Arturlang** [comment]
Old, old bug

**Comment by timothymtorres** [comment]
Yeah this has been a thing for a while but it's so minor that nobody has bothered to report it as a bug.
