### ISSUE TITLE
Ghost in the machine/How revenants are not logged properly

### ISSUE THREAD

**Issue by techno0** [tgstation/tgstation#65463]
## Reproduction:

- Have a revenant on station.
- Stuff happens
- You kinda need logs
- Look at logs
- Notice that only Overload Lights/Defile/Blight/Transmit are apparently logged
- Cry because you need the Harvest interaction logged
- Get banned

**Comment by msgerbs** [comment]
What specific actions, besides harvest, aren't logged?
