### ISSUE TITLE
AI is completely unable to use mech modules

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#65471]
Reporting client version: 514.1581

## Round ID:
[179955](https://scrubby.melonmesa.com/round/179955)

## Testmerges:
- [MODsuit painting](https://www.github.com/tgstation/tgstation/pull/65445)

## Reproduction:
Hop in mech through your preferred method as AI
Be unable to use modules that require you to click and despair.

**Comment by Serxule** [comment]
its middle click to use mech modules, same with punching, if that doesnt work then its bugged

**Comment by SuperNovaa41** [comment]
Dupe of https://github.com/tgstation/tgstation/issues/64112
