### ISSUE TITLE
Traitor Interface window does not open (PDA, headset, pen, etc.)

### ISSUE THREAD

**Issue by Pandarsenic** [tgstation/tgstation#65483]
## Round ID:
[179973](https://scrubby.melonmesa.com/round/179973), but also occured in [179879](https://scrubby.melonmesa.com/round/179879) and within previous rounds before that ever since the Progression Traitor merge.

## Reproduction:

- Activate the traitor interface by any of the usual methods (input a code into a PDA; input a code into a headset; input a code into a pen; etc.)
- The window vanishes immediately. Any attempt to open an unlocked PDA, my own or anyone else's, fails. No screencap included because there is nothing to display.
- Restart BYOND and I get this: https://cdn.discordapp.com/attachments/707247196420046900/932555049144553483/unknown.png
- Reinstall BYOND and I get this: https://cdn.discordapp.com/attachments/639570551035396107/953170971223785512/unknown.png
- Use a multitool, station-bounced radio, debug uplink, or uplink implant, and I get this: https://cdn.discordapp.com/attachments/707247196420046900/932555277230825472/unknown.png

Right-clicking on the broken window, pressing "Select All," and then copy-pasting produces this text:

[copypasteblock]    



Syndicate Uplink

×

SyndOS Version 3.17  Connection Secure

WELCOME, AGENT.

Significant (501)

20 TC

Objectives

Market

Lock

Smuggle odd pen from Vacant Commissary off the station via cargo shuttle 



Go to a designated area, pick up syndicate contraband, and get it off the station via the cargo shuttle. You will instantly fail this objective if anyone else picks up your contraband. If you fail, you are liable for the costs of the smuggling item.

Failing this objective will deduct 2 TC.

1 TC,55.2 Reputation



Empty Objective, drop objectives here to take them

Potential Objectives

Request More Objectives

 

 
Pressing this will materialize the contraband you need to deliver. You must be in Vacant Commissary to receive it![/copypasteblock]

Clickin in the upper-right corner of the window still closes it as though I had successfully Xed out. After doing this, I cannot open the window at all again.

**Comment by interestingusernam3** [comment]
Did you have connection problems?

**Comment by SuperNovaa41** [comment]
I've had this happen to me before. I wasn't able to open any uplink for like 2 weeks, and then it just went away

**Comment by Pandarsenic** [comment]
> Did you have connection problems?

No connection problems of any sort, All other game functionality seemed unimpaired, including other systems that used the windows (and uplinks that didn't have whatever is in the default tato uplink area. Objective selection?)

**Comment by Pandarsenic** [comment]
In case it's any insight into why this happens, I discovered that attempting to open the traitor interface also stops me from opening the interface to control the mining shuttle.

**Comment by Sealed101** [comment]
dead links + it's been over two years surely something managed to unfuck the uplink :clueless:
