### ISSUE TITLE
Survival pod seems to not be spawning in with correct atmosphere

### ISSUE THREAD

**Issue by plutori** [tgstation/tgstation#65482]
Reporting client version: 514.1581

## Round ID:
[179977](https://scrubby.melonmesa.com/round/179977)

## Testmerges:
- [Action button refactor/rework: Enhanced Dragging](https://www.github.com/tgstation/tgstation/pull/65180)

## Reproduction:

I decided to use my starting bluespace shelter capsule on icebox today on the bottom z level just to plunder the warm donk pockets inside for food. However, upon starting to munch on my delicious Donk Pockets, I realized I was suffocating to death inside of my freshly spawned survival pod, which is extremely unusual, since bluespace shelters are supposed to spawn in with a certain breathable atmosphere. Reported issue to admin Jaredfogle who was on at the time, they advised me to file this bug report.

Steps for reproduction:

1. Be on icebox (Unknown if this issue is icebox specific or applies to all maps, I am merely stating the steps I took)
2. Proceed to the lowest z-level
3. Use a bluespace shelter capsule in hand (by pressing z) and hold it in your hand until it spawns in the shelter pod.
4. Turn off internals, begin suffocating

**Comment by AdipemDragon** [comment]
It might be that you oppened it under an open floor on the higher z-level and the pod just. Doesn't have a ceiling. So all the breathable air went up and around the walls

**Comment by plutori** [comment]
> It might be that you oppened it under an open floor on the higher z-level and the pod just. Doesn't have a ceiling. So all the breathable air went up and around the walls

Could be. Does that mean all of lavaland has a ceiling? I've never had this issue there.

**Comment by san7890** [comment]
I was able to reproduce this error. It occurs when you go on IceBox underneath an ice chasm, so all the air flows upwards by one Z-level. I suppose fixing it would involve adding a ceiling to the survival pods.

This is not an issue on Lavaland, which is only one Z-Level.
