### ISSUE TITLE
Axes can't bust down doors

### ISSUE THREAD

**Issue by Cheshify** [tgstation/tgstation#65499]
## Round ID:
[180015](https://scrubby.melonmesa.com/round/180015)

## Testmerges:
[#65445: 'MODsuit painting' by Fikou at commit 79c49641e4](https://www.github.com/tgstation/tgstation/pull/65445)

## Reproduction:
So, for some reason, you can't seem to attack doors with two-handed axes anymore.

**Comment by optimumtact** [comment]
finally the nerf of axes

**Comment by moocowswag** [comment]
> ## Round ID:
> [180015](https://scrubby.melonmesa.com/round/180015)
> 
> ## Testmerges:
> [#65445: 'MODsuit painting' by Fikou at commit 79c49641e4](https://www.github.com/tgstation/tgstation/pull/65445)
> 
> ## Reproduction:
> So, for some reason, you can't seem to attack doors with two-handed axes anymore.

I`ve noticed multiple issues with airlocks in general recently.

For instance you cant claim a circuit airlock with an id anymore, and you cant attack windoors without having combat mode off.

**Comment by MacBlaze1** [comment]
> I`ve noticed multiple issues with airlocks in general recently.
> 
> For instance you cant claim a circuit airlock with an id anymore, and you cant attack windoors without having combat mode off.

tool act rework seemed to screw a lot of stuff

**Comment by LemonInTheDark** [comment]
S a big change, bound to break stuff
@lewcc if you're interested
