### ISSUE TITLE
Revs can't end if an ex-headrev has their body destroyed (and thus, their mind.current null)

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#65516]
## Round ID: [180058](https://scrubby.melonmesa.com/round/180058)

![](https://images-ext-2.discordapp.net/external/Hz5KG-QKcILaOjz7K2XsG1bnYknVQh0iJ-uVz1pI8nI/https/i.imgur.com/sY7HdtC.png)

Ex-headrev got put into a cult shade, chaos ensues (the round doesn't end until I force the current to me then remove the headrev from myself)

https://github.com/tgstation/tgstation/blob/24af1c3a9816a5b9eb3fad84092812428ffcfa62/code/modules/antagonists/revolution/revolution.dm#L437

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=X7usA3YouKw
