### ISSUE TITLE
Words that aren't on the word filter are being hard and soft filtered 

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#65535]
## Round ID:
[180105](https://scrubby.melonmesa.com/round/180105)

## Reproduction:
I was unable to reproduce this on Terry, but multiple players were noticing this. One of the reporting players said they were on Byond version 514.1582

![image](https://user-images.githubusercontent.com/66640614/158887391-40e25c6e-b7a8-4041-960f-8ee901e862ef.png)

  id: 6936937
  datetime: "2022-03-17 19:56:22"
  round_id: 180105
  key_name: "soft_ic_blocked_words"
  key_type: "tally"
  version: 1
  json: "{\"data\":{\"antag\":3,\"chas\":1,\"erp\":3,\"fli\":1}}"

  id: 6936945
  datetime: "2022-03-17 19:56:22"
  round_id: 180105
  key_name: "ic_blocked_words"
  key_type: "tally"
  version: 1
  json: "{\"data\":{\"ur\":1,\"b\\u00e9\":1,\"wtf\":1,\"afk\":1,\"mo teanga \":1,\"xd\":1,\"lol\":3,\"lmao\":1,\"validhunting\":1,\"pls\":1,\"ngl\":1,\"now\":1}}"

--------------------------------------

This issue only began appearing once the servers were updated to Byond version 514.1582

**Comment by Mothblocks** [comment]
The BYOND issue is...?

**Comment by Mothblocks** [comment]
To be clear, I know what it is, or at least can figure it out, but not everyone has that benefit--Discord conversations are ephemeral, GitHub conversations are eternal.

**Comment by Mothblocks** [comment]
It doesn't appear to consistently filter specific words--I was able to say many words that were blocked.

**Comment by Mothblocks** [comment]
also nice 2^16 - 1 get

**Comment by dragomagol** [comment]
Updated

**Comment by LummoxJR** [comment]
Client version should be immaterial to this issue, as it's a server issue. But I need a test case to figure out what's wrong. My guess is something in the Unicode rework for 514.1582 ended up causing a subtle flaw in findtext/replacetext, especially the routine that does a case-insensitive search. But without being able to replicate said flaw, it's not something I can fix yet.

**Comment by Mothblocks** [comment]
@LummoxJR We're going to start logging what people chat when they get filtered in #65539. Hopefully that will lead to a consistent result, if it doesn't then it means `Find` is relying on some other state, not sure if it's implemented like that.

**Comment by Mothblocks** [comment]
Still can't get a repro, but have at least narrowed it down to being related to Unicode characters

![image](https://user-images.githubusercontent.com/35135081/159128528-f4e76b29-7fe1-4100-b440-34ec48cc5512.png)

(That is a dotless i, `ı`)

![image](https://user-images.githubusercontent.com/35135081/159128537-d1fe8c1e-787e-4fde-9cac-3ff5835dd88b.png)

![image](https://user-images.githubusercontent.com/35135081/159128541-dc94a73e-0f33-412b-8723-13df3466d45b.png)

**Comment by Mothblocks** [comment]
```
/mob/verb/test_findtext()
	var/regex/regex = regex(@"(tbh|tfw)", "i")
	usr << "match: [regex.Find("i managed to get the dude up but they keep escaping with severe brain trauöa")]"

```

**Comment by Mothblocks** [comment]
http://www.byond.com/forum/post/2776427

**Comment by Mothblocks** [comment]
This is fixed in 1583
