### ISSUE TITLE
Simplebot medibots can apparently enter "arrest" status

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#65547]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/158946274-f9a4e0d4-5a15-47a6-b38b-97a29193d9d5.png)

~~It wasn't a renamed bot or anything~~

**Comment by Jamarkus127** [comment]
Robotics got lazy and made multi-purpose bots.

**Comment by JohnFulpWillard** [comment]
i hate mode_name!! i hate mode_name!!
