### ISSUE TITLE
Error Item - The Concept of Cheese spawned in Icebox Ruin

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#65562]
Reporting client version: 514.1582

## Round ID:
[180183](https://scrubby.melonmesa.com/round/180183)

![Delicious Existentialism](https://user-images.githubusercontent.com/88996803/159107588-620e9dd9-c3ad-4cec-9ff6-31a401eb9282.png)

## Testmerges:
- [MODsuit painting](https://www.github.com/tgstation/tgstation/pull/65445)

## Reproduction:
Found item called The Concept of Cheese inside a locker in an icebox ruin, the diner-ish ruin with the giant ant in it. Item description is 'This probably shouldn't exist.'

**Comment by interestingusernam3** [comment]
Caused by my PR, #65422.
