### ISSUE TITLE
Delta airlocks pointing the wrong way.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#65563]
## Round ID:
#180184

![image](https://user-images.githubusercontent.com/7069733/159108824-7e3954c1-bad4-4a27-ad72-e36e16fef8d4.png)

Both sides of the shuttle slot has whatever that overlay effect is, pointing in the same direction when the other ones have them pointing outside on both side.

I don't into mapping enough to remember what that signifies, but it means something!

**Comment by Djvarik** [comment]
I don't know if there's any other possible reason but I've seen that white overlay appear when using the RCD and allowing directional all access on an airlock.
