### ISSUE TITLE
Error when i click on Take SSD Mob.

### ISSUE THREAD

**Issue by vengeful910month3** [tgstation/tgstation#65564]
## Reproduction:
Die as a xenomorph and wait 5 minutes and click Take SSD Mob

**Comment by vengeful910month3** [comment]
13856 is the round id

**Comment by SuperNovaa41** [comment]
What was the error?

**Comment by Serxule** [comment]
fairly certain this is supposed to be for tgmc

**Comment by SuperNovaa41** [comment]
Yeah i think so too
