### ISSUE TITLE
Last Ash Drake Active Turf bugs

### ISSUE THREAD

**Issue by Jolly-66** [tgstation/tgstation#65593]
## Reproduction:
This has a very specific recreation and the chances of it happening are most likely very low (if not, near impossible).

If the Last Ash Drake ruin spawns, and if anywhere above the ruin has holes leading to the above Z, it'll active turf both on Zs

![image](https://user-images.githubusercontent.com/70232195/159188336-5096327d-c982-458e-b257-0f2ff9db9cd3.png)
![image](https://user-images.githubusercontent.com/70232195/159188338-ea2407ec-63a8-4392-923e-8574ea8d915a.png)

**Comment by san7890** [comment]
Ceilings may be needed, since it's similar to #65582

**Comment by Jolly-66** [comment]
@timothymtorres 
You can probably close this, the linked PR didn't have the close prefix in the body but it was merged, so the issue should be resolved.
