### ISSUE TITLE
food created/transformed on griddle stops cooking

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#65608]
## Reproduction:

1.  Put raw meatball on grill
2. roll raw meatball to make patties
3. nothing happens and they dont start cooking
4. realise your attempt to save time at the extremely click & micro intensive production of even simple foods has been foiled and you have to pick each one up and put it back on.

I assume it's that when the meatball item is replaced by the patty item its no longer in the griddle's list of items that are on it.

**Comment by SyncIt21** [comment]
@timothymtorres a very ancient bug that is no longer the case?
