### ISSUE TITLE
kheiral cuff runtimes

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#65605]
## Round ID:
[180316](https://scrubby.melonmesa.com/round/180316)

## Testmerges:
#65539 

## Reproduction:
![image](https://user-images.githubusercontent.com/75639936/159334220-29f8b3c6-0e35-4006-9b31-1e4af30a91ef.png)
there is a few hundred runtimes on the cuffs

**Comment by Wallemations** [comment]
Not home but still gave it a look on my less-than-optimal laptop
It looks like when the GPS component is made, it's trying to force the player to interact with it for some reason.
Fun!

**Comment by Wallemations** [comment]
NVM figured it out, it wants to treat the cuffs like gloves but since they're an item it doesn't know what to do.

I'll just make them a form of gloves or something, that should fix it
