### ISSUE TITLE
Can interact with airlock wires after adding shielding

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#65609]
Reporting client version: 514.1571

## Round ID:
[180328](https://scrubby.melonmesa.com/round/180328)

## Testmerges:
- [Almost halves airlock auto close delay](https://www.github.com/tgstation/tgstation/pull/65349)
- [Action button refactor/rework: Enhanced Dragging](https://www.github.com/tgstation/tgstation/pull/65180)
- [Log filters better, including the message](https://www.github.com/tgstation/tgstation/pull/65539)

## Reproduction:

1. Have airlock wire UI open
2. Adding shielding to wires using plasteel
3. UI doesn't close, and wires can still be interacted with

**Comment by MacBlaze1** [comment]
This probably isnt a major issue unless the panel stays open forever, but it should be fixed for free gbp

**Comment by MacBlaze1** [comment]
a simple check in some ui proc should be enough

**Comment by cacogen** [comment]
>This probably isnt a major issue

How is that relevant? Do you comment this on all minor bugs that are reported?
