### ISSUE TITLE
Ambience sounds play even with earmuffs on

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#65618]
## Reproduction:
1) Equip earmuffs to drown out all noise
2) random ambience noises still play at full volume

**Comment by Serxule** [comment]
its because they're client-side sounds

**Comment by SuperNovaa41** [comment]
...no theyre not.
It's because SSambience doesn't check for hearing obstruction on the mob

**Comment by Serxule** [comment]
> ...no theyre not. It's because SSambience doesn't check for hearing obstruction on the mob

i know its not a literal client-side sound but you get what i mean

**Comment by timothymtorres** [comment]
Relevant ear code:

https://github.com/tgstation/tgstation/blob/bf0d7558f7f573e95390d1dab24632618044f0e7/code/modules/surgery/organs/ears.dm#L31-L52

Relevant ambience code:

https://github.com/tgstation/tgstation/blob/449b7245636b4a793a76dfdd44bb2f7529f6fae1/code/modules/client/client_procs.dm#L1140-L1146

Relevant ambience removal procs:

https://github.com/tgstation/tgstation/blob/579471bce53b7f3dd44717a77ecfe7da80ddc2d8/code/controllers/subsystem/ambience.dm#L26-L49

The solution is to use the ambience removal proc in the ear module to remove the client and then readd them once deafness goes away.  Unfortunately this fix is too big for me to do with webedits without messing it up.
