### ISSUE TITLE
Putting a kiosk wand into a storage item on the ground lets you walk off with it.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#65611]
Reporting client version: 514.1582

## Round ID:
180331

## Testmerges:
- [Almost halves airlock auto close delay](https://www.github.com/tgstation/tgstation/pull/65349)
- [Action button refactor/rework: Enhanced Dragging](https://www.github.com/tgstation/tgstation/pull/65180)
- [Log filters better, including the message](https://www.github.com/tgstation/tgstation/pull/65539)

## Reproduction:
1. Remove the wand from a medical kiosk.
2. Place it into a nearby storage item on the floor. (A burn medkit for example.)
3. Walk away from the kiosk with the storage item containing the wand.
4. Take the wand out of the storage item.
5. Leave with the wand.

![Wand](https://user-images.githubusercontent.com/53582584/159383214-097a99f5-fe42-47ce-adb6-c0665eba5e2c.png)

**Comment by dragomagol** [comment]
I made the PR faster than I checked lmao, but you can run off with the medical wand even if it's not in a box

**Comment by TemporalOroboros** [comment]
It's supposed to snap back to the scanner if you get too far away IIRC.

**Comment by TemporalOroboros** [comment]
Has that ever been a thing?

**Comment by ArcaneMusic** [comment]
It is intended to snap back to the machine in a similar way to the defib paddle, yes.

**Comment by SuperNovaa41** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/65613 (i think)
