### ISSUE TITLE
You can force-feed people who have no heads

### ISSUE THREAD

**Issue by interestingusernam3** [tgstation/tgstation#65647]
## Round ID:
180433

## Testmerges:
[#65625: 'Pingbus changes and improvements' by Watermelon914 at commit 323f5df074](https://www.github.com/tgstation/tgstation/pull/65625)
[#65591: 'makes vent scrubbers only activate if a gas they filter is on their tile, again! alive edition' by Kylerace at commit 4fc46411fb](https://www.github.com/tgstation/tgstation/pull/65591)

## Reproduction:
1. kill and decapitate a human
2. force-feed the decapitated human something
3. human eats it

**Comment by newfren** [comment]
you're ramming it down the hole

**Comment by ATH1909** [comment]
> you're ramming it down the hole

this

**Comment by capsaicinz** [comment]
> you're ramming it down the hole

quite outstanding idea you've give me here, just a moment and i can resolve this issue

**Comment by JohnFulpWillard** [comment]
closed by https://github.com/tgstation/tgstation/pull/65717
