### ISSUE TITLE
Magic Polar Bear Transformation removes the ability to hear 

### ISSUE THREAD

**Issue by Eronymun** [tgstation/tgstation#65653]
Reporting client version: 514.1582
## Round ID:
[180443](https://scrubby.melonmesa.com/round/180443)

## Testmerges:
- [Adds mob bleeding overlays, tweaks some bleeding balance](https://www.github.com/tgstation/tgstation/pull/65371)
- [Pingbus changes and improvements](https://www.github.com/tgstation/tgstation/pull/65625)
- [Almost halves airlock auto close delay](https://www.github.com/tgstation/tgstation/pull/65349)
- [Action button refactor/rework: Enhanced Dragging](https://www.github.com/tgstation/tgstation/pull/65180)

## Reproduction:
Using the ability to transform into a magic bear gained from the wendigo blood bottle causes you to lose the ability to read text after returning to your prior form. Going from your prior form back to your bear form causes you to regain the ability to hear text. The ability to talk and hear over radio is unhindered, you just can't see any local chatter, including your own, in both rune text and in the chat menu. I've noticed this issue persisting through several rounds as miner on icebox.

**Comment by newfren** [comment]
this also happens with the drake transformation

**Comment by timothymtorres** [comment]
This may due to polymorph code being pretty buggy.  Related to #42685

**Comment by newfren** [comment]
oh yeah I remember that this issue fixes itself when you change z-levels
