### ISSUE TITLE
Bluespace Body Bag trapped user inside for a moment upon opening for the first(?) time.

### ISSUE THREAD

**Issue by joybod** [tgstation/tgstation#65673]
Reporting client version: 514.1566

## Round ID:
[180495](https://scrubby.melonmesa.com/round/180495)

## Testmerges:
- [Turbine Rework](https://www.github.com/tgstation/tgstation/pull/65586)
- [Pingbus changes and improvements](https://www.github.com/tgstation/tgstation/pull/65625)

## Reproduction:
After printing one fresh, I used the bluespace body bag in hand. It opened as usual, but I was trapped for a moment. While it displayed the graphic of being open, it made my character disappear like it was closed with me standing over it (including the darkness rimming the screen). I attempted to perform the bug again, but it opened without sucking me inside the second time, closing as normal as well.

**Comment by timothymtorres** [comment]
Might be related to #64631.  Bluespace bodybags have been known to be quite glitchy.

**Comment by Sealed101** [comment]
i'd wager that this happened because of a little bit too many clicks on the item when it was picked up, which caused the bag to open and close but not really? i don't think i can reproduce this; it's been a year and nothing similar has been reported from what i can tell
