### ISSUE TITLE
Bartenders unable to properly throw glasses.

### ISSUE THREAD

**Issue by CMDR-Gungnir** [tgstation/tgstation#65678]
Reporting client version: 514.1582

## Round ID:
[180501](https://scrubby.melonmesa.com/round/180501)

## Testmerges:
- [Turbine Rework](https://www.github.com/tgstation/tgstation/pull/65586)
- [Pingbus changes and improvements](https://www.github.com/tgstation/tgstation/pull/65625)

## Reproduction:

Step 1) Be a Bartender (or Select Equipment -> Bartender, as Jackraxxus tested for me, too)
Step 2) Fill a glass with any drink
Step 3) Throw it while wearing your special Bartender Glasses
Step 4) See in chat that it says it lands without spilling a drop
Step 5) Watch the glass shatter, like your hopes and dreams
Step 6) Be told that it's giving you the trait properly, and checks 'CanPass'

**Comment by ATH1909** [comment]
sad

off-topic, but at some point, we should add a special message for throwing reading glasses while wearing bartender glasses, as a pun.

**Comment by LemonInTheDark** [comment]
Broken by https://github.com/tgstation/tgstation/pull/65356
I was expecting togh to make a fix, but I think I scared him off.
