### ISSUE TITLE
Gutlunch Healing Bugged

### ISSUE THREAD

**Issue by RikuTheKiller** [tgstation/tgstation#65687]
## Reproduction:

Gutlunches, although meant to recover health (According to the wiki, but even if they weren't, in order to make them eat you HAVE to hit them with your fist, pretty much.) when eating gibs, organs and such, don't.

They don't eat limbs, leaving the necropolis tendril room quite messy once enough humanoid corpses are gibbed. (Such as legion corpses, miners or other ash walkers.)

I personally would make gibbing them through the necropolis tendril either drop no limbs or make gutlunches able to eat limbs to remedy this issue.

Please, for the love of god, fix the healing so I don't accidentally gib our only remaining gutlunch while trying to just do some cleanup for a mood modifier. (The limb thing CAN be remedied by simply using a crate to drag them out, but it still defeats the entire point of having gutlunches there in the first place. Also, the limbs from gibbing humanoids can hit the ashwalkers in the face, dealing quite a bit of damage.)

**Comment by timothymtorres** [comment]
Somewhat related to #47568.  Apparently they need to be damaged in order for them to eat which is why people say you need to punch them first.

**Comment by RikuTheKiller** [comment]
On that thread the person who closed it stated "they eat to heal" which is bugged. So yeah, fairly sure they're intended to heal from it.

**Comment by timothymtorres** [comment]
They won't eat if they are at full health.  Were they refusing to eat regardless if they were damaged or not?

**Comment by RikuTheKiller** [comment]
They ate for a while after being hit, but then just abruptly stopped until being hit again. Sometimes they decide to eat anyways. They act weirdly. Also, when checking their health as a ghost, it never increases even when they eat.

**Comment by RikuTheKiller** [comment]
Though, they may keep eating without being hit again. I'm actually not sure, I may have to investigate this a little further.

**Comment by timothymtorres** [comment]
Fixed by #69242
