### ISSUE TITLE
Humans are immune to pressure and thermal damage in space

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#65696]
Reporting client version: 514.1582

## Round ID:
[180547](https://scrubby.melonmesa.com/round/180547)

## Testmerges:
- [Pingbus changes and improvements](https://www.github.com/tgstation/tgstation/pull/65625)
- [makes vent scrubbers only activate if a gas they filter is on their tile, again! alive edition](https://www.github.com/tgstation/tgstation/pull/65591)
- [Kapulimbs](https://www.github.com/tgstation/tgstation/pull/65523)
- [Turbine Rework](https://www.github.com/tgstation/tgstation/pull/65586)

## Reproduction:

Spawn yourself in space as a human in e.g. assistant clothing.  You will require an oxygen internals tank.
Wear and engage the internals.
Notice how fine you are.

Pressure damage does not seem to be applying.  Thermal damage also ; the core/body temperature decreases but no damage is taken.

Low pressure and low temperature alerts top-right are triggered.

This bug does NOT seem to apply to other species e.g. ethereal or felinid.

**Comment by TheBonded** [comment]
Why do I feel like this is something weird with spawning as a human with kapulimbs testmerged?

**Comment by JohnFulpWillard** [comment]
I'm gonna assume this is a testmerge bug, please report it on https://github.com/tgstation/tgstation/pull/65523 instead.

**Comment by LemonInTheDark** [comment]
This is being reported as still an issue

**Comment by JohnFulpWillard** [comment]
> This is being reported as still an issue

because kapulimbs was merged now ☹️

**Comment by LemonInTheDark** [comment]
closed by https://github.com/tgstation/tgstation/pull/65887
