### ISSUE TITLE
Mirrors fail to set hair or beard

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#65692]
Reporting client version: 514.1582

## Round ID:
[180537](https://scrubby.melonmesa.com/round/180537)

## Testmerges:
- [Pingbus changes and improvements](https://www.github.com/tgstation/tgstation/pull/65625)
- [makes vent scrubbers only activate if a gas they filter is on their tile, again! alive edition](https://www.github.com/tgstation/tgstation/pull/65591)
- [Kapulimbs](https://www.github.com/tgstation/tgstation/pull/65523)
- [Turbine Rework](https://www.github.com/tgstation/tgstation/pull/65586)

## Reproduction:

Spawn a /obj/structure/mirror/directional/east as per a random bathroom mirror I picked.
Spawn in as a human.
Attempt to use the mirror to change your hair or beard.
Nothing happens.

**Comment by LemonInTheDark** [comment]
Likely #65523

**Comment by Kapu1178** [comment]
I thought I fixed this, damn it

**Comment by Kapu1178** [comment]
Issue identified and fixed.
