### ISSUE TITLE
atmos pumps can be toggled past windows

### ISSUE THREAD

**Issue by nogoodidea** [tgstation/tgstation#65709]
## Reproduction: 
walk up to a direcinial window with a pump on the other side of it (like in meta atmos).
use hotkeys to toggle the pump while being on the other side of the window.
it toggles.

**Comment by nogoodidea** [comment]
still happens as of latest git build.

**Comment by MacBlaze1** [comment]
this is due to the nature of the sanity checks on the toggling of the pumps
