### ISSUE TITLE
Face hugger modsuit inconsistency

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#65708]
[Round ID]: unimportant
## Testmerges:
[#65371: 'Adds mob bleeding overlays, tweaks some bleeding balance' by Ryll-Ryll at commit 184edbbb2a](https://www.github.com/tgstation/tgstation/pull/65371)
[#65625: 'Pingbus changes and improvements' by Watermelon914 at commit cd8865bb1b](https://www.github.com/tgstation/tgstation/pull/65625)
[#65349: 'Almost halves airlock auto close delay' by LemonInTheDark at commit f1d38cedcf](https://www.github.com/tgstation/tgstation/pull/65349)
[#65180: 'Action button refactor/rework: Enhanced Dragging' by LemonInTheDark at commit 3a7028c959](https://www.github.com/tgstation/tgstation/pull/65180)

## Reproduction:
 Throw a face hugger at someone wearing a modsuit. Hugger teleports into the mask slot without the helmet being disturbed. Was thinking that it was strange that it would teleport into the mask slot without destroying or being blocked by the helmet.

**Comment by davethwave** [comment]
To give a bit more information. after getting facehugged the modsuit I used (engineering) didn't shutdown. Just acted like normal. Shoved the current mask off my face though which was that welding gasmask, knocked me unconscious and all that as they typically do.

**Comment by Fikou** [comment]
sounds like you had the mouth apparatus
