### ISSUE TITLE
Chisel and block not working most of the time.

### ISSUE THREAD

**Issue by RobertRoberts2020** [tgstation/tgstation#65701]
Reporting client version: 514.1583

## Round ID:
[180555](https://scrubby.melonmesa.com/round/180555)

## Testmerges:
- [Pingbus changes and improvements](https://www.github.com/tgstation/tgstation/pull/65625)
- [Turbine Rework](https://www.github.com/tgstation/tgstation/pull/65586)

## Reproduction:
Most of the time the chisel and block don't work, the theme menu never comes up and nothing happens after getting the message " you prepare to work on the gold block" once I managed to get it working but most of the time it doesn't I asked other players to do it and some can do it and some others can't. this is frustrating.

Steps to reproduce:
1) Craft a block with any material.
2) Use a chisel on the block
3) nothing happens.

**Comment by newfren** [comment]
you have to chisel the block then chisel the thing you want to make a statue of

**Comment by TheBonded** [comment]
This isnt a bug, you click on the block, click on what you want to make a statue of (at any range), then click on the block instead to start carving.

**Comment by RobertRoberts2020** [comment]
> This isnt a bug, you click on the block, click on what you want to make a statue of (at any range), then click on the block again to start carving.

Ok, then it needs some kind of GUI feedback to let people who are either new or stupid (I'm included in both categories) that you need to click on something and then click on the block again, because there's no way to guess that's what the game expects you to do.
