### ISSUE TITLE
Heads of Staff seem to be using backup human names, even when human

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#65712]
Reporting client version: 514.1582

## Round ID:
[180598](https://scrubby.melonmesa.com/round/180598)

## Testmerges:
- [Pingbus changes and improvements](https://www.github.com/tgstation/tgstation/pull/65625)
- [makes vent scrubbers only activate if a gas they filter is on their tile, again! alive edition](https://www.github.com/tgstation/tgstation/pull/65591)
- [Kapulimbs](https://www.github.com/tgstation/tgstation/pull/65523)

## Reproduction:

As per the subject.  Some of us still have backup set to the same as our primary name from the last time this bug happened so it's not universal.  Apparently is only happening on Terry right now so likely test merge related.  Had multiple tickets and verified against a few head of staff's preferences for people who didn't ticket and the pattern seems to hold out.

**Comment by dragomagol** [comment]
I suspect this is due to the Kapulimbs testmerge.

**Comment by JohnFulpWillard** [comment]
> I suspect this is due to the Kapulimbs testmerge.

https://github.com/orgs/tgstation/teams/issue-managers/discussions/11

PR in question to report to https://github.com/orgs/tgstation/teams/issue-managers/discussions/11
