### ISSUE TITLE
Zeta Emergency shuttle loses one of the rooms plus a door

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#65711]
Reporting client version: 514.1581

## Round ID:
[180588](https://scrubby.melonmesa.com/round/180588)

## Testmerges:
- [Pingbus changes and improvements](https://www.github.com/tgstation/tgstation/pull/65625)

## Reproduction:

On round 180588 on Bagil the Zeta Emergency shuttle docked at the station with the floor of the room immediately to the right of the bridge, above the repair bay missing. This included all floor tiles as well as the airlock to this room, resulting in the immediate depressurizing of the emergency shuttle. As best as I could tell the floor was not left behind at central.

**Comment by dragomagol** [comment]
This one's probably my fault, from #65615

**Comment by dragomagol** [comment]
Update because I am in pain: when a brig area is added anywhere else on the shuttle, unconnected to the cluster of tiles in the brig, the brig doesn't disappear. I have no idea why this happens, but without this the brig is not considered part of the shuttle.

**Comment by dragomagol** [comment]
Happens with and without plating floors. For some reason replacing the floors with mineral abductor floors spawns the shuttle sawed in half. Shuttle code is a mystery.
