### ISSUE TITLE
All GUIs break.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#65719]
Reporting client version: 514.1582

## Round ID:
[180250](https://scrubby.melonmesa.com/round/180250)

## Testmerges:
- [Action button refactor/rework: Enhanced Dragging](https://www.github.com/tgstation/tgstation/pull/65180)
- [Almost halves airlock auto close delay](https://www.github.com/tgstation/tgstation/pull/65349)
- [Log filters better, including the message](https://www.github.com/tgstation/tgstation/pull/65539)

## Reproduction:
1. (Optional) Spawn as the HoP, and acting captain, on deadpop Kilostation.
1. Have a GUI become a white box.
2. Have this problem spread to other GUIs.
3. Have this problem spread to the chat and status tab.
4. Reconnect.
5. Have all ingame GUIs no longer open at all.
6. Have the chat and status tab inform you that they cannot connect to some IP. (Probably localhost. I've forgotten)
7. Relog and have the problem persist.
8. Be unable to interact with any ingame GUI interfaces, hear people talking on comms, or ahelp.
9. (Optional) Be unable to go SSD because you are the acting captain, sole head, and bearer of the disk.

**Comment by Sealed101** [comment]
did this ever repeat
the better question would be can we ever reproduce this reliably
