### ISSUE TITLE
Destroying a Mech with the SM shard in it somehow destroys and deletes the SM shard itself

### ISSUE THREAD

**Issue by TheMaggotGuy** [tgstation/tgstation#65723]
Reporting client version: 514.1578

## Round ID:
[180610](https://scrubby.melonmesa.com/round/180610)

## Testmerges:
- [Adds mob bleeding overlays, tweaks some bleeding balance](https://www.github.com/tgstation/tgstation/pull/65371)
- [Pingbus changes and improvements](https://www.github.com/tgstation/tgstation/pull/65625)
- [Almost halves airlock auto close delay](https://www.github.com/tgstation/tgstation/pull/65349)
- [Action button refactor/rework: Enhanced Dragging](https://www.github.com/tgstation/tgstation/pull/65180)

## Reproduction:

Someone is carrying SM shard through the halls. A Ripley MK II mech scoops up the crate somehow. The followers of the shard destroy the mech, and somehow this deletes the SM crystal.

**Comment by timothymtorres** [comment]
Relevant to #61600.  I still think it's a bug that mechs can pickup SM shards without getting dusted.

**Comment by Sealed101** [comment]
destroying the mech drops out whatever was in cargo currently; it would appear that this was somehow broken on the fundamental drop-shit-out-of-thing level, but this was amended... unless this was caused by some other miracle and i can't reproduce it. oh for fuck's sake
