### ISSUE TITLE
Bartender's Throwing Ability

### ISSUE THREAD

**Issue by Slurge00** [tgstation/tgstation#65738]
Reporting client version: 514.1568

## Round ID:
[180646](https://scrubby.melonmesa.com/round/180646)

## Testmerges:
- [Pingbus changes and improvements](https://www.github.com/tgstation/tgstation/pull/65625)
- [Overhauls Security on IceBox](https://www.github.com/tgstation/tgstation/pull/65699)

**Comment by LemonInTheDark** [comment]
Resolved by #65698, least it ought to have been
