### ISSUE TITLE
Ripley Mechs can't hold more than one utility tool?

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#65777]
## Reproduction:

You can ONLY attach a SINGLE hydraulic clamp OR plasma cutter / Drill / Mecha PKA to a Ripley mining mech. This makes mech mining 100% impossible at least with the Ripley as you need the clamp to pick up crates to hold ores, you need a PKA for defense (the whole reason it was added), a plasma cutter to mine rocks, a drill to mine sand and a mining scanner to actually see the ores.

EDIT: Apparently you can attach two in-hand modules by left clicking which isn't said anywhere in-game and I only figured it out by reading the PR multiple times. Still, this doesn't leave much room for "optional" modules like a kinetic gun or a drill.

**Comment by Serxule** [comment]
this is probably caused by that new mech refractor thing

**Comment by githubuser4141** [comment]
most likely, yes. I hope it isn't intended because mechs are 100% useless for mining if you don't have at least three (hydraulic clamp, plasma cutter, drill) ACTIVE in-hand modules on. Ideally and before the refractor you'd have a clamp, a cutter, a drill a kinetic gun (for killing mobs easily) and a scanner for mining.

**Comment by TheBonded** [comment]
wait people unironically use mechs for mining?

**Comment by githubuser4141** [comment]
> wait people unironically use mechs for mining?

yes, I'll tell you why. Mechs (pre-refactor) are quicker than a miner on foot, are sturdier taking only 3-5% damage to the front armor from most mobs. Their plasma cutter has extended range and mechs pick up ores from a 3x1 tile radius so if you're using a Ripley you can move in ANY direction while facing the ores. So the 'penalty' for not being able to turn is very slight. And of course you can turn on a dime by pressing ALT + directionyouwant.

Pre-refactor it'd be a thing to rush a Ripley and outdo the miners (who'd be saying "waa.. mechs are shit...", it was pretty easy to get something like 1M metal, 400k silver/gold and 100k for the less common minerals.

**Comment by TheBonded** [comment]
![Capture+_2022-03-30-07-25-52.png](https://user-images.githubusercontent.com/58570888/160845269-f4fb85e5-ded6-4a90-9e14-b2981459d0a4.png)
