### ISSUE TITLE
Pheromone Receptors icon is an error

### ISSUE THREAD

**Issue by RadsammyT** [tgstation/tgstation#65773]
## Testmerges: [#65371: 'Adds mob bleeding overlays, tweaks some bleeding balance' by Ryll-Ryll at commit 184edbbb2a](https://www.github.com/tgstation/tgstation/pull/65371)
[#65625: 'Pingbus changes and improvements' by Watermelon914 at commit cd8865bb1b](https://www.github.com/tgstation/tgstation/pull/65625)
[#65180: 'Action button refactor/rework: Enhanced Dragging' by LemonInTheDark at commit 3a7028c959](https://www.github.com/tgstation/tgstation/pull/65180)

## Reproduction:
>Be Changeling
>Get Pheromone Receptors
>See the icon be an ERROR

![0cPgpqSt4T](https://user-images.githubusercontent.com/32146976/160507957-be010a11-999f-4445-85a3-02419fbf5bea.png)

**Comment by RadsammyT** [comment]
Also, I have reason to believe that Absorbing a person as a changeling may be outdated.
As a changeling, I cannot absorb people who I am grabbing **Aggressively**

**Comment by Serxule** [comment]
> Also, I have reason to believe that Absorbing a person as a changeling may be outdated. As a changeling, I cannot absorb people who I am grabbing **Aggressively**

absorbing requires you to be choking the person

**Comment by necromanceranne** [comment]
This power never had an icon.
