### ISSUE TITLE
Borg Drinks Reagent oversight

### ISSUE THREAD

**Issue by Wallemations** [tgstation/tgstation#65798]
## Round ID:
[180755](https://scrubby.melonmesa.com/round/180755)

## Testmerges:
#65625 

## Reproduction:

1. Be service borg
2. Fill something with a drink
3. Pour into another container
4. Drop the empty glass
5. Go as far away as you want from it
6. It magically refills despite not being anywhere near you

Originally I thought I was making glasses of infinite booze, but it turns out this is just an intended feature with a slight oversight. It refilling no matter your distance to it seems a little odd to me, seeing how there's no visual indication that it's refilled itself because of the borg. Because of this I thought it was a massive bug or something like that.

I'd recommend stopping the timer if it exits the inventory, or making some kinda beam going from the borg to the drink showing that it's being refilled because of them.

**Comment by Kubisopplay** [comment]
It's not a bug, it is intended that borg glass grabber resynthesizes drinks you make with it, for a sizable power cost

**Comment by ATH1909** [comment]
> It's not a bug, it is intended that borg glass grabber resynthesizes drinks you make with it, for a sizable power cost

this

https://github.com/tgstation/tgstation/pull/58638

it was intentional both before and after this PR, btw, according to the code comments.

**Comment by Wallemations** [comment]
I realized what happened, and I know what the issue is now.

While it is intended, it seems pretty weird that a glass that's on the other side of the station will still refill itself, even if you're not holding it.
