### ISSUE TITLE
Posimech UI doesn't give you anything besides the access panel

### ISSUE THREAD

**Issue by RegJackson** [tgstation/tgstation#65796]
Reporting client version: 514.1568
![image](https://user-images.githubusercontent.com/91390185/160747052-8ed8d1e6-70f5-4177-8c34-2d6a2b742ba6.png)
From what I understand, Posimech UI is borked. Can't turn on equipment, can't get status readouts. You just get access to the access panel, and uploaded accesses don't even work. Not sure the depths to which this is borked because I haven't been here in a while but it's easy as hell to reproduce so someone smarter should be able to follow up.

## Round ID:
[180755](https://scrubby.melonmesa.com/round/180755)

## Testmerges:
- [Pingbus changes and improvements](https://www.github.com/tgstation/tgstation/pull/65625)

## Reproduction:
Step 1: put posibrain in mech
step 2: attempt to open stats
step 3: suffer

**Comment by dragomagol** [comment]
Likely caused by #65375 @TiviPlus
