### ISSUE TITLE
Sanitization kills the markings on the forms

### ISSUE THREAD

**Issue by twilightwanderer** [tgstation/tgstation#65831]
## Reproduction:

Hi, in PR #61323 I implemented the form system. It was based on the use of pre-formed html/css code. But as I understood from the names in #65752 this approach is not safe. I'm getting to the question, is it worth trying to maintain these mechanics or is it just easier to remove it from the TG codebase?
![изображение](https://user-images.githubusercontent.com/88540658/161036107-48e43165-6aca-4f7a-8c62-063d5db9120a.png)

**Comment by timothymtorres** [comment]
@AnturK might be able to answer this here, but you would be better off asking questions like this on the coderbus discord.

**Comment by SuperNovaa41** [comment]
very much a bug this is supposed to be a feature

**Comment by AnturK** [comment]
Just a bug most likely, static raw html content shouldn't be an issue.
