### ISSUE TITLE
chemical acclimator is filling while heating

### ISSUE THREAD

**Issue by RafRoq** [tgstation/tgstation#65874]
chemical aclimmator keeps filling state even while heating which causes unwanted behavior, like waiting for a reaction to end before accepting anymore reagents.

for example a nitric acid reation requires facid, hydrogen peroxide and nitrogen, there is a reation chambers right before it, that feeds it,
the chemicals are sent to the aclimmator and the reaction starts once its done the chemicals are sent to a tank, but since the acclimator keeps accepting reagents, it will send nitric acid and some more reagents

**Comment by timothymtorres** [comment]
I don't have any experience in chemistry to know if this is a feature request or if this is an actual bug.

**Comment by TheBonded** [comment]
as far as I can tell, this isnt a bug, and you should just put the acclimator **before** the reaction chamber, as the acclimator will continue filling and will always deposit what it contains if it is at the target temperature, as it is not a reaction chamber and doesnt wait for reactions to finish to send and receive chemicals
