### ISSUE TITLE
Humans appear to be space immune

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#65883]
## Testmerges:

#65795
#65841 
#65860 

## Reproduction:

>See other assistant in space
>Get curious
>They yell at me to put oxygen on and walk out with them
>Holy fuck it works
>Set up a couch with the boys
>Be space assistants, assistants in space.

Only oxygen is necessary to be completely space immune as an assistant because of this.

**Comment by robbertapir** [comment]
honestly quite incredible

**Comment by GolfinhoVoador** [comment]
could be a missed april fools joke leftover

**Comment by Kapu1178** [comment]
Cannot reproduce locally

**Comment by TheBonded** [comment]
duplicate of https://github.com/tgstation/tgstation/issues/65696
