### ISSUE TITLE
Bluespace Golem Multi-Teleportation Bug

### ISSUE THREAD

**Issue by RikuTheKiller** [tgstation/tgstation#65900]
## Reproduction:
The bluespace golem's manual teleportation ability doesn't go on cooldown until it has charged up and teleported you. This means you can use it as many times as you want during the startup until it teleports you, for quite the funny effect of teleporting across the station like fucking crazy. Somehow, this isn't actually laggy and doesn't destroy your ears.

Step 1: Become a bluespace golem.
Step 2: Spam the manual teleportation ability.
Step 3: AAAAAAAAAAAAAAAAAAAAAA

Personal opinion: Make the teleport useable while in crit, but it instead does what this bug does (Just teleports you 10 times rapidly.) and kills you. As a form of final escape or something if you happen to end up in medbay, which isn't exactly likely. It's just cool.

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=82DJUDS_S7Y

fits, tbh. feature.

**Comment by apynnonen** [comment]
You can close this bug now I think. Sorry again Livrah, I didn't know before fixing it. :(
