### ISSUE TITLE
Androids Sprite Broken?

### ISSUE THREAD

**Issue by Cheshify** [tgstation/tgstation#65913]
## Round ID:
[181033](https://scrubby.melonmesa.com/round/181033)

## Testmerges:
None

## Reproduction:
Simply spawn an android, their sprite will be a pasty white without any eyes, is this intentional?
![image](https://user-images.githubusercontent.com/73589390/161451984-6c22c28e-b884-4c57-aef3-84116481c436.png)

**Comment by Serxule** [comment]
weird, beestation has this too but i thought that was just their sprite (even though the wiki said otherwise). definitely a byond thing going on

**Comment by Kapu1178** [comment]
nah its definitely my fault.
