### ISSUE TITLE
AI unable to submit stories or create newscaster channels.

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#65921]
Reporting client version: 514.1581

## Round ID:
[181045](https://scrubby.melonmesa.com/round/181045)

## Reproduction:
Be an AI, try to use new shiny TGUI newscasters, pain instead.
Clicking to create a channel or submit a story does not work.
![image](https://user-images.githubusercontent.com/81882910/161474195-4dde40ca-f560-4baf-b9b4-c77c3d9b8231.png)

**Comment by timothymtorres** [comment]
Duplicate of #65801
