### ISSUE TITLE
Cryo tubes eject you saying you are healed when its false with pyroxadone

### ISSUE THREAD

**Issue by Deathfox666** [tgstation/tgstation#65924]
Reporting client version: 514.1581

## Round ID:
[181055](https://scrubby.melonmesa.com/round/181055)

## Testmerges:
none

## Reproduction:
here are steps
step 1 hook up the cryo room gas tanks
step 2 set the thermo machines to heating(for pyro to work)
step 3 put beaker of pyroxadone into the cryo tube
step 4 put a injured into the cryo tube
step 5 watch as the cryo tube reports fully healed and shuts off/ejects you after a bit being turn on

**Comment by SmArtKar** [comment]
This is going to be fixed by #65904
