### ISSUE TITLE
Big White Box

### ISSUE THREAD

**Issue by fndkfurkan** [tgstation/tgstation#65937]
![image](https://user-images.githubusercontent.com/50272923/161605829-994eebe6-1d06-424f-b387-3ffd68573b4e.png)
This white screen blocks all of the menus and makes me unable to interact with the menus

Any solutions?

**Comment by necromanceranne** [comment]
Probably a tgui window that failed to load. Maybe restart the game?

**Comment by Serxule** [comment]
yeah its just a tgui window bug, usually fixed by closing and reopening the game

**Comment by fndkfurkan** [comment]
> Probably a tgui window that failed to load. Maybe restart the game?





> yeah its just a tgui window bug, usually fixed by closing and reopening the game


I tried it but it didint work + I tried to reinstall byond delete the cache etc.

**Comment by TheBonded** [comment]
open the server, open the character settings, game settings, and changelog, odds are it's one of those failing to load.

**Comment by interestingusernam3** [comment]
Get a better internet connection

**Comment by private-tristan** [comment]
run build.bat works for me
