### ISSUE TITLE
Ethereal hair color is borked

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#65941]
## Round ID:
N/A

## Testmerges:
See above

## Reproduction:
Ethereal hair color is no longer properly overrided by their glow, and is instead tied to the hair color they had selected before changing species.
![image](https://user-images.githubusercontent.com/58055496/161622105-d88d77c3-c275-46b3-8905-27a4e62bf1f2.png)

Pls fix

**Comment by ATH1909** [comment]
cursed

**Comment by Bluedino1025** [comment]
Wait, this is a bug? I’ve been able to edit it without changing species first and also quite like how I’ve rigged it.
