### ISSUE TITLE
I accidentally made an invisible face mask and an admin told me to report it after I adminhelped.

### ISSUE THREAD

**Issue by atomic1fire** [tgstation/tgstation#65947]
Reporting client version: 514.1583

## Round ID:
[181089](https://scrubby.melonmesa.com/round/181089)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Biddle Verbs: Queues the Most Expensive Verbs for the Next Tick if the Server Is Overloaded](https://www.github.com/tgstation/tgstation/pull/65589)
- [Refactor and improve antimagic to be more robust](https://www.github.com/tgstation/tgstation/pull/64124)

## Reproduction:

I was screwing around with a black crayon, some custom bandanas, and some gloves, and dyed it all in the washing machine. Two items came out fine, and the third lost it's sprite.

**Comment by atomic1fire** [comment]
This might make it possible to conceal/fake your identity, if the sprite doesn't show up for anyone. I just thought it was a funny error.

**Comment by thgvr** [comment]
#65760 Maybe this?

**Comment by Ebb-Real** [comment]
I attempted to recreate this, with 2 gloves and one bandana and 2 bandanas + 1 glove along with a bunch of other clothing at the same time and in different combos with different color crayons. I did it with all 3 of the bandana types, but failed to recreate the bug. @atomic1fire what exactly did you use and which item went invisible?

**Comment by atomic1fire** [comment]
One of the facemasks went invisible.

IIRC

I was trying to put the hankerchief on my head, reversed it a few times, made it into a scarf, and then realized that it no longer had a sprite.

**Comment by Ebb-Real** [comment]
okay i know whats causing this, when you push your bandana into a hat and dye it the sprite gets switched to the normal bandana but still has the _up greyscale config so when you then try to change it again glitches out the sprite
