### ISSUE TITLE
JPS paths around railings strangely

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#65962]
## Round ID:

Local

## Testmerges:

None

## Reproduction:
![](https://i.imgur.com/m5f1aVF.png)
I'm assuming this will create issues with bots trying to path past parallel railings getting stuck trying to go behind them instead.

If you get rid of the railing, the path appears as you'd expect.
![Halaal City Forty-Five 2022-04-06 020105](https://user-images.githubusercontent.com/25089914/161771260-09f05bf3-5058-46cb-89ab-ba09b7de567b.png)

**Comment by AnturK** [comment]
Should have been fixed by #65930
