### ISSUE TITLE
Something weird was happening with the spiders' webs and cocoons.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#65975]
## Testmerges: #65860: '[April Fools] Live Moth Reaction' by RigglePrime 

Spiders were placing the webs outside of the holodeck on the Delta station. After few ticks of being there the webs were just disappearing. The same thing was happening with the cocoons as well. There was a corpse wrapped into the cocoon, after few moments the cocoon just vanished, dropping the corpse outside.

**Comment by IndieanaJones** [comment]
There's a gas that destroys spider structures.  Pretty sure its BZ.

**Comment by MrMelbert** [comment]
Not just BZ, but any gas (air in general) that's too hot or too cold will slowly destroy spider structures

**Comment by IllotAFV** [comment]
Yes, I know that, however not every tile was affected. For example, in the locker room only half of the tiles were under this effect, an adjacent tile was working correctly, the web didn’t disappear there. Or only a quarter of the holodeck itself was vanishing the web tiles.

**Comment by IndieanaJones** [comment]
Could be something with atmos and the holodeck then?  Or just the holodeck in general?

**Comment by IllotAFV** [comment]
This wasn't happening exclusively at the holodeck. Spiders couldn't web the area in between the holodeck and the dormitory. But in the locker room, which is right after the court and before the washing machines, they could web the half of the room. The other half was under that weird effect.

**Comment by IndieanaJones** [comment]
Could also just be atmos doing atmos stuff as well.  I don't see what else would destroy the structures.

**Comment by IllotAFV** [comment]
If it had been the atmos, spiders would have been damaged as well, right? They weren’t harmed at all. I may or may not be missing something.

**Comment by TheBonded** [comment]
if it was BZ that could have been the reason it didnt harm the spiders. its also possible the temperature threshold that spiders start taking damage is larger than that of the webs and cocoons

**Comment by IllotAFV** [comment]
Alright, sure, I’ll try to keep an eye on the another occurrence of this. Thanks for the clarification. I didn’t know about the BZ.
