### ISSUE TITLE
Securitrons and ED-209's dont auto-patrol or respond to start patrol

### ISSUE THREAD

**Issue by OzfurAtlas** [tgstation/tgstation#65986]
## Round ID:

[Round ID]: 
(its been going for atleast since 3/4/2022)

Whats wrong?:
Basically as of late all securitrons and ED-209s havent been patroling the station at all, even after theyve been told to patrol through the PDA and tablet. This is not only with the round start bots but also ones that are made during the round. 
This isnt just for a specific round but it seems to be happening on all rounds as of late.
If the code for security bot patrols has been disabled and i just havent seen it that could explain this.

**Comment by JohnFulpWillard** [comment]
@AnturK Not sure if any of your recent pathfinding changes may have changed anything about this?
