### ISSUE TITLE
diagonal interaction for computers and machines not working

### ISSUE THREAD

**Issue by Mechanelize** [tgstation/tgstation#65989]
Reporting client version: 514.1569

## Round ID:
[181156](https://scrubby.melonmesa.com/round/181156)

## Testmerges:
- [Refactor and improve antimagic to be more robust](https://www.github.com/tgstation/tgstation/pull/64124)
- [Biddle Verbs: Queues the Most Expensive Verbs for the Next Tick if the Server Is Overloaded](https://www.github.com/tgstation/tgstation/pull/65589)

## Reproduction:

attempt to interaction with a computer/machine (autolathe, disposal unit, vending machine, etc.) while on a tile diagonal from it
you cant interact with it (but you can hit it with stuff)

**Comment by OzfurAtlas** [comment]
Might be just for icebox, but we will see next round.

**Comment by OzfurAtlas** [comment]
> Might be just for icebox, but we will see next round.
seems to be all maps

**Comment by LemonInTheDark** [comment]
Resolved by #65998

**Comment by Mechanelize** [comment]
thanks

**Comment by OzfurAtlas** [comment]
> Resolved by #65998

unless it hasnt been merged, it isnt fixed as of yet.

**Comment by LemonInTheDark** [comment]
It likely hasn't updated on your server yet, is it still borked?
