### ISSUE TITLE
Hellgun Fire Kit single pack doesn't appear on the cargo shuttle when confirmed.

### ISSUE THREAD

**Issue by vengeful910month3** [tgstation/tgstation#65999]
## Round ID: 
[19643](https://scrubby.melonmesa.com/round/19643)

## Reproduction:
Go to the supply console requests in cargo and buy a hellgun fire kit single pack in the goodies section. Wait until a cargo technician accepts your request. Wait for the cargo shuttle to come. and there is no hellgun fire kit single pack.

**Comment by TheBonded** [comment]
did you make sure you had enough credits in your personal account to afford this? is it possible the AI or someone else could have canceled the order before calling the shuttle?

**Comment by JohnFulpWillard** [comment]
I can't see the round ID, apparently never happened yet?

**Comment by TheBonded** [comment]
probably happened on a downstream that doesnt have the "report a bug" button go to their github

**Comment by Sealed101** [comment]
related #67383
the fix was https://github.com/tgstation/tgstation/pull/70572
needs checking though

**Comment by projectkepler-ru** [comment]
N/A

**Comment by Sealed101** [comment]
fixed by https://github.com/tgstation/tgstation/pull/70572 apparently
