### ISSUE TITLE
Skillsoft Stations Don't Let You Enter/Cannot Be Used

### ISSUE THREAD

**Issue by realroyalderg** [tgstation/tgstation#66002]
Reporting client version: 514.1583

## Round ID:
181164

## Testmerges:
- [firelocks now automatically open once the alarms are cleared and fixed fire alarms not clearing](https://www.github.com/tgstation/tgstation/pull/65490)

## Reproduction:
Go to a skill soft station
Realize you cannot enter it standing up
Attempt to enter it laying down
Stand up
Realize you cannot enter or use the skillsoft station without someone putting you in it
Have someone put you in it while you are standing up
Realize you cannot enter the skillsoft station while standing up
Lay down
Have them close the skillsoft machine
Stand up
Realize you or they cannot activate/implant the skill chip into you

**Comment by capsaicinz** [comment]
this seems like it was fixed-- works fine on my end.

**Comment by robbertapir** [comment]
failed to reproducd

**Comment by Sealed101** [comment]
no idea how and what caused this to be an issue for you - but either there was something missing in your steps or we've been trolled

can't repro, works just fine
