### ISSUE TITLE
Tram AI Teleporter Room Lacking A Shutter Button

### ISSUE THREAD

**Issue by realroyalderg** [tgstation/tgstation#66009]
Reporting client version: 514.1583

## Round ID:
[181171](https://scrubby.melonmesa.com/round/181171)

## Testmerges:
- [firelocks now automatically open once the alarms are cleared and fixed fire alarms not clearing](https://www.github.com/tgstation/tgstation/pull/65490)

## Reproduction:
Look at this photo, its in the AI sat to the left, there is no button to open the shutter meaning you cannot for example drag the AI's core through there. 
![tram missing button](https://user-images.githubusercontent.com/101699364/161992093-5e47027f-1d56-4d5b-a649-c3410b8778a4.PNG)

**Comment by unit0016** [comment]
> there is no button to open the shutter meaning you cannot for example drag the AI's core through there.

Gamer AI tip until this is fixed: Turn off equipment power on the APC and crowbar the shutters open. Crude but it works.
