### ISSUE TITLE
Note from Sloth in the lavaland ruin is blank

### ISSUE THREAD

**Issue by YAllanonY** [tgstation/tgstation#66025]
Reporting client version: 514.1575

## Round ID:
[181194](https://scrubby.melonmesa.com/round/181194)

## Testmerges:
- [firelocks now automatically open once the alarms are cleared and fixed fire alarms not clearing](https://www.github.com/tgstation/tgstation/pull/65490)

## Reproduction:

 It's just the note from Sloth in the lavaland ruin, if it shows up you can just click it to see that the note is blank

![image](https://user-images.githubusercontent.com/26759940/162098401-ec0521af-5d8e-4251-9ccf-70e4d52d8897.png)

**Comment by realroyalderg** [comment]
Funnily enough this is on point for sloth

**Comment by YakumoChen** [comment]
it's on the examine text, not the paper itself
