### ISSUE TITLE
Krokodil transformation not displaying a proper icon

### ISSUE THREAD

**Issue by lnGoror** [tgstation/tgstation#66066]
Reporting client version: 514.1566

## Round ID:
[181273](https://scrubby.melonmesa.com/round/181273)

## Reproduction:
After creating a sufficiently impure krokodil (test dose was at around 58% purity) and ingesting, the recipient receives the usual transofrmation promp "Your skin falls off easily!", but does not receive the 50 brute damage. After the transofmation the users icon stays the same (looks human). Brief conversation with ExcessiveUseOfCobby revealed that the recipient gets all the zombie parts, they just keep looking human. 

This issue is semi-consistent, as it does seem to appear during most rounds, but I managed to properly turn into a zombie like 3 days ago.

**Comment by Kapu1178** [comment]
Not a bug, this actually incredibly deliberate.

![image](https://user-images.githubusercontent.com/75460809/162554458-c806eda2-1945-4d54-840b-f7d35374ece5.png)

**Comment by ATH1909** [comment]
*why* is this deliberate?

**Comment by lnGoror** [comment]
I would too like to know if this is a permanent decision and if so, why was it made? Gameplay-wise I never encountered a situation where looking like a zombie broke the flow of a game. Since purity was introduced this transformation has become rather obscure and only a few people know about it (in my experience ingame). If the problem is in transforming other people into zombies, might I suggest instead setting the addiction threshold much higher. If this breaks something in the code, I would like to know if this is a temporary patch, or a permanent solution. Thank you.

**Comment by Kapu1178** [comment]
> I would too like to know if this is a permanent decision and if so, why was it made? Gameplay-wise I never encountered a situation where looking like a zombie broke the flow of a game. Since purity was introduced this transformation has become rather obscure and only a few people know about it (in my experience ingame). If the problem is in transforming other people into zombies, might I suggest instead setting the addiction threshold much higher. If this breaks something in the code, I would like to know if this is a temporary patch, or a permanent solution. Thank you.

was more so an oversight in conflicting design that i just didnt realise. someone's free to fix it.

**Comment by lnGoror** [comment]
I also noticed this interaction turns other races seemingly human when becoming krokodil addicts.
