### ISSUE TITLE
under certain circumstances, the blood demons on lavaland can leave a permanent beam

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#66062]
## Testmerges:
The following pull requests are currently test merged:
[#65490: 'firelocks now automatically open once the alarms are cleared and fixed fire alarms not clearing' by MacBlaze1 at commit 1d1ef331e0](https://www.github.com/tgstation/tgstation/pull/65490)

## Reproduction:
https://puu.sh/ITvlD/91b8bdc5f3.png
the heirophant killed one of these things mid beam
the beam stayed there the entire round, continuously damaging shit that stands in it

**Comment by TheBonded** [comment]
going to add the Needs Reproducing tag until someone manages to reproduce this so we know it's not a one time fluke

**Comment by YakumoChen** [comment]
actually I can confirm this happened in a round downstream

**Comment by TheBonded** [comment]
so if the creature dies while charging/firing the beam, the beam doesnt go away?

**Comment by YakumoChen** [comment]
I didn't see what actually triggered the demon to attack heiro or get killed but I saw the standalone beam when visiting the arena. I assume its the same thing.
