### ISSUE TITLE
Spray Tan overdose doesn't work

### ISSUE THREAD

**Issue by ModDownloading** [tgstation/tgstation#66089]
## Reproduction:

1. Drink or spray on 15u or more of Spray Tan.
2. Notice that you don't turn orange.

I think the addiction/overdose refactor from several months ago (maybe a year ago now) broke this. It probably just needs to get updated with the new code.

EDIT: A 30u patch DID overdose me, but as a lizard it only changed the color of my tail to orange and not the rest of my body, which still seems like a bug.

**Comment by ATH1909** [comment]
spray tan's metab rate is VERY high, you might not have injected it fast enough

**Comment by dnworden** [comment]
I'll try that sometime, I chugged 30 units of the stuff out of a beaker and that apparently wasn't fast enough, but maybe it's instantaneous.

**Comment by ModDownloading** [comment]
Ok, I tried it, 30u pill didn't overdose me, 30u patch applied right afterwards DID overdose me, but as a lizard it only changed my tail color and not the color of the rest of my scales, I'll update the original post with the issue.
