### ISSUE TITLE
ERROR masks in the botanist wardrobe on Delta

### ISSUE THREAD

**Issue by datorangebottle** [tgstation/tgstation#66081]
Reporting client version: 514.1566

## Round ID:
[181309](https://scrubby.melonmesa.com/round/181309)

## Testmerges:
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)
- [Arconomy: The bigger balance PR (REVISED EDITION)](https://www.github.com/tgstation/tgstation/pull/65795)
- [Biddle Verbs: Queues the Most Expensive Verbs for the Next Tick if the Server Is Overloaded](https://www.github.com/tgstation/tgstation/pull/65589)

## Reproduction:
Go to the maint room behind hydroponics on Delta. Open the locker. Learn that MSO forgot to install CS:Source.
![image](https://user-images.githubusercontent.com/46474741/162562420-5792d041-4702-493a-810b-3c9ba56131e5.png)

**Comment by timothymtorres** [comment]
Looks like this may be related to #65760
