### ISSUE TITLE
Upgraded resonators can summons "Mob Spawners" from legions.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#66096]
## Round ID:

[181321](https://scrubby.melonmesa.com/round/181321)

## Testmerges:

[#66074: 'An error occurred with this API request' by An error occurred with this API request at commit 44047246e1](https://www.github.com/tgstation/tgstation/pull/66074)

## Reproduction:

Attack a legion with an upgraded resonator on matrix mode, it'll spawn a LOT of mob spawners, humans without chests and human torsos.
![imagem](https://user-images.githubusercontent.com/4581352/162591667-a5e896ec-08af-4694-8657-f09ffe982d9c.png)

**Comment by timothymtorres** [comment]
This is either a bug from https://github.com/tgstation/tgstation/pull/65297 or from https://github.com/tgstation/tgstation/pull/56293

**Comment by robbertapir** [comment]
The humans this summons lack chests.
![Chestless](https://user-images.githubusercontent.com/102324362/162619082-bc1256ba-dafc-4613-a93d-c7349223c5fc.PNG)
