### ISSUE TITLE
Buckling a mob to a bench results in "ERROR" over the mob

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#66108]
Reporting client version: 514.1581

## Round ID:
[181351](https://scrubby.melonmesa.com/round/181351)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)

## Reproduction:

Buckling a mob to a bench, specifically obj/structure/chair/sofa/bench results in a flashing red "ERROR" overlay on top of the buckled mob.

**Comment by timothymtorres** [comment]
I suspect this is an issue with GAGs combined with overlays that came from #62169.  Looking through the code the culprit might be the armrest mutable overlay not playing nice with GAGs.
