### ISSUE TITLE
Airlock Helpers not initializing correctly onboard shuttles or midround-placed map templates

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#66102]
Reporting client version: 514.1583

## Round ID:
[181344](https://scrubby.melonmesa.com/round/181344)

## Testmerges:
- [An error occurred with this API request](https://www.github.com/tgstation/tgstation/pull/66074)

## Reproduction:
See title. Works for any shuttle or map template if they have a airlock mapping helper. ?????????
These DO have to be loaded in midround and not at mapload
![image](https://user-images.githubusercontent.com/50649185/162595888-6cc5968d-a0c8-421e-a8c7-aaaf92daab11.png)

(Easiest way I found to test this locally is either summoning one of the pirate ships or summoning the SBC starfury, because. yea.)

**Comment by unit0016** [comment]
Now that I get a good look at it, name helpers've broken completely too. What the hell's going on?

**Comment by dragomagol** [comment]
Aughhhh I think I know what caused this but not why.
