### ISSUE TITLE
All vendors except shuttle med dispensers are empty roundstart

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#66118]
## Round ID:
[181375](https://scrubby.melonmesa.com/round/181375) & 181379 

## Testmerges:
 Optimizes Runechat #65791 
 **Rebalanced Power consumption, increase for machines** #66059 (main culprit when discussed OOC)

## Reproduction:

- What a beautiful day on /tg/ station Terry Lag Free EU Punjabi 360p HD Download
- All vendors on the station are empty

**Comment by Ghilker** [comment]
the issue is that vendors can't handle one too many refresh parts call otherwise their content will empty out
