### ISSUE TITLE
AI cannot create newscaster channels

### ISSUE THREAD

**Issue by lnGoror** [tgstation/tgstation#66129]
Reporting client version: 514.1566

## Round ID:
[181407](https://scrubby.melonmesa.com/round/181407)

## Reproduction:
Plain and simple, AI can interact with the newscaster and can freely use channels created by other people, but cannot create one themselves. This issue is present since the new newscaster sprite and I am only reporting this now cause I miss taking photos and sharing them around.

**Comment by lnGoror** [comment]
I would like to add that cyborgs are also unable to create new channels. Their interactions with newscasters seem to be of the same nature as an AI. (don't know if there is any difference between the two code-wise, so just reporting for a good measure.)

**Comment by timothymtorres** [comment]
Duplicate of #66129
