### ISSUE TITLE
Constructs don't have their action buttons

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#66120]
Reporting client version: 514.1582

## Round ID:
[181382](https://scrubby.melonmesa.com/round/181382)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)

## Reproduction:
As a Wraith, Juggernaut, or Artificer, your action buttons are simply not there. They will reappear if you press Alt-Click on the "button palette".
![image](https://user-images.githubusercontent.com/42555530/162629163-35d8dc53-f0e0-4463-9c55-15a0eb126a39.png)

Most likely related to #65180

**Comment by DragonTrance** [comment]
Can confirm this, I was a harvester last night and didn't get any actions when I became one.

**Comment by LemonInTheDark** [comment]
The fuck
