### ISSUE TITLE
Ant dupe as janiborg

### ISSUE THREAD

**Issue by SmArtKar** [tgstation/tgstation#66131]
## Testmerges:
[#65795: 'Arconomy: The bigger balance PR (REVISED EDITION)' by ArcaneMusic at commit d55f3570be](https://www.github.com/tgstation/tgstation/pull/65795)
[#65997: 'Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)' by Mothblocks at commit 0492fcd3d5](https://www.github.com/tgstation/tgstation/pull/65997)

## Reproduction:

Be a janiborg
Scoop up some ants with your bucket
Start cleaning the floors
Notice a huge trail of FULL ANT HILLS behind you
Realise that potato had a moment and for some reason, janiborg's turf exposure code relays the amount of reagents in the bucket instead of a small portion that's being used per turf.

Credits to MooCow12 for finding this one

**Comment by moocowswag** [comment]
https://youtu.be/KYbYgXm16AM

**Comment by TemporalOroboros** [comment]
https://github.com/tgstation/tgstation/blob/0e805709e07e5206e5461773450fc823bbf6a87a/code/modules/mob/living/silicon/robot/robot_model.dm#L550
I am about 90% certain that this is a multiplier, not the volume of the reagents that the floor should be exposed to.

**Comment by moocowswag** [comment]
It was making alot more than just duping full amount of what was in the bucket, i started with 9 u ants and instantly made full anthills that took 2 or 3 entire full scoops of a bucket to scoop a single tile (so over 100u ON EACH TILE across multiple tiles with only 9u in the bucket)

**Comment by LemonInTheDark** [comment]
~~you don't say~~

**Comment by TheBonded** [comment]
does this also mean if they fill their bucket with acid and attack people with the mop itll dump the full bucket worth of acid on them?
