### ISSUE TITLE
Incinerator access console on meta station is uncloseable as an AI

### ISSUE THREAD

**Issue by lnGoror** [tgstation/tgstation#66130]
Reporting client version: 514.1566

## Round ID:
[181407](https://scrubby.melonmesa.com/round/181407)

## Testmerges:
- [Hud Image Culling By Z Level: Theft edition](https://www.github.com/tgstation/tgstation/pull/65189)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Rebalanced Power consumption, increase for machines](https://www.github.com/tgstation/tgstation/pull/66059)

## Reproduction:
Metastation science toxins incinerator access console keeps reopening after closing the window. This is apparently for AI only (crew didn't seem to have this issue). Talk with another AI player after the round concluded revealed that they know about the issue.

**Comment by TheBonded** [comment]
seems like this isnt to do with mapping and more what the consoles do as a whole
