### ISSUE TITLE
Cleaning "strange object" creates infinite used cleaning grenades 

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#66143]
## Reproduction:

Getting a strange object that spawns a cleaning foam creates a used cleaning grenade. 

```
/obj/item/relic/proc/clean(mob/user)
	playsound(src, SFX_SPARKS, rand(25,50), TRUE, SHORT_RANGE_SOUND_EXTRARANGE)
	var/obj/item/grenade/chem_grenade/cleaner/CL = new/obj/item/grenade/chem_grenade/cleaner(get_turf(user))
	CL.detonate()
```

This is becuase it literally creates a grenade and uses it, which are no longer consumed. 
This means you can generate a grenade + two beakers out of thin air infinitely.

**Comment by ATH1909** [comment]
amazing
