### ISSUE TITLE
Russian Revolver is not working

### ISSUE THREAD

**Issue by GolfinhoVoador** [tgstation/tgstation#66142]
## Reproduction:
Step 1: Load a russian revolver with 6 bullets and spin the chamber.
Step 2: Shoot yourself.
Expected result: You get shot...
Result: The revolver does not shoot.

**Comment by GolfinhoVoador** [comment]
I removed the testmerges since its happening on an outdated server of mine and in tgstation

**Comment by MrMelbert** [comment]
Caused by #65473 it seems
@cacogen ?

**Comment by GolfinhoVoador** [comment]
#66154 hopefully fixes it

**Comment by interestingusernam3** [comment]
It fixes it I tested it.
