### ISSUE TITLE
Trying to shoot a monkey with russian revolver makes it aggro

### ISSUE THREAD

**Issue by robbertapir** [tgstation/tgstation#66152]
## Round ID:
private server

## Testmerges:
n/a

## Reproduction:
1. Click a monkey with russian revolver
2. "A mechanism prevents you from shooting anyone but yourself!"
3. Monkey attacks you despite not being harmed by this

**Comment by TheBonded** [comment]
to be fair id be pretty pissed if you pointed a gun at me too

**Comment by robbertapir** [comment]
It also happens when you shoot an empty revolver of any kind at a monkey. If you do this to a cleanbot it will sparkle. If you do this to a beepsky he will sparkle and arrest you.
