### ISSUE TITLE
New Cryo Sleepmix Bug

### ISSUE THREAD

**Issue by RikuTheKiller** [tgstation/tgstation#66151]
## Reproduction:
Step 1: Upgrade the freezer connected to any of the new cryogenic systems.
Step 2: Cool the gas to extremely low temperatures.
Step 3: Realize the gas shrinks down so much that it no longer provides sleep, eliminating the "cooler = better" aspect of cryoxadone.
Step 4: Accidentally kill your patient because they're just getting burned by the cold temperatures and not healed.
Step 5: Realize cryo is kind of shit now.

Personal Opinion:
I like the idea of gasses being used, but also, internals should bypass it (If they don't already, plasmamen don't breathe oxygen.) and also adding a pressure option to the cryotubes to forcefully change the amount of pressure regardless of the moles/pressure/temperature in the tubing, kind of like an internal pump of sorts. (This could even be upgraded with a better matter bin to allow for higher pressures to be set like with temperature on freezers when upgrading their lasers.)

**Comment by WarlockD** [comment]
I think its more about how your supposed to go "cold" but not "cold where your body will shatter once it falls out"  I mean if your body is at 3K, your a popsicle, Maybe a safty system that lets you set the temp depending on the percent?  Like lizard's hate cryo but they are convenient.

**Comment by Sealed101** [comment]
not really an issue even with t4 parts currently. there's enough moles in the roundstart supply to make enough pressure for the mix and even if enough of it is consumed, i don't think it's too much of a problem to request more juice from cargo/atmos (let ghilker have this one it's a sound design choice)
