### ISSUE TITLE
Bone Construction Book Bugs Crafting Menu

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#66199]
Reporting client version: 514.1583

## Round ID:
[181610](https://scrubby.melonmesa.com/round/181610)

## Testmerges:
- [Super Thief Health Update: Disables Hoarder, Adds All Access Fan, Rarely Thief Guilds in Maint ](https://www.github.com/tgstation/tgstation/pull/66123)

## Reproduction:
Find and read "The Complete Works of Lavaland Bone Architecture"
You'll now have TWO tribal crafting menu buttons.
One of them allows you to craft the recipes. The other lists the recipes, but you can't actually craft them.
![image](https://user-images.githubusercontent.com/44104681/163486359-89342900-074a-4eb6-8952-d346336ed88f.png)
![image](https://user-images.githubusercontent.com/44104681/163486396-ba329390-480c-436c-b8b9-1c3d7e884c39.png)

**Comment by robbertapir** [comment]
Actually the bottom menu allows you to craft the Collosal Rib and nothing else, while the top menu allows you to craft everything except the Collosal Rib.
