### ISSUE TITLE
Items in Suit Storage Turning Invisible

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#66197]
Reporting client version: 514.1583

## Round ID:
[181605](https://scrubby.melonmesa.com/round/181605)

## Testmerges:
- [Super Thief Health Update: Disables Hoarder, Adds All Access Fan, Rarely Thief Guilds in Maint ](https://www.github.com/tgstation/tgstation/pull/66123)

## Reproduction:
Wear something with suit storage.
Put something it can hold into the suit storage.
It MAY or may not turn invisible, and you won't be able to click it.

I've noticed this while wearing a chaplain follower hoodie (put bible into storage) and the explorer suit (put large blue oxy tank into storage). I'm pretty sure this is the same thing happening in #65652, but I wanted to make sure we were aware it's a much broader issue than just aprons.

**Comment by Potato-Masher** [comment]
I've noticed this too with a few different things, mostly with putting disablers into suit storage on armor. Only does it sometimes though, which is the weird part.

**Comment by VladinXXV** [comment]
Not fixed.
![image](https://user-images.githubusercontent.com/44104681/168495649-3682bf73-f38c-4700-b10d-d31e47b09d21.png)
![image](https://user-images.githubusercontent.com/44104681/168495654-d2a6584e-fb37-495d-91ba-8f5e4c373ce7.png)
