### ISSUE TITLE
Duplicating robotic head after augmentation

### ISSUE THREAD

**Issue by B4CKU** [tgstation/tgstation#66231]
## Round ID:
tested locally on the currently latest  tgcode

## Testmerges:
none, see above

## Reproduction:

i've turned myself into a slimeperson, split into two, then after augmenting my entire body, i realised that the head has duplicated, being both on the augmented body and dropped on the ground

![image](https://user-images.githubusercontent.com/50628162/163682262-41345ae6-5639-41cc-9f50-b4a64bbe8ccb.png)

also i'm pretty sure that robotic heads shouldn't have the bloody eyes overlay, but that's probably a completely different issue, one that also applies to freshly printed cyborg heads

![image](https://user-images.githubusercontent.com/50628162/163682070-961371ea-2549-4416-9a63-5655708b777d.png)

probably related to the recent limbs refactor, i guess

**Comment by B4CKU** [comment]
i've also tried carving out the insides of the heads on the ground, but they don't seem to have anything inside

![image](https://user-images.githubusercontent.com/50628162/163682402-8413eea9-86d0-4470-99ab-99bb2b5b034c.png)

**Comment by nianjiilical** [comment]
so it turns out this bug is even funnier than just a duplicated head

because if you augment person A to create a dupe robot head, then use that head to augment person B, B's name/face changes to A's, and they become damage linked as if they were holoparas, making one die after a delay if the other is killed

**Comment by Sealed101** [comment]
can't replicate anymore, i think ghost organs after surgeries were mostly fixed.
