### ISSUE TITLE
Book binder is messing up formatting

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#66234]
Reporting client version: 514.1583

## Round ID:
[181704](https://scrubby.melonmesa.com/round/181704)

## Testmerges:
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)

## Reproduction:

Write on a piece of paper. Finish the paper. Insert into book binder. The book you get will display all the formatting spans (not present in the paper). I tried with both a crayon and a pen, both got screwed up.

**Comment by timothymtorres** [comment]
Does the spans look like #66254? If so then this is a dupe.

**Comment by SuperNovaa41** [comment]
those two issues are absolutely not a dupe what are you talking about

**Comment by timothymtorres** [comment]
> The book you get will display all the formatting spans

The launch sequence span was displayed due to `say` vs `auidbile_message`.  I wonder if there is a similar proc being used that isn't formatting the span correctly for books.

**Comment by TetrakoHateThis** [comment]
This issue is still present.

**Comment by tf-4** [comment]
broke in https://github.com/tgstation/tgstation/pull/65326

**Comment by timothymtorres** [comment]
Tagging @LemonInTheDark since it's from his PR

**Comment by wesoda25** [comment]
Been a long 4 months :(

**Comment by LemonInTheDark** [comment]
ok yeah gimme a bit

**Comment by LemonInTheDark** [comment]
Not actually my fault at least anymore, tho it is stupid.
Paper stores formatting in raw markdown now, because storing the parsed script was leading to stupid.
The PROBLEM is it prints the raw markdown too. We need to get off our collective ass and unify paper rendering.
![image](https://user-images.githubusercontent.com/58055496/203258798-f8ed8a9c-a282-4ff0-934b-46806767e6dc.png)

**Comment by wesoda25** [comment]
might take a look into that

**Comment by JohnFulpWillard** [comment]
@wesoda25

**Comment by wesoda25** [comment]
Yeah I looked haven't a clue how to go about it, sorry.

**Comment by timothymtorres** [comment]
The sad thing about this is that all the old books still have their markdown and pen colors intact.  Any new books that someone tries to make however will not.

**Comment by JohnFulpWillard** [comment]
Newscasters also seem to upload them fine, the problem is limited to books.

**Comment by VladinXXV** [comment]
wtf guys i just spent like 4 hours writing a book only to discover this 😢

**Comment by JohnFulpWillard** [comment]
> wtf guys i just spent like 4 hours writing a book only to discover this 😢

me too man me too

**Comment by SylvetteSylph** [comment]
I will literally pay a hundred hard-earned American dollars to whoever fixes book binders please god. I have been suffering for almost a year now.

**Comment by timothymtorres** [comment]
I would be willing to tackle this for the bounty.  DM me on discord my username is TimT

**Comment by SylvetteSylph** [comment]
This was fixed in #74902.

**Comment by wesoda25** [comment]
lets fucking go hell yeah (not fact checking that)
