### ISSUE TITLE
When processing a sausage if you don't select an option it runtimes

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#66256]
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
Spawn a knife, spawn a sausage, hold the knife, open the radial menu to pick which result, then walk away or click the x 

[09:31:21] Runtime in atoms.dm, line 1452: bad index
proc name: StartProcessingAtom (/atom/proc/StartProcessingAtom)

**Comment by SuperNovaa41** [comment]
Can't reproduce

**Comment by SuperNovaa41** [comment]
Closed by https://github.com/tgstation/tgstation/pull/66382
