### ISSUE TITLE
"<span class='danger'>Launch sequence activated! Prepare for drop!!</span>"

### ISSUE THREAD

**Issue by B4CKU** [tgstation/tgstation#66254]
## Round ID:

local server running on the latest tgcode

## Testmerges:

none

## Reproduction:

![image](https://user-images.githubusercontent.com/50628162/163719470-6562b94b-1e8e-49ae-8932-0c07cefcc5c3.png)

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/17edd5300c7136d471519dc0f4a662563ee5afbf/code/modules/mining/aux_base.dm#L133-L147
