### ISSUE TITLE
Scrapheap Escape Shuttle never spawned (Kilostation)

### ISSUE THREAD

**Issue by Fastmapler** [tgstation/tgstation#66277]
## Round ID:

[181772](https://scrubby.melonmesa.com/round/181772)

## Testmerges:

#66220 

## Reproduction:

For some unknown reason, the Scrapheap Challenge escape shuttle never arrived to departures. When the shuttle "arrived", the announcement still occurred, and the countdown for departure and its supposed arrival to centcom still occured. I am unsure if the shuttle simply did not appear at departures or just didn't spawn. Furthermore, some specific things happened with shuttle selection:

1. Monastery shuttle was either bought or randomly rolled from shuttle insurance event, unsure as I was SSD
2. Insurance rolled and replaced Monastery with scrapheap

I arrived at departures right after the shuttle arrived, so I highly doubt someone managed to disassemble the whole thing before I got there.

**Comment by Fastmapler** [comment]
Here is a better step by step guide to reproduce it:

1. Emag a comms console and purchase the monastery shuttle
2. Force a Shuttle Catastrophe event to change the shuttle to something else
3. Call the shuttle and wait for it to arrive

Images:

Departures right when shuttle arrived (In this case the shuttle catastrophe event rolled delta escape shuttle)
![image](https://user-images.githubusercontent.com/22627974/163869850-1479adad-0673-4c89-8cf9-736b486ed259.png)

It arrived to Centcom on round end, but for some strange reason it had a large amount of strange junk in it:
![image](https://user-images.githubusercontent.com/22627974/163870145-7609bd76-f636-443c-9cfc-5f1941857936.png)

**Comment by TheBonded** [comment]
>strange junk

thats the janicart... does the monestary shuttle permanently change the docking location to on-station, causing any forced shuttle replacement to crash land in the middle of the station when docking? the janitors closet is very close to departures on kilo...

**Comment by GoblinBackwards** [comment]
same issue as https://github.com/tgstation/tgstation/issues/65515

**Comment by TheBonded** [comment]
which means this is a duplicate issue
