### ISSUE TITLE
If the escape shuttle docks in empty space it does not count as escaped

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#66347]
## Testmerges:
The following pull requests are currently test merged:
[#66220: 'Add button to relaunch the game alongside reconnect when you lose connection' by Mothblocks at commit 99bf4a0cd5](https://www.github.com/tgstation/tgstation/pull/66220)

## Reproduction:
https://puu.sh/IVOCb/7de5bfdcb1.png
I was standing here and I red texted this is horse shit I'm going to report you to the police

**Comment by Son-of-Space** [comment]
Looking at the area for the raven cruiser, it's the same area as the rest of the shuttles (default area/shuttle/escape) so the area is not acting differently for the purposes of being captured. Were you restrained in any way when the round ended (such as being in the body bag, being in cuffs, being pulled by someone, etc.?) This is likely not a mapping issue.

**Comment by newfren** [comment]
no, but the shuttle was hijacked during the time when hijacking took you to empty space instead of a syndicate base

**Comment by Son-of-Space** [comment]
Looks like it is probably an error with how the game handled ending the game in empty space as a traitor, then. Likely not a mapping issue.

**Comment by Son-of-Space** [comment]
@newfren can you change the name of this issue to properly reflect what is being incorrectly handled?

**Comment by Sadboysuss** [comment]
doesn't seem to be an issue anymore
