### ISSUE TITLE
Ripley equipment utility count oversight

### ISSUE THREAD

**Issue by iwishforducks** [tgstation/tgstation#66357]
https://github.com/tgstation/tgstation/pull/65375

This PR introduced categorical slots for each mecha (utility, weaponry, etc.) and gave each mech a fitting max of two slots for respective modules, one for each hand. However, this introduced a new equipment item, the Cargo Compartment, which eats up one of the two utility slots on the Ripley.

This means Ripleys only have an effective utility slot of 1, which seems like an oversight considering that they're **the** utility mech.

**Comment by MTandi** [comment]
Ripley has 3 utility slots other than cargo compartment, so I believe we can say that this issue is irrelevant.
