### ISSUE TITLE
Tablet ID is "used" read after in hand ID.

### ISSUE THREAD

**Issue by Nabski89** [tgstation/tgstation#66360]
Part of https://github.com/tgstation/tgstation/pull/65755
## Reproduction:

Put the spare in your tablet.
Have another random ID in your hand.
Try to log into the communications console.
Fail.
Put the other ID in your hand in the bag.
Log in.
It works.

Not even sure if this is really a bug or just a functionality change.

**Comment by TheBonded** [comment]
>logging in prioritizes the ID in your hand over the ID in your tablet

all machines that require IDs prioritize the ID in your hand over the ID in your ID slot. This includes vending machines, any console you have to log in to, and anything else of the sort
