### ISSUE TITLE
Breath mask sticks out of plasmaman helmet

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#66366]
Reporting client version: 514.1582

## Round ID:
[181923](https://scrubby.melonmesa.com/round/181923)

## Testmerges:
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/164352549-09bfd789-f00f-43e1-90a8-dcf2f5f5a436.png)

**Comment by Serxule** [comment]
this is a problem with most things, not just plasmaman
