### ISSUE TITLE
the Oh Hi Mark got duplicated at centcom somehow

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#66379]
## Reproduction: 
![image](https://user-images.githubusercontent.com/30074002/164387962-1d3cf4da-596d-4148-8847-22857788b761.png)

idk but they did buy shuttle insurance for it if that helps

**Comment by TheBonded** [comment]
almost as if it duplicated and tried to dock with itself, so weird that it would be mirrored

**Comment by dragomagol** [comment]
I made this with build mode hahahahaha

**Comment by TheBonded** [comment]
> I made this with build mode hahahahaha

shouldve known, you forgot to add the display or pen in the paper bin, and your windoor is on the table instead of wall
