### ISSUE TITLE
Icebox Atmos has no vents or scrubbers

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#66370]
Reporting client version: 514.1582

## Round ID:
[181923](https://scrubby.melonmesa.com/round/181923)

## Testmerges:
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/164356813-8b5b7cb6-236b-4883-8a3b-6fbc34550b75.png)

**Comment by dragomagol** [comment]
The ones in the pump area are a separate area

**Comment by san7890** [comment]
This is probably non-trivial to fix- if you want to work on this issue, maybe these two spots would be good?

![image](https://user-images.githubusercontent.com/34697715/164357174-2ab7c270-cc55-4106-93ca-cde8d058ca9a.png)

Up to whoever takes this task.
