### ISSUE TITLE
Icebox mining bottom floor is missing an apc

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#66374]
I saw this last night and forgot to report it sorry.

There's an apc for the mining mech bay on the lowest floor of icebox mining but not one for the main area. The cables lead into maint and then point at a rack. As a result the area is magically powered.

**Comment by Zytolg** [comment]
The magic power comes from the area being shared by both mechbays in mining.

**Comment by newfren** [comment]
for the record, the mechbay isn't the magically powered one, the bottom floor main area is

**Comment by Son-of-Space** [comment]
This is actually because the APC on the middle floor is covering both the upper and lower section, as they are the same area. It isn't being magically powered.

**Comment by newfren** [comment]
For the record, and I appreciate you are fixing this: during the round in question the middle floor was unpowered while the bottom floor was powered.

**Comment by Son-of-Space** [comment]
![image](https://user-images.githubusercontent.com/63861499/164952134-cfa1d548-6399-4a77-aa54-8772fcd1b938.png)
