### ISSUE TITLE
SaturnX doesn't turn you invisible anymore, and ONLY turns your eyeballs invisible

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#66377]
Reporting client version: 514.1568

## Round ID:
[181927](https://scrubby.melonmesa.com/round/181927)

## Reproduction:

- Drink SaturnX. 
- Stay completely visible, defeating the entire point of the chemical
- Notice that your eyes are now transparent, and ONLY your eyes
- ![image](https://user-images.githubusercontent.com/51863163/164369073-1170b28d-04db-4d60-b893-7a5aea0b3109.png)

Likely caused by KapuLimbs.

**Comment by ArcaneDefence** [comment]
Fucking amazing.

**Comment by davethwave** [comment]
Indeed, honestly. If it wasn't so unnoticeable. That would be an amazing effect by it's own accord.

**Comment by Amrabol** [comment]
> Likely caused by KapuLimbs.

Most likely as i when i tried to make lead recipe for SaturnX i did not had the newest version of code and SaturnX worked normally with invisibility and that unique visual screen effect

**Comment by Amrabol** [comment]
I can't understand how exactly SaturnX is making someone invisible but i believe it this file that need to be fixed \code\modules\mob\living\carbon\human\species.dm .
Lines 538 and 669

**Comment by SmArtKar** [comment]
> I can't understand how exactly SaturnX is making someone invisible but i believe it this file that need to be fixed \code\modules\mob\living\carbon\human\species.dm . Lines 538 and 669

it changes their limbs texture to invisible one

**Comment by Amrabol** [comment]
Tried it on local and not gonna lie its really weird now. All races were losing eyes and clothes. Felinids were losing ear and tail too. Lizards were losing tail but no frail or anything. Moth were losing markings and their unique eyes. Any other race i did not mentioned just lost eyes. By losing i meant them becoming invisible

**Comment by timothymtorres** [comment]
You only become invisible when peoples eyes are closed.  Kind of like the weeping angels.

**Comment by JohnFulpWillard** [comment]
@Kapu1178

**Comment by Kapu1178** [comment]
ill crack at it tomorrow

**Comment by Kapu1178** [comment]
I had uh. An emotional week. I'll tackle this somepoint soon.

**Comment by Justice12354** [comment]
A few months later, I've realized it also makes you UNDERWEAR invisible. Oh my god. This surely does go against God and Nature...

**Comment by weesnaw-ops** [comment]
> I had uh. An emotional week. I'll tackle this somepoint soon.

you still gonna tackle this?

**Comment by weesnaw-ops** [comment]
@Kapu1178

**Comment by weesnaw-ops** [comment]
relevant code bounty: https://tgstation13.org/phpBB/viewtopic.php?f=5&t=32421&p=651614#p651614
