### ISSUE TITLE
Tablet doesn't set your name, the id inside does + mime tablet issues

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#66375]
Saw this last night and forgot to report it sorry

if you have your own tablet equipped but a different id and you're wearing a face obscuring mask, the name given to you is the one on the id, not the one on the tablet.

ALSO the mime tablet is given <either a random name or your character's default name, I was playing hardcore random and don't know> instead of your mime name, although the ID correctly has your mime name.

**Comment by TheBonded** [comment]
to be fair you could always examine someone to see the ID within the PDA before. still an issue that should be fixed

**Comment by JohnFulpWillard** [comment]
i mentioned this issue but my PR doesn't actually fix it mb

**Comment by JohnFulpWillard** [comment]
Mime issue was patched a while ago and I don't think we should disguise people as their PDAs, removes the point of the ID, so I'm closing this as not planned.
