### ISSUE TITLE
Titanium glass fulltile windows / Shuttle windows when crafted in hand are in a state of screwed in place but still movable

### ISSUE THREAD

**Issue by Ed640** [tgstation/tgstation#66387]
Reporting client version: 514.1583

## Reproduction:

Using Titanium glass in hand and using the crafting menu that comes up to make a shuttle window will create a full tile window that can move around but can't be screwed in since its considers itself finished and will only accept deconstruction steps.

![image](https://user-images.githubusercontent.com/16868239/164446138-aad98e7b-6ab2-4da8-b734-76896b7588b1.png)

**Comment by TheBonded** [comment]
I have no idea why they didnt have the `state = WINDOW_OUT_OF_FRAME`, someone should check to see what removed that
