### ISSUE TITLE
Shaking someone who is "PermaSleeping" will wake them up instantly 

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#66399]
## Reproduction:

- Inject someone with 10u healium. 
- They fall asleep.
- Shake them.
- They wake up, despite being "perma-slept". 
- When the healium exits their system, they are microslept for 1 second before getting up again.

**Comment by Sealed101** [comment]
`PermaSleeping()` somehow ended up as never being used anywhere now. calling it via VV reproduces the issue as described (minus the healium bits). do we need this proc even
https://github.com/tgstation/tgstation/pull/78657 and https://github.com/tgstation/tgstation/pull/77637
