### ISSUE TITLE
All Shuttle Displays will display the name of the current Evacuation Shuttle

### ISSUE THREAD

**Issue by Zytolg** [tgstation/tgstation#66394]
## Reproduction:

Any shuttle with an ETA display should do this. I tested this with the roundstart spawned NukeOps Shuttle. You have an AI display and an ETA display. The ETA display will display the "name" of the shuttle when inspected. The code for that is as follows: 

> /obj/machinery/status_display/proc/examine_shuttle(mob/user, obj/docking_port/mobile/shuttle)
> 	if (shuttle)
> 		var/modestr = shuttle.getModeStr()
> 		if (modestr)
> 			if (shuttle.timer)
> 				modestr = "<br>\t<tt>[modestr]: [shuttle.getTimerStr()]</tt>"
> 			else
> 				modestr = "<br>\t<tt>[modestr]</tt>"
> 		return "The display says:<br>\t<tt>[shuttle.name]</tt>[modestr]"
> 	else
> 		return "The display says:<br>\t<tt>Shuttle missing!</tt>"

This code makes it so that these displays only ever fetch values for the current emergency shuttle, making all other shuttles that want to do this sort of stuff for themselves tonight's biggest loosers.

**Comment by Sealed101** [comment]
ETA displays no longer display the name of a shuttle when examined as of #69153, not sure if intentional but oh well
