### ISSUE TITLE
Caves away mission has no atmos

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#66403]
## Round ID:
 [181968](https://scrubby.melonmesa.com/round/181968)

## Testmerges:

irrelevant

## Reproduction:

enter gateway
see that it looks like lavaland
die to low pressure + low temp
complain in deadchat.
![image_2022-04-21_174913386](https://user-images.githubusercontent.com/54422837/164557604-a948bd9b-f549-4ec6-9a1a-6a074664ddc3.png)
![image_2022-04-21_175637184](https://user-images.githubusercontent.com/54422837/164558492-d1b8e4d8-debc-4c0d-87a3-26f5c4dbeec2.png)

**Comment by ATH1909** [comment]
> this bug is ages old how has it not been reported until now 💀

it has been, but IIRC, the creator of this away mission said "fuck it, it's a feature"

**Comment by Zytolg** [comment]
it's getting remapped regardless. It'll just depend on whenever we get to it.
