### ISSUE TITLE
Split personality leaves the current controller as the owner of the body when it's cured

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#66400]
## Round ID:
Observed across a few rounds

## Reproduction:

- Gain a split personality
- It takes control of your body
- Be cured of your split personality syndrome while the other personality (not you) is in control
- You lose control of your own body permanently, and the split personality now owns it

"But that makes sense?"

It's not intended that split personality leaves the current controller as the owner of the body on cure as evidenced by this comment
```
/datum/brain_trauma/severe/split_personality/on_lose()
	if(current_controller != OWNER) //it would be funny to cure a guy only to be left with the other personality, but it seems too cruel
		switch_personalities(TRUE)
	QDEL_NULL(stranger_backseat)
	QDEL_NULL(owner_backseat)
	..()
```

**Comment by Sealed101** [comment]
fixed by #73579
base brain trauma's `Destroy()` calls `on_lose()` anyway so it should be fine and has seemingly been fine ever since that pr so uh yeah coolio
