### ISSUE TITLE
Health Analyzers not indicating if a damaged limb is prosthetic or not

### ISSUE THREAD

**Issue by MeteorCrush** [tgstation/tgstation#66401]
## Reproduction:

Either give yourself a Prosthetic Limb quirk, or find someone else who has a prosthetic limb. 

Apply damage to the prosthetic limb, such as brute damage from spacing the body temporarily with low pressure.

Check for damage with a Health Analyzer and you will see that nowhere does it mention which limb is prosthetic.

For example, if you have a prosthetic right arm, and you happen to have 20 brute damage on the right arm, the Health Analyzer will show that it is a "Right Arm" rather than a "Prosthetic Right Arm" (I actually can't remember the actual name. Might be Cybernetic Right Arm or Prosthetic Right Arm).

Without knowing that the limb is prosthetic, doctors will be puzzled by why their medicine is not healing their patient. The Health Analyzer used to indicate that damaged prosthetic limbs are prosthetic.

**Comment by TheBonded** [comment]
probably a result of kapulimbs. luckily examining the person still tells you what limbs are prosthetic
