### ISSUE TITLE
Return the paper scanning function on the tablet PDAs

### ISSUE THREAD

**Issue by GForceTF** [tgstation/tgstation#66402]
I like playing with blind quirk. The old PDAs allowed you to scan papers, and the paper's contents would be copied onto the note-keeping section of the PDA. It was the only way I could read the captain's spare ID papers.

**Comment by TheBonded** [comment]
you must be the only player who even knew that was a feature

**Comment by timothymtorres** [comment]
I bet @MrMelbert didn't know about this, hehehe.

**Comment by TheBonded** [comment]
> I bet @MrMelbert didn't know about this, hehehe.

honestly this is almost as obscure as the fact that you could scan photos to send them to people

**Comment by magatsuchi** [comment]
i will release a fix for this today

**Comment by B4CKU** [comment]
> > I bet @MrMelbert didn't know about this, hehehe.
> 
> honestly this is almost as obscure as the fact that you could scan photos to send them to people

you could WHAT

**Comment by timothymtorres** [comment]
Can you still PDA message a picture of your butt to the captain?

**Comment by magatsuchi** [comment]
> Can you still PDA message a picture of your butt to the captain?

yes

**Comment by TheBonded** [comment]
> > > I bet @MrMelbert didn't know about this, hehehe.
> > 
> > 
> > honestly this is almost as obscure as the fact that you could scan photos to send them to people
> 
> you could WHAT

@B4CKU click on PDA with photo, next PDA message you send will send the photo with it. worked with the send-to-all function.

**Comment by RandomGamer123** [comment]
Resolved by #66470 , can be closed
