### ISSUE TITLE
DeltaStation Airlock Ordnance Inconsistency

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#66410]
## Reproduction:

![image](https://user-images.githubusercontent.com/34697715/164569761-0d2ac019-2b39-4a4d-9d57-02297c22360a.png)

Did you know that every airlock on DeltaStation has two caution stripes under each airlock? I did not. Very well appreciated if someone could correct this design oversight and place the caution lines per the standard.

**Comment by Zytolg** [comment]
I'll do you one better bröther.
