### ISSUE TITLE
TGUI Is majorly fucked

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#66423]
Reporting client version: 514.1583

## Round ID:
[181984](https://scrubby.melonmesa.com/round/181984)

## Testmerges:
N/A

## Reproduction:
Step 1: Join Manuel.
Step 2: Behold.

When you open the game, there' a weird white square in the middle of the screen. I ASSUME it's the changelog, because it usually automatically opens when there are changes, and now it won't open at all. View crew manifest button doesn't seem to do anything. Same for character setup. Trying to latejoin gives you a blank window, which, if it loads, you see the job selection menu, but it's all whacked up. Pics included.

![image](https://user-images.githubusercontent.com/44104681/164767655-beae2298-c9c0-41c8-b95a-c2d6567be52b.png)
![image](https://user-images.githubusercontent.com/44104681/164767751-0f76f677-10b7-4a3b-9f49-b9d5d42f07c7.png)

**Comment by LemonInTheDark** [comment]
![image](https://user-images.githubusercontent.com/58055496/164768617-585f2ad0-20e3-470b-903b-3e0b412ff858.png)
tgui works on latest commit

**Comment by LemonInTheDark** [comment]
Host issue on manuel, admins pressed the funny cdn button, oughta be fixed now
