### ISSUE TITLE
Some chaplain music sect rites trigger their own chaplain's antimagic, causing repeated antimagic effects

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#66492]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/164998663-548814de-4f0c-4f17-a76b-052cdda034bd.png)

This chaplain was playing the "nullwave vibrato" and was causing almost constant antimagic effects on themselves.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/fe913b246617faae021accc67aeb8c842578f451/code/modules/religion/festival/instrument_rites.dm#L79-L85

@tralezab the `can_block_magic` proc is supposed to be used for one-shot spells.  It wasn't intended to be spammed.  However if you add an extra arg, something like `silent=FALSE`, you could fix this quite easily and turn off the text and appearance effects.  It would probably be a good idea to set `charge_cost=0` unless you are trying to drain antimagic.
