### ISSUE TITLE
Placing posters on a wall puts them on the floor

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#66504]
Reporting client version: 514.1582

## Round ID:
[182118](https://scrubby.melonmesa.com/round/182118)

## Testmerges:
- [Adds a discord bot command version of show-server-revision](https://www.github.com/tgstation/tgstation/pull/66338)
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)
- [Human Life Optimization: Citrus Flavored](https://www.github.com/tgstation/tgstation/pull/66037)
- [Adds MC initialization stages. Earlier stages can fire while later ones init. Fixes tgui chat reconnection banner showing during init.](https://www.github.com/tgstation/tgstation/pull/66473)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/165029842-0667c939-77c8-4bc4-9b09-8dec9132d3ec.png)

**Comment by msgerbs** [comment]
Placing like in game, or in the editor?

**Comment by dragomagol** [comment]
This was placing them in-game

**Comment by Mooshimi** [comment]
Unable to replicate

**Comment by msgerbs** [comment]
Hey @dragomagol did you by chance print this poster from a library console?

**Comment by dragomagol** [comment]
It honestly might be! I was helping a player out on the syndie listening base and it may have been with the book console?

**Comment by msgerbs** [comment]
Nope, that doesn't seem to be the case. Which means I found the bug!
