### ISSUE TITLE
Atmospheric Technician PDA is name/jobless

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#66515]
Reporting client version: 514.1583

## Round ID:
[182136](https://scrubby.melonmesa.com/round/182136)

## Testmerges:
- [fixes ethereal feeding breaking APC charging](https://www.github.com/tgstation/tgstation/pull/66490)

## Reproduction:
Join the game as an Atmos Tech.
Look at your PDA.

The atmos tech PDA starts off without a name or job in it's name, unlike others. You can't fix this by simply imprinting your ID. I needed to imprint someone else's ID first, then I could imprint mine.
![image](https://user-images.githubusercontent.com/44104681/165148043-a3ecac7e-1962-45d7-a860-518b947c0774.png)

**Comment by Ghilker** [comment]
![image](https://user-images.githubusercontent.com/42839747/165188045-867a091a-c219-4911-b797-c613ea2cbfc1.png)
