### ISSUE TITLE
All the xeno weeds disappeared 

### ISSUE THREAD

**Issue by itseasytosee** [tgstation/tgstation#66525]
## Testmerges:
The following pull requests are currently test merged:
[#66338: 'Adds a discord bot command version of show-server-revision' by MrStonedOne at commit 0516689a7d](https://www.github.com/tgstation/tgstation/pull/66338)
[#65997: 'Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)' by Mothblocks at commit cef54eeb19](https://www.github.com/tgstation/tgstation/pull/65997)
[#66037: 'Human Life Optimization: Citrus Flavored' by LemonInTheDark at commit 3816f23590](https://www.github.com/tgstation/tgstation/pull/66037)
[#66473: 'Adds MC initialization stages. Earlier stages can fire while later ones init. Fixes tgui chat reconnection banner showing during init.' by MrStonedOne at commit c6d247c853](https://www.github.com/tgstation/tgstation/pull/66473)

## Reproduction:
I was xeno queen, it happened three times that round. It seemed like they disappeared in batches with the ones placed first disappearing first. They just disappeared. It felt like it was maybe related to the eggs opening, or maybe decaying?

**Comment by Serxule** [comment]
its from heat

**Comment by itseasytosee** [comment]
> its from heat

It was in normal station atmosphere, dose it need to be colder?

**Comment by Serxule** [comment]
> > its from heat
> 
> It was in normal station atmosphere, dose it need to be colder?

did you check it with gas scan as a ghost? it may have just been slightly too hot but not enough to be noticeable, weeds are sensitive to heat

**Comment by itseasytosee** [comment]
It was ambient virology temperature, there was even a little breach earlier so that should have made it colder.

**Comment by TheBonded** [comment]
> It was ambient virology temperature, there was even a little breach earlier so that should have made it colder.

could have been a BZ leak perhaps? I know they destroy webs, wouldnt be surprised if they did the same to weeds

**Comment by davethwave** [comment]
Viro has it's own dedicated atmos. No way for BZ to reach there. The temp of which they disappeared if I remember right was around 30c

**Comment by davethwave** [comment]
Welp, did some actual testing. The standard temp for the station is 20c. If the temp rises above 30c aka 86f the weed is destroyed. This is kind of busted. You could light a single piece of plasma and see the entire xeno base turn to dust. I tested this and lighting a single plasma floor tile, in other words a fourth of a piece of plasma was enough to bring the temp in the thunderdome to 150c.  Heck, you could just warm up a can of air to around 40c and watch as a massive radius around the thing is now weed proof.

**Comment by TheBonded** [comment]
> Welp, did some actual testing. The standard temp for the station is 20c. If the temp rises above 30c aka 86f the weed is destroyed. This is kind of busted. You could light a single piece of plasma and see the entire xeno base turn to dust. I tested this and lighting a single plasma floor tile, in other words a fourth of a piece of plasma was enough to bring the temp in the thunderdome to 150c. Heck, you could just warm up a can of air to around 40c and watch as a massive radius around the thing is now weed proof.

generally xenos just vent the room theyre in since theyre pressure and cold proof so that rarely happens
