### ISSUE TITLE
heretic brazil can spawn you on nukie shuttle oversight 

### ISSUE THREAD

**Issue by theta060** [tgstation/tgstation#66526]
Reporting client version: 514.1583

## Round ID:
[182161](https://scrubby.melonmesa.com/round/182161)

## Testmerges:
- [Adds a discord bot command version of show-server-revision](https://www.github.com/tgstation/tgstation/pull/66338)
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)
- [Human Life Optimization: Citrus Flavored](https://www.github.com/tgstation/tgstation/pull/66037)
- [Adds MC initialization stages. Earlier stages can fire while later ones init. Fixes tgui chat reconnection banner showing during init.](https://www.github.com/tgstation/tgstation/pull/66473)

**Comment by ArcaneDefence** [comment]
These reproduction steps fucking suck.

**Comment by MrMelbert** [comment]
a consequence of using `find_safe_turf()` instead of `get_safe_random_station_turf()`

**Comment by theta060** [comment]
> These reproduction steps fucking suck.

its very descriptive on what went wrong

**Comment by timothymtorres** [comment]
So you spawned as a heretic on the nuke shuttle?  Was this at roundstart?

**Comment by necromanceranne** [comment]
> > These reproduction steps fucking suck.
> 
> its very descriptive on what went wrong

Rewrite this properly, and follow the template please.

**Comment by TheBonded** [comment]
> > > These reproduction steps fucking suck.
> > 
> > 
> > its very descriptive on what went wrong
> 
> Rewrite this properly, explain exactly the steps to recreate this situation, and follow the template please.

to be fair its super self explanatory.

step 1: get sacrificed by a heretic
step 2: survive touhou hell
step 3: get sent back to a random safe location after surviving touhou hell
step 4: have that random safe location roll the syndie ship 
step 5: die to the armour piercing turrets on the syndie ship

**Comment by theta060** [comment]
> > > > These reproduction steps fucking suck.
> > > 
> > > 
> > > its very descriptive on what went wrong
> > 
> > 
> > Rewrite this properly, explain exactly the steps to recreate this situation, and follow the template please.
> 
> to be fair its super self explanatory.
> 
> step 1: get sacrificed by a heretic step 2: survive touhou hell step 3: get sent back to a random safe location after surviving touhou hell step 4: have that random safe location roll the syndie ship step 5: die to the armour piercing turrets on the syndie ship

this guy gets it

**Comment by JohnFulpWillard** [comment]
this reminds me of that time the nuclear authentication disk went off the Z level and teleported to the syndicate infiltrator.
