### ISSUE TITLE
Character Setup Error

### ISSUE THREAD

**Issue by KonKonBreezeFox** [tgstation/tgstation#66535]
![image](https://user-images.githubusercontent.com/104439587/165308319-8bd885b8-7da3-4066-af24-c51e3b6be195.png)

## Reproduction:Clicking on character setup... thats basicly what i did to get that... i tried opening the character setup about 10 times and 8 times it did not open and 2 times that popped up. After this is the full message in the picture due some stuff being blocked off. To add on, this is on Sybil.
UnhandledRejection: SyntaxError: Ungültiges Zeichen
   at Anonymous function (http://127.0.0.1:52485/tmp15980/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:52485/tmp15980/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"kondafairydragon","interface":"PreferencesMenu","window":{"key":"[0x210757b1]-main","size":null,"fancy":1,"locked":0}}

UnhandledRejection: UnhandledRejection: SyntaxError: Ungültiges Zeichen
   at Anonymous function (http://127.0.0.1:52485/tmp15980/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:52485/tmp15980/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"kondafairydragon","interface":"PreferencesMenu","window":{"key":"[0x210757b1]-main","size":null,"fancy":1,"locked":0}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Ungültiges Zeichen
   at Anonymous function (http://127.0.0.1:52485/tmp15980/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:52485/tmp15980/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"kondafairydragon","interface":"PreferencesMenu","window":{"key":"[0x210757b1]-main","size":null,"fancy":1,"locked":0}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Ungültiges Zeichen
   at Anonymous function (http://127.0.0.1:52485/tmp15980/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:52485/tmp15980/tgui.bundle.js:1:64895)

**Comment by MrStonedOne** [comment]
> Round ID:None... its in the lobby

We still need the round id.

or at least the date time and timezone so we can figure it out ourselves.

round ids are used to store logs, and logs have more details about what happened.

Also i have a feeling that if you tried this right now, it would not happen again.

**Comment by Mothblocks** [comment]
![image](https://user-images.githubusercontent.com/35135081/165414896-62588c9e-f1b1-46f2-9cf2-0e0ee799c485.png)
