### ISSUE TITLE
Removal of uplink unlock failure message removal runtimes implant and pen uplinks

### ISSUE THREAD

**Issue by GolfinhoVoador** [tgstation/tgstation#66536]
## Testmerges:
[65997](https://github.com/tgstation/tgstation/pull/65997)
[66037](https://github.com/tgstation/tgstation/pull/66037)

## Reproduction:
Get a pen (or implant) implant.
Try to use it.
TGUI runtime error
[PR mentioned in title](https://github.com/tgstation/tgstation/pull/66458)

**Comment by magatsuchi** [comment]
this is hilarious
please post the error

**Comment by magatsuchi** [comment]
possibly an isolated incident

**Comment by GolfinhoVoador** [comment]
> possibly an isolated incident

Can you check if its happening in the latest sybil round?

**Comment by magatsuchi** [comment]
i cannot for i am not home

**Comment by Mothblocks** [comment]
Uplinks use `/datum/asset/json`, which is broken. Without an error (which are not in server logs), I'm going to assume it's that and let this auto close.

**Comment by timothymtorres** [comment]
As Mothblocks said, lots of stuff that were using the asset system all broke recently leading to lots of duplicate issues.  This should be fixed by #66549

**Comment by TheBonded** [comment]
@GolfinhoVoador the reason you couldnt find the logs initially is because they are not posted until the round *following* completes, and the sybil round that took place after the one in question lasted 3 hours, meaning the logs would have been made available around 18:08:49 UTC or 12:08:49 MDT
