### ISSUE TITLE
Personal TGUI bluescreen error

### ISSUE THREAD

**Issue by Shellton123** [tgstation/tgstation#66542]
## Testmerges:

[#65791: 'Optimizes Runechat' by Kylerace at commit 8e213063d4](https://www.github.com/tgstation/tgstation/pull/65791)
[#66348: 'Makes it possible to speed up the tram' by Thunder12345 at commit 15f5a6d7a6](https://www.github.com/tgstation/tgstation/pull/66348)
## Reproduction:
Whenever I click anything that uses tgui I get the following bluescreen message

Script error.
   at https://tgstation13.download/byond/assets/7e/asset.7e30f58c9483e1bb5ec5e372e8629f2b.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)

I have tried the following: Updating byond, Clearing Cache, restarting game and reinstalling byond as a whole. It seems its just me having this issue as well and it just started happening today.

Any tips?

**Comment by ModDownloading** [comment]
Not just you, I'm having the exact same issue too.

**Comment by LuxuriousTurnip** [comment]
I'm having the same issue as well.  If I find a way to get it fixed by messing around, I'll let ya know.

**Comment by Mothblocks** [comment]
Looks to be a CDN bug, there's one potential fix we have in mind (in #66535) but without any more information I'm just going to close this.
