### ISSUE TITLE
Fatal Exception

### ISSUE THREAD

**Issue by Scrambles18** [tgstation/tgstation#66541]
## Round ID:

 182196

## Reproduction:

I'm unable to utilize nearly everything that has a pop-up. No PDA, Computers, etc. Relogging does not work. Everything brings up the following. It seems I'm the only one with this issue.

Script error.
   at https://tgstation13.download/byond/assets/7e/asset.7e30f58c9483e1bb5ec5e372e8629f2b.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)

**Comment by TheBonded** [comment]
open the byond launcher, go into preferences -> game -> clear BYOND cache. 99% sure this will fix it.

**Comment by Mothblocks** [comment]
Looks to be a CDN bug, there's one potential fix we have in mind but without any more information I'm just going to close this.
