### ISSUE TITLE
Midround join ignored antag preferences being disabled

### ISSUE THREAD

**Issue by Crushtoe** [tgstation/tgstation#66558]
Reporting client version: 514.1569

## Round ID:
[182218](https://scrubby.melonmesa.com/round/182218)

## Testmerges:
- [Remove data/ from /datum/asset/json url mapping](https://www.github.com/tgstation/tgstation/pull/66549)
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)
- [Keep mutating filenames when the cdn is disabled midround.](https://www.github.com/tgstation/tgstation/pull/66550)

## Reproduction:

1. Have traitor off in character preferences. (Verified it was turned off.)
2. Join the game midround.
3. Be auto-assigned traitor despite character preference having it off.

If I had to bet money, it's related to #65997 and midround rolls being whack.

**Comment by TheBonded** [comment]
do you have midround traitor disabled, or roundstart traitor (or even midround traitor)? or all three? there are three different prefs for traitor.

**Comment by Mothblocks** [comment]
I checked your preferences and you have Syndicate Infiltrator on, AKA latejoin traitor, which is what you rolled (not midround).

**Comment by Crushtoe** [comment]
Woops, I'm a fool. So many buttons to press.
