### ISSUE TITLE
Bar Bots Are Fucking Broken (they keep spamming the order edition)

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#66554]
## Reproduction:

Place down a bar bot decal
Open the bar bot portal
The following will happen when the bar bot reaches its seat

https://user-images.githubusercontent.com/34697715/165432682-eaaba217-a145-47bb-af1c-05a52ccdc7d8.mp4

**Comment by newfren** [comment]
give the man his beer

**Comment by interestingusernam3** [comment]
@TRALEZAB

**Comment by MrMelbert** [comment]
#66073 @Ghommie ?

**Comment by Ghommie** [comment]
Uh uh. I'll fix that right away.
