### ISSUE TITLE
Station Drones aren't allowed to interact while near another Station Drone

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#66577]
## Reproduction:
![image](https://user-images.githubusercontent.com/62538745/165817563-6528e2e8-8a87-4045-b99f-03013340784d.png)
Spawn as a drone, when another drone spawns, if you are near them you can't do anything.

I'm pretty sure you're supposed to be able to cooperate with drones.

**Comment by TheBonded** [comment]
Related code
https://github.com/tgstation/tgstation/blob/6eb56a639141c6913330c4e9bd548d75bd670cd3/code/datums/components/shy.dm#L88-L105
https://github.com/tgstation/tgstation/blob/6eb56a639141c6913330c4e9bd548d75bd670cd3/code/modules/mob/living/simple_animal/friendly/drone/_drone.dm#L338-L341

**Comment by ZeroMODE0** [comment]
Other quirks with the weird allowances that drones have are the ability to literally weldertank bomb, plasma flood, and strip living, active players at certain times
But picking up a lightbulb box is against your laws!

**Comment by TheBonded** [comment]
I can welderbomb, strip living active players sometimes, even plasmaflood entire departments, but
![image](https://user-images.githubusercontent.com/58570888/165836113-fca7d60e-9db2-4e22-8ca2-886e575f9242.png)
![image](https://user-images.githubusercontent.com/58570888/165836142-e764e637-c3a9-43a4-9df6-c0a6552e8df7.png)


(though Im pretty sure the only time they can welderbomb or strip living players is if they have their laws disabled by the chief engineers PDA)

**Comment by ZeroMODE0** [comment]
Unless something changed I remember spawning in during round-end and being pacified, being unable to act near a medibot, but being able to strip a living player out of having a gas mask before pflooding
then welder tank bombing to ignite said plasma flood

I don't think people play drone enough for stuff like this to even get noticed, let alone multiple drones attempting to light up maintenance together noticing they have to go one at a time at least 6 tiles away from one another...
Being unable to hold stuff like gas analyzers makes sense as drones would probably be bored enough to upgrade all the AI's cameras and allow it to snipe people through walls

**Comment by TheBonded** [comment]
without a gas analyzer i cant tell if the room im fixing is safe for humans. and without an atmos holofan i cant make sure to not vent a room when upgrading the windows

**Comment by ZeroMODE0** [comment]
You're able to ask admins to add things to your drone's whitelist by adding an atom typepath to the parent drone's /datom/components/itempicky >> whitelist list.
![image](https://user-images.githubusercontent.com/62538745/165848630-8aca094d-9377-4472-8d67-b54ae4fdc4a3.png)
I guess I understand good tools like these have opportunity for drones to be too impactful on a round by replacing an atmos tech entirely
Since it's working off a whitelist rather than a blacklist, and already has 1356 items in it, it's pretty reasonable to assume some of this might be oversight stuff, like light replacers and light boxes. Which is also fixable by asking admins to add to your whitelist, like I've done here.
![image](https://user-images.githubusercontent.com/62538745/165849257-1149af45-a946-466b-a4a4-456a73286653.png)

**Comment by ATH1909** [comment]
> (though Im pretty sure the only time they can welderbomb or strip living players is if they have their laws disabled by the chief engineers PDA)

wait, the CE can disable drone laws??

**Comment by ZeroMODE0** [comment]
> > (though Im pretty sure the only time they can welderbomb or strip living players is if they have their laws disabled by the chief engineers PDA)
> 
> wait, the CE can disable drone laws??

They can enable drones to interact with "machines that may prove harmful or dangerous" etc from their pda/tablet
which I'm not really sure what it does, but it enables the use of air alarms, and drones can just... turn it on themselves.
![image](https://user-images.githubusercontent.com/62538745/165858848-e779ae19-b63e-4ea4-84a8-a350d71873f7.png)

**Comment by TheBonded** [comment]
you can welderbomb and plasmaflood with it turned on too, as it turns out.

**Comment by JohnFulpWillard** [comment]
>  and drones can just... turn it on themselves. 

what

**Comment by TheBonded** [comment]
> > and drones can just... turn it on themselves.
> 
> what

they can interact with PDA tablets and just enable it themselves
