### ISSUE TITLE
The detective waistcoat renders on top of trenchcoats

### ISSUE THREAD

**Issue by TheSmallBlue** [tgstation/tgstation#66580]
## Reproduction:

1. Put on the noir suit
2. Apply the waistcoat to the suit
3. Put on a trenchcoat
4. See the waistcoat render on top of the trenchcoat
![dreamseeker_ebsaZKv7zp](https://user-images.githubusercontent.com/24967815/165848376-1cb89158-a099-4cc4-b3ab-0503d013202f.png)
![dreamseeker_4pZ07Y7s9e](https://user-images.githubusercontent.com/24967815/165848384-0359af8d-b37d-441a-b1ca-a33e9ed67a1c.png)
![dreamseeker_3aEYc202MF](https://user-images.githubusercontent.com/24967815/165848396-7c1920f8-885e-4a7d-a33c-d6f8d84eacd0.png)

**Comment by Twaticus** [comment]
so this is kind of a feature and kinda bugged at the same time. right clicking the waistcoat will toggle it to display under the coat/over the coat. the issue is something somewhere accidently flipped the toggle i guess? so its rendering above initially instead of below

**Comment by TheSmallBlue** [comment]
Oh God I forgot to close this. Someone told me about right clicking the waistcoat and after that it works fine. Still think it sucks that it isn't the default but that has nothing to do with this being a bug, which it isn't.
