### ISSUE TITLE
Malfunction module picker crashes after purchasing Voice Changer

### ISSUE THREAD

**Issue by liilac** [tgstation/tgstation#66598]
## Round ID: `182285`

The round was on **Manuel**.

~~There were adminhelps between myself (**2884784276937S**) and **PositiveEntropy** during the round. I believe that this is the only round I have communicated with **PositiveEntropy** via adminhelp.~~

~~The round, I believe, took place around **03:50** to **05:40** on **29/04/2022** (Australian Eastern Standard Time, **UTC+10:00**).~~

## Testmerges:
N/A

## Reproduction:

**NOTE**: I have not attempted to reproduce this outside of the round described above.

### Steps to reproduce

1. Be AI
2. Receive combat software upgrade, enabling Malfunction Modules
3. Purchase _Voice Changer_ module
4. Open the _Voice Changer_ module (_possibly_ requires the Malfunction Module Picker to still be open)

### Notes
- Crashed _Malfunction Module Picker_ persists across reconnections and restarting BYOND
- Interfaces for the *Voice Changer* and other modules continue to work fine.
- Successfully hacking further APCs does not correct the issue.
- Using the repair cameras module does not correct the issue.

### In-game stack trace
```
NtOS

https://github.com/tgstation/tgstation. Thank you for your cooperation.

Script error,
at https://tgstation13.download/byond/assets/7e/asset.7e30f58c9483e1bb5ec5e372e8629f
2b.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET
4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"2884784276937S", "interface": "MalfunctionModulePicker", "window": {"key":"[0x21082ee8]-main", "size':null,"fancy":1, "locked":1}}

Nanotrasen (c) 2525-2562
```
![Nanotrasen Stack Trace](https://files.catbox.moe/2vum6x.png)

**Comment by TheBonded** [comment]
Likely round https://scrubby.melonmesa.com/round/182285

Falls close to (but not exactly) the time frame provided in the issue report, and is a round where user 2884784276937S plays AI and receives combat upgrades. user PositiveEntropy is also shown to have observed this round, meaning they would have been there to handle the ahelps.

Testmerges during this round were #66549 and #66550 

For future reference, please use the "report bug" function in game, or use any of the ways to check the current round ID for making your issue reports (such as checking the website, using the discord bot, or one of the in game verbs probably shows it)

**Comment by liilac** [comment]
Thanks @TheBonded, that was indeed the correct round.

**Comment by TheBonded** [comment]
> I had taken screenshots during the round, recording the round ID and other information. I had accidentally only been saving these to my clipboard.

fair, though do keep in mind the report bug button (which I believe is above the status tab, at the top of the side bar) *should* autofill the round ID into the bug report meaning you wouldnt have to worry about remembering the round ID or testmerges

**Comment by TheBonded** [comment]
Also, on an unrelated note, your transcription of the provided screenshot in the issue report body has a slight typo where you have replaced the "S" at the end of your ckey with a "5"

**Comment by TheBonded** [comment]
possibly related code:
https://github.com/tgstation/tgstation/blob/bc28593e9d9665bb3c209b512cfe003130072476/code/modules/antagonists/traitor/equipment/Malf_Modules.dm#L932-L936

**Comment by Sadboysuss** [comment]
doesn't seem to happen anymore
