### ISSUE TITLE
Lings that get forcibly DNR'd by the rev victory are unable to revive

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#66606]
## Round ID:

[Round ID]: # 182357

## Testmerges:
irrelevant

## Reproduction:

be a head of staff
be a ling
have revs kill you
have revs win
be unable to revive 
![image_2022-04-29_215125564](https://user-images.githubusercontent.com/54422837/166085957-f16d7253-0d73-4730-b20b-8e46f0d2e270.png)

**Comment by JohnFulpWillard** [comment]
https://cdn.discordapp.com/attachments/803384291383574540/969784167384641546/2022-04-29_22-14-35.mp4
