### ISSUE TITLE
Admin messages cannot be dismissed

### ISSUE THREAD

**Issue by Tarhalindur** [tgstation/tgstation#66619]
## Reproduction: 
1. Get an admin message that appears when you connect.
2. Click the link to dismiss it.
3. Scream in horror as it continuously reappears every connection and reminds you of your failures.

**Comment by Mothblocks** [comment]
No relevant SQL logs on that round. Can't seem to find relevant runtimes either.

**Comment by Jordie0608** [comment]
The wrong href parameter is being passed; topic checks for `message_id`
https://github.com/tgstation/tgstation/blob/45fa34d252708a5d28da5dff9efd8c17dc477323/code/modules/admin/topic.dm#L406
but the href sets `messageread`
https://github.com/tgstation/tgstation/blob/45fa34d252708a5d28da5dff9efd8c17dc477323/code/modules/admin/sql_message_system.dm#L672

Also this is handled in `admin/Topic`, this proc doesn't fire for non-admins.

**Comment by JohnFulpWillard** [comment]
https://github.com/tgstation/tgstation/pull/80908
