### ISSUE TITLE
Tables merge with each other through directional windows.

### ISSUE THREAD

**Issue by Son-of-Space** [tgstation/tgstation#66614]
## Round ID: N/A

Placing two tables next to each other with a directional window in-between them will still result in the tables merging

## Testmerges:

None

## Reproduction:
Place two tables next to each other with a window in between

**Comment by timothymtorres** [comment]
What makes you think they shouldn't auto-connect?  Do tables connect if there is a girder placed on top?  What about railings or full-tile windows?

**Comment by Son-of-Space** [comment]
Directional windows are a barrier to people so they should be a barrier to tables. They're a full z level high.
