### ISSUE TITLE
Mind Reader Mutation going on permanent cool down in specific instance

### ISSUE THREAD

**Issue by Davesalter** [tgstation/tgstation#66624]
## Reproduction:

 get the Mind Reader mutation from genetics or other sources as long as its the same one
use the ability as all targets on the list leave sight/range so that you have a list with names in it but no visible targets
proceed to target one of them by selecting their name
the ability will go into a permanent cool down state (this has happened twice in total to me with the outcome and steps being the same so likely consistent)

**Comment by Rhials** [comment]
I did some testing and it looks like this can also happen when you use the spell when there's nobody in view more than once.
