### ISSUE TITLE
Clicking on people out of attack range with Deathnettles cause durability loss

### ISSUE THREAD

**Issue by Cookhimself** [tgstation/tgstation#66631]
## Round ID:
Tested Locally

## Testmerges:
N/A

## Reproduction:
Grab a Deathnettle and click on someone across the screen with it and watch as your nettle disappears from durability loss.

**Comment by MrMelbert** [comment]
Amazing. 

`after_plant_attack()` doesn't check if proximity before proceeding. 
`COMSIG_ITEM_AFTERATTACK` sends `proximity_flag` which `after_plant_attack()` disregards. Simple fix
