### ISSUE TITLE
Bluespace bodybagging a xenomorph qdels it, the bag, and everything else inside when you fold it

### ISSUE THREAD

**Issue by OmegaDarkPotato** [tgstation/tgstation#66634]
Reporting client version: 514.1582

## Round ID:
[182418](https://scrubby.melonmesa.com/round/182418)

## Testmerges:
- [Makes smoke and foam attempt to fill the available space.](https://www.github.com/tgstation/tgstation/pull/65281)
- [Keep mutating filenames when the cdn is disabled midround.](https://www.github.com/tgstation/tgstation/pull/66550)
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)
- [Parallax but better: Smooth movement cleanup](https://www.github.com/tgstation/tgstation/pull/66567)

## Reproduction:
Step 1: kill a benomorph of choice
step 2: slide a bluespace bodybag underneath it
step 3: close the bag, fold it up
step 4: watch as the bag ceases to exist

**Comment by Crushtoe** [comment]
reproducible on local
