### ISSUE TITLE
No HUD for construct's spells

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#66641]
## Reproduction:

Wizard's constructs didn't have HUD buttons for their spells.

**Comment by castawaynont** [comment]
This is a result of the test merge of new action buttons. Alt click the action button drop down to restore the spells.

**Comment by private-tristan** [comment]
this also applies to the nar'sie harvesters that people are converted into by nar'sie, dunno about cult constructs because I haven't been one recently.

**Comment by moocowswag** [comment]
it applies to cult construct too but I ran into that like weeks ago (why is this still a test merge)

**Comment by IllotAFV** [comment]
Duplicate of https://github.com/tgstation/tgstation/issues/66120?

**Comment by magatsuchi** [comment]
duplicate of #66120
