### ISSUE TITLE
you can shoot things point blank even when they're behind a windoor

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#66645]
## Round ID:
[182451](https://scrubby.melonmesa.com/round/182451)

## Reproduction:
have object behind windoor (with the windoor on the same tile as the object)
be positioned so that the windoor is between you and the object
shoot object 
object gets shot point blank despite the windoor being between it

examples:
![image_2022-05-01_200257590](https://user-images.githubusercontent.com/54422837/166170114-f243cf97-2d2a-439d-8b8b-6c0fec579c15.png)
![image_2022-05-01_200316347](https://user-images.githubusercontent.com/54422837/166170128-2ddb1add-b51d-4491-87fe-8e0115649d78.png)

**Comment by TheBonded** [comment]
doesnt shooting a glass window with a PKA also hit the grille underneath first, even if its a fulltile?
