### ISSUE TITLE
Changeling UI runtimes

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#66668]
Reporting client version: 514.1568

## Round ID:
[182507](https://scrubby.melonmesa.com/round/182507)

## Testmerges:
- [Makes smoke and foam attempt to fill the available space.](https://www.github.com/tgstation/tgstation/pull/65281)
- [Keep mutating filenames when the cdn is disabled midround.](https://www.github.com/tgstation/tgstation/pull/66550)
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)
- [Parallax but better: Smooth movement cleanup](https://www.github.com/tgstation/tgstation/pull/66567)

## Reproduction:

```
[2022-05-02 23:12:00.342] runtime error: Cannot modify null.icon_state.
 - proc name: unset sting (/datum/action/changeling/sting/proc/unset_sting)
 -   source file: tiny_prick.dm,31
 ```
```
[2022-05-02 23:11:49.452] runtime error: Cannot modify null.icon_state.
 - proc name: set sting (/datum/action/changeling/sting/proc/set_sting)
 -   source file: tiny_prick.dm,23
 ```
```
[2022-05-02 23:23:15.917] runtime error: Cannot modify null.maptext.
 - proc name: adjust chemicals (/datum/antagonist/changeling/proc/adjust_chemicals)
 -   source file: changeling.dm,273
 ```

**Comment by Sealed101** [comment]
fixed by https://github.com/tgstation/tgstation/pull/76772 question mark? at least that's the last bit of code that i can see that affected `lingstingdisplay`, and i can't really reproduce these runtimes with any of the stings
