### ISSUE TITLE
When making "Fields" on pieces of paper they display correctly in the preview, but don't actually save

### ISSUE THREAD

**Issue by Palpetinus** [tgstation/tgstation#66679]
## Round ID:
[182488](https://scrubby.melonmesa.com/round/182488)

## Testmerges:
#66348 
#65791 
#66550 
#66549 

## Reproduction:
1. Grab pen and paper
2. Attempt to make a field on said paper "[____]"
3. Watch how it displays properly in the preview, a neat field to be filled in afterwards
4. Save
5. Watch how it's gone afterwards
6. Despair as paperwork RP is ruined

Or just watch this instructional video:

https://user-images.githubusercontent.com/91543124/166516244-9f54ef04-455a-4686-81ba-25414ca0c69d.mp4

(To clarify, no I didn't expect the stuff in "preview" to stick, that was just idle commentary)

**Comment by Sealed101** [comment]
paperwork got refactored... [somewhere](https://github.com/tgstation/tgstation/commits/master/code/modules/paperwork/paper.dm) and this issue got squashed; can't reproduce
