### ISSUE TITLE
Crafting heads on sticks creates a broken version, doesn't consume the materials

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#66676]
## Round ID:

Consistent - different heads, different rounds, and different people trying to craft them
## Reproduction:
Tribal crafting tab has an option to put heads on spears as a decoration "for when you wanna send a message".
A while ago, that recipe stopped working. It does not consume the head, nor the spear & creates a "spooky head on a spear" which is just an empty spear standing upright.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/f3d2f0b7c7bbdca2b2493d074ca9cfbd07c44b48/code/datums/components/crafting/recipes.dm#L1006-L1015

Did you try to craft it using a normal spear?

**Comment by Likteer** [comment]
@timothymtorres Yes, it was a regular spear in all cases. There is a seperate crafting recipe for a bone spear one which I haven't checked.

**Comment by Redrover1760** [comment]
I have seen this bug as well. Its real, and its sad.
