### ISSUE TITLE
HoP is charged for Supply techfabs

### ISSUE THREAD

**Issue by JohnFulpWillard** [tgstation/tgstation#66682]
## Reproduction:

1. Join as HoP
2. Go to Cargo
3. Print something out
4. Get charged 10 credits

![image](https://user-images.githubusercontent.com/53777086/166605252-755cd092-bbdc-47d7-bd8a-1fa724881b3d.png)

HoP is considered Service, not Cargo, but they are supposed to be both
![image](https://user-images.githubusercontent.com/53777086/166605291-e426a134-ac7b-4f3d-946f-85c6b9ee94ff.png)
![image](https://user-images.githubusercontent.com/53777086/166605297-10c1f105-8f50-48b0-bb28-8f48bb75c936.png)

**Comment by JohnFulpWillard** [comment]
@ArcaneDefence

**Comment by JohnFulpWillard** [comment]
@ArcaneMusic (I once again pinged the wrong person)

**Comment by TheBonded** [comment]
just let command crew use any techfab with no taxes honestly
