### ISSUE TITLE
The Tale Of Two Intercoms on DeltaStation's Captain Office (Insert Hot Dog Meme Here)

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#66716]
## Reproduction:

![image](https://user-images.githubusercontent.com/34697715/166869571-3d977360-99da-49a9-b3cb-a7bdf2781978.png)

The captain has two intercoms in their room on DeltaStation. Please make certain the captain only has ONE intercom in their room.

**Comment by MrMelbert** [comment]
Repeating here: 

> It's likely that one of the two intercoms is supposed to be the "captain's intercom", the freerange intercom the captain's office is given on some maps

>Metastation has two intercoms in a similar configuration,  but one is a Captain's Intercom while the other is normal
![image](https://user-images.githubusercontent.com/51863163/166878299-e6eaf60f-8978-4252-839e-fbc06a4953dd.png)

>However on Delta they're both normal intercoms. Might've been removed by accident at some point or something. 

![image](https://user-images.githubusercontent.com/51863163/166878802-2f8052e2-053c-4dc9-acdc-946ce5ae1707.png)

Tram has two intercoms as well, and neither are Captain's Intercoms
