### ISSUE TITLE
DeltaStation Virology Shower Floaty (Not Good Floaty :( )

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#66714]
## Reproduction:

![image](https://user-images.githubusercontent.com/34697715/166869172-43e5d437-d864-410b-8ee7-488ee9e7a9a0.png)

This one is a bit hard, but both of these showers on the Virology airlock "float" without support. Doesn't make sense at all to me, and this is a pretty cramped space. You'd probably have to re-arrange the whole room to account for the showers? Have fun with this, just make sure the showers are on the wall in some way. If you really need to, you can expand the airlock a bit to accommodate, but doesn't need to be a hugely large thing.

**Comment by MrMelbert** [comment]
I think they were designed to look like emergency chemical showers. 

I doubt it was unintentional, but I don't think anyone would object to it being changed
