### ISSUE TITLE
"?" Sechud icon remains on some people after removing security hud

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#66710]
Reporting client version: 514.1568

## Round ID:
[182624](https://scrubby.melonmesa.com/round/182624)

## Testmerges:
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Fix granular admin ranks not being loaded from DB](https://www.github.com/tgstation/tgstation/pull/66706)

## Reproduction:

I'm not even sure if this is a bug or what tbh

![image](https://user-images.githubusercontent.com/51863163/166858484-80b74478-483a-4054-b0be-7aea611b563d.png)

- Wear security hud
- Take security hud off
- Some people still have a "?" hud by them, despite wearing no huds anymore

**Comment by BebeYoshi** [comment]
Sometimes I had to go to ice moon to save some bodies as a MD so I had to use mesons instead of MedHUD and the same happened but with MedHUD, it was not functional though, so most people would appear with a full health even if they were dead.

**Comment by SethLafuente** [comment]
![gtR7Yyl](https://github.com/tgstation/tgstation/assets/84478872/6d596d54-09fd-4778-a87c-736f4b975397)
No longer an issue as shown in this gif
