### ISSUE TITLE
Blob Zombies become sentient (and evil!) when made by the gold slime reaction

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#66728]
## Reproduction: 1. Use gold slime blood reaction to create monsters. 2. create a blob spore via the neutral xenobio reaction. 3. Drag a monkey towards it. 4. A sentient blob zombie is created that is not bound to your will, nor neutral. 5. die for being an unknowing unprepared xenobiologist

Whatever blob feature made all blob zombies sentient definitely forgot to account for xenobio, otherwise the blobbernauts would be sentient and evil too! (Without light pink reaction)

**Comment by moocowswag** [comment]
Whats funny is (I`m not sure if this unrelated bug is still in the game but since I`ve last seen a blob it is) If the blob zombie became sentient after the blob zombie ai targeted you then the player that took control of the zombie has very little in the way of free will until the ai either kills you or losses track of you.

**Comment by davethwave** [comment]
You are reading it wrong. They mean that a blob spore from a friendly reaction took over a monkey, then the player who was in control of said monkey killed them due to their mobs nature.

**Comment by ATH1909** [comment]
I believe this is intentional? Like, the niche of the blob spore for xb (and, importantly, cytology) is that you don't need a sentience potion for it.

**Comment by Shadowflame909** [comment]
Yeah but they're not bound to you at all like by the xenobiology light pink potion. and as a simple mob with brute attacks only that's very bad

**Comment by timothymtorres** [comment]
So two things are needed to fix this:

- When creating a blob zombie, check if the spore is passive
- When a aggressive blob zombie gets dociled by a light pink potion, we need to reset it's AI attack state

**Comment by Sealed101** [comment]
light pink potion interaction seems to be fixed already, basicmobbing is the likely cause
