### ISSUE TITLE
Random item no longer takes any item from the job specific item pool. Random item on Debug uplink grabs every item from any item pool.

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/tgstation#66743]
## Round ID:
Did this in a local

## Testmerges:
None

## Reproduction:
1. Get an uplink
2. Use random item
3. No matter how much TC you use you wont get any job specific items other than your own jobs.
---Debug Uplink---
1. Get a debug uplink
2. Use random item
3. Get any item from any pool, including clown ops and nuke ops, despite the fact you wont see them as an option to pick normally.

![image](https://user-images.githubusercontent.com/24631139/167110244-55aae504-686f-4690-a6fa-f88859ea053d.png)

Past behaviour was the normal uplink giving you any job specific item if you were lucky/unlucky enough to roll it, even the ancient jumpsuit.

**Comment by Shadowflame909** [comment]
Is this really an issue for the debug uplink though?

About as much rng as a christmas tree, plus most of those items require a syndicate firing implant which you cannot obtain from the uplink.

**Comment by BlueMemesauce** [comment]
Had no idea that the past behavior was even a thing. It wasn't mentioned anywhere that it did anything extra other than just pick a random item for you.

**Comment by orthography** [comment]
> Is this really an issue for the debug uplink though?
> 
> About as much rng as a christmas tree, plus most of those items require a syndicate firing implant which you cannot obtain from the uplink.

It'd really suck to do a random item and then be out of luck with no TC because you were given an item you can't use.

**Comment by msgerbs** [comment]
So what is the _expected_ behavior and the _actual_ behavior, with the non-debug uplink? I'm a bit confused.
