### ISSUE TITLE
Borgs are unable to turn on floodlights

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#66758]
Reporting client version: 514.1581

## Round ID:
182733

## Testmerges:
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)

## Reproduction:

>Be a borg

>Place floodlight

>Wrench floodlight

>Click to turn on

>Nothing happens

>Human clicks to turn on

>It turns on

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/8c7e4ef6ee0b6e60783ccb084d60138353b2e2be/code/modules/power/floodlight.dm#L120-L129

https://github.com/tgstation/tgstation/blob/8c7e4ef6ee0b6e60783ccb084d60138353b2e2be/code/modules/power/floodlight.dm#L85-L108
