### ISSUE TITLE
Drones wearing kitty ears creates tentacle.

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/tgstation#6675]
Problem: A drone puts kitty ears on its head to look cute.
Cat ears apply fine, cat tail that normally goes along with cat ears ends up looking like this weird tentacle thing coming out of the floor.

Pic: 
![image](https://cloud.githubusercontent.com/assets/5169683/5575148/977cfd9e-8f8e-11e4-9f9c-80fd3920cb6e.png)

![image](https://cloud.githubusercontent.com/assets/5169683/5575149/9e3bbc2e-8f8e-11e4-89c2-54751f0f2614.png)

**Comment by bgobandit** [comment]
fucking feature

**Comment by tedward1337** [comment]
Has this been fixed?

**Comment by RemieRichards** [comment]
Not strictly "fixable"

**Comment by ChangelingRain** [comment]
unfixable withour drone-specific sprites, which is unworkable for various reasons
