### ISSUE TITLE
Drinking too much root beer makes your screen shake through space and time

### ISSUE THREAD

**Issue by TheBonded** [tgstation/tgstation#66755]
## Reproduction:
1. get root beer
2. use it to make root beer bees
3. get stung by root beer bees (you now have several hundred units of root beer in your system
4. start seeing things across the map and eventually just hardcrash every time you reconnect

https://user-images.githubusercontent.com/58570888/167224843-7fb6f9cb-34c2-4ea5-9f3c-a8873e43e7d5.mp4

**Comment by MrMelbert** [comment]
Likely a consequence of having very high dizziness, very late into the round
Reproduction steps on a local server would be appreciated

**Comment by Shadowflame909** [comment]
too much of that bluespacium

**Comment by MacBlaze1** [comment]
could we cap dizzyiness?

**Comment by Shirbu** [comment]
The consequences of being a Mug Maniac. The bloodlust cannot be contained.

**Comment by Slurge00** [comment]
this was her last contribution. the last bug she showed me. i miss you.

**Comment by notfrying1pans** [comment]
> this was her last contribution. the last bug she showed me. i miss you.

thats me in the video, i had no clue this was going to be our last interaction in game

**Comment by Slurge00** [comment]
> > this was her last contribution. the last bug she showed me. i miss you.
> 
> thats me in the video, i had no clue this was going to be our last interaction in game

it is surreal. almost 2 years since she left. almost 1 since i stopped playing. i remember her dm’ing me about this specific bug. one of the last things we talked about.
