### ISSUE TITLE
DeltaStation Brig Fire Alarm Hijinx

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#66761]
## Reproduction:

![image](https://user-images.githubusercontent.com/34697715/167239656-4511c192-9343-4085-bef6-40e8257147cf.png)

These two fire alarms (to the north and the east of the tile I have highlighted) both suck in placement. That one to the north of the highlighted tile is directly RIGHT over a pepper spray dispenser. Just rearrange stuff. It's a bit cramped on wallspace so you might have to do some trickery as far as the north one, the eastern one just needs to be moved somewhere else in that hallway.

**Comment by MrMelbert** [comment]
weird looking metastation

**Comment by san7890** [comment]
> weird looking metastation

FUCK
