### ISSUE TITLE
pAI unable to recover after *collapse

### ISSUE THREAD

**Issue by lucigoosi** [tgstation/tgstation#66760]
## Round ID: 
**Edit/Reproduced on tg code:** Manuel round #182889, pAI name was Luci, testing occurred around 19:40 server time.

Round was on a downstream, sorry. #6427 on RussStation, melbert may have access there?
Will try to reproduce locally as well, but sounds like this has been an issue for a while.

## Testmerges:
N/A

## Reproduction:
Load up as a pAI and do the *collapse emote.
I was in a holochassis, but I'm not sure you can even do the emote outside of one.
Admin said IsUnconscious was returning 0 for me.
They also said they noticed a signal `COMSIG_LIVING_STATUS_UNCONSCIOUS` was being sent, but nothing seemed to be listening for it.

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=cwCtM6D4GOc

**Comment by LemonInTheDark** [comment]
Does this behavior replicate on our codebase?

**Comment by lucigoosi** [comment]
Just confirmed, the issue is present on the tg codebase as well.
Manuel round #182889, pAI name was Luci, testing occurred around 19:40 server time.
Collapsed, then was unable to do anything other than toggle resting state. Had to be destroyed then deleted by the person helping me test.
