### ISSUE TITLE
MetaStation Mapping Helper Errors

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#66763]
## Reproduction:

![image](https://user-images.githubusercontent.com/34697715/167241852-8da66503-c70f-4f55-8a7d-37974dcdbd1f.png)

If you go in any CI Run (which loads MetaStation), this slew of issues come up. Please look into this to ensure errors stop erroring, probably just a misconfiguration when we swapped over to mapping helpers with #66588.

#66756 _might_ fix a few of these instances, but there's a few like the Medbay General one that should definitely be looked into.

You can also find this out on your local by doing the following:

In order to find this out on your local, you must first compile and boot into MetaStation. Then, once Initialization is complete, use the verb get-current-logs and go down to map_errors.log. From there, download that log, and open it up in a text editor like Notepad++. You should see that, and other map errors we encountered loading the map.

**Comment by Son-of-Space** [comment]
I will fix this tomorrow.
