### ISSUE TITLE
Meta Library Maints require access other than maints

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#66799]
Reporting client version: 514.1583

## Round ID:
[182842](https://scrubby.melonmesa.com/round/182842)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)

## Reproduction:
Try to use either of the maints doors connecting to the library on deltastation as someone with maints access.
The doors dont open, despite only being connected to maints and public parts of the library.
![image](https://user-images.githubusercontent.com/44104681/167317174-dcafe2c0-6c42-4ada-93de-a0b85cea8276.png)
![image](https://user-images.githubusercontent.com/44104681/167317180-3a98de35-2bdc-4ac1-9aaf-b2a9ab536d1b.png)

**Comment by BlueMemesauce** [comment]
It was probably caused by this #66521

**Comment by Son-of-Space** [comment]
This looks like it is MetaStation, not Deltastation, and this is intentional. These doors are technically owned by the librarian and thus are only accessible with library access.

**Comment by Son-of-Space** [comment]
Either way once I go through the maint accesses on Delta and replace them with mapping helpers, this will stay the same.

**Comment by VladinXXV** [comment]
> This looks like it is MetaStation, not Deltastation, and this is intentional. These doors are technically owned by the librarian and thus are only accessible with library access.

You're right about it being meta, I dunno why I got them mixed up. But I don't see your point with the technicality. They're connected to public sections of the library and maints. Why make separate maints and public areas with an access not required to get into either area normally?
