### ISSUE TITLE
shutters no longer get brought along with the tram

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#66790]
## Round ID:
[Round ID]: # 182776

## Testmerges:

likely caused by #66657 

## Reproduction:

build shutters on tram
click tram move button
shutters float in air
move tram back to shutters
shutters get destroyed by tram

https://user-images.githubusercontent.com/54422837/167283525-3577d56d-be21-4372-bf30-faf5952a57c8.mp4

**Comment by dragomagol** [comment]
I suspect this was from
