### ISSUE TITLE
Cannot progress on abandoned station due to lack of griddle/ancient protolathe cost requirements

### ISSUE THREAD

**Issue by OWD9000** [tgstation/tgstation#66792]
## Round ID:
[182807](https://scrubby.melonmesa.com/round/182807)

## Testmerges:
[#65997: 'Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)' by Mothblocks at commit cef54eeb19](https://www.github.com/tgstation/tgstation/pull/65997)
[#65791: 'Optimizes Runechat' by Kylerace at commit c92148ea79](https://www.github.com/tgstation/tgstation/pull/65791)

## Reproduction:
1. Spawn into a cryopod ghost role on the abandoned station.
2. Attempt to cook/process xeno/carp meat in a way that yields edible food (microwave cannot cook meat anymore)
OR
2. Attempt to print anything from the ancient protolathe (10 credits required per print for all roles: security, engineer, scientist. No credits present on spawning ID cards and no coins or coin production available to add credits to ID card)

**Comment by ArcaneMusic** [comment]
Do you know if this was before or after #66566 was merged?

**Comment by Son-of-Space** [comment]
I will add a griddle to charliestation.
