### ISSUE TITLE
Supply shuttle runtime that resulted in purchases not spawning on supply shuttle

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#66808]
Reporting client version: 514.1583

## Round ID:
[182853](https://scrubby.melonmesa.com/round/182853)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Makes it possible to speed up the tram](https://www.github.com/tgstation/tgstation/pull/66348)
- [Fix granular admin ranks not being loaded from DB](https://www.github.com/tgstation/tgstation/pull/66706)

## Reproduction:

Not sure how you'll reproduce it ; the player reported purchasing crates and them not making it there.  I spawned in at CC and ordered various sundries like donk pockets, none of the items spawned on the supply shuttle, however the mail bin thing did.

Checking runtimes revealed this likely culprit ; there are others in this round too

```
[2022-05-09 03:30:11.205] runtime error: list index out of bounds
 - proc name: buy (/obj/docking_port/mobile/supply/proc/buy)
 -   source file: supply.dm,164
 -   usr: null
 -   src: the supply shuttle (/obj/docking_port/mobile/supply)
 -   src.loc: the plating (152,108,1) (/turf/open/floor/plating)
 -   call stack:
 - the supply shuttle (/obj/docking_port/mobile/supply): buy()
 - the supply shuttle (/obj/docking_port/mobile/supply): initiate docking(Transit for supply/supply shut... (/obj/docking_port/stationary/transit))
 - the supply shuttle (/obj/docking_port/mobile/supply): enterTransit()
 - the supply shuttle (/obj/docking_port/mobile/supply): check()
 - Shuttle (/datum/controller/subsystem/shuttle): fire(0)
 - Shuttle (/datum/controller/subsystem/shuttle): ignite(0)
 - Master (/datum/controller/master): RunQueue()
 - Master (/datum/controller/master): Loop(2)
 - Master (/datum/controller/master): StartProcessing(0)
```

**Comment by timothymtorres** [comment]
Pretty sure this is from #66230 when we were testing we had this problem but I thought it was fixed.  Apparently not.
