### ISSUE TITLE
Anything other than the proto kinetic acceleator does not increase the mining skill

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#66826]
I did a bit of testing when I found it odd that my crusher was not giving me any mining skull increase. I printed a advanced plasma cutter, an upgraded resonator, and bought a pka.  Out of those, the only tool to increase my mining skill when mining rocks and ores was the PKA

**Comment by TemporalOroboros** [comment]
IIRC this is intended with that toolset. Mining skill is restricted to the pka and pickaxes/drills/the sonic mining tool to help try to balance them against the plasma cutters and resonator.

**Comment by Sealed101** [comment]
pickaxes drills and pka, maybe survival pens and spoons, other methods aren't supposed to give mining xp

**Comment by magatsuchi** [comment]
intended behavior (because coders hate miners)
