### ISSUE TITLE
Fireman-carry through doorways causes a visual bug.

### ISSUE THREAD

**Issue by orthography** [tgstation/tgstation#66833]
## Round ID: 
Irrelivant

## Reproduction:
Fireman carrying someone through a door to which you have ID access, but the person being carried does not, will cause both door touch sounds (opening and access denied) and will briefly open the door before showing the sprite for a closed door. The door can still be entered. This issue #[56420](https://github.com/tgstation/tgstation/issues/56420)  mentions it but there was no further resolve of it.

**Comment by magatsuchi** [comment]
since #56420 is still open, i'm going to close this for being a duplicate, but ill go ahead and take a look at the code
