### ISSUE TITLE
the lightning bolt spell only grants its tesla immunity if you learn it from a spellbook

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#66845]
this means that if you receive the spell directly from an admin instead of from a wizard spellbook, you'll be able to electrocute yourself with it, making the spell way worse than it's intended to be.

also, I'd bet an internet cookie that using lightning bolt as a wizard while shapeshifted will result in you electrocuting yourself, due to only your humanoid body receiving the tesla immunity from learning the spell. sadly, I don't think this can be abused with ED-209 form, because the supercharging of secbots when they get electrocuted looks like it'd only apply to automated bot movement (which is probably a bug/oversight of its own, but I digress).

**Comment by magatsuchi** [comment]
even if this is intended behavior it should be changed (point fingers at @tralezab)
