### ISSUE TITLE
Sentience potion notifications not appearing even with it enabled in prefs

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#66867]
Reporting client version: 514.1583

## Round ID:
[182946](https://scrubby.melonmesa.com/round/182946)

## Testmerges:
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)

## Reproduction:
This is an issue i've been having for a while now which also seems to affect lavaland elite. But the notifications just will not show up whenever someone offers the potion.
https://gyazo.com/11946920f19ee719c5831d9714203533
All prefs are enabled, nothing pops up.

**Comment by dragomagol** [comment]
Duplicate of #63092

**Comment by dragomagol** [comment]
As I understand it, if your sentience potion pref is set to "Off", you won't see any of these popups regardless
