### ISSUE TITLE
Plasmamen burn if delimbed (assuming its the "without gloves" check) even if wearing a firesuit

### ISSUE THREAD

**Issue by RandomGamer123** [tgstation/tgstation#66865]
## Round ID:
[182944](https://scrubby.melonmesa.com/round/182944)

## Reproduction:
1. Be a plasmeme wearing a full-body covering suit (eg. firesuits)
2. Delimb yourself (not sure if taking off your gloves works)
3. Notice that you're on fire despite having all your body parts logically covered

I assume its related to kapulimbs

**Comment by dragomagol** [comment]
![image](https://user-images.githubusercontent.com/66640614/167746908-708502ea-b720-4c48-aa77-c6477031b5bc.png)

**Comment by RandomGamer123** [comment]
@dragomagol turns out this is a bug but not caused by kapulimbs or even the gloves check in specific, what should have happened was the firesuit should have made plasmemes pressure proof and therefore atmos_sealed (with an appropriate helmet), but #66114 accidentally reversed a check for `CanIgniteMob`
Original:
```
	var/atmos_sealed = CanIgniteMob(H) && (isclothing(H.wear_suit) && H.wear_suit.clothing_flags & STOPSPRESSUREDAMAGE) && (isclothing(H.head) && H.head.clothing_flags & STOPSPRESSUREDAMAGE)
```

New:
```
	var/atmos_sealed = TRUE
	if(CanIgniteMob(H))
		atmos_sealed = FALSE
	else if(!isclothing(H.wear_suit) || !(H.wear_suit.clothing_flags & STOPSPRESSUREDAMAGE))
		atmos_sealed = FALSE
        (more stuff below)
```

This meant that unless you had TRAIT_NOFIRE (ie. CanIgniteMob false), you would not be "atmos sealed", so you will catch on fire even when you aren't supposed to

**Comment by RandomGamer123** [comment]
(Screenshot from private server running revision 8471d1216f73502524551d00b5b42db6829d6bf8, before #66144 was merged)

![ThingAN1936-pre66144img3](https://user-images.githubusercontent.com/31096837/168494524-b6667dbf-4a55-48c3-a5c3-1bc30740dedf.png)
