### ISSUE TITLE
Circuit Triggers straight up dont work, dog

### ISSUE THREAD

**Issue by TheSmallBlue** [tgstation/tgstation#66870]
## Testmerges: 
#65997 #65791 

## Reproduction:
1. Grab any component that uses a trigger for activation
2. Try to trigger it in any way, either via click or a remote or a radio, any way.
3. See how the component does not, in fact, get triggered

https://user-images.githubusercontent.com/24967815/167743791-6efe9f03-0e2a-45e2-9e70-46ecd223c182.mp4

https://user-images.githubusercontent.com/24967815/167743800-2f9464c1-aa25-46b9-8a40-8ba4159d3cbe.mp4

**Comment by Comxy** [comment]
Did the circuit contain a battery?

**Comment by TheSmallBlue** [comment]
im a fucking idiot
