### ISSUE TITLE
AI camera stuck to lower tram

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#66887]
## Testmerges: 
#65997: 'Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)' by Mothblocks at commit 4ca83151e5
#66657: '(code bounty) The tram is now unstoppably powerful. it cannot be stopped, it cannot be slowed, it cannot be reasoned with. YOU HAVE NO IDEA HOW READY YOU ARE' by Kylerace at commit 8d1366783a

## Reproduction:  Be AI on tramstation with multi z level tram

Somehow get camera stuck on lower tram level
[ the camera was moving horizontally with the tram whenever it moved, even if i was tracking something else or even on a different z level ]

Admin fixed it and said i was in the trams list of things to move but only on the lower tram

tram moment

**Comment by Kylerace** [comment]
Camera mobs need to be added to the ignore blacklist in AddItemOnLift(). I'm 99% sure this is a problem on master since I don't think I changed that list in the tm

**Comment by Kylerace** [comment]
should be fixed as part of latest commit
