### ISSUE TITLE
Cult abilities overwrite each other

### ISSUE THREAD

**Issue by Edelor68** [tgstation/tgstation#66894]
## Reproduction:
1. Get first cult ability without empowering rune and then more with the rune
2. Remove runes by going over your limit
3. Im not sure what triggers it but often when you get new runes they will replace old ones even if you dont have the max number OR it will tell you that you have the maximum number even if less abilities are shown (Im assuming here that some have gone invisible because the abilities I did have were shifted and there was just empty space where normally the button for the first ability is) OR sometimes nothing will happen and with a bit delay one random ability will be replaced but keep the icon of the one that came before.

While this was happening the server was lagging out and crashed 2 times so maybe that had something to do with it.

**Comment by Palpetinus** [comment]
What might have happened is that the buttons for new abilities simply appeared over the old ones, happened constantly to me yesterday. Always check "under" the buttons first.

**Comment by msgerbs** [comment]
This almost constantly happens to me, cult spells are incredibly fucked. Don't even need to be actively adding new spells, sometimes they just disappear at random.
