### ISSUE TITLE
Using the biogenerator completely drains the apc of whatever room it's in

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#66919]
## Testmerges:
The following pull requests are currently test merged:
[#65791: 'Optimizes Runechat' by Kylerace at commit 0ee9ccf62b](https://www.github.com/tgstation/tgstation/pull/65791)
[#65997: 'Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)' by Mothblocks at commit 4ca83151e5](https://www.github.com/tgstation/tgstation/pull/65997)

## Reproduction:
also observed in a previous round
turn on the biogenerator
botany/the service corridor completely loses power
curse ghilker's name

**Comment by newfren** [comment]
I realised this might be unclear - by "turn on" I mean grind. printing shit is fine

**Comment by fippefi** [comment]
grinding uses 2kW per item inside it so 10 melons is the full powercell

**Comment by fippefi** [comment]
this is kind of obscenely high in energy cost
