### ISSUE TITLE
Moths can eat Traitor Objectives

### ISSUE THREAD

**Issue by fippefi** [tgstation/tgstation#66923]
## Round ID:

If you discovered this issue from playing tgstation hosted servers:
[Round ID]: 183028

## Testmerges:

probably not

## Reproduction:

be a moth traitor tot
bug CE's magboots
cash out tot bug bounty
eat CE's magboots
???
no evidence

To clarify, during the round the magboots were bugged by someone else and I just found them in CE's office while breaking in, and ate them. I think various clothing items that are objectives probably should be blacklisted from moth eating, it's funny though.

**Comment by magatsuchi** [comment]
wyci

**Comment by rdragan** [comment]
Ok and? You can deep fry anything and anyone can eat it. You can throw anything into the SM. The only indestructible items on the station are nuke disks and bar bot portals.

**Comment by magatsuchi** [comment]
> Ok and? You can deep fry anything and anyone can eat it. You can throw anything into the SM. The only indestructible items on the station are nuke disks and bar bot portals.

this is more a matter of it being unreasonably easy for a moth to completely fuck a tot over with nothing but their mouth

**Comment by ArcaneDefence** [comment]
Moths eating tot objectives normally doesn't do any damage to the object.
The only thing I can initially think of is that bugging it changes something

**Comment by private-tristan** [comment]
> Ok and? You can deep fry anything and anyone can eat it. You can throw anything into the SM. The only indestructible items on the station are nuke disks and bar bot portals.

because such items were made specifically to be much harder to destroy, for example HoS lasgun isn't able to be deepfried, or shuttlegibbed, or burnt by lava, so you need to seek out specific methods to destroy it (SM and cremate)
