### ISSUE TITLE
Dead Mouse bounty still available - but only for mimes (and probably clowns)

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#66936]
Reporting client version: 514.1582

## Round ID:
[183053](https://scrubby.melonmesa.com/round/183053)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)

## Reproduction:
Recent changelog said that dead mouse, sunglasses, and suitcase bounties were removed from assistant bounty list, but dead mouse bounties, at least, are still available if you're a mime or presumably a clown, who otherwise share lists with assistants. Unsure if this is intentional or not, the removals felt like they were to account for those items being increasingly rare, and the theatre crew are even less likely than assistants to be able to get dead mice.

![quiet sadness]
![quiet sadness](https://user-images.githubusercontent.com/88996803/168188986-f65b5cef-3f0d-4439-8e41-c0874135a231.png)

**Comment by Zonespace27** [comment]
Not really a bug, I forgot to remove the dead mice bit from the changelog

**Comment by Mooshimi** [comment]
I saw a secoff doing this bounty yesterday, felinid.
