### ISSUE TITLE
Solid plasma can be broken into plasma glass shards

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#66977]
## Reproduction:
combat mode, click floor with plasma sheets
![obraz](https://user-images.githubusercontent.com/68878861/168440341-acb38499-5fd0-484f-8ec8-38e0c8f3a6f8.png)

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/e657e6c4f7c7aeef50c7495009708a758bb0da7a/code/game/objects/items/stacks/sheets/sheets.dm#L25-L48

https://github.com/tgstation/tgstation/blob/e657e6c4f7c7aeef50c7495009708a758bb0da7a/code/game/objects/items/stacks/sheets/mineral.dm#L150-L172

Just to double check, it was the plasma bars you get from the ore redemption machine at cargo right?  Not the plasma glass sheets?

**Comment by Likteer** [comment]
@timothymtorres Yes, plasma bars. I used in-game wording and provided a screenshot so there wouldn't be any doubt. Also, I think this is a bug, not a consistency issue. Pure plasma is obviously not made out of it's alloy with glass.
