### ISSUE TITLE
Pepper spray cannot stop zombies.

### ISSUE THREAD

**Issue by notfrying1pans** [tgstation/tgstation#66982]
## Round ID:

[Round ID]: #183132

## Testmerges:

#65791 
#65997 

## Reproduction:

* Pepper spray a zombie
* Watch as the zombie collapses
* Get attacked by downed zombie regardless

**Comment by timothymtorres** [comment]
I don't think this is a bug.  Zombies are OP and immune to stuns.

**Comment by notfrying1pans** [comment]
i checked on the wiki before reporting this and it didnt say anything about stuns, someone should update the wiki im too tired to

**Comment by private-tristan** [comment]
zombies only take 20% stuns if im reading it correctly

 > /datum/species/zombie/infectious/spec_stun(mob/living/carbon/human/H,amount)
	. = min(20, amount)
	
also pepperspray doesn't stun in the first place

	

>if (!(pepper_proof)) // you need both eye and mouth protection
if(prob(5))
victim.emote("scream")
victim.blur_eyes(5) // 10 seconds
victim.blind_eyes(3) // 6 seconds
victim.set_timed_status_effect(5 SECONDS, /datum/status_effect/confusion, only_if_higher = TRUE)			victim.Knockdown(3 SECONDS)
victim.add_movespeed_modifier(/datum/movespeed_modifier/reagent/pepperspray)
addtimer(CALLBACK(victim, /mob.proc/remove_movespeed_modifier, /datum/movespeed_modifier/reagent/pepperspray), 10 SECONDS)
victim.update_damage_hud()

**Comment by notfrying1pans** [comment]
OH LOL

**Comment by timothymtorres** [comment]
@private-tristan you should checkout how to [link code](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet) properly.  It's very helpful for the issue tracker.  See:

https://github.com/tgstation/tgstation/blob/5326ab26c48f78e732d6df3905d38e5dd06b200c/code/modules/mob/living/carbon/human/species_types/zombies.dm#L96-L97

https://github.com/tgstation/tgstation/blob/a7070d7ee3942c103047024aaf56f74e1a7f866c/code/modules/reagents/chemistry/reagents/food_reagents.dm#L351-L371
