### ISSUE TITLE
you can knockdown monkeys by walking into them even if you can't walk into them

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#66983]
## Testmerges:

irrelevant

## Reproduction:

have money on same tile as a window
on the other side of window
walk into window
get stopped by window
monkey falls down

https://user-images.githubusercontent.com/54422837/168441701-76130e1d-3a31-48ad-9735-72ba8eb23a6a.mp4

**Comment by ArcaneDefence** [comment]
we like directional windows

**Comment by itseasytosee** [comment]
You can also trip monkeys as a revenant by flying overtop of them. Revert monkeys to not be a human subtype please :(
