### ISSUE TITLE
Tramstation needs a large atmos look-over

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#66984]
Reporting client version: 514.1581

## Round ID:
[183139](https://scrubby.melonmesa.com/round/183139)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)

## Reproduction:
Lots of areas on Tramstation are sectioned off with firelocks without having a scrubber + vent combination, resulting in horrible horrible things happening during breaches or when engineering uses Draught to fix cold/overheated areas. Notable areas include:

All of the hallways on either side of departments:
![image](https://user-images.githubusercontent.com/81882910/168441405-11bf8b39-a0f3-40e9-9ee3-902fbce159d3.png)
![image](https://user-images.githubusercontent.com/81882910/168441409-4aecd6d5-50ce-4a13-ba13-bfa33f40cf20.png)
The funny ring around medical:
![image](https://user-images.githubusercontent.com/81882910/168441401-8678d3ab-89a1-438f-9f66-6424c8084e2f.png)
Science stairs towards AI sat:
![image](https://user-images.githubusercontent.com/81882910/168441499-87526118-c8b6-47b9-aeca-7c2a69ae1c4b.png)

**Comment by MMMiracles** [comment]
there was only like 3 other areas listed that wasn't photographed and 2 of them were double doored areas fr*ck u
