### ISSUE TITLE
Tramstation - Shaftminer cannot open cargo doors.

### ISSUE THREAD

**Issue by Dsiwarper** [tgstation/tgstation#67015]
Reporting client version: 514.1583

## Round ID:
[183199](https://scrubby.melonmesa.com/round/183199)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)

## Reproduction:

Shaft Miner, also, new account for new username, on tramstation.

Door on upper Y level leading to the ORM could not be opened, did not have access on Shaft Miner ID. Other cargo doors were inaccessible too. 
Was also dragging Ore Box, if relevant, thought tried without, same result.

Admin (Riggle) opened the door temporarily so I could access the ORM. (yellow lights on door.)

**Comment by san7890** [comment]
This should have been fixed by #67025.
