### ISSUE TITLE
Ethereal reviving while being buckled to a borg creates a clone of your corpse and glitches you into the floor

### ISSUE THREAD

**Issue by maxspells** [tgstation/tgstation#67010]
## Round ID: 
N/A (downstream Fulpstation round:20241)

## Reproduction:

While dead and being buckled to a borg, the ethereal revival crystal was spawned on my tile, while a separate corpse was still buckled to the borg. I revived normally in the crystal, but was unable to stand up or be dragged or moved from the tile. Even admin intervention wasn't able to fix the issue through aheals, and I ended up having to be ghosted and spawned back in to fix the issue.

**Comment by MrMelbert** [comment]
Happened to me too, while buckled to a roller bed. ~~Ethereal Revive was a mistake~~

**Comment by Palpetinus** [comment]
Might be the same bug that also caused mine (#66656), did the borg/roller bed move while the crystal formed?
Maybe buckling is an entire new can of worms..
