### ISSUE TITLE
'Make AI' button in VV dropdown does not work

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#67028]
Reporting client version: 514.1583

## Round ID:
[183219](https://scrubby.melonmesa.com/round/183219)

## Testmerges:
- [refactors statpanel to use tgui API](https://www.github.com/tgstation/tgstation/pull/66971)
- [Adds Cargorilla](https://www.github.com/tgstation/tgstation/pull/67003)
- [Fuck it, we ball. Adds a very simple balling skill and minorly reworks dunking and shooting, adds ball stealing](https://www.github.com/tgstation/tgstation/pull/66960)

## Reproduction:

![xtnrhTOJwz](https://user-images.githubusercontent.com/37246588/168502821-aa5898eb-2409-46a2-8b72-fc6ffe01616c.png)

player in question was in thunderdome, spawned in as a human, and had already been an AI earlier in the shift. I was also human in the tdome.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/70faa854b47fe784bb863e78a5b3a68f8464ab54/code/modules/mob/living/carbon/carbon.dm#L1065
