### ISSUE TITLE
Foam goes through airlocks with impunity

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#67026]
## Round ID:
Reproduced on local

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/168500448-0d8b8c82-5874-4fb2-9d96-eb4df7928fb5.png)

![image](https://user-images.githubusercontent.com/66640614/168500580-91941282-e16a-48a1-9cc7-e0dc23fdab65.png)

This seems like an oversight, you can't hide from foam behind doors that lock out the void of space.

**Comment by TemporalOroboros** [comment]
For some reason foam uses a "where can I go with the access I have" proc to determine whether it can spread to an adjacent tile. This means it can spread through public access doors.

**Comment by Palpetinus** [comment]
> For some reason foam uses a "where can I go with the access I have" proc to determine whether it can spread to an adjacent tile. This means it can spread through public access doors.

Don't mind the foam just casually swiping its foam ID on the door
