### ISSUE TITLE
you can get many uses out of one molotov by catching it

### ISSUE THREAD

**Issue by dox-net** [tgstation/tgstation#67033]
## Round ID:
[183232](https://scrubby.melonmesa.com/round/183232)

## Testmerges:
#66971
#67003

## Reproduction:
craft molotov
light molotov
throw at person with throw intent on so they catch it
they get lit on fire and catch it
they can then throw it again and it will light fire again
you can repeat the catching and throwing over and over again for many fires from one molotov

**Comment by Shadowflame909** [comment]
Should be a bug that becomes a feature

>Catches the molotov which leaves somes fluid to set another person on fire with
