### ISSUE TITLE
Random Lavaland rock tile in Icebox

### ISSUE THREAD

**Issue by Krentell** [tgstation/tgstation#67046]
## Round ID:
[183256](https://sb.atlantaned.space/rounds/183256)

## Testmerges:
https://github.com/tgstation/tgstation/pull/65997
https://github.com/tgstation/tgstation/pull/65791
https://github.com/tgstation/tgstation/pull/67003

## Reproduction:
Icebox round, as a ghost a single Lavaland rock tile was found amidst the mountainside ones, near the edge of the z-level, outside the contained Lavaland area where the Last Ash Drake is.
Screenshot below:
![Screenshot_1](https://user-images.githubusercontent.com/81385366/168653734-18894df2-0f6a-4334-8b5a-f6585a01791a.png)

**Comment by Son-of-Space** [comment]
I checked this out on the map proper. Scanned the entire area up there on all three levels for rogue tiles and areas, searched on the browser for lavaland turfgen areas, and couldn't find anything. This is very likely a bug related to turfgen.

**Comment by private-tristan** [comment]
![image](https://user-images.githubusercontent.com/54422837/173280923-6d738fb7-5df3-4b0d-9325-158c275076e6.png)
round 184818
