### ISSUE TITLE
Slimes dont feed on monkeys

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#67041]
Reporting client version: 514.1583

Slimes dont feed on monkeys at all

## Round ID:
[183250](https://scrubby.melonmesa.com/round/183250)

## Testmerges:
- [Adds Cargorilla](https://www.github.com/tgstation/tgstation/pull/67003)
- [(code bounty) The tram is now unstoppably powerful. it cannot be stopped, it cannot be slowed, it cannot be reasoned with. YOU HAVE NO IDEA HOW READY YOU ARE](https://www.github.com/tgstation/tgstation/pull/66657)

## Reproduction:

1. Give a monkey to a slime
2. Observe as the slime does not interact with the monkey or feed on it

**Comment by SuperNovaa41** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/67034
