### ISSUE TITLE
Manifests being marked incorrect even when correct

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#67043]
Reporting client version: 514.1583

## Round ID:
[183256](https://scrubby.melonmesa.com/round/183256)

## Testmerges:
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Adds Cargorilla](https://www.github.com/tgstation/tgstation/pull/67003)

## Reproduction:
Confirm contents of a crate
Stamp manifest
Send back
Lose money

The false manifest shown here came from engineering using their free orders console to order a BZ canister, which I saw with my own eyes. You can't tell me I got that wrong.
![image](https://user-images.githubusercontent.com/44104681/168653042-35bec94b-e7be-4d3c-924a-cbb6f7a5cc72.png)

I've also seen this happen with manifests for orders made using the cargo budget, rather than departmental orders, so it isn't exclusive to those.

**Comment by MrMelbert** [comment]
![image](https://user-images.githubusercontent.com/51863163/168656511-da21450b-b05c-4180-be48-09366dbe3e8b.png)

**Comment by MrMelbert** [comment]
I wonder if dynamically generated cargo packs (gas canisters) are having issues in confirming their contents.

**Comment by Sealed101** [comment]
spiked the error chance up to 100, ordered several canisters, got multiple missing contents errors, contents were indeed missing _in the manifest_, stamped them denied and sent the canisters back, got the credits back. either it got fixed or you didn't read the manifest close enough? for what it's worth, department orders don't get errors at all as of https://github.com/tgstation/tgstation/pull/78923
