### ISSUE TITLE
Items in Suit Storage STILL Turning Invisible

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#67048]
Reporting client version: 514.1583
## Round ID:
[183256](https://scrubby.melonmesa.com/round/183256)

## Testmerges:
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Adds Cargorilla](https://www.github.com/tgstation/tgstation/pull/67003)

## Reproduction:
Wear something with suit storage.
Put something it can hold into the suit storage.
It MAY or may not turn invisible.

I've noticed #66875 definitely REDUCED instances of this, but it still happens. It happened during the linked round with putting a mosin on a standard armor vest, and I have images from a previous round (where the server HAD been updated, according to CL), showing it happening with the CMO labcoat and an Advanced Health Analyzer (~22hrs ago, Manuel).
![image](https://user-images.githubusercontent.com/44104681/168668401-f6aaaad2-166a-4a4e-876f-cd6ff0d0d5ed.png)
![image](https://user-images.githubusercontent.com/44104681/168668431-a0770c48-8a53-4362-9eab-2e0a0c2a75f4.png)

**Comment by RCWLam** [comment]
Noticing this happening a lot when initially spawning into the round with something in the vest storage slot, Energy disablers as sec and penlites as medstaff explicitly.

**Comment by DomitiusKnack** [comment]
Noticing this happening a lot when initially spawning into the round with something in the vest storage slot, Energy disablers as sec and penlites as medstaff explicitly.

**Comment by Nabski89** [comment]
Had this happen to me in round 184243. https://imgur.com/cETfjJ2 A picture of it not showing up in my inventory. Admin confirmed that it was in the suit slot.

**Comment by Fhaxaris** [comment]
Still happening

**Comment by notfrying1pans** [comment]
[psst](https://github.com/pariahstation/Pariah-Station/pull/768)
