### ISSUE TITLE
Warp whistle ignores your location

### ISSUE THREAD

**Issue by JohnFulpWillard** [tgstation/tgstation#67054]
## Reproduction:

1. Use a warp whistle
2. Move away from the warp whistle
3. You move anyways

This makes the warp whistle (the cheapest item in the spellbook), the best way to escape security, since you can use it and have some time to do whatever you want before you 100% get a free and unavoidable getaway.
Moving (or being moved) out of the way of the warp whistle will not prevent the teleporation.

**Comment by Iamgoofball** [comment]
``Move away from the warp whistle``
this is a bug, you're not supposed to be able to move while using the warp whistle

![chrome_HDxZg0rgcQ](https://user-images.githubusercontent.com/4081722/168753373-904d3b16-332c-4e57-bb76-e1df1a602cee.png)


fix TRAIT_IMMOBILIZED not working

**Comment by timothymtorres** [comment]
@Iamgoofball I'd recommend [linking the code](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet) properly like so:

https://github.com/tgstation/tgstation/blob/a4dca96f15760fbc95df4f2ec13185e588fde9f2/code/modules/antagonists/wizard/equipment/artefact.dm#L323-L338
