### ISSUE TITLE
Because antimagic blocks the use of spells, chaplain is unable to use their roundstart Smoke spellbook without dropping their nullrod.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#67055]
Reporting client version: 514.1583

## Round ID:
[183270](https://scrubby.melonmesa.com/round/183270)

## Testmerges:
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Adds Cargorilla](https://www.github.com/tgstation/tgstation/pull/67003)

## Reproduction:

A fun little oversight involving antimagic and job gear.

As of recent changes, anyone who is immune to magic also happens to be unable to cast their own spells. This is fine and all, but it seems it has unintentionally messed with the chaplain's Smoke spell that can be found in the chapel office on most maps. As long as the nullrod is in their possession, they can't use the spell at all. I dunno about you, but I don't think most chaplains would drop their nullrod just so they can spew a bit of smoke. 

Small little oversight for a small spell, but I wonder if it's even worth making a workaround. Still, might as well record this here.

EDIT: I'm also told Blind didn't work with this as well.

**Comment by ATH1909** [comment]
this definitely wasn't a thing a few months ago

are wizard modsuits affected?

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/f37b17979383263ed7f2b4a7217d6dd8670b4408/code/modules/spells/spell_types/wizard.dm#L71-L87

The `antimagic_flag` is set to `NONE` and I'm pretty sure we tested this to make sure it worked. (we did this on mime spells and chaplain's smoke)

https://github.com/tgstation/tgstation/blob/bea938745876492ddd7d41a61711b26ec72d2f08/code/modules/mob/mob.dm#L902-L913

Looks like #65281 changed how smoke in spells work recently.  That might be it.
