### ISSUE TITLE
cant reply to PDA messages through chat

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#67063]
Reproduce: Receive a PDA message. Try to reply with the button in the chatbox. Does not work.
You gotta open up your tablet, go to messages and then reply that way. Much slower.

Related PRs: No idea I'm gonna guess this one
https://github.com/tgstation/tgstation/pull/66505

**Comment by rasepretep** [comment]
It works, but you have to have the PDA / messaging up running first, by opening it up in your PDA at least once.

**Comment by MrMelbert** [comment]
As rasep said, it only lets you hotlick reply if you've opened the messaging system once per shift

Also the ringtone doesn't work if you haven't opened the app at least once, and it runtimes to heck
