### ISSUE TITLE
Stop Drop and Roll Doesn't Save Your Clothes

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#67077]
Reporting client version: 514.1583

## Round ID:
[183300](https://scrubby.melonmesa.com/round/183300)

## Testmerges:
- [Adds Cargorilla](https://www.github.com/tgstation/tgstation/pull/67003)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)

## Reproduction:
Get set on fire.
Resist to stop drop and roll until the fire is out.
Watch your clothes continue to burn and be destroyed AFTER you've already put yourself out.

Seems like an oversight to me. If clothes on my body are still burning, why am I not burning myself? It's bizzare that you need an extinguisher to save clothes, and it fucks you over in situations where you can't get an extinguisher, such as being on the escape shuttle or while handcuffed.

**Comment by necromanceranne** [comment]
@SmArtKar
