### ISSUE TITLE
Placing bugs with the stealth implant deployed lets you move the bug's location, even outside the given area

### ISSUE THREAD

**Issue by RazorManager89** [tgstation/tgstation#67078]
## Reproduction
Accept a progtot bug objective. Take the bug. Get to the area. Deploy the stealth implant. Place the bug. Get out of there, some place far away. Get out of your box. 
The bug will be exactly where you got out of the box and nowhere near the area where you were meant to place it, but the objective will still count as completed.
![image](https://user-images.githubusercontent.com/37266586/168867030-edc7e87d-b34e-4e1d-bd9e-49882b5c5abc.png)
![image](https://user-images.githubusercontent.com/37266586/168866911-2e43f4a7-40f6-4e4e-9834-1a8b6834850b.png)

**Comment by JohnFulpWillard** [comment]
Bugs no longer exist
