### ISSUE TITLE
Admin-Spawned Door Remotes do not Work

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#67085]
Reporting client version: 514.1583

## Round ID:
[183318](https://scrubby.melonmesa.com/round/183318)

## Reproduction:

If you spawn in a door remote they'll get this issue: Error: network_error_bad_receiver_id  and won't work. Roundstart ones work fine.

**Comment by lizardqueenlexi** [comment]
This no longer appears to be the case - admin-spawned door remotes work fine.
