### ISSUE TITLE
Moth body parts are not rendered correctly on the preferences menu

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#67092]
Round ID was 183338, post @Kapu1178 's limbs.

Moths in the preferences menu do not render their head appropriately.

Old:

![image](https://user-images.githubusercontent.com/35135081/168956296-bbb96e9b-6e36-4bc9-980f-249140af52f0.png)

New:

![image](https://user-images.githubusercontent.com/35135081/168956314-9802ae72-6158-4ed1-927c-3767f3058a53.png)
![image](https://user-images.githubusercontent.com/35135081/168956322-e475f3fe-4d7e-41c2-a10d-91529339d117.png)

**Comment by itsmeow** [comment]
Fixed in https://github.com/BeeStation/BeeStation-Hornet/pull/8776

**Comment by itsmeow** [comment]
https://github.com/tgstation/tgstation/milestone/63

**Comment by Mothblocks** [comment]
FYI that milestone is only for regressions from pre-tgui prefs menu to new one, I should make that more clear

**Comment by itsmeow** [comment]
Oh. Tracking post prefs PRs would be useful.
