### ISSUE TITLE
Tree cutting doesn't work with chainsaws and eswords don't need to be on

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#67094]
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
![image](https://user-images.githubusercontent.com/51932756/168963070-3ca218c6-15a6-490c-98ab-f06a3e8ab50d.png)
Spawn a tree, a chainsaw, wield the chainsaw, and click it - it takes brute damage
Spawn a hatchet and click it - progress bar
Spawn an esword, pick it up, don't turn it on, click it - progress bar
https://github.com/tgstation/tgstation/blob/5d264fbea0124e5af511af3fed24203e196d108b/code/__DEFINES/flora.dm#L1

I hate refactors! I hate refactors!!

**Comment by Palpetinus** [comment]
But it works with a fucking SCREWDRIVER

**Comment by newfren** [comment]
this also doesn't work with crushers, which are big axes
