### ISSUE TITLE
Animals can pass through closed directional firelocks

### ISSUE THREAD

**Issue by notfrying1pans** [tgstation/tgstation#67109]
## Round ID:

[Round ID]: #183359

## Testmerges: 

#67003
#65791
#65997

## Reproduction:

* Go to Meta's garden 
* Watch as the animals eventually walk through the firelocks

**Comment by Sealed101** [comment]
seems to have been fixed somewhat somehow since i've made a firelock rage cage for a bunch of cows and chickens, left them for an hour and nobody managed to get out
