### ISSUE TITLE
Reinforced glass floor doesnt blur

### ISSUE THREAD

**Issue by tnekohue** [tgstation/tgstation#67110]
## Reproduction:

Get healed, or somehow otherwise obtain the fullscreen blur effect

![image](https://user-images.githubusercontent.com/17634568/169108193-098e9ca3-928a-4abc-b42a-2d3ce6f75ddb.png)

**Comment by dragomagol** [comment]
Layers my beloved

**Comment by LemonInTheDark** [comment]
https://github.com/tgstation/tgstation/blob/master/code/_onclick/hud/rendering/plane_master_controller.dm#L83
Likely caused by the plane not being in this list
