### ISSUE TITLE
Smoothies are invisible

### ISSUE THREAD

**Issue by PrivVi** [tgstation/tgstation#67120]
## Testmerges:

[#67003: 'Adds Cargorilla' by MrMelbert at commit 7c3f80913f](https://www.github.com/tgstation/tgstation/pull/67003)
[#65791: 'Optimizes Runechat' by Kylerace at commit a5738cd6f7](https://www.github.com/tgstation/tgstation/pull/65791)
[#65997: 'Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)' by Mothblocks at commit 7d029ad194](https://www.github.com/tgstation/tgstation/pull/65997)

## Reproduction:

Made "green giant smoothie" Using equal portions creme de menthe, milk, and lime juice. Poured it into a drinking glass, turning it invisible

**Comment by Sylphet** [comment]
**FUCK**

will fix this as soon as I get home
