### ISSUE TITLE
Wrenching a SM shard as a borg instantly kills you

### ISSUE THREAD

**Issue by techno0** [tgstation/tgstation#67130]
## Round ID:
183417

### **Right Click path**
- Be borg
- Have a wrench
- See Supermatter shard
- Press right click
- Borg instantly dies

### **Left Click path**
- Be borg
- Have a wrench
- See Supermatter shard
- Press left click 
- Borg instantly dies
- SM is wrenched to the floor

**Comment by MrMelbert** [comment]
@Ghilker Maybe a consequence of not returning "`COMPONENT_BLOCK_TOOL_ATTACK`" from the SM component on wrench
