### ISSUE TITLE
TGChat NToS Blue Screen

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#67147]
Reporting client version: 514.1583

## Round ID:
[183444](https://scrubby.melonmesa.com/round/183444)

## Testmerges:
- [Adds Cargorilla](https://www.github.com/tgstation/tgstation/pull/67003)
- [Biddle Verbs: Queues the Most Expensive Verbs for the Next Tick if the Server Is Overloaded](https://www.github.com/tgstation/tgstation/pull/65589)

## Reproduction:

![image](https://user-images.githubusercontent.com/34697715/169434536-42d0771a-53c5-4bec-b3ec-b4153f0aaaf1.png)

Apologies, I was in the middle of other things and didn't grab a good copy-paste of the issue. Other people reported this occuring, but restarting BYOND did clear it.

**Comment by CocaColaTastesGood** [comment]
Out of curiosity did anything weird pop up or happen near the end? I noticed that this happens when something tries to open a new window using js in tgui chat.

**Comment by san7890** [comment]
> Out of curiosity did anything weird pop up or happen near the end? I noticed that this happens when something tries to open a new window using js in tgui chat.

No? It just kept re-iterating UnhandledRejection errors until I rebooted BYOND. I was doing admin tickety stuff if that helps diagnose it.

**Comment by Mooshimi** [comment]
Repost of #65824. Please add any further details you have on the issue to #65824 .
