### ISSUE TITLE
broken proximity sensors in grenades

### ISSUE THREAD

**Issue by Magic101lvl** [tgstation/tgstation#67159]
## Reproduction:
Create a grenade, attach a sensor to it, put it in some kind of storage, and then put this storage in another storage. After these actions, even if you pull out a grenade and activate, it will not react to any movement and will never work. (Sometimes the sensor works if you walk where the grenade was placed in the storage twice in a row). A grenade bugged in this way cannot be dismantled due to the fact that it has not yet worked, but is already activated. All subsequent grenades to which motion sensors are attached also stop responding to any movement and become bugged even without manipulations with putting them in storage.

UPD: This happens when the tile is set to 0.

**Comment by robbertapir** [comment]
failed to reproduce

**Comment by exymian** [comment]
This happens when the tile is set to 0. Thats how you recreate it

**Comment by CPTANT** [comment]
I don't think this is just range zero. I think it also happens when you put an arming time or something else on the sensor.

**Comment by Magic101lvl** [comment]
Resolved

**Comment by CPTANT** [comment]
Resolved where, I don't see a PR linked
