### ISSUE TITLE
codedocs.tgstation13.org has the wrong link for `dmdoc 1.4.1`

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#67166]
![image](https://user-images.githubusercontent.com/34697715/169590334-98bf60a9-555d-493d-8907-08389784d450.png)

That button goes to the wrong link (errors 404), it's supposed to go to https://github.com/SpaceManiac/SpacemanDMM/tree/master/crates/dmdoc . I've no idea how to fix it, but end up catching a different issue when I did #67165.

**Comment by optimumtact** [comment]
this needs to be reported on the spacemandmm repo not here I imagine

**Comment by san7890** [comment]
They already fixed this back in https://github.com/SpaceManiac/SpacemanDMM/pull/301 , so I'm not sure why it's acting up here.

**Comment by optimumtact** [comment]
the version of spacemanDMM used for ci Tools will need updating to be aligned to the fixed version
