### ISSUE TITLE
Icebox service unknown requests console

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#67179]
Reporting client version: 514.1568

## Round ID:
[183503](https://scrubby.melonmesa.com/round/183503)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/169625896-479b1d0e-dca0-4e97-919f-17b82ebdfca1.png)

**Comment by fippefi** [comment]
actually affects far more request consoles than just this one; the prefab only sets name instead of the department which is renaming the requests consoles on mapload

**Comment by msgerbs** [comment]
Fixed by #67219
