### ISSUE TITLE
Aux base perimteter defense turrets don't target wildlife

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#67208]
## Round ID: 
[183593](https://scrubby.melonmesa.com/round/183593) (+ various before)

## Reproduction:
If this happened just in this instance I'd assume it's anti boss cheesing mechanic, but it happened before to me with regular wildlife before - I just forgot to capture it.

![obraz](https://user-images.githubusercontent.com/68878861/169690016-10f574c9-27df-4f22-93ae-169032816497.png)
(this is a result of a blind drop which made the drunkard appear inside of the base upon landing)

**Comment by timothymtorres** [comment]
Did you try setting up the turrets in open turf spots without windows or walls?

**Comment by Likteer** [comment]
> Did you try setting up the turrets in open turf spots without windows or walls?

Yes. Even if they are supposed to work in closed areas (but not as effectively), I frequently launched near empty bases with turrets in the corners to no effect.
