### ISSUE TITLE
Cannot ventcrawl up or down pipe layers

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#67205]
Other stuff not relevant

## Reproduction:

Ventcrawling does not account for multi-z maps, there is no way to move up or down Zs while in a multi-layer adapter.

**Comment by Mooshimi** [comment]
I did this as a monkey and it worked fine.

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/82996
