### ISSUE TITLE
hilbert hotel tram gets mobs stuck in it when running them over

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#67215]
## Testmerges:
~~might be related to #66657 but im not sure, was too long ago for me to remember~~
not related
## Reproduction:

> be on hilbert hotel tram
have mob in hallway
run them over
mob gets run over 1-2 times 
mob phases into the tram 
get mauled to death

I think it has to do with the hilbert tram using directional windows instead of normal windows, can possibly apply to tramstation tram if you replace the fulltiles with dir windows

**Comment by Kylerace** [comment]
https://user-images.githubusercontent.com/15794172/169716159-c6072dab-b32c-4726-a232-caa7079a23a8.mp4
cannot reproduce using #66657

**Comment by private-tristan** [comment]
here's what the bug looks like, 66657 wasn't merged so I guess it got fixed by the pr.
 
https://user-images.githubusercontent.com/54422837/170801688-bd6f8ad7-74fe-49e1-b898-f597f1299700.mp4

**Comment by private-tristan** [comment]
Tested this again now that #66657 is merged and I can't reproduce, closing
