### ISSUE TITLE
Nuke cutscene didn't go away, didn't end round

### ISSUE THREAD

**Issue by JoshAdamPowell** [tgstation/tgstation#67210]
## Round ID: 
183602

## Testmerges:
[#65791: 'Optimizes Runechat' by Kylerace at commit 4262b5536d](https://www.github.com/tgstation/tgstation/pull/65791)

## Reproduction:
Nuke exploded off station, the correct cutscene screen came up, but the round didn't end, the cutscene stayed up. Eventually I had to end the round manually.

**Comment by JoshAdamPowell** [comment]
Might be related to https://github.com/tgstation/tgstation/pull/67144 ?

**Comment by MrMelbert** [comment]
you win some, you lose some

do you know which nuke cinematic it was @JoshAdamPowell ? 
Mutually assured destruction, nuke win, nuke fluke, etc?

**Comment by JoshAdamPowell** [comment]
@MrMelbert It was the crew minor one where the nuke goes off but not on the station (it was just off the solars) It was at least a minute and a half before I decided to end the round. OOC had well and truly gone to HELP WHY CANT I SEE ANYTHING

**Comment by MrMelbert** [comment]
Test it locally, the cinematic appears and disappears correctly, so not sure about that

Also, from what I can tell the round isn't supposed to end if the nuke misses the station - so that one makes sense, I think

**Comment by Mothblocks** [comment]
> Also, from what I can tell the round isn't supposed to end if the nuke misses the station - so that one makes sense, I think

I don't think that's right, I believe it is meant to end the round
