### ISSUE TITLE
Latticed chasms can be fallen into

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#67224]
## Reproduction:

> be on snap pop shuttle (presumably any chasm works)
attempt to place lattice on chasm
fail
RCD chasm into a floor
RCD floor back into chasm
place lattice
attempt to walk over lattice
death

https://user-images.githubusercontent.com/54422837/169724218-1b3b2258-bbe2-43a8-870b-cc49a657648a.mp4

**Comment by OrionTheFox** [comment]
Dont you need to double-bar it so its a Catwalk if you want to stand on it? I thought falling thru lattices was intentional

**Comment by private-tristan** [comment]
> Dont you need to double-bar it so its a Catwalk if you want to stand on it? I thought falling thru lattices was intentional

standing on lattices has always worked  on multiZ maps like tram to avoid falling, so I sorta assumed it WOULD work here, the only difference that I know of between lattices and catwalks is that catwalks allow wires

**Comment by Mooshimi** [comment]
relevant code:
https://github.com/tgstation/tgstation/blob/0e4ab866c39fbbcef91accbb907fc26bec0af271/code/datums/components/chasm.dm#L48
