### ISSUE TITLE
Performacne of the alt click / turf stat panel is now extremely terrible 

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#67249]
## Reproduction:

Alt-clicking something / pulling up the "turf" stat panel now seems to lag your game to absurd levels.

**Comment by Mothblocks** [comment]
i told @magatsuchi this but i dont hink they did anything yet

**Comment by Mothblocks** [comment]
It's still horrible

**Comment by Mooshimi** [comment]
Can confirm using it fully freezes my client for 30+ seconds before loading and then refreezing. This continues until you click off the alt tab on the top right.

**Comment by Mooshimi** [comment]
> i told @magatsuchi this but i dont hink they did anything yet

https://github.com/tgstation/tgstation/pull/68518 looks like they took a shot at it recently

**Comment by PKPenguin321** [comment]
bumping, this is pretty outstandingly bad

**Comment by SinfulBliss** [comment]
I found another wrinkle in this that may help solve it.
When alt-clicking an object on a tile, it will not only use alt-click on that object but also on the floor tile itself, despite not touching the floor tile.

I have a clip of this. I alt-click a PDA on the floor to remove the ID from it, and it removes the ID while simultaneously opening up the floor examine tab and lagging the game:
https://streamable.com/zi9sgu

**Comment by SinfulBliss** [comment]
https://github.com/tgstation/tgstation/pull/67067
https://github.com/tgstation/tgstation/pull/66971
https://github.com/tgstation/tgstation/pull/67173
It might be one of these.

**Comment by Mooshimi** [comment]
> I found another wrinkle in this that may help solve it.
> When alt-clicking an object on a tile, it will not only use alt-click on that object but also on the floor tile itself, despite not touching the floor tile.
> 
> I have a clip of this. I alt-click a PDA on the floor to remove the ID from it, and it removes the ID while simultaneously opening up the floor examine tab and lagging the game:
> https://streamable.com/zi9sgu

I'm fairly sure this is known, since the same happens when spinning chairs

**Comment by iprice** [comment]
I miss this feature, its the best way to loot my head of staff locker (made me think my computer was really messed up when i first found it too) so...

I did a git bisect on this, my test is 20 spawned donuts alt clicked and trying to do one tile range steps around it, i defined a bad case as lagging me off and a good case as giving no issues (it's pretty identifiable when it happens)

```
bea938745876492ddd7d41a61711b26ec72d2f08 is the first bad commit
commit bea938745876492ddd7d41a61711b26ec72d2f08
Author: magatsuchi <88991542+magatsuchi@users.noreply.github.com>
Date:   Sun May 15 23:12:05 2022 -0500

    refactors statpanel to use tgui API (#66971)

    refactors the status panel to utilize the tgui/byond communication APIs instead of passing along href data, as well as converts the entirety of it into a datum/tgui_window

    Co-authored-by: Aleksej Komarov <stylemistake@gmail.com>
```

The full bisect history is (likely uninteresting)

```
$ git bisect log
git bisect start
# status: waiting for both good and bad commits
# bad: [f307b2c772537338fe3f108469bda5598d4f6f55] Automatic changelog generation for PR #69024 [ci skip]
git bisect bad f307b2c772537338fe3f108469bda5598d4f6f55
# status: waiting for good commit(s), bad commit known
# good: [6671847826399acb11e0c131f338232777510c33] Automatic changelog generation for PR #60579 [ci skip]
git bisect good 6671847826399acb11e0c131f338232777510c33
# good: [258618ca241ee1cbe39474885791bdefab97537b] Make the repeated messages spam filter give a clearer warning (#65029)
git bisect good 258618ca241ee1cbe39474885791bdefab97537b
# good: [258618ca241ee1cbe39474885791bdefab97537b] Make the repeated messages spam filter give a clearer warning (#65029)
git bisect good 258618ca241ee1cbe39474885791bdefab97537b
# good: [44d8bce60a78cbd1d271b797d796d09c17072075] Automatic changelog compile [ci skip]
git bisect good 44d8bce60a78cbd1d271b797d796d09c17072075
# bad: [99e5714184bbb4dd98dbc7f68f53d993a1573b76] Fixes Invisible Equipment on Monkified Monkeys (#68009)
git bisect bad 99e5714184bbb4dd98dbc7f68f53d993a1573b76
# bad: [b4544229ae495736957cfe8dc76943307fece4c6] Roundstart engineering SMESes start with ROUGHLY 4-5 more minutes of power (#67391)
git bisect bad b4544229ae495736957cfe8dc76943307fece4c6
# bad: [cd46d30dc732069f3e55f70b6c4f6ec4931c4410] Automatic changelog generation for PR #67186 [ci skip]
git bisect bad cd46d30dc732069f3e55f70b6c4f6ec4931c4410
# bad: [2077358bf777a87279d7b440fd0478878cd2e276] Automatic changelog generation for PR #67039 [ci skip]
git bisect bad 2077358bf777a87279d7b440fd0478878cd2e276
# good: [480751a6f4176c645d55bcb7ff6ce187c1bca7b2] Split up mecha.dm properly (#66986)
git bisect good 480751a6f4176c645d55bcb7ff6ce187c1bca7b2
# bad: [89650214fd80b260f91693f8ec86e94e47115f10] [MDB Ignore] Refactoring Flora code (#66978)
git bisect bad 89650214fd80b260f91693f8ec86e94e47115f10
# good: [26f8daa145dac04637b5561aed6dbac152748cb3] Automatic changelog generation for PR #66974 [ci skip]
git bisect good 26f8daa145dac04637b5561aed6dbac152748cb3
# bad: [a3add3761884e925059d0e4fd4e74af5febfac5c] Refactors the forensics component into a datum (#66809)
git bisect bad a3add3761884e925059d0e4fd4e74af5febfac5c
# good: [532a64d346bf391e4268d94151f36df3d482f06b] Automatic changelog generation for PR #66991 [ci skip]
git bisect good 532a64d346bf391e4268d94151f36df3d482f06b
# good: [e83c27534ff3918d1e4c7495567c891342437def] Automatic changelog generation for PR #67025 [ci skip]
git bisect good e83c27534ff3918d1e4c7495567c891342437def
# bad: [bea938745876492ddd7d41a61711b26ec72d2f08] refactors statpanel to use tgui API (#66971)
git bisect bad bea938745876492ddd7d41a61711b26ec72d2f08
# good: [b245c72994b6e9dd4c3ea0083fe6079cec4eb41f] Automatic changelog compile [ci skip]
git bisect good b245c72994b6e9dd4c3ea0083fe6079cec4eb41f
# first bad commit: [bea938745876492ddd7d41a61711b26ec72d2f08] refactors statpanel to use tgui API (#66971)
```

**Comment by Mothblocks** [comment]
yeah thats why i was nagging @magatsuchi to fix this but i dont think they will

**Comment by magatsuchi** [comment]
i am going to refactor it

**Comment by LemonInTheDark** [comment]
This was always an issue, ever since we added timeouts like 2 years ago.
Kyler's pr #63991 did hurt things, but it just exposed an existing issue more strongly

**Comment by Mothblocks** [comment]
the root of it might have always been an issue but "alt click is literally too terrible for anyone to use ever" is definitely not a 2 year old issue
