### ISSUE TITLE
Most hostile mining fauna can move anchored objects and they stay anchored

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#67271]
Reporting client version: 514.1583

## Round ID:
[183734](https://scrubby.melonmesa.com/round/183734)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Adds Cargorilla](https://www.github.com/tgstation/tgstation/pull/67003)
- [Resprites almost all the hair to modern standards by Crumpaloo](https://www.github.com/tgstation/tgstation/pull/67184)

## Reproduction:
Stand on one side of an anchored object such as a reinforced window, put goliath/ice whelp on other side
It will push the window around while keeping it anchored.
Causes a lot of problems with mapping things such as fences on icebox as well.

**Comment by Fikou** [comment]
that is intended, those mobs have moving force that will push any object with a weaker move resist
