### ISSUE TITLE
Chem bomb destroys all of middle section tram

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#67278]
There is more than this:
![Untitled(1)](https://user-images.githubusercontent.com/84478872/170176890-49068bec-c490-40ca-b034-916f013f6909.png)

Round: 183741

Chem bomb 20 minutes in destroyed all of central tram station, shuttle called immediately 

Please nerf this shit why do we even have syndicate bombs they are nothing compared to this

**Comment by LemonInTheDark** [comment]
This is not a bug, it's just dumb
