### ISSUE TITLE
When you turn off the lights in cargo, it will move the shutters on the converyor belt

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#67292]
## Round ID:
Round ID: [183762](https://scrubby.melonmesa.com/round/183762)

## Testmerges:
[#65791: 'Optimizes Runechat' by Kylerace at commit 52075d331d](https://www.github.com/tgstation/tgstation/pull/65791)
[#67003: 'Adds Cargorilla' by MrMelbert at commit 7c3f80913f](https://www.github.com/tgstation/tgstation/pull/67003)
[#67184: 'Resprites almost all the hair to modern standards by Crumpaloo' by Iamgoofball at commit bec4d92d79](https://www.github.com/tgstation/tgstation/pull/67184)

## Reproduction:
1. Click lightswitch
2. Shutters move
Also happens if you do it as a player, not just with admin ai interact.
See the video https://gfycat.com/grandioseposhgourami

**Comment by Mooshimi** [comment]
Is this a prank...?

**Comment by ATH1909** [comment]
bug of the year 2022?

**Comment by robbertapir** [comment]
reproduced

**Comment by blackdav123** [comment]
happened again round 183940

**Comment by Mooshimi** [comment]
![dreamseeker-18 25 16 920](https://user-images.githubusercontent.com/85910816/170844624-07a01e59-a1a9-403a-a3e4-c35aac1b886c.png)

I did it and I'm very confused...
