### ISSUE TITLE
Path of the Blade heretic knife costs 2 silver instead of 1

### ISSUE THREAD

**Issue by blackdav123** [tgstation/tgstation#67305]
## Reproduction:
1. Be awesome and cool silver heretic
2. Read recipe for cool silver knife. "Allows you to transmute a knife with _a bar of silver_ to create a Darkened Blade."
3. Miners haven't done shit, deconstruct operating table
4. Try to make funny knife using one bar of silver and a knife
5. Actually takes two silver bar, heretic immediately kills himself out of shame.

Please SAVE the poor heretics from this GAMEBREAKING issue

**Comment by private-tristan** [comment]
from #65718
>  Cutting Edge: Allows them to transmute up to five knives. Knives are made with two bars of silver.

intended to cost 2 silver, not 1, I'll see what I can do.
