### ISSUE TITLE
`/datum/component/drift` runtimes on transit tube pods

### ISSUE THREAD

**Issue by SabreML** [tgstation/tgstation#67301]
## Round ID:
N/A, runtime on a downstream then reliably reproduced on a TG test server.

## Reproduction:
1. Enter a transit tube that goes through more than 1 tile of open space. (The one to Kilo's chapel for example)

This seems to be a side effect of #67145. (Probably revealed by rather than caused by)
```
runtime error: Incompatible /datum/component/drift assigned to a /obj/structure/transit_tube_pod/dispensed! args: [0,0,0]
 - proc name: stack trace (/proc/stack_trace)
 -   source file: stack_trace.dm,3
 -   usr: (src)
 -   src: null
 -   call stack:
 - stack trace("Incompatible /datum/component/...")
 - /datum/component/drift (/datum/component/drift): New(/list (/list))
 - the temporary transit tube pod (/obj/structure/transit_tube_pod/dispensed):  AddComponent(/list (/list))
 - the temporary transit tube pod (/obj/structure/transit_tube_pod/dispensed): newtonian move(0, 0, 0)
 - the temporary transit tube pod (/obj/structure/transit_tube_pod/dispensed): Moved(space (81,167,2) (/turf/open/space/basic), 0, 1, null)
 - the temporary transit tube pod (/obj/structure/transit_tube_pod/dispensed): Moved(space (81,167,2) (/turf/open/space/basic), 0, 1)
 - the temporary transit tube pod (/obj/structure/transit_tube_pod/dispensed): doMove(space (80,168,2) (/turf/open/space/basic))
 - the temporary transit tube pod (/obj/structure/transit_tube_pod/dispensed): forceMove(space (80,168,2) (/turf/open/space/basic))
 - /datum/move_loop/move/force (/datum/move_loop/move/force): move()
 - /datum/move_loop/move/force (/datum/move_loop/move/force): process()
 - Movement Loops (/datum/controller/subsystem/movement): pour bucket(/list (/list))
 - Movement Loops (/datum/controller/subsystem/movement): fire(0)
 - Movement Loops (/datum/controller/subsystem/movement): ignite(0)
 - Master (/datum/controller/master): RunQueue()
 - Master (/datum/controller/master): Loop(2)
 - Master (/datum/controller/master): StartProcessing(0)
```
<hr>

Transit tube pods use `SSmove_manager.force_move_dir()` to move. That calls `forceMove()`, which if the pod is in space without any nearby lattices, calls `newtonian_move()` and adds `/datum/component/drift` to the pod.
`/datum/component/drift` tries to add a new 'drifting' movement loop in its initialize proc here:
https://github.com/tgstation/tgstation/blob/0e4ab866c39fbbcef91accbb907fc26bec0af271/code/datums/components/drift.dm#L26-L37
This works fine on the first space tile, but the pod is `forceMove()`'d on every tile after that as well, with each move trying to add a new drift component.
`/datum/component/drift` uses `COMPONENT_DUPE_HIGHLANDER` as its `dupe_mode`, which creates a new version and *then* deletes the old one:
https://github.com/tgstation/tgstation/blob/0e4ab866c39fbbcef91accbb907fc26bec0af271/code/datums/components/_component.dm#L435-L441
Because of this, the original component doesn't delete `drifting_loop`, and the moveloop comparison PR prevents a duplicate being created, causing a `COMPONENT_INCOMPATIBLE` error.

(Note: The pod never actually drifts as far as I can tell, so a possible solution would be to avoid the component being added in the first place.)

**Comment by Sealed101** [comment]
no longer seems to be an issue, can't encounter this runtime on either of the pods, both when they are in or out of the transit system; there were like one or two refactors to space movement so that might have cleaned this up
