### ISSUE TITLE
IceBoxStation Camera In Maintenance (West Of EVA)

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#67314]
![image](https://user-images.githubusercontent.com/34697715/170424852-b9d6db5f-2a12-4679-96b5-f0eb4a0abf9e.png)

jesse that's not supposed to be there JESSE HANK THERE'S A CAMERA IN ICEBOX MAINTENANCE REMOVE THE CAMERA GO HURRY

**Comment by newfren** [comment]
that's been there for like 5 years at least

**Comment by Striders13** [comment]
I think it's intentional because icebox's Eva is the only one you can access through maint

**Comment by san7890** [comment]
Is there any proof that this change was intentional? If not, I will OK any changes that remove this camera.
