### ISSUE TITLE
Several Icemoon fauna have alot of undocumented / abnormal self regen.

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#67311]
Reporting client version: 514.1582

## Testmerges:
- [Resprites almost all the hair to modern standards by Crumpaloo](https://www.github.com/tgstation/tgstation/pull/67184)
- [The Humanening](https://www.github.com/tgstation/tgstation/pull/67298)

Ice whelps, Bears, Demonic watchers, and possibly more icemoon specific mobs have very notice-able self regen capabilities.

I do not know or think this was intended and was told to report it by an admin who also thought it was unintentional.

This is extremely impactful because many icemoon mobs are big balls of stats that most crew are forced to hit and run, and any amount of self regen does a lot to minimize the crews ability to fight back (rip botanists if something breaks in)

This is also impactful for miners, specifically with Demonic watchers since they teleport around making them hard to kill quickly.
## Reproduction: 

Damage mob

Watch it heal

**Comment by interestingusernam3** [comment]
The mobs are just morbing out.
![FTSpJWLXoAE13uc](https://user-images.githubusercontent.com/51925758/170712089-6460d6f6-a527-4006-aa56-3980279c1e86.jpeg)

**Comment by ATH1909** [comment]
> Ice waste fauna (polar bears, watchers) all seem to have a copy+pasted function in `Life()` in which they regenerate 25%(?) of their health _every life tick_ while they don't have a target they're attacking.
> 
> This is pretty rough for fauna that get on station (botany, kitchen, chapel, chem lab) (and unfun). Needs documentation, in game feedback, or just axe it since it sucks.

```adjustHealth(-0.0125 * maxHealth * delta_time)```
ain't this just 1.25% of their health/sec?

**Comment by timothymtorres** [comment]
This was fixed by #67426
