### ISSUE TITLE
Losing any antag datum will remove all of your antag datum's moodlets

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#67313]
## Reproduction:

If you gain multiple antagonist datums, losing any antag datum will cause you to lose the moodlet from all your antag datums. 
Ex: A heretic revolutionary will lose the heretic moodlet when the revolution ends.

**Comment by timothymtorres** [comment]
I'm actually in the process of doing a big mood refactor.  I've got most of the code ready but it just needs to be tested and tweaked.  The antag moodlets use the same category right now so they replace the old moodlet if a new one gets added.  My PR changes this so each antag moodlet is separate so it is possible to stack them together.
