### ISSUE TITLE
B.E.P.I.S. Chamber deletes itself when opening the maintenance hatch

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#67347]

**Comment by Rhials** [comment]
Two things of note from testing -- left clicking the BEPIS with a screwdriver has no issue. The BEPIS will only go invisible if right-clicked by a screwdriver and is still accessible if you alt-click the tile it was on. Screwdrivering it again in the alt-click menu will return the BEPIS to normal.

**Comment by ArcaneDefence** [comment]
Thanks for figuring that out, I had looked into reproducing this and instinctively used lmb.
Really just a reminder that providing thorough reproduction steps is important
