### ISSUE TITLE
Somebody changed something they shouldn't have and now derelict drones cant open the vault

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#67350]
Reporting client version: 514.1583

## Round ID:
[183890](https://scrubby.melonmesa.com/round/183890)

## Testmerges:
- [The Humanening](https://www.github.com/tgstation/tgstation/pull/67298)
- [Resprites almost all the hair to modern standards by Crumpaloo](https://www.github.com/tgstation/tgstation/pull/67184)

## Reproduction:
>Spawn in as derelict drone
>Make your way into the vault room
>"You try to read the vault controller, but can't comprehend any of it."
>Crying ensues

![image](https://user-images.githubusercontent.com/36141254/170805841-fad92e31-29bd-46bc-800c-71fee6f14e4b.png)

**Comment by Crystal9156** [comment]
This is because of the illiterate PR I believe, as I've had it as drone as well. https://github.com/tgstation/tgstation/pull/66648

**Comment by timothymtorres** [comment]
I'll fix this in a day or two.
