### ISSUE TITLE
Plasmaman envirogloves use envirosuit inhands

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#67351]
Reporting client version: 514.1583

## Round ID:
[183887](https://scrubby.melonmesa.com/round/183887)

## Testmerges:
- [The Humanening](https://www.github.com/tgstation/tgstation/pull/67298)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Adds Cargorilla](https://www.github.com/tgstation/tgstation/pull/67003)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/170805894-70f79ee0-dbfd-4945-9757-12f0de997f27.png)

**Comment by ArcaneDefence** [comment]
There is an ungodly amount of these sorts of situations with clothing in general.
Not entirely sure this has a nice solution

**Comment by NamelessFairy** [comment]
> There is an ungodly amount of these sorts of situations with clothing in general. Not entirely sure this has a nice solution

Specifically for gloves couldn't this be resolved by doing GAGS on them?
