### ISSUE TITLE
Destroy Machinery obj can target hard-to-destroy Master Server

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#67354]
## Reproduction:

https://github.com/tgstation/tgstation/blob/master/code/modules/antagonists/traitor/objectives/destroy_machinery.dm

The Destroy Machinery traitor objective can target the RnD Master Server, which is intentionally difficult to destroy due to containing a traitor objective, as opposed to the regular server box, which can just be deconstructed.

Removing the objective hard drive (goon code) does not complete the objective despite effectively disabling the server, making the objective seemingly vague.

The only viable and feasible way to complete the objective is spending TC on a block of c4.

**Comment by Mooshimi** [comment]
Seems like a possible oversight.

**Comment by timothymtorres** [comment]
https://github.com/tgstation/tgstation/blob/25ef92db38492c518fd03104c1b38a3b59569e37/code/modules/research/server.dm#L204-L219

**Comment by YakumoChen** [comment]
@Iamgoofball Wheres the fix for this located?
