### ISSUE TITLE
Cursed Heart red screen does not appear when in berserk mode in Berserk Armor

### ISSUE THREAD

**Issue by TheBoxCat** [tgstation/tgstation#67367]
## Round ID:
 [183925](https://scrubby.melonmesa.com/round/183925)

## Reproduction:
Wearing the Berserk Armor and activating the berserk mode while also having cursed heart will make the red screen not appear notifying the player that they need to pump their heart. Due to this I instantly died not knowing I needed to pump my heart.

**Comment by Sealed101** [comment]
can not reproduce; berserk mode doesn't seem to have anything that would interfere with the cursed heart's overlay

recent refactor #73301 could have closed this somehow? also mining loot rework #60516 ? either or lol

https://github.com/tgstation/tgstation/blob/2e240d0e9d0744238bf9ef639ca9bf0a8942364f/code/modules/mining/lavaland/tendril_loot.dm#L755-L765

https://github.com/tgstation/tgstation/blob/2e240d0e9d0744238bf9ef639ca9bf0a8942364f/code/modules/surgery/organs/heart.dm#L153-L169
