### ISSUE TITLE
Operatives make Golems...instead make more humans.

### ISSUE THREAD

**Issue by TheMidnightRose** [tgstation/tgstation#67376]
Reporting client version: 514.1583

## Round ID:
[183947](https://scrubby.melonmesa.com/round/183947)

## Testmerges:
- [The Humanening](https://www.github.com/tgstation/tgstation/pull/67298)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Adds Cargorilla](https://www.github.com/tgstation/tgstation/pull/67003)

## Reproduction:

Well the Operatives in this round decided to make golems before invading...for 40min. Finally made them and the first couple got turned into Op Humans after creation, last couple were made by the golems and got shot.

So be an Operative and create a golem to get free reinforcements right now.

**Comment by rellyreri** [comment]
some extra details
- material did not matter, when using glass/iron/cardboard/etc they would turn into humans
- the new human golem-ops were completely naked without gear
- an admin turned them back into cardboard golems and they all had the free golem hazard debuff on-station

**Comment by private-tristan** [comment]
probobly has to do with how the game spawns you as your desired race, then turns you into a human when you're a nukie, and I guess it's setting the golems as a nukie as well, causing their race to be turned human.

**Comment by CCC23** [comment]
Hey guys I got an idea I call Xenobio ops wanna see it?
