### ISSUE TITLE
Custom say emote issues.

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#67381]
Reporting client version: 514.1583

## Round ID:
[183960](https://scrubby.melonmesa.com/round/183960)

## Testmerges:
- [The Humanening](https://www.github.com/tgstation/tgstation/pull/67298)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Adds Cargorilla](https://www.github.com/tgstation/tgstation/pull/67003)

## Reproduction:
Custom say emotes force you to say "An interesting thing to say" in runechat if no second argument is given.
Example:
`screams in agony!*`
Tried reproducing this on local, and it didn't happen, so most definitely #65791 test merge bug.

**Comment by dragomagol** [comment]
Please report this on the relevant PR.
