### ISSUE TITLE
Can't complete firing range bounty in Icebox.

### ISSUE THREAD

**Issue by Xander3359** [tgstation/tgstation#67382]
Reporting client version: 514.1583

## Round ID:
[183956](https://scrubby.melonmesa.com/round/183956)

## Testmerges:
- [The Humanening](https://www.github.com/tgstation/tgstation/pull/67298)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Adds Cargorilla](https://www.github.com/tgstation/tgstation/pull/67003)

## Reproduction:

For security one of their bounties is to perform a routine inspection in firing range, but there's no firing range in icebox so this bounty is impossible.

**Comment by Son-of-Space** [comment]
There's actually no firing range on Kilo either. My fix for this is going to be removing the range as an option for scanning.
