### ISSUE TITLE
Atrocinator and Antigrav MODules do not prevent slips

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#67380]
## Round ID:
Downstream

## Reproduction:

Slips of any type still function normally when using the Atrocinator or Antigravity (with a jetpack). This is inconsistent with behaviour related to global gravity being disabled, for example and doesn't make sense in all cases. (the Atrocinator makes you walk on the ceiling, you shouldn't be slipping on stuff on the floor)

**Comment by Fikou** [comment]
are you sure gravity being disabled makes people immune to slips? no gravity gives people the trait of floating, not flying (flying is required to be immune to slips

**Comment by YakumoChen** [comment]
afaik floating has always enabled you to avoid common slips like soaps and water? It doesn't seem very consistent either way. How do you slip on a banana in midair?
