### ISSUE TITLE
private purchases can SCAM you

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#67383]
## Reproduction:

1. get a private purchase
2. roll the rng chance for it to not have the correct stuff
3. send your goody away stamped denied
4. the money goes to the cargo budget, not to you
5. cry as you lost all your round savings to rng

**Comment by necromanceranne** [comment]
Is it supposed to be an incorrect order?

**Comment by Profakos** [comment]
Hey, is this still an issue after #70572? Are there other manifest errors that can still happen with goodie purchases?

**Comment by Sealed101** [comment]
if #70572 didn't kill this, #78923 did
