### ISSUE TITLE
Lings can cheat during sparring matches using fleshmend and cryo sting (and I guess mute sting but that doesn't have much impact on the fight itself)

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#67395]
Reporting client version: 514.1584

## Round ID:
[183990](https://scrubby.melonmesa.com/round/183990)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Adds Cargorilla](https://www.github.com/tgstation/tgstation/pull/67003)
- [Disables soft lock on traitor objectives](https://www.github.com/tgstation/tgstation/pull/67385)

## Reproduction:
Fight a ling for a holy sparring sect match
Get cryo stung, mute stung, and watch them go from severe bruising to minor bruising
The game sees YOU as the cheater when you try to flee the rigged match.
![image](https://user-images.githubusercontent.com/44104681/170887382-02d277fd-3b39-463a-a8b7-c006fbb7b07c.png)

**Comment by blackdav123** [comment]
Skill issue

**Comment by necromanceranne** [comment]
It is simply a difference in ability.

**Comment by VladinXXV** [comment]
They had to rely on fleshmend TWICE I think you're confused about who here has the skill issue.

**Comment by blackdav123** [comment]
I'd argue this is intentional. If you challenge the wrong person during your duels you'd better hope there are witnesses willing to back you up. Bring some pills if you are thinking the opponent might cheat, or you'll end up like this [https://www.youtube.com/watch?v=kQKrmDLvijo](url)

**Comment by timothymtorres** [comment]
I really don't think this is a bug.  There are plenty of cheating mechanics in lots of the code (cards, dice, etc.) and this should be no different.  If you are dumb enough to challenge a ling to a rage cage match, expect to get robusted.

**Comment by VladinXXV** [comment]
> I really don't think this is a bug. There are plenty of cheating mechanics in lots of the code (cards, dice, etc.) and this should be no different. If you are dumb enough to challenge a ling to a rage cage match, expect to get robusted.

A: it's not like I knew he was a ling beforehand

B: regardless of if you want to leave the ability for lings to cheat a fight being observed by god (because sure, let's say god can't tell) there should at least be some detection of such so the chaplain isn't punished for it. losing a holy match is a big deal, if you lose 3 you're excommunicated. whole point of having a contract you both agree to is to keep the fight fair. if we're all fine with cheating, why bother mechanically enforcing rules at all in the matches?

C: "this should be no different" again bro idk if cheating in a card game is the same as cheating in a fight being observed by a deity where even trying to take a step outside of the agreed upon room sends you flying and is a "violation"

**Comment by Iamgoofball** [comment]
declared intentional by feature designer
