### ISSUE TITLE
Plungers do not solve hostile scrubbers

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#67397]
Reporting client version: 514.1584

## Round ID:
[183994](https://scrubby.melonmesa.com/round/183994)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Adds Cargorilla](https://www.github.com/tgstation/tgstation/pull/67003)
- [Disables soft lock on traitor objectives](https://www.github.com/tgstation/tgstation/pull/67385)

## Reproduction:
We had glockroaches/hauberroaches in the arrivals hallway, and despite personally using a plunger on every scrubber and vent (only one of them actually had a progress bar), the roaches kept coming.

**Comment by Rhials** [comment]
![image](https://user-images.githubusercontent.com/28870487/171078327-939fad37-ca2a-4ccc-9b6f-6d001bdc50ae.png)

Was this the cause of your problem, or were they still spawning from the scrubber (with a message that they're crawling out of the vent) after you unclogged the vent with the progress bar?

**Comment by VladinXXV** [comment]
I don't recall exactly. I wasn't aware an admin had continued to spawn them. They were appearing from one of the scrubbers after I did the progress bar, but whether or not that was just because of Harricross spawning them I cannot say.

**Comment by Sealed101** [comment]
i call admin trolling, most of roach manipulations were on or near vents. QoL wouold be logging the successful `unclog()` but like... eh

![изображение](https://user-images.githubusercontent.com/75863639/223722667-dc7398d6-8587-482c-af94-66133a23b41d.png)
![изображение](https://user-images.githubusercontent.com/75863639/223722812-eb758696-f4cd-4833-a9f2-0b2d692c4978.png)
![изображение](https://user-images.githubusercontent.com/75863639/223722875-77029b8d-f94d-4a5e-9cbb-278e135c8ee4.png)
![изображение](https://user-images.githubusercontent.com/75863639/223723070-8965863e-5f6d-44a4-a48b-2744c1af99ac.png)
