### ISSUE TITLE
Icebox Windoors in Walls 2 for 1

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#67398]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Middle-layer South Mining base exit
![Screenshot_1](https://user-images.githubusercontent.com/95751821/170892387-9434f4fb-f9a5-4d37-82e8-3603474dd3b0.png)
Middle-layer locker room (?) exit
![Screenshot_2](https://user-images.githubusercontent.com/95751821/170892392-53e50ca0-9327-4a10-873c-d31f7eb809a8.png)

**Comment by san7890** [comment]
FYI: This was caused by an updatepaths error, which was fixed #67209. If you want to correct this issue, please ensure that you replace whatever missing sign was once there.
