### ISSUE TITLE
halucination fire is completely invisible

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#67401]
## Round ID:
[183997](https://scrubby.melonmesa.com/round/183997)

## Testmerges:

irrelevant

## Reproduction:

> accidentally look at the SM with no goggles
> see the fire notification pop up
> not on fire
> see temperature going up
> begin taking stamina damage
> get stamcritted from invisible fire

**Comment by LemonInTheDark** [comment]
Trap a rippy main in a locked room and force him to stare at hallucination tests to see if they're working or not
Upkeep will be cheap
