### ISSUE TITLE
Lavaland lungs don't work on Icebox

### ISSUE THREAD

**Issue by conk444** [tgstation/tgstation#67400]
Reporting client version: 514.1583

## Round ID:
[184001](https://scrubby.melonmesa.com/round/184001)

## Testmerges:
- [Disables soft lock on traitor objectives](https://www.github.com/tgstation/tgstation/pull/67385)

## Reproduction:
1. kill a goliath or ashwalker on Icebox.
2. Harvest the innards of the lizard corpse.
3. Have another player replace your ordinary lungs with the "blackened frilled lungs" of the Necropolis lizard.
4. Go outside, fail to breathe, and slowly die.

**Comment by rasepretep** [comment]
I wouldn't say this is a bug.

There is a ruin on Ice Box that strongly suggests an ashwalker tribe was there and died out, presumably to the cold. Ashwalker lungs make you able to breathe the airmix, but do nothing about the air temperature, which low enough to be fatal when inhaled. In theory, the Last Ash Drake ruin on Ice Box should have the correct lavaland atmos and be breathable with ashwalker lungs, but the whole of ice wastes definitely shouldn't.

**Comment by dragomagol** [comment]
I don't think this is a bug either. Lizzers hate the cold.
