### ISSUE TITLE
External organs are not displaying

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#67433]
Reporting client version: 514.1583

## Round ID:
[184088](https://scrubby.melonmesa.com/round/184088)

## Testmerges:
- [Adminwho now caches feedback links until admins are reloaded (and also works again)](https://www.github.com/tgstation/tgstation/pull/67307)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Adds Cargorilla](https://www.github.com/tgstation/tgstation/pull/67003)
- [Disables soft lock on traitor objectives](https://www.github.com/tgstation/tgstation/pull/67385)

## Reproduction:
Open SS13 
Create a moth and/or lizard
They are now abominations
Most definitely caused by [67017](https://github.com/tgstation/tgstation/pull/67017) which was not test merged whatsoever
![image](https://user-images.githubusercontent.com/81882910/171115317-568baa8b-8622-4d5e-9240-10ffe864f546.png)
![image](https://user-images.githubusercontent.com/81882910/171115327-58f7a1b7-8c70-4af8-9178-a5e7b74caa2a.png)

caused by [67017](https://github.com/tgstation/tgstation/pull/67017)

**Comment by Kylerace** [comment]
we do a little trolling
