### ISSUE TITLE
xenomorphs have the strange burning sprites

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#67444]
## Round ID:
irrelevant

## Testmerges:

irrelevant

## Reproduction:

> be xenomorph
be set on fire

![image](https://user-images.githubusercontent.com/54422837/171282686-78ae62c4-7a84-4a59-9807-6e7651a0f692.png)
![image](https://user-images.githubusercontent.com/54422837/171282799-65af8ab6-aa39-4247-8493-6392e2139d80.png)

**Comment by timothymtorres** [comment]
Duplicate of #12605

**Comment by private-tristan** [comment]
oops my bad
