### ISSUE TITLE
Traitors can change the "orbit" of icebox

### ISSUE THREAD

**Issue by itseasytosee** [tgstation/tgstation#67467]
Traitor doing the add threat final objective on icebox.
![image](https://user-images.githubusercontent.com/55666666/171516018-c384893d-26fc-4b0b-8b8c-78aad7f58f62.png)

**Comment by necromanceranne** [comment]
They're just really big rockets. It's how NT turned it into an Icemoon.

**Comment by Jolly-66** [comment]
Be funny is instead of orbit, icebox just got colder for the threat level increase haha

**Comment by ZAMODA** [comment]
"Someone on your station just opened all the freezers in our cold storage, decreasing the temperature of the planet"
