### ISSUE TITLE
Showers no longer trigger tissue hydration virus symptom

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#67480]
RoundID 184195

be viro 
make tissue hydration virus and consume it
stand under shower with brute damage
cry as you don't get healed from it

drinking water still works, healed the brute pretty much instantly, but after standing in a shower for ten seconds damage was not going down.

**Comment by TemporalOroboros** [comment]
I'm going to be that it doesn't trigger the AP explosion either.

**Comment by Xander3359** [comment]
This might be fixed by https://github.com/tgstation/tgstation/pull/72844 . Please attempt to reproduce again

**Comment by Sealed101** [comment]
water is indeed wet
https://github.com/tgstation/tgstation/pull/72844
