### ISSUE TITLE
cyborg RCD can't be upgraded with RCD upgrade disk

### ISSUE THREAD

**Issue by Holoo-1** [tgstation/tgstation#67487]
this was added in https://github.com/tgstation/tgstation/pull/52018 but something broke it and noone noticed
same goes for RPD upgrades

**Comment by 13spacemen** [comment]
I just tested it and it works fine with both RCD and RPD upgrades

**Comment by Holoo-1** [comment]
oops
tested again and it works(I was trying to do it in a wrong way)
