### ISSUE TITLE
Chameleon ion rifle disconnects AI from shells

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#67490]
Reporting client version: 514.1583

## Round ID:
[184207](https://scrubby.melonmesa.com/round/184207)

## Testmerges:
- [Adminwho now caches feedback links until admins are reloaded (and also works again)](https://www.github.com/tgstation/tgstation/pull/67307)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Disables soft lock on traitor objectives](https://www.github.com/tgstation/tgstation/pull/67385)

## Reproduction:
Shoot an AI in their shell with chameleon gun disguised as ion carbine / ion rifle
They will be disconnected from shell with every shot, taking no damage otherwise.

**Comment by timothymtorres** [comment]
The EMP effects from the ion rifle should disconnect the AI from the borg shell.  The real bug here is that if you use a chamelon projector you can shoot guns?  Can you link a video or something?

**Comment by newfren** [comment]
they are not talking about the chameleon projector, they are talking about the chameleon gun.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/9095a84a3f422335efe3939801beacb3c4be7eeb/code/modules/clothing/chameleon.dm#L765-L931

**Comment by Sealed101** [comment]
can't reproduce with either the ion carbine or ion rifle chameleon disguises
