### ISSUE TITLE
Departmental Security Officers are getting assigned to the same department instead of filling unfilled roles

### ISSUE THREAD

**Issue by Son-of-Space** [tgstation/tgstation#67534]
[Round ID]: N/A

Testmerges:
N/A

Reproduction:

Play on any server with a decent pop. Watch as security officers either join late or at roundstart get assigned to the same department instead of different departments.

Details:
Instead of filling out departmental roles until they're all filled, the system seems to be choosing the departmental assignment based on preference alone, which means that despite having a 6 or 7 officer security force, those officers might only cover one or two departments.

**Comment by Potato-Masher** [comment]
[57685](https://github.com/tgstation/tgstation/pull/57685)
Was it this one perhaps?

**Comment by Son-of-Space** [comment]
It might not be properly assigning only two to a department, but in practice I've noticed that it makes security coverage really lopsided. If it's properly assigning then this issue isn't a bug and should be closed.

**Comment by Mothblocks** [comment]
No because most rounds do not have 6 or 7 security slots
