### ISSUE TITLE
View Crew Manifest alignment off

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#67546]
## Testmerges: 
https://github.com/tgstation/tgstation/pull/67307
https://github.com/tgstation/tgstation/pull/67385

## Reproduction:
1. Observe round (whether a custom job role has been added matters I'm unsure)
2. Ghost Tab ->  View Crew Manifest

![gif](https://i.imgur.com/WBt4Jn0.gif)

**Comment by timothymtorres** [comment]
What part of the alignment is messed up?  It looks okay to me

**Comment by Mooshimi** [comment]
If you watch as I scroll in the gif all the job titles are misaligned between categories

**Comment by timothymtorres** [comment]
I see it now.  Looks like it's due to the length of job titles.  They probably should have used left align instead of right and made sure there was enough room.
