### ISSUE TITLE
Mech Hydraulic Clamps can't squeeze people on harm intent

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#67580]
## Reproduction: Try to use a mecha cargo clamp on somebody in harm intent, while in a mech, it doesn't do anything and displays "You longingly wish to tear [M]'s arms off.".

Looking at the code, it seems this message is supposed to play if you attempt a clamp with a 'fake' kill-clamp. The genuine kill-clamp, when aimed at someone's arms, is supposed to disarm them, but for some reason there's a fake kill-clamp that doesn't do anything. The regular squeeze code is still there; so presumably this wasn't intentional.

It might have something to do with the right click/left click changes made in the TGUI PR that weren't properly configured, not sure.

**Comment by timothymtorres** [comment]
Also some clamp problems involving #29282

**Comment by Sealed101** [comment]
this will happen when a clamp is installed into the secondary slot. clamps in the primary slots properly deal squeeze damage and do not produce such messages

clamp code was not updated with the mech rework and still has a right click exclusive action which just doesn't work

relevant code:

https://github.com/tgstation/tgstation/blob/2e240d0e9d0744238bf9ef639ca9bf0a8942364f/code/modules/vehicles/mecha/equipment/tools/work_tools.dm#L83-L130
