### ISSUE TITLE
Bolt of possession figment can't see anything

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#67596]
## Reproduction:
Fire staff of chaos a lot.
You fire it but it sometimes hits yourself....
![dreamseeker-00 00 37 406](https://user-images.githubusercontent.com/85910816/172294008-a1efbb18-a023-4240-b5bf-28ee92722f07.png)
![dreamseeker-23 50 26 225](https://user-images.githubusercontent.com/85910816/172294027-755b58c7-917c-4a94-ac08-c4e0250d1fd0.gif)
Round removal.

**Comment by davethwave** [comment]
Fixed a few of these as an admin. The figments they become don't have a location and are blind. You can't pull them toward you, only way to really fix currently is to delete the mob via vv to ghost them.

**Comment by Mooshimi** [comment]
> The issue here is not the bolt of possession round removing you, that is what the bolt is meant to do. The issue is that your figment is blind, which has to be some annoying bug thing

I thought this as well but the admin in the ahelp was talking about the round removal instead so I just made it this.

**Comment by timothymtorres** [comment]
Looks like there might be some overlap between this issue and #65669

**Comment by Sealed101** [comment]
missed this while doing https://github.com/tgstation/tgstation/pull/87288 which resolved the underlying jank
