### ISSUE TITLE
SM Cascade final objective is still available even if the SM has delaminated.

### ISSUE THREAD

**Issue by zxaber** [tgstation/tgstation#67598]
## Reproduction:

- SM delams for the usual reasons.
- Later, Traitor gets to final objective
- Traitor selects Supermatter Cascade
- Engineering is a hole, and shards from cargo don't work.

Saw this happen while observing a round. Either the final objective should be unavailable, or it should modify itself to allow cargo shards.

**Comment by antropod** [comment]
can you buy a shard and cascade it?
