### ISSUE TITLE
Teleprods are essentially free random teleports

### ISSUE THREAD

**Issue by castawaynont** [tgstation/tgstation#67616]
## Round ID:
[184529](https://scrubby.melonmesa.com/round/184529)

## Reproduction:
Acquire a random spawn teleprod in maint. Unknown if it actually matters if it's a maint spawn. Add a cell, then hit a mob. Random teleport functions as intended, but you are not knocked down, nor do you take stamina damage. Teleprod cell charge is not depleted on hit.

**Comment by private-tristan** [comment]
all stunprods seem to not work

**Comment by optimumtact** [comment]
we would definitely have player storming the gates if stunprods did not work.
