### ISSUE TITLE
there's no more emojipedia on mime pdas

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#67623]
## Testmerges:
The following pull requests are currently test merged:
[#65791: 'Optimizes Runechat' by Kylerace at commit 775d002c97](https://www.github.com/tgstation/tgstation/pull/65791)
[#67385: 'Reduces the point reduction on traitor objectives significantly' by Watermelon914 at commit 9a9f35340b](https://www.github.com/tgstation/tgstation/pull/67385)
[#67116: 'TGUI Say: Upgrades chat input with modern features' by jlsnow301 at commit 9edb8d8709](https://www.github.com/tgstation/tgstation/pull/67116)
[#67615: 'Fix Dynamic midrounds spawning heavies significantly earlier than they're supposed to' by Mothblocks at commit 28b5169054](https://www.github.com/tgstation/tgstation/pull/67615)

## Reproduction:
pretty sure it's been like this since the tablet change but noone's noticed
used to be a big list of emojis and the code to use them in the mime pda but that functionality has not carried over to tablets

**Comment by etherware-novice** [comment]
i will work on this
