### ISSUE TITLE
Sleeping Carp gives immunity to nuke shuttle turrets (Balance issue)

### ISSUE THREAD

**Issue by Thunder12345** [tgstation/tgstation#67633]
## Reproduction:

1. Buy sleeping carp
2. Turn on throw mode
3. Run onto the nuke shuttle
4. Watch in amusement as the operatives are unable to use their own shuttle because turret projectiles are randomly flying around the shuttle.

This seems like a place where an exception to sleeping carp might have to be made for the sake of balance, as a single traitor with sleeping carp can, if they are so inclined, render the nukies own shuttle uninhabitable to them, while being unreasonably difficult to dislodge (Can't shoot them because sleeping carp, if you try to melee you take even more hits from the turrets)

**Comment by ATH1909** [comment]
skill issue

**Comment by Shadowflame909** [comment]
the power of dynamic. A killer wizard/changeling/ascended heretic(ehh)/the owl can also do this

Intended antag vs antag chaos

**Comment by Mooshimi** [comment]
Feel free to open a pr to balance this, but it's intended behaviour.
