### ISSUE TITLE
Unable to relink Lathe over to another zlevel on Tram

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#67638]
## Round ID:
[184574](https://scrubby.melonmesa.com/round/184574)

## Testmerges:
#65791
#67385
#67116
#67615

## Reproduction:
> med lathe got unlinked
> go to silo and get a link
> cant link lathe "its too far away"
> med crippled for the rest of the round

**Comment by antropod** [comment]
I blame this
https://github.com/tgstation/tgstation/pull/66953

**Comment by antropod** [comment]
Just as expected, make a change that nobody asked for, break everything
