### ISSUE TITLE
Watermelons are SEVERELY broken and are exploding? And also give no biomass.

### ISSUE THREAD

**Issue by plutori** [tgstation/tgstation#67649]
Reporting client version: 514.1584

## Round ID:
[184600](https://scrubby.melonmesa.com/round/184600)

## Testmerges:
- [TGUI Say: Upgrades chat input with modern features](https://www.github.com/tgstation/tgstation/pull/67116)
- [Reduces the point reduction on traitor objectives significantly](https://www.github.com/tgstation/tgstation/pull/67385)

## Reproduction:

1. Plant some watermelons
2. Get their potency above a certain value (Not sure what the exact value is, but on low-mid potency the watermelons are just producing a chemical reaction that doesnt do anything, but on higher potency they will explode.). In the shift in question, just using EZ nutrient, they watermelons exploded on the second time they were harvested with EZ nutrient fertilizer.
3. Harvest the watermelons (works both with hand harvesting and a plant bag!)
4. Die with all of your limbs blown off

Also, watermelons appear to only be giving 1 biomass currently. To reproduce that, just shove them in a biogenerator and activate it.

**Comment by plutori** [comment]
> did you plant them next to bananas

They were 2 tiles from bananas, actually. And I see what you're getting at, it could have been a potassium and water explosion via cross pollination. If so, sorry to waste your time.

**Comment by interestingusernam3** [comment]
Maybe the plant between the watermelon and the banana got the potassium gene from the banana and the watermelon got it from that plant?

**Comment by YakumoChen** [comment]
I can't confirm the biomass thing, unless hydro was changed very recently I was able to get a huge amount of biomass from watermelons playing them a few days ago

**Comment by Iamgoofball** [comment]
Biomass is based on nutrient value iirc, and explosions clear the contents, so I really think it's because the watermelons were exploding due to water-potassium.

I love reagent code.
