### ISSUE TITLE
Ninja MODsuit storage is unusable; says you need to retract the parts even if it's fully activated.

### ISSUE THREAD

**Issue by castawaynont** [tgstation/tgstation#67658]
## Reproduction:
Be a Space Ninja
Attempt to click your MODsuit to open it and put stuff in it
be greeted with a message that says you need to retract the parts first
Might be an issue with the ninja MODsuit just not having a storage module

**Comment by YakumoChen** [comment]
it doesn't have a suit storage module.

**Comment by castawaynont** [comment]
if that's intended that's dumb ngl

**Comment by YakumoChen** [comment]
Ninja's modsuit is supposed to make it 1:1 with ninja before, which didn't start with a backpack, so that seems about even.
Although it doesn't have a jetpack either now, but honestly not a big deal.
