### ISSUE TITLE
Mousetrap is useless against assistants (humans).

### ISSUE THREAD

**Issue by Magic101lvl** [tgstation/tgstation#67651]
## Reproduction:
Make a mousetrap in craft menu, activate it, put in container, open this container and understand that it does not stun who activate it or damage stamina.

**Comment by nemvar** [comment]
Looking at the code, it appears this is unintended behavior. Mousetrap code needs another look in general.

**Comment by timothymtorres** [comment]
> Make a mousetrap in craft menu, activate it, put in container, open this container and understand that it does not stun who activate it or damage stamina.

If the person has gloves on, then they don't suffer any kind of damage.
