### ISSUE TITLE
ModSuits: Wearing insulated gloves doesn't apply when suited up

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#67688]
## Round ID: 
[184681](https://scrubby.melonmesa.com/round/184681)

## Testmerges:
https://github.com/tgstation/tgstation/pull/67669

## Reproduction:
1. Wear Captain's gloves, insulated gloves, etc.
2. Equip all parts of modsuit (cargo if it matters).
3. Activate modsuit.
4. Reattach a wire where one was bitten by a mouse.
5. Sometimes get shocked and sometimes don't, as if you don't have insulated gloves on.

**Comment by Fikou** [comment]
not much we can do here, you are not wearing the gloves, you are wearing the modsuit gauntlets

**Comment by Electronics** [comment]
Can we re-open this? Surely there must be some way to inherit the glove properties that were stored?
