### ISSUE TITLE
Using a "Proofing Potion" on clothes doesn't update the sprite

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#67689]
## Round ID:
Irrelevant

## Testmerges:
Irrelevant

## Reproduction:
1. Get possession of either a xenobio "Chill Potion" which fireproofs clothing, or an atmospherics "Pressure Proof" potion.
2. Use one the clothes you're wearing.
3. Notice the sprite in your inventory has changed but your player sprite wearing the clothes has not.
4. (You have to take them off and reequip to update sprite.)

**Comment by Sealed101** [comment]
resolved by #73627
