### ISSUE TITLE
StunProds not stunning

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#67697]
## Testmerges:
[#67669: 'Lemon attempts to optimize lighting [TM]' by LemonInTheDark at commit 9913284f94](https://www.github.com/tgstation/tgstation/pull/67669)
[#67116: 'TGUI Say: Upgrades chat input with modern features' by jlsnow301 at commit bf4fc4a932](https://www.github.com/tgstation/tgstation/pull/67116)

## Reproduction:
Build a stunprod via manual crafting, not menu (unsure if relevant.)
Try to stun people, then awkwardly laugh it off as a joke because they aren't falling down!!
(This has happened in multiple rounds on Sybil across yesterday and today as far as I am aware.

**Comment by castawaynont** [comment]
https://github.com/tgstation/tgstation/pull/67682 
closes this
