### ISSUE TITLE
Zombie powder is much weaker than it's supposed to be

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#67709]
![obraz](https://user-images.githubusercontent.com/68878861/173187243-d660bea1-3790-477a-a435-1a8a51b965af.png)

- The zombie powder is a hard-to-get chem with PH requirements, an exotic ingredient (KoiBeans, Carps, EMAG) and a very small output **_(results in 2u instead of 15u)._**
-  The chemical is deisgned to be used via ingestion, as described by the wiki.
![obraz](https://user-images.githubusercontent.com/68878861/173187253-71328906-d873-40f0-b72a-187158089e44.png)
- ### From the testing performed with a damp rag+mouth aim+combat mode: 
1. Reliably isnta-knocks out the target - works as advertised.
For reference, damp rag filled to capacity (5u) with chloral hydrate is NOT reliable.
2. Requires at least 4u to do anything.
3. The effect from 4u lasts a very short while. Little difference with the extra 1u.
For reference, chloral hydrate will do better if it does decide to work + the knock out time from ZP here **_was not enough to perform a forcefeeding taskbar_**.
![obraz](https://user-images.githubusercontent.com/68878861/173188061-55ada28a-797c-44a3-a566-795c425e8182.png)
4. The aforementioned capacity of the rag is the same as a sip (bite of food?) from a container, leaving only shot glass, pills, maybe cigars viable.
5. But then again, ZP **_is clearly not designed to be produced and applied in industrial quantities_**.
- ### Conclusion:

1. Zombie powder _**does not work as intended**_
2. The damp rag fandom is dying, repost if you are a true sleepyhead

**Comment by newfren** [comment]
regarding requiring at least 4u: the liver will shrug off 3u of toxin, perhaps this is the effect observed?

**Comment by Likteer** [comment]
> regarding requiring at least 4u: the liver will shrug off 3u of toxin, perhaps this is the effect observed?

Yup, confirmed with vincentius liver is most likely responsible for that, but he could find nothing about the rest.

**Comment by Shadowflame909** [comment]
I think the easiest solution to this is buffing damp rags. Them being able to hold the same liquid content as a syringe (15u) would be good

**Comment by Sealed101** [comment]
either the chemical itself got more robust or the liver is no longer such a powerhouse of toxin purging. in testing 5u applied via rag lasts ehh about 20-25 seconds, which is enough to forcefeed the victim more of the stuff at the very least.
https://github.com/tgstation/tgstation/pull/76666 https://github.com/tgstation/tgstation/pull/71937 https://github.com/tgstation/tgstation/pull/78657 for chemical changes that may have helped but i dunno
