### ISSUE TITLE
Ore silo on a different z-level cannot link (Tramstation)

### ISSUE THREAD

**Issue by Xander3359** [tgstation/tgstation#67708]
Reporting client version: 514.1583

## Round ID:
[184712](https://scrubby.melonmesa.com/round/184712)

## Testmerges:
- [Completely removes `proc_holders` from existence. Refactors all wizard, xeno, spider, and genetics powers to be actions. Also refactors and sorts ton of accompanying code. ](https://www.github.com/tgstation/tgstation/pull/67083)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Fix Dynamic midrounds spawning heavies significantly earlier than they're supposed to](https://www.github.com/tgstation/tgstation/pull/67615)
- [Lemon attempts to optimize lighting [TM]](https://www.github.com/tgstation/tgstation/pull/67669)
- [TGUI Say: Upgrades chat input with modern features](https://www.github.com/tgstation/tgstation/pull/67116)

**Comment by Xander3359** [comment]
Due to the ore silo being on a different z-layer on tram you cannot relink any techfabs once they are destroyed.

**Comment by Mooshimi** [comment]
lolololol

**Comment by dragomagol** [comment]
Might make sense to have it only disconnect on non-station Zs

**Comment by Mooshimi** [comment]
#67640

**Comment by msgerbs** [comment]
So... This is fixed right?

**Comment by JohnFulpWillard** [comment]
Yea
