### ISSUE TITLE
Minebot Passthrough doesn't function at all.

### ISSUE THREAD

**Issue by Xander3359** [tgstation/tgstation#67705]
Reporting client version: 514.1583

## Round ID:
[184708](https://scrubby.melonmesa.com/round/184708)

## Testmerges:
- [TGUI Say: Upgrades chat input with modern features](https://www.github.com/tgstation/tgstation/pull/67116)
- [Lemon attempts to optimize lighting [TM]](https://www.github.com/tgstation/tgstation/pull/67669)
- [Fix Dynamic midrounds spawning heavies significantly earlier than they're supposed to](https://www.github.com/tgstation/tgstation/pull/67615)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Completely removes `proc_holders` from existence. Refactors all wizard, xeno, spider, and genetics powers to be actions. Also refactors and sorts ton of accompanying code. ](https://www.github.com/tgstation/tgstation/pull/67083)

## Reproduction:
The minebot passthrough upgrade just doesn't work whatsoever. You can't shoot through the minebot, and the minebot can't shoot through you.

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/81940
