### ISSUE TITLE
Recycler destroys material stacks

### ISSUE THREAD

**Issue by MTandi** [tgstation/tgstation#67710]
The recycler seem to destroy non-alloy material sheets. Maybe due to some automatic stacking happening on the tile.

https://user-images.githubusercontent.com/3625094/173189906-df0ea2ce-7d0a-45bd-a55d-9ff104892f24.mp4

## Reproduction:

- Place recycler, throw iron sheets at it.
- It doesn't poop out a sheets back (However it properly sucks them in, since 1 iron sheet increases the internal material amount)
- If you try the same with non-sheet items, everything works correctly.

**Comment by timothymtorres** [comment]
Fixed by #67711
