### ISSUE TITLE
clear_camera_ref type mismatch: null -= the security camera

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#67729]
## Testmerges:
[e](https://github.com/tgstation/tgstation/pull/67116)
## Reproduction:
![brave-22 37 10 669](https://user-images.githubusercontent.com/85910816/173232246-2e6752d8-ef9c-477c-909b-24f0768faa75.png)

**Comment by JohnFulpWillard** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/78839
