### ISSUE TITLE
atom_examine overridden. Use override = TRUE

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#67728]
## Testmerges:
https://github.com/tgstation/tgstation/pull/67116

## Reproduction:
![image](https://user-images.githubusercontent.com/85910816/173232158-749d1669-4260-45b9-9d99-b2f9418d2a27.png)

**Comment by Sealed101** [comment]
got fixed at some point in time
https://github.com/tgstation/tgstation/blob/fc41c78b8416b3610f78864ae6e9a563c27792d6/code/modules/surgery/organs/internal/heart/heart_ethereal.dm#L91
