### ISSUE TITLE
Clowns activating holographic swords brute damage themselves.

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#67739]
Reporting client version: 514.1583

## Round ID:
[184801](https://scrubby.melonmesa.com/round/184801)

## Testmerges:
- [TGUI Say: Upgrades chat input with modern features](https://www.github.com/tgstation/tgstation/pull/67116)

## Reproduction:

Be a clown.
Grab a holographic sword.
Spam Z.
Watch you crit yourself.

While the interaction of the clown accidentally boinking themselves with weapons seems intended (and appropriate), the damage type delivered by the holographic sword appears to be brute when it would be more appropriately stamina

**Comment by SethLafuente** [comment]
Tested happens with the clumsy trait as expected;



![Image](https://github.com/tgstation/tgstation/assets/84478872/caf9225d-d685-4718-b45e-334fd2e24728)
