### ISSUE TITLE
donk pockets never cool down

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#67751]
## Round ID:
NA
## Testmerges:
irrelevant

## Reproduction:

> examine donk pocket box (the default one)
> says that it cools if not eaten after 7 minutes
> microwave donk pocket
> wait
> wait
> not cooled down
> check code
> nothing about donk pockets cooling down

should probably either remove the donk pocket box saying it, or make donk pockets cool

relevant code: 
https://github.com/tgstation/tgstation/blob/1706ffa2d324781fdf58ed8336e8be0cdbd49a19/code/game/objects/items/storage/boxes.dm#L452-L454

**Comment by private-tristan** [comment]
they've never cooled for as long as I've played (2019 or so?), was probably lost to time

**Comment by Shadowflame909** [comment]
We must change their description. Future microwaves will keep things warm for years to come

**Comment by davethwave** [comment]
There was a PR a long while back that claimed it would nerf donkpockets by making them only be in a warmed state and have omnizine in them for only 5ish minutes. PR didn't work after merge, nobody noticed and nobody cared.

**Comment by Mooshimi** [comment]
Feature... Universe bending donk pockets are a part of tg
