### ISSUE TITLE
Cows can catch fire with no visible effect (outside of an orange glow)

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#67765]
Reporting client version: 514.1584

## Round ID:
[184860](https://scrubby.melonmesa.com/round/184860)

## Testmerges:
- [Completely removes `proc_holders` from existence. Refactors all wizard, xeno, spider, and genetics powers to be actions. Also refactors and sorts ton of accompanying code. ](https://www.github.com/tgstation/tgstation/pull/67083)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Lemon attempts to optimize lighting [TM]](https://www.github.com/tgstation/tgstation/pull/67669)
- [TGUI Say: Upgrades chat input with modern features](https://www.github.com/tgstation/tgstation/pull/67116)
- [The Tilening V2 - Damaged Tile Overlays Edition](https://www.github.com/tgstation/tgstation/pull/67761)

## Reproduction:

Just something I noticed while messing around in the thunderdome. Flamethrower goes off and the fire reaches the cows, and a little red message pops up in chat saying that the cow caught fire.

You can tell they're on fire as they have an orange glow to them, and bumping into them sets you ablaze.
![dreamseeker_4W3vD0AyRu](https://user-images.githubusercontent.com/33107541/173455225-3868a7df-bdac-4746-b09a-25337ebe292e.png)
![MDT6D8GNaw](https://user-images.githubusercontent.com/33107541/173455242-090cfb7d-4ce6-4e13-ba7d-89ced4be83df.png)

**Comment by Mooshimi** [comment]
This applies to a lot of simplemobs I think.
(No comment on shooting a flamethrower at a cow in your freetime...)

**Comment by timothymtorres** [comment]
Related to #65174

**Comment by Mothblocks** [comment]
Cows aren't simple mobs, they're basic mobs.

Which means it is likely the same issue as #65174, since those are direct subtypes of /living, and are also not simple mobs.
