### ISSUE TITLE
Bluespace Navigation Gigabeacons don't work

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#67762]
Reporting client version: 514.1566

## Round ID:
[184856](https://scrubby.melonmesa.com/round/184856)

## Testmerges:
- [TGUI Say: Upgrades chat input with modern features](https://www.github.com/tgstation/tgstation/pull/67116)

## Reproduction:
Build a gigabeacon, try jumping to it with whiteship/other shuttles, can't.

Tried giving it a powered area, tried with and without floor tiles underneath, don't work.

**Comment by timothymtorres** [comment]
Might be related to https://github.com/tgstation/tgstation/issues/60394

**Comment by Striders13** [comment]
fixed some time along the years
