### ISSUE TITLE
Infiltrator case too small to fit all suit parts

### ISSUE THREAD

**Issue by bob-b-b** [tgstation/tgstation#67770]
## Reproduction:
Infiltrator case is too small to fit all the suit parts after they've been taken out.

Also the functionality of quickly equiping and unequiping the whole suit via the case doesn't work but that might be intended dunno if the wiki is outdated on that.

**Comment by necromanceranne** [comment]
The box just needs its storage capacity increased in the storage component. Easy enough fix. Have a look at the storage case and give it something like max weight of about 24 or something.

There was never a quick swap functionality.

**Comment by necromanceranne** [comment]
Closed because the fix was coupled with bigger things. Please fix it I made it and I'm telling you it is a bug.
