### ISSUE TITLE
Tilening broke tile

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#67786]
## Testmerges:
#67761

## Reproduction:
![dreamseeker-20 34 09 417](https://user-images.githubusercontent.com/85910816/173711923-2bb0e351-06cb-41ec-b98d-e269c045321e.png)

**Comment by Mooshimi** [comment]
![image](https://user-images.githubusercontent.com/85910816/173720985-ff2e6e2d-dcfc-4b5c-984d-99574acb051e.png)

**Comment by Imaginos16** [comment]
Fixes in latest commit.
