### ISSUE TITLE
Janitor issues during round (spicy start)

### ISSUE THREAD

**Issue by BrisketBilly** [tgstation/tgstation#67822]
## Testmerges:
[#65791: 'Optimizes Runechat' by Kylerace at commit 775d002c97](https://www.github.com/tgstation/tgstation/pull/65791)
[#67669: 'Lemon attempts to optimize lighting [TM]' by LemonInTheDark at commit 9913284f94](https://www.github.com/tgstation/tgstation/pull/67669)
[#67116: 'TGUI Say: Upgrades chat input with modern features' by jlsnow301 at commit d83f53869d](https://www.github.com/tgstation/tgstation/pull/67116)

## Reproduction:
Joined the round over an hour in as janitor, and had an unlinked ID (correctly titled) and an PDA titled "()", and missing my survival box. In my pocket I had a .357 speed loader full of rounds, but no revolver to go with it. Downloaded and hosted a fresh copy from git and in the two cycles of a blank janitor start, no account/PDA issues, but still had the speed loader and came with a gun those times.

**Comment by Ryusenshu** [comment]
The gun part and the loader is from the "garbage day" "event"
Happens once a year on that day
Its normal right now that a jannitor starts with it right now

Not sure about the missing survival box though

**Comment by BrisketBilly** [comment]
Yeah, might just write this one off then. Wasn't able to reproduce the PDA/ID/survival box bug on local testing, but did see another SSD janitor with it the night before, so might be intermittent.

**Comment by dragomagol** [comment]
Fixed by above PR
