### ISSUE TITLE
Prefs menu felinids are Sphynx cats

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#67827]
Issue reproduction:
Go to the preferences menu
The catperson picture is bald, showing as a sphynx cat
![image](https://user-images.githubusercontent.com/23585223/174201717-da42a926-0ec4-4dcb-a8ec-d1c684d5066b.png)
![image](https://c.tenor.com/b0GB8KqB68YAAAAS/bingus-bingus-cult.gif)

**Comment by notfrying1pans** [comment]
bingus

**Comment by Mothblocks** [comment]
not my fault its kapus

**Comment by necromanceranne** [comment]
Bingus

**Comment by nemvar** [comment]
bald man bald cat bald mancat

**Comment by Mothblocks** [comment]
it is a bug they're supposed to have hair :(

**Comment by Mooshimi** [comment]
Didn't they *just* fix this recently
