### ISSUE TITLE
Snail eyes missing texture (?)

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#67830]
Reporting client version: 514.1583

## Round ID:
[185030](https://scrubby.melonmesa.com/round/185030)

## Testmerges:
- [TGUI Say: Upgrades chat input with modern features](https://www.github.com/tgstation/tgstation/pull/67116)

## Reproduction:

Spawn a human
Replace its eyes with snail eyes
See ERROR
![image](https://user-images.githubusercontent.com/3789327/174164104-b72146cc-9c0c-48fb-a299-2014f44672fc.png)

**Comment by Profakos** [comment]
Looks like this was fixed in #68013
