### ISSUE TITLE
help my NToS is seems to be broken, and I cant see the chat.

### ISSUE THREAD

**Issue by fishingsman** [tgstation/tgstation#67839]
## Reproduction:

A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation

![image](https://user-images.githubusercontent.com/102311071/174315225-6aaa88f8-8b04-4fd4-a3b2-5e493fdc7ae4.png)

I dont know what to do bro this is so scary bro I am so sad rn sobbin

**Comment by fishingsman** [comment]
aLSO i RELAUNCHED GAME AND ITS STIL THERE BRO THIS IS SO SCARY

**Comment by Crushtoe** [comment]
Same problem. Fancy chat is broken, persists across relogs, relaunches.

```
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 Script error.
   at https://tgstation13.download/byond/assets/86/asset.8614c204a358b39d682c395cd7eb7797.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Zoom 3.6.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
```

**Comment by Mooshimi** [comment]
#53997
