### ISSUE TITLE
Autolathes cannot eject any other material except for metal and glass

### ISSUE THREAD

**Issue by Imaginos16** [tgstation/tgstation#67847]
## Reproduction:
Simply insert any ore or material inside an autolathe, and find out you can't eject it. This was initially found on shiptest, where inserting different materials in an autolathe is a ghetto, but efficient way to refine ores. Tested it here to make sure it was also the case and sure enough, the oversight is present here as well. As a result of this bug, to currently extract the refined materials, you have to deconstruct the autolathe.

I imagine the fix should be easy enough- just adding a button for all other materials such as gold, uranium, diamonds, et cetera.

**Comment by RandomGamer123** [comment]
Should be closed by #67848
