### ISSUE TITLE
Chilled Bluespace extract doesn't work

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#67842]
## Reproduction:

Chilled Bluespace extract - Station Z level - fill with plasma and link someone with it - no do_after countdown and no effect.

**Comment by Salex08** [comment]
I tested it on a local server and it worked fine, am I missing something?

**Comment by Mooshimi** [comment]
This was *recently* used on sybil in this manner:
[Bluespace](https://tgstation13.org/wiki/Guide_to_xenobiology#Bluespace_Slime) - Touching someone or a creature with it adds/removes them from a list. Activating the extract will try to summon everyone on the list to you after a few seconds. Targets get bubble effects on them and can resist out of it.

So I believe this is fully functional. Please reopen if you find out this had some specific circumstances required to fail.
