### ISSUE TITLE
TG Say: checking past messages deletes current one

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#67851]
## Reproduction:

Open Say
Type a message
Press the up key and see the last message you typed
Press down to go back to the current mess- oh, where'd it go?

I feel like we should have safeguards against immediately losing your typed message to a commonly used key, especially a movement key.

It's a much worse problem when you're used to having a traditional text box and pressing UP goes up a line instead of doing something else.

**Comment by YakumoChen** [comment]
Unrelated but I miss the text box being moveable and being able to have multiple Say windows open at once

**Comment by Mothblocks** [comment]
you can move it around its just a weird boundary

**Comment by jlsnow301** [comment]
I will say that this was considered and "not a bug". 
I played warframe for some time which has this sort of "sticky input" (ie: unsent messages needed to either be cleared or entered, they never left). It caused numerous very awkward situations of me typing without looking and sending an hour old draft + message on accident
This is why tgui say is more safe than sorry by just deleting your draft messages.

I can consider this, if you're sure, as a user preference for the future

**Comment by Mothblocks** [comment]
@jlsnow301  I'm confused, it sounds like pressing up gives you your message history but pressing down doesn't give you the message you were typing. That's unintuitive, it doesn't need to keep every unsent message in history, just the one you were typing.

**Comment by jlsnow301** [comment]
> @jlsnow301  I'm confused, it sounds like pressing up gives you your message history but pressing down doesn't give you the message you were typing. That's unintuitive, it doesn't need to keep every unsent message in history, just the one you were typing.

I don't mean a record of drafts either- it deletes your unsent message in a number of cases, erring on caution. 
I don't see how that's terribly unintuitive with how uncommon this would occur. 
I'll be adding this as a pref for chat history...

**Comment by YakumoChen** [comment]
> I played warframe for some time which has this sort of "sticky input", ie: unsent messages needed to either be cleared or entered, they didn't delete on their own. It caused numerous, very awkward situations of me typing without looking and sending an hour old draft + message on accident (I didn't press enter for a reason!)

It's a problem when deleting your message is tied to a movement key and also a key commonly used to navigate a textbox
