### ISSUE TITLE
TramStation Disposal'd Borgs can get "softlocked" in cargo behind plastic flaps

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#67863]
## Round ID:
[185156](https://scrubby.melonmesa.com/round/185156)

## Testmerges:
N/A

## Reproduction:
![Screenshot_1](https://user-images.githubusercontent.com/95751821/174462686-ec5364fe-2d68-4eca-bd38-6d70ae049145.png)

**Comment by timothymtorres** [comment]
This is probably an issue even with simple mobs.

**Comment by Ryusenshu** [comment]
edit: more info

from what ive seen the saw didnt do any damage to it
![Screenshot_2](https://user-images.githubusercontent.com/95751821/174485200-a954223b-36f9-47da-a53f-c409566506a4.png)

they got teleported out by admin
![Screenshot_4](https://user-images.githubusercontent.com/95751821/174485306-6bbcdcf5-b80b-4a06-838f-21707ef98383.png)

**Comment by ATH1909** [comment]
> This is probably an issue even with simple mobs, however I don't think this should be considered a bug. Human mobs are dexterous enough to slider under the flaps. Borgs can just destroy the flaps if it's in their way or dismantle them.
> 
> @san7890 care to share your opinion on this?

IIRC, they can't, as plastic flaps have 100 melee armor:
`armor = list(MELEE = 100, BULLET = 80, LASER = 80, ENERGY = 100, BOMB = 50, BIO = 0, FIRE = 50, ACID = 50)`

**Comment by itseasytosee** [comment]
Borg's aren't simple mobs, they're silicons

**Comment by san7890** [comment]
Why do plastic flaps have 100 melee armor, lol

**Comment by san7890** [comment]
No? I just tried and it just keeps saying "without leaving a mark" on both an oxygen tank and captain's saber.

**Comment by Inari-Whitebear** [comment]
> > Why do plastic flaps have 100 melee armor, lol
> 
> have you tried hitting plastic flaps with a blunt object, or knife? it just moves away.

Sure... but if it just moves away, shouldn't the borg just be able to move through?

**Comment by JohnFulpWillard** [comment]
bozo down
