### ISSUE TITLE
Statue netherworld mob in cytology being way too strong

### ISSUE THREAD

**Issue by bob-b-b** [tgstation/tgstation#67867]
## Reproduction:
If im reading the changes correctly this added the mob to the cytology netherworld pool #67105 while fixing it's broken spells.
I like the mob as it's pretty unique but way too strong for cytology/xenobio with 50k HP and being able to run through doors, windows. 

https://youtu.be/8n-KS2KP2lg?t=1988 timestamped video of it in action

Don't really want to see it removed but one possible solution could be having the cytology version be way weaker in terms of total health, object damage

**Comment by Shadowflame909** [comment]
The health got reduced to 5k

Chisels do 40x damage too it. And it can't move while being stared at

Not a bug. Just fighting it wrong

**Comment by bob-b-b** [comment]
Unless im misreading the code only the snowmen ruin variant has 5k health, but even then megafauna has almost half that usually (bubblegum/ash - 2500) the statue is still 50k

**Comment by moocowswag** [comment]
Id say it needs to be removed so nobody makes a sentient one and makes an unsuspecting player click yes and have to play as it not knowing what they are getting into.

Its not fun not being able to move for 5 minutes at a time.

**Comment by ATH1909** [comment]
> ## Round ID:
> ## Testmerges:
> ## Reproduction:
> If im reading the changes correctly this added the mob to the cytology netherworld pool #67105 while fixing it's broken spells. I like the mob as it's pretty unique but way too strong for cytology/xenobio with 50k HP and being able to run through doors, windows.
> 
> https://youtu.be/8n-KS2KP2lg?t=1988 timestamped video of it in action
> 
> Don't really want to see it removed but one possible solution could be having the cytology version be way weaker in terms of total health, object damage

they're supposed to be pretty much unkillable, as they're unable to move while any non-blind, non-silicon is looking at them while they're not in the dark. a saner health total will just result in them being effortlessly bopped if someone walks in on them while they're trying to gank someone, as that effectively hardstuns them until their AoE blindness spell comes off of cooldown again.

do NPC weeping angels even use their AoE blindness spell?

**Comment by Sealed101** [comment]
unless i'm missing something the cyto cell line did get removed and they only appear in mapping/admemery/icebox pool transformation. there's also the chisel
