### ISSUE TITLE
Offered soul to soul blade and instead got sent to error room.

### ISSUE THREAD

**Issue by Shellton123** [tgstation/tgstation#67888]
## Reproduction:

So I elanced myself for no reason and died, Kraven lockheart needed a soul for his blade and I offered, this showed up twice then when I was choosed instead of going to his blade I was sent to the place where you go if an error happens. This is what it looked like
![error](https://user-images.githubusercontent.com/83558207/174542050-6a252ff9-f6ea-4b7b-bc6d-3bc38e14eadd.PNG)

EDIT: After testing I found out I am an immortal shade.

**Comment by moocowswag** [comment]
https://github.com/tgstation/tgstation/issues/61935

similar issue with nullrod from lavaland.
