### ISSUE TITLE
Access Problems with Lavaland Outpost on Metastation

### ISSUE THREAD

**Issue by HabGear** [tgstation/tgstation#67899]
## Round ID:

[185263](https://scrubby.melonmesa.com/round/185263)

## Testmerges:

N/A

## Reproduction:

The now splitted Lavalandoutpost on Metastation has an Accessproblem with the part of it that has the Tcomms. You are able to access/open the airlocks from the outside, but not from the inside. I got trapped in those maints, where the ghost is, as miner and had to adminhelp to get out of there.
(the admin set the doors to emergency).
As miner you shouldnt have access to this area, but like with other maints you should be able to escape once in there.
With how its currently is i assume the doors are the wrong way around.
![grafik](https://user-images.githubusercontent.com/28983661/174680110-983449a6-3f55-4675-8872-01c50797a103.png)

**Comment by dragomagol** [comment]
@Thunder12345

**Comment by san7890** [comment]
This is fixed in the production (full-merged) version of this map.
