### ISSUE TITLE
EMP'd (?) Server vanished after crowbar-ing it (and was unable to reboot)

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#67891]
## Round ID:
[185234](https://scrubby.melonmesa.com/round/185234)

## Testmerges:
#67796
#65791
#67083

## Reproduction:
> Normal and Master Server is sparkly
> 
![Screenshot_3](https://user-images.githubusercontent.com/95751821/174577071-c1c011a3-57ad-4314-b883-fcd118860b41.png)
> turn it on and off again
> doesnt work
> tried rebuilding it and screwdriver crowbar'd the server
> vanished

![Screenshot_1](https://user-images.githubusercontent.com/95751821/174577270-dfbddfce-c0b5-416a-a391-eb1a86ac0498.png)

> build new one, also broken and sparkly
> fixed itself suddenly later on

**Comment by Sealed101** [comment]
fixed in #70394
