### ISSUE TITLE
optical meson scanners broke

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#67905]
RoundID 185278

put on some mesons notice they don't give you the normal meson vision
game is literally unplayable fix this now

**Comment by trexter5555** [comment]
> potentially caused by #67902 ?
> 
> please include testmerges in your issue if you're unsure

i dont remember what was testmerged but i think that one was, ye

**Comment by ArcaneDefence** [comment]
https://scrubby.melonmesa.com/round/185278
That pr was testmerged that round.

**Comment by LemonInTheDark** [comment]
seen it, thanks
