### ISSUE TITLE
Jungle Salad cant be eaten

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#67928]
## Round ID:
[185344](https://scrubby.melonmesa.com/round/185344)

## Testmerges:
N/A

## Reproduction:
> See tasty looking Jungle Salad
> Cant be eaten
> Grab the lesser tasty looking Fruit Bowl instead

**Comment by carshalash** [comment]
gimme 5

**Comment by Ryusenshu** [comment]
Fix has been merged
