### ISSUE TITLE
You can't push objects while on a wheelchair

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#67923]
split from #67912 to keep things tidy

You can't push objects while on a wheelchair using the paraplegic quirk, though you can still pull them.
I don't know if this is intentional or not-- it might just be a feature of the vehicle code and the fact that motorised wheelchairs crash if they're upgraded too much. This makes it easy to get stuck in corners-- toxins is Interesting with this quirk. The DIY fix is to get out of the wheelchair, because somehow you can push objects. better when lying on the ground than while anchored to a fairly solid surface.

**Reproduction:**
Sit on a wheelchair and try to push a canister.

**Comment by nemvar** [comment]
This never struck me as a bug. It happens with all vehicles.
