### ISSUE TITLE
Fluid tank rapturing inconsistencies

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#67933]
## Reproduction:

1.  Take a water tank, rapture it by damaging too much or shooting it with a plasma cutter. The water spread from this can extinguish fires (hotspots included), slips people, can freeze from atmos... but doesn't clean the tiles it's on.
2. Take a welding fuel tank, add iron to it so it's plumbing compatible. Rapturing it will not create an explosion and instead spreads the recently added fuel pools as if it'd be water.

**Comment by Sealed101** [comment]
fixed by https://github.com/tgstation/tgstation/pull/78976 or similar
