### ISSUE TITLE
Fishing... maybe broken???

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#67942]
Reporting client version: 514.1584

## Round ID:
[185392](https://scrubby.melonmesa.com/round/185392)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Mining Outpost Overhaul: Island Living Edition](https://www.github.com/tgstation/tgstation/pull/67796)
- [Completely removes `proc_holders` from existence. Refactors all wizard, xeno, spider, and genetics powers to be actions. Also refactors and sorts ton of accompanying code. ](https://www.github.com/tgstation/tgstation/pull/67083)

## Reproduction:
Two assistants, one human and one felinid.
They share a rod, bait, and fishing spot. Everything between the two is the same.
Their rod uses flexible reel, a shiny hook, and extra slimy worms. 
The fishing spot is a moisture trap in maints.
The felinid catches a ratfish on every attempt. Five in total.
The human, despite completing the minigame PERFECTLY every time, never catches anything. It always "gets away".
The human tries everything. He uses different bait, intentionally performs imperfectly on the minigame, a new fishing spot, even going as far as turning off his light, lest it scare the fish. But alas, he never catches a single fish.
They are both perplexed.

No seriously man what the fuck. I've played SDV before, I was great at that kind of fishing. I have all the achievements. I've tried mixing up all the variables. You can't seriously be telling me 20+ attempts in a row were just bad luck or something, on perfect games with different reels, baits, hooks, and locations.

**Comment by AnturK** [comment]
There's a lot of runtimes for that round for hitting the below minimum fishing time abuse check. Though if you tried intentionally performing worse and it didn't help that's bit annoying. Was the server lagging badly when fishing ?
