### ISSUE TITLE
Broken give notif

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#67940]
Reporting client version: 514.1584

## Round ID:
[185392](https://scrubby.melonmesa.com/round/185392)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Mining Outpost Overhaul: Island Living Edition](https://www.github.com/tgstation/tgstation/pull/67796)
- [Completely removes `proc_holders` from existence. Refactors all wizard, xeno, spider, and genetics powers to be actions. Also refactors and sorts ton of accompanying code. ](https://www.github.com/tgstation/tgstation/pull/67083)

## Reproduction:
1. Get offered something
2. Person offering drops item on ground
3. Person walks away
4. You are now stuck with the status effect thing of being offered something. Clicking it does not get rid of it. Relogging does not. Getting offered and accepting something else does not.

![image](https://user-images.githubusercontent.com/44104681/175194256-7f41d760-3d25-4e65-b753-44b4d1083699.png)

I fucking hate this bug so fucking god damn much. It's happened multiple times over the last few months (?) and I assumed there MUST be a bug report already. I actually bothered to check this time and couldn't find one. So here it fucking is. I hate this thing so much. It makes me so unreasonably angry. Fuck give.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/45d2cdb3187e9b1b5a03364907e67916529735f9/code/modules/mob/living/carbon/inventory.dm#L195-L244

https://github.com/tgstation/tgstation/blob/45d2cdb3187e9b1b5a03364907e67916529735f9/code/datums/status_effects/neutral.dm#L214-L235

Looks like in the `dropped_item` proc that the `removed_candidate` proc needs to be added.

**Comment by etherware-novice** [comment]
im pretty sure this is alreaedy fixed

**Comment by Sealed101** [comment]
yeah
