### ISSUE TITLE
Detective ON/OFF, asisstant LOW/MEDIUM/HIGH. Good job, good fix.

### ISSUE THREAD

**Issue by fishingsman** [tgstation/tgstation#67947]
## Reproduction:

just go to occupation menu in character preferences and you see this... NOW THERE IS BIG CHANCE TO BECOME DETECTIVE! but finally adjustable chance to become an assistant. I think this is a bit feature, a bit bug
![image](https://user-images.githubusercontent.com/102311071/175269261-291b81fe-d2f4-4941-8526-b70093f92b2c.png)

**Comment by Mothblocks** [comment]
This is a station trait.
