### ISSUE TITLE
OldStation Firelock Issues (NOT ACTIVE TURFS)

### ISSUE THREAD

**Issue by Jolly-66** [tgstation/tgstation#67956]
## Round ID:
Tested locally.

## Reproduction:

I have 0 idea why the firelocks are getting down dirty, but they are.

https://user-images.githubusercontent.com/70232195/175390519-36e25672-b3e4-4b8d-9e80-8ed8afaaf4c1.mp4

**Comment by LemonInTheDark** [comment]
this is likely my fault, from #66250 
will look into it when I get the chance

**Comment by Jolly-66** [comment]
@LemonInTheDark 
I think this got fixed somewhere, not sure where to be exact but its fixed.
