### ISSUE TITLE
Mech tgui does not let you drop some crates from cargo compartment

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#67960]
## Round ID:
[185430](https://scrubby.melonmesa.com/round/185430)

## Testmerges:
None are relevant to the issue

## Reproduction:
Get a ripley mech, pick up a crate with a long name, try to drop the crate using the tgui menu
![image](https://user-images.githubusercontent.com/75639936/175381847-925ea8c6-ae4e-4f28-adad-c59c2298c710.png)
you can alleviate this problem by making the window wider but this does not work for longer names

**Comment by raffclar** [comment]
Confirmed very annoying
![image](https://user-images.githubusercontent.com/32263167/177044236-515693de-ed00-40f0-88e5-e858baed2802.png)
Working on a fix now.
