### ISSUE TITLE
Traitor objective "Plant a bug" bonus reputation does not count towards objectives

### ISSUE THREAD

**Issue by Edelor68** [tgstation/tgstation#67977]
## Reproduction:

When you do the traitor objective of stealing a high-value item and planting a bug on it, it is possible to gain bonus reputation if you keep the item near you the entire time. This reputation does not count towards the end of the round objective of gaining a certain amount of reputation.

![image](https://user-images.githubusercontent.com/85312201/175568627-c06c3bf1-8d22-4374-9385-8dd6eecd5998.png)

**Comment by rasepretep** [comment]
Can confirm. Received the extra TC for completing the bonus objective, but didn't get extra reputation in round-end.

**Comment by Profakos** [comment]
Since the end of round rep objective does not exist anymore, this could be closed.

**Comment by JohnFulpWillard** [comment]
Bugging objective no longer exists, sorry

**Comment by JohnFulpWillard** [comment]
Nvm wrong bug

**Comment by JohnFulpWillard** [comment]
nvm nvm these bugs were also removed
