### ISSUE TITLE
Piano doesn't use the broken sprite

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#67980]
It doesn't use it when heavily dmged or falling apart, disappears upon destruction (duh).
![obraz](https://user-images.githubusercontent.com/68878861/175652556-7dbcde50-3009-490c-bee6-d1710429ef2f.png)

**Comment by timothymtorres** [comment]
I'm surprised this wasn't reported sooner.  This has been a known thing for years and it was probably overlooked.
