### ISSUE TITLE
Canisters are almost completely invisible

### ISSUE THREAD

**Issue by RazorManager89** [tgstation/tgstation#67992]
## Round ID
185505

## Testmerges
[#65791: 'Optimizes Runechat' by Kylerace at commit 775d002c97](https://www.github.com/tgstation/tgstation/pull/65791)
[#67796: 'Mining Outpost Overhaul: Island Living Edition' by Thunder12345 at commit 6aff904b99](https://www.github.com/tgstation/tgstation/pull/67796)
[#67083: 'Completely removes `proc_holders` from existence. Refactors all wizard, xeno, spider, and genetics powers to be actions. Also refactors and sorts ton of accompanying code. ' by MrMelbert at commit 7611036e06](https://www.github.com/tgstation/tgstation/pull/67083)

## Reproduction
Go to anywhere with a canister and look at it. It will be completely invisible, save for the capacity indicator. You can only interact with the canister if you click on the light.
The issue persists between rounds.
![image](https://user-images.githubusercontent.com/37266586/175756944-6b7ae7de-12bf-4282-8f1e-38f16fbac358.png)

**Comment by dragomagol** [comment]
This doesn't seem to be happening on any of the other servers, and Manuel wasn't letting me connect to check if it was still happening there.

**Comment by CoffeeDragon16** [comment]
Couldn't reproduce on local

**Comment by nemvar** [comment]
Is it still happening? Have you tried clearing your byond cache?

**Comment by RandomGamer123** [comment]
Still happening on terry

**Comment by JohnFulpWillard** [comment]
is this still happening

**Comment by RandomGamer123** [comment]
Not that I know of

**Comment by KliperX** [comment]
I have the same issue with fresh build, also PDAs have no sprites but i think someone else already made a issue about that
![Zrzut ekranu 2024-03-01 174929](https://github.com/tgstation/tgstation/assets/93185091/cc7b3f45-a97e-4880-9ea5-944bc4ac8eef)

**Comment by Sadboysuss** [comment]
is this still happening?
