### ISSUE TITLE
Cannot access and log into ce's power flow control console as a borg.

### ISSUE THREAD

**Issue by Gremyo** [tgstation/tgstation#68049]
Reporting client version: 514.1585

## Round ID:
[185685](https://scrubby.melonmesa.com/round/185685)

## Testmerges:
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)
- [Updates the sprites for bullets (inflight), adds pellet sprites, redoes the thermal projectile sprites](https://www.github.com/tgstation/tgstation/pull/67856)
- [Completely removes `proc_holders` from existence. Refactors all wizard, xeno, spider, and genetics powers to be actions. Also refactors and sorts ton of accompanying code. ](https://www.github.com/tgstation/tgstation/pull/67083)

## Reproduction:

Attempt to access the power flow control console in the ce's office as a borg.

**Comment by nichlas0010** [comment]
https://github.com/tgstation/tgstation/blob/375a20e49b593c57bf55c2f0ba512cf346d09ffe/code/game/machinery/computer/apc_control.dm#L35

Seems intentional

**Comment by Ryusenshu** [comment]
Yeah intentional
Imagine how strong a single emagged/subverted/malf borg would be with remote access to all apcs
