### ISSUE TITLE
Food and drinks created by silver slimes are not actually disgusting

### ISSUE THREAD

**Issue by Edelor68** [tgstation/tgstation#68058]
## Testmerges:
Round ID: [185698](https://scrubby.melonmesa.com/round/185698)
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [511aa8a5ab47d1154a0b179d58682dc70db28f82](https://www.github.com/tgstation/tgstation/commit/511aa8a5ab47d1154a0b179d58682dc70db28f82)
The following pull requests are currently test merged:
[#67083: 'Completely removes `proc_holders` from existence. Refactors all wizard, xeno, spider, and genetics powers to be actions. Also refactors and sorts ton of accompanying code. ' by MrMelbert at commit ecaa3268fe](https://www.github.com/tgstation/tgstation/pull/67083)
[#65791: 'Optimizes Runechat' by Kylerace at commit 775d002c97](https://www.github.com/tgstation/tgstation/pull/65791)

## Reproduction:
According to the wiki, food and drinks created by silver slimes are disgusting to spacemen. If you actually eat the food/drinks in the game nothing of the sort is indicated. 
I'm not sure if this is a mistake on the wikis part or a bug.

**Comment by magatsuchi** [comment]
toxic foods are intended to cause [disgust](https://github.com/tgstation/tgstation/blob/369ee37e62628e32eb12ddedd8e786c860583ade/code/modules/food_and_drinks/food.dm#L35), if it isn't then there is something wrong

**Comment by magatsuchi** [comment]
[further reference](https://github.com/tgstation/tgstation/blob/6a08c3b626cdade22fe8c458016fe978d2a7fc2d/code/datums/components/food/edible.dm#L458)

**Comment by Mothblocks** [comment]
i ate silver slime food a few days ago and didnt get anything

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/68319
