### ISSUE TITLE
Non-human 'heads of staff' get random crew photos.

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#68052]
## Round ID:

[Round ID]: [185686](https://scrubby.melonmesa.com/round/185686)

## Testmerges:

#65791 
#67083 

## Reproduction:

Have someone join as a head of staff with a non-human character at round start. Their race will be changed to human as they picked dead of staff.
Look at their photo and see it is some other crewmember.
It's that simple.

![image](https://user-images.githubusercontent.com/16896032/176106718-21c36fd4-7b20-48bb-9bfe-7e15d2d453be.png)
![image](https://user-images.githubusercontent.com/16896032/176106788-9357ddc1-9971-412e-88bd-af4faa71fa11.png)

**Comment by JohnFulpWillard** [comment]
Spawned as lizard CMO, ended up as human
records were fine, spawned roundstart with a 2nd medical doctor in case
![image](https://github.com/tgstation/tgstation/assets/53777086/d11f88ed-902a-4aa1-a2bd-1aaba7df52dc)
