### ISSUE TITLE
Getting In Mech Prevents C-4 Attached To You from Damaging You

### ISSUE THREAD

**Issue by IndieanaJones** [tgstation/tgstation#68076]
## Testmerges:

[#65635: '[Ready for Review] Admin lua scripting' by Y0SH1M4S73R at commit cdb7990197](https://www.github.com/tgstation/tgstation/pull/65635)
[#67856: 'Updates the sprites for bullets (inflight), adds pellet sprites, redoes the thermal projectile sprites' by necromanceranne at commit 211dd1f01a](https://www.github.com/tgstation/tgstation/pull/67856)

## Reproduction:

- Stick a bar of C-4 on person
- Person gets in mech
- C-4 explodes, but no damage is dealt to the person at all.

**Comment by Mooshimi** [comment]
Im fairly sure this also works with lockers

**Comment by moocowswag** [comment]
Lockers I dont think so, most containers dont protect you from explosions and mechs are uhhh something unique and its obvious that they would protect you from an explosion but i dont think there is anything in place that allows for an internal explosion.

**Comment by nemvar** [comment]
This happens because the explosion happens on the turf, not on the mob. This same thing probably happens with grenades in your backpack.

**Comment by CursedBirb** [comment]
I recall seeing c4 being deleted by shutters before. Someone planeted c4 during nukie round under armory shutters. Hos just went and closed shutters. We heard boom but nothing was destroyed

**Comment by Mooshimi** [comment]
same issue different explosive: #45508

**Comment by Sealed101** [comment]
some recent-ish pr made explosives go boom through mechas and i can't fucking find it good fucking lord help me
anyways can't reproduce because see above
