### ISSUE TITLE
Inconsistent Blur Applied On View (Test Merge Related?)

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#68074]
Reporting client version: 514.1585

## Round ID:
[185742](https://scrubby.melonmesa.com/round/185742)

## Testmerges:
- [Updates the sprites for bullets (inflight), adds pellet sprites, redoes the thermal projectile sprites](https://www.github.com/tgstation/tgstation/pull/67856)
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)
- [Lemon does pain](https://www.github.com/tgstation/tgstation/pull/67902)

## Reproduction:

![image](https://user-images.githubusercontent.com/34697715/176356581-4f35b52d-0d26-4db3-8aa9-a1497b0750e4.png)

I was sent to the Heretic's Z-Level as a sacrifice (after I died, if that helps), and the then when I came back, the blur effect was inconsistent. You see how the freezer and floor is crystal-sharp while everything else is pretty blurry? Might be due to #67802 touching planes?

**Comment by timothymtorres** [comment]
You linked the wrong issue.  The test merge is from #67902

**Comment by LemonInTheDark** [comment]
TM bug, and I saw it, closing
