### ISSUE TITLE
Reoccuring issues with HUDs/Combo HUD not always appearing/updating, especially for midround spawned antagonists.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#68087]
Reporting client version: 514.1584

## Round ID:
[185771](https://scrubby.melonmesa.com/round/185771)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Completely removes `proc_holders` from existence. Refactors all wizard, xeno, spider, and genetics powers to be actions. Also refactors and sorts ton of accompanying code. ](https://www.github.com/tgstation/tgstation/pull/67083)

## Reproduction:

This isn't specific to the linked round, but there's been countless issues with HUDs actually showing up or updating. I've only really noticed this for admin combo HUDs with midround spawned antagonists, and security HUDs and arrest tags.

Below is when everyone on the station was set to arrest automatically by a space ninja. While I on the right have the arrest HUD, the assistant to my left does not, despite being set to arrest in the records as seen when examining with the sechud glasses.
![dreamseeker_aG99sJ7I6Q](https://user-images.githubusercontent.com/33107541/176496190-c052017b-db32-4eb6-9ec6-fc3ef14d42b1.png)
(notice the criminal status: arrest)
![dreamseeker_9mv81D6o3e](https://user-images.githubusercontent.com/33107541/176496206-e4a31412-76bb-45c0-ac1c-82fc788fdd54.png)

Below is an example of broken combo huds for admins. Usually this works fine for most of the crew and other antagonists, but sometimes (especially with midround spawned antagonists). Here in the below image is two antags seen through combo hud, one a deceased thief and another a living nuke op. The operative has _no huds at all, not even a health hud._
![dreamseeker_aoWvJlswaa](https://user-images.githubusercontent.com/33107541/176496853-ce155ace-18cb-4e29-919d-3de170cdef29.png)
I've had syndicate medical cyborg players in the past also have issues regarding health huds and their fellow operatives, so this might be a bigger issue than just the combo hud.

**Comment by Mothblocks** [comment]
@Kylerace Did that z-index-images PR ever get merged? Is this the fault of that perhaps?

**Comment by Kylerace** [comment]
> @Kylerace Did that z-level-images PR ever get merged? Is this the fault of that perhaps?

Yes, and probably

**Comment by SinfulBliss** [comment]
Noticed this occurred yesterday in round 199968. After revs lost their rev HUD stayed. 

Also affects the sechud icons, sometimes they disappear and show nothing (kind of like if the person were a disguised abductor).

**Comment by Potato-Masher** [comment]
I have yet to notice this recently... I'm going to close this unless I see it again.
