### ISSUE TITLE
simplemobs that emit light appear to leave their light behind when moving

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#68089]
## Round ID:
[185778](https://scrubby.melonmesa.com/round/185778)

## Testmerges:

[#65635: '[Ready for Review] Admin lua scripting' by Y0SH1M4S73R at commit cdb7990197](https://www.github.com/tgstation/tgstation/pull/65635)
[#67856: 'Updates the sprites for bullets (inflight), adds pellet sprites, redoes the thermal projectile sprites' by necromanceranne at commit 211dd1f01a](https://www.github.com/tgstation/tgstation/pull/67856)

## Reproduction:

> be miner
go to lavaland
see  brimdemon
watch it move
realize that the red light that it emits stays in the same place instead of moving with the brimdemon
go to ash drake
realize that it's light is also left behind when it moves

![image](https://user-images.githubusercontent.com/54422837/176504717-1a09e47b-1596-4f7f-a20d-96935964dd84.png)
![image](https://user-images.githubusercontent.com/54422837/176505095-82b7f352-d024-4fb8-8658-a4ea7628fa5a.png)

**Comment by ShizCalev** [comment]
Probably fixed this via #70250

**Comment by private-tristan** [comment]
Yeah, this bug hasn't shown up in a while
