### ISSUE TITLE
Left arm has less space for augments than right arm

### ISSUE THREAD

**Issue by Maxipat112** [tgstation/tgstation#68138]
Reporting client version: 514.1575

## Round ID:
[185906](https://scrubby.melonmesa.com/round/185906), probably not tied to round

## Testmerges:
None

## Reproduction:
TESTED ONLY ON SURGICAL TOOLSET IMPLANT, on organic arm
1. Start organ manipulation on left arm
2. Finish all the surgery steps
3. Try to put implant into left arm
4. Should end in "no space in left arm" message
5. Try doing the same on right arm
6. Works as it should

**Comment by newfren** [comment]
the toolset implants have a specific arm they need to go in: right when they are initially printed, or left when a screwdriver is used on them to flip them.

**Comment by Maxipat112** [comment]
oh, alright, didn't know that thought it's a bug haha, closing this then
