### ISSUE TITLE
Repairing damaged plating doesn't update it's appearance

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#68133]
Reporting client version: 514.1585

## Round ID:
[185890](https://scrubby.melonmesa.com/round/185890)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Completely rewrites the orbit screen](https://www.github.com/tgstation/tgstation/pull/68054)

## Reproduction:
Find some damaged plating
Weld it
It looks busted, but acts repaired.

**Comment by timothymtorres** [comment]
Likely caused by #67761
