### ISSUE TITLE
alien resin sometimes doesn't change colors during timestop?

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#68154]
## Round ID:
[185955](https://scrubby.melonmesa.com/round/185955)

## Testmerges:

[#68054: 'Completely rewrites the orbit screen' by jlsnow301 at commit aa5cc8ec07](https://www.github.com/tgstation/tgstation/pull/68054)
[#68118: 'Makes pAI screen alert actually work' by dragomagol at commit bcace884a9](https://www.github.com/tgstation/tgstation/pull/68118)
## Reproduction:

use timestop sepia extract with alien resin
sometimes doesn't change back?
 
![image](https://user-images.githubusercontent.com/54422837/177015811-44d1ebff-f7fa-4503-96df-6c059baab0c5.png)
![image](https://user-images.githubusercontent.com/54422837/177015820-6e75b86c-7587-4572-93fa-1851e1d8ee1b.png)

**Comment by Sealed101** [comment]
affects resin tiles that have grown in an active timestop field - glowing resin's `make more tiles` thing isunaffected by the timestop and don't get the memo to remove the negative filter from the tiles created while under timestop

![image](https://github.com/tgstation/tgstation/assets/75863639/1ea47f21-beef-42bf-a277-2c52c42e90ed)

![image](https://github.com/tgstation/tgstation/assets/75863639/ea210a73-3b6f-4031-8567-28886c3685ce)

**Comment by SethLafuente** [comment]
Dosen't seem to be an issue anymore
![BMgsPP3](https://github.com/tgstation/tgstation/assets/84478872/556a78d8-f36e-4cd1-be00-4d04e23a0f1b)

**Comment by SethLafuente** [comment]
@Sealed101

**Comment by Sealed101** [comment]
somehow, it got fixed. i don't see what could have fixed this, but it did. mysterious
