### ISSUE TITLE
Lavaland Plants cannot be harvested

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#68158]
Reporting client version: 514.1584

## Round ID:
[185970](https://scrubby.melonmesa.com/round/185970)

## Testmerges:
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)

## Reproduction:

Lavaland plants cannot be harvested, either barehanded, with knives or with tools from botany.

**Comment by madamheichou** [comment]
Getting this issue myself, too.

**Comment by NamelessFairy** [comment]
Is it possible that this is related to [66978](https://github.com/tgstation/tgstation/pull/66978) ?
