### ISSUE TITLE
Brimdemon's glow filter gets left behind

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#68157]
Reporting client version: 514.1584

## Round ID:
[185970](https://scrubby.melonmesa.com/round/185970)

## Testmerges:
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)

## Reproduction:

The red filter/glow that surrounds brimdemons on lavaland remain in their original position after the brimdemon moves away.

**Comment by timothymtorres** [comment]
Duplicate of #68089
