### ISSUE TITLE
Hand swap breaks for entire round, or until you change bodies.

### ISSUE THREAD

**Issue by Robustitron** [tgstation/tgstation#68172]
## Testmerges:
[#68118: 'Makes pAI screen alert actually work' by dragomagol at commit bcace884a9](https://www.github.com/tgstation/tgstation/pull/68118)
[#68054: 'Completely rewrites the orbit screen' by jlsnow301 at commit aa5cc8ec07](https://www.github.com/tgstation/tgstation/pull/68054)
[#68137: 'Barf a bunch of dynamic logs' by Mothblocks at commit 6691a2d293](https://www.github.com/tgstation/tgstation/pull/68137)

## Reproduction:
1) Join a round while unlucky
2) Try middle mouse clicking, or using x to swap hands.
3) Realize you are unable to swap hands unless you click the ui manually
4) Check keybinds, they're all fine
5) Issue persists for the rest of the round or until you're in a new body.

Wubli was an admin that round, tried to fix it by respawning my mob, it worked for about 5 minutes, then my ability to swap hands broke again and I decided to continue my ling round one-handed.

This is a fairly old bug, also a pretty terrible one to deal with when rolling antag, so far it seems to be related to your body on the server, since a new body can fix it, though temporarily.

**Comment by Sealed101** [comment]
an old bug with no reliable reproduction steps or related runtimes in the linked round. i can't imagine we can do anything with this
