### ISSUE TITLE
CI failure caused by default AI name

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#68170]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:

`[20:47:58] Runtime in _preference.dm,261: Couldn't write the default value for /datum/preference/name/ai (received 16-20)`

Had this pretty random CL failure. Since both numbers and dashes are stripped from AI name inputs, the name became empty.

**Comment by Mothblocks** [comment]
You need a single letter in your name, even as AI.

Relevant:
https://github.com/tgstation/tgstation/blob/c070dd4ffdc75d409b84dabd7bf21f2aa3422479/code/modules/client/preferences/names.dm#L32-L33

https://github.com/tgstation/tgstation/blob/1e79567d3354993637b86124c36efe7dc9d46fdb/code/__HELPERS/text.dm#L154

Easy fix would be remove this from default names. Proper fix is to allow a name like this as AI.

**Comment by msgerbs** [comment]
Fixed by #69458
