### ISSUE TITLE
Simple mobs ignore directional windows

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#68197]
Reporting client version: 514.1585

## Round ID:
[186084](https://scrubby.melonmesa.com/round/186084)

## Testmerges:
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)

## Reproduction:

Simple mobs pass through directional windows. This can easily be seen with the chickens and cow in the garden, but can also be seen with simple mob syndicate shock troops.

**Comment by Artemchik542** [comment]
Can't reproduce this bug on up-to-date localhost

**Comment by Sealed101** [comment]
the jank is likely an issue with pathfinding forcing its way through certain configurations of directional windows or other border objects, and we've got at least one more issue for that quirk somewhere. also the amount of simple animal mobs has been dropping so there's that
