### ISSUE TITLE
Custom burgers have far too many overlays

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation#68203]
## Round ID: [186075](https://scrubby.melonmesa.com/round/186075)
```
[22:29:25] Runtime in stack_trace.dm,3: Too many overlays on /obj/item/food/burger/empty - 100, refusing to update and cutting.
 What follows is a printout of all existing overlays at the time of the overflow 
(icons/obj/food/burgerbread.dmi-custburg-0) = 1
(icons/obj/food/burgerbread.dmi-custburg_filling-0) = 98
(icons/obj/food/burgerbread.dmi-custburg_top-0) = 1
  proc name: stack trace (/proc/stack_trace)
  ```

**Comment by Iamgoofball** [comment]
why is there a limit

**Comment by optimumtact** [comment]
because having too many overlays causes 
A) client lag
B) lag when reprocessing overlays

There's no way someone put 99+ fillings in this burger, the code is definitely just replicating things incorrectly.

**Comment by optimumtact** [comment]
it may be enough to just change customiseable reagent holder to be
`max_ingredients = MAX_ATOM_OVERLAYS - 3`

**Comment by Iamgoofball** [comment]
``There's no way someone put 99+ fillings in this burger, the code is definitely just replicating things incorrectly.``

you underestimate our chef players and their dedication to extremely tall burg

**Comment by optimumtact** [comment]
![Screenshot from 2022-05-31 17-50-17](https://user-images.githubusercontent.com/2544323/177302508-60246695-7d4b-41af-a924-eb68822c0c25.png)
