### ISSUE TITLE
Nuclear operative pinpointers broken, Fission360 app bluescreens the tablets.

### ISSUE THREAD

**Issue by Robustitron** [tgstation/tgstation#68223]
## Testmerges:
No testmerges according to show server revision on sybil

## Reproduction:
1) Be a nukie
2) Open your tablet
3) Click the fission360 app
4) Tablet bluescreens
5) Try and fail to find a way to reset or fix it
6) Test your buddies tablets and find the same thing

Was the nuke op leader when this happened, none of our tablets worked, our ahelps got no answer, we ultimately had to steal the crew pinpointer to find the disk, only to be unable to find our nuke (was off the shuttle, another op tried and failed to arm), since that feature is exclusive to the tablets that no longer work.

**Comment by jlsnow301** [comment]
Do you remember the error from the error screen
