### ISSUE TITLE
MetaStation Atmospherics Engine Apc is not cabled

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#68233]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
![Screenshot_2](https://user-images.githubusercontent.com/95751821/177658184-2f9316e0-e321-41ac-b5a7-a68a9ef015fe.png)

**Comment by orthography** [comment]
Fuck fuck fuck fuck fuck fuck fuck fuck.
