### ISSUE TITLE
Controlling the tram via circuits is broken (or poorly explained)

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#68247]
Controlling the tram using a bot shell and an usb cable connected to the tram control computer, just doesnt work from my attempts
Setting the "Destination" to "left_part","right_part","East Wing",etc. and signalling "Send Tram" just simply didnt work, and it seems the circuits "Location" and "Travelling" outputs are always null
## Round ID:
Local Copy, should be latest version of the master branch though

## Reproduction:

1. Get on tramstation
2. Get a bot shell with an USB cable connected to the tram control computer
3. Set the destination in the circuit
4. Signal "Send Tram"
5. No movement, tram works fine with the computer

**Comment by Mothblocks** [comment]
Likely the tram optimizations

**Comment by mc-oofert** [comment]
seems to be only broken on local copies
