### ISSUE TITLE
Illiterate people have no way to remove pai from tablets

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#68244]
I remember being mad about this for like 3 rounds but I didn't write down the round ids mb

pick illiterate quirk
put pai into tablet to store it for later
there's now no way to activate the pai nor remove it from the tablet

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/86f1eab23d0e7992b97ab444b683e27e25bbf92d/code/modules/modular_computers/computers/item/computer_ui.dm#L253-L262

https://github.com/tgstation/tgstation/blob/45d2cdb3187e9b1b5a03364907e67916529735f9/code/modules/modular_computers/computers/item/computer.dm#L619-L631

I think the correct solution is to just tie this into the Alt Click or Ctrl Click behavior to pop it out.
