### ISSUE TITLE
rad storm not green enough and ash storms not grey enough

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#68253]
## Testmerges:
The following pull requests are currently test merged:
[#65635: '[Ready for Review] Admin lua scripting' by Y0SH1M4S73R at commit ebd39ac1ad](https://www.github.com/tgstation/tgstation/pull/65635)
[#67902: 'Lemon does pain' by LemonInTheDark at commit 1de078be91](https://www.github.com/tgstation/tgstation/pull/67902)

## Reproduction:
![image](https://user-images.githubusercontent.com/12635164/177768175-297224e2-5093-41bd-80d0-1bf298aa7029.png)
I've got no fucking clue how to reproduce it sorry
rad storm happened and there was just a few specks of colour around but no overwhelming green

![image](https://user-images.githubusercontent.com/12635164/177779854-d24d03f1-cf81-4692-86b3-ac3ab17f3b01.png)
it happened with ash storms too

**Comment by dragomagol** [comment]
@LemonInTheDark ?

**Comment by LemonInTheDark** [comment]
Damn it I need to do it properly
Hhhhhhhh
