### ISSUE TITLE
PDA painters are indestructable and runtime to heck when they reach 0 integrity 

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#68263]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/177889799-22b3b6ba-cb0f-4d24-af3e-563b62b5c199.png)

PDA painters have no destruction handling and, as a result, are indestructible. When they reach 0 integrity, they instead will spit runtimes every time they take damage. 

![image](https://user-images.githubusercontent.com/51863163/177889866-bc476179-fb62-4457-8ced-44e4ff0a18cb.png)

**Comment by timothymtorres** [comment]
Is there a lot of other machinery that have this problem as well?  PDA painters are quite old and I think the root cause could likely be affecting other machines we don't know about.
