### ISSUE TITLE
Jetpacks don't change your momentum in space

### ISSUE THREAD

**Issue by GuiltyNeko** [tgstation/tgstation#68275]
## Round ID: 
Tested locally several minutes ago on latest code

## Reproduction:
Go into space. Use jetpack to move around. Keep moving in the same direction you initially moved in, despite jetpacking in the opposite direction. 
This at least applies to the MODsuit jetpack module, not sure if other jetpacks work with the same code, hopefully they do. 
Stabilizers will stop you, but moving in a jetpack should change your momentum anyways. And, under the right circumstances, this could be abused for a speed boost, and if someone chasing you started out going a different direction than you, they're shit out of luck without toggling their stabilizers, yada yada counter counter counter play it's not ideal.

**Comment by LemonInTheDark** [comment]
hhhhhhhhhhhhhhhhhhh

**Comment by Sealed101** [comment]
recent spacemove and jetpack changes basically made this a feature? newtonian physics and allat
#87020
