### ISSUE TITLE
Gateway visuals broken

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#68273]
Reporting client version: 514.1585

## Round ID:
[186302](https://scrubby.melonmesa.com/round/186302)

## Testmerges:
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)

## Reproduction:
We had a PR way back to make the gateway show the other side, which was cute.
Now it looks like this:
![image](https://user-images.githubusercontent.com/50649185/178075562-548bf1a3-3c50-40a0-aba1-f95452e1ccc6.png)

**Comment by unit0016** [comment]
I think this effect was entirely removed (on purpose) since, though I'd like citation on that before I feel comfy closing this PR.

**Comment by Profakos** [comment]
Yeah, it has been replaced in #69115
