### ISSUE TITLE
Camera static overlay sticking after moving away from the console

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#68279]
RoundID 186309
no testmerges

after using a camera console [xenobio] and walking around, some of the static overlays stick around and you can still see them even when you're off the console [see picture]

![image](https://user-images.githubusercontent.com/105343481/178081938-29ca6183-f4b8-4aa2-83c8-65cfb6d612c6.png)

**Comment by Sealed101** [comment]
it seems that these issues are casued by cameras not clearing up properly when taken offline/destroyed, and we've had a bunch of these over the years. i _think_ this case was resolved in https://github.com/tgstation/tgstation/pull/78839 but we'll see
