### ISSUE TITLE
Signing tonal indicators can get stuck on people

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#68277]
Reporting client version: 514.1568

## Round ID:
[186308](https://scrubby.melonmesa.com/round/186308)

## Reproduction:

The tonal indicators for sign language-ers can get stuck on people long after they stopped talking.

(Bad picture but they were like this for most of the round) 

![image](https://user-images.githubusercontent.com/51863163/178083982-398434f7-265d-48ea-875d-ffcf78066118.png)

**Comment by jlsnow301** [comment]
he :|

**Comment by dragomagol** [comment]
Looks like this is an issue with the timing used by tonal indicators. If you sign two things with tonal indicators in a row before the timer removes it it'll stick.
