### ISSUE TITLE
Bodybags can't be folded

### ISSUE THREAD

**Issue by Ryll-Ryll** [tgstation/tgstation#68285]
Reporting client version: 514.1571

## Round ID:
[186323](https://scrubby.melonmesa.com/round/186323)

## Reproduction:

1. Lay out bodybag
2. Drag the bodybag back on top of you, which should put it back in your hands
3. It doesn't

**Comment by trexter5555** [comment]
are you doing this while it's open or while it's closed

**Comment by timothymtorres** [comment]
From #67893 

> qol: You fold roller beds and bodybags with a right click instead of click and dragging into you.

Marking this as `Not a bug`

**Comment by Mothblocks** [comment]
@MrMelbert @JohnFulpWillard That PR should not have been merged without contextual screentips. The fact this bug report exists is testament to that

**Comment by ArcaneMusic** [comment]
Now, bodybags can be folded, that's true.
...But from the same PR, roller beds cannot.
![image](https://user-images.githubusercontent.com/41715314/178161529-b78b208e-1453-4a46-9107-4f539eab937f.png)

**Comment by dragomagol** [comment]
Fixed by #68334
