### ISSUE TITLE
You cant open Service Ordering Console crates on Tram Station

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#68281]

**Comment by Likteer** [comment]
the crates are opened at the console that ordered it

**Comment by Shadowflame909** [comment]
Not on tram. We tried and the admins found service hall non existent. You have to break the crate open with makeshift tools

**Comment by san7890** [comment]
![image](https://user-images.githubusercontent.com/34697715/178116657-7bc294f3-7b94-4eb4-9318-364f78d8c3ef.png)

![image](https://user-images.githubusercontent.com/34697715/178116664-96254c11-d358-4b8c-9bfa-1aded7d4aeac.png)

That's... confusing.
