### ISSUE TITLE
Kilo Whiteship Bridge Console does not function

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#68307]
Reporting client version: 514.1585

## Round ID:
[186386](https://scrubby.melonmesa.com/round/186386)

## Testmerges:
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)

## Reproduction:

The bridge console for the kilo whiteship does not function properly, leaving the navigation console as the only way to move it, limiting where it can go by default.

**Comment by Maurukas** [comment]
At this point I'm willing to accept a full rework of the Kilo whiteship and warehouse.
