### ISSUE TITLE
Grid check event causes APCs to continously play the powering down sound

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#68300]
## Round ID:
N/A

## Testmerges:

N/A

## Reproduction:

Trigger the grid check event, hear the APCs continously clunk until they are rebooted.

**Comment by moocowswag** [comment]
I think ive also experienced this just from apcs losing power, not just the event that turns them off.

**Comment by Profakos** [comment]
This has been solved by #68835 .
