### ISSUE TITLE
Roller bed/body bag code does not use the _secondary procs correctly, and almost certainly runtimes

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#68306]
See my reviews here: https://github.com/tgstation/tgstation/pull/67893#pullrequestreview-1033586348

It returns FALSE in certain cases, which is not allowed, and it returns `..()` in others, which is not allowed but not currently statically checked.

https://github.com/tgstation/tgstation/blob/3e006282e2c511c2c605b2dacf61a5f324e757d5/code/_onclick/other_mobs.dm#L5-L10

(It also should have had contextual screentips, but I'm just upset about it)

@GuillaumePrata

**Comment by GuillaumePrata** [comment]
Working on it right now.

**Comment by Mothblocks** [comment]
Thanks!

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/68334
