### ISSUE TITLE
Tramstation doesn't have enough dark xeno spawns

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#68320]
## Round ID:
Different server

## Testmerges:
N/A

## Reproduction:
Tramstation does not have enough xeno spawns in lightless areas. This prevents Nightmare from spawning. I tried to put them in completely dark maint areas, but, none of them have vents, and spiders use the spawn spawn condition, and they kinda need the vents. 
Of course, eventually lights break, but still, it would be nice to have some guaranteed spawn areas.

**Comment by MMMiracles** [comment]
Currently working on a maintenance revamp, will keep this in mind while I put it together.

**Comment by Profakos** [comment]
Thank you!
