### ISSUE TITLE
Gondolapods cannot be spawned in via the Game Panel

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#68339]
Reporting client version: 514.1585

## Round ID:
[186436](https://scrubby.melonmesa.com/round/186436)

## Testmerges:
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)

## Reproduction:

Gondola pods do not spawn in when selected via the game panel's "create mob" menu, attempting to do so does nothing. Can only be spawned in via create/launch supply pod and choosing to have the pod stay.

Also, when gondola pods are used as supply pods the thing they are shipping tend to disappear or get eaten as it were, don't know if that is intentional or not.

**Comment by Sealed101** [comment]
basicmobbing them in https://github.com/tgstation/tgstation/pull/83451 was probably responsible for the fix; can spawn them in fine and dandy
