### ISSUE TITLE
ghosts cannot open boxes/bags/etc

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#68330]
## Round ID:
[186423](https://scrubby.melonmesa.com/round/186423)

## Reproduction:
go find some storage (bags, boxes, jackboots, you name it), click it, get the "can't reach!" alert
likely its the storage component refactor that is causing this

**Comment by Shadowflame909** [comment]
Yeah just noticed this too.

**Comment by magatsuchi** [comment]
duplicate of #68290
