### ISSUE TITLE
Loading pAI profile doesn't work

### ISSUE THREAD

**Issue by lordheichou** [tgstation/tgstation#68353]
Reporting client version: 514.1584

## Testmerges:
- [Reworks pAIs](https://www.github.com/tgstation/tgstation/pull/68241)
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)
- [Barf a bunch of dynamic logs](https://www.github.com/tgstation/tgstation/pull/68137)

## Reproduction: 
During the round I loaded my pAI profile, my information showed up (name, ooc notes, etc) and I hit submit. When I was downloaded, my name was randomized.
![image](https://user-images.githubusercontent.com/27985186/178350443-7ad69fca-4c33-411c-a0b0-8fea0a6dd857.png)
(screenshot of the pAI candidate screen after I had submitted myself)
I suicided then tried again. Loaded my pAI profile and hit submit. Again, my name was randomized and I had no extra information on the download screen.
Only when I manually put in my information rather than loading my profile did my information stick and I was downloaded with the correct name.

**Comment by dragomagol** [comment]
#68241

**Comment by jlsnow301** [comment]
i have this fixed on local rn, will upload in a minute
