### ISSUE TITLE
Trying to withdraw cash from a new ID card instead just brings you to the Account Reclamation screen.

### ISSUE THREAD

**Issue by weesnaw-ops** [tgstation/tgstation#68351]
## Reproduction:

Trying to withdraw cash from a new ID card that you did not spawn with instead brings you to the Account Reclamation screen. You used to get an account number from the Account Registration device. That number can no longer be obtained.

![reclamation](https://user-images.githubusercontent.com/54719976/178349462-056be02f-da62-4dd7-958f-463f13638139.PNG)

This is useful for people who lost their ID card- but not for ghost roles who have been given an ID, like golems.

**Comment by Mooshimi** [comment]
is the issue the ability to create money accounts
