### ISSUE TITLE
Banana Glutton Cannot regurgitate anything

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#68360]
Reporting client version: 514.1585

## Round ID:
[186491](https://scrubby.melonmesa.com/round/186491)

## Testmerges:
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)

## Reproduction:
Bananaglutton cannot regurgitate banana peels/morsels after consuming bananas.

**Comment by timothymtorres** [comment]
Duplicate of #60933
