### ISSUE TITLE
Science Bags no longer feed Reproductive Extracts

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#68363]
Reporting client version: 514.1584

## Round ID:
[186498](https://scrubby.melonmesa.com/round/186498)

## Testmerges:
- [Barf a bunch of dynamic logs](https://www.github.com/tgstation/tgstation/pull/68137)
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)
- [Reworks pAIs](https://www.github.com/tgstation/tgstation/pull/68241)

## Reproduction: The Science Bags present for Xenobiology and Cytology are no longer compatible with feeding reproductive extracts monkey cubes. It doesn't matter how many cubes are actually present in the bag, or if anything else is with them, but it will always produce the empty response.

1. Fill the Science Bag with any number of monkey cubes
2. Prepare a Reproductive Extract of any type
3. Click on the Reproductive Extract with the Science Bag
4. Receive an empty response

**Comment by ZeroKelvn** [comment]
Since this still hasn't been fixed as of six weeks, I went and did some code digging and determined that whatever happened in 7d0f393f5d3cb4ebe7ca5427628e4d1e9a8d2303 broke the Bio Bags being able to feed Reproductive Extracts. As a consequence of converting the signal to an atom function, this stopped working entirely. I'm not sure if a file reversion would fix this, but it may be worth looking into.

**Comment by Sealed101** [comment]
fixed in #69518
