### ISSUE TITLE
Material airlocks are bland and white

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#68377]
Reporting client version: 514.1585

## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
![image](https://user-images.githubusercontent.com/44104681/178610593-8b24d0c3-7a0b-480b-af6e-c0af1227c15b.png)
I was messing around in localhost with a few different materials. From left to right: Bone, Metallic Hydrogen, Meat, and Runite. The airlocks connecting these four rooms are ALSO made of their respective materials. Notice anything... off? I'll give you a minute. Think you've got it? The airlocks are all the exact same boring white color. They aren't like this during construction, but once you finish the airlock, boom, lifeless.

**Comment by 13spacemen** [comment]
@Y0SH1M4S73R
