### ISSUE TITLE
Can't dump out storage containers with clickdrag

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#68374]
Reporting client version: 514.1583

## Round ID:
[186533](https://scrubby.melonmesa.com/round/186533)

## Testmerges:
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)
- [Revert "Fixes admin.fun list"](https://www.github.com/tgstation/tgstation/pull/68369)

## Reproduction:
See title

**Comment by BigGrease** [comment]
aha tattle noticed this a week before me, thats why she gets paid the big bux B)

**Comment by dragomagol** [comment]
I have the mighty need to strew objects all over the station like a maniac
