### ISSUE TITLE
Book Binder still presenting spans when creating books

### ISSUE THREAD

**Issue by TetrakoHateThis** [tgstation/tgstation#68404]
## Round ID:
N/A

## Testmerges:
Irrelevant - Issue has been present since April 2022.

## Reproduction:
Duplicate of #66234 since it's been 3 months now and nobody seems to be really looking into fixing it. When pages are put through the Book Binder, they come out with all the spans laid out, clear as day, making newly printed books practically unreadable. This issue pretty much puts the kabosh on half of a Curator's role, to write stuff, meaning the library will pretty much be stagnant with the same offerings before long and if left ignored, might I suggest rethinking the Curator's role in the overall design.

![bookbroken](https://user-images.githubusercontent.com/81869793/178839169-a8fed920-5963-4af2-8820-7e61ef7ea1fd.jpg)

**Comment by weesnaw-ops** [comment]
can we fix this please good lord its been THREE MONTHS!!!

**Comment by ShizCalev** [comment]
Dupe.
