### ISSUE TITLE
Holoparasites only speak galactic common, regardless of what their master speaks or understands

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#68402]
## Round ID:
irrelevant

## Testmerges:
irrelevant

## Reproduction:

> be ash walker
get holoparasite
realize that it speaks galactic common
you don't understand it
it doesn't understand you
you need to use communicate to talk

forcing someone to use communicate to talk with their holoparasite (slow, requires you to look at chat) isn't good

**Comment by timothymtorres** [comment]
This is hilarious.

**Comment by Shadowflame909** [comment]
does holopara telepathy not work either?

**Comment by private-tristan** [comment]
holopara telepathy (communicate) does work, but it's clunky to use (holopara user needs to go into a new holopara tab and click a button to talk) and it isn't runechat so it's really, really hard to notice when you're in a tense situation
