### ISSUE TITLE
Admin triggering events will put it on a 10 second timer ("Random event triggerin in [x]"), and ask "if you'd like to alert the crew" after it's already triggered

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#68408]
- Admin trigger an event
- It puts it on a 10 second random event "trigger" queue, instead of it being instant
- After the event actually triggers, it asks you if you want to alert the crew or cancel

**Comment by Profakos** [comment]
I have been working on a trigger event panel UI remake in the last few days and noticed this. It also has the issue that a lot of events have a very short announceWhen duration, so you will never have the chance to click 'no'.

I am making running it without alerting the crew a checkbox you tick in before triggering an event.

Right now specifically puts it on a 10 second delay so other admins can cancel it quickly, so I will keep that, but will also make it use a callback, right now it specifically calls sleep.

**Comment by Profakos** [comment]
Wait god, alert_observers = false run immediately and can not be stopped by other admins??

**Comment by Profakos** [comment]
Wait god, alert_observers = false run immediately and can not be stopped by other admins?? That makes sense for randomly occurring space dust and camera failure but not for electrical storm or fake virus.
