### ISSUE TITLE
Peacekeeper Cyborg Cookie synthesizer doesn't store cookie

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#68414]
## Reproduction:
Be a peacekeeper cyborg and periodically examine your cookie synthesizer to check stock, and notice it's always at 0, and you have to wait 10 seconds after printing a cookie to print another.

**Comment by nemvar** [comment]
https://github.com/tgstation/tgstation/blob/aa034d02cdee14ca039cc07d59a0d5280d2ffa61/code/game/objects/items/RSF.dm#L166-L170

Code implies this is intentional.

**Comment by nemvar** [comment]
https://github.com/tgstation/tgstation/pull/57786
>  balance: Cyborg cookie dispensers can now only dispense a cookie once every 10 seconds (instead of once per second). Non-cyborg cookie dispensers no longer self-recharge, but can now accept compressed matter cartirdges for reloading purposes. Support has been added for other types of RSFs to have use cooldowns.

Is the issue that the borg cookie printer does not automatically recharge? If so, I didn't catch that from the issue body.

**Comment by Mooshimi** [comment]
to_chat(user, span_notice("\The [src] now holds [matter]/[max_matter] [discriptor]."))
this line suggests that there should be a built up stock of them, no??

**Comment by Mooshimi** [comment]
it shows 0/10 on the examine text

**Comment by moocowswag** [comment]
So either the examine text is a bug or the functionality is a bug.

**Comment by timothymtorres** [comment]
More relevant code:

https://github.com/tgstation/tgstation/blob/aa034d02cdee14ca039cc07d59a0d5280d2ffa61/code/game/objects/items/RSF.dm#L58-L60

https://github.com/tgstation/tgstation/blob/aa034d02cdee14ca039cc07d59a0d5280d2ffa61/code/game/objects/items/RSF.dm#L130-L148
