### ISSUE TITLE
Getting converted to a android  (presumably any race with no hunger?) while having the hungry moodlet keeps the moodlet forever

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#68416]
Reporting client version: 514.1584

## Round ID:
[186612](https://scrubby.melonmesa.com/round/186612)

## Testmerges:
- [Nukie Rework Part 1: Removes some stuff from nukie uplink, adds it as keycard bonuses instead.](https://www.github.com/tgstation/tgstation/pull/68396)
- [Nukie Rework Part 2: Nuclear Operative starting gear rework](https://www.github.com/tgstation/tgstation/pull/68401)
- [Reworks pAIs](https://www.github.com/tgstation/tgstation/pull/68241)
- [Shortens names on orbit ui](https://www.github.com/tgstation/tgstation/pull/68389)

## Reproduction:

> be hungry
get converted to android by chappie
wonder why your hungry moodlet won't go away
wait
wait
still there

![image](https://user-images.githubusercontent.com/54422837/178913197-ebd51286-b4ec-4347-bc19-bb06d0bbb285.png)

**Comment by newfren** [comment]
might also effect the "I'm stuffed!" moodlet?

**Comment by Ryusenshu** [comment]
another issue, same cause

This might affect races with tails too, they will get a negative moodlet because of the missing tail
(atleast that happened last time i used pride mirror to change into a runic golem)

**Comment by Sealed101** [comment]
fixed at some point
