### ISSUE TITLE
Directives tab bluescreens TGUI

### ISSUE THREAD

**Issue by CMDR-Gungnir** [tgstation/tgstation#68429]
Reporting client version: 514.1582

## Round ID:
[186638](https://scrubby.melonmesa.com/round/186638)

## Testmerges:
- [Barf a bunch of dynamic logs](https://www.github.com/tgstation/tgstation/pull/68137)
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)
- [Reworks pAIs](https://www.github.com/tgstation/tgstation/pull/68241)

## Reproduction:

Step 1, be a pAI
Step 2, click Directives on your pAI panel
Step 3, it bluescreens it

**Comment by dragomagol** [comment]
Caused by #68241
