### ISSUE TITLE
Using a multitool on a wire on a powernet not connected to the station displays no power.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#6843]
http://i.imgur.com/Na2GVSq.png
Though things DO charge properly you cannot get any number out of this. I could not check this myself so it may be just a weird one-time problem.

**Comment by ike709** [comment]
whatever happened to the powernet rewrite of legend?

**Comment by Mervill** [comment]
Unless @WJohn says otherwise, I think this can be safely close @optimumtact
