### ISSUE TITLE
Exosuit Materials 1: Stress Failure Test doesn't always accept mechs

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#68435]
Reporting client version: 514.1585

## Round ID:
[186659](https://scrubby.melonmesa.com/round/186659)

## Testmerges:
- [Barf a bunch of dynamic logs](https://www.github.com/tgstation/tgstation/pull/68137)
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)
- [[MDB Ignore] DELTASTATION: Remaps science, medbay, the chapel, and the library, and a whole lot more. Featuring mass driver. The Alpha and the Omega. ](https://www.github.com/tgstation/tgstation/pull/68431)
- [The Toiletbong and other poetical additions (*click* Noice)](https://www.github.com/tgstation/tgstation/pull/68193)

## Reproduction:
In a round earlier today the experiment wanted two mechs at 89% integrity. Did that no problem. In the linked round I was asked for mechs at 30% integrity. No matter what I tried, it didn't seem to accept my mechs, which did report 30% integrity.
![image](https://user-images.githubusercontent.com/44104681/179140605-25564350-fa29-428f-b245-90836fff3018.png)
![image](https://user-images.githubusercontent.com/44104681/179140706-a29335ca-4c18-4fc1-8ca8-539334f96bb6.png)
![image](https://user-images.githubusercontent.com/44104681/179140822-b74e3f81-e3e4-4208-8e47-b6ae6580a201.png)

**Comment by zxaber** [comment]
I'll look further into this. I hadn't been able to recreate the issue, but perhaps certain goal values like "30" are behaving odd.
