### ISSUE TITLE
Lavaland magma ambience is horrible

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#68437]
## Reproduction:
Listen to https://github.com/tgstation/tgstation/blob/master/sound/ambience/magma.ogg
The audio crackles and has poor balancing, it's quite distracting and jarring to hear the entire time you're on lavaland. Upsetting as well that ambience can only be disabled entirely.

**Comment by SamuelRowe** [comment]
Saw this on the Github issues for sound and decided to have a go at recreating lavaland ambience, let me know if this would work!
[https://voca.ro/1jZ9Qk8u4w1N](url)

**Comment by san7890** [comment]
@SamuelRowe hey that's pretty nice actually, would you mind making a pull request to our repository to replace `magma.ogg` with your ambience? this is just so we can get more eyes (and ears) on it for better feedback so we can determine if it's a good enough replacement.

be sure to link to this issue in your pull request
