### ISSUE TITLE
Magic Inventory that doesn't go away

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#68448]
Reporting client version: 514.1585

## Round ID:
[186694](https://scrubby.melonmesa.com/round/186694)

## Testmerges:
- [Barf a bunch of dynamic logs](https://www.github.com/tgstation/tgstation/pull/68137)
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)
- [Reworks pAIs](https://www.github.com/tgstation/tgstation/pull/68241)
- [The Toiletbong and other poetical additions (*click* Noice)](https://www.github.com/tgstation/tgstation/pull/68193)

## Reproduction:
I genuinely don't know how I got here. I was going through maints looking in trash bags and eventually I noticed I had an "inventory" I couldn't close or put things into. I took off anything with an inventory and walked away from them, didn't fix. I tried clicking the little arrow at the end, didn't fix.
![image](https://user-images.githubusercontent.com/44104681/179291939-5c4ef417-f04b-4f09-be63-f5fb79a54a95.png)

**Comment by newfren** [comment]
I find this happens to me pretty often when I fold up a box into cardboard and is cleared when I restart the game

**Comment by hannahscript** [comment]
This has happened to me when I open the pen protector on the curator's suit and then remove it from the suit.

**Comment by private-tristan** [comment]
https://user-images.githubusercontent.com/54422837/179734995-779d8f29-5476-442f-9791-625482c8df64.mp4

**Comment by Sealed101** [comment]
none of the reproduction steps listed above seem to work anymore
