### ISSUE TITLE
bubblegum is broken again but in a slightly different way

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#68443]
Reporting client version: 514.1584

## Round ID:
[186679](https://scrubby.melonmesa.com/round/186679)

## Testmerges:
- [Barf a bunch of dynamic logs](https://www.github.com/tgstation/tgstation/pull/68137)
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)
- [Reworks pAIs](https://www.github.com/tgstation/tgstation/pull/68241)
- [The Toiletbong and other poetical additions (*click* Noice)](https://www.github.com/tgstation/tgstation/pull/68193)

## Reproduction:
attack bubbles
he will successfully try to kill you with a charge once
then he's broken again as in https://github.com/tgstation/tgstation/issues/67873

it's possible that you HAVE to stay off blood to avoid him charging again, as I did that round

**Comment by timothymtorres** [comment]
Instead of making a new issue, you should have just posted your information into the old one and asked for it to be reopened.  If nobody responds after a few days, then you should make a new one.

I'm closing this one and then reopening the old issue.
