### ISSUE TITLE
Getting your brain implanted into your body whilst still in an MMI will null void your brain

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#68457]
## Reproduction: 
1. Get borged
2.  Dont want to be a borg anymore, get deconstructed and be MMI
3. Get my body and brain to medbay
4. Doctor takes me brain out of the mmi and quickly implants it into my head.
5. Game is unaware im out of my MMI because the doctor did it so fast, and it had no time to recognize I was dead
6. Spam admins messages with an error, I see nothing but darkness and cannot ghost without DNRing or succumb since the game thinks im alive and still in the mmi.

<img width="960" alt="brain error bug" src="https://user-images.githubusercontent.com/29222521/179337177-ad18e904-eeb5-499b-ba8c-47910486fe75.png">
<img width="347" alt="more info from the admins side" src="https://user-images.githubusercontent.com/29222521/179337217-8db89261-cf2d-46cb-bab8-ca554490361d.png">

**Comment by 13spacemen** [comment]
problem with the mmi eject_brain() brainmob check
