### ISSUE TITLE
Deconstruct unpowered microwave with cable coil

### ISSUE THREAD

**Issue by Colovorat** [tgstation/tgstation#68456]
Reporting client version: 514.1581

## Round ID:
The round before 186718

## Testmerges:
- [Reworks pAIs](https://www.github.com/tgstation/tgstation/pull/68241)
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)
- [Barf a bunch of dynamic logs](https://www.github.com/tgstation/tgstation/pull/68137)

## Reproduction:

1.Depower microwave(maybe optional? haven't tested on powered one)
2. Use wires on microwave
3. You get wired machine frame with all the parts for microwave

**Comment by Mooshimi** [comment]
LOL? that's hilarious that this is possible
