### ISSUE TITLE
Tram STILL has two circuit labs and two cargo ordering consoles

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#68459]
## Reproduction:

Despite #68073 being resolved, nothing was changed. 

(Bonus issue: Sci starts without a stack of glass like on other maps to do experiments with)

~~(Bonus bonus issue but science's shutters aren't directional yet)~~

![image](https://user-images.githubusercontent.com/51863163/179343599-cf1aa134-ef35-4835-ac2b-fbc3c10160f4.png)

**Comment by 13spacemen** [comment]
@MrMelbert it's not just science's shutters, all the shutters on the station got reverted by someone who edited it without directional shutters

**Comment by san7890** [comment]
Issue with shutters should be fixed with #68464.
