### ISSUE TITLE
New Long-Ranged Gas Analyzer can scan thru walls

### ISSUE THREAD

**Issue by OrionTheFox** [tgstation/tgstation#68469]
## Round ID:
Any (Found on downstream test server while prepping the Mirror)(No its not a downstream issue)

## Testmerges:
None (Test server)

## Reproduction:
https://user-images.githubusercontent.com/76465278/179347123-8768c48f-6903-4aa1-8987-47352fa80122.mp4

Get a ranged analyzer
Go beside a wall
Click around where the room the other side of the wall probably is
Scan that room

Doesnt work if there's another wall wherever you click though.

**Comment by TheBoondock** [comment]
God damn it, honestly sounds a bit fitting to me since its bluespace powered and all. I'll ask lemon his thoughts

**Comment by TheBoondock** [comment]
actually nevermind fixing it rn

**Comment by kopoba** [comment]
can its scan anomalys?
