### ISSUE TITLE
Slimepeople provide a soft landing for themselves

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#68466]
## Reproduction:

- Be slimeperson. 
- Fall
- Get a message that you provided a soft landing... for yourself. 
- Be fine. 

Also shows for walking down stairs.

**Comment by necromanceranne** [comment]
Should be a feature. But you splat into a puddle for a bit.

**Comment by moocowswag** [comment]
Slime people are one of the few species that cant get wings so maybee???

**Comment by Mooshimi** [comment]
shouldn't show for walking down the stairs

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/0131d55d3aa9cbdea7a1dd51c1fb21a7ec61cddb/code/modules/mob/living/carbon/human/species_types/jellypeople.dm#L45-L50

https://github.com/tgstation/tgstation/blob/0131d55d3aa9cbdea7a1dd51c1fb21a7ec61cddb/code/datums/elements/soft_landing.dm#L1-L25

https://github.com/tgstation/tgstation/blob/952c3ee0d3075d94edc6f1af2954408f7edd15c1/code/game/turfs/turf.dm#L298-L322

https://github.com/tgstation/tgstation/blob/6236a0ddd1bd3c4e5574eb9fdebf4d79ccad2d2f/code/__DEFINES/movement.dm#L42-L62
