### ISSUE TITLE
Antag revealing bug

### ISSUE THREAD

**Issue by Bluedino1025** [tgstation/tgstation#68460]
Reporting client version: 514.1585

## Round ID:
[186722](https://scrubby.melonmesa.com/round/186722)

## Testmerges:
- [Reworks pAIs](https://www.github.com/tgstation/tgstation/pull/68241)
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)
- [Barf a bunch of dynamic logs](https://www.github.com/tgstation/tgstation/pull/68137)

## Reproduction:

High five someone who's an antag and it will say something like this in your memories "The high five between the medical doctor and %DEUTERAGONIST."

**Comment by TemporalOroboros** [comment]
Deuteragonist in this case is just being used to refer to the other person in the interaction. It's basically just "second protagonist".

**Comment by LemonInTheDark** [comment]
Monkey sees %******agonist%
conditioned response
