### ISSUE TITLE
Glass floors are made of pure suffering

### ISSUE THREAD

**Issue by tnekohue** [tgstation/tgstation#68461]
## Reproduction:
Exist, really, thats about it

![image](https://user-images.githubusercontent.com/17634568/179341542-4dc0395f-9e60-4dc0-9ac8-b13148ad7a9c.png)

**Comment by tnekohue** [comment]
The gas is visible above the floor and the character who is also above the floor

**Comment by ArcaneMusic** [comment]
This is, admittedly, still very vague. Was the gas there roundstart?
What map was this on? This appears to be multi-Z, which contributes to the confusion. Was the gas released still there when the screenshot was taken? Was it on your current Z-level, or below you?

**Comment by tnekohue** [comment]
No, it was not present at roundstart, this particular map was Ice box, this is the toxins mixing area.
The gas is on a lower z-level, its rendering above me even though thats the case.
That gas was still there.

**Comment by timothymtorres** [comment]
This might get fixed with #67902

**Comment by LemonInTheDark** [comment]
shhhhhhhhhhhhhhhhhhhh (yes it would, this is a vis_contents issue)

**Comment by LemonInTheDark** [comment]
Wait no it wouldn't. At least not yet I might poke around a bit
