### ISSUE TITLE
Tipping over an arachne borg messes with the chatbox.

### ISSUE THREAD

**Issue by orthography** [tgstation/tgstation#68477]
## Reproduction:

Tipping over a borg fucks up their chatbox, at least with the Arachne it does.

![image](https://user-images.githubusercontent.com/98856144/179367843-bfea5b30-2519-4eef-8100-da2c080bd0f8.png)

**Comment by Time-Green** [comment]
Arachnes are dead

**Comment by Time-Green** [comment]
Also next time just put this on the PR if you can
