### ISSUE TITLE
You can do some serious business with brains.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#68481]
## Round ID: 
[185757](https://scrubby.melonmesa.com/round/185757), replicated at the private sever with the current build as well.
## Testmerges:
[#68396: 'Nukie Rework Part 1: Removes some stuff from nukie uplink, adds it as keycard bonuses instead.' by Fikou at commit bcf2609673](https://www.github.com/tgstation/tgstation/pull/68396)
[#68401: 'Nukie Rework Part 2: Nuclear Operative starting gear rework' by Fikou at commit b175bb84b6](https://www.github.com/tgstation/tgstation/pull/68401)
[#68444: 'Arachne Borgs' by axietheaxolotl at commit 924e92f215](https://www.github.com/tgstation/tgstation/pull/68444)
## Reproduction:
1) Place an active brain into an MMI.
2) Take the brain out of an MMI.
3) Congratulations, you have a talking brain, thats showing up as the totally dead one.
![brain](https://user-images.githubusercontent.com/34580767/179369439-615b8694-7353-4de5-86a5-1b36d761bbc2.png)
4) Place the brain into the body.
5) Congratulations, you are spamming the admin log now. The user of the brain can't see nor hear. The body will be shown as the soulless one.
![brain2](https://user-images.githubusercontent.com/34580767/179369539-ab7c2917-00b9-411b-bd6d-088f7958343e.png)
6) Remove the brain again. You once more have the talking brain.
![brain3](https://user-images.githubusercontent.com/34580767/179369678-dfb0fd5e-df71-4834-94fd-d27e447eeb7b.png)
Defibrillation of the body with that alive brain will leave the catatonic body behind.
If you remove the brain of that catatonic body, you will have your talking brain back again.
The brain will deteriorate like a normal organ would. However, even with the 200 brain damage the brain will still be able to talk. You can use that as the worse pAI, I suppose, like a very wicked pet of sorts.

**Comment by 13spacemen** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/68451

**Comment by IllotAFV** [comment]
Alright
