### ISSUE TITLE
Round refused to start

### ISSUE THREAD

**Issue by notfrying1pans** [tgstation/tgstation#68483]
Reporting client version: 514.1585

## Round ID:
[186761](https://scrubby.melonmesa.com/round/186761)

## Testmerges:
- [Barf a bunch of dynamic logs](https://www.github.com/tgstation/tgstation/pull/68137)
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)
- [Arachne Borgs](https://www.github.com/tgstation/tgstation/pull/68444)

![image](https://user-images.githubusercontent.com/49667761/179371306-d0f330e6-a318-4ba7-9bf5-9be4c8b981b1.png)

**Comment by notfrying1pans** [comment]
@NoxVS asked me to

**Comment by Mooshimi** [comment]
![image](https://user-images.githubusercontent.com/85910816/182754602-3ff8075b-efaa-4fe6-89a6-95cc18915879.png)
![image](https://user-images.githubusercontent.com/85910816/182754669-4ccbb6a9-8ac6-4b9e-9816-5c5d0f4af5da.png)
![image](https://user-images.githubusercontent.com/85910816/182754888-c8392a9e-8be7-435f-bb62-e7dd1c62dc7e.png)

**Comment by Mooshimi** [comment]
Dont see any runtimes necessarily related:
![image](https://user-images.githubusercontent.com/85910816/182755312-8db3c3b7-b8dc-4ac0-aa67-62bb50cb01aa.png)
![brave-23 14 25 714](https://user-images.githubusercontent.com/85910816/182755321-ca92b004-c1a5-4e0e-87ca-723f65d6d131.png)
