### ISSUE TITLE
Brain has no .loc with a client, causing them to repeatedly be sent to the secret room, and then back to nullspace

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#68497]
Reporting client version: 514.1583

## Round ID:
[186760](https://scrubby.melonmesa.com/round/186760)

## Testmerges:
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)
- [Revert "Fixes admin.fun list"](https://www.github.com/tgstation/tgstation/pull/68369)

## Reproduction:
Happened on the attached round, as well as on an earlier Terry round. 

As described by the player, they were killed and decapitated by a traitor, someone tried to fix their brain and put it a morgue human, then they were suddenly in the void. This then proceeded to spam admin logs and relays like crazy.

![image](https://user-images.githubusercontent.com/66640614/179374664-8c443a01-7b1e-48a3-9677-786ba3c6dca9.png)

**Comment by 13spacemen** [comment]
if they got put into an MMI and then ejected, there's a bug with the MMI not transferring the brainmob on eject_brain()

**Comment by san7890** [comment]
I believe this is the same issue as #68457 , which is fixed with #68451 since the same thing just happened on Terry Round 186787
