### ISSUE TITLE
Obsession photo objective is STILL BROKEN

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#68517]
RoundID 186789

be obsessed
take photo for objective
![image](https://user-images.githubusercontent.com/105343481/179390199-7ed45e92-6657-43c5-ae99-d3e23772dcc6.png)

**Comment by Fikou** [comment]
where was the photo stored? it only checks in your inventory

**Comment by trexter5555** [comment]
> where was the photo stored? it only checks in your inventory

thats probably it then, but the wording should be changed to "have a photo of x while they're alive in your backpack" or something
