### ISSUE TITLE
You appear under glass tiles in the SecurEye camera app

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#68514]
## Reproduction: Look at yourself on a glass tile while on SecurEye, icebox security is good for this.
![image](https://user-images.githubusercontent.com/54517726/179385502-f3f7ac65-7a76-4283-b21c-93df8aab8b5c.png)

**Comment by san7890** [comment]
Might be related to #61998 ?

**Comment by Baskett55** [comment]
probably the exact same bug since you can also use the detective spyglasses while blind too

**Comment by timothymtorres** [comment]
Yeah this is a dupe.  Also the blindness thing was ruled `Not a bug` by oranges and maintainers.  See: #58936

**Comment by timothymtorres** [comment]
Duplicate of #61998
