### ISSUE TITLE
 Double Malf Picker

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#68512]
Reporting client version: 514.1585

## Round ID:
[186778](https://scrubby.melonmesa.com/round/186778)

## Testmerges:
- [Arachne Borgs](https://www.github.com/tgstation/tgstation/pull/68444)
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)
- [Barf a bunch of dynamic logs](https://www.github.com/tgstation/tgstation/pull/68137)
- [Reworks pAIs](https://www.github.com/tgstation/tgstation/pull/68241)

## Reproduction:
Get combat upgrades as AI
Roll malf
First malfpicker can no longer receive malfbux:tm:, but can still be used.
Second can also be used.
????
![image](https://user-images.githubusercontent.com/50649185/179384059-32b504b8-abf7-4dc8-ae8d-9f5c3c533624.png)

**Comment by Sealed101** [comment]
can no longer reproduce; while the combat upgrade grants a separate action button to access the malf module picker, both it and the malf AI UI share the point pool. both receive points and can be used as normal
