### ISSUE TITLE
You can't auto collect ores from floor using mining satchels

### ISSUE THREAD

**Issue by Holoo-1** [tgstation/tgstation#68546]
## Testmerges: #68444 and #68241

related too https://github.com/tgstation/tgstation/issues/68547
## Reproduction:
0 rightclick with pka in hand
1 run around for 2-5 minutes untill it stops spamming "you are no longer aiming"
2 run over any ore
3 it stays on floor

**Comment by weesnaw-ops** [comment]
like.. first bit and all. aiming shit

**Comment by Fikou** [comment]
can't reproduce

**Comment by Fikou** [comment]
others can apparently

**Comment by san7890** [comment]
Where is the satchel? I heard of someone being able to reproduce it by it being in their pockets as opposed to in-hand/belt. That might be it?

**Comment by weesnaw-ops** [comment]
pocket or hand. Been able to reproduce. Severel people on skyrat have as wel

**Comment by Holoo-1** [comment]
fixed by https://github.com/tgstation/tgstation/pull/68556
