### ISSUE TITLE
Moving the tram with circuits can absolutely destroy the tram, breaking the universe

### ISSUE THREAD

**Issue by scriptis** [tgstation/tgstation#68541]
## Round ID:

[186841](https://scrubby.melonmesa.com/round/186841)

## Testmerges:

[#68241: 'Reworks pAIs' by jlsnow301 at commit e003870995](https://www.github.com/tgstation/tgstation/pull/68241)
[#68389: 'Shortens names on orbit ui' by jlsnow301 at commit 68551ab621](https://www.github.com/tgstation/tgstation/pull/68389)

## Reproduction:

Possibly related to #68222 

Somebody hooked a tram bot up to the tram. It went out of the right side of the station, sent a ton of players to the secret error room, completely broke, and had a bunch of other crazy side effects.

https://i.imgur.com/pcl44Fe.png

Players that were sent to the secret error room were still moved when the tram moved, which was also hysterical.

I was unable to retrieve the circuit responsible--it seems to have been deleted with half of the tram.

**Comment by moocowswag** [comment]
https://user-images.githubusercontent.com/62126254/179457431-31ad4bc5-7d1f-41bf-bef0-83609d91a6b4.mp4

you can hear someone spamming the button to the bot shell right before it crashed so I have reason to believe this isnt a circuit issue but a spamming the tram issue and it might also happen just from people spam calling it at the right time.

**Comment by Mothblocks** [comment]
@Kylerace i am willing to say this is probably your fault somehow

reminds me of #68247

**Comment by newfren** [comment]
this is the funniest shit I've ever seen

**Comment by bob-b-b** [comment]
looks fun, could get locked behind an emag interaction instead of being completely removed

**Comment by Kylerace** [comment]
fixed
