### ISSUE TITLE
Weird behavior with the Smooth-Headed quirk and HARS mutation

### ISSUE THREAD

**Issue by Teleported-Bread** [tgstation/tgstation#68563]
Reporting client version: 514.1566

## Round ID:
[186875](https://scrubby.melonmesa.com/round/186875)

## Testmerges:
- [[Ready for Review] Admin lua scripting](https://www.github.com/tgstation/tgstation/pull/65635)
- [Reworks pAIs](https://www.github.com/tgstation/tgstation/pull/68241)
- [New Satchel and Backpack Sprites!](https://www.github.com/tgstation/tgstation/pull/68524)

## Reproduction:

During a Radiation Storm, i gained the HARS mutation. Despite this, i had the moodlet for being upset about not wearing headware. Upon having the mutation removed by mutadone, i had my natural hair restored (which i did not have before HARS). I still, though, had the moodlet for wanting to cover my bald head. Wearing my wig worked as normal in this state
Step 1: Have the smooth head quirk
Step 2: Gain hars
Step 3: cry because you have low mood
Step 4: lose hars
Step 5: Stare in bewilderment at your head full of hair, but still cry until you find a hat or your wig.
![image](https://user-images.githubusercontent.com/28495609/179615443-d7bf3295-8a21-4020-ac32-24079f9ef936.png)
^Me, gaining HARS during a radstorm and checking mood

**Comment by Y0SH1M4S73R** [comment]
seems to be a bug with hair in general - while testing a PR of mine that involves hair, I discovered that giving the baldness quirk to a mob and stripping their wig still makes them look like they have hair, while technically still being bald. Conversely, gaining hair as a non-human using spray tan OD (or the thing I'm implementing in said PR) still makes you appear hairless
