### ISSUE TITLE
Nightshift subsystem does not resume if called by an admin

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#68564]
## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:

Wait for the night shift system to trigger, or trigger it manually. Place a breakpoint in the loop iterating over the currentrun list, and notice how it yields after checking just one APC (at least on the server I visit, and during local testing), and doesn't fire again to resume.

Update, 22/08/02
Automatic triggering has been fixed, admin setting still does not work.

**Comment by Profakos** [comment]
It looks like naturally occurring night shift has been fixed. The only problem right now is admin triggering them. Updating this issue to reflect on this change.

**Comment by SyncIt21** [comment]
@Profakos #74657 might have fixed this entirely, Can you confirm?

**Comment by Profakos** [comment]
Looks like it has been fixed, the other issue was a duplicate of this one. Closing it, thank you for alerting me.
