### ISSUE TITLE
Demonic Frost Miner is not spawning (at all? ever? most rounds?)

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#68579]
## Reproduction:
ok so I looked through every single icebox round for the past three days on manuel (manually, because I don't know how to search the logs and did the first thing that seemed to work) and in zero of the 8 did the demonic frost miner spawn. I code dove a bit and the ruin's supposed to be called "Mining Site" for the top bit and "Mining Site Underground" for the arena itself, and from the game.txt I couldn't find a single time they loaded in.

This has anecdotally been happening for a while but I don't know how I'd tell you how long it's been happening for without a lot of very tedious work.

**Comment by msgerbs** [comment]
Confirmed this does not spawn at all, and it is set to always spawn so something's not working right. I'm looking at it.

**Comment by newfren** [comment]
round 191600, demonic frost miner failed to spawn on icebox

**Comment by msgerbs** [comment]
The log says the mining site loaded, was it missing the underground part where the miner spawns? Have you seen it spawn in any rounds since the fix?

**Comment by msgerbs** [comment]
Alright I found the issue. I'm going to make a new issue for this since it's technically a different problem and multi-z ruins are a fuck and deserve their own issue.
