### ISSUE TITLE
Gulag doesn't interact properly with Modsuits

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#68574]
## Round ID: 
[186884](https://scrubby.melonmesa.com/round/186884)

## Testmerges:
#68241 
#68444
(I think)

## Reproduction:
- Have a modsuit on and active;
- Be gulaged;
- Arrive without the modsuit control unit, but with the head, gloves, suit, and boots parts, as well as the prisoner clothing and a backpack.

In this case, when the player reclaimed their equipment, the modsuit control unit was gone (maybe because I deleted one of the body parts).

**Comment by Mooshimi** [comment]
CC @Fikou
