### ISSUE TITLE
Split personality can ghost you

### ISSUE THREAD

**Issue by Thaums** [tgstation/tgstation#68573]
## Testmerges:

#68241 
#68389

## Reproduction:

At one point when switching personalities it just ghosted me instead of taking away control temporarily, leaving the other personality at the wheel. I was actually the original so I effectively got permanently kicked out of my own body. Trying to enter it just gave "Another consciousness is in your body...It is resisting you."

The character in question was Anton Sugar if anyone wants to poke in the logs

**Comment by Mooshimi** [comment]
I had this issue after revival, where my ghost couldn't enter the body at all afterwards. The same feedback message showed up.

**Comment by Profakos** [comment]
Has #73579 fixed this?

**Comment by Sealed101** [comment]
#73579 has indeed fixed this
