### ISSUE TITLE
Blankets no longer lay atop mobs

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#68594]
Reporting client version: 514.1585

## Round ID:
[186948](https://scrubby.melonmesa.com/round/186948)

## Reproduction:

Whereas before if you were to lay down on a bed with a blanket on it you would lay beneath the blanket, you now lay atop the blanket.

**Comment by Palpetinus** [comment]
For me, it never worked like you state in your "Reproduction" section, I was always on top. To get blankets to be on top, you have to use them in-hand. I don't rightly know what the intended behavior is, but not having the blanket on top when it's not intended (by simply moving onto a bed, for example) seems like a good thing.

**Comment by timothymtorres** [comment]
So apparently this is intended.  You need to "tuck" the mob under the bedsheet use them in-hand.  Later on I plan on adding tooltips so this is more apparent for people.
