### ISSUE TITLE
Ghosts can not see AI laws.

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#68604]
Reporting client version: 514.1566

## Round ID:
[186972](https://scrubby.melonmesa.com/round/186972)

## Testmerges:
- [Reworks pAIs](https://www.github.com/tgstation/tgstation/pull/68241)
- [Arachne Borgs](https://www.github.com/tgstation/tgstation/pull/68444)
- [Refactored fundamental circuit components that have varying inputs. Improvements to the integrated circuit UI](https://www.github.com/tgstation/tgstation/pull/68586)

## Reproduction:
Be ghost, click on AI, you can't check the laws.
I blame https://github.com/tgstation/tgstation/pull/68063

**Comment by ShizCalev** [comment]
unable to repo on live.
![image](https://user-images.githubusercontent.com/6209658/180339806-16d7952d-6ea6-4a16-9c0d-72488e7cda2d.png)

**Comment by Striders13** [comment]
> unable to repo on live. ![image](https://user-images.githubusercontent.com/6209658/180339806-16d7952d-6ea6-4a16-9c0d-72488e7cda2d.png)

AI was malf the round people were having this issue. Maybe that has something to do with it?

**Comment by Mooshimi** [comment]
Unable to replicate with a malf AI.

**Comment by Striders13** [comment]
Well, doesn't seem to be the case anymore.

**Comment by timothymtorres** [comment]
San figured it out in his PR:

https://github.com/tgstation/tgstation/blob/374acb7ac11d9633d4ab60c866c5db32940506a2/code/game/objects/items/AI_modules/_AI_modules.dm#L31-L34

It was the `Adjacent()` check which applies even to ghosts so it means if you are not directly next to the AI the laws wouldn't display.

**Comment by timothymtorres** [comment]
False alarm guys.  The examine code is different for the silicon mobs and the actual AI module item boards.
