### ISSUE TITLE
Organ transport box does not preserve organs

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#68605]
Reporting client version: 514.1566

## Round ID:
[186972](https://scrubby.melonmesa.com/round/186972)

## Testmerges:
- [Reworks pAIs](https://www.github.com/tgstation/tgstation/pull/68241)
- [Arachne Borgs](https://www.github.com/tgstation/tgstation/pull/68444)
- [Refactored fundamental circuit components that have varying inputs. Improvements to the integrated circuit UI](https://www.github.com/tgstation/tgstation/pull/68586)

## Reproduction:
Insert cryostylane and an organ into organ transport box, cryostylane gets used up as usual but organs inside it still decay. Also, a little weird thing that the box becomes frozen when you put an organ in it (so you can throw it and it'll shatter).
This seriously fucks over organ thieves.

**Comment by timothymtorres** [comment]
When you say "organ transport box" are you talking about the freezer crate, the smartvendor, or the biohazard bag that lets you store organs in?

**Comment by Striders13** [comment]
> When you say "organ transport box" are you talking about the freezer crate, the smartvendor, or the biohazard bag that lets you store organs in?

/obj/item/storage/organbox
