### ISSUE TITLE
cigarette packet bugs

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#68607]
Reporting client version: 514.1584

## Round ID:
[186974](https://scrubby.melonmesa.com/round/186974)

## Testmerges:
- [Lemon does pain](https://www.github.com/tgstation/tgstation/pull/67902)

## Reproduction:
cigarette packages look empty when they're full and closed

ALSO

rightclicking a cigarette package removes a cigarette, alt clicking one opens it so you can see this contents - this is backwards from how it's supposed to be

**Comment by magatsuchi** [comment]
#68707
