### ISSUE TITLE
Xenomorph Larva Cannot Evolve

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#68623]
Reporting client version: 514.1585

## Round ID:
[186994](https://scrubby.melonmesa.com/round/186994)

## Reproduction:
Larva cannot evolve. Upon reaching full progress and choosing a form, at least the drone form, no evolution takes place and the option to evolve stays inactive.

**Comment by Shadowflame909** [comment]
yeah it breaks the xenomorph antag
