### ISSUE TITLE
cant properly attack as a rat king

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#68621]
Round ID: [186997](https://scrubby.melonmesa.com/round/186997)
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [3b3c74c5a9ba478500b839abbf75c8be8d0afd46](https://www.github.com/tgstation/tgstation/commit/3b3c74c5a9ba478500b839abbf75c8be8d0afd46)
The following pull requests are currently test merged:
[#67902: 'Lemon does pain' by LemonInTheDark at commit c89872a6df](https://www.github.com/tgstation/tgstation/pull/67902)

Local commit: ce7bc99b3dd42c711db959663f39b00d313488a2
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
[(F)](http://127.0.0.1:8646/tmp16544/browseroutput.html?src=[mob_3172];follow=[mob_3147])

## Reproduction:

become a rat king, attempt to click on people. youll start licking them no matter what combat mode you are on, you cant preform your normal slash attacks

**Comment by ATH1909** [comment]
mm inject them with your rat spit

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/98909277d4d0a3875fa451e1281f0e8e2d4d7969/code/modules/mob/living/simple_animal/hostile/regalrat.dm#L125-L146

**Comment by Mooshimi** [comment]
Related runtime located
``` 
[00:09:34] Cannot execute null.attack animal().
Thrown by AttackingTarget (/mob/living/simple_animal/hostile/proc/AttackingTarget) at hostile.dm, line 355
User: null (src)
Source: Maintenance Prince (/mob/living/simple_animal/hostile/regalrat/controlled)
Source Location: the floor (/turf/open/floor/iron) (104, 116, 2)
Stacktrace:
1 Maintenance Prince (/mob/living/simple_animal/hostile/regalrat/controlled): AttackingTarget(Akira Ashwind (/mob/living/carbon/human))
2 Maintenance Prince (/mob/living/simple_animal/hostile/regalrat/controlled): AttackingTarget(Akira Ashwind (/mob/living/carbon/human))
3 Maintenance Prince (/mob/living/simple_animal/hostile/regalrat/controlled): UnarmedAttack(Akira Ashwind (/mob/living/carbon/human), 1, /list (/list))
4 Maintenance Prince (/mob/living/simple_animal/hostile/regalrat/controlled): ClickOn(Akira Ashwind (/mob/living/carbon/human), "icon-x=17;icon-y=14;left=1;but...")
5 Akira Ashwind (/mob/living/carbon/human): Click(the floor (105,116,2) (/turf/open/floor/iron), "mapwindow.map", "icon-x=17;icon-y=14;left=1;but...")
```
