### ISSUE TITLE
Flashdarks don't follow the player

### ISSUE THREAD

**Issue by notfrying1pans** [tgstation/tgstation#68638]
Reporting client version: 514.1585

## Round ID:
[187034](https://scrubby.melonmesa.com/round/187034)

## Testmerges:
- [Lemon does pain](https://www.github.com/tgstation/tgstation/pull/67902)
- [Refactors SM Delaminations to be strategies](https://www.github.com/tgstation/tgstation/pull/68599)

## Reproduction:

1: Turn on flashdark
2: Move away from where you turned it on from.

**Comment by unit0016** [comment]
Also applies to the syndie lantern

**Comment by ChungusGamer666** [comment]
this should be fixed by https://github.com/tgstation/tgstation/pull/72148

**Comment by TerraGS** [comment]
Still an issue as of [Round ID]: 211018
