### ISSUE TITLE
Make AI button in player panel doesn't work on ghosts

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#68643]
Reporting client version: 514.1583

## Round ID:
[187041](https://scrubby.melonmesa.com/round/187041)

## Testmerges:
- [Refactors SM Delaminations to be strategies](https://www.github.com/tgstation/tgstation/pull/68599)
- [Reworks pAIs](https://www.github.com/tgstation/tgstation/pull/68241)
- [Arachne Borgs](https://www.github.com/tgstation/tgstation/pull/68444)
- [Drastically improved the USB connection for air alarms. Any airlock can now be made into a shell](https://www.github.com/tgstation/tgstation/pull/68632)

## Reproduction:
Related to #67028
Make AI button in the player panel creates a default AI below the ghost it's used on, and immediately ghosts the player with their AI name.

**Comment by ShizCalev** [comment]
Unable to repo.

**Comment by dragomagol** [comment]
Looks like it works on living mobs, but I was able to reproduce it again on Terry when I used it on myself as a ghost

**Comment by Time-Green** [comment]
I can't reproduce this, works fine for ghosts

**Comment by Sealed101** [comment]
it works fine with observer ghosts with no minds attached but fails on a dead player's ghost
