### ISSUE TITLE
Paper bins have no paper in their bins

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#68645]
## Reproduction:

All paper bins in existence - either roundstart or adminspawned - are completely void of paper. 
![image](https://user-images.githubusercontent.com/51863163/180314574-ff0ebc3a-cfea-4291-a56e-4d17c6bbd1a7.png)

**Comment by Mooshimi** [comment]
Closing bc you posted this in the pr responsible, thanks for doing so
