### ISSUE TITLE
Bioscrambler Anomaly cannot be defused by basic means

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#68640]
Reporting client version: 514.1585

## Round ID:
[187034](https://scrubby.melonmesa.com/round/187034)

## Testmerges:
- [Lemon does pain](https://www.github.com/tgstation/tgstation/pull/67902)
- [Refactors SM Delaminations to be strategies](https://www.github.com/tgstation/tgstation/pull/68599)

## Reproduction:
0. Be an AI controlled Engineering shell
1. Bioscrambler Anomaly spawns
2. Scan anomaly with gas analyzer
3. Send the signal (145.7, 47) through Remote Signaling Device
4. Anomaly remains completely intact
5. An Anomaly Defuser could still defuse the Bioscrambler Anomaly

**Comment by ShizCalev** [comment]
Bioscramblers don't have any code different from all the other anomalies.

**Comment by CoffeeDragon16** [comment]
Couldn't reproduce on local

**Comment by ShizCalev** [comment]
Gonna close in 7 days without additional input.
