### ISSUE TITLE
Auxlua registering signals on datums does not work

### ISSUE THREAD

**Issue by Watermelon914** [tgstation/tgstation#68656]
## Reproduction:

CC: @Y0SH1M4S73R 
Running this code will throw up an error in the editor. The error message is too vague for me to figure out what it means exactly.

`SS13.signal_handlers.[mob_2920].movable_moved.[0x2104c47c].func errored with the message "src\lib.rs,705: error converting Lua nil to function"`
```lua
local SS13 = require("SS13")

local human = SS13.new("/mob/living/carbon/human", dm.global_proc("_get_step", dm.usr, 0))

SS13.register_signal(human, "movable_moved", function(source)
    local location = human:get_var("loc")
    location:set_var("color", "#ff0000")
end)

**Comment by Valtosin** [comment]
it works on the https://github.com/tgstation/tgstation/pull/69271
![](https://i.imgur.com/sabklgs.png)

**Comment by Watermelon914** [comment]
it was fixed a while ago
