### ISSUE TITLE
Leather Satchels have pixel hierarchy issues

### ISSUE THREAD

**Issue by Jolly-66** [tgstation/tgstation#68675]
## Round ID:
Tested locally.

## Reproduction:
Leather satchels, when facing left (dir 8) have a rogue pixel that has higher priority and appears above clothing. This is more noticeable on "bigger" clothing items, like the clown suits.

<details>
<summary> Images </summary>

Satchel equipped

![image](https://user-images.githubusercontent.com/70232195/180576780-e520700a-765f-4c9b-8f7a-6e0c377171b1.png)

![image](https://user-images.githubusercontent.com/70232195/180576798-1a9045c7-40bd-410d-865c-c2c00e1acee0.png)

Satchel not equipped

![image](https://user-images.githubusercontent.com/70232195/180576833-7ea3e77e-de35-4655-8994-a47e832c19bf.png)

![image](https://user-images.githubusercontent.com/70232195/180576841-a41a34b9-3f4e-4027-89a8-9f1179f4adfa.png)

</details>

**Comment by Imaginos16** [comment]
Ancient bug, ninety nine of servers have this fuckup.
