### ISSUE TITLE
Wrenching a SM shard as a borg instantly kills you when you right click it

### ISSUE THREAD

**Issue by techno0** [tgstation/tgstation#68685]
## Round ID:
187139

## Testmerges:
[#68599: 'Refactors SM Delaminations to be strategies' by vincentiusvin at commit b95272e164](https://www.github.com/tgstation/tgstation/pull/68599)
[#68241: 'Reworks pAIs' by jlsnow301 at commit e003870995](https://www.github.com/tgstation/tgstation/pull/68241)
[#68444: 'Arachne Borgs' by axietheaxolotl at commit 924e92f215](https://www.github.com/tgstation/tgstation/pull/68444)
[#68632: 'Drastically improved the USB connection for air alarms. Any airlock can now be made into a shell' by Watermelon914 at commit aa11c812e6](https://www.github.com/tgstation/tgstation/pull/68632)

## Reproduction:
- Be borg
- Have a wrench
- See Supermatter shard
- Press right click
- Borg instantly dies

Continuation of:
https://github.com/tgstation/tgstation/issues/67130

You wrench tables and a lot of stuff with right click. Its kinda stupid for a right click to dust you.

**Comment by Mooshimi** [comment]
ive wrenched a sm shard as a borg before, is the issue that wrenching it doesn't use right click

**Comment by CPTANT** [comment]
There is internal inconsistency which button is used. Cannisters wrench with left mouse, but closets wrench with right mouse for example.

**Comment by Mooshimi** [comment]
True, stages of reconstruction also vary between right and left click for tools
