### ISSUE TITLE
necropolis chest opened but has no loot inside

### ISSUE THREAD

**Issue by Helvetica8563** [tgstation/tgstation#68688]
Reporting client version: 514.1585

opened a necropolis chest with a skeleton key contained no items has happened to me a couple times dont know how to replicate it
as it seems to happen randomly
![image](https://user-images.githubusercontent.com/105236622/180608604-a2440092-43f2-4414-aae5-d096f9d4c654.png)
round id was 45
bug found on Austation TG byond://game.austation.net:2337

**Comment by ShizCalev** [comment]
did it say You disable the magic lock, revealing the loot?

**Comment by CoffeeDragon16** [comment]
duplicate of #67650

**Comment by timothymtorres** [comment]
This has been happening a lot to other people.  I tried to dig through server logs on the other duplicate issues and couldn't find any runtimes that might indicate what went wrong.

**Comment by CoffeeDragon16** [comment]
yeah, ive handled an ahelp where this happened and i couldn't find any leads nor anything in the logs

**Comment by Livrah** [comment]
Lootboxes for you

**Comment by Helvetica8563** [comment]
> did it say `You disable the magic lock, revealing the loot.` when you opened it?

it most definetly did sorry didnt get a screenshot of chat

**Comment by ShizCalev** [comment]
Dupe of #67650
