### ISSUE TITLE
Mining Shuttle Hyperspace doesn't move you

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/tgstation#6869]
Unlike the immediate area around pods and the emergency shuttle, the mining shuttle hyperspace doesn't throw you back away from the pod. You can chill quite comfortably next to it

**Comment by Carn** [comment]
dunt wurkan
u feex

**Comment by Carn** [comment]
Cannot replicate, it's throwing me as expected.
Insufficient information.
How did you leave the shuttle? did you run out of the door? were you thrown?

**Comment by Carn** [comment]
were you a ghost?

**Comment by Stickymayhem** [comment]
I was punted out after being hit by it for being a retard. My corpse sat on the left side between the windows without moving adjacent to the shuttle.

I spawned a human mob in the area to attempt to replicate and it too did not move.

**Comment by paprka** [comment]
That's a lot of information you should have added initially sticky

**Comment by Carn** [comment]
was punted out after being hit by it for being a retard. 

by it you are referring to what? The queen?

**Comment by Carn** [comment]
between the windows,
what does this mean?

**Comment by Jalleo** [comment]
Basically when the shuttle landed Stickys mob was already there instead of getting thrown a fair distance or even into space already dead you just get stuck to the edge of the shuttle area just outside where the shuttle would be. This may be due to mapping with reasons

**Comment by Carn** [comment]
Oh, It's due to me not understanding how momentum works in space. I'll sort it out when I get a chance.Trying to find some bug burried in timsort atm.
:sob:

**Comment by Jalleo** [comment]
Gotcha have fun and a nice break from shuttles.
