### ISSUE TITLE
Destroying an AI controlled mech kills the AI too

### ISSUE THREAD

**Issue by WrillWasTaken** [tgstation/tgstation#68713]
## Round ID:
[187198](https://scrubby.melonmesa.com/round/187198)

## Testmerges:
[#68571: 'Removes requirements from most midround rulesets, and lowers their minimum population to run, because nobody knows what it means' by Mothblocks at commit c2f7f54fe8](https://www.github.com/tgstation/tgstation/pull/68571)
[#68630: 'Revolution victories now call the shuttle when enough of the station is revolutionaries' by Mothblocks at commit c001c14cf6](https://www.github.com/tgstation/tgstation/pull/68630)

## Reproduction:
Be a normal AI -> control mech with AI control beacon -> mech destroyed for any reason -> you are now a ghost, your core is now a blank AI core.

**Comment by zxaber** [comment]
AI that are carded/shunted into a mech are supposed to be put into the wreckage if the mech is destroyed. This seems to currently not work, as one of the mech reworks has AIs just get gibbed if the exit proc has `force = TRUE`.

Simultaneously, `AI.linked_core` also isn't being checked (and AI being sent back), which means that AIs remotely controlling the mech also get gibbed.

I will implement a fix PR when I have a moment, within the next day or two.

**Comment by timothymtorres** [comment]
I suspect this might be related to #38443
