### ISSUE TITLE
Dog eat dog envirochow not healing or buffing monsters

### ISSUE THREAD

**Issue by blackdav123** [tgstation/tgstation#68717]
## Round ID:
[187213](https://scrubby.melonmesa.com/round/187213)

## Testmerges:
n/a

## Reproduction:
1. Craft dog eat dog envirochow
2. attempt to feed it to a cytology creature or gold slime creature
3. using the can while unopened gives the proper "open the can moron" message but opening the can and using it does nothing

Both the creatures I used it on were sentient so that may make a difference

**Comment by ShizCalev** [comment]
Intentional. #61532
https://github.com/tgstation/tgstation/blob/70faa854b47fe784bb863e78a5b3a68f8464ab54/code/game/objects/items/food/misc.dm#L731-L732
