### ISSUE TITLE
AI core duplication by unwrenching

### ISSUE THREAD

**Issue by Ekaterina-von-Russland** [tgstation/tgstation#68710]
## Round ID: 187198

If you discovered this issue from playing tgstation hosted servers:
[Round ID]: [187198](https://scrubby.melonmesa.com/round/187198)
## Testmerges:

The following pull requests are currently test merged:
[#68571: 'Removes requirements from most midround rulesets, and lowers their minimum population to run, because nobody knows what it means' by Mothblocks at commit c2f7f54fe8](https://www.github.com/tgstation/tgstation/pull/68571)
[#68630: 'Revolution victories now call the shuttle when enough of the station is revolutionaries' by Mothblocks at commit c001c14cf6](https://www.github.com/tgstation/tgstation/pull/68630)

## Reproduction:

Unwreching an active AI core creates a new, empty AI core in the same tile, which can be dragged.
![bug report](https://user-images.githubusercontent.com/109872269/180647947-b553b294-6fac-46e8-8366-116d139b61d0.png)

**Comment by WrillWasTaken** [comment]
I believe it was actually the act of carding me and putting me back in that made another AI core, not the unwrenching. You do need to unwrench it to actually move it though.

**Comment by ShizCalev** [comment]
oh someone was dumb and forgot to do a sanity check. i'll open the pr in the morning.
