### ISSUE TITLE
Malfunctioning AIs cannot unlock the cyborgs. 

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#68716]
There was a PR, that removed the unlocking feature from the AIs, if the cyborgs were locked by a player with a proper access. But with that malf AIs just cannot unlock them as well. Intentional or an oversight?

**Comment by zxaber** [comment]
Intentional. This was the trade to remove cyborg detonations.

In the Malf AI's case, you can still hack and detonate if the crew is planning on desyncing the borg.

**Comment by IllotAFV** [comment]
Alright. Maybe it makes sense. If a player is nearby the console, they already won.
