### ISSUE TITLE
Remote Signalers doesn't trigger emitters

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#68733]
## Reproduction:

None of emitter's wires trigger a shot to be fired when pulsed with remote.

**Comment by orthography** [comment]
Tested this, and was able to get lasers fired off with the remote/multitool by pulsing the WIRE_ZAP. But as the emitter already fires about as fast as it's capable it doesn't do much. 

A new wire that switches the emitter to manual fire (or something like that) seems like the work around.

**Comment by antropod** [comment]
I had issue with custom guns, specifically accelerator laser cannon
When you put it in emitter and connect signaller to the wire, it doesn't work.
But if you pulse it manually, it does work

**Comment by 13spacemen** [comment]
remote signaller igniter assembly on welding fuel tanks also doesn't work

**Comment by msgerbs** [comment]
When you guys were testing this were you by chance using the default signaler frequency? If so, I fixed this: #69773

**Comment by antropod** [comment]
I used default frequency, but different code

**Comment by msgerbs** [comment]
Good enough for me. If somebody sees this again make a new issue cause I'm pretty sure this was it.

Fixed by #69773
