### ISSUE TITLE
AI combat upgrade tab is a NtOS tab

### ISSUE THREAD

**Issue by Antischoker** [tgstation/tgstation#68742]
so the oder round on tg terry I was AI and some miner gave me combat upgrade, after that i got some models and when i got the mech one the tab where you buy the models turned in to a NtOS tab. I don't know if that bug happens to oder people to or not but i just wanted to tell that it is there

round ID was [187276

**Comment by dragomagol** [comment]
If you see this again, please try to take a screenshot of the error you see

**Comment by Sealed101** [comment]
closing as no repro is available
