### ISSUE TITLE
Having a holopad move while someone is connected to it will teleport the callee

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#68746]
## Reproduction:

#68650 made it harder for people to move holopads and teleport people, but it did not fix the issue itself. 

If a holopad moves while someone is connected to it, the callee will teleport to the location of the holopad. 

This can be done a few ways in game - one example is by calling a holopad located on the Tram.

**Comment by TheSmallBlue** [comment]
This glitch is STILL a thing, you can call the AI to a holopad, drag the holopad and immediately teleport the AI to where you are, making ai stealing stupid easy

**Comment by TheSmallBlue** [comment]
Here's a video showing exactly how it works:

https://youtu.be/a04zme_J0D0
