### ISSUE TITLE
5000 hc random points does not give you a golden wheelchair with the parapalegic perk

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#68762]
Reporting client version: 514.1584

## Round ID:
[187308](https://scrubby.melonmesa.com/round/187308)

## Testmerges:
- [Refactors SM Delaminations to be strategies](https://www.github.com/tgstation/tgstation/pull/68599)

## Reproduction:
![image](https://user-images.githubusercontent.com/12635164/180967169-3e345992-fff3-4a55-85e3-305986892d81.png)

I did my time give me the goods

this is my first round after getting the points required and I think I set paraplegic in the set up screen as the round started. I latejoined instead of starting the shift in vivo

NEXT round I was shift start and still did not have the wheelchair

**Comment by orthography** [comment]
This looks like a job for me.

**Comment by newfren** [comment]
still happening the next day
