### ISSUE TITLE
cannot read null.legacy

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#68769]
## Testmerges:
https://github.com/tgstation/tgstation/pull/61440
https://github.com/tgstation/tgstation/pull/61835

## Reproduction:
![brave-14 02 18 734](https://user-images.githubusercontent.com/85910816/181079132-8e0b295b-8427-4fba-9245-869212c30bc2.png)

**Comment by ShizCalev** [comment]
that's... from over a year ago?

**Comment by Mooshimi** [comment]
> that's... from over a year ago?

your comment insinuates issue jannies are now closing issues older than a year old
