### ISSUE TITLE
Weakpoint charge can be used on people, instead of just on ... weakpoints

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#68775]
## Round ID:
[187329](https://scrubby.melonmesa.com/round/187329)

## Testmerges:
#68599

## Reproduction:
Guy was in Robotics and got a bomb planted on them instead of the actual station

![Screenshot_1](https://user-images.githubusercontent.com/95751821/181092580-9c193374-c617-4066-95f6-7780ba3bfc11.png)

**Comment by Jackal-boop** [comment]
i will not apologize for sending that moff to syndicate controlled space with that charge
