### ISSUE TITLE
Oh Hi Daniel is incorrectly labelled as Oh Hi Mark

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#68789]
![image](https://user-images.githubusercontent.com/105343481/181164667-3c8492fe-2427-4772-bd29-b6ae579a4a48.png)

fix this immediately

**Comment by timothymtorres** [comment]
This was originally added in #17592.  Relevant code:

https://github.com/tgstation/tgstation/blob/f5ea51339f8e65d161a3c0144b391e859dd6038a/_maps/shuttles/emergency_imfedupwiththisworld.dmm#L6-L11

@Iamgoofball did someone forget to change the name or was this deliberate?

**Comment by orthography** [comment]
> This was originally added in #17592. Relevant code:
> 
> https://github.com/tgstation/tgstation/blob/f5ea51339f8e65d161a3c0144b391e859dd6038a/_maps/shuttles/emergency_imfedupwiththisworld.dmm#L6-L11
> 
> @Iamgoofball did someone forget to change the name or was this deliberate?

@timothymtorres https://github.com/tgstation/tgstation/pull/17592/commits/8b4524603435c90a7d9816fac18aa820321deb3a
