### ISSUE TITLE
Eternal fire visual bug for alien alloy golems

### ISSUE THREAD

**Issue by Sm0lKiwi** [tgstation/tgstation#68781]
Reporting client version: 514.1575

## Round ID:
[187345](https://scrubby.melonmesa.com/round/187345)

## Testmerges:
- [Drastically improved the USB connection for air alarms. Any airlock can now be made into a shell](https://www.github.com/tgstation/tgstation/pull/68632)
- [Refactors SM Delaminations to be strategies](https://www.github.com/tgstation/tgstation/pull/68599)
- [Revamped Away Mission: Caves (needs testing)](https://www.github.com/tgstation/tgstation/pull/68686)
- [Adds the Mothroach](https://www.github.com/tgstation/tgstation/pull/68763)

## Reproduction:

As a miner i used the Mirror of envy (if thats what it was called) to turn self into an alien alloy golem, after which i realised i cant wear clothing so i wanted to turn back. while doing so, i accidentally stepped into lava and seeing as golems are imune it set me on fire without me being able to actually put it out with an extinguisher or rolling. Even after changing races back it appeared as if i was on fire without actually dealing the damage. Visual effect was there for everyone. It might either be an issue with the mirror or just the race and lava combination itself.
Worthy note is also that i used a hierophant staff to get into the lava, not just walked into it.

**Comment by Mooshimi** [comment]
This doesn't just occur with golems, it's probably any mob since I've seen it on Mothpeople and Humans.

**Comment by tgsAvylaar** [comment]
I have recently had this happen multiple times, but ONLY as a miner. For me, and I can recall one occurence vividly (and probably have some footage somewhere), it happened once I was burned by a fire attack from a drake. I had indeed killed hiero on beforehand. It had nothing to do with the lava.

**Comment by tgsAvylaar** [comment]
https://youtu.be/xpC-otk_GGw Interesting video here, where I have it and manage to dispel the bug later. It happened with lava here without the hiero staff being involved.

**Comment by Mooshimi** [comment]
Closing this in favor of #70406
