### ISSUE TITLE
Burning rust off walls doesn't blind you

### ISSUE THREAD

**Issue by Jolly-66** [tgstation/tgstation#68796]
## Round ID:
Tested locally.

## Reproduction:
Go to burn rust off a wall, your eyes are fine.
Go do ANYTHING else with a welder, your eyes are NOT fine.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/af4d6af96c3eefcc3698a0824d9b1906aac3cb90/code/game/objects/items/tools/weldingtool.dm#L58-L61

https://github.com/tgstation/tgstation/blob/8b591f13eb03fcfbf02d5af6d8d2694e114f0cc0/code/datums/elements/rust.dm#L40-L63

https://github.com/tgstation/tgstation/blob/1c81adac8dda623cd97a944dd30ab38df6f52b00/code/datums/elements/tool_flash.dm#L6-L37

Looks like the signals for `COMSIG_TOOL_IN_USE` or `COMSIG_TOOL_START_USE` need to be called in the rust element.
