### ISSUE TITLE
Shot glass filled sprite is incorrect

### ISSUE THREAD

**Issue by Jolly-66** [tgstation/tgstation#68798]
## Round ID:
Tested locally.

## Reproduction:
Fill the shot glass

![image](https://user-images.githubusercontent.com/70232195/181307268-b4ad2d3c-ab2e-47f2-a496-58450ecaadd5.png)

**Comment by Likteer** [comment]
68227

**Comment by Likteer** [comment]
#68227

**Comment by Jolly-66** [comment]
Dupe issue
