### ISSUE TITLE
RPEDs can no longer hold beakers

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#68808]
## Round ID:
[187383](https://scrubby.melonmesa.com/round/187383)

## Testmerges:
Unknown

## Reproduction:
Try to shove a beaker into a borg RPED. Realize it no worky. See nothing in changelog. Admin confused too.

**Comment by antropod** [comment]
that means that borgs can't construct techfabs and some other machines

**Comment by Mooshimi** [comment]
when did you first notice this? I saw about a month ago probably

**Comment by Mooshimi** [comment]
seems to be caused by
https://github.com/tgstation/tgstation/pull/67478
this line specifically
![image](https://user-images.githubusercontent.com/85910816/181369569-ba793bf8-a5bd-4ca5-8a57-976aef6671ea.png)

**Comment by Mooshimi** [comment]
https://github.com/tgstation/tgstation/pull/68822
