### ISSUE TITLE
BSA is missing part description

### ISSUE THREAD

**Issue by Edelor68** [tgstation/tgstation#68805]
## Reproduction:
In the description of the machine frame of the BSA bore it only says that it needs manipulators without specifiying which even though it needs specifically tier 4 ones.
This can be very confusing.

![SS13BSABug](https://user-images.githubusercontent.com/85312201/181352279-82a96335-6afc-4418-bbf7-8e2253907d68.png)

**Comment by newfren** [comment]
also happens on the dna vault

**Comment by cacogen** [comment]
fuck i thought i specifically tested for this when i updated how these descriptions read
