### ISSUE TITLE
Shooting while running may hit you

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#68809]
## Round ID: 
[187391](https://scrubby.melonmesa.com/round/187391)

## Testmerges:
#68763 
#68686 
#68599 
#68632 

## Reproduction:
Shoot in front of you while running in that same direction. 
You may find yourself getting shot at by your own bullet/projectile.
https://imgur.com/2CTTpEF

**Comment by dragomagol** [comment]
Fixed by #68804 (should be resolved after the servers update)
