### ISSUE TITLE
spawning with a helmet/modsuit on your head can make you bald

### ISSUE THREAD

**Issue by kawoppi** [tgstation/tgstation#68818]
## Round ID:
[187395](https://scrubby.melonmesa.com/round/187395)

## Testmerges:
The following pull requests are currently test merged:
[#68763: 'Adds the Mothroach' by Justice12354 at commit c7f6c15f6e](https://www.github.com/tgstation/tgstation/pull/68763)
[#68686: 'Revamped Away Mission: Caves (needs testing)' by MMMiracles at commit 8b1936fb95](https://www.github.com/tgstation/tgstation/pull/68686)
[#68599: 'Refactors SM Delaminations to be strategies' by vincentiusvin at commit b95272e164](https://www.github.com/tgstation/tgstation/pull/68599)
[#68632: 'Drastically improved the USB connection for air alarms. Any airlock can now be made into a shell' by Watermelon914 at commit aa11c812e6](https://www.github.com/tgstation/tgstation/pull/68632)

## Reproduction:
This seems to be happening to people that spawn in as security officers. An easier way to reproduce this is to right click yourself as a ghost -> select equipment -> security officer. When you take your helmet off you will notice that you are now bald. It also happens with loadouts that start with a modsuit equipped

**Comment by Mooshimi** [comment]
Not just spawning, it will take the hair off if you wear a modsuit for a bit. Consider this merged with this issue https://github.com/tgstation/tgstation/issues/68863
