### ISSUE TITLE
There are no minimum hour requirements for Quartermaster

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#68810]
Reporting client version: 514.1583

## Round ID:
[187391](https://scrubby.melonmesa.com/round/187391)

## Testmerges:
- [Adds the Mothroach](https://www.github.com/tgstation/tgstation/pull/68763)
- [Revamped Away Mission: Caves (needs testing)](https://www.github.com/tgstation/tgstation/pull/68686)
- [Refactors SM Delaminations to be strategies](https://www.github.com/tgstation/tgstation/pull/68599)
- [Drastically improved the USB connection for air alarms. Any airlock can now be made into a shell](https://www.github.com/tgstation/tgstation/pull/68632)

## Reproduction:
Encountered a player with 1 hour of playtime joining as an intern quartermaster. As they are now considered a head of staff, this seems like an oversight to let brand new players join as it.

**Comment by Jolly-66** [comment]
Wouldn't a key holder need to also update this on the boxes too?
I'm not sure how TG handles EXP requirements for jobs, but the default (180min) isn't the same as what we use on live, assuming QM is to have the 40hr pre-req, or whatever the hour pre-req is.

**Comment by ANAME593** [comment]
doesn't matter anymore the orange man has spoken

**Comment by SuperNovaa41** [comment]
Intended
