### ISSUE TITLE
Sometimes you spawn BALD when you have hair in your character setup

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#68828]
## Round ID:
 [187407](https://scrubby.melonmesa.com/round/187407)
  187402

## Testmerges:

https://github.com/tgstation/tgstation/pull/68599

##what happened?:
I played as maia roentgen in these rounds and spawned without any hair as opposed to the bedhead floorlength hair my character always has. When attempted to fix it in a mirror I had to select a non floorlength bedhead style, then select floor length bedhead.

**Comment by Mooshimi** [comment]
This says you spawned as a sec officer, so the issue is better described by https://github.com/tgstation/tgstation/issues/68863
