### ISSUE TITLE
Emitters 'firing 1 beam every X seconds' text tracks the time until the next beam, instead of an average

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#68820]
## Round ID:
found locally while getting screenshots

## Testmerges:

irrelevant

## Reproduction:

> examine emitter
see it will fire **EVERY** X seconds
watch it fire
examine it again
realize that the 'firing 1 beam **EVERY** X seconds' text changes

Screenshots
same emitter before and after firing
![image](https://user-images.githubusercontent.com/54422837/181387417-68450595-8b4e-46cd-9b57-8d7607a2bcb9.png)
t1 parts
![image](https://user-images.githubusercontent.com/54422837/181387447-504e764d-c189-4c05-913c-f9b249fbf2e9.png)

**Comment by CoffeeDragon16** [comment]
The firing delay is random between two max and min values, not sure how it would be possible to go about including the text without making the firing delay static

**Comment by private-tristan** [comment]
have it display the minimum and maximum values for the emitter, and the time before the next shot?
