### ISSUE TITLE
Dragging a storage to your person to open it will try to mass trasfer into you

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#68824]
## Reproduction:

- Try to open a storage the old fashion way (drag it to your sprite)
- It ties to dump all of its contents "Into you"

**Comment by ZeroMODE0** [comment]
This also happens a lot when trying to dump bags into other bags- it dumps it, onto the floor, with the do after progress bar on top of the bag

You know, instead of just putting the items into the bag
