### ISSUE TITLE
Default stacking machines don't work

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#68839]
## Testmerges:
[#68739: 'Cursed heart revamp.' by orthography at commit 0ec943549b](https://www.github.com/tgstation/tgstation/pull/68739)
[#68630: 'Revolution victories now call the shuttle when enough of the station is revolutionaries' by Mothblocks at commit c001c14cf6](https://www.github.com/tgstation/tgstation/pull/68630)
[#68592: 'Replaces the mood component with a mood datum' by SuperNovaa41 at commit e1cd1d0a02](https://www.github.com/tgstation/tgstation/pull/68592)

## Reproduction:
throw a stack of materials into the conveyor right in front of the stacker or before it. (Delta, unsure if other maps are same)
watch in awe as it does nothing.

**Comment by TheVekter** [comment]
This appears to be fixed.
