### ISSUE TITLE
Modafinil OD Issue

### ISSUE THREAD

**Issue by Helvetica8563** [tgstation/tgstation#68859]
Round ID: [69](https://scrubby.melonmesa.com/round/69) nice

this bug happens with the modafinil od quirk that puts you in a infinite sleep until its out of your system the drug gets rid of the sleepiness as it gets metabolised even while your asleep and its been well over the 82 cycles required for it does not send you to sleep even though the icon for being asleep is active as the drug heals dizziness, drowsyness and sleep

you can replicate this by taking a 50u pill of modafinil and waiting 82 cycles you can still move and do everything even while asleep
this issue was found on AU station which is NOT an official server just uses tg code

**Comment by private-tristan** [comment]
I guess it's because modafinil stops you from normally sleeping, but the effect isn't removed when you begin ODing so it does nothing?

**Comment by Helvetica8563** [comment]
> I guess it's because modafinil stops you from normally sleeping, but the effect isn't removed when you begin ODing so it does nothing?

Yes
