### ISSUE TITLE
going bald after wearing a head-covering item

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#68863]
## Testmerges:
[#68763: 'Adds the Mothroach' by Justice12354 at commit 95aa66d6e5](https://www.github.com/tgstation/tgstation/pull/68763)
[#68855: 'fixes nuke ops leaders not spawning' by Fikou at commit ad7cbde3be](https://www.github.com/tgstation/tgstation/pull/68855)
[#68739: 'Cursed heart revamp.' by orthography at commit 6569acc4f1](https://www.github.com/tgstation/tgstation/pull/68739)
[#68630: 'Revolution victories now call the shuttle when enough of the station is revolutionaries' by Mothblocks at commit c001c14cf6](https://www.github.com/tgstation/tgstation/pull/68630)

## Reproduction:

1. Wear a head-covering item like a sec helmet or a full modsuit.
2. Remove after a minute.
3. You are now bald.

My hair returned after a while so I believe it's an issue with updating the hair sprite being hidden -> not hidden.

**Comment by Mooshimi** [comment]
possibly cause by this very recent change 
![image](https://user-images.githubusercontent.com/85910816/181861184-fd02adf6-bbd3-4239-9ca4-8d9fb1e1d9a9.png)

**Comment by Kapu1178** [comment]
If thats the problem that means people are using regenerate_icons() when they shouldnt be. Im not home else id git bisect the issue.

**Comment by Mooshimi** [comment]
posting for future reference:
![image](https://user-images.githubusercontent.com/85910816/181863034-71aec698-279e-40a3-a4ea-e58baac68dbf.png)

**Comment by timothymtorres** [comment]
Whatever is causing this is likely causing #68828 as well.  I suspect it's from #68580 since it was merged about a week ago.

**Comment by SinfulBliss** [comment]
This happens to me whenever I spawn as a roundstart security officer.
