### ISSUE TITLE
enclosed solar panels?

### ISSUE THREAD

**Issue by daplanman12** [tgstation/tgstation#68862]
## Round ID:

[Round ID]: # 187525

## Reproduction:

![image](https://user-images.githubusercontent.com/20193128/181843896-6c3af72a-1233-4daf-bc5f-eba12f10fb0c.png)

Self-explanatory. SOlar panels work inside rooms.

**Comment by private-tristan** [comment]
do they generate power? i'd assume not because they have no sightline to the sun?

**Comment by daplanman12** [comment]
Yes. Full power.

**Comment by Kitfox88** [comment]
STATION HAS NO ROOF CONFIRMED

**Comment by JohnFulpWillard** [comment]
I can't replicate this, ``sunfrac`` gets set to 0 if it has an opaque turf which causes it to not make any power
![image](https://github.com/tgstation/tgstation/assets/53777086/bf7589ef-a33d-40ec-b76a-758aa22d3191)
![image](https://github.com/tgstation/tgstation/assets/53777086/9d8082fa-549d-4af3-b685-dc8c72d6a075)
