### ISSUE TITLE
Optical meson scanners can see items through walls

### ISSUE THREAD

**Issue by CoastalCookie** [tgstation/tgstation#68874]
Reporting client version: 514.1585

## Round ID:
[187558](https://scrubby.melonmesa.com/round/187558)

## Testmerges:
- [Adds the Mothroach](https://www.github.com/tgstation/tgstation/pull/68763)
- [Refactors SM Delaminations to be strategies](https://www.github.com/tgstation/tgstation/pull/68599)
- [fixes nuke ops leaders not spawning](https://www.github.com/tgstation/tgstation/pull/68855)

## Reproduction:

Wear the optical meson scanners stand behind a wall and another person infront of the wall and have that person pull out items from their backpack etc the animation will be visible for the user with the meson scanners

(i am not a admin did a admin modify anything. meaning this was in a normal round of ss13)

**Comment by CoastalCookie** [comment]
Details how i discovered this bug:

i discovered this bug in the middle of a round when a heretic was sacrificing someone as he ran into maints i saw random items popping up in a room (which i couldn't see in) i suddenly see items popping up in the halways which clearly identifies he was going to go the other way so this could be really power full as you can see what enemies have equipped if you think about it (unless the item equipped doesn't play a animation)

**Comment by private-tristan** [comment]
#39799

**Comment by CoastalCookie** [comment]
Ah you already reported that well then (i couldn't find it at all)

**Comment by Mooshimi** [comment]
Note: You can see this without meson it's just easier to see with lightened surroundings I'm fairly sure.

**Comment by Mooshimi** [comment]
> #39799
