### ISSUE TITLE
Leaving anomolous crystal posession just gibs you

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#68881]
## Reproduction:

Use the critter posession crystal next to Ian, then press the "leave possesion" HUD icon. Congratulation you're now gibbed

This actually sucked since I was in the most perfect opportunity to assasinate the unsuspecting HoP, but I just ended up covering him in my gibs 
![image](https://user-images.githubusercontent.com/7501474/181975713-d696e7b3-d7d1-4ea9-b99e-72325b812e28.png)

**Comment by Mooshimi** [comment]
Did your body disappear when you possessed Ian as if you would regain it when you left Ian or was it left behind?

**Comment by Time-Green** [comment]
My body disappeared (put in Ian) during posession. When unposessing my body was deleted during the gibbing of Ian

**Comment by Sealed101** [comment]
ugh... it's a overly complicated mess

https://github.com/tgstation/tgstation/blob/2e240d0e9d0744238bf9ef639ca9bf0a8942364f/code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm#L541-L606

- it shoves you into a locker, then into the animal
- when you exit the possession it gibs the animal
- it tries to `dump_contents()` when gibbing the animal but fails anyway, probably related to #73657
- it doesn't allow possession of basic mobs (grave sin); if no `simple_animal` mobs are found, it spawns a cockroach. which is a basic mob.
