### ISSUE TITLE
Teleporting AI Via Holopads

### ISSUE THREAD

**Issue by LucyGrind** [tgstation/tgstation#68898]
## Round ID:
[187650](https://scrubby.melonmesa.com/round/187650)
## Reproduction:
step 1: wrench holopad so its draggable 
step 2: have ai connect to holopad
step 3: drag the holopad, the ai should now teleport to the holopads location.

**Comment by scriptis** [comment]
This appears to work on all mobs, not just AI cores.

**Comment by Mooshimi** [comment]
Please consider this issue merged with #68746
