### ISSUE TITLE
Screwdriver/Hand Drill cannot secure grilles

### ISSUE THREAD

**Issue by TerraGS** [tgstation/tgstation#68897]
![tgdrillbug](https://user-images.githubusercontent.com/40574831/182041018-96693ae4-39bb-4552-bd1e-2454ffdba014.png)

## Round ID:
[187648](https://scrubby.melonmesa.com/round/187648), 187649
Sybil

## Reproduction:
Action: Attempt to use a screwdriver tool on an unfastened grille.
Result: Player performs default attack on grille with tool.
Expected: Player should perform screw action on grille.

**Comment by Mooshimi** [comment]
screwdrivers actually can't do this either I think, currently

**Comment by TerraGS** [comment]
> screwdrivers actually can't do this either I think, currently

Thought I'd checked this but you are correct. Updated post accordingly.
