### ISSUE TITLE
Getting Brain Trama Event On Lowpop

### ISSUE THREAD

**Issue by Helvetica8563** [tgstation/tgstation#68907]
should make it so you need at least 5 people to get the brain trauma event because you cannot always seek surgery and some traumas make it so that you cant make neurine and it is especially bad when you are solo on a station and you get a random deep rooted brain trauma i understand it is meant to make the round end sooner but thats not always what the one guy on tg basil at three in the mourning testing shit may want because it forces you to call the shuttle

**Comment by SuperNovaa41** [comment]
Feature request
