### ISSUE TITLE
Shades have easily ommitable information about being slaved to someone

### ISSUE THREAD

**Issue by Miczu555PL** [tgstation/tgstation#68918]
## Testmerges:
#68763: 'Adds the Mothroach' by Justice12354 at commit 2265106aba
#68599: 'Refactors SM Delaminations to be strategies' by vincentiusvin at commit 606d9b0fbb
#67902: 'Lemon does pain' by LemonInTheDark at commit faa2958c50

## Reproduction:

Get killed then look away from your screen or be otherwise distracted. Look back that you are now spectating (most likely) a chaplain, without ghost HUD.

The information about what you can/can't do (attack your master) is written in **bold standard size text** that could be easily lost in chat spam, **especially** when the (most likely) dead-player-now-shade is not looking at the game.

![image](https://user-images.githubusercontent.com/32741399/182226929-91583cf7-0342-44e2-8c58-8110cce90b63.png)

Getting slaved to someone is pretty important information that shouldn't get easily omitted.
Especially important for anyone getting sharded first time by chaplain. (Pretty sure cult shades get the antag info popup.)

**Comment by Miczu555PL** [comment]
a QoL?
Admin was more understanding.
*sob

**Comment by dragomagol** [comment]
Strictly speaking it's not a bug, and I wasn't sure what else to call it

**Comment by Miczu555PL** [comment]
It's important. An exaple was me getting **BWOINK** because it was my first time being randomly shaded by chaplain.
So I couldn't really tell if I can bash his head in for this. And the only thing that is telling me that is _this small text_ that **really** should be bigger.

**Comment by dragomagol** [comment]
Ya, I agree it's something that needs fixing
