### ISSUE TITLE
Statues of carbon/humans do not complete properly

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#68922]
Reporting client version: 514.1585

## Round ID:
[187720](https://scrubby.melonmesa.com/round/187720)

## Testmerges:
- [Adds the Mothroach](https://www.github.com/tgstation/tgstation/pull/68763)
- [Refactors SM Delaminations to be strategies](https://www.github.com/tgstation/tgstation/pull/68599)
- [Lemon does pain](https://www.github.com/tgstation/tgstation/pull/67902)

## Reproduction:

My money's on #67902 (nice description summary that goes into the report issue list of possible culprit TMs :P)

Statues of player mobs do not complete properly ; they animate the carving however upon completion the statue section is rendered invisible leaving just the base behind

In extended testing it appears to be subtypes of carbon/human that are affected, e.g. carbon/xeno statues properly but carbon/human, carbon/human/moth, abductor, do not complete properly.

Looking good...
![image](https://user-images.githubusercontent.com/3789327/182248046-3711e88c-fa5c-4822-92ab-d2a738dbfcf9.png)

Aww shucks...
![image](https://user-images.githubusercontent.com/3789327/182248104-4a5fb459-f00d-4efc-9474-2537dc7f53e8.png)

**Comment by Mooshimi** [comment]
Please post in https://github.com/tgstation/tgstation/pull/67902

**Comment by LemonInTheDark** [comment]
Handled
