### ISSUE TITLE
Supply pod menu has icon issues

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#68923]
Reporting client version: 514.1585

## Round ID:
[187720](https://scrubby.melonmesa.com/round/187720)

## Testmerges:
- [Adds the Mothroach](https://www.github.com/tgstation/tgstation/pull/68763)
- [Refactors SM Delaminations to be strategies](https://www.github.com/tgstation/tgstation/pull/68599)
- [Lemon does pain](https://www.github.com/tgstation/tgstation/pull/67902)

## Reproduction:

Probably #67902  ?

The icons are all messed up and the view area of the pod bay etc is completely broken (rather than its usual 'kinda quirky' existence)

Lemon Edit: The viewport is my fault, and a TM bug. The icons however, are broken on master

![image](https://user-images.githubusercontent.com/3789327/182251667-16a8f096-71be-481c-8656-76029461996a.png)

**Comment by Mooshimi** [comment]
Please post this on https://github.com/tgstation/tgstation/pull/67902

**Comment by LemonInTheDark** [comment]
The pod window not showing is my fault (and solved now, but the icons being weird is on master, and thus an actual issue

**Comment by Mooshimi** [comment]
Game consoles also have ghost boxes around the head icons

**Comment by LemonInTheDark** [comment]
why was this closed @iprice

**Comment by iprice** [comment]
> why was this closed @iprice

Seems to have been (at least the issue i was reporting) silent fixed at some point.  I'll make sure I clarify that if I close any of my old issues in future.
![image](https://github.com/tgstation/tgstation/assets/3789327/86b3d815-6447-4223-bf33-955d2b551dd4)

**Comment by LemonInTheDark** [comment]
huhhhhhhhhhhhhhhh
For the record I think the grey background has something to do with the first sprite that is inserted in a sheet, though I'm really not sure why. Needs more investigation smells of a byond bug
