### ISSUE TITLE
Traitors can spam-buy the grid check event, resulting in spam.

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#68932]
Reporting client version: 514.1585

## Round ID:
[187755](https://scrubby.melonmesa.com/round/187755)

## Testmerges:
- [Adds the Mothroach](https://www.github.com/tgstation/tgstation/pull/68763)
- [Refactors SM Delaminations to be strategies](https://www.github.com/tgstation/tgstation/pull/68599)
- [Lemon does pain](https://www.github.com/tgstation/tgstation/pull/67902)

## Reproduction:
1. Be traitor
2. Begin spam-clicking the button to buy a blackout
3. 
![image](https://user-images.githubusercontent.com/80979251/182367640-d0e96cb2-9676-40e2-8e9a-b28e2a650a80.png)
4. what the fuck

**Comment by Mooshimi** [comment]
This also applies to DUMP-eets which will then hellishly spam from your ID, but the above seems like moreso it's wasting TC
