### ISSUE TITLE
General Issue Dump - Kilostation Whiteship

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#68939]
# Foreword

This isn't exactly an issue, more some minor gripes with the new Kilo Station whiteship.
Read on.

# MINOR ISSUES
Only 1 EVA suit
No robot arm for cleanbot
No donks
Crew quarters eating room seperate APC (just use both bar and crew quarters area so that ghosts have more teleport options to increase information hell)

# MEDIUM ISSUES
SMES not hooked up to ship powernet
SMES starts empty
No wrench to secure PACMAN

no major issues
ok bye

**Comment by Addust** [comment]
i cant format sorry

**Comment by Mooshimi** [comment]
> i cant format sorry

two # before the line makes it look like a category like i think you want

**Comment by Mooshimi** [comment]
Also I think the robo arm and smes are oversights

**Comment by san7890** [comment]
@Capsandi

**Comment by rageguy505** [comment]
Just looking into it it seems like most of these concerns were resolved.
it has a toolbox, the SMES starts with power, the SMES is connected to the shuttles wire grid. It has donk pockets. Yhe 1 eva suit/no borg arm to make the cleanbot just seems like it was intentionally mapped.

**Comment by Addust** [comment]
yea should probably mark this is as resolved, the 1 EVA suit was intentional IIRC
