### ISSUE TITLE
Heretic Stalkers' shapeshift spell is unusable and has no name, description, or icon

### ISSUE THREAD

**Issue by VioletN** [tgstation/tgstation#68941]
## Reproduction:

1. Spawn Stalker mob.
2. Assume control of the Stalker.

![](https://cdn.discordapp.com/attachments/982852284205654046/1004115094436851802/stalker_spell.png)

The spell can't be used because it doesn't have spell_requirements = NONE.  However, a broader problem is that even when this is fixed (as I have attempted), upon transformation, the transformed mob does not have the spell anymore, meaning that they will be unable to change back into their Stalker form, rendering the spell essentially useless your evil plan involves permanently turning into a mouse.

**Comment by Mooshimi** [comment]
This is the same appearance of the spider "Lay Egg" and "Lay the upgraded purple egg" I saw yesterday

**Comment by Mooshimi** [comment]
Related: #68933
