### ISSUE TITLE
Narcolepsy seems active even when neutered in a virus

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#68944]
Reporting client version: 514.1585

## Round ID:
[187796](https://scrubby.melonmesa.com/round/187796)

## Testmerges:
- [Adds the Mothroach](https://www.github.com/tgstation/tgstation/pull/68763)
- [Refactors SM Delaminations to be strategies](https://www.github.com/tgstation/tgstation/pull/68599)
- [Lemon does pain](https://www.github.com/tgstation/tgstation/pull/67902)

## Reproduction:

This reproduction done in round 187796, however was seen originally in 187792 where we suffered this in a virus until we figured out we just needed to cure it despite the virus trait being neutered.

Tried this with other traits neutered (spontaneous combustion and polyviltigo) but it only seems to happen on narcolepsy
1) Take the default flu virion culture
2) Mutate it until you get narcolepsy
3) Neuter the narcolepsy
4) Feed it to a victim

![image](https://user-images.githubusercontent.com/3789327/182499243-faf35d32-d7f3-41c2-af09-c5f414f2ba50.png)

```
ADMIN LOG: [Iain0] has put Iain0 in control of Seth Scherer.
You feel very sleepy.
Seth Scherer analyzes Seth Scherer's vitals.
Analyzing results for Seth Scherer:
Overall status: 100% healthy
Genetic Stability: 100%.
Species: Human
Core temperature: 30.1 °C (86.2 °F)
Body temperature: 29.1 °C (84.4 °F)
Warning: Advanced Disease detected
Name: Cough + Narco Neutered.
Type: Blood.
Stage: 5/5.
Possible Cure: Copper
Blood level: 100 %, 560 cl, type: O+

So tired...
x2

... You can almost hear something ...
x2

You feel very sleepy.
x2

... You can almost hear something ...
You have a hard time keeping your eyes open.
You have a hard time keeping your eyes open.
```

etc etc

![image](https://user-images.githubusercontent.com/3789327/182499425-6ec43959-8b50-47f1-b7a3-d3b8750d1750.png)

**Comment by timothymtorres** [comment]
+1 for a very detailed and thorough bug report.  Relevant code:

https://github.com/tgstation/tgstation/blob/a2be43fbd0ce0c0988208f1748b4fe1f0ec01d3d/code/datums/diseases/advance/symptoms/narcolepsy.dm#L26-L70

https://github.com/tgstation/tgstation/blob/3702fa579351047801e4d21e55570cc01ce41be3/code/datums/diseases/advance/symptoms/symptoms.dm#L32-L70

https://github.com/tgstation/tgstation/blob/6ff4d03ee0cd8ed4e566f63064f49522c7a579c2/code/datums/diseases/advance/advance.dm#L107-L126

Disease code needs a refactor badly.
