### ISSUE TITLE
Camera saves you from Ice Storm

### ISSUE THREAD

**Issue by Diamond-74** [tgstation/tgstation#68952]

**Comment by newfren** [comment]
cameras have to be part of an area to be powered, and areas are used to protect from things like ice storms or ash storms. you can see the same thing on the lights on the outside of the clown ruin on lavaland

**Comment by Mooshimi** [comment]
Yeah it's mapping, don't think this is a but just an effect of wall items. Perhaps consistency and realism but I don't think they plan to mess with this

**Comment by LemonInTheDark** [comment]
it's a bug, even if we don't want to solve it this shouldn't be happening 
a non bug would be the existence of cameras because "THEY CAN SEE ME WHEN I'M TRAITORING" or such

**Comment by san7890** [comment]
Technically I caused this bug by mapping the cameras to be in an area but they wouldn't be powered, as newfren says above. I wish there was a way to work around this but since weather effects are area-based I'm not particularly sure how one might approach fixing this

**Comment by LemonInTheDark** [comment]
we could take camera/apc/light area from the wall they're connected to, rather then the tile they're on 
that'd solve this and the box meme
