### ISSUE TITLE
ordering a gas canister using a departmental ordering console will be openable from anywhere

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#68982]
## Round ID:

[187904](https://scrubby.melonmesa.com/round/187904)

## Testmerges:

[#68763: 'Adds the Mothroach' by Justice12354 at commit 55f95faa96](https://www.github.com/tgstation/tgstation/pull/68763)
[#68630: 'Revolution victories now call the shuttle when enough of the station is revolutionaries' by Mothblocks at commit c001c14cf6](https://www.github.com/tgstation/tgstation/pull/68630)

## Reproduction:

order a BZ/n2o/water vapor can using departmental ordering console
go to cargo
notice that the lock says it cannot be opened outside of engineering
apply crowbar while outside of engineering
get your free BZ/n2o/water vapor can

**Comment by newfren** [comment]
opening it will also fail to give cargo any money even when in the correct location
