### ISSUE TITLE
Box whiteship zombies don't spawn corpses

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#68981]
Reporting client version: 514.1585
# foreword

hey nerd this is an old problem
possibly older than modsuits

## Round ID:
[187894](https://scrubby.melonmesa.com/round/187894)

## Testmerges:
- [Adds the Mothroach](https://www.github.com/tgstation/tgstation/pull/68763)
- [Atmospheric Improvement: Fixing air is now faster and much easier](https://www.github.com/tgstation/tgstation/pull/68325)

## Reproduction:

1. kill box whiteship zombie
2. no corpse
3. aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by Fikou** [comment]
https://github.com/tgstation/tgstation/pull/68760 makes them spawn remains

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/e47dca56349584f77e702e9a1b4ec6bbe817d1ee/code/modules/mob/living/simple_animal/hostile/zombie.dm#L1-L48

Zombies are simple animals and thus don't spawn any corpse upon death.  This is the same pattern for other simple mobs like syndicate commandos.
