### ISSUE TITLE
Bags of holding wont accept a refined bluespace anomaly.

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#68991]
Reporting client version: 514.1584

## Round ID:
[187926](https://scrubby.melonmesa.com/round/187926)

## Testmerges:
- [Adds the Mothroach](https://www.github.com/tgstation/tgstation/pull/68763)
- [Revolution victories now call the shuttle when enough of the station is revolutionaries](https://www.github.com/tgstation/tgstation/pull/68630)

**Comment by dragomagol** [comment]
Did you try to use the crafting menu?

**Comment by Baskett55** [comment]
I didn't know you had to craft it, I asked 3 separate people for help.
