### ISSUE TITLE
Bubblegum sometimes does the hallucination attack twice

### ISSUE THREAD

**Issue by 1393F** [tgstation/tgstation#69008]
## Testmerges:
https://github.com/tgstation/tgstation/pull/68855

## Reproduction:
fight bubblegum till half health

watch as he SOMETIMES does the hallucination charge attack twice at the same time?
![Screenshot (247)](https://user-images.githubusercontent.com/59183821/183139712-c79ef4e0-031b-443e-ac07-322e7a2e431a.png)

**Comment by Mooshimi** [comment]
Marking as bug on the idea that this is not supposed to happen, which I don't know.

**Comment by rasepretep** [comment]
He does this every time he's doing the red enraged attack, all his sigil spawns are doubled like the screenshot shows, whether it be a charge or hallucination surround. Can't possibly be intended, seeing is it often leads into getting outright stuck if he surrounds you in a particularly unlucky way.

**Comment by 1393F** [comment]
this was fixed by https://github.com/tgstation/tgstation/pull/81082
