### ISSUE TITLE
Traitor eyesnatch still doesn't show up

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#69019]
## Round ID:

irrelevant

## Testmerges:

irrelevant

## Reproduction:

play through multiple progtot rounds
never see the eyesnatch objective
ask around in discord if anyone has seen it
no one has

**Comment by Mooshimi** [comment]
possible area of interest: https://vscode.dev/github/Mooshimi/tgstation/blob/4b0b64df6be6fa919b03741517245904c2e20aed/code/modules/antagonists/traitor/objectives/eyesnatching.dm#L48-L101

**Comment by Mooshimi** [comment]
Also: #67287 @SmArtKar
