### ISSUE TITLE
Changeling tentacle holds up the targets instead of stealing their items

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#69013]
## Round ID:
Different server

## Testmerges:

N/A

## Reproduction:

Activate your changeling tentacle, right click on someone. Instead of shooting out and stealing their active item, as described, it will instead initiate a hold up, slowly aiming at the target.

**Comment by ArcaneDefence** [comment]
we like guns that aren't guns

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/74418bad5494f05250d7dea37ff1e71923cfe81c/code/modules/projectiles/gun.dm#L208-L217

https://github.com/tgstation/tgstation/blob/2eccf3cea0a090302be8b110b77c7a9f728897f5/code/modules/antagonists/changeling/powers/mutations.dm#L367-L376

You just need to do:

```
/obj/item/gun/magic/tentacle/attack_secondary(mob/living/victim, mob/living/user, params) 
  // insert item steal code
```
