### ISSUE TITLE
Every time you scan an erroneous manifest with the export scanner, its value decreases more and more, until it reaches the deep negatives

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#69020]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/183228336-577a8f1b-2262-47f7-acfe-8ec1abcd320b.png)

![image](https://user-images.githubusercontent.com/51863163/183228333-aeed6bf8-101f-49ce-b7d5-714887c6705f.png)

**Comment by ATH1909** [comment]
nega-stonks
