### ISSUE TITLE
Beam sprite layer rotated

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#69021]
## Reproduction:
You can observe this any time you use a BRPED, as that beam does the same behavior as the below one.
![dreamseeker-22 59 57 967](https://user-images.githubusercontent.com/85910816/183230897-49c23f6a-76ed-4651-a54d-785e3248533a.gif)

**Comment by newfren** [comment]
https://github.com/tgstation/tgstation/issues/67336 ?

**Comment by Mooshimi** [comment]
> #67336 ?

so true
