### ISSUE TITLE
Can't reach backpack when inside a locker

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#69033]
Reporting client version: 514.1585

## Round ID:
[188030](https://scrubby.melonmesa.com/round/188030)

## Testmerges:
- [Prevents NAN amounts infecting the chemistry reagent container system](https://www.github.com/tgstation/tgstation/pull/69017)

## Reproduction:

stand inside locker
click backpack
![image](https://user-images.githubusercontent.com/6209658/183257487-d7ff1e5f-6fff-4d88-ba57-c15b803e662e.png)

**Comment by newfren** [comment]
wasn't this change intentional in https://github.com/tgstation/tgstation/pull/63955 ?
