### ISSUE TITLE
Organic slurry creation appears to be broken

### ISSUE THREAD

**Issue by capn-monkeypaw** [tgstation/tgstation#69046]
Both player and admin attempts to create organic slurry result the elimination of the component ingredients. 
To put it another way, everything in a reagent container goes poof once a dead mouse is added to the welding fuel.
This was observed during round 188039 on Sybil.

**Comment by newfren** [comment]
I believe the organic slurry is added to the mouse, which has to then be ground

**Comment by Shadowflame909** [comment]
yeah mouse is a sponge that you then grind up

**Comment by Time-Green** [comment]
> yeah mouse is a sponge that you then grind up

This does not work though, ran into it yesterday and forgot to make a bug report. It gives welding fuel, blood, mold, nutriment etc but no organic slurry

**Comment by CPTANT** [comment]
I am unable to reproduce this.

I did this:
Beaker of 50 welding fuel
dip dead mouse
wait until reaction sound
grind mouse
And I got organic slurry as expected

**Comment by Time-Green** [comment]
Should close this then. It might’ve been due to my mice becoming moldy
