### ISSUE TITLE
secbelts don't update sprites for the last item inserted

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#69052]
Reporting client version: 514.1585

## Round ID:
[188049](https://scrubby.melonmesa.com/round/188049)

## Testmerges:
- [Prevents NAN amounts infecting the chemistry reagent container system](https://www.github.com/tgstation/tgstation/pull/69017)
- [Unique ambience for virology!](https://www.github.com/tgstation/tgstation/pull/69031)

## Reproduction:
have sec belt
remove stun baton - baton icon gets removed
insert stun baton - icon doesn't change
remove stun grenade - grenade icon gets removed, baton icon appears
insert stun grenade - icon doesn't change

**Comment by newfren** [comment]
this is the case for toolbelts as well

https://github.com/tgstation/tgstation/issues/68430 is the previous issue that was marked as solved
