### ISSUE TITLE
You can hold players at gunpoint from any range

### ISSUE THREAD

**Issue by scriptis** [tgstation/tgstation#69065]
## Testmerges:

[#69017: 'Prevents NAN amounts infecting the chemistry reagent container system' by optimumtact at commit 0689fbd6d9](https://www.github.com/tgstation/tgstation/pull/69017)
[#69031: 'Unique ambience for virology!' by DrDiasyl at commit d3f8b762ed](https://www.github.com/tgstation/tgstation/pull/69031)
[#68739: 'Cursed heart revamp.' by orthography at commit 9552090246](https://www.github.com/tgstation/tgstation/pull/68739)

## Reproduction:

Get a laser gun. Hold somebody up by right-clicking them while they are 4+ tiles away. Laugh, as you will never, ever, miss again. Your shots always qualify as point-blank.

Seems to have been introduced by #68361.

**Comment by CursedBirb** [comment]
A lot of issues about gunpoints started to pop-up recently
