### ISSUE TITLE
Some pipe icons turn invisible and unclickable when placed/connected

### ISSUE THREAD

**Issue by TerraGS** [tgstation/tgstation#69063]
![image](https://user-images.githubusercontent.com/40574831/183308125-182b2db0-8d4e-4eb1-9e94-69b445fe16b3.png)
Reporting client version: 514.1585

## Round ID:
[188098](https://scrubby.melonmesa.com/round/188098)

## Testmerges:
- [Atmospheric Improvement: Fixing air is now faster and much easier](https://www.github.com/tgstation/tgstation/pull/68325)
- [Prevents NAN amounts infecting the chemistry reagent container system](https://www.github.com/tgstation/tgstation/pull/69017)

## Reproduction:
Placing/connecting pipes with blocked directions using RPD is the only method found to produce it so far. Unclear what determines visibility. Occurs above and below floor. Confirmed by right click display.

**Comment by newfren** [comment]
one way I've found to do it is putting down a pipe with a connection to the south and the west (and pipes on those tiles as well) then placing another pipe on the same tile of a different colour, with a new connection to the north but not the east. the pipe will appear again when a pipe is placed to the east

**Comment by timothymtorres** [comment]
Some pipes for mapping are visible or hidden, which determines whether a pipe can be sign above the floortile or you need the floor plating removed.
