### ISSUE TITLE
"the concept of cheese" has no sprite

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#69074]
## Testmerges:

[#69017: 'Prevents NAN amounts infecting the chemistry reagent container system' by optimumtact at commit 0689fbd6d9](https://www.github.com/tgstation/tgstation/pull/69017)
[#69031: 'Unique ambience for virology!' by DrDiasyl at commit d3f8b762ed](https://www.github.com/tgstation/tgstation/pull/69031)
[#68739: 'Cursed heart revamp.' by orthography at commit 9552090246](https://www.github.com/tgstation/tgstation/pull/68739)

## Reproduction:

![image](https://user-images.githubusercontent.com/85910816/183325208-8dde71a3-f099-4a33-8623-686643229e75.png)

**Comment by ArcaneDefence** [comment]
https://github.com/tgstation/tgstation/blob/3839bd4d751d5a4fc5b6e5d71de8f60e9130e875/code/game/objects/items/food/cheese.dm#L1
It's a parent class item that shouldn't be getting created in the first place

**Comment by ATH1909** [comment]
understand, understand, the CONCEPT of cheese- UNH

**Comment by Sealed101** [comment]
oh it's just xenobio silver slime produce, it can spawn /obj/item/food as well and it will be an error
