### ISSUE TITLE
Alien UI usability

### ISSUE THREAD

**Issue by paprka** [tgstation/tgstation#6907]
https://github.com/tgstation/-tg-station/pull/6398 introduced a 'cycle' system for the alien intents which is extremely annoying to use versus the 'click the intent you want to use' system. Consistency is nice but the usability is awful.

**Comment by optimumtact** [comment]
I thought this was a pref you could change to choose between the types?

**Comment by RemieRichards** [comment]
it is, for humans. Aliens just say no to this system at the moment and are always cycle mode.
