### ISSUE TITLE
Deep Storage Fire alarms are activating with no cause

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#69072]
Reporting client version: 514.1585

## Round ID:
[188111](https://scrubby.melonmesa.com/round/188111)

## Testmerges:
- [Prevents NAN amounts infecting the chemistry reagent container system](https://www.github.com/tgstation/tgstation/pull/69017)

## Reproduction:

Untouched deep storage air alarms are going off with no apparent cause without having been visited by any living thing.

**Comment by Mooshimi** [comment]
A mapper said this is due to someone not using directional firelocks or something

**Comment by timothymtorres** [comment]
Couple of questions:  

- Where is "Deep Storage" is that on a specific map or ruin?
- Why would directional firelocks have any effect on this?
- What did the atmos alarm in the area say?  (Low pressure, Toxic Gas, Temperature too high, etc.)

**Comment by Mooshimi** [comment]
> Why would directional firelocks have any effect on this?

No idea ask mappers

**Comment by Richie9999** [comment]
Don't check this often, deep storage is a space ruin. It's also known as the survivalist bunker if you use the jump to ruin command.

**Comment by RazorManager89** [comment]
Are the fire alarms going off inside the atmos area? In such case, it's probably due to the fact that the gas miners work only half the time. Sometimes the tanks are full of gas, sometimes they're not. The lack of gas sets off the alarms.
