### ISSUE TITLE
Some tgui icons are off-center

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#69087]
## Round ID:
[188165](https://scrubby.melonmesa.com/round/188165)

## Reproduction:
![image](https://user-images.githubusercontent.com/75639936/183515778-350f5379-b61a-46a0-ace5-7c3795331001.png)
now you cannot unsee it

**Comment by FlamingCheese** [comment]
![image](https://user-images.githubusercontent.com/75639936/183745626-c664696c-720b-4ba9-8491-06615b13d128.png)
![image](https://user-images.githubusercontent.com/75639936/183745673-a6fad8f7-7aee-4f8c-aae4-75acc7aef250.png)
another set of images with icon issues, some say the icons are off center but others say they are not.

**Comment by ShizCalev** [comment]
browser issue?
