### ISSUE TITLE
Banana peel's inhands are (still) slightly wrong

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#69089]
## Reproduction:

The right facing and left facing inhands for banana peels is the same no matter which hand the peel is in

![image](https://user-images.githubusercontent.com/51863163/183531560-9d57980c-0f6c-466c-b227-d70fe38439a5.png)

![image](https://user-images.githubusercontent.com/51863163/183531574-938cf83b-f770-4130-8ac5-9756256ffed5.png)

**Comment by CursedBirb** [comment]
Ah i know what i did wrong with my fix. I forget that bananas has side sprites too. Gotta pr it in second with no gbp
