### ISSUE TITLE
NTOS Error upon attempting to save chat logs

### ISSUE THREAD

**Issue by PCPort** [tgstation/tgstation#69097]
## Reproduction: Click the gear icon on the top right corner of the chat tab, and click "Save chat log" in the dropdown menu.

![uhoh](https://user-images.githubusercontent.com/62071287/183760351-c305eba4-ab60-415d-ba36-6d2734838972.png)

**Comment by Valtosin** [comment]
it happens because it tries to save object CSSKeyframesRule here:
https://github.com/tgstation/tgstation/blob/802c894fecd8b4f414df5c3d96afa6f98b8455a9/tgui/packages/tgui-panel/chat/renderer.js#L492-L501

can be fixed with typecheck like this:
```js
if (rule && typeof rule.cssText === 'string') {
  cssText += rule.cssText + '\n';
}
```
