### ISSUE TITLE
Temporal scars not saving upon successfully surviving a round.

### ISSUE THREAD

**Issue by rasepretep** [tgstation/tgstation#69093]
Gained three new scars, survived the round by taking an escape pod, next round they were gone and I was back to what I had at the start of the previous round. I suspect it's been going on for a while, since I've had about 4 for a long time despite having been through a few injuries over the past couple weeks.

Admittedly, I'm not entirely certain how temporal scars are gained and removed. Whether things like limb replacement or whole body transplant rewrite your slots with the body you end the round with, or if they are only saved when you're on the actual escape shuttle round-end (rather than just being marked as survived).

I understand that this is a hilariously insignificant cosmetic issue, but still pointing it out in case someone wants to take a look at it.

## Round ID:
[188165](https://tgstation13.org/parsed-logs/manuel/data/logs/2022/08/08/round-188165/)

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/3e006282e2c511c2c605b2dacf61a5f324e757d5/code/modules/mob/living/carbon/human/human_helpers.dm#L148-L194

https://github.com/tgstation/tgstation/blob/70faa854b47fe784bb863e78a5b3a68f8464ab54/code/controllers/subsystem/ticker.dm#L303-L310
