### ISSUE TITLE
the bench sprite has ascended

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#69111]
## Testmerges:
#68592 
#68630 
#68739

## Reproduction:

Someone made benches in maint and one in cargo, which you can still buckle to. 
![dreamseeker-21 24 07 673](https://user-images.githubusercontent.com/85910816/183848182-6ba55b01-8bf1-403f-a42a-2b6422712823.png)

**Comment by dragomagol** [comment]
Are you sure they're not just benches rotated weirdly?

**Comment by Mooshimi** [comment]
> Are you sure they're not just benches rotated weirdly?

If they are, wouldn't this still be a broken sprite? If you look its very fucked...

**Comment by Mooshimi** [comment]
are you supposed to be able to make multiple on the same tile???
