### ISSUE TITLE
Long-range analyzer does not display in science lathe tool designs

### ISSUE THREAD

**Issue by TerraGS** [tgstation/tgstation#69125]
Reporting client version: 514.1585

## Round ID:
[188280](https://scrubby.melonmesa.com/round/188280)

## Testmerges:
- [Check for compliant JSON before receiving payload](https://www.github.com/tgstation/tgstation/pull/69023)
- [Multiz Rework: Human Suffering Edition (Contains PLANE CUBE)](https://www.github.com/tgstation/tgstation/pull/69115)

## Reproduction:
Browsing tool designs in science lathe after unlocking experimental tools fails to display the long-range analyzer in the list, though others tools such as experimental welder appear. Only way to find it is using the search function.

**Comment by Mooshimi** [comment]
#68051
Looks like they missed an "s" on the "Tool Designs"
https://github.com/tgstation/tgstation/blob/92dc954ab5317b370e98dd070ad60ba8c3e8a6e9/code/modules/research/designs/tool_designs.dm#L37-L54
