### ISSUE TITLE
Using a wing potion as a moth drops your normal wings on the ground and gives you no new wings

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#69138]
## Round ID:
[188309](https://scrubby.melonmesa.com/round/188309)

## Reproduction:

- Be moth
- Drink wing potion
- Select wing type
- Suddenly your old wings are on the ground below you and you have no new wings
(I was wearing an EVA suit and took the top option if that matters)

**Comment by Time-Green** [comment]
The wing icon looked kinda sick though, right?

**Comment by Kitfox88** [comment]
heh, bug label

**Comment by Time-Green** [comment]
I can't reproduce this. Trying this as a moth with an EVA suit gives the wings. Did you try to remove your EVA suit or look at your HUD? 

Only thing standing out is that the old wings drop on the floor, which makes sense since the flight potion grows you new wings
![image](https://user-images.githubusercontent.com/7501474/184329494-983420b3-dc79-42f4-8a8a-c0b20511d9bd.png)
![image](https://user-images.githubusercontent.com/7501474/184329555-de5f942d-1b5c-445e-8494-d67beda072ac.png)

**Comment by Time-Green** [comment]
> I'll have to double check, but also:
> 
> Why are normal moth wings shown in EVA suits, but large moth wings hidden? Shouldn't they both either be hidden or shown?

Large moth wings are just resprited angel wings and are blocked visually and functionally by exosuits. Moth wings aren't for fetish reasons, I didn't even realise they were supposed to go over exosuits untill I got hogged by a thousand mothplayers when I accidentally removed it

**Comment by Time-Green** [comment]
> I'll have to double check, but also:
> 
> Why are normal moth wings shown in EVA suits, but large moth wings hidden? Shouldn't they both either be hidden or shown?

Large moth wings are just resprited angel wings and are blocked visually and functionally by exosuits. Moth wings aren't hidden for fetish reasons, I didn't even realise they were supposed to go over exosuits untill I got hogged by a thousand mothplayers when I accidentally removed it

**Comment by Mooshimi** [comment]
> > I'll have to double check, but also:
> > Why are normal moth wings shown in EVA suits, but large moth wings hidden? Shouldn't they both either be hidden or shown?
> 
> Large moth wings are just resprited angel wings and are blocked visually and functionally by exosuits. Moth wings aren't hidden for fetish reasons, I didn't even realise they were supposed to go over exosuits untill I got hogged by a thousand mothplayers when I accidentally removed it

Saying it's for a fetish is a pretty inappropriate assumption imo

**Comment by Mooshimi** [comment]
> I'll have to double check, but also:
> 
> Why are normal moth wings shown in EVA suits, but large moth wings hidden? Shouldn't they both either be hidden or shown?

Correct, they should both be one or the other for consistency

**Comment by Mooshimi** [comment]
cleanup tag isn't working
