### ISSUE TITLE
Inacusiate's claimed hearing boost doesn't work (also the reaction's pH is weird)

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#69133]
Reporting client version: 514.1585

## Round ID:
[188294](https://scrubby.melonmesa.com/round/188294)

## Testmerges:
- [Check for compliant JSON before receiving payload](https://www.github.com/tgstation/tgstation/pull/69023)
- [Multiz Rework: Human Suffering Edition (Contains PLANE CUBE)](https://www.github.com/tgstation/tgstation/pull/69115)

## Reproduction:

Find a friend, spawn in thunderdome, have one whisper words (more than 2-3 characters inputs) and have the other player measure the results at ranges
(My results)
1 tile (vertically/horizontally adjacent to): Clearly heard whisper
2 tiles: whispers with occasional masking by ***
3 tiles: nothing

Spawn-reagent-container some inacusiate in a pill.  Verify if desired that its reagents/inacusiate/purity is indeed 1 (100%).  Consume the pill.  Repeat above testing

Nothing is any different, same results.

Also if anyone fancies looking into it, the pH production of this recipe seems very very heavy relative to e.g. oculine.  The wiki also marks it as H+ producing (meaning the pH should drop?) but it's clearly coded with a very very heavy pH increase (of 15 pH per 10u reacted I seem to remember).  It strikes me this might be unintended.

**Comment by davethwave** [comment]
Did you test to see if it was referring to the total range of hearing instead? Could be referring to hearing things like gunshots further or casual conversation farther.

**Comment by kopoba** [comment]
> Did you test to see if it was referring to the total range of hearing instead? Could be referring to hearing things like gunshots further or casual conversation farther.

https://github.com/tgstation/tgstation/blob/85d6fad686fcd2f6633dd5fff5925e5473b16e5e/strings/chemistrytips.txt#L14

yeh is about whisper

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/a20d1a8d963df21e6e499395355fa79195cedd25/code/modules/reagents/chemistry/reagents/medicine_reagents.dm#L719-L742
