### ISSUE TITLE
Reagents: Table Salt inversion to Nutriment does not function

### ISSUE THREAD

**Issue by Muffindrake** [tgstation/tgstation#69140]
## Round ID:
[188322](https://scrubby.melonmesa.com/round/188322)

## Reproduction:
Attempt to produce Nutriment by inverting Table Salt, i.e. producing 0% purity table salt with 100 hydrogen, 5 sodium, 5 water, 5 chlorine. Watch in awe as it stays Table Salt.

![1660227728](https://user-images.githubusercontent.com/19580030/184157131-cee6967e-bb27-4b31-af0a-905d791151dd.png)

**Comment by ATH1909** [comment]
sad!

**Comment by Muffindrake** [comment]
In my limited knowledge of DM, I assume that `/datum/reagent/consumable/salt` inherits `inverse_chem` from `/datum/reagent/consumable`, which was `null`, and nutriment being a failed_chem rather than inverse_chem. There is currently no recipe for nutriment, so it's probably an unintended removal. Perhaps adding nutriment specifically to inverse_chem for salt works?

**Comment by Mooshimi** [comment]
I don't know if there is supposed to be a recipe for nutriment since it's simply a byproduct of food, it would be like adding a recipe for protein I think?

**Comment by Palpetinus** [comment]
> I don't know if there is supposed to be a recipe for nutriment since it's simply a byproduct of food, it would be like adding a recipe for protein I think?

I know this is getting a bit too balance discussion-y but if I can print 1000u of sugar, eat that and never see any difference in my character's body fat, we've already thrown food logic out the window.
A recipe for nutrients has this spacer feel to it where instead of eating a burger like a normal human being, you just eat shitty synthesized slop to get through the day

**Comment by Mooshimi** [comment]
> > I don't know if there is supposed to be a recipe for nutriment since it's simply a byproduct of food, it would be like adding a recipe for protein I think?
> 
> I know this is getting a bit too balance discussion-y but if I can print 1000u of sugar, eat that and never see any difference in my character's body fat, we've already thrown food logic out the window.
> A recipe for nutrients has this spacer feel to it where instead of eating a burger like a normal human being, you just eat shitty synthesized slop to get through the day

If you're not getting any change from 1000u sugar that's a problem. Over 50u is supposed to have an effect

**Comment by Time-Green** [comment]
@Mooshimi kill?

**Comment by Mooshimi** [comment]
> @Mooshimi kill?

Lemme ask, I've not gotten a response yet
