### ISSUE TITLE
Drones Phase Through Doors

### ISSUE THREAD

**Issue by RandomlyEvil** [tgstation/tgstation#69144]
Reporting client version: 514.1585

## Round ID:
[188342](https://scrubby.melonmesa.com/round/188342) (Tested again in 188343)

## Testmerges:
- [Check for compliant JSON before receiving payload](https://www.github.com/tgstation/tgstation/pull/69023)
- [Multiz Rework: Human Suffering Edition (Contains PLANE CUBE)](https://www.github.com/tgstation/tgstation/pull/69115)

## Reproduction:

Spawned in to derelict drone and noticed I was able to phase directly through all doors, including vault doors, with the one exception of Windoors.  Only windoors required opening to pass through.  Drone could walk through airlocks into space and cheese through vault doors to grab material (and of course hats).  Seems unintentional.
Admin also tested in round 188343 by spawning a drone on station and they were able to replicate the same behavior of the drone phasing right through a door as if it didn't exist.

**Comment by JoshAdamPowell** [comment]
I'm the admin that tested it in #188343 and it definitely just let me walk straight through airlocks

**Comment by RandomlyEvil** [comment]
Note:  Behavior is not reproducible on private server running TG code without current TMs.  Could be tested on Sybil to compare to the above mentioned behavior seen on Terry?

**Comment by JoshAdamPowell** [comment]
This is now no longer an issue on Terry. Which means the culprit is #69115

**Comment by LemonInTheDark** [comment]
what, how

**Comment by LemonInTheDark** [comment]
![image](https://user-images.githubusercontent.com/58055496/184451162-b5a67d4a-e319-4496-9fdf-0492f6b07b26.png)
.........
handled
