### ISSUE TITLE
Tram console being depowered doesn't prevent movement

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#69175]
Round ID: [188378](https://scrubby.melonmesa.com/round/188378)

Reproduction: Have the station be depowered until the tram console is depowered. Summoned the tram with a button.

Issue: When the station loses power, the tram console turns off which means it cannot be used as transportation anymore. However, it can still be called to departments by clicking the button, which means it becomes just a hazard without any use-case for transportation once the station power shuts down.

**Comment by lessthnthree** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/73057
