### ISSUE TITLE
Signing a question or exclamation `?`, `!`, then immediately signing un punctuated sentence will have the tonal indictor get stuck

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#69229]
## Reproduction:

- Sign a question or exclamation 
- Immediately sign something that is neither
- The tonal indicator is now stuck on you

![image](https://user-images.githubusercontent.com/51863163/184757055-28732e96-65f5-4d1f-bb0f-df7da1ece20e.png)

This happens because, 
if an un-punctuated sentence comes through while a tonal indicator is active: 
- `if(!isnull(tonal_indicator) && owner?.client.typing_indicators)` will fail
- `tonal_indicator` will be set to `null`
- The `remove_tonal_indicator` timer will early return when ran

**Comment by Wallemations** [comment]
Goddamnit I thought this was fixed

Also I got the side confused on where the ?. Needed to be oops

I'll see about fixing this, since it's my fault it's a problem in the first place and it's been annoying me as well Lmao
