### ISSUE TITLE
Photocopied forms don't retain text

### ISSUE THREAD

**Issue by BanementI** [tgstation/tgstation#69225]
## Round ID: 
[188580](https://scrubby.melonmesa.com/round/188580)

## Testmerges:

[#69023: 'Check for compliant JSON before receiving payload' by Mothblocks at commit 2ef735b5f8](https://www.github.com/tgstation/tgstation/pull/69023)

## Reproduction:

1. Make a form.
2. Photocopy it.
3. Enter something in the fields on the photocopied form.
4. Everything entered doesn't save.
5. Original form keeps what is written.

https://user-images.githubusercontent.com/47301693/184647457-a316fe10-f7bd-493c-9ff8-2efb98f97af4.mp4

I know literally nobody uses the photocopier except me.

**Comment by Sealed101** [comment]
seems to be fixed; https://github.com/tgstation/tgstation/pull/73633 or some other PR?
