### ISSUE TITLE
Tramstation Ordinance Lab is currently not setup correctly

### ISSUE THREAD

**Issue by Tupinambis** [tgstation/tgstation#69222]
## Reproduction:

The input injectors inside the ordinance lab are not on by default, and the igniter in the mix chamber is completely nonfunctional.

**Comment by RandomGamer123** [comment]
The injectors can be easily turned on with the monitoring console and also start off on some other maps, so that's not a bug.
The igniter in the burn chamber functions as expecting on testing, but is that the mix chamber you were referring to?

**Comment by Tupinambis** [comment]
> The injectors can be easily turned on with the monitoring console and also start off on some other maps, so that's not a bug. The igniter in the burn chamber functions as expecting on testing, but is that the mix chamber you were referring to?

oh I was not aware of this being a mechanic, but yeah I might have been thinking of the mix chamber.
