### ISSUE TITLE
lightgeists are unable to climb up ladders 

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#69228]
Reporting client version: 514.1585

## Round ID:
[188614](https://scrubby.melonmesa.com/round/188614)

## Testmerges:
- [Unique ambience for virology!](https://www.github.com/tgstation/tgstation/pull/69031)

## Reproduction:

>be a lightgeist
go down a ladder (right click)
attempt to go back up a ladder
nothing happens

I assume im attempting to heal the ladder and it fails instead of climbing up?

**Comment by timothymtorres** [comment]
Related to #57061

**Comment by Mooshimi** [comment]
can you move to the spot and hit the Move Up and Move Down verbs? I know that doesn't work for pais but lightgeists are flying aren't they?
