### ISSUE TITLE
TGUI Error (Recently Began as I Moved to College)

### ISSUE THREAD

**Issue by Tastes-of-Limelight** [tgstation/tgstation#69231]
There has been an Issue with the TGui Interface and Various tabs when attempting to play on TGstation,  Everything from Fancy chat to Character setup, to pAI menus.  Any solutions?
(It told me to send this to Github/tgstation/tgstation.)

Error: Access is denied.

   at isStyleSheetLoaded (http://127.0.0.1:50427/tmp3860/tgui-window-1.html:249:7)
   at node.onload (http://127.0.0.1:50427/tmp3860/tgui-window-1.html:343:9)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)

Nanotrasen (c) 2525-2562

**Comment by Tastes-of-Limelight** [comment]
I'm pretty much Brand New to Issues like this occurring, any help or attempts to help will be greatly appreciated.

**Comment by ShizCalev** [comment]
CDN issue?

#66541

**Comment by Tastes-of-Limelight** [comment]
I've attempted clearing the cache as recommended in https://github.com/tgstation/tgstation/issues/66541 But that didn't seem to fix the issue, I'll try to do a Bit more testing to see if I can recreate this issue or if I need to just let time sort out this affair.

**Comment by Tastes-of-Limelight** [comment]
![2022-08-16](https://user-images.githubusercontent.com/111244730/184956434-a6460364-a0ae-4ca9-8bc1-382e3daec15b.png)

**Comment by msgerbs** [comment]
Could the college be doing some web filtering that could affect the loading of tgui assets? What if you connect to a VPN of some kind (or even just a mobile hotspot), does that fix it?

**Comment by Tastes-of-Limelight** [comment]
Testing this theory

**Comment by Tastes-of-Limelight** [comment]
Initial Test Complete.  Mobile Hotspot has brought back the chat and the TGui, beginning further tests (although they may not be needed)

**Comment by Tastes-of-Limelight** [comment]
Seems like other tabs are working, it seems like it might be filtering contents, However the Hotspot has generally worse service here, I'll attempt to get a VPN that works since the last one was ineffective.

**Comment by Tastes-of-Limelight** [comment]
It seems that the school's Wi-Fi is blocking VPNs on my computer, any solutions for that?

**Comment by msgerbs** [comment]
The TG CDN is at http://tgstation13.download/byond/tgstation.zip so you could try going to that link in a browser and see if you get a block page that might tell you how you can request it be unblocked.

As far as a way to get your VPN to work if it's being blocked I'm not sure that's really appropriate for me to discuss here, but there are certainly resources on the internet that could help with that.

**Comment by msgerbs** [comment]
At this point it seems like this is not a code issue so I am closing the issue. I suggest [joining the Discord](https://discord.com/invite/VW9ZEwc) and asking in #help under the Official Bizzness category for further assistance.
