### ISSUE TITLE
Meta Grav Gen has two Air Alarms (one of which is outside)

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#69239]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
> Atmos Alarm Grav Gen
> ... Oh its just the room in front of it

![Screenshot_1](https://user-images.githubusercontent.com/95751821/184811188-b8a7e56f-4de3-4d27-9ba8-890fa0e959ea.png)

**Comment by ShizCalev** [comment]
does the room outside not deserve an air alarm?

**Comment by Ryusenshu** [comment]
They both are called Grav Gen

Also this place likes to get cold/lose air , because the solars and an airlock are to the right of it
That can trigger the alarm quite a bit

**Comment by ShizCalev** [comment]
think a better fix than removing it is adding scrubbers n a vent tbh
