### ISSUE TITLE
Sulfuric acid, fluorosulfuric acid, and nitric acid do not deal damage properly when injected

### ISSUE THREAD

**Issue by wulfenbach-jpg** [tgstation/tgstation#69243]
## Reproduction:

1. Fill a syringe with 5u Sulfuric Acid, 5u Fluorosulfuric Acid, and 5u Nitric Acid
2. Inject human with syringe.
3. Expected result is for brute and burn damage to be dealt, as intended in toxin_reagents.dm
4. All 3 acids in the syringe only do 5 burn damage and 48 toxin damage, with 0 brute damage being dealt.
Moreover, a syringe filled with 15u sulfuric acid does 0 brute damage. However, the brute/burn damage is dealt when the acids are splashed onto the target.

**Comment by antropod** [comment]
I blame #69035

**Comment by TemporalOroboros** [comment]
I wouldn't be surprised if the code is referring to the reagents from the original container. In that case the volume would be getting set to zero because they are used up in the transfer.
