### ISSUE TITLE
Bileworm track range is infinite

### ISSUE THREAD

**Issue by captainfrost20** [tgstation/tgstation#69244]
Reporting client version: 514.1585

## Round ID:
[188659](https://scrubby.melonmesa.com/round/188659)

## Testmerges:
- [Check for compliant JSON before receiving payload](https://www.github.com/tgstation/tgstation/pull/69023)
- [Fixes storage mass transfer being generally broken, adds mass transferring onto griddles ](https://www.github.com/tgstation/tgstation/pull/69084)
- [Buffs Heretic Curses, Living Heart, Leeching Walk, and technically Entropic Plume by fixing some bugs](https://www.github.com/tgstation/tgstation/pull/69181)

## Reproduction:
I aggroed 2 bileworms up by the top eastern part of lava land and Hiero clubbed back to base. They proceeded to follow me all the way there and wreck the base. Its kind of a massive issue to add a mob that just doesnt deaggro

**Comment by rasepretep** [comment]
They follow you across z-layers too. Had a moment where I aggroed a bilework and jaunted to the station on Kilo. It just so happened I landed at a spot where there was sand nearby. Bileworms only stop pursuit if there is no place to burrow near you and in this case, there was. So it got all the way to the station.

**Comment by timothymtorres** [comment]
Related to: #64677, #64063

> I believe this is intended behavior, if a megafauna BEGINS a tracking attack (think bubblegum charges, ash drake swoops) it'll autolock onto you no matter where you end up. If this isn't intended, it's been in for quite a while

**Comment by captainfrost20** [comment]
> They follow you across z-layers too. Had a moment where I aggroed a bileworm and jaunted to the station on Kilo. It just so happened I landed at a spot where there was sand nearby. Bileworms only stop pursuit if there is no place to burrow near you and in this case, there was. So it got all the way to the station.

Bruh

**Comment by Tupinambis** [comment]
You should be able to escape any standard lavaland mob by running away regardless, so yeah there needs to be a deaggro range. It's incredibly annoying to deal with especially when you just barely brush past their aggro range.

**Comment by Time-Green** [comment]
@tralezab
