### ISSUE TITLE
Welding hard hat missing worn sprite

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#69257]
## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/185017524-a6b5ab00-c093-4a44-bf95-2581f80dbc97.png)

**Comment by necromanceranne** [comment]
Probably lost in some dmi reshuffles.

**Comment by dragomagol** [comment]
![image](https://user-images.githubusercontent.com/66640614/209274254-9cb342f4-8ab3-4770-bb68-cb1045ec3f92.png)

![image](https://user-images.githubusercontent.com/66640614/209274261-4c3226d5-aa9a-499d-9669-7b908d2c8b26.png)

Appears to have been fixed
