### ISSUE TITLE
Bar Bots can grab you through directional windows

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#69254]
RoundID 188681

step 1: anger the bar bot
step 2: attempt to hide behind a thin wall of glass
step 3: the bar bot can phase through the window to crush your bones

![image](https://user-images.githubusercontent.com/105343481/185009365-df964d15-dd07-4432-845d-d6c572bb5349.png)

![image](https://user-images.githubusercontent.com/105343481/185009386-33dfd686-cab9-47be-b4f2-17f278f348b9.png)

**Comment by timothymtorres** [comment]
Related to #69110 and #66983
