### ISSUE TITLE
Unwrapping an Easter rabbit egg with telekinesis teleporst the reward to you

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#69258]
## Reproduction:

- Use Telekinesis to grab a toy egg and pop it open
- The toy appears under your feet 

TK is a blight

**Comment by timothymtorres** [comment]
Related to #68438

**Comment by Mooshimi** [comment]
> Related to #68438

Same behaviour, can we make one issue that says when something is activated inhand the effect is activates where the person is
