### ISSUE TITLE
Papercode lags

### ISSUE THREAD

**Issue by twilightwanderer** [tgstation/tgstation#69261]
## Reproduction:

In the implementation of the current [Papercodes](https://github.com/tgstation/tgstation/pull/68612), there are FPS sags and lags when entering characters into the format string and into the input lines. By talking to people I found that such cases are massive. Perhaps the problem lies in the rendering or zanitize call every time you enter a new character.

**Comment by LemonInTheDark** [comment]
@Timberpoes ????

**Comment by twilightwanderer** [comment]
Papers in general work quite strangely and unpredictably. For example, they often do not save the entered data in the input fields. I'm trying to poll people and collect data about what works wrong.
