### ISSUE TITLE
lathes have 2 sections for stock parts and none for equipment

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#69264]
Reporting client version: 514.1585

## Round ID:
[188714](https://scrubby.melonmesa.com/round/188714)

## Testmerges:
- [Buffs Heretic Curses, Living Heart, Leeching Walk, and technically Entropic Plume by fixing some bugs](https://www.github.com/tgstation/tgstation/pull/69181)
- [Fixes storage mass transfer being generally broken, adds mass transferring onto griddles ](https://www.github.com/tgstation/tgstation/pull/69084)
- [Check for compliant JSON before receiving payload](https://www.github.com/tgstation/tgstation/pull/69023)
- [Kills `/obj/shapeshift_holder`, replaces it with `/datum/status_effect/shapechange_mob`, also does a lot of Wabbajack refactoring](https://www.github.com/tgstation/tgstation/pull/69091)

## Reproduction:
![image](https://user-images.githubusercontent.com/12635164/185127662-a6658909-9fb4-4140-b6e0-5c020c2b9f17.png)
the stock parts on the left third from the top should be equipment. this isn't a cosmetic change, you can't get to the equipment section (although you can print stuff that lives there if you search for it)

**Comment by antropod** [comment]
#69161

https://github.com/tgstation/tgstation/blob/b9e6ca0a2cd3cb6d065e5b5939d8f4696cc56c60/code/modules/research/machinery/protolathe.dm#L10-L11

**Comment by timothymtorres** [comment]
Good work!  Threw up a quick PR to fix it.
