### ISSUE TITLE
Brim Demons can walk into their own beam and damage themselves

### ISSUE THREAD

**Issue by Jolly-66** [tgstation/tgstation#69275]
## Round ID:
Tested locally.

## Reproduction:
Take control of a brim demon, 
Walk forward after charging and attacking,
Regret taking that devil deal.

**Comment by timothymtorres** [comment]
CC @Fikou

**Comment by Mooshimi** [comment]
also, skill issue...

**Comment by Mooshimi** [comment]
Unable to reproduce, you're unable to move after firing
