### ISSUE TITLE
Blob invincible to TTV's

### ISSUE THREAD

**Issue by JohnKiwols** [tgstation/tgstation#69280]
## Reproduction:

1) Make a trit-oxy hot-plasma max-cap.
2) Explode it two tiles from a green blob's brain.
3) Cry because it took zero damage.
4) Have a genuinely nice chit chat with the blob in dead chat when the crew finally kills it.

Edit: I know using ttv's on blobs is extremely frowned on, but it spawned inside ordnance testing when i finished the mix, and it's brain was right next to space.  Normally I wouldn't even consider using a ttv for this (even if i had a nice batch).  It has occurred to me that this invulnerability is could be intentional to avoid precisely such an application of ttv's.

**Comment by newfren** [comment]
the core is intentionally immune to explosions I think, were the tiles around it destroyed?

**Comment by JohnKiwols** [comment]
To a minor extent, I think so.  I was so surprised at the time I don't recall clearly; the blob mentioned in dead chat that it didn't take significant damage, if any.  Could check chat logs (that's a thing right?) if you're really curious, but...

If the core is intentionally immune then the rest is a bit of a toss-up: moral of the story is, don't use bombs on blobs kids! Ever!  Quite sad, but if that's the balance decision I'm kinda fine with it honestly. :(

**Comment by ShizCalev** [comment]
Intended
