### ISSUE TITLE
Mecha Syringe Gun can synthesize plasma, both slime toxins and all sorts that it shouldn't.

### ISSUE THREAD

**Issue by lolnon** [tgstation/tgstation#6929]
The only requirement for a reagent is R.reagent_state == 2 (code\game\mecha\equipment\tools\medical_tools.dm line 484), i.e. that the reagent is liquid.

This is the default value for the reagent base class and isn't changed for many exotic reagents. 

Perhaps we should test whether the reagent can be produced by chem dispensers.

**Comment by dannno** [comment]
I forgot to mention this, I had a round where I got an oddy and went around turning people into slimepeople

which isn't awful but I assumed it also allowed black slime toxin which is probably a lot worse

**Comment by TZK13** [comment]
"that it shouldn't."

Who's to say that it shouldn't? It's explicitly called a reagent synthesizer, I don't see why this should be nerfed when Odysseus mechs are rarely used enough as it is and are woefully inadequate when compared to other mechs. This is basically the one real saving grace the Odysseus has and it requires at least some amount of effort unlike something like heating up donk pockets in a microwave which wasn't intended.

**Comment by lolnon** [comment]
It's clearly an oversight. It's based on reagent_state and the only use of reagent_state I can find, but the values of reagent_state don't seem to have any consideration for balance, instead it takes a realistic approach.

It's arbitrary, then, which reagents can by synthesized and has no consideration for balance.

It also allows for infinite plasma, mutetoxin, and very easy creation of unlimited zombie powder (synth carpotoxin + stoxin, add copper).

**Comment by TZK13** [comment]
I know it allows for an infinite amount of those chemicals, personally I find that to be perfectly reasonable. It's extremely rare that anybody actually bothers to use it to its full extent because of the effort it takes to do so.

**Comment by lolnon** [comment]
The point is that reagent_state is an arbitrary value to base this on.

**Comment by phil235** [comment]
#7005 added the can_synth var to every reagent, now we only need to add can_synth = 0 to the reagents we don't want the odysseus to be able to synthesize.
