### ISSUE TITLE
Meson scanner goggles no longer update on your character sprite when the mode is changed

### ISSUE THREAD

**Issue by tnekohue** [tgstation/tgstation#69303]
## Reproduction:
Use Meson Goggles

![image](https://user-images.githubusercontent.com/17634568/185497041-8153235e-a263-425e-9f54-8ff697403fad.png)
![image](https://user-images.githubusercontent.com/17634568/185497058-9321b668-b14e-4bd1-818d-36072e715297.png)
The goggles should show up as yellow on my face

**Comment by ShizCalev** [comment]
@Kapu1178 #69179
