### ISSUE TITLE
Cracking Eggs into a beaker doesnt give egg yolk

### ISSUE THREAD

**Issue by Xander3359** [tgstation/tgstation#69300]
Reporting client version: 514.1583

## Round ID:
[188795](https://scrubby.melonmesa.com/round/188795)

## Testmerges:
- [Kills `/obj/shapeshift_holder`, replaces it with `/datum/status_effect/shapechange_mob`, also does a lot of Wabbajack refactoring](https://www.github.com/tgstation/tgstation/pull/69091)
- [Check for compliant JSON before receiving payload](https://www.github.com/tgstation/tgstation/pull/69023)
- [Fixes storage mass transfer being generally broken, adds mass transferring onto griddles ](https://www.github.com/tgstation/tgstation/pull/69084)
- [Buffs Heretic Curses, Living Heart, Leeching Walk, and technically Entropic Plume by fixing some bugs](https://www.github.com/tgstation/tgstation/pull/69181)

## Reproduction:
1: Take egg
2: Take beaker
3: Right click egg on beaker
4: Egg gone, nothing in beaker.
5: Be sad because no pancakes.

**Comment by Dorsisdwarf** [comment]
Reproduced. I suspect this is my fault

**Comment by newfren** [comment]
does left clicking the egg on the beaker add the reagents?

**Comment by Mooshimi** [comment]
> Reproduced. I suspect this is my fault

Do you plan to fix it

**Comment by Dorsisdwarf** [comment]
> > Reproduced. I suspect this is my fault
> 
> Do you plan to fix it

The behaviour isnt coded into the egg object, and I dont even try to touch things like beakers that are in literally hundreds of files its not worth the blood pressure from 15 minutes of looking through item search results trying to find the definition since we dont use dm any more
