### ISSUE TITLE
Apiaries refuse to spawn bees after some time... 

### ISSUE THREAD

**Issue by DAKKA-WAAAGH** [tgstation/tgstation#69315]
## Reproduction: Botanist, ordered beekeeper starter, placed apiary in botany, after mitosing first bee, injected it with omnizine, produced a lot of bees and honey (omnizine), added two more apiaries next to it, added a queen bee (happiness) and another queen bee (miner's salve), eventually bees stopped spawning, Striders13 and AdipemDragon were the ones who answered my ticket about this issue.

![image](https://user-images.githubusercontent.com/34065421/185608735-408a0f92-0ee0-4a13-93fc-6f48b21371ee.png)

**Comment by AdipemDragon** [comment]
looking at the apiary VV in the moment, there WERE a lot of bees in there, but they were just refusing to come out. That, and the stats tracking the progress to the next honeycomb and bee and such were all stuck in place on all 3 apiaries, at kind of random values, too.

**Comment by timothymtorres** [comment]
Just wanted to add that this is a old bug that is at least a year or two old.  I'm also not sure how to exactly reproduce it since it seemed to happen randomly.

**Comment by DAKKA-WAAAGH** [comment]
I tried bees again on another round and changing the type of queen bee and putting them back will force all of the bees of the old type out, but will also not produce bees afterwards.
