### ISSUE TITLE
You can now Teleport with Holopads

### ISSUE THREAD

**Issue by Timonkeyn** [tgstation/tgstation#69317]
Reporting client version: 514.1581

## Round ID:
[188832](https://scrubby.melonmesa.com/round/188832)

## Testmerges:
- [Check for compliant JSON before receiving payload](https://www.github.com/tgstation/tgstation/pull/69023)
- [Day and night controller](https://www.github.com/tgstation/tgstation/pull/68239)

## Reproduction:

Step 1: Call an unanchored Holopad
Step 2: get someone to move said holopad
you are now teleported

works with AI too if it connects to the holopad

**Comment by RazorManager89** [comment]
Duplicated of #68639 perhaps?

**Comment by Dorsisdwarf** [comment]
> Duplicated of #68639 perhaps?

#68639 is reported fixed and closed, if the issue is back then @ShizCalev ought to know

**Comment by Timonkeyn** [comment]
i think the easiest way to fix this is to make holopads unable to be constructed unanchored.

**Comment by Timonkeyn** [comment]
the way i got an unanchored holopad: i deconstructed one, unwrenched the assembly and constructed it again
also the holopad doesnt get turned "into someone" its like they are buckled to it while calling it, causing it to update the position of the player as on top of the holopad when its moved

**Comment by newfren** [comment]
you can also just use a wrench on a holopad to unanchor it

**Comment by Timonkeyn** [comment]
actually, its a dupe of 3 different issues, making this the 4th instance of it being reported

**Comment by ShizCalev** [comment]
dupe
