### ISSUE TITLE
Unable to defuse Flux Anomaly (certain frequency?)

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#69335]
## Round ID:
[188883](https://scrubby.melonmesa.com/round/188883)

## Testmerges:
#69091
#69023
#69084
#69181

## Reproduction:
> Flux Alert
> Get in and get frequency for signaller
> Enter Signaller , doesnt work
> Someone else arrives and tries , doesnt work
> Flux blows up

![Screenshot_1](https://user-images.githubusercontent.com/95751821/185742645-c028c62a-1190-4143-b9d0-2490c32eca49.png)

Do note that the first number was the standard frequency in the signaller

**Comment by Profakos** [comment]
That is strange, signalers sign up to SSradio during initialize.
