### ISSUE TITLE
angry vending machines can fly

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#69337]
Reporting client version: 514.1585

## Round ID:
[188899](https://scrubby.melonmesa.com/round/188899)

## Testmerges:
- [Kills `/obj/shapeshift_holder`, replaces it with `/datum/status_effect/shapechange_mob`, also does a lot of Wabbajack refactoring](https://www.github.com/tgstation/tgstation/pull/69091)
- [Check for compliant JSON before receiving payload](https://www.github.com/tgstation/tgstation/pull/69023)
- [Fixes storage mass transfer being generally broken, adds mass transferring onto griddles ](https://www.github.com/tgstation/tgstation/pull/69084)
- [Buffs Heretic Curses, Living Heart, Leeching Walk, and technically Entropic Plume by fixing some bugs](https://www.github.com/tgstation/tgstation/pull/69181)

## Reproduction:
![image](https://user-images.githubusercontent.com/12635164/185753551-04c1424f-cefc-40ec-82be-b6ce3322d315.png)
that's above the chapel in icebox and it should probably be falling

**Comment by Time-Green** [comment]
They’re not technically mobs I guess, but fuck

**Comment by LemonInTheDark** [comment]
floorbound things shouldn't be able to do this either. s dumb

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/04c36e57f012c01058ffe71fa1f3b55b5d7e6973/code/datums/ai/objects/vending_machines/vending_machine_controller.dm#L30-L48

https://github.com/tgstation/tgstation/blob/04c36e57f012c01058ffe71fa1f3b55b5d7e6973/code/datums/ai/objects/vending_machines/vending_machine_behaviors.dm#L1-L22

https://github.com/tgstation/tgstation/blob/04c36e57f012c01058ffe71fa1f3b55b5d7e6973/code/datums/ai/_ai_behavior.dm#L1-L28

I'm kind of surprised they don't just make them mimics...

**Comment by Sealed101** [comment]
can no longer reproduce; a bucketful of controller PRs ought to have fixed this at some point
![just lookatit](https://github.com/user-attachments/assets/3bc9646d-3aea-41c0-9e19-f55a5a20d78d)
