### ISSUE TITLE
Damage overlays don't seem to show up.

### ISSUE THREAD

**Issue by sergeirocks100** [tgstation/tgstation#69336]
Apologies if this has been reported before, i couldn't seem to find any relevant issues when i searched.

## Reproduction:

1. Hurt someone with brute or blunt damage.
2. Watch as they appear totally unharmed, because the damage overlays never seem to show up, no matter how much you hit them.

![Screenshot_9](https://user-images.githubusercontent.com/31294280/185748652-4c9381b1-1fa9-4e15-acca-76f57daa8281.png)

I beat this test subject up badly with my fists and the captain's saber, and dumped an entire laser rifle into them, and the damage overlays still failed to show up.

**Comment by timothymtorres** [comment]
Was this a dummy mob?  Can you test this on a real player? (even if they are ghosted it should be fine)

**Comment by Mooshimi** [comment]
The overlay showed up briefly for my tests but reset shortly and then allowed my to re-wound over and over

**Comment by Sealed101** [comment]
can't reproduce; fixed at some point
