### ISSUE TITLE
chemMaster 3000 (and by extension condi master) dont show their depowerd or broken sprites ever. 

### ISSUE THREAD

**Issue by D4C-420** [tgstation/tgstation#69350]
## Reproduction:
Found this while working on new sprites for condi master and had made ones for it to match the broken ones for the chem master . Thats when I noticed I had never seen depowerd or broken chem master sprites dispite them clearly being in code.

for the lack of a broke sprite
Step 1. head over to a chem master 3000.
step 2. hit it a bunch.
step 3. notice that it never "breaks" and goes directly to being a machine frame. you never see mixer1_b or mixer0_b

for lack of power
step 1. smash the apc
step 2. see the chem master not change sprites to mixer1_nopower or mixer0_nopower

https://streamable.com/we4kk7
^ video showing this on local

**Comment by Mooshimi** [comment]
it not using broken sprite is because it's not a computer, since it being broken literally just breaks it to it's base assembly components.... those are leftover icons i removed in my pr, ty for pointing them out
