### ISSUE TITLE
the mob charge ability destroys objects and walls regardless of if destroy_objects is true or not

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#69360]
## Reproduction:
Give a mob the charge ability, usually just basic_charge, then set the destroy_objects var to false. Use the ability on said mob and watch as it destroys objects anyways. Why does this happen, you might ask? I cannot be entirely certain, BUT:

This is the first of two separate procs that work together to handle object collision, as you can see it has a check for destroy_objects, however...
![image](https://user-images.githubusercontent.com/82386923/185807246-61296bc0-9e06-43ad-ad6b-699a73c6866a.png)

This is on_bump, which is called when a charging mob bumps into something, notice how it will add turfs and objects to the SSexplosions damage list regardless of destroys_objects or not.
![image](https://user-images.githubusercontent.com/82386923/185807275-93152507-0552-49c8-b842-09d7361e63b3.png)

So I MIGHT have found what the issue is, and this is likely an easy fix, but I'm cdoing rn and can't be bothered to wait the 30 seconds to change between codebases.

**Comment by Mooshimi** [comment]
inconsistent - mob charge ability destroying objects and walls regardless of destroy_objects true or not

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/70044
