### ISSUE TITLE
Paywall Firing pins no longer detect bank accounts.

### ISSUE THREAD

**Issue by Vanadiom** [tgstation/tgstation#69379]
## Testmerges: 
#69023
#68239  
Pretty sure they are not at fault, but, ya know.

## Reproduction:
0. (optional): Have a drive to make money by turning the greytide into a dangerous force.
1. Buy paywall firing pins
2. Buy disablers
2.1. Break open those crates
3. Remove the boring Electronic firing pins from the disablers
4. Link your account to the paywall firing pins and set any value for buying/shooting the gun
4.1 Insert said linked paywall firing pins into the disablers
5. Have other people try to fire the disablers, without success
5.1. Give em money to try it once, with no difference being made, except you getting less wealthy.

6. Notice the upside of having 9 disablers that only you can use.
7. Lament that you cant make money, and are now a poor man with 9 disablers to your name

**Comment by ShizCalev** [comment]
for whoever tackles this, active_prompt doesn't look to be setting correctly
