### ISSUE TITLE
Drones are blocked from interacting when a Revenant, Slaughter Demon, or any spectre'ing entity is hovering over them.

### ISSUE THREAD

**Issue by Feasel** [tgstation/tgstation#69370]
## Reproduction:

Just be a Drone and have a Revenant camp ontop of you. Or a slaughter demon. Or a Nightmare. Or well... anything! You can get griefed and be unable to do anything because of how Drones are currently coded. You just sit there, cry, suicide, and then wonder why the ghost role is even still in the code. Which is a shame because I liked sometimes rebuilding sections of the station silently... but yeah.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/20ddfddcc6d51f813f3fec3a90e94b396e61d33d/code/modules/mob/living/simple_animal/friendly/drone/_drone.dm#L339-L342

This is intended.  Drones are supposed to be able to interact near other drones and bots.  Anything else makes you shy.

**Comment by ShizCalev** [comment]
Shy component doesn't factor for incorporeal/invisible mobs. Will fix tomorrow.
