### ISSUE TITLE
Legion deciding to vacation outside the Necropolis without the door being opened.

### ISSUE THREAD

**Issue by Kitfox88** [tgstation/tgstation#69391]
Reporting client version: 514.1585

## Round ID:
[189036](https://scrubby.melonmesa.com/round/189036)

## Testmerges:
- [Tilening V2 Part 2.5 - Changing colors](https://www.github.com/tgstation/tgstation/pull/69342)
- [Buffs Heretic Curses, Living Heart, Leeching Walk, and technically Entropic Plume by fixing some bugs](https://www.github.com/tgstation/tgstation/pull/69181)
- [Check for compliant JSON before receiving payload](https://www.github.com/tgstation/tgstation/pull/69023)
- [Kills `/obj/shapeshift_holder`, replaces it with `/datum/status_effect/shapechange_mob`, also does a lot of Wabbajack refactoring](https://www.github.com/tgstation/tgstation/pull/69091)

## Reproduction:

Head north to the necropolis outer walls for some nice rare minerals. On my way back by the main door to take the bridge, Legion's vibing by it. It notices me and busts the door down and shits on my parade. Not the first time it's happened either.

**Comment by Mooshimi** [comment]
It was standing inside the open door, inside the closed door, outside it, etc? Your statement makes me think it's outside it's chamber, so what would it be busting through to get to you from there?

>It notices me and busts the door down and shits on my parade.

What door is this referring to?

**Comment by Jolly-66** [comment]
The door they're (probably) referring to is the one that leads to the Legions chamber.

**Comment by Mooshimi** [comment]
Is it outside the necropolis or not I'm confused

**Comment by Kitfox88** [comment]
> The door they're (probably) referring to is the one that leads to the Legions chamber.

This, the door right after the dragon statues. It will happily break it down and leave the necropolis entirely.
