### ISSUE TITLE
All limb targeted attacks redirect to chest

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#69398]
Round ID: [189052](https://scrubby.melonmesa.com/round/189052)

Testmerges: Not sure

Reproduction: Target head, and attack. It will attack the chest instead.

Clip: https://streamable.com/rrenzg

**Comment by dragomagol** [comment]
@ShizCalev ?

**Comment by ShizCalev** [comment]
Only affecting melee attacks, ranged is fine. Checking.
