### ISSUE TITLE
Cult Ghosts summoned via Manifest Rune can pass out because of n2o

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#69415]
## Round ID:
[189098](https://scrubby.melonmesa.com/round/189098)

## Testmerges:
#69023
#68239

## Reproduction:
> Last Ditch Summoning using Summon Ghost Runes in Atmos
> Ghost pass out because of n2o flood

Not very Ghostlike

**Comment by Mooshimi** [comment]
https://github.com/tgstation/tgstation/blob/92c5fd9a88d875b330b6204baa9ae21984c583a2/code/datums/status_effects/debuffs/debuffs.dm#L329-L340
