### ISSUE TITLE
the sec modsuit isnt shockproof but its description says it is

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#69417]
## Reproduction:
the description of the sec modsuit is. "An Apadyne Technologies security suit, offering shock protection and quicker speed, at the cost of carrying capacity."

1. get a sec modsuit
2. try to rescue a prisoner that got shocked by a grille
3. die to the shocks

**Comment by Mooshimi** [comment]
cc @Fikou Should this be shock proof or is the description wrong

**Comment by Mooshimi** [comment]
https://github.com/tgstation/tgstation/blob/92c5fd9a88d875b330b6204baa9ae21984c583a2/code/modules/mod/mod_theme.dm#L605-L656

**Comment by Mooshimi** [comment]
Looks like an accident 
https://github.com/tgstation/tgstation/blob/92c5fd9a88d875b330b6204baa9ae21984c583a2/html/changelogs/archive/2022-06.yml#L478-L481
