### ISSUE TITLE
Being deconverted from cult while a cult attribute is being applied (halo) will cause you to keep the attribute.

### ISSUE THREAD

**Issue by orthography** [tgstation/tgstation#69423]
## Testmerges:

n/A

## Reproduction:

Was being force-fed holy-water as cultist, I was deconverted just as the halo was applied causing me to keep the halo for the round, this quickly caused every single non-cultist to try and beat me to death while I was handcuffed in brig, admin intervention was needed as the only fix.

![image](https://user-images.githubusercontent.com/98856144/186304089-b7a53fe3-88ac-4151-b010-502825f3df10.png)

**Comment by necromanceranne** [comment]
"Oh, him? He's just the Antichrist, don't mind him."
