### ISSUE TITLE
Job required hours borking

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#69422]
## Testmerges:
[#69393: 'Makes the game start faster by optimizing round-start manifest injections' by GoldenAlpharex at commit c0e9377c8d](https://www.github.com/tgstation/tgstation/pull/69393)
[#69366: 'Sets up logging code to get numbers for where we spend the most REAL time during game setup' by LemonInTheDark at commit 7ddfca6397](https://www.github.com/tgstation/tgstation/pull/69366)
[#69181: 'Buffs Heretic Curses, Living Heart, Leeching Walk, and technically Entropic Plume by fixing some bugs' by MrMelbert at commit ed75f232d1](https://www.github.com/tgstation/tgstation/pull/69181)
[#69031: 'Unique ambience for virology!' by DrDiasyl at commit a04238bb39](https://www.github.com/tgstation/tgstation/pull/69031)
[#69376: 'Resolves is_banned_from headaches and lag (Speeds up roundstart significantly)' by LemonInTheDark at commit 9b9ccd0c12](https://www.github.com/tgstation/tgstation/pull/69376)
[#69353: 'TGUI for techfabs' by scriptis at commit b8ae1d5207](https://www.github.com/tgstation/tgstation/pull/69353)

## Reproduction:
1. Join /tg/station and view the jobs pref panel.
2. Randomly have some jobs that require time to join them again, which is not fixed by closing and opening the panel.
![Qzg2WXisnj](https://user-images.githubusercontent.com/85910816/186297990-50ebb82a-33c8-41ee-a684-c4cb25ee9309.png)

**Comment by SmoSmoSmoSmok** [comment]
i also started having lie playtime requirements on atmos tech and engineering
