### ISSUE TITLE
Leg cuffs make heretic sacrifice minigame unsurvivable (Not a bug) (Maybe an oversight)

### ISSUE THREAD

**Issue by Vanadiom** [tgstation/tgstation#69435]
## Round ID:
[189138](https://scrubby.melonmesa.com/round/189138)

## Testmerges:
#69023 
#68239 

## Reproduction:
1. Get leg cuffed before being sent to the shadow hand realm.
2. Have no chance of survival
3. Cry and Die

I think this shouldn't happen that way, the leg cuff should be removed in my opinion because it basically removes the whole minigame aspect of being sacced.

**Comment by timothymtorres** [comment]
CC @MrMelbert
