### ISSUE TITLE
Tasty tasty [Error] eggs

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#69462]
Reporting client version: 514.1578

## Round ID:
[189196](https://scrubby.melonmesa.com/round/189196)

## Testmerges:
- [Buffs Heretic Curses, Living Heart, Leeching Walk, and technically Entropic Plume by fixing some bugs](https://www.github.com/tgstation/tgstation/pull/69181)
- [Makes the game start faster by optimizing round-start manifest injections](https://www.github.com/tgstation/tgstation/pull/69393)
- [Adds lazyloading to the asset subsystems](https://www.github.com/tgstation/tgstation/pull/69454)

## Reproduction:
![image](https://user-images.githubusercontent.com/76874615/186683341-260843f0-31be-403d-9170-3aff25ece804.png)
Scotch Eggs are really something

**Comment by dragomagol** [comment]
This one's my fault
