### ISSUE TITLE
Whiteship fire alarms turn on when departing

### ISSUE THREAD

**Issue by DABLONKIE** [tgstation/tgstation#69471]
## Reproduction:

When a whiteship jumps to another location, all fire alarms on the whiteship turn on despite the atmosphere. It is possible to turn it off but it's annoying.

**Comment by Mooshimi** [comment]
Probably just triggered by momentary atmos changes, why not just remove the fire alarms and firelocks

**Comment by Mooshimi** [comment]
Dupe of #69447
