### ISSUE TITLE
PDAs can be destroyed in autolathes

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#69474]
## Reproduction:

Not really a "bug" so much as not intended probably, but you can destroy tablet PDAs (and anything inside of them) in an autolathe very easily.

**Comment by lessthnthree** [comment]
People shredding their IDs and PDAs in a lathe is a time old tradition to point and laugh at them as they sheepishly go to the HoP for a replacement.

**Comment by rasepretep** [comment]
I once also shredded my PKA. Features like this are genuinely hilarious.
