### ISSUE TITLE
You can activate modsuit modules if theyre pinned to the hud when the interface is malfunctioning.

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#69480]
Reporting client version: 514.1584

## Round ID:
[189251](https://scrubby.melonmesa.com/round/189251)

## Reproduction: pin a module, cut interface wire, and then activate the module.

![image](https://user-images.githubusercontent.com/54517726/186835942-1dfa8244-50b8-4631-a3fb-285d3172b50e.png)
![image](https://user-images.githubusercontent.com/54517726/186835957-949d3ec8-f615-4a73-babe-8f32ab533e03.png)

**Comment by Fikou** [comment]
intended you can also do this with the module button
