### ISSUE TITLE
you can fax c-4/x-4

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#69484]
Reporting client version: 514.1585

## Round ID:
[189267](https://scrubby.melonmesa.com/round/189267)

## Testmerges:
- [Buffs Heretic Curses, Living Heart, Leeching Walk, and technically Entropic Plume by fixing some bugs](https://www.github.com/tgstation/tgstation/pull/69181)
- [Makes the game start faster by optimizing round-start manifest injections](https://www.github.com/tgstation/tgstation/pull/69393)
- [Adds lazyloading to the asset subsystems](https://www.github.com/tgstation/tgstation/pull/69454)

## Reproduction:
stick c-4/x-4 to paper
stick paper in fax machine
click destination before 10 seconds pass
destination explodes
do it 11 more times until you run out of tc for x-4
giggle constantly

**Comment by AdipemDragon** [comment]
This could probably apply to other items, if you can make them stick to the paper, no?

**Comment by KommandantJackal** [comment]
This should be a feature

**Comment by Time-Green** [comment]
This doesn’t seem to be a bug. Papers are teleported through bluespace and other people pointed out c4 would transfer. It was known by the author and they didn’t stop it

@twilightwanderer thougts?

**Comment by ShizCalev** [comment]
100% feature. I won't fix this one.

**Comment by twilightwanderer** [comment]
> This doesn’t seem to be a bug. Papers are teleported through bluespace and other people pointed out c4 would transfer. It was known by the author and they didn’t stop it
> 
> @twilightwanderer thougts?

Yes, I knew about that.

**Comment by twilightwanderer** [comment]
Has this become a strong problem and have players begun to abuse this opportunity?
