### ISSUE TITLE
Chem dupe? In my spaceman game?

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#69483]
Reporting client version: 514.1578

## Round ID:
[189267](https://scrubby.melonmesa.com/round/189267)

## Testmerges:
- [69181](https://www.github.com/tgstation/tgstation/pull/69181) [69393](https://www.github.com/tgstation/tgstation/pull/69393) [69454](https://www.github.com/tgstation/tgstation/pull/69454)

## Reproduction:
Make Pill/Patch/Bottle, reagent stays in the machine as well as making the output.

![image](https://user-images.githubusercontent.com/76874615/186904613-134de014-b24e-422e-b97e-9fc4322e61ba.png)
![image](https://user-images.githubusercontent.com/76874615/186906853-471aa1c0-a774-4ff3-a029-89850a360286.png)

Droppers/Glasses/Cans just Make The Liquids now.

![image](https://user-images.githubusercontent.com/76874615/186906581-84176ea4-2d33-4cde-bcdf-e52eff44ec10.png)
![image](https://user-images.githubusercontent.com/76874615/186909823-41d6302d-da1c-47c7-b034-c119bfc26b64.png)
![Tasty Ginger](https://user-images.githubusercontent.com/76874615/186909886-3a34ce7a-687a-4fb8-883c-849b0ae5e20f.gif)

Yes they're all probably the same root problem but This Is Just All Sorts Of Bad.

**Comment by newfren** [comment]
I had to get so many droppers because it was impossible to empty the old ones

**Comment by AdipemDragon** [comment]
The only interaction I saw that's able to empty a canister of Something is either directly eating it or taking it out with a chemmaster/condimaster and the such

**Comment by newfren** [comment]
you could combat mode right click dump contents out of beakers and syringes emptied as normal (although drawing liquids duplicated them)

**Comment by Stiix72** [comment]
Got a tasty glitch. Round ID: 189288, name: Rolls-The-Dice, job: Virologist
Quirks: Illiterate, Foreigner, Self-Aware, Frail, Stormtrooper Aim, Light Drinker, Ageusia, Heterochromatic, Shifty Eyes, Tongue Tied, Friendly, Jolly, Night Vision, Heavy Sleeper, Light Step
Removed translator gloves and equipped latex. Now any container I transfer liquids from will retain liquid amount. Tested with dropper and beaker. Throwing the container causes it to spill ALL contents out, emptying it.

**Comment by timothymtorres** [comment]
Looks like this is happening to grenades, droppers, and beakers.  Somebody dun goofed _really bad._
