### ISSUE TITLE
Icebox new book scanner sprite does not look right on table

### ISSUE THREAD

**Issue by CursedBirb** [tgstation/tgstation#69485]
## Reproduction:
Start on IceBox and go to library

![009ef7a720e7d5a248a4951c4bfd9957](https://user-images.githubusercontent.com/47064429/186916498-c1e02fc5-f520-4e49-985a-13ebd2b4811b.png)

**Comment by ArcaneMusic** [comment]
Could probably use a pixel y offset and it's perfect
