### ISSUE TITLE
Can see into maintenance as AI with multi camera mode

### ISSUE THREAD

**Issue by Constellado** [tgstation/tgstation#69514]
## Reproduction:
I was able to see maintenance as AI. 

This only works in multi panel mode!

[

https://user-images.githubusercontent.com/64122807/187063180-621e5c14-5c22-4ca4-a563-0cfc84438f73.mp4

](url)

-First make one panel over maintenance. 
-Then make another panel, and move it over somewhere that is far away,
-The panel that is over maintenance can now see maintanance.
-I cannot access machines this way. thank goodness!

**Comment by timothymtorres** [comment]
Duplicate of #38307
