### ISSUE TITLE
You can "duplicate" deadchat controlled pets

### ISSUE THREAD

**Issue by NamelessFairy** [tgstation/tgstation#69521]
## Testmerges:
#68239

## Reproduction:
Its not true duplication of the mob but rather you can duplicate the inhand/clothing version.
Give Ian a deadchat control and orbit them, have a human pick up Ian, using deadchat control while orbiting the Ian and not the player holding them input a direction. Doing this will keep the Ian inhand/clothing item on the person carrying it but will release the mob. The mob can then be picked up again and this can be repeated.
Duplicated Ians teleport the actual Ian to their location when dropped/thrown

**Comment by private-tristan** [comment]
another note, though only related through ian, if you put deadchat controlled ian into a pet carrier as ian moves, the player that put ian in will instead be put into the pet carrier, don't remember the round ID on it, though
![image](https://user-images.githubusercontent.com/54422837/187099951-bb728275-b034-4892-8455-8e8332592cc2.png)

**Comment by dopamiin0** [comment]
I believe this may be linked to a similar issue I've experienced as an item variant of a pAI hologram - being put into a fryer, and then moving, leaves a frying "clone" of the hologram item, while also allowing the real version to escape. I'd hazard this is something to do with how itemified simplemobs, specifically uncurling/the summoning, is handled?
