### ISSUE TITLE
Can't reach your hand around a fax machine to push a button

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#69520]
Reporting client version: 514.1578

## Round ID:
[189398](https://scrubby.melonmesa.com/round/189398) but literally irrelevant because it's mapping

## Testmerges:
Irrelevant for mapping

## Reproduction:
![image](https://user-images.githubusercontent.com/76874615/187080455-66d20d85-34bb-4ee0-bbfe-dd868e5b17cf.png)
Genuinely now, Why are fax machines considered Dense or whatever it is. This is about the 3rd instance I've seen in the issue tracker of the fax blocking Something, thus needing some map rearrangement to counteract it.

**Comment by twilightwanderer** [comment]
I'm sorry, I tried to place all the faxes correctly, but I miscalculated in a couple of places.

**Comment by AdipemDragon** [comment]
It happens with new things, people Will find ways that they're broken
