### ISSUE TITLE
Praetorian instakilled borg.

### ISSUE THREAD

**Issue by Kitfox88** [tgstation/tgstation#69577]
Reporting client version: 514.1585
![instakill](https://user-images.githubusercontent.com/16981475/187597870-1e865d65-60f3-415f-958b-e8b6cfafecb4.png)

## Round ID:
[189567](https://scrubby.melonmesa.com/round/189567)

## Testmerges:
- [Buffs Heretic Curses, Living Heart, Leeching Walk, and technically Entropic Plume by fixing some bugs](https://www.github.com/tgstation/tgstation/pull/69181)
- [Adds lazyloading to the asset subsystems](https://www.github.com/tgstation/tgstation/pull/69454)

## Reproduction:
Heard about xenos in departures as the emergency shuttle was docking. Went to go check. Praetorian did the ol' spin stun once, then grabbed a person. I ran up to try to help after recovering and it did it again, walked over to me, and somehow instantly killed me from full health (minus the relatively minimal damage from a firelock crush). Absolutely no chance to fight back or flee.

**Comment by dragomagol** [comment]
Yep, this is from using acid (that's meant to be used on objects and turfs) on living things. It was changed when the acid power was changed from using a list to find a target to a click. I thought there was another issue on this but I can't seem to find it.

**Comment by Kitfox88** [comment]
Oh, well shit. Is it intended behavior then? If so it's kinda cruddy but not a bug.

**Comment by Ryusenshu** [comment]
it was supposed to be fixed a while back in #68246 
i got instakilled as a dragon by them in a round aswell 
[189639](https://scrubby.melonmesa.com/round/189639)

**Comment by Time-Green** [comment]
I'm gonna call being able to instakill borgs and dragons a bug, unless someone else wants to take over
