### ISSUE TITLE
Heretic hearts are deleted on species transformation

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#69574]
## Reproduction:
Be a heretic. Turn into another species via mutation tox, DNA spread virus, or any other way. This will cause the heretics heart to be deleted. In the case I observed specifically was in where a player turned into a chem zombie.

**Comment by davethwave** [comment]
I'll just generalize it to species transformation as the cause then.

**Comment by timothymtorres** [comment]
Duplicate of #35539
