### ISSUE TITLE
Revenants dont see Staff-DChat

### ISSUE THREAD

**Issue by Zergspower** [tgstation/tgstation#69590]
## Reproduction:

1.Revenant doing a bad
2.Staff tells Rev to knock it the fuck off
3.Revenant no see and continues doing a bad

Usually the non-bwoink approach of just telling em to calm down doesnt seem to allow them to see it

**Comment by msgerbs** [comment]
What is staff-dchat?

**Comment by Ghommie** [comment]
Typical skyrat issue.

> What is staff-dchat?

Yes, it's. As you can see on my PR, the command has aged like milk.

**Comment by msgerbs** [comment]
Oh I see, you mean the command that lets admins speak in deadchat.

**Comment by Mothblocks** [comment]
please use the full word i had no idea what you were talking about

**Comment by Zergspower** [comment]
> 

Revenant - since we dont have Rev's I forgot they existed honestly

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/d79a24c80f82871c233ac938a1a2073f8dc9ea74/code/modules/admin/verbs/deadsay.dm
