### ISSUE TITLE
legion spawned plasmamen are just humans

### ISSUE THREAD

**Issue by 1393F** [tgstation/tgstation#69609]
Reporting client version: 514.1584

## Round ID:
[189611](https://scrubby.melonmesa.com/round/189611)

## Testmerges:
- [Converts SSblackbox feedback to an associative list](https://www.github.com/tgstation/tgstation/pull/69399)

## Reproduction:
I don't quite remember, but I'm pretty sure awhile ago they were legit plasmamen
![Screenshot (353)](https://user-images.githubusercontent.com/59183821/187794365-ac3e4455-737e-4cb6-9553-04d5264149fe.png)

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/9f7beefb2640aba4576f5b1b138c1319c6c8d953/code/modules/mob_spawn/corpses/mining_corpses.dm#L68-L79

Also might be possibly related to #67282
