### ISSUE TITLE
Delta Stations 4 uncable'd APCs

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#69605]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
![Screenshot_1](https://user-images.githubusercontent.com/95751821/187777410-86a17c20-d095-4a60-9d2d-4c1c71b2bdb7.png)
![Screenshot_2](https://user-images.githubusercontent.com/95751821/187777422-4ba7c27c-329b-48a8-a497-e99f06bcf442.png)
![Screenshot_3](https://user-images.githubusercontent.com/95751821/187777432-2b1f1b0a-bb44-4e44-9e4a-425834b5f8e2.png)
![Screenshot_4](https://user-images.githubusercontent.com/95751821/187777445-54f57dcb-23f2-4200-ac44-07017fb1430f.png)

**Comment by msgerbs** [comment]
Any idea how long this has been like this? I see no PRs that immediately look like they'd have touched these areas...

**Comment by Ryusenshu** [comment]
Possibly since the Delta Rework, but im not sure why engi was affected here
