### ISSUE TITLE
xenos have fully working hands

### ISSUE THREAD

**Issue by theta060** [tgstation/tgstation#69615]
Reporting client version: 514.1585

## Round ID:
[189617](https://scrubby.melonmesa.com/round/189617)

## Testmerges:
- [Converts SSblackbox feedback to an associative list](https://www.github.com/tgstation/tgstation/pull/69399)

## Reproduction: be a xeno pick up a gun have fun better then shitty hardstun shoves 

![image](https://user-images.githubusercontent.com/103159114/187809125-f0ee8b05-45c6-4e93-9bf0-e89e267a8acd.png)

**Comment by theta060** [comment]
by fully working i mean they can use EVERYTHING just not computers

**Comment by theta060** [comment]
also another bug if a xeno eats a dead person they are just gone

**Comment by ArcaneDefence** [comment]
> also another bug if a xeno eats a dead person they are just gone

Or, perhaps... Feature? flushed hahaha... 

A separate issue for this would be good, as I can't imagine they're immediately related
