### ISSUE TITLE
Funds that were intended to be sent were not received

### ISSUE THREAD

**Issue by Ryll-Ryll** [tgstation/tgstation#69628]
## Reproduction:
this isn't a reproduction , i'm just gonna say what happened. a few months ago, oranges @optimumtact told me that he would provide me with $100 USD, which he specified as USD and not the lesser NZ dollars. I've yet to receive the funds in my paypal or my paypal/venmo. I'd just like to bring up this issue since it's documented he agreed to do this, but hasn't, so i think tagging it to the tg issue report count will help make sure freak accidents where people don't give me $100 have an easily known working known solution

once this matter is resolved, we should be good to close this issue report without needing an explicit fix going forward, as this is an instantiated issue.

**Comment by Ryll-Ryll** [comment]
tagged

**Comment by theta060** [comment]
orange man also failed to pay my shitposting tax ban he

**Comment by optimumtact** [comment]
ratio + l + touch grass
