### ISSUE TITLE
Space syndie simplemobs with knives (redsuit variant) have shields that block lasers

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#69636]
Reporting client version: 514.1585

## Round ID:
[189641](https://scrubby.melonmesa.com/round/189641)

## Testmerges:
- [Day and night controller](https://www.github.com/tgstation/tgstation/pull/68239)

## Reproduction:
1. spawn knife redsuit syndie simplemob
2. shoot with laser
3. shield???

**Comment by msgerbs** [comment]
Are they not supposed to? And what was the exact name/typepath of the mob you spawned?

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/1be57f31e4094bf4c4e07615198188a1654e9245/code/modules/mob/living/simple_animal/hostile/syndicate.dm#L76-L139

This looks intended.

**Comment by Addust** [comment]
it still isn't visibly pointed out in game that they have a shield when they should definitely NOT have a shield (icon shows no shield)

**Comment by Addust** [comment]
the mob was naturally spawned but the typepath is /mob/living/simple_animal/hostile/syndicate/melee/space iirc

**Comment by msgerbs** [comment]
Alright well that's an issue we can work on, the sprite should better show that it's got an energy shield.

**Comment by Addust** [comment]
1. gets an eshield to explain the shield
2. loses its shield

**Comment by Addust** [comment]
and dont fucking give a shield to the non-space one the meta-class whiteship is irritating enough to capture already

**Comment by Mooshimi** [comment]
Cleanup tag isn't working
