### ISSUE TITLE
Some Icons with Multiple States are not Displaying Correctly

### ISSUE THREAD

**Issue by GreyTide2108** [tgstation/tgstation#69645]
Reporting client version: 514.1585

![](https://puu.sh/JjbJc/6dad77f6dc.gif)

![](https://puu.sh/JjbhP/e5f821e372.png)

![](https://puu.sh/JjbK2/a26a725702.png)

![](https://puu.sh/Jjcfg/bdbde0a30e.png)

## Round ID:
[189659](https://scrubby.melonmesa.com/round/189659), 189664

## Testmerges:
- [Buffs Heretic Curses, Living Heart, Leeching Walk, and technically Entropic Plume by fixing some bugs](https://www.github.com/tgstation/tgstation/pull/69181)
- [Moves "catch this var/flag" code from obj/init and datum/new into the types that use it ](https://www.github.com/tgstation/tgstation/pull/69634)
- [Macro optimizes SSmapping saving 50% ](https://www.github.com/tgstation/tgstation/pull/69632)

**Comment by JohnFulpWillard** [comment]
![image](https://user-images.githubusercontent.com/53777086/187985461-36b44ce7-5206-4d77-b70c-c496cefbcbcd.png)
Canisters at the moment. None of these are actually open, their gas overlay just seems to go through the canister.

![image](https://user-images.githubusercontent.com/53777086/187985533-cdb40b22-dd04-418a-91bd-dc018789ab89.png)
Posters also don't seem to load

This is a picture on Sybil, without these testmerges, on the same map and same place
![image](https://user-images.githubusercontent.com/53777086/187985633-d93d71a3-6b7f-4cb4-9e0b-73bae5987bfb.png)

One of these two testmerges broke this @LemonInTheDark

**Comment by LemonInTheDark** [comment]
I'll look into it. no way it's fucking maploading right?

**Comment by GreyTide2108** [comment]
> no way it's fucking maploading right?

Mapload and mapfiles have a LOT of the game data compressed inside them. It's entirely possible those optimizations could have borked icons. Not that I would understand how.

**Comment by LemonInTheDark** [comment]
it's not maploading, it's just emissives being fucking weird

**Comment by LemonInTheDark** [comment]
Resolved
