### ISSUE TITLE
Operating tables are invisible

### ISSUE THREAD

**Issue by scriptis** [tgstation/tgstation#69657]
## Testmerges:

[#69635: 'Limit icon_states checks in spritesheet creation to UNIT_TESTS (saves 1.6s of init time)' by Mothblocks at commit 14830a36a7](https://www.github.com/tgstation/tgstation/pull/69635)
[#69586: 'Paper bins now create paper dynamically, rather than creating thousands of pieces of paper on init every round' by Mothblocks at commit 920e024f8c](https://www.github.com/tgstation/tgstation/pull/69586)
[#69587: 'Closets now initialize their contents on demand (more than 1.6 seconds of init time saved)' by Mothblocks at commit b92220822d](https://www.github.com/tgstation/tgstation/pull/69587)
[#69638: 'Micro-optimize RegisterSignal, saving 0.3s of init time' by Mothblocks at commit bb0f20e2be](https://www.github.com/tgstation/tgstation/pull/69638)

## Reproduction:

1. Have an operating table.
2. ![don't have an operating table](https://user-images.githubusercontent.com/12202230/188046923-ec1e37fd-3140-42a5-b8fc-47fbb4bf6b72.png)

**Comment by scriptis** [comment]
Energy swords, when active, are also currently invisible.

**Comment by ShizCalev** [comment]
#69635 perhaps? confirming

**Comment by ShizCalev** [comment]
#69635 perhaps? testing

**Comment by scriptis** [comment]
@ShizCalev seems to be caused by #69543

**Comment by scriptis** [comment]
#69416 seems to have caused eswords, only affects admin-spawned eswords; there is no icon for a `NULL` `sword_color_icon`, which defaults to `e_sword_on` in `transforming_energy.dmi`

**Comment by scriptis** [comment]
I'm blind, operating tables are fixed by #69654

**Comment by san7890** [comment]
#69654 is now merged, closing.
