### ISSUE TITLE
Lizard tail stay pixles remained after tail was removed

### ISSUE THREAD

**Issue by itseasytosee** [tgstation/tgstation#69658]
## Round ID:
Local

## Testmerges:
Local

## Reproduction:
Remove a lizards tale
![image](https://user-images.githubusercontent.com/55666666/188056943-9848e0d6-0a88-4e26-a45c-8f4e0a59798b.png)
(Ignore the lack of lizard snout I removed it via surgery)
Probably has something to do with the lizard's "ridge"cosmetic? I don't know I don't play lizard.

**Comment by newfren** [comment]
that'd be the external organ for sure, it probably shouldn't stick around after a tail's removed

**Comment by Jolly-66** [comment]
Its the spines yeah

**Comment by rasepretep** [comment]
Noodletail

**Comment by Time-Green** [comment]
Spines have the tail sprite baked in. This was known when they were added and it’s going to be awful to fix

**Comment by itseasytosee** [comment]
Also, presumably, you should be able to implant the spines in another tailless creature and have the pixels on display.

**Comment by Time-Green** [comment]
> Also, presumably, you should be able to implant the spines in another tailless creature and have the pixels on display.

Yes that’ll do it aswell
