### ISSUE TITLE
mayhem in a bottle removed my dexterity?

### ISSUE THREAD

**Issue by 1393F** [tgstation/tgstation#69653]
Reporting client version: 514.1584

## Round ID:
[189675](https://scrubby.melonmesa.com/round/189675)

## Testmerges:
- [Converts SSblackbox feedback to an associative list](https://www.github.com/tgstation/tgstation/pull/69399)

## Reproduction:
![Screenshot (388)](https://user-images.githubusercontent.com/59183821/188025340-67746b0f-4005-40ed-85c1-839b185372e0.png)
I tried using the legion core inhand but this came up after I used mayhem in a bottle

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/d91390a4474e511279b6ee7525c5982266b9a858/code/modules/mining/lavaland/megafauna_loot.dm#L236-L249

https://github.com/tgstation/tgstation/blob/f1a363c825a31b9083019d19c69212e87fd78722/code/datums/status_effects/buffs.dm#L371-L397

This might be causing it...

https://github.com/tgstation/tgstation/blob/d91390a4474e511279b6ee7525c5982266b9a858/code/modules/mining/equipment/regenerative_core.dm#L99-L101

**Comment by 1393F** [comment]
this was fixed by the adminordrazine rework
