### ISSUE TITLE
Nightmares are immune to light, can not heal in the dark.

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#69666]
## Round ID:

[Round ID]: # 189709

#69632 
#69634 
#69181 

## Reproduction:

>Be nightmare
>Stand in the light
>Take no damage
>Go to holodeck and suck up the rays while enjoying a pina colada.

![image](https://user-images.githubusercontent.com/16896032/188143390-39ccfbac-7634-4457-be98-696405519432.png)

Jaunting and arm blade still work as intended; healing/damage involving light and dark are both currently broken however which is a drag. Probably caused by #69543 

Still love you tho arm.

**Comment by timothymtorres** [comment]
Did you test this in locations outside of the holodeck?  Holodeck is not affected by light since it's all simulated.

**Comment by newfren** [comment]
that nightmare was walking around all round just chatting to people standing in brightly lit hallways and shit it wasn't just the holodeck

**Comment by carshalash** [comment]
> Did you test this in locations outside of the holodeck? Holodeck is not affected by light since it's all simulated.

I took the screenshot in the beach holodeck with the pina colada as a joke mostly. It was effecting me everywhere and there was no healing in the dark, either in ain't or in the outside of icebox.

I stand by my belief that the screenshot is funny.

**Comment by Shadowflame909** [comment]
Im just glad it didnt completely make nightmares unplayable. At least they currently temporarily dont fry in the light AND dont heal in the dark.

Not the worst bug to play with for now
