### ISSUE TITLE
too many colossus on icebox

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#69677]
Round ID: [189747](https://scrubby.melonmesa.com/round/189747)
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [2e29dd1989f81a79c032aa16cf870be49bd220a0](https://www.github.com/tgstation/tgstation/commit/2e29dd1989f81a79c032aa16cf870be49bd220a0)
The following pull requests are currently test merged:
[#69634: 'Moves "catch this var/flag" code from obj/init and datum/new into the types that use it ' by LemonInTheDark at commit 18b5e81303](https://www.github.com/tgstation/tgstation/pull/69634)
[#69632: 'Macro optimizes SSmapping saving 50% ' by LemonInTheDark at commit 90f63bbbeb](https://www.github.com/tgstation/tgstation/pull/69632)
[#69240: 'Changed Supermatter Internal Math + UI Additions' by vincentiusvin at commit 09a016a732](https://www.github.com/tgstation/tgstation/pull/69240)

Local commit: fb5219713dcd39d4fe8afda34a76c0a0ebba5c63
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1

observe on icebox and see way too many colossus.
![image](https://user-images.githubusercontent.com/61211748/188249209-ba140077-f83c-4634-9645-12a7e744d53d.png)

**Comment by newfren** [comment]
I've heard there's been way too many tendrils and drakes on lavaland as well but don't have direct experience

**Comment by Kitfox88** [comment]
this is a big problem

**Comment by rasepretep** [comment]
> I've heard there's been way too many tendrils and drakes on lavaland as well but don't have direct experience

![image](https://user-images.githubusercontent.com/85033934/188267492-8bf7f34e-aa43-47b2-b20c-526bf146a2b7.png)

Correct. That's 8 out of 10 total in that round. Other rounds I've seen drakes consistently up to 15+, and there's always around 20+ tendrils now.

**Comment by Jackal-boop** [comment]
![image](https://user-images.githubusercontent.com/61211748/188281648-a6b03949-05fa-48bd-8038-6227b0e29845.png)

they are getting more powerful

**Comment by ATH1909** [comment]
> > I've heard there's been way too many tendrils and drakes on lavaland as well but don't have direct experience
>
> Correct. That's 8 out of 10 total in that round. Other rounds I've seen drakes consistently up to 15+, and there's always around 20+ tendrils now.

damn that's a power image right there
