### ISSUE TITLE
Able to join as AI despite being Silicon banned.

### ISSUE THREAD

**Issue by Stiix72** [tgstation/tgstation#69688]
## Reproduction:
Was just able to join as AI while being silicon banned permanently. Did not notice anything more than that.

**Comment by Time-Green** [comment]
Was the occupation screen different? Or could you just click AI like there wasnt a ban?

**Comment by san7890** [comment]
@LemonInTheDark Potentially related to ban cache?

@Stiix72 Your ckey (BYOND account name) is Stiix, right? I could pull logs to check but it's better to have all information in one spot.

**Comment by LemonInTheDark** [comment]
I'm unsure. yes, it is

**Comment by Stiix72** [comment]
Yes, my Ckey is Stiix. Apologies for the lateness of getting back to this. Occupation screen was like it always is  except I was able to interact with the AI and cyborg settings as though I was not banned.

**Comment by Timberpoes** [comment]
Reproduced on local, problem is explained in more detail in PRs #69702 and/or #69703
