### ISSUE TITLE
Thunderdome reset issues - stacking turfs (?) and the camera.

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#69711]
Reporting client version: 514.1585

## Round ID:
[189847](https://scrubby.melonmesa.com/round/189847)

## Testmerges:
- [Changed Supermatter Internal Math + UI Additions](https://www.github.com/tgstation/tgstation/pull/69240)

## Reproduction:

Repeatedly reset the thunderdome.  After some number of attempts the floor tiling will break (usually in patches, but in this case after 6 resets its totally messed up).  Some chat i caught in passing maybe relates this to the turfs stacking in some way (?)

![image](https://user-images.githubusercontent.com/3789327/188324734-48d6a4d6-b2ad-4dae-a2c4-25951183f21f.png)

Also of note, the security cameras stack up

![image](https://user-images.githubusercontent.com/3789327/188324765-d41d63b9-c2ee-4036-a992-d44815f7b605.png)

**Comment by ShizCalev** [comment]
Think the security cameras thing is intentional so that people can keep watching the same feed.
![image](https://user-images.githubusercontent.com/6209658/188345518-e10f856c-1dfc-45de-a805-79a1c1fdf2cd.png)
