### ISSUE TITLE
Cult size check breaks and divides by zero when no active non-cultist player is alive

### ISSUE THREAD

**Issue by Pepsilawn** [tgstation/tgstation#69718]
## Round ID:
Found locally

## Reproduction:

Proc that gets the ratio of the size of the cult goes `number of alive cultists players/number of alive non-cultists players`, which ends up dividing by zero if there is no active, alive non-cultist player. Ends up runtiming hard, breaks everything that requests that check, which includes a few runes effects as well as the red eyes/halo check

Related code bit:
https://github.com/tgstation/tgstation/blob/41823ee00075a18fcef7c21a851bef88f1f2a80e/code/modules/antagonists/cult/cult.dm#L275-L287

**Comment by ShizCalev** [comment]
did you encounter this by manually callings procs? check_size is only called when a cultist uses attack_hand on a rune

![image](https://user-images.githubusercontent.com/6209658/188497225-e133d820-b874-4cde-8f6f-9aa037c01d3b.png)
