### ISSUE TITLE
Circuit USB fails to interact with outside objects

### ISSUE THREAD

**Issue by Blevruz** [tgstation/tgstation#69715]
## Reproduction:

Build circuit server with integrated circuit.
Build bluespace launchpad console.
Link at least one launchpad to the console.
Link the console to the server via USB.
Add a "speech" component to the error output of the bluespace launchpad component in the circuit.
Try to do anything with the launchpad.

In my case, it claimed "No Launchpad Connected" even when one launchpad was connected and usable through the console itself. I couldn't even set its X and Y position.

**Comment by moocowswag** [comment]
I dont know what causes this but ive experienced it before, make sure the pad itself is in a powered area, set the pad youre controlling to 1 via the circuits, and if that doesnt work deconstruct the pad/screwdriver the console and set it back up again.

**Comment by Anstan001** [comment]
I've had the exact same issue. Bluespace launchpad, even when connected directly to the shell via USB reports "Not connected!"

**Comment by moocowswag** [comment]
Might be a new problem if multiple people are reporting it now, it was an uncommon inconvience for me when i had to deal with it.

**Comment by Blevruz** [comment]
After further testing, the exact same issue arose with reflectors. I'll keep looking for USB stuff that works.

**Comment by Acer202** [comment]
Also here to lament about this bug. My circuits!

Reflectors and launchpads aren'tworking like everyone else states. Probably more than that.

**Comment by Mooshimi** [comment]
cc @Watermelon914

**Comment by moocowswag** [comment]
I dont think watermelon is the one that coded reflector and launchpad ports.

**Comment by Mooshimi** [comment]
sure, watermelon is just the circuit person and it's good to consult them

**Comment by Mooshimi** [comment]
> I dont think watermelon is the one that coded reflector and launchpad ports but if other stuff is failing then its probably relevant to him
> 
> I think #69664 caused this cause this issue report was made 2 days after it was merged

@LemonInTheDark what do you think?

**Comment by LemonInTheDark** [comment]
Potentially, go bully moth @Mothblocks

**Comment by Watermelon914** [comment]
is this still a bug? I am the circuits person but I have been pretty inactive since I've been busy.

**Comment by Watermelon914** [comment]
Okay, I know why this is happening. It's an easy enough fix
