### ISSUE TITLE
Ethereals don't take toxin damage from low charge

### ISSUE THREAD

**Issue by Bluedino1025** [tgstation/tgstation#69716]
Reporting client version: 514.1585

## Round ID:
[189874](https://scrubby.melonmesa.com/round/189874)

## Testmerges:
- [Macro optimizes SSmapping saving 50% ](https://www.github.com/tgstation/tgstation/pull/69632)
- [Completely refactors hallucinations, and also adds a few ](https://www.github.com/tgstation/tgstation/pull/69706)

## Reproduction:
As an ethereal just run low on charge and you won't take toxin damage.

**Comment by Palpetinus** [comment]
They don't do and were never intended to, assuming you actually mean LOW charge. After that, there's STARVING charge and they take toxin damage in that.

**Comment by Mooshimi** [comment]
no response, and ive played ethereal and starved to death from toxin damage in the last month
