### ISSUE TITLE
cargo remote can't access cargo shuttle doors

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#69720]
Reporting client version: 514.1585

## Round ID:
[189903](https://scrubby.melonmesa.com/round/189903)

## Testmerges:
- [Macro optimizes SSmapping saving 50% ](https://www.github.com/tgstation/tgstation/pull/69632)
- [Completely refactors hallucinations, and also adds a few ](https://www.github.com/tgstation/tgstation/pull/69706)

## Reproduction:
![image](https://user-images.githubusercontent.com/12635164/188437449-5e06f714-91e6-4d8a-ae1e-18b4d80e9ed6.png)
gives you this message when you try

set remote to emergency access
successfully emergency access doors leading to shuttle
fail to emergency access shuttle

**Comment by Maurukas** [comment]
Tests good. Appears to have been fixed by #71735
