### ISSUE TITLE
syndicate listening post in space comes with an incomprehensably cursed lantern that tears at the seams of reality

### ISSUE THREAD

**Issue by dopamiin0** [tgstation/tgstation#69737]
## Round ID:

[189961](https://scrubby.melonmesa.com/round/189961)

## Reproduction:
"IT CREATES CLIENTSIDE PSEUDO-LIGHT IN YOUR INVENTORY"

In the syndicate listening post, there exists a lantern labelled the "Suspicious Lantern." This is an unfathomable understatement. While turned on and set down normally, it exists the intended behavior: emitting light for all to see. While picked up, though, it has two different effects, depending on whether you're the one holding it.

Not holding it: the lantern will fail to emit any light, even while turned on. You can watch the person holding it all you want, they can swear it's on, but everything will remain at the same light levels.

Holding it: Wherever the icon exists on your screen, it'll emit light for you only. By default, this is your hands and in the top left with the buttons, but hovering over a new valid spot, like your belt or back slot, will also emit light there. This is not true light, as it will not light up tiles so dark that you cannot see them at all. 

I cannot explain just how cursed this lantern is within words, I HIGHLY recommend seeing this for yourself. And then getting therapy to attempt to unsee it.

**Comment by msgerbs** [comment]
wtf have you done

**Comment by dopamiin0** [comment]
> wtf have you done

ITS NOT MY FAULT I SWEAR

**Comment by msgerbs** [comment]
LOL oh this is great. Apparently if you put a lantern (of any sort) on a map and edit the light_on var to on, it breaks it completely and you get this utterly bizarre effect. I'll fix this.
