### ISSUE TITLE
Assemblies are mostly broken

### ISSUE THREAD

**Issue by msgerbs** [tgstation/tgstation#69751]
## Reproduction:

I tested a bunch of different assemblies and almost none them worked as expected:

- Igniter/timer: Worked fine. Slapped it on a welding tank, went boom. No issue.
- ~~Igniter/signaler: Completely non-fuctional. Did nothing in my hands, the ground, or a tank.~~ Fixed in #69773
- Igniter/voice: Worked fine. Slapped it on a welding tank, went boom. No issue.
- Igniter/prox sensor: Mostly worked in my hands or on the ground, with some inconsistency. Seems completely broken when attached to tanks. When armed, it goes off before putting it on the tank and then just turns off. When on timer mode it stays in the arming state (flashing yellow) and never arms then immediately arms, goes off, and turns off as soon as I take it off.
- Igniter/laser: Seems to work, although the laser turns itself off the first time it's triggered. Does not work on a tank but I suspect the tank blocks the laser.
- ~~Prox/signaler: Doesn't seem to work. Arms properly but then stays armed forever and never beeps or does anything else. Only goes off when I pick it up.~~ Fixed in #69773
- ~~Laser/signaler: Beeps once when triggered then turns off, but never triggers other signalers.~~ Fixed in #69773
- ~~Voice/signaler: Again the voice sensor goes off but the signaler does not.~~ Fixed in #69773
- ~~Timer/signaler: Again the timer goes off (and repeats if set) but signaler does not.~~ Fixed in #69773
- ~~Signaler by itself: Couldn't get it to do anything in any possible configuration or usage.~~ Fixed in #69773
- Prox by itself: Couldn't get this to do anything either most of the time but I think I did manage to get it to go off as expected a few times.
- Laser by itself: Seems to work as expected
- Timer by itself: Works as expected
- Voice by itself: Works as expected

That's about everything I could think of to test. Some of this is explained by #68139 but it seems there's more going on than just that since signalers don't seem to work at all and proximity sensors seem very inconsistent even when not in an assembly.

**Comment by moocowswag** [comment]
Proximity sensor has a quirk i want to add incase you ran into this and got confused.

First off, setting range to 1 means it triggers when you walk to the tile next to it, all good and normal, this implies that 1 range = 1 tile away right?

WRONG

Setting range to 0 means that it only triggers when you pick it up or take it out of a container or something like that (it doesnt trigger when you walk on the same tile as it)

**Comment by msgerbs** [comment]
Good to know, but I didn't actually try range 0. I tried 1 and 2 and neither seemed to work consistently.

**Comment by moocowswag** [comment]
Either a recent pr scuffed proximity sensors by themselves even more or their broken behavior just doesnt take place when attached to a wire/grenade, I recently posted a round where I made a ton of grenades using range 1 proximity sensors.

**Comment by dalmationer** [comment]
this is a duplicate of #69043

**Comment by moocowswag** [comment]
> this is a duplicate of #69043 (but i get it i did name it something fairly weird)

Get in line

**Comment by msgerbs** [comment]
I think this issue is more broad than either of these 2 honestly.

**Comment by dalmationer** [comment]
I -think- @SuperSayu  may be working on this right now.

**Comment by moocowswag** [comment]
Im still convinced #65420 caused this.

**Comment by msgerbs** [comment]
Should be easy enough to test. I can't remember exactly how to find what the last revision was before the pull request, but I know it's doable.

**Comment by SuperSayu** [comment]
> Im still convinced #65240 caused at least some of this.

There's broken logic for assembly holders that traces back to that pr, responsible for assemblies pinging themselves, yes.  I could list at least 3-4 trivial fixes for things in assemblies that I have put together to pr, but I'm having trouble with the stupid prox sensors because the logic for this one stupid part is distributed across two or three datums and one to three objects, depending on how it's configured, and I am not sure exactly which parts are malfunctioning or where to fix them.

I should really just fix the things I can and leave the prox sensor mess for someone else.

**Comment by msgerbs** [comment]
I tested both #65240 and #67160 and although #67160 does indeed have bugs with prox sensors attached to welding tanks as the PR says, the rest of the stuff works fine and did not match my experience documented in this issue.  So it was something newer than those PRs.

**Comment by msgerbs** [comment]
I did a bisect and determined that #68318 is the PR that broke signalers. I have absolutely no idea how, but it did.

**Comment by SuperSayu** [comment]
> I did a bisect and determined that #68318 is the PR that broke signalers. I have absolutely no idea how, but it did.

I would believe that.  Signalers are runtiming because there are weak ref datums being deleted and nulls left in the frequency list.  Software signalers sounds like a place where proper cleanup might have been overlooked

**Comment by timothymtorres** [comment]
Please don't batch up your issues together in one massive report.  It also appears that almost all of them were fixed at some point.  I'd highly recommend you close this and open separate issues for the ones that remain.

**Comment by msgerbs** [comment]
Yeah I think most of these were fixed by those 2 bugfix PRs
