### ISSUE TITLE
Fishing is Probably Broken

### ISSUE THREAD

**Issue by Breadeagle** [tgstation/tgstation#69755]
## Round ID:
[190003](https://scrubby.melonmesa.com/round/190003)
[190006](https://scrubby.melonmesa.com/round/190006)

## Testmerges:
https://github.com/tgstation/tgstation/pull/69632
https://github.com/tgstation/tgstation/pull/69706

## Reproduction:
Human cargo tech
Used a variety of bait, rods, lines, and hooks. 
Fished in a fishing portal, moisture trap (190003), then gateway beach biodome (190006)
Many attempts with perfect or near perfect minigame play. 
The only person who got even a single fish was a lizard chef on the fishing portal. 
Probably did 30+ fishing attempts between myself and a few other characters over the course of two rounds. One fish caught.

In this problem report https://github.com/tgstation/tgstation/issues/67942
AnturK, the developer of the feature, suggests that problems may have been caused by the minimum fishing time abuse check, which I noticed in the code while trying to see why the catch rate was so low. That said, I'm not even sure an abuse check even needs to be in place here. Its fishing, and I'm not too sure if people really cheat all that much in SS13. The catch rate was SO low that I thought it was possible the success chance was either reversed, or if the roll equaled the exact fail number or something.

**Comment by VladinXXV** [comment]
i just want to fish for gods sake

**Comment by Time-Green** [comment]
@AnturK

**Comment by AnturK** [comment]
I guess i'll just remove this check.
