### ISSUE TITLE
Everything except the UI is black

### ISSUE THREAD

**Issue by AterSoul** [tgstation/tgstation#69774]
Reporting client version: 514.1587

**Comment by timothymtorres** [comment]
A screenshot would be preferred.

**Comment by LemonInTheDark** [comment]
Oh come the fuck on

**Comment by LemonInTheDark** [comment]
Also: byond issue, make a report on the byond forums https://www.byond.com/forum/5

**Comment by LemonInTheDark** [comment]
in the mean time downgrade to 1585

**Comment by LemonInTheDark** [comment]
that or play on sybil it should? function there, my multiz pr somehow fixed it

**Comment by LemonInTheDark** [comment]
I think this is an us issue, but it's kinda hard to tell.
The byond update fixed some buggy behavior that we may have accidentally been relying on?
