### ISSUE TITLE
maint closets spawn in opened an empty but unable to be passed through, then continue to be weird

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#69779]
Reporting client version: 514.1585

## Round ID:
[190091](https://scrubby.melonmesa.com/round/190091)

## Testmerges:
- [Macro optimizes SSmapping saving 50% ](https://www.github.com/tgstation/tgstation/pull/69632)
- [Completely refactors hallucinations, and also adds a few ](https://www.github.com/tgstation/tgstation/pull/69706)

## Reproduction:
![image](https://user-images.githubusercontent.com/12635164/189067304-5c5d3981-e1b6-4708-894d-dafae415c3a3.png)
maybe another assistant came by and opened this? but I can't walk into its tile...
![image](https://user-images.githubusercontent.com/12635164/189067400-0552b0fe-998b-413b-a778-029c39aaa06f.png)
first click closes it as you'd expect
![image](https://user-images.githubusercontent.com/12635164/189067454-f5ba678b-772d-4365-bbe3-af687ed080e0.png)
but the second click opens it again to reveal it was actually full of delicious maintenance loot! what's the big idea here

**Comment by newfren** [comment]
this happened with crates too

**Comment by timothymtorres** [comment]
Very strange.  Possible caused by #69587  This sounds like `PopulateContents()` is triggered after the closet is spawned open and has it's icon updated.  That would likely result in the icon appearing open with no items on the floor.

CC @Mothblocks @MrMelbert

**Comment by Mothblocks** [comment]
oh that would make sense
