### ISSUE TITLE
Skeletons can no longer heal with milk

### ISSUE THREAD

**Issue by realthomas69** [tgstation/tgstation#69777]
## Round ID:
[190085](https://scrubby.melonmesa.com/round/190085)
Byond ver: 514.1587

## Reproduction:

Drinking milk as a skeleton is no longer possible; due to your lack of stomach you will vomit the milk back up
![image](https://cdn.discordapp.com/attachments/952505243525062658/1017332714757693480/unknown.png)

**Comment by moocowswag** [comment]
Shouldnt even be possible to throw up without a stomach lol

**Comment by Time-Green** [comment]
If I got a quarter everytime skeletons drinking milk broke, I'd have 6 quarters

**Comment by ATH1909** [comment]
![image](https://user-images.githubusercontent.com/42606352/189814271-75f9fe4d-a180-44ca-be08-d8f25178e577.png)
