### ISSUE TITLE
tackles are broken

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#69780]
Round ID: [190090](https://scrubby.melonmesa.com/round/190090)

Testmerges: https://github.com/tgstation/tgstation/pull/69078

Reproduction: Tackle someone with tackle gloves. Always fail to knock them down.

I tested this with both gorilla gloves and gripper gloves. Both of them fail to get a knockdown against human opponents, both with jumpsuits on. I tested a dozen times with each and they never will knock down. I think the tackle defense values were changed mistakenly in the recent tackle buff given to moths and lizards.

https://streamable.com/xxuz7l

The odd thing is that against some opponents, the tackles work normally. I think it has something to do with the uniform?

**Comment by timothymtorres** [comment]
Can confirm this was happening to a moth security officer from a round I recently played a few days ago.  He tried test tackling several different people to see if he was able to knock them down without succeeding.  The officer was a giant as well but never got a single tackle despite numerous attempts.
