### ISSUE TITLE
Carrying an npc on your back breaks door animation

### ISSUE THREAD

**Issue by AterSoul** [tgstation/tgstation#69784]
Reporting client version: 514.1587

**Comment by msgerbs** [comment]
I don't think this is related to door animations, I have seen this randomly happening for a while and just forgotten to report it.

**Comment by msgerbs** [comment]
> Report details a little lacking

So what I've seen, which I think they're talking about, is where doors will randomly not "open" visually, and you end up just walking through an apparently closed door.

**Comment by Time-Green** [comment]
There is no information. Either update this issue and alert me or make a new one
