### ISSUE TITLE
Auxiliary Base does just not work on Icebox

### ISSUE THREAD

**Issue by Vanadiom** [tgstation/tgstation#69787]
## Round ID:
[190104](https://scrubby.melonmesa.com/round/190104)

## Testmerges:
#69240 

## Reproduction:
1. Build your super awesome aux base in the auxilary room that is on Icebox (Either for no reason or because we didn't know it's unusable)
2. Try to random launch it because you are too lazy to choose a location.
2.1. Be disappointed because it does not work.
3. Take your destination tagger down into the icemoons caves (z level -1/-2)
3.1. Try to find a location to drop your cool base
3.2. Find no location (even after clearing big spaces in multiple locations)
4. (Optional) Cry.

**Comment by Rhials** [comment]
I would like to add that, unless something had changed, you can get the auxillary base to drop if you clear out enough space and use the location remote...

...inside of the lavaland ruin

**Comment by Profakos** [comment]
https://github.com/tgstation/tgstation/pull/69501 Fix has been up for a while, waiting for merge. Clearly bluespace is what lets you make it squeeze into caves and huts. :y
