### ISSUE TITLE
you will not wake up if you use the collapse emote as a pai

### ISSUE THREAD

**Issue by a-bat-named-sloth** [tgstation/tgstation#69797]
Reporting client version: 514.1585

## Round ID:
[190130](https://scrubby.melonmesa.com/round/190130)

## Reproduction:

if you use the collapse emote as a pai you will not wake up after some time like normally

be a pai and use a keybind for the collapse emote

this will probably be the same for emotes like faint

**Comment by timothymtorres** [comment]
Duplicate of #66760
