### ISSUE TITLE
big engines look weird on NTSS Independence

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#69804]
Reporting client version: 514.1585

## Round ID:
[190168](https://scrubby.melonmesa.com/round/190168)

## Testmerges:
- [Macro optimizes SSmapping saving 50% ](https://www.github.com/tgstation/tgstation/pull/69632)
- [Completely refactors hallucinations, and also adds a few ](https://www.github.com/tgstation/tgstation/pull/69706)

## Reproduction:
![image](https://user-images.githubusercontent.com/12635164/189406769-1a0e60f0-39cf-448d-a956-b4c3d850e5a9.png)
probably they shouldn't be there

**Comment by Maurukas** [comment]
I wasn't able to replicate this locally. Is this still happening? Or are they only weird in certain situations?

**Comment by norsvenska** [comment]
no longer an issue, i don't think

**Comment by Sadboysuss** [comment]
doesn't seem to be an issue anymore
