### ISSUE TITLE
You can pick yourself up as bread, runechat moves to your hand

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#69809]
## Reproduction:
Smite a player into bread. The player can pick themselves up with the LEFT hand only. Their runechat speech also floats from the bread in their own hand, in addition to their proper location.

![image](https://user-images.githubusercontent.com/83487515/189424428-31cc7209-02fa-40ee-b53a-c4222d562321.png)

**Comment by san7890** [comment]
In my reproduction of this as I solved the issue, I found that you could do it from either hand at most any time.
