### ISSUE TITLE
Ian duplicates while under deadchat control

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#69815]
## Reproduction:

When Ian is controlled by deadchat, if someone picks him up into their hand. If deadchat moves Ian while in their hand, it makes another Ian. Rinse and repeat until you have a ton of Ians.

![image](https://user-images.githubusercontent.com/83487515/189453531-9c7e3c1f-a6b9-4207-9b8f-5f0ec4ad36b3.png)

**Comment by SomeRandomOwl** [comment]
Too add onto this, if one of the duplicated ians are dropped it will teleport ian to that posistion

**Comment by dopamiin0** [comment]
Seems a dupe of #69521 and should be resolved by the same PR that resolves that.

**Comment by lessthnthree** [comment]
Closing this as yes it seems to be a dupe that I couldn't find.
