### ISSUE TITLE
Brains show "Name" (As ID worn) with a gibbed body.

### ISSUE THREAD

**Issue by tgsAvylaar** [tgstation/tgstation#69828]
## Round ID:[190229](https://scrubby.melonmesa.com/round/190229)

[image](https://user-images.githubusercontent.com/63151598/189494779-00e1e467-c1b9-4532-91de-e37b72187a14.png)
[image](https://user-images.githubusercontent.com/63151598/189494783-210d3adc-2a51-4147-8f7c-89ccd946dd99.png)

https://user-images.githubusercontent.com/63151598/189494779-00e1e467-c1b9-4532-91de-e37b72187a14.png

## Reproduction:

Wear someone else's id without a PDA, while not hiding your own identity (eg. no gasmask etc).
Your brain, while gibbed shows your own name, (as ID worn).
Is this intended?

**Comment by ShizCalev** [comment]
fixing this would potentially reveal lings.

**Comment by SuperNovaa41** [comment]
Close it then coward
