### ISSUE TITLE
Etherial crystals can be broken before crystalizing extremely easily.

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#69829]
Reporting client version: 514.1585

## Round ID:
[190235](https://scrubby.melonmesa.com/round/190235)

## Testmerges:
- [Changed Supermatter Internal Math + UI Additions](https://www.github.com/tgstation/tgstation/pull/69240)

## Reproduction:
Die as ethereal, be hit with any item besides fists 3 times, and be unable to crystalize.
I know the whole not being able to crystalize after your corpse is hit is intentional, but the fact that you can be hit with a **fucking screwdriver** three times and not be able to crystalize is ridiculous.

tell me cope and seeth and all that stuff but I just wanna make sure that this is at least intentional for it to be so weak.

**Comment by timothymtorres** [comment]
Crystallization is supposed to be against environmental threats and not prevent other players from killing you.  See #68184

**Comment by LemonInTheDark** [comment]
![image](https://user-images.githubusercontent.com/58055496/189506443-766bc66c-f74a-487a-b2c8-3ebe404b5771.png)
Cope and seethe, sometimes you just die.

Get owned.

**Comment by LemonInTheDark** [comment]
Well I say that, screwdrivers do 5 damage a hit, but I think you may be slightly biased

**Comment by LemonInTheDark** [comment]
I do notice the damage count doesn't really... reset when you crystalize, maybe that's part of the trouble?

**Comment by ZAMODA** [comment]
this really was a seething post but im glad i was able to reveal a potential problem with it
