### ISSUE TITLE
Table shoves in combat logs can lack actor information

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#69837]
Reporting client version: 514.1585

## Round ID:
[190263](https://scrubby.melonmesa.com/round/190263)

## Testmerges:
- [Changed Supermatter Internal Math + UI Additions](https://www.github.com/tgstation/tgstation/pull/69240)

## Reproduction:

Table shoves can generate messages such as the following, which are somewhat lacking in key details (like, who shoved)

```[2022-09-11 03:34:44.266] ATTACK: [table] shoved Nope22/(Christopher Priebe) with onto the table (table) (NEWHP: 100)  (Security Office (116,172,2))```

**Comment by msgerbs** [comment]
Tables are the enemy
