### ISSUE TITLE
Bloody feet remained after feet were gone

### ISSUE THREAD

**Issue by itseasytosee** [tgstation/tgstation#69843]
## Round ID:
Tested locally

![image](https://user-images.githubusercontent.com/55666666/189554676-119a25e1-3c41-44c8-b712-e260a726db39.png)

I don't know what this is. My guess is its wounds sprites lingering past the limb being removed.

**Comment by Sealed101** [comment]
no repro
no round id because it's local testing
probably not an issue anymore since it's been two years already

vine boom
