### ISSUE TITLE
Prosthetic limbs take damage from vacuum

### ISSUE THREAD

**Issue by KirbyDaMaster** [tgstation/tgstation#69858]
## Reproduction:
Have the quirk prosthetic limb and enter a vacuum. The vacuum damages all body parts regardless of type.

**Comment by itseasytosee** [comment]
Is this only for surplus limbs? They don't have any damage reduction unlike normal robot parts.

**Comment by KirbyDaMaster** [comment]
> Is this only for surplus limbs? They don't have any damage reduction unlike normal robot parts.

I believe so, but it doesnt make sense for a prosthetic to be damaged from low pressure. (maybe if the vacuum was strong enough it could pull the prosthetic off hehe) just not damaged.

**Comment by ShizCalev** [comment]
prosthetic limbs aren't meant to replace needing a spacesuit.
