### ISSUE TITLE
Nonstation ore silos that are mounted on shuttles lose connection to lathes when shuttle moves

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#69863]
Reporting client version: 514.1585

## Round ID:
[190361](https://scrubby.melonmesa.com/round/190361)

## Testmerges:
- [Changed Supermatter Internal Math + UI Additions](https://www.github.com/tgstation/tgstation/pull/69240)

## Reproduction:

1. shitcode
2. take ore silo
3. put on whiteship
4. use KC13 boards to make ancient lathes
5. link to whiteship silo
6. lathes are on whiteship, alongside silo
7. ship move
8. lathe disconnect
9. what

**Comment by the-orange-cow** [comment]
It probably has something to do with when the ided when they made the ORM have to be on the same zlevel as the ore silo.

**Comment by Mooshimi** [comment]
Please correct me if I am wrong but, this is:
Moving orm and silos off station via whiteship to another z level
Is the question: 
Why does it not work if they're both moved simultaneously?

**Comment by Mooshimi** [comment]
> It probably has something to do with the ided when they made the ORM have to be on the same zlevel as the ore silo.

Im fairly sure this is absed on station z levels not the silo z level

**Comment by Mooshimi** [comment]
> At the very least its an oversight.

based on the ore silo moving along on the same z with the orm?

**Comment by Mooshimi** [comment]
cc @JohnFulpWillard

**Comment by JohnFulpWillard** [comment]
ore silos disconnect everything when they move z-level, it is an oversight that it disconnects machines that move z-level with them though.

**Comment by Addust** [comment]
i fucking hate the ided PR that made this bug
