### ISSUE TITLE
Bileworms are broken

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#69867]
Reporting client version: 514.1566

## Round ID:
[190372](https://scrubby.melonmesa.com/round/190372)

## Testmerges:
- [Changed Supermatter Internal Math + UI Additions](https://www.github.com/tgstation/tgstation/pull/69240)

## Reproduction:
Fight bileworm, notice he can't spit projectiles.
Profit?

He makes the attacking sound but doesn't spit anything.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/254bbc27486692b5f77b980fc5f44157492c2987/code/datums/ai/basic_mobs/basic_ai_behaviors/try_mob_ability.dm#L13-L17

iirc i saw something in runtime logs the other day along the lines of `var/mob/living/target = controller.blackboard[target_key]` is resolving as /datum/ai_behavior/try_mob_ability, and runtiming w/ `"/datum/ai_behavior/try_mob_ability".stat`

**Comment by ArcaneDefence** [comment]
https://github.com/tgstation/tgstation/issues/69608
