### ISSUE TITLE
lesser dragon form cant spit fire

### ISSUE THREAD

**Issue by 1393F** [tgstation/tgstation#69877]
Reporting client version: 514.1584

## Round ID:
[190385](https://scrubby.melonmesa.com/round/190385)

## Testmerges:
- [Changed Supermatter Internal Math + UI Additions](https://www.github.com/tgstation/tgstation/pull/69240)
- [Removes overlay queuing, saves 6/7 seconds of initialize. Lightly modifies stat tracking macros](https://www.github.com/tgstation/tgstation/pull/69696)

## Reproduction:
try left clicking, right clicking, no fire
not entirely sure, but I'm pretty sure it used to be able to

**Comment by newfren** [comment]
it also can't swoop, which it used to be able to do with alt click

**Comment by the-orange-cow** [comment]
I think theyvchanged swoop from alt click to a button ability.  I preffered alt click

**Comment by rasepretep** [comment]
I've definitely swooped using both button ability and I think ctrl+click. Breathing fire does not work, though.
