### ISSUE TITLE
Market Crash event does not work

### ISSUE THREAD

**Issue by Rhials** [tgstation/tgstation#69893]
## Testmerges:

[Micros the lighting subsystem (Saves a second of init) by LemonInTheDark](https://github.com/tgstation/tgstation/pull/69838)
[ Removes overlay queuing, saves 6/7 seconds of initialize. Lightly modifies stat tracking macros by LemonInTheDark](https://github.com/tgstation/tgstation/pull/69696)
[ Macro optimizes SSmapping saving 50% by LemonInTheDark](https://github.com/tgstation/tgstation/pull/69632)
[ Completely refactors hallucinations, and also adds a few by MrMelbert](https://github.com/tgstation/tgstation/pull/69706)

(These may or may not be relevant, as the issue persisted on local)

## Reproduction:

Trigger market crash event on local.

See no results, prices remain unchanged. Problem persists with a debug crew.

The only time I did see increased prices was when creating a new vendor via buildmode while the economy was tanked, which reflected the increased prices but did NOT change back to pre-crash prices after the event.

At no point in this process (or at least during testing) are any runtime errors thrown.

Confirmed that prices do not get modified at any point when tested on a live round.

**Comment by ArcaneMusic** [comment]
Fixed with #77055.
