### ISSUE TITLE
Looping sounds max_loops var is broken

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/tgstation#69903]
## Reproduction:
The max_loops var is currently not used in TG, but is supposed to set a max number of loops for the sound to iterate before stopping.
If this var is used however, the looping sound will end before it plays at all.

This is due to line 53, where the initial timer when the sound first starts doesn't include a start_time arg. In the sound_loop proc this is supplied as world.time.

One line fix: Adding this arg to the initial addtimer fixes this issue.
I found this issue and fixed it on TGMC, but I don't have the tg repo I can't be assed to get it and pr it on this side.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/TerraGov-Marine-Corps/pull/10954

**Comment by ShizCalev** [comment]
Actually, looks like this was fixed already on our end.... about a year and a half ago. #59284

**Comment by Lumipharon** [comment]
Ah cool, you broke sound_loop into two procs, I missed that.
