### ISSUE TITLE
Syriniver doesn't turn into musiver properly

### ISSUE THREAD

**Issue by dopamiin0** [tgstation/tgstation#69910]
## Reproduction:

inject syriniver into someone who should be affected normally (high liver health etc)
cry as it does not turn into musiver and they get drastically less healing and take a shitton of liver damage

sorry if this can't be recreated, i swear ive been having it as an issue for a few weeks and just kept forgetting to make an issue report, syriniver is normally my go-to for toxin healing and this shit has made it way fucking worse, if this was a weird niche issue and it cant be created i apologize but if i dont make this post ill forget

**Comment by dopamiin0** [comment]
note to self to add more useful info later because i could have sworn i had some useful insight but i dont remember it right now. apologies for the low quality post even by my rock-bottom standards

**Comment by dopamiin0** [comment]
oh also nooartrium doesnt FUCKING WORK. unsure if related

**Comment by Mooshimi** [comment]
Related code:
https://github.com/tgstation/tgstation/blob/2ff790863981eda4e2cf1fe2dcdc65040497f0b2/code/modules/reagents/chemistry/reagents/cat2_medicine_reagents.dm#L369-L451
PS a round number would be very helpful

**Comment by dopamiin0** [comment]
> Related code:
> 
> https://github.com/tgstation/tgstation/blob/2ff790863981eda4e2cf1fe2dcdc65040497f0b2/code/modules/reagents/chemistry/reagents/cat2_medicine_reagents.dm#L369-L451
> 
> PS a round number would be very helpful

yeah i know but i was half asleep when i wrote this and just wanted to get it up, will add a round number if/when i can recreate it on live, been having connection issues recently

**Comment by private-tristan** [comment]
yeah I also have had this issue for the past months, you can likely just reproduce by playing med doc and injecting syriniver into someone and watching them not get much musiver.

**Comment by dopamiin0** [comment]
round 191139 works but you can see this in literally every round of using syriniver. this was just the first round I remembered to write down the number, this has been constantly happening
