### ISSUE TITLE
Reagent containers do not visually update when crafting with resources from them

### ISSUE THREAD

**Issue by msgerbs** [tgstation/tgstation#69935]
## Testmerges:

- #69775 
- #69115
- #69000

## Reproduction:

Be chef. Fill beaker with milk or some other reagent used in crafting. Craft a recipe using that reagent. Observe that the beaker does not visually change even if it is now empty.

Probably affects more than just beakers, that's just the one I noticed it on. Probably just needs to call `update_appearance()` or whatever it is after crafting.

**Comment by newfren** [comment]
definitely also effects glasses etc
