### ISSUE TITLE
Overlay_lighting component is showing light on backpack slots/your inventory instead of your mob.

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#69936]
Reporting client version: 514.1585

## Round ID:
[190512](https://scrubby.melonmesa.com/round/190512)

## Testmerges:
- [Completely refactors hallucinations, and also adds a few ](https://www.github.com/tgstation/tgstation/pull/69706)
- [Macro optimizes SSmapping saving 50% ](https://www.github.com/tgstation/tgstation/pull/69632)
- [Micros the lighting subsystem (Saves a second of init)](https://www.github.com/tgstation/tgstation/pull/69838)

## Reproduction:
ok so do we all remember this issue https://github.com/tgstation/tgstation/issues/69737

well

![image](https://user-images.githubusercontent.com/12635164/190347541-9d1bae32-f79c-4c38-bfb0-46d46697f983.png)
gun in my belt, light in my belt
![image](https://user-images.githubusercontent.com/12635164/190347597-853e3823-1626-4a89-99b1-d761c948e8d5.png)
gun in my hand, light in my hand
![image](https://user-images.githubusercontent.com/12635164/190347646-350c241c-3d8f-4e60-9dbf-17736fdc548e.png)
gun in my hand but hovered over my belt, light at both places
![image](https://user-images.githubusercontent.com/12635164/190347788-2b2099a9-831c-40e6-9931-888ed20f8eca.png)
gun in my bag, light in my bag

this illuminates things for me, sorta

I think 

![image](https://user-images.githubusercontent.com/12635164/190348007-29f4f95e-b408-4f6e-8082-bd8dfe0494ac.png)
the action button for the gun is also all sorts of fucked

this happens whether the light is on or off

**Comment by ShizCalev** [comment]
To clarify for those reading, the light overlay is illuminating underneath where the gun sprite is on the screen, not centered on the player.

**Comment by msgerbs** [comment]
Were these lights you picked up from a ruin somewhere or where did they come from?

**Comment by newfren** [comment]
this light was the torch that starts in the miner locker on icebox attached to a pka

**Comment by msgerbs** [comment]
Huh... Ok then. That's weird.

**Comment by ShizCalev** [comment]
another thing with the same issue;
spawn `/obj/item/dualsaber/red`
turn it on
throw it
turn it on again
![image](https://user-images.githubusercontent.com/6209658/193424444-43326fc1-2b8c-49eb-bdc0-783790335e70.png)

**Comment by ShizCalev** [comment]
Something with /datum/component/overlay_lighting

**Comment by ShizCalev** [comment]
Seeing current_holder being set to the wrong atom after being thrown

**Comment by ShizCalev** [comment]
Throwing it is deregistering the movable_moved signal 
![image](https://user-images.githubusercontent.com/6209658/193425329-32de4033-5d20-40e4-aefc-31b68ddd1e6e.png)

![image](https://user-images.githubusercontent.com/6209658/193425333-6ead012c-16fa-44ea-b418-6d5f0c7b7cc5.png)

**Comment by ShizCalev** [comment]
![image](https://user-images.githubusercontent.com/6209658/193425498-427cde30-4d68-4f45-b928-946cfecc6e0f.png)
Thisssssssss might be it.
