### ISSUE TITLE
Say broke for living mobs

### ISSUE THREAD

**Issue by RigglePrime** [tgstation/tgstation#69942]
## Round ID:

[R190542](https://tgstation13.org/parsed-logs/terry/data/logs/2022/09/15/round-190542/) (Terry)

## Testmerges:

#69897
#69240

## Reproduction:

[Detailed explanation](https://www.youtube.com/watch?v=fq3abPnEEGE)

All I know is that there's a bunch of runtimes in `living_say.dm`, and nobody could speak for a while. It fixed itself somehow.

Quote from tattle:

> the way speaking broke was that you could talk on the radio, but any local talking, both runechat and goonchat, didn't display
> or tgchat? whatever's in the box

**Comment by SuperNovaa41** [comment]
Seems `prefs` was null for... all clients? 
`[2022-09-15 17:47:04.472] runtime error: Cannot read null.chat_toggles`
