### ISSUE TITLE
Ashtorm does not have any graphics

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#69945]
Reporting client version: 514.1588

## Round ID:
[190556](https://scrubby.melonmesa.com/round/190556)

## Testmerges:
- [Multiz Rework: Human Suffering Edition (Contains PLANE CUBE)](https://www.github.com/tgstation/tgstation/pull/69115)

## Reproduction:
I havent seen it first hand, but ive gotten several reports of players dying from this issue.
 I imagine to reproduce this would be to be at lavaland and see that theres no ash falling from the sky.

**Comment by dragomagol** [comment]
Likely from #69115

**Comment by Baskett55** [comment]
yeah i first got a report of a guy dying from this yesterday, if that was tm'd by then

**Comment by LemonInTheDark** [comment]
aight, fixed, thank you

**Comment by Baskett55** [comment]
> aight, fixed, thank you

are you talking about #69944 ?
