### ISSUE TITLE
Fun fish friends dont work :(

### ISSUE THREAD

**Issue by KommandantJackal** [tgstation/tgstation#69950]
## Round ID:
[190562](https://scrubby.melonmesa.com/round/190562)

## Reproduction:

Buy 14 dehydrated space carp from unlink 
Pet then all inhand 
Rehydrate them via fire extinguisher
Cry as they all sit in a corner and do fucking nothing

**Comment by VladinXXV** [comment]
> ```
> /obj/item/toy/plush/carpplushie/dehy_carp/attack_self(mob/user)
> 	src.add_fingerprint(user) //Anyone can add their fingerprints to it with this
> 	if(!owned)
> 		to_chat(user, span_notice("You pet [src]. You swear it looks up at you."))
> 		owner = user
> ```
> 
> ```
> 	if(owner)
> 		var/list/factions = owner.faction.Copy()
> 		for(var/F in factions)
> 			if(F == "neutral")
> 				factions -= F
> 		M.faction = factions
> ```
> 
> Apparently it seems like you're supposed to use it in hand first to make it hostile to everyone (excluding you)

According to their post, they did. "Pet then all inhand". When you use it in hand, you "pet" the plush.

**Comment by Jackal-boop** [comment]
Yeah, I pet then all. I ahelped after and the admin said there waa a bug with them assigning freidnly or foe teams
