### ISSUE TITLE
Some material put in a mortar and pestle can be ground indefinitely 

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#69966]
Reporting client version: 514.1588

## Round ID:
[190630](https://scrubby.melonmesa.com/round/190630)

## Testmerges:
- [Multiz Rework: Human Suffering Edition (Contains PLANE CUBE)](https://www.github.com/tgstation/tgstation/pull/69115)
- [Tramstation: Modular Maintenance Insanity](https://www.github.com/tgstation/tgstation/pull/69000)

## Reproduction: Get a mortar and pestle, put in a bluespace crystal, continually grind it.
In testing I got like 60u of bluespace powder before i stopped. then i put a crystal in a grinder and grinding it gives me 40u.
As far as i know you can grind it forever to get rare chemicals like ground bluespace or whatever you could from grinding.

**Comment by antropod** [comment]
same with glass
