### ISSUE TITLE
Missing texture near tram vault in space

### ISSUE THREAD

**Issue by dopamiin0** [tgstation/tgstation#69969]
## Testmerges:

[#69115: 'Multiz Rework: Human Suffering Edition (Contains PLANE CUBE)' by LemonInTheDark at commit 811362bd0d](https://www.github.com/tgstation/tgstation/pull/69115)
[#69000: 'Tramstation: Modular Maintenance Insanity' by MMMiracles at commit 75c0124af2](https://www.github.com/tgstation/tgstation/pull/69000)
## Reproduction:

![image](https://user-images.githubusercontent.com/112458553/190844840-e31bdf00-21de-4a2b-9a02-31cd0892d6e6.png)

**Comment by timothymtorres** [comment]
CC @MMMiracles

**Comment by MMMiracles** [comment]
fixed it in the testmerged pr this can be closed

**Comment by timothymtorres** [comment]
Fixed in #69000
