### ISSUE TITLE
Newscasters, fire alarms and probably more wall mounted objects are partially visible through floors when next to a glass floor tile

### ISSUE THREAD

**Issue by NamelessFairy** [tgstation/tgstation#69971]
## Testmerges:
#69897
#69240

## Reproduction:

Its extremely faint so I recommend turning off all lights and equipping night vision goggles first. Go to a Mutli-Z station and look at the floor above a newscaster or fire alarm where the newscaster/fire alarm is placed on a glass tile but is pixel offset so it shouldn't be visible, you'll see this.
Newscaster:
![image](https://user-images.githubusercontent.com/40036527/190862747-8fc7273c-b25d-4b99-a857-7febc1f406cb.png)
Fire Alarms (Extra alarms for added visibility):
![image](https://user-images.githubusercontent.com/40036527/190862855-224133b6-f17f-47a6-9346-896967588740.png)

**Comment by private-tristan** [comment]
#65800
