### ISSUE TITLE
The decal painter's right and left inhands are backwards

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#69980]
Reporting client version: 514.1583

## Round ID:
[190665](https://scrubby.melonmesa.com/round/190665)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/190882370-cd382939-ed62-423b-a619-d63a15adf2c8.png)
![image](https://user-images.githubusercontent.com/66640614/190882371-a7da9412-9cf6-4364-aad5-45d6b41306b9.png)

**Comment by ShizCalev** [comment]
Will be fixed by #70037
