### ISSUE TITLE
emcloset still hard deletes

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#70047]
https://github.com/tgstation/tgstation/actions/runs/3093573073/jobs/5006092585

#69889 didn't fix it, a reminder to everyone that if you don't include a regression test with your fixes, **you have no idea if they're fixed or not**. Someone should make a closet that always deletes, rather than the 1% chance of emcloset, so that it'll ALWAYS fail in unit tests.

**Comment by LemonInTheDark** [comment]
It's not just the 1% chance of deletion, it's something else.
We do not get this failure with a qdeleted check in the test and a 100% chance of deletion in the closet. somethin weird's goin on

**Comment by Mothblocks** [comment]
The first goal should be getting a test that fails 100% of the time is my point

**Comment by JohnFulpWillard** [comment]
duplicate of https://github.com/tgstation/tgstation/issues/69732 >:(
