### ISSUE TITLE
Are nuke auth pinpointers supposed to be destroyable?

### ISSUE THREAD

**Issue by Syndro101** [tgstation/tgstation#70040]
Reporting client version: 514.1588

## Round ID:
[190777](https://scrubby.melonmesa.com/round/190777)

## Reproduction:
Grab the nuke auth pinpointer and shove it in an auto lathe, it will get turned into base materials.

(again I'm not sure if this is supposed to happen, but it seems weird.)
(please feel free to tell me I'm wrong.)

**Comment by optimumtact** [comment]
correct
