### ISSUE TITLE
Cannot link ore silo with autolathe using multitool

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#70041]
Reporting client version: 514.1588

First time reporting a bug here so please let me know if more information is required

RoundID :This happened when i ran a private server using the latest [git build](https://github.com/tgstation/tgstation) [which i downloaded yesterday] hence its round ID was NULL

**Frequency**
Every time

## Reproduction:
1) build an ore silo

2) left click on it with a multi tool to log it to the buffer

3) left or right click with the same multitool on the department autolathe. 

**Result**
Eats up the multitool for material every time and doesn't link it

**Expected Result**
the autolathe should first check if the multi tool has anything in its buffer and if it does link it. If the machine was already linked or if the multitool buffer is empty then the autolathe should consume the multitool for material

**Comment by rasepretep** [comment]
Hasn't this always been the case? As in, only departmental protolathes being linkable, while the cargo autolathe always required mats to be loaded in manually.

**Comment by SyncIt21** [comment]
I did not know this has always been the case since today when i experimented with ore silo. Well then i agree this isn't a bug however it would be convenient if autolathes could be linked without being department dependent.

**Comment by msgerbs** [comment]
Suggestions for new functionality should be discussed on the forums. I'm not really sure why autolathes work differently to be honest.
