### ISSUE TITLE
The Build Your Own Shuttle Doesn't Dock At The Station, Thus Ruining It's Purpose

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#70050]
Reporting client version: 514.1585

## Round ID:
[190883](https://scrubby.melonmesa.com/round/190883)

## Testmerges:
- [Adds The Ducky Shoes, From Paradise](https://www.github.com/tgstation/tgstation/pull/69986)
- [TGUI for Techfabs II: The Great Recategorizing (AND ICONS) (AND MECHFABS) (AND AUTOLATHES)](https://www.github.com/tgstation/tgstation/pull/69990)
- [Multiz Rework: Human Suffering Edition (Contains PLANE CUBE)](https://www.github.com/tgstation/tgstation/pull/69115)

## Reproduction:

Order the Bring Your Own Shuttle.

Note how it stays at CentCom (arrows drawn to illustrate that it is indeed CentCom and not the station. Disregard the ores and pickaxes, I was doing something funny with gibtonite):

![image](https://user-images.githubusercontent.com/34697715/191414196-8657776e-5553-4964-a5c3-099788ac1592.png)

Then look at the station, and notice how it is not there:

![image](https://user-images.githubusercontent.com/34697715/191414277-23282057-eb6c-4600-9efc-be29b77ac94f.png)

Did something recently touch shuttlecode to break this? Didn't see any relevant runtimes.

**Comment by msgerbs** [comment]
I might've broken this in #69901

**Comment by msgerbs** [comment]
Yeah I definitely broke this. Fuck. I'll fix it.
