### ISSUE TITLE
You can run an SM in the snow of Icebox

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#70058]
You can set up an SM shard in the snow of icebox, with no cooling or infrastructure, and it works.

![image](https://user-images.githubusercontent.com/83487515/191602749-d3ad7539-34ec-4f0d-9aad-5db517b91646.png)

![image](https://user-images.githubusercontent.com/83487515/191602819-cad4ef27-230a-42ec-8c29-ffb503c88a9b.png)

**Comment by Jackal-boop** [comment]
not really a bug, you can run a SM in the halls of most stations aslong as you keep the airlocks closed

**Comment by lessthnthree** [comment]
More of an oversight. Out in the snow the plasma can just dissipate. In a hall the scrubbers aren't set so it'd eventually build. But snow SM or hallway SM shouldn't be a thing.

**Comment by moocowswag** [comment]
Pretty sure you could also do a lavaland sm aswell.

**Comment by msgerbs** [comment]
> 



> Pretty sure you could also do a lavaland sm aswell although thats probably more volatile.
> 
> From what i can tell it doesn't really matter how much plasma or oxygen youre generating in an unclaimed/wild turf, the atmos is going to quickly and constant be set to whatever that out door area is meant to be.

I believe you're right, and I'm not really sure what can be done to fix that (or if anything even should be). Unfortunately Icebox's gas mix is pretty damn ideal for at least a low-power SM, idk how well this would hold up with a ton of emitters hitting it.

**Comment by private-tristan** [comment]
imo if a engineer is willing to dedicate 30~ mins making a supermatter shard with tesla coils and emitter(s) in icebox wastes they deserve all the power it will give (judging by the picture, its about slightly less power output than the regular supermatter)

even better if the icebox atmos has miasma :eyes:

**Comment by msgerbs** [comment]
tbh I'm inclined to call this "working as designed". It's just how the SM interacts with the preset gasmix of Ice Box. If somebody really wants to tackle this as a balance issue they can but I don't think it's really a bug to be fixed.
