### ISSUE TITLE
Mining Shuttle on Tramstation not working

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#70100]
Reporting client version: 514.1585

## Round ID:
[191061](https://scrubby.melonmesa.com/round/191061)

## Reproduction:

Miner goes to use mining shuttle at beginning of round, shuttle cannot be moved because something is occupying its destination. Public mining shuttle, for inexplicable reasons is docked at the mining shuttle lavaland dock. Move public mining shuttle to public lavaland dock. Regular mining shuttle doesn't move to now clear spot, in fact attempting to move the mining shuttle moves the public shuttle. Graphics of space outside mining shuttle show motion despite the stationary nature of the shuttle. Eventually both shuttles wind up on lavaland. Attempting to use the regular mining shuttle, which had just made the trip down, results in the public mining shuttle going back to the station.

**Comment by msgerbs** [comment]
What server was this on? PR #69836 was just merged to fix this.

**Comment by san7890** [comment]
> What server was this on? PR #69836 was just merged to fix this.

Bagil, running commit https://github.com/tgstation/tgstation/commit/ec6e5b558858d675801762dc0fc4bd8419cf12c4, which contains the changes made in your PR.

**Comment by msgerbs** [comment]
Fuck.

**Comment by msgerbs** [comment]
The very first shuttle move recorded in the logs was sending the public shuttle from the mining shuttle console, and the user who moved it posted the below video in discord.

`02:21:41 | SHUTTLE | LePiromano/(Lepir Omano) has sent shuttle "mining_common" towards "mining_away", using the mining shuttle console.`

https://user-images.githubusercontent.com/1313921/192081401-1b0ea841-d6a7-4969-9dbc-a6ad4fb8e748.mp4

**Comment by msgerbs** [comment]
Duplicated of #69641

Yeah I reopened it.
