### ISSUE TITLE
you cant read the book of babel if you dont know galactic common

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#70111]
Round ID: [191104](https://scrubby.melonmesa.com/round/191104)
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [45516f474147137d811d26ea72dd98a68953ad9f](https://www.github.com/tgstation/tgstation/commit/45516f474147137d811d26ea72dd98a68953ad9f)
The following pull requests are currently test merged:
[#69838: 'Micros the lighting subsystem (Saves a second of init)' by LemonInTheDark at commit 9f8144427a](https://www.github.com/tgstation/tgstation/pull/69838)

Local commit: 7c22c8f1f975e32446722b504d70c381d2fe97d1
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1

supposedly the book of babel is "written in countless tongues". but you can only read it if you know galactic common, which means ash walkers cant read it

**Comment by ShizCalev** [comment]
lmao

**Comment by timothymtorres** [comment]
Wrong, this has nothing to do with language or galactic common.  Ash walkers do not have literacy at roundstart.  They can gain it by getting the clever mutation from a DNA scanner, but until they do they cannot read books.  This is 100% deliberate and something I consulted with the person who created ash walkers about part of their lore.  Basically they are lavaland hillbillies who are illiterate.

Not a bug.

**Comment by Jackal-boop** [comment]
:(
