### ISSUE TITLE
Certain areas in the station of icebox are fucked

### ISSUE THREAD

**Issue by Pook-gif** [tgstation/tgstation#70123]
Reporting client version: 514.1588

Round ID:
[191138](https://scrubby.melonmesa.com/round/191138)

Xenobio, medbay and other areas of the station are having this issue. Map is Icebox
![image](https://user-images.githubusercontent.com/110084965/192132170-0db7efe2-ecb6-4018-b5d9-ae0029f11a21.png)
![image](https://user-images.githubusercontent.com/110084965/192132175-9b5b838a-a89b-4a53-a366-d54a75993980.png)
It looks like the station its self is being dragged to hell.

**Comment by Time-Green** [comment]
Caused by #69642, oops

**Comment by OrionTheFox** [comment]
Can this please be used as a feature in some way this looks amazingly terrifying
