### ISSUE TITLE
Prosthetic replacement (head) surgery on HARS'd body fails and puts head into surgeons VV contents

### ISSUE THREAD

**Issue by RandomlyEvil** [tgstation/tgstation#70125]
Reporting client version: 514.1588

## Round ID:
[191164](https://scrubby.melonmesa.com/round/191164)

## Reproduction:
Originally found in 191160, retested in Thunderdome on 191164

1- Spawn 2 NPCs, give one HARs
2- Amputate Head from second NPC
3- Perform Prosthetic Replacement surgery on HARS'd corpse with head of second NPC

Surgery fails with a message of "You fail in replacing Unknown's head! Their body has rejected "NPC name"'s head!"

4-  Check your own contents in VV and see that the head is now inside your mob but cannot be found in bag/pockets/etc
![image](https://user-images.githubusercontent.com/109258931/192155505-bbc5044e-3c46-41de-b8aa-f39ab6b8412c.png)

**Comment by msgerbs** [comment]
lol wtf?

**Comment by Kapu1178** [comment]
![image](https://user-images.githubusercontent.com/75460809/192175479-1cf50a7b-6816-43f1-bd1a-2c3bac596c36.png)

**Comment by RandomlyEvil** [comment]
> Dupe of #67590, except with bonus HARS memery

Ah, I didn't see that issue, though the big issue with the head is the accidental round removal when surgery fails.  Head/brain being in your contents means the player cant be recovered unless the doctor knows to ahelp and an admin is available to remove it from their contents.
