### ISSUE TITLE
Grammar error when being cuffed with cable restraints while unconscious.

### ISSUE THREAD

**Issue by dopamiin0** [tgstation/tgstation#70143]
## Reproduction:
![image](https://user-images.githubusercontent.com/112458553/192216381-c042d4ae-b22e-4efb-9e13-0a003a774477.png)

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/8bd7aabe7283acfeb1d2a7dc79c6929a0902b613/code/game/objects/items/handcuffs.dm#L60-L65
