### ISSUE TITLE
A ton of miscellaneous issues with new PDAs

### ISSUE THREAD

**Issue by itsmeow** [tgstation/tgstation#70140]
## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:

This is mainly a courtesy to @JohnFulpWillard

I have spent a lot of time in the PDA code improving it and have discovered quite a few glaring issues downstream. I'd suggest taking a look at some of the more bugfixy changes I've made in https://github.com/BeeStation/BeeStation-Hornet/pull/7550

Mainly related to attaching and sending images, especially as silicon. I've also made a lot of fixes related to the mime PDA as emojis don't show properly inside the app either.

From what I understanding sending photos via PDA does not work *at all* currently. Only on the sender side, receiving them is actually impossible. Also quite a few regressions with ringtones, the item descriptions and custom starting notes, a few general UI improvements, paper scanning improvements (the previous solution is really hacky), photo scanning, a runtime or two, plus a bunch of additional features an polish.

I'm probably not going to have time to port any of it upstream, but I can tell a lot of love is being put into modpcs and PDAs in general, so hopefully this helps give some direction.

**Comment by JohnFulpWillard** [comment]
Messenger has always been a problem and I hope we can make it actually work well, thank you for putting your time into this

> Also quite a few regressions with ringtones

Can you explain this further? I fixed one bug with it but I don't recall any other ones. Do you mean custom ringtones for jobs?

**Comment by itsmeow** [comment]
Yes that and also visible mssages (and thus ringtones) weren't showing if you were holding the PDA. Also silencing the ringtone roundstart for mimes

**Comment by JohnFulpWillard** [comment]
For notekeeping, clown virus seems to have lost their ability to upload viruses to airlocks
https://github.com/tgstation/tgstation/pull/64443
