### ISSUE TITLE
meat floor tiles from a dimensional anomaly (and probably from other sources) don't have inhand sprites

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#70146]
## Testmerges:
sure, some of them, sorry!

## Reproduction:
have a dimensional anomaly spawn and turn shit into meat
remove a floor tile
hold it in your little hands
counterstrike source

probably sheetmeistering meat and making those into tiles will also have no sprite

**Comment by ShizCalev** [comment]
Already being covered by https://github.com/tgstation/tgstation/pull/70037

**Comment by Mooshimi** [comment]
> Already being covered by #70037

apparently done
