### ISSUE TITLE
Screenshot tests doesn't explain what it is.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#70169]

**Comment by Mothblocks** [comment]
Wut? There is a dropdown that says "What is this" and I thought I explained it pretty well to someone who wouldn't know the system like me

![Screen Shot 2022-09-27 at 2 25 42 PM](https://user-images.githubusercontent.com/35135081/192638647-d34bac96-b51c-47e9-af81-c42ff13e9902.png)

**Comment by MrStonedOne** [comment]
That only shows up when it fails, when i was looking into this, i just wanted to figure out why it was still yellow (its not anymore), and was confused on what it is. I'll have to go lookup if there is any way to provide more detailed descriptions on actions that show up in the checks tab.

**Comment by Mothblocks** [comment]
Fair enough.

The closest is https://github.com/tgstation/tgstation/blob/master/code/modules/unit_tests/screenshots/README.md, but we could do with documenting our entire CI pipeline I think
