### ISSUE TITLE
ERT Medical Officer has no Health Analyzer

### ISSUE THREAD

**Issue by msgerbs** [tgstation/tgstation#70187]
## Reproduction:
Spawn as Medical Response Officer. Find injured person. Try to find your health analyzer. Try harder to find your health analyzer. Error 404 health analyzer not found. What kind of medic has a bag full of advanced medical tools but no health analyzer? Cry.

**Comment by Baskett55** [comment]
wouldn't the health analyzer module fit the medical ert more?
