### ISSUE TITLE
Door all access indicator gets parallaxed while on the same layer as it

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#70197]
Reporting client version: 514.1585

## Round ID:
[191363](https://scrubby.melonmesa.com/round/191363)

## Reproduction:

seems to only happen on the lower layers of tram and the like
use the move down verb as a ghost
look at maintenance doors

see this horrid abomination of parallaxing

looking from the bottom left
![image](https://user-images.githubusercontent.com/36141254/192898450-414daeeb-2f44-450d-a620-4d913c00f612.png)
looking from the top right
![image](https://user-images.githubusercontent.com/36141254/192898544-680a2d92-8822-4b09-b1a5-a56251dbd058.png)

**Comment by san7890** [comment]
@LemonInTheDark forgot to mention this because I got lazy, but this was apparent during the test merges of #69115 and reverted back to standard behavior when the test merge was pulled.

**Comment by LemonInTheDark** [comment]
god damn it san
it makes sense, I obviously forgot to catch those. would have thought it'd show in ci tho
easy fix, just need to make them pass parent for their plane
