### ISSUE TITLE
Massive numeber of lavaland mobs(in particular bileworms)

### ISSUE THREAD

**Issue by the-orange-cow** [tgstation/tgstation#70191]
Round ID: [191355](https://scrubby.melonmesa.com/round/191355)
BYOND Version: 514.1588
Server revision compiled on: 
Master commit: [ca1f6846e622f46b31d65e4699b0709f9bb2c42d](https://www.github.com/tgstation/tgstation/commit/ca1f6846e622f46b31d65e4699b0709f9bb2c42d)
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:

Absolutely massive number of lavaland mobs, has been like this for several days, at least.  This includes tendrils, various megafauna, and most importantly BILEWORMS.  You seriously can't walk 10 tiles without seeing three at once, and they just about never stop tracking you.  It is extremely disruptive and overtuned.

**Comment by san7890** [comment]
Duplicate-not-duplicate (similar-ish issue to: #69677).

**Comment by san7890** [comment]
@tralezab this is fixed, right?

**Comment by SyncIt21** [comment]
I'm pretty sure this was fixed somehow. I don't see this problem anymore.

**Comment by LemonInTheDark** [comment]
https://github.com/tgstation/tgstation/pull/70321 fixed this

**Comment by LemonInTheDark** [comment]
I think. I touched cave generation which did tweak mobspawning, but I'm unsure how much of this issue was bileworms and how much was that cavegen change.
It sorta is a feel thing. If lavaland feels alright then we're good, otherwise not
