### ISSUE TITLE
Energy guns colors are very dim

### ISSUE THREAD

**Issue by msgerbs** [tgstation/tgstation#70195]
## Reproduction:
Find an energy gun. It looks normal in hand but the item sprite doesn't, the blue/red color on the gun is barely visible compared to the bright color of inhand. It used to be much more vibrant. Not sure when this changed.

![image](https://user-images.githubusercontent.com/1313921/192895162-151ebe08-bcd3-43f7-a831-32a0103a81d1.png)

**Comment by weesnaw-ops** [comment]
This also prevents you from seeing how much ammo you have left.
