### ISSUE TITLE
counterstrike source in tram maintenance

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#70207]
Reporting client version: 514.1585

## Round ID:
[191388](https://scrubby.melonmesa.com/round/191388)

## Reproduction:
![image](https://user-images.githubusercontent.com/12635164/192998996-ec54c71b-ee2a-40b5-bf2c-78b6378d8215.png)
this was just to the right of aux tool storage

**Comment by san7890** [comment]
@MMMiracles i bet this is a dug asteroid thing

**Comment by ArcaneMusic** [comment]
Which tramstation template is this in?
