### ISSUE TITLE
Icebox Service Hall One Way Airlock

### ISSUE THREAD

**Issue by Breadeagle** [tgstation/tgstation#70200]
Reporting client version: 514.1585

## Round ID:
[191373](https://scrubby.melonmesa.com/round/191373)

## Testmerges:

Not sure how to check, but probably not relevant either, since it was an issue for a good while.

## Reproduction:
In Icebox, not having access allows you to open this airlock in the service hall from the outside (Second level, bottom right airlock) but does not let you open it once you are inside. This is a problem because one way airlocks are generally meant to get crew out of an area, rather than trap them inside. In addition to the round ID posted, I've also noticed it a few times over a week ago, but wasn't sure.
![image](https://user-images.githubusercontent.com/17058929/192919002-25270c3a-0dbd-48fb-bbb3-f8a4f7efddec.png)

**Comment by san7890** [comment]
Probably just a mistake in mapping- best option is to remove the unrestricted helper on that airlock
