### ISSUE TITLE
New protolathe is causing connection timeouts

### ISSUE THREAD

**Issue by Thrugdelmir** [tgstation/tgstation#70205]
## Round ID: 191360 Campbell

Using the new protolathes reliably causes connection timeouts and crashes the game. After the crash I am unable to reconnect to the ongoing round. 

BYOND version: 514.1588

**Comment by msgerbs** [comment]
That's strange, do other TGUI panels do this?

**Comment by Thrugdelmir** [comment]
The Protolathes do that and if I Alt-Click item stacks it happened in the past but not anymore. Just happened again btw and I cannot reconnect/restart back into the game no matter what I try. Allways says connection failed.

**Comment by Mothblocks** [comment]
Please have your issue title be a brief description of the bug

**Comment by Thrugdelmir** [comment]
Looks like the latest change to the Protolathe fixed it.
