### ISSUE TITLE
Blob Tiles of other blobs go over other blobs

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#70201]
Reporting client version: 514.1585

## Round ID:
[191374](https://scrubby.melonmesa.com/round/191374)

## Reproduction:
have 2 blobs try to kill each other no epic blob fight only peaceful blob over blob kind of deal

**Comment by msgerbs** [comment]
This may be intended, or an oversight. I know blobbernauts can't attack any blob either regardless of their loyalty. I don't know if blobs are considered a team antag or not though.

**Comment by SethLafuente** [comment]
> This may be intended, or an oversight. I know blobbernauts can't attack any blob either regardless of their loyalty. I don't know if blobs are considered a team antag or not though.

Pretty sure thats just because blob code hasen't being planned for multiple blobs yet and so it just generalized every blob entity as friendly or not planned at all which is fair in most rounds but if we ever get two blobs this is a problem I consider it an oversight

**Comment by IndieanaJones** [comment]
> Pretty sure thats just because blob code hasen't being planned for multiple blobs yet and so it just generalized every blob entity as friendly or not planned at all which is fair in most rounds but if we ever get two blobs this is a problem I consider it an oversight

Old blob had more than one blob participant, although I never remember an instance where they were close enough to each other to overlap. Perhaps an older boomer might remember how it worked, but I think its unintentional.

**Comment by YakumoChen** [comment]
Blobs are a cooperative antagonist, in legacy having multiple blobs would simply increase the tile requirement for victory. Blobs also previously could split their core to add a second blob player.

Most of this behaviour was removed over the many blob rewrites but they still remain a team in the loose sense.

**Comment by SethLafuente** [comment]
It doesn't seem very fair for balance when 2 blobs come to be for them to overlap since the blob tile max dosent increase and it looks kind of odd so im pretty sure it isn't intended and this is an oversight I can never be to sure though and I don't know who changed blob into its current state

**Comment by YakumoChen** [comment]
Blobs aren't supposed to be able to expand onto other blob tiles no.

**Comment by SethLafuente** [comment]
Cool so we all agree this is most likely an oversight unless stated otherwise by the creator

**Comment by Time-Green** [comment]
Yeah def an oversight. Old blob even had the ability to create new blobs and they just couldn’t spread to each others tiles

**Comment by timothymtorres** [comment]
![dreamseeker_2dI9AicMIB](https://user-images.githubusercontent.com/5195984/216483707-4e6d2334-2ef9-45d0-bd6d-76cb3b4631b0.png)

Looks like this got fixed in #72195
