### ISSUE TITLE
Cant disable Atmos detect with a multitool

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#70212]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
#62055 changed how firealarms work 
You used to be able to deactivate firealarm sensors reacting to atmos by simply multitooling them
This no longer works

![Screenshot_1](https://user-images.githubusercontent.com/95751821/193114549-7b34b3a3-3c69-4b75-beb5-a11202ccc500.png)

This was maybe unintended?

![Screenshot_2](https://user-images.githubusercontent.com/95751821/193115280-245bab82-1925-4816-a231-c521b7d1ca48.png)

**Comment by moocowswag** [comment]
I think a pr that made it so the firelocks themselves scan for shitmos broke it.

Ive even been cutting the wires to fire alarms in hopes of making them not respond to shitmos and they still went off...

**Comment by Mothblocks** [comment]
CC @zxaber

**Comment by zxaber** [comment]
Unintended, I didn't know that was a feature. That said, there's a silicon action at the fire alarms that disables detection across all firelocks in the fire alarm's area, so the multitool behavior could just do that.
