### ISSUE TITLE
Ais Cannot Jump to (camera) Network

### ISSUE THREAD

**Issue by tgsAvylaar** [tgstation/tgstation#70228]
## Reproduction:
![image](https://user-images.githubusercontent.com/63151598/193349637-da6ce53e-f82c-45c0-8681-791dbd379ffd.png)

Hi, 

Ais cannot jump to Camera networks (eg. Mine).
Jump to (camera) network hasn't worked for at the least 2 weeks.

**Comment by msgerbs** [comment]
Can confirm, doesn't work.

**Comment by tgsAvylaar** [comment]
I want to additionally add, that for a certain period during the last month, you could still jump to any of the Station's camera networks, however you couldn't jump to the "Mine" or "Labor" networks, being the only off-station camera networks ais used to be able to connect to. 

Now, the camera network menu doesn't even work, but as I said, there was a period where the menu still worked, but the mine and labor options just did nothing.

Your cameras can still go to lavaland if you manage to track someone (jump to) anyone within a camera's range on lavaland.

**Comment by Sealed101** [comment]
camera lights seem to be in the mystery zone of not being an issue, at least in my testing. they take a while to change their state so you could have just misinterpreted them as not working

**Comment by msgerbs** [comment]
Camera lights are definitely broken. I've left it on for a whole shift as an AI and never noticed anything. I'm assuming this was broken by Lemon's multi-z rework, same as the egun overlays and such.

**Comment by msgerbs** [comment]
I created a separate issue for the camera lights, can you edit it out of this one (or cross it out)? #70240

**Comment by tgsAvylaar** [comment]
> I created a separate issue for the camera lights, can you edit it out of this one (or cross it out)? #70240

Done. Thanks.

Should I close this issue, considering Sealed's fix?

**Comment by msgerbs** [comment]
No, it will close automatically when the fix is merged.
