### ISSUE TITLE
AI camera lights do not work.

### ISSUE THREAD

**Issue by msgerbs** [tgstation/tgstation#70240]
## Reproduction:
AI camera lights are broken. Try to turn on camera light as AI, nothing happens. It used to light up the nearest camera.

Previously reported in #70228 but I wanted to break this out into a separate issue. I believed this was caused by #69115.

**Comment by tgsAvylaar** [comment]
I can confirm that the camera lights do not work.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/bb4cce72e8d0d2121e8f8d084619435f2f50c920/code/modules/mob/living/silicon/ai/freelook/cameranet.dm#L49-L56
is runtiming every time an AI moves their camera.

Caused by #69115

**Comment by ShizCalev** [comment]
can't even test this till #70329 is fixed @LemonInTheDark
