### ISSUE TITLE
You can remove prisoner shoes from yourself with shoesteal

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#70279]
Reporting client version: 514.1588

## Round ID:
[191648](https://scrubby.melonmesa.com/round/191648)

## Reproduction:
Get shoesteal verb, lay down, slap yourself, remove shoes
![image](https://user-images.githubusercontent.com/54517726/193507144-561d767e-20a4-4b85-af08-b6fa2e545081.png)

**Comment by itseasytosee** [comment]
I cried
