### ISSUE TITLE
Split personalities not able to communicate.

### ISSUE THREAD

**Issue by MrrFiish** [tgstation/tgstation#70302]
Reporting client version: 514.1579

## Round ID:
[191709](https://scrubby.melonmesa.com/round/191709)
191705

## Testmerges:
- [Checks Filters For Cross-Station Messages](https://www.github.com/tgstation/tgstation/pull/70273)

## Reproduction:
Pretty simple, basically when you have a split personality, the person who isn't controlling should be able to speak to the one controlling using a communication button in the top left, however in two rounds I played it didn't work in either so we were not able to communicate directly.
To recreate:
1) Get the split personality brain trauma
2) Have someone become your split personality
3) Whoever isn't controlling the body at the time (either one of you) try to talk using the button or just by talking and neither will work.

**Comment by timothymtorres** [comment]
I did just refactor some of the say code for split personalities that was merged a few hours ago.

https://github.com/tgstation/tgstation/blob/5f1ace136c384673a999b188f4dab82e29924cc7/code/datums/brain_damage/split_personality.dm#L166-L168

Based on the ROUND ID and commit ID it doesn't look like my code should have caused this.  (although I have been wrong about this in the past)  

Could also be caused somewhere in: 

https://github.com/tgstation/tgstation/blob/45d2cdb3187e9b1b5a03364907e67916529735f9/code/modules/spells/spell_types/self/personality_commune.dm#L1-L54

CC @MrMelbert

**Comment by MrrFiish** [comment]
Sadly I didn't download the chat and I couldn't find a way to recover it but if I remember correctly I did get this message: "You cannot speak, your other self is controlling your body!" which I'm not sure if that's what your code added but if so then it might have been in the round at the time.
