### ISSUE TITLE
Hand swapping through middle mouse breaks for changelings after their first transformation

### ISSUE THREAD

**Issue by Robustitron** [tgstation/tgstation#70301]
## Testmerges:

[#70273: 'Checks Filters For Cross-Station Messages' by san7890 at commit 06a2e27234](https://www.github.com/tgstation/tgstation/pull/70273)

## Reproduction:
1) Be a ling 
2) Try swapping hands with middle-mouse, it generally works
3) Steal someones genome
4) Transform into anyone thats not you (or maybe even yourself)
5) Middle mouse hand swapping broken forever, you have to manually click the empty space of your hand slots to switch hands now, which can be hard when holding things, very annoying, you effectively need to fight one handed. Middle mouse hand switch -may- still work exclusively while the mouse is over visible or non-visible (black/obscured) tiles, or not at all (check this if you're trying to reproduce it).
6) Ask an admin to help fix it, if they manage it by respawning your mob or something, itl simply break again on the next transform.

This has been around for a pretty long time and it's annoying to have to play one handed whenever I'm a ling, pixel hunting the background of each hand slot isnt feasible during a fight and I'm left carefully managing one hand.

**Comment by newfren** [comment]
does hitting x break as well, or is it just the middle mouse hotkey

**Comment by necromanceranne** [comment]
likely because all ling powers are a 'string' ability and those have a predefined use for the middle mouse button, so when transformed you don't ever really _stop_ using that ability.

Ling code is fucking cursed.
