### ISSUE TITLE
It is impossible to create a superMatter crystal shard inside crystallizer

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#70307]
**Round ID : N/A**

**Description:**

Creating the gases to make a supermatter crystal shard[Plasma,O2,BZ,Hyper-Nob,Anti-Nob] is not the difficult part. These are possible via a fusion reactor or quad ultra micro lasers but maintaining the Temperature[2-5 kelvin] range for the reaction is impossible.

To illustrate the point here is my setup

![Screenshot (21)](https://user-images.githubusercontent.com/110812394/193893664-8c4121de-ffae-4f6f-8d29-dd9b6509649c.png)

On the left i have 3 tier 4 freezers[bluespace matter bins and quad ultra micro lasers] and this is what the horizontal omni pipe and the vertical red coolant pipe contains

![Screenshot (22)](https://user-images.githubusercontent.com/110812394/193894131-f39bec75-4f87-4e96-a073-c48e54418786.png)

I cant physically fit any more gas in these pipes and my entire plasma tank in atmospherics is running out. Even with hyber-noblium we would need to create an mental amount of it via the dangerous fusion reactor to reach a heat capacity of 20 MJ and even then it fails to keep the gas cool enough

![Screenshot (23)](https://user-images.githubusercontent.com/110812394/193894651-8eedc8f3-c328-4491-a1f7-65e4eb440eea.png)

Temps still spike to 63 kelvin and i don't have enough time to cool down the gas before the progress goes down to 0 again. Even with admin tools after spawning like 50+ canisters of Hyper-Nobelium i still couldn't get it to cool down fast enough.

The wiki dosen't offer any advice and nobody has even tried to use the crystallizer as the shard can be ordered through cargo bay i get it but this process should be made easier. Expand the temp requirements or decrease the amount of energy this reaction releases

**Comment by msgerbs** [comment]
@LemonInTheDark The crystalizer was your baby, right? What are your thoughts?

**Comment by LemonInTheDark** [comment]
it was ghilker's child, I was just really fond of it
we could totally lower the energy output, that's a bit silly

**Comment by msgerbs** [comment]
Ah yes, I forgot Ghilker was the atmo nerd before they vanished.

Personally I think both the 5K threshold and the huge energy output seem a bit extreme considering you can just *buy one* but I've almost basically never touched this stuff in a real round.
