### ISSUE TITLE
ai cameras runtime CONSTANTLY when not around the center of the station

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#70329]
repo:
be ai
be in ai core
move camera.

https://github.com/tgstation/tgstation/blob/bb4cce72e8d0d2121e8f8d084619435f2f50c920/code/modules/mob/living/silicon/ai/freelook/cameranet.dm#L67-L79
this is CONSTANTLY sending 0 values. 

https://github.com/tgstation/tgstation/blob/bb4cce72e8d0d2121e8f8d084619435f2f50c920/code/modules/mob/living/silicon/ai/freelook/cameranet.dm#L49-L56
causing this to runtime constantly. lowest is returning null since it's getting 0 x/y coords. 

@LemonInTheDark Caused by #69115

```
[2022-10-15 16:12:38.890] runtime error: Cannot read null.z
 - proc name: getCameraChunk (/datum/cameranet/proc/getCameraChunk)
 -   source file: cameranet.dm,53
 -   usr: AI (/mob/living/silicon/ai)
 -   src: Camera Net (/datum/cameranet)
 -   usr.loc: the floor (150,25,4) (/turf/open/floor/circuit)
 -   call stack:
 - Camera Net (/datum/cameranet): getCameraChunk(160, 0, 4)
 - Camera Net (/datum/cameranet): visibility(/list (/list), null, /list (/list), 1)
 - AI (/mob/living/silicon/ai): camera visibility(Inactive AI Eye (/mob/camera/ai_eye))
 - Inactive AI Eye (/mob/camera/ai_eye): setLoc(the floor (150,25,4) (/turf/open/floor/circuit), 0)
 - AI (/mob/living/silicon/ai): create eye()
 - AI (/mob/living/silicon/ai): Initialize(0, null, TagGamerGame2 (/mob/dead/new_player))
 - Atoms (/datum/controller/subsystem/atoms): InitAtom(AI (/mob/living/silicon/ai), 0, /list (/list))
 - AI (/mob/living/silicon/ai): New(0, null, TagGamerGame2 (/mob/dead/new_player))
 - AI (/mob/living/silicon/ai): New(the floor (150,25,4) (/turf/open/floor/circuit), null, TagGamerGame2 (/mob/dead/new_player))
 - /datum/job/ai (/datum/job/ai): get spawn mob(TagGamerGame2 (/client), AI (/obj/effect/landmark/start/ai))
 - TagGamerGame2 (/mob/dead/new_player): create character(AI (/obj/effect/landmark/start/ai))
 - Ticker (/datum/controller/subsystem/ticker): create characters()
 - Ticker (/datum/controller/subsystem/ticker): setup()
 - Ticker (/datum/controller/subsystem/ticker): fire(0)
 - Ticker (/datum/controller/subsystem/ticker): ignite(0)
 - 
```
```
[2022-10-15 16:12:38.902] runtime error: Cannot execute null.add().
 - proc name: visibility (/datum/cameranet/proc/visibility)
 -   source file: cameranet.dm,88
 -   usr: AI (/mob/living/silicon/ai)
 -   src: Camera Net (/datum/cameranet)
 -   usr.loc: the floor (150,25,4) (/turf/open/floor/circuit)
 -   call stack:
 - Camera Net (/datum/cameranet): visibility(/list (/list), null, /list (/list), 1)
 - AI (/mob/living/silicon/ai): camera visibility(Inactive AI Eye (/mob/camera/ai_eye))
 - Inactive AI Eye (/mob/camera/ai_eye): setLoc(the floor (150,25,4) (/turf/open/floor/circuit), 0)
 - AI (/mob/living/silicon/ai): create eye()
 - AI (/mob/living/silicon/ai): Initialize(0, null, TagGamerGame2 (/mob/dead/new_player))
 - Atoms (/datum/controller/subsystem/atoms): InitAtom(AI (/mob/living/silicon/ai), 0, /list (/list))
 - AI (/mob/living/silicon/ai): New(0, null, TagGamerGame2 (/mob/dead/new_player))
 - AI (/mob/living/silicon/ai): New(the floor (150,25,4) (/turf/open/floor/circuit), null, TagGamerGame2 (/mob/dead/new_player))
 - /datum/job/ai (/datum/job/ai): get spawn mob(TagGamerGame2 (/client), AI (/obj/effect/landmark/start/ai))
 - TagGamerGame2 (/mob/dead/new_player): create character(AI (/obj/effect/landmark/start/ai))
 - Ticker (/datum/controller/subsystem/ticker): create characters()
 - Ticker (/datum/controller/subsystem/ticker): setup()
 - Ticker (/datum/controller/subsystem/ticker): fire(0)
 - Ticker (/datum/controller/subsystem/ticker): ignite(0)
```

**Comment by ShizCalev** [comment]
>click track with camera
https://github.com/tgstation/tgstation/blob/bb4cce72e8d0d2121e8f8d084619435f2f50c920/code/modules/mob/living/silicon/ai/freelook/chunk.dm#L127-L136
this runtimes. 0,0,5 coords being sent.

**Comment by MrStonedOne** [comment]
@tgstation/issue-managers please close this issue report.

Nobody, let alone a fucking maintainer should be putting up reports about runtimes without actually putting up the actual fucking runtime.

**Comment by LemonInTheDark** [comment]
Thought I fixed this, ahhhh

**Comment by Kylerace** [comment]
```
[2022-10-15 16:12:38.848] runtime error: Cannot read null.z
 - proc name: getCameraChunk (/datum/cameranet/proc/getCameraChunk)
 -   source file: cameranet.dm,53
 -   usr: AI (/mob/living/silicon/ai)
 -   src: Camera Net (/datum/cameranet)
 -   usr.loc: the floor (150,25,4) (/turf/open/floor/circuit)
 -   call stack:
 - Camera Net (/datum/cameranet): getCameraChunk(128, 0, 4)
 - Camera Net (/datum/cameranet): visibility(/list (/list), null, /list (/list), 1)
 - AI (/mob/living/silicon/ai): camera visibility(Inactive AI Eye (/mob/camera/ai_eye))
 - Inactive AI Eye (/mob/camera/ai_eye): setLoc(the floor (150,25,4) (/turf/open/floor/circuit), 0)
 - AI (/mob/living/silicon/ai): create eye()
 - AI (/mob/living/silicon/ai): Initialize(0, null, [ckey] (/mob/dead/new_player))
 - Atoms (/datum/controller/subsystem/atoms): InitAtom(AI (/mob/living/silicon/ai), 0, /list (/list))
 - AI (/mob/living/silicon/ai): New(0, null, [ckey] (/mob/dead/new_player))
 - AI (/mob/living/silicon/ai): New(the floor (150,25,4) (/turf/open/floor/circuit), null, TagGamerGame2 (/mob/dead/new_player))
 - /datum/job/ai (/datum/job/ai): get spawn mob([ckey] (/client), AI (/obj/effect/landmark/start/ai))
 - [ckey] (/mob/dead/new_player): create character(AI (/obj/effect/landmark/start/ai))
 - Ticker (/datum/controller/subsystem/ticker): create characters()
 - Ticker (/datum/controller/subsystem/ticker): setup()
 - Ticker (/datum/controller/subsystem/ticker): fire(0)
 - Ticker (/datum/controller/subsystem/ticker): ignite(0)
```
found one from https://tgstation13.org/parsed-logs/sybil/data/logs/2022/10/15/round-192405/runtime.txt

**Comment by tgstation-server** [comment]
![image](https://user-images.githubusercontent.com/12387510/196012003-706f9b65-4027-44de-823b-b8ae9bcb5498.png)
This is no longer acceptable.

**Comment by LemonInTheDark** [comment]
Piss off

**Comment by MrStonedOne** [comment]
https://gitlab.com/gitlab-org/gitlab-foss/-/issues/2432

you are colossally stupid if you think you will win this war.

**Comment by LemonInTheDark** [comment]
I don't even fucking care man I just don't want to deal with you when you're upset, and I don't want others to either
Please do not use me saying that as an excuse to escalate this non argument, it's really annoying

**Comment by MrStonedOne** [comment]
i don't think you understand, the `just let oranges handle it` montra is no long working.

It just makes me frustrated nobody is listening to me so I lash out.

You should have closed the issue and let oranges handle re-opening it if thats how you wanted to play it.

**Comment by ShizCalev** [comment]
> @tgstation/issue-managers please close this issue report.
> 
> Nobody, let alone a fucking maintainer should be putting up reports about runtimes without actually putting up the actual fucking runtime.

Don't know who pissed in your coffee, but seriously, you need to relax bro. 

I forgot to put the runtime. It's not the end of the world. I didn't hurt anyone by doing it. I can just edit the post to add it.

**Comment by optimumtact** [comment]
> i don't think you understand, the `just let oranges handle it` montra is no long working.

This is recommended advice because anytime anyone else interacts with you, you end up frustrated and lashing out anyway because they are not always willing to consider your PoV.

I asked people to let me handle it because otherwise it seems like people end up in long running fights with you that end up with you applying some kind of block or ban on people, or people leaving because they're fed up from having to deal with you.

I think you really do need to be more patient and allow there to be time for someone with appropriate seniority to deal with the issue because any other come tends to become a net negative for either you or the codebase.

i.e the thing you end up having fustration with is entirely self inflicted because of how you keep interacting with people in the codebase. 

Saying that it's no longer possible to wait for someone senior to come on line is effectively putting yourself and us in a no win situation that can't be resolved easily.
