### ISSUE TITLE
Paper bag missing sprite

### ISSUE THREAD

**Issue by M3hillus** [tgstation/tgstation#70337]
## Round ID:
[191828](https://scrubby.melonmesa.com/round/191828)

## Reproduction: 
get 5 paper, make a paper bag via the crafting menu. Produces 1 invisible paper bag. Bag is on the same tile as the red paper.
![using construction paper](https://i.imgur.com/6ESH00u.png)

**Comment by ShizCalev** [comment]
Mixed systems, reeeeeeeee
