### ISSUE TITLE
You can see normally while travelling through disposals

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/tgstation#7033]
Ancient bug that nobody bothered to mention because we got so used to it.

You can see things normally as you ride through disposals, potentially letting you see things you logically shouldn't be able to see because you're in a pipe under the floor tiles.

**Comment by Ergovisavi** [comment]
Closets have this same issue. You're 100% aware, despite being in a small metal box with very small eye slits, if they even exist.

**Comment by Ikarrus** [comment]
Closets and pipes should have the same overlay as being unconscious y/n

**Comment by mikecari** [comment]
Doesn't bother me at all, the game ain't supposed to be realistic.

**Comment by Ikarrus** [comment]
<mso> just make disposals be only see_turf <- even better

**Comment by dannno** [comment]
>Closets and pipes should have the same overlay as being unconscious y/n

Pipes sure. Closets no. Closets don't have an overlay for gameplay/mechanic reasons IMO.

**Comment by paprka** [comment]
>Closets don't have an overlay for gameplay/mechanic reasons IMO.

Bad ones. Terrible ones. Camping in closets is maximum fucking scrub strategy, please remove.

Also disposal bins.

**Comment by xxalpha** [comment]
Realistically you could hide in a closet and see something, but unless you plan to code a realistic closet view, players shouldn't go blind in closets.

**Comment by dannno** [comment]
yeah.

**Comment by paprka** [comment]
No, closet slits are designed for air flow, not visibility within a closet.

![locker](https://cloud.githubusercontent.com/assets/7247232/5743531/aa29b6f2-9bce-11e4-8303-4bd5120fc8bc.JPG)

Realistically you'd be blind as a bat. KILL CLOSET POWERGAME 2015.

**Comment by dannno** [comment]
realism is worse than "closet powergame"

**Comment by paprka** [comment]
So if seeing out of closets is neither realistic nor balanced gameplay, what is it?

I feel like a preschool teacher here dannos.

**Comment by hornygranny** [comment]
you should be blind in both

**Comment by dannno** [comment]
i don't feel like it's that unbalanced at all

**Comment by Miauw62** [comment]
danno is a closet powergamer :^]

(sorry for the terrible joke)

**Comment by dannno** [comment]
or just give the welder-vision overlay to people in closets
that's semi-maybe-kind-realistic-ish and kills the vision a bit

**Comment by MrStonedOne** [comment]
Welder vision for lockers

Turf only vision for disposals. (so that Mr Wacky's wild ride is actually fun)

And fuck it, just pop this in life for mob/living, then no worry about non normal things removing you from lockers/disposals not removing the effect.

**Comment by optimumtact** [comment]
http://i00.i.aliimg.com/img/pb/256/328/607/607328256_009.jpg

**Comment by paprka** [comment]
Didn't know you could stack 3 lockers on top of each other in ss13 oranges, thanks for the tip!

Except no, please go.

**Comment by MrStonedOne** [comment]
Except that's not the fucking point.

And you fucking know that.

Seriously pap, stop this obtuse bullshit, we all see right thru it.

**Comment by paprka** [comment]
![ss 2015-01-14 at 05 25 35](https://cloud.githubusercontent.com/assets/7247232/5751031/574869c6-9c12-11e4-91c9-9fe4251eb4b9.png)

**Comment by swankcookie** [comment]
@phil235 this can probably be closed.

**Comment by phil235** [comment]
No, my PR didn't completely fix the issue. You can still see things you shouldn't while travelling in disposal. Your vision is now a bit limited but you still basically see through the metal of the pipe you are in.

**Comment by tedward1337** [comment]
Close this shit yo
