### ISSUE TITLE
obj/item/gun/ballistic/fire_sounds() runtime

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#70332]
https://github.com/tgstation/tgstation/blob/91f02f2a6b99c6eb5ae56fc3f7cfb903e703bc08/code/modules/projectiles/guns/ballistic.dm#L139-L140

div/null doesn't work.

**Comment by Mooshimi** [comment]
it say runtime in the title so i add runtime

**Comment by ShizCalev** [comment]
fixed by #76196
