### ISSUE TITLE
Powernet test inconsistently fails 

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#70360]
https://github.com/tgstation/tgstation/actions/runs/3200620257/jobs/5227741740

Error: /datum/powernet found with no power roundstart, connected to a cable at (166, 213, 2).

**Comment by Mothblocks** [comment]
Nvm it's the powernet test

**Comment by Mothblocks** [comment]
@JohnFulpWillard

**Comment by JohnFulpWillard** [comment]
It's reporting this tile
![image](https://user-images.githubusercontent.com/53777086/194438597-15bd6704-52a6-4bdc-8faf-4e2ff0a11ffa.png)

My assumption here would be that before unit tests ran, a mice bit the cable under it, which is unfortunate.

**Comment by Mothblocks** [comment]
How many times are the mice going to do this to us

**Comment by Mothblocks** [comment]
Making mice not bite wires during unit tests is fine because they're a source of randomness, in a perfect world we would have a bespoke test for it.

**Comment by WarlockD** [comment]
powernets are created on producers so the smes might of created the net initialy but mabye that wire was cut?

**Comment by JohnFulpWillard** [comment]
a powernet is a single cable

the error is that it has no power roundstart, regardless of SMES being there, so something severed it from the station's powernet before unit tests ran.
