### ISSUE TITLE
RMB welds airlocks shut, LMB welds firedoors shut

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#70378]
## Reproduction:

If you have a welding tool and want to weld an airlock shut, you use RMB

If you wanna do the same to a firedoor / firelock, you use LMB

**Comment by Guestratem** [comment]
Found the source, on the door.dm class file there is two defined methods for interacting with a welding tool, one try_to_weld_secondary uses right click, try_to_weld uses left click
