### ISSUE TITLE
Telescoping riot shield has no inhand sprites when extended.

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#70377]
Reporting client version: 514.1588

## Round ID:
[191943](https://scrubby.melonmesa.com/round/191943)

## Testmerges:
- [Checks Filters For Cross-Station Messages](https://www.github.com/tgstation/tgstation/pull/70273)

## Reproduction:
Get shield, activate it,
![image](https://user-images.githubusercontent.com/54517726/194683074-e67e16e0-9a80-4767-961b-c52d152da7ce.png)
![image](https://user-images.githubusercontent.com/54517726/194683081-50a08692-99d6-4899-872e-b7af62823971.png)

**Comment by Mothblocks** [comment]
@ShizCalev Yours?
