### ISSUE TITLE
Double barrel shotguns fire ghost bullets; they do not harm and they cannot be loaded or unloaded

### ISSUE THREAD

**Issue by DAKKA-WAAAGH** [tgstation/tgstation#70399]
## Reproduction: May not be able to be reproduced. I found it in disposals and took it to the brig to see if I can put some real ammo in it for the current station threat. It could not be unloaded or loaded and inspection didn't detail if it had rounds in it or not, but it could be shot infinitely and none of the shots did any type of damage.

**Comment by necromanceranne** [comment]
Oh that was a chameleon gun. No, it was working as intended.

**Comment by DAKKA-WAAAGH** [comment]
> Oh that was a chameleon gun. No, it was working as intended. I'll wait on someone with log access to check this maybe but I think this wasn't an actual double-barrel shotgun.

Haha I even ahelped it too!
