### ISSUE TITLE
White cane has no extended inhand sprites

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#70400]
Reporting client version: 514.1588

## Round ID:
[192004](https://scrubby.melonmesa.com/round/192004)

## Testmerges:
- [Checks Filters For Cross-Station Messages](https://www.github.com/tgstation/tgstation/pull/70273)

## Reproduction:
Get cane, extend cane

**Comment by ShizCalev** [comment]
Fixed by #70425
