### ISSUE TITLE
Mobs that are held will sometimes temporarily lose their ability to see normal conversation and some *mes.

### ISSUE THREAD

**Issue by dopamiin0** [tgstation/tgstation#70405]
## Testmerges:
[#70311: 'Having very very low sanity will rarely cause hallucintions' by MrMelbert at commit 0d6864fc4c](https://www.github.com/tgstation/tgstation/pull/70311)

## Reproduction:
Be any sort of mobholder mob like a pAI or sentient axolotl or whatever
get set down or picked up
cry as you can temporarily not see text convos or *mes, even your own (you can hear radio tho???)

**Comment by msgerbs** [comment]
I just had this as well in 192090. I assumed it was related to the issue discussed in 70404, but I was also a sentient mob that got picked up. (although not at the specific time that speech stopped working)
