### ISSUE TITLE
Simple Circuit Design disk upgrade for RCD[Rapid Construction Device] doesn't work

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#70418]
**Round ID** : N/A

**Reproduction**

1)Research design disk upgrades for RCD

2)Make a simple circuit design disk upgrade for RCD

3)Install it in your RCD

4)You don't have option's to print circuit boards or battery cells in the RCD Menu . Wasted titanium and silver printing this upgrade for nothing

**Comment by newfren** [comment]
did you try to use the rcd on something that required a circuit board or a cell, such as an apc or fire alarm

**Comment by SyncIt21** [comment]
You were right. I assumed it would show a menu displaying what  circuit boards you would like to print. Didn't know it would directly install them inside a APC/Air alarm frame when you clicked on them with the RCD. The wiki didn't make it clear enough. My bad ill close this issue
