### ISSUE TITLE
Interactive humans can pick up items through closed windoors.

### ISSUE THREAD

**Issue by phil235** [tgstation/tgstation#7041]
Example: put item behind a closed windoor, the interactive human can pick up the item through it, without having to open the windoor first. It's basically not checking whether the mob and item are truly adjacent and not separated by a single pane window or windoor.

**Comment by Jalleo** [comment]
Can you explain a bit more?

**Comment by phil235** [comment]
@sawu-tg

**Comment by sawu-tg** [comment]
I'm aware, it's going to take ages to fix them all, and it'd help if other people could chip in. A lot of their errors are related to them not double checking their location, but beyond that some I haven't a clue.

**Comment by phil235** [comment]
@sawu-tg is this fixed?

**Comment by sawu-tg** [comment]
@phil235 Most probably not, I don't code for /tg/ anymore, and I didn't fix this bug so if someone else hasn't, it still exists.

Probably better to just rip out the SNPC system entirely because i'm definitely not going to maintain them and no one else seems to want to.

**Comment by nicbn** [comment]
Could not reproduce this
