### ISSUE TITLE
Medical Jumpsuit mob sprite has 2 dupe frames instead of being a 1 frame item

### ISSUE THREAD

**Issue by OrionTheFox** [tgstation/tgstation#70417]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
This one's just a 'look at the .dmi' thing
![image](https://user-images.githubusercontent.com/76465278/194753357-bd6ff575-a9ab-4456-baa2-084d0faccbd0.png)

Can't fix it myself, my TG branch hates me right now.
**Path:** icons\mob\clothing\under\medical.dmi
**Icon State:** medical

**Comment by dragomagol** [comment]
Closed in #70429
