### ISSUE TITLE
Anomaly Refinery Issue #70248

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#70426]
Just a remainder for issue [#70248](https://github.com/tgstation/tgstation/issues/70248)

It's a very simple fix but I want to get someone's thoughts on this before I make a pull request. 

I'll close this issue when someone comments on that

**Comment by LemonInTheDark** [comment]
You shouldn't open issues just to bump an existing issue.
If you wanna get thoughts on something, discuss it in the tg discord, all the maints are quite easy to talk to there.
