### ISSUE TITLE
Area editing breaks air alarm  configuration

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#70430]
**Round ID** : N/A

**Reproduction**

1) Create a small area shown  and use area editor/small create area icon on the bottom right of your screen. Name the area to "OUTER" &  Install apc, air alarm , and 2 scrubbers just for testing like as shown  

![Screenshot (26)](https://user-images.githubusercontent.com/110812394/194865499-27365fdb-1a3e-4132-98ba-68bc15a3722d.png)

2) Create a second walled area within this area as shown. Use AreaEditor and name this area to "INNER"

![Screenshot (27)](https://user-images.githubusercontent.com/110812394/194866004-8419f622-e1cd-4837-a81f-4fcc5ae028db.png)

**3 Bugs Occur**

1) The air alarm installed in the "OUTER" Area also shows the scrubber installed in the "INNER" area. This shouldn't be possible as only the air alarm installed in the "INNER" area should locate this scrubber and the "OUTER" air alarm should no longer have control over that scrubber

2) If you unwrench & wrench back the "INNER" scrubber it breaks the air alarm interface located in "OUTER"

![Screenshot (28)](https://user-images.githubusercontent.com/110812394/194867049-b287c04a-bb2a-4592-8ae8-c6617e45e040.png)

Notice how the 2nd scrubber name isn't displayed and the off button is misaligned and i cant interact with this scrubber

3) If you install an APC & an Air alarm interface inside "INNER" but later break down a wall and merge area "INNER" to "OUTER" it breaks area "INNER" air alarm. i.e interface becomes non responsive

![Screenshot (29)](https://user-images.githubusercontent.com/110812394/194870679-bd298834-c55d-46fb-81e2-b7ed52d0ce8a.png)

Notice how the air alarm is still called "Inner air alarm" even though i merged this area with outer. The interface looks ok but you cant click on any buttons on the scrubber

**Comment by SyncIt21** [comment]
Forgot to mention that it breaks vents as well. Any updates?

**Comment by msgerbs** [comment]
Ah the good old area editor, ever a source of random-ass bugs :)
