### ISSUE TITLE
Corpses have read-able thoughts. (allowing dead to communicate with living)

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#70442]
Reporting client version: 514.1582

## Reproduction:

Set up a thought reader bci circuit that can retrigger itself while the host is dead.

It accepts input from dead players (the only real limitation I think is you need to return to your body before you submit the text)

https://www.youtube.com/watch?v=cKi5FR0OPfU

**Comment by san7890** [comment]
All of the messages that were typed into the thought reader did indeed output into IC chat. "amongus" is hard-IC-filtered on /tg/ (as well as saying stuff like lol), which they were later able to do in the round
