### ISSUE TITLE
Pocket protector item restriction label lists all subtypes when worn

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#70464]
## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:

Wear a pocket protector on your suit, and examine it. You will be told that the suit can hold 3 items, with the `items` being a hyperlink that would list all the items that are allowed. Click the link, and you will the see a list of the names every subtype of those items.

Take off your pocket protector, and examine it. Note that it also displays that it can hold 3 items. Click the link and see the list:
The pocket protector can hold: 
	a pen
	a red crayon
	a red lipstick
	a penlight
	a cigarette

The list of the base type's displayed names is correct.

I don't know of any other accessories that has storage, but if anyone remembers one, I will test those too.

**Comment by Jackal-boop** [comment]
I've never actually been able to store an item in a pocket protector
