### ISSUE TITLE
Inorganic Biology and infection. 

### ISSUE THREAD

**Issue by FotisLight** [tgstation/tgstation#70460]
## Reproduction: It just seems as tho Inorganic Bio no longer enables the infection of plasmen or anyone for that matter. The diseases composition included Eternal Youth, Inorganic Biology, Disfiuragtion (neutered), Sneezing(neutered), and Regen Coma in that order.

Inorganic Bio seems to disable any method of infection as I was able to test this on myself being a plasman, monkey, human monkey, and another player (Methods used to attempt to spread disease were a pill, injection, and consumption of the disease directly). I ensured none of them were infected with any sort of disease before attempting to infect them. It seems as tho something is just broken with viro mechanics. As I was able to make a disease without Inorganic Bio that was able to spread and infect others.

**Comment by timothymtorres** [comment]
Seems like #51128 or #51150 is back.  Apparently #51177 didn't fix this completely?

**Comment by ATH1909** [comment]
oh god not this bug again
