### ISSUE TITLE
Mech right click not using secondary only primary

### ISSUE THREAD

**Issue by Kelvin-Mondayne** [tgstation/tgstation#70516]
Reporting client version: 514.1584

## Round ID:
[192303](https://scrubby.melonmesa.com/round/192303)

## Testmerges:
- [Checks Filters For Cross-Station Messages](https://www.github.com/tgstation/tgstation/pull/70273)
- [Swaps sleep() to use SECONDS define](https://www.github.com/tgstation/tgstation/pull/70452)

**Comment by ShizCalev** [comment]
#70369 @TiviPlus ?

**Comment by TiviPlus** [comment]
> @TiviPlus perhaps?
> 
> 
> 
> #70369 specifically changed mecha right clicking.

514.1584 is a broken byond version it's been fixed
Iirc  514.1583 is broken

**Comment by Sealed101** [comment]
this seems like it was a common issue at some point, i remember seeing complaints in-game and on the tracker. can't find em, but they seem to have ceased. byond issue?
