### ISSUE TITLE
Sneaksuits don't block your Sechud ID icon as an AI

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#70519]
Reporting client version: 514.1589

## Round ID:
[192308](https://scrubby.melonmesa.com/round/192308)

## Testmerges:
- [Checks Filters For Cross-Station Messages](https://www.github.com/tgstation/tgstation/pull/70273)
- [Stairs DLC: Buildable stairs, material datum staircases, fall up a staircase](https://www.github.com/tgstation/tgstation/pull/70504)

## Reproduction:
In this particular shift I was able to spot a curator running around in a sneaksuit and immediately be able to tell it was him despite the new identity hiding feature because of his hud icon. I'm not sure if its supposed to do that or not but it does seem a little bit like an oversight

**Comment by necromanceranne** [comment]
It's an oversight and not intended.
