### ISSUE TITLE
GitHub Actions Test Merge Comment Bot Reverting Count

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#70520]
## Reproduction:

For an example, consult this comment on this PR: https://github.com/tgstation/tgstation/pull/70273#issuecomment-1272455064

It got up to 171 rounds, stayed there for a few days, and now it's... counting down? If you look at the edit history, you can see that for the last few hours, it's been removing one from the count just about every hour. This is especially confusing when you should consider the fact that the number should be going up, as this PR is actively test-merged on both Sybil and Manuel (at the time of this issue report). Very odd stuff.

If you can't see an actual increment, just go to around the date of oranges' comment on that PR, and notice that it did indeed read 171 test-merged rounds at one point, and has now abruptly gone below 171 for no logical reason beyond the fact that the functionality is FUCKED.

**Comment by Mothblocks** [comment]
It's regenerating the list every time from the most recent 200 instead of merging the sets together
