### ISSUE TITLE
Gas Senders convert all gasses other than oxygen into n2 

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#70534]
## Testmerges:

[#70273: 'Checks Filters For Cross-Station Messages' by san7890 at commit b7391b8f9a](https://www.github.com/tgstation/tgstation/pull/70273)
[#70452: 'Swaps sleep() to use SECONDS define' by san7890 at commit 068f1259a2](https://www.github.com/tgstation/tgstation/pull/70452)

## Reproduction:

wrench gas sender next to a pipe with many gasses of different types in it
screw it in
turn it on
wonder why all the gas is turned into n2

![image](https://user-images.githubusercontent.com/54422837/195946850-9895d7a9-1c9c-40f6-ae60-dbbb362e8d6d.png)
![image](https://user-images.githubusercontent.com/54422837/195946865-a3bbf77c-405a-474c-8782-39751e63011f.png)

**Comment by Jackal-boop** [comment]
What the fuck

**Comment by vincentiusvin** [comment]
are you sure you are not connecting it to distro, looks like its on layer 2/4.
![image](https://user-images.githubusercontent.com/54709710/195971210-fd41147d-6031-4c78-8823-df9b8cdc8000.png)

**Comment by GoblinBackwards** [comment]
There's a distro pipe on layer 3 there that you connected it to
![image](https://user-images.githubusercontent.com/22856555/195980450-98e2bf4c-e99d-4a78-b5b2-ca2c883eef51.png)

**Comment by msgerbs** [comment]
Aren't layers fun?
