### ISSUE TITLE
SSU locks dont seem to do anything

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#70552]
## Round ID:
Round ID: [192406](https://scrubby.melonmesa.com/round/192406)

## Reproduction:
i locked my CE modsuit storage and someone just opened it and took it, no emag required or anything.

**Comment by Jackal-boop** [comment]
Also SSUs don't charge modsuits, even though they charge space suits

**Comment by Sealed101** [comment]
not a modsuit related issue (though the comment to the issue is modsuit related)

actually, MODsuits can be charged via a SSU if their panel is screwed open. though it doesn't really tell anywhere about that. curious
