### ISSUE TITLE
Recharging the buyable mining MOD suit creates dead inventory slots in the modsuit

### ISSUE THREAD

**Issue by du5tball** [tgstation/tgstation#70554]
## Round ID:
[192414](https://scrubby.melonmesa.com/round/192414)

## Reproduction:
Buy a mining MOD suit, harvest some plasma, use plasma on the MOD suit control unit. Poof, dead inventory slot. Try the same with plasma sheets and you get two dead inventory slots. It seems to try and add the plasma to the inventory and at the same time use it to charge the suit.

**Comment by davethwave** [comment]
A quick work around is to drag empty your inventory onto the ground. Clears up the invisible objects.
