### ISSUE TITLE
Metastation solars has a probably erroneously placed wall instead of Rglass 

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#70560]
Reporting client version: 514.1589

## Round ID:
[192426](https://scrubby.melonmesa.com/round/192426)

## Testmerges:
- [Swaps sleep() to use SECONDS define](https://www.github.com/tgstation/tgstation/pull/70452)

## Reproduction: Look at it
![image](https://user-images.githubusercontent.com/54517726/196012243-02bb0b46-f503-42ce-9ace-0bf74d7c8e0f.png)
In contrast to every other solars:
![image](https://user-images.githubusercontent.com/54517726/196012251-66609d34-6d7e-407d-856d-f9c5a7efc9c6.png)

**Comment by msgerbs** [comment]
Is every solar on meta the same? I don't know if this really counts as a bug as there's no design doc stating how solars _must_ look.

**Comment by dragomagol** [comment]
Inclined to say not a bug. All the meta solars are drastically different from each other, so it makes sense that they're not all uniform.

**Comment by Baskett55** [comment]
> Inclined to say not a bug. All the meta solars are drastically different from each other, so it makes sense that they're not all uniform.

theyre all uniform except for the lower left solars

**Comment by msgerbs** [comment]
They're actually really un-uniform and idk if it's intended or not but I fixed it anyway.
