### ISSUE TITLE
Snake staff from Lavaland/Icebox portals dissapears when moving Z levels

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#70562]
Reporting client version: 514.1589

## Round ID:
[192431](https://scrubby.melonmesa.com/round/192431)

## Testmerges:
- [Stairs DLC: Buildable stairs, material datum staircases, fall up a staircase](https://www.github.com/tgstation/tgstation/pull/70504)
- [Chefs can now kiss food they make to make it with love. (And a lot of cooking refactoring)](https://www.github.com/tgstation/tgstation/pull/70409)
- [Adds extended tooltip information to observables in the orbit ui](https://www.github.com/tgstation/tgstation/pull/70547)

## Reproduction:
For some reason if you move up a zlevel while holding the Healing snake staff (I refuse to botch its actual name) it disappears from your hand completely, on this round it happened right as I ascended the stairs

**Comment by msgerbs** [comment]
Pretend I know nothing about lavaland and try to type out its actual name (or even parts of its description) so I can search it please.

**Comment by DaydreamIQ** [comment]
Rod of Asclepius

**Comment by Mooshimi** [comment]
> 

weak
