### ISSUE TITLE
Sprayer / Painter inhands seem inaccurate

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#70565]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/196016160-f5f8847c-9652-4549-8ce2-f75376737a65.png)

![image](https://user-images.githubusercontent.com/51863163/196016232-e5f3ab33-db1c-4dc0-b800-65abd44203a3.png)

Front and back look fine, but side to side seem jank

**Comment by dragomagol** [comment]
Duplicate of (now closed) #69980

Was supposed to be fixed in #70037
