### ISSUE TITLE
Wearing a gas mask while infected with a sentient disease (even without internals) completely negates the ability for a sentient disease to spread with Voluntary Cough. 

### ISSUE THREAD

**Issue by Redrover1760** [tgstation/tgstation#70581]
## Round ID: 
192489

## Testmerges: 
https://github.com/tgstation/tgstation/pull/70452

## Reproduction:

I was literally unable to infect anyone because the janitor I infected literally wore a gas mask for style. No internals on at all, I couldn't even infect people when all he had was a gas mask and was naked due to getting surgery for a lost leg. Without being able to infect people, I couldn't do anything at all.

My god what a boring round.

Spam the Cough button over and over again after starting on some random human with a gas mask on. No internals on. Even if someone is right by your host you will never infect them.

**Comment by LemonInTheDark** [comment]
Is this a bug? gas masks block infection (I thought that was part of the point), so they block infection goin out too, even if there's no tank attached.

**Comment by dragomagol** [comment]
Seems like a balance change if anything; I don't think this behaviour is unintentional

**Comment by private-tristan** [comment]
after previously having this happen to me a few weeks ago, i searched why and found #41230, which seems to be the cause

**Comment by Mooshimi** [comment]
> Honestly, this should definitely be changed, specifically for sentient diseases. Or another ability be given to sentient diseases that bypasses this entirely. Or just have their cough, specifically, bypass this. Sure, it makes little sense, but completely removing an antagonist just because people happen to be wearing a very common item is bullshit. (Plasmamen or literally everyone when the station is in firelock hell WILL be wearing masks.)

sentient virus isn't meant to be super strong to begin with anyways. pick people not wearing masks for your first infection

**Comment by RikuTheKiller** [comment]
> > Honestly, this should definitely be changed, specifically for sentient diseases. Or another ability be given to sentient diseases that bypasses this entirely. Or just have their cough, specifically, bypass this. Sure, it makes little sense, but completely removing an antagonist just because people happen to be wearing a very common item is bullshit. (Plasmamen or literally everyone when the station is in firelock hell WILL be wearing masks.)
> 
> sentient virus isn't meant to be super strong to begin with anyways. pick people not wearing masks for your first infection

You don't even get to pick, do you? Or am I just dumb. Judging by the fact that a guy got a moth trapped inside of a crate as their patient zero, which they literally can't choose.

**Comment by Mooshimi** [comment]
> > > Honestly, this should definitely be changed, specifically for sentient diseases. Or another ability be given to sentient diseases that bypasses this entirely. Or just have their cough, specifically, bypass this. Sure, it makes little sense, but completely removing an antagonist just because people happen to be wearing a very common item is bullshit. (Plasmamen or literally everyone when the station is in firelock hell WILL be wearing masks.)
> > 
> > 
> > sentient virus isn't meant to be super strong to begin with anyways. pick people not wearing masks for your first infection
> 
> You don't even get to pick, do you? Or am I just dumb? Judging by the fact that a guy got a moth trapped inside of a crate as their patient zero, which they literally can't choose. (Or the moth walked into a crate immediately after infection???)
> 
> Oh and if you wanna go the goon route and make side antags unreasonably nerfed go right ahead, but sentient virus, xenos, nightmare, etc. are meant to be rather strong. Sentient virus is among the worst ones already judging by how some people just don't want to play it due to it being underpowered, so nerfing it any further is completely fucking pointless.
> 
> If side antags don't add any major spice up to the round, they're completely pointless. (Once again, goon is an example of that.)

Why are you arguing this if you haven't played this antag and don't know you can actually pick your first infected person...
And the "Not a bug" just means it was intended that masks prevented the spread of diseases, not that it can't be changed in that instance.

**Comment by LemonInTheDark** [comment]
if it's dumb or not is another question, but it's not a bug in the code, it's a feature. 
feel free to make a pr arguin for it, it just doesn't belong on the issue tracket
