### ISSUE TITLE
Tram is still functional in unpowered areas

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#70605]
The tram is still functional from unpowered areas. Presumably because the control computer is checking its power status from the APC of the departed area and not updating when the tram arrives at the destination.

![trampower](https://user-images.githubusercontent.com/83487515/196289327-a5b6f06d-ceff-42a9-bef9-42d7d21becb5.gif)

## Expected behaviour:
The tram computer should power off when it's in an area with a dead APC.

## Reproduction:
Power off an APC in the primary hallway of a section of the station, send the tram. The tram computer remains powered and the tram can be sent even though the area has no power.

**Comment by Mooshimi** [comment]
It's powered on its own via suffering.

**Comment by lessthnthree** [comment]
The computer gets the power from somewhere. Like if you power off west primary hallway -and- central primary hallway the tram stops working.

**Comment by msgerbs** [comment]
Do we even have code in the power system for machines just magically moving between areas? Like does it actually change what area it's drawing power from at all?

**Comment by Mooshimi** [comment]
> Do we even have code in the power system for machines just magically moving between areas? Like does it actually change what area it's drawing power from at all?

Yeah have you ever moved a chem dispenser by wrenching it??

**Comment by CarlosA22** [comment]
Literally unplayable

**Comment by MMMiracles** [comment]
The tram is now powered by the area it stops in instead of being powered by tears, so this issue is fixed.
