### ISSUE TITLE
demonic frost miner arena doesn't have an open ceiling anymore

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#70627]
Reporting client version: 514.1585

## Round ID:
[192579](https://scrubby.melonmesa.com/round/192579)

## Testmerges:
- [Orbit refactor + features part dos: Icons, health bars.](https://www.github.com/tgstation/tgstation/pull/70580)

## Reproduction:
![image](https://user-images.githubusercontent.com/12635164/196401785-b0e5c8f5-6d9c-4b3b-a653-d22287660a8a.png)
go to the z level 1 up from the bloodthirsty signal
there's supposed to be a big pit around the ladder with a slim bridge
instead there's nothing

observed over a few rounds, not just this one

**Comment by msgerbs** [comment]
I believe this was deliberately changed here: #66836

**Comment by msgerbs** [comment]
Who originally mapped this? I'm not really sure it was intentionally open to begin with. It would be very strange thematically, as my understanding from the description of the ruin is that it's meant to appear as a little cottage holding a mystery underneath, not being a huge obvious hole in the ground.

**Comment by msgerbs** [comment]
I think I see now that this was accidental and I retract my previous statement. The change above was meant to apply to turfs *above* the ruin, not turfs that were deliberately left open as part of a multi-z ruin, but the change just turns *all* openspace above a ruin into `/turf/closed/mineral/random/snow` without any accounting for the ruin itself. I will fix this.
