### ISSUE TITLE
Agent ID cant steal access from players

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#70632]
## Round ID:
[192547](https://scrubby.melonmesa.com/round/192547)

## Reproduction:
I attempted to use a agent id on someone's sprite and I just slapped them with the ID. Code says it should start a short channel before allowing you to steal access codes

**Comment by Jackal-boop** [comment]
Relevant code is here
https://github.com/tgstation/tgstation/blob/4f6f75387ff5fb6124226c42c8ab76ca0023941e/code/game/objects/items/cards_ids.dm

**Comment by Jackal-boop** [comment]
I'll re try this tmr

**Comment by EuclidianGeometer** [comment]
anecdotally this has also been the issue on 'Orbstation', a tg downstream, for a couple weeks. it works sometimes but very inconsistently.

**Comment by Jackal-boop** [comment]
Okay so this isn't an issue here, I've tested it. Right click works but we should maybe add that to the description of the item so tots don't giveaway their totness
