### ISSUE TITLE
Welding animation doesn't finishing/cannot weld objects, welding animation stuck on something (mech/aug person/walls)

### ISSUE THREAD

**Issue by LikesGreen** [tgstation/tgstation#70651]
## Round ID: 

192630

## Reproduction:

Was trying to make Odysseus mech, started welding part 1 when I seen that welding animation is stuck on mech after I finished first welding, when I was trying to do part 2 welding I couldn't do anything with welder (the fuel was in, welder was on and the step with construction was saying that it needs welding), one of the admins was present during it and try to fix it without success.

I also seen lots of welding animation stuck on walls, doors and aug/synth people. Im not sure but I think lots of aug people couldn't heal themself with welder also.

**Comment by CactusAcolyte** [comment]
Can confirm to have happened when trying to unsecure a double-sided reflector from the floor (Round ID 192635), fix an airlock via welding and cut through a vault door's security plating (Round ID 192630).
The weld can be attempted any number of times and the starting text is shown each time in the chat, but no progress bar shows up nor is any progress made. Welding sparks animation shows up and gets stuck permanently.

**Comment by san7890** [comment]
whoops my fault
