### ISSUE TITLE
Limited AI functionality

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#70664]
Currently, it seems that quite a few important features of AI are incredibly fucked, they are unable to send any PDA messages and the CMC button for the AI hotbar is non-functional. 

## Round ID:
[192674](https://scrubby.melonmesa.com/round/192674)

## Testmerges:

[#70580: 'Orbit refactor + features part dos: Icons, health bars.' by jlsnow301 at commit 8d39b61ea9](https://www.github.com/tgstation/tgstation/pull/70580)
[#70235: 'Cleans up the fallout from plane cube' by LemonInTheDark at commit a87cd13b79](https://www.github.com/tgstation/tgstation/pull/70235)

## Reproduction:

For the PDA issue
>Attempt to send PDA message
>Get to input field
>Send message
>No confirmation in chat, recipient says they received no message

Crew monitoring hotkey
>Press button
>Nothing happens

R&D server console
>Click
>Nothing loads

**Comment by Mooshimi** [comment]
what in tarnation

**Comment by carshalash** [comment]
Update: It seems the inabiliyt to interface with random consoles/doors is being caused by an error with cameras.

![image](https://user-images.githubusercontent.com/16896032/196873821-7e16131b-5350-400b-976c-3a8c89dec1e7.png)
this was occurring when I tried using a smes when we can see in this photo here, that I was able to see all of them quite clearly.
![image](https://user-images.githubusercontent.com/16896032/196873950-e89579c6-08bc-410c-a992-4f03c308d3b2.png)

**Comment by Mooshimi** [comment]
can you try doing this stuff again since some tms were removed last night that were causing issues?

**Comment by Mooshimi** [comment]
[X7] - Line 2 just changes location of click
```[01:13:45] Cannot execute null.can use(). 
Thrown by light_cameras (/mob/living/silicon/ai/proc/light_cameras) at ai.dm, line 788
User: null (src)
Source: Amaretto (/mob/living/silicon/ai)
Source Location: the floor (/turf/open/floor/circuit/green) (214, 144, 2)
Stacktrace:
1 Amaretto (/mob/living/silicon/ai): light cameras()
2 Amaretto (AI Eye) (/mob/camera/ai_eye): setLoc(the floor (211,146,2) (/turf/open/floor/iron/dark), 0)
3 Amaretto (/mob/living/silicon/ai): switchCamera(the security camera (/obj/machinery/camera/directional/west))
4 Amaretto (/mob/living/silicon/ai): Topic("src=\[mob_3143];switchcamera=\...", /list (/list))
5 Carshalash (/client): Topic(Amaretto (/mob/living/silicon/ai), "src=\[mob_3143];switchcamera=\...", /list (/list))
6 /datum/callback/verb_callback (/datum/callback/verb_callback): Invoke()
7 world: push usr(Amaretto (/mob/living/silicon/ai), /datum/callback/verb_callback (/datum/callback/verb_callback))
```

**Comment by Sealed101** [comment]
the issue with failed can_see is happening with objects that are located in coordinates that are divisible by 16, so I'm assuming it's the new chunk creation that's at fault. 

Here, x is 176.
![image](https://user-images.githubusercontent.com/75863639/196939646-6303c0ac-0434-4101-b8b2-323143f2a18a.png)

Chunk coordinates are marked by green circuit tiles, and tiles that are fucking up with `can_see` are marked with blue circuit tiles.
![image](https://user-images.githubusercontent.com/75863639/196951469-6c5b7f0b-71de-433f-bc96-83bceb883d88.png)


<details>
  <summary>So how the fuck?</summary>

The check goes through to `can_see` like this:

https://github.com/tgstation/tgstation/blob/17b6de8b814826ccea58ecce366f4868f7418ef7/code/_onclick/ai.dm#L46-L53

![image](https://user-images.githubusercontent.com/75863639/196940161-00b2e49b-0910-4e0b-909a-c45dc7e581fa.png)

goes through to `checkTurfVis`
https://github.com/tgstation/tgstation/blob/17b6de8b814826ccea58ecce366f4868f7418ef7/code/modules/mob/living/silicon/ai/ai.dm#L856-L864

![image](https://user-images.githubusercontent.com/75863639/196940694-4e447617-e1b7-4813-b5f5-44ebc394e23f.png)

![image](https://user-images.githubusercontent.com/75863639/196940828-c5cce934-9f5a-4614-9fdc-4f9973562f2b.png)


https://github.com/tgstation/tgstation/blob/17b6de8b814826ccea58ecce366f4868f7418ef7/code/modules/mob/living/silicon/ai/freelook/cameranet.dm#L153-L160

it fails to find the turf and thus returns `FALSE`

</details>

**Comment by Sealed101** [comment]
could not replicate the PDA or the crew monitor issues, though
RnD server console in the linked round is located on (138, 96, 2), which were not working due to the AI GRID OF DOOM described above

**Comment by scriptis** [comment]
This makes it impossible for AIs to interact with their APC and turret control on Delta Station.

**Comment by tnekohue** [comment]
Affects xenobiology/slime consoles.
