### ISSUE TITLE
 Unable to compete Exosuit Materials 1: Stress Failure Test Experiment.

### ISSUE THREAD

**Issue by Squishypone** [tgstation/tgstation#70665]
Reporting client version: 514.1585

## Round ID:
[192675](https://scrubby.melonmesa.com/round/192675)

## Testmerges:
- [Swaps sleep() to use SECONDS define](https://www.github.com/tgstation/tgstation/pull/70452)
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)

## Reproduction:
 1. Damage a exosuit to the requested percentage.
 2.  try to scan it using the Experi-Scanner.
 3.  Receive the message "The APLU MK-I "Ripley" is not related to your currently selected experiment."
 4. cry

**Comment by msgerbs** [comment]
Did some digging, this isn't actually broken, the feedback is just bad. You'll get this message if the mech isn't the right damage % which is +/- 2% of the target.

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/68691

**Comment by msgerbs** [comment]
But this issue report was made after that PR was merged?
