### ISSUE TITLE
Under certain conditions involving the arena shuttle, borgs can be forced to drop their held item.

### ISSUE THREAD

**Issue by dopamiin0** [tgstation/tgstation#70675]
## Reproduction:
Be AI shell mediborg
Have my circular saw out, bloodied from battling the xeno menace
Emergency shuttle arrives
It's the arena one (I forget the exact name, but the one that teleports you into an arena and forces you to fight)
Enter the teleporter into it with my circular saw selected
My circular saw is now on the floor of the arena

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/6a0fe4fe8c78186ac6c0a7d92062be3480d68e9a/code/game/area/areas/shuttles.dm#L287-L299

https://github.com/tgstation/tgstation/blob/a2a2c2da24293785ab4ddc52bd7ec248d0dbcf53/code/datums/status_effects/buffs.dm#L341-L380

Looks like it's the mayhem status effect causing mobs to drop held items.
