### ISSUE TITLE
Picking a name as Space Dragon crashes your game.

### ISSUE THREAD

**Issue by Xander3359** [tgstation/tgstation#70688]
Reporting client version: 514.1589

## Round ID:
[192717](https://scrubby.melonmesa.com/round/192717)

## Reproduction:
As a traitor with the space dragon legendary objective, become a space dragon. When the popup shows up for choosing a name, hitting submit causes your game to close.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/e1447a60e97541f0030c760e3481485522457f08/code/modules/mob/living/simple_animal/hostile/space_dragon.dm#L181-L194

**Comment by Salex08** [comment]
tested it out in local server didnt crash my game

**Comment by Mooshimi** [comment]
Wait this is Traitor -> Legendary Space Dragon final objective, does that make a difference

**Comment by SkeletalElite** [comment]
> Wait this is Traitor -> Legendary Space Dragon final objective, does that make a difference

Was still unable to reproduce in local using the traitor objective

**Comment by Xander3359** [comment]
Sorry to the people who tried reproducing this, it was a issue on my end.
