### ISSUE TITLE
Nukie tablets have no name and come with a nonexistent pen

### ISSUE THREAD

**Issue by Rhials** [tgstation/tgstation#70692]
## Round ID:

Tested locally

## Testmerges:

N/A

## Reproduction:

Make yourself nukie

Your tablet should be named "()"

Pulling out your pen gives you a message along the lines of "you remove the /obj/item/pen from the ()" and will not give you a pen

**Comment by ShizCalev** [comment]
@JohnFulpWillard I'm guessing

**Comment by JohnFulpWillard** [comment]
The name thing is fixed in https://github.com/tgstation/tgstation/pull/70679 but I'll have to check about the pen

**Comment by dragomagol** [comment]
Related to #67377
