### ISSUE TITLE
icemoon clockwork ruin genturf

### ISSUE THREAD

**Issue by 1393F** [tgstation/tgstation#70717]
Reporting client version: 514.1589

## Round ID:
[192778](https://scrubby.melonmesa.com/round/192778)

## Reproduction:
its just genturf
![Screenshot (827)](https://user-images.githubusercontent.com/59183821/197274335-8242451e-303a-4509-ac25-4035a6276bff.png)

**Comment by msgerbs** [comment]
Duplicate of #70672

And fixed by #70693
