### ISSUE TITLE
You cannot build the honk mech

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#70712]
Reporting client version: 514.1589

## Round ID:
[192747](https://scrubby.melonmesa.com/round/192747)

## Testmerges:
- [JPS Optimization (Light Botcode)](https://www.github.com/tgstation/tgstation/pull/70623)

## Reproduction: The description says to "honk" but honking does not allow you to add any parts.
![image](https://user-images.githubusercontent.com/54517726/197127078-c5ad51f5-196d-40a6-aa46-e7b4ea2048a6.png)

![image](https://user-images.githubusercontent.com/54517726/197127103-6521e385-5859-461e-b7e6-4e73607a26fd.png)
And i could not put in any boards after honking

**Comment by Profakos** [comment]
You are supposed to use a clown horn. It looks like my funny description that I added in place of no description was not helpful enough :pensive:

**Comment by Baskett55** [comment]
> You are supposed to use a bike horn. It looks like my funny description that I added in place of no description was not helpful enough 😔

the second picture is me using the bike horn and still not being able to add any boards

**Comment by Profakos** [comment]
Very strange then. I only changed the description, and during testing it worked, although, I was using an airhorn.

I did notice that Honk Mech building is buggy in general. It does not consume items for one.

**Comment by Profakos** [comment]
On further check, it is weird that it worked for me while I was testing. Custom Action returns null instead of TRUE when you honk at the mech, which should mean that construction can't advance.

**Comment by Profakos** [comment]
Aha! Indeed, it was me who broke it. Somehow a return got there on that line. I will fix it later today. No GBP for me...
