### ISSUE TITLE
Paper is missing on-mob sprites

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#70746]
Reporting client version: 514.1589

## Round ID:
[192873](https://scrubby.melonmesa.com/round/192873)

## Testmerges:
- [JSON Savefiles | Player Saves use JSON](https://www.github.com/tgstation/tgstation/pull/70492)

## Reproduction:
1. Pick up a piece of paper.
2. Put the piece of paper on your head.
3. Missing Textures.

Putting a piece of paper on your head normally gives you a paper hat, but the sprite seems to be missing.

**Comment by ShizCalev** [comment]
![image](https://user-images.githubusercontent.com/6209658/197370524-f16a0be9-d364-4fb4-a539-272f77a19105.png)
yep.
