### ISSUE TITLE
Moonshine uses generic sprite instead of the XXX bottle meant for it

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#70756]
## Round ID:
various, last tested on 192896

## Reproduction:
- Mix 5u nutriment + 5u sugar with 5u universal enzyme as catalyst. Shudder just as you are to begin your Demoman roleplay session.
- Double checked a hacked booze-o-mat to see if it wasn't meant for an actual bottle (which wouldn't make much sense cuz it's literal moonshine), but that wasn't the case either.
![obraz](https://user-images.githubusercontent.com/68878861/197385046-9a3a3006-6da2-4569-95bf-1a2fcd75dabf.png)
![obraz](https://user-images.githubusercontent.com/68878861/197385054-39781251-6ed8-4952-9b5c-b764a4d7c06a.png)

**Comment by DAKKA-WAAAGH** [comment]
C'est horrible...

**Comment by Thunder12345** [comment]
Intended behaviour. The moonshine bottle uses this sprite, and is craftable with a glass bottle and 100 units of moonshine.

https://github.com/tgstation/tgstation/blob/9f7beefb2640aba4576f5b1b138c1319c6c8d953/code/modules/food_and_drinks/recipes/tablecraft/recipes_drink.dm#L17

**Comment by Likteer** [comment]
@Thunder12345 Do you happen to know if it accepts all manners of alcohol bottles or only the default unlabeled one?
And if so, how does one acquire it?

**Comment by newfren** [comment]
the default unlabelled bottles can be bought in the bartender's vending machine
