### ISSUE TITLE
The nightmare can't dodge energy projectiles.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#70760]
Checked on the private server with the current build version.
## Reproduction:
1) Spawn a nightmare mob.
2) Shoot with an any energy gun.
3) The nightmare will be hit by the energy projectile.
That probably isn't supposed to happen.

**Comment by timothymtorres** [comment]
Were they on a lit tile?  I think their ability to dodge happens only in the dark.

**Comment by IllotAFV** [comment]
It was on the dark tile, ballistic projectiles were avoided, when all of the energy ones connected.

**Comment by timothymtorres** [comment]
> It was on the dark tile, ballistic projectiles were avoided, when all of the energy ones connected.

It could also be that energy projectiles create light.  So this might actually be intended.

**Comment by IllotAFV** [comment]
I am not entirely sure, but back in the days, when it was just added, it was able to dodge the energy projectiles. But I can't find any direct proof of that right now.

**Comment by private-tristan** [comment]
nightmare should be able to dodge lasers #53328
>  balance: nightmares can now dodge beam projectiles on dark tiles

**Comment by timothymtorres** [comment]
Then it's likely someone touched the lighting code since then and now it's too bright.

**Comment by necromanceranne** [comment]
Is this really worth fixing? I don't understand why the shadow monster shouldn't get absolutely destroyed by an intensified beam of _light_.

**Comment by IllotAFV** [comment]
It was the origial design. Moreover, every security officer and some more has an energy gun in their possession. What is the point of that nightmare's power then?
