### ISSUE TITLE
On icebox the RD office, unlike others, is only protected by reinf windoors and reinf directional windows by the left side which can be deconstructed rather easily

### ISSUE THREAD

**Issue by LarissaMayrink** [tgstation/tgstation#70771]
## Round ID:
[192955](https://scrubby.melonmesa.com/round/192955)

## Reproduction:
on icebox the RD office is quite vulnerable due to the lack of SHUTTERS and reinforced full tile windows with gridle bellow as windoors can be deconstructed without a multitool, cannot be bolted down and offer no risk of shocking someone trying to break in

**Comment by msgerbs** [comment]
How on earth are you deconstructing a windoor without access to it? You need to open it first.

**Comment by msgerbs** [comment]
Also you literally have to break into xenobio to get into the RD's office this way, at which point it's not exact much of a stretch to also get through another door. I think this is a nothingburger of an issue and honestly it's _faster_ to get through a door than a windoor, multitools are not hard to come by and you can't hack a windoor. The CMO and QM both have doors directly to maint which the RD does not. I don't feel this is an issue. If you want to remap it yourself or convince somebody else to do it for you, feel free but it doesn't belong here as an issue report.
