### ISSUE TITLE
I just want to hear the felenids laugh

### ISSUE THREAD

**Issue by Magic101lvl** [tgstation/tgstation#70789]
## Reproduction:

Felenids use the same sound files for screaming as humans, but they do not have a laugh sound file, although it would be logical to have exactly the same sound as humans, but silence instead.

**Comment by ArcaneDefence** [comment]
https://github.com/tgstation/tgstation/pull/48004

**Comment by Time-Green** [comment]
> Im going to say this is not an issue for now, since the is_human check returns based on if it's a person not based on species (it's sort of mislabeled
> 
> https://github.com/tgstation/tgstation/blob/45280b6f7537cdf5adebbd8ef1e0ceaa154dce69/code/modules/mob/living/emote.dm#L263-L270
> 
> Feel free to reopen if anyone else feels otherwise

This should be a bug just for how incredibly awful this code is

**Comment by Mooshimi** [comment]
> > Im going to say this is not an issue for now, since the is_human check returns based on if it's a person not based on species (it's sort of mislabeled
> > 
> > https://github.com/tgstation/tgstation/blob/45280b6f7537cdf5adebbd8ef1e0ceaa154dce69/code/modules/mob/living/emote.dm#L263-L270
> > 
> > Feel free to reopen if anyone else feels otherwise
> 
> This should be a bug just for how incredibly awful this code is

Is there another laugh track meant for other species in the code though

**Comment by Time-Green** [comment]
> > > Im going to say this is not an issue for now, since the is_human check returns based on if it's a person not based on species (it's sort of mislabeled
> > > https://github.com/tgstation/tgstation/blob/45280b6f7537cdf5adebbd8ef1e0ceaa154dce69/code/modules/mob/living/emote.dm#L263-L270
> > > 
> > > Feel free to reopen if anyone else feels otherwise
> > 
> > 
> > This should be a bug just for how incredibly awful this code is
> 
> Is there another laugh track meant for other species in the code though

No, but istype checks for species are just absolutely awful. This specific piece of code encourages those really afwul istype species else if chains. This should just be asking the species datum or a derivate thereof, like the tongue or something. It would've been so easy to just do it proper from the start
