### ISSUE TITLE
cargo lathe cannot produce rcds

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#70791]
Reporting client version: 514.1589

## Round ID:
[193056](https://scrubby.melonmesa.com/round/193056)

## Testmerges:
- [[DNM] Include __FILE__:__LINE__ with every log](https://www.github.com/tgstation/tgstation/pull/70780)

## Reproduction:
search rapid
it's not there anymore
it used to be
mining could use them to seal up pits and such it was very helpful
:(

**Comment by Mooshimi** [comment]
> I'm fairly certain RCDs (and maybe RPDs as well) were deliberately removed from cargo lathe, so it's unlikely they are gonna make a comeback.
> 
> What would be nicer is if we got a new bluespace capsule that works exactly like the standard 5x5 pod capsule does, but only deploys a non-defined area 5x5 floor. Put it in a mining vendor for like 50-100 points, make it only work on a chasm tile if worried about balance, problem solved. This idea coming from me currently using 5x5 pod capsules that way to seal chasms.

you know you can put iron rode over chasms right

**Comment by rasepretep** [comment]
> you know you can put iron rode over chasms right

I do. It's my go to if I don't have a pod capsule on me, since those are quicker to use.
