### ISSUE TITLE
Cloth golems say they are magic immune when they are not magic immune

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#70802]
Reporting client version: 514.1589

## Round ID:
[193106](https://scrubby.melonmesa.com/round/193106)

## Reproduction: Go into a cloth golem shell and read description
![image](https://user-images.githubusercontent.com/54517726/197918714-309f5f91-ca41-43c0-9eb4-ca7b9d32bcef.png)
I then used wizard magic to smite the golem and the golem got gibbed

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/9edf99cc204bfbc232e9db3b6070fb5c5b913ff4/code/modules/mob/living/carbon/human/species_types/golems.dm#L805-L811

**Comment by Baskett55** [comment]
i tested with both cult stun hand and wizard smite hand and they both worked

**Comment by Baskett55** [comment]
as in, they both worked on the golem

**Comment by timothymtorres** [comment]
Relevant PR https://github.com/tgstation/tgstation/pull/67775
