### ISSUE TITLE
Russian revolver can lethally hold people up

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#70823]
Reporting client version: 514.1589

## Round ID:
[193152](https://scrubby.melonmesa.com/round/193152)

## Reproduction:

Grab a russian revolver, try shoot people with it, fail
Right click on the person from an adjacent position to hold them up
If they now move or are moved they will take a lethal shot from the gun

While kinda funny this feels like an oversight rather than intended (?)

**Comment by ArcaneDefence** [comment]
God I love the russian revolver
