### ISSUE TITLE
Bileworms resurrect into Vileworms when the change is applied 30 minutes in

### ISSUE THREAD

**Issue by rasepretep** [tgstation/tgstation#70865]
Bileworms are set to start as Bileworms and then mutate into Vileworms at around the 30 minute mark. I feel like it's an oversight when not only living Bileworms, but also their corpses, turn. This results in any dead Bileworm that hasn't been gibbed resurrecting into a Vileworm.

## Round ID:
Any recent round post: https://github.com/tgstation/tgstation/pull/70321

**Comment by Sealed101** [comment]
ive informed @tralezab about it this week

personally i think this is a funny and cool feature and it blends well with the whole vileworm shtick
