### ISSUE TITLE
Atrocinator does not work correctly

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#70875]
## Round ID:
Found on https://github.com/Skyrat-SS13/Skyrat-tg

## Reproduction:
A Modsuit with the Atrocinator module does not turn you upside down, it just seems to make you float instead of what it did before (walk on ceilings). It doesn't even lift you up Z levels if you move to an open space.

**Comment by Mothblocks** [comment]
> If you are reporting an issue found in another branch or codebase, you MUST link the branch or codebase repo in your issue report or it will be closed.

**Comment by Time-Green** [comment]
Give me a ping when you've updated the issue

**Comment by YakumoChen** [comment]
@Time-Green 
sure, although if I get flamed for playing on the dumb furry server that's on you

**Comment by Mothblocks** [comment]
we just ban people like that

**Comment by necromanceranne** [comment]
I've managed to reproduce this on current upstream. What it effectively does currently is just give you zero-g. That's it.

It appears that NEGATIVE_GRAVITY simply isn't achievable anymore. As a result, it's defaulting to normal zero-g instead, which means we get none of the interesting negative gravity stuff of the atrocinator.
