### ISSUE TITLE
Halloween high functioning zombies can't succumb emprisioning them in a eternal crit state unless ghosted

### ISSUE THREAD

**Issue by LarissaMayrink** [tgstation/tgstation#70877]
## Round ID:
[193309](https://scrubby.melonmesa.com/round/193309)

## Reproduction:
Halloween high functioning zombies can't succumb emprisioning them in a eternal crit state unless ghosted

**Comment by Boopideedoo** [comment]
Oof

**Comment by LarissaMayrink** [comment]
According to PositiveEntropy zombies have no_death trait and thats whats causing them to burn in lava eternally and still not die
