### ISSUE TITLE
Halloween races are un selectable

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#70873]
## Reproduction:

- Halloween races, despite it being Halloween, are not selectable. This is because the roundstart races list is instantiated before the holidays list is. 

![image](https://user-images.githubusercontent.com/51863163/198757685-c46c5824-326b-4d07-bd37-f1f1b11b00d0.png)

![image](https://user-images.githubusercontent.com/51863163/198757721-fe1d3b19-1a1c-4692-bd9a-b896483dd822.png)

![image](https://user-images.githubusercontent.com/51863163/198757790-c08b859e-f4dd-4242-bd27-5f24e89e32a9.png)

**Comment by Jackraxxus** [comment]
Karma for ruining vampires

**Comment by Mooshimi** [comment]
i saw people as Halloween races so fixed right?
