### ISSUE TITLE
Implanting engineering skillchip does not give wire-vision

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#70884]
## Reproduction:

I joined as a xenospawn iron golem, became a bluespace golem and then got an assignment to engineering. The chief engineer gave me the engineering skillchip. I went to library skillchip machine and got it implanted, but it did not give me the wire assignments when looking at a wire UI.

**Comment by private-tristan** [comment]
did you activate it? you need to both implant and press the 'activate' button.

**Comment by Time-Green** [comment]
> did you activate it? you need to both implant and press the 'activate' button.

oh my fucking god
