### ISSUE TITLE
Dullahans can't read, shoot guns or use strip menus

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#70890]
## Round ID:

N/A, local testing

## Testmerges:

N/A

## Reproduction:
Become a dullahan, and try to read your PDA, shoot a gun, or remove someone's clothes. I assume this happens because the head falling off during on_species_gain removes these.

**Comment by Time-Green** [comment]
You can switch to body mode to circumvent a lot of these, but stuff like computers and machinery will still see you as 'blind'

**Comment by Mooshimi** [comment]
@LarissaMayrink 's in detail exploration of this:
> Dullahans cannot take off handcuffs and other things off people, have no radio, cannot interface with any computers, vendors, consoles, cannot use health scanners and others except the little atmospheric reader one, can't fire guns, can't fire staffs, can't get spaceproofed because without the helmet you still take pressure damage, can't wear modsuits
> 
> Dullahans can't be cheffs because they can't even vent their tools <br>Cant be bartender because they can't use the dispenser <br>Can't be botanist because they can't read the trays nor use the vendors <br>Can't be engineers because they can't spaceproof nor use many of the tools <br>Can't be chemists because they can't interface with any machine, including the plumbing tool <br>Can't be doctors because they can't use the health scanner nor surgery computer <br>Can't be cargo techs because they can't use the console nor the taggers <br>Can't be atmos because they can't use the pipe dispenser, nor the alarms, nor the pumps <br>Can't be scientist nor roboticists because they cannot do absolutelly anything in there <br>Can't be security because no hud and no guns <br>Can't be geneticists because computers <br>Can't be miners because you can't fire the kpa <br>Can't be chaplain because you can't chose your rod form nor order your armor <br>Can't be miner because you can't use the janitor cart nor the lights replacer

**Comment by Time-Green** [comment]
Other one seems more detailed, can also keep that one open

**Comment by Mooshimi** [comment]
it's why i moved the details here


> Other one seems more detailed, can also keep that one open
