### ISSUE TITLE
Traitor objectives dont seem to change. Cant roll final objective. Heirloom theft is much more common

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#70906]
## Round ID:
[193339](https://scrubby.melonmesa.com/round/193339)

## Reproduction:
Be a traitor and get a ton of heirloom theft objectives. For the first hour have your objectives rarely change. Then for the nest hour notice your objectives don't change at all. And don't roll your final objective once you reach legendary reputation.
Almost certainly related to https://github.com/tgstation/tgstation/pull/70856

**Comment by Time-Green** [comment]
@Watermelon914

**Comment by LarissaMayrink** [comment]
From my experience it seems like the final objective spawns only after you've done enough objectives, not about your total rep.

Yesterday i got the core theft one but heirloom is indeed too common

**Comment by Sealed101** [comment]
relatively old issue with no follow-up, and we've had a recent rework touching steal objectives. probably not an upstanding issue anymore

**Comment by Watermelon914** [comment]
this was never a bug by the way
