### ISSUE TITLE
Sales tagger doesnt work, also "QOL" change actually harshly affected the accessibility of custom vendors

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#70909]
Reporting client version: 514.1582

## Testmerges:
- [Fix halloweens races](https://www.github.com/tgstation/tgstation/pull/70874)

## Reproduction:
Try to print sales tagger for my custom vendor shop
Cant print it from autolathe
Look up and read that #70314 merged it with export scanner as some "QOL" pr 
Break into cargo
Cant print from cargo printer
Have to get the universal scanner from QM locker (LIMITED AVAILABILITY?!??!?!) (Edit:) melbert pointed out you can also buy up to 3 from the youtool vendor for 95 credits each
Set it to sales function
I can only set the price of items to 1, no matter what number i input making my custom vendor pretty much useless.

**Comment by moocowswag** [comment]
Also the universal tagger goes invisible when you change it to one of the modes.

**Comment by Sealed101** [comment]
@ArcaneMusic

**Comment by ArcaneMusic** [comment]
All cargo staff also start the shift with a universal scanner, and within all shipping boxes (The orange boxes in tool storage), you will find one as well. Being in a vending machine as well means they are not limited in their quantity and availability, yes.

You appear to have neglected to right click to change the price of the sales function.

The missing sprite is totally 100% my fault however.

**Comment by moocowswag** [comment]
> You appear to have neglected to right click to change the price of the sales function.

I used alt click while on sales function like i normally do..
