### ISSUE TITLE
Head's organ vars are never set by default

### ISSUE THREAD

**Issue by JohnFulpWillard** [tgstation/tgstation#70916]
## Reproduction:

1. Spawn as/a human
2. Go in their VV -> their head
3. 

![image](https://user-images.githubusercontent.com/53777086/198882773-db4358dc-7fcc-478e-83bd-3a691acfdbdd.png)
![image](https://user-images.githubusercontent.com/53777086/198882780-a555ac74-3ada-4432-9fbe-40dc7f25f113.png)
![image](https://user-images.githubusercontent.com/53777086/198882783-1f2d5ef2-4ae9-4ac7-9537-b340f08b1bfe.png)
![image](https://user-images.githubusercontent.com/53777086/198882784-6f4ea9e6-65ec-4c4a-bc01-5cd4740217c3.png)

@Time-Green 

It's set on ``transfer_to_limb`` but it doesn't seem to be called by default. The only exception to this is dullahan which manually sets their eyes. It's one of the main causes of https://github.com/tgstation/tgstation/issues/70913

**Comment by Kapu1178** [comment]
Organs are stupid and only transfer to their limb when the limb is dismembered, since thats the only time organs are in limb contents. Why is this the case? Mothblocks said it was so `ex_act()` didnt apply to organs inside of mobs.

**Comment by JohnFulpWillard** [comment]
what da hell

**Comment by Time-Green** [comment]
This conversation repeats every three months, it’s just so weird. I got the talk when I tried to change it 😢
