### ISSUE TITLE
New R & D servers don't create additional research points

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#70912]
In the station i demolished some walls to make room for additional R & D servers as shown below

![Screenshot (31)](https://user-images.githubusercontent.com/110812394/198870883-820bfeed-5f24-4fe0-90ff-04a9e1c09250.png)

I also checked the server console to see if all 6 of my servers are online

![Screenshot (32)](https://user-images.githubusercontent.com/110812394/198870939-e0b75494-17b4-4135-9310-7f03e7386b1c.png)

Put in spite of all 6 of my servers being online and also upgraded with tri phasic scanning module and also the freezer upgraded with blue space matter bins and quad ultra micro lasers to cool the room down to 3k i'm still only generating only 52.3 points per second

![Screenshot (33)](https://user-images.githubusercontent.com/110812394/198871026-7720e616-da1e-4356-8e65-22b264f07b39.png)

The wiki page says upgrading the server with higher tier scanning modules don't do anything i get that part but more number of servers should mean higher generation of research points right?

**Comment by LarissaMayrink** [comment]
pretty sure this is intended

**Comment by JohnFulpWillard** [comment]
You can't get more research points by building new machines and that's intended. Point generation only requires 1 machine and will generate a static cost.
