### ISSUE TITLE
You can get a steal heirloom objective for the same thing from the same person multiple times

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#70925]
## Info:
You can sometimes get the "Steal Heirloom and destroy" objective as a traitor for the same persons same heirloom multiple times
such as: "Steal Gotts Bagguete and destroy it" twice
This might be due to said person being the only person with the heirloom quirk during objective generation
## Reproduction:

1. be traitor
2. RNG moment, get two available objectives for stealing a heirloom and destroying it for the same object
3. free TC

**Comment by Profakos** [comment]
Found out what caused this. The duplication checker proc removes objects from the list of crewmembers, effectively doing nothing.
