### ISSUE TITLE
Balloonify ore pickups doesn't remove chat spam as it should.

### ISSUE THREAD

**Issue by rasepretep** [tgstation/tgstation#70928]
So the point of that garbage PR was to move the ore pickup spam from chatbox to middle of screen. Seems to me it's not exactly working as intended and in fact made things worse.

![lol](https://i.imgur.com/X3YdC4I.png)

## Round ID:
Any recent round post https://github.com/tgstation/tgstation/pull/70487

**Comment by Mothblocks** [comment]
@Mooshimi The "Feedback" label is for the feedback database table, which I admit is a bit confusing

**Comment by Mothblocks** [comment]
@GuillaumePrata

**Comment by GuillaumePrata** [comment]
It is working as intended indeed.

The message you are showing is the default message you get when an item is added to your inventory.
Ore bags used to send their own message on top of the generic one for double the chat spam, that one was unnecessary and turned into a balloon alert as it works better as one.

Turning this generic "add to inventory" message into a balloon alert is something I would like to look into the future but it needs to be it's own PR as it has it's own issues to be discussed.

**Comment by Mothblocks** [comment]
Makes sense to me

**Comment by rasepretep** [comment]
> Makes sense to me

... how does that make sense to you? They are two identical (although one is shortened) messages, displayed in two different places, one of which is still causing spam in chatbox that the PR was supposed to remove. How in the world does that make the least bit of sense?

**Comment by Mothblocks** [comment]
I think you were the person who pinged me on Discord last night for an answer but for posterity: it's because the PR in question removed some redundant messsages, and that part worked. That its scope was not higher is not a bug.
