### ISSUE TITLE
Admin logs don't persist after the round ends

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/tgstation#7096]
(Not related to public logs)

A lot of the things normally logged into the admin log (Secrets menu admin log, investigate verb logs) doesn't get logged into the game log.

The game log persists after the round ends and can be retrieved in the future. Admin logs are wiped every round.

Either save admin logs as their own log file, or log everything into the game log.

**Comment by hornygranny** [comment]
This isn't really enough information to be helpful. I'm assuming you mean some things that have message_admins don't also log to the game?

**Comment by MrStonedOne** [comment]
He is referring to the admin log button in the secrets panel

**Comment by Ikarrus** [comment]
Sorry, allow me to clarify.

I believe we have two procs log_game() and log_admin() or something to that effect. There are some actions that are logged into admin logs (which are not persistent) without being logged into game logs.

I just want to log whatever isn't already logged into the game log

**Comment by Carn** [comment]
We really need a system where these thing log with some sort of class spans. That way they can be filtered clientside with javascript to make them easy to view.
I'm pretty sure the only reason I made the investigate verb for stuff like singularities was because the admin log is soooooooo spammy
