### ISSUE TITLE
Ethereals do not regain glow after lighteater

### ISSUE THREAD

**Issue by KittyNoodle** [tgstation/tgstation#70964]
## Reproduction:

1. Be ethereal
2. Be hit by a light eater
3. Loose glow
4. Wait to regain glow
5. 10 minutes later:
6. Still no glow

**Comment by Serxule** [comment]
thats intentional because of how lighteater works

**Comment by KittyNoodle** [comment]
slightly confusing word, but you don't actually get it back after being lighteatered and there is no way to regain it

**Comment by Mooshimi** [comment]
> slightly confusing wording, but you don't actually get it back after being lighteatered and there is no way to regain it

light eater eat your light.... yum :)

**Comment by moocowswag** [comment]
Emag might fix it.

**Comment by KittyNoodle** [comment]
The light eater calls a light emp proc, which _should_ be returning the light after around 10 seconds.
However for whatever reason it’s not, I assume this bug also applies to emps, will do some testing later today.

**Comment by Mooshimi** [comment]
https://github.com/tgstation/tgstation/blob/60ee087b168b57a6716410cf1c2af81f3f3d6dd5/code/datums/elements/light_eater.dm#L85-L93
https://github.com/tgstation/tgstation/blob/60ee087b168b57a6716410cf1c2af81f3f3d6dd5/code/datums/components/light_eater.dm#L54-L66

where is this 10 second timer you speak of, did i miss it

**Comment by Mooshimi** [comment]
> Emag might fix it but what confuses me is, arnt bioluminescent light sources supposed to be immune to light eater? Like lumi mushrooms, glowy mutation, slime person with yellow extract.
> 
> I think some of those are immune but i could be wrong and nothing is immune.

see line 88 of the above comment's first block of code, there's a block light eater component
