### ISSUE TITLE
Selling Gas Canisters only nets 10 cred.

### ISSUE THREAD

**Issue by Xander3359** [tgstation/tgstation#70971]
Reporting client version: 514.1589

## Round ID:
[193503](https://scrubby.melonmesa.com/round/193503)

## Testmerges:
- [(hopefully) improvements to use of scope and kinesis module](https://www.github.com/tgstation/tgstation/pull/70934)

## Reproduction:
Fill up a canister with any gas.
Scan the canister with export scanner (It shows up as worth 10 cred)
Try selling the canister to cargo anyways, (It sells for 10 cred)
![image2](https://user-images.githubusercontent.com/66163761/199183914-44a25b05-b677-436c-9d7e-ef899fbb06d3.png)
![image3](https://user-images.githubusercontent.com/66163761/199183920-f7ea918e-32d5-410f-8d05-09b09bc3cada.png)
![image1](https://user-images.githubusercontent.com/66163761/199183921-b1215fd9-edcb-4f43-b49f-05ab5291d47f.png)

**Comment by SyncIt21** [comment]
Not a bug. If u read the [wiki](https://tgstation13.org/wiki/Atmospheric_Technician#Sell_Gas_for_Fun_and_Profit) ur cannister should have gas at room temp and  less than 2500kpa of pressure else price goes down badly.  

This prevents atmos ppl from getting filty rich by shoving a ton if gas in one cannister instead they have to work to fill up multiple canisters and if they run out of cannister they have to order or make more

**Comment by Serxule** [comment]
yeah this is intended

**Comment by Jackal-boop** [comment]
> yeah this is intended, also p sure you cant even sell any of those gasses since they're basic ones

You can sell any gas for credit.
But yeah this is intended.
PV=NRT muh boy Xander. Keep it room temp!

**Comment by RandomGamer123** [comment]
A slight note that when checking bugs and stuff that this explanation here is slightly misleading:

There's a [hardcoded list of gases to check](https://github.com/tgstation/tgstation/blob/master/code/modules/cargo/exports/large_objects.dm#L128-L143), and oxygen, nitrogen, plasma, and water vapor are all not on that list, and therefore yield **nothing** when sold.

For gases that yield something, sale price is independent of temperature, and only dependent on mole count, it's just that the higher amount of moles you have, you get significantly diminishing returns, which approach `base_value/0.00033` (30303 credits for antinob, 16667 credits for healium, for example) as mole count approaches infinity. However, just `ln(2)/0.00033` = 2100 moles are enough to reach 1/2 of the maximum value, while 4200 moles would just get you 3/4th of the maximum value, 6300 moles would give you 7/8th the maximum value, 8400 moles would give you 15/16th of the maximum value, et cetera.

Therefore, if you're interested in selling gases, first make sure they are actually worth something, and then just split them up into lots of cans, ideally each one under 2000 moles or so, to maximum their value.
