### ISSUE TITLE
Flux anomalys repeatedly stun even if you arent touching it

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#70975]
## Reproduction:
 1. go to supermatter to fix delamination
 2. be next to a flux anomaly (not touching) 
 3. get repeatedly stunned and burned by it, despite never even going onto your tile (which is what should cause shocking) or touching you (it happens even when downed and still not on your tile)

**Comment by Mothblocks** [comment]
```
https://github.com/tgstation/tgstation/blob/a625fc8038f264c7fdb978bbde3e533aaba20373/code/game/objects/effects/anomalies.dm#L234-L235
```

Interesting

Are you sure it's not the supermatter (or whatever is actually doing it) dragging you into the anomaly repeatedly?

**Comment by Serxule** [comment]
> https://github.com/tgstation/tgstation/blob/a625fc8038f264c7fdb978bbde3e533aaba20373/code/game/objects/effects/anomalies.dm#L234-L235
> 
> Interesting
> 
> Are you sure it's not the supermatter (or whatever is actually doing it) dragging you into the anomaly repeatedly?

had CE magboots, anomaly was diagonal from me when it started shocking

**Comment by Sealed101** [comment]
was it the anomaly really
![изображение](https://github.com/tgstation/tgstation/assets/75863639/0200b779-0def-4e1d-82e6-2037578e0df2)
i don't see any sort of electrocution logging in place when a flux anomaly does it, you've been shocked by the SM most likely?
