### ISSUE TITLE
regen cores are bugged and cant be stabalized

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#70994]
## Round ID:
[193548](https://scrubby.melonmesa.com/round/193548)

## Testmerges:
[#70934: '(hopefully) improvements to use of scope and kinesis module' by Fikou at commit 35c7b2c352](https://www.github.com/tgstation/tgstation/pull/70934)

## Reproduction:
![image](https://user-images.githubusercontent.com/61211748/199360383-c756e2b7-e42c-40b7-99ac-a0b614546153.png)
try to stabalize a regen core and this happens

**Comment by Sealed101** [comment]
if it was already decayed you will not be able to rejuvenate it, that has been a thing before but it was fixed in #70546

**Comment by Jackal-boop** [comment]
> 

Mmmmmmmmmmmmmmmmmmm

Bruh
