### ISSUE TITLE
Plumbing: End manual typing of reagent names

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#71004]
This isn't actually a bug it works but it's really bugging and annoying and extremely error prone so might as well list it as a bug.

Inside plumbing devices which requires reagent names to work such as the Chem filters & plumbing reaction chambers remove the text box which asks the user to enter the reagent name manually and replace it with a drop down box containing all available chemicals in the game so the user can pick and choose without making mistakes. 

For long chemical names typing them in the text box  is a pain.

**Comment by Mothblocks** [comment]
The issues page is for bugs only.

BTW I would deny this PR if it was like this since the proper UX is just a live search bar with autocomplete based on chemical names
