### ISSUE TITLE
text for being implanted is no longer large

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#71001]
## Reproduction: 
be in revolution, get implanted at some point without knowing, get killed by revs and see you're implanted, look back in chat and see how small the text is 
![Screenshot_1109](https://user-images.githubusercontent.com/64584757/199387013-cc3890b6-7d9c-436a-a5da-62a3dc5467e6.png)

**Comment by LarissaMayrink** [comment]
Don't think thats a problem, what part of passing out and not seeing the giant red and blue R on top of people did you miss?

**Comment by Serxule** [comment]
> Don't think thats a problem, what part of passing out and not seeing the giant red and blue R on top of people did you miss?

i was never converted, and yes it is a problem because afaik it used to be big text, this means that you can stealth implant revs that arent focusing on the chat

**Comment by Ryusenshu** [comment]
i agree that it is an issue, i have seen sec stealth implant people before
it really sucks

**Comment by Time-Green** [comment]
I’ve had this happen to me aswell, was really confused sec trusted me so much during a revolution and surprise surprise, I was stealthimplantee.

Should probably just throw a balloon pop-up, but that’d be more of a balance change since this isn’t a bug

**Comment by moocowswag** [comment]
If its not intentional for implants to not be obvious, then it might be a QOL for the text to be bigger.

**Comment by Mothblocks** [comment]
@Time-Green It's a bug if it used to be big and changed and no PR intentionally did that, we should investigate that first before calling this not a bug

**Comment by Mothblocks** [comment]
It should be both a balloon alert for visiblity and a chat message since it's important to archival tho

**Comment by Mothblocks** [comment]
@Serxule Which part of this text used to be large?

**Comment by Serxule** [comment]
> @Serxule Which part of this text used to be large?

pretty sure the first message for being injected/implanted, definitely remember there being large text before

and i think there was something like: "**[name] is trying to implant/inject you with [thing]!**", could be another server im thinking of though

**Comment by Mothblocks** [comment]
Checking blames suggests this was not the case, you might be thinking of something else
