### ISSUE TITLE
Chess holodeck simulation can produce infinite metal

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#71019]
## Reproduction:
1. set holodeck to chess
2. deconstruct chesspieces with wrench
3. set holodeck to something else, then chess again
4. repeat
5. profit

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/a302b952266c9bfc12a9374d6bfc479cd815070e/code/game/objects/structures/chess.dm#L10-L19

Just need to do a simple `if(item.flags_1 & HOLOGRAM_1)` check
