### ISSUE TITLE
Heated reagents and Herignis do not raise body temperature

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#71012]
## Reproduction:

Heat reagent then drink/inject, body temperature stays a same. Herignis (This reagent causes a dramatic raise in a patient's body temperature. - Wiki) has no effect on spaceman. Tested on humans.

**Comment by msgerbs** [comment]
Is the temperature of ingested reagents supposed to change your body temp? I've never heard of that before, so that's news to me. Not saying you're wrong, just that it's not a feature I've ever read anything about.

**Comment by LarissaMayrink** [comment]
Herignis increases body temperature when processed, it has nothing to do with the reagent temperature itself

**Comment by Livrah** [comment]
> Herignis increases body temperature when processed, it has nothing to do with the reagent temperature itself

This is why I mentioned it separately.

**Comment by Magic101lvl** [comment]
The absorption of oxygen by pyrosium also does not change the temperature while in the body.

**Comment by antropod** [comment]
last itme I tested herignis didn't work, but it was like half a year ago

**Comment by RikuTheKiller** [comment]
herignis is completely broken due to shitcode, fixing it rn

**Comment by RikuTheKiller** [comment]
> It's not gaining its methods correctly, and defaulting "Touch method", which only increase firestacks

oh and yeah this makes no sense in general, just look at how hercuri works

this shouldnt work completely differently and in a way more retarded manner
