### ISSUE TITLE
tot eyeball item doesnt work

### ISSUE THREAD

**Issue by theta060** [tgstation/tgstation#71021]
Reporting client version: 514.1585

## Round ID:
[193597](https://scrubby.melonmesa.com/round/193597)

**Comment by Profakos** [comment]
Tested on latest, it works, but it really should do a balloon alert about when it fails to work if the target has no eyes or has their eyes covered. I did find a new bug though... it has infinite uses despite being told it works only once.

**Comment by Profakos** [comment]
@theta060 could you retry this please?

**Comment by MrMelbert** [comment]
Has been fixed since
