### ISSUE TITLE
Cyborg Icon not showing light being on when it is on

### ISSUE THREAD

**Issue by Reco201** [tgstation/tgstation#71036]
## Round ID:
N/A found on downstream recreated on a tgstation local

## Reproduction:
Spawn in as a cyborg
Turn light on
Notice the icon does not change having the sprite's light appear to be off
![image](https://user-images.githubusercontent.com/71794877/199764951-a64bd759-05d2-4771-ab6e-06b09090936e.png)

**Comment by ShizCalev** [comment]
Plane issue perhaps?
#70271
