### ISSUE TITLE
Gracefully breaking the Tram is, well, gracefully broken

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#71049]
## Reproduction:

Attempting to blow up the tram with fields results in the following. 

https://user-images.githubusercontent.com/51863163/199876705-fbf266b2-971a-42f9-9c3c-b66249592610.mp4

Expected: A bunch a explosions
Reality: This

**Comment by lessthnthree** [comment]
What's the expected behavior? Looks like it did exactly what it was supposed to. Explode with a 1, 2, 3, 0 explosion and delete the tram.
