### ISSUE TITLE
Iron rod with broken sprite shows every material stack when alt+clicked

### ISSUE THREAD

**Issue by msgerbs** [tgstation/tgstation#71053]
## Testmerges:

- #70492 
- #70162
- #70972

## Reproduction:
To be honest I haven't a clue. I know there was a pyro anomaly in medbay. I went to go clean afterward and found this cursed iron rod that was invisible but showed every material stack sprite when alt+clicking the tile.
![Magic rod](https://user-images.githubusercontent.com/1313921/199890042-f237bf6e-de87-4569-9eb3-65efb6882449.png)

Yeah, that's pretty much it. I lost track of it before I could ask an admin to poke it with varedit cause, ya know, invisible things are easy to lose.

**Comment by Mothblocks** [comment]
Duplicate of #53824

**Comment by msgerbs** [comment]
o.o
