### ISSUE TITLE
TGUI Scripterror (Cant play the game)

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#71055]
## Round ID:
[193682](https://sb.atlantaned.space/rounds/193682)
And several more

## Testmerges:

N/A
## Reproduction:
Since 3 or 4 Days ago i started to have this Error on Terry and it started a day ago on manuel
Every single ingame tgui window is unusable, including Settings
Status Panel and Fancy Chat are fine

![Screenshot_1](https://user-images.githubusercontent.com/95751821/199892373-bffaa466-b25a-40e4-9f01-8e037b5ff31c.png)

A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 
Script error
   at https://tgstation13.download/byond/assets/a8/asset.a8ba281612609441541337e3061bde7c.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)

Nanotrasen (c) 2525-2562

**Comment by Ryusenshu** [comment]
At the time of writing this, Campbell and Sybil do work with those round IDs
193700 : Campbell
193702 : Sybil

Affected by the Error are : Terry, Manuel and Basil

**Comment by Mantatest** [comment]
Same. I guess I can delete my thread then?

**Comment by Ryusenshu** [comment]
> Same. I guess I can delete my thread then?

It will be done if someone reads up on it, but since its the same issue, guess you could delete it
(i like exposure though and really want to play the game again)

**Comment by Mantatest** [comment]
Yea, Ill leave it up. Its more likely to catch an eye that way, right?

**Comment by Mantatest** [comment]
> ## Round ID:
> [193682](https://sb.atlantaned.space/rounds/193682) And several more
> 
> ## Testmerges:
> N/A
> 
> ## Reproduction:
> Since 3 or 4 Days ago i started to have this Error on Terry and it started a day ago on manuel Every single ingame tgui window is unusable, including Settings Status Panel and Fancy Chat are fine
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/95751821/199892373-bffaa466-b25a-40e4-9f01-8e037b5ff31c.png)
> 
> A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation.
> 
> Script error at https://tgstation13.download/byond/assets/a8/asset.a8ba281612609441541337e3061bde7c.js:0 User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)
> 
> Nanotrasen (c) 2525-2562

Ryusenshu, right now the issue seems to have been solved, or solved itself! Get back to it, gamers

**Comment by Ryusenshu** [comment]
Yeah i noticed too, guess i can close this one

**Comment by Ryusenshu** [comment]
Turns out its back, from one round to another (another "asset" though)
Round ID: 194761

![Screenshot_1](https://user-images.githubusercontent.com/95751821/203002450-8738049a-2df3-4ad9-880f-ae45c8736b84.png)

**Comment by Striders13** [comment]
same issue on round 194769, terry

**Comment by Mantatest** [comment]
Yes, its back for me as well. Manuel server

**Comment by jlsnow301** [comment]
#53997
