### ISSUE TITLE
Pepper Spray Sparsity on Icebox

### ISSUE THREAD

**Issue by davethwave** [tgstation/tgstation#71050]
## Round ID:
[193680](https://scrubby.melonmesa.com/round/193680)

## Reproduction:
The only place you can refill your pepperspray in sec is the HOS's office and the labor shuttle as far as I can tell. Which is inconsistent with the other maps. The medbay sec post also doesn't have a pepperspray dispenser as well.

**Comment by msgerbs** [comment]
The text for this label applies very literally here.
