### ISSUE TITLE
BoH TTV Voice Analyzer doesnt work

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#71069]
Reporting client version: 514.1589

## Round ID:
[193706](https://scrubby.melonmesa.com/round/193706)

## Testmerges:
- [JSON Savefiles | Player Saves use JSON](https://www.github.com/tgstation/tgstation/pull/70492)
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)
- [Remove ELEMENT_DETACH on everything that doesn't need it, rename to ELEMENT_DETACH_ON_HOST_DESTROY + a PSA (about 0.2s init time savings)](https://www.github.com/tgstation/tgstation/pull/70972)

## Reproduction:

1. slam a voice analyzer onto that ttv
2. put into BoH
3. attempt to trigger bomb via phrase to kill your murderer
4. no boom, murderer fine, murderer has free maxcap

**Comment by Jackal-boop** [comment]
I don't know if it's intentional or not. But no assemblies seem to work while inside bags

**Comment by mc-oofert** [comment]
apparently voice analyzers dont register whispering
