### ISSUE TITLE
Microwave drops its parts or explodes.

### ISSUE THREAD

**Issue by antropod** [tgstation/tgstation#71063]
No round ID, found while playing on skyrat, reproduced on /tg/ built from master on local server.

When you make new microwave with better then default parts or upgrade existing microwave:
- if you cook anything it explodes
- if you put something in it, then press "eject" it drops matter bin and laser. After that you can use it safely.

## Reproduction:

Upgrade existing roundstart microwave with t4 parts, put spaghetti in it, press "eject" - it ejects matter bin and laser.
Upgrade existing microwave with t4 parts and then cook spaghetti, microwave explodes.

**Comment by Serxule** [comment]
sounds like the parts are somehow ending up literally inside of the microwave, are you using a normal rped or a bluespace one

**Comment by antropod** [comment]
bluespace rped with t4 parts
spawn -> tier4

**Comment by antropod** [comment]
actually it doesn't matter, reproduces with normal one too

**Comment by antropod** [comment]
Most likely caused by #70727
This PR chaged Entered signal handler, and now after upgrade parts end up in the ingredient list
![изображение](https://user-images.githubusercontent.com/7479888/199987052-01828ef3-b1f3-4152-bec8-91e4d7daf484.png)

**Comment by ShizCalev** [comment]
Lmao, forgot about upgrades. Ez fix.
