### ISSUE TITLE
A fatal exception has occured in TGUI. Cant open windows within the game. Halp

### ISSUE THREAD

**Issue by Mantatest** [tgstation/tgstation#71071]
Hello, this is my first report.
Since I believe 2 days ago, whenever I want to open a window within the game, like for example when I want to use a vendor, customize characters, or use something like adminhelp, a scripterror report of some sort pops up. The first line reads the following: 
"A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation."

So this is what I do now.

Script error
   at https://tgstation13.download/byond/assets/a8/asset.a8ba281612609441541337e3061bde7c.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; Zoom 3.6.0)

I hope this is the right place. The game itself runs without problems. I play on the Terry [EU] standard server, which now that I checked changed its name to Larry for some odd reason. Whatever. The round ID is irrelevant I believe. Please tell me if I missed something. It sucks, as I can hardly do anything sensible in game without this function. Thank you

**Comment by SyncIt21** [comment]
Have you tried clearing cache in your Byond client? Open Byond->gear icon top right->preferences tab->clear cache.  
Some of my game crashes and frozen GUI windows were fixed by this. Ur client will have to re-download all the assets again after thoo

**Comment by Ryusenshu** [comment]
> Have you tried clearing cache in your Byond client? Open Byond->gear icon top right->preferences tab->clear cache. Some of my game crashes and frozen GUI windows were fixed by this. Ur client will have to re-download all the assets again after thoo

i have the same issue and that solution doesnt work

**Comment by Mantatest** [comment]
> Have you tried clearing cache in your Byond client? Open Byond->gear icon top right->preferences tab->clear cache. Some of my game crashes and frozen GUI windows were fixed by this. Ur client will have to re-download all the assets again after thoo

Yes, I did. As Ryusenshu said, it did not work :(

**Comment by Tastyfish** [comment]
Close out of tgstation, then:

On Windows, search for Internet Options in the start menu. Opening it should give you this:
![image](https://user-images.githubusercontent.com/1185434/201834401-76f1a002-4518-4980-b74b-28b32e9e41ce.png)

Slap that Delete button towards the top that's already highlighted in the image I posted, and check all the options like so:
![image](https://user-images.githubusercontent.com/1185434/201834551-0e4559d0-2b8e-40cf-a406-5d38ef490b0d.png)

and hit the Delete button at the bottom to confirm.

Rejoin and see if that helps.

**Comment by jlsnow301** [comment]
#53997

**Comment by Imadethisaccounttoreportabug** [comment]
Similar issue to this, but with only the fancy chat

**Comment by jlsnow301** [comment]
> Similar issue to this, but with only the fancy chat

post your error here please
#53997
