### ISSUE TITLE
Pickle Jar Folds Into Cardboard

### ISSUE THREAD

**Issue by Bobthe28th** [tgstation/tgstation#71083]
Reporting client version: 514.1588

## Round ID:
[193733](https://scrubby.melonmesa.com/round/193733)

## Testmerges:
None

## Reproduction:
1. Aquire jar of pickles by crafting or ordering
2. Empty the jar
3. Activate in hand and watch as it magically turns to cardboard

I'm pretty sure this is because it is defined as a fancy box in the code.
~~Is it possible to change the fold_result to a large beaker?~~ When you activate it there is text that says "folded"
https://github.com/tgstation/tgstation/blob/35acc39763321ece6c83e519c38d152d6fd491fb/code/game/objects/items/storage/fancy.dm#L464-L474
https://github.com/tgstation/tgstation/blob/35acc39763321ece6c83e519c38d152d6fd491fb/code/game/objects/items/storage/fancy.dm#L30

**Comment by Mooshimi** [comment]
hmmmmmmmmmmmmmmmmmm i like pickles

**Comment by Shadowflame909** [comment]
future cardboard is very versatile. it makes you think its glass!
