### ISSUE TITLE
Instant Death from Dusty Shard

### ISSUE THREAD

**Issue by Shroomerian** [tgstation/tgstation#71099]
Reporting client version: 514.1589

## Round ID:
[193765](https://scrubby.melonmesa.com/round/193765)

## Reproduction:

I was playing a shaft miner and I got a dusty shard as a reward from the necropolis chests. Somebody becomes my power miner and they proceed to appear in their normal form. The issue came from the fact that when they tried to appear, they were crushed by the door and that killed me and them instantly.

Steps:

1. Gain a dusty shard
2. Use it and have somebody become your power miner
3. Open a door and stand on the right/left of it
4. Power miner appears in their physical form on the door as it closes down
5. Proceed to get immediately crushed.

**This next statement is an opinion and not part of the issue**
(Another issue that dusty shard has is that the holo-parasite sprite appears to be floating, but in fact is not. This creates confusion for power-miners who think they can fly over chasms and in fact end up killing both themselves and their user.)

**Comment by moocowswag** [comment]
The worst kind of noob bait is when a player falls for it, other people suffer immensely for it.

I dont think this will be considered a bug, you might be able to scream oversight because of unintended player behavior due to lack of information / inverse quality of life.

**Comment by Serxule** [comment]
> The worst kind of noob bait is when a player falls for it, other people suffer immensely for it.

? 

> I dont think this will be considered a bug, you might be able to scream oversight because of unintended player behavior due to lack of information / inverse quality of life.

this is definitely a bug in some form, i've had doors close on me and crush me without reopening, and they dont kill me

**Comment by msgerbs** [comment]
Do holoparasites spawn at very low health or something? I don't understand why a door crush would instantly kill it.

**Comment by Jacquerel** [comment]
> Do holoparasites spawn at very low health or something? I don't understand why a door crush would instantly kill it.

Holoparasites don't really have their own health at all, they damage the _owner_ instead and if the owner enters hard crit both of them are instantly dusted.
Why that was enough to instantly kill the miner is still an open question, but it's slightly more possible.

**Comment by msgerbs** [comment]
@Shroomerian What was your character name this round?

**Comment by msgerbs** [comment]
Ok I think I found who you were, the last damage I see before you die has you at 75.5 HP which really shouldn't be enough for you to instantly die to a door crush so idk what happened here unless something fucky happened with your holo. Any idea what their name was?

**Comment by Shroomerian** [comment]
> Ok I think I found who you were, the last damage I see before you die has you at 75.5 HP which really shouldn't be enough for you to instantly die to a door crush so idk what happened here unless something fucky happened with your holo. Any idea what their name was?


I was Wilson Wonder and the Holoparasite's name was Bababooey.

**Comment by msgerbs** [comment]
Can't find the holoparasite in the logs at all unfortunately.

**Comment by Shroomerian** [comment]
Nealy a year of this being open. It's added to bugs so I'm closing the issue.
