### ISSUE TITLE
Flesh Space Suit sprite is missing(?)

### ISSUE THREAD

**Issue by Rhials** [tgstation/tgstation#71107]
## Round ID:

Tested locally

## Testmerges:

N/A

## Reproduction:

Become ling

activate flesh space suit

![image](https://user-images.githubusercontent.com/28870487/200135480-11c7ae26-ee00-431f-8f14-a5187fa2c552.png)
waaaaaaaaaaaghhghg

(doesn't appear on the player sprite either)

**Comment by Serxule** [comment]
clear byond cache, this is probably a problem from that

**Comment by dragomagol** [comment]
![image](https://user-images.githubusercontent.com/66640614/209273816-6fd0b478-b13a-4148-9c31-98095656b2ef.png)

Appears to have been fixed
