### ISSUE TITLE
Syndicate Assault Borgs have Messenger

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#71116]
## Round ID:
[193774](https://sb.atlantaned.space/rounds/193774)

## Testmerges:
N/A

## Reproduction:
> Be Assault Borg
> Get message from a lawyer on your PDA (you somehow have)
> Deny any need for legal Advice

![Screenshot_1](https://user-images.githubusercontent.com/95751821/200143780-fffcbab6-f0f8-45f5-9afb-99bdace04959.png)

**Comment by ShizCalev** [comment]
@JohnFulpWillard
