### ISSUE TITLE
medical borgs cant use downloaded surguries

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#71120]
## Round ID:
[193791](https://scrubby.melonmesa.com/round/193791)

## Reproduction:
![image](https://user-images.githubusercontent.com/61211748/200146726-39e9d72c-e507-4b65-bd26-911ac77a90d3.png)
![image](https://user-images.githubusercontent.com/61211748/200146828-6db2c233-52ff-4217-97b6-e2e6bbabb19e.png)
![image](https://user-images.githubusercontent.com/61211748/200146736-a310a04b-ad61-42c7-9e15-9e97078dd344.png)
try and download surguries from a computer, then you cant use them
the surguries were synced on the operrating computer i used

**Comment by JohnFulpWillard** [comment]
Did you have the item in one of your module-hands?

**Comment by Jackal-boop** [comment]
I don't believe so. But I remember not requiring that when I used it before

**Comment by NeverDawnedNoz** [comment]
Yeah that is strange, you're supposed to be able to use the module anywhere. I haven't been able to use it at all.

**Comment by Sealed101** [comment]
you need to have the processor in one of your active modules to actually benefit from the surgery processor's stored surgeries

![image](https://user-images.githubusercontent.com/75863639/224976002-fca7cfec-d8ca-456d-8486-41ddde0b230d.png)
_____
![image](https://user-images.githubusercontent.com/75863639/224976036-05dc995f-696c-4257-8ba9-b33ca2581134.png)


however it's not told to the player anywhere, which is an oversight
