### ISSUE TITLE
Lavaland mobs break mineral turfs when bumping into them.

### ISSUE THREAD

**Issue by LePiromano** [tgstation/tgstation#71126]

**Comment by private-tristan** [comment]
https://user-images.githubusercontent.com/54422837/200154905-5240b841-7185-4115-9da4-e3206e79042c.mp4

**Comment by Fikou** [comment]
caused by https://github.com/tgstation/tgstation/pull/71008

**Comment by LemonInTheDark** [comment]
bro what
