### ISSUE TITLE
Sprite layering has become randomly insane

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#71127]
## Testmerges:
[#70972: 'Remove ELEMENT_DETACH on everything that doesn't need it, rename to ELEMENT_DETACH_ON_HOST_DESTROY + a PSA (about 0.2s init time savings)' by Mothblocks at commit 05724373f9](https://www.github.com/tgstation/tgstation/pull/70972)
[#70162: 'Changes our map_format to SIDE_MAP' by LemonInTheDark at commit b2f1f2a684](https://www.github.com/tgstation/tgstation/pull/70162)
[#70492: 'JSON Savefiles | Player Saves use JSON' by ZephyrTFA at commit 5c690036d6](https://www.github.com/tgstation/tgstation/pull/70492)

## Reproduction:
Randomly observed.

https://user-images.githubusercontent.com/85910816/200154668-8e527d74-3004-4400-8fc7-3d5c88afcf33.mp4

**Comment by ArcaneMusic** [comment]
@LemonInTheDark This appears to be sidemap specific.

**Comment by LemonInTheDark** [comment]
yep

**Comment by LemonInTheDark** [comment]
was anything moving by it at the time? sprites don't really flicker, they just conflict in layer

**Comment by Mooshimi** [comment]
> was anything moving by it at the time? sprites don't really flicker, they just conflict in layer
 
Not directly near it, how close do you mean?

**Comment by LemonInTheDark** [comment]
literally any object in your view could in theory cause this

**Comment by Mooshimi** [comment]
> literally any object or thing in your view could in theory cause this

then sure yeah 
![dreamseeker-17 38 41 293](https://user-images.githubusercontent.com/85910816/200959395-81edfd02-38e6-4ffd-a356-514a84d26fb2.gif)

![dreamseeker-17 37 52 676](https://user-images.githubusercontent.com/85910816/200959408-32c0826e-7975-4d44-a3c7-983a70d69b97.gif)

**Comment by LemonInTheDark** [comment]
do you have a screen wide view of that? is it consistent at all?

**Comment by LemonInTheDark** [comment]
is it repeatable?
these are quite hard to debug because they involve esoteric byond shit like visual vs actual bounds, and the different rendering details that effect those. That's why I want a screenwide view, so I can see fully what's going on, but it also means that even knowing what's wrong requires having at least some idea of how to cause it

**Comment by scriptis** [comment]
R194095 (Sybil):

https://user-images.githubusercontent.com/12202230/201234179-9d702564-2518-4d95-9d85-36ee88e216a6.mp4

Can't reproduce on local (`LemonInTheDark:roll-the-old-chariot-along`/`b2f1f2a684e7187281cbc5034f6ddeb534bfa125`), but this happens fairly consistently in production with the TM.

**Comment by LemonInTheDark** [comment]
ohhhhhhhhhhhhhhhh lummy

**Comment by out-of-phaze** [comment]
fun fact: it seems Bay was aware of this six years ago https://github.com/Hubblenaut/Baystation12/blob/6f96e73cd050da8ddb13d8100dec6aea3eefe909/code/modules/tables/interactions.dm#L199
asked the PR author what the bug they were referring to was, they said clipping/z-fighting. maybe a lead idk

**Comment by LemonInTheDark** [comment]
This appears to be a bug with alert screens. They hold a long string of text in maptext's of objects inside their vis_contents, and then mask away most of it before displaying/offsetting.
The problem is maptext (UNDOCUMENTEDLY) counts as a visual_bounds expander, so when we maptext_y things down, they (for reasons I do not fully understand) start to cause conflicts with pixelshifted objects.

**Comment by LemonInTheDark** [comment]
Resolved? https://github.com/tgstation/tgstation/pull/70162/commits/2defc0ad20a0ee7d12e0b071f6d31b6127b8765d
It appears to have been an issue of conflicting between the screen and the text on it. offsetting the text down physically and then back up visually ensures it will render over anything sitting on that tile (on that plane). so still slightly cursed, but better I think.
