### ISSUE TITLE
felinids don't like dead mice

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#71138]
https://github.com/tgstation/tgstation/pull/68899

"I just want the cats to eat mice ok."

```
/// Mice turn into food when they die
/obj/item/food/deadmouse
    name = "dead mouse"
    desc = "They look like somebody dropped the bass on it. A lizard's favorite meal."
    icon = 'icons/mob/simple/animal.dmi'
    icon_state = "mouse_gray_dead"
    bite_consumption = 3
    eatverbs = list("devour")
    food_reagents = list(/datum/reagent/consumable/nutriment = 3, /datum/reagent/consumable/nutriment/vitamin = 2)
    foodtypes = GORE | MEAT | RAW
    grind_results = list(/datum/reagent/blood = 20, /datum/reagent/liquidgibs = 5)
    decomp_req_handle = TRUE
    ant_attracting = FALSE
    decomp_type = /obj/item/food/deadmouse/moldy
```
```
    species_language_holder = /datum/language_holder/felinid
    disliked_food = GROSS | CLOTH | RAW
    liked_food = SEAFOOD | ORANGES | BUGS | GORE
```
dead mice have the RAW foodtype, which is in the disliked_food list for felinids. thus, felinids do not like mice, even though they also have the GORE foodtype.

... why exactly are GORE and RAW separate food types, again? like, for which species would we ever want the difference between them ever come into play?

**Comment by Jacquerel** [comment]
RAW is applied to thinks like "uncooked dough", "uncooked pizza", and "eggs" as well as raw meat.
How granular the food groups system really needs to be is of course an open question.

**Comment by NeverDawnedNoz** [comment]
Felinids are humans spliced with Feline DNA in some abomination experiment.
Because they are still somewhat human, they cannot eat raw meat and such...

But SS13 doesn't care.
You can fry food and it won't be so horrible to eat. Oranges merged Felinids loving oranges.

**Comment by Mooshimi** [comment]
According to the pr, remove raw from the mouse so cat may feast

**Comment by dalmationer** [comment]
We could always make them the 'GORE' subtype that orbstation uses?
We split 'gross' and 'gore' food. Gross being food that's actively moldy etc. Gore being stuff with raw meat or blood and guts, and just made felinids and lizards like that. (they're predators innit.)

**Comment by Sealed101** [comment]
https://github.com/tgstation/tgstation/pull/78481#issuecomment-1729260042
