### ISSUE TITLE
Rat king's rats kill each other, and so does he when he isn't possessed by anyone

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#71139]
## Round ID:
[193840](https://scrubby.melonmesa.com/round/193840)

## Reproduction:
Observe the bahviour of Rat King's spawns.

**Comment by ArcaneMusic** [comment]
Rat kings are intended to be hostile to each other.

**Comment by Magic101lvl** [comment]
There can be only one true king.

**Comment by JohnFulpWillard** [comment]
@optimumtact Was something discussed to say this is not behavior we want? Re-opening wordlessly doesn't tell us

**Comment by optimumtact** [comment]
arcane can explain it

**Comment by ArcaneMusic** [comment]
The wording was initially difficult to parse at first glance, but what he means is that a rat king's summoned rats are becoming hostile to their king, and other summoned rats from the same faction, if they are exclusively AI controlled.

Rat kings are intended to have mechanics that give them a single faction that they create upon init, and then pass onto their children. When this was originally implemented, it was meant to work as a way to force multiple rat kings from being friendly to each other, as there can only be one true king (sic). I imagine that the changes to how rat king's domain works by melbert may have had unintended consequences to their faction mechanics.

I'll put it on my list.

**Comment by Likteer** [comment]
No longer the case
