### ISSUE TITLE
Art not rendering when it's on the floor as an object

### ISSUE THREAD

**Issue by Squishypone** [tgstation/tgstation#71142]
Reporting client version: 514.1585

## Round ID:
[193847](https://scrubby.melonmesa.com/round/193847)

## Testmerges:
- [Remove ELEMENT_DETACH on everything that doesn't need it, rename to ELEMENT_DETACH_ON_HOST_DESTROY + a PSA (about 0.2s init time savings)](https://www.github.com/tgstation/tgstation/pull/70972)
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)
- [JSON Savefiles | Player Saves use JSON](https://www.github.com/tgstation/tgstation/pull/70492)
- [Adds logic to provide leniency for drag clicks](https://www.github.com/tgstation/tgstation/pull/71082)

## Reproduction:
 When printing or taking art off the wall,  It appears blank
 Oddly, you can see it when it's in your hand, but not when it's on the floor.
 Another weird thing, this issue does not affect large paintings
 Last thing, I also think this affects the AI painting display but I only tested it once.
1. print or take art off the wall.
2. see blank art

**Comment by Sealed101** [comment]
only some canvases are affected, canvas sizes of 45x27 and 36x24 show up fine
![image](https://user-images.githubusercontent.com/75863639/225308827-8543702d-ca7a-4ac3-80da-4191dd25ac2e.png)

**Comment by Squishypone** [comment]
Weirdly, this was fixed at one point, but it broke again. I don't know what happened or when it did
