### ISSUE TITLE
Bare rock in tramstation arrivals

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#71145]
Reporting client version: 514.1585

## Round ID:
[193855](https://scrubby.melonmesa.com/round/193855)

## Reproduction:
arrive at the station
go down
![image](https://user-images.githubusercontent.com/36141254/200200413-9dca8602-adae-435f-ae8e-9616b72f35bc.png)

**Comment by msgerbs** [comment]
Fairly certain this is intended and exists in several areas.

**Comment by msgerbs** [comment]
Yeah, this is part of one of the modular maint segments. Not a bug.
