### ISSUE TITLE
If the first Lavaland ash storm is an ember storm, the sounds of the storm will not cease until the next storm front

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#71154]
## Round ID: [193842](https://scrubby.melonmesa.com/round/193842)
there have been a few more rounds with this but I didn't write them down sorry

## Reproduction:
So lavaland rolls its first storm as per any other storm right? So there's a 10% chance that it will be an ember storm that is harmless. There's currently an issue with the ember storm that makes its storm sounds never cease when it triggers, leaving anyone present on lavaland deafened with the storm sounds until the next storm comes. IIRC if an ember storm happens on any other trigger, it will not have this issue.

**Comment by rasepretep** [comment]
I'm fairly certain this happens anytime an ember storm happens, not just if it's the first one. Have been noticing it several times in the past weeks well into the rounds.
