### ISSUE TITLE
you can throw vending machines with sorium (presumably) to hardstun to near and/or instakill people

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#71151]

**Comment by Shadowflame909** [comment]
that sounds like an expected outcome of a vending machine falling onto you

**Comment by Serxule** [comment]
> that sounds like an expected outcome of a vending machine falling onto you

normal vending machine crush doesnt do near as much damage, and afaik sorium objects are supposed to "dodge" people, from what i've heard anyways

**Comment by Magic101lvl** [comment]
I think it damaged you twice. For hitting in flying and another for falling on to you.

**Comment by Sealed101** [comment]
can't reproduce
