### ISSUE TITLE
humans don't particularly enjoy fried food

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#71164]
reproduction steps:
1. deep fry a piece of meat
2. feed it to a human
3. the human does not get the positive moodlet for eating something with a foodtype on their species's list of liked foods (FRIED)

**Comment by Sealed101** [comment]
did #71551 affect this? or did that also not work with crafted foods with the FRIED tag?

**Comment by Sealed101** [comment]
https://github.com/tgstation/tgstation/pull/78481#issuecomment-1729260042
