### ISSUE TITLE
deep frying a piece of food entirely replaces its food types

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#71165]
this is because deep frying something actually creates a new deepfriedholder object containing it, with some of the original object's properties being transferred. reagents are transferred from food (via the OnFried function), but food types are apparently not.

this is odd, because the fry() proc uses `foodtypes |= FRIED` instead of `foodtypes = FRIED`, implying that food types are meant to be copied.

**Comment by Sealed101** [comment]
https://github.com/tgstation/tgstation/pull/78481#issuecomment-1729260042
