### ISSUE TITLE
Going down a z-level through stairs as a soul scythe leads to Central command.

### ISSUE THREAD

**Issue by Xander3359** [tgstation/tgstation#71163]
Reporting client version: 514.1589

## Round ID:
[193913](https://scrubby.melonmesa.com/round/193913)

## Reproduction:
This was done on Tram:
As a soul scythe, head to cargo
Go to the stairs leading down to mining
When on the stairs, move down a z level
You are now at central command.
???

https://user-images.githubusercontent.com/66163761/200435152-e0dc35d7-8789-4c2a-9bf1-7bc9f2854838.mp4

**Comment by msgerbs** [comment]
Are you using the "move down" hotkey here?

**Comment by Shadowflame909** [comment]
Nanotransen hates him. Here's how he can save you time and money on the shuttle with one simple trick!
