### ISSUE TITLE
Integrated circuits UI can print components without a linked printer & with no material consumption

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#71173]
**Steps to reproduce**
1) In the very start of the round go to R & D IC lab. Don't deposit any glass sheets in the component printer [make sure it has 0 glass] & don't link the IC to the printer and grab an IC sitting on the rack

![Screenshot (45)](https://user-images.githubusercontent.com/110812394/200636866-f02152a2-4de0-4fad-989f-81a7a0a627b3.png)

2)Click on the IC & drag and drop components
![Screenshot (46)](https://user-images.githubusercontent.com/110812394/200637092-59b4d4c1-c22b-4d8b-879f-fbb143fdc82f.png)

3) You can do that without consuming any glass or without linking it to any printer so what's the purpose of the printer then?

**Source of the bug**
It appears to be in file code/modules/wiremod/core/integrated_circuit.dm inside proc ui_act on line 621
![Screenshot (47)](https://user-images.githubusercontent.com/110812394/200637608-3e381ea2-3789-437c-900f-20a1ead2ced0.png)

Changing the if(!check_rights_for(...))) to if(check_rights_for(...))) seemed to have fixed the problem but components which can't be printed such as variable setters & getters & other components which i am not aware can't be printed nor dragged & dropped now. 

If anyone knows a fix drop an comment

**Comment by Mothblocks** [comment]
@Watermelon914

**Comment by moocowswag** [comment]
So this is a bug that only takes place before the printer gets matts and starts updating its ability to print stuff?

**Comment by SyncIt21** [comment]
I don't need to link any printer and when dragging and dropping no glass is consumed from the printer . Insert a glass sheet in the printer,drag and drop the component and check the glass in the printer.  Nothing is consumed and I can drag & drop without even linking the circuit to the printer

**Comment by SyncIt21** [comment]
I made an interesting observation. If you are an admin then you can drag & drop all researched & unresearched components without linking it to a printer and without consuming any glass but if you are a normal player, then everything works as intended. Is this desired behaviour or are we just giving the admin too much power?

**Comment by Mothblocks** [comment]
Admin circuits are a thing, but I would hope our check isn't just if a player is admin since playminning is not a thing the codebase wants to prohibit or give more advantage to. Sounds like an oversight in a culture where that's not a big thing people do anymore.

**Comment by SyncIt21** [comment]
I'm closing this because admins do have a free pass for creating IC components without materials or printers and it seems intended. Regular players can't do any of this so that's good enough for me

**Comment by Mothblocks** [comment]
It is not intended at all

**Comment by SyncIt21** [comment]
Then the solution is admins need linked printers and materials but they can still add unresearched and special IC components? 
That's very easy to do just need to make sure that's the solution here.

**Comment by SyncIt21** [comment]
> > Giving admins an explicit toggle for free materials (enabled by default if on CentCom) sounds like a good path to fix this if that is the issue.

Ahh.

**Comment by SyncIt21** [comment]
> sounds like a good path
I guess it's not the absolute solution but just one of many good ones. This issue lives another day

**Comment by Watermelon914** [comment]
this'll be an easy fix, it's just about making a check for if it's an admin circuit or not

**Comment by Watermelon914** [comment]
Though actually, this was sort of intentional as I didn't expect admins would be playing normally throughout a round whilst not deadminned, but that's my fault for not making it clear in the original PR
