### ISSUE TITLE
Solar panels have a overlay/layering issue on tramstation.

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#71179]
Reporting client version: 514.1589

## Round ID:
[193985](https://scrubby.melonmesa.com/round/193985)

## Testmerges:
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)
- [Adds logic to provide leniency for drag clicks](https://www.github.com/tgstation/tgstation/pull/71082)

## Reproduction:
 look at solar panels. 

![image](https://user-images.githubusercontent.com/54517726/200727866-59c2d6b1-eff8-4f97-a24d-3ba6fc2eb86f.png)

**Comment by Baskett55** [comment]
i saw this also affects non multi z-level maps like delta 
![image](https://user-images.githubusercontent.com/54517726/200763607-1e014986-4801-4df8-97c1-ed27621d3c91.png)

**Comment by LemonInTheDark** [comment]
My fault, #70162
They were on the same layer, and while that typically would be resolved by draw order, because of the pixel offsets it was messed up.
I've used layers directly to solve this
