### ISSUE TITLE
portable air scrubbers dont scrub

### ISSUE THREAD

**Issue by restedwaves** [tgstation/tgstation#71187]
## Round ID:

194009

## Reproduction:
bring air scrubber into hall full of gas, put in empty holding tank, turn on scrubber, choke on n2o

**Comment by mc-oofert** [comment]
scrubbers will only scrub gas from the tank if you insert one, remove it to make it actually scrub gas

probably not a bug

**Comment by ArcaneDefence** [comment]
The scrubber has its own internal tank that it puts gases filtered from the atmosphere into.
Attaching a tank to it means that you're trying to filter gases *out* of that removable tank to the scrubber's internal tank, so it would not have an effect on the open air in the hallway.
This is functioning as intended and how it's been for a long time.
Thanks for reporting this anyway

**Comment by restedwaves** [comment]
while good to know it wasn't filtering without a tank either witch is why i thought it needed one
