### ISSUE TITLE
you can't use your pda with insulated gloves on

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#71180]
## Reproduction:
put on insulated gloves
try to use pda
fingers too fat

I know it's technically a modular computer but previous behaviour allowed you to use your pda with insulated gloves on.

**Comment by private-tristan** [comment]
actually this is a recent change, before (at least 2 days ago?) you could use PDAs even with clunky fingers.

**Comment by newfren** [comment]
yeah, I wasn't clear, this was changed after modular computer pdas were introduced

**Comment by Mothblocks** [comment]
CC @optimumtact on whether you think this should be left in--the complaint is about how PDAs have been changed to tablets, which intentionally did not allow you to use them with chunky fingers, and that PDAs not being usable was not part of the original intent.

I'm surprised this was different 2 days ago though?

**Comment by newfren** [comment]
you were definitely able to use modular tablet pdas with insulated gloves when they were first introduced and for most of the time they have been around

**Comment by itseasytosee** [comment]
Might be my limb refractor. Don't know how though

**Comment by Mothblocks** [comment]
I think timothy might have changed it recently, actually, I remember we had another chunky finger related bugs

**Comment by Mothblocks** [comment]
Unless that was you and I'm dumb

**Comment by msgerbs** [comment]
Until recently you could use PDA tablets with chunky fingers but not stationary computers, which doesn't make much sense. This way is more consistent, but honestly I think this whole mechanic is just pointless and annoying (specifically to engineers who are pretty much the only people who actually need/want to use stationary computers and PDAs while also having insulated gloves.

**Comment by newfren** [comment]
it was intentionally different to stationary computers (and laptops, I believe) because all functionality of pdas were preserved when moving over to tablet pdas, including being able to use them with insulated gloves.

**Comment by JohnFulpWillard** [comment]
I think we should either have insuls affect all modular computers or none of them, no reason it should work on PDA with its small keyboard but not computers with a large one.
