### ISSUE TITLE
Cant claim tram mining areas as rooms

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#71197]
Reporting client version: 514.1582

## Testmerges:
- [Caves Away Mission (for real this time) [DNM]](https://www.github.com/tgstation/tgstation/pull/71188)
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)
- [Adds logic to provide leniency for drag clicks](https://www.github.com/tgstation/tgstation/pull/71082)

## Reproduction:
1. Spend 20 minutes digging out and building the the general structure of your maint base on tram station
2. Try to claim the area and see that the area is already claimed
3. Try to place an apc and it says you cant place one in this area
4. Build a door and see its unpowered
5. Place a Scrubber and it says the area youre in is defined as "Lavaland"???

This isnt normal behavior, you used to be able to just claim whatever room you wanted and ive had countless rounds where I was able to claim my own room without blueprints or anything.

**Comment by Jackal-boop** [comment]
Might be related
You don't seem to be able to use consoles in tram maintenence. For whatever reason

**Comment by Jackal-boop** [comment]
Might be related
You don't seem to be able to use consoles in tram maintenence. For whatever reason

**Comment by san7890** [comment]
This is more of an issue that we use `/area/lavaland/surface` on TramStation's "asteroid" portions, which should probably be fixed sometime to actually be some sort of "asteroid" area, because I think that's silly.

**Comment by msgerbs** [comment]
Almost certainly caused by this: #70182
