### ISSUE TITLE
Modsuits don't cover clothing under them when deployed but not activated

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#71198]
Reporting client version: 514.1589

## Round ID:
[194046](https://scrubby.melonmesa.com/round/194046)

## Testmerges:
- [Caves Away Mission (for real this time) [DNM]](https://www.github.com/tgstation/tgstation/pull/71188)
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)
- [Adds logic to provide leniency for drag clicks](https://www.github.com/tgstation/tgstation/pull/71082)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/201000394-2a2d87c9-cbc4-4550-9c86-7a156029c248.png)

Seen here with engineering skirt

**Comment by Kapu1178** [comment]
![image](https://user-images.githubusercontent.com/75460809/201045523-c944ea2b-061c-4287-a804-a9b3cef4e8b3.png)
