### ISSUE TITLE
The changeling's transform ability removes restraints on the ling.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#71225]
## Round ID:
[194185](https://scrubby.melonmesa.com/round/194185)

## Testmerges:
[#71188: 'Caves Away Mission (for real this time) [DNM]' by MMMiracles at commit 4e14350a18](https://www.github.com/tgstation/tgstation/pull/71188)
[#71058: 'Imaginary friend refactor' by RigglePrime at commit da388ccc30](https://www.github.com/tgstation/tgstation/pull/71058)

## Reproduction:
If you are cuffed, for example, you can use the ability, named "Transform", to get free out of the cuffs. That probably isn't supposed to happen, otherwise another ability, known as "Biodegrade", is kind of pointless.

**Comment by moocowswag** [comment]
Biodegrade isnt flashy and can be done almost stralithly so you can pull out something to attack your cuffer before they realize it.

**Comment by TheBoondock** [comment]
> /datum/species/proc/worn_items_fit_body_check(mob/living/carbon/wearer)
	for(var/obj/item/equipped_item in wearer.get_all_worn_items())
		var/equipped_item_slot = wearer.get_slot_by_item(equipped_item)
		if(!equipped_item.mob_can_equip(wearer, equipped_item_slot, bypass_equip_delay_self = TRUE, ignore_equipped = TRUE))
			wearer.dropItemToGround(equipped_item)
So transform ability will call set_specie which ultimately call this and drop the item
