### ISSUE TITLE
Sprayer Icons are completely fucked

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#71241]
Reporting client version: 514.1585

## Round ID:
[194228](https://scrubby.melonmesa.com/round/194228)

## Testmerges:
- [Caves Away Mission (for real this time) [DNM]](https://www.github.com/tgstation/tgstation/pull/71188)
- [Adds 5 new Heretic spells. Rebalances some aspects of Heretics. Refactors some spells as well, and makes it so emote spells require free hands.](https://www.github.com/tgstation/tgstation/pull/71044)
- [New Station Trait: Cybernetic Revolution](https://www.github.com/tgstation/tgstation/pull/71229)

## Reproduction:
![image](https://user-images.githubusercontent.com/36141254/201502354-e6238119-abb6-4475-902c-b6ddd7df2be1.png)

**Comment by Time-Green** [comment]
Can someone else reproduce this? I dont know a lot of tgui but it has a tendency to break randomly for specific people

**Comment by ZAMODA** [comment]
twas a tgui issue, shoulda closed this way earlier
