### ISSUE TITLE
Disposal loops completely delete people that fall into them?

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#71252]
RoundID 194307

a ling made a disposal loop trap, but when they welded a pipe to let two people that fell in out, they were both deleted, no body, just ghosts.

**Comment by Time-Green** [comment]
Probably caused by #70908 

@zxaber

**Comment by zxaber** [comment]
And here I thought I had tested things like this.

I'm on it.

**Comment by zxaber** [comment]
So, looking through the logs, it seems the pipe had actually been destroyed by a chem grenade. I cannot replicate the issue using proper deconstruction (through welding), but destroying a pipe through damage is incorrectly deleting the contents.
