### ISSUE TITLE
Cyborg multitool can't check power in cables

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#71266]
Reporting client version: 514.1585

## Round ID:
[194351](https://scrubby.melonmesa.com/round/194351)

## Testmerges:
- [Adds 5 new Heretic spells. Rebalances some aspects of Heretics. Refactors some spells as well, and makes it so emote spells require free hands.](https://www.github.com/tgstation/tgstation/pull/71044)

## Reproduction:
Take out your trust cyborg multitool as a little engi borg.
Try to see amount of power in a powernet, nothing happens on click.

**Comment by moocowswag** [comment]
else if(W.tool_behaviour == TOOL_MULTITOOL)
		to_chat(user, get_power_info())
		shock(user, 5, 0.2)

So its checking for tool behavior tool_multitool...
