### ISSUE TITLE
Ruins spawning on z-level 11 when it shouldn't.

### ISSUE THREAD

**Issue by Xander3359** [tgstation/tgstation#71268]
Reporting client version: 514.1589
This tram round had 2 ruins spawn on z-level 11, aesthetic and lizard gas. 

## Round ID:
[194351](https://scrubby.melonmesa.com/round/194351)

## Testmerges:
- [Adds 5 new Heretic spells. Rebalances some aspects of Heretics. Refactors some spells as well, and makes it so emote spells require free hands.](https://www.github.com/tgstation/tgstation/pull/71044)

## Reproduction:
I dont know how to reproduce it, maybe join tram and see if z-levels spawn on layer 11 again.

![z level 11](https://user-images.githubusercontent.com/66163761/201794309-3e899e99-f860-4c4a-87cb-64f09474e783.png)

**Comment by san7890** [comment]
Ruins spawning on z-level 11 is expected actually, I wrote about this back in #66540.

```txt
As of April 26th, 2022, the typical Z-levels for a single-level station are:
1: CentCom
2: Station
3-4: Randomized Space (Ruins)
5: Mining
6-11: Randomized Space (Ruins)
12: Transit/Reserved Space
```
Since Tram is a multi-Z station, it will just "occupy" Z-Level 3 (and force it to not be randomized space). Z-Levels 6-11 should (theoretically) be unaffected by Tram's multi-z characteristic.

**Comment by san7890** [comment]
![image](https://user-images.githubusercontent.com/34697715/201798221-3a0d7388-fc61-4a1b-8ee8-534641fd485a.png)

Yeah, it's still valid after running the `debug-z-levels` verb on a local just now.
