### ISSUE TITLE
AI portrait display broken.

### ISSUE THREAD

**Issue by Shellton123** [tgstation/tgstation#71270]
## Testmerges:
[#71229: 'New Station Trait: Cybernetic Revolution + Body Purist Quirk' by Fikou at commit 236a046822](https://www.github.com/tgstation/tgstation/pull/71229)
[#71044: 'Adds 5 new Heretic spells. Rebalances some aspects of Heretics. Refactors some spells as well, and makes it so emote spells require free hands.' by MrMelbert at commit 0c28b4d6fa](https://www.github.com/tgstation/tgstation/pull/71044)
[#70162: 'Changes our map_format to SIDE_MAP' by LemonInTheDark at commit b2f1f2a684](https://www.github.com/tgstation/tgstation/pull/70162)
[#71082: 'Adds logic to provide leniency for drag clicks' by LemonInTheDark at commit 24f257c05f](https://www.github.com/tgstation/tgstation/pull/71082)

## Reproduction: When picking any portrait to display on your ai core it just shows a blank screen. To reproduce just try picking a portrait. 

![ai bug](https://user-images.githubusercontent.com/83558207/201799051-ac70960e-80b8-4222-b7db-3a8e929b8ba3.PNG)

**Comment by msgerbs** [comment]
Potentially related to #71179? Did you happen to stumble upon any solar arrays during this round?

**Comment by LemonInTheDark** [comment]
SIDE_MAP related, it uses pixel y and the portrait was offset more then the frame, so it was rendering behind. Solved
