### ISSUE TITLE
Hilbert's Hotel Ruin Tram is spaced.

### ISSUE THREAD

**Issue by Xander3359** [tgstation/tgstation#71298]
Reporting client version: 514.1589

## Round ID:
[194432](https://scrubby.melonmesa.com/round/194432)

## Testmerges:
- [Adds 5 new Heretic spells. Rebalances some aspects of Heretics. Refactors some spells as well, and makes it so emote spells require free hands.](https://www.github.com/tgstation/tgstation/pull/71044)

## Reproduction:
Get to hilberts hotel
Tram has 4 tiles of space
![hil tram](https://user-images.githubusercontent.com/66163761/202113025-c42c92cf-5966-4f95-bf38-a63a09a4ef60.png)

https://youtu.be/Btb8j_MKgMY

**Comment by private-tristan** [comment]
#71186

**Comment by Fikou** [comment]
i blame willard

**Comment by Fikou** [comment]
and strongdmm2
