### ISSUE TITLE
spear embeds bypass furious steel and blocking with weapons.

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#71309]
## Round ID:
[194465](http://127.0.0.1:56559/tmp18168/af587ea4.htm?action=openLink&link=https%3A%2F%2Fsb.atlantaned.space%2Frounds%2F194465)

## Reproduction:

cast funny blade spell
get spear thrown at you 
die because it embeds
![image](https://user-images.githubusercontent.com/54422837/202303504-b7f26c3c-9510-49a9-9397-4a5103511f7a.png)

**Comment by private-tristan** [comment]
just realized it's sorta a dupe of #62386 but it also appears to effect furious steel.

**Comment by moocowswag** [comment]
It if penetrates special block effects like furious steel then I`m wondering if it also penetrates nukie`s shielded modsuit, wizard`s shielded robes, and reactive armor.
