### ISSUE TITLE
Ambience background "hum" doesn't start unless you enter a different area (like maintenance)

### ISSUE THREAD

**Issue by Jolly-66** [tgstation/tgstation#71304]
## Round ID:
Local test.

## Reproduction:
Background "hum", "whir", whatever we wanna call it, does not start unless you enter a different area that has a different background "hum". This applies when you spawn in, late join spawn, admin spawn, whatever. Regular noises that occasionally play still do, but the rest is dead silence. 

<details>
<summary> Video </summary>

https://youtu.be/KEsOlR-7z40

</details>

**Comment by distributivgesetz** [comment]
Fixed in #81149

**Comment by Jolly-66** [comment]
FINALLY YEEEEEEAAAAAAAAAHH!!
