### ISSUE TITLE
bolt of possession bricks the original player

### ISSUE THREAD

**Issue by 1393F** [tgstation/tgstation#71311]
Reporting client version: 514.1589

## Round ID:
[194470](https://scrubby.melonmesa.com/round/194470)

## Reproduction:
once I was taken over by a ghost my screen was blackened, I had 2 action buttons appear but they disappeared after I clicked them,
it was basically impossible to ghost, I had to spam the button then quickly click yes on the popup or it disappeared
![Screenshot (930)](https://user-images.githubusercontent.com/59183821/202315138-b1f7fd94-9ab0-4b5d-b7f7-da941064ef1b.png)

**Comment by 1393F** [comment]
I don't actually know what bolt did it, feel free to tell me so I can change the title

**Comment by Jolly-66** [comment]
You can probably find the information in the parsed round logs. Maybe check the combat logs?

**Comment by 1393F** [comment]
I don't care enough

**Comment by timothymtorres** [comment]
I think bolt of possession creates split personality which is an extremally bugged out feature currently.  I'd recommend you checking through the issue tracker for "split personality" and seeing if your outcome is similar to others.

**Comment by 1393F** [comment]
oh, I accidentally made a dupe issue
