### ISSUE TITLE
Performace of Slot Machine is Horrible

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#71314]
## Reproduction:
Spin a slot machine and watch as you go to 5fps

**Comment by Serxule** [comment]
maybe there's a tgui problem thats popped up, made this just a few hours ago https://github.com/tgstation/tgstation/issues/71312

**Comment by Profakos** [comment]
Slotmachine is not even tgui, its uses datum/browser.

**Comment by Mooshimi** [comment]
This and the ore smelter needs a UI update to current standards, that's all
