### ISSUE TITLE
Brimdemon AI is incredibly easy to break

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#71330]
![2022-11-17 17_51_40-_tg_Station Sybil  ENGLISH   US-WEST   100% FREE LAG   DDOS _ Malla Complex Eta](https://user-images.githubusercontent.com/70376633/202673531-95dad5b4-72f5-40b6-b964-a2f2195b48c6.png)

## Reproduction:

1. Be miner, find brimdemon
2. Stand 1 tile away from the brimdemon, but not in any of its adjacent directions
3. Brimdemon brain fries and does not move or fire or attack

**Comment by Sealed101** [comment]
have seen it happen multiple times, still an issue
