### ISSUE TITLE
Aheals don't heal oxygen damage

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#71353]
Reporting client version: 514.1589

## Round ID:
[194625](https://scrubby.melonmesa.com/round/194625)

## Reproduction:
THEY DON'T

**Comment by timothymtorres** [comment]
Duplicate of #71331

**Comment by Striders13** [comment]
> Duplicate of #71331

Is oxygen damage tied to organs?

**Comment by timothymtorres** [comment]
> **Aheals no longer heal**/repair organs

Aheal is tied to healing everything.  Organs, damage, wounds, limbs, genetic mutations, disease, and status effects.
