### ISSUE TITLE
TGUI-Dev Cache Reloading Doesn't Work

### ISSUE THREAD

**Issue by RimiNosha** [tgstation/tgstation#71365]
## Round ID:
N/A

## Testmerges:
None (local env), latest commit as of writing (780b41ca)

## Reproduction:
Start up `tgui-dev` from `bin`, and watch as it spits a 404 error as it tries to ping BYOND to reload TGUI cache. (`http://127.0.0.1:55674//dummy?tgui=1&type=cacheReloaded`)

Seems to be broken by #71161.

<details>
<summary>Logs!</summary>

    Using vendored Node v14.16.1
    :: Juke Build version 0.8.1
    :: Skipping 'yarn' (up to date)
    => Starting 'tgui-dev'
       0.628 webpack setting up
       0.630 link setting up
       0.632 link listening on port 3000 (WebSocket)
       0.633 link listening on port 3001 (HTTP)
    Browserslist: caniuse-lite is outdated. Please run:
      npx browserslist@latest --update-db
      Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
       1.057 webpack watching for changes
       1.076 webpack clearing garbage (9 files)
       1.078 webpack compiling
       5.183 webpack Entrypoint tgui 5.44 MiB (4.12 MiB) = tgui.bundle.css 348 KiB tgui.bundle.js 5.1 MiB 2 auxiliary assets
       5.183 webpack Entrypoint tgui-panel 1.74 MiB (1.25 MiB) = tgui-panel.bundle.css 123 KiB tgui-panel.bundle.js 1.62 MiB 2 auxiliary assets
       5.184 webpack Entrypoint tgui-say 1.36 MiB (982 KiB) = tgui-say.bundle.css 20.8 KiB tgui-say.bundle.js 1.34 MiB 2 auxiliary assets
       5.184 webpack webpack compiled successfully
       5.937 retrace loaded 6 source maps
       5.937 reloader looking for byond cache
       5.944 reloader found cache at 'C:/Users/username/Documents/BYOND/cache'
       5.993 reloader copied 12 files to 'C:/Users/username/Documents/BYOND/cache/tmp20036'
       6.002 dreamseeker found 1 instance
       6.003 reloader notifying dreamseeker
       6.004 dreamseeker topic call at http://127.0.0.1:55674//dummy?tgui=1&type=cacheReloaded
    (node:5228) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
        at createError (C:\Users\username\Desktop\tgstation.git\tgui\.yarn\cache\axios-npm-0.21.1-d192f6b3b3-c87915fa0b.zip\node_modules\axios\lib\core\createError.js:16:15)
        at settle (C:\Users\username\Desktop\tgstation.git\tgui\.yarn\cache\axios-npm-0.21.1-d192f6b3b3-c87915fa0b.zip\node_modules\axios\lib\core\settle.js:17:12)
        at IncomingMessage.handleStreamEnd (C:\Users\username\Desktop\tgstation.git\tgui\.yarn\cache\axios-npm-0.21.1-d192f6b3b3-c87915fa0b.zip\node_modules\axios\lib\adapters\http.js:260:11)
        at IncomingMessage.emit (events.js:327:22)
        at endReadableNT (internal/streams/readable.js:1327:12)
        at processTicksAndRejections (internal/process/task_queues.js:80:21)
    (Use `node --trace-warnings ...` to show where the warning was created)
    (node:5228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 350)
    (node:5228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</details>

**Comment by AnturK** [comment]
Was fixed in #71374
