### ISSUE TITLE
Curd cheese microwaves into burned mess

### ISSUE THREAD

**Issue by antropod** [tgstation/tgstation#71391]
No Round Id, found on Skyrat, then reproduced on local server built from master.

Curd cheese turns into burned mess when microwaved. It supposed to produce cheese curds when microwaved.

## Reproduction
Make curd cheese by mixing 15 milk, 5 cream, 5 vinegar and headting it. Put results in a microwave.

caused by changes in #70409, setting it as microwavable was moved into proc that was misnamed
`/obj/item/food/curd_cheese/make_microwavable()`
and it should be named
`/obj/item/food/cheese/curd_cheese/make_microwavable()`

**Comment by antropod** [comment]
good first issue xD

**Comment by Fikou** [comment]
> good first issue xD. 2 years too late

its not about you its good issues for first timers to fix

**Comment by antropod** [comment]
confusing
