### ISSUE TITLE
Paramedic starts with only one bone gel in their medical belt, even when they have five surgical tapes.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#71393]
I am not really sure, if this is even a bug, but it's at least an inconsistency.

**Comment by NeverDawnedNoz** [comment]
It's an inconsistency.
When you dispense bone gel from a nanomed, it will come in a stack of 5 instead of 1.
You will find most roundstart bone gel/surgical tape stacks only come in a stack of 1.

**Comment by Mooshimi** [comment]
> It's an inconsistency.

Ok
