### ISSUE TITLE
Firebots attempt to extinguish people that are not on fire

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#71390]
Reporting client version: 514.1589

## Round ID:
[194701](https://scrubby.melonmesa.com/round/194701)

## Testmerges:
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)
- [Adds logic to provide leniency for drag clicks](https://www.github.com/tgstation/tgstation/pull/71082)

## Reproduction:

1. build firebot
2. firebot attempts to extinguish people not on fire

**Comment by ShizCalev** [comment]
they're just smokin hot.
