### ISSUE TITLE
Inverse Penthrite (Nooartrium) is exploding when mixed with atropine.

### ISSUE THREAD

**Issue by Xander3359** [tgstation/tgstation#71406]
Reporting client version: 514.1589

## Round ID:
[194755](https://scrubby.melonmesa.com/round/194755)

## Testmerges:
- [Rewrites how action buttons icons are generated, makes them layer nicer. Allows observers to see a mob's action buttons. ](https://www.github.com/tgstation/tgstation/pull/71339)

## Reproduction:
Make Nooartrium (inverse penthrite)
Mix it with Atropine
-> Explodes
I believe this is unintended, seeing how nooartrium won't explode when mixed with atropine in a body.

**Comment by antropod** [comment]
did you purify it?

**Comment by Xander3359** [comment]
It needs to be 100% pure for it to not explode? And yet, it doesnt react with atropine in a body.

**Comment by antropod** [comment]
no, you need to run it trough machine to turn it into actual nooartrium, otherwise it will stay as penthrite and turn into nooartrium only when it enters the body

**Comment by RikuTheKiller** [comment]
> no, you need to run it trough machine to turn it into actual nooartrium, otherwise it will stay as penthrite and turn into nooartrium only when it enters the body

Correct

**Comment by Xander3359** [comment]
Gotcha, I just wish this were more clear somewhere.
