### ISSUE TITLE
Mesons allow you to see through open_space through walls

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#71407]
Reporting client version: 514.1589

## Round ID:
[194762](https://scrubby.melonmesa.com/round/194762)

## Testmerges:
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)
- [Adds logic to provide leniency for drag clicks](https://www.github.com/tgstation/tgstation/pull/71082)

## Reproduction:

1. get mesons
2. look at xenobiology through maint
3. see stuff
![2022-11-21 11_04_03-Window](https://user-images.githubusercontent.com/70376633/203022541-050aa9bb-35b3-495a-9fca-e6fa92ec8cda.png)

**Comment by private-tristan** [comment]
#53783

**Comment by ArcaneDefence** [comment]
Duplicate as previously mentioned
