### ISSUE TITLE
Space Dragons can spam the right click stun

### ISSUE THREAD

**Issue by Cheshify** [tgstation/tgstation#71400]
## Round ID:
 [194728](https://scrubby.melonmesa.com/round/194728)

## Testmerges:
[#71339: 'Rewrites how action buttons icons are generated, makes them layer nicer. Allows observers to see a mob's action buttons. ' by MrMelbert at commit 7d3187ebcb](https://www.github.com/tgstation/tgstation/pull/71339)

## Reproduction:
Well I spawned a space dragon in central, and right clicked, and then I right clicked again once the stun went off and there was no delay

**Comment by Serxule** [comment]
i think its intentional since you're unable to move while doing it

**Comment by private-tristan** [comment]
the endlag increases the more you spam. this is intentional.
https://github.com/tgstation/tgstation/blob/9580928050a93994944dab3be902ed208b54bf9b/code/modules/mob/living/simple_animal/hostile/space_dragon.dm#L64-L65

**Comment by Time-Green** [comment]
You can change it but it’ll be a balance change
