### ISSUE TITLE
Department Lathes Not Auto-Syncing with Science Research

### ISSUE THREAD

**Issue by RandomlyEvil** [tgstation/tgstation#71418]
Reporting client version: 514.1589

## Round ID:
[194791](https://scrubby.melonmesa.com/round/194791)

## Reproduction:

Had a ticket come in that there were issues between round listed above and the prior round on Terry where medical lathe was not receiving updated designs when research was done.  I had the player decon lathe and reassemble it, which seemed to have corrected the issue (newly built lathes seemed okay when tested) however round end showed multiple players reporting the same issue as well.  
Uncertain if rebuilt lathes autosync after decon/reconstruction but likely needs to be checked out why they don't sync originally.

**Comment by Mothblocks** [comment]
@JohnFulpWillard

**Comment by JohnFulpWillard** [comment]
I wish tools were logged on scrubby
