### ISSUE TITLE
Tgui issues

### ISSUE THREAD

**Issue by 145play145** [tgstation/tgstation#71412]
Tgui simply opens blue screen and asks me to send thing below (tryed both beta and last stabile versions of byond)
(Server is Terry)

Script error
   at https://tgstation13.download/byond/assets/58/asset.58c2052c1979897eb29c35d2980d4fc4.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; Zoom 3.6.0)

**Comment by Ryusenshu** [comment]
same issue
even reopened my old issue report from the start of the month which had the same effect
https://github.com/tgstation/tgstation/issues/71055

**Comment by 145play145** [comment]
> Clear your cache

i did - same result

**Comment by DrCrawler** [comment]
Seems to be server-specific. There's issue #71425 describing the same error.

**Comment by Striders13** [comment]
I'm getting bluescreens on all servers. Tried playing with a vpn, issue persists. Using admin verb Toggle-CDN fixes it for me.

**Comment by jlsnow301** [comment]
#53997
