### ISSUE TITLE
TGUI crashing repeatedly

### ISSUE THREAD

**Issue by etherware-novice** [tgstation/tgstation#71425]
Reporting client version: 514.1589

## Round ID:
[194808](https://scrubby.melonmesa.com/round/194808)

## Testmerges:
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [194808](https://scrubby.melonmesa.com/round/194808)
BYOND Version: 514.1588
Server revision compiled on: 
Master commit: [2829271d046456647f5a6ef71eccfe0df5c4deaf](https://www.github.com/tgstation/tgstation/commit/2829271d046456647f5a6ef71eccfe0df5c4deaf)
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1

## Reproduction:
Opening any tgui menu. Tried logging out/in, tried refresh-TGUI, tried updating from 514.1584 to 514.1589. it still crashes and bluescreens and makes playing very difficult

![image](https://user-images.githubusercontent.com/73374039/203201370-6321b50b-145e-43b2-a1ca-b4d29ecf7e27.png)

**Comment by DrCrawler** [comment]
Seems to be either server or round-specific. Same happened to me on Terry, decided to join Sybil and check there, couldn't replicate, joined Terry again and it was back.

**Comment by jlsnow301** [comment]
#53997
