### ISSUE TITLE
C4 Sprite shows up UNDER syndicate bomb sprite.

### ISSUE THREAD

**Issue by MrrFiish** [tgstation/tgstation#71438]
Reporting client version: 514.1589

## Round ID:
194831

## Testmerges:
- [Rewrites how action buttons icons are generated, makes them layer nicer. Allows observers to see a mob's action buttons. ](https://www.github.com/tgstation/tgstation/pull/71339)

## Reproduction:
1) Put down syndicate bomb
2) C4 it
3) Look at it

**Comment by timothymtorres** [comment]
Closing this due to #72986 neutering c4 with bombs
