### ISSUE TITLE
Failsafe code can generate the same code as your actual uplink code

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#71446]
Doesnt explode as far as i am aware though

## Reproduction:

1. buy failsafe
2. 
![2022-11-22 17_43_56-](https://user-images.githubusercontent.com/70376633/203374825-c0f7cf92-baaf-4903-a026-239b57e8227e.png)

**Comment by msgerbs** [comment]
Why is there no number on either of them?

**Comment by mc-oofert** [comment]
> Why is there no number on either of them?

it headset code

**Comment by Kapu1178** [comment]
Feature.
