### ISSUE TITLE
Plates don't show food placed on top of them, rather underneath it.

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#71455]
Reporting client version: 514.1589

## Round ID:
[194859](https://scrubby.melonmesa.com/round/194859)

## Testmerges:
- [Adds logic to provide leniency for drag clicks](https://www.github.com/tgstation/tgstation/pull/71082)
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)
- [Atmospheric machineries now interact with each other directly, rather than going through a radio layer -- saves about 0.4s of init time](https://www.github.com/tgstation/tgstation/pull/71232)

## Reproduction:
Placing food on plates seems to rather put it underneath the plate which makes it difficult to grab off the plate without it being in hand.

- Food on a plate while inhand
![Screenshot 2022-11-22 144946](https://user-images.githubusercontent.com/85206687/203433771-20cce8ae-f996-49e4-b1da-8a56565545e6.png)
- Food on a plate, on a table
![Screenshot 2022-11-22 145014](https://user-images.githubusercontent.com/85206687/203433856-13093643-b6dc-43ef-af17-49694a896cfa.png)
This also seems to be happening with oven trays as well.

**Comment by LemonInTheDark** [comment]
SIDE_MAP problem, pixel y pushing stuff over the "in front" wall. Fixed by using pixel_z instead
