### ISSUE TITLE
Slime people break heratic's heart, and the ritual to make a new one doesn't work despite the wiki saying it should for other races. Thankfully turning yourself back to human lets you do the ritual to get your heart again.

### ISSUE THREAD

**Issue by Troxonater** [tgstation/tgstation#71451]
## Reproduction: Become a slime person as heretic, lose your heart, then cope and seethe as you realize you just lost your method for tracking targets. Attempt to make a new heart in your slime body. Watch in frustration as the ritual says you have no heart. Read the wiki and source yourself an organic heart hoping it works. Get the same message again from the ritual saying you have no heart. Go back the exobiology lab and turn yourself back to human, then do the ritual for getting your heretic heart back and continue on after wasting 10-20 minutes. 

I'm unsure if this is meant to happen as a quirk of the game systems, but the wiki implies that other species can get a living heart no matter what. At the very least, there should be a documented way to get a living heart the old way, where it was an object you held in your hand for edge case scenarios like this.

**Comment by Vect0r2** [comment]
can confirm had this happen to me

**Comment by Serxule** [comment]
i assume this is an oversight where slimes werent ever given the ability to get a heart

**Comment by RikuTheKiller** [comment]
> i assume this is an oversight where slimes werent ever given the ability to get a heart

All races can have a heart, it's a matter of whether or not the game recognizes an ordinarily heartless race having one to be valid.

I can, for example, use a heart as a plasmaman to become a romerol zombie. (Which I ordinarily couldn't do.)

**Comment by IndieanaJones** [comment]
Monkeying a heretic also removes their special heart.
