### ISSUE TITLE
Traitor Objectives Fail to Complete

### ISSUE THREAD

**Issue by RandomlyEvil** [tgstation/tgstation#71458]
Reporting client version: 514.1589

## Round ID:
[194868](https://scrubby.melonmesa.com/round/194868)

## Reproduction:

Seeing multiple rounds where Traitor objectives are failing to complete/succeed. This appears to be happening namely on the "bug the office" objectives, but was reported for destroying a department techfab as well.  Other objectives such as killing pets and bugging cargo budget appear to work, so uncertain which objectives do not succeed and which succeed but bugging HoP and Cap's offices have both required admins to succeed the objectives through multiple rounds.

**Comment by Oranggu** [comment]
Same thing happened to me, i vouch
