### ISSUE TITLE
Holding a direction as you land somewhere while drifting results you getting stuck and not drifting as expected

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#71454]
## Reproduction:

- Be drifting through a room in zero gravity. 
- Hold a direction key that you wish to go, such as the opposite direction that you are drifting. 
- Bump a wall or table, or anything that would allow you to move off of it while floating in zero gravity. 
- You will move one tile away from the object, but you will not continue to drift, leaving you stuck floating until you act with a throwable or similar. 

https://user-images.githubusercontent.com/51863163/203431724-537b0437-07ad-46f3-b163-6771f9254364.mp4

**Comment by Inari-Whitebear** [comment]
Oh god yes, I hate when that happens.
