### ISSUE TITLE
Moth wings disappear upon being hit

### ISSUE THREAD

**Issue by ValuedEmployee** [tgstation/tgstation#71463]
After chem blew up in round 194869, I got blown back by the blast without taking fire damage. My wings instantly disappeared upon hitting the wall behind me. I've seen multiple moths that round have a similar problem.

**Comment by Time-Green** [comment]
I can't manage to reproduce this. My first guess is you did something with genetics to fuck your wings and it only got caught when you took a joint dislocation and your limbs updated, but Fermi (the other moth?) seemed to also lose their wings according to convo without suffering a joint dislocation (only after)

I can't reproduce this on local, is there anything weird you two were both exposed to?

**Comment by Time-Green** [comment]
i give up
