### ISSUE TITLE
You cannot photocopy your ass

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#71466]
## Testmerges:
no testmerges

## Reproduction:

https://user-images.githubusercontent.com/4081722/203470394-f26f02be-1f81-4cd8-a4f4-5b1bd3ab8657.mp4

**Comment by Sealed101** [comment]
did you hold an id or a credit stack while trying to use the copier? it costs 5 cr to copy something

**Comment by Iamgoofball** [comment]
if it does, it's not displaying an error message about that
