### ISSUE TITLE
Non-vending machines can be affected by the vendor uprising

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#71465]
Reporting client version: 514.1589

## Round ID:
[194881](https://scrubby.melonmesa.com/round/194881)

## Testmerges:
- [Adds logic to provide leniency for drag clicks](https://www.github.com/tgstation/tgstation/pull/71082)
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)
- [Atmospheric machineries now interact with each other directly, rather than going through a radio layer -- saves about 0.4s of init time](https://www.github.com/tgstation/tgstation/pull/71232)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/203468248-219f79ed-48a3-45d2-a492-4af8f344b83f.png)

**Comment by dragomagol** [comment]
Yes I know it's technically a vending machine, but it should also be stuck to the wall

**Comment by Mooshimi** [comment]
I mean, this is a good issue because the hotbox is actually one tile off from where it appears as well, since that's how wall things work currently
