### ISSUE TITLE
Botany Biogenerators can make biomass above their capacity

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#71472]
Reporting client version: 514.1589

## Round ID:
[194912](https://scrubby.melonmesa.com/round/194912)

## Testmerges:
- [Atmospheric machineries now interact with each other directly, rather than going through a radio layer -- saves about 0.4s of init time](https://www.github.com/tgstation/tgstation/pull/71232)
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)
- [Adds logic to provide leniency for drag clicks](https://www.github.com/tgstation/tgstation/pull/71082)

## Reproduction:

1. have biogen with 500 capacity currently at 400
2. cram it with potency 100 watermelons
3. activate
4. watch as it goes above 500
![2022-11-23 15_49_54-](https://user-images.githubusercontent.com/70376633/203580414-4bb42690-912c-48e1-afb6-3e1e308b7afc.png)

**Comment by MTandi** [comment]
This is intentional according to @GoldenAlpharex and @MrMelbert via https://github.com/tgstation/tgstation/pull/71563

**Comment by mc-oofert** [comment]
> This is intentional according to @GoldenAlpharex and @MrMelbert via https://github.com/tgstation/tgstation/pull/71563

im sure this was an issue pre-PR but ok

**Comment by MTandi** [comment]
> > This is intentional according to @GoldenAlpharex and @MrMelbert via #71563
> 
> im sure this was an issue pre-PR but ok

Oh, then it was fixed after https://github.com/tgstation/tgstation/pull/71460
