### ISSUE TITLE
You can traverse z-levels by moving down while inside a mech, letting you go into centcom.

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#71484]
Reporting client version: 514.1589

## Round ID:
[194936](https://scrubby.melonmesa.com/round/194936)

## Testmerges:
- [Adds logic to provide leniency for drag clicks](https://www.github.com/tgstation/tgstation/pull/71082)
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)
- [Atmospheric machineries now interact with each other directly, rather than going through a radio layer -- saves about 0.4s of init time](https://www.github.com/tgstation/tgstation/pull/71232)
- [Revert "Unit tests radio, saymode, and language prefix keys"](https://www.github.com/tgstation/tgstation/pull/71474)

**Comment by saprasam** [comment]
it feels good finding a new way to break into centcom
