### ISSUE TITLE
Cleanbot reads a lot of null values

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#71493]
**Steps to reproduce**
1. Start the server choose map metastation[from my experiments don't know about other maps]
2. Observe the server log for some time maybe 5 to 10 minutes
![Screenshot (9)](https://user-images.githubusercontent.com/110812394/203799915-ef7dbc8e-8b59-49ee-a25f-2830fd3d1e8f.png)

Don't know the exact conditions when this occurs i just happened to randomly check my log. I'll post more details when i find them.

**Comment by Sealed101** [comment]
relevant code:
https://github.com/tgstation/tgstation/blob/ac6064c5f9b4ac9500b06b87a1f8b24f90e787ab/code/modules/mob/living/simple_animal/bot/cleanbot.dm#L295-L301

on metastation it fires a runtime as it tries to go to the dirt under the bed in a brig cell

![image](https://user-images.githubusercontent.com/75863639/203835139-909d76ba-4be1-4e85-a987-86b79af8de2e.png)

it doesn't have any path set, but it tries to check the path's length anyway

**Comment by Inari-Whitebear** [comment]
Seems like it should use the set_path method from bot to set the path instead of setting it directly?
