### ISSUE TITLE
Air alarm operating modes are not setting scrubber filters properly

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#71509]
Reporting client version: 514.1589

## Round ID:
[195011](https://scrubby.melonmesa.com/round/195011)

## Testmerges:
- [Adds logic to provide leniency for drag clicks](https://www.github.com/tgstation/tgstation/pull/71082)
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)
- [Atmospheric machineries now interact with each other directly, rather than going through a radio layer -- saves about 0.4s of init time](https://www.github.com/tgstation/tgstation/pull/71232)
- [Revert "Unit tests radio, saymode, and language prefix keys"](https://www.github.com/tgstation/tgstation/pull/71474)

## Reproduction:
Air alarms operating modes do not seem to be setting gasses to filter in scrubber settings when selected. I had tested this on a couple of scrubbers in an area with some contaminated air, and it failed to filter anything, needing manual selection.

1. Get a room with a contaminate gas of your choice
2. Check current scrubber filtering settings
3. Set air alarm to contaminated
4. Check the settings of the scrubber filter once more
5. Scrubbers fail to scrub the air

**Comment by LemonInTheDark** [comment]
@Mothblocks

**Comment by Mothblocks** [comment]
Ugh

I am not home to remove the test merge, can you do it

**Comment by Mothblocks** [comment]
I am closing this because it is (likely) a test merge bug, but I will be solving this

**Comment by LemonInTheDark** [comment]
yeah sure
