### ISSUE TITLE
Some ghost role spawns (like spiders) can get GBJ'd by mapping

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#71504]
## Reproduction:
Not sure how many maps this is on but definitely Kilo; spiders were spawned in a room with an abandoned airlock helper door as the only exit. ...but it spawned a wall, and they couldn't destroy any walls, rendering them permanently trapped without outside intervention.

![image](https://user-images.githubusercontent.com/66640614/203873149-fb4000c1-8741-4970-b1d7-e5f885a06e29.png)

**Comment by Addust** [comment]
make them able to tear down walls

**Comment by timothymtorres** [comment]
This happened recently on another round.
