### ISSUE TITLE
Unable to imprint ID on PDA.

### ISSUE THREAD

**Issue by Xander3359** [tgstation/tgstation#71512]
Reporting client version: 514.1589

## Round ID:
[195017](https://scrubby.melonmesa.com/round/195017)

## Testmerges:
- [Revert "Unit tests radio, saymode, and language prefix keys"](https://www.github.com/tgstation/tgstation/pull/71474)

## Reproduction:
Lose your roundstart PDA
Go to hopline and get a new PDA
Put in your ID
Try to imprint ID (The button is gone)
Try using the messenger app (Can't, it requires a imprinted ID)
None of the apps seem to have a way to imprint a ID, the button is gone and there's a loss of functionality due to it.

**Comment by JohnFulpWillard** [comment]
You able to replicate this still? I can't lol
