### ISSUE TITLE
You can disassemble PDAs with a wrench and it'll also delete the ID

### ISSUE THREAD

**Issue by Cheshify** [tgstation/tgstation#71514]
## Round ID:
[195017](https://scrubby.melonmesa.com/round/195017)

## Testmerges:
[#71474: 'Revert "Unit tests radio, saymode, and language prefix keys"' by MrStonedOne at commit 68b8bcd408](https://www.github.com/tgstation/tgstation/pull/71474)

## Reproduction:
Just spawn in, and click your PDA with a wrench in hand.

**Comment by LemonInTheDark** [comment]
wtf

**Comment by ZephyrTFA** [comment]
can we get a fuckup of the year here

**Comment by LemonInTheDark** [comment]
this has gotta be like 4 years old man

**Comment by ZephyrTFA** [comment]
still one hell of a fuckup

**Comment by Jacquerel** [comment]
After investigation, turns out you could use this to delete pais as well.
