### ISSUE TITLE
Return gateway did not work

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#71522]
## Testmerges:

N/A 

## Details:

From a discord DM (The man appears to be unable to log into github):
the gateway inside the away mission place didn't work, despite being on/active
also not sure if the air is correct inside because i burst into flames smoking a cig, so the halls may have leaks or something, but it caused a major fire inside, a few people got trapped

![image](https://user-images.githubusercontent.com/58055496/203988213-218767b7-9ed4-4f6d-a271-b8726344e7b9.png)

![image](https://user-images.githubusercontent.com/58055496/203988242-425ee419-e5a8-4961-8ee5-074cea295f1e.png)

**Comment by msgerbs** [comment]
Was the station side gateway depowered? When this happened to me, I ahelped and the responding admin eventually determined the gateway was unpowered and took pity on me and moved me back manually.

**Comment by kayozzx** [comment]
I'm not sure tbh. I know throughout the round it was powered station side and a few people went through during the round including myself , but several people mentioned getting stuck.
Also I did try and pray/ahelp but no admins were online.
