### ISSUE TITLE
Unequipped memento mori dusts Space Dragon and contents when the dragon dies.

### ISSUE THREAD

**Issue by Phaseus** [tgstation/tgstation#71536]
Server: /tg/Station Manuel
[Round ID]: #195076

BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [b52b4f8dd7e0c8e1db250eaa934e6338aa60c29f](https://www.github.com/tgstation/tgstation/commit/b52b4f8dd7e0c8e1db250eaa934e6338aa60c29f)
The following pull requests are currently test merged:
[#71520: 'fixes & increases SSinput click delay threshold & moves it and average_click_delay to deciseconds' by Kylerace at commit 73347fa0f9](https://www.github.com/tgstation/tgstation/pull/71520)
[#71474: 'Revert "Unit tests radio, saymode, and language prefix keys"' by MrStonedOne at commit 19d0ba1b7e](https://www.github.com/tgstation/tgstation/pull/71474)
[#71527: 'Partially reverts moving up/down whilst in a movable from #70431' by Watermelon914 at commit bb1ccc9005](https://www.github.com/tgstation/tgstation/pull/71527)

Local commit: eeaa69a7add5c467b383f92428982ae8fb8d5ef8
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1

## Reproduction:

Step 1: Become a space dragon.
Step 2: Eat a bunch of people, or at the very least a person with a Memento Mori stored in a bag.
Step 3: Get killed due to not placing enough rifts in time.

As a result of these three steps, we found that every individual consumed by the space dragon will get dusted when the dragon dies. The unused memento mori as well as any trading cards in the character inventories will be the only remaining items. Another interesting result is that any Wisps equipped will remain active even after the original owner has been dusted by the death of the dragon.

![image](https://user-images.githubusercontent.com/18403372/204067161-bce49bcb-fdc5-4345-8195-354503b30102.png)

**Comment by Mooshimi** [comment]
So it also deleted the container? Neat.

**Comment by Phaseus** [comment]
> So it also deleted the container? Neat.

Yep. I'm also not 100% sure if the trading cards were part of the stomach's contents, but I don't see why they'd be out in space right where I died.
