### ISSUE TITLE
Tesla energy balls can be recycled.

### ISSUE THREAD

**Issue by plutori** [tgstation/tgstation#71541]
Reporting client version: 514.1589

## Round ID:
[195104](https://scrubby.melonmesa.com/round/195104)

## Testmerges:
- [Adds logic to provide leniency for drag clicks](https://www.github.com/tgstation/tgstation/pull/71082)
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)
- [Revert "Unit tests radio, saymode, and language prefix keys"](https://www.github.com/tgstation/tgstation/pull/71474)
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)

## Reproduction: The tesla, apparently, if it hits a recycler (The ones used for trash, in disposals) will be recycled and deleted.

1. Delaminate a supermatter crystal with above 5k MeV to spawn a tesla
2. Wait for it to hit a recycler
3. Cry

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/4d6a8bc5371eb61f9adb7c4dd1b8c441d3ae9251/code/modules/power/tesla/energy_ball.dm#L13-L30

https://github.com/tgstation/tgstation/blob/4d6a8bc5371eb61f9adb7c4dd1b8c441d3ae9251/code/game/machinery/recycler.dm#L110-L164

If we do an early return for the recycler eat proc, we can avoid destroying the telsa ball by doing:

```
if(item.resistance_flags & INDESTRUCTIBLE)
    return
```
