### ISSUE TITLE
You can bypass all word filters using emote mode

### ISSUE THREAD

**Issue by NamelessFairy** [tgstation/tgstation#71570]
## Round ID: [195174](https://scrubby.melonmesa.com/round/195174)
(Permission given by timber to use an ongoing round)

## Testmerges:
#71474
#71527

## Reproduction:
State a word that is hard or soft filtered using the "Me"/emote chat mode. You will be able to say it without any warning.

**Comment by Timberpoes** [comment]
Fix is to take all the filter related code out of `/mob/try_speak()` and put it into its own proc.

Then make the say() and emote() code paths use this proc.

Extra credit if we then use this new proc to create word filter unit tests to make sure a wide variety of messages are correctly identified and categorised by the chat filters.
