### ISSUE TITLE
Its very very very common to get strange seed packs with no reagents

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#71589]
## Round ID:
Nearly every round on manuel for the past few days

## Reproduction:
Buy the 2 packs of strange seeds from the botany mega seed vend, see they have no reagents. Buy an exotic seed crate from cargo, neither of the packs in the crate have reagents

**Comment by flowercuco** [comment]
i just tested it right now, i spawned in 10 random seeds and viewed their variables, only 2 had no reagents. 
i grew one of the random ones that had reagents and grinded it up and it had reagents.
in the code theres a 40% chance that the random seeds will not have reagents. 
I bought a bunch of seeds and the exotic crate did have reagents in it.
The two roundstart seeds in the machine did not have reagents but then I refilled it and then it did have reagents.

Going to see if roundstart vending machines are always without reagents bc thats the last thing left to check, but it takes a while obvs.

**Comment by flowercuco** [comment]
update: i just got a bag of seeds with reagents on it on a fresh hacked seedvend.
when you only have the two bags i agree that it doesn't feel like 60/40 but that is almost a coinflip, and spawning them in 10 at a time does feel more like 60/40.

**Comment by Jackal-boop** [comment]
So not a bug

**Comment by Time-Green** [comment]
https://github.com/tgstation/tgstation/blob/e31ea3b34839cef1b0cc2be8a088cc2955de947b/code/modules/hydroponics/grown/random.dm#L16-L24

It's a feature, sorry :/
It's not fit for the bugtracker, but you're free to make a PR to change it (or convince someone else to do it)
