### ISSUE TITLE
AI satellite is not connected to the station power grid on Delta station

### ISSUE THREAD

**Issue by plutori** [tgstation/tgstation#71604]
Reporting client version: 514.1589

## Round ID:
[195272](https://scrubby.melonmesa.com/round/195272)

## Testmerges:
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)
- [Changes our map_format to SIDE_MAP](https://www.github.com/tgstation/tgstation/pull/70162)
- [Adds logic to provide leniency for drag clicks](https://www.github.com/tgstation/tgstation/pull/71082)

## Reproduction:

Not so much a bug as a mapping oversight. The satellite is not connected to the power grid by default. In the shift I'm reporting from, I had to place a piece of cable using an AI shell on the tile where the transit tube exits in order to connect the satellite to the power network. Was told by Armhulen to issue report.

**Comment by dragomagol** [comment]
Isn't this intentional? I think the AI is supposed to be on its own grid.

**Comment by Ryusenshu** [comment]
just checked
the multilayer hub goes blue cable at the transit tube who then goes into both smes
which then goes onto yellow to power each apc

im not seeing the issue

**Comment by san7890** [comment]
@Maurukas you're the only one who can definitively answer this question

**Comment by Sealed101** [comment]
it do be connected though

![изображение](https://user-images.githubusercontent.com/75863639/224984222-0bf91868-1541-4156-b7e9-2b420c3616b7.png)

![изображение](https://user-images.githubusercontent.com/75863639/224984323-88c5cdea-7752-4205-a2a3-7172071ac17b.png)
