### ISSUE TITLE
The mutated carp-heart missing sprite

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#71612]
Reporting client version: 514.1589

## Round ID:
[195316](https://scrubby.melonmesa.com/round/195316)

## Testmerges:
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)

## Reproduction:

![image](https://user-images.githubusercontent.com/3789327/204658140-3fcd04b5-dc63-4aca-908e-888fc68d2082.png)

**Comment by dragomagol** [comment]
![image](https://user-images.githubusercontent.com/66640614/209273585-e518c646-c22f-487d-8018-346ea50e84f2.png)

Appears to have been fixed
