### ISSUE TITLE
The SecurEye app on laptops and computers doesn't display cameras

### ISSUE THREAD

**Issue by TheSmallBlue** [tgstation/tgstation#71618]
## Round ID: 
[195328](https://scrubby.melonmesa.com/round/195328)

## Testmerges:
#71566 #71520 #71527 

## Reproduction:
* Get a Laptop or go to a computer
* Input a valid security ID
* Go to the Software Hub and download the SecurEye app
* Open the app
* See how no cameras are listed, even when normal camera consoles display cameras just fine.
![dreamseeker_UWw3oagK77](https://user-images.githubusercontent.com/24967815/204701538-6dc1f196-1ae1-40e3-8a71-cab683d5a62d.png)

@zxaber reminder ping

**Comment by Sealed101** [comment]
this was a thing i've found and fixed during #71392. the issue was cameras in objects reading the camera's z instead of the turf of the object they were in, so borg cameras would break the app

**Comment by TheSmallBlue** [comment]
I made this issue while the round was going on, by that time your PR was already merged and should've already been in the game for a bunch of rounds shouldn't it?

**Comment by TheSmallBlue** [comment]
Ah I just saw what you edited on, odd, I'll check again tomorrow and see if it's fixed

**Comment by Sealed101** [comment]
merged does not necessarily mean already used on the servers. judging by the round data, the server commit is behind that pr's commit. we should wait until server ops run the update through and check again.

**Comment by Mothblocks** [comment]
it updates every 6 hours

**Comment by TheSmallBlue** [comment]
> merged does not necessarily mean already used on the servers. judging by the round data, the server commit is behind that pr's commit. we should wait until server ops run the update through and check again.

I know, I'm saying that by the time this happened 6/7 hours had already passed since it was merged. Didn't know how frequently the server's commit updated but usually it's around that time frame or less, which Mothblocks just confirmed

**Comment by TheSmallBlue** [comment]
Tested again, works fine
