### ISSUE TITLE
Carp lungs make you choke, even in space.

### ISSUE THREAD

**Issue by MrrFiish** [tgstation/tgstation#71622]
Reporting client version: 514.1589

## Round ID:
[195333](https://scrubby.melonmesa.com/round/195333)

## Testmerges:
- [Psykers](https://www.github.com/tgstation/tgstation/pull/71566)
- [fixes & increases SSinput click delay threshold & moves it and average_click_delay to deciseconds](https://www.github.com/tgstation/tgstation/pull/71520)
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)

## Reproduction:
1) Get carp lungs through the genetic infuser machine.
2) Start choking in the station.
3) Go into space and suffocate from too much oxygen, even though you're in a vacuum.

**Comment by dragomagol** [comment]
Fixed by #71023 71605
