### ISSUE TITLE
Digitigrade handling doesn't work for female body type

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#71624]
Reporting client version: 514.1585

## Round ID:
[195338](https://scrubby.melonmesa.com/round/195338)

## Testmerges:
- [Psykers](https://www.github.com/tgstation/tgstation/pull/71566)
- [fixes & increases SSinput click delay threshold & moves it and average_click_delay to deciseconds](https://www.github.com/tgstation/tgstation/pull/71520)
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)

## Reproduction:
See title.

Female body: 
![image](https://user-images.githubusercontent.com/81882910/204727554-17184f2b-1a28-4c26-8523-cdd47b28787a.png)

Male body: 
![image](https://user-images.githubusercontent.com/81882910/204727584-a1fa00c4-ed26-423d-a01c-3616edabbce9.png)

**Comment by lizardqueenlexi** [comment]
I'm managing to get totally different incorrect behavior:

![image](https://user-images.githubusercontent.com/105025397/204736347-ff4046ba-7c37-4028-bcb3-021d794bbbc7.png)

Digitigrade shorts sprite... on non-digitigrade legs. This only happens with the female bodytype - the correct shorts appear with the male one. I'm going to try to find the cause of this...

**Comment by LemonInTheDark** [comment]
@lizardqueenlexi was this actually resolved? you guys got in a
