### ISSUE TITLE
Ethereal revive does not apply a trauma

### ISSUE THREAD

**Issue by RandomPredictable** [tgstation/tgstation#71630]
## Reproduction:

As an Ethereal:
1. Die (in a way that is revivable.)
2. Wait for crystallisation.
3.5. Get encased in a crystal of the wrong colour.
3. Fall out of crystal alive.
4. Get the wrong chat alert, and receive no permanent brain trauma unlike intended.

Reproducible on local instance with the same merges as of writing, I've annotated a video showcasing the bug:
https://user-images.githubusercontent.com/84472254/204825882-ca6e0939-6bd2-4bfd-a6f8-3134abf3e6ec.mp4

The relevant bit of code as to what's *supposed* to happen (taken from /code/modules/surgery/organs/heart.dm)
```
/obj/structure/ethereal_crystal/proc/heal_ethereal()
	ethereal_heart.owner.revive(HEAL_ALL)
	to_chat(ethereal_heart.owner, span_notice("You burst out of the crystal with vigour... </span><span class='userdanger'>But at a cost."))
	var/datum/brain_trauma/picked_trauma
	if(prob(10)) //10% chance for a severe trauma
		picked_trauma = pick(subtypesof(/datum/brain_trauma/severe))
	else
		picked_trauma = pick(subtypesof(/datum/brain_trauma/mild))
	ethereal_heart.owner.gain_trauma(picked_trauma, TRAUMA_RESILIENCE_ABSOLUTE)
	playsound(get_turf(ethereal_heart.owner), 'sound/effects/ethereal_revive.ogg', 100)
	qdel(src)
```

**Comment by GoblinBackwards** [comment]
Broke in #71123 since revive calls full_heal which replaces all the organs with new ones, so after the revive call ethereal_heart becomes null and the new heart they get has the default value for its colour which means future revive crystals won't match the ethereals colour

**Comment by thgvr** [comment]
this needs fixing asap
