### ISSUE TITLE
Roboticists lack access to the mech removal crowbar cabinet

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#71642]
Reporting client version: 514.1589

## Round ID:
[195405](https://scrubby.melonmesa.com/round/195405)

## Testmerges:
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)

## Reproduction:
The mech removal tool was added for roboticists to remove people in the event they get stuck in a mech, but they don't seem to have access to their own cabinet.
1. Be a roboticist.
2. Find the mech removal tool cabinet.
3. Slap your roboticist ID on it.
4. Access denied.

I suspect it's still using the same access requirements as the fire axe cabinet.

**Comment by Sealed101** [comment]
it needs a multitool slap or a toolbox bashing brother

**Comment by Derpguy3** [comment]
While I do that all the time, it only feels that the roboticists should have the access for their tools.

**Comment by Sealed101** [comment]
it's functioning exactly as the fire axe cabinets do - you open 'em with a mutitool to disengage the lock or you smash the glass in, there are no access restrictions anywhere on those cabinets

**Comment by necromanceranne** [comment]
We didn't ID lock the atmos and bridge axe cabinets, I don't think we need to do the same for roboticists. Use the multitool provided. If you want to see that changed, make a PR and include fire axe cabinets. This is operating as expected.
