### ISSUE TITLE
tagger's art doesn't give positive moodlets, as it's supposed to

### ISSUE THREAD

**Issue by blackdav123** [tgstation/tgstation#71688]
Reporting client version: 514.1589

## Round ID:
[195562](https://scrubby.melonmesa.com/round/195562)

## Testmerges:
- [Rewrites how action buttons icons are generated, makes them layer nicer. Allows observers to see a mob's action buttons. ](https://www.github.com/tgstation/tgstation/pull/71339)
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)
- [Micro-optimize icon smoothing subsystem, cutting down more than 50% of its init time (about .8s drop on local, more on prod)](https://www.github.com/tgstation/tgstation/pull/69741)

## Reproduction:
1. Take tagger quirk
2. Make awesome art
3. It sucks
4. Cry

**Comment by blackdav123** [comment]
to reiterate on this, tagger quirk is supposed to make all graffiti you paint give a mood buff whereas it currently is giving a debuff

**Comment by Mothblocks** [comment]
please edit your issue description then because this is extremely useless
