### ISSUE TITLE
Odd gas duplication phenomena in connected canister.

### ISSUE THREAD

**Issue by Pickle-Coding** [tgstation/tgstation#71694]
## Round ID:
[195579](https://scrubby.melonmesa.com/round/195579)

## Reproduction:
Unsure. I was pumping plasma via volume pump into a pipenet with a connector port into it. When I secured the canister to the port, its pressure started rising way beyond the pump's limit, like over 60MPa. When I unsecured it and analysed it, there was somewhere around 50,000 to 60,000 moles of plasma. The pipenet pressure had a normal and expected pressure around 9MPa. This did not happen again after I secured the canister or secure another one into it again.

**Comment by Sadboysuss** [comment]
doesn't seem to be an issue anymore
