### ISSUE TITLE
Destination Tagger lacks belt on-mob icon

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#71692]
Reporting client version: 514.1589

## Round ID:
[195581](https://scrubby.melonmesa.com/round/195581)

## Testmerges:
- [Rewrites how action buttons icons are generated, makes them layer nicer. Allows observers to see a mob's action buttons. ](https://www.github.com/tgstation/tgstation/pull/71339)
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)
- [Micro-optimize icon smoothing subsystem, cutting down more than 50% of its init time (about .8s drop on local, more on prod)](https://www.github.com/tgstation/tgstation/pull/69741)

## Reproduction:
The destination tagger is lacking an on-mob sprite when put on the character's belt slot.
![Screenshot 2022-12-03 172358](https://user-images.githubusercontent.com/85206687/205468674-d05840d4-22bd-4066-bb73-98eaa84f238c.png)
![Screenshot 2022-12-03 173453](https://user-images.githubusercontent.com/85206687/205468675-2bddb5dc-d49b-4651-ac14-d6d56b3dff52.png)

**Comment by ShizCalev** [comment]
other broken ones
```
	FAILURE #1: 	1 - /obj/item/melee/cleric_mace using invalid worn_icon_state, "default_worn" in 'icons/mob/clothing/belt.dmi' at code/modules/unit_tests/worn_icons.dm:30
	FAILURE #2: 	2 - /obj/item/analyzer/ranged using invalid icon_state, "analyzerranged" in 'icons/mob/clothing/belt.dmi' at code/modules/unit_tests/worn_icons.dm:30
	FAILURE #3: 	3 - /obj/item/crowbar/red/caravan using invalid icon_state, "crowbar_caravan" in 'icons/mob/clothing/belt.dmi' at code/modules/unit_tests/worn_icons.dm:30
	FAILURE #4: 	4 - /obj/item/crowbar/drone using invalid icon_state, "crowbar_cyborg" in 'icons/mob/clothing/belt.dmi' at code/modules/unit_tests/worn_icons.dm:30
	FAILURE #5: 	5 - /obj/item/soulstone/mystic using invalid icon_state, "mystic_soulstone" in 'icons/mob/clothing/belt.dmi' at code/modules/unit_tests/worn_icons.dm:30
	FAILURE #6: 	6 - /obj/item/chisel using invalid icon_state, "chisel" in 'icons/mob/clothing/belt.dmi' at code/modules/unit_tests/worn_icons.dm:30
	FAILURE #7: 	7 - /obj/item/dest_tagger using invalid worn_icon_state, "cargo tagger" in 'icons/mob/clothing/belt.dmi' at code/modules/unit_tests/worn_icons.dm:30
```
