### ISSUE TITLE
You can't use text fields on paper that has been copied

### ISSUE THREAD

**Issue by TheSmallBlue** [tgstation/tgstation#71698]
## Round ID:
[195593](https://scrubby.melonmesa.com/round/195593)

## Testmerges:

#71645 #71527 #71520 #71339

## Reproduction:

1. Write a piece of paper with text entry field (written like [______]) and save it
2. Go to a photocopier, copy the paper
3. Grab the original paper, see how you can fill out field just fine by typing on them then clicking save
4. Grab the copied paper, see how even after clicking save, the fields just will not save.

**Comment by tnekohue** [comment]
Can confirm
![image](https://user-images.githubusercontent.com/17634568/206342939-6ff0a888-8f1d-4a79-912d-ac3ca88058ab.png)

**Comment by DaddyIssues98** [comment]
fucking fix this, cannot rolplay as lawyer. unplayable 😢
