### ISSUE TITLE
Gas canisters do not update their indicator lights when being drained / filled using a port.

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#71712]
## Testmerges:
#71645
#71527
#71520
#71339

## Reproduction:
Refill / empty a canister. You will notice it's indicator doesn't update properly, and is only refreshed after the canister is unwrenched.

**Comment by TheBoondock** [comment]
I was unable to reproduce this

**Comment by OverwatchVoice** [comment]
> I was unable to reproduce this

If you still struggle with it, I will make a quick vid showing the issue when I get home later today.

**Comment by ShizCalev** [comment]
> > I was unable to reproduce this
> 
> If you still struggle with it, I will make a quick vid showing the issue when I get home later today.

That'd be very helpful. ♥

**Comment by OverwatchVoice** [comment]
Did what I could, but I couldn't find a way to reproduce it. It may just have been a one-off graphical issue
