### ISSUE TITLE
Blobs attack invisible revenents

### ISSUE THREAD

**Issue by Slime842** [tgstation/tgstation#71715]
So uh this doesn't need an id because it happens everytime there's a blob and a revenant so I cannot specify or I wl not write down a the id of a blob and a revenant shift so I'll just get straight to the point

When a revenant enters a blob tile the blob attacks the revenant wich will reveal the revenants position when crew is fighting the blob wich will tell the crew to avoid that spot and know that there's a revenant ready to finish them off once they go to critical

**Comment by private-tristan** [comment]
so when the blob tries to expand onto a tile that a revenant is incorporeal will cause the blob to attack the revenant instead of expanding onto the tile?

**Comment by Slime842** [comment]
Yes it will even if the revenant touches the blob
