### ISSUE TITLE
Spawning as a Blade Spirit Leads to the Error Room

### ISSUE THREAD

**Issue by Phaseus** [tgstation/tgstation#71716]
Reporting client version: 514.1585

## Round ID:
[195621](https://scrubby.melonmesa.com/round/195621)

## Testmerges:
- [UPDATE_APPEARANCE PROFILING TESTMERGE](https://www.github.com/tgstation/tgstation/pull/71645)
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)
- [fixes & increases SSinput click delay threshold & moves it and average_click_delay to deciseconds](https://www.github.com/tgstation/tgstation/pull/71520)
- [Rewrites how action buttons icons are generated, makes them layer nicer. Allows observers to see a mob's action buttons. ](https://www.github.com/tgstation/tgstation/pull/71339)

## Reproduction:

During a 4.5 hour round of Ice Station, I was offered the ghost role to possesses a Holy Claymore, but instead of spawning with the master, I was placed in the 'error room' which looks like the one from The Legend of Zelda: A Link to the Past. When you arrive, the stone states that you should not be here, and that you should report the error to an admin. Shortly thereafter it'll spawn a ladder which will drop you in a random location. In my case I was put in the permabrig and had to find a way back to the station without breaking anything, since possessed blades aren't inherently antagonistic. Additionally, the name I chose didn't get applied, so I ended up being 'The spirit of' instead of the generic sword name I picked at the time.

Here is an image of where I ended up after the error room: https://i.imgur.com/YasI6wf.png
Unfortunately I didn't get an image of the room itself, but it spawns on one of the admin Z-levels so I'm sure you can figure out where it is.

AyamePup is the admin that responded to my ahelp to confirm that the error room was not in fact an intentional joke area for possessed blade spawns.

**Comment by Sealed101** [comment]
image from the link repost
![изображение](https://user-images.githubusercontent.com/75863639/224763861-5a323d20-ba8c-4735-b90f-5a470f40fd57.png)


did the spirit mob created in the possessed blade somehow detach from the blade? needs repro
