### ISSUE TITLE
Magboots do not function when standing on lattices in the upper floor of a multi-z level.

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#71711]
## Testmerges:
#71645 
#71527 
#71520 
#71339 

## Reproduction:
Stand next to the supermatter on only lattices while wearing magboots. The supermatter will suck you in.

**Comment by Sealed101** [comment]
i mean lattices do not count to being a tile that gets affected by gravity, so technically it's not a bug?
