### ISSUE TITLE
Crab Rangoon sprite missing (?)

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#71736]
## Testmerges:
[#71731: 'Holy SHIT it's the FUCKING NORTH STAR' by Cheshify at commit 609d9a3216](https://www.github.com/tgstation/tgstation/pull/71731)
[#71645: 'UPDATE_APPEARANCE PROFILING TESTMERGE' by LemonInTheDark at commit 806c8c9768](https://www.github.com/tgstation/tgstation/pull/71645)
[#71527: 'Partially reverts moving up/down whilst in a movable from #70431' by Watermelon914 at commit bb1ccc9005](https://www.github.com/tgstation/tgstation/pull/71527)
[#71520: 'fixes & increases SSinput click delay threshold & moves it and average_click_delay to deciseconds' by Kylerace at commit 73347fa0f9](https://www.github.com/tgstation/tgstation/pull/71520)

## Reproduction:
Self-explanatory. Create crab rangoon, admire the error sprite

**Comment by flowercuco** [comment]
the sprite is in the meat.dmi, easy fix, someone probably moved it recently but didnt change the code or something
