### ISSUE TITLE
Tramstation shuttle dock exterior was set to Lavaland generic area for some bullshit reason

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#71747]
Reporting client version: 514.1583

## Round ID:
[195697](https://scrubby.melonmesa.com/round/195697)

## Testmerges:
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)

## Reproduction:

1. put bomb right outside tram lower mining dock
2. why does it say lavaland
3. open SDMM and fix

![image](https://user-images.githubusercontent.com/80979251/205710845-7885014f-6593-442d-b88d-53932b9ea6dc.png)

**Comment by san7890** [comment]
yeah pretty much every exterior portion on tram is like this

**Comment by san7890** [comment]
will require more than just "repath the areas on tram", probably need to make a new `/area/station/asteroid` or something
