### ISSUE TITLE
Bunker interview box has no close button

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#71752]
## Round ID:
[195708](https://scrubby.melonmesa.com/round/195708)

![image](https://user-images.githubusercontent.com/83487515/205740054-9b2be6ca-9c51-4a72-9d4f-ba59785939d7.png)

## Reproduction:
Get approved on your application, when approved there's no button to close the interview box.

**Comment by jlsnow301** [comment]
`canClose={is_admin}` 🥴
