### ISSUE TITLE
Ordnance Burn Chamber Airlock Cycle to External sequence is broken

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#71777]
## Reproduction:
Use the Airlock Control panel in Ordnance Burn chamber, open Internal airlock, enter the buffer chamber, start the Cycle to External sequence, realize that the air pump is not draining air and the sequence is not working. The Abort button also does not work.

probable cause - #71232 

something in this file is fucking up, i think this is the sequence for cycling to external

https://github.com/tgstation/tgstation/blob/5c18606d9bae4f4a6f6117b0bcc990f616ecedd9/code/game/machinery/embedded_controller/airlock_controller.dm#L186-L209

from local testing, the weakrefs to the machinery seem to be fine, i'm guessing the sequence itself got whacked

**Comment by Profakos** [comment]
I have found it! A pump.on = TRUE was missing from depressurizing.
