### ISSUE TITLE
Records consoles (Security, Med) have no logging for name changes

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#71798]
## Testmerges:

n/a

## Reproduction:
There is no logging (in-round or administrative) for anyone changing the records in records consoles (notably the security one since the medical records only have flavour value)
You can change everyone's name to dickbutt on their record and admins arent gonna know for sure who done it

**Comment by dragomagol** [comment]
I'm seeing investigate entries for these in `INVESTIGATE_RECORDS` in `code/game/machinery/computer/medical.dm` (just deletions) and `code/game/machinery/computer/security.dm` (everything but name changes, it seems).
