### ISSUE TITLE
Abductor brainwashing isn't cured by mindshields or removing organ

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#71790]
Reporting client version: 514.1585

## Round ID:
[195805](https://scrubby.melonmesa.com/round/195805)

## Testmerges:
- [fixes & increases SSinput click delay threshold & moves it and average_click_delay to deciseconds](https://www.github.com/tgstation/tgstation/pull/71520)
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)

## Reproduction:
Get abducted.
Run to medbay because you puked plasma or something.
They remove the organ, your brainwash stays permanently. Same steps with mindshield.
Can't find this change being documented anywhere, a while ago Abductors were shifted away from having permanent traumas/brain tied effects.
I can't see it being intentional that you have to execute victims of abductors.

**Comment by Serxule** [comment]
pretty sure this isnt a bug

**Comment by thgvr** [comment]
it's an undocumented change, so it's a bug until proven otherwise. Removing the organ always fixed it.

**Comment by necromanceranne** [comment]
I can't actually remember a time when it did in the last four years at least.

**Comment by thgvr** [comment]
Taking the organ out always fixed the brainwash objective. You may be thinking of the permanent traumas the abductor experimentation surgery always left behind, which were removed.

**Comment by Sealed101** [comment]
the objectives are not tied to the organ or the brain trauma, they're granted with an abductee antag datum. the abductees do not have and seemingly have never had any ties to the organ, as well as not showing anything that would remove their antag status upon being mindshielded. in fact, i can't quite find anything pointing to abductee antag status ever being removable.

i think you got gaslit/abducted and brainwashed into thinking this was a feature. or you were mistaking brainwashed antagonists for abductees.
