### ISSUE TITLE
Component examine on circuitboards is fucked up

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#71807]
## Round ID: [195836](https://scrubby.melonmesa.com/round/195836) 

A bunch of machine circuitboards seem to have this, the ORM seems to have gotten it the worst: 
![image](https://user-images.githubusercontent.com/7501474/206278952-b60a8d52-7e9d-4075-ab8b-d7e06c6c86a1.png)

Probably caused by #71693
@Mothblocks

**Comment by Time-Green** [comment]
![image](https://user-images.githubusercontent.com/7501474/206279991-e74be216-7e90-4601-aedc-2e35eeccd691.png)

**Comment by Mothblocks** [comment]
Hm, ore redemption machines don't use scanning modules.

**Comment by Mothblocks** [comment]
https://github.com/tgstation/tgstation/blob/b6bc8c6c297926472cb411d1833644e00017d73e/code/game/objects/items/circuitboards/machines/machine_circuitboards.dm#L1203-L1208
