### ISSUE TITLE
You can throw around the clown's car with the power of the telekinesis.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#71803]
## Testmerges:
[#71527: 'Partially reverts moving up/down whilst in a movable from #70431' by Watermelon914 at commit bb1ccc9005](https://www.github.com/tgstation/tgstation/pull/71527)
## Reproduction:
Someone was using their telekinesis to throw the car around. I mean, it's an object, so it's probably not a bug, but still, sounds kind of unfair.

**Comment by Mooshimi** [comment]
Did it bang into the wall and spit everyone out via the TK throws

**Comment by IllotAFV** [comment]
I don't really remember about the wall hits, but the car could run over people with this.

**Comment by JohnFulpWillard** [comment]
I don't wish to make clown cars exceptions to telekinesis, this is a unique way of dealing with it and I don't see that as a bad thing, in fact it's pretty funny.
