### ISSUE TITLE
RPED doesn't exchange datum stock parts correctly & doesn't install datum stock parts

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#71801]
Caused by #71693

Steps to reproduce

1. Create an empty machine frame with anomaly refinery circuit board installed 

2. Create a fully assembled anomaly refinery[by hand cause RPED dosen't work] 

3. Watch the video below

https://user-images.githubusercontent.com/110812394/206229168-8a819c83-0d4d-4316-9570-910061957ba9.mp4

**Comment by SyncIt21** [comment]
@Mothblocks

**Comment by Mothblocks** [comment]
Aaaaagh I swore I test this...
