### ISSUE TITLE
Any head of staff can open the teleporter

### ISSUE THREAD

**Issue by Overuseddart** [tgstation/tgstation#71806]

**Comment by Overuseddart** [comment]
> the HoP, RD, and captain (duh) have teleporter access by base
> the CMO, CE, and HoS have teleporter access as extra access

I think they all have acces to specifically the shutters, including the QM, even on high pop

**Comment by Sealed101** [comment]
teleporter shutters buttons have command access requirement
![image](https://user-images.githubusercontent.com/75863639/206290658-e50486a0-4781-4439-9ea3-c4599afafa61.png)
the doors themselves use a helper with teleporter requirement
