### ISSUE TITLE
Carrying a candle does not move the light from where you started it 

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#71826]
## Reproduction:

- Light candle
- Pick it up
- Walk around
- The light stays where you picked it up, does not follow
- Pocket it
- The light moves to where you pocketed it, does not follow
- drop it and drag it
- Light follows

**Comment by timothymtorres** [comment]
Looks like a dupe of #38109

**Comment by timothymtorres** [comment]
Just tested both of these and it seems the old issue I mentioned was fixed at some point.

**Comment by Mooshimi** [comment]
Same with lamps, being that lamps is an active issue with the light being left behind
