### ISSUE TITLE
You can trap people in the infuser (more than one)

### ISSUE THREAD

**Issue by Skyfiremighty** [tgstation/tgstation#71827]
## Round ID:
[195857](https://scrubby.melonmesa.com/round/195857)

## Reproduction:

To reproduce put a person in the infuser and drag yourself into it, if this does not work just try dragging them in and you in and open and close till it works.

**Comment by Time-Green** [comment]
@tralezab

**Comment by Skyfiremighty** [comment]
![image](https://user-images.githubusercontent.com/103969620/206522770-caf870bf-8006-467c-8ab4-28542d15789d.png)
