### ISSUE TITLE
Both regular and tagger graffitis SUCK

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#71841]
## Round ID:
[195881](https://scrubby.melonmesa.com/round/195881) (most recent atm, the issue appeared like 2-3 days ago)

## Reproduction:
Appraise a graffiti. Wow, it sucks.

**Comment by Serxule** [comment]
already a fix thats been up for a while https://github.com/tgstation/tgstation/pull/71760

**Comment by Dorsisdwarf** [comment]
Dupe of #71688
