### ISSUE TITLE
Missing required materials in Description of circuit boards and machines.

### ISSUE THREAD

**Issue by delaron** [tgstation/tgstation#71872]
Round ID: [195961](https://scrubby.melonmesa.com/round/195961)

Circuit boards and Machines that require materials like beakers do not display all the requirement in the description. It shows all the numbers required but wont show all the materials. Beakers for the techfab, matter bins on the cyrotube. Its not universal regarding what is missing.

**Comment by Sealed101** [comment]
seems like a remnant of the stock parts datumising, which were fixed eventually
