### ISSUE TITLE
Tot objective displaying the correct gender.

### ISSUE THREAD

**Issue by ChumbleBusiness** [tgstation/tgstation#71898]
In some traitor uplink missions descriptions, the gender of the target is incorrect. So, if your objective is to steal someone's eyes, whether female, other, or male, it will say "He's been on our shitlist for a while"  This is a small detail but in a game all about small details. It feels wrong for something so simple as a target gender to be incorrect.

**Comment by lizardqueenlexi** [comment]
As far as I could tell, it was only the Steal Heirloom objective with this issue - so I corrected that one.
