### ISSUE TITLE
Disco Inferno's main gimmick is broken and it's super lame now (plasma material datums are TOO explosive) 

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#71894]
## Reproduction:

https://user-images.githubusercontent.com/51863163/206827586-768c5048-2bfc-4bc5-b310-bd68212b5413.mp4

**Comment by timothymtorres** [comment]
Likely caused by #69584 however I don't see the problem here.  People would still just ignite the plasma into an inferno and kill everyone in the resulting fire, which is the same outcome.
