### ISSUE TITLE
Multi-cell charger is uncategorised for techfab/imprinter tgui

### ISSUE THREAD

**Issue by Quink-Fix** [tgstation/tgstation#71896]
## Round ID:
N/A (Tested locally)

## Testmerges:
N/A

## Reproduction:
The machine board for multi-cell chargers is not categorised and thus does not appear in the tgui techfab/circuit imprinter lists. This can be circumvented by searching for the board directly.
1. Research entire techweb via debug
2. Use a generic circuit imprinter
3. Observe that the multi-cell charger is not in any of the machine board categories
4. Search "multi"
5. The multi-cell charger should appear.

This issue was observed on the Skyrat tg downstream, however digging into code from the original tgui PR on this codebase revealed the lack of categorisation for this machine in this codebase too. 
Included images taken from a generic circuit imprinter.
![image](https://user-images.githubusercontent.com/88389357/206831590-dda8dda5-c109-4b6a-bce4-03a8f0c8a4e8.png)
![image](https://user-images.githubusercontent.com/88389357/206831600-920b50d1-438f-4470-a585-c6367f286757.png)

**Comment by lizardqueenlexi** [comment]
It looks like the multi-cell charger is a Skyrat-specific machine, and isn't present on this codebase. So, it'd have to be fixed downstream instead of here.

https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/modular_skyrat/modules/multicellcharger/code/multi_cell_charger.dm

**Comment by Serxule** [comment]
yeah i was gonna say, i dont think we even have this

**Comment by Quink-Fix** [comment]
Fucking whoops. I apologise, closing and op3nint the issue downstream
