### ISSUE TITLE
Packaged crates are invisible

### ISSUE THREAD

**Issue by NamelessFairy** [tgstation/tgstation#71905]
## Round ID: [196017](https://scrubby.melonmesa.com/round/196017)

(ongoing round, tested in thunderdome so its ok 🐈)

## Reproduction:

Potentially caused by #69416 since it appears to be the last PR that touched the icon file.

Package a crate using package wrap, it becomes invisible.

**Comment by Time-Green** [comment]
Also broke briefcase sprites, they're just not in the spritesheet
