### ISSUE TITLE
Wrapping Paper Causing Items To Turn Invisible

### ISSUE THREAD

**Issue by IAmMediocre** [tgstation/tgstation#71913]
Reporting client version: 514.1589

## Round ID:
[196037](https://scrubby.melonmesa.com/round/196037)

## Testmerges:
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)
- [Creates short-lived foam (and applies it to the Scrubber Overflow)](https://www.github.com/tgstation/tgstation/pull/71850)

## Reproduction:
Using an instance of wrapping paper on a movable crate leads to the crate becoming invisible and uninteractable. Same goes for smaller parcels except they are still in your hand, just invisible.

**Comment by dragomagol** [comment]
Duplicate of #71905
