### ISSUE TITLE
Heretic blade teleports you when it shouldn't

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#71939]
## Reproduction:

Click your blade in the bag "too fast" and it will be used in hand.

**Comment by necromanceranne** [comment]
Sadly, this one is a latency/BYOND issue. Can't solve it on our end. I too know the pain of experiencing this. 

You just have to pace yourself when clicking items. Alternatively, this is an issue with specifically the blades and the way they are designed.
