### ISSUE TITLE
Brown Briefcase and Parcel are invisible 

### ISSUE THREAD

**Issue by Zargoar** [tgstation/tgstation#71935]
Reporting client version: 514.1589

## Round ID:
[196100](https://scrubby.melonmesa.com/round/196100)

## Testmerges:
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)
- [Creates short-lived foam (and applies it to the Scrubber Overflow)](https://www.github.com/tgstation/tgstation/pull/71850)

## Reproduction:

1. Spawn in as a lawyer.
2. Observe the briefcase in your hand is invisible.
3. Drop the briefcase on the floor.
4. Observe the briefcase is invisible on the floor.

Notes:
This issue reproduces for other players.
This issue also effects parcels.

**Comment by dragomagol** [comment]
Fixed by #71893
