### ISSUE TITLE
Psyker pirates cannot use consoles

### ISSUE THREAD

**Issue by jlsnow301** [tgstation/tgstation#71946]
## Round ID:

196119

## Testmerges:
None

## Reproduction:
Psyker pirates are blind, thus they are not able to interact with their own ship consoles to fly to the station.

(The ship console might be different, but) I spawned one on the syndie ship and tried to set a ship destination:
![Screenshot 2022-12-12 094240](https://user-images.githubusercontent.com/42397676/207116069-5b8d90d9-e45b-40cc-80c5-fe8519332c3d.png)
You can pull up the screen to depart, but can they not view cams or set the destination?

**Comment by Overuseddart** [comment]
Hey that was me!

**Comment by Jezzared** [comment]
Hey! This is _still a thing._ Maybe someone ought to get on that.

**Comment by Sealed101** [comment]
- #75031 has given the psyker ship both a psyker-friendly console to dock the ship and a literal normal person with working eyes
