### ISSUE TITLE
full firesuits dont protect against fire 

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#71956]
## Round ID: [196137](https://scrubby.melonmesa.com/round/196137)

Reproduction: wear full firesuit in plasmaflood, be on fire and watch as you still take burn damage and get burn wounds, and die from being on fire, even if the plasma wasnt on fire or high temp (it was 200c or lower)

fairly sure this is caused by the PR that allowed using internals if you had a full space helmet (which had a rework to what classifies headwear as a full, sealed head covering), as firehelmets _used_ to have full head atmos protection, but it was probably removed from them

**Comment by newfren** [comment]
I don't believe they've ever completely protected from fire? they only protected from the high pressure that the fire created, not the temperature

**Comment by Serxule** [comment]
> I don't believe they've ever completely protected from fire? they only protected from the high pressure that the fire created, not the temperature

the fire that was on me is what killed me, which they used to protect against, you could die from the atmos temp if it was too high (white-hot or higher) which none of the fire near me was as it had just ignited

**Comment by necromanceranne** [comment]
When we're talking firesuits, is it the specialized atmospherics ones or the red emergency suits? Did you have internals on? Did you have a mask on?

**Comment by Serxule** [comment]
> When we're talking firesuits, is it the specialized atmospherics ones or the red emergency suits? Did you have internals on? Did you have a mask on?

the red emergency ones, also yes i had internals and a mask

**Comment by Fikou** [comment]
emergency firesuits were never intended to fully protect against fire. they are for emergencies and significantly lengthen how much you can stay in one, but if you want full immunity you need an actual firesuit from atmos, or one of the fireproof modsuits

**Comment by Serxule** [comment]
then a bug definitely happened
