### ISSUE TITLE
Strange shuttle clinging behaviour

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#71977]
## Round ID:
196219

## Testmerges:
https://github.com/tgstation/tgstation/pull/71906

## Reproduction:
Cling to shuttle with magboots: Turn them off while on a solid tile and cling to the side, then turn them on again.
This allows for proper clinging up until landing, when the shuttle moved along z levels, but I did not.

**The original PR didn't mention magboots at all, so that's acceptable.**
However, afterwards I was standing still in space, while an item in my hand (plasma cutter) spun around like crazy (like the power yeet described in the PR, but it was still in my hand),  until I tried to bag it, then returned to normal, but couldn't get bagged at all despite the action message.

**Comment by Time-Green** [comment]
That magboot interaction is really weird, it shouldn’t ever override the drag

Seems items can sometimes be thrown while in inventories, I’ll look into it.
Thanks for the report! This’ll be closed soonish since it’s from the testmerge but I’ll fix it in the PR

**Comment by Time-Green** [comment]
I don't fully understand the magboot part, you managed to stand completely still outside the shuttle using magboots? I can't reproduce this. Are you sure you don't mean the slower spacedrift you get when you're holding on to the side of the shuttle?
