### ISSUE TITLE
You cannot cancel naming of paintings when finalizing them

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#71975]
Reporting client version: 514.1585

## Round ID:
[196207](https://scrubby.melonmesa.com/round/196207)

## Testmerges:
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)
- [Avoid wasted work creating body parts that are just going to be destroyed [0.3s of init]](https://www.github.com/tgstation/tgstation/pull/71916)

## Reproduction:
Press finalize, click cancel, and get untitled artwork that is finalized instead of the expected function of it canceling.

**Comment by Mooshimi** [comment]
true
