### ISSUE TITLE
Cult Barrier Rune Inconsistency 

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#71987]
Reporting client version: 514.1589

## Round ID:
[196244](https://scrubby.melonmesa.com/round/196244)

## Testmerges:
- [*hand, or That /One/ Emote You Always Felt Was Missing](https://www.github.com/tgstation/tgstation/pull/71600)

## Reproduction:
Be a cultist make barriers see them on see some hulk traitor just walk right through them on your base while you are stuck within the barriers you made die and see as they keep walking through the on barriers but somehow they can't see them being on wacky

![image](https://user-images.githubusercontent.com/84478872/207493518-4156cd1f-d5a5-4b18-a816-f9005733cae7.png)

**Comment by necromanceranne** [comment]
was it just hulk, or did he have dwarfism as well?

**Comment by moocowswag** [comment]
Im trying to walk through a barrier rune as a hulk , not working, i tried dwarfism, still no work, try with nullrod, still no work, dont know what else there is to try that a traitor might have access to.

**Comment by SethLafuente** [comment]
Up date on this it wasn't just hill it was everything it might be an issue with ghost vision ? It's rather confusing

**Comment by SethLafuente** [comment]
> was it just hulk, or did he have dwarfism as well?

Any one could this wasent related to any mutation and no he didn't have dwarfism

**Comment by SethLafuente** [comment]
freak incident if it shows up again well see right now its clutter
