### ISSUE TITLE
Xeno plasma and health regeneration appears to be inconsistent.

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#71994]
Reporting client version: 514.1589

## Testmerges:
- [*hand, or That /One/ Emote You Always Felt Was Missing](https://www.github.com/tgstation/tgstation/pull/71600)

## Reproduction:
Step 1. See xeno queen healing super fast and spamming eggs + spit mid combat.

 Step 2. Recall playing as queen, eggs/abilities are difficult to spam and health regeneration was not super fast

Step 3. Wonder if the speed at which their health / plasma storage updates is based on server performance at the time.

**Comment by Sealed101** [comment]
sigh
TD could probably fuck you up a lot with this regen, as well as any other tick-based regens which are all of them
