### ISSUE TITLE
Syndicate Propaganda posters can become festive

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#72003]
## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:

Summon your syndicate posters during holiday times. There is 30% they become a "Festive Notice Poster". They still have the necessary components, so you can finish the objective with them, so I would rather ask for a framework that elevates this a feature, with festive propaganda.

**Comment by Jacquerel** [comment]
Looks like this was fixed by the linked PR
