### ISSUE TITLE
Monkey cultist bug? | Can't use runes directly.

### ISSUE THREAD

**Issue by gamefreak2998** [tgstation/tgstation#72020]
Reporting client version: 514.1583

## Testmerges:
- [Fishing-themed Escape Shuttle](https://www.github.com/tgstation/tgstation/pull/71805)
- [DRAMATIC SHUTTLES!! You can now fly around the shuttle](https://www.github.com/tgstation/tgstation/pull/71906)

## Reproduction: Be monkey, Be cultist, No clever mutation?, attempt to use any rune directly, nothing happens. I can however draw them and use some magic? 

Monkeys seem unable to use cult runes? Clicking resulted in no message or action. Haven't tested with clever mutation or as evolved monkey.
EDIT: Thought i'd clarify the magic bit. Didn't get a chance to test most of it but blood rites cant seems to absorb blood as monkey but the direct touch spells work.

**Comment by Mooshimi** [comment]
https://github.com/tgstation/tgstation/blob/84f69359a0787adaa4047d42614858097e448692/code/modules/antagonists/cult/runes.dm#L106-L114

this is the only reason i see for not getting a feedback message at all. the possibility of being registered as a simple animal and there's no path for monkies
