### ISSUE TITLE
-1 silicon slots available

### ISSUE THREAD

**Issue by etherware-novice** [tgstation/tgstation#72034]
## Reproduction:
have ai and borg in round
![image](https://user-images.githubusercontent.com/73374039/208037146-9a71b3c6-1511-455b-9d0a-77630c5080a4.png)

**Comment by Jolly-66** [comment]
Doubt this is a bug.
Cyborgs have never been a late join option, they're simply picked via ghost pooling of posi (or human borging)

**Comment by Mooshimi** [comment]
https://github.com/tgstation/tgstation/blob/246810e6a3d5bd0e272b4b506e0b7435fe9bf737/tgui/packages/tgui/interfaces/JobSelection.tsx#L155-L157
