### ISSUE TITLE
1 tile big/ass images are moved to the SE corner in a Wanted Poster

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#72055]
I haven't tested this with bigger photos, because posters aren't really designed for them.
This issue makes part of the photo obscured and worsens the final product.

![assplasma](https://user-images.githubusercontent.com/68878861/208234874-1be0d828-dc01-45b9-98e7-b31fde33800a.png)

![obraz](https://user-images.githubusercontent.com/68878861/208234745-39fb84ee-9692-46cb-87b4-857550cf1567.png)

## Reproduction:
Take an ass photo, or a custom photo. Log into security records. Update a photo on a record, by clicking on the appropriate button while holding the photo in your hand.
It uploads properly.

Resulting wanted poster has the photo moved to the SE corner.

**Comment by timothymtorres** [comment]
Might be related to #56228

**Comment by Mooshimi** [comment]
alignment moment

**Comment by Sealed101** [comment]
as of #72725 the console simply rejects images that are larger than the required 1x1 size. kinda lame but i'm sure there will be some kind of workarounds for booty bounty calls and posters
