### ISSUE TITLE
PILLOWS ARE DANGEROUS AND HARMFUL WEAPONS (Pacifist bug)

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#72054]
## Round ID: 
tested, confirmed on local

## Testmerges:
nada

## Reproduction:

![image](https://user-images.githubusercontent.com/10399117/208233149-14ab8b82-1eac-437e-bade-d78cdd6df867.png)

Pillows, despite doing only stamina damage, cannot be used by pacifists.
Bizarrely, you can attack yourself with a pillow (dealing stamina damage, makes sound) and still receive a pacifist message.

**Comment by Mooshimi** [comment]
this extends to anything that does stamina damage besides "disablers". holographic swords, the shiny gold toolboxes for sparring, boxing gloves, etc
