### ISSUE TITLE
Signaler on Microwave bug

### ISSUE THREAD

**Issue by jlsnow301** [tgstation/tgstation#72053]
## Round ID:
#196445

## Testmerges:
*hand PR #71600 

## Reproduction:
Look, don't ask what I was doing, okay?

I attached a signaler to a microwave for a remotely cooked meal.

When activated, it spits the signaler out, which you cannot pick up, but you call pull, and it still activates the microwave.

**Comment by Likteer** [comment]
I saw a similarly behaving remote appear, after I deconstructed an emitter with one inside. 
Also some machinery like DNA scanner spit out a duplicate board, when you build one and open it, similarly to the older microwave bug, where upgrading resulted in a surprise explosion hazard.

**Comment by timothymtorres** [comment]
CC @Mothblocks I know you have been tinkering with cutting init costs by removing contents inside of machines so might be releated?

> I saw a similarly behaving remote appear, after I deconstructed an emitter with one inside. Also some machinery like DNA scanner spit out a duplicate board, when you build one and open it, similarly to the older microwave bug, where upgrading resulted in a surprise explosion hazard.

Uhhhh... you've got like several bugs listed here that each need their separate issue.

**Comment by Mothblocks** [comment]
I don't think this should have any relation to my changes, at least in how they exist now

**Comment by jlsnow301** [comment]
very similar #72132
