### ISSUE TITLE
Arrival shuttle stuck in hyperspace?

### ISSUE THREAD

**Issue by Cheshify** [tgstation/tgstation#72064]
## Round ID:
[196507](https://scrubby.melonmesa.com/round/196507)

## Testmerges:
Unsure, can't reconnect

## Reproduction:
Arrival shuttle just gets stuck, doesn't move.
![image](https://user-images.githubusercontent.com/73589390/208279752-09e5047f-ed2d-415b-98a5-310559a7c1d1.png)

**Comment by Mothblocks** [comment]
@ZephyrTFA this has gotta be your pr bro this is time number two

**Comment by Mothblocks** [comment]
we're 95% that this is a test merge bug from https://github.com/tgstation/tgstation/pull/71785

**Comment by Mothblocks** [comment]
I removed the TM, let me know if this comes up again
