### ISSUE TITLE
Gameplay preferences MultiZ detail on low - causes lower Z levels to become a mime fever dream

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#72063]
Both looking from above and being on them. 
I don't think I have to emphasize that this is unplayable - especially when things like xenomorph resin floors appear.
If this is intentional, could there be another middleground added between standard and low settings?
![obraz](https://user-images.githubusercontent.com/68878861/208268527-0e9e97fe-4dc1-414b-b5e6-e7c2c069a28c.png)

**Comment by TemporalOroboros** [comment]
Not intentional, this bug has popped up a couple times for a couple reasons. It'll probably get fixed soon.

**Comment by Pickle-Coding** [comment]
Strongly related: #71757

**Comment by Likteer** [comment]
I don't think this happens anymore

**Comment by Likteer** [comment]
I don't think this happens anymore, at least not due to MultiZ
