### ISSUE TITLE
Pentaerythritol reaction does not work

### ISSUE THREAD

**Issue by H3skan** [tgstation/tgstation#72072]
## Reproduction:

1 part Acetaldehyde

3 parts Formaldehyde

1 part Water

1 part = 10u. Does not react even when heated, all reagents pure.

**Comment by Inari-Whitebear** [comment]
Wiki says 1 part Lye, not Water?

**Comment by Profakos** [comment]
Code also says its Lye, so this bug report is incorrect.

**Comment by TheVekter** [comment]
You heard the man. Woman? Whatever.
