### ISSUE TITLE
Santa Claus doesn't get full EVA protection.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#72070]
## Round ID:
[196534](https://scrubby.melonmesa.com/round/196534)

## Reproduction:
The Santa's suit is a EVA suit, which offers a pressure proofness and even has a temprature regulator, but the hat is just a festive decoration, which doesn't give the desired effect of the full safety in space. It's probably not intended to have only half of the protection you expect from Space Santa.

**Comment by ShizCalev** [comment]
There are two different kinds of hats

An ACTUAL spacesuit hat
`/obj/item/clothing/head/helmet/space/santahat`

and a normal costume version
`/obj/item/clothing/head/costume/santa`
