### ISSUE TITLE
Brain traumas can give you magic somehow

### ISSUE THREAD

**Issue by CCC23** [tgstation/tgstation#72088]
Round ID196584

Reproduction

This is a bit iffy but if you give yourself cortex folding then a lobotomy you have a chance at getting honor bound which if you aren't a Chaplin will you give you a spell which does nothing and requires robes. I have no idea why this is happening.

**Comment by Time-Green** [comment]
Someone prob just forgot to blacklist honorbound

**Comment by Profakos** [comment]
Correct, random_gain is not set to false on it.
