### ISSUE TITLE
Bugged sprite ordering or so (Sm reflectors, burgers, maybe others)

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#72094]
Reflector bases are on top of the mirrors (except while the beam is being reflected). Also the bottom part of burgers is also on top of the burger, making them look weird. Don't have a picture of the burgers.

![image](https://user-images.githubusercontent.com/1077971/208433709-814a00bf-5924-431e-ba62-6826ca9165e2.png)

## Round ID: 
[Round ID]: [196590](https://scrubby.melonmesa.com/round/196590), but seen it in many rounds

## Testmerges:

#72089 

## Reproduction:

Make burger/look at reflectors

**Comment by LemonInTheDark** [comment]
from #70162 
thank you for paying attention. I'll get these two cleaned up

**Comment by Jacquerel** [comment]
May or may not be the root of #72035 also
Overlays look normal in VV panel but left digit does not display in actual game

**Comment by LemonInTheDark** [comment]
likely sidemap, yes. will have to check tho

**Comment by dragomagol** [comment]
![image](https://user-images.githubusercontent.com/66640614/208819668-cc3c18cc-edfc-4746-b3a2-97e04b7056ad.png)
Might also be causing hats to be under borgs

**Comment by LemonInTheDark** [comment]
> ![image](https://user-images.githubusercontent.com/66640614/208819668-cc3c18cc-edfc-4746-b3a2-97e04b7056ad.png) Might also be causing hats to be under borgs

yep

Burger fix done, others too. pr incoming

**Comment by Inari-Whitebear** [comment]
Another thing I noticed is that putting some stuff in the SM chamber, while the SM bolts happen, it appears above the SM. Like if I put 4-way manifolds on layer 2/3/4 as well as scrubbers on layer 5

Not sure if that's related to this

**Comment by LemonInTheDark** [comment]
likely is, yes. will investigate

**Comment by Inari-Whitebear** [comment]
![dreamseeker_dKyKdapxWd](https://user-images.githubusercontent.com/1077971/209339206-252c75d9-342b-44de-87a6-f63b8a9afaeb.gif)

demonstration. You see the scrubbers go below the cooling pipes sometimes, and also one scrubber appearing above the SM as it just gets hit by the emitter at the end.
