### ISSUE TITLE
Golem Vendors are being stolen to bypass the rework.

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#72092]
Reporting client version: 514.1589

## Round ID:
[196595](https://scrubby.melonmesa.com/round/196595)

## Reproduction:
As a result of #71023, miners (including on this round) have formed a habit of just stealing the golem mining vendor so they don't have to deal with the wait times of cargo, thus destroying the point of the rework completely and fucking over the ghostrole spawn for anyone who wants to take it.

Oh, also the mining vendor is still named "Produce Orders" when the UI is opened.

**Comment by Sealed101** [comment]
life finds a way

**Comment by Serxule** [comment]
who wouldve guessed that a PR that had a negative impact on gameplay made more negative impact on gameplay

**Comment by Jackal-boop** [comment]
Waiting for the revert PR

**Comment by rasepretep** [comment]
> Waiting for the revert PR

You don't even need to revert the PR, just turn it from stick to carrot.

Stick: "If you don't use the cargo shuttle, you will have to pay MORE for your gear."
Carrot: "If you use the cargo shuttle to order your gear, you'll get a discount!"

Seriously. Make express cost the standard 100% price like we're used to, make the cargo shuttle orders have like 25-50% point discount, and you will have miners begging to use it.

**Comment by Jackal-boop** [comment]
Make rasepetep a mining code owner please

**Comment by unit0016** [comment]
> Is this still a problem after #72380?

I've yet to see this behavior repeated since, so I think it successfully dissuaded it.

I'll (or whatever poor maintainer stumbles upon this in a few months) re-open this if that changes.
