### ISSUE TITLE
Endless runtimes when you throw something into lava

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#72100]
1. Go to lavaland
2. Throw something into lava
3. Get endless runtimes 911 in my specific case when i tried to throw all garbage in labour camp into the lava
![Screenshot (10)](https://user-images.githubusercontent.com/110812394/208483341-39476fdb-8b93-4038-9d4a-66ef6e2138a4.png)

**Comment by SyncIt21** [comment]
@LemonInTheDark did you fix this in your recent PRs by any chance?  I haven't seen this issue for some time now, but I don't want to close it till you/someone else give an assurance.

**Comment by SyncIt21** [comment]
This occurs randomly but very less often now. Not sure if I should close this.
CC @LemonInTheDark 
Thoughts?

**Comment by LemonInTheDark** [comment]
If it's still happening keep her open, don't need to close just cause it's less common
