### ISSUE TITLE
rats no eat chease

### ISSUE THREAD

**Issue by u-have-small-pp** [tgstation/tgstation#72116]
Reporting client version: 514.1584

## Round ID:
[196646](https://scrubby.melonmesa.com/round/196646)

## Runtime error:
 [2022-12-20 07:49:19.911] runtime error: The mouse wants to perform action type /datum/ai_behavior/run_away_from_target/mouse which requires movement, but has no current movement target! (code/datums/ai/_ai_controller.dm:170)
 - proc name:  stack trace (/proc/_stack_trace)
 -   source file: stack_trace.dm,4
 -   usr: (src)
 -   src: null
 -   call stack:
 -  stack trace("The mouse wants to perform act...", "code/datums/ai/_ai_controller....", 170)
 - /datum/ai_controller/basic_con... (/datum/ai_controller/basic_controller/mouse): process(0.1)
 - AI Behavior Ticker (/datum/controller/subsystem/processing/ai_behaviors): fire(0)
 - AI Behavior Ticker (/datum/controller/subsystem/processing/ai_behaviors): fire(0)
 - AI Behavior Ticker (/datum/controller/subsystem/processing/ai_behaviors): ignite(0)
 - Master (/datum/controller/master): RunQueue()
 - Master (/datum/controller/master): Loop(2)
 - Master (/datum/controller/master): StartProcessing(0)

## Reproduction:
so basicly i tryed to feed my rats some chease but it did not work due to the new ai that was added

**Comment by Likteer** [comment]
Ive had issues feeding rats/mice even before that change. Not sure if someone might have intentionally nerfed multiplying them.

**Comment by kooarbiter** [comment]
the rats want to go vegan? good for them
