### ISSUE TITLE
Racks don't want to exist

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#72155]
Reporting client version: 514.1589

## Round ID:
[196750](https://scrubby.melonmesa.com/round/196750)

## Testmerges:
- [holopara qol update](https://www.github.com/tgstation/tgstation/pull/72042)
- [[READY] DRAMATIC SHUTTLES!! You can now fly around the shuttle](https://www.github.com/tgstation/tgstation/pull/71906)

## Reproduction:
After you craft rack parts, when you try to assemble them by pressing Z, you get the message "You assemble a rack.", but nothing happens. The rack parts disappear from your hands and nothing appears on the floor (even if you shift+M2, you can't find anything).

**Comment by Farquaar** [comment]
Can confirm that this happened to me as well
