### ISSUE TITLE
"fingers are too big!" spam when viewing (HoP?) console

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#72153]
Computer console will spam the "fingers are too big!" message over and over if I have UI open and wear insulated gloves.

![dreamseeker_9VnNJ7huef](https://user-images.githubusercontent.com/1077971/209012971-2b27b93c-8a7c-472e-996f-9b9c79f83bb2.gif)

## Round ID: 
Round ID: [196732](https://scrubby.melonmesa.com/round/196732)

## Testmerges:

Seems none

## Reproduction:

* Open HoP console
* Put on insulated gloves

**Comment by Serxule** [comment]
its not a bug, any computer console/tablet isnt able to be used if you have insuls on

**Comment by Mothblocks** [comment]
this means some nincompoop made a should-be-pure function impure again

**Comment by ShizCalev** [comment]
insuls make your fingers thick. not a bug.

**Comment by Inari-Whitebear** [comment]
> insuls make your fingers chunky. not a bug.

The bug was that it kept spamming the balloon message while you were just standing next ot the console, doing nothing other than having the UI open. Will have to test it again to see if it still happens, but was definitely a bug

**Comment by Mothblocks** [comment]
UIs proccing an alert every ui_data is definitely a bug

**Comment by Inari-Whitebear** [comment]
Needs to be unclosed still :D

And yeah, still happens to me on master:




https://user-images.githubusercontent.com/1077971/212318712-3c538842-7574-432e-b1ab-d9497b747337.mp4
