### ISSUE TITLE
Husks don't show as husks

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#72159]
Reporting client version: 514.1585

## Round ID:
[196753](https://scrubby.melonmesa.com/round/196753)

## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/209033509-49cf4e95-d54c-44a6-ae3f-ebd78f9c8e59.png)
![image](https://user-images.githubusercontent.com/51863163/209033526-02eebe6a-d982-4319-8ee2-1d02410cdf7d.png)
![image](https://user-images.githubusercontent.com/51863163/209033534-b0035d36-8faf-4596-b0fd-06d2e8b0ac9a.png)

**Comment by ChungusGamer666** [comment]
I fear i inadvertently broke husks while trying to make them actually render their legs properly...
