### ISSUE TITLE
Santa's Hat hides/removes all hair on the head, including the beard

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#72163]
Reporting client version: 514.1588

## Round ID:
[196758](https://scrubby.melonmesa.com/round/196758)

## Testmerges:
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)

## Reproduction:

Santa arrives on station to spread joy and merriment. Santa lacks a beard. Shame. Santa removes hat, viola, suddenly there it is, Santa's beard, as well as the hair that you didn't realize was missing. Put on a santa hat as a non-santa, beard and hair gone, remove and it returns.

**Comment by Wayland-Smithy** [comment]
Duplicate. You were first but #72181 ended up with more traction srry <3
