### ISSUE TITLE
Cyborg multitool still cannot check power in cables 

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#72174]
## Reproduction:
#71266 closed for some reason, it's still happening, just tested it on live server now.
Take out your trusty cyborg multitool as a little engi borg.
Try to see amount of power in a powernet, nothing happens on click.
Clicking cables, multi-z hubs, or cable layer hubs does not show power in powernet.

**Comment by ShizCalev** [comment]
Can you make a video of it happening? Still unable to reproduce on master

**Comment by ShizCalev** [comment]
Unable to repo. There's nothing code wise that would make it act different.
