### ISSUE TITLE
Thunderdome atmos is ... broken

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#72170]
Reporting client version: 514.1589

## Round ID:
[196763](https://scrubby.melonmesa.com/round/196763)

## Testmerges:
- [holopara qol update](https://www.github.com/tgstation/tgstation/pull/72042)
- [[READY] DRAMATIC SHUTTLES!! You can now fly around the shuttle](https://www.github.com/tgstation/tgstation/pull/71906)

## Reproduction:

Spawn in the thunderdome
Enter build mode and right click a hole into space.
The hole to space, and the 4 cardinally adjacent tiles, will be vented of gas.
The rest of thunderdome will be "fine"

![image](https://user-images.githubusercontent.com/3789327/209068143-d877fa35-2ddd-4d42-9f29-78fbf5ec2861.png)

(Doesn't matter if you build mode, thermite, or RCD the hole, behaviour is the same)

**Comment by LemonInTheDark** [comment]
gggggggggggggg
