### ISSUE TITLE
Icebox shield sat station goal uncompletable?

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#72180]
Icebox can get the shield sat goal, but trying to put up a satellite, it says that it can only be deployed in space. Icebox does not have space as far as I'm aware?

## Round ID:
[Round ID]: [196775](https://scrubby.melonmesa.com/round/196775)

## Testmerges:

#72042 

## Reproduction:

* Spawn on icebox
* Shield sat goal
* Order satellite
* Unbox it
* Try to put it up outside the station

**Comment by Jacquerel** [comment]
One could argue that there's not much point setting up meteor satellites on a station which cannot experience meteors, this should probably just be disabled on planetary maps.

**Comment by distributivgesetz** [comment]
Fixed in #79224
