### ISSUE TITLE
Mobs made invisible by Invisimin can be seen by anyone on HUDs

### ISSUE THREAD

**Issue by plapatin** [tgstation/tgstation#72198]
Reporting client version: 514.1589

## Round ID:
[196815](https://scrubby.melonmesa.com/round/196815), though the issue has been around for months at this point.

## Reproduction:
-Spawn yourself in.
-Press F8.
-Get someone else to put on medhuds/sechuds/etc.
-Marvel in how visible you are.

**Comment by lessthnthree** [comment]
Yeah it's still been around for months. Try to invisimin and sneakily fix some issue and they see your HUD icon lol.
