### ISSUE TITLE
Despite attempts to keep the hulk down, hulks can become immune to cold. They're not actually that vulnerable at all.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#72197]
https://github.com/tgstation/tgstation/pull/56131 The relevant PR. In it, apparently, hulks are _meant_ to be incapable of resisting cold effects. It is their apparent 'weakness'.

Unfortunately, nothing stops them from getting temperature adaptation (which is just one half of the old space adaptation that mattered for hulks), so they are actually just immune to cold while they have that mutation. According to the comments, this is not supposed to be the case. And, in fact, I would argue that most likely hulks can benefit from all standard methods of directly altering their temperature, so a modsuited hulk is probably just as immune.

I'm pretty confident, looking at the code, that the only thing that this does is make hulks take more damage from being cold. and that means the hulk needs to actually achieve freezing temperatures in order to reach the point that this change is relevant.

Unlike lizards, who cannot readjust their temperature back to core levels, hulks do not have this and simply use their standard physiology for temperature adjustment. Humans, currently, are pretty damn good at remaining at room temperature.

End result: Hulks are actually pretty okay in cold temperatures up until they start taking damage from the cold, which probably takes a good while. Oops.

## Reproduction:

Just shoot a hulk with temperature adapt with a tempt gun. Behold, as they do not freeze to death, as advertised. Cry, because people will continue to ignore the temp gun despite all of its apparent value.

**Comment by Xander3359** [comment]
What? Temperature adaptaion makes you immune to cold. This is not a bug.

**Comment by necromanceranne** [comment]
Actually
![floyd may not have done this](https://user-images.githubusercontent.com/40847847/216620951-c1a63ab7-6ac1-44c0-b252-c0aa5ef75cc9.png)


But I won't object.
