### ISSUE TITLE
Having an AI installed in your modsuit doesnt count for the steal AI objective.

### ISSUE THREAD

**Issue by Gristlebee** [tgstation/tgstation#72205]
Reporting client version: 514.1589

## Round ID:

196828

## Reproduction:
Be antagonist with a steal AI objective.
Install AI via intellicard into your modsuit.
Wear it to roundend.
Have it not count.

Probably more of an oversight than an actual bug tbh.

**Comment by Wayland-Smithy** [comment]
Most definitely an oversight, and on a possibly related note I also have personally experienced having my laws reset (even 0th traitor) as AI when ejected from a modsuit.

**Comment by ShizCalev** [comment]
the obj itself is looking explicitly for AI cards. don't think the obj system has support for multiple target items yet.
https://github.com/tgstation/tgstation/blob/1ffdc2b146777006aca013b22a79ca1ca995d878/code/game/gamemodes/objective_items.dm#L277-L286
https://github.com/tgstation/tgstation/blob/db87e154c9283426d0597c33ccfa65163ed2a1c8/code/modules/mod/mod_ai.dm#L57-L65
