### ISSUE TITLE
Battlecruiser ships can't leave

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#72204]
Reporting client version: 514.1589

## Round ID:
[196821](https://scrubby.melonmesa.com/round/196821)

## Reproduction:
For some reason in this round neither of the battlecruiser ships could travel to the station in any way, the navigation console wouldn't target the station zlevel and the shuttle consoles would remain locked

**Comment by Jacquerel** [comment]
I've experienced this issue on other rounds but usually on Tramstation, might be related to that map specifically.

**Comment by DaydreamIQ** [comment]
Yeah this happened on Tram so that might be it
