### ISSUE TITLE
Inserting a [ into a circuit component menu searchbar blue screens it

### ISSUE THREAD

**Issue by NamelessFairy** [tgstation/tgstation#72211]
## Testmerges:
#72042
#71906

## Reproduction:
Make a circuit, open the components menu of that circuit, type "[" into the search bar.

**Comment by Mothblocks** [comment]
can you post the error message

**Comment by NamelessFairy** [comment]
> can you post the error message

![image](https://user-images.githubusercontent.com/40036527/209843287-9fb1e218-1def-4dda-914f-63a8760adff6.png)
