### ISSUE TITLE
Circuit NTNET Transmitter. Nothing can be connected to "Data Package"

### ISSUE THREAD

**Issue by TheLeopold** [tgstation/tgstation#72212]
## Reproduction:
install NTNET Transmitter into circuit
try to connect anything to Data Package

P.S. Correction: NTNET Receiver's 'Data Package' can be connected. Not like it helps tho...

**Comment by Elli-Skala** [comment]
I haven't had this issue are you sure you're using lists? 
(Honestly should be a blank element though to send non lists)
