### ISSUE TITLE
Plasmamen get their liver (reagent processing crystal) severely damaged from intaking liquid plasma

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#72229]
Little known fact: plasmamen can remove wounds with plasma.
```
/datum/species/plasmaman/handle_chemicals(datum/reagent/chem, mob/living/carbon/human/H, delta_time, times_fired)
    . = ..()
    if(istype(chem, /datum/reagent/toxin/plasma))
        H.reagents.remove_reagent(chem.type, chem.metabolization_rate * delta_time)
        for(var/i in H.all_wounds)
            var/datum/wound/iter_wound = i
            iter_wound.on_xadone(4 * REAGENTS_EFFECT_MULTIPLIER * delta_time) *// plasmamen use plasma to reform their bones or whatever*
        return TRUE
```
...however, since some time ago, this is now severely damaging to their liver, with about 20-something units of it shutting it down completely.
Even with less generous dosing, this can leave persistant messages of discomfort, etc.

## Reproduction:
Grind plasma sheets. 1 sheet = 20u. Inject it, turn it into a patch, or even eat it, I'm not your mom.

**Comment by timothymtorres** [comment]
Somewhat related to #61424
