### ISSUE TITLE
Traitor hijacks cause noticeable lag when successful

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#72233]
## Reproduction:
Probably from the lazyloading PR; the shuttle ride tends to get extended when a traitor hijacks the shuttle and attempts to land at the syndie base.

**Comment by Serxule** [comment]
yeahhh having any big area (especially with lots of objects) load in while the games going is gonna kill serb

**Comment by Mothblocks** [comment]
Might be fixed by #72244
