### ISSUE TITLE
you cant build turbines vertically

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#72235]
## Round ID:
[196952](https://scrubby.melonmesa.com/round/196952)

## Reproduction:
try building a vertical turbine
![image](https://user-images.githubusercontent.com/61211748/209456212-69b54bdb-65ad-47db-987e-82ec6684537e.png)

**Comment by SyncIt21** [comment]
Yes you can actually.

The balloon alert is misleading but if you rotate the core roter the other way around it works

https://github.com/tgstation/tgstation/assets/110812394/925cb075-6057-43f5-a0e6-6d5d493e0d89

If someone were to make a PR abut this it would be a qol PR telling what part goes where so it's not that interesting.

@Sealed101 close issue

**Comment by SyncIt21** [comment]
Ah what the heck might as well make life easier in a new PR, never mind don't close PR

**Comment by Sealed101** [comment]
it's still unintuitive and should be cleaned up
