### ISSUE TITLE
cannot view station waste or distrobution loop

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#72243]
## Round ID:
[196988](https://scrubby.melonmesa.com/round/196988)

## Reproduction:
![image](https://user-images.githubusercontent.com/61211748/209478412-83013320-620e-4fc5-b78c-e9af50c51b98.png)
try to use the monitoring console

**Comment by san7890** [comment]
is it like this on other maps? just wondering if it's more prominent than just meta(?)

**Comment by SyncIt21** [comment]
Same problem with waste distribution as well. And yes it happens on all maps
