### ISSUE TITLE
Being on a hijacked shuttle doesn't count as escaping 

### ISSUE THREAD

**Issue by Miceworld2** [tgstation/tgstation#72240]
## Reproduction: 
Be on a shuttle that gets hijacked, round end report shows that nobody escaped.
[Escape Stats](https://imgur.com/a/ykggkd4)
Also be a traitor on the shuttle, get redtext even after doing your objectives and surviving. (Even if YOU hijacked the shuttle.)
[Red Text](https://imgur.com/a/PNnjk70)
[Red Text when I Hijacked](https://imgur.com/a/fYgSOXl)

The shuttle also takes a really long time to dock after being hijacked, could be related?

**Comment by improvedname** [comment]
i think this is intended how haijcks work pherhaps everyone in the syndie faction needs a soecial check
