### ISSUE TITLE
Lazy Loaded Abductor Ships Improper Cordoning

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#72305]
## Reproduction:

This is how the Abductor Ships are in StrongDMM:

![image](https://user-images.githubusercontent.com/34697715/209736281-bc68a0e6-cda4-48d2-93f0-1afa9c639257.png)

This means they act like this in game (i'm adminned):

![image](https://user-images.githubusercontent.com/34697715/209736258-a5bdda66-2ab8-4fea-bd5d-2a2bfd0ae47c.png)

That means that the cordonning acting as an "external" border between the different shuttles and ships and whatnot on the Transit Z-Level are not useful, as you can clearly see the boundary of the abductor ships from the outside looking right at it. I believe @ZephyrTFA was saying something about how you couldn't really expand the boundary of the template(?), but something about it should really change given the fact that we don't even properly leverage cordoning for the external encapsulation of all of the abductor ships.

**Comment by ZephyrTFA** [comment]
i misspoke, i meant that if you change the template size you need to remember to update the datum vars to match or it'll complain

**Comment by ZephyrTFA** [comment]
Also, i plan on having templates automatically border themselves with cordon, so it doesn't need a remap
