### ISSUE TITLE
Bots Immediatelly dinsegage patrol after starting it.

### ISSUE THREAD

**Issue by DATA-xPUNGED** [tgstation/tgstation#72302]
## Round ID:
197130
194142

## Reproduction:

- Build Cleanbots
- Set them to go on a patrol, be it through the PDA app or directly
- They will immediatelly stop a patrol

**Comment by ShizCalev** [comment]
#70623 @LemonInTheDark  ?
```
[07:09:58] Runtime in bot.dm, line 1068: filter argument vars notÓ½•ÅsÉŒ0
proc name: set path (/mob/living/simple_animal/bot/proc/set_path)
src: Officer Beepsky (/mob/living/simple_animal/bot/secbot/beepsky/officer)
src.loc: the floor (136,191,2) (/turf/open/floor/iron/dark/corner)
call stack:
Officer Beepsky (/mob/living/simple_animal/bot/secbot/beepsky/officer): set path(/list (/list))
Officer Beepsky (/mob/living/simple_animal/bot/secbot/beepsky/officer): calc path(null)
Officer Beepsky (/mob/living/simple_animal/bot/secbot/beepsky/officer): target patrol()
world: ImmediateInvokeAsync(Officer Beepsky (/mob/living/simple_animal/bot/secbot/beepsky/officer), /mob/living/simple_animal/bot/... (/mob/living/simple_animal/bot/proc/target_patrol))
```

`Exception has occurred: Cannot modify null.dir.`

https://github.com/tgstation/tgstation/blob/3900336835d65651fdb15960b5f90e31351175fd/code/modules/mob/living/simple_animal/bot/bot.dm#L1067-L1068

**Comment by LemonInTheDark** [comment]
what the christ

**Comment by DATA-xPUNGED** [comment]
I haven't seen this issue in-game for months now, i think it might have been fixed

**Comment by DATA-xPUNGED** [comment]
As i said on that comment, still haven't seen this bug around anymore, marking it fixed
