### ISSUE TITLE
Ghost chemical scan formatting issue

### ISSUE THREAD

**Issue by Rhials** [tgstation/tgstation#72311]
## Reproduction:

Look at someone with no reagents in their body

toggle ghost chem scan and scan them

![image](https://user-images.githubusercontent.com/28870487/209738763-a8d5eb9b-cb01-4efc-89d9-6eb5ae9ce538.png)

The blood message properly changes when there are no reagents in their system, however the stomach message remains the same as if there were reagents present.

**Comment by fishingsman** [comment]
Probably due to nutriment
