### ISSUE TITLE
(Cult) HUD Icons Overlap If Moved (New Spells).

### ISSUE THREAD

**Issue by tgsAvylaar** [tgstation/tgstation#72312]
## Round ID: [197122](https://scrubby.melonmesa.com/round/197122)

Video example:
Eg. Edit: Happens numerous times in (https://youtu.be/WX7mcwvzQcY)
Vid is currently reprocessing, to be uploaded into 2 parts, so if the video suddenly cuts off at 36m then you know I'll reupload it later.

## Reproduction:
I think that if you move the HUD icons, they stay moved, and as you can see in the 1st example (this happens continuously throughout the shift, by the way), all new spells overlap the same one old one. 
Falling asleep here, can elaborate tomorrow, but it's pretty evident.
![image](https://user-images.githubusercontent.com/63151598/209745008-4dc4015b-e0a3-4c4f-a8c6-2725bbf518ff.png)

**Comment by Sealed101** [comment]
fixed in #73914
