### ISSUE TITLE
Lobstrosities don't do the wind up tell as part of their charge.

### ISSUE THREAD

**Issue by Gristlebee** [tgstation/tgstation#72321]
## Reproduction:
Find a lobstrosity on lavaland or icebox.
Wait for it to charge.
It just stands still doesn't do the shake as a tell.

They've lost this behavior for a while now, and I honestly thought I was misremembering them doing this until I found the original PR https://github.com/tgstation/tgstation/pull/52692

**Comment by Sealed101** [comment]
`Shake()` is globally broken and the windup also makes use of that proc
