### ISSUE TITLE
Newscasters Fail To Display Photos For A Absurd Amount Of Time

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#72329]
Reporting client version: 514.1589

## Round ID:
[197179](https://scrubby.melonmesa.com/round/197179)

## Testmerges:
- [[NEW GHOST ANTAG] The Paradox Clone](https://www.github.com/tgstation/tgstation/pull/71141)
- [Refactor air alarm TLV and modes.](https://www.github.com/tgstation/tgstation/pull/72315)

## Reproduction:
Attach a photo to newscaster. Post story.
Photo doesn't show up, replaced with this:
![image](https://user-images.githubusercontent.com/50649185/209842772-425cbe12-f607-41a0-a65a-9c3a0ea45441.png)

Leaving the newscaster and coming back doesn't fix this. However, waiting around for a while (In my case, ~30 minutes? I think?) allows the photo to embed properly.

Possibly related to #70140?

**Comment by timothymtorres** [comment]
It should display the photo after you send a 2nd message and recheck the newscaster.  The code for the UI probably needs to be refreshed after each message.

**Comment by itsmeow** [comment]
We fixed this on Bee by sending newcaster photos to all clients' cache when they are posted, which is messy but works

**Comment by itsmeow** [comment]
It might be possible to write a custom asset loading for newscasters - as currently it's just sending them using browse_rsc which has no guarantee of arriving at the client before the image is rendered.

**Comment by unit0016** [comment]
This has gotten way faster as of recent (around ~5 seconds to 30) and I consider it that sane enough to close this.
