### ISSUE TITLE
Lazy loading glitches out indestructible windows sometimes, causing the (presumably viscontent) grille to layer itself over the window

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#72325]
Reporting client version: 514.1585

## Round ID:
[197162](https://scrubby.melonmesa.com/round/197162)

## Testmerges:
- [[NEW GHOST ANTAG] The Paradox Clone](https://www.github.com/tgstation/tgstation/pull/71141)
- [Refactor air alarm TLV and modes.](https://www.github.com/tgstation/tgstation/pull/72315)

## Reproduction:

1. lazyload nukie base
2. what the fuck
<img width="135" alt="image" src="https://user-images.githubusercontent.com/80979251/209807335-dfd58771-7d3f-49a7-aca7-f00333a421a5.png">

**Comment by ZephyrTFA** [comment]
I'll look into this

**Comment by ZephyrTFA** [comment]
So the window does actually spawn right? It's just that the grille is rendered over the window?
