### ISSUE TITLE
The esword cannot be covered in blood but the desword can

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#72338]
## Reproduction:

Energy weapons override `add_blood_DNA`, no matter how much you smack someone they will never be covered in blood

https://github.com/tgstation/tgstation/blob/585227226addcea0b29f0f831362b0a37cfc70d4/code/game/objects/items/melee/energy.dm#L70-L71

The Desword does not, even though it's the same "construction" of weapon

**Comment by timothymtorres** [comment]
Surprised this isn't a item flag.

**Comment by timothymtorres** [comment]
![dreamseeker_wtugxswIzj](https://user-images.githubusercontent.com/5195984/211229191-d51d9eff-cd53-48b7-87b0-aa0fc3d68594.png)
