### ISSUE TITLE
Elite Syndicate Hardsuit doesn't protect from the HE rocket's fire trails.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#72334]
Maybe not a bug, I am not really sure about this one, but if you step backwards after the shot from the rocket launcher, you'll get toasted in the flames.

**Comment by Sealed101** [comment]
the damage is dealt by the invisible plume projectile, and it would seem that it's intended. if not, someone could probably just override the damage for the backblast subtype and set it to 0

https://github.com/tgstation/tgstation/blob/a4c1f6298e821a6449108e19c2d31c323a7e79cd/code/datums/elements/backblast.dm#L64-L74

___

https://github.com/tgstation/tgstation/blob/a4c1f6298e821a6449108e19c2d31c323a7e79cd/code/modules/projectiles/projectile/bullets/_incendiary.dm#L25-L42

https://github.com/tgstation/tgstation/blob/a4c1f6298e821a6449108e19c2d31c323a7e79cd/code/modules/projectiles/projectile/bullets/_incendiary.dm#L51-L59
