### ISSUE TITLE
Cleanbots fail to clean dried blood

### ISSUE THREAD

**Issue by KittyNoodle** [tgstation/tgstation#72349]
## Reproduction:

1.Cleanbot
2.Summon dried blood
3.Watch as cleanbot sprays acid at the dried blood, doing nothing

**Comment by ShizCalev** [comment]
#70239 perhaps?

**Comment by SethLafuente** [comment]
Tested it seems maybe because of #70239 this bug was fixed or maybe some other change within the past 2 years.


![Image](https://github.com/tgstation/tgstation/assets/84478872/979dbfd2-1f0d-4e06-a6d1-14679480397c)
