### ISSUE TITLE
Cummerbund is a gigantic all purpose belt 

### ISSUE THREAD

**Issue by SomeoneYouProbablyKnow** [tgstation/tgstation#72357]
Yes i'm whistleblowing on storage balance but i've only been back for a few days (which is like 4 high pop rounds) and 3 HOSes had this specific item.
But i guess boxes still exist and item balance is fucked so who cares

**Comment by Serxule** [comment]
the cummerbund is supposed to be like a fannypack, what happened with it

**Comment by SomeoneYouProbablyKnow** [comment]
Can't test right now but i think it can fit a bunch of different items and has more than 3 slots. Highly doubt gamers are wearing it for style points

**Comment by Serxule** [comment]
probably needs to just be changed to a fannypack subtype or something since thats what its supposed to be afaik
