### ISSUE TITLE
chloral hydrate is extremely poisonous instead of sleepy?

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#72369]

**Comment by newfren** [comment]
it's intentional that it's poisonous, but it is weird that it's not putting people to sleep

**Comment by ShizCalev** [comment]
15u of chloral used to be straight murder mix :)

**Comment by timothymtorres** [comment]
https://github.com/tgstation/tgstation/blob/64e2d027c38b6fcbe26ab8e7453edf84bf9e971d/code/modules/reagents/chemistry/reagents/impure_reagents/impure_toxin_reagents.dm#L39-L50

This is intended.  The impure version only does toxin damage and doesn't put people to sleep.

https://github.com/tgstation/tgstation/blob/3731cb489dd5bd43c2752ecab1939326a0cf2bd6/code/modules/reagents/chemistry/reagents/toxin_reagents.dm#L456-L482
