### ISSUE TITLE
The Destabilizing Crystal Final Objective counts even if the Supermatter does not delaminate

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#72375]
Reporting client version: 514.1588

## Round ID:
[197305](https://scrubby.melonmesa.com/round/197305)

## Testmerges:
- [[Draft] Adds TTS to the game](https://www.github.com/tgstation/tgstation/pull/72300)
- [Refactor air alarm TLV and modes.](https://www.github.com/tgstation/tgstation/pull/72315)
- [afterattack now returns a flag if it's reasonable to suspect the user intends to act on an item](https://www.github.com/tgstation/tgstation/pull/72320)
- [[NEW GHOST ANTAG] The Paradox Clone](https://www.github.com/tgstation/tgstation/pull/71141)

## Reproduction: As the AI presiding over the round, I have to guess at this, but it's very likely
1. Complete Traitor objectives up to Delamination final
2. Stick the Supermatter with the crystal
3. Do not allow the Supermatter to delaminate
4. Get the greentext for your final objective regardless

**Comment by Profakos** [comment]
You actually get greentext for just beginning any final objectives at the moment.

**Comment by Jacquerel** [comment]
In fact this is how Final Objectives (all of them) have always worked.
None of them track any progress, AFAIK this is intended behaviour and ni5 a bug.
