### ISSUE TITLE
Explosive implants call bad explosive args

### ISSUE THREAD

**Issue by jlsnow301** [tgstation/tgstation#72377]
## Round ID:
Current

## Testmerges:
Any

## Reproduction:
/obj/item/implant/explosive has explosion radius vars as floats when they should be integers. 

```	
// Explosive implant action is always available.
	var/weak = 2
	var/medium = 0.8
	var/heavy = 0.4
```
How does one blow up .4 of a tile? BYOND rounds these numbers down.

These should be changed to int  + documented. And the file, if you're a bad enough dude, should be refactored to fit [contribution guidelines](https://github.com/tgstation/tgstation/blob/master/.github/guides/STYLE.md).

**Comment by Sealed101** [comment]
i wonder if this was intetional so if one would stack multiple explosive implants in one spaceman and blow said spaceman up, it would add up all of the implants to get a large boom - but not large enough for it to be cheaper than buying a bomb implant
