### ISSUE TITLE
New pods have smoothing issues

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#72383]
Reporting client version: 514.1589

## Round ID:
[197324](https://scrubby.melonmesa.com/round/197324)

## Testmerges:
- [Refactor air alarm TLV and modes.](https://www.github.com/tgstation/tgstation/pull/72315)
- [[NEW GHOST ANTAG] The Paradox Clone](https://www.github.com/tgstation/tgstation/pull/71141)
- [[Draft] Adds TTS to the game](https://www.github.com/tgstation/tgstation/pull/72300)

## Reproduction: Load cramped/luxury pods and see if any have smoothing issues like this:
![image](https://user-images.githubusercontent.com/54517726/210116956-c1eb2bb9-71f1-4387-99bc-be0dbb08ef5b.png)

**Comment by Baskett55** [comment]
this added the pods : #72076

**Comment by Inari-Whitebear** [comment]
Isn't that pod also slightly weird? You can see plating there on the bottom right corner of it, but not the top right. But if you delete the top right wall, plating appears where it was.
