### ISSUE TITLE
Infinite free nuggets

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#72385]
Reporting client version: 514.1589

## Round ID:
[197329](https://scrubby.melonmesa.com/round/197329)

## Testmerges:
- [[NEW GHOST ANTAG] The Paradox Clone](https://www.github.com/tgstation/tgstation/pull/71141)

## Reproduction:

Spawn one /obj/item/stack/sheet/cardboard, or just dismantle a random box.
Go into the crafting menu thing (not use the box in hand, more this) 
![image](https://user-images.githubusercontent.com/3789327/210120006-ddefb428-6aea-4a69-815b-4a7079854e06.png)
Craft a nugget box
Obtain 6 pieces of delicious free chicken!

(Edit: Might want to overview other box producing recipes given i guess there was a recent overhaul here with the UI)

**Comment by the-orange-cow** [comment]
Chefs seething

**Comment by ZephyrTFA** [comment]
Hilarious

**Comment by Thunder12345** [comment]
Addendum: once the meal is finished, break the box down and do it again

**Comment by Profakos** [comment]
Addendum: StackCrafting still works as intended, because using a stack of items, if it detects that a storage box has been created, deletes the contents of the box.

**Comment by Addust** [comment]
It works with everything. Prayer will not save you.
