### ISSUE TITLE
Layer 2/4 heat pipe positioning incorrect

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#72394]
Putting heat pipes on layer 2 or 4 doesn't align properly.

This is how it should look (layer 3):
![image](https://user-images.githubusercontent.com/1077971/210150672-471f3f67-ad17-4ee6-a39b-99020520e1ff.png)

This is how it does look for layer 2:
![image](https://user-images.githubusercontent.com/1077971/210150689-ba0e5f58-66a6-4b1b-a8e3-416ed098a7c2.png)

And for layer 4:
![image](https://user-images.githubusercontent.com/1077971/210150697-a8e4f785-2375-4e5e-999f-2482f009de12.png)

## Reproduction:

Place heat pipes on layer 2 or 4

**Comment by LemonInTheDark** [comment]
This makes me so fucking sad man IT WORKED BEFORE
