### ISSUE TITLE
Motorized Wheelchair unbuckleable for some raisin

### ISSUE THREAD

**Issue by Vanadiom** [tgstation/tgstation#72398]
## Testmerges:
#71141 

### 1. Get a motorized wheelchair, in my case:  
 * 2 pico manipulators
 * 1 advanced capacitor
 * 1 super-capacity powercell

### 4. Find yourself and anyone else unable to buckle to the chair, as if someone was already sitting in it or something
The chair essentially becomes absolutely unusable, until disassembled with a wrench.
Taking the battery out and putting it back in does not help.

**Comment by newfren** [comment]
I believe it's the slipping that buggers up the chair

**Comment by timothymtorres** [comment]
Duplicate of #67841
