### ISSUE TITLE
UO45 research has no grav

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#72400]
Reporting client version: 514.1585

## Round ID:
[197386](https://scrubby.melonmesa.com/round/197386)

## Testmerges:
- [[NEW GHOST ANTAG] The Paradox Clone](https://www.github.com/tgstation/tgstation/pull/71141)

## Reproduction:

1. go to UO45 research
2. tide wall
3. why no grav

**Comment by Serxule** [comment]
what is uo45 research

**Comment by Addust** [comment]
its an away mission area (Underground Outpost 45)

**Comment by ArthuroPep** [comment]
Looking at the areas, all of them have gravity set to 1, so no idea what is doing this
