### ISSUE TITLE
Lazarus injector does not work on basic mobs (only simple mobs)

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#72404]
Reporting client version: 514.1589

## Round ID:
[197401](https://scrubby.melonmesa.com/round/197401)

## Testmerges:
- [[NEW GHOST ANTAG] The Paradox Clone](https://www.github.com/tgstation/tgstation/pull/71141)

## Reproduction:

Spawn a /mobn/living/basic/mothroach
Beat it to death (sad)
Spawn a /obj/item/lazarus_injector
Try use it on the dead mothroach
Receive error
```
The lazarus injector is only effective on lesser beings.
```

I guess this was never updated for basic mobs, which more and more things are becoming.

**Comment by Likteer** [comment]
Lazarus and strange reagent also do not work on mice/rats, and bees due to spaghetti code considering their corpses as food/trash.
The only advantage of them being the way they are, appears to be special descriptions upon death (?)

**Comment by Serxule** [comment]
> Lazarus and strange reagent also do not work on mice/rats, and bees due to spaghetti code considering their corpses as food/trash. The only advantage of them being the way they are, appears to be special descriptions upon death (?)

afaik they're trash as they're able to be grabbed and eaten, unlike other dead simplemobs (or basic mobs)

**Comment by Likteer** [comment]
> afaik they're trash as they're able to be grabbed and eaten, unlike other dead simplemobs (or basic mobs)

@Serxule Wdym, moths can eat Ian and he's revivable by either!

Except that an undead corgi army is not as functional as bees or rats and that is why I'm complaining.

**Comment by Profakos** [comment]
Moths can no longer eat picked up Ians though, alas.

**Comment by Jacquerel** [comment]
I've looked at this twice and I think the basic reason nobody has made the Lazarus Injector work with basic mobs yet is that it can't, the way their AI works is too variable to have the EMPed effect of the Laz Injector work the same way on them as it does on Simple Mobs
But also it doesn't make sense to expect players to know the difference
I will try a PR which just changes how the Laz Injector works in order to rectify this

**Comment by Serxule** [comment]
> > afaik they're trash as they're able to be grabbed and eaten, unlike other dead simplemobs (or basic mobs)
> 
> @Serxule Wdym, moths can eat Ian and he's revivable by either!

moths eating ian was a bug (but im assuming this is a joke)
