### ISSUE TITLE
Paradox clones of clowns dont copy the clown name and instead a random clown name.

### ISSUE THREAD

**Issue by rageguy505** [tgstation/tgstation#72437]
Reporting client version: 514.1589

## Round ID:
[197528](https://scrubby.melonmesa.com/round/197528)

## Testmerges:
- [[NEW GHOST ANTAG] The Paradox Clone](https://www.github.com/tgstation/tgstation/pull/71141)
- [[Draft] Adds TTS to the game](https://www.github.com/tgstation/tgstation/pull/72300)

## Reproduction:
Have a clown on station, pick paradox clone, if the clone picks the clown as the target you'll have the same appearance but a different name.

**Comment by Baskett55** [comment]
Also i feel like it'd be safe to assume the same for mimes but i didnt test it. Also i tested and reproduced this.
