### ISSUE TITLE
You cannot delimb xenomorphs with a plasma cutter

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#72446]
![obraz](https://user-images.githubusercontent.com/68878861/210416140-053c8229-9931-4fb1-b032-9ce9b16e2038.png)
FALSE ADVERTISING

## Reproduction:
(player-controlled, not simplemob enemy kind)
![obraz](https://user-images.githubusercontent.com/68878861/210419454-eeaff3b9-7254-40ee-aca6-71d174dcd8c9.png)
Plasma projectiles correctly hit specific limbs.
![obraz](https://user-images.githubusercontent.com/68878861/210419626-9c006d74-3b21-4b97-bcb6-5c43e0943396.png)
Repeat until the creature dies.
LiarGG dies from boredom in the corner.

**Comment by timothymtorres** [comment]
I've never seen xenos have their arms or legs cutoff.

**Comment by Serxule** [comment]
xenos cant be delimbed

**Comment by private-tristan** [comment]
This is just msant as a reference to dead space

**Comment by Ryusenshu** [comment]
We had destriptions changed over things like this before

**Comment by ZephyrTFA** [comment]
This isn't a bug but a reference, but you can probably get a PR removing it from the description merged.
