### ISSUE TITLE
Buildmode's reload block mapgen no longer works

### ISSUE THREAD

**Issue by Pepsilawn** [tgstation/tgstation#72469]
## Round ID: 
Tested locally on latest TG code, hard to do on live since it requires admin perms.

## Reproduction:

Started happening 2-3 months ago.
Toggle buildmode, go to mapgen and select either reload block options, be it Mass Delete or Mass Delete - In Place.
Select an area, area gets cleaned as intended.
Doesn't actually rebuild after, doesn't hang but actually seems to stop early as it doesn't give the **"You are already reloading an area! Please wait for it to fully finish loading before trying to load another!**" warning if you try to rebuild a new selection.
Few runtimes relating to bad indexes and indexes out of bound, not sure it's 100% related to buildmode.
Trying to rebuild a non-station map, like CentCom won't rebuild but will stay hanging, will prompt you the before mentioned error message as was old behaviour, the early stop is exclusive to station maps it seems.

**Comment by timothymtorres** [comment]
Fixed by #75444

**Comment by JohnFulpWillard** [comment]
Reportedly wasn't fixed by linked PR

**Comment by Pepsilawn** [comment]
#78622 fixed it
