### ISSUE TITLE
Shape of rod interaction with hyperspace

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#72497]
## Round ID:
Iiiii didn't write it down in time

## Testmerges:
Irrelevant for this

## Reproduction:
![image](https://user-images.githubusercontent.com/76874615/210890300-7bace636-b5bc-40ff-877c-0a3ae8c98955.png)
Be a wizard
Rod against the flow of the hyperspace
Get pushed back, never travel the full length of the rod 
Infinite rod form until the shuttle lands!

**Comment by Serxule** [comment]
_technically_ not a bug because of how hyperspace is coded now (you slowly drift backwards if you cant move in space afaik), definitely an oversight

**Comment by moocowswag** [comment]
Rod form is based on distance and not time spent as rod?

well i guess that makes sense since otherwise it would probably be effected by td

**Comment by Serxule** [comment]
> Rod form is based on distance and not time spent as rod?


yea thats how its always been, the more you upgrade it the more tiles you can go

**Comment by Time-Green** [comment]
Legendary

**Comment by newfren** [comment]
the shuttle just happens to be stationary compared to the rod it makes perfect sense
