### ISSUE TITLE
Humans can't get wet

### ISSUE THREAD

**Issue by Bobthe28th** [tgstation/tgstation#72505]
## Round ID:
[197705](https://scrubby.melonmesa.com/round/197705)

## Testmerges:
https://github.com/tgstation/tgstation/pull/71141

## Reproduction:
Round doesn't matter, broken locally.
Splash water on someone or stand under a flowing shower and watch as your body magically repels all the water.

I'm pretty sure https://github.com/tgstation/tgstation/pull/66573 broke it as I tried this same thing a few months ago and it didn't work then.

Found this issue because I was trying to proc alkali perspiration's explosion: https://github.com/tgstation/tgstation/blob/1fcf2caa5f085d58f643e8827cbee9c98366b324/code/datums/diseases/advance/symptoms/fire.dm#L133-L135 Negative fire stacks should not be even possible anymore so this would never proc, seems like there are some inconsistencies with negative fire stacks and wet stacks that were not overlooked in the refactor. Also, I can barely find any uses of wet stacks.

There is also: https://github.com/tgstation/tgstation/blob/1fcf2caa5f085d58f643e8827cbee9c98366b324/code/modules/mob/living/carbon/human/examine.dm#L216-L217 Which I can never make show.

**Comment by Bobthe28th** [comment]
Also I don't know where to report this but I think the wiki is also wrong about alkali perspiration, napalm and chlorine trifluoride are only synthesized when the transmission threshold is met. Or I am just wrong.

**Comment by Sealed101** [comment]
seems to have been fixed in #72844, alcali can and will blow wet people up
