### ISSUE TITLE
(Intentional?) Mechs' armour is affected by armor penetration & and it doesn't feel balanced.

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#72509]
## Reproduction:

Mechs apparently care about armor penetration now, which wasn't a thing for years after they were added. Shouldn't this be.. rebalanced? Mechs in most other servers DON'T care about AP - and most mechs have lowish armor values to match (Gygax's armor is 25/20/30, lower then the security armor.)

It doesn't feel balanced because even a Durand with all 3 melee boosters still won't have enough melee armor to protect it from a critical failure roll, which happens if the incoming damage is 15 or over, because it'll take 16 damage which seems a bit.. high, and that's the toughest (bar the Savanna) mech the crew can access. A Gygax with maxed melee armor  (55% armor) will recieve 24 damage each hit.

Mechs, being made entirely of hardened steel/composites should be inherently more resistant to anti-armor weapons which are designed to _pierce body/personal armor_ like Sec's security vests - which according to lore are "Type I" rated which is probably around [NIJ I-II](https://bulletproofzone.com/blogs/bullet-proof-blog/nij-protection-levels-choose-the-right-vest-for-you) looking at it's lack of slowdown/weak armor.

The nearest IRL equivalent to a SS13 Durand is probably a [tankette ](https://en.wikipedia.org/wiki/L3/35) which according to Wiki, has around 6-14 mm armour on it, was **manufacutred in the 1935's** and according to [TankArchives](https://www.tankarchives.ca/p/demarre-calculator.html)  your average .357 round would have around 6ish (ick) mm of penetration so it /probably/ wouldn't be penetrated. After accounting for the 500+ years in material/armour advances you'd probably end up with more like 15-25 mm armor for a Durand.

OTOH, weapons like e-swords and cutlasses (Apparently, lightsabers & curved metal machetes have the exact same values because...?) shouldn't.. do anything even to the tankette. I think you'd have an annoying time trying to disable a typical civilian off-roader truck with one honestly. It also goes against other gameplay mechanics that a lightweight, edged cutting tool like a cutlass would be effective against Mechs, if weighted items like toolboxes/fireaxes get a buff vs. structures then swords, especially AP swords should receive a massive penalty against hard structures - I think you'd wind up with a broken blade if you tried to hack it against a steel target 'realistically'.

**Comment by itseasytosee** [comment]
Windows are effected by armor penetration too.

**Comment by ZephyrTFA** [comment]
consider having armor have a penetration resistance var

**Comment by itseasytosee** [comment]
Too much to juggle. Make armor penetration not apply to structures, Add a structure armor penetration var for big fuck off hammers and the like.

**Comment by ZephyrTFA** [comment]
> > consider having armor have a penetration resistance var
> 
> armor de-penetration? can we have armor de-penetration penetration as well?

when you code it

**Comment by necromanceranne** [comment]
If you can demonstrate some kind of bug, let me know. Because honestly, this seems to logically follow.
