### ISSUE TITLE
Threw a monkey at a ninja while carrying it instead of hitting the ninja it hit me

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#72500]
Reporting client version: 514.1589

## Round ID:
 [197698](https://scrubby.melonmesa.com/round/197698) 

## Testmerges:
- [[NEW GHOST ANTAG] The Paradox Clone](https://www.github.com/tgstation/tgstation/pull/71141)

## Reproduction:
throw a moneky while running sometimes it happens it will hit you

**Comment by Jacquerel** [comment]
Things you throw move in the direction you throw them, if it was behind you when you threw it then it will hit you.

**Comment by ArcaneDefence** [comment]
Fireman carrying qol was a mistake

**Comment by Sealed101** [comment]
basically a dupe of #59926

**Comment by SethLafuente** [comment]
Oh that's true gonna close
