### ISSUE TITLE
Invisible/missing vibebots ? 

### ISSUE THREAD

**Issue by LikesGreen** [tgstation/tgstation#72533]
## Reproduction:

Made a vibebot from crafting menu but apparently its invisible ? you can still inspect it with right click or see on diagnostic hud, even more if you move your robotic ID to "happy bot icon", near its health, you can unlock it and place pai, invisible vibebot pai is possible 

![invisible vibebots2](https://user-images.githubusercontent.com/116151419/211143104-a041c079-fe51-4066-9287-a4c48891ff4f.png)
![invisible vibebots](https://user-images.githubusercontent.com/116151419/211143106-d2f60277-8dc6-4ba3-849e-16c8ed1974c7.png)

**Comment by ZephyrTFA** [comment]
https://github.com/tgstation/tgstation/issues/72847
