### ISSUE TITLE
Sybil Nukie non stop

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#72531]
## Round ID:

Either admins are force doing nukies or their is a weight issue with nukies nukies for this week has rolled far to many times than normal I feel like there could possibly be a change in their weight  done by dynamic idk dynamic it just seems odd and there should be some focus put into it

## Reproduction:
Play 3 nukies round in a row then a few days later nukies twice in a row then in that same week have nukies round happen like 5 times in a single day then think why are most nukie rounds in icebox

**Comment by qbmax32** [comment]
sorry i force it every night because i love nukies so much

**Comment by Serxule** [comment]
i rarely play a round when there's nukies, just seems like coincidence

**Comment by moocowswag** [comment]
whenever there is a high impact antag like nukies or wizard or revs or cult it feels like they always happen multiple times in a row.
