### ISSUE TITLE
Produce Orders cost money even if they dont go through if they dont cost enough

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#72536]
Reporting client version: 514.1589

## Round ID:
[197781](https://scrubby.melonmesa.com/round/197781)

## Testmerges:
- [[NEW GHOST ANTAG] The Paradox Clone](https://www.github.com/tgstation/tgstation/pull/71141)
- [Allows Panic Bunker Interview Window To Be Closed](https://www.github.com/tgstation/tgstation/pull/72522)

## Reproduction:

1. Try to buy 1 flour sack (30c)
2. Console says failed but removes 30c from your card, no flour sack

**Comment by ArcaneMusic** [comment]
![image](https://user-images.githubusercontent.com/41715314/219844438-fd65619e-c719-424c-b6df-10bebff822db.png)
Failing to reproduce. Can you think of anything that would have ran into issues with the handling of credits? EG: Did you have multiple ID cards on you, anything like that? Sorry for getting to this so late, I've been trapped at work for about 2 months

**Comment by mc-oofert** [comment]
think i used express or something
