### ISSUE TITLE
SQRT_2 macro is useless

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#72534]
`SQRT_2` in maths.dm is useless because `sqrt(2)` constant folds.

**Comment by Mothblocks** [comment]
![image](https://user-images.githubusercontent.com/35135081/211146520-72b6bcb0-3e35-4873-9dd1-23889f60d98d.png)

**Comment by Mothblocks** [comment]
its even more accurate than ours

**Comment by optimumtact** [comment]
I don't really trust that it will always do this

**Comment by Mothblocks** [comment]
why not? `3 * 2` always does and its probably the same mechanism
