### ISSUE TITLE
Missing icon for fairygrass tile

### ISSUE THREAD

**Issue by Salex08** [tgstation/tgstation#72549]
![grafik](https://user-images.githubusercontent.com/33989683/211172789-fafd51ee-a441-4270-9a89-b7962cdcc2e2.png)
fairy grass tile is missing icon.

Wasnt there a merged unit test PR which tested wheter icons arnt missing any texture?

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/9f9f782329f74984128c129b6b33ceb395f4ce4f/code/game/objects/items/stacks/tiles/tile_types.dm#L120
