### ISSUE TITLE
Bluespace Light Replacer only works when clicking where the light isnt, and gives false negatives.

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#72557]
Reporting client version: 514.1589

## Round ID:
[197829](https://scrubby.melonmesa.com/round/197829)

## Testmerges:
- [[NEW GHOST ANTAG] The Paradox Clone](https://www.github.com/tgstation/tgstation/pull/71141)

## Reproduction:
Print a bluespace light replacer
Make sure it is filled with lights
Attempt to replace broken, burnt out, and missing light bulbs/tubes from varying distances
Nothing.
Attempt at melee range.
Works.

I'm 100% certain this is not me missing the lights when I click. The light replacer is definitely filled.

UPDATE: It DOES work if you click anywhere on the tile *except* where the light fixture actually is. Not very intuitive? Clicking on tiles where there is no light will give the "The bluespace light replacer's refill light blinks red." warning, regardless of actual lightbulb levels.

**Comment by SyncIt21** [comment]
This just might be a convinience feature and not a bug. Clicking on a turf will repair all lights tubes & bulbs on that turf so if you create a light tube on the wall & a light bulb on the floor and they both fall on the same turf it will fix both of them. Plus clicking on the turf is much easier than clicking on a small light fixture so although not intuitive like the RLD its definitely more efficient
