### ISSUE TITLE
Droppers broken by recent update

### ISSUE THREAD

**Issue by Ekaterina-von-Russland** [tgstation/tgstation#72589]
## Round ID: [1979075](https://scrubby.melonmesa.com/round/1979075)

If you discovered this issue from playing tgstation hosted servers:
[Round ID]: [1979075](https://scrubby.melonmesa.com/round/1979075)

## Testmerges:
[#72576: 'Orbit + traitor panel category refactor' by jlsnow301 at commit 71daa4dfe6](https://www.github.com/tgstation/tgstation/pull/72576)

## Reproduction:

Hold a dropper. Click a beaker. Instead of correctly taking 1 unit from the beaker, it will take the unit and instantly put it back in the beaker, making the dropper completely useless.
It was working fine yesterday.

**Comment by Serxule** [comment]
you have to use right click to extract (afaik), if its saying that it did extract and then put it back in, thats the bug

**Comment by timothymtorres** [comment]
Fixed by #72617
