### ISSUE TITLE
Abductors are unable to use normal batons (baton, prod, telescopic)

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#72585]
Reporting client version: 514.1589

## Round ID:
[197893](https://scrubby.melonmesa.com/round/197893)

## Testmerges:
- [[NEW GHOST ANTAG] The Paradox Clone](https://www.github.com/tgstation/tgstation/pull/71141)

## Reproduction:

I'm not sure if this is intended. But abductors have chunky fingers right? There was a change that made batons not work with chunky fingers. So say for instance an abductor loses their one precious baton, suddenly they have to resort to ghetto alternatives. But they can't!

![image](https://user-images.githubusercontent.com/33107541/211252098-cbe25383-50f9-4c64-8b3e-251d0e1a9160.png)

Seems awfully punishing, but idk.

**Comment by Sealed101** [comment]
yeah that was made a thing when batons became impossible to use with chunky fingers

**Comment by ATH1909** [comment]
gee it's almost like #71285 should have targeted TRAIT_HULK specifically instead of chunky fingers

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/5511a82149f823ab3e4eac4f6fdc8d6acf355537/code/modules/surgery/bodyparts/species_parts/misc_bodyparts.dm#L42-L52

This is intended.

**Comment by moocowswag** [comment]
Abductors were intended to have chunky fingers yes, that was before chunky fingers made you unable to use batons.
