### ISSUE TITLE
Two handed tools are always Two handed (bug of the year?)

### ISSUE THREAD

**Issue by Castone001** [tgstation/tgstation#72599]
## Round ID:

197940

## Testmerges:

#72576 
## Reproduction:

Pick up a two handed item someone mentioned the crusher not working, but I saw it with mech removal tool. Try to one hand it, cannot switch hands regardless of two handing or one handing it, says your other hand is busy. Thanks coders.

**Comment by ShizCalev** [comment]
already fixed.
