### ISSUE TITLE
the regenerative sepia crossbreed's description is inaccurate

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#72600]
/obj/item/slimecross/regenerative/sepia
	colour = "sepia"
	effect_desc = "Fully heals the target and stops time."

/obj/item/slimecross/regenerative/sepia/core_effect_before(mob/living/target, mob/user)
	to_chat(target, span_notice("You try to forget how you feel."))
	target.AddComponent(/datum/component/dejavu)

**Comment by Profakos** [comment]
Has the linked PR fixed the issue?

**Comment by Sealed101** [comment]
well yeah it displays the correct information
