### ISSUE TITLE
Item scaling doesn't work as intended when in storage/inventory

### ISSUE THREAD

**Issue by Ed640** [tgstation/tgstation#72601]
Reporting client version: 514.1585

## Reproduction:
![image](https://user-images.githubusercontent.com/16868239/211442499-f85d05b8-e281-4100-82c9-aa4394f9ac46.png)
Cards when put inside an inventory shrink as if they were out in the world when I'm certain they haven't done so before, but will still be enlarged like normal when in hand or in a pocket
![image](https://user-images.githubusercontent.com/16868239/211442951-9a521b0b-530a-436d-8421-2964f07b40a4.png)

This also applies to mail if that matters as well.

**Comment by Serxule** [comment]
this is intended, the fullsize card sprite goes over the inventory slot line so the small sprite is used when inside something + its only big inhand so you can see it when playing a card game

**Comment by Ed640** [comment]
I was hoping to be able to see the cards in a binder to easily pick through them instead of examining each tiny blob

**Comment by Ed640** [comment]
Just looking in the item_scaling element does mention it should work in storage. I'm not too sure how exactly it works.
`// Object scaled when placed in an inventory slot OR when entering a storage component.
	RegisterSignals(target, list(COMSIG_ITEM_EQUIPPED, COMSIG_ATOM_ENTERED), PROC_REF(scale_storage))`
