### ISSUE TITLE
Oldstation research broken, or I have no idea what I'm doing.

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#72608]
Reporting client version: 514.1589

## Round ID:
[197949](https://scrubby.melonmesa.com/round/197949)

## Testmerges:
- [[NEW GHOST ANTAG] The Paradox Clone](https://www.github.com/tgstation/tgstation/pull/71141)

## Reproduction:

Play old station (aka charlie station, whatever you like) quietly on (very) low pop.
Standard late night issue ; station isn't researching anything, want to get better medical tech, chem dispensers and friends.
These are now (for some time now) mandatorily locked behind Human Dissection.
I believe the way we used to make this work was to build an R&D server and multitool link it to the operating table.

This doesn't currently work however
![image](https://user-images.githubusercontent.com/3789327/211454827-00293dbe-52f3-4482-847c-7e5f089248aa.png)
"R&D Server d0b5" above, multitooled
"Stored the R&D Server d0b5's techweb information in the multitool."
Then using this multitool on the operating computer doesn't seem to help:
![image](https://user-images.githubusercontent.com/3789327/211455027-91e6df96-6580-478c-a211-2d9fcbfeb1cf.png)

I'm not sure the R&D Console really reacts to the multitool anyway, but at least its connected to something that has research and options.

**Comment by ZAMODA** [comment]
You just need a operating computer and surgery table to do dissection research, currently building extra r&d server or console does literally nothing.

**Comment by JohnFulpWillard** [comment]
Experiment handlers by default only connect to techwebs that are on the same z-level, which is the station.
It's more of an inconsistency error that servers built on other z-levels aren't part of it.

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/74123
