### ISSUE TITLE
Psyker pirates can't fly their ship

### ISSUE THREAD

**Issue by Zonespace27** [tgstation/tgstation#72605]
## Reproduction:
1. Spawn as psyker pirate
2. open nav console
3. Be unable to see shit

![image](https://user-images.githubusercontent.com/41448081/211455200-0275135c-25db-42b2-ae65-45476c6fc5d7.png)

**Comment by Fikou** [comment]
well u can fly it

**Comment by Sealed101** [comment]
- #75031 has given the psyker ship both a psyker-friendly console to dock the ship and a literal normal person with working eyes
