### ISSUE TITLE
Telecomms no longer functions like the wiki would suggest/has in the past.

### ISSUE THREAD

**Issue by Kaptinalexander** [tgstation/tgstation#72613]
Reporting client version: 514.1589

## Round ID:
[197958](https://scrubby.melonmesa.com/round/197958)

## Testmerges:
- [Orbit + traitor panel category refactor](https://www.github.com/tgstation/tgstation/pull/72576)

## Reproduction: So the wiki says that if you have a broadcaster, a bus mainframe, a processor, and a receiver, you can link them all to the bus mainframe and you should have a working Telecomms. In the past I've done this and it works, but this round it didn't.

As AI, I set it up in the picture below after a traitor had deconstructed the hub. I linked it all using the prebuilt telecomms machines that hadn't been deconstructed.

Usually in the past this has been enough to get telecomms working, even if not optimally, this time it remained offline. and I was unable to get comms working. My theory is that something borked when the hub was deconstructed and it broke everything linked to it. I wasn't able to test it however as I was an AI this round.

![image](https://user-images.githubusercontent.com/8625925/211497197-d736a074-d1ce-4a0f-8560-98ba14e8b339.png)

**Comment by Serxule** [comment]
the wiki is very outdated in many places

**Comment by Serxule** [comment]
also, are you sure this wasnt just an ionosphereic anomaly?

**Comment by Kaptinalexander** [comment]
> also, are you sure this wasnt just an ionosphereic anomaly?

Yeah, unless it managed to last for a full ten minutes, plus during anomalies I'm fairly certain the lights stop blinking on the machines don't they?, either way I started the attempt to fix it before the shuttle got called, and even after it docked I never managed to fix it.

**Comment by Serxule** [comment]
i know there is an anomaly that disables comms without changing how tcomms looks (forget what its called) but i dont really know much about tcomms otherwise, i usually just connect every machine possible and it ends up working again

**Comment by Kaptinalexander** [comment]
Yeah, on further thought, it's possible that the quantum relays need a hub right? or have to be relinked in someway, that I don't know about.
(The machine right below the SMES in the picture that lets you use comms on different Z-levels)

If that's true then the comms may have been fixed for the lower level of the station but not the upper, and because the AI resides on the upper level, I wasn't able to tell that. Either way I'd have to test that to find out.

**Comment by BlueMemesauce** [comment]
that same setup works for me so I have no idea what you're doing wrong

![image](https://user-images.githubusercontent.com/47338680/213577702-4cc485a3-eb95-4d26-8090-b4275b0c0eef.png)

**Comment by BlueMemesauce** [comment]
I believe the issue is that if you have two receivers on the same frequency and only one of them is set up it wont work. Just turn off the other receiver then it will work.

**Comment by BlueMemesauce** [comment]
So this is indeed a bug. One reciever existing but not connected shouldn't fuck up the entire network.

**Comment by ZephyrTFA** [comment]
Not a bug. Tcomms is just incredibly non user friendly

**Comment by BlueMemesauce** [comment]
It literally is a bug #74786
