### ISSUE TITLE
Many actions are firing twice

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#72612]
Reporting client version: 514.1589

## Round ID:
[197954](https://scrubby.melonmesa.com/round/197954)

## Reproduction: Most actions seem to happen twice when performing them, which can lead to some pretty stupid behaviour.
I think this is a broader picture of what's gone wrong with https://github.com/tgstation/tgstation/issues/72589#issue-1525380295, but I've witnessed this behaviour personally with conveyor belts and plumbing pipes. For plumbing, you place down two pipes at a time. For conveyor belts, you place two down at a time, even if you only have one, which can lead to conveyor belt duplication.

**Comment by timothymtorres** [comment]
Fixed by #72617
