### ISSUE TITLE
beakers are double transferring reagents

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#72620]
Reporting client version: 514.1589

## Round ID:
[197967](https://scrubby.melonmesa.com/round/197967)

## Reproduction:
put 20u of something in a beaker set to 10u transfer
click another beaker
it double transfers, all liquid ends up in new beaker

the message in chat also double sends, so I'm pretty sure the action is happening twice

**Comment by Profakos** [comment]
It was very likely caused by the double afterattack issue (now fixed).

**Comment by timothymtorres** [comment]
Fixed by #72617
