### ISSUE TITLE
Abductors often spawn unlinked to their ship, resulting in non-functional recall implants and vests.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#72639]
Reporting client version: 514.1589

## Round ID:
[197998](https://scrubby.melonmesa.com/round/197998)

## Reproduction:

Unsure if this is tied to multiz maps or not, seems to happen often on icebox though.

Abductors will sometimes briefly spawn on the arrivals shuttle, then get wrapped to their UFO a second later (lazyload issue?). This seems to result in not being linked to any part of their ship, leaving the scientist's recall implant without a set home variable. This requires admin intervention to fix properly. The agent's vest also will not be linked to the console, however this can be fixed by hand through using the armor on the main UFO console. 

![dreamseeker_2diPfWakzg](https://user-images.githubusercontent.com/33107541/211715612-96d7d284-94b6-4448-931e-deeff4ac49cf.png)

**Comment by Serxule** [comment]
> Abductors will sometimes briefly spawn on the arrivals shuttle, then get wrapped to their UFO a second later (lazyload issue?)

100% a lazyloading issue, this was happening with nukies too

**Comment by ZephyrTFA** [comment]
God dammit, I'll look into it
