### ISSUE TITLE
Reverse revolver and syndicate revolver use different sprites, making it easy to tell the difference.

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#72651]
Reporting client version: 514.1589

## Round ID:
[198041](https://scrubby.melonmesa.com/round/198041)

## Reproduction:
be clown, be traitor, buy revolver, buy reverse revolver, look at different sprites.

**Comment by timothymtorres** [comment]
This is intended.  The idea to let someone knock it out of your hands and let them try to shoot you with it, thus killing themselves.

**Comment by timothymtorres** [comment]
I wasn't aware someone swapped the sprites for the revolvers. Should be a simple fix then.
