### ISSUE TITLE
Bleed Wounds Heal Automatically and Do Not Reduce Blood Level on Corpses

### ISSUE THREAD

**Issue by RandomlyEvil** [tgstation/tgstation#72668]
Reporting client version: 514.1589

## Round ID:
[198101](https://scrubby.melonmesa.com/round/198101)

## Reproduction:

(Unsure if this is intended but it feels like it...probably is not.)

Spawn in a human, a health analyzer, and a drill or pokey object of your choice.  Fill your human full of holes, making sure to rack up as many bleed wounds as possible until they die.  Health scan them to see the wounds and blood level.  Drag them around a bit, leaving a nice bloody trail everywhere, scanning them occasionally.  After anywhere from 30-60 seconds later, all wounds will disappear (seem to be related to body temp but unsure if the temp required to close wounds is intended to be in "normal corpse" range).  Also, you will note that the blood level has not changed since the point of their death, despite your glorious blood trail you've left.  (This was noticed after someone dragged a bleeding body around the station repeatedly, leaving trails...but the body stayed at 100% blood the whole time.)

![image](https://user-images.githubusercontent.com/109258931/212166528-4c540885-8978-4e12-bb43-34d8cc3dddfc.png)

![image](https://user-images.githubusercontent.com/109258931/212166586-1c7cec7b-becb-4fb4-aa1d-7a87434d9cb9.png)

![image](https://user-images.githubusercontent.com/109258931/212166640-d29acd76-447d-4094-add1-979f84204ac3.png)

**Comment by Serxule** [comment]
man doesnt know biology

**Comment by Serxule** [comment]
alright, who deleted my comment for saying this isnt a bug and is _literally_ intended

**Comment by optimumtact** [comment]
I did because you didn't actually provide any evidence and I don't need to take your word for it.

**Comment by RandomlyEvil** [comment]
I can understand some measure of "stop bleeding after death", though the continued trail of blood from the body dragging is a bit odd.  The fact that all wounds heal purely by a corpse cooling down is a bit...odd.  Seems to me that medical actually can save themselves some time by killing their patient, which effectively stops their bleeding and heals the wounds in under a minute, vs having to actually replace blood and fix wounds.

**Comment by moocowswag** [comment]
before bleed wounds were a thing dragging corpses was seen as a very bad thing, i remember being told it caused bloodloss, im wondering if this was just lost in transition from how we previously did bleeding.

**Comment by RandomlyEvil** [comment]
> The first part is definitely intended. It depends on the severity of the wound.
> 
> ```
> /datum/wound/slash/severe
> 	name = "Open Laceration"
> 	clot_rate = 0.03
> ```
> 
> ```
> /datum/wound/slash/critical
> 	name = "Weeping Avulsion"
> 	clot_rate = -0.015 // critical cuts actively get worse instead of better
> ```
> 
> Not sure about the second part.

Weeping Avulsion and Ruptured Cavity both heal as well, which is part of the concern.  And its not just they 'heal over time', they just instantly disappear once the body reaches a certain temp.  I know exposure to cold can close wounds, but I feel like the text that says "exposure to extreme cold" doesn't mean 10 degrees below body temp = full instant wound fix.

**Comment by Serxule** [comment]
while the set time/temp limit for dead wound clotting is weird, its still definitely intended, because otherwise it wouldnt be happening (see bleeding wounds when alive), although there should probably be some reworks

**Comment by Profakos** [comment]
I assume #74412 should have closed this?
