### ISSUE TITLE
Revelation is entirely broken

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#72682]
Reporting client version: 514.1589

## Round ID:
[198139](https://scrubby.melonmesa.com/round/198139)

## Reproduction:
Install revolution onto a modular console, obfuscate with a silly name. Arm. Activate.
AI is easily able to simply... open the program despite it being armed, and the system remains unbricked.
Guh?

**Comment by Jackal-boop** [comment]
None of the syndie apps work IIRC. They've been broken since they were added

**Comment by Profakos** [comment]
I have checked the cause. It only bricks if you press a button that calls the PRG_activate ui_act. There is no such button.
Should be hooked up to `on_start()`.

**Comment by Profakos** [comment]
Caused by #70678 removing hard drives without replacing the effect.
