### ISSUE TITLE
GCd_at_time reports as unused on 515

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#72681]
https://github.com/tgstation/tgstation/blob/4d6eadabadec42779771aa8fb544df4841fc00e3/code/controllers/subsystem/garbage.dm#L176-L189

This is reported as an unused variable because `IS_DELETED` does not use `GCd_at_time` in 515. Could save this for free by doing something like:

```dm
#define SUPPRESS_UNUSED(name) if (UNLINT(FALSE)) { pass(name) }
```

**Comment by LemonInTheDark** [comment]
Warnings should error in ci, that's the real trouble here

**Comment by Mothblocks** [comment]
Agree, I think it's only not because alternate tests might be a bit odd? Wouldn't be surprised if not though

**Comment by Mothblocks** [comment]
https://github.com/tgstation/tgstation/pull/61025/files

**Comment by Mothblocks** [comment]
i think we dont set this on linux (aka ci)

**Comment by LemonInTheDark** [comment]
depression
