### ISSUE TITLE
Machine-scanning experiments are broken

### ISSUE THREAD

**Issue by TheSmallBlue** [tgstation/tgstation#72694]
## Testmerges:
#72661 

## Reproduction:

* Grab an experiment scanner
* Click on one of the stock-part replacement experiments
* Go to one of the listed machines, replace the asked component either manually via deconstruction or via an RPED, bluespace or otherwise.
* Try to scan the machine
* Notice how it fails, even though you did everything right

Also, where the part name should be in the experiment description, it only says "adv"

According to melbert this is most likely caused by the recently merged #72559 Stock part datumization PR

**Comment by jlsnow301** [comment]
@SyncIt21 whats your thoughts on this

**Comment by Sealed101** [comment]
yeah that PR did an oopsie and changed the requirements for the experiments for no apparent reason. reverting the reqirements from datums to objects will fix the issue

**Comment by SyncIt21** [comment]
The machine is supposed to have datum stock parts that shouldn't be touched but the scanner is still looking for old obj stock parts and not the new datum parts. I'll look into it

**Comment by SyncIt21** [comment]
Never mind I did accidentally replace Requirements with datum parts even though the scanning experiments converted them back to obj parts before testing them.
I'll combine this with renaming tier2 and higher datum parts which was  requested by mothblock's in my final PR
