### ISSUE TITLE
Trading card piles with 0 cards

### ISSUE THREAD

**Issue by blackdav123** [tgstation/tgstation#72697]
Reporting client version: 514.1589

## Round ID:
[198178](https://scrubby.melonmesa.com/round/198178)

## Testmerges:
- [Makes nerve splicing surgery reduce stamina damage](https://www.github.com/tgstation/tgstation/pull/72661)

## Reproduction:
1. Create a pile of trading cards
2. Clickdrag the pile to quickly move them into a card binder
3. Pile remains with 0 cards in it

**Comment by Mooshimi** [comment]
whats next do you want to get rid of 0 credit chips

**Comment by Mooshimi** [comment]
Dunno if this is normal because no one plays with those cards, but there's bunch on runtimes for tgc cards for that round with Forcemove etc
