### ISSUE TITLE
Chairs (and possibly other things you may get buckled to) travel Z's with you when using ladders

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#72691]
## Reproduction:

https://user-images.githubusercontent.com/75863639/212418532-9f4ca8a1-a5ff-42c1-a0a3-516f7e52b7ff.mp4

**Comment by Serxule** [comment]
probably intended (meant to be easier for wheelchairs) but probably not meant to happen with bolted buckle-ables
