### ISSUE TITLE
Trading card decks can hold an ILLEGAL number of cards

### ISSUE THREAD

**Issue by blackdav123** [tgstation/tgstation#72701]
Reporting client version: 514.1589

## Round ID:
[198181](https://scrubby.melonmesa.com/round/198181)

## Testmerges:
- [Makes nerve splicing surgery reduce stamina damage](https://www.github.com/tgstation/tgstation/pull/72661)

## Reproduction:
Trading card decks can hold 31 cards instead of 30
Putting the 31st card in gives the "only 30 cards allowed" message but still allows you to put it in

**Comment by BlueMemesauce** [comment]
Looking at the code, I don't think its an bug. 
Logically it wouldn't make sense for a stack of cards to outright refuse to accept another card. It's just letting you know that it's an illegal deck.

**Comment by davethwave** [comment]
Neat, the game itself allows you to cheat at cards by design.

**Comment by Mooshimi** [comment]
Seems you reached a decision on your own...
