### ISSUE TITLE
Uranium in protolathe image does not update according to uranium amount

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#72702]
## Reproduction:
As of right now Uranium does not update in the protolathe as other materials do when it has mora than 20 stacks
 #72652 
![image](https://user-images.githubusercontent.com/84478872/212450320-9c78af51-51bb-4fa0-a573-23094b664db9.png)

**Comment by Wallemations** [comment]
I didn't even realize these changed depending on how much there was in the machine
If that's the case, then diamonds & bananium are also going to have issues
I'll look into it when I have time
