### ISSUE TITLE
Syndicate NPCs (Commandos) can target through solid walls

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#72723]
Reporting client version: 514.1589

## Round ID:
[198236](https://scrubby.melonmesa.com/round/198236)

## Testmerges:
- [Makes nerve splicing surgery reduce stamina damage](https://www.github.com/tgstation/tgstation/pull/72661)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/212503482-ba469b74-40ca-4c6c-9b13-d678ad5bf7ac.png)

Moved back and forth along the wall, the bullet holes followed me despite there being no line of sight.

**Comment by Serxule** [comment]
there should be a PR up that fixes this exact problem (and problems it causes, like an absolute fuckload of bullet casings), i thought it was merged but maybe not

**Comment by dragomagol** [comment]
Oh yeah, the commandos do absolutely produce an absurd amount of casings. Plus they throw themselves back and flip around like they belong in the Cirque du Soleil which is brilliant but probably not intended.

**Comment by Profakos** [comment]
#72494 has been merged, so it  should be fixed by now.
