### ISSUE TITLE
Infinite Salad Glitch

### ISSUE THREAD

**Issue by ShielDeploy** [tgstation/tgstation#72729]
Round ID; https://sb.atlantaned.space/rounds/198250

Escaped-The-Rock with the Assistance of Bos the Moth Engineering managed to produce an ungodly amount of food with next to no effort.

Suppose a small animal (such as a lizard pet) is sentient or was chosen randomly to be controlled by a ghost; Gets picked up and put in the deep frier. Once "complete" (Lightly-fried to The very idea of fried goods), that animal  (provided they don't move) can be picked up as an item and put in a bowl. Spawning in a "Bowl of Lightly Fried(Or something else) XXXX Salad.

After this, the animal can freely move around once more and repeat it infinitely. Not game-breaking but for sure hilarious as even if someone picks up the bowl of salad WITH the creature still "in" the bowl, eat the whole thing. The creature will not be eaten and just roll out without a single tick of damage taken.

**Comment by ATH1909** [comment]
is there any real benefit to doing this instead of just using sheets of paper, metal rods, or other easily-spammable items

**Comment by Serxule** [comment]
being able to eat deep fried animals but them uncurling is intentional afaik and has existed for a long time, although its supposed to give very little food, i dont think its supposed to be able to be combined with other food things

**Comment by Sealed101** [comment]
practical continuation of #50524
