### ISSUE TITLE
Heretic shadow realm spawns you in space

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#72732]
Reporting client version: 514.1581

## Round ID:
[198260](https://scrubby.melonmesa.com/round/198260)

## Testmerges:
- [Makes nerve splicing surgery reduce stamina damage](https://www.github.com/tgstation/tgstation/pull/72661)

## Reproduction:

Survive shadow realm > Spawn in toxins test site
![image](https://user-images.githubusercontent.com/36066032/212532452-424b4763-d2c2-4afe-aa28-13198a5b151f.png)

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/baf1492a12e76ad070626141fcb9643658a00132/code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_knowledge.dm#L384-L389

https://github.com/tgstation/tgstation/blob/77c2b7f50c407ca6f5c9ac3d6bb8c44b49b023b4/code/__HELPERS/turfs.dm#L339-L359
