### ISSUE TITLE
Infuser no longer accepts drag-on mobs, or mobs when someone is inside it.

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#72738]
Reporting client version: 514.1589

## Round ID:
[198282](https://scrubby.melonmesa.com/round/198282)

## Reproduction:

Spawn DNA infuser
Kill a carp, drag it onto the infuser, nothing
Kill a cat, same
Kill a mouse, this you can pick up and insert, but only if there isn't someone in the infuser (this might be intended, but the other two presumably are not)

**Comment by SyncIt21** [comment]
The original author only wanted to drag human mobs into the infuser so I did just that.  Just have to tweak a small if condition to fix this
