### ISSUE TITLE
When doing prothetic surgery you stab people with tools if they are not used in current step

### ISSUE THREAD

**Issue by SuperSlayer0** [tgstation/tgstation#72755]
When you do prothetic surgeries and use such items as screwdrivers, crowbars, etc., and they aren't used in the current step(for example you don't know exact steps and randomly use tools trying to figure out which one is correct), you will just attack the person you are doing the surgery on, even if you aren't on harm intent. 

## Testmerges:

https://github.com/tgstation/tgstation/pull/72661

## Reproduction:

1. Start a surgery on a robotic bodypart
2. Try to use a tool that isn't used in the current step, with combat mode off. This will result in attacking the person with your tool.

**Comment by Zytolg** [comment]
not a bug, this has always behaved like this

**Comment by Fikou** [comment]
this is a specific flag nicety for real surgical tools, its intended to be that way. you wont get that with ghetto alternatives and whatnot

**Comment by CMDR-Gungnir** [comment]
> this is a specific flag nicety for real surgical tools, its intended to be that way. you wont get that with ghetto alternatives and whatnot

But aren't Tools the Intended Tools for prosthetic surgeries?
