### ISSUE TITLE
Hacked autolathe fails to print some ammunition items

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#72760]
Reporting client version: 514.1589

## Round ID:
[198349](https://scrubby.melonmesa.com/round/198349)

## Reproduction:

Hacked lathe seems unable to print various ammunition items, notably Ammo Box (.45, 10mm or 9mm), some other items under this category do or dont work, silently doing nothing (being unclickable?) when broken.

**Comment by Serxule** [comment]
its unable to print any contraband items iirc, had the same problem but with industrial welder

**Comment by Mey-Ha-Zah** [comment]
can confirm, same issue

**Comment by necromanceranne** [comment]
@JohnFulpWillard you might want to address this
