### ISSUE TITLE
Gene Infuser doesn't splice genes

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#72767]
Reporting client version: 514.1589

## Round ID:
198368

## Testmerges:
- [Makes nerve splicing surgery reduce stamina damage](https://www.github.com/tgstation/tgstation/pull/72661)

## Reproduction:
Try to splice yourself with DNA of a dead rat or goliath, nothing happens

**Comment by tGyro** [comment]
Yeah same experience for multiple rounds. Zero genes were spliced. Completed process the exact same as prior for when it worked. Seems to be non-funcitonal

ROUND - 198656

**Comment by Floofies** [comment]
Fixing this now, this is due to my oversight. Sorry about that
