### ISSUE TITLE
Bar dispensers and other items go invisible when ghosts orbit

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#72765]
Something seems to be making certain machines disappear when you ghost over them. I've also seen bar drinks, folders, paper bins and other small items on tables doing the same thing depending where they're placed.

![211277653-1f925143-9fb4-4112-b5bc-cac2e0b90638](https://user-images.githubusercontent.com/83487515/212798483-ec6af952-1d1e-4706-8db8-f6eaf35e6dff.gif)

## Reproduction:
Orbit machine on a table. Place items on a boundary between two tables (such as the middle of a 1x2 table)

**Comment by TheVekter** [comment]
This is probably related to #72765

**Comment by lessthnthree** [comment]
Oh this should be closed, I confirmed it's downstream.
