### ISSUE TITLE
Android species transformation bug.

### ISSUE THREAD

**Issue by ChumbleBusiness** [tgstation/tgstation#72771]
If one manages to transform their species into an android, or augmented human, they will be unable to lose those robo limbs when transforming again. This happens no matter the method of transforming. Whether by using a magic mirror, or a charged black extract, once you've turned into an augmented human / android, if you try to transform into something else, you don't lose the robo limbs, but do lose the attributes.

Like if I were to transform into an android via a magic mirror, and then try to turn back into a human, I would keep all of the robotic limbs, but wouldn't have any of the bonuses like immunity to pressure, no need to breathe, etc.

**Comment by Kapu1178** [comment]
the problem is the code doesnt know if it's a robotic limb you happened to obtain surgerically, or if its because of a transformation. Species being given robotic limbs is dumb, species changing is dumb.

**Comment by ChumbleBusiness** [comment]
Is this something that can be fixed? This has fucked me over in real rounds, and more than once.

**Comment by ChungusGamer666** [comment]
> 

making a big deal out of something simple, androids just need to use a non-exempt subtype lol
