### ISSUE TITLE
C4 is too powerful and/or has an unusually big radius?

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#72786]
RoundID 198433

so i put a c4 on a wall, and hid a couple tiles away [see in picture] and when the c4 blew, it took off two of my limbs and nearly crit me despite me being far enough away(?) and inside of a suit storage thing.

ive seen someone have c4 on their same tile detonate without them even losing any limbs or taking more than half a healthbar's damage

![image](https://user-images.githubusercontent.com/105343481/213091944-609cbbb3-e4de-4cdb-bf77-6da91fe02896.png)

example two: couple tiles away, the blast still damages and crits me
(circle is me, x is c4 placement)

![image](https://user-images.githubusercontent.com/105343481/213092055-7e6c31f2-9c72-4105-845e-fc6a9b222cfc.png)

im not sure if c4 was always supposed to be like this or i'm just coping but i thought i'd report it just incase
ive seen someone have c4 on their same tile detonate without them even losing any limbs or taking more than half a healthbar's damage

**Comment by Serxule** [comment]
just seems like you got bad rng or there's a weird diagonal thing happening

**Comment by SethLafuente** [comment]
why do c4s have rng? also I once threw a c4 with a bolas into a crew member blew it up with a signaller and it didnt even take off any limbs or damaged more than 50% whats going on with c4s?

**Comment by SkeletalElite** [comment]
Dont think this is a bug.

c4 creates a light explosion with a range of 3.

Light explosions can delimb (there's RNG) espeically if you don't have bomb armor

**Comment by TheVekter** [comment]
C4 does 1 dev, 2 heavy, and 3 light, so you were in range.
