### ISSUE TITLE
Atrocinator still doesn't work

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#72794]
## Round ID:
[198435](https://scrubby.melonmesa.com/round/198435)

## Reproduction:

Despite #71664 being merged: 

- Get an atrocinator
- Stand below openspace
- No uppies

![image](https://user-images.githubusercontent.com/51863163/213094818-211e30f7-db3a-4640-be12-cdadc18b5e36.png)

- Get bummed out, travel upstairs
- Walk over openspace, expecting to stay uppies
- Fall anyways

It doesn't even stop slips, it's pretty much entirely just a cosmetic "you are flipped now" module in its current state

**Comment by newfren** [comment]
does it still kill you when outside on icebox?

**Comment by KittyNoodle** [comment]
yes
