### ISSUE TITLE
Guest accounts have no keys bound

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#72804]
## Reproduction:

Related to #72268 . 

Load into the game as a guest account to test something. No keys are bound, including movement keys. Very annoying for testing. 

![image](https://user-images.githubusercontent.com/51863163/213277394-831d0bd3-290f-4c26-aa54-fb6e2bd715b7.png)

**Comment by Timberpoes** [comment]
It also throws up pref runtime in the process. Very annoying when debugging.

**Comment by ZephyrTFA** [comment]
I believe I already know the issue
