### ISSUE TITLE
Autolathe can't print hacked designs?

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#72806]
Reporting client version: 514.1589

## Round ID:
[198479](https://scrubby.melonmesa.com/round/198479)

## Testmerges:
- [Makes nerve splicing surgery reduce stamina damage](https://www.github.com/tgstation/tgstation/pull/72661)

## Reproduction:
Multitool pulse the hack wire three times, then cut it.
Find a hacked design (ie, industrial welding tool)
Try to click it but accidentally highlight it instead
Un-highlight it
Click it normally. Nothing.
Try other hacked designs (ie, riot foam darts) and see they also won't print.
Try non-hacked designs (ie, multitool) and see they work just fine.

The autolathe definitely had enough materials and was definitely powered. Tried mending/cutting hack wire and deconstructing the autolathe. Other players were also unable to print hacked designs, so I don't think the highlight step is necessarily relevant?

**Comment by Serxule** [comment]
https://github.com/tgstation/tgstation/issues/72760
