### ISSUE TITLE
Luxury shuttle lacks fire extinguishers

### ISSUE THREAD

**Issue by blackdav123** [tgstation/tgstation#72803]
Reporting client version: 514.1589

## Round ID:
[198468](https://scrubby.melonmesa.com/round/198468)

## Testmerges:
- [Makes nerve splicing surgery reduce stamina damage](https://www.github.com/tgstation/tgstation/pull/72661)

## Reproduction:
Every other shuttle seems to have them on the walls but the luxury shuttle has none even in the rich section.

**Comment by Zytolg** [comment]
The Luxury Shuttle was disabled with config change as detailed here -> https://tgstation13.org/phpBB/viewtopic.php?p=662250#p662250

As the current shuttle is unsatisfactory, reworks are being discussed and proposed as with #72940

**Comment by mc-oofert** [comment]
resolved with #72940
