### ISSUE TITLE
Possible Odysseus heal beam over sight

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#72807]
## Round ID:

Before the new mech change that made it so mechs could only have 2 slots the oddyseus had 3 slots which made it able to use 3 heal beams for max healing as intended for its design with this new change the Odysseus can only use 2 heal beams max with no other equipment which masibly downgrade its use and the general capability of heal beams for odysseus mech It doesn't seem like the original creature of the odysseus had this intended and it would probably be good balance to make two oddyseus beams heal as much as 3 beams.

**Comment by jughu** [comment]
>Game design can't cross medbeams or they explode
>but the oddysues can stack 3 medbeams over eachother

**Comment by SethLafuente** [comment]
> >Game design can't cross medbeams or they explode
> 
> >but the oddysues can stack 3 medbeams over eachother

Dear jughu next time you respond to an issue or pull request please be sure of what you say otherwise you will be seen as an utter fool let this be a reminder go the future 

First of all current Odysseus has 2 beams and they can indeed cross without exploding 

Before Odysseus had 3 beam beams as intended and they did cross without exploding

You are wrong in every possible way and it shows you have clearly never used seen or manage an oddy before and after the update that permanently nerfed them sorry if I come out as rude it simply pisses me off when people are confidently wrong
