### ISSUE TITLE
By not being in combat mode, unarmed strikes bypass blocking mechanics entirely.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#72812]
Reproduction:

The title is the TL;DR, here is the long format version explanation;

Say we have Maint Lee coming up to Scruff McGriff, the security officer. Lee wants Scruff's shoes, but Scruff is one of those paranoid weirdos that not only got himself an antidrop implant, but also two shields so that nobody could possibly touch him nor remove his shields without outright murdering him. Let's also say that Scruff, for whatever reason, is wearing a shielded modsuit he stole off a nukie or something. Real piece of work.

Maint Lee could attempt to shove over Scruff using right click in combat mode, but this would result in absolutely no effect as not only the shielded component will always block the attack while it has charges, but then he would need to contend with the RNG rolls for both shields. He'll probably get it, eventually, but it's extremely unlikely. 

Fortunately for Lee, he can instead choose to not enter combat mode whatsoever and use any unarmed based move he wants on Scruff to full effect, ignoring his layered shielding entirely. He can't lethally punch, but he can grab and shove, which opens plenty of opportunities for shoe theft.

This extends to martial arts, so if Lee were to possess a martial art that could perform moves using disarm (Krav Maga) or had grab/disarm moves (CQC), he could use this through the layered shielding. In this instance, Maint Lee could _kill_ Scruff McGriff using this one simple trick.

I call this bug 'Inner Peace Tricks the Unyielding Wall into Complacency'.

**Comment by IllotAFV** [comment]
#67715 I think , that defibrillator's stun is also related to this.

**Comment by necromanceranne** [comment]
It's a different check, but falls under the category of 'Shield checks not being checked'
