### ISSUE TITLE
Limb Grower refuses to print

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#72823]
Reporting client version: 514.1589

## Round ID:
[198523](https://scrubby.melonmesa.com/round/198523)

## Testmerges:
- [Makes nerve splicing surgery reduce stamina damage](https://www.github.com/tgstation/tgstation/pull/72661)

## Reproduction:
1. Construct a Limb Grower (this one was with a femto manipulator and two bluespace beakers)
2. Connect a Synthflesh pipeline leading in from the bottom so it autofills
3. Look at the 600u synthflesh in the tank
4. Watch it fail to print when you hit any of the buttons

**Comment by Profakos** [comment]
Could be linked the issue of autolathes being unable to print hacked items. Categories got messed up?
