### ISSUE TITLE
Multi-Z Parallax Oddity Upon Death (Blackness Fuck)

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#72832]
Reporting client version: 514.1588

## Round ID:
198558

## Testmerges:
- [Makes nerve splicing surgery reduce stamina damage](https://www.github.com/tgstation/tgstation/pull/72661)

## Reproduction:

Be on Tramstation.

I was hit by the tram (skill issue) on the top level, and was flung to the bottom level. I ghosted and wandered the station (using ladders to flip z-levels) for a bit until I was revived, until I was met with this.

![image](https://user-images.githubusercontent.com/34697715/213624425-a4a980f2-f2c0-4fd7-a25f-6d0f8c1540d8.png)

![image](https://user-images.githubusercontent.com/34697715/213624561-c9537522-73a0-4df9-9777-3120aacf5c03.png)

All of the "blackness" that normally obscures stuff you can't see was replaced with a shot clear through the station (I'm in the medbay, which is on the upper z-level of Tram). Also, looking through to the bottom level was just weird whiteness. That's not supposed to happen!

I was able to descend to the lower level to fix that parallax oddity, but I was met with two new things:

Firstly, on the lower Z-Level, I could see the "light cone" my seclite was emitting into the "blackness plane".

![image](https://user-images.githubusercontent.com/34697715/213624599-d0a14b7e-7584-4138-afec-a4a35bc7a967.png)

If I was on the upper z-level and something on the lower z-level (like this medibot (which you can't see)) would shine into the blackness plane, even though that doesn't make sense:

![image](https://user-images.githubusercontent.com/34697715/213624919-ef8f2d39-28a9-4aaa-bd41-9adf3aa50ec4.png)

Something to note is that this doesn't trigger if the light source is on the upper z-level, like this:

![image](https://user-images.githubusercontent.com/34697715/213625008-58250d3d-48ae-4be2-bec4-76b47e594e62.png)

Secondly (and only in a few places), I was met with this weird staggered-line effect whenever I move dmy character around and was looking at the lower z-level. Not sure what that was meant to be:

![image](https://user-images.githubusercontent.com/34697715/213624730-8eca5472-df7f-4242-a97d-3359e0198e20.png)

![image](https://user-images.githubusercontent.com/34697715/213624808-8cc62f57-c01e-43ce-9207-6e5a8a0b6e3c.png)

Seemed to only occur on the upper z-level?

Also, this is a bigger one, the whole lower z-level was fullbright:

![image](https://user-images.githubusercontent.com/34697715/213627396-42040047-bdf4-4923-81ad-c97e4471d8f9.png)

Everything was meant to be depowered, zero light. Yet, I can see all. Why?

Also space looked like this on the upper z-level after I "fixed" it:

![image](https://user-images.githubusercontent.com/34697715/213628277-03f8d392-c301-47dd-94ac-dba09b83628e.png)

**Comment by Serxule** [comment]
clear byond cache, a lot of this looks like problems from that

**Comment by san7890** [comment]
> clear byond cache, a lot of this looks like problems from that

it was perfectly fine before i died, this only showed up after i had died. i don't think the BYOND cache should affect plane/layering like this.

**Comment by Serxule** [comment]
> > clear byond cache, a lot of this looks like problems from that
> 
> it was perfectly fine before i died, this only showed up after i had died. i don't think the BYOND cache should affect plane/layering like this.

i dunno if z-level or anything is affecting this but i've gotten it a few times before and clearing byond cache always fixes it

**Comment by VladinXXV** [comment]
I experienced the same bug.

Manuel, Tramstation, Round 199181
Ckey: Vladoricious
Vladin Heir - Janitor

Died in maintenance (lower level) and explored as ghost. I don't remember if I went up/down between the z-levels while a ghost, but if I did it was using the `[` and `]` keys (which I have bound to move up and move down.)

**Comment by LemonInTheDark** [comment]
I have no idea what's going here

**Comment by LemonInTheDark** [comment]
I can't replicate it either which is..... ??????

**Comment by timothymtorres** [comment]
Lemon's fixed a lot of layer/plane issues since this bug report was added.  It's likely this was fixed

**Comment by TheVekter** [comment]
I'm closing this, there's another report up for a similar bug but this specific issue is fixed I think? Open a new one if I'm wrong.
