### ISSUE TITLE
Decal and Tile painters do not have icons on Terry

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#72849]
## Round ID: 
Every round for a few weeks now

## Reproduction:
Open a decal/tile painter's UI;
See the following:
![image](https://user-images.githubusercontent.com/42555530/213824365-977bca04-204b-4abe-bd35-80ccaac63898.png)

[This only happens on Terry for some reason LMAO]

**Comment by Inari-Whitebear** [comment]
Happens to me sometimes, try re-opening the UI or clearing your cache

**Comment by Justice12354** [comment]
Today I woke up and it decided to work just fine. Hurray!
