### ISSUE TITLE
You can somehow go unconscious forever as MMI

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#72869]
you cant move out to become ghost

Reporting client version: 514.1589

## Round ID:
[198648](https://scrubby.melonmesa.com/round/198648)

## Testmerges:
- [Makes nerve splicing surgery reduce stamina damage](https://www.github.com/tgstation/tgstation/pull/72661)

## Reproduction:

i dont even know what causes this
managed to do it by
1. became MMI
2. put in durand
3. died to EMP as durand
4. cant talk?? forever

**Comment by Serxule** [comment]
oh yeah, this happens with posbrains too, probably because a brain is an item and not a mob, so it cant wake up or pass out so it just softlocks/runtimes it
