### ISSUE TITLE
cant eat as clown when head gear is on

### ISSUE THREAD

**Issue by wizzardmuffin** [tgstation/tgstation#72871]
Round ID: [198654](https://scrubby.melonmesa.com/round/198654)
when i tried to eat as clown it kept asking me to remove my head gear and when i did i was able to eat.
the hat i was wearing was the plague doctor's hat.

**Comment by blackdav123** [comment]
I think the plague doctor's hat is just a reskinned biosuit hood so thats why you cant eat with one on

**Comment by wizzardmuffin** [comment]
that would make sense.

**Comment by Xander3359** [comment]
![image](https://user-images.githubusercontent.com/66163761/214441234-a30f8a56-2b32-4dcd-969a-77780dee1451.png)
It protects against diseases AND food!
