### ISSUE TITLE
Security Officers have no Orbit Menu icon.

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#72875]
Reporting client version: 514.1589

## Round ID:
[198660](https://scrubby.melonmesa.com/round/198660)

## Testmerges:
- [Refactors crew records](https://www.github.com/tgstation/tgstation/pull/72725)

## Reproduction:
Observe/die/etc.
Find someone who is a security officer on the list.
Notice the lack of an icon next to their name.
![image](https://user-images.githubusercontent.com/44104681/213888656-ea3080cc-4887-4a50-a3f4-73683ca60b7d.png)
![image](https://user-images.githubusercontent.com/44104681/213888666-9909d964-2d15-498f-9f5c-09efe2295aa7.png)
Every other job on here has an icon (Kiera and Zeke are charlie station crew, Nodder was using an agent ID as a "Syndicate Operative".)

**Comment by jlsnow301** [comment]
appears i've reencountered the bug where departmental officers were technically a different job (that i didn't account for). well, it's fixed now:
![Screenshot 2023-01-21 163057](https://user-images.githubusercontent.com/42397676/213895290-00de3c18-00d7-43f9-a162-21ed074390eb.png)
