### ISSUE TITLE
secHUD does not update with arrest status

### ISSUE THREAD

**Issue by ArthuroPep** [tgstation/tgstation#72872]
## Round ID:
Manuel, 198645

## Testmerges:
https://github.com/tgstation/tgstation/pull/72725

## Reproduction:

-Get a sechud
-Set yourself, or someone else, to arrest through the sechud
-Sechud won't update

**Comment by jlsnow301** [comment]
![Screenshot 2023-01-21 145847](https://user-images.githubusercontent.com/42397676/213890384-aa8757ee-f3ed-4e32-8481-7387f39fe7b8.png)

working. indentation issue

**Comment by SinfulBliss** [comment]
This is still broken

**Comment by ZephyrTFA** [comment]
It's an issue with huds not updating, not arrest status.

**Comment by ZephyrTFA** [comment]
(see https://github.com/tgstation/tgstation/issues/73134)
