### ISSUE TITLE
Escaping on a hijacked shuttle flags you as marooned

### ISSUE THREAD

**Issue by rasepretep** [tgstation/tgstation#72897]
## Round ID: [198725](https://scrubby.melonmesa.com/round/198725)

I'm not entirely sure if that's intentional or not, it could very well be considering we no longer have hijacking as objective, but just in case - if you have an escape on pod/shuttle objective as a traitor, the shuttle gets hijacked, and you land at the syndie base, you are flagged as marooned and fail the objective.

## Reproduction:
Be traitor or blood brother, hijack shuttle.

**Comment by Profakos** [comment]
Duplicate of #72240, caused by the lazy loaded template getting separated from centcom I think.
