### ISSUE TITLE
Catwalk/cable layering inverted

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#72894]
Catwalk/cable layering inverted

Seen on Manuel today, and yesterday:
![dreamseeker_W1drCPATDk](https://user-images.githubusercontent.com/1077971/213948881-f0dafcdd-4165-4e23-b2ae-984aa1f90a52.png)

Maybe it's only an issue on Charlie Station though, haven't checked on main station. Can't click the cable it seems like unless I do the alt-click thing to get the tile list. In the past the cable was on top of those catwalks.

## Testmerges:

#72725 

## Reproduction:

* Go to solars panel array

**Comment by lessthnthree** [comment]
Fixed in https://github.com/tgstation/tgstation/pull/72703
