### ISSUE TITLE
syndie infiltrator is somehow just a door

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#72891]
Reporting client version: 514.1589

## Round ID:
[198709](https://scrubby.melonmesa.com/round/198709)

## Testmerges:
- [Potentially fixes roundstart firelock hell](https://www.github.com/tgstation/tgstation/pull/72887)

## Reproduction:
![2023-01-22 16_23_39-Window](https://user-images.githubusercontent.com/70376633/213923905-78ef9795-3438-4696-9a04-2ce0381a1836.png)

i dunno nukeops spawned and that happened

**Comment by ZephyrTFA** [comment]
Has this occurred recently? This was probably fixed

**Comment by mc-oofert** [comment]
> Has this occurred recently? This was probably fixed

this was literally 30 days ago and its probably fixed so
