### ISSUE TITLE
Some roundstart pipes appear to not want to connect to coloured pipes, but will connect to omni colored pipes

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#72904]
## Reproduction:

Say, for instance, we go to the Metastation supermatter engine room, and we want to repipe our loop so that it's a straight pipe/volumetric pipes to, say, the thermomachines in the north section of the engine room. Our first through would probably be 'okay, match the colours'. 

Sadly, this won't work. Those pipes will never connect to any other pipe that wasn't one spawned at roundstart matching some unique colour that is exclusive to those pipes. This is maybe also why the pumps can cross colours despite using different colours, but aren't actually omnipipes.

Omnipipes, however, will always connect to each other. So we can actually utilize the pipes as intended, but we would have to repipe the entire loop to utilize color coding. Bridging, color changes, whatever, they don't work. These roundstart pipes will just refuse all comers, sometimes even pipes that seemingly they share a colour with.

**Comment by SyncIt21** [comment]
Pictures,  Videos,  even a round ID would be helpful

**Comment by TheVekter** [comment]
Yeah, get me pictures or reproduce it, please. Otherwise I'll be closing this.

**Comment by necromanceranne** [comment]
haven't seen it in a while so maybe this is fixed?
