### ISSUE TITLE
playing on fullscreen might be able to cause your PC to freeze

### ISSUE THREAD

**Issue by kawoppi** [tgstation/tgstation#72921]
## Round ID:
[198783](https://scrubby.melonmesa.com/round/198783)

## Testmerges:
~~The following pull requests are currently test merged:
[#72887: 'Potentially fixes roundstart firelock hell' by LemonInTheDark at commit 998bfa7a0a](https://www.github.com/tgstation/tgstation/pull/72887)~~
not likely to be relevant

## Reproduction:
I don't know if this might just be some fucked up hardware issue or what but I've only had this happen to me while playing SS13 in fullscreen. A handful of times I've had my PC just freeze while playing. Ambient sound keeps playing but the PC doesn't react to anything anymore. Only fix is to turn the PC off and on again.

This time it happened right before finishing climbing down a ladder on icebox. I don't remember if this has anything in common with the other times this has happened but I'll keep track from now on.

**Comment by SyncIt21** [comment]
I had the same problem. It was solved by clearing byond cache. This also happens when I switch between github branches and rebuild the game,  the keyboard input just stops working but clearing cache fixed that too

**Comment by kawoppi** [comment]
Cleared the cache, thanks for the suggestion! Haven't been able to play enough to be entirely confident on if it fixed the issue or not, but if it happens again I can just re-open this.

**Comment by SyncIt21** [comment]
> Cleared the cache, thanks for the suggestion! Haven't been able to play enough to be entirely confident on if it fixed the issue or not, but if it happens again I can just re-open this.

It will mostly happen again cause the cache can get corruped at any time so make sure to clear your cache atleast once a month. 
I do that every time I connect to a new serve actually and never had the problem since
