### ISSUE TITLE
Pirate APCs can be disabled remotely

### ISSUE THREAD

**Issue by Mewchild** [tgstation/tgstation#72939]
## Round ID: 
N/A, downstream. Confirmed issue is live here via DreamMaker
https://github.com/Skyrat-SS13/Skyrat-tg
Round #7505

## Reproduction:

Bring the Silverscale shuttle onto the station Z-level, and access the APC remotely via either the AI or the CE Console. Not sure if this issue affects other pirate vessels.

**Comment by Mewchild** [comment]
To note: This is a bug that returned since it was originally fixed back in https://github.com/tgstation/tgstation/pull/42616

**Comment by timothymtorres** [comment]
Looks like the correct solution would be to have an AI disabled APC mapping subtype
