### ISSUE TITLE
Demonic frost miner still fails at loading occasionally

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#72943]
Reporting client version: 514.1585

## Round ID:
[198842](https://scrubby.melonmesa.com/round/198842)

## Testmerges:
- [Refactors Suicide Verb + Basic Mobs Can Now Suicide](https://www.github.com/tgstation/tgstation/pull/72919)
- [Refactors crew records](https://www.github.com/tgstation/tgstation/pull/72725)
- [Potentially fixes roundstart firelock hell](https://www.github.com/tgstation/tgstation/pull/72887)

## Reproduction:

(id assume this is because it spawned on top of the lake below sec)
![image](https://user-images.githubusercontent.com/36141254/214384724-5ffe010b-b373-4ff7-b640-0cbd191c5c59.png)

**Comment by timothymtorres** [comment]
This is a multi-z ruin correct?

**Comment by newfren** [comment]
still an issue as of round 203744 (I got an admin to spawn it in for me, but later found that the top half had spawned without the bottom half)

**Comment by TheVekter** [comment]
I think this has more to do with multi-z ruins just sort of not working sometimes than it does him not spawning, but I'm leaving this open in case I'm proven incorrect.
