### ISSUE TITLE
ERT summon spawn as a briefing officer spawning in prisoner clothing.

### ISSUE THREAD

**Issue by itseasytosee** [tgstation/tgstation#72945]
## Round ID:
Tested local

## Reproduction:
Summon an ERT trough admin commands. enable "spawn youself in as a briefing officer". When preformed, instead you are spawned in in one of the chairs wearing nothing except a prisoner outfit.

**Comment by Baskett55** [comment]
Did you somehow change the briefing outfit setting on your end? it looks like this in game prefs in the admin tab
![image](https://user-images.githubusercontent.com/54517726/214491398-f3844983-cc8d-41fb-b620-8c226663ae29.png)

**Comment by itseasytosee** [comment]
> 



> Did you somehow change the briefing outfit setting on your end? it looks like this in game prefs in the admin tab ![image](https://user-images.githubusercontent.com/54517726/214491398-f3844983-cc8d-41fb-b620-8c226663ae29.png)

I haven't fiddled with it, but i'll give it a look

**Comment by TheVekter** [comment]
I've never seen this happen and it's worked fine the last 20 or so times I've done it, so I'm guessing this was an accident.
