### ISSUE TITLE
United Surplus Scam - Buy keys, but for what?

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#72978]
Reporting client version: 514.1589

## Reproduction:
Have an uplink, either as a nuke op or traitor.
Go to bundles.
As you can see, it's been at least 30 minutes.
![image](https://user-images.githubusercontent.com/44104681/214910360-65f9ab6e-bc38-4cf2-8159-12993d71d906.png)
Traitor uplink.
![image](https://user-images.githubusercontent.com/44104681/214910554-89742e13-2e92-4e74-8896-42ed3bf02ccb.png)
Operative uplink.
![image](https://user-images.githubusercontent.com/44104681/214910665-b46c81bd-0eb9-40a2-a532-63af2245858e.png)

Both uplinks allow you to spend 20TC on a United Surplus Crate Key, however, at no point is the United Surplus Crate itself actually available for purchase. Both have a progression minimum of 30 minutes. And of course, the key cannot be refunded.

**Comment by private-tristan** [comment]
you're meant to get another traitor to work together with you to buy the key and open it (although you can work around this by killing them and taking their PDA). see #71869

**Comment by VladinXXV** [comment]
I'm aware. The problem is it does not exist in the uplink.

**Comment by VladinXXV** [comment]
The key exists. The crate does not.

**Comment by timothymtorres** [comment]
Whatever code that is preventing the crates from appearing should be used on the key as well.  Sounds like a simple fix.

**Comment by Profakos** [comment]
Tested on latest, the surplus crate is there, along with many other crates that are missing from the screenshot in the OP. Peculiar!

![image](https://user-images.githubusercontent.com/2676196/215792112-6dd834f7-278d-46db-bef4-004b3d628367.png)

Likewise was visible in nuke op PDA.

**Comment by VladinXXV** [comment]
This was done in a locally hosted game. The code was up to date (as of making the issue). I was just messing around as various antags (which led to #72977, and subsequently, #72988). I'll also note that I tried manually spawning a crate in during this time, and opening it revealed absolutely nothing.

**Comment by VladinXXV** [comment]
I will try to see if I can reproduce it again on latest later today.

**Comment by VladinXXV** [comment]
> I will try to see if I can reproduce it again on latest later today.

I forgot. I'm doing it right now on latest (96117e742d136bf1ffe2c715691ca9386bf6a25c as of making this comment). And by doing it right now I mean I'm sitting here with the game running waiting for the Round Time to pass 30 minutes.

**Comment by VladinXXV** [comment]
> > I will try to see if I can reproduce it again on latest later today.
> 
> I forgot. I'm doing it right now on latest ([96117e7](https://github.com/tgstation/tgstation/commit/96117e742d136bf1ffe2c715691ca9386bf6a25c) as of making this comment). And by doing it right now I mean I'm sitting here with the game running waiting for the Round Time to pass 30 minutes.

On latest:

30 minutes passed:
![image](https://user-images.githubusercontent.com/44104681/216413102-561f7ec7-716f-4859-aa98-03b8c506f611.png)

Nukie uplink (normal nukie bundles DID show up this time, but still no crate. only the key):
![image](https://user-images.githubusercontent.com/44104681/216413477-e56c985a-732f-4eaa-8ae8-e392cdd6504d.png)

Traitor uplink:
![image](https://user-images.githubusercontent.com/44104681/216414599-cea94fa5-52f5-475a-896e-859cee918d83.png)

Steps:
join as assistant on metastation
gib yourself
realize you did not need to gib yourself
Ctrl + Shift + LMB on your ghost to spawn in again as a naked human
Go to traitor panel
select "Nuclear Operative"
wait until round time is at least 30 minutes
check your uplink
go to traitor panel
take away the uplink
in the "Syndicate" traitor category, select none
activate explosive implant
go to medical
Ctrl + Shift + LMB on your ghost to spawn in again as a naked human
go to traitor panel
select "traitor"
check your uplink
set TC to 100 and rep decently high just to be sure
check uplink again

**Comment by Profakos** [comment]
Followed steps on even later version, on 55e8ceba706.

On nuclear, indeed, the key was visible but not the crate. It looks like `purchasable_from = ~(UPLINK_NUKE_OPS | UPLINK_CLOWN_OPS)` is missing from the key.

After Ctrl + Shift + LMB as the same character as traitor, I could see neither nuclear operative items, nor traitor only items.

However, after I have went to the lobby, and spawned as a new character, and turned myself into a regular traitor, I have had access to the union crate.

So my final verdict is that the key appearing for nuke ops is indeed a real issue due to the missing flags. It not appearing for traitor is a different issue: your uplink flags got messed up by Ctrl + Shift + LMB respawning the character.

Thank you for the in detail steps, really helped with debugging it.
