### ISSUE TITLE
Telekinetic Viscerators

### ISSUE THREAD

**Issue by LSommers** [tgstation/tgstation#72984]
Reporting client version: 514.1588

## Round ID:
[198977](https://scrubby.melonmesa.com/round/198977)

## Testmerges:
- [Potentially fixes roundstart firelock hell](https://www.github.com/tgstation/tgstation/pull/72887)
- [Refactors Suicide Verb + Basic Mobs (actually all (most) living mobs) Can Now Suicide](https://www.github.com/tgstation/tgstation/pull/72919)

## Reproduction:

I have no idea how much of that I'm meant to include, but the issue in question can be replicated as follows:
-put a directional window between yourself and a viscerator
-get your limbs cut off through the window
-die

**Comment by timothymtorres** [comment]
Duplicate of #69254
