### ISSUE TITLE
Modsuit Control App won't link?

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#72980]
Reporting client version: 514.1589

## Round ID:
[198964](https://scrubby.melonmesa.com/round/198964)

## Testmerges:
- [Potentially fixes roundstart firelock hell](https://www.github.com/tgstation/tgstation/pull/72887)
- [Refactors Suicide Verb + Basic Mobs (actually all (most) living mobs) Can Now Suicide](https://www.github.com/tgstation/tgstation/pull/72919)

## Reproduction:
Find Modsuit Control program on maints disk.
Upload to PDA.
Try hitting a modsuit with your PDA.
Try hitting your PDA with a modsuit.
Nothing.

In the logs it will show up as me putting my PDA *into* my modsuit, but I'll note I've also tried this on modsuits without storage modules while localhosting - to no avail.

It doesn't seem like you can link a modsuit to the Modsuit Control program.

**Comment by Serxule** [comment]
did you open the modsuit control panel itself/have the suit powered on?

**Comment by VladinXXV** [comment]
Not in this particular round, but I did try this while localhosting (separately, of course, since you can't have the suit powered on while the panel is open). I've tried:
PDA on suit (panel closed, powered off, no storage module)
PDA on suit (panel open, powered off, no storage module)
PDA on suit (powered on, no storage module)
Suit on PDA (panel open, powered off, no storage module)
Suit on PDA (panel closed, powered off, no storage module)

The only missing combinations are not possible because you cannot take the suit off or open the panel while the suit is powered on.
