### ISSUE TITLE
Deploying doorjack while moving causes you to be spammed with "Cable retracted" popups

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#72989]
Reporting client version: 514.1589

## Round ID:
[198984](https://scrubby.melonmesa.com/round/198984)

## Testmerges:
- [Potentially fixes roundstart firelock hell](https://www.github.com/tgstation/tgstation/pull/72887)
- [Refactors Suicide Verb + Basic Mobs (actually all (most) living mobs) Can Now Suicide](https://www.github.com/tgstation/tgstation/pull/72919)

## Reproduction:
During this round I tried to use my doorjack while the person carrying me was moving around, but when I hit cancel I'd keep getting popups saying "Cable retracted" any time they moved

**Comment by Sealed101** [comment]
can no longer reproduce, also #73302 fixed an issue that was probably the cause of this one
