### ISSUE TITLE
you can achieve faster than walk speed with skateboards

### ISSUE THREAD

**Issue by Timonkeyn** [tgstation/tgstation#72993]
Reporting client version: 514.1589

## Round ID:
[199018](https://scrubby.melonmesa.com/round/199018)

## Testmerges:
- [Potentially fixes roundstart firelock hell](https://www.github.com/tgstation/tgstation/pull/72887)

## Reproduction:
buckle to skateboard, pull it and click 2 tiles ahead (pushing the skateboard while driving)

**Comment by moocowswag** [comment]
That.....makes me wonder if we could give skateboards a unique movement mechanic that requires you to use your mouse so that you cant use it during combat...just to go fast and try not to hit anyone while going fast.

**Comment by LEtranger135** [comment]
> That.....makes me wonder if we could give skateboards a unique movement mechanic that requires you to use your mouse so that you cant use said interaction/mechanic during combat...just to go fast and try not to hit anyone while going fast, might make for a fun way to race.
> 
> Whatever you describe in its current state I dont think is abusive towards game balance and it actually seems kind of neat, should probably fixed and replaced with an actual feature though.

𝑖 ℎ𝑜𝑛𝑒𝑠𝑡𝑙𝑦 𝑡ℎ𝑖𝑛𝑘 𝑡ℎ𝑒𝑟𝑒 𝑠ℎ𝑜𝑢𝑙𝑑 𝑏𝑒 𝑎 𝑓𝑢𝑛𝑐𝑡𝑖𝑜𝑛 𝑤ℎ𝑒𝑟𝑒 𝑦𝑜𝑢 𝑐𝑎𝑛 "𝑘𝑖𝑐𝑘𝑓𝑙𝑖𝑝" 𝑡ℎ𝑒 𝑠𝑘𝑎𝑡𝑒𝑏𝑜𝑎𝑟𝑑 𝑖𝑛𝑡𝑜 𝑦𝑜𝑢𝑟 ℎ𝑎𝑛𝑑 𝑖𝑛𝑠𝑡𝑒𝑎𝑑 𝑜𝑓 ℎ𝑎𝑣𝑖𝑛𝑔 𝑡𝑜 𝑐𝑙𝑖𝑐𝑘-𝑑𝑟𝑎𝑔 𝑖𝑡 𝑜𝑛𝑡𝑜 𝑦𝑜𝑢.

**Comment by Timonkeyn** [comment]
> 𝑖 ℎ𝑜𝑛𝑒𝑠𝑡𝑙𝑦 𝑡ℎ𝑖𝑛𝑘 𝑡ℎ𝑒𝑟𝑒 𝑠ℎ𝑜𝑢𝑙𝑑 𝑏𝑒 𝑎 𝑓𝑢𝑛𝑐𝑡𝑖𝑜𝑛 𝑤ℎ𝑒𝑟𝑒 𝑦𝑜𝑢 𝑐𝑎𝑛 "𝑘𝑖𝑐𝑘𝑓𝑙𝑖𝑝" 𝑡ℎ𝑒 𝑠𝑘𝑎𝑡𝑒𝑏𝑜𝑎𝑟𝑑 𝑖𝑛𝑡𝑜 𝑦𝑜𝑢𝑟 ℎ𝑎𝑛𝑑 𝑖𝑛𝑠𝑡𝑒𝑎𝑑 𝑜𝑓 ℎ𝑎𝑣𝑖𝑛𝑔 𝑡𝑜 𝑐𝑙𝑖𝑐𝑘-𝑑𝑟𝑎𝑔 𝑖𝑡 𝑜𝑛𝑡𝑜 𝑦𝑜𝑢.

![pp,504x498-pad,600x600,f8f8f8~2](https://user-images.githubusercontent.com/42039728/215391806-ede308eb-27de-4bc0-989f-002f6d327525.jpg)

**Comment by TheVekter** [comment]
Feature...?

**Comment by Timonkeyn** [comment]
> Feature...?

I know this is sarcasm but no this is not a feature since all vehicles except the cargo bike are in fact not faster than walking speed and this could probably be abused in a macro or a hack even

**Comment by Sealed101** [comment]
fixed by https://github.com/tgstation/tgstation/pull/73611
