### ISSUE TITLE
Small Fonts (our maptext font) needs to be replaced

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#73002]
"Small Fonts" doesn't come with all versions of Windows. I don't know what it comes with, but I have seen many screenshots of people not having it and the text looking terrible.

We can't legally distribute it as it is a builtin Windows font, and the license is not apparent. Theoretically possible to get a license from Microsoft, but fat chance.

We have VCR OSD Mono now, but it doesn't look good at very small sizes, only big ones.

Whatever font we replace it with needs to be non-blurry at the *very* small sizes maptext is usually at (Runechat, balloon alerts), which is extremely hard to find a font for. It must also be public domain, or otherwise distributable with our license. I don't really have any suggestions.

**Comment by MTandi** [comment]
Can confirm issue on this version

```
Edition	Windows 10 Pro
Version	21H2
Installed on	‎9/‎1/‎2021
OS build	19044.2965
Experience	Windows Feature Experience Pack 1000.19041.1000.0
```

**Comment by lessthnthree** [comment]
I've been looking into this on various occasions. A block I'm hitting is the rendering of the fonts as maptext. Since it's scaling them as vector objects it's difficult to find one that looks 'proper' at those sizes, even though their pixel characteristics should make them crisp. For example, a 6x11 pixel font won't be rendered properly even though it should be a perfect match.

If someone knows more about maptext or how we may be able to get around that, reach out to me.

**Comment by JohnFulpWillard** [comment]
https://github.com/intel/intel-one-mono

**Comment by lessthnthree** [comment]
> https://github.com/intel/intel-one-mono

It does.

![image](https://github.com/tgstation/tgstation/assets/83487515/d682ae38-6a60-43b0-b12e-364f23cc2d6c)

**Comment by Mothblocks** [comment]
do you think we can ask lummox why small fonts isn't anti-aliased while everything else we try is?

**Comment by MTandi** [comment]
Intel one is not a bitmap font, while the one we use right now (smalle.FON) - is a bitmap font. 
Intel one mono was not supposed to be rendered as bitmap font neither was it made for pixel art.

We need something like kenney's fonts that was made specifically to be rendered at font sizes below 8.

https://www.dafont.com/bitmap.php

**Comment by lessthnthree** [comment]
I looked at Lummox's dmifontsplus today to see if there's any hints, because it does a fine job with some normal fonts. Did make some progress. Nice and crisp.

![image](https://github.com/tgstation/tgstation/assets/83487515/af3aa254-64d7-4879-bbd5-58808489507c)

**Comment by Mothblocks** [comment]
Good find. That text is reaaaally big but you seem to be onto something

**Comment by MTandi** [comment]
Try this:

[Spess Font.zip](https://github.com/tgstation/tgstation/files/11859491/Spess.Font.zip)

![image](https://github.com/tgstation/tgstation/assets/3625094/8ebf7756-7746-4857-97af-c97dc46faee5)

**Comment by lessthnthree** [comment]
Yeah, it wasn't meant to be the final font, but getting it to look crisp in game was the first half of the battle, now on to fonts themselves.

**Comment by lessthnthree** [comment]
Here we go, I'll PR it when I'm done.

![image](https://github.com/tgstation/tgstation/assets/83487515/705f3a7d-5e10-41c9-8309-cb99a795a918)

**Comment by MTandi** [comment]
Please note that this one is bigger than the current one and you need to check how it looks when you scream.

**Comment by lessthnthree** [comment]
Yes, it's not finished. When I have all used styles (whisper, yell, clown etc.) then I'll put it up.
