### ISSUE TITLE
Genetic ability Geladikinesis Create Snow smites honorbound sect members

### ISSUE THREAD

**Issue by MisterGrimm** [tgstation/tgstation#73000]
## Reproduction: 

If you use the ability Create Snow from the Geladikinesis genetic while being a honorbound member you will get smote by god for using "conjuration magic". Don't know about you, but I don't think using genetics to make snow makes you magical.

1. Get the genetic ability Geladikinesis
2. Become a chaplain honorbound sect member
3. Use Geladikinesis ability Create Snow
4. Get smite by god for using "conjuration magic"

**Comment by moocowswag** [comment]
Its a lore issue, technically wizards are genetic mutants that are still considered human by asimov ai cause policy

**Comment by MisterGrimm** [comment]
Apparently genetics are magic now.

**Comment by moocowswag** [comment]
Its probably still a bug i would 100% leave it open.

**Comment by MisterGrimm** [comment]
> Its probably still a bug i would 100% leave it open.

Geladikinesis is under the Conjuration magic category, which is one of the four Punishable magic types for Honorbound, which hurt but do not outright kill you. The four Punished magic types for Honorbound are Evocation, Transmutation, Translocation, and Conjuration. The banned spells, which cause instant death, are Necromancy, Forbidden **heretic**, and Sanguine.
