### ISSUE TITLE
Tiling issue with opsglass

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#73028]
Reporting client version: 514.1589

## Round ID:
[199098](https://scrubby.melonmesa.com/round/199098)

## Testmerges:
- [Potentially fixes roundstart firelock hell](https://www.github.com/tgstation/tgstation/pull/72887)

## Reproduction:

Nuke ops during this round, part of their base looks like this:
![image](https://user-images.githubusercontent.com/3789327/215290490-4e569eb4-ca25-4eb1-a6b7-46fefbd0f826.png)

The grill tiles seem odd, or a new thing on the map, and look rather out of place, they are however the same as the indestructible glass tiles, they're just drawn wierdly..  

![image](https://user-images.githubusercontent.com/3789327/215290720-52fc5e65-8463-400d-b369-f73e327d0668.png)

The issue seems inconsistent, I initially thought it was end tiles but

![image](https://user-images.githubusercontent.com/3789327/215290639-4efd8a71-9709-476a-8a3e-b42d54cb94ad.png)
![image](https://user-images.githubusercontent.com/3789327/215290648-d90a67f4-52ca-4228-9250-8ce769315ebc.png)

And this one is the wierdest, two tiles of the same type and same tiling (lone tile) rendering differently
![image](https://user-images.githubusercontent.com/3789327/215290685-72f893cf-0fb8-4c4c-a6af-872e2c5bb647.png)

**Comment by ZephyrTFA** [comment]
fixed in a previous pr
