### ISSUE TITLE
Shattered ritual ghouls can regain use of both hands

### ISSUE THREAD

**Issue by blackdav123** [tgstation/tgstation#73034]
Reporting client version: 514.1589

## Testmerges:
- [Don't initialize stack components inside machines](https://www.github.com/tgstation/tgstation/pull/72863)

## Reproduction:
As a shattered ritual ghoul, fireman carry a corpse. This will remove both of your big meaty claws and allow you to freely use both hands for the rest of the round.

**Comment by BlueMemesauce** [comment]
Round ID was 199117
