### ISSUE TITLE
Cult is able to use blueprints to falsify summon location.

### ISSUE THREAD

**Issue by the-orange-cow** [tgstation/tgstation#73036]
Round ID: [199119](https://scrubby.melonmesa.com/round/199119)
BYOND Version: 514.1589
Server revision compiled on: 
Master commit: [075067a7378bad618e3cfee9567b3365f770a84f](https://www.github.com/tgstation/tgstation/commit/075067a7378bad618e3cfee9567b3365f770a84f)
The following pull requests are currently test merged:
[#72863: 'Don't initialize stack components inside machines' by SyncIt21 at commit 1f67d0fc92](https://www.github.com/tgstation/tgstation/pull/72863)

Local commit: 458c159ac865e3523e8abe1cb48aa3e99d5bee5c
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:

Cultists are able to rename the room in which they summon narsie, which falsifies the warning announcement.

**Comment by the-orange-cow** [comment]
> Sounds like clever use to me. Not sure if that makes it a bug

It is certainly clever, but it destabilizes the game mode.  The summoning is supposed to be done when the cult is fully capable of defending from the crew.  With this strategy in place, the meta will be to rush the CE, get the blueprints, get 9 members then name the summon room something from the other side of the station.  There really isn't a counter, as the warning was designed to state the true name of the summoner and the true location.

**Comment by Sealed101** [comment]
if they do that a cardboard mockup of the summoning should appear in the room they re-designated the actual summoning location into, with a paper notice about the change of place
if they rename it into some stupid shit like "youre mome" then randomly gib one cultist or something lol

**Comment by msgerbs** [comment]
This applies to way more than just cult summoning. Anything that gives a location can be faked out this way. It's very annoying being an engineer trying to find a breach only to discover that half the station has been renamed "Fore primary hallway". It isn't a "bug" per se but there's definitely some room for improvement. You probably shouldn't be able to rename uniquely named areas at all.
