### ISSUE TITLE
Kilo Maints Access

### ISSUE THREAD

**Issue by LinusMatysiak** [tgstation/tgstation#73041]
## Round ID: [199111](https://scrubby.melonmesa.com/round/199111)

the door on north and south despite being maintenance cant be accessed by CE but rather hop, which makes 0 sense, the map is kilo and the doors are: Research Lab Maintenance, Cargo Maintenance
https://imgur.com/gallery/yQwjzQZ

**Comment by Maurukas** [comment]
This is correct. Those doors lead to department interiors that the HoP has roundstart access to, and the CE does not.
