### ISSUE TITLE
Non-human players always spawn without underwear

### ISSUE THREAD

**Issue by NamelessFairy** [tgstation/tgstation#73063]
## Reproduction:

Main Issue:
Be a non-human, join the round either at roundstart or as a latejoin. You will have no underwear.

Original Issue which is related:
Be an admin with a non-human static, spawn yourself in using control + shift + click, you will spawn without any underwear. This occurs for all playable non-humans but not humans.

**Comment by NamelessFairy** [comment]
I feel like #73010 is somehow related

**Comment by ArcaneDefence** [comment]
cat with no panties

**Comment by itseasytosee** [comment]
Still works on felinids.

**Comment by LikesGreen** [comment]
Round ID: 199193
Think its related cause I, non-admin, normally shift spawning non-human (lizard) dont have underwear also on start

**Comment by Mothblocks** [comment]
needs screenshot tests

**Comment by NamelessFairy** [comment]
> Isn't this intentional? That pr like, said it was doing this didn't it

The pr says this doesn't impact character creation, this is impacted any non-human player character who spawns in using the admin shortcut, so I don't think it's intentional.

**Comment by NamelessFairy** [comment]
Following further testing, this impacts all non-human player characters in all commonplace situations, including roundstart joins and latejoins, I'll modify the issue to update it.

**Comment by NamelessFairy** [comment]
Found the cause. As part of on_species_gain(), called when someone changes species replace_body() is called, which happens to replace every single limb of the mob, which triggers the code added in #73010 when limbs are removed to remove the underwear associated with them.

**Comment by NamelessFairy** [comment]
This would also mean having your species changed, such as through mutation toxins or alternative human preference as described by Alamo on the original PR would also trigger this.

**Comment by necromanceranne** [comment]
> Still works on felinids.

Does not work on felinids, by the way.

**Comment by Pinkufeck** [comment]
Fucks up backup humans too. if it wasn't already mentionned

**Comment by san7890** [comment]
this was fixed by #73074
