### ISSUE TITLE
Cannot Click on HUD

### ISSUE THREAD

**Issue by WinterDarkraven** [tgstation/tgstation#73067]
## Reproduction:

At random (seemingly) you cannot click on items in your HUD. Restarting Byond breaks this even more. Clicking with both L and R mouse works as a click, but using one or the other does not.

This is strange and makes no sense.

**Comment by Serxule** [comment]
clear byond cache? unless other people are having this problem its either that or lag

also this isnt really descriptive of anything, and im confused on what 
>Clicking with both L and R mouse works as a click, but using one or the other does not.

 means, clicking works but doesnt work?

**Comment by Mothblocks** [comment]
Your toggle throw key probably got stuck, press Escape when this happens
