### ISSUE TITLE
Ghost huds are partially or completely missing

### ISSUE THREAD

**Issue by Thunder12345** [tgstation/tgstation#73075]
## Reproduction:

Be a ghost, look at someone. Medicul hus is missing entirely, sechud seems mostly present but missing at least mindshield implants, unsure about diagnostic hud.

![image](https://user-images.githubusercontent.com/5479091/215499042-a6b31665-dee9-4de3-8cf2-ad6150d04d50.png)

**Comment by Ryusenshu** [comment]
Not just as Ghost, happened to me as borg too
Had to reset the overlay multiple times because it kept breaking

**Comment by NamelessFairy** [comment]
For ghosts specifically this appears to occur every time you change orbit targets

**Comment by NamelessFairy** [comment]
Seems to break every time you change Z levels, might be other causes since I've seen this happen on single Z stations as well.

**Comment by sydemix** [comment]
diagnostic huds seem to work fine

**Comment by JupiterJaeden** [comment]
I'm pretty sure this is still related to the recent crew records change (#72725), at least with the sechuds. That change totally broke sechuds, but there was a patch made (#72948), however it seems that some of the issues have persisted. Not only does changing z levels break huds, but it still seems that sometimes when you change someone's arrest status with the console, it doesn't reflect on their hud (still shows when inspecting them though). Changing people's arrest status directly by inspecting works fine.

**Comment by GoldenAlpharex** [comment]
> I'm pretty sure this is still related to the recent crew records change (#72725), at least with the sechuds. That change totally broke sechuds, but there was a patch made (#72948), however these new issues appear to have arisen when that was merged. Not only does changing z levels break huds, but it still seems that sometimes when you change someone's arrest status with the console, it doesn't reflect on their hud icon (still shows when inspecting them though). Changing people's arrest status directly by inspecting will reflect the change on their hud icon.

I can say that it's not related to the crew records changes because we don't have it merged downstream yet and we have that issue too. It's something else that was merged recently.

**Comment by san7890** [comment]
@LemonInTheDark we good now?

**Comment by LemonInTheDark** [comment]
Ought to be better, if not let me know

**Comment by Diegoflores31** [comment]
tested yesterday , when you spawn with HUDs on you wont be able to see it . also it seems to ramdomly dissapear over time .

Example: you play security officer / warden . play for a while and it will magically go away either just your overlay or someone elses

**Comment by Diegoflores31** [comment]
it Seems that taking the glasses out and re equip fixes the issue but is quite anoying

**Comment by remuluson2** [comment]
Its still happening sadly, on all types of huds.

**Comment by TheVekter** [comment]
Someone verify that this isn't the same bug as #73134 then get back to me
