### ISSUE TITLE
the  nukie auto injector is empty

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#73085]
## Round ID:
[199230](https://scrubby.melonmesa.com/round/199230)

## Reproduction:
buy the special medical suite kit as a nukie and try using the combat auto injector, its empty! promptly get called fluke ops in dchat

**Comment by wulfenbach-jpg** [comment]
Not a bug. Intended. You are to use the reagents provided with the kit to fill the combat autoinjector.
https://github.com/tgstation/tgstation/blob/e9284490673074867a4357fc67c6504f0756cae0/code/game/objects/items/storage/medkit.dm#L291-L313
` /obj/item/reagent_containers/hypospray/combat/empty = 1, 
 /obj/item/storage/box/evilmeds = 1, `
Spawned directly next to the hypospray is a box of medicinal reagents.
https://github.com/tgstation/tgstation/blob/ac48461526e8300c49525803657bc3cc91b9f9b2/code/game/objects/items/storage/boxes/medical_boxes.dm#L115-L130
Moreover, see description of item in uplink:
https://github.com/tgstation/tgstation/blob/e9284490673074867a4357fc67c6504f0756cae0/code/modules/uplink/uplink_items/nukeops.dm#L669-L675
> **unloaded combat chemical injector**

**Comment by Jackal-boop** [comment]
Ooh I see
