### ISSUE TITLE
Gravity generator wrongly oriented/off-center

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#73083]
## Round ID: [199218](https://scrubby.melonmesa.com/round/199218) and others

As far as I can tell, broken by #72709

Gravity gen is weirdly oriented/off-center:
![image](https://user-images.githubusercontent.com/1077971/215595820-52736217-d806-4d74-9ca1-d6825284a0a6.png)

Seems to happen to all of them - including ones in space ruins.

## Reproduction:

* Play round
* Look at gravgen

**Comment by LemonInTheDark** [comment]
@ZephyrTFA

**Comment by ZephyrTFA** [comment]
I know exactly what the issue here, the implementation for this is hardcoded as a counter. Just need to change that counter.

TLDR: Changed the way the list of turfs is collected for the grav gen and so the corner "changed index"

**Comment by ZephyrTFA** [comment]
I'm just gonna cheat and change the x offset though.
