### ISSUE TITLE
AIs can't press buttons (again)

### ISSUE THREAD

**Issue by scriptis** [tgstation/tgstation#73091]
## Testmerges:

None

## Reproduction:

- be AI
- attempt to lower shutters in core
- doesn't work
- scream at john willard
- john willard doesnt work
- weep

Doesn't seem to be related to https://github.com/tgstation/tgstation/issues/70664. Affects all buttons

**Comment by JohnFulpWillard** [comment]
friday night f*nkin' memes

**Comment by MrrFiish** [comment]
Hey I was playing as an AI and let me add on to this, it is actually VERY weird.
If you look around off station (I was on icebox) there will be lines where you have vision no matter what, even without a camera and they're 1 wide. There's like a whole fucking grid of them that forms boxes that are somethin like 10x10, and anything that is on the line can't be interacted with, including consoles, doors, and buttons.

**Comment by newfren** [comment]
wait that sounds insanely familiar to an older ai bug...

https://github.com/tgstation/tgstation/issues/70664

any chance this is the cause again?

**Comment by Vect0r2** [comment]
+1 happened to me

**Comment by Vect0r2** [comment]
honestly I do think it is about the chunk loading or SOMETHING, as you can see here:
![chunk1](https://user-images.githubusercontent.com/71346830/215888398-a9582b69-036d-4468-bed8-046948c23373.PNG)
![chunk2](https://user-images.githubusercontent.com/71346830/215888439-b682607b-3937-4dbb-9ada-6387abc9c547.PNG)
![chunk4](https://user-images.githubusercontent.com/71346830/215888461-82bdedce-10c6-41ea-9672-4162ebd6f013.PNG)

**Comment by Vect0r2** [comment]
Also, I would assume it has to do with chunk loading, as I took a few snapshots from a recent AI game I played
![chunk1](https://user-images.githubusercontent.com/71346830/215901331-8eea52e8-7e6f-4e25-8873-fc3bf140c1db.PNG)
![chunk2](https://user-images.githubusercontent.com/71346830/215901344-de0f1223-7c7d-405a-b4e8-0eaaebb5c425.PNG)
![chunk4](https://user-images.githubusercontent.com/71346830/215901361-d6840b60-2fda-4660-9840-64e0e9c57e5d.PNG)

**Comment by Sealed101** [comment]
comedy

**Comment by Sealed101** [comment]
i think it may be creating chunks that are shorter on each side by 1 tile

https://github.com/tgstation/tgstation/blob/e0bf4d9090aeed8e9bacf8ba062ae71cc484c910/code/__DEFINES/turfs.dm#L34

https://github.com/tgstation/tgstation/blob/5dbaa25f915157be1f6dc4eddaffe6d987e43655/code/modules/mob/living/silicon/ai/freelook/chunk.dm#L158-L159

**Comment by msgerbs** [comment]
It's too early for FOTY 2023 dammit!
