### ISSUE TITLE
You can eat Meat and Pizza turfs with your mind (thanks to Telekinesis, everyone's favourite click code misfit)

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#73115]
## Reproduction:

Just put down some pizza floors or make the walls out of sheetizza. Then, with telekinesis, click those turfs.

You'll begin eating those turfs. This also happens to work through walls, on turfs you can't actually see.

![ztxi2rac4va51](https://user-images.githubusercontent.com/40847847/215896894-b1c62f11-d588-45ac-931a-d51e2a882d50.jpg)

**Comment by the-orange-cow** [comment]
Feature
