### ISSUE TITLE
tracker rounds dont work

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#73121]
## Round ID:
[199295](https://scrubby.melonmesa.com/round/199295)

## Reproduction:
fire a detective tracker  round into a human target. you cant access that persons location through a tele console. even though a red dot appears on their sec HUD

**Comment by Profakos** [comment]
Reproduced. They still work on the prisoner console at least, so the error is probably in the teleporter console, not the implant.

**Comment by Profakos** [comment]
Final investigation results: the detective bullets have allow_teleport = FALSE. This is not a bug, and is intended. However, it should be made clearer that this only works for the Prisoner Management console.
