### ISSUE TITLE
Autolathes accept several materials they cannot print the raw sheets of [and therefore cannot be removed easily]

### ISSUE THREAD

**Issue by SeigaSeiga** [tgstation/tgstation#73123]
## Reproduction:

Autolathes accept several material sheets and recycled items they cannot do anything with under most circumstances, with the potential to clog the material storage [though practically this never happens]. I haven't accounted for design disks and obscure items when making this list, but I've been as thorough as I can.

- bone
- adamantine
- wood
- bluespace crystal
- bamboo
- snow
- metal hydrogen
- hot ice
- runed metal
- bronze
- paper
- zaukerite
- meat
- pizza
- hauntium
- mythril
- sand
- sandstone

alien alloy just recycles into plasma and iron, so it doesn't make the list. some of these are vanishingly rare, some are very common. The only way to remove these materials once they enter the lathe is to deconstruct the lathe, which is somewhat inelegant. I'm not a talented enough coder to figure out the right solution. [make all above material sheets available to be printed? make these sheets available to be printed if autolathe hacked? change the way you remove raw materials from autolathes entirely?? stop these materials going in?? idunno.]

**Comment by SeigaSeiga** [comment]
I know you can make toolboxes out of anything, but that's not exactly helpful.

**Comment by newfren** [comment]
the real issue looks like just not being able to dispense the raw form of some materials when the autolathe has accepted them - like, it can't dispense metal hydrogen bars if it's given them somehow

**Comment by SeigaSeiga** [comment]
> Your title is misleading and you recognize it in your first comment
> 
> It's not that "there are several materials which you cannot print anything with" it's that "there's nothing useful you can print with these materials"
> 
> This on its own is not an issue, but if someone wants to expand these with unique recipes... go for it?

My bad. Title was an easy enough thing to correct, shouldn't be misleading now.
