### ISSUE TITLE
Paper rework (presumably) broke voting box

### ISSUE THREAD

**Issue by Ekaterina-von-Russland** [tgstation/tgstation#73139]
## Reproduction:

![](https://i.imgur.com/fxL83kD.png)

Make voting box (15 iron). Put votes in. Tally votes. Weird formatting.
Discovered in the course of holding the most secure shuttle call vote.

**Comment by msgerbs** [comment]
Wow, somebody actually used this feature? This deserves a fix just for that alone.

**Comment by msgerbs** [comment]
Probably caused by #68612
