### ISSUE TITLE
Zombies and Venus Fly traps can kill each other based on flavor text

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#73158]
## Round ID:

Zombies and venus fly traps lack the same traitor panel that other "team based" antags have gotten. At the moment they only have flavor text that comes in the chat panel, which doesn't tell them that they cannot or should not attack each other. 

Which would be fine but admins say you can't do that but players have no way of knowing that and their answer will varied from admin to admin bases so is better to give them one for new and dumb players alike.

A possible solution (in addition to bringing their conversion/ghost role taking) would be giving them a hud icon (similar to revs, wizards, cult) so that they can determine who is friend or foe.

**Comment by JohnFulpWillard** [comment]
Sounds like you refused to read flavortext, got bwoinked, then blamed the game

https://github.com/tgstation/tgstation/blob/ad86f8e6be71298b9e001d7bd7c6430e47d4f738/code/modules/zombie/organs.dm#L82-L87

https://github.com/tgstation/tgstation/blob/ad86f8e6be71298b9e001d7bd7c6430e47d4f738/code/modules/mob_spawn/ghost_roles/venus_human_trap.dm#L1-L11

**Comment by SethLafuente** [comment]
No it was more like a got killed by other zombies for no reason one round ahelped admin told me zombies technically aren't a team antag then I kill a few kudzu and an admin told me they are a team antag also all antags should have an antag panel as standard anyways and having an antag hud for zombies to know who is a zombie for those in full suits would also be optimal

**Comment by JohnFulpWillard** [comment]
So you refused to read flavortext, got bwoinked, then blamed the game

**Comment by Ekaterina-von-Russland** [comment]
This is one confusing report. It sounds like you're implying venus human traps and zombies are somehow on the same team when they have nothing to do with each other.

**Comment by SkeletalElite** [comment]
> This is one confusing report. It sounds like you're implying venus human traps and zombies are somehow on the same team when they have nothing to do with each other.

![image](https://user-images.githubusercontent.com/26270704/216286245-1b4e5a6f-00e0-487c-aef1-c2cd3583e45c.png)

**Comment by tralezab** [comment]
> No I read Venus fly trap flavor text and nowhere did it say I couldn't kill other fly traps

I'll fix this issue but like in the future you can avoid getting banned by like, thinking about it. Just use a little logical thinking

**Comment by LemonInTheDark** [comment]
This isn't a bug, get off my lawn. It's an admin problem.
@tralezab what do you want to fix?

**Comment by SethLafuente** [comment]
> This isn't a bug, get off my lawn. It's an admin problem.
> 
> @tralezab what do you want to fix?
> 
> 

Fixing 2 clear antagonist not having antag panels instead of just easily missable chat alerts reason they don't have that is because their code is older than antag panels if they were added recently they would have gotten antag panels im sure

**Comment by SethLafuente** [comment]
> > No I read Venus fly trap flavor text and nowhere did it say I couldn't kill other fly traps
> 
> 
> 
> I'll fix this issue but like in the future you can avoid getting banned by like, thinking about it. Just use a little logical thinking

Didn't get banned or even an admin note for this surprisingly enough this post wasent done because of similar "ided/ibanned " reasons is out of legitimate concern for new players not knowing based on missing chat alerts and rules not being concrete and easy to follow for dumb people such as myself
