### ISSUE TITLE
AI can't use Hop Queue Shutter button/Doesn't have access

### ISSUE THREAD

**Issue by spaceboi123** [tgstation/tgstation#73155]
Reporting client version: 514.1589

## Round ID:
[199362](https://scrubby.melonmesa.com/round/199362)

## Testmerges:
Don't think there's any

## Reproduction:
Step 1: Be AI (I know very hard)
Step 2: Try to close/open HoPs queue shutters via button
Step 3: Shutter button flashes red, and you are sad
Step 4: Cry silicon tears because something on the station has access you don't have (Important and required step)

**Comment by Sealed101** [comment]
did it say access denied and actulally flash red or did it not react at all
if it's the latter, it's #73091 at play

**Comment by spaceboi123** [comment]
I didn't get a access denied message but the button did flash red

**Comment by Sealed101** [comment]
could not reproduce with and without the grid of doom
which button did you press? were there any modifications done to them? perhaps some dipshit just screwed the electronics out of the button, ruining it
![image](https://user-images.githubusercontent.com/75863639/216633716-7d7e7381-8b6d-4c2d-ba5b-d7b4612c45fd.png)

**Comment by spaceboi123** [comment]
I am like 88% sure that the issue prob came from the other AI issues that were going on, but I don't think anyone messed with the button, I hit the bottom one that's labeled shutters, and it flashed red, but the Hop could open them still, so I don't know, haven't been AI again yet so I haven't been able to check

**Comment by Sealed101** [comment]
haven't heard about this issue appearing again, and couldn't reproduce it. probably safe to close
