### ISSUE TITLE
Golems made from the autolathe have the Lavaland free golem debuff

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#73167]
## Testmerges: None

If you get the disk from the Free Golem ship, bring it back, and create a golem shell with it, that golem is considered "free" and has the debuff it normally would from being from Lavaland. I'm not sure if this is intentional, but it results in people thinking they aren't supposed to be there and validing them.

**Comment by JohnFulpWillard** [comment]
They're still free golems, I don't see why they would not have the slowdown

**Comment by IndieanaJones** [comment]
I mean, you print the shell and fill in the materials, I feel like they should probably be loyal to whoever filled the shell with mats, just like normal golems.

**Comment by Sealed101** [comment]
it's a free golem design disk and it prints free golem shells, makes sense to me
if you need golem spam(ew), go to xenobio, it's easier to do that there in industrial quantities
