### ISSUE TITLE
Mech Armor doesn't seem to calculate properly (actual bug?)

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#73181]
Round ID:  N/A

## Reproduction:

Mech Armor doesn't seem to calc damage as it should. I tested this by using 3 CQC boosters on a Durand, which should leave it at 85% armour. (Base armour is 40%, each plate adds 15%, so 85%.) I then tested a Fire Axe against a Durand, which should in theory do about 5.4 damage - the Axe has 24 base damage * 1.25 for as the demolition mod. Instead, the Axe seems to do around 4% damage to the mech - which is around 16 damage, critically this is enough to roll the mech's internal damage threshold (which is 15 damage) - meaning a Axe user can cripple a fully-armoured Durand at 100% HP in a single strike.

Another test - when using a Axe against a stock Ripley (40% melee) the Axe appeared to deal around 15% of its health - around 30 damage as it was a MK-1 Ripley. This is bizarre as it should only do about 18 damage, enough for a critical roll, but not enough to destroy a Ripley in around 7 hits.

**Comment by timothymtorres** [comment]
Double check if fire axes have any kind of AP properties which might be the reason it's happening.

**Comment by githubuser4141** [comment]
> Double check if fire axes have any kind of AP properties which might be the reason it's happening.

Mr_Melbert said mechs at the time of writing (about 3-5 days ago) didn't care about AP, according to fireaxe.dm it has sharpness but shouldn't have any dedicated AP.

**Comment by githubuser4141** [comment]
So.. do you mean it runs AP calcs all the time, or it applies AP when there isn't any AP to be found in a weapon? The fireaxe doesn't seem to have any AP number, so unless there's a hardcoded minimum amount, like, 15, somewhere it shouldn't be having any effect? To do 16 damage under 85% armour it'd have to be fairly significant, like 35%+ AP which wouldn't make sense as a minimum. The demo mod as I mentioned in the OP should make the fireaxe do 30 damage in total which should be 4.5 damage against armor -- but currently it does 16 (or thereabout) damage.

**Comment by timothymtorres** [comment]
> Nowhere in the code snippets you supplied is the item's armor penetration value read - it's only done in `bullet_act`

I was looking at `var/damage_taken = take_damage(attacking_item.force * attacking_item.demolition_mod, attacking_item.damtype, MELEE, 1)` wrong and thought the 1 was setting the armor penetration to true.  Late night coding fatigue I guess.

Tested this just now:

Wielded fire axe vs RIPLEY 1 resulted in `18` damage and Durand x3 CQC armor booster results in `4.5` damage. This was consistent regardless of angle or if an operator was inside the mech.

**Comment by githubuser4141** [comment]
> 

That's really weird. I'll test this once I've got the time to d/l the repo but when I tried in-game it was 4& for the Durand (4% of 400 is 16) and 15% for the Ripley (so, 30 damage). I'll see if I can test this again in a live server and put the results in one of those imgur sites if I can find one.

**Comment by githubuser4141** [comment]
Wow. Tested in a local, up-to-date server & I'm getting the same results. Is it possible that the Host's machine has subtle changes that wouldn't appear on the github repo that affects weapon balance? Or maybe it was a one-off VE change. I'll try to join a live server in a bit and post the results.

**Comment by githubuser4141** [comment]
Update: This bug isn't present on the Sybil server, but it is in Campbell, and probably Manuel (?). 

Round info:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: 199516
BYOND Version: 514.1581
Server revision compiled on: 2023-02-02T09:27:34+00:00
Master commit: [e0bf4d9090aeed8e9bacf8ba062ae71cc484c910](https://www.github.com/tgstation/tgstation/commit/e0bf4d9090aeed8e9bacf8ba062ae71cc484c910)
TGS version: 4.15.7
DMAPI version: 5.3.0

**Comment by Sealed101** [comment]
#73319 seems to have fixed the flat armor values; armor boosters properly increase those values
