### ISSUE TITLE
Containers can instafeed their contents

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#73198]
Reporting client version: 514.1589

## Round ID:
[199449](https://scrubby.melonmesa.com/round/199449)

## Reproduction:
1. Get a container with some form of reagents (bottle, beaker, glass, etc)
2. Try to feed it to someone else
3. Watch it happen instantly without any time for the other player to react.

**Comment by Robustitron** [comment]
Noticed this during cult, I was able to instantly feed people holy water, I could _technically_  just run by people in the halls feeding them holy water if I wanted.
