### ISSUE TITLE
Wagging removes spines from your sprite. 

### ISSUE THREAD

**Issue by Slurge00** [tgstation/tgstation#73230]
Reporting client version: 514.1589

## Round ID:
[199523](https://scrubby.melonmesa.com/round/199523)

## Reproduction:
Wagging your tail removes your lizard spines from your sprite. Stopping the wag returns them. 
![image](https://user-images.githubusercontent.com/102489377/216792818-475f5ac7-84ed-4d16-984c-db856a097ece.png)
![image](https://user-images.githubusercontent.com/102489377/216792835-6b55b887-87b0-4349-a44f-99b78ccdc224.png)

**Comment by Time-Green** [comment]
UUUUUUUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHH

**Comment by thegrb93** [comment]
It was fixed a few days ago for me, but today wagging doesn't use the animated spines, and stopping wagging removes the spines.
