### ISSUE TITLE
Golems cannot put themselves out if they walk into lava/light themselves on fire (while they are not even on fire, sprite issue!)

### ISSUE THREAD

**Issue by epicgamer545** [tgstation/tgstation#73235]
## Reproduction:

1. Be a golem.
2. Go into lava/set yourself on fire.
3. Attempt to put yourself out.
4. Plot Twist: You can't put yourself out. You are not even on fire. It's a sprite issue.

Here's me trying to put out myself as a golem: https://gyazo.com/43a3f9b234470e7c9ba7c6aa3e1577e2
[](https://i.gyazo.com/43a3f9b234470e7c9ba7c6aa3e1577e2.png)

**Comment by epicgamer545** [comment]
I'm unsure if this is intended, but being forever on fire while you are CLEARLY not on fire is at least an oversight.

**Comment by newfren** [comment]
drakes can also leave you in this "permanent on fire" state, and I THINK I've seen it crop up with whelps too although I'm not certain.

**Comment by necromanceranne** [comment]
Actually, this problem isn't just for golems, or drake fire, something really fucked up happened with the fire overlays seemingly never wanting to go away. I think there are a few workarounds to getting rid of it, but it has been a problem for some time.

I'll make a separate issue for it.
