### ISSUE TITLE
Pandemic machine bluescreens when trying to print vaccines

### ISSUE THREAD

**Issue by Robustitron** [tgstation/tgstation#73233]
## Testmerges:
none that I could see

## Reproduction:
1) Put blood with antibodies into pandemic machine
2) Try to print/fabricate the vaccine
3) The ui window bluescreens
4) Try several times and realize its not possible to print vaccines

I've seen this happen a few times but the last time (round id) was on the lavaland syndicate base.

**Comment by timothymtorres** [comment]
Probably fixed by #73613
