### ISSUE TITLE
pAI door jack prompt spam 

### ISSUE THREAD

**Issue by spaceboi123** [tgstation/tgstation#73244]
Reporting client version: 514.1589

## Round ID:
[199538](https://scrubby.melonmesa.com/round/199538)

## Testmerges:
Don't think there's any

## Reproduction:
As a pAI, have the door jack
Then, extend the cable
Hit cancel
Every time you take a step, you get a prompt saying the cable has been retracted

**Comment by Likteer** [comment]
#73222 Also, repeating multiplies the balloon alert, I've reached a point where i got it popping up even when standing still
