### ISSUE TITLE
EMP doesnt work, probably as most of chemistry.

### ISSUE THREAD

**Issue by Helg2** [tgstation/tgstation#73248]
## Round ID:
[199553](https://scrubby.melonmesa.com/round/199553)

## Reproduction:
Combine Uranium with Iron and get nothing. Like totally.

**Comment by VladinXXV** [comment]
Not a bug, as of #73081 EMPs now also require aluminium. Wiki is outdated in this regard.

**Comment by Helg2** [comment]
bruh
