### ISSUE TITLE
Gorilla gloves still reference throw intent

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#73240]
Reporting client version: 514.1589

## Round ID:
[199539](https://scrubby.melonmesa.com/round/199539)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/216801298-4632b5aa-9e15-46a9-b589-de927826b9e6.png)

**Comment by JohnFulpWillard** [comment]
what's the problem with throw intent? your intent is to throw

**Comment by dragomagol** [comment]
I had a moment where I thought grab intent was throw intent, I still think "throw mode" is clearer though
