### ISSUE TITLE
Can't repair shredded limbs on clothing

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#73249]
Reporting client version: 514.1589

## Round ID:
[199551](https://scrubby.melonmesa.com/round/199551)

## Reproduction:
Have a section of your jumpsuit damaged
Click on it with cloth
Nothing!

From what I've gathered, the suit needs to be damaged too badly to wear to be fixable in terms of shredding. Seems really weird though. WHY can't I repair the massive hole in my pants until everything else is fucked?
![image](https://user-images.githubusercontent.com/44104681/216812584-0a2833bd-0f52-4b64-b83d-e9399db87e61.png)

**Comment by TheVekter** [comment]
This is an old comment on the matter, but I can't find anything that even touches clothing damage since then, so I assume this is still correct.

> Damaging clothes, despite the fancy damage overlay, is a 'critical existance failure' situation; they're either in full working condition or fucking gone and there's no actual in-between, and with stuff like hardsuits there's no range for in-between, since space immunity is pretty binary already.

So you can't repair damaged clothing because it's not actually damaged until it's broken. Sounds like something neat to implement but it's not a bug.
