### ISSUE TITLE
All Benches appear blue, rather than only Tram benches

### ISSUE THREAD

**Issue by OrionTheFox** [tgstation/tgstation#73250]
## Round ID:
Irrelevant

## Testmerges:
Irrelevant

## Reproduction:
Craft a Bench of any type
Observe, it is the weird neon-blue the Tram uses

![image](https://user-images.githubusercontent.com/76465278/216818680-59f05516-2ac3-4b0f-bfcb-a71e273e54c2.png)

The benches SHOULD be a dull yellow, per the base type.
As defined in `code\game\objects\structures\beds_chairs\sofa.dm`
```
/obj/structure/chair/sofa/bench
	name = "bench"
	desc = "Perfectly designed to be comfortable to sit on, and hellish to sleep on."
	icon_state = "bench_middle"
	greyscale_config = /datum/greyscale_config/bench_middle
	greyscale_colors = "#af7d28"
```

And per code\modules\industrial_lift\tram_override_objects.dm...
```
/obj/structure/chair/sofa/bench/tram
	greyscale_colors = "#00CCFF"
```

They shouldn't be overwriting EVERY bench, the tram benches should be separately colored subtypes.

**Comment by lessthnthree** [comment]
Oop.

**Comment by OrionTheFox** [comment]
This was **not** fixed, and intentionally so. The PR that reportedly fixed it purposefully changed all colors to a slightly different shade of blue rather than back to the expected yellow.
![image](https://user-images.githubusercontent.com/76465278/218447189-3deec233-1652-44e6-a112-b54225a2865e.png)
https://github.com/tgstation/tgstation/pull/73243/commits/f20297557db8827fecfb22b9cb2ec9de662132eb intentionally made all benches a different blue than the tram, while the PR stated it'd be reverted back to the expected color. This was a blatant lie.

@Imaginos16 Pinging for visibility, this shouldn't have been marked as being fixed and intentionally worked around.
