### ISSUE TITLE
Gubbucks do not consume Gibs

### ISSUE THREAD

**Issue by ArthuroPep** [tgstation/tgstation#73262]
## Round ID:

[199595](https://scrubby.melonmesa.com/round/199595) 

## Reproduction:

- Play Ashwalker
- Bring a body to the necropolis tendril. This will gib it
- The gubbucks will not eat the gibs, and will stay without any "milk"

**Comment by Sealed101** [comment]
they were always a bit shy with eating gibs and organs, we can only hope they will get changed to basic mobs to improve their ai

**Comment by timothymtorres** [comment]
See #47568

> They eat things to heal, which means they will not eat unless you damage them. Punch them or otherwise damage them to make them eat.

**Comment by Likteer** [comment]
You can also drag them around and they should eventually start eating.

**Comment by kopoba** [comment]
> See #47568
> 
> > They eat things to heal, which means they will not eat unless you damage them. Punch them or otherwise damage them to make them eat.

they definitely must auto eat without punching so its a bug.
