### ISSUE TITLE
Suffocation isn't working.  And probably some other things.

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#73276]
Reporting client version: 514.1589

## Round ID:
[199644](https://scrubby.melonmesa.com/round/199644)

## Testmerges:
- [ChilledStation: A Bold New Venture for Nanotrasen](https://www.github.com/tgstation/tgstation/pull/72994)

## Reproduction:

Spawn in space with a health analyzer.  Take brute and burn damage, but no suffocation.

Strangle suffocation seems to do nothing, pillow suffocation the same.  CPR works, salbutamol works.

I did have a test human that was suffocated, CPRed to about 57 oxyloss, then re-suffocated (which does zero additional damage) which seemed to stop them recovering oxyloss, even after I stopped re-suffocating them.

Plasmapeople dont seem to need their plasma internals.  On the other hand, anaesthetic internals makes you pass out.

**Comment by Time-Green** [comment]
Suffocation was removed it seemed to kill the player

**Comment by Time-Green** [comment]
Suffocation was removed because it seemed to kill the player
