### ISSUE TITLE
Solar tracker overlay broken

### ISSUE THREAD

**Issue by MTandi** [tgstation/tgstation#73278]
Solar tracker lost its overlay and the animation in built state.

Regression after #72886 

@LemonInTheDark FYI

## Reproduction:

Try to build solar tracker

**Comment by LemonInTheDark** [comment]
ghhhhhhhh

**Comment by SyncIt21** [comment]
@LemonInTheDark you should close this

**Comment by LemonInTheDark** [comment]
right right
