### ISSUE TITLE
Some emotes that should work without arms don't

### ISSUE THREAD

**Issue by Echriser** [tgstation/tgstation#73289]
## Reproduction:
Lose both of your arms and then try to perform an emote like `*spin` or `*flip`.

**Comment by TheSmallBlue** [comment]
Spinning I understand, flipping I think does involve needing some counterweight with your arms

**Comment by TheVekter** [comment]
This is working as intended; there's a check the game does for whether or not the player has arms on certain emotes, and both of these emotes intentionally include this check.

As TheSmallBlue points out as well, it makes sense for both cases as you'd need arms to flip and spin (at a decent rate, at least. I guess you could shuffle your feet.)
