### ISSUE TITLE
Syndicate revolver and trick revolver have different names, making it easy to know the difference

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#73313]
Reporting client version: 514.1589

## Round ID:
[199732](https://scrubby.melonmesa.com/round/199732)

## Testmerges:
- [Tramstation: Growing Pains](https://www.github.com/tgstation/tgstation/pull/72331)

## Reproduction:
Look at them 
![image](https://user-images.githubusercontent.com/54517726/217437812-82ffd523-31a7-4316-b663-569d71ae8fcd.png)

**Comment by Sealed101** [comment]
this is what soul removal leads to people
