### ISSUE TITLE
forcing cough  as  sentiennt  virus cant infect anyone

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#73312]
## Round ID:
[199721](https://scrubby.melonmesa.com/round/199721)

## Reproduction:
try forcing a cough through a host next to someone. it wont infect them

**Comment by Overuseddart** [comment]
Isn’t it in front of the host? It’s also chance based for infection Im pretty sure.

**Comment by Time-Green** [comment]
There's a lot of influencing variables, like above, which OP has not elaborated on. Closing for too little info
