### ISSUE TITLE
Gulag shuttle is missing point claim console

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#73324]
Reporting client version: 514.1589

## Round ID:
[199777](https://scrubby.melonmesa.com/round/199777)

## Testmerges:
- [Tramstation: Growing Pains](https://www.github.com/tgstation/tgstation/pull/72331)

## Reproduction:
Look at the gulag shuttle with no claim console.

**Comment by Baskett55** [comment]
might be caused by #72433

**Comment by Baskett55** [comment]
And the stacking machine console starts of unlinked 
![image](https://user-images.githubusercontent.com/54517726/217689109-714bab9e-f7a1-4efa-afb8-f7df45018acd.png)

**Comment by NamelessFairy** [comment]
Caused by #73261
