### ISSUE TITLE
Meteor Changelings can get immediately killed by shield satellites

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#73349]
Reporting client version: 514.1589

## Round ID:
[199870](https://scrubby.melonmesa.com/round/199870)

## Reproduction:
This just seems like a waste of threat, you are able to spawn in and start flying towards the station but it just immediately kills you upon you closing in. I feel like there should be SOME sort of counter to being instantly round removed upon spawning in.

**Comment by CCC23** [comment]
Skill issue

**Comment by Serxule** [comment]
this isnt a bug since like, its literally doing what its meant to by destroying a meteor

**Comment by Jacquerel** [comment]
Given that this is spending threat and taking time to poll a ghost, probably the meteor should just spit you out when shot and fling you into the satellite.
