### ISSUE TITLE
Tramstation engi elevator bugs

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#73341]
this elevator controller is hidden behind the glass and cant be used
![Screenshot_1](https://user-images.githubusercontent.com/53361823/217948592-6eee07f7-cac2-4ee9-9228-e865079d20ef.png)
this tile is slippery for some reason
![Screenshot_2](https://user-images.githubusercontent.com/53361823/217948867-f7b70abf-f027-4cc5-93d3-d2dc03510ab8.png)

**Comment by MMMiracles** [comment]
The elevator panel was fixed in #73323 and I can't seem to replicate the slippery tile locally and there's nothing there to actually cause a slip. I'm gonna assume it was due to someone getting the floor below wet/ and the elevator hides the fact when its down.
