### ISSUE TITLE
The RTD sprite is generally bad

### ISSUE THREAD

**Issue by KittyNoodle** [tgstation/tgstation#73377]
## Reproduction:

1.
![image](https://user-images.githubusercontent.com/78111117/218296879-b1b6d893-746a-4d85-b86a-97cfbf411ad6.png)
the trigger is see through, the area around the trigger is solid black, and completely lacks shading.

**Comment by SyncIt21** [comment]
I know it's bad and i haven't improved in spiriting since then. If you have better sprites, feel free to make a PR.

**Comment by DragonTrance** [comment]
the issue: game bad
the resolve: be the change you want to see
