### ISSUE TITLE
players' mobs' vision become bugged due to Z levels

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#73387]
Round ID: #199970

Testmerges: https://github.com/tgstation/tgstation/pull/73107

Reproduction: EDIT: F12 doesn't seem to _always_ cause the issue. At first I thought it was F12 since that broke it the first time, but later this happened to my character while just observing as a ghost.

What happens is you get a screen that looks like this:
![image](https://user-images.githubusercontent.com/16496315/218318023-539dd1a1-bb6f-4a64-a0d3-9a81e1026e31.png)

Clicking F12 again or changing Z levels, closing the game entirely and reloading, etc., doesn't seem to fix it since the issue is connected to your mob. Once you die your ghost gets normal vision. If you observe someone with the bug and tick the box to auto-observe, it'll show on your screen what they're seeing. Usually it's a handful of players every round that get this bug and it's fairly roundending since you lose the ability to interact with your character (their inventory, clothing slots, radio, hand slots, etc). Hotkeys work though.

**Comment by optimumtact** [comment]
stop pressing f12

**Comment by SinfulBliss** [comment]
> stop pressing f12

Actually I just had another round, #200032, in which this happened again without (I think) pressing F12. it was also on Icebox like before. I wasn't bugged until after I had died, then I went back into my body and it was suddenly bugged. Very odd because the bug happened to my dead body independent of my input.

Clip below showing it as well as another character that was impacted (I observed him with auto-observe ticked as a ghost, maybe that somehow bugged my mob?):

https://streamable.com/y6osxj

**Comment by TheSmallBlue** [comment]
Had this bug a while ago without even touching f12.
From what I remember a meat heretic was reviving a soulless corpse and I got rolled to be the soulless dead. I stormed sec, died, got unhusked by a mediborg, and when said mediborg revived me I had this glitch. Went down a z-level and it fixed itself.

![dreamseeker_RQr0x3NGyA](https://user-images.githubusercontent.com/24967815/218384369-2ee6822a-71d0-438b-b096-04bab7228971.png)
![dreamseeker_NAdGGOBLni](https://user-images.githubusercontent.com/24967815/218384374-6cd3c9a4-cd50-41ed-a0c3-c267319e2810.png)
![dreamseeker_VeNV8fuxVS](https://user-images.githubusercontent.com/24967815/218384375-2736d2b8-f1eb-468b-a8b3-4acb16effa21.png)

Hopefully this helps replicate it

**Comment by TheSmallBlue** [comment]
![dreamseeker_8LAbIIF2CQ](https://user-images.githubusercontent.com/24967815/218390054-f207687a-41fd-48a4-8dc9-a273feedc961.png)
![dreamseeker_clRZscIKjG](https://user-images.githubusercontent.com/24967815/218390059-15d3b583-7c71-42dd-b1f7-d296b4de5a19.png)
![dreamseeker_0ciBhMK59Y](https://user-images.githubusercontent.com/24967815/218390063-d28b72c3-df31-411f-88fe-1657246c7bfb.png)


Got an offshoot of this bug by being ran over by the tram as a cyborg and being revived. Seems like reviving is the thing that links each of these together

**Comment by Serxule** [comment]
clear your byond cache, afaik thats what causes this (i've had this problem before)

**Comment by Serxule** [comment]
infact i didnt read the PR but my point still stands, clearing byond cache has fixed this before

**Comment by TheSmallBlue** [comment]
> clear your byond cache, afaik thats what causes this (i've had this problem before)

In between those two instances I've not only cleared byond cache but also, like, reinstalled my entire OS so I don't think this is it

**Comment by LemonInTheDark** [comment]
if part 2 replicates (which it likely will) throw me up another issue report yeah?
