### ISSUE TITLE
Meson vision gives you perfect vision of lower z-levels through walls.

### ISSUE THREAD

**Issue by Gristlebee** [tgstation/tgstation#73409]
Reporting client version: 514.1589

## Round ID:
[200039](https://scrubby.melonmesa.com/round/200039)

## Reproduction:

1. Wear mesons.
2. Have a wall between you and objects on the floor below.
3. See it through the walls.

![image](https://user-images.githubusercontent.com/56049844/218397272-ff301648-5f5a-4b0d-8fe0-64a13fbdf798.png)

**Comment by ZephyrTFA** [comment]
https://github.com/tgstation/tgstation/issues/53783
