### ISSUE TITLE
Awful "message meant for OOC" detection

### ISSUE THREAD

**Issue by LSommers** [tgstation/tgstation#73419]

**Comment by LSommers** [comment]
" 📎 your message ;OH GOD HELP HELP FUCK I AM BEING BEATEN TO DEATH IN DORMS BY THE CLOWN looks like it was meant to go in OOC w-"
>reflexively click annoying popup because you are being beaten to death (fictional but plausible situation), click wrong button
>violently ICK in OCK
>bwoink
>noted
>mocked by OOC

**Comment by skylord-a52** [comment]
Please provide the exact message that caused the problem, otherwise this is impossible to fix -- I doubt the maintainers are going to remove this system entirely, but we can remove certain words from the filter easily.

**Comment by Ryusenshu** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/95751821/218764320-b9c96046-063a-46b2-82ed-6d7fbd556370.png)

Seems like a typo?
(Still pretty bad of a system that opens a popup and kicks chat into ooc because of misspellings)

**Comment by dragomagol** [comment]
I think you've got this backwards, the prompt was trying to save you from ick ocking, not causing it.

![image](https://user-images.githubusercontent.com/66640614/218793258-99d3f145-8dad-4cc2-a164-20cb082929b6.png)

**Comment by Ryusenshu** [comment]
oh that makes WAY more sense

**Comment by RikuTheKiller** [comment]
> oh that makes WAY more sense might be nice to have a timer on that

but do you really want a timer when you're being beaten to death...?

**Comment by Ryusenshu** [comment]
> > oh that makes WAY more sense might be nice to have a timer on that
> 
> but do you really want a timer when you're being beaten to death...?

a timer on the "yes" button so you dont instantly ick ock

**Comment by jlsnow301** [comment]
what if we just swapped the default to no

**Comment by LSommers** [comment]
What if there was, you know, _a check for messages starting with a ; that flags them as clearly IC_

**Comment by LSommers** [comment]
> I think you've got this backwards, the prompt was trying to save you from ick ocking, not causing it. This is what it looks like when you try to type something in OOC starting with a semicolon or colon:
> 
> ![image](https://user-images.githubusercontent.com/66640614/218793258-99d3f145-8dad-4cc2-a164-20cb082929b6.png)

I **_swear_** that it was a prompt saying that it looked like an _OOC_ message. Either way, awful.

**Comment by Ryusenshu** [comment]
> what if we just swapped the default to no

i meant it as a "can only click yes after 2 or 3 seconds pass" button

**Comment by LSommers** [comment]
What if it was only a warning instead of a "click here to fuck up immediately"
What if it was literally anything but what it is

**Comment by dragomagol** [comment]
> > what if we just swapped the default to no
> 
> i meant it as a "can only click yes after 2 or 3 seconds pass" button

That would be really annoying if I was trying to start an OOC message with `:` or `;`
I think making it auto-focus on "No" is fine

**Comment by Ryusenshu** [comment]
imo, ooc can wait two seconds, its not that there is much reason to talk fast there anyway
