### ISSUE TITLE
Expedition drones and pAIs

### ISSUE THREAD

**Issue by Krentell** [tgstation/tgstation#73417]
## Reproduction: When a pAI is put inside an expedition drone's storage, and said drone is sent to an expedition, the pAI gets sent to the room with rupee looking crystals, without any way to leave. I'm not sure if it's a certain type of expedition that triggers this, both because I was the pAI in the situation it happened in, and that this has only happened once, to me at least.

**Comment by DingleFlop** [comment]
Reproduced on a recent round on May 8
