### ISSUE TITLE
Lightgeists can't heal Toxin damage, but they can still try

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#73439]
Reporting client version: 514.1589

## Round ID:
[200147](https://scrubby.melonmesa.com/round/200147)

## Reproduction:
1. Become a sentient Lightgeist (in this case via an anomalous crystal)
2. Try to heal someone who has a single point of Toxin damage
3. Try to heal them over and over to no avail

If Lightgeists are only meant to heal Brute and Burn, then it probably shouldn't consider Toxin a valid form of damage to try and heal. Or just make them able to heal Toxin damage, seems like a weird outlier.

**Comment by Ryusenshu** [comment]
they also got progress bar for healing now, when before it was instant with a cooldown after

**Comment by IndieanaJones** [comment]
I think this is from one of the spider PRs.
