### ISSUE TITLE
Cell Charges don't drain power from energy source properly

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#73438]
## Round ID:

You can make infinite power since cells don't take a 1-1 ratio from the power soruce
## Reproduction:
Get 10 cell chargers a smes and a room with an apc 

1.Charger all cells
2. build SMES and put in the cells
3. Wait when the SMES hits 0 power
4. While you wait have another 5 cells charging
5. When the SMES hits 0 power deconstruct and put another one for effectively an infinite power source

2 is good enough but you can do this with as many as you want so many that you wont even have to replace it all shift

**Comment by Sealed101** [comment]
needs a thorough test case - cell chargers were changed to get energy from the power grid instead of the room's APC. 

separate a room from the station's grid, get some uncharged cells, get some juice in the room's powernet - the whole deal

**Comment by Pickle-Coding** [comment]
#81579 should fix it.
