### ISSUE TITLE
TRAIT_DWARF can't throw some things

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#73448]
## Reproduction:
Add TRAIT_DWARF to a mob, throw item (such as a book or baton)

https://user-images.githubusercontent.com/83487515/219184269-db129975-f9f6-4895-b2d0-35d1770db462.mp4

**Comment by the-orange-cow** [comment]
As a dwarf your mass is lower than that of the book, thus reducing your ability to displace it.  Logical example of in game physics.
