### ISSUE TITLE
Refurbished Tramstation lacking some things

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#73441]
Reporting client version: 514.1585

## Round ID:
[200165](https://scrubby.melonmesa.com/round/200165)

## Reproduction:
Play Tramstation
As a roboticist, look at the lack of a mech crowbar
As a Syndicate Battlecruiser crew, marvel at the inability to land near the station (This one's really weird, as a Pirate was able to land and reland around the station, but the Battlecruiser couldn't engage at all, could be a missing hyperspace anchor or some such.)

**Comment by AdipemDragon** [comment]
Oh i guess the battlecruiser and such being weirdly unable to land should've been its own issue, if that pr only fixes the crowbar but closes it anyway

**Comment by DATA-xPUNGED** [comment]
> Oh i guess the battlecruiser and such being weirdly unable to land should've been its own issue, if that pr only fixes the crowbar but closes it anyway

I did a mistake on saying that my PR "closes" yours, but i will try taking a look at the battleship cruiser
