### ISSUE TITLE
Cardboard golems have tongues again

### ISSUE THREAD

**Issue by rageguy505** [tgstation/tgstation#73449]
Reporting client version: 514.1589

## Round ID:
[200191](https://scrubby.melonmesa.com/round/200191)

## Testmerges:
- [Optimizes INVOKE_ASYNC by making it a macro and avoiding a proc call](https://www.github.com/tgstation/tgstation/pull/73264)

## Reproduction:
Talk as a cardboard golem/look at their organs

**Comment by san7890** [comment]
we need to unit test these fuckers NOT having tongues @CoffeeDragon16 @MrMelbert
