### ISSUE TITLE
Ninja can't hack new security consoles

### ISSUE THREAD

**Issue by rageguy505** [tgstation/tgstation#73456]
Reporting client version: 514.1589

## Round ID:
[200218](https://scrubby.melonmesa.com/round/200218)

## Testmerges:
- [Optimizes INVOKE_ASYNC by making it a macro and avoiding a proc call](https://www.github.com/tgstation/tgstation/pull/73264)

## Reproduction:
Be ninja, cant hack a security console

**Comment by Baskett55** [comment]
probably caused by #72725

**Comment by Baskett55** [comment]
i think the issue is that right clicking tries to bring up the console? im not too sure

**Comment by Ekaterina-von-Russland** [comment]
Can confirm, had this issue on my first time as ninja recently.

**Comment by remuluson2** [comment]
The issue is the action of opening a security console doesnt trigger ninja's hacking as it should and it instead opens the menu.
