### ISSUE TITLE
Disembowelled romerol infected corpses do not revive upon the transformation into the zombie.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#73465]
## Round ID:
Tested locally on a current build version.

## Reproduction:
1) Gut a person.
2) Infect them with the romerol chemical, in my test I used the zombie's claw.
3) Person will turn into a zombie, but will not rise from the dead.

**Comment by Overuseddart** [comment]
Was the zombified organ still in the zombie?

**Comment by IllotAFV** [comment]
Yes, they were still a zombie, their species was "infectious zombie".
