### ISSUE TITLE
Some, but not all, spider egg spawns broke

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#73468]
Reporting client version: 514.1589

## Round ID:
[200240](https://scrubby.melonmesa.com/round/200240)

## Reproduction:

ADMIN LOG: The enriched egg cluster didn't return anything when creating a mob, this might be broken! The use of the spawner it would have taken has been refunded.
x2

(repeated periodically through the round)

Guess some spider spawns might be broken in some way (but not all of them, many spiders exist just fine).  Didn't find any obvious associated runtimes.
Secondly this log line could be more useful ; if it indicated which egg failed we might be able to delete it / debug it / something, just telling is 'an egg' didn't work isn't great

**Comment by Jacquerel** [comment]
Did players also report eggs not working? 
On investigation it seems you can trigger this message by clicking on an egg _and then closing the radial menu without selecting a spider_, which is certainly a misleading error.

I can try fixing that to be more descriptive and then also adding a hyperlink to orbit the offending spawner?

**Comment by iprice** [comment]
> Did players also report eggs not working?

Yeah, couple of dead chat said it wasn't working, might have been a ticket.  A better debugging message may help figure this out at least, cheers.
