### ISSUE TITLE
A Revolution ban doesn't do anything

### ISSUE THREAD

**Issue by Sightld2** [tgstation/tgstation#73478]
## Round ID: Tested on 200270
So I noticed in the banning panel there's options to ban someone from either a Head Revolutionary or a normal Revolutionary. I assume a normal Rev ban is supposed to ghost you when flashed just like cult bans/conversions, but that doesn't seem to be happening. I banned myself from Head rev and normal rev but was still able to be flashed and converted. A player I banned from all antags also reported the same thing.

## Reproduction:

Step 1. Ban yourself from Revolution
Step 2. Don't get ghosted
Step 3. Enjoy your free antag

**Comment by ZephyrTFA** [comment]
duplicate of #61611
