### ISSUE TITLE
Medical Records/HUDs are missing physical/sanity status settings

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#73477]
Reporting client version: 514.1589

## Round ID:
[200271](https://scrubby.melonmesa.com/round/200271)

## Testmerges:
- [Optimizes INVOKE_ASYNC by making it a macro and avoiding a proc call](https://www.github.com/tgstation/tgstation/pull/73264)

## Reproduction:
Medical records and MedHUDs had the ability to mark people's physical and mental status in their records, however that option seems to be missing entirely from the records which is preventing that function from being used.

1. Go to a medical records computer.
2. Login
3. Select any record you wish to mess with
4. Modify everything except for the physical/mental status
OR
1. Equip MedHUDs
2. Examine the person you wish to set status of
3. Missing option to set physical/mental status

There was a couple systems which modified the mental status in the records or interacted with it, and you can't change or monitor them with it missing.

**Comment by Derpguy3** [comment]
Uncertain, but may potentially be related to the recent records refactoring #72725

**Comment by jlsnow301** [comment]
this was intentional. the functionality is basically unused or made obsolete by the monitoring console. notes was the alternative.

**Comment by Derpguy3** [comment]
There were a few systems which had used the sanity status.
- Secbots would arrest people who's sanity status was set to insane.
- Repeatedly killing crew on the Orion trail would change sanity status to watch, and send a message on both security and medical radio.
