### ISSUE TITLE
Shuttles REALLY don't like atmos heating; microwave shuttle dream on the line

### ISSUE THREAD

**Issue by DAKKA-WAAAGH** [tgstation/tgstation#73506]
## Reproduction: 
![image](https://user-images.githubusercontent.com/34065421/219857019-d623bb81-d331-44df-afa9-63cfe9f91ab5.png)

Before departure, shows connected with no pressure or temp changes.

![image](https://user-images.githubusercontent.com/34065421/219857025-625206d2-d2db-4c9d-9cf9-051be8477c03.png)

Confirmed no changes in pipes.

![image](https://user-images.githubusercontent.com/34065421/219857033-f9bc2dca-7791-421e-b72c-63a2b8c8a19c.png)

After departure, disconnects itself automatically.

![image](https://user-images.githubusercontent.com/34065421/219857037-42c59eac-b6c6-4c10-9008-d61ef0dbfb28.png)

When reconnected manually for the second time, still no pressure or temp changes.

**Comment by LemonInTheDark** [comment]
looking at the thermomachine off your branch, it isn't like, directed right
changing that appears to fix things? though I'm not 100% on that I didn't see these issues. does it not fix things fully for you?

**Comment by DAKKA-WAAAGH** [comment]
This is fixed by changing the dir, somehow. Just is what it is.
