### ISSUE TITLE
PDA Crashes when Accessing NT Software Hub

### ISSUE THREAD

**Issue by gerdus4898** [tgstation/tgstation#73501]
Reporting client version: 514.1589

## Round ID:
[200327](https://scrubby.melonmesa.com/round/200327)

## Testmerges:
- [Optimizes INVOKE_ASYNC by making it a macro and avoiding a proc call](https://www.github.com/tgstation/tgstation/pull/73264)

## Reproduction:
PDA/Consoles crashes when trying to access NT Software Hub. Found this when trying to download NT Frontier App.
1. Open PDA
2. Click "NT Software Hub"
![image](https://user-images.githubusercontent.com/20459542/219847804-6d64305e-e725-48a1-a565-c953d685dece.png)

**Comment by SyncIt21** [comment]
Duplicate of #73493

**Comment by gerdus4898** [comment]
My bad, should've had noticed that.
