### ISSUE TITLE
PDA Bugs

### ISSUE THREAD

**Issue by gerdus4898** [tgstation/tgstation#73507]
Reporting client version: 514.1589

## Round ID:
[200337](https://scrubby.melonmesa.com/round/200337)

## Testmerges:
- [Optimizes INVOKE_ASYNC by making it a macro and avoiding a proc call](https://www.github.com/tgstation/tgstation/pull/73264)

## Reproduction:
The PDA became like this after I tried downloading gas shell data from a data disk (once I minimize/close the file manager after download)
![image](https://user-images.githubusercontent.com/20459542/219857693-2f87da43-b465-4ec5-bca2-107c2c181aae.png)

**Comment by gerdus4898** [comment]
Same thing happened with console
![image](https://user-images.githubusercontent.com/20459542/219857833-a3ef7166-aff4-4bd7-a158-f64cbcb612fe.png)

**Comment by JohnFulpWillard** [comment]
![image](https://user-images.githubusercontent.com/53777086/219888732-a43cd2d4-655a-47f1-b3e4-60680dd1c10a.png)
![image](https://user-images.githubusercontent.com/53777086/219888775-3850ba34-d1bc-4b9d-88e7-58991af6e6ed.png)

I can't replicate this, did you do anything else?

**Comment by JohnFulpWillard** [comment]
https://user-images.githubusercontent.com/53777086/219891785-4a84ec86-7cc0-45f6-92c1-aea5fb3c8e47.mp4

**Comment by gerdus4898** [comment]
No, not from that ordnance data disk, I downloaded a gas shells experiment data after conducting a gas shell experiment in science (from a gray diskette that I put into the gas shells machine then ejected). The file should be named something like gas shell log or something. I believe you'd have to find someone that can do that experiment to replicate the issue.

**Comment by JohnFulpWillard** [comment]
OH

**Comment by JohnFulpWillard** [comment]
Got it
