### ISSUE TITLE
Carpet Dots are above everything else?

### ISSUE THREAD

**Issue by Cheshify** [tgstation/tgstation#73518]
## Round ID:
[200366](https://scrubby.melonmesa.com/round/200366)

## Testmerges:
Master -> [c5e57af68bdd99475198194e1a330e34eba825b6](https://www.github.com/tgstation/tgstation/commit/c5e57af68bdd99475198194e1a330e34eba825b6)

## Reproduction:
/turf/open/floor/carpet/black aren't rendering properly, the dots appear above tables, mobs, and other things 
![image](https://user-images.githubusercontent.com/73589390/219899145-0d9f847b-52fe-4960-b49c-67aeaa95a3db.png)

**Comment by ZephyrTFA** [comment]
That's a little bit cursed. @LemonInTheDark

**Comment by LemonInTheDark** [comment]
???????

**Comment by timothymtorres** [comment]
Are those dots on their own plane or something?

**Comment by LemonInTheDark** [comment]
oh my god I know what's happening

**Comment by LemonInTheDark** [comment]
This is a bit of a guess, but we do this thing where we create this mask for the lighting plane using floors, walls and space.
This lets us prevent stupid stuff showing through the darkness by lighting it up.

I think I'm doing it wrong, so the pure blackness of the carpet is fully masking the lighting plane.
Suffering

**Comment by Likteer** [comment]
@LemonInTheDark Tiles with light sources, scrubbers and vents cancel out the dots when standing on them

**Comment by LemonInTheDark** [comment]
wtf

**Comment by dragomagol** [comment]
![image](https://user-images.githubusercontent.com/66640614/220245627-e86eff1f-0a3c-4f82-9591-07a013b59319.png)

Same with foam dispensers

**Comment by LemonInTheDark** [comment]
yeah it's anything that's fullblack on the floor plane
