### ISSUE TITLE
Debrain Objective Issue

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/tgstation#7351]
Debrain objective can fail if the target's mob changes from the one it starts with.
Caused by an Admin making the player a pet in this case, but I assume things like drones and cultist summons may properly handle the changing of the mob.

Not sure if this is fixable or if there's any point, since it's most likely only caused by an admin.

**Comment by Miauw62** [comment]
This may be a dupe. We should probably disable debrain for the time being, I think it's broken.

**Comment by tedward1337** [comment]
Still an issue? @RemieRichards

**Comment by RemieRichards** [comment]
Not sure, would have to look into it again.
