### ISSUE TITLE
Ninja Adrenaline Boost cannot be used when Unconscious?

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#73521]
## Reproduction:
"It's capable of clearing any fatigue whatsoever from the user, any immobilizing effect, and can even cure total paralysis."

Be a ninja.
Make yourself unconscious.
Try to use the adrenaline boost.

Even if I make the assumption this isn't meant to undo sleeping, it still seems it should fix being unconscious, as the code explicitly has
`mod.wearer.SetUnconscious(0)`
right there in it. Seems like an oversight to me. I'm not sure how many things induce JUST unconsciousness, but Entropic Polypnium seems to.

**Comment by IndieanaJones** [comment]
I reckon that's probably because you need to actually be conscious to use the ability.

**Comment by VladinXXV** [comment]
> I reckon that's probably because you need to actually be conscious to use the ability.

yes thats my point. there are abilities you can ue when unconscious (explosive implants) and it seems like it is supposed to be one of them

**Comment by tralezab** [comment]
I'm gonna fix it
