### ISSUE TITLE
Ghosts unable to examine dark objects from a distance

### ISSUE THREAD

**Issue by Archimus12** [tgstation/tgstation#73532]
## Round ID:
[200413](https://scrubby.melonmesa.com/round/200413)

## Testmerges:
No testmerges were on Terry when I noticed the issue.

## Reproduction: 
As a ghost try to examine anything in the dark from that is further than 1 tile away from you and notice you can't examine it.
Ghosts can only examine an object when next to or if it is in light.

**Comment by timothymtorres** [comment]
Fixed by #73520
