### ISSUE TITLE
Moths Are Unable to Eat Clothing Items

### ISSUE THREAD

**Issue by RandomlyEvil** [tgstation/tgstation#73546]
Reporting client version: 514.1589

## Round ID:
[200420](https://scrubby.melonmesa.com/round/200420)

## Reproduction:
Reported by player and tested in Thunderdome.  Moths are unable to feed themselves with any of the clothing items that were tested (hats, boots, jumpsuits, etc).  Was unable to find any cloth item that would work.  Tested all with combat both on and off, no change. Normal food items still worked as expected.

**Comment by FlufflesTheDog** [comment]
Introduced by #73481
The edible component isn't directly attached to the clothes but a dummy "moth_snack" var, which fails the new in_range check
