### ISSUE TITLE
Can't examine things unless at point blank range

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#73548]
Reporting client version: 514.1589

## Round ID:
[200435](https://scrubby.melonmesa.com/round/200435)

## Reproduction:
Be in a typically dark area with mesons and a flashlight
Try to examine something one tile away, in your light
Nothing happens
![image](https://user-images.githubusercontent.com/44104681/219991521-c71fbfdc-5a41-482c-b512-41ba9f88ef19.png)

**Comment by LemonInTheDark** [comment]
Unrelated yes.
It's odd that has_nightvision is required here, since the tile should be lit by the flashlight. Something weird's going on
That error was fixed by #73520 btw
