### ISSUE TITLE
Grenades are now Weapons of Mass Destruction. 

### ISSUE THREAD

**Issue by Zytolg** [tgstation/tgstation#73554]
Live on Birdshot, which is running the latest version of tgcode as of this post.

## Testmerges:
Birdshot

## Reproduction:
>Throw any grenade into a department, and then watch in horror as the effects reach you, the clown behind you, Ian, Poly's mom, and then proceeds to punch holes from Evac all the way into Science.

**Comment by Fikou** [comment]
what?

**Comment by necromanceranne** [comment]
You're going to have to be way more elaborate here or this is an utterly useless issue.

Give us a round, give us what _kind_ of grenade this is, and  make sure there wasn't somehow additional explosives that might have caused a chain reaction.

I can tell you for a fact chem grenades can get gnarly big, so this isn't really saying much.
