### ISSUE TITLE
Most movable sources of light are broken on 515

### ISSUE THREAD

**Issue by Holoo-1** [tgstation/tgstation#73557]
## Reproduction:
0. Uptade byond from 514.1589 to 515.xxx (I tested this on 515.1600 but it happed on previous versions too)
1. Try using any movable source of light and it simply doesn't work
Some light sources(obj/item/flashlight/lamp and /obj/item/flashlight/flashdark) may work, but they update lightning location only when their location is changed (which is also not smooth)

https://user-images.githubusercontent.com/38228316/220084316-369667b8-15eb-4b35-a278-5b463a11be8f.mp4

**Comment by JohnFulpWillard** [comment]
Desk lamps have been an issue prior to all of this im pretty sure

**Comment by JohnFulpWillard** [comment]
![image](https://user-images.githubusercontent.com/53777086/220198415-64519c92-e107-415a-9515-830d808237e4.png)

I forgot to make an issue report god damn it

**Comment by san7890** [comment]
@LemonInTheDark hope this isn't something we blonked

**Comment by LemonInTheDark** [comment]
> ![image](https://user-images.githubusercontent.com/53777086/220198415-64519c92-e107-415a-9515-830d808237e4.png)
> 
> I forgot to make an issue report god damn it

Desk lamps are static lights, this means static lights are broken (if anyone says that's fine anything movable should use the movable system I'll scalp you)

**Comment by LemonInTheDark** [comment]
Overlays not working is a byond thing, we'll need to work up a test case

**Comment by LemonInTheDark** [comment]
I worked up a test case, should be fixed in 515.1603

**Comment by Mothblocks** [comment]
@LemonInTheDark Confirm?

**Comment by LemonInTheDark** [comment]
seems good to me
