### ISSUE TITLE
Black carpet looks buggy and cursed.

### ISSUE THREAD

**Issue by Helg2** [tgstation/tgstation#73561]
## Round ID:
[200464](https://scrubby.melonmesa.com/round/200464)

## Reproduction:
Place black carpet on the floor and it will look like this 
![image](https://user-images.githubusercontent.com/93882977/220128679-7bc335e2-9134-416c-a5ad-2fbcd39d338f.png)

**Comment by ZephyrTFA** [comment]
Duplicate of #73518
