### ISSUE TITLE
Fishing minigame always results in a fail.

### ISSUE THREAD

**Issue by remuluson2** [tgstation/tgstation#73585]
## Round ID:
[200543](https://scrubby.melonmesa.com/round/200543)

## Reproduction:

1. Try to fish with any rod, any type of reel or hook.
2. finish minigame
3. positive minigame result doesnt trigger, you fail to catch the fish.

**Comment by necromanceranne** [comment]
@AnturK @GoldenAlpharex We've had a reversion I guess, might be worth a unit test

**Comment by Sealed101** [comment]
kinda a dupe of #70067 ?

**Comment by Ghommie** [comment]
Dupe, and I believe we're gradually fixing the issue.
