### ISSUE TITLE
Spiders seem to not be able to extinguish themselves.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#73584]
## Round ID: [200531](https://scrubby.melonmesa.com/round/200531)
I was a spider that was lit on fire, standing still didn't work, pressing the fire icon didn't work, pressing the resistance button didn't work. The fire extinguished itself on the dead corpse of mine after some time.

**Comment by Jacquerel** [comment]
Have they ever been able to do this? It seems like this proc has only ever been implemented for carbons.
It can probably be added but that's not necessarily fixing a bug.

**Comment by IllotAFV** [comment]
#68971 PR’s body mentions spider’s ability to extinguish themselves after some time. But in that round the timer of the fire being put out seemed to be a very long one.

**Comment by Jacquerel** [comment]
Ah I see where it would have decayed faster previously than it does now, that can be fixed.
