### ISSUE TITLE
Cultists Objectives not showing up in Traitor Panel

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#73592]
Reporting client version: 514.1589

## Round ID:
[200564](https://scrubby.melonmesa.com/round/200564)

## Reproduction:

Bagil has cultists, neat, doesn't happen too often. Check a cultists Traitor Panel to see who their target is. Objective shows up as empty. Bwoinking a cultist confirms that they do infact have a target. It's just not showing up for me, for both of the original cultists their personal objective just displays EMPTY. However, a convert to the cult DID have a list of objectives on their traitor panel.

**Comment by Likteer** [comment]
What about the alert icon with the rune, in the top right corner? Is it missing also?
During the first stage, it should showcase the character and give their name when hovered over.
During the second stage, it should have a Nar'Sie over the rune and list the possible summoning locations.

Can confirm the traitor panel is empty, but I've always assumed they didn't want to disclose the summoning location before you finish the sacrifice and haven't found a workaround.

**Comment by JohnFulpWillard** [comment]
this was fixed somewhere idk I cant reproduce it anymore
