### ISSUE TITLE
Borg Synthesizer status gets stuck on status panel when module change occurs(?)

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#73594]
Reporting client version: 514.1589

## Round ID:
[200571](https://scrubby.melonmesa.com/round/200571)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)

## Reproduction:
I'm not quite sure how it got stuck on the status panel, only that I had been reset a few times. Originally engi, remoduled back to engi, before changing to medical.
![Screenshot 2023-02-22 001019](https://user-images.githubusercontent.com/85206687/220548448-8e435496-498a-4841-9f27-87efe9f2906b.png)

**Comment by Sealed101** [comment]
confirmed, synthesizers appear in the stat menu on module pick, but don't seem to be cleared on module reset

![image](https://user-images.githubusercontent.com/75863639/222122834-450b1b53-b86b-4518-8908-cebff95da5f7.png)

the following procs are used when `transform_to()` is called, and there doesn't seem to be logic in place to remove borg energy datums when a module associated with them gets removed

https://github.com/tgstation/tgstation/blob/d901e0e412cde55f88d1c7789bb514dc72f610fb/code/modules/mob/living/silicon/robot/robot_model.dm#L86-L142
