### ISSUE TITLE
Intern Scientists can spawn on Roboticist Spawn Points

### ISSUE THREAD

**Issue by Zytolg** [tgstation/tgstation#73593]
## Reproduction:

This happened on the Birdshot testmerge but can happen on any station. Intern Scientists can use up Roboticist Spawn points as their round-start insertion, but they don't have Roboticist Access. If they should happen to spawn in robotics this way, they do not have the access to leave. 

Start a new map, set the only spawn to Roboticist and try to spawn in as an Intern Scientist or Roboticist (trying to replicate this issue). Cry when you have no access.

**Comment by Sealed101** [comment]
any reoccurrences?
