### ISSUE TITLE
Observing before the round starts creates "ghost" observers (for lack of a better word), which cannot role for dynamic ghost roles

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#73622]
## Reproduction:

- Server starts.
- Click observe.
- Round starts.
- Try to execute a ghost midround.
- Notice you will not get counted as a candidate. 

```
/mob/proc/add_to_player_list()
	...
	if(!SSticker?.mode)
		return
	if(stat == DEAD)
		add_to_current_dead_players()
	else
		add_to_current_living_players()
```
`add_to_player_list` will not add mobs to living or dead player lists unless the round has started (mode is instantiated). 
This is (debatably) sensible for living mobs, but for dead players it's totally valid to observe before round starts.
This means these lists are fallible for those who read from it (`GLOB.current_observers_list` is not all observers, it is only observers who have observed after roundstart.)

**Comment by Jacquerel** [comment]
I was looking into this but got hung up on why the SSticker check is there in the first place, was it just a sanity check?
It seems that technically you can _also_ violate the living player part by joining as an observer before the round begins and then quickly finding and possessing a Regal Rat in the maintenance tunnels, which should presumably add you to the living mobs list even though the round hasn't started yet.

That said, whether we care about if a regal rat is alive or not in terms of making player count calculations... it's probably not a big deal but it is an inconsistency. Would we be better off just removing the SSticker return entirely or is it guarding against something I haven't thought of?
