### ISSUE TITLE
heretic rune blocks all objects and items on it

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#73647]
Round ID: scrubby isn’t updating but less than a day ago on Sybil

Testmerges: https://github.com/tgstation/tgstation/pull/72415

Reproduction: drag something or someone onto the rune and try to click it. you’ll click the rune instead. EVEN IF you click the object itself and not the rune, it will act as if you clicked the rune. so it’s impossible to click or move objects on a rune unless you alt click or right click the tile and select the object manually. 

in fact it’s not only objects and mobs, it’s even things like hand tele portals and such. the layering is off and it’ll have the rune layer ontop of everything i believe with no way to click in between the spaces since the spaces count as rune

**Comment by NamelessFairy** [comment]
Same issue as #72899
