### ISSUE TITLE
Plasmamen Have Hearts Again... Somehow

### ISSUE THREAD

**Issue by RikuTheKiller** [tgstation/tgstation#73640]
## Reproduction:

Yeah uh I don't think plasmamen are meant to have hearts at all. They have no blood, they haven't had hearts before and I can't see any PRs via searching that give plasmamen their hearts back. (Only one I can see is a 2020 pr that specifically REMOVED hearts from bloodless species.)

1. Open up a plasmaman via organ manipulation.
2. The plasmaman has a heart, which it shouldn't.

**Comment by Profakos** [comment]
https://github.com/tgstation/tgstation/blob/38e66c4bb28d937b5e8fc23bd70358874328426c/code/modules/mob/living/carbon/human/species.dm#L341-L347

It seems to me, that regenerate organs just continues the loop instead of deleting organs of the new species that do not exist.
