### ISSUE TITLE
Something is weird with the job selection upon the shift start.

### ISSUE THREAD

**Issue by IllotAFV** [tgstation/tgstation#73652]
## Reproduction:
In that round I had the roboticist job on "High" and the scientist job on "Medium". I didn't get the roboticist job, because all positions were taken, but instead of giving me the scientist job, which was 3/5 in the begging, it decided to apply "Return to lobby if unavailable", which wasn't a true statement, because the scientist job was still avaiable with two open positions.

**Comment by Profakos** [comment]
By default, only 3 out of 5 scientist slots are open at roundstart. So unless the server config was set to 5 roundstart slots too, this is not a bug.

**Comment by SgtHunk** [comment]
This is not a bug, there are "roundstart" slots and "total" slots. The total slot is usually higher than roundstart and is the actual capacity for the job, but on roundstart only the initial slots will be occupied and the rest will be left for latejoins.
Scientist has 3 roundstart slots but 5 total positions.

**Comment by IllotAFV** [comment]
I had no idea about this, thank you for explaining it.
