### ISSUE TITLE
Slow movement speed issue

### ISSUE THREAD

**Issue by michaelsmetsker2** [tgstation/tgstation#73676]
Reporting client version: 514.1589

## Round ID:
200867
[200867](https://scrubby.melonmesa.com/round/200867)

## Reproduction:

for the past few rounds at a certain point (current theories are slipping or intoxication) my (cook in this case) movement speed drops to a crawl, not a medical issue and i'm not walking, I have reset all key bindings as well. Issue has lasted upwards of 45 minutes and has only fixed itself once. rejoining does not fix the issue.

**Comment by michaelsmetsker2** [comment]
bug fixed at around 2:14:00 not sure what did it

**Comment by Mothblocks** [comment]
your walk key probably got stuck. press escape when this happens

**Comment by michaelsmetsker2** [comment]
it was not stuck down, i could walk and it made me even slower

**Comment by Mothblocks** [comment]
next time this happens, can you tell an admin that Mothblocks wants to see the `movespeed_modification` on your mob, and then send them this issue report to post it on?

**Comment by Vect0r2** [comment]
Yeah, that happened to me as well...
Not sure if it was the same thing, but it seemed like I was going walking speed. (It was a while ago)
