### ISSUE TITLE
khinkali cooking recipe

### ISSUE THREAD

**Issue by michaelsmetsker2** [tgstation/tgstation#73677]
Reporting client version: 514.1589

## Round ID:
[200867](https://scrubby.melonmesa.com/round/200867)

## Reproduction:

this is a simple one, when cooking raw khinkali into khinkali the recipe book says to use the microwave but you can only cook it using the griddle

**Comment by ArthuroPep** [comment]
This should be a simple Wiki fix

**Comment by ArthuroPep** [comment]
This has been fixed

**Comment by Sealed101** [comment]
the issue is in the crafting menu, there are two recipes and the microwave one is incorrect (the griddle one is lower and ive cut off the part that says about the griddle part whoops)
![image](https://user-images.githubusercontent.com/75863639/222111407-5e47c6a8-b8c5-40a7-9867-386b24710350.png)
