### ISSUE TITLE
sushi slice duplicates banana peels

### ISSUE THREAD

**Issue by michaelsmetsker2** [tgstation/tgstation#73685]
Reporting client version: 514.1589

## Round ID:
[200906](https://scrubby.melonmesa.com/round/200906)

## Reproduction:

crating a banana sushi roll makes a peel and then once cut it makes another for each slice created

![2023-02-27 11-23-38 (1)](https://user-images.githubusercontent.com/26945240/221663145-63aaac18-b1b6-4519-9cab-22f124f5a582.gif)

**Comment by Profakos** [comment]
Duplicate of #69285.

**Comment by Sealed101** [comment]
yeah, dupe of that issue at base. seems like any custom food item that can be cut into smaller pieces has a similar issue
