### ISSUE TITLE
AIs can see the job titles of people disguised using the heretic cloak of shadows if they talk.

### ISSUE THREAD

**Issue by NamelessFairy** [tgstation/tgstation#73709]
## Reproduction:

This occured when I overheard a cloaked heretic use their Mansus grasp while I was using a holopad. The name still showed as unknown as intended with cloak of shadows however the heretics job title was still shown in chat allowing me to identify who the heretic was.

**Comment by Sealed101** [comment]
AI's relay speech doesn't take the unknown trait into account anywhere apparently
relevant code:

https://github.com/tgstation/tgstation/blob/7ae677e1e0a055be697285977911c94804dbb458/code/modules/mob/living/silicon/ai/ai.dm#L866-L891

https://github.com/tgstation/tgstation/blob/7ae677e1e0a055be697285977911c94804dbb458/code/modules/antagonists/heretic/magic/shadow_cloak.dm#L137-L154
