### ISSUE TITLE
Kilo Spare Problem

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#73705]
Reporting client version: 514.1589

## Round ID:
[200955](https://scrubby.melonmesa.com/round/200955)

## Reproduction:
![image](https://user-images.githubusercontent.com/76874615/221925201-a15cffd0-0bac-4beb-98b2-4debf02590cd.png)
You can't access the Spare Captain's ID Safe without first shoving a computer aside. Climbing the table doesn't reach either.
It's centered on the wall facing south but it's truly anchored southwest instead.

**Comment by Mothblocks** [comment]
this bug comes up aaaaaaaall the time, whether its wall frames or not. we really need a good way to detect these

**Comment by Sealed101** [comment]
it could probably be accessed without moving the console by standing near the console, but it really should be moved to the table's tile with the `north` subtype
![image](https://user-images.githubusercontent.com/75863639/222566819-069aa323-8c07-4c26-a056-f06106824752.png)
