### ISSUE TITLE
freezing? issue

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#73732]
## Round ID:
nearly ever round for the past week or so

## Testmerges:
None

## Reproduction:
be doing anything in the game and occasionally the  game freezes up. where you cant see any changes, people standing still when they are actually moving for example

**Comment by LemonInTheDark** [comment]
dupe of https://github.com/tgstation/tgstation/issues/2601

**Comment by LemonInTheDark** [comment]
good to know that old specter's alive
