### ISSUE TITLE
"Scare Tactics" gone wrong - Juggernaut "Gauntlet Echo" does nothing.

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#73756]
## Reproduction:
Be cult juggernaut.
Launch your Gauntlet Echo at a noncult human, both at a distance and at point blank.
Both clearly connect and even have a blood spray effect.
The human is 100% healthy. Not so much as a little bloodloss even.

![image](https://user-images.githubusercontent.com/44104681/222653053-58e43e00-a5fb-485b-adeb-56b662bc56f8.png)

I always thought this attack was kinda weak. Wonder how long it's been like this? So much for a "devastating" attack.

**Comment by Helg2** [comment]
The issue appears to be in `basic_projectale` component or with something similar that both "Gauntlet Echo" and "Patron's reach" possess. Patron's reach has 30 toxin damage and still doesn't do any damage on hit.
https://github.com/tgstation/tgstation/blob/aff9cf1b434c7a95d156ea20108d8b2bc015083d/code/modules/antagonists/heretic/magic/rust_wave.dm#L84-L89
![image](https://user-images.githubusercontent.com/93882977/222989045-d5883dac-2cc0-478c-9cb4-f4cdaa5e9d61.png)

**Comment by VladinXXV** [comment]
> ...Well. Juggernaut / Rust wave both have `nodamage = TRUE`, so that's probably why it does no damage

how did we end up here on something that claims to be a "devastating attack"
