### ISSUE TITLE
Circumstantially, the captain's spare safe is impossible to break into or even open.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#73764]
## Reproduction:

```
/obj/item/storage/secure/safe/caps_spare
	name = "captain's spare ID safe"
	desc = "In case of emergency, do not break glass. All Captains and Acting Captains are provided with codes to access this safe. \
        It is made out of the same material as the station's Black Box and is designed to resist all conventional weaponry. \
        There appears to be a small amount of surface corrosion. It doesn't look like it could withstand much of an explosion.\
        It remains quite flush against the wall, and there only seems to be enough room to fit something as slim as an ID card."
	can_hack_open = FALSE
	armor_type = /datum/armor/safe_caps_spare
	max_integrity = 300
	color = "#ffdd33"
```

The safe suggests that it would be possible to break open utilizing an explosive, and it seems to suggest from its armor values that acid and fire should eat away at it as well, but it has a few issues that prevent them from being possible.

1) It cannot be attacked by anything that isn't interacting with its storage component, so it can't either have C-4/X-4 attached, nor can it be splashed with acid. It also has no interaction with emags, so even antagonists cannot open this. (secure storage lacks any emag interaction anyway, but worth mentioning) 
2) Since it cannot be directly attacked, trying to place explosives on the safe requires actually having an explosive capable of destroying a tiles worth of objects, rather than whatever it is attached too (like C-4 does), which means destroying the wall the safe is affixed too and then using something as strong as, say, a minibomb to blow up the safe. Acid clouds could work here too, but the wall still has to come down. Fire is...probably not possible.
3) Even if you were to destroy the safe, destroying it does not dump the content. It instead destroys the contents, thus destroying the ID.

So, actually going by the brute force method, this seems pretty undoable. You might then ask yourself 'okay, so what can I do otherwise?'

If there is a head of staff or no head of staff, that means a code paper has spawned or can be spawned via a Centcomm launch a few minutes into the shift. This is one way to get access, and those people who otherwise got the codes will probably open the safe and have the ID on them anyway.

If a captain spawned, you have two options. Get the piece of paper with the code from the captain's possessions, or get it from their memories (impossible unless you're a ling). Otherwise, mechanically, this presents particular issues if neither of these are obtainable and the captain has died. There are no additional fallbacks in place, and no real methods for antagonists (except lings) to circumvent this issue.

So the supposed method of obtaining this ID does not work, and from when I asked Timber, this may be an oversight, but I welcome him to come correct me on this.

**Comment by Profakos** [comment]
I have successfully splashed acid on the wall safe, it got destroyed by the melting and dropped the ID. The issue is that is did like 8-10 damage per splash of 30 units of fluorosulphic acid, and it has 300 integrity.

**Comment by Profakos** [comment]
I managed to destroy the safe via explosions, it did dropped the spare ID, however, it was an another abysmally slow process.

**Comment by Profakos** [comment]
Fire also worked (opened a plasma can and set it on fire), and probably acid cloud should also work as the spare ID is actually on the tile next to the wall.

**Comment by necromanceranne** [comment]
in which case I'll close the issue, I've tested it too to the same results. Maybe something fixed in the meantime.
