### ISSUE TITLE
Blob infection allows players to blob again if the ghost of a player takes on a new antag roll

### ISSUE THREAD

**Issue by Draggeru** [tgstation/tgstation#73776]
[Round ID]: # 201187

## Reproduction:
Roll blob infection, die, then take a new antag roll. Boom you can now blob again.

As far as I'm aware, if the players leave a blood sample for pod cloning they can also blob again.

**Comment by Jacquerel** [comment]
I have noticed several instances of antag datum persisting between lives recently which are likely connected. Had a paradox clone spawn with the nightmare datum which left them very confused p.n

**Comment by Sealed101** [comment]
may be related #37274

**Comment by JohnFulpWillard** [comment]
This has to do with bringing their previous mind with them when taking a new body. I swear I saw a fix PR for this but I can't find any other issue report on it.

**Comment by JohnFulpWillard** [comment]
Nevermind. Fixed by https://github.com/tgstation/tgstation/pull/73568
