### ISSUE TITLE
Prosthetic Replacement of someone's head to someone else's body makes head look like its original for this body.

### ISSUE THREAD

**Issue by Helg2** [tgstation/tgstation#73782]
## Reproduction:
![image](https://user-images.githubusercontent.com/93882977/222923562-4be65317-1d69-4457-ba9d-21d60f9bc91b.png)
Steps: 

 1. Behead both humans.
 2. Do transplantation of head to non-original body.
 3. Watch the head changing it's hair style, and maybe even something else, to the same as original for this body.
![image](https://user-images.githubusercontent.com/93882977/222923555-2ea9a176-08fc-433f-9060-b92e7818de08.png)

**Comment by Profakos** [comment]
If i see it correctly, it at least kept the proper skintone, only hair seems to not carry over. Odd.

**Comment by ChungusGamer666** [comment]
i can't wait to have to rewrite hair code to fix this
