### ISSUE TITLE
Bartender's Heirloom can be folded, losing it forever

### ISSUE THREAD

**Issue by Slurge00** [tgstation/tgstation#73790]
Reporting client version: 514.1589

## Round ID:
[201246](https://scrubby.melonmesa.com/round/201246)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)

## Reproduction:
In my round, I was bartender with the family heirloom quirk, unaware that the beanbag box of shells i spawned with was the heirloom, i put the rounds into my bandolier, and folded the box. As it turns out, folding the box means you cannot get it back, so i was stuck with a mood debuff until i ahelped about it.

**Comment by Helg2** [comment]
https://github.com/tgstation/tgstation/blob/aff9cf1b434c7a95d156ea20108d8b2bc015083d/code/modules/jobs/job_types/bartender.dm#L23-L24
Unless some strange fuckery appeared its kinda unlikely that the issue even exists.

**Comment by Helg2** [comment]
@Slurge00 Also Round ID is wrong and this round didn't even occured yet.
![image](https://user-images.githubusercontent.com/93882977/222989413-c28faa69-3a4b-478f-b2d1-2f4ee7a2bbe0.png)

**Comment by Slurge00** [comment]
> @Slurge00 Also Round ID is wrong and this round didn't even occured yet. ![image](https://user-images.githubusercontent.com/93882977/222989413-c28faa69-3a4b-478f-b2d1-2f4ee7a2bbe0.png)

![image](https://user-images.githubusercontent.com/102489377/222989816-eac615a5-68ba-486c-85b0-4560c9d76253.png)
🤷
