### ISSUE TITLE
Spider Charge failed to detonate

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#73804]
Reporting client version: 514.1589

## Round ID:
[201298](https://scrubby.melonmesa.com/round/201298)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)

## Reproduction:
0. Be a Space Ninja (this was Ice Box)
1. Go to the place where you're meant to detonate the Spider Charge (this was the Head of Staff Meeting Room)
2. Plant the Spider Charge on the wall (this was on the wall below the Robust Softdrinks)
3. Ghosts later report that the bomb was reported as being in the wrong place to detonate and fell off

**Comment by optimumtact** [comment]
area controlled things are so bad lol
