### ISSUE TITLE
Palm Trees and Coconuts are immune to singularities

### ISSUE THREAD

**Issue by Maurukas** [tgstation/tgstation#73827]
Reporting client version: 514.1589

## Round ID:
[201354](https://scrubby.melonmesa.com/round/201354)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)
- [[NO GBP] Fixes some major (and minor) issues with the birthday station trait.](https://www.github.com/tgstation/tgstation/pull/73813)

## Reproduction:

Create a singularity in the beach gateway away mission, watch as the native plantlife laughs at it:

![image](https://user-images.githubusercontent.com/66576896/223313192-eecd523b-6384-4f33-a878-95b53646c8f0.png)

**Comment by Profakos** [comment]
Turns out, this is because they are not real. They are overlays like sparkles, or beams from a medgun, which are all immune to the singularity.
Probably someone could turn them into actual trees and fruits.

**Comment by ArcaneMusic** [comment]
INDESTRUCTABLE NUTS

**Comment by LSommers** [comment]
let scrungulo enjoy his beach vacation :(
