### ISSUE TITLE
Pickle Jar does not make Pickles

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#73841]
Reporting client version: 514.1589

## Round ID:
[201400](https://scrubby.melonmesa.com/round/201400)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)
- [[NO GBP] Fixes some major (and minor) issues with the birthday station trait.](https://www.github.com/tgstation/tgstation/pull/73813)

## Reproduction:
1. Get the components for a pickle jar
2. Craft the pickle jar in the crafting menu
3. All the cucumbers used in the recipe remain as cucumbers, and do not become pickles

**Comment by san7890** [comment]
*adds this onto the pile of "pickle jar bugs", of which there are twenty more

**Comment by Sealed101** [comment]
the dreaded pickle jar issue milestone inches closer

**Comment by ZephyrTFA** [comment]
why are there so many issues for a singular item.
