### ISSUE TITLE
Early Launching Pods Is Completely Bust (again)

### ISSUE THREAD

**Issue by NamelessFairy** [tgstation/tgstation#73855]
## Reproduction:

Return of #72966

Go to an escape pod during delta alert and try to launch it, the option to do so is greyed out.

**Comment by Profakos** [comment]
![image](https://user-images.githubusercontent.com/2676196/224088457-e09f40e4-8c1b-48f3-a732-05d4da41671b.png)
Yeah that was it. I noticed this when Tram update got merged, but I completely forgot to make a fix for this. Sorry for the delay!
