### ISSUE TITLE
Space Dragon Sprites go somewhat behind space floors

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#73860]
## Round ID:

It seems the space dragon sprites go behind space grills and heat pipes and probably other things looks a  bit odd
![image](https://user-images.githubusercontent.com/84478872/223895601-a08e51e0-aa55-4808-8544-148a6bf6b63a.png)
![image](https://user-images.githubusercontent.com/84478872/223895633-86ee3587-7886-4862-8bb5-f56ae6c8ca03.png)

**Comment by Sealed101** [comment]
the issue is with the catwalks/lattices, not the dragon

![изображение](https://user-images.githubusercontent.com/75863639/224507367-6bb1b12c-158e-4284-8f9a-f15ad97a02ce.png)

**Comment by LemonInTheDark** [comment]
who broke all of mob emissive blocking wtf
