### ISSUE TITLE
Podpeople custom blood doesn't work

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#73861]
## Reproduction:

Inject replica pod with 1u of blood and rest of any reagent. On harvest podperson will have default Water blood.

**Comment by newfren** [comment]
this isn't how custom blood for pod people works, you have to crossbreed a chem from a different plant into the replica pod seeds. [iirc there's still a bunch of issues](https://github.com/tgstation/tgstation/issues/66920) is still an issue with them however

**Comment by JohnFulpWillard** [comment]
Blood depends on the plants grown next to the pods, not the reagents you injected into it.
