### ISSUE TITLE
Icebox station vault wall had poor cable management  

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#73884]
## Reproduction:

Cables under solid walls from when they were windows

![image](https://user-images.githubusercontent.com/51863163/224197269-4045167c-0a30-42b6-95fb-8d95f016a0e2.png)

@timothymtorres

**Comment by san7890** [comment]
one day we ban closed turfs from having any neighbors in maplint (this will generate a lot of work but it's good for wallening and silly stuff like this)
