### ISSUE TITLE
Supermatter Shards are an administrative nightmare

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/tgstation#7389]
They're far too easy to grief with with insufficient logging to help us catch the culprit. Mobs get deleted when they touch the shard so they lose the evidence that was stored there too. Most of this doesn't get reported to us until at least a few people are already dead to it.

My wish list for better logging tools:

- an announcement about who ordered it to the admins.
- When people are killed by it, admins should know 
  - who died
  - who touched the shard last and when
  - Who pushed the victim last
  - When they were pushed, if possible

**Comment by TheVekter** [comment]
:+1:. Nothing is worse than joining a round in progress and seeing half the station dead around a supermatter.

We really need to either regulate the purchase of one better (force Captain approval to open the crate) or remove it entirely until the new engine is in. It's just too easy to grief with.

**Comment by Tenebrosity** [comment]
It's a hugely OP object and it needs a nerf

**Comment by Steelpoint** [comment]
When I get my SM Generator PR up (Once my bloody White Ship PR is merged) I intend to put a SM Shard somewhere on the station, most likely in Engi Secure Storage.

I would also then make the SM Shard from Cargo be locked in a secure crate, likely needing the Captain's authorisation to open, or the CE's.

**Comment by TheVekter** [comment]
It already is, but I want to see it upped to Captain only. Reminder that
any idiot with an emag or emitter can bust them open.

**Comment by Lumipharon** [comment]
Keep in mind that unless you have the CE hardsuit/are a silicon, that dragging the shard around killing nerds is also suicide because the wombo combo of radiation AND fire.

If the CE is rogue and has a shard though, literally everyone is fucked.

**Comment by TheVekter** [comment]
Understood, but that still causes major issues by having players buy and open it without knowing how it works. Then we still have a giant radiation-generating asshole relic that kills people who touch it.

**Comment by Miauw62** [comment]
@tgstation/commit-access no idea what to tag this

**Comment by RemieRichards** [comment]
@Miauw62 New tag: "Administrative Issue" or "Administrative Request" :P

**Comment by Miauw62** [comment]
i did add that new tag, rr :V

**Comment by RemieRichards** [comment]
:)
