### ISSUE TITLE
Map vote and transfer vote leak into each other

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#73895]
Some crime against god and nature, there's an edge case that causes a map to show up in a transfer vote. 

![image](https://user-images.githubusercontent.com/83487515/224382592-f83473d9-6d10-42d6-9472-6d9e70e2f668.png)

![image](https://user-images.githubusercontent.com/83487515/224382610-e4212fe4-babe-4625-b489-ff70d80a2abc.png)

## Reproduction:

It is a mystery. Need to reproduce. Reported from a player as "a transfer vote passed, blob delayed it long enough that the transfer vote came up again during the shuttle ride home"

**Comment by Sealed101** [comment]
void raptor

**Comment by Sealed101** [comment]
so I'm guessing this is from a downstream, and Void Raptor is a map? and it somehow leaked into a transfer(restart round) poll? could you please clear this up in the title and description of the issue, as it is right now it's a little confusing. 

it would also need to be reproduced on our code as well

**Comment by lessthnthree** [comment]
Yeah

**Comment by Mothblocks** [comment]
tg does not have crew transfer votes

**Comment by Mothblocks** [comment]
Unless you are confident this happens with a normal restart vote but this is really sus
