### ISSUE TITLE
MOD suit's cell tooltip isn't working.

### ISSUE THREAD

**Issue by Helg2** [tgstation/tgstation#73901]
https://github.com/Helg2/tgstation
Synced to today's version.

## Reproduction:

https://github.com/tgstation/tgstation/blob/aff9cf1b434c7a95d156ea20108d8b2bc015083d/code/modules/mod/mod_core.dm#L168-L174
There is supposed to be mod-suits tooltip for cells if you have standart mod-core, but there isn't one.
![image](https://user-images.githubusercontent.com/93882977/224434467-5a15dd43-043a-485d-992b-037fbdb9658c.png)

**Comment by Sealed101** [comment]
uh
![image](https://user-images.githubusercontent.com/75863639/224437427-abfecf95-2468-42e4-ac2b-a497910622ab.png)

**Comment by Helg2** [comment]
I'm blind, ok

**Comment by Helg2** [comment]
I was just watching on the wrong part of text.
