### ISSUE TITLE
stabilized orange seems to not have a cap to its cooling rate?

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#73923]
```
/datum/status_effect/stabilized/orange
	id = "stabilizedorange"
	colour = "orange"

/datum/status_effect/stabilized/orange/tick()
	var/body_temperature_difference = owner.get_body_temp_normal(apply_change=FALSE) - owner.bodytemperature
	owner.adjust_bodytemperature(min(5, body_temperature_difference))
	if(ishuman(owner))
		var/mob/living/carbon/human/humi = owner
		humi.adjust_coretemperature(min(5, humi.get_body_temp_normal(apply_change=FALSE) - humi.coretemperature))
	return ..()
```
the rate it can heat you up by is restricted to 5C/tick, it seems, but I don't see anything that enforces a restriction to how fast it can cool you by. this might make you incredibly resistant to damage from being set on fire? needs more testing.

**Comment by Sealed101** [comment]
it's underwhelming is what it is

**Comment by ATH1909** [comment]
![oganessonVI](https://user-images.githubusercontent.com/42606352/224561524-8898ba4f-9763-4122-b57a-bfa4fcb6098a.PNG)
for what it's worth, on a skyrat round, I was able to remain on fire as a plasmaman indefinitely without taking damage thanks to the aid of a stabilized orange extact (and explicit admin permission to do this).

**Comment by Sealed101** [comment]
oh, yeah, i can't read
seems like the `min()` check should also have something to turn negative values of body temp differences (produced by high body temperatures) to positive before comparing the two values. otherwise is just picks the temperature difference which is negative in cases with being set on fire and scales much faster
