### ISSUE TITLE
armor piercing 9mm magazine invisible

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#73979]
Round ID: [201774](https://scrubby.melonmesa.com/round/201774)

Testmerges: unknown

Reproduction: buy AP 9mm round, it's invisible

sprite was invisible. it was also discounted if that matters

**Comment by ArcaneDefence** [comment]
https://github.com/tgstation/tgstation/pull/73736
Thanks, very cool.

**Comment by ArcaneDefence** [comment]
Shotgun magazines haven't used their unique sprites for two years. 
My soul weeps.
