### ISSUE TITLE
Paradox Clone of Modsuit Users Get Strange Results

### ISSUE THREAD

**Issue by IndieanaJones** [tgstation/tgstation#73973]
[Round ID]: Forgot

## Reproduction:

1. Accept Paradox Clone ghost role
2. Get selected to clone someone who is actively using a modsuit.
3. Upon spawning in, if the user of the modsuit has a low battery, the warning for it will be placed on your screen permanently.

As an aside, this also seems to completely deafen some in-game sounds for some reason. Sorry I don't have a picture or round id, but it seems rather simple to reproduce.

**Comment by san7890** [comment]
switching milestones because this isn't an issue with modsuits as much as it is this antagonist
