### ISSUE TITLE
Paradox Clone Of Someone On Different Z-Level Results in Shadow Clone

### ISSUE THREAD

**Issue by IndieanaJones** [tgstation/tgstation#73972]
[Round ID]: Forgot, sorry

## Reproduction:

1. Accept paradox clone role
2. Spawn as a paradox clone of someone on a different z-level from where you spawned
3. Become Shadow Wizard Money Gang
![ShadowWizardMoneyGangCropped](https://user-images.githubusercontent.com/47086570/224825391-631cde55-97d6-4280-8241-1c4a503ea204.png)

This result is permanent until you go to a different z-level, wherein it fixes itself.

**Comment by Sealed101** [comment]
whar
