### ISSUE TITLE
Kidnapping side objective deletes uplink implants present in other traitors.

### ISSUE THREAD

**Issue by DustanHache** [tgstation/tgstation#73985]

**Comment by EuclidianGeometer** [comment]
It does this with storage implants as well, iirc.

**Comment by DustanHache** [comment]
> Same as #59272 , except it was closed... how silly

I dont think it’s related unless bad contractor code was added blindly with the syndi kits. This has only started to happen within the last few months. used to be fine to get sent to brazil by a fellow tot.

**Comment by Jacquerel** [comment]
Kidnapping plays extremely badly with implants and nodrop items in general, as it manually loops through the mob's contents and only ignores shoes and jumpsuits.
It should probably be refactored to store your belongings in a somewhat more robust way.
