### ISSUE TITLE
Ore gathered by mining bag of holding disappears and seems to be deleted

### ISSUE THREAD

**Issue by Threeinone** [tgstation/tgstation#73998]
## Round ID: 
[201817](https://scrubby.melonmesa.com/round/201817)

## Testmerges: 
[#73502: 'Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]' by Zytolg at commit 06db3150fa](https://www.github.com/tgstation/tgstation/pull/73502)
[#73604: 'JSON Logging Take Two' by ZephyrTFA at commit 02f85c6a96](https://www.github.com/tgstation/tgstation/pull/73604)

## Reproduction: 
uncertain. But I used the red/blue cube and quantum spin inverter frequently, and even after dropping the bag I still deleted any ore I walked over, making the pick up sound effect despite not holding a miner's bag

**Comment by Gristlebee** [comment]
Were you wearing a miner modsuit at the time? Those have an internal ore storage module and it scoops into that instead of any ore bags you're carrying. It's a mixup I notice other miners have from time to time and this sounds pretty similar to that.
