### ISSUE TITLE
Floor tile decals placed on a wall in the RDs office

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#73997]
Reporting client version: 514.1589

## Round ID:
[201823](https://scrubby.melonmesa.com/round/201823)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)
- [Adds TTS to announcements made by the Captain and silicons](https://www.github.com/tgstation/tgstation/pull/72300)

## Reproduction:
directly to the right of the robotics control console is this:
![image](https://user-images.githubusercontent.com/36141254/225118163-8b75f793-2947-4554-83bc-081674b3924c.png)

**Comment by Sealed101** [comment]
birdshot station issue fixed in commit #73502 https://github.com/tgstation/tgstation/pull/73502/commits/b7f898c8ccbd8fa07e8ab72f9f8b3ae2632fd275
