### ISSUE TITLE
Creatures and Hatchlings bugged

### ISSUE THREAD

**Issue by MrSandman2000** [tgstation/tgstation#73995]
Reporting client version: 514.1589

## Round ID:
[201807](https://scrubby.melonmesa.com/round/201807)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)
- [Adds TTS to announcements made by the Captain and silicons](https://www.github.com/tgstation/tgstation/pull/72300)

## Reproduction:
The "Creature" and "Hatchling" mobs when in space move faster then they're supposed to, the no-grav drift movement and space-walk movement are combined so they go SUPER fast, to the point they are able to catch up to people using jetpacks.

**Comment by Addust** [comment]
they die to a few lasgun shots so as the V O I D M A N of terry i see this as balanced. if they are too fast for you, Z-level change away

**Comment by Sealed101** [comment]
they speed up and gain bonus damage when losing health brother + they are a basic mob as of late (which tend to act much smoother and faster), when at full health they seem to be moving not that fast

if anything's broken is that they are no longer resized to be smol
