### ISSUE TITLE
Paintings havent worked for along time (a month plus)

### ISSUE THREAD

**Issue by wawabenford** [tgstation/tgstation#74007]
## Testmerges: [#72300: 'Adds TTS to announcements made by the Captain and silicons' by Watermelon914 at commit 07b7f2c962](https://www.github.com/tgstation/tgstation/pull/72300)
[#73502: 'Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]' by Zytolg at commit 045e9bf9b6](https://www.github.com/tgstation/tgstation/pull/73502)
[#73902: 'Don't cache \ref on 515' by MrStonedOne at commit 33cf84e23b](https://www.github.com/tgstation/tgstation/pull/73902)

## Reproduction: go to the library and print a painting, or go to a picture hanging spot and cut one down, 

the world model and point box (thought bubble?) display a white square, seems like it should have been fixed a while ago

![codeer](https://user-images.githubusercontent.com/122773783/225207573-e82b9b7f-1435-41ba-ad37-73c9a24593a2.png)

**Comment by wawabenford** [comment]
the actual painting sprite is behind the canvaas, you can see it when thrown

**Comment by san7890** [comment]
sidemap issue? that's really odd

**Comment by Sealed101** [comment]
same as #71142
i have a feeling that only some painting sizes ate affected
