### ISSUE TITLE
`copy_dna` causes species hard deletes

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#74002]
## Reproduction:

#73252 made it one mob's species can be referenced by two DNA datums, this can cause species hard deletes

**Comment by Kapu1178** [comment]
Species are not at a point where they can be shared by mobs. Each mob needs its own species datum due to holding state.

**Comment by Profakos** [comment]
Would `species = new species.type` solve this issue?

**Comment by Profakos** [comment]
Sorry about my old incorrect solution, I should have used `new` in the first place.
