### ISSUE TITLE
Solo Benches have no east or west facing sprites

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#74010]
## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:
Spawn a solo bench rotated east or west, so it becomes invisible, as the related item states only have north and south facing sprites.

**Comment by lessthnthree** [comment]
I made the solo bench sprite, I don't remember which exact PR. It was used on an older layout of the tram. I was planning to do GAGS coloured benches in the next couple days, so I'll fix this.

**Comment by Profakos** [comment]
Thank you! I wanted to use them for a picnic area on a downstream map, happy to hear they will work soon.
