### ISSUE TITLE
Being crushed by a vendor can half-cure being paraplegic???

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#74025]
Reporting client version: 514.1589

## Round ID:
[201880](https://scrubby.melonmesa.com/round/201880)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)
- [Adds TTS to announcements made by the Captain and silicons](https://www.github.com/tgstation/tgstation/pull/72300)

## Reproduction:
Be a Cursed Paraplegic.
Vendor crushes you.
Only one of your legs doesn't work now.
???

I had an admin view variables the paraplegic in question and as far as I can tell their paraplegic brain trauma was completely intact??? They were able to walk around after the incident. I spent a while running Cursed Paraplegic in localhost getting crushed by vendors and could not reproduce it.

![image](https://user-images.githubusercontent.com/44104681/225435289-f4e927f9-51e4-4c89-b37c-ba5f5125b7a9.png)

Below images courtesy of the detective in question:
![image](https://user-images.githubusercontent.com/44104681/225435409-c2bc63ec-b95e-411f-9fe9-41ac3084ea9d.png)
![image](https://user-images.githubusercontent.com/44104681/225435706-b068eba4-4172-4cbe-b11e-5b1050a70605.png)
![image](https://user-images.githubusercontent.com/44104681/225435763-42e5ca21-3e35-4024-b5e2-c46c3a6bf078.png)
 
EDIT: Towards the end of the round their limbs got replaced by a bioscrambler anomaly/armor and the new legs were both correctly unable to walk. What.

**Comment by Sealed101** [comment]
yeah replacing legs cures paraplegia because it just does

was the anomaly spawned and encountered before or after the vendor incident?

**Comment by VladinXXV** [comment]
> yeah replacing legs cures paraplegia because it just does
> 
> was the anomaly spawned and encountered before or after the vendor incident?

No, no, their limbs got replaced AFTERWARDS and it re-paraplegic'd them.

**Comment by Sealed101** [comment]
that seems like a separate issue because i see a relevant runtime

still no clue as to the original paraplegia interaction

```
[2023-03-15 20:51:17.653] runtime error: Yuki Shizuka had set_usable_legs() called on them with a negative value! (code/modules/mob/living/living.dm:2175)
 - proc name:  stack trace (/proc/_stack_trace)
 -   source file: stack_trace.dm,4
 -   usr: Eris ZL (/mob/living/carbon/human)
 -   src: null
 -   usr.loc: the plating (89,46,14) (/turf/open/floor/plating)
 -   call stack:
 -  stack trace("Yuki Shizuka had set_usable_le...", "code/modules/mob/living/living...", 2175)
 - Yuki Shizuka (/mob/living/carbon/human): set usable legs(-1)
 - Yuki Shizuka (/mob/living/carbon/human): set usable legs(-1)
 - the mush right leg (/obj/item/bodypart/leg/right/mushroom): set disabled(1)
 - the mush right leg (/obj/item/bodypart/leg/right/mushroom): on paralysis trait gain(the mush right leg (/obj/item/bodypart/leg/right/mushroom), "paralysis")
 - the mush right leg (/obj/item/bodypart/leg/right/mushroom):  SendSignal("addtrait paralysis", /list (/list))
 - the mush right leg (/obj/item/bodypart/leg/right/mushroom): set owner(Yuki Shizuka (/mob/living/carbon/human))
 - the mush right leg (/obj/item/bodypart/leg/right/mushroom): try attach limb(Yuki Shizuka (/mob/living/carbon/human), 1)
 - the mush right leg (/obj/item/bodypart/leg/right/mushroom): replace limb(Yuki Shizuka (/mob/living/carbon/human), 1)
 - the reactive bioscrambling arm... (/obj/item/clothing/suit/armor/reactive/bioscrambling): bioscrambler pulse(Betelgeuse MV (/mob/living/carbon/human), 0)
 - ...
 - Eris ZL (/mob/living/carbon/human): ClickOn(Betelgeuse MV (/mob/living/carbon/human), "icon-x=14;icon-y=14;right=1;bu...")
 - Betelgeuse MV (/mob/living/carbon/human): Click(the shuttle floor (90,46,14) (/turf/open/floor/mineral/titanium/blue), "mapwindow.map", "icon-x=14;icon-y=14;right=1;bu...")
 - Betelgeuse MV (/mob/living/carbon/human):  Click(the shuttle floor (90,46,14) (/turf/open/floor/mineral/titanium/blue), "mapwindow.map", "icon-x=14;icon-y=14;right=1;bu...")
 - /datum/callback/verb_callback (/datum/callback/verb_callback): Invoke()
 - /datum/callback/verb_callback (/datum/callback/verb_callback): InvokeAsync()
 - Input (/datum/controller/subsystem/verb_manager/input): fire(0)
 - Input (/datum/controller/subsystem/verb_manager/input): fire(0)
 - Master (/datum/controller/master): RunQueue()
 - Master (/datum/controller/master): StartProcessing(0)
```
