### ISSUE TITLE
Heretic' objective bug

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#74028]
## Reproduction:

ckey: livrah. Sacrifice one Head of Staff objective didn't count this round after I sacrificed roundstart HoP. Note that he was beheaded and Revolution was over with Revs win.

**Comment by Sealed101** [comment]
relevant code:

https://github.com/tgstation/tgstation/blob/413f2413144e658b8b8f687d3834a265c84db05c/code/modules/antagonists/revolution/revolution.dm#L477-L479

https://github.com/tgstation/tgstation/blob/413f2413144e658b8b8f687d3834a265c84db05c/code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_knowledge.dm#L186-L197

the defib blacklist trait doesn't seem to affect the sacrifice process of a head, however, sacrificing relies on the mind (and role) being present. perhaps DNRing affected it somehow?

**Comment by blackdav123** [comment]
https://github.com/tgstation/tgstation/issues/73236 possibly related as I had a similar problem with saccing a head post revs
