### ISSUE TITLE
Tram xenobio bz pen disconnected from the rest of xenobio

### ISSUE THREAD

**Issue by Elli-Skala** [tgstation/tgstation#74050]
Tram xenobio's bz pen made for strong slimes/the occasional changling/xenos are in a different area of the top floor 

Unlike any other startion this means to move slimes to the bz pen you have to manually drag the slime up a ladder, build a second xenobio console in the room, and then pick the slime up again a second time with the new console to drop them into the pen

**Comment by Sealed101** [comment]
do the current tram consoles not have a button to switch the zlevel?
