### ISSUE TITLE
Entities that shouldn't be affected by defibrillators are

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#74056]
## Round ID:

![image](https://user-images.githubusercontent.com/84478872/225760959-e96c0af5-eee8-4ce2-91a2-b5de41dc2111.jpeg)

## Reproduction:
Be a slime or a golem with no heart or nerve tissues and get robusted by a combat defibrillator or revive people without a heart using a defibrillator

**Comment by Sealed101** [comment]
the heart revival claim is very wild don't go around spreading misinfo

defib disarm/harm actions apply stamina loss/knockdown and damage/paralyze/a heart attack if a heart is present, respectively.

i don't really care but judging by the file history going back to 2015-ish it was somewhat always the case so probably intended, the shock isn't directed at the heart but the nerves in general

https://github.com/tgstation/tgstation/blob/ee1f1bfc3ef53f71b5c2774d25df1a6c3cf447cb/code/game/objects/items/defib.dm#L531-L588

**Comment by SethLafuente** [comment]
> the heart revival claim is very wild don't go around spreading misinfo
> 
> 
> 
> defib disarm/harm actions apply stamina loss/knockdown and damage/paralyze/a heart attack if a heart is present, respectively.
> 
> 
> 
> i don't really care but judging by the file history going back to 2015-ish it was somewhat always the case so probably intended, the shock isn't directed at the heart but the nerves in general
> 
> 
> 
> https://github.com/tgstation/tgstation/blob/ee1f1bfc3ef53f71b5c2774d25df1a6c3cf447cb/code/game/objects/items/defib.dm#L531-L588

Alright my bad but for creatures without nerves like golems and slime people?

**Comment by Sealed101** [comment]
nerves are non-existent, everyone gets the zaps and paralyze/stamina loss, there isn't and has never been anything like that

**Comment by SethLafuente** [comment]
Things without nerves or hearts probably shouldn't be affected by combat defibrillators but fair enough closing this
