### ISSUE TITLE
Bone talisman cannot be attached to bone armor

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#74058]
Reporting client version: 514.1589

## Round ID:
[201954](https://scrubby.melonmesa.com/round/201954)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)

## Reproduction:
Craft bone armor, then craft a bone talisman and attempt to attach it to bone armor
cannot attach it to bone armor, can only attach it to your suit, which according to the wiki does nothing

 >Attached to bone armor, provides a small boost to base protection but a massive boost to bomb and biological protection. (Useless if worn as an accessory, as those don't provide protection)

page im taking from [https://tgstation13.org/wiki/Ashwalkers](https://tgstation13.org/wiki/Ashwalkers)

**Comment by Jackal-boop** [comment]
The talisman can purposefully only be attached to suits I believe. and doing so does grant defenses

**Comment by ZAMODA** [comment]
i thought badges were counted as an accessory though?

**Comment by Sealed101** [comment]
wiki is lying, go figure

**Comment by Sealed101** [comment]
unless it isn't and we've been gaslit
