### ISSUE TITLE
McGriff drags his bed with him when chasing a felinid

### ISSUE THREAD

**Issue by plutori** [tgstation/tgstation#74082]
Reporting client version: 514.1589

## Round ID:
[202032](https://scrubby.melonmesa.com/round/202032)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)

## Reproduction: Dogs, which includes McGriff, will growl and chase felinids. Apparently, this will happen even if mcgriff is buckled to his bed. He will simply slide across the floor while attached to his bed. Although it is adorable, it is probably unintended behavior.

Steps to reproduce:

1. Be a felinid.
2. Exist in McGriff's vicinity while he is buckled to his bed.
3. Walk away, but not too far away, so he chases you.

**Comment by Sealed101** [comment]
iirc the pet beds are supposed to not be a bolted down structure, but a mob buckled to it should definitely not be able to move with the bed still on its butt

**Comment by LemonInTheDark** [comment]
the dog should bark at you, with some flavor text about being too comfy to move

**Comment by Bobthe28th** [comment]
Also moves the bed to catch objects thrown
