### ISSUE TITLE
Plasmamen Race is Mindshield Resistant / Unimplantable

### ISSUE THREAD

**Issue by ophaq** [tgstation/tgstation#74080]
## Reproduction:
Try implanting a plasmaman with a mind shield and it will resist it. The bug was tested in round, and confirmed by admin testing too. Not sure how or why this was cause be any previous merges.

**Comment by Sealed101** [comment]
are you sure you didn't just try to implant a headrev

**Comment by Jacquerel** [comment]
No I think I broke this in #74029, easy to fix

**Comment by ophaq** [comment]
> are you sure you didn't just try to implant a headrev

This instance happened where I was playing a plasmaman and had revs turned off. The warden tried to implant me and I didn't move and decided to kill me instantly because I was a potential head rev when I wasn't. Later on an admin and I tested it it out and found out it was plasmamen themselves that were bugged.
