### ISSUE TITLE
Cryotubes rid you of sight, suck nearby people in and make you temporarily nonexistant

### ISSUE THREAD

**Issue by IlyaSmyichkov55** [tgstation/tgstation#74088]
I made a cryotube, put some co2 in and put some 10u sulfuric acid 10u welding fuel and 5u mercurium mix. I get in (only atleast 1 burn/brute damage or higher works), helpers turn it on and after a while i get SPEWED out of the cryo tube while my camera is still locked in at the cryo tube with that darkness overlay. I am confused, deconstruct the tube and.... DARKNESS. VOID. NOTHING IS VISIBLE. after i get put into another cryo tube/locker/whatever gives you darkness overlay, WOILA! vision returns! And if a person stands at the place where you will be ejected, they get sucked in instead of you! And guess what? The cryo cell says 'No occupant detected'!!! What the fuck?

**Comment by Sealed101** [comment]
closing in favor of #74092 as that one describes the issue more clearly, mercury is shitfuck
