### ISSUE TITLE
Crafting using an Integrated Welder can consume the Integrated Welder

### ISSUE THREAD

**Issue by SansSarif** [tgstation/tgstation#74081]
## Round ID:
N/A
[Round ID]:
 n/a - on a downstream [`here`](https://github.com/lizardqueenlexi/orbstation)

## Reproduction: 
1) install the integrated toolset implant in either arm.
2) spawn an ancient engine
3) craft a "house edge" with 1 welding tool (not in-hand) & the integrated welder

in my test, this consumed the integrated welder in your arm but left the non-integrated welder alone. as you can see in the screenshot below, the integrated welder is no longer available to choose.

![image](https://user-images.githubusercontent.com/77178736/226085280-a80b4032-a3dc-45d7-80c8-01ce4794e67f.png)

**Comment by lizardqueenlexi** [comment]
Replicated successfully on tgstation code.
