### ISSUE TITLE
Weird mercury induced cryo tube escape

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#74092]
Reporting client version: 514.1589

## Round ID:
[202066](https://scrubby.melonmesa.com/round/202066)

## Reproduction:

Spawn a cryo tube
Stick 10u mercury in yourself
Close yourself in the cryo tube

The random movement of mercury will free your mob, which you can then move, but your camera is locked on the cryo tube.

![image](https://user-images.githubusercontent.com/3789327/226134279-a961c314-91b2-461c-81f0-74d0af6ba218.png)

Interestingly does NOT happen with lithium, which also causes random movement, so I guess rebase mercury's behaviour on lithium (?)

**Comment by Sealed101** [comment]
relevant code:

https://github.com/tgstation/tgstation/blob/6a8fbc5bea5bfbf45421ecc78fb16cf921fe458a/code/modules/reagents/chemistry/reagents/other_reagents.dm#L900-L913

https://github.com/tgstation/tgstation/blob/6a8fbc5bea5bfbf45421ecc78fb16cf921fe458a/code/modules/reagents/chemistry/reagents/other_reagents.dm#L1020-L1034

related issue - #40435

we should probably implement the same sanity check for mob's loc to be a turf in every other instance of forced movement and not just the chemicals
