### ISSUE TITLE
Pyro anomalies can spawn in the bomb testing region

### ISSUE THREAD

**Issue by jlsnow301** [tgstation/tgstation#74108]
## Round ID:
[202091](https://scrubby.melonmesa.com/round/202091)

## Testmerges:
any

## Reproduction:
pyro anomaly slimes can spawn in the bomb testing region, which they cannot escape.

**Comment by Sealed101** [comment]
just adding the toxins test site area to the blacklist should do the trick

https://github.com/tgstation/tgstation/blob/d635971eac1c0888b8685cfe26427142d21009b0/code/modules/events/anomaly/anomaly_placer.dm#L56-L68

**Comment by Jackal-boop** [comment]
You can also be teleported to the bomb test site when breaking a heretic blade I believe
