### ISSUE TITLE
Paradox clones of someone who's handcuffed are also handcuffed but not actually

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#74122]
Reporting client version: 514.1589

## Round ID:
[202125](https://scrubby.melonmesa.com/round/202125)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)

The game made a paradox clone of someone who we think was handcuffed at the time. It seemed to copy over the state of being handcuffed to the clone, but they weren't actually wearing handcuffs. Still unable to actually pick up anything. Only thing that fixed it was putting handcuffs on the person then removing them.

**Comment by IndieanaJones** [comment]
Getting the vibe this is related to #73973. I think statuses caused by certain equipped items get carried over onto Paradox Clones despite not having said equipped items themselves.
