### ISSUE TITLE
Brains are getting sent to the debug room

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#74126]
Reporting client version: 514.1589

## Round ID:
[202141](https://scrubby.melonmesa.com/round/202141)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)

## Reproduction:
ADMIN LOG: [MercuryArrow] was found to have no .loc with an attached client, if the cause is unknown it would be wise to ask how this was accomplished.

DEAD: Miria Monteith says, "WHY DOES MY BRAIN KEEP BEING SENT TO THE SHADOW REALM"
DEAD: STAFF (Dragomagol) says, "what did you do? "
DEAD: Miria Monteith says, "Just head my head swap surgery done with Miria like I do sometimes onto a skeleton"
DEAD: Miria Monteith says, "and somehow when the head got reattached, it sent my brain to the Bug Room"
DEAD: Miria Monteith says, "Something similar happened when I got gibbed in a round this morning"

**Comment by CocaColaTastesGood** [comment]
> Maybe #73026 ?

I've seen this bug on every ss13 server. Heads being removed seems to sometimes teleport both the brain and the brainmob(sometimes it's still alive and able to talk) to a very specific seemingly random location.

**Comment by dragomagol** [comment]
Happened again in round 202234

Reported by a player:
`After medical borg took my head and cutted brain teleported to debug room that didn't know it's glitched `
