### ISSUE TITLE
Paradox Clone needs to desperately not use volatile admin only duplication code 

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#74124]
## Reproduction:

```
/datum/dynamic_ruleset/midround/from_ghosts/paradox_clone/generate_ruleset_body(mob/applicant)
	...
	var/mob/living/carbon/human/clone = duplicate_object(clone_victim, pick(possible_spawns))
```
Duplicate object is not meant to be used in regular code and this creates a horrendous amount of issues, It needs to be replaced with a better method of copying, one simultaneously less thorough and more deliberate with what it wants to copy. 

Related issues: #74122 , #73973 , #73972 , Probably #72437 , #73352 , and more than likely more in the future

@Shadyyy66

**Comment by Mothblocks** [comment]
:+1: I have said this as well
