### ISSUE TITLE
Cargo Requisition Forms no longer printing from any source

### ISSUE THREAD

**Issue by OrionTheFox** [tgstation/tgstation#74133]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Go to Cargo
Request any item from cargo
Purchase any item using the cargo budget
Express-order any item through the express console
Put an order in via the IRN app

Observe, no paper.

Every single one of these instances calls generateRequisition() but something is wrong with them.
Theres no issue downstream with an entire separate call of this proc, but on a private clean-TG server nothing prints from the ones up here.

**Comment by SyncIt21** [comment]
Paper is printed only after cargo confirms the order and calls the shuttle in their supply console and not for any other request console. This was removed because it caused a lot of paper mess, and nobody did anything with those papers anyway.

**Comment by SyncIt21** [comment]
I think i did it in #72423

**Comment by OrionTheFox** [comment]
Now there's no way for Cargo to track who orders what though, nor time of the order. The point of the Requisition forms were to make sure that non-departmental and non-Cargo orders had a trail back to where they came from, not to be a Manifest.
Removing it from the non-Request sources is valid, but a full removal seems over the top.

**Comment by SyncIt21** [comment]
> Now there's no way for Cargo to track who orders what though, nor time of the order. The point of the Requisition forms were to make sure that non-departmental and non-Cargo orders had a trail back to where they came from, not to be a Manifest. Removing it from the non-Request sources is valid, but a full removal seems over the top.

Let's be honest. nobody cares enough in a real round to track what orders came from where, they see it as a piece of paper and throw it down the shoot, or probably burn it for ash which can be used in chemistry or in the kitchen for BBQ Sause. 
Is cargo's job to keep track what they order in their console, they can store their Requisition from either in a folder/security drawer if they care enough (which i assure you they won't) or throw in the trash/recycler(which i assure you they will).
I don't know if enough people want the form back then i'll do it but realistically no one cares really.

**Comment by SyncIt21** [comment]
> Not mentioned in the changelog 😔

My bad, well now we know
