### ISSUE TITLE
You can burn your hands on smashed light bulbs.

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#74130]
Reporting client version: 514.1589

## Round ID:
[202149](https://scrubby.melonmesa.com/round/202149)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)

## Reproduction:
I'm not sure how this happened specifically, but these lights broke following an electrical storm. I was able to take other broken lights out of other fixtures, but the ones in question seem to keep burning hands.
![Screenshot 2023-03-19 232324](https://user-images.githubusercontent.com/85206687/226253850-d829009a-3293-4321-afdb-184aac9d9657.png)
![Screenshot 2023-03-19 232354](https://user-images.githubusercontent.com/85206687/226253867-d00db21e-eddd-443f-ad63-6d49be4860fc.png)
1. Find/Smash a (broken)light fixture.
2. Reach out to remove the broken bulb.
3. Scorch your hand horrifically.

**Comment by Derpguy3** [comment]
I had this occur again in a recent round. Seems to have been during the blackout station trait? (The one where all the lights are broken.)
![image](https://github.com/tgstation/tgstation/assets/85206687/fe3c5265-1545-4844-9bb1-ba3198a47bcd)
![image](https://github.com/tgstation/tgstation/assets/85206687/9525d211-7f46-47a5-98ab-f7a7b60756bf)

Round ID: 224480
Client Version: 515.1630


Test Merges
[#81231: 'A red spy has entered the base: Adds Spies, a roundstart antagonist inspired by Goonstation's Spy-Thief' by MrMelbert at commit 33778691b3](https://www.github.com/tgstation/tgstation/pull/81231)
[#81089: 'Temp keybinds patch for 515.1628' by MrStonedOne at commit 45649ea7a5](https://www.github.com/tgstation/tgstation/pull/81089)
[#81477: 'Comprehensive frame refactor to fix being unable to thwack frames with brute force to break them' by MrMelbert at commit 3149c449ad](https://www.github.com/tgstation/tgstation/pull/81477)

**Comment by Sadboysuss** [comment]
couldn't reproduce on latest master
