### ISSUE TITLE
Being able to succumb to death while healthy

### ISSUE THREAD

**Issue by Altertine** [tgstation/tgstation#74149]
## Reproduction: I was put into crit after fighting a xeno Praetorian and healed by a mediborg with chems. After wandering around for a bit I noticed the option was still there and placed myself in front of medbay to test if it was going to kill me. (Spoiler: It did) I assume it only dealt Oxy damage to me cause I came back to my previous state immediately after being revived due to having self-resp. Note: During the xeno fight I was hit with acid I believe and then slashed with brute damage, I don't think I took any other damage than that after.
![image](https://user-images.githubusercontent.com/128440369/226501437-ce6f4325-caff-44e8-a0df-40d1a3fca0b5.png)

**Comment by wawabenford** [comment]
yea its just kinda been happening

**Comment by the-orange-cow** [comment]
Happened to me on numerous rounds yesterday, although I didn't click it to see if it would kill me.

**Comment by Mooshimi** [comment]
It works if you try it. I tested this round 202805 when I got it. Went into crit, did not fully die. Healed and noticed succumb button. Tried with message "YEET". Died at full health(?) in front of a confused CMO.

**Comment by Profakos** [comment]
![image](https://user-images.githubusercontent.com/2676196/230184663-12caa953-6a4f-412c-92b0-491e204cf1d9.png)
Debugged a bit. The critical condition trait was never removed.
