### ISSUE TITLE
[BUG] MODsuit core removal causes the suit's missing cell alert to be permanent, making it unable to charge

### ISSUE THREAD

**Issue by AverageUser67** [tgstation/tgstation#74148]
## Round ID:
[202196](https://scrubby.melonmesa.com/round/202196)

## Testmerges:
None (that I know of).

## Reproduction:

Exactly what it says on the tin.
Step 1: make MODsuit, standard plating
Step 2: open cover and pry out core
Step 3: notice the missing cell alert
Step 4: put core back in
Step 5: missing cell alert is still there and you can't charge the suit
Step 6: mfw

**Comment by Sealed101** [comment]
this is not fuck-worthy

**Comment by SyncIt21** [comment]
Removing the mod core also drops the cell so it makes sense why it shows you the alert. Maybe the cell got dropped behind the suit so you didn't see it?

https://user-images.githubusercontent.com/110812394/226639462-8f0a11a3-dbcf-41f4-8aa2-cfbcbe1c6f3e.mp4

**Comment by Sealed101** [comment]
ok let me clear this up:
a worn MODsuit with no core installed will produce a screen alert that says you don't have a _core_ installed.
installing the core only will change the alert, mentioning the lack of a _power cell_. the core by itself doesn't store the charge, you need to install a power cell.
installing a cell clears the screen alert
