### ISSUE TITLE
Organic space suit does not regulate oxygen needs as advertised.

### ISSUE THREAD

**Issue by blackdav123** [tgstation/tgstation#74168]
Reporting client version: 514.1589

## Round ID:
[202258](https://scrubby.melonmesa.com/round/202258)

## Reproduction:
The description for the changeling's ability claims it regulates the oxygen needs, but this does not work as advertised. Oxygen is not taken care of and other gases can also pose an issue resulting in space changelings dying repeatedly as they scramble to find an airlock.

**Comment by ATH1909** [comment]
I have a hunch that this is because salbutamol got reworked semi-recently to only work on species that breathe oxygen. What species were you disguised as when this happened?

**Comment by blackdav123** [comment]
> I have a hunch that this is because salbutamol got reworked semi-recently to only work on species that breathe oxygen. What species were you disguised as when this happened?
> 
> Either that or you thought you were choking to death but were actually outhealing it (as intended).

I was disguised as a default human that meteor-changelings are assigned. I was definitely dying (or at least being forced unconcious via oxyloss) because it took a good 6 or so revives to make it into the station on icebox.

The atmosphere was both too low in oxygen and too high in CO2 to breathe for anyone normal but as I said the description of the ability implies you wouldnt be fucked over by gases and the lack of gases
