### ISSUE TITLE
Shuttles cause Signal Overrides after #73920

### ISSUE THREAD

**Issue by dwasint** [tgstation/tgstation#74172]
## Round ID:
This was originally found on Monkestation2.0:https://github.com/Monkestation/Monkestation2.0
Tested on Stock TG afterwards
![image](https://user-images.githubusercontent.com/82520990/226809493-4ae41bcb-6762-4873-b3ef-ad7ecbe6635c.png)

## Reproduction:
The re-production steps are pretty easy, late join as anyone so the shuttle docks
Watch as runtimes appear
This would also work with anything else that moves without really moving

**Comment by Mothblocks** [comment]
It's because it registers to attack_robot but doesn't unregister it

**Comment by Time-Green** [comment]
Turfs don’t get their signals cleaned because you can only ever replace them, and you’ll need to do it manually

**Comment by Mothblocks** [comment]
It does, but it doesn't clear attack_robot because it was added later on

**Comment by Time-Green** [comment]
> It does, but it doesn't clear attack_robot because it was added later on

Potato tomato
