### ISSUE TITLE
Body purist quirk hates being a headrev

### ISSUE THREAD

**Issue by blackdav123** [tgstation/tgstation#74180]
Reporting client version: 514.1589

## Round ID:
[202309](https://scrubby.melonmesa.com/round/202309)

## Reproduction:
After becoming a provocateur my mood quickly tanked as the antag mood buff was no match for body purist getting pissy. After revs ended suddenly the quirk was no longer acting up and everything was fine.

The quirk should probably exclude whatever being a headrev gives you.

**Comment by san7890** [comment]
i think headrevs give you an implant for huds?

**Comment by Sealed101** [comment]
they do get an implant for huds
