### ISSUE TITLE
Firelocks have a chance to be permanently triggered.

### ISSUE THREAD

**Issue by Pickle-Coding** [tgstation/tgstation#74207]
## Reproduction:
Firelocks get triggered from the air cooling and rushing into space from a breach. Throw metal foam like a hero to seal the breach. After fixing the air then removing excess metal foam, some firelocks did not clear, ever, and had the blue lights.

I am assuming the firelocks that were broken are the ones that had the metal foam break after the air was fixed. They only got cleared when I deconstructed then reconstructed them.

**Comment by Ryusenshu** [comment]
While i dont know how it looked for you, i kinda noticed (in other rounds) that firelocks might be checking atmos in walls or windows again

it was a bug a while back and might have reappeared [#67491](https://github.com/tgstation/tgstation/issues/67491)

**Comment by TheVekter** [comment]
I'm still seeing fucking fire alarms refusing to clear, but not this specific bug. Open up a new one if it continues.
