### ISSUE TITLE
Silicons are unable to open/close cyborg rechargers

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#74213]
Reporting client version: 514.1589

## Round ID:
[202394](https://scrubby.melonmesa.com/round/202394)

## Testmerges:
- [New Cosmic Heretic Path DLC](https://www.github.com/tgstation/tgstation/pull/73915)

## Reproduction:
This bug is making it physically impossible without outside help, to recharge, resupply, and repair cyborgs. Neither the AI or cyborgs are able to interact with them. This is very detrimental to cyborgs.

1. Be an AI or a cyborg.
2. Find a cyborg charger
3. Attempt to open/close it, and charge from it.
4. Fail to close it, and fail to charge from it.

Also encountered this bug on round 202392

**Comment by CMDR-Gungnir** [comment]
It's not just Borgs having this issue. Last round on Manuel, organics couldn't either.
