### ISSUE TITLE
Skillsoft station trapping a person & Going invisible/lacking sprite

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#74216]
Reporting client version: 514.1589

## Round ID:
[202397](https://scrubby.melonmesa.com/round/202397)

## Testmerges:
- [New Cosmic Heretic Path DLC](https://www.github.com/tgstation/tgstation/pull/73915)

## Reproduction:
Not sure how to really reproduce the issue, but here's what was said to have occurred.
1. Person went into the Skillsoft machine, door closed.
2. They tried to get in, and the sprite disappeared and trapped them
3. They were physically unable to get out of the machine, without somebody breaking the machine.

The skillsoft machine, when interacted with kept flashing between closed W/ person and invisible sprite (Needed to alt click the tile to interact with it while invisible).
![Screenshot 2023-03-24 005959](https://user-images.githubusercontent.com/85206687/227449944-24b7253e-dec5-4afa-8142-dd620774ffed.png)

**Comment by SyncIt21** [comment]
Will be fixed by #74215
