### ISSUE TITLE
Active Turfs on something

### ISSUE THREAD

**Issue by Rex9001** [tgstation/tgstation#74245]
Reporting client version: 514.1589

## Round ID:
[202498](https://scrubby.melonmesa.com/round/202498)

## Testmerges:
- [New Cosmic Heretic Path DLC](https://www.github.com/tgstation/tgstation/pull/73915)

## Reproduction:
Well joining the round on metastation whilst the server was starting I saw that there were some AT turfs
![Screenshot 2023-03-25 190831](https://user-images.githubusercontent.com/120136161/227734336-ed2f9238-3ca0-4e6e-a559-98bf59670869.png)

**Comment by LemonInTheDark** [comment]
we should really log active turfs better
