### ISSUE TITLE
Humans on the derelict are killed by a nuclear explosion

### ISSUE THREAD

**Issue by Chocobro** [tgstation/tgstation#7424]
pretty sure this doesn't happen for the centcomm and shuttle transit z-levels. not 100% certain.

**Comment by PKPenguin321** [comment]
Killed or knocked down indefinitely?

**Comment by SconesC** [comment]
also happens to mining

**Comment by Dorsisdwarf** [comment]
dupe/parent dupe of #7778 

One of these needs to be closed.

**Comment by phil235** [comment]
The other one has already been closed.

**Comment by Dorsisdwarf** [comment]
Is this still in effect?

**Comment by Jalleo** [comment]
Is this connected to the honk nuke going off by any chance? As in everyone is actually buckled to a invisible bed which dosent exist on any z?

**Comment by Chocobro** [comment]
@Jalleo not that i'm aware of. consider that this issue report is ancient

**Comment by KorPhaeron** [comment]
This doesn't happen anymore
