### ISSUE TITLE
Sentient Disease "vomit" symptom not working

### ISSUE THREAD

**Issue by nukularpower** [tgstation/tgstation#74262]
Hello,

I've gone two rounds as sentient disease lately.  Both times I took vomitting, but neither time did a single person ever vomit.

Thats pretty much it - thanks!

**Comment by DrDiasyl** [comment]
_But that's just what I think, maybe there is something I'm missing_

**Comment by ATH1909** [comment]
oh god

**Comment by Sealed101** [comment]
sentient disease has been retired as of #83453
