### ISSUE TITLE
Zero Gravity Effects With Gravity

### ISSUE THREAD

**Issue by Slurge00** [tgstation/tgstation#74274]
Reporting client version: 514.1589

## Round ID:
[202562](https://scrubby.melonmesa.com/round/202562)

## Testmerges:
- [Reagent soup / Soup rework / Stoves - A kitchen expansion](https://www.github.com/tgstation/tgstation/pull/74205)

## Reproduction:
After a Gravnospheric anomaly happened, and the grav gen reset, people were still "floating" and the icon was still there.  Gravity was functioning as normal.
![image](https://user-images.githubusercontent.com/102489377/227797684-6dbffc69-e273-437b-b235-84e0e7ab65b0.png)
![image](https://user-images.githubusercontent.com/102489377/227797705-3e01615a-d51e-4ffc-8a99-edfa4348c617.png)

**Comment by JohnFulpWillard** [comment]
@LemonInTheDark
