### ISSUE TITLE
Anti Gravity module only activates when you change areas?

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#74271]
## Reproduction:
1. Build any mod suit with anti gravity module & ion jetpack module so you can hover around with no gravity.
2. Watch the video

https://user-images.githubusercontent.com/110812394/227792949-1b0c003d-d0d3-4715-8bba-e63aa0ff5f33.mp4

If i want to activate my anti gravity module in lavaland now i literarly have to take a shuttle back to the station to get it activated and then take another shuttle back again to lavaland, 

Broken in #74084

**Comment by SyncIt21** [comment]
CC @LemonInTheDark

**Comment by LemonInTheDark** [comment]
what the fuck man
