### ISSUE TITLE
You can step on shards of glass while there's no gravity.

### ISSUE THREAD

**Issue by orthography** [tgstation/tgstation#74272]
## Testmerges:

[#73915: 'New Cosmic Heretic Path DLC' by Comxy at commit 2ff76ae6c5](https://www.github.com/tgstation/tgstation/pull/73915)
## Reproduction:
With the gravity gone for whatever purpose,, go over glass with no shoes on, you'll collapse from stepping on glass even though you're floating.

**Comment by Helg2** [comment]
Punji sticks and beartraps have the same issue.

**Comment by san7890** [comment]
did this happen pre-#74084?
