### ISSUE TITLE
Ref can smack the welding tank on that one maint basketball map.

### ISSUE THREAD

**Issue by captainfrost20** [tgstation/tgstation#74286]
So that basketball map in maint, I dont know its name. It has birdboat and all that. A ref can smack that welding tank in the arena with the welding tool from the emergency tool box and space the whole thing

## Reproduction:
Boot up a round of good ole b-ball and smack that welding tank.

**Comment by timothymtorres** [comment]
So that map is the Greytide Worldwide home court.  When I placed that welding tank there, I thought the floors on centcomm were indestructible but it looks like I was wrong.
