### ISSUE TITLE
soo my brain is in debug room!

### ISSUE THREAD

**Issue by StevieTV123** [tgstation/tgstation#74328]
## Round ID:
202688

[Round ID]:  202688

i was a syndicate i got caught and cuffed i was downed while cuffed and was beheaded at the coordinates shuttle hallway (194,177,3))  i don't know if they took my brain out with the sword it didn't seem like they did but when i clicked the view body button in the ghost menu at the bottom of the screen my bran was in the debug room also i was a goliath mutation who had my right arm replaced from the goliath arm to cyborg arm

**Comment by Jacquerel** [comment]
Duplicate of #74326
