### ISSUE TITLE
Shake() does not stop SpinAnimation()

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#74323]
Reporting client version: 514.1589

## Round ID:
[202670](https://scrubby.melonmesa.com/round/202670)

## Testmerges:
- [Reagent soup / Soup rework / Stoves - A kitchen expansion](https://www.github.com/tgstation/tgstation/pull/74205)

## Reproduction:
See spinning person. Try to call Shake() to make them stop. They don't stop. 
Used to work, not sure if that's part of some intentional change or not.
But it may have resulted in one of the admins having their screen forever stuck in spin mode. Possibly.

**Comment by Sealed101** [comment]
shake used to not work prior to #73480 at all, unless you are talking about some other proc

**Comment by Striders13** [comment]
> shake used to not work prior to #73480 at all, unless you are talking about some other proc

I always used Shake to stop people from spinning, so I assumed this what this proc was meant to do? Maybe it was so bugged it just removed spinning from people? Is there another proc I can call to stop SpinAnimation()?

**Comment by Mothblocks** [comment]
I don't really treat this as an intentional design, just a side effect admins learned. We need a dedicated stop spinning proc.

**Comment by Mothblocks** [comment]
I'm tagging not a bug but leaving open because this is an important proc to exist

**Comment by the-og-gear** [comment]
Call SpinAnimation directly, and ensure you specify `parallel = false`
`SpinAnimation(speed=1, loops=1, parallel=false)` or something like that.

**Comment by Mothblocks** [comment]
Tbh spin should be a menu dropdown option, that's too complicated

**Comment by the-og-gear** [comment]
I can shim something in later. I foresee short term high usages of it as a menu option, but I also think it would be pretty fucking funny for all of a few hours.

**Comment by Mothblocks** [comment]
admins use SpinAnimation a weirdly high amount

**Comment by Striders13** [comment]
> admins use SpinAnimation a weirdly high amount

yes

**Comment by Mothblocks** [comment]
> I'm tagging not a bug but leaving open because this is an important proc to exist

I changed my mind on leaving it open
