### ISSUE TITLE
Gem room brains still appears to be an issue

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#74326]
## Reproduction:

Pull master to post #74227 merge. 

atom proc call `drop_limb` on your head bodypart. 
atom proc call `try_attach_limb` on your head with your (former) body marked as the first argument

Your brain will be error roomed as before. 

See: #74126

**Comment by Timberpoes** [comment]
I fucked it up while reorganising code during the PR writeup. Hotfix incoming shortly.
