### ISSUE TITLE
Circuits NTNet components seems to be working no more

### ISSUE THREAD

**Issue by Zeropol** [tgstation/tgstation#74327]
_NTNet transmitter_ and/or _NTNet receiver_ components are not working anymore.

## Reproduction:
- Create a circuit to test it. Example this one ( screenshot )
![image](https://user-images.githubusercontent.com/28099824/228351335-50c5932c-fa41-4267-87d4-afcb0c71deca.png)
- Make sure you can talk on the radio comms.
![image](https://user-images.githubusercontent.com/28099824/228351581-c19c8bfb-d2b9-4a60-aabc-5294faee7e06.png)
- Use the circuit
- See it dont work.  ( note that if you did this exact circuit, it will still say "TEST OK" everytime you mess with a link to the speech component, or change the battery,  but it dont mean the NTNet message was actually transmitted. You can make sure of this by looking at the "trigerred" value of differents components with a multitool )

May be related to #74142 ?
If I did something wrong and it is not a bug, sorry ! ( but tell me anyway )

**Comment by Mothblocks** [comment]
@JohnFulpWillard Please look into this
