### ISSUE TITLE
Tram Issues 3in1

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#74348]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:

- Hop office has no cams
- Escapepod Hall has no cams
- Vault is not connected to Power and Pipesystem (Upper and Below Pics)
![Screenshot_1](https://user-images.githubusercontent.com/95751821/228658252-929ab793-6d6a-4165-80a2-01e53c46447b.png)
![Screenshot_3](https://user-images.githubusercontent.com/95751821/228658733-97b7b792-df0f-4644-a65c-a32d852d3a46.png)

**Comment by lessthnthree** [comment]
Turns out this is the north side of west 2nd floor, not just the vault.
