### ISSUE TITLE
singulo caller final traitor objective wont let you call down the smuggled satellites

### ISSUE THREAD

**Issue by Zevotech** [tgstation/tgstation#74376]
Reporting client version: 514.1589

## Round ID:
[202808](https://scrubby.melonmesa.com/round/202808)

## Testmerges:
- [Reagent soup / Soup rework / Stoves - A kitchen expansion](https://www.github.com/tgstation/tgstation/pull/74205)

## Reproduction:
Tried calling the pod at starboard quarter solars on metastation and the button didnt do anything. An admin said the objective was counting itself as both active and skipped.

**Comment by rageguy505** [comment]
Yeah, i was the admin and in his TP it was under the ongoing section with (skipped) at the end. Also round end report said they succeeded their obective.
