### ISSUE TITLE
hud popups whitescreens randomly/when multiple instances are created, crafting/lathe/etc menu will not show item sprites

### ISSUE THREAD

**Issue by saprasam** [tgstation/tgstation#74445]
## Round ID: 
[202943](https://scrubby.melonmesa.com/round/202943) (happy aprifls fools)

## Testmerges:
https://github.com/tgstation/tgstation/pull/74416
https://github.com/tgstation/tgstation/pull/74389
https://github.com/tgstation/tgstation/pull/74420
https://github.com/tgstation/tgstation/pull/74423
https://github.com/tgstation/tgstation/pull/74437
https://github.com/tgstation/tgstation/pull/74402
https://github.com/tgstation/tgstation/pull/74404

## Reproduction:
for the record: this has been a problem i've had for the past month now. instead of the game crashing, or the game freezing whenever i click on fancy chat, instead it now breaks my ui. awesome. aweosm. aw

open multiple hud tabs. for me, after opening 2 tabs at a time, it leaves a semi-permanent white box in the middle of my screen that completely fucks with my ability to play the game (just as much as not being able to open multiple huds in the first place!) that is only fixed by walking away from the item/instance that opened the box in the first place. opening the crafting menu while this whitebox state is active will also not show sprites.
the only fix i've noted is that i can clear the cache, which fixes it for... 5 rounds? at best? and then it goes back to breaking

IMAGES FOR REFERENCE!!!!
![tgui hype](https://user-images.githubusercontent.com/62454517/229310612-cb911d12-394a-46e2-83c3-a637e4a6efa4.png)
](url)
![tgui2](https://user-images.githubusercontent.com/62454517/229310623-cc128ec9-29f1-4482-a1ca-4d47105779c1.png)
![tgui3](https://user-images.githubusercontent.com/62454517/229310628-59156761-2535-4537-b2fd-eae5f58a479b.png)

**Comment by Sealed101** [comment]
i di believe this is yet another instance of your PC/connection lacking, thus leading to tgui windows struggling to load. can't really offer any advice on it outside of 'clear thy cache', but i believe you can close these windows with Alt+F4 after you click on them

**Comment by saprasam** [comment]
holy shit. i am so horrifically retarded. i managed to forget to update my graphics driver for months. MONTHS. MONTHS. MONTHS.
this was a nothing burger solved by not being lazy
