### ISSUE TITLE
AI carding issues, malf and not malf.

### ISSUE THREAD

**Issue by MrrFiish** [tgstation/tgstation#74449]
Reporting client version: 514.1589

## Round ID:
[202902](https://scrubby.melonmesa.com/round/202902) and later 202964

## Testmerges:
The first time it happened there were no testmerges.

- [Improves Roleplay](https://www.github.com/tgstation/tgstation/pull/74439)
- [[April Fools] tf_weapon_criticals 1](https://www.github.com/tgstation/tgstation/pull/74425)
- [[april fools] adds frogression traitors](https://www.github.com/tgstation/tgstation/pull/74416)
- [[april fools] Booping Is Now Legal](https://www.github.com/tgstation/tgstation/pull/74399)
- [New species: IPC](https://www.github.com/tgstation/tgstation/pull/74402)
- [[April Fools] Issue of skill](https://www.github.com/tgstation/tgstation/pull/74393)
- [[April Fools] Votekick](https://www.github.com/tgstation/tgstation/pull/74392)
- [[Aprile Fools] [TM] Add Zomboid jumpscare](https://www.github.com/tgstation/tgstation/pull/74389)
- [Adds Chuunibyou Spell + Granter](https://www.github.com/tgstation/tgstation/pull/74404)
- [Adds Master.sleep_delta to the mc tab.](https://www.github.com/tgstation/tgstation/pull/74360)
- [[April Fools] Adds 13 new jobs to the game to enhance the roleplaying experience.](https://www.github.com/tgstation/tgstation/pull/74423)

## Reproduction:
AI being carded then put in it's core is unable to do anything if its permissions weren't turned on while carded. Malf AI also loses its shop and abilities, not even being able to hack APCs or shunt.
1. Shunt into an APC as malf AI.
2. Have your core be killed.
3. Have a new core built and be carded then put into it.
4. Your name will now be <name> Apc Copy and you can't use any malf abilities or anything.

In the second round I wasn't malf.
1. Be carded and have the permissions off.
2. Be put back in core.
3. Be unable to interact with doors/APCs/anything.

**Comment by Sealed101** [comment]
can't reproduce; no amount of fiddling with connection/radio settings on the aicard locked the ai out of using their abilities when redeployed to a core
