### ISSUE TITLE
Basketball broke, turf issues, similar to a logged thunderdome issue

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#74443]
Reporting client version: 514.1589

## Round ID:
[202940](https://scrubby.melonmesa.com/round/202940)

## Testmerges:
- [[april fools] adds frogression traitors](https://www.github.com/tgstation/tgstation/pull/74416)
- [[Aprile Fools] [TM] Add Zomboid jumpscare](https://www.github.com/tgstation/tgstation/pull/74389)
- [[April Fools] Votekick](https://www.github.com/tgstation/tgstation/pull/74392)
- [[April Fools] Issue of skill](https://www.github.com/tgstation/tgstation/pull/74393)
- [Adds Master.sleep_delta to the mc tab.](https://www.github.com/tgstation/tgstation/pull/74360)
- [[April Fools] Adds 13 new jobs to the game to enhance the roleplaying experience.](https://www.github.com/tgstation/tgstation/pull/74423)
- [[april fools] makes felinids more realistic](https://www.github.com/tgstation/tgstation/pull/74420)
- [[April fools] Better audio for combat & some announcements](https://www.github.com/tgstation/tgstation/pull/74408)

## Reproduction:

Only really reporting this because its probably related to an issue I reported with the TD and I don't think its april fools related.

See #69711 for what is probably the same bug and if so easier to reproduce.

![image](https://user-images.githubusercontent.com/3789327/229310360-031a97c2-fe20-4ec4-9e7e-bb4e9f6f1396.png)

**Comment by timothymtorres** [comment]
Does this occur on all basketball maps?  It does look similar to the Thunderdome bug.
