### ISSUE TITLE
arrest status doesn't update

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#74469]
Round ID: [202966](https://scrubby.melonmesa.com/round/202966)

Testmerges: https://github.com/tgstation/tgstation/pull/73022 

Reproduction: set someone to arrest. look at them with sechuds. they will not be set to arrest. remove their ID and put it back on, they will be set to arrest

https://streamable.com/a44met

pretty big issue since this also works the other way around, i.e. setting someone off arrest won't update it so they will be arrested after getting set off

**Comment by Mooshimi** [comment]
HUD update moment

**Comment by Sealed101** [comment]
#75320
