### ISSUE TITLE
Asteroid Rocks have Two `icon` vars

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#74475]
on master right now
## Reproduction:

![image](https://user-images.githubusercontent.com/34697715/229420034-4b582325-714d-4c1a-b4c3-25f2b6b88446.png)

which one should we use

**Comment by LemonInTheDark** [comment]
second one

**Comment by Ical92** [comment]
Is this what's causing the issue with them to be blank on the maps?

**Comment by san7890** [comment]
most likely yea. i haven't seen this myself i just noticed this was flarped

**Comment by LemonInTheDark** [comment]
in theory the second icon set should override the first
