### ISSUE TITLE
Assistants do not have maintenance access by default

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#74488]
It's probably a config option that someone must have turned on when messing during April Fool's.

I am aware it is used on some dowstream MRP servers.

I think I recall, there was a poll on /tg/ concerning removing the access from assistants.
It did not pass.
## Round ID:
[203061](https://scrubby.melonmesa.com/round/203061)

## Testmerges:
[#74371: 'The North Star Expeditionary Vessel - A Second Wind' by Cheshify at commit 00565162d8](https://www.github.com/tgstation/tgstation/pull/74371)
[#74360: 'Adds Master.sleep_delta to the mc tab.' by MrStonedOne at commit ce113c522f](https://www.github.com/tgstation/tgstation/pull/74360)

## Reproduction:
Join the round as an assistant. Bump into the grey hatch repeatedly, like a flyperson into a window. The hatch wont open.

**Comment by san7890** [comment]
Thanks for reporting this, but the codebase is not able to assist in any issues of server-specific configurations. Please reach out to the Head Administration to see if this was an intentional change or not.

**Comment by san7890** [comment]
If you find out that it was intentional, you may request this to be changed at this subforum: https://tgstation13.org/phpBB/viewforum.php?f=33
