### ISSUE TITLE
Alien/Xenomorph AI mobs can't be lied down

### ISSUE THREAD

**Issue by AlamoTurtle** [tgstation/tgstation#74503]
Reporting client version: 514.1589

## Round ID:
[203102](https://scrubby.melonmesa.com/round/203102)

## Testmerges:
- [Block connections to the server from new ckeys if the panic bunker is up and not in interview mode](https://www.github.com/tgstation/tgstation/pull/74496)
- [Clients can't OOC until they have fully gone through `New()`](https://www.github.com/tgstation/tgstation/pull/74493)
- [Disables auxtools](https://www.github.com/tgstation/tgstation/pull/74497)

## Reproduction:

1. Find AI xenomorph on Charlie Station/Lavaland
2. Kill
3. Attempt to lie it down on a bed to do surgery, being unable to with a bedsheet or drapes as the target is not lying down
4. It is dead, you cannot make it lie down

This effectively makes it impossible to get xeno dissection done without doing a silly surgery in the middle of an ongoing xenomorph outbreak, as well as getting easy alien organs for shenanigans.

**Comment by rageguy505** [comment]
those are simple/basic mobs arent they?

**Comment by Mooshimi** [comment]
consistency for being unable to lie down not the organs part

**Comment by JohnFulpWillard** [comment]
> makes it impossible to get xeno dissection done without doing a silly surgery in the middle of an ongoing xenomorph outbreak

You can't do dissection surgery without an operating computer anyways so this is irrelevant.

What difference does it make if they can't be lied down or not here? Not that I can replicate this bug anyways.
