### ISSUE TITLE
Cameras and newscaster photos do not show many items

### ISSUE THREAD

**Issue by Chocobro** [tgstation/tgstation#7450]
![cameras are still broken](https://cloud.githubusercontent.com/assets/5677255/5980384/d1acfaaa-a8a7-11e4-9fdb-f6cc747ee1bb.png)
![camera newscaster bug](https://cloud.githubusercontent.com/assets/5677255/5980389/dc9cb310-a8a7-11e4-884a-86624437ffa4.png)
https://github.com/tgstation/-tg-station/issues/4315

this has been a bug for over two years, now. is anyone ever going to fix it??? find out next time this bug gets issue reported

[ ] mechs

[ ] crabs

[ ] janibots

**Comment by RemieRichards** [comment]
> is anyone ever going to fix it??? 

It's been fixed about 4-5 fucking times now, it's a complicated bug because some of the stuff is deeply rooted in byond crap.

**Comment by Chocobro** [comment]
clearly it hasn't been fixed because the bug is very much still there

**Comment by RemieRichards** [comment]
Well actually cameras have been fixed many a time, To name a few:
* Lying down in photos used to not be shown
* Many objects facing different directions were not shown
* Carpets caused an issue at one point or another

The list of things wrong with cameras that has been fixed is stupidly long, and as I said, it's a complicated bug.

**Comment by AndroidSFV** [comment]
Remie is not exaggerating, camera code is extremely complicated and rooted in byond shit.

**Comment by Chocobro** [comment]
great! however it's still not fixed.

**Comment by AndroidSFV** [comment]
I believe I've determined what is needed to resolve this.. will open a new issue for it because it will likely require a significant refactor.

**Comment by Nienhaus** [comment]
I see the sprites tag but I have nothing to do with this. Have fun with the code.

**Comment by AndroidSFV** [comment]
Nien is right, this is a code issue, not a sprite issue.

**Comment by optimumtact** [comment]
old higgs bugson

**Comment by PKPenguin321** [comment]
Not sure why this was a higgs because it definitely still happens

**Comment by optimumtact** [comment]
The label implies nobody knows why it's occurring, not that it is occuring

**Comment by AndroidSFV** [comment]
We know why it this happens, we just can't Implement a good solution for it. Best fix would be added into byond.

**Comment by Chocobro** [comment]
unsubbed imo
