### ISSUE TITLE
Brig plasma moat creating massive frame drops on icebox

### ISSUE THREAD

**Issue by arnociiroc** [tgstation/tgstation#74515]
## Testmerges:
[#74430: 'Adds lava and plasma particle effects' by Time-Green at commit 47c75fa81d](https://www.github.com/tgstation/tgstation/pull/74430)
[#74496: 'Block connections to the server from new ckeys if the panic bunker is up and not in interview mode' by MrStonedOne at commit fe4dc0f867](https://www.github.com/tgstation/tgstation/pull/74496)
[#74493: 'Clients can't OOC until they have fully gone through `New()`' by san7890 at commit e4076ee7cb](https://www.github.com/tgstation/tgstation/pull/74493)
[#74497: 'Disables auxtools' by MrStonedOne at commit 10158ca4d3](https://www.github.com/tgstation/tgstation/pull/74497)
[#74490: 'Imports and Contraband: Different! Cargo crates without locks! MEAT!' by necromanceranne at commit f67163ff84](https://www.github.com/tgstation/tgstation/pull/74490)

## Reproduction:
be on icebox as a ghost, hover over brig plasma moat, watch game slow to a crawl

**Comment by Mooshimi** [comment]
#74430

**Comment by Mooshimi** [comment]
wait mothblocks said ur supposed to post this in the pr if it's for a testmerge, please do so @arnociiroc

**Comment by arnociiroc** [comment]
i paste the issue into the PR comments?

**Comment by Mooshimi** [comment]
> i paste the issue into the PR comments?

yeahp, the details at least please. that it's making framedrops etc round number
