### ISSUE TITLE
Plating that starts off airless is incompatible with the RTD

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#74526]
Reporting client version: 514.1589

## Round ID:
[203172](https://scrubby.melonmesa.com/round/203172)

## Testmerges:
- [Disables auxtools](https://www.github.com/tgstation/tgstation/pull/74497)
- [Clients can't OOC until they have fully gone through `New()`](https://www.github.com/tgstation/tgstation/pull/74493)
- [The North Star Expeditionary Vessel - A Second Wind](https://www.github.com/tgstation/tgstation/pull/74371)
- [Adds Master.sleep_delta to the mc tab.](https://www.github.com/tgstation/tgstation/pull/74360)
- [Imports and Contraband: Different! Cargo crates without locks! MEAT!](https://www.github.com/tgstation/tgstation/pull/74490)

## Reproduction:

1. try to use RTD on donut whiteship
2. WHY NO WORK

**Comment by SyncIt21** [comment]
What's the donut whiteship? could you be more specific? RTD can only construct & deconstruct tile types which it supports i.e. metal & glass types, this was done for balance reasons, all other floor types like bamboo, wood, titanium any other material is not supported

**Comment by Mooshimi** [comment]
So the issue here is that they don't know **why** this doesn't work. 
Please update the title of this pr to reflect that using the RTD needs feedback when used on an incompatible tile.

**Comment by Mooshimi** [comment]
> ...which would be because `is_valid_plating` does not check for `/turt/open/floor/plating/airless`

so the first /turf/open/floor/plating doesn't return true if it's a child of /turf/open/floor/plating? wacky

**Comment by SyncIt21** [comment]
Ah yes at the time I did want to specifically check only for these 2 types of platings because I was unsure of what type of platings are out there. 
 I guess it should be ok to use istype() directly, or check from an list of allowed platings using type_in_list()

**Comment by SyncIt21** [comment]
I'll address this in my latest RCD refactor PR, I should probably draft that till tom
