### ISSUE TITLE
Plasmen and Suits

### ISSUE THREAD

**Issue by FotisLight** [tgstation/tgstation#74546]
Reporting client version: 514.1589

## Round ID:
[203231](https://scrubby.melonmesa.com/round/203231)

## Testmerges:
- [Adds lava and plasma particle effects](https://www.github.com/tgstation/tgstation/pull/74430)
- [Disables auxtools](https://www.github.com/tgstation/tgstation/pull/74497)
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)

## Reproduction:
Just be a plasman and put on an infiltrator MOD suit. After sealing your body will still keep reacting to the air.

**Comment by mc-oofert** [comment]
did you have a plasma stabilizer module

**Comment by necromanceranne** [comment]
The suit doesn't have a stabilizer inbuilt, you need to add one. This isn't a bug.
