### ISSUE TITLE
Humans have no taste buds.

### ISSUE THREAD

**Issue by CMDR-Gungnir** [tgstation/tgstation#74571]
Reporting client version: 514.1589

## Round ID:
[203291](https://scrubby.melonmesa.com/round/203291)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)
- [Disables auxtools](https://www.github.com/tgstation/tgstation/pull/74497)

## Reproduction:
Step 1) Fill a Large Glass Bottle with a drink
Step 2) Drink it
Step 3) Notice that the flavour doesn't show up.

**Comment by Mooshimi** [comment]
Can you give more detail about the state of your character at the time, species, etc.

Related code:
https://github.com/tgstation/tgstation/blob/ecbcef778df6cffc7ec31306c630a52f497a5712/code/modules/reagents/chemistry/holder.dm#L1384-L1423

**Comment by CMDR-Gungnir** [comment]
Uhh. Perfectly normal, I don't think there was anything really going on about them at the time and it's been every time in recent memory that I've used a bottle.

Species was Human. And the drinks were 100% Fringe Weaver, in one, and Sea Breeze in another. I beliiiieve the beaker with Ethanol didn't give a taste either, but I may be wrong on that one so don't quote me on it. But drinks from glasses are displaying flavour properly, including the "a hint of" on  the smaller amounts.

**Comment by Livrah** [comment]
I noticed Floor pills lost their taste too.

**Comment by CMDR-Gungnir** [comment]
> I noticed Floor pills lost their taste too.

I'd argue it a safe bet then that everything's lost their tastes except for Drink Glass(es)

**Comment by Mooshimi** [comment]
> > I noticed Floor pills lost their taste too.
> 
> I'd argue it a safe bet then that everything's lost their tastes except for Drink Glass(es)

mind renaming the issue to reflect the new scope (that multiple things have lose taste flavortext

**Comment by CMDR-Gungnir** [comment]
Renamed to reflect the fact that we're fairly confident about some things but don't know it 100% for sure.

**Comment by CMDR-Gungnir** [comment]
I did a bunch of testing with the help of some admins in the thunderdome, and Felinids and Moths both had taste, but a test size of three humans (and one player talking about some past rounds as a Human) had no taste.

Safe to say it's a bug with Humans, I'd wager.

**Comment by Mooshimi** [comment]
> I did a bunch of testing with the help of some admins in the thunderdome, and Felinids and Moths both had taste, but a test size of three humans (and one player talking about some past rounds as a Human) had no taste.
> 
> Safe to say it's a bug with Humans, I'd wager.

tyvm for ur testing
