### ISSUE TITLE
Set nightshift admin command doesn't work

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#74587]
Turning nightshift on or off from the secrets panel doesn't work. The message is broadcast but the lights don't actually change. Night shift is enabled in config.

https://user-images.githubusercontent.com/83487515/230697579-954099fe-c6cd-417c-b4fb-45ff87c62ea3.mp4

## Reproduction:

Try to toggle night shift.

**Comment by san7890** [comment]
We see this on all maps right, not just runtime?

**Comment by lessthnthree** [comment]
> We see this on all maps right, not just runtime?

Yeah. In nightshift.dm:
This for loop doesn't work because if(MC_TICK_CHECK)

![image](https://user-images.githubusercontent.com/83487515/230706224-4ca900fa-8d9c-4f05-b7fe-2c67f2a90274.png)

The subsystem is in state idle, not running, so this always returns 'true'
