### ISSUE TITLE
"Too many conflicting APCS!" warning always triggers upon using the create/modify area button

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#74605]
Reporting client version: 514.1589

## Round ID:
[203393](https://scrubby.melonmesa.com/round/203393)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)
- [DEPARTMENTAL TRAINEES/ASSISTANTS!](https://www.github.com/tgstation/tgstation/pull/74578)

## Reproduction:
Get the blueprints or become a cyborg
Try editing a area using it
"Too many conflicting APCS!"
Create new room in space
Try to create new area
"Too many conflicting APCS!"
cry

**Comment by SyncIt21** [comment]
Not a bug.  This check was added in the event a player tried to merge 2 or more areas having apcs which would create a new area having multiple apc. You have to deconstruct all apc before you make the area in this event and then remake them again,  that's just the price you pay if you didn't think ahead 

If you are creating a room next to one already having an apc then just make sure they are separated by 2 layers of walls and not one or if you are making several areas next to each other first create all the areas and then make apcs for each of those areas.

Also if you are creating an area in space they must not share their walls with the shuttle in  other words add 1 more layer of wall or make it at some distance from the shuttle.

The general solution is make sure your area is atleast 1 tile away on all sides from the neibouring areas.

**Comment by ZAMODA** [comment]
> Also if you are creating an area in space they must not share their walls with the shuttle in other words add 1 more layer of wall or make it at some distance from the shuttle.
> 
> The general solution is make sure your area is atleast 1 tile away on all sides from the neibouring areas.

Unless you mean shuttle as in station then its still a problem since that completely removes the ability to expand rooms AT ALL
I.e. create an expansion off of evac from the airlocks, try to expand the evac room, get said error

**Comment by ZephyrTFA** [comment]
Why are we relying on two layers of walls, this seems like a downgrade in QOL more than reasonable

**Comment by SyncIt21** [comment]
> > Also if you are creating an area in space they must not share their walls with the shuttle in other words add 1 more layer of wall or make it at some distance from the shuttle.
> > The general solution is make sure your area is atleast 1 tile away on all sides from the neibouring areas.
> 
> Unless you mean shuttle as in station then its still a problem since that completely removes the ability to expand rooms AT ALL I.e. create an expansion off of evac from the airlocks, try to expand the evac room, get said error

By shuttle I mean outside the station in space you are trying to create a room attached to the shuttle walls for that you need to add some space. You can expand the room into space with no problem but you can't expand it into another room already having an apc because like I said we wouldn't know which apc to use for this new area.
 The solution is to dismantle both the rooms apcs, expand the area and then rebuild the apc for the new area.(and also the old remaining area if you didn't expand it fully into the new area)

**Comment by SyncIt21** [comment]
> Why are we relying on two layers of walls, this seems like a downgrade in QOL more than reasonable

Yup it is downgrade for Qol but it also prevents duplicate APC's so it's nessassary

**Comment by SyncIt21** [comment]
We can try to make the checks a little less strict. I'll see what I can do
