### ISSUE TITLE
Holodeck reagents are real

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#74612]
## Reproduction:

1. Go to the Holodeck
2. Load up Chapel/Courtroom
3. Eat a poppy
4. Heal from the Libital in it.

not sure what the correct fix is here, holographic items should be able to handle reagents, see the welder tank holodeck. removing the food would be fine ig? we could also prevent holographic food from getting the edible component, but you could cut it up with a knife or whatever and it wont inherit being a hologram

**Comment by msgerbs** [comment]
What if we made a holographic component, which is inherited by anything an item with that component creates and ensures the item is deleted when the holodeck program closes?

**Comment by Mooshimi** [comment]
Yeah the apple feeds you as well
