### ISSUE TITLE
Aquatic spines vanishing when lizards wag their tail

### ISSUE THREAD

**Issue by TattoMoon** [tgstation/tgstation#74611]
## Reproduction: Wag your tail with aquatic spines on a lizard person

Wagging your tail as a lizard will make aquatic spines, and possibly some others, vanish while the tail is in motion. Wagging your tail should not do this.
![ezgif-4-2354d61a7e](https://user-images.githubusercontent.com/94944115/230746410-8c70206c-9f30-4c4b-801a-e43356131b6f.gif)

**Comment by Time-Green** [comment]
Someone probably just messed with the spines icon state name
