### ISSUE TITLE
Fugitive Hunters don't have ghost roll

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#74625]
## Reproduction:
After Fugitives spawned, ghosts never get to roll the Hunters. In 2 different rounds I found Hunter's spawners via ghost spawner menu. This explains why we never seen hunters ingame.

**Comment by Mooshimi** [comment]
https://github.com/tgstation/tgstation/blob/50b37c8c7f6c53033634b7ffa6bbed3dca17199b/code/modules/mob_spawn/ghost_roles/fugitive_hunter_roles.dm#L10-L12

https://github.com/tgstation/tgstation/blob/3b1460d220584e87cc3fddea3c705cc8c10d6759/code/modules/events/ghost_role/fugitive_event.dm#L64

https://github.com/tgstation/tgstation/blob/3b1460d220584e87cc3fddea3c705cc8c10d6759/code/modules/events/ghost_role/fugitive_event.dm#L105-L123

**Comment by Mooshimi** [comment]
Why do these say fugitive when they're for fugitive hunter??

https://github.com/tgstation/tgstation/blob/50b37c8c7f6c53033634b7ffa6bbed3dca17199b/code/modules/mob_spawn/ghost_roles/fugitive_hunter_roles.dm#L2

https://github.com/tgstation/tgstation/blob/50b37c8c7f6c53033634b7ffa6bbed3dca17199b/code/modules/mob_spawn/ghost_roles/fugitive_hunter_roles.dm#L10-L12

https://github.com/tgstation/tgstation/blob/50b37c8c7f6c53033634b7ffa6bbed3dca17199b/code/modules/mob_spawn/ghost_roles/fugitive_hunter_roles.dm#L14-L21

Looking at the file, the ship files start with the sleepers for the hunters on them so maybe ghosts just need a better notification that the ship has landed?

**Comment by BlueMemesauce** [comment]
It's designed that way because the  fugitive hunters arrive 10 minutes after the fugitives. The fugitive hunters need to appear or else the fugitives have nothing to do. Therefore, sleepers are the best choice since there's no guarantee that there will be any ghosts to become fugitive hunters. Sleepers are necessary to allow the role to be gradually filled by more people becoming ghosts in such a scenario. 

So just having a better notification would be the best improvement to solve this issue like Mooshimi said.

**Comment by Rex9001** [comment]
> It's designed that way because the fugitive hunters arrive 10 minutes after the fugitives. The fugitive hunters need to appear or else the fugitives have nothing to do. Therefore, sleepers are the best choice since there's no guarantee that there will be any ghosts to become fugitive hunters. Sleepers are necessary to allow the role to be gradually filled by more people becoming ghosts in such a scenario.
> 
> So just having a better notification would be the best improvement to solve this issue like Mooshimi said.

Pirates have a sleeper and ghost roll, maybe it could be implimented that way?

**Comment by BlueMemesauce** [comment]
> > It's designed that way because the fugitive hunters arrive 10 minutes after the fugitives. The fugitive hunters need to appear or else the fugitives have nothing to do. Therefore, sleepers are the best choice since there's no guarantee that there will be any ghosts to become fugitive hunters. Sleepers are necessary to allow the role to be gradually filled by more people becoming ghosts in such a scenario.
> > So just having a better notification would be the best improvement to solve this issue like Mooshimi said.
> 
> Pirates have a sleeper and ghost roll, maybe it could be implimented that way?

That spawning system is currently bugged #73822
But it would be a good idea to add fugitive hunters to that system if it's ever fixed
