### ISSUE TITLE
Regal Rats destroy disposals when rummaging

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#74627]
Reporting client version: 514.1589

## Round ID:
[203443](https://scrubby.melonmesa.com/round/203443)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)
- [The North Star Expeditionary Vessel - A Second Wind](https://www.github.com/tgstation/tgstation/pull/74371)

## Reproduction:
1. Be a regal rat
2. Click on a disposal chute to rummage for cheese
3. Attack the chute while also rummaging in it
I've been told this may NOT be a bug, but I don't recall seeing any pulls to change this, and it definitely isn't how this used to work

**Comment by Mooshimi** [comment]
looks like an unintentional change if it was one. were you on harm intent by any chance

**Comment by Mooshimi** [comment]
https://github.com/tgstation/tgstation/blob/ccef887efec2cb3025228210bcb134700aac5175/code/modules/recycling/disposal/bin.dm#L136-L155

**Comment by ZeroKelvn** [comment]
Nope, Combat Mode was off

**Comment by IndieanaJones** [comment]
Regal rat isn't supposed to go through with his normal attack chain if he's doing a special interaction (licking, rummaging, etc...). Something broke it entirely, and he's attacking things again after other actions.

**Comment by san7890** [comment]
this is fixed now because it's all signal based and we cancel the whole attack chain on a successful rat interaction
