### ISSUE TITLE
replacement uplinks do not work if PDA is destroyed

### ISSUE THREAD

**Issue by Loafin34** [tgstation/tgstation#74637]
## Round ID: [203483](https://scrubby.melonmesa.com/round/203483)

#74315  doesnt work if pda is blown up. happened when i was tiding and used a plasma-filled power cell on a stunprod, was not pretty, could not use anteg uplink. very sad.

**Comment by Profakos** [comment]
Wait, detomatix cartridge is not supposed to work on traitor PDAs with uplinks in them, that is one more issue.

**Comment by mc-oofert** [comment]
> Wait, detomatix cartridge is not supposed to work on traitor PDAs with uplinks in them, that is one more issue.

(it doesnt work on traitor PDAs)

**Comment by Profakos** [comment]
> > Wait, detomatix cartridge is not supposed to work on traitor PDAs with uplinks in them, that is one more issue.
> 
> (it doesnt work on traitor PDAs)

Aha, okay. The reproduction steps confused me then.

**Comment by flowercuco** [comment]
you could have still crafted a replacement uplink but youre correct that it is hard to see the information past the "YOU HAVE LOST YOUR UPLINK" dimmer text stuff, ive just put a second iteration of the replacement information on the dimmer screen
