### ISSUE TITLE
PDA flashlights not working properly

### ISSUE THREAD

**Issue by Juninho77** [tgstation/tgstation#7466]
In the following picture, my PDA's flashlight is on:
![untitled](https://cloud.githubusercontent.com/assets/10784590/5987749/24f62ee4-a90b-11e4-9ada-cddc358405ee.png)

How to reproduce:
1. Have your PDA and another source of light on.
2. Put your PDA into your backpack.
3. Remove your PDA from your backpack.
4. Turn off your other source of light.

Suggested workaround:
Give us a top left icon for the PDA flashlight, so we can easily reset it when this bug happens.

**Comment by Deantwo** [comment]
Known bug, but yeah I thought it was fix before.
I have noticed it recently again too though.

**Comment by paprka** [comment]
"Give us a top left icon for the PDA flashlight, so we can easily reset it when this bug happens."

Please this. At least an object verb.

**Comment by Deantwo** [comment]
I didn't see the "suggestion" part.
And it wouldn't really help anyway.

The best solution would be to just fix this.
I am pretty sure that this was fixed for flashlights and other things right? So fixing the PDA too shouldn't be hard.

**Comment by Mervill** [comment]
@optimumtact closeable, no longer an issue (tested on runtimestation)
