### ISSUE TITLE
Mixing cryostylane with oxygen doesn't lower the temperature

### ISSUE THREAD

**Issue by ZealousZeke** [tgstation/tgstation#74667]
Reporting client version: 514.1589

## Round ID:
[203590](https://scrubby.melonmesa.com/round/203590)

## Testmerges:
- [Adds a Material Stack manipulation apparatus for Engineer Cyborgs, replaces the R-Glass tool](https://www.github.com/tgstation/tgstation/pull/74297)

## Reproduction:
Step 1. Mix cryostylane and make note of the temperature.
Step 2. Add oxygen to the cryostylane.
Step 3. Notice the temperature has risen slightly above the original cryostylane mixing temp instead of dropping.

I believe this is due to temperature averaging raising the temperature more than it cools.

![cryostylane](https://user-images.githubusercontent.com/85478781/231301215-6324a02f-be2a-443f-8094-576f37cea954.png)

EDIT:
![stinkygif](https://user-images.githubusercontent.com/85478781/232259070-49454924-6cf8-4067-8320-b32701b42b98.gif)

**Comment by SyncIt21** [comment]
This might be fixed by #74462? @Pickle-Coding

**Comment by ZealousZeke** [comment]
> That PR would actually make this worse, though I'm not exactly sure what is going on here. Is the oxygen getting consumed?

Yes, the cryostylane consumes the oxygen much like pyrosium does, but the intended effect of lowering the temperature doesn't seem to be working as intended.

**Comment by ZealousZeke** [comment]
![stinkygif](https://user-images.githubusercontent.com/85478781/231498584-96678249-eb77-4899-a04b-cae33735c3d9.gif)
