### ISSUE TITLE
Conciousness transfer potion works on the Meat-eor boss

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#74669]
Reporting client version: 514.1589

## Round ID:
[203604](https://scrubby.melonmesa.com/round/203604)

## Testmerges:
- [Adds a Material Stack manipulation apparatus for Engineer Cyborgs, replaces the R-Glass tool](https://www.github.com/tgstation/tgstation/pull/74297)
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)
- [The North Star Expeditionary Vessel - A Second Wind](https://www.github.com/tgstation/tgstation/pull/74371)

## Reproduction:
Turns out that you can make the weird boss heart thing in the organ ruin sentient or turn yourself into one. I don't think that's intentional considering its a boss and all

**Comment by timothymtorres** [comment]
The person who coded this commented on the PR that tried to address this:

> Yeah I forgot this, the idea of someone moving their mind into a completely immobile mob is funny but we probably should guard against it. Teleporting it onto the station, also probably a bad idea. I don't know if the faction is necessary though. If someone wants to defeat this not terribly challenging entity by teleporting bubblegum into space somehow then I think that's a valid solution which mostly makes their own life worse.
