### ISSUE TITLE
Using lavaland pride mirror on North Star map will kill you

### ISSUE THREAD

**Issue by LikesGreen** [tgstation/tgstation#74672]
## Testmerges:
[#74297: 'Adds a Material Stack manipulation apparatus for Engineer Cyborgs, replaces the R-Glass tool' by zxaber at commit a68598e96b](https://www.github.com/tgstation/tgstation/pull/74297)
[#73502: 'Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]' by Zytolg at commit 7ea114086b](https://www.github.com/tgstation/tgstation/pull/73502)
[#74371: 'The North Star Expeditionary Vessel - A Second Wind' by Cheshify at commit 3189fbf8e7](https://www.github.com/tgstation/tgstation/pull/74371)

## Reproduction:
Map: North Star
1. Find pride mirror on lavaland
2. Pick race that you want to change into
3. Think it will drop you into some random place in space
4. Get killed by chasm that is made after you pick race

**Comment by CMDR-Gungnir** [comment]
You know what they say.

Pride comes before a fall :^)

**Comment by Sealed101** [comment]
afaik the map has no space z levels, so the pride mirror uses a chasm as a fallback. doesn't seem like an issue to me, using that belt teleporter thing works for both.

**Comment by plutori** [comment]
> afaik the map has no space z levels, so the pride mirror uses a chasm as a fallback. doesn't seem like an issue to me, using that belt teleporter thing works for both.

And how exactly are players expected to know to do this on only this map?

**Comment by Helg2** [comment]
> And how exactly are players expected to know to do this on only this map?

They're expected to not play it.

**Comment by ZephyrTFA** [comment]
The entire point of the pride mirror is that it kills you when you use it.
