### ISSUE TITLE
HFR recipe selection is broken in NTOS

### ISSUE THREAD

**Issue by plutori** [tgstation/tgstation#74677]
Reporting client version: 514.1589

## Round ID:
[203620](https://scrubby.melonmesa.com/round/203620)

## Testmerges:
- [Adds a Material Stack manipulation apparatus for Engineer Cyborgs, replaces the R-Glass tool](https://www.github.com/tgstation/tgstation/pull/74297)
- [Fixes taste not existing for mobs without having their tongue changed](https://www.github.com/tgstation/tgstation/pull/74665)

## Reproduction: Trying to select a fuel fusion recipe in the HFR results in a fatal error bluescreen in NTOS.
1. Construct the HFR
2. Try to select a fuel recipe (IE, something like plasma/oxygen fusion fuel)
3. Get bluescreened

Additionally, refreshing tgui will make it so that it does not crash when you try to select a recipe any more, but it will not open the recipe selection page.

**Comment by jlsnow301** [comment]
#74664
