### ISSUE TITLE
People in closed lockers cannot examine anything

### ISSUE THREAD

**Issue by Chocobro** [tgstation/tgstation#7468]
p sure they're supposed to.

**Comment by bgobandit** [comment]
how can you examine something through a closed locker? feature.

**Comment by Deantwo** [comment]
Can you examine things in your inventory?

**Comment by GunHog** [comment]
This is also an issue with pAIs, if your master has placed you into something.

**Comment by Chocobro** [comment]
nope, can't examine things even in your inventory.
same bug happens when you're in a sleeper, too.

**Comment by tedward1337** [comment]
Pretty sure this was fixed

**Comment by phil235** [comment]
Yep, fixed
