### ISSUE TITLE
Empty list in radio hallucination event

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#74698]
![Screenshot (158)](https://user-images.githubusercontent.com/110812394/231691980-3903ca82-4a3c-45d7-ac2d-784e586f1d7f.png)

**Reproduction**
1. Load up meta station(don't know about others)
2. If your lucky get this error, understand it, fix it, If not then i don't know it's not consistent , happens randomly.

**Comment by Helg2** [comment]
Maybe it occurs because there is no one in crew list?

**Comment by SyncIt21** [comment]
> Maybe it occurs because there is no one in crew list?

This was tested on local  before the game started so most likely. However his error is random
