### ISSUE TITLE
Some ruins stop generating now

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#74725]
Reporting client version: 514.1589

## Round ID:
[203746](https://scrubby.melonmesa.com/round/203746)

## Reproduction:

Certain ruins have stopped generating on the main server at times, for reasons I cannot yet determine. However, I have the following theories.

1: Available Space Exhausted
Add another Z-level and we'll be fine.
2: Ruin Spawn Token Depletion
Ruins work on a sort of 'token' system to spawn in space, however IIRC these were overriden with a high value to allow all ruins to spawn. However, there are not enough tokens for all the ruins added during Mapping March, as such causing some ruins to fail to spawn.

I am issue reporting this as I believe that the intent was for all ruins to spawn equally, if this is not the modern intent please close immediately.

**Comment by dragomagol** [comment]
I would assume this is intended; unless there are specific ruins that are always being skipped, it makes sense that you don't see the same ones all the time.

**Comment by msgerbs** [comment]
Which ruins specifically? There is an open issue for multi-z ruins basically non-functional: https://github.com/tgstation/tgstation/issues/70269

Other than that, any ruin can spawn at random, but the ones that pass checks more easily (IE: Smaller ones) will spawn more often. As you've described, there is a token system used to spawn ruins and the high-priority ones will spawn first followed by everything else. Not all ruins are high priority, unless that changed while I wasn't looking.

If there is a specific ruin or ruins which are just never spawning, that could be an issue still (like was found with multi-z ruins), but beyond that this seems like it's not a bug.
