### ISSUE TITLE
Bananium HONK-Spect Scanner can't be crafted

### ISSUE THREAD

**Issue by Joster730** [tgstation/tgstation#74745]
## Round ID: [203795](https://scrubby.melonmesa.com/round/203795)

 203795, this happened on Manuel

## Reproduction:

 During round 203795 I could not craft the Honk-Spect scanner even though I had all the required materials and tools. When I tried using the crafting menu to make it, the option was grayed out. 

Step 1. Get 5 bananium, 3 sticky tape, an N-Spect Scanner, and a bike horn
Step 2. Open up the crafting menu and attempt to craft the Bananium HONK-Spect Scanner

**Comment by Helg2** [comment]
It uses the fake N-Spect Scanner, which is simply doesn't appear anywhere in-game.

**Comment by TheVekter** [comment]
> It uses the fake N-Spect Scanner, which is simply doesn't appear anywhere in-game.

This is incorrect.

`/**
 * # Fake N-spect scanner black market entry
 */
/datum/market_item/tool/fake_scanner
	name = "Clowny N-spect scanner"
	desc = "This UPGRADED N-spect scanner can play FIVE HIGH-QUALITY SOUNDS (fork required for sound adjustment not included) and print reports \
	LIGHTNING FAST (screwdriver necessary to activate maximum speed not included). We make no claims as to the usefulness of the reports printed by this. \
	Any and all implied warranties are void if the device is touched, moved, kicked, thrown or modified with bananium sheets. Batteries included. \
	Crowbar necessary to change batteries and adjust settings not included."
	item = /obj/item/inspector/clown

	price_min = CARGO_CRATE_VALUE * 1.15
	price_max = CARGO_CRATE_VALUE * 1.615
	stock_max = 2
	availability_prob = 50`

You can get it from the Cargo black market item.
