### ISSUE TITLE
IV drip default animation issue and inability to attach it safely without injecting the chemical

### ISSUE THREAD

**Issue by MTandi** [tgstation/tgstation#74752]
#74724 changed the default transfer rate for IV drips to MAX and now IV drips show active animation by default, even when nothing is attached.

Also now there is no safe way to start injection with small transfer rate, so multiple use cases got broken:

- Case when you want to inject a chemical that can easily cause overdose
- Case when you have a little amount of some precious medicine and you want to start injecting it at the rate of metabolism
- Case when you have a recurring slime extract that may break down if you inject too much plasma
- Case when you want to have two IV drips start injecting at the same rate simultaneously into a hydroponics tray or an empty container
- Case when you want to inject some explosive component with iv drip to delay the explosion reaction
- Others

## Reproduction:

To reproduce the animation bug, find any map-spawned IV drip or craft/spawn it manually.

**Comment by MTandi** [comment]
The easiest solution would be to revert the mentioned PR and add a note to the IV drip description that you can toggle between MIN and MAX with alt-click.

But maybe there is another way to satsfy @carlarctg 's concerns without breaking the mentioned use cases.

**Comment by MTandi** [comment]
A potential solution may be to set the default rate depending on the container and the object:

- Default transfer rate to max if the container is a blood pack, or the drip is a saline glucose solution drip and attached to a carbon
- Default transfer rate to the metabolic rate of major chemical in container if attached to a carbon
- Default transfer rate to 0 if attached to an object

**Comment by msgerbs** [comment]
Honestly the ideal fix is probably to revert that PR and resprite the IV drip (I know I know, WYSI) to look like a modern electronic IV drip which would hint at the need to interact with it like a machine. Another potential fix here would be for the animation to not start if the IV drip is set to 0 so it's more obvious that nothing is happening. This one should be fairly straightforward I would think.

**Comment by msgerbs** [comment]
Can you edit this to just cover the inability to adjust the flow before it starts injecting, and create a separate issue for the animation bug? It will be more clear that way and make it easier to track.

**Comment by MTandi** [comment]
Animations are fixed too.
