### ISSUE TITLE
Sentient Disease cannot infect when someone has a mask on.

### ISSUE THREAD

**Issue by Comxy** [tgstation/tgstation#74755]
## Round ID:
[203832](https://scrubby.melonmesa.com/round/203832)

## Reproduction:
Be a sentient disease. Pick a starting host with a mask on, it has to be toggled up. Try infecting people with the starting symptom which will fail for some reason, even though you will be able to infect them the other way around, if you had a person without a mask toggled up infecting someone with a mask toggled up. Then die from the flu after trying to infect people for 20 minutes and wondering what the hell is going on.

**Comment by TheVekter** [comment]
This is working as intended if you chose the coughing or sneezing symptom.

**Comment by Comxy** [comment]
I am talking about the starting symptom. If you accidentally picked someone with a gas mask on as the starting host you will be soft-locked to one host. Or was that intentional?

**Comment by TheVekter** [comment]
> I am talking about the starting symptom. If you accidentally picked someone with a gas mask on as the starting host you will be soft-locked to one host. Or was that intentional?

To my knowledge, yes. It's a skill issue - don't pick someone who has a mask on for your first host. I believe you can examine them before infecting them.

**Comment by TheVekter** [comment]
> That just seems like an oversight or bad game design ngl

It's neither. Masks are not intended to prevent you from getting sick, they're intended to prevent you from getting _others_ sick. They help prevent you breathing in germs, but the main purpose is to keep you from spreading them when you cough, hence why coughing/sneezing doesn't work as a symptom if your target is wearing a mask.

Sentient Disease has a lot of problems but this isn't one of them.

**Comment by Comxy** [comment]
It is like picking a pen uplink as traitor and the uplink doesn't work because you are the clown and start with a crayon, then calling it intentional game design. You are sabotaged at the start from something you didn't know about and got stuck not being able to play the antag you got assigned to. I call that bad game design but if it somehow is intended, then fair enough. This is just how I see it.

**Comment by TheVekter** [comment]
This isn't the place to complain about antag balance, please do so on the forums or Discord.

**Comment by Comxy** [comment]
I mean, I am not complaining, I am just clarifying why I think it is bad game design.
