### ISSUE TITLE
Carps can bite you through windoors.

### ISSUE THREAD

**Issue by dessysalta** [tgstation/tgstation#74823]
Reporting client version: 514.1587

## Round ID:
[203986](https://scrubby.melonmesa.com/round/203986)

## Testmerges:
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)
- [Experiment with replacing weakrefs in AI blackboard with deleting signals, ideally making it easier to work with and harder to cause hard deletes](https://www.github.com/tgstation/tgstation/pull/74791)

## Reproduction:

1. Piss off the nearest carp
2. Step behind a closed windoor
3. Watch in horror as the carp shifts its teeth through the windoor and into your flesh

This happened at the "destroyed Syndie infiltrator" ruin, if that's anything worth mentioning--specifically the bottom-right windoors.

**Comment by Mooshimi** [comment]
Same behavior as #69110
