### ISSUE TITLE
Scrying wizard being reported as logged out

### ISSUE THREAD

**Issue by Ahammer18** [tgstation/tgstation#7482]
![image](https://cloud.githubusercontent.com/assets/10344968/5991218/565cdcf4-a9a5-11e4-8401-7204c26e12ce.png)

Basically a wizard used his scry ability and it reported him as logged out, almost leading to a nasty misunderstanding.

I believe this happens every time, so its easy to replicate,

**Comment by tedward1337** [comment]
Fixed by #17818
