### ISSUE TITLE
Civilian console can't display correctly SecurEye camera software

### ISSUE THREAD

**Issue by WarerBrow** [tgstation/tgstation#74839]
Reporting client version: 514.1589

## Round ID:
[204027](https://scrubby.melonmesa.com/round/204027)

## Reproduction:
1. Open any civilan console, and try to install SecurEye on it.
2. See the interface with cam selection working, but instead of image - black screens.
3. Dance!

**Comment by Sealed101** [comment]
i think something on the tgui side is fucking it up or uhh something i'm not sure
security camera consoles work fine and they share most of the camera FoV code with the secureye app, so it's some kind of tgui update failure i'm guessing?
