### ISSUE TITLE
Larva's have incorrect examine text on them.

### ISSUE THREAD

**Issue by Helg2** [tgstation/tgstation#74859]
## Reproduction:
1. Examine Alien Larva
2. See this:
![image](https://user-images.githubusercontent.com/93882977/233214426-afa48abd-ebf1-4ea9-92ce-9161ede1c3df.png)

**Comment by Helg2** [comment]
> Not incorrect

So theyre supposed to have it?

**Comment by Time-Green** [comment]
I mean they dont have any arms or legs ;_;

**Comment by Time-Green** [comment]
they don thave limbs ;_;

**Comment by Helg2** [comment]
Why not incorrect then ._.
