### ISSUE TITLE
Fugitive/Hunters spawn/trigger and objective system is bugged.

### ISSUE THREAD

**Issue by Googles-Hands** [tgstation/tgstation#74855]
## Reproduction:

Now, as there are MANY things wrong with it, I can split them up in different issues later, but for now, I'll have them all in one.

1. Fugitives only get triggered when the shuttle is called. I've seen this happen accross multiple rounds in the last few days. They only spawn once the shuttle gets called, which gives the Hunters who spawn 10 minutes later, no time to actually hunt.
2. Fugitive objectives/round-end-report are bugged. For example, all fugitives are captured alive and the round end says it's a "Major Hunter Victory" when it should be "Badass Hunter Victory" or the fugitives die but don't get captured, it should be "Fugitive Victory" but gets counted as a "Fugitive Major Victory".

There is no direct evidence for the first point as I did not write the round numbers down. All I can say is what I've seen.

For the second point there are also no round numbers I can provide, I reproduced the error locally and on the servers themselves I took this screenshot a couple of days ago but could not track the round down via Scrubby:
![Screenshot 2023-04-18 225103](https://user-images.githubusercontent.com/59937074/233283667-d61264c3-92d7-4607-93ec-13ca2191d6a5.png)

**Comment by Googles-Hands** [comment]
> So 1 and 3 aren't bugs, just a badmin pressing buttons

Alright, I didn't know it went to that extent, but I am fairly certain that the few times I've seen fugitives spawn was shortly after the shuttle was called. The objectives are also bugged. I'll update the issue.

**Comment by TheVekter** [comment]
> Fugitive objectives/round-end-report are bugged. For example, all fugitives are captured alive and the round end says it's a "Major Hunter Victory" when it should be "Badass Hunter Victory" or the fugitives die but don't get captured, it should be "Fugitive Victory" but gets counted as a "Fugitive Major Victory".

Make this its own issue.
