### ISSUE TITLE
Wielded pillows break riot shields

### ISSUE THREAD

**Issue by WarerBrow** [tgstation/tgstation#74876]
Reporting client version: 514.1589

## Round ID:
[204121](https://scrubby.melonmesa.com/round/204121)

## Testmerges:
- [Make sslibrary init faster by loading bookcases asynchronously in parallel ](https://www.github.com/tgstation/tgstation/pull/74835)
- [Refactors and defuckulates dbcore. Adds support for min_threads rustg setting, Reduce query delay, Make unit tests faster](https://www.github.com/tgstation/tgstation/pull/74852)

## Reproduction:

Well, subject. Don't know if this bug or feature though:

1. Wield pillow in both hands
2. Hit someone with a riot shields a couple of dozens of times (no more than 30)
3. Watch as riot shield breaks to glass!

**Comment by Jackal-boop** [comment]
We should be able to fill pillows with bricks

**Comment by optimumtact** [comment]
feature

**Comment by moocowswag** [comment]
physical shields like wooden shields break to stamina damage including from disablers.
