### ISSUE TITLE
Alien Limb Grower menu doesn't show things normally.

### ISSUE THREAD

**Issue by Helg2** [tgstation/tgstation#74875]
## Reproduction:
1. Spawn limbgrower/fullupgrade
2.  Try to interfere with it and see this: 
![image](https://user-images.githubusercontent.com/93882977/233424877-a9e7e403-a1ff-4310-8fb4-ea838ca2391e.png)
also felinids don't have their own subcategory and their organs are located in humans subcategory.

**Comment by msgerbs** [comment]
Can you pretend I've never used the Alien Limb Grower and explain to me what's wrong about the screenshot (or post other screenshots demonstrating it)? I don't understand, sorry.

**Comment by Helg2** [comment]
> Can you pretend I've never used the Alien Limb Grower and explain to me what's wrong about the screenshot (or post other screenshots demonstrating it)? I don't understand, sorry.

This is a screen of how common limbgrower menu looks like, without upgrades but that doesn't matter:
![image](https://user-images.githubusercontent.com/93882977/233706328-b359d41a-fc1b-430e-b917-68da5a057f02.png)
And that's how fullupgrade looks like:
![image](https://user-images.githubusercontent.com/93882977/233706424-24e8e40f-809a-4f27-a434-d1f05188de0b.png)
The problem is that it just repeats its build paths a second time and just clutters up the menu, which is why it looks like this. If you choose "left arm" from the start of list and "left arm" from the middle it will give you the same result.

**Comment by msgerbs** [comment]
Oh, I see what you mean now. Seems like probably a simple fix.

**Comment by Sealed101** [comment]
related code:
https://github.com/tgstation/tgstation/blob/050fcfcded861b379f64237e1f7bef3a67f0d7e6/code/game/machinery/limbgrower.dm#L284-L289

it's uploading every available limb/organ design as imported, thus we get duplicates
