### ISSUE TITLE
Storage datum can_hold typecaches are incomplete.

### ISSUE THREAD

**Issue by Timberpoes** [tgstation/tgstation#74907]
## Commit thing was broken on:
https://www.github.com/tgstation/tgstation/commit/46b2319559c951c04bd2fd42f6542daa69a19756
![image](https://user-images.githubusercontent.com/24975989/233748591-70ab6b88-749b-460f-88d0-ec64d8fd1ae1.png)

## Commit thing was not broken on:
https://www.github.com/tgstation/tgstation/commit/addf5ae682c04894f4532f4cf7516f23ce387c70
![image](https://user-images.githubusercontent.com/24975989/233748596-b451570c-4b1b-4113-9401-781076870037.png)

## Reproduction:
Play on any server after the broken commit, spawn in a paramedic belt, watch as you probably can't insert any of its contents back into it.

Probably broken by https://github.com/tgstation/tgstation/pull/74769

**Comment by NamelessFairy** [comment]
Based on some mostly bruteforce testing it seems like the specific area in code where this is caused is:
```
for(var/i in 1 to ROUND_UP(pathlen / 5))
	for(var/subpath in typesof(pathlist[i], (i + 1 <= pathlen) ? pathlist[i + 1] : null, \
		(i + 2 <= pathlen) ? pathlist[i + 2] : null, (i + 3 <= pathlen) ? pathlist[i + 3] : null, \
		(i + 4 <= pathlen) ? pathlist[i + 4] : null))
		.[subpath] = TRUE
```
(Line 313 of _lists.dm)
I suspect the maths here must be off since both loops are ending before the list passed to can_hold is actually complete.

**Comment by DaydreamIQ** [comment]
This is affecting sec belts as well too

**Comment by Cheshify** [comment]
This is affecting chem/plant/xenobio bags as well I believe.
