### ISSUE TITLE
Catwalks immune to new space color

### ISSUE THREAD

**Issue by MTandi** [tgstation/tgstation#74905]
Catwalks and everything that is on them is immune to the new blue tint of space.

![image](https://user-images.githubusercontent.com/3625094/233736938-7c5b3b57-c6c8-47a8-bc5a-362c40649ae7.png)

![image](https://user-images.githubusercontent.com/3625094/233736961-140e22f0-9c56-40a7-ae8b-59a2b0d20c7c.png)

## Reproduction:

Spawn at solars and try walking on catwalk and on tile with plating, the character loses and gains blue tint.

**Comment by MTandi** [comment]
@LemonInTheDark FYI

**Comment by LemonInTheDark** [comment]
closed by #74887 when merged (life is pain, thanks for the report)

**Comment by MTandi** [comment]
@LemonInTheDark now cantwalks are ok, but the newly constructed tiles in space ignore the tint. Not sure if related.

![image](https://user-images.githubusercontent.com/3625094/233780108-582d7fb0-fd47-4e19-8a71-e8c126e98a68.png)

**Comment by MTandi** [comment]
Also during the event when the starlight changes color, catwalks remain blue 

![image](https://user-images.githubusercontent.com/3625094/233789964-c2c6441c-89a1-4400-9ad3-33b5364176c5.png)

**Comment by LemonInTheDark** [comment]
> @LemonInTheDark now catwalks are ok, but the newly constructed tiles in space ignore the tint. Not sure if related.
> 
> ![image](https://user-images.githubusercontent.com/3625094/233780108-582d7fb0-fd47-4e19-8a71-e8c126e98a68.png)

s not strictly related but it is something I need to fix yes

> Also during the event when the starlight changes color, catwalks remain blue
> 
> ![image](https://user-images.githubusercontent.com/3625094/233789964-c2c6441c-89a1-4400-9ad3-33b5364176c5.png)

This is because starlight only updates for space turfs in the /nearspace area
I have plans to improve on this, the solution would be a global list of "starlit" turfs that we can iterate, alongside changing a global var or something. Someday.
