### ISSUE TITLE
Missing a leg slows you down in space with a jetpack and in no-gravity

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#74911]
## Round ID:

Round id : 204201

Honestly not much to say but title. Shouldn't do that considering you aren't using your legs to self-propel.  Confirmed as bug
![image](https://user-images.githubusercontent.com/53100513/233757771-dd82921d-c000-4005-96d0-1dd9ad24f1ca.png)

## Testmerges:

[#74775: 'Adds TTS to the game. Players can select their own voices in preferences.' by Watermelon914 at commit 543dc77055](https://www.github.com/tgstation/tgstation/pull/74775)

**Comment by BlueMemesauce** [comment]
Should technically move faster due to less mass
