### ISSUE TITLE
Stuff isnt fitting inside belts like batons or tools

### ISSUE THREAD

**Issue by rageguy505** [tgstation/tgstation#74915]
Reporting client version: 514.1589

## Round ID:
[204213](https://scrubby.melonmesa.com/round/204213)

## Testmerges:
- [World Initialization Refactor](https://www.github.com/tgstation/tgstation/pull/74808)
- [Drastically improves north star / multi-z performance by trimming down on camera upwards visibility](https://www.github.com/tgstation/tgstation/pull/74822)
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)
- [Adds TTS to the game. Players can select their own voices in preferences.](https://www.github.com/tgstation/tgstation/pull/74775)

**Comment by SyncIt21** [comment]
#74914 & #74910 should have fixed this. Report back in a few hours if the issue still persists.

**Comment by rageguy505** [comment]
Didn't see a issue open, was just making sure so everyone else dosent just say known issue while it isn't on the git

**Comment by Likteer** [comment]
Can confirm, round 204212
![obraz](https://user-images.githubusercontent.com/68878861/233774926-bf0c3613-6e41-43bc-b1e1-d1d674eba800.png)

**Comment by necromanceranne** [comment]
Possible culprit? https://github.com/tgstation/tgstation/pull/74139

**Comment by SyncIt21** [comment]
> Can confirm, round 204212 ![obraz](https://user-images.githubusercontent.com/68878861/233774926-bf0c3613-6e41-43bc-b1e1-d1d674eba800.png)

Can confirm this is no longer a bug on local. Have to wait till the server's update on the next round

https://user-images.githubusercontent.com/110812394/233775603-41f175c0-1f7e-4e0e-bc44-a755505e7fe8.mp4

**Comment by SyncIt21** [comment]
> Possible culprit? #74139

No bug here

**Comment by ZephyrTFA** [comment]
Resolved, just wait for servers to update.
