### ISSUE TITLE
Warden cannot access Brig cells

### ISSUE THREAD

**Issue by RoderickGrey** [tgstation/tgstation#74928]
## Round ID:[204245](https://scrubby.melonmesa.com/round/204245)

<!--- **INCLUDE THE ROUND ID**
If you discovered this issue from playing tgstation hosted servers:
[Round ID]:  [204245](https://scrubby.melonmesa.com/round/204245)

## Reproduction:

Attempted to open brigcells as a latejoin warden., could not. Officer I.Ds and even the HoP I.D worked fine.

**Comment by msgerbs** [comment]
I assume this is on Delta Station, can you edit the issue to reflect that? I also assume you mean the warden didn't have access to the windows on the cells?

**Comment by RoderickGrey** [comment]
No it was on birdshot

**Comment by BlueMemesauce** [comment]
Can confirm that it is an issue
All members of security, not just the warden, are unable to access the doors labeled "Brig Cells" on Birdshot. However, the Captain is able to access it. So there must be a wrong type of access given to the door.
https://user-images.githubusercontent.com/47338680/233877026-8fc81b0a-1694-4d41-9fa4-feb186925f43.mp4

**Comment by Zytolg** [comment]
I don't know why it's doing this, I initially updated the doors to use the general sec and lawyer accesses but apparently lawyer access was overriding the doors? It's back down to general sec access now. Old system was easier, door helpers bad.

**Comment by msgerbs** [comment]
You just need to use the Any Access helpers, you probably used the All Access ones which require the person to have all of the accesses. Almost every location should use Any Access helpers.

**Comment by JohnFulpWillard** [comment]
If this is still a problem please put it on the PR itself
