### ISSUE TITLE
The traitor panel and round end report shows conflicting "completion" status of Traitors final objective

### ISSUE THREAD

**Issue by Draggeru** [tgstation/tgstation#74929]
## Reproduction:
Place the cascade crystal into the sm to start the cascade, then end the round. The TP shows the objective has been skipped, but the round-end report shows the objective to be completed. On MRP the final objective being completed gives traitors the ability to murderbone. These two information sources being different complicates admin-related decisions for this policy.

**Comment by Profakos** [comment]
Also note, when you take a final objective, it automatically counts as completed according to the uplink.

**Comment by Watermelon914** [comment]
Yes, you cannot officially 'complete' a final objective, this is not a bug. Final objectives don't have a completion state, reaching the final objective is the end.

**Comment by Watermelon914** [comment]
After some local testing though, I've found that the 'Skipped' text on the final objective is a bug though.
