### ISSUE TITLE
Sokoban station - Engineers cannot actually access the gravity generator's interface

### ISSUE THREAD

**Issue by plutori** [tgstation/tgstation#74969]
Reporting client version: 514.1589

## Round ID:
[204409](https://scrubby.melonmesa.com/round/204409)

**Comment by rageguy505** [comment]
This would probably be a better issue for the map depot. Sokoban isn't found here.
https://github.com/tgstation/map_depot

**Comment by plutori** [comment]
> This would probably be a better issue for the map depot. Sokoban isn't found here. https://github.com/tgstation/map_depot

I don't actually see an issues button on map depot, am I blind?

**Comment by rageguy505** [comment]
> > This would probably be a better issue for the map depot. Sokoban isn't found here. https://github.com/tgstation/map_depot
> 
> I don't actually see an issues button on map depot, am I blind?

no it doesn't exist. ill put a fix for it anyways

**Comment by plutori** [comment]
> > > This would probably be a better issue for the map depot. Sokoban isn't found here. https://github.com/tgstation/map_depot
> > 
> > 
> > I don't actually see an issues button on map depot, am I blind?
> 
> no it doesn't exist. ill put a fix for it anyways

The funniest way to fix this would be to just replace the reinforced wall 1 tile south of the gravgen with an airlock, so you still have to go through space to reach it. Completely in the spirit of the map.

**Comment by Fikou** [comment]
not a tgstation codebase
