### ISSUE TITLE
headphones not showing animation when placed on ears

### ISSUE THREAD

**Issue by heepox** [tgstation/tgstation#74965]
## Reproduction:

Play music on headphones and put them on your ears instead of your head slot
the animated notes wont show up at all.
only when placed on the head slot will they show up.

**Comment by Rex9001** [comment]
Attempted to reproduce this bug, but it didn't occur to me

**Comment by heepox** [comment]
![Notes](https://user-images.githubusercontent.com/48312144/235329918-b1e2bf93-de9c-41bb-b484-08c8d6978bc1.png)
![Nonotes](https://user-images.githubusercontent.com/48312144/235329924-72f1bc36-e4a8-4003-8a7b-a6787f7db2f6.png)
