### ISSUE TITLE
holorecord disk recordings do not look like holograms when played from the holopad

### ISSUE THREAD

**Issue by kawoppi** [tgstation/tgstation#74975]
## Round ID:
[204407](https://scrubby.melonmesa.com/round/204407)

## Testmerges:
 The following pull requests are currently test merged:
[#74775: 'Adds TTS to the game. Players can select their own voices in preferences.' by Watermelon914 at commit 543dc77055](https://www.github.com/tgstation/tgstation/pull/74775)
[#73502: 'Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]' by Zytolg at commit 7a6713a1aa](https://www.github.com/tgstation/tgstation/pull/73502)

## Reproduction:
Put a holorecord disk in a holopad and record yourself. Then play the recording back. The hologram will look just like a normal person instead of being all blue with scanline artifacts and whatnot.
![holograms](https://user-images.githubusercontent.com/94711066/234342415-d2fc9e7a-f97a-4172-9aee-7ffa7568ac9d.PNG)
left: real (cat)person, right: hologram projection of a (cat)person

I think the projection beam effect is gone from the holopad recording now too, or it may have only been on the AI projection I'm not sure.

**Comment by SyncIt21** [comment]
Probably broken by #73793. 
CC @LemonInTheDark

**Comment by LemonInTheDark** [comment]
god damn it

**Comment by LemonInTheDark** [comment]
the bream was only ever on ais and calls, but I've fixed that too, so it'll look less jank
