### ISSUE TITLE
You can no longer become a gorilla via genetic damage like you should

### ISSUE THREAD

**Issue by ophaq** [tgstation/tgstation#74981]
## Testmerges:
One of the recent PRs to how genetics works or genetic damage maybe?

## Reproduction:
Step 1: Have someone copy your enzyme/makeup.
Step 2: Have them replace your enzyme full appearance makeup to build up genetic damage + make sure they scramble (gives about 40% genetic damage each time). Do this repeatedly at each genetic computer until you reach 600 (what I heard was the minimum threshold) or the wiki's recommended 2500. Go to 2600 to be safe if you're doing 2500.
Step 3: Use monkey mutator.
Step 4: Wait a bit. You have like a 2.5% chance or something, or you are supposed to. I waited over 30 minutes at both 600 genetic damage and 2600, no gorillification.

I went through this in round with an experienced genetics player and they told me they've done this at 600 genetic damage. We both tried this at 600 and 2600 thresholds. No luck, waited through an hour 1/2 shift. Tried it on a second monkey too, no luck. We are in belief that gorillification is borked.

Also, genetic damage does not damage you with toxin as fast as it is supposed to I think. I had a toxin bot with me and took toxin damage very slowly.

**Comment by moocowswag** [comment]
Im wondering if it has to do with the radiation reworks that have happened in the past 2 years.

**Comment by limeenjoyer** [comment]
I played during this round and was the geneticist assisting ophaq with becoming a gorilla. As already mentioned, over the course of a long round neither ophaq nor a second npc monkey transformed into gorillas despite spending the majority of the shift with significant (greater than 500%) genetic damage. 

Normally, I'd just consider this bad luck, but genetic damage was behaving unusually: the genetic damage itself was decaying much slower than I've seen before. The toxin damage that it applies was also being inflicted at an equally slow pace. If I had to guess, I would say that the gorilla transformation chance is rolling at this slower speed as well making it unreasonably difficult to achieve.

This is the most recent PR I could find regarding genetic damage: #74799

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/0da072d0d86175e22caf876d056cb03b74e428e0/code/datums/status_effects/debuffs/genetic_damage.dm#L1-L2

https://github.com/tgstation/tgstation/blob/0da072d0d86175e22caf876d056cb03b74e428e0/code/datums/status_effects/debuffs/genetic_damage.dm#L34-L39

**Comment by BlueMemesauce** [comment]
It worked for me on round 200443
https://scrubby.melonmesa.com/round/200443

You just need to be a monkey and have a shit ton of genetic damage. Like so much genetic damage it takes 20 minutes of constantly reshuffling someone's DNA to get it.

**Comment by Rex9001** [comment]
> It worked for me on round 200443 https://scrubby.melonmesa.com/round/200443
> 
> You just need to be a monkey and have a shit ton of genetic damage. Like so much genetic damage it takes 20 minutes of constantly reshuffling someone's DNA to get it.

Sounds like the minimum might have increased? Unsure

**Comment by JohnFulpWillard** [comment]
It could be possible that https://github.com/tgstation/tgstation/pull/74799 messed something with it, but we don't know as this isn't currently unit tested anywhere.

**Comment by BlueMemesauce** [comment]
Probably that PR as it falls between now and when gorillas worked

**Comment by ophaq** [comment]
Did another test on private server. 4 Clones of me, given 20000 genetic damage (that's 4000% in the genetics console) through VV. Waited around an hour afk to see if they would do anything and nothing really happened. There was one some kind of exception error that popped up in VS Code around 30 minutes however, relating to the transformation of gorilla where timothymtorres referenced.

**Comment by Jacquerel** [comment]
> Did another test on private server. There were 4 clones of me, given 20000 genetic damage (that's 4000% in the genetics console) through VV. Monkified them and waited around an hour afk to see if they would do anything and nothing really happened. There was one some kind of exception error that popped up in VS Code around 30 minutes however, relating to the transformation of gorilla where timothymtorres referenced.

For reference if you feel like doing some kind of investigative work like this again in the future, actually copying down what the exception error _is_ and where vscode is pointing you at would have been an enormous timesaver.
Knowing that there is "something" wrong there is helpful but now someone will have to take exactly the same steps you did again to find out that information you had on your screen 😅

**Comment by ophaq** [comment]
> > Did another test on private server. There were 4 clones of me, given 20000 genetic damage (that's 4000% in the genetics console) through VV. Monkified them and waited around an hour afk to see if they would do anything and nothing really happened. There was one some kind of exception error that popped up in VS Code around 30 minutes however, relating to the transformation of gorilla where timothymtorres referenced.
> 
> For reference if you feel like doing some kind of investigative work like this again in the future, actually copying down what the exception error _is_ and where vscode is pointing you at would have been an enormous timesaver. Knowing that there is "something" wrong there is helpful but now someone will have to take exactly the same steps you did again to find out that information you had on your screen 😅

I know. But I instinctively hit f5 and ignored it before remembering to do so, and yeah, oops.

**Comment by AverageUser67** [comment]
Not Monkey Mode!
Although I'm not sure who decided you could be a gorilla without magillitis only using roundstart genetics equipment

**Comment by ChungusGamer666** [comment]
> It could be possible that #74799 messed something with it, but we don't know as this isn't currently unit tested anywhere.

Did not mess with it, behavior should be functionally identical to what it was before.

**Comment by Sealed101** [comment]
the issue is that the genetic damage status effect gets deleted when trying to make a gorilla, thus the following `carbon_owner` var has no `owner` to get set to, and so the `gorillize()` has nothing to do its namesake on.

after #74799, status effect era
https://github.com/tgstation/tgstation/blob/a4c1f6298e821a6449108e19c2d31c323a7e79cd/code/datums/status_effects/debuffs/genetic_damage.dm#L34-L39

before #74799, component era
https://github.com/tgstation/tgstation/blob/7ad8223ed94253254afd7bf580b89ad1cb886f02/code/datums/components/genetic_damage.dm#L45-L50
