### ISSUE TITLE
Bugged floodlight frame won't take bulbs

### ISSUE THREAD

**Issue by MrSandman2000** [tgstation/tgstation#75000]
Reporting client version: 515.1603

## Round ID:
[204517](https://scrubby.melonmesa.com/round/204517)

## Testmerges:
- [Adds TTS to the game. Players can select their own voices in preferences.](https://www.github.com/tgstation/tgstation/pull/74775)
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)

## Reproduction:
No matter what light you put in a floodlight, it always reads as broken, i was playing as a Engineer and i kept trying to put NON BROKEN large bulbs into a floodlight frame, but it kept saying it was broken, despite it not being broken, i even tried with a live bulb that was on the wall next to me and still didn't work.

**Comment by SyncIt21** [comment]
From the [Wiki](https://tgstation13.org/wiki/Guide_to_construction#Floodlight) you are meant to add only light tube not bulbs, the bulbs keep breaking because the default behavior is you attack the frame with the bulb causing it to break if the floodlight doesn't accept it.

Not a bug

**Comment by ZephyrTFA** [comment]
Floodlights take tubes not bulbs, which can be read if you examine them.

**Comment by Bawhoppen** [comment]
Sadly a wasted get
