### ISSUE TITLE
Syndicate base didn't spawn?

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#75012]
Reporting client version: 514.1589

## Round ID:
[204560](https://scrubby.melonmesa.com/round/204560)

## Testmerges:
- [Adds TTS to the game. Players can select their own voices in preferences.](https://www.github.com/tgstation/tgstation/pull/74775)
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)

## Reproduction:
Go to observe, type in all keywords that have anything to do with "syndicate" or the like and its just not there.
Same with the missing syndicate infiltrator orbit point.
![image](https://user-images.githubusercontent.com/36141254/234961117-9fe46832-a51d-4a11-968e-58a7d873b181.png)
![image](https://user-images.githubusercontent.com/36141254/234961250-c629be12-5482-40d2-81ba-59564a43f798.png)

**Comment by Time-Green** [comment]
Pretty sure it’s lazyloaded and will only spawn when needed

**Comment by Mothblocks** [comment]
Correct
