### ISSUE TITLE
TTS Male 16 Voice Pronounces 'huh' VERY incorrectly

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#75027]
Reporting client version: 514.1589

## Round ID:
[204661](https://scrubby.melonmesa.com/round/204661)

## Testmerges:
- [Adds TTS to the game. Players can select their own voices in preferences.](https://www.github.com/tgstation/tgstation/pull/74775)
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)

## Reproduction:
Attempting to say the word 'huh' while using Male 16 voice makes you say something much longer and incomprehensible than that word, described by  an admin as sounding like 'Duwantonieboobs'. Sound appears to only be audible to the person speaking, as bystanders didn't notice anything different and the admin only heard it when possessing me. Video attached.

https://user-images.githubusercontent.com/88996803/235267683-905cd5fd-3ee8-4ac6-af3b-d17c00074c04.mp4

**Comment by Mothblocks** [comment]
Please report this on https://github.com/tgstation/tgstation/pull/74775
