### ISSUE TITLE
Job Manuals not working

### ISSUE THREAD

**Issue by Richie9999** [tgstation/tgstation#75047]
Reporting client version: 514.1589

## Round ID:
[204766](https://scrubby.melonmesa.com/round/204766)

## Testmerges:
- [Adds TTS to the game. Players can select their own voices in preferences.](https://www.github.com/tgstation/tgstation/pull/74775)

## Reproduction:

Player prays "funny html book" examine book. Is a job manual that should link to the wiki and display part of it. It does not. Just displays some code. Check the bartender book. Similar result. Try a total of four books all with the same result. Conclude it is likely a bug and write up a bug report.

**Comment by Jolly-66** [comment]
Fixed by #79589
