### ISSUE TITLE
Tramstation Genetics Pen uses turfs that can turn into Chasms

### ISSUE THREAD

**Issue by OrionTheFox** [tgstation/tgstation#75054]
## Round ID:
N/A (Downstream - reverified on plain TG code)

## Reproduction:
On Tramstation, in the Genetics Lab's monkey pen, strip any of the jungle dirt down to the baseturf (explosions, vortex anomalies, etc etc)
The turf will become a chasm

![dreamseeker_U6zDixoMcw](https://user-images.githubusercontent.com/76465278/235347529-6096b828-72a7-4520-b219-262c3a9db2a6.png)

As funny as this is, it's likely not intended.

## Relevant Code Info:
Verified to be a TG upstream issue
![image](https://user-images.githubusercontent.com/76465278/235347554-38eb9c68-aa23-4732-b15b-94aa481470e2.png)

**Comment by Sealed101** [comment]
incredible

making a separate jungle astroturf with a proper plating baseturf would work fine perhaps
