### ISSUE TITLE
Found green turf it told me to come here and yell

### ISSUE THREAD

**Issue by anonymous13ify** [tgstation/tgstation#75056]
## Reproduction:
I was mining on icebox, was using a advanced resonator, blew some gibtonite using it, and then there was the turf that upon inspection told me to yell at coders if i wasnt a ghost. RE, CODERS BAD!

![GREENTURFEMRUHGAWD](https://user-images.githubusercontent.com/76134745/235350033-db65e7cb-3286-421e-8aca-1792f5992a11.png)

**Comment by Addust** [comment]
funky genturf

**Comment by optimumtact** [comment]
scrape turf moment
