### ISSUE TITLE
Taking items from your inventory while flying over lava will set them on fire

### ISSUE THREAD

**Issue by o-d-a-z** [tgstation/tgstation#75081]
Reporting client version: 514.1589

## Round ID:
[204837](https://scrubby.melonmesa.com/round/204837)

## Testmerges:
- [Adds TTS to the game. Players can select their own voices in preferences.](https://www.github.com/tgstation/tgstation/pull/74775)
- [Taking Brute or Burn Damage Reduces Stuns](https://www.github.com/tgstation/tgstation/pull/75063)

**Comment by rasepretep** [comment]
Items will also appear to fall down a z-level if flying, or appear to fall into a chasm if above one. Neither of those actually fully happens, but it's clear that taking an item out of inventory briefly lets it be affected by whatever tile you're on.

**Comment by Sealed101** [comment]
affects taking things out of any storage in general, taking things out of your equipment slots or from adjacent tiles seems fine. the non-zlevel chasms do actually eat items, multi-z just teleports them back to you basically. roflmao
