### ISSUE TITLE
Birdshot: Chem factory too small to be viable for gameplay

### ISSUE THREAD

**Issue by YehnBeep** [tgstation/tgstation#75080]
This was mentioned in #73502 but since the recent Kilo removal discussion seemed to suggest issues should be made for stuff like this... making it here.

The birdshot chem factory is too small for chem factory gameplay. Using these screenshots for example:

![image](https://user-images.githubusercontent.com/86855173/235384587-d9a757f2-5124-42c6-98c7-05066451af54.png)
![image](https://user-images.githubusercontent.com/86855173/235384592-c0deb066-c7e4-43e3-b3b6-8d4489116f6d.png)

The factory also extends a bit further than can be seen to the north. This is a degraded-functionality chem factory but further expansions would require building even more in the hallways and/or thermit'ing out the wall and building into the general hallway. And even getting this much required deconstructing parts of the factory room.

There really needs to be more space here for chem factory gameplay to work - unless people are happy with 10~15 minute builds that make hardly anything - or consuming the medbay hallways, or a thermite-expansion into the general hallway.

Lastly, as a much more minor issue - it could use more starting metal. More so that a factory chemist doesn't frustrate people by draining the silo early in (than because they can't build), and considering that as the new minimum-pop station, full mining staff will likely be a rare sight under these conditions.

**Comment by Singul0** [comment]
these kind of stuff is very hard to fix without reworking entire sections of the map

**Comment by YehnBeep** [comment]
Yeah :(

Makes me wish the mapper had taken a look at kilo and realized the chem lab wasn't that big out of the mappers' generosity, but, Kilo's gone and birdshot's here so to have chem factory play, something has to be figured out. I've kind of had thoughts about maybe just try to push out the stuff to the west and south, though it's a little ambitious for me.

**Comment by JohnFulpWillard** [comment]
I don't think this is issue-report worthy. You're fine to make changes but this isn't something we should keep on our issue tracker.

**Comment by YehnBeep** [comment]
I mean... this is akin to say, an unbuildable console a job needs being missing or similar. Larger scale and harder to address - but it's an issue that prevents meaningfully engaging with the gameplay.
