### ISSUE TITLE
Immovable Rods still loop sometimes even if we tell them not to

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#75088]
## Reproduction:

- Trigger Immovable Rod event.
- When asked if we want to force the rod to loop, choose "no".
- Rod still loops sometimes

I have no idea if this is intended or if we just can't fix it but it's kind of annoying. I don't want to "fix" looping rods, but I'd like to not have to manually delete it if I don't want it to loop just because I'm sniping something.

**Comment by ArcaneDefence** [comment]
Wouldn't this happen if you had a natural loop made from the z level transitions on that round and the rod randomly selected that direction

**Comment by TheVekter** [comment]
Okay, I'd always assumed the rod looping was a bug because it didn't make any sense to me.
