### ISSUE TITLE
Lord of the Night doesn't handle multi-z stairs well

### ISSUE THREAD

**Issue by AverageUser67** [tgstation/tgstation#75093]
Specifically, they always "crash into the plating with a sickening noise!" (not sure if they take damage or not, this was done on my local game)
They can also push stairs sometimes which resulted in mobs not being able to traverse them, basicmob or carbon.
Map was Northstar, I am not sure if this happens on other maps with stairs like chilled or tram

**Comment by lizardqueenlexi** [comment]
This is not actually specific to the Lord of the Night - any mob that can damage structures by walking into them does this same thing. For example, ice whelps on Icebox, when fed intelligence potions, can't escape the lower floor of the mining wing because they ruin the stairs.

**Comment by AverageUser67** [comment]
(partial) fix yippee
