### ISSUE TITLE
Minimizing apps on modular computers does not clear the screen properly

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#75108]
Reporting client version: 514.1589

## Round ID:
[204917](https://scrubby.melonmesa.com/round/204917)

## Testmerges:
- [New Medical job: The Coroner](https://www.github.com/tgstation/tgstation/pull/75065)

## Reproduction:
Minimizing an app on a modular computer (Whether its a PDA, computer, laptop, ETC.) seems to fail to bring the screen back to the start screen, and replaces the buttons normally used to close an app with only the power off button.
Re-opening the computer of choice by closing the window and reusing the computer it brings it back to the start screen.
1. Acquire computer
2. Download or open an app.
3. Minimize.
4. Screen remains on the app.
5. Close the window, or turn off the computer to get back to the start screen.

**Comment by SyncIt21** [comment]
Duplicate #75046
