### ISSUE TITLE
Derelict drone dispenser just flat out dosen't work

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#75104]
Reporting client version: 514.1589

## Round ID:
[204912](https://scrubby.melonmesa.com/round/204912)

## Testmerges:
- [New Medical job: The Coroner](https://www.github.com/tgstation/tgstation/pull/75065)

## Reproduction:
Attempt to put ores in dispenser
Nothing happens
Realize the power is out
Power the room
Still nothing
Try clicking it with an empty hand
Still nothing
Admin comes in to try to put in ores
Still nothing

**Comment by SyncIt21** [comment]
@Sealed101 Never been able to reproduce till date. Should be safe to close
