### ISSUE TITLE
Paint has a var, `paintleft`, which is never decremented 

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#75110]
## Reproduction:

![image](https://user-images.githubusercontent.com/51863163/235571910-2056a376-4540-44e1-a2fa-4e45cf1945e0.png)

It seems as if paint is intended to have it uses decrement but no code decrements it.

**Comment by LemonInTheDark** [comment]
man wtf

**Comment by NamelessFairy** [comment]
Caused by https://github.com/tgstation/tgstation/pull/2375
