### ISSUE TITLE
birdshot doesn't have a working gulag

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#75119]
Round ID: [204926](https://tgstation13.download/parsed-logs/sybil/data/logs/2023/05/02/round-204926/)
Parsed Successfully 41 Players 44 Files

Reproduction: Birdshot is missing prisoner IDs on the table next to the gulag shuttle console, so you can't send anyone to gulag. If you use perma prisoner IDs, they work, but after completing your points you have no access to get out of the gulag shuttle, so you're trapped in.

A greater issue is that you have no access to leave the gulag area of the brig, and it's fairly far from the rest of brig, meaning most seccies are not going to walk all the way down to let you out (or notice that you finished).

**Comment by BeeSting12** [comment]
Additionally when I gulagged you your stuff dropped on the teleporter. Should be in the bluespace locker or whatever it does with prisoners stuff

**Comment by SinfulBliss** [comment]
Right, the bluespace gulag locker also doesn't work (or exist?) in Birdshot. It just drops all their items on the floor (so anyone could steal them when they get out gulag). Not sure if that needs a separate report or not

**Comment by DATA-xPUNGED** [comment]
> Right, the bluespace gulag locker also doesn't work (or exist?) in Birdshot. It just drops all their items on the floor (so anyone could steal them when they get out gulag). Not sure if that needs a separate report or not

I was gonna fix that in my, uh, 3 PRs, but i was hopelessly confused by the term "gulag locker", i will try fixing it now

**Comment by TheVekter** [comment]
The prisoner IDs appear to be there now, no clue when they were added.

![image](https://github.com/tgstation/tgstation/assets/7019927/78b2a204-71dc-4a2e-b68a-6cc779a2bc58)

Anything else that needs to be changed here, or is it working now?
