### ISSUE TITLE
Spiderlings get stuck in spiderwebs

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#75114]
## Round ID:

spiderlings get stuck in spiderwebs

@san7890 #75001

**Comment by moocowswag** [comment]
One thing ive noticed is webs themselves seem to be tied to specific factions or entities or something because when i made webs via mutation in my maint base the giant spiders that attacked it ended up getting stuck in my webs.

**Comment by SethLafuente** [comment]
fixed now they just get stuck in sticky webs
