### ISSUE TITLE
Birdshot's kitchen is missing a range for making soup

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#75128]
Reporting client version: 514.1589

## Round ID:
[204966](https://scrubby.melonmesa.com/round/204966)

## Testmerges:
- [New Medical job: The Coroner](https://www.github.com/tgstation/tgstation/pull/75065)

## Reproduction:
The kitchen on Birdshot is missing a range. Its got the oven, but they were recently included to have a range on the oven itself, which prevents the use of soup pots.

I have no range and I must make soupe.

**Comment by DATA-xPUNGED** [comment]
soup will be real in
