### ISSUE TITLE
Stray light fixture in NorthStar Kitchen

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#75137]
Reporting client version: 514.1589

## Round ID:
[204974](https://scrubby.melonmesa.com/round/204974)

## Testmerges:
- [New Medical job: The Coroner](https://www.github.com/tgstation/tgstation/pull/75065)

## Reproduction:
![Screenshot 2023-05-02 174605](https://user-images.githubusercontent.com/85206687/235816140-6a7ca0bc-b0d3-47ac-bad8-85db0dc60eb3.png)

**Comment by norsvenska** [comment]
Fixed in #75099

**Comment by Sealed101** [comment]
^
