### ISSUE TITLE
Clicking yourself with the dragon final objective scanner doesnt turn you into a dragon.

### ISSUE THREAD

**Issue by Xander3359** [tgstation/tgstation#75147]
## Reproduction:
A traitor with the final objective "become a space dragon" cannot click themselves to turn into a dragon.
Normal reproduction steps:
- Get objective
- Get the scanner kit
- Scan a fish
- Click on yourself

You will get a error that says "No Database", this is because /obj/item/dna_probe/carp_scanner is running the parent of afterattack which means it's trying to do the DNA vault stuff. This is super confusing to a traitor who may be in a tense situation or pressed for time.
The only way for you to actually turn into a dragon is with attack_self (use in hand), but I think clicking yourself should also work to avoid this kind of panic/confusion.
![image](https://user-images.githubusercontent.com/66163761/235939594-6cbb402d-013e-4514-b169-a18999cfe3c8.png)

**Comment by JohnFulpWillard** [comment]
From the very start it's only attack hand. Attacking yourself with it is you trying to collect your own DNA.
