### ISSUE TITLE
Flora and tendrils spawn on lava.

### ISSUE THREAD

**Issue by Helg2** [tgstation/tgstation#75154]
## Reproduction:
1. Press Observe in lobby.
2. Spectate bunch of flora spawning and burning on the lava. Also tendrils aren't accessable for miners which just leaves them useless.
![image](https://user-images.githubusercontent.com/93882977/236025557-ede5d370-5b54-4ce1-8f76-b0e8791c4230.png)
![image](https://user-images.githubusercontent.com/93882977/236025577-3fd0f266-0e0e-4f2e-befc-d0d42a4342c5.png)
![image](https://user-images.githubusercontent.com/93882977/236025595-d11304d8-84cd-4277-a8c1-9987fdd8b720.png)

**Comment by newfren** [comment]
portals can also spawn above plasma rivers on icebox

they can be reached, if the miner gets an rcd or the lava staff from killing a drake, but they are certainly much more tedious than intended to destroy
