### ISSUE TITLE
Morgue optables are varedited on every map

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#75181]
These should be a subtype of optable, not varedited.

![image](https://user-images.githubusercontent.com/66640614/236543864-066516a4-dcc0-4998-98c9-4e35a63da019.png)

**Comment by Sealed101** [comment]
Coroner updates removed these varedits and therefore this is no longer applicable
___
![изображение](https://github.com/tgstation/tgstation/assets/75863639/372668a9-98e1-41a3-8d14-b043d0152e11)
