### ISSUE TITLE
Security gas masks do not filter air toxins even if the filter is fine.

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#75218]
Reporting client version: 514.1589

## Round ID:
[205222](https://scrubby.melonmesa.com/round/205222)

## Testmerges:
N/A

## Reproduction:
Security gas masks do not seem to be working as a gasmask, in filtering toxins from the air. Even with a gasmask filter, which enables the gasmask to filter toxins from the air, it does not seem to be working.
1. Get a room full of an air contaminate such as plasma or N2O.
2. Put on your trusty security gasmask.
3. Go into the room.
4. Cough up on plasma or fall unconscious from N2O.
Side note: The filter inserted into the security gasmask does not seem to have its integrity degrade at all while worn, though the filter isn't managing filter anything, anyways.

**Comment by timothymtorres** [comment]
The gas mask does not filter 100% of bad air.

https://github.com/tgstation/tgstation/blob/fb22d5385b6be538607d02b15f0cbd6938334bde/code/modules/clothing/masks/gas_filter.dm

**Comment by Derpguy3** [comment]
I was playing around in a recent round with a SWAT mask, and it seems they also do not filter gases, even if they have a filter cloth in them.

I think there is an issue with the type of gasmasks which have a "HALT" sound to them in general.
