### ISSUE TITLE
Cargo Requesition form gets printed wrongly

### ISSUE THREAD

**Issue by Googles-Hands** [tgstation/tgstation#75231]
## Reproduction:

Cargo requesition forms get printed and includes all the items in the approved shopping basket when the supply shuttle is called. This is the intended behaviour.
The problem is that the paper also gets printed when the shuttle is sent from the station to centcom, so if you order something while the shuttle is docked at the station you end up with the form twice, once for when it gets sent TO centcom and the proper form when the shuttle with the actual supplies is shipped FROM centcom.
The papers should only be printed when you actually approve the orders and they get shipped to the station. I assume the problem is that it's the same button that sends the shuttle back and forth and the printing function is linked to it no matter the travel destination.

Probably an oversight from @SyncIt21 in #72423.

**Comment by Peliex** [comment]
This does appear to be the case, the code for printing the shopping list should be moved into the function for sending the shuttle to the station from CentCom.

**Comment by Sealed101** [comment]
#75768
