### ISSUE TITLE
coroner is in the latejoin menu twice

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#75261]
Reporting client version: 514.1589

## Round ID:
[205304](https://scrubby.melonmesa.com/round/205304)

## Testmerges:
- [JSON Logging Take Two](https://www.github.com/tgstation/tgstation/pull/73604)
- [Adds TTS to the game. Players can select their own voices in preferences.](https://www.github.com/tgstation/tgstation/pull/74775)

## Reproduction:
![image](https://user-images.githubusercontent.com/12635164/236819242-9fbd9ffc-ca5c-4b55-ad93-3960fa765368.png)
this is inconsistent with lawyer and psychologist, other service jobs with a nominal to another department.

**Comment by newfren** [comment]
it also gives the late join menu a scrollbar

**Comment by BlueMemesauce** [comment]
Not a bug according to johnfulpwillard who created the coroner
