### ISSUE TITLE
SEC-hud wanted status error

### ISSUE THREAD

**Issue by Eldeen** [tgstation/tgstation#75296]
Reporting client version: 514.1588

## Round ID:
[205343](https://scrubby.melonmesa.com/round/205343)

## Testmerges:
- [JSON Logging Take Two](https://www.github.com/tgstation/tgstation/pull/73604)
- [Adds TTS to the game. Players can select their own voices in preferences.](https://www.github.com/tgstation/tgstation/pull/74775)

## Reproduction:

After the ninja did a terminal hack and set everyone to arrest, I went over to a security terminal and went about setting everyone back to having no status. When I finished, a handful of people, including myself, still had the wanted symbol on their ingame characters. This wasn't just on my end, other officers were reporting seeing people running around with wanted signs on them. 

I tried resetting the status by changing myself to various states, I also set myself a fake crime, labeled "test" in the screenshot, and that didn't change the status either when I took it off. An admin spawned a security bot in the room to test if it was visual or not, the security bot didn't respond to my status so it was purely visual. 

When I was taking people off arrest en mass, I was trying to do it as quickly as possible so I wonder if some flag wasn't set correctly due to time dilation and so many commands going through the console at once.

![screenie](https://user-images.githubusercontent.com/60030520/236986860-fdff6c76-11c8-400b-b3bc-88a43d3411e7.png)

**Comment by Sealed101** [comment]
#75320
