### ISSUE TITLE
secret recipes can contain unobtainable reagents

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#75304]
Reporting client version: 514.1589

## Round ID:
[205371](https://scrubby.melonmesa.com/round/205371)

## Testmerges:
- [JSON Logging Take Two](https://www.github.com/tgstation/tgstation/pull/73604)
- [Adds TTS to the game. Players can select their own voices in preferences.](https://www.github.com/tgstation/tgstation/pull/74775)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/12635164/d6cddb56-fe07-4051-873f-97e9fd5e60b5)
both inaprovaline and stranger reagent are not obtainable outside admin spawn

**Comment by Jackal-boop** [comment]
both are obtainable from strange seed RNG

**Comment by Likteer** [comment]
@Jackal-boop  Doesn't matter cause reagents only obtainable via strange seeds RNG are considered unintentional and have already been blacklisted in the past.
https://github.com/tgstation/tgstation/pull/62611

**Comment by newfren** [comment]
if stranger reagent is obtainable from seed rng it probably shouldn't be, isn't it just strange reagent used for tests?
