### ISSUE TITLE
Fulton Pack doesn't automatically go into Syndicate MOD Control Unit even if there is space

### ISSUE THREAD

**Issue by o-d-a-z** [tgstation/tgstation#75327]
Reporting client version: 514.1589

## Round ID:
[205409](https://scrubby.melonmesa.com/round/205409)

## Testmerges:
- [JSON Logging Take Two](https://www.github.com/tgstation/tgstation/pull/73604)

**Comment by Helg2** [comment]
Works this way with every mod, not just syndicate one

**Comment by Jacquerel** [comment]
Currently it is explicitly checking for `/obj/item/storage/backpack` rather than any storage-capable object in the back slot.
