### ISSUE TITLE
Wallet don't seem to combine ID accesses

### ISSUE THREAD

**Issue by rasepretep** [tgstation/tgstation#75351]
## Round ID:
Any recent round in the past few days

Put Assistant and Miner ID in wallet. While Assistant is in first place, Miner access doesn't work, and vice versa.

**Comment by SyncIt21** [comment]
This is not a bug and has been the default behaviour since forever, It's too expensive to sort through every ID in your wallet and check it's access against the door, There is simply no reason/nor gain to do this,

**Comment by SyncIt21** [comment]
Wow, thanks for showing the code, i think ibroke this in closet/crate PR. I know how to fix it

**Comment by rasepretep** [comment]
> I remember someone saying that it was designed so that you could hide a 2nd ID behind the 1st one. So you could appear as your job/name but have captain's level access secretly.

Whether bug or intended, that doesn't actually happen, though. You can hide a second similar-level ID behind the first one like you said, but if your wallet has an ID of a higher access, it will always take up the first slot.

I forget which ID I've had this happen with, let's say for example Station Engineer. I'd have Assistant, Shaft Miner and Station Engineer and the last one would always show up in main wallet slot.

Similarly, when you put in a nonstandard ID card, like the agent ID you can get from uplink, it will -always- occupy the main slot. Agent IDs have a "wallet spoofing" option, which lets you enable or disable whether the ID automatically forces itself into the main slot, but the trouble with that is that it doesn't work. Even if you disable it, agent ID will always be in the main slot, the only way to get around it is to rename it to your name and job.
