### ISSUE TITLE
Hardcore random score does not increment

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#75368]
## Reproduction:

This is the second time in a row this happened: I have a score of 5045 and beat a round with a hardcore random score of 71. To my surprise, my score did not get incremented. I checked other servers and a day later (which is now), to see that it still has not incremented. 

I'm not sure if others are experiencing this or if this only occurs randomly, since testing this is a bit iffy. 

(Below is the round right after I got a score of 71, but did not increment my point total)

![image](https://github.com/tgstation/tgstation/assets/7501474/98190c25-b188-431c-b1d9-6f7e1352fb4f)

**Comment by newfren** [comment]
double checking, you were there roundstart?

**Comment by Time-Green** [comment]
> double checking, you were there roundstart?

Yes, if you dont you don’t get reported in the round end report

**Comment by Time-Green** [comment]
Again. Might be broken completely:

![image](https://github.com/tgstation/tgstation/assets/7501474/e7d29916-a7fc-4f37-b862-8b7ca3e34c61)

Round after:
![image](https://github.com/tgstation/tgstation/assets/7501474/4b497474-b32b-44e6-9473-b73f6e984581)
