### ISSUE TITLE
TTS doesn't work correctly with social anxiety. (Or sign language)

### ISSUE THREAD

**Issue by dopamiin0** [tgstation/tgstation#75363]
## Testmerges:
#74775 

## Reproduction:
When speaking with social anxiety and having your message changed, TTS will play your original message, instead of the new one.

Also, signing still says your message out loud with TTS.

**Comment by Dorsisdwarf** [comment]
This seems to be a general issue with all speech modifications.

**Comment by Mothblocks** [comment]
TTS is now merged
