### ISSUE TITLE
Grass tiles no longer have a broken sprite (from burn dmg or explosions)

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#75372]
![obraz](https://github.com/tgstation/tgstation/assets/68878861/020e43c4-9b42-41b8-85e0-c956bd69c6d5)
(broken grass tiles are supposed to look like sand or dirt turf - this was also the only way for players to achieve this look)
## Round ID:
[205485](https://scrubby.melonmesa.com/round/205485)

## Testmerges:
none

## Reproduction:
Damage a grass astroturf (easily done with a flamethrower).
The sprite does not change. You can now remove it via a crowbar instead of a shovel and it does not yield the tile.

**Comment by Sealed101** [comment]
relevant code:
https://github.com/tgstation/tgstation/blob/a4c1f6298e821a6449108e19c2d31c323a7e79cd/code/game/turfs/open/floor/fancy_floor.dm#L133-L147

https://github.com/tgstation/tgstation/blob/a4c1f6298e821a6449108e19c2d31c323a7e79cd/code/game/turfs/open/floor.dm#L138-L147

it's trying to return `sand` value when it's setting up the damaged state. however, the `damaged_dmi` value is defaulted to `damaged.dmi`, which does not have a `sand` sprite. changing grass floor's `damaged_dmi` to `'icons/turf/sand.dmi'` should work

**Comment by ShizCalev** [comment]
Time for a new unit test!

**Comment by ShizCalev** [comment]
> relevant code:
> 
> https://github.com/tgstation/tgstation/blob/a4c1f6298e821a6449108e19c2d31c323a7e79cd/code/game/turfs/open/floor/fancy_floor.dm#L133-L147
> 
> https://github.com/tgstation/tgstation/blob/a4c1f6298e821a6449108e19c2d31c323a7e79cd/code/game/turfs/open/floor.dm#L138-L147
> 
> it's trying to return `sand` value when it's setting up the damaged state. however, the `damaged_dmi` value is defaulted to `damaged.dmi`, which does not have a `sand` sprite. changing grass floor's `damaged_dmi` to `'icons/turf/sand.dmi'` should work

..........


yeah literally none of that is implemented for grass lol
#65504

**Comment by ShizCalev** [comment]
> it's trying to return `sand` value when it's setting up the damaged state. however, the `damaged_dmi` value is defaulted to `damaged.dmi`, which does not have a `sand` sprite. changing grass floor's `damaged_dmi` to `'icons/turf/sand.dmi'` should work

..........


yeah, looking at it, literally none of that is implemented for grass cause @LemonInTheDark just blanket renamed a fuckton of paths without actually checking their code lol #65504
