### ISSUE TITLE
Spiders can't attack while they have any ability cooldown on the countdown

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#75380]
## Round ID:

Why Is this a thing? no idea
Don't even know where the bar of code that does this is I can't find it someone please help

**Comment by moocowswag** [comment]
i cant do it rn but like run it in debug mode and have it stop at the point when you use the ability then look at and see where the engine proceeds to if it reaches anything that looks like it might disable attacking

it might also be the  code that stops spiders from attacking when laying eggs/making webs which means it probably activates before the ability procs so my suggestion probably wont be useful

**Comment by Jacquerel** [comment]
This isn't a bug, you have configured the ability wrong.
Set `melee_cooldown_time` to 0 in the action.
