### ISSUE TITLE
Remembering the christmas party always leads to losing your drone in "strange tree" encounter

### ISSUE THREAD

**Issue by terracat474** [tgstation/tgstation#75427]
## Reproduction:
Step 1: encounter the strange tree in exploration drone
Step 2: choose everything until "remember the christmas party" and choose that
Step 3: choose "snap a photo"
Step 4: choose "take a moment to calm down"
Step 5: see issue - nothing is happening

**Comment by terracat474** [comment]
https://github.com/tgstation/tgstation/assets/94134200/140982a0-b2c2-4c9c-8e36-ca2d2dd79913

**Comment by BlueMemesauce** [comment]
In the tester it works as intended https://anturk.github.io/adventure-maker/

Maybe caused by the adventure system not handling random negative numbers properly within byond? otherwise idk

![image](https://github.com/tgstation/tgstation/assets/47338680/f97d7175-393e-42fb-8d51-bd317312b2a6)

**Comment by BlueMemesauce** [comment]
Looks like I found the issue. Did you "Snap a photo" of the tree? This sends you to the epilogue page which adds 9999 confusion for some reason?
This makes it appear as the button is doing nothing, as you're only reducing the value of 9999 by -3 to -5 each time, and it needs to be less than 30 for you to leave.
![image](https://github.com/tgstation/tgstation/assets/47338680/a11bba5f-5d32-4be9-839b-803350cc5cfb)
