### ISSUE TITLE
Chemical Grinders are one way and can be walked through one side, but not any other way.

### ISSUE THREAD

**Issue by epicgamer545** [tgstation/tgstation#75429]
## Reproduction:
1. Get a chemical grinder.
2. Try walking through it where the pipe is.
3. Realize that you can enter through the grinder.
4. Walk out and try to walk in any other way.
5. Turns out that there's only one way you can walk in.

Unsure if this is intentional, but feels abusive. 

Below is an image walking into the machine on the side it can be phased through with.
![6448b22a32597974493d22f18423d248](https://github.com/tgstation/tgstation/assets/106710384/ec96ee23-0fe7-421d-8cd1-1fabd9cec8d3)

**Comment by DoomAngelBlade** [comment]
D;

**Comment by SyncIt21** [comment]
:D

**Comment by the-orange-cow** [comment]
Must be intentional, its the only way I can escape my own setups.
