### ISSUE TITLE
xeno corpses being weird

### ISSUE THREAD

**Issue by NalyKalZul** [tgstation/tgstation#75443]
this was from a terry round 205681

so i was playing a shift as the ghost crew for tiny delta ruins.
and i am still getting used to the whole tgui overhaul here for controls, but i for the love of god not figure out how to grab/agro grab them. i just was trying to do both surgery and clean them up in a gibber so we had a decent meat supply. that i could work down into a non xeno meat variant. but the other ghost crew also only could pull drag them or shove them to.
i was told to make a ticket about it since it is indeed them being funny.

not sure if this was also related to a other funny thing that happened that round, weird speed glitch that came out of nowhere.

**Comment by Sealed101** [comment]
the charlie station xenos are a simplemob and are thus not able to be aggrograbbed or put through the gibber. you can put em in a meatspike or just butcher directly though
