### ISSUE TITLE
projectiles do not go through hand tele portals

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#75447]
they just hit the portals instead

![image](https://github.com/tgstation/tgstation/assets/42606352/d944c1e3-7202-4eb3-ba18-168f1fa39f30)

we also tried this with an L6 saw, both clicking on and past the portals

this is immensely disappointing and contradicts some of our art

very sad

**Comment by VladinXXV** [comment]
See my comment https://github.com/tgstation/tgstation/pull/74606#issuecomment-1501194244. It's been a bit, but I believe I tried Portal guns, hand teleporter portals, and the actual teleporter machine. None allow projectiles through, and none preserve momentum of thrown objects.
