### ISSUE TITLE
arrow envenoming just doesn't work

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#75448]
like, at all

examining the arrow doesn't even give the message that's supposed to indicate that it can be envenomed ("You can dip it in a chemical to deliver a poisonous kick.")

an arrow that we gave the envenomable_casing component to directly gave the examine message, but couldn't be dipped

a foam dart that we gave the envenomable_casing component to could be dipped, but didn't deliver its payload upon hitting its target (unless it bypasses expose_mob?)

**Comment by mc-oofert** [comment]
> like, at all
> 
> examining the arrow doesn't even give the message that's supposed to indicate that it can be envenomed ("You can dip it in a chemical to deliver a poisonous kick.")

it directly requires an open container and it to be an actual reagent container

**Comment by mc-oofert** [comment]
> like, at all
> 
> examining the arrow doesn't even give the message that's supposed to indicate that it can be envenomed ("You can dip it in a chemical to deliver a poisonous kick.")

arrows arent casings
