### ISSUE TITLE
Guns with BOLT_TYPE_LOCKING (pistols and bolt-actions) magically lock open when trying to fire while empty

### ISSUE THREAD

**Issue by Hatterhat** [tgstation/tgstation#75452]
## Round ID:
n/a tested on local

## Testmerges:
n/a tested on local
## Reproduction:
- get an empty pistol or bolt-action rifle
- empty the gun with the bolt/slide down/dropped
- attempt to fire it
- watch as the bolt/slide magically comes open, despite it not supposed to do that

The issue here, I think, is in these parts of guncode -
https://github.com/tgstation/tgstation/blob/553d03748e270ae0a0ab768fd4793ab36ddefc18/code/modules/projectiles/guns/ballistic.dm#L451-L464
https://github.com/tgstation/tgstation/blob/553d03748e270ae0a0ab768fd4793ab36ddefc18/code/modules/projectiles/gun.dm#L222-L224

The post-fire checks to lock the bolt back check for if the last shot was successful. If the gun doesn't fire a bullet, it doesn't return anything, and therefore it was a failed shot.

*However*, the attached `AFTERATTACK_PROCESSED_ITEM` adds 2 to the return value no matter what, so the postfire empty checks always assumes that the last shot succeeded because it gets a non-zero return value, so the bolt locks backwards because it *assumes* that it shot successfully, went empty, and therefore locks open.

The only way I can think of resolving this is just by removing the `AFTERATTACK_PROCESSED_ITEM`, but that would probably break something else.

This might also have some similar "oh, it returned something non-zero, we should do something else" issues in regards to other afterattack calls that have `AFTERATTACK_PROCESSED_ITEM` attached to them.

**Comment by YakumoChen** [comment]
> the slide lock isn't supposed to open if the gun is empty

Isn't that just a visual indicator that there's no bullets left? 

I can't tell if this is a legitimate game issue or just a gun autism rant

**Comment by Hatterhat** [comment]
> > the slide lock isn't supposed to open if the gun is empty
> 
> Isn't that just a visual indicator that there's no bullets left?
> 
> I can't tell if this is a legitimate game issue or just a gun autism rant

very slight A, mostly B and it's because the AFTERATTACK_PROCESSED_ITEM bit had some unintended repercussions

with this bug if you try to shoot a mosin it magically opens itself which messes with my muscle memory so i end up closing it and having to reopen it before i can put more bullets in

the same issue kinda exists with pistols but much less
