### ISSUE TITLE
new golem cant use dna syringes

### ISSUE THREAD

**Issue by NalyKalZul** [tgstation/tgstation#75466]
Round ID:  [205734](https://scrubby.melonmesa.com/round/205734)
on Terry as ghost role of free golems

so we were playing with the recent rework of the golems, we do have genetics.
but it seems the golems native thick space proof skin, stops the possible genetic injects from working.

perhaps a future fix with golem racial genetics to bypass this, either dna syringes that bypass golem skin
or them being able to drop the thick skin as a genetic trait. but you lose a few baser golem traits as a result.
with the genetic path being one way trip to remove if possible, you are a slim jim silicon now!

**Comment by Mothblocks** [comment]
Please make your title an understandable description of the issue, it makes it harder to look through issues when it is not

**Comment by Jacquerel** [comment]
Golems have `NO_DNA_COPY`, `NOTRANSSTING`, and `TRAIT_PIERCEIMMUNE` which would block any way of injecting genes.
They _also_ have `TRAIT_GENELESS` so if the DNA machine works on them anyway I have no idea what that trait is supposed to be doing, but that's the actual bug.
While not the answer you want, the fix here is certainly "make them not able to use the DNA machine" rather than "allow them to use DNA syringes".

**Comment by Namwty** [comment]
Doesn't help that golems take cellular damage from slimes or let's say greed gambling den... when they apparently are not meant to have genetics or anything like that ( like skeletons ).

**Comment by Sealed101** [comment]
golems are not supposed to have dna or get mutations, they are ronks
also the cellular damage is a general damage thing that applies to all humanoids, making golems immune to that damage is not the solution (i.e. greed ruin). you can stretch it to be molecular damage or something

**Comment by Jacquerel** [comment]
Can you let me know _how_ you were doing genetics on a golem? Simply putting one into a DNA scanner doesn't appear to work (as expected).

**Comment by Sealed101** [comment]
i'm almost certain golems always were not eligible for genetics and should be unable to modify their non-existent rock dna
