### ISSUE TITLE
Hack communication console objective fails for no reason

### ISSUE THREAD

**Issue by plutori** [tgstation/tgstation#75479]
Reporting client version: 514.1589

## Round ID:
[205777](https://scrubby.melonmesa.com/round/205777)

## Testmerges:
- [JSON Logging Take Two](https://www.github.com/tgstation/tgstation/pull/73604)
- [Spider Infestation Balance Rebalance Expansion Part 1](https://www.github.com/tgstation/tgstation/pull/75204)

## Reproduction:

1. select the golden "Hack the communication console" traitor objective
2. Hack the communication console
3. Be very depressed when it turns red and says you failed for no apparent reason.

Happened both in this shift for me and the previous Sybil shift, I got traitor twice in a row, objective failed with me being the only one to hack the console both times.

**Comment by TheVekter** [comment]
Can you guys confirm this is still happening? I haven't seen this in a while.

**Comment by plutori** [comment]
> Can you guys confirm this is still happening? I haven't seen this in a while.

I haven't seen it in a while either. Cannot at this time confirm it is still occurring.

**Comment by plutori** [comment]
> Can you guys confirm this is still happening? I haven't seen this in a while.

Hey so, this happened to me again in Sybil shift 209620.

**Comment by Gboster-0** [comment]
happening on forks of TG aswell
