### ISSUE TITLE
I'm having extreme lag after being gone for about a week from SS13

### ISSUE THREAD

**Issue by Cutplays** [tgstation/tgstation#75483]
no idea what is happing but I've check my internet and its stable and its not my computer so I don't know what to do I was really just hoping for some advice
![Screenshot 2023-05-16 181857](https://github.com/tgstation/tgstation/assets/119466350/8d1270bb-a88c-4164-9525-3f4ef704abe2)

**Comment by YakumoChen** [comment]
Follow the format

**Comment by SyncIt21** [comment]
Literarily provides no information & unable to reproduce. Just because it was a one time thing & was unique only to you doesn't make it our problem.
Maintainer's feel free to close
