### ISSUE TITLE
Weird TGUI say placement for pAI holoforms being worn by a person

### ISSUE THREAD

**Issue by YehnBeep** [tgstation/tgstation#75482]
## Reproduction:
1. As a pAI, activate holoform
2. Have someone pick you up and wear you on their head
3. Press 't' to open TGUI say (and note the placement is more towards the upper left corner than centered)

![image](https://github.com/tgstation/tgstation/assets/86855173/a0d2d418-292c-4d7c-9e18-c12cb87bb31f)

**Comment by jlsnow301** [comment]
I tried to test this locally and it came up in the default location. Note that moving the tgui say window to any position will cause it to reopen at that position.

If you can, please confirm this is still happening to you.

![Screenshot 2023-05-22 120217](https://github.com/tgstation/tgstation/assets/42397676/7cda2d62-bcc7-4e53-8512-424ea868171a)

**Comment by YehnBeep** [comment]
I didn't realize the window could be moved. Seems likely, then, it was accidentally dragged (maybe while alt tabbing or a cat on keyboard/mouse issue?). Sorry about that.
