### ISSUE TITLE
need to pause before typing after hitting t to bring up the dialogue box

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#75497]
Reporting client version: 514.1589

## Round ID:
[205834](https://scrubby.melonmesa.com/round/205834)

## Testmerges:
- [Experimental Mineral Balance PR.](https://www.github.com/tgstation/tgstation/pull/75437)
- [Fix runtime with chat messages deleting when their clients do](https://www.github.com/tgstation/tgstation/pull/75445)
- [Adds TTS to the game. Players can select their own voices in preferences.](https://www.github.com/tgstation/tgstation/pull/74775)
- [Use rust-g compiled with panic hooks](https://www.github.com/tgstation/tgstation/pull/75426)

## Reproduction:
hit t and continue typing to say things
the first letter is eaten by lag
this is the most frustrating experience in the world

**Comment by SinfulBliss** [comment]
Happens for me too now, not sure what changed it but it's very irritating and makes talking much harder.

**Comment by SinfulBliss** [comment]
Also I don't think it's a matter of lag since this occurred on a 33pop shift with 0% time dilation
