### ISSUE TITLE
Request console "send message" doesn't remove whitespace

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#75494]
## Reproduction:

Have RC

Send message to department:

![image](https://github.com/tgstation/tgstation/assets/51863163/adb1576b-56c7-4699-bf35-479fd9457127)

This has no discernible limit

![image](https://github.com/tgstation/tgstation/assets/51863163/da933d36-fbaa-41ad-bc72-5641c7c2dafa)

**Comment by Profakos** [comment]
While trim and html_encode were indeed missing from send_message and send_announcement (but not from quick_reply as tgui_input_text automatically uses those), it seems like that not stripping long batches of whitespace _within_ text is not just an issue in requests consoles.

![image](https://github.com/tgstation/tgstation/assets/2676196/0635081f-a1bf-448b-81b3-3da84bafc9a2)
![image](https://github.com/tgstation/tgstation/assets/2676196/3d2f748a-a735-46ae-b51d-249c4d22f70d)

I am making a PR that fixes the backend side trim and html_encode missing for now. Is there a proc that already exists, that removes excess whitespace from inputs? I am willing to hunt down all instances of this issue.

**Comment by MrMelbert** [comment]
@jlsnow301 Know anything about this? I assume it is an issue with TextArea

**Comment by jlsnow301** [comment]
> @jlsnow301 Know anything about this? I assume it is an issue with TextArea 

There is a max length prop on text area, which would fix at least one issue, but if you won't want white space at all it would presumably need done elsewhere

**Comment by Profakos** [comment]
I am using maxLength in requests console, which is 1052, which is arguably pretty huge, but that was the default text length the previously used tgui_input_text was using.

**Comment by lessthnthree** [comment]
https://github.com/tgstation/tgstation/pull/75503

**Comment by Profakos** [comment]
That pr only fixed missing trim at the start and end of the messages, did not fix large whitespace in the middle. Then again, that is a general issue still, affecting multiple things.

**Comment by lessthnthree** [comment]
> That pr only fixed missing trim at the start and end of the messages, did not fix large whitespace in the middle. Then again, that is a general issue still, affecting multiple things.

Thanks, I'm consolidating some of the text issues and will find a spot for it.
