### ISSUE TITLE
you can hear tts while unconsious 

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#75498]
Reporting client version: 514.1589

## Round ID:
[205834](https://scrubby.melonmesa.com/round/205834)

## Testmerges:
- [Experimental Mineral Balance PR.](https://www.github.com/tgstation/tgstation/pull/75437)
- [Fix runtime with chat messages deleting when their clients do](https://www.github.com/tgstation/tgstation/pull/75445)
- [Adds TTS to the game. Players can select their own voices in preferences.](https://www.github.com/tgstation/tgstation/pull/74775)
- [Use rust-g compiled with panic hooks](https://www.github.com/tgstation/tgstation/pull/75426)

## Reproduction:
get killed
be brought back to life in crit
pulled out of crit but not awake
hear people talk around you

**Comment by the-og-gear** [comment]
Also happens when unconscious by other means, such as narcolepsy.
