### ISSUE TITLE
birdshot missing fire alarms

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#75510]
A significant portion of the main hallways don't have any fire alarms so firelocks can't be opened if you have no crowbar.
Hall right above medbay:
https://i.imgur.com/DyQ7Tdc.png

Hall to the left of dorms (circled is a fire alarm but it's on the other side of the firelocks):
https://i.imgur.com/3Ms6XiW.png

These are the only two I noticed but it's probably worth checking elsewhere.

**Comment by YakumoChen** [comment]
Given its birdshot this might not be a bug
