### ISSUE TITLE
The CIA Hairstyle seems to be missing two patches of hair pixels

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#75513]
Reporting client version: 514.1589

## Round ID:
[206352](https://scrubby.melonmesa.com/round/206352)

## Testmerges:
- [JSON Logging Take Two](https://www.github.com/tgstation/tgstation/pull/73604)
- [Spider Infestation Balance Rebalance Expansion Part 1](https://www.github.com/tgstation/tgstation/pull/75204)

## Reproduction:
![Screenshot 2023-05-17 203358](https://github.com/tgstation/tgstation/assets/85206687/5a54cc6f-e034-45c4-bfe1-384b9bb6d14e)
(Oh god my character is starting to bald)

**Comment by Helg2** [comment]
Apparently it's not missing 2 pixels, but redundant 2 grey pixels under hair sprite. No idea why they are even on head.

**Comment by Derpguy3** [comment]
On a hunch, I decided to test the CIA hairstyle alongside the security gear I was wearing at the time.
As it turns out, the two grey pixels which you pointed out seem to be as a result of the security bowman headset my character was wearing.
![Screenshot 2023-05-27 201345](https://github.com/tgstation/tgstation/assets/85206687/e115c936-3c6f-40c4-a848-8ed44722442c)
![Screenshot 2023-06-02 153931](https://github.com/tgstation/tgstation/assets/85206687/b613ac9f-23d9-4149-a85a-fafb8f10df09)
![Screenshot 2023-06-02 153942](https://github.com/tgstation/tgstation/assets/85206687/cebf010c-c142-412f-91e4-4f00f2d48ab7)
