### ISSUE TITLE
Rolling pin in crafting recipes has wrong icon.

### ISSUE THREAD

**Issue by Helg2** [tgstation/tgstation#75525]
![image](https://github.com/tgstation/tgstation/assets/93882977/2b577563-afb2-44b2-a2c1-ec4133c97f0e)

**Comment by SyncIt21** [comment]
Unable to reproduce on latest commit
![Screenshot (218)](https://github.com/tgstation/tgstation/assets/110812394/93688b55-57be-4bcc-8d47-d02a0953e569)

**Comment by Treachce** [comment]
> Unable to reproduce on latest commit 

![rollingpin](https://github.com/tgstation/tgstation/assets/69348667/06ad698c-ca31-44a6-91c9-f4b80817d2af)
The recipe to craft the rolling pin itself has the right icon, but any food recipe has it use the wirebrush icon instead. The rolling pin has the correct icon assigned but it is right above the wirebrush in the tool crafting icon list which makes me wonder if that is somehow causing this fuckup, wrong list indices and whatnot. Probably worth checking if this happens to any other tools.
```
/datum/asset/spritesheet/crafting/proc/add_tool_icons()
	var/list/tool_icons = list(
		...
		TOOL_ROLLINGPIN = icon('icons/obj/kitchen.dmi', "rolling_pin"),
		TOOL_RUSTSCRAPER = icon('icons/obj/tools.dmi', "wirebrush"),
	)
```

**Comment by Treachce** [comment]
![image](https://github.com/tgstation/tgstation/assets/69348667/94e68ccc-f622-4688-9c1b-ebb8e450e7b4)
This doesn't look like a basketball hoop.
