### ISSUE TITLE
Tram botany, constant elevator music

### ISSUE THREAD

**Issue by the-orange-cow** [tgstation/tgstation#75531]
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [206425](https://scrubby.melonmesa.com/round/206425)
BYOND Version: 515.1607
Server revision compiled on: 
Master commit: [c6b291b0f0bf3f7236bc1c901491d04a63730747](https://www.github.com/tgstation/tgstation/commit/c6b291b0f0bf3f7236bc1c901491d04a63730747)
The following pull requests are currently test merged:
[#73604: 'JSON Logging Take Two' by ZephyrTFA at commit d9c19d9f0e](https://www.github.com/tgstation/tgstation/pull/73604)
[#75204: 'Spider Infestation Balance Rebalance Expansion Part 1' by SethLafuente at commit 0788c110dd](https://www.github.com/tgstation/tgstation/pull/75204)

Local commit: 452dede77b4d77084044d16c57a01488c2f23460
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

The elevator music pull(https://github.com/tgstation/tgstation/pull/75388) has made tram botany extremely annoying, it plays nonstop due to there being an elevator panel that connects tram botany to the kitchen.

**Comment by JusticeGoat** [comment]
Same when observing in medbay, some reason the sound is not constrained to just the elevator area.

**Comment by Jacquerel** [comment]
Does this still occur? I believe that elevator should no longer play music.
