### ISSUE TITLE
a sheet of iron is 100 units without anything else being scaled

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#75554]
Reporting client version: 514.1589

## Round ID:
[206526](https://scrubby.melonmesa.com/round/206526)

## Testmerges:
- [Should* make tgui say faster](https://www.github.com/tgstation/tgstation/pull/75534)
- [Experimental Mineral Balance PR.](https://www.github.com/tgstation/tgstation/pull/75437)
- [Fix runtime with chat messages deleting when their clients do](https://www.github.com/tgstation/tgstation/pull/75445)
- [Use rust-g compiled with panic hooks](https://www.github.com/tgstation/tgstation/pull/75426)

## Reproduction:
get a stack of metal
stick it in the lathe
"you inserted a total of 5000 into the lathe"
![image](https://github.com/tgstation/tgstation/assets/12635164/36dad769-6b59-4921-a6bc-441d28e77a19)
x large beakers cost 25 sheets of glass per

**Comment by newfren** [comment]
rods are still the regular amount, but floor tiles scale with this 100per sheet

**Comment by SyncIt21** [comment]
It should be safe to close this? @Sealed101

**Comment by Sealed101** [comment]
test merge bug label moment
