### ISSUE TITLE
Option to dump ore from the Clarke's ore bin is missing

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#75568]
There used to be a button for it in the UI but it wasn't copied back over when the UI was upgraded.

**Comment by necromanceranne** [comment]
It still exists...kind of. It's just extremely poorly conveyed that it is the way to do it.

So there is an option in the ore bin on the ui that is either toggle or activate. Hitting that will release the contents. Obviously, you're not toggling anything, you're just using the equipment. But that's how you activate it.

This obviously could stand to be more clear.
