### ISSUE TITLE
The void causes you to return to lobby (aka ghetto respawning)

### ISSUE THREAD

**Issue by InsaneTGplayer** [tgstation/tgstation#75569]
## Reproduction: become ai, get put into intellicard, get a borg shell, throw intellicard into sm as borg shell, somehow live, return to core, embrace void for long enough (while being able to switch between void and reality also being able to talk in binary), get disconnected, return to find yourself in lobby

I think the issue is self explanatory. Not only you are able to not exist at will, you also get sent back to lobby (get respawned) after some time passes while you are in void.

Oh boy I feel coders are gonna be amused

**Comment by Ghommie** [comment]
The disconnection and following return to the lobby are most likely the result of the player control over a mob being relinquished but not assigned to another mob. Basically, the PC mob key or ckey var has been set from "john_doe" to null without the opposite having happened on any other mob during the same tick. This boots you, and when you come back, having no mob in control, you're given control of a default mob instance, which is the "new player" mob.

**Comment by InsaneTGplayer** [comment]
Also I learned that if you are not in the void when the 'booting' happens, the core vanishes, locking you in your borg shell. And after round ends, your ai shell is said to be a 'AI-less borg' which is not true as you still have the remote icon and description (aka this appears to be active ai shell). And not only that, if your shell gets reset then disassembled in this state, no brain\boris board spawns effectively killing you off for good

**Comment by InsaneTGplayer** [comment]
thing is.... it still works. yup.

**Comment by InsaneTGplayer** [comment]
only with mod ais, tho. which is why im reopening this issue

**Comment by Sealed101** [comment]
@InsaneTGplayer does it still work, modsuit or aicard or however else? can you open another issue for it, if it does?
