### ISSUE TITLE
Birdshot prison tram has controls under window

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#75587]
## Reproduction:
1. go to birdshot brig
2. get on prison tram
3. note that you have to alt click tile controls are on to use them, theyre hidden under the window.

**Comment by Sealed101** [comment]
curious
![image](https://github.com/tgstation/tgstation/assets/75863639/f236116d-3c69-4520-9fce-2c9666fd938c)

would there be a chance there's something wrong with layers on the client side?

**Comment by lessthnthree** [comment]
> curious
> ![image](https://github.com/tgstation/tgstation/assets/75863639/f236116d-3c69-4520-9fce-2c9666fd938c)
> 
> would there be a chance there's something wrong with layers on the client side?

I'm on 1589, you?

**Comment by Sealed101** [comment]
same

**Comment by lessthnthree** [comment]
I have new tram walls coming in like a week so I don't want to spend too
much time chasing.

**Comment by BeeSting12** [comment]
Next time I get on I'll grab a screenshot and give y'all more information, let me know if there's anything that could be helpful. Will also update my BYOND.

**Comment by lessthnthree** [comment]
I stared at the picture some more. It's not that the tram controls are under the window.

The tram controls are meant to be holographic buttons on the window. In your screenshot the tram controls are indeed there.

The controls were really only designed for Tramstation, but they were thrown on the Birdshot trams and mostly work. (Notice in my screenshot it's displaying Tram's 3 station layout.) What's happened there is the controls are blank, not that they're hidden underneath the window. There's some tram state on Birdshot that the controls don't have an icon for.

![image](https://github.com/tgstation/tgstation/assets/83487515/aafd172b-4ea4-406b-9ac0-33d55d1c429a)

There's probably no alpha layer to assist clicking if the display is blank, so it makes it seem the controls panel is unresponsive underneath the window.

I can fix that before my larger tram refactor.
