### ISSUE TITLE
Organs have no DNA, violently removed organs are not bloody

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#75585]
## Round ID: 
Noticed downstream in skyrat

## Testmerges:
n/a

## Reproduction:
Organs removed from a body do not contain any DNA  from said body when scanned with a detective scanner, which is not consistent with how they would be expected to function. This makes properly solving crimes like organ theft circumstantial. 
May apply to all bodyparts without testing.
Related but gutting someone's organs out does not cover them with blood despite the violent ejection, causing the same issue.

**Comment by Sealed101** [comment]
more like someone forgot to add those clues and they kinda should be
