### ISSUE TITLE
Tramstation is missing a maintenance drone fabricator

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#75609]
Reporting client version: 514.1589

## Round ID:
[206764](https://scrubby.melonmesa.com/round/206764)

## Testmerges:
- [Spider Infestation Balance Rebalance Expansion Part 1](https://www.github.com/tgstation/tgstation/pull/75204)

## Reproduction:
I've checked the upper and lower parts of Tramstation's maintenance near science multiple times, and I haven't been able to find a drone fabricator, so its safe to presume its missing entirely.

**Comment by MrMelbert** [comment]
Someone add this to required map contents test
