### ISSUE TITLE
Plumbing Constructor Broken.

### ISSUE THREAD

**Issue by DoomAngelBlade** [tgstation/tgstation#75618]
Reporting client version: 514.1589

## Round ID:
[206797](https://scrubby.melonmesa.com/round/206797)

## Testmerges:
- [Mark client as QDELING](https://www.github.com/tgstation/tgstation/pull/75576)
- [Should* make tgui say faster](https://www.github.com/tgstation/tgstation/pull/75534)
- [Fix runtime with chat messages deleting when their clients do](https://www.github.com/tgstation/tgstation/pull/75445)

## Reproduction:
Equip Plumbing constructor.
Use it.
See you can't do shit with it.
![image](https://github.com/tgstation/tgstation/assets/46872312/6f685a50-3817-4178-a1a9-b48ae455d6f7)

**Comment by SyncIt21** [comment]
@MTandi

**Comment by MTandi** [comment]
Oh shi. Looking into it

**Comment by MTandi** [comment]
Yes, I didn't notice that there is some other UI that reuses components from piping dispensers

```
import { ColorItem, LayerSelect } from './RapidPipeDispenser';
import { SiloItem, MatterItem } from './RapidConstructionDevice';
```

**Comment by SyncIt21** [comment]
Ahh yes, i do remember reusing these components when i made the TGUI for plumbing RCD back in #71569. I don't think it's a problem with the front end, maybe the plumbing RCD backend isn't sending the data in your new format? 'm looking into it

**Comment by SyncIt21** [comment]
Nice
