### ISSUE TITLE
Metalgen recipe not updating properly

### ISSUE THREAD

**Issue by MercuryArrow** [tgstation/tgstation#75619]
## Round ID:
Any

## Testmerges:
Not applicable

## Reproduction:
Join a round, find the old recipe for metalgen if it's rolled metalgen. Despair as you realise it's the same inapprovaline/stranger reagent recipe that was targeted by a recent fix.  The temperatures involved in the reaction are updating every few days as expected so it's definitely doing SOMETHING, but the recipe components themselves have not changed since the fix was put in two weeks ago and are still using unobtainable reagents.

To complicate matters further, after speaking with a few other people, this issue doesn't seem to be universal? The recipe seems to generate seperately across servers and this specific issue is affecting Manuel primarily.
![oldrecipe](https://github.com/tgstation/tgstation/assets/130743013/1b4b2bbb-d08f-485d-a7ce-798d9c302451)

**Comment by Sealed101** [comment]
"latest" PR to touch the code for recipe generation #72396
inaprovalin fix #75307
could it be failing to generate new reagents somehow?
