### ISSUE TITLE
Smart fridges laden with items can create client FPS drops

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#75639]
## Round ID:
[206840](https://scrubby.melonmesa.com/round/206840)

## Reproduction:

Smart fridge with a lot (1200+) of items in it causes intense FPS drop even on a fairly high end client.

Some (hopefully) useful information:

![fridge-1](https://github.com/tgstation/tgstation/assets/3789327/7f9375eb-ba34-41fd-b360-fe982d99a22d)
![fridge-2](https://github.com/tgstation/tgstation/assets/3789327/fbbe47fd-b861-4f7a-9914-d505eb66e538)
![fridge-3](https://github.com/tgstation/tgstation/assets/3789327/3e790e92-36a4-441f-bad4-ca57c07d4e03)

I guess something could be simplified in the appearance once it passes a certain number of items or something (speculating wildly the cause though)

**Comment by SyncIt21** [comment]
Not able to reproduce, also your profiling isn't helpful because it doesn't show any calls specific to smart fridge. When does the lag begin? does it only happen when adding/removing item's from the fridge or does the game lag continuously after al the items are loaded?

**Comment by iprice** [comment]
@SyncIt21 its a client FPS degradation so has no impact on pings or server performance when the fridge is off-screen.  From what I gathered from various conversations on this topic it may well relate to light emitting plants so give that a shot if you're looking to reproduce it.

As for the profiler, thats all the client shows and clearly shows a disproportionate ammount of time spent on something related to sorting lists.  I genuinely have no idea if thats actually useful to those in the know but I basically grabbed whatever info I could before round restart.  Providing excess information is better than not enough :)

**Comment by MrMelbert** [comment]
As far as I know the issue lies not in the UI code but in the fact that you can add 750 light overlays onto one atom (botany plants that glow)

**Comment by jlsnow301** [comment]
> @jlsnow301 do we still need the `md5()` function or is there a way around it?

I'm really not sure if this is still pertinent, looks like the bug predates me, even. I think the pro-engineer solution to this would be to... 

limit the smart fridges capacity to a sane number :)
