### ISSUE TITLE
Spraycans seem unable to draw on the floor

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#75664]
Reporting client version: 514.1589

## Round ID:
[206900](https://scrubby.melonmesa.com/round/206900)

## Reproduction:

Not much to say, initially reported by a borg and verified with borg model, /infinite and base class /spraycan types ; none of them seem to do anything when clicked on the floor.  Unless the cap is on in which case they tell you to take the cap off.  Then nothing.

**Comment by MrMelbert** [comment]
#75635
