### ISSUE TITLE
Syndicate Lavaland chem dispensers cannot be unwrenched

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#75684]
Reporting client version: 514.1589

## Round ID:
[206988](https://scrubby.melonmesa.com/round/206988)

## Testmerges:
- [Adds a new front end for viewing logs | fixes the manifest log message too](https://www.github.com/tgstation/tgstation/pull/75617)

## Reproduction:

1. try to move chem dispenser to new funny lab you built
2. wrench doesnt work
3. there isnt a beaker inside
4. what the fuck

**Comment by Sealed101** [comment]
it and some other dispenser variants have the NODECONSTRUCT_1 flag, preventing them from being deconstructed and moved. honestly idk why would they be like that, their circuit requires t4 parts anyway and the machine drops them upon decon

https://github.com/tgstation/tgstation/blob/b9cf1f9bb45e1253abfc3edffeb14f22a6608943/code/modules/reagents/chemistry/machinery/chem_dispenser.dm#L638-L642

**Comment by Sealed101** [comment]
fixed by https://github.com/tgstation/tgstation/pull/82280 i think; circuitboard also requires t4 parts to make the machine
