### ISSUE TITLE
Gas Overlays do not function on Lower Z-levels in multi-z maps

### ISSUE THREAD

**Issue by dwasint** [tgstation/tgstation#75709]
## Round ID:

Originally found on: https://github.com/Monkestation/Monkestation2.0
tested on tgstation commit: 385702775dc494505eaf9b7e2a77812a53c0b13b

## Reproduction:
On any multi-z level map go to its lowest z-level
spawn in a gas canister
set its pressure
open it
watch as the canister gets pushed but no overlays are created
see image below for in game view

![image](https://github.com/tgstation/tgstation/assets/82520990/46c4437f-6ed2-468a-a6eb-a4045dc0c415)

**Comment by LemonInTheDark** [comment]
god fucking damn it

**Comment by TheVekter** [comment]
Looks like this might be happening on all z-levels, not just the lowest. See above.
