### ISSUE TITLE
bows have weird-ass examine text probably inherited from the base gun

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#75711]
Reporting client version: 514.1589

## Round ID:
[207088](https://scrubby.melonmesa.com/round/207088)

## Testmerges:
- [Adds a new front end for viewing logs | fixes the manifest log message too](https://www.github.com/tgstation/tgstation/pull/75617)

## Reproduction:

<img width="278" alt="image" src="https://github.com/tgstation/tgstation/assets/80979251/ea55860b-6a2c-40a2-b139-de35703469d5">
get this shit out

**Comment by TheVekter** [comment]
I'm not sure you're intended to get this version of the bow, but it should probably at least have an actual name and desc.
