### ISSUE TITLE
The thermo-electric generator (TEG) does not work.

### ISSUE THREAD

**Issue by rageguy505** [tgstation/tgstation#75738]
Reporting client version: 514.1589

## Round ID:
[207199](https://scrubby.melonmesa.com/round/207199)

## Testmerges:
- [Adds a new front end for viewing logs | fixes the manifest log message too](https://www.github.com/tgstation/tgstation/pull/75617)

## Reproduction:
Spawn a TEG and try to set it up. Far as I can tell gas does not flow through it.

**Comment by TheVekter** [comment]
TEG isn't currently maintained; you're not wrong in that it's broken but this might not get fixed.

**Comment by rageguy505** [comment]
> TEG isn't currently maintained; you're not wrong in that it's broken but this might not get fixed.

Sure, but its still in the code so I figured it'd be something to put on here.
