### ISSUE TITLE
Guns with pinless = TRUE act strangely with autolathe.

### ISSUE THREAD

**Issue by Helg2** [tgstation/tgstation#75735]
## Reproduction:
Meat hook and ling's tentacle act strangely when you try to insert them into autolathe.
Probably because of pinless var which is TRUE, but the message from autolathe isn't connected with pins directly.
### Meathook:
1. Spawn it and put in the autolathe.
2. Gain this text, even though you refined the hook into metal:
![image](https://github.com/tgstation/tgstation/assets/93882977/52431209-4156-44d8-8d7c-007f83a9afc9)
Not an error with picture, it shows "You insert a material total of.." message 2 times.
### Tentacle:
1. Spawn the tentacle and try to put it in autolathe.
2. Achieve this message and softlock your arm because tentacle didn't dissappear:
![image](https://github.com/tgstation/tgstation/assets/93882977/4e0211b2-fb08-4433-b62e-f2ecf6938baf)
You can get materials only 1 time, and after that it just says that the firepin isn't tasty.
3. Try to shoot the tentacle and occure an error:
![image](https://github.com/tgstation/tgstation/assets/93882977/ec774715-15b6-4408-8539-425ba680d38b)

**Comment by SyncIt21** [comment]
It's not an error but an feature in #75422. Before the autolathe would only consume the item but not its contents but now it will consume all the contents of the object recursively so it will consume all the contents of the gun and anything that doesn't have enough material it will show that message.
Refining the hook into metal does its job but it doesn't effect the crystal inside so when it tries to recycle that you get the message 
This is just something we have to get used to

**Comment by SyncIt21** [comment]
However I don't understand why the tentacle isn't getting consumed , it's trying to fire a garbage collected component so I'll have to check that

**Comment by SyncIt21** [comment]
Ok found the problem. I'll fix this

**Comment by newfren** [comment]
seems like an error that the changeling tentacle could be consumed by the autolathe at all

**Comment by SyncIt21** [comment]
Ok I figured out the problem. I'll fix this.
