### ISSUE TITLE
Preference icon dropdown menus become blank after UI is closed

### ISSUE THREAD

**Issue by timothymtorres** [tgstation/tgstation#75741]
## Reproduction:

Use any Typescript menu that uses the `FeatureIconnedDropdownInput` component.  When you select a value it displays properly, but after the UI closes it becomes blank when you reopen it.  Strangely, the UI selection is still saved to preferences properly.

Before:

![BLJyhrJGL5](https://github.com/tgstation/tgstation/assets/5195984/b4973bdb-70a1-4839-878f-fea4e55e42eb)

After:

![y85u2EPdJn](https://github.com/tgstation/tgstation/assets/5195984/2d07e1d6-7539-4965-9f8e-87bbffca76b8)

CC @Mothblocks

**Comment by itsmeow** [comment]
add to https://github.com/tgstation/tgstation/milestone/63
