### ISSUE TITLE
If a felinid chooses to not have a tail, the cat butcherer will still rip said tail out

### ISSUE THREAD

**Issue by Jolly-66** [tgstation/tgstation#75746]
## Round ID:
Tested locally.

## Reproduction:
1. Be a flinid
2. Don't have a tail
3. Cat butcherer neuron activation
4. You now suddenly have a tail that's butcherable (???)

![image](https://github.com/tgstation/tgstation/assets/70232195/b8c6e6a6-b21a-461f-bd79-844ecf854781)

![image](https://github.com/tgstation/tgstation/assets/70232195/1d56c41c-1638-4cea-86c8-354ffac8ca3d)

Also relevant [downstream issue](https://github.com/TaleStation/TaleStation/issues/5875).

**Comment by itseasytosee** [comment]
I'm fairly certain TGstation does not offer felinids without tails. May the watchers have mercy.

**Comment by Jolly-66** [comment]
> I'm fairly certain TGstation does not offer felinids without tails. May the watchers have mercy.

They do check prefs. My tests were done using my /tg/ local.

**Comment by MrMelbert** [comment]
It's because we do tailless felinids in the stupidest way - by just making the icon invisible

**Comment by ATH1909** [comment]
cursed

**Comment by ATH1909** [comment]
> It's because we do tailless felinids in the stupidest way - by just making the icon invisible

WHAT
