### ISSUE TITLE
Roundend Report still links to Statbus despite it being dead 

### ISSUE THREAD

**Issue by Archie700** [tgstation/tgstation#75753]
## Round ID: 
[207219](https://scrubby.melonmesa.com/round/207219)

## Testmerges: 
https://github.com/tgstation/tgstation/pull/75617

## Reproduction: 
When clicking on the round number in the roundend report, it still opens a window leading to statbus, even though the statbus has been closed down for a while. It should be linked to scrubby instead.

![6RtHX5kETc](https://github.com/tgstation/tgstation/assets/17823321/7899150a-1ab2-4b4c-bb8b-0b353b542fbd)
![chrome_Jdg2jDSTQj](https://github.com/tgstation/tgstation/assets/17823321/8aec6254-1b88-4082-9b71-859412498272)

**Comment by Sealed101** [comment]
goodnight sweet prince

https://github.com/tgstation/tgstation/blob/master/code/__HELPERS/roundend.dm#L325-L328

**Comment by nfreader** [comment]
Definitely fixable.

**Comment by nfreader** [comment]
Oh, actually, the code accounts for the stat URL not being defined, but it's still defined in the server config. Not a bug! :)
