### ISSUE TITLE
Apcs do not always charge or accept power for upkeep when set to auto even when enough power is available.

### ISSUE THREAD

**Issue by moocowswag** [tgstation/tgstation#75789]
## Round ID:  [207081](https://scrubby.melonmesa.com/round/207081)

https://github.com/tgstation/tgstation/assets/62126254/3b02e690-a5f5-4e48-9af3-1a99ce376c2f

## Reproduction:

Disconnect the apc and a portion of cable from the grid and try to power it with a stable power source like a pacman to remove other factors

Check the wire with a multi tool

The apc will either 

A- Try to match the power supplied to it (increase load) so that it can take in excess power into its battery.
(INTENDED)

or
B- Stop taking power from its cable at all (resulting in a load of 0 on the cable) during this period the apc will lose charge because 
its not accepting power.
(Most likely a bug)

or
C- Continue just pulling its normal load of whatever power it requires just to power the machines in its room, usually swaps 
between this and B.
(Sort of intended, especially if the battery is full)

I do not know the conditions that cause B.

And i have reason to believe this doesnt just happen on individual APCs with their own grid I just think its easiest to test that way.

**Comment by moocowswag** [comment]
also for further clarification on the video, that apc eventually died despite constantly having access to more power than its internal load.

**Comment by BlueMemesauce** [comment]
From the video, looks like the APC draw went to 50 kW and stopped charging since the supply was only 40 kW. Looks like its working as intended to me, although the initial time it took to charge was a little slow.

**Comment by TheVekter** [comment]
> From the video, looks like the APC draw went to 50 kW and stopped charging since the supply was only 40 kW. Looks like its working as intended to me, although the initial time it took to charge was a little slow.

The APC draw never went to 50, I'm not seeing that at all in the video.

**Comment by BlueMemesauce** [comment]
![image](https://github.com/tgstation/tgstation/assets/47338680/53f8e6c8-6f7d-4f4e-b943-4fd1e06f82b4)

**Comment by moocowswag** [comment]
Something is still weird, so whenever an apc tries to charge it draws more power? Then if the wire cant deal with that increase power draw it just stops taking power at all and loses charge?
