### ISSUE TITLE
Crates look horribly contorted

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#75814]
![obraz](https://github.com/tgstation/tgstation/assets/68878861/dd198c91-6933-4df9-8575-540ed16e192d)

## Round ID:
[207420](https://scrubby.melonmesa.com/round/207420)

## Testmerges:
#75617 

## Reproduction:
Walk by a bunch of crates. Notice how they have uncanny proportions, are shaded inappropriately to the lighting around them and have a shine to them akin to a plastic object. 

After encountering various subtypes, notice the lack of former detail and encounter trouble with identifying them without examination.

Open a crate, to notice that they now possess a high-tech interior, not befitting the game's style, nor representing their functionality.

**Comment by Likteer** [comment]
The following PR may close this issue:
https://github.com/tgstation/tgstation/pull/66557

**Comment by SyncIt21** [comment]
You can blame #75785.

**Comment by Likteer** [comment]
![obraz](https://github.com/tgstation/tgstation/assets/68878861/54215ae0-15e1-49b7-9d0b-d5a14a3b6107)
Thank you Sync. A comment under the PR also meantions they look unfit to be carried by MULEbots (MULEbot sprites are fairly fresh).

**Comment by LemonInTheDark** [comment]
malding in my issue reports is unproductive and only serves to clutter an already fucked issue tracker.
crates not fitting on mulebots is a real concern, the rest of this is personal preference, and we have artists to make that decision. you disagreeing with them is not a bug

**Comment by moocowswag** [comment]
Honestly them being alittle too big for the mulebots is realistic for a place full of workplace hazards

**Comment by TheVekter** [comment]
> ![obraz](https://user-images.githubusercontent.com/68878861/242959527-54215ae0-15e1-49b7-9d0b-d5a14a3b6107.png) Thank you Sync. A comment under the PR also meantions they look unfit to be carried by MULEbots (MULEbot sprites are fairly fresh).

Someone has already mentioned they will be fixing the mulebot sprite.
