### ISSUE TITLE
Heretic's might not be able to sac a head of staff post rev victory

### ISSUE THREAD

**Issue by the-orange-cow** [tgstation/tgstation#75811]
Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [207383](https://scrubby.melonmesa.com/round/207383)
BYOND Version: 515.1607
Server revision compiled on: 
Master commit: [f125f4592cf0d90e7b5cb9d603dc6cf1e2634aba](https://www.github.com/tgstation/tgstation/commit/f125f4592cf0d90e7b5cb9d603dc6cf1e2634aba)
The following pull requests are currently test merged:
[#75617: 'Adds a new front end for viewing logs | fixes the manifest log message too' by ZephyrTFA at commit 40714a3c47](https://www.github.com/tgstation/tgstation/pull/75617)

Local commit: d85ac7bd6eae55d39290b05d8d66b4890a5c6b12
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

I was the servant to a flesh heretic, they were stuck without being able to sac a head post rev victory till an admin logged on and helped.

**Comment by blackdav123** [comment]
also https://github.com/tgstation/tgstation/issues/74028

**Comment by moocowswag** [comment]
They couldnt even roll a head of staff as a sac target , objective needs to just auto resolve when that happens

**Comment by GPeckman** [comment]
I was the heretic in question. I was able to sacrifice the QM's body after revs won, but for some reason it didn't count as a head of staff, and I rerolled my sacrifices 3 times but didn't get any heads of staff because they were all already dead.

**Comment by the-orange-cow** [comment]
> I was able to sacrifice the QM's body after revs won

I mean, I think we all know that the QM isn't a real head of staff, but yeah.

**Comment by Mothblocks** [comment]
What does "unable to" mean in this case? You couldn't acquire one because they were unrevivable? You tried but it didn't do anything?

**Comment by the-orange-cow** [comment]
> What does "unable to" mean in this case? You couldn't acquire one because they were unrevivable? You tried but it didn't do anything?

Someone correct me if I'm wrong.  I belive the heretic in question sac'd the QM's body post rev victory, but it didn't fulfill the head of staff requirement for ascension.  Following this, the heretic did the reroll target ritual several times, but no heads of staff were rolled as sac targets.

**Comment by GPeckman** [comment]
That is correct. I don't know why the QM didn't count as a head in this case, and unfortunately it doesn't look like heretic sacrifices are logged.

**Comment by carlarctg** [comment]
@TheVekter close this

**Comment by TheVekter** [comment]
> @TheVekter close this

Don't tell me what to do.
