### ISSUE TITLE
Space tiles in incorrect basketball arena spawn

### ISSUE THREAD

**Issue by Teleported-Bread** [tgstation/tgstation#75822]
Reporting client version: 514.1589

## Round ID:
[207448](https://scrubby.melonmesa.com/round/207448)

## Testmerges:
- [Adds a new front end for viewing logs | fixes the manifest log message too](https://www.github.com/tgstation/tgstation/pull/75617)
- [It's Nice To Be Unique: Adds new quirks to pick up!](https://www.github.com/tgstation/tgstation/pull/75630)

## Reproduction:
1) Start basketball with 3 people
2) ???
3) This happens. These are actual space tiles, no gravity or pressure or O2, and I couldn't move.
<img width="825" alt="Report this 3" src="https://github.com/tgstation/tgstation/assets/28495609/18e68fe4-d228-43ec-83d9-0e25357255f1">
<img width="1192" alt="report this 4" src="https://github.com/tgstation/tgstation/assets/28495609/83ccc1e5-b198-45c7-81e9-974072079b34">

**Comment by timothymtorres** [comment]
I know there was a PR up to change water sprites around the same time as when I added this map a few weeks ago.  They probably forgot to properly swap out the tiles with the new tile path.  

Should be a simple mapping fix.
