### ISSUE TITLE
Ethereal-turned humans due to being selected for/selecting a command role when joining still have some "artifacts" from being an ethereal

### ISSUE THREAD

**Issue by Hotmud9** [tgstation/tgstation#75838]
## Round ID:
I don't think the Round ID is required in this situation, as it has to do with something that occurs at roundstart due to character creation.

## Testmerges:
Don't think it has to do with a testmerge.

## Reproduction:
When using an ethereal character, after selecting a command role and becoming a human, said human still has LE blood, but still needs to eat like a normal human.
This could be fixed by simply defaulting to the human options that someone could have set for that species. (Maybe.)

**Comment by ChungusGamer666** [comment]
where is the against god and nature tag when we need it
