### ISSUE TITLE
SiliConnect app doesn't work/producing empty report

### ISSUE THREAD

**Issue by LikesGreen** [tgstation/tgstation#75831]
## Testmerges:

[#75617: 'Adds a new front end for viewing logs | fixes the manifest log message too' by ZephyrTFA at commit 40714a3c47](https://www.github.com/tgstation/tgstation/pull/75617)
[#75630: 'It's Nice To Be Unique: Adds new quirks to pick up!' by orthography at commit 479c812f6c](https://www.github.com/tgstation/tgstation/pull/75630)
## Reproduction:

1. Download SiliConnect app as robotic
2. Right click borg, see progress on app to produce report 
3. Report comes out empty, nothing is there

**Comment by Sealed101** [comment]
testing reveals that it produces the report, but it fails to update the tgui window somehow; minimizing the program or closing the tablet window and reopening will print out the log just fine.


https://github.com/tgstation/tgstation/assets/75863639/a2fc4753-5a5c-41cc-9214-d5dbea384fb4



code:

https://github.com/tgstation/tgstation/blob/0dd70993f996a1f7530035a64b3cf3afb702f527/code/modules/modular_computers/file_system/programs/borg_monitor.dm#L55-L68

i also have a suspicion that these ui update failures are the same that are happening in #74839
