### ISSUE TITLE
Pre-installed pathfinder modules don't start implanted.

### ISSUE THREAD

**Issue by MIC132** [tgstation/tgstation#75877]
## Reproduction:
 - Spawn as Captain on any station that starts you with a MODsuit (probably all, tested on Meta)

The Captain's MODsuit starts pre-installed with the pathfinder module (that allows you to recall your suit), but you don't start with the matching implant implanted. This can be remedied if you have a screwdriver and a crowbar (take out the module, whack yourself with it, put it back in) but it makes little sense that you would need to do this when you start as a Captain (maybe makes sense for latejoins).

I'm not sure if any other (assigned) MODsuits start with pathfinder, but if so the same applies. Of course if the suit doesn't explicitly belong to a role, and has pathfinder (don't think anything like that exists?), it would make sense for it to need manual implanting.

**Comment by Fikou** [comment]
the station doesn't hook you up fully to its equipment, its the same case with things such as the cmo's autosurgeon for medhud implants

**Comment by MIC132** [comment]
Maybe it should at least not start inside the MODsuit, so you wouldn't need to crowbar it out? That would make it more in-line with said autosurgeon for medhud implants, even.
