### ISSUE TITLE
Chili and Tomato Soup reaction conflict

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#75886]
Chili and Tomato Soup have a conflicting recipe. Attempting to cook Chili in a soup pot will result in half of the reaction being tomato soup if you are making chili with a portion size larger than 1. A similar problem would probbably occur in Chili sin Carne, as it also has a recipie which includes all the ingredients for tomato soup in a large batch.

## Reproduction:

Prepare a pot of chili, using twice the minimum ingredients. 

Observe that your chili is contaminated by tomato soup.

**Comment by Dorsisdwarf** [comment]
Tomato Soup should probbably be given an extra reagant requirement to avoid this, as I think technically this interaction will occur for ALL soups with tomatoes in.

**Comment by MrMelbert** [comment]
If we want to keep the recipe as simple as possible we could simply bring the heat up a little bit. 
Otherwise we could add a requirement for onions (sliced), garlic, butter, or cream.
I think butter's (criminally?) underutilized in recipes so it might fit well
