### ISSUE TITLE
potted plant bug

### ISSUE THREAD

**Issue by magicbrannch** [tgstation/tgstation#75918]
Reporting client version: 514.1589

## Round ID:[207803](https://scrubby.melonmesa.com/round/207803)
(http://127.0.0.1:57115/tmp13364/d9f97482.htm?action=openLink&link=https%3A%2F%2Fsb.atlantaned.space%2Frounds%2F207803)

## Reproduction:

 grab a potted plant, any, throw it any where, the plant will change plants, if it doesnt change, then find a differnt potted plant.

**Comment by Likteer** [comment]
Notable example in the cockpit of the alien shuttle.
