### ISSUE TITLE
Space Dragon fire breath can hit you multiple times if you move

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#75930]
## Reproduction:

Move on tile with firebreath, get one shotted
![Screenshot_86](https://github.com/tgstation/tgstation/assets/64209864/f9d5f61b-f052-4b5b-98e0-e77e8ee5364d)

**Comment by Likteer** [comment]
Similar to the cloud of fire sent backwards by rocket launchers.

**Comment by DaydreamIQ** [comment]
I think that's cause the tip of the fire breath is the actual damaging part of it, so if you keep running in a straight line away from it you'll get hit over and over. The same thing happens with Ash drake iirc.

**Comment by IndieanaJones** [comment]
Daydream is correct. The tip of the fire is the part that does actual damage. With the recent speed increase to the fire breath's travel time, running directly away from it will probably get you hit several times
