### ISSUE TITLE
Feature surgery can remove tails that aren't supposed to be there.

### ISSUE THREAD

**Issue by YehnBeep** [tgstation/tgstation#75979]
## Reproduction:
Related to [75963](https://github.com/tgstation/tgstation/pull/75963) and https://github.com/tgstation/tgstation/issues/75746

1. Spawn a felinid with the tail option set to 'none'
2. Perform "feature manipulation" surgery targeted at the tail
3. Note that the organ is removable.

**Comment by Sealed101** [comment]
notail felinids are an abomination
