### ISSUE TITLE
A Slimeperson's conciousness is tied to the body rather than the brain.

### ISSUE THREAD

**Issue by MisterBomb7** [tgstation/tgstation#75989]
As a slimeperson, you can swap to your cloned body even if it has a brain that is not yours. I _assume_ you're supposed to be able to switch between brains rather than bodies, and if you aren't, why would you even need a brain in the first place?

# Reproduction:

1. Become a slimeperson.
2. Split yourself.
3. Replace your clone's brain with any other kind, even one that belonged to someone else.
4. You are still able to swap to your cloned body.

**Comment by ATH1909** [comment]
this is one of the few ways to transfer your consciousness into a new brain, yeah. I don't think this is a bug?

the really cool part about this is that you can share your slimeperson body network with other people if you brainswap them with one of your clones.

**Comment by Pumpkinoe** [comment]
this is cool and shouldn't be removed, it's not really a bug that causes people to be kicked out of a body and RR'd or something
there's even special function to show that a body is 'occupied' when someone else is using it

**Comment by SethLafuente** [comment]
> As a slimeperson, you can swap to your cloned body even if it has a brain that is not yours. I _assume_ you're supposed to be able to switch between brains rather than bodies, and if you aren't, why would you even need a brain in the first place?
> 
> # Reproduction:
> 1. Become a slimeperson.
> 2. Split yourself.
> 3. Replace your clone's brain with any other kind, even one that belonged to someone else.
> 4. You are still able to swap to your cloned body.

Slimes by nature don't really have a central brain system as their being is just their whole self so it would so this makes sense I don't really see it as a bug, even if it is its pretty cool (feature)

**Comment by ExcessiveUseOfCobblestone** [comment]
Should be the opposite, the body should be how youre able to interact with the slime network.

Unless someone says its not intended i think it should just be considered emergent gameplay :)

**Comment by TheVekter** [comment]
I agree with Cobby, unless someone corrects me, I'm calling this too cool to fix.

**Comment by MisterBomb7** [comment]
In that case do you think it would be better to remove their need for a brain (like with their heart, where they don't need one but can have one implanted)?
