### ISSUE TITLE
holy melon has no on-character sprite

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#75981]
![image](https://github.com/tgstation/tgstation/assets/42606352/35c94e34-d453-478a-b54d-116db7c131b1)

this is important, because it's normal-sized and only blocks spells when held

but you can't tell if someone's holding it at a glance

**Comment by the-orange-cow** [comment]
The glow would give it away, but holy melon hand sprites would be cool regardless.

**Comment by SethLafuente** [comment]
I could probably add this but Its just the fact that every single fruit just doesn't have a hand sprite more than it being an error that holy melons don't have one

**Comment by SethLafuente** [comment]
![New Piskel (2)](https://github.com/tgstation/tgstation/assets/84478872/0fabe183-0571-4dcb-95cb-7d8f85f09dc4)
![New Piskel (4)](https://github.com/tgstation/tgstation/assets/84478872/9f1f91bd-12ea-4b3d-97ff-dc702e242a1b)
