### ISSUE TITLE
No one fucking knows how to fix telecomms for upper tram z-level.

### ISSUE THREAD

**Issue by Pickle-Coding** [tgstation/tgstation#75991]
## Reproduction:
Deconstruct telecomms hub in tramstation, reconstruct telecomms hub. Do usual shit to fix it. The upper z-level won't be fixed, only lower z-level. Even as a ghost I couldn't find the telecomm machinery in the upper level to get the upper z-level fixed. There's no reasonable way to link it without building a new machine.

**Comment by Ryusenshu** [comment]
well i know :)
its in the back of upper ai sat

**Comment by Sealed101** [comment]
its in the ai sat lol

**Comment by Sealed101** [comment]
this sucker
![image](https://github.com/tgstation/tgstation/assets/75863639/5101eb76-ce2d-4ff4-b215-15b5de4b3afe)

**Comment by LemonInTheDark** [comment]
why does tcomms need to be fixed on explicitly the upper floor

**Comment by Pickle-Coding** [comment]
To link the machinery together. Though I guess it doesn't actually make sense considering they're on the same station. This problem is like 4* worse on Northstar though.

**Comment by LemonInTheDark** [comment]
we should have z... zones? groups of z levels near each other, that all use the same machinery and such.
I thought we did tbh, with the grav gen and all. Guess that's handled some other way?

**Comment by Pickle-Coding** [comment]
Maybe telecomms just simply doesn't respect the z zones, and explicitly chrcks for the z-level. I have no idea if z-zones exist or not, but I hope they do. Would make that a more simple fix.
