### ISSUE TITLE
The ChemMaster gives patches far too long names

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#76011]
Reporting client version: 514.1589

## Round ID:
[208097](https://scrubby.melonmesa.com/round/208097)

## Testmerges:
- [Pink Security](https://www.github.com/tgstation/tgstation/pull/75946)

## Reproduction:
The following is the default name given by the ChemMaster to 30u patches of Saline-Glucose Solution. The name given has 44 characters while the maximum is 42 characters. I'm not precisely sure, but I think that before the "chemical patch" part was not there.
![image](https://github.com/tgstation/tgstation/assets/42555530/27607ac4-d47c-49f0-8051-cbaa462dab81)
I think #75849 may have changed the way patch names work, because this was not an issue before.

**Comment by ExcessiveUseOfCobblestone** [comment]
Im pro keeping the limit low because I don’t want every chem in the patch listed in the name.

If you are scared of a patch you can ask about it or if you’re feeling particularly gamey you can chemscan one.

If the issue is that patch and unit amount are being counted Id rather that be pulled out and either auto-appended or provided as a second option (ie “do you want to include unit amount?”)

**Comment by ExcessiveUseOfCobblestone** [comment]
Yeah that’s fine.

i was thinking having the unit amount as a separate option so it can be included in the final name if you so desired but wouldn’t be taking up slots in the custom name portion.

**Comment by Justice12354** [comment]
> Yeah that’s fine.
> 
> i was thinking having the unit amount as a separate option so it can be included in the final name if you so desired but wouldn’t be taking up slots in the custom name portion.

For the vast majority of relevant chemicals, the name limit will not be reached if my PR is merged, so having the amount count as a separate option will not be that big of a deal towards this objective (specially since it only takes up to 6 characters). Furthermore, I personally would dislike that change, since it'd just be more buttons to press. As it currently is, making chemicals and printing patches/pills is already very tedious and repetitive, so I don't think adding another button would be fun.

If I could ask for a change for ChemMasters, I'd ask that the number of products printed would be saved once the UI is closed (which was a thing b4). As it currently is, let's say you print 20 patches and then close the UI, once you open it again, it will go back to 1. Idk if this was intended or not with the ChemMaster revamp, but I quite enjoyed how it was before.

**Comment by Justice12354** [comment]
> I don't think it was working like that before my change. But regardless, I don't see why it should be there. You only need it to start the printing. Why would you need it saved? Can you share your use case?

When I am making Saline Glucose patches, I make 30u each and usually try to make 9 patches total. Since with a normal beaker I make 90u at a time, I have to print the patches 3 times. To be quite honest, it's not something very concerning, but it makes the work easier and takes more clicks away. It's just a small QOL change for those of us who print the same multiple times.

**Comment by ExcessiveUseOfCobblestone** [comment]
A simple checkbox on the initial window to include units in name would not add to the level of buttons…

Anyways I think this is more of a feature request versus an issue warranting of being tracked especially w the pr that opened up a few char slots so ima go ahead and close.
