### ISSUE TITLE
Autotomy floating torso bug

### ISSUE THREAD

**Issue by F-e-r-n** [tgstation/tgstation#76028]
Reporting client version: 514.1589

## Round ID:
[208130](https://scrubby.melonmesa.com/round/208130)

## Testmerges:
- [Pink Security](https://www.github.com/tgstation/tgstation/pull/75946)

## Reproduction:
walking with no limbs is possible! you just have to get autotomy and rid yourself of one leg, wait for the action timer to get up, then get rid of the other. This tricks the game into thinking you have legs, allowing you to rest and get up even if you dont have arms or legs

**Comment by SyncIt21** [comment]
Duplicate if #73211
