### ISSUE TITLE
Protolathe material readouts are inaccurate and show 1/10th of how much is actually in the silo.

### ISSUE THREAD

**Issue by Gristlebee** [tgstation/tgstation#76027]
Reporting client version: 514.1589

## Round ID:
[208129](https://scrubby.melonmesa.com/round/208129)

## Testmerges:
- [Pink Security](https://www.github.com/tgstation/tgstation/pull/75946)

## Reproduction:

<img width="281" alt="fuckedup" src="https://github.com/tgstation/tgstation/assets/56049844/642ecc1c-d445-4948-bd4b-59acc8c31359">

1. Check lathe - see that there's barely any mats.
2. Check ORM - see how many mats there actually are.

Both ORM and the lathes were properly synced to the ore silo when I checked.

**Comment by GPeckman** [comment]
This is an intentional side effect of #75437, a sheet of metal is now 100 units instead of 2000. There are are few bugs with the GUI, though-the material icon still gets grayed out below 2000 units, when it should now be 100 units.
