### ISSUE TITLE
Gases aren't getting garbage collected

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#76034]
Why?
![Screenshot (255)](https://github.com/tgstation/tgstation/assets/110812394/5c8d58bf-dff8-4313-8e98-af4dbbf1d042)

We shouldn't be dealing with "extremely small" values like these
![Screenshot (257)](https://github.com/tgstation/tgstation/assets/110812394/693d9dab-f4a5-47bb-8e5b-2064aecb20b4)

These gases should be gone by now but they arent

**Comment by SyncIt21** [comment]
Ok confirmed it is caused by https://github.com/tgstation/tgstation/pull/74233. Just downloaded the repository before this PR at [this](https://github.com/tgstation/tgstation/tree/ccef887efec2cb3025228210bcb134700aac5175) point and everything worked.

**Comment by LemonInTheDark** [comment]
was under the impression it was https://github.com/tgstation/tgstation/pull/75935#issuecomment-1586193413

**Comment by SyncIt21** [comment]
My bad your right it is caused by #75935.
