### ISSUE TITLE
Medieval Sim Dome escape shuttle doesnt properly the red or blue team highlights for the knights on spawn.

### ISSUE THREAD

**Issue by Gristlebee** [tgstation/tgstation#76045]
Reporting client version: 514.1589

## Round ID:
[208197](https://scrubby.melonmesa.com/round/208197)

## Reproduction:
1. Get the Medieval Sim dome shuttle.
2. Spawn in.
3. Don't get the highlight.
4. Walk out and step back inside the spawn area.
5. Highlight is now applied.

**Comment by TheVekter** [comment]
Can you get us some screenshots? I'm not understanding what you're referring to.

**Comment by Sadboysuss** [comment]
this doesn't seem to be an issue anymore
