### ISSUE TITLE
Donut Inhand sprites are not good

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#76058]
## Round ID:

Currently donut inhand sprites are missing the code line to relay back to them having inhand spriters 
![image](https://github.com/tgstation/tgstation/assets/84478872/dc06059b-e5cb-4b4c-8a58-e9d8fc4c17c7)

Meanwhile their also missing the right hand spriters:
![image](https://github.com/tgstation/tgstation/assets/84478872/574af23a-2f41-4212-8047-a8578ea0183c)

This is basically free GBP to be honest just flip some sprites and add the singular missing code line

**Comment by carlarctg** [comment]
@TheVekter close this

**Comment by Sealed101** [comment]
sniped
