### ISSUE TITLE
All coins are worth 5 credits

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#76052]
![obraz](https://github.com/tgstation/tgstation/assets/68878861/85518cad-4a21-4a19-b8b6-bbd6f64fb7c1)

## Round ID:
[208227](https://scrubby.melonmesa.com/round/208227)

## Testmerges:
[#75819: 'A small pile of borg combat changes' by Kubisopplay at commit e2ed05a257](https://www.github.com/tgstation/tgstation/pull/75819)

Most likely related to the other, recent material issues.

## Reproduction:
Easy ways to observe this are gambling, wallet spawns, captain's office and MetaStation's garden.

**Comment by ChungusGamer666** [comment]
this will be terrible for the economy

**Comment by ArcaneMusic** [comment]
Interesting. ~~Shit~~

**Comment by Momo8289** [comment]
Fixed here: #76066

**Comment by SyncIt21** [comment]
@ArcaneMusic please close this issue

**Comment by Likteer** [comment]
https://github.com/tgstation/tgstation/pull/76066
Fixed. Didn't autoclose.
