### ISSUE TITLE
Matching threats fail to execute

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#76100]
Reporting client version: 514.1589

## Round ID:
[208364](https://scrubby.melonmesa.com/round/208364)

## Reproduction:
1. Roll a midround ghost threat, like a Nightmare or, in this case, a Space Ninja
2. Try to roll the same threat again, here where another Ninja tried to spawn due to the console hacking
3. Threat is consumed, but the second threat is never spawned

**Comment by MrMelbert** [comment]
Related: https://github.com/tgstation/tgstation/issues/69327
Keeping this one open, see the other for additional logs.

**Comment by Sadboysuss** [comment]
still an issue?
