### ISSUE TITLE
Mining Cyborg's Lavaproofing upgrade does not protect from liquid plasma

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#76107]
Reporting client version: 514.1589

## Round ID:
[208383](https://scrubby.melonmesa.com/round/208383)

## Testmerges:
- [Adds new brain damage line](https://www.github.com/tgstation/tgstation/pull/76083)
- [Energy Weapon Touch-up: Thermal Pistols Rework, X-01 Multiphase new shot type, DRAGnets are just gone ](https://www.github.com/tgstation/tgstation/pull/76076)

## Reproduction:
The mining cyborg's lava-proof track upgrade does not provide damage prevention for the cyborg when traveling through Ice Box's liquid plasma, which is the lava equivalent for the map.
1. Become mining borg
2. Acquire that lava-proof track upgrade
3. Walk into liquid plasma
4. Gradually take damage

**Comment by timothymtorres** [comment]
This isn't regular volcano lava.  It's chilled plasma lava that is below freezing temps.

```
/turf/open/lava/plasma
	name = "liquid plasma"
	desc = "A flowing stream of chilled liquid plasma. You probably shouldn't get in."
	initial_gas_mix = "n2=82;plasma=24;TEMP=120"
	immunity_trait = TRAIT_SNOWSTORM_IMMUNE
	immunity_resistance_flags = FREEZE_PROOF
	lava_temperature = 100
```
