### ISSUE TITLE
Advanced ion jetpack module and normal ion jetpack module don't work

### ISSUE THREAD

**Issue by LikesGreen** [tgstation/tgstation#76116]
## Round ID:
[208399](https://scrubby.melonmesa.com/round/208399)

## Reproduction:

1. Print ion jetpack module for modsuit
2. Put it into modsuit
3. Go to space, turn ion jetpack on, realized its not working

Tested also advanced ion jetpack module, same result, you turn it on but its not working.

**Comment by Sealed101** [comment]
broken by #75844 as `user` is not being passed with the signal to the modsuit jetpack's component so no signals are being registered

https://github.com/tgstation/tgstation/blob/5509c32cedb937069bb64abcec289684366623e8/code/datums/components/jetpack.dm#L81-L90

**Comment by Stonetear** [comment]
piss :(
