### ISSUE TITLE
Medical Cyborg's beaker apparatus cannot grab vials/tubes

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#76111]
Reporting client version: 514.1589

## Round ID:
[208387](https://scrubby.melonmesa.com/round/208387)

## Testmerges:
- [Energy Weapon Touch-up: Thermal Pistols Rework, X-01 Multiphase new shot type, DRAGnets are just gone ](https://www.github.com/tgstation/tgstation/pull/76076)
- [Adds new brain damage line](https://www.github.com/tgstation/tgstation/pull/76083)
- [Xenomorph/Alien Rework 2023: Part 1](https://www.github.com/tgstation/tgstation/pull/75286)
- [Optimization pass focused on foam code (saves about 30% of cpu usage I think)](https://www.github.com/tgstation/tgstation/pull/76104)

## Reproduction:
The beaker apparatus can grab bottles and beakers, but they cannot grab tubes/vials.
1. Be a medical cyborg
2. Make something/Do something that involves a tube from the chemmaster
3. Attempt to grab it
4. Fail

**Comment by Sealed101** [comment]
then again, was it possible for that module to grab chemmaster bottles before they were switched out for the tubes?
