### ISSUE TITLE
Orbit menu refuses to open

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#76127]
## Testmerges:
Round ID: [208447](https://scrubby.melonmesa.com/round/208447)
BYOND Version: 515.1607
Server revision compiled on: 
Master commit: [d1373015cce17f037849c1c1bc947f1dfe352bbf](https://www.github.com/tgstation/tgstation/commit/d1373015cce17f037849c1c1bc947f1dfe352bbf)
The following pull requests are currently test merged:
[#76076: 'Energy Weapon Touch-up: Thermal Pistols Rework, X-01 Multiphase new shot type, DRAGnets are just gone ' by necromanceranne at commit 13040fe696](https://www.github.com/tgstation/tgstation/pull/76076)
[#76104: 'Optimization pass focused on foam code (saves about 30% of cpu usage I think)' by LemonInTheDark at commit 8984031be8](https://www.github.com/tgstation/tgstation/pull/76104)

Local commit: 389c56aae178b9b519cf04e23ed55e4fcaac1b07
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1

## Reproduction:

no idea how to reproduce, after killing myself with the russian revolver then DNRing myself i became unable to open the orbit menu, admin Bmon pressed something that fixed it later

**Comment by TheVekter** [comment]
I can't reproduce this at this time following your steps.
