### ISSUE TITLE
Mech's Plasma Generator consumes fuel ridiculously fast

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#76132]
Reporting client version: 514.1589

## Round ID:
[208454](https://scrubby.melonmesa.com/round/208454)

## Testmerges:
- [Optimization pass focused on foam code (saves about 30% of cpu usage I think)](https://www.github.com/tgstation/tgstation/pull/76104)
- [Xenomorph/Alien Rework 2023: Part 1](https://www.github.com/tgstation/tgstation/pull/75286)
- [Adds new brain damage line](https://www.github.com/tgstation/tgstation/pull/76083)
- [Energy Weapon Touch-up: Thermal Pistols Rework, X-01 Multiphase new shot type, DRAGnets are just gone ](https://www.github.com/tgstation/tgstation/pull/76076)

## Reproduction:
Since the mineral rebalancing when in and changed the material values for everything, plasma has become less for its material amount but the same overall in terms of item production. 

However, the plasma consumption rate for the mech's plasma generator remains the same before the material rebalance, and currently consumes an amount of plasma which would be fine prior to the rebalance. With the current amount it consumes with the changed values (About at a rate of 200cm3?), it consumes ridiculously fast, and would need a large amount of plasma to supply it decently for long periods of time.

**Comment by SyncIt21** [comment]
@Sealed101 was this caused by #75704?

**Comment by Sealed101** [comment]
that pr made the damned thing work in the first place. but yes, after the mineral rebalance plasma sheets cost less and the engine's consumption rates and fuel capacity have not been changed to fit
