### ISSUE TITLE
Service Hall Lightswitch is Outside of the Room (and therefore appears to be missing)

### ISSUE THREAD

**Issue by GoldenAlpharex** [tgstation/tgstation#76144]
It's just on the wrong side of the wall, it just needs to be put inside of the room instead of outside.

Cc @Cheshify <3

**Comment by Sealed101** [comment]
assuming this is for northstar

**Comment by GoldenAlpharex** [comment]
> assuming this is for northstar

Yeah it is, I don't know why I forgot to put it in this issue report.

**Comment by DATA-xPUNGED** [comment]
Took a while to find out the specific area, but i don't think that lightswitch was ever MEANT to be from the service hall:
![image](https://github.com/tgstation/tgstation/assets/44149906/460df841-dba7-43c8-9f97-138ad24d1029)
The lightswitch is placed here, but-
![image](https://github.com/tgstation/tgstation/assets/44149906/d4763c31-fa62-4670-bf2c-6a14df84ce31)
The service hall area seems to overextend its boundaries here, i'm pretty sure that lightswitch was meant for the locker room instead (especially as lightswitches for "public" areas aren't common)

**Comment by Sealed101** [comment]
fixed by some other PR

![изображение](https://github.com/tgstation/tgstation/assets/75863639/5fbe9de0-e9e1-4c73-8ba1-b767ee08968b)
