### ISSUE TITLE
Pie overlays give monkeys a second head

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#76148]
Reporting client version: 514.1589

## Round ID:
[208508](https://scrubby.melonmesa.com/round/208508)

## Testmerges:
- [Optimization pass focused on foam code (saves about 30% of cpu usage I think)](https://www.github.com/tgstation/tgstation/pull/76104)
- [Energy Weapon Touch-up: Thermal Pistols Rework, X-01 Multiphase new shot type, DRAGnets are just gone ](https://www.github.com/tgstation/tgstation/pull/76076)
- [Build Mode Preview + better help text](https://www.github.com/tgstation/tgstation/pull/76095)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/66640614/c786b25a-263e-420e-8af5-527d786a4052)

**Comment by MrMelbert** [comment]
we can totally solve this by making monkeys tall and then using dwarfism

**Comment by IndieanaJones** [comment]
> we can totally solve this by making monkeys tall and then using dwarfism

cursed

**Comment by ChungusGamer666** [comment]
i gotta converte creampies (lol) to bodypart overlays
