### ISSUE TITLE
You can't print things if you have just enough materials

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#76151]
## Reproduction:

Found this after materials rebalance, not sure if this only bs crystals.
![Screenshot_165](https://github.com/tgstation/tgstation/assets/64209864/920027ba-398f-42d2-a958-fed4a9243317)

**Comment by Sealed101** [comment]
do you have a round id? because i can't reproduce this, could be some wack rounding error somewhere

**Comment by ArcaneMusic** [comment]
I'd tend to agree, this could easily be a TGUI rounding error, however with the outstanding errors on how lathes read minerals going on right now it appears to be causing a number of fun issues like this.

**Comment by Livrah** [comment]
> do you have a round id? because i can't reproduce this, could be some wack rounding error somewhere

Оne of these 208425 208428 208432
