### ISSUE TITLE
legion (snow legion in this case) will instantly convert your body if you're asleep/unconscious (not crit or even hurt)

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#76160]
## Reproduction: be in a mech, have it get broken by another icebox mob, be unconscious, nearby snow legion instantly converts your body (instakilling you via MAXIMUM BRUTE DAMAGE?????)
 
![Screenshot_659](https://github.com/tgstation/tgstation/assets/64584757/148566c7-da08-43dd-9be9-5349dac0613b)

**Comment by Momo8289** [comment]
Looking at the code, looks like this is intentional and not actually an issue.

**Comment by Sealed101** [comment]
do be intended doe

https://github.com/tgstation/tgstation/blob/805bc2f5e61548a737f9299edac4f56a3b44245d/code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm#L203-L212
