### ISSUE TITLE
Ion Storm sometimes removes other laws, up to and including purging the AI.

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#76169]
## Round ID:

208577, but I've seen it happen multiple times across the last few months.

## Testmerges:

N/A

## Reproduction:

1) Push the funny meme AI law button
2) A bunch of their existing laws go away

In this specific case, it purged all 3 base Asimov laws and replaced them with an ion one. I have no clue if this is intentional, but I couldn't find a PR that changed this in the last few months and it's not been a thing until relatively recently.

**Comment by JupiterJaeden** [comment]
I feel like I remember this being a thing for a while

**Comment by Ryusenshu** [comment]
yeah its been like this for a long time now
> add ion law
> remove law
> scramble laws
> full purge
One or a combination of them can happen 

BUT
A funny ai law button should not have full ion effects imo
Afterall you could still call a normal ion storm if you want the full effects

**Comment by MrMelbert** [comment]
https://github.com/tgstation/tgstation/blob/fc56699e3a19b7668c8cec8e276cc108dfff5082/code/modules/events/ion_storm.dm#L48-L49

**Comment by TheVekter** [comment]
> https://github.com/tgstation/tgstation/blob/fc56699e3a19b7668c8cec8e276cc108dfff5082/code/modules/events/ion_storm.dm#L48-L49

![image](https://github.com/tgstation/tgstation/assets/7019927/ab50afa2-81c4-4925-90b4-a5ea4de58fab)
