### ISSUE TITLE
Changing species makes you win at burden sect

### ISSUE THREAD

**Issue by JohnFulpWillard** [tgstation/tgstation#76163]
## Reproduction:

1. Be a species (Human for consistency) in the Burden sect.
2. Change species.
3. You will have all your limbs and organs replaced, immediately boosting you to ~14 burden points

https://github.com/tgstation/tgstation/assets/53777086/c414fdc2-69ba-4433-9c55-e04a1465b4af

**Comment by necromanceranne** [comment]
does this also happen if you get hit with mulligan?
