### ISSUE TITLE
Fields created by Shield projectors fly away in hyperspace

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#76172]
Reporting client version: 514.1589

## Round ID:
[208588](https://scrubby.melonmesa.com/round/208588)

## Testmerges:
- [Optimization pass focused on foam code (saves about 30% of cpu usage I think)](https://www.github.com/tgstation/tgstation/pull/76104)
- [Energy Weapon Touch-up: Thermal Pistols Rework, X-01 Multiphase new shot type, DRAGnets are just gone ](https://www.github.com/tgstation/tgstation/pull/76076)
- [Build Mode Preview + better help text](https://www.github.com/tgstation/tgstation/pull/76095)

## Reproduction:
Activate one of those breach field generators that are included with some evac shuttles. Watch as the fields drift away into hyperspace like a bunch of bubbles.

![image](https://github.com/tgstation/tgstation/assets/33107541/53431022-cc7d-4c59-977b-801063edeb35)

**Comment by Helg2** [comment]
Amazing
