### ISSUE TITLE
Players can use Station Bounced Radios in the funny hand room

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#76218]
## Round ID:

208748

## Reproduction:

1) Get sacked while having an SBR in your bag and mic turned on
2) Scream out who sacked you so you can bypass the whole "you don't remember who sacrificed you" thing since that only actually takes effect once you leave the room

I'm pretty sure it's supposed to be radio blocked? There's no concern with regular headsets because it's on a different z-level, but SBRs work regardless of z-level, so...

**Comment by JupiterJaeden** [comment]
So, are you sure that when this happened, anyone on station was actually able to hear you? I do not think that SBRs used off the station z level will reach anyone on the station, but if you have the mic and speaker on you will still get a radio transmission back of yourself talking.

**Comment by TheVekter** [comment]
> So, are you sure that when this happened, anyone on station was actually able to hear you? I do not think that SBRs used off the station z level will reach anyone on the station, but if you have the mic and speaker on you will still get a radio transmission back of yourself talking.

I wasn't the one involved, but it did indeed transmit to the station.

**Comment by BlueMemesauce** [comment]
Do you know exactly when in the log this occurred and who was the one that used the radio?

I reproduced this on a local server, yes they could use the radio in the heretic place and it would say [Common] "bla bla", but you couldn't actually hear it on the station. Vice versa, they couldn't hear any messages from the station in the heretic place either.

**Comment by BlueMemesauce** [comment]
Looks like it was just a coincidence, nobody reacted directly to their message. They just already knew he was a heretic. 
![image](https://github.com/tgstation/tgstation/assets/47338680/a827ef8d-6cf0-4a94-adea-a58297b651da)
![image](https://github.com/tgstation/tgstation/assets/47338680/c9c82cbc-351f-4d55-99a2-96cac98661ba)

**Comment by TheVekter** [comment]
Dope, thanks. Closing.
