### ISSUE TITLE
Everyone is naked, disabled limbs, Unknown, not moving and can't take control of their ghosts.

### ISSUE THREAD

**Issue by Pickle-Coding** [tgstation/tgstation#76226]
## Testmerges:
#75819

## Reproduction:
Start the round. Title happens.

**Comment by Pickle-Coding** [comment]
Also for some reason the naked bodies use old spaceman sprite.

**Comment by MrMelbert** [comment]
Caused by #76179 on servers with roundstart away mission loading

**Comment by newfren** [comment]
LMAO

**Comment by TheVekter** [comment]
Fixed by #76241. I hope.
