### ISSUE TITLE
ectoscopic sniffer cant be activated by custom ghost sprites

### ISSUE THREAD

**Issue by magicbrannch** [tgstation/tgstation#76246]
Reporting client version: 514.1589

## Round ID:
[208845](https://scrubby.melonmesa.com/round/208845)

## Reproduction:

 Be any custom ghost sprite, skeleton etc and click the ectoscopic sniffer, it wont activate but the default ghost sprite will work but custom sprites will not work

**Comment by newfren** [comment]
as skeleton ghost I was able to activate the sniffer on round 208894

**Comment by Sealed101** [comment]
looking at game logs it kinda seems like the roboticist did notice the sniffer beeping/sounding off
![image](https://github.com/tgstation/tgstation/assets/75863639/b022fb07-4d95-4b79-a6f7-f196af83b5ae)

please confirm that you don't get visual and audio feedback when you click on the sniffer as well as not getting the to_chat cooldown message in green text

**Comment by TheVekter** [comment]
I was finally able to track down someone with member to test this, it's working fine. Unable to replicate.
