### ISSUE TITLE
Runtime when creating toolbox from custom material

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#76249]
1. Put iron, glass whatever material in the autolathe
2. Try printing a toolbox from any of this material
3. Get runtime
![Screenshot (264)](https://github.com/tgstation/tgstation/assets/110812394/99fb18f4-2e73-4b69-9f24-c457bb7fe7d9)

Since error is related to tgui I tracked down what tgui code gets called when printing a toolbox and found this
https://github.com/tgstation/tgstation/blob/f030b3b5aa8dcd4e06820d892208127f7325d6c6/code/game/machinery/autolathe.dm#L205-L210

Since error is related to TGUI i tracked down what PR made recent changes to TGUI & found #76215

@LemonInTheDark

**Comment by LemonInTheDark** [comment]
god fucking damn it
