### ISSUE TITLE
You can't craft anything that requires reagents with bottles as containers for it.

### ISSUE THREAD

**Issue by Helg2** [tgstation/tgstation#76250]
## Reproduction:
1. Get everything needed for crafting something with reagent needed for it.
2. Fill `/glass/bottle` with the needed reagent.
3. Don't be able to craft anything.
# Improvised Shotgun Shells
![image](https://github.com/tgstation/tgstation/assets/93882977/e12930d9-8f48-4d63-94d5-911a87718b21)
![image](https://github.com/tgstation/tgstation/assets/93882977/29ad4813-707d-49d8-89fe-1eba5cdd8119)
![image](https://github.com/tgstation/tgstation/assets/93882977/9a784b6b-45f0-4651-8fda-7851aa690300)
![image](https://github.com/tgstation/tgstation/assets/93882977/db75e5ca-643d-494b-a82a-866c60860742)
# Dragonsbreath Shell
![image](https://github.com/tgstation/tgstation/assets/93882977/839ee07a-1835-49ec-973e-33042bb00188)
![image](https://github.com/tgstation/tgstation/assets/93882977/a76b3199-1fe6-42bf-8f7d-23defc1d833d)
![image](https://github.com/tgstation/tgstation/assets/93882977/ae7a8b45-ba09-42fc-972e-bb6861106588)
Works this way exclusively for `/glass/bottle` i think?
With `/glass/drinkingglass/shotglass` as example i could craft what i wanted.
Its not just `weapon ammo` category, couldn't craft IED either.

**Comment by TheVekter** [comment]
I haven't tried this, but it appears to just be bottles - I was able to craft a hot dog last night just fine with ketchup from a beaker.
