### ISSUE TITLE
We have elements that use non-cached lists as arguments.

### ISSUE THREAD

**Issue by Ghommie** [tgstation/tgstation#76279]
## Round ID: N/A
~~is an issue I've been fairly aware of for a couple years now, though I was under the false impression it was being fixed at the time. Just a few minutes ago, I ascertain it's still an issue to this day: GetIdFromArguments gets text refs from lists, rather than generate text strings from its keys and assoc values.
Now, there's no reason why elements shouldn't support lists, and furthermore, at least eleven different elements already use them for args, so this is definitely a problem.~~

IMPORTANT EDIT: I've been informed by ninjanomnom that GetIDFromElements are not intended to generae text strings of keys and values from lists, because it can be quite expensive. Not a bug since the game will work pretty much the same anyway, but still, this is a coding pit-fall contributors and maintainers will keep falling for even if we've it mentioned in the guide. I'll update this soon enough.

## Reproduction:
Spawn two datums of the same type (preferably non-singleton atoms) that make use of a bespoke element with at least one list (neither global or static) as argument. Open the VV menus of both or them and find said element in their signal lookup list. Note how these are two different instance of an element that virtually do the exact same things in the exact same way.

Here's an example: check the refs closely.
![this is your proof](https://github.com/tgstation/tgstation/assets/42542238/f21ef5ef-3209-42e9-bd9b-28dd469aeeac)

**Comment by ninjanomnom** [comment]
When originally implementing the checking the arguments being identical I did some preliminary profiling of implementations where list contents were checked and it's just not worth the performance cost. Elements are flawed in many ways but from the beginning I tried to make sure it'd be performant for even extreme usecases like applying an element to every single projectile fired from a gun. List checks of any kind made that not really viable.

Instead if you want to use list arguments you should be caching and reusing the same list instance yourself. It's not too big a deal if this isn't done on accident occasionally. A unit test could be written to check it doesn't happen at least during init which should catch a good chunk of cases.
