### ISSUE TITLE
AI Vox voice plays alongside the TTS AI voice.

### ISSUE THREAD

**Issue by DATA-xPUNGED** [tgstation/tgstation#76310]
## Reproduction:

* Spawn as AI.
* Make a Vox announcement.
* The regular TTS voice will play alongside the Vox voice, making audio garbage

**Comment by BlueMemesauce** [comment]
https://github.com/tgstation/tgstation/blob/b832e2f47765ea321457221cc4e2a8ea64137555/code/modules/mob/living/silicon/ai/ai_say.dm#L132
Would `radio.talk_into(src, "[message]")` be a good fix for this? I'm unsure since it seemed like it's only used by machines.

**Comment by Sealed101** [comment]
that feature was asked a few times to be made into an ai announcement instead of the ai just radioing the vox, so this is yet another reason why it shouldn't be radio speech
