### ISSUE TITLE
Ingesting liquid plasma fails to remove plasmamen wounds

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#76329]
![obraz](https://github.com/tgstation/tgstation/assets/68878861/8855eb24-c677-4848-8249-208eb8a2664b)
![obraz](https://github.com/tgstation/tgstation/assets/68878861/03d6a256-523c-4f0a-ad4a-5871ecb389e1)

## Round ID:
[209071](https://scrubby.melonmesa.com/round/209071)

## Testmerges:
https://github.com/tgstation/tgstation/pull/75819
This did use to work until recently. Something about liver changes or species nuking?

## Reproduction:
Get a wound. Grind plasma. Drink plasma. Drink more plasma. Despair.

**Comment by ChungusGamer666** [comment]
Interesting, milk was working. I'll look into this.

**Comment by ChungusGamer666** [comment]
I believe this is caused by liver failure as i forgot to give plasmaman livers TRAIT_PLASMA_LOVER_METABOLISM

**Comment by ChungusGamer666** [comment]
> I believe this is caused by liver failure as i forgot to give plasmaman livers TRAIT_PLASMA_LOVER_METABOLISM

it was something else but regardless, plasma livers should give you this trait

**Comment by timothymtorres** [comment]
@Likteer Make sure you are properly [linking to the code](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet) instead of a screenshot.
