### ISSUE TITLE
Silverscale pirates can understand but cannot speak common

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#76330]
## Round ID:

N/A
## Testmerges:

N/A
## Reproduction:

Be a Silverscale pirate and have someone talk to you I guess?

It doesn't make much sense that they can understand anything someone says in common but cannot speak it. I confirmed that the other pirates can either speak and understand common or can do neither.

**Comment by MrMelbert** [comment]
This seems to be because minds have language holders that aren't the same as mob language holders
(Meaning human players have 2 language holders, yes)

And they default to the base language holder type, which grants common understood from the mind - which then inherits the species languages

**Comment by MrMelbert** [comment]
I'm gonna fix the issue but also I'm gonna let Silverscales keep understanding galcom because I think it's funnier that they know it and just refuse to speak it / it's useful for pirates

**Comment by TheVekter** [comment]
> I'm gonna fix the issue but also I'm gonna let Silverscales keep understanding galcom because I think it's funnier that they know it and just refuse to speak it / it's useful for pirates

I'm fine with that, but it should be indicated somewhere somehow or it's just going to be very, very confusing as to why they don't speak it.
