### ISSUE TITLE
Many traits are not in _globalvars/traits

### ISSUE THREAD

**Issue by ChungusGamer666** [tgstation/tgstation#76349]
An inumerable amount of traits is not put in the proper lists in traits.dm.
This is bad for debugging and for admin fuckery.

An unit test for this could be incredibly helpful, but honestly I don't know exactly how I'd write one myself.

Examples include but are not limited to:
TRAIT_NOFEAR_HOLDUPS
TRAIT_HATED_BY_DOGS
TRAIT_BLIND_TOOL
TRAIT_SNEAK
TRAIT_SPIDER_CONSUMED

**Comment by necromanceranne** [comment]
Throw hammers at people who forget about the globalvars lists. Either they remember for the future, or they get much better at dodging hammers.
