### ISSUE TITLE
Slurring effect from having no tongue happens immediately after death

### ISSUE THREAD

**Issue by zoomachina** [tgstation/tgstation#76355]
Client version: 514.1589

## Testmerges:
[#75819: 'A small pile of borg combat changes' by Kubisopplay at commit ae43cf232a](https://www.github.com/tgstation/tgstation/pull/75819)

## Reproduction:
In this round, cult clown died, then got revived very fast, via revival rune. Despite that, he was still slurring, as if he had no tongue (I believe his tongue was perfectly healthy).
I think this issue happened to other people in other rounds as well, but I do not have round ids.

**Comment by ChungusGamer666** [comment]
the check for organ failure on the tongue organ is inverted (my bad) and somehow this went through unit tests and local testing without being caught
very very bad

**Comment by ChungusGamer666** [comment]
https://github.com/tgstation/tgstation/blob/e939fbb8c4af97f2adbf9fbac35b5ac2218b8029/code/modules/surgery/organs/internal/tongue/_tongue.dm#L157C1-L160C66

God fucking damn it

**Comment by ChungusGamer666** [comment]
@TheVekter not an oversight, straight up a bug

**Comment by TheVekter** [comment]
> @TheVekter not an oversight, straight up a bug

It's an oversight because you didn't catch the bug before it happened. /j
