### ISSUE TITLE
Captain's sabre's bane effect does not work.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#76368]
## Reproduction:

Step 1: Brandish your sword.

Step 2: Slice open an assistant that has invaded your personal space.

Step 3: Be sad, as the damage inflicted is substantially less than what it should be.

Apparently this worked when initially merged but broke literally within the week. Bane, like normal bane effects, are still working. Only this special bane is not working.

I have tested this.
![tested on live build bane no workies](https://github.com/tgstation/tgstation/assets/40847847/f679fcdd-18cd-4d40-a08c-8885b8732c3f)

**Comment by Likteer** [comment]
I really love the chungus coder fella, but this again, seems likely related to the species nuking/liver changes.

**Comment by necromanceranne** [comment]
I have my doubts. The liver stuff still works fine for maint drugs.

**Comment by ChungusGamer666** [comment]
> I really love the chungus coder fella, but this again, seems likely related to the species nuking/liver changes.

I would love to say this is my fault, but it is most likely not as liver traits are apparently working in every other way.

**Comment by MrMelbert** [comment]
all new banes being added must be unit tested starting now

**Comment by ChungusGamer666** [comment]
Melbeet try not to talk about unit tests challenge (IMPOSSIBLE)

**Comment by MrMelbert** [comment]
user above me loves breaking the game

**Comment by TheVekter** [comment]
It looks like banes might entirely be broken right now as I changed the sabre to do zero force damage but an additional 30 against corgis only and it still did nothing.

**Comment by necromanceranne** [comment]
Nah, the sabre has a special cancel condition. Other banes should work. Sabre checks for TRAIT_MAINTENANCE_METABOLSIM on the liver but is functionally a humanoid bane

**Comment by TheVekter** [comment]
> Nah, the sabre has a special cancel condition. Other banes should work. Sabre checks for TRAIT_MAINTENANCE_METABOLSIM on the liver but is functionally a humanoid bane

Right, but I tried commenting out the unique parts of it so it's identical to other banes and it's not applying the bonus damage as it should be.

**Comment by san7890** [comment]
were you in combat mode? this bane will only work in combat mode. I tested it with a character in combat mode and it worked flawlessly. this is a bit weird so i would like to see a UX improvement to either clarify this feature or strike it entirely, but this issue is being closed as it does indeed work.

**Comment by TheVekter** [comment]
Oh hey, so I'm just an idiot who can't read code
