### ISSUE TITLE
Spawn Debug Full Crew doesn't work

### ISSUE THREAD

**Issue by cnleth** [tgstation/tgstation#76372]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Launch a local server, press "Spawn Debug Full Crew" in the debug tab, it fails to spawn any crewmembers and produces a runtime error for every crewmember it attempted to spawn:
```
Runtime in job.dm, line 1111: Cannot read null.prefs
proc name: check job eligibility (/datum/controller/subsystem/job/proc/check_job_eligibility)
usr: Guest-1876322787/(Franklin Harshman)
usr.loc: (Fore Central Primary Hallway (169,141,2))
src: Jobs (/datum/controller/subsystem/job)
call stack:
Jobs (/datum/controller/subsystem/job): check job eligibility(the new player (/mob/dead/new_player), /datum/job/assistant (/datum/job/assistant), "AR", 1)
Jobs (/datum/controller/subsystem/job): AssignRole(the new player (/mob/dead/new_player), /datum/job/assistant (/datum/job/assistant), 0, 1)
Guest-1876322787 (/client): Spawn Debug Full Crew()
```

**Comment by MrMelbert** [comment]
https://github.com/tgstation/tgstation/blob/e929cf39cded5207d63df1fa8521f41f2816b383/code/controllers/subsystem/job.dm#L1110-L1113

this check changed `AssignRole` from client-less save to client requires, should be using the mob's age directly if it's set by this point isntead
