### ISSUE TITLE
Ashy plating decals (and possibly some others) phase through the Mining shuttle and reappear ON the shuttle after it departs for the station

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#76382]
## Testmerges: 
- #76129
- #75819

## Reproduction:
So you know the Lavaland Landing pad area, right? It's covered in ashy decals for decoration. Previously, they would stick to the pad no matter how many times the Mining shuttle arrived or departed. Something recent (my guess would be either #76130 or #75189) has caused that to change, and they now behave wacky:
1. Shuttle arrives on lavaland
2. The decals appear on the shuttle floor, reattaching to it
3. Shuttle departs for the station
4. The decals move with it

From local testing, it appears that they reattach to the shuttle floor due to the shuttle being rotated, but I might be mislead.

https://github.com/tgstation/tgstation/assets/75863639/ff1f26fa-a43e-404c-9587-ea5c2566e7d2

(my potato laptop was struggling for some reason when I launched the shuttle back to the station dock, so here's screenshots instead)

![изображение](https://github.com/tgstation/tgstation/assets/75863639/0c2c7e7c-ede6-4df1-84a9-bb859eaa932c) ![изображение](https://github.com/tgstation/tgstation/assets/75863639/aba0dc08-876c-4985-bdfd-652bf30cba0e)

**Comment by JohnFulpWillard** [comment]
Likely caused by https://github.com/tgstation/tgstation/pull/75769
