### ISSUE TITLE
Virologist in default job outfit can tank 8 xeno neurotoxin spits before going into stamcrit

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#76389]
Reporting client version: 514.1589

## Round ID:
[209250](https://scrubby.melonmesa.com/round/209250)

## Testmerges:
- [A small pile of borg combat changes](https://www.github.com/tgstation/tgstation/pull/75819)
- [TTS Improvements: Improved Audio Quality, Pitch Adjustment, Preference Silicon Voices, Per-Character Voice Disable Toggle, Tongue Voice Filters, Reworked Silicon and Vending Machine Filters](https://www.github.com/tgstation/tgstation/pull/76129)

## Reproduction:
Xenos can't even spit that much with full plasma storage. I assume that's not intentional, and has something to do with their clothing's armor values. A single labcoat allows you to tank 2 additional hits, which is already too much.

**Comment by MrMelbert** [comment]
Should probably have a smidge of armor piercing on them
