### ISSUE TITLE
Mute not being able to laugh

### ISSUE THREAD

**Issue by Generubi** [tgstation/tgstation#76394]
## Reproduction:

 When you try to laugh when having the mute trait using the *laugh interaction, you are unable to. Mimes on the other part when using *laugh gets rephrased into a "laughs silently", while mutes cannot laugh at all, not even silently. I think that it is an oversight.

**Comment by MrMelbert** [comment]
I don't think this is an oversight. 

`*laugh` requires you be able to speak but allows mimes specifically as an exception.
If you are otherwise mute, you can't laugh.

**Comment by Generubi** [comment]
the petition is to redirect the *laugh interaction to *laughs silently

**Comment by MrMelbert** [comment]
I would disagree with that but regardless - not an issue, so shouldn't be on the tracker
