### ISSUE TITLE
Buttons for Coat Hoods, Flashlights, Internals, etc. Not Appearing

### ISSUE THREAD

**Issue by PrismaticLoop** [tgstation/tgstation#76405]
Reporting client version: 514.1589

## Round ID:
[209296](https://scrubby.melonmesa.com/round/209296)

## Reproduction:
Top-left icons for buttons not appearing when wearing apparel that can change (i.e. coat/cloak hoods/welding masks/goggles), toggleable objects (i.e. flashlights/RPED and bag gathering modes) and most importantly, INTERNALS. Tried restarting, resetting the buttons

**Comment by SyncIt21** [comment]
Duplicate of #75578

**Comment by Sealed101** [comment]
this is recent and it seems to have been reported to be an issue for multiple people, there may be something else at play here

**Comment by SapphoQueer** [comment]
Don't think it's a duplicate, been happening server-wide, atleast for manuel, for the past couple of shifts.

**Comment by Rex9001** [comment]
This has been happening to everyone multiple shifts in a row on Terry.

**Comment by TheVekter** [comment]
We've got another one lads
