### ISSUE TITLE
Mining points not getting redeemed ORM?

### ISSUE THREAD

**Issue by PVT-LF** [tgstation/tgstation#76409]
## Reproduction:
Just gameplay
I initially thought it had something to do with having an Intern Shaft Miner ID, as interns didn't seem to be getting points either. Also conscripted miners (ie not assigned miner occupation at roundstart) did not get mining points and I assumed this was normal behaviour.

EDIT: I usually click the ORM, open the interface, see that my ID is there (it has never been wrong), then open my mining ore bag and insert ores by hand (one by one, each type). Then I would click claim points but in this case I have none, and pressing it does not result in points. This did not usually have issues on fulp so I'm just writing it up in case others have a similar issue.

**Comment by TheVekter** [comment]
I need you to go over the exact steps you took. The ORM's interface is kind of weird if you haven't used it before so I want to make sure you didn't just do the wrong thing and not get your points.

**Comment by SyncIt21** [comment]
Apparently only if you drop the Ore on the floor[by clicking on the mining satchel] near the ORM do you get points, not when inserting by hand, Seems like an oversight.

**Comment by PVT-LF** [comment]
> Apparently only if you drop the Ore on the floor[by clicking on the mining satchel] near the ORM do you get points, not when inserting by hand, Seems like an oversight.

Yeah this seems to be the issue after doing a quick test
