### ISSUE TITLE
Lone firstnames, or anything after it get eaten by the VTMB config event

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#76412]
![obraz](https://github.com/tgstation/tgstation/assets/68878861/18560c3e-6851-4689-9f4f-c1603dd09a3a)

There is a bizarre VTMB-themed config event on june 29th.
It converts lastnames into Vampire clan names, randomly rolled for each department.
(as far as I know, there is no holiday or anniversary, maybe vampires are gay as hell & tis' the season)

It takes no hostages.

## Round ID:

209257 
for instance

## Testmerges:
#75819 

## Reproduction:
Pick or roll a default name, that lacks spaces, or gets more than 1.
Join the game on june 29th.

- If the name is 1 word **(some default clown & mime names)**, your whole name will be a [vampire clan].
_Example: Silencio -->Von Sport_
- f the name is divided by "-" instead of spaces **(lizard names)**, your whole name will ALSO be a [vampire clan].
_Example: Only-He-Stands-There -->Tremere; 
Gulum-Ei --> La Croix_

- If the name is longer than 2 words - the 1st word is treated as the firstname, and every other word is converted to the [vampire clan].
_Example: Austin 'Danger' Powers --> Austin Hecata;
Lt. Jonh Smith --> Lt. Toreador_

Who even coded this.

**Comment by TheVekter** [comment]
Actually it's not Armhulen's fault it's @ChungusGamer666's.

![image](https://github.com/tgstation/tgstation/assets/7019927/73732e52-494c-4f57-a90d-43b7808c0964)

Melbert says he's testing a fix now.
