### ISSUE TITLE
Beard changing colors/unable to save color preset.

### ISSUE THREAD

**Issue by Payuut** [tgstation/tgstation#76422]
Upon joining a game my beard had a random color from what i had it saved to in my preferences, after that i was unable to change the color of my beard in the menu. when the round began i had a random beard color. After that round i joined another round on a different TG server, and was confronted with the same issue. I proceeded to ahelp it and got told to make this report.

**Comment by ChungusGamer666** [comment]
Very interesting. I probably caused this in one of my head flags PRs, I'll take a look into it.

**Comment by wulfenbach-jpg** [comment]
Using temporary DNA features enzymes from the genetics console scanned from another mob does not give you the correct hair color, instead giving a random one. Moreover, upon the wearing off of the DNA injector, you retain the random hair color you're given, which is neither yours nor the person who was scanned. I believe this may be related to this issue, as both beards and hairs are kinds of hair colors.

**Comment by MrMelbert** [comment]
@ChungusGamer666 

Every time I ctrl+shift+click a new body of myself I get a random haircolor, how did you manage this 

![image](https://github.com/tgstation/tgstation/assets/51863163/e96ccbef-acff-411c-b7be-8ce67f0b02df)

![image](https://github.com/tgstation/tgstation/assets/51863163/79fee5d8-a0c0-4b64-a8f0-daf6da937f88)

**Comment by ChungusGamer666** [comment]
@MrMelbert This did not happen when I was testing it. I have no fucking clue.

**Comment by ChungusGamer666** [comment]
I will fix this as soon as possible.
Sorry for the goof, fellas.

**Comment by AlamoTurtle** [comment]
gradients are completely botched in general as well :)

**Comment by ChungusGamer666** [comment]
I *think* I figured out the issue. Working on a fix.

**Comment by Cutplays** [comment]
this is happing to me as well
