### ISSUE TITLE
You can zip duffelbags not on your person but you cannot unzip them

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#76430]
## Reproduction:

- Go to open up the surgical dufflebag on the table next to you to commit surgery
- It's zipped.
- Try to unzip it
- It says it's locked.
- Have to pick it up to unzip it, then place it back down

**Comment by TheVekter** [comment]
I _think_ this is intentional? @LemonInTheDark

**Comment by LemonInTheDark** [comment]
not really man, not really
