### ISSUE TITLE
TK and new duffel -  Telekinesis teleports bag to hand through walls

### ISSUE THREAD

**Issue by PVT-LF** [tgstation/tgstation#76441]
![Screenshot (232)](https://github.com/tgstation/tgstation/assets/63499294/2eabf968-e731-4401-8d52-bf87343063d0)

## Reproduction:
Telekinesis teleports a duffel bag directly to your hand with the new duffel bag PR.

As seen, I managed to teleport the drone duffel bag on display into my hand through a wall. It could also be the unzip feature? As you are capable of unzipping the bag while it is in your TK hand, which then teleports it to you. Will test after the round ends

EDIT: using the duffel in your TK hand to zip/unzip appears to teleport it directly to you. Seems like an unintended interaction as TK should not be teleporting items through physical barriers like walls.

![Screenshot (233)](https://github.com/tgstation/tgstation/assets/63499294/a30779b6-1037-42e8-a910-6751e8d597f1)
![Screenshot (234)](https://github.com/tgstation/tgstation/assets/63499294/fa6e33eb-4ba0-4466-aaaa-833744c1aa06)
![Screenshot (235)](https://github.com/tgstation/tgstation/assets/63499294/8b7df477-6026-40d2-9f80-601ed4cacc96)

#76313 
@wulfenbach-jpg
@LemonInTheDark 

Maybe this is the real buff duffels need? 😄

**Comment by LemonInTheDark** [comment]
Oh my god I hate TK so much
