### ISSUE TITLE
gradient hairs dont work

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#76451]
## Round ID:
[209385](https://scrubby.melonmesa.com/round/209385)
and rounds before it i dont know when it started

## Testmerges:
[#76408: 'reverts Makes hoods into a component #75977' by Time-Green at commit 6b41c93898](https://www.github.com/tgstation/tgstation/pull/76408)

## Reproduction:

try using hairs with a color gradient and see they dont show up

**Comment by TheVekter** [comment]
Duplicate of #76422
