### ISSUE TITLE
Urinal cakes can decay into moldy messes like food.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#76465]
Reporting client version: 514.1589

## Round ID:
[209408](https://scrubby.melonmesa.com/round/209408)

## Reproduction:
I mean I know it's edible, but I don't think it should just disintegrate like food.
![image](https://github.com/tgstation/tgstation/assets/33107541/1ec3be22-fa2a-4724-8d7d-c40a98caed82)

**Comment by SyncIt21** [comment]
@MTandi unintended side effect of #76018?

**Comment by MTandi** [comment]
Decomposition logic should stay unaffected by my changes, so all reports about chocolate bars and other things decomposing are unrelated and it was there before my PR.

In fact, my changes only protected some additional food types from decomposition: Canned (regardless of being open or not), bowled and packaged food should now not decompose (this includes things that leave seed after eating, like bungo fruit and gatfruit but whatever)

![image](https://github.com/tgstation/tgstation/assets/3625094/b736f7e3-fbd2-4706-887d-4507b93fb84c)

If someone thinks that urinal cake should be protected, then it should have the `preserved_food` flag.
