### ISSUE TITLE
Tramstation: Random maint template intersecting with lower science.

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#76466]
Reporting client version: 514.1589

## Round ID:
[209426](https://scrubby.melonmesa.com/round/209426)

## Reproduction:
No idea which specific template this is, sorry.

Upper floor:
![dreamseeker_mq6Ff97uEu](https://github.com/tgstation/tgstation/assets/33107541/79b8bade-894a-417e-954e-591142b551d0)

Lower floor:
![dreamseeker_yeFfLadNI0](https://github.com/tgstation/tgstation/assets/33107541/817f48ac-444d-4c17-b029-95853d21ed97)

**Comment by TheVekter** [comment]
It keeps happening

**Comment by TheVekter** [comment]
This is fixed by #76424
