### ISSUE TITLE
Interdyne pirates sleeper surgery disk has a SPELLING ERROR

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#76463]
Any round
![image](https://github.com/tgstation/tgstation/assets/105343481/231433b4-0c39-4516-be3c-581c0d27d575)

literally unplayable, etc.

**Comment by ChungusGamer666** [comment]
Oh god the HORROR

**Comment by SethLafuente** [comment]
Noooo the humanity D:
