### ISSUE TITLE
Alien queens can acid through reinforced walls

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#76473]
## Reproduction:

Be an alien queen

Acid a wall

Wall disappears after a bit

This is obviously not great, since aliens can't be contained anymore in xenobiology.

**Comment by moocowswag** [comment]
you can also acid away the reinforced floor to make a breach to space but you cant go down through it :(

but it atleast prevents the crew from killing the xenos with gas

**Comment by Time-Green** [comment]
> you can also acid away the reinforced floor to make a breach to space but you cant go down through it :(
> 
> but it atleast prevents the crew from killing the xenos with gas

That’s been like that for a while. The r-wall thing is new, either the recent alien rework or the acid changes

**Comment by IndieanaJones** [comment]
I didn't touch the xeno acid mechanics, so it was likely the acid changes.
