### ISSUE TITLE
cosmic vomiting is now in the generatable symptom pool alongside normal vomiting

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#76488]
you didn't override the symptom level when you made your subtype dummy

**Comment by TheVekter** [comment]
It's not a symptom level thing, there's a var that when set false will disable it from the normal symptom pool. I'll fix it real quick.

**Comment by ATH1909** [comment]
> It's not a symptom level thing, there's a var that when set false will disable it from the normal symptom pool. I'll fix it real quick.

ah okay, my bad

I was the dummy all along
