### ISSUE TITLE
Pun pun has oversized clothes.

### ISSUE THREAD

**Issue by Helg2** [tgstation/tgstation#76481]
![image](https://github.com/tgstation/tgstation/assets/93882977/b09e19f2-e005-4c2f-b023-14f99f7ca94e)
Poor Pun Pun looks like hobo now.

**Comment by TheVekter** [comment]
Feature.

**Comment by JohnFulpWillard** [comment]
@ChungusGamer666

**Comment by ChungusGamer666** [comment]
I will try to figure this out but it's WACK

**Comment by ChungusGamer666** [comment]
![image](https://github.com/tgstation/tgstation/assets/82850673/f3da3882-45b9-4a82-8eb0-54d4e67fa4c0)
for some reason, bodytypes are NOT being synchronized properly by monkeys?
