### ISSUE TITLE
if you try to shoot the sanity face it will click endlessly

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#76495]
Reporting client version: 514.1589

## Round ID:
[209501](https://scrubby.melonmesa.com/round/209501)

## Reproduction:
build the laser musket
mouse over the happiness meter
click and the gun makes a click noise
shoot the musket somewhere so it's unloaded
click the happiness meter again
click noise

**Comment by TheVekter** [comment]
@Cheshify

**Comment by Cheshify** [comment]
Do we know if this is unique to muskets or all guns? I haven't changed anything with how the weapon fires, all the code just makes it charge up.

**Comment by MrMelbert** [comment]
Likely related to #63493 .

**Comment by newfren** [comment]
I didn't try it with other guns, apologies. I do know that the click is audible to other people.

**Comment by TheVekter** [comment]
> Do we know if this is unique to muskets or all guns? I haven't changed anything with how the weapon fires, all the code just makes it charge up.

This is reproducible with all guns.

**Comment by TheVekter** [comment]
@newfren Edit the subject for me please, this is affecting all guns, not just the musket.

**Comment by newfren** [comment]
👍
