### ISSUE TITLE
Abductors cannot probe abductees and can't get points

### ISSUE THREAD

**Issue by Time-Green** [tgstation/tgstation#76504]
## Reproduction:

Put an abductee in the experimentation machine and press one of the colorful buttons 
![image](https://github.com/tgstation/tgstation/assets/7501474/acf1345a-3981-42ea-b56a-8f9acf846aa1)

It just does nothing. I couldn't find a runtime, nor did it work when I manually called the experiment() proc with all the right params. There's absolutely no feedback 

https://github.com/tgstation/tgstation/blob/9d2af976549c496ecc1d2b402a50ed16e747f992/code/modules/antagonists/abductor/machinery/experiment.dm#L119C1-L125C1

Tried it on the other ships aswell, absolutely nothing

**Comment by TheVekter** [comment]
@Rhials This might be due to #76101, can you take a look please?

**Comment by Time-Green** [comment]
> @Rhials This might be due to #76101, can you take a look please?

Good call, I'll check. This is a pretty major antag mechanic to break

**Comment by Time-Green** [comment]
> @Rhials This might be due to #76101, can you take a look please?

I've found it already, I'm dumb for not seeing it instantly
