### ISSUE TITLE
Examined tongues display numbers, instead of its liked tastes.

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#76536]
Reporting client version: 514.1589

## Round ID:
[209600](https://scrubby.melonmesa.com/round/209600)

## Testmerges:
N/A

## Reproduction:
![Screenshot 2023-07-03 223409](https://github.com/tgstation/tgstation/assets/85206687/eb33a223-51b0-4112-b39a-4ca3e10a34f3)
Examine a tongue.

**Comment by ChungusGamer666** [comment]
oops
