### ISSUE TITLE
Monkeys do NOT have tails.

### ISSUE THREAD

**Issue by MrrFiish** [tgstation/tgstation#76539]
## Round ID: 
Any but tested in 209608 and the next two.

## Testmerges:
None from what I can see

## Reproduction:
No matter what, monkeys have no tail and this sucks for heretics and such.
1. Gib a monkey
2. No tail will drop no matter what you do

1. Do feature manipulation on a monkey's groin.
2. There are no removable organs.

**Comment by TheVekter** [comment]
@ChungusGamer666 SIGH

**Comment by ChungusGamer666** [comment]
@TheVekter I have not touched monkey organs in any PR except #76381 which hasn't even been testmerged
I find it highly unlikely that I fucked something up here

**Comment by IndieanaJones** [comment]
Chungus is right, it's been like this for a long time now. Monkey tails aren't even tied to the tail organ itself, it's tied to the monkey body. I'm not sure how to consistently get a monkey tail myself.
