### ISSUE TITLE
Invisible N2O knocking people out

### ISSUE THREAD

**Issue by Cheshify** [tgstation/tgstation#76559]
## Round ID:
[209637](https://scrubby.melonmesa.com/round/209637)

## Reproduction:
<img width="200" alt="gas2" src="https://github.com/tgstation/tgstation/assets/73589390/109f6e7e-1e75-4a8e-bc00-ec56cf3e4cee">

<img width="432" alt="gas1" src="https://github.com/tgstation/tgstation/assets/73589390/a51f102f-194d-4d22-948e-edd8bd7c2f45">

N2O in the air at the specified amount is not visible, and it also makes you sleep. This probably shouldn't be happening unless you can actually see it?

**Comment by TheVekter** [comment]
Chesh says this was on Z2 of Northstar but it's similar enough to #75709 that I think we can just assume it's happening on any z-level, not just the lowest one. I'm closing this as a duplicate.
