### ISSUE TITLE
blood rites unteaches itself if your blood charges happen to drop to zero and that's annoying

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#76562]
the point of the spell is that you can charge it up by absorbing blood, then spend that blood on various effects

but if any of those effects happen to reduce your blood charge level to exactly zero (or below), the spell unteaches itself (as a stun hand or the like would) and you have to relearn it

**Comment by Helg2** [comment]
Wait so it wasnt intended?

**Comment by ATH1909** [comment]
> Wait so it wasnt intended?

it might be, but if it is, it's a really annoying design
