### ISSUE TITLE
blood barrage has no sprite

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#76561]
bababooey

**Comment by TheVekter** [comment]
Can you get us a screenshot?

I'm kidding.

**Comment by Sealed101** [comment]
- broken in #76325

 as it has overridden the basic `icons/obj/weapons/guns/ballistic.dmi` which has the arcane barrage icon. currently it reads the `icons/obj/weapons/guns/mosinnagant.dmi`
why are arcane barrages not a `gun/magic` at least lmao

### relevant code

https://github.com/tgstation/tgstation/blob/95298fb99d3d55a555667e4c9def3112ac2593a8/code/modules/projectiles/guns/ballistic/rifle.dm#L1-L22

https://github.com/tgstation/tgstation/blob/95298fb99d3d55a555667e4c9def3112ac2593a8/code/modules/projectiles/guns/ballistic/rifle.dm#L214-L226

https://github.com/tgstation/tgstation/blob/95298fb99d3d55a555667e4c9def3112ac2593a8/code/modules/antagonists/cult/cult_items.dm#L790-L819
