### ISSUE TITLE
blood barrage bolts don't seem to heal fellow cultists?

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#76560]
they're supposed to give them a dose of unholy water instead of damaging them

but, uh, it seems that I accidentally executed a fellow cultist by firing a few of them into him

**Comment by necromanceranne** [comment]
The problem is that the entirety of the relevant code is the /Bump proc, and not in the /on_hit proc. So guess what. You still shoot the fucker if you hit them with blood barrage.
