### ISSUE TITLE
Lizards can catch viruses from eating maint rats 

### ISSUE THREAD

**Issue by LikesGreen** [tgstation/tgstation#76573]
## Reproduction:

1. Be lizard
2. Try to eat maint rats/mouse
3. Realized you are infected 

I don't recall this being a problem some weeks ago, I know we got new change related to food but eating safely rats/mouses from floor was kinda lizard thing due to their animal like nature. 

Not sure if it's oversight due to the fact that it wasn't a thing before or it's intended.

**Comment by Jacquerel** [comment]
We could make dead rats ignore the five second rule but frankly it makes sense to give them a rinse I'm the sink if you don't want to risk being ill.

**Comment by Sealed101** [comment]
this feels like an emergent feature

**Comment by TheVekter** [comment]
@MTandi Intended?

**Comment by MTandi** [comment]
Intended. Wash it with extinguisher or something before eating.

**Comment by Sealed101** [comment]
^
