### ISSUE TITLE
Ambush spiders can aggro-grab hulks

### ISSUE THREAD

**Issue by cnleth** [tgstation/tgstation#76584]
## Round ID:
[209686](https://scrubby.melonmesa.com/round/209686)

## Testmerges:
#75819

## Reproduction:
A player complained in dchat about being aggro-grabbed by an ambush spider as a hulk, I tried reproducing this on a local server and it actually worked:
1. Find a hulk while being an ambush spider
2. Grab them
3. They are instantly aggro-grabbed despite hulks normally not being aggro-grabbable and can even fail to break free from your grab

**Comment by IndieanaJones** [comment]
The hulk fears the ambush spider

**Comment by cnleth** [comment]
Fixed by #76591
