### ISSUE TITLE
Perfectly intact organs seem to be incapable of being transplanted

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#76615]
Reporting client version: 514.1589

## Round ID:
[209761](https://scrubby.melonmesa.com/round/209761)

## Testmerges:
- [Ports cluwnes](https://www.github.com/tgstation/tgstation/pull/76564)
- [SPECIES NUKING 2023: TOTAL EXTERNAL ORGAN DEATH](https://www.github.com/tgstation/tgstation/pull/76381)

## Reproduction:
![Screenshot 2023-07-06 183349](https://github.com/tgstation/tgstation/assets/85206687/96eb21ba-028a-402f-8a88-932acf3c45e2)
Freshly printed, unused. Attempted to be transplanted into a person, but didn't work.
I tried with an organic liver, but it too said it was destroyed and didn't work. I checked it to see if it was munched, but it was not, only being slightly discoloured.
1. Acquire/Make a subject in need of an organ transplant.
2. Remove that unwanted organ.
3. Acquire replacement organ.
4. Attempt to insert.
5. Organ is destroyed and cannot be transplanted?

**Comment by TheVekter** [comment]
Let me test this on Manny; I bet it's #76381.

**Comment by TheVekter** [comment]
YUP

@ChungusGamer666 This one actually probably is you, I can't replicate it on Manuel and it's not TMed there.

**Comment by ChungusGamer666** [comment]
ah hell nah, alright ill deal with this

**Comment by ChungusGamer666** [comment]
on one hand surprised that this is the only bug so far
on the other hand i am surprised its this out of all things thatd bug out

**Comment by ChungusGamer666** [comment]
This has been fixed 👍

**Comment by TheVekter** [comment]
> This has been fixed 👍

I'll have a key holder test merge it again; if we can confirm it's not happening on live I'll close this out.
