### ISSUE TITLE
Rod of Ascelpius resets MuleBots('s speed)

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#76614]
Reporting client version: 514.1589

## Round ID:
[209749](https://scrubby.melonmesa.com/round/209749)

## Reproduction:

Be a pAI, driving a MuleBot
Have your circuits fiddled with, so you go fast! Lovely, going places won't take fore-
Enter the radius of a doctor's healing effect.
Watch your speed revert to normal instantly.

It Might be more than just the speed that's affected, but it was weird to experience firsthand, literally had who was on top of me try to fix this constantly (busy shift, doctor out on halls a lot)

**Comment by TheVekter** [comment]
How the fuck does that happen

**Comment by MrMelbert** [comment]
Asclepius heals the MULEbot which in turns calls updatehealth which in turn calls update stamina which in turn resets speed back to initial speed

```dm
	mule.set_varspeed(FAST_MOTOR_SPEED)
```

```dm
/mob/living/simple_animal/update_stamina()
	set_varspeed(initial(speed) + (staminaloss * 0.06))
```

**Comment by Kapu1178** [comment]
LOL.
