### ISSUE TITLE
Asterisks don't display before emote text

### ISSUE THREAD

**Issue by cnleth** [tgstation/tgstation#76626]
## Round ID:
[209809](https://scrubby.melonmesa.com/round/209809)

## Testmerges:
https://github.com/tgstation/tgstation/pull/75819

## Reproduction:
Use a custom emote or be forced to emote by external things, the asterisk symbol before the emote in runechat doesn't show up
![asterisk](https://github.com/tgstation/tgstation/assets/113535457/42e70ccc-51de-422f-b7c7-98e83cc8e065)

**Comment by TheVekter** [comment]
Able to reproduce on current version.

**Comment by cnleth** [comment]
Could be related to https://github.com/tgstation/tgstation/pull/76552, although the screenshots in that PR have the asterisk, so I'm not sure

**Comment by orthography** [comment]
Deathgasp still has the asterisk.

**Comment by cnleth** [comment]
Fixed by #76696
