### ISSUE TITLE
Morgues can "hold" ghosts

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#76632]
## Reproduction:
 
![image](https://github.com/tgstation/tgstation/assets/76874615/e0d5eea4-e058-4ca3-be21-7bc56528beee)
Have a ghost on the morgue tray, watch confused mortician wonder why this morgue gives off the "has stuff in it" light
no matter how many times the morgue gets toggled, the ghost always follows the tray
(the blood is from the tray right under it's not me missing a whole corpse)

**Comment by TheVekter** [comment]
I'm pretty sure this bug has been around longer than I have.

I can't find another issue for it, though, so it'll stay.

**Comment by AdipemDragon** [comment]
the wonders of having someone actually hang around the morgue to see it happen

**Comment by ChungusGamer666** [comment]
feature
