### ISSUE TITLE
Holy Arrows without a sprite or not working as intended

### ISSUE THREAD

**Issue by KingMapache** [tgstation/tgstation#76636]
Reporting client version: 514.1589

## Round ID:
[209824](https://scrubby.melonmesa.com/round/209824)

The Holy Arrows for chap doesn't have sprite
And you can't make more? or its maybe intentional but im not sure

![image](https://github.com/tgstation/tgstation/assets/86317189/62fe185e-1f64-4f28-98cd-5ad6f7327423)

**Comment by Helg2** [comment]
https://github.com/tgstation/tgstation/blob/06adfd9d03312ea08edd30433b946c05392ef490/code/modules/projectiles/ammunition/_ammunition.dm#L87-L89
Because of this part all arrows spawn with -live suffix on icon_state. Somehow worked fine before.
