### ISSUE TITLE
As nukies, can't buy ammo if you bought it at a discount before

### ISSUE THREAD

**Issue by zoomachina** [tgstation/tgstation#76651]
## Reproduction:
- As a nukie, buy any ammo that is on a limited discount. 
- Can't buy the ammo at a discount anymore, can't buy ammo normally - pain everywhere.
- May be relevant for other consumables, like stimpacks or explosives.

**Comment by SyncIt21** [comment]
I could be wrong but
#28286
#73560
Are all giving similar vibes?

**Comment by zoomachina** [comment]
> I could be wrong but #28286 #73560 Are all giving similar vibes?

I don't think first is related, I guess the second one is the same bug, only applied to nukies

**Comment by zoomachina** [comment]
Fuck

**Comment by zoomachina** [comment]
It is a duplicate of #73560 true

**Comment by zoomachina** [comment]
Fuck

**Comment by zoomachina** [comment]
I

**Comment by zoomachina** [comment]
Ok hopefully it's right now
