### ISSUE TITLE
Ling trauma purge doesn't get rid of Ethereal brain trauma.

### ISSUE THREAD

**Issue by B00tz** [tgstation/tgstation#76664]
## Testmerges:
[#76564: 'Ports cluwnes' by jlsnow301 at commit f56e1ba37d](https://www.github.com/tgstation/tgstation/pull/76564)

## Reproduction:
Be Ethereal.
Get cut once and bleed out because medical is shit and doesn't know what to do when someone is dying of blood loss.
Get crystal regen'd 
Use the Anatomic Panacea ability to attempt to get rid of the newly acquired trauma 
Notice how it does not do that.

**Comment by MrMelbert** [comment]
Anatomic panacea cures traumas of `TRAUMA_RESILIENCE_LOBOTOMY` level, while ethereal traumas are `TRAUMA_RESILIENCE_ABSOLUTE`. 
You however might be able to cure the trauma by cutting off your head and regenerating a new brain. Think smarter not harder.
