### ISSUE TITLE
Pluoxium atmosphere kills station pets

### ISSUE THREAD

**Issue by YehnBeep** [tgstation/tgstation#76661]
## Reproduction:

1. Scrub (using a portable scrubber for example) all oxygen out of a room.
2. Replace with at least 3 kPa of pluoxium (though in my test I went with 9 kPa, 3 times what should be the required amount)
3. Move a pet into the room. Note that their health starts taking damage and they will die.

**Comment by Jacquerel** [comment]
`/datum/element/atmos_requirements` only checks for "oxygen" when checking oxygen requirements and not for any oxygen substitute.
