### ISSUE TITLE
Lings having trouble using Reviving Stasis.

### ISSUE THREAD

**Issue by B00tz** [tgstation/tgstation#76665]
## Testmerges:
[#76564: 'Ports cluwnes' by jlsnow301 at commit f56e1ba37d](https://www.github.com/tgstation/tgstation/pull/76564)

## Reproduction:
(note: I was an Ethereal so that may be the cause of the issue)
Be ling.
Die.
Use reviving stasis.
Sit there for a good long while to confirm that yes indeed you arn't getting up anytime soon.

**Comment by MrMelbert** [comment]
ahhhhhhhhhhhhhh you can't `fakedeath` if you're dead ahhhhhhhhhh
