### ISSUE TITLE
datum components appear twice in the component list

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#76678]
This might have been around for ages and I'm not aware of any problems that has come out of it but it seems weird to me.

Pretty simple to reproduce.

1. Find anything that uses a component say for example the engineering protolathe in the shared engineering storage room
2. VV analyze it & look for its components
3. Observe the same component appear twice in the list
![Screenshot (274)](https://github.com/tgstation/tgstation/assets/110812394/2dc58516-6c25-40bc-95eb-81e5e82fde7c)

This might be an issue because the component is getting deleted twice in the for loop during destroy
https://github.com/tgstation/tgstation/blob/5398edf4a6e0860e5babf88745f12f03be03061b/code/datums/datum.dm#L129-L134

Now again this might be intended for reasons i don't understand so if anyone does close this an explanation would be appreciated

**Comment by LemonInTheDark** [comment]
nah this smells like a bug u right
