### ISSUE TITLE
Revolvers permanently decrement ammo capacity on reloading with a speedloader if you do not empty the magazine first

### ISSUE THREAD

**Issue by vinylspiders** [tgstation/tgstation#76681]
## Reproduction:

-> Fire all 6 live rounds from a revolver (detective's for example). Do not empty it. 
-> Use a speedloader on it
-> See that in the examine text there are now 5 rounds loaded.
-> Repeat steps above, see that it gets to 4... etc

Also, if you try to load a single bullet without the speedloader while the magazine is not empty it will simply not increment the ammo count.

Loading with both single bullets and the speedloader works fine when you have the magazine emptied first.
`max_ammo` var for the magazine is unchanged. I suspect it has something to do with the way `ammo_count()` works (`stored_ammo` list not being updated properly when inserting ammo, perhaps).

**Comment by Sealed101** [comment]
could have been my fuckup, too
- #76323
