### ISSUE TITLE
pAIs cannot cast (admin given) spells 

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#76684]
## Reproduction:

go pAI
give yourself spells
set to robeless
can't cast (redded out)

**Comment by MrMelbert** [comment]
https://github.com/tgstation/tgstation/blob/6701e902979b9d7ba12778280e316f71f8b1684c/code/modules/spells/spell.dm#L212-L214

Not a bug - PAIs are prevented from casting spells due to general bugginess. Could be removed from this line but just be aware it'll in turn break with some spells.
