### ISSUE TITLE
Metastation AI sat request console is called "Unknown request console"

### ISSUE THREAD

**Issue by nikothedude** [tgstation/tgstation#76689]
## Reproduction:

Spawn in on meta, look at the sat, see how the thing is called unknown request console.
This is probably because this thing isn't mapped in with a name. It tries defaulting to a departmental name, but it has no department, so it defaults to unknown.

Probably exists in other maps too.

**Comment by DATA-xPUNGED** [comment]
This has been fixed at some point

**Comment by nikothedude** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/77525
