### ISSUE TITLE
Mechs can have access added to them that ID doesn't have

### ISSUE THREAD

**Issue by DrPepperIsSpicy** [tgstation/tgstation#76706]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/137026778/9e5279d2-5259-4cc8-8628-317c530019a4)
Doesn't check to see if the access adder's ID has the access being added.

**Comment by TheVekter** [comment]
Not sure, but can you test this without having the captain's ID in your bag? I doubt it matters but I want to make sure.

**Comment by DrPepperIsSpicy** [comment]
yeah

**Comment by DrPepperIsSpicy** [comment]
![image](https://github.com/tgstation/tgstation/assets/137026778/433f441c-c65e-4f42-a7a1-4c2de0d2e522)

**Comment by DrPepperIsSpicy** [comment]
this doesn't give the mech the access by the way, it just stops people without it from entering.

**Comment by TheVekter** [comment]
> this doesn't give the mech the access by the way, it just stops people without it from entering.

It's probably not a bug then, unless it's possible to lock yourself out of the mech permanently.

**Comment by DrPepperIsSpicy** [comment]
It is possible, since you can give accesses limited to centcomm.

**Comment by SyncIt21** [comment]
The whole interface was changed by #77221. Is this still an issue?
