### ISSUE TITLE
Tin Man Quirk Dumps Organs On Spawn

### ISSUE THREAD

**Issue by orthography** [tgstation/tgstation#76700]
## Testmerges:

n/A

## Reproduction:

Pick Tin Man, late join (possibly same issue on fresh spawn too), all your organs hit the floor like a bag of fleshy rocks.

![image](https://github.com/tgstation/tgstation/assets/98856144/2961b77d-98db-4147-857a-0fa96b50cb13)

**Comment by ChungusGamer666** [comment]
seems to be caused by a recent change to organs, will hopefully fix it soon even though it is funny

**Comment by MrMelbert** [comment]
Hm, I wonder why the organs are dropping when replaced?
![image](https://github.com/tgstation/tgstation/assets/51863163/de3ea5e7-35d1-40c8-b1cc-7497c3878bf6)

**Comment by orthography** [comment]
ON IT, MELBERT!!!!

**Comment by ChungusGamer666** [comment]
> Hm, I wonder why the organs are dropping when replaced? ![image](https://user-images.githubusercontent.com/51863163/252208211-de3ea5e7-35d1-40c8-b1cc-7497c3878bf6.png)

What the hell! !!!!!
how did i actually do this

**Comment by Generubi** [comment]
I can confirm, also happens at roundstart
