### ISSUE TITLE
Testmerge screws up brains, Shit's Fucked

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#76712]
Reporting client version: 514.1589

## Round ID:
[209970](https://scrubby.melonmesa.com/round/209970) and 209974, probably anything with this testmerge

## Testmerges:
[SPECIES NUKING 2023: TOTAL EXTERNAL ORGAN DEATH](https://www.github.com/tgstation/tgstation/pull/76381)

## Reproduction:
Get decapitated!
have your head get reattached to your body.
Almost crash and watch your brain (generic item name brain, not [Spaceman]'s Brain) get sent to the fucking shadow realm.
![image](https://github.com/tgstation/tgstation/assets/76874615/fee5671e-3e89-4735-8e65-93065eff56d6)
![image](https://github.com/tgstation/tgstation/assets/76874615/86149278-f82b-4ee6-9c50-1308efe9ac41)

When the surgeon takes the brain out, the generic brain item vanishes and allegedly fuses with what is pulled out. 
When it's put back in and revived, lag out again like the first time get sent back to the shadow realm again in an unnamed brain again.

I had to intervene by ahealing and dragging the ghost back into the healed body after all that
skillchips got abandoned in the generic brain item that was in the glitch room

Apperently, in another case where i didn't intervene with an aheal, this also unlinks the ghost from the body, aka the blood, so podcloning doesn't work anymore, allegedly, but it's a problem mingling with the unlinking this beheading thing causes so it's here too

**Comment by TheVekter** [comment]
This sounds odd, but this might not actually be related to the testmerge. This is an older bug we've been having for a while where brains sometimes just fuck off to the debug room.

**Comment by SyncIt21** [comment]
Very similar to #74326 guess like it wasn't truly fixed.

**Comment by AdipemDragon** [comment]
It evidently happens because of something the Tm just did, otherwise it wouldn't happen consistently on Manuel, where it's currently active. I would go test right now but I can't right this second

**Comment by Isratosh** [comment]
Just to clarify, the nullspace event happened immediately after clicking the "reenter corpse" button as a ghost.

**Comment by AdipemDragon** [comment]
![image](https://github.com/tgstation/tgstation/assets/76874615/3fbb54c2-0e2b-44b6-89a3-79a9169c45eb)
everytime

**Comment by ChungusGamer666** [comment]
![image](https://github.com/tgstation/tgstation/assets/82850673/9ebb7127-8237-4088-b185-75dbe96f8398)
head reattachment SEEMS to be fixed!
pushing it

**Comment by ChungusGamer666** [comment]
nevermind not yet its still fucked

**Comment by TheVekter** [comment]
This is no longer relevant as the PR this feature was on has been closed.
