### ISSUE TITLE
most Popup windows randomly stop opening after a while.

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#76722]
## Round ID:
[209986](https://scrubby.melonmesa.com/round/209986) but this occurs basically every round for me.

## Reproduction:

Basically, whenever I play the round, after a while, most pop up windows will just stop opening when I try and activate them. On some rounds this can be mitigated by spam-clicking until it eventually pops up, but on others the windows will just stop opening. This doesnt apply to all popups, just some. 

Windows this generally happens to: 
- Crafting menu
- APC menu
- Machines and computers in general
- Vendors
- Strip menu
- Door menus.

Reconnecting does not fix this issue.
Restarting the client and connecting again manually does fix this issue (Or rather reset it until it slowly happens again)
Using the Refresh TGUI verb will re-open every single tgui window that has been opened in this session.

Based on this I think what's happening is that closing tgui windows is not properly shutting them down, and they are in some way all remaining active and I get prevented from opening them again once there are enough?

**Comment by Sealed101** [comment]
i think the windows are being minimized instead of closed somehow, yeah

**Comment by xprtdrt** [comment]
i had this same issue. its incredibly frustrating. if i remember right, i fixed it by enabling fancy tgui in game prefs

**Comment by LemonInTheDark** [comment]
> This is happening downstream too. It's really a frustrating issue.
> 
> This also comes up a lot, unsure if related:
> 
> ![image](https://user-images.githubusercontent.com/13398309/253629843-5737d7c5-ced4-41ca-837c-c4ce2f4eb253.png)

It's possible that that runtime is why you're having problems, but it's happening because you dropped a pr mirror https://github.com/tgstation/tgstation/pull/76251

**Comment by LemonInTheDark** [comment]
I did change some things that seemed like bugs with how tgui handled window cleanup. it's possible that's what's going on here? would be useful to poke around in vv when this happens.

**Comment by LemonInTheDark** [comment]
that is odd but should be unrelated, that's a ui object not a window

**Comment by Sightld2** [comment]
[Live footage of the bug](https://www.youtube.com/watch?v=bSNj11eNAgs)

**Comment by Sealed101** [comment]
#77101 went through but let's keep tabs on this one for a little while

**Comment by jlsnow301** [comment]
Very quiet here now, assuming this is fixed due to the PR above. Feel free to reopen if it isn't

**Comment by Sealed101** [comment]
you didn't close it NERD

**Comment by jlsnow301** [comment]
it was cleanup flagged woweee

**Comment by Sealed101** [comment]
man nobody who is reporting issues checks the issue tracker more than a month deep, just close 'em.
