### ISSUE TITLE
Cult antagonist status is split wierdly between both body and soul.

### ISSUE THREAD

**Issue by DustanHache** [tgstation/tgstation#76746]
## Round ID:
[210020]

## Testmerges:
N/A

## Reproduction:

Be roundstart cultist.
Get caught out early.
Get gibbed by prayer to avoid deconversion
get brain transferred to a new body.

New body still posesses cult objectives and the ability to use their gear/chat, but lacks the objective tracker status and the ability to use cult magic.

**Comment by TheVekter** [comment]
@JohnFulpWillard I think you touched this last?

**Comment by JohnFulpWillard** [comment]
> the ability to use cult magic.

To draw spells n stuff you mean?
I didn't touch this stuff but it seems like an easy fix.

**Comment by DustanHache** [comment]
> > the ability to use cult magic.
> 
> To draw spells n stuff you mean? I didn't touch this stuff but it seems like an easy fix. 
not quite so cut and dry. you can still draw and invoke runes if you have a dagger, but you cannot use the “empower” rune to give yourself cult spells.

**Comment by JohnFulpWillard** [comment]
> you can still draw and invoke runes if you have a dagger, but you cannot use the “empower” rune to give yourself cult spells.

yeah that's what i meant. We just have to properly transfer over cult actions on antag's mind transfer.
