### ISSUE TITLE
Implant Removal Surgery Bugged

### ISSUE THREAD

**Issue by milktao** [tgstation/tgstation#76756]
## Round ID:
[210046](https://scrubby.melonmesa.com/round/210046) (although this has been a bug for a while now)

## Testmerges:
N/A

## Reproduction:
Perform Cavity Implant surgery and implant an item.
Perform Implant Removal surgery, (which has a strange order of steps that differ from the wiki). Scalpel > hemostat > retractor > hemostat (to remove implant), a message pops up saying "You can't find anything in {user}'s chest!" then cauterize. The item is still inside the person and I would expect the surgery to have retractor first then hemostat.

**Comment by SirNooben** [comment]
This is irrelevant as the cavity implant and implant removal surgeries are for two different things. Cavity implant is something you put in the chest and is removed by doing the same surgery again and at the step when you insert you have to use an empty hand to remove it. Implant removal removes implants such as mindshields, it even says so on the surgery wiki.

**Comment by TheVekter** [comment]
Nooben is correct, this is working as intended.
