### ISSUE TITLE
Scanner/Goggles Sprites Inconsistency

### ISSUE THREAD

**Issue by milktao** [tgstation/tgstation#76750]
## Round ID:
[210032](https://scrubby.melonmesa.com/round/210032)

## Testmerges:
N/A

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/22015544/4333517e-7e7d-4776-a50c-17beb0c36330)
On the left is "Engineering Scanner Goggles" in meson mode and on the right is "Optical Meson Scanner" showing green colouring.
Meson mode was recently changed back to being yellow, but the "Optical Meson Scanner" has not been changed too.

![image](https://github.com/tgstation/tgstation/assets/22015544/285f5c6e-8468-47fc-82c8-91ef124ada38)
This is an "Optical T-Ray Scanner" which Atmospheric Technicians usually wear, in Connectable mode.

**Comment by Likteer** [comment]
The 2 goggles differed already before the resprite.

**Comment by Sealed101** [comment]
true but they weren't gmod erroring

**Comment by OrionTheFox** [comment]
![image](https://github.com/tgstation/tgstation/assets/76465278/45339000-5bcf-4801-93b9-64978ec49240)
gmod error is gone, cs:source has been installed

**Comment by Ghommie** [comment]
Gmod error gone, the different colors are pretty much mandatory or they'll basically look the same.
