### ISSUE TITLE
miner credit transfer cards give more than they cost

### ISSUE THREAD

**Issue by DrPepperIsSpicy** [tgstation/tgstation#76768]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
325 for a card, 500 contained in the card. 175 profit per card bought.

**Comment by BlueMemesauce** [comment]
That's because it's discounted if you buy it through cargo. It costs 500 to buy it express. Should probably remove the ability to buy it through cargo.

**Comment by DrPepperIsSpicy** [comment]
makes sense

**Comment by Sealed101** [comment]
@DrPepperIsSpicy it is unnecessary to close the issue when a PR is linked to it, it will close automatically when that PR is merged
