### ISSUE TITLE
Autopsies conflict with themselves and Dissections

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#76775]
Reporting client version: 514.1589

## Testmerges:
N/A

## Reproduction:
1. Acquire a cadaver.
2. Perform either a dissection or an autopsy.
3. You can no longer perform autopsies on that cadaver. Even after revival and death 2.

While I understand the speed boost from dissections would have them be a once-per-person ordeal, an autopsy is something you could very easily need to do to the same body multiple times in a round. From what I've heard, autopsies also apply the dissection speed boost. I don't think that's necessary. I'd remove the speedboost from autopsies and separate them from dissections - I should be able to perform an autopsy as many times as I'd like to. If John "Victim" Assistant dies again after his first autopsy, I should be able to produce a new one.

**Comment by MrMelbert** [comment]
This is intended / more of a code request than an issue

**Comment by necromanceranne** [comment]
I'd consider it an oversight in that it blocks future autopsies when that was the intend method for coroners to gather medical data. Just needs some separating out of traits and finding ways to clear traits when possible.

**Comment by TheVekter** [comment]
I agree with Anne on this; it seems more like just something that wasn't considered rather than it actually being intended, especially since you can dissect someone, revive them, kill them, then be unable to autopsy them. If it was intentional, it wouldn't persist between deaths.

**Comment by lessthnthree** [comment]
I started to work on this and found (I'm going to say half-related) issue. https://github.com/tgstation/tgstation/issues/77135

There's some gaps in the revival check that dissection-autopsy probably falls in with.

**Comment by JohnFulpWillard** [comment]
It was intentional that you could not do autopsy/dissection, or repeated autopsies on the same body, but I've said in the past that I am fine with removing the requirement for autopsy. It's not a bug, but it's a harmless change if anyone wants to do it.
