### ISSUE TITLE
Bileworm turning into vileworm while you are consumed by them makes you vanish

### ISSUE THREAD

**Issue by InsaneTGplayer** [tgstation/tgstation#76791]
## Reproduction:
1. Get crit
2. Be consumed by bileworm
3. Wait
4. Body vanishes (even if you were alive and uncrit) once bileworm turns into vileworm

Issue is that deleting players is quite not cool. Even if the person is dead, other miners can try to rescue them

**Comment by TheVekter** [comment]
I'm not 100% sure this is unintentional. @tralezab Can you confirm?

**Comment by Time-Green** [comment]
I hereby maintainer declare this as unintentional

**Comment by Jacquerel** [comment]
This is _probably_ unintentional as the Bileworm is designed to eject stored players when it dies, so it's not intended as round removal.
"Evolving" deletes the original mob and replaces it with a new one, which neither transfers nor dumps the contents.

**Comment by InsaneTGplayer** [comment]
Honestly I just stare with my rod of asclepious that the worm decimates the wizard npcs and im just thinking about how to escape (full health but pacified) when I suddenly turn into a ghost
