### ISSUE TITLE
Revived androids can be stuck with un-healable oxy damage

### ISSUE THREAD

**Issue by GPeckman** [tgstation/tgstation#76804]
## Testmerges: 

#76728 

## Reproduction:

Find a corpse, convert it into an android with the robotic chaplain sect, then attempt to defibrilate. The android will be revived, but will have 150 oxy damage that does not heal on its own and seemingly cannot be healed, at least not with the methods tested (bible smacking and CPR). As far as I know, androids do not breath and should not be capable of getting oxy damage in the first place.

I've converted and then revived corpses before, so this bug was likely caused by a recent change. Probably one of the species/organ refactors.

**Comment by ATH1909** [comment]
I could've sworn we used to have a check for TRAIT_NOBREATH in spec_life() that set oxyloss to 0; I remember bullying SR devs over creating their own nooxyloss trait instead of using that

did it get removed?

**Comment by GPeckman** [comment]
https://github.com/tgstation/tgstation/blob/6977a041a999c16c5bee439ea99ede9883759d9d/code/modules/mob/living/carbon/human/species.dm#L873-L876

It did used to exist. Looks like it got removed by accident in one of the species nukening PRs.
