### ISSUE TITLE
Syndicate drop pod post kidnaping can drop you in dangerous areas

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#76813]
Reporting client version: 514.1589

## Round ID:
[210170](https://scrubby.melonmesa.com/round/210170)

## Reproduction:
Get kidnaped
Return
Get dropped in gas tank
Be effectively round removed by drop pod
(FYI I had chameleon genes which is why I am not in the image, I'm right on top of the items)
![image](https://github.com/tgstation/tgstation/assets/36141254/95018d44-3c2b-4614-a5e1-6d81dd12b7cc)

**Comment by Jacquerel** [comment]
starting to seem like we maybe need a "get_actually_safe_station_turf` proc
