### ISSUE TITLE
Syndicate basicmobs (and possibly other ones) when firing, eject unspent buckshot shells

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#76815]
Reporting client version: 514.1589

## Reproduction:

1. get a syndie shotgun dude to shoot you
2. see that they leave unspent buckshot

**Comment by Jacquerel** [comment]
This is how they have infinite ammunition, they're capable of putting the unfired buckshot back into the gun and firing it again. 🤔

**Comment by DustanHache** [comment]
> This is how they have infinite ammunition, they're capable of putting the unfired buckshot back into the gun and firing it again. 🤔

i smell chronogun shenanigans. they literally rewind their shots to conserve and generate ammo for the nukies.
