### ISSUE TITLE
If you throw supermatter from the cliff it will dust itself.

### ISSUE THREAD

**Issue by Helg2** [tgstation/tgstation#76811]
## Reproduction:
1. Get supermatter.
![image](https://github.com/tgstation/tgstation/assets/93882977/c91aa03a-3962-4b35-bc21-ea80833e41d1)
2. Find a cliff and push it.
3. It dusts itself.
![image](https://github.com/tgstation/tgstation/assets/93882977/ad2c7dbe-f46c-4217-adda-c0b06bbd390e)
![image](https://github.com/tgstation/tgstation/assets/93882977/b9f65c9b-683b-4d6c-9182-5d901c6a2e3b)

**Comment by DustanHache** [comment]
ah yes, the wonder of multiz and their torturously finnicky atmos/object handling. another reason for me to despise and want to avoid icebox.

**Comment by Jackal-boop** [comment]
This also happens on stairs
