### ISSUE TITLE
Solar panel tiles have gravity

### ISSUE THREAD

**Issue by MTandi** [tgstation/tgstation#76827]
https://github.com/tgstation/tgstation/assets/3625094/354f7413-1e5e-4dfe-bb03-dbae5f14ce06

Tiles under the solar panels are magnetic.

This was fixed a few months ago, but seems to happen again.

## Reproduction:

1. Try walking onto a solar panel tile
2. Notice that you lose weightless status

**Comment by plutori** [comment]
I always thought this was intentional so you could just toss solar panels on to a tile instead of having to manually float to each tile.

Fixing this will just increase annoyance for engineers who do solars tbh

**Comment by MTandi** [comment]
> I always thought this was intentional so you could just toss solar panels on to a tile instead of having to manually float to each tile.
> 
> Fixing this will just increase annoyance for engineers who do solars tbh

I also thought so, but there is no such effect when you build it in space, so this is something related to these tiles being subtype of iron floor.

Agree that it would be nice if these were "magnetic" for solar panel assemblies, but this has to be consistent then.

**Comment by YakumoChen** [comment]
I thought solar panel tiles were just part of a station area?
