### ISSUE TITLE
Megafauna is immune to singularity 

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#76831]
## Reproduction:

Megafauna (polymorphed Ashdrake version) wasn't affected by singu at roundend.

**Comment by mikederkan** [comment]
bruh

**Comment by Jacquerel** [comment]
Appears to be intentional, as megafauna cannot be gibbed if their health is greater than 0.
This does expose a different bug where the the Singularity still _thinks_ that it has eaten them and powers itself up, potentially infinitely.

**Comment by the-og-gear** [comment]
I don't think that's intentional. Singulo shouldn't be gibbing but instead just removing the mob from existence.

**Comment by Jacquerel** [comment]
It will usually eat the gibs in short order, but run any mob into the singularity (including a player) and it will gib.
That said on the basis that the supermatter can dust a dragon it should probably be able to be consumed by the singularity.
