### ISSUE TITLE
Compound fractures are not surgically curable

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#76832]
Reporting client version: 514.1589

## Round ID:
[210245](https://scrubby.melonmesa.com/round/210245)

## Testmerges:
- [Standardizes a majority of the GAGS configs for Clothing](https://www.github.com/tgstation/tgstation/pull/76384)

## Reproduction:

Suspect caused by #76533 as this is a new recent issue.

Surgical correction of compound wounds no longer works ; normally during surgical steps you get told you are "carefully applying" bonegel, however, now, it always reports you "hastily applying" it, which is the same as not using surgical steps at all.

Reproduction, spawn a /human and smite it with boneless, slam it on a table and check for a compound fracture.

Start 'repair compound fracture', use scalpel, retractor, hemostat, bonesetter, bonegel.  Observe you get the 'hastily applying' message instead of the 'carefully applying'.  Note the wound isn't cured on completion (and wound scan mode shows you should use tape to start the non-surgical wound fix).

On a different compound fracture, skip surgery and just bonegel then tape them, note this ends up with the same results as the above.

```(surgical steps)

You drape the surgical drapes over Lakeisha Brown's right leg to prepare for Repair Compound Fracture.
You put the surgical drapes into the surgical duffel bag.
You begin to make an incision in Lakeisha Brown's right leg...
Blood pools around the incision in Lakeisha Brown's right leg.
You put the scalpel into the surgical duffel bag.
You begin to retract the skin in Lakeisha Brown's right leg...
You succeed.x2
You put the retractor into the surgical duffel bag.
You begin to clamp bleeders in Lakeisha Brown's right leg...
You put the hemostat into the surgical duffel bag.
You begin to reset the bone in Lakeisha Brown's right leg...
You successfully reset the bone in Lakeisha Brown's right leg.
=====> You begin hastily applying the bone gel to Lakeisha Brown's right leg, disregarding the warning label... <=====
Lakeisha Brown screams!
You finish applying the bone gel to Lakeisha Brown's right leg!

(and med scan)

Warning: Physical trauma detected in human right legType: Compound Fracture
Severity: Critical
Description: Patient's bones have suffered multiple gruesome fractures, causing significant pain and near uselessness of limb.
Recommended Treatment: Immediate binding of affected limb, followed by surgical intervention ASAP.
Continue Alternative Treatment: Apply surgical tape directly to injured limb to begin bone regeneration. Note, this is both excruciatingly painful and slow, though sleep or laying down will speed recovery.

```

(EDIT: Wierdly if you bandage them before doing surgery it says the application is okay, but still doesn't cure it, wasn't how this used to work though?)

**Comment by TheVekter** [comment]
@carlarctg This might be related to one of your PRs.
