### ISSUE TITLE
Crayon powder does not color players when ingested

### ISSUE THREAD

**Issue by Ultikrill** [tgstation/tgstation#76856]
## Round ID:

Not discovered in any actual rounds, discovered while messing around on a one-person test server. I was running a version of the code I've downloaded roughly 5 something hours ago as of writing this.
## Reproduction:

As the title suggests, crayon powder no longer colors the player when ingested. I've tried it with eating full crayons as well as ingesting crayon powder pills. Colorful reagent works normally, so it's likely specific to crayon powder. It's a simple bug to reproduce, just eat any crayon, and watch as the fun effects totally fail leaving your spess life as bland and miserable as it was before.

**Comment by mikederkan** [comment]
Intended behaviour

**Comment by Sealed101** [comment]
the above is true
https://github.com/tgstation/tgstation/blob/0f47384465c29911fef57a13013337f1ea6a2cb2/code/modules/reagents/chemistry/reagents/other_reagents.dm#L1548-L1590

unless the rainbow crayon or the non-crayon colorful reagents don't color you, then yeah
