### ISSUE TITLE
#76048 is not working on live servers

### ISSUE THREAD

**Issue by DATA-xPUNGED** [tgstation/tgstation#76850]
## Reproduction:

- Go to a live server, i've tested this on manuel
- you should see this
![image](https://github.com/tgstation/tgstation/assets/44149906/58add999-a3b0-4d73-a377-e9cdec907f4e)
- On an updated localhost, this appears instead, which is what #76048 added
![image](https://github.com/tgstation/tgstation/assets/44149906/0fa21bb0-5a5d-4929-a83d-62ac0d124fe9)

**Comment by distributivgesetz** [comment]
Config issue, this'll be something that I'll have to bother key holders about I think

**Comment by san7890** [comment]
> Config issue, this'll be something that I'll have to bother key holders about I think

correct. please reach out to them through the forums or discord or something.
