### ISSUE TITLE
Paralax is borked on multi-z, causing the bottom layers of the map to be merged making everything appear as if its space

### ISSUE THREAD

**Issue by Rex9001** [tgstation/tgstation#76892]
Reporting client version: 514.1589

## Round ID:
[210366](https://scrubby.melonmesa.com/round/210366)

## Testmerges:
- [Standardizes a majority of the GAGS configs for Clothing](https://www.github.com/tgstation/tgstation/pull/76384)

## Reproduction:
1. Boot up tramstation
2. Go down one floor
3. Watch as every tile is transparent

**Comment by Rex9001** [comment]
Running 'delete /atom/movable/screen/parallax_layer' in sdql2 seems to fix this but makes space all white, mostly just helpful for admins.

**Comment by TheVekter** [comment]
This is being fixed but in the future please include screenshots for parallax/graphical issues.

**Comment by Rex9001** [comment]
> This is being fixed but in the future please include screenshots for parallax/graphical issues.

Will do, Time-Green fixed my screen before I had a chance with the line of SDQL.

**Comment by Rex9001** [comment]
This is still an issue on Terry.
![Screenshot 2023-07-17 203640](https://github.com/tgstation/tgstation/assets/120136161/27145673-f46b-4f4d-84b2-17f04db6dc98)
