### ISSUE TITLE
you can't crawl out of graves

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#76918]
Reporting client version: 514.1589

## Round ID:
[210397](https://scrubby.melonmesa.com/round/210397)

## Testmerges:
(may be wrong, i didnt hit report issue until the next round started. check the round ID above for testmerges)
- [Optimization pass focused on foam code (saves about 30% of cpu usage I think)](https://www.github.com/tgstation/tgstation/pull/76104)
- [Temporarily reverts 76772 "Hud screens now set hud owner in Initialize."](https://www.github.com/tgstation/tgstation/pull/76893)

## Reproduction:
1. On icebox/elephant graveyard ruin on lavaland, find a grave
2. Dig it up with a shovel, climb on top, lay down, and bury yourself alive.
3. Spam resist.
4. You can't get out.

These specifically have a 90 second breakout time so I'm pretty sure you're supposed to be able to unbury yourself alive.

**Comment by MrMelbert** [comment]
local man buries himself alive, expects to be able to reverse this decision

**Comment by VladinXXV** [comment]
> local man buries himself alive, expects to be able to reverse this decision

I mean, yes. They're closets. Closets specifically set to have a 90 second breakout time. And you can bury others alive too.

**Comment by Sealed101** [comment]
feature

to be fair they should not be closets ideally

**Comment by necromanceranne** [comment]
If the expectation is that you can escape, given it has a breakout timer, then it probably is a bug.
