### ISSUE TITLE
Turf icon changes and varediting magic

### ISSUE THREAD

**Issue by Razharas** [tgstation/tgstation#7692]
I tried to change the icon of the turf in the wizard den by varedit
After i changed it and refreshed the varedit page it turned out the varedit is now pointing to a different turf and the icon was also changed of the different turf, not the one i initially wanted to change
Each time the turf switches to the same different turf, different turf is always of the same type and usually not too far away, few screens
Each different turf switches to its unique other turf, no pattern of coordinate placement was traced from this behaviour by me, looks like they switch to seemingly random turf, it is also static from round to round

**Comment by optimumtact** [comment]
varedit was changed
