### ISSUE TITLE
Possessed MULEbots can run over living players

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#76926]
I wasn't actually going to post this but I think if I get one more report of "HELP THE MULEBOT JUST RAN ME OVER BAN HIM" I'm going to pop a blood vessel.

To my knowledge, a MULE with a personality is not supposed to be able to run over people, yet here we are. If they are lying on the ground, they can run over them and do just a stupid amount of brute. This probably shouldn't be possible.

To be fair, cleanbots can do something similar, but their knives do like 5-10 brute while driving over someone with a MULE does like 50.

**Comment by ATH1909** [comment]
player mules (and unhacked mules) are just unable to knock down people by running into them. once they're prone, any mulebot can run over 'em, even an unhacked one.

**Comment by TheVekter** [comment]
> player mules (and unhacked mules) are just unable to knock down people by running into them. once they're prone, any mulebot can run over 'em, even an unhacked one.

This is still causing issues because it takes very little for someone else to do the knocking down. A lot of MULEbots will just roll over anyone who's lying down with no care for who or why as well. Jacquerel's PR is a good resolution to this issue.
