### ISSUE TITLE
Beach Barkeep's lockers are a smidge weird

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#76943]
Reporting client version: 514.1589

## Round ID:
[210495](https://scrubby.melonmesa.com/round/210495)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/76874615/7117781a-608d-441f-9e33-db4ac1f52b85)

**Comment by TheVekter** [comment]
Is it two lockers stacked on top of one another?

**Comment by AdipemDragon** [comment]
Nope, it's the doors just turning into basic locker doors
