### ISSUE TITLE
You can do implant removal surgery on any mob under /mob/living

### ISSUE THREAD

**Issue by SapphoQueer** [tgstation/tgstation#76958]
## Round ID:
[210568](https://scrubby.melonmesa.com/round/210568)

## Testmerges:
none

## Reproduction:
1. Take drapes
2. Target chest
3. Do implant removal surgery. With medical tools. For some reason. Somehow. This is incredibly cursed when done on sillicons or slimes or the like. 

![image](https://github.com/tgstation/tgstation/assets/94389951/6c9f060f-a101-4145-bfbe-f9876c1977ae)

**Comment by nikothedude** [comment]
maybe block most surgeries if the mob has the robotic biotype

**Comment by Derpguy3** [comment]
Feels semi-intentional, as you can give cyborgs implants, such as the death-rattle implants nuclear operatives can buy.

**Comment by Vincent983** [comment]
I believe you can give any living mob implants infact, even things they cant use like the storage implant

**Comment by distributivgesetz** [comment]
Not an issue, deathrattle implants can be implanted into any mob so surgery has to still work on everyone
