### ISSUE TITLE
Stamina damage is extremely buggy

### ISSUE THREAD

**Issue by paprka** [tgstation/tgstation#7695]
Stamina damage is sending me into crit, but not fully into crit. It puts me into a pseudo crit where my health thing shows crit, but I'm still fully conscious, just on the ground and unable to move. Stamina damage is somehow conflicting with regular damage and fucking with things

**Comment by Jalleo** [comment]
I think this happened before when holo damage first started

**Comment by AlexanderUlanH** [comment]
Staminaloss is capped at your current health, but it probably doesn't get reduced when you take damage, so this would probably happen if you took damage after staminaloss knocked you down.  Reproduce it by getting knocked down with a disabler then smacked with an esword.  You're disabled by the staminaloss, and your health display will show crit.  More or less as intended.
If it's confusing, staminaloss could be moved to a display separate from health, but it's not really buggy.

**Comment by paprka** [comment]
Stamina loss should not be displaying crit unless you're actually in crit, so yes, that's a pretty major bug.

**Comment by TheWiznard** [comment]
I don't know the what damage lasertag guns do to you but this happens when you are repeatedly shot with lasertag beams via guns or turrets. The whole "the icon says you're in crit" but you're still alive thing.

**Comment by paprka** [comment]
Holy shit apparently laser guns are causing people to fall into stamina knockdown, what the shit

can someone find the source of this weirdness in the stamina code?

**Comment by tedward1337** [comment]
I believe this was fixed over the past year

**Comment by phil235** [comment]
yep, fixed
