### ISSUE TITLE
Birdshot morgue lacks a surgery bag, every other station has one.

### ISSUE THREAD

**Issue by SapphoQueer** [tgstation/tgstation#76960]
## Round ID:
[210579](https://scrubby.melonmesa.com/round/210579) (and just about every other birdshot round)

## Testmerges:

irrelevant

## Reproduction:
Load into birdshot. It's merely a consistency issue but it's one that annoys me anyways due to me actually being a coroner player.

**Comment by TheVekter** [comment]
While you're correct in it being a consistency problem, coroners _do_ start with a kit in their backpack that comes with special surgery tools.
