### ISSUE TITLE
changelings can once again turn you into a plasmaman, burning you to death

### ISSUE THREAD

**Issue by scriptis** [tgstation/tgstation#76972]
## Testmerges:

[#76663: 'Bumps rust-g to pre-release version of `3.0.0` ' by san7890 at commit ce331dda19](https://www.github.com/tgstation/tgstation/pull/76663)

## Reproduction:

1. be changeling
2. dna extract sting a plasmaman
3. dna transform sting into someone else
4. they fucking die lmao

this shouldn't be possible (plasmamen don't have DNA) and was previously fixed in #61928

**Comment by ArcaneDefence** [comment]
based

**Comment by Mooshimi** [comment]
https://github.com/tgstation/tgstation/blob/06ca7a4481f657ea74ad464825b1ae78d371da09/code/modules/antagonists/changeling/changeling.dm#L454-L498

https://github.com/tgstation/tgstation/blob/316767fc0712ee0ffaf3d4b48e0fda9973b4c1d3/code/modules/mob/living/carbon/human/species_types/golems.dm#L2-L18

https://github.com/tgstation/tgstation/blob/HEAD/code/modules/mob/living/carbon/human/species_types/plasmamen.dm#L1-L15
