### ISSUE TITLE
Captain seems unable to award medals

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#76979]
Reporting client version: 514.1589

## Round ID:
[210628](https://scrubby.melonmesa.com/round/210628)

## Reproduction:
Be a clown, do good, get awarded a medal of captaincy!
Watch the captain swear at the inability to just pin a thing to someone else's suit.
Easely put it on by yourself with no valor attached to it.

I tested it in the thunderdome in a later round, all medals aren't stickable to someone else. It's Gotta be something overlooked by #76629

Would it be fairer to be treated as a more general "nobody can accessorise someone else" issue or?

**Comment by Sealed101** [comment]
`attach` and `attach_accessory` assume that they get an item of clothing to get attached to, and you can't really fiddle with someone's clothing that way. previous code was handling medal awarding by using the medal's `attack` to get the mob and the mob's worn clothing

**Comment by MrMelbert** [comment]
Oh god I deleted the attack code by accident in a final pass over, that was not intended at all

**Comment by Sealed101** [comment]
happy accidents
