### ISSUE TITLE
Inline bench presses lie to you

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#76980]
Reporting client version: 514.1589

## Round ID:
[210643](https://scrubby.melonmesa.com/round/210643)

## Reproduction:
Sometimes you press delete to remove a word and that somehow makes you post an incomplete issue report it's _Fine._

![image](https://github.com/tgstation/tgstation/assets/76874615/18bf659d-97e1-4856-9242-5f02196bfd8d)
Try to work out by following the old method.
Watch the "tooltip" lie to you, you're supposed to drag yourself onto em, not just click.

**Comment by AdipemDragon** [comment]
Neverfucking mind, missed them having a completely new method of interaction, chalk that up to me being not inquisitive enough

**Comment by AdipemDragon** [comment]
Why do I only think of things **After** I Press The Button.
The issue is now that the text showing you how to interact with something isn't the same as what needs to happen.

**Comment by Sealed101** [comment]
lying is even worse than Not Working ™️
