### ISSUE TITLE
Medibots made from syndicate medkits lack their unique sprite

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#76996]
## Round ID: **N/A**
Found during local testing

## Testmerges:
**N/A**

## Reproduction:
Medibots which are made from syndicate medkits obtain its associated properties, but they do not have their unique sprite while as an assembly and a mob.
![medibot_bezerk](https://github.com/tgstation/tgstation/assets/85206687/0456e12e-8814-4288-8ac4-3cb1ad537d0b)
![syndicate medibot problems](https://github.com/tgstation/tgstation/assets/85206687/09dbdb15-dcca-4bdb-9af9-98b00786485c)

**Comment by AdipemDragon** [comment]
I really oughta resprite all the medibots...

**Comment by cnleth** [comment]
![syndie_medbot](https://github.com/tgstation/tgstation/assets/113535457/cafb6022-1e84-438a-b5af-2f11bc2b06bb)
This is what a medbot with this skin looks like... I'm not sure if i should even PR this

**Comment by Helg2** [comment]
> I'm not sure if i should even PR this

Pr this so someone resprites medbots :D

**Comment by Sealed101** [comment]
medibots need a resprite very very badly and none of the latest medkit resprites modified them in any way and that's a sin

please fix

**Comment by DaydreamIQ** [comment]
Do the syndie med kits even give the bot any special upgrades like the advanced ones?

**Comment by Derpguy3** [comment]
I believe it lets the medibot treat all four damage types (I only tested with brute and oxy), not sure if it is more efficient at it, or just able to do all four.
