### ISSUE TITLE
Dead cats will still chase laser pointers

### ISSUE THREAD

**Issue by xPokee** [tgstation/tgstation#77003]
Reporting client version: 514.1589

## Round ID:
[210704](https://scrubby.melonmesa.com/round/210704)

## Reproduction:
Kill a cat and shine a laser pointer near it. Watch in horror as even in death it still chases the dot.

**Comment by Helg2** [comment]
Did you kill a cat or a felinid?

**Comment by xPokee** [comment]
> Did you kill a cat or a felinid?

A cat, not sure if it works on felinids or not.

**Comment by Sealed101** [comment]
![изображение](https://github.com/tgstation/tgstation/assets/75863639/9a29eb63-8b33-4852-b685-fba7e1e9beaa)

i have a branch with laser pointer bullshit cleanup and you are free to smash my head with a rock if i don't open a pr on it soon
