### ISSUE TITLE
Hoods don't get removed when the hooded clothing item is removed from a body

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#77010]
Reporting client version: 514.1589

## Round ID:
[210738](https://scrubby.melonmesa.com/round/210738)

## Reproduction:
Remove the clothing item with a hood and observe the hood not get removed with the clothing item
![изображение](https://github.com/tgstation/tgstation/assets/75863639/462a2815-1735-468a-8fc2-8bbd22521928)

**Comment by Sealed101** [comment]
could be a global thing for taking it off others, could be the outfits working like shit

**Comment by mikederkan** [comment]
adding to this, monkification keeps the hood which is funny
