### ISSUE TITLE
North star "How to set up SM waste" paper misleading

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#77024]
## Reproduction:

The North Star has a paper describing how to set up the Sm waste system, stating: 
`"Decide if you want to send the gas to atmos with the Supermatter Waste To Port pump, or waste it by sending it to space with the Emergency Release Valve."`

Waste To Port is fairly simple to find, but the latter is nowhere to be seen. 

Following the pipe into atmos results in it terminating next to a bunch of pumps which do not lead to space and are unlabeled. 

Either the "Emergency Release Valve" was cut and the paper never amended, or ... something is not intuitive here.

**Comment by Peliex** [comment]
Fixed in #77089
