### ISSUE TITLE
CMO requests console on metastation is called "unknown requests console"

### ISSUE THREAD

**Issue by SapphoQueer** [tgstation/tgstation#77038]
## Round ID:
[210854](https://scrubby.melonmesa.com/round/210854)

## Reproduction:
1. Load up metastation.
2. Go to CMO requests console.

![image](https://github.com/tgstation/tgstation/assets/94389951/568ce5e2-cc24-4f49-a903-3257cc09404b)

Side effect of this issue is that announcements from it come out as "Unknown Announcement"
![image](https://github.com/tgstation/tgstation/assets/94389951/61b783c3-2a76-4f66-bb12-bd1cbfc5c2c2)

**Comment by Sealed101** [comment]
yeah it doesn't have `department` and `name` set like other consoles do
![изображение](https://github.com/tgstation/tgstation/assets/75863639/ce279095-b83a-4db8-b2ed-a3da6e461b4d)
![изображение](https://github.com/tgstation/tgstation/assets/75863639/7dc1e6af-0b50-4776-af77-9360086bd921)

**Comment by distributivgesetz** [comment]
this is a custom type instead of edited vars preferably
