### ISSUE TITLE
fully augmented people are not ashstorm or space immune

### ISSUE THREAD

**Issue by D4C-420** [tgstation/tgstation#77033]
## Reproduction:

1. get fully augmented
2. walk into space/ash storm
3. start to take cold damage from space / burn damage from the ash storm
4. cry

likely caused by #76817 not accounting for temp and only pressure damage and also completely ignoring ash storms existing

**Comment by Sealed101** [comment]
marking as oversight cuz space immunity was expected to not have been changed as per PR discussion, and weather immunity was not brought up. both should be preserved

**Comment by timothymtorres** [comment]
Related to #48846

**Comment by Time-Green** [comment]
scammed

**Comment by erik30015** [comment]
This is worsened because you cant unhusk fully augmented people, tough that might be an issue of its own
