### ISSUE TITLE
`bad index` runtimes in `/atom/proc/bitmask_smooth` presumably during lazyloading templates

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#77040]
## Round ID:
[runtimes moth fans link for affected rounds](https://runtimes.moth.fans/runtime/bad%20index_______%2Fatom%2Fproc%2Fbitmask_smooth)

### quick examples:
- [210826](https://tgstation13.download/parsed-logs/terry/data/logs/2023/07/23/round-210826/)
- [210379](https://tgstation13.download/parsed-logs/terry/data/logs/2023/07/16/round-210379/)
- [210682](https://tgstation13.download/parsed-logs/manuel/data/logs/2023/07/21/round-210682/)
- [210726](https://tgstation13.download/parsed-logs/sybil/data/logs/2023/07/21/round-210726/)

## Runtimes:
```dm
[2023-07-23 02:04:47.873] RUNTIME: runtime error: bad index
 - proc name: bitmask smooth (/atom/proc/bitmask_smooth)
 -   source file: code/__HELPERS/icon_smoothing.dm,447
 -   usr: null
 -   src: the wall (188,43,6) (/turf/closed/indestructible/riveted)
 -   call stack:
 - the wall (188,43,6) (/turf/closed/indestructible/riveted): bitmask smooth()
 - the wall (188,43,6) (/turf/closed/indestructible/riveted): smooth icon()
 - Icon Smoothing (/datum/controller/subsystem/icon_smooth): fire(0)
 - Icon Smoothing (/datum/controller/subsystem/icon_smooth): ignite(0)
 - Master (/datum/controller/master): RunQueue()
 - Master (/datum/controller/master): Loop(2)
 - Master (/datum/controller/master): StartProcessing(0)
```

Judging by the specific turfs being smoothed (indestructible, syndicate, weeb) and the containment of those runtimes to one or two zlevels, I'd wager these all pop up during template lazyloading of CentCom/Syndicate Base & Hostage drop-off areas

https://github.com/tgstation/tgstation/blob/b488a846a1b469803bbc2cfca7b5621cfd4559ac/code/__HELPERS/icon_smoothing.dm#L363-L480

**Comment by MrStonedOne** [comment]
I'd suggest against playing guessing game.

Step 1 would be to Unroll the huge mess of defines into proper procs to get a more exact line number of where the runtime is actually coming from. right now line 447 includes like ~75 lines of defines in one "code" line. This can be a test merge pr if the runtime can't be repoed on local test.

Step 2: 9 times out of 10 step 2 becomes super obvious once you find out what list is being iterated over to trigger the bad index runtime. (which normally means the list is null)

a quick skim thru the code for list accesses without any null checking found one source.

```dm
#define CAN_DIAGONAL_SMOOTH(border_obj, target, direction) (\
	(target.smoothing_flags & SMOOTH_BORDER_OBJECT) ? \
		GLOB.adjacent_direction_lookup[border_obj.dir][direction + 1]?[target.dir] : \
		(GLOB.adjacent_direction_lookup[border_obj.dir][direction + 1]) ? turn(direction, 180) : NONE \
	)
```
if `border_obj` or `target` have non-cardinal `dir`s those list accesses will fail. only the middle of the 3 has null checking and only cardinal directions have sublists, the rest are nulls.

**Comment by LemonInTheDark** [comment]
border objects are expected (perhaps improperly) to have cardinal dirs. targets are allowed non cardinals since we never access a sublist off them. 
Issue here was with attempting to smooth with uninit'd objects

![image](https://github.com/tgstation/tgstation/assets/58055496/07de94b0-f904-4f92-a796-e4c2ea08ca3f)
