### ISSUE TITLE
Players stop being dense sometimes, can move through players on combat mode, are more difficult to shoot

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#77041]
Reporting client version: 514.1589

## Round ID:
[210873](https://scrubby.melonmesa.com/round/210873)

## Reproduction:

Spawn yourself in, and spawn a friend /human (you can do this with another player or a soulless mob but you will need to switch to it at some point).  I will call these mobs "you" and "other"
Have You aggressive grab Other, and have Other drag themselves to you (swapping souls if necessary) - this creates the piggy back situation
Give You the skittish trait and spawn an open crate
Skittish dive into the crate while the Other is still piggybacked, you will drop them

Now, shoot a gun through the Other, not directly clicking on them but a tile behind them ; the bullet will travel through them as if they are immaterial.
Note that direct targetted shots, i.e. clicking on the mob directly, will still hit them (though not hugely tested how them moving around influences this)

**Comment by Sealed101** [comment]
iirc piggybacking makes the rider phased out, so it seems like the skittish doesn't properly clean up the exit of the riser from the carbon uh steed that's diving into a crate

**Comment by Jacquerel** [comment]
![image](https://github.com/tgstation/tgstation/assets/7483112/981c57ed-12e5-4925-8ce9-3b896673cae5)

Also occured on round 211176 for player ckey "KickPaw", probably by accident.
This is almost certainly related to the trait "TRAIT_UNDENSE" (introduced in #76704) as admins have reported it being present on effected players, and resolved by removing the trait manually.

Some source or sources of this trait do not clean themselves up correctly, piggyback rides and crates with skittish have been mentioned as causes.

Unfortunately, the nature of this bug tends to mean that people don't notice it has happened immediately, so it's quite possible there are other causes too which people found harder to identify.
