### ISSUE TITLE
Mafia minigame chaplain bug

### ISSUE THREAD

**Issue by Papersmiles** [tgstation/tgstation#77042]
## Reproduction: 

Join as chaplain in a mafia game. Seance a living person during the night phase. You find out their role during the next day phase even if they're alive

**Comment by distributivgesetz** [comment]
Confirmed on local

https://github.com/tgstation/tgstation/blob/ea23860332d104d908ad5db2d36f52a354e35044/code/modules/mafia/abilities/abilities.dm#L58-L70
