### ISSUE TITLE
Mulebots can steal anchored nuclear bombs/bananium bombs 

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#77052]
RoundID 210889

somehow get on the nukie shuttle, mulebot can load the anchored nuke and take it to the supermatter, super cucking the nukies

**Comment by ShizCalev** [comment]
![image](https://github.com/tgstation/tgstation/assets/6209658/48a785be-c158-4f00-a91c-964ba7b8cfc8)
???

you sure it was anchored?

**Comment by trexter5555** [comment]
pretty sure, disk holder was on the station and far away from the nukie ship. unless it was manually unanchored by an admin or something, the mulebot picked it up while it was anchored

**Comment by distributivgesetz** [comment]
needs confirming if it works with anchored nukes, because being able to take an armed nuke and throw it in the SM is pretty bad

**Comment by Helg2** [comment]
Doesn't work for me

**Comment by Jacquerel** [comment]
> Doesn't work for me And it just buzzes if you try to lift banana bomb

I think you have to hack the load sensor first.
Regardless, I could not replicate this either. I suspect that the nuke simply wasn't anchored?

**Comment by trexter5555** [comment]
okay i think i found the issue, roundstart clownops bananium nuke doesnt start off anchored for some reason (round 211344)
