### ISSUE TITLE
Unwired APCs on MetaStation

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#77064]
## Round ID: [210839](https://scrubby.melonmesa.com/round/210839)

APCs lack wiring (they have a terminal just no wires leading to it).
* Shared Engineering Storage
* Recreation Area
* Fitness Room

## Testmerges:

None

**Comment by Peliex** [comment]
Fixed in #77072

**Comment by distributivgesetz** [comment]
shhshhhh
