### ISSUE TITLE
Automated IV drips seems broken. 

### ISSUE THREAD

**Issue by PeriodicChaos** [tgstation/tgstation#77115]
## Reproduction:

Try to use the IV trips to store chemicals via pipes. then find out nothing from the pipes are coming in

![image](https://github.com/tgstation/tgstation/assets/44913068/0ede544b-b58d-4cfe-8400-469de9a603cd)

![image](https://github.com/tgstation/tgstation/assets/44913068/d931d562-c606-43f7-bbcc-3c705b26c348)

**Comment by DustanHache** [comment]
the issue is that plumbing IVs don’t store chems unless you are drawing blood. if you leave it hooked up to a plumbing network and attach it to someone, it will pump them full of chems from that network.

**Comment by Sealed101** [comment]
that looks like an oversight then

**Comment by Time-Green** [comment]
> that looks like an oversight then

Not an oversight. IV's have one storage tank, if we both draw and inject from the same tank, we'd just inject our own blood. That's clumsy, so this is the compromise. I believe the description states how it works

**Comment by Time-Green** [comment]
It should probably be changed with an internal beaker or something, but it's not a bug

**Comment by PeriodicChaos** [comment]
> that looks like an oversight then

I also forgot to say when i connected it to me my blood did not go up
