### ISSUE TITLE
Labs on Nukeops base can be opened without key

### ISSUE THREAD

**Issue by antropod** [tgstation/tgstation#77112]
## Round ID: [211034](https://scrubby.melonmesa.com/round/211034)

There are 3 labs on Nuclear Operatives base - chemistry, botany and toxins.
To open them you need to purchase a key from your uplink.
Those doors can be opened without a key if you simply fireman carry your teammate and walk into a door.

## Reproduction:

Fireman carry teammate, walk into a door of a lab.

**Comment by Sealed101** [comment]
incredible
some `Bump()` fuckery obviously but fireman carrying is just janky yet again
