### ISSUE TITLE
Nobreath from heretic (and possibly other sources) causes oxyloss to be permanent rather than clearing gradually/instantly

### ISSUE THREAD

**Issue by DustanHache** [tgstation/tgstation#77127]
## Round ID:
[211071](https://scrubby.melonmesa.com/round/211071)

## Testmerges:
N/A

## Reproduction:
1: Be void heretic with aristocrats way
2: get injured, drink helbital
3: drop into oxycrit (knockout when oxyloss goes above 50
4: get busted while being unconcious for 20 straight minutes.

**Comment by distributivgesetz** [comment]
https://github.com/tgstation/tgstation/blob/26eac054d7ccc10556930a57ab5d1317a21eef4f/code/modules/mob/living/carbon/life.dm#L141-L151
oxygen damage does not heal because `TRAIT_NOBREATH` early returns, arguably a feature working as intended but no natural oxyhealing is a problem
