### ISSUE TITLE
Successful revival surgery doesn't mark complete

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#77135]
## Reproduction:

Perform revival surgery on a mob
After the successful defib the mob is alive and fine
Surgery isn't marked complete, allows you to keep defibbing (does nothing)
Additional defibs give the defib fail message, but wrong reason. It fails because the patient is alive, not because it failed to revive.

![image](https://github.com/tgstation/tgstation/assets/83487515/f81abbaf-6b64-4d51-bc38-17a7a07c4347)

**Comment by JohnFulpWillard** [comment]
It is fine to not mark as complete in case the patient dies again after, not having to re-do the whole surgery each failure would make the surgery even more of a hassle. Best option would be to prevent the step from working if the patient is alive.

**Comment by TheVekter** [comment]
I'm closing this as not planned given that the fix would probably be more annoying than the current state.
