### ISSUE TITLE
Detective's Revolver Not reloading properly.

### ISSUE THREAD

**Issue by M1xm1** [tgstation/tgstation#77132]
Reporting client version: 514.1589

## Round ID:
[211069](https://scrubby.melonmesa.com/round/211069)

## Reproduction:
Issue: Everytime Det's .38 revolver Gets reloaded , Its maximum number of bullets it can hold decreases till it doesnt take anymore bullets in it,

Steps:
1-Shoot my det's .38 revolver to empty its chamber
2-reload it using Quickloader.

Results Expected:
Fully loaded .38 revolver with 6 Bullets in it

actual result:
Chamber only Loaded with 5 Bullets instead and the quickloader left with one bullet in it., that decreases even more everytime i reload. 

Example:
I shoot a cultist six times which means i emptied my revolver's chamber on him, Grabbed another quick loader and loaded only 5 bullets instead of six, another cultist shows up , shooted him 5 times, Grabbed another quickloader and loaded only 4 Bullets and so it goes like this till i cant load anymore bullets and the Weapon is mostly useless.

**Comment by blackdav123** [comment]
same thing happened to me with a syndie revolver

**Comment by cnleth** [comment]
#76681

**Comment by Sealed101** [comment]
^
