### ISSUE TITLE
Getting stamina damage and using the MOD timeline jumper module afterwards makes you have that stamina damage until you receive more stamina damage

### ISSUE THREAD

**Issue by cnleth** [tgstation/tgstation#77152]
## Round ID:
N/A, local

## Testmerges:
N/A

## Reproduction:
Spawn chrono legionnaire equipment, hit yourself with a baton or shoot yourself with a disabler, then use the timeline jumper module to go into a jaunt. Your stamina stops regenerating and View Variables shows that you have 0 stamina damage. Being in stamcrit before jaunting leaves you in stamcrit indefinitely. Dealing more stamina damage normally or through VV after unjaunting makes stamina regenerate again.

**Comment by MrMelbert** [comment]
https://github.com/tgstation/tgstation/blob/d9c8bd9baef65a537ad236133a2e6aff4416b3cc/code/modules/mod/modules/modules_timeline.dm#L175-L176

Very simple fix, remove the second `0` from `setStaminaLoss`
