### ISSUE TITLE
Circuits are way too expensive in the module duplicator.

### ISSUE THREAD

**Issue by Terra1** [tgstation/tgstation#77158]
## Round ID:

[211137](https://scrubby.melonmesa.com/round/211137)

## Testmerges:

None as far as I can tell.

## Reproduction:

Make a circuit. Put it into a module duplicator. It will be extremely overpriced compared to the cost of remaking it from scratch.

**Comment by ExcessiveUseOfCobblestone** [comment]
Is this not intended or something

**Comment by Terra1** [comment]
> Is this not intended or something

It seems counterproductive to make a roundstart system that's already rarely used so ridiculously expensive that attempting to produce anything on a larger-than-individual scale will instantly result in the loss of all station resources, yes.

Also, this is pretty clearly a relic of the resource cost rebalance.

**Comment by ExcessiveUseOfCobblestone** [comment]
the bottom part is definitely unintended.
