### ISSUE TITLE
Bounty console won't offer bounties, "Remove Card" won't function and must be alt-clicked.

### ISSUE THREAD

**Issue by mikederkan** [tgstation/tgstation#77182]
## Round ID:
[211198](https://scrubby.melonmesa.com/round/211198)

## Testmerges:
None

## Reproduction:
If reproduction doesn't work I'll close this, as it's probably a one off issue. Put an ID into a bounty console, (this was done on Tramstation) and try to take a bounty. Nothing will happen; no options will be displayed. Try removing your card, nothing will happen and the console itself must be alt-clicked.

**Comment by MrMelbert** [comment]
Just to confirm the computer / the area was not depowered?

**Comment by mikederkan** [comment]
> Just to confirm the computer / the area was not depowered?

Definitely powered. The interface could be interacted with, and trying to take a bounty came up with an error of some sort. Cause it can't be reproduced I'll chalk it up to a cosmic bit flip
