### ISSUE TITLE
Gorilla Gloves appear as "Gorilla Glovess" on Cargo manifests

### ISSUE THREAD

**Issue by mikederkan** [tgstation/tgstation#77183]
## Round ID:
[211183](https://scrubby.melonmesa.com/round/211183)

## Testmerges:
None

## Reproduction:
Order Gorilla Gloves, manifests will appear with error.

**Comment by TheVekter** [comment]
The number thing with sheets already has a bug report under #76802.

Typos aren't something that's generated as part of incorrect manifests so this isn't an issue with that system but a typo somewhere in code causing it.

**Comment by mikederkan** [comment]
spelling errors arent included in manifests?? TIL

**Comment by Vincent983** [comment]
strange, I just ordered gorilla gloves on a private server to test this, looked at the manifest, it didn't include the typo

**Comment by Vincent983** [comment]
![image](https://github.com/tgstation/tgstation/assets/124026007/3c481f96-7433-4cad-81d9-996a2ad21fc7)
