### ISSUE TITLE
Foam Darts can embed

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#77187]
Reporting client version: 514.1589

## Round ID:
[211221](https://scrubby.melonmesa.com/round/211221)

## Testmerges:
- [Add leash component to pAIs that keeps them within range instead of directly teleporting them back, increases default range to max range](https://www.github.com/tgstation/tgstation/pull/77030)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/12635164/3220c524-a747-4f41-b170-cf85ed04de5c)
get illegal tech from a random supply pod
print a bunch of donk weaponry
get regular foam darts, freshly bought from the vendor, embedded in you, causing bleeding etc.

NOT sure if they actually cause bloodloss but you definitely bleed everywhere

**Comment by Helg2** [comment]
Doesn't regular foam darts also embed?
