### ISSUE TITLE
Putting dead kittens in an evidence bag

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#77197]
Schrodinger
![obraz](https://github.com/tgstation/tgstation/assets/68878861/4e08e7bb-4ed6-478c-98fe-01523270e1ee)

## Round ID:
[211249](https://scrubby.melonmesa.com/round/211249)

## Testmerges:
null

## Reproduction:
First, someone made a bag, that looked like it had a dead kitten inside, but was in fact, empty. It cleared when something else was inserted.

In an attempt to reproduce this, I got the exact opposite effect - a bag that looked empty, but I could infinitely pull out non-existant kittens out of it.

**Comment by TheVekter** [comment]
Why a fucking dead cat
