### ISSUE TITLE
Pai's in simplebots that die get sent back to the lobby (after disconnecting)

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#77213]
Reporting client version: 514.1589

## Round ID:
[211312](https://scrubby.melonmesa.com/round/211312)

## Reproduction:

Spawn a pai card
Have a friend drop into it
Take a clean bot, unlock it and open its maintenance panel
Shove the pai in
Murder the cleanbot
Other player gets disconnected, on reconnect they are in the lobby

**Comment by Jacquerel** [comment]
```
CRASH("get_language_holder() called on a QDELing atom, \
			this will try to re-instantiate the language holder that's about to be deleted, which is bad.")
```

This is triggered by `transfer_to` from the pai's mind when it is transferring out of a deleting bot, interrupts the rest of the mind transfer and presumably then boots the player back to the lobby.
