### ISSUE TITLE
A huge amount of items/interactions don't work/function strangely when used with telekinesis active. (Not comprehensive)

### ISSUE THREAD

**Issue by mikederkan** [tgstation/tgstation#77237]
## Round ID:
N/a 

## Testmerges:
N/a 

## Reproduction:
Too many examples to name, unsure why this wasn't on the tracker.

Some items have very cool interactions, like being able to detonate a grenade at a distance or hurl a locker across the room. As far as I can surmise, any item with a direct interaction will function, but any item that opens a menu will not. Eg; signallers, C4, TTVs. However, items interacting with OTHER items that open a menu function fine - like using a multitool on a grenade.
Wound analyzers are especially strange in that they can report health from a distance and will teleport underneath you if used too often.
Fire Axe cabinets can be unlocked with a multitool and flipped open, but the fireaxe cannot be removed - the telekinesis will only give right click reactions.
Slapcrafting that places items inhand (like wrapping cloth around a shard) will teleport through walls, or even cameras, to appear in hand, or beneath you if your hands are occupied.

(is being able to interact with consoles if they're in line of sight a bug, or a very interesting feature?

**Comment by Sealed101** [comment]
not all items have tk interactivity or tk restrictions. this would have to be explored in detail for every instance to pinpoint what's a bug and what's just being blocked
the three specific things mentioned in the report are oversights however. console interaction is a feature.
