### ISSUE TITLE
The Russian Revolver can be fired at other players if used with Telekinesis

### ISSUE THREAD

**Issue by mikederkan** [tgstation/tgstation#77238]
## Round ID:
N/A

## Testmerges:
N/A 

## Reproduction:
Put a russian revolver somewhere, with you some distance away. Have someone, something, anything stand between the revolver and you. Telekinesis the revolver and fire at yourself, aiming at any bodyzone EXCEPT your head. The bullet will fire directly into them.

Minorly, the revolver will not make any sound or give any feedback when being spun up with telekinesis. The revolver also seems to prevent continuous firing when used with Telekinesis (thank GOD), compared to using it in hand.

What's even stranger is that if the revolver is pointed at one's head, it will instantly travel through anything to kill you. Glass will be shattered, walls will have a bullethole, and in a few test cases people have had the bullet cleave their head open and instantly put them into crit. But, no matter what, the revolve rwill always instantly kill whoever is using it.

**Comment by Sealed101** [comment]
we love/hate TK

**Comment by ArcaneDefence** [comment]
I just hate tk.

**Comment by Sealed101** [comment]
we need to chain fikou to the PC to make him rework tk into the gravity gun trust me it will work great

**Comment by ZAMODA** [comment]
I feel like we should keep this interaction around with a traitor item of some sort.

**Comment by Arturlang** [comment]
Leave it in but make it guaranteed to kill the TK man, just that there might be collateral damage. It'll be funny
