### ISSUE TITLE
Rapid part exchange device (not a bluespace one) does not upgrade machines or check what parts are inside 

### ISSUE THREAD

**Issue by LikesGreen** [tgstation/tgstation#77247]
## Reproduction:

Make rapid part exchange device (normal one, not bluespace one)
Fill it with higher tier parts
Try to upgrade machines that have lower parts tier (tested on lathe and exofab), realized nothing happen when you left click on open machine (it does not upgrade it nor show what is inside)

However building machine from scratch with it works.

**Comment by Inari-Whitebear** [comment]
It doesn't even give the message of what the machine contains already, so it feels like the interaction as a whole fails, not just the replacing.
