### ISSUE TITLE
Recoloring clothes in a vendor gives a bluescreen or a blank tgUI window

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#77246]
The nightmare was kind enough to guest star in the screenshot.
![obraz](https://github.com/tgstation/tgstation/assets/68878861/d2ccbf88-0847-4507-b902-e25dbbf8684f)

## Round ID:
[211403](https://scrubby.melonmesa.com/round/211403)

## Testmerges:
nuh uh

## Reproduction:
Open a vendor. Find something that has a button, with a palette icon. Click. Observe.
Fixing chat/refreshing tgUI did not help

Users in OOC reported the same.

**Comment by AdipemDragon** [comment]
![image](https://github.com/tgstation/tgstation/assets/76874615/217af8e5-3af5-493b-a20a-b72a832801e0)
I have a more full screenie of it happening, if it helps
