### ISSUE TITLE
Suicide with a scythe generates a random head, not your own head

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#77256]
Reporting client version: 514.1589

## Round ID:
[211423](https://scrubby.melonmesa.com/round/211423)

## Testmerges:
- [Improved PDA Direct Messenger](https://www.github.com/tgstation/tgstation/pull/75820)
- [Improves the RPG loot wizard event.](https://www.github.com/tgstation/tgstation/pull/77218)

## Reproduction:
Committing suicide with a scythe has you chop off your head. Doing so seems to generate a new, random head, instead of removing yours and dropping it on the floor - As Grey Gray the mime, I did so, and the head was named Alexander Moore.

**Comment by Jacquerel** [comment]
I cannot replicate this, did anything else notable happen to you before commiting suicide?

**Comment by Jacquerel** [comment]
From the logs of that round:
```
Eethir/(Vinny King) stung Ouroborus113/(Grey Gray) with transformation sting new identity is 'Alexander Moore' (NEWHP: 100) 
```
