### ISSUE TITLE
refined anomaly cores sorta function like signalers

### ISSUE THREAD

**Issue by InsaneTGplayer** [tgstation/tgstation#77290]
## Round ID:
does not matter

## Testmerges:
does not matter

## Reproduction:
1. Refine anomaly core
2. Interact with a signaler/other refined anomaly core
3. 'frequency and signaling code from first anomaly core linked to second anomaly core'
Not only that, you can also secure anomaly cores to other stuff / other anomaly cores, which does absolutely nothing aside save a little bit of space in your inventory

**Comment by Sealed101** [comment]
they are an assembly item and this property isn't used anywhere i think? unless anomaly defusal is what uses that. either a holdover from some very old feature or someone was lazy. not really an issue though

**Comment by Jacquerel** [comment]
This is less a bug than some kind of feature nobody bothered to implement? I have no idea what the original intention was.

**Comment by Sealed101** [comment]
yeah no anomalies just use those to be stabilized
https://github.com/tgstation/tgstation/blob/f1b0ef0ff900e4bc06353885d16da58070349362/code/modules/research/anomaly/anomaly_core.dm#L12-L26

which by incident also means that if one were to suicide-eat the raw anomaly core, slide under an active anomaly then signal the frequency of the suicide-eaten, the anomaly would be neutralized. hilarious

**Comment by TheVekter** [comment]
This is a consequence of how they're coded. Someone might eventually want to add a way to suppress the signaler UI that comes up but nobody's bothered to do it in the past.

Going to close this one up.
