### ISSUE TITLE
Light fixtures always seem turned off

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#77296]
Reporting client version: 514.1589

## Round ID:
[211574](https://scrubby.melonmesa.com/round/211574)

## Testmerges:
- [Improved PDA Direct Messenger](https://www.github.com/tgstation/tgstation/pull/75820)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/62606051/bd264feb-379e-4b36-ae84-280077b18334)
This light is on, but there's not really an indication that its emitting light at all

**Comment by SyncIt21** [comment]
@Sealed101 this was fixed with #77594?

**Comment by Sealed101** [comment]
that our the emissives
