### ISSUE TITLE
opening the GAGs menu for re-coloring vendor clothes causes an NTOS error, making it impossible to re-color clothes.

### ISSUE THREAD

**Issue by Donglesplonge** [tgstation/tgstation#77305]
## Round ID:
[211408](https://scrubby.melonmesa.com/round/211408)

211579

## Testmerges:

#75820: 'Improved PDA Direct Messenger' by distributivgesetz at commit 60bf3f1cd3

## Reproduction:

1. walk up to a ClothesMate and attempt to, for instance, open the GAGs recolor menu for the hawaiian print shirt 

2. immediately be met with an NTOS error, preventing you from using the GAGs menu at all

![image](https://github.com/tgstation/tgstation/assets/120208006/96e40543-5d2c-4097-b039-7e34e7a0342b)

![image](https://github.com/tgstation/tgstation/assets/120208006/8264ce40-d66a-4614-b1f5-7af764260c12)

two images of runtimes brought on by this to help, image taken from scrubby of both the rounds.

i tried to re-create it on localhost and couldn't get it to work with a fully updated fresh branch, so i can't really grab a screencap of the NTOS error, but i'm sure it'll probably happen on a live server again, as i also saw someone else asking if the color menu was broken during round-end yesterday

**Comment by SyncIt21** [comment]
This was fixed by #77208. Wait for the servers to update and try again later, because it works locally

**Comment by Donglesplonge** [comment]
yeah i guess i missed it somehow when looking if anyone else had already reported/fixed it 

thanks for the heads-up
