### ISSUE TITLE
spell burger appears twice in crafting menu

### ISSUE THREAD

**Issue by michaelsmetsker2** [tgstation/tgstation#77301]
Reporting client version: 514.1589

## Round ID:
[211579](https://scrubby.melonmesa.com/round/211579)

## Testmerges:
- [Improved PDA Direct Messenger](https://www.github.com/tgstation/tgstation/pull/75820)

## Reproduction:

spell burger appears twice in the crafting menu

**Comment by Sealed101** [comment]
back on your supercook quest, eh?

**Comment by michaelsmetsker2** [comment]
> back on your supercook quest, eh?

yeah, stopped playing for a while
