### ISSUE TITLE
New messaging servers take far longer than 15 minutes to come online.

### ISSUE THREAD

**Issue by YehnBeep** [tgstation/tgstation#77313]
## Reproduction:

1. Start the game, and ideally enter the round as a job with easy access to telecomms.
2. Deconstruct the messaging server via screwdriver -> crowbar. (Alternatively, load a map with no telecomms and build from scratch - as this is how I first noticed this).
3. Rebuild, making sure to link and configure the machine.
4. Set a timer for 15 minutes.
5. Note that after 15 minutes, the messaging server is still not online (and lacks the green icon indicating such on its sprite). (As far as I can tell, it takes many hours - though it will _eventually_ come online.).

**Comment by distributivgesetz** [comment]
Tested it, was ~16 minutes of calibration time

**Comment by Sealed101** [comment]
so is it not an issue or is the overlay not updating in time?

**Comment by YehnBeep** [comment]
Sorry about misunderstanding the issue
