### ISSUE TITLE
The barman book is broken.

### ISSUE THREAD

**Issue by plutori** [tgstation/tgstation#77315]
Reporting client version: 514.1589

## Round ID:
[211612](https://scrubby.melonmesa.com/round/211612)

## Testmerges:
- [Screentip images](https://www.github.com/tgstation/tgstation/pull/76889)
- [Improved PDA Direct Messenger](https://www.github.com/tgstation/tgstation/pull/75820)
- [Foodening](https://www.github.com/tgstation/tgstation/pull/76205)
- [Try waiting for db queries to finish during db shutdown](https://www.github.com/tgstation/tgstation/pull/77311)

## Reproduction: The book "Barman Recipes: Mixing Drinks and Changing Lives", when read, produces nothing but a bunch of script, instead of the intended list of bar recipes. The "Throwing drinks without them breaking or spilling" effect works as normal.

1. Literally just get the book and start reading it.

**Comment by AdipemDragon** [comment]
not just that, basically all the guide books are broken
