### ISSUE TITLE
A gun in stun mode turns lethal when put inside an emitter.

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#77321]
![obraz](https://github.com/tgstation/tgstation/assets/68878861/80a82a01-6bd4-40b6-a1ad-ae2e56dde54b)
![obraz](https://github.com/tgstation/tgstation/assets/68878861/f5bbf3b2-9f9d-4584-9747-288185f8fcd9)
![obraz](https://github.com/tgstation/tgstation/assets/68878861/4aecc7c8-fdaf-4d59-83a9-865747ed95e8)
![obraz](https://github.com/tgstation/tgstation/assets/68878861/a5088167-5a23-42bf-9df7-dd064c2449c8)
(If this worked properly, you could, for instance put them in the HoP line)

## Round ID:
[211626](https://scrubby.melonmesa.com/round/211626)

## Testmerges:
#77309 

## Reproduction:
Emitters can have various energy and laser guns installed in them, if their panel is open.
This changes the emitter's laser shots to the projectiles of the gun inserted.

Guns with both stun and a kill mode will default to kill.

**Comment by Likteer** [comment]
@Sealed101 Turns out this is not a bug, Livrah pointed out the other wire in the emitter changes modes on pulsing.

Minor issue discovered that you need to use your hand or an attachable device to reach the wiring, cause clicking with multitool will try to default to changing layers.

**Comment by Sealed101** [comment]
i'll keep that in mind, thanks
