### ISSUE TITLE
The dynamic lorentz curve is incorrect

### ISSUE THREAD

**Issue by PowerfulBacon** [tgstation/tgstation#77329]
The dynamic lorentz curve seems to be slightly wrong and gives is a many-to-one function.
https://github.com/tgstation/tgstation/blob/db5b78fda78d00114178952ff442eef994a33773/code/game/gamemodes/dynamic/dynamic.dm#L839C32-L839C32
This gives the following curve:
![image](https://github.com/tgstation/tgstation/assets/26465327/61f492ac-0908-4ac6-a72a-4dbe777a7dae)

To get a nice curve, the function
```
/datum/game_mode/dynamic/proc/lorentz_to_amount(x)
	switch (x)
		if (-INFINITY to -20)
			return rand(0, 10)
		if (-20 to -10)
			return RULE_OF_THREE(1, 1, x) + 30
		if (-10 to -5)
			return RULE_OF_THREE(2, 1, x) + 40
		if (-5 to -2.5)
			return RULE_OF_THREE(3, 1, x) + 45
		if (-2.5 to -0)
			return RULE_OF_THREE(5, 1, x) + 50
		if (0 to 2.5)
			return RULE_OF_THREE(5, 1, x) + 50
		if (2.5 to 5)
			return RULE_OF_THREE(3, 1, x) + 45
		if (5 to 10)
			return RULE_OF_THREE(2, 1, x) + 40
		if (10 to 20)
			return RULE_OF_THREE(1, 1, x) + 30
		if (20 to INFINITY)
			return rand(90, 100)
```
will give us this instead:
![image](https://github.com/tgstation/tgstation/assets/26465327/97fd1e5f-a25b-45cb-98d3-bfdc8ded6c94)

Having this as a one-to-one function is very useful as it allows us to take the inverse of the function, which allows for building a probability function of dynamic threat levels allowing developers to reason about dynamic just a little bit easier.

**Comment by optimumtact** [comment]
@Mothblocks

**Comment by Mothblocks** [comment]
yeah this is ported from vg and its silly

**Comment by Ghommie** [comment]
Is there a reason this crude approximation should be used in place of the LORENTZ_CUMULATIVE_DISTRIBUTION macro?
