### ISSUE TITLE
Issue with heritics loosing their Heritic heart and info

### ISSUE THREAD

**Issue by Mike-Mofless** [tgstation/tgstation#77337]
## Round ID: [211663]

Issue with heritics loosing their heritic hearts and info, also heritics can still draw runes and use their mantis grasp inside of the simulation.

**Comment by MrMelbert** [comment]
Needs more information

In what situation are heretics losing their hearts / info

**Comment by cnleth** [comment]
In the specified round #77259 was testmerged and the player who reported this was a heretic bitrunner, so maybe the issue is that heretics lose their living heart when entering/leaving the simulation?

**Comment by Sealed101** [comment]
i'd wager that was the case yeah

**Comment by Mike-Mofless** [comment]
Yeah, whenever you enter the simulation you loose your heart.
