### ISSUE TITLE
Spaceman thinks a corpse is alive

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#77332]
Reporting client version: 514.1589

## Round ID:
[211639](https://scrubby.melonmesa.com/round/211639)

## Testmerges:
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/76874615/2f47e37b-b4b3-4051-94af-c7763c56dbad)
Or at least, the roundstart dead ones.

**Comment by Jacquerel** [comment]
What's the part of this which is a bug?

**Comment by AdipemDragon** [comment]
trying to shake up a brainless roundstart corpse as if they're just alive and unconcious, 
when doing so on like, a regular person corpse would just give a "this person is dead" text instead
