### ISSUE TITLE
Lipolicide causes damage to avoid critical condition

### ISSUE THREAD

**Issue by Crimsonerva** [tgstation/tgstation#77336]
Reporting client version: 514.1589

## Round ID:
[211657](https://scrubby.melonmesa.com/round/211657)

## Testmerges:
- [Screentip images](https://www.github.com/tgstation/tgstation/pull/76889)
- [Improved PDA Direct Messenger](https://www.github.com/tgstation/tgstation/pull/75820)
- [Foodening](https://www.github.com/tgstation/tgstation/pull/76205)
- [Try waiting for db queries to finish during db shutdown](https://www.github.com/tgstation/tgstation/pull/77311)

## Reproduction:

1. Be fat
2. Take lipolicide
3. Continue dosing yourself even after you're no longer fat
4. Toxin damage will accrue, and any damage you had before will be ignored. You will continue taking toxin damage endlessly until the lipocide leaves your system. You will not be sent into critical from 100+ damage as long as you only accrue toxin damage from the lipocide.

You will instantly be sent into critical if you take any brute, burn, or cellular damage after meeting the 100 crit threshold with the toxins accrued from lipocide, otherwise you will appear perfectly healthy and not be slowed down or anything of the sort.

**Comment by Sealed101** [comment]
curious
https://github.com/tgstation/tgstation/blob/4d80c446260c06838439f46a86e69d9eb4f12e41/code/modules/reagents/chemistry/reagents/toxin_reagents.dm#L902-L907

**Comment by Vincent983** [comment]
I noticed this same thing happening in a hellfoam grenade I made, I had a fireproof sealed modsuit, and internals on, detonated the hellfoam, but took 300 burn damage and lived until I punched myself a single time and instantly died.

**Comment by carlarctg** [comment]
This happens with unholy water and eldritch water as well

**Comment by blueDev2** [comment]
> I noticed this same thing happening in a hellfoam grenade I made, I had a fireproof sealed modsuit, and internals on, detonated the hellfoam, but took 300 burn damage and lived until I punched myself a single time and instantly died.

Just to make sure, your hellfoam grenade had Napalm in it yes? I'm not familiar with the normal composition of hellfoam.
