### ISSUE TITLE
Helpful? arm spasms

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#77333]
Reporting client version: 514.1589

## Round ID:
[211639](https://scrubby.melonmesa.com/round/211639)

## Testmerges:
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/76874615/b8a91113-b00c-45b4-9dc2-16b7d83be754)
get stasis'd while waiting for a medic to help you with your brain suddently exploding
watch you chat get slowly filled with self examines as self-punching fails

**Comment by MrMelbert** [comment]
An arm spasm is literally just "forces you to click on something", and well the only thing you can really do on stasis is examine yourself. 

If someone wanted to they can add a stasis check in `/datum/status_effect/spasms/tick()` but this seems to be WAD.

**Comment by AdipemDragon** [comment]
iirc, there used to be a time when having an arm spasm while stasis'd, it Would just punch instead of this, but it might be me misremembering
