### ISSUE TITLE
Golems don't get ashstorm immunity after eating plasma

### ISSUE THREAD

**Issue by HalfPunch** [tgstation/tgstation#77349]
Reporting client version: 514.1589

## Round ID:
[211701](https://scrubby.melonmesa.com/round/211701)

## Testmerges:
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)

## Reproduction:
1. wait for ash to storm
2. eat plasma to get ashstorm immunity
3. go outside
4. die like an idiot

**Comment by Sealed101** [comment]
how fast were you dying? judging by the code it doesn't really give you full immunity to the storm damage, just a very huge burn damage modifier
https://github.com/tgstation/tgstation/blob/27d46f17173034b805d6ef064d4db31c7e34b26d/code/game/objects/items/stacks/golem_food/golem_status_effects.dm#L163-L183

it's working as intended if you were dying slower than if you'd stand under the storm as a human, but it's a bug if you were dying just as fast as a human.

**Comment by HalfPunch** [comment]
It was like 4 damage per damage tick. But that is not what wiki states it should be

"They become immune to damage from heat and high pressure and additionally at any time when they would take heat damage, that damage is converted into power for the nearest APC. It also lends golems on Lavaland immunity to ash storms." 
That is what was written on wiki page

**Comment by Sealed101** [comment]
wiki can lie if the code is broken

ash storm directly applies fire damage which ignores any fire armor unless you are fire or ash storm immune. golems should just have an ash storm immunity trait
