### ISSUE TITLE
Nobody who is alive can hear anything over comms

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#77350]
Reporting client version: 514.1589

## Round ID:
[211711](https://scrubby.melonmesa.com/round/211711)

## Testmerges:
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)
- [Improved PDA Direct Messenger](https://www.github.com/tgstation/tgstation/pull/75820)
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)

## Reproduction:

1) Say thing over radio
2) Hear what you said and what others can say

Anyone who's dead or observing can see comms fine, just alive people cannot. Replicated on both Sybil and Bagil which are running completely different TMs so it's not likely a TM issue.

**Comment by Thunder12345** [comment]
Confirmed locally as of https://github.com/tgstation/tgstation/commit/6d93f64f0e3b5ef8e5f63d546e6aababc11f3ffd

**Comment by TheVekter** [comment]
Fuck it, it goes in the book

**Comment by TheVekter** [comment]
Confirmed fixed by #77351
