### ISSUE TITLE
Baked boiled rice has no after-cook time

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#77377]
Reporting client version: 514.1589

## Round ID:
[211744](https://scrubby.melonmesa.com/round/211744)

## Testmerges:
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/76874615/e1d77f87-57ed-44db-8671-14992ab4e151)
I swear there was a very similar issue with baked bell peppers back when they were introduced that I could point at to be like "same hat" but I can't find it

**Comment by FernandoJ8** [comment]
Boiled rice doesn't have `burns_in_oven` set to true, so it gets ruined instantly. Surely we should make the baking component itself handle that var, right?
