### ISSUE TITLE
getting a limb reattached doesn't remove the mood debuff from losing it

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#77388]
Reporting client version: 514.1589

## Round ID:
[211837](https://scrubby.melonmesa.com/round/211837)

## Testmerges:
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)

## Reproduction:
get your limb blown off
reattach it
you still look angry at your missing limb

**Comment by distributivgesetz** [comment]
is this an issue? if you lost your arm but still got it back, technically youre still going to be upset that you lost it in the first place, you might not just immediately move on

**Comment by Serxule** [comment]
yeah this isnt a bug, some moodlets like this are just on a timer and arent literally based on having or not having a limb

**Comment by Inari-Whitebear** [comment]
Seems weird since the moodlet goes something like "AHH I WAS USING THAT LIMB"
If I get my limb back, sure, might've not been a great experience, but I can use it again
