### ISSUE TITLE
Stuff that can't embed is now embedding??

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#77405]
Reporting client version: 514.1589

## Round ID:
[211880](https://scrubby.melonmesa.com/round/211880)

## Testmerges:
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/62606051/2750c96c-66c2-496d-8e9e-4d4caf5e18a6)
Shoot someone with a foam pistol, they get an embed
Borg fires a gumball at someone. They get an embed
???

**Comment by cnleth** [comment]
Same issue as https://github.com/tgstation/tgstation/issues/77187 most likely

**Comment by Sealed101** [comment]
correct
