### ISSUE TITLE
Materials cannot be grinded

### ISSUE THREAD

**Issue by Crimsonerva** [tgstation/tgstation#77415]
Reporting client version: 514.1589

## Round ID:
[211954](https://scrubby.melonmesa.com/round/211954)

## Testmerges:
- [Revert "Replaces Upgraded Cybernetic Ears with two new variants "](https://www.github.com/tgstation/tgstation/pull/77351)
- [Foodening](https://www.github.com/tgstation/tgstation/pull/76205)
- [Disable Rust based url decoding and encoding overrides](https://www.github.com/tgstation/tgstation/pull/77397)

## Reproduction:

Attempt to grind plasma; met with an error message saying it fails to grind and it's placed back in storage. Nobody was able to grind it that round.

**Comment by Crimsonerva** [comment]
This was also additionally tested with a mortar & pestle; still unable to grind/pulverize

**Comment by Sealed101** [comment]
test merge bug https://github.com/tgstation/tgstation/pull/76205
