### ISSUE TITLE
All-In-One-Grinders dont work.

### ISSUE THREAD

**Issue by CopperCrow9** [tgstation/tgstation#77414]
## Testmerges: The following pull requests are currently test merged:
[#77351: 'Revert "Replaces Upgraded Cybernetic Ears with two new variants "' by ZephyrTFA at commit 5d140d8902](https://www.github.com/tgstation/tgstation/pull/77351)
[#76205: 'Foodening' by MTandi at commit bc9947ea99](https://www.github.com/tgstation/tgstation/pull/76205)
[#77397: 'Disable Rust based url decoding and encoding overrides' by optimumtact at commit 8557c4bde2](https://www.github.com/tgstation/tgstation/pull/77397)

**Comment by Sealed101** [comment]
test merge bug #76205
