### ISSUE TITLE
Meteor spam that rivals god himself

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#77433]
Reporting client version: 514.1589

## Round ID:
[212007](https://scrubby.melonmesa.com/round/212007)

## Testmerges:
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [Chen And Garry's Ice Cream: Ice Cream DLC (LIZARD APPROVED!)](https://www.github.com/tgstation/tgstation/pull/77174)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/62606051/106ccb9b-13ef-4be2-be59-9636356fe11e)
Station just got absolutely deleted by a billion meteors all of a sudden
Admins said they had no hand in causing this, so...yeah.

**Comment by LSommers** [comment]
Gameaddict07 was the person "preparing a lightshow for the shuttle", they might know what caused the fifty fucktillion meteors.

**Comment by IndieanaJones** [comment]
We have a way to summon meteors?

**Comment by Inari-Whitebear** [comment]
> Gameaddict07 was the person "preparing a lightshow for the shuttle", they might know what caused the fifty fucktillion meteors.

They were just doing a particle accelerator cannon thing, nothing to do with meteors.

Best explanation I've seen if "meteors spawn as the shuttle travels in hyperspace and pass it left/right, but the shuttle didn't leave, yet the meteors spawned"

**Comment by necromanceranne** [comment]
Yeah, okay, togopal, I guess you could call that an event.

**Comment by moocowswag** [comment]
ive had like 3 rounds where shuttle didnt properly leave within the last month, events that target shuttle are going above and beyond if they follow it to effect it on the station z level its the shuttle not leaving thats the issue.

**Comment by Dorsisdwarf** [comment]
happened again on 212145

**Comment by Inari-Whitebear** [comment]
Not sure if z-level looping is related yeah, they spawned next to the shuttle and actually started looping after tearing through the  huttle
