### ISSUE TITLE
Goliath bluespace biting

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#77449]
## Testmerges:
not sure

## Reproduction:
get a friend
get a goliath
have goliath aggro onto friend
walk into melee range of goliath
witness the goliath attack indicator pop up over friend, and watch them take damage

![image](https://github.com/tgstation/tgstation/assets/54422837/bfca4ea7-721b-4d08-92a6-9ebd5627ed86)

https://github.com/tgstation/tgstation/assets/54422837/9b722f6f-6eb0-42d0-a8b3-e982e0587bcf

**Comment by Sealed101** [comment]
lmao
