### ISSUE TITLE
mime book glows a black light when read in a dark area

### ISSUE THREAD

**Issue by murder357** [tgstation/tgstation#77441]
Reporting client version: 514.1589

## Round ID:
[212026](https://scrubby.melonmesa.com/round/212026)

## Testmerges:
- [Alert a Discord role when a new player joins](https://www.github.com/tgstation/tgstation/pull/77432)
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)

## Reproduction:

Read the mime book in a dark area and then read it again in a bright area, and it should show it. Make sure not to select anything and this may have to be done multiple times(?)

(also this is my first issue report, tell me if i did anything wrong!)

**Comment by murder357** [comment]
> you cant read books twice, its one use only, the "glows in a black light" means its already been read, this isnt a bug nor has anything to do with light

the thing is i didnt read it, i got it out, pressed z, saw it was too dark, so i went into a lighter area, pressed z again, and then it showed that message

**Comment by Serxule** [comment]
then i assume someone else read it, otherwise im not entirely sure what you'd be referring to, since that message is used when a books read.

**Comment by murder357** [comment]
> then i assume someone else read it, otherwise im not entirely sure what you'd be referring to, since that message is used when a books read.

unless the clown did some black magic on me, nobody else had the book

**Comment by Serxule** [comment]
oh, i might know what happened actually, since the mime book doesnt get read and instead is more like a nullrod (pick your item thing) it probably assumed you picked it (despite being unable to in darkness) since you had used it, so when you tried again it just considered it used even though it shouldnt exist anymore

**Comment by TheVekter** [comment]
Someone else try this and see if they can make it happen again, I don't think this is a bug.
