### ISSUE TITLE
Your random mail gifts might come pre-drank

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#77467]
Reporting client version: 514.1589

## Round ID:
[212045](https://scrubby.melonmesa.com/round/212045)

## Testmerges:
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)
- [Alert a Discord role when a new player joins](https://www.github.com/tgstation/tgstation/pull/77432)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/76874615/6cd8e645-c8a2-488e-90cc-df168e378d8a)
Be a chef (or anything), get mail
Get a bottle of something, that doesn't have a pre-made bottle (so not booze and such)
get only 30u's of the stuff

somewhere along the line, mailed custom reagent bottles just weren't given a patch with the increased bottle size, so it's just funny to imagine someone drinking half of your gift before sending it

**Comment by Helg2** [comment]
The fact that chips pack are half empty doesn't mean someone ate them before you.

**Comment by MrMelbert** [comment]
According to Mtandi a week or so it's intended bottles aren't pre-filled to limit - they bumped the max volume to 50 and didn't want to deal with the balance discussion behind increasing *every bottle*'s reagents to the new cap.

**Comment by AdipemDragon** [comment]
I mean, I just thought it looked like a forgotten value but, in that case, would it be fun to add like a 10u wiggle room for randomizing the amount (25-35) or something like that? (Yeah, yeah, "wyci") 
These's other cargo stuff that already comes in somewhat randomly that could set a precedent for this, like the chicken crate (mostly chickens, sometimes chicks, now and again just empty, not even an egg)
