### ISSUE TITLE
Bombs cause heavy stuttering

### ISSUE THREAD

**Issue by WarerBrow** [tgstation/tgstation#77463]
Reporting client version: 514.1589

## Round ID:
[212071](https://scrubby.melonmesa.com/round/212071) + round before that

## Testmerges:
- [Alert a Discord role when a new player joins](https://www.github.com/tgstation/tgstation/pull/77432)
- [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)

## Reproduction:

It just as simple as it is: bombing (I don't know if that were singletanks or TTV) causes heavy lag (Connection lost at hub, ping jumping to 2k and slow-mo movement after it ended).

It affected server the most when previous from mentioned round someone exploded several bombs at time: server was actively dying (but not completely) for about 3 minutes. 

So that would be:

1. Explode bombs (more = better)
2. Enjoy lag

**Comment by Serxule** [comment]
this isnt a bug this is just performance problems that have always existed during highpop due to TD

**Comment by MrMelbert** [comment]
> Testmerges: [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)

🤔

**Comment by Serxule** [comment]
oh wait this is intended lag and not just performance (tbf there's no difference unless you're told so)

**Comment by Mothblocks** [comment]
@MrMelbert test merge bug is meant to only be closed bugs
