### ISSUE TITLE
Mirror reflections are backwards

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#77476]
## Reproduction:
Step 1: Stand in front of mirror
Step 2: Look away from mirror
Step 3: Watch as your reflection stares at the back of your head

![EVERY MOVE YOU MAKE EVERY STEP YOU TAKE](https://github.com/tgstation/tgstation/assets/88996803/42c8a912-9b01-4b06-8b66-e0e7e328f0e5)

**Comment by Ghommie** [comment]
I'm pretty much aware of the issue. The reflection looks good when the mirror is placed west, east and south, however I couldn't find a clean way to flip the direction of the visual when the mirror is positioned north, so I threw in the towel and settled with what I managed to achieve.
There could be a way, but it'd also require for the copied appearance in the mirror to be updated at least every time the mob's sprite changes somehow, and that doesn't look very feasible atm.
