### ISSUE TITLE
Maploader does not support partial template loading

### ISSUE THREAD

**Issue by itsmeow** [tgstation/tgstation#77482]
There is a bug in the maploader, specifically this line

https://github.com/tgstation/tgstation/blob/14c3f2e829efb83b18f2cb667dc47317570ab256/code/modules/mapping/reader.dm#L346

All uses that I know of on TG don't actually have a y_starting_skip that isn't zero (aka always loading the entire map), but downstream after switching to the updated maploder from #71074, we encountered a bug with our antigrief partial map regenerator not working. The problem was that the ycrd was far too high (over 255) and so nothing would regenerate. Simple fix was just doing `-=` rather than `+=`.

I don't have time to upstream this but here is the downstream PR: https://github.com/BeeStation/BeeStation-Hornet/pull/9636

**Comment by LemonInTheDark** [comment]
yeah u right u right
