### ISSUE TITLE
Transforming into a Giant Spider gives you a persistent antag datum

### ISSUE THREAD

**Issue by Boopideedoo** [tgstation/tgstation#77501]
## Reproduction:

The way I found out this bug is I took the dna of a spider and became it to test if I could become a spider then after turning human again the spider tab stayed on my character but steps to reproduce:
1. Get the polymorph inverter and insert the bioscrambler core.
2. Grow a spider from a gold slime core or find a corpse.
3. Become said spider then turn human again once the cooldown is done.
![Bug](https://github.com/tgstation/tgstation/assets/44647111/e1db4e06-1314-4259-860e-a6b43227cb41)

**Comment by Boopideedoo** [comment]
Yes I am a carp currnetly but that spider tab dont go away

**Comment by distributivgesetz** [comment]
@Jacquerel are players supposed to get antag datums when they polymorph into basic/simplemobs?

**Comment by Jacquerel** [comment]
Some mobs just do this as a fuction of becoming them, I've been meaning to refactor spiders to stop doing it though.
Otherwise, the normal rules of "if you did it to yourself you don't become an antag" still apply, according to admins.
