### ISSUE TITLE
reagent dartgun sprite is scuffed as fuck

### ISSUE THREAD

**Issue by Vincent983** [tgstation/tgstation#77502]
## Reproduction:

1.Get reagent dartgun
2. put it in your right hand
3. look to the side
4. it's horrible

![image](https://github.com/tgstation/tgstation/assets/124026007/9293bf34-afd2-443a-a0a2-4db54c9010f6)

**Comment by distributivgesetz** [comment]
Held icon state dirs seem to be reversed
