### ISSUE TITLE
A talking mirror

### ISSUE THREAD

**Issue by timothymtorres** [tgstation/tgstation#77512]
## Round ID: 

 212220

## Reproduction:

1. Stand in front of a mirror.
2. Speak
3. See below

![dreamseeker_MTJtV4Mc0Q](https://github.com/tgstation/tgstation/assets/5195984/a3481221-82cf-4c40-b919-757c8840165d)

**Comment by Ghommie** [comment]
Duplicate of #77431, which the fix for has been merged recently.

**Comment by distributivgesetz** [comment]
Reported round happened 8 hours before the fix was merged, so we can assume this was fixed. Closing as duplicate of #77431.
