### ISSUE TITLE
Rat King rats cant follow Rat King using stairs

### ISSUE THREAD

**Issue by Cutplays** [tgstation/tgstation#77520]
Round ID:[212234](https://scrubby.melonmesa.com/round/212234)

Reproduction: Summon rats as rat king, Order rats to follow, Go up or down using a stair case,

**Comment by Jacquerel** [comment]
Currently our "follow" AI is too stupid to understand z levels. 
This isn't technically a "bug" because it's a known thing, but it'd be nice if someone took the time to add it.

**Comment by BlueMemesauce** [comment]
Same as #73664 then

**Comment by Mothblocks** [comment]
Closing as "Not a bug" is expected to be only closed issues
