### ISSUE TITLE
Directional firelocks can be walked through while closed, but only in one direction

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#77535]
Reporting client version: 514.1589

## Round ID:
[212298](https://scrubby.melonmesa.com/round/212298)

## Testmerges:
- [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)

## Reproduction:
The directional firelocks in Birdshot in the public hallway near engineering can be walked through, but only if you're walking into the space between them - IE, when coming from the north, you can walk through the northern firelocks, but get stopped by the southern ones and can't backtrack, and the same for coming from the south and walking through the southern firelocks

![MAGIC](https://github.com/tgstation/tgstation/assets/88996803/0deaee73-3b99-446f-b93f-12ef9db7feb2)

**Comment by newfren** [comment]
this is true for all directional firelocks, fyi, if you're on the same tile as them you can move through them to the tile they theoretically block
