### ISSUE TITLE
The Polymorph belt can be used to delete people

### ISSUE THREAD

**Issue by Sightld2** [tgstation/tgstation#77536]
## Reproduction:

Use polymorph belt to become gelatinous cube.
Eat unsuspecting victim
Polymorphn't

**Comment by TheVekter** [comment]
Lots of good bugs this year and we're only roughly 2/3rds of the way through

**Comment by LikesGreen** [comment]
Use belt on dead xeno, turn into xeno, eat someone, turn back, eaten victim was deleted

**Comment by TheVekter** [comment]
So it's basically vo-

**Comment by Likteer** [comment]
> eaten victim was deleted

Even as a natural beno, I've noticed corpses rapidly being deleted from me.
