### ISSUE TITLE
Cultist Keeping Fellow cultist icons after being unconverted.

### ISSUE THREAD

**Issue by Mike-Mofless** [tgstation/tgstation#77530]
## Round ID:[212250](https://scrubby.melonmesa.com/round/212250)

I spawned roundstart cultist did some cult shit got robusted husked by fire, then unhusked and revived while being fed holy water
stayed in crit for a while on a stasis bed then succumbed right before i died because they where not healing me, got fed a fuck ton more holy water, woke up out of crit after getting cpr said some shit on cult comms got fed a fuck ton MORE holy water, then got fed a holymelon that unculted me but left me with the little icons next to peoples heads (example picture below) went on to shoot the QM because i though i was in the cult still, leading to the bwoinkaning.
![image](https://github.com/tgstation/tgstation/assets/141287969/a74f5765-1119-44c9-915a-b8feafe8af17)

## Testmerges:

Dont think it was caused by any test merges
## Reproduction:

Spawn as roundstart cultist, die to fire and get husked, fed holy water the whole time revived and then fed more holy water then a holymelon

**Comment by MrMelbert** [comment]
I know why this is happening now: 

![image](https://github.com/tgstation/tgstation/assets/51863163/09801854-fa51-4075-ac6f-20dc6b164559)

![image](https://github.com/tgstation/tgstation/assets/51863163/dd58dae4-6491-44f0-a796-81d00f27a7dd)
