### ISSUE TITLE
Unable to place rods / plating on multi-Z levels with pine trees underneath

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#77540]
Reporting client version: 514.1589

## Round ID:
[212307](https://scrubby.melonmesa.com/round/212307)

## Testmerges:
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)

## Reproduction:
Stand on the upper level of a linked Z-level, with a pine tree under it. Make sure it is obscuring entirety of the upper-Z level's tile. You will be unable to place down rods on the tile.

![obrazek](https://github.com/tgstation/tgstation/assets/39193093/9bb190f3-3e9f-4ba5-9449-f43c10174e57)

**Comment by Sealed101** [comment]
feature :+1:

I'm guessing this would apply to any object under the open tile though, not jus pine trees, unless their transparent component is conflicting with something multiZ

**Comment by OverwatchVoice** [comment]
> I'm guessing this would apply to any object under the open tile though, not jus pine trees, unless their transparent component is conflicting with something multiZ

It's safe to assume any relatively large enough sprite that covers the entire tile would do this, yeah

**Comment by iwishforducks** [comment]
This happens with any kind of item/mob on the floor below. This is because your click is eaten up by the item below, and so you end up not clicking on the openspace turf, and clicking on an openspace turf is required to patch holes up.
