### ISSUE TITLE
dextrous holopara storage doesnt work

### ISSUE THREAD

**Issue by Loafin34** [tgstation/tgstation#77552]
## Round ID: [212335](https://scrubby.melonmesa.com/round/212335)

 212335

## Reproduction:

 get tarot deck, choose dextrous holopara, play as him, can't store anything.

**Comment by JohnFulpWillard** [comment]
What stuff were you able to hold in it? I messed with it for a bit and I don't think anything was able to be stored in there anyways

**Comment by san7890** [comment]
@Jacquerel is this fixed now btw

**Comment by Jacquerel** [comment]
no idea if it is fixed on live, it works in my unmerged PR #79473 once I get around to finishing the reviews

**Comment by san7890** [comment]
That's what I meant, sorry for the confusion
