### ISSUE TITLE
get_cardinal_dir() is inconsistent

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#77553]
get_cardinal_dir(a, b) proc is returning inconsistent results on repeat calls

## Reproduction:

obj1 at 79,122,3, obj2 at 72,119,3

get_cardinal_dir(obj1, obj2)

Sometimes returns 8 (West), other times 2 (South)

![image](https://github.com/tgstation/tgstation/assets/83487515/4be9eaec-dfc0-49c7-8499-ddd0f8dabf90)

**Comment by LemonInTheDark** [comment]
I uh
```
///Get the cardinal direction between two atoms
/proc/get_cardinal_dir(atom/start, atom/end)
	var/dx = abs(end.x - start.x)
	var/dy = abs(end.y - start.y)
	return get_dir(start, end) & (rand() * (dx+dy) < dy ? 3 : 12)
```
I believe this is intentional, is there a reason you believe it to not be?

**Comment by lessthnthree** [comment]
I was trying to use it to check what direction it is from a position towards a landmark. ie:

```
var/direction_to_go = get_cardinal_dir(point_a, point_b)
    switch(direction_to_go)
        if(NORTH)
            do_north_thing()
        if(SOUTH)
            do_south_thing()
        if(EAST)
            do_east_thing()
        if(WEST)
            do_west_thing()
```

If neither object is moving, I'd expect the proc to consistently return one of the four values (even if it's wrong about it)

**Comment by lessthnthree** [comment]
I don't know why you'd want to add an element of randomness to a direction calculation, but it should probably be documented that it does that.
