### ISSUE TITLE
un-deconstructable and un-openable Airlocks. 

### ISSUE THREAD

**Issue by Tw1sting** [tgstation/tgstation#77588]
Reporting client version: 514.1589

## Round ID:
[212447](https://scrubby.melonmesa.com/round/212447)

## Testmerges:
- [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)

## Reproduction:

Airlocks with status "This door does not cycle." cannot be deconstructed or fixed. Trying to deconstruct it, it says "The airlock's bolts prevent it from being forced!" when you try to pry electronics out (power is cut off). Trying to fix it by cutting-mending wires does nothing. The door becomes an obstacle and some times happened in places like cargo leaving door opened without ability to be fixed , making it a trouble for cargo workers. These doors are mostly created in round start so it occurs in regular circumstances.

**Comment by Likteer** [comment]
Cutting-mending is not enough to raise the bolts. You need to pulse the wire.

**Comment by Tw1sting** [comment]
> Cutting-mending is not enough to raise the bolts. You need to pulse the wire.

I used multitool too, pulsed every wire and nothing happened, the door has status that bolts are engaged

**Comment by Tw1sting** [comment]
> Cutting-mending is not enough to raise the bolts. You need to pulse the wire.

It's not a problem with bolts, bolts are engaged and for the pulsating, i used multitool on every wire too: nothing happened

**Comment by Inari-Whitebear** [comment]
Not sure what you mean? I've not seen roundstart bolted doors?
"Does not cycle" just means it doesn't close other airlocks when you open it.

If you pulsed every wire, maybe you pulsed the power wires before the bolt wire? If power is out("test light is off") the bolts can't be raised via pulsing wires, as they would be raised by something the requires power.

In general to pry electronics from a door you have to:
1) unbolt it, otherwise it tells you the bolts prevent it being forced
2) unpower it, otherwise it tells you the motor prevents it being forced
3) weld it shut, otherwise you just open it

If you have a depowered and bolted door, you have to either smash it, power it up to raise the bolts, or have a bolter wrench to use on it.

**Comment by Tw1sting** [comment]
> Not sure what you mean? I've not seen roundstart bolted doors? "Does not cycle" just means it doesn't close other airlocks when you open it.
> 
> If you pulsed every wire, maybe you pulsed the power wires before the bolt wire? If power is out("test light is off") the bolts can't be raised via pulsing wires, as they would be raised by something the requires power.
> 
> In general to pry electronics from a door you have to:
> 
> 1. unbolt it, otherwise it tells you the bolts prevent it being forced
> 2. unpower it, otherwise it tells you the motor prevents it being forced
> 3. weld it shut, otherwise you just open it
> 
> If you have a depowered and bolted door, you have to either smash it, power it up to raise the bolts, or have a bolter wrench to use on it.

I didn't mean i just pulsed every wire without thinking. Both times i have seen this door i was an engineer so i saw what every wire does so i tried every of them. Trying to turn power off (when its unbolted), welding it and trying to pry electronics doesn't work. The door doesn't open, you cant just open in, you cant hack it, you can't deconstruct it. I don't know if emagging it will do anything, but normal methods does not work on it.
Doors are powered, and have bolts.
The only possible way to do anything to it is to damage it till it falls apart

**Comment by Inari-Whitebear** [comment]
Which door are we talking about? Cause can't say I ever experienced that

**Comment by Tw1sting** [comment]
> Which door are we talking about? Cause can't say I ever experienced that

Door with status "This door does not cycle" when you inspect it

**Comment by Inari-Whitebear** [comment]
> > Which door are we talking about? Cause can't say I ever experienced that
> 
> Door with status "This door does not cycle" when you inspect it

Wait, door or airlock?
Becasue basically every single airlock on the station has that status

**Comment by Inari-Whitebear** [comment]
Hmm well I'd be curious to actually see this happen and figure it out, can't see how the door not cycling would be related at all sadly.

And:
![NVIDIA_Share_vo3ImYYqIz](https://github.com/tgstation/tgstation/assets/1077971/0b82dad5-a86f-4f49-b541-8075457a946a)

**Comment by Tw1sting** [comment]
> Hmm well I'd be curious to actually see this happen and figure it out, can't see how the door not cycling would be related at all sadly.
> 
> And: ![NVIDIA_Share_vo3ImYYqIz](https://user-images.githubusercontent.com/1077971/260847695-0b82dad5-a86f-4f49-b541-8075457a946a.png)

I'll check it

**Comment by Tw1sting** [comment]
Hmm, then i was wrong in the part about status. There must be something else that causes doors to not work
