### ISSUE TITLE
Using graft with Fungal Vitality, Weed Adaptation or Natural Insecticide will not give this trait to plant

### ISSUE THREAD

**Issue by HalfPunch** [tgstation/tgstation#77586]
## Reproduction:
I think it's selfexplainatory. Just graft mushroom/weed/flover try to use graft on a plant without any of these traits -> it doesn't work

**Comment by the-orange-cow** [comment]
Testmerges?  I was using these grafts less than 24 hours ago and weed adapt and natural insecticide seemed to be working properly.

I'll double check when I get off work.  Just to be clear, for the graft the plant comes from, simply having these traits isn't enough to get the trait imbued into the graft, the plant must specifically be set to give hat type of graft.  For example, most flower have natural insecticide, but only fraxnellia give it as a graft.

Also, I believe weed adapt and fungal bit can only be applied to a normal plant and have an effect, which seems to be intended.  I.e. you can't weed a mushroom or mushroom a weed.
