### ISSUE TITLE
body bags show welding tool tips in their description

### ISSUE THREAD

**Issue by Vincent983** [tgstation/tgstation#77596]
## Reproduction:
1. get a body bag
2. unfold it
3. examine it
4. what
![image](https://github.com/tgstation/tgstation/assets/124026007/2cd9c047-6d7a-4a80-b334-239a48c1ab65)

**Comment by Vincent983** [comment]
whoops, posted screenshot of the criminal capture body bag, but it shows this for the other types of body bags too

**Comment by DeerJesus** [comment]
well can it be welded shut?

**Comment by Vincent983** [comment]
nope
