### ISSUE TITLE
a immovable rod going up stairs deletes itself

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#77622]
## Round ID:
[212528](https://scrubby.melonmesa.com/round/212528)

## Testmerges:
[#77307: 'Revert "Bumps rust-g to `3.0.0` "' by MrStonedOne at commit 8dad0feceb](https://www.github.com/tgstation/tgstation/pull/77307)
[#77447: 'Trying to qdelete a callback now lags the server instead.' by MrStonedOne at commit e15efd1604](https://www.github.com/tgstation/tgstation/pull/77447)

## Reproduction:
launch a rod torwarrds stairs that go up, see tthe rod delete itself in shame

**Comment by Sealed101** [comment]
got fixed somehow; the stairs just get broken and that's about it
