### ISSUE TITLE
Cook Suits turn you into Rayman

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#77642]
Reporting client version: 514.1589

## Round ID:
[212544](https://scrubby.melonmesa.com/round/212544)

## Testmerges:
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/76874615/dec0a93f-2f83-4c85-8013-489b2ff2f957)
wear suit, adjust to be casual, turn sideways

**Comment by AdipemDragon** [comment]
it's gotta be something missed by #77558, it's the one pr that touched this recently.
which probably means this is also a problem with the other suits touched by it

**Comment by Time-Green** [comment]
I dont get it

**Comment by OrionTheFox** [comment]
The screenshot in this bug physically cannot be from after my PR, as the hat is not updated (two darker px at the bottom corners). Clear your cache.
