### ISSUE TITLE
Service Borg picking up enzyme bottle from inventory with drink claw.

### ISSUE THREAD

**Issue by Stiix72** [tgstation/tgstation#77659]
Reporting client version: 514.1589

## Round ID:
[212636](https://scrubby.melonmesa.com/round/212636)

## Testmerges:
- [MODLink System (+ NWTLMM)](https://www.github.com/tgstation/tgstation/pull/77639)
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)

## Reproduction:
Be a service borg and attempt to pick up the enzyme bottle from the inventory like you would any other bottle or glass. It is now stuck to the claw until you reset your model. Resetting the model at this point drops a bottle of enzyme that CANNOT be dropped if someone picks it up. That is all.

**Comment by Holoo-1** [comment]
same goes for engborg with its material manipulation apparatus and floortile
