### ISSUE TITLE
Exosuit typo when installing stock parts after a mech is created; Upgrading a Ripley from MK-I to MK-II deletes the servo that is installed from existence

### ISSUE THREAD

**Issue by Hotmud9** [tgstation/tgstation#77677]
(Foreword: Typo is "(such-and-such part) intalled"; should be "installed")

## Round ID: 
[212677](https://scrubby.melonmesa.com/round/212677)

## Testmerges:
N/A

## Reproduction:
Build a Ripley MK-I
Open the maintenance panel with a screwdriver
Apply Ripley MK-I to MK-II conversion kit
The micro servo is missing

**Comment by Hotmud9** [comment]
Why did pressing enter just fucking submit it

**Comment by a-reny** [comment]
Can I work on this?
