### ISSUE TITLE
Mime PDA unable to send any messages at all

### ISSUE THREAD

**Issue by Zargoar** [tgstation/tgstation#77683]
Reporting client version: 514.1589

## Round ID:
[212699](https://scrubby.melonmesa.com/round/212699)

## Testmerges:
- [MODLink System (+ NWTLMM)](https://www.github.com/tgstation/tgstation/pull/77639)
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)

## Reproduction:

1-Take mime PDA.
2-Open Messenger.
3-Attempt to send a text message.
4- Attempt to send an emoji message.
5- Attempt to send a photo message.

All functionality of the mime's messenger are broken. If a mime is going to spawn with a PDA then it should work.
PDA communication is a valuable tool in a roleplaying game and removing what few tools a mime has hurts roleplaying.
Fix this.

**Comment by Serxule** [comment]
mimes can only send emojis anyways

**Comment by distributivgesetz** [comment]
@JohnFulpWillard next time ping me on this please

**Comment by distributivgesetz** [comment]
![image](https://github.com/tgstation/tgstation/assets/47710522/afbf369d-6656-46a6-9154-e36564021c26)
i knew i had tested this, it works just fine (besides it not displaying in the UI)
