### ISSUE TITLE
Certain chemmixes can light you on fire visually forever

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#77701]
Reporting client version: 514.1589

## Round ID:
[212738](https://scrubby.melonmesa.com/round/212738)

## Testmerges:
- [MODLink System (+ NWTLMM)](https://www.github.com/tgstation/tgstation/pull/77639)
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)

## Reproduction:
Be lit on fire by chemist
Die
Be revived via ethereal crystal
Never be able to be put out
Stay visually on fire for everyone but be functionally fine

I do not know what chemmix was used, so I'm hoping you can look through the gamelogs.

**Comment by ZAMODA** [comment]
That's what it was for my experience, dude didn't reveal exactly what chems it was but he did say it had phlog in it.

**Comment by Crimsonerva** [comment]
This isn't exclusive to chemistry. You can also be lit on fire and the overlay can break from atmospherics fires. Something with fire overlays in general is broken.
