### ISSUE TITLE
Returning items to vendors don't work

### ISSUE THREAD

**Issue by JohnFulpWillard** [tgstation/tgstation#77719]
## Reproduction:

With clothing vendors

1. Go to a clothing vending machine.
2. Put its respective clothing back in (you can just buy a clothing item and put it in)
3. It gets inserted into the vending machine, but does not pop up in the UI under Returned Clothing, nor does the item in the UI show up as having the item back in stock.

The contents are moved into the vending machine, but it does not pop up on the UI.
Deconstructing it will drop it, but there's unused code saying it's meant to have its own section in the UI
![image](https://github.com/tgstation/tgstation/assets/53777086/f934e2e3-809c-4825-b25e-1032f7026bb4)

With Chef stuff

1. Go to a Food vendor
If you don't have kitchen access, you will get an Access Denied, but if you do, then
- If it's regular food, nothing happens
- If it's food that is from the vendor (or a type of food that the vendor has), then just like the clothing vendor, it will eat it, and nothing will change. Still moved to inside of the vending machine.

Video demonstration
https://github.com/tgstation/tgstation/assets/53777086/1276e1d0-8573-442c-a41d-f368b71f2e3b

**Comment by Sealed101** [comment]
related https://github.com/tgstation/tgstation/issues/68848 https://github.com/tgstation/tgstation/issues/76314
