### ISSUE TITLE
Tram exploded and gibbed me, despite not being near it. Several players elsewhere gibbed by a Tram explosion.

### ISSUE THREAD

**Issue by theSkymonster** [tgstation/tgstation#77722]
## Round ID:
[212791](https://statbus.space/rounds/212791)

## Reproduction:

Got randomly gibbed by an explosion that seems to have occurred at the same time as the Tram exploded. I was not near the Tram at the time. Other players mentioned corpses and a few other players exploding at the same time.

- Joined shift and walked onto Tram
![image](https://github.com/tgstation/tgstation/assets/118898237/ce3da5fb-94e5-4f3d-9872-526cdb33a4f0)

- Activated Tram, but it just phased through me and left me standing in place. Made a comment of disbelief
![image](https://github.com/tgstation/tgstation/assets/118898237/5129c139-763d-4a9a-a336-294ecc797e58)
![image](https://github.com/tgstation/tgstation/assets/118898237/1eb7b4e5-9845-4d5e-adbb-1e1923191bf6)

- Decided to not use the Tram from that point on, used a bluespace transit tube instead.
- Started getting random intermittent speed boosts while walking around the station, as if I were on the Tram in motion.
- Notice a couple of other people getting jerky speed boosts as well
- One player sest up field gens to destroy the tram for (fun)
- Tram explodes approaching Medbay after hitting shield wall, several people across the station explode with the same/similar force at exactly the same time:
![image](https://github.com/tgstation/tgstation/assets/118898237/09617cdf-f56e-458c-83bb-2b76b8b3d07f)

I can't really reproduce but included some of my IC comments with the approx. times of tram phasing, so if someone else who is better at log diving knows where to look to figure this out, be my guest.

Speculatory: The game thought my mob was permanently on a tram tile and therefore was giving me speed boosts when it was  moving, and also affected me with the explosion later on in the shift. 

Sorry if it's a poor submission, I don't really do this kind of thing. Was asked to by an admin in ahelp and I'm happy to do what I can.

**Comment by Sealed101** [comment]
ghost tram ghost tram ghost tram

**Comment by Dorsisdwarf** [comment]
!()[https://github.com/tgstation/tgstation/assets/7305553/130363e9-781b-45a2-b6f8-d93a622a8241]


!()[https://github.com/tgstation/tgstation/assets/7305553/b88b2e06-06b7-4a49-a5d9-32fd9bad984a]

Possibly related, on 212996 i got on a tram and it left me behind. Afterwards, every time the tram moved, i moved an equal amount in the same direction, through ALL WALLS AND BARRIERS. This lasted even across Z levels and after being admin teleported. Getting back on the tram and riding it normally fixed it.

**Comment by lessthnthree** [comment]
It's not a poor submission, don't worry. The tram doesn't leave much in the way of logs at the moment.

I'm aiming to have my refactor done this month, it will improve on that.

**Comment by TheVekter** [comment]
This is still going on and it's causing interesting affects, and by 'interesting' I mean 'quantum entangling players so that any time the tram moves they move the same distance regardless of where they are, often killing them in the process'.

**Comment by Dorsisdwarf** [comment]
i love when that effect happens its cinematic being dragged back and forth through walls screaming.

**Comment by DaxDupont** [comment]
I fucking love trams
