### ISSUE TITLE
Threat always in the -800's

### ISSUE THREAD

**Issue by DeerJesus** [tgstation/tgstation#77726]
## Round ID:

One of them was 212807 manuel.

## Testmerges:

The active merge probably causing this is https://github.com/tgstation/tgstation/pull/77460

## Reproduction:

For the four past rounds on manuel (AT LEAST) and two rounds on sybil (AT LEAST) the threat has been -800 or more. Even when it's reported as  'black orbit'.

**Comment by Isratosh** [comment]
Affected rounds 212810 and 212813 on Sybil. Revert TM on round 212814 and threat was normal.
