### ISSUE TITLE
Simple bots (or at least Firebots) have free movement in space

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#77735]
Reporting client version: 514.1589

## Round ID:
[212834](https://scrubby.melonmesa.com/round/212834)

## Testmerges:
- [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [MODLink System (+ NWTLMM)](https://www.github.com/tgstation/tgstation/pull/77639)
- [Revert "Edits a proc from dynamic.dm to use the actual cumulative formula of the Cauchy-Lorentz distribution."](https://www.github.com/tgstation/tgstation/pull/77728)

## Reproduction:
Just like it says on the tin, possessed a Firebot on Birdshot station, then went into space and had free, full movement like carp do. Not sure if that's intended behavior, but it's an upgrade for full borgs, plus it isn't mentioned anywhere. As a bonus, firebots also continuously spray out foam like a cleaner grenade in space, but that may be pressure-related and not atually an issue.

**Comment by Sealed101** [comment]
firebots are intended to have spacewalk, apparently

https://github.com/tgstation/tgstation/blob/ef3a55dd7cb39fa0e08f698074cc302ee2e745d2/code/modules/mob/living/simple_animal/bot/firebot.dm#L50-L52

foaming also seems to be the firebot reacting to atmos changes around it, and the foam is that of the firefighting variety

https://github.com/tgstation/tgstation/blob/ef3a55dd7cb39fa0e08f698074cc302ee2e745d2/code/modules/mob/living/simple_animal/bot/firebot.dm#L275-L283
