### ISSUE TITLE
double barrel won't work properly

### ISSUE THREAD

**Issue by Voudez** [tgstation/tgstation#77758]
Reporting client version: 514.1589

## Round ID:
[212912](https://scrubby.melonmesa.com/round/212912)

## Testmerges:
- [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)

## Reproduction:
-grab double barrel shotgun
-use any shotgun shells
-empty double barrel shotgun
-insert 2 shotgun shells 
-examine it 
-at this point you should notice there only 1 shell instead of 2
Double barrel shotgun broken because it literally deletes one shell, wich means it needs 3 shells totall to fill up, and it makes way complicated to use.

(its also filled only with one shell when spawned by itself (roundstart included))

**Comment by Sealed101** [comment]
ok this seems new because last month or so i was fixing double barrels improperly reloading spent shells and now this is happening, whatever this is
https://github.com/tgstation/tgstation/pull/77157 oversight? internal magazines my beloathed

**Comment by necromanceranne** [comment]
> ok this seems new because last month or so i was fixing double barrels improperly reloading spent shells and now this is happening, whatever this is #77157 oversight? internal magazines my beloathed

Testing this, I reverted my change and found that it did not in fact fix this issue. This needs further investigation. (I also am adamant I tested shotguns thoroughly given they were the other internal magazine that would have been relevant and should not have been affected by my changes)

**Comment by necromanceranne** [comment]
Testing it further, unfortunately it was this PR https://github.com/tgstation/tgstation/pull/77339 which reintroduced the bug that Sealed fixed.

**Comment by Sealed101** [comment]
sins of the father
