### ISSUE TITLE
Plumbing machines won't connect to ducts

### ISSUE THREAD

**Issue by Muffindrake** [tgstation/tgstation#77761]
## Round ID: 
[212917](https://scrubby.melonmesa.com/round/212917)

## Reproduction:
Start a round on Delta Station, place down fluid ducts. Attempt to create a plumbing machine and wrench it down, and observe it not connecting to fluid ducts. Alternatively observe existing plumbing machines that are wrenched down not connect to fluid ducts that you place down next to them.

**Comment by Sealed101** [comment]
closing in favor of #77774 because it has A PICTIRE WOW im so biased

also that picture just confirms that it's not a layering goof
