### ISSUE TITLE
some lights don't emit light despite being on

### ISSUE THREAD

**Issue by kawoppi** [tgstation/tgstation#77789]
## Round ID:
[212982](https://scrubby.melonmesa.com/round/212982)

## Testmerges:
The following pull requests are currently test merged:
[#77447: 'Trying to qdelete a callback now lags the server instead.' by MrStonedOne at commit 24565a3e08](https://www.github.com/tgstation/tgstation/pull/77447)

## Reproduction:
I don't know what gets it to happen but it seems to be an issue with quite a few lights throughout the round. The light seems to be on, yet it emits no light.
![lamps1](https://github.com/tgstation/tgstation/assets/94711066/8925ddd1-72ea-4c55-82be-79343c1d5891)\
Taking the light out of the socket and putting it back in fixes it.
![lamps2](https://github.com/tgstation/tgstation/assets/94711066/5be10594-68eb-4283-a500-7ab2dc2575b2)

**Comment by mc-oofert** [comment]
this is caused by smoke i think
