### ISSUE TITLE
Ice hiking boots do not prevent slipping on tiles frozen by water vapor.

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#77797]
Reporting client version: 514.1589

## Reproduction:
Self-explanatory. Wear hiking boots, and release some cold water vapor. You will slip as if you weren't wearing them.

![obrazek](https://github.com/tgstation/tgstation/assets/39193093/27682fc4-3e8c-45fb-b09c-59d63386b854)

**Comment by MrMelbert** [comment]
Intended / not a bug but is rather silly

**Comment by OverwatchVoice** [comment]
> Intended / not a bug but is rather silly

For something that says it prevents slipping on ice in it's description, it's awfully specific, but I guess it's not a bug then.
Still, it should either be specified it only works on one kind of ice, or have it's functionality changed
