### ISSUE TITLE
Chemical Pipes do not Connect

### ISSUE THREAD

**Issue by Eronymun** [tgstation/tgstation#77795]
Reporting client version: 515.1613

## Round ID:
[212998](https://scrubby.melonmesa.com/round/212998)

## Testmerges:
- [Separate init_possible_values() from icon generation](https://www.github.com/tgstation/tgstation/pull/77660)
- [Disable Rust based url decoding and encoding overrides](https://www.github.com/tgstation/tgstation/pull/77397)

## Reproduction:

I placed down a chemical synth, a chemical tank, and a duct in between them. Once they were all wrenched down, they did not connect. Tried this again with an input gate, a duct, and a synth, and received the same result.

**Comment by Derpguy3** [comment]
I was doing some testing in a local server for things related to plumbing and noticed some similar issues, among the fluid ducts failing to connect to machines such as sinks and stationary tanks.
![image](https://github.com/tgstation/tgstation/assets/85206687/4bda1a39-9aeb-48d4-b55b-bad46e7eda8a)
Tested the sinks with a beaker to double check if they were connected, and they were not receiving any water from the tank.
