### ISSUE TITLE
Corpse flower does not produce miasma at all

### ISSUE THREAD

**Issue by HalfPunch** [tgstation/tgstation#77791]
Reporting client version: 514.1589

## Round ID:
[212918](https://scrubby.melonmesa.com/round/212918)

## Testmerges:
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/91390177/df6fc7af-c744-4f40-9604-411b365dc07c)

**Comment by ArcaneDefence** [comment]
https://github.com/tgstation/tgstation/blob/ac446d8bad3596016217112a53fe91b8140dace2/code/modules/hydroponics/grown/weeds/starthistle.dm#L35-L37

https://github.com/tgstation/tgstation/blob/ac446d8bad3596016217112a53fe91b8140dace2/code/modules/hydroponics/unique_plant_genes.dm#L688-L690

Working as intended, you have it in 0.03 kPa at 31K. Put it in a more normal atmosphere. 
![image](https://github.com/tgstation/tgstation/assets/51932756/3d3f6120-6341-4c0d-b7b1-59ae5e874cd8)
