### ISSUE TITLE
Certain food products burn on griddle/in oven.

### ISSUE THREAD

**Issue by Mrfilms** [tgstation/tgstation#77807]
Reporting client version: 514.1589

## Round ID:
[213009](https://scrubby.melonmesa.com/round/213009)

## Testmerges:
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)

## Reproduction:
As soon as octopus and pita bread has done cooking on the griddle/in the oven (respectively), they begin to burn. This is due to an incorrect flag - likely the 'can_burn' (or similar name) being set to 'false' rather than 'true'.

**Comment by Serxule** [comment]
yeah foods burn if you leave them in lol? unless you're saying they instantly go from cooked to burnt

**Comment by Mrfilms** [comment]
The change is instant, you have about one second to remove them before they start burning.

**Comment by Aurumdude** [comment]
I had something similar in round [214156](https://scrubby.melonmesa.com/round/214156). Bread burned in the oven, cutlets burned on the griddle after a second or two. Microwaves could cook food without it burning, but in all instances the food could not be removed from whatever device cooked them. The only way to reliably cook food was to use a grill, ordered from cargo.

**Comment by SyncIt21** [comment]
@Mrfilms the fix PR for this has been merged. Please close this issue if your above mentioned problems has stopped occurring.

**Comment by distributivgesetz** [comment]
just tested on local, no longer reproducible
