### ISSUE TITLE
Refactored Watchers can lock onto an enclosed mecha's pilot

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#77819]
Round ID:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: 
BYOND Version: 515.1610
Server revision compiled on: 
Master commit: [1e7b41b0f62c662665be7e9dd74746e9b78c6d7c](https://www.github.com/tgstation/tgstation/commit/1e7b41b0f62c662665be7e9dd74746e9b78c6d7c)
The following pull requests are currently test merged:
[#77660: 'Separate init_possible_values() from icon generation' by Mothblocks at commit 532f6bc28b](https://www.github.com/tgstation/tgstation/pull/77660)
[#77397: 'Disable Rust based url decoding and encoding overrides' by optimumtact at commit 8557c4bde2](https://www.github.com/tgstation/tgstation/pull/77397)

Local commit: b7aee66affbc74404307d455ec1d192358cfab14
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:

This is possibly related to https://github.com/tgstation/tgstation/pull/77630 

Get a human pilot into any enclosed mecha, go up to a Watcher. The Watcher will use it's stare ray at the pilot regardless of the mecha - however, the mecha will not actually be stunned, only the pilot (the pilot can still use the mecha, however.)

This is (probably!) NOT intended - one, it doesn't make sense that watchers can see through mechs, otherwise they'd see through walls, asteroids, etc etc. Two, the original coder who refactored these mobs a few days ago said in their PR "they do nothing to mechs", only the active watching ability does. Three, while the pilot is stunned, the mech can still behave normally. This doesn't make sense as the pilot is already 'stunned' by using the mech, as they can't do anything else in the mech other then use it, so being 'extra stunned' is pointless. 

Below, 1. The user's HUD has a red 'lock' overlay, 2, the targeting effect of the watcher's stun ray, 3, "the textual notification that the watcher has locked on to 'user' and 4, the watercher's stun ray animation (red curly beam that's touching the mecha and the watcher.

![clarke_watcher_lock](https://github.com/tgstation/tgstation/assets/61243846/89cab20d-44b0-46b2-94a7-b526dc52f654)

![clarke_water_lock](https://github.com/tgstation/tgstation/assets/61243846/3035c8e4-dba3-493a-845f-a6f78eb27240)

**Comment by Jacquerel** [comment]
You're reading this backwards, this is the "watching for active movement" ability, which still functions on mechs because they can see the mechs moving.
This isn't a bug.
