### ISSUE TITLE
Emojis don't work in PDA Messenger app

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#77856]
When you send a message via PDA, you can see it in the usual chat log, e.g. a checkmark. But the messenger app just shows e.g. :yes:

## Reproduction:

Send an emoji via PDA messenger

**Comment by JohnFulpWillard** [comment]
related https://github.com/tgstation/tgstation/issues/77683

@distributivgesetz im gonna consider it an oversight for it to not appear in the ui, it really should

**Comment by distributivgesetz** [comment]
I should really fix this issue now guh
