### ISSUE TITLE
We suspect the shuttle spaghetti event may have caused extreme lag.

### ISSUE THREAD

**Issue by Sightld2** [tgstation/tgstation#77855]
## Round ID: [213090](https://scrubby.melonmesa.com/round/213090)

![image](https://github.com/tgstation/tgstation/assets/93492992/dacaaf84-dbfc-4811-bcc0-86f91c797ba7)
![image](https://github.com/tgstation/tgstation/assets/93492992/5750949c-a4c7-4e0e-bdf3-1a35ccc3960c)

As the shuttle went continued its flight, lag got progressively worse and worse. I think It was briefly alleviated by tattle running an SDQL to delete food objects?

Player perspective seen here:
![image](https://github.com/tgstation/tgstation/assets/93492992/ae5d2fe1-7ed8-43b2-96e9-2bf4065f3bcd)

**Comment by Sightld2** [comment]
I was told to @Time-Green shuttle events guy

**Comment by Time-Green** [comment]
I’m ooo but its probably the sheer quantity of moving spaghetti. Should probably just be taken out to avoid admins forcing it

**Comment by Sightld2** [comment]
Hey now! I'll have you know that was all natural spaghetti. No admin forcing here to the best of my knowledge.

**Comment by Time-Green** [comment]
> Hey now! I'll have you know that was all natural spaghetti. No admin forcing here to the best of my knowledge.

Damnnnnnnnnnnnnnnnn alright. It’s like a 1 in 3000 roll so that’s pretty impressive

**Comment by LemonInTheDark** [comment]
why is it so expensive to throw 200 items. what's actually goin on here

**Comment by LemonInTheDark** [comment]
![image](https://github.com/tgstation/tgstation/assets/58055496/d598fbe1-e0f4-4ddb-b423-5db9dca0dcc9)
This amount of total with no self and few calls implies you have infinite recursion happening

**Comment by LemonInTheDark** [comment]
actually, I think what's happening is the spaghetti causing callbacks to be destroyed, which instantly harddeletes, totally chewing cpu time.
Was the fault of #77447, which is no longer tm'd and so shouldn't cause you headache anymore. Didn't replicate locally

**Comment by Sealed101** [comment]
so is it worth keeping the issue around for the spaghetti callbacks being deleted or what

**Comment by LemonInTheDark** [comment]
nah the callbacks being del'd is fixed now (it's because they were edible there's a comp with callbacks linked to that), can close this
