### ISSUE TITLE
JSON logs do not appear to be valid json

### ISSUE THREAD

**Issue by nfreader** [tgstation/tgstation#77873]
e.g. attempting to parse https://tgstation13.org/parsed-logs/manuel/data/logs/2023/08/14/round-212484/telecomms.log.json throws an error. It appears that the json objects themselves are missing a `,` separator.

**Comment by Mothblocks** [comment]
its not an array so that we can only append to the file to not have to worry about a total server crash creating malformed JSON

the extension might be a bit confusing but im not sure of anything better
