### ISSUE TITLE
all in one grinder eats plasma stack and does other silly things

### ISSUE THREAD

**Issue by honorconner** [tgstation/tgstation#77878]
all in one grinder is bad about not ejecting ungrinded materials and instead banishing them into forever. I haven't been able to work out how much solid plasma turns into how much liquid plasma, I think its supposed to be 10u liquid per 1 solid stack. The grinder does not do this at all. Sometimes I'll put the xenobio starting stack (5 solid) into the grinder, and sometimes it gives 20, 10, or 100. Other times you put in 1-2 solid and it gives 100. There might be some kind of buffer/stored value issue. Doing a little testing I've found that only sometimes it will return unused material. I'm motivated to create this report because I got a full stack (50 solid), accidentally loaded the whole thing up with a large beaker (100u capacity) and it ate the entire stack and only returned the full beacon destroying the rest.
## Reproduction:
put plasma into grinder and pay attention to values

**Comment by Serxule** [comment]
it depends on if the grinders upgraded too probably but yeah, i've definitely had stuff i've grinded get deleted when i put too much in
