### ISSUE TITLE
flashes still flash you with correct eye+ear protection

### ISSUE THREAD

**Issue by randy10122** [tgstation/tgstation#77882]
## Round ID:  
like 213159 maybe its happened on several rounds 

## Testmerges: 
#77307, #76928

## Reproduction: 
be security with bowman headset and hudglasses -> apply flash to face/have flash applied to face/run in front of autoflasher -> be flashed

**Comment by MrMelbert** [comment]
Possibly swing test related but I cannot reproduce

**Comment by randy10122** [comment]
> are you a moth

nope

> Possibly swing test related but I cannot reproduce

ill try to reproduce gimme a bit

**Comment by Comxy** [comment]
Did a bioscrambler swap your regular eyes with moth eyes?

**Comment by randy10122** [comment]
> Did a bioscrambler swap your regular eyes with moth eyes?
nope
heres the video i got sorry i forgot to throw it up earlier

https://github.com/tgstation/tgstation/assets/88034663/c180892b-39a5-4649-8ce1-41d7850a9bfa

**Comment by randy10122** [comment]
waits its because i have photophobia im fucking dumb
