### ISSUE TITLE
picking up an item while using disarm on swing combat doesnt remove the item from the floor, letting you dupe it

### ISSUE THREAD

**Issue by DeerJesus** [tgstation/tgstation#77884]
## Round ID:
[213169](https://scrubby.melonmesa.com/round/213169) (manuel)

## Testmerges:
#76928 

## Reproduction:
disarm rollerbed
you get the rollerbed item but it doesnt dissappear from the floor
TWO rollerbeds
multiply

**Comment by MrMelbert** [comment]
Resolved
