### ISSUE TITLE
Runtime when firing arrows at non-carbon mobs

### ISSUE THREAD

**Issue by vinylspiders** [tgstation/tgstation#77893]
## Reproduction:

Something is not quite right with arrows after https://github.com/tgstation/tgstation/pull/77674 . This runtime only happens with noncarbon mobs

`[2023-08-22 19:12:57.019] RUNTIME: runtime error: We just tried to add an element to a qdeleted datum, something is fucked `

![image](https://github.com/tgstation/tgstation/assets/13398309/7a9f7e63-99cd-4f57-aad6-9381d68f7f0a)

Looks like a `/datum/element/caseless` is being added after the arrow gets deleted. 

If I were to guess I'd say that when they embed in noncarbon mobs they get destroyed rather than moved into the mob, and that needs to be taken into account.

**Comment by Quink-Fix** [comment]
This runtime has an effect on downstream content; the linked PR won't actually take effect until this is fixed.
