### ISSUE TITLE
1 cyrillic letter in code

### ISSUE THREAD

**Issue by Tsurupeta** [tgstation/tgstation#77906]
https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/food/misc.dm#L60

The first letter "с" in "caramel_popcorn" icon state is cyrillic...

![image](https://github.com/tgstation/tgstation/assets/41485301/768a2e3f-03ff-460f-88f6-389f59d39ad8)

**Comment by Vect0r2** [comment]
Soul

**Comment by Sealed101** [comment]
душевно

**Comment by Sealed101** [comment]
the funnier thing is that it's cyrillic in the dmi as well

**Comment by CCC23** [comment]
душа
