### ISSUE TITLE
Silicon Mechs cannot have accesses added to them

### ISSUE THREAD

**Issue by CMDRYouth** [tgstation/tgstation#77925]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
In the beforefore times, an MMI or Positronic Brain piloted Mech could have Accesses added to its own through an ID Card interaction.  One of the recent Mech updates has removed this ability, relegating Silicon Mechs to Hallway Monitors.  To reproduce, put an MMI or a Posibrain in a Mech and try to put accesses in it without admemes.  You can't.

**Comment by Sealed101** [comment]
wasn't that menu relegated to the pilot UI? it used to be an ID slap away but now i think you have to enter the mecha to edit accesses

**Comment by Sealed101** [comment]
slapping the mech with an id with an appropriate access enables/disables the ID lock. to edit the accesses, pilot the mech, enable the ID lock and pick the Edit accesses option
![изображение](https://github.com/tgstation/tgstation/assets/75863639/2391f9e0-0d62-4b22-b7e0-204ed7032ec4)
