### ISSUE TITLE
Link scryer in deltastation's robotics is not functional

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#77934]
Reporting client version: 514.1589

## Round ID:
[213335](https://scrubby.melonmesa.com/round/213335)

## Reproduction:
It's frequency is unset, making it unusable. Current typepath:
`/obj/item/clothing/neck/link_scryer`
Correct typepath for it would be
`/obj/item/clothing/neck/link_scryer/loaded`
Idk if it's also an issue on other maps.

**Comment by Fikou** [comment]
oops
