### ISSUE TITLE
Variation of Mime’s shirt

### ISSUE THREAD

**Issue by NicoDeLuna** [tgstation/tgstation#77938]
Hello all, sorta new to GitHub so trying to figure out, but I was thinking, you guys know how there’s different color variations for the clown outfit? I was thinking that the mime deserves something similar as well like a red and blue striped variation instead of black. I tried to create a red striped shirt variation the other day but was having issues trying to run a test server for it.

**Comment by timothymtorres** [comment]
I'd recommend you hope into the [Discord](https://discord.gg/tg13) and ask on the #coderbus channel.  Unfortunately the issue tracker is only for bug reports and this does not qualify as a bug.

**Comment by timothymtorres** [comment]
The cleanup flagged label is supposed to auto close in 7 days.  It must be broken then.
