### ISSUE TITLE
Double free objective traitors spawning

### ISSUE THREAD

**Issue by Archie700** [tgstation/tgstation#77943]
## Reproduction:
![Example](https://i.imgur.com/FWxqrI8.png)

Traitors have started receiving two free objectives again, this has happened twice today and it has happened to roundstart traitor and latejoin traitor.

**Comment by Archie700** [comment]
https://statbus.space/rounds/213704, https://statbus.space/rounds/213700, https://statbus.space/rounds/213339
More recent free objectives

**Comment by Jacquerel** [comment]
At roundstart on Birdshot, `GLOB.possible_items` used for finding theft objectives contained only "cute lizard plush toy" and "cute moth plush toy", neither of which are valid theft options because they're minor secondary objectives. Something is up there.
