### ISSUE TITLE
Labor Camp keeps spawning bad decals on rocks.

### ISSUE THREAD

**Issue by ArcaneMusic** [tgstation/tgstation#77954]
## Testmerges:

N/A

## Reproduction:

This runtime keeps showing up on my local just about every other time I compile, if that helps.
![image](https://github.com/tgstation/tgstation/assets/41715314/bc0b1586-542d-404e-ba73-945d6a3df1f2)

On the pointed-at turf, it appears decals are spawning on labor camp, which is resulting in the dedicated runtime.  Looks like the decal is incompatible with the closed turf it's spawning on.

**Comment by Sealed101** [comment]
wait why the fuck are rocks there in the first place what?
![изображение](https://github.com/tgstation/tgstation/assets/75863639/e3da67af-9ded-40df-b41a-7b0dacebb97c)

**Comment by OrionTheFox** [comment]
> wait why the fuck are rocks there in the first place what?

??? The area is fine too how did these get here
![image](https://github.com/tgstation/tgstation/assets/76465278/c8822328-ea24-477f-bbb5-1e8dcc203be7)

**Comment by ArcaneMusic** [comment]
Well, you are right. I have no clue how or when it happened, but it's not on master. Hunh. Must be my fuck up then 🙂
