### ISSUE TITLE
Deep fryers don't react to water or ice.

### ISSUE THREAD

**Issue by xJavaMaster** [tgstation/tgstation#77955]
## Reproduction:
1. Get a beaker of ice or water
2. Pour it in a deep fryer
3. No giant fire
4. ????

**Comment by ArcaneMusic** [comment]
Kino, yet not a bug

**Comment by Sealed101** [comment]
fikou didn't do the needful
- https://github.com/tgstation/tgstation/pull/63073

**Comment by ArcaneMusic** [comment]
I stand corrected!

**Comment by Sealed101** [comment]
i mean fikou's pr didn't add ice or water reactions, only cold humnas and the freeze cube, sot his issue is still a feature request

**Comment by Sealed101** [comment]
would be funny but let's not keep this as an issue, it's a feature request in essence
