### ISSUE TITLE
Bile/vileworms are not organic

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#77965]
## Reproduction:

Found it while testing Polymorph belt
![Screenshot_40](https://github.com/tgstation/tgstation/assets/64209864/00a13b64-5fe7-4e96-b60e-c1d73ac92eb2)

**Comment by Sealed101** [comment]
Duplicate of #77756

**Comment by Livrah** [comment]
Raw Prophet is not organic too, but looks like the list is too big to bother.
