### ISSUE TITLE
[!!!] Wirebrush doesn't clean Rust

### ISSUE THREAD

**Issue by CMDRYouth** [tgstation/tgstation#77962]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Try to use the Wirebrush for its intended purpose.

**Comment by Sealed101** [comment]
did you use LMB or RMB to try scraping it off

**Comment by VladinXXV** [comment]
Cannot reproduce. Though I do find it a bit strange the rust-scraping behavior is only on RMB. What exactly is LMB being reserved for here?
![image](https://github.com/tgstation/tgstation/assets/44104681/feeaa29c-d32f-4d1f-8fae-8f02d1dfa18b)
