### ISSUE TITLE
Rice Dough is unmakeable due to Uncooked Rice recipe

### ISSUE THREAD

**Issue by PhillipSF** [tgstation/tgstation#77966]
## Round ID: 
[213479](https://scrubby.melonmesa.com/round/213479)

## Testmerges: 
N/A

## Reproduction:

1. Plan to make Noodles
2. See how to make Noodles
3. Rice dough - **10u Flour + 10u Rice + 10u Water**
4. Attempt to make Rice dough
5. Uncooked Rice is made instead
6. See Uncooked Rice's recipe
7. **10u Rice + 10u Water**
8. Scream

Suggestion: Change Uncooked Rice's recipe to need 15u Water instead of 10u.

**Comment by ZeroKelvn** [comment]
You can bypass this by using the Crafting Menu, but it is annoying

**Comment by PhillipSF** [comment]
Huh, I see, overexaggerated the title. I still expected to be able to mix them into a beaker like ordinary dough.
