### ISSUE TITLE
A 0 credit holochip randomly appeared

### ISSUE THREAD

**Issue by cnleth** [tgstation/tgstation#77969]
## Round ID:
[213488](https://scrubby.melonmesa.com/round/213488)

## Testmerges:
None

## Reproduction:
I found a 0 credit holochip on the cargo shuttle in the middle of a round after the QM ordered a bunch of stuff. I don't know how or when it appeared, but hopefully the round's logs will be useful. When I tried inserting the holochip in my ID, it said "The 0 credit holochip doesn't seem to be worth anything" or something like that and wouldn't let me insert it.
![0cr](https://github.com/tgstation/tgstation/assets/113535457/4a816dc5-583e-45a9-868b-1f537166695d)

**Comment by Serxule** [comment]
this bugs existed for an extremely long time, i assumed pretty much everyone who wasnt new already knew this

**Comment by Sealed101** [comment]
then write the reproduction steps mr smartypants sexrule
