### ISSUE TITLE
Fishing is woefully underpowered; Fishing skill is absurdly difficult to gain

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#77972]
Reporting client version: 514.1589

## Round ID:
[213499](https://scrubby.melonmesa.com/round/213499)

## Testmerges:
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)

## Reproduction:
I dedicated the entire 2 hour round to one thing: fishing. I wanted to reach Legendary Fishing Skill. I put a small amount of time into doing bounties to buy the gear I needed, then spent the rest of the shift fishing. I did not go onto the emergency shuttle, I didn't get bothered by any antags. All I did was fish.

In these 2 hours, my efforts amounted to 11 fish total; 7 goldfish and 4 guppies.
![image](https://github.com/tgstation/tgstation/assets/44104681/58ab1532-b260-425b-bc4e-5ae3bf6d16eb)
I just barely got 1/5th of the way to Legendary. In 2 hours of nonstop fishing.

I was using the telescopic fishing rod with the flexible fishing line, shiny lure hook, and deluxe bait (extra slimy worms). I am quite good at the minigame, which mimics that of stardew valley.
![image](https://github.com/tgstation/tgstation/assets/44104681/18baca5d-93a2-450e-829a-caf7259886df)
![image](https://github.com/tgstation/tgstation/assets/44104681/9fd18b46-87a6-4f88-afc1-f7fb53d9e655)

This is just unreasonable. 95% of the time, completing the minigame perfectly doesn't even result in a fish. You don't get ANY feedback. You just stop fishing. Even failing to catch a fish gives you some XP for the skill, but it just isn't enough. Am I expected to convince everyone on a given /tg/ server to sit around for a 10-hour long round so I can fish? There's a reason absolutely no one has made it to Legendary yet.
![image](https://github.com/tgstation/tgstation/assets/44104681/3e8d624a-ef4b-4909-8b41-83b2a4ce3190)

**Comment by Jackal-boop** [comment]
Kinda related but with how hard it is to actually fish. The miner saver fishing is impossible

**Comment by iansdoor** [comment]
> Kinda related but with how hard it is to actually fish. The miner saver fishing is impossible

As person that has successful fished out 10 ish miners. That impossible is you cannot be perfect..? like the code itself is written in a way that wants the encounter to be x amount of seconds long. If you go 5-7 seconds longer by "failing" to be perfect, you fish out the person or the fish. This doesn't also include RNG that it might be their body, a PKA, a crab or, what mob that fail in.  I don't get the minigame that takes 30 minutes to finish out a person that has ghosted.

**Comment by timothymtorres** [comment]
CC @AnturK

**Comment by carlarctg** [comment]
Fishing is so indescribably horridly rancid that it is genuinely worse than virology. The only reason it's preferable over the latter is that virology forces itself to be the entire station's problem. I'm sorry, but I'm someone who WANTS fishing to be noteworthy but it is just so, so, so, so bad.

Honestly, throw the whole thing out and replace it with Terraria's system. It's a lot simpler.

**Comment by VladinXXV** [comment]
> Honestly, throw the whole thing out and replace it with Terraria's system. It's a lot simpler. Better yet add two types of fishing rods, a Terraria style and a Stardew Valley style. Also there's no way in hell SV fishing is as awful and unforgiving as ours???

Stardew valley fishing uses the same style of minigame, is all I meant. The outcomes and behind-the-scenes are quite different. The point I was trying to make is just that I am Good At This Minigame, it isn't just me having a skill issue.

**Comment by Ghommie** [comment]
It's actually a bug because I have forgot to multiply the divisor of the gain per second by 0.1
