### ISSUE TITLE
Ice legions dropping an extra Ash Walker.

### ISSUE THREAD

**Issue by Astrogem2** [tgstation/tgstation#77973]
Reporting client version: 514.1589

## Round ID:
[213510](https://scrubby.melonmesa.com/round/213510)

## Reproduction:
I killed an ice legion and instead of not dropping an ash walker, it seems to include an ash walker when I kill an ice legion
![image](https://github.com/tgstation/tgstation/assets/101240878/79caa552-495c-4a1d-8442-f7289176da52)

**Comment by Astrogem2** [comment]
It seems to also drop an extra body if it doesn't drop another ash walker when you kill one
![image](https://github.com/tgstation/tgstation/assets/101240878/4db4c8ae-e85a-43c6-905e-096eed85b720)

**Comment by Sealed101** [comment]
introduced in #76898 as the corpse spawners the snow legions drop now are a subtype of a regular legion corpse spawner, and the former calls the latter's corpse spawn proc, resulting in an additional lavaland-flavored corpse spawning.

not subtyping the snow legion's corpse spawner to the lavaland one should alleviate the issue
