### ISSUE TITLE
Dead rat kings still show up as playable mobs on the spawners menu

### ISSUE THREAD

**Issue by xPokee** [tgstation/tgstation#77988]
Reporting client version: 514.1589

## Round ID:
[213579](https://scrubby.melonmesa.com/round/213579)

## Reproduction:
Try to spawn as a rat king via spawners menu, realise it is dead. 
![image](https://github.com/tgstation/tgstation/assets/20053168/d398bf7f-60be-48ca-b39c-01b6c77996cf)

**Comment by san7890** [comment]
should have been fixed in #79615
