### ISSUE TITLE
Airlock Directional Unrestricted Access Doesn't Work When Set Manually (w/out RCD)

### ISSUE THREAD

**Issue by Wiselunatic** [tgstation/tgstation#77981]
## Round ID:

All rounds

## Reproduction:

Directional unrestricted access (north-south-east-west) doesn't work if set manually with an airlock electronics board in hand. It works when using RCDs.

**Comment by MrZoraman** [comment]
https://github.com/tgstation/tgstation/assets/720034/8fba4034-d74a-45e4-8d62-073ee5750219

Seems to be working as expected, I couldn't reproduce the problem. could you give more details?

**Comment by Wiselunatic** [comment]
It might be windoor specific as that's when I encountered the problem

**Comment by Sealed101** [comment]
did windoors ever supported unrestricted access from a side cuz i don't remember them having that feature

**Comment by Wiselunatic** [comment]
Yeah it works when constructed with RCD

**Comment by Serxule** [comment]
> It might be windoor specific as that's when I encountered the problem. I was also using any instead of all for required privileges, I don't know if that matters or not.

thats pretty important to specify that it was a windoor since those pretty different from airlocks
