### ISSUE TITLE
Can't remove allergy dogtags from clown suits

### ISSUE THREAD

**Issue by Bibarra** [tgstation/tgstation#77984]
## Round ID:

213555

## Testmerges:

[#77307: 'Revert "Bumps rust-g to `3.0.0` "' by MrStonedOne at commit 8dad0feceb](https://www.github.com/tgstation/tgstation/pull/77307)
[#77813: '[TEST-MERGE FIRST] Allows all limbs to be dismembered and significantly refactors wounds' by nikothedude at commit bed7906764](https://www.github.com/tgstation/tgstation/pull/77813)
## Reproduction:

Try to save a clown having an allergic reaction.
Realize you don't have a health analyzer, but see the clown's suit has allergy dogtags attached.
Remove their clown suit and alt click it to try to remove attaches as the tooltip suggests.
Get a "can't adjust" balloon alert and the dogtag doesn't get removed.

**Comment by AdipemDragon** [comment]
isn't it alt _right_ click?

**Comment by Bibarra** [comment]
Fair enough. Clown moment.
