### ISSUE TITLE
Security Camera Console BSOD

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#78009]
Reporting client version: 514.1589

## Round ID:
[213646](https://scrubby.melonmesa.com/round/213646)

## Testmerges:
- [[TEST-MERGE FIRST] Allows all limbs to be dismembered and significantly refactors wounds](https://www.github.com/tgstation/tgstation/pull/77813)
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)

## Reproduction:
Try to use security camera console (science sec checkpoint on metastation, not that it should matter?)
![image](https://github.com/tgstation/tgstation/assets/44104681/2e528f26-d6f6-44aa-9ccc-469cb3fb1a16)

**Comment by jlsnow301** [comment]
do you have any screenshots of this without the black box? it would narrow down the search quite a bit

**Comment by VladinXXV** [comment]
> do you have any screenshots of this without the black box? it would narrow down the search quite a bit

No, the black box was ingame.

**Comment by jlsnow301** [comment]
a little difficult to reproduce this as it doesn't really show where the error happened on the UI. for now i'm going to flag this for cleanup, "probably fixed", if it isn't just reopen
