### ISSUE TITLE
Flamethrower logging in attack logs despite not being ignited

### ISSUE THREAD

**Issue by lnGoror** [tgstation/tgstation#78008]
Reporting client version: 514.1589

## Round ID:
[213658](https://scrubby.melonmesa.com/round/213658)

## Reproduction:
So using a flamethrower logs as "flamethrowered [x] with the flamethrower". This event gets logged the same no matter if the flamethrower is lit or not, leading to potential confusions while proofreading logs. Having a check for whether the flamethrower is lit would be appreciated.

**Comment by Profakos** [comment]
Unlit flamethrowers can still be used as Ice Throwers or Sleep Throwers, so rather than not logging if unlit, I would probably expand a log with the lit status, and maybe the contents of the thrower's air mix, though that might be too much.

**Comment by Pickle-Coding** [comment]
Personally I think it should be in attack logs regardless just so there is a consistent place to look for flamethrower usage. I think giving more detail is the way to go.
