### ISSUE TITLE
the tram malfunction event can roll on maps that are not tramstation, presumably due to hilbert's research facility having one

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#78018]
## Testmerges:
[#78015: 'enables ref tracker' by Fikou at commit 5da8b24a94](https://www.github.com/tgstation/tgstation/pull/78015)

## Reproduction:

-be on metastation
-the tram malfunctions
-?????????

**Comment by Serxule** [comment]
OH MY GOD IS THIS WHY IT HAPPENS

I THOUGHT THE EVENT WAS JUST RANDOMLY TRIGGERS REGARDLESS
