### ISSUE TITLE
Linked stacking machine does not send alloys to silo

### ISSUE THREAD

**Issue by HalfPunch** [tgstation/tgstation#78029]
Reporting client version: 514.1589

## Round ID:
[213695](https://scrubby.melonmesa.com/round/213695)

## Reproduction:
It just puts it on the floor on the output

**Comment by SyncIt21** [comment]
Not a bug cause that has always been the case. You don't get that much convinience.

**Comment by Sealed101** [comment]
didn't stacking machines link to the silo a few weeks back
which allowed for campbell's setups of xenobio crossbreeds usage for iron glass and plasma

**Comment by HalfPunch** [comment]
> didn't stacking machines link to the silo a few weeks back which allowed for campbell's setups of xenobio crossbreeds usage for iron glass and plasma

Yes, i build machine that makes lots of plassteel but the problem is that such a large amount of plasteel leads to lags on the server if left on the floor. So plasing all of plasteel inside stacking machine may sometimes be very hard.

I think that stacking machine should send alloys to ore silo, because it already collects and stacks alloys, but just not sends
