### ISSUE TITLE
Custom tapes do not work.

### ISSUE THREAD

**Issue by DATA-xPUNGED** [tgstation/tgstation#78036]
## Reproduction:
- Open the vibeo gane
- spawn in /obj/item/tape/captains_log, spool it, and try playing it in a recorder
- recorder will say that it is empty even though it has 48 minutes of dialogue

**Comment by norsvenska** [comment]
I was unable to reproduce

**Comment by VladinXXV** [comment]
![image](https://github.com/tgstation/tgstation/assets/44104681/74725b8e-6817-451a-ad20-cd79f5374595)

**Comment by timothymtorres** [comment]
You need to flip the tape.  There is a 50/50 chance that when a tape spawns it picks a random side.  It's really stupid but that's how the tapes work in real life.

**Comment by DATA-xPUNGED** [comment]
> You need to flip the tape. There is a 50/50 chance that when a tape spawns it picks a random side. It's really stupid but that's how the tapes work in real life.
> 
> Also - it doesn't have 48 mins of dialogue. I broke the dialogue down into different time segments to show kind of a timeline of the station going to shit.
> 
>     * Early round - Complaining about NT
> 
>     * Mid round - Paranoia about antags
> 
>     * End round - Crew is dying and captain is possibly a ~traitor~ hero saving the station

I know it isn't actually 48 minutes, i was exaggerating for dramatic effect

**Comment by SyncIt21** [comment]
So was planning to make a fix PR for this but since it's not a bug idk what happens now?
