### ISSUE TITLE
[NorthStar] Ordnance mass driver has no control interface

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#78059]
Reporting client version: 514.1589

## Round ID:
[213841](https://scrubby.melonmesa.com/round/213841)

Self-explanatory. The mass driver in ordnance doesn't have a control panel, and hence no way to actally use it.

![obrazek](https://github.com/tgstation/tgstation/assets/39193093/2facd085-8f7a-48e6-bae8-bad2e8c5f32b)

## Testmerges:
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)

**Comment by norsvenska** [comment]
check underneath the binoculars

**Comment by OverwatchVoice** [comment]
> check underneath the binoculars

God damn it...
I expected it to be on a wall since it can only be built on walls, but I should've known mapping logic is weird like that
