### ISSUE TITLE
Tram controls don't make the tram actually move

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#78068]
## Round ID: [213868](https://scrubby.melonmesa.com/round/213868) and many before

When you try to move the tram with the tram controls (the ones on the tram), it says it'll go there. The doors close, then the doors just open again without it actually having moved. And the UI of those controls think you are in the location you wanted to go to now.

The tram call buttons outside the tram work though to call it to the current location.

## Testmerges:

https://github.com/tgstation/tgstation/pull/77307

## Reproduction:

1. Get on Tram
2. Try to operate the tram controls
3. Notice Tram doesn't move

**Comment by lessthnthree** [comment]
@Inari-Whitebear how many times a round does this seem to happen?

**Comment by Inari-Whitebear** [comment]
> @Inari-Whitebear how many times a round does this seem to happen?

Had it multiple rounds, and the controls never work in those rounds. The call buttons work

**Comment by Inari-Whitebear** [comment]
Oddly it seemed to work on my private server, but neither on Manuel nor Campbell? (Gravity off here, yeah, but it also doesn't work with grav on)

Example:

https://github.com/tgstation/tgstation/assets/1077971/14068c5e-0d2a-4984-9e73-f6d436d06e5e

**Comment by lessthnthree** [comment]
I watched a Manuel round last night and it was fine, haven't been able to reproduce it locally.

Do you recall anything happening to the tram when that occurs, or is it like that roundstart?

The controls receive location data from the lift_master and base on 0:10 it thinks it's at the east wing, so there's a disconnect between where the tram is and the lift_master thinks it is. (I have some improvements to this in an upcoming PR.)

For looking into this could you please grab info these vars from before/after you try to send the tram:

idle_platform (name)
nav_beacon (x, y, z)
travelling (0/1)
travel_trip_length (number)

They'll be in this datum:
![image](https://github.com/tgstation/tgstation/assets/83487515/add23f0e-f861-4feb-8492-49c15c9fd983)

**Comment by Inari-Whitebear** [comment]
It's just from roundstart as far as I can tell.

And well I can if I make it work on a private server, yeah

**Comment by deathrobotpunch** [comment]
this is true, I have seen rounds recently describing the very same problems that are described here
