### ISSUE TITLE
The penguin chick on the west side of the medsci floor on northstar always dies inside its pen.

### ISSUE THREAD

**Issue by xPokee** [tgstation/tgstation#78084]
Reporting client version: 514.1589

## Round ID:
[213911](https://scrubby.melonmesa.com/round/213911)

## Testmerges:
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)

## Reproduction:
Join on Northstar, notice that the poor penguin dies every single time due to something inside its cage.

**Comment by Sealed101** [comment]
headminmapper exposed for animal cruelty
