### ISSUE TITLE
Corn doesn't give 'Vegetable Oil' when grinded up anymore

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#78087]
## Reproduction:

Corn is now defined as having 'grind_results = corn meal', which overrides completely the contents that it's supposed to have. This is due to the Foodening PR. It makes it really hard to make Glycerol for Nitroglycerin

**Comment by blueDev2** [comment]
All-in-one grinders don't accept seeds, so I'm not sure how you are supposed to extract the oil from them. Perhaps that's the a actual issue.

**Comment by Profakos** [comment]
That is a fair point!

**Comment by Profakos** [comment]
Looking over things, I was incorrect, the variable on seeds doesn't do what I thought it did. Maybe this is the same error as livers not producing peptids, which have been fixed recently. Maybe that PR fixed this too?

**Comment by blueDev2** [comment]
Yeah the "reagents_added" variable did not do what I thought either.
It's pretty simple to just add a "grind_results" to make the seeds actually create the oil... I think at least.
The question is was that the intended function of the foodening PR.
