### ISSUE TITLE
'Mirror Explodes' Cursed trait effect does nothing

### ISSUE THREAD

**Issue by OuroborusReporter** [tgstation/tgstation#78082]
Reporting client version: 514.1589

## Round ID:
[213911](https://scrubby.melonmesa.com/round/213911)

## Testmerges:
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)

## Reproduction:
Was testing the various effects listed in the code for the Omen effect (the effect permanently given the characters with the Cursed trait). Mirrors have three effects listed - Your reflection giving you an evil look, Not having a reflection, and 'The mirror explodes into a million pieces!'. I ran between two mirrors in NorthStar's public restrooms and got the effect twice, according to the status message, but the mirrors were fully intact afterwards. Not sure if they're meant to actually break, but given that the other Omen effects that cause damage, like lights zapping you or vendors crushing you, actually effect the items in-game, this feels like something got missed,

![kaboom](https://github.com/tgstation/tgstation/assets/88996803/bba9dcd7-8a4f-4194-b16d-5bb35129139b)

**Comment by carlarctg** [comment]
What the frick I thought I removed that bit after I couldn't get it to work. Whoever wants to fix this, do so by removing that to_chat
