### ISSUE TITLE
the icebox lake of change only changes you into a human

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#78097]
## Round ID:
on 2 live rounds and tested on local

## Reproduction:
try going into the icebox lake of change, you will always be turned into a human

**Comment by Jacquerel** [comment]
I spawned it on local and walked in and turned into a mouse.
I then ran icebox and reset it until it spawned naturally and turned into a fox.
Might just be bad luck?

**Comment by Jackal-boop** [comment]
3 human rolls in a row huh. whats the chances of that?

**Comment by Sealed101** [comment]
slim, you could have won 1/10th of an arcade jackpot with that maybe

i suggest trying it again and recording it if possible; also round IDs would be great

**Comment by timothymtorres** [comment]
what race were you initially before you turned into a human 3 times?
