### ISSUE TITLE
Quad amputee hemiplegic characters cannot move or use their hands to use a wheelchair

### ISSUE THREAD

**Issue by xPokee** [tgstation/tgstation#78114]
Reporting client version: 514.1589

## Round ID:
[214004](https://scrubby.melonmesa.com/round/214004)

## Testmerges:
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)

## Reproduction:
Join the game with quad amputee and hemiplegic quirks, suffer as you cannot move or do anything.

**Comment by Serxule** [comment]
if you have no limbs you cant do anything, thats intentional

**Comment by lizardqueenlexi** [comment]
How did you get both quirks at once? They're not compatible.

**Comment by Time-Green** [comment]
Quad amputee just gives you four prosthethics, hemiplegic paralyzes your left or right side. How did you get a wheelchair if you couldnt move?

**Comment by san7890** [comment]
me myself personally i just wouldn't take the quirks

**Comment by xPokee** [comment]
> How did you get both quirks at once? They're not compatible.

Via hardcore random

**Comment by xPokee** [comment]
> Quad amputee just gives you four prosthethics, hemiplegic paralyzes your left or right side. How did you get a wheelchair if you couldnt move?

I spawned on the floor, unable to stand, at which point I called for help over the medical radio and a doctor brought me a wheelchair, which I was then unable to move

**Comment by Time-Green** [comment]
> > How did you get both quirks at once? They're not compatible.
> 
> Via hardcore random

Fair enough that does happen frequently
