### ISSUE TITLE
Exploding a maxcap from inside an exosuit's cargo results in you not taking any damage at all.

### ISSUE THREAD

**Issue by DeerJesus** [tgstation/tgstation#78126]
## Round ID:
n/a

## Testmerges:
n/a

## Reproduction:
put maxcap in crate
pick up crate with cargo hold
activate maxcap
exosuit gone
but you? are fine

**Comment by Sealed101** [comment]
related issues that probably have the common cause of mech contents being handled like a bag of chicken eggs in the backseat of your car on a bumpy country road
- #45508 
- #68076 
- #65723 
- #61600

**Comment by Sealed101** [comment]
something something explosions work from inside mechs (and other containers probably)

![изображение](https://github.com/user-attachments/assets/583c5efb-bc03-48ab-b413-8f203b0768ef)
