### ISSUE TITLE
Birdshot Disposals recycler is fundementally Broken

### ISSUE THREAD

**Issue by nintyuk** [tgstation/tgstation#78135]
## Reproduction:
The Birdshot Disposals Recycler is setup to take input from below but the recycler can only take input from the sides.
![263841800-571fa329-7d66-4225-9864-77bcc6db1c23](https://github.com/tgstation/tgstation/assets/4965151/f9953b52-ffa3-4dfc-b9b0-91cb8720d247)
The recycler either needs a rotated sprite to allow it to run vertically or the entire room needs to be re-designed

**Comment by nintyuk** [comment]
my suggestion is to move it in to the area where the vending machine is in a U shape and move the door to where the start of the convenor is now
![image](https://github.com/tgstation/tgstation/assets/4965151/9ac87557-3f14-4dad-b5ff-1334cdaa5bf2)

**Comment by MrMelbert** [comment]
the setup is valid, just the `eat_dir` on the recycler needs to be edited to `2` instead of `8`. 

https://github.com/tgstation/tgstation/assets/51863163/5fad8af3-770c-41c5-a82b-6daa7f1087fc

**Comment by MrMelbert** [comment]
that being said there is another issue in this room, and it's that the stacker has no stacking console linked

**Comment by BlueMemesauce** [comment]
> the setup is valid, just the `eat_dir` on the recycler needs to be edited to `2` instead of `8`.
that looks pretty bad though

**Comment by nintyuk** [comment]
> the setup is valid, just the `eat_dir` on the recycler needs to be edited to `2` instead of `8`.
> 
>  2023-09-04.18-47-56.mp4

Can that be done in game by players though? As with no vertical sprites there is no visual feedback and if the machine is disassembled how can crew put it back together and still have it work?

**Comment by deathrobotpunch** [comment]
> > the setup is valid, just the `eat_dir` on the recycler needs to be edited to `2` instead of `8`.
> > 2023-09-04.18-47-56.mp4
> 
> Can that be done in game by players though? As with no vertical sprites there is no visual feedback and if the machine is disassembled how can crew put it back together and still have it work?

should they have to reconfirgure it every god damned time?

**Comment by nintyuk** [comment]
> > > the setup is valid, just the `eat_dir` on the recycler needs to be edited to `2` instead of `8`.
> > > 2023-09-04.18-47-56.mp4
> > 
> > 
> > Can that be done in game by players though? As with no vertical sprites there is no visual feedback and if the machine is disassembled how can crew put it back together and still have it work?
> 
> should they have to reconfirgure it every god damned time?

Exactly, like it looks like you can fix it in the editor manually so the map can be updated and "fixed" however when there comes the inevitable time when something causes it to get broken can crew rebuild it and still have it work?

**Comment by Vincent983** [comment]
a solution could just be, adding down sprites and the ability to rotate the recycler

**Comment by nintyuk** [comment]
> a solution could just be, adding down sprites and the ability to rotate the recycler

That's the long term solution, but that requires art. Someone has already put in a re map to fix it. It just needs to be approved
