### ISSUE TITLE
50 minute shuttlecall

### ISSUE THREAD

**Issue by Timonkeyn** [tgstation/tgstation#78159]
Reporting client version: 514.1589

## Round ID:
[214018](https://scrubby.melonmesa.com/round/214018)

## Reproduction:
kill the AI going delta while no comms consoles are active and the shuttle isnt called. may have been amplified by lag.

1. AI dies
2. 25 minute shuttle call
3. alert level gets lowered to red
4. 50 minute shuttle call

**Comment by CCC23** [comment]
sent to brazil dimension

**Comment by Sealed101** [comment]
it kind of makes sense as delta alert is the one that gets you the shuttle the fastest, and pumping it to red is actually **going back an alert level**, which multiplies it by 2.

you should have lowered it to green somehow and go play campbell :trollface: 

saying that seems like the auto call just doesn't respect the station alert levels and calls the shuttle on the hard 25 minute time mark

**Comment by Jacquerel** [comment]
I don't _see_ a notification of an admin deleting every engine on the shuttle in the logs, did the shuttle have engines when it arrived? 😅

**Comment by Timonkeyn** [comment]
Don't think it matters but I don't know

**Comment by Sealed101** [comment]
https://github.com/tgstation/tgstation/blob/79e394320d79cc9151b63368a3ced3ded30cb819/code/controllers/subsystem/shuttle.dm#L435-L462

https://github.com/tgstation/tgstation/blob/79e394320d79cc9151b63368a3ced3ded30cb819/code/modules/shuttle/emergency.dm#L340-L367

the autoevac does not actually take station alert status into the account when proc'd, hence why it does this.
