### ISSUE TITLE
blob flashed

### ISSUE THREAD

**Issue by Cutplays** [tgstation/tgstation#78165]
Reporting client version: 514.1589

 Round ID: [214050](https://scrubby.melonmesa.com/round/214050)

Reproduction: be blob hivemind and flash

 blob hivemind gets flashed by any flash source

**Comment by Cutplays** [comment]
This might not be a bug but I'm reporting it just in case

**Comment by ArcaneDefence** [comment]
lol

**Comment by SethLafuente** [comment]
Maybe a bug or not a bug either way this no longer happens as shown below with either flashes or flashbangs.
![yFrbErx](https://github.com/tgstation/tgstation/assets/84478872/a3d6cc24-d22e-48ad-9ef9-8ee64e9a7b34)
![EsEFQGH](https://github.com/tgstation/tgstation/assets/84478872/23bbbd90-9bd2-4cf7-bb42-1d82855c6f36)
