### ISSUE TITLE
Liberator Golems can't eat

### ISSUE THREAD

**Issue by MoffNyan** [tgstation/tgstation#78167]
## Reproduction: Spawned in as the free golems that worship "The Liberator", tried to eat raw iron, regular iron, mushrooms, different minerals. Could not eat, and eventually statued and died from starvation. I tried targeting the mouth, head, and chest when I ate, as well as feeding the other golem that spawned along with me. The other golem was unable to eat nor feed me either.
I don't know if it's a problem with all golems, or just the deathspawn ones.

An admin did feed me once to revive, and I tried spawning in a second time as another golem to try again, but eventually starved the same way.
<img width="300" alt="sadgolems" src="https://github.com/tgstation/tgstation/assets/143907841/9711c7a4-76f6-4ae8-8258-eb94849b63ae">

**Comment by gueba14** [comment]
cant eat as xenobio golems too
