### ISSUE TITLE
Observing is broken on away missions

### ISSUE THREAD

**Issue by trerri** [tgstation/tgstation#78162]
Reporting client version: 514.1589

## Round ID:
[214028](https://scrubby.melonmesa.com/round/214028)

## Reproduction:

When suiciding on an away mission, my ghost was instantly kicked to the arrivals shuttle. Orbiting an individual on the away mission did not do anything. Toggling auto-observe did let me see from that person's POV, and let me verify that they were indeed still on the away mission. Unfortunately though, speech and probably other sounds were both inaudible and invisible. Only the speech bubble animation let me know that this person and another were speaking.

**Comment by Sealed101** [comment]
i think some away missions are configured to not be ghost accessible, with the only loophole being the observe verb

**Comment by Time-Green** [comment]
Yeah this isn’t a bug, it’s intentional to fight metagaming
