### ISSUE TITLE
Heretic Living Heart deletes as bitrunner

### ISSUE THREAD

**Issue by ValerieSteel** [tgstation/tgstation#78173]
## Round ID:
[214089](https://scrubby.melonmesa.com/round/214089)

## Testmerges:
77259 "bitrunner"

## Reproduction:
Roll heretic as bitrunner. Enter a domain. Exit the domain. You now lack your Living Heart!

**Comment by san7890** [comment]
@jlsnow301

**Comment by Sealed101** [comment]
might be related #71451

**Comment by MrMelbert** [comment]
if antag datums follows you into cyber realm that's a big problem

**Comment by jlsnow301** [comment]
it's using `mind.transfer_to`.

**Comment by MrMelbert** [comment]
> mind.transfer_to

NOOOOOOOOOOOOOOOOOOO

**Comment by jlsnow301** [comment]
the pr is open for review

**Comment by jlsnow301** [comment]
the mind transference system has been totally rewritten. as such, this issue should no longer be valid. closing this as resolved; however, if the issue persists feel free to reopen
