### ISSUE TITLE
Charged black extract breaking monkey sprite

### ISSUE THREAD

**Issue by HalfPunch** [tgstation/tgstation#78179]
Reporting client version: 514.1589

## Round ID:
[214008](https://scrubby.melonmesa.com/round/214008)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/91390177/bb1830d9-9aa7-4604-9ede-ece9ae650ec1)
In order to do that you need to change into monkey while wearing uniform
Not always
Some times it does this
![image](https://github.com/tgstation/tgstation/assets/91390177/60299409-1a18-4137-a727-acfc2b85baf2)

**Comment by Jacquerel** [comment]
Why do we have so many types of these I hate xenobiology
