### ISSUE TITLE
Nyctophobia breaking your walking speed forever if you are Etherial

### ISSUE THREAD

**Issue by HalfPunch** [tgstation/tgstation#78178]
Reporting client version: 514.1589

## Round ID:
[214008](https://scrubby.melonmesa.com/round/214008)

## Reproduction:
1. Be Etherial with Nyctophobia
2. Get in locker/Cyborg recharger/get your glow removed while in the dark
3. 
![image](https://github.com/tgstation/tgstation/assets/91390177/32c7e081-ba0a-45a4-b40e-1a8803f70899)
4. F*ck why am i a turtle now

**Comment by ZAMODA** [comment]
Did you toggle to run again?  Nyctophobia only toggles you to walk when you go into darkness, it doesn't toggle it back to run when you are back in light.
