### ISSUE TITLE
Components can not be removed properly via admin tooling

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#78172]
Reporting client version: 514.1589

## Round ID:
[214043](https://scrubby.melonmesa.com/round/214043)

## Reproduction:

Find a sensible atom.
Add the /datum/component/spawner component to it via the VV dropdown Add Component/Element
Try use the VV dropdown to remove this component

**Comment by Jacquerel** [comment]
Spawner is runtiming on init if added with no arguments and then is never added to the list to remove.
It is also impossible to instantiate it with a list of typepaths as an argument from the VV menu, so it's not possible to add this component to things 🙃
