### ISSUE TITLE
Grinders output only 100u of grinded material no matter how much volume beaker has

### ISSUE THREAD

**Issue by HalfPunch** [tgstation/tgstation#78180]
Reporting client version: 514.1589

## Round ID:
[214008](https://scrubby.melonmesa.com/round/214008)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/91390177/db8fd6e0-0841-43c6-acc2-8c73b1148cb7)
Plumbing grinders do this to
1. Grab 6 or more sheets of plasma(or what ever you want)
2. Grind it
3. Get less plasma than you expected

**Comment by SyncIt21** [comment]
Duplicate 
#77878
