### ISSUE TITLE
Cooked food is completely fucking broken

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#78192]
Reporting client version: 514.1589

## Round ID:
[214161](https://scrubby.melonmesa.com/round/214161)

## Testmerges:
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)

## Reproduction:

- Cook food
- Expect to be able to interact with the food
- Be completely unable to pick up or do anything with it because it's not getting the init flag for some reason??????

![image](https://github.com/tgstation/tgstation/assets/7019927/fc391896-75c0-4483-9774-5b5b224ee57e)

Even when I var edit the init flag on correctly, I still can't actually eat it because its reagents list is also nulled, so something _really_ fucky is going on here.

**Comment by Deadgebert** [comment]
reverting this https://github.com/tgstation/tgstation/pull/78150 on local fixed the issue. i think it's their change in [code/game/objects/items/food/_food.dm](https://github.com/tgstation/tgstation/pull/78150/files#diff-360d9e5d1ad347dc6f8ce0cdcb3515ba7ae5169f9804dbcd0d1d7423cc0d130c)
