### ISSUE TITLE
Fishing with the rod from the Settler Quirk has become a Sisyphean task

### ISSUE THREAD

**Issue by AyamePup** [tgstation/tgstation#78210]
## Reproduction: 
I was using the rod and line given by the Settler quirk, so a regular rod, line, and basic hook. Bait used was a dough ball. I successfully completed the minigame at least a dozen times, and caught nothing. It did not say the fish had gotten away, or that something had failed, it simply said 'stopped fishing' in the balloon alert. The bait was not used up, but my fishing skill did increase. I think I got all the way to expert before giving up because I wasnt catching anything. I dont know if this is a bug with the quirk items or the portal itself.
Extra details that may or may not be relevant?: This was on northstar, and the food glitch was also active at this time. [That issue was report here](https://github.com/tgstation/tgstation/issues/78192)

**Comment by OuroborusReporter** [comment]
Can confirm the portal works, I just ended a round where it got me to legendary and caught plenty of fish with a standard rod, reel, hook, and extra slimy worm for bait, but I never got the settler gear to catch anything the few rounds I took it

**Comment by AyamePup** [comment]
> Can confirm the portal works, I just ended a round where it got me to legendary and caught plenty of fish with a standard rod, reel, hook, and extra slimy worm for bait, but I never got the settler gear to catch anything the few rounds I took it

I wonder if its just the rod thats fucked up then. Thanks for lettin me know others work at least!

**Comment by AyamePup** [comment]
Updated the title to what might more realistically be the problem.

**Comment by VladinXXV** [comment]
I'm pretty sure this is just universally an issue with fishing. Confident, actually. Because I simply do not use the settler quirk.
