### ISSUE TITLE
Vorpal Scythe harming you despite being sated

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#78218]
Reporting client version: 514.1589

## Round ID:
[214237](https://scrubby.melonmesa.com/round/214237)

## Testmerges:
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)

## Reproduction:
Take out vorpal scythe on accident.
Kill a crab with it.
Examine. Says it is sated.
Try to stow it. Be punished.
![image](https://github.com/tgstation/tgstation/assets/44104681/ddf27b44-8c17-4fe5-8bf6-33c82cf845d6)

Also tried:
Take out vorpal scythe.
Perform the death knell on a human corpse (nonsentient)
Does not seem to get empowered at all.
Try to stow it. Be punished.
![image](https://github.com/tgstation/tgstation/assets/44104681/e2602f94-bc61-4f64-ad9b-69cb90008e05)

**Comment by necromanceranne** [comment]
https://github.com/tgstation/tgstation/pull/77595 most likely the culprit.
