### ISSUE TITLE
You can turn everyone into lings using the Polymorph Belt

### ISSUE THREAD

**Issue by StrangeWeirdKitten** [tgstation/tgstation#78227]
## Testmerges:

Reported from downstream: https://github.com/Bubberstation/Bubberstation - Reproduced on upstream

## Reproduction:

- Find a dead head slug from a ling. Doesn't matter if it was successful or not.
- Scan it. Inject the egg into a corpse. Kill yourself (without suicide verb). Sit in your corpse
- Wait 4 minutes
- Congratulations. You're now a changeling.

Did I mention that someone can pull the polymorph belt from your body and repeat the process?

**Comment by Sealed101** [comment]
[![parenting](https://user-images.githubusercontent.com/39163353/198381160-f0aa7fc4-4f2d-486f-8b33-44a1965e2ad1.svg)](https://media.oglaf.com/comic/parenting.jpg)

we've had a fix PR for this merged about two weeks ago, and you guys don't seem to have caught the update.
- #77941

**Comment by StrangeWeirdKitten** [comment]
ah I see, no problem then

**Comment by StrangeWeirdKitten** [comment]
@sealed101 It's still reproducible on updated TG. The PR above just made the beakless head slug a thing. If you find a real headslug from a changeling, you can use that to produce a ling.

**Comment by Sealed101** [comment]
lmao
