### ISSUE TITLE
Holopad users cannot hear in the area surrounding destination holopad's projection

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#78231]
Reporting client version: 514.1589
Self-explanatory.

## Round ID:
[214280](https://scrubby.melonmesa.com/round/214280)

## Testmerges:
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)

## Reproduction:
Self-explanatory.

**Comment by SyncIt21** [comment]
Duplicate #77730

**Comment by Sealed101** [comment]
^

**Comment by OverwatchVoice** [comment]
Should've checked this yesterday, whoops
