### ISSUE TITLE
Birdshot station, some of the shutters unset by default

### ISSUE THREAD

**Issue by WarerBrow** [tgstation/tgstation#78234]
Reporting client version: 514.1589

## Round ID:
[214307](https://scrubby.melonmesa.com/round/214307)

## Testmerges:
- [[TEST-MERGE FIRST] Wound refactor number two: Full synthetic support](https://www.github.com/tgstation/tgstation/pull/78124)

## Reproduction:
There is a guest suite at the Birdshots Bridge, and one of the shutters isn't closing. I guess it's just rarely used and/or maintainers just weren't aware. So
1. You press the button
2. Only half of shutters close
![image](https://github.com/tgstation/tgstation/assets/106118256/547f2c9f-dcee-44f5-ac54-ee5f4d199981)

**Comment by DATA-xPUNGED** [comment]
Okay so, looking at the editor, each button seems to be tied to ONE shutter. But i'm gonna test it ingame first
