### ISSUE TITLE
Polymorphic field inverter deletes users body when used on a vileworm and leaves them as a gosth

### ISSUE THREAD

**Issue by gueba14** [tgstation/tgstation#78250]
## Round ID:
[214349](https://scrubby.melonmesa.com/round/214349)

## Testmerges:
Unknown

## Reproduction:
Use a Polymorphic belt to scan a vileworm

Tansformation into scanned vileworm

Deletes your body and puts a vileworm ai in the new vileworm body

**Comment by MrMelbert** [comment]
i would hazard a guess that it's turning into a vileworm, they get the "growth" component, they evolve into the very-vile-worm, so it deletes them?

**Comment by gueba14** [comment]
It did transform me into a red vileworm not the adult one

**Comment by gueba14** [comment]
> i would hazard a guess that it's turning into a vileworm, they get the "growth" component, they evolve into the very-vile-worm, so it deletes them?

Did tranform into the red version even tho i scanned the yellow one

**Comment by Sealed101** [comment]
IIRC the evolutionary leap component doesn't have any handling for client transference, though i may be mistaken

whaddayaknow new polymoprh belt bug :^)

**Comment by Livrah** [comment]
I bit on top of this: scanning Paper Wizard spell copy will delete you completly.

**Comment by gueba14** [comment]
Im not a coder but maybe add a check for a list of entity names that should no be scanable for the spell one,but the vileworm one to me seems like an entity one should be able to scan since its like the othe lavaland fauna and other more rare creatures

**Comment by necromanceranne** [comment]
@Jacquerel some new funny business, both livrah's comment and the issue.
