### ISSUE TITLE
Watchers can target you thru wall ?

### ISSUE THREAD

**Issue by LikesGreen** [tgstation/tgstation#78285]
## Round ID:
[214447](https://scrubby.melonmesa.com/round/214447)

## Testmerges:
[#77307: 'Revert "Bumps rust-g to `3.0.0` "' by MrStonedOne at commit 8dad0feceb](https://www.github.com/tgstation/tgstation/pull/77307)
[#78217: 'Pipe gas visuals' by ninjanomnom at commit 63053a67b0](https://www.github.com/tgstation/tgstation/pull/78217)
[#77920: '[TEST-MERGE FIRST] Adds synthetic wounds' by nikothedude at commit fe54c54171](https://www.github.com/tgstation/tgstation/pull/77920)

## Reproduction:

1. Go to lavaland in mech
2. Hug one of the rock walls 
3. Realized you are being targeted by watcher laser thing
![wew](https://github.com/tgstation/tgstation/assets/116151419/c8249bd0-9e3b-40fc-97c9-815add056f70)

**Comment by SethLafuente** [comment]
![d7s7Ga2](https://github.com/tgstation/tgstation/assets/84478872/519dc077-558d-4532-a2c5-889cbaf8a083)
![mgVi32F](https://github.com/tgstation/tgstation/assets/84478872/f5172637-4bbd-4f3d-8614-151652521b1b)
Watchers do no longer target you through walls not to mention they no longer have that weird laser ability
