### ISSUE TITLE
`COMSIG_HIT_BY_SABOTEUR` returns a boolean which is improper for signals

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#78297]
## Reproduction:

Signals should not return `TRUE` (or `FALSE`), it should be returning a bitflag.

**Comment by ShizCalev** [comment]
COMPONENT_RIDDEN_STOP_Z_MOVE
COMSIG_CONTAINER_TRY_ATTACH
COMSIG_ATOM_EMAG_ACT
COMSIG_PREQDELETED

**Comment by MrMelbert** [comment]
yeah a lot of the really older signals still do it... need to be updated some day

**Comment by MrMelbert** [comment]
also `/datum/component/container_item` and `/datum/component/container_item/tank_holder` are really bad, like they probably shouldn't be components
