### ISSUE TITLE
northstar can spawn smuggler satchels on its space tiles

### ISSUE THREAD

**Issue by kittysmooch** [tgstation/tgstation#78304]
discovered downstream but then goof said hed take my family hostage if i didnt report it.
## Reproduction:
you know how northstar has a bunch of tiled floors in space? smugglers satchels can spawn under these too. arguably a feature, probably best reported.

**Comment by Addust** [comment]
its realistic, better to smuggle along the hull than inside a fucking hallway where engis will pry up tiles for even the least smidgen of loot
