### ISSUE TITLE
Mech rockets don't blow up when they direct hit soemone

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#78311]
## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/53100513/d2dbabda-d4a7-470d-8014-e6f9de0c5cba)

Fiore rocket at man

It cracks his chest

Fire rocket near man
It blows up

**Comment by Sealed101** [comment]
what were the mech and the rockets used
because robotics only has access to anti-materiel rockets and not anti-everything
- #70813

**Comment by Serxule** [comment]
yeah, i doubt this is a bug, you need the SRM-8 missiles to explode people, the BRM-6 are for destroying defenses/mechs, SRM was removed from the lathe as it would 1 shot/nugget people

**Comment by cnleth** [comment]
The rocket used here is a PEP missile which only explodes when it hits structures or silicons
