### ISSUE TITLE
Medical Cyborgs cannot cauterize a stomach pump surgery.

### ISSUE THREAD

**Issue by MiniMeatwad** [tgstation/tgstation#78329]
## Testmerges: 

[#78217: 'Pipe gas visuals' by ninjanomnom at commit 63053a67b0](https://www.github.com/tgstation/tgstation/pull/78217)
[#77307: 'Revert "Bumps rust-g to `3.0.0` "' by MrStonedOne at commit 8dad0feceb](https://www.github.com/tgstation/tgstation/pull/77307)

## Reproduction:

Use a cautery on a stomach pump surgery as a cyborg to try to cancel it, instead you will stomach pump. This means you cannot cauterize the torso.

**Comment by timothymtorres** [comment]
Duplicate of #48941
