### ISSUE TITLE
syndie medibot oppenheimer gets insta killed by turrets when possessed by player

### ISSUE THREAD

**Issue by thematycer** [tgstation/tgstation#78343]
## Reproduction:

When a player spawns as Oppenheimer on syndie ship, the bot is no longer considered as part of a syndicate faction (if the bot was in it in a first place)and turrets attack it. Seems like an oversight.

**Comment by necromanceranne** [comment]
The bot is going to need the syndicate faction if we don't want it being blown away by the turrets.
