### ISSUE TITLE
Baking raw pastry base makes horible things

### ISSUE THREAD

**Issue by HalfPunch** [tgstation/tgstation#78388]
Reporting client version: 514.1589

## Round ID:
[214705](https://scrubby.melonmesa.com/round/214705)

## Reproduction:
Try bake pastry base in oven
First of all it can't be baked or burned and does this
![image](https://github.com/tgstation/tgstation/assets/91390177/86ab3dc7-ad94-48be-8ea3-7f730d96eea6)
Second - You can open oven and see that pastry didn't disapeared/burned/baked/multiplied(it's third part).
![image](https://github.com/tgstation/tgstation/assets/91390177/fe430f9b-4180-44f1-9f07-b42fdb7a15ce)
Third - Game lag will spike if you leave pastry in oven like if there was "exponentially multiplying stuff" happening.
You can't really play the game if you see ovens

**Comment by MrMelbert** [comment]
Should have been fixed by #78372 ?

**Comment by SyncIt21** [comment]
No longer reproducible on local
