### ISSUE TITLE
Issue with botany in tramstation (maybe in other stations)

### ISSUE THREAD

**Issue by Gyrazu** [tgstation/tgstation#78389]
## Reproduction:

I was plating as botany (my main role) and several sprites an interactions were broken. For example tower caps and cotton. Not only i could not grab the "dark sprite" from the floor, i can pick all i want of that seedless plants. They return NO seeds and can only picked up with the portable seed bag if a "non broken" sprite is in the same title. In the same line, mutations in plants sometime worked, sometimes don't. But with the somatray they did just fine. With mutagen and left4dead no. But can be bad RNG in my part. I'll add a screenshot of the issue, with cotton only. 
![screenshot botany](https://github.com/tgstation/tgstation/assets/145230929/081dd90f-fa0a-4cd4-87fc-abd0a2d743fa)

**Comment by Gyrazu** [comment]
Novaflowers are broken too. No way to use them

**Comment by the-orange-cow** [comment]
Probably related to https://github.com/tgstation/tgstation/issues/78375

From what people are describing, this sounds like something standard no plants that produce non-edible product.
