### ISSUE TITLE
breaking down a borg drops its floor tiles

### ISSUE THREAD

**Issue by Deathfox666** [tgstation/tgstation#78397]
Reporting client version: 514.1589

## Round ID:
[214746](https://scrubby.melonmesa.com/round/214746)

## Testmerges:
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [Pipe gas visuals](https://www.github.com/tgstation/tgstation/pull/78217)

## Reproduction:
1 get a (roundstart)? borg
2 start to wrench the borg down to its parts
3 see floor tiles on the ground and pick them up
4 you now have 100+ floor tiles stuck to your hand?

**Comment by msgerbs** [comment]
This makes sense to me, because it was changed so they use actual material to create actual floor tiles. If they weren't dropped, then dismantling the borg would lose a lot of materials. Unless I'm misunderstanding.
