### ISSUE TITLE
Tower Caps Are Currently Broken

### ISSUE THREAD

**Issue by amenitykitten** [tgstation/tgstation#78401]
**Reporting client version: 514.1589
[Round ID]: [214748](https://scrubby.melonmesa.com/round/214748), Sybil**

## Reproduction:

**The Issue:** 
I planted Tower Cap in soil in the prison on Delta Station, upon it fully maturing, it was infinitely harvestable, yet unable to be interacted with, and produced zero seeds. The resulting tower cap logs could not be cut into wood, nor picked up (except by right clicking it), could not be dragged, and the plant itself infinitely produced logs instead of disappearing after harvest.

1. Plant tower cap seed- for the exact results I got, use the Soil in the Delta Station prison.
2. Ensure it survives to be harvested.
3. Harvest it by hand. When you do this it should appear on the ground, and unable to be picked up by simply clicking on it, you will have to right click it to pick it up. The Tower Caps will, for some reason, be able to be harvested repeatedly. They produce no seeds, they cannot be cut into planks. They simply produce infinite, useless tower cap. According to **That Engineer** the Tower Cap both existed and did not exist, and had to be deleted very manually.

The resulting screenshot of me surrounded by non-interactable towercap.
![Screenshot_1](https://github.com/tgstation/tgstation/assets/78749284/d2bd6dfb-4aea-4fba-8028-e36cad104787)

**Comment by SyncIt21** [comment]
Duplicate #78375

**Comment by Sealed101** [comment]
^
