### ISSUE TITLE
prone snailpeople move at normal running speed 

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#78417]
## Reproduction:
Be snail, lie down, go fast
broken in #76336 I guess

**Comment by Sealed101** [comment]
snail shadow buff

**Comment by ChungusGamer666** [comment]
how the fuck

**Comment by lizardqueenlexi** [comment]
it gets worse! if you replace a snailperson's legs with regular ones they will crawl at somewhere around rush gland speeds.

**Comment by ChungusGamer666** [comment]
> how the fuck

The movespeed modifier should still be applicable while crawling if I am reading the code correctly. 
Just how?
