### ISSUE TITLE
Lavaland mining base waste vents cause unnecessary roundstart processing.

### ISSUE THREAD

**Issue by Pickle-Coding** [tgstation/tgstation#78413]
The passive vents for lavaland's mining bases cause roundstart atmos processing. This could be avoided if the pipenet started with a gas mixture in equilibrium with the planetary air.

**Comment by Sealed101** [comment]
which is randomised each time and why would you have a planet's potentially deadly atmosphere piped into the base's atmospherics system where people tend to breathe

**Comment by Pickle-Coding** [comment]
It's the waste pipenet. People don't breathe from that. The atmosphere is going to get into it because of the passive vent.

**Comment by Sealed101** [comment]
just map injectors in or something idk don't we have anything that can output gas without power
