### ISSUE TITLE
Using the AI rolling malf power at the exact moment you get carded will spawn a duplicate core and allow you to "live" even if you get wiped

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#78416]
see title
roundid 214818

could still use malf powers but couldnt "interact" with stuff like hacking apcs or using vox/announcements, as if i was in a card with the wireless stuff disabled

**Comment by MrMelbert** [comment]
i wonder if this is a `sleep` moment

**Comment by MrMelbert** [comment]
nope, but it appears this timer doesn't sanity check after the time expires

![image](https://github.com/tgstation/tgstation/assets/51863163/5e8e640a-f37e-47ee-bb10-98bb364a473d)

this means it calls `fall_and_crush` regardless of if the AI is in a valid state, which in turn calls `Move`, so it `Move`s... the ai... out of the card

@nikothedude

**Comment by nikothedude** [comment]
what the fuck.

ill fix this when i get a chance
