### ISSUE TITLE
:B:oneless get_corresponding_wound_type doesn't work

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#78437]
## Reproduction:

Try to smite using :B:oneless

Runtime in wounds.dm, line 260: type mismatch: cannot compare 2 to "3"

proc name: get corresponding wound type (/proc/get_corresponding_wound_type)
usr: LT3/(Dustin Brindle)
usr.loc: (Chief Engineer's Office (125,89,2))
src: null
call stack:
get corresponding wound type(/list (/list), the human head (/obj/item/bodypart/head), "3", "3", 1, 1, 0, 1)
Dustin Brindle (/mob/living/carbon/human): cause wound of type and severity("wound_blunt", the human head (/obj/item/bodypart/head), "3", "3", 1, null)
:B:oneless (/datum/smite/boneless): effect(LT3 (/client), Dustin Brindle (/mob/living/carbon/human))
LT3 (/client): Smite(Dustin Brindle (/mob/living/carbon/human))

**Comment by nikothedude** [comment]
cock

**Comment by nikothedude** [comment]
this looks like an isolated issue with the proc

i forgot to use num2text to destringify the severity
