### ISSUE TITLE
Bioscrambler anomaly does not give core after neutralization

### ISSUE THREAD

**Issue by HalfPunch** [tgstation/tgstation#78438]
Reporting client version: 514.1589

## Round ID:
[214887](https://scrubby.melonmesa.com/round/214887)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/91390177/46641293-1141-4816-aae0-17e0b8521cc3)
I used remote signaler and gas analyser to neutralize anomaly
Anomaly gone, but no cores
I am standing right next to the place where anomaly was before neutralization

**Comment by Shadow-Quill** [comment]
Couldn't reproduce in testing.

**Comment by HalfPunch** [comment]
It's common issue on Campbell, i tried this only on anomalies that exist more than 2-3 hours. If i could find another i'll try it again

**Comment by Jacquerel** [comment]
Is it possible that this anomaly was created via the "anomaly releaser" space ruin item? 
That creates immortal anomalies with no cores.

Unfortunately the round you have linked doesn't have logs yet (is it... still running?) so I can't check if it runtimed when trying to create the core. You usually wouldn't be able to defuse a stabilised anomaly with a signaller.

**Comment by HalfPunch** [comment]
> Is it possible that this anomaly was created via the "anomaly releaser" space ruin item? That creates immortal anomalies with no cores.
> 
> Unfortunately the round you have linked doesn't have logs yet (is it... still running?) so I can't check if it runtimed when trying to create the core. You usually wouldn't be able to defuse a stabilised anomaly with a signaller.

It's not running, Campbell broke 8 hours ago. And so is the round

**Comment by Sadboysuss** [comment]
could not reproduce with normal anomalies
