### ISSUE TITLE
Syndicate Modsuit AI doesn't get codespeak

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#78455]
Reporting client version: 514.1589

## Round ID:
[214942](https://scrubby.melonmesa.com/round/214942)

## Testmerges:
- [Pipe gas visuals](https://www.github.com/tgstation/tgstation/pull/78217)
- [Tram v6/Transport Subsystem](https://www.github.com/tgstation/tgstation/pull/78230)

## Reproduction:
Seems that syndicate AI's don't start with codespeak, and as far as I know you can't just use the book on the intellicard to fix that

**Comment by xzero314** [comment]
Adding to this since its from the same round and I was the nuclear op that bought the AI. 

After putting the syndicate ai into my mod suit a new one was able to download into my syndicate intellicard. I could have effectively given every op an ai for free.

**Comment by deathrobotpunch** [comment]
the reusability on the AI might be intentional due to its high price though i’m not sure
