### ISSUE TITLE
Heretic can blink while stunned on the ground

### ISSUE THREAD

**Issue by Zargoar** [tgstation/tgstation#78453]
Reporting client version: 514.1589

## Round ID:
[214926](https://scrubby.melonmesa.com/round/214926)

## Testmerges:
- [Pipe gas visuals](https://www.github.com/tgstation/tgstation/pull/78217)
- [Tram v6/Transport Subsystem](https://www.github.com/tgstation/tgstation/pull/78230)

## Reproduction:
1. Spawn in as heretic with reality phase unlocked.
2. Get stunned by a stun baton.
3. Teleport while stunned on the ground.

**Comment by MrMelbert** [comment]
why would this not be the case, you can jaunt and blink and otherwise cast while stunned

**Comment by Jacquerel** [comment]
You can make a balance PR to change this if you can justify it in the PR body but that would be inconsistent with other jaunt spells, which are usable while stunned (leaving you out of phase but also still totally immobile)

**Comment by Zargoar** [comment]
TIL! 
For whatever reason I recall them operating differently so I filed this.
