### ISSUE TITLE
Spray Painting the SM will dust you, despite never touching it.

### ISSUE THREAD

**Issue by TheMaggotGuy** [tgstation/tgstation#78456]
## Testmerges: Round ID: [214945](https://scrubby.melonmesa.com/round/214945)
BYOND Version: 515.1610
Server revision compiled on: 
Master commit: [1dc9418bcbf6a33fb1668a82a82fa9e5f9c924d1](https://www.github.com/tgstation/tgstation/commit/1dc9418bcbf6a33fb1668a82a82fa9e5f9c924d1)
The following pull requests are currently test merged:
[#78217: 'Pipe gas visuals' by ninjanomnom at commit 039b63564f](https://www.github.com/tgstation/tgstation/pull/78217)
[#78230: 'Tram v6/Transport Subsystem' by lessthnthree at commit f21ce47c98](https://www.github.com/tgstation/tgstation/pull/78230)

Local commit: 93028e012fc576f95b0562f444a0a5b18e0eaad1
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1

**Comment by TheMaggotGuy** [comment]
Beestation and a few other servers already have this fixed, should be easy to port the fix here.

**Comment by timothymtorres** [comment]
Relevant code on how cigarettes interact with the SM:

https://github.com/tgstation/tgstation/blob/85f20e1f4400bab2abbb440194478cec376766bd/code/datums/components/supermatter_crystal.dm#L140-L190

**Comment by TheMaggotGuy** [comment]
thanks! :))))
