### ISSUE TITLE
The Holodeck TCG Battle Arena  Mana Panel is not in the right place

### ISSUE THREAD

**Issue by Gmet1234** [tgstation/tgstation#78466]
## Testmerges: 
[#78217: 'Pipe gas visuals' by ninjanomnom at commit 039b63564f](https://www.github.com/tgstation/tgstation/pull/78217)
[#78230: 'Tram v6/Transport Subsystem' by lessthnthree at commit f21ce47c98](https://www.github.com/tgstation/tgstation/pull/78230)

## Reproduction:

Set the holodeck to TCG Battle Arena and the mana panel is one tile to the left where it should be
![image](https://github.com/tgstation/tgstation/assets/145606503/3fa0bb2d-7ed0-4642-94df-d56a8ed0c103)

**Comment by Singul0** [comment]
![image](https://github.com/tgstation/tgstation/assets/127663818/4685f181-32e0-4460-8bbf-cbbe3dbe7b92)
Works on my machine. ¯\_(ツ)_/¯

**Comment by Gmet1234** [comment]
![image](https://github.com/tgstation/tgstation/assets/145606503/e3ba9fc0-d654-4c9d-9ece-945328bf19ee)
tested again in manuel, it still happens
