### ISSUE TITLE
Breaking a modular console with an intellicarded AI in it instantly deletes the card and AI

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#78467]
## Round ID:
Manuel: 214970

## Reproduction:

1.  Dead AI on intellicard put into RD Console with restorer
2.  AI awakens in restorer
3.  AI convinces a spacecarp that they will feed nonhumans to them if they free them from the console theyve been stuck in with radio off for 10 minutes
4. Carp breaks console
5. AI and intellicard deleted.

**Comment by GPeckman** [comment]
Just tested it, this does in fact occur with laptops as well, not just stationary computers.
