### ISSUE TITLE
Epinephrine no longer heals properly

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#78474]
Reporting client version: 514.1589

## Round ID:
[214999](https://scrubby.melonmesa.com/round/214999)

## Testmerges:
- [[Fuck Shotties] Old Yellers Old Yeller (Improvised Shell Nerf)](https://www.github.com/tgstation/tgstation/pull/78235)

## Reproduction:

Spawn a human
Build mode throw them against a wall a bit or whatever
![image](https://github.com/tgstation/tgstation/assets/3789327/077d1d36-11b1-43b6-8d25-0da997e8317e)
Add 25u epinephrine to them and come back 10u later
![image](https://github.com/tgstation/tgstation/assets/3789327/c6cb17bb-7e7f-41d2-9aaa-182afccadf77)
When the epinephrine runs out they will "update" and recover their full health, however the gradual progressive improvement of health will not be reflected on the character's mob ; e.g. while here we see total 86 brute the overall status is -14% (incorrectly) and the player has a flashing health bar, is horizontal, and crawls, as if in soft crit.

**Comment by GPeckman** [comment]
The issue appears to be located here:

https://github.com/tgstation/tgstation/blob/85f20e1f4400bab2abbb440194478cec376766bd/code/modules/reagents/chemistry/reagents/medicine_reagents.dm#L815-L820

All the adjust damage procs are being passed false as the parameter updating_health instead of true.

**Comment by leaKsi** [comment]
The issue is most likely caused by `return ..()` at the end of `epinephrine/on_mob_life`.

**Comment by GPeckman** [comment]
> Atropine doesn't have this problem.

Huh, I just tested it and you seem to be right about that.

> Simply changing it to return `..() || .` should fix this.

The parent proc in this case will never return anything under any circumstances, so I think just `..()` will work fine.
