### ISSUE TITLE
Ghost of Poly causes endless supermatter resonances

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#78490]
Ghost of Poly doesn't get dusted when touching the supermatter crystal. This causes endless resonances as the ghost bird keeps hitting it.

The crystal shouldn't interact when hit by ghost mobs/godmode mobs.

![image](https://github.com/tgstation/tgstation/assets/83487515/72c2b52b-8257-4b4f-99b2-7e35d1e3b0ce)

## Reproduction:

Put Ghost of Poly in the SM chamber

**Comment by the-orange-cow** [comment]
feature

**Comment by Jackal-boop** [comment]
Feature
