### ISSUE TITLE
Monkeys from monkey cubes have synthetic meat

### ISSUE THREAD

**Issue by HalfPunch** [tgstation/tgstation#78493]
Reporting client version: 514.1589

## Round ID:
[215029](https://scrubby.melonmesa.com/round/215029)

Maybe it does make sense because monkeys were not born in some kind of "organic relationship" but.. then there is no way for chef to get organic meat in large quantities other then cook one half of the crew to feed another half.

## Reproduction:
Take monkey cube, make monkey, make monkey dead, MEAT... wait it's synthetic
![image](https://github.com/tgstation/tgstation/assets/91390177/53540dba-270a-47c1-ae61-398e21288620)

**Comment by Ticklezcat** [comment]
There are still other ways to get meat beyond cubes and crew: cytology, cargo, and breeding station pets give non-synthetic meat I believe.

**Comment by AtomTheProphet** [comment]
> There are still other ways to get meat beyond cubes and crew: cytology, cargo, and breeding station pets give non-synthetic meat I believe.

Breeding pets is terribly inefficient and slow, though.

**Comment by SyncIt21** [comment]
This was an intentional change from the Foodening PR You aren't meant to get organic meat in large amounts this easily anymore forcing you to invest some time in breeding pets.

Although making the meat inedible is definitely a bug

**Comment by BlueMemesauce** [comment]
> This was an intentional change from the Foodening PR You aren't meant to get organic meat in large amounts this easily anymore forcing you to invest some time in breeding pets.
> 
> Although making the meat inedible is definitely a bug

It's not actually inedible, it refers to how the food tastes. Raw meat doesn't taste very good until it is cooled

**Comment by SyncIt21** [comment]
> It's not actually inedible, it refers to how the food tastes. Inedible is the lowest ranking of taste. Raw meat doesn't taste very good until it is cooked

I misunderstood it my bad. In that case this isn't a bug  at all.
