### ISSUE TITLE
hemiplegic quad amputee interaction

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#78505]
Reporting client version: 514.1589

## Round ID:
[215087](https://scrubby.melonmesa.com/round/215087)

## Testmerges:
- [Tram v6/Transport Subsystem](https://www.github.com/tgstation/tgstation/pull/78230)
- [Pipe gas visuals](https://www.github.com/tgstation/tgstation/pull/78217)

## Reproduction:
get both quirks (through hc random)
neither hand can pick up anything, although clicking around your character does turn you around and clicking the face does check your mood
ahelp, so sightid can remove hemiplegic
both hands work again, almost
you still can't use defibs (it says "you need 2 hands" or something similar when you try to separate the paddles)
otherwise appears to be working ok

later in the round, have an arm broken via damage (very easy with the shitty prosthetics)
both arms stop working again
sightid tries very hard for a long time to try to let your hands work again (I don't know precisely what they all tried)
eventually give up and respawn me (although due to hc random, as my static, kludged together back to the moth I was)

**Comment by ChungusGamer666** [comment]
I have no clue how hemiplegic and quad amputee could be interacting at all. This is just weird.
