### ISSUE TITLE
Crew with pacifist quirk cannot defibrillate or repair other's robotic limbs

### ISSUE THREAD

**Issue by Tuckatk** [tgstation/tgstation#78507]
## Testmerges:

- Swing Combat Test Merge (https://github.com/tgstation/tgstation/pull/76928)

## Reproduction:

This occurred when Manual was tested merged with the Swing Combat test merge. There appears to be a issue where someone with the pacifist quirk is unable to defibrillate anybody nor repair other's robotic limbs like a welder. When done correctly, clicking the body, all it does is initiate the hand cooldown with no progress bar for the start of the defibrillation or repair. People without the quirk are still able to do the actions just fine. Unsure how else to detail it but an admin was able to replicate the issue by spawning in as a pacifist.

**Comment by san7890** [comment]
hopefully this is addressed when the whole swing combat thing is brough back for real
