### ISSUE TITLE
Function buttons disappeared (except internals) (only for me)

### ISSUE THREAD

**Issue by WarerBrow** [tgstation/tgstation#78503]
Reporting client version: 514.1589

## Round ID:
[215083](https://scrubby.melonmesa.com/round/215083)

## Testmerges:
- [[Fuck Shotties] Old Yellers Old Yeller (Improvised Shell Nerf)](https://www.github.com/tgstation/tgstation/pull/78235)

## Reproduction:
So uh it was a default shift, I prepared myself for space exploring and put on a MODsuit. Then I noticed that I can't deploy it because buttons didn't show.
![image](https://github.com/tgstation/tgstation/assets/106118256/87a7348c-86c1-4a27-8770-11ad7131639c)
When I have my egun with a seclite attached on me, 5-dot button slides down, but still nuffin'.
![image](https://github.com/tgstation/tgstation/assets/106118256/dc5f7026-52af-40c9-96f2-cc7e36853ec8)
Also, when I have my jetpack on, I can only set internals, but no enabling or stabilizing available. 

I gave my modsuit to a guy just to be sure, and for him it was all working. I also tried wearing 2 different modsuits.
I restarted a couple of times, toggled fullscreen, restarted UI, cleared cache but nothing really worked for me.

**Comment by SyncIt21** [comment]
Duplicate #75578?

**Comment by Sealed101** [comment]
yeah seems like another screen object hard delete
so long as it's linked to the issue above it should help
`[2023-09-22 10:39:02.416] RUNTIME: ## TESTING: GC: -- [0x201ada0] | /atom/movable/screen/movable/action_button was unable to be GC'd -- (ref count of 2)`
