### ISSUE TITLE
Bodies never cool down their body temperature naturally

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#78508]
## Reproduction:

![image](https://github.com/tgstation/tgstation/assets/53100513/f8985792-6cf2-4bdf-ba43-696800db3045)

This poor fucker's body temperatuer was so fucking high it literally outpaced my synthflesh patch factory's output. It went from roughly 233 from my patching to the 600 you see above in teh time it took me as a chemist to get to a surgyery room. 

The issue, and Ive seen this before, is that corpse body temp never goes down for some reason. Thsi sucks and makes treating husks very annoying

**Comment by Serxule** [comment]
this is technically intentional (since a corpse shouldnt be warming itself up/cooling itself down) but the environment itself should definitely change it without requiring drastic temps (eg you can change bodytemp through freezing/burning temps either atmospherically or through a shower)

**Comment by Higgin** [comment]
You can also use cryo on this and hercuri, IIRC.

**Comment by Vincent983** [comment]
or a shower

**Comment by carlarctg** [comment]
> You can also use cryo on this and hercuri, IIRC.

Hercuri on a corpse? bro that aint gona process

**Comment by carlarctg** [comment]
> or a shower

This one makes sense actually. Spacemen dont get the beenfits frmo showering as a nod to realism and players

**Comment by yorii** [comment]
> this is technically intentional (since a corpse shouldnt be warming itself up/cooling itself down) but the environment itself should definitely change it without requiring drastic temps (eg you can change bodytemp through freezing/burning temps either atmospherically or through a shower)

Found an oversight in the code, you could only heat up dead bodies this way, never cool them down. So I PR'ed a quick fix just now.

**Comment by OverwatchVoice** [comment]
Human mains seeing the lizard experience for the first time, I see
