### ISSUE TITLE
Sentient Lavaland Elites do not drop their unique loot, and instead drop the same as non-Sentient Lavaland Elites

### ISSUE THREAD

**Issue by FlamingIceGolem** [tgstation/tgstation#78512]
## Round ID:
[Round ID]: # 215111 

## Reproduction:
I killed what the Admin confirmed to be a Sentient Pandora, which only dropped a Necropolis chest and neither Hope or a Tumor Shard. The confirmation for my words should be in the logs of 215111, I also have some screenshots confirming it was sentient.

![Screenshot 2023-09-23 093609](https://github.com/tgstation/tgstation/assets/59223560/309befa1-5331-49de-be2e-3e0fc360b2ca)

**Comment by Sealed101** [comment]
it's a 50/50 chance for them to drop their special loot when they've been legion core boosted. you've probably just gotten unlucky.
try it a few more times (and don't roll herald)

https://github.com/tgstation/tgstation/blob/a53f614e67722b0ac648486404b79559dcd3153c/code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm#L329-L334

**Comment by SyncIt21** [comment]
Can we close this. We are approaching the famous 1800 + open issue landmark :( and no one is proud of it

**Comment by Sealed101** [comment]
thanks for the grim reminder

anyway during testing the drops were correctly placed in a chest that pops up in place of the tumor when the sentient elite is killed. the oversight here is that the chest requires a key, which arguably could be lifted as a requirement for your boss loot. that's a separate issue though
