### ISSUE TITLE
Syndicate Lavaland now has free lava traversal via its MODsuit

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#78557]
Reporting client version: 514.1589

## Round ID:
[215228](https://scrubby.melonmesa.com/round/215228)

The Ionic Jump Jet allows the agents to achieve zero-G, which can be used to Tactically Abscond. Holy fucking shit.

## Reproduction:

1. join syndie lavaland
2. take modsuit
3. activate jump jet
4. activate jetpack
5. off to the other side

**Comment by Jacquerel** [comment]
They should uh, probably use a different suit preset 😅

**Comment by Addust** [comment]
i once tested this on live server, tried to go back, and fell in the fucking lava because i didnt do another ionic jump jet thing
