### ISSUE TITLE
Funny graphical bug with ovens

### ISSUE THREAD

**Issue by HalfPunch** [tgstation/tgstation#78552]
Reporting client version: 514.1589

## Round ID:
[215180](https://scrubby.melonmesa.com/round/215180)

## Reproduction:
1.Open
![image](https://github.com/tgstation/tgstation/assets/91390177/c4edb6ad-e9b3-459e-956e-868427806ab3)
2. Take oven tray
3. Return
4. Close
![image](https://github.com/tgstation/tgstation/assets/91390177/38bf34b2-69ca-42d0-b3aa-86229852e8c8)
5. Ha ha he he

**Comment by SethLafuente** [comment]
![GboLX6U](https://github.com/tgstation/tgstation/assets/84478872/f12a0521-2618-43fc-a50b-ccdc09044afb)
As shown above no longer a bug, opened, took tray returned it and closed it and it ended up where it should
