### ISSUE TITLE
AI duplicates if teleported as an intell card

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#78569]
Reporting client version: 514.1589

## Round ID:
[215276](https://scrubby.melonmesa.com/round/215276)

![image](https://github.com/tgstation/tgstation/assets/84478872/4f5e6981-4da1-41b5-883f-b4595e769719)
![image](https://github.com/tgstation/tgstation/assets/84478872/c2fab4c3-cb59-405b-a02c-f654a30e549d)
![image](https://github.com/tgstation/tgstation/assets/84478872/5a85a16e-d730-4a53-8682-2a9a07d14dfb)

Got hit by an AI vending machine style while I carded them teleported myself back before I died which caused the intell card to produce anotehr AI core that hit me again like a vending machine while the AI was still on the intell card

(The AI core on the second image was moved inside the shuttle it was exactly where my engineer corpse is)

## Testmerges:
- [Feature: bitrunner, a new supply role (READY)](https://www.github.com/tgstation/tgstation/pull/77259)
- [Revert "Resolves parallax harddels" test merge to find lag](https://www.github.com/tgstation/tgstation/pull/78457)

**Comment by Sealed101** [comment]
what

**Comment by MrMelbert** [comment]
dupe of #78416 ?

**Comment by SethLafuente** [comment]
> dupe of #78416 ?

I think so
