### ISSUE TITLE
You can become an INVICIBLE Holoparasite with the Polymorph Belt 

### ISSUE THREAD

**Issue by StrangeWeirdKitten** [tgstation/tgstation#78578]
Reported from downstream (Bubberstation) - **Reproduced on TG code**
## Round ID:

N/A

## Testmerges:

I don't play on TG dude...

## Reproduction:

*Polymorph Belt Bugs 2.0 - Electric Bongulo*

- Get a polymorph belt.
- Find a holoparasite
- Scan a holoparasite
- Now you can become a holoparasite without a host

*also I should also mention one small detail*
## YOU'RE FUCKING INVINCIBLE

![image](https://github.com/tgstation/tgstation/assets/95130227/889761f9-39d1-41a1-b9b7-91e248637f9f)

**Comment by Sealed101** [comment]
it has no biotypes to check against, also it doesn't trip sentience i guess? not too familiar with how we classify sentience but there's that

https://github.com/tgstation/tgstation/blob/99f4d6bb56820aa1ff226d2ef4efaf90e2381726/code/modules/mob/living/simple_animal/guardian/guardian.dm#L9

https://github.com/tgstation/tgstation/blob/99f4d6bb56820aa1ff226d2ef4efaf90e2381726/code/modules/clothing/belts/polymorph_belt.dm#L54-L84

**Comment by StrangeWeirdKitten** [comment]
> it has no biotypes to check against, also it doesn't trip sentience i guess? not too familiar with how we classify sentience but there's that
> 
> 
> 
> https://github.com/tgstation/tgstation/blob/99f4d6bb56820aa1ff226d2ef4efaf90e2381726/code/modules/mob/living/simple_animal/guardian/guardian.dm#L9
> 
> 
> 
> https://github.com/tgstation/tgstation/blob/99f4d6bb56820aa1ff226d2ef4efaf90e2381726/code/modules/clothing/belts/polymorph_belt.dm#L54-L84

Every day we inch closer to my desire for a mob blacklist tag you can slap onto something. It would probably fix a lot of these once in a while niche cases and you could probably blacklist slime core extracts interactions from head slugs to

**Comment by Sealed101** [comment]
this is an expected oversight popup because mob biotypes can be places nilly-willy; implementing a hard blacklist is sad

we can just stick `MOB_SPECIAL` on guardians and it should be fine, it's basically only used for special no-fun-allowed mobs

**Comment by Sealed101** [comment]
oh yeah regenerative black core on ling headcrabs should probably be fixed too but w/e

**Comment by Jacquerel** [comment]
it should probably have `SENTIENCE_HUMANOID` too in that it's an exclusively player-controlled humanoid mob.

**Comment by gueba14** [comment]
The still open?

**Comment by Sealed101** [comment]
thi is still open.

**Comment by ATH1909** [comment]
> oh yeah regenerative black core on ling headcrabs should probably be fixed too but w/e

this got deliberately turned into a feature with code for it, IIRC
