### ISSUE TITLE
Multiple Bitrunner servers don't spread loot

### ISSUE THREAD

**Issue by IgiariValkyr** [tgstation/tgstation#78571]
## Reproduction:
Having multiple bitrunner server/pod sets do not share loot. Crates are sent solely to the station drop-zone rather than nearby the server that the crate was pulled from.

_I personally do understand that this is because there was never meant to be multiple servers running at once other than the original, but during the excitement for testing such a pull, we tried a direct mirror pull and went ham with it. This resulted in us finding this slight issue._

**Comment by Sealed101** [comment]
[![parenting](https://user-images.githubusercontent.com/39163353/198381160-f0aa7fc4-4f2d-486f-8b33-44a1965e2ad1.svg)](https://media.oglaf.com/comic/parenting.jpg)

we should really get a bitrunners milestone at this point

**Comment by jlsnow301** [comment]
Crates are sent to the nearby landmark. Did you pile them all in the same room?

**Comment by StrangeWeirdKitten** [comment]
> Crates are sent to the nearby landmark. Did you pile them all in the same room?

No, I belive (from what someone told me when I asked them to look at the code) that all the machines are bound to only give credit and loot inside the bitrunner area. (I don't know if this is intentional) These were created in locations ranging from the cargo lobby, bar, and lavaland. 

They're also not on the tech tree. (also, I don't know if this is intentional)

**Comment by jlsnow301** [comment]
you can have multiple working, i've tested this on high pop with other admins. i'm assuming you were spawning them in, so you would just need to spawn the station landmark for any individual server to properly generate caches. here's the actual code:

```
#define MAX_DISTANCE 4 // How far crates can spawn from the server
/obj/machinery/quantum_server/proc/locate_receive_turfs()
	for(var/obj/effect/landmark/bitrunning/station_reward_spawn/spawner in GLOB.landmarks_list)
		if(IN_GIVEN_RANGE(src, spawner, MAX_DISTANCE))
			receive_turfs += get_turf(spawner)
			qdel(spawner)

	return length(receive_turfs) > 0
```
whenever the first domain is completed the server looks for the landmark within 4 tiles.

> They're also not on the tech tree. (also, I don't know if this is intentional)

yes. it does not seem to create lag but i do not want to create hallways full of servers. very quick way to get this outright deleted from the codebase.

**Comment by StrangeWeirdKitten** [comment]
> you can have multiple working, i've tested this on high pop with other admins. i'm assuming you were spawning them in, so you would just need to spawn the station landmark for any individual server to properly generate caches. here's the actual code:
> 
> ```
> #define MAX_DISTANCE 4 // How far crates can spawn from the server
> /obj/machinery/quantum_server/proc/locate_receive_turfs()
> 	for(var/obj/effect/landmark/bitrunning/station_reward_spawn/spawner in GLOB.landmarks_list)
> 		if(IN_GIVEN_RANGE(src, spawner, MAX_DISTANCE))
> 			receive_turfs += get_turf(spawner)
> 			qdel(spawner)
> 
> 	return length(receive_turfs) > 0
> ```
> 
> whenever the first domain is completed the server looks for the landmark within 4 tiles.
> 
> > They're also not on the tech tree. (also, I don't know if this is intentional)
> 
> yes. it does not seem to create lag but i do not want to create hallways full of servers. very quick way to get this outright deleted from the codebase.

From a gameplay perspective. This makes them completely irreplaceable and could perhaps be something you order from cargo instead with the ability to place down a landmark and link it. 

I get the hallway full of pods-type stuff, but I suppose that will naturally happen when it's a huge, and admittedly pretty fun game interaction. However, if you give it a few rounds, people will slowly get through everything and find something admittedly more rewarding or worthwhile to do. But this isn't really the point of this bug report.
