### ISSUE TITLE
bitrunner pod "captain" preset gives you a station renamer at the start of the shift

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#78575]
roundID 215287
select the captain outfit on the bitrunning pod, go in

![image](https://github.com/tgstation/tgstation/assets/105343481/536b23ae-41b4-425f-9411-21c575678518)

**Comment by ArcaneDefence** [comment]
epic

**Comment by Serxule** [comment]
should be a feature because its funny (and only works at the start of the shift)

**Comment by jlsnow301** [comment]
Unexpected also what in the world where they thinking while making that spawner

**Comment by jlsnow301** [comment]
Read this wrong initially. Easier to fix now, I'll add it to the hotfix pr

**Comment by jlsnow301** [comment]
Not able to produce this on local as it's not spawning any of the captain gear on load.
