### ISSUE TITLE
Lavaland shuttle flung me into lava

### ISSUE THREAD

**Issue by MoffNyan** [tgstation/tgstation#78634]
Reporting client version: 514.1589

## Round ID:
[215456](https://scrubby.melonmesa.com/round/215456)

## Testmerges:
- [Tram v6/Transport Subsystem](https://www.github.com/tgstation/tgstation/pull/78230)
- [Pipe gas visuals](https://www.github.com/tgstation/tgstation/pull/78217)
- [adds boxes of bandages, and bandages to go in them](https://www.github.com/tgstation/tgstation/pull/78406)

## Reproduction: I heading down to the lavaland shuttle that heads back to the main base, when suddenly it was called by someone else at the same time. The firelock doors shut on me, and then I somehow was flung out through the wall and into lava outside of the shuttle (I think I did press up). Died and immediately husked.
It happened too quickly for me to react and I don't know if I made any extra button presses during this moment, but I do remember seeing my character fly through the wall. I don't know if it was a freak accident or reproducible either...

**Comment by Sealed101** [comment]
nothing to suggest admemery or an attack in the logs, maybe the shuttle's hyperspace pull got triggered prematurely somehow?
