### ISSUE TITLE
Dimensional anomaly fucks up everything on a wall

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#78643]
Reporting client version: 514.1589

## Round ID:
[215486](https://scrubby.melonmesa.com/round/215486)

## Testmerges:
- [ArCargo: Adds the Galactic Materials Stock Market V1.2 (Free Market Edition)](https://www.github.com/tgstation/tgstation/pull/78500)

## Reproduction:

1. dimensional anomaly
2. it hits a wall with an APC
3. your lighting priveleges be gone
<img width="52" alt="image" src="https://github.com/tgstation/tgstation/assets/80979251/65b8c4f9-0097-4e8f-b9b2-ccfcb29e2969">

**Comment by SyncIt21** [comment]
Related #73885
