### ISSUE TITLE
Game setup doesn't check job slots changed in preround

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#78645]
Game setup doesn't seem to be checking/properly restricting jobs at roundstart.

## Reproduction:

Set a job that has no available job slots. Even with 'return to lobby if unavailable' is the preference, you'll still get the job that's supposed to be unavailable.

![image](https://github.com/tgstation/tgstation/assets/83487515/48ec8760-bf8d-4164-b5b7-7019d59ff2db)

**Comment by lessthnthree** [comment]
You can also get head jobs apparently, like CE without the proper number of hours etc.

**Comment by Watermelon914** [comment]
Job slots get reset on round pre setup. I wouldn't really call it a bug, but it might be a bit annoying for admins who may want to change the job slots before a round begins.

They can still be changed via config.

**Comment by lessthnthree** [comment]
I'm a dummy and forgot to deadmin.
