### ISSUE TITLE
Swing combat breaks hand labeler

### ISSUE THREAD

**Issue by MoffNyan** [tgstation/tgstation#78656]
Reporting client version: 514.1589

## Round ID:
[215522](https://scrubby.melonmesa.com/round/215522)

## Testmerges:
- [adds boxes of bandages, and bandages to go in them](https://www.github.com/tgstation/tgstation/pull/78406)
- [Pipe gas visuals](https://www.github.com/tgstation/tgstation/pull/78217)
- [Tram v6/Transport Subsystem](https://www.github.com/tgstation/tgstation/pull/78230)
- [(Testing phase only!) Removes click combat, adds swing combat, Removes RNG block, adds active block](https://www.github.com/tgstation/tgstation/pull/76928)

## Reproduction: Turn on hand labeler, use on bookcase to label it. Instead of beautiful high class sorting methods; a cooldown is placed on the labeler with unsatisfying results.
Items can be labelled just fine, you can add and remove labels.
(Also I don't know if this is a good place to add this footnote, but when library's have pre-labelled bookshelves, you cannot remove the pre-existing label and you just add a new label on top. Usually I deconstruct and reconstruct bookshelves to overcome this, not really a big deal.)

**Comment by MrMelbert** [comment]
https://github.com/tgstation/tgstation/pull/76928/commits/b3f442e700f17e28bc2ab36e9d372eabfcca8bef
