### ISSUE TITLE
Hand Timers are blocking Mecha Dual-Fire

### ISSUE THREAD

**Issue by githubuser4141** [tgstation/tgstation#78661]
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [215533](https://scrubby.melonmesa.com/round/215533)
BYOND Version: 515.1610
Server revision compiled on: 
Master commit: [aaf853e83d64816d891bcc50559dc16c35df46d2](https://www.github.com/tgstation/tgstation/commit/aaf853e83d64816d891bcc50559dc16c35df46d2)
The following pull requests are currently test merged:
[#78406: 'adds boxes of bandages, and bandages to go in them' by CoiledLamb at commit 3c7228f147](https://www.github.com/tgstation/tgstation/pull/78406)
[#78217: 'Pipe gas visuals' by ninjanomnom at commit 37a05e3621](https://www.github.com/tgstation/tgstation/pull/78217)
[#78230: 'Tram v6/Transport Subsystem' by lessthnthree at commit c1478d322a](https://www.github.com/tgstation/tgstation/pull/78230)
[#76928: '(Testing phase only!) Removes click combat, adds swing combat, Removes RNG block, adds active block' by MrMelbert at commit c8744bb440](https://www.github.com/tgstation/tgstation/pull/76928)

Local commit: cd5f94a1a94ea718801fac77d736096e39904388
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1

## Reproduction:

Use a mech, equip it with two different weapons/tools. (Cutter, KA for instance.) Attempt to fire both weapons at once, or both weapons in series. Fail, because the egg timers on your hands prevevnt you from doing so.

WTF do I mean by 'hand timer'? These things:

![mecha_hand_timers](https://github.com/tgstation/tgstation/assets/61243846/e2da2afc-a7c2-4abd-a56a-ee37716ed28a)

**Comment by SyncIt21** [comment]
It's obviously intentional then since there is a clean UI showing what's happening and there are no runtimes to report. Probably done for balance reasons so mechs don't go ham when dual wielded.

No bug to fix here. If you don't like this then create a balance PR to remove it.

**Comment by Jacquerel** [comment]
> It's obviously intentional then since there is a clean UI showing what's happening and there are no runtimes to report. Probably done for balance reasons so mechs don't go ham when dual wielded.
> 
> No bug to fix here. If you don't like this then create a balance PR to remove it.

I don't think this is necessarily obviously intentional, if it isn't behaviour on normal tg and is during this testmerge it's probably an oversight.

**Comment by githubuser4141** [comment]
> It's obviously intentional then since there is a clean UI showing what's happening and there are no runtimes to report. Probably done for balance reasons so mechs don't go ham when dual wielded.
> 
> No bug to fix here. If you don't like this then create a balance PR to remove it.

So, after playing for a bit, I think it's caused by the combat AoE PR that adds hack and slash melee. So. It's not mentioned anywhere in that PR that it changes mech balance. It's also not really relevant they'd change *mech ranged weapons* in a PR that doesn't touch mechs at all, and it wasn't a thing before the AoE melee PR. 

It's a quoted feature in the mech rebalance PR that added it.
https://github.com/tgstation/tgstation/pull/65375

![mech_cooldown_arm](https://github.com/tgstation/tgstation/assets/61243846/3f2a1aeb-c157-45ba-947f-f9e971b99bfd)

**Comment by SyncIt21** [comment]
This still a bug? The test merge was closed a while back

**Comment by Sadboysuss** [comment]
the pr is merged now
