### ISSUE TITLE
Can't resize font, all font with "font override" toggled is same size, even things that should be big.

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#78692]
Reporting client version: 514.1589

## Round ID:
[215749](https://scrubby.melonmesa.com/round/215749)

## Testmerges:
- [ArCargo: Adds the Galactic Materials Stock Market V1.2 (Free Market Edition)](https://www.github.com/tgstation/tgstation/pull/78500)

## Reproduction:
Stuff like announcements, loud voice on comms is in small font with option "Override font size" toggled. You can't change font size without toggling it, so you're either stuck with super small font, or with everything being same size.
This broke it probably https://github.com/tgstation/tgstation/pull/78621

**Comment by lessthnthree** [comment]
I think it's an oversight with how it's implemented. Various message spans should have a font size that's specified as a scale of the original, ie userdanger or w/e being 3x the normal size, whatever the player has set as 'normal' be it 14px or 20px.

That's the only way it'll be consistent between players at high resolutions where the hardcoded sizes are too small, or if you like small fonts they may be too big.

**Comment by distributivgesetz** [comment]
Intentional oversight because at the time I did not know a better way to implement font scaling
