### ISSUE TITLE
ling disguise objective can apply to plasmamen

### ISSUE THREAD

**Issue by SinfulBliss** [tgstation/tgstation#78694]
Round ID: [215716](https://scrubby.melonmesa.com/round/215716)

Testmerges: https://github.com/tgstation/tgstation/pull/61928
https://github.com/tgstation/tgstation/pull/77021

Reproduction: Basically lings can still get the disguise objective for plasmamen but can't disguise as plasmamen anymore
https://i.imgur.com/plVJFKz.png

**Comment by Sealed101** [comment]
Duplicate of #60088

**Comment by Sealed101** [comment]
well not a perfect one but you get the idea
