### ISSUE TITLE
not getting achievments

### ISSUE THREAD

**Issue by terracat474** [tgstation/tgstation#78697]
## Reproduction:
step 1: try getting an achievment (tested: tendril exterminator, legendary miner, bowl'd new world)
step 2: do the thing that needs to be done
step 3: see error
admin said recent prs bugged this, idk. Please fix, i want to be a completionist.

**Comment by Sealed101** [comment]
why give testmerges but not give a round id
(provide a round id so we could have a look at runtimes if there's any)

**Comment by terracat474** [comment]
> why give testmerges but not give a round id (provide a round id so we could have a look at 
> 
I didnt get it but it was a nukie round on icebox literally an hour ago, my IC name was Talon Bulldog
> also what do you mean by step 3? did you see an error message?
> 
See error, i.e see that there's nothing happening. No chat message, nothing in end round report, nothing in achievment tab
> also also are you sure you've met the actual requirements of the cheevos listed?
> 
I'm quite sure that the bowl'd new world was met the requirement (i was drowned in the toilet, no succumbing) plus iirc legendary miner only requires you get the level and the cape so that too
In the worst case, go kill a tendril on lavaland without this achiv. You still won't get it.
> also also also sorry to break it to you but judging by the cheevo scores we haven't had a completionist in over 4 years of the cheevo framework existing, you'd have a real hard time doing this
>
A man can dream

**Comment by Sealed101** [comment]
bowl'd one is kinda finicky i think as you need to suffocate, not get brutalized by the swirlie.. or something, i don't recall exactly

the miner cheevo is done by breaking a Very strong rock/an ancient rock from the elephant graveyard or battle site ruins... and icebox does not spawn either of those, unless the wendigo arena has them (probably not though)
the tendril cheevo is granted when every single tendril on lavaland is destroyed... and you played on icebox. i think the cheevo just doesn't work on icebox.

you've got two and a half of those wrong, try getting some other cheevos. round [215759](https://tgstation13.download/parsed-logs/terry/data/logs/2023/09/30/round-215759/) did not show any errors that would point to cheevos not working, except a query runtime, though they seem to relate to your adminhelps instead

<details><summary>i'll stick em here for archiving i suppose</summary>
```
[2023-09-30 20:19:26.060] RUNTIME: runtime error: Attempting to create a new db query during the world shutdown
 - proc name: NewQuery (/datum/controller/subsystem/dbcore/proc/NewQuery)
 -   source file: code/controllers/subsystem/dbcore.dm,353
 -   usr: the mi-go (/mob/dead/observer)
 -   src: Database (/datum/controller/subsystem/dbcore)
 -   usr.loc: the shuttle floor (63,117,4) (/turf/open/floor/mineral/titanium/blue)
 -   call stack:
 - Database (/datum/controller/subsystem/dbcore): NewQuery("\n\t\tINSERT INTO ticket (tick...", /list (/list), 0)
 - Blackbox (/datum/controller/subsystem/blackbox): LogAhelp(9, "Disconnected", "Client disconnected", "terrariola", null, 0)
 - /datum/admin_help_tickets (/datum/admin_help_tickets): ClientLogout(Terrariola (/client))
 - /datum/admin_help_tickets (/datum/admin_help_tickets): ClientLogout(Terrariola (/client))
 - Terrariola (/client): Destroy()
 - Terrariola (/client): Del()
 - 
[2023-09-30 20:19:26.062] RUNTIME: runtime error: Cannot execute null.Execute().
 - proc name: LogAhelp (/datum/controller/subsystem/blackbox/proc/LogAhelp)
 -   source file: code/controllers/subsystem/blackbox.dm,312
 -   usr: the mi-go (/mob/dead/observer)
 -   src: Blackbox (/datum/controller/subsystem/blackbox)
 -   usr.loc: the shuttle floor (63,117,4) (/turf/open/floor/mineral/titanium/blue)
 -   call stack:
 - Blackbox (/datum/controller/subsystem/blackbox): LogAhelp(9, "Disconnected", "Client disconnected", "terrariola", null, 0)
 - /datum/admin_help_tickets (/datum/admin_help_tickets): ClientLogout(Terrariola (/client))
 - /datum/admin_help_tickets (/datum/admin_help_tickets): ClientLogout(Terrariola (/client))
 - Terrariola (/client): Destroy()
 - Terrariola (/client): Del()
 - 
```
</details>

**Comment by terracat474** [comment]
I don't think all these achievements (especially the tendril one) have these retarded obscure ways to get them. Double check pls
And i've tried the tendril one on lavaland, didnt get that round id but it was the round right before the icebox. So yk

**Comment by Sealed101** [comment]
i didn't warn you for no raisin... 

tendril cheevo
https://github.com/tgstation/tgstation/blob/a51efa3e583e2cc219f48ac51bd13d0bfd1afd3f/code/game/objects/structures/lavaland/necropolis_tendril.dm#L52-L67

miner cheevo
https://github.com/tgstation/tgstation/blob/a51efa3e583e2cc219f48ac51bd13d0bfd1afd3f/code/game/turfs/closed/minerals.dm#L802-L821

bowl cheevo (i just think it's finicky to get, oxy damage tracking could be unreliable) 
https://github.com/tgstation/tgstation/blob/a51efa3e583e2cc219f48ac51bd13d0bfd1afd3f/code/game/objects/structures/watercloset.dm#L40-L57

**Comment by terracat474** [comment]
this is utterly retarded. Who in the world did this shit
